<a href="https://colab.research.google.com/github/ankit-rathi/Quantvesting_v2/blob/main/myStocks_Portfolio_Analysis.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
'''
!pip install pandas==2.2.2 -qq
!pip install pyxirr -qq
!pip install ta -qq
!pip install yfinance==0.2.59 -qq
'''

'\n!pip install pandas==2.2.2 -qq\n!pip install pyxirr -qq\n!pip install ta -qq\n!pip install yfinance==0.2.59 -qq\n'

In [2]:
# import libraries

import numpy as np
import pandas as pd
import datetime
import warnings
warnings.filterwarnings('ignore')
import yfinance as yfin
import ta
import matplotlib.pyplot as plt
import requests

In [3]:
# notebook start time
import time
import datetime
import pytz

start_time = time.time()

# function to print date timestamp
def print_date_time():
  tz_NY = pytz.timezone('Asia/Kolkata')
  datetime_NY = datetime.datetime.now(tz_NY)
  print("Run date time (IST):", datetime_NY.strftime("%Y-%m-%d %H:%M:%S"))

In [4]:
# function to get booked and reserved amount
def get_amt():
  # fetch the JSON data from the URL
  url = "https://raw.githubusercontent.com/ankit-rathi/Tradevesting_v1/main/data/myPortfolioAmts.json"
  response = requests.get(url)
  pf_amts = response.json()  # parse the JSON data

  # extract values from the JSON
  py_booked_amt_dm = pf_amts["py_booked_amt_dm"]
  py_booked_amt_sv = pf_amts["py_booked_amt_sv"]
  cy_booked_amt_dm = pf_amts["cy_booked_amt_dm"]
  cy_booked_amt_sv = pf_amts["cy_booked_amt_sv"]
  reserve_amt_dm = pf_amts["reserve_amt_dm"]
  reserve_amt_sv = pf_amts["reserve_amt_sv"]

  # perform calculations
  py_booked_amt = py_booked_amt_dm + py_booked_amt_sv
  cy_booked_amt = cy_booked_amt_dm + cy_booked_amt_sv
  reserve_amt = reserve_amt_dm + reserve_amt_sv
  total_booked_amt = py_booked_amt + cy_booked_amt

  return total_booked_amt, reserve_amt, cy_booked_amt, py_booked_amt

gen_output = 0

In [5]:
# function to format the amount
def format_amt(number):
    abs_number = abs(number)

    if abs_number >= 1_00_00_000:  # Crores
        formatted_amt = f"{number / 1_00_00_000:.2f} C"
    elif abs_number >= 1_00_000:  # Lakhs
        formatted_amt = f"{number / 1_00_000:.2f} L"
    elif abs_number >= 1_000:  # Thousands
        formatted_amt = f"{number / 1_000:.2f} K"
    else:
        formatted_amt = f"{number:.2f}"

    return formatted_amt

# function to set start and end date
def get_start_end_date():
  start_date = (datetime.date.today() + datetime.timedelta(days=-365)).strftime('%Y-%m-%d')
  end_date = (datetime.date.today() + datetime.timedelta(days=1)).strftime('%Y-%m-%d')
  return start_date, end_date

# function to fetch my portfolio csv
def get_mypfs_df():
  mypfs_df = pd.read_csv('https://raw.githubusercontent.com/ankit-rathi/Tradevesting_v1/main/data/myPortfolioStocks.csv')
  return mypfs_df

# function to fetch my prospects csv
def get_mypps_df():
  mypps_df = pd.read_csv('https://raw.githubusercontent.com/ankit-rathi/Tradevesting_v1/main/data/myProspectsScrips.csv')
  return mypps_df

# function to fetch screener data
def get_myscreen_df():
  myscreen_df = pd.read_csv('https://raw.githubusercontent.com/ankit-rathi/Tradevesting_v1/main/data/myScreenerDB.csv')
  return myscreen_df

# function to fetch momentum data
def get_myinvmt_df():
  myinvmt_df = pd.read_csv('https://raw.githubusercontent.com/ankit-rathi/Tradevesting_v1/main/data/myInvestments.csv')
  return myinvmt_df

# function to get the stock ids
def get_stock_ids(df_pf):
  stock_n100 = df_pf['Symbol'].unique()

  exclude = ['CADILAHC','MMTC', 'MASFIN']

  stock_ids = df_pf[~df_pf['Symbol'].isin(exclude) ]['Symbol'].unique()

  #mypf = mypf[mypf.Forecast.notnull()]
  #stock_ids = mypf['Symbol'].unique()

  #stock_ids.sort()
  return stock_ids

# get features from screener data
def get_screener_features():
  myscreen_df = get_myscreen_df()
  cols = ['Symbol', 'EPS', 'MedPE', 'ROCE%', 'ROE%', 'CapType']
  return myscreen_df[cols]

# get relative strength
def get_relative_strength(stock_list):

    # Dictionary to store stock tickers and their corresponding percentage price change
    stock_changes = {}

    # Loop through each stock and fetch its price data
    for stock in stock_list:
        try:
            # Download the stock data for the given date range
            stock_data = yfin.Ticker(stock + '.NS').history(period='1mo', interval='1d')[map(str.title, ['open', 'close', 'low', 'high', 'volume'])]

            # Calculate the percentage change for the stock
            if len(stock_data) > 0:
                start_price = stock_data['Close'].iloc[0]
                end_price = stock_data['Close'].iloc[-1]
                percent_change = round(((end_price - start_price) / start_price) * 100, 2)
                stock_changes[stock] = percent_change
            else:
                stock_changes[stock] = np.nan  # If no data is available, set to NaN

        except Exception as e:
            print(f"Error fetching data for {stock}: {e}")
            stock_changes[stock] = np.nan

    # Create a DataFrame with stock tickers and their percentage changes
    df = pd.DataFrame(list(stock_changes.items()), columns=['Symbol', 'Percent_Change'])

    # Drop any stocks with missing data (NaN values)
    df = df.dropna()

    # Calculate the percentile rank based on percentage change
    df['RSP'] = round(df['Percent_Change'].rank(pct=True) * 100, 2)
    cols = ['Symbol', 'RSP']
    df = df[cols]
    # Sort by percentile rank (optional)
    df = df.sort_values(by='RSP', ascending=False).reset_index(drop=True)

    return df

In [6]:
# function to get stock technicals
def stock_prec_dev(stock_symbol):
    #stock_symbol = 'ULTRACEMCO.NS'
    short_window = 20
    mid_window = 50
    long_window = 200
    moving_avg = 'SMA'

    start = datetime.datetime(*map(int, start_date.split('-')))
    end = datetime.datetime(*map(int, end_date.split('-')))

    stock_df = yfin.Ticker(stock_symbol + '.NS').history(period='max', interval='1d')[map(str.title, ['open', 'close', 'low', 'high', 'volume'])]

    stock_df['Max'] = round(max(stock_df['Close']),2)
    stock_df = stock_df[(stock_df.index <= end_date) & (stock_df.index >= start_date)]
    stock_df['200_SMA'] = round(stock_df['Close'].rolling(window = 200, min_periods = 1).mean(),0)
    stock_df['Dev%_200'] = round((stock_df['Close'] - stock_df['200_SMA'])*100/stock_df['200_SMA'],2)
    stock_df.dropna(axis = 0, inplace = True) # remove any null rows

    stock_df['20_SMA'] = stock_df['Close'].rolling(window=20).mean()
    stock_df['50_SMA'] = stock_df['Close'].rolling(window=50).mean()
    stock_df['Symbol'] = stock_symbol

    stock_df['Close'] = round(stock_df['Close'],2)
    stock_df['Min'] = round(min(stock_df['Close']),2)
    stock_df['RSI_14'] = ta.momentum.RSIIndicator(close=stock_df['Close'], window=14).rsi()
    stock_df['RSI_14'] = round(stock_df['RSI_14'],0)
    stock_df['Prev_Close'] = stock_df['Close'].shift(1)
    stock_df.drop(['Open', 'Low', 'High', 'Volume'], axis=1, inplace=True)
    stock_df = stock_df.tail(1)

    max_SMA = max(stock_df['20_SMA'].item(), stock_df['50_SMA'].item(), stock_df['200_SMA'].item())
    min_SMA = min(stock_df['20_SMA'].item(), stock_df['50_SMA'].item(), stock_df['200_SMA'].item())
    ABS_Spread = max_SMA - min_SMA
    stock_df['Spread%'] = round((ABS_Spread / stock_df['200_SMA'].item()) * 100,2)

    return stock_df

# function to compute stock attributes
def get_common_features(stock_ids, df_mypf):

  df_prec_dev = pd.DataFrame()
  df_tmp = get_screener_features()
  df_rs = get_relative_strength(stock_ids)

  for stock_id in stock_ids:
      tmp = stock_prec_dev(stock_id)
      tmp = tmp.reset_index()
      df_prec_dev = pd.concat([df_prec_dev, tmp], ignore_index = True)
  df_prec_dev = pd.merge(df_prec_dev, df_mypf, on= 'Symbol')
  df_prec_dev = pd.merge(df_prec_dev, df_tmp, on= 'Symbol', how='left')
  df_prec_dev = pd.merge(df_prec_dev, df_rs, on= 'Symbol', how='left')
  #print(df_prec_dev.columns)
  df_prec_dev['Curr_PE'] = round(df_prec_dev['Close']/df_prec_dev['EPS'],1)
  df_prec_dev['Dev%_PE'] = round((df_prec_dev['Curr_PE'] - df_prec_dev['MedPE'])*100/df_prec_dev['MedPE'],2)
  df_prec_dev['Conviction'] = df_prec_dev['Conviction'] + '-' + df_prec_dev['CapType']
  return df_prec_dev

# function to arrange stock features
def arrange_features(df_stocks, common_cols, diff_cols):
  df_stocks_common = df_stocks[common_cols].drop_duplicates()
  df_stocks_diff = df_stocks[diff_cols]
  df_stocks_diff['Investment'] = df_stocks_diff['AvgCost'] * df_stocks_diff['Shares']
  df_stocks_diff = df_stocks_diff.groupby(['Symbol'])[['Shares', 'Investment']].aggregate(['sum']).reset_index()
  df_stocks_diff.columns = ['Symbol', 'Shares', 'Investment']
  df_stocks_diff['AvgCost'] = round(df_stocks_diff['Investment']/df_stocks_diff['Shares'],2)
  df_stocks = pd.merge(df_stocks_diff, df_stocks_common, on='Symbol')
  return df_stocks

# plot fact distribution across dimension
def plot_pie_chart(df, dimension, fact):
  # grouping the data by category and calculating the sum of fact for each type
  grouped_data = df.groupby(dimension)[fact].sum()

  # sorting the grouped data in descending order
  grouped_data = grouped_data.sort_values(ascending=False)

  # creating a pie chart
  grouped_data.plot.pie(autopct='%1.1f%%', startangle=90, figsize=(6, 6))

  # adding a title and displaying the plot
  plt.title(f'{dimension} {fact} Distribution')
  plt.ylabel('')  # To hide the y-label
  plt.show()

In [7]:
# function to get portfolio features

def get_portfolio_features(df_common_features):

  print_date_time()
  print('-------------------')

  #df_common_features["Target"] = df_common_features["Target"].fillna(df_common_features["Max"])
  df_common_features['NTT'] = np.where(df_common_features['Strategy']== 'NTT', df_common_features["Target"], df_common_features['Max'])
  df_common_features['LTT'] = np.where(df_common_features['Strategy']== 'BTT', df_common_features["Target"], df_common_features['Max'])
  df_common_features['BOL'] = df_common_features['Min']

  tmp_df = df_common_features[df_common_features['Symbol'].isin(mypf_df[mypf_df['InPortfolio'] != 'NA'].Symbol.values)]
  print('qualified stocks: '+str(len(tmp_df['Symbol'].unique())))
  tmp_df1 = tmp_df[tmp_df['LatestQtr'] == 1]
  print('with latest results: '+str(len(tmp_df1['Symbol'].unique())))
  tmp_df1 = tmp_df1[tmp_df1['StarStock'] == 1]
  print('still star stocks: '+str(len(tmp_df1['Symbol'].unique())))
  tmp_df['Investment'] = tmp_df['AvgCost'] * tmp_df['Shares']
  tmp_df['Current'] = round(tmp_df['Close'] * tmp_df['Shares'],0)
  tmp_df['Previous'] = tmp_df['Prev_Close'] * tmp_df['Shares']
  tmp_df['EstimatedST'] = tmp_df['NTT'] * tmp_df['Shares']
  tmp_df['EstimatedLT'] = tmp_df['LTT'] * tmp_df['Shares']
  tmp_df['Current P/L'] = round((tmp_df['Current'] - tmp_df['Investment']),0)
  tmp_df['Today P/L%'] = round((tmp_df['Current'] - tmp_df['Previous'])*100/tmp_df['Previous'],2)
  tmp_df['Current P/L%'] = round((tmp_df['Current'] - tmp_df['Investment'])*100/tmp_df['Investment'],2)
  tmp_df['EstimatedST P/L%'] = round((tmp_df['EstimatedST'] - tmp_df['Investment'])*100/tmp_df['Investment'],2)
  tmp_df['EstimatedLT P/L%'] = round((tmp_df['EstimatedLT'] - tmp_df['Investment'])*100/tmp_df['Investment'],2)
  tmp_df['NTT%'] = round((tmp_df['NTT'] - tmp_df['Close'])*100/tmp_df['Close'],2)
  tmp_df['LTT%'] = round((tmp_df['LTT'] - tmp_df['Close'])*100/tmp_df['Close'],2)
  tmp_df['Gained%'] = round((tmp_df['Close'] - tmp_df['BOL'])*100/tmp_df['BOL'],2)
  investment = round(sum(tmp_df['AvgCost']*tmp_df['Shares']),0)
  current = round(sum(tmp_df['Close']*tmp_df['Shares']),0)
  tmp_df['InitAlloc%'] = round(tmp_df['Investment']*100/investment,2)
  tmp_df['CurrAlloc%'] = round(tmp_df['Current']*100/current,2)
  tmp_df['FTT'] = tmp_df['LTT']
  tmp_df.loc[tmp_df['Strategy'] == 'NTT', 'FTT'] = tmp_df['NTT']
  tmp_df['FTT%'] = tmp_df['LTT%']
  tmp_df.loc[tmp_df['Strategy'] == 'NTT', 'FTT%'] = tmp_df['NTT%']
  tmp_df['FTT Amt'] = round(tmp_df['FTT%'] * tmp_df['Current']/100,0)
  tmp_df['OTT%'] = round((tmp_df['FTT'] - tmp_df['AvgCost'])*100/tmp_df['AvgCost'],2)
  tmp_df['RRR Ind'] = round(tmp_df['Current P/L']/tmp_df['FTT Amt'],2)
  tmp_df['Risk Ind'] = round(tmp_df['Current P/L%']*tmp_df['CurrAlloc%'],0)

  return tmp_df

# function to print portfolio features
def print_portfolio_stats(df_portfolio_features, myinvmt_df):
  from pyxirr import xirr

  total_booked_amt, reserve_amt, cy_booked_amt, py_booked_amt = get_amt()

  dates = myinvmt_df['Date'].values
  dates = np.append(dates, datetime.date.today().strftime('%d-%b-%y'))
  investment = myinvmt_df['Investment'].values
  dates= pd.to_datetime(dates)

  current = round(sum(df_portfolio_features['Close']*df_portfolio_features['Shares']),0) + reserve_amt
  investment_xirr = np.append(investment, current)
  cagr = round(xirr(pd.DataFrame({"dates": dates, "amounts": investment_xirr}))*100,2)

  investment = -sum(investment)
  invested = round(sum(df_portfolio_features['AvgCost']*df_portfolio_features['Shares']),0) + reserve_amt
  previous = round(sum(df_portfolio_features['Prev_Close']*df_portfolio_features['Shares']),0) + reserve_amt
  cy_invested = investment + py_booked_amt

  today_pnl_amount = current-previous
  today_pnl_percentage = round((current-previous)*100/previous,2)

  curr_pnl_amount = current-invested
  curr_pnl_percentage = round((curr_pnl_amount)*100/(cy_invested),2)

  cy_pnl_amount = cy_booked_amt + curr_pnl_amount
  cy_pnl_percentage = round((cy_pnl_amount)*100/cy_invested,2)

  overall_pnl_amount = total_booked_amt + curr_pnl_amount
  overall_pnl_percentage = round((overall_pnl_amount)*100/investment,2)

  estimate_st = round(sum(df_portfolio_features['FTT']*df_portfolio_features['Shares']),0)  + reserve_amt
  est_st_pnl_amount = estimate_st-current
  est_st_pnl_percentage = round((est_st_pnl_amount)*100/current,2)

  estimate_lt = round(sum(df_portfolio_features['LTT']*df_portfolio_features['Shares']),0)  + reserve_amt
  est_lt_pnl_amount = estimate_lt-current
  est_lt_pnl_percentage = round((est_lt_pnl_amount)*100/current,2)

  total_profit = round(sum(df_portfolio_features[df_portfolio_features['Current P/L%'] > 0]['Current']) - sum(df_portfolio_features[df_portfolio_features['Current P/L%'] > 0]['Investment']),0)
  total_loss = round(sum(df_portfolio_features[df_portfolio_features['Current P/L%'] < 0]['Current']) - sum(df_portfolio_features[df_portfolio_features['Current P/L%'] < 0]['Investment']),0)

  cy_booked_percentage = round((cy_booked_amt)*100/current,2)
  py_booked_percentage = round((py_booked_amt)*100/investment,2)
  total_booked_percentage = round((total_booked_amt)*100/investment,2)

  print('-------------------')
  print('Initial Investment: ', format_amt(investment))
  print('CY Investment: ', format_amt(cy_invested))
  print('Reserve: ', format_amt(reserve_amt))
  print('Current: ',  format_amt(current))
  print('-------------------')
  print('Today PnL: '+ '{} ({}%)'.format(format_amt(today_pnl_amount), today_pnl_percentage))
  print('Current PnL: '+ '{} ({}%)'.format(format_amt(curr_pnl_amount), curr_pnl_percentage))
  print('CY Booked + Current PnL: '+ '{} ({}%)'.format(format_amt(cy_pnl_amount), cy_pnl_percentage))
  print('-------------------')
  print('Total profit: ', format_amt(total_profit))
  print('Total loss: ', format_amt(total_loss))
  print('-------------------')
  print('Total Booked + Current PnL: '+ '{} ({}%)'.format(format_amt(overall_pnl_amount), overall_pnl_percentage))
  print('Total Booked PnL: '+ '{} ({}%)'.format(format_amt(total_booked_amt), total_booked_percentage))
  print('Curr Year Booked PnL: '+ '{} ({}%)'.format(format_amt(cy_booked_amt), cy_booked_percentage))
  print('Prev Year Booked PnL: '+ '{} ({}%)'.format(format_amt(py_booked_amt), py_booked_percentage))
  print('===================')
  print('Est FTT: ',  format_amt(estimate_st))
  print('Est FTT PnL: '+ '{} ({}%)'.format(format_amt(est_st_pnl_amount), est_st_pnl_percentage))

  print('===================')
  print('Deployed: ', format_amt(investment))

  print('Current: ', format_amt(current))

  print('CAGR/XIRR %: '+'{}%'.format(cagr))

In [8]:
# get start and end date
start_date, end_date = get_start_end_date()

# get portfolio and prospects data
mypfs_df = get_mypfs_df()
mypps_df = get_mypps_df()
myinvmt_df = get_myinvmt_df()

# merge above datasets
mypf_df = pd.merge(mypfs_df, mypps_df, on="Symbol")

# seggregate dm and sv portfolio
dm_pf = mypf_df[mypf_df['InPortfolio'] == 'DM']
sv_pf = mypf_df[mypf_df['InPortfolio'] == 'SV']

# build portfolio stock dataframe
dm_stocks = get_stock_ids(dm_pf)
sv_stocks = get_stock_ids(sv_pf)
df_stocks = pd.concat([dm_pf,sv_pf], ignore_index = True)

# arrange common and diff stock features
common_cols = ['Symbol', 'Target', 'Criteria', 'Strategy', 'CumlRnk', 'LatestQtr', 'StarStock', 'Conviction', 'Category', 'InFolio', 'XIRR', 'MBQ']
diff_cols = ['Symbol', 'AvgCost', 'Shares']
df_stocks = arrange_features(df_stocks, common_cols, diff_cols)

# get common features
stock_ids = df_stocks['Symbol'].values
df_common_features = get_common_features(stock_ids, df_stocks)

df_common_features.reset_index(drop=True, inplace=True)
df_common_features.drop(['Date'], axis=1, inplace=True)
# get and print portfolio features
df_portfolio_features = get_portfolio_features(df_common_features)

print_portfolio_stats(df_portfolio_features, myinvmt_df)

df = df_portfolio_features
#plot_pie_chart(df, 'CapType', 'Current')
list_ox40n = list(df[df['MBQ'].str.contains('OX40N', na=False)]['Symbol'].values)

Run date time (IST): 2026-03-12 12:05:40
-------------------
qualified stocks: 86
with latest results: 26
still star stocks: 15
-------------------
Initial Investment:  1.36 C
CY Investment:  1.62 C
Reserve:  66.25 K
Current:  1.36 C
-------------------
Today PnL: -36.80 K (-0.27%)
Current PnL: -40.70 L (-25.05%)
CY Booked + Current PnL: -25.02 L (-15.4%)
-------------------
Total profit:  1.13 L
Total loss:  -41.83 L
-------------------
Total Booked + Current PnL: 1.96 L (1.45%)
Total Booked PnL: 42.66 L (31.48%)
Curr Year Booked PnL: 15.68 L (11.51%)
Prev Year Booked PnL: 26.98 L (19.91%)
===================
Est FTT:  2.47 C
Est FTT PnL: 1.11 C (81.52%)
===================
Deployed:  1.36 C
Current:  1.36 C
CAGR/XIRR %: 0.27%

In [9]:
# top 5 near their targets
cols = ['Symbol', 'Today P/L%', 'Current P/L%', 'FTT%', 'OTT%', 'FTT Amt', 'Current P/L', 'Current', 'FTT', 'Dev%_PE', 'RSI_14','Conviction', 'Spread%',  'CumlRnk', 'RRR Ind', 'CurrAlloc%', 'Gained%', 'Criteria', 'Strategy', 'Category']
df_tmp = df_portfolio_features[~df_portfolio_features['Symbol'].isin(['ENRIN','BLUSPRING','DIGITIDE'])]
df_tmp = df_tmp.sort_values(by = 'FTT Amt', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
19,COALINDIA,4.32,14.61,2.67,17.67,4604.0,21978.0,172438.0,478.51,37.73,69.0,L-LC,12.15,185.0,4.77,1.27,33.91,XY25,ATH,MINING
77,TTKPRESTIG,7.39,-25.26,33.91,0.09,25543.0,-25452.0,75325.0,770.00,74.81,60.0,M-SC,15.27,250.0,-1.00,0.56,27.27,OX40N,NTT,DURABLES
50,MASFIN,-0.13,-7.23,31.04,21.57,28215.0,-7080.0,90900.0,397.04,-20.05,39.0,H-SC,4.15,167.0,-0.25,0.67,26.10,XR,ATH,FINANCE
37,ICICIGI,-1.40,-2.06,21.85,19.34,42825.0,-4115.0,195994.0,2252.93,-17.63,40.0,X-MC,1.78,66.0,-0.10,1.45,11.78,X40,ATH,INSURANCE
78,UNITDSPR,-1.22,0.29,20.42,20.77,47949.0,670.0,234814.0,1644.00,-11.09,48.0,X-MC,1.41,64.0,0.01,1.73,7.01,X40N,NTT,BREWERIES

In [10]:
# top 5 today
df_tmp = df_portfolio_features.sort_values(by = 'Today P/L%', ascending=False)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
77,TTKPRESTIG,7.39,-25.26,33.91,0.09,25543.0,-25452.0,75325.0,770.00,74.81,60.0,M-SC,15.27,250.0,-1.00,0.56,27.27,OX40N,NTT,DURABLES
19,COALINDIA,4.32,14.61,2.67,17.67,4604.0,21978.0,172438.0,478.51,37.73,69.0,L-LC,12.15,185.0,4.77,1.27,33.91,XY25,ATH,MINING
57,RECLTD,3.23,-6.93,29.73,20.74,56216.0,-14080.0,189090.0,446.00,3.52,48.0,M-MC,5.07,191.0,-0.25,1.39,5.98,XY25,NTT,FINANCE
60,REPCOHOME,3.08,-19.06,134.51,89.82,311934.0,-54601.0,231904.0,880.00,-59.76,45.0,H-SC,3.62,161.0,-0.18,1.71,23.29,XY24,NTT,FINANCE
31,HAPPSTMNDS,2.81,-48.60,259.66,84.85,171043.0,-62293.0,65872.0,1480.71,-38.81,63.0,H-SC,28.65,152.0,-0.36,0.49,21.99,AR,ATH,IT

In [11]:
# bottom 5 today
df_tmp = df_portfolio_features.sort_values(by = 'Today P/L%', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
42,INDUSINDBK,-4.40,-38.09,114.66,32.89,54804.0,-29410.0,47797.0,1800.00,-324.79,31.0,L-MC,10.63,258.0,-0.54,0.35,31.63,XR,NTT,BANKS
69,SURYODAY,-3.76,-26.52,67.44,23.03,88738.0,-47491.0,131580.0,216.00,42.54,49.0,H-SC,7.41,166.0,-0.54,0.97,30.55,XR,NTT,BANKS
81,VBL,-3.46,-15.90,61.32,35.67,162885.0,-50211.0,265631.0,671.64,-25.70,31.0,X-LC,5.04,13.0,-0.31,1.96,0.00,X40N,ATH,FMCG
55,RAJESHEXPO,-3.14,-78.56,366.79,0.07,107862.0,-107770.0,29407.0,518.00,978.28,22.0,L-SC,21.00,268.0,-1.00,0.22,1.63,OX40N,NTT,JEWELLERY
15,BSOFT,-2.40,-32.42,123.13,50.79,117036.0,-45602.0,95051.0,831.70,-13.41,41.0,H-SC,6.69,172.0,-0.39,0.70,10.67,XR,ATH,IT

In [12]:
# top 5 to exit based on CumlRnk
df_tmp = df_portfolio_features[~df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])]
df_tmp = df_tmp[(df_tmp['Current P/L%'] > -1) & (df_tmp['Current P/L%'] < 1)].sort_values(by = 'CumlRnk', ascending=False)
df_tmp[cols].head()

Empty DataFrame
Columns: [Symbol, Today P/L%, Current P/L%, FTT%, OTT%, FTT Amt, Current P/L, Current, FTT, Dev%_PE, RSI_14, Conviction, Spread%, CumlRnk, RRR Ind, CurrAlloc%, Gained%, Criteria, Strategy, Category]
Index: []

In [13]:
# OX40N stocks to exit
df_tmp = df_portfolio_features[(df_portfolio_features['Symbol'].isin(list_ox40n))].sort_values(by = 'Current P/L%', ascending=False)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
27,FINCABLES,1.32,13.94,82.48,107.91,138752.0,20581.0,168225.0,1641.55,2.49,57.0,M-SC,7.76,220.0,0.15,1.24,26.56,OX40N,ATH,CABLES
77,TTKPRESTIG,7.39,-25.26,33.91,0.09,25543.0,-25452.0,75325.0,770.00,74.81,60.0,M-SC,15.27,250.0,-1.00,0.56,27.27,OX40N,NTT,DURABLES
66,SIS,-1.53,-34.07,83.94,21.26,61442.0,-37834.0,73198.0,528.00,1713.99,34.0,H-SC,10.62,168.0,-0.62,0.54,0.91,OX40N,NTT,MISC
70,SYMPHONY,1.21,-36.38,57.14,-0.03,62211.0,-62267.0,108874.0,1306.00,-48.93,49.0,M-SC,13.65,205.0,-1.00,0.80,10.10,OX40N,NTT,DURABLES
48,KANSAINER,1.38,-36.72,79.32,13.47,135352.0,-99027.0,170640.0,340.00,-45.60,32.0,H-SC,16.69,162.0,-0.73,1.26,2.30,XY24,NTT,PAINTS

In [14]:
# top 5 to book for rotation
df_tmp = df_portfolio_features[(df_portfolio_features['Current P/L%'] > 20) ].sort_values(by = 'CumlRnk', ascending=False)
df_tmp[cols].head()

Empty DataFrame
Columns: [Symbol, Today P/L%, Current P/L%, FTT%, OTT%, FTT Amt, Current P/L, Current, FTT, Dev%_PE, RSI_14, Conviction, Spread%, CumlRnk, RRR Ind, CurrAlloc%, Gained%, Criteria, Strategy, Category]
Index: []

In [15]:
# top 5 to monitor for exit
df_tmp = df_portfolio_features[~df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])]
df_tmp = df_tmp[(df_tmp['Current P/L%'] > 0) ].sort_values(by = 'Dev%_PE', ascending=False)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
19,COALINDIA,4.32,14.61,2.67,17.67,4604.0,21978.0,172438.0,478.51,37.73,69.0,L-LC,12.15,185.0,4.77,1.27,33.91,XY25,ATH,MINING
27,FINCABLES,1.32,13.94,82.48,107.91,138752.0,20581.0,168225.0,1641.55,2.49,57.0,M-SC,7.76,220.0,0.15,1.24,26.56,OX40N,ATH,CABLES
1,ABB,0.96,16.32,25.14,45.57,76506.0,42701.0,304320.0,7934.00,-25.21,67.0,H-MC,10.51,125.0,0.56,2.24,35.14,AR,NTT,ELECTRICAL

In [16]:
# top 5 to book for rotation from weak conviction
df_tmp = df_portfolio_features[~df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])]
df_tmp = df_tmp[~df_tmp['Criteria'].isin(['XY25','XY24','X40', 'X40N'])].sort_values(by = 'RRR Ind', ascending=False)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
1,ABB,0.96,16.32,25.14,45.57,76506.0,42701.0,304320.0,7934.00,-25.21,67.0,H-MC,10.51,125.0,0.56,2.24,35.14,AR,NTT,ELECTRICAL
27,FINCABLES,1.32,13.94,82.48,107.91,138752.0,20581.0,168225.0,1641.55,2.49,57.0,M-SC,7.76,220.0,0.15,1.24,26.56,OX40N,ATH,CABLES
85,ZYDUSLIFE,0.03,-2.77,39.50,35.63,80486.0,-5812.0,203762.0,1286.17,-15.32,55.0,H-MC,5.01,120.0,-0.07,1.50,13.44,AR,ATH,PHARMA
40,INDIAMART,-1.05,-9.41,128.20,106.72,143237.0,-11607.0,111729.0,4810.62,-59.18,41.0,H-SC,9.44,140.0,-0.08,0.82,11.77,AR,ATH,MISC
84,WIPRO,0.36,-16.76,106.95,72.27,150853.0,-28398.0,141050.0,420.00,-25.02,36.0,M-LC,15.04,98.0,-0.19,1.04,3.86,XR,NTT,IT

In [17]:
# top 5 to accumulate based on lowest RSI_14
df_tmp = df_portfolio_features[df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])].sort_values(by = 'RSI_14', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
58,RELAXO,-0.20,-60.62,286.78,52.31,163926.0,-87999.0,57161.0,1176.00,-58.09,19.0,X-SC,19.53,92.0,-0.54,0.42,0.00,X40N,NTT,FOOTWEAR
3,ACC,-0.60,-35.21,169.83,74.81,295015.0,-94416.0,173712.0,3906.00,-53.87,22.0,X-SC,12.77,85.0,-0.32,1.28,0.00,XY24,BTT,CEMENT
12,BATAINDIA,0.23,-53.53,190.97,35.20,114179.0,-68881.0,59789.0,2096.00,-21.59,22.0,X-SC,26.20,91.0,-0.60,0.44,0.48,X40,NTT,FOOTWEAR
8,AWL,-0.47,-38.51,171.63,67.02,376009.0,-137228.0,219081.0,485.00,-66.89,22.0,X-SC,23.35,81.0,-0.36,1.62,1.68,XY24,NTT,FMCG
73,TCS,0.20,-27.49,74.56,26.57,250452.0,-127367.0,335906.0,4311.58,-38.71,22.0,X-LC,14.40,2.0,-0.51,2.48,0.20,X40,ATH,IT

In [18]:
# top 5 to accumulate based on Spread and CumlRnk
df_tmp = df_portfolio_features[df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])]
df_tmp = df_tmp[(df_tmp['CumlRnk'] < 100)].sort_values(by = 'Spread%', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
78,UNITDSPR,-1.22,0.29,20.42,20.77,47949.0,670.0,234814.0,1644.00,-11.09,48.0,X-MC,1.41,64.0,0.01,1.73,7.01,X40N,NTT,BREWERIES
22,DABUR,-2.01,-9.61,58.97,43.70,132234.0,-23828.0,224240.0,735.00,-17.99,31.0,X-MC,1.50,70.0,-0.18,1.65,4.00,XY24,BTT,FMCG
75,TMPV,-1.89,-25.11,82.37,36.58,219508.0,-89351.0,266490.0,600.00,-84.72,34.0,X-LC,1.76,4.0,-0.41,1.97,0.00,XY24,NTT,AUTO
37,ICICIGI,-1.40,-2.06,21.85,19.34,42825.0,-4115.0,195994.0,2252.93,-17.63,40.0,X-MC,1.78,66.0,-0.10,1.45,11.78,X40,ATH,INSURANCE
59,RELIANCE,1.40,-9.52,38.48,25.30,69971.0,-19125.0,181838.0,1952.00,-11.96,49.0,X-LC,2.68,21.0,-0.27,1.34,21.41,XY25,BTT,REFINERIES

In [19]:
# top 5 to accumulate based on lowest Gained%
df_tmp = df_portfolio_features[df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])].sort_values(by = 'Gained%', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
3,ACC,-0.60,-35.21,169.83,74.81,295015.0,-94416.0,173712.0,3906.00,-53.87,22.0,X-SC,12.77,85.0,-0.32,1.28,0.0,XY24,BTT,CEMENT
10,BAJAJHLDNG,-1.84,-10.67,44.66,29.22,75846.0,-20295.0,169830.0,14451.52,-17.16,27.0,X-LC,12.26,28.0,-0.27,1.25,0.0,X40,ATH,FINANCE
21,COLPAL,-2.36,-23.79,85.69,41.51,171980.0,-62665.0,200700.0,3726.84,-7.87,34.0,X-MC,4.14,62.0,-0.36,1.48,0.0,XY25,ATH,FMCG
13,BERGEPAINT,-1.02,-21.45,59.53,25.32,120530.0,-55280.0,202469.0,680.00,-25.65,26.0,X-MC,15.64,68.0,-0.46,1.49,0.0,XY24,NTT,PAINTS
58,RELAXO,-0.20,-60.62,286.78,52.31,163926.0,-87999.0,57161.0,1176.00,-58.09,19.0,X-SC,19.53,92.0,-0.54,0.42,0.0,X40N,NTT,FOOTWEAR

In [20]:
# top 5 to accumulate based on lowest CurrAlloc%
df_tmp = df_portfolio_features[df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])].sort_values(by = 'CurrAlloc%', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
58,RELAXO,-0.20,-60.62,286.78,52.31,163926.0,-87999.0,57161.0,1176.00,-58.09,19.0,X-SC,19.53,92.0,-0.54,0.42,0.00,X40N,NTT,FOOTWEAR
12,BATAINDIA,0.23,-53.53,190.97,35.20,114179.0,-68881.0,59789.0,2096.00,-21.59,22.0,X-SC,26.20,91.0,-0.60,0.44,0.48,X40,NTT,FOOTWEAR
54,QUESS,-0.38,-21.08,120.36,73.90,101435.0,-22517.0,84276.0,424.00,-57.58,43.0,X-SC,18.31,80.0,-0.22,0.62,3.96,XY24,NTT,MISC
36,HONAUT,-0.29,-20.76,90.96,51.31,138987.0,-40038.0,152800.0,58357.33,-34.10,42.0,X-SC,13.79,90.0,-0.29,1.13,2.90,X40N,ATH,ELECTRICAL
2,ABBOTINDIA,-1.18,-9.83,30.93,18.07,49884.0,-17575.0,161280.0,35195.00,-23.22,48.0,X-MC,11.08,58.0,-0.35,1.19,2.24,X40,ATH,PHARMA

In [21]:
# top 5 to accumulate based on CumlRnk
df_tmp = df_portfolio_features.sort_values(by = 'CumlRnk', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
45,ITC,-0.66,-19.15,47.26,19.06,129978.0,-65139.0,275027.0,452.00,-55.52,36.0,X-LC,17.02,1.0,-0.50,2.03,0.31,X40,NTT,FMCG
73,TCS,0.20,-27.49,74.56,26.57,250452.0,-127367.0,335906.0,4311.58,-38.71,22.0,X-LC,14.40,2.0,-0.51,2.48,0.20,X40,ATH,IT
43,INFY,0.06,-13.06,54.41,34.24,148007.0,-40866.0,272022.0,1972.00,-31.42,26.0,X-LC,12.71,3.0,-0.28,2.01,0.13,X40,NTT,IT
75,TMPV,-1.89,-25.11,82.37,36.58,219508.0,-89351.0,266490.0,600.00,-84.72,34.0,X-LC,1.76,4.0,-0.41,1.97,0.00,XY24,NTT,AUTO
34,HCLTECH,0.81,-11.66,40.17,23.83,85853.0,-28200.0,213724.0,1908.19,-7.36,31.0,X-LC,9.79,8.0,-0.33,1.58,2.54,X40,ATH,IT

In [22]:
# top 5 for average up
df_tmp = df_portfolio_features[(df_portfolio_features['Dev%_200'] > 5)].sort_values(by = 'CurrAlloc%', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
67,SONACOMS,-1.54,-12.05,58.15,39.09,51736.0,-12189.0,88970.0,804.02,-30.33,47.0,M-MC,9.82,193.0,-0.24,0.66,25.86,AR,ATH,AUTO
65,SIEMENS,1.92,-10.40,40.07,25.51,66817.0,-19345.0,166750.0,4671.50,40.03,58.0,H-LC,3.81,51.0,-0.29,1.23,22.80,AR,ATH,ELECTRICAL
27,FINCABLES,1.32,13.94,82.48,107.91,138752.0,20581.0,168225.0,1641.55,2.49,57.0,M-SC,7.76,220.0,0.15,1.24,26.56,OX40N,ATH,CABLES
19,COALINDIA,4.32,14.61,2.67,17.67,4604.0,21978.0,172438.0,478.51,37.73,69.0,L-LC,12.15,185.0,4.77,1.27,33.91,XY25,ATH,MINING
82,VOLTAS,-1.39,13.50,27.92,45.20,60764.0,25893.0,217635.0,1856.00,29.95,46.0,X-MC,9.36,79.0,0.43,1.61,21.22,XY25,NTT,AC

In [23]:
# top 5 RSP
df_tmp = df_portfolio_features.sort_values(by = 'RSP', ascending=False)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
19,COALINDIA,4.32,14.61,2.67,17.67,4604.0,21978.0,172438.0,478.51,37.73,69.0,L-LC,12.15,185.0,4.77,1.27,33.91,XY25,ATH,MINING
27,FINCABLES,1.32,13.94,82.48,107.91,138752.0,20581.0,168225.0,1641.55,2.49,57.0,M-SC,7.76,220.0,0.15,1.24,26.56,OX40N,ATH,CABLES
1,ABB,0.96,16.32,25.14,45.57,76506.0,42701.0,304320.0,7934.00,-25.21,67.0,H-MC,10.51,125.0,0.56,2.24,35.14,AR,NTT,ELECTRICAL
26,EASEMYTRIP,-0.95,-59.82,262.64,45.70,186574.0,-105777.0,71038.0,26.40,-26.33,43.0,M-SC,18.19,204.0,-0.57,0.52,17.04,XY24,NTT,TRAVEL
31,HAPPSTMNDS,2.81,-48.60,259.66,84.85,171043.0,-62293.0,65872.0,1480.71,-38.81,63.0,H-SC,28.65,152.0,-0.36,0.49,21.99,AR,ATH,IT

In [24]:
# Top N allocation
df_tmp = df_portfolio_features.sort_values(by = 'CurrAlloc%', ascending=False)
top_n_values = [10, 25, 50]

sum_df = pd.DataFrame({
    'Top_N': top_n_values,
    'Sum_Alloc%': [df_tmp['CurrAlloc%'].head(n).sum() for n in top_n_values]
})

sum_df

   Top_N  Sum_Alloc%
0     10       20.36
1     25       45.15
2     50       77.76

In [25]:
# market-cap-wise allocation
df_tmp = df_portfolio_features[cols]
df_tmp.groupby(df_tmp['Conviction'].str[-2:])['CurrAlloc%'].sum().sort_values(ascending=False)

Conviction
SC    44.70
MC    30.38
LC    24.90
Name: CurrAlloc%, dtype: float64

In [26]:
# criteria-wise allocation
df_portfolio_features.groupby('Criteria')['CurrAlloc%'].sum().sort_values(ascending=False)

Criteria
XY24     27.29
X40      23.77
X40N     15.03
AR        9.25
XY25      8.66
XR        8.21
OX40N     6.99
SR        0.78
Name: CurrAlloc%, dtype: float64

In [27]:
# conviction-wise allocation
df_portfolio_features.groupby('Conviction')['CurrAlloc%'].sum().sort_values(ascending=False)

Conviction
X-MC    22.95
H-SC    21.74
X-LC    21.36
X-SC    12.09
M-SC    10.28
H-MC     5.03
M-MC     2.05
L-LC     1.27
H-LC     1.23
M-LC     1.04
L-SC     0.59
L-MC     0.35
Name: CurrAlloc%, dtype: float64

In [28]:
# sector-wise stats
df_tmp = df_portfolio_features.groupby('Category')[['CurrAlloc%', 'Current', 'Current P/L', 'FTT Amt']].sum().sort_values(by=['Current', 'Current P/L'], ascending=False)
df_tmp['Current P/L%'] = round(df_tmp['Current P/L'] * 100 / df_tmp['Current'], 2)
df_tmp['FTT%'] = round(df_tmp['FTT Amt'] * 100 / df_tmp['Current'], 2)
cols = ['CurrAlloc%', 'Current P/L%', 'FTT%']
df_tmp[cols].sort_values(by=['CurrAlloc%'], ascending=False)

               CurrAlloc%  Current P/L%    FTT%
Category
FMCG                15.11        -21.96   65.26
FINANCE             12.85        -23.30   73.55
IT                  11.74        -41.63  113.70
MISC                 6.97        -41.54  103.02
ELECTRICAL           6.70         -6.56   47.36
PAINTS               5.19        -40.06   64.38
INSURANCE            4.71         -6.34   42.73
PHARMA               4.17         -3.94   36.66
AUTO                 3.70        -30.78   82.67
BANKS                3.08        -27.79  105.23
AC                   2.15         -9.73   39.48
HEALTHCARE           1.99        -33.02   67.74
DURABLES             1.95        -46.25   81.83
FOOTWEAR             1.85        -76.09  146.70
TRAVEL               1.81        -81.40  172.23
BREWERIES            1.73          0.29   20.42
APPARELS             1.60        -23.38   65.47
REALTY               1.46        -12.33   30.78
CERAMICS             1.35        -68.14  119.22
REFINERIES           1.34        -10.52   38.48
CEMENT               1.28        -54.35  169.83
MINING               1.27         12.75    2.67
CABLES               1.24         12.23   82.48
JEWELLERY            1.12       -112.21  185.93
ENGINEERING          1.11        -60.60  134.05
CHEMICALS            0.96       -103.05  268.70
ENTERTAINMENT        0.76        -87.25  198.93
TEXTILES             0.42        -60.44  106.19
HOTELS               0.37       -126.68  206.63

In [29]:
# money to be made criteria-wise
df_portfolio_features.groupby('Criteria')['FTT Amt'].agg(['sum', 'count']).sort_values(by='sum', ascending=False)

                sum  count
Criteria
XY24      3896623.0     21
X40       1650848.0     15
XR        1376102.0     12
AR        1317640.0     10
X40N      1262515.0     10
OX40N      845115.0     10
XY25       442885.0      6
SR         314007.0      2

In [30]:
# money to be made conviction-wise
df_portfolio_features.groupby('Conviction')['FTT Amt'].agg(['sum', 'count']).sort_values(by='sum', ascending=False)

                  sum  count
Conviction
H-SC        3845058.0     24
X-MC        1621173.0     15
X-LC        1580861.0     12
X-SC        1543478.0     10
M-SC        1523639.0     14
H-MC         395127.0      3
L-SC         211369.0      2
M-LC         150853.0      1
M-MC         107952.0      2
H-LC          66817.0      1
L-MC          54804.0      1
L-LC           4604.0      1

In [31]:
# money to be made criteria and conviction-wise
df_portfolio_features.groupby(['Conviction', 'Criteria'])['FTT Amt'].agg(['sum', 'count']).sort_values(by='sum', ascending=False)

                           sum  count
Conviction Criteria
H-SC       XY24      1304136.0      6
           AR         965022.0      5
M-SC       XY24       904268.0      6
H-SC       XR         877262.0      7
X-SC       XY24       830743.0      4
X-LC       X40        815316.0      6
X-MC       X40        630989.0      7
X-SC       X40N       508192.0      4
X-MC       X40N       504676.0      4
H-SC       OX40N      384631.0      4
X-LC       XY24       366577.0      2
M-SC       OX40N      352622.0      5
H-SC       SR         314007.0      2
X-MC       XY24       252764.0      2
X-LC       X40N       249647.0      2
H-MC       XY24       238135.0      1
X-MC       XY25       232744.0      2
X-SC       X40        204543.0      2
M-SC       XR         189676.0      2
H-MC       AR         156992.0      2
M-LC       XR         150853.0      1
X-LC       XY25       149321.0      2
L-SC       OX40N      107862.0      1
           XR         103507.0      1
M-SC       AR          77073.0      1
H-LC       AR          66817.0      1
M-MC       XY25        56216.0      1
L-MC       XR          54804.0      1
M-MC       AR          51736.0      1
L-LC       XY25         4604.0      1

In [32]:
# notebook execution time

end_time = time.time()
execution_time = round(end_time - start_time, 0)
print(f"Notebook execution time: {execution_time} seconds")

Notebook execution time: 33.0 seconds