<a href="https://colab.research.google.com/github/ankit-rathi/Quantvesting_v2/blob/main/myStocks_Portfolio_Analysis.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
'''
!pip install pandas==2.2.2 -qq
!pip install pyxirr -qq
!pip install ta -qq
!pip install yfinance==0.2.59 -qq
'''

'\n!pip install pandas==2.2.2 -qq\n!pip install pyxirr -qq\n!pip install ta -qq\n!pip install yfinance==0.2.59 -qq\n'

In [2]:
# import libraries

import numpy as np
import pandas as pd
import datetime
import warnings
warnings.filterwarnings('ignore')
import yfinance as yfin
import ta
import matplotlib.pyplot as plt
import requests

In [3]:
# notebook start time
import time
import datetime
import pytz

start_time = time.time()

# function to print date timestamp
def print_date_time():
  tz_NY = pytz.timezone('Asia/Kolkata')
  datetime_NY = datetime.datetime.now(tz_NY)
  print("Run date time (IST):", datetime_NY.strftime("%Y-%m-%d %H:%M:%S"))

In [4]:
# function to get booked and reserved amount
def get_amt():
  # fetch the JSON data from the URL
  url = "https://raw.githubusercontent.com/ankit-rathi/Tradevesting_v1/main/data/myPortfolioAmts.json"
  response = requests.get(url)
  pf_amts = response.json()  # parse the JSON data

  # extract values from the JSON
  py_booked_amt_dm = pf_amts["py_booked_amt_dm"]
  py_booked_amt_sv = pf_amts["py_booked_amt_sv"]
  cy_booked_amt_dm = pf_amts["cy_booked_amt_dm"]
  cy_booked_amt_sv = pf_amts["cy_booked_amt_sv"]
  reserve_amt_dm = pf_amts["reserve_amt_dm"]
  reserve_amt_sv = pf_amts["reserve_amt_sv"]

  # perform calculations
  py_booked_amt = py_booked_amt_dm + py_booked_amt_sv
  cy_booked_amt = cy_booked_amt_dm + cy_booked_amt_sv
  reserve_amt = reserve_amt_dm + reserve_amt_sv
  total_booked_amt = py_booked_amt + cy_booked_amt

  return total_booked_amt, reserve_amt, cy_booked_amt, py_booked_amt

gen_output = 0

In [5]:
# function to format the amount
def format_amt(number):
    abs_number = abs(number)

    if abs_number >= 1_00_00_000:  # Crores
        formatted_amt = f"{number / 1_00_00_000:.2f} C"
    elif abs_number >= 1_00_000:  # Lakhs
        formatted_amt = f"{number / 1_00_000:.2f} L"
    elif abs_number >= 1_000:  # Thousands
        formatted_amt = f"{number / 1_000:.2f} K"
    else:
        formatted_amt = f"{number:.2f}"

    return formatted_amt

# function to set start and end date
def get_start_end_date():
  start_date = (datetime.date.today() + datetime.timedelta(days=-365)).strftime('%Y-%m-%d')
  end_date = (datetime.date.today() + datetime.timedelta(days=1)).strftime('%Y-%m-%d')
  return start_date, end_date

# function to fetch my portfolio csv
def get_mypfs_df():
  mypfs_df = pd.read_csv('https://raw.githubusercontent.com/ankit-rathi/Tradevesting_v1/main/data/myPortfolioStocks.csv')
  return mypfs_df

# function to fetch my prospects csv
def get_mypps_df():
  mypps_df = pd.read_csv('https://raw.githubusercontent.com/ankit-rathi/Tradevesting_v1/main/data/myProspectsScrips.csv')
  return mypps_df

# function to fetch screener data
def get_myscreen_df():
  myscreen_df = pd.read_csv('https://raw.githubusercontent.com/ankit-rathi/Tradevesting_v1/main/data/myScreenerDB.csv')
  return myscreen_df

# function to fetch momentum data
def get_myinvmt_df():
  myinvmt_df = pd.read_csv('https://raw.githubusercontent.com/ankit-rathi/Tradevesting_v1/main/data/myInvestments.csv')
  return myinvmt_df

# function to get the stock ids
def get_stock_ids(df_pf):
  stock_n100 = df_pf['Symbol'].unique()

  exclude = ['CADILAHC','MMTC', 'MASFIN']

  stock_ids = df_pf[~df_pf['Symbol'].isin(exclude) ]['Symbol'].unique()

  #mypf = mypf[mypf.Forecast.notnull()]
  #stock_ids = mypf['Symbol'].unique()

  #stock_ids.sort()
  return stock_ids

# get features from screener data
def get_screener_features():
  myscreen_df = get_myscreen_df()
  cols = ['Symbol', 'EPS', 'MedPE', 'ROCE%', 'ROE%', 'CapType']
  return myscreen_df[cols]

# get relative strength
def get_relative_strength(stock_list):

    # Dictionary to store stock tickers and their corresponding percentage price change
    stock_changes = {}

    # Loop through each stock and fetch its price data
    for stock in stock_list:
        try:
            # Download the stock data for the given date range
            stock_data = yfin.Ticker(stock + '.NS').history(period='1mo', interval='1d')[map(str.title, ['open', 'close', 'low', 'high', 'volume'])]

            # Calculate the percentage change for the stock
            if len(stock_data) > 0:
                start_price = stock_data['Close'].iloc[0]
                end_price = stock_data['Close'].iloc[-1]
                percent_change = round(((end_price - start_price) / start_price) * 100, 2)
                stock_changes[stock] = percent_change
            else:
                stock_changes[stock] = np.nan  # If no data is available, set to NaN

        except Exception as e:
            print(f"Error fetching data for {stock}: {e}")
            stock_changes[stock] = np.nan

    # Create a DataFrame with stock tickers and their percentage changes
    df = pd.DataFrame(list(stock_changes.items()), columns=['Symbol', 'Percent_Change'])

    # Drop any stocks with missing data (NaN values)
    df = df.dropna()

    # Calculate the percentile rank based on percentage change
    df['RSP'] = round(df['Percent_Change'].rank(pct=True) * 100, 2)
    cols = ['Symbol', 'RSP']
    df = df[cols]
    # Sort by percentile rank (optional)
    df = df.sort_values(by='RSP', ascending=False).reset_index(drop=True)

    return df

In [6]:
# function to get stock technicals
def stock_prec_dev(stock_symbol):
    #stock_symbol = 'ULTRACEMCO.NS'
    short_window = 20
    mid_window = 50
    long_window = 200
    moving_avg = 'SMA'

    start = datetime.datetime(*map(int, start_date.split('-')))
    end = datetime.datetime(*map(int, end_date.split('-')))

    stock_df = yfin.Ticker(stock_symbol + '.NS').history(period='max', interval='1d')[map(str.title, ['open', 'close', 'low', 'high', 'volume'])]

    stock_df['Max'] = round(max(stock_df['Close']),2)
    stock_df = stock_df[(stock_df.index <= end_date) & (stock_df.index >= start_date)]
    stock_df['200_SMA'] = round(stock_df['Close'].rolling(window = 200, min_periods = 1).mean(),0)
    stock_df['Dev%_200'] = round((stock_df['Close'] - stock_df['200_SMA'])*100/stock_df['200_SMA'],2)
    stock_df.dropna(axis = 0, inplace = True) # remove any null rows

    stock_df['20_SMA'] = stock_df['Close'].rolling(window=20).mean()
    stock_df['50_SMA'] = stock_df['Close'].rolling(window=50).mean()
    stock_df['Symbol'] = stock_symbol

    stock_df['Close'] = round(stock_df['Close'],2)
    stock_df['Min'] = round(min(stock_df['Close']),2)
    stock_df['RSI_14'] = ta.momentum.RSIIndicator(close=stock_df['Close'], window=14).rsi()
    stock_df['RSI_14'] = round(stock_df['RSI_14'],0)
    stock_df['Prev_Close'] = stock_df['Close'].shift(1)
    stock_df.drop(['Open', 'Low', 'High', 'Volume'], axis=1, inplace=True)
    stock_df = stock_df.tail(1)

    max_SMA = max(stock_df['20_SMA'].item(), stock_df['50_SMA'].item(), stock_df['200_SMA'].item())
    min_SMA = min(stock_df['20_SMA'].item(), stock_df['50_SMA'].item(), stock_df['200_SMA'].item())
    ABS_Spread = max_SMA - min_SMA
    stock_df['Spread%'] = round((ABS_Spread / stock_df['200_SMA'].item()) * 100,2)

    return stock_df

# function to compute stock attributes
def get_common_features(stock_ids, df_mypf):

  df_prec_dev = pd.DataFrame()
  df_tmp = get_screener_features()
  df_rs = get_relative_strength(stock_ids)

  for stock_id in stock_ids:
      tmp = stock_prec_dev(stock_id)
      tmp = tmp.reset_index()
      df_prec_dev = pd.concat([df_prec_dev, tmp], ignore_index = True)
  df_prec_dev = pd.merge(df_prec_dev, df_mypf, on= 'Symbol')
  df_prec_dev = pd.merge(df_prec_dev, df_tmp, on= 'Symbol', how='left')
  df_prec_dev = pd.merge(df_prec_dev, df_rs, on= 'Symbol', how='left')
  #print(df_prec_dev.columns)
  df_prec_dev['Curr_PE'] = round(df_prec_dev['Close']/df_prec_dev['EPS'],1)
  df_prec_dev['Dev%_PE'] = round((df_prec_dev['Curr_PE'] - df_prec_dev['MedPE'])*100/df_prec_dev['MedPE'],2)
  df_prec_dev['Conviction'] = df_prec_dev['Conviction'] + '-' + df_prec_dev['CapType']
  return df_prec_dev

# function to arrange stock features
def arrange_features(df_stocks, common_cols, diff_cols):
  df_stocks_common = df_stocks[common_cols].drop_duplicates()
  df_stocks_diff = df_stocks[diff_cols]
  df_stocks_diff['Investment'] = df_stocks_diff['AvgCost'] * df_stocks_diff['Shares']
  df_stocks_diff = df_stocks_diff.groupby(['Symbol'])[['Shares', 'Investment']].aggregate(['sum']).reset_index()
  df_stocks_diff.columns = ['Symbol', 'Shares', 'Investment']
  df_stocks_diff['AvgCost'] = round(df_stocks_diff['Investment']/df_stocks_diff['Shares'],2)
  df_stocks = pd.merge(df_stocks_diff, df_stocks_common, on='Symbol')
  return df_stocks

# plot fact distribution across dimension
def plot_pie_chart(df, dimension, fact):
  # grouping the data by category and calculating the sum of fact for each type
  grouped_data = df.groupby(dimension)[fact].sum()

  # sorting the grouped data in descending order
  grouped_data = grouped_data.sort_values(ascending=False)

  # creating a pie chart
  grouped_data.plot.pie(autopct='%1.1f%%', startangle=90, figsize=(6, 6))

  # adding a title and displaying the plot
  plt.title(f'{dimension} {fact} Distribution')
  plt.ylabel('')  # To hide the y-label
  plt.show()

In [7]:
# function to get portfolio features

def get_portfolio_features(df_common_features):

  print_date_time()
  print('-------------------')

  #df_common_features["Target"] = df_common_features["Target"].fillna(df_common_features["Max"])
  df_common_features['NTT'] = np.where(df_common_features['Strategy']== 'NTT', df_common_features["Target"], df_common_features['Max'])
  df_common_features['LTT'] = np.where(df_common_features['Strategy']== 'BTT', df_common_features["Target"], df_common_features['Max'])
  df_common_features['BOL'] = df_common_features['Min']

  tmp_df = df_common_features[df_common_features['Symbol'].isin(mypf_df[mypf_df['InPortfolio'] != 'NA'].Symbol.values)]
  print('qualified stocks: '+str(len(tmp_df['Symbol'].unique())))
  tmp_df1 = tmp_df[tmp_df['LatestQtr'] == 1]
  print('with latest results: '+str(len(tmp_df1['Symbol'].unique())))
  tmp_df1 = tmp_df1[tmp_df1['StarStock'] == 1]
  print('still star stocks: '+str(len(tmp_df1['Symbol'].unique())))
  tmp_df['Investment'] = tmp_df['AvgCost'] * tmp_df['Shares']
  tmp_df['Current'] = round(tmp_df['Close'] * tmp_df['Shares'],0)
  tmp_df['Previous'] = tmp_df['Prev_Close'] * tmp_df['Shares']
  tmp_df['EstimatedST'] = tmp_df['NTT'] * tmp_df['Shares']
  tmp_df['EstimatedLT'] = tmp_df['LTT'] * tmp_df['Shares']
  tmp_df['Current P/L'] = round((tmp_df['Current'] - tmp_df['Investment']),0)
  tmp_df['Today P/L%'] = round((tmp_df['Current'] - tmp_df['Previous'])*100/tmp_df['Previous'],2)
  tmp_df['Current P/L%'] = round((tmp_df['Current'] - tmp_df['Investment'])*100/tmp_df['Investment'],2)
  tmp_df['EstimatedST P/L%'] = round((tmp_df['EstimatedST'] - tmp_df['Investment'])*100/tmp_df['Investment'],2)
  tmp_df['EstimatedLT P/L%'] = round((tmp_df['EstimatedLT'] - tmp_df['Investment'])*100/tmp_df['Investment'],2)
  tmp_df['NTT%'] = round((tmp_df['NTT'] - tmp_df['Close'])*100/tmp_df['Close'],2)
  tmp_df['LTT%'] = round((tmp_df['LTT'] - tmp_df['Close'])*100/tmp_df['Close'],2)
  tmp_df['Gained%'] = round((tmp_df['Close'] - tmp_df['BOL'])*100/tmp_df['BOL'],2)
  investment = round(sum(tmp_df['AvgCost']*tmp_df['Shares']),0)
  current = round(sum(tmp_df['Close']*tmp_df['Shares']),0)
  tmp_df['InitAlloc%'] = round(tmp_df['Investment']*100/investment,2)
  tmp_df['CurrAlloc%'] = round(tmp_df['Current']*100/current,2)
  tmp_df['FTT'] = tmp_df['LTT']
  tmp_df.loc[tmp_df['Strategy'] == 'NTT', 'FTT'] = tmp_df['NTT']
  tmp_df['FTT%'] = tmp_df['LTT%']
  tmp_df.loc[tmp_df['Strategy'] == 'NTT', 'FTT%'] = tmp_df['NTT%']
  tmp_df['FTT Amt'] = round(tmp_df['FTT%'] * tmp_df['Current']/100,0)
  tmp_df['OTT%'] = round((tmp_df['FTT'] - tmp_df['AvgCost'])*100/tmp_df['AvgCost'],2)
  tmp_df['RRR Ind'] = round(tmp_df['Current P/L']/tmp_df['FTT Amt'],2)
  tmp_df['Risk Ind'] = round(tmp_df['Current P/L%']*tmp_df['CurrAlloc%'],0)

  return tmp_df

# function to print portfolio features
def print_portfolio_stats(df_portfolio_features, myinvmt_df):
  from pyxirr import xirr

  total_booked_amt, reserve_amt, cy_booked_amt, py_booked_amt = get_amt()

  dates = myinvmt_df['Date'].values
  dates = np.append(dates, datetime.date.today().strftime('%d-%b-%y'))
  investment = myinvmt_df['Investment'].values
  dates= pd.to_datetime(dates)

  current = round(sum(df_portfolio_features['Close']*df_portfolio_features['Shares']),0) + reserve_amt
  investment_xirr = np.append(investment, current)
  cagr = round(xirr(pd.DataFrame({"dates": dates, "amounts": investment_xirr}))*100,2)

  investment = -sum(investment)
  invested = round(sum(df_portfolio_features['AvgCost']*df_portfolio_features['Shares']),0) + reserve_amt
  previous = round(sum(df_portfolio_features['Prev_Close']*df_portfolio_features['Shares']),0) + reserve_amt
  cy_invested = investment + py_booked_amt

  today_pnl_amount = current-previous
  today_pnl_percentage = round((current-previous)*100/previous,2)

  curr_pnl_amount = current-invested
  curr_pnl_percentage = round((curr_pnl_amount)*100/(cy_invested),2)

  cy_pnl_amount = cy_booked_amt + curr_pnl_amount
  cy_pnl_percentage = round((cy_pnl_amount)*100/cy_invested,2)

  overall_pnl_amount = total_booked_amt + curr_pnl_amount
  overall_pnl_percentage = round((overall_pnl_amount)*100/investment,2)

  estimate_st = round(sum(df_portfolio_features['FTT']*df_portfolio_features['Shares']),0)  + reserve_amt
  est_st_pnl_amount = estimate_st-current
  est_st_pnl_percentage = round((est_st_pnl_amount)*100/current,2)

  estimate_lt = round(sum(df_portfolio_features['LTT']*df_portfolio_features['Shares']),0)  + reserve_amt
  est_lt_pnl_amount = estimate_lt-current
  est_lt_pnl_percentage = round((est_lt_pnl_amount)*100/current,2)

  total_profit = round(sum(df_portfolio_features[df_portfolio_features['Current P/L%'] > 0]['Current']) - sum(df_portfolio_features[df_portfolio_features['Current P/L%'] > 0]['Investment']),0)
  total_loss = round(sum(df_portfolio_features[df_portfolio_features['Current P/L%'] < 0]['Current']) - sum(df_portfolio_features[df_portfolio_features['Current P/L%'] < 0]['Investment']),0)

  cy_booked_percentage = round((cy_booked_amt)*100/current,2)
  py_booked_percentage = round((py_booked_amt)*100/investment,2)
  total_booked_percentage = round((total_booked_amt)*100/investment,2)

  print('-------------------')
  print('Initial Investment: ', format_amt(investment))
  print('CY Investment: ', format_amt(cy_invested))
  print('Reserve: ', format_amt(reserve_amt))
  print('Current: ',  format_amt(current))
  print('-------------------')
  print('Today PnL: '+ '{} ({}%)'.format(format_amt(today_pnl_amount), today_pnl_percentage))
  print('Current PnL: '+ '{} ({}%)'.format(format_amt(curr_pnl_amount), curr_pnl_percentage))
  print('CY Booked + Current PnL: '+ '{} ({}%)'.format(format_amt(cy_pnl_amount), cy_pnl_percentage))
  print('-------------------')
  print('Total profit: ', format_amt(total_profit))
  print('Total loss: ', format_amt(total_loss))
  print('-------------------')
  print('Total Booked + Current PnL: '+ '{} ({}%)'.format(format_amt(overall_pnl_amount), overall_pnl_percentage))
  print('Total Booked PnL: '+ '{} ({}%)'.format(format_amt(total_booked_amt), total_booked_percentage))
  print('Curr Year Booked PnL: '+ '{} ({}%)'.format(format_amt(cy_booked_amt), cy_booked_percentage))
  print('Prev Year Booked PnL: '+ '{} ({}%)'.format(format_amt(py_booked_amt), py_booked_percentage))
  print('===================')
  print('Est FTT: ',  format_amt(estimate_st))
  print('Est FTT PnL: '+ '{} ({}%)'.format(format_amt(est_st_pnl_amount), est_st_pnl_percentage))

  print('===================')
  print('Deployed: ', format_amt(investment))

  print('Current: ', format_amt(current))

  print('CAGR/XIRR %: '+'{}%'.format(cagr))

In [8]:
# get start and end date
start_date, end_date = get_start_end_date()

# get portfolio and prospects data
mypfs_df = get_mypfs_df()
mypps_df = get_mypps_df()
myinvmt_df = get_myinvmt_df()

# merge above datasets
mypf_df = pd.merge(mypfs_df, mypps_df, on="Symbol")

# seggregate dm and sv portfolio
dm_pf = mypf_df[mypf_df['InPortfolio'] == 'DM']
sv_pf = mypf_df[mypf_df['InPortfolio'] == 'SV']

# build portfolio stock dataframe
dm_stocks = get_stock_ids(dm_pf)
sv_stocks = get_stock_ids(sv_pf)
df_stocks = pd.concat([dm_pf,sv_pf], ignore_index = True)

# arrange common and diff stock features
common_cols = ['Symbol', 'Target', 'Criteria', 'Strategy', 'CumlRnk', 'LatestQtr', 'StarStock', 'Conviction', 'Category', 'InFolio', 'XIRR', 'MBQ']
diff_cols = ['Symbol', 'AvgCost', 'Shares']
df_stocks = arrange_features(df_stocks, common_cols, diff_cols)

# get common features
stock_ids = df_stocks['Symbol'].values
df_common_features = get_common_features(stock_ids, df_stocks)

df_common_features.reset_index(drop=True, inplace=True)
df_common_features.drop(['Date'], axis=1, inplace=True)
# get and print portfolio features
df_portfolio_features = get_portfolio_features(df_common_features)

print_portfolio_stats(df_portfolio_features, myinvmt_df)

df = df_portfolio_features
#plot_pie_chart(df, 'CapType', 'Current')
list_ox40n = list(df[df['MBQ'].str.contains('OX40N', na=False)]['Symbol'].values)

Run date time (IST): 2026-08-10 12:21:25
-------------------
qualified stocks: 88
with latest results: 30
still star stocks: 19
-------------------
Initial Investment:  1.46 C
CY Investment:  1.89 C
Reserve:  2.24 L
Current:  1.62 C
-------------------
Today PnL: 23.70 K (0.15%)
Current PnL: -30.27 L (-16.02%)
CY Booked + Current PnL: -26.05 L (-13.79%)
-------------------
Total profit:  3.89 L
Total loss:  -34.16 L
-------------------
Total Booked + Current PnL: 16.82 L (11.51%)
Total Booked PnL: 47.09 L (32.24%)
Curr Year Booked PnL: 4.22 L (2.61%)
Prev Year Booked PnL: 42.87 L (29.35%)
===================
Est FTT:  2.67 C
Est FTT PnL: 1.05 C (64.8%)
===================
Deployed:  1.46 C
Current:  1.62 C
CAGR/XIRR %: 4.71%

In [9]:
# top 5 near their targets
cols = ['Symbol', 'Today P/L%', 'Current P/L%', 'FTT%', 'OTT%', 'FTT Amt', 'Current P/L', 'Current', 'FTT', 'Dev%_PE', 'RSI_14','Conviction', 'Spread%',  'CumlRnk', 'RRR Ind', 'CurrAlloc%', 'Gained%', 'Criteria', 'Strategy', 'Category']
df_tmp = df_portfolio_features[~df_portfolio_features['Symbol'].isin(['ENRIN','BLUSPRING','DIGITIDE'])]
df_tmp = df_tmp.sort_values(by = 'FTT Amt', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
55,MEDANTA,1.42,26.28,0.66,27.12,1471.0,46389.0,222906.0,1486.00,22.38,71.0,X-SC,15.67,87.0,31.54,1.40,53.59,XY24,NTT,HEALTHCARE
52,M&M,0.53,11.16,6.89,18.82,18434.0,26869.0,267550.0,3762.88,-3.30,70.0,X-LC,5.36,25.0,1.46,1.68,21.37,X40N,ATH,AUTO
80,UNITDSPR,1.28,12.52,7.33,20.77,19311.0,29308.0,263452.0,1644.00,-0.15,72.0,X-MC,7.60,64.0,1.52,1.65,26.64,X40N,NTT,BREWERIES
79,TTKPRESTIG,-1.53,-21.15,26.95,0.09,21414.0,-21319.0,79458.0,770.00,84.42,43.0,M-SC,13.37,250.0,-1.00,0.50,43.01,OX40N,NTT,DURABLES
69,SIS,-1.82,-1.92,23.64,21.26,25743.0,-2134.0,108898.0,528.00,2598.45,47.0,H-SC,22.90,168.0,-0.08,0.68,61.91,OX40N,NTT,MISC

In [10]:
# top 5 today
df_tmp = df_portfolio_features.sort_values(by = 'Today P/L%', ascending=False)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
58,QUESS,5.00,33.95,29.82,73.90,42658.0,36258.0,143051.0,424.00,-27.82,66.0,X-SC,39.57,80.0,0.85,0.90,96.89,XY24,NTT,MISC
0,5PAISA,4.99,-26.53,53.67,12.90,86159.0,-57962.0,160534.0,593.00,136.78,62.0,H-SC,11.69,170.0,-0.67,1.01,54.92,OX40N,NTT,FINANCE
25,FINCABLES,3.39,34.17,54.96,107.91,108875.0,50454.0,198098.0,1641.55,20.75,56.0,M-SC,17.41,220.0,0.46,1.24,49.04,OX40N,ATH,CABLES
82,VALIANTORG,2.98,-38.26,182.06,74.15,183906.0,-62591.0,101014.0,838.00,-281.53,64.0,H-SC,4.32,145.0,-0.34,0.63,50.32,XR,NTT,CHEMICALS
23,DMART,2.86,-2.22,34.40,31.42,104877.0,-6916.0,304874.0,5391.45,-18.71,50.0,X-LC,3.17,14.0,-0.07,1.91,10.02,X40N,ATH,FMCG

In [11]:
# bottom 5 today
df_tmp = df_portfolio_features.sort_values(by = 'Today P/L%', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
5,ATULAUTO,-9.56,-10.01,61.76,45.57,109559.0,-19737.0,177395.0,844.00,3851.35,53.0,M-SC,9.70,248.0,-0.18,1.11,36.51,XY24,NTT,AUTO
61,RECLTD,-4.52,-5.14,27.28,20.74,52574.0,-10450.0,192720.0,446.00,5.47,42.0,M-MC,3.47,191.0,-0.20,1.21,16.16,XY25,NTT,FINANCE
18,COFFEEDAY,-4.01,-47.41,157.23,35.27,93885.0,-53837.0,59712.0,80.00,-59.76,45.0,L-SC,4.97,266.0,-0.57,0.37,47.25,XR,NTT,HOTELS
28,GODREJCP,-2.12,-6.51,42.94,33.64,100174.0,-16249.0,233288.0,1469.04,-3.32,40.0,X-LC,5.14,32.0,-0.16,1.46,4.87,X40N,ATH,FMCG
56,PAGEIND,-1.83,2.17,30.76,33.59,84341.0,5811.0,274190.0,51217.29,-26.77,42.0,X-MC,9.03,55.0,0.07,1.72,30.21,X40,ATH,APPARELS

In [12]:
# top 5 to exit based on CumlRnk
df_tmp = df_portfolio_features[~df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])]
df_tmp = df_tmp[(df_tmp['Current P/L%'] > -1) & (df_tmp['Current P/L%'] < 1)].sort_values(by = 'CumlRnk', ascending=False)
df_tmp[cols].head()

Empty DataFrame
Columns: [Symbol, Today P/L%, Current P/L%, FTT%, OTT%, FTT Amt, Current P/L, Current, FTT, Dev%_PE, RSI_14, Conviction, Spread%, CumlRnk, RRR Ind, CurrAlloc%, Gained%, Criteria, Strategy, Category]
Index: []

In [13]:
# OX40N stocks to exit
df_tmp = df_portfolio_features[(df_portfolio_features['Symbol'].isin(list_ox40n))].sort_values(by = 'Current P/L%', ascending=False)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
25,FINCABLES,3.39,34.17,54.96,107.91,108875.0,50454.0,198098.0,1641.55,20.75,56.0,M-SC,17.41,220.0,0.46,1.24,49.04,OX40N,ATH,CABLES
69,SIS,-1.82,-1.92,23.64,21.26,25743.0,-2134.0,108898.0,528.00,2598.45,47.0,H-SC,22.90,168.0,-0.08,0.68,61.91,OX40N,NTT,MISC
43,INDIGOPNTS,1.87,-18.92,23.36,0.02,33062.0,-33025.0,141534.0,1408.00,115.96,67.0,M-SC,5.06,222.0,-1.00,0.89,60.58,OX40N,NTT,PAINTS
16,CERA,0.20,-20.58,55.99,23.89,78219.0,-36201.0,139702.0,9475.00,-23.39,45.0,H-SC,12.74,153.0,-0.46,0.88,35.80,OX40N,NTT,CERAMICS
79,TTKPRESTIG,-1.53,-21.15,26.95,0.09,21414.0,-21319.0,79458.0,770.00,84.42,43.0,M-SC,13.37,250.0,-1.00,0.50,43.01,OX40N,NTT,DURABLES

In [14]:
# top 5 to book for rotation
df_tmp = df_portfolio_features[(df_portfolio_features['Current P/L%'] > 20) ].sort_values(by = 'CumlRnk', ascending=False)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
25,FINCABLES,3.39,34.17,54.96,107.91,108875.0,50454.0,198098.0,1641.55,20.75,56.0,M-SC,17.41,220.0,0.46,1.24,49.04,OX40N,ATH,CABLES
55,MEDANTA,1.42,26.28,0.66,27.12,1471.0,46389.0,222906.0,1486.00,22.38,71.0,X-SC,15.67,87.0,31.54,1.40,53.59,XY24,NTT,HEALTHCARE
58,QUESS,5.00,33.95,29.82,73.90,42658.0,36258.0,143051.0,424.00,-27.82,66.0,X-SC,39.57,80.0,0.85,0.90,96.89,XY24,NTT,MISC

In [15]:
# top 5 to monitor for exit
df_tmp = df_portfolio_features[~df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])]
df_tmp = df_tmp[(df_tmp['Current P/L%'] > 0) ].sort_values(by = 'Dev%_PE', ascending=False)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
70,STARHEALTH,-0.46,9.77,34.16,47.26,105412.0,27461.0,308584.0,761.00,73.16,42.0,H-SC,17.28,173.0,0.26,1.93,33.42,XY24,NTT,INSURANCE
25,FINCABLES,3.39,34.17,54.96,107.91,108875.0,50454.0,198098.0,1641.55,20.75,56.0,M-SC,17.41,220.0,0.46,1.24,49.04,OX40N,ATH,CABLES
87,ZYDUSLIFE,0.24,17.78,15.05,35.51,37149.0,37261.0,246835.0,1285.01,2.70,50.0,H-MC,15.54,120.0,1.00,1.55,29.90,AR,ATH,PHARMA

In [16]:
# top 5 to book for rotation from weak conviction
df_tmp = df_portfolio_features[~df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])]
df_tmp = df_tmp[~df_tmp['Criteria'].isin(['XY25','XY24','X40', 'X40N'])].sort_values(by = 'RRR Ind', ascending=False)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
87,ZYDUSLIFE,0.24,17.78,15.05,35.51,37149.0,37261.0,246835.0,1285.01,2.70,50.0,H-MC,15.54,120.0,1.00,1.55,29.90,AR,ATH,PHARMA
25,FINCABLES,3.39,34.17,54.96,107.91,108875.0,50454.0,198098.0,1641.55,20.75,56.0,M-SC,17.41,220.0,0.46,1.24,49.04,OX40N,ATH,CABLES
69,SIS,-1.82,-1.92,23.64,21.26,25743.0,-2134.0,108898.0,528.00,2598.45,47.0,H-SC,22.90,168.0,-0.08,0.68,61.91,OX40N,NTT,MISC
3,ALKYLAMINE,0.78,-18.71,136.87,92.54,112329.0,-18893.0,82070.0,4520.85,-12.91,58.0,H-SC,13.54,142.0,-0.17,0.51,55.84,SR,ATH,CHEMICALS
42,INDIAMART,2.17,-22.95,160.77,100.92,152778.0,-28307.0,95029.0,4675.60,-65.23,43.0,H-SC,12.20,140.0,-0.19,0.60,2.87,AR,ATH,MISC

In [17]:
# top 5 to accumulate based on lowest RSI_14
df_tmp = df_portfolio_features[df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])].sort_values(by = 'RSI_14', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
57,PGHH,-0.03,-36.35,107.39,32.01,145956.0,-77608.0,135912.0,17616.87,-56.92,35.0,X-MC,19.22,57.0,-0.53,0.85,0.21,X40,ATH,FMCG
34,HDFCBANK,0.51,-10.26,46.04,31.05,121104.0,-30080.0,263040.0,1073.00,-25.47,37.0,X-LC,10.96,26.0,-0.25,1.65,2.10,X40,BTT,BANKS
35,HDFCLIFE,-0.09,-7.48,50.40,39.15,116920.0,-18752.0,231985.0,811.41,-31.13,39.0,X-LC,16.10,31.0,-0.16,1.45,0.66,X40,ATH,INSURANCE
20,DABUR,0.61,-19.35,78.18,43.70,156408.0,-48006.0,200062.0,735.00,-26.86,40.0,X-MC,9.23,70.0,-0.31,1.25,1.80,XY24,BTT,FMCG
84,VOLTAS,-0.87,-0.35,45.71,45.20,87338.0,-672.0,191070.0,1856.00,14.09,40.0,X-MC,4.06,79.0,-0.01,1.20,4.72,XY25,NTT,AC

In [18]:
# top 5 to accumulate based on Spread and CumlRnk
df_tmp = df_portfolio_features[df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])]
df_tmp = df_tmp[(df_tmp['CumlRnk'] < 100)].sort_values(by = 'Spread%', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
19,COLPAL,-0.53,-23.33,82.41,39.86,166411.0,-61435.0,201930.0,3683.41,-7.20,44.0,X-MC,1.63,62.0,-0.37,1.27,14.22,XY25,ATH,FMCG
11,BERGEPAINT,1.88,-0.39,25.81,25.32,66264.0,-1011.0,256738.0,680.00,-5.80,63.0,X-MC,2.14,68.0,-0.02,1.61,34.63,XY24,NTT,PAINTS
8,BAJAJHLDNG,1.41,2.62,24.97,28.24,65598.0,6701.0,262706.0,14274.15,-5.41,65.0,X-LC,2.71,28.0,0.10,1.65,32.22,X40,ATH,FINANCE
23,DMART,2.86,-2.22,34.40,31.42,104877.0,-6916.0,304874.0,5391.45,-18.71,50.0,X-LC,3.17,14.0,-0.07,1.91,10.02,X40N,ATH,FMCG
26,GILLETTE,-0.04,-9.25,42.94,29.72,98940.0,-23481.0,230415.0,10978.86,-30.33,45.0,X-SC,3.36,83.0,-0.24,1.44,5.89,X40,ATH,FMCG

In [19]:
# top 5 to accumulate based on lowest Gained%
df_tmp = df_portfolio_features[df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])].sort_values(by = 'Gained%', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
57,PGHH,-0.03,-36.35,107.39,32.01,145956.0,-77608.0,135912.0,17616.87,-56.92,35.0,X-MC,19.22,57.0,-0.53,0.85,0.21,X40,ATH,FMCG
35,HDFCLIFE,-0.09,-7.48,50.40,39.15,116920.0,-18752.0,231985.0,811.41,-31.13,39.0,X-LC,16.10,31.0,-0.16,1.45,0.66,X40,ATH,INSURANCE
20,DABUR,0.61,-19.35,78.18,43.70,156408.0,-48006.0,200062.0,735.00,-26.86,40.0,X-MC,9.23,70.0,-0.31,1.25,1.80,XY24,BTT,FMCG
34,HDFCBANK,0.51,-10.26,46.04,31.05,121104.0,-30080.0,263040.0,1073.00,-25.47,37.0,X-LC,10.96,26.0,-0.25,1.65,2.10,X40,BTT,BANKS
47,ITC,-0.87,-21.76,59.38,24.70,184568.0,-86452.0,310826.0,452.00,-59.16,47.0,X-LC,11.24,1.0,-0.47,1.95,2.92,X40,NTT,FMCG

In [20]:
# top 5 to accumulate based on lowest CurrAlloc%
df_tmp = df_portfolio_features[df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])].sort_values(by = 'CurrAlloc%', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
10,BATAINDIA,-0.31,-53.67,191.82,35.20,114353.0,-69055.0,59615.0,2096.00,-21.88,60.0,X-SC,14.04,91.0,-0.60,0.37,19.77,X40,NTT,FOOTWEAR
62,RELAXO,0.57,-44.85,176.15,52.31,141026.0,-65100.0,80060.0,1176.00,-41.24,61.0,X-SC,11.78,92.0,-0.46,0.50,79.00,X40N,NTT,FOOTWEAR
57,PGHH,-0.03,-36.35,107.39,32.01,145956.0,-77608.0,135912.0,17616.87,-56.92,35.0,X-MC,19.22,57.0,-0.53,0.85,0.21,X40,ATH,FMCG
58,QUESS,5.00,33.95,29.82,73.90,42658.0,36258.0,143051.0,424.00,-27.82,66.0,X-SC,39.57,80.0,0.85,0.90,96.89,XY24,NTT,MISC
40,ICICIPRULI,-0.81,-17.76,58.40,30.28,94621.0,-34983.0,162022.0,787.27,-39.83,45.0,X-MC,13.52,78.0,-0.37,1.02,7.95,X40,ATH,INSURANCE

In [21]:
# top 5 to accumulate based on CumlRnk
df_tmp = df_portfolio_features.sort_values(by = 'CumlRnk', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
47,ITC,-0.87,-21.76,59.38,24.70,184568.0,-86452.0,310826.0,452.00,-59.16,47.0,X-LC,11.24,1.0,-0.47,1.95,2.92,X40,NTT,FMCG
75,TCS,-0.40,-28.28,73.18,24.20,243139.0,-131025.0,332248.0,4230.71,-39.36,62.0,X-LC,15.48,2.0,-0.54,2.08,23.90,X40,ATH,IT
45,INFY,0.78,-15.69,66.51,40.38,211097.0,-59078.0,317392.0,1972.00,-36.50,64.0,X-LC,16.29,3.0,-0.28,1.99,20.20,X40,NTT,IT
77,TMPV,0.48,-17.05,72.09,42.75,248829.0,-70943.0,345164.0,600.00,-83.62,57.0,X-LC,5.29,4.0,-0.29,2.16,18.69,XY24,NTT,AUTO
33,HCLTECH,0.41,-8.90,36.07,23.97,101701.0,-27531.0,281955.0,1853.42,-6.95,69.0,X-LC,13.31,8.0,-0.27,1.77,33.05,X40,ATH,IT

In [22]:
# top 5 for average up
df_tmp = df_portfolio_features[(df_portfolio_features['Dev%_200'] > 5)].sort_values(by = 'CurrAlloc%', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
44,INDUSINDBK,-0.28,-24.76,76.63,32.89,44514.0,-19118.0,58089.0,1800.00,-373.11,55.0,L-MC,13.99,258.0,-0.43,0.36,43.21,XR,NTT,BANKS
62,RELAXO,0.57,-44.85,176.15,52.31,141026.0,-65100.0,80060.0,1176.00,-41.24,61.0,X-SC,11.78,92.0,-0.46,0.50,79.00,X40N,NTT,FOOTWEAR
79,TTKPRESTIG,-1.53,-21.15,26.95,0.09,21414.0,-21319.0,79458.0,770.00,84.42,43.0,M-SC,13.37,250.0,-1.00,0.50,43.01,OX40N,NTT,DURABLES
3,ALKYLAMINE,0.78,-18.71,136.87,92.54,112329.0,-18893.0,82070.0,4520.85,-12.91,58.0,H-SC,13.54,142.0,-0.17,0.51,55.84,SR,ATH,CHEMICALS
12,BOSCH-HCIL,2.01,-24.80,32.97,-0.01,31686.0,-31698.0,96107.0,2282.00,19573.91,86.0,M-SC,3.52,231.0,-1.00,0.60,63.59,OX40N,BTT,AC

In [23]:
# top 5 RSP
df_tmp = df_portfolio_features.sort_values(by = 'RSP', ascending=False)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
12,BOSCH-HCIL,2.01,-24.80,32.97,-0.01,31686.0,-31698.0,96107.0,2282.00,19573.91,86.0,M-SC,3.52,231.0,-1.00,0.60,63.59,OX40N,BTT,AC
75,TCS,-0.40,-28.28,73.18,24.20,243139.0,-131025.0,332248.0,4230.71,-39.36,62.0,X-LC,15.48,2.0,-0.54,2.08,23.90,X40,ATH,IT
33,HCLTECH,0.41,-8.90,36.07,23.97,101701.0,-27531.0,281955.0,1853.42,-6.95,69.0,X-LC,13.31,8.0,-0.27,1.77,33.05,X40,ATH,IT
58,QUESS,5.00,33.95,29.82,73.90,42658.0,36258.0,143051.0,424.00,-27.82,66.0,X-SC,39.57,80.0,0.85,0.90,96.89,XY24,NTT,MISC
68,SIEMENS,0.87,6.79,16.96,24.90,33704.0,12630.0,198725.0,4648.66,66.91,71.0,H-LC,10.98,51.0,0.37,1.25,40.21,AR,ATH,ELECTRICAL

In [24]:
# Top N allocation
df_tmp = df_portfolio_features.sort_values(by = 'CurrAlloc%', ascending=False)
top_n_values = [10, 25, 50]

sum_df = pd.DataFrame({
    'Top_N': top_n_values,
    'Sum_Alloc%': [df_tmp['CurrAlloc%'].head(n).sum() for n in top_n_values]
})

sum_df

   Top_N  Sum_Alloc%
0     10       19.74
1     25       44.77
2     50       76.80

In [25]:
# market-cap-wise allocation
df_tmp = df_portfolio_features[cols]
df_tmp.groupby(df_tmp['Conviction'].str[-2:])['CurrAlloc%'].sum().sort_values(ascending=False)

Conviction
SC    39.34
LC    37.80
MC    22.86
Name: CurrAlloc%, dtype: float64

In [26]:
# criteria-wise allocation
df_portfolio_features.groupby('Criteria')['CurrAlloc%'].sum().sort_values(ascending=False)

Criteria
X40      26.35
XY24     25.00
X40N     18.52
XR        9.06
XY25      7.22
OX40N     6.93
AR        6.07
SR        0.85
Name: CurrAlloc%, dtype: float64

In [27]:
# conviction-wise allocation
df_portfolio_features.groupby('Conviction')['CurrAlloc%'].sum().sort_values(ascending=False)

Conviction
X-LC    35.74
H-SC    19.25
X-MC    18.67
X-SC     9.99
M-SC     9.59
H-MC     2.62
H-LC     1.25
M-MC     1.21
M-LC     0.81
L-SC     0.51
L-MC     0.36
Name: CurrAlloc%, dtype: float64

In [28]:
# sector-wise stats
df_tmp = df_portfolio_features.groupby('Category')[['CurrAlloc%', 'Current', 'Current P/L', 'FTT Amt']].sum().sort_values(by=['Current', 'Current P/L'], ascending=False)
df_tmp['Current P/L%'] = round(df_tmp['Current P/L'] * 100 / df_tmp['Current'], 2)
df_tmp['FTT%'] = round(df_tmp['FTT Amt'] * 100 / df_tmp['Current'], 2)
cols = ['CurrAlloc%', 'Current P/L%', 'FTT%']
df_tmp[cols].sort_values(by=['CurrAlloc%'], ascending=False)

               CurrAlloc%  Current P/L%    FTT%
Category
FMCG                15.47        -20.76   64.25
IT                  11.25        -32.84   98.78
FINANCE              9.28        -15.29   63.74
AUTO                 8.36         -1.32   37.61
MISC                 6.92        -21.63   73.81
BANKS                6.05        -10.34   57.93
PHARMA               5.58          7.00   19.38
INSURANCE            5.49         -6.04   43.53
PAINTS               5.47        -12.91   32.17
ELECTRICAL           4.13         -7.45   45.08
HEALTHCARE           2.11         -6.58   34.39
AC                   1.80        -11.27   41.45
APPARELS             1.72          2.12   30.76
REFINERIES           1.70         -9.86   46.77
FOOTWEAR             1.66        -65.88  132.40
BREWERIES            1.65         11.12    7.33
DURABLES             1.50        -61.78  101.14
TRAVEL               1.47        -89.76  184.77
CERAMICS             1.35        -42.51   85.80
CABLES               1.24         25.47   54.96
ENGINEERING          1.20        -26.37   84.18
CHEMICALS            1.14        -44.51  161.80
CEMENT               1.03        -63.88  186.49
JEWELLERY            0.99       -103.75  174.54
ENTERTAINMENT        0.68        -78.24  184.54
TEXTILES             0.39        -49.40   92.00
HOTELS               0.37        -90.16  157.23

In [29]:
# money to be made criteria-wise
df_portfolio_features.groupby('Criteria')['FTT Amt'].agg(['sum', 'count']).sort_values(by='sum', ascending=False)

                sum  count
Criteria
XY24      3411048.0     20
X40       2019131.0     18
XR        1349305.0     13
X40N      1125118.0     12
AR        1064682.0      8
OX40N      687771.0     10
XY25       549368.0      5
SR         280469.0      2

In [30]:
# money to be made conviction-wise
df_portfolio_features.groupby('Conviction')['FTT Amt'].agg(['sum', 'count']).sort_values(by='sum', ascending=False)

                  sum  count
Conviction
H-SC        3278644.0     23
X-LC        2353998.0     20
X-MC        1474733.0     14
M-SC        1387618.0     14
X-SC        1209771.0      9
H-MC         279614.0      2
L-SC         209372.0      2
M-LC         162350.0      1
M-MC          52574.0      1
L-MC          44514.0      1
H-LC          33704.0      1

In [31]:
# money to be made criteria and conviction-wise
df_portfolio_features.groupby(['Conviction', 'Criteria'])['FTT Amt'].agg(['sum', 'count']).sort_values(by='sum', ascending=False)

                           sum  count
Conviction Criteria
X-LC       X40       1152638.0      9
H-SC       XY24       986540.0      5
           AR         917413.0      5
M-SC       XY24       839009.0      6
H-SC       XR         802861.0      7
X-SC       XY24       703179.0      4
X-MC       X40        653200.0      7
X-LC       X40N       486707.0      6
           XY24       417183.0      2
X-MC       X40N       345112.0      3
X-SC       X40N       293299.0      3
H-SC       OX40N      291361.0      4
M-SC       OX40N      280923.0      5
H-SC       SR         280469.0      2
X-MC       XY25       253749.0      2
X-LC       XY25       243045.0      2
H-MC       XY24       242465.0      1
X-MC       XY24       222672.0      2
X-SC       X40        213293.0      2
M-SC       XR         191270.0      2
M-LC       XR         162350.0      1
L-SC       OX40N      115487.0      1
           XR          93885.0      1
M-SC       AR          76416.0      1
X-LC       XR          54425.0      1
M-MC       XY25        52574.0      1
L-MC       XR          44514.0      1
H-MC       AR          37149.0      1
H-LC       AR          33704.0      1

In [32]:
# notebook execution time

end_time = time.time()
execution_time = round(end_time - start_time, 0)
print(f"Notebook execution time: {execution_time} seconds")

Notebook execution time: 30.0 seconds