<a href="https://colab.research.google.com/github/ankit-rathi/Quantvesting_v2/blob/main/myStocks_Portfolio_Analysis.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
'''
!pip install pandas==2.2.2 -qq
!pip install pyxirr -qq
!pip install ta -qq
!pip install yfinance==0.2.59 -qq
'''

'\n!pip install pandas==2.2.2 -qq\n!pip install pyxirr -qq\n!pip install ta -qq\n!pip install yfinance==0.2.59 -qq\n'

In [2]:
# import libraries

import numpy as np
import pandas as pd
import datetime
import warnings
warnings.filterwarnings('ignore')
import yfinance as yfin
import ta
import matplotlib.pyplot as plt
import requests

In [3]:
# notebook start time
import time
import datetime
import pytz

start_time = time.time()

# function to print date timestamp
def print_date_time():
  tz_NY = pytz.timezone('Asia/Kolkata')
  datetime_NY = datetime.datetime.now(tz_NY)
  print("Run date time (IST):", datetime_NY.strftime("%Y-%m-%d %H:%M:%S"))

In [4]:
# function to get booked and reserved amount
def get_amt():
  # fetch the JSON data from the URL
  url = "https://raw.githubusercontent.com/ankit-rathi/Tradevesting_v1/main/data/myPortfolioAmts.json"
  response = requests.get(url)
  pf_amts = response.json()  # parse the JSON data

  # extract values from the JSON
  py_booked_amt_dm = pf_amts["py_booked_amt_dm"]
  py_booked_amt_sv = pf_amts["py_booked_amt_sv"]
  cy_booked_amt_dm = pf_amts["cy_booked_amt_dm"]
  cy_booked_amt_sv = pf_amts["cy_booked_amt_sv"]
  reserve_amt_dm = pf_amts["reserve_amt_dm"]
  reserve_amt_sv = pf_amts["reserve_amt_sv"]

  # perform calculations
  py_booked_amt = py_booked_amt_dm + py_booked_amt_sv
  cy_booked_amt = cy_booked_amt_dm + cy_booked_amt_sv
  reserve_amt = reserve_amt_dm + reserve_amt_sv
  total_booked_amt = py_booked_amt + cy_booked_amt

  return total_booked_amt, reserve_amt, cy_booked_amt, py_booked_amt

gen_output = 0

In [5]:
# function to format the amount
def format_amt(number):
    abs_number = abs(number)

    if abs_number >= 1_00_00_000:  # Crores
        formatted_amt = f"{number / 1_00_00_000:.2f} C"
    elif abs_number >= 1_00_000:  # Lakhs
        formatted_amt = f"{number / 1_00_000:.2f} L"
    elif abs_number >= 1_000:  # Thousands
        formatted_amt = f"{number / 1_000:.2f} K"
    else:
        formatted_amt = f"{number:.2f}"

    return formatted_amt

# function to set start and end date
def get_start_end_date():
  start_date = (datetime.date.today() + datetime.timedelta(days=-365)).strftime('%Y-%m-%d')
  end_date = (datetime.date.today() + datetime.timedelta(days=1)).strftime('%Y-%m-%d')
  return start_date, end_date

# function to fetch my portfolio csv
def get_mypfs_df():
  mypfs_df = pd.read_csv('https://raw.githubusercontent.com/ankit-rathi/Tradevesting_v1/main/data/myPortfolioStocks.csv')
  return mypfs_df

# function to fetch my prospects csv
def get_mypps_df():
  mypps_df = pd.read_csv('https://raw.githubusercontent.com/ankit-rathi/Tradevesting_v1/main/data/myProspectsScrips.csv')
  return mypps_df

# function to fetch screener data
def get_myscreen_df():
  myscreen_df = pd.read_csv('https://raw.githubusercontent.com/ankit-rathi/Tradevesting_v1/main/data/myScreenerDB.csv')
  return myscreen_df

# function to fetch momentum data
def get_myinvmt_df():
  myinvmt_df = pd.read_csv('https://raw.githubusercontent.com/ankit-rathi/Tradevesting_v1/main/data/myInvestments.csv')
  return myinvmt_df

# function to get the stock ids
def get_stock_ids(df_pf):
  stock_n100 = df_pf['Symbol'].unique()

  exclude = ['CADILAHC','MMTC', 'MASFIN']

  stock_ids = df_pf[~df_pf['Symbol'].isin(exclude) ]['Symbol'].unique()

  #mypf = mypf[mypf.Forecast.notnull()]
  #stock_ids = mypf['Symbol'].unique()

  #stock_ids.sort()
  return stock_ids

# get features from screener data
def get_screener_features():
  myscreen_df = get_myscreen_df()
  cols = ['Symbol', 'EPS', 'MedPE', 'ROCE%', 'ROE%', 'CapType']
  return myscreen_df[cols]

# get relative strength
def get_relative_strength(stock_list):

    # Dictionary to store stock tickers and their corresponding percentage price change
    stock_changes = {}

    # Loop through each stock and fetch its price data
    for stock in stock_list:
        try:
            # Download the stock data for the given date range
            stock_data = yfin.Ticker(stock + '.NS').history(period='1mo', interval='1d')[map(str.title, ['open', 'close', 'low', 'high', 'volume'])]

            # Calculate the percentage change for the stock
            if len(stock_data) > 0:
                start_price = stock_data['Close'].iloc[0]
                end_price = stock_data['Close'].iloc[-1]
                percent_change = round(((end_price - start_price) / start_price) * 100, 2)
                stock_changes[stock] = percent_change
            else:
                stock_changes[stock] = np.nan  # If no data is available, set to NaN

        except Exception as e:
            print(f"Error fetching data for {stock}: {e}")
            stock_changes[stock] = np.nan

    # Create a DataFrame with stock tickers and their percentage changes
    df = pd.DataFrame(list(stock_changes.items()), columns=['Symbol', 'Percent_Change'])

    # Drop any stocks with missing data (NaN values)
    df = df.dropna()

    # Calculate the percentile rank based on percentage change
    df['RSP'] = round(df['Percent_Change'].rank(pct=True) * 100, 2)
    cols = ['Symbol', 'RSP']
    df = df[cols]
    # Sort by percentile rank (optional)
    df = df.sort_values(by='RSP', ascending=False).reset_index(drop=True)

    return df

In [6]:
# function to get stock technicals
def stock_prec_dev(stock_symbol):
    #stock_symbol = 'ULTRACEMCO.NS'
    short_window = 20
    mid_window = 50
    long_window = 200
    moving_avg = 'SMA'

    start = datetime.datetime(*map(int, start_date.split('-')))
    end = datetime.datetime(*map(int, end_date.split('-')))

    stock_df = yfin.Ticker(stock_symbol + '.NS').history(period='max', interval='1d')[map(str.title, ['open', 'close', 'low', 'high', 'volume'])]

    stock_df['Max'] = round(max(stock_df['Close']),2)
    stock_df = stock_df[(stock_df.index <= end_date) & (stock_df.index >= start_date)]
    stock_df['200_SMA'] = round(stock_df['Close'].rolling(window = 200, min_periods = 1).mean(),0)
    stock_df['Dev%_200'] = round((stock_df['Close'] - stock_df['200_SMA'])*100/stock_df['200_SMA'],2)
    stock_df.dropna(axis = 0, inplace = True) # remove any null rows

    stock_df['20_SMA'] = stock_df['Close'].rolling(window=20).mean()
    stock_df['50_SMA'] = stock_df['Close'].rolling(window=50).mean()
    stock_df['Symbol'] = stock_symbol

    stock_df['Close'] = round(stock_df['Close'],2)
    stock_df['Min'] = round(min(stock_df['Close']),2)
    stock_df['RSI_14'] = ta.momentum.RSIIndicator(close=stock_df['Close'], window=14).rsi()
    stock_df['RSI_14'] = round(stock_df['RSI_14'],0)
    stock_df['Prev_Close'] = stock_df['Close'].shift(1)
    stock_df.drop(['Open', 'Low', 'High', 'Volume'], axis=1, inplace=True)
    stock_df = stock_df.tail(1)

    max_SMA = max(stock_df['20_SMA'].item(), stock_df['50_SMA'].item(), stock_df['200_SMA'].item())
    min_SMA = min(stock_df['20_SMA'].item(), stock_df['50_SMA'].item(), stock_df['200_SMA'].item())
    ABS_Spread = max_SMA - min_SMA
    stock_df['Spread%'] = round((ABS_Spread / stock_df['200_SMA'].item()) * 100,2)

    return stock_df

# function to compute stock attributes
def get_common_features(stock_ids, df_mypf):

  df_prec_dev = pd.DataFrame()
  df_tmp = get_screener_features()
  df_rs = get_relative_strength(stock_ids)

  for stock_id in stock_ids:
      tmp = stock_prec_dev(stock_id)
      tmp = tmp.reset_index()
      df_prec_dev = pd.concat([df_prec_dev, tmp], ignore_index = True)
  df_prec_dev = pd.merge(df_prec_dev, df_mypf, on= 'Symbol')
  df_prec_dev = pd.merge(df_prec_dev, df_tmp, on= 'Symbol', how='left')
  df_prec_dev = pd.merge(df_prec_dev, df_rs, on= 'Symbol', how='left')
  #print(df_prec_dev.columns)
  df_prec_dev['Curr_PE'] = round(df_prec_dev['Close']/df_prec_dev['EPS'],1)
  df_prec_dev['Dev%_PE'] = round((df_prec_dev['Curr_PE'] - df_prec_dev['MedPE'])*100/df_prec_dev['MedPE'],2)
  df_prec_dev['Conviction'] = df_prec_dev['Conviction'] + '-' + df_prec_dev['CapType']
  return df_prec_dev

# function to arrange stock features
def arrange_features(df_stocks, common_cols, diff_cols):
  df_stocks_common = df_stocks[common_cols].drop_duplicates()
  df_stocks_diff = df_stocks[diff_cols]
  df_stocks_diff['Investment'] = df_stocks_diff['AvgCost'] * df_stocks_diff['Shares']
  df_stocks_diff = df_stocks_diff.groupby(['Symbol'])[['Shares', 'Investment']].aggregate(['sum']).reset_index()
  df_stocks_diff.columns = ['Symbol', 'Shares', 'Investment']
  df_stocks_diff['AvgCost'] = round(df_stocks_diff['Investment']/df_stocks_diff['Shares'],2)
  df_stocks = pd.merge(df_stocks_diff, df_stocks_common, on='Symbol')
  return df_stocks

# plot fact distribution across dimension
def plot_pie_chart(df, dimension, fact):
  # grouping the data by category and calculating the sum of fact for each type
  grouped_data = df.groupby(dimension)[fact].sum()

  # sorting the grouped data in descending order
  grouped_data = grouped_data.sort_values(ascending=False)

  # creating a pie chart
  grouped_data.plot.pie(autopct='%1.1f%%', startangle=90, figsize=(6, 6))

  # adding a title and displaying the plot
  plt.title(f'{dimension} {fact} Distribution')
  plt.ylabel('')  # To hide the y-label
  plt.show()

In [7]:
# function to get portfolio features

def get_portfolio_features(df_common_features):

  print_date_time()
  print('-------------------')

  #df_common_features["Target"] = df_common_features["Target"].fillna(df_common_features["Max"])
  df_common_features['NTT'] = np.where(df_common_features['Strategy']== 'NTT', df_common_features["Target"], df_common_features['Max'])
  df_common_features['LTT'] = np.where(df_common_features['Strategy']== 'BTT', df_common_features["Target"], df_common_features['Max'])
  df_common_features['BOL'] = df_common_features['Min']

  tmp_df = df_common_features[df_common_features['Symbol'].isin(mypf_df[mypf_df['InPortfolio'] != 'NA'].Symbol.values)]
  print('qualified stocks: '+str(len(tmp_df['Symbol'].unique())))
  tmp_df1 = tmp_df[tmp_df['LatestQtr'] == 1]
  print('with latest results: '+str(len(tmp_df1['Symbol'].unique())))
  tmp_df1 = tmp_df1[tmp_df1['StarStock'] == 1]
  print('still star stocks: '+str(len(tmp_df1['Symbol'].unique())))
  tmp_df['Investment'] = tmp_df['AvgCost'] * tmp_df['Shares']
  tmp_df['Current'] = round(tmp_df['Close'] * tmp_df['Shares'],0)
  tmp_df['Previous'] = tmp_df['Prev_Close'] * tmp_df['Shares']
  tmp_df['EstimatedST'] = tmp_df['NTT'] * tmp_df['Shares']
  tmp_df['EstimatedLT'] = tmp_df['LTT'] * tmp_df['Shares']
  tmp_df['Current P/L'] = round((tmp_df['Current'] - tmp_df['Investment']),0)
  tmp_df['Today P/L%'] = round((tmp_df['Current'] - tmp_df['Previous'])*100/tmp_df['Previous'],2)
  tmp_df['Current P/L%'] = round((tmp_df['Current'] - tmp_df['Investment'])*100/tmp_df['Investment'],2)
  tmp_df['EstimatedST P/L%'] = round((tmp_df['EstimatedST'] - tmp_df['Investment'])*100/tmp_df['Investment'],2)
  tmp_df['EstimatedLT P/L%'] = round((tmp_df['EstimatedLT'] - tmp_df['Investment'])*100/tmp_df['Investment'],2)
  tmp_df['NTT%'] = round((tmp_df['NTT'] - tmp_df['Close'])*100/tmp_df['Close'],2)
  tmp_df['LTT%'] = round((tmp_df['LTT'] - tmp_df['Close'])*100/tmp_df['Close'],2)
  tmp_df['Gained%'] = round((tmp_df['Close'] - tmp_df['BOL'])*100/tmp_df['BOL'],2)
  investment = round(sum(tmp_df['AvgCost']*tmp_df['Shares']),0)
  current = round(sum(tmp_df['Close']*tmp_df['Shares']),0)
  tmp_df['InitAlloc%'] = round(tmp_df['Investment']*100/investment,2)
  tmp_df['CurrAlloc%'] = round(tmp_df['Current']*100/current,2)
  tmp_df['FTT'] = tmp_df['LTT']
  tmp_df.loc[tmp_df['Strategy'] == 'NTT', 'FTT'] = tmp_df['NTT']
  tmp_df['FTT%'] = tmp_df['LTT%']
  tmp_df.loc[tmp_df['Strategy'] == 'NTT', 'FTT%'] = tmp_df['NTT%']
  tmp_df['FTT Amt'] = round(tmp_df['FTT%'] * tmp_df['Current']/100,0)
  tmp_df['OTT%'] = round((tmp_df['FTT'] - tmp_df['AvgCost'])*100/tmp_df['AvgCost'],2)
  tmp_df['RRR Ind'] = round(tmp_df['Current P/L']/tmp_df['FTT Amt'],2)
  tmp_df['Risk Ind'] = round(tmp_df['Current P/L%']*tmp_df['CurrAlloc%'],0)

  return tmp_df

# function to print portfolio features
def print_portfolio_stats(df_portfolio_features, myinvmt_df):
  from pyxirr import xirr

  total_booked_amt, reserve_amt, cy_booked_amt, py_booked_amt = get_amt()

  dates = myinvmt_df['Date'].values
  dates = np.append(dates, datetime.date.today().strftime('%d-%b-%y'))
  investment = myinvmt_df['Investment'].values
  dates= pd.to_datetime(dates)

  current = round(sum(df_portfolio_features['Close']*df_portfolio_features['Shares']),0) + reserve_amt
  investment_xirr = np.append(investment, current)
  cagr = round(xirr(pd.DataFrame({"dates": dates, "amounts": investment_xirr}))*100,2)

  investment = -sum(investment)
  invested = round(sum(df_portfolio_features['AvgCost']*df_portfolio_features['Shares']),0) + reserve_amt
  previous = round(sum(df_portfolio_features['Prev_Close']*df_portfolio_features['Shares']),0) + reserve_amt
  cy_invested = investment + py_booked_amt

  today_pnl_amount = current-previous
  today_pnl_percentage = round((current-previous)*100/previous,2)

  curr_pnl_amount = current-invested
  curr_pnl_percentage = round((curr_pnl_amount)*100/(cy_invested),2)

  cy_pnl_amount = cy_booked_amt + curr_pnl_amount
  cy_pnl_percentage = round((cy_pnl_amount)*100/cy_invested,2)

  overall_pnl_amount = total_booked_amt + curr_pnl_amount
  overall_pnl_percentage = round((overall_pnl_amount)*100/investment,2)

  estimate_st = round(sum(df_portfolio_features['FTT']*df_portfolio_features['Shares']),0)  + reserve_amt
  est_st_pnl_amount = estimate_st-current
  est_st_pnl_percentage = round((est_st_pnl_amount)*100/current,2)

  estimate_lt = round(sum(df_portfolio_features['LTT']*df_portfolio_features['Shares']),0)  + reserve_amt
  est_lt_pnl_amount = estimate_lt-current
  est_lt_pnl_percentage = round((est_lt_pnl_amount)*100/current,2)

  total_profit = round(sum(df_portfolio_features[df_portfolio_features['Current P/L%'] > 0]['Current']) - sum(df_portfolio_features[df_portfolio_features['Current P/L%'] > 0]['Investment']),0)
  total_loss = round(sum(df_portfolio_features[df_portfolio_features['Current P/L%'] < 0]['Current']) - sum(df_portfolio_features[df_portfolio_features['Current P/L%'] < 0]['Investment']),0)

  cy_booked_percentage = round((cy_booked_amt)*100/current,2)
  py_booked_percentage = round((py_booked_amt)*100/investment,2)
  total_booked_percentage = round((total_booked_amt)*100/investment,2)

  print('-------------------')
  print('Initial Investment: ', format_amt(investment))
  print('CY Investment: ', format_amt(cy_invested))
  print('Reserve: ', format_amt(reserve_amt))
  print('Current: ',  format_amt(current))
  print('-------------------')
  print('Today PnL: '+ '{} ({}%)'.format(format_amt(today_pnl_amount), today_pnl_percentage))
  print('Current PnL: '+ '{} ({}%)'.format(format_amt(curr_pnl_amount), curr_pnl_percentage))
  print('CY Booked + Current PnL: '+ '{} ({}%)'.format(format_amt(cy_pnl_amount), cy_pnl_percentage))
  print('-------------------')
  print('Total profit: ', format_amt(total_profit))
  print('Total loss: ', format_amt(total_loss))
  print('-------------------')
  print('Total Booked + Current PnL: '+ '{} ({}%)'.format(format_amt(overall_pnl_amount), overall_pnl_percentage))
  print('Total Booked PnL: '+ '{} ({}%)'.format(format_amt(total_booked_amt), total_booked_percentage))
  print('Curr Year Booked PnL: '+ '{} ({}%)'.format(format_amt(cy_booked_amt), cy_booked_percentage))
  print('Prev Year Booked PnL: '+ '{} ({}%)'.format(format_amt(py_booked_amt), py_booked_percentage))
  print('===================')
  print('Est FTT: ',  format_amt(estimate_st))
  print('Est FTT PnL: '+ '{} ({}%)'.format(format_amt(est_st_pnl_amount), est_st_pnl_percentage))

  print('===================')
  print('Deployed: ', format_amt(investment))

  print('Current: ', format_amt(current))

  print('CAGR/XIRR %: '+'{}%'.format(cagr))

In [8]:
# get start and end date
start_date, end_date = get_start_end_date()

# get portfolio and prospects data
mypfs_df = get_mypfs_df()
mypps_df = get_mypps_df()
myinvmt_df = get_myinvmt_df()

# merge above datasets
mypf_df = pd.merge(mypfs_df, mypps_df, on="Symbol")

# seggregate dm and sv portfolio
dm_pf = mypf_df[mypf_df['InPortfolio'] == 'DM']
sv_pf = mypf_df[mypf_df['InPortfolio'] == 'SV']

# build portfolio stock dataframe
dm_stocks = get_stock_ids(dm_pf)
sv_stocks = get_stock_ids(sv_pf)
df_stocks = pd.concat([dm_pf,sv_pf], ignore_index = True)

# arrange common and diff stock features
common_cols = ['Symbol', 'Target', 'Criteria', 'Strategy', 'CumlRnk', 'LatestQtr', 'StarStock', 'Conviction', 'Category', 'InFolio', 'XIRR', 'MBQ']
diff_cols = ['Symbol', 'AvgCost', 'Shares']
df_stocks = arrange_features(df_stocks, common_cols, diff_cols)

# get common features
stock_ids = df_stocks['Symbol'].values
df_common_features = get_common_features(stock_ids, df_stocks)

df_common_features.reset_index(drop=True, inplace=True)
df_common_features.drop(['Date'], axis=1, inplace=True)
# get and print portfolio features
df_portfolio_features = get_portfolio_features(df_common_features)

print_portfolio_stats(df_portfolio_features, myinvmt_df)

df = df_portfolio_features
#plot_pie_chart(df, 'CapType', 'Current')
list_ox40n = list(df[df['MBQ'].str.contains('OX40N', na=False)]['Symbol'].values)

Run date time (IST): 2026-03-27 15:01:48
-------------------
qualified stocks: 86
with latest results: 26
still star stocks: 16
-------------------
Initial Investment:  1.36 C
CY Investment:  1.62 C
Reserve:  1.61 K
Current:  1.28 C
-------------------
Today PnL: -3.40 L (-2.59%)
Current PnL: -49.12 L (-30.23%)
CY Booked + Current PnL: -33.23 L (-20.45%)
-------------------
Total profit:  40.38 K
Total loss:  -49.52 L
-------------------
Total Booked + Current PnL: -6.25 L (-4.61%)
Total Booked PnL: 42.87 L (31.64%)
Curr Year Booked PnL: 15.89 L (12.41%)
Prev Year Booked PnL: 26.98 L (19.91%)
===================
Est FTT:  2.48 C
Est FTT PnL: 1.20 C (93.65%)
===================
Deployed:  1.36 C
Current:  1.28 C
CAGR/XIRR %: -2.78%

In [9]:
# top 5 near their targets
cols = ['Symbol', 'Today P/L%', 'Current P/L%', 'FTT%', 'OTT%', 'FTT Amt', 'Current P/L', 'Current', 'FTT', 'Dev%_PE', 'RSI_14','Conviction', 'Spread%',  'CumlRnk', 'RRR Ind', 'CurrAlloc%', 'Gained%', 'Criteria', 'Strategy', 'Category']
df_tmp = df_portfolio_features[~df_portfolio_features['Symbol'].isin(['ENRIN','BLUSPRING','DIGITIDE'])]
df_tmp = df_tmp.sort_values(by = 'FTT Amt', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
50,MASFIN,-2.83,-10.23,35.42,21.57,31155.0,-10020.0,87960.0,397.04,-22.76,40.0,H-SC,3.51,167.0,-0.32,0.69,19.97,XR,ATH,FINANCE
77,TTKPRESTIG,-0.06,-42.80,75.00,0.09,43230.0,-43137.0,57640.0,770.00,33.83,35.0,M-SC,20.61,250.0,-1.00,0.45,0.33,OX40N,NTT,DURABLES
37,ICICIGI,-1.20,-7.35,28.81,19.34,53412.0,-14715.0,185394.0,2252.93,-22.04,34.0,X-MC,4.47,66.0,-0.28,1.45,2.48,X40,ATH,INSURANCE
67,SONACOMS,-4.83,-15.79,65.18,39.09,55521.0,-15978.0,85181.0,804.02,-33.30,44.0,M-MC,6.69,193.0,-0.29,0.67,20.50,AR,ATH,AUTO
2,ABBOTINDIA,-1.80,-13.01,35.73,18.07,55589.0,-23275.0,155580.0,35195.00,-25.88,43.0,X-MC,10.52,58.0,-0.42,1.22,1.75,X40,ATH,PHARMA

In [10]:
# top 5 today
df_tmp = df_portfolio_features.sort_values(by = 'Today P/L%', ascending=False)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
66,SIS,1.45,-33.39,82.04,21.26,60679.0,-37069.0,73963.0,528.00,1732.64,49.0,H-SC,14.37,168.0,-0.61,0.58,9.97,OX40N,NTT,MISC
8,AWL,1.16,-36.30,162.19,67.02,368123.0,-129339.0,226970.0,485.00,-65.68,49.0,X-SC,26.05,81.0,-0.35,1.77,7.36,XY24,NTT,FMCG
84,WIPRO,1.03,-21.66,119.91,72.27,159166.0,-36710.0,132738.0,420.00,-29.24,35.0,M-LC,17.95,98.0,-0.23,1.04,1.84,XR,NTT,IT
73,TCS,0.56,-29.82,80.35,26.57,261246.0,-138138.0,325135.0,4311.59,-40.68,31.0,X-LC,17.85,2.0,-0.53,2.54,1.47,X40,ATH,IT
83,WHIRLPOOL,0.34,-35.09,180.25,81.92,134322.0,-40278.0,74520.0,2270.00,-62.04,41.0,M-SC,25.04,210.0,-0.30,0.58,4.68,XR,NTT,DURABLES

In [11]:
# bottom 5 today
df_tmp = df_portfolio_features.sort_values(by = 'Today P/L%', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
14,BOSCH-HCIL,-9.02,-51.92,107.97,-0.01,66346.0,-66356.0,61449.0,2282.0,12465.22,22.0,M-SC,6.01,231.0,-1.00,0.48,0.00,OX40N,BTT,AC
80,VALIANTORG,-8.32,-54.97,286.71,74.15,211242.0,-89927.0,73678.0,838.0,-232.25,43.0,H-SC,28.15,145.0,-0.43,0.58,9.64,XR,NTT,CHEMICALS
56,RAJOOENG,-6.87,-50.57,182.42,39.61,92432.0,-51830.0,50670.0,143.1,-66.59,32.0,H-SC,32.95,136.0,-0.56,0.40,0.00,AR,ATH,MISC
25,EASEMYTRIP,-6.74,-65.62,323.76,45.70,196820.0,-116023.0,60792.0,26.4,-36.79,33.0,M-SC,9.52,204.0,-0.59,0.47,0.16,XY24,NTT,TRAVEL
22,DEN,-6.53,-54.42,211.72,42.07,81504.0,-45968.0,38496.0,75.0,37.31,26.0,M-SC,19.72,235.0,-0.56,0.30,0.00,AR,NTT,ENTERTAINMENT

In [12]:
# top 5 to exit based on CumlRnk
df_tmp = df_portfolio_features[~df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])]
df_tmp = df_tmp[(df_tmp['Current P/L%'] > -1) & (df_tmp['Current P/L%'] < 1)].sort_values(by = 'CumlRnk', ascending=False)
df_tmp[cols].head()

Empty DataFrame
Columns: [Symbol, Today P/L%, Current P/L%, FTT%, OTT%, FTT Amt, Current P/L, Current, FTT, Dev%_PE, RSI_14, Conviction, Spread%, CumlRnk, RRR Ind, CurrAlloc%, Gained%, Criteria, Strategy, Category]
Index: []

In [13]:
# OX40N stocks to exit
df_tmp = df_portfolio_features[(df_portfolio_features['Symbol'].isin(list_ox40n))].sort_values(by = 'Current P/L%', ascending=False)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
26,FINCABLES,-3.19,2.03,103.77,107.91,156326.0,3003.0,150647.0,1641.55,-8.17,43.0,M-SC,7.90,220.0,0.02,1.18,13.34,OX40N,ATH,CABLES
66,SIS,1.45,-33.39,82.04,21.26,60679.0,-37069.0,73963.0,528.00,1732.64,49.0,H-SC,14.37,168.0,-0.61,0.58,9.97,OX40N,NTT,MISC
18,CERA,-1.13,-38.87,102.67,23.89,110398.0,-68376.0,107527.0,9475.00,-41.05,45.0,H-SC,19.14,153.0,-0.62,0.84,3.33,OX40N,NTT,CERAMICS
72,TATAELXSI,-1.52,-40.20,120.77,32.03,95215.0,-52995.0,78840.0,9161.00,-25.24,37.0,H-SC,21.27,158.0,-0.56,0.62,2.73,OX40N,NTT,IT
77,TTKPRESTIG,-0.06,-42.80,75.00,0.09,43230.0,-43137.0,57640.0,770.00,33.83,35.0,M-SC,20.61,250.0,-1.00,0.45,0.33,OX40N,NTT,DURABLES

In [14]:
# top 5 to book for rotation
df_tmp = df_portfolio_features[(df_portfolio_features['Current P/L%'] > 20) ].sort_values(by = 'CumlRnk', ascending=False)
df_tmp[cols].head()

Empty DataFrame
Columns: [Symbol, Today P/L%, Current P/L%, FTT%, OTT%, FTT Amt, Current P/L, Current, FTT, Dev%_PE, RSI_14, Conviction, Spread%, CumlRnk, RRR Ind, CurrAlloc%, Gained%, Criteria, Strategy, Category]
Index: []

In [15]:
# top 5 to monitor for exit
df_tmp = df_portfolio_features[~df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])]
df_tmp = df_tmp[(df_tmp['Current P/L%'] > 0) ].sort_values(by = 'Dev%_PE', ascending=False)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
26,FINCABLES,-3.19,2.03,103.77,107.91,156326.0,3003.0,150647.0,1641.55,-8.17,43.0,M-SC,7.90,220.0,0.02,1.18,13.34,OX40N,ATH,CABLES
1,ABB,-1.84,11.88,30.11,45.57,88133.0,31085.0,292704.0,7934.00,-28.06,51.0,H-MC,13.35,125.0,0.35,2.29,29.98,AR,NTT,ELECTRICAL

In [16]:
# top 5 to book for rotation from weak conviction
df_tmp = df_portfolio_features[~df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])]
df_tmp = df_tmp[~df_tmp['Criteria'].isin(['XY25','XY24','X40', 'X40N'])].sort_values(by = 'RRR Ind', ascending=False)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
1,ABB,-1.84,11.88,30.11,45.57,88133.0,31085.0,292704.0,7934.00,-28.06,51.0,H-MC,13.35,125.0,0.35,2.29,29.98,AR,NTT,ELECTRICAL
26,FINCABLES,-3.19,2.03,103.77,107.91,156326.0,3003.0,150647.0,1641.55,-8.17,43.0,M-SC,7.90,220.0,0.02,1.18,13.34,OX40N,ATH,CABLES
40,INDIAMART,-1.89,-15.02,143.26,106.72,150155.0,-18523.0,104813.0,4810.62,-61.72,35.0,H-SC,12.37,140.0,-0.12,0.82,4.85,AR,ATH,MISC
85,ZYDUSLIFE,-0.87,-5.53,43.57,35.63,86261.0,-11591.0,197983.0,1286.17,-17.57,49.0,H-MC,5.30,120.0,-0.13,1.55,10.22,AR,ATH,PHARMA
84,WIPRO,1.03,-21.66,119.91,72.27,159166.0,-36710.0,132738.0,420.00,-29.24,35.0,M-LC,17.95,98.0,-0.23,1.04,1.84,XR,NTT,IT

In [17]:
# top 5 to accumulate based on lowest RSI_14
df_tmp = df_portfolio_features[df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])].sort_values(by = 'RSI_14', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
53,PGHH,-3.39,-30.11,88.88,32.01,132637.0,-64288.0,149232.0,17616.87,-52.76,18.0,X-MC,17.16,57.0,-0.48,1.17,0.0,X40,ATH,FMCG
9,BAJAJHFL,-4.64,-32.59,140.52,62.13,258623.0,-88999.0,184047.0,181.50,-44.55,22.0,X-MC,20.64,60.0,-0.34,1.44,0.0,X40N,ATH,FINANCE
38,ICICIPRULI,-1.96,-12.30,49.06,30.73,84766.0,-24225.0,172780.0,790.00,-35.82,22.0,X-MC,5.57,78.0,-0.29,1.35,0.0,X40,ATH,INSURANCE
58,RELAXO,-5.87,-67.60,370.12,52.31,174060.0,-98132.0,47028.0,1176.00,-65.54,22.0,X-SC,28.51,92.0,-0.56,0.37,0.0,X40N,NTT,FOOTWEAR
27,GILLETTE,-2.49,-11.48,46.55,29.72,104619.0,-29151.0,224745.0,10978.86,-32.05,27.0,X-SC,11.82,83.0,-0.28,1.76,0.0,X40,ATH,FMCG

In [18]:
# top 5 to accumulate based on Spread and CumlRnk
df_tmp = df_portfolio_features[df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])]
df_tmp = df_tmp[(df_tmp['CumlRnk'] < 100)].sort_values(by = 'Spread%', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
65,SIEMENS,-1.62,-18.03,53.11,25.51,81019.0,-33545.0,152550.0,4671.50,28.15,44.0,H-LC,1.82,51.0,-0.41,1.19,12.34,AR,ATH,ELECTRICAL
78,UNITDSPR,-4.35,-7.84,31.04,20.77,66982.0,-18353.0,215791.0,1644.00,-18.34,38.0,X-MC,2.38,64.0,-0.27,1.69,0.00,X40N,NTT,BREWERIES
82,VOLTAS,-3.55,3.28,40.58,45.20,80361.0,6288.0,198030.0,1856.00,18.29,40.0,X-MC,3.35,79.0,0.08,1.55,10.30,XY25,NTT,AC
59,RELIANCE,-4.47,-13.34,44.59,25.30,77653.0,-26813.0,174150.0,1952.00,-15.42,38.0,X-LC,3.67,21.0,-0.35,1.36,16.27,XY25,BTT,REFINERIES
37,ICICIGI,-1.20,-7.35,28.81,19.34,53412.0,-14715.0,185394.0,2252.93,-22.04,34.0,X-MC,4.47,66.0,-0.28,1.45,2.48,X40,ATH,INSURANCE

In [19]:
# top 5 to accumulate based on lowest Gained%
df_tmp = df_portfolio_features[df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])].sort_values(by = 'Gained%', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
3,ACC,-3.90,-41.17,197.15,74.81,310984.0,-110388.0,157740.0,3906.00,-58.35,28.0,X-SC,19.11,85.0,-0.35,1.23,0.0,XY24,BTT,CEMENT
9,BAJAJHFL,-4.64,-32.59,140.52,62.13,258623.0,-88999.0,184047.0,181.50,-44.55,22.0,X-MC,20.64,60.0,-0.34,1.44,0.0,X40N,ATH,FINANCE
10,BAJAJHLDNG,-4.21,-18.17,57.91,29.22,90099.0,-34541.0,155584.0,14451.52,-24.33,31.0,X-LC,17.87,28.0,-0.38,1.22,0.0,X40,ATH,FINANCE
27,GILLETTE,-2.49,-11.48,46.55,29.72,104619.0,-29151.0,224745.0,10978.86,-32.05,27.0,X-SC,11.82,83.0,-0.28,1.76,0.0,X40,ATH,FMCG
28,GLAXO,-2.73,-9.34,53.49,39.15,96637.0,-18620.0,180664.0,3466.20,-30.71,31.0,X-MC,10.00,56.0,-0.19,1.41,0.0,X40,ATH,PHARMA

In [20]:
# top 5 to accumulate based on lowest CurrAlloc%
df_tmp = df_portfolio_features[df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])].sort_values(by = 'CurrAlloc%', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
58,RELAXO,-5.87,-67.60,370.12,52.31,174060.0,-98132.0,47028.0,1176.00,-65.54,22.0,X-SC,28.51,92.0,-0.56,0.37,0.00,X40N,NTT,FOOTWEAR
12,BATAINDIA,-3.55,-58.93,229.22,35.20,121124.0,-75828.0,52842.0,2096.00,-30.69,28.0,X-SC,32.33,91.0,-0.63,0.41,1.74,X40,NTT,FOOTWEAR
54,QUESS,-1.64,-28.73,144.01,73.90,109602.0,-30686.0,76107.0,424.00,-61.43,37.0,X-SC,21.78,80.0,-0.28,0.59,2.29,XY24,NTT,MISC
36,HONAUT,-3.88,-29.71,115.26,51.31,156235.0,-57288.0,135550.0,58357.33,-41.61,28.0,X-SC,16.67,90.0,-0.37,1.06,0.00,X40N,ATH,ELECTRICAL
51,MEDANTA,-2.58,-15.72,50.83,27.12,75617.0,-27752.0,148765.0,1486.00,-18.36,33.0,X-SC,13.42,87.0,-0.37,1.16,1.61,XY24,NTT,HEALTHCARE

In [21]:
# top 5 to accumulate based on CumlRnk
df_tmp = df_portfolio_features.sort_values(by = 'CumlRnk', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
45,ITC,-0.27,-22.32,53.27,19.06,140755.0,-75936.0,264230.0,452.00,-57.54,36.0,X-LC,18.92,1.0,-0.54,2.06,1.53,X40,NTT,FMCG
73,TCS,0.56,-29.82,80.35,26.57,261246.0,-138138.0,325135.0,4311.59,-40.68,31.0,X-LC,17.85,2.0,-0.53,2.54,1.47,X40,ATH,IT
43,INFY,-0.48,-13.35,54.92,34.24,148903.0,-41760.0,271128.0,1972.00,-31.79,41.0,X-LC,15.07,3.0,-0.28,2.12,4.27,X40,NTT,IT
75,TMPV,-4.50,-30.88,97.60,36.58,240053.0,-109885.0,245956.0,600.00,-85.81,35.0,X-LC,8.34,4.0,-0.46,1.92,0.00,XY24,NTT,AUTO
33,HCLTECH,-1.14,-11.38,39.74,23.83,85196.0,-27540.0,214384.0,1908.19,-6.95,44.0,X-LC,11.63,8.0,-0.32,1.68,4.09,X40,ATH,IT

In [22]:
# top 5 for average up
df_tmp = df_portfolio_features[(df_portfolio_features['Dev%_200'] > 5)].sort_values(by = 'CurrAlloc%', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
1,ABB,-1.84,11.88,30.11,45.57,88133.0,31085.0,292704.0,7934.0,-28.06,51.0,H-MC,13.35,125.0,0.35,2.29,29.98,AR,NTT,ELECTRICAL

In [23]:
# top 5 RSP
df_tmp = df_portfolio_features.sort_values(by = 'RSP', ascending=False)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
30,HAPPSTMNDS,-2.05,-51.32,279.72,84.85,174523.0,-65773.0,62392.0,1480.71,-42.16,51.0,H-SC,25.70,152.0,-0.38,0.49,15.54,AR,ATH,IT
5,ANGELONE,-1.79,-3.43,28.59,24.18,84208.0,-10462.0,294538.0,303.00,-85.87,52.0,X-SC,10.11,97.0,-0.12,2.30,13.37,X40N,NTT,FINANCE
24,DMART,0.01,-5.98,37.84,29.60,88802.0,-14922.0,234678.0,5391.45,-20.67,55.0,X-LC,6.86,14.0,-0.17,1.83,7.27,X40N,ATH,FMCG
1,ABB,-1.84,11.88,30.11,45.57,88133.0,31085.0,292704.0,7934.00,-28.06,51.0,H-MC,13.35,125.0,0.35,2.29,29.98,AR,NTT,ELECTRICAL
52,PAGEIND,-3.13,-17.54,62.64,34.11,138625.0,-47074.0,221305.0,51418.64,-40.84,47.0,X-MC,21.08,55.0,-0.34,1.73,4.69,X40,ATH,APPARELS

In [24]:
# Top N allocation
df_tmp = df_portfolio_features.sort_values(by = 'CurrAlloc%', ascending=False)
top_n_values = [10, 25, 50]

sum_df = pd.DataFrame({
    'Top_N': top_n_values,
    'Sum_Alloc%': [df_tmp['CurrAlloc%'].head(n).sum() for n in top_n_values]
})

sum_df

   Top_N  Sum_Alloc%
0     10       20.96
1     25       46.26
2     50       78.52

In [25]:
# market-cap-wise allocation
df_tmp = df_portfolio_features[cols]
df_tmp.groupby(df_tmp['Conviction'].str[-2:])['CurrAlloc%'].sum().sort_values(ascending=False)

Conviction
SC    44.19
MC    30.12
LC    25.74
Name: CurrAlloc%, dtype: float64

In [26]:
# criteria-wise allocation
df_portfolio_features.groupby('Criteria')['CurrAlloc%'].sum().sort_values(ascending=False)

Criteria
XY24     27.03
X40      25.56
X40N     15.24
AR        9.21
XR        8.24
XY25      7.36
OX40N     6.63
SR        0.78
Name: CurrAlloc%, dtype: float64

In [27]:
# conviction-wise allocation
df_portfolio_features.groupby('Conviction')['CurrAlloc%'].sum().sort_values(ascending=False)

Conviction
X-LC    23.51
X-MC    22.59
H-SC    21.61
X-SC    12.29
M-SC     9.77
H-MC     5.14
M-MC     2.04
H-LC     1.19
M-LC     1.04
L-SC     0.52
L-MC     0.35
Name: CurrAlloc%, dtype: float64

In [28]:
# sector-wise stats
df_tmp = df_portfolio_features.groupby('Category')[['CurrAlloc%', 'Current', 'Current P/L', 'FTT Amt']].sum().sort_values(by=['Current', 'Current P/L'], ascending=False)
df_tmp['Current P/L%'] = round(df_tmp['Current P/L'] * 100 / df_tmp['Current'], 2)
df_tmp['FTT%'] = round(df_tmp['FTT Amt'] * 100 / df_tmp['Current'], 2)
cols = ['CurrAlloc%', 'Current P/L%', 'FTT%']
df_tmp[cols].sort_values(by=['CurrAlloc%'], ascending=False)

               CurrAlloc%  Current P/L%    FTT%
Category
FMCG                15.20        -28.35   73.91
FINANCE             13.17        -27.67   79.70
IT                  11.96        -47.40  122.42
MISC                 6.93        -51.18  116.85
ELECTRICAL           6.56        -15.45   59.65
PAINTS               5.21        -47.83   73.50
INSURANCE            4.74        -11.75   49.99
BANKS                4.59        -30.96   97.44
PHARMA               4.18        -10.01   44.64
AUTO                 3.66        -39.93   95.45
AC                   2.03        -23.15   56.54
HEALTHCARE           1.87        -49.52   88.54
TRAVEL               1.77        -96.74  195.26
FOOTWEAR             1.77        -94.43  172.39
DURABLES             1.76        -71.49  113.21
APPARELS             1.73        -21.27   62.64
BREWERIES            1.69         -8.50   31.04
REALTY               1.48        -17.14   36.39
CERAMICS             1.38        -74.08  126.97
REFINERIES           1.36        -15.40   44.59
CEMENT               1.23        -69.98  197.15
CABLES               1.18          1.99  103.77
ENGINEERING          1.06        -78.46  160.08
CHEMICALS            1.01       -104.60  271.52
JEWELLERY            0.99       -152.97  240.85
ENTERTAINMENT        0.74       -104.61  226.64
TEXTILES             0.46        -56.73  101.43
HOTELS               0.34       -159.96  251.65

In [29]:
# money to be made criteria-wise
df_portfolio_features.groupby('Criteria')['FTT Amt'].agg(['sum', 'count']).sort_values(by='sum', ascending=False)

                sum  count
Criteria
XY24      4135313.0     21
X40       1906202.0     16
XR        1437030.0     12
AR        1395509.0     10
X40N      1350538.0     10
OX40N      945693.0     10
XY25       498290.0      5
SR         319043.0      2

In [30]:
# money to be made conviction-wise
df_portfolio_features.groupby('Conviction')['FTT Amt'].agg(['sum', 'count']).sort_values(by='sum', ascending=False)

                  sum  count
Conviction
H-SC        4029911.0     24
X-MC        1844496.0     15
X-LC        1768704.0     13
M-SC        1666856.0     14
X-SC        1607835.0     10
H-MC         421517.0      3
L-SC         224771.0      2
M-LC         159166.0      1
M-MC         125805.0      2
H-LC          81019.0      1
L-MC          57538.0      1

In [31]:
# money to be made criteria and conviction-wise
df_portfolio_features.groupby(['Conviction', 'Criteria'])['FTT Amt'].agg(['sum', 'count']).sort_values(by='sum', ascending=False)

                           sum  count
Conviction Criteria
H-SC       XY24      1387984.0      6
           AR        1003071.0      5
M-SC       XY24       963917.0      6
X-LC       X40        943739.0      7
H-SC       XR         916381.0      7
X-SC       XY24       864326.0      4
X-MC       X40        736720.0      7
           X40N       563562.0      4
X-SC       X40N       517766.0      4
M-SC       OX40N      427411.0      5
H-SC       OX40N      403432.0      4
X-LC       XY24       393313.0      2
H-SC       SR         319043.0      2
X-MC       XY24       278650.0      2
X-LC       X40N       269210.0      2
X-MC       XY25       265564.0      2
H-MC       XY24       247123.0      1
X-SC       X40        225743.0      2
M-SC       XR         194024.0      2
H-MC       AR         174394.0      2
X-LC       XY25       162442.0      2
M-LC       XR         159166.0      1
L-SC       OX40N      114850.0      1
           XR         109921.0      1
M-SC       AR          81504.0      1
H-LC       AR          81019.0      1
M-MC       XY25        70284.0      1
L-MC       XR          57538.0      1
M-MC       AR          55521.0      1

In [32]:
# notebook execution time

end_time = time.time()
execution_time = round(end_time - start_time, 0)
print(f"Notebook execution time: {execution_time} seconds")

Notebook execution time: 25.0 seconds