<a href="https://colab.research.google.com/github/ankit-rathi/Quantvesting_v2/blob/main/myStocks_Portfolio_Analysis.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
'''
!pip install pandas==2.2.2 -qq
!pip install pyxirr -qq
!pip install ta -qq
!pip install yfinance==0.2.59 -qq
'''

'\n!pip install pandas==2.2.2 -qq\n!pip install pyxirr -qq\n!pip install ta -qq\n!pip install yfinance==0.2.59 -qq\n'

In [2]:
# import libraries

import numpy as np
import pandas as pd
import datetime
import warnings
warnings.filterwarnings('ignore')
import yfinance as yfin
import ta
import matplotlib.pyplot as plt
import requests

In [3]:
# notebook start time
import time
import datetime
import pytz

start_time = time.time()

# function to print date timestamp
def print_date_time():
  tz_NY = pytz.timezone('Asia/Kolkata')
  datetime_NY = datetime.datetime.now(tz_NY)
  print("Run date time (IST):", datetime_NY.strftime("%Y-%m-%d %H:%M:%S"))

In [4]:
# function to get booked and reserved amount
def get_amt():
  # fetch the JSON data from the URL
  url = "https://raw.githubusercontent.com/ankit-rathi/Tradevesting_v1/main/data/myPortfolioAmts.json"
  response = requests.get(url)
  pf_amts = response.json()  # parse the JSON data

  # extract values from the JSON
  py_booked_amt_dm = pf_amts["py_booked_amt_dm"]
  py_booked_amt_sv = pf_amts["py_booked_amt_sv"]
  cy_booked_amt_dm = pf_amts["cy_booked_amt_dm"]
  cy_booked_amt_sv = pf_amts["cy_booked_amt_sv"]
  reserve_amt_dm = pf_amts["reserve_amt_dm"]
  reserve_amt_sv = pf_amts["reserve_amt_sv"]

  # perform calculations
  py_booked_amt = py_booked_amt_dm + py_booked_amt_sv
  cy_booked_amt = cy_booked_amt_dm + cy_booked_amt_sv
  reserve_amt = reserve_amt_dm + reserve_amt_sv
  total_booked_amt = py_booked_amt + cy_booked_amt

  return total_booked_amt, reserve_amt, cy_booked_amt, py_booked_amt

gen_output = 0

In [5]:
# function to format the amount
def format_amt(number):
    abs_number = abs(number)

    if abs_number >= 1_00_00_000:  # Crores
        formatted_amt = f"{number / 1_00_00_000:.2f} C"
    elif abs_number >= 1_00_000:  # Lakhs
        formatted_amt = f"{number / 1_00_000:.2f} L"
    elif abs_number >= 1_000:  # Thousands
        formatted_amt = f"{number / 1_000:.2f} K"
    else:
        formatted_amt = f"{number:.2f}"

    return formatted_amt

# function to set start and end date
def get_start_end_date():
  start_date = (datetime.date.today() + datetime.timedelta(days=-365)).strftime('%Y-%m-%d')
  end_date = (datetime.date.today() + datetime.timedelta(days=1)).strftime('%Y-%m-%d')
  return start_date, end_date

# function to fetch my portfolio csv
def get_mypfs_df():
  mypfs_df = pd.read_csv('https://raw.githubusercontent.com/ankit-rathi/Tradevesting_v1/main/data/myPortfolioStocks.csv')
  return mypfs_df

# function to fetch my prospects csv
def get_mypps_df():
  mypps_df = pd.read_csv('https://raw.githubusercontent.com/ankit-rathi/Tradevesting_v1/main/data/myProspectsScrips.csv')
  return mypps_df

# function to fetch screener data
def get_myscreen_df():
  myscreen_df = pd.read_csv('https://raw.githubusercontent.com/ankit-rathi/Tradevesting_v1/main/data/myScreenerDB.csv')
  return myscreen_df

# function to fetch momentum data
def get_myinvmt_df():
  myinvmt_df = pd.read_csv('https://raw.githubusercontent.com/ankit-rathi/Tradevesting_v1/main/data/myInvestments.csv')
  return myinvmt_df

# function to get the stock ids
def get_stock_ids(df_pf):
  stock_n100 = df_pf['Symbol'].unique()

  exclude = ['CADILAHC','MMTC', 'MASFIN']

  stock_ids = df_pf[~df_pf['Symbol'].isin(exclude) ]['Symbol'].unique()

  #mypf = mypf[mypf.Forecast.notnull()]
  #stock_ids = mypf['Symbol'].unique()

  #stock_ids.sort()
  return stock_ids

# get features from screener data
def get_screener_features():
  myscreen_df = get_myscreen_df()
  cols = ['Symbol', 'EPS', 'MedPE', 'ROCE%', 'ROE%', 'CapType']
  return myscreen_df[cols]

# get relative strength
def get_relative_strength(stock_list):

    # Dictionary to store stock tickers and their corresponding percentage price change
    stock_changes = {}

    # Loop through each stock and fetch its price data
    for stock in stock_list:
        try:
            # Download the stock data for the given date range
            stock_data = yfin.Ticker(stock + '.NS').history(period='1mo', interval='1d')[map(str.title, ['open', 'close', 'low', 'high', 'volume'])]

            # Calculate the percentage change for the stock
            if len(stock_data) > 0:
                start_price = stock_data['Close'].iloc[0]
                end_price = stock_data['Close'].iloc[-1]
                percent_change = round(((end_price - start_price) / start_price) * 100, 2)
                stock_changes[stock] = percent_change
            else:
                stock_changes[stock] = np.nan  # If no data is available, set to NaN

        except Exception as e:
            print(f"Error fetching data for {stock}: {e}")
            stock_changes[stock] = np.nan

    # Create a DataFrame with stock tickers and their percentage changes
    df = pd.DataFrame(list(stock_changes.items()), columns=['Symbol', 'Percent_Change'])

    # Drop any stocks with missing data (NaN values)
    df = df.dropna()

    # Calculate the percentile rank based on percentage change
    df['RSP'] = round(df['Percent_Change'].rank(pct=True) * 100, 2)
    cols = ['Symbol', 'RSP']
    df = df[cols]
    # Sort by percentile rank (optional)
    df = df.sort_values(by='RSP', ascending=False).reset_index(drop=True)

    return df

In [6]:
# function to get stock technicals
def stock_prec_dev(stock_symbol):
    #stock_symbol = 'ULTRACEMCO.NS'
    short_window = 20
    mid_window = 50
    long_window = 200
    moving_avg = 'SMA'

    start = datetime.datetime(*map(int, start_date.split('-')))
    end = datetime.datetime(*map(int, end_date.split('-')))

    stock_df = yfin.Ticker(stock_symbol + '.NS').history(period='max', interval='1d')[map(str.title, ['open', 'close', 'low', 'high', 'volume'])]

    stock_df['Max'] = round(max(stock_df['Close']),2)
    stock_df = stock_df[(stock_df.index <= end_date) & (stock_df.index >= start_date)]
    stock_df['200_SMA'] = round(stock_df['Close'].rolling(window = 200, min_periods = 1).mean(),0)
    stock_df['Dev%_200'] = round((stock_df['Close'] - stock_df['200_SMA'])*100/stock_df['200_SMA'],2)
    stock_df.dropna(axis = 0, inplace = True) # remove any null rows

    stock_df['20_SMA'] = stock_df['Close'].rolling(window=20).mean()
    stock_df['50_SMA'] = stock_df['Close'].rolling(window=50).mean()
    stock_df['Symbol'] = stock_symbol

    stock_df['Close'] = round(stock_df['Close'],2)
    stock_df['Min'] = round(min(stock_df['Close']),2)
    stock_df['RSI_14'] = ta.momentum.RSIIndicator(close=stock_df['Close'], window=14).rsi()
    stock_df['RSI_14'] = round(stock_df['RSI_14'],0)
    stock_df['Prev_Close'] = stock_df['Close'].shift(1)
    stock_df.drop(['Open', 'Low', 'High', 'Volume'], axis=1, inplace=True)
    stock_df = stock_df.tail(1)

    max_SMA = max(stock_df['20_SMA'].item(), stock_df['50_SMA'].item(), stock_df['200_SMA'].item())
    min_SMA = min(stock_df['20_SMA'].item(), stock_df['50_SMA'].item(), stock_df['200_SMA'].item())
    ABS_Spread = max_SMA - min_SMA
    stock_df['Spread%'] = round((ABS_Spread / stock_df['200_SMA'].item()) * 100,2)

    return stock_df

# function to compute stock attributes
def get_common_features(stock_ids, df_mypf):

  df_prec_dev = pd.DataFrame()
  df_tmp = get_screener_features()
  df_rs = get_relative_strength(stock_ids)

  for stock_id in stock_ids:
      tmp = stock_prec_dev(stock_id)
      tmp = tmp.reset_index()
      df_prec_dev = pd.concat([df_prec_dev, tmp], ignore_index = True)
  df_prec_dev = pd.merge(df_prec_dev, df_mypf, on= 'Symbol')
  df_prec_dev = pd.merge(df_prec_dev, df_tmp, on= 'Symbol', how='left')
  df_prec_dev = pd.merge(df_prec_dev, df_rs, on= 'Symbol', how='left')
  #print(df_prec_dev.columns)
  df_prec_dev['Curr_PE'] = round(df_prec_dev['Close']/df_prec_dev['EPS'],1)
  df_prec_dev['Dev%_PE'] = round((df_prec_dev['Curr_PE'] - df_prec_dev['MedPE'])*100/df_prec_dev['MedPE'],2)
  df_prec_dev['Conviction'] = df_prec_dev['Conviction'] + '-' + df_prec_dev['CapType']
  return df_prec_dev

# function to arrange stock features
def arrange_features(df_stocks, common_cols, diff_cols):
  df_stocks_common = df_stocks[common_cols].drop_duplicates()
  df_stocks_diff = df_stocks[diff_cols]
  df_stocks_diff['Investment'] = df_stocks_diff['AvgCost'] * df_stocks_diff['Shares']
  df_stocks_diff = df_stocks_diff.groupby(['Symbol'])[['Shares', 'Investment']].aggregate(['sum']).reset_index()
  df_stocks_diff.columns = ['Symbol', 'Shares', 'Investment']
  df_stocks_diff['AvgCost'] = round(df_stocks_diff['Investment']/df_stocks_diff['Shares'],2)
  df_stocks = pd.merge(df_stocks_diff, df_stocks_common, on='Symbol')
  return df_stocks

# plot fact distribution across dimension
def plot_pie_chart(df, dimension, fact):
  # grouping the data by category and calculating the sum of fact for each type
  grouped_data = df.groupby(dimension)[fact].sum()

  # sorting the grouped data in descending order
  grouped_data = grouped_data.sort_values(ascending=False)

  # creating a pie chart
  grouped_data.plot.pie(autopct='%1.1f%%', startangle=90, figsize=(6, 6))

  # adding a title and displaying the plot
  plt.title(f'{dimension} {fact} Distribution')
  plt.ylabel('')  # To hide the y-label
  plt.show()

In [7]:
# function to get portfolio features

def get_portfolio_features(df_common_features):

  print_date_time()
  print('-------------------')

  #df_common_features["Target"] = df_common_features["Target"].fillna(df_common_features["Max"])
  df_common_features['NTT'] = np.where(df_common_features['Strategy']== 'NTT', df_common_features["Target"], df_common_features['Max'])
  df_common_features['LTT'] = np.where(df_common_features['Strategy']== 'BTT', df_common_features["Target"], df_common_features['Max'])
  df_common_features['BOL'] = df_common_features['Min']

  tmp_df = df_common_features[df_common_features['Symbol'].isin(mypf_df[mypf_df['InPortfolio'] != 'NA'].Symbol.values)]
  print('qualified stocks: '+str(len(tmp_df['Symbol'].unique())))
  tmp_df1 = tmp_df[tmp_df['LatestQtr'] == 1]
  print('with latest results: '+str(len(tmp_df1['Symbol'].unique())))
  tmp_df1 = tmp_df1[tmp_df1['StarStock'] == 1]
  print('still star stocks: '+str(len(tmp_df1['Symbol'].unique())))
  tmp_df['Investment'] = tmp_df['AvgCost'] * tmp_df['Shares']
  tmp_df['Current'] = round(tmp_df['Close'] * tmp_df['Shares'],0)
  tmp_df['Previous'] = tmp_df['Prev_Close'] * tmp_df['Shares']
  tmp_df['EstimatedST'] = tmp_df['NTT'] * tmp_df['Shares']
  tmp_df['EstimatedLT'] = tmp_df['LTT'] * tmp_df['Shares']
  tmp_df['Current P/L'] = round((tmp_df['Current'] - tmp_df['Investment']),0)
  tmp_df['Today P/L%'] = round((tmp_df['Current'] - tmp_df['Previous'])*100/tmp_df['Previous'],2)
  tmp_df['Current P/L%'] = round((tmp_df['Current'] - tmp_df['Investment'])*100/tmp_df['Investment'],2)
  tmp_df['EstimatedST P/L%'] = round((tmp_df['EstimatedST'] - tmp_df['Investment'])*100/tmp_df['Investment'],2)
  tmp_df['EstimatedLT P/L%'] = round((tmp_df['EstimatedLT'] - tmp_df['Investment'])*100/tmp_df['Investment'],2)
  tmp_df['NTT%'] = round((tmp_df['NTT'] - tmp_df['Close'])*100/tmp_df['Close'],2)
  tmp_df['LTT%'] = round((tmp_df['LTT'] - tmp_df['Close'])*100/tmp_df['Close'],2)
  tmp_df['Gained%'] = round((tmp_df['Close'] - tmp_df['BOL'])*100/tmp_df['BOL'],2)
  investment = round(sum(tmp_df['AvgCost']*tmp_df['Shares']),0)
  current = round(sum(tmp_df['Close']*tmp_df['Shares']),0)
  tmp_df['InitAlloc%'] = round(tmp_df['Investment']*100/investment,2)
  tmp_df['CurrAlloc%'] = round(tmp_df['Current']*100/current,2)
  tmp_df['FTT'] = tmp_df['LTT']
  tmp_df.loc[tmp_df['Strategy'] == 'NTT', 'FTT'] = tmp_df['NTT']
  tmp_df['FTT%'] = tmp_df['LTT%']
  tmp_df.loc[tmp_df['Strategy'] == 'NTT', 'FTT%'] = tmp_df['NTT%']
  tmp_df['FTT Amt'] = round(tmp_df['FTT%'] * tmp_df['Current']/100,0)
  tmp_df['OTT%'] = round((tmp_df['FTT'] - tmp_df['AvgCost'])*100/tmp_df['AvgCost'],2)
  tmp_df['RRR Ind'] = round(tmp_df['Current P/L']/tmp_df['FTT Amt'],2)
  tmp_df['Risk Ind'] = round(tmp_df['Current P/L%']*tmp_df['CurrAlloc%'],0)

  return tmp_df

# function to print portfolio features
def print_portfolio_stats(df_portfolio_features, myinvmt_df):
  from pyxirr import xirr

  total_booked_amt, reserve_amt, cy_booked_amt, py_booked_amt = get_amt()

  dates = myinvmt_df['Date'].values
  dates = np.append(dates, datetime.date.today().strftime('%d-%b-%y'))
  investment = myinvmt_df['Investment'].values
  dates= pd.to_datetime(dates)

  current = round(sum(df_portfolio_features['Close']*df_portfolio_features['Shares']),0) + reserve_amt
  investment_xirr = np.append(investment, current)
  cagr = round(xirr(pd.DataFrame({"dates": dates, "amounts": investment_xirr}))*100,2)

  investment = -sum(investment)
  invested = round(sum(df_portfolio_features['AvgCost']*df_portfolio_features['Shares']),0) + reserve_amt
  previous = round(sum(df_portfolio_features['Prev_Close']*df_portfolio_features['Shares']),0) + reserve_amt
  cy_invested = investment + py_booked_amt

  today_pnl_amount = current-previous
  today_pnl_percentage = round((current-previous)*100/previous,2)

  curr_pnl_amount = current-invested
  curr_pnl_percentage = round((curr_pnl_amount)*100/(cy_invested),2)

  cy_pnl_amount = cy_booked_amt + curr_pnl_amount
  cy_pnl_percentage = round((cy_pnl_amount)*100/cy_invested,2)

  overall_pnl_amount = total_booked_amt + curr_pnl_amount
  overall_pnl_percentage = round((overall_pnl_amount)*100/investment,2)

  estimate_st = round(sum(df_portfolio_features['FTT']*df_portfolio_features['Shares']),0)  + reserve_amt
  est_st_pnl_amount = estimate_st-current
  est_st_pnl_percentage = round((est_st_pnl_amount)*100/current,2)

  estimate_lt = round(sum(df_portfolio_features['LTT']*df_portfolio_features['Shares']),0)  + reserve_amt
  est_lt_pnl_amount = estimate_lt-current
  est_lt_pnl_percentage = round((est_lt_pnl_amount)*100/current,2)

  total_profit = round(sum(df_portfolio_features[df_portfolio_features['Current P/L%'] > 0]['Current']) - sum(df_portfolio_features[df_portfolio_features['Current P/L%'] > 0]['Investment']),0)
  total_loss = round(sum(df_portfolio_features[df_portfolio_features['Current P/L%'] < 0]['Current']) - sum(df_portfolio_features[df_portfolio_features['Current P/L%'] < 0]['Investment']),0)

  cy_booked_percentage = round((cy_booked_amt)*100/current,2)
  py_booked_percentage = round((py_booked_amt)*100/investment,2)
  total_booked_percentage = round((total_booked_amt)*100/investment,2)

  print('-------------------')
  print('Initial Investment: ', format_amt(investment))
  print('CY Investment: ', format_amt(cy_invested))
  print('Reserve: ', format_amt(reserve_amt))
  print('Current: ',  format_amt(current))
  print('-------------------')
  print('Today PnL: '+ '{} ({}%)'.format(format_amt(today_pnl_amount), today_pnl_percentage))
  print('Current PnL: '+ '{} ({}%)'.format(format_amt(curr_pnl_amount), curr_pnl_percentage))
  print('CY Booked + Current PnL: '+ '{} ({}%)'.format(format_amt(cy_pnl_amount), cy_pnl_percentage))
  print('-------------------')
  print('Total profit: ', format_amt(total_profit))
  print('Total loss: ', format_amt(total_loss))
  print('-------------------')
  print('Total Booked + Current PnL: '+ '{} ({}%)'.format(format_amt(overall_pnl_amount), overall_pnl_percentage))
  print('Total Booked PnL: '+ '{} ({}%)'.format(format_amt(total_booked_amt), total_booked_percentage))
  print('Curr Year Booked PnL: '+ '{} ({}%)'.format(format_amt(cy_booked_amt), cy_booked_percentage))
  print('Prev Year Booked PnL: '+ '{} ({}%)'.format(format_amt(py_booked_amt), py_booked_percentage))
  print('===================')
  print('Est FTT: ',  format_amt(estimate_st))
  print('Est FTT PnL: '+ '{} ({}%)'.format(format_amt(est_st_pnl_amount), est_st_pnl_percentage))

  print('===================')
  print('Deployed: ', format_amt(investment))

  print('Current: ', format_amt(current))

  print('CAGR/XIRR %: '+'{}%'.format(cagr))

In [8]:
# get start and end date
start_date, end_date = get_start_end_date()

# get portfolio and prospects data
mypfs_df = get_mypfs_df()
mypps_df = get_mypps_df()
myinvmt_df = get_myinvmt_df()

# merge above datasets
mypf_df = pd.merge(mypfs_df, mypps_df, on="Symbol")

# seggregate dm and sv portfolio
dm_pf = mypf_df[mypf_df['InPortfolio'] == 'DM']
sv_pf = mypf_df[mypf_df['InPortfolio'] == 'SV']

# build portfolio stock dataframe
dm_stocks = get_stock_ids(dm_pf)
sv_stocks = get_stock_ids(sv_pf)
df_stocks = pd.concat([dm_pf,sv_pf], ignore_index = True)

# arrange common and diff stock features
common_cols = ['Symbol', 'Target', 'Criteria', 'Strategy', 'CumlRnk', 'LatestQtr', 'StarStock', 'Conviction', 'Category', 'InFolio', 'XIRR', 'MBQ']
diff_cols = ['Symbol', 'AvgCost', 'Shares']
df_stocks = arrange_features(df_stocks, common_cols, diff_cols)

# get common features
stock_ids = df_stocks['Symbol'].values
df_common_features = get_common_features(stock_ids, df_stocks)

df_common_features.reset_index(drop=True, inplace=True)
df_common_features.drop(['Date'], axis=1, inplace=True)
# get and print portfolio features
df_portfolio_features = get_portfolio_features(df_common_features)

print_portfolio_stats(df_portfolio_features, myinvmt_df)

df = df_portfolio_features
#plot_pie_chart(df, 'CapType', 'Current')
list_ox40n = list(df[df['MBQ'].str.contains('OX40N', na=False)]['Symbol'].values)

Run date time (IST): 2026-03-09 09:48:25
-------------------
qualified stocks: 86
with latest results: 26
still star stocks: 15
-------------------
Initial Investment:  1.36 C
CY Investment:  1.62 C
Reserve:  66.25 K
Current:  1.34 C
-------------------
Today PnL: -3.44 L (-2.5%)
Current PnL: -42.65 L (-26.25%)
CY Booked + Current PnL: -26.97 L (-16.6%)
-------------------
Total profit:  93.56 K
Total loss:  -43.58 L
-------------------
Total Booked + Current PnL: 1.14 K (0.01%)
Total Booked PnL: 42.66 L (31.48%)
Curr Year Booked PnL: 15.68 L (11.68%)
Prev Year Booked PnL: 26.98 L (19.91%)
===================
Est FTT:  2.47 C
Est FTT PnL: 1.13 C (84.16%)
===================
Deployed:  1.36 C
Current:  1.34 C
CAGR/XIRR %: -0.46%

In [9]:
# top 5 near their targets
cols = ['Symbol', 'Today P/L%', 'Current P/L%', 'FTT%', 'OTT%', 'FTT Amt', 'Current P/L', 'Current', 'FTT', 'Dev%_PE', 'RSI_14','Conviction', 'Spread%',  'CumlRnk', 'RRR Ind', 'CurrAlloc%', 'Gained%', 'Criteria', 'Strategy', 'Category']
df_tmp = df_portfolio_features[~df_portfolio_features['Symbol'].isin(['ENRIN','BLUSPRING','DIGITIDE'])]
df_tmp = df_tmp.sort_values(by = 'FTT Amt', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
19,COALINDIA,1.10,9.50,7.46,17.67,12291.0,14300.0,164761.0,478.51,31.99,61.0,L-LC,11.40,185.0,1.16,1.23,27.95,XY25,ATH,MINING
50,MASFIN,-3.06,-10.69,36.11,21.57,31600.0,-10470.0,87510.0,397.04,-23.22,31.0,H-SC,5.64,167.0,-0.33,0.65,22.11,XR,ATH,FINANCE
77,TTKPRESTIG,-2.77,-40.74,68.90,0.09,41149.0,-41054.0,59723.0,770.00,38.53,17.0,M-SC,14.25,250.0,-1.00,0.45,0.00,OX40N,NTT,DURABLES
37,ICICIGI,-1.53,-1.92,21.68,19.34,42549.0,-3850.0,196259.0,2252.93,-17.38,41.0,X-MC,1.58,66.0,-0.09,1.47,11.93,X40,ATH,INSURANCE
78,UNITDSPR,-2.37,-0.32,21.16,20.77,49385.0,-757.0,233387.0,1644.00,-11.56,46.0,X-MC,1.54,64.0,-0.02,1.75,6.36,X40N,NTT,BREWERIES

In [10]:
# top 5 today
df_tmp = df_portfolio_features.sort_values(by = 'Today P/L%', ascending=False)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
19,COALINDIA,1.10,9.50,7.46,17.67,12291.0,14300.0,164761.0,478.51,31.99,61.0,L-LC,11.40,185.0,1.16,1.23,27.95,XY25,ATH,MINING
36,HONAUT,0.10,-22.23,94.56,51.31,141816.0,-42863.0,149975.0,58357.33,-35.33,31.0,X-SC,13.30,90.0,-0.30,1.12,0.17,X40N,ATH,ELECTRICAL
59,RELIANCE,-0.21,-10.02,39.25,25.30,70977.0,-20131.0,180832.0,1952.00,-12.34,47.0,X-LC,2.13,21.0,-0.28,1.35,20.73,XY25,BTT,REFINERIES
69,SURYODAY,-0.35,-26.63,67.70,23.03,88942.0,-47695.0,131376.0,216.00,42.54,49.0,H-SC,7.18,166.0,-0.54,0.98,30.35,XR,NTT,BANKS
31,HAPPSTMNDS,-0.36,-58.02,340.29,84.85,183103.0,-74357.0,53808.0,1480.71,-50.16,23.0,H-SC,29.05,152.0,-0.41,0.40,0.00,AR,ATH,IT

In [11]:
# bottom 5 today
df_tmp = df_portfolio_features.sort_values(by = 'Today P/L%', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
55,RAJESHEXPO,-5.00,-78.18,358.61,0.07,107339.0,-107245.0,29932.0,518.00,997.22,18.0,L-SC,15.34,268.0,-1.00,0.22,0.00,OX40N,NTT,JEWELLERY
75,TMPV,-4.99,-24.14,80.05,36.58,216081.0,-85909.0,269932.0,600.00,-84.72,31.0,X-LC,2.69,4.0,-0.40,2.02,0.00,XY24,NTT,AUTO
6,ASIANPAINT,-4.96,-22.03,59.72,24.52,131971.0,-62456.0,220983.0,3460.25,-21.42,20.0,X-LC,7.36,30.0,-0.47,1.65,0.00,X40,ATH,PAINTS
7,ATULAUTO,-4.91,-26.98,99.36,45.57,143018.0,-53193.0,143939.0,844.00,3105.41,38.0,M-SC,7.29,248.0,-0.37,1.08,8.93,XY24,NTT,AUTO
46,JIOFIN,-4.62,-24.24,69.51,28.43,157104.0,-72310.0,226017.0,387.00,-25.44,20.0,X-LC,13.93,34.0,-0.46,1.69,7.09,XY24,BTT,FINANCE

In [12]:
# top 5 to exit based on CumlRnk
df_tmp = df_portfolio_features[~df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])]
df_tmp = df_tmp[(df_tmp['Current P/L%'] > -1) & (df_tmp['Current P/L%'] < 1)].sort_values(by = 'CumlRnk', ascending=False)
df_tmp[cols].head()

Empty DataFrame
Columns: [Symbol, Today P/L%, Current P/L%, FTT%, OTT%, FTT Amt, Current P/L, Current, FTT, Dev%_PE, RSI_14, Conviction, Spread%, CumlRnk, RRR Ind, CurrAlloc%, Gained%, Criteria, Strategy, Category]
Index: []

In [13]:
# OX40N stocks to exit
df_tmp = df_portfolio_features[(df_portfolio_features['Symbol'].isin(list_ox40n))].sort_values(by = 'Current P/L%', ascending=False)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
27,FINCABLES,-0.75,21.79,70.71,107.91,127150.0,32175.0,179819.0,1641.55,9.59,70.0,M-SC,7.22,220.0,0.25,1.35,35.28,OX40N,ATH,CABLES
66,SIS,-3.94,-34.28,84.52,21.26,61673.0,-38064.0,72968.0,528.00,1708.29,32.0,H-SC,8.36,168.0,-0.62,0.55,0.59,OX40N,NTT,MISC
72,TATAELXSI,-1.79,-38.71,115.42,32.03,93261.0,-51034.0,80801.0,9161.00,-23.39,25.0,H-SC,15.18,158.0,-0.55,0.60,0.00,OX40N,NTT,IT
48,KANSAINER,-4.19,-39.51,87.58,13.47,142873.0,-106533.0,163134.0,340.00,-48.09,21.0,H-SC,15.68,162.0,-0.75,1.22,0.00,XY24,NTT,PAINTS
18,CERA,-2.83,-39.74,105.60,23.89,111932.0,-69907.0,105996.0,9475.00,-41.77,25.0,H-SC,15.62,153.0,-0.62,0.79,0.00,OX40N,NTT,CERAMICS

In [14]:
# top 5 to book for rotation
df_tmp = df_portfolio_features[(df_portfolio_features['Current P/L%'] > 20) ].sort_values(by = 'CumlRnk', ascending=False)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
27,FINCABLES,-0.75,21.79,70.71,107.91,127150.0,32175.0,179819.0,1641.55,9.59,70.0,M-SC,7.22,220.0,0.25,1.35,35.28,OX40N,ATH,CABLES

In [15]:
# top 5 to monitor for exit
df_tmp = df_portfolio_features[~df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])]
df_tmp = df_tmp[(df_tmp['Current P/L%'] > 0) ].sort_values(by = 'Dev%_PE', ascending=False)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
19,COALINDIA,1.10,9.50,7.46,17.67,12291.0,14300.0,164761.0,478.51,31.99,61.0,L-LC,11.40,185.0,1.16,1.23,27.95,XY25,ATH,MINING
27,FINCABLES,-0.75,21.79,70.71,107.91,127150.0,32175.0,179819.0,1641.55,9.59,70.0,M-SC,7.22,220.0,0.25,1.35,35.28,OX40N,ATH,CABLES
1,ABB,-2.28,8.69,33.93,45.57,96481.0,22733.0,284352.0,7934.00,-30.12,55.0,H-MC,9.33,125.0,0.24,2.13,26.27,AR,NTT,ELECTRICAL

In [16]:
# top 5 to book for rotation from weak conviction
df_tmp = df_portfolio_features[~df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])]
df_tmp = df_tmp[~df_tmp['Criteria'].isin(['XY25','XY24','X40', 'X40N'])].sort_values(by = 'RRR Ind', ascending=False)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
27,FINCABLES,-0.75,21.79,70.71,107.91,127150.0,32175.0,179819.0,1641.55,9.59,70.0,M-SC,7.22,220.0,0.25,1.35,35.28,OX40N,ATH,CABLES
1,ABB,-2.28,8.69,33.93,45.57,96481.0,22733.0,284352.0,7934.00,-30.12,55.0,H-MC,9.33,125.0,0.24,2.13,26.27,AR,NTT,ELECTRICAL
40,INDIAMART,-1.46,-10.21,130.22,106.72,144217.0,-12587.0,110749.0,4810.62,-59.57,38.0,H-SC,9.04,140.0,-0.09,0.83,10.79,AR,ATH,MISC
85,ZYDUSLIFE,-2.12,-5.76,43.92,35.63,86746.0,-12066.0,197508.0,1286.17,-18.02,46.0,H-MC,5.14,120.0,-0.14,1.48,9.95,AR,ATH,PHARMA
84,WIPRO,-0.37,-20.15,115.74,72.27,156600.0,-34145.0,135303.0,420.00,-27.84,19.0,M-LC,13.35,98.0,-0.22,1.01,0.00,XR,NTT,IT

In [17]:
# top 5 to accumulate based on lowest RSI_14
df_tmp = df_portfolio_features[df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])].sort_values(by = 'RSI_14', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
8,AWL,-1.77,-40.04,178.56,67.02,381463.0,-142676.0,213633.0,485.00,-67.69,11.0,X-SC,21.80,81.0,-0.37,1.60,0.00,XY24,NTT,FMCG
53,PGHH,-2.44,-20.43,65.90,32.01,111967.0,-43616.0,169904.0,17616.87,-46.19,13.0,X-MC,10.59,57.0,-0.39,1.27,0.00,X40,ATH,FMCG
3,ACC,-3.64,-35.26,170.03,74.81,295138.0,-94548.0,173580.0,3906.00,-53.87,16.0,X-SC,11.18,85.0,-0.32,1.30,0.00,XY24,BTT,CEMENT
9,BAJAJHFL,-2.67,-26.85,121.64,62.13,242952.0,-73316.0,199730.0,181.50,-39.75,20.0,X-MC,18.07,60.0,-0.30,1.49,0.00,X40N,ATH,FINANCE
46,JIOFIN,-4.62,-24.24,69.51,28.43,157104.0,-72310.0,226017.0,387.00,-25.44,20.0,X-LC,13.93,34.0,-0.46,1.69,7.09,XY24,BTT,FINANCE

In [18]:
# top 5 to accumulate based on Spread and CumlRnk
df_tmp = df_portfolio_features[df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])]
df_tmp = df_tmp[(df_tmp['CumlRnk'] < 100)].sort_values(by = 'Spread%', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
22,DABUR,-2.72,-8.97,57.86,43.70,130657.0,-22252.0,225816.0,735.00,-17.44,27.0,X-MC,0.96,70.0,-0.17,1.69,4.73,XY24,BTT,FMCG
78,UNITDSPR,-2.37,-0.32,21.16,20.77,49385.0,-757.0,233387.0,1644.00,-11.56,46.0,X-MC,1.54,64.0,-0.02,1.75,6.36,X40N,NTT,BREWERIES
37,ICICIGI,-1.53,-1.92,21.68,19.34,42549.0,-3850.0,196259.0,2252.93,-17.38,41.0,X-MC,1.58,66.0,-0.09,1.47,11.93,X40,ATH,INSURANCE
59,RELIANCE,-0.21,-10.02,39.25,25.30,70977.0,-20131.0,180832.0,1952.00,-12.34,47.0,X-LC,2.13,21.0,-0.28,1.35,20.73,XY25,BTT,REFINERIES
75,TMPV,-4.99,-24.14,80.05,36.58,216081.0,-85909.0,269932.0,600.00,-84.72,31.0,X-LC,2.69,4.0,-0.40,2.02,0.00,XY24,NTT,AUTO

In [19]:
# top 5 to accumulate based on lowest Gained%
df_tmp = df_portfolio_features[df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])].sort_values(by = 'Gained%', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
3,ACC,-3.64,-35.26,170.03,74.81,295138.0,-94548.0,173580.0,3906.00,-53.87,16.0,X-SC,11.18,85.0,-0.32,1.30,0.0,XY24,BTT,CEMENT
6,ASIANPAINT,-4.96,-22.03,59.72,24.52,131971.0,-62456.0,220983.0,3460.25,-21.42,20.0,X-LC,7.36,30.0,-0.47,1.65,0.0,X40,ATH,PAINTS
9,BAJAJHFL,-2.67,-26.85,121.64,62.13,242952.0,-73316.0,199730.0,181.50,-39.75,20.0,X-MC,18.07,60.0,-0.30,1.49,0.0,X40N,ATH,FINANCE
8,AWL,-1.77,-40.04,178.56,67.02,381463.0,-142676.0,213633.0,485.00,-67.69,11.0,X-SC,21.80,81.0,-0.37,1.60,0.0,XY24,NTT,FMCG
10,BAJAJHLDNG,-2.37,-7.81,40.17,29.22,70406.0,-14855.0,175270.0,14451.52,-14.55,32.0,X-LC,11.90,28.0,-0.21,1.31,0.0,X40,ATH,FINANCE

In [20]:
# top 5 to accumulate based on lowest CurrAlloc%
df_tmp = df_portfolio_features[df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])].sort_values(by = 'CurrAlloc%', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
58,RELAXO,-2.38,-59.31,274.34,52.31,162025.0,-86100.0,59060.0,1176.00,-56.64,22.0,X-SC,17.54,92.0,-0.53,0.44,0.00,X40N,NTT,FOOTWEAR
12,BATAINDIA,-3.46,-53.68,191.92,35.20,114373.0,-69076.0,59594.0,2096.00,-21.88,21.0,X-SC,24.18,91.0,-0.60,0.45,0.00,X40,NTT,FOOTWEAR
54,QUESS,-2.13,-23.82,128.29,73.90,104364.0,-25443.0,81350.0,424.00,-59.23,32.0,X-SC,17.65,80.0,-0.24,0.61,0.00,XY24,NTT,MISC
36,HONAUT,0.10,-22.23,94.56,51.31,141816.0,-42863.0,149975.0,58357.33,-35.33,31.0,X-SC,13.30,90.0,-0.30,1.12,0.17,X40N,ATH,ELECTRICAL
65,SIEMENS,-3.51,-15.25,48.10,25.51,75861.0,-28380.0,157715.0,4671.50,32.53,47.0,H-LC,3.33,51.0,-0.37,1.18,16.14,AR,ATH,ELECTRICAL

In [21]:
# top 5 to accumulate based on CumlRnk
df_tmp = df_portfolio_features.sort_values(by = 'CumlRnk', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
45,ITC,-1.65,-19.77,48.39,19.06,132067.0,-67244.0,272922.0,452.00,-55.92,32.0,X-LC,16.98,1.0,-0.51,2.04,0.00,X40,NTT,FMCG
73,TCS,-1.63,-26.14,71.37,26.57,244201.0,-121111.0,342162.0,4311.59,-37.40,24.0,X-LC,12.54,2.0,-0.50,2.56,0.00,X40,ATH,IT
43,INFY,-1.37,-12.15,52.81,34.24,145162.0,-38012.0,274876.0,1972.00,-30.70,27.0,X-LC,10.93,3.0,-0.26,2.06,1.18,X40,NTT,IT
75,TMPV,-4.99,-24.14,80.05,36.58,216081.0,-85909.0,269932.0,600.00,-84.72,31.0,X-LC,2.69,4.0,-0.40,2.02,0.00,XY24,NTT,AUTO
34,HCLTECH,-0.97,-12.81,42.02,23.83,88639.0,-30979.0,210945.0,1908.19,-8.60,26.0,X-LC,8.73,8.0,-0.35,1.58,1.21,X40,ATH,IT

In [22]:
# top 5 for average up
df_tmp = df_portfolio_features[(df_portfolio_features['Dev%_200'] > 5)].sort_values(by = 'CurrAlloc%', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
42,INDUSINDBK,-2.07,-32.24,96.11,32.89,50282.0,-24890.0,52317.0,1800.00,-346.50,47.0,L-MC,12.03,258.0,-0.50,0.39,44.08,XR,NTT,BANKS
19,COALINDIA,1.10,9.50,7.46,17.67,12291.0,14300.0,164761.0,478.51,31.99,61.0,L-LC,11.40,185.0,1.16,1.23,27.95,XY25,ATH,MINING
27,FINCABLES,-0.75,21.79,70.71,107.91,127150.0,32175.0,179819.0,1641.55,9.59,70.0,M-SC,7.22,220.0,0.25,1.35,35.28,OX40N,ATH,CABLES
11,BANDHANBNK,-1.08,-11.95,118.54,92.42,290731.0,-33299.0,245260.0,400.00,110.49,66.0,H-SC,9.71,174.0,-0.11,1.84,35.11,XY24,NTT,BANKS
1,ABB,-2.28,8.69,33.93,45.57,96481.0,22733.0,284352.0,7934.00,-30.12,55.0,H-MC,9.33,125.0,0.24,2.13,26.27,AR,NTT,ELECTRICAL

In [23]:
# top 5 RSP
df_tmp = df_portfolio_features.sort_values(by = 'RSP', ascending=False)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
27,FINCABLES,-0.75,21.79,70.71,107.91,127150.0,32175.0,179819.0,1641.55,9.59,70.0,M-SC,7.22,220.0,0.25,1.35,35.28,OX40N,ATH,CABLES
11,BANDHANBNK,-1.08,-11.95,118.54,92.42,290731.0,-33299.0,245260.0,400.00,110.49,66.0,H-SC,9.71,174.0,-0.11,1.84,35.11,XY24,NTT,BANKS
26,EASEMYTRIP,-3.20,-59.99,264.14,45.70,186868.0,-106069.0,70746.0,26.40,-26.57,42.0,M-SC,18.15,204.0,-0.57,0.53,16.56,XY24,NTT,TRAVEL
19,COALINDIA,1.10,9.50,7.46,17.67,12291.0,14300.0,164761.0,478.51,31.99,61.0,L-LC,11.40,185.0,1.16,1.23,27.95,XY25,ATH,MINING
1,ABB,-2.28,8.69,33.93,45.57,96481.0,22733.0,284352.0,7934.00,-30.12,55.0,H-MC,9.33,125.0,0.24,2.13,26.27,AR,NTT,ELECTRICAL

In [24]:
# Top N allocation
df_tmp = df_portfolio_features.sort_values(by = 'CurrAlloc%', ascending=False)
top_n_values = [10, 25, 50]

sum_df = pd.DataFrame({
    'Top_N': top_n_values,
    'Sum_Alloc%': [df_tmp['CurrAlloc%'].head(n).sum() for n in top_n_values]
})

sum_df

   Top_N  Sum_Alloc%
0     10       20.61
1     25       45.41
2     50       77.94

In [25]:
# market-cap-wise allocation
df_tmp = df_portfolio_features[cols]
df_tmp.groupby(df_tmp['Conviction'].str[-2:])['CurrAlloc%'].sum().sort_values(ascending=False)

Conviction
SC    44.46
MC    30.38
LC    25.13
Name: CurrAlloc%, dtype: float64

In [26]:
# criteria-wise allocation
df_portfolio_features.groupby('Criteria')['CurrAlloc%'].sum().sort_values(ascending=False)

Criteria
XY24     27.29
X40      23.99
X40N     15.02
AR        8.99
XY25      8.77
XR        8.19
OX40N     6.94
SR        0.78
Name: CurrAlloc%, dtype: float64

In [27]:
# conviction-wise allocation
df_portfolio_features.groupby('Conviction')['CurrAlloc%'].sum().sort_values(ascending=False)

Conviction
X-MC    23.09
X-LC    21.71
H-SC    21.54
X-SC    12.06
M-SC    10.27
H-MC     4.92
M-MC     1.98
L-LC     1.23
H-LC     1.18
M-LC     1.01
L-SC     0.59
L-MC     0.39
Name: CurrAlloc%, dtype: float64

In [28]:
# sector-wise stats
df_tmp = df_portfolio_features.groupby('Category')[['CurrAlloc%', 'Current', 'Current P/L', 'FTT Amt']].sum().sort_values(by=['Current', 'Current P/L'], ascending=False)
df_tmp['Current P/L%'] = round(df_tmp['Current P/L'] * 100 / df_tmp['Current'], 2)
df_tmp['FTT%'] = round(df_tmp['FTT Amt'] * 100 / df_tmp['Current'], 2)
cols = ['CurrAlloc%', 'Current P/L%', 'FTT%']
df_tmp[cols].sort_values(by=['CurrAlloc%'], ascending=False)

               CurrAlloc%  Current P/L%    FTT%
Category
FMCG                15.43        -21.07   64.05
FINANCE             12.67        -26.79   78.46
IT                  11.64        -44.68  118.31
MISC                 6.91        -45.53  108.75
ELECTRICAL           6.50        -11.58   54.31
PAINTS               5.16        -42.89   67.71
INSURANCE            4.73         -7.29   44.00
PHARMA               4.16         -5.68   38.95
AUTO                 3.75        -30.54   82.34
BANKS                3.21        -24.68  100.23
AC                   2.17        -10.16   40.04
HEALTHCARE           1.97        -35.42   70.76
FOOTWEAR             1.90        -74.12  143.93
TRAVEL               1.84        -81.91  172.99
DURABLES             1.78        -63.51  103.28
BREWERIES            1.75         -0.32   21.16
APPARELS             1.63        -23.16   65.17
REALTY               1.46        -13.96   32.69
CERAMICS             1.35        -69.28  120.70
REFINERIES           1.35        -11.13   39.25
CABLES               1.35         17.89   70.71
CEMENT               1.30        -54.47  170.03
MINING               1.23          8.68    7.46
JEWELLERY            1.11       -115.64  190.57
ENGINEERING          1.11        -63.42  138.17
CHEMICALS            0.95       -107.65  277.05
ENTERTAINMENT        0.77        -89.19  202.02
TEXTILES             0.42        -62.81  109.24
HOTELS               0.37       -127.99  208.40

In [29]:
# money to be made criteria-wise
df_portfolio_features.groupby('Criteria')['FTT Amt'].agg(['sum', 'count']).sort_values(by='sum', ascending=False)

                sum  count
Criteria
XY24      3951637.0     21
X40       1665866.0     15
XR        1395379.0     12
AR        1370719.0     10
X40N      1293201.0     10
OX40N      864503.0     10
XY25       444938.0      6
SR         314514.0      2

In [30]:
# money to be made conviction-wise
df_portfolio_features.groupby('Conviction')['FTT Amt'].agg(['sum', 'count']).sort_values(by='sum', ascending=False)

                  sum  count
Conviction
H-SC        3913607.0     24
X-MC        1648863.0     15
X-LC        1572177.0     12
X-SC        1570875.0     10
M-SC        1546733.0     14
H-MC         421760.0      3
L-SC         211133.0      2
M-LC         156600.0      1
M-MC         120575.0      2
H-LC          75861.0      1
L-MC          50282.0      1
L-LC          12291.0      1

In [31]:
# money to be made criteria and conviction-wise
df_portfolio_features.groupby(['Conviction', 'Criteria'])['FTT Amt'].agg(['sum', 'count']).sort_values(by='sum', ascending=False)

                           sum  count
Conviction Criteria
H-SC       XY24      1334563.0      6
           AR         980262.0      5
M-SC       XY24       911248.0      6
H-SC       XR         893831.0      7
X-SC       XY24       841794.0      4
X-LC       X40        812446.0      6
X-MC       X40        646819.0      7
           X40N       529842.0      4
X-SC       X40N       522480.0      4
H-SC       OX40N      390437.0      4
X-LC       XY24       373185.0      2
M-SC       OX40N      366727.0      5
H-SC       SR         314514.0      2
X-MC       XY24       252314.0      2
X-LC       X40N       240879.0      2
H-MC       XY24       238533.0      1
X-MC       XY25       219888.0      2
X-SC       X40        206601.0      2
M-SC       XR         190872.0      2
H-MC       AR         183227.0      2
M-LC       XR         156600.0      1
X-LC       XY25       145667.0      2
L-SC       OX40N      107339.0      1
           XR         103794.0      1
M-SC       AR          77886.0      1
H-LC       AR          75861.0      1
M-MC       XY25        67092.0      1
           AR          53483.0      1
L-MC       XR          50282.0      1
L-LC       XY25        12291.0      1

In [32]:
# notebook execution time

end_time = time.time()
execution_time = round(end_time - start_time, 0)
print(f"Notebook execution time: {execution_time} seconds")

Notebook execution time: 29.0 seconds