<a href="https://colab.research.google.com/github/ankit-rathi/Quantvesting_v2/blob/main/myStocks_Portfolio_Analysis.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
'''
!pip install pandas==2.2.2 -qq
!pip install pyxirr -qq
!pip install ta -qq
!pip install yfinance==0.2.59 -qq
'''

'\n!pip install pandas==2.2.2 -qq\n!pip install pyxirr -qq\n!pip install ta -qq\n!pip install yfinance==0.2.59 -qq\n'

In [2]:
# import libraries

import numpy as np
import pandas as pd
import datetime
import warnings
warnings.filterwarnings('ignore')
import yfinance as yfin
import ta
import matplotlib.pyplot as plt
import requests

In [3]:
# notebook start time
import time
import datetime
import pytz

start_time = time.time()

# function to print date timestamp
def print_date_time():
  tz_NY = pytz.timezone('Asia/Kolkata')
  datetime_NY = datetime.datetime.now(tz_NY)
  print("Run date time (IST):", datetime_NY.strftime("%Y-%m-%d %H:%M:%S"))

In [4]:
# function to get booked and reserved amount
def get_amt():
  # fetch the JSON data from the URL
  url = "https://raw.githubusercontent.com/ankit-rathi/Tradevesting_v1/main/data/myPortfolioAmts.json"
  response = requests.get(url)
  pf_amts = response.json()  # parse the JSON data

  # extract values from the JSON
  py_booked_amt_dm = pf_amts["py_booked_amt_dm"]
  py_booked_amt_sv = pf_amts["py_booked_amt_sv"]
  cy_booked_amt_dm = pf_amts["cy_booked_amt_dm"]
  cy_booked_amt_sv = pf_amts["cy_booked_amt_sv"]
  reserve_amt_dm = pf_amts["reserve_amt_dm"]
  reserve_amt_sv = pf_amts["reserve_amt_sv"]

  # perform calculations
  py_booked_amt = py_booked_amt_dm + py_booked_amt_sv
  cy_booked_amt = cy_booked_amt_dm + cy_booked_amt_sv
  reserve_amt = reserve_amt_dm + reserve_amt_sv
  total_booked_amt = py_booked_amt + cy_booked_amt

  return total_booked_amt, reserve_amt, cy_booked_amt, py_booked_amt

gen_output = 0

In [5]:
# function to format the amount
def format_amt(number):
    abs_number = abs(number)

    if abs_number >= 1_00_00_000:  # Crores
        formatted_amt = f"{number / 1_00_00_000:.2f} C"
    elif abs_number >= 1_00_000:  # Lakhs
        formatted_amt = f"{number / 1_00_000:.2f} L"
    elif abs_number >= 1_000:  # Thousands
        formatted_amt = f"{number / 1_000:.2f} K"
    else:
        formatted_amt = f"{number:.2f}"

    return formatted_amt

# function to set start and end date
def get_start_end_date():
  start_date = (datetime.date.today() + datetime.timedelta(days=-365)).strftime('%Y-%m-%d')
  end_date = (datetime.date.today() + datetime.timedelta(days=1)).strftime('%Y-%m-%d')
  return start_date, end_date

# function to fetch my portfolio csv
def get_mypfs_df():
  mypfs_df = pd.read_csv('https://raw.githubusercontent.com/ankit-rathi/Tradevesting_v1/main/data/myPortfolioStocks.csv')
  return mypfs_df

# function to fetch my prospects csv
def get_mypps_df():
  mypps_df = pd.read_csv('https://raw.githubusercontent.com/ankit-rathi/Tradevesting_v1/main/data/myProspectsScrips.csv')
  return mypps_df

# function to fetch screener data
def get_myscreen_df():
  myscreen_df = pd.read_csv('https://raw.githubusercontent.com/ankit-rathi/Tradevesting_v1/main/data/myScreenerDB.csv')
  return myscreen_df

# function to fetch momentum data
def get_myinvmt_df():
  myinvmt_df = pd.read_csv('https://raw.githubusercontent.com/ankit-rathi/Tradevesting_v1/main/data/myInvestments.csv')
  return myinvmt_df

# function to get the stock ids
def get_stock_ids(df_pf):
  stock_n100 = df_pf['Symbol'].unique()

  exclude = ['CADILAHC','MMTC', 'MASFIN']

  stock_ids = df_pf[~df_pf['Symbol'].isin(exclude) ]['Symbol'].unique()

  #mypf = mypf[mypf.Forecast.notnull()]
  #stock_ids = mypf['Symbol'].unique()

  #stock_ids.sort()
  return stock_ids

# get features from screener data
def get_screener_features():
  myscreen_df = get_myscreen_df()
  cols = ['Symbol', 'EPS', 'MedPE', 'ROCE%', 'ROE%', 'CapType']
  return myscreen_df[cols]

# get relative strength
def get_relative_strength(stock_list):

    # Dictionary to store stock tickers and their corresponding percentage price change
    stock_changes = {}

    # Loop through each stock and fetch its price data
    for stock in stock_list:
        try:
            # Download the stock data for the given date range
            stock_data = yfin.Ticker(stock + '.NS').history(period='1mo', interval='1d')[map(str.title, ['open', 'close', 'low', 'high', 'volume'])]

            # Calculate the percentage change for the stock
            if len(stock_data) > 0:
                start_price = stock_data['Close'].iloc[0]
                end_price = stock_data['Close'].iloc[-1]
                percent_change = round(((end_price - start_price) / start_price) * 100, 2)
                stock_changes[stock] = percent_change
            else:
                stock_changes[stock] = np.nan  # If no data is available, set to NaN

        except Exception as e:
            print(f"Error fetching data for {stock}: {e}")
            stock_changes[stock] = np.nan

    # Create a DataFrame with stock tickers and their percentage changes
    df = pd.DataFrame(list(stock_changes.items()), columns=['Symbol', 'Percent_Change'])

    # Drop any stocks with missing data (NaN values)
    df = df.dropna()

    # Calculate the percentile rank based on percentage change
    df['RSP'] = round(df['Percent_Change'].rank(pct=True) * 100, 2)
    cols = ['Symbol', 'RSP']
    df = df[cols]
    # Sort by percentile rank (optional)
    df = df.sort_values(by='RSP', ascending=False).reset_index(drop=True)

    return df

In [6]:
# function to get stock technicals
def stock_prec_dev(stock_symbol):
    #stock_symbol = 'ULTRACEMCO.NS'
    short_window = 20
    mid_window = 50
    long_window = 200
    moving_avg = 'SMA'

    start = datetime.datetime(*map(int, start_date.split('-')))
    end = datetime.datetime(*map(int, end_date.split('-')))

    stock_df = yfin.Ticker(stock_symbol + '.NS').history(period='max', interval='1d')[map(str.title, ['open', 'close', 'low', 'high', 'volume'])]

    stock_df['Max'] = round(max(stock_df['Close']),2)
    stock_df = stock_df[(stock_df.index <= end_date) & (stock_df.index >= start_date)]
    stock_df['200_SMA'] = round(stock_df['Close'].rolling(window = 200, min_periods = 1).mean(),0)
    stock_df['Dev%_200'] = round((stock_df['Close'] - stock_df['200_SMA'])*100/stock_df['200_SMA'],2)
    stock_df.dropna(axis = 0, inplace = True) # remove any null rows

    stock_df['20_SMA'] = stock_df['Close'].rolling(window=20).mean()
    stock_df['50_SMA'] = stock_df['Close'].rolling(window=50).mean()
    stock_df['Symbol'] = stock_symbol

    stock_df['Close'] = round(stock_df['Close'],2)
    stock_df['Min'] = round(min(stock_df['Close']),2)
    stock_df['RSI_14'] = ta.momentum.RSIIndicator(close=stock_df['Close'], window=14).rsi()
    stock_df['RSI_14'] = round(stock_df['RSI_14'],0)
    stock_df['Prev_Close'] = stock_df['Close'].shift(1)
    stock_df.drop(['Open', 'Low', 'High', 'Volume'], axis=1, inplace=True)
    stock_df = stock_df.tail(1)

    max_SMA = max(stock_df['20_SMA'].item(), stock_df['50_SMA'].item(), stock_df['200_SMA'].item())
    min_SMA = min(stock_df['20_SMA'].item(), stock_df['50_SMA'].item(), stock_df['200_SMA'].item())
    ABS_Spread = max_SMA - min_SMA
    stock_df['Spread%'] = round((ABS_Spread / stock_df['200_SMA'].item()) * 100,2)

    return stock_df

# function to compute stock attributes
def get_common_features(stock_ids, df_mypf):

  df_prec_dev = pd.DataFrame()
  df_tmp = get_screener_features()
  df_rs = get_relative_strength(stock_ids)

  for stock_id in stock_ids:
      tmp = stock_prec_dev(stock_id)
      tmp = tmp.reset_index()
      df_prec_dev = pd.concat([df_prec_dev, tmp], ignore_index = True)
  df_prec_dev = pd.merge(df_prec_dev, df_mypf, on= 'Symbol')
  df_prec_dev = pd.merge(df_prec_dev, df_tmp, on= 'Symbol', how='left')
  df_prec_dev = pd.merge(df_prec_dev, df_rs, on= 'Symbol', how='left')
  #print(df_prec_dev.columns)
  df_prec_dev['Curr_PE'] = round(df_prec_dev['Close']/df_prec_dev['EPS'],1)
  df_prec_dev['Dev%_PE'] = round((df_prec_dev['Curr_PE'] - df_prec_dev['MedPE'])*100/df_prec_dev['MedPE'],2)
  df_prec_dev['Conviction'] = df_prec_dev['Conviction'] + '-' + df_prec_dev['CapType']
  return df_prec_dev

# function to arrange stock features
def arrange_features(df_stocks, common_cols, diff_cols):
  df_stocks_common = df_stocks[common_cols].drop_duplicates()
  df_stocks_diff = df_stocks[diff_cols]
  df_stocks_diff['Investment'] = df_stocks_diff['AvgCost'] * df_stocks_diff['Shares']
  df_stocks_diff = df_stocks_diff.groupby(['Symbol'])[['Shares', 'Investment']].aggregate(['sum']).reset_index()
  df_stocks_diff.columns = ['Symbol', 'Shares', 'Investment']
  df_stocks_diff['AvgCost'] = round(df_stocks_diff['Investment']/df_stocks_diff['Shares'],2)
  df_stocks = pd.merge(df_stocks_diff, df_stocks_common, on='Symbol')
  return df_stocks

# plot fact distribution across dimension
def plot_pie_chart(df, dimension, fact):
  # grouping the data by category and calculating the sum of fact for each type
  grouped_data = df.groupby(dimension)[fact].sum()

  # sorting the grouped data in descending order
  grouped_data = grouped_data.sort_values(ascending=False)

  # creating a pie chart
  grouped_data.plot.pie(autopct='%1.1f%%', startangle=90, figsize=(6, 6))

  # adding a title and displaying the plot
  plt.title(f'{dimension} {fact} Distribution')
  plt.ylabel('')  # To hide the y-label
  plt.show()

In [7]:
# function to get portfolio features

def get_portfolio_features(df_common_features):

  print_date_time()
  print('-------------------')

  #df_common_features["Target"] = df_common_features["Target"].fillna(df_common_features["Max"])
  df_common_features['NTT'] = np.where(df_common_features['Strategy']== 'NTT', df_common_features["Target"], df_common_features['Max'])
  df_common_features['LTT'] = np.where(df_common_features['Strategy']== 'BTT', df_common_features["Target"], df_common_features['Max'])
  df_common_features['BOL'] = df_common_features['Min']

  tmp_df = df_common_features[df_common_features['Symbol'].isin(mypf_df[mypf_df['InPortfolio'] != 'NA'].Symbol.values)]
  print('qualified stocks: '+str(len(tmp_df['Symbol'].unique())))
  tmp_df1 = tmp_df[tmp_df['LatestQtr'] == 1]
  print('with latest results: '+str(len(tmp_df1['Symbol'].unique())))
  tmp_df1 = tmp_df1[tmp_df1['StarStock'] == 1]
  print('still star stocks: '+str(len(tmp_df1['Symbol'].unique())))
  tmp_df['Investment'] = tmp_df['AvgCost'] * tmp_df['Shares']
  tmp_df['Current'] = round(tmp_df['Close'] * tmp_df['Shares'],0)
  tmp_df['Previous'] = tmp_df['Prev_Close'] * tmp_df['Shares']
  tmp_df['EstimatedST'] = tmp_df['NTT'] * tmp_df['Shares']
  tmp_df['EstimatedLT'] = tmp_df['LTT'] * tmp_df['Shares']
  tmp_df['Current P/L'] = round((tmp_df['Current'] - tmp_df['Investment']),0)
  tmp_df['Today P/L%'] = round((tmp_df['Current'] - tmp_df['Previous'])*100/tmp_df['Previous'],2)
  tmp_df['Current P/L%'] = round((tmp_df['Current'] - tmp_df['Investment'])*100/tmp_df['Investment'],2)
  tmp_df['EstimatedST P/L%'] = round((tmp_df['EstimatedST'] - tmp_df['Investment'])*100/tmp_df['Investment'],2)
  tmp_df['EstimatedLT P/L%'] = round((tmp_df['EstimatedLT'] - tmp_df['Investment'])*100/tmp_df['Investment'],2)
  tmp_df['NTT%'] = round((tmp_df['NTT'] - tmp_df['Close'])*100/tmp_df['Close'],2)
  tmp_df['LTT%'] = round((tmp_df['LTT'] - tmp_df['Close'])*100/tmp_df['Close'],2)
  tmp_df['Gained%'] = round((tmp_df['Close'] - tmp_df['BOL'])*100/tmp_df['BOL'],2)
  investment = round(sum(tmp_df['AvgCost']*tmp_df['Shares']),0)
  current = round(sum(tmp_df['Close']*tmp_df['Shares']),0)
  tmp_df['InitAlloc%'] = round(tmp_df['Investment']*100/investment,2)
  tmp_df['CurrAlloc%'] = round(tmp_df['Current']*100/current,2)
  tmp_df['FTT'] = tmp_df['LTT']
  tmp_df.loc[tmp_df['Strategy'] == 'NTT', 'FTT'] = tmp_df['NTT']
  tmp_df['FTT%'] = tmp_df['LTT%']
  tmp_df.loc[tmp_df['Strategy'] == 'NTT', 'FTT%'] = tmp_df['NTT%']
  tmp_df['FTT Amt'] = round(tmp_df['FTT%'] * tmp_df['Current']/100,0)
  tmp_df['OTT%'] = round((tmp_df['FTT'] - tmp_df['AvgCost'])*100/tmp_df['AvgCost'],2)
  tmp_df['RRR Ind'] = round(tmp_df['Current P/L']/tmp_df['FTT Amt'],2)
  tmp_df['Risk Ind'] = round(tmp_df['Current P/L%']*tmp_df['CurrAlloc%'],0)

  return tmp_df

# function to print portfolio features
def print_portfolio_stats(df_portfolio_features, myinvmt_df):
  from pyxirr import xirr

  total_booked_amt, reserve_amt, cy_booked_amt, py_booked_amt = get_amt()

  dates = myinvmt_df['Date'].values
  dates = np.append(dates, datetime.date.today().strftime('%d-%b-%y'))
  investment = myinvmt_df['Investment'].values
  dates= pd.to_datetime(dates)

  current = round(sum(df_portfolio_features['Close']*df_portfolio_features['Shares']),0) + reserve_amt
  investment_xirr = np.append(investment, current)
  cagr = round(xirr(pd.DataFrame({"dates": dates, "amounts": investment_xirr}))*100,2)

  investment = -sum(investment)
  invested = round(sum(df_portfolio_features['AvgCost']*df_portfolio_features['Shares']),0) + reserve_amt
  previous = round(sum(df_portfolio_features['Prev_Close']*df_portfolio_features['Shares']),0) + reserve_amt
  cy_invested = investment + py_booked_amt

  today_pnl_amount = current-previous
  today_pnl_percentage = round((current-previous)*100/previous,2)

  curr_pnl_amount = current-invested
  curr_pnl_percentage = round((curr_pnl_amount)*100/(cy_invested),2)

  cy_pnl_amount = cy_booked_amt + curr_pnl_amount
  cy_pnl_percentage = round((cy_pnl_amount)*100/cy_invested,2)

  overall_pnl_amount = total_booked_amt + curr_pnl_amount
  overall_pnl_percentage = round((overall_pnl_amount)*100/investment,2)

  estimate_st = round(sum(df_portfolio_features['FTT']*df_portfolio_features['Shares']),0)  + reserve_amt
  est_st_pnl_amount = estimate_st-current
  est_st_pnl_percentage = round((est_st_pnl_amount)*100/current,2)

  estimate_lt = round(sum(df_portfolio_features['LTT']*df_portfolio_features['Shares']),0)  + reserve_amt
  est_lt_pnl_amount = estimate_lt-current
  est_lt_pnl_percentage = round((est_lt_pnl_amount)*100/current,2)

  total_profit = round(sum(df_portfolio_features[df_portfolio_features['Current P/L%'] > 0]['Current']) - sum(df_portfolio_features[df_portfolio_features['Current P/L%'] > 0]['Investment']),0)
  total_loss = round(sum(df_portfolio_features[df_portfolio_features['Current P/L%'] < 0]['Current']) - sum(df_portfolio_features[df_portfolio_features['Current P/L%'] < 0]['Investment']),0)

  cy_booked_percentage = round((cy_booked_amt)*100/current,2)
  py_booked_percentage = round((py_booked_amt)*100/investment,2)
  total_booked_percentage = round((total_booked_amt)*100/investment,2)

  print('-------------------')
  print('Initial Investment: ', format_amt(investment))
  print('CY Investment: ', format_amt(cy_invested))
  print('Reserve: ', format_amt(reserve_amt))
  print('Current: ',  format_amt(current))
  print('-------------------')
  print('Today PnL: '+ '{} ({}%)'.format(format_amt(today_pnl_amount), today_pnl_percentage))
  print('Current PnL: '+ '{} ({}%)'.format(format_amt(curr_pnl_amount), curr_pnl_percentage))
  print('CY Booked + Current PnL: '+ '{} ({}%)'.format(format_amt(cy_pnl_amount), cy_pnl_percentage))
  print('-------------------')
  print('Total profit: ', format_amt(total_profit))
  print('Total loss: ', format_amt(total_loss))
  print('-------------------')
  print('Total Booked + Current PnL: '+ '{} ({}%)'.format(format_amt(overall_pnl_amount), overall_pnl_percentage))
  print('Total Booked PnL: '+ '{} ({}%)'.format(format_amt(total_booked_amt), total_booked_percentage))
  print('Curr Year Booked PnL: '+ '{} ({}%)'.format(format_amt(cy_booked_amt), cy_booked_percentage))
  print('Prev Year Booked PnL: '+ '{} ({}%)'.format(format_amt(py_booked_amt), py_booked_percentage))
  print('===================')
  print('Est FTT: ',  format_amt(estimate_st))
  print('Est FTT PnL: '+ '{} ({}%)'.format(format_amt(est_st_pnl_amount), est_st_pnl_percentage))

  print('===================')
  print('Deployed: ', format_amt(investment))

  print('Current: ', format_amt(current))

  print('CAGR/XIRR %: '+'{}%'.format(cagr))

In [8]:
# get start and end date
start_date, end_date = get_start_end_date()

# get portfolio and prospects data
mypfs_df = get_mypfs_df()
mypps_df = get_mypps_df()
myinvmt_df = get_myinvmt_df()

# merge above datasets
mypf_df = pd.merge(mypfs_df, mypps_df, on="Symbol")

# seggregate dm and sv portfolio
dm_pf = mypf_df[mypf_df['InPortfolio'] == 'DM']
sv_pf = mypf_df[mypf_df['InPortfolio'] == 'SV']

# build portfolio stock dataframe
dm_stocks = get_stock_ids(dm_pf)
sv_stocks = get_stock_ids(sv_pf)
df_stocks = pd.concat([dm_pf,sv_pf], ignore_index = True)

# arrange common and diff stock features
common_cols = ['Symbol', 'Target', 'Criteria', 'Strategy', 'CumlRnk', 'LatestQtr', 'StarStock', 'Conviction', 'Category', 'InFolio', 'XIRR', 'MBQ']
diff_cols = ['Symbol', 'AvgCost', 'Shares']
df_stocks = arrange_features(df_stocks, common_cols, diff_cols)

# get common features
stock_ids = df_stocks['Symbol'].values
df_common_features = get_common_features(stock_ids, df_stocks)

df_common_features.reset_index(drop=True, inplace=True)
df_common_features.drop(['Date'], axis=1, inplace=True)
# get and print portfolio features
df_portfolio_features = get_portfolio_features(df_common_features)

print_portfolio_stats(df_portfolio_features, myinvmt_df)

df = df_portfolio_features
#plot_pie_chart(df, 'CapType', 'Current')
list_ox40n = list(df[df['MBQ'].str.contains('OX40N', na=False)]['Symbol'].values)

Run date time (IST): 2026-08-21 09:26:54
-------------------
qualified stocks: 87
with latest results: 30
still star stocks: 19
-------------------
Initial Investment:  1.46 C
CY Investment:  1.89 C
Reserve:  3.69 L
Current:  1.58 C
-------------------
Today PnL: -26.85 K (-0.17%)
Current PnL: -35.04 L (-18.54%)
CY Booked + Current PnL: -29.98 L (-15.87%)
-------------------
Total profit:  3.57 L
Total loss:  -38.61 L
-------------------
Total Booked + Current PnL: 12.89 L (8.83%)
Total Booked PnL: 47.93 L (32.82%)
Curr Year Booked PnL: 5.06 L (3.2%)
Prev Year Booked PnL: 42.87 L (29.35%)
===================
Est FTT:  2.67 C
Est FTT PnL: 1.09 C (69.15%)
===================
Deployed:  1.46 C
Current:  1.58 C
CAGR/XIRR %: 3.53%

In [9]:
# top 5 near their targets
cols = ['Symbol', 'Today P/L%', 'Current P/L%', 'FTT%', 'OTT%', 'FTT Amt', 'Current P/L', 'Current', 'FTT', 'Dev%_PE', 'RSI_14','Conviction', 'Spread%',  'CumlRnk', 'RRR Ind', 'CurrAlloc%', 'Gained%', 'Criteria', 'Strategy', 'Category']
df_tmp = df_portfolio_features[~df_portfolio_features['Symbol'].isin(['ENRIN','BLUSPRING','DIGITIDE'])]
df_tmp = df_tmp.sort_values(by = 'FTT Amt', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
66,SIEMENS,0.87,5.15,5.40,10.83,10567.0,9590.0,195685.0,4125.00,-14.90,58.0,H-LC,14.29,51.0,0.91,1.27,38.07,AR,NTT,ELECTRICAL
78,UNITDSPR,0.97,13.04,6.84,20.77,18104.0,30530.0,264674.0,1644.00,-3.65,64.0,X-MC,11.35,64.0,1.69,1.72,27.23,X40N,NTT,BREWERIES
77,TTKPRESTIG,0.67,-23.44,30.73,0.09,23711.0,-23618.0,77159.0,770.00,-6.90,41.0,M-SC,9.41,250.0,-1.00,0.50,38.88,OX40N,NTT,DURABLES
52,M&M,-0.06,8.08,9.94,18.82,25856.0,19444.0,260125.0,3762.88,-6.96,58.0,X-LC,5.02,25.0,0.75,1.69,18.00,X40N,ATH,AUTO
67,SIS,0.67,-4.47,26.94,21.26,28574.0,-4965.0,106067.0,528.00,103.76,40.0,H-SC,20.44,168.0,-0.17,0.69,57.71,OX40N,NTT,MISC

In [10]:
# top 5 today
df_tmp = df_portfolio_features.sort_values(by = 'Today P/L%', ascending=False)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
31,HATHWAY,2.97,-40.73,192.36,73.29,123957.0,-44280.0,64440.0,31.40,NaN,48.0,NaN,2.74,171.0,-0.36,0.42,21.08,XR,NTT,ENTERTAINMENT
21,DEN,2.63,-46.77,166.90,42.07,75038.0,-39504.0,44960.0,75.00,NaN,54.0,NaN,5.46,235.0,-0.53,0.29,22.28,AR,NTT,ENTERTAINMENT
38,HYUNDAI,2.50,15.29,24.85,43.94,72005.0,38425.0,289757.0,2782.73,19.49,67.0,X-LC,5.69,29.0,0.53,1.88,33.04,X40N,ATH,AUTO
14,CAMPUS,2.32,-22.58,72.15,33.28,93721.0,-37878.0,129897.0,393.00,NaN,57.0,NaN,10.32,218.0,-0.40,0.84,6.24,XY24,NTT,FOOTWEAR
70,SYMPHONY,2.19,-52.91,112.27,-0.03,90487.0,-90543.0,80598.0,1306.00,NaN,32.0,NaN,16.86,205.0,-1.00,0.52,2.19,OX40N,NTT,DURABLES

In [11]:
# bottom 5 today
df_tmp = df_portfolio_features.sort_values(by = 'Today P/L%', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
0,5PAISA,-4.41,-26.18,52.95,12.90,85399.0,-57213.0,161283.0,593.0,3.45,56.0,H-SC,11.86,170.0,-0.67,1.05,55.64,OX40N,NTT,FINANCE
81,VALIANTORG,-3.62,-36.59,174.66,74.15,181182.0,-59871.0,103734.0,838.0,NaN,55.0,NaN,8.72,145.0,-0.33,0.67,54.37,XR,NTT,CHEMICALS
51,LAOPALA,-3.31,-47.18,163.34,39.09,113108.0,-61858.0,69247.0,464.0,NaN,40.0,NaN,3.81,154.0,-0.55,0.45,10.39,AR,NTT,CERAMICS
57,RAJESHEXPO,-2.66,-84.78,557.36,0.07,116388.0,-116295.0,20882.0,518.0,NaN,33.0,NaN,36.59,268.0,-1.00,0.14,3.13,OX40N,NTT,JEWELLERY
43,INDIGOPNTS,-2.44,-20.38,25.62,0.02,35606.0,-35580.0,138979.0,1408.0,-24.17,55.0,M-SC,7.49,222.0,-1.00,0.90,57.68,OX40N,NTT,PAINTS

In [12]:
# top 5 to exit based on CumlRnk
df_tmp = df_portfolio_features[~df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])]
df_tmp = df_tmp[(df_tmp['Current P/L%'] > -1) & (df_tmp['Current P/L%'] < 1)].sort_values(by = 'CumlRnk', ascending=False)
df_tmp[cols].head()

Empty DataFrame
Columns: [Symbol, Today P/L%, Current P/L%, FTT%, OTT%, FTT Amt, Current P/L, Current, FTT, Dev%_PE, RSI_14, Conviction, Spread%, CumlRnk, RRR Ind, CurrAlloc%, Gained%, Criteria, Strategy, Category]
Index: []

In [13]:
# OX40N stocks to exit
df_tmp = df_portfolio_features[(df_portfolio_features['Symbol'].isin(list_ox40n))].sort_values(by = 'Current P/L%', ascending=False)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
25,FINCABLES,-0.13,63.33,27.30,107.91,65833.0,93502.0,241146.0,1641.55,18.78,69.0,M-SC,22.66,220.0,1.42,1.56,81.42,OX40N,ATH,CABLES
67,SIS,0.67,-4.47,26.94,21.26,28574.0,-4965.0,106067.0,528.00,103.76,40.0,H-SC,20.44,168.0,-0.17,0.69,57.71,OX40N,NTT,MISC
43,INDIGOPNTS,-2.44,-20.38,25.62,0.02,35606.0,-35580.0,138979.0,1408.00,-24.17,55.0,M-SC,7.49,222.0,-1.00,0.90,57.68,OX40N,NTT,PAINTS
12,BOSCH-HCIL,-0.38,-22.65,29.27,-0.01,28935.0,-28948.0,98857.0,2282.00,774.64,78.0,M-SC,10.45,231.0,-1.00,0.64,68.27,OX40N,BTT,AC
77,TTKPRESTIG,0.67,-23.44,30.73,0.09,23711.0,-23618.0,77159.0,770.00,-6.90,41.0,M-SC,9.41,250.0,-1.00,0.50,38.88,OX40N,NTT,DURABLES

In [14]:
# top 5 to book for rotation
df_tmp = df_portfolio_features[(df_portfolio_features['Current P/L%'] > 20) ].sort_values(by = 'CumlRnk', ascending=False)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
25,FINCABLES,-0.13,63.33,27.3,107.91,65833.0,93502.0,241146.0,1641.55,18.78,69.0,M-SC,22.66,220.0,1.42,1.56,81.42,OX40N,ATH,CABLES

In [15]:
# top 5 to monitor for exit
df_tmp = df_portfolio_features[~df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])]
df_tmp = df_tmp[(df_tmp['Current P/L%'] > 0) ].sort_values(by = 'Dev%_PE', ascending=False)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
25,FINCABLES,-0.13,63.33,27.30,107.91,65833.0,93502.0,241146.0,1641.55,18.78,69.0,M-SC,22.66,220.0,1.42,1.56,81.42,OX40N,ATH,CABLES
68,STARHEALTH,-1.58,11.00,32.67,47.26,101943.0,30915.0,312038.0,761.00,-2.08,43.0,H-SC,16.00,173.0,0.30,2.02,34.92,XY24,NTT,INSURANCE

In [16]:
# top 5 to book for rotation from weak conviction
df_tmp = df_portfolio_features[~df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])]
df_tmp = df_tmp[~df_tmp['Criteria'].isin(['XY25','XY24','X40', 'X40N'])].sort_values(by = 'RRR Ind', ascending=False)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
25,FINCABLES,-0.13,63.33,27.30,107.91,65833.0,93502.0,241146.0,1641.55,18.78,69.0,M-SC,22.66,220.0,1.42,1.56,81.42,OX40N,ATH,CABLES
3,ALKYLAMINE,-1.53,-17.97,134.72,92.54,111578.0,-18141.0,82822.0,4520.85,NaN,56.0,NaN,14.94,142.0,-0.16,0.54,57.27,SR,ATH,CHEMICALS
67,SIS,0.67,-4.47,26.94,21.26,28574.0,-4965.0,106067.0,528.00,103.76,40.0,H-SC,20.44,168.0,-0.17,0.69,57.71,OX40N,NTT,MISC
42,INDIAMART,1.14,-24.63,166.57,100.92,154847.0,-30374.0,92962.0,4675.60,NaN,40.0,NaN,13.66,140.0,-0.20,0.60,1.14,AR,ATH,MISC
71,TANLA,1.28,-34.43,231.35,117.25,410706.0,-93235.0,177526.0,1922.32,NaN,49.0,NaN,15.21,147.0,-0.23,1.15,55.43,AR,ATH,IT

In [17]:
# top 5 to accumulate based on lowest RSI_14
df_tmp = df_portfolio_features[df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])].sort_values(by = 'RSI_14', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
56,PGHH,-0.27,-38.43,114.40,32.01,150404.0,-82048.0,131472.0,17616.87,-54.78,27.0,X-SC,19.43,57.0,-0.55,0.85,0.00,X40,ATH,FMCG
55,PAGEIND,0.58,-7.55,43.70,32.85,108426.0,-20264.0,248115.0,50936.07,-31.21,30.0,X-MC,8.56,55.0,-0.19,1.61,18.48,X40,ATH,APPARELS
20,DABUR,-0.12,-21.89,83.98,43.70,162718.0,-54310.0,193758.0,735.00,-32.67,32.0,X-MC,10.51,70.0,-0.33,1.26,0.00,XY24,BTT,FMCG
19,COLPAL,-0.84,-28.09,94.49,39.86,178955.0,-73975.0,189390.0,3683.41,-12.94,33.0,X-MC,2.28,62.0,-0.41,1.23,7.13,XY25,ATH,FMCG
1,ABBOTINDIA,-0.38,-12.71,32.17,15.37,50224.0,-22735.0,156120.0,34390.26,-29.03,33.0,X-MC,3.07,58.0,-0.45,1.01,5.75,X40,ATH,PHARMA

In [18]:
# top 5 to accumulate based on Spread and CumlRnk
df_tmp = df_portfolio_features[df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])]
df_tmp = df_tmp[(df_tmp['CumlRnk'] < 100)].sort_values(by = 'Spread%', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
50,KOTAKBANK,0.55,5.01,13.24,18.92,33327.0,12014.0,251716.0,452.46,-11.03,59.0,X-LC,2.05,12.0,0.36,1.63,13.25,X40,ATH,BANKS
19,COLPAL,-0.84,-28.09,94.49,39.86,178955.0,-73975.0,189390.0,3683.41,-12.94,33.0,X-MC,2.28,62.0,-0.41,1.23,7.13,XY25,ATH,FMCG
23,DMART,-0.57,-3.90,36.76,31.42,110138.0,-12175.0,299615.0,5391.45,-19.39,43.0,X-LC,2.30,14.0,-0.11,1.94,8.12,X40N,ATH,FMCG
1,ABBOTINDIA,-0.38,-12.71,32.17,15.37,50224.0,-22735.0,156120.0,34390.26,-29.03,33.0,X-MC,3.07,58.0,-0.45,1.01,5.75,X40,ATH,PHARMA
26,GILLETTE,0.28,-11.07,45.88,29.72,103588.0,-28116.0,225780.0,10978.86,-35.84,38.0,X-SC,3.74,83.0,-0.27,1.46,3.76,X40,ATH,FMCG

In [19]:
# top 5 to accumulate based on lowest Gained%
df_tmp = df_portfolio_features[df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])].sort_values(by = 'Gained%', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
20,DABUR,-0.12,-21.89,83.98,43.70,162718.0,-54310.0,193758.0,735.00,-32.67,32.0,X-MC,10.51,70.0,-0.33,1.26,0.00,XY24,BTT,FMCG
56,PGHH,-0.27,-38.43,114.40,32.01,150404.0,-82048.0,131472.0,17616.87,-54.78,27.0,X-SC,19.43,57.0,-0.55,0.85,0.00,X40,ATH,FMCG
36,HINDUNILVR,0.25,-15.72,44.24,21.56,125470.0,-52905.0,283612.0,2922.00,-41.98,38.0,X-LC,6.62,9.0,-0.42,1.84,0.25,XY25,NTT,FMCG
83,VOLTAS,0.46,-4.16,51.50,45.20,94639.0,-7977.0,183765.0,1856.00,31.93,36.0,X-MC,5.18,79.0,-0.08,1.19,0.72,XY25,NTT,AC
35,HDFCLIFE,-0.37,-7.39,50.26,39.15,116704.0,-18537.0,232200.0,811.41,-31.88,44.0,X-LC,16.42,31.0,-0.16,1.51,0.77,X40,ATH,INSURANCE

In [20]:
# top 5 to accumulate based on lowest CurrAlloc%
df_tmp = df_portfolio_features[df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])].sort_values(by = 'CurrAlloc%', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
56,PGHH,-0.27,-38.43,114.40,32.01,150404.0,-82048.0,131472.0,17616.87,-54.78,27.0,X-SC,19.43,57.0,-0.55,0.85,0.00,X40,ATH,FMCG
1,ABBOTINDIA,-0.38,-12.71,32.17,15.37,50224.0,-22735.0,156120.0,34390.26,-29.03,33.0,X-MC,3.07,58.0,-0.45,1.01,5.75,X40,ATH,PHARMA
2,ACC,1.25,-41.60,199.36,74.81,312150.0,-111552.0,156576.0,3906.00,-42.24,39.0,X-SC,11.60,85.0,-0.36,1.02,4.60,XY24,BTT,CEMENT
40,ICICIPRULI,1.34,-16.24,55.53,30.28,91636.0,-31984.0,165021.0,787.27,-46.34,51.0,X-MC,12.20,78.0,-0.35,1.07,9.95,X40,ATH,INSURANCE
39,ICICIGI,0.35,-14.11,38.42,18.89,66032.0,-28241.0,171868.0,2244.41,-14.33,41.0,X-MC,10.14,66.0,-0.43,1.11,2.39,X40,ATH,INSURANCE

In [21]:
# top 5 to accumulate based on CumlRnk
df_tmp = df_portfolio_features.sort_values(by = 'CumlRnk', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
47,ITC,-0.42,-25.38,67.10,24.70,198930.0,-100810.0,296468.0,452.00,-30.35,37.0,X-LC,10.47,1.0,-0.51,1.92,1.29,X40,NTT,FMCG
73,TCS,-1.24,-33.38,86.42,24.20,266725.0,-154635.0,308638.0,4230.71,-44.65,45.0,X-LC,13.68,2.0,-0.58,2.00,15.09,X40,ATH,IT
45,INFY,-0.47,-19.94,75.34,40.38,227090.0,-75050.0,301420.0,1972.00,-41.25,48.0,X-LC,15.61,3.0,-0.33,1.95,14.15,X40,NTT,IT
75,TMPV,0.34,-23.54,86.71,42.75,275856.0,-97971.0,318136.0,600.00,-84.91,36.0,X-LC,4.35,4.0,-0.36,2.06,9.39,XY24,NTT,AUTO
33,HCLTECH,-0.92,-12.21,41.20,23.97,111944.0,-37778.0,271708.0,1853.42,-14.68,53.0,X-LC,10.70,8.0,-0.34,1.76,28.21,X40,ATH,IT

In [22]:
# top 5 for average up
df_tmp = df_portfolio_features[(df_portfolio_features['Dev%_200'] > 5)].sort_values(by = 'CurrAlloc%', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
44,INDUSINDBK,-0.69,-26.10,79.82,32.89,45543.0,-20150.0,57057.0,1800.00,320.23,47.0,L-MC,12.17,258.0,-0.44,0.37,40.67,XR,NTT,BANKS
3,ALKYLAMINE,-1.53,-17.97,134.72,92.54,111578.0,-18141.0,82822.0,4520.85,NaN,56.0,NaN,14.94,142.0,-0.16,0.54,57.27,SR,ATH,CHEMICALS
12,BOSCH-HCIL,-0.38,-22.65,29.27,-0.01,28935.0,-28948.0,98857.0,2282.00,774.64,78.0,M-SC,10.45,231.0,-1.00,0.64,68.27,OX40N,BTT,AC
81,VALIANTORG,-3.62,-36.59,174.66,74.15,181182.0,-59871.0,103734.0,838.00,NaN,55.0,NaN,8.72,145.0,-0.33,0.67,54.37,XR,NTT,CHEMICALS
67,SIS,0.67,-4.47,26.94,21.26,28574.0,-4965.0,106067.0,528.00,103.76,40.0,H-SC,20.44,168.0,-0.17,0.69,57.71,OX40N,NTT,MISC

In [23]:
# top 5 RSP
df_tmp = df_portfolio_features.sort_values(by = 'RSP', ascending=False)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
12,BOSCH-HCIL,-0.38,-22.65,29.27,-0.01,28935.0,-28948.0,98857.0,2282.00,774.64,78.0,M-SC,10.45,231.0,-1.00,0.64,68.27,OX40N,BTT,AC
25,FINCABLES,-0.13,63.33,27.30,107.91,65833.0,93502.0,241146.0,1641.55,18.78,69.0,M-SC,22.66,220.0,1.42,1.56,81.42,OX40N,ATH,CABLES
27,GLAXO,-2.08,19.20,13.84,35.69,32876.0,38260.0,237544.0,3380.16,-10.63,77.0,X-MC,10.76,56.0,1.16,1.54,41.18,X40,ATH,PHARMA
38,HYUNDAI,2.50,15.29,24.85,43.94,72005.0,38425.0,289757.0,2782.73,19.49,67.0,X-LC,5.69,29.0,0.53,1.88,33.04,X40N,ATH,AUTO
81,VALIANTORG,-3.62,-36.59,174.66,74.15,181182.0,-59871.0,103734.0,838.00,NaN,55.0,NaN,8.72,145.0,-0.33,0.67,54.37,XR,NTT,CHEMICALS

In [24]:
# Top N allocation
df_tmp = df_portfolio_features.sort_values(by = 'CurrAlloc%', ascending=False)
top_n_values = [10, 25, 50]

sum_df = pd.DataFrame({
    'Top_N': top_n_values,
    'Sum_Alloc%': [df_tmp['CurrAlloc%'].head(n).sum() for n in top_n_values]
})

sum_df

   Top_N  Sum_Alloc%
0     10       19.68
1     25       45.02
2     50       77.64

In [25]:
# market-cap-wise allocation
df_tmp = df_portfolio_features[cols]
df_tmp.groupby(df_tmp['Conviction'].str[-2:])['CurrAlloc%'].sum().sort_values(ascending=False)

Conviction
LC    38.09
MC    22.22
SC    21.53
Name: CurrAlloc%, dtype: float64

In [26]:
# criteria-wise allocation
df_portfolio_features.groupby('Criteria')['CurrAlloc%'].sum().sort_values(ascending=False)

Criteria
X40      26.65
XY24     23.99
X40N     18.75
XR        9.13
OX40N     7.32
XY25      7.16
AR        6.11
SR        0.87
Name: CurrAlloc%, dtype: float64

In [27]:
# conviction-wise allocation
df_portfolio_features.groupby('Conviction')['CurrAlloc%'].sum().sort_values(ascending=False)

Conviction
X-LC    34.42
X-MC    19.64
H-SC     8.51
X-SC     7.61
M-SC     5.41
H-LC     2.86
M-MC     1.17
H-MC     1.04
M-LC     0.81
L-MC     0.37
Name: CurrAlloc%, dtype: float64

In [28]:
# sector-wise stats
df_tmp = df_portfolio_features.groupby('Category')[['CurrAlloc%', 'Current', 'Current P/L', 'FTT Amt']].sum().sort_values(by=['Current', 'Current P/L'], ascending=False)
df_tmp['Current P/L%'] = round(df_tmp['Current P/L'] * 100 / df_tmp['Current'], 2)
df_tmp['FTT%'] = round(df_tmp['FTT Amt'] * 100 / df_tmp['Current'], 2)
cols = ['CurrAlloc%', 'Current P/L%', 'FTT%']
df_tmp[cols].sort_values(by=['CurrAlloc%'], ascending=False)

               CurrAlloc%  Current P/L%    FTT%
Category
FMCG                15.41        -25.48   70.59
IT                  11.21        -37.79  106.13
FINANCE             10.77        -16.32   66.43
AUTO                 8.32         -5.54   43.34
BANKS                6.23        -10.94   58.78
MISC                 5.93        -34.81   89.04
PHARMA               5.85          8.19   17.85
INSURANCE            5.71         -5.43   42.71
PAINTS               5.41        -17.89   38.00
ELECTRICAL           4.18         -9.71   44.06
AC                   1.83        -13.07   43.72
REFINERIES           1.73        -11.45   48.88
BREWERIES            1.72         11.53    6.84
FOOTWEAR             1.67        -70.80  139.29
APPARELS             1.61         -8.17   43.70
CABLES               1.56         38.77   27.30
DURABLES             1.48        -68.56  109.56
TRAVEL               1.43       -104.01  206.16
CERAMICS             1.32        -51.02   96.90
ENGINEERING          1.26        -24.67   81.69
CHEMICALS            1.21        -41.82  156.93
CEMENT               1.02        -71.24  199.36
JEWELLERY            0.97       -115.84  190.84
ENTERTAINMENT        0.71        -76.59  181.90
HEALTHCARE           0.69        -70.30  113.04
TEXTILES             0.39        -51.71   94.96
HOTELS               0.36       -102.53  173.97

In [29]:
# money to be made criteria-wise
df_portfolio_features.groupby('Criteria')['FTT Amt'].agg(['sum', 'count']).sort_values(by='sum', ascending=False)

                sum  count
Criteria
XY24      3627068.0     19
X40       2110922.0     18
XR        1387507.0     13
X40N      1189253.0     12
AR        1063933.0      8
OX40N      663393.0     10
XY25       594943.0      5
SR         282270.0      2

In [30]:
# money to be made conviction-wise
df_portfolio_features.groupby('Conviction')['FTT Amt'].agg(['sum', 'count']).sort_values(by='sum', ascending=False)

                  sum  count
Conviction
X-LC        2417558.0     19
X-MC        1473545.0     14
X-SC        1104656.0      6
H-SC         837638.0      8
M-SC         328859.0      6
H-MC         254054.0      1
M-LC         166291.0      1
M-MC          65143.0      1
H-LC          49210.0      2
L-MC          45543.0      1

In [31]:
# money to be made criteria and conviction-wise
df_portfolio_features.groupby(['Conviction', 'Criteria'])['FTT Amt'].agg(['sum', 'count']).sort_values(by='sum', ascending=False)

                           sum  count
Conviction Criteria
X-LC       X40       1227682.0      9
X-SC       XY24       675396.0      2
H-SC       XY24       527782.0      3
X-MC       X40        513806.0      6
X-LC       XY24       459300.0      2
X-MC       X40N       449233.0      4
X-LC       X40N       413789.0      5
X-MC       XY25       273594.0      2
X-LC       XY25       256206.0      2
H-MC       XY24       254054.0      1
X-SC       X40        253992.0      2
X-MC       XY24       236912.0      2
H-SC       OX40N      218548.0      3
X-SC       X40N       175268.0      2
M-LC       XR         166291.0      1
M-SC       OX40N      154085.0      4
           XY24       117028.0      1
H-SC       XR          91308.0      2
M-MC       XY25        65143.0      1
X-LC       XR          60581.0      1
M-SC       XR          57746.0      1
H-LC       AR          49210.0      2
L-MC       XR          45543.0      1

In [32]:
# notebook execution time

end_time = time.time()
execution_time = round(end_time - start_time, 0)
print(f"Notebook execution time: {execution_time} seconds")

Notebook execution time: 38.0 seconds