<a href="https://colab.research.google.com/github/ankit-rathi/Quantvesting_v2/blob/main/myStocks_Portfolio_Analysis.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
'''
!pip install pandas==2.2.2 -qq
!pip install pyxirr -qq
!pip install ta -qq
!pip install yfinance==0.2.59 -qq
'''

'\n!pip install pandas==2.2.2 -qq\n!pip install pyxirr -qq\n!pip install ta -qq\n!pip install yfinance==0.2.59 -qq\n'

In [2]:
# import libraries

import numpy as np
import pandas as pd
import datetime
import warnings
warnings.filterwarnings('ignore')
import yfinance as yfin
import ta
import matplotlib.pyplot as plt
import requests

In [3]:
# notebook start time
import time
import datetime
import pytz

start_time = time.time()

# function to print date timestamp
def print_date_time():
  tz_NY = pytz.timezone('Asia/Kolkata')
  datetime_NY = datetime.datetime.now(tz_NY)
  print("Run date time (IST):", datetime_NY.strftime("%Y-%m-%d %H:%M:%S"))

In [4]:
# function to get booked and reserved amount
def get_amt():
  # fetch the JSON data from the URL
  url = "https://raw.githubusercontent.com/ankit-rathi/Tradevesting_v1/main/data/myPortfolioAmts.json"
  response = requests.get(url)
  pf_amts = response.json()  # parse the JSON data

  # extract values from the JSON
  py_booked_amt_dm = pf_amts["py_booked_amt_dm"]
  py_booked_amt_sv = pf_amts["py_booked_amt_sv"]
  cy_booked_amt_dm = pf_amts["cy_booked_amt_dm"]
  cy_booked_amt_sv = pf_amts["cy_booked_amt_sv"]
  reserve_amt_dm = pf_amts["reserve_amt_dm"]
  reserve_amt_sv = pf_amts["reserve_amt_sv"]

  # perform calculations
  py_booked_amt = py_booked_amt_dm + py_booked_amt_sv
  cy_booked_amt = cy_booked_amt_dm + cy_booked_amt_sv
  reserve_amt = reserve_amt_dm + reserve_amt_sv
  total_booked_amt = py_booked_amt + cy_booked_amt

  return total_booked_amt, reserve_amt, cy_booked_amt, py_booked_amt

gen_output = 0

In [5]:
# function to format the amount
def format_amt(number):
    abs_number = abs(number)

    if abs_number >= 1_00_00_000:  # Crores
        formatted_amt = f"{number / 1_00_00_000:.2f} C"
    elif abs_number >= 1_00_000:  # Lakhs
        formatted_amt = f"{number / 1_00_000:.2f} L"
    elif abs_number >= 1_000:  # Thousands
        formatted_amt = f"{number / 1_000:.2f} K"
    else:
        formatted_amt = f"{number:.2f}"

    return formatted_amt

# function to set start and end date
def get_start_end_date():
  start_date = (datetime.date.today() + datetime.timedelta(days=-365)).strftime('%Y-%m-%d')
  end_date = (datetime.date.today() + datetime.timedelta(days=1)).strftime('%Y-%m-%d')
  return start_date, end_date

# function to fetch my portfolio csv
def get_mypfs_df():
  mypfs_df = pd.read_csv('https://raw.githubusercontent.com/ankit-rathi/Tradevesting_v1/main/data/myPortfolioStocks.csv')
  return mypfs_df

# function to fetch my prospects csv
def get_mypps_df():
  mypps_df = pd.read_csv('https://raw.githubusercontent.com/ankit-rathi/Tradevesting_v1/main/data/myProspectsScrips.csv')
  return mypps_df

# function to fetch screener data
def get_myscreen_df():
  myscreen_df = pd.read_csv('https://raw.githubusercontent.com/ankit-rathi/Tradevesting_v1/main/data/myScreenerDB.csv')
  return myscreen_df

# function to fetch momentum data
def get_myinvmt_df():
  myinvmt_df = pd.read_csv('https://raw.githubusercontent.com/ankit-rathi/Tradevesting_v1/main/data/myInvestments.csv')
  return myinvmt_df

# function to get the stock ids
def get_stock_ids(df_pf):
  stock_n100 = df_pf['Symbol'].unique()

  exclude = ['CADILAHC','MMTC', 'MASFIN']

  stock_ids = df_pf[~df_pf['Symbol'].isin(exclude) ]['Symbol'].unique()

  #mypf = mypf[mypf.Forecast.notnull()]
  #stock_ids = mypf['Symbol'].unique()

  #stock_ids.sort()
  return stock_ids

# get features from screener data
def get_screener_features():
  myscreen_df = get_myscreen_df()
  cols = ['Symbol', 'EPS', 'MedPE', 'ROCE%', 'ROE%', 'CapType']
  return myscreen_df[cols]

# get relative strength
def get_relative_strength(stock_list):

    # Dictionary to store stock tickers and their corresponding percentage price change
    stock_changes = {}

    # Loop through each stock and fetch its price data
    for stock in stock_list:
        try:
            # Download the stock data for the given date range
            stock_data = yfin.Ticker(stock + '.NS').history(period='1mo', interval='1d')[map(str.title, ['open', 'close', 'low', 'high', 'volume'])]

            # Calculate the percentage change for the stock
            if len(stock_data) > 0:
                start_price = stock_data['Close'].iloc[0]
                end_price = stock_data['Close'].iloc[-1]
                percent_change = round(((end_price - start_price) / start_price) * 100, 2)
                stock_changes[stock] = percent_change
            else:
                stock_changes[stock] = np.nan  # If no data is available, set to NaN

        except Exception as e:
            print(f"Error fetching data for {stock}: {e}")
            stock_changes[stock] = np.nan

    # Create a DataFrame with stock tickers and their percentage changes
    df = pd.DataFrame(list(stock_changes.items()), columns=['Symbol', 'Percent_Change'])

    # Drop any stocks with missing data (NaN values)
    df = df.dropna()

    # Calculate the percentile rank based on percentage change
    df['RSP'] = round(df['Percent_Change'].rank(pct=True) * 100, 2)
    cols = ['Symbol', 'RSP']
    df = df[cols]
    # Sort by percentile rank (optional)
    df = df.sort_values(by='RSP', ascending=False).reset_index(drop=True)

    return df

In [6]:
# function to get stock technicals
def stock_prec_dev(stock_symbol):
    #stock_symbol = 'ULTRACEMCO.NS'
    short_window = 20
    mid_window = 50
    long_window = 200
    moving_avg = 'SMA'

    start = datetime.datetime(*map(int, start_date.split('-')))
    end = datetime.datetime(*map(int, end_date.split('-')))

    stock_df = yfin.Ticker(stock_symbol + '.NS').history(period='max', interval='1d')[map(str.title, ['open', 'close', 'low', 'high', 'volume'])]

    stock_df['Max'] = round(max(stock_df['Close']),2)
    stock_df = stock_df[(stock_df.index <= end_date) & (stock_df.index >= start_date)]
    stock_df['200_SMA'] = round(stock_df['Close'].rolling(window = 200, min_periods = 1).mean(),0)
    stock_df['Dev%_200'] = round((stock_df['Close'] - stock_df['200_SMA'])*100/stock_df['200_SMA'],2)
    stock_df.dropna(axis = 0, inplace = True) # remove any null rows

    stock_df['20_SMA'] = stock_df['Close'].rolling(window=20).mean()
    stock_df['50_SMA'] = stock_df['Close'].rolling(window=50).mean()
    stock_df['Symbol'] = stock_symbol

    stock_df['Close'] = round(stock_df['Close'],2)
    stock_df['Min'] = round(min(stock_df['Close']),2)
    stock_df['RSI_14'] = ta.momentum.RSIIndicator(close=stock_df['Close'], window=14).rsi()
    stock_df['RSI_14'] = round(stock_df['RSI_14'],0)
    stock_df['Prev_Close'] = stock_df['Close'].shift(1)
    stock_df.drop(['Open', 'Low', 'High', 'Volume'], axis=1, inplace=True)
    stock_df = stock_df.tail(1)

    max_SMA = max(stock_df['20_SMA'].item(), stock_df['50_SMA'].item(), stock_df['200_SMA'].item())
    min_SMA = min(stock_df['20_SMA'].item(), stock_df['50_SMA'].item(), stock_df['200_SMA'].item())
    ABS_Spread = max_SMA - min_SMA
    stock_df['Spread%'] = round((ABS_Spread / stock_df['200_SMA'].item()) * 100,2)

    return stock_df

# function to compute stock attributes
def get_common_features(stock_ids, df_mypf):

  df_prec_dev = pd.DataFrame()
  df_tmp = get_screener_features()
  df_rs = get_relative_strength(stock_ids)

  for stock_id in stock_ids:
      tmp = stock_prec_dev(stock_id)
      tmp = tmp.reset_index()
      df_prec_dev = pd.concat([df_prec_dev, tmp], ignore_index = True)
  df_prec_dev = pd.merge(df_prec_dev, df_mypf, on= 'Symbol')
  df_prec_dev = pd.merge(df_prec_dev, df_tmp, on= 'Symbol', how='left')
  df_prec_dev = pd.merge(df_prec_dev, df_rs, on= 'Symbol', how='left')
  #print(df_prec_dev.columns)
  df_prec_dev['Curr_PE'] = round(df_prec_dev['Close']/df_prec_dev['EPS'],1)
  df_prec_dev['Dev%_PE'] = round((df_prec_dev['Curr_PE'] - df_prec_dev['MedPE'])*100/df_prec_dev['MedPE'],2)
  df_prec_dev['Conviction'] = df_prec_dev['Conviction'] + '-' + df_prec_dev['CapType']
  return df_prec_dev

# function to arrange stock features
def arrange_features(df_stocks, common_cols, diff_cols):
  df_stocks_common = df_stocks[common_cols].drop_duplicates()
  df_stocks_diff = df_stocks[diff_cols]
  df_stocks_diff['Investment'] = df_stocks_diff['AvgCost'] * df_stocks_diff['Shares']
  df_stocks_diff = df_stocks_diff.groupby(['Symbol'])[['Shares', 'Investment']].aggregate(['sum']).reset_index()
  df_stocks_diff.columns = ['Symbol', 'Shares', 'Investment']
  df_stocks_diff['AvgCost'] = round(df_stocks_diff['Investment']/df_stocks_diff['Shares'],2)
  df_stocks = pd.merge(df_stocks_diff, df_stocks_common, on='Symbol')
  return df_stocks

# plot fact distribution across dimension
def plot_pie_chart(df, dimension, fact):
  # grouping the data by category and calculating the sum of fact for each type
  grouped_data = df.groupby(dimension)[fact].sum()

  # sorting the grouped data in descending order
  grouped_data = grouped_data.sort_values(ascending=False)

  # creating a pie chart
  grouped_data.plot.pie(autopct='%1.1f%%', startangle=90, figsize=(6, 6))

  # adding a title and displaying the plot
  plt.title(f'{dimension} {fact} Distribution')
  plt.ylabel('')  # To hide the y-label
  plt.show()

In [7]:
# function to get portfolio features

def get_portfolio_features(df_common_features):

  print_date_time()
  print('-------------------')

  #df_common_features["Target"] = df_common_features["Target"].fillna(df_common_features["Max"])
  df_common_features['NTT'] = np.where(df_common_features['Strategy']== 'NTT', df_common_features["Target"], df_common_features['Max'])
  df_common_features['LTT'] = np.where(df_common_features['Strategy']== 'BTT', df_common_features["Target"], df_common_features['Max'])
  df_common_features['BOL'] = df_common_features['Min']

  tmp_df = df_common_features[df_common_features['Symbol'].isin(mypf_df[mypf_df['InPortfolio'] != 'NA'].Symbol.values)]
  print('qualified stocks: '+str(len(tmp_df['Symbol'].unique())))
  tmp_df1 = tmp_df[tmp_df['LatestQtr'] == 1]
  print('with latest results: '+str(len(tmp_df1['Symbol'].unique())))
  tmp_df1 = tmp_df1[tmp_df1['StarStock'] == 1]
  print('still star stocks: '+str(len(tmp_df1['Symbol'].unique())))
  tmp_df['Investment'] = tmp_df['AvgCost'] * tmp_df['Shares']
  tmp_df['Current'] = round(tmp_df['Close'] * tmp_df['Shares'],0)
  tmp_df['Previous'] = tmp_df['Prev_Close'] * tmp_df['Shares']
  tmp_df['EstimatedST'] = tmp_df['NTT'] * tmp_df['Shares']
  tmp_df['EstimatedLT'] = tmp_df['LTT'] * tmp_df['Shares']
  tmp_df['Current P/L'] = round((tmp_df['Current'] - tmp_df['Investment']),0)
  tmp_df['Today P/L%'] = round((tmp_df['Current'] - tmp_df['Previous'])*100/tmp_df['Previous'],2)
  tmp_df['Current P/L%'] = round((tmp_df['Current'] - tmp_df['Investment'])*100/tmp_df['Investment'],2)
  tmp_df['EstimatedST P/L%'] = round((tmp_df['EstimatedST'] - tmp_df['Investment'])*100/tmp_df['Investment'],2)
  tmp_df['EstimatedLT P/L%'] = round((tmp_df['EstimatedLT'] - tmp_df['Investment'])*100/tmp_df['Investment'],2)
  tmp_df['NTT%'] = round((tmp_df['NTT'] - tmp_df['Close'])*100/tmp_df['Close'],2)
  tmp_df['LTT%'] = round((tmp_df['LTT'] - tmp_df['Close'])*100/tmp_df['Close'],2)
  tmp_df['Gained%'] = round((tmp_df['Close'] - tmp_df['BOL'])*100/tmp_df['BOL'],2)
  investment = round(sum(tmp_df['AvgCost']*tmp_df['Shares']),0)
  current = round(sum(tmp_df['Close']*tmp_df['Shares']),0)
  tmp_df['InitAlloc%'] = round(tmp_df['Investment']*100/investment,2)
  tmp_df['CurrAlloc%'] = round(tmp_df['Current']*100/current,2)
  tmp_df['FTT'] = tmp_df['LTT']
  tmp_df.loc[tmp_df['Strategy'] == 'NTT', 'FTT'] = tmp_df['NTT']
  tmp_df['FTT%'] = tmp_df['LTT%']
  tmp_df.loc[tmp_df['Strategy'] == 'NTT', 'FTT%'] = tmp_df['NTT%']
  tmp_df['FTT Amt'] = round(tmp_df['FTT%'] * tmp_df['Current']/100,0)
  tmp_df['OTT%'] = round((tmp_df['FTT'] - tmp_df['AvgCost'])*100/tmp_df['AvgCost'],2)
  tmp_df['RRR Ind'] = round(tmp_df['Current P/L']/tmp_df['FTT Amt'],2)
  tmp_df['Risk Ind'] = round(tmp_df['Current P/L%']*tmp_df['CurrAlloc%'],0)

  return tmp_df

# function to print portfolio features
def print_portfolio_stats(df_portfolio_features, myinvmt_df):
  from pyxirr import xirr

  total_booked_amt, reserve_amt, cy_booked_amt, py_booked_amt = get_amt()

  dates = myinvmt_df['Date'].values
  dates = np.append(dates, datetime.date.today().strftime('%d-%b-%y'))
  investment = myinvmt_df['Investment'].values
  dates= pd.to_datetime(dates)

  current = round(sum(df_portfolio_features['Close']*df_portfolio_features['Shares']),0) + reserve_amt
  investment_xirr = np.append(investment, current)
  cagr = round(xirr(pd.DataFrame({"dates": dates, "amounts": investment_xirr}))*100,2)

  investment = -sum(investment)
  invested = round(sum(df_portfolio_features['AvgCost']*df_portfolio_features['Shares']),0) + reserve_amt
  previous = round(sum(df_portfolio_features['Prev_Close']*df_portfolio_features['Shares']),0) + reserve_amt
  cy_invested = investment + py_booked_amt

  today_pnl_amount = current-previous
  today_pnl_percentage = round((current-previous)*100/previous,2)

  curr_pnl_amount = current-invested
  curr_pnl_percentage = round((curr_pnl_amount)*100/(cy_invested),2)

  cy_pnl_amount = cy_booked_amt + curr_pnl_amount
  cy_pnl_percentage = round((cy_pnl_amount)*100/cy_invested,2)

  overall_pnl_amount = total_booked_amt + curr_pnl_amount
  overall_pnl_percentage = round((overall_pnl_amount)*100/investment,2)

  estimate_st = round(sum(df_portfolio_features['FTT']*df_portfolio_features['Shares']),0)  + reserve_amt
  est_st_pnl_amount = estimate_st-current
  est_st_pnl_percentage = round((est_st_pnl_amount)*100/current,2)

  estimate_lt = round(sum(df_portfolio_features['LTT']*df_portfolio_features['Shares']),0)  + reserve_amt
  est_lt_pnl_amount = estimate_lt-current
  est_lt_pnl_percentage = round((est_lt_pnl_amount)*100/current,2)

  total_profit = round(sum(df_portfolio_features[df_portfolio_features['Current P/L%'] > 0]['Current']) - sum(df_portfolio_features[df_portfolio_features['Current P/L%'] > 0]['Investment']),0)
  total_loss = round(sum(df_portfolio_features[df_portfolio_features['Current P/L%'] < 0]['Current']) - sum(df_portfolio_features[df_portfolio_features['Current P/L%'] < 0]['Investment']),0)

  cy_booked_percentage = round((cy_booked_amt)*100/current,2)
  py_booked_percentage = round((py_booked_amt)*100/investment,2)
  total_booked_percentage = round((total_booked_amt)*100/investment,2)

  print('-------------------')
  print('Initial Investment: ', format_amt(investment))
  print('CY Investment: ', format_amt(cy_invested))
  print('Reserve: ', format_amt(reserve_amt))
  print('Current: ',  format_amt(current))
  print('-------------------')
  print('Today PnL: '+ '{} ({}%)'.format(format_amt(today_pnl_amount), today_pnl_percentage))
  print('Current PnL: '+ '{} ({}%)'.format(format_amt(curr_pnl_amount), curr_pnl_percentage))
  print('CY Booked + Current PnL: '+ '{} ({}%)'.format(format_amt(cy_pnl_amount), cy_pnl_percentage))
  print('-------------------')
  print('Total profit: ', format_amt(total_profit))
  print('Total loss: ', format_amt(total_loss))
  print('-------------------')
  print('Total Booked + Current PnL: '+ '{} ({}%)'.format(format_amt(overall_pnl_amount), overall_pnl_percentage))
  print('Total Booked PnL: '+ '{} ({}%)'.format(format_amt(total_booked_amt), total_booked_percentage))
  print('Curr Year Booked PnL: '+ '{} ({}%)'.format(format_amt(cy_booked_amt), cy_booked_percentage))
  print('Prev Year Booked PnL: '+ '{} ({}%)'.format(format_amt(py_booked_amt), py_booked_percentage))
  print('===================')
  print('Est FTT: ',  format_amt(estimate_st))
  print('Est FTT PnL: '+ '{} ({}%)'.format(format_amt(est_st_pnl_amount), est_st_pnl_percentage))

  print('===================')
  print('Deployed: ', format_amt(investment))

  print('Current: ', format_amt(current))

  print('CAGR/XIRR %: '+'{}%'.format(cagr))

In [8]:
# get start and end date
start_date, end_date = get_start_end_date()

# get portfolio and prospects data
mypfs_df = get_mypfs_df()
mypps_df = get_mypps_df()
myinvmt_df = get_myinvmt_df()

# merge above datasets
mypf_df = pd.merge(mypfs_df, mypps_df, on="Symbol")

# seggregate dm and sv portfolio
dm_pf = mypf_df[mypf_df['InPortfolio'] == 'DM']
sv_pf = mypf_df[mypf_df['InPortfolio'] == 'SV']

# build portfolio stock dataframe
dm_stocks = get_stock_ids(dm_pf)
sv_stocks = get_stock_ids(sv_pf)
df_stocks = pd.concat([dm_pf,sv_pf], ignore_index = True)

# arrange common and diff stock features
common_cols = ['Symbol', 'Target', 'Criteria', 'Strategy', 'CumlRnk', 'LatestQtr', 'StarStock', 'Conviction', 'Category', 'InFolio', 'XIRR', 'MBQ']
diff_cols = ['Symbol', 'AvgCost', 'Shares']
df_stocks = arrange_features(df_stocks, common_cols, diff_cols)

# get common features
stock_ids = df_stocks['Symbol'].values
df_common_features = get_common_features(stock_ids, df_stocks)

df_common_features.reset_index(drop=True, inplace=True)
df_common_features.drop(['Date'], axis=1, inplace=True)
# get and print portfolio features
df_portfolio_features = get_portfolio_features(df_common_features)

print_portfolio_stats(df_portfolio_features, myinvmt_df)

df = df_portfolio_features
#plot_pie_chart(df, 'CapType', 'Current')
list_ox40n = list(df[df['MBQ'].str.contains('OX40N', na=False)]['Symbol'].values)

Run date time (IST): 2026-03-24 15:09:28
-------------------
qualified stocks: 86
with latest results: 26
still star stocks: 16

-------------------
Initial Investment:  1.36 C
CY Investment:  1.62 C
Reserve:  1.61 K
Current:  1.29 C
-------------------
Today PnL: 2.48 L (1.96%)
Current PnL: -47.93 L (-29.5%)
CY Booked + Current PnL: -32.04 L (-19.72%)
-------------------
Total profit:  42.88 K
Total loss:  -48.36 L
-------------------
Total Booked + Current PnL: -5.06 L (-3.74%)
Total Booked PnL: 42.87 L (31.64%)
Curr Year Booked PnL: 15.89 L (12.3%)
Prev Year Booked PnL: 26.98 L (19.91%)
===================
Est FTT:  2.48 C
Est FTT PnL: 1.19 C (91.87%)
===================
Deployed:  1.36 C
Current:  1.29 C
CAGR/XIRR %: -2.34%

In [9]:
# top 5 near their targets
cols = ['Symbol', 'Today P/L%', 'Current P/L%', 'FTT%', 'OTT%', 'FTT Amt', 'Current P/L', 'Current', 'FTT', 'Dev%_PE', 'RSI_14','Conviction', 'Spread%',  'CumlRnk', 'RRR Ind', 'CurrAlloc%', 'Gained%', 'Criteria', 'Strategy', 'Category']
df_tmp = df_portfolio_features[~df_portfolio_features['Symbol'].isin(['ENRIN','BLUSPRING','DIGITIDE'])]
df_tmp = df_tmp.sort_values(by = 'FTT Amt', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
50,MASFIN,2.28,-8.14,32.35,21.57,29115.0,-7980.0,90000.0,397.04,-20.96,44.0,H-SC,2.33,167.0,-0.27,0.70,22.75,XR,ATH,FINANCE
77,TTKPRESTIG,-4.00,-43.04,75.72,0.09,43466.0,-43373.0,57404.0,770.00,33.19,34.0,M-SC,19.19,250.0,-1.00,0.44,0.00,OX40N,NTT,DURABLES
2,ABBOTINDIA,5.16,-10.09,31.32,18.07,50363.0,-18055.0,160800.0,35195.00,-23.42,50.0,X-MC,10.60,58.0,-0.36,1.24,5.16,X40,ATH,PHARMA
67,SONACOMS,2.23,-14.24,62.18,39.09,53945.0,-14403.0,86756.0,804.02,-32.08,46.0,M-MC,7.47,193.0,-0.27,0.67,22.73,AR,ATH,AUTO
78,UNITDSPR,4.16,-2.43,23.78,20.77,54325.0,-5694.0,228450.0,1644.00,-13.41,47.0,X-MC,1.62,64.0,-0.10,1.77,4.16,X40N,NTT,BREWERIES

In [10]:
# top 5 today
df_tmp = df_portfolio_features.sort_values(by = 'Today P/L%', ascending=False)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
4,ALKYLAMINE,15.19,-39.20,218.46,93.63,134106.0,-39576.0,61387.0,4546.37,-34.89,54.0,H-SC,25.72,142.0,-0.30,0.48,15.18,SR,ATH,CHEMICALS
60,REPCOHOME,6.95,-22.35,144.44,89.82,321350.0,-64025.0,222480.0,880.00,-61.25,45.0,H-SC,7.83,161.0,-0.20,1.72,9.86,XY24,NTT,FINANCE
66,SIS,6.88,-35.26,87.30,21.26,62755.0,-39148.0,71884.0,528.00,1681.35,43.0,H-SC,14.19,168.0,-0.62,0.56,6.88,OX40N,NTT,MISC
7,ATULAUTO,5.22,-29.03,105.10,45.57,147045.0,-57222.0,139910.0,844.00,3013.51,42.0,M-SC,4.42,248.0,-0.39,1.08,5.88,XY24,NTT,AUTO
2,ABBOTINDIA,5.16,-10.09,31.32,18.07,50363.0,-18055.0,160800.0,35195.00,-23.42,50.0,X-MC,10.60,58.0,-0.36,1.24,5.16,X40,ATH,PHARMA

In [11]:
# bottom 5 today
df_tmp = df_portfolio_features.sort_values(by = 'Today P/L%', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
55,RAJESHEXPO,-4.99,-83.61,510.49,0.07,114784.0,-114692.0,22485.0,518.0,724.49,14.0,L-SC,34.55,268.0,-1.00,0.17,0.00,OX40N,NTT,JEWELLERY
77,TTKPRESTIG,-4.00,-43.04,75.72,0.09,43466.0,-43373.0,57404.0,770.0,33.19,34.0,M-SC,19.19,250.0,-1.00,0.44,0.00,OX40N,NTT,DURABLES
0,5PAISA,-2.22,-48.02,117.22,12.90,133124.0,-104928.0,113568.0,593.0,67.07,30.0,H-SC,13.75,170.0,-0.79,0.88,0.00,OX40N,NTT,FINANCE
14,BOSCH-HCIL,-1.99,-47.03,88.75,-0.01,60087.0,-60101.0,67704.0,2282.0,13747.83,31.0,M-SC,4.69,231.0,-1.00,0.52,0.00,OX40N,BTT,AC
80,VALIANTORG,-1.75,-50.69,253.20,74.15,204251.0,-82937.0,80668.0,838.0,-245.35,51.0,H-SC,28.22,145.0,-0.41,0.62,20.05,XR,NTT,CHEMICALS

In [12]:
# top 5 to exit based on CumlRnk
df_tmp = df_portfolio_features[~df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])]
df_tmp = df_tmp[(df_tmp['Current P/L%'] > -1) & (df_tmp['Current P/L%'] < 1)].sort_values(by = 'CumlRnk', ascending=False)
df_tmp[cols].head()

Empty DataFrame
Columns: [Symbol, Today P/L%, Current P/L%, FTT%, OTT%, FTT Amt, Current P/L, Current, FTT, Dev%_PE, RSI_14, Conviction, Spread%, CumlRnk, RRR Ind, CurrAlloc%, Gained%, Criteria, Strategy, Category]
Index: []

In [13]:
# OX40N stocks to exit
df_tmp = df_portfolio_features[(df_portfolio_features['Symbol'].isin(list_ox40n))].sort_values(by = 'Current P/L%', ascending=False)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
26,FINCABLES,0.77,3.21,101.45,107.91,154586.0,4733.0,152377.0,1641.55,-7.15,44.0,M-SC,8.17,220.0,0.03,1.18,14.64,OX40N,ATH,CABLES
66,SIS,6.88,-35.26,87.30,21.26,62755.0,-39148.0,71884.0,528.00,1681.35,43.0,H-SC,14.19,168.0,-0.62,0.56,6.88,OX40N,NTT,MISC
18,CERA,2.16,-38.78,102.38,23.89,110244.0,-68222.0,107681.0,9475.00,-41.05,45.0,H-SC,18.97,153.0,-0.62,0.83,3.48,OX40N,NTT,CERAMICS
72,TATAELXSI,1.02,-39.86,119.55,32.03,94778.0,-52556.0,79279.0,9161.00,-24.73,37.0,H-SC,20.96,158.0,-0.55,0.61,3.30,OX40N,NTT,IT
77,TTKPRESTIG,-4.00,-43.04,75.72,0.09,43466.0,-43373.0,57404.0,770.00,33.19,34.0,M-SC,19.19,250.0,-1.00,0.44,0.00,OX40N,NTT,DURABLES

In [14]:
# top 5 to book for rotation
df_tmp = df_portfolio_features[(df_portfolio_features['Current P/L%'] > 20) ].sort_values(by = 'CumlRnk', ascending=False)
df_tmp[cols].head()

Empty DataFrame
Columns: [Symbol, Today P/L%, Current P/L%, FTT%, OTT%, FTT Amt, Current P/L, Current, FTT, Dev%_PE, RSI_14, Conviction, Spread%, CumlRnk, RRR Ind, CurrAlloc%, Gained%, Criteria, Strategy, Category]
Index: []

In [15]:
# top 5 to monitor for exit
df_tmp = df_portfolio_features[~df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])]
df_tmp = df_tmp[(df_tmp['Current P/L%'] > 0) ].sort_values(by = 'Dev%_PE', ascending=False)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
26,FINCABLES,0.77,3.21,101.45,107.91,154586.0,4733.0,152377.0,1641.55,-7.15,44.0,M-SC,8.17,220.0,0.03,1.18,14.64,OX40N,ATH,CABLES
1,ABB,2.14,13.22,28.57,45.57,84627.0,34589.0,296208.0,7934.00,-27.27,54.0,H-MC,13.28,125.0,0.41,2.29,31.54,AR,NTT,ELECTRICAL

In [16]:
# top 5 to book for rotation from weak conviction
df_tmp = df_portfolio_features[~df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])]
df_tmp = df_tmp[~df_tmp['Criteria'].isin(['XY25','XY24','X40', 'X40N'])].sort_values(by = 'RRR Ind', ascending=False)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
1,ABB,2.14,13.22,28.57,45.57,84627.0,34589.0,296208.0,7934.00,-27.27,54.0,H-MC,13.28,125.0,0.41,2.29,31.54,AR,NTT,ELECTRICAL
26,FINCABLES,0.77,3.21,101.45,107.91,154586.0,4733.0,152377.0,1641.55,-7.15,44.0,M-SC,8.17,220.0,0.03,1.18,14.64,OX40N,ATH,CABLES
40,INDIAMART,-0.51,-15.75,145.38,106.72,151059.0,-19430.0,103906.0,4810.62,-61.91,30.0,H-SC,11.66,140.0,-0.13,0.80,3.94,AR,ATH,MISC
85,ZYDUSLIFE,3.10,-6.43,44.95,35.63,88144.0,-13481.0,196093.0,1286.17,-18.47,47.0,H-MC,5.41,120.0,-0.15,1.52,9.17,AR,ATH,PHARMA
84,WIPRO,0.70,-22.54,122.40,72.27,160651.0,-38197.0,131251.0,420.00,-30.18,31.0,M-LC,17.83,98.0,-0.24,1.02,0.70,XR,NTT,IT

In [17]:
# top 5 to accumulate based on lowest RSI_14
df_tmp = df_portfolio_features[df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])].sort_values(by = 'RSI_14', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
53,PGHH,0.47,-28.81,85.44,32.01,129869.0,-61520.0,152000.0,17616.87,-51.83,14.0,X-MC,15.84,57.0,-0.47,1.18,0.47,X40,ATH,FMCG
58,RELAXO,1.96,-66.35,352.57,52.31,172237.0,-96308.0,48852.0,1176.00,-64.19,21.0,X-SC,26.56,92.0,-0.56,0.38,1.96,X40N,NTT,FOOTWEAR
12,BATAINDIA,1.71,-58.95,229.33,35.20,121144.0,-75845.0,52825.0,2096.00,-30.69,22.0,X-SC,31.23,91.0,-0.63,0.41,1.71,X40,NTT,FOOTWEAR
38,ICICIPRULI,1.25,-10.99,46.87,30.73,82189.0,-21650.0,175355.0,790.00,-34.90,22.0,X-MC,4.43,78.0,-0.26,1.36,1.25,X40,ATH,INSURANCE
21,DABUR,0.93,-17.64,74.48,43.70,152167.0,-43762.0,204306.0,735.00,-25.19,24.0,X-MC,6.39,70.0,-0.29,1.58,0.93,XY24,BTT,FMCG

In [18]:
# top 5 to accumulate based on Spread and CumlRnk
df_tmp = df_portfolio_features[df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])]
df_tmp = df_tmp[(df_tmp['CumlRnk'] < 100)].sort_values(by = 'Spread%', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
78,UNITDSPR,4.16,-2.43,23.78,20.77,54325.0,-5694.0,228450.0,1644.00,-13.41,47.0,X-MC,1.62,64.0,-0.10,1.77,4.16,X40N,NTT,BREWERIES
65,SIEMENS,0.47,-19.33,55.59,25.51,83452.0,-35975.0,150120.0,4671.50,26.07,40.0,H-LC,2.79,51.0,-0.43,1.16,10.55,AR,ATH,ELECTRICAL
59,RELIANCE,0.39,-9.28,38.12,25.30,69499.0,-18647.0,182316.0,1952.00,-11.57,51.0,X-LC,3.45,21.0,-0.27,1.41,21.72,XY25,BTT,REFINERIES
37,ICICIGI,0.59,-8.24,30.05,19.34,55179.0,-16485.0,183624.0,2252.93,-22.78,27.0,X-MC,3.72,66.0,-0.30,1.42,1.51,X40,ATH,INSURANCE
82,VOLTAS,4.06,1.86,42.55,45.20,83100.0,3558.0,195300.0,1856.00,16.67,35.0,X-MC,3.99,79.0,0.04,1.51,8.78,XY25,NTT,AC

In [19]:
# top 5 to accumulate based on lowest Gained%
df_tmp = df_portfolio_features[df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])].sort_values(by = 'Gained%', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
32,HAVELLS,0.16,-21.06,67.30,32.08,174260.0,-69061.0,258930.0,2062.85,-25.80,32.0,X-MC,8.61,63.0,-0.40,2.00,0.16,X40,ATH,ELECTRICAL
45,ITC,0.24,-23.31,55.25,19.06,144131.0,-79296.0,260870.0,452.00,-57.95,30.0,X-LC,18.66,1.0,-0.55,2.02,0.24,X40,NTT,FMCG
9,BAJAJHFL,0.36,-29.62,130.36,62.13,250512.0,-80877.0,192169.0,181.50,-42.15,27.0,X-MC,20.42,60.0,-0.32,1.49,0.36,X40N,ATH,FINANCE
51,MEDANTA,0.38,-16.74,52.68,27.12,77423.0,-29549.0,146968.0,1486.00,-19.31,25.0,X-SC,12.31,87.0,-0.38,1.14,0.38,XY24,NTT,HEALTHCARE
3,ACC,0.39,-40.25,192.58,74.81,308513.0,-107928.0,160200.0,3906.00,-57.46,26.0,X-SC,17.76,85.0,-0.35,1.24,0.39,XY24,BTT,CEMENT

In [20]:
# top 5 to accumulate based on lowest CurrAlloc%
df_tmp = df_portfolio_features[df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])].sort_values(by = 'CurrAlloc%', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
58,RELAXO,1.96,-66.35,352.57,52.31,172237.0,-96308.0,48852.0,1176.00,-64.19,21.0,X-SC,26.56,92.0,-0.56,0.38,1.96,X40N,NTT,FOOTWEAR
12,BATAINDIA,1.71,-58.95,229.33,35.20,121144.0,-75845.0,52825.0,2096.00,-30.69,22.0,X-SC,31.23,91.0,-0.63,0.41,1.71,X40,NTT,FOOTWEAR
54,QUESS,3.17,-28.12,141.93,73.90,108951.0,-30029.0,76764.0,424.00,-61.43,37.0,X-SC,21.47,80.0,-0.28,0.59,3.17,XY24,NTT,MISC
36,HONAUT,1.67,-28.26,110.90,51.31,153430.0,-54488.0,138350.0,58357.33,-40.38,27.0,X-SC,15.84,90.0,-0.36,1.07,1.67,X40N,ATH,ELECTRICAL
51,MEDANTA,0.38,-16.74,52.68,27.12,77423.0,-29549.0,146968.0,1486.00,-19.31,25.0,X-SC,12.31,87.0,-0.38,1.14,0.38,XY24,NTT,HEALTHCARE

In [21]:
# top 5 to accumulate based on CumlRnk
df_tmp = df_portfolio_features.sort_values(by = 'CumlRnk', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
45,ITC,0.24,-23.31,55.25,19.06,144131.0,-79296.0,260870.0,452.00,-57.95,30.0,X-LC,18.66,1.0,-0.55,2.02,0.24,X40,NTT,FMCG
73,TCS,0.66,-29.56,79.69,26.57,260054.0,-136941.0,326332.0,4311.58,-40.35,30.0,X-LC,17.37,2.0,-0.53,2.53,1.85,X40,ATH,IT
43,INFY,1.70,-12.99,54.28,34.24,147781.0,-40631.0,272257.0,1972.00,-31.42,42.0,X-LC,15.19,3.0,-0.27,2.11,4.70,X40,NTT,IT
75,TMPV,1.93,-29.17,92.83,36.58,233960.0,-103810.0,252031.0,600.00,-85.81,35.0,X-LC,6.70,4.0,-0.44,1.95,1.93,XY24,NTT,AUTO
33,HCLTECH,1.13,-10.84,38.89,23.83,83887.0,-26222.0,215702.0,1908.19,-6.53,45.0,X-LC,11.84,8.0,-0.31,1.67,4.73,X40,ATH,IT

In [22]:
# top 5 for average up
df_tmp = df_portfolio_features[(df_portfolio_features['Dev%_200'] > 5)].sort_values(by = 'CurrAlloc%', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
1,ABB,2.14,13.22,28.57,45.57,84627.0,34589.0,296208.0,7934.0,-27.27,54.0,H-MC,13.28,125.0,0.41,2.29,31.54,AR,NTT,ELECTRICAL

In [23]:
# top 5 RSP
df_tmp = df_portfolio_features.sort_values(by = 'RSP', ascending=False)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
30,HAPPSTMNDS,1.10,-50.45,273.02,84.85,173400.0,-64653.0,63512.0,1480.71,-41.05,54.0,H-SC,26.65,152.0,-0.37,0.49,17.61,AR,ATH,IT
69,SURYODAY,0.50,-28.23,71.43,23.03,91802.0,-50551.0,128520.0,216.00,40.35,47.0,H-SC,6.32,166.0,-0.55,0.99,25.61,XR,NTT,BANKS
33,HCLTECH,1.13,-10.84,38.89,23.83,83887.0,-26222.0,215702.0,1908.19,-6.53,45.0,X-LC,11.84,8.0,-0.31,1.67,4.73,X40,ATH,IT
1,ABB,2.14,13.22,28.57,45.57,84627.0,34589.0,296208.0,7934.00,-27.27,54.0,H-MC,13.28,125.0,0.41,2.29,31.54,AR,NTT,ELECTRICAL
2,ABBOTINDIA,5.16,-10.09,31.32,18.07,50363.0,-18055.0,160800.0,35195.00,-23.42,50.0,X-MC,10.60,58.0,-0.36,1.24,5.16,X40,ATH,PHARMA

In [24]:
# Top N allocation
df_tmp = df_portfolio_features.sort_values(by = 'CurrAlloc%', ascending=False)
top_n_values = [10, 25, 50]

sum_df = pd.DataFrame({
    'Top_N': top_n_values,
    'Sum_Alloc%': [df_tmp['CurrAlloc%'].head(n).sum() for n in top_n_values]
})

sum_df

   Top_N  Sum_Alloc%
0     10       20.77
1     25       45.92
2     50       78.18

In [25]:
# market-cap-wise allocation
df_tmp = df_portfolio_features[cols]
df_tmp.groupby(df_tmp['Conviction'].str[-2:])['CurrAlloc%'].sum().sort_values(ascending=False)

Conviction
SC    44.23
MC    30.17
LC    25.58
Name: CurrAlloc%, dtype: float64

In [26]:
# criteria-wise allocation
df_portfolio_features.groupby('Criteria')['CurrAlloc%'].sum().sort_values(ascending=False)

Criteria
XY24     26.92
X40      25.55
X40N     15.22
AR        9.15
XR        8.32
XY25      7.36
OX40N     6.62
SR        0.84
Name: CurrAlloc%, dtype: float64

In [27]:
# conviction-wise allocation
df_portfolio_features.groupby('Conviction')['CurrAlloc%'].sum().sort_values(ascending=False)

Conviction
X-LC    23.40
X-MC    22.67
H-SC    21.58
X-SC    12.20
M-SC     9.94
H-MC     5.11
M-MC     2.04
H-LC     1.16
M-LC     1.02
L-SC     0.51
L-MC     0.35
Name: CurrAlloc%, dtype: float64

In [28]:
# sector-wise stats
df_tmp = df_portfolio_features.groupby('Category')[['CurrAlloc%', 'Current', 'Current P/L', 'FTT Amt']].sum().sort_values(by=['Current', 'Current P/L'], ascending=False)
df_tmp['Current P/L%'] = round(df_tmp['Current P/L'] * 100 / df_tmp['Current'], 2)
df_tmp['FTT%'] = round(df_tmp['FTT Amt'] * 100 / df_tmp['Current'], 2)
cols = ['CurrAlloc%', 'Current P/L%', 'FTT%']
df_tmp[cols].sort_values(by=['CurrAlloc%'], ascending=False)

               CurrAlloc%  Current P/L%    FTT%
Category
FMCG                15.03        -28.74   74.45
FINANCE             13.09        -27.11   78.91
IT                  11.94        -46.05  120.37
MISC                 6.93        -49.74  114.78
ELECTRICAL           6.52        -14.81   58.77
PAINTS               5.10        -49.57   75.54
INSURANCE            4.70        -11.73   49.97
BANKS                4.56        -30.50   96.74
PHARMA               4.19         -8.51   42.67
AUTO                 3.70        -36.65   90.86
AC                   2.03        -21.50   54.44
HEALTHCARE           1.88        -47.81   86.39
TRAVEL               1.80        -92.07  188.24
BREWERIES            1.77         -2.49   23.78
FOOTWEAR             1.77        -93.96  171.73
DURABLES             1.74        -71.51  113.23
APPARELS             1.74        -19.12   59.76
REALTY               1.48        -16.24   35.34
REFINERIES           1.41        -10.23   38.12
CERAMICS             1.38        -71.69  123.85
CEMENT               1.24        -67.37  192.58
CABLES               1.18          3.11  101.45
CHEMICALS            1.10        -86.24  238.19
ENGINEERING          1.09        -72.60  151.54
JEWELLERY            1.03       -139.70  222.98
ENTERTAINMENT        0.75        -99.69  218.79
TEXTILES             0.49        -46.76   88.61
HOTELS               0.34       -156.02  246.32

In [29]:
# money to be made criteria-wise
df_portfolio_features.groupby('Criteria')['FTT Amt'].agg(['sum', 'count']).sort_values(by='sum', ascending=False)

                sum  count
Criteria
XY24      4121289.0     21
X40       1873148.0     16
XR        1417016.0     12
AR        1387027.0     10
X40N      1335321.0     10
OX40N      934163.0     10
XY25       489640.0      5
SR         311407.0      2

In [30]:
# money to be made conviction-wise
df_portfolio_features.groupby('Conviction')['FTT Amt'].agg(['sum', 'count']).sort_values(by='sum', ascending=False)

                  sum  count
Conviction
H-SC        4004740.0     24
X-MC        1803591.0     15
X-LC        1754327.0     13
M-SC        1634333.0     14
X-SC        1605782.0     10
H-MC         418259.0      3
L-SC         224032.0      2
M-LC         160651.0      1
M-MC         122577.0      2
H-LC          83452.0      1
L-MC          57267.0      1

In [31]:
# money to be made criteria and conviction-wise
df_portfolio_features.groupby(['Conviction', 'Criteria'])['FTT Amt'].agg(['sum', 'count']).sort_values(by='sum', ascending=False)

                           sum  count
Conviction Criteria
H-SC       XY24      1396874.0      6
           AR         997021.0      5
M-SC       XY24       944704.0      6
X-LC       X40        935920.0      7
H-SC       XR         898537.0      7
X-SC       XY24       869011.0      4
X-MC       X40        719078.0      7
           X40N       537964.0      4
X-SC       X40N       518621.0      4
M-SC       OX40N      418478.0      5
H-SC       OX40N      400901.0      4
X-LC       XY24       386625.0      2
H-SC       SR         311407.0      2
X-LC       X40N       278736.0      2
X-MC       XY24       278587.0      2
           XY25       267962.0      2
H-MC       XY24       245488.0      1
X-SC       X40        218150.0      2
M-SC       XR         191313.0      2
H-MC       AR         172771.0      2
M-LC       XR         160651.0      1
X-LC       XY25       153046.0      2
L-SC       OX40N      114784.0      1
           XR         109248.0      1
H-LC       AR          83452.0      1
M-SC       AR          79838.0      1
M-MC       XY25        68632.0      1
L-MC       XR          57267.0      1
M-MC       AR          53945.0      1

In [32]:
# notebook execution time

end_time = time.time()
execution_time = round(end_time - start_time, 0)
print(f"Notebook execution time: {execution_time} seconds")

Notebook execution time: 28.0 seconds