<a href="https://colab.research.google.com/github/ankit-rathi/Quantvesting_v2/blob/main/myStocks_Portfolio_Analysis.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
'''
!pip install pandas==2.2.2 -qq
!pip install pyxirr -qq
!pip install ta -qq
!pip install yfinance==0.2.59 -qq
'''

'\n!pip install pandas==2.2.2 -qq\n!pip install pyxirr -qq\n!pip install ta -qq\n!pip install yfinance==0.2.59 -qq\n'

In [2]:
# import libraries

import numpy as np
import pandas as pd
import datetime
import warnings
warnings.filterwarnings('ignore')
import yfinance as yfin
import ta
import matplotlib.pyplot as plt
import requests

In [3]:
# notebook start time
import time
import datetime
import pytz

start_time = time.time()

# function to print date timestamp
def print_date_time():
  tz_NY = pytz.timezone('Asia/Kolkata')
  datetime_NY = datetime.datetime.now(tz_NY)
  print("Run date time (IST):", datetime_NY.strftime("%Y-%m-%d %H:%M:%S"))

In [4]:
# function to get booked and reserved amount
def get_amt():
  # fetch the JSON data from the URL
  url = "https://raw.githubusercontent.com/ankit-rathi/Tradevesting_v1/main/data/myPortfolioAmts.json"
  response = requests.get(url)
  pf_amts = response.json()  # parse the JSON data

  # extract values from the JSON
  py_booked_amt_dm = pf_amts["py_booked_amt_dm"]
  py_booked_amt_sv = pf_amts["py_booked_amt_sv"]
  cy_booked_amt_dm = pf_amts["cy_booked_amt_dm"]
  cy_booked_amt_sv = pf_amts["cy_booked_amt_sv"]
  reserve_amt_dm = pf_amts["reserve_amt_dm"]
  reserve_amt_sv = pf_amts["reserve_amt_sv"]

  # perform calculations
  py_booked_amt = py_booked_amt_dm + py_booked_amt_sv
  cy_booked_amt = cy_booked_amt_dm + cy_booked_amt_sv
  reserve_amt = reserve_amt_dm + reserve_amt_sv
  total_booked_amt = py_booked_amt + cy_booked_amt

  return total_booked_amt, reserve_amt, cy_booked_amt, py_booked_amt

gen_output = 0

In [5]:
# function to format the amount
def format_amt(number):
    abs_number = abs(number)

    if abs_number >= 1_00_00_000:  # Crores
        formatted_amt = f"{number / 1_00_00_000:.2f} C"
    elif abs_number >= 1_00_000:  # Lakhs
        formatted_amt = f"{number / 1_00_000:.2f} L"
    elif abs_number >= 1_000:  # Thousands
        formatted_amt = f"{number / 1_000:.2f} K"
    else:
        formatted_amt = f"{number:.2f}"

    return formatted_amt

# function to set start and end date
def get_start_end_date():
  start_date = (datetime.date.today() + datetime.timedelta(days=-365)).strftime('%Y-%m-%d')
  end_date = (datetime.date.today() + datetime.timedelta(days=1)).strftime('%Y-%m-%d')
  return start_date, end_date

# function to fetch my portfolio csv
def get_mypfs_df():
  mypfs_df = pd.read_csv('https://raw.githubusercontent.com/ankit-rathi/Tradevesting_v1/main/data/myPortfolioStocks.csv')
  return mypfs_df

# function to fetch my prospects csv
def get_mypps_df():
  mypps_df = pd.read_csv('https://raw.githubusercontent.com/ankit-rathi/Tradevesting_v1/main/data/myProspectsScrips.csv')
  return mypps_df

# function to fetch screener data
def get_myscreen_df():
  myscreen_df = pd.read_csv('https://raw.githubusercontent.com/ankit-rathi/Tradevesting_v1/main/data/myScreenerDB.csv')
  return myscreen_df

# function to fetch momentum data
def get_myinvmt_df():
  myinvmt_df = pd.read_csv('https://raw.githubusercontent.com/ankit-rathi/Tradevesting_v1/main/data/myInvestments.csv')
  return myinvmt_df

# function to get the stock ids
def get_stock_ids(df_pf):
  stock_n100 = df_pf['Symbol'].unique()

  exclude = ['CADILAHC','MMTC', 'MASFIN']

  stock_ids = df_pf[~df_pf['Symbol'].isin(exclude) ]['Symbol'].unique()

  #mypf = mypf[mypf.Forecast.notnull()]
  #stock_ids = mypf['Symbol'].unique()

  #stock_ids.sort()
  return stock_ids

# get features from screener data
def get_screener_features():
  myscreen_df = get_myscreen_df()
  cols = ['Symbol', 'EPS', 'MedPE', 'ROCE%', 'ROE%', 'CapType']
  return myscreen_df[cols]

# get relative strength
def get_relative_strength(stock_list):

    # Dictionary to store stock tickers and their corresponding percentage price change
    stock_changes = {}

    # Loop through each stock and fetch its price data
    for stock in stock_list:
        try:
            # Download the stock data for the given date range
            stock_data = yfin.Ticker(stock + '.NS').history(period='1mo', interval='1d')[map(str.title, ['open', 'close', 'low', 'high', 'volume'])]

            # Calculate the percentage change for the stock
            if len(stock_data) > 0:
                start_price = stock_data['Close'].iloc[0]
                end_price = stock_data['Close'].iloc[-1]
                percent_change = round(((end_price - start_price) / start_price) * 100, 2)
                stock_changes[stock] = percent_change
            else:
                stock_changes[stock] = np.nan  # If no data is available, set to NaN

        except Exception as e:
            print(f"Error fetching data for {stock}: {e}")
            stock_changes[stock] = np.nan

    # Create a DataFrame with stock tickers and their percentage changes
    df = pd.DataFrame(list(stock_changes.items()), columns=['Symbol', 'Percent_Change'])

    # Drop any stocks with missing data (NaN values)
    df = df.dropna()

    # Calculate the percentile rank based on percentage change
    df['RSP'] = round(df['Percent_Change'].rank(pct=True) * 100, 2)
    cols = ['Symbol', 'RSP']
    df = df[cols]
    # Sort by percentile rank (optional)
    df = df.sort_values(by='RSP', ascending=False).reset_index(drop=True)

    return df

In [6]:
# function to get stock technicals
def stock_prec_dev(stock_symbol):
    #stock_symbol = 'ULTRACEMCO.NS'
    short_window = 20
    mid_window = 50
    long_window = 200
    moving_avg = 'SMA'

    start = datetime.datetime(*map(int, start_date.split('-')))
    end = datetime.datetime(*map(int, end_date.split('-')))

    stock_df = yfin.Ticker(stock_symbol + '.NS').history(period='max', interval='1d')[map(str.title, ['open', 'close', 'low', 'high', 'volume'])]

    stock_df['Max'] = round(max(stock_df['Close']),2)
    stock_df = stock_df[(stock_df.index <= end_date) & (stock_df.index >= start_date)]
    stock_df['200_SMA'] = round(stock_df['Close'].rolling(window = 200, min_periods = 1).mean(),0)
    stock_df['Dev%_200'] = round((stock_df['Close'] - stock_df['200_SMA'])*100/stock_df['200_SMA'],2)
    stock_df.dropna(axis = 0, inplace = True) # remove any null rows

    stock_df['20_SMA'] = stock_df['Close'].rolling(window=20).mean()
    stock_df['50_SMA'] = stock_df['Close'].rolling(window=50).mean()
    stock_df['Symbol'] = stock_symbol

    stock_df['Close'] = round(stock_df['Close'],2)
    stock_df['Min'] = round(min(stock_df['Close']),2)
    stock_df['RSI_14'] = ta.momentum.RSIIndicator(close=stock_df['Close'], window=14).rsi()
    stock_df['RSI_14'] = round(stock_df['RSI_14'],0)
    stock_df['Prev_Close'] = stock_df['Close'].shift(1)
    stock_df.drop(['Open', 'Low', 'High', 'Volume'], axis=1, inplace=True)
    stock_df = stock_df.tail(1)

    max_SMA = max(stock_df['20_SMA'].item(), stock_df['50_SMA'].item(), stock_df['200_SMA'].item())
    min_SMA = min(stock_df['20_SMA'].item(), stock_df['50_SMA'].item(), stock_df['200_SMA'].item())
    ABS_Spread = max_SMA - min_SMA
    stock_df['Spread%'] = round((ABS_Spread / stock_df['200_SMA'].item()) * 100,2)

    return stock_df

# function to compute stock attributes
def get_common_features(stock_ids, df_mypf):

  df_prec_dev = pd.DataFrame()
  df_tmp = get_screener_features()
  df_rs = get_relative_strength(stock_ids)

  for stock_id in stock_ids:
      tmp = stock_prec_dev(stock_id)
      tmp = tmp.reset_index()
      df_prec_dev = pd.concat([df_prec_dev, tmp], ignore_index = True)
  df_prec_dev = pd.merge(df_prec_dev, df_mypf, on= 'Symbol')
  df_prec_dev = pd.merge(df_prec_dev, df_tmp, on= 'Symbol', how='left')
  df_prec_dev = pd.merge(df_prec_dev, df_rs, on= 'Symbol', how='left')
  #print(df_prec_dev.columns)
  df_prec_dev['Curr_PE'] = round(df_prec_dev['Close']/df_prec_dev['EPS'],1)
  df_prec_dev['Dev%_PE'] = round((df_prec_dev['Curr_PE'] - df_prec_dev['MedPE'])*100/df_prec_dev['MedPE'],2)
  df_prec_dev['Conviction'] = df_prec_dev['Conviction'] + '-' + df_prec_dev['CapType']
  return df_prec_dev

# function to arrange stock features
def arrange_features(df_stocks, common_cols, diff_cols):
  df_stocks_common = df_stocks[common_cols].drop_duplicates()
  df_stocks_diff = df_stocks[diff_cols]
  df_stocks_diff['Investment'] = df_stocks_diff['AvgCost'] * df_stocks_diff['Shares']
  df_stocks_diff = df_stocks_diff.groupby(['Symbol'])[['Shares', 'Investment']].aggregate(['sum']).reset_index()
  df_stocks_diff.columns = ['Symbol', 'Shares', 'Investment']
  df_stocks_diff['AvgCost'] = round(df_stocks_diff['Investment']/df_stocks_diff['Shares'],2)
  df_stocks = pd.merge(df_stocks_diff, df_stocks_common, on='Symbol')
  return df_stocks

# plot fact distribution across dimension
def plot_pie_chart(df, dimension, fact):
  # grouping the data by category and calculating the sum of fact for each type
  grouped_data = df.groupby(dimension)[fact].sum()

  # sorting the grouped data in descending order
  grouped_data = grouped_data.sort_values(ascending=False)

  # creating a pie chart
  grouped_data.plot.pie(autopct='%1.1f%%', startangle=90, figsize=(6, 6))

  # adding a title and displaying the plot
  plt.title(f'{dimension} {fact} Distribution')
  plt.ylabel('')  # To hide the y-label
  plt.show()

In [7]:
# function to get portfolio features

def get_portfolio_features(df_common_features):

  print_date_time()
  print('-------------------')

  #df_common_features["Target"] = df_common_features["Target"].fillna(df_common_features["Max"])
  df_common_features['NTT'] = np.where(df_common_features['Strategy']== 'NTT', df_common_features["Target"], df_common_features['Max'])
  df_common_features['LTT'] = np.where(df_common_features['Strategy']== 'BTT', df_common_features["Target"], df_common_features['Max'])
  df_common_features['BOL'] = df_common_features['Min']

  tmp_df = df_common_features[df_common_features['Symbol'].isin(mypf_df[mypf_df['InPortfolio'] != 'NA'].Symbol.values)]
  print('qualified stocks: '+str(len(tmp_df['Symbol'].unique())))
  tmp_df1 = tmp_df[tmp_df['LatestQtr'] == 1]
  print('with latest results: '+str(len(tmp_df1['Symbol'].unique())))
  tmp_df1 = tmp_df1[tmp_df1['StarStock'] == 1]
  print('still star stocks: '+str(len(tmp_df1['Symbol'].unique())))
  tmp_df['Investment'] = tmp_df['AvgCost'] * tmp_df['Shares']
  tmp_df['Current'] = round(tmp_df['Close'] * tmp_df['Shares'],0)
  tmp_df['Previous'] = tmp_df['Prev_Close'] * tmp_df['Shares']
  tmp_df['EstimatedST'] = tmp_df['NTT'] * tmp_df['Shares']
  tmp_df['EstimatedLT'] = tmp_df['LTT'] * tmp_df['Shares']
  tmp_df['Current P/L'] = round((tmp_df['Current'] - tmp_df['Investment']),0)
  tmp_df['Today P/L%'] = round((tmp_df['Current'] - tmp_df['Previous'])*100/tmp_df['Previous'],2)
  tmp_df['Current P/L%'] = round((tmp_df['Current'] - tmp_df['Investment'])*100/tmp_df['Investment'],2)
  tmp_df['EstimatedST P/L%'] = round((tmp_df['EstimatedST'] - tmp_df['Investment'])*100/tmp_df['Investment'],2)
  tmp_df['EstimatedLT P/L%'] = round((tmp_df['EstimatedLT'] - tmp_df['Investment'])*100/tmp_df['Investment'],2)
  tmp_df['NTT%'] = round((tmp_df['NTT'] - tmp_df['Close'])*100/tmp_df['Close'],2)
  tmp_df['LTT%'] = round((tmp_df['LTT'] - tmp_df['Close'])*100/tmp_df['Close'],2)
  tmp_df['Gained%'] = round((tmp_df['Close'] - tmp_df['BOL'])*100/tmp_df['BOL'],2)
  investment = round(sum(tmp_df['AvgCost']*tmp_df['Shares']),0)
  current = round(sum(tmp_df['Close']*tmp_df['Shares']),0)
  tmp_df['InitAlloc%'] = round(tmp_df['Investment']*100/investment,2)
  tmp_df['CurrAlloc%'] = round(tmp_df['Current']*100/current,2)
  tmp_df['FTT'] = tmp_df['LTT']
  tmp_df.loc[tmp_df['Strategy'] == 'NTT', 'FTT'] = tmp_df['NTT']
  tmp_df['FTT%'] = tmp_df['LTT%']
  tmp_df.loc[tmp_df['Strategy'] == 'NTT', 'FTT%'] = tmp_df['NTT%']
  tmp_df['FTT Amt'] = round(tmp_df['FTT%'] * tmp_df['Current']/100,0)
  tmp_df['OTT%'] = round((tmp_df['FTT'] - tmp_df['AvgCost'])*100/tmp_df['AvgCost'],2)
  tmp_df['RRR Ind'] = round(tmp_df['Current P/L']/tmp_df['FTT Amt'],2)
  tmp_df['Risk Ind'] = round(tmp_df['Current P/L%']*tmp_df['CurrAlloc%'],0)

  return tmp_df

# function to print portfolio features
def print_portfolio_stats(df_portfolio_features, myinvmt_df):
  from pyxirr import xirr

  total_booked_amt, reserve_amt, cy_booked_amt, py_booked_amt = get_amt()

  dates = myinvmt_df['Date'].values
  dates = np.append(dates, datetime.date.today().strftime('%d-%b-%y'))
  investment = myinvmt_df['Investment'].values
  dates= pd.to_datetime(dates)

  current = round(sum(df_portfolio_features['Close']*df_portfolio_features['Shares']),0) + reserve_amt
  investment_xirr = np.append(investment, current)
  cagr = round(xirr(pd.DataFrame({"dates": dates, "amounts": investment_xirr}))*100,2)

  investment = -sum(investment)
  invested = round(sum(df_portfolio_features['AvgCost']*df_portfolio_features['Shares']),0) + reserve_amt
  previous = round(sum(df_portfolio_features['Prev_Close']*df_portfolio_features['Shares']),0) + reserve_amt
  cy_invested = investment + py_booked_amt

  today_pnl_amount = current-previous
  today_pnl_percentage = round((current-previous)*100/previous,2)

  curr_pnl_amount = current-invested
  curr_pnl_percentage = round((curr_pnl_amount)*100/(cy_invested),2)

  cy_pnl_amount = cy_booked_amt + curr_pnl_amount
  cy_pnl_percentage = round((cy_pnl_amount)*100/cy_invested,2)

  overall_pnl_amount = total_booked_amt + curr_pnl_amount
  overall_pnl_percentage = round((overall_pnl_amount)*100/investment,2)

  estimate_st = round(sum(df_portfolio_features['FTT']*df_portfolio_features['Shares']),0)  + reserve_amt
  est_st_pnl_amount = estimate_st-current
  est_st_pnl_percentage = round((est_st_pnl_amount)*100/current,2)

  estimate_lt = round(sum(df_portfolio_features['LTT']*df_portfolio_features['Shares']),0)  + reserve_amt
  est_lt_pnl_amount = estimate_lt-current
  est_lt_pnl_percentage = round((est_lt_pnl_amount)*100/current,2)

  total_profit = round(sum(df_portfolio_features[df_portfolio_features['Current P/L%'] > 0]['Current']) - sum(df_portfolio_features[df_portfolio_features['Current P/L%'] > 0]['Investment']),0)
  total_loss = round(sum(df_portfolio_features[df_portfolio_features['Current P/L%'] < 0]['Current']) - sum(df_portfolio_features[df_portfolio_features['Current P/L%'] < 0]['Investment']),0)

  cy_booked_percentage = round((cy_booked_amt)*100/current,2)
  py_booked_percentage = round((py_booked_amt)*100/investment,2)
  total_booked_percentage = round((total_booked_amt)*100/investment,2)

  print('-------------------')
  print('Initial Investment: ', format_amt(investment))
  print('CY Investment: ', format_amt(cy_invested))
  print('Reserve: ', format_amt(reserve_amt))
  print('Current: ',  format_amt(current))
  print('-------------------')
  print('Today PnL: '+ '{} ({}%)'.format(format_amt(today_pnl_amount), today_pnl_percentage))
  print('Current PnL: '+ '{} ({}%)'.format(format_amt(curr_pnl_amount), curr_pnl_percentage))
  print('CY Booked + Current PnL: '+ '{} ({}%)'.format(format_amt(cy_pnl_amount), cy_pnl_percentage))
  print('-------------------')
  print('Total profit: ', format_amt(total_profit))
  print('Total loss: ', format_amt(total_loss))
  print('-------------------')
  print('Total Booked + Current PnL: '+ '{} ({}%)'.format(format_amt(overall_pnl_amount), overall_pnl_percentage))
  print('Total Booked PnL: '+ '{} ({}%)'.format(format_amt(total_booked_amt), total_booked_percentage))
  print('Curr Year Booked PnL: '+ '{} ({}%)'.format(format_amt(cy_booked_amt), cy_booked_percentage))
  print('Prev Year Booked PnL: '+ '{} ({}%)'.format(format_amt(py_booked_amt), py_booked_percentage))
  print('===================')
  print('Est FTT: ',  format_amt(estimate_st))
  print('Est FTT PnL: '+ '{} ({}%)'.format(format_amt(est_st_pnl_amount), est_st_pnl_percentage))

  print('===================')
  print('Deployed: ', format_amt(investment))

  print('Current: ', format_amt(current))

  print('CAGR/XIRR %: '+'{}%'.format(cagr))

In [8]:
# get start and end date
start_date, end_date = get_start_end_date()

# get portfolio and prospects data
mypfs_df = get_mypfs_df()
mypps_df = get_mypps_df()
myinvmt_df = get_myinvmt_df()

# merge above datasets
mypf_df = pd.merge(mypfs_df, mypps_df, on="Symbol")

# seggregate dm and sv portfolio
dm_pf = mypf_df[mypf_df['InPortfolio'] == 'DM']
sv_pf = mypf_df[mypf_df['InPortfolio'] == 'SV']

# build portfolio stock dataframe
dm_stocks = get_stock_ids(dm_pf)
sv_stocks = get_stock_ids(sv_pf)
df_stocks = pd.concat([dm_pf,sv_pf], ignore_index = True)

# arrange common and diff stock features
common_cols = ['Symbol', 'Target', 'Criteria', 'Strategy', 'CumlRnk', 'LatestQtr', 'StarStock', 'Conviction', 'Category', 'InFolio', 'XIRR', 'MBQ']
diff_cols = ['Symbol', 'AvgCost', 'Shares']
df_stocks = arrange_features(df_stocks, common_cols, diff_cols)

# get common features
stock_ids = df_stocks['Symbol'].values
df_common_features = get_common_features(stock_ids, df_stocks)

df_common_features.reset_index(drop=True, inplace=True)
df_common_features.drop(['Date'], axis=1, inplace=True)
# get and print portfolio features
df_portfolio_features = get_portfolio_features(df_common_features)

print_portfolio_stats(df_portfolio_features, myinvmt_df)

df = df_portfolio_features
#plot_pie_chart(df, 'CapType', 'Current')
list_ox40n = list(df[df['MBQ'].str.contains('OX40N', na=False)]['Symbol'].values)

Run date time (IST): 2026-08-17 15:45:43
-------------------
qualified stocks: 88
with latest results: 30
still star stocks: 19
-------------------
Initial Investment:  1.46 C
CY Investment:  1.89 C
Reserve:  2.21 L
Current:  1.59 C
-------------------
Today PnL: -60.02 K (-0.38%)
Current PnL: -33.47 L (-17.72%)
CY Booked + Current PnL: -28.83 L (-15.26%)
-------------------
Total profit:  3.80 L
Total loss:  -37.27 L
-------------------
Total Booked + Current PnL: 14.04 L (9.62%)
Total Booked PnL: 47.52 L (32.53%)
Curr Year Booked PnL: 4.65 L (2.92%)
Prev Year Booked PnL: 42.87 L (29.35%)
===================
Est FTT:  2.68 C
Est FTT PnL: 1.09 C (68.35%)
===================
Deployed:  1.46 C
Current:  1.59 C
CAGR/XIRR %: 3.88%

In [9]:
# top 5 near their targets
cols = ['Symbol', 'Today P/L%', 'Current P/L%', 'FTT%', 'OTT%', 'FTT Amt', 'Current P/L', 'Current', 'FTT', 'Dev%_PE', 'RSI_14','Conviction', 'Spread%',  'CumlRnk', 'RRR Ind', 'CurrAlloc%', 'Gained%', 'Criteria', 'Strategy', 'Category']
df_tmp = df_portfolio_features[~df_portfolio_features['Symbol'].isin(['ENRIN','BLUSPRING','DIGITIDE'])]
df_tmp = df_tmp.sort_values(by = 'FTT Amt', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
79,UNITDSPR,0.59,13.49,6.41,20.77,17034.0,31596.0,265740.0,1644.00,0.62,68.0,X-MC,9.99,64.0,1.85,1.69,27.74,X40N,NTT,BREWERIES
78,TTKPRESTIG,-0.64,-23.03,30.05,0.09,23308.0,-23212.0,77565.0,770.00,79.94,41.0,M-SC,10.51,250.0,-1.00,0.49,39.61,OX40N,NTT,DURABLES
54,MASFIN,1.26,-6.52,30.05,21.57,27523.0,-6390.0,91590.0,397.04,-19.60,45.0,H-SC,0.98,167.0,-0.23,0.58,9.17,XR,ATH,FINANCE
52,M&M,-1.11,7.06,10.99,18.82,28318.0,16989.0,257670.0,3762.88,-6.78,56.0,X-LC,4.74,25.0,0.60,1.64,16.88,X40N,ATH,AUTO
68,SIS,-3.07,-4.36,26.79,21.26,28450.0,-4837.0,106195.0,528.00,2531.61,39.0,H-SC,21.33,168.0,-0.17,0.68,57.90,OX40N,NTT,MISC

In [10]:
# top 5 today
df_tmp = df_portfolio_features.sort_values(by = 'Today P/L%', ascending=False)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
25,FINCABLES,5.93,67.29,24.28,107.91,59971.0,99355.0,246999.0,1641.55,50.68,76.0,M-SC,18.95,220.0,1.66,1.57,85.83,OX40N,ATH,CABLES
18,COFFEEDAY,2.95,-49.83,169.63,35.27,96631.0,-56583.0,56966.0,80.00,-61.77,41.0,L-SC,3.93,266.0,-0.59,0.36,40.48,XR,NTT,HOTELS
12,BOSCH-HCIL,2.79,-25.49,34.20,-0.01,32566.0,-32583.0,95222.0,2282.00,19378.26,75.0,M-SC,5.73,231.0,-1.00,0.61,62.08,OX40N,BTT,AC
15,CAMS,1.84,1.71,22.38,24.48,57329.0,4306.0,256162.0,950.00,-2.64,48.0,X-SC,5.62,89.0,0.08,1.63,25.75,X40N,NTT,MISC
57,QUESS,1.81,41.05,23.29,73.90,35081.0,43835.0,150628.0,424.00,-23.97,72.0,X-SC,43.29,80.0,1.25,0.96,107.32,XY24,NTT,MISC

In [11]:
# bottom 5 today
df_tmp = df_portfolio_features.sort_values(by = 'Today P/L%', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
82,VALIANTORG,-4.99,-35.93,171.81,74.15,180095.0,-58783.0,104822.0,838.0,-288.40,58.0,H-SC,6.38,145.0,-0.33,0.67,55.99,XR,NTT,CHEMICALS
24,EASEMYTRIP,-4.22,-66.17,330.67,45.70,197797.0,-116998.0,59817.0,26.4,-38.00,32.0,M-SC,7.07,204.0,-0.59,0.38,4.79,XY24,NTT,TRAVEL
84,VOLTAS,-4.05,-0.88,46.49,45.20,88354.0,-1692.0,190050.0,1856.0,13.41,42.0,X-MC,3.97,79.0,-0.02,1.21,4.16,XY25,NTT,AC
65,SFL,-3.55,-33.58,90.64,26.63,157873.0,-88042.0,174176.0,1287.0,31.97,37.0,M-SC,20.09,242.0,-0.56,1.11,45.36,XY24,NTT,MISC
68,SIS,-3.07,-4.36,26.79,21.26,28450.0,-4837.0,106195.0,528.0,2531.61,39.0,H-SC,21.33,168.0,-0.17,0.68,57.90,OX40N,NTT,MISC

In [12]:
# top 5 to exit based on CumlRnk
df_tmp = df_portfolio_features[~df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])]
df_tmp = df_tmp[(df_tmp['Current P/L%'] > -1) & (df_tmp['Current P/L%'] < 1)].sort_values(by = 'CumlRnk', ascending=False)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
80,UTIAMC,-0.08,-0.02,51.18,51.15,113767.0,-42.0,222288.0,1371.68,-19.39,47.0,M-SC,7.72,229.0,-0.0,1.42,4.12,XY24,ATH,FINANCE

In [13]:
# OX40N stocks to exit
df_tmp = df_portfolio_features[(df_portfolio_features['Symbol'].isin(list_ox40n))].sort_values(by = 'Current P/L%', ascending=False)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
25,FINCABLES,5.93,67.29,24.28,107.91,59971.0,99355.0,246999.0,1641.55,50.68,76.0,M-SC,18.95,220.0,1.66,1.57,85.83,OX40N,ATH,CABLES
68,SIS,-3.07,-4.36,26.79,21.26,28450.0,-4837.0,106195.0,528.00,2531.61,39.0,H-SC,21.33,168.0,-0.17,0.68,57.90,OX40N,NTT,MISC
43,INDIGOPNTS,1.07,-17.53,21.27,0.02,30621.0,-30595.0,143964.0,1408.00,119.31,68.0,M-SC,6.67,222.0,-1.00,0.92,63.34,OX40N,NTT,PAINTS
78,TTKPRESTIG,-0.64,-23.03,30.05,0.09,23308.0,-23212.0,77565.0,770.00,79.94,41.0,M-SC,10.51,250.0,-1.00,0.49,39.61,OX40N,NTT,DURABLES
16,CERA,-1.45,-24.33,63.73,23.89,84825.0,-42802.0,133101.0,9475.00,-26.97,35.0,H-SC,12.95,153.0,-0.50,0.85,29.39,OX40N,NTT,CERAMICS

In [14]:
# top 5 to book for rotation
df_tmp = df_portfolio_features[(df_portfolio_features['Current P/L%'] > 20) ].sort_values(by = 'CumlRnk', ascending=False)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
25,FINCABLES,5.93,67.29,24.28,107.91,59971.0,99355.0,246999.0,1641.55,50.68,76.0,M-SC,18.95,220.0,1.66,1.57,85.83,OX40N,ATH,CABLES
57,QUESS,1.81,41.05,23.29,73.90,35081.0,43835.0,150628.0,424.00,-23.97,72.0,X-SC,43.29,80.0,1.25,0.96,107.32,XY24,NTT,MISC

In [15]:
# top 5 to monitor for exit
df_tmp = df_portfolio_features[~df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])]
df_tmp = df_tmp[(df_tmp['Current P/L%'] > 0) ].sort_values(by = 'Dev%_PE', ascending=False)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
69,STARHEALTH,-0.15,13.06,30.25,47.26,96144.0,36709.0,317832.0,761.00,78.49,51.0,H-SC,16.28,173.0,0.38,2.03,37.42,XY24,NTT,INSURANCE
25,FINCABLES,5.93,67.29,24.28,107.91,59971.0,99355.0,246999.0,1641.55,50.68,76.0,M-SC,18.95,220.0,1.66,1.57,85.83,OX40N,ATH,CABLES
87,ZYDUSLIFE,-0.33,19.32,13.57,35.51,33933.0,40488.0,250062.0,1285.01,4.05,50.0,H-MC,15.45,120.0,1.19,1.59,31.60,AR,ATH,PHARMA

In [16]:
# top 5 to book for rotation from weak conviction
df_tmp = df_portfolio_features[~df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])]
df_tmp = df_tmp[~df_tmp['Criteria'].isin(['XY25','XY24','X40', 'X40N'])].sort_values(by = 'RRR Ind', ascending=False)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
25,FINCABLES,5.93,67.29,24.28,107.91,59971.0,99355.0,246999.0,1641.55,50.68,76.0,M-SC,18.95,220.0,1.66,1.57,85.83,OX40N,ATH,CABLES
87,ZYDUSLIFE,-0.33,19.32,13.57,35.51,33933.0,40488.0,250062.0,1285.01,4.05,50.0,H-MC,15.45,120.0,1.19,1.59,31.60,AR,ATH,PHARMA
3,ALKYLAMINE,-0.16,-18.22,135.45,92.54,111833.0,-18399.0,82564.0,4520.85,-12.41,57.0,H-SC,14.04,142.0,-0.16,0.53,56.78,SR,ATH,CHEMICALS
68,SIS,-3.07,-4.36,26.79,21.26,28450.0,-4837.0,106195.0,528.00,2531.61,39.0,H-SC,21.33,168.0,-0.17,0.68,57.90,OX40N,NTT,MISC
42,INDIAMART,-1.11,-23.94,164.16,100.92,153998.0,-29526.0,93810.0,4675.60,-65.62,40.0,H-SC,13.38,140.0,-0.19,0.60,1.55,AR,ATH,MISC

In [17]:
# top 5 to accumulate based on lowest RSI_14
df_tmp = df_portfolio_features[df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])].sort_values(by = 'RSI_14', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
28,GODREJCP,-0.67,-15.58,57.43,32.90,120980.0,-38881.0,210656.0,1460.97,-12.70,31.0,X-LC,5.72,32.0,-0.32,1.34,2.54,X40N,ATH,FMCG
56,PGHH,-0.73,-37.32,110.60,32.01,148027.0,-79680.0,133840.0,17616.87,-57.60,32.0,X-MC,19.61,57.0,-0.54,0.85,0.00,X40,ATH,FMCG
47,ITC,-1.85,-24.67,65.54,24.70,196137.0,-98015.0,299263.0,452.00,-60.37,35.0,X-LC,10.54,1.0,-0.50,1.91,0.00,X40,NTT,FMCG
34,HDFCBANK,0.28,-10.96,47.19,31.05,123157.0,-32138.0,260982.0,1073.00,-25.96,36.0,X-LC,12.56,26.0,-0.26,1.66,1.30,X40,BTT,BANKS
55,PAGEIND,1.66,-2.56,37.09,33.59,96998.0,-6859.0,261520.0,51217.29,-30.16,36.0,X-MC,8.88,55.0,-0.07,1.67,24.19,X40,ATH,APPARELS

In [18]:
# top 5 to accumulate based on Spread and CumlRnk
df_tmp = df_portfolio_features[df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])]
df_tmp = df_tmp[(df_tmp['CumlRnk'] < 100)].sort_values(by = 'Spread%', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
19,COLPAL,-0.86,-25.43,87.55,39.86,171948.0,-66965.0,196400.0,3683.41,-9.66,37.0,X-MC,1.61,62.0,-0.39,1.25,11.09,XY25,ATH,FMCG
23,DMART,-1.60,-2.62,34.95,31.42,106115.0,-8170.0,303620.0,5391.45,-18.98,48.0,X-LC,2.49,14.0,-0.08,1.94,9.56,X40N,ATH,FMCG
50,KOTAKBANK,0.40,3.21,15.22,18.92,37654.0,7699.0,247401.0,452.46,-9.84,53.0,X-LC,2.63,12.0,0.20,1.58,11.31,X40,ATH,BANKS
26,GILLETTE,-0.40,-10.56,45.04,29.72,102279.0,-26811.0,227085.0,10978.86,-31.19,40.0,X-SC,3.38,83.0,-0.26,1.45,4.36,X40,ATH,FMCG
84,VOLTAS,-4.05,-0.88,46.49,45.20,88354.0,-1692.0,190050.0,1856.00,13.41,42.0,X-MC,3.97,79.0,-0.02,1.21,4.16,XY25,NTT,AC

In [19]:
# top 5 to accumulate based on lowest Gained%
df_tmp = df_portfolio_features[df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])].sort_values(by = 'Gained%', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
47,ITC,-1.85,-24.67,65.54,24.70,196137.0,-98015.0,299263.0,452.00,-60.37,35.0,X-LC,10.54,1.0,-0.50,1.91,0.00,X40,NTT,FMCG
56,PGHH,-0.73,-37.32,110.60,32.01,148027.0,-79680.0,133840.0,17616.87,-57.60,32.0,X-MC,19.61,57.0,-0.54,0.85,0.00,X40,ATH,FMCG
20,DABUR,0.38,-20.47,80.68,43.70,159180.0,-50770.0,197298.0,735.00,-27.78,38.0,X-MC,9.69,70.0,-0.32,1.26,0.40,XY24,BTT,FMCG
34,HDFCBANK,0.28,-10.96,47.19,31.05,123157.0,-32138.0,260982.0,1073.00,-25.96,36.0,X-LC,12.56,26.0,-0.26,1.66,1.30,X40,BTT,BANKS
35,HDFCLIFE,1.33,-6.88,49.43,39.15,115414.0,-17247.0,233490.0,811.41,-30.68,44.0,X-LC,16.62,31.0,-0.15,1.49,1.33,X40,ATH,INSURANCE

In [20]:
# top 5 to accumulate based on lowest CurrAlloc%
df_tmp = df_portfolio_features[df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])].sort_values(by = 'CurrAlloc%', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
10,BATAINDIA,0.32,-51.10,176.48,35.20,111045.0,-65748.0,62922.0,2096.00,-17.55,69.0,X-SC,12.31,91.0,-0.59,0.40,26.42,X40,NTT,FOOTWEAR
61,RELAXO,-1.27,-49.33,200.61,52.31,147541.0,-71614.0,73546.0,1176.00,-46.08,44.0,X-SC,13.30,92.0,-0.49,0.47,64.44,X40N,NTT,FOOTWEAR
56,PGHH,-0.73,-37.32,110.60,32.01,148027.0,-79680.0,133840.0,17616.87,-57.60,32.0,X-MC,19.61,57.0,-0.54,0.85,0.00,X40,ATH,FMCG
57,QUESS,1.81,41.05,23.29,73.90,35081.0,43835.0,150628.0,424.00,-23.97,72.0,X-SC,43.29,80.0,1.25,0.96,107.32,XY24,NTT,MISC
2,ACC,-0.36,-41.08,196.67,74.81,310723.0,-110136.0,157992.0,3906.00,-58.35,39.0,X-SC,11.40,85.0,-0.35,1.01,5.55,XY24,BTT,CEMENT

In [21]:
# top 5 to accumulate based on CumlRnk
df_tmp = df_portfolio_features.sort_values(by = 'CumlRnk', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
47,ITC,-1.85,-24.67,65.54,24.70,196137.0,-98015.0,299263.0,452.00,-60.37,35.0,X-LC,10.54,1.0,-0.50,1.91,0.00,X40,NTT,FMCG
74,TCS,-2.02,-32.09,82.89,24.20,260768.0,-148678.0,314595.0,4230.71,-42.64,49.0,X-LC,14.56,2.0,-0.57,2.01,17.31,X40,ATH,IT
45,INFY,-2.51,-18.85,73.00,40.38,223010.0,-70977.0,305493.0,1972.00,-39.04,51.0,X-LC,15.93,3.0,-0.32,1.95,15.69,X40,NTT,IT
76,TMPV,-1.29,-21.44,81.71,42.75,267108.0,-89209.0,326898.0,600.00,-84.72,41.0,X-LC,4.56,4.0,-0.33,2.08,12.40,XY24,NTT,AUTO
33,HCLTECH,-2.57,-11.38,39.88,23.97,109381.0,-35211.0,274275.0,1853.42,-9.84,57.0,X-LC,11.95,8.0,-0.32,1.75,29.43,X40,ATH,IT

In [22]:
# top 5 for average up
df_tmp = df_portfolio_features[(df_portfolio_features['Dev%_200'] > 5)].sort_values(by = 'CurrAlloc%', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
44,INDUSINDBK,-1.38,-25.39,78.11,32.89,44994.0,-19602.0,57604.0,1800.00,-371.01,52.0,L-MC,13.50,258.0,-0.44,0.37,42.02,XR,NTT,BANKS
30,HAPPSTMNDS,1.57,-46.72,243.61,83.08,166356.0,-59877.0,68288.0,1466.54,-36.58,70.0,H-SC,9.25,152.0,-0.36,0.44,27.91,AR,ATH,IT
61,RELAXO,-1.27,-49.33,200.61,52.31,147541.0,-71614.0,73546.0,1176.00,-46.08,44.0,X-SC,13.30,92.0,-0.49,0.47,64.44,X40N,NTT,FOOTWEAR
3,ALKYLAMINE,-0.16,-18.22,135.45,92.54,111833.0,-18399.0,82564.0,4520.85,-12.41,57.0,H-SC,14.04,142.0,-0.16,0.53,56.78,SR,ATH,CHEMICALS
12,BOSCH-HCIL,2.79,-25.49,34.20,-0.01,32566.0,-32583.0,95222.0,2282.00,19378.26,75.0,M-SC,5.73,231.0,-1.00,0.61,62.08,OX40N,BTT,AC

In [23]:
# top 5 RSP
df_tmp = df_portfolio_features.sort_values(by = 'RSP', ascending=False)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
25,FINCABLES,5.93,67.29,24.28,107.91,59971.0,99355.0,246999.0,1641.55,50.68,76.0,M-SC,18.95,220.0,1.66,1.57,85.83,OX40N,ATH,CABLES
12,BOSCH-HCIL,2.79,-25.49,34.20,-0.01,32566.0,-32583.0,95222.0,2282.00,19378.26,75.0,M-SC,5.73,231.0,-1.00,0.61,62.08,OX40N,BTT,AC
57,QUESS,1.81,41.05,23.29,73.90,35081.0,43835.0,150628.0,424.00,-23.97,72.0,X-SC,43.29,80.0,1.25,0.96,107.32,XY24,NTT,MISC
82,VALIANTORG,-4.99,-35.93,171.81,74.15,180095.0,-58783.0,104822.0,838.00,-288.40,58.0,H-SC,6.38,145.0,-0.33,0.67,55.99,XR,NTT,CHEMICALS
30,HAPPSTMNDS,1.57,-46.72,243.61,83.08,166356.0,-59877.0,68288.0,1466.54,-36.58,70.0,H-SC,9.25,152.0,-0.36,0.44,27.91,AR,ATH,IT

In [24]:
# Top N allocation
df_tmp = df_portfolio_features.sort_values(by = 'CurrAlloc%', ascending=False)
top_n_values = [10, 25, 50]

sum_df = pd.DataFrame({
    'Top_N': top_n_values,
    'Sum_Alloc%': [df_tmp['CurrAlloc%'].head(n).sum() for n in top_n_values]
})

sum_df

   Top_N  Sum_Alloc%
0     10       19.59
1     25       44.71
2     50       76.86

In [25]:
# market-cap-wise allocation
df_tmp = df_portfolio_features[cols]
df_tmp.groupby(df_tmp['Conviction'].str[-2:])['CurrAlloc%'].sum().sort_values(ascending=False)

Conviction
SC    39.46
LC    37.48
MC    23.09
Name: CurrAlloc%, dtype: float64

In [26]:
# criteria-wise allocation
df_portfolio_features.groupby('Criteria')['CurrAlloc%'].sum().sort_values(ascending=False)

Criteria
X40      26.44
XY24     24.82
X40N     18.35
XR        9.03
OX40N     7.25
XY25      7.19
AR        6.09
SR        0.86
Name: CurrAlloc%, dtype: float64

In [27]:
# conviction-wise allocation
df_portfolio_features.groupby('Conviction')['CurrAlloc%'].sum().sort_values(ascending=False)

Conviction
X-LC    35.41
H-SC    19.14
X-MC    18.90
M-SC    11.23
X-SC     8.59
H-MC     2.63
H-LC     1.26
M-MC     1.19
M-LC     0.81
L-SC     0.50
L-MC     0.37
Name: CurrAlloc%, dtype: float64

In [28]:
# sector-wise stats
df_tmp = df_portfolio_features.groupby('Category')[['CurrAlloc%', 'Current', 'Current P/L', 'FTT Amt']].sum().sort_values(by=['Current', 'Current P/L'], ascending=False)
df_tmp['Current P/L%'] = round(df_tmp['Current P/L'] * 100 / df_tmp['Current'], 2)
df_tmp['FTT%'] = round(df_tmp['FTT Amt'] * 100 / df_tmp['Current'], 2)
cols = ['CurrAlloc%', 'Current P/L%', 'FTT%']
df_tmp[cols].sort_values(by=['CurrAlloc%'], ascending=False)

               CurrAlloc%  Current P/L%    FTT%
Category
FMCG                15.31        -24.13   68.76
IT                  11.08        -37.55  105.83
FINANCE             10.61        -15.97   65.93
AUTO                 8.20         -5.15   42.81
MISC                 6.91        -23.69   76.77
BANKS                6.09        -11.77   59.97
PHARMA               5.68          6.98   19.40
INSURANCE            5.67         -4.50   41.45
PAINTS               5.51        -14.02   33.47
ELECTRICAL           4.16         -8.43   46.40
AC                   1.82        -12.01   42.39
REFINERIES           1.71        -11.03   48.33
BREWERIES            1.69         11.89    6.41
APPARELS             1.67         -2.62   37.09
FOOTWEAR             1.66        -69.55  137.53
CABLES               1.57         40.22   24.28
DURABLES             1.47        -67.87  108.71
TRAVEL               1.42       -100.77  201.31
CERAMICS             1.33        -47.42   92.21
CHEMICALS            1.20        -41.19  155.79
ENGINEERING          1.19        -29.38   88.56
CEMENT               1.01        -69.71  196.67
JEWELLERY            0.95       -113.87  188.17
ENTERTAINMENT        0.69        -78.89  185.59
HEALTHCARE           0.68        -70.66  113.50
TEXTILES             0.39        -52.01   95.36
HOTELS               0.36        -99.33  169.63

In [29]:
# money to be made criteria-wise
df_portfolio_features.groupby('Criteria')['FTT Amt'].agg(['sum', 'count']).sort_values(by='sum', ascending=False)

                sum  count
Criteria
XY24      3620555.0     20
X40       2080511.0     18
XR        1381518.0     13
X40N      1202209.0     12
AR        1077997.0      8
OX40N      655801.0     10
XY25       569739.0      5
SR         282604.0      2

In [30]:
# money to be made conviction-wise
df_portfolio_features.groupby('Conviction')['FTT Amt'].agg(['sum', 'count']).sort_values(by='sum', ascending=False)

                  sum  count
Conviction
H-SC        3353043.0     23
X-LC        2503958.0     20
M-SC        1493479.0     15
X-MC        1488897.0     14
X-SC        1230819.0      8
H-MC         284651.0      2
L-SC         212012.0      2
M-LC         165484.0      1
M-MC          58307.0      1
L-MC          44994.0      1
H-LC          35290.0      1

In [31]:
# money to be made criteria and conviction-wise
df_portfolio_features.groupby(['Conviction', 'Criteria'])['FTT Amt'].agg(['sum', 'count']).sort_values(by='sum', ascending=False)

                           sum  count
Conviction Criteria
X-LC       X40       1207898.0      9
H-SC       XY24      1014330.0      5
M-SC       XY24       986468.0      7
H-SC       AR         933221.0      5
           XR         818729.0      7
X-SC       XY24       703662.0      3
X-MC       X40        659289.0      7
X-LC       X40N       540302.0      6
           XY24       444145.0      2
X-MC       X40N       348074.0      3
X-SC       X40N       313833.0      3
H-SC       OX40N      304159.0      4
           SR         282604.0      2
X-MC       XY25       260302.0      2
X-LC       XY25       251130.0      2
H-MC       XY24       250718.0      1
M-SC       OX40N      236261.0      5
X-MC       XY24       221232.0      2
X-SC       X40        213324.0      2
M-SC       XR         195197.0      2
M-LC       XR         165484.0      1
L-SC       OX40N      115381.0      1
           XR          96631.0      1
M-SC       AR          75553.0      1
X-LC       XR          60483.0      1
M-MC       XY25        58307.0      1
L-MC       XR          44994.0      1
H-LC       AR          35290.0      1
H-MC       AR          33933.0      1

In [32]:
# notebook execution time

end_time = time.time()
execution_time = round(end_time - start_time, 0)
print(f"Notebook execution time: {execution_time} seconds")

Notebook execution time: 29.0 seconds