<a href="https://colab.research.google.com/github/ankit-rathi/Quantvesting_v2/blob/main/myStocks_Portfolio_Analysis.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
'''
!pip install pandas==2.2.2 -qq
!pip install pyxirr -qq
!pip install ta -qq
!pip install yfinance==0.2.59 -qq
'''

'\n!pip install pandas==2.2.2 -qq\n!pip install pyxirr -qq\n!pip install ta -qq\n!pip install yfinance==0.2.59 -qq\n'

In [2]:
# import libraries

import numpy as np
import pandas as pd
import datetime
import warnings
warnings.filterwarnings('ignore')
import yfinance as yfin
import ta
import matplotlib.pyplot as plt
import requests

In [3]:
# notebook start time
import time
import datetime
import pytz

start_time = time.time()

# function to print date timestamp
def print_date_time():
  tz_NY = pytz.timezone('Asia/Kolkata')
  datetime_NY = datetime.datetime.now(tz_NY)
  print("Run date time (IST):", datetime_NY.strftime("%Y-%m-%d %H:%M:%S"))

In [4]:
# function to get booked and reserved amount
def get_amt():
  # fetch the JSON data from the URL
  url = "https://raw.githubusercontent.com/ankit-rathi/Tradevesting_v1/main/data/myPortfolioAmts.json"
  response = requests.get(url)
  pf_amts = response.json()  # parse the JSON data

  # extract values from the JSON
  py_booked_amt_dm = pf_amts["py_booked_amt_dm"]
  py_booked_amt_sv = pf_amts["py_booked_amt_sv"]
  cy_booked_amt_dm = pf_amts["cy_booked_amt_dm"]
  cy_booked_amt_sv = pf_amts["cy_booked_amt_sv"]
  reserve_amt_dm = pf_amts["reserve_amt_dm"]
  reserve_amt_sv = pf_amts["reserve_amt_sv"]

  # perform calculations
  py_booked_amt = py_booked_amt_dm + py_booked_amt_sv
  cy_booked_amt = cy_booked_amt_dm + cy_booked_amt_sv
  reserve_amt = reserve_amt_dm + reserve_amt_sv
  total_booked_amt = py_booked_amt + cy_booked_amt

  return total_booked_amt, reserve_amt, cy_booked_amt, py_booked_amt

gen_output = 0

In [5]:
# function to format the amount
def format_amt(number):
    abs_number = abs(number)

    if abs_number >= 1_00_00_000:  # Crores
        formatted_amt = f"{number / 1_00_00_000:.2f} C"
    elif abs_number >= 1_00_000:  # Lakhs
        formatted_amt = f"{number / 1_00_000:.2f} L"
    elif abs_number >= 1_000:  # Thousands
        formatted_amt = f"{number / 1_000:.2f} K"
    else:
        formatted_amt = f"{number:.2f}"

    return formatted_amt

# function to set start and end date
def get_start_end_date():
  start_date = (datetime.date.today() + datetime.timedelta(days=-365)).strftime('%Y-%m-%d')
  end_date = (datetime.date.today() + datetime.timedelta(days=1)).strftime('%Y-%m-%d')
  return start_date, end_date

# function to fetch my portfolio csv
def get_mypfs_df():
  mypfs_df = pd.read_csv('https://raw.githubusercontent.com/ankit-rathi/Tradevesting_v1/main/data/myPortfolioStocks.csv')
  return mypfs_df

# function to fetch my prospects csv
def get_mypps_df():
  mypps_df = pd.read_csv('https://raw.githubusercontent.com/ankit-rathi/Tradevesting_v1/main/data/myProspectsScrips.csv')
  return mypps_df

# function to fetch screener data
def get_myscreen_df():
  myscreen_df = pd.read_csv('https://raw.githubusercontent.com/ankit-rathi/Tradevesting_v1/main/data/myScreenerDB.csv')
  return myscreen_df

# function to fetch momentum data
def get_myinvmt_df():
  myinvmt_df = pd.read_csv('https://raw.githubusercontent.com/ankit-rathi/Tradevesting_v1/main/data/myInvestments.csv')
  return myinvmt_df

# function to get the stock ids
def get_stock_ids(df_pf):
  stock_n100 = df_pf['Symbol'].unique()

  exclude = ['CADILAHC','MMTC', 'MASFIN']

  stock_ids = df_pf[~df_pf['Symbol'].isin(exclude) ]['Symbol'].unique()

  #mypf = mypf[mypf.Forecast.notnull()]
  #stock_ids = mypf['Symbol'].unique()

  #stock_ids.sort()
  return stock_ids

# get features from screener data
def get_screener_features():
  myscreen_df = get_myscreen_df()
  cols = ['Symbol', 'EPS', 'MedPE', 'ROCE%', 'ROE%', 'CapType']
  return myscreen_df[cols]

# get relative strength
def get_relative_strength(stock_list):

    # Dictionary to store stock tickers and their corresponding percentage price change
    stock_changes = {}

    # Loop through each stock and fetch its price data
    for stock in stock_list:
        try:
            # Download the stock data for the given date range
            stock_data = yfin.Ticker(stock + '.NS').history(period='1mo', interval='1d')[map(str.title, ['open', 'close', 'low', 'high', 'volume'])]

            # Calculate the percentage change for the stock
            if len(stock_data) > 0:
                start_price = stock_data['Close'].iloc[0]
                end_price = stock_data['Close'].iloc[-1]
                percent_change = round(((end_price - start_price) / start_price) * 100, 2)
                stock_changes[stock] = percent_change
            else:
                stock_changes[stock] = np.nan  # If no data is available, set to NaN

        except Exception as e:
            print(f"Error fetching data for {stock}: {e}")
            stock_changes[stock] = np.nan

    # Create a DataFrame with stock tickers and their percentage changes
    df = pd.DataFrame(list(stock_changes.items()), columns=['Symbol', 'Percent_Change'])

    # Drop any stocks with missing data (NaN values)
    df = df.dropna()

    # Calculate the percentile rank based on percentage change
    df['RSP'] = round(df['Percent_Change'].rank(pct=True) * 100, 2)
    cols = ['Symbol', 'RSP']
    df = df[cols]
    # Sort by percentile rank (optional)
    df = df.sort_values(by='RSP', ascending=False).reset_index(drop=True)

    return df

In [6]:
# function to get stock technicals
def stock_prec_dev(stock_symbol):
    #stock_symbol = 'ULTRACEMCO.NS'
    short_window = 20
    mid_window = 50
    long_window = 200
    moving_avg = 'SMA'

    start = datetime.datetime(*map(int, start_date.split('-')))
    end = datetime.datetime(*map(int, end_date.split('-')))

    stock_df = yfin.Ticker(stock_symbol + '.NS').history(period='max', interval='1d')[map(str.title, ['open', 'close', 'low', 'high', 'volume'])]

    stock_df['Max'] = round(max(stock_df['Close']),2)
    stock_df = stock_df[(stock_df.index <= end_date) & (stock_df.index >= start_date)]
    stock_df['200_SMA'] = round(stock_df['Close'].rolling(window = 200, min_periods = 1).mean(),0)
    stock_df['Dev%_200'] = round((stock_df['Close'] - stock_df['200_SMA'])*100/stock_df['200_SMA'],2)
    stock_df.dropna(axis = 0, inplace = True) # remove any null rows

    stock_df['20_SMA'] = stock_df['Close'].rolling(window=20).mean()
    stock_df['50_SMA'] = stock_df['Close'].rolling(window=50).mean()
    stock_df['Symbol'] = stock_symbol

    stock_df['Close'] = round(stock_df['Close'],2)
    stock_df['Min'] = round(min(stock_df['Close']),2)
    stock_df['RSI_14'] = ta.momentum.RSIIndicator(close=stock_df['Close'], window=14).rsi()
    stock_df['RSI_14'] = round(stock_df['RSI_14'],0)
    stock_df['Prev_Close'] = stock_df['Close'].shift(1)
    stock_df.drop(['Open', 'Low', 'High', 'Volume'], axis=1, inplace=True)
    stock_df = stock_df.tail(1)

    max_SMA = max(stock_df['20_SMA'].item(), stock_df['50_SMA'].item(), stock_df['200_SMA'].item())
    min_SMA = min(stock_df['20_SMA'].item(), stock_df['50_SMA'].item(), stock_df['200_SMA'].item())
    ABS_Spread = max_SMA - min_SMA
    stock_df['Spread%'] = round((ABS_Spread / stock_df['200_SMA'].item()) * 100,2)

    return stock_df

# function to compute stock attributes
def get_common_features(stock_ids, df_mypf):

  df_prec_dev = pd.DataFrame()
  df_tmp = get_screener_features()
  df_rs = get_relative_strength(stock_ids)

  for stock_id in stock_ids:
      tmp = stock_prec_dev(stock_id)
      tmp = tmp.reset_index()
      df_prec_dev = pd.concat([df_prec_dev, tmp], ignore_index = True)
  df_prec_dev = pd.merge(df_prec_dev, df_mypf, on= 'Symbol')
  df_prec_dev = pd.merge(df_prec_dev, df_tmp, on= 'Symbol', how='left')
  df_prec_dev = pd.merge(df_prec_dev, df_rs, on= 'Symbol', how='left')
  #print(df_prec_dev.columns)
  df_prec_dev['Curr_PE'] = round(df_prec_dev['Close']/df_prec_dev['EPS'],1)
  df_prec_dev['Dev%_PE'] = round((df_prec_dev['Curr_PE'] - df_prec_dev['MedPE'])*100/df_prec_dev['MedPE'],2)
  df_prec_dev['Conviction'] = df_prec_dev['Conviction'] + '-' + df_prec_dev['CapType']
  return df_prec_dev

# function to arrange stock features
def arrange_features(df_stocks, common_cols, diff_cols):
  df_stocks_common = df_stocks[common_cols].drop_duplicates()
  df_stocks_diff = df_stocks[diff_cols]
  df_stocks_diff['Investment'] = df_stocks_diff['AvgCost'] * df_stocks_diff['Shares']
  df_stocks_diff = df_stocks_diff.groupby(['Symbol'])[['Shares', 'Investment']].aggregate(['sum']).reset_index()
  df_stocks_diff.columns = ['Symbol', 'Shares', 'Investment']
  df_stocks_diff['AvgCost'] = round(df_stocks_diff['Investment']/df_stocks_diff['Shares'],2)
  df_stocks = pd.merge(df_stocks_diff, df_stocks_common, on='Symbol')
  return df_stocks

# plot fact distribution across dimension
def plot_pie_chart(df, dimension, fact):
  # grouping the data by category and calculating the sum of fact for each type
  grouped_data = df.groupby(dimension)[fact].sum()

  # sorting the grouped data in descending order
  grouped_data = grouped_data.sort_values(ascending=False)

  # creating a pie chart
  grouped_data.plot.pie(autopct='%1.1f%%', startangle=90, figsize=(6, 6))

  # adding a title and displaying the plot
  plt.title(f'{dimension} {fact} Distribution')
  plt.ylabel('')  # To hide the y-label
  plt.show()

In [7]:
# function to get portfolio features

def get_portfolio_features(df_common_features):

  print_date_time()
  print('-------------------')

  #df_common_features["Target"] = df_common_features["Target"].fillna(df_common_features["Max"])
  df_common_features['NTT'] = np.where(df_common_features['Strategy']== 'NTT', df_common_features["Target"], df_common_features['Max'])
  df_common_features['LTT'] = np.where(df_common_features['Strategy']== 'BTT', df_common_features["Target"], df_common_features['Max'])
  df_common_features['BOL'] = df_common_features['Min']

  tmp_df = df_common_features[df_common_features['Symbol'].isin(mypf_df[mypf_df['InPortfolio'] != 'NA'].Symbol.values)]
  print('qualified stocks: '+str(len(tmp_df['Symbol'].unique())))
  tmp_df1 = tmp_df[tmp_df['LatestQtr'] == 1]
  print('with latest results: '+str(len(tmp_df1['Symbol'].unique())))
  tmp_df1 = tmp_df1[tmp_df1['StarStock'] == 1]
  print('still star stocks: '+str(len(tmp_df1['Symbol'].unique())))
  tmp_df['Investment'] = tmp_df['AvgCost'] * tmp_df['Shares']
  tmp_df['Current'] = round(tmp_df['Close'] * tmp_df['Shares'],0)
  tmp_df['Previous'] = tmp_df['Prev_Close'] * tmp_df['Shares']
  tmp_df['EstimatedST'] = tmp_df['NTT'] * tmp_df['Shares']
  tmp_df['EstimatedLT'] = tmp_df['LTT'] * tmp_df['Shares']
  tmp_df['Current P/L'] = round((tmp_df['Current'] - tmp_df['Investment']),0)
  tmp_df['Today P/L%'] = round((tmp_df['Current'] - tmp_df['Previous'])*100/tmp_df['Previous'],2)
  tmp_df['Current P/L%'] = round((tmp_df['Current'] - tmp_df['Investment'])*100/tmp_df['Investment'],2)
  tmp_df['EstimatedST P/L%'] = round((tmp_df['EstimatedST'] - tmp_df['Investment'])*100/tmp_df['Investment'],2)
  tmp_df['EstimatedLT P/L%'] = round((tmp_df['EstimatedLT'] - tmp_df['Investment'])*100/tmp_df['Investment'],2)
  tmp_df['NTT%'] = round((tmp_df['NTT'] - tmp_df['Close'])*100/tmp_df['Close'],2)
  tmp_df['LTT%'] = round((tmp_df['LTT'] - tmp_df['Close'])*100/tmp_df['Close'],2)
  tmp_df['Gained%'] = round((tmp_df['Close'] - tmp_df['BOL'])*100/tmp_df['BOL'],2)
  investment = round(sum(tmp_df['AvgCost']*tmp_df['Shares']),0)
  current = round(sum(tmp_df['Close']*tmp_df['Shares']),0)
  tmp_df['InitAlloc%'] = round(tmp_df['Investment']*100/investment,2)
  tmp_df['CurrAlloc%'] = round(tmp_df['Current']*100/current,2)
  tmp_df['FTT'] = tmp_df['LTT']
  tmp_df.loc[tmp_df['Strategy'] == 'NTT', 'FTT'] = tmp_df['NTT']
  tmp_df['FTT%'] = tmp_df['LTT%']
  tmp_df.loc[tmp_df['Strategy'] == 'NTT', 'FTT%'] = tmp_df['NTT%']
  tmp_df['FTT Amt'] = round(tmp_df['FTT%'] * tmp_df['Current']/100,0)
  tmp_df['OTT%'] = round((tmp_df['FTT'] - tmp_df['AvgCost'])*100/tmp_df['AvgCost'],2)
  tmp_df['RRR Ind'] = round(tmp_df['Current P/L']/tmp_df['FTT Amt'],2)
  tmp_df['Risk Ind'] = round(tmp_df['Current P/L%']*tmp_df['CurrAlloc%'],0)

  return tmp_df

# function to print portfolio features
def print_portfolio_stats(df_portfolio_features, myinvmt_df):
  from pyxirr import xirr

  total_booked_amt, reserve_amt, cy_booked_amt, py_booked_amt = get_amt()

  dates = myinvmt_df['Date'].values
  dates = np.append(dates, datetime.date.today().strftime('%d-%b-%y'))
  investment = myinvmt_df['Investment'].values
  dates= pd.to_datetime(dates)

  current = round(sum(df_portfolio_features['Close']*df_portfolio_features['Shares']),0) + reserve_amt
  investment_xirr = np.append(investment, current)
  cagr = round(xirr(pd.DataFrame({"dates": dates, "amounts": investment_xirr}))*100,2)

  investment = -sum(investment)
  invested = round(sum(df_portfolio_features['AvgCost']*df_portfolio_features['Shares']),0) + reserve_amt
  previous = round(sum(df_portfolio_features['Prev_Close']*df_portfolio_features['Shares']),0) + reserve_amt
  cy_invested = investment + py_booked_amt

  today_pnl_amount = current-previous
  today_pnl_percentage = round((current-previous)*100/previous,2)

  curr_pnl_amount = current-invested
  curr_pnl_percentage = round((curr_pnl_amount)*100/(cy_invested),2)

  cy_pnl_amount = cy_booked_amt + curr_pnl_amount
  cy_pnl_percentage = round((cy_pnl_amount)*100/cy_invested,2)

  overall_pnl_amount = total_booked_amt + curr_pnl_amount
  overall_pnl_percentage = round((overall_pnl_amount)*100/investment,2)

  estimate_st = round(sum(df_portfolio_features['FTT']*df_portfolio_features['Shares']),0)  + reserve_amt
  est_st_pnl_amount = estimate_st-current
  est_st_pnl_percentage = round((est_st_pnl_amount)*100/current,2)

  estimate_lt = round(sum(df_portfolio_features['LTT']*df_portfolio_features['Shares']),0)  + reserve_amt
  est_lt_pnl_amount = estimate_lt-current
  est_lt_pnl_percentage = round((est_lt_pnl_amount)*100/current,2)

  total_profit = round(sum(df_portfolio_features[df_portfolio_features['Current P/L%'] > 0]['Current']) - sum(df_portfolio_features[df_portfolio_features['Current P/L%'] > 0]['Investment']),0)
  total_loss = round(sum(df_portfolio_features[df_portfolio_features['Current P/L%'] < 0]['Current']) - sum(df_portfolio_features[df_portfolio_features['Current P/L%'] < 0]['Investment']),0)

  cy_booked_percentage = round((cy_booked_amt)*100/current,2)
  py_booked_percentage = round((py_booked_amt)*100/investment,2)
  total_booked_percentage = round((total_booked_amt)*100/investment,2)

  print('-------------------')
  print('Initial Investment: ', format_amt(investment))
  print('CY Investment: ', format_amt(cy_invested))
  print('Reserve: ', format_amt(reserve_amt))
  print('Current: ',  format_amt(current))
  print('-------------------')
  print('Today PnL: '+ '{} ({}%)'.format(format_amt(today_pnl_amount), today_pnl_percentage))
  print('Current PnL: '+ '{} ({}%)'.format(format_amt(curr_pnl_amount), curr_pnl_percentage))
  print('CY Booked + Current PnL: '+ '{} ({}%)'.format(format_amt(cy_pnl_amount), cy_pnl_percentage))
  print('-------------------')
  print('Total profit: ', format_amt(total_profit))
  print('Total loss: ', format_amt(total_loss))
  print('-------------------')
  print('Total Booked + Current PnL: '+ '{} ({}%)'.format(format_amt(overall_pnl_amount), overall_pnl_percentage))
  print('Total Booked PnL: '+ '{} ({}%)'.format(format_amt(total_booked_amt), total_booked_percentage))
  print('Curr Year Booked PnL: '+ '{} ({}%)'.format(format_amt(cy_booked_amt), cy_booked_percentage))
  print('Prev Year Booked PnL: '+ '{} ({}%)'.format(format_amt(py_booked_amt), py_booked_percentage))
  print('===================')
  print('Est FTT: ',  format_amt(estimate_st))
  print('Est FTT PnL: '+ '{} ({}%)'.format(format_amt(est_st_pnl_amount), est_st_pnl_percentage))

  print('===================')
  print('Deployed: ', format_amt(investment))

  print('Current: ', format_amt(current))

  print('CAGR/XIRR %: '+'{}%'.format(cagr))

In [8]:
# get start and end date
start_date, end_date = get_start_end_date()

# get portfolio and prospects data
mypfs_df = get_mypfs_df()
mypps_df = get_mypps_df()
myinvmt_df = get_myinvmt_df()

# merge above datasets
mypf_df = pd.merge(mypfs_df, mypps_df, on="Symbol")

# seggregate dm and sv portfolio
dm_pf = mypf_df[mypf_df['InPortfolio'] == 'DM']
sv_pf = mypf_df[mypf_df['InPortfolio'] == 'SV']

# build portfolio stock dataframe
dm_stocks = get_stock_ids(dm_pf)
sv_stocks = get_stock_ids(sv_pf)
df_stocks = pd.concat([dm_pf,sv_pf], ignore_index = True)

# arrange common and diff stock features
common_cols = ['Symbol', 'Target', 'Criteria', 'Strategy', 'CumlRnk', 'LatestQtr', 'StarStock', 'Conviction', 'Category', 'InFolio', 'XIRR', 'MBQ']
diff_cols = ['Symbol', 'AvgCost', 'Shares']
df_stocks = arrange_features(df_stocks, common_cols, diff_cols)

# get common features
stock_ids = df_stocks['Symbol'].values
df_common_features = get_common_features(stock_ids, df_stocks)

df_common_features.reset_index(drop=True, inplace=True)
df_common_features.drop(['Date'], axis=1, inplace=True)
# get and print portfolio features
df_portfolio_features = get_portfolio_features(df_common_features)

print_portfolio_stats(df_portfolio_features, myinvmt_df)

df = df_portfolio_features
#plot_pie_chart(df, 'CapType', 'Current')
list_ox40n = list(df[df['MBQ'].str.contains('OX40N', na=False)]['Symbol'].values)

Run date time (IST): 2026-04-23 12:31:15
-------------------
qualified stocks: 90
with latest results: 28
still star stocks: 17
-------------------
Initial Investment:  1.38 C
CY Investment:  1.80 C
Reserve:  1.84 K
Current:  1.47 C
-------------------
Today PnL: -71.64 K (-0.49%)
Current PnL: -33.19 L (-18.4%)
CY Booked + Current PnL: -32.23 L (-17.87%)
-------------------
Total profit:  2.13 L
Total loss:  -35.31 L
-------------------
Total Booked + Current PnL: 10.64 L (7.74%)
Total Booked PnL: 43.83 L (31.88%)
Curr Year Booked PnL: 96.00 K (0.65%)
Prev Year Booked PnL: 42.87 L (31.18%)
===================
Est FTT:  2.52 C
Est FTT PnL: 1.05 C (71.71%)
===================
Deployed:  1.38 C
Current:  1.47 C
CAGR/XIRR %: 3.19%

In [9]:
# top 5 near their targets
cols = ['Symbol', 'Today P/L%', 'Current P/L%', 'FTT%', 'OTT%', 'FTT Amt', 'Current P/L', 'Current', 'FTT', 'Dev%_PE', 'RSI_14','Conviction', 'Spread%',  'CumlRnk', 'RRR Ind', 'CurrAlloc%', 'Gained%', 'Criteria', 'Strategy', 'Category']
df_tmp = df_portfolio_features[~df_portfolio_features['Symbol'].isin(['ENRIN','BLUSPRING','DIGITIDE'])]
df_tmp = df_tmp.sort_values(by = 'FTT Amt', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
1,ABB,0.04,39.26,4.53,45.57,16504.0,102701.0,364320.0,7934.00,-10.49,82.0,H-MC,20.49,125.0,6.22,2.48,61.78,AR,NTT,ELECTRICAL
54,MASFIN,-0.67,-1.75,23.73,21.57,22845.0,-1710.0,96270.0,397.04,-15.09,59.0,H-SC,2.65,167.0,-0.07,0.66,24.40,XR,ATH,FINANCE
81,TTKPRESTIG,2.83,-32.41,48.08,0.09,32752.0,-32657.0,68120.0,770.00,58.16,62.0,M-SC,22.19,250.0,-1.00,0.46,21.30,OX40N,NTT,DURABLES
53,MARUTI,-1.09,-2.40,31.09,27.95,32809.0,-2592.0,105528.0,17292.00,-19.23,47.0,X-LC,11.93,33.0,-0.08,0.72,13.98,XR,ATH,AUTO
18,CIPLA,4.09,4.55,29.27,35.15,37291.0,5544.0,127403.0,1663.60,-19.25,60.0,X-LC,15.66,18.0,0.15,0.87,7.93,X40N,ATH,PHARMA

In [10]:
# top 5 today
df_tmp = df_portfolio_features.sort_values(by = 'Today P/L%', ascending=False)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
60,RAJOOENG,7.19,-29.17,97.11,39.61,70502.0,-29900.0,72600.0,143.10,-52.19,70.0,H-SC,26.41,136.0,-0.42,0.49,55.53,AR,ATH,MISC
59,RAJESHEXPO,4.99,-75.14,302.52,0.07,103168.0,-103074.0,34103.0,518.00,1150.00,62.0,L-SC,39.12,268.0,-1.00,0.23,60.10,OX40N,NTT,JEWELLERY
18,CIPLA,4.09,4.55,29.27,35.15,37291.0,5544.0,127403.0,1663.60,-19.25,60.0,X-LC,15.66,18.0,0.15,0.87,7.93,X40N,ATH,PHARMA
49,JIOFIN,3.66,-17.95,56.53,28.43,138367.0,-53559.0,244768.0,387.00,-19.24,55.0,X-LC,18.33,34.0,-0.39,1.67,10.33,XY24,BTT,FINANCE
4,ALKYLAMINE,2.90,-34.62,196.18,93.63,129489.0,-34958.0,66005.0,4546.37,-30.06,65.0,H-SC,22.19,142.0,-0.27,0.45,24.63,SR,ATH,CHEMICALS

In [11]:
# bottom 5 today
df_tmp = df_portfolio_features.sort_values(by = 'Today P/L%', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
33,HAVELLS,-6.04,-18.87,62.79,32.08,167092.0,-61879.0,266112.0,2062.85,-23.66,46.0,X-MC,12.43,63.0,-0.37,1.81,7.34,X40,ATH,ELECTRICAL
23,DIXON,-3.16,-20.51,73.50,37.92,152379.0,-53480.0,207318.0,18931.72,-66.19,53.0,X-MC,24.39,54.0,-0.35,1.41,12.80,X40N,ATH,IT
76,TATAELXSI,-2.99,-39.01,116.47,32.03,93651.0,-51427.0,80408.0,9161.00,-23.72,42.0,H-SC,17.69,158.0,-0.55,0.55,6.42,OX40N,NTT,IT
84,VALIANTORG,-2.50,-46.02,222.62,74.15,196607.0,-75290.0,88315.0,838.00,-259.08,53.0,H-SC,18.07,145.0,-0.38,0.60,31.43,XR,NTT,CHEMICALS
86,VOLTAS,-2.47,13.04,28.44,45.20,61644.0,25008.0,216750.0,1856.00,29.40,58.0,X-MC,6.10,79.0,0.41,1.48,20.73,XY25,NTT,AC

In [12]:
# top 5 to exit based on CumlRnk
df_tmp = df_portfolio_features[~df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])]
df_tmp = df_tmp[(df_tmp['Current P/L%'] > -1) & (df_tmp['Current P/L%'] < 1)].sort_values(by = 'CumlRnk', ascending=False)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
71,SONACOMS,-1.61,0.16,38.86,39.09,39375.0,166.0,101325.0,804.02,-20.60,62.0,M-MC,11.93,193.0,0.00,0.69,43.34,AR,ATH,AUTO
72,STARHEALTH,1.57,0.01,47.25,47.26,132838.0,16.0,281139.0,761.00,57.86,73.0,H-SC,3.62,173.0,0.00,1.91,45.60,XY24,NTT,INSURANCE
89,ZYDUSLIFE,1.41,-0.56,36.39,35.63,75838.0,-1171.0,208403.0,1286.17,-13.51,62.0,H-MC,4.37,120.0,-0.02,1.42,10.95,AR,ATH,PHARMA

In [13]:
# OX40N stocks to exit
df_tmp = df_portfolio_features[(df_portfolio_features['Symbol'].isin(list_ox40n))].sort_values(by = 'Current P/L%', ascending=False)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
26,FINCABLES,0.74,24.50,66.99,107.91,123142.0,36177.0,183821.0,1641.55,12.13,72.0,M-SC,4.85,220.0,0.29,1.25,38.29,OX40N,ATH,CABLES
70,SIS,-1.17,-23.41,58.32,21.26,49596.0,-25990.0,85042.0,528.00,2007.25,71.0,H-SC,8.33,168.0,-0.52,0.58,26.45,OX40N,NTT,MISC
17,CERA,-0.59,-28.65,73.64,23.89,92421.0,-50399.0,125504.0,9475.00,-31.26,70.0,H-SC,12.97,153.0,-0.55,0.85,20.61,OX40N,NTT,CERAMICS
81,TTKPRESTIG,2.83,-32.41,48.08,0.09,32752.0,-32657.0,68120.0,770.00,58.16,62.0,M-SC,22.19,250.0,-1.00,0.46,21.30,OX40N,NTT,DURABLES
51,KANSAINER,-1.77,-33.11,69.64,13.47,125622.0,-89280.0,180387.0,340.00,-42.48,59.0,H-SC,18.59,162.0,-0.71,1.23,26.00,XY24,NTT,PAINTS

In [14]:
# top 5 to book for rotation
df_tmp = df_portfolio_features[(df_portfolio_features['Current P/L%'] > 20) ].sort_values(by = 'CumlRnk', ascending=False)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
26,FINCABLES,0.74,24.50,66.99,107.91,123142.0,36177.0,183821.0,1641.55,12.13,72.0,M-SC,4.85,220.0,0.29,1.25,38.29,OX40N,ATH,CABLES
1,ABB,0.04,39.26,4.53,45.57,16504.0,102701.0,364320.0,7934.00,-10.49,82.0,H-MC,20.49,125.0,6.22,2.48,61.78,AR,NTT,ELECTRICAL

In [15]:
# top 5 to monitor for exit
df_tmp = df_portfolio_features[~df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])]
df_tmp = df_tmp[(df_tmp['Current P/L%'] > 0) ].sort_values(by = 'Dev%_PE', ascending=False)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
72,STARHEALTH,1.57,0.01,47.25,47.26,132838.0,16.0,281139.0,761.00,57.86,73.0,H-SC,3.62,173.0,0.00,1.91,45.60,XY24,NTT,INSURANCE
61,RECLTD,-1.36,2.37,17.94,20.74,37312.0,4812.0,207982.0,446.00,13.28,67.0,M-MC,3.72,191.0,0.13,1.42,23.94,XY25,NTT,FINANCE
26,FINCABLES,0.74,24.50,66.99,107.91,123142.0,36177.0,183821.0,1641.55,12.13,72.0,M-SC,4.85,220.0,0.29,1.25,38.29,OX40N,ATH,CABLES
1,ABB,0.04,39.26,4.53,45.57,16504.0,102701.0,364320.0,7934.00,-10.49,82.0,H-MC,20.49,125.0,6.22,2.48,61.78,AR,NTT,ELECTRICAL
71,SONACOMS,-1.61,0.16,38.86,39.09,39375.0,166.0,101325.0,804.02,-20.60,62.0,M-MC,11.93,193.0,0.00,0.69,43.34,AR,ATH,AUTO

In [16]:
# top 5 to book for rotation from weak conviction
df_tmp = df_portfolio_features[~df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])]
df_tmp = df_tmp[~df_tmp['Criteria'].isin(['XY25','XY24','X40', 'X40N'])].sort_values(by = 'RRR Ind', ascending=False)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
1,ABB,0.04,39.26,4.53,45.57,16504.0,102701.0,364320.0,7934.00,-10.49,82.0,H-MC,20.49,125.0,6.22,2.48,61.78,AR,NTT,ELECTRICAL
26,FINCABLES,0.74,24.50,66.99,107.91,123142.0,36177.0,183821.0,1641.55,12.13,72.0,M-SC,4.85,220.0,0.29,1.25,38.29,OX40N,ATH,CABLES
71,SONACOMS,-1.61,0.16,38.86,39.09,39375.0,166.0,101325.0,804.02,-20.60,62.0,M-MC,11.93,193.0,0.00,0.69,43.34,AR,ATH,AUTO
89,ZYDUSLIFE,1.41,-0.56,36.39,35.63,75838.0,-1171.0,208403.0,1286.17,-13.51,62.0,H-MC,4.37,120.0,-0.02,1.42,10.95,AR,ATH,PHARMA
43,INDIAMART,0.34,-6.50,121.10,106.72,139649.0,-8019.0,115317.0,4810.62,-57.81,61.0,H-SC,11.08,140.0,-0.06,0.79,10.79,AR,ATH,MISC

In [17]:
# top 5 to accumulate based on lowest RSI_14
df_tmp = df_portfolio_features[df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])].sort_values(by = 'RSI_14', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
34,HCLTECH,-0.41,-16.93,49.08,23.83,98631.0,-40964.0,200960.0,1908.19,-12.74,32.0,X-LC,7.33,8.0,-0.42,1.37,0.00,X40,ATH,IT
41,ICICIPRULI,-1.36,-11.85,48.30,30.73,83878.0,-23345.0,173660.0,790.00,-35.47,38.0,X-MC,13.15,78.0,-0.28,1.18,5.82,X40,ATH,INSURANCE
2,ABBOTINDIA,-0.18,-14.88,38.70,18.07,58921.0,-26605.0,152250.0,35195.00,-27.52,39.0,X-MC,11.95,58.0,-0.45,1.04,0.00,X40,ATH,PHARMA
46,INFY,-1.36,-14.82,57.60,34.24,153520.0,-46361.0,266527.0,1972.00,-32.87,39.0,X-LC,12.47,3.0,-0.30,1.81,2.50,X40,NTT,IT
36,HDFCLIFE,-0.46,-2.02,35.42,32.69,41531.0,-2419.0,117253.0,814.30,-23.18,43.0,X-LC,17.87,31.0,-0.06,0.80,6.22,X40,ATH,INSURANCE

In [18]:
# top 5 to accumulate based on Spread and CumlRnk
df_tmp = df_portfolio_features[df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])]
df_tmp = df_tmp[(df_tmp['CumlRnk'] < 100)].sort_values(by = 'Spread%', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
69,SIEMENS,0.11,3.40,21.39,25.51,41159.0,6325.0,192420.0,4671.50,61.70,76.0,H-LC,4.76,51.0,0.15,1.31,35.82,AR,ATH,ELECTRICAL
82,UNITDSPR,-0.20,2.11,18.27,20.77,43680.0,4936.0,239080.0,1644.00,-9.40,64.0,X-MC,5.42,64.0,0.11,1.63,14.05,X40N,NTT,BREWERIES
63,RELIANCE,-0.99,-13.43,44.74,25.30,77834.0,-26994.0,173969.0,1952.00,-15.80,47.0,X-LC,5.85,21.0,-0.35,1.18,4.15,XY25,BTT,REFINERIES
86,VOLTAS,-2.47,13.04,28.44,45.20,61644.0,25008.0,216750.0,1856.00,29.40,58.0,X-MC,6.10,79.0,0.41,1.48,20.73,XY25,NTT,AC
24,DMART,-1.34,8.97,18.94,29.60,51514.0,22386.0,271986.0,5391.45,-8.09,65.0,X-LC,6.37,14.0,0.43,1.85,24.32,X40N,ATH,FMCG

In [19]:
# top 5 to accumulate based on lowest Gained%
df_tmp = df_portfolio_features[df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])].sort_values(by = 'Gained%', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
2,ABBOTINDIA,-0.18,-14.88,38.70,18.07,58921.0,-26605.0,152250.0,35195.00,-27.52,39.0,X-MC,11.95,58.0,-0.45,1.04,0.00,X40,ATH,PHARMA
34,HCLTECH,-0.41,-16.93,49.08,23.83,98631.0,-40964.0,200960.0,1908.19,-12.74,32.0,X-LC,7.33,8.0,-0.42,1.37,0.00,X40,ATH,IT
46,INFY,-1.36,-14.82,57.60,34.24,153520.0,-46361.0,266527.0,1972.00,-32.87,39.0,X-LC,12.47,3.0,-0.30,1.81,2.50,X40,NTT,IT
63,RELIANCE,-0.99,-13.43,44.74,25.30,77834.0,-26994.0,173969.0,1952.00,-15.80,47.0,X-LC,5.85,21.0,-0.35,1.18,4.15,XY25,BTT,REFINERIES
41,ICICIPRULI,-1.36,-11.85,48.30,30.73,83878.0,-23345.0,173660.0,790.00,-35.47,38.0,X-MC,13.15,78.0,-0.28,1.18,5.82,X40,ATH,INSURANCE

In [20]:
# top 5 to accumulate based on lowest CurrAlloc%
df_tmp = df_portfolio_features[df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])].sort_values(by = 'CurrAlloc%', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
62,RELAXO,-0.45,-59.81,278.96,52.31,162745.0,-86820.0,58340.0,1176.0,-57.22,58.0,X-SC,30.59,92.0,-0.53,0.40,30.44,X40N,NTT,FOOTWEAR
11,BATAINDIA,-1.63,-50.87,175.19,35.20,110750.0,-65453.0,63217.0,2096.0,-17.11,61.0,X-SC,30.08,91.0,-0.59,0.43,25.37,X40,NTT,FOOTWEAR
58,QUESS,-1.15,-19.82,116.88,73.90,100083.0,-21164.0,85629.0,424.0,-57.02,57.0,X-SC,18.18,80.0,-0.21,0.58,15.19,XY24,NTT,MISC
53,MARUTI,-1.09,-2.40,31.09,27.95,32809.0,-2592.0,105528.0,17292.0,-19.23,47.0,X-LC,11.93,33.0,-0.08,0.72,13.98,XR,ATH,AUTO
36,HDFCLIFE,-0.46,-2.02,35.42,32.69,41531.0,-2419.0,117253.0,814.3,-23.18,43.0,X-LC,17.87,31.0,-0.06,0.80,6.22,X40,ATH,INSURANCE

In [21]:
# top 5 to accumulate based on CumlRnk
df_tmp = df_portfolio_features.sort_values(by = 'CumlRnk', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
48,ITC,-0.18,-19.68,48.22,19.06,131754.0,-66931.0,273235.0,452.00,-55.92,51.0,X-LC,18.70,1.0,-0.51,1.86,6.00,X40,NTT,FMCG
77,TCS,0.21,-25.32,69.49,26.57,240406.0,-117316.0,345957.0,4311.59,-36.74,51.0,X-LC,15.32,2.0,-0.49,2.36,7.97,X40,ATH,IT
46,INFY,-1.36,-14.82,57.60,34.24,153520.0,-46361.0,266527.0,1972.00,-32.87,39.0,X-LC,12.47,3.0,-0.30,1.81,2.50,X40,NTT,IT
79,TMPV,-1.98,-19.26,69.16,36.58,198702.0,-68534.0,287307.0,600.00,-83.62,58.0,X-LC,8.38,4.0,-0.34,1.96,19.75,XY24,NTT,AUTO
34,HCLTECH,-0.41,-16.93,49.08,23.83,98631.0,-40964.0,200960.0,1908.19,-12.74,32.0,X-LC,7.33,8.0,-0.42,1.37,0.00,X40,ATH,IT

In [22]:
# top 5 for average up
df_tmp = df_portfolio_features[(df_portfolio_features['Dev%_200'] > 5)].sort_values(by = 'CurrAlloc%', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
71,SONACOMS,-1.61,0.16,38.86,39.09,39375.0,166.0,101325.0,804.02,-20.60,62.0,M-MC,11.93,193.0,0.00,0.69,43.34,AR,ATH,AUTO
73,SURYODAY,-1.94,-16.89,48.05,23.03,71507.0,-30253.0,148818.0,216.00,62.28,63.0,H-SC,3.28,166.0,-0.42,1.01,26.91,XR,NTT,BANKS
26,FINCABLES,0.74,24.50,66.99,107.91,123142.0,36177.0,183821.0,1641.55,12.13,72.0,M-SC,4.85,220.0,0.29,1.25,38.29,OX40N,ATH,CABLES
69,SIEMENS,0.11,3.40,21.39,25.51,41159.0,6325.0,192420.0,4671.50,61.70,76.0,H-LC,4.76,51.0,0.15,1.31,35.82,AR,ATH,ELECTRICAL
61,RECLTD,-1.36,2.37,17.94,20.74,37312.0,4812.0,207982.0,446.00,13.28,67.0,M-MC,3.72,191.0,0.13,1.42,23.94,XY25,NTT,FINANCE

In [23]:
# top 5 RSP
df_tmp = df_portfolio_features.sort_values(by = 'RSP', ascending=False)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
59,RAJESHEXPO,4.99,-75.14,302.52,0.07,103168.0,-103074.0,34103.0,518.0,1150.00,62.0,L-SC,39.12,268.0,-1.00,0.23,60.10,OX40N,NTT,JEWELLERY
60,RAJOOENG,7.19,-29.17,97.11,39.61,70502.0,-29900.0,72600.0,143.1,-52.19,70.0,H-SC,26.41,136.0,-0.42,0.49,55.53,AR,ATH,MISC
69,SIEMENS,0.11,3.40,21.39,25.51,41159.0,6325.0,192420.0,4671.5,61.70,76.0,H-LC,4.76,51.0,0.15,1.31,35.82,AR,ATH,ELECTRICAL
85,VBL,-1.28,-1.30,37.29,35.50,116243.0,-4115.0,311727.0,670.8,-12.89,70.0,X-LC,7.85,13.0,-0.04,2.12,28.00,X40N,ATH,FMCG
70,SIS,-1.17,-23.41,58.32,21.26,49596.0,-25990.0,85042.0,528.0,2007.25,71.0,H-SC,8.33,168.0,-0.52,0.58,26.45,OX40N,NTT,MISC

In [24]:
# Top N allocation
df_tmp = df_portfolio_features.sort_values(by = 'CurrAlloc%', ascending=False)
top_n_values = [10, 25, 50]

sum_df = pd.DataFrame({
    'Top_N': top_n_values,
    'Sum_Alloc%': [df_tmp['CurrAlloc%'].head(n).sum() for n in top_n_values]
})

sum_df

   Top_N  Sum_Alloc%
0     10       19.95
1     25       44.25
2     50       75.04

In [25]:
# market-cap-wise allocation
df_tmp = df_portfolio_features[cols]
df_tmp.groupby(df_tmp['Conviction'].str[-2:])['CurrAlloc%'].sum().sort_values(ascending=False)

Conviction
SC    42.32
MC    29.08
LC    28.59
Name: CurrAlloc%, dtype: float64

In [26]:
# criteria-wise allocation
df_portfolio_features.groupby('Criteria')['CurrAlloc%'].sum().sort_values(ascending=False)

Criteria
XY24     26.84
X40      24.31
X40N     15.73
AR        9.43
XR        8.86
XY25      7.13
OX40N     6.89
SR        0.80
Name: CurrAlloc%, dtype: float64

In [27]:
# conviction-wise allocation
df_portfolio_features.groupby('Conviction')['CurrAlloc%'].sum().sort_values(ascending=False)

Conviction
X-LC    26.32
H-SC    21.85
X-MC    21.51
M-SC    10.06
X-SC     9.82
H-MC     5.13
M-MC     2.11
H-LC     1.31
M-LC     0.96
L-SC     0.59
L-MC     0.33
Name: CurrAlloc%, dtype: float64

In [28]:
# sector-wise stats
df_tmp = df_portfolio_features.groupby('Category')[['CurrAlloc%', 'Current', 'Current P/L', 'FTT Amt']].sum().sort_values(by=['Current', 'Current P/L'], ascending=False)
df_tmp['Current P/L%'] = round(df_tmp['Current P/L'] * 100 / df_tmp['Current'], 2)
df_tmp['FTT%'] = round(df_tmp['FTT Amt'] * 100 / df_tmp['Current'], 2)
cols = ['CurrAlloc%', 'Current P/L%', 'FTT%']
df_tmp[cols].sort_values(by=['CurrAlloc%'], ascending=False)

               CurrAlloc%  Current P/L%    FTT%
Category
FMCG                15.67        -13.96   54.23
FINANCE             10.99        -14.34   64.07
IT                  10.94        -40.22  111.58
MISC                 7.02        -29.99   86.46
ELECTRICAL           6.71          1.82   35.77
AUTO                 5.28        -14.31   59.40
PAINTS               5.25        -27.93   50.15
INSURANCE            5.20         -4.34   39.81
PHARMA               4.67         -3.52   36.76
BANKS                4.42        -18.50   78.66
AC                   2.00         -8.76   38.25
HEALTHCARE           1.89        -28.45   61.97
FOOTWEAR             1.80        -67.08  134.07
APPARELS             1.78         -2.43   37.37
DURABLES             1.78        -48.09   84.12
TRAVEL               1.75        -74.77  162.28
BREWERIES            1.63          2.06   18.27
REALTY               1.42         -6.33   23.80
CERAMICS             1.33        -56.76  104.38
CABLES               1.25         19.68   66.99
REFINERIES           1.18        -15.52   44.74
CEMENT               1.16        -56.87  174.22
ENGINEERING          1.15        -43.76  109.51
JEWELLERY            1.10        -98.45  167.40
CHEMICALS            1.05        -71.44  211.31
ENTERTAINMENT        0.77        -70.60  172.36
TEXTILES             0.44        -43.71   84.69
HOTELS               0.36       -117.27  193.90

In [29]:
# money to be made criteria-wise
df_portfolio_features.groupby('Criteria')['FTT Amt'].agg(['sum', 'count']).sort_values(by='sum', ascending=False)

                sum  count
Criteria
XY24      3654868.0     21
X40       1761015.0     17
XR        1330807.0     13
AR        1187013.0     10
X40N      1125455.0     12
OX40N      778660.0     10
XY25       393804.0      5
SR         301259.0      2

In [30]:
# money to be made conviction-wise
df_portfolio_features.groupby('Conviction')['FTT Amt'].agg(['sum', 'count']).sort_values(by='sum', ascending=False)

                  sum  count
Conviction
H-SC        3585527.0     24
X-LC        1722083.0     18
X-MC        1574948.0     15
M-SC        1439605.0     14
X-SC        1358391.0      9
H-MC         326008.0      3
L-SC         204504.0      2
M-LC         150362.0      1
M-MC          76687.0      2
L-MC          53607.0      1
H-LC          41159.0      1

In [31]:
# money to be made criteria and conviction-wise
df_portfolio_features.groupby(['Conviction', 'Criteria'])['FTT Amt'].agg(['sum', 'count']).sort_values(by='sum', ascending=False)

                           sum  count
Conviction Criteria
H-SC       XY24      1189371.0      6
           AR         939751.0      5
X-LC       X40        910850.0      8
M-SC       XY24       852180.0      6
H-SC       XR         817153.0      7
X-SC       XY24       806837.0      4
X-MC       X40        648425.0      7
           X40N       467320.0      4
X-SC       X40N       349814.0      3
H-SC       OX40N      337993.0      4
M-SC       OX40N      337499.0      5
X-LC       XY24       337069.0      2
           X40N       308321.0      5
H-SC       SR         301259.0      2
X-MC       XY24       235745.0      2
H-MC       XY24       233666.0      1
X-MC       XY25       223458.0      2
X-SC       X40        201740.0      2
M-SC       XR         175540.0      2
M-LC       XR         150362.0      1
X-LC       XY25       133034.0      2
L-SC       OX40N      103168.0      1
           XR         101336.0      1
H-MC       AR          92342.0      2
M-SC       AR          74386.0      1
L-MC       XR          53607.0      1
H-LC       AR          41159.0      1
M-MC       AR          39375.0      1
           XY25        37312.0      1
X-LC       XR          32809.0      1

In [32]:
# notebook execution time

end_time = time.time()
execution_time = round(end_time - start_time, 0)
print(f"Notebook execution time: {execution_time} seconds")

Notebook execution time: 40.0 seconds