<a href="https://colab.research.google.com/github/ankit-rathi/Quantvesting_v2/blob/main/myStocks_Portfolio_Analysis.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
'''
!pip install pandas==2.2.2 -qq
!pip install pyxirr -qq
!pip install ta -qq
!pip install yfinance==0.2.59 -qq
'''

'\n!pip install pandas==2.2.2 -qq\n!pip install pyxirr -qq\n!pip install ta -qq\n!pip install yfinance==0.2.59 -qq\n'

In [2]:
# import libraries

import numpy as np
import pandas as pd
import datetime
import warnings
warnings.filterwarnings('ignore')
import yfinance as yfin
import ta
import matplotlib.pyplot as plt
import requests

In [3]:
# notebook start time
import time
import datetime
import pytz

start_time = time.time()

# function to print date timestamp
def print_date_time():
  tz_NY = pytz.timezone('Asia/Kolkata')
  datetime_NY = datetime.datetime.now(tz_NY)
  print("Run date time (IST):", datetime_NY.strftime("%Y-%m-%d %H:%M:%S"))

In [4]:
# function to get booked and reserved amount
def get_amt():
  # fetch the JSON data from the URL
  url = "https://raw.githubusercontent.com/ankit-rathi/Tradevesting_v1/main/data/myPortfolioAmts.json"
  response = requests.get(url)
  pf_amts = response.json()  # parse the JSON data

  # extract values from the JSON
  py_booked_amt_dm = pf_amts["py_booked_amt_dm"]
  py_booked_amt_sv = pf_amts["py_booked_amt_sv"]
  cy_booked_amt_dm = pf_amts["cy_booked_amt_dm"]
  cy_booked_amt_sv = pf_amts["cy_booked_amt_sv"]
  reserve_amt_dm = pf_amts["reserve_amt_dm"]
  reserve_amt_sv = pf_amts["reserve_amt_sv"]

  # perform calculations
  py_booked_amt = py_booked_amt_dm + py_booked_amt_sv
  cy_booked_amt = cy_booked_amt_dm + cy_booked_amt_sv
  reserve_amt = reserve_amt_dm + reserve_amt_sv
  total_booked_amt = py_booked_amt + cy_booked_amt

  return total_booked_amt, reserve_amt, cy_booked_amt, py_booked_amt

gen_output = 0

In [5]:
# function to format the amount
def format_amt(number):
    abs_number = abs(number)

    if abs_number >= 1_00_00_000:  # Crores
        formatted_amt = f"{number / 1_00_00_000:.2f} C"
    elif abs_number >= 1_00_000:  # Lakhs
        formatted_amt = f"{number / 1_00_000:.2f} L"
    elif abs_number >= 1_000:  # Thousands
        formatted_amt = f"{number / 1_000:.2f} K"
    else:
        formatted_amt = f"{number:.2f}"

    return formatted_amt

# function to set start and end date
def get_start_end_date():
  start_date = (datetime.date.today() + datetime.timedelta(days=-365)).strftime('%Y-%m-%d')
  end_date = (datetime.date.today() + datetime.timedelta(days=1)).strftime('%Y-%m-%d')
  return start_date, end_date

# function to fetch my portfolio csv
def get_mypfs_df():
  mypfs_df = pd.read_csv('https://raw.githubusercontent.com/ankit-rathi/Tradevesting_v1/main/data/myPortfolioStocks.csv')
  return mypfs_df

# function to fetch my prospects csv
def get_mypps_df():
  mypps_df = pd.read_csv('https://raw.githubusercontent.com/ankit-rathi/Tradevesting_v1/main/data/myProspectsScrips.csv')
  return mypps_df

# function to fetch screener data
def get_myscreen_df():
  myscreen_df = pd.read_csv('https://raw.githubusercontent.com/ankit-rathi/Tradevesting_v1/main/data/myScreenerDB.csv')
  return myscreen_df

# function to fetch momentum data
def get_myinvmt_df():
  myinvmt_df = pd.read_csv('https://raw.githubusercontent.com/ankit-rathi/Tradevesting_v1/main/data/myInvestments.csv')
  return myinvmt_df

# function to get the stock ids
def get_stock_ids(df_pf):
  stock_n100 = df_pf['Symbol'].unique()

  exclude = ['CADILAHC','MMTC', 'MASFIN']

  stock_ids = df_pf[~df_pf['Symbol'].isin(exclude) ]['Symbol'].unique()

  #mypf = mypf[mypf.Forecast.notnull()]
  #stock_ids = mypf['Symbol'].unique()

  #stock_ids.sort()
  return stock_ids

# get features from screener data
def get_screener_features():
  myscreen_df = get_myscreen_df()
  cols = ['Symbol', 'EPS', 'MedPE', 'ROCE%', 'ROE%', 'CapType']
  return myscreen_df[cols]

# get relative strength
def get_relative_strength(stock_list):

    # Dictionary to store stock tickers and their corresponding percentage price change
    stock_changes = {}

    # Loop through each stock and fetch its price data
    for stock in stock_list:
        try:
            # Download the stock data for the given date range
            stock_data = yfin.Ticker(stock + '.NS').history(period='1mo', interval='1d')[map(str.title, ['open', 'close', 'low', 'high', 'volume'])]

            # Calculate the percentage change for the stock
            if len(stock_data) > 0:
                start_price = stock_data['Close'].iloc[0]
                end_price = stock_data['Close'].iloc[-1]
                percent_change = round(((end_price - start_price) / start_price) * 100, 2)
                stock_changes[stock] = percent_change
            else:
                stock_changes[stock] = np.nan  # If no data is available, set to NaN

        except Exception as e:
            print(f"Error fetching data for {stock}: {e}")
            stock_changes[stock] = np.nan

    # Create a DataFrame with stock tickers and their percentage changes
    df = pd.DataFrame(list(stock_changes.items()), columns=['Symbol', 'Percent_Change'])

    # Drop any stocks with missing data (NaN values)
    df = df.dropna()

    # Calculate the percentile rank based on percentage change
    df['RSP'] = round(df['Percent_Change'].rank(pct=True) * 100, 2)
    cols = ['Symbol', 'RSP']
    df = df[cols]
    # Sort by percentile rank (optional)
    df = df.sort_values(by='RSP', ascending=False).reset_index(drop=True)

    return df

In [6]:
# function to get stock technicals
def stock_prec_dev(stock_symbol):
    #stock_symbol = 'ULTRACEMCO.NS'
    short_window = 20
    mid_window = 50
    long_window = 200
    moving_avg = 'SMA'

    start = datetime.datetime(*map(int, start_date.split('-')))
    end = datetime.datetime(*map(int, end_date.split('-')))

    stock_df = yfin.Ticker(stock_symbol + '.NS').history(period='max', interval='1d')[map(str.title, ['open', 'close', 'low', 'high', 'volume'])]

    stock_df['Max'] = round(max(stock_df['Close']),2)
    stock_df = stock_df[(stock_df.index <= end_date) & (stock_df.index >= start_date)]
    stock_df['200_SMA'] = round(stock_df['Close'].rolling(window = 200, min_periods = 1).mean(),0)
    stock_df['Dev%_200'] = round((stock_df['Close'] - stock_df['200_SMA'])*100/stock_df['200_SMA'],2)
    stock_df.dropna(axis = 0, inplace = True) # remove any null rows

    stock_df['20_SMA'] = stock_df['Close'].rolling(window=20).mean()
    stock_df['50_SMA'] = stock_df['Close'].rolling(window=50).mean()
    stock_df['Symbol'] = stock_symbol

    stock_df['Close'] = round(stock_df['Close'],2)
    stock_df['Min'] = round(min(stock_df['Close']),2)
    stock_df['RSI_14'] = ta.momentum.RSIIndicator(close=stock_df['Close'], window=14).rsi()
    stock_df['RSI_14'] = round(stock_df['RSI_14'],0)
    stock_df['Prev_Close'] = stock_df['Close'].shift(1)
    stock_df.drop(['Open', 'Low', 'High', 'Volume'], axis=1, inplace=True)
    stock_df = stock_df.tail(1)

    max_SMA = max(stock_df['20_SMA'].item(), stock_df['50_SMA'].item(), stock_df['200_SMA'].item())
    min_SMA = min(stock_df['20_SMA'].item(), stock_df['50_SMA'].item(), stock_df['200_SMA'].item())
    ABS_Spread = max_SMA - min_SMA
    stock_df['Spread%'] = round((ABS_Spread / stock_df['200_SMA'].item()) * 100,2)

    return stock_df

# function to compute stock attributes
def get_common_features(stock_ids, df_mypf):

  df_prec_dev = pd.DataFrame()
  df_tmp = get_screener_features()
  df_rs = get_relative_strength(stock_ids)

  for stock_id in stock_ids:
      tmp = stock_prec_dev(stock_id)
      tmp = tmp.reset_index()
      df_prec_dev = pd.concat([df_prec_dev, tmp], ignore_index = True)
  df_prec_dev = pd.merge(df_prec_dev, df_mypf, on= 'Symbol')
  df_prec_dev = pd.merge(df_prec_dev, df_tmp, on= 'Symbol', how='left')
  df_prec_dev = pd.merge(df_prec_dev, df_rs, on= 'Symbol', how='left')
  #print(df_prec_dev.columns)
  df_prec_dev['Curr_PE'] = round(df_prec_dev['Close']/df_prec_dev['EPS'],1)
  df_prec_dev['Dev%_PE'] = round((df_prec_dev['Curr_PE'] - df_prec_dev['MedPE'])*100/df_prec_dev['MedPE'],2)
  df_prec_dev['Conviction'] = df_prec_dev['Conviction'] + '-' + df_prec_dev['CapType']
  return df_prec_dev

# function to arrange stock features
def arrange_features(df_stocks, common_cols, diff_cols):
  df_stocks_common = df_stocks[common_cols].drop_duplicates()
  df_stocks_diff = df_stocks[diff_cols]
  df_stocks_diff['Investment'] = df_stocks_diff['AvgCost'] * df_stocks_diff['Shares']
  df_stocks_diff = df_stocks_diff.groupby(['Symbol'])[['Shares', 'Investment']].aggregate(['sum']).reset_index()
  df_stocks_diff.columns = ['Symbol', 'Shares', 'Investment']
  df_stocks_diff['AvgCost'] = round(df_stocks_diff['Investment']/df_stocks_diff['Shares'],2)
  df_stocks = pd.merge(df_stocks_diff, df_stocks_common, on='Symbol')
  return df_stocks

# plot fact distribution across dimension
def plot_pie_chart(df, dimension, fact):
  # grouping the data by category and calculating the sum of fact for each type
  grouped_data = df.groupby(dimension)[fact].sum()

  # sorting the grouped data in descending order
  grouped_data = grouped_data.sort_values(ascending=False)

  # creating a pie chart
  grouped_data.plot.pie(autopct='%1.1f%%', startangle=90, figsize=(6, 6))

  # adding a title and displaying the plot
  plt.title(f'{dimension} {fact} Distribution')
  plt.ylabel('')  # To hide the y-label
  plt.show()

In [7]:
# function to get portfolio features

def get_portfolio_features(df_common_features):

  print_date_time()
  print('-------------------')

  #df_common_features["Target"] = df_common_features["Target"].fillna(df_common_features["Max"])
  df_common_features['NTT'] = np.where(df_common_features['Strategy']== 'NTT', df_common_features["Target"], df_common_features['Max'])
  df_common_features['LTT'] = np.where(df_common_features['Strategy']== 'BTT', df_common_features["Target"], df_common_features['Max'])
  df_common_features['BOL'] = df_common_features['Min']

  tmp_df = df_common_features[df_common_features['Symbol'].isin(mypf_df[mypf_df['InPortfolio'] != 'NA'].Symbol.values)]
  print('qualified stocks: '+str(len(tmp_df['Symbol'].unique())))
  tmp_df1 = tmp_df[tmp_df['LatestQtr'] == 1]
  print('with latest results: '+str(len(tmp_df1['Symbol'].unique())))
  tmp_df1 = tmp_df1[tmp_df1['StarStock'] == 1]
  print('still star stocks: '+str(len(tmp_df1['Symbol'].unique())))
  tmp_df['Investment'] = tmp_df['AvgCost'] * tmp_df['Shares']
  tmp_df['Current'] = round(tmp_df['Close'] * tmp_df['Shares'],0)
  tmp_df['Previous'] = tmp_df['Prev_Close'] * tmp_df['Shares']
  tmp_df['EstimatedST'] = tmp_df['NTT'] * tmp_df['Shares']
  tmp_df['EstimatedLT'] = tmp_df['LTT'] * tmp_df['Shares']
  tmp_df['Current P/L'] = round((tmp_df['Current'] - tmp_df['Investment']),0)
  tmp_df['Today P/L%'] = round((tmp_df['Current'] - tmp_df['Previous'])*100/tmp_df['Previous'],2)
  tmp_df['Current P/L%'] = round((tmp_df['Current'] - tmp_df['Investment'])*100/tmp_df['Investment'],2)
  tmp_df['EstimatedST P/L%'] = round((tmp_df['EstimatedST'] - tmp_df['Investment'])*100/tmp_df['Investment'],2)
  tmp_df['EstimatedLT P/L%'] = round((tmp_df['EstimatedLT'] - tmp_df['Investment'])*100/tmp_df['Investment'],2)
  tmp_df['NTT%'] = round((tmp_df['NTT'] - tmp_df['Close'])*100/tmp_df['Close'],2)
  tmp_df['LTT%'] = round((tmp_df['LTT'] - tmp_df['Close'])*100/tmp_df['Close'],2)
  tmp_df['Gained%'] = round((tmp_df['Close'] - tmp_df['BOL'])*100/tmp_df['BOL'],2)
  investment = round(sum(tmp_df['AvgCost']*tmp_df['Shares']),0)
  current = round(sum(tmp_df['Close']*tmp_df['Shares']),0)
  tmp_df['InitAlloc%'] = round(tmp_df['Investment']*100/investment,2)
  tmp_df['CurrAlloc%'] = round(tmp_df['Current']*100/current,2)
  tmp_df['FTT'] = tmp_df['LTT']
  tmp_df.loc[tmp_df['Strategy'] == 'NTT', 'FTT'] = tmp_df['NTT']
  tmp_df['FTT%'] = tmp_df['LTT%']
  tmp_df.loc[tmp_df['Strategy'] == 'NTT', 'FTT%'] = tmp_df['NTT%']
  tmp_df['FTT Amt'] = round(tmp_df['FTT%'] * tmp_df['Current']/100,0)
  tmp_df['OTT%'] = round((tmp_df['FTT'] - tmp_df['AvgCost'])*100/tmp_df['AvgCost'],2)
  tmp_df['RRR Ind'] = round(tmp_df['Current P/L']/tmp_df['FTT Amt'],2)
  tmp_df['Risk Ind'] = round(tmp_df['Current P/L%']*tmp_df['CurrAlloc%'],0)

  return tmp_df

# function to print portfolio features
def print_portfolio_stats(df_portfolio_features, myinvmt_df):
  from pyxirr import xirr

  total_booked_amt, reserve_amt, cy_booked_amt, py_booked_amt = get_amt()

  dates = myinvmt_df['Date'].values
  dates = np.append(dates, datetime.date.today().strftime('%d-%b-%y'))
  investment = myinvmt_df['Investment'].values
  dates= pd.to_datetime(dates)

  current = round(sum(df_portfolio_features['Close']*df_portfolio_features['Shares']),0) + reserve_amt
  investment_xirr = np.append(investment, current)
  cagr = round(xirr(pd.DataFrame({"dates": dates, "amounts": investment_xirr}))*100,2)

  investment = -sum(investment)
  invested = round(sum(df_portfolio_features['AvgCost']*df_portfolio_features['Shares']),0) + reserve_amt
  previous = round(sum(df_portfolio_features['Prev_Close']*df_portfolio_features['Shares']),0) + reserve_amt
  cy_invested = investment + py_booked_amt

  today_pnl_amount = current-previous
  today_pnl_percentage = round((current-previous)*100/previous,2)

  curr_pnl_amount = current-invested
  curr_pnl_percentage = round((curr_pnl_amount)*100/(cy_invested),2)

  cy_pnl_amount = cy_booked_amt + curr_pnl_amount
  cy_pnl_percentage = round((cy_pnl_amount)*100/cy_invested,2)

  overall_pnl_amount = total_booked_amt + curr_pnl_amount
  overall_pnl_percentage = round((overall_pnl_amount)*100/investment,2)

  estimate_st = round(sum(df_portfolio_features['FTT']*df_portfolio_features['Shares']),0)  + reserve_amt
  est_st_pnl_amount = estimate_st-current
  est_st_pnl_percentage = round((est_st_pnl_amount)*100/current,2)

  estimate_lt = round(sum(df_portfolio_features['LTT']*df_portfolio_features['Shares']),0)  + reserve_amt
  est_lt_pnl_amount = estimate_lt-current
  est_lt_pnl_percentage = round((est_lt_pnl_amount)*100/current,2)

  total_profit = round(sum(df_portfolio_features[df_portfolio_features['Current P/L%'] > 0]['Current']) - sum(df_portfolio_features[df_portfolio_features['Current P/L%'] > 0]['Investment']),0)
  total_loss = round(sum(df_portfolio_features[df_portfolio_features['Current P/L%'] < 0]['Current']) - sum(df_portfolio_features[df_portfolio_features['Current P/L%'] < 0]['Investment']),0)

  cy_booked_percentage = round((cy_booked_amt)*100/current,2)
  py_booked_percentage = round((py_booked_amt)*100/investment,2)
  total_booked_percentage = round((total_booked_amt)*100/investment,2)

  print('-------------------')
  print('Initial Investment: ', format_amt(investment))
  print('CY Investment: ', format_amt(cy_invested))
  print('Reserve: ', format_amt(reserve_amt))
  print('Current: ',  format_amt(current))
  print('-------------------')
  print('Today PnL: '+ '{} ({}%)'.format(format_amt(today_pnl_amount), today_pnl_percentage))
  print('Current PnL: '+ '{} ({}%)'.format(format_amt(curr_pnl_amount), curr_pnl_percentage))
  print('CY Booked + Current PnL: '+ '{} ({}%)'.format(format_amt(cy_pnl_amount), cy_pnl_percentage))
  print('-------------------')
  print('Total profit: ', format_amt(total_profit))
  print('Total loss: ', format_amt(total_loss))
  print('-------------------')
  print('Total Booked + Current PnL: '+ '{} ({}%)'.format(format_amt(overall_pnl_amount), overall_pnl_percentage))
  print('Total Booked PnL: '+ '{} ({}%)'.format(format_amt(total_booked_amt), total_booked_percentage))
  print('Curr Year Booked PnL: '+ '{} ({}%)'.format(format_amt(cy_booked_amt), cy_booked_percentage))
  print('Prev Year Booked PnL: '+ '{} ({}%)'.format(format_amt(py_booked_amt), py_booked_percentage))
  print('===================')
  print('Est FTT: ',  format_amt(estimate_st))
  print('Est FTT PnL: '+ '{} ({}%)'.format(format_amt(est_st_pnl_amount), est_st_pnl_percentage))

  print('===================')
  print('Deployed: ', format_amt(investment))

  print('Current: ', format_amt(current))

  print('CAGR/XIRR %: '+'{}%'.format(cagr))

In [8]:
# get start and end date
start_date, end_date = get_start_end_date()

# get portfolio and prospects data
mypfs_df = get_mypfs_df()
mypps_df = get_mypps_df()
myinvmt_df = get_myinvmt_df()

# merge above datasets
mypf_df = pd.merge(mypfs_df, mypps_df, on="Symbol")

# seggregate dm and sv portfolio
dm_pf = mypf_df[mypf_df['InPortfolio'] == 'DM']
sv_pf = mypf_df[mypf_df['InPortfolio'] == 'SV']

# build portfolio stock dataframe
dm_stocks = get_stock_ids(dm_pf)
sv_stocks = get_stock_ids(sv_pf)
df_stocks = pd.concat([dm_pf,sv_pf], ignore_index = True)

# arrange common and diff stock features
common_cols = ['Symbol', 'Target', 'Criteria', 'Strategy', 'CumlRnk', 'LatestQtr', 'StarStock', 'Conviction', 'Category', 'InFolio', 'XIRR', 'MBQ']
diff_cols = ['Symbol', 'AvgCost', 'Shares']
df_stocks = arrange_features(df_stocks, common_cols, diff_cols)

# get common features
stock_ids = df_stocks['Symbol'].values
df_common_features = get_common_features(stock_ids, df_stocks)

df_common_features.reset_index(drop=True, inplace=True)
df_common_features.drop(['Date'], axis=1, inplace=True)
# get and print portfolio features
df_portfolio_features = get_portfolio_features(df_common_features)

print_portfolio_stats(df_portfolio_features, myinvmt_df)

df = df_portfolio_features
#plot_pie_chart(df, 'CapType', 'Current')
list_ox40n = list(df[df['MBQ'].str.contains('OX40N', na=False)]['Symbol'].values)

Run date time (IST): 2026-03-19 14:40:06
-------------------
qualified stocks: 86
with latest results: 26
still star stocks: 16
-------------------
Initial Investment:  1.36 C
CY Investment:  1.62 C
Reserve:  1.61 K
Current:  1.31 C
-------------------
Today PnL: -3.05 L (-2.27%)
Current PnL: -45.77 L (-28.17%)
CY Booked + Current PnL: -29.88 L (-18.39%)
-------------------
Total profit:  60.61 K
Total loss:  -46.38 L
-------------------
Total Booked + Current PnL: -2.90 L (-2.14%)
Total Booked PnL: 42.87 L (31.64%)
Curr Year Booked PnL: 15.89 L (12.1%)
Prev Year Booked PnL: 26.98 L (19.91%)
===================
Est FTT:  2.48 C
Est FTT PnL: 1.17 C (88.72%)
===================
Deployed:  1.36 C
Current:  1.31 C
CAGR/XIRR %: -1.54%

In [9]:
# top 5 near their targets
cols = ['Symbol', 'Today P/L%', 'Current P/L%', 'FTT%', 'OTT%', 'FTT Amt', 'Current P/L', 'Current', 'FTT', 'Dev%_PE', 'RSI_14','Conviction', 'Spread%',  'CumlRnk', 'RRR Ind', 'CurrAlloc%', 'Gained%', 'Criteria', 'Strategy', 'Category']
df_tmp = df_portfolio_features[~df_portfolio_features['Symbol'].isin(['ENRIN','BLUSPRING','DIGITIDE'])]
df_tmp = df_tmp.sort_values(by = 'FTT Amt', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
50,MASFIN,-3.68,-11.45,37.29,21.57,32353.0,-11220.0,86760.0,397.04,-23.67,34.0,H-SC,1.85,167.0,-0.35,0.66,18.96,XR,ATH,FINANCE
77,TTKPRESTIG,2.03,-36.64,57.98,0.09,37020.0,-36928.0,63849.0,770.00,48.13,42.0,M-SC,17.50,250.0,-1.00,0.49,7.88,OX40N,NTT,DURABLES
37,ICICIGI,-1.41,-4.37,24.79,19.34,47441.0,-8737.0,191372.0,2252.93,-19.59,34.0,X-MC,2.52,66.0,-0.18,1.46,5.79,X40,ATH,INSURANCE
67,SONACOMS,-3.48,-14.54,62.76,39.09,54256.0,-14709.0,86450.0,804.02,-32.22,44.0,M-MC,8.34,193.0,-0.27,0.66,22.30,AR,ATH,AUTO
2,ABBOTINDIA,-0.87,-12.29,34.61,18.07,54293.0,-21985.0,156870.0,35195.00,-25.27,40.0,X-MC,10.83,58.0,-0.40,1.19,0.00,X40,ATH,PHARMA

In [10]:
# top 5 today
df_tmp = df_portfolio_features.sort_values(by = 'Today P/L%', ascending=False)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
80,VALIANTORG,7.61,-46.96,228.37,74.15,198152.0,-76837.0,86768.0,838.00,-255.96,62.0,H-SC,29.26,145.0,-0.39,0.66,29.12,XR,NTT,CHEMICALS
71,TANLA,5.69,-51.26,350.76,119.69,462870.0,-138799.0,131962.0,1943.92,-50.72,43.0,H-SC,24.63,147.0,-0.30,1.00,5.69,AR,ATH,IT
70,SYMPHONY,4.03,-37.52,60.00,-0.03,64157.0,-64212.0,106929.0,1306.00,-49.88,48.0,M-SC,14.76,205.0,-1.00,0.81,8.13,OX40N,NTT,DURABLES
69,SURYODAY,2.11,-26.07,66.41,23.03,87924.0,-46675.0,132396.0,216.00,44.74,51.0,H-SC,6.60,166.0,-0.53,1.01,29.40,XR,NTT,BANKS
77,TTKPRESTIG,2.03,-36.64,57.98,0.09,37020.0,-36928.0,63849.0,770.00,48.13,42.0,M-SC,17.50,250.0,-1.00,0.49,7.88,OX40N,NTT,DURABLES

In [11]:
# bottom 5 today
df_tmp = df_portfolio_features.sort_values(by = 'Today P/L%', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
19,COFFEEDAY,-5.07,-59.15,231.13,35.27,107214.0,-67162.0,46387.0,80.0,-67.81,26.0,L-SC,24.62,266.0,-0.63,0.35,0.00,XR,NTT,HOTELS
79,VAIBHAVGBL,-4.87,-37.15,155.81,60.77,178979.0,-67905.0,114870.0,521.0,32.23,38.0,H-SC,5.23,160.0,-0.38,0.87,4.14,XR,NTT,JEWELLERY
75,TMPV,-4.74,-29.58,93.96,36.58,235439.0,-105267.0,250574.0,600.0,-85.81,31.0,X-LC,4.44,4.0,-0.45,1.91,0.00,XY24,NTT,AUTO
34,HDFCBANK,-4.58,-3.77,33.39,28.37,75473.0,-8849.0,226036.0,1073.0,-18.07,28.0,X-LC,10.13,26.0,-0.12,1.72,0.00,X40,BTT,BANKS
21,DABUR,-4.57,-15.70,70.45,43.70,147333.0,-38936.0,209132.0,735.0,-23.53,24.0,X-MC,4.02,70.0,-0.26,1.59,0.00,XY24,BTT,FMCG

In [12]:
# top 5 to exit based on CumlRnk
df_tmp = df_portfolio_features[~df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])]
df_tmp = df_tmp[(df_tmp['Current P/L%'] > -1) & (df_tmp['Current P/L%'] < 1)].sort_values(by = 'CumlRnk', ascending=False)
df_tmp[cols].head()

Empty DataFrame
Columns: [Symbol, Today P/L%, Current P/L%, FTT%, OTT%, FTT Amt, Current P/L, Current, FTT, Dev%_PE, RSI_14, Conviction, Spread%, CumlRnk, RRR Ind, CurrAlloc%, Gained%, Criteria, Strategy, Category]
Index: []

In [13]:
# OX40N stocks to exit
df_tmp = df_portfolio_features[(df_portfolio_features['Symbol'].isin(list_ox40n))].sort_values(by = 'Current P/L%', ascending=False)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
26,FINCABLES,-3.20,7.51,93.39,107.91,148243.0,11091.0,158735.0,1641.55,-3.09,49.0,M-SC,8.07,220.0,0.07,1.21,19.42,OX40N,ATH,CABLES
77,TTKPRESTIG,2.03,-36.64,57.98,0.09,37020.0,-36928.0,63849.0,770.00,48.13,42.0,M-SC,17.50,250.0,-1.00,0.49,7.88,OX40N,NTT,DURABLES
66,SIS,-1.99,-37.07,92.70,21.26,64769.0,-41162.0,69870.0,528.00,1631.09,32.0,H-SC,13.59,168.0,-0.64,0.53,0.70,OX40N,NTT,MISC
18,CERA,-4.07,-37.51,98.24,23.89,107993.0,-65975.0,109928.0,9475.00,-39.62,47.0,H-SC,18.23,153.0,-0.61,0.84,5.64,OX40N,NTT,CERAMICS
70,SYMPHONY,4.03,-37.52,60.00,-0.03,64157.0,-64212.0,106929.0,1306.00,-49.88,48.0,M-SC,14.76,205.0,-1.00,0.81,8.13,OX40N,NTT,DURABLES

In [14]:
# top 5 to book for rotation
df_tmp = df_portfolio_features[(df_portfolio_features['Current P/L%'] > 20) ].sort_values(by = 'CumlRnk', ascending=False)
df_tmp[cols].head()

Empty DataFrame
Columns: [Symbol, Today P/L%, Current P/L%, FTT%, OTT%, FTT Amt, Current P/L, Current, FTT, Dev%_PE, RSI_14, Conviction, Spread%, CumlRnk, RRR Ind, CurrAlloc%, Gained%, Criteria, Strategy, Category]
Index: []

In [15]:
# top 5 to monitor for exit
df_tmp = df_portfolio_features[~df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])]
df_tmp = df_tmp[(df_tmp['Current P/L%'] > 0) ].sort_values(by = 'Dev%_PE', ascending=False)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
26,FINCABLES,-3.20,7.51,93.39,107.91,148243.0,11091.0,158735.0,1641.55,-3.09,49.0,M-SC,8.07,220.0,0.07,1.21,19.42,OX40N,ATH,CABLES
1,ABB,-1.78,14.20,27.46,45.57,82044.0,37157.0,298776.0,7934.00,-26.59,58.0,H-MC,12.54,125.0,0.45,2.27,32.68,AR,NTT,ELECTRICAL

In [16]:
# top 5 to book for rotation from weak conviction
df_tmp = df_portfolio_features[~df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])]
df_tmp = df_tmp[~df_tmp['Criteria'].isin(['XY25','XY24','X40', 'X40N'])].sort_values(by = 'RRR Ind', ascending=False)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
1,ABB,-1.78,14.20,27.46,45.57,82044.0,37157.0,298776.0,7934.00,-26.59,58.0,H-MC,12.54,125.0,0.45,2.27,32.68,AR,NTT,ELECTRICAL
26,FINCABLES,-3.20,7.51,93.39,107.91,148243.0,11091.0,158735.0,1641.55,-3.09,49.0,M-SC,8.07,220.0,0.07,1.21,19.42,OX40N,ATH,CABLES
40,INDIAMART,-2.89,-12.44,136.10,106.72,146972.0,-15348.0,107988.0,4810.62,-60.55,36.0,H-SC,10.52,140.0,-0.10,0.82,8.02,AR,ATH,MISC
85,ZYDUSLIFE,-2.11,-7.13,46.05,35.63,89624.0,-14950.0,194624.0,1286.17,-19.37,41.0,H-MC,5.30,120.0,-0.17,1.48,8.35,AR,ATH,PHARMA
84,WIPRO,-2.92,-22.63,122.66,72.27,160805.0,-38350.0,131098.0,420.00,-30.18,27.0,M-LC,16.58,98.0,-0.24,1.00,0.00,XR,NTT,IT

In [17]:
# top 5 to accumulate based on lowest RSI_14
df_tmp = df_portfolio_features[df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])].sort_values(by = 'RSI_14', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
12,BATAINDIA,-3.23,-57.98,221.79,35.20,119904.0,-74608.0,54062.0,2096.00,-29.10,14.0,X-SC,29.31,91.0,-0.62,0.41,0.0,X40,NTT,FOOTWEAR
53,PGHH,-0.89,-25.59,77.41,32.01,122989.0,-54640.0,158880.0,17616.87,-49.68,16.0,X-MC,13.90,57.0,-0.44,1.21,0.0,X40,ATH,FMCG
58,RELAXO,-4.13,-64.54,329.51,52.31,169612.0,-93686.0,51474.0,1176.00,-62.25,20.0,X-SC,23.60,92.0,-0.55,0.39,0.0,X40N,NTT,FOOTWEAR
3,ACC,-3.59,-39.37,188.33,74.81,306157.0,-105564.0,162564.0,3906.00,-57.01,22.0,X-SC,15.88,85.0,-0.34,1.24,0.0,XY24,BTT,CEMENT
73,TCS,-3.15,-30.60,82.39,26.57,264887.0,-141769.0,321504.0,4311.59,-41.33,23.0,X-LC,16.32,2.0,-0.54,2.45,0.0,X40,ATH,IT

In [18]:
# top 5 to accumulate based on Spread and CumlRnk
df_tmp = df_portfolio_features[df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])]
df_tmp = df_tmp[(df_tmp['CumlRnk'] < 100)].sort_values(by = 'Spread%', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
78,UNITDSPR,-2.11,-5.06,27.21,20.77,60486.0,-11851.0,222293.0,1644.00,-15.87,39.0,X-MC,1.00,64.0,-0.20,1.69,1.31,X40N,NTT,BREWERIES
37,ICICIGI,-1.41,-4.37,24.79,19.34,47441.0,-8737.0,191372.0,2252.93,-19.59,34.0,X-MC,2.52,66.0,-0.18,1.46,5.79,X40,ATH,INSURANCE
38,ICICIPRULI,-3.77,-6.26,39.45,30.73,72856.0,-12326.0,184679.0,790.00,-31.46,24.0,X-MC,3.04,78.0,-0.17,1.41,5.65,X40,ATH,INSURANCE
59,RELIANCE,-1.07,-10.58,40.13,25.30,72112.0,-21266.0,179697.0,1952.00,-12.73,46.0,X-LC,3.35,21.0,-0.29,1.37,19.98,XY25,BTT,REFINERIES
65,SIEMENS,-4.17,-17.07,51.35,25.51,79248.0,-31765.0,154330.0,4671.50,29.61,42.0,H-LC,3.48,51.0,-0.40,1.18,13.65,AR,ATH,ELECTRICAL

In [19]:
# top 5 to accumulate based on lowest Gained%
df_tmp = df_portfolio_features[df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])].sort_values(by = 'Gained%', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
2,ABBOTINDIA,-0.87,-12.29,34.61,18.07,54293.0,-21985.0,156870.0,35195.00,-25.27,40.0,X-MC,10.83,58.0,-0.40,1.19,0.0,X40,ATH,PHARMA
3,ACC,-3.59,-39.37,188.33,74.81,306157.0,-105564.0,162564.0,3906.00,-57.01,22.0,X-SC,15.88,85.0,-0.34,1.24,0.0,XY24,BTT,CEMENT
6,ASIANPAINT,-3.01,-21.04,57.71,24.52,129154.0,-59641.0,223798.0,3460.25,-20.40,33.0,X-LC,8.42,30.0,-0.46,1.70,0.0,X40,ATH,PAINTS
12,BATAINDIA,-3.23,-57.98,221.79,35.20,119904.0,-74608.0,54062.0,2096.00,-29.10,14.0,X-SC,29.31,91.0,-0.62,0.41,0.0,X40,NTT,FOOTWEAR
20,COLPAL,-2.34,-28.00,96.55,41.51,183068.0,-73755.0,189610.0,3726.84,-12.80,27.0,X-MC,4.38,62.0,-0.40,1.44,0.0,XY25,ATH,FMCG

In [20]:
# top 5 to accumulate based on lowest CurrAlloc%
df_tmp = df_portfolio_features[df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])].sort_values(by = 'CurrAlloc%', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
58,RELAXO,-4.13,-64.54,329.51,52.31,169612.0,-93686.0,51474.0,1176.00,-62.25,20.0,X-SC,23.60,92.0,-0.55,0.39,0.00,X40N,NTT,FOOTWEAR
12,BATAINDIA,-3.23,-57.98,221.79,35.20,119904.0,-74608.0,54062.0,2096.00,-29.10,14.0,X-SC,29.31,91.0,-0.62,0.41,0.00,X40,NTT,FOOTWEAR
54,QUESS,-2.21,-26.74,137.38,73.90,107481.0,-28557.0,78236.0,424.00,-60.33,37.0,X-SC,19.94,80.0,-0.27,0.60,1.96,XY24,NTT,MISC
36,HONAUT,-1.98,-25.68,103.58,51.31,148456.0,-49513.0,143325.0,58357.33,-38.16,28.0,X-SC,14.76,90.0,-0.33,1.09,0.00,X40N,ATH,ELECTRICAL
51,MEDANTA,-2.78,-13.17,46.40,27.12,71115.0,-23252.0,153265.0,1486.00,-15.82,29.0,X-SC,10.56,87.0,-0.33,1.17,0.00,XY24,NTT,HEALTHCARE

In [21]:
# top 5 to accumulate based on CumlRnk
df_tmp = df_portfolio_features.sort_values(by = 'CumlRnk', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
45,ITC,-1.46,-21.09,50.87,19.06,136556.0,-71724.0,268442.0,452.00,-56.73,34.0,X-LC,17.57,1.0,-0.53,2.04,0.0,X40,NTT,FMCG
73,TCS,-3.15,-30.60,82.39,26.57,264887.0,-141769.0,321504.0,4311.59,-41.33,23.0,X-LC,16.32,2.0,-0.54,2.45,0.0,X40,ATH,IT
43,INFY,-3.34,-16.62,61.01,34.24,159164.0,-52006.0,260882.0,1972.00,-34.33,28.0,X-LC,14.54,3.0,-0.33,1.99,0.0,X40,NTT,IT
75,TMPV,-4.74,-29.58,93.96,36.58,235439.0,-105267.0,250574.0,600.00,-85.81,31.0,X-LC,4.44,4.0,-0.45,1.91,0.0,XY24,NTT,AUTO
33,HCLTECH,-2.77,-14.36,44.60,23.83,92401.0,-34747.0,207177.0,1908.19,-9.84,32.0,X-LC,11.24,8.0,-0.38,1.58,0.0,X40,ATH,IT

In [22]:
# top 5 for average up
df_tmp = df_portfolio_features[(df_portfolio_features['Dev%_200'] > 5)].sort_values(by = 'CurrAlloc%', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
1,ABB,-1.78,14.2,27.46,45.57,82044.0,37157.0,298776.0,7934.0,-26.59,58.0,H-MC,12.54,125.0,0.45,2.27,32.68,AR,NTT,ELECTRICAL

In [23]:
# top 5 RSP
df_tmp = df_portfolio_features.sort_values(by = 'RSP', ascending=False)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
1,ABB,-1.78,14.20,27.46,45.57,82044.0,37157.0,298776.0,7934.00,-26.59,58.0,H-MC,12.54,125.0,0.45,2.27,32.68,AR,NTT,ELECTRICAL
26,FINCABLES,-3.20,7.51,93.39,107.91,148243.0,11091.0,158735.0,1641.55,-3.09,49.0,M-SC,8.07,220.0,0.07,1.21,19.42,OX40N,ATH,CABLES
80,VALIANTORG,7.61,-46.96,228.37,74.15,198152.0,-76837.0,86768.0,838.00,-255.96,62.0,H-SC,29.26,145.0,-0.39,0.66,29.12,XR,NTT,CHEMICALS
69,SURYODAY,2.11,-26.07,66.41,23.03,87924.0,-46675.0,132396.0,216.00,44.74,51.0,H-SC,6.60,166.0,-0.53,1.01,29.40,XR,NTT,BANKS
47,JSWINFRA,-2.15,-13.39,34.43,16.43,66130.0,-29702.0,192072.0,342.00,-25.70,46.0,X-MC,11.50,61.0,-0.45,1.46,3.12,X40N,NTT,REALTY

In [24]:
# Top N allocation
df_tmp = df_portfolio_features.sort_values(by = 'CurrAlloc%', ascending=False)
top_n_values = [10, 25, 50]

sum_df = pd.DataFrame({
    'Top_N': top_n_values,
    'Sum_Alloc%': [df_tmp['CurrAlloc%'].head(n).sum() for n in top_n_values]
})

sum_df

   Top_N  Sum_Alloc%
0     10       20.64
1     25       45.53
2     50       77.92

In [25]:
# market-cap-wise allocation
df_tmp = df_portfolio_features[cols]
df_tmp.groupby(df_tmp['Conviction'].str[-2:])['CurrAlloc%'].sum().sort_values(ascending=False)

Conviction
SC    44.53
MC    30.18
LC    25.29
Name: CurrAlloc%, dtype: float64

In [26]:
# criteria-wise allocation
df_portfolio_features.groupby('Criteria')['CurrAlloc%'].sum().sort_values(ascending=False)

Criteria
XY24     26.93
X40      25.44
X40N     15.18
AR        9.17
XR        8.30
XY25      7.34
OX40N     6.85
SR        0.79
Name: CurrAlloc%, dtype: float64

In [27]:
# conviction-wise allocation
df_portfolio_features.groupby('Conviction')['CurrAlloc%'].sum().sort_values(ascending=False)

Conviction
X-LC    23.11
X-MC    22.70
H-SC    21.64
X-SC    12.21
M-SC    10.13
H-MC     5.06
M-MC     2.06
H-LC     1.18
M-LC     1.00
L-SC     0.55
L-MC     0.36
Name: CurrAlloc%, dtype: float64

In [28]:
# sector-wise stats
df_tmp = df_portfolio_features.groupby('Category')[['CurrAlloc%', 'Current', 'Current P/L', 'FTT Amt']].sum().sort_values(by=['Current', 'Current P/L'], ascending=False)
df_tmp['Current P/L%'] = round(df_tmp['Current P/L'] * 100 / df_tmp['Current'], 2)
df_tmp['FTT%'] = round(df_tmp['FTT Amt'] * 100 / df_tmp['Current'], 2)
cols = ['CurrAlloc%', 'Current P/L%', 'FTT%']
df_tmp[cols].sort_values(by=['CurrAlloc%'], ascending=False)

               CurrAlloc%  Current P/L%    FTT%
Category
FMCG                15.05        -26.26   71.09
FINANCE             13.16        -24.33   75.00
IT                  11.63        -47.71  122.87
MISC                 6.95        -46.91  110.73
ELECTRICAL           6.61        -11.46   54.14
PAINTS               5.06        -48.41   74.18
INSURANCE            4.76         -8.56   45.71
BANKS                4.71        -24.54   87.76
PHARMA               4.13         -8.22   42.28
AUTO                 3.65        -36.78   91.06
AC                   2.10        -15.78   47.17
HEALTHCARE           1.90        -43.54   81.00
DURABLES             1.87        -57.48   95.79
TRAVEL               1.82        -86.73  180.23
FOOTWEAR             1.77        -89.26  165.15
BREWERIES            1.69         -5.33   27.21
APPARELS             1.67        -22.65   64.49
REALTY               1.46        -15.46   34.43
CERAMICS             1.40        -67.70  118.64
REFINERIES           1.37        -11.83   40.13
CEMENT               1.24        -64.94  188.33
CABLES               1.21          6.99   93.39
ENGINEERING          1.08        -70.21  148.06
CHEMICALS            1.08        -85.95  237.66
JEWELLERY            1.07       -126.58  205.30
ENTERTAINMENT        0.77        -91.45  205.64
TEXTILES             0.44        -59.55  105.04
HOTELS               0.35       -144.79  231.13

In [29]:
# money to be made criteria-wise
df_portfolio_features.groupby('Criteria')['FTT Amt'].agg(['sum', 'count']).sort_values(by='sum', ascending=False)

                sum  count
Criteria
XY24      4061646.0     21
X40       1832979.0     16
XR        1401043.0     12
AR        1366784.0     10
X40N      1306040.0     10
OX40N      893645.0     10
XY25       475268.0      5
SR         315796.0      2

In [30]:
# money to be made conviction-wise
df_portfolio_features.groupby('Conviction')['FTT Amt'].agg(['sum', 'count']).sort_values(by='sum', ascending=False)

                  sum  count
Conviction
H-SC        3948992.0     24
X-MC        1751738.0     15
X-LC        1740741.0     13
M-SC        1588792.0     14
X-SC        1580027.0     10
H-MC         413129.0      3
L-SC         218144.0      2
M-LC         160805.0      1
M-MC         115658.0      2
H-LC          79248.0      1
L-MC          55927.0      1

In [31]:
# money to be made criteria and conviction-wise
df_portfolio_features.groupby(['Conviction', 'Criteria'])['FTT Amt'].agg(['sum', 'count']).sort_values(by='sum', ascending=False)

                           sum  count
Conviction Criteria
H-SC       XY24      1372095.0      6
           AR         983355.0      5
X-LC       X40        938616.0      7
M-SC       XY24       928469.0      6
H-SC       XR         882312.0      7
X-SC       XY24       863200.0      4
X-MC       X40        685083.0      7
           X40N       534279.0      4
X-SC       X40N       507547.0      4
H-SC       OX40N      395434.0      4
M-SC       OX40N      387281.0      5
X-LC       XY24       381407.0      2
H-SC       SR         315796.0      2
X-MC       XY24       275014.0      2
X-LC       X40N       264214.0      2
X-MC       XY25       257362.0      2
H-MC       XY24       241461.0      1
X-SC       X40        209280.0      2
M-SC       XR         194785.0      2
H-MC       AR         171668.0      2
M-LC       XR         160805.0      1
X-LC       XY25       156504.0      2
L-SC       OX40N      110930.0      1
           XR         107214.0      1
H-LC       AR          79248.0      1
M-SC       AR          78257.0      1
M-MC       XY25        61402.0      1
L-MC       XR          55927.0      1
M-MC       AR          54256.0      1

In [32]:
# notebook execution time

end_time = time.time()
execution_time = round(end_time - start_time, 0)
print(f"Notebook execution time: {execution_time} seconds")

Notebook execution time: 25.0 seconds