<a href="https://colab.research.google.com/github/ankit-rathi/Quantvesting_v2/blob/main/myStocks_Portfolio_Analysis.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
'''
!pip install pandas==2.2.2 -qq
!pip install pyxirr -qq
!pip install ta -qq
!pip install yfinance==0.2.59 -qq
'''

'\n!pip install pandas==2.2.2 -qq\n!pip install pyxirr -qq\n!pip install ta -qq\n!pip install yfinance==0.2.59 -qq\n'

In [2]:
# import libraries

import numpy as np
import pandas as pd
import datetime
import warnings
warnings.filterwarnings('ignore')
import yfinance as yfin
import ta
import matplotlib.pyplot as plt
import requests

In [3]:
# notebook start time
import time
import datetime
import pytz

start_time = time.time()

# function to print date timestamp
def print_date_time():
  tz_NY = pytz.timezone('Asia/Kolkata')
  datetime_NY = datetime.datetime.now(tz_NY)
  print("Run date time (IST):", datetime_NY.strftime("%Y-%m-%d %H:%M:%S"))

In [4]:
# function to get booked and reserved amount
def get_amt():
  # fetch the JSON data from the URL
  url = "https://raw.githubusercontent.com/ankit-rathi/Tradevesting_v1/main/data/myPortfolioAmts.json"
  response = requests.get(url)
  pf_amts = response.json()  # parse the JSON data

  # extract values from the JSON
  py_booked_amt_dm = pf_amts["py_booked_amt_dm"]
  py_booked_amt_sv = pf_amts["py_booked_amt_sv"]
  cy_booked_amt_dm = pf_amts["cy_booked_amt_dm"]
  cy_booked_amt_sv = pf_amts["cy_booked_amt_sv"]
  reserve_amt_dm = pf_amts["reserve_amt_dm"]
  reserve_amt_sv = pf_amts["reserve_amt_sv"]

  # perform calculations
  py_booked_amt = py_booked_amt_dm + py_booked_amt_sv
  cy_booked_amt = cy_booked_amt_dm + cy_booked_amt_sv
  reserve_amt = reserve_amt_dm + reserve_amt_sv
  total_booked_amt = py_booked_amt + cy_booked_amt

  return total_booked_amt, reserve_amt, cy_booked_amt, py_booked_amt

gen_output = 0

In [5]:
# function to format the amount
def format_amt(number):
    abs_number = abs(number)

    if abs_number >= 1_00_00_000:  # Crores
        formatted_amt = f"{number / 1_00_00_000:.2f} C"
    elif abs_number >= 1_00_000:  # Lakhs
        formatted_amt = f"{number / 1_00_000:.2f} L"
    elif abs_number >= 1_000:  # Thousands
        formatted_amt = f"{number / 1_000:.2f} K"
    else:
        formatted_amt = f"{number:.2f}"

    return formatted_amt

# function to set start and end date
def get_start_end_date():
  start_date = (datetime.date.today() + datetime.timedelta(days=-365)).strftime('%Y-%m-%d')
  end_date = (datetime.date.today() + datetime.timedelta(days=1)).strftime('%Y-%m-%d')
  return start_date, end_date

# function to fetch my portfolio csv
def get_mypfs_df():
  mypfs_df = pd.read_csv('https://raw.githubusercontent.com/ankit-rathi/Tradevesting_v1/main/data/myPortfolioStocks.csv')
  return mypfs_df

# function to fetch my prospects csv
def get_mypps_df():
  mypps_df = pd.read_csv('https://raw.githubusercontent.com/ankit-rathi/Tradevesting_v1/main/data/myProspectsScrips.csv')
  return mypps_df

# function to fetch screener data
def get_myscreen_df():
  myscreen_df = pd.read_csv('https://raw.githubusercontent.com/ankit-rathi/Tradevesting_v1/main/data/myScreenerDB.csv')
  return myscreen_df

# function to fetch momentum data
def get_myinvmt_df():
  myinvmt_df = pd.read_csv('https://raw.githubusercontent.com/ankit-rathi/Tradevesting_v1/main/data/myInvestments.csv')
  return myinvmt_df

# function to get the stock ids
def get_stock_ids(df_pf):
  stock_n100 = df_pf['Symbol'].unique()

  exclude = ['CADILAHC','MMTC', 'MASFIN']

  stock_ids = df_pf[~df_pf['Symbol'].isin(exclude) ]['Symbol'].unique()

  #mypf = mypf[mypf.Forecast.notnull()]
  #stock_ids = mypf['Symbol'].unique()

  #stock_ids.sort()
  return stock_ids

# get features from screener data
def get_screener_features():
  myscreen_df = get_myscreen_df()
  cols = ['Symbol', 'EPS', 'MedPE', 'ROCE%', 'ROE%', 'CapType']
  return myscreen_df[cols]

# get relative strength
def get_relative_strength(stock_list):

    # Dictionary to store stock tickers and their corresponding percentage price change
    stock_changes = {}

    # Loop through each stock and fetch its price data
    for stock in stock_list:
        try:
            # Download the stock data for the given date range
            stock_data = yfin.Ticker(stock + '.NS').history(period='1mo', interval='1d')[map(str.title, ['open', 'close', 'low', 'high', 'volume'])]

            # Calculate the percentage change for the stock
            if len(stock_data) > 0:
                start_price = stock_data['Close'].iloc[0]
                end_price = stock_data['Close'].iloc[-1]
                percent_change = round(((end_price - start_price) / start_price) * 100, 2)
                stock_changes[stock] = percent_change
            else:
                stock_changes[stock] = np.nan  # If no data is available, set to NaN

        except Exception as e:
            print(f"Error fetching data for {stock}: {e}")
            stock_changes[stock] = np.nan

    # Create a DataFrame with stock tickers and their percentage changes
    df = pd.DataFrame(list(stock_changes.items()), columns=['Symbol', 'Percent_Change'])

    # Drop any stocks with missing data (NaN values)
    df = df.dropna()

    # Calculate the percentile rank based on percentage change
    df['RSP'] = round(df['Percent_Change'].rank(pct=True) * 100, 2)
    cols = ['Symbol', 'RSP']
    df = df[cols]
    # Sort by percentile rank (optional)
    df = df.sort_values(by='RSP', ascending=False).reset_index(drop=True)

    return df

In [6]:
# function to get stock technicals
def stock_prec_dev(stock_symbol):
    #stock_symbol = 'ULTRACEMCO.NS'
    short_window = 20
    mid_window = 50
    long_window = 200
    moving_avg = 'SMA'

    start = datetime.datetime(*map(int, start_date.split('-')))
    end = datetime.datetime(*map(int, end_date.split('-')))

    stock_df = yfin.Ticker(stock_symbol + '.NS').history(period='max', interval='1d')[map(str.title, ['open', 'close', 'low', 'high', 'volume'])]

    stock_df['Max'] = round(max(stock_df['Close']),2)
    stock_df = stock_df[(stock_df.index <= end_date) & (stock_df.index >= start_date)]
    stock_df['200_SMA'] = round(stock_df['Close'].rolling(window = 200, min_periods = 1).mean(),0)
    stock_df['Dev%_200'] = round((stock_df['Close'] - stock_df['200_SMA'])*100/stock_df['200_SMA'],2)
    stock_df.dropna(axis = 0, inplace = True) # remove any null rows

    stock_df['20_SMA'] = stock_df['Close'].rolling(window=20).mean()
    stock_df['50_SMA'] = stock_df['Close'].rolling(window=50).mean()
    stock_df['Symbol'] = stock_symbol

    stock_df['Close'] = round(stock_df['Close'],2)
    stock_df['Min'] = round(min(stock_df['Close']),2)
    stock_df['RSI_14'] = ta.momentum.RSIIndicator(close=stock_df['Close'], window=14).rsi()
    stock_df['RSI_14'] = round(stock_df['RSI_14'],0)
    stock_df['Prev_Close'] = stock_df['Close'].shift(1)
    stock_df.drop(['Open', 'Low', 'High', 'Volume'], axis=1, inplace=True)
    stock_df = stock_df.tail(1)

    max_SMA = max(stock_df['20_SMA'].item(), stock_df['50_SMA'].item(), stock_df['200_SMA'].item())
    min_SMA = min(stock_df['20_SMA'].item(), stock_df['50_SMA'].item(), stock_df['200_SMA'].item())
    ABS_Spread = max_SMA - min_SMA
    stock_df['Spread%'] = round((ABS_Spread / stock_df['200_SMA'].item()) * 100,2)

    return stock_df

# function to compute stock attributes
def get_common_features(stock_ids, df_mypf):

  df_prec_dev = pd.DataFrame()
  df_tmp = get_screener_features()
  df_rs = get_relative_strength(stock_ids)

  for stock_id in stock_ids:
      tmp = stock_prec_dev(stock_id)
      tmp = tmp.reset_index()
      df_prec_dev = pd.concat([df_prec_dev, tmp], ignore_index = True)
  df_prec_dev = pd.merge(df_prec_dev, df_mypf, on= 'Symbol')
  df_prec_dev = pd.merge(df_prec_dev, df_tmp, on= 'Symbol', how='left')
  df_prec_dev = pd.merge(df_prec_dev, df_rs, on= 'Symbol', how='left')
  #print(df_prec_dev.columns)
  df_prec_dev['Curr_PE'] = round(df_prec_dev['Close']/df_prec_dev['EPS'],1)
  df_prec_dev['Dev%_PE'] = round((df_prec_dev['Curr_PE'] - df_prec_dev['MedPE'])*100/df_prec_dev['MedPE'],2)
  df_prec_dev['Conviction'] = df_prec_dev['Conviction'] + '-' + df_prec_dev['CapType']
  return df_prec_dev

# function to arrange stock features
def arrange_features(df_stocks, common_cols, diff_cols):
  df_stocks_common = df_stocks[common_cols].drop_duplicates()
  df_stocks_diff = df_stocks[diff_cols]
  df_stocks_diff['Investment'] = df_stocks_diff['AvgCost'] * df_stocks_diff['Shares']
  df_stocks_diff = df_stocks_diff.groupby(['Symbol'])[['Shares', 'Investment']].aggregate(['sum']).reset_index()
  df_stocks_diff.columns = ['Symbol', 'Shares', 'Investment']
  df_stocks_diff['AvgCost'] = round(df_stocks_diff['Investment']/df_stocks_diff['Shares'],2)
  df_stocks = pd.merge(df_stocks_diff, df_stocks_common, on='Symbol')
  return df_stocks

# plot fact distribution across dimension
def plot_pie_chart(df, dimension, fact):
  # grouping the data by category and calculating the sum of fact for each type
  grouped_data = df.groupby(dimension)[fact].sum()

  # sorting the grouped data in descending order
  grouped_data = grouped_data.sort_values(ascending=False)

  # creating a pie chart
  grouped_data.plot.pie(autopct='%1.1f%%', startangle=90, figsize=(6, 6))

  # adding a title and displaying the plot
  plt.title(f'{dimension} {fact} Distribution')
  plt.ylabel('')  # To hide the y-label
  plt.show()

In [7]:
# function to get portfolio features

def get_portfolio_features(df_common_features):

  print_date_time()
  print('-------------------')

  #df_common_features["Target"] = df_common_features["Target"].fillna(df_common_features["Max"])
  df_common_features['NTT'] = np.where(df_common_features['Strategy']== 'NTT', df_common_features["Target"], df_common_features['Max'])
  df_common_features['LTT'] = np.where(df_common_features['Strategy']== 'BTT', df_common_features["Target"], df_common_features['Max'])
  df_common_features['BOL'] = df_common_features['Min']

  tmp_df = df_common_features[df_common_features['Symbol'].isin(mypf_df[mypf_df['InPortfolio'] != 'NA'].Symbol.values)]
  print('qualified stocks: '+str(len(tmp_df['Symbol'].unique())))
  tmp_df1 = tmp_df[tmp_df['LatestQtr'] == 1]
  print('with latest results: '+str(len(tmp_df1['Symbol'].unique())))
  tmp_df1 = tmp_df1[tmp_df1['StarStock'] == 1]
  print('still star stocks: '+str(len(tmp_df1['Symbol'].unique())))
  tmp_df['Investment'] = tmp_df['AvgCost'] * tmp_df['Shares']
  tmp_df['Current'] = round(tmp_df['Close'] * tmp_df['Shares'],0)
  tmp_df['Previous'] = tmp_df['Prev_Close'] * tmp_df['Shares']
  tmp_df['EstimatedST'] = tmp_df['NTT'] * tmp_df['Shares']
  tmp_df['EstimatedLT'] = tmp_df['LTT'] * tmp_df['Shares']
  tmp_df['Current P/L'] = round((tmp_df['Current'] - tmp_df['Investment']),0)
  tmp_df['Today P/L%'] = round((tmp_df['Current'] - tmp_df['Previous'])*100/tmp_df['Previous'],2)
  tmp_df['Current P/L%'] = round((tmp_df['Current'] - tmp_df['Investment'])*100/tmp_df['Investment'],2)
  tmp_df['EstimatedST P/L%'] = round((tmp_df['EstimatedST'] - tmp_df['Investment'])*100/tmp_df['Investment'],2)
  tmp_df['EstimatedLT P/L%'] = round((tmp_df['EstimatedLT'] - tmp_df['Investment'])*100/tmp_df['Investment'],2)
  tmp_df['NTT%'] = round((tmp_df['NTT'] - tmp_df['Close'])*100/tmp_df['Close'],2)
  tmp_df['LTT%'] = round((tmp_df['LTT'] - tmp_df['Close'])*100/tmp_df['Close'],2)
  tmp_df['Gained%'] = round((tmp_df['Close'] - tmp_df['BOL'])*100/tmp_df['BOL'],2)
  investment = round(sum(tmp_df['AvgCost']*tmp_df['Shares']),0)
  current = round(sum(tmp_df['Close']*tmp_df['Shares']),0)
  tmp_df['InitAlloc%'] = round(tmp_df['Investment']*100/investment,2)
  tmp_df['CurrAlloc%'] = round(tmp_df['Current']*100/current,2)
  tmp_df['FTT'] = tmp_df['LTT']
  tmp_df.loc[tmp_df['Strategy'] == 'NTT', 'FTT'] = tmp_df['NTT']
  tmp_df['FTT%'] = tmp_df['LTT%']
  tmp_df.loc[tmp_df['Strategy'] == 'NTT', 'FTT%'] = tmp_df['NTT%']
  tmp_df['FTT Amt'] = round(tmp_df['FTT%'] * tmp_df['Current']/100,0)
  tmp_df['OTT%'] = round((tmp_df['FTT'] - tmp_df['AvgCost'])*100/tmp_df['AvgCost'],2)
  tmp_df['RRR Ind'] = round(tmp_df['Current P/L']/tmp_df['FTT Amt'],2)
  tmp_df['Risk Ind'] = round(tmp_df['Current P/L%']*tmp_df['CurrAlloc%'],0)

  return tmp_df

# function to print portfolio features
def print_portfolio_stats(df_portfolio_features, myinvmt_df):
  from pyxirr import xirr

  total_booked_amt, reserve_amt, cy_booked_amt, py_booked_amt = get_amt()

  dates = myinvmt_df['Date'].values
  dates = np.append(dates, datetime.date.today().strftime('%d-%b-%y'))
  investment = myinvmt_df['Investment'].values
  dates= pd.to_datetime(dates)

  current = round(sum(df_portfolio_features['Close']*df_portfolio_features['Shares']),0) + reserve_amt
  investment_xirr = np.append(investment, current)
  cagr = round(xirr(pd.DataFrame({"dates": dates, "amounts": investment_xirr}))*100,2)

  investment = -sum(investment)
  invested = round(sum(df_portfolio_features['AvgCost']*df_portfolio_features['Shares']),0) + reserve_amt
  previous = round(sum(df_portfolio_features['Prev_Close']*df_portfolio_features['Shares']),0) + reserve_amt
  cy_invested = investment + py_booked_amt

  today_pnl_amount = current-previous
  today_pnl_percentage = round((current-previous)*100/previous,2)

  curr_pnl_amount = current-invested
  curr_pnl_percentage = round((curr_pnl_amount)*100/(cy_invested),2)

  cy_pnl_amount = cy_booked_amt + curr_pnl_amount
  cy_pnl_percentage = round((cy_pnl_amount)*100/cy_invested,2)

  overall_pnl_amount = total_booked_amt + curr_pnl_amount
  overall_pnl_percentage = round((overall_pnl_amount)*100/investment,2)

  estimate_st = round(sum(df_portfolio_features['FTT']*df_portfolio_features['Shares']),0)  + reserve_amt
  est_st_pnl_amount = estimate_st-current
  est_st_pnl_percentage = round((est_st_pnl_amount)*100/current,2)

  estimate_lt = round(sum(df_portfolio_features['LTT']*df_portfolio_features['Shares']),0)  + reserve_amt
  est_lt_pnl_amount = estimate_lt-current
  est_lt_pnl_percentage = round((est_lt_pnl_amount)*100/current,2)

  total_profit = round(sum(df_portfolio_features[df_portfolio_features['Current P/L%'] > 0]['Current']) - sum(df_portfolio_features[df_portfolio_features['Current P/L%'] > 0]['Investment']),0)
  total_loss = round(sum(df_portfolio_features[df_portfolio_features['Current P/L%'] < 0]['Current']) - sum(df_portfolio_features[df_portfolio_features['Current P/L%'] < 0]['Investment']),0)

  cy_booked_percentage = round((cy_booked_amt)*100/current,2)
  py_booked_percentage = round((py_booked_amt)*100/investment,2)
  total_booked_percentage = round((total_booked_amt)*100/investment,2)

  print('-------------------')
  print('Initial Investment: ', format_amt(investment))
  print('CY Investment: ', format_amt(cy_invested))
  print('Reserve: ', format_amt(reserve_amt))
  print('Current: ',  format_amt(current))
  print('-------------------')
  print('Today PnL: '+ '{} ({}%)'.format(format_amt(today_pnl_amount), today_pnl_percentage))
  print('Current PnL: '+ '{} ({}%)'.format(format_amt(curr_pnl_amount), curr_pnl_percentage))
  print('CY Booked + Current PnL: '+ '{} ({}%)'.format(format_amt(cy_pnl_amount), cy_pnl_percentage))
  print('-------------------')
  print('Total profit: ', format_amt(total_profit))
  print('Total loss: ', format_amt(total_loss))
  print('-------------------')
  print('Total Booked + Current PnL: '+ '{} ({}%)'.format(format_amt(overall_pnl_amount), overall_pnl_percentage))
  print('Total Booked PnL: '+ '{} ({}%)'.format(format_amt(total_booked_amt), total_booked_percentage))
  print('Curr Year Booked PnL: '+ '{} ({}%)'.format(format_amt(cy_booked_amt), cy_booked_percentage))
  print('Prev Year Booked PnL: '+ '{} ({}%)'.format(format_amt(py_booked_amt), py_booked_percentage))
  print('===================')
  print('Est FTT: ',  format_amt(estimate_st))
  print('Est FTT PnL: '+ '{} ({}%)'.format(format_amt(est_st_pnl_amount), est_st_pnl_percentage))

  print('===================')
  print('Deployed: ', format_amt(investment))

  print('Current: ', format_amt(current))

  print('CAGR/XIRR %: '+'{}%'.format(cagr))

In [8]:
# get start and end date
start_date, end_date = get_start_end_date()

# get portfolio and prospects data
mypfs_df = get_mypfs_df()
mypps_df = get_mypps_df()
myinvmt_df = get_myinvmt_df()

# merge above datasets
mypf_df = pd.merge(mypfs_df, mypps_df, on="Symbol")

# seggregate dm and sv portfolio
dm_pf = mypf_df[mypf_df['InPortfolio'] == 'DM']
sv_pf = mypf_df[mypf_df['InPortfolio'] == 'SV']

# build portfolio stock dataframe
dm_stocks = get_stock_ids(dm_pf)
sv_stocks = get_stock_ids(sv_pf)
df_stocks = pd.concat([dm_pf,sv_pf], ignore_index = True)

# arrange common and diff stock features
common_cols = ['Symbol', 'Target', 'Criteria', 'Strategy', 'CumlRnk', 'LatestQtr', 'StarStock', 'Conviction', 'Category', 'InFolio', 'XIRR', 'MBQ']
diff_cols = ['Symbol', 'AvgCost', 'Shares']
df_stocks = arrange_features(df_stocks, common_cols, diff_cols)

# get common features
stock_ids = df_stocks['Symbol'].values
df_common_features = get_common_features(stock_ids, df_stocks)

df_common_features.reset_index(drop=True, inplace=True)
df_common_features.drop(['Date'], axis=1, inplace=True)
# get and print portfolio features
df_portfolio_features = get_portfolio_features(df_common_features)

print_portfolio_stats(df_portfolio_features, myinvmt_df)

df = df_portfolio_features
#plot_pie_chart(df, 'CapType', 'Current')
list_ox40n = list(df[df['MBQ'].str.contains('OX40N', na=False)]['Symbol'].values)

Run date time (IST): 2026-04-06 10:14:45
-------------------
qualified stocks: 86
with latest results: 26
still star stocks: 16
-------------------
Initial Investment:  1.36 C
CY Investment:  1.62 C
Reserve:  1.61 K
Current:  1.29 C
-------------------
Today PnL: -48.30 K (-0.37%)
Current PnL: -48.18 L (-29.65%)
CY Booked + Current PnL: -32.29 L (-19.87%)
-------------------
Total profit:  53.52 K
Total loss:  -48.72 L
-------------------
Total Booked + Current PnL: -5.31 L (-3.92%)
Total Booked PnL: 42.87 L (31.64%)
Curr Year Booked PnL: 15.89 L (12.32%)
Prev Year Booked PnL: 26.98 L (19.91%)
===================
Est FTT:  2.48 C
Est FTT PnL: 1.19 C (92.24%)
===================
Deployed:  1.36 C
Current:  1.29 C
CAGR/XIRR %: -2.39%

In [9]:
# top 5 near their targets
cols = ['Symbol', 'Today P/L%', 'Current P/L%', 'FTT%', 'OTT%', 'FTT Amt', 'Current P/L', 'Current', 'FTT', 'Dev%_PE', 'RSI_14','Conviction', 'Spread%',  'CumlRnk', 'RRR Ind', 'CurrAlloc%', 'Gained%', 'Criteria', 'Strategy', 'Category']
df_tmp = df_portfolio_features[~df_portfolio_features['Symbol'].isin(['ENRIN','BLUSPRING','DIGITIDE'])]
df_tmp = df_tmp.sort_values(by = 'FTT Amt', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
50,MASFIN,0.17,-9.34,34.09,21.57,30282.0,-9150.0,88830.0,397.04,-21.86,45.0,H-SC,4.96,167.0,-0.30,0.69,21.16,XR,ATH,FINANCE
77,TTKPRESTIG,-0.06,-42.38,73.70,0.09,42799.0,-42705.0,58072.0,770.00,34.69,38.0,M-SC,22.38,250.0,-1.00,0.45,3.41,OX40N,NTT,DURABLES
67,SONACOMS,1.35,-12.94,59.77,39.09,52639.0,-13090.0,88069.0,804.02,-31.00,50.0,M-MC,6.98,193.0,-0.25,0.68,24.59,AR,ATH,AUTO
2,ABBOTINDIA,-1.07,-12.76,35.34,18.07,55141.0,-22825.0,156030.0,35195.00,-25.68,44.0,X-MC,10.66,58.0,-0.41,1.21,2.04,X40,ATH,PHARMA
24,DMART,1.19,6.11,22.14,29.60,58638.0,15252.0,264852.0,5391.45,-10.50,75.0,X-LC,6.06,14.0,0.26,2.05,21.06,X40N,ATH,FMCG

In [10]:
# top 5 today
df_tmp = df_portfolio_features.sort_values(by = 'Today P/L%', ascending=False)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
19,COFFEEDAY,3.32,-61.53,251.65,35.27,109921.0,-69869.0,43680.0,80.00,-69.82,39.0,L-SC,32.29,266.0,-0.64,0.34,7.72,XR,NTT,HOTELS
80,VALIANTORG,2.71,-50.41,251.16,74.15,203786.0,-82467.0,81138.0,838.00,-245.98,53.0,H-SC,27.11,145.0,-0.40,0.63,20.74,XR,NTT,CHEMICALS
69,SURYODAY,2.63,-26.40,67.17,23.03,88526.0,-47277.0,131794.0,216.00,42.54,52.0,H-SC,5.33,166.0,-0.53,1.02,19.25,XR,NTT,BANKS
67,SONACOMS,1.35,-12.94,59.77,39.09,52639.0,-13090.0,88069.0,804.02,-31.00,50.0,M-MC,6.98,193.0,-0.25,0.68,24.59,AR,ATH,AUTO
84,WIPRO,1.27,-19.04,112.78,72.27,154718.0,-32262.0,137186.0,420.00,-26.90,48.0,M-LC,18.12,98.0,-0.21,1.06,5.25,XR,NTT,IT

In [11]:
# bottom 5 today
df_tmp = df_portfolio_features.sort_values(by = 'Today P/L%', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
68,STARHEALTH,-3.81,-12.53,68.36,47.26,168089.0,-35235.0,245888.0,761.0,38.15,45.0,H-SC,0.36,173.0,-0.21,1.91,30.54,XY24,NTT,INSURANCE
70,SYMPHONY,-2.90,-45.87,84.67,-0.03,78441.0,-78498.0,92643.0,1306.0,-56.52,37.0,M-SC,17.70,205.0,-1.00,0.72,2.75,OX40N,NTT,DURABLES
0,5PAISA,-2.34,-46.94,112.77,12.90,130749.0,-102553.0,115943.0,593.0,70.67,43.0,H-SC,16.85,170.0,-0.78,0.90,11.89,OX40N,NTT,FINANCE
12,BATAINDIA,-2.34,-58.60,226.58,35.20,120697.0,-75401.0,53269.0,2096.0,-30.11,37.0,X-SC,34.25,91.0,-0.62,0.41,5.65,X40,NTT,FOOTWEAR
59,RELIANCE,-2.16,-15.18,47.73,25.30,81355.0,-30515.0,170448.0,1952.0,-17.34,36.0,X-LC,3.96,21.0,-0.38,1.32,13.80,XY25,BTT,REFINERIES

In [12]:
# top 5 to exit based on CumlRnk
df_tmp = df_portfolio_features[~df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])]
df_tmp = df_tmp[(df_tmp['Current P/L%'] > -1) & (df_tmp['Current P/L%'] < 1)].sort_values(by = 'CumlRnk', ascending=False)
df_tmp[cols].head()

Empty DataFrame
Columns: [Symbol, Today P/L%, Current P/L%, FTT%, OTT%, FTT Amt, Current P/L, Current, FTT, Dev%_PE, RSI_14, Conviction, Spread%, CumlRnk, RRR Ind, CurrAlloc%, Gained%, Criteria, Strategy, Category]
Index: []

In [13]:
# OX40N stocks to exit
df_tmp = df_portfolio_features[(df_portfolio_features['Symbol'].isin(list_ox40n))].sort_values(by = 'Current P/L%', ascending=False)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
26,FINCABLES,0.18,1.20,105.44,107.91,157551.0,1778.0,149422.0,1641.55,-9.18,44.0,M-SC,5.00,220.0,0.01,1.16,12.42,OX40N,ATH,CABLES
66,SIS,-1.34,-34.78,85.92,21.26,62223.0,-38612.0,72420.0,528.00,1694.30,46.0,H-SC,14.90,168.0,-0.62,0.56,7.68,OX40N,NTT,MISC
72,TATAELXSI,0.55,-38.54,114.82,32.03,93034.0,-50809.0,81026.0,9161.00,-23.05,46.0,H-SC,21.69,158.0,-0.55,0.63,7.24,OX40N,NTT,IT
18,CERA,-0.81,-39.34,104.22,23.89,111211.0,-69195.0,106708.0,9475.00,-41.53,45.0,H-SC,19.27,153.0,-0.62,0.83,2.55,OX40N,NTT,CERAMICS
48,KANSAINER,-1.97,-41.57,94.20,13.47,148433.0,-112095.0,157572.0,340.00,-49.75,43.0,H-SC,23.53,162.0,-0.76,1.22,10.06,XY24,NTT,PAINTS

In [14]:
# top 5 to book for rotation
df_tmp = df_portfolio_features[(df_portfolio_features['Current P/L%'] > 20) ].sort_values(by = 'CumlRnk', ascending=False)
df_tmp[cols].head()

Empty DataFrame
Columns: [Symbol, Today P/L%, Current P/L%, FTT%, OTT%, FTT Amt, Current P/L, Current, FTT, Dev%_PE, RSI_14, Conviction, Spread%, CumlRnk, RRR Ind, CurrAlloc%, Gained%, Criteria, Strategy, Category]
Index: []

In [15]:
# top 5 to monitor for exit
df_tmp = df_portfolio_features[~df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])]
df_tmp = df_tmp[(df_tmp['Current P/L%'] > 0) ].sort_values(by = 'Dev%_PE', ascending=False)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
26,FINCABLES,0.18,1.20,105.44,107.91,157551.0,1778.0,149422.0,1641.55,-9.18,44.0,M-SC,5.00,220.0,0.01,1.16,12.42,OX40N,ATH,CABLES
1,ABB,1.12,13.95,27.75,45.57,82724.0,36485.0,298104.0,7934.00,-26.78,55.0,H-MC,13.65,125.0,0.44,2.31,32.38,AR,NTT,ELECTRICAL

In [16]:
# top 5 to book for rotation from weak conviction
df_tmp = df_portfolio_features[~df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])]
df_tmp = df_tmp[~df_tmp['Criteria'].isin(['XY25','XY24','X40', 'X40N'])].sort_values(by = 'RRR Ind', ascending=False)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
1,ABB,1.12,13.95,27.75,45.57,82724.0,36485.0,298104.0,7934.00,-26.78,55.0,H-MC,13.65,125.0,0.44,2.31,32.38,AR,NTT,ELECTRICAL
26,FINCABLES,0.18,1.20,105.44,107.91,157551.0,1778.0,149422.0,1641.55,-9.18,44.0,M-SC,5.00,220.0,0.01,1.16,12.42,OX40N,ATH,CABLES
40,INDIAMART,-1.88,-14.87,142.84,106.72,149972.0,-18343.0,104993.0,4810.62,-61.52,39.0,H-SC,13.04,140.0,-0.12,0.81,5.03,AR,ATH,MISC
84,WIPRO,1.27,-19.04,112.78,72.27,154718.0,-32262.0,137186.0,420.00,-26.90,48.0,M-LC,18.12,98.0,-0.21,1.06,5.25,XR,NTT,IT
85,ZYDUSLIFE,-1.01,-9.79,50.34,35.63,95176.0,-20508.0,189066.0,1286.17,-21.62,39.0,H-MC,5.76,120.0,-0.22,1.47,5.25,AR,ATH,PHARMA

In [17]:
# top 5 to accumulate based on lowest RSI_14
df_tmp = df_portfolio_features[df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])].sort_values(by = 'RSI_14', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
38,ICICIPRULI,-0.04,-16.73,57.00,30.73,93505.0,-32962.0,164043.0,790.00,-39.14,19.0,X-MC,9.56,78.0,-0.35,1.27,0.00,X40,ATH,INSURANCE
37,ICICIGI,0.01,-10.52,33.36,19.34,59736.0,-21043.0,179066.0,2252.93,-24.74,28.0,X-MC,6.35,66.0,-0.35,1.39,0.01,X40,ATH,INSURANCE
32,HAVELLS,-0.45,-24.75,75.52,32.08,186393.0,-81178.0,246813.0,2062.85,-29.22,29.0,X-MC,11.67,63.0,-0.44,1.91,0.00,X40,ATH,ELECTRICAL
21,DABUR,0.07,-18.36,76.03,43.70,153970.0,-45556.0,202512.0,735.00,-25.93,31.0,X-MC,11.63,70.0,-0.30,1.57,1.73,XY24,BTT,FMCG
34,HDFCBANK,-0.47,-10.59,43.57,28.37,91499.0,-24880.0,210005.0,1073.00,-23.99,32.0,X-LC,16.04,26.0,-0.27,1.63,2.16,X40,BTT,BANKS

In [18]:
# top 5 to accumulate based on Spread and CumlRnk
df_tmp = df_portfolio_features[df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])]
df_tmp = df_tmp[(df_tmp['CumlRnk'] < 100)].sort_values(by = 'Spread%', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
65,SIEMENS,-0.63,-19.20,55.33,25.51,83200.0,-35725.0,150370.0,4671.50,26.28,43.0,H-LC,0.55,51.0,-0.43,1.17,10.74,AR,ATH,ELECTRICAL
82,VOLTAS,-1.34,-4.65,52.28,45.20,95578.0,-8922.0,182820.0,1856.00,9.21,32.0,X-MC,3.53,79.0,-0.09,1.42,1.83,XY25,NTT,AC
78,UNITDSPR,0.07,-10.23,34.53,20.77,72577.0,-23960.0,210184.0,1644.00,-20.34,37.0,X-MC,3.94,64.0,-0.33,1.63,0.26,X40N,NTT,BREWERIES
59,RELIANCE,-2.16,-15.18,47.73,25.30,81355.0,-30515.0,170448.0,1952.00,-17.34,36.0,X-LC,3.96,21.0,-0.38,1.32,13.80,XY25,BTT,REFINERIES
24,DMART,1.19,6.11,22.14,29.60,58638.0,15252.0,264852.0,5391.45,-10.50,75.0,X-LC,6.06,14.0,0.26,2.05,21.06,X40N,ATH,FMCG

In [19]:
# top 5 to accumulate based on lowest Gained%
df_tmp = df_portfolio_features[df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])].sort_values(by = 'Gained%', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
38,ICICIPRULI,-0.04,-16.73,57.00,30.73,93505.0,-32962.0,164043.0,790.00,-39.14,19.0,X-MC,9.56,78.0,-0.35,1.27,0.00,X40,ATH,INSURANCE
47,JSWINFRA,-1.78,-19.33,44.33,16.43,79305.0,-42877.0,178897.0,342.00,-30.86,40.0,X-MC,11.76,61.0,-0.54,1.39,0.00,X40N,NTT,REALTY
32,HAVELLS,-0.45,-24.75,75.52,32.08,186393.0,-81178.0,246813.0,2062.85,-29.22,29.0,X-MC,11.67,63.0,-0.44,1.91,0.00,X40,ATH,ELECTRICAL
37,ICICIGI,0.01,-10.52,33.36,19.34,59736.0,-21043.0,179066.0,2252.93,-24.74,28.0,X-MC,6.35,66.0,-0.35,1.39,0.01,X40,ATH,INSURANCE
78,UNITDSPR,0.07,-10.23,34.53,20.77,72577.0,-23960.0,210184.0,1644.00,-20.34,37.0,X-MC,3.94,64.0,-0.33,1.63,0.26,X40N,NTT,BREWERIES

In [20]:
# top 5 to accumulate based on lowest CurrAlloc%
df_tmp = df_portfolio_features[df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])].sort_values(by = 'CurrAlloc%', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
58,RELAXO,-1.66,-65.94,347.13,52.31,171642.0,-95714.0,49446.0,1176.00,-63.70,37.0,X-SC,31.99,92.0,-0.56,0.38,10.55,X40N,NTT,FOOTWEAR
12,BATAINDIA,-2.34,-58.60,226.58,35.20,120697.0,-75401.0,53269.0,2096.00,-30.11,37.0,X-SC,34.25,91.0,-0.62,0.41,5.65,X40,NTT,FOOTWEAR
54,QUESS,-0.86,-27.25,139.05,73.90,108025.0,-29105.0,77688.0,424.00,-60.88,43.0,X-SC,22.56,80.0,-0.27,0.60,4.51,XY24,NTT,MISC
36,HONAUT,-0.58,-30.69,118.32,51.31,158135.0,-59188.0,133650.0,58357.33,-42.35,32.0,X-SC,18.32,90.0,-0.37,1.04,1.54,X40N,ATH,ELECTRICAL
51,MEDANTA,-1.25,-15.50,50.43,27.12,75224.0,-27352.0,149165.0,1486.00,-18.04,38.0,X-SC,15.59,87.0,-0.36,1.16,2.78,XY24,NTT,HEALTHCARE

In [21]:
# top 5 to accumulate based on CumlRnk
df_tmp = df_portfolio_features.sort_values(by = 'CumlRnk', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
45,ITC,-0.46,-23.22,55.06,19.06,143808.0,-78982.0,261184.0,452.00,-57.95,37.0,X-LC,19.76,1.0,-0.55,2.03,1.32,X40,NTT,FMCG
73,TCS,0.45,-27.73,75.15,26.57,251595.0,-128482.0,334791.0,4311.59,-38.71,44.0,X-LC,18.68,2.0,-0.51,2.60,4.49,X40,ATH,IT
43,INFY,1.00,-10.56,50.10,34.24,140199.0,-33049.0,279839.0,1972.00,-29.61,52.0,X-LC,14.88,3.0,-0.24,2.17,7.62,X40,NTT,IT
75,TMPV,0.41,-30.68,97.01,36.58,239310.0,-109155.0,246686.0,600.00,-85.81,37.0,X-LC,11.83,4.0,-0.46,1.91,2.82,XY24,NTT,AUTO
33,HCLTECH,0.56,-8.50,35.33,23.83,78210.0,-20554.0,221370.0,1908.19,-4.05,54.0,X-LC,11.25,8.0,-0.26,1.72,7.49,X40,ATH,IT

In [22]:
# top 5 for average up
df_tmp = df_portfolio_features[(df_portfolio_features['Dev%_200'] > 5)].sort_values(by = 'CurrAlloc%', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
67,SONACOMS,1.35,-12.94,59.77,39.09,52639.0,-13090.0,88069.0,804.02,-31.00,50.0,M-MC,6.98,193.0,-0.25,0.68,24.59,AR,ATH,AUTO
24,DMART,1.19,6.11,22.14,29.60,58638.0,15252.0,264852.0,5391.45,-10.50,75.0,X-LC,6.06,14.0,0.26,2.05,21.06,X40N,ATH,FMCG
1,ABB,1.12,13.95,27.75,45.57,82724.0,36485.0,298104.0,7934.00,-26.78,55.0,H-MC,13.65,125.0,0.44,2.31,32.38,AR,NTT,ELECTRICAL

In [23]:
# top 5 RSP
df_tmp = df_portfolio_features.sort_values(by = 'RSP', ascending=False)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
30,HAPPSTMNDS,-1.87,-51.84,283.80,84.85,175184.0,-66437.0,61728.0,1480.71,-42.72,50.0,H-SC,23.76,152.0,-0.38,0.48,14.31,AR,ATH,IT
24,DMART,1.19,6.11,22.14,29.60,58638.0,15252.0,264852.0,5391.45,-10.50,75.0,X-LC,6.06,14.0,0.26,2.05,21.06,X40N,ATH,FMCG
80,VALIANTORG,2.71,-50.41,251.16,74.15,203786.0,-82467.0,81138.0,838.00,-245.98,53.0,H-SC,27.11,145.0,-0.40,0.63,20.74,XR,NTT,CHEMICALS
5,ANGELONE,0.75,-0.55,24.87,24.18,75437.0,-1675.0,303325.0,303.00,-85.37,56.0,X-SC,9.14,97.0,-0.02,2.35,16.75,X40N,NTT,FINANCE
52,PAGEIND,1.18,-10.42,49.71,34.11,119510.0,-27964.0,240415.0,51418.65,-35.81,64.0,X-MC,19.76,55.0,-0.23,1.86,13.73,X40,ATH,APPARELS

In [24]:
# Top N allocation
df_tmp = df_portfolio_features.sort_values(by = 'CurrAlloc%', ascending=False)
top_n_values = [10, 25, 50]

sum_df = pd.DataFrame({
    'Top_N': top_n_values,
    'Sum_Alloc%': [df_tmp['CurrAlloc%'].head(n).sum() for n in top_n_values]
})

sum_df

   Top_N  Sum_Alloc%
0     10       21.23
1     25       46.41
2     50       78.17

In [25]:
# market-cap-wise allocation
df_tmp = df_portfolio_features[cols]
df_tmp.groupby(df_tmp['Conviction'].str[-2:])['CurrAlloc%'].sum().sort_values(ascending=False)

Conviction
SC    44.51
MC    29.61
LC    25.90
Name: CurrAlloc%, dtype: float64

In [26]:
# criteria-wise allocation
df_portfolio_features.groupby('Criteria')['CurrAlloc%'].sum().sort_values(ascending=False)

Criteria
XY24     26.98
X40      25.48
X40N     15.43
AR        9.18
XR        8.38
XY25      7.14
OX40N     6.64
SR        0.79
Name: CurrAlloc%, dtype: float64

In [27]:
# conviction-wise allocation
df_portfolio_features.groupby('Conviction')['CurrAlloc%'].sum().sort_values(ascending=False)

Conviction
X-LC    23.67
X-MC    22.15
H-SC    21.76
X-SC    12.36
M-SC     9.87
H-MC     5.06
M-MC     2.06
H-LC     1.17
M-LC     1.06
L-SC     0.52
L-MC     0.34
Name: CurrAlloc%, dtype: float64

In [28]:
# sector-wise stats
df_tmp = df_portfolio_features.groupby('Category')[['CurrAlloc%', 'Current', 'Current P/L', 'FTT Amt']].sum().sort_values(by=['Current', 'Current P/L'], ascending=False)
df_tmp['Current P/L%'] = round(df_tmp['Current P/L'] * 100 / df_tmp['Current'], 2)
df_tmp['FTT%'] = round(df_tmp['FTT Amt'] * 100 / df_tmp['Current'], 2)
cols = ['CurrAlloc%', 'Current P/L%', 'FTT%']
df_tmp[cols].sort_values(by=['CurrAlloc%'], ascending=False)

               CurrAlloc%  Current P/L%    FTT%
Category
FMCG                15.35        -26.30   71.14
FINANCE             13.18        -26.36   77.86
IT                  12.21        -43.32  116.25
MISC                 6.99        -48.73  113.34
ELECTRICAL           6.43        -16.84   61.58
PAINTS               5.20        -46.91   72.42
INSURANCE            4.57        -15.15   54.56
BANKS                4.51        -32.41   99.62
PHARMA               4.10        -11.21   46.22
AUTO                 3.67        -38.10   92.89
AC                   1.91        -30.10   65.38
HEALTHCARE           1.91        -45.79   83.84
APPARELS             1.86        -11.63   49.71
FOOTWEAR             1.80        -89.42  165.36
TRAVEL               1.77        -95.89  193.98
DURABLES             1.74        -72.48  114.44
BREWERIES            1.63        -11.40   34.53
REALTY               1.39        -23.97   44.33
CERAMICS             1.37        -74.40  127.38
REFINERIES           1.32        -17.90   47.73
CEMENT               1.24        -67.75  193.24
CABLES               1.16          1.19  105.44
ENGINEERING          1.09        -72.80  151.83
CHEMICALS            1.06        -93.37  251.12
JEWELLERY            0.99       -150.05  236.93
ENTERTAINMENT        0.77        -94.50  210.50
TEXTILES             0.46        -56.93  101.68
HOTELS               0.34       -159.96  251.65

In [29]:
# money to be made criteria-wise
df_portfolio_features.groupby('Criteria')['FTT Amt'].agg(['sum', 'count']).sort_values(by='sum', ascending=False)

                sum  count
Criteria
XY24      4120502.0     21
X40       1887898.0     16
XR        1412071.0     12
AR        1387802.0     10
X40N      1310620.0     10
OX40N      936488.0     10
XY25       520904.0      5
SR         317709.0      2

In [30]:
# money to be made conviction-wise
df_portfolio_features.groupby('Conviction')['FTT Amt'].agg(['sum', 'count']).sort_values(by='sum', ascending=False)

                  sum  count
Conviction
H-SC        3989747.0     24
X-MC        1877125.0     15
X-LC        1724402.0     13
M-SC        1646610.0     14
X-SC        1588699.0     10
H-MC         426370.0      3
L-SC         224143.0      2
M-LC         154718.0      1
M-MC         120094.0      2
H-LC          83200.0      1
L-MC          58886.0      1

In [31]:
# money to be made criteria and conviction-wise
df_portfolio_features.groupby(['Conviction', 'Criteria'])['FTT Amt'].agg(['sum', 'count']).sort_values(by='sum', ascending=False)

                           sum  count
Conviction Criteria
H-SC       XY24      1386869.0      6
           AR         994527.0      5
M-SC       XY24       946904.0      6
X-LC       X40        929449.0      7
H-SC       XR         893425.0      7
X-SC       XY24       864238.0      4
X-MC       X40        736164.0      7
           X40N       577464.0      4
X-SC       X40N       502176.0      4
M-SC       OX40N      425049.0      5
H-SC       OX40N      397217.0      4
X-LC       XY24       396309.0      2
H-SC       SR         317709.0      2
X-MC       XY25       285785.0      2
           XY24       277712.0      2
H-MC       XY24       248470.0      1
X-LC       X40N       230980.0      2
X-SC       X40        222285.0      2
M-SC       XR         195121.0      2
H-MC       AR         177900.0      2
X-LC       XY25       167664.0      2
M-LC       XR         154718.0      1
L-SC       OX40N      114222.0      1
           XR         109921.0      1
H-LC       AR          83200.0      1
M-SC       AR          79536.0      1
M-MC       XY25        67455.0      1
L-MC       XR          58886.0      1
M-MC       AR          52639.0      1

In [32]:
# notebook execution time

end_time = time.time()
execution_time = round(end_time - start_time, 0)
print(f"Notebook execution time: {execution_time} seconds")

Notebook execution time: 25.0 seconds