<a href="https://colab.research.google.com/github/ankit-rathi/Quantvesting_v2/blob/main/myStocks_Portfolio_Analysis.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
'''
!pip install pandas==2.2.2 -qq
!pip install pyxirr -qq
!pip install ta -qq
!pip install yfinance==0.2.59 -qq
'''

'\n!pip install pandas==2.2.2 -qq\n!pip install pyxirr -qq\n!pip install ta -qq\n!pip install yfinance==0.2.59 -qq\n'

In [2]:
# import libraries

import numpy as np
import pandas as pd
import datetime
import warnings
warnings.filterwarnings('ignore')
import yfinance as yfin
import ta
import matplotlib.pyplot as plt
import requests

In [3]:
# notebook start time
import time
import datetime
import pytz

start_time = time.time()

# function to print date timestamp
def print_date_time():
  tz_NY = pytz.timezone('Asia/Kolkata')
  datetime_NY = datetime.datetime.now(tz_NY)
  print("Run date time (IST):", datetime_NY.strftime("%Y-%m-%d %H:%M:%S"))

In [4]:
# function to get booked and reserved amount
def get_amt():
  # fetch the JSON data from the URL
  url = "https://raw.githubusercontent.com/ankit-rathi/Tradevesting_v1/main/data/myPortfolioAmts.json"
  response = requests.get(url)
  pf_amts = response.json()  # parse the JSON data

  # extract values from the JSON
  py_booked_amt_dm = pf_amts["py_booked_amt_dm"]
  py_booked_amt_sv = pf_amts["py_booked_amt_sv"]
  cy_booked_amt_dm = pf_amts["cy_booked_amt_dm"]
  cy_booked_amt_sv = pf_amts["cy_booked_amt_sv"]
  reserve_amt_dm = pf_amts["reserve_amt_dm"]
  reserve_amt_sv = pf_amts["reserve_amt_sv"]

  # perform calculations
  py_booked_amt = py_booked_amt_dm + py_booked_amt_sv
  cy_booked_amt = cy_booked_amt_dm + cy_booked_amt_sv
  reserve_amt = reserve_amt_dm + reserve_amt_sv
  total_booked_amt = py_booked_amt + cy_booked_amt

  return total_booked_amt, reserve_amt, cy_booked_amt, py_booked_amt

gen_output = 0

In [5]:
# function to format the amount
def format_amt(number):
    abs_number = abs(number)

    if abs_number >= 1_00_00_000:  # Crores
        formatted_amt = f"{number / 1_00_00_000:.2f} C"
    elif abs_number >= 1_00_000:  # Lakhs
        formatted_amt = f"{number / 1_00_000:.2f} L"
    elif abs_number >= 1_000:  # Thousands
        formatted_amt = f"{number / 1_000:.2f} K"
    else:
        formatted_amt = f"{number:.2f}"

    return formatted_amt

# function to set start and end date
def get_start_end_date():
  start_date = (datetime.date.today() + datetime.timedelta(days=-365)).strftime('%Y-%m-%d')
  end_date = (datetime.date.today() + datetime.timedelta(days=1)).strftime('%Y-%m-%d')
  return start_date, end_date

# function to fetch my portfolio csv
def get_mypfs_df():
  mypfs_df = pd.read_csv('https://raw.githubusercontent.com/ankit-rathi/Tradevesting_v1/main/data/myPortfolioStocks.csv')
  return mypfs_df

# function to fetch my prospects csv
def get_mypps_df():
  mypps_df = pd.read_csv('https://raw.githubusercontent.com/ankit-rathi/Tradevesting_v1/main/data/myProspectsScrips.csv')
  return mypps_df

# function to fetch screener data
def get_myscreen_df():
  myscreen_df = pd.read_csv('https://raw.githubusercontent.com/ankit-rathi/Tradevesting_v1/main/data/myScreenerDB.csv')
  return myscreen_df

# function to fetch momentum data
def get_myinvmt_df():
  myinvmt_df = pd.read_csv('https://raw.githubusercontent.com/ankit-rathi/Tradevesting_v1/main/data/myInvestments.csv')
  return myinvmt_df

# function to get the stock ids
def get_stock_ids(df_pf):
  stock_n100 = df_pf['Symbol'].unique()

  exclude = ['CADILAHC','MMTC', 'MASFIN']

  stock_ids = df_pf[~df_pf['Symbol'].isin(exclude) ]['Symbol'].unique()

  #mypf = mypf[mypf.Forecast.notnull()]
  #stock_ids = mypf['Symbol'].unique()

  #stock_ids.sort()
  return stock_ids

# get features from screener data
def get_screener_features():
  myscreen_df = get_myscreen_df()
  cols = ['Symbol', 'EPS', 'MedPE', 'ROCE%', 'ROE%', 'CapType']
  return myscreen_df[cols]

# get relative strength
def get_relative_strength(stock_list):

    # Dictionary to store stock tickers and their corresponding percentage price change
    stock_changes = {}

    # Loop through each stock and fetch its price data
    for stock in stock_list:
        try:
            # Download the stock data for the given date range
            stock_data = yfin.Ticker(stock + '.NS').history(period='1mo', interval='1d')[map(str.title, ['open', 'close', 'low', 'high', 'volume'])]

            # Calculate the percentage change for the stock
            if len(stock_data) > 0:
                start_price = stock_data['Close'].iloc[0]
                end_price = stock_data['Close'].iloc[-1]
                percent_change = round(((end_price - start_price) / start_price) * 100, 2)
                stock_changes[stock] = percent_change
            else:
                stock_changes[stock] = np.nan  # If no data is available, set to NaN

        except Exception as e:
            print(f"Error fetching data for {stock}: {e}")
            stock_changes[stock] = np.nan

    # Create a DataFrame with stock tickers and their percentage changes
    df = pd.DataFrame(list(stock_changes.items()), columns=['Symbol', 'Percent_Change'])

    # Drop any stocks with missing data (NaN values)
    df = df.dropna()

    # Calculate the percentile rank based on percentage change
    df['RSP'] = round(df['Percent_Change'].rank(pct=True) * 100, 2)
    cols = ['Symbol', 'RSP']
    df = df[cols]
    # Sort by percentile rank (optional)
    df = df.sort_values(by='RSP', ascending=False).reset_index(drop=True)

    return df

In [6]:
# function to get stock technicals
def stock_prec_dev(stock_symbol):
    #stock_symbol = 'ULTRACEMCO.NS'
    short_window = 20
    mid_window = 50
    long_window = 200
    moving_avg = 'SMA'

    start = datetime.datetime(*map(int, start_date.split('-')))
    end = datetime.datetime(*map(int, end_date.split('-')))

    stock_df = yfin.Ticker(stock_symbol + '.NS').history(period='max', interval='1d')[map(str.title, ['open', 'close', 'low', 'high', 'volume'])]

    stock_df['Max'] = round(max(stock_df['Close']),2)
    stock_df = stock_df[(stock_df.index <= end_date) & (stock_df.index >= start_date)]
    stock_df['200_SMA'] = round(stock_df['Close'].rolling(window = 200, min_periods = 1).mean(),0)
    stock_df['Dev%_200'] = round((stock_df['Close'] - stock_df['200_SMA'])*100/stock_df['200_SMA'],2)
    stock_df.dropna(axis = 0, inplace = True) # remove any null rows

    stock_df['20_SMA'] = stock_df['Close'].rolling(window=20).mean()
    stock_df['50_SMA'] = stock_df['Close'].rolling(window=50).mean()
    stock_df['Symbol'] = stock_symbol

    stock_df['Close'] = round(stock_df['Close'],2)
    stock_df['Min'] = round(min(stock_df['Close']),2)
    stock_df['RSI_14'] = ta.momentum.RSIIndicator(close=stock_df['Close'], window=14).rsi()
    stock_df['RSI_14'] = round(stock_df['RSI_14'],0)
    stock_df['Prev_Close'] = stock_df['Close'].shift(1)
    stock_df.drop(['Open', 'Low', 'High', 'Volume'], axis=1, inplace=True)
    stock_df = stock_df.tail(1)

    max_SMA = max(stock_df['20_SMA'].item(), stock_df['50_SMA'].item(), stock_df['200_SMA'].item())
    min_SMA = min(stock_df['20_SMA'].item(), stock_df['50_SMA'].item(), stock_df['200_SMA'].item())
    ABS_Spread = max_SMA - min_SMA
    stock_df['Spread%'] = round((ABS_Spread / stock_df['200_SMA'].item()) * 100,2)

    return stock_df

# function to compute stock attributes
def get_common_features(stock_ids, df_mypf):

  df_prec_dev = pd.DataFrame()
  df_tmp = get_screener_features()
  df_rs = get_relative_strength(stock_ids)

  for stock_id in stock_ids:
      tmp = stock_prec_dev(stock_id)
      tmp = tmp.reset_index()
      df_prec_dev = pd.concat([df_prec_dev, tmp], ignore_index = True)
  df_prec_dev = pd.merge(df_prec_dev, df_mypf, on= 'Symbol')
  df_prec_dev = pd.merge(df_prec_dev, df_tmp, on= 'Symbol', how='left')
  df_prec_dev = pd.merge(df_prec_dev, df_rs, on= 'Symbol', how='left')
  #print(df_prec_dev.columns)
  df_prec_dev['Curr_PE'] = round(df_prec_dev['Close']/df_prec_dev['EPS'],1)
  df_prec_dev['Dev%_PE'] = round((df_prec_dev['Curr_PE'] - df_prec_dev['MedPE'])*100/df_prec_dev['MedPE'],2)
  df_prec_dev['Conviction'] = df_prec_dev['Conviction'] + '-' + df_prec_dev['CapType']
  return df_prec_dev

# function to arrange stock features
def arrange_features(df_stocks, common_cols, diff_cols):
  df_stocks_common = df_stocks[common_cols].drop_duplicates()
  df_stocks_diff = df_stocks[diff_cols]
  df_stocks_diff['Investment'] = df_stocks_diff['AvgCost'] * df_stocks_diff['Shares']
  df_stocks_diff = df_stocks_diff.groupby(['Symbol'])[['Shares', 'Investment']].aggregate(['sum']).reset_index()
  df_stocks_diff.columns = ['Symbol', 'Shares', 'Investment']
  df_stocks_diff['AvgCost'] = round(df_stocks_diff['Investment']/df_stocks_diff['Shares'],2)
  df_stocks = pd.merge(df_stocks_diff, df_stocks_common, on='Symbol')
  return df_stocks

# plot fact distribution across dimension
def plot_pie_chart(df, dimension, fact):
  # grouping the data by category and calculating the sum of fact for each type
  grouped_data = df.groupby(dimension)[fact].sum()

  # sorting the grouped data in descending order
  grouped_data = grouped_data.sort_values(ascending=False)

  # creating a pie chart
  grouped_data.plot.pie(autopct='%1.1f%%', startangle=90, figsize=(6, 6))

  # adding a title and displaying the plot
  plt.title(f'{dimension} {fact} Distribution')
  plt.ylabel('')  # To hide the y-label
  plt.show()

In [7]:
# function to get portfolio features

def get_portfolio_features(df_common_features):

  print_date_time()
  print('-------------------')

  #df_common_features["Target"] = df_common_features["Target"].fillna(df_common_features["Max"])
  df_common_features['NTT'] = np.where(df_common_features['Strategy']== 'NTT', df_common_features["Target"], df_common_features['Max'])
  df_common_features['LTT'] = np.where(df_common_features['Strategy']== 'BTT', df_common_features["Target"], df_common_features['Max'])
  df_common_features['BOL'] = df_common_features['Min']

  tmp_df = df_common_features[df_common_features['Symbol'].isin(mypf_df[mypf_df['InPortfolio'] != 'NA'].Symbol.values)]
  print('qualified stocks: '+str(len(tmp_df['Symbol'].unique())))
  tmp_df1 = tmp_df[tmp_df['LatestQtr'] == 1]
  print('with latest results: '+str(len(tmp_df1['Symbol'].unique())))
  tmp_df1 = tmp_df1[tmp_df1['StarStock'] == 1]
  print('still star stocks: '+str(len(tmp_df1['Symbol'].unique())))
  tmp_df['Investment'] = tmp_df['AvgCost'] * tmp_df['Shares']
  tmp_df['Current'] = round(tmp_df['Close'] * tmp_df['Shares'],0)
  tmp_df['Previous'] = tmp_df['Prev_Close'] * tmp_df['Shares']
  tmp_df['EstimatedST'] = tmp_df['NTT'] * tmp_df['Shares']
  tmp_df['EstimatedLT'] = tmp_df['LTT'] * tmp_df['Shares']
  tmp_df['Current P/L'] = round((tmp_df['Current'] - tmp_df['Investment']),0)
  tmp_df['Today P/L%'] = round((tmp_df['Current'] - tmp_df['Previous'])*100/tmp_df['Previous'],2)
  tmp_df['Current P/L%'] = round((tmp_df['Current'] - tmp_df['Investment'])*100/tmp_df['Investment'],2)
  tmp_df['EstimatedST P/L%'] = round((tmp_df['EstimatedST'] - tmp_df['Investment'])*100/tmp_df['Investment'],2)
  tmp_df['EstimatedLT P/L%'] = round((tmp_df['EstimatedLT'] - tmp_df['Investment'])*100/tmp_df['Investment'],2)
  tmp_df['NTT%'] = round((tmp_df['NTT'] - tmp_df['Close'])*100/tmp_df['Close'],2)
  tmp_df['LTT%'] = round((tmp_df['LTT'] - tmp_df['Close'])*100/tmp_df['Close'],2)
  tmp_df['Gained%'] = round((tmp_df['Close'] - tmp_df['BOL'])*100/tmp_df['BOL'],2)
  investment = round(sum(tmp_df['AvgCost']*tmp_df['Shares']),0)
  current = round(sum(tmp_df['Close']*tmp_df['Shares']),0)
  tmp_df['InitAlloc%'] = round(tmp_df['Investment']*100/investment,2)
  tmp_df['CurrAlloc%'] = round(tmp_df['Current']*100/current,2)
  tmp_df['FTT'] = tmp_df['LTT']
  tmp_df.loc[tmp_df['Strategy'] == 'NTT', 'FTT'] = tmp_df['NTT']
  tmp_df['FTT%'] = tmp_df['LTT%']
  tmp_df.loc[tmp_df['Strategy'] == 'NTT', 'FTT%'] = tmp_df['NTT%']
  tmp_df['FTT Amt'] = round(tmp_df['FTT%'] * tmp_df['Current']/100,0)
  tmp_df['OTT%'] = round((tmp_df['FTT'] - tmp_df['AvgCost'])*100/tmp_df['AvgCost'],2)
  tmp_df['RRR Ind'] = round(tmp_df['Current P/L']/tmp_df['FTT Amt'],2)
  tmp_df['Risk Ind'] = round(tmp_df['Current P/L%']*tmp_df['CurrAlloc%'],0)

  return tmp_df

# function to print portfolio features
def print_portfolio_stats(df_portfolio_features, myinvmt_df):
  from pyxirr import xirr

  total_booked_amt, reserve_amt, cy_booked_amt, py_booked_amt = get_amt()

  dates = myinvmt_df['Date'].values
  dates = np.append(dates, datetime.date.today().strftime('%d-%b-%y'))
  investment = myinvmt_df['Investment'].values
  dates= pd.to_datetime(dates)

  current = round(sum(df_portfolio_features['Close']*df_portfolio_features['Shares']),0) + reserve_amt
  investment_xirr = np.append(investment, current)
  cagr = round(xirr(pd.DataFrame({"dates": dates, "amounts": investment_xirr}))*100,2)

  investment = -sum(investment)
  invested = round(sum(df_portfolio_features['AvgCost']*df_portfolio_features['Shares']),0) + reserve_amt
  previous = round(sum(df_portfolio_features['Prev_Close']*df_portfolio_features['Shares']),0) + reserve_amt
  cy_invested = investment + py_booked_amt

  today_pnl_amount = current-previous
  today_pnl_percentage = round((current-previous)*100/previous,2)

  curr_pnl_amount = current-invested
  curr_pnl_percentage = round((curr_pnl_amount)*100/(cy_invested),2)

  cy_pnl_amount = cy_booked_amt + curr_pnl_amount
  cy_pnl_percentage = round((cy_pnl_amount)*100/cy_invested,2)

  overall_pnl_amount = total_booked_amt + curr_pnl_amount
  overall_pnl_percentage = round((overall_pnl_amount)*100/investment,2)

  estimate_st = round(sum(df_portfolio_features['FTT']*df_portfolio_features['Shares']),0)  + reserve_amt
  est_st_pnl_amount = estimate_st-current
  est_st_pnl_percentage = round((est_st_pnl_amount)*100/current,2)

  estimate_lt = round(sum(df_portfolio_features['LTT']*df_portfolio_features['Shares']),0)  + reserve_amt
  est_lt_pnl_amount = estimate_lt-current
  est_lt_pnl_percentage = round((est_lt_pnl_amount)*100/current,2)

  total_profit = round(sum(df_portfolio_features[df_portfolio_features['Current P/L%'] > 0]['Current']) - sum(df_portfolio_features[df_portfolio_features['Current P/L%'] > 0]['Investment']),0)
  total_loss = round(sum(df_portfolio_features[df_portfolio_features['Current P/L%'] < 0]['Current']) - sum(df_portfolio_features[df_portfolio_features['Current P/L%'] < 0]['Investment']),0)

  cy_booked_percentage = round((cy_booked_amt)*100/current,2)
  py_booked_percentage = round((py_booked_amt)*100/investment,2)
  total_booked_percentage = round((total_booked_amt)*100/investment,2)

  print('-------------------')
  print('Initial Investment: ', format_amt(investment))
  print('CY Investment: ', format_amt(cy_invested))
  print('Reserve: ', format_amt(reserve_amt))
  print('Current: ',  format_amt(current))
  print('-------------------')
  print('Today PnL: '+ '{} ({}%)'.format(format_amt(today_pnl_amount), today_pnl_percentage))
  print('Current PnL: '+ '{} ({}%)'.format(format_amt(curr_pnl_amount), curr_pnl_percentage))
  print('CY Booked + Current PnL: '+ '{} ({}%)'.format(format_amt(cy_pnl_amount), cy_pnl_percentage))
  print('-------------------')
  print('Total profit: ', format_amt(total_profit))
  print('Total loss: ', format_amt(total_loss))
  print('-------------------')
  print('Total Booked + Current PnL: '+ '{} ({}%)'.format(format_amt(overall_pnl_amount), overall_pnl_percentage))
  print('Total Booked PnL: '+ '{} ({}%)'.format(format_amt(total_booked_amt), total_booked_percentage))
  print('Curr Year Booked PnL: '+ '{} ({}%)'.format(format_amt(cy_booked_amt), cy_booked_percentage))
  print('Prev Year Booked PnL: '+ '{} ({}%)'.format(format_amt(py_booked_amt), py_booked_percentage))
  print('===================')
  print('Est FTT: ',  format_amt(estimate_st))
  print('Est FTT PnL: '+ '{} ({}%)'.format(format_amt(est_st_pnl_amount), est_st_pnl_percentage))

  print('===================')
  print('Deployed: ', format_amt(investment))

  print('Current: ', format_amt(current))

  print('CAGR/XIRR %: '+'{}%'.format(cagr))

In [8]:
# get start and end date
start_date, end_date = get_start_end_date()

# get portfolio and prospects data
mypfs_df = get_mypfs_df()
mypps_df = get_mypps_df()
myinvmt_df = get_myinvmt_df()

# merge above datasets
mypf_df = pd.merge(mypfs_df, mypps_df, on="Symbol")

# seggregate dm and sv portfolio
dm_pf = mypf_df[mypf_df['InPortfolio'] == 'DM']
sv_pf = mypf_df[mypf_df['InPortfolio'] == 'SV']

# build portfolio stock dataframe
dm_stocks = get_stock_ids(dm_pf)
sv_stocks = get_stock_ids(sv_pf)
df_stocks = pd.concat([dm_pf,sv_pf], ignore_index = True)

# arrange common and diff stock features
common_cols = ['Symbol', 'Target', 'Criteria', 'Strategy', 'CumlRnk', 'LatestQtr', 'StarStock', 'Conviction', 'Category', 'InFolio', 'XIRR', 'MBQ']
diff_cols = ['Symbol', 'AvgCost', 'Shares']
df_stocks = arrange_features(df_stocks, common_cols, diff_cols)

# get common features
stock_ids = df_stocks['Symbol'].values
df_common_features = get_common_features(stock_ids, df_stocks)

df_common_features.reset_index(drop=True, inplace=True)
df_common_features.drop(['Date'], axis=1, inplace=True)
# get and print portfolio features
df_portfolio_features = get_portfolio_features(df_common_features)

print_portfolio_stats(df_portfolio_features, myinvmt_df)

df = df_portfolio_features
#plot_pie_chart(df, 'CapType', 'Current')
list_ox40n = list(df[df['MBQ'].str.contains('OX40N', na=False)]['Symbol'].values)

Run date time (IST): 2026-03-18 09:55:12
-------------------
qualified stocks: 86
with latest results: 26
still star stocks: 16
-------------------
Initial Investment:  1.36 C
CY Investment:  1.62 C
Reserve:  1.61 K
Current:  1.34 C
-------------------
Today PnL: 2.17 L (1.64%)
Current PnL: -43.01 L (-26.47%)
CY Booked + Current PnL: -27.12 L (-16.69%)
-------------------
Total profit:  84.48 K
Total loss:  -43.85 L
-------------------
Total Booked + Current PnL: -13.62 K (-0.1%)
Total Booked PnL: 42.87 L (31.64%)
Curr Year Booked PnL: 15.89 L (11.85%)
Prev Year Booked PnL: 26.98 L (19.91%)
===================
Est FTT:  2.48 C
Est FTT PnL: 1.14 C (84.83%)
===================
Deployed:  1.36 C
Current:  1.34 C
CAGR/XIRR %: -0.51%

In [9]:
# top 5 near their targets
cols = ['Symbol', 'Today P/L%', 'Current P/L%', 'FTT%', 'OTT%', 'FTT Amt', 'Current P/L', 'Current', 'FTT', 'Dev%_PE', 'RSI_14','Conviction', 'Spread%',  'CumlRnk', 'RRR Ind', 'CurrAlloc%', 'Gained%', 'Criteria', 'Strategy', 'Category']
df_tmp = df_portfolio_features[~df_portfolio_features['Symbol'].isin(['ENRIN','BLUSPRING','DIGITIDE'])]
df_tmp = df_tmp.sort_values(by = 'FTT Amt', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
50,MASFIN,2.24,-7.76,31.80,21.57,28739.0,-7605.0,90375.0,397.04,-20.51,41.0,H-SC,2.16,167.0,-0.26,0.67,25.33,XR,ATH,FINANCE
77,TTKPRESTIG,0.06,-36.90,58.62,0.09,37279.0,-37183.0,63594.0,770.00,47.71,41.0,M-SC,16.88,250.0,-1.00,0.47,7.45,OX40N,NTT,DURABLES
37,ICICIGI,-0.84,-3.58,23.77,19.34,45865.0,-7157.0,192952.0,2252.93,-18.85,37.0,X-MC,2.32,66.0,-0.16,1.44,6.66,X40,ATH,INSURANCE
67,SONACOMS,3.67,-9.95,54.46,39.09,49611.0,-10063.0,91096.0,804.02,-28.71,54.0,M-MC,8.83,193.0,-0.20,0.68,28.87,AR,ATH,AUTO
2,ABBOTINDIA,0.43,-10.88,32.49,18.07,51786.0,-19465.0,159390.0,35195.00,-24.24,45.0,X-MC,10.81,58.0,-0.38,1.19,1.05,X40,ATH,PHARMA

In [10]:
# top 5 today
df_tmp = df_portfolio_features.sort_values(by = 'Today P/L%', ascending=False)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
80,VALIANTORG,18.00,-51.53,259.33,74.15,205625.0,-84314.0,79291.0,838.00,-242.86,53.0,H-SC,29.68,145.0,-0.41,0.59,18.00,XR,NTT,CHEMICALS
61,ROUTE,11.84,-62.19,344.69,68.16,173441.0,-82748.0,50318.0,2215.45,-69.55,47.0,H-SC,35.63,141.0,-0.48,0.38,11.84,SR,ATH,IT
18,CERA,6.30,-36.04,93.70,23.89,105416.0,-63399.0,112504.0,9475.00,-38.19,52.0,H-SC,18.03,153.0,-0.60,0.84,8.12,OX40N,NTT,CERAMICS
4,ALKYLAMINE,3.99,-43.35,241.81,93.63,138301.0,-43769.0,57194.0,4546.37,-39.38,36.0,H-SC,24.00,142.0,-0.32,0.43,5.61,SR,ATH,CHEMICALS
5,ANGELONE,3.90,-7.60,34.40,24.18,96943.0,-23188.0,281812.0,303.00,-86.38,43.0,X-SC,8.93,97.0,-0.24,2.10,16.46,X40N,NTT,FINANCE

In [11]:
# bottom 5 today
df_tmp = df_portfolio_features.sort_values(by = 'Today P/L%', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
34,HDFCBANK,-1.20,-0.08,28.47,28.37,66817.0,-194.0,234691.0,1073.00,-15.10,34.0,X-LC,9.54,26.0,-0.00,1.75,2.23,X40,BTT,BANKS
24,DMART,-0.96,-9.10,42.58,29.60,96607.0,-22716.0,226884.0,5391.45,-23.35,43.0,X-LC,7.21,14.0,-0.24,1.69,3.71,X40N,ATH,FMCG
37,ICICIGI,-0.84,-3.58,23.77,19.34,45865.0,-7157.0,192952.0,2252.93,-18.85,37.0,X-MC,2.32,66.0,-0.16,1.44,6.66,X40,ATH,INSURANCE
20,COLPAL,-0.42,-26.61,92.81,41.51,179392.0,-70075.0,193290.0,3726.84,-11.23,29.0,X-MC,4.21,62.0,-0.39,1.44,0.00,XY25,ATH,FMCG
77,TTKPRESTIG,0.06,-36.90,58.62,0.09,37279.0,-37183.0,63594.0,770.00,47.71,41.0,M-SC,16.88,250.0,-1.00,0.47,7.45,OX40N,NTT,DURABLES

In [12]:
# top 5 to exit based on CumlRnk
df_tmp = df_portfolio_features[~df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])]
df_tmp = df_tmp[(df_tmp['Current P/L%'] > -1) & (df_tmp['Current P/L%'] < 1)].sort_values(by = 'CumlRnk', ascending=False)
df_tmp[cols].head()

Empty DataFrame
Columns: [Symbol, Today P/L%, Current P/L%, FTT%, OTT%, FTT Amt, Current P/L, Current, FTT, Dev%_PE, RSI_14, Conviction, Spread%, CumlRnk, RRR Ind, CurrAlloc%, Gained%, Criteria, Strategy, Category]
Index: []

In [13]:
# OX40N stocks to exit
df_tmp = df_portfolio_features[(df_portfolio_features['Symbol'].isin(list_ox40n))].sort_values(by = 'Current P/L%', ascending=False)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
26,FINCABLES,1.60,10.34,88.43,107.91,144057.0,15261.0,162905.0,1641.55,-0.56,53.0,M-SC,8.03,220.0,0.11,1.21,22.56,OX40N,ATH,CABLES
66,SIS,2.54,-35.92,89.25,21.26,63497.0,-39887.0,71145.0,528.00,1662.69,35.0,H-SC,13.05,168.0,-0.63,0.53,2.54,OX40N,NTT,MISC
18,CERA,6.30,-36.04,93.70,23.89,105416.0,-63399.0,112504.0,9475.00,-38.19,52.0,H-SC,18.03,153.0,-0.60,0.84,8.12,OX40N,NTT,CERAMICS
77,TTKPRESTIG,0.06,-36.90,58.62,0.09,37279.0,-37183.0,63594.0,770.00,47.71,41.0,M-SC,16.88,250.0,-1.00,0.47,7.45,OX40N,NTT,DURABLES
70,SYMPHONY,2.25,-38.59,62.78,-0.03,65982.0,-66040.0,105101.0,1306.00,-50.64,45.0,M-SC,14.83,205.0,-1.00,0.78,6.29,OX40N,NTT,DURABLES

In [14]:
# top 5 to book for rotation
df_tmp = df_portfolio_features[(df_portfolio_features['Current P/L%'] > 20) ].sort_values(by = 'CumlRnk', ascending=False)
df_tmp[cols].head()

Empty DataFrame
Columns: [Symbol, Today P/L%, Current P/L%, FTT%, OTT%, FTT Amt, Current P/L, Current, FTT, Dev%_PE, RSI_14, Conviction, Spread%, CumlRnk, RRR Ind, CurrAlloc%, Gained%, Criteria, Strategy, Category]
Index: []

In [15]:
# top 5 to monitor for exit
df_tmp = df_portfolio_features[~df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])]
df_tmp = df_tmp[(df_tmp['Current P/L%'] > 0) ].sort_values(by = 'Dev%_PE', ascending=False)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
26,FINCABLES,1.60,10.34,88.43,107.91,144057.0,15261.0,162905.0,1641.55,-0.56,53.0,M-SC,8.03,220.0,0.11,1.21,22.56,OX40N,ATH,CABLES
1,ABB,1.16,17.13,24.28,45.57,74402.0,44813.0,306432.0,7934.00,-24.72,64.0,H-MC,12.28,125.0,0.60,2.29,36.08,AR,NTT,ELECTRICAL

In [16]:
# top 5 to book for rotation from weak conviction
df_tmp = df_portfolio_features[~df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])]
df_tmp = df_tmp[~df_tmp['Criteria'].isin(['XY25','XY24','X40', 'X40N'])].sort_values(by = 'RRR Ind', ascending=False)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
1,ABB,1.16,17.13,24.28,45.57,74402.0,44813.0,306432.0,7934.00,-24.72,64.0,H-MC,12.28,125.0,0.60,2.29,36.08,AR,NTT,ELECTRICAL
26,FINCABLES,1.60,10.34,88.43,107.91,144057.0,15261.0,162905.0,1641.55,-0.56,53.0,M-SC,8.03,220.0,0.11,1.21,22.56,OX40N,ATH,CABLES
40,INDIAMART,0.57,-10.73,131.57,106.72,144861.0,-13234.0,110102.0,4810.62,-59.77,39.0,H-SC,10.31,140.0,-0.09,0.82,10.14,AR,ATH,MISC
85,ZYDUSLIFE,1.55,-4.71,42.34,35.63,84551.0,-9878.0,199696.0,1286.17,-17.12,49.0,H-MC,5.19,120.0,-0.12,1.49,11.17,AR,ATH,PHARMA
67,SONACOMS,3.67,-9.95,54.46,39.09,49611.0,-10063.0,91096.0,804.02,-28.71,54.0,M-MC,8.83,193.0,-0.20,0.68,28.87,AR,ATH,AUTO

In [17]:
# top 5 to accumulate based on lowest RSI_14
df_tmp = df_portfolio_features[df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])].sort_values(by = 'RSI_14', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
53,PGHH,0.52,-24.68,75.26,32.01,121042.0,-52688.0,160832.0,17616.87,-49.01,18.0,X-MC,13.35,57.0,-0.44,1.20,0.52,X40,ATH,FMCG
58,RELAXO,2.36,-63.47,316.95,52.31,168063.0,-92135.0,53025.0,1176.00,-61.09,20.0,X-SC,22.66,92.0,-0.55,0.40,2.36,X40N,NTT,FOOTWEAR
12,BATAINDIA,1.82,-55.91,206.66,35.20,117238.0,-71940.0,56730.0,2096.00,-25.63,22.0,X-SC,28.58,91.0,-0.61,0.42,1.82,X40,NTT,FOOTWEAR
3,ACC,1.39,-37.16,178.17,74.81,300224.0,-99624.0,168504.0,3906.00,-55.22,26.0,X-SC,15.23,85.0,-0.33,1.26,2.26,XY24,BTT,CEMENT
20,COLPAL,-0.42,-26.61,92.81,41.51,179392.0,-70075.0,193290.0,3726.84,-11.23,29.0,X-MC,4.21,62.0,-0.39,1.44,0.00,XY25,ATH,FMCG

In [18]:
# top 5 to accumulate based on Spread and CumlRnk
df_tmp = df_portfolio_features[df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])]
df_tmp = df_tmp[(df_tmp['CumlRnk'] < 100)].sort_values(by = 'Spread%', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
78,UNITDSPR,0.57,-3.86,25.61,20.77,57652.0,-9030.0,225114.0,1644.00,-14.79,41.0,X-MC,0.97,64.0,-0.16,1.68,2.59,X40N,NTT,BREWERIES
37,ICICIGI,-0.84,-3.58,23.77,19.34,45865.0,-7157.0,192952.0,2252.93,-18.85,37.0,X-MC,2.32,66.0,-0.16,1.44,6.66,X40,ATH,INSURANCE
38,ICICIPRULI,0.14,-1.83,33.16,30.73,64131.0,-3605.0,193400.0,790.00,-28.25,32.0,X-MC,2.75,78.0,-0.06,1.44,10.64,X40,ATH,INSURANCE
21,DABUR,0.17,-11.36,62.13,43.70,136608.0,-28193.0,219875.0,735.00,-19.65,31.0,X-MC,3.22,70.0,-0.21,1.64,1.97,XY24,BTT,FMCG
59,RELIANCE,0.94,-9.44,38.36,25.30,69813.0,-18970.0,181993.0,1952.00,-11.96,50.0,X-LC,3.24,21.0,-0.27,1.36,21.51,XY25,BTT,REFINERIES

In [19]:
# top 5 to accumulate based on lowest Gained%
df_tmp = df_portfolio_features[df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])].sort_values(by = 'Gained%', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
20,COLPAL,-0.42,-26.61,92.81,41.51,179392.0,-70075.0,193290.0,3726.84,-11.23,29.0,X-MC,4.21,62.0,-0.39,1.44,0.00,XY25,ATH,FMCG
53,PGHH,0.52,-24.68,75.26,32.01,121042.0,-52688.0,160832.0,17616.87,-49.01,18.0,X-MC,13.35,57.0,-0.44,1.20,0.52,X40,ATH,FMCG
36,HONAUT,1.01,-23.41,97.55,51.31,144081.0,-45138.0,147700.0,58357.33,-36.31,36.0,X-SC,14.45,90.0,-0.31,1.10,1.01,X40N,ATH,ELECTRICAL
2,ABBOTINDIA,0.43,-10.88,32.49,18.07,51786.0,-19465.0,159390.0,35195.00,-24.24,45.0,X-MC,10.81,58.0,-0.38,1.19,1.05,X40,ATH,PHARMA
45,ITC,0.08,-19.64,48.15,19.06,131628.0,-66796.0,273370.0,452.00,-55.92,39.0,X-LC,17.34,1.0,-0.51,2.04,1.21,X40,NTT,FMCG

In [20]:
# top 5 to accumulate based on lowest CurrAlloc%
df_tmp = df_portfolio_features[df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])].sort_values(by = 'CurrAlloc%', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
58,RELAXO,2.36,-63.47,316.95,52.31,168063.0,-92135.0,53025.0,1176.00,-61.09,20.0,X-SC,22.66,92.0,-0.55,0.40,2.36,X40N,NTT,FOOTWEAR
12,BATAINDIA,1.82,-55.91,206.66,35.20,117238.0,-71940.0,56730.0,2096.00,-25.63,22.0,X-SC,28.58,91.0,-0.61,0.42,1.82,X40,NTT,FOOTWEAR
54,QUESS,3.60,-25.51,133.47,73.90,106169.0,-27248.0,79545.0,424.00,-59.78,38.0,X-SC,19.68,80.0,-0.26,0.59,3.66,XY24,NTT,MISC
36,HONAUT,1.01,-23.41,97.55,51.31,144081.0,-45138.0,147700.0,58357.33,-36.31,36.0,X-SC,14.45,90.0,-0.31,1.10,1.01,X40N,ATH,ELECTRICAL
2,ABBOTINDIA,0.43,-10.88,32.49,18.07,51786.0,-19465.0,159390.0,35195.00,-24.24,45.0,X-MC,10.81,58.0,-0.38,1.19,1.05,X40,ATH,PHARMA

In [21]:
# top 5 to accumulate based on CumlRnk
df_tmp = df_portfolio_features.sort_values(by = 'CumlRnk', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
45,ITC,0.08,-19.64,48.15,19.06,131628.0,-66796.0,273370.0,452.00,-55.92,39.0,X-LC,17.34,1.0,-0.51,2.04,1.21,X40,NTT,FMCG
73,TCS,3.01,-27.67,75.00,26.57,251297.0,-128210.0,335063.0,4311.59,-38.71,31.0,X-LC,15.87,2.0,-0.51,2.50,3.01,X40,ATH,IT
43,INFY,3.13,-13.44,55.09,34.24,149200.0,-42058.0,270830.0,1972.00,-31.79,34.0,X-LC,14.09,3.0,-0.28,2.02,3.13,X40,NTT,IT
75,TMPV,2.24,-25.71,83.85,36.58,221652.0,-91497.0,264344.0,600.00,-84.72,38.0,X-LC,3.42,4.0,-0.41,1.97,3.90,XY24,NTT,AUTO
33,HCLTECH,3.01,-11.69,40.23,23.83,85950.0,-28278.0,213646.0,1908.19,-7.36,38.0,X-LC,10.81,8.0,-0.33,1.59,3.01,X40,ATH,IT

In [22]:
# top 5 for average up
df_tmp = df_portfolio_features[(df_portfolio_features['Dev%_200'] > 5)].sort_values(by = 'CurrAlloc%', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
67,SONACOMS,3.67,-9.95,54.46,39.09,49611.0,-10063.0,91096.0,804.02,-28.71,54.0,M-MC,8.83,193.0,-0.2,0.68,28.87,AR,ATH,AUTO
1,ABB,1.16,17.13,24.28,45.57,74402.0,44813.0,306432.0,7934.00,-24.72,64.0,H-MC,12.28,125.0,0.6,2.29,36.08,AR,NTT,ELECTRICAL

In [23]:
# top 5 RSP
df_tmp = df_portfolio_features.sort_values(by = 'RSP', ascending=False)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
1,ABB,1.16,17.13,24.28,45.57,74402.0,44813.0,306432.0,7934.00,-24.72,64.0,H-MC,12.28,125.0,0.60,2.29,36.08,AR,NTT,ELECTRICAL
26,FINCABLES,1.60,10.34,88.43,107.91,144057.0,15261.0,162905.0,1641.55,-0.56,53.0,M-SC,8.03,220.0,0.11,1.21,22.56,OX40N,ATH,CABLES
69,SURYODAY,0.98,-26.93,68.38,23.03,89472.0,-48225.0,130846.0,216.00,42.54,49.0,H-SC,6.76,166.0,-0.54,0.98,29.82,XR,NTT,BANKS
2,ABBOTINDIA,0.43,-10.88,32.49,18.07,51786.0,-19465.0,159390.0,35195.00,-24.24,45.0,X-MC,10.81,58.0,-0.38,1.19,1.05,X40,ATH,PHARMA
65,SIEMENS,0.84,-14.02,45.98,25.51,73568.0,-26095.0,160000.0,4671.50,34.40,49.0,H-LC,3.62,51.0,-0.35,1.19,17.83,AR,ATH,ELECTRICAL

In [24]:
# Top N allocation
df_tmp = df_portfolio_features.sort_values(by = 'CurrAlloc%', ascending=False)
top_n_values = [10, 25, 50]

sum_df = pd.DataFrame({
    'Top_N': top_n_values,
    'Sum_Alloc%': [df_tmp['CurrAlloc%'].head(n).sum() for n in top_n_values]
})

sum_df

   Top_N  Sum_Alloc%
0     10       20.65
1     25       45.54
2     50       78.02

In [25]:
# market-cap-wise allocation
df_tmp = df_portfolio_features[cols]
df_tmp.groupby(df_tmp['Conviction'].str[-2:])['CurrAlloc%'].sum().sort_values(ascending=False)

Conviction
SC    44.30
MC    30.26
LC    25.45
Name: CurrAlloc%, dtype: float64

In [26]:
# criteria-wise allocation
df_portfolio_features.groupby('Criteria')['CurrAlloc%'].sum().sort_values(ascending=False)

Criteria
XY24     27.04
X40      25.51
X40N     14.96
AR        9.20
XR        8.25
XY25      7.43
OX40N     6.81
SR        0.81
Name: CurrAlloc%, dtype: float64

In [27]:
# conviction-wise allocation
df_portfolio_features.groupby('Conviction')['CurrAlloc%'].sum().sort_values(ascending=False)

Conviction
X-LC    23.24
X-MC    22.75
H-SC    21.59
X-SC    12.08
M-SC    10.05
H-MC     5.07
M-MC     2.09
H-LC     1.19
M-LC     1.02
L-SC     0.58
L-MC     0.35
Name: CurrAlloc%, dtype: float64

In [28]:
# sector-wise stats
df_tmp = df_portfolio_features.groupby('Category')[['CurrAlloc%', 'Current', 'Current P/L', 'FTT Amt']].sum().sort_values(by=['Current', 'Current P/L'], ascending=False)
df_tmp['Current P/L%'] = round(df_tmp['Current P/L'] * 100 / df_tmp['Current'], 2)
df_tmp['FTT%'] = round(df_tmp['FTT Amt'] * 100 / df_tmp['Current'], 2)
cols = ['CurrAlloc%', 'Current P/L%', 'FTT%']
df_tmp[cols].sort_values(by=['CurrAlloc%'], ascending=False)

               CurrAlloc%  Current P/L%    FTT%
Category
FMCG                15.01        -24.08   68.14
FINANCE             13.02        -23.04   73.19
IT                  11.71        -43.58  116.64
MISC                 6.89        -44.86  107.79
ELECTRICAL           6.67         -8.34   49.83
PAINTS               5.09        -44.49   69.58
INSURANCE            4.76         -6.16   42.48
BANKS                4.70        -22.17   84.19
PHARMA               4.15         -5.77   39.06
AUTO                 3.73        -30.91   82.85
AC                   2.15        -10.87   40.93
HEALTHCARE           1.93        -37.78   73.74
DURABLES             1.83        -57.23   95.48
FOOTWEAR             1.81        -82.49  155.66
TRAVEL               1.80        -85.46  178.32
BREWERIES            1.68         -4.01   25.61
APPARELS             1.62        -23.18   65.20
REALTY               1.45        -13.99   32.71
CERAMICS             1.40        -63.24  112.84
REFINERIES           1.36        -10.42   38.36
CEMENT               1.26        -59.12  178.17
CABLES               1.21          9.37   88.43
ENGINEERING          1.10        -63.75  138.65
JEWELLERY            1.10       -116.90  192.25
CHEMICALS            1.02        -93.84  251.99
ENTERTAINMENT        0.77        -87.51  199.34
TEXTILES             0.42        -65.41  112.58
HOTELS               0.37       -131.56  213.23

In [29]:
# money to be made criteria-wise
df_portfolio_features.groupby('Criteria')['FTT Amt'].agg(['sum', 'count']).sort_values(by='sum', ascending=False)

                sum  count
Criteria
XY24      3970548.0     21
X40       1753530.0     16
XR        1387092.0     12
AR        1337668.0     10
X40N      1294146.0     10
OX40N      877707.0     10
XY25       444017.0      5
SR         311742.0      2

In [30]:
# money to be made conviction-wise
df_portfolio_features.groupby('Conviction')['FTT Amt'].agg(['sum', 'count']).sort_values(by='sum', ascending=False)

                  sum  count
Conviction
H-SC        3898208.0     24
X-MC        1682881.0     15
X-LC        1659599.0     13
M-SC        1569572.0     14
X-SC        1561407.0     10
H-MC         399848.0      3
L-SC         214136.0      2
M-LC         155486.0      1
M-MC         106145.0      2
H-LC          73568.0      1
L-MC          55600.0      1

In [31]:
# money to be made criteria and conviction-wise
df_portfolio_features.groupby(['Conviction', 'Criteria'])['FTT Amt'].agg(['sum', 'count']).sort_values(by='sum', ascending=False)

                           sum  count
Conviction Criteria
H-SC       XY24      1345131.0      6
           AR         978143.0      5
M-SC       XY24       915794.0      6
X-LC       X40        887965.0      7
H-SC       XR         877079.0      7
X-SC       XY24       844446.0      4
X-MC       X40        658951.0      7
           X40N       520926.0      4
X-SC       X40N       510347.0      4
H-SC       OX40N      386113.0      4
M-SC       OX40N      382020.0      5
X-LC       XY24       362921.0      2
H-SC       SR         311742.0      2
X-LC       X40N       262873.0      2
X-MC       XY24       261361.0      2
           XY25       241643.0      2
H-MC       XY24       240895.0      1
X-SC       X40        206614.0      2
M-SC       XR         194365.0      2
H-MC       AR         158953.0      2
M-LC       XR         155486.0      1
X-LC       XY25       145840.0      2
L-SC       OX40N      109574.0      1
           XR         104562.0      1
M-SC       AR          77393.0      1
H-LC       AR          73568.0      1
M-MC       XY25        56534.0      1
L-MC       XR          55600.0      1
M-MC       AR          49611.0      1

In [32]:
# notebook execution time

end_time = time.time()
execution_time = round(end_time - start_time, 0)
print(f"Notebook execution time: {execution_time} seconds")

Notebook execution time: 33.0 seconds