<a href="https://colab.research.google.com/github/ankit-rathi/Quantvesting_v2/blob/main/myStocks_Portfolio_Analysis.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
'''
!pip install pandas==2.2.2 -qq
!pip install pyxirr -qq
!pip install ta -qq
!pip install yfinance==0.2.59 -qq
'''

'\n!pip install pandas==2.2.2 -qq\n!pip install pyxirr -qq\n!pip install ta -qq\n!pip install yfinance==0.2.59 -qq\n'

In [2]:
# import libraries

import numpy as np
import pandas as pd
import datetime
import warnings
warnings.filterwarnings('ignore')
import yfinance as yfin
import ta
import matplotlib.pyplot as plt
import requests

In [3]:
# notebook start time
import time
import datetime
import pytz

start_time = time.time()

# function to print date timestamp
def print_date_time():
  tz_NY = pytz.timezone('Asia/Kolkata')
  datetime_NY = datetime.datetime.now(tz_NY)
  print("Run date time (IST):", datetime_NY.strftime("%Y-%m-%d %H:%M:%S"))

In [4]:
# function to get booked and reserved amount
def get_amt():
  # fetch the JSON data from the URL
  url = "https://raw.githubusercontent.com/ankit-rathi/Tradevesting_v1/main/data/myPortfolioAmts.json"
  response = requests.get(url)
  pf_amts = response.json()  # parse the JSON data

  # extract values from the JSON
  py_booked_amt_dm = pf_amts["py_booked_amt_dm"]
  py_booked_amt_sv = pf_amts["py_booked_amt_sv"]
  cy_booked_amt_dm = pf_amts["cy_booked_amt_dm"]
  cy_booked_amt_sv = pf_amts["cy_booked_amt_sv"]
  reserve_amt_dm = pf_amts["reserve_amt_dm"]
  reserve_amt_sv = pf_amts["reserve_amt_sv"]

  # perform calculations
  py_booked_amt = py_booked_amt_dm + py_booked_amt_sv
  cy_booked_amt = cy_booked_amt_dm + cy_booked_amt_sv
  reserve_amt = reserve_amt_dm + reserve_amt_sv
  total_booked_amt = py_booked_amt + cy_booked_amt

  return total_booked_amt, reserve_amt, cy_booked_amt, py_booked_amt

gen_output = 0

In [5]:
# function to format the amount
def format_amt(number):
    abs_number = abs(number)

    if abs_number >= 1_00_00_000:  # Crores
        formatted_amt = f"{number / 1_00_00_000:.2f} C"
    elif abs_number >= 1_00_000:  # Lakhs
        formatted_amt = f"{number / 1_00_000:.2f} L"
    elif abs_number >= 1_000:  # Thousands
        formatted_amt = f"{number / 1_000:.2f} K"
    else:
        formatted_amt = f"{number:.2f}"

    return formatted_amt

# function to set start and end date
def get_start_end_date():
  start_date = (datetime.date.today() + datetime.timedelta(days=-365)).strftime('%Y-%m-%d')
  end_date = (datetime.date.today() + datetime.timedelta(days=1)).strftime('%Y-%m-%d')
  return start_date, end_date

# function to fetch my portfolio csv
def get_mypfs_df():
  mypfs_df = pd.read_csv('https://raw.githubusercontent.com/ankit-rathi/Tradevesting_v1/main/data/myPortfolioStocks.csv')
  return mypfs_df

# function to fetch my prospects csv
def get_mypps_df():
  mypps_df = pd.read_csv('https://raw.githubusercontent.com/ankit-rathi/Tradevesting_v1/main/data/myProspectsScrips.csv')
  return mypps_df

# function to fetch screener data
def get_myscreen_df():
  myscreen_df = pd.read_csv('https://raw.githubusercontent.com/ankit-rathi/Tradevesting_v1/main/data/myScreenerDB.csv')
  return myscreen_df

# function to fetch momentum data
def get_myinvmt_df():
  myinvmt_df = pd.read_csv('https://raw.githubusercontent.com/ankit-rathi/Tradevesting_v1/main/data/myInvestments.csv')
  return myinvmt_df

# function to get the stock ids
def get_stock_ids(df_pf):
  stock_n100 = df_pf['Symbol'].unique()

  exclude = ['CADILAHC','MMTC', 'MASFIN']

  stock_ids = df_pf[~df_pf['Symbol'].isin(exclude) ]['Symbol'].unique()

  #mypf = mypf[mypf.Forecast.notnull()]
  #stock_ids = mypf['Symbol'].unique()

  #stock_ids.sort()
  return stock_ids

# get features from screener data
def get_screener_features():
  myscreen_df = get_myscreen_df()
  cols = ['Symbol', 'EPS', 'MedPE', 'ROCE%', 'ROE%', 'CapType']
  return myscreen_df[cols]

# get relative strength
def get_relative_strength(stock_list):

    # Dictionary to store stock tickers and their corresponding percentage price change
    stock_changes = {}

    # Loop through each stock and fetch its price data
    for stock in stock_list:
        try:
            # Download the stock data for the given date range
            stock_data = yfin.Ticker(stock + '.NS').history(period='1mo', interval='1d')[map(str.title, ['open', 'close', 'low', 'high', 'volume'])]

            # Calculate the percentage change for the stock
            if len(stock_data) > 0:
                start_price = stock_data['Close'].iloc[0]
                end_price = stock_data['Close'].iloc[-1]
                percent_change = round(((end_price - start_price) / start_price) * 100, 2)
                stock_changes[stock] = percent_change
            else:
                stock_changes[stock] = np.nan  # If no data is available, set to NaN

        except Exception as e:
            print(f"Error fetching data for {stock}: {e}")
            stock_changes[stock] = np.nan

    # Create a DataFrame with stock tickers and their percentage changes
    df = pd.DataFrame(list(stock_changes.items()), columns=['Symbol', 'Percent_Change'])

    # Drop any stocks with missing data (NaN values)
    df = df.dropna()

    # Calculate the percentile rank based on percentage change
    df['RSP'] = round(df['Percent_Change'].rank(pct=True) * 100, 2)
    cols = ['Symbol', 'RSP']
    df = df[cols]
    # Sort by percentile rank (optional)
    df = df.sort_values(by='RSP', ascending=False).reset_index(drop=True)

    return df

In [6]:
# function to get stock technicals
def stock_prec_dev(stock_symbol):
    #stock_symbol = 'ULTRACEMCO.NS'
    short_window = 20
    mid_window = 50
    long_window = 200
    moving_avg = 'SMA'

    start = datetime.datetime(*map(int, start_date.split('-')))
    end = datetime.datetime(*map(int, end_date.split('-')))

    stock_df = yfin.Ticker(stock_symbol + '.NS').history(period='max', interval='1d')[map(str.title, ['open', 'close', 'low', 'high', 'volume'])]

    stock_df['Max'] = round(max(stock_df['Close']),2)
    stock_df = stock_df[(stock_df.index <= end_date) & (stock_df.index >= start_date)]
    stock_df['200_SMA'] = round(stock_df['Close'].rolling(window = 200, min_periods = 1).mean(),0)
    stock_df['Dev%_200'] = round((stock_df['Close'] - stock_df['200_SMA'])*100/stock_df['200_SMA'],2)
    stock_df.dropna(axis = 0, inplace = True) # remove any null rows

    stock_df['20_SMA'] = stock_df['Close'].rolling(window=20).mean()
    stock_df['50_SMA'] = stock_df['Close'].rolling(window=50).mean()
    stock_df['Symbol'] = stock_symbol

    stock_df['Close'] = round(stock_df['Close'],2)
    stock_df['Min'] = round(min(stock_df['Close']),2)
    stock_df['RSI_14'] = ta.momentum.RSIIndicator(close=stock_df['Close'], window=14).rsi()
    stock_df['RSI_14'] = round(stock_df['RSI_14'],0)
    stock_df['Prev_Close'] = stock_df['Close'].shift(1)
    stock_df.drop(['Open', 'Low', 'High', 'Volume'], axis=1, inplace=True)
    stock_df = stock_df.tail(1)

    max_SMA = max(stock_df['20_SMA'].item(), stock_df['50_SMA'].item(), stock_df['200_SMA'].item())
    min_SMA = min(stock_df['20_SMA'].item(), stock_df['50_SMA'].item(), stock_df['200_SMA'].item())
    ABS_Spread = max_SMA - min_SMA
    stock_df['Spread%'] = round((ABS_Spread / stock_df['200_SMA'].item()) * 100,2)

    return stock_df

# function to compute stock attributes
def get_common_features(stock_ids, df_mypf):

  df_prec_dev = pd.DataFrame()
  df_tmp = get_screener_features()
  df_rs = get_relative_strength(stock_ids)

  for stock_id in stock_ids:
      tmp = stock_prec_dev(stock_id)
      tmp = tmp.reset_index()
      df_prec_dev = pd.concat([df_prec_dev, tmp], ignore_index = True)
  df_prec_dev = pd.merge(df_prec_dev, df_mypf, on= 'Symbol')
  df_prec_dev = pd.merge(df_prec_dev, df_tmp, on= 'Symbol', how='left')
  df_prec_dev = pd.merge(df_prec_dev, df_rs, on= 'Symbol', how='left')
  #print(df_prec_dev.columns)
  df_prec_dev['Curr_PE'] = round(df_prec_dev['Close']/df_prec_dev['EPS'],1)
  df_prec_dev['Dev%_PE'] = round((df_prec_dev['Curr_PE'] - df_prec_dev['MedPE'])*100/df_prec_dev['MedPE'],2)
  df_prec_dev['Conviction'] = df_prec_dev['Conviction'] + '-' + df_prec_dev['CapType']
  return df_prec_dev

# function to arrange stock features
def arrange_features(df_stocks, common_cols, diff_cols):
  df_stocks_common = df_stocks[common_cols].drop_duplicates()
  df_stocks_diff = df_stocks[diff_cols]
  df_stocks_diff['Investment'] = df_stocks_diff['AvgCost'] * df_stocks_diff['Shares']
  df_stocks_diff = df_stocks_diff.groupby(['Symbol'])[['Shares', 'Investment']].aggregate(['sum']).reset_index()
  df_stocks_diff.columns = ['Symbol', 'Shares', 'Investment']
  df_stocks_diff['AvgCost'] = round(df_stocks_diff['Investment']/df_stocks_diff['Shares'],2)
  df_stocks = pd.merge(df_stocks_diff, df_stocks_common, on='Symbol')
  return df_stocks

# plot fact distribution across dimension
def plot_pie_chart(df, dimension, fact):
  # grouping the data by category and calculating the sum of fact for each type
  grouped_data = df.groupby(dimension)[fact].sum()

  # sorting the grouped data in descending order
  grouped_data = grouped_data.sort_values(ascending=False)

  # creating a pie chart
  grouped_data.plot.pie(autopct='%1.1f%%', startangle=90, figsize=(6, 6))

  # adding a title and displaying the plot
  plt.title(f'{dimension} {fact} Distribution')
  plt.ylabel('')  # To hide the y-label
  plt.show()

In [7]:
# function to get portfolio features

def get_portfolio_features(df_common_features):

  print_date_time()
  print('-------------------')

  #df_common_features["Target"] = df_common_features["Target"].fillna(df_common_features["Max"])
  df_common_features['NTT'] = np.where(df_common_features['Strategy']== 'NTT', df_common_features["Target"], df_common_features['Max'])
  df_common_features['LTT'] = np.where(df_common_features['Strategy']== 'BTT', df_common_features["Target"], df_common_features['Max'])
  df_common_features['BOL'] = df_common_features['Min']

  tmp_df = df_common_features[df_common_features['Symbol'].isin(mypf_df[mypf_df['InPortfolio'] != 'NA'].Symbol.values)]
  print('qualified stocks: '+str(len(tmp_df['Symbol'].unique())))
  tmp_df1 = tmp_df[tmp_df['LatestQtr'] == 1]
  print('with latest results: '+str(len(tmp_df1['Symbol'].unique())))
  tmp_df1 = tmp_df1[tmp_df1['StarStock'] == 1]
  print('still star stocks: '+str(len(tmp_df1['Symbol'].unique())))
  tmp_df['Investment'] = tmp_df['AvgCost'] * tmp_df['Shares']
  tmp_df['Current'] = round(tmp_df['Close'] * tmp_df['Shares'],0)
  tmp_df['Previous'] = tmp_df['Prev_Close'] * tmp_df['Shares']
  tmp_df['EstimatedST'] = tmp_df['NTT'] * tmp_df['Shares']
  tmp_df['EstimatedLT'] = tmp_df['LTT'] * tmp_df['Shares']
  tmp_df['Current P/L'] = round((tmp_df['Current'] - tmp_df['Investment']),0)
  tmp_df['Today P/L%'] = round((tmp_df['Current'] - tmp_df['Previous'])*100/tmp_df['Previous'],2)
  tmp_df['Current P/L%'] = round((tmp_df['Current'] - tmp_df['Investment'])*100/tmp_df['Investment'],2)
  tmp_df['EstimatedST P/L%'] = round((tmp_df['EstimatedST'] - tmp_df['Investment'])*100/tmp_df['Investment'],2)
  tmp_df['EstimatedLT P/L%'] = round((tmp_df['EstimatedLT'] - tmp_df['Investment'])*100/tmp_df['Investment'],2)
  tmp_df['NTT%'] = round((tmp_df['NTT'] - tmp_df['Close'])*100/tmp_df['Close'],2)
  tmp_df['LTT%'] = round((tmp_df['LTT'] - tmp_df['Close'])*100/tmp_df['Close'],2)
  tmp_df['Gained%'] = round((tmp_df['Close'] - tmp_df['BOL'])*100/tmp_df['BOL'],2)
  investment = round(sum(tmp_df['AvgCost']*tmp_df['Shares']),0)
  current = round(sum(tmp_df['Close']*tmp_df['Shares']),0)
  tmp_df['InitAlloc%'] = round(tmp_df['Investment']*100/investment,2)
  tmp_df['CurrAlloc%'] = round(tmp_df['Current']*100/current,2)
  tmp_df['FTT'] = tmp_df['LTT']
  tmp_df.loc[tmp_df['Strategy'] == 'NTT', 'FTT'] = tmp_df['NTT']
  tmp_df['FTT%'] = tmp_df['LTT%']
  tmp_df.loc[tmp_df['Strategy'] == 'NTT', 'FTT%'] = tmp_df['NTT%']
  tmp_df['FTT Amt'] = round(tmp_df['FTT%'] * tmp_df['Current']/100,0)
  tmp_df['OTT%'] = round((tmp_df['FTT'] - tmp_df['AvgCost'])*100/tmp_df['AvgCost'],2)
  tmp_df['RRR Ind'] = round(tmp_df['Current P/L']/tmp_df['FTT Amt'],2)
  tmp_df['Risk Ind'] = round(tmp_df['Current P/L%']*tmp_df['CurrAlloc%'],0)

  return tmp_df

# function to print portfolio features
def print_portfolio_stats(df_portfolio_features, myinvmt_df):
  from pyxirr import xirr

  total_booked_amt, reserve_amt, cy_booked_amt, py_booked_amt = get_amt()

  dates = myinvmt_df['Date'].values
  dates = np.append(dates, datetime.date.today().strftime('%d-%b-%y'))
  investment = myinvmt_df['Investment'].values
  dates= pd.to_datetime(dates)

  current = round(sum(df_portfolio_features['Close']*df_portfolio_features['Shares']),0) + reserve_amt
  investment_xirr = np.append(investment, current)
  cagr = round(xirr(pd.DataFrame({"dates": dates, "amounts": investment_xirr}))*100,2)

  investment = -sum(investment)
  invested = round(sum(df_portfolio_features['AvgCost']*df_portfolio_features['Shares']),0) + reserve_amt
  previous = round(sum(df_portfolio_features['Prev_Close']*df_portfolio_features['Shares']),0) + reserve_amt
  cy_invested = investment + py_booked_amt

  today_pnl_amount = current-previous
  today_pnl_percentage = round((current-previous)*100/previous,2)

  curr_pnl_amount = current-invested
  curr_pnl_percentage = round((curr_pnl_amount)*100/(cy_invested),2)

  cy_pnl_amount = cy_booked_amt + curr_pnl_amount
  cy_pnl_percentage = round((cy_pnl_amount)*100/cy_invested,2)

  overall_pnl_amount = total_booked_amt + curr_pnl_amount
  overall_pnl_percentage = round((overall_pnl_amount)*100/investment,2)

  estimate_st = round(sum(df_portfolio_features['FTT']*df_portfolio_features['Shares']),0)  + reserve_amt
  est_st_pnl_amount = estimate_st-current
  est_st_pnl_percentage = round((est_st_pnl_amount)*100/current,2)

  estimate_lt = round(sum(df_portfolio_features['LTT']*df_portfolio_features['Shares']),0)  + reserve_amt
  est_lt_pnl_amount = estimate_lt-current
  est_lt_pnl_percentage = round((est_lt_pnl_amount)*100/current,2)

  total_profit = round(sum(df_portfolio_features[df_portfolio_features['Current P/L%'] > 0]['Current']) - sum(df_portfolio_features[df_portfolio_features['Current P/L%'] > 0]['Investment']),0)
  total_loss = round(sum(df_portfolio_features[df_portfolio_features['Current P/L%'] < 0]['Current']) - sum(df_portfolio_features[df_portfolio_features['Current P/L%'] < 0]['Investment']),0)

  cy_booked_percentage = round((cy_booked_amt)*100/current,2)
  py_booked_percentage = round((py_booked_amt)*100/investment,2)
  total_booked_percentage = round((total_booked_amt)*100/investment,2)

  print('-------------------')
  print('Initial Investment: ', format_amt(investment))
  print('CY Investment: ', format_amt(cy_invested))
  print('Reserve: ', format_amt(reserve_amt))
  print('Current: ',  format_amt(current))
  print('-------------------')
  print('Today PnL: '+ '{} ({}%)'.format(format_amt(today_pnl_amount), today_pnl_percentage))
  print('Current PnL: '+ '{} ({}%)'.format(format_amt(curr_pnl_amount), curr_pnl_percentage))
  print('CY Booked + Current PnL: '+ '{} ({}%)'.format(format_amt(cy_pnl_amount), cy_pnl_percentage))
  print('-------------------')
  print('Total profit: ', format_amt(total_profit))
  print('Total loss: ', format_amt(total_loss))
  print('-------------------')
  print('Total Booked + Current PnL: '+ '{} ({}%)'.format(format_amt(overall_pnl_amount), overall_pnl_percentage))
  print('Total Booked PnL: '+ '{} ({}%)'.format(format_amt(total_booked_amt), total_booked_percentage))
  print('Curr Year Booked PnL: '+ '{} ({}%)'.format(format_amt(cy_booked_amt), cy_booked_percentage))
  print('Prev Year Booked PnL: '+ '{} ({}%)'.format(format_amt(py_booked_amt), py_booked_percentage))
  print('===================')
  print('Est FTT: ',  format_amt(estimate_st))
  print('Est FTT PnL: '+ '{} ({}%)'.format(format_amt(est_st_pnl_amount), est_st_pnl_percentage))

  print('===================')
  print('Deployed: ', format_amt(investment))

  print('Current: ', format_amt(current))

  print('CAGR/XIRR %: '+'{}%'.format(cagr))

In [8]:
# get start and end date
start_date, end_date = get_start_end_date()

# get portfolio and prospects data
mypfs_df = get_mypfs_df()
mypps_df = get_mypps_df()
myinvmt_df = get_myinvmt_df()

# merge above datasets
mypf_df = pd.merge(mypfs_df, mypps_df, on="Symbol")

# seggregate dm and sv portfolio
dm_pf = mypf_df[mypf_df['InPortfolio'] == 'DM']
sv_pf = mypf_df[mypf_df['InPortfolio'] == 'SV']

# build portfolio stock dataframe
dm_stocks = get_stock_ids(dm_pf)
sv_stocks = get_stock_ids(sv_pf)
df_stocks = pd.concat([dm_pf,sv_pf], ignore_index = True)

# arrange common and diff stock features
common_cols = ['Symbol', 'Target', 'Criteria', 'Strategy', 'CumlRnk', 'LatestQtr', 'StarStock', 'Conviction', 'Category', 'InFolio', 'XIRR', 'MBQ']
diff_cols = ['Symbol', 'AvgCost', 'Shares']
df_stocks = arrange_features(df_stocks, common_cols, diff_cols)

# get common features
stock_ids = df_stocks['Symbol'].values
df_common_features = get_common_features(stock_ids, df_stocks)

df_common_features.reset_index(drop=True, inplace=True)
df_common_features.drop(['Date'], axis=1, inplace=True)
# get and print portfolio features
df_portfolio_features = get_portfolio_features(df_common_features)

print_portfolio_stats(df_portfolio_features, myinvmt_df)

df = df_portfolio_features
#plot_pie_chart(df, 'CapType', 'Current')
list_ox40n = list(df[df['MBQ'].str.contains('OX40N', na=False)]['Symbol'].values)

Run date time (IST): 2026-07-03 11:23:39
-------------------
qualified stocks: 92
with latest results: 31
still star stocks: 20
-------------------
Initial Investment:  1.40 C
CY Investment:  1.82 C
Reserve:  1.49 K
Current:  1.54 C
-------------------
Today PnL: 32.10 K (0.21%)
Current PnL: -29.57 L (-16.21%)
CY Booked + Current PnL: -27.49 L (-15.07%)
-------------------
Total profit:  4.86 L
Total loss:  -34.43 L
-------------------
Total Booked + Current PnL: 15.38 L (11.03%)
Total Booked PnL: 44.95 L (32.22%)
Curr Year Booked PnL: 2.08 L (1.35%)
Prev Year Booked PnL: 42.87 L (30.73%)
===================
Est FTT:  2.55 C
Est FTT PnL: 1.01 C (66.0%)
===================
Deployed:  1.40 C
Current:  1.54 C
CAGR/XIRR %: 4.43%

In [9]:
# top 5 near their targets
cols = ['Symbol', 'Today P/L%', 'Current P/L%', 'FTT%', 'OTT%', 'FTT Amt', 'Current P/L', 'Current', 'FTT', 'Dev%_PE', 'RSI_14','Conviction', 'Spread%',  'CumlRnk', 'RRR Ind', 'CurrAlloc%', 'Gained%', 'Criteria', 'Strategy', 'Category']
df_tmp = df_portfolio_features[~df_portfolio_features['Symbol'].isin(['ENRIN','BLUSPRING','DIGITIDE'])]
df_tmp = df_tmp.sort_values(by = 'FTT Amt', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
59,PIDILITIND,-0.06,13.71,4.10,18.37,6578.0,19340.0,160450.0,1670.26,-20.38,70.0,X-LC,6.83,5.0,2.94,1.04,25.98,X40,ATH,CHEMICALS
49,JSWINFRA,-0.12,11.36,4.56,16.43,11261.0,25187.0,246961.0,342.00,-4.60,66.0,X-MC,10.06,61.0,2.24,1.61,40.02,X40N,NTT,REALTY
83,TTKPRESTIG,-1.70,-17.46,21.27,0.09,17692.0,-17599.0,83178.0,770.00,92.96,74.0,M-SC,5.99,250.0,-0.99,0.54,48.11,OX40N,NTT,DURABLES
56,MEDANTA,0.48,15.63,9.94,27.12,20288.0,27590.0,204107.0,1486.00,12.08,74.0,X-SC,6.83,87.0,1.36,1.33,40.64,XY24,NTT,HEALTHCARE
51,KOTAKBANK,-0.63,6.03,14.22,21.11,20877.0,8344.0,146816.0,453.24,-8.97,51.0,X-LC,4.31,12.0,0.40,0.96,12.28,X40,ATH,BANKS

In [10]:
# top 5 today
df_tmp = df_portfolio_features.sort_values(by = 'Today P/L%', ascending=False)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
33,HCLTECH,5.86,-25.93,64.05,21.51,114767.0,-62740.0,179184.0,1872.35,-22.25,52.0,X-LC,20.33,8.0,-0.55,1.17,10.36,X40,ATH,IT
61,RAJESHEXPO,3.57,-81.66,445.55,0.07,112109.0,-112015.0,25162.0,518.00,821.72,48.0,L-SC,38.94,268.0,-1.00,0.16,24.26,OX40N,NTT,JEWELLERY
7,BAJAJHFL,2.99,-18.45,98.80,62.13,220009.0,-50365.0,222681.0,181.50,-32.98,69.0,X-MC,8.66,60.0,-0.23,1.45,24.91,X40N,ATH,FINANCE
60,QUESS,2.45,19.15,45.96,73.90,58479.0,20446.0,127239.0,424.00,-36.09,86.0,X-SC,19.20,80.0,0.35,0.83,73.45,XY24,NTT,MISC
67,ROUTE,2.37,-57.80,298.46,68.16,167603.0,-76910.0,56156.0,2215.45,-65.82,63.0,H-SC,12.81,141.0,-0.46,0.37,33.78,SR,ATH,IT

In [11]:
# bottom 5 today
df_tmp = df_portfolio_features.sort_values(by = 'Today P/L%', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
23,DMART,-4.82,-4.20,35.29,29.60,84383.0,-10488.0,239112.0,5391.45,-19.25,35.0,X-LC,3.75,14.0,-0.12,1.56,9.29,X40N,ATH,FMCG
74,STARHEALTH,-2.18,11.39,32.20,47.26,100836.0,32031.0,313154.0,761.00,75.71,62.0,H-SC,14.98,173.0,0.32,2.04,37.42,XY24,NTT,INSURANCE
25,FINCABLES,-2.12,40.07,48.44,107.91,100175.0,59159.0,206803.0,1641.55,25.82,51.0,M-SC,26.43,220.0,0.59,1.35,55.59,OX40N,ATH,CABLES
68,SATIN,-1.86,41.23,7.51,51.83,29303.0,113907.0,390191.0,274.00,26.15,65.0,H-SC,41.48,159.0,3.89,2.54,90.08,XY24,NTT,FINANCE
83,TTKPRESTIG,-1.70,-17.46,21.27,0.09,17692.0,-17599.0,83178.0,770.00,92.96,74.0,M-SC,5.99,250.0,-0.99,0.54,48.11,OX40N,NTT,DURABLES

In [12]:
# top 5 to exit based on CumlRnk
df_tmp = df_portfolio_features[~df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])]
df_tmp = df_tmp[(df_tmp['Current P/L%'] > -1) & (df_tmp['Current P/L%'] < 1)].sort_values(by = 'CumlRnk', ascending=False)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
63,RECLTD,-0.24,-0.19,20.97,20.74,42524.0,-385.0,202785.0,446.00,9.37,62.0,M-MC,2.15,191.0,-0.01,1.32,20.85,XY25,NTT,FINANCE
55,MASFIN,1.85,-0.61,22.32,21.57,21735.0,-600.0,97380.0,397.04,-14.18,61.0,H-SC,2.41,167.0,-0.03,0.63,16.07,XR,ATH,FINANCE

In [13]:
# OX40N stocks to exit
df_tmp = df_portfolio_features[(df_portfolio_features['Symbol'].isin(list_ox40n))].sort_values(by = 'Current P/L%', ascending=False)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
25,FINCABLES,-2.12,40.07,48.44,107.91,100175.0,59159.0,206803.0,1641.55,25.82,51.0,M-SC,26.43,220.0,0.59,1.35,55.59,OX40N,ATH,CABLES
72,SIS,0.29,-2.00,23.74,21.26,25831.0,-2224.0,108808.0,528.00,2596.37,55.0,H-SC,24.95,168.0,-0.09,0.71,61.78,OX40N,NTT,MISC
16,CERA,0.08,-15.25,46.19,23.89,68857.0,-26829.0,149074.0,9475.00,-18.14,66.0,H-SC,13.20,153.0,-0.39,0.97,43.26,OX40N,NTT,CERAMICS
83,TTKPRESTIG,-1.70,-17.46,21.27,0.09,17692.0,-17599.0,83178.0,770.00,92.96,74.0,M-SC,5.99,250.0,-0.99,0.54,48.11,OX40N,NTT,DURABLES
43,INDIGOPNTS,0.36,-23.21,30.25,0.02,40548.0,-40515.0,134044.0,1408.00,104.24,69.0,M-SC,5.26,222.0,-1.00,0.87,52.08,OX40N,NTT,PAINTS

In [14]:
# top 5 to book for rotation
df_tmp = df_portfolio_features[(df_portfolio_features['Current P/L%'] > 20) ].sort_values(by = 'CumlRnk', ascending=False)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
25,FINCABLES,-2.12,40.07,48.44,107.91,100175.0,59159.0,206803.0,1641.55,25.82,51.0,M-SC,26.43,220.0,0.59,1.35,55.59,OX40N,ATH,CABLES
68,SATIN,-1.86,41.23,7.51,51.83,29303.0,113907.0,390191.0,274.00,26.15,65.0,H-SC,41.48,159.0,3.89,2.54,90.08,XY24,NTT,FINANCE

In [15]:
# top 5 to monitor for exit
df_tmp = df_portfolio_features[~df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])]
df_tmp = df_tmp[(df_tmp['Current P/L%'] > 0) ].sort_values(by = 'Dev%_PE', ascending=False)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
75,SURYODAY,-0.91,3.68,18.67,23.03,34663.0,6589.0,185660.0,216.00,101.75,66.0,H-SC,19.73,166.0,0.19,1.21,56.32,XR,NTT,BANKS
74,STARHEALTH,-2.18,11.39,32.20,47.26,100836.0,32031.0,313154.0,761.00,75.71,62.0,H-SC,14.98,173.0,0.32,2.04,37.42,XY24,NTT,INSURANCE
68,SATIN,-1.86,41.23,7.51,51.83,29303.0,113907.0,390191.0,274.00,26.15,65.0,H-SC,41.48,159.0,3.89,2.54,90.08,XY24,NTT,FINANCE
25,FINCABLES,-2.12,40.07,48.44,107.91,100175.0,59159.0,206803.0,1641.55,25.82,51.0,M-SC,26.43,220.0,0.59,1.35,55.59,OX40N,ATH,CABLES
91,ZYDUSLIFE,1.75,18.00,14.94,35.63,36946.0,37725.0,247299.0,1286.17,2.70,62.0,H-MC,14.38,120.0,1.02,1.61,30.03,AR,ATH,PHARMA

In [16]:
# top 5 to book for rotation from weak conviction
df_tmp = df_portfolio_features[~df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])]
df_tmp = df_tmp[~df_tmp['Criteria'].isin(['XY25','XY24','X40', 'X40N'])].sort_values(by = 'RRR Ind', ascending=False)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
91,ZYDUSLIFE,1.75,18.00,14.94,35.63,36946.0,37725.0,247299.0,1286.17,2.70,62.0,H-MC,14.38,120.0,1.02,1.61,30.03,AR,ATH,PHARMA
73,SONACOMS,0.20,14.81,20.80,38.69,24157.0,14980.0,116139.0,801.69,-8.99,77.0,M-MC,18.53,193.0,0.62,0.76,64.77,AR,ATH,AUTO
25,FINCABLES,-2.12,40.07,48.44,107.91,100175.0,59159.0,206803.0,1641.55,25.82,51.0,M-SC,26.43,220.0,0.59,1.35,55.59,OX40N,ATH,CABLES
75,SURYODAY,-0.91,3.68,18.67,23.03,34663.0,6589.0,185660.0,216.00,101.75,66.0,H-SC,19.73,166.0,0.19,1.21,56.32,XR,NTT,BANKS
55,MASFIN,1.85,-0.61,22.32,21.57,21735.0,-600.0,97380.0,397.04,-14.18,61.0,H-SC,2.41,167.0,-0.03,0.63,16.07,XR,ATH,FINANCE

In [17]:
# top 5 to accumulate based on lowest RSI_14
df_tmp = df_portfolio_features[df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])].sort_values(by = 'RSI_14', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
23,DMART,-4.82,-4.20,35.29,29.60,84383.0,-10488.0,239112.0,5391.45,-19.25,35.0,X-LC,3.75,14.0,-0.12,1.56,9.29,X40N,ATH,FMCG
81,TMPV,0.01,-21.24,73.41,36.58,205739.0,-75581.0,280260.0,600.00,-83.62,39.0,X-LC,7.51,4.0,-0.37,1.82,17.78,XY24,NTT,AUTO
26,GILLETTE,-0.43,-10.42,44.82,29.72,101934.0,-26466.0,227430.0,10978.86,-31.19,40.0,X-SC,6.33,83.0,-0.26,1.48,4.52,X40,ATH,FMCG
35,HDFCLIFE,-0.30,-6.83,42.44,32.71,59231.0,-10236.0,139564.0,811.41,-27.21,41.0,X-LC,16.02,31.0,-0.17,0.91,4.85,X40,ATH,INSURANCE
58,PGHH,0.50,-33.08,97.28,32.01,138994.0,-70640.0,142880.0,17616.87,-54.78,41.0,X-MC,21.05,57.0,-0.51,0.93,1.33,X40,ATH,FMCG

In [18]:
# top 5 to accumulate based on Spread and CumlRnk
df_tmp = df_portfolio_features[df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])]
df_tmp = df_tmp[(df_tmp['CumlRnk'] < 100)].sort_values(by = 'Spread%', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
17,CIPLA,0.44,18.40,12.70,33.43,23030.0,28177.0,181338.0,1648.14,-8.32,68.0,X-LC,2.14,18.0,1.22,1.18,23.79,X40N,ATH,PHARMA
84,UNITDSPR,1.11,2.01,18.38,20.77,43902.0,4712.0,238856.0,1644.00,-9.55,65.0,X-MC,3.15,64.0,0.11,1.56,13.94,X40N,NTT,BREWERIES
11,BERGEPAINT,0.91,-3.16,29.40,25.32,73386.0,-8137.0,249612.0,680.00,-8.48,54.0,X-MC,3.28,68.0,-0.11,1.63,29.91,XY24,NTT,PAINTS
19,COLPAL,-0.72,-22.29,79.97,39.86,163675.0,-58695.0,204670.0,3683.41,-6.07,53.0,X-MC,3.39,62.0,-0.36,1.33,15.77,XY25,ATH,FMCG
23,DMART,-4.82,-4.20,35.29,29.60,84383.0,-10488.0,239112.0,5391.45,-19.25,35.0,X-LC,3.75,14.0,-0.12,1.56,9.29,X40N,ATH,FMCG

In [19]:
# top 5 to accumulate based on lowest Gained%
df_tmp = df_portfolio_features[df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])].sort_values(by = 'Gained%', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
58,PGHH,0.50,-33.08,97.28,32.01,138994.0,-70640.0,142880.0,17616.87,-54.78,41.0,X-MC,21.05,57.0,-0.51,0.93,1.33,X40,ATH,FMCG
1,ABBOTINDIA,0.29,-13.45,36.41,18.07,56363.0,-24055.0,154800.0,35195.00,-26.29,46.0,X-MC,6.56,58.0,-0.43,1.01,2.46,X40,ATH,PHARMA
65,RELIANCE,-0.06,-16.38,49.84,25.30,83755.0,-32915.0,168048.0,1952.00,-18.49,46.0,X-LC,7.83,21.0,-0.39,1.09,3.49,XY25,BTT,REFINERIES
26,GILLETTE,-0.43,-10.42,44.82,29.72,101934.0,-26466.0,227430.0,10978.86,-31.19,40.0,X-SC,6.33,83.0,-0.26,1.48,4.52,X40,ATH,FMCG
32,HAVELLS,-0.51,-24.41,73.86,31.42,183118.0,-80065.0,247926.0,2052.62,-28.94,50.0,X-MC,12.94,63.0,-0.44,1.61,4.57,X40,ATH,ELECTRICAL

In [20]:
# top 5 to accumulate based on lowest CurrAlloc%
df_tmp = df_portfolio_features[df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])].sort_values(by = 'CurrAlloc%', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
10,BATAINDIA,-0.20,-55.03,200.65,35.20,116102.0,-70807.0,57863.0,2096.00,-24.19,49.0,X-SC,20.04,91.0,-0.61,0.38,14.76,X40,NTT,FOOTWEAR
64,RELAXO,-0.86,-47.94,192.57,52.31,145519.0,-69593.0,75567.0,1176.00,-44.54,67.0,X-SC,10.68,92.0,-0.48,0.49,68.96,X40N,NTT,FOOTWEAR
60,QUESS,2.45,19.15,45.96,73.90,58479.0,20446.0,127239.0,424.00,-36.09,86.0,X-SC,19.20,80.0,0.35,0.83,73.45,XY24,NTT,MISC
35,HDFCLIFE,-0.30,-6.83,42.44,32.71,59231.0,-10236.0,139564.0,811.41,-27.21,41.0,X-LC,16.02,31.0,-0.17,0.91,4.85,X40,ATH,INSURANCE
53,M&M,-0.67,2.35,19.28,22.08,27365.0,3253.0,141934.0,3762.31,-13.39,57.0,X-LC,9.00,25.0,0.12,0.92,8.75,X40N,ATH,AUTO

In [21]:
# top 5 to accumulate based on CumlRnk
df_tmp = df_portfolio_features.sort_values(by = 'CumlRnk', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
47,ITC,0.28,-23.43,55.49,19.06,144533.0,-79699.0,260467.0,452.00,-57.95,52.0,X-LC,13.18,1.0,-0.55,1.70,4.95,X40,NTT,FMCG
79,TCS,1.80,-38.20,102.06,24.88,292219.0,-176952.0,286321.0,4253.91,-47.56,45.0,X-LC,21.62,2.0,-0.61,1.86,6.19,X40,ATH,IT
45,INFY,1.21,-28.28,87.19,34.24,195651.0,-88492.0,224396.0,1972.00,-43.40,44.0,X-LC,20.37,3.0,-0.45,1.46,6.92,X40,NTT,IT
81,TMPV,0.01,-21.24,73.41,36.58,205739.0,-75581.0,280260.0,600.00,-83.62,39.0,X-LC,7.51,4.0,-0.37,1.82,17.78,XY24,NTT,AUTO
59,PIDILITIND,-0.06,13.71,4.10,18.37,6578.0,19340.0,160450.0,1670.26,-20.38,70.0,X-LC,6.83,5.0,2.94,1.04,25.98,X40,ATH,CHEMICALS

In [22]:
# top 5 for average up
df_tmp = df_portfolio_features[(df_portfolio_features['Dev%_200'] > 5)].sort_values(by = 'CurrAlloc%', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
44,INDUSINDBK,0.32,-30.12,90.16,32.89,48644.0,-23254.0,53953.0,1800.00,-354.20,59.0,L-MC,7.30,258.0,-0.48,0.35,33.02,XR,NTT,BANKS
64,RELAXO,-0.86,-47.94,192.57,52.31,145519.0,-69593.0,75567.0,1176.00,-44.54,67.0,X-SC,10.68,92.0,-0.48,0.49,68.96,X40N,NTT,FOOTWEAR
3,ALKYLAMINE,1.12,-21.28,144.58,92.54,114914.0,-21482.0,79481.0,4520.85,-15.74,59.0,H-SC,8.91,142.0,-0.19,0.52,50.93,SR,ATH,CHEMICALS
83,TTKPRESTIG,-1.70,-17.46,21.27,0.09,17692.0,-17599.0,83178.0,770.00,92.96,74.0,M-SC,5.99,250.0,-0.99,0.54,48.11,OX40N,NTT,DURABLES
72,SIS,0.29,-2.00,23.74,21.26,25831.0,-2224.0,108808.0,528.00,2596.37,55.0,H-SC,24.95,168.0,-0.09,0.71,61.78,OX40N,NTT,MISC

In [23]:
# top 5 RSP
df_tmp = df_portfolio_features.sort_values(by = 'RSP', ascending=False)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
60,QUESS,2.45,19.15,45.96,73.90,58479.0,20446.0,127239.0,424.0,-36.09,86.0,X-SC,19.20,80.0,0.35,0.83,73.45,XY24,NTT,MISC
69,SFL,-1.18,-25.81,70.69,26.63,137515.0,-67686.0,194532.0,1287.0,47.35,69.0,M-SC,19.12,242.0,-0.49,1.27,62.13,XY24,NTT,MISC
49,JSWINFRA,-0.12,11.36,4.56,16.43,11261.0,25187.0,246961.0,342.0,-4.60,66.0,X-MC,10.06,61.0,2.24,1.61,40.02,X40N,NTT,REALTY
0,5PAISA,2.00,-25.18,50.89,12.90,83199.0,-55008.0,163488.0,593.0,140.38,81.0,H-SC,2.27,170.0,-0.66,1.06,57.77,OX40N,NTT,FINANCE
64,RELAXO,-0.86,-47.94,192.57,52.31,145519.0,-69593.0,75567.0,1176.0,-44.54,67.0,X-SC,10.68,92.0,-0.48,0.49,68.96,X40N,NTT,FOOTWEAR

In [24]:
# Top N allocation
df_tmp = df_portfolio_features.sort_values(by = 'CurrAlloc%', ascending=False)
top_n_values = [10, 25, 50]

sum_df = pd.DataFrame({
    'Top_N': top_n_values,
    'Sum_Alloc%': [df_tmp['CurrAlloc%'].head(n).sum() for n in top_n_values]
})

sum_df

   Top_N  Sum_Alloc%
0     10       19.42
1     25       42.57
2     50       72.72

In [25]:
# market-cap-wise allocation
df_tmp = df_portfolio_features[cols]
df_tmp.groupby(df_tmp['Conviction'].str[-2:])['CurrAlloc%'].sum().sort_values(ascending=False)

Conviction
SC    43.85
LC    30.27
MC    25.91
Name: CurrAlloc%, dtype: float64

In [26]:
# criteria-wise allocation
df_portfolio_features.groupby('Criteria')['CurrAlloc%'].sum().sort_values(ascending=False)

Criteria
XY24     27.96
X40      24.49
X40N     17.45
XR        8.85
OX40N     7.21
AR        6.74
XY25      6.44
SR        0.89
Name: CurrAlloc%, dtype: float64

In [27]:
# conviction-wise allocation
df_portfolio_features.groupby('Conviction')['CurrAlloc%'].sum().sort_values(ascending=False)

Conviction
X-LC    28.32
H-SC    23.00
X-MC    20.79
M-SC    10.17
X-SC    10.11
H-MC     2.69
M-MC     2.08
H-LC     1.15
M-LC     0.80
L-SC     0.57
L-MC     0.35
Name: CurrAlloc%, dtype: float64

In [28]:
# sector-wise stats
df_tmp = df_portfolio_features.groupby('Category')[['CurrAlloc%', 'Current', 'Current P/L', 'FTT Amt']].sum().sort_values(by=['Current', 'Current P/L'], ascending=False)
df_tmp['Current P/L%'] = round(df_tmp['Current P/L'] * 100 / df_tmp['Current'], 2)
df_tmp['FTT%'] = round(df_tmp['FTT Amt'] * 100 / df_tmp['Current'], 2)
cols = ['CurrAlloc%', 'Current P/L%', 'FTT%']
df_tmp[cols].sort_values(by=['CurrAlloc%'], ascending=False)

               CurrAlloc%  Current P/L%    FTT%
Category
FMCG                14.42        -19.57   61.52
FINANCE             11.51         -4.16   49.30
IT                   9.57        -53.51  130.26
MISC                 7.25        -20.67   72.44
AUTO                 6.68         -6.61   46.37
BANKS                5.75         -2.94   50.53
PAINTS               5.57        -15.07   34.70
INSURANCE            5.21         -3.42   38.30
PHARMA               5.06          4.56   24.99
ELECTRICAL           4.05        -13.74   53.89
CHEMICALS            2.18        -21.06   92.87
HEALTHCARE           2.12        -10.12   38.86
APPARELS             1.95         10.56   19.49
AC                   1.75        -18.36   50.46
FOOTWEAR             1.74        -65.17  131.40
DURABLES             1.62        -55.34   93.13
REALTY               1.61         10.20    4.56
BREWERIES            1.56          1.97   18.38
TRAVEL               1.54        -89.38  184.20
CERAMICS             1.44        -39.06   81.31
CABLES               1.35         28.61   48.44
ENGINEERING          1.31        -20.73   75.95
REFINERIES           1.09        -19.59   49.84
CEMENT               1.08        -61.67  182.61
JEWELLERY            1.03       -101.89  172.04
ENTERTAINMENT        0.75        -66.89  166.43
TEXTILES             0.43        -39.10   78.77
HOTELS               0.41        -82.25  146.53

In [29]:
# money to be made criteria-wise
df_portfolio_features.groupby('Criteria')['FTT Amt'].agg(['sum', 'count']).sort_values(by='sum', ascending=False)

                sum  count
Criteria
XY24      3305621.0     21
X40       1913678.0     19
XR        1321499.0     13
AR        1144294.0      9
X40N      1041541.0     13
OX40N      683807.0     10
XY25       445527.0      5
SR         282517.0      2

In [30]:
# money to be made conviction-wise
df_portfolio_features.groupby('Conviction')['FTT Amt'].agg(['sum', 'count']).sort_values(by='sum', ascending=False)

                  sum  count
Conviction
H-SC        3249099.0     24
X-LC        1926032.0     21
X-MC        1524560.0     15
M-SC        1356843.0     14
X-SC        1252677.0      9
H-MC         284400.0      2
L-SC         203403.0      2
M-LC         168639.0      1
M-MC          66681.0      2
H-LC          57506.0      1
L-MC          48644.0      1

In [31]:
# money to be made criteria and conviction-wise
df_portfolio_features.groupby(['Conviction', 'Criteria'])['FTT Amt'].agg(['sum', 'count']).sort_values(by='sum', ascending=False)

                           sum  count
Conviction Criteria
X-LC       X40       1034486.0     10
H-SC       AR         953397.0      5
           XY24       936740.0      6
M-SC       XY24       807936.0      6
H-SC       XR         794566.0      7
X-SC       XY24       746766.0      4
X-MC       X40        661156.0      7
           X40N       400204.0      4
X-LC       X40N       353462.0      6
           XY24       351620.0      2
M-SC       OX40N      289819.0      5
X-SC       X40N       287875.0      3
H-SC       SR         282517.0      2
           OX40N      281879.0      4
X-MC       XY25       248095.0      2
H-MC       XY24       247454.0      1
X-SC       X40        218036.0      2
X-MC       XY24       215105.0      2
M-SC       XR         186800.0      2
M-LC       XR         168639.0      1
X-LC       XY25       154908.0      2
L-SC       OX40N      112109.0      1
           XR          91294.0      1
M-SC       AR          72288.0      1
H-LC       AR          57506.0      1
L-MC       XR          48644.0      1
M-MC       XY25        42524.0      1
H-MC       AR          36946.0      1
X-LC       XR          31556.0      1
M-MC       AR          24157.0      1

In [32]:
# notebook execution time

end_time = time.time()
execution_time = round(end_time - start_time, 0)
print(f"Notebook execution time: {execution_time} seconds")

Notebook execution time: 51.0 seconds