<a href="https://colab.research.google.com/github/ankit-rathi/Quantvesting_v2/blob/main/myStocks_Portfolio_Analysis.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
'''
!pip install pandas==2.2.2 -qq
!pip install pyxirr -qq
!pip install ta -qq
!pip install yfinance==0.2.59 -qq
'''

'\n!pip install pandas==2.2.2 -qq\n!pip install pyxirr -qq\n!pip install ta -qq\n!pip install yfinance==0.2.59 -qq\n'

In [2]:
# import libraries

import numpy as np
import pandas as pd
import datetime
import warnings
warnings.filterwarnings('ignore')
import yfinance as yfin
import ta
import matplotlib.pyplot as plt
import requests

In [3]:
# notebook start time
import time
import datetime
import pytz

start_time = time.time()

# function to print date timestamp
def print_date_time():
  tz_NY = pytz.timezone('Asia/Kolkata')
  datetime_NY = datetime.datetime.now(tz_NY)
  print("Run date time (IST):", datetime_NY.strftime("%Y-%m-%d %H:%M:%S"))

In [4]:
# function to get booked and reserved amount
def get_amt():
  # fetch the JSON data from the URL
  url = "https://raw.githubusercontent.com/ankit-rathi/Tradevesting_v1/main/data/myPortfolioAmts.json"
  response = requests.get(url)
  pf_amts = response.json()  # parse the JSON data

  # extract values from the JSON
  py_booked_amt_dm = pf_amts["py_booked_amt_dm"]
  py_booked_amt_sv = pf_amts["py_booked_amt_sv"]
  cy_booked_amt_dm = pf_amts["cy_booked_amt_dm"]
  cy_booked_amt_sv = pf_amts["cy_booked_amt_sv"]
  reserve_amt_dm = pf_amts["reserve_amt_dm"]
  reserve_amt_sv = pf_amts["reserve_amt_sv"]

  # perform calculations
  py_booked_amt = py_booked_amt_dm + py_booked_amt_sv
  cy_booked_amt = cy_booked_amt_dm + cy_booked_amt_sv
  reserve_amt = reserve_amt_dm + reserve_amt_sv
  total_booked_amt = py_booked_amt + cy_booked_amt

  return total_booked_amt, reserve_amt, cy_booked_amt, py_booked_amt

gen_output = 0

In [5]:
# function to format the amount
def format_amt(number):
    abs_number = abs(number)

    if abs_number >= 1_00_00_000:  # Crores
        formatted_amt = f"{number / 1_00_00_000:.2f} C"
    elif abs_number >= 1_00_000:  # Lakhs
        formatted_amt = f"{number / 1_00_000:.2f} L"
    elif abs_number >= 1_000:  # Thousands
        formatted_amt = f"{number / 1_000:.2f} K"
    else:
        formatted_amt = f"{number:.2f}"

    return formatted_amt

# function to set start and end date
def get_start_end_date():
  start_date = (datetime.date.today() + datetime.timedelta(days=-365)).strftime('%Y-%m-%d')
  end_date = (datetime.date.today() + datetime.timedelta(days=1)).strftime('%Y-%m-%d')
  return start_date, end_date

# function to fetch my portfolio csv
def get_mypfs_df():
  mypfs_df = pd.read_csv('https://raw.githubusercontent.com/ankit-rathi/Tradevesting_v1/main/data/myPortfolioStocks.csv')
  return mypfs_df

# function to fetch my prospects csv
def get_mypps_df():
  mypps_df = pd.read_csv('https://raw.githubusercontent.com/ankit-rathi/Tradevesting_v1/main/data/myProspectsScrips.csv')
  return mypps_df

# function to fetch screener data
def get_myscreen_df():
  myscreen_df = pd.read_csv('https://raw.githubusercontent.com/ankit-rathi/Tradevesting_v1/main/data/myScreenerDB.csv')
  return myscreen_df

# function to fetch momentum data
def get_myinvmt_df():
  myinvmt_df = pd.read_csv('https://raw.githubusercontent.com/ankit-rathi/Tradevesting_v1/main/data/myInvestments.csv')
  return myinvmt_df

# function to get the stock ids
def get_stock_ids(df_pf):
  stock_n100 = df_pf['Symbol'].unique()

  exclude = ['CADILAHC','MMTC', 'MASFIN']

  stock_ids = df_pf[~df_pf['Symbol'].isin(exclude) ]['Symbol'].unique()

  #mypf = mypf[mypf.Forecast.notnull()]
  #stock_ids = mypf['Symbol'].unique()

  #stock_ids.sort()
  return stock_ids

# get features from screener data
def get_screener_features():
  myscreen_df = get_myscreen_df()
  cols = ['Symbol', 'EPS', 'MedPE', 'ROCE%', 'ROE%', 'CapType']
  return myscreen_df[cols]

# get relative strength
def get_relative_strength(stock_list):

    # Dictionary to store stock tickers and their corresponding percentage price change
    stock_changes = {}

    # Loop through each stock and fetch its price data
    for stock in stock_list:
        try:
            # Download the stock data for the given date range
            stock_data = yfin.Ticker(stock + '.NS').history(period='1mo', interval='1d')[map(str.title, ['open', 'close', 'low', 'high', 'volume'])]

            # Calculate the percentage change for the stock
            if len(stock_data) > 0:
                start_price = stock_data['Close'].iloc[0]
                end_price = stock_data['Close'].iloc[-1]
                percent_change = round(((end_price - start_price) / start_price) * 100, 2)
                stock_changes[stock] = percent_change
            else:
                stock_changes[stock] = np.nan  # If no data is available, set to NaN

        except Exception as e:
            print(f"Error fetching data for {stock}: {e}")
            stock_changes[stock] = np.nan

    # Create a DataFrame with stock tickers and their percentage changes
    df = pd.DataFrame(list(stock_changes.items()), columns=['Symbol', 'Percent_Change'])

    # Drop any stocks with missing data (NaN values)
    df = df.dropna()

    # Calculate the percentile rank based on percentage change
    df['RSP'] = round(df['Percent_Change'].rank(pct=True) * 100, 2)
    cols = ['Symbol', 'RSP']
    df = df[cols]
    # Sort by percentile rank (optional)
    df = df.sort_values(by='RSP', ascending=False).reset_index(drop=True)

    return df

In [6]:
# function to get stock technicals
def stock_prec_dev(stock_symbol):
    #stock_symbol = 'ULTRACEMCO.NS'
    short_window = 20
    mid_window = 50
    long_window = 200
    moving_avg = 'SMA'

    start = datetime.datetime(*map(int, start_date.split('-')))
    end = datetime.datetime(*map(int, end_date.split('-')))

    stock_df = yfin.Ticker(stock_symbol + '.NS').history(period='max', interval='1d')[map(str.title, ['open', 'close', 'low', 'high', 'volume'])]

    stock_df['Max'] = round(max(stock_df['Close']),2)
    stock_df = stock_df[(stock_df.index <= end_date) & (stock_df.index >= start_date)]
    stock_df['200_SMA'] = round(stock_df['Close'].rolling(window = 200, min_periods = 1).mean(),0)
    stock_df['Dev%_200'] = round((stock_df['Close'] - stock_df['200_SMA'])*100/stock_df['200_SMA'],2)
    stock_df.dropna(axis = 0, inplace = True) # remove any null rows

    stock_df['20_SMA'] = stock_df['Close'].rolling(window=20).mean()
    stock_df['50_SMA'] = stock_df['Close'].rolling(window=50).mean()
    stock_df['Symbol'] = stock_symbol

    stock_df['Close'] = round(stock_df['Close'],2)
    stock_df['Min'] = round(min(stock_df['Close']),2)
    stock_df['RSI_14'] = ta.momentum.RSIIndicator(close=stock_df['Close'], window=14).rsi()
    stock_df['RSI_14'] = round(stock_df['RSI_14'],0)
    stock_df['Prev_Close'] = stock_df['Close'].shift(1)
    stock_df.drop(['Open', 'Low', 'High', 'Volume'], axis=1, inplace=True)
    stock_df = stock_df.tail(1)

    max_SMA = max(stock_df['20_SMA'].item(), stock_df['50_SMA'].item(), stock_df['200_SMA'].item())
    min_SMA = min(stock_df['20_SMA'].item(), stock_df['50_SMA'].item(), stock_df['200_SMA'].item())
    ABS_Spread = max_SMA - min_SMA
    stock_df['Spread%'] = round((ABS_Spread / stock_df['200_SMA'].item()) * 100,2)

    return stock_df

# function to compute stock attributes
def get_common_features(stock_ids, df_mypf):

  df_prec_dev = pd.DataFrame()
  df_tmp = get_screener_features()
  df_rs = get_relative_strength(stock_ids)

  for stock_id in stock_ids:
      tmp = stock_prec_dev(stock_id)
      tmp = tmp.reset_index()
      df_prec_dev = pd.concat([df_prec_dev, tmp], ignore_index = True)
  df_prec_dev = pd.merge(df_prec_dev, df_mypf, on= 'Symbol')
  df_prec_dev = pd.merge(df_prec_dev, df_tmp, on= 'Symbol', how='left')
  df_prec_dev = pd.merge(df_prec_dev, df_rs, on= 'Symbol', how='left')
  #print(df_prec_dev.columns)
  df_prec_dev['Curr_PE'] = round(df_prec_dev['Close']/df_prec_dev['EPS'],1)
  df_prec_dev['Dev%_PE'] = round((df_prec_dev['Curr_PE'] - df_prec_dev['MedPE'])*100/df_prec_dev['MedPE'],2)
  df_prec_dev['Conviction'] = df_prec_dev['Conviction'] + '-' + df_prec_dev['CapType']
  return df_prec_dev

# function to arrange stock features
def arrange_features(df_stocks, common_cols, diff_cols):
  df_stocks_common = df_stocks[common_cols].drop_duplicates()
  df_stocks_diff = df_stocks[diff_cols]
  df_stocks_diff['Investment'] = df_stocks_diff['AvgCost'] * df_stocks_diff['Shares']
  df_stocks_diff = df_stocks_diff.groupby(['Symbol'])[['Shares', 'Investment']].aggregate(['sum']).reset_index()
  df_stocks_diff.columns = ['Symbol', 'Shares', 'Investment']
  df_stocks_diff['AvgCost'] = round(df_stocks_diff['Investment']/df_stocks_diff['Shares'],2)
  df_stocks = pd.merge(df_stocks_diff, df_stocks_common, on='Symbol')
  return df_stocks

# plot fact distribution across dimension
def plot_pie_chart(df, dimension, fact):
  # grouping the data by category and calculating the sum of fact for each type
  grouped_data = df.groupby(dimension)[fact].sum()

  # sorting the grouped data in descending order
  grouped_data = grouped_data.sort_values(ascending=False)

  # creating a pie chart
  grouped_data.plot.pie(autopct='%1.1f%%', startangle=90, figsize=(6, 6))

  # adding a title and displaying the plot
  plt.title(f'{dimension} {fact} Distribution')
  plt.ylabel('')  # To hide the y-label
  plt.show()

In [7]:
# function to get portfolio features

def get_portfolio_features(df_common_features):

  print_date_time()
  print('-------------------')

  #df_common_features["Target"] = df_common_features["Target"].fillna(df_common_features["Max"])
  df_common_features['NTT'] = np.where(df_common_features['Strategy']== 'NTT', df_common_features["Target"], df_common_features['Max'])
  df_common_features['LTT'] = np.where(df_common_features['Strategy']== 'BTT', df_common_features["Target"], df_common_features['Max'])
  df_common_features['BOL'] = df_common_features['Min']

  tmp_df = df_common_features[df_common_features['Symbol'].isin(mypf_df[mypf_df['InPortfolio'] != 'NA'].Symbol.values)]
  print('qualified stocks: '+str(len(tmp_df['Symbol'].unique())))
  tmp_df1 = tmp_df[tmp_df['LatestQtr'] == 1]
  print('with latest results: '+str(len(tmp_df1['Symbol'].unique())))
  tmp_df1 = tmp_df1[tmp_df1['StarStock'] == 1]
  print('still star stocks: '+str(len(tmp_df1['Symbol'].unique())))
  tmp_df['Investment'] = tmp_df['AvgCost'] * tmp_df['Shares']
  tmp_df['Current'] = round(tmp_df['Close'] * tmp_df['Shares'],0)
  tmp_df['Previous'] = tmp_df['Prev_Close'] * tmp_df['Shares']
  tmp_df['EstimatedST'] = tmp_df['NTT'] * tmp_df['Shares']
  tmp_df['EstimatedLT'] = tmp_df['LTT'] * tmp_df['Shares']
  tmp_df['Current P/L'] = round((tmp_df['Current'] - tmp_df['Investment']),0)
  tmp_df['Today P/L%'] = round((tmp_df['Current'] - tmp_df['Previous'])*100/tmp_df['Previous'],2)
  tmp_df['Current P/L%'] = round((tmp_df['Current'] - tmp_df['Investment'])*100/tmp_df['Investment'],2)
  tmp_df['EstimatedST P/L%'] = round((tmp_df['EstimatedST'] - tmp_df['Investment'])*100/tmp_df['Investment'],2)
  tmp_df['EstimatedLT P/L%'] = round((tmp_df['EstimatedLT'] - tmp_df['Investment'])*100/tmp_df['Investment'],2)
  tmp_df['NTT%'] = round((tmp_df['NTT'] - tmp_df['Close'])*100/tmp_df['Close'],2)
  tmp_df['LTT%'] = round((tmp_df['LTT'] - tmp_df['Close'])*100/tmp_df['Close'],2)
  tmp_df['Gained%'] = round((tmp_df['Close'] - tmp_df['BOL'])*100/tmp_df['BOL'],2)
  investment = round(sum(tmp_df['AvgCost']*tmp_df['Shares']),0)
  current = round(sum(tmp_df['Close']*tmp_df['Shares']),0)
  tmp_df['InitAlloc%'] = round(tmp_df['Investment']*100/investment,2)
  tmp_df['CurrAlloc%'] = round(tmp_df['Current']*100/current,2)
  tmp_df['FTT'] = tmp_df['LTT']
  tmp_df.loc[tmp_df['Strategy'] == 'NTT', 'FTT'] = tmp_df['NTT']
  tmp_df['FTT%'] = tmp_df['LTT%']
  tmp_df.loc[tmp_df['Strategy'] == 'NTT', 'FTT%'] = tmp_df['NTT%']
  tmp_df['FTT Amt'] = round(tmp_df['FTT%'] * tmp_df['Current']/100,0)
  tmp_df['OTT%'] = round((tmp_df['FTT'] - tmp_df['AvgCost'])*100/tmp_df['AvgCost'],2)
  tmp_df['RRR Ind'] = round(tmp_df['Current P/L']/tmp_df['FTT Amt'],2)
  tmp_df['Risk Ind'] = round(tmp_df['Current P/L%']*tmp_df['CurrAlloc%'],0)

  return tmp_df

# function to print portfolio features
def print_portfolio_stats(df_portfolio_features, myinvmt_df):
  from pyxirr import xirr

  total_booked_amt, reserve_amt, cy_booked_amt, py_booked_amt = get_amt()

  dates = myinvmt_df['Date'].values
  dates = np.append(dates, datetime.date.today().strftime('%d-%b-%y'))
  investment = myinvmt_df['Investment'].values
  dates= pd.to_datetime(dates)

  current = round(sum(df_portfolio_features['Close']*df_portfolio_features['Shares']),0) + reserve_amt
  investment_xirr = np.append(investment, current)
  cagr = round(xirr(pd.DataFrame({"dates": dates, "amounts": investment_xirr}))*100,2)

  investment = -sum(investment)
  invested = round(sum(df_portfolio_features['AvgCost']*df_portfolio_features['Shares']),0) + reserve_amt
  previous = round(sum(df_portfolio_features['Prev_Close']*df_portfolio_features['Shares']),0) + reserve_amt
  cy_invested = investment + py_booked_amt

  today_pnl_amount = current-previous
  today_pnl_percentage = round((current-previous)*100/previous,2)

  curr_pnl_amount = current-invested
  curr_pnl_percentage = round((curr_pnl_amount)*100/(cy_invested),2)

  cy_pnl_amount = cy_booked_amt + curr_pnl_amount
  cy_pnl_percentage = round((cy_pnl_amount)*100/cy_invested,2)

  overall_pnl_amount = total_booked_amt + curr_pnl_amount
  overall_pnl_percentage = round((overall_pnl_amount)*100/investment,2)

  estimate_st = round(sum(df_portfolio_features['FTT']*df_portfolio_features['Shares']),0)  + reserve_amt
  est_st_pnl_amount = estimate_st-current
  est_st_pnl_percentage = round((est_st_pnl_amount)*100/current,2)

  estimate_lt = round(sum(df_portfolio_features['LTT']*df_portfolio_features['Shares']),0)  + reserve_amt
  est_lt_pnl_amount = estimate_lt-current
  est_lt_pnl_percentage = round((est_lt_pnl_amount)*100/current,2)

  total_profit = round(sum(df_portfolio_features[df_portfolio_features['Current P/L%'] > 0]['Current']) - sum(df_portfolio_features[df_portfolio_features['Current P/L%'] > 0]['Investment']),0)
  total_loss = round(sum(df_portfolio_features[df_portfolio_features['Current P/L%'] < 0]['Current']) - sum(df_portfolio_features[df_portfolio_features['Current P/L%'] < 0]['Investment']),0)

  cy_booked_percentage = round((cy_booked_amt)*100/current,2)
  py_booked_percentage = round((py_booked_amt)*100/investment,2)
  total_booked_percentage = round((total_booked_amt)*100/investment,2)

  print('-------------------')
  print('Initial Investment: ', format_amt(investment))
  print('CY Investment: ', format_amt(cy_invested))
  print('Reserve: ', format_amt(reserve_amt))
  print('Current: ',  format_amt(current))
  print('-------------------')
  print('Today PnL: '+ '{} ({}%)'.format(format_amt(today_pnl_amount), today_pnl_percentage))
  print('Current PnL: '+ '{} ({}%)'.format(format_amt(curr_pnl_amount), curr_pnl_percentage))
  print('CY Booked + Current PnL: '+ '{} ({}%)'.format(format_amt(cy_pnl_amount), cy_pnl_percentage))
  print('-------------------')
  print('Total profit: ', format_amt(total_profit))
  print('Total loss: ', format_amt(total_loss))
  print('-------------------')
  print('Total Booked + Current PnL: '+ '{} ({}%)'.format(format_amt(overall_pnl_amount), overall_pnl_percentage))
  print('Total Booked PnL: '+ '{} ({}%)'.format(format_amt(total_booked_amt), total_booked_percentage))
  print('Curr Year Booked PnL: '+ '{} ({}%)'.format(format_amt(cy_booked_amt), cy_booked_percentage))
  print('Prev Year Booked PnL: '+ '{} ({}%)'.format(format_amt(py_booked_amt), py_booked_percentage))
  print('===================')
  print('Est FTT: ',  format_amt(estimate_st))
  print('Est FTT PnL: '+ '{} ({}%)'.format(format_amt(est_st_pnl_amount), est_st_pnl_percentage))

  print('===================')
  print('Deployed: ', format_amt(investment))

  print('Current: ', format_amt(current))

  print('CAGR/XIRR %: '+'{}%'.format(cagr))

In [8]:
# get start and end date
start_date, end_date = get_start_end_date()

# get portfolio and prospects data
mypfs_df = get_mypfs_df()
mypps_df = get_mypps_df()
myinvmt_df = get_myinvmt_df()

# merge above datasets
mypf_df = pd.merge(mypfs_df, mypps_df, on="Symbol")

# seggregate dm and sv portfolio
dm_pf = mypf_df[mypf_df['InPortfolio'] == 'DM']
sv_pf = mypf_df[mypf_df['InPortfolio'] == 'SV']

# build portfolio stock dataframe
dm_stocks = get_stock_ids(dm_pf)
sv_stocks = get_stock_ids(sv_pf)
df_stocks = pd.concat([dm_pf,sv_pf], ignore_index = True)

# arrange common and diff stock features
common_cols = ['Symbol', 'Target', 'Criteria', 'Strategy', 'CumlRnk', 'LatestQtr', 'StarStock', 'Conviction', 'Category', 'InFolio', 'XIRR', 'MBQ']
diff_cols = ['Symbol', 'AvgCost', 'Shares']
df_stocks = arrange_features(df_stocks, common_cols, diff_cols)

# get common features
stock_ids = df_stocks['Symbol'].values
df_common_features = get_common_features(stock_ids, df_stocks)

df_common_features.reset_index(drop=True, inplace=True)
df_common_features.drop(['Date'], axis=1, inplace=True)
# get and print portfolio features
df_portfolio_features = get_portfolio_features(df_common_features)

print_portfolio_stats(df_portfolio_features, myinvmt_df)

df = df_portfolio_features
#plot_pie_chart(df, 'CapType', 'Current')
list_ox40n = list(df[df['MBQ'].str.contains('OX40N', na=False)]['Symbol'].values)

Run date time (IST): 2026-04-27 15:44:17
-------------------
qualified stocks: 92
with latest results: 31
still star stocks: 20
-------------------
Initial Investment:  1.40 C
CY Investment:  1.82 C
Reserve:  1.49 K
Current:  1.50 C
-------------------
Today PnL: 2.97 L (2.03%)
Current PnL: -33.50 L (-18.37%)
CY Booked + Current PnL: -31.42 L (-17.23%)
-------------------
Total profit:  1.42 L
Total loss:  -34.92 L
-------------------
Total Booked + Current PnL: 11.45 L (8.21%)
Total Booked PnL: 44.95 L (32.22%)
Curr Year Booked PnL: 2.08 L (1.39%)
Prev Year Booked PnL: 42.87 L (30.73%)
===================
Est FTT:  2.56 C
Est FTT PnL: 1.06 C (70.71%)
===================
Deployed:  1.40 C
Current:  1.50 C
CAGR/XIRR %: 3.52%

In [9]:
# top 5 near their targets
cols = ['Symbol', 'Today P/L%', 'Current P/L%', 'FTT%', 'OTT%', 'FTT Amt', 'Current P/L', 'Current', 'FTT', 'Dev%_PE', 'RSI_14','Conviction', 'Spread%',  'CumlRnk', 'RRR Ind', 'CurrAlloc%', 'Gained%', 'Criteria', 'Strategy', 'Category']
df_tmp = df_portfolio_features[~df_portfolio_features['Symbol'].isin(['ENRIN','BLUSPRING','DIGITIDE'])]
df_tmp = df_tmp.sort_values(by = 'FTT Amt', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
55,MASFIN,0.48,-1.44,23.34,21.57,22539.0,-1410.0,96570.0,397.04,-15.09,59.0,H-SC,1.75,167.0,-0.06,0.65,24.79,XR,ATH,FINANCE
59,PIDILITIND,0.36,-0.84,19.36,18.37,27090.0,-1180.0,139930.0,1670.26,-30.55,55.0,X-LC,8.04,5.0,-0.04,0.93,9.87,X40,ATH,CHEMICALS
51,KOTAKBANK,1.60,0.68,20.29,21.11,28288.0,944.0,139416.0,453.24,-13.74,50.0,X-LC,9.63,12.0,0.03,0.93,6.62,X40,ATH,BANKS
53,M&M,2.11,0.67,22.56,23.38,31496.0,927.0,139608.0,3802.40,-14.78,46.0,X-LC,9.02,25.0,0.03,0.93,7.48,X40N,ATH,AUTO
83,TTKPRESTIG,0.93,-31.74,46.64,0.09,32083.0,-31989.0,68788.0,770.00,59.66,63.0,M-SC,20.81,250.0,-1.00,0.46,22.49,OX40N,NTT,DURABLES

In [10]:
# top 5 today
df_tmp = df_portfolio_features.sort_values(by = 'Today P/L%', ascending=False)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
77,TANLA,20.00,-34.12,233.46,119.69,416453.0,-92378.0,178383.0,1943.92,-33.47,76.0,H-SC,19.87,147.0,-0.22,1.19,54.44,AR,ATH,IT
76,SYMPHONY,7.47,-34.62,52.91,-0.03,59199.0,-59254.0,111887.0,1306.00,-47.60,65.0,M-SC,15.17,205.0,-1.00,0.75,24.09,OX40N,NTT,DURABLES
86,VALIANTORG,7.15,-43.32,207.27,74.15,192191.0,-70880.0,92725.0,838.00,-266.56,58.0,H-SC,17.90,145.0,-0.37,0.62,37.99,XR,NTT,CHEMICALS
70,SHALBY,7.06,-36.27,96.30,25.10,111169.0,-65703.0,115440.0,327.00,748.48,63.0,M-SC,23.02,236.0,-0.59,0.77,31.37,XY24,NTT,HEALTHCARE
67,ROUTE,6.83,-59.65,316.75,68.16,170069.0,-79374.0,53692.0,2215.45,-67.37,62.0,H-SC,30.40,141.0,-0.47,0.36,27.91,SR,ATH,IT

In [11]:
# bottom 5 today
df_tmp = df_portfolio_features.sort_values(by = 'Today P/L%', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
5,ATULAUTO,-1.42,-15.22,71.70,45.57,119830.0,-30005.0,167127.0,844.00,3618.92,63.0,M-SC,2.79,248.0,-0.25,1.12,28.61,XY24,NTT,AUTO
19,COLPAL,-1.40,-18.71,74.07,41.51,158584.0,-49265.0,214100.0,3726.84,-1.59,63.0,X-MC,9.19,62.0,-0.31,1.43,19.70,XY25,ATH,FMCG
27,GLAXO,-1.33,-2.08,42.10,39.15,82152.0,-4148.0,195136.0,3466.20,-25.17,53.0,X-MC,9.32,56.0,-0.05,1.30,7.95,X40,ATH,PHARMA
16,CERA,-1.18,-31.15,79.94,23.89,96812.0,-54797.0,121106.0,9475.00,-33.65,58.0,H-SC,12.70,153.0,-0.57,0.81,16.38,OX40N,NTT,CERAMICS
10,BATAINDIA,-0.85,-52.84,186.67,35.20,113281.0,-67985.0,60685.0,2096.00,-20.43,51.0,X-SC,28.74,91.0,-0.60,0.41,20.35,X40,NTT,FOOTWEAR

In [12]:
# top 5 to exit based on CumlRnk
df_tmp = df_portfolio_features[~df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])]
df_tmp = df_tmp[(df_tmp['Current P/L%'] > -1) & (df_tmp['Current P/L%'] < 1)].sort_values(by = 'CumlRnk', ascending=False)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
74,STARHEALTH,0.58,-0.23,47.60,47.26,133511.0,-637.0,280486.0,761.00,57.39,71.0,H-SC,4.78,173.0,-0.00,1.87,45.26,XY24,NTT,INSURANCE
91,ZYDUSLIFE,1.32,-0.91,36.88,35.63,76586.0,-1911.0,207663.0,1286.17,-13.96,59.0,H-MC,3.96,120.0,-0.02,1.39,9.19,AR,ATH,PHARMA

In [13]:
# OX40N stocks to exit
df_tmp = df_portfolio_features[(df_portfolio_features['Symbol'].isin(list_ox40n))].sort_values(by = 'Current P/L%', ascending=False)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
25,FINCABLES,3.35,27.32,63.30,107.91,118993.0,40338.0,187982.0,1641.55,14.66,73.0,M-SC,6.79,220.0,0.34,1.26,41.43,OX40N,ATH,CABLES
72,SIS,1.92,-21.42,54.32,21.26,47393.0,-23784.0,87248.0,528.00,2062.18,72.0,H-SC,8.36,168.0,-0.50,0.58,29.73,OX40N,NTT,MISC
16,CERA,-1.18,-31.15,79.94,23.89,96812.0,-54797.0,121106.0,9475.00,-33.65,58.0,H-SC,12.70,153.0,-0.57,0.81,16.38,OX40N,NTT,CERAMICS
83,TTKPRESTIG,0.93,-31.74,46.64,0.09,32083.0,-31989.0,68788.0,770.00,59.66,63.0,M-SC,20.81,250.0,-1.00,0.46,22.49,OX40N,NTT,DURABLES
50,KANSAINER,2.10,-32.82,68.91,13.47,124838.0,-88506.0,181161.0,340.00,-42.28,59.0,H-SC,16.50,162.0,-0.71,1.21,26.54,XY24,NTT,PAINTS

In [14]:
# top 5 to book for rotation
df_tmp = df_portfolio_features[(df_portfolio_features['Current P/L%'] > 20) ].sort_values(by = 'CumlRnk', ascending=False)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
25,FINCABLES,3.35,27.32,63.3,107.91,118993.0,40338.0,187982.0,1641.55,14.66,73.0,M-SC,6.79,220.0,0.34,1.26,41.43,OX40N,ATH,CABLES

In [15]:
# top 5 to monitor for exit
df_tmp = df_portfolio_features[~df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])]
df_tmp = df_tmp[(df_tmp['Current P/L%'] > 0) ].sort_values(by = 'Dev%_PE', ascending=False)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
25,FINCABLES,3.35,27.32,63.30,107.91,118993.0,40338.0,187982.0,1641.55,14.66,73.0,M-SC,6.79,220.0,0.34,1.26,41.43,OX40N,ATH,CABLES
63,RECLTD,1.08,2.34,17.97,20.74,37365.0,4758.0,207928.0,446.00,13.28,65.0,M-MC,3.58,191.0,0.13,1.39,23.91,XY25,NTT,FINANCE
73,SONACOMS,4.21,1.83,36.59,39.09,37693.0,1855.0,103014.0,804.02,-19.25,63.0,M-MC,13.46,193.0,0.05,0.69,45.73,AR,ATH,AUTO

In [16]:
# top 5 to book for rotation from weak conviction
df_tmp = df_portfolio_features[~df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])]
df_tmp = df_tmp[~df_tmp['Criteria'].isin(['XY25','XY24','X40', 'X40N'])].sort_values(by = 'RRR Ind', ascending=False)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
25,FINCABLES,3.35,27.32,63.30,107.91,118993.0,40338.0,187982.0,1641.55,14.66,73.0,M-SC,6.79,220.0,0.34,1.26,41.43,OX40N,ATH,CABLES
73,SONACOMS,4.21,1.83,36.59,39.09,37693.0,1855.0,103014.0,804.02,-19.25,63.0,M-MC,13.46,193.0,0.05,0.69,45.73,AR,ATH,AUTO
91,ZYDUSLIFE,1.32,-0.91,36.88,35.63,76586.0,-1911.0,207663.0,1286.17,-13.96,59.0,H-MC,3.96,120.0,-0.02,1.39,9.19,AR,ATH,PHARMA
55,MASFIN,0.48,-1.44,23.34,21.57,22539.0,-1410.0,96570.0,397.04,-15.09,59.0,H-SC,1.75,167.0,-0.06,0.65,24.79,XR,ATH,FINANCE
42,INDIAMART,0.59,-8.92,126.97,106.72,142630.0,-11002.0,112334.0,4810.62,-58.98,51.0,H-SC,10.34,140.0,-0.08,0.75,7.92,AR,ATH,MISC

In [17]:
# top 5 to accumulate based on lowest RSI_14
df_tmp = df_portfolio_features[df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])].sort_values(by = 'RSI_14', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
45,INFY,1.36,-20.33,68.50,34.24,170753.0,-63614.0,249274.0,1972.00,-37.23,31.0,X-LC,12.98,3.0,-0.37,1.67,1.36,X40,NTT,IT
33,HCLTECH,2.08,-20.29,52.45,21.51,101138.0,-49097.0,192827.0,1872.35,-16.46,32.0,X-LC,7.95,8.0,-0.49,1.29,2.08,X40,ATH,IT
40,ICICIPRULI,1.05,-14.02,52.04,30.73,88151.0,-27615.0,169390.0,790.00,-37.08,35.0,X-MC,13.13,78.0,-0.31,1.13,3.22,X40,ATH,INSURANCE
1,ABBOTINDIA,0.97,-14.71,38.43,18.07,58625.0,-26305.0,152550.0,35195.00,-27.52,41.0,X-MC,11.94,58.0,-0.45,1.02,0.97,X40,ATH,PHARMA
35,HDFCLIFE,1.55,-2.31,36.33,33.18,53165.0,-3462.0,146338.0,814.30,-23.74,43.0,X-LC,17.73,31.0,-0.07,0.98,5.51,X40,ATH,INSURANCE

In [18]:
# top 5 to accumulate based on Spread and CumlRnk
df_tmp = df_portfolio_features[df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])]
df_tmp = df_tmp[(df_tmp['CumlRnk'] < 100)].sort_values(by = 'Spread%', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
88,VOLTAS,3.48,18.52,22.51,45.20,51154.0,35508.0,227250.0,1856.00,35.64,65.0,X-MC,4.62,79.0,0.69,1.52,26.57,XY25,NTT,AC
84,UNITDSPR,-0.02,2.23,18.14,20.77,43419.0,5211.0,239355.0,1644.00,-9.40,63.0,X-MC,4.78,64.0,0.12,1.60,14.18,X40N,NTT,BREWERIES
87,VBL,5.79,4.81,29.29,35.50,96958.0,15184.0,331026.0,670.80,-7.45,75.0,X-LC,6.14,13.0,0.16,2.21,35.92,X40N,ATH,FMCG
65,RELIANCE,2.86,-12.33,42.92,25.30,75620.0,-24775.0,176188.0,1952.00,-14.65,51.0,X-LC,6.18,21.0,-0.33,1.18,4.69,XY25,BTT,REFINERIES
39,ICICIGI,-0.09,-6.21,27.25,19.34,51141.0,-12436.0,187673.0,2252.93,-21.06,43.0,X-MC,6.47,66.0,-0.24,1.25,4.82,X40,ATH,INSURANCE

In [19]:
# top 5 to accumulate based on lowest Gained%
df_tmp = df_portfolio_features[df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])].sort_values(by = 'Gained%', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
1,ABBOTINDIA,0.97,-14.71,38.43,18.07,58625.0,-26305.0,152550.0,35195.00,-27.52,41.0,X-MC,11.94,58.0,-0.45,1.02,0.97,X40,ATH,PHARMA
45,INFY,1.36,-20.33,68.50,34.24,170753.0,-63614.0,249274.0,1972.00,-37.23,31.0,X-LC,12.98,3.0,-0.37,1.67,1.36,X40,NTT,IT
33,HCLTECH,2.08,-20.29,52.45,21.51,101138.0,-49097.0,192827.0,1872.35,-16.46,32.0,X-LC,7.95,8.0,-0.49,1.29,2.08,X40,ATH,IT
40,ICICIPRULI,1.05,-14.02,52.04,30.73,88151.0,-27615.0,169390.0,790.00,-37.08,35.0,X-MC,13.13,78.0,-0.31,1.13,3.22,X40,ATH,INSURANCE
79,TCS,2.12,-28.15,76.16,26.57,253517.0,-130399.0,332874.0,4311.58,-39.04,43.0,X-LC,14.99,2.0,-0.51,2.22,3.89,X40,ATH,IT

In [20]:
# top 5 to accumulate based on lowest CurrAlloc%
df_tmp = df_portfolio_features[df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])].sort_values(by = 'CurrAlloc%', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
64,RELAXO,2.36,-60.07,281.46,52.31,163131.0,-87201.0,57959.0,1176.00,-57.51,56.0,X-SC,29.07,92.0,-0.53,0.39,29.59,X40N,NTT,FOOTWEAR
10,BATAINDIA,-0.85,-52.84,186.67,35.20,113281.0,-67985.0,60685.0,2096.00,-20.43,51.0,X-SC,28.74,91.0,-0.60,0.41,20.35,X40,NTT,FOOTWEAR
60,QUESS,4.53,-18.48,113.32,73.90,98653.0,-19736.0,87057.0,424.00,-55.92,59.0,X-SC,16.92,80.0,-0.20,0.58,17.11,XY24,NTT,MISC
53,M&M,2.11,0.67,22.56,23.38,31496.0,927.0,139608.0,3802.40,-14.78,46.0,X-LC,9.02,25.0,0.03,0.93,7.48,X40N,ATH,AUTO
51,KOTAKBANK,1.60,0.68,20.29,21.11,28288.0,944.0,139416.0,453.24,-13.74,50.0,X-LC,9.63,12.0,0.03,0.93,6.62,X40,ATH,BANKS

In [21]:
# top 5 to accumulate based on CumlRnk
df_tmp = df_portfolio_features.sort_values(by = 'CumlRnk', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
47,ITC,0.75,-19.97,48.76,19.06,132749.0,-67916.0,272250.0,452.00,-55.92,50.0,X-LC,18.15,1.0,-0.51,1.82,5.61,X40,NTT,FMCG
79,TCS,2.12,-28.15,76.16,26.57,253517.0,-130399.0,332874.0,4311.58,-39.04,43.0,X-LC,14.99,2.0,-0.51,2.22,3.89,X40,ATH,IT
45,INFY,1.36,-20.33,68.50,34.24,170753.0,-63614.0,249274.0,1972.00,-37.23,31.0,X-LC,12.98,3.0,-0.37,1.67,1.36,X40,NTT,IT
81,TMPV,1.10,-19.34,69.32,36.58,198965.0,-68817.0,287024.0,600.00,-83.62,58.0,X-LC,6.94,4.0,-0.35,1.92,19.63,XY24,NTT,AUTO
59,PIDILITIND,0.36,-0.84,19.36,18.37,27090.0,-1180.0,139930.0,1670.26,-30.55,55.0,X-LC,8.04,5.0,-0.04,0.93,9.87,X40,ATH,CHEMICALS

In [22]:
# top 5 for average up
df_tmp = df_portfolio_features[(df_portfolio_features['Dev%_200'] > 5)].sort_values(by = 'CurrAlloc%', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
44,INDUSINDBK,6.16,-33.54,99.97,32.89,51294.0,-25898.0,51309.0,1800.00,-341.60,62.0,L-MC,4.85,258.0,-0.50,0.34,26.29,XR,NTT,BANKS
73,SONACOMS,4.21,1.83,36.59,39.09,37693.0,1855.0,103014.0,804.02,-19.25,63.0,M-MC,13.46,193.0,0.05,0.69,45.73,AR,ATH,AUTO
75,SURYODAY,2.88,-14.91,44.60,23.03,67956.0,-26703.0,152368.0,216.00,66.67,66.0,H-SC,4.17,166.0,-0.39,1.02,29.94,XR,NTT,BANKS
5,ATULAUTO,-1.42,-15.22,71.70,45.57,119830.0,-30005.0,167127.0,844.00,3618.92,63.0,M-SC,2.79,248.0,-0.25,1.12,28.61,XY24,NTT,AUTO
25,FINCABLES,3.35,27.32,63.30,107.91,118993.0,40338.0,187982.0,1641.55,14.66,73.0,M-SC,6.79,220.0,0.34,1.26,41.43,OX40N,ATH,CABLES

In [23]:
# top 5 RSP
df_tmp = df_portfolio_features.sort_values(by = 'RSP', ascending=False)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
61,RAJESHEXPO,1.22,-75.21,303.58,0.07,103257.0,-103164.0,34013.0,518.00,1146.21,61.0,L-SC,36.75,268.0,-1.00,0.23,59.68,OX40N,NTT,JEWELLERY
77,TANLA,20.00,-34.12,233.46,119.69,416453.0,-92378.0,178383.0,1943.92,-33.47,76.0,H-SC,19.87,147.0,-0.22,1.19,54.44,AR,ATH,IT
62,RAJOOENG,0.24,-30.50,100.87,39.61,71860.0,-31260.0,71240.0,143.10,-52.96,67.0,H-SC,24.60,136.0,-0.44,0.48,52.61,AR,ATH,MISC
80,TITAGARH,5.50,-24.84,93.91,45.74,170927.0,-60165.0,182012.0,1548.00,0.02,72.0,H-SC,15.11,175.0,-0.35,1.22,38.87,XY24,NTT,ENGINEERING
87,VBL,5.79,4.81,29.29,35.50,96958.0,15184.0,331026.0,670.80,-7.45,75.0,X-LC,6.14,13.0,0.16,2.21,35.92,X40N,ATH,FMCG

In [24]:
# Top N allocation
df_tmp = df_portfolio_features.sort_values(by = 'CurrAlloc%', ascending=False)
top_n_values = [10, 25, 50]

sum_df = pd.DataFrame({
    'Top_N': top_n_values,
    'Sum_Alloc%': [df_tmp['CurrAlloc%'].head(n).sum() for n in top_n_values]
})

sum_df

   Top_N  Sum_Alloc%
0     10       18.87
1     25       42.56
2     50       72.77

In [25]:
# market-cap-wise allocation
df_tmp = df_portfolio_features[cols]
df_tmp.groupby(df_tmp['Conviction'].str[-2:])['CurrAlloc%'].sum().sort_values(ascending=False)

Conviction
SC    42.07
LC    31.75
MC    26.18
Name: CurrAlloc%, dtype: float64

In [26]:
# criteria-wise allocation
df_portfolio_features.groupby('Criteria')['CurrAlloc%'].sum().sort_values(ascending=False)

Criteria
XY24     26.68
X40      25.58
X40N     17.10
XR        8.99
XY25      7.08
AR        6.96
OX40N     6.81
SR        0.80
Name: CurrAlloc%, dtype: float64

In [27]:
# conviction-wise allocation
df_portfolio_features.groupby('Conviction')['CurrAlloc%'].sum().sort_values(ascending=False)

Conviction
X-LC    29.51
H-SC    21.70
X-MC    21.18
M-SC    10.02
X-SC     9.78
H-MC     2.58
M-MC     2.08
H-LC     1.29
M-LC     0.95
L-SC     0.57
L-MC     0.34
Name: CurrAlloc%, dtype: float64

In [28]:
# sector-wise stats
df_tmp = df_portfolio_features.groupby('Category')[['CurrAlloc%', 'Current', 'Current P/L', 'FTT Amt']].sum().sort_values(by=['Current', 'Current P/L'], ascending=False)
df_tmp['Current P/L%'] = round(df_tmp['Current P/L'] * 100 / df_tmp['Current'], 2)
df_tmp['FTT%'] = round(df_tmp['FTT Amt'] * 100 / df_tmp['Current'], 2)
cols = ['CurrAlloc%', 'Current P/L%', 'FTT%']
df_tmp[cols].sort_values(by=['CurrAlloc%'], ascending=False)

               CurrAlloc%  Current P/L%    FTT%
Category
FMCG                15.69        -12.71   52.49
FINANCE             10.78        -14.22   63.90
IT                  10.67        -40.99  112.38
MISC                 6.82        -31.60   88.76
AUTO                 6.64        -10.27   51.61
BANKS                5.40        -12.30   64.23
INSURANCE            5.23         -5.63   41.58
PAINTS               5.09        -29.20   51.63
PHARMA               4.80         -3.09   36.22
ELECTRICAL           4.14        -14.09   54.71
AC                   2.05         -4.15   32.40
CHEMICALS            1.99        -35.82  116.75
HEALTHCARE           1.95        -22.58   54.57
DURABLES             1.82        -42.03   76.58
APPARELS             1.76         -1.68   36.37
FOOTWEAR             1.75        -69.05  136.83
TRAVEL               1.71        -75.43  163.27
BREWERIES            1.60          2.18   18.14
REALTY               1.44         -3.24   20.21
CERAMICS             1.28        -59.93  108.51
CABLES               1.26         21.46   63.30
ENGINEERING          1.22        -33.06   93.91
REFINERIES           1.18        -14.06   42.92
CEMENT               1.15        -55.19  171.29
JEWELLERY            1.06       -101.90  172.05
ENTERTAINMENT        0.75        -73.17  176.44
TEXTILES             0.43        -42.72   83.42
HOTELS               0.34       -123.25  202.00

In [29]:
# money to be made criteria-wise
df_portfolio_features.groupby('Criteria')['FTT Amt'].agg(['sum', 'count']).sort_values(by='sum', ascending=False)

                sum  count
Criteria
XY24      3604964.0     21
X40       1871288.0     19
XR        1336077.0     13
X40N      1167356.0     13
AR        1149301.0      9
OX40N      772793.0     10
XY25       382095.0      5
SR         299525.0      2

In [30]:
# money to be made conviction-wise
df_portfolio_features.groupby('Conviction')['FTT Amt'].agg(['sum', 'count']).sort_values(by='sum', ascending=False)

                  sum  count
Conviction
H-SC        3544790.0     24
X-LC        1882125.0     21
X-MC        1561719.0     15
M-SC        1419293.0     14
X-SC        1340378.0      9
H-MC         312576.0      2
L-SC         205996.0      2
M-LC         149393.0      1
M-MC          75058.0      2
L-MC          51294.0      1
H-LC          40777.0      1

In [31]:
# money to be made criteria and conviction-wise
df_portfolio_features.groupby(['Conviction', 'Criteria'])['FTT Amt'].agg(['sum', 'count']).sort_values(by='sum', ascending=False)

                           sum  count
Conviction Criteria
H-SC       XY24      1165052.0      6
X-LC       X40       1015734.0     10
H-SC       AR         919207.0      5
M-SC       XY24       847841.0      6
H-SC       XR         816726.0      7
X-SC       XY24       785038.0      4
X-MC       X40        658627.0      7
           X40N       453306.0      4
X-SC       X40N       358413.0      3
X-LC       X40N       355637.0      6
H-SC       OX40N      344280.0      4
X-LC       XY24       330995.0      2
M-SC       OX40N      325256.0      5
H-SC       SR         299525.0      2
X-MC       XY24       240048.0      2
H-MC       XY24       235990.0      1
X-MC       XY25       209738.0      2
X-SC       X40        196927.0      2
M-SC       XR         171158.0      2
M-LC       XR         149393.0      1
X-LC       XY25       134992.0      2
L-SC       OX40N      103257.0      1
           XR         102739.0      1
H-MC       AR          76586.0      1
M-SC       AR          75038.0      1
L-MC       XR          51294.0      1
X-LC       XR          44767.0      1
H-LC       AR          40777.0      1
M-MC       AR          37693.0      1
           XY25        37365.0      1

In [32]:
# notebook execution time

end_time = time.time()
execution_time = round(end_time - start_time, 0)
print(f"Notebook execution time: {execution_time} seconds")

Notebook execution time: 28.0 seconds