<a href="https://colab.research.google.com/github/ankit-rathi/Quantvesting_v2/blob/main/myStocks_Portfolio_Analysis.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
'''
!pip install pandas==2.2.2 -qq
!pip install pyxirr -qq
!pip install ta -qq
!pip install yfinance==0.2.59 -qq
'''

'\n!pip install pandas==2.2.2 -qq\n!pip install pyxirr -qq\n!pip install ta -qq\n!pip install yfinance==0.2.59 -qq\n'

In [2]:
# import libraries

import numpy as np
import pandas as pd
import datetime
import warnings
warnings.filterwarnings('ignore')
import yfinance as yfin
import ta
import matplotlib.pyplot as plt
import requests

In [3]:
# notebook start time
import time
import datetime
import pytz

start_time = time.time()

# function to print date timestamp
def print_date_time():
  tz_NY = pytz.timezone('Asia/Kolkata')
  datetime_NY = datetime.datetime.now(tz_NY)
  print("Run date time (IST):", datetime_NY.strftime("%Y-%m-%d %H:%M:%S"))

In [4]:
# function to get booked and reserved amount
def get_amt():
  # fetch the JSON data from the URL
  url = "https://raw.githubusercontent.com/ankit-rathi/Tradevesting_v1/main/data/myPortfolioAmts.json"
  response = requests.get(url)
  pf_amts = response.json()  # parse the JSON data

  # extract values from the JSON
  py_booked_amt_dm = pf_amts["py_booked_amt_dm"]
  py_booked_amt_sv = pf_amts["py_booked_amt_sv"]
  cy_booked_amt_dm = pf_amts["cy_booked_amt_dm"]
  cy_booked_amt_sv = pf_amts["cy_booked_amt_sv"]
  reserve_amt_dm = pf_amts["reserve_amt_dm"]
  reserve_amt_sv = pf_amts["reserve_amt_sv"]

  # perform calculations
  py_booked_amt = py_booked_amt_dm + py_booked_amt_sv
  cy_booked_amt = cy_booked_amt_dm + cy_booked_amt_sv
  reserve_amt = reserve_amt_dm + reserve_amt_sv
  total_booked_amt = py_booked_amt + cy_booked_amt

  return total_booked_amt, reserve_amt, cy_booked_amt, py_booked_amt

gen_output = 0

In [5]:
# function to format the amount
def format_amt(number):
    abs_number = abs(number)

    if abs_number >= 1_00_00_000:  # Crores
        formatted_amt = f"{number / 1_00_00_000:.2f} C"
    elif abs_number >= 1_00_000:  # Lakhs
        formatted_amt = f"{number / 1_00_000:.2f} L"
    elif abs_number >= 1_000:  # Thousands
        formatted_amt = f"{number / 1_000:.2f} K"
    else:
        formatted_amt = f"{number:.2f}"

    return formatted_amt

# function to set start and end date
def get_start_end_date():
  start_date = (datetime.date.today() + datetime.timedelta(days=-365)).strftime('%Y-%m-%d')
  end_date = (datetime.date.today() + datetime.timedelta(days=1)).strftime('%Y-%m-%d')
  return start_date, end_date

# function to fetch my portfolio csv
def get_mypfs_df():
  mypfs_df = pd.read_csv('https://raw.githubusercontent.com/ankit-rathi/Tradevesting_v1/main/data/myPortfolioStocks.csv')
  return mypfs_df

# function to fetch my prospects csv
def get_mypps_df():
  mypps_df = pd.read_csv('https://raw.githubusercontent.com/ankit-rathi/Tradevesting_v1/main/data/myProspectsScrips.csv')
  return mypps_df

# function to fetch screener data
def get_myscreen_df():
  myscreen_df = pd.read_csv('https://raw.githubusercontent.com/ankit-rathi/Tradevesting_v1/main/data/myScreenerDB.csv')
  return myscreen_df

# function to fetch momentum data
def get_myinvmt_df():
  myinvmt_df = pd.read_csv('https://raw.githubusercontent.com/ankit-rathi/Tradevesting_v1/main/data/myInvestments.csv')
  return myinvmt_df

# function to get the stock ids
def get_stock_ids(df_pf):
  stock_n100 = df_pf['Symbol'].unique()

  exclude = ['CADILAHC','MMTC', 'MASFIN']

  stock_ids = df_pf[~df_pf['Symbol'].isin(exclude) ]['Symbol'].unique()

  #mypf = mypf[mypf.Forecast.notnull()]
  #stock_ids = mypf['Symbol'].unique()

  #stock_ids.sort()
  return stock_ids

# get features from screener data
def get_screener_features():
  myscreen_df = get_myscreen_df()
  cols = ['Symbol', 'EPS', 'MedPE', 'ROCE%', 'ROE%', 'CapType']
  return myscreen_df[cols]

# get relative strength
def get_relative_strength(stock_list):

    # Dictionary to store stock tickers and their corresponding percentage price change
    stock_changes = {}

    # Loop through each stock and fetch its price data
    for stock in stock_list:
        try:
            # Download the stock data for the given date range
            stock_data = yfin.Ticker(stock + '.NS').history(period='1mo', interval='1d')[map(str.title, ['open', 'close', 'low', 'high', 'volume'])]

            # Calculate the percentage change for the stock
            if len(stock_data) > 0:
                start_price = stock_data['Close'].iloc[0]
                end_price = stock_data['Close'].iloc[-1]
                percent_change = round(((end_price - start_price) / start_price) * 100, 2)
                stock_changes[stock] = percent_change
            else:
                stock_changes[stock] = np.nan  # If no data is available, set to NaN

        except Exception as e:
            print(f"Error fetching data for {stock}: {e}")
            stock_changes[stock] = np.nan

    # Create a DataFrame with stock tickers and their percentage changes
    df = pd.DataFrame(list(stock_changes.items()), columns=['Symbol', 'Percent_Change'])

    # Drop any stocks with missing data (NaN values)
    df = df.dropna()

    # Calculate the percentile rank based on percentage change
    df['RSP'] = round(df['Percent_Change'].rank(pct=True) * 100, 2)
    cols = ['Symbol', 'RSP']
    df = df[cols]
    # Sort by percentile rank (optional)
    df = df.sort_values(by='RSP', ascending=False).reset_index(drop=True)

    return df

In [6]:
# function to get stock technicals
def stock_prec_dev(stock_symbol):
    #stock_symbol = 'ULTRACEMCO.NS'
    short_window = 20
    mid_window = 50
    long_window = 200
    moving_avg = 'SMA'

    start = datetime.datetime(*map(int, start_date.split('-')))
    end = datetime.datetime(*map(int, end_date.split('-')))

    stock_df = yfin.Ticker(stock_symbol + '.NS').history(period='max', interval='1d')[map(str.title, ['open', 'close', 'low', 'high', 'volume'])]

    stock_df['Max'] = round(max(stock_df['Close']),2)
    stock_df = stock_df[(stock_df.index <= end_date) & (stock_df.index >= start_date)]
    stock_df['200_SMA'] = round(stock_df['Close'].rolling(window = 200, min_periods = 1).mean(),0)
    stock_df['Dev%_200'] = round((stock_df['Close'] - stock_df['200_SMA'])*100/stock_df['200_SMA'],2)
    stock_df.dropna(axis = 0, inplace = True) # remove any null rows

    stock_df['20_SMA'] = stock_df['Close'].rolling(window=20).mean()
    stock_df['50_SMA'] = stock_df['Close'].rolling(window=50).mean()
    stock_df['Symbol'] = stock_symbol

    stock_df['Close'] = round(stock_df['Close'],2)
    stock_df['Min'] = round(min(stock_df['Close']),2)
    stock_df['RSI_14'] = ta.momentum.RSIIndicator(close=stock_df['Close'], window=14).rsi()
    stock_df['RSI_14'] = round(stock_df['RSI_14'],0)
    stock_df['Prev_Close'] = stock_df['Close'].shift(1)
    stock_df.drop(['Open', 'Low', 'High', 'Volume'], axis=1, inplace=True)
    stock_df = stock_df.tail(1)

    max_SMA = max(stock_df['20_SMA'].item(), stock_df['50_SMA'].item(), stock_df['200_SMA'].item())
    min_SMA = min(stock_df['20_SMA'].item(), stock_df['50_SMA'].item(), stock_df['200_SMA'].item())
    ABS_Spread = max_SMA - min_SMA
    stock_df['Spread%'] = round((ABS_Spread / stock_df['200_SMA'].item()) * 100,2)

    return stock_df

# function to compute stock attributes
def get_common_features(stock_ids, df_mypf):

  df_prec_dev = pd.DataFrame()
  df_tmp = get_screener_features()
  df_rs = get_relative_strength(stock_ids)

  for stock_id in stock_ids:
      tmp = stock_prec_dev(stock_id)
      tmp = tmp.reset_index()
      df_prec_dev = pd.concat([df_prec_dev, tmp], ignore_index = True)
  df_prec_dev = pd.merge(df_prec_dev, df_mypf, on= 'Symbol')
  df_prec_dev = pd.merge(df_prec_dev, df_tmp, on= 'Symbol', how='left')
  df_prec_dev = pd.merge(df_prec_dev, df_rs, on= 'Symbol', how='left')
  #print(df_prec_dev.columns)
  df_prec_dev['Curr_PE'] = round(df_prec_dev['Close']/df_prec_dev['EPS'],1)
  df_prec_dev['Dev%_PE'] = round((df_prec_dev['Curr_PE'] - df_prec_dev['MedPE'])*100/df_prec_dev['MedPE'],2)
  df_prec_dev['Conviction'] = df_prec_dev['Conviction'] + '-' + df_prec_dev['CapType']
  return df_prec_dev

# function to arrange stock features
def arrange_features(df_stocks, common_cols, diff_cols):
  df_stocks_common = df_stocks[common_cols].drop_duplicates()
  df_stocks_diff = df_stocks[diff_cols]
  df_stocks_diff['Investment'] = df_stocks_diff['AvgCost'] * df_stocks_diff['Shares']
  df_stocks_diff = df_stocks_diff.groupby(['Symbol'])[['Shares', 'Investment']].aggregate(['sum']).reset_index()
  df_stocks_diff.columns = ['Symbol', 'Shares', 'Investment']
  df_stocks_diff['AvgCost'] = round(df_stocks_diff['Investment']/df_stocks_diff['Shares'],2)
  df_stocks = pd.merge(df_stocks_diff, df_stocks_common, on='Symbol')
  return df_stocks

# plot fact distribution across dimension
def plot_pie_chart(df, dimension, fact):
  # grouping the data by category and calculating the sum of fact for each type
  grouped_data = df.groupby(dimension)[fact].sum()

  # sorting the grouped data in descending order
  grouped_data = grouped_data.sort_values(ascending=False)

  # creating a pie chart
  grouped_data.plot.pie(autopct='%1.1f%%', startangle=90, figsize=(6, 6))

  # adding a title and displaying the plot
  plt.title(f'{dimension} {fact} Distribution')
  plt.ylabel('')  # To hide the y-label
  plt.show()

In [7]:
# function to get portfolio features

def get_portfolio_features(df_common_features):

  print_date_time()
  print('-------------------')

  #df_common_features["Target"] = df_common_features["Target"].fillna(df_common_features["Max"])
  df_common_features['NTT'] = np.where(df_common_features['Strategy']== 'NTT', df_common_features["Target"], df_common_features['Max'])
  df_common_features['LTT'] = np.where(df_common_features['Strategy']== 'BTT', df_common_features["Target"], df_common_features['Max'])
  df_common_features['BOL'] = df_common_features['Min']

  tmp_df = df_common_features[df_common_features['Symbol'].isin(mypf_df[mypf_df['InPortfolio'] != 'NA'].Symbol.values)]
  print('qualified stocks: '+str(len(tmp_df['Symbol'].unique())))
  tmp_df1 = tmp_df[tmp_df['LatestQtr'] == 1]
  print('with latest results: '+str(len(tmp_df1['Symbol'].unique())))
  tmp_df1 = tmp_df1[tmp_df1['StarStock'] == 1]
  print('still star stocks: '+str(len(tmp_df1['Symbol'].unique())))
  tmp_df['Investment'] = tmp_df['AvgCost'] * tmp_df['Shares']
  tmp_df['Current'] = round(tmp_df['Close'] * tmp_df['Shares'],0)
  tmp_df['Previous'] = tmp_df['Prev_Close'] * tmp_df['Shares']
  tmp_df['EstimatedST'] = tmp_df['NTT'] * tmp_df['Shares']
  tmp_df['EstimatedLT'] = tmp_df['LTT'] * tmp_df['Shares']
  tmp_df['Current P/L'] = round((tmp_df['Current'] - tmp_df['Investment']),0)
  tmp_df['Today P/L%'] = round((tmp_df['Current'] - tmp_df['Previous'])*100/tmp_df['Previous'],2)
  tmp_df['Current P/L%'] = round((tmp_df['Current'] - tmp_df['Investment'])*100/tmp_df['Investment'],2)
  tmp_df['EstimatedST P/L%'] = round((tmp_df['EstimatedST'] - tmp_df['Investment'])*100/tmp_df['Investment'],2)
  tmp_df['EstimatedLT P/L%'] = round((tmp_df['EstimatedLT'] - tmp_df['Investment'])*100/tmp_df['Investment'],2)
  tmp_df['NTT%'] = round((tmp_df['NTT'] - tmp_df['Close'])*100/tmp_df['Close'],2)
  tmp_df['LTT%'] = round((tmp_df['LTT'] - tmp_df['Close'])*100/tmp_df['Close'],2)
  tmp_df['Gained%'] = round((tmp_df['Close'] - tmp_df['BOL'])*100/tmp_df['BOL'],2)
  investment = round(sum(tmp_df['AvgCost']*tmp_df['Shares']),0)
  current = round(sum(tmp_df['Close']*tmp_df['Shares']),0)
  tmp_df['InitAlloc%'] = round(tmp_df['Investment']*100/investment,2)
  tmp_df['CurrAlloc%'] = round(tmp_df['Current']*100/current,2)
  tmp_df['FTT'] = tmp_df['LTT']
  tmp_df.loc[tmp_df['Strategy'] == 'NTT', 'FTT'] = tmp_df['NTT']
  tmp_df['FTT%'] = tmp_df['LTT%']
  tmp_df.loc[tmp_df['Strategy'] == 'NTT', 'FTT%'] = tmp_df['NTT%']
  tmp_df['FTT Amt'] = round(tmp_df['FTT%'] * tmp_df['Current']/100,0)
  tmp_df['OTT%'] = round((tmp_df['FTT'] - tmp_df['AvgCost'])*100/tmp_df['AvgCost'],2)
  tmp_df['RRR Ind'] = round(tmp_df['Current P/L']/tmp_df['FTT Amt'],2)
  tmp_df['Risk Ind'] = round(tmp_df['Current P/L%']*tmp_df['CurrAlloc%'],0)

  return tmp_df

# function to print portfolio features
def print_portfolio_stats(df_portfolio_features, myinvmt_df):
  from pyxirr import xirr

  total_booked_amt, reserve_amt, cy_booked_amt, py_booked_amt = get_amt()

  dates = myinvmt_df['Date'].values
  dates = np.append(dates, datetime.date.today().strftime('%d-%b-%y'))
  investment = myinvmt_df['Investment'].values
  dates= pd.to_datetime(dates)

  current = round(sum(df_portfolio_features['Close']*df_portfolio_features['Shares']),0) + reserve_amt
  investment_xirr = np.append(investment, current)
  cagr = round(xirr(pd.DataFrame({"dates": dates, "amounts": investment_xirr}))*100,2)

  investment = -sum(investment)
  invested = round(sum(df_portfolio_features['AvgCost']*df_portfolio_features['Shares']),0) + reserve_amt
  previous = round(sum(df_portfolio_features['Prev_Close']*df_portfolio_features['Shares']),0) + reserve_amt
  cy_invested = investment + py_booked_amt

  today_pnl_amount = current-previous
  today_pnl_percentage = round((current-previous)*100/previous,2)

  curr_pnl_amount = current-invested
  curr_pnl_percentage = round((curr_pnl_amount)*100/(cy_invested),2)

  cy_pnl_amount = cy_booked_amt + curr_pnl_amount
  cy_pnl_percentage = round((cy_pnl_amount)*100/cy_invested,2)

  overall_pnl_amount = total_booked_amt + curr_pnl_amount
  overall_pnl_percentage = round((overall_pnl_amount)*100/investment,2)

  estimate_st = round(sum(df_portfolio_features['FTT']*df_portfolio_features['Shares']),0)  + reserve_amt
  est_st_pnl_amount = estimate_st-current
  est_st_pnl_percentage = round((est_st_pnl_amount)*100/current,2)

  estimate_lt = round(sum(df_portfolio_features['LTT']*df_portfolio_features['Shares']),0)  + reserve_amt
  est_lt_pnl_amount = estimate_lt-current
  est_lt_pnl_percentage = round((est_lt_pnl_amount)*100/current,2)

  total_profit = round(sum(df_portfolio_features[df_portfolio_features['Current P/L%'] > 0]['Current']) - sum(df_portfolio_features[df_portfolio_features['Current P/L%'] > 0]['Investment']),0)
  total_loss = round(sum(df_portfolio_features[df_portfolio_features['Current P/L%'] < 0]['Current']) - sum(df_portfolio_features[df_portfolio_features['Current P/L%'] < 0]['Investment']),0)

  cy_booked_percentage = round((cy_booked_amt)*100/current,2)
  py_booked_percentage = round((py_booked_amt)*100/investment,2)
  total_booked_percentage = round((total_booked_amt)*100/investment,2)

  print('-------------------')
  print('Initial Investment: ', format_amt(investment))
  print('CY Investment: ', format_amt(cy_invested))
  print('Reserve: ', format_amt(reserve_amt))
  print('Current: ',  format_amt(current))
  print('-------------------')
  print('Today PnL: '+ '{} ({}%)'.format(format_amt(today_pnl_amount), today_pnl_percentage))
  print('Current PnL: '+ '{} ({}%)'.format(format_amt(curr_pnl_amount), curr_pnl_percentage))
  print('CY Booked + Current PnL: '+ '{} ({}%)'.format(format_amt(cy_pnl_amount), cy_pnl_percentage))
  print('-------------------')
  print('Total profit: ', format_amt(total_profit))
  print('Total loss: ', format_amt(total_loss))
  print('-------------------')
  print('Total Booked + Current PnL: '+ '{} ({}%)'.format(format_amt(overall_pnl_amount), overall_pnl_percentage))
  print('Total Booked PnL: '+ '{} ({}%)'.format(format_amt(total_booked_amt), total_booked_percentage))
  print('Curr Year Booked PnL: '+ '{} ({}%)'.format(format_amt(cy_booked_amt), cy_booked_percentage))
  print('Prev Year Booked PnL: '+ '{} ({}%)'.format(format_amt(py_booked_amt), py_booked_percentage))
  print('===================')
  print('Est FTT: ',  format_amt(estimate_st))
  print('Est FTT PnL: '+ '{} ({}%)'.format(format_amt(est_st_pnl_amount), est_st_pnl_percentage))

  print('===================')
  print('Deployed: ', format_amt(investment))

  print('Current: ', format_amt(current))

  print('CAGR/XIRR %: '+'{}%'.format(cagr))

In [8]:
# get start and end date
start_date, end_date = get_start_end_date()

# get portfolio and prospects data
mypfs_df = get_mypfs_df()
mypps_df = get_mypps_df()
myinvmt_df = get_myinvmt_df()

# merge above datasets
mypf_df = pd.merge(mypfs_df, mypps_df, on="Symbol")

# seggregate dm and sv portfolio
dm_pf = mypf_df[mypf_df['InPortfolio'] == 'DM']
sv_pf = mypf_df[mypf_df['InPortfolio'] == 'SV']

# build portfolio stock dataframe
dm_stocks = get_stock_ids(dm_pf)
sv_stocks = get_stock_ids(sv_pf)
df_stocks = pd.concat([dm_pf,sv_pf], ignore_index = True)

# arrange common and diff stock features
common_cols = ['Symbol', 'Target', 'Criteria', 'Strategy', 'CumlRnk', 'LatestQtr', 'StarStock', 'Conviction', 'Category', 'InFolio', 'XIRR', 'MBQ']
diff_cols = ['Symbol', 'AvgCost', 'Shares']
df_stocks = arrange_features(df_stocks, common_cols, diff_cols)

# get common features
stock_ids = df_stocks['Symbol'].values
df_common_features = get_common_features(stock_ids, df_stocks)

df_common_features.reset_index(drop=True, inplace=True)
df_common_features.drop(['Date'], axis=1, inplace=True)
# get and print portfolio features
df_portfolio_features = get_portfolio_features(df_common_features)

print_portfolio_stats(df_portfolio_features, myinvmt_df)

df = df_portfolio_features
#plot_pie_chart(df, 'CapType', 'Current')
list_ox40n = list(df[df['MBQ'].str.contains('OX40N', na=False)]['Symbol'].values)

Run date time (IST): 2026-08-13 11:19:16
-------------------
qualified stocks: 88
with latest results: 30
still star stocks: 19
-------------------
Initial Investment:  1.46 C
CY Investment:  1.89 C
Reserve:  2.21 L
Current:  1.60 C
-------------------
Today PnL: -52.59 K (-0.33%)
Current PnL: -32.09 L (-16.99%)
CY Booked + Current PnL: -27.44 L (-14.53%)
-------------------
Total profit:  3.72 L
Total loss:  -35.81 L
-------------------
Total Booked + Current PnL: 15.43 L (10.56%)
Total Booked PnL: 47.52 L (32.53%)
Curr Year Booked PnL: 4.65 L (2.9%)
Prev Year Booked PnL: 42.87 L (29.35%)
===================
Est FTT:  2.68 C
Est FTT PnL: 1.07 C (66.89%)
===================
Deployed:  1.46 C
Current:  1.60 C
CAGR/XIRR %: 4.3%

In [9]:
# top 5 near their targets
cols = ['Symbol', 'Today P/L%', 'Current P/L%', 'FTT%', 'OTT%', 'FTT Amt', 'Current P/L', 'Current', 'FTT', 'Dev%_PE', 'RSI_14','Conviction', 'Spread%',  'CumlRnk', 'RRR Ind', 'CurrAlloc%', 'Gained%', 'Criteria', 'Strategy', 'Category']
df_tmp = df_portfolio_features[~df_portfolio_features['Symbol'].isin(['ENRIN','BLUSPRING','DIGITIDE'])]
df_tmp = df_tmp.sort_values(by = 'FTT Amt', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
79,UNITDSPR,-1.39,12.18,7.66,20.77,20120.0,28517.0,262661.0,1644.00,-0.46,67.0,X-MC,8.57,64.0,1.42,1.66,26.26,X40N,NTT,BREWERIES
78,TTKPRESTIG,1.15,-22.43,29.03,0.09,22694.0,-22603.0,78174.0,770.00,81.43,41.0,M-SC,12.20,250.0,-1.00,0.49,40.70,OX40N,NTT,DURABLES
87,ZYDUSLIFE,-2.29,24.16,9.14,35.51,23783.0,50631.0,260205.0,1285.01,8.11,62.0,H-MC,15.99,120.0,2.13,1.64,36.93,AR,ATH,PHARMA
68,SIS,-1.31,-0.83,22.28,21.26,24532.0,-923.0,110109.0,528.00,2628.50,51.0,H-SC,22.56,168.0,-0.04,0.70,63.72,OX40N,NTT,MISC
52,M&M,0.05,7.53,10.50,18.82,27174.0,18122.0,258803.0,3762.88,-6.43,59.0,X-LC,4.53,25.0,0.67,1.64,17.40,X40N,ATH,AUTO

In [10]:
# top 5 today
df_tmp = df_portfolio_features.sort_values(by = 'Today P/L%', ascending=False)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
82,VALIANTORG,10.23,-29.02,145.35,74.15,168791.0,-47478.0,116127.0,838.0,-308.98,79.0,H-SC,4.49,145.0,-0.28,0.73,72.81,XR,NTT,CHEMICALS
5,ATULAUTO,3.20,-12.06,65.52,45.57,113589.0,-23766.0,173366.0,844.0,3759.46,50.0,M-SC,10.09,248.0,-0.21,1.10,33.41,XY24,NTT,AUTO
10,BATAINDIA,2.43,-52.75,186.12,35.20,113165.0,-67868.0,60802.0,2096.0,-20.29,62.0,X-SC,12.84,91.0,-0.60,0.38,22.15,X40,NTT,FOOTWEAR
65,SFL,2.31,-31.62,85.19,26.63,152743.0,-82921.0,179297.0,1287.0,35.77,40.0,M-SC,21.91,242.0,-0.54,1.13,49.64,XY24,NTT,MISC
51,LAOPALA,2.04,-41.64,138.33,39.09,105840.0,-54592.0,76513.0,464.0,67.64,60.0,H-SC,5.09,154.0,-0.52,0.48,18.71,AR,NTT,CERAMICS

In [11]:
# bottom 5 today
df_tmp = df_portfolio_features.sort_values(by = 'Today P/L%', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
72,TANLA,-4.51,-33.45,226.45,117.25,408036.0,-90573.0,180188.0,1922.32,-32.65,51.0,H-SC,15.06,147.0,-0.22,1.14,57.76,AR,ATH,IT
18,COFFEEDAY,-3.64,-50.37,172.57,35.27,97247.0,-57197.0,56352.0,80.00,-61.77,37.0,L-SC,4.28,266.0,-0.59,0.36,38.97,XR,NTT,HOTELS
24,EASEMYTRIP,-3.09,-65.40,321.05,45.70,196428.0,-115632.0,61183.0,26.40,-36.54,30.0,M-SC,6.52,204.0,-0.59,0.39,7.18,XY24,NTT,TRAVEL
58,RAJESHEXPO,-2.78,-84.38,540.69,0.07,115843.0,-115752.0,21425.0,518.00,685.35,35.0,L-SC,36.52,268.0,-1.00,0.14,5.81,OX40N,NTT,JEWELLERY
29,GREENPANEL,-2.41,-54.05,211.48,43.14,177920.0,-98947.0,84131.0,537.00,88.63,30.0,M-SC,10.17,225.0,-0.56,0.53,1.32,XY24,NTT,MISC

In [12]:
# top 5 to exit based on CumlRnk
df_tmp = df_portfolio_features[~df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])]
df_tmp = df_tmp[(df_tmp['Current P/L%'] > -1) & (df_tmp['Current P/L%'] < 1)].sort_values(by = 'CumlRnk', ascending=False)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
80,UTIAMC,-0.88,0.17,50.89,51.15,113341.0,387.0,222717.0,1371.68,-19.39,48.0,M-SC,7.65,229.0,0.00,1.41,4.32,XY24,ATH,FINANCE
68,SIS,-1.31,-0.83,22.28,21.26,24532.0,-923.0,110109.0,528.00,2628.50,51.0,H-SC,22.56,168.0,-0.04,0.70,63.72,OX40N,NTT,MISC

In [13]:
# OX40N stocks to exit
df_tmp = df_portfolio_features[(df_portfolio_features['Symbol'].isin(list_ox40n))].sort_values(by = 'Current P/L%', ascending=False)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
25,FINCABLES,-2.05,58.81,30.92,107.91,72498.0,86826.0,234470.0,1641.55,43.07,73.0,M-SC,18.16,220.0,1.20,1.48,76.40,OX40N,ATH,CABLES
68,SIS,-1.31,-0.83,22.28,21.26,24532.0,-923.0,110109.0,528.00,2628.50,51.0,H-SC,22.56,168.0,-0.04,0.70,63.72,OX40N,NTT,MISC
43,INDIGOPNTS,1.57,-19.04,23.54,0.02,33267.0,-33236.0,141323.0,1408.00,115.40,64.0,M-SC,6.00,222.0,-1.00,0.89,60.34,OX40N,NTT,PAINTS
78,TTKPRESTIG,1.15,-22.43,29.03,0.09,22694.0,-22603.0,78174.0,770.00,81.43,41.0,M-SC,12.20,250.0,-1.00,0.49,40.70,OX40N,NTT,DURABLES
16,CERA,-0.96,-22.50,59.86,23.89,81602.0,-39582.0,136321.0,9475.00,-25.30,39.0,H-SC,12.36,153.0,-0.49,0.86,32.52,OX40N,NTT,CERAMICS

In [14]:
# top 5 to book for rotation
df_tmp = df_portfolio_features[(df_portfolio_features['Current P/L%'] > 20) ].sort_values(by = 'CumlRnk', ascending=False)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
25,FINCABLES,-2.05,58.81,30.92,107.91,72498.0,86826.0,234470.0,1641.55,43.07,73.0,M-SC,18.16,220.0,1.20,1.48,76.40,OX40N,ATH,CABLES
87,ZYDUSLIFE,-2.29,24.16,9.14,35.51,23783.0,50631.0,260205.0,1285.01,8.11,62.0,H-MC,15.99,120.0,2.13,1.64,36.93,AR,ATH,PHARMA
57,QUESS,-1.60,34.87,28.93,73.90,41670.0,37243.0,144036.0,424.00,-27.27,65.0,X-SC,41.53,80.0,0.89,0.91,98.25,XY24,NTT,MISC

In [15]:
# top 5 to monitor for exit
df_tmp = df_portfolio_features[~df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])]
df_tmp = df_tmp[(df_tmp['Current P/L%'] > 0) ].sort_values(by = 'Dev%_PE', ascending=False)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
69,STARHEALTH,-0.90,12.13,31.33,47.26,98759.0,34098.0,315221.0,761.00,76.87,48.0,H-SC,16.84,173.0,0.35,1.99,36.29,XY24,NTT,INSURANCE
25,FINCABLES,-2.05,58.81,30.92,107.91,72498.0,86826.0,234470.0,1641.55,43.07,73.0,M-SC,18.16,220.0,1.20,1.48,76.40,OX40N,ATH,CABLES
87,ZYDUSLIFE,-2.29,24.16,9.14,35.51,23783.0,50631.0,260205.0,1285.01,8.11,62.0,H-MC,15.99,120.0,2.13,1.64,36.93,AR,ATH,PHARMA
80,UTIAMC,-0.88,0.17,50.89,51.15,113341.0,387.0,222717.0,1371.68,-19.39,48.0,M-SC,7.65,229.0,0.00,1.41,4.32,XY24,ATH,FINANCE

In [16]:
# top 5 to book for rotation from weak conviction
df_tmp = df_portfolio_features[~df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])]
df_tmp = df_tmp[~df_tmp['Criteria'].isin(['XY25','XY24','X40', 'X40N'])].sort_values(by = 'RRR Ind', ascending=False)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
87,ZYDUSLIFE,-2.29,24.16,9.14,35.51,23783.0,50631.0,260205.0,1285.01,8.11,62.0,H-MC,15.99,120.0,2.13,1.64,36.93,AR,ATH,PHARMA
25,FINCABLES,-2.05,58.81,30.92,107.91,72498.0,86826.0,234470.0,1641.55,43.07,73.0,M-SC,18.16,220.0,1.20,1.48,76.40,OX40N,ATH,CABLES
68,SIS,-1.31,-0.83,22.28,21.26,24532.0,-923.0,110109.0,528.00,2628.50,51.0,H-SC,22.56,168.0,-0.04,0.70,63.72,OX40N,NTT,MISC
3,ALKYLAMINE,-2.41,-19.06,137.89,92.54,112680.0,-19246.0,81717.0,4520.85,-13.24,55.0,H-SC,13.80,142.0,-0.17,0.52,55.17,SR,ATH,CHEMICALS
42,INDIAMART,0.48,-22.96,160.78,100.92,152780.0,-28312.0,95024.0,4675.60,-65.23,43.0,H-SC,12.71,140.0,-0.19,0.60,2.86,AR,ATH,MISC

In [17]:
# top 5 to accumulate based on lowest RSI_14
df_tmp = df_portfolio_features[df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])].sort_values(by = 'RSI_14', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
28,GODREJCP,1.92,-16.09,58.39,32.90,122260.0,-40152.0,209385.0,1460.97,-13.20,28.0,X-LC,5.09,32.0,-0.33,1.32,1.92,X40N,ATH,FMCG
55,PAGEIND,-2.39,-2.50,37.02,33.59,96867.0,-6719.0,261660.0,51217.29,-30.03,32.0,X-MC,8.87,55.0,-0.07,1.65,24.26,X40,ATH,APPARELS
34,HDFCBANK,-0.35,-11.28,47.70,31.05,124053.0,-33051.0,260069.0,1073.00,-25.96,33.0,X-LC,12.03,26.0,-0.27,1.64,0.94,X40,BTT,BANKS
56,PGHH,0.24,-36.49,107.86,32.01,146267.0,-77912.0,135608.0,17616.87,-57.06,35.0,X-MC,19.23,57.0,-0.53,0.86,0.24,X40,ATH,FMCG
83,VBL,-0.15,-11.58,53.41,35.66,166168.0,-40726.0,311118.0,669.42,-22.18,37.0,X-LC,7.46,13.0,-0.25,1.97,14.55,X40N,ATH,FMCG

In [18]:
# top 5 to accumulate based on Spread and CumlRnk
df_tmp = df_portfolio_features[df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])]
df_tmp = df_tmp[(df_tmp['CumlRnk'] < 100)].sort_values(by = 'Spread%', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
19,COLPAL,-1.00,-24.63,85.56,39.86,169837.0,-64865.0,198500.0,3683.41,-8.76,39.0,X-MC,1.50,62.0,-0.38,1.25,12.28,XY25,ATH,FMCG
23,DMART,-0.80,-1.95,34.03,31.42,104036.0,-6072.0,305718.0,5391.45,-18.44,51.0,X-LC,2.91,14.0,-0.06,1.93,10.32,X40N,ATH,FMCG
50,KOTAKBANK,-0.20,2.42,16.10,18.92,39527.0,5809.0,245511.0,452.46,-10.71,50.0,X-LC,2.99,12.0,0.15,1.55,10.46,X40,ATH,BANKS
8,BAJAJHLDNG,-0.43,3.32,24.12,28.24,63797.0,8495.0,264500.0,14274.15,-4.76,65.0,X-LC,3.05,28.0,0.13,1.67,33.12,X40,ATH,FINANCE
26,GILLETTE,0.24,-10.11,44.31,29.72,101133.0,-25656.0,228240.0,10978.86,-30.84,42.0,X-SC,3.19,83.0,-0.25,1.44,4.89,X40,ATH,FMCG

In [19]:
# top 5 to accumulate based on lowest Gained%
df_tmp = df_portfolio_features[df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])].sort_values(by = 'Gained%', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
56,PGHH,0.24,-36.49,107.86,32.01,146267.0,-77912.0,135608.0,17616.87,-57.06,35.0,X-MC,19.23,57.0,-0.53,0.86,0.24,X40,ATH,FMCG
35,HDFCLIFE,0.17,-7.75,50.85,39.15,117615.0,-19440.0,231297.0,811.41,-31.35,39.0,X-LC,16.33,31.0,-0.17,1.46,0.36,X40,ATH,INSURANCE
47,ITC,0.18,-23.68,63.38,24.70,192173.0,-94070.0,303208.0,452.00,-59.97,38.0,X-LC,10.69,1.0,-0.49,1.92,0.40,X40,NTT,FMCG
20,DABUR,-0.57,-20.06,79.75,43.70,158157.0,-49752.0,198316.0,735.00,-27.41,38.0,X-MC,9.42,70.0,-0.31,1.25,0.92,XY24,BTT,FMCG
34,HDFCBANK,-0.35,-11.28,47.70,31.05,124053.0,-33051.0,260069.0,1073.00,-25.96,33.0,X-LC,12.03,26.0,-0.27,1.64,0.94,X40,BTT,BANKS

In [20]:
# top 5 to accumulate based on lowest CurrAlloc%
df_tmp = df_portfolio_features[df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])].sort_values(by = 'CurrAlloc%', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
10,BATAINDIA,2.43,-52.75,186.12,35.20,113165.0,-67868.0,60802.0,2096.00,-20.29,62.0,X-SC,12.84,91.0,-0.60,0.38,22.15,X40,NTT,FOOTWEAR
61,RELAXO,1.55,-45.16,177.72,52.31,141481.0,-65551.0,79609.0,1176.00,-41.63,59.0,X-SC,13.09,92.0,-0.46,0.50,77.99,X40N,NTT,FOOTWEAR
56,PGHH,0.24,-36.49,107.86,32.01,146267.0,-77912.0,135608.0,17616.87,-57.06,35.0,X-MC,19.23,57.0,-0.53,0.86,0.24,X40,ATH,FMCG
57,QUESS,-1.60,34.87,28.93,73.90,41670.0,37243.0,144036.0,424.00,-27.27,65.0,X-SC,41.53,80.0,0.89,0.91,98.25,XY24,NTT,MISC
2,ACC,-1.09,-40.69,194.75,74.81,309699.0,-109104.0,159024.0,3906.00,-57.90,41.0,X-SC,11.98,85.0,-0.35,1.00,6.24,XY24,BTT,CEMENT

In [21]:
# top 5 to accumulate based on CumlRnk
df_tmp = df_portfolio_features.sort_values(by = 'CumlRnk', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
47,ITC,0.18,-23.68,63.38,24.70,192173.0,-94070.0,303208.0,452.00,-59.97,38.0,X-LC,10.69,1.0,-0.49,1.92,0.40,X40,NTT,FMCG
74,TCS,-0.11,-31.10,80.25,24.20,256163.0,-144067.0,319206.0,4230.71,-41.66,52.0,X-LC,15.04,2.0,-0.56,2.02,19.03,X40,ATH,IT
45,INFY,-1.18,-17.27,69.68,40.38,217032.0,-65000.0,311470.0,1972.00,-37.59,57.0,X-LC,16.10,3.0,-0.30,1.97,17.95,X40,NTT,IT
76,TMPV,1.36,-17.29,72.59,42.75,249836.0,-71933.0,344174.0,600.00,-83.62,55.0,X-LC,4.48,4.0,-0.29,2.18,18.34,XY24,NTT,AUTO
33,HCLTECH,-0.34,-8.99,36.21,23.97,101991.0,-27821.0,281665.0,1853.42,-7.36,68.0,X-LC,12.78,8.0,-0.27,1.78,32.91,X40,ATH,IT

In [22]:
# top 5 for average up
df_tmp = df_portfolio_features[(df_portfolio_features['Dev%_200'] > 5)].sort_values(by = 'CurrAlloc%', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
44,INDUSINDBK,-0.05,-24.92,76.99,32.89,44630.0,-19238.0,57969.0,1800.00,-373.11,54.0,L-MC,13.66,258.0,-0.43,0.37,42.92,XR,NTT,BANKS
61,RELAXO,1.55,-45.16,177.72,52.31,141481.0,-65551.0,79609.0,1176.00,-41.63,59.0,X-SC,13.09,92.0,-0.46,0.50,77.99,X40N,NTT,FOOTWEAR
3,ALKYLAMINE,-2.41,-19.06,137.89,92.54,112680.0,-19246.0,81717.0,4520.85,-13.24,55.0,H-SC,13.80,142.0,-0.17,0.52,55.17,SR,ATH,CHEMICALS
12,BOSCH-HCIL,-1.15,-25.77,34.70,-0.01,32920.0,-32935.0,94870.0,2282.00,19313.04,79.0,M-SC,4.23,231.0,-1.00,0.60,61.48,OX40N,BTT,AC
68,SIS,-1.31,-0.83,22.28,21.26,24532.0,-923.0,110109.0,528.00,2628.50,51.0,H-SC,22.56,168.0,-0.04,0.70,63.72,OX40N,NTT,MISC

In [23]:
# top 5 RSP
df_tmp = df_portfolio_features.sort_values(by = 'RSP', ascending=False)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
12,BOSCH-HCIL,-1.15,-25.77,34.70,-0.01,32920.0,-32935.0,94870.0,2282.00,19313.04,79.0,M-SC,4.23,231.0,-1.00,0.60,61.48,OX40N,BTT,AC
82,VALIANTORG,10.23,-29.02,145.35,74.15,168791.0,-47478.0,116127.0,838.00,-308.98,79.0,H-SC,4.49,145.0,-0.28,0.73,72.81,XR,NTT,CHEMICALS
25,FINCABLES,-2.05,58.81,30.92,107.91,72498.0,86826.0,234470.0,1641.55,43.07,73.0,M-SC,18.16,220.0,1.20,1.48,76.40,OX40N,ATH,CABLES
67,SIEMENS,-1.54,6.32,17.47,24.90,34566.0,11765.0,197860.0,4648.66,66.28,65.0,H-LC,12.66,51.0,0.34,1.25,39.60,AR,ATH,ELECTRICAL
38,HYUNDAI,0.00,15.86,24.23,43.94,70558.0,39868.0,291200.0,2782.73,-4.08,73.0,X-LC,4.15,29.0,0.57,1.84,33.70,X40N,ATH,AUTO

In [24]:
# Top N allocation
df_tmp = df_portfolio_features.sort_values(by = 'CurrAlloc%', ascending=False)
top_n_values = [10, 25, 50]

sum_df = pd.DataFrame({
    'Top_N': top_n_values,
    'Sum_Alloc%': [df_tmp['CurrAlloc%'].head(n).sum() for n in top_n_values]
})

sum_df

   Top_N  Sum_Alloc%
0     10       19.75
1     25       44.75
2     50       76.78

In [25]:
# market-cap-wise allocation
df_tmp = df_portfolio_features[cols]
df_tmp.groupby(df_tmp['Conviction'].str[-2:])['CurrAlloc%'].sum().sort_values(ascending=False)

Conviction
SC    39.45
LC    37.60
MC    22.94
Name: CurrAlloc%, dtype: float64

In [26]:
# criteria-wise allocation
df_portfolio_features.groupby('Criteria')['CurrAlloc%'].sum().sort_values(ascending=False)

Criteria
X40      26.29
XY24     24.98
X40N     18.31
XR        9.13
XY25      7.17
OX40N     7.15
AR        6.11
SR        0.85
Name: CurrAlloc%, dtype: float64

In [27]:
# conviction-wise allocation
df_portfolio_features.groupby('Conviction')['CurrAlloc%'].sum().sort_values(ascending=False)

Conviction
X-LC    35.55
H-SC    19.31
X-MC    18.69
M-SC    11.14
X-SC     8.50
H-MC     2.69
H-LC     1.25
M-MC     1.19
M-LC     0.80
L-SC     0.50
L-MC     0.37
Name: CurrAlloc%, dtype: float64

In [28]:
# sector-wise stats
df_tmp = df_portfolio_features.groupby('Category')[['CurrAlloc%', 'Current', 'Current P/L', 'FTT Amt']].sum().sort_values(by=['Current', 'Current P/L'], ascending=False)
df_tmp['Current P/L%'] = round(df_tmp['Current P/L'] * 100 / df_tmp['Current'], 2)
df_tmp['FTT%'] = round(df_tmp['FTT Amt'] * 100 / df_tmp['Current'], 2)
cols = ['CurrAlloc%', 'Current P/L%', 'FTT%']
df_tmp[cols].sort_values(by=['CurrAlloc%'], ascending=False)

               CurrAlloc%  Current P/L%    FTT%
Category
FMCG                15.25        -23.54   67.96
IT                  11.05        -36.45  104.18
FINANCE             10.70        -14.00   63.10
AUTO                 8.34         -2.66   39.43
MISC                 6.87        -23.24   76.12
BANKS                6.08        -10.99   58.86
PHARMA               5.73          8.57   17.36
INSURANCE            5.58         -5.10   42.26
PAINTS               5.50        -13.16   32.47
ELECTRICAL           4.10         -9.07   47.25
AC                   1.81        -11.30   41.48
REFINERIES           1.69        -11.37   48.78
FOOTWEAR             1.67        -65.94  132.48
BREWERIES            1.66         10.86    7.66
APPARELS             1.65         -2.57   37.02
CABLES               1.48         37.03   30.92
DURABLES             1.47        -65.18  105.37
TRAVEL               1.44        -97.42  196.28
CERAMICS             1.34        -44.25   88.07
CHEMICALS            1.25        -33.73  142.27
ENGINEERING          1.23        -24.24   81.06
CEMENT               1.00        -68.61  194.75
JEWELLERY            0.98       -107.66  179.80
ENTERTAINMENT        0.69        -78.11  184.33
HEALTHCARE           0.68        -67.47  109.51
TEXTILES             0.39        -51.09   94.17
HOTELS               0.36       -101.50  172.57

In [29]:
# money to be made criteria-wise
df_portfolio_features.groupby('Criteria')['FTT Amt'].agg(['sum', 'count']).sort_values(by='sum', ascending=False)

                sum  count
Criteria
XY24      3559590.0     20
X40       2064628.0     18
XR        1353765.0     13
X40N      1184078.0     12
AR        1065333.0      8
OX40N      659034.0     10
XY25       563035.0      5
SR         282901.0      2

In [30]:
# money to be made conviction-wise
df_portfolio_features.groupby('Conviction')['FTT Amt'].agg(['sum', 'count']).sort_values(by='sum', ascending=False)

                  sum  count
Conviction
H-SC        3297031.0     23
X-LC        2433274.0     20
X-MC        1495226.0     14
M-SC        1489332.0     15
X-SC        1230927.0      8
H-MC         272075.0      2
L-SC         213090.0      2
M-LC         165591.0      1
M-MC          56622.0      1
L-MC          44630.0      1
H-LC          34566.0      1

In [31]:
# money to be made criteria and conviction-wise
df_portfolio_features.groupby(['Conviction', 'Criteria'])['FTT Amt'].agg(['sum', 'count']).sort_values(by='sum', ascending=False)

                           sum  count
Conviction Criteria
X-LC       X40       1183917.0      9
H-SC       XY24       994910.0      5
M-SC       XY24       970372.0      7
H-SC       AR         930890.0      5
           XR         794609.0      7
X-SC       XY24       711976.0      3
X-MC       X40        666413.0      7
X-LC       X40N       524608.0      6
           XY24       416043.0      2
X-MC       X40N       354817.0      3
X-SC       X40N       304653.0      3
H-SC       OX40N      293721.0      4
           SR         282901.0      2
X-MC       XY25       255999.0      2
X-LC       XY25       250414.0      2
M-SC       OX40N      249470.0      5
H-MC       XY24       248292.0      1
X-MC       XY24       217997.0      2
X-SC       X40        214298.0      2
M-SC       XR         193396.0      2
M-LC       XR         165591.0      1
L-SC       OX40N      115843.0      1
           XR          97247.0      1
M-SC       AR          76094.0      1
X-LC       XR          58292.0      1
M-MC       XY25        56622.0      1
L-MC       XR          44630.0      1
H-LC       AR          34566.0      1
H-MC       AR          23783.0      1

In [32]:
# notebook execution time

end_time = time.time()
execution_time = round(end_time - start_time, 0)
print(f"Notebook execution time: {execution_time} seconds")

Notebook execution time: 29.0 seconds