<a href="https://colab.research.google.com/github/ankit-rathi/Quantvesting_v2/blob/main/myStocks_Portfolio_Analysis.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
'''
!pip install pandas==2.2.2 -qq
!pip install pyxirr -qq
!pip install ta -qq
!pip install yfinance==0.2.59 -qq
'''

'\n!pip install pandas==2.2.2 -qq\n!pip install pyxirr -qq\n!pip install ta -qq\n!pip install yfinance==0.2.59 -qq\n'

In [2]:
# import libraries

import numpy as np
import pandas as pd
import datetime
import warnings
warnings.filterwarnings('ignore')
import yfinance as yfin
import ta
import matplotlib.pyplot as plt
import requests

In [3]:
# notebook start time
import time
import datetime
import pytz

start_time = time.time()

# function to print date timestamp
def print_date_time():
  tz_NY = pytz.timezone('Asia/Kolkata')
  datetime_NY = datetime.datetime.now(tz_NY)
  print("Run date time (IST):", datetime_NY.strftime("%Y-%m-%d %H:%M:%S"))

In [4]:
# function to get booked and reserved amount
def get_amt():
  # fetch the JSON data from the URL
  url = "https://raw.githubusercontent.com/ankit-rathi/Tradevesting_v1/main/data/myPortfolioAmts.json"
  response = requests.get(url)
  pf_amts = response.json()  # parse the JSON data

  # extract values from the JSON
  py_booked_amt_dm = pf_amts["py_booked_amt_dm"]
  py_booked_amt_sv = pf_amts["py_booked_amt_sv"]
  cy_booked_amt_dm = pf_amts["cy_booked_amt_dm"]
  cy_booked_amt_sv = pf_amts["cy_booked_amt_sv"]
  reserve_amt_dm = pf_amts["reserve_amt_dm"]
  reserve_amt_sv = pf_amts["reserve_amt_sv"]

  # perform calculations
  py_booked_amt = py_booked_amt_dm + py_booked_amt_sv
  cy_booked_amt = cy_booked_amt_dm + cy_booked_amt_sv
  reserve_amt = reserve_amt_dm + reserve_amt_sv
  total_booked_amt = py_booked_amt + cy_booked_amt

  return total_booked_amt, reserve_amt, cy_booked_amt, py_booked_amt

gen_output = 0

In [5]:
# function to format the amount
def format_amt(number):
    abs_number = abs(number)

    if abs_number >= 1_00_00_000:  # Crores
        formatted_amt = f"{number / 1_00_00_000:.2f} C"
    elif abs_number >= 1_00_000:  # Lakhs
        formatted_amt = f"{number / 1_00_000:.2f} L"
    elif abs_number >= 1_000:  # Thousands
        formatted_amt = f"{number / 1_000:.2f} K"
    else:
        formatted_amt = f"{number:.2f}"

    return formatted_amt

# function to set start and end date
def get_start_end_date():
  start_date = (datetime.date.today() + datetime.timedelta(days=-365)).strftime('%Y-%m-%d')
  end_date = (datetime.date.today() + datetime.timedelta(days=1)).strftime('%Y-%m-%d')
  return start_date, end_date

# function to fetch my portfolio csv
def get_mypfs_df():
  mypfs_df = pd.read_csv('https://raw.githubusercontent.com/ankit-rathi/Tradevesting_v1/main/data/myPortfolioStocks.csv')
  return mypfs_df

# function to fetch my prospects csv
def get_mypps_df():
  mypps_df = pd.read_csv('https://raw.githubusercontent.com/ankit-rathi/Tradevesting_v1/main/data/myProspectsScrips.csv')
  return mypps_df

# function to fetch screener data
def get_myscreen_df():
  myscreen_df = pd.read_csv('https://raw.githubusercontent.com/ankit-rathi/Tradevesting_v1/main/data/myScreenerDB.csv')
  return myscreen_df

# function to fetch momentum data
def get_myinvmt_df():
  myinvmt_df = pd.read_csv('https://raw.githubusercontent.com/ankit-rathi/Tradevesting_v1/main/data/myInvestments.csv')
  return myinvmt_df

# function to get the stock ids
def get_stock_ids(df_pf):
  stock_n100 = df_pf['Symbol'].unique()

  exclude = ['CADILAHC','MMTC', 'MASFIN']

  stock_ids = df_pf[~df_pf['Symbol'].isin(exclude) ]['Symbol'].unique()

  #mypf = mypf[mypf.Forecast.notnull()]
  #stock_ids = mypf['Symbol'].unique()

  #stock_ids.sort()
  return stock_ids

# get features from screener data
def get_screener_features():
  myscreen_df = get_myscreen_df()
  cols = ['Symbol', 'EPS', 'MedPE', 'ROCE%', 'ROE%', 'CapType']
  return myscreen_df[cols]

# get relative strength
def get_relative_strength(stock_list):

    # Dictionary to store stock tickers and their corresponding percentage price change
    stock_changes = {}

    # Loop through each stock and fetch its price data
    for stock in stock_list:
        try:
            # Download the stock data for the given date range
            stock_data = yfin.Ticker(stock + '.NS').history(period='1mo', interval='1d')[map(str.title, ['open', 'close', 'low', 'high', 'volume'])]

            # Calculate the percentage change for the stock
            if len(stock_data) > 0:
                start_price = stock_data['Close'].iloc[0]
                end_price = stock_data['Close'].iloc[-1]
                percent_change = round(((end_price - start_price) / start_price) * 100, 2)
                stock_changes[stock] = percent_change
            else:
                stock_changes[stock] = np.nan  # If no data is available, set to NaN

        except Exception as e:
            print(f"Error fetching data for {stock}: {e}")
            stock_changes[stock] = np.nan

    # Create a DataFrame with stock tickers and their percentage changes
    df = pd.DataFrame(list(stock_changes.items()), columns=['Symbol', 'Percent_Change'])

    # Drop any stocks with missing data (NaN values)
    df = df.dropna()

    # Calculate the percentile rank based on percentage change
    df['RSP'] = round(df['Percent_Change'].rank(pct=True) * 100, 2)
    cols = ['Symbol', 'RSP']
    df = df[cols]
    # Sort by percentile rank (optional)
    df = df.sort_values(by='RSP', ascending=False).reset_index(drop=True)

    return df

In [6]:
# function to get stock technicals
def stock_prec_dev(stock_symbol):
    #stock_symbol = 'ULTRACEMCO.NS'
    short_window = 20
    mid_window = 50
    long_window = 200
    moving_avg = 'SMA'

    start = datetime.datetime(*map(int, start_date.split('-')))
    end = datetime.datetime(*map(int, end_date.split('-')))

    stock_df = yfin.Ticker(stock_symbol + '.NS').history(period='max', interval='1d')[map(str.title, ['open', 'close', 'low', 'high', 'volume'])]

    stock_df['Max'] = round(max(stock_df['Close']),2)
    stock_df = stock_df[(stock_df.index <= end_date) & (stock_df.index >= start_date)]
    stock_df['200_SMA'] = round(stock_df['Close'].rolling(window = 200, min_periods = 1).mean(),0)
    stock_df['Dev%_200'] = round((stock_df['Close'] - stock_df['200_SMA'])*100/stock_df['200_SMA'],2)
    stock_df.dropna(axis = 0, inplace = True) # remove any null rows

    stock_df['20_SMA'] = stock_df['Close'].rolling(window=20).mean()
    stock_df['50_SMA'] = stock_df['Close'].rolling(window=50).mean()
    stock_df['Symbol'] = stock_symbol

    stock_df['Close'] = round(stock_df['Close'],2)
    stock_df['Min'] = round(min(stock_df['Close']),2)
    stock_df['RSI_14'] = ta.momentum.RSIIndicator(close=stock_df['Close'], window=14).rsi()
    stock_df['RSI_14'] = round(stock_df['RSI_14'],0)
    stock_df['Prev_Close'] = stock_df['Close'].shift(1)
    stock_df.drop(['Open', 'Low', 'High', 'Volume'], axis=1, inplace=True)
    stock_df = stock_df.tail(1)

    max_SMA = max(stock_df['20_SMA'].item(), stock_df['50_SMA'].item(), stock_df['200_SMA'].item())
    min_SMA = min(stock_df['20_SMA'].item(), stock_df['50_SMA'].item(), stock_df['200_SMA'].item())
    ABS_Spread = max_SMA - min_SMA
    stock_df['Spread%'] = round((ABS_Spread / stock_df['200_SMA'].item()) * 100,2)

    return stock_df

# function to compute stock attributes
def get_common_features(stock_ids, df_mypf):

  df_prec_dev = pd.DataFrame()
  df_tmp = get_screener_features()
  df_rs = get_relative_strength(stock_ids)

  for stock_id in stock_ids:
      tmp = stock_prec_dev(stock_id)
      tmp = tmp.reset_index()
      df_prec_dev = pd.concat([df_prec_dev, tmp], ignore_index = True)
  df_prec_dev = pd.merge(df_prec_dev, df_mypf, on= 'Symbol')
  df_prec_dev = pd.merge(df_prec_dev, df_tmp, on= 'Symbol', how='left')
  df_prec_dev = pd.merge(df_prec_dev, df_rs, on= 'Symbol', how='left')
  #print(df_prec_dev.columns)
  df_prec_dev['Curr_PE'] = round(df_prec_dev['Close']/df_prec_dev['EPS'],1)
  df_prec_dev['Dev%_PE'] = round((df_prec_dev['Curr_PE'] - df_prec_dev['MedPE'])*100/df_prec_dev['MedPE'],2)
  df_prec_dev['Conviction'] = df_prec_dev['Conviction'] + '-' + df_prec_dev['CapType']
  return df_prec_dev

# function to arrange stock features
def arrange_features(df_stocks, common_cols, diff_cols):
  df_stocks_common = df_stocks[common_cols].drop_duplicates()
  df_stocks_diff = df_stocks[diff_cols]
  df_stocks_diff['Investment'] = df_stocks_diff['AvgCost'] * df_stocks_diff['Shares']
  df_stocks_diff = df_stocks_diff.groupby(['Symbol'])[['Shares', 'Investment']].aggregate(['sum']).reset_index()
  df_stocks_diff.columns = ['Symbol', 'Shares', 'Investment']
  df_stocks_diff['AvgCost'] = round(df_stocks_diff['Investment']/df_stocks_diff['Shares'],2)
  df_stocks = pd.merge(df_stocks_diff, df_stocks_common, on='Symbol')
  return df_stocks

# plot fact distribution across dimension
def plot_pie_chart(df, dimension, fact):
  # grouping the data by category and calculating the sum of fact for each type
  grouped_data = df.groupby(dimension)[fact].sum()

  # sorting the grouped data in descending order
  grouped_data = grouped_data.sort_values(ascending=False)

  # creating a pie chart
  grouped_data.plot.pie(autopct='%1.1f%%', startangle=90, figsize=(6, 6))

  # adding a title and displaying the plot
  plt.title(f'{dimension} {fact} Distribution')
  plt.ylabel('')  # To hide the y-label
  plt.show()

In [7]:
# function to get portfolio features

def get_portfolio_features(df_common_features):

  print_date_time()
  print('-------------------')

  #df_common_features["Target"] = df_common_features["Target"].fillna(df_common_features["Max"])
  df_common_features['NTT'] = np.where(df_common_features['Strategy']== 'NTT', df_common_features["Target"], df_common_features['Max'])
  df_common_features['LTT'] = np.where(df_common_features['Strategy']== 'BTT', df_common_features["Target"], df_common_features['Max'])
  df_common_features['BOL'] = df_common_features['Min']

  tmp_df = df_common_features[df_common_features['Symbol'].isin(mypf_df[mypf_df['InPortfolio'] != 'NA'].Symbol.values)]
  print('qualified stocks: '+str(len(tmp_df['Symbol'].unique())))
  tmp_df1 = tmp_df[tmp_df['LatestQtr'] == 1]
  print('with latest results: '+str(len(tmp_df1['Symbol'].unique())))
  tmp_df1 = tmp_df1[tmp_df1['StarStock'] == 1]
  print('still star stocks: '+str(len(tmp_df1['Symbol'].unique())))
  tmp_df['Investment'] = tmp_df['AvgCost'] * tmp_df['Shares']
  tmp_df['Current'] = round(tmp_df['Close'] * tmp_df['Shares'],0)
  tmp_df['Previous'] = tmp_df['Prev_Close'] * tmp_df['Shares']
  tmp_df['EstimatedST'] = tmp_df['NTT'] * tmp_df['Shares']
  tmp_df['EstimatedLT'] = tmp_df['LTT'] * tmp_df['Shares']
  tmp_df['Current P/L'] = round((tmp_df['Current'] - tmp_df['Investment']),0)
  tmp_df['Today P/L%'] = round((tmp_df['Current'] - tmp_df['Previous'])*100/tmp_df['Previous'],2)
  tmp_df['Current P/L%'] = round((tmp_df['Current'] - tmp_df['Investment'])*100/tmp_df['Investment'],2)
  tmp_df['EstimatedST P/L%'] = round((tmp_df['EstimatedST'] - tmp_df['Investment'])*100/tmp_df['Investment'],2)
  tmp_df['EstimatedLT P/L%'] = round((tmp_df['EstimatedLT'] - tmp_df['Investment'])*100/tmp_df['Investment'],2)
  tmp_df['NTT%'] = round((tmp_df['NTT'] - tmp_df['Close'])*100/tmp_df['Close'],2)
  tmp_df['LTT%'] = round((tmp_df['LTT'] - tmp_df['Close'])*100/tmp_df['Close'],2)
  tmp_df['Gained%'] = round((tmp_df['Close'] - tmp_df['BOL'])*100/tmp_df['BOL'],2)
  investment = round(sum(tmp_df['AvgCost']*tmp_df['Shares']),0)
  current = round(sum(tmp_df['Close']*tmp_df['Shares']),0)
  tmp_df['InitAlloc%'] = round(tmp_df['Investment']*100/investment,2)
  tmp_df['CurrAlloc%'] = round(tmp_df['Current']*100/current,2)
  tmp_df['FTT'] = tmp_df['LTT']
  tmp_df.loc[tmp_df['Strategy'] == 'NTT', 'FTT'] = tmp_df['NTT']
  tmp_df['FTT%'] = tmp_df['LTT%']
  tmp_df.loc[tmp_df['Strategy'] == 'NTT', 'FTT%'] = tmp_df['NTT%']
  tmp_df['FTT Amt'] = round(tmp_df['FTT%'] * tmp_df['Current']/100,0)
  tmp_df['OTT%'] = round((tmp_df['FTT'] - tmp_df['AvgCost'])*100/tmp_df['AvgCost'],2)
  tmp_df['RRR Ind'] = round(tmp_df['Current P/L']/tmp_df['FTT Amt'],2)
  tmp_df['Risk Ind'] = round(tmp_df['Current P/L%']*tmp_df['CurrAlloc%'],0)

  return tmp_df

# function to print portfolio features
def print_portfolio_stats(df_portfolio_features, myinvmt_df):
  from pyxirr import xirr

  total_booked_amt, reserve_amt, cy_booked_amt, py_booked_amt = get_amt()

  dates = myinvmt_df['Date'].values
  dates = np.append(dates, datetime.date.today().strftime('%d-%b-%y'))
  investment = myinvmt_df['Investment'].values
  dates= pd.to_datetime(dates)

  current = round(sum(df_portfolio_features['Close']*df_portfolio_features['Shares']),0) + reserve_amt
  investment_xirr = np.append(investment, current)
  cagr = round(xirr(pd.DataFrame({"dates": dates, "amounts": investment_xirr}))*100,2)

  investment = -sum(investment)
  invested = round(sum(df_portfolio_features['AvgCost']*df_portfolio_features['Shares']),0) + reserve_amt
  previous = round(sum(df_portfolio_features['Prev_Close']*df_portfolio_features['Shares']),0) + reserve_amt
  cy_invested = investment + py_booked_amt

  today_pnl_amount = current-previous
  today_pnl_percentage = round((current-previous)*100/previous,2)

  curr_pnl_amount = current-invested
  curr_pnl_percentage = round((curr_pnl_amount)*100/(cy_invested),2)

  cy_pnl_amount = cy_booked_amt + curr_pnl_amount
  cy_pnl_percentage = round((cy_pnl_amount)*100/cy_invested,2)

  overall_pnl_amount = total_booked_amt + curr_pnl_amount
  overall_pnl_percentage = round((overall_pnl_amount)*100/investment,2)

  estimate_st = round(sum(df_portfolio_features['FTT']*df_portfolio_features['Shares']),0)  + reserve_amt
  est_st_pnl_amount = estimate_st-current
  est_st_pnl_percentage = round((est_st_pnl_amount)*100/current,2)

  estimate_lt = round(sum(df_portfolio_features['LTT']*df_portfolio_features['Shares']),0)  + reserve_amt
  est_lt_pnl_amount = estimate_lt-current
  est_lt_pnl_percentage = round((est_lt_pnl_amount)*100/current,2)

  total_profit = round(sum(df_portfolio_features[df_portfolio_features['Current P/L%'] > 0]['Current']) - sum(df_portfolio_features[df_portfolio_features['Current P/L%'] > 0]['Investment']),0)
  total_loss = round(sum(df_portfolio_features[df_portfolio_features['Current P/L%'] < 0]['Current']) - sum(df_portfolio_features[df_portfolio_features['Current P/L%'] < 0]['Investment']),0)

  cy_booked_percentage = round((cy_booked_amt)*100/current,2)
  py_booked_percentage = round((py_booked_amt)*100/investment,2)
  total_booked_percentage = round((total_booked_amt)*100/investment,2)

  print('-------------------')
  print('Initial Investment: ', format_amt(investment))
  print('CY Investment: ', format_amt(cy_invested))
  print('Reserve: ', format_amt(reserve_amt))
  print('Current: ',  format_amt(current))
  print('-------------------')
  print('Today PnL: '+ '{} ({}%)'.format(format_amt(today_pnl_amount), today_pnl_percentage))
  print('Current PnL: '+ '{} ({}%)'.format(format_amt(curr_pnl_amount), curr_pnl_percentage))
  print('CY Booked + Current PnL: '+ '{} ({}%)'.format(format_amt(cy_pnl_amount), cy_pnl_percentage))
  print('-------------------')
  print('Total profit: ', format_amt(total_profit))
  print('Total loss: ', format_amt(total_loss))
  print('-------------------')
  print('Total Booked + Current PnL: '+ '{} ({}%)'.format(format_amt(overall_pnl_amount), overall_pnl_percentage))
  print('Total Booked PnL: '+ '{} ({}%)'.format(format_amt(total_booked_amt), total_booked_percentage))
  print('Curr Year Booked PnL: '+ '{} ({}%)'.format(format_amt(cy_booked_amt), cy_booked_percentage))
  print('Prev Year Booked PnL: '+ '{} ({}%)'.format(format_amt(py_booked_amt), py_booked_percentage))
  print('===================')
  print('Est FTT: ',  format_amt(estimate_st))
  print('Est FTT PnL: '+ '{} ({}%)'.format(format_amt(est_st_pnl_amount), est_st_pnl_percentage))

  print('===================')
  print('Deployed: ', format_amt(investment))

  print('Current: ', format_amt(current))

  print('CAGR/XIRR %: '+'{}%'.format(cagr))

In [8]:
# get start and end date
start_date, end_date = get_start_end_date()

# get portfolio and prospects data
mypfs_df = get_mypfs_df()
mypps_df = get_mypps_df()
myinvmt_df = get_myinvmt_df()

# merge above datasets
mypf_df = pd.merge(mypfs_df, mypps_df, on="Symbol")

# seggregate dm and sv portfolio
dm_pf = mypf_df[mypf_df['InPortfolio'] == 'DM']
sv_pf = mypf_df[mypf_df['InPortfolio'] == 'SV']

# build portfolio stock dataframe
dm_stocks = get_stock_ids(dm_pf)
sv_stocks = get_stock_ids(sv_pf)
df_stocks = pd.concat([dm_pf,sv_pf], ignore_index = True)

# arrange common and diff stock features
common_cols = ['Symbol', 'Target', 'Criteria', 'Strategy', 'CumlRnk', 'LatestQtr', 'StarStock', 'Conviction', 'Category', 'InFolio', 'XIRR', 'MBQ']
diff_cols = ['Symbol', 'AvgCost', 'Shares']
df_stocks = arrange_features(df_stocks, common_cols, diff_cols)

# get common features
stock_ids = df_stocks['Symbol'].values
df_common_features = get_common_features(stock_ids, df_stocks)

df_common_features.reset_index(drop=True, inplace=True)
df_common_features.drop(['Date'], axis=1, inplace=True)
# get and print portfolio features
df_portfolio_features = get_portfolio_features(df_common_features)

print_portfolio_stats(df_portfolio_features, myinvmt_df)

df = df_portfolio_features
#plot_pie_chart(df, 'CapType', 'Current')
list_ox40n = list(df[df['MBQ'].str.contains('OX40N', na=False)]['Symbol'].values)

Run date time (IST): 2026-04-22 10:16:40
-------------------
qualified stocks: 90
with latest results: 28
still star stocks: 17
-------------------
Initial Investment:  1.38 C
CY Investment:  1.80 C
Reserve:  1.84 K
Current:  1.47 C
-------------------
Today PnL: -24.90 K (-0.17%)
Current PnL: -33.40 L (-18.52%)
CY Booked + Current PnL: -32.44 L (-17.98%)
-------------------
Total profit:  1.84 L
Total loss:  -35.24 L
-------------------
Total Booked + Current PnL: 10.43 L (7.59%)
Total Booked PnL: 43.83 L (31.88%)
Curr Year Booked PnL: 96.00 K (0.65%)
Prev Year Booked PnL: 42.87 L (31.18%)
===================
Est FTT:  2.52 C
Est FTT PnL: 1.06 C (71.96%)
===================
Deployed:  1.38 C
Current:  1.47 C
CAGR/XIRR %: 3.12%

In [9]:
# top 5 near their targets
cols = ['Symbol', 'Today P/L%', 'Current P/L%', 'FTT%', 'OTT%', 'FTT Amt', 'Current P/L', 'Current', 'FTT', 'Dev%_PE', 'RSI_14','Conviction', 'Spread%',  'CumlRnk', 'RRR Ind', 'CurrAlloc%', 'Gained%', 'Criteria', 'Strategy', 'Category']
df_tmp = df_portfolio_features[~df_portfolio_features['Symbol'].isin(['ENRIN','BLUSPRING','DIGITIDE'])]
df_tmp = df_tmp.sort_values(by = 'FTT Amt', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
54,MASFIN,2.88,-0.49,22.17,21.57,21616.0,-480.0,97500.0,397.04,-14.18,62.0,H-SC,2.88,167.0,-0.02,0.66,25.99,XR,ATH,FINANCE
53,MARUTI,-0.64,-1.04,29.29,27.95,31340.0,-1120.0,107000.0,17292.00,-18.07,51.0,X-LC,12.10,33.0,-0.04,0.73,15.57,XR,ATH,AUTO
61,RECLTD,0.13,3.91,16.19,20.74,34180.0,7948.0,211118.0,446.00,15.23,71.0,M-MC,4.07,191.0,0.23,1.44,25.81,XY25,NTT,FINANCE
81,TTKPRESTIG,0.30,-34.68,53.23,0.09,35040.0,-34949.0,65828.0,770.00,52.83,57.0,M-SC,22.66,250.0,-1.00,0.45,17.21,OX40N,NTT,DURABLES
1,ABB,-1.00,31.78,10.46,45.57,36062.0,83141.0,344760.0,7934.00,-15.30,73.0,H-MC,19.16,125.0,2.31,2.35,53.10,AR,NTT,ELECTRICAL

In [10]:
# top 5 today
df_tmp = df_portfolio_features.sort_values(by = 'Today P/L%', ascending=False)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
59,RAJESHEXPO,4.99,-76.32,322.62,0.07,104790.0,-104696.0,32481.0,518.00,1090.66,58.0,L-SC,40.48,268.0,-1.00,0.22,52.49,OX40N,NTT,JEWELLERY
7,AWL,4.07,-32.45,147.23,67.02,354384.0,-115608.0,240701.0,485.00,-63.67,63.0,X-SC,22.87,81.0,-0.33,1.64,13.85,XY24,NTT,FMCG
54,MASFIN,2.88,-0.49,22.17,21.57,21616.0,-480.0,97500.0,397.04,-14.18,62.0,H-SC,2.88,167.0,-0.02,0.66,25.99,XR,ATH,FINANCE
67,SFL,2.24,-45.26,131.31,26.63,188497.0,-118667.0,143551.0,1287.00,8.65,61.0,M-SC,16.51,242.0,-0.63,0.98,19.64,XY24,NTT,MISC
75,TANLA,1.86,-43.54,289.10,119.69,441970.0,-117883.0,152878.0,1943.92,-42.92,65.0,H-SC,21.30,147.0,-0.27,1.04,32.36,AR,ATH,IT

In [11]:
# bottom 5 today
df_tmp = df_portfolio_features.sort_values(by = 'Today P/L%', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
34,HCLTECH,-9.42,-15.28,46.18,23.83,94645.0,-36976.0,204948.0,1908.19,-11.08,34.0,X-LC,7.27,8.0,-0.39,1.40,0.00,X40,ATH,IT
76,TATAELXSI,-4.62,-36.07,106.52,32.03,89777.0,-47553.0,84282.0,9161.00,-20.03,50.0,H-SC,17.78,158.0,-0.53,0.57,11.55,OX40N,NTT,IT
46,INFY,-3.31,-13.56,55.30,34.24,149568.0,-42421.0,270467.0,1972.00,-32.15,42.0,X-LC,12.56,3.0,-0.28,1.84,4.01,X40,NTT,IT
14,BSOFT,-2.54,-30.31,116.36,50.79,114058.0,-42631.0,98022.0,831.70,-10.71,55.0,H-SC,6.56,172.0,-0.37,0.67,15.59,XR,ATH,IT
10,BANDHANBNK,-2.12,-17.07,132.02,92.42,304987.0,-47543.0,231016.0,400.00,98.28,57.0,H-SC,4.32,174.0,-0.16,1.58,27.26,XY24,NTT,BANKS

In [12]:
# top 5 to exit based on CumlRnk
df_tmp = df_portfolio_features[~df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])]
df_tmp = df_tmp[(df_tmp['Current P/L%'] > -1) & (df_tmp['Current P/L%'] < 1)].sort_values(by = 'CumlRnk', ascending=False)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
72,STARHEALTH,-0.47,-0.99,48.73,47.26,135634.0,-2785.0,278338.0,761.00,56.24,73.0,H-SC,2.94,173.0,-0.02,1.90,44.15,XY24,NTT,INSURANCE
54,MASFIN,2.88,-0.49,22.17,21.57,21616.0,-480.0,97500.0,397.04,-14.18,62.0,H-SC,2.88,167.0,-0.02,0.66,25.99,XR,ATH,FINANCE

In [13]:
# OX40N stocks to exit
df_tmp = df_portfolio_features[(df_portfolio_features['Symbol'].isin(list_ox40n))].sort_values(by = 'Current P/L%', ascending=False)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
26,FINCABLES,1.15,22.16,70.20,107.91,126614.0,32718.0,180362.0,1641.55,10.10,69.0,M-SC,4.15,220.0,0.26,1.23,35.69,OX40N,ATH,CABLES
70,SIS,0.92,-21.89,55.25,21.26,47916.0,-24306.0,86726.0,528.00,2049.22,76.0,H-SC,9.20,168.0,-0.51,0.59,28.95,OX40N,NTT,MISC
17,CERA,1.09,-30.01,77.01,23.89,94812.0,-52786.0,123117.0,9475.00,-32.46,68.0,H-SC,13.27,153.0,-0.56,0.84,18.31,OX40N,NTT,CERAMICS
51,KANSAINER,0.62,-30.74,63.85,13.47,119246.0,-82908.0,186759.0,340.00,-40.41,67.0,H-SC,19.25,162.0,-0.70,1.27,30.45,XY24,NTT,PAINTS
81,TTKPRESTIG,0.30,-34.68,53.23,0.09,35040.0,-34949.0,65828.0,770.00,52.83,57.0,M-SC,22.66,250.0,-1.00,0.45,17.21,OX40N,NTT,DURABLES

In [14]:
# top 5 to book for rotation
df_tmp = df_portfolio_features[(df_portfolio_features['Current P/L%'] > 20) ].sort_values(by = 'CumlRnk', ascending=False)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
26,FINCABLES,1.15,22.16,70.20,107.91,126614.0,32718.0,180362.0,1641.55,10.1,69.0,M-SC,4.15,220.0,0.26,1.23,35.69,OX40N,ATH,CABLES
1,ABB,-1.00,31.78,10.46,45.57,36062.0,83141.0,344760.0,7934.00,-15.3,73.0,H-MC,19.16,125.0,2.31,2.35,53.10,AR,NTT,ELECTRICAL

In [15]:
# top 5 to monitor for exit
df_tmp = df_portfolio_features[~df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])]
df_tmp = df_tmp[(df_tmp['Current P/L%'] > 0) ].sort_values(by = 'Dev%_PE', ascending=False)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
61,RECLTD,0.13,3.91,16.19,20.74,34180.0,7948.0,211118.0,446.00,15.23,71.0,M-MC,4.07,191.0,0.23,1.44,25.81,XY25,NTT,FINANCE
26,FINCABLES,1.15,22.16,70.20,107.91,126614.0,32718.0,180362.0,1641.55,10.10,69.0,M-SC,4.15,220.0,0.26,1.23,35.69,OX40N,ATH,CABLES
1,ABB,-1.00,31.78,10.46,45.57,36062.0,83141.0,344760.0,7934.00,-15.30,73.0,H-MC,19.16,125.0,2.31,2.35,53.10,AR,NTT,ELECTRICAL
71,SONACOMS,1.17,1.74,36.71,39.09,37781.0,1759.0,102918.0,804.02,-19.39,66.0,M-MC,11.41,193.0,0.05,0.70,45.59,AR,ATH,AUTO

In [16]:
# top 5 to book for rotation from weak conviction
df_tmp = df_portfolio_features[~df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])]
df_tmp = df_tmp[~df_tmp['Criteria'].isin(['XY25','XY24','X40', 'X40N'])].sort_values(by = 'RRR Ind', ascending=False)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
1,ABB,-1.00,31.78,10.46,45.57,36062.0,83141.0,344760.0,7934.00,-15.30,73.0,H-MC,19.16,125.0,2.31,2.35,53.10,AR,NTT,ELECTRICAL
26,FINCABLES,1.15,22.16,70.20,107.91,126614.0,32718.0,180362.0,1641.55,10.10,69.0,M-SC,4.15,220.0,0.26,1.23,35.69,OX40N,ATH,CABLES
71,SONACOMS,1.17,1.74,36.71,39.09,37781.0,1759.0,102918.0,804.02,-19.39,66.0,M-MC,11.41,193.0,0.05,0.70,45.59,AR,ATH,AUTO
54,MASFIN,2.88,-0.49,22.17,21.57,21616.0,-480.0,97500.0,397.04,-14.18,62.0,H-SC,2.88,167.0,-0.02,0.66,25.99,XR,ATH,FINANCE
89,ZYDUSLIFE,-0.12,-2.20,38.68,35.63,79281.0,-4608.0,204966.0,1286.17,-14.86,57.0,H-MC,4.66,120.0,-0.06,1.40,10.01,AR,ATH,PHARMA

In [17]:
# top 5 to accumulate based on lowest RSI_14
df_tmp = df_portfolio_features[df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])].sort_values(by = 'RSI_14', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
34,HCLTECH,-9.42,-15.28,46.18,23.83,94645.0,-36976.0,204948.0,1908.19,-11.08,34.0,X-LC,7.27,8.0,-0.39,1.40,0.00,X40,ATH,IT
2,ABBOTINDIA,0.51,-14.41,37.94,18.07,58082.0,-25765.0,153090.0,35195.00,-27.11,41.0,X-MC,11.84,58.0,-0.44,1.04,0.51,X40,ATH,PHARMA
41,ICICIPRULI,-1.52,-10.35,45.82,30.73,80923.0,-20395.0,176610.0,790.00,-34.44,41.0,X-MC,12.98,78.0,-0.25,1.20,7.62,X40,ATH,INSURANCE
46,INFY,-3.31,-13.56,55.30,34.24,149568.0,-42421.0,270467.0,1972.00,-32.15,42.0,X-LC,12.56,3.0,-0.28,1.84,4.01,X40,NTT,IT
18,CIPLA,-0.45,-0.32,35.58,35.15,43220.0,-386.0,121473.0,1663.60,-23.13,43.0,X-LC,15.86,18.0,-0.01,0.83,2.90,X40N,ATH,PHARMA

In [18]:
# top 5 to accumulate based on Spread and CumlRnk
df_tmp = df_portfolio_features[df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])]
df_tmp = df_tmp[(df_tmp['CumlRnk'] < 100)].sort_values(by = 'Spread%', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
69,SIEMENS,0.48,0.47,24.93,25.51,46612.0,875.0,186970.0,4671.50,57.12,73.0,H-LC,3.55,51.0,0.02,1.27,31.97,AR,ATH,ELECTRICAL
24,DMART,-0.72,9.53,18.33,29.60,50111.0,23784.0,273384.0,5391.45,-7.65,67.0,X-LC,5.71,14.0,0.47,1.86,24.96,X40N,ATH,FMCG
63,RELIANCE,0.32,-12.85,43.77,25.30,76660.0,-25820.0,175143.0,1952.00,-15.03,48.0,X-LC,5.71,21.0,-0.34,1.19,5.57,XY25,BTT,REFINERIES
82,UNITDSPR,0.77,0.90,19.69,20.77,46516.0,2098.0,236242.0,1644.00,-10.48,62.0,X-MC,5.82,64.0,0.05,1.61,12.69,X40N,NTT,BREWERIES
86,VOLTAS,1.28,15.45,25.76,45.20,57025.0,29628.0,221370.0,1856.00,32.11,63.0,X-MC,6.52,79.0,0.52,1.51,23.30,XY25,NTT,AC

In [19]:
# top 5 to accumulate based on lowest Gained%
df_tmp = df_portfolio_features[df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])].sort_values(by = 'Gained%', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
34,HCLTECH,-9.42,-15.28,46.18,23.83,94645.0,-36976.0,204948.0,1908.19,-11.08,34.0,X-LC,7.27,8.0,-0.39,1.40,0.00,X40,ATH,IT
2,ABBOTINDIA,0.51,-14.41,37.94,18.07,58082.0,-25765.0,153090.0,35195.00,-27.11,41.0,X-MC,11.84,58.0,-0.44,1.04,0.51,X40,ATH,PHARMA
18,CIPLA,-0.45,-0.32,35.58,35.15,43220.0,-386.0,121473.0,1663.60,-23.13,43.0,X-LC,15.86,18.0,-0.01,0.83,2.90,X40N,ATH,PHARMA
46,INFY,-3.31,-13.56,55.30,34.24,149568.0,-42421.0,270467.0,1972.00,-32.15,42.0,X-LC,12.56,3.0,-0.28,1.84,4.01,X40,NTT,IT
49,JIOFIN,0.14,-21.99,64.62,28.43,150396.0,-65588.0,232739.0,387.00,-23.21,46.0,X-LC,18.81,34.0,-0.44,1.59,4.90,XY24,BTT,FINANCE

In [20]:
# top 5 to accumulate based on lowest CurrAlloc%
df_tmp = df_portfolio_features[df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])].sort_values(by = 'CurrAlloc%', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
62,RELAXO,-0.36,-60.50,285.57,52.31,163746.0,-87820.0,57340.0,1176.0,-57.99,56.0,X-SC,31.12,92.0,-0.54,0.39,28.21,X40N,NTT,FOOTWEAR
11,BATAINDIA,-0.54,-51.09,176.44,35.20,111035.0,-65739.0,62931.0,2096.0,-17.55,62.0,X-SC,30.87,91.0,-0.59,0.43,24.81,X40,NTT,FOOTWEAR
58,QUESS,0.29,-19.31,115.51,73.90,99537.0,-20621.0,86172.0,424.0,-56.47,59.0,X-SC,18.60,80.0,-0.21,0.59,15.92,XY24,NTT,MISC
53,MARUTI,-0.64,-1.04,29.29,27.95,31340.0,-1120.0,107000.0,17292.0,-18.07,51.0,X-LC,12.10,33.0,-0.04,0.73,15.57,XR,ATH,AUTO
36,HDFCLIFE,-1.11,-1.03,34.06,32.69,40342.0,-1229.0,118443.0,814.3,-22.40,44.0,X-LC,17.81,31.0,-0.03,0.81,7.30,X40,ATH,INSURANCE

In [21]:
# top 5 to accumulate based on CumlRnk
df_tmp = df_portfolio_features.sort_values(by = 'CumlRnk', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
48,ITC,-0.98,-19.24,47.42,19.06,130269.0,-65452.0,274714.0,452.00,-55.52,53.0,X-LC,18.76,1.0,-0.50,1.87,6.57,X40,NTT,FMCG
77,TCS,-1.75,-24.70,68.10,26.57,237551.0,-114447.0,348826.0,4311.59,-36.41,53.0,X-LC,15.65,2.0,-0.48,2.38,8.87,X40,ATH,IT
46,INFY,-3.31,-13.56,55.30,34.24,149568.0,-42421.0,270467.0,1972.00,-32.15,42.0,X-LC,12.56,3.0,-0.28,1.84,4.01,X40,NTT,IT
79,TMPV,1.29,-17.94,66.44,36.58,194008.0,-63836.0,292005.0,600.00,-82.53,63.0,X-LC,8.96,4.0,-0.33,1.99,21.71,XY24,NTT,AUTO
34,HCLTECH,-9.42,-15.28,46.18,23.83,94645.0,-36976.0,204948.0,1908.19,-11.08,34.0,X-LC,7.27,8.0,-0.39,1.40,0.00,X40,ATH,IT

In [22]:
# top 5 for average up
df_tmp = df_portfolio_features[(df_portfolio_features['Dev%_200'] > 5)].sort_values(by = 'CurrAlloc%', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
71,SONACOMS,1.17,1.74,36.71,39.09,37781.0,1759.0,102918.0,804.02,-19.39,66.0,M-MC,11.41,193.0,0.05,0.70,45.59,AR,ATH,AUTO
73,SURYODAY,0.46,-15.92,46.32,23.03,69745.0,-28499.0,150572.0,216.00,64.47,67.0,H-SC,3.46,166.0,-0.41,1.03,28.41,XR,NTT,BANKS
26,FINCABLES,1.15,22.16,70.20,107.91,126614.0,32718.0,180362.0,1641.55,10.10,69.0,M-SC,4.15,220.0,0.26,1.23,35.69,OX40N,ATH,CABLES
69,SIEMENS,0.48,0.47,24.93,25.51,46612.0,875.0,186970.0,4671.50,57.12,73.0,H-LC,3.55,51.0,0.02,1.27,31.97,AR,ATH,ELECTRICAL
61,RECLTD,0.13,3.91,16.19,20.74,34180.0,7948.0,211118.0,446.00,15.23,71.0,M-MC,4.07,191.0,0.23,1.44,25.81,XY25,NTT,FINANCE

In [23]:
# top 5 RSP
df_tmp = df_portfolio_features.sort_values(by = 'RSP', ascending=False)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
59,RAJESHEXPO,4.99,-76.32,322.62,0.07,104790.0,-104696.0,32481.0,518.0,1090.66,58.0,L-SC,40.48,268.0,-1.00,0.22,52.49,OX40N,NTT,JEWELLERY
51,KANSAINER,0.62,-30.74,63.85,13.47,119246.0,-82908.0,186759.0,340.0,-40.41,67.0,H-SC,19.25,162.0,-0.70,1.27,30.45,XY24,NTT,PAINTS
60,RAJOOENG,1.63,-34.73,113.90,39.61,76199.0,-35600.0,66900.0,143.1,-55.84,63.0,H-SC,27.50,136.0,-0.47,0.46,43.32,AR,ATH,MISC
70,SIS,0.92,-21.89,55.25,21.26,47916.0,-24306.0,86726.0,528.0,2049.22,76.0,H-SC,9.20,168.0,-0.51,0.59,28.95,OX40N,NTT,MISC
85,VBL,0.83,-1.19,37.14,35.50,115906.0,-3764.0,312078.0,670.8,-12.73,72.0,X-LC,8.85,13.0,-0.03,2.13,28.14,X40N,ATH,FMCG

In [24]:
# Top N allocation
df_tmp = df_portfolio_features.sort_values(by = 'CurrAlloc%', ascending=False)
top_n_values = [10, 25, 50]

sum_df = pd.DataFrame({
    'Top_N': top_n_values,
    'Sum_Alloc%': [df_tmp['CurrAlloc%'].head(n).sum() for n in top_n_values]
})

sum_df

   Top_N  Sum_Alloc%
0     10       20.03
1     25       44.31
2     50       75.13

In [25]:
# market-cap-wise allocation
df_tmp = df_portfolio_features[cols]
df_tmp.groupby(df_tmp['Conviction'].str[-2:])['CurrAlloc%'].sum().sort_values(ascending=False)

Conviction
SC    42.16
MC    29.15
LC    28.68
Name: CurrAlloc%, dtype: float64

In [26]:
# criteria-wise allocation
df_portfolio_features.groupby('Criteria')['CurrAlloc%'].sum().sort_values(ascending=False)

Criteria
XY24     26.88
X40      24.58
X40N     15.71
AR        9.21
XR        8.85
XY25      7.17
OX40N     6.81
SR        0.78
Name: CurrAlloc%, dtype: float64

In [27]:
# conviction-wise allocation
df_portfolio_features.groupby('Conviction')['CurrAlloc%'].sum().sort_values(ascending=False)

Conviction
X-LC    26.44
H-SC    21.81
X-MC    21.69
M-SC    10.01
X-SC     9.77
H-MC     4.99
M-MC     2.14
H-LC     1.27
M-LC     0.97
L-SC     0.57
L-MC     0.33
Name: CurrAlloc%, dtype: float64

In [28]:
# sector-wise stats
df_tmp = df_portfolio_features.groupby('Category')[['CurrAlloc%', 'Current', 'Current P/L', 'FTT Amt']].sum().sort_values(by=['Current', 'Current P/L'], ascending=False)
df_tmp['Current P/L%'] = round(df_tmp['Current P/L'] * 100 / df_tmp['Current'], 2)
df_tmp['FTT%'] = round(df_tmp['FTT Amt'] * 100 / df_tmp['Current'], 2)
cols = ['CurrAlloc%', 'Current P/L%', 'FTT%']
df_tmp[cols].sort_values(by=['CurrAlloc%'], ascending=False)

               CurrAlloc%  Current P/L%    FTT%
Category
FMCG                15.67        -14.14   54.47
IT                  11.08        -38.57  109.09
FINANCE             10.90        -15.27   65.41
MISC                 6.97        -31.38   88.45
ELECTRICAL           6.62          0.41   37.72
AUTO                 5.33        -13.16   57.79
PAINTS               5.31        -26.61   48.60
INSURANCE            5.23         -4.05   39.41
PHARMA               4.59         -5.32   39.13
BANKS                4.48        -17.28   76.80
AC                   2.03         -7.34   36.44
HEALTHCARE           1.88        -29.71   63.57
APPARELS             1.81         -1.07   35.54
FOOTWEAR             1.80        -67.68  134.91
TRAVEL               1.76        -73.92  161.00
DURABLES             1.75        -50.63   87.28
BREWERIES            1.61          0.89   19.69
REALTY               1.43         -6.07   23.50
CERAMICS             1.33        -57.84  105.80
CABLES               1.23         18.14   70.20
REFINERIES           1.19        -14.74   43.77
CEMENT               1.17        -56.48  173.55
ENGINEERING          1.15        -44.20  110.15
JEWELLERY            1.07       -103.50  174.20
CHEMICALS            1.05        -72.92  213.99
ENTERTAINMENT        0.76        -71.95  174.49
TEXTILES             0.44        -43.88   84.90
HOTELS               0.35       -118.96  196.19

In [29]:
# money to be made criteria-wise
df_portfolio_features.groupby('Criteria')['FTT Amt'].agg(['sum', 'count']).sort_values(by='sum', ascending=False)

                sum  count
Criteria
XY24      3659235.0     21
X40       1725694.0     17
XR        1331391.0     13
AR        1219734.0     10
X40N      1132067.0     12
OX40N      792623.0     10
XY25       387658.0      5
SR         305632.0      2

In [30]:
# money to be made conviction-wise
df_portfolio_features.groupby('Conviction')['FTT Amt'].agg(['sum', 'count']).sort_values(by='sum', ascending=False)

                  sum  count
Conviction
H-SC        3595274.0     24
X-LC        1709186.0     18
X-MC        1550616.0     15
M-SC        1450964.0     14
X-SC        1371743.0      9
H-MC         347367.0      3
L-SC         206532.0      2
M-LC         150110.0      1
M-MC          71961.0      2
L-MC          53669.0      1
H-LC          46612.0      1

In [31]:
# money to be made criteria and conviction-wise
df_portfolio_features.groupby(['Conviction', 'Criteria'])['FTT Amt'].agg(['sum', 'count']).sort_values(by='sum', ascending=False)

                           sum  count
Conviction Criteria
H-SC       XY24      1184702.0      6
           AR         945869.0      5
X-LC       X40        890792.0      8
M-SC       XY24       853543.0      6
H-SC       XR         816939.0      7
X-SC       XY24       810437.0      4
X-MC       X40        633327.0      7
           X40N       463582.0      4
X-SC       X40N       359731.0      3
M-SC       OX40N      345701.0      5
X-LC       XY24       344404.0      2
H-SC       OX40N      342132.0      4
X-LC       X40N       308754.0      5
H-SC       SR         305632.0      2
X-MC       XY24       234125.0      2
H-MC       XY24       232024.0      1
X-MC       XY25       219582.0      2
X-SC       X40        201575.0      2
M-SC       XR         177591.0      2
M-LC       XR         150110.0      1
X-LC       XY25       133896.0      2
H-MC       AR         115343.0      2
L-SC       OX40N      104790.0      1
           XR         101742.0      1
M-SC       AR          74129.0      1
L-MC       XR          53669.0      1
H-LC       AR          46612.0      1
M-MC       AR          37781.0      1
           XY25        34180.0      1
X-LC       XR          31340.0      1

In [32]:
# notebook execution time

end_time = time.time()
execution_time = round(end_time - start_time, 0)
print(f"Notebook execution time: {execution_time} seconds")

Notebook execution time: 25.0 seconds