<a href="https://colab.research.google.com/github/ankit-rathi/Quantvesting_v2/blob/main/myStocks_Portfolio_Analysis.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
'''
!pip install pandas==2.2.2 -qq
!pip install pyxirr -qq
!pip install ta -qq
!pip install yfinance==0.2.59 -qq
'''

'\n!pip install pandas==2.2.2 -qq\n!pip install pyxirr -qq\n!pip install ta -qq\n!pip install yfinance==0.2.59 -qq\n'

In [2]:
# import libraries

import numpy as np
import pandas as pd
import datetime
import warnings
warnings.filterwarnings('ignore')
import yfinance as yfin
import ta
import matplotlib.pyplot as plt
import requests

In [3]:
# notebook start time
import time
import datetime
import pytz

start_time = time.time()

# function to print date timestamp
def print_date_time():
  tz_NY = pytz.timezone('Asia/Kolkata')
  datetime_NY = datetime.datetime.now(tz_NY)
  print("Run date time (IST):", datetime_NY.strftime("%Y-%m-%d %H:%M:%S"))

In [4]:
# function to get booked and reserved amount
def get_amt():
  # fetch the JSON data from the URL
  url = "https://raw.githubusercontent.com/ankit-rathi/Tradevesting_v1/main/data/myPortfolioAmts.json"
  response = requests.get(url)
  pf_amts = response.json()  # parse the JSON data

  # extract values from the JSON
  py_booked_amt_dm = pf_amts["py_booked_amt_dm"]
  py_booked_amt_sv = pf_amts["py_booked_amt_sv"]
  cy_booked_amt_dm = pf_amts["cy_booked_amt_dm"]
  cy_booked_amt_sv = pf_amts["cy_booked_amt_sv"]
  reserve_amt_dm = pf_amts["reserve_amt_dm"]
  reserve_amt_sv = pf_amts["reserve_amt_sv"]

  # perform calculations
  py_booked_amt = py_booked_amt_dm + py_booked_amt_sv
  cy_booked_amt = cy_booked_amt_dm + cy_booked_amt_sv
  reserve_amt = reserve_amt_dm + reserve_amt_sv
  total_booked_amt = py_booked_amt + cy_booked_amt

  return total_booked_amt, reserve_amt, cy_booked_amt, py_booked_amt

gen_output = 0

In [5]:
# function to format the amount
def format_amt(number):
    abs_number = abs(number)

    if abs_number >= 1_00_00_000:  # Crores
        formatted_amt = f"{number / 1_00_00_000:.2f} C"
    elif abs_number >= 1_00_000:  # Lakhs
        formatted_amt = f"{number / 1_00_000:.2f} L"
    elif abs_number >= 1_000:  # Thousands
        formatted_amt = f"{number / 1_000:.2f} K"
    else:
        formatted_amt = f"{number:.2f}"

    return formatted_amt

# function to set start and end date
def get_start_end_date():
  start_date = (datetime.date.today() + datetime.timedelta(days=-365)).strftime('%Y-%m-%d')
  end_date = (datetime.date.today() + datetime.timedelta(days=1)).strftime('%Y-%m-%d')
  return start_date, end_date

# function to fetch my portfolio csv
def get_mypfs_df():
  mypfs_df = pd.read_csv('https://raw.githubusercontent.com/ankit-rathi/Tradevesting_v1/main/data/myPortfolioStocks.csv')
  return mypfs_df

# function to fetch my prospects csv
def get_mypps_df():
  mypps_df = pd.read_csv('https://raw.githubusercontent.com/ankit-rathi/Tradevesting_v1/main/data/myProspectsScrips.csv')
  return mypps_df

# function to fetch screener data
def get_myscreen_df():
  myscreen_df = pd.read_csv('https://raw.githubusercontent.com/ankit-rathi/Tradevesting_v1/main/data/myScreenerDB.csv')
  return myscreen_df

# function to fetch momentum data
def get_myinvmt_df():
  myinvmt_df = pd.read_csv('https://raw.githubusercontent.com/ankit-rathi/Tradevesting_v1/main/data/myInvestments.csv')
  return myinvmt_df

# function to get the stock ids
def get_stock_ids(df_pf):
  stock_n100 = df_pf['Symbol'].unique()

  exclude = ['CADILAHC','MMTC', 'MASFIN']

  stock_ids = df_pf[~df_pf['Symbol'].isin(exclude) ]['Symbol'].unique()

  #mypf = mypf[mypf.Forecast.notnull()]
  #stock_ids = mypf['Symbol'].unique()

  #stock_ids.sort()
  return stock_ids

# get features from screener data
def get_screener_features():
  myscreen_df = get_myscreen_df()
  cols = ['Symbol', 'EPS', 'MedPE', 'ROCE%', 'ROE%', 'CapType']
  return myscreen_df[cols]

# get relative strength
def get_relative_strength(stock_list):

    # Dictionary to store stock tickers and their corresponding percentage price change
    stock_changes = {}

    # Loop through each stock and fetch its price data
    for stock in stock_list:
        try:
            # Download the stock data for the given date range
            stock_data = yfin.Ticker(stock + '.NS').history(period='1mo', interval='1d')[map(str.title, ['open', 'close', 'low', 'high', 'volume'])]

            # Calculate the percentage change for the stock
            if len(stock_data) > 0:
                start_price = stock_data['Close'].iloc[0]
                end_price = stock_data['Close'].iloc[-1]
                percent_change = round(((end_price - start_price) / start_price) * 100, 2)
                stock_changes[stock] = percent_change
            else:
                stock_changes[stock] = np.nan  # If no data is available, set to NaN

        except Exception as e:
            print(f"Error fetching data for {stock}: {e}")
            stock_changes[stock] = np.nan

    # Create a DataFrame with stock tickers and their percentage changes
    df = pd.DataFrame(list(stock_changes.items()), columns=['Symbol', 'Percent_Change'])

    # Drop any stocks with missing data (NaN values)
    df = df.dropna()

    # Calculate the percentile rank based on percentage change
    df['RSP'] = round(df['Percent_Change'].rank(pct=True) * 100, 2)
    cols = ['Symbol', 'RSP']
    df = df[cols]
    # Sort by percentile rank (optional)
    df = df.sort_values(by='RSP', ascending=False).reset_index(drop=True)

    return df

In [6]:
# function to get stock technicals
def stock_prec_dev(stock_symbol):
    #stock_symbol = 'ULTRACEMCO.NS'
    short_window = 20
    mid_window = 50
    long_window = 200
    moving_avg = 'SMA'

    start = datetime.datetime(*map(int, start_date.split('-')))
    end = datetime.datetime(*map(int, end_date.split('-')))

    stock_df = yfin.Ticker(stock_symbol + '.NS').history(period='max', interval='1d')[map(str.title, ['open', 'close', 'low', 'high', 'volume'])]

    stock_df['Max'] = round(max(stock_df['Close']),2)
    stock_df = stock_df[(stock_df.index <= end_date) & (stock_df.index >= start_date)]
    stock_df['200_SMA'] = round(stock_df['Close'].rolling(window = 200, min_periods = 1).mean(),0)
    stock_df['Dev%_200'] = round((stock_df['Close'] - stock_df['200_SMA'])*100/stock_df['200_SMA'],2)
    stock_df.dropna(axis = 0, inplace = True) # remove any null rows

    stock_df['20_SMA'] = stock_df['Close'].rolling(window=20).mean()
    stock_df['50_SMA'] = stock_df['Close'].rolling(window=50).mean()
    stock_df['Symbol'] = stock_symbol

    stock_df['Close'] = round(stock_df['Close'],2)
    stock_df['Min'] = round(min(stock_df['Close']),2)
    stock_df['RSI_14'] = ta.momentum.RSIIndicator(close=stock_df['Close'], window=14).rsi()
    stock_df['RSI_14'] = round(stock_df['RSI_14'],0)
    stock_df['Prev_Close'] = stock_df['Close'].shift(1)
    stock_df.drop(['Open', 'Low', 'High', 'Volume'], axis=1, inplace=True)
    stock_df = stock_df.tail(1)

    max_SMA = max(stock_df['20_SMA'].item(), stock_df['50_SMA'].item(), stock_df['200_SMA'].item())
    min_SMA = min(stock_df['20_SMA'].item(), stock_df['50_SMA'].item(), stock_df['200_SMA'].item())
    ABS_Spread = max_SMA - min_SMA
    stock_df['Spread%'] = round((ABS_Spread / stock_df['200_SMA'].item()) * 100,2)

    return stock_df

# function to compute stock attributes
def get_common_features(stock_ids, df_mypf):

  df_prec_dev = pd.DataFrame()
  df_tmp = get_screener_features()
  df_rs = get_relative_strength(stock_ids)

  for stock_id in stock_ids:
      tmp = stock_prec_dev(stock_id)
      tmp = tmp.reset_index()
      df_prec_dev = pd.concat([df_prec_dev, tmp], ignore_index = True)
  df_prec_dev = pd.merge(df_prec_dev, df_mypf, on= 'Symbol')
  df_prec_dev = pd.merge(df_prec_dev, df_tmp, on= 'Symbol', how='left')
  df_prec_dev = pd.merge(df_prec_dev, df_rs, on= 'Symbol', how='left')
  #print(df_prec_dev.columns)
  df_prec_dev['Curr_PE'] = round(df_prec_dev['Close']/df_prec_dev['EPS'],1)
  df_prec_dev['Dev%_PE'] = round((df_prec_dev['Curr_PE'] - df_prec_dev['MedPE'])*100/df_prec_dev['MedPE'],2)
  df_prec_dev['Conviction'] = df_prec_dev['Conviction'] + '-' + df_prec_dev['CapType']
  return df_prec_dev

# function to arrange stock features
def arrange_features(df_stocks, common_cols, diff_cols):
  df_stocks_common = df_stocks[common_cols].drop_duplicates()
  df_stocks_diff = df_stocks[diff_cols]
  df_stocks_diff['Investment'] = df_stocks_diff['AvgCost'] * df_stocks_diff['Shares']
  df_stocks_diff = df_stocks_diff.groupby(['Symbol'])[['Shares', 'Investment']].aggregate(['sum']).reset_index()
  df_stocks_diff.columns = ['Symbol', 'Shares', 'Investment']
  df_stocks_diff['AvgCost'] = round(df_stocks_diff['Investment']/df_stocks_diff['Shares'],2)
  df_stocks = pd.merge(df_stocks_diff, df_stocks_common, on='Symbol')
  return df_stocks

# plot fact distribution across dimension
def plot_pie_chart(df, dimension, fact):
  # grouping the data by category and calculating the sum of fact for each type
  grouped_data = df.groupby(dimension)[fact].sum()

  # sorting the grouped data in descending order
  grouped_data = grouped_data.sort_values(ascending=False)

  # creating a pie chart
  grouped_data.plot.pie(autopct='%1.1f%%', startangle=90, figsize=(6, 6))

  # adding a title and displaying the plot
  plt.title(f'{dimension} {fact} Distribution')
  plt.ylabel('')  # To hide the y-label
  plt.show()

In [7]:
# function to get portfolio features

def get_portfolio_features(df_common_features):

  print_date_time()
  print('-------------------')

  #df_common_features["Target"] = df_common_features["Target"].fillna(df_common_features["Max"])
  df_common_features['NTT'] = np.where(df_common_features['Strategy']== 'NTT', df_common_features["Target"], df_common_features['Max'])
  df_common_features['LTT'] = np.where(df_common_features['Strategy']== 'BTT', df_common_features["Target"], df_common_features['Max'])
  df_common_features['BOL'] = df_common_features['Min']

  tmp_df = df_common_features[df_common_features['Symbol'].isin(mypf_df[mypf_df['InPortfolio'] != 'NA'].Symbol.values)]
  print('qualified stocks: '+str(len(tmp_df['Symbol'].unique())))
  tmp_df1 = tmp_df[tmp_df['LatestQtr'] == 1]
  print('with latest results: '+str(len(tmp_df1['Symbol'].unique())))
  tmp_df1 = tmp_df1[tmp_df1['StarStock'] == 1]
  print('still star stocks: '+str(len(tmp_df1['Symbol'].unique())))
  tmp_df['Investment'] = tmp_df['AvgCost'] * tmp_df['Shares']
  tmp_df['Current'] = round(tmp_df['Close'] * tmp_df['Shares'],0)
  tmp_df['Previous'] = tmp_df['Prev_Close'] * tmp_df['Shares']
  tmp_df['EstimatedST'] = tmp_df['NTT'] * tmp_df['Shares']
  tmp_df['EstimatedLT'] = tmp_df['LTT'] * tmp_df['Shares']
  tmp_df['Current P/L'] = round((tmp_df['Current'] - tmp_df['Investment']),0)
  tmp_df['Today P/L%'] = round((tmp_df['Current'] - tmp_df['Previous'])*100/tmp_df['Previous'],2)
  tmp_df['Current P/L%'] = round((tmp_df['Current'] - tmp_df['Investment'])*100/tmp_df['Investment'],2)
  tmp_df['EstimatedST P/L%'] = round((tmp_df['EstimatedST'] - tmp_df['Investment'])*100/tmp_df['Investment'],2)
  tmp_df['EstimatedLT P/L%'] = round((tmp_df['EstimatedLT'] - tmp_df['Investment'])*100/tmp_df['Investment'],2)
  tmp_df['NTT%'] = round((tmp_df['NTT'] - tmp_df['Close'])*100/tmp_df['Close'],2)
  tmp_df['LTT%'] = round((tmp_df['LTT'] - tmp_df['Close'])*100/tmp_df['Close'],2)
  tmp_df['Gained%'] = round((tmp_df['Close'] - tmp_df['BOL'])*100/tmp_df['BOL'],2)
  investment = round(sum(tmp_df['AvgCost']*tmp_df['Shares']),0)
  current = round(sum(tmp_df['Close']*tmp_df['Shares']),0)
  tmp_df['InitAlloc%'] = round(tmp_df['Investment']*100/investment,2)
  tmp_df['CurrAlloc%'] = round(tmp_df['Current']*100/current,2)
  tmp_df['FTT'] = tmp_df['LTT']
  tmp_df.loc[tmp_df['Strategy'] == 'NTT', 'FTT'] = tmp_df['NTT']
  tmp_df['FTT%'] = tmp_df['LTT%']
  tmp_df.loc[tmp_df['Strategy'] == 'NTT', 'FTT%'] = tmp_df['NTT%']
  tmp_df['FTT Amt'] = round(tmp_df['FTT%'] * tmp_df['Current']/100,0)
  tmp_df['OTT%'] = round((tmp_df['FTT'] - tmp_df['AvgCost'])*100/tmp_df['AvgCost'],2)
  tmp_df['RRR Ind'] = round(tmp_df['Current P/L']/tmp_df['FTT Amt'],2)
  tmp_df['Risk Ind'] = round(tmp_df['Current P/L%']*tmp_df['CurrAlloc%'],0)

  return tmp_df

# function to print portfolio features
def print_portfolio_stats(df_portfolio_features, myinvmt_df):
  from pyxirr import xirr

  total_booked_amt, reserve_amt, cy_booked_amt, py_booked_amt = get_amt()

  dates = myinvmt_df['Date'].values
  dates = np.append(dates, datetime.date.today().strftime('%d-%b-%y'))
  investment = myinvmt_df['Investment'].values
  dates= pd.to_datetime(dates)

  current = round(sum(df_portfolio_features['Close']*df_portfolio_features['Shares']),0) + reserve_amt
  investment_xirr = np.append(investment, current)
  cagr = round(xirr(pd.DataFrame({"dates": dates, "amounts": investment_xirr}))*100,2)

  investment = -sum(investment)
  invested = round(sum(df_portfolio_features['AvgCost']*df_portfolio_features['Shares']),0) + reserve_amt
  previous = round(sum(df_portfolio_features['Prev_Close']*df_portfolio_features['Shares']),0) + reserve_amt
  cy_invested = investment + py_booked_amt

  today_pnl_amount = current-previous
  today_pnl_percentage = round((current-previous)*100/previous,2)

  curr_pnl_amount = current-invested
  curr_pnl_percentage = round((curr_pnl_amount)*100/(cy_invested),2)

  cy_pnl_amount = cy_booked_amt + curr_pnl_amount
  cy_pnl_percentage = round((cy_pnl_amount)*100/cy_invested,2)

  overall_pnl_amount = total_booked_amt + curr_pnl_amount
  overall_pnl_percentage = round((overall_pnl_amount)*100/investment,2)

  estimate_st = round(sum(df_portfolio_features['FTT']*df_portfolio_features['Shares']),0)  + reserve_amt
  est_st_pnl_amount = estimate_st-current
  est_st_pnl_percentage = round((est_st_pnl_amount)*100/current,2)

  estimate_lt = round(sum(df_portfolio_features['LTT']*df_portfolio_features['Shares']),0)  + reserve_amt
  est_lt_pnl_amount = estimate_lt-current
  est_lt_pnl_percentage = round((est_lt_pnl_amount)*100/current,2)

  total_profit = round(sum(df_portfolio_features[df_portfolio_features['Current P/L%'] > 0]['Current']) - sum(df_portfolio_features[df_portfolio_features['Current P/L%'] > 0]['Investment']),0)
  total_loss = round(sum(df_portfolio_features[df_portfolio_features['Current P/L%'] < 0]['Current']) - sum(df_portfolio_features[df_portfolio_features['Current P/L%'] < 0]['Investment']),0)

  cy_booked_percentage = round((cy_booked_amt)*100/current,2)
  py_booked_percentage = round((py_booked_amt)*100/investment,2)
  total_booked_percentage = round((total_booked_amt)*100/investment,2)

  print('-------------------')
  print('Initial Investment: ', format_amt(investment))
  print('CY Investment: ', format_amt(cy_invested))
  print('Reserve: ', format_amt(reserve_amt))
  print('Current: ',  format_amt(current))
  print('-------------------')
  print('Today PnL: '+ '{} ({}%)'.format(format_amt(today_pnl_amount), today_pnl_percentage))
  print('Current PnL: '+ '{} ({}%)'.format(format_amt(curr_pnl_amount), curr_pnl_percentage))
  print('CY Booked + Current PnL: '+ '{} ({}%)'.format(format_amt(cy_pnl_amount), cy_pnl_percentage))
  print('-------------------')
  print('Total profit: ', format_amt(total_profit))
  print('Total loss: ', format_amt(total_loss))
  print('-------------------')
  print('Total Booked + Current PnL: '+ '{} ({}%)'.format(format_amt(overall_pnl_amount), overall_pnl_percentage))
  print('Total Booked PnL: '+ '{} ({}%)'.format(format_amt(total_booked_amt), total_booked_percentage))
  print('Curr Year Booked PnL: '+ '{} ({}%)'.format(format_amt(cy_booked_amt), cy_booked_percentage))
  print('Prev Year Booked PnL: '+ '{} ({}%)'.format(format_amt(py_booked_amt), py_booked_percentage))
  print('===================')
  print('Est FTT: ',  format_amt(estimate_st))
  print('Est FTT PnL: '+ '{} ({}%)'.format(format_amt(est_st_pnl_amount), est_st_pnl_percentage))

  print('===================')
  print('Deployed: ', format_amt(investment))

  print('Current: ', format_amt(current))

  print('CAGR/XIRR %: '+'{}%'.format(cagr))

In [8]:
# get start and end date
start_date, end_date = get_start_end_date()

# get portfolio and prospects data
mypfs_df = get_mypfs_df()
mypps_df = get_mypps_df()
myinvmt_df = get_myinvmt_df()

# merge above datasets
mypf_df = pd.merge(mypfs_df, mypps_df, on="Symbol")

# seggregate dm and sv portfolio
dm_pf = mypf_df[mypf_df['InPortfolio'] == 'DM']
sv_pf = mypf_df[mypf_df['InPortfolio'] == 'SV']

# build portfolio stock dataframe
dm_stocks = get_stock_ids(dm_pf)
sv_stocks = get_stock_ids(sv_pf)
df_stocks = pd.concat([dm_pf,sv_pf], ignore_index = True)

# arrange common and diff stock features
common_cols = ['Symbol', 'Target', 'Criteria', 'Strategy', 'CumlRnk', 'LatestQtr', 'StarStock', 'Conviction', 'Category', 'InFolio', 'XIRR', 'MBQ']
diff_cols = ['Symbol', 'AvgCost', 'Shares']
df_stocks = arrange_features(df_stocks, common_cols, diff_cols)

# get common features
stock_ids = df_stocks['Symbol'].values
df_common_features = get_common_features(stock_ids, df_stocks)

df_common_features.reset_index(drop=True, inplace=True)
df_common_features.drop(['Date'], axis=1, inplace=True)
# get and print portfolio features
df_portfolio_features = get_portfolio_features(df_common_features)

print_portfolio_stats(df_portfolio_features, myinvmt_df)

df = df_portfolio_features
#plot_pie_chart(df, 'CapType', 'Current')
list_ox40n = list(df[df['MBQ'].str.contains('OX40N', na=False)]['Symbol'].values)

Run date time (IST): 2026-08-18 11:47:01
-------------------
qualified stocks: 87
with latest results: 30
still star stocks: 19
-------------------
Initial Investment:  1.46 C
CY Investment:  1.89 C
Reserve:  3.69 L
Current:  1.58 C
-------------------
Today PnL: -1.12 L (-0.7%)
Current PnL: -34.82 L (-18.43%)
CY Booked + Current PnL: -29.76 L (-15.75%)
-------------------
Total profit:  3.35 L
Total loss:  -38.17 L
-------------------
Total Booked + Current PnL: 13.11 L (8.98%)
Total Booked PnL: 47.93 L (32.82%)
Curr Year Booked PnL: 5.06 L (3.2%)
Prev Year Booked PnL: 42.87 L (29.35%)
===================
Est FTT:  2.67 C
Est FTT PnL: 1.09 C (68.93%)
===================
Deployed:  1.46 C
Current:  1.58 C
CAGR/XIRR %: 3.6%

In [9]:
# top 5 near their targets
cols = ['Symbol', 'Today P/L%', 'Current P/L%', 'FTT%', 'OTT%', 'FTT Amt', 'Current P/L', 'Current', 'FTT', 'Dev%_PE', 'RSI_14','Conviction', 'Spread%',  'CumlRnk', 'RRR Ind', 'CurrAlloc%', 'Gained%', 'Criteria', 'Strategy', 'Category']
df_tmp = df_portfolio_features[~df_portfolio_features['Symbol'].isin(['ENRIN','BLUSPRING','DIGITIDE'])]
df_tmp = df_tmp.sort_values(by = 'FTT Amt', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
66,SIEMENS,0.05,5.99,4.56,10.83,8995.0,11155.0,197250.0,4125.00,-14.10,63.0,H-LC,13.58,51.0,1.24,1.28,39.17,AR,NTT,ELECTRICAL
78,UNITDSPR,-0.41,13.02,6.85,20.77,18128.0,30495.0,264639.0,1644.00,-3.65,64.0,X-MC,10.97,64.0,1.68,1.71,27.21,X40N,NTT,BREWERIES
77,TTKPRESTIG,0.04,-23.00,29.99,0.09,23272.0,-23179.0,77598.0,770.00,-6.23,41.0,M-SC,10.20,250.0,-1.00,0.50,39.67,OX40N,NTT,DURABLES
52,M&M,1.10,8.24,9.78,18.82,25477.0,19824.0,260505.0,3762.88,-6.55,59.0,X-LC,4.80,25.0,0.78,1.69,18.17,X40N,ATH,AUTO
67,SIS,0.82,-3.58,25.76,21.26,27579.0,-3970.0,107062.0,528.00,105.79,42.0,H-SC,21.64,168.0,-0.14,0.69,59.18,OX40N,NTT,MISC

In [10]:
# top 5 today
df_tmp = df_portfolio_features.sort_values(by = 'Today P/L%', ascending=False)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
0,5PAISA,2.94,-24.78,50.09,12.90,82329.0,-54134.0,164362.0,593.00,5.46,63.0,H-SC,11.12,170.0,-0.66,1.06,58.61,OX40N,NTT,FINANCE
12,BOSCH-HCIL,2.89,-25.42,34.08,-0.01,32482.0,-32493.0,95312.0,2282.00,743.28,75.0,M-SC,5.98,231.0,-1.00,0.62,62.23,OX40N,BTT,AC
18,COFFEEDAY,2.53,-50.03,170.73,35.27,96865.0,-56813.0,56736.0,80.00,NaN,40.0,NaN,4.03,266.0,-0.59,0.37,39.91,XR,NTT,HOTELS
82,VBL,1.19,-11.04,52.49,35.66,164297.0,-38837.0,313007.0,669.42,-27.16,40.0,X-LC,7.13,13.0,-0.24,2.03,15.24,X40N,ATH,FMCG
22,DIXON,1.17,3.37,33.43,37.92,90124.0,8793.0,269591.0,18931.72,-60.71,58.0,X-MC,15.10,54.0,0.10,1.75,46.69,X40N,ATH,IT

In [11]:
# bottom 5 today
df_tmp = df_portfolio_features.sort_values(by = 'Today P/L%', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
29,GREENPANEL,-4.84,-55.73,223.32,43.14,181005.0,-102026.0,81052.0,537.00,NaN,28.0,NaN,10.95,225.0,-0.56,0.52,0.00,XY24,NTT,MISC
33,HCLTECH,-4.52,-13.15,42.74,23.97,114881.0,-40696.0,268790.0,1853.42,-15.52,51.0,X-LC,11.99,8.0,-0.35,1.74,26.84,X40,ATH,IT
81,VALIANTORG,-4.45,-35.57,170.28,74.15,179504.0,-58188.0,105417.0,838.00,NaN,59.0,NaN,6.31,145.0,-0.32,0.68,56.88,XR,NTT,CHEMICALS
71,TANLA,-4.20,-36.98,244.75,117.25,417607.0,-100135.0,170626.0,1922.32,NaN,42.0,NaN,15.34,147.0,-0.24,1.10,49.39,AR,ATH,IT
60,RELAXO,-3.90,-50.68,208.82,52.31,149494.0,-73570.0,71590.0,1176.00,NaN,40.0,NaN,12.48,92.0,-0.49,0.46,60.07,X40N,NTT,FOOTWEAR

In [12]:
# top 5 to exit based on CumlRnk
df_tmp = df_portfolio_features[~df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])]
df_tmp = df_tmp[(df_tmp['Current P/L%'] > -1) & (df_tmp['Current P/L%'] < 1)].sort_values(by = 'CumlRnk', ascending=False)
df_tmp[cols].head()

Empty DataFrame
Columns: [Symbol, Today P/L%, Current P/L%, FTT%, OTT%, FTT Amt, Current P/L, Current, FTT, Dev%_PE, RSI_14, Conviction, Spread%, CumlRnk, RRR Ind, CurrAlloc%, Gained%, Criteria, Strategy, Category]
Index: []

In [13]:
# OX40N stocks to exit
df_tmp = df_portfolio_features[(df_portfolio_features['Symbol'].isin(list_ox40n))].sort_values(by = 'Current P/L%', ascending=False)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
25,FINCABLES,-0.37,66.68,24.74,107.91,60883.0,98448.0,246092.0,1641.55,21.68,75.0,M-SC,19.21,220.0,1.62,1.59,85.14,OX40N,ATH,CABLES
67,SIS,0.82,-3.58,25.76,21.26,27579.0,-3970.0,107062.0,528.00,105.79,42.0,H-SC,21.64,168.0,-0.14,0.69,59.18,OX40N,NTT,MISC
43,INDIGOPNTS,0.40,-18.07,22.08,0.02,31576.0,-31550.0,143009.0,1408.00,-21.90,67.0,M-SC,6.63,222.0,-1.00,0.93,62.25,OX40N,NTT,PAINTS
77,TTKPRESTIG,0.04,-23.00,29.99,0.09,23272.0,-23179.0,77598.0,770.00,-6.23,41.0,M-SC,10.20,250.0,-1.00,0.50,39.67,OX40N,NTT,DURABLES
0,5PAISA,2.94,-24.78,50.09,12.90,82329.0,-54134.0,164362.0,593.00,5.46,63.0,H-SC,11.12,170.0,-0.66,1.06,58.61,OX40N,NTT,FINANCE

In [14]:
# top 5 to book for rotation
df_tmp = df_portfolio_features[(df_portfolio_features['Current P/L%'] > 20) ].sort_values(by = 'CumlRnk', ascending=False)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
25,FINCABLES,-0.37,66.68,24.74,107.91,60883.0,98448.0,246092.0,1641.55,21.68,75.0,M-SC,19.21,220.0,1.62,1.59,85.14,OX40N,ATH,CABLES

In [15]:
# top 5 to monitor for exit
df_tmp = df_portfolio_features[~df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])]
df_tmp = df_tmp[(df_tmp['Current P/L%'] > 0) ].sort_values(by = 'Dev%_PE', ascending=False)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
25,FINCABLES,-0.37,66.68,24.74,107.91,60883.0,98448.0,246092.0,1641.55,21.68,75.0,M-SC,19.21,220.0,1.62,1.59,85.14,OX40N,ATH,CABLES
68,STARHEALTH,-0.64,12.51,30.89,47.26,97700.0,35159.0,316282.0,761.00,-0.86,49.0,H-SC,16.49,173.0,0.36,2.05,36.75,XY24,NTT,INSURANCE

In [16]:
# top 5 to book for rotation from weak conviction
df_tmp = df_portfolio_features[~df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])]
df_tmp = df_tmp[~df_tmp['Criteria'].isin(['XY25','XY24','X40', 'X40N'])].sort_values(by = 'RRR Ind', ascending=False)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
25,FINCABLES,-0.37,66.68,24.74,107.91,60883.0,98448.0,246092.0,1641.55,21.68,75.0,M-SC,19.21,220.0,1.62,1.59,85.14,OX40N,ATH,CABLES
67,SIS,0.82,-3.58,25.76,21.26,27579.0,-3970.0,107062.0,528.00,105.79,42.0,H-SC,21.64,168.0,-0.14,0.69,59.18,OX40N,NTT,MISC
3,ALKYLAMINE,-0.38,-18.67,136.74,92.54,112281.0,-18850.0,82113.0,4520.85,NaN,56.0,NaN,14.03,142.0,-0.17,0.53,55.93,SR,ATH,CHEMICALS
42,INDIAMART,-2.17,-24.76,167.02,100.92,155000.0,-30533.0,92803.0,4675.60,NaN,37.0,NaN,13.42,140.0,-0.20,0.60,0.46,AR,ATH,MISC
71,TANLA,-4.20,-36.98,244.75,117.25,417607.0,-100135.0,170626.0,1922.32,NaN,42.0,NaN,15.34,147.0,-0.24,1.10,49.39,AR,ATH,IT

In [17]:
# top 5 to accumulate based on lowest RSI_14
df_tmp = df_portfolio_features[df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])].sort_values(by = 'RSI_14', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
55,PAGEIND,-0.44,-4.56,39.98,33.59,102401.0,-12249.0,256130.0,51217.29,-29.08,30.0,X-MC,8.64,55.0,-0.12,1.66,21.64,X40,ATH,APPARELS
28,GODREJCP,-0.71,-15.61,57.48,32.90,121046.0,-38949.0,210588.0,1460.97,-17.22,31.0,X-MC,5.72,32.0,-0.32,1.36,2.51,X40N,ATH,FMCG
19,COLPAL,-3.43,-27.36,92.54,39.86,177038.0,-72055.0,191310.0,3683.41,-12.03,31.0,X-MC,1.61,62.0,-0.41,1.24,8.22,XY25,ATH,FMCG
56,PGHH,-1.04,-37.52,111.27,32.01,148452.0,-80104.0,133416.0,17616.87,-54.11,31.0,X-SC,19.62,57.0,-0.54,0.86,0.00,X40,ATH,FMCG
47,ITC,-0.57,-25.10,66.48,24.70,197821.0,-99714.0,297564.0,452.00,-30.35,33.0,X-LC,10.72,1.0,-0.50,1.93,0.00,X40,NTT,FMCG

In [18]:
# top 5 to accumulate based on Spread and CumlRnk
df_tmp = df_portfolio_features[df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])]
df_tmp = df_tmp[(df_tmp['CumlRnk'] < 100)].sort_values(by = 'Spread%', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
19,COLPAL,-3.43,-27.36,92.54,39.86,177038.0,-72055.0,191310.0,3683.41,-12.03,31.0,X-MC,1.61,62.0,-0.41,1.24,8.22,XY25,ATH,FMCG
23,DMART,0.25,-2.38,34.62,31.42,105376.0,-7410.0,304380.0,5391.45,-18.14,49.0,X-LC,2.30,14.0,-0.07,1.97,9.84,X40N,ATH,FMCG
50,KOTAKBANK,-0.20,3.00,15.45,18.92,38146.0,7195.0,246897.0,452.46,-12.85,52.0,X-LC,2.61,12.0,0.19,1.60,11.09,X40,ATH,BANKS
26,GILLETTE,-0.52,-11.03,45.80,29.72,103462.0,-27996.0,225900.0,10978.86,-35.84,38.0,X-SC,3.53,83.0,-0.27,1.46,3.81,X40,ATH,FMCG
11,BERGEPAINT,0.27,0.95,24.13,25.32,62787.0,2456.0,260205.0,680.00,-12.25,61.0,X-MC,4.11,68.0,0.04,1.68,36.45,XY24,NTT,PAINTS

In [19]:
# top 5 to accumulate based on lowest Gained%
df_tmp = df_portfolio_features[df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])].sort_values(by = 'Gained%', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
20,DABUR,-0.90,-21.18,82.31,43.70,160939.0,-52540.0,195528.0,735.00,-31.92,35.0,X-MC,9.88,70.0,-0.33,1.27,0.00,XY24,BTT,FMCG
47,ITC,-0.57,-25.10,66.48,24.70,197821.0,-99714.0,297564.0,452.00,-30.35,33.0,X-LC,10.72,1.0,-0.50,1.93,0.00,X40,NTT,FMCG
56,PGHH,-1.04,-37.52,111.27,32.01,148452.0,-80104.0,133416.0,17616.87,-54.11,31.0,X-SC,19.62,57.0,-0.54,0.86,0.00,X40,ATH,FMCG
34,HDFCBANK,-0.56,-11.46,48.02,31.05,124619.0,-33606.0,259514.0,1073.00,-28.50,34.0,X-LC,12.72,26.0,-0.27,1.68,0.73,X40,BTT,BANKS
35,HDFCLIFE,-0.56,-7.40,50.28,39.15,116740.0,-18558.0,232179.0,811.41,-31.88,42.0,X-LC,16.48,31.0,-0.16,1.50,0.77,X40,ATH,INSURANCE

In [20]:
# top 5 to accumulate based on lowest CurrAlloc%
df_tmp = df_portfolio_features[df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])].sort_values(by = 'CurrAlloc%', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
56,PGHH,-1.04,-37.52,111.27,32.01,148452.0,-80104.0,133416.0,17616.87,-54.11,31.0,X-SC,19.62,57.0,-0.54,0.86,0.00,X40,ATH,FMCG
2,ACC,-0.27,-41.24,197.49,74.81,311165.0,-110568.0,157560.0,3906.00,-41.79,38.0,X-SC,11.34,85.0,-0.36,1.02,5.26,XY24,BTT,CEMENT
1,ABBOTINDIA,-2.00,-11.03,29.68,15.37,47227.0,-19735.0,159120.0,34390.26,-27.58,38.0,X-MC,4.39,58.0,-0.42,1.03,7.79,X40,ATH,PHARMA
40,ICICIPRULI,-1.27,-16.81,56.61,30.28,92772.0,-33125.0,163880.0,787.27,-46.69,48.0,X-MC,12.81,78.0,-0.36,1.06,9.19,X40,ATH,INSURANCE
39,ICICIGI,-0.42,-14.22,38.60,18.89,66259.0,-28453.0,171656.0,2244.41,-14.59,40.0,X-MC,10.53,66.0,-0.43,1.11,2.27,X40,ATH,INSURANCE

In [21]:
# top 5 to accumulate based on CumlRnk
df_tmp = df_portfolio_features.sort_values(by = 'CumlRnk', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
47,ITC,-0.57,-25.10,66.48,24.70,197821.0,-99714.0,297564.0,452.00,-30.35,33.0,X-LC,10.72,1.0,-0.50,1.93,0.00,X40,NTT,FMCG
73,TCS,-1.18,-32.89,85.08,24.20,264498.0,-152391.0,310882.0,4230.71,-44.31,47.0,X-LC,14.31,2.0,-0.58,2.01,15.93,X40,ATH,IT
45,INFY,-2.15,-20.60,76.80,40.38,229576.0,-77543.0,298927.0,1972.00,-41.63,46.0,X-LC,15.93,3.0,-0.34,1.94,13.20,X40,NTT,IT
75,TMPV,-1.85,-22.89,85.13,42.75,273147.0,-95248.0,320859.0,600.00,-84.91,37.0,X-LC,4.61,4.0,-0.35,2.08,10.33,XY24,NTT,AUTO
33,HCLTECH,-4.52,-13.15,42.74,23.97,114881.0,-40696.0,268790.0,1853.42,-15.52,51.0,X-LC,11.99,8.0,-0.35,1.74,26.84,X40,ATH,IT

In [22]:
# top 5 for average up
df_tmp = df_portfolio_features[(df_portfolio_features['Dev%_200'] > 5)].sort_values(by = 'CurrAlloc%', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
44,INDUSINDBK,-1.34,-25.36,78.04,32.89,44972.0,-19580.0,57627.0,1800.00,324.50,52.0,L-MC,13.50,258.0,-0.44,0.37,42.07,XR,NTT,BANKS
3,ALKYLAMINE,-0.38,-18.67,136.74,92.54,112281.0,-18850.0,82113.0,4520.85,NaN,56.0,NaN,14.03,142.0,-0.17,0.53,55.93,SR,ATH,CHEMICALS
12,BOSCH-HCIL,2.89,-25.42,34.08,-0.01,32482.0,-32493.0,95312.0,2282.00,743.28,75.0,M-SC,5.98,231.0,-1.00,0.62,62.23,OX40N,BTT,AC
81,VALIANTORG,-4.45,-35.57,170.28,74.15,179504.0,-58188.0,105417.0,838.00,NaN,59.0,NaN,6.31,145.0,-0.32,0.68,56.88,XR,NTT,CHEMICALS
67,SIS,0.82,-3.58,25.76,21.26,27579.0,-3970.0,107062.0,528.00,105.79,42.0,H-SC,21.64,168.0,-0.14,0.69,59.18,OX40N,NTT,MISC

In [23]:
# top 5 RSP
df_tmp = df_portfolio_features.sort_values(by = 'RSP', ascending=False)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
25,FINCABLES,-0.37,66.68,24.74,107.91,60883.0,98448.0,246092.0,1641.55,21.68,75.0,M-SC,19.21,220.0,1.62,1.59,85.14,OX40N,ATH,CABLES
12,BOSCH-HCIL,2.89,-25.42,34.08,-0.01,32482.0,-32493.0,95312.0,2282.00,743.28,75.0,M-SC,5.98,231.0,-1.00,0.62,62.23,OX40N,BTT,AC
81,VALIANTORG,-4.45,-35.57,170.28,74.15,179504.0,-58188.0,105417.0,838.00,NaN,59.0,NaN,6.31,145.0,-0.32,0.68,56.88,XR,NTT,CHEMICALS
38,HYUNDAI,0.84,14.23,26.00,43.94,74647.0,35773.0,287105.0,2782.73,18.18,65.0,X-LC,5.00,29.0,0.48,1.86,31.82,X40N,ATH,AUTO
30,HAPPSTMNDS,-1.79,-47.67,249.88,83.08,167580.0,-61101.0,67064.0,1466.54,NaN,65.0,NaN,8.96,152.0,-0.36,0.43,25.61,AR,ATH,IT

In [24]:
# Top N allocation
df_tmp = df_portfolio_features.sort_values(by = 'CurrAlloc%', ascending=False)
top_n_values = [10, 25, 50]

sum_df = pd.DataFrame({
    'Top_N': top_n_values,
    'Sum_Alloc%': [df_tmp['CurrAlloc%'].head(n).sum() for n in top_n_values]
})

sum_df

   Top_N  Sum_Alloc%
0     10       19.78
1     25       45.19
2     50       77.57

In [25]:
# market-cap-wise allocation
df_tmp = df_portfolio_features[cols]
df_tmp.groupby(df_tmp['Conviction'].str[-2:])['CurrAlloc%'].sum().sort_values(ascending=False)

Conviction
LC    38.15
MC    22.20
SC    21.61
Name: CurrAlloc%, dtype: float64

In [26]:
# criteria-wise allocation
df_portfolio_features.groupby('Criteria')['CurrAlloc%'].sum().sort_values(ascending=False)

Criteria
X40      26.57
XY24     24.00
X40N     18.66
XR        9.12
OX40N     7.36
XY25      7.27
AR        6.12
SR        0.86
Name: CurrAlloc%, dtype: float64

In [27]:
# conviction-wise allocation
df_portfolio_features.groupby('Conviction')['CurrAlloc%'].sum().sort_values(ascending=False)

Conviction
X-LC    34.44
X-MC    19.58
H-SC     8.50
X-SC     7.65
M-SC     5.46
H-LC     2.90
M-MC     1.21
H-MC     1.04
M-LC     0.81
L-MC     0.37
Name: CurrAlloc%, dtype: float64

In [28]:
# sector-wise stats
df_tmp = df_portfolio_features.groupby('Category')[['CurrAlloc%', 'Current', 'Current P/L', 'FTT Amt']].sum().sort_values(by=['Current', 'Current P/L'], ascending=False)
df_tmp['Current P/L%'] = round(df_tmp['Current P/L'] * 100 / df_tmp['Current'], 2)
df_tmp['FTT%'] = round(df_tmp['FTT Amt'] * 100 / df_tmp['Current'], 2)
cols = ['CurrAlloc%', 'Current P/L%', 'FTT%']
df_tmp[cols].sort_values(by=['CurrAlloc%'], ascending=False)

               CurrAlloc%  Current P/L%    FTT%
Category
FMCG                15.49        -24.66   69.48
IT                  11.06        -39.46  108.63
FINANCE             10.74        -16.15   66.18
AUTO                 8.32         -5.32   43.04
BANKS                6.13        -12.62   61.19
MISC                 5.96        -33.89   87.75
PHARMA               5.76          6.88   19.54
INSURANCE            5.72         -5.09   42.25
PAINTS               5.54        -15.24   34.89
ELECTRICAL           4.21         -8.69   42.72
AC                   1.84        -12.92   43.54
REFINERIES           1.75        -10.52   47.64
BREWERIES            1.71         11.52    6.85
FOOTWEAR             1.67        -70.65  139.08
APPARELS             1.66         -4.78   39.98
CABLES               1.59         40.00   24.74
DURABLES             1.50        -67.70  108.50
TRAVEL               1.43       -101.63  202.59
CERAMICS             1.33        -48.97   94.22
CHEMICALS            1.21        -41.08  155.59
ENGINEERING          1.21        -29.68   89.00
CEMENT               1.02        -70.18  197.49
JEWELLERY            0.96       -116.72  192.02
ENTERTAINMENT        0.69        -80.46  188.09
HEALTHCARE           0.69        -70.73  113.59
TEXTILES             0.40        -50.91   93.94
HOTELS               0.37       -100.14  170.73

In [29]:
# money to be made criteria-wise
df_portfolio_features.groupby('Criteria')['FTT Amt'].agg(['sum', 'count']).sort_values(by='sum', ascending=False)

                sum  count
Criteria
XY24      3618021.0     19
X40       2120044.0     18
XR        1389005.0     13
X40N      1197837.0     12
AR        1059947.0      8
OX40N      653834.0     10
XY25       578055.0      5
SR         282597.0      2

In [30]:
# money to be made conviction-wise
df_portfolio_features.groupby('Conviction')['FTT Amt'].agg(['sum', 'count']).sort_values(by='sum', ascending=False)

                  sum  count
Conviction
X-LC        2409839.0     19
X-MC        1479889.0     14
X-SC        1095690.0      6
H-SC         835766.0      8
M-SC         321751.0      6
H-MC         252342.0      1
M-LC         167341.0      1
M-MC          58076.0      1
L-MC          44972.0      1
H-LC          42862.0      2

In [31]:
# money to be made criteria and conviction-wise
df_portfolio_features.groupby(['Conviction', 'Criteria'])['FTT Amt'].agg(['sum', 'count']).sort_values(by='sum', ascending=False)

                           sum  count
Conviction Criteria
X-LC       X40       1234873.0      9
X-SC       XY24       671045.0      2
H-SC       XY24       528197.0      3
X-MC       X40        521658.0      6
           X40N       466742.0      4
X-LC       XY24       453955.0      2
           X40N       408870.0      5
X-MC       XY25       267763.0      2
H-MC       XY24       252342.0      1
X-LC       XY25       252216.0      2
X-SC       X40        251914.0      2
X-MC       XY24       223726.0      2
H-SC       OX40N      213896.0      3
X-SC       X40N       172731.0      2
M-LC       XR         167341.0      1
M-SC       OX40N      148213.0      4
           XY24       116111.0      1
H-SC       XR          93673.0      2
X-LC       XR          59925.0      1
M-MC       XY25        58076.0      1
M-SC       XR          57427.0      1
L-MC       XR          44972.0      1
H-LC       AR          42862.0      2

In [32]:
# notebook execution time

end_time = time.time()
execution_time = round(end_time - start_time, 0)
print(f"Notebook execution time: {execution_time} seconds")

Notebook execution time: 52.0 seconds