<a href="https://colab.research.google.com/github/ankit-rathi/Quantvesting_v2/blob/main/myStocks_Portfolio_Analysis.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
'''
!pip install pandas==2.2.2 -qq
!pip install pyxirr -qq
!pip install ta -qq
!pip install yfinance==0.2.59 -qq
'''

'\n!pip install pandas==2.2.2 -qq\n!pip install pyxirr -qq\n!pip install ta -qq\n!pip install yfinance==0.2.59 -qq\n'

In [2]:
# import libraries

import numpy as np
import pandas as pd
import datetime
import warnings
warnings.filterwarnings('ignore')
import yfinance as yfin
import ta
import matplotlib.pyplot as plt
import requests

In [3]:
# notebook start time
import time
import datetime
import pytz

start_time = time.time()

# function to print date timestamp
def print_date_time():
  tz_NY = pytz.timezone('Asia/Kolkata')
  datetime_NY = datetime.datetime.now(tz_NY)
  print("Run date time (IST):", datetime_NY.strftime("%Y-%m-%d %H:%M:%S"))

In [4]:
# function to get booked and reserved amount
def get_amt():
  # fetch the JSON data from the URL
  url = "https://raw.githubusercontent.com/ankit-rathi/Tradevesting_v1/main/data/myPortfolioAmts.json"
  response = requests.get(url)
  pf_amts = response.json()  # parse the JSON data

  # extract values from the JSON
  py_booked_amt_dm = pf_amts["py_booked_amt_dm"]
  py_booked_amt_sv = pf_amts["py_booked_amt_sv"]
  cy_booked_amt_dm = pf_amts["cy_booked_amt_dm"]
  cy_booked_amt_sv = pf_amts["cy_booked_amt_sv"]
  reserve_amt_dm = pf_amts["reserve_amt_dm"]
  reserve_amt_sv = pf_amts["reserve_amt_sv"]

  # perform calculations
  py_booked_amt = py_booked_amt_dm + py_booked_amt_sv
  cy_booked_amt = cy_booked_amt_dm + cy_booked_amt_sv
  reserve_amt = reserve_amt_dm + reserve_amt_sv
  total_booked_amt = py_booked_amt + cy_booked_amt

  return total_booked_amt, reserve_amt, cy_booked_amt, py_booked_amt

gen_output = 0

In [5]:
# function to format the amount
def format_amt(number):
    abs_number = abs(number)

    if abs_number >= 1_00_00_000:  # Crores
        formatted_amt = f"{number / 1_00_00_000:.2f} C"
    elif abs_number >= 1_00_000:  # Lakhs
        formatted_amt = f"{number / 1_00_000:.2f} L"
    elif abs_number >= 1_000:  # Thousands
        formatted_amt = f"{number / 1_000:.2f} K"
    else:
        formatted_amt = f"{number:.2f}"

    return formatted_amt

# function to set start and end date
def get_start_end_date():
  start_date = (datetime.date.today() + datetime.timedelta(days=-365)).strftime('%Y-%m-%d')
  end_date = (datetime.date.today() + datetime.timedelta(days=1)).strftime('%Y-%m-%d')
  return start_date, end_date

# function to fetch my portfolio csv
def get_mypfs_df():
  mypfs_df = pd.read_csv('https://raw.githubusercontent.com/ankit-rathi/Tradevesting_v1/main/data/myPortfolioStocks.csv')
  return mypfs_df

# function to fetch my prospects csv
def get_mypps_df():
  mypps_df = pd.read_csv('https://raw.githubusercontent.com/ankit-rathi/Tradevesting_v1/main/data/myProspectsScrips.csv')
  return mypps_df

# function to fetch screener data
def get_myscreen_df():
  myscreen_df = pd.read_csv('https://raw.githubusercontent.com/ankit-rathi/Tradevesting_v1/main/data/myScreenerDB.csv')
  return myscreen_df

# function to fetch momentum data
def get_myinvmt_df():
  myinvmt_df = pd.read_csv('https://raw.githubusercontent.com/ankit-rathi/Tradevesting_v1/main/data/myInvestments.csv')
  return myinvmt_df

# function to get the stock ids
def get_stock_ids(df_pf):
  stock_n100 = df_pf['Symbol'].unique()

  exclude = ['CADILAHC','MMTC', 'MASFIN']

  stock_ids = df_pf[~df_pf['Symbol'].isin(exclude) ]['Symbol'].unique()

  #mypf = mypf[mypf.Forecast.notnull()]
  #stock_ids = mypf['Symbol'].unique()

  #stock_ids.sort()
  return stock_ids

# get features from screener data
def get_screener_features():
  myscreen_df = get_myscreen_df()
  cols = ['Symbol', 'EPS', 'MedPE', 'ROCE%', 'ROE%', 'CapType']
  return myscreen_df[cols]

# get relative strength
def get_relative_strength(stock_list):

    # Dictionary to store stock tickers and their corresponding percentage price change
    stock_changes = {}

    # Loop through each stock and fetch its price data
    for stock in stock_list:
        try:
            # Download the stock data for the given date range
            stock_data = yfin.Ticker(stock + '.NS').history(period='1mo', interval='1d')[map(str.title, ['open', 'close', 'low', 'high', 'volume'])]

            # Calculate the percentage change for the stock
            if len(stock_data) > 0:
                start_price = stock_data['Close'].iloc[0]
                end_price = stock_data['Close'].iloc[-1]
                percent_change = round(((end_price - start_price) / start_price) * 100, 2)
                stock_changes[stock] = percent_change
            else:
                stock_changes[stock] = np.nan  # If no data is available, set to NaN

        except Exception as e:
            print(f"Error fetching data for {stock}: {e}")
            stock_changes[stock] = np.nan

    # Create a DataFrame with stock tickers and their percentage changes
    df = pd.DataFrame(list(stock_changes.items()), columns=['Symbol', 'Percent_Change'])

    # Drop any stocks with missing data (NaN values)
    df = df.dropna()

    # Calculate the percentile rank based on percentage change
    df['RSP'] = round(df['Percent_Change'].rank(pct=True) * 100, 2)
    cols = ['Symbol', 'RSP']
    df = df[cols]
    # Sort by percentile rank (optional)
    df = df.sort_values(by='RSP', ascending=False).reset_index(drop=True)

    return df

In [6]:
# function to get stock technicals
def stock_prec_dev(stock_symbol):
    #stock_symbol = 'ULTRACEMCO.NS'
    short_window = 20
    mid_window = 50
    long_window = 200
    moving_avg = 'SMA'

    start = datetime.datetime(*map(int, start_date.split('-')))
    end = datetime.datetime(*map(int, end_date.split('-')))

    stock_df = yfin.Ticker(stock_symbol + '.NS').history(period='max', interval='1d')[map(str.title, ['open', 'close', 'low', 'high', 'volume'])]

    stock_df['Max'] = round(max(stock_df['Close']),2)
    stock_df = stock_df[(stock_df.index <= end_date) & (stock_df.index >= start_date)]
    stock_df['200_SMA'] = round(stock_df['Close'].rolling(window = 200, min_periods = 1).mean(),0)
    stock_df['Dev%_200'] = round((stock_df['Close'] - stock_df['200_SMA'])*100/stock_df['200_SMA'],2)
    stock_df.dropna(axis = 0, inplace = True) # remove any null rows

    stock_df['20_SMA'] = stock_df['Close'].rolling(window=20).mean()
    stock_df['50_SMA'] = stock_df['Close'].rolling(window=50).mean()
    stock_df['Symbol'] = stock_symbol

    stock_df['Close'] = round(stock_df['Close'],2)
    stock_df['Min'] = round(min(stock_df['Close']),2)
    stock_df['RSI_14'] = ta.momentum.RSIIndicator(close=stock_df['Close'], window=14).rsi()
    stock_df['RSI_14'] = round(stock_df['RSI_14'],0)
    stock_df['Prev_Close'] = stock_df['Close'].shift(1)
    stock_df.drop(['Open', 'Low', 'High', 'Volume'], axis=1, inplace=True)
    stock_df = stock_df.tail(1)

    max_SMA = max(stock_df['20_SMA'].item(), stock_df['50_SMA'].item(), stock_df['200_SMA'].item())
    min_SMA = min(stock_df['20_SMA'].item(), stock_df['50_SMA'].item(), stock_df['200_SMA'].item())
    ABS_Spread = max_SMA - min_SMA
    stock_df['Spread%'] = round((ABS_Spread / stock_df['200_SMA'].item()) * 100,2)

    return stock_df

# function to compute stock attributes
def get_common_features(stock_ids, df_mypf):

  df_prec_dev = pd.DataFrame()
  df_tmp = get_screener_features()
  df_rs = get_relative_strength(stock_ids)

  for stock_id in stock_ids:
      tmp = stock_prec_dev(stock_id)
      tmp = tmp.reset_index()
      df_prec_dev = pd.concat([df_prec_dev, tmp], ignore_index = True)
  df_prec_dev = pd.merge(df_prec_dev, df_mypf, on= 'Symbol')
  df_prec_dev = pd.merge(df_prec_dev, df_tmp, on= 'Symbol', how='left')
  df_prec_dev = pd.merge(df_prec_dev, df_rs, on= 'Symbol', how='left')
  #print(df_prec_dev.columns)
  df_prec_dev['Curr_PE'] = round(df_prec_dev['Close']/df_prec_dev['EPS'],1)
  df_prec_dev['Dev%_PE'] = round((df_prec_dev['Curr_PE'] - df_prec_dev['MedPE'])*100/df_prec_dev['MedPE'],2)
  df_prec_dev['Conviction'] = df_prec_dev['Conviction'] + '-' + df_prec_dev['CapType']
  return df_prec_dev

# function to arrange stock features
def arrange_features(df_stocks, common_cols, diff_cols):
  df_stocks_common = df_stocks[common_cols].drop_duplicates()
  df_stocks_diff = df_stocks[diff_cols]
  df_stocks_diff['Investment'] = df_stocks_diff['AvgCost'] * df_stocks_diff['Shares']
  df_stocks_diff = df_stocks_diff.groupby(['Symbol'])[['Shares', 'Investment']].aggregate(['sum']).reset_index()
  df_stocks_diff.columns = ['Symbol', 'Shares', 'Investment']
  df_stocks_diff['AvgCost'] = round(df_stocks_diff['Investment']/df_stocks_diff['Shares'],2)
  df_stocks = pd.merge(df_stocks_diff, df_stocks_common, on='Symbol')
  return df_stocks

# plot fact distribution across dimension
def plot_pie_chart(df, dimension, fact):
  # grouping the data by category and calculating the sum of fact for each type
  grouped_data = df.groupby(dimension)[fact].sum()

  # sorting the grouped data in descending order
  grouped_data = grouped_data.sort_values(ascending=False)

  # creating a pie chart
  grouped_data.plot.pie(autopct='%1.1f%%', startangle=90, figsize=(6, 6))

  # adding a title and displaying the plot
  plt.title(f'{dimension} {fact} Distribution')
  plt.ylabel('')  # To hide the y-label
  plt.show()

In [7]:
# function to get portfolio features

def get_portfolio_features(df_common_features):

  print_date_time()
  print('-------------------')

  #df_common_features["Target"] = df_common_features["Target"].fillna(df_common_features["Max"])
  df_common_features['NTT'] = np.where(df_common_features['Strategy']== 'NTT', df_common_features["Target"], df_common_features['Max'])
  df_common_features['LTT'] = np.where(df_common_features['Strategy']== 'BTT', df_common_features["Target"], df_common_features['Max'])
  df_common_features['BOL'] = df_common_features['Min']

  tmp_df = df_common_features[df_common_features['Symbol'].isin(mypf_df[mypf_df['InPortfolio'] != 'NA'].Symbol.values)]
  print('qualified stocks: '+str(len(tmp_df['Symbol'].unique())))
  tmp_df1 = tmp_df[tmp_df['LatestQtr'] == 1]
  print('with latest results: '+str(len(tmp_df1['Symbol'].unique())))
  tmp_df1 = tmp_df1[tmp_df1['StarStock'] == 1]
  print('still star stocks: '+str(len(tmp_df1['Symbol'].unique())))
  tmp_df['Investment'] = tmp_df['AvgCost'] * tmp_df['Shares']
  tmp_df['Current'] = round(tmp_df['Close'] * tmp_df['Shares'],0)
  tmp_df['Previous'] = tmp_df['Prev_Close'] * tmp_df['Shares']
  tmp_df['EstimatedST'] = tmp_df['NTT'] * tmp_df['Shares']
  tmp_df['EstimatedLT'] = tmp_df['LTT'] * tmp_df['Shares']
  tmp_df['Current P/L'] = round((tmp_df['Current'] - tmp_df['Investment']),0)
  tmp_df['Today P/L%'] = round((tmp_df['Current'] - tmp_df['Previous'])*100/tmp_df['Previous'],2)
  tmp_df['Current P/L%'] = round((tmp_df['Current'] - tmp_df['Investment'])*100/tmp_df['Investment'],2)
  tmp_df['EstimatedST P/L%'] = round((tmp_df['EstimatedST'] - tmp_df['Investment'])*100/tmp_df['Investment'],2)
  tmp_df['EstimatedLT P/L%'] = round((tmp_df['EstimatedLT'] - tmp_df['Investment'])*100/tmp_df['Investment'],2)
  tmp_df['NTT%'] = round((tmp_df['NTT'] - tmp_df['Close'])*100/tmp_df['Close'],2)
  tmp_df['LTT%'] = round((tmp_df['LTT'] - tmp_df['Close'])*100/tmp_df['Close'],2)
  tmp_df['Gained%'] = round((tmp_df['Close'] - tmp_df['BOL'])*100/tmp_df['BOL'],2)
  investment = round(sum(tmp_df['AvgCost']*tmp_df['Shares']),0)
  current = round(sum(tmp_df['Close']*tmp_df['Shares']),0)
  tmp_df['InitAlloc%'] = round(tmp_df['Investment']*100/investment,2)
  tmp_df['CurrAlloc%'] = round(tmp_df['Current']*100/current,2)
  tmp_df['FTT'] = tmp_df['LTT']
  tmp_df.loc[tmp_df['Strategy'] == 'NTT', 'FTT'] = tmp_df['NTT']
  tmp_df['FTT%'] = tmp_df['LTT%']
  tmp_df.loc[tmp_df['Strategy'] == 'NTT', 'FTT%'] = tmp_df['NTT%']
  tmp_df['FTT Amt'] = round(tmp_df['FTT%'] * tmp_df['Current']/100,0)
  tmp_df['OTT%'] = round((tmp_df['FTT'] - tmp_df['AvgCost'])*100/tmp_df['AvgCost'],2)
  tmp_df['RRR Ind'] = round(tmp_df['Current P/L']/tmp_df['FTT Amt'],2)
  tmp_df['Risk Ind'] = round(tmp_df['Current P/L%']*tmp_df['CurrAlloc%'],0)

  return tmp_df

# function to print portfolio features
def print_portfolio_stats(df_portfolio_features, myinvmt_df):
  from pyxirr import xirr

  total_booked_amt, reserve_amt, cy_booked_amt, py_booked_amt = get_amt()

  dates = myinvmt_df['Date'].values
  dates = np.append(dates, datetime.date.today().strftime('%d-%b-%y'))
  investment = myinvmt_df['Investment'].values
  dates= pd.to_datetime(dates)

  current = round(sum(df_portfolio_features['Close']*df_portfolio_features['Shares']),0) + reserve_amt
  investment_xirr = np.append(investment, current)
  cagr = round(xirr(pd.DataFrame({"dates": dates, "amounts": investment_xirr}))*100,2)

  investment = -sum(investment)
  invested = round(sum(df_portfolio_features['AvgCost']*df_portfolio_features['Shares']),0) + reserve_amt
  previous = round(sum(df_portfolio_features['Prev_Close']*df_portfolio_features['Shares']),0) + reserve_amt
  cy_invested = investment + py_booked_amt

  today_pnl_amount = current-previous
  today_pnl_percentage = round((current-previous)*100/previous,2)

  curr_pnl_amount = current-invested
  curr_pnl_percentage = round((curr_pnl_amount)*100/(cy_invested),2)

  cy_pnl_amount = cy_booked_amt + curr_pnl_amount
  cy_pnl_percentage = round((cy_pnl_amount)*100/cy_invested,2)

  overall_pnl_amount = total_booked_amt + curr_pnl_amount
  overall_pnl_percentage = round((overall_pnl_amount)*100/investment,2)

  estimate_st = round(sum(df_portfolio_features['FTT']*df_portfolio_features['Shares']),0)  + reserve_amt
  est_st_pnl_amount = estimate_st-current
  est_st_pnl_percentage = round((est_st_pnl_amount)*100/current,2)

  estimate_lt = round(sum(df_portfolio_features['LTT']*df_portfolio_features['Shares']),0)  + reserve_amt
  est_lt_pnl_amount = estimate_lt-current
  est_lt_pnl_percentage = round((est_lt_pnl_amount)*100/current,2)

  total_profit = round(sum(df_portfolio_features[df_portfolio_features['Current P/L%'] > 0]['Current']) - sum(df_portfolio_features[df_portfolio_features['Current P/L%'] > 0]['Investment']),0)
  total_loss = round(sum(df_portfolio_features[df_portfolio_features['Current P/L%'] < 0]['Current']) - sum(df_portfolio_features[df_portfolio_features['Current P/L%'] < 0]['Investment']),0)

  cy_booked_percentage = round((cy_booked_amt)*100/current,2)
  py_booked_percentage = round((py_booked_amt)*100/investment,2)
  total_booked_percentage = round((total_booked_amt)*100/investment,2)

  print('-------------------')
  print('Initial Investment: ', format_amt(investment))
  print('CY Investment: ', format_amt(cy_invested))
  print('Reserve: ', format_amt(reserve_amt))
  print('Current: ',  format_amt(current))
  print('-------------------')
  print('Today PnL: '+ '{} ({}%)'.format(format_amt(today_pnl_amount), today_pnl_percentage))
  print('Current PnL: '+ '{} ({}%)'.format(format_amt(curr_pnl_amount), curr_pnl_percentage))
  print('CY Booked + Current PnL: '+ '{} ({}%)'.format(format_amt(cy_pnl_amount), cy_pnl_percentage))
  print('-------------------')
  print('Total profit: ', format_amt(total_profit))
  print('Total loss: ', format_amt(total_loss))
  print('-------------------')
  print('Total Booked + Current PnL: '+ '{} ({}%)'.format(format_amt(overall_pnl_amount), overall_pnl_percentage))
  print('Total Booked PnL: '+ '{} ({}%)'.format(format_amt(total_booked_amt), total_booked_percentage))
  print('Curr Year Booked PnL: '+ '{} ({}%)'.format(format_amt(cy_booked_amt), cy_booked_percentage))
  print('Prev Year Booked PnL: '+ '{} ({}%)'.format(format_amt(py_booked_amt), py_booked_percentage))
  print('===================')
  print('Est FTT: ',  format_amt(estimate_st))
  print('Est FTT PnL: '+ '{} ({}%)'.format(format_amt(est_st_pnl_amount), est_st_pnl_percentage))

  print('===================')
  print('Deployed: ', format_amt(investment))

  print('Current: ', format_amt(current))

  print('CAGR/XIRR %: '+'{}%'.format(cagr))

In [8]:
# get start and end date
start_date, end_date = get_start_end_date()

# get portfolio and prospects data
mypfs_df = get_mypfs_df()
mypps_df = get_mypps_df()
myinvmt_df = get_myinvmt_df()

# merge above datasets
mypf_df = pd.merge(mypfs_df, mypps_df, on="Symbol")

# seggregate dm and sv portfolio
dm_pf = mypf_df[mypf_df['InPortfolio'] == 'DM']
sv_pf = mypf_df[mypf_df['InPortfolio'] == 'SV']

# build portfolio stock dataframe
dm_stocks = get_stock_ids(dm_pf)
sv_stocks = get_stock_ids(sv_pf)
df_stocks = pd.concat([dm_pf,sv_pf], ignore_index = True)

# arrange common and diff stock features
common_cols = ['Symbol', 'Target', 'Criteria', 'Strategy', 'CumlRnk', 'LatestQtr', 'StarStock', 'Conviction', 'Category', 'InFolio', 'XIRR', 'MBQ']
diff_cols = ['Symbol', 'AvgCost', 'Shares']
df_stocks = arrange_features(df_stocks, common_cols, diff_cols)

# get common features
stock_ids = df_stocks['Symbol'].values
df_common_features = get_common_features(stock_ids, df_stocks)

df_common_features.reset_index(drop=True, inplace=True)
df_common_features.drop(['Date'], axis=1, inplace=True)
# get and print portfolio features
df_portfolio_features = get_portfolio_features(df_common_features)

print_portfolio_stats(df_portfolio_features, myinvmt_df)

df = df_portfolio_features
#plot_pie_chart(df, 'CapType', 'Current')
list_ox40n = list(df[df['MBQ'].str.contains('OX40N', na=False)]['Symbol'].values)

Run date time (IST): 2026-08-20 11:16:42
-------------------
qualified stocks: 87
with latest results: 30
still star stocks: 19
-------------------
Initial Investment:  1.46 C
CY Investment:  1.89 C
Reserve:  3.69 L
Current:  1.58 C
-------------------
Today PnL: 72.66 K (0.46%)
Current PnL: -34.52 L (-18.27%)
CY Booked + Current PnL: -29.46 L (-15.59%)
-------------------
Total profit:  3.63 L
Total loss:  -38.15 L
-------------------
Total Booked + Current PnL: 13.41 L (9.18%)
Total Booked PnL: 47.93 L (32.82%)
Curr Year Booked PnL: 5.06 L (3.19%)
Prev Year Booked PnL: 42.87 L (29.35%)
===================
Est FTT:  2.67 C
Est FTT PnL: 1.09 C (68.6%)
===================
Deployed:  1.46 C
Current:  1.58 C
CAGR/XIRR %: 3.68%

In [9]:
# top 5 near their targets
cols = ['Symbol', 'Today P/L%', 'Current P/L%', 'FTT%', 'OTT%', 'FTT Amt', 'Current P/L', 'Current', 'FTT', 'Dev%_PE', 'RSI_14','Conviction', 'Spread%',  'CumlRnk', 'RRR Ind', 'CurrAlloc%', 'Gained%', 'Criteria', 'Strategy', 'Category']
df_tmp = df_portfolio_features[~df_portfolio_features['Symbol'].isin(['ENRIN','BLUSPRING','DIGITIDE'])]
df_tmp = df_tmp.sort_values(by = 'FTT Amt', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
66,SIEMENS,0.58,5.36,5.19,10.83,10176.0,9980.0,196075.0,4125.00,-14.70,59.0,H-LC,14.13,51.0,0.98,1.27,38.34,AR,NTT,ELECTRICAL
78,UNITDSPR,0.72,12.53,7.32,20.77,19287.0,29343.0,263487.0,1644.00,-4.14,62.0,X-MC,10.92,64.0,1.52,1.70,26.66,X40N,NTT,BREWERIES
77,TTKPRESTIG,-0.49,-23.08,30.13,0.09,23355.0,-23264.0,77513.0,770.00,-6.45,41.0,M-SC,9.71,250.0,-1.00,0.50,39.51,OX40N,NTT,DURABLES
52,M&M,0.35,8.21,9.80,18.82,25524.0,19771.0,260452.0,3762.88,-6.55,59.0,X-LC,4.88,25.0,0.77,1.68,18.15,X40N,ATH,AUTO
54,MASFIN,-0.59,-7.79,31.84,21.57,28766.0,-7635.0,90345.0,397.04,-28.64,42.0,H-SC,1.46,167.0,-0.27,0.58,7.69,XR,ATH,FINANCE

In [10]:
# top 5 today
df_tmp = df_portfolio_features.sort_values(by = 'Today P/L%', ascending=False)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
62,REPCOHOME,4.76,-20.89,139.95,89.82,317199.0,-59853.0,226652.0,880.0,NaN,41.0,NaN,4.44,161.0,-0.19,1.46,8.96,XY24,NTT,FINANCE
9,BANDHANBNK,3.50,-15.75,128.40,92.42,301321.0,-43885.0,234674.0,400.0,49.43,46.0,H-SC,11.17,174.0,-0.15,1.52,30.39,XY24,NTT,BANKS
0,5PAISA,3.15,-23.74,48.05,12.90,80065.0,-51867.0,166629.0,593.0,6.97,64.0,H-SC,11.85,170.0,-0.65,1.08,60.80,OX40N,NTT,FINANCE
14,CAMPUS,3.04,-24.30,76.07,33.28,96613.0,-40769.0,127006.0,393.0,NaN,51.0,NaN,10.55,218.0,-0.42,0.82,3.87,XY24,NTT,FOOTWEAR
80,VAIBHAVGBL,2.51,-29.31,127.41,60.77,164629.0,-53563.0,129212.0,521.0,NaN,38.0,NaN,7.35,160.0,-0.33,0.84,32.30,XR,NTT,JEWELLERY

In [11]:
# bottom 5 today
df_tmp = df_portfolio_features.sort_values(by = 'Today P/L%', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
51,LAOPALA,-6.32,-46.84,161.64,39.09,112655.0,-61410.0,69695.0,464.00,NaN,37.0,NaN,4.03,154.0,-0.55,0.45,8.13,AR,NTT,CERAMICS
29,GREENPANEL,-4.12,-57.54,237.08,43.14,184313.0,-105335.0,77743.0,537.00,NaN,24.0,NaN,12.00,225.0,-0.57,0.50,0.00,XY24,NTT,MISC
60,RELAXO,-2.59,-51.56,214.44,52.31,150777.0,-74848.0,70312.0,1176.00,NaN,38.0,NaN,11.87,92.0,-0.50,0.45,57.21,X40N,NTT,FOOTWEAR
59,RECLTD,-2.39,-10.95,35.58,20.74,64372.0,-22248.0,180922.0,446.00,-2.70,32.0,M-MC,2.41,191.0,-0.35,1.17,9.54,XY25,NTT,FINANCE
55,PAGEIND,-2.28,-7.67,43.89,32.85,108759.0,-20579.0,247800.0,50936.07,-31.34,28.0,X-MC,8.81,55.0,-0.19,1.60,18.33,X40,ATH,APPARELS

In [12]:
# top 5 to exit based on CumlRnk
df_tmp = df_portfolio_features[~df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])]
df_tmp = df_tmp[(df_tmp['Current P/L%'] > -1) & (df_tmp['Current P/L%'] < 1)].sort_values(by = 'CumlRnk', ascending=False)
df_tmp[cols].head()

Empty DataFrame
Columns: [Symbol, Today P/L%, Current P/L%, FTT%, OTT%, FTT Amt, Current P/L, Current, FTT, Dev%_PE, RSI_14, Conviction, Spread%, CumlRnk, RRR Ind, CurrAlloc%, Gained%, Criteria, Strategy, Category]
Index: []

In [13]:
# OX40N stocks to exit
df_tmp = df_portfolio_features[(df_portfolio_features['Symbol'].isin(list_ox40n))].sort_values(by = 'Current P/L%', ascending=False)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
25,FINCABLES,-0.28,65.92,25.31,107.91,62002.0,97326.0,244970.0,1641.55,20.71,74.0,M-SC,21.38,220.0,1.57,1.58,84.30,OX40N,ATH,CABLES
67,SIS,0.00,-5.01,27.66,21.26,29172.0,-5564.0,105468.0,528.00,102.74,37.0,H-SC,20.82,168.0,-0.19,0.68,56.82,OX40N,NTT,MISC
43,INDIGOPNTS,0.39,-17.93,21.87,0.02,31330.0,-31302.0,143257.0,1408.00,-21.69,65.0,M-SC,7.25,222.0,-1.00,0.93,62.54,OX40N,NTT,PAINTS
12,BOSCH-HCIL,0.06,-22.72,29.39,-0.01,29028.0,-29038.0,98767.0,2282.00,773.87,78.0,M-SC,8.75,231.0,-1.00,0.64,68.12,OX40N,BTT,AC
77,TTKPRESTIG,-0.49,-23.08,30.13,0.09,23355.0,-23264.0,77513.0,770.00,-6.45,41.0,M-SC,9.71,250.0,-1.00,0.50,39.51,OX40N,NTT,DURABLES

In [14]:
# top 5 to book for rotation
df_tmp = df_portfolio_features[(df_portfolio_features['Current P/L%'] > 20) ].sort_values(by = 'CumlRnk', ascending=False)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
25,FINCABLES,-0.28,65.92,25.31,107.91,62002.0,97326.0,244970.0,1641.55,20.71,74.0,M-SC,21.38,220.0,1.57,1.58,84.30,OX40N,ATH,CABLES
27,GLAXO,-0.92,20.61,12.51,35.69,30068.0,41068.0,240352.0,3380.16,-9.49,82.0,X-MC,10.79,56.0,1.37,1.55,42.85,X40,ATH,PHARMA

In [15]:
# top 5 to monitor for exit
df_tmp = df_portfolio_features[~df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])]
df_tmp = df_tmp[(df_tmp['Current P/L%'] > 0) ].sort_values(by = 'Dev%_PE', ascending=False)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
25,FINCABLES,-0.28,65.92,25.31,107.91,62002.0,97326.0,244970.0,1641.55,20.71,74.0,M-SC,21.38,220.0,1.57,1.58,84.30,OX40N,ATH,CABLES
68,STARHEALTH,0.03,13.02,30.30,47.26,96270.0,36600.0,317723.0,761.00,-0.37,51.0,H-SC,16.28,173.0,0.38,2.05,37.38,XY24,NTT,INSURANCE

In [16]:
# top 5 to book for rotation from weak conviction
df_tmp = df_portfolio_features[~df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])]
df_tmp = df_tmp[~df_tmp['Criteria'].isin(['XY25','XY24','X40', 'X40N'])].sort_values(by = 'RRR Ind', ascending=False)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
25,FINCABLES,-0.28,65.92,25.31,107.91,62002.0,97326.0,244970.0,1641.55,20.71,74.0,M-SC,21.38,220.0,1.57,1.58,84.30,OX40N,ATH,CABLES
3,ALKYLAMINE,-0.14,-16.81,131.43,92.54,110396.0,-16967.0,83996.0,4520.85,NaN,59.0,NaN,14.74,142.0,-0.15,0.54,59.50,SR,ATH,CHEMICALS
67,SIS,0.00,-5.01,27.66,21.26,29172.0,-5564.0,105468.0,528.00,102.74,37.0,H-SC,20.82,168.0,-0.19,0.68,56.82,OX40N,NTT,MISC
42,INDIAMART,0.02,-24.65,166.66,100.92,154877.0,-30406.0,92930.0,4675.60,NaN,37.0,NaN,13.86,140.0,-0.20,0.60,0.60,AR,ATH,MISC
71,TANLA,2.07,-34.11,229.70,117.25,409815.0,-92348.0,178413.0,1922.32,NaN,50.0,NaN,15.67,147.0,-0.23,1.15,56.20,AR,ATH,IT

In [17]:
# top 5 to accumulate based on lowest RSI_14
df_tmp = df_portfolio_features[df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])].sort_values(by = 'RSI_14', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
47,ITC,-0.43,-26.64,69.99,24.70,203969.0,-105852.0,291426.0,452.00,-31.57,28.0,X-LC,10.93,1.0,-0.52,1.88,0.00,X40,NTT,FMCG
55,PAGEIND,-2.28,-7.67,43.89,32.85,108759.0,-20579.0,247800.0,50936.07,-31.34,28.0,X-MC,8.81,55.0,-0.19,1.60,18.33,X40,ATH,APPARELS
56,PGHH,-0.93,-38.25,113.80,32.01,150034.0,-81680.0,131840.0,17616.87,-54.65,28.0,X-SC,19.68,57.0,-0.54,0.85,0.00,X40,ATH,FMCG
19,COLPAL,0.40,-28.34,95.18,39.86,179624.0,-74645.0,188720.0,3683.41,-13.17,29.0,X-MC,1.97,62.0,-0.42,1.22,6.75,XY25,ATH,FMCG
20,DABUR,0.14,-21.74,83.61,43.70,162325.0,-53922.0,194146.0,735.00,-32.48,33.0,X-MC,10.25,70.0,-0.33,1.25,0.14,XY24,BTT,FMCG

In [18]:
# top 5 to accumulate based on Spread and CumlRnk
df_tmp = df_portfolio_features[df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])]
df_tmp = df_tmp[(df_tmp['CumlRnk'] < 100)].sort_values(by = 'Spread%', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
19,COLPAL,0.40,-28.34,95.18,39.86,179624.0,-74645.0,188720.0,3683.41,-13.17,29.0,X-MC,1.97,62.0,-0.42,1.22,6.75,XY25,ATH,FMCG
50,KOTAKBANK,1.56,4.17,14.16,18.92,35358.0,9998.0,249700.0,452.46,-11.94,57.0,X-LC,2.10,12.0,0.28,1.61,12.35,X40,ATH,BANKS
23,DMART,1.13,-2.25,34.45,31.42,104990.0,-7030.0,304760.0,5391.45,-18.04,50.0,X-LC,2.29,14.0,-0.07,1.97,9.97,X40N,ATH,FMCG
26,GILLETTE,-0.57,-11.68,46.87,29.72,105106.0,-29646.0,224250.0,10978.86,-36.19,35.0,X-SC,3.73,83.0,-0.28,1.45,3.05,X40,ATH,FMCG
53,MARUTI,0.25,-0.08,24.75,24.64,61140.0,-206.0,247032.0,17120.06,-5.97,48.0,X-LC,3.97,33.0,-0.00,1.60,12.64,XR,ATH,AUTO

In [19]:
# top 5 to accumulate based on lowest Gained%
df_tmp = df_portfolio_features[df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])].sort_values(by = 'Gained%', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
47,ITC,-0.43,-26.64,69.99,24.70,203969.0,-105852.0,291426.0,452.00,-31.57,28.0,X-LC,10.93,1.0,-0.52,1.88,0.00,X40,NTT,FMCG
56,PGHH,-0.93,-38.25,113.80,32.01,150034.0,-81680.0,131840.0,17616.87,-54.65,28.0,X-SC,19.68,57.0,-0.54,0.85,0.00,X40,ATH,FMCG
83,VOLTAS,-0.43,-4.73,52.41,45.20,95737.0,-9072.0,182670.0,1856.00,31.20,34.0,X-MC,4.81,79.0,-0.09,1.18,0.12,XY25,NTT,AC
20,DABUR,0.14,-21.74,83.61,43.70,162325.0,-53922.0,194146.0,735.00,-32.48,33.0,X-MC,10.25,70.0,-0.33,1.25,0.14,XY24,BTT,FMCG
36,HINDUNILVR,0.31,-15.67,44.15,21.56,125289.0,-52737.0,283780.0,2922.00,-41.98,39.0,X-LC,6.62,9.0,-0.42,1.83,0.31,XY25,NTT,FMCG

In [20]:
# top 5 to accumulate based on lowest CurrAlloc%
df_tmp = df_portfolio_features[df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])].sort_values(by = 'CurrAlloc%', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
56,PGHH,-0.93,-38.25,113.80,32.01,150034.0,-81680.0,131840.0,17616.87,-54.65,28.0,X-SC,19.68,57.0,-0.54,0.85,0.00,X40,ATH,FMCG
1,ABBOTINDIA,-1.60,-12.26,31.49,15.37,49417.0,-21925.0,156930.0,34390.26,-28.62,35.0,X-MC,4.04,58.0,-0.44,1.01,6.30,X40,ATH,PHARMA
2,ACC,0.99,-41.76,200.14,74.81,312555.0,-111960.0,156168.0,3906.00,-42.24,38.0,X-SC,11.72,85.0,-0.36,1.01,4.33,XY24,BTT,CEMENT
40,ICICIPRULI,1.08,-16.45,55.93,30.28,92059.0,-32408.0,164597.0,787.27,-46.46,50.0,X-MC,12.20,78.0,-0.35,1.06,9.67,X40,ATH,INSURANCE
39,ICICIGI,0.84,-13.26,37.06,18.89,64327.0,-26534.0,173575.0,2244.41,-13.56,44.0,X-MC,10.38,66.0,-0.41,1.12,3.41,X40,ATH,INSURANCE

In [21]:
# top 5 to accumulate based on CumlRnk
df_tmp = df_portfolio_features.sort_values(by = 'CumlRnk', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
47,ITC,-0.43,-26.64,69.99,24.70,203969.0,-105852.0,291426.0,452.00,-31.57,28.0,X-LC,10.93,1.0,-0.52,1.88,0.00,X40,NTT,FMCG
73,TCS,0.53,-32.45,83.85,24.20,262419.0,-150310.0,312963.0,4230.71,-43.98,48.0,X-LC,14.03,2.0,-0.57,2.02,16.71,X40,ATH,IT
45,INFY,0.96,-19.52,74.44,40.38,225534.0,-73496.0,302974.0,1972.00,-40.86,50.0,X-LC,15.88,3.0,-0.33,1.96,14.74,X40,NTT,IT
75,TMPV,0.36,-23.28,86.08,42.75,274790.0,-96881.0,319226.0,600.00,-84.91,36.0,X-LC,4.56,4.0,-0.35,2.06,9.77,XY24,NTT,AUTO
33,HCLTECH,0.43,-11.01,39.30,23.97,108238.0,-34072.0,275414.0,1853.42,-13.43,57.0,X-LC,10.67,8.0,-0.31,1.78,29.96,X40,ATH,IT

In [22]:
# top 5 for average up
df_tmp = df_portfolio_features[(df_portfolio_features['Dev%_200'] > 5)].sort_values(by = 'CurrAlloc%', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
44,INDUSINDBK,-0.61,-25.52,78.43,32.89,45099.0,-19704.0,57502.0,1800.00,323.08,51.0,L-MC,13.12,258.0,-0.44,0.37,41.77,XR,NTT,BANKS
3,ALKYLAMINE,-0.14,-16.81,131.43,92.54,110396.0,-16967.0,83996.0,4520.85,NaN,59.0,NaN,14.74,142.0,-0.15,0.54,59.50,SR,ATH,CHEMICALS
12,BOSCH-HCIL,0.06,-22.72,29.39,-0.01,29028.0,-29038.0,98767.0,2282.00,773.87,78.0,M-SC,8.75,231.0,-1.00,0.64,68.12,OX40N,BTT,AC
67,SIS,0.00,-5.01,27.66,21.26,29172.0,-5564.0,105468.0,528.00,102.74,37.0,H-SC,20.82,168.0,-0.19,0.68,56.82,OX40N,NTT,MISC
81,VALIANTORG,-0.34,-35.92,171.77,74.15,180082.0,-58766.0,104839.0,838.00,NaN,58.0,NaN,7.85,145.0,-0.33,0.68,56.02,XR,NTT,CHEMICALS

In [23]:
# top 5 RSP
df_tmp = df_portfolio_features.sort_values(by = 'RSP', ascending=False)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
12,BOSCH-HCIL,0.06,-22.72,29.39,-0.01,29028.0,-29038.0,98767.0,2282.00,773.87,78.0,M-SC,8.75,231.0,-1.00,0.64,68.12,OX40N,BTT,AC
25,FINCABLES,-0.28,65.92,25.31,107.91,62002.0,97326.0,244970.0,1641.55,20.71,74.0,M-SC,21.38,220.0,1.57,1.58,84.30,OX40N,ATH,CABLES
27,GLAXO,-0.92,20.61,12.51,35.69,30068.0,41068.0,240352.0,3380.16,-9.49,82.0,X-MC,10.79,56.0,1.37,1.55,42.85,X40,ATH,PHARMA
81,VALIANTORG,-0.34,-35.92,171.77,74.15,180082.0,-58766.0,104839.0,838.00,NaN,58.0,NaN,7.85,145.0,-0.33,0.68,56.02,XR,NTT,CHEMICALS
38,HYUNDAI,1.22,13.85,26.43,43.94,75624.0,34798.0,286130.0,2782.73,17.86,64.0,X-LC,5.66,29.0,0.46,1.85,31.37,X40N,ATH,AUTO

In [24]:
# Top N allocation
df_tmp = df_portfolio_features.sort_values(by = 'CurrAlloc%', ascending=False)
top_n_values = [10, 25, 50]

sum_df = pd.DataFrame({
    'Top_N': top_n_values,
    'Sum_Alloc%': [df_tmp['CurrAlloc%'].head(n).sum() for n in top_n_values]
})

sum_df

   Top_N  Sum_Alloc%
0     10       19.70
1     25       44.97
2     50       77.63

In [25]:
# market-cap-wise allocation
df_tmp = df_portfolio_features[cols]
df_tmp.groupby(df_tmp['Conviction'].str[-2:])['CurrAlloc%'].sum().sort_values(ascending=False)

Conviction
LC    38.03
MC    22.16
SC    21.64
Name: CurrAlloc%, dtype: float64

In [26]:
# criteria-wise allocation
df_portfolio_features.groupby('Criteria')['CurrAlloc%'].sum().sort_values(ascending=False)

Criteria
X40      26.60
XY24     24.03
X40N     18.71
XR        9.11
OX40N     7.39
XY25      7.13
AR        6.11
SR        0.87
Name: CurrAlloc%, dtype: float64

In [27]:
# conviction-wise allocation
df_portfolio_features.groupby('Conviction')['CurrAlloc%'].sum().sort_values(ascending=False)

Conviction
X-LC    34.35
X-MC    19.59
H-SC     8.58
X-SC     7.60
M-SC     5.46
H-LC     2.87
M-MC     1.17
H-MC     1.03
M-LC     0.81
L-MC     0.37
Name: CurrAlloc%, dtype: float64

In [28]:
# sector-wise stats
df_tmp = df_portfolio_features.groupby('Category')[['CurrAlloc%', 'Current', 'Current P/L', 'FTT Amt']].sum().sort_values(by=['Current', 'Current P/L'], ascending=False)
df_tmp['Current P/L%'] = round(df_tmp['Current P/L'] * 100 / df_tmp['Current'], 2)
df_tmp['FTT%'] = round(df_tmp['FTT Amt'] * 100 / df_tmp['Current'], 2)
cols = ['CurrAlloc%', 'Current P/L%', 'FTT%']
df_tmp[cols].sort_values(by=['CurrAlloc%'], ascending=False)

               CurrAlloc%  Current P/L%    FTT%
Category
FMCG                15.36        -25.37   70.45
IT                  11.25        -36.80  104.65
FINANCE             10.81        -15.23   64.86
AUTO                 8.27         -5.67   43.51
BANKS                6.21        -11.13   59.05
MISC                 5.94        -34.23   88.22
PHARMA               5.86          8.73   17.16
INSURANCE            5.74         -4.52   41.48
PAINTS               5.46        -16.77   36.69
ELECTRICAL           4.17         -9.61   43.93
AC                   1.82        -13.54   44.33
REFINERIES           1.73        -11.56   49.03
BREWERIES            1.70         11.14    7.32
FOOTWEAR             1.65        -72.15  141.18
APPARELS             1.60         -8.30   43.89
CABLES               1.58         39.73   25.31
DURABLES             1.47        -70.31  111.75
TRAVEL               1.42       -104.04  206.21
CERAMICS             1.31        -51.57   97.62
ENGINEERING          1.25        -25.63   83.09
CHEMICALS            1.22        -40.11  153.83
CEMENT               1.01        -71.69  200.14
JEWELLERY            0.98       -112.34  186.12
HEALTHCARE           0.70        -67.02  108.95
ENTERTAINMENT        0.68        -81.56  189.85
TEXTILES             0.39        -51.34   94.49
HOTELS               0.37        -99.12  169.36

In [29]:
# money to be made criteria-wise
df_portfolio_features.groupby('Criteria')['FTT Amt'].agg(['sum', 'count']).sort_values(by='sum', ascending=False)

                sum  count
Criteria
XY24      3608188.0     19
X40       2103069.0     18
XR        1386456.0     13
X40N      1182580.0     12
AR        1060461.0      8
OX40N      650503.0     10
XY25       596030.0      5
SR         280699.0      2

In [30]:
# money to be made conviction-wise
df_portfolio_features.groupby('Conviction')['FTT Amt'].agg(['sum', 'count']).sort_values(by='sum', ascending=False)

                  sum  count
Conviction
X-LC        2408896.0     19
X-MC        1465570.0     14
X-SC        1103079.0      6
H-SC         824098.0      8
M-SC         319687.0      6
H-MC         254083.0      1
M-LC         165946.0      1
M-MC          64372.0      1
H-LC          47025.0      2
L-MC          45099.0      1

In [31]:
# money to be made criteria and conviction-wise
df_portfolio_features.groupby(['Conviction', 'Criteria'])['FTT Amt'].agg(['sum', 'count']).sort_values(by='sum', ascending=False)

                           sum  count
Conviction Criteria
X-LC       X40       1225766.0      9
X-SC       XY24       675034.0      2
H-SC       XY24       521133.0      3
X-MC       X40        507392.0      6
X-LC       XY24       456159.0      2
X-MC       X40N       449364.0      4
X-LC       X40N       409534.0      5
X-MC       XY25       275361.0      2
X-LC       XY25       256297.0      2
X-SC       X40        255140.0      2
H-MC       XY24       254083.0      1
X-MC       XY24       233453.0      2
H-SC       OX40N      212519.0      3
X-SC       X40N       172905.0      2
M-LC       XR         165946.0      1
M-SC       OX40N      145715.0      4
           XY24       116371.0      1
H-SC       XR          90446.0      2
M-MC       XY25        64372.0      1
X-LC       XR          61140.0      1
M-SC       XR          57601.0      1
H-LC       AR          47025.0      2
L-MC       XR          45099.0      1

In [32]:
# notebook execution time

end_time = time.time()
execution_time = round(end_time - start_time, 0)
print(f"Notebook execution time: {execution_time} seconds")

Notebook execution time: 27.0 seconds