<a href="https://colab.research.google.com/github/ankit-rathi/Quantvesting_v2/blob/main/myStocks_Portfolio_Analysis.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
'''
!pip install pandas==2.2.2 -qq
!pip install pyxirr -qq
!pip install ta -qq
!pip install yfinance==0.2.59 -qq
'''

'\n!pip install pandas==2.2.2 -qq\n!pip install pyxirr -qq\n!pip install ta -qq\n!pip install yfinance==0.2.59 -qq\n'

In [2]:
# import libraries

import numpy as np
import pandas as pd
import datetime
import warnings
warnings.filterwarnings('ignore')
import yfinance as yfin
import ta
import matplotlib.pyplot as plt
import requests

In [3]:
# notebook start time
import time
import datetime
import pytz

start_time = time.time()

# function to print date timestamp
def print_date_time():
  tz_NY = pytz.timezone('Asia/Kolkata')
  datetime_NY = datetime.datetime.now(tz_NY)
  print("Run date time (IST):", datetime_NY.strftime("%Y-%m-%d %H:%M:%S"))

In [4]:
# function to get booked and reserved amount
def get_amt():
  # fetch the JSON data from the URL
  url = "https://raw.githubusercontent.com/ankit-rathi/Tradevesting_v1/main/data/myPortfolioAmts.json"
  response = requests.get(url)
  pf_amts = response.json()  # parse the JSON data

  # extract values from the JSON
  py_booked_amt_dm = pf_amts["py_booked_amt_dm"]
  py_booked_amt_sv = pf_amts["py_booked_amt_sv"]
  cy_booked_amt_dm = pf_amts["cy_booked_amt_dm"]
  cy_booked_amt_sv = pf_amts["cy_booked_amt_sv"]
  reserve_amt_dm = pf_amts["reserve_amt_dm"]
  reserve_amt_sv = pf_amts["reserve_amt_sv"]

  # perform calculations
  py_booked_amt = py_booked_amt_dm + py_booked_amt_sv
  cy_booked_amt = cy_booked_amt_dm + cy_booked_amt_sv
  reserve_amt = reserve_amt_dm + reserve_amt_sv
  total_booked_amt = py_booked_amt + cy_booked_amt

  return total_booked_amt, reserve_amt, cy_booked_amt, py_booked_amt

gen_output = 0

In [5]:
# function to format the amount
def format_amt(number):
    abs_number = abs(number)

    if abs_number >= 1_00_00_000:  # Crores
        formatted_amt = f"{number / 1_00_00_000:.2f} C"
    elif abs_number >= 1_00_000:  # Lakhs
        formatted_amt = f"{number / 1_00_000:.2f} L"
    elif abs_number >= 1_000:  # Thousands
        formatted_amt = f"{number / 1_000:.2f} K"
    else:
        formatted_amt = f"{number:.2f}"

    return formatted_amt

# function to set start and end date
def get_start_end_date():
  start_date = (datetime.date.today() + datetime.timedelta(days=-365)).strftime('%Y-%m-%d')
  end_date = (datetime.date.today() + datetime.timedelta(days=1)).strftime('%Y-%m-%d')
  return start_date, end_date

# function to fetch my portfolio csv
def get_mypfs_df():
  mypfs_df = pd.read_csv('https://raw.githubusercontent.com/ankit-rathi/Tradevesting_v1/main/data/myPortfolioStocks.csv')
  return mypfs_df

# function to fetch my prospects csv
def get_mypps_df():
  mypps_df = pd.read_csv('https://raw.githubusercontent.com/ankit-rathi/Tradevesting_v1/main/data/myProspectsScrips.csv')
  return mypps_df

# function to fetch screener data
def get_myscreen_df():
  myscreen_df = pd.read_csv('https://raw.githubusercontent.com/ankit-rathi/Tradevesting_v1/main/data/myScreenerDB.csv')
  return myscreen_df

# function to fetch momentum data
def get_myinvmt_df():
  myinvmt_df = pd.read_csv('https://raw.githubusercontent.com/ankit-rathi/Tradevesting_v1/main/data/myInvestments.csv')
  return myinvmt_df

# function to get the stock ids
def get_stock_ids(df_pf):
  stock_n100 = df_pf['Symbol'].unique()

  exclude = ['CADILAHC','MMTC', 'MASFIN']

  stock_ids = df_pf[~df_pf['Symbol'].isin(exclude) ]['Symbol'].unique()

  #mypf = mypf[mypf.Forecast.notnull()]
  #stock_ids = mypf['Symbol'].unique()

  #stock_ids.sort()
  return stock_ids

# get features from screener data
def get_screener_features():
  myscreen_df = get_myscreen_df()
  cols = ['Symbol', 'EPS', 'MedPE', 'ROCE%', 'ROE%', 'CapType']
  return myscreen_df[cols]

# get relative strength
def get_relative_strength(stock_list):

    # Dictionary to store stock tickers and their corresponding percentage price change
    stock_changes = {}

    # Loop through each stock and fetch its price data
    for stock in stock_list:
        try:
            # Download the stock data for the given date range
            stock_data = yfin.Ticker(stock + '.NS').history(period='1mo', interval='1d')[map(str.title, ['open', 'close', 'low', 'high', 'volume'])]

            # Calculate the percentage change for the stock
            if len(stock_data) > 0:
                start_price = stock_data['Close'].iloc[0]
                end_price = stock_data['Close'].iloc[-1]
                percent_change = round(((end_price - start_price) / start_price) * 100, 2)
                stock_changes[stock] = percent_change
            else:
                stock_changes[stock] = np.nan  # If no data is available, set to NaN

        except Exception as e:
            print(f"Error fetching data for {stock}: {e}")
            stock_changes[stock] = np.nan

    # Create a DataFrame with stock tickers and their percentage changes
    df = pd.DataFrame(list(stock_changes.items()), columns=['Symbol', 'Percent_Change'])

    # Drop any stocks with missing data (NaN values)
    df = df.dropna()

    # Calculate the percentile rank based on percentage change
    df['RSP'] = round(df['Percent_Change'].rank(pct=True) * 100, 2)
    cols = ['Symbol', 'RSP']
    df = df[cols]
    # Sort by percentile rank (optional)
    df = df.sort_values(by='RSP', ascending=False).reset_index(drop=True)

    return df

In [6]:
# function to get stock technicals
def stock_prec_dev(stock_symbol):
    #stock_symbol = 'ULTRACEMCO.NS'
    short_window = 20
    mid_window = 50
    long_window = 200
    moving_avg = 'SMA'

    start = datetime.datetime(*map(int, start_date.split('-')))
    end = datetime.datetime(*map(int, end_date.split('-')))

    stock_df = yfin.Ticker(stock_symbol + '.NS').history(period='max', interval='1d')[map(str.title, ['open', 'close', 'low', 'high', 'volume'])]

    stock_df['Max'] = round(max(stock_df['Close']),2)
    stock_df = stock_df[(stock_df.index <= end_date) & (stock_df.index >= start_date)]
    stock_df['200_SMA'] = round(stock_df['Close'].rolling(window = 200, min_periods = 1).mean(),0)
    stock_df['Dev%_200'] = round((stock_df['Close'] - stock_df['200_SMA'])*100/stock_df['200_SMA'],2)
    stock_df.dropna(axis = 0, inplace = True) # remove any null rows

    stock_df['20_SMA'] = stock_df['Close'].rolling(window=20).mean()
    stock_df['50_SMA'] = stock_df['Close'].rolling(window=50).mean()
    stock_df['Symbol'] = stock_symbol

    stock_df['Close'] = round(stock_df['Close'],2)
    stock_df['Min'] = round(min(stock_df['Close']),2)
    stock_df['RSI_14'] = ta.momentum.RSIIndicator(close=stock_df['Close'], window=14).rsi()
    stock_df['RSI_14'] = round(stock_df['RSI_14'],0)
    stock_df['Prev_Close'] = stock_df['Close'].shift(1)
    stock_df.drop(['Open', 'Low', 'High', 'Volume'], axis=1, inplace=True)
    stock_df = stock_df.tail(1)

    max_SMA = max(stock_df['20_SMA'].item(), stock_df['50_SMA'].item(), stock_df['200_SMA'].item())
    min_SMA = min(stock_df['20_SMA'].item(), stock_df['50_SMA'].item(), stock_df['200_SMA'].item())
    ABS_Spread = max_SMA - min_SMA
    stock_df['Spread%'] = round((ABS_Spread / stock_df['200_SMA'].item()) * 100,2)

    return stock_df

# function to compute stock attributes
def get_common_features(stock_ids, df_mypf):

  df_prec_dev = pd.DataFrame()
  df_tmp = get_screener_features()
  df_rs = get_relative_strength(stock_ids)

  for stock_id in stock_ids:
      tmp = stock_prec_dev(stock_id)
      tmp = tmp.reset_index()
      df_prec_dev = pd.concat([df_prec_dev, tmp], ignore_index = True)
  df_prec_dev = pd.merge(df_prec_dev, df_mypf, on= 'Symbol')
  df_prec_dev = pd.merge(df_prec_dev, df_tmp, on= 'Symbol', how='left')
  df_prec_dev = pd.merge(df_prec_dev, df_rs, on= 'Symbol', how='left')
  #print(df_prec_dev.columns)
  df_prec_dev['Curr_PE'] = round(df_prec_dev['Close']/df_prec_dev['EPS'],1)
  df_prec_dev['Dev%_PE'] = round((df_prec_dev['Curr_PE'] - df_prec_dev['MedPE'])*100/df_prec_dev['MedPE'],2)
  df_prec_dev['Conviction'] = df_prec_dev['Conviction'] + '-' + df_prec_dev['CapType']
  return df_prec_dev

# function to arrange stock features
def arrange_features(df_stocks, common_cols, diff_cols):
  df_stocks_common = df_stocks[common_cols].drop_duplicates()
  df_stocks_diff = df_stocks[diff_cols]
  df_stocks_diff['Investment'] = df_stocks_diff['AvgCost'] * df_stocks_diff['Shares']
  df_stocks_diff = df_stocks_diff.groupby(['Symbol'])[['Shares', 'Investment']].aggregate(['sum']).reset_index()
  df_stocks_diff.columns = ['Symbol', 'Shares', 'Investment']
  df_stocks_diff['AvgCost'] = round(df_stocks_diff['Investment']/df_stocks_diff['Shares'],2)
  df_stocks = pd.merge(df_stocks_diff, df_stocks_common, on='Symbol')
  return df_stocks

# plot fact distribution across dimension
def plot_pie_chart(df, dimension, fact):
  # grouping the data by category and calculating the sum of fact for each type
  grouped_data = df.groupby(dimension)[fact].sum()

  # sorting the grouped data in descending order
  grouped_data = grouped_data.sort_values(ascending=False)

  # creating a pie chart
  grouped_data.plot.pie(autopct='%1.1f%%', startangle=90, figsize=(6, 6))

  # adding a title and displaying the plot
  plt.title(f'{dimension} {fact} Distribution')
  plt.ylabel('')  # To hide the y-label
  plt.show()

In [7]:
# function to get portfolio features

def get_portfolio_features(df_common_features):

  print_date_time()
  print('-------------------')

  #df_common_features["Target"] = df_common_features["Target"].fillna(df_common_features["Max"])
  df_common_features['NTT'] = np.where(df_common_features['Strategy']== 'NTT', df_common_features["Target"], df_common_features['Max'])
  df_common_features['LTT'] = np.where(df_common_features['Strategy']== 'BTT', df_common_features["Target"], df_common_features['Max'])
  df_common_features['BOL'] = df_common_features['Min']

  tmp_df = df_common_features[df_common_features['Symbol'].isin(mypf_df[mypf_df['InPortfolio'] != 'NA'].Symbol.values)]
  print('qualified stocks: '+str(len(tmp_df['Symbol'].unique())))
  tmp_df1 = tmp_df[tmp_df['LatestQtr'] == 1]
  print('with latest results: '+str(len(tmp_df1['Symbol'].unique())))
  tmp_df1 = tmp_df1[tmp_df1['StarStock'] == 1]
  print('still star stocks: '+str(len(tmp_df1['Symbol'].unique())))
  tmp_df['Investment'] = tmp_df['AvgCost'] * tmp_df['Shares']
  tmp_df['Current'] = round(tmp_df['Close'] * tmp_df['Shares'],0)
  tmp_df['Previous'] = tmp_df['Prev_Close'] * tmp_df['Shares']
  tmp_df['EstimatedST'] = tmp_df['NTT'] * tmp_df['Shares']
  tmp_df['EstimatedLT'] = tmp_df['LTT'] * tmp_df['Shares']
  tmp_df['Current P/L'] = round((tmp_df['Current'] - tmp_df['Investment']),0)
  tmp_df['Today P/L%'] = round((tmp_df['Current'] - tmp_df['Previous'])*100/tmp_df['Previous'],2)
  tmp_df['Current P/L%'] = round((tmp_df['Current'] - tmp_df['Investment'])*100/tmp_df['Investment'],2)
  tmp_df['EstimatedST P/L%'] = round((tmp_df['EstimatedST'] - tmp_df['Investment'])*100/tmp_df['Investment'],2)
  tmp_df['EstimatedLT P/L%'] = round((tmp_df['EstimatedLT'] - tmp_df['Investment'])*100/tmp_df['Investment'],2)
  tmp_df['NTT%'] = round((tmp_df['NTT'] - tmp_df['Close'])*100/tmp_df['Close'],2)
  tmp_df['LTT%'] = round((tmp_df['LTT'] - tmp_df['Close'])*100/tmp_df['Close'],2)
  tmp_df['Gained%'] = round((tmp_df['Close'] - tmp_df['BOL'])*100/tmp_df['BOL'],2)
  investment = round(sum(tmp_df['AvgCost']*tmp_df['Shares']),0)
  current = round(sum(tmp_df['Close']*tmp_df['Shares']),0)
  tmp_df['InitAlloc%'] = round(tmp_df['Investment']*100/investment,2)
  tmp_df['CurrAlloc%'] = round(tmp_df['Current']*100/current,2)
  tmp_df['FTT'] = tmp_df['LTT']
  tmp_df.loc[tmp_df['Strategy'] == 'NTT', 'FTT'] = tmp_df['NTT']
  tmp_df['FTT%'] = tmp_df['LTT%']
  tmp_df.loc[tmp_df['Strategy'] == 'NTT', 'FTT%'] = tmp_df['NTT%']
  tmp_df['FTT Amt'] = round(tmp_df['FTT%'] * tmp_df['Current']/100,0)
  tmp_df['OTT%'] = round((tmp_df['FTT'] - tmp_df['AvgCost'])*100/tmp_df['AvgCost'],2)
  tmp_df['RRR Ind'] = round(tmp_df['Current P/L']/tmp_df['FTT Amt'],2)
  tmp_df['Risk Ind'] = round(tmp_df['Current P/L%']*tmp_df['CurrAlloc%'],0)

  return tmp_df

# function to print portfolio features
def print_portfolio_stats(df_portfolio_features, myinvmt_df):
  from pyxirr import xirr

  total_booked_amt, reserve_amt, cy_booked_amt, py_booked_amt = get_amt()

  dates = myinvmt_df['Date'].values
  dates = np.append(dates, datetime.date.today().strftime('%d-%b-%y'))
  investment = myinvmt_df['Investment'].values
  dates= pd.to_datetime(dates)

  current = round(sum(df_portfolio_features['Close']*df_portfolio_features['Shares']),0) + reserve_amt
  investment_xirr = np.append(investment, current)
  cagr = round(xirr(pd.DataFrame({"dates": dates, "amounts": investment_xirr}))*100,2)

  investment = -sum(investment)
  invested = round(sum(df_portfolio_features['AvgCost']*df_portfolio_features['Shares']),0) + reserve_amt
  previous = round(sum(df_portfolio_features['Prev_Close']*df_portfolio_features['Shares']),0) + reserve_amt
  cy_invested = investment + py_booked_amt

  today_pnl_amount = current-previous
  today_pnl_percentage = round((current-previous)*100/previous,2)

  curr_pnl_amount = current-invested
  curr_pnl_percentage = round((curr_pnl_amount)*100/(cy_invested),2)

  cy_pnl_amount = cy_booked_amt + curr_pnl_amount
  cy_pnl_percentage = round((cy_pnl_amount)*100/cy_invested,2)

  overall_pnl_amount = total_booked_amt + curr_pnl_amount
  overall_pnl_percentage = round((overall_pnl_amount)*100/investment,2)

  estimate_st = round(sum(df_portfolio_features['FTT']*df_portfolio_features['Shares']),0)  + reserve_amt
  est_st_pnl_amount = estimate_st-current
  est_st_pnl_percentage = round((est_st_pnl_amount)*100/current,2)

  estimate_lt = round(sum(df_portfolio_features['LTT']*df_portfolio_features['Shares']),0)  + reserve_amt
  est_lt_pnl_amount = estimate_lt-current
  est_lt_pnl_percentage = round((est_lt_pnl_amount)*100/current,2)

  total_profit = round(sum(df_portfolio_features[df_portfolio_features['Current P/L%'] > 0]['Current']) - sum(df_portfolio_features[df_portfolio_features['Current P/L%'] > 0]['Investment']),0)
  total_loss = round(sum(df_portfolio_features[df_portfolio_features['Current P/L%'] < 0]['Current']) - sum(df_portfolio_features[df_portfolio_features['Current P/L%'] < 0]['Investment']),0)

  cy_booked_percentage = round((cy_booked_amt)*100/current,2)
  py_booked_percentage = round((py_booked_amt)*100/investment,2)
  total_booked_percentage = round((total_booked_amt)*100/investment,2)

  print('-------------------')
  print('Initial Investment: ', format_amt(investment))
  print('CY Investment: ', format_amt(cy_invested))
  print('Reserve: ', format_amt(reserve_amt))
  print('Current: ',  format_amt(current))
  print('-------------------')
  print('Today PnL: '+ '{} ({}%)'.format(format_amt(today_pnl_amount), today_pnl_percentage))
  print('Current PnL: '+ '{} ({}%)'.format(format_amt(curr_pnl_amount), curr_pnl_percentage))
  print('CY Booked + Current PnL: '+ '{} ({}%)'.format(format_amt(cy_pnl_amount), cy_pnl_percentage))
  print('-------------------')
  print('Total profit: ', format_amt(total_profit))
  print('Total loss: ', format_amt(total_loss))
  print('-------------------')
  print('Total Booked + Current PnL: '+ '{} ({}%)'.format(format_amt(overall_pnl_amount), overall_pnl_percentage))
  print('Total Booked PnL: '+ '{} ({}%)'.format(format_amt(total_booked_amt), total_booked_percentage))
  print('Curr Year Booked PnL: '+ '{} ({}%)'.format(format_amt(cy_booked_amt), cy_booked_percentage))
  print('Prev Year Booked PnL: '+ '{} ({}%)'.format(format_amt(py_booked_amt), py_booked_percentage))
  print('===================')
  print('Est FTT: ',  format_amt(estimate_st))
  print('Est FTT PnL: '+ '{} ({}%)'.format(format_amt(est_st_pnl_amount), est_st_pnl_percentage))

  print('===================')
  print('Deployed: ', format_amt(investment))

  print('Current: ', format_amt(current))

  print('CAGR/XIRR %: '+'{}%'.format(cagr))

In [8]:
# get start and end date
start_date, end_date = get_start_end_date()

# get portfolio and prospects data
mypfs_df = get_mypfs_df()
mypps_df = get_mypps_df()
myinvmt_df = get_myinvmt_df()

# merge above datasets
mypf_df = pd.merge(mypfs_df, mypps_df, on="Symbol")

# seggregate dm and sv portfolio
dm_pf = mypf_df[mypf_df['InPortfolio'] == 'DM']
sv_pf = mypf_df[mypf_df['InPortfolio'] == 'SV']

# build portfolio stock dataframe
dm_stocks = get_stock_ids(dm_pf)
sv_stocks = get_stock_ids(sv_pf)
df_stocks = pd.concat([dm_pf,sv_pf], ignore_index = True)

# arrange common and diff stock features
common_cols = ['Symbol', 'Target', 'Criteria', 'Strategy', 'CumlRnk', 'LatestQtr', 'StarStock', 'Conviction', 'Category', 'InFolio', 'XIRR', 'MBQ']
diff_cols = ['Symbol', 'AvgCost', 'Shares']
df_stocks = arrange_features(df_stocks, common_cols, diff_cols)

# get common features
stock_ids = df_stocks['Symbol'].values
df_common_features = get_common_features(stock_ids, df_stocks)

df_common_features.reset_index(drop=True, inplace=True)
df_common_features.drop(['Date'], axis=1, inplace=True)
# get and print portfolio features
df_portfolio_features = get_portfolio_features(df_common_features)

print_portfolio_stats(df_portfolio_features, myinvmt_df)

df = df_portfolio_features
#plot_pie_chart(df, 'CapType', 'Current')
list_ox40n = list(df[df['MBQ'].str.contains('OX40N', na=False)]['Symbol'].values)

Run date time (IST): 2026-04-07 11:39:23
-------------------
qualified stocks: 86
with latest results: 26
still star stocks: 16
-------------------
Initial Investment:  1.36 C
CY Investment:  1.62 C
Reserve:  1.61 K
Current:  1.31 C
-------------------
Today PnL: 37.41 K (0.29%)
Current PnL: -45.83 L (-28.2%)
CY Booked + Current PnL: -29.94 L (-18.43%)
-------------------
Total profit:  65.90 K
Total loss:  -46.49 L
-------------------
Total Booked + Current PnL: -2.96 L (-2.18%)
Total Booked PnL: 42.87 L (31.64%)
Curr Year Booked PnL: 15.89 L (12.1%)
Prev Year Booked PnL: 26.98 L (19.91%)
===================
Est FTT:  2.48 C
Est FTT PnL: 1.17 C (88.8%)
===================
Deployed:  1.36 C
Current:  1.31 C
CAGR/XIRR %: -1.52%

In [9]:
# top 5 near their targets
cols = ['Symbol', 'Today P/L%', 'Current P/L%', 'FTT%', 'OTT%', 'FTT Amt', 'Current P/L', 'Current', 'FTT', 'Dev%_PE', 'RSI_14','Conviction', 'Spread%',  'CumlRnk', 'RRR Ind', 'CurrAlloc%', 'Gained%', 'Criteria', 'Strategy', 'Category']
df_tmp = df_portfolio_features[~df_portfolio_features['Symbol'].isin(['ENRIN','BLUSPRING','DIGITIDE'])]
df_tmp = df_tmp.sort_values(by = 'FTT Amt', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
50,MASFIN,-0.35,-7.50,31.43,21.57,28485.0,-7350.0,90630.0,397.04,-20.05,49.0,H-SC,4.91,167.0,-0.26,0.69,23.61,XR,ATH,FINANCE
77,TTKPRESTIG,3.28,-38.77,63.48,0.09,39168.0,-39076.0,61701.0,770.00,43.22,46.0,M-SC,22.37,250.0,-1.00,0.47,9.87,OX40N,NTT,DURABLES
67,SONACOMS,0.80,-11.17,56.58,39.09,50844.0,-11297.0,89862.0,804.02,-29.65,53.0,M-MC,7.30,193.0,-0.22,0.68,27.13,AR,ATH,AUTO
24,DMART,-0.25,9.13,18.76,29.60,51099.0,22782.0,272382.0,5391.45,-8.00,77.0,X-LC,5.63,14.0,0.45,2.07,24.50,X40N,ATH,FMCG
2,ABBOTINDIA,-0.06,-13.18,35.99,18.07,55885.0,-23575.0,155280.0,35195.00,-26.09,43.0,X-MC,10.89,58.0,-0.42,1.18,1.55,X40,ATH,PHARMA

In [10]:
# top 5 today
df_tmp = df_portfolio_features.sort_values(by = 'Today P/L%', ascending=False)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
74,TITAGARH,11.65,-32.79,116.85,45.74,190183.0,-79419.0,162758.0,1548.0,-10.49,60.0,H-SC,23.36,175.0,-0.42,1.24,24.18,XY24,NTT,ENGINEERING
55,RAJESHEXPO,5.00,-81.42,438.46,0.07,111777.0,-111684.0,25493.0,518.0,834.34,38.0,L-SC,44.02,268.0,-1.00,0.19,19.68,OX40N,NTT,JEWELLERY
0,5PAISA,4.87,-44.01,101.66,12.90,124360.0,-96167.0,122329.0,593.0,80.29,50.0,H-SC,16.76,170.0,-0.77,0.93,18.05,OX40N,NTT,FINANCE
84,WIPRO,3.30,-16.41,106.08,72.27,150253.0,-27807.0,141641.0,420.0,-24.55,56.0,M-LC,17.95,98.0,-0.19,1.08,8.67,XR,NTT,IT
77,TTKPRESTIG,3.28,-38.77,63.48,0.09,39168.0,-39076.0,61701.0,770.0,43.22,46.0,M-SC,22.37,250.0,-1.00,0.47,9.87,OX40N,NTT,DURABLES

In [11]:
# bottom 5 today
df_tmp = df_portfolio_features.sort_values(by = 'Today P/L%', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
69,SURYODAY,-2.43,-26.66,67.77,23.03,88999.0,-47746.0,131325.0,216.0,42.54,51.0,H-SC,5.36,166.0,-0.54,1.00,18.83,XR,NTT,BANKS
11,BANDHANBNK,-2.34,-28.32,168.44,92.42,336329.0,-78886.0,199673.0,400.0,70.98,41.0,H-SC,1.48,174.0,-0.23,1.52,9.99,XY24,NTT,BANKS
82,VOLTAS,-2.29,-4.30,51.72,45.20,94904.0,-8247.0,183495.0,1856.0,9.62,34.0,X-MC,4.26,79.0,-0.09,1.40,2.20,XY25,NTT,AC
47,JSWINFRA,-1.71,-20.15,45.81,16.43,81123.0,-44689.0,177085.0,342.0,-31.54,38.0,X-MC,12.20,61.0,-0.55,1.35,0.00,X40N,NTT,REALTY
3,ACC,-1.70,-40.07,191.71,74.81,308040.0,-107448.0,160680.0,3906.0,-57.46,39.0,X-SC,21.88,85.0,-0.35,1.22,6.73,XY24,BTT,CEMENT

In [12]:
# top 5 to exit based on CumlRnk
df_tmp = df_portfolio_features[~df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])]
df_tmp = df_tmp[(df_tmp['Current P/L%'] > -1) & (df_tmp['Current P/L%'] < 1)].sort_values(by = 'CumlRnk', ascending=False)
df_tmp[cols].head()

Empty DataFrame
Columns: [Symbol, Today P/L%, Current P/L%, FTT%, OTT%, FTT Amt, Current P/L, Current, FTT, Dev%_PE, RSI_14, Conviction, Spread%, CumlRnk, RRR Ind, CurrAlloc%, Gained%, Criteria, Strategy, Category]
Index: []

In [13]:
# OX40N stocks to exit
df_tmp = df_portfolio_features[(df_portfolio_features['Symbol'].isin(list_ox40n))].sort_values(by = 'Current P/L%', ascending=False)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
26,FINCABLES,-0.28,2.21,103.43,107.91,156076.0,3256.0,150900.0,1641.55,-8.17,45.0,M-SC,4.17,220.0,0.02,1.15,13.53,OX40N,ATH,CABLES
66,SIS,0.02,-33.60,82.64,21.26,60922.0,-37312.0,73720.0,528.00,1726.94,49.0,H-SC,14.91,168.0,-0.61,0.56,9.61,OX40N,NTT,MISC
72,TATAELXSI,2.26,-37.03,109.68,32.03,91046.0,-48824.0,83011.0,9161.00,-21.20,50.0,H-SC,21.56,158.0,-0.54,0.63,9.87,OX40N,NTT,IT
18,CERA,0.08,-37.34,97.70,23.89,107693.0,-65675.0,110228.0,9475.00,-39.62,51.0,H-SC,18.97,153.0,-0.61,0.84,5.93,OX40N,NTT,CERAMICS
77,TTKPRESTIG,3.28,-38.77,63.48,0.09,39168.0,-39076.0,61701.0,770.00,43.22,46.0,M-SC,22.37,250.0,-1.00,0.47,9.87,OX40N,NTT,DURABLES

In [14]:
# top 5 to book for rotation
df_tmp = df_portfolio_features[(df_portfolio_features['Current P/L%'] > 20) ].sort_values(by = 'CumlRnk', ascending=False)
df_tmp[cols].head()

Empty DataFrame
Columns: [Symbol, Today P/L%, Current P/L%, FTT%, OTT%, FTT Amt, Current P/L, Current, FTT, Dev%_PE, RSI_14, Conviction, Spread%, CumlRnk, RRR Ind, CurrAlloc%, Gained%, Criteria, Strategy, Category]
Index: []

In [15]:
# top 5 to monitor for exit
df_tmp = df_portfolio_features[~df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])]
df_tmp = df_tmp[(df_tmp['Current P/L%'] > 0) ].sort_values(by = 'Dev%_PE', ascending=False)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
26,FINCABLES,-0.28,2.21,103.43,107.91,156076.0,3256.0,150900.0,1641.55,-8.17,45.0,M-SC,4.17,220.0,0.02,1.15,13.53,OX40N,ATH,CABLES
1,ABB,0.16,13.82,27.90,45.57,83077.0,36149.0,297768.0,7934.00,-26.88,55.0,H-MC,13.88,125.0,0.44,2.27,32.23,AR,NTT,ELECTRICAL

In [16]:
# top 5 to book for rotation from weak conviction
df_tmp = df_portfolio_features[~df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])]
df_tmp = df_tmp[~df_tmp['Criteria'].isin(['XY25','XY24','X40', 'X40N'])].sort_values(by = 'RRR Ind', ascending=False)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
1,ABB,0.16,13.82,27.90,45.57,83077.0,36149.0,297768.0,7934.00,-26.88,55.0,H-MC,13.88,125.0,0.44,2.27,32.23,AR,NTT,ELECTRICAL
26,FINCABLES,-0.28,2.21,103.43,107.91,156076.0,3256.0,150900.0,1641.55,-8.17,45.0,M-SC,4.17,220.0,0.02,1.15,13.53,OX40N,ATH,CABLES
40,INDIAMART,-0.81,-11.87,134.56,106.72,146264.0,-14638.0,108698.0,4810.62,-60.16,47.0,H-SC,12.83,140.0,-0.10,0.83,8.73,AR,ATH,MISC
85,ZYDUSLIFE,0.75,-7.96,47.36,35.63,91352.0,-16685.0,192889.0,1286.17,-19.82,44.0,H-MC,5.93,120.0,-0.18,1.47,7.38,AR,ATH,PHARMA
84,WIPRO,3.30,-16.41,106.08,72.27,150253.0,-27807.0,141641.0,420.00,-24.55,56.0,M-LC,17.95,98.0,-0.19,1.08,8.67,XR,NTT,IT

In [17]:
# top 5 to accumulate based on lowest RSI_14
df_tmp = df_portfolio_features[df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])].sort_values(by = 'RSI_14', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
38,ICICIPRULI,-0.14,-15.21,54.18,30.73,90503.0,-29963.0,167042.0,790.00,-37.99,25.0,X-MC,10.40,78.0,-0.33,1.27,1.79,X40,ATH,INSURANCE
21,DABUR,0.07,-19.06,77.54,43.70,155693.0,-47278.0,200790.0,735.00,-26.49,30.0,X-MC,12.40,70.0,-0.30,1.53,0.86,XY24,BTT,FMCG
59,RELIANCE,-0.71,-16.85,50.69,25.30,84707.0,-33856.0,167107.0,1952.00,-18.88,32.0,X-LC,4.28,21.0,-0.40,1.27,11.57,XY25,BTT,REFINERIES
37,ICICIGI,-0.39,-9.62,32.04,19.34,57950.0,-19241.0,180868.0,2252.93,-24.00,33.0,X-MC,6.68,66.0,-0.33,1.38,1.02,X40,ATH,INSURANCE
82,VOLTAS,-2.29,-4.30,51.72,45.20,94904.0,-8247.0,183495.0,1856.00,9.62,34.0,X-MC,4.26,79.0,-0.09,1.40,2.20,XY25,NTT,AC

In [18]:
# top 5 to accumulate based on Spread and CumlRnk
df_tmp = df_portfolio_features[df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])]
df_tmp = df_tmp[(df_tmp['CumlRnk'] < 100)].sort_values(by = 'Spread%', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
65,SIEMENS,0.21,-17.94,52.95,25.51,80863.0,-33380.0,152715.0,4671.50,28.36,46.0,H-LC,0.71,51.0,-0.41,1.16,12.46,AR,ATH,ELECTRICAL
78,UNITDSPR,-1.32,-10.38,34.75,20.77,72919.0,-24304.0,209840.0,1644.00,-20.49,37.0,X-MC,4.21,64.0,-0.33,1.60,0.10,X40N,NTT,BREWERIES
82,VOLTAS,-2.29,-4.30,51.72,45.20,94904.0,-8247.0,183495.0,1856.00,9.62,34.0,X-MC,4.26,79.0,-0.09,1.40,2.20,XY25,NTT,AC
59,RELIANCE,-0.71,-16.85,50.69,25.30,84707.0,-33856.0,167107.0,1952.00,-18.88,32.0,X-LC,4.28,21.0,-0.40,1.27,11.57,XY25,BTT,REFINERIES
24,DMART,-0.25,9.13,18.76,29.60,51099.0,22782.0,272382.0,5391.45,-8.00,77.0,X-LC,5.63,14.0,0.45,2.07,24.50,X40N,ATH,FMCG

In [19]:
# top 5 to accumulate based on lowest Gained%
df_tmp = df_portfolio_features[df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])].sort_values(by = 'Gained%', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
47,JSWINFRA,-1.71,-20.15,45.81,16.43,81123.0,-44689.0,177085.0,342.00,-31.54,38.0,X-MC,12.20,61.0,-0.55,1.35,0.00,X40N,NTT,REALTY
78,UNITDSPR,-1.32,-10.38,34.75,20.77,72919.0,-24304.0,209840.0,1644.00,-20.49,37.0,X-MC,4.21,64.0,-0.33,1.60,0.10,X40N,NTT,BREWERIES
35,HINDUNILVR,-0.92,-19.65,41.46,13.67,85640.0,-50503.0,206560.0,2922.00,-40.44,36.0,X-LC,11.67,9.0,-0.59,1.57,0.65,XY25,NTT,FMCG
21,DABUR,0.07,-19.06,77.54,43.70,155693.0,-47278.0,200790.0,735.00,-26.49,30.0,X-MC,12.40,70.0,-0.30,1.53,0.86,XY24,BTT,FMCG
37,ICICIGI,-0.39,-9.62,32.04,19.34,57950.0,-19241.0,180868.0,2252.93,-24.00,33.0,X-MC,6.68,66.0,-0.33,1.38,1.02,X40,ATH,INSURANCE

In [20]:
# top 5 to accumulate based on lowest CurrAlloc%
df_tmp = df_portfolio_features[df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])].sort_values(by = 'CurrAlloc%', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
58,RELAXO,3.25,-63.47,316.99,52.31,168068.0,-92140.0,53020.0,1176.00,-61.09,45.0,X-SC,32.20,92.0,-0.55,0.40,18.55,X40N,NTT,FOOTWEAR
12,BATAINDIA,0.41,-56.83,213.19,35.20,118423.0,-73122.0,55548.0,2096.00,-27.22,43.0,X-SC,34.36,91.0,-0.62,0.42,10.16,X40,NTT,FOOTWEAR
54,QUESS,1.90,-25.51,133.45,73.90,106159.0,-27243.0,79550.0,424.00,-59.78,48.0,X-SC,22.42,80.0,-0.26,0.61,7.01,XY24,NTT,MISC
36,HONAUT,-0.53,-29.11,113.45,51.31,155086.0,-56138.0,136700.0,58357.33,-41.12,38.0,X-SC,18.47,90.0,-0.36,1.04,3.86,X40N,ATH,ELECTRICAL
65,SIEMENS,0.21,-17.94,52.95,25.51,80863.0,-33380.0,152715.0,4671.50,28.36,46.0,H-LC,0.71,51.0,-0.41,1.16,12.46,AR,ATH,ELECTRICAL

In [21]:
# top 5 to accumulate based on CumlRnk
df_tmp = df_portfolio_features.sort_values(by = 'CumlRnk', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
45,ITC,0.73,-21.77,52.19,19.06,138884.0,-74054.0,266112.0,452.00,-57.14,43.0,X-LC,19.70,1.0,-0.53,2.03,3.23,X40,NTT,FMCG
73,TCS,2.55,-25.53,69.96,26.57,241375.0,-118255.0,345018.0,4311.59,-37.07,53.0,X-LC,18.62,2.0,-0.49,2.63,7.68,X40,ATH,IT
43,INFY,2.24,-9.09,47.66,34.24,135575.0,-28426.0,284462.0,1972.00,-28.52,56.0,X-LC,14.75,3.0,-0.21,2.17,9.40,X40,NTT,IT
75,TMPV,-0.67,-30.49,96.50,36.58,238677.0,-108507.0,247334.0,600.00,-85.81,38.0,X-LC,12.48,4.0,-0.45,1.88,3.09,XY24,NTT,AUTO
33,HCLTECH,2.56,-6.60,32.59,23.83,73638.0,-15970.0,225954.0,1908.19,-1.99,59.0,X-LC,10.94,8.0,-0.22,1.72,9.71,X40,ATH,IT

In [22]:
# top 5 for average up
df_tmp = df_portfolio_features[(df_portfolio_features['Dev%_200'] > 5)].sort_values(by = 'CurrAlloc%', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
67,SONACOMS,0.80,-11.17,56.58,39.09,50844.0,-11297.0,89862.0,804.02,-29.65,53.0,M-MC,7.30,193.0,-0.22,0.68,27.13,AR,ATH,AUTO
24,DMART,-0.25,9.13,18.76,29.60,51099.0,22782.0,272382.0,5391.45,-8.00,77.0,X-LC,5.63,14.0,0.45,2.07,24.50,X40N,ATH,FMCG
1,ABB,0.16,13.82,27.90,45.57,83077.0,36149.0,297768.0,7934.00,-26.88,55.0,H-MC,13.88,125.0,0.44,2.27,32.23,AR,NTT,ELECTRICAL

In [23]:
# top 5 RSP
df_tmp = df_portfolio_features.sort_values(by = 'RSP', ascending=False)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
24,DMART,-0.25,9.13,18.76,29.60,51099.0,22782.0,272382.0,5391.45,-8.00,77.0,X-LC,5.63,14.0,0.45,2.07,24.50,X40N,ATH,FMCG
80,VALIANTORG,0.02,-50.33,250.61,74.15,203653.0,-82342.0,81263.0,838.00,-245.98,53.0,H-SC,26.47,145.0,-0.40,0.62,20.93,XR,NTT,CHEMICALS
5,ANGELONE,0.37,1.22,22.69,24.18,70047.0,3712.0,308712.0,303.00,-85.37,58.0,X-SC,8.59,97.0,0.05,2.35,18.83,X40N,NTT,FINANCE
30,HAPPSTMNDS,-0.26,-52.01,285.20,84.85,175409.0,-66661.0,61504.0,1480.71,-42.90,50.0,H-SC,23.21,152.0,-0.38,0.47,13.90,AR,ATH,IT
52,PAGEIND,-0.19,-9.53,48.24,34.11,117124.0,-25584.0,242795.0,51418.64,-35.18,65.0,X-MC,19.20,55.0,-0.22,1.85,14.85,X40,ATH,APPARELS

In [24]:
# Top N allocation
df_tmp = df_portfolio_features.sort_values(by = 'CurrAlloc%', ascending=False)
top_n_values = [10, 25, 50]

sum_df = pd.DataFrame({
    'Top_N': top_n_values,
    'Sum_Alloc%': [df_tmp['CurrAlloc%'].head(n).sum() for n in top_n_values]
})

sum_df

   Top_N  Sum_Alloc%
0     10       21.22
1     25       46.20
2     50       77.97

In [25]:
# market-cap-wise allocation
df_tmp = df_portfolio_features[cols]
df_tmp.groupby(df_tmp['Conviction'].str[-2:])['CurrAlloc%'].sum().sort_values(ascending=False)

Conviction
SC    44.76
MC    29.43
LC    25.81
Name: CurrAlloc%, dtype: float64

In [26]:
# criteria-wise allocation
df_portfolio_features.groupby('Criteria')['CurrAlloc%'].sum().sort_values(ascending=False)

Criteria
XY24     27.10
X40      25.43
X40N     15.37
AR        9.16
XR        8.42
XY25      7.02
OX40N     6.70
SR        0.80
Name: CurrAlloc%, dtype: float64

In [27]:
# conviction-wise allocation
df_portfolio_features.groupby('Conviction')['CurrAlloc%'].sum().sort_values(ascending=False)

Conviction
X-LC    23.57
H-SC    22.04
X-MC    22.01
X-SC    12.28
M-SC     9.90
H-MC     5.02
M-MC     2.06
H-LC     1.16
M-LC     1.08
L-SC     0.54
L-MC     0.34
Name: CurrAlloc%, dtype: float64

In [28]:
# sector-wise stats
df_tmp = df_portfolio_features.groupby('Category')[['CurrAlloc%', 'Current', 'Current P/L', 'FTT Amt']].sum().sort_values(by=['Current', 'Current P/L'], ascending=False)
df_tmp['Current P/L%'] = round(df_tmp['Current P/L'] * 100 / df_tmp['Current'], 2)
df_tmp['FTT%'] = round(df_tmp['FTT Amt'] * 100 / df_tmp['Current'], 2)
cols = ['CurrAlloc%', 'Current P/L%', 'FTT%']
df_tmp[cols].sort_values(by=['CurrAlloc%'], ascending=False)

               CurrAlloc%  Current P/L%    FTT%
Category
FMCG                15.12        -25.75   70.40
FINANCE             13.26        -23.48   73.80
IT                  12.23        -40.38  111.82
MISC                 7.07        -44.55  107.35
ELECTRICAL           6.42        -14.85   58.82
PAINTS               5.20        -44.49   69.58
INSURANCE            4.57        -13.00   51.68
BANKS                4.50        -30.25   96.37
PHARMA               4.07         -9.97   44.58
AUTO                 3.63        -37.08   91.48
HEALTHCARE           1.95        -39.58   76.01
AC                   1.89        -28.79   63.71
APPARELS             1.85        -10.54   48.24
FOOTWEAR             1.83        -83.02  156.41
TRAVEL               1.78        -91.75  187.76
DURABLES             1.76        -68.00  108.87
BREWERIES            1.60        -11.58   34.75
CERAMICS             1.38        -69.69  121.24
REALTY               1.35        -25.24   45.81
REFINERIES           1.27        -20.26   50.69
ENGINEERING          1.24        -48.80  116.85
CEMENT               1.22        -66.87  191.71
CABLES               1.15          2.16  103.43
CHEMICALS            1.06        -90.98  246.78
JEWELLERY            1.02       -138.09  220.81
ENTERTAINMENT        0.78        -89.83  203.04
TEXTILES             0.45        -54.72   98.84
HOTELS               0.35       -150.70  239.13

In [29]:
# money to be made criteria-wise
df_portfolio_features.groupby('Criteria')['FTT Amt'].agg(['sum', 'count']).sort_values(by='sum', ascending=False)

                sum  count
Criteria
XY24      4041100.0     21
X40       1835034.0     16
XR        1387558.0     12
AR        1369476.0     10
X40N      1281852.0     10
OX40N      911114.0     10
XY25       518151.0      5
SR         314414.0      2

In [30]:
# money to be made conviction-wise
df_portfolio_features.groupby('Conviction')['FTT Amt'].agg(['sum', 'count']).sort_values(by='sum', ascending=False)

                  sum  count
Conviction
H-SC        3901543.0     24
X-MC        1845190.0     15
X-LC        1681422.0     13
M-SC        1618695.0     14
X-SC        1566738.0     10
H-MC         420699.0      3
L-SC         220086.0      2
M-LC         150253.0      1
M-MC         114952.0      2
H-LC          80863.0      1
L-MC          58258.0      1

In [31]:
# money to be made criteria and conviction-wise
df_portfolio_features.groupby(['Conviction', 'Criteria'])['FTT Amt'].agg(['sum', 'count']).sort_values(by='sum', ascending=False)

                           sum  count
Conviction Criteria
H-SC       XY24      1341498.0      6
           AR         984027.0      5
M-SC       XY24       930911.0      6
X-LC       X40        897101.0      7
H-SC       XR         877583.0      7
X-SC       XY24       858483.0      4
X-MC       X40        716593.0      7
           X40N       570911.0      4
X-SC       X40N       486915.0      4
M-SC       OX40N      415316.0      5
X-LC       XY24       389948.0      2
H-SC       OX40N      384021.0      4
           SR         314414.0      2
X-MC       XY25       283696.0      2
           XY24       273990.0      2
H-MC       XY24       246270.0      1
X-LC       X40N       224026.0      2
X-SC       X40        221340.0      2
M-SC       XR         193155.0      2
H-MC       AR         174429.0      2
X-LC       XY25       170347.0      2
M-LC       XR         150253.0      1
L-SC       OX40N      111777.0      1
           XR         108309.0      1
H-LC       AR          80863.0      1
M-SC       AR          79313.0      1
M-MC       XY25        64108.0      1
L-MC       XR          58258.0      1
M-MC       AR          50844.0      1

In [32]:
# notebook execution time

end_time = time.time()
execution_time = round(end_time - start_time, 0)
print(f"Notebook execution time: {execution_time} seconds")

Notebook execution time: 23.0 seconds