<a href="https://colab.research.google.com/github/ankit-rathi/Quantvesting_v2/blob/main/myStocks_Portfolio_Analysis.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
'''
!pip install pandas==2.2.2 -qq
!pip install pyxirr -qq
!pip install ta -qq
!pip install yfinance==0.2.59 -qq
'''

'\n!pip install pandas==2.2.2 -qq\n!pip install pyxirr -qq\n!pip install ta -qq\n!pip install yfinance==0.2.59 -qq\n'

In [2]:
# import libraries

import numpy as np
import pandas as pd
import datetime
import warnings
warnings.filterwarnings('ignore')
import yfinance as yfin
import ta
import matplotlib.pyplot as plt
import requests

In [3]:
# notebook start time
import time
import datetime
import pytz

start_time = time.time()

# function to print date timestamp
def print_date_time():
  tz_NY = pytz.timezone('Asia/Kolkata')
  datetime_NY = datetime.datetime.now(tz_NY)
  print("Run date time (IST):", datetime_NY.strftime("%Y-%m-%d %H:%M:%S"))

In [4]:
# function to get booked and reserved amount
def get_amt():
  # fetch the JSON data from the URL
  url = "https://raw.githubusercontent.com/ankit-rathi/Tradevesting_v1/main/data/myPortfolioAmts.json"
  response = requests.get(url)
  pf_amts = response.json()  # parse the JSON data

  # extract values from the JSON
  py_booked_amt_dm = pf_amts["py_booked_amt_dm"]
  py_booked_amt_sv = pf_amts["py_booked_amt_sv"]
  cy_booked_amt_dm = pf_amts["cy_booked_amt_dm"]
  cy_booked_amt_sv = pf_amts["cy_booked_amt_sv"]
  reserve_amt_dm = pf_amts["reserve_amt_dm"]
  reserve_amt_sv = pf_amts["reserve_amt_sv"]

  # perform calculations
  py_booked_amt = py_booked_amt_dm + py_booked_amt_sv
  cy_booked_amt = cy_booked_amt_dm + cy_booked_amt_sv
  reserve_amt = reserve_amt_dm + reserve_amt_sv
  total_booked_amt = py_booked_amt + cy_booked_amt

  return total_booked_amt, reserve_amt, cy_booked_amt, py_booked_amt

gen_output = 0

In [5]:
# function to format the amount
def format_amt(number):
    abs_number = abs(number)

    if abs_number >= 1_00_00_000:  # Crores
        formatted_amt = f"{number / 1_00_00_000:.2f} C"
    elif abs_number >= 1_00_000:  # Lakhs
        formatted_amt = f"{number / 1_00_000:.2f} L"
    elif abs_number >= 1_000:  # Thousands
        formatted_amt = f"{number / 1_000:.2f} K"
    else:
        formatted_amt = f"{number:.2f}"

    return formatted_amt

# function to set start and end date
def get_start_end_date():
  start_date = (datetime.date.today() + datetime.timedelta(days=-365)).strftime('%Y-%m-%d')
  end_date = (datetime.date.today() + datetime.timedelta(days=1)).strftime('%Y-%m-%d')
  return start_date, end_date

# function to fetch my portfolio csv
def get_mypfs_df():
  mypfs_df = pd.read_csv('https://raw.githubusercontent.com/ankit-rathi/Tradevesting_v1/main/data/myPortfolioStocks.csv')
  return mypfs_df

# function to fetch my prospects csv
def get_mypps_df():
  mypps_df = pd.read_csv('https://raw.githubusercontent.com/ankit-rathi/Tradevesting_v1/main/data/myProspectsScrips.csv')
  return mypps_df

# function to fetch screener data
def get_myscreen_df():
  myscreen_df = pd.read_csv('https://raw.githubusercontent.com/ankit-rathi/Tradevesting_v1/main/data/myScreenerDB.csv')
  return myscreen_df

# function to fetch momentum data
def get_myinvmt_df():
  myinvmt_df = pd.read_csv('https://raw.githubusercontent.com/ankit-rathi/Tradevesting_v1/main/data/myInvestments.csv')
  return myinvmt_df

# function to get the stock ids
def get_stock_ids(df_pf):
  stock_n100 = df_pf['Symbol'].unique()

  exclude = ['CADILAHC','MMTC', 'MASFIN']

  stock_ids = df_pf[~df_pf['Symbol'].isin(exclude) ]['Symbol'].unique()

  #mypf = mypf[mypf.Forecast.notnull()]
  #stock_ids = mypf['Symbol'].unique()

  #stock_ids.sort()
  return stock_ids

# get features from screener data
def get_screener_features():
  myscreen_df = get_myscreen_df()
  cols = ['Symbol', 'EPS', 'MedPE', 'ROCE%', 'ROE%', 'CapType']
  return myscreen_df[cols]

# get relative strength
def get_relative_strength(stock_list):

    # Dictionary to store stock tickers and their corresponding percentage price change
    stock_changes = {}

    # Loop through each stock and fetch its price data
    for stock in stock_list:
        try:
            # Download the stock data for the given date range
            stock_data = yfin.Ticker(stock + '.NS').history(period='1mo', interval='1d')[map(str.title, ['open', 'close', 'low', 'high', 'volume'])]

            # Calculate the percentage change for the stock
            if len(stock_data) > 0:
                start_price = stock_data['Close'].iloc[0]
                end_price = stock_data['Close'].iloc[-1]
                percent_change = round(((end_price - start_price) / start_price) * 100, 2)
                stock_changes[stock] = percent_change
            else:
                stock_changes[stock] = np.nan  # If no data is available, set to NaN

        except Exception as e:
            print(f"Error fetching data for {stock}: {e}")
            stock_changes[stock] = np.nan

    # Create a DataFrame with stock tickers and their percentage changes
    df = pd.DataFrame(list(stock_changes.items()), columns=['Symbol', 'Percent_Change'])

    # Drop any stocks with missing data (NaN values)
    df = df.dropna()

    # Calculate the percentile rank based on percentage change
    df['RSP'] = round(df['Percent_Change'].rank(pct=True) * 100, 2)
    cols = ['Symbol', 'RSP']
    df = df[cols]
    # Sort by percentile rank (optional)
    df = df.sort_values(by='RSP', ascending=False).reset_index(drop=True)

    return df

In [6]:
# function to get stock technicals
def stock_prec_dev(stock_symbol):
    #stock_symbol = 'ULTRACEMCO.NS'
    short_window = 20
    mid_window = 50
    long_window = 200
    moving_avg = 'SMA'

    start = datetime.datetime(*map(int, start_date.split('-')))
    end = datetime.datetime(*map(int, end_date.split('-')))

    stock_df = yfin.Ticker(stock_symbol + '.NS').history(period='max', interval='1d')[map(str.title, ['open', 'close', 'low', 'high', 'volume'])]

    stock_df['Max'] = round(max(stock_df['Close']),2)
    stock_df = stock_df[(stock_df.index <= end_date) & (stock_df.index >= start_date)]
    stock_df['200_SMA'] = round(stock_df['Close'].rolling(window = 200, min_periods = 1).mean(),0)
    stock_df['Dev%_200'] = round((stock_df['Close'] - stock_df['200_SMA'])*100/stock_df['200_SMA'],2)
    stock_df.dropna(axis = 0, inplace = True) # remove any null rows

    stock_df['20_SMA'] = stock_df['Close'].rolling(window=20).mean()
    stock_df['50_SMA'] = stock_df['Close'].rolling(window=50).mean()
    stock_df['Symbol'] = stock_symbol

    stock_df['Close'] = round(stock_df['Close'],2)
    stock_df['Min'] = round(min(stock_df['Close']),2)
    stock_df['RSI_14'] = ta.momentum.RSIIndicator(close=stock_df['Close'], window=14).rsi()
    stock_df['RSI_14'] = round(stock_df['RSI_14'],0)
    stock_df['Prev_Close'] = stock_df['Close'].shift(1)
    stock_df.drop(['Open', 'Low', 'High', 'Volume'], axis=1, inplace=True)
    stock_df = stock_df.tail(1)

    max_SMA = max(stock_df['20_SMA'].item(), stock_df['50_SMA'].item(), stock_df['200_SMA'].item())
    min_SMA = min(stock_df['20_SMA'].item(), stock_df['50_SMA'].item(), stock_df['200_SMA'].item())
    ABS_Spread = max_SMA - min_SMA
    stock_df['Spread%'] = round((ABS_Spread / stock_df['200_SMA'].item()) * 100,2)

    return stock_df

# function to compute stock attributes
def get_common_features(stock_ids, df_mypf):

  df_prec_dev = pd.DataFrame()
  df_tmp = get_screener_features()
  df_rs = get_relative_strength(stock_ids)

  for stock_id in stock_ids:
      tmp = stock_prec_dev(stock_id)
      tmp = tmp.reset_index()
      df_prec_dev = pd.concat([df_prec_dev, tmp], ignore_index = True)
  df_prec_dev = pd.merge(df_prec_dev, df_mypf, on= 'Symbol')
  df_prec_dev = pd.merge(df_prec_dev, df_tmp, on= 'Symbol', how='left')
  df_prec_dev = pd.merge(df_prec_dev, df_rs, on= 'Symbol', how='left')
  #print(df_prec_dev.columns)
  df_prec_dev['Curr_PE'] = round(df_prec_dev['Close']/df_prec_dev['EPS'],1)
  df_prec_dev['Dev%_PE'] = round((df_prec_dev['Curr_PE'] - df_prec_dev['MedPE'])*100/df_prec_dev['MedPE'],2)
  df_prec_dev['Conviction'] = df_prec_dev['Conviction'] + '-' + df_prec_dev['CapType']
  return df_prec_dev

# function to arrange stock features
def arrange_features(df_stocks, common_cols, diff_cols):
  df_stocks_common = df_stocks[common_cols].drop_duplicates()
  df_stocks_diff = df_stocks[diff_cols]
  df_stocks_diff['Investment'] = df_stocks_diff['AvgCost'] * df_stocks_diff['Shares']
  df_stocks_diff = df_stocks_diff.groupby(['Symbol'])[['Shares', 'Investment']].aggregate(['sum']).reset_index()
  df_stocks_diff.columns = ['Symbol', 'Shares', 'Investment']
  df_stocks_diff['AvgCost'] = round(df_stocks_diff['Investment']/df_stocks_diff['Shares'],2)
  df_stocks = pd.merge(df_stocks_diff, df_stocks_common, on='Symbol')
  return df_stocks

# plot fact distribution across dimension
def plot_pie_chart(df, dimension, fact):
  # grouping the data by category and calculating the sum of fact for each type
  grouped_data = df.groupby(dimension)[fact].sum()

  # sorting the grouped data in descending order
  grouped_data = grouped_data.sort_values(ascending=False)

  # creating a pie chart
  grouped_data.plot.pie(autopct='%1.1f%%', startangle=90, figsize=(6, 6))

  # adding a title and displaying the plot
  plt.title(f'{dimension} {fact} Distribution')
  plt.ylabel('')  # To hide the y-label
  plt.show()

In [7]:
# function to get portfolio features

def get_portfolio_features(df_common_features):

  print_date_time()
  print('-------------------')

  #df_common_features["Target"] = df_common_features["Target"].fillna(df_common_features["Max"])
  df_common_features['NTT'] = np.where(df_common_features['Strategy']== 'NTT', df_common_features["Target"], df_common_features['Max'])
  df_common_features['LTT'] = np.where(df_common_features['Strategy']== 'BTT', df_common_features["Target"], df_common_features['Max'])
  df_common_features['BOL'] = df_common_features['Min']

  tmp_df = df_common_features[df_common_features['Symbol'].isin(mypf_df[mypf_df['InPortfolio'] != 'NA'].Symbol.values)]
  print('qualified stocks: '+str(len(tmp_df['Symbol'].unique())))
  tmp_df1 = tmp_df[tmp_df['LatestQtr'] == 1]
  print('with latest results: '+str(len(tmp_df1['Symbol'].unique())))
  tmp_df1 = tmp_df1[tmp_df1['StarStock'] == 1]
  print('still star stocks: '+str(len(tmp_df1['Symbol'].unique())))
  tmp_df['Investment'] = tmp_df['AvgCost'] * tmp_df['Shares']
  tmp_df['Current'] = round(tmp_df['Close'] * tmp_df['Shares'],0)
  tmp_df['Previous'] = tmp_df['Prev_Close'] * tmp_df['Shares']
  tmp_df['EstimatedST'] = tmp_df['NTT'] * tmp_df['Shares']
  tmp_df['EstimatedLT'] = tmp_df['LTT'] * tmp_df['Shares']
  tmp_df['Current P/L'] = round((tmp_df['Current'] - tmp_df['Investment']),0)
  tmp_df['Today P/L%'] = round((tmp_df['Current'] - tmp_df['Previous'])*100/tmp_df['Previous'],2)
  tmp_df['Current P/L%'] = round((tmp_df['Current'] - tmp_df['Investment'])*100/tmp_df['Investment'],2)
  tmp_df['EstimatedST P/L%'] = round((tmp_df['EstimatedST'] - tmp_df['Investment'])*100/tmp_df['Investment'],2)
  tmp_df['EstimatedLT P/L%'] = round((tmp_df['EstimatedLT'] - tmp_df['Investment'])*100/tmp_df['Investment'],2)
  tmp_df['NTT%'] = round((tmp_df['NTT'] - tmp_df['Close'])*100/tmp_df['Close'],2)
  tmp_df['LTT%'] = round((tmp_df['LTT'] - tmp_df['Close'])*100/tmp_df['Close'],2)
  tmp_df['Gained%'] = round((tmp_df['Close'] - tmp_df['BOL'])*100/tmp_df['BOL'],2)
  investment = round(sum(tmp_df['AvgCost']*tmp_df['Shares']),0)
  current = round(sum(tmp_df['Close']*tmp_df['Shares']),0)
  tmp_df['InitAlloc%'] = round(tmp_df['Investment']*100/investment,2)
  tmp_df['CurrAlloc%'] = round(tmp_df['Current']*100/current,2)
  tmp_df['FTT'] = tmp_df['LTT']
  tmp_df.loc[tmp_df['Strategy'] == 'NTT', 'FTT'] = tmp_df['NTT']
  tmp_df['FTT%'] = tmp_df['LTT%']
  tmp_df.loc[tmp_df['Strategy'] == 'NTT', 'FTT%'] = tmp_df['NTT%']
  tmp_df['FTT Amt'] = round(tmp_df['FTT%'] * tmp_df['Current']/100,0)
  tmp_df['OTT%'] = round((tmp_df['FTT'] - tmp_df['AvgCost'])*100/tmp_df['AvgCost'],2)
  tmp_df['RRR Ind'] = round(tmp_df['Current P/L']/tmp_df['FTT Amt'],2)
  tmp_df['Risk Ind'] = round(tmp_df['Current P/L%']*tmp_df['CurrAlloc%'],0)

  return tmp_df

# function to print portfolio features
def print_portfolio_stats(df_portfolio_features, myinvmt_df):
  from pyxirr import xirr

  total_booked_amt, reserve_amt, cy_booked_amt, py_booked_amt = get_amt()

  dates = myinvmt_df['Date'].values
  dates = np.append(dates, datetime.date.today().strftime('%d-%b-%y'))
  investment = myinvmt_df['Investment'].values
  dates= pd.to_datetime(dates)

  current = round(sum(df_portfolio_features['Close']*df_portfolio_features['Shares']),0) + reserve_amt
  investment_xirr = np.append(investment, current)
  cagr = round(xirr(pd.DataFrame({"dates": dates, "amounts": investment_xirr}))*100,2)

  investment = -sum(investment)
  invested = round(sum(df_portfolio_features['AvgCost']*df_portfolio_features['Shares']),0) + reserve_amt
  previous = round(sum(df_portfolio_features['Prev_Close']*df_portfolio_features['Shares']),0) + reserve_amt
  cy_invested = investment + py_booked_amt

  today_pnl_amount = current-previous
  today_pnl_percentage = round((current-previous)*100/previous,2)

  curr_pnl_amount = current-invested
  curr_pnl_percentage = round((curr_pnl_amount)*100/(cy_invested),2)

  cy_pnl_amount = cy_booked_amt + curr_pnl_amount
  cy_pnl_percentage = round((cy_pnl_amount)*100/cy_invested,2)

  overall_pnl_amount = total_booked_amt + curr_pnl_amount
  overall_pnl_percentage = round((overall_pnl_amount)*100/investment,2)

  estimate_st = round(sum(df_portfolio_features['FTT']*df_portfolio_features['Shares']),0)  + reserve_amt
  est_st_pnl_amount = estimate_st-current
  est_st_pnl_percentage = round((est_st_pnl_amount)*100/current,2)

  estimate_lt = round(sum(df_portfolio_features['LTT']*df_portfolio_features['Shares']),0)  + reserve_amt
  est_lt_pnl_amount = estimate_lt-current
  est_lt_pnl_percentage = round((est_lt_pnl_amount)*100/current,2)

  total_profit = round(sum(df_portfolio_features[df_portfolio_features['Current P/L%'] > 0]['Current']) - sum(df_portfolio_features[df_portfolio_features['Current P/L%'] > 0]['Investment']),0)
  total_loss = round(sum(df_portfolio_features[df_portfolio_features['Current P/L%'] < 0]['Current']) - sum(df_portfolio_features[df_portfolio_features['Current P/L%'] < 0]['Investment']),0)

  cy_booked_percentage = round((cy_booked_amt)*100/current,2)
  py_booked_percentage = round((py_booked_amt)*100/investment,2)
  total_booked_percentage = round((total_booked_amt)*100/investment,2)

  print('-------------------')
  print('Initial Investment: ', format_amt(investment))
  print('CY Investment: ', format_amt(cy_invested))
  print('Reserve: ', format_amt(reserve_amt))
  print('Current: ',  format_amt(current))
  print('-------------------')
  print('Today PnL: '+ '{} ({}%)'.format(format_amt(today_pnl_amount), today_pnl_percentage))
  print('Current PnL: '+ '{} ({}%)'.format(format_amt(curr_pnl_amount), curr_pnl_percentage))
  print('CY Booked + Current PnL: '+ '{} ({}%)'.format(format_amt(cy_pnl_amount), cy_pnl_percentage))
  print('-------------------')
  print('Total profit: ', format_amt(total_profit))
  print('Total loss: ', format_amt(total_loss))
  print('-------------------')
  print('Total Booked + Current PnL: '+ '{} ({}%)'.format(format_amt(overall_pnl_amount), overall_pnl_percentage))
  print('Total Booked PnL: '+ '{} ({}%)'.format(format_amt(total_booked_amt), total_booked_percentage))
  print('Curr Year Booked PnL: '+ '{} ({}%)'.format(format_amt(cy_booked_amt), cy_booked_percentage))
  print('Prev Year Booked PnL: '+ '{} ({}%)'.format(format_amt(py_booked_amt), py_booked_percentage))
  print('===================')
  print('Est FTT: ',  format_amt(estimate_st))
  print('Est FTT PnL: '+ '{} ({}%)'.format(format_amt(est_st_pnl_amount), est_st_pnl_percentage))

  print('===================')
  print('Deployed: ', format_amt(investment))

  print('Current: ', format_amt(current))

  print('CAGR/XIRR %: '+'{}%'.format(cagr))

In [8]:
# get start and end date
start_date, end_date = get_start_end_date()

# get portfolio and prospects data
mypfs_df = get_mypfs_df()
mypps_df = get_mypps_df()
myinvmt_df = get_myinvmt_df()

# merge above datasets
mypf_df = pd.merge(mypfs_df, mypps_df, on="Symbol")

# seggregate dm and sv portfolio
dm_pf = mypf_df[mypf_df['InPortfolio'] == 'DM']
sv_pf = mypf_df[mypf_df['InPortfolio'] == 'SV']

# build portfolio stock dataframe
dm_stocks = get_stock_ids(dm_pf)
sv_stocks = get_stock_ids(sv_pf)
df_stocks = pd.concat([dm_pf,sv_pf], ignore_index = True)

# arrange common and diff stock features
common_cols = ['Symbol', 'Target', 'Criteria', 'Strategy', 'CumlRnk', 'LatestQtr', 'StarStock', 'Conviction', 'Category', 'InFolio', 'XIRR', 'MBQ']
diff_cols = ['Symbol', 'AvgCost', 'Shares']
df_stocks = arrange_features(df_stocks, common_cols, diff_cols)

# get common features
stock_ids = df_stocks['Symbol'].values
df_common_features = get_common_features(stock_ids, df_stocks)

df_common_features.reset_index(drop=True, inplace=True)
df_common_features.drop(['Date'], axis=1, inplace=True)
# get and print portfolio features
df_portfolio_features = get_portfolio_features(df_common_features)

print_portfolio_stats(df_portfolio_features, myinvmt_df)

df = df_portfolio_features
#plot_pie_chart(df, 'CapType', 'Current')
list_ox40n = list(df[df['MBQ'].str.contains('OX40N', na=False)]['Symbol'].values)

Run date time (IST): 2026-05-14 11:18:08
-------------------
qualified stocks: 92
with latest results: 31
still star stocks: 20
-------------------
Initial Investment:  1.40 C
CY Investment:  1.82 C
Reserve:  1.49 K
Current:  1.47 C
-------------------
Today PnL: -35.41 K (-0.24%)
Current PnL: -36.31 L (-19.91%)
CY Booked + Current PnL: -34.23 L (-18.77%)
-------------------
Total profit:  1.77 L
Total loss:  -38.08 L
-------------------
Total Booked + Current PnL: 8.64 L (6.2%)
Total Booked PnL: 44.95 L (32.22%)
Curr Year Booked PnL: 2.08 L (1.42%)
Prev Year Booked PnL: 42.87 L (30.73%)
===================
Est FTT:  2.55 C
Est FTT PnL: 1.09 C (73.92%)
===================
Deployed:  1.40 C
Current:  1.47 C
CAGR/XIRR %: 2.51%

In [9]:
# top 5 near their targets
cols = ['Symbol', 'Today P/L%', 'Current P/L%', 'FTT%', 'OTT%', 'FTT Amt', 'Current P/L', 'Current', 'FTT', 'Dev%_PE', 'RSI_14','Conviction', 'Spread%',  'CumlRnk', 'RRR Ind', 'CurrAlloc%', 'Gained%', 'Criteria', 'Strategy', 'Category']
df_tmp = df_portfolio_features[~df_portfolio_features['Symbol'].isin(['ENRIN','BLUSPRING','DIGITIDE'])]
df_tmp = df_tmp.sort_values(by = 'FTT Amt', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
59,PIDILITIND,2.56,5.07,12.66,18.37,18770.0,7150.0,148260.0,1670.26,-26.41,64.0,X-LC,5.58,5.0,0.38,1.01,16.41,X40,ATH,CHEMICALS
55,MASFIN,-0.97,-1.42,23.32,21.57,22524.0,-1395.0,96585.0,397.04,-15.09,46.0,H-SC,5.64,167.0,-0.06,0.66,19.89,XR,ATH,FINANCE
51,KOTAKBANK,-0.11,0.80,20.14,21.11,28112.0,1110.0,139582.0,453.24,-13.74,49.0,X-LC,7.29,12.0,0.04,0.95,6.75,X40,ATH,BANKS
53,M&M,0.37,1.34,21.75,23.38,30568.0,1863.0,140544.0,3802.40,-14.09,46.0,X-LC,8.25,25.0,0.06,0.96,6.55,X40N,ATH,AUTO
17,CIPLA,6.51,14.48,17.65,34.69,30947.0,22175.0,175336.0,1663.60,-11.50,69.0,X-LC,11.04,18.0,0.72,1.19,18.58,X40N,ATH,PHARMA

In [10]:
# top 5 today
df_tmp = df_portfolio_features.sort_values(by = 'Today P/L%', ascending=False)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
3,ALKYLAMINE,11.85,-22.03,148.34,93.63,116773.0,-22243.0,78720.0,4546.37,-16.57,69.0,H-SC,16.46,142.0,-0.19,0.54,48.64,SR,ATH,CHEMICALS
17,CIPLA,6.51,14.48,17.65,34.69,30947.0,22175.0,175336.0,1663.60,-11.50,69.0,X-LC,11.04,18.0,0.72,1.19,18.58,X40N,ATH,PHARMA
11,BERGEPAINT,5.58,-1.21,26.85,25.32,68367.0,-3125.0,254624.0,680.00,-6.58,72.0,X-MC,11.79,68.0,-0.05,1.73,32.52,XY24,NTT,PAINTS
91,ZYDUSLIFE,5.03,4.03,30.38,35.63,66233.0,8442.0,218016.0,1286.17,-9.46,66.0,H-MC,3.25,120.0,0.13,1.48,14.63,AR,ATH,PHARMA
24,EASEMYTRIP,3.93,-54.75,221.95,45.70,177596.0,-96799.0,80016.0,26.40,-16.85,60.0,M-SC,6.95,204.0,-0.55,0.54,40.17,XY24,NTT,TRAVEL

In [11]:
# bottom 5 today
df_tmp = df_portfolio_features.sort_values(by = 'Today P/L%', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
77,TANLA,-2.82,-42.59,278.41,117.25,432783.0,-115313.0,155448.0,1922.32,-42.09,50.0,H-SC,15.35,147.0,-0.27,1.06,36.1,AR,ATH,IT
83,TTKPRESTIG,-2.65,-32.80,48.94,0.09,33146.0,-33050.0,67727.0,770.00,57.10,52.0,M-SC,17.12,250.0,-1.00,0.46,20.6,OX40N,NTT,DURABLES
33,HCLTECH,-2.62,-27.75,68.18,21.51,119170.0,-67136.0,174788.0,1872.35,-23.90,23.0,X-LC,15.67,8.0,-0.56,1.19,0.0,X40,ATH,IT
67,ROUTE,-2.59,-61.58,337.66,68.16,172632.0,-81940.0,51126.0,2215.45,-68.92,46.0,H-SC,25.94,141.0,-0.47,0.35,21.8,SR,ATH,IT
45,INFY,-2.57,-25.51,80.22,34.24,186965.0,-79823.0,233065.0,1972.00,-41.22,27.0,X-LC,17.58,3.0,-0.43,1.59,0.0,X40,NTT,IT

In [12]:
# top 5 to exit based on CumlRnk
df_tmp = df_portfolio_features[~df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])]
df_tmp = df_tmp[(df_tmp['Current P/L%'] > -1) & (df_tmp['Current P/L%'] < 1)].sort_values(by = 'CumlRnk', ascending=False)
df_tmp[cols].head()

Empty DataFrame
Columns: [Symbol, Today P/L%, Current P/L%, FTT%, OTT%, FTT Amt, Current P/L, Current, FTT, Dev%_PE, RSI_14, Conviction, Spread%, CumlRnk, RRR Ind, CurrAlloc%, Gained%, Criteria, Strategy, Category]
Index: []

In [13]:
# OX40N stocks to exit
df_tmp = df_portfolio_features[(df_portfolio_features['Symbol'].isin(list_ox40n))].sort_values(by = 'Current P/L%', ascending=False)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
25,FINCABLES,-1.17,34.89,54.14,107.91,107823.0,51511.0,199155.0,1641.55,21.26,62.0,M-SC,23.17,220.0,0.48,1.36,49.83,OX40N,ATH,CABLES
72,SIS,0.20,-13.95,40.91,21.26,39089.0,-15484.0,95548.0,528.00,2267.88,61.0,H-SC,12.93,168.0,-0.40,0.65,42.07,OX40N,NTT,MISC
16,CERA,-1.14,-24.91,65.00,23.89,85851.0,-43825.0,132078.0,9475.00,-27.45,62.0,H-SC,9.45,153.0,-0.51,0.90,26.93,OX40N,NTT,CERAMICS
50,KANSAINER,-0.11,-27.08,55.61,13.47,109357.0,-73017.0,196650.0,340.00,-37.29,66.0,H-SC,14.98,162.0,-0.67,1.34,37.36,XY24,NTT,PAINTS
43,INDIGOPNTS,-2.00,-31.40,45.79,0.02,54835.0,-54806.0,119753.0,1408.00,82.48,65.0,M-SC,20.50,222.0,-1.00,0.82,35.87,OX40N,NTT,PAINTS

In [14]:
# top 5 to book for rotation
df_tmp = df_portfolio_features[(df_portfolio_features['Current P/L%'] > 20) ].sort_values(by = 'CumlRnk', ascending=False)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
25,FINCABLES,-1.17,34.89,54.14,107.91,107823.0,51511.0,199155.0,1641.55,21.26,62.0,M-SC,23.17,220.0,0.48,1.36,49.83,OX40N,ATH,CABLES
68,SATIN,-2.24,22.13,24.32,51.83,82063.0,61148.0,337432.0,274.00,9.07,78.0,H-SC,24.14,159.0,0.75,2.30,64.38,XY24,NTT,FINANCE

In [15]:
# top 5 to monitor for exit
df_tmp = df_portfolio_features[~df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])]
df_tmp = df_tmp[(df_tmp['Current P/L%'] > 0) ].sort_values(by = 'Dev%_PE', ascending=False)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
25,FINCABLES,-1.17,34.89,54.14,107.91,107823.0,51511.0,199155.0,1641.55,21.26,62.0,M-SC,23.17,220.0,0.48,1.36,49.83,OX40N,ATH,CABLES
68,SATIN,-2.24,22.13,24.32,51.83,82063.0,61148.0,337432.0,274.00,9.07,78.0,H-SC,24.14,159.0,0.75,2.30,64.38,XY24,NTT,FINANCE
91,ZYDUSLIFE,5.03,4.03,30.38,35.63,66233.0,8442.0,218016.0,1286.17,-9.46,66.0,H-MC,3.25,120.0,0.13,1.48,14.63,AR,ATH,PHARMA
73,SONACOMS,-1.10,1.18,37.47,39.09,38350.0,1190.0,102349.0,804.02,-19.79,55.0,M-MC,19.93,193.0,0.03,0.70,44.79,AR,ATH,AUTO

In [16]:
# top 5 to book for rotation from weak conviction
df_tmp = df_portfolio_features[~df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])]
df_tmp = df_tmp[~df_tmp['Criteria'].isin(['XY25','XY24','X40', 'X40N'])].sort_values(by = 'RRR Ind', ascending=False)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
25,FINCABLES,-1.17,34.89,54.14,107.91,107823.0,51511.0,199155.0,1641.55,21.26,62.0,M-SC,23.17,220.0,0.48,1.36,49.83,OX40N,ATH,CABLES
91,ZYDUSLIFE,5.03,4.03,30.38,35.63,66233.0,8442.0,218016.0,1286.17,-9.46,66.0,H-MC,3.25,120.0,0.13,1.48,14.63,AR,ATH,PHARMA
73,SONACOMS,-1.10,1.18,37.47,39.09,38350.0,1190.0,102349.0,804.02,-19.79,55.0,M-MC,19.93,193.0,0.03,0.70,44.79,AR,ATH,AUTO
55,MASFIN,-0.97,-1.42,23.32,21.57,22524.0,-1395.0,96585.0,397.04,-15.09,46.0,H-SC,5.64,167.0,-0.06,0.66,19.89,XR,ATH,FINANCE
75,SURYODAY,-1.26,-2.29,25.92,23.03,45352.0,-4100.0,174971.0,216.00,90.79,70.0,H-SC,14.51,166.0,-0.09,1.19,47.32,XR,NTT,BANKS

In [17]:
# top 5 to accumulate based on lowest RSI_14
df_tmp = df_portfolio_features[df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])].sort_values(by = 'RSI_14', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
33,HCLTECH,-2.62,-27.75,68.18,21.51,119170.0,-67136.0,174788.0,1872.35,-23.90,23.0,X-LC,15.67,8.0,-0.56,1.19,0.00,X40,ATH,IT
79,TCS,-1.84,-34.51,93.26,26.57,282966.0,-159857.0,303416.0,4311.58,-44.61,26.0,X-LC,15.37,2.0,-0.56,2.07,0.00,X40,ATH,IT
45,INFY,-2.57,-25.51,80.22,34.24,186965.0,-79823.0,233065.0,1972.00,-41.22,27.0,X-LC,17.58,3.0,-0.43,1.59,0.00,X40,NTT,IT
88,VOLTAS,0.45,-1.07,46.77,45.20,88718.0,-2052.0,189690.0,1856.00,13.28,34.0,X-MC,1.46,79.0,-0.02,1.29,3.64,XY25,NTT,AC
58,PGHH,0.22,-27.49,82.05,32.01,127040.0,-58688.0,154832.0,17616.87,-51.02,37.0,X-MC,16.70,57.0,-0.46,1.05,5.90,X40,ATH,FMCG

In [18]:
# top 5 to accumulate based on Spread and CumlRnk
df_tmp = df_portfolio_features[df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])]
df_tmp = df_tmp[(df_tmp['CumlRnk'] < 100)].sort_values(by = 'Spread%', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
88,VOLTAS,0.45,-1.07,46.77,45.20,88718.0,-2052.0,189690.0,1856.00,13.28,34.0,X-MC,1.46,79.0,-0.02,1.29,3.64,XY25,NTT,AC
84,UNITDSPR,0.44,-7.30,30.28,20.77,65722.0,-17097.0,217047.0,1644.00,-17.72,41.0,X-MC,2.93,64.0,-0.26,1.48,3.54,X40N,NTT,BREWERIES
65,RELIANCE,0.38,-12.45,43.12,25.30,75867.0,-25020.0,175943.0,1952.00,-14.65,44.0,X-LC,3.58,21.0,-0.33,1.20,4.55,XY25,BTT,REFINERIES
39,ICICIGI,0.38,-4.07,24.40,19.34,46840.0,-8143.0,191966.0,2252.93,-19.34,52.0,X-MC,4.68,66.0,-0.17,1.31,7.22,X40,ATH,INSURANCE
19,COLPAL,0.56,-18.50,73.62,41.51,158025.0,-48715.0,214650.0,3726.84,-1.37,57.0,X-MC,5.35,62.0,-0.31,1.46,20.00,XY25,ATH,FMCG

In [19]:
# top 5 to accumulate based on lowest Gained%
df_tmp = df_portfolio_features[df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])].sort_values(by = 'Gained%', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
45,INFY,-2.57,-25.51,80.22,34.24,186965.0,-79823.0,233065.0,1972.00,-41.22,27.0,X-LC,17.58,3.0,-0.43,1.59,0.00,X40,NTT,IT
33,HCLTECH,-2.62,-27.75,68.18,21.51,119170.0,-67136.0,174788.0,1872.35,-23.90,23.0,X-LC,15.67,8.0,-0.56,1.19,0.00,X40,ATH,IT
79,TCS,-1.84,-34.51,93.26,26.57,282966.0,-159857.0,303416.0,4311.58,-44.61,26.0,X-LC,15.37,2.0,-0.56,2.07,0.00,X40,ATH,IT
32,HAVELLS,-0.11,-23.30,72.21,32.08,181651.0,-76432.0,251559.0,2062.85,-27.80,38.0,X-MC,11.03,63.0,-0.42,1.71,1.47,X40,ATH,ELECTRICAL
48,JIOFIN,-0.91,-23.89,68.74,28.43,156078.0,-71271.0,227056.0,387.00,-25.03,39.0,X-LC,15.52,34.0,-0.46,1.55,2.34,XY24,BTT,FINANCE

In [20]:
# top 5 to accumulate based on lowest CurrAlloc%
df_tmp = df_portfolio_features[df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])].sort_values(by = 'CurrAlloc%', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
64,RELAXO,1.87,-62.18,302.74,52.31,166192.0,-90264.0,54896.0,1176.00,-59.73,45.0,X-SC,24.86,92.0,-0.54,0.37,22.74,X40N,NTT,FOOTWEAR
10,BATAINDIA,0.29,-54.63,198.00,35.20,115588.0,-70292.0,58378.0,2096.00,-23.47,42.0,X-SC,26.18,91.0,-0.61,0.40,15.78,X40,NTT,FOOTWEAR
60,QUESS,-1.72,-16.20,107.51,73.90,96218.0,-17296.0,89497.0,424.00,-54.82,52.0,X-SC,12.65,80.0,-0.18,0.61,22.00,XY24,NTT,MISC
28,GODREJCP,-1.09,-8.78,44.12,31.47,59812.0,-13047.0,135567.0,1469.04,-3.99,41.0,X-LC,7.43,32.0,-0.22,0.92,4.02,X40N,ATH,FMCG
51,KOTAKBANK,-0.11,0.80,20.14,21.11,28112.0,1110.0,139582.0,453.24,-13.74,49.0,X-LC,7.29,12.0,0.04,0.95,6.75,X40,ATH,BANKS

In [21]:
# top 5 to accumulate based on CumlRnk
df_tmp = df_portfolio_features.sort_values(by = 'CumlRnk', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
47,ITC,0.54,-19.37,47.66,19.06,130715.0,-65900.0,274266.0,452.00,-55.92,50.0,X-LC,15.49,1.0,-0.50,1.87,6.40,X40,NTT,FMCG
79,TCS,-1.84,-34.51,93.26,26.57,282966.0,-159857.0,303416.0,4311.58,-44.61,26.0,X-LC,15.37,2.0,-0.56,2.07,0.00,X40,ATH,IT
45,INFY,-2.57,-25.51,80.22,34.24,186965.0,-79823.0,233065.0,1972.00,-41.22,27.0,X-LC,17.58,3.0,-0.43,1.59,0.00,X40,NTT,IT
81,TMPV,-0.49,-23.70,79.00,36.58,214494.0,-84329.0,271512.0,600.00,-83.62,44.0,X-LC,5.81,4.0,-0.39,1.85,13.17,XY24,NTT,AUTO
59,PIDILITIND,2.56,5.07,12.66,18.37,18770.0,7150.0,148260.0,1670.26,-26.41,64.0,X-LC,5.58,5.0,0.38,1.01,16.41,X40,ATH,CHEMICALS

In [22]:
# top 5 for average up
df_tmp = df_portfolio_features[(df_portfolio_features['Dev%_200'] > 5)].sort_values(by = 'CurrAlloc%', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
44,INDUSINDBK,-0.27,-34.29,102.22,32.89,51862.0,-26470.0,50736.0,1800.00,-338.80,51.0,L-MC,7.29,258.0,-0.51,0.35,24.88,XR,NTT,BANKS
3,ALKYLAMINE,11.85,-22.03,148.34,93.63,116773.0,-22243.0,78720.0,4546.37,-16.57,69.0,H-SC,16.46,142.0,-0.19,0.54,48.64,SR,ATH,CHEMICALS
72,SIS,0.20,-13.95,40.91,21.26,39089.0,-15484.0,95548.0,528.00,2267.88,61.0,H-SC,12.93,168.0,-0.40,0.65,42.07,OX40N,NTT,MISC
73,SONACOMS,-1.10,1.18,37.47,39.09,38350.0,1190.0,102349.0,804.02,-19.79,55.0,M-MC,19.93,193.0,0.03,0.70,44.79,AR,ATH,AUTO
5,ATULAUTO,-1.62,-16.67,74.69,45.57,122694.0,-32861.0,164271.0,844.00,3559.46,53.0,M-SC,7.21,248.0,-0.27,1.12,26.41,XY24,NTT,AUTO

In [23]:
# top 5 RSP
df_tmp = df_portfolio_features.sort_values(by = 'RSP', ascending=False)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
68,SATIN,-2.24,22.13,24.32,51.83,82063.0,61148.0,337432.0,274.00,9.07,78.0,H-SC,24.14,159.0,0.75,2.30,64.38,XY24,NTT,FINANCE
3,ALKYLAMINE,11.85,-22.03,148.34,93.63,116773.0,-22243.0,78720.0,4546.37,-16.57,69.0,H-SC,16.46,142.0,-0.19,0.54,48.64,SR,ATH,CHEMICALS
75,SURYODAY,-1.26,-2.29,25.92,23.03,45352.0,-4100.0,174971.0,216.00,90.79,70.0,H-SC,14.51,166.0,-0.09,1.19,47.32,XR,NTT,BANKS
25,FINCABLES,-1.17,34.89,54.14,107.91,107823.0,51511.0,199155.0,1641.55,21.26,62.0,M-SC,23.17,220.0,0.48,1.36,49.83,OX40N,ATH,CABLES
72,SIS,0.20,-13.95,40.91,21.26,39089.0,-15484.0,95548.0,528.00,2267.88,61.0,H-SC,12.93,168.0,-0.40,0.65,42.07,OX40N,NTT,MISC

In [24]:
# Top N allocation
df_tmp = df_portfolio_features.sort_values(by = 'CurrAlloc%', ascending=False)
top_n_values = [10, 25, 50]

sum_df = pd.DataFrame({
    'Top_N': top_n_values,
    'Sum_Alloc%': [df_tmp['CurrAlloc%'].head(n).sum() for n in top_n_values]
})

sum_df

   Top_N  Sum_Alloc%
0     10       19.26
1     25       42.71
2     50       73.01

In [25]:
# market-cap-wise allocation
df_tmp = df_portfolio_features[cols]
df_tmp.groupby(df_tmp['Conviction'].str[-2:])['CurrAlloc%'].sum().sort_values(ascending=False)

Conviction
SC    42.59
LC    31.36
MC    26.08
Name: CurrAlloc%, dtype: float64

In [26]:
# criteria-wise allocation
df_portfolio_features.groupby('Criteria')['CurrAlloc%'].sum().sort_values(ascending=False)

Criteria
XY24     27.49
X40      25.53
X40N     16.77
XR        8.93
OX40N     6.97
XY25      6.77
AR        6.68
SR        0.89
Name: CurrAlloc%, dtype: float64

In [27]:
# conviction-wise allocation
df_portfolio_features.groupby('Conviction')['CurrAlloc%'].sum().sort_values(ascending=False)

Conviction
X-LC    29.24
H-SC    22.36
X-MC    21.09
M-SC    10.03
X-SC     9.68
H-MC     2.66
M-MC     1.98
H-LC     1.23
M-LC     0.89
L-SC     0.52
L-MC     0.35
Name: CurrAlloc%, dtype: float64

In [28]:
# sector-wise stats
df_tmp = df_portfolio_features.groupby('Category')[['CurrAlloc%', 'Current', 'Current P/L', 'FTT Amt']].sum().sort_values(by=['Current', 'Current P/L'], ascending=False)
df_tmp['Current P/L%'] = round(df_tmp['Current P/L'] * 100 / df_tmp['Current'], 2)
df_tmp['FTT%'] = round(df_tmp['FTT Amt'] * 100 / df_tmp['Current'], 2)
cols = ['CurrAlloc%', 'Current P/L%', 'FTT%']
df_tmp[cols].sort_values(by=['CurrAlloc%'], ascending=False)

               CurrAlloc%  Current P/L%    FTT%
Category
FMCG                15.53        -16.04   56.94
FINANCE             10.82        -16.15   66.66
IT                   9.98        -53.80  131.24
MISC                 6.91        -32.12   89.52
AUTO                 6.62        -12.69   54.94
BANKS                5.72         -8.21   58.25
PAINTS               5.71        -17.48   37.88
INSURANCE            5.40         -4.36   39.88
PHARMA               5.11          1.30   30.42
ELECTRICAL           3.91        -22.97   66.75
CHEMICALS            2.20        -25.72  100.65
HEALTHCARE           1.98        -23.01   55.11
AC                   1.82        -19.74   52.21
TRAVEL               1.72        -76.48  164.85
APPARELS             1.70         -7.36   43.99
FOOTWEAR             1.69        -77.53  148.71
DURABLES             1.66        -58.17   96.64
BREWERIES            1.48         -7.88   30.28
REALTY               1.37        -10.47   28.62
CERAMICS             1.36        -53.92  100.68
CABLES               1.36         25.86   54.14
REFINERIES           1.20        -14.22   43.12
ENGINEERING          1.19        -38.79  102.27
CEMENT               1.12        -63.74  186.24
JEWELLERY            1.02       -114.47  188.98
ENTERTAINMENT        0.71        -85.28  195.79
TEXTILES             0.42        -50.60   93.55
HOTELS               0.32       -142.48  228.00

In [29]:
# money to be made criteria-wise
df_portfolio_features.groupby('Criteria')['FTT Amt'].agg(['sum', 'count']).sort_values(by='sum', ascending=False)

                sum  count
Criteria
XY24      3561527.0     21
X40       1954605.0     19
XR        1372403.0     13
X40N      1261483.0     13
AR        1202152.0      9
OX40N      768995.0     10
XY25       445388.0      5
SR         289405.0      2

In [30]:
# money to be made conviction-wise
df_portfolio_features.groupby('Conviction')['FTT Amt'].agg(['sum', 'count']).sort_values(by='sum', ascending=False)

                  sum  count
Conviction
H-SC        3504623.0     24
X-LC        2004541.0     21
X-MC        1636663.0     15
M-SC        1445410.0     14
X-SC        1381849.0      9
H-MC         306476.0      2
L-SC         215072.0      2
M-LC         161658.0      1
M-MC          95336.0      2
H-LC          52468.0      1
L-MC          51862.0      1

In [31]:
# money to be made criteria and conviction-wise
df_portfolio_features.groupby(['Conviction', 'Criteria'])['FTT Amt'].agg(['sum', 'count']).sort_values(by='sum', ascending=False)

                           sum  count
Conviction Criteria
H-SC       XY24      1089597.0      6
X-LC       X40       1068528.0     10
H-SC       AR         966844.0      5
M-SC       XY24       860286.0      6
H-SC       XR         814985.0      7
X-SC       XY24       801491.0      4
X-MC       X40        676198.0      7
           X40N       514384.0      4
X-LC       X40N       376620.0      6
           XY24       370572.0      2
X-SC       X40N       370479.0      3
H-SC       OX40N      343792.0      4
M-SC       OX40N      316901.0      5
H-SC       SR         289405.0      2
X-MC       XY25       246743.0      2
H-MC       XY24       240243.0      1
X-SC       X40        209879.0      2
X-MC       XY24       199338.0      2
M-SC       XR         189966.0      2
M-LC       XR         161658.0      1
X-LC       XY25       141659.0      2
L-SC       OX40N      108302.0      1
           XR         106770.0      1
M-SC       AR          78257.0      1
H-MC       AR          66233.0      1
M-MC       XY25        56986.0      1
H-LC       AR          52468.0      1
L-MC       XR          51862.0      1
X-LC       XR          47162.0      1
M-MC       AR          38350.0      1

In [32]:
# notebook execution time

end_time = time.time()
execution_time = round(end_time - start_time, 0)
print(f"Notebook execution time: {execution_time} seconds")

Notebook execution time: 58.0 seconds