<a href="https://colab.research.google.com/github/ankit-rathi/Quantvesting_v2/blob/main/myStocks_Portfolio_Analysis.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
'''
!pip install pandas==2.2.2 -qq
!pip install pyxirr -qq
!pip install ta -qq
!pip install yfinance==0.2.59 -qq
'''

'\n!pip install pandas==2.2.2 -qq\n!pip install pyxirr -qq\n!pip install ta -qq\n!pip install yfinance==0.2.59 -qq\n'

In [2]:
# import libraries

import numpy as np
import pandas as pd
import datetime
import warnings
warnings.filterwarnings('ignore')
import yfinance as yfin
import ta
import matplotlib.pyplot as plt
import requests

In [3]:
# notebook start time
import time
import datetime
import pytz

start_time = time.time()

# function to print date timestamp
def print_date_time():
  tz_NY = pytz.timezone('Asia/Kolkata')
  datetime_NY = datetime.datetime.now(tz_NY)
  print("Run date time (IST):", datetime_NY.strftime("%Y-%m-%d %H:%M:%S"))

In [4]:
# function to get booked and reserved amount
def get_amt():
  # fetch the JSON data from the URL
  url = "https://raw.githubusercontent.com/ankit-rathi/Tradevesting_v1/main/data/myPortfolioAmts.json"
  response = requests.get(url)
  pf_amts = response.json()  # parse the JSON data

  # extract values from the JSON
  py_booked_amt_dm = pf_amts["py_booked_amt_dm"]
  py_booked_amt_sv = pf_amts["py_booked_amt_sv"]
  cy_booked_amt_dm = pf_amts["cy_booked_amt_dm"]
  cy_booked_amt_sv = pf_amts["cy_booked_amt_sv"]
  reserve_amt_dm = pf_amts["reserve_amt_dm"]
  reserve_amt_sv = pf_amts["reserve_amt_sv"]

  # perform calculations
  py_booked_amt = py_booked_amt_dm + py_booked_amt_sv
  cy_booked_amt = cy_booked_amt_dm + cy_booked_amt_sv
  reserve_amt = reserve_amt_dm + reserve_amt_sv
  total_booked_amt = py_booked_amt + cy_booked_amt

  return total_booked_amt, reserve_amt, cy_booked_amt, py_booked_amt

gen_output = 0

In [5]:
# function to format the amount
def format_amt(number):
    abs_number = abs(number)

    if abs_number >= 1_00_00_000:  # Crores
        formatted_amt = f"{number / 1_00_00_000:.2f} C"
    elif abs_number >= 1_00_000:  # Lakhs
        formatted_amt = f"{number / 1_00_000:.2f} L"
    elif abs_number >= 1_000:  # Thousands
        formatted_amt = f"{number / 1_000:.2f} K"
    else:
        formatted_amt = f"{number:.2f}"

    return formatted_amt

# function to set start and end date
def get_start_end_date():
  start_date = (datetime.date.today() + datetime.timedelta(days=-365)).strftime('%Y-%m-%d')
  end_date = (datetime.date.today() + datetime.timedelta(days=1)).strftime('%Y-%m-%d')
  return start_date, end_date

# function to fetch my portfolio csv
def get_mypfs_df():
  mypfs_df = pd.read_csv('https://raw.githubusercontent.com/ankit-rathi/Tradevesting_v1/main/data/myPortfolioStocks.csv')
  return mypfs_df

# function to fetch my prospects csv
def get_mypps_df():
  mypps_df = pd.read_csv('https://raw.githubusercontent.com/ankit-rathi/Tradevesting_v1/main/data/myProspectsScrips.csv')
  return mypps_df

# function to fetch screener data
def get_myscreen_df():
  myscreen_df = pd.read_csv('https://raw.githubusercontent.com/ankit-rathi/Tradevesting_v1/main/data/myScreenerDB.csv')
  return myscreen_df

# function to fetch momentum data
def get_myinvmt_df():
  myinvmt_df = pd.read_csv('https://raw.githubusercontent.com/ankit-rathi/Tradevesting_v1/main/data/myInvestments.csv')
  return myinvmt_df

# function to get the stock ids
def get_stock_ids(df_pf):
  stock_n100 = df_pf['Symbol'].unique()

  exclude = ['CADILAHC','MMTC', 'MASFIN']

  stock_ids = df_pf[~df_pf['Symbol'].isin(exclude) ]['Symbol'].unique()

  #mypf = mypf[mypf.Forecast.notnull()]
  #stock_ids = mypf['Symbol'].unique()

  #stock_ids.sort()
  return stock_ids

# get features from screener data
def get_screener_features():
  myscreen_df = get_myscreen_df()
  cols = ['Symbol', 'EPS', 'MedPE', 'ROCE%', 'ROE%', 'CapType']
  return myscreen_df[cols]

# get relative strength
def get_relative_strength(stock_list):

    # Dictionary to store stock tickers and their corresponding percentage price change
    stock_changes = {}

    # Loop through each stock and fetch its price data
    for stock in stock_list:
        try:
            # Download the stock data for the given date range
            stock_data = yfin.Ticker(stock + '.NS').history(period='1mo', interval='1d')[map(str.title, ['open', 'close', 'low', 'high', 'volume'])]

            # Calculate the percentage change for the stock
            if len(stock_data) > 0:
                start_price = stock_data['Close'].iloc[0]
                end_price = stock_data['Close'].iloc[-1]
                percent_change = round(((end_price - start_price) / start_price) * 100, 2)
                stock_changes[stock] = percent_change
            else:
                stock_changes[stock] = np.nan  # If no data is available, set to NaN

        except Exception as e:
            print(f"Error fetching data for {stock}: {e}")
            stock_changes[stock] = np.nan

    # Create a DataFrame with stock tickers and their percentage changes
    df = pd.DataFrame(list(stock_changes.items()), columns=['Symbol', 'Percent_Change'])

    # Drop any stocks with missing data (NaN values)
    df = df.dropna()

    # Calculate the percentile rank based on percentage change
    df['RSP'] = round(df['Percent_Change'].rank(pct=True) * 100, 2)
    cols = ['Symbol', 'RSP']
    df = df[cols]
    # Sort by percentile rank (optional)
    df = df.sort_values(by='RSP', ascending=False).reset_index(drop=True)

    return df

In [6]:
# function to get stock technicals
def stock_prec_dev(stock_symbol):
    #stock_symbol = 'ULTRACEMCO.NS'
    short_window = 20
    mid_window = 50
    long_window = 200
    moving_avg = 'SMA'

    start = datetime.datetime(*map(int, start_date.split('-')))
    end = datetime.datetime(*map(int, end_date.split('-')))

    stock_df = yfin.Ticker(stock_symbol + '.NS').history(period='max', interval='1d')[map(str.title, ['open', 'close', 'low', 'high', 'volume'])]

    stock_df['Max'] = round(max(stock_df['Close']),2)
    stock_df = stock_df[(stock_df.index <= end_date) & (stock_df.index >= start_date)]
    stock_df['200_SMA'] = round(stock_df['Close'].rolling(window = 200, min_periods = 1).mean(),0)
    stock_df['Dev%_200'] = round((stock_df['Close'] - stock_df['200_SMA'])*100/stock_df['200_SMA'],2)
    stock_df.dropna(axis = 0, inplace = True) # remove any null rows

    stock_df['20_SMA'] = stock_df['Close'].rolling(window=20).mean()
    stock_df['50_SMA'] = stock_df['Close'].rolling(window=50).mean()
    stock_df['Symbol'] = stock_symbol

    stock_df['Close'] = round(stock_df['Close'],2)
    stock_df['Min'] = round(min(stock_df['Close']),2)
    stock_df['RSI_14'] = ta.momentum.RSIIndicator(close=stock_df['Close'], window=14).rsi()
    stock_df['RSI_14'] = round(stock_df['RSI_14'],0)
    stock_df['Prev_Close'] = stock_df['Close'].shift(1)
    stock_df.drop(['Open', 'Low', 'High', 'Volume'], axis=1, inplace=True)
    stock_df = stock_df.tail(1)

    max_SMA = max(stock_df['20_SMA'].item(), stock_df['50_SMA'].item(), stock_df['200_SMA'].item())
    min_SMA = min(stock_df['20_SMA'].item(), stock_df['50_SMA'].item(), stock_df['200_SMA'].item())
    ABS_Spread = max_SMA - min_SMA
    stock_df['Spread%'] = round((ABS_Spread / stock_df['200_SMA'].item()) * 100,2)

    return stock_df

# function to compute stock attributes
def get_common_features(stock_ids, df_mypf):

  df_prec_dev = pd.DataFrame()
  df_tmp = get_screener_features()
  df_rs = get_relative_strength(stock_ids)

  for stock_id in stock_ids:
      tmp = stock_prec_dev(stock_id)
      tmp = tmp.reset_index()
      df_prec_dev = pd.concat([df_prec_dev, tmp], ignore_index = True)
  df_prec_dev = pd.merge(df_prec_dev, df_mypf, on= 'Symbol')
  df_prec_dev = pd.merge(df_prec_dev, df_tmp, on= 'Symbol', how='left')
  df_prec_dev = pd.merge(df_prec_dev, df_rs, on= 'Symbol', how='left')
  #print(df_prec_dev.columns)
  df_prec_dev['Curr_PE'] = round(df_prec_dev['Close']/df_prec_dev['EPS'],1)
  df_prec_dev['Dev%_PE'] = round((df_prec_dev['Curr_PE'] - df_prec_dev['MedPE'])*100/df_prec_dev['MedPE'],2)
  df_prec_dev['Conviction'] = df_prec_dev['Conviction'] + '-' + df_prec_dev['CapType']
  return df_prec_dev

# function to arrange stock features
def arrange_features(df_stocks, common_cols, diff_cols):
  df_stocks_common = df_stocks[common_cols].drop_duplicates()
  df_stocks_diff = df_stocks[diff_cols]
  df_stocks_diff['Investment'] = df_stocks_diff['AvgCost'] * df_stocks_diff['Shares']
  df_stocks_diff = df_stocks_diff.groupby(['Symbol'])[['Shares', 'Investment']].aggregate(['sum']).reset_index()
  df_stocks_diff.columns = ['Symbol', 'Shares', 'Investment']
  df_stocks_diff['AvgCost'] = round(df_stocks_diff['Investment']/df_stocks_diff['Shares'],2)
  df_stocks = pd.merge(df_stocks_diff, df_stocks_common, on='Symbol')
  return df_stocks

# plot fact distribution across dimension
def plot_pie_chart(df, dimension, fact):
  # grouping the data by category and calculating the sum of fact for each type
  grouped_data = df.groupby(dimension)[fact].sum()

  # sorting the grouped data in descending order
  grouped_data = grouped_data.sort_values(ascending=False)

  # creating a pie chart
  grouped_data.plot.pie(autopct='%1.1f%%', startangle=90, figsize=(6, 6))

  # adding a title and displaying the plot
  plt.title(f'{dimension} {fact} Distribution')
  plt.ylabel('')  # To hide the y-label
  plt.show()

In [7]:
# function to get portfolio features

def get_portfolio_features(df_common_features):

  print_date_time()
  print('-------------------')

  #df_common_features["Target"] = df_common_features["Target"].fillna(df_common_features["Max"])
  df_common_features['NTT'] = np.where(df_common_features['Strategy']== 'NTT', df_common_features["Target"], df_common_features['Max'])
  df_common_features['LTT'] = np.where(df_common_features['Strategy']== 'BTT', df_common_features["Target"], df_common_features['Max'])
  df_common_features['BOL'] = df_common_features['Min']

  tmp_df = df_common_features[df_common_features['Symbol'].isin(mypf_df[mypf_df['InPortfolio'] != 'NA'].Symbol.values)]
  print('qualified stocks: '+str(len(tmp_df['Symbol'].unique())))
  tmp_df1 = tmp_df[tmp_df['LatestQtr'] == 1]
  print('with latest results: '+str(len(tmp_df1['Symbol'].unique())))
  tmp_df1 = tmp_df1[tmp_df1['StarStock'] == 1]
  print('still star stocks: '+str(len(tmp_df1['Symbol'].unique())))
  tmp_df['Investment'] = tmp_df['AvgCost'] * tmp_df['Shares']
  tmp_df['Current'] = round(tmp_df['Close'] * tmp_df['Shares'],0)
  tmp_df['Previous'] = tmp_df['Prev_Close'] * tmp_df['Shares']
  tmp_df['EstimatedST'] = tmp_df['NTT'] * tmp_df['Shares']
  tmp_df['EstimatedLT'] = tmp_df['LTT'] * tmp_df['Shares']
  tmp_df['Current P/L'] = round((tmp_df['Current'] - tmp_df['Investment']),0)
  tmp_df['Today P/L%'] = round((tmp_df['Current'] - tmp_df['Previous'])*100/tmp_df['Previous'],2)
  tmp_df['Current P/L%'] = round((tmp_df['Current'] - tmp_df['Investment'])*100/tmp_df['Investment'],2)
  tmp_df['EstimatedST P/L%'] = round((tmp_df['EstimatedST'] - tmp_df['Investment'])*100/tmp_df['Investment'],2)
  tmp_df['EstimatedLT P/L%'] = round((tmp_df['EstimatedLT'] - tmp_df['Investment'])*100/tmp_df['Investment'],2)
  tmp_df['NTT%'] = round((tmp_df['NTT'] - tmp_df['Close'])*100/tmp_df['Close'],2)
  tmp_df['LTT%'] = round((tmp_df['LTT'] - tmp_df['Close'])*100/tmp_df['Close'],2)
  tmp_df['Gained%'] = round((tmp_df['Close'] - tmp_df['BOL'])*100/tmp_df['BOL'],2)
  investment = round(sum(tmp_df['AvgCost']*tmp_df['Shares']),0)
  current = round(sum(tmp_df['Close']*tmp_df['Shares']),0)
  tmp_df['InitAlloc%'] = round(tmp_df['Investment']*100/investment,2)
  tmp_df['CurrAlloc%'] = round(tmp_df['Current']*100/current,2)
  tmp_df['FTT'] = tmp_df['LTT']
  tmp_df.loc[tmp_df['Strategy'] == 'NTT', 'FTT'] = tmp_df['NTT']
  tmp_df['FTT%'] = tmp_df['LTT%']
  tmp_df.loc[tmp_df['Strategy'] == 'NTT', 'FTT%'] = tmp_df['NTT%']
  tmp_df['FTT Amt'] = round(tmp_df['FTT%'] * tmp_df['Current']/100,0)
  tmp_df['OTT%'] = round((tmp_df['FTT'] - tmp_df['AvgCost'])*100/tmp_df['AvgCost'],2)
  tmp_df['RRR Ind'] = round(tmp_df['Current P/L']/tmp_df['FTT Amt'],2)
  tmp_df['Risk Ind'] = round(tmp_df['Current P/L%']*tmp_df['CurrAlloc%'],0)

  return tmp_df

# function to print portfolio features
def print_portfolio_stats(df_portfolio_features, myinvmt_df):
  from pyxirr import xirr

  total_booked_amt, reserve_amt, cy_booked_amt, py_booked_amt = get_amt()

  dates = myinvmt_df['Date'].values
  dates = np.append(dates, datetime.date.today().strftime('%d-%b-%y'))
  investment = myinvmt_df['Investment'].values
  dates= pd.to_datetime(dates)

  current = round(sum(df_portfolio_features['Close']*df_portfolio_features['Shares']),0) + reserve_amt
  investment_xirr = np.append(investment, current)
  cagr = round(xirr(pd.DataFrame({"dates": dates, "amounts": investment_xirr}))*100,2)

  investment = -sum(investment)
  invested = round(sum(df_portfolio_features['AvgCost']*df_portfolio_features['Shares']),0) + reserve_amt
  previous = round(sum(df_portfolio_features['Prev_Close']*df_portfolio_features['Shares']),0) + reserve_amt
  cy_invested = investment + py_booked_amt

  today_pnl_amount = current-previous
  today_pnl_percentage = round((current-previous)*100/previous,2)

  curr_pnl_amount = current-invested
  curr_pnl_percentage = round((curr_pnl_amount)*100/(cy_invested),2)

  cy_pnl_amount = cy_booked_amt + curr_pnl_amount
  cy_pnl_percentage = round((cy_pnl_amount)*100/cy_invested,2)

  overall_pnl_amount = total_booked_amt + curr_pnl_amount
  overall_pnl_percentage = round((overall_pnl_amount)*100/investment,2)

  estimate_st = round(sum(df_portfolio_features['FTT']*df_portfolio_features['Shares']),0)  + reserve_amt
  est_st_pnl_amount = estimate_st-current
  est_st_pnl_percentage = round((est_st_pnl_amount)*100/current,2)

  estimate_lt = round(sum(df_portfolio_features['LTT']*df_portfolio_features['Shares']),0)  + reserve_amt
  est_lt_pnl_amount = estimate_lt-current
  est_lt_pnl_percentage = round((est_lt_pnl_amount)*100/current,2)

  total_profit = round(sum(df_portfolio_features[df_portfolio_features['Current P/L%'] > 0]['Current']) - sum(df_portfolio_features[df_portfolio_features['Current P/L%'] > 0]['Investment']),0)
  total_loss = round(sum(df_portfolio_features[df_portfolio_features['Current P/L%'] < 0]['Current']) - sum(df_portfolio_features[df_portfolio_features['Current P/L%'] < 0]['Investment']),0)

  cy_booked_percentage = round((cy_booked_amt)*100/current,2)
  py_booked_percentage = round((py_booked_amt)*100/investment,2)
  total_booked_percentage = round((total_booked_amt)*100/investment,2)

  print('-------------------')
  print('Initial Investment: ', format_amt(investment))
  print('CY Investment: ', format_amt(cy_invested))
  print('Reserve: ', format_amt(reserve_amt))
  print('Current: ',  format_amt(current))
  print('-------------------')
  print('Today PnL: '+ '{} ({}%)'.format(format_amt(today_pnl_amount), today_pnl_percentage))
  print('Current PnL: '+ '{} ({}%)'.format(format_amt(curr_pnl_amount), curr_pnl_percentage))
  print('CY Booked + Current PnL: '+ '{} ({}%)'.format(format_amt(cy_pnl_amount), cy_pnl_percentage))
  print('-------------------')
  print('Total profit: ', format_amt(total_profit))
  print('Total loss: ', format_amt(total_loss))
  print('-------------------')
  print('Total Booked + Current PnL: '+ '{} ({}%)'.format(format_amt(overall_pnl_amount), overall_pnl_percentage))
  print('Total Booked PnL: '+ '{} ({}%)'.format(format_amt(total_booked_amt), total_booked_percentage))
  print('Curr Year Booked PnL: '+ '{} ({}%)'.format(format_amt(cy_booked_amt), cy_booked_percentage))
  print('Prev Year Booked PnL: '+ '{} ({}%)'.format(format_amt(py_booked_amt), py_booked_percentage))
  print('===================')
  print('Est FTT: ',  format_amt(estimate_st))
  print('Est FTT PnL: '+ '{} ({}%)'.format(format_amt(est_st_pnl_amount), est_st_pnl_percentage))

  print('===================')
  print('Deployed: ', format_amt(investment))

  print('Current: ', format_amt(current))

  print('CAGR/XIRR %: '+'{}%'.format(cagr))

In [8]:
# get start and end date
start_date, end_date = get_start_end_date()

# get portfolio and prospects data
mypfs_df = get_mypfs_df()
mypps_df = get_mypps_df()
myinvmt_df = get_myinvmt_df()

# merge above datasets
mypf_df = pd.merge(mypfs_df, mypps_df, on="Symbol")

# seggregate dm and sv portfolio
dm_pf = mypf_df[mypf_df['InPortfolio'] == 'DM']
sv_pf = mypf_df[mypf_df['InPortfolio'] == 'SV']

# build portfolio stock dataframe
dm_stocks = get_stock_ids(dm_pf)
sv_stocks = get_stock_ids(sv_pf)
df_stocks = pd.concat([dm_pf,sv_pf], ignore_index = True)

# arrange common and diff stock features
common_cols = ['Symbol', 'Target', 'Criteria', 'Strategy', 'CumlRnk', 'LatestQtr', 'StarStock', 'Conviction', 'Category', 'InFolio', 'XIRR', 'MBQ']
diff_cols = ['Symbol', 'AvgCost', 'Shares']
df_stocks = arrange_features(df_stocks, common_cols, diff_cols)

# get common features
stock_ids = df_stocks['Symbol'].values
df_common_features = get_common_features(stock_ids, df_stocks)

df_common_features.reset_index(drop=True, inplace=True)
df_common_features.drop(['Date'], axis=1, inplace=True)
# get and print portfolio features
df_portfolio_features = get_portfolio_features(df_common_features)

print_portfolio_stats(df_portfolio_features, myinvmt_df)

df = df_portfolio_features
#plot_pie_chart(df, 'CapType', 'Current')
list_ox40n = list(df[df['MBQ'].str.contains('OX40N', na=False)]['Symbol'].values)

Run date time (IST): 2026-06-16 17:56:43
-------------------
qualified stocks: 92
with latest results: 31
still star stocks: 20
-------------------
Initial Investment:  1.40 C
CY Investment:  1.82 C
Reserve:  1.49 K
Current:  1.51 C
-------------------
Today PnL: 99.67 K (0.66%)
Current PnL: -31.95 L (-17.52%)
CY Booked + Current PnL: -29.87 L (-16.38%)
-------------------
Total profit:  3.00 L
Total loss:  -34.94 L
-------------------
Total Booked + Current PnL: 13.00 L (9.32%)
Total Booked PnL: 44.95 L (32.22%)
Curr Year Booked PnL: 2.08 L (1.38%)
Prev Year Booked PnL: 42.87 L (30.73%)
===================
Est FTT:  2.55 C
Est FTT PnL: 1.04 C (68.73%)
===================
Deployed:  1.40 C
Current:  1.51 C
CAGR/XIRR %: 3.79%

In [9]:
# top 5 near their targets
cols = ['Symbol', 'Today P/L%', 'Current P/L%', 'FTT%', 'OTT%', 'FTT Amt', 'Current P/L', 'Current', 'FTT', 'Dev%_PE', 'RSI_14','Conviction', 'Spread%',  'CumlRnk', 'RRR Ind', 'CurrAlloc%', 'Gained%', 'Criteria', 'Strategy', 'Category']
df_tmp = df_portfolio_features[~df_portfolio_features['Symbol'].isin(['ENRIN','BLUSPRING','DIGITIDE'])]
df_tmp = df_tmp.sort_values(by = 'FTT Amt', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
59,PIDILITIND,0.01,11.35,6.30,18.37,9899.0,16010.0,157120.0,1670.26,-22.05,74.0,X-LC,3.68,5.0,1.62,1.04,23.37,X40,ATH,CHEMICALS
51,KOTAKBANK,0.52,8.98,11.13,21.11,16796.0,12432.0,150904.0,453.24,-6.37,70.0,X-LC,5.95,12.0,0.74,1.00,15.41,X40,ATH,BANKS
55,MASFIN,0.51,-4.26,26.97,21.57,25301.0,-4170.0,93810.0,397.04,-17.34,52.0,H-SC,3.51,167.0,-0.16,0.62,11.82,XR,ATH,FINANCE
72,SIS,-1.02,-2.76,24.70,21.26,26668.0,-3065.0,107967.0,528.00,2575.13,61.0,H-SC,21.80,168.0,-0.11,0.71,60.53,OX40N,NTT,MISC
53,M&M,0.12,1.82,21.18,23.38,29907.0,2525.0,141206.0,3802.40,-13.74,56.0,X-LC,10.54,25.0,0.08,0.93,7.06,X40N,ATH,AUTO

In [10]:
# top 5 today
df_tmp = df_portfolio_features.sort_values(by = 'Today P/L%', ascending=False)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
61,RAJESHEXPO,5.00,-83.73,514.91,0.07,114949.0,-114853.0,22324.0,518.00,718.18,33.0,L-SC,34.70,268.0,-1.00,0.15,10.25,OX40N,NTT,JEWELLERY
80,TITAGARH,3.97,-15.79,73.07,45.74,149015.0,-38242.0,203935.0,1548.00,12.11,66.0,H-SC,4.95,175.0,-0.26,1.35,55.60,XY24,NTT,ENGINEERING
27,GLAXO,3.78,-11.57,53.45,35.69,94192.0,-23060.0,176224.0,3380.16,-32.56,47.0,X-MC,10.16,56.0,-0.24,1.17,4.74,X40,ATH,PHARMA
33,HCLTECH,3.55,-24.79,61.55,21.51,111998.0,-59961.0,181963.0,1872.35,-21.01,47.0,X-LC,18.44,8.0,-0.54,1.20,4.45,X40,ATH,IT
6,AWL,3.20,-32.07,145.86,67.02,353054.0,-114259.0,242050.0,485.00,-63.40,58.0,X-SC,14.86,81.0,-0.32,1.60,14.49,XY24,NTT,FMCG

In [11]:
# bottom 5 today
df_tmp = df_portfolio_features.sort_values(by = 'Today P/L%', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
38,HYUNDAI,-2.73,4.98,42.26,49.35,68430.0,7684.0,161925.0,2809.30,-15.47,60.0,X-LC,15.25,29.0,0.11,1.07,16.75,X40N,ATH,AUTO
14,CAMPUS,-1.91,-20.93,68.56,33.28,90953.0,-35113.0,132662.0,393.00,-36.35,40.0,M-SC,6.29,218.0,-0.39,0.88,6.53,XY24,NTT,FOOTWEAR
11,BERGEPAINT,-1.71,-5.92,33.20,25.32,80506.0,-15261.0,242488.0,680.00,-11.00,54.0,X-MC,3.49,68.0,-0.19,1.60,26.21,XY24,NTT,PAINTS
21,DEN,-1.70,-45.16,159.07,42.07,73681.0,-38144.0,46320.0,75.00,65.80,62.0,M-SC,9.00,235.0,-0.52,0.31,25.98,AR,NTT,ENTERTAINMENT
3,ALKYLAMINE,-1.46,-23.84,154.23,93.63,118598.0,-24066.0,76897.0,4546.37,-18.40,55.0,H-SC,7.84,142.0,-0.20,0.51,45.20,SR,ATH,CHEMICALS

In [12]:
# top 5 to exit based on CumlRnk
df_tmp = df_portfolio_features[~df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])]
df_tmp = df_tmp[(df_tmp['Current P/L%'] > -1) & (df_tmp['Current P/L%'] < 1)].sort_values(by = 'CumlRnk', ascending=False)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
74,STARHEALTH,-1.31,0.96,45.86,47.26,130165.0,2709.0,283832.0,761.0,59.25,52.0,H-SC,10.06,173.0,0.02,1.88,24.61,XY24,NTT,INSURANCE

In [13]:
# OX40N stocks to exit
df_tmp = df_portfolio_features[(df_portfolio_features['Symbol'].isin(list_ox40n))].sort_values(by = 'Current P/L%', ascending=False)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
25,FINCABLES,1.09,33.69,55.52,107.91,109584.0,49734.0,197378.0,1641.55,20.24,53.0,M-SC,23.35,220.0,0.45,1.31,48.49,OX40N,ATH,CABLES
72,SIS,-1.02,-2.76,24.70,21.26,26668.0,-3065.0,107967.0,528.00,2575.13,61.0,H-SC,21.80,168.0,-0.11,0.71,60.53,OX40N,NTT,MISC
16,CERA,-0.81,-18.83,52.63,23.89,75147.0,-33119.0,142784.0,9475.00,-21.72,69.0,H-SC,4.67,153.0,-0.44,0.94,37.21,OX40N,NTT,CERAMICS
43,INDIGOPNTS,2.34,-26.92,36.86,0.02,47023.0,-46988.0,127571.0,1408.00,94.75,64.0,M-SC,10.78,222.0,-1.00,0.84,44.74,OX40N,NTT,PAINTS
50,KANSAINER,-0.36,-28.02,57.64,13.47,111886.0,-75555.0,194112.0,340.00,-38.12,56.0,H-SC,6.48,162.0,-0.68,1.28,35.59,XY24,NTT,PAINTS

In [14]:
# top 5 to book for rotation
df_tmp = df_portfolio_features[(df_portfolio_features['Current P/L%'] > 20) ].sort_values(by = 'CumlRnk', ascending=False)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
25,FINCABLES,1.09,33.69,55.52,107.91,109584.0,49734.0,197378.0,1641.55,20.24,53.0,M-SC,23.35,220.0,0.45,1.31,48.49,OX40N,ATH,CABLES
68,SATIN,-0.31,28.22,18.42,51.83,65252.0,77959.0,354243.0,274.00,14.32,58.0,H-SC,40.27,159.0,1.19,2.34,72.57,XY24,NTT,FINANCE

In [15]:
# top 5 to monitor for exit
df_tmp = df_portfolio_features[~df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])]
df_tmp = df_tmp[(df_tmp['Current P/L%'] > 0) ].sort_values(by = 'Dev%_PE', ascending=False)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
9,BANDHANBNK,2.78,4.26,84.55,92.42,245560.0,11873.0,290432.0,400.00,149.28,65.0,H-SC,21.66,174.0,0.05,1.92,59.99,XY24,NTT,BANKS
74,STARHEALTH,-1.31,0.96,45.86,47.26,130165.0,2709.0,283832.0,761.00,59.25,52.0,H-SC,10.06,173.0,0.02,1.88,24.61,XY24,NTT,INSURANCE
25,FINCABLES,1.09,33.69,55.52,107.91,109584.0,49734.0,197378.0,1641.55,20.24,53.0,M-SC,23.35,220.0,0.45,1.31,48.49,OX40N,ATH,CABLES
68,SATIN,-0.31,28.22,18.42,51.83,65252.0,77959.0,354243.0,274.00,14.32,58.0,H-SC,40.27,159.0,1.19,2.34,72.57,XY24,NTT,FINANCE
91,ZYDUSLIFE,-0.86,13.75,19.23,35.63,45843.0,28819.0,238393.0,1286.17,-0.90,59.0,H-MC,13.36,120.0,0.63,1.58,25.34,AR,ATH,PHARMA

In [16]:
# top 5 to book for rotation from weak conviction
df_tmp = df_portfolio_features[~df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])]
df_tmp = df_tmp[~df_tmp['Criteria'].isin(['XY25','XY24','X40', 'X40N'])].sort_values(by = 'RRR Ind', ascending=False)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
91,ZYDUSLIFE,-0.86,13.75,19.23,35.63,45843.0,28819.0,238393.0,1286.17,-0.90,59.0,H-MC,13.36,120.0,0.63,1.58,25.34,AR,ATH,PHARMA
25,FINCABLES,1.09,33.69,55.52,107.91,109584.0,49734.0,197378.0,1641.55,20.24,53.0,M-SC,23.35,220.0,0.45,1.31,48.49,OX40N,ATH,CABLES
73,SONACOMS,0.39,3.56,34.31,39.09,35945.0,3605.0,104764.0,804.02,-17.90,53.0,M-MC,18.43,193.0,0.10,0.69,48.20,AR,ATH,AUTO
75,SURYODAY,0.96,-1.15,24.47,23.03,43315.0,-2060.0,177011.0,216.00,92.98,61.0,H-SC,18.38,166.0,-0.05,1.17,49.04,XR,NTT,BANKS
42,INDIAMART,1.73,-10.44,130.82,106.72,144500.0,-12879.0,110457.0,4810.62,-59.57,62.0,H-SC,9.98,140.0,-0.09,0.73,6.93,AR,ATH,MISC

In [17]:
# top 5 to accumulate based on lowest RSI_14
df_tmp = df_portfolio_features[df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])].sort_values(by = 'RSI_14', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
58,PGHH,0.95,-31.98,94.08,32.01,136634.0,-68288.0,145232.0,17616.87,-53.97,35.0,X-MC,19.41,57.0,-0.50,0.96,0.95,X40,ATH,FMCG
1,ABBOTINDIA,-0.59,-12.44,34.85,18.07,54575.0,-22255.0,156600.0,35195.00,-25.47,44.0,X-MC,6.03,58.0,-0.41,1.04,3.65,X40,ATH,PHARMA
79,TCS,1.71,-35.45,93.45,24.88,279475.0,-164209.0,299064.0,4253.91,-45.26,44.0,X-LC,18.90,2.0,-0.59,1.98,2.97,X40,ATH,IT
35,HDFCLIFE,-1.17,-6.06,41.77,33.18,58782.0,-9072.0,140728.0,814.30,-26.65,45.0,X-LC,16.36,31.0,-0.15,0.93,5.35,X40,ATH,INSURANCE
40,ICICIPRULI,0.86,-18.86,60.55,30.28,96792.0,-37151.0,159854.0,787.27,-40.63,46.0,X-MC,16.97,78.0,-0.38,1.06,6.51,X40,ATH,INSURANCE

In [18]:
# top 5 to accumulate based on Spread and CumlRnk
df_tmp = df_portfolio_features[df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])]
df_tmp = df_tmp[(df_tmp['CumlRnk'] < 100)].sort_values(by = 'Spread%', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
49,JSWINFRA,-0.22,0.02,16.41,16.43,36400.0,45.0,221819.0,342.00,-14.25,63.0,X-MC,1.46,61.0,0.00,1.47,25.39,X40N,NTT,REALTY
57,PAGEIND,-0.33,1.89,31.11,33.59,85072.0,5076.0,273455.0,51217.29,-26.89,59.0,X-MC,2.78,55.0,0.06,1.81,29.86,X40,ATH,APPARELS
19,COLPAL,1.91,-20.38,75.66,39.86,158651.0,-53675.0,209690.0,3683.41,-3.61,56.0,X-MC,2.94,62.0,-0.34,1.39,18.61,XY25,ATH,FMCG
15,CAMS,1.91,3.80,19.92,24.48,52076.0,9570.0,261426.0,950.00,-0.61,58.0,X-SC,3.17,89.0,0.18,1.73,27.27,X40N,NTT,MISC
11,BERGEPAINT,-1.71,-5.92,33.20,25.32,80506.0,-15261.0,242488.0,680.00,-11.00,54.0,X-MC,3.49,68.0,-0.19,1.60,26.21,XY24,NTT,PAINTS

In [19]:
# top 5 to accumulate based on lowest Gained%
df_tmp = df_portfolio_features[df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])].sort_values(by = 'Gained%', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
58,PGHH,0.95,-31.98,94.08,32.01,136634.0,-68288.0,145232.0,17616.87,-53.97,35.0,X-MC,19.41,57.0,-0.50,0.96,0.95,X40,ATH,FMCG
79,TCS,1.71,-35.45,93.45,24.88,279475.0,-164209.0,299064.0,4253.91,-45.26,44.0,X-LC,18.90,2.0,-0.59,1.98,2.97,X40,ATH,IT
1,ABBOTINDIA,-0.59,-12.44,34.85,18.07,54575.0,-22255.0,156600.0,35195.00,-25.47,44.0,X-MC,6.03,58.0,-0.41,1.04,3.65,X40,ATH,PHARMA
33,HCLTECH,3.55,-24.79,61.55,21.51,111998.0,-59961.0,181963.0,1872.35,-21.01,47.0,X-LC,18.44,8.0,-0.54,1.20,4.45,X40,ATH,IT
32,HAVELLS,0.78,-24.44,73.92,31.42,183205.0,-80149.0,247842.0,2052.62,-28.94,49.0,X-MC,14.30,63.0,-0.44,1.64,4.53,X40,ATH,ELECTRICAL

In [20]:
# top 5 to accumulate based on lowest CurrAlloc%
df_tmp = df_portfolio_features[df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])].sort_values(by = 'CurrAlloc%', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
10,BATAINDIA,-0.21,-56.21,208.76,35.20,117626.0,-72325.0,56345.0,2096.00,-26.06,48.0,X-SC,25.26,91.0,-0.61,0.37,11.74,X40,NTT,FOOTWEAR
64,RELAXO,2.74,-54.56,235.19,52.31,155131.0,-79200.0,65960.0,1176.00,-51.60,64.0,X-SC,18.14,92.0,-0.51,0.44,47.48,X40N,NTT,FOOTWEAR
60,QUESS,1.74,2.46,69.73,73.90,76296.0,2624.0,109417.0,424.00,-44.90,79.0,X-SC,6.01,80.0,0.03,0.72,49.16,XY24,NTT,MISC
28,GODREJCP,-0.22,-7.42,42.00,31.47,57787.0,-11026.0,137588.0,1469.04,-2.65,53.0,X-LC,9.59,32.0,-0.19,0.91,5.57,X40N,ATH,FMCG
35,HDFCLIFE,-1.17,-6.06,41.77,33.18,58782.0,-9072.0,140728.0,814.30,-26.65,45.0,X-LC,16.36,31.0,-0.15,0.93,5.35,X40,ATH,INSURANCE

In [21]:
# top 5 to accumulate based on CumlRnk
df_tmp = df_portfolio_features.sort_values(by = 'CumlRnk', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
47,ITC,1.30,-23.18,54.98,19.06,143673.0,-78848.0,261318.0,452.00,-57.95,54.0,X-LC,15.27,1.0,-0.55,1.73,5.29,X40,NTT,FMCG
79,TCS,1.71,-35.45,93.45,24.88,279475.0,-164209.0,299064.0,4253.91,-45.26,44.0,X-LC,18.90,2.0,-0.59,1.98,2.97,X40,ATH,IT
45,INFY,0.77,-22.15,72.44,34.24,176454.0,-69301.0,243587.0,1972.00,-38.68,47.0,X-LC,16.58,3.0,-0.39,1.61,6.70,X40,NTT,IT
81,TMPV,-0.71,-10.40,52.44,36.58,167187.0,-37025.0,318816.0,600.00,-81.44,59.0,X-LC,12.87,4.0,-0.22,2.11,32.88,XY24,NTT,AUTO
59,PIDILITIND,0.01,11.35,6.30,18.37,9899.0,16010.0,157120.0,1670.26,-22.05,74.0,X-LC,3.68,5.0,1.62,1.04,23.37,X40,ATH,CHEMICALS

In [22]:
# top 5 for average up
df_tmp = df_portfolio_features[(df_portfolio_features['Dev%_200'] > 5)].sort_values(by = 'CurrAlloc%', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
44,INDUSINDBK,-0.77,-31.64,94.38,32.89,49816.0,-24424.0,52782.0,1800.00,-348.60,56.0,L-MC,7.38,258.0,-0.49,0.35,29.92,XR,NTT,BANKS
3,ALKYLAMINE,-1.46,-23.84,154.23,93.63,118598.0,-24066.0,76897.0,4546.37,-18.40,55.0,H-SC,7.84,142.0,-0.20,0.51,45.20,SR,ATH,CHEMICALS
73,SONACOMS,0.39,3.56,34.31,39.09,35945.0,3605.0,104764.0,804.02,-17.90,53.0,M-MC,18.43,193.0,0.10,0.69,48.20,AR,ATH,AUTO
72,SIS,-1.02,-2.76,24.70,21.26,26668.0,-3065.0,107967.0,528.00,2575.13,61.0,H-SC,21.80,168.0,-0.11,0.71,60.53,OX40N,NTT,MISC
60,QUESS,1.74,2.46,69.73,73.90,76296.0,2624.0,109417.0,424.00,-44.90,79.0,X-SC,6.01,80.0,0.03,0.72,49.16,XY24,NTT,MISC

In [23]:
# top 5 RSP
df_tmp = df_portfolio_features.sort_values(by = 'RSP', ascending=False)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
18,COFFEEDAY,-1.13,-43.59,139.81,35.27,89550.0,-49498.0,64051.0,80.00,-55.73,54.0,L-SC,15.48,266.0,-0.55,0.42,57.95,XR,NTT,HOTELS
37,HONAUT,1.99,-5.05,59.36,51.31,108688.0,-9738.0,183100.0,58357.33,-21.04,66.0,X-SC,8.87,90.0,-0.09,1.21,39.11,X40N,ATH,ELECTRICAL
60,QUESS,1.74,2.46,69.73,73.90,76296.0,2624.0,109417.0,424.00,-44.90,79.0,X-SC,6.01,80.0,0.03,0.72,49.16,XY24,NTT,MISC
64,RELAXO,2.74,-54.56,235.19,52.31,155131.0,-79200.0,65960.0,1176.00,-51.60,64.0,X-SC,18.14,92.0,-0.51,0.44,47.48,X40N,NTT,FOOTWEAR
80,TITAGARH,3.97,-15.79,73.07,45.74,149015.0,-38242.0,203935.0,1548.00,12.11,66.0,H-SC,4.95,175.0,-0.26,1.35,55.60,XY24,NTT,ENGINEERING

In [24]:
# Top N allocation
df_tmp = df_portfolio_features.sort_values(by = 'CurrAlloc%', ascending=False)
top_n_values = [10, 25, 50]

sum_df = pd.DataFrame({
    'Top_N': top_n_values,
    'Sum_Alloc%': [df_tmp['CurrAlloc%'].head(n).sum() for n in top_n_values]
})

sum_df

   Top_N  Sum_Alloc%
0     10       19.63
1     25       42.84
2     50       72.80

In [25]:
# market-cap-wise allocation
df_tmp = df_portfolio_features[cols]
df_tmp.groupby(df_tmp['Conviction'].str[-2:])['CurrAlloc%'].sum().sort_values(ascending=False)

Conviction
SC    43.19
LC    31.28
MC    25.57
Name: CurrAlloc%, dtype: float64

In [26]:
# criteria-wise allocation
df_portfolio_features.groupby('Criteria')['CurrAlloc%'].sum().sort_values(ascending=False)

Criteria
XY24     27.87
X40      24.81
X40N     17.25
XR        8.95
OX40N     6.92
AR        6.78
XY25      6.59
SR        0.87
Name: CurrAlloc%, dtype: float64

In [27]:
# conviction-wise allocation
df_portfolio_features.groupby('Conviction')['CurrAlloc%'].sum().sort_values(ascending=False)

Conviction
X-LC    29.24
H-SC    22.76
X-MC    20.52
M-SC     9.96
X-SC     9.90
H-MC     2.71
M-MC     1.99
H-LC     1.20
M-LC     0.84
L-SC     0.57
L-MC     0.35
Name: CurrAlloc%, dtype: float64

In [28]:
# sector-wise stats
df_tmp = df_portfolio_features.groupby('Category')[['CurrAlloc%', 'Current', 'Current P/L', 'FTT Amt']].sum().sort_values(by=['Current', 'Current P/L'], ascending=False)
df_tmp['Current P/L%'] = round(df_tmp['Current P/L'] * 100 / df_tmp['Current'], 2)
df_tmp['FTT%'] = round(df_tmp['FTT Amt'] * 100 / df_tmp['Current'], 2)
cols = ['CurrAlloc%', 'Current P/L%', 'FTT%']
df_tmp[cols].sort_values(by=['CurrAlloc%'], ascending=False)

               CurrAlloc%  Current P/L%    FTT%
Category
FMCG                14.92        -17.32   58.47
FINANCE             10.91        -11.89   60.56
IT                  10.04        -48.39  122.58
MISC                 7.18        -23.35   76.94
AUTO                 6.84         -5.84   45.52
BANKS                5.90         -1.85   48.95
PAINTS               5.57        -16.69   36.95
INSURANCE            5.12         -7.05   43.26
PHARMA               4.92          0.08   30.84
ELECTRICAL           4.05        -15.36   56.08
CHEMICALS            2.20        -22.35   95.26
HEALTHCARE           2.01        -17.37   48.00
AC                   1.82        -16.36   47.91
APPARELS             1.81          1.86   31.11
FOOTWEAR             1.69        -73.20  142.65
TRAVEL               1.67        -77.69  166.66
DURABLES             1.53        -67.24  107.92
BREWERIES            1.48         -4.80   26.56
REALTY               1.47          0.02   16.41
CERAMICS             1.41        -43.55   87.16
ENGINEERING          1.35        -18.75   73.07
CABLES               1.31         25.20   55.52
REFINERIES           1.13        -17.24   46.90
CEMENT               1.07        -65.63  189.55
JEWELLERY            1.06       -100.99  170.82
ENTERTAINMENT        0.75        -70.54  172.25
HOTELS               0.42        -77.28  139.81
TEXTILES             0.41        -49.88   92.62

In [29]:
# money to be made criteria-wise
df_portfolio_features.groupby('Criteria')['FTT Amt'].agg(['sum', 'count']).sort_values(by='sum', ascending=False)

                sum  count
Criteria
XY24      3382488.0     21
X40       1933323.0     19
XR        1330777.0     13
AR        1158049.0      9
X40N      1116018.0     13
OX40N      745724.0     10
XY25       439706.0      5
SR         287627.0      2

In [30]:
# money to be made conviction-wise
df_portfolio_features.groupby('Conviction')['FTT Amt'].agg(['sum', 'count']).sort_values(by='sum', ascending=False)

                  sum  count
Conviction
H-SC        3344927.0     24
X-LC        1865440.0     21
X-MC        1619153.0     15
M-SC        1413608.0     14
X-SC        1305366.0      9
H-MC         289080.0      2
L-SC         204499.0      2
M-LC         164941.0      1
M-MC          85147.0      2
H-LC          51735.0      1
L-MC          49816.0      1

In [31]:
# money to be made criteria and conviction-wise
df_portfolio_features.groupby(['Conviction', 'Criteria'])['FTT Amt'].agg(['sum', 'count']).sort_values(by='sum', ascending=False)

                           sum  count
Conviction Criteria
X-LC       X40       1018463.0     10
H-SC       XY24      1004307.0      6
           AR         950845.0      5
M-SC       XY24       824438.0      6
H-SC       XR         793289.0      7
X-SC       XY24       773935.0      4
X-MC       X40        699324.0      7
           X40N       456134.0      4
X-LC       X40N       343989.0      6
M-SC       OX40N      321916.0      5
X-SC       X40N       315895.0      3
X-LC       XY24       310785.0      2
H-SC       OX40N      308859.0      4
           SR         287627.0      2
H-MC       XY24       243237.0      1
X-MC       XY25       237909.0      2
           XY24       225786.0      2
X-SC       X40        215536.0      2
M-SC       XR         193573.0      2
M-LC       XR         164941.0      1
X-LC       XY25       152595.0      2
L-SC       OX40N      114949.0      1
           XR          89550.0      1
M-SC       AR          73681.0      1
H-LC       AR          51735.0      1
L-MC       XR          49816.0      1
M-MC       XY25        49202.0      1
H-MC       AR          45843.0      1
X-LC       XR          39608.0      1
M-MC       AR          35945.0      1

In [32]:
# notebook execution time

end_time = time.time()
execution_time = round(end_time - start_time, 0)
print(f"Notebook execution time: {execution_time} seconds")

Notebook execution time: 28.0 seconds