<a href="https://colab.research.google.com/github/ankit-rathi/Quantvesting_v2/blob/main/myStocks_Portfolio_Analysis.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
'''
!pip install pandas==2.2.2 -qq
!pip install pyxirr -qq
!pip install ta -qq
!pip install yfinance==0.2.59 -qq
'''

'\n!pip install pandas==2.2.2 -qq\n!pip install pyxirr -qq\n!pip install ta -qq\n!pip install yfinance==0.2.59 -qq\n'

In [2]:
# import libraries

import numpy as np
import pandas as pd
import datetime
import warnings
warnings.filterwarnings('ignore')
import yfinance as yfin
import ta
import matplotlib.pyplot as plt
import requests

In [3]:
# notebook start time
import time
import datetime
import pytz

start_time = time.time()

# function to print date timestamp
def print_date_time():
  tz_NY = pytz.timezone('Asia/Kolkata')
  datetime_NY = datetime.datetime.now(tz_NY)
  print("Run date time (IST):", datetime_NY.strftime("%Y-%m-%d %H:%M:%S"))

In [4]:
# function to get booked and reserved amount
def get_amt():
  # fetch the JSON data from the URL
  url = "https://raw.githubusercontent.com/ankit-rathi/Tradevesting_v1/main/data/myPortfolioAmts.json"
  response = requests.get(url)
  pf_amts = response.json()  # parse the JSON data

  # extract values from the JSON
  py_booked_amt_dm = pf_amts["py_booked_amt_dm"]
  py_booked_amt_sv = pf_amts["py_booked_amt_sv"]
  cy_booked_amt_dm = pf_amts["cy_booked_amt_dm"]
  cy_booked_amt_sv = pf_amts["cy_booked_amt_sv"]
  reserve_amt_dm = pf_amts["reserve_amt_dm"]
  reserve_amt_sv = pf_amts["reserve_amt_sv"]

  # perform calculations
  py_booked_amt = py_booked_amt_dm + py_booked_amt_sv
  cy_booked_amt = cy_booked_amt_dm + cy_booked_amt_sv
  reserve_amt = reserve_amt_dm + reserve_amt_sv
  total_booked_amt = py_booked_amt + cy_booked_amt

  return total_booked_amt, reserve_amt, cy_booked_amt, py_booked_amt

gen_output = 0

In [5]:
# function to format the amount
def format_amt(number):
    abs_number = abs(number)

    if abs_number >= 1_00_00_000:  # Crores
        formatted_amt = f"{number / 1_00_00_000:.2f} C"
    elif abs_number >= 1_00_000:  # Lakhs
        formatted_amt = f"{number / 1_00_000:.2f} L"
    elif abs_number >= 1_000:  # Thousands
        formatted_amt = f"{number / 1_000:.2f} K"
    else:
        formatted_amt = f"{number:.2f}"

    return formatted_amt

# function to set start and end date
def get_start_end_date():
  start_date = (datetime.date.today() + datetime.timedelta(days=-365)).strftime('%Y-%m-%d')
  end_date = (datetime.date.today() + datetime.timedelta(days=1)).strftime('%Y-%m-%d')
  return start_date, end_date

# function to fetch my portfolio csv
def get_mypfs_df():
  mypfs_df = pd.read_csv('https://raw.githubusercontent.com/ankit-rathi/Tradevesting_v1/main/data/myPortfolioStocks.csv')
  return mypfs_df

# function to fetch my prospects csv
def get_mypps_df():
  mypps_df = pd.read_csv('https://raw.githubusercontent.com/ankit-rathi/Tradevesting_v1/main/data/myProspectsScrips.csv')
  return mypps_df

# function to fetch screener data
def get_myscreen_df():
  myscreen_df = pd.read_csv('https://raw.githubusercontent.com/ankit-rathi/Tradevesting_v1/main/data/myScreenerDB.csv')
  return myscreen_df

# function to fetch momentum data
def get_myinvmt_df():
  myinvmt_df = pd.read_csv('https://raw.githubusercontent.com/ankit-rathi/Tradevesting_v1/main/data/myInvestments.csv')
  return myinvmt_df

# function to get the stock ids
def get_stock_ids(df_pf):
  stock_n100 = df_pf['Symbol'].unique()

  exclude = ['CADILAHC','MMTC', 'MASFIN']

  stock_ids = df_pf[~df_pf['Symbol'].isin(exclude) ]['Symbol'].unique()

  #mypf = mypf[mypf.Forecast.notnull()]
  #stock_ids = mypf['Symbol'].unique()

  #stock_ids.sort()
  return stock_ids

# get features from screener data
def get_screener_features():
  myscreen_df = get_myscreen_df()
  cols = ['Symbol', 'EPS', 'MedPE', 'ROCE%', 'ROE%', 'CapType']
  return myscreen_df[cols]

# get relative strength
def get_relative_strength(stock_list):

    # Dictionary to store stock tickers and their corresponding percentage price change
    stock_changes = {}

    # Loop through each stock and fetch its price data
    for stock in stock_list:
        try:
            # Download the stock data for the given date range
            stock_data = yfin.Ticker(stock + '.NS').history(period='1mo', interval='1d')[map(str.title, ['open', 'close', 'low', 'high', 'volume'])]

            # Calculate the percentage change for the stock
            if len(stock_data) > 0:
                start_price = stock_data['Close'].iloc[0]
                end_price = stock_data['Close'].iloc[-1]
                percent_change = round(((end_price - start_price) / start_price) * 100, 2)
                stock_changes[stock] = percent_change
            else:
                stock_changes[stock] = np.nan  # If no data is available, set to NaN

        except Exception as e:
            print(f"Error fetching data for {stock}: {e}")
            stock_changes[stock] = np.nan

    # Create a DataFrame with stock tickers and their percentage changes
    df = pd.DataFrame(list(stock_changes.items()), columns=['Symbol', 'Percent_Change'])

    # Drop any stocks with missing data (NaN values)
    df = df.dropna()

    # Calculate the percentile rank based on percentage change
    df['RSP'] = round(df['Percent_Change'].rank(pct=True) * 100, 2)
    cols = ['Symbol', 'RSP']
    df = df[cols]
    # Sort by percentile rank (optional)
    df = df.sort_values(by='RSP', ascending=False).reset_index(drop=True)

    return df

In [6]:
# function to get stock technicals
def stock_prec_dev(stock_symbol):
    #stock_symbol = 'ULTRACEMCO.NS'
    short_window = 20
    mid_window = 50
    long_window = 200
    moving_avg = 'SMA'

    start = datetime.datetime(*map(int, start_date.split('-')))
    end = datetime.datetime(*map(int, end_date.split('-')))

    stock_df = yfin.Ticker(stock_symbol + '.NS').history(period='max', interval='1d')[map(str.title, ['open', 'close', 'low', 'high', 'volume'])]

    stock_df['Max'] = round(max(stock_df['Close']),2)
    stock_df = stock_df[(stock_df.index <= end_date) & (stock_df.index >= start_date)]
    stock_df['200_SMA'] = round(stock_df['Close'].rolling(window = 200, min_periods = 1).mean(),0)
    stock_df['Dev%_200'] = round((stock_df['Close'] - stock_df['200_SMA'])*100/stock_df['200_SMA'],2)
    stock_df.dropna(axis = 0, inplace = True) # remove any null rows

    stock_df['20_SMA'] = stock_df['Close'].rolling(window=20).mean()
    stock_df['50_SMA'] = stock_df['Close'].rolling(window=50).mean()
    stock_df['Symbol'] = stock_symbol

    stock_df['Close'] = round(stock_df['Close'],2)
    stock_df['Min'] = round(min(stock_df['Close']),2)
    stock_df['RSI_14'] = ta.momentum.RSIIndicator(close=stock_df['Close'], window=14).rsi()
    stock_df['RSI_14'] = round(stock_df['RSI_14'],0)
    stock_df['Prev_Close'] = stock_df['Close'].shift(1)
    stock_df.drop(['Open', 'Low', 'High', 'Volume'], axis=1, inplace=True)
    stock_df = stock_df.tail(1)

    max_SMA = max(stock_df['20_SMA'].item(), stock_df['50_SMA'].item(), stock_df['200_SMA'].item())
    min_SMA = min(stock_df['20_SMA'].item(), stock_df['50_SMA'].item(), stock_df['200_SMA'].item())
    ABS_Spread = max_SMA - min_SMA
    stock_df['Spread%'] = round((ABS_Spread / stock_df['200_SMA'].item()) * 100,2)

    return stock_df

# function to compute stock attributes
def get_common_features(stock_ids, df_mypf):

  df_prec_dev = pd.DataFrame()
  df_tmp = get_screener_features()
  df_rs = get_relative_strength(stock_ids)

  for stock_id in stock_ids:
      tmp = stock_prec_dev(stock_id)
      tmp = tmp.reset_index()
      df_prec_dev = pd.concat([df_prec_dev, tmp], ignore_index = True)
  df_prec_dev = pd.merge(df_prec_dev, df_mypf, on= 'Symbol')
  df_prec_dev = pd.merge(df_prec_dev, df_tmp, on= 'Symbol', how='left')
  df_prec_dev = pd.merge(df_prec_dev, df_rs, on= 'Symbol', how='left')
  #print(df_prec_dev.columns)
  df_prec_dev['Curr_PE'] = round(df_prec_dev['Close']/df_prec_dev['EPS'],1)
  df_prec_dev['Dev%_PE'] = round((df_prec_dev['Curr_PE'] - df_prec_dev['MedPE'])*100/df_prec_dev['MedPE'],2)
  df_prec_dev['Conviction'] = df_prec_dev['Conviction'] + '-' + df_prec_dev['CapType']
  return df_prec_dev

# function to arrange stock features
def arrange_features(df_stocks, common_cols, diff_cols):
  df_stocks_common = df_stocks[common_cols].drop_duplicates()
  df_stocks_diff = df_stocks[diff_cols]
  df_stocks_diff['Investment'] = df_stocks_diff['AvgCost'] * df_stocks_diff['Shares']
  df_stocks_diff = df_stocks_diff.groupby(['Symbol'])[['Shares', 'Investment']].aggregate(['sum']).reset_index()
  df_stocks_diff.columns = ['Symbol', 'Shares', 'Investment']
  df_stocks_diff['AvgCost'] = round(df_stocks_diff['Investment']/df_stocks_diff['Shares'],2)
  df_stocks = pd.merge(df_stocks_diff, df_stocks_common, on='Symbol')
  return df_stocks

# plot fact distribution across dimension
def plot_pie_chart(df, dimension, fact):
  # grouping the data by category and calculating the sum of fact for each type
  grouped_data = df.groupby(dimension)[fact].sum()

  # sorting the grouped data in descending order
  grouped_data = grouped_data.sort_values(ascending=False)

  # creating a pie chart
  grouped_data.plot.pie(autopct='%1.1f%%', startangle=90, figsize=(6, 6))

  # adding a title and displaying the plot
  plt.title(f'{dimension} {fact} Distribution')
  plt.ylabel('')  # To hide the y-label
  plt.show()

In [7]:
# function to get portfolio features

def get_portfolio_features(df_common_features):

  print_date_time()
  print('-------------------')

  #df_common_features["Target"] = df_common_features["Target"].fillna(df_common_features["Max"])
  df_common_features['NTT'] = np.where(df_common_features['Strategy']== 'NTT', df_common_features["Target"], df_common_features['Max'])
  df_common_features['LTT'] = np.where(df_common_features['Strategy']== 'BTT', df_common_features["Target"], df_common_features['Max'])
  df_common_features['BOL'] = df_common_features['Min']

  tmp_df = df_common_features[df_common_features['Symbol'].isin(mypf_df[mypf_df['InPortfolio'] != 'NA'].Symbol.values)]
  print('qualified stocks: '+str(len(tmp_df['Symbol'].unique())))
  tmp_df1 = tmp_df[tmp_df['LatestQtr'] == 1]
  print('with latest results: '+str(len(tmp_df1['Symbol'].unique())))
  tmp_df1 = tmp_df1[tmp_df1['StarStock'] == 1]
  print('still star stocks: '+str(len(tmp_df1['Symbol'].unique())))
  tmp_df['Investment'] = tmp_df['AvgCost'] * tmp_df['Shares']
  tmp_df['Current'] = round(tmp_df['Close'] * tmp_df['Shares'],0)
  tmp_df['Previous'] = tmp_df['Prev_Close'] * tmp_df['Shares']
  tmp_df['EstimatedST'] = tmp_df['NTT'] * tmp_df['Shares']
  tmp_df['EstimatedLT'] = tmp_df['LTT'] * tmp_df['Shares']
  tmp_df['Current P/L'] = round((tmp_df['Current'] - tmp_df['Investment']),0)
  tmp_df['Today P/L%'] = round((tmp_df['Current'] - tmp_df['Previous'])*100/tmp_df['Previous'],2)
  tmp_df['Current P/L%'] = round((tmp_df['Current'] - tmp_df['Investment'])*100/tmp_df['Investment'],2)
  tmp_df['EstimatedST P/L%'] = round((tmp_df['EstimatedST'] - tmp_df['Investment'])*100/tmp_df['Investment'],2)
  tmp_df['EstimatedLT P/L%'] = round((tmp_df['EstimatedLT'] - tmp_df['Investment'])*100/tmp_df['Investment'],2)
  tmp_df['NTT%'] = round((tmp_df['NTT'] - tmp_df['Close'])*100/tmp_df['Close'],2)
  tmp_df['LTT%'] = round((tmp_df['LTT'] - tmp_df['Close'])*100/tmp_df['Close'],2)
  tmp_df['Gained%'] = round((tmp_df['Close'] - tmp_df['BOL'])*100/tmp_df['BOL'],2)
  investment = round(sum(tmp_df['AvgCost']*tmp_df['Shares']),0)
  current = round(sum(tmp_df['Close']*tmp_df['Shares']),0)
  tmp_df['InitAlloc%'] = round(tmp_df['Investment']*100/investment,2)
  tmp_df['CurrAlloc%'] = round(tmp_df['Current']*100/current,2)
  tmp_df['FTT'] = tmp_df['LTT']
  tmp_df.loc[tmp_df['Strategy'] == 'NTT', 'FTT'] = tmp_df['NTT']
  tmp_df['FTT%'] = tmp_df['LTT%']
  tmp_df.loc[tmp_df['Strategy'] == 'NTT', 'FTT%'] = tmp_df['NTT%']
  tmp_df['FTT Amt'] = round(tmp_df['FTT%'] * tmp_df['Current']/100,0)
  tmp_df['OTT%'] = round((tmp_df['FTT'] - tmp_df['AvgCost'])*100/tmp_df['AvgCost'],2)
  tmp_df['RRR Ind'] = round(tmp_df['Current P/L']/tmp_df['FTT Amt'],2)
  tmp_df['Risk Ind'] = round(tmp_df['Current P/L%']*tmp_df['CurrAlloc%'],0)

  return tmp_df

# function to print portfolio features
def print_portfolio_stats(df_portfolio_features, myinvmt_df):
  from pyxirr import xirr

  total_booked_amt, reserve_amt, cy_booked_amt, py_booked_amt = get_amt()

  dates = myinvmt_df['Date'].values
  dates = np.append(dates, datetime.date.today().strftime('%d-%b-%y'))
  investment = myinvmt_df['Investment'].values
  dates= pd.to_datetime(dates)

  current = round(sum(df_portfolio_features['Close']*df_portfolio_features['Shares']),0) + reserve_amt
  investment_xirr = np.append(investment, current)
  cagr = round(xirr(pd.DataFrame({"dates": dates, "amounts": investment_xirr}))*100,2)

  investment = -sum(investment)
  invested = round(sum(df_portfolio_features['AvgCost']*df_portfolio_features['Shares']),0) + reserve_amt
  previous = round(sum(df_portfolio_features['Prev_Close']*df_portfolio_features['Shares']),0) + reserve_amt
  cy_invested = investment + py_booked_amt

  today_pnl_amount = current-previous
  today_pnl_percentage = round((current-previous)*100/previous,2)

  curr_pnl_amount = current-invested
  curr_pnl_percentage = round((curr_pnl_amount)*100/(cy_invested),2)

  cy_pnl_amount = cy_booked_amt + curr_pnl_amount
  cy_pnl_percentage = round((cy_pnl_amount)*100/cy_invested,2)

  overall_pnl_amount = total_booked_amt + curr_pnl_amount
  overall_pnl_percentage = round((overall_pnl_amount)*100/investment,2)

  estimate_st = round(sum(df_portfolio_features['FTT']*df_portfolio_features['Shares']),0)  + reserve_amt
  est_st_pnl_amount = estimate_st-current
  est_st_pnl_percentage = round((est_st_pnl_amount)*100/current,2)

  estimate_lt = round(sum(df_portfolio_features['LTT']*df_portfolio_features['Shares']),0)  + reserve_amt
  est_lt_pnl_amount = estimate_lt-current
  est_lt_pnl_percentage = round((est_lt_pnl_amount)*100/current,2)

  total_profit = round(sum(df_portfolio_features[df_portfolio_features['Current P/L%'] > 0]['Current']) - sum(df_portfolio_features[df_portfolio_features['Current P/L%'] > 0]['Investment']),0)
  total_loss = round(sum(df_portfolio_features[df_portfolio_features['Current P/L%'] < 0]['Current']) - sum(df_portfolio_features[df_portfolio_features['Current P/L%'] < 0]['Investment']),0)

  cy_booked_percentage = round((cy_booked_amt)*100/current,2)
  py_booked_percentage = round((py_booked_amt)*100/investment,2)
  total_booked_percentage = round((total_booked_amt)*100/investment,2)

  print('-------------------')
  print('Initial Investment: ', format_amt(investment))
  print('CY Investment: ', format_amt(cy_invested))
  print('Reserve: ', format_amt(reserve_amt))
  print('Current: ',  format_amt(current))
  print('-------------------')
  print('Today PnL: '+ '{} ({}%)'.format(format_amt(today_pnl_amount), today_pnl_percentage))
  print('Current PnL: '+ '{} ({}%)'.format(format_amt(curr_pnl_amount), curr_pnl_percentage))
  print('CY Booked + Current PnL: '+ '{} ({}%)'.format(format_amt(cy_pnl_amount), cy_pnl_percentage))
  print('-------------------')
  print('Total profit: ', format_amt(total_profit))
  print('Total loss: ', format_amt(total_loss))
  print('-------------------')
  print('Total Booked + Current PnL: '+ '{} ({}%)'.format(format_amt(overall_pnl_amount), overall_pnl_percentage))
  print('Total Booked PnL: '+ '{} ({}%)'.format(format_amt(total_booked_amt), total_booked_percentage))
  print('Curr Year Booked PnL: '+ '{} ({}%)'.format(format_amt(cy_booked_amt), cy_booked_percentage))
  print('Prev Year Booked PnL: '+ '{} ({}%)'.format(format_amt(py_booked_amt), py_booked_percentage))
  print('===================')
  print('Est FTT: ',  format_amt(estimate_st))
  print('Est FTT PnL: '+ '{} ({}%)'.format(format_amt(est_st_pnl_amount), est_st_pnl_percentage))

  print('===================')
  print('Deployed: ', format_amt(investment))

  print('Current: ', format_amt(current))

  print('CAGR/XIRR %: '+'{}%'.format(cagr))

In [8]:
# get start and end date
start_date, end_date = get_start_end_date()

# get portfolio and prospects data
mypfs_df = get_mypfs_df()
mypps_df = get_mypps_df()
myinvmt_df = get_myinvmt_df()

# merge above datasets
mypf_df = pd.merge(mypfs_df, mypps_df, on="Symbol")

# seggregate dm and sv portfolio
dm_pf = mypf_df[mypf_df['InPortfolio'] == 'DM']
sv_pf = mypf_df[mypf_df['InPortfolio'] == 'SV']

# build portfolio stock dataframe
dm_stocks = get_stock_ids(dm_pf)
sv_stocks = get_stock_ids(sv_pf)
df_stocks = pd.concat([dm_pf,sv_pf], ignore_index = True)

# arrange common and diff stock features
common_cols = ['Symbol', 'Target', 'Criteria', 'Strategy', 'CumlRnk', 'LatestQtr', 'StarStock', 'Conviction', 'Category', 'InFolio', 'XIRR', 'MBQ']
diff_cols = ['Symbol', 'AvgCost', 'Shares']
df_stocks = arrange_features(df_stocks, common_cols, diff_cols)

# get common features
stock_ids = df_stocks['Symbol'].values
df_common_features = get_common_features(stock_ids, df_stocks)

df_common_features.reset_index(drop=True, inplace=True)
df_common_features.drop(['Date'], axis=1, inplace=True)
# get and print portfolio features
df_portfolio_features = get_portfolio_features(df_common_features)

print_portfolio_stats(df_portfolio_features, myinvmt_df)

df = df_portfolio_features
#plot_pie_chart(df, 'CapType', 'Current')
list_ox40n = list(df[df['MBQ'].str.contains('OX40N', na=False)]['Symbol'].values)

Run date time (IST): 2026-03-19 09:54:13
-------------------
qualified stocks: 86
with latest results: 26
still star stocks: 16
-------------------
Initial Investment:  1.36 C
CY Investment:  1.62 C
Reserve:  1.61 K
Current:  1.32 C
-------------------
Today PnL: -2.25 L (-1.67%)
Current PnL: -44.90 L (-27.63%)
CY Booked + Current PnL: -29.01 L (-17.85%)
-------------------
Total profit:  66.36 K
Total loss:  -45.56 L
-------------------
Total Booked + Current PnL: -2.03 L (-1.49%)
Total Booked PnL: 42.87 L (31.64%)
Curr Year Booked PnL: 15.89 L (12.02%)
Prev Year Booked PnL: 26.98 L (19.91%)
===================
Est FTT:  2.48 C
Est FTT PnL: 1.16 C (87.47%)
===================
Deployed:  1.36 C
Current:  1.32 C
CAGR/XIRR %: -1.21%

In [9]:
# top 5 near their targets
cols = ['Symbol', 'Today P/L%', 'Current P/L%', 'FTT%', 'OTT%', 'FTT Amt', 'Current P/L', 'Current', 'FTT', 'Dev%_PE', 'RSI_14','Conviction', 'Spread%',  'CumlRnk', 'RRR Ind', 'CurrAlloc%', 'Gained%', 'Criteria', 'Strategy', 'Category']
df_tmp = df_portfolio_features[~df_portfolio_features['Symbol'].isin(['ENRIN','BLUSPRING','DIGITIDE'])]
df_tmp = df_tmp.sort_values(by = 'FTT Amt', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
50,MASFIN,-0.65,-8.67,33.10,21.57,29621.0,-8490.0,89490.0,397.04,-21.41,39.0,H-SC,1.91,167.0,-0.29,0.68,22.71,XR,ATH,FINANCE
77,TTKPRESTIG,1.58,-36.92,58.68,0.09,37302.0,-37209.0,63568.0,770.00,47.49,42.0,M-SC,17.51,250.0,-1.00,0.48,7.40,OX40N,NTT,DURABLES
37,ICICIGI,-1.59,-4.54,25.02,19.34,47794.0,-9086.0,191023.0,2252.93,-19.59,34.0,X-MC,2.53,66.0,-0.19,1.44,5.60,X40,ATH,INSURANCE
67,SONACOMS,-1.89,-13.14,60.13,39.09,52835.0,-13291.0,87868.0,804.02,-31.14,47.0,M-MC,8.43,193.0,-0.25,0.66,24.30,AR,ATH,AUTO
2,ABBOTINDIA,0.00,-11.52,33.44,18.07,52919.0,-20605.0,158250.0,35195.00,-24.65,42.0,X-MC,10.80,58.0,-0.39,1.20,0.32,X40,ATH,PHARMA

In [10]:
# top 5 today
df_tmp = df_portfolio_features.sort_values(by = 'Today P/L%', ascending=False)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
61,ROUTE,7.91,-63.51,360.88,68.16,175211.0,-84515.0,48551.0,2215.45,-70.48,41.0,H-SC,35.74,141.0,-0.48,0.37,7.91,SR,ATH,IT
80,VALIANTORG,2.77,-49.35,243.81,74.15,202050.0,-80733.0,82872.0,838.00,-249.10,58.0,H-SC,29.44,145.0,-0.40,0.63,23.33,XR,NTT,CHEMICALS
77,TTKPRESTIG,1.58,-36.92,58.68,0.09,37302.0,-37209.0,63568.0,770.00,47.49,42.0,M-SC,17.51,250.0,-1.00,0.48,7.40,OX40N,NTT,DURABLES
68,STARHEALTH,0.63,-10.10,63.80,47.26,161249.0,-28381.0,252742.0,761.00,41.86,53.0,H-SC,0.68,173.0,-0.18,1.91,35.41,XY24,NTT,INSURANCE
14,BOSCH-HCIL,0.61,-43.39,76.64,-0.01,55446.0,-55459.0,72346.0,2282.00,14704.35,42.0,M-SC,3.61,231.0,-1.00,0.55,2.76,OX40N,BTT,AC

In [11]:
# bottom 5 today
df_tmp = df_portfolio_features.sort_values(by = 'Today P/L%', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
34,HDFCBANK,-5.12,-4.31,34.14,28.37,76737.0,-10113.0,224772.0,1073.00,-18.56,27.0,X-LC,10.15,26.0,-0.13,1.70,0.00,X40,BTT,BANKS
76,TRIDENT,-4.09,-37.24,104.78,28.51,60664.0,-34358.0,57897.0,48.00,-19.26,43.0,M-SC,13.44,223.0,-0.57,0.44,6.26,XR,NTT,TEXTILES
23,DIXON,-3.53,-24.74,83.25,37.92,163411.0,-64509.0,196289.0,18931.72,-67.97,45.0,X-MC,27.36,54.0,-0.39,1.48,5.38,X40N,ATH,IT
82,VOLTAS,-3.23,7.70,34.82,45.20,71905.0,14763.0,206505.0,1856.00,23.31,38.0,X-MC,6.77,79.0,0.21,1.56,15.02,XY25,NTT,AC
75,TMPV,-3.22,-28.46,90.90,36.58,231416.0,-101258.0,254583.0,600.00,-84.72,33.0,X-LC,4.38,4.0,-0.44,1.93,0.06,XY24,NTT,AUTO

In [12]:
# top 5 to exit based on CumlRnk
df_tmp = df_portfolio_features[~df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])]
df_tmp = df_tmp[(df_tmp['Current P/L%'] > -1) & (df_tmp['Current P/L%'] < 1)].sort_values(by = 'CumlRnk', ascending=False)
df_tmp[cols].head()

Empty DataFrame
Columns: [Symbol, Today P/L%, Current P/L%, FTT%, OTT%, FTT Amt, Current P/L, Current, FTT, Dev%_PE, RSI_14, Conviction, Spread%, CumlRnk, RRR Ind, CurrAlloc%, Gained%, Criteria, Strategy, Category]
Index: []

In [13]:
# OX40N stocks to exit
df_tmp = df_portfolio_features[(df_portfolio_features['Symbol'].isin(list_ox40n))].sort_values(by = 'Current P/L%', ascending=False)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
26,FINCABLES,-2.87,7.88,92.73,107.91,147698.0,11633.0,159277.0,1641.55,-3.09,49.0,M-SC,8.08,220.0,0.08,1.20,19.83,OX40N,ATH,CABLES
18,CERA,-1.98,-36.15,94.02,23.89,105601.0,-63585.0,112318.0,9475.00,-38.42,51.0,H-SC,18.14,153.0,-0.60,0.85,7.94,OX40N,NTT,CERAMICS
66,SIS,-1.54,-36.78,91.83,21.26,64455.0,-40843.0,70189.0,528.00,1639.38,33.0,H-SC,13.57,168.0,-0.63,0.53,1.16,OX40N,NTT,MISC
77,TTKPRESTIG,1.58,-36.92,58.68,0.09,37302.0,-37209.0,63568.0,770.00,47.49,42.0,M-SC,17.51,250.0,-1.00,0.48,7.40,OX40N,NTT,DURABLES
70,SYMPHONY,-1.92,-38.72,63.13,-0.03,66210.0,-66262.0,104879.0,1306.00,-50.83,45.0,M-SC,14.84,205.0,-1.00,0.79,6.06,OX40N,NTT,DURABLES

In [14]:
# top 5 to book for rotation
df_tmp = df_portfolio_features[(df_portfolio_features['Current P/L%'] > 20) ].sort_values(by = 'CumlRnk', ascending=False)
df_tmp[cols].head()

Empty DataFrame
Columns: [Symbol, Today P/L%, Current P/L%, FTT%, OTT%, FTT Amt, Current P/L, Current, FTT, Dev%_PE, RSI_14, Conviction, Spread%, CumlRnk, RRR Ind, CurrAlloc%, Gained%, Criteria, Strategy, Category]
Index: []

In [15]:
# top 5 to monitor for exit
df_tmp = df_portfolio_features[~df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])]
df_tmp = df_tmp[(df_tmp['Current P/L%'] > 0) ].sort_values(by = 'Dev%_PE', ascending=False)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
26,FINCABLES,-2.87,7.88,92.73,107.91,147698.0,11633.0,159277.0,1641.55,-3.09,49.0,M-SC,8.08,220.0,0.08,1.20,19.83,OX40N,ATH,CABLES
1,ABB,-0.86,15.28,26.28,45.57,79256.0,39965.0,301584.0,7934.00,-25.90,61.0,H-MC,12.59,125.0,0.50,2.28,33.92,AR,NTT,ELECTRICAL

In [16]:
# top 5 to book for rotation from weak conviction
df_tmp = df_portfolio_features[~df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])]
df_tmp = df_tmp[~df_tmp['Criteria'].isin(['XY25','XY24','X40', 'X40N'])].sort_values(by = 'RRR Ind', ascending=False)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
1,ABB,-0.86,15.28,26.28,45.57,79256.0,39965.0,301584.0,7934.00,-25.90,61.0,H-MC,12.59,125.0,0.50,2.28,33.92,AR,NTT,ELECTRICAL
26,FINCABLES,-2.87,7.88,92.73,107.91,147698.0,11633.0,159277.0,1641.55,-3.09,49.0,M-SC,8.08,220.0,0.08,1.20,19.83,OX40N,ATH,CABLES
40,INDIAMART,-1.74,-11.41,133.36,106.72,145709.0,-14076.0,109260.0,4810.62,-59.96,38.0,H-SC,10.47,140.0,-0.10,0.83,9.30,AR,ATH,MISC
85,ZYDUSLIFE,-1.74,-6.79,45.50,35.63,88886.0,-14221.0,195353.0,1286.17,-18.92,42.0,H-MC,5.30,120.0,-0.16,1.48,8.76,AR,ATH,PHARMA
84,WIPRO,-1.98,-21.89,120.53,72.27,159537.0,-37085.0,132363.0,420.00,-29.71,28.0,M-LC,16.54,98.0,-0.23,1.00,0.00,XR,NTT,IT

In [17]:
# top 5 to accumulate based on lowest RSI_14
df_tmp = df_portfolio_features[df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])].sort_values(by = 'RSI_14', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
12,BATAINDIA,-2.44,-57.64,219.17,35.20,119461.0,-74164.0,54506.0,2096.00,-28.52,15.0,X-SC,29.28,91.0,-0.62,0.41,0.00,X40,NTT,FOOTWEAR
53,PGHH,-0.41,-25.23,76.56,32.01,122227.0,-53872.0,159648.0,17616.87,-49.41,16.0,X-MC,13.88,57.0,-0.44,1.21,0.00,X40,ATH,FMCG
58,RELAXO,-2.71,-64.01,323.25,52.31,168853.0,-92924.0,52236.0,1176.00,-61.67,21.0,X-SC,23.56,92.0,-0.55,0.40,0.83,X40N,NTT,FOOTWEAR
3,ACC,-2.21,-38.50,184.26,74.81,303830.0,-103236.0,164892.0,3906.00,-56.56,23.0,X-SC,15.83,85.0,-0.34,1.25,0.07,XY24,BTT,CEMENT
73,TCS,-1.47,-29.40,79.29,26.57,259320.0,-136220.0,327053.0,4311.59,-40.35,25.0,X-LC,16.25,2.0,-0.53,2.47,0.55,X40,ATH,IT

In [18]:
# top 5 to accumulate based on Spread and CumlRnk
df_tmp = df_portfolio_features[df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])]
df_tmp = df_tmp[(df_tmp['CumlRnk'] < 100)].sort_values(by = 'Spread%', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
78,UNITDSPR,-1.86,-4.82,26.88,20.77,59905.0,-11284.0,222860.0,1644.00,-15.56,39.0,X-MC,0.99,64.0,-0.19,1.69,1.57,X40N,NTT,BREWERIES
37,ICICIGI,-1.59,-4.54,25.02,19.34,47794.0,-9086.0,191023.0,2252.93,-19.59,34.0,X-MC,2.53,66.0,-0.19,1.44,5.60,X40,ATH,INSURANCE
38,ICICIPRULI,-2.19,-4.72,37.20,30.73,69828.0,-9294.0,187711.0,790.00,-30.32,27.0,X-MC,3.00,78.0,-0.13,1.42,7.39,X40,ATH,INSURANCE
59,RELIANCE,-0.33,-9.91,39.08,25.30,70755.0,-19911.0,181052.0,1952.00,-12.34,49.0,X-LC,3.38,21.0,-0.28,1.37,20.88,XY25,BTT,REFINERIES
65,SIEMENS,-2.33,-15.48,48.49,25.51,76272.0,-28800.0,157295.0,4671.50,32.11,46.0,H-LC,3.53,51.0,-0.38,1.19,15.83,AR,ATH,ELECTRICAL

In [19]:
# top 5 to accumulate based on lowest Gained%
df_tmp = df_portfolio_features[df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])].sort_values(by = 'Gained%', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
12,BATAINDIA,-2.44,-57.64,219.17,35.20,119461.0,-74164.0,54506.0,2096.00,-28.52,15.0,X-SC,29.28,91.0,-0.62,0.41,0.0,X40,NTT,FOOTWEAR
21,DABUR,-2.42,-13.80,66.70,43.70,142629.0,-34232.0,213836.0,735.00,-21.68,27.0,X-MC,3.93,70.0,-0.24,1.62,0.0,XY24,BTT,FMCG
20,COLPAL,-1.42,-27.33,94.71,41.51,181275.0,-71965.0,191400.0,3726.84,-12.13,29.0,X-MC,4.34,62.0,-0.40,1.45,0.0,XY25,ATH,FMCG
53,PGHH,-0.41,-25.23,76.56,32.01,122227.0,-53872.0,159648.0,17616.87,-49.41,16.0,X-MC,13.88,57.0,-0.44,1.21,0.0,X40,ATH,FMCG
45,ITC,-1.25,-20.91,50.54,19.06,135965.0,-71142.0,269024.0,452.00,-56.73,34.0,X-LC,17.56,1.0,-0.52,2.03,0.0,X40,NTT,FMCG

In [20]:
# top 5 to accumulate based on lowest CurrAlloc%
df_tmp = df_portfolio_features[df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])].sort_values(by = 'CurrAlloc%', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
58,RELAXO,-2.71,-64.01,323.25,52.31,168853.0,-92924.0,52236.0,1176.00,-61.67,21.0,X-SC,23.56,92.0,-0.55,0.40,0.83,X40N,NTT,FOOTWEAR
12,BATAINDIA,-2.44,-57.64,219.17,35.20,119461.0,-74164.0,54506.0,2096.00,-28.52,15.0,X-SC,29.28,91.0,-0.62,0.41,0.00,X40,NTT,FOOTWEAR
54,QUESS,-1.65,-26.32,136.03,73.90,107031.0,-28111.0,78682.0,424.00,-60.33,37.0,X-SC,20.25,80.0,-0.26,0.60,2.54,XY24,NTT,MISC
36,HONAUT,-1.69,-25.46,102.98,51.31,148034.0,-49088.0,143750.0,58357.33,-38.04,28.0,X-SC,14.74,90.0,-0.33,1.09,0.00,X40N,ATH,ELECTRICAL
51,MEDANTA,-0.96,-11.55,43.71,27.12,68246.0,-20383.0,156134.0,1486.00,-14.24,32.0,X-SC,10.48,87.0,-0.30,1.18,0.39,XY24,NTT,HEALTHCARE

In [21]:
# top 5 to accumulate based on CumlRnk
df_tmp = df_portfolio_features.sort_values(by = 'CumlRnk', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
45,ITC,-1.25,-20.91,50.54,19.06,135965.0,-71142.0,269024.0,452.00,-56.73,34.0,X-LC,17.56,1.0,-0.52,2.03,0.00,X40,NTT,FMCG
73,TCS,-1.47,-29.40,79.29,26.57,259320.0,-136220.0,327053.0,4311.59,-40.35,25.0,X-LC,16.25,2.0,-0.53,2.47,0.55,X40,ATH,IT
43,INFY,-2.08,-15.54,58.94,34.24,155760.0,-48619.0,264269.0,1972.00,-33.60,29.0,X-LC,14.49,3.0,-0.31,2.00,0.63,X40,NTT,IT
75,TMPV,-3.22,-28.46,90.90,36.58,231416.0,-101258.0,254583.0,600.00,-84.72,33.0,X-LC,4.38,4.0,-0.44,1.93,0.06,XY24,NTT,AUTO
33,HCLTECH,-1.43,-13.18,42.64,23.83,89559.0,-31889.0,210035.0,1908.19,-8.60,34.0,X-LC,11.18,8.0,-0.36,1.59,1.26,X40,ATH,IT

In [22]:
# top 5 for average up
df_tmp = df_portfolio_features[(df_portfolio_features['Dev%_200'] > 5)].sort_values(by = 'CurrAlloc%', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
67,SONACOMS,-1.89,-13.14,60.13,39.09,52835.0,-13291.0,87868.0,804.02,-31.14,47.0,M-MC,8.43,193.0,-0.25,0.66,24.30,AR,ATH,AUTO
1,ABB,-0.86,15.28,26.28,45.57,79256.0,39965.0,301584.0,7934.00,-25.90,61.0,H-MC,12.59,125.0,0.50,2.28,33.92,AR,NTT,ELECTRICAL

In [23]:
# top 5 RSP
df_tmp = df_portfolio_features.sort_values(by = 'RSP', ascending=False)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
1,ABB,-0.86,15.28,26.28,45.57,79256.0,39965.0,301584.0,7934.00,-25.90,61.0,H-MC,12.59,125.0,0.50,2.28,33.92,AR,NTT,ELECTRICAL
26,FINCABLES,-2.87,7.88,92.73,107.91,147698.0,11633.0,159277.0,1641.55,-3.09,49.0,M-SC,8.08,220.0,0.08,1.20,19.83,OX40N,ATH,CABLES
69,SURYODAY,-0.50,-27.96,70.78,23.03,91313.0,-50061.0,129010.0,216.00,40.35,47.0,H-SC,6.72,166.0,-0.55,0.98,26.09,XR,NTT,BANKS
47,JSWINFRA,-1.00,-12.37,32.87,16.43,63879.0,-27437.0,194337.0,342.00,-24.80,49.0,X-MC,11.45,61.0,-0.43,1.47,4.34,X40N,NTT,REALTY
65,SIEMENS,-2.33,-15.48,48.49,25.51,76272.0,-28800.0,157295.0,4671.50,32.11,46.0,H-LC,3.53,51.0,-0.38,1.19,15.83,AR,ATH,ELECTRICAL

In [24]:
# Top N allocation
df_tmp = df_portfolio_features.sort_values(by = 'CurrAlloc%', ascending=False)
top_n_values = [10, 25, 50]

sum_df = pd.DataFrame({
    'Top_N': top_n_values,
    'Sum_Alloc%': [df_tmp['CurrAlloc%'].head(n).sum() for n in top_n_values]
})

sum_df

   Top_N  Sum_Alloc%
0     10       20.66
1     25       45.53
2     50       77.97

In [25]:
# market-cap-wise allocation
df_tmp = df_portfolio_features[cols]
df_tmp.groupby(df_tmp['Conviction'].str[-2:])['CurrAlloc%'].sum().sort_values(ascending=False)

Conviction
SC    44.48
MC    30.21
LC    25.33
Name: CurrAlloc%, dtype: float64

In [26]:
# criteria-wise allocation
df_portfolio_features.groupby('Criteria')['CurrAlloc%'].sum().sort_values(ascending=False)

Criteria
XY24     27.03
X40      25.37
X40N     15.14
AR        9.18
XR        8.29
XY25      7.39
OX40N     6.82
SR        0.80
Name: CurrAlloc%, dtype: float64

In [27]:
# conviction-wise allocation
df_portfolio_features.groupby('Conviction')['CurrAlloc%'].sum().sort_values(ascending=False)

Conviction
X-LC    23.14
X-MC    22.70
H-SC    21.67
X-SC    12.15
M-SC    10.10
H-MC     5.08
M-MC     2.08
H-LC     1.19
M-LC     1.00
L-SC     0.56
L-MC     0.35
Name: CurrAlloc%, dtype: float64

In [28]:
# sector-wise stats
df_tmp = df_portfolio_features.groupby('Category')[['CurrAlloc%', 'Current', 'Current P/L', 'FTT Amt']].sum().sort_values(by=['Current', 'Current P/L'], ascending=False)
df_tmp['Current P/L%'] = round(df_tmp['Current P/L'] * 100 / df_tmp['Current'], 2)
df_tmp['FTT%'] = round(df_tmp['FTT Amt'] * 100 / df_tmp['Current'], 2)
cols = ['CurrAlloc%', 'Current P/L%', 'FTT%']
df_tmp[cols].sort_values(by=['CurrAlloc%'], ascending=False)

               CurrAlloc%  Current P/L%    FTT%
Category
FMCG                15.02        -25.79   70.45
FINANCE             13.16        -23.43   73.72
IT                  11.64        -46.43  120.95
MISC                 6.96        -45.71  109.01
ELECTRICAL           6.63        -10.48   52.78
PAINTS               5.06        -47.43   73.03
INSURANCE            4.77         -7.41   44.16
BANKS                4.65        -25.31   88.92
PHARMA               4.13         -7.74   41.66
AUTO                 3.67        -34.98   88.54
AC                   2.11        -14.59   45.67
HEALTHCARE           1.93        -40.38   77.01
DURABLES             1.85        -58.15   96.62
TRAVEL               1.83        -85.18  177.90
FOOTWEAR             1.77        -88.51  164.10
BREWERIES            1.69         -5.06   26.88
APPARELS             1.65        -22.84   64.75
REALTY               1.47        -14.12   32.87
CERAMICS             1.40        -65.99  116.41
REFINERIES           1.37        -11.00   39.08
CEMENT               1.25        -62.61  184.26
CABLES               1.20          7.30   92.73
ENGINEERING          1.09        -67.40  143.97
JEWELLERY            1.09       -122.61  199.95
CHEMICALS            1.06        -90.19  245.35
ENTERTAINMENT        0.77        -89.55  202.60
TEXTILES             0.44        -59.34  104.78
HOTELS               0.36       -137.70  221.54

In [29]:
# money to be made criteria-wise
df_portfolio_features.groupby('Criteria')['FTT Amt'].agg(['sum', 'count']).sort_values(by='sum', ascending=False)

                sum  count
Criteria
XY24      4025371.0     21
X40       1817872.0     16
XR        1397323.0     12
AR        1358287.0     10
X40N      1298861.0     10
OX40N      889426.0     10
XY25       463692.0      5
SR         314466.0      2

In [30]:
# money to be made conviction-wise
df_portfolio_features.groupby('Conviction')['FTT Amt'].agg(['sum', 'count']).sort_values(by='sum', ascending=False)

                  sum  count
Conviction
H-SC        3930122.0     24
X-MC        1731809.0     15
X-LC        1716274.0     13
M-SC        1582874.0     14
X-SC        1577481.0     10
H-MC         407806.0      3
L-SC         216401.0      2
M-LC         159537.0      1
M-MC         110640.0      2
H-LC          76272.0      1
L-MC          56082.0      1

In [31]:
# money to be made criteria and conviction-wise
df_portfolio_features.groupby(['Conviction', 'Criteria'])['FTT Amt'].agg(['sum', 'count']).sort_values(by='sum', ascending=False)

                           sum  count
Conviction Criteria
H-SC       XY24      1358716.0      6
           AR         983135.0      5
X-LC       X40        927274.0      7
M-SC       XY24       924047.0      6
H-SC       XR         882451.0      7
X-SC       XY24       859112.0      4
X-MC       X40        678778.0      7
           X40N       529801.0      4
X-SC       X40N       506549.0      4
H-SC       OX40N      391354.0      4
M-SC       OX40N      387501.0      5
X-LC       XY24       373782.0      2
H-SC       SR         314466.0      2
X-MC       XY24       270050.0      2
X-LC       X40N       262511.0      2
X-MC       XY25       253180.0      2
H-MC       XY24       239664.0      1
X-SC       X40        211820.0      2
M-SC       XR         193423.0      2
H-MC       AR         168142.0      2
M-LC       XR         159537.0      1
X-LC       XY25       152707.0      2
L-SC       OX40N      110571.0      1
           XR         105830.0      1
M-SC       AR          77903.0      1
H-LC       AR          76272.0      1
M-MC       XY25        57805.0      1
L-MC       XR          56082.0      1
M-MC       AR          52835.0      1

In [32]:
# notebook execution time

end_time = time.time()
execution_time = round(end_time - start_time, 0)
print(f"Notebook execution time: {execution_time} seconds")

Notebook execution time: 32.0 seconds