<a href="https://colab.research.google.com/github/ankit-rathi/Quantvesting_v2/blob/main/myStocks_Portfolio_Analysis.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
'''
!pip install pandas==2.2.2 -qq
!pip install pyxirr -qq
!pip install ta -qq
!pip install yfinance==0.2.59 -qq
'''

'\n!pip install pandas==2.2.2 -qq\n!pip install pyxirr -qq\n!pip install ta -qq\n!pip install yfinance==0.2.59 -qq\n'

In [2]:
# import libraries

import numpy as np
import pandas as pd
import datetime
import warnings
warnings.filterwarnings('ignore')
import yfinance as yfin
import ta
import matplotlib.pyplot as plt
import requests

In [3]:
# notebook start time
import time
import datetime
import pytz

start_time = time.time()

# function to print date timestamp
def print_date_time():
  tz_NY = pytz.timezone('Asia/Kolkata')
  datetime_NY = datetime.datetime.now(tz_NY)
  print("Run date time (IST):", datetime_NY.strftime("%Y-%m-%d %H:%M:%S"))

In [4]:
# function to get booked and reserved amount
def get_amt():
  # fetch the JSON data from the URL
  url = "https://raw.githubusercontent.com/ankit-rathi/Tradevesting_v1/main/data/myPortfolioAmts.json"
  response = requests.get(url)
  pf_amts = response.json()  # parse the JSON data

  # extract values from the JSON
  py_booked_amt_dm = pf_amts["py_booked_amt_dm"]
  py_booked_amt_sv = pf_amts["py_booked_amt_sv"]
  cy_booked_amt_dm = pf_amts["cy_booked_amt_dm"]
  cy_booked_amt_sv = pf_amts["cy_booked_amt_sv"]
  reserve_amt_dm = pf_amts["reserve_amt_dm"]
  reserve_amt_sv = pf_amts["reserve_amt_sv"]

  # perform calculations
  py_booked_amt = py_booked_amt_dm + py_booked_amt_sv
  cy_booked_amt = cy_booked_amt_dm + cy_booked_amt_sv
  reserve_amt = reserve_amt_dm + reserve_amt_sv
  total_booked_amt = py_booked_amt + cy_booked_amt

  return total_booked_amt, reserve_amt, cy_booked_amt, py_booked_amt

gen_output = 0

In [5]:
# function to format the amount
def format_amt(number):
    abs_number = abs(number)

    if abs_number >= 1_00_00_000:  # Crores
        formatted_amt = f"{number / 1_00_00_000:.2f} C"
    elif abs_number >= 1_00_000:  # Lakhs
        formatted_amt = f"{number / 1_00_000:.2f} L"
    elif abs_number >= 1_000:  # Thousands
        formatted_amt = f"{number / 1_000:.2f} K"
    else:
        formatted_amt = f"{number:.2f}"

    return formatted_amt

# function to set start and end date
def get_start_end_date():
  start_date = (datetime.date.today() + datetime.timedelta(days=-365)).strftime('%Y-%m-%d')
  end_date = (datetime.date.today() + datetime.timedelta(days=1)).strftime('%Y-%m-%d')
  return start_date, end_date

# function to fetch my portfolio csv
def get_mypfs_df():
  mypfs_df = pd.read_csv('https://raw.githubusercontent.com/ankit-rathi/Tradevesting_v1/main/data/myPortfolioStocks.csv')
  return mypfs_df

# function to fetch my prospects csv
def get_mypps_df():
  mypps_df = pd.read_csv('https://raw.githubusercontent.com/ankit-rathi/Tradevesting_v1/main/data/myProspectsScrips.csv')
  return mypps_df

# function to fetch screener data
def get_myscreen_df():
  myscreen_df = pd.read_csv('https://raw.githubusercontent.com/ankit-rathi/Tradevesting_v1/main/data/myScreenerDB.csv')
  return myscreen_df

# function to fetch momentum data
def get_myinvmt_df():
  myinvmt_df = pd.read_csv('https://raw.githubusercontent.com/ankit-rathi/Tradevesting_v1/main/data/myInvestments.csv')
  return myinvmt_df

# function to get the stock ids
def get_stock_ids(df_pf):
  stock_n100 = df_pf['Symbol'].unique()

  exclude = ['CADILAHC','MMTC', 'MASFIN']

  stock_ids = df_pf[~df_pf['Symbol'].isin(exclude) ]['Symbol'].unique()

  #mypf = mypf[mypf.Forecast.notnull()]
  #stock_ids = mypf['Symbol'].unique()

  #stock_ids.sort()
  return stock_ids

# get features from screener data
def get_screener_features():
  myscreen_df = get_myscreen_df()
  cols = ['Symbol', 'EPS', 'MedPE', 'ROCE%', 'ROE%', 'CapType']
  return myscreen_df[cols]

# get relative strength
def get_relative_strength(stock_list):

    # Dictionary to store stock tickers and their corresponding percentage price change
    stock_changes = {}

    # Loop through each stock and fetch its price data
    for stock in stock_list:
        try:
            # Download the stock data for the given date range
            stock_data = yfin.Ticker(stock + '.NS').history(period='1mo', interval='1d')[map(str.title, ['open', 'close', 'low', 'high', 'volume'])]

            # Calculate the percentage change for the stock
            if len(stock_data) > 0:
                start_price = stock_data['Close'].iloc[0]
                end_price = stock_data['Close'].iloc[-1]
                percent_change = round(((end_price - start_price) / start_price) * 100, 2)
                stock_changes[stock] = percent_change
            else:
                stock_changes[stock] = np.nan  # If no data is available, set to NaN

        except Exception as e:
            print(f"Error fetching data for {stock}: {e}")
            stock_changes[stock] = np.nan

    # Create a DataFrame with stock tickers and their percentage changes
    df = pd.DataFrame(list(stock_changes.items()), columns=['Symbol', 'Percent_Change'])

    # Drop any stocks with missing data (NaN values)
    df = df.dropna()

    # Calculate the percentile rank based on percentage change
    df['RSP'] = round(df['Percent_Change'].rank(pct=True) * 100, 2)
    cols = ['Symbol', 'RSP']
    df = df[cols]
    # Sort by percentile rank (optional)
    df = df.sort_values(by='RSP', ascending=False).reset_index(drop=True)

    return df

In [6]:
# function to get stock technicals
def stock_prec_dev(stock_symbol):
    #stock_symbol = 'ULTRACEMCO.NS'
    short_window = 20
    mid_window = 50
    long_window = 200
    moving_avg = 'SMA'

    start = datetime.datetime(*map(int, start_date.split('-')))
    end = datetime.datetime(*map(int, end_date.split('-')))

    stock_df = yfin.Ticker(stock_symbol + '.NS').history(period='max', interval='1d')[map(str.title, ['open', 'close', 'low', 'high', 'volume'])]

    stock_df['Max'] = round(max(stock_df['Close']),2)
    stock_df = stock_df[(stock_df.index <= end_date) & (stock_df.index >= start_date)]
    stock_df['200_SMA'] = round(stock_df['Close'].rolling(window = 200, min_periods = 1).mean(),0)
    stock_df['Dev%_200'] = round((stock_df['Close'] - stock_df['200_SMA'])*100/stock_df['200_SMA'],2)
    stock_df.dropna(axis = 0, inplace = True) # remove any null rows

    stock_df['20_SMA'] = stock_df['Close'].rolling(window=20).mean()
    stock_df['50_SMA'] = stock_df['Close'].rolling(window=50).mean()
    stock_df['Symbol'] = stock_symbol

    stock_df['Close'] = round(stock_df['Close'],2)
    stock_df['Min'] = round(min(stock_df['Close']),2)
    stock_df['RSI_14'] = ta.momentum.RSIIndicator(close=stock_df['Close'], window=14).rsi()
    stock_df['RSI_14'] = round(stock_df['RSI_14'],0)
    stock_df['Prev_Close'] = stock_df['Close'].shift(1)
    stock_df.drop(['Open', 'Low', 'High', 'Volume'], axis=1, inplace=True)
    stock_df = stock_df.tail(1)

    max_SMA = max(stock_df['20_SMA'].item(), stock_df['50_SMA'].item(), stock_df['200_SMA'].item())
    min_SMA = min(stock_df['20_SMA'].item(), stock_df['50_SMA'].item(), stock_df['200_SMA'].item())
    ABS_Spread = max_SMA - min_SMA
    stock_df['Spread%'] = round((ABS_Spread / stock_df['200_SMA'].item()) * 100,2)

    return stock_df

# function to compute stock attributes
def get_common_features(stock_ids, df_mypf):

  df_prec_dev = pd.DataFrame()
  df_tmp = get_screener_features()
  df_rs = get_relative_strength(stock_ids)

  for stock_id in stock_ids:
      tmp = stock_prec_dev(stock_id)
      tmp = tmp.reset_index()
      df_prec_dev = pd.concat([df_prec_dev, tmp], ignore_index = True)
  df_prec_dev = pd.merge(df_prec_dev, df_mypf, on= 'Symbol')
  df_prec_dev = pd.merge(df_prec_dev, df_tmp, on= 'Symbol', how='left')
  df_prec_dev = pd.merge(df_prec_dev, df_rs, on= 'Symbol', how='left')
  #print(df_prec_dev.columns)
  df_prec_dev['Curr_PE'] = round(df_prec_dev['Close']/df_prec_dev['EPS'],1)
  df_prec_dev['Dev%_PE'] = round((df_prec_dev['Curr_PE'] - df_prec_dev['MedPE'])*100/df_prec_dev['MedPE'],2)
  df_prec_dev['Conviction'] = df_prec_dev['Conviction'] + '-' + df_prec_dev['CapType']
  return df_prec_dev

# function to arrange stock features
def arrange_features(df_stocks, common_cols, diff_cols):
  df_stocks_common = df_stocks[common_cols].drop_duplicates()
  df_stocks_diff = df_stocks[diff_cols]
  df_stocks_diff['Investment'] = df_stocks_diff['AvgCost'] * df_stocks_diff['Shares']
  df_stocks_diff = df_stocks_diff.groupby(['Symbol'])[['Shares', 'Investment']].aggregate(['sum']).reset_index()
  df_stocks_diff.columns = ['Symbol', 'Shares', 'Investment']
  df_stocks_diff['AvgCost'] = round(df_stocks_diff['Investment']/df_stocks_diff['Shares'],2)
  df_stocks = pd.merge(df_stocks_diff, df_stocks_common, on='Symbol')
  return df_stocks

# plot fact distribution across dimension
def plot_pie_chart(df, dimension, fact):
  # grouping the data by category and calculating the sum of fact for each type
  grouped_data = df.groupby(dimension)[fact].sum()

  # sorting the grouped data in descending order
  grouped_data = grouped_data.sort_values(ascending=False)

  # creating a pie chart
  grouped_data.plot.pie(autopct='%1.1f%%', startangle=90, figsize=(6, 6))

  # adding a title and displaying the plot
  plt.title(f'{dimension} {fact} Distribution')
  plt.ylabel('')  # To hide the y-label
  plt.show()

In [7]:
# function to get portfolio features

def get_portfolio_features(df_common_features):

  print_date_time()
  print('-------------------')

  #df_common_features["Target"] = df_common_features["Target"].fillna(df_common_features["Max"])
  df_common_features['NTT'] = np.where(df_common_features['Strategy']== 'NTT', df_common_features["Target"], df_common_features['Max'])
  df_common_features['LTT'] = np.where(df_common_features['Strategy']== 'BTT', df_common_features["Target"], df_common_features['Max'])
  df_common_features['BOL'] = df_common_features['Min']

  tmp_df = df_common_features[df_common_features['Symbol'].isin(mypf_df[mypf_df['InPortfolio'] != 'NA'].Symbol.values)]
  print('qualified stocks: '+str(len(tmp_df['Symbol'].unique())))
  tmp_df1 = tmp_df[tmp_df['LatestQtr'] == 1]
  print('with latest results: '+str(len(tmp_df1['Symbol'].unique())))
  tmp_df1 = tmp_df1[tmp_df1['StarStock'] == 1]
  print('still star stocks: '+str(len(tmp_df1['Symbol'].unique())))
  tmp_df['Investment'] = tmp_df['AvgCost'] * tmp_df['Shares']
  tmp_df['Current'] = round(tmp_df['Close'] * tmp_df['Shares'],0)
  tmp_df['Previous'] = tmp_df['Prev_Close'] * tmp_df['Shares']
  tmp_df['EstimatedST'] = tmp_df['NTT'] * tmp_df['Shares']
  tmp_df['EstimatedLT'] = tmp_df['LTT'] * tmp_df['Shares']
  tmp_df['Current P/L'] = round((tmp_df['Current'] - tmp_df['Investment']),0)
  tmp_df['Today P/L%'] = round((tmp_df['Current'] - tmp_df['Previous'])*100/tmp_df['Previous'],2)
  tmp_df['Current P/L%'] = round((tmp_df['Current'] - tmp_df['Investment'])*100/tmp_df['Investment'],2)
  tmp_df['EstimatedST P/L%'] = round((tmp_df['EstimatedST'] - tmp_df['Investment'])*100/tmp_df['Investment'],2)
  tmp_df['EstimatedLT P/L%'] = round((tmp_df['EstimatedLT'] - tmp_df['Investment'])*100/tmp_df['Investment'],2)
  tmp_df['NTT%'] = round((tmp_df['NTT'] - tmp_df['Close'])*100/tmp_df['Close'],2)
  tmp_df['LTT%'] = round((tmp_df['LTT'] - tmp_df['Close'])*100/tmp_df['Close'],2)
  tmp_df['Gained%'] = round((tmp_df['Close'] - tmp_df['BOL'])*100/tmp_df['BOL'],2)
  investment = round(sum(tmp_df['AvgCost']*tmp_df['Shares']),0)
  current = round(sum(tmp_df['Close']*tmp_df['Shares']),0)
  tmp_df['InitAlloc%'] = round(tmp_df['Investment']*100/investment,2)
  tmp_df['CurrAlloc%'] = round(tmp_df['Current']*100/current,2)
  tmp_df['FTT'] = tmp_df['LTT']
  tmp_df.loc[tmp_df['Strategy'] == 'NTT', 'FTT'] = tmp_df['NTT']
  tmp_df['FTT%'] = tmp_df['LTT%']
  tmp_df.loc[tmp_df['Strategy'] == 'NTT', 'FTT%'] = tmp_df['NTT%']
  tmp_df['FTT Amt'] = round(tmp_df['FTT%'] * tmp_df['Current']/100,0)
  tmp_df['OTT%'] = round((tmp_df['FTT'] - tmp_df['AvgCost'])*100/tmp_df['AvgCost'],2)
  tmp_df['RRR Ind'] = round(tmp_df['Current P/L']/tmp_df['FTT Amt'],2)
  tmp_df['Risk Ind'] = round(tmp_df['Current P/L%']*tmp_df['CurrAlloc%'],0)

  return tmp_df

# function to print portfolio features
def print_portfolio_stats(df_portfolio_features, myinvmt_df):
  from pyxirr import xirr

  total_booked_amt, reserve_amt, cy_booked_amt, py_booked_amt = get_amt()

  dates = myinvmt_df['Date'].values
  dates = np.append(dates, datetime.date.today().strftime('%d-%b-%y'))
  investment = myinvmt_df['Investment'].values
  dates= pd.to_datetime(dates)

  current = round(sum(df_portfolio_features['Close']*df_portfolio_features['Shares']),0) + reserve_amt
  investment_xirr = np.append(investment, current)
  cagr = round(xirr(pd.DataFrame({"dates": dates, "amounts": investment_xirr}))*100,2)

  investment = -sum(investment)
  invested = round(sum(df_portfolio_features['AvgCost']*df_portfolio_features['Shares']),0) + reserve_amt
  previous = round(sum(df_portfolio_features['Prev_Close']*df_portfolio_features['Shares']),0) + reserve_amt
  cy_invested = investment + py_booked_amt

  today_pnl_amount = current-previous
  today_pnl_percentage = round((current-previous)*100/previous,2)

  curr_pnl_amount = current-invested
  curr_pnl_percentage = round((curr_pnl_amount)*100/(cy_invested),2)

  cy_pnl_amount = cy_booked_amt + curr_pnl_amount
  cy_pnl_percentage = round((cy_pnl_amount)*100/cy_invested,2)

  overall_pnl_amount = total_booked_amt + curr_pnl_amount
  overall_pnl_percentage = round((overall_pnl_amount)*100/investment,2)

  estimate_st = round(sum(df_portfolio_features['FTT']*df_portfolio_features['Shares']),0)  + reserve_amt
  est_st_pnl_amount = estimate_st-current
  est_st_pnl_percentage = round((est_st_pnl_amount)*100/current,2)

  estimate_lt = round(sum(df_portfolio_features['LTT']*df_portfolio_features['Shares']),0)  + reserve_amt
  est_lt_pnl_amount = estimate_lt-current
  est_lt_pnl_percentage = round((est_lt_pnl_amount)*100/current,2)

  total_profit = round(sum(df_portfolio_features[df_portfolio_features['Current P/L%'] > 0]['Current']) - sum(df_portfolio_features[df_portfolio_features['Current P/L%'] > 0]['Investment']),0)
  total_loss = round(sum(df_portfolio_features[df_portfolio_features['Current P/L%'] < 0]['Current']) - sum(df_portfolio_features[df_portfolio_features['Current P/L%'] < 0]['Investment']),0)

  cy_booked_percentage = round((cy_booked_amt)*100/current,2)
  py_booked_percentage = round((py_booked_amt)*100/investment,2)
  total_booked_percentage = round((total_booked_amt)*100/investment,2)

  print('-------------------')
  print('Initial Investment: ', format_amt(investment))
  print('CY Investment: ', format_amt(cy_invested))
  print('Reserve: ', format_amt(reserve_amt))
  print('Current: ',  format_amt(current))
  print('-------------------')
  print('Today PnL: '+ '{} ({}%)'.format(format_amt(today_pnl_amount), today_pnl_percentage))
  print('Current PnL: '+ '{} ({}%)'.format(format_amt(curr_pnl_amount), curr_pnl_percentage))
  print('CY Booked + Current PnL: '+ '{} ({}%)'.format(format_amt(cy_pnl_amount), cy_pnl_percentage))
  print('-------------------')
  print('Total profit: ', format_amt(total_profit))
  print('Total loss: ', format_amt(total_loss))
  print('-------------------')
  print('Total Booked + Current PnL: '+ '{} ({}%)'.format(format_amt(overall_pnl_amount), overall_pnl_percentage))
  print('Total Booked PnL: '+ '{} ({}%)'.format(format_amt(total_booked_amt), total_booked_percentage))
  print('Curr Year Booked PnL: '+ '{} ({}%)'.format(format_amt(cy_booked_amt), cy_booked_percentage))
  print('Prev Year Booked PnL: '+ '{} ({}%)'.format(format_amt(py_booked_amt), py_booked_percentage))
  print('===================')
  print('Est FTT: ',  format_amt(estimate_st))
  print('Est FTT PnL: '+ '{} ({}%)'.format(format_amt(est_st_pnl_amount), est_st_pnl_percentage))

  print('===================')
  print('Deployed: ', format_amt(investment))

  print('Current: ', format_amt(current))

  print('CAGR/XIRR %: '+'{}%'.format(cagr))

In [8]:
# get start and end date
start_date, end_date = get_start_end_date()

# get portfolio and prospects data
mypfs_df = get_mypfs_df()
mypps_df = get_mypps_df()
myinvmt_df = get_myinvmt_df()

# merge above datasets
mypf_df = pd.merge(mypfs_df, mypps_df, on="Symbol")

# seggregate dm and sv portfolio
dm_pf = mypf_df[mypf_df['InPortfolio'] == 'DM']
sv_pf = mypf_df[mypf_df['InPortfolio'] == 'SV']

# build portfolio stock dataframe
dm_stocks = get_stock_ids(dm_pf)
sv_stocks = get_stock_ids(sv_pf)
df_stocks = pd.concat([dm_pf,sv_pf], ignore_index = True)

# arrange common and diff stock features
common_cols = ['Symbol', 'Target', 'Criteria', 'Strategy', 'CumlRnk', 'LatestQtr', 'StarStock', 'Conviction', 'Category', 'InFolio', 'XIRR', 'MBQ']
diff_cols = ['Symbol', 'AvgCost', 'Shares']
df_stocks = arrange_features(df_stocks, common_cols, diff_cols)

# get common features
stock_ids = df_stocks['Symbol'].values
df_common_features = get_common_features(stock_ids, df_stocks)

df_common_features.reset_index(drop=True, inplace=True)
df_common_features.drop(['Date'], axis=1, inplace=True)
# get and print portfolio features
df_portfolio_features = get_portfolio_features(df_common_features)

print_portfolio_stats(df_portfolio_features, myinvmt_df)

df = df_portfolio_features
#plot_pie_chart(df, 'CapType', 'Current')
list_ox40n = list(df[df['MBQ'].str.contains('OX40N', na=False)]['Symbol'].values)

Run date time (IST): 2026-07-22 10:49:05
-------------------
qualified stocks: 92
with latest results: 31
still star stocks: 20
-------------------
Initial Investment:  1.40 C
CY Investment:  1.82 C
Reserve:  1.49 K
Current:  1.51 C
-------------------
Today PnL: -1.36 L (-0.89%)
Current PnL: -31.96 L (-17.52%)
CY Booked + Current PnL: -29.88 L (-16.38%)
-------------------
Total profit:  4.32 L
Total loss:  -36.28 L
-------------------
Total Booked + Current PnL: 12.99 L (9.31%)
Total Booked PnL: 44.95 L (32.22%)
Curr Year Booked PnL: 2.08 L (1.38%)
Prev Year Booked PnL: 42.87 L (30.73%)
===================
Est FTT:  2.55 C
Est FTT PnL: 1.04 C (68.55%)
===================
Deployed:  1.40 C
Current:  1.51 C
CAGR/XIRR %: 3.62%

In [9]:
# top 5 near their targets
cols = ['Symbol', 'Today P/L%', 'Current P/L%', 'FTT%', 'OTT%', 'FTT Amt', 'Current P/L', 'Current', 'FTT', 'Dev%_PE', 'RSI_14','Conviction', 'Spread%',  'CumlRnk', 'RRR Ind', 'CurrAlloc%', 'Gained%', 'Criteria', 'Strategy', 'Category']
df_tmp = df_portfolio_features[~df_portfolio_features['Symbol'].isin(['ENRIN','BLUSPRING','DIGITIDE'])]
df_tmp = df_tmp.sort_values(by = 'FTT Amt', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
49,JSWINFRA,-2.66,14.18,1.97,16.43,4989.0,31453.0,253227.0,342.00,-2.13,56.0,X-MC,19.13,61.0,6.30,1.67,43.57,X40N,NTT,REALTY
59,PIDILITIND,-0.92,11.74,5.93,18.37,9350.0,16560.0,157670.0,1670.26,-21.72,53.0,X-LC,8.09,5.0,1.77,1.04,23.80,X40,ATH,CHEMICALS
73,SONACOMS,-1.18,25.27,10.72,38.69,13584.0,25559.0,126718.0,801.69,-0.76,78.0,M-MC,25.02,193.0,1.88,0.84,79.78,AR,ATH,AUTO
83,TTKPRESTIG,-1.78,-15.04,17.81,0.09,15249.0,-15155.0,85622.0,770.00,98.72,63.0,M-SC,9.90,250.0,-0.99,0.57,52.46,OX40N,NTT,DURABLES
56,MEDANTA,1.92,16.08,9.51,27.12,19487.0,28390.0,204907.0,1486.00,12.56,63.0,X-SC,11.20,87.0,1.46,1.36,41.19,XY24,NTT,HEALTHCARE

In [10]:
# top 5 today
df_tmp = df_portfolio_features.sort_values(by = 'Today P/L%', ascending=False)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
62,RAJOOENG,5.00,-45.08,154.22,39.61,86810.0,-46210.0,56290.0,143.1,-62.94,67.0,H-SC,20.44,136.0,-0.53,0.37,20.59,AR,ATH,MISC
61,RAJESHEXPO,4.99,-82.27,464.39,0.07,112949.0,-112855.0,24322.0,518.0,791.41,48.0,L-SC,35.73,268.0,-1.00,0.16,20.12,OX40N,NTT,JEWELLERY
85,VAIBHAVGBL,2.40,-18.44,97.12,60.77,144778.0,-33704.0,149071.0,521.0,71.90,65.0,H-SC,7.28,160.0,-0.23,0.99,51.67,XR,NTT,JEWELLERY
56,MEDANTA,1.92,16.08,9.51,27.12,19487.0,28390.0,204907.0,1486.0,12.56,63.0,X-SC,11.20,87.0,1.46,1.36,41.19,XY24,NTT,HEALTHCARE
11,BERGEPAINT,1.88,-7.87,36.01,25.32,85515.0,-20273.0,237476.0,680.0,-12.89,47.0,X-MC,1.78,68.0,-0.24,1.57,23.60,XY24,NTT,PAINTS

In [11]:
# bottom 5 today
df_tmp = df_portfolio_features.sort_values(by = 'Today P/L%', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
9,BANDHANBNK,-15.29,-14.90,126.12,92.42,298962.0,-41513.0,237046.0,400.0,103.30,31.0,H-SC,19.23,174.0,-0.14,1.57,30.58,XY24,NTT,BANKS
42,INDIAMART,-5.11,-21.79,156.90,100.92,151346.0,-26876.0,96460.0,4675.6,-64.65,34.0,H-SC,9.16,140.0,-0.18,0.64,0.00,AR,ATH,MISC
88,VOLTAS,-2.72,3.44,40.37,45.20,80066.0,6588.0,198330.0,1856.0,18.43,50.0,X-MC,5.35,79.0,0.08,1.31,8.70,XY25,NTT,AC
49,JSWINFRA,-2.66,14.18,1.97,16.43,4989.0,31453.0,253227.0,342.0,-2.13,56.0,X-MC,19.13,61.0,6.30,1.67,43.57,X40N,NTT,REALTY
89,WHIRLPOOL,-2.43,-39.51,200.76,81.92,139402.0,-45361.0,69437.0,2270.0,-64.63,31.0,M-SC,15.62,210.0,-0.33,0.46,0.00,XR,NTT,DURABLES

In [12]:
# top 5 to exit based on CumlRnk
df_tmp = df_portfolio_features[~df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])]
df_tmp = df_tmp[(df_tmp['Current P/L%'] > -1) & (df_tmp['Current P/L%'] < 1)].sort_values(by = 'CumlRnk', ascending=False)
df_tmp[cols].head()

Empty DataFrame
Columns: [Symbol, Today P/L%, Current P/L%, FTT%, OTT%, FTT Amt, Current P/L, Current, FTT, Dev%_PE, RSI_14, Conviction, Spread%, CumlRnk, RRR Ind, CurrAlloc%, Gained%, Criteria, Strategy, Category]
Index: []

In [13]:
# OX40N stocks to exit
df_tmp = df_portfolio_features[(df_portfolio_features['Symbol'].isin(list_ox40n))].sort_values(by = 'Current P/L%', ascending=False)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
25,FINCABLES,-0.48,27.99,62.45,107.91,118008.0,41320.0,188964.0,1641.55,15.17,39.0,M-SC,21.91,220.0,0.35,1.25,42.16,OX40N,ATH,CABLES
72,SIS,1.35,1.50,19.47,21.26,21942.0,1665.0,112697.0,528.00,2692.75,62.0,H-SC,25.02,168.0,0.08,0.75,67.56,OX40N,NTT,MISC
83,TTKPRESTIG,-1.78,-15.04,17.81,0.09,15249.0,-15155.0,85622.0,770.00,98.72,63.0,M-SC,9.90,250.0,-0.99,0.57,52.46,OX40N,NTT,DURABLES
16,CERA,-0.10,-19.23,53.39,23.89,75852.0,-33832.0,142071.0,9475.00,-21.96,51.0,H-SC,15.03,153.0,-0.45,0.94,38.11,OX40N,NTT,CERAMICS
43,INDIGOPNTS,-2.24,-25.13,33.60,0.02,43910.0,-43875.0,130684.0,1408.00,99.22,53.0,M-SC,3.62,222.0,-1.00,0.86,48.27,OX40N,NTT,PAINTS

In [14]:
# top 5 to book for rotation
df_tmp = df_portfolio_features[(df_portfolio_features['Current P/L%'] > 20) ].sort_values(by = 'CumlRnk', ascending=False)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
25,FINCABLES,-0.48,27.99,62.45,107.91,118008.0,41320.0,188964.0,1641.55,15.17,39.0,M-SC,21.91,220.0,0.35,1.25,42.16,OX40N,ATH,CABLES
73,SONACOMS,-1.18,25.27,10.72,38.69,13584.0,25559.0,126718.0,801.69,-0.76,78.0,M-MC,25.02,193.0,1.88,0.84,79.78,AR,ATH,AUTO
68,SATIN,0.40,42.47,6.57,51.83,25861.0,117336.0,393620.0,274.00,27.46,56.0,H-SC,44.44,159.0,4.54,2.60,91.75,XY24,NTT,FINANCE
60,QUESS,-0.66,20.17,44.71,73.90,57378.0,21541.0,128334.0,424.00,-35.54,67.0,X-SC,31.72,80.0,0.38,0.85,74.95,XY24,NTT,MISC

In [15]:
# top 5 to monitor for exit
df_tmp = df_portfolio_features[~df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])]
df_tmp = df_tmp[(df_tmp['Current P/L%'] > 0) ].sort_values(by = 'Dev%_PE', ascending=False)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
72,SIS,1.35,1.50,19.47,21.26,21942.0,1665.0,112697.0,528.00,2692.75,62.0,H-SC,25.02,168.0,0.08,0.75,67.56,OX40N,NTT,MISC
75,SURYODAY,1.25,5.57,16.54,23.03,31268.0,9976.0,189047.0,216.00,106.14,60.0,H-SC,21.89,166.0,0.32,1.25,60.47,XR,NTT,BANKS
74,STARHEALTH,-0.94,11.41,32.18,47.26,100790.0,32085.0,313208.0,761.00,75.94,49.0,H-SC,18.98,173.0,0.32,2.07,35.92,XY24,NTT,INSURANCE
68,SATIN,0.40,42.47,6.57,51.83,25861.0,117336.0,393620.0,274.00,27.46,56.0,H-SC,44.44,159.0,4.54,2.60,91.75,XY24,NTT,FINANCE
25,FINCABLES,-0.48,27.99,62.45,107.91,118008.0,41320.0,188964.0,1641.55,15.17,39.0,M-SC,21.91,220.0,0.35,1.25,42.16,OX40N,ATH,CABLES

In [16]:
# top 5 to book for rotation from weak conviction
df_tmp = df_portfolio_features[~df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])]
df_tmp = df_tmp[~df_tmp['Criteria'].isin(['XY25','XY24','X40', 'X40N'])].sort_values(by = 'RRR Ind', ascending=False)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
73,SONACOMS,-1.18,25.27,10.72,38.69,13584.0,25559.0,126718.0,801.69,-0.76,78.0,M-MC,25.02,193.0,1.88,0.84,79.78,AR,ATH,AUTO
91,ZYDUSLIFE,-2.02,18.11,14.84,35.63,36732.0,37946.0,247520.0,1286.17,2.70,50.0,H-MC,17.25,120.0,1.03,1.64,30.14,AR,ATH,PHARMA
25,FINCABLES,-0.48,27.99,62.45,107.91,118008.0,41320.0,188964.0,1641.55,15.17,39.0,M-SC,21.91,220.0,0.35,1.25,42.16,OX40N,ATH,CABLES
75,SURYODAY,1.25,5.57,16.54,23.03,31268.0,9976.0,189047.0,216.00,106.14,60.0,H-SC,21.89,166.0,0.32,1.25,60.47,XR,NTT,BANKS
72,SIS,1.35,1.50,19.47,21.26,21942.0,1665.0,112697.0,528.00,2692.75,62.0,H-SC,25.02,168.0,0.08,0.75,67.56,OX40N,NTT,MISC

In [17]:
# top 5 to accumulate based on lowest RSI_14
df_tmp = df_portfolio_features[df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])].sort_values(by = 'RSI_14', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
39,ICICIGI,-1.53,-15.42,40.56,18.89,68652.0,-30848.0,169261.0,2244.41,-28.90,30.0,X-MC,5.80,66.0,-0.45,1.12,0.00,X40,ATH,INSURANCE
87,VBL,-0.91,-7.23,45.92,35.37,134547.0,-22840.0,293002.0,670.16,-18.17,31.0,X-LC,7.62,13.0,-0.17,1.94,20.42,X40N,ATH,FMCG
58,PGHH,0.32,-34.42,101.30,32.01,141844.0,-73496.0,140024.0,17616.87,-55.58,37.0,X-MC,20.31,57.0,-0.52,0.93,0.36,X40,ATH,FMCG
34,HDFCBANK,-0.98,-9.80,42.31,28.37,89644.0,-23011.0,211874.0,1073.00,-23.49,37.0,X-LC,10.86,26.0,-0.26,1.40,4.77,X40,BTT,BANKS
81,TMPV,-1.24,-24.96,82.01,36.58,218980.0,-88825.0,267016.0,600.00,-84.72,37.0,X-LC,7.75,4.0,-0.41,1.77,12.22,XY24,NTT,AUTO

In [18]:
# top 5 to accumulate based on Spread and CumlRnk
df_tmp = df_portfolio_features[df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])]
df_tmp = df_tmp[(df_tmp['CumlRnk'] < 100)].sort_values(by = 'Spread%', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
11,BERGEPAINT,1.88,-7.87,36.01,25.32,85515.0,-20273.0,237476.0,680.00,-12.89,47.0,X-MC,1.78,68.0,-0.24,1.57,23.60,XY24,NTT,PAINTS
23,DMART,0.60,-3.86,34.80,29.60,83512.0,-9624.0,239976.0,5391.45,-18.89,42.0,X-LC,1.92,14.0,-0.12,1.59,9.69,X40N,ATH,FMCG
19,COLPAL,-1.08,-21.39,77.91,39.86,161305.0,-56325.0,207040.0,3683.41,-4.95,54.0,X-MC,2.01,62.0,-0.35,1.37,17.11,XY25,ATH,FMCG
1,ABBOTINDIA,0.73,-4.46,23.58,18.07,40294.0,-7975.0,170880.0,35195.00,-18.71,74.0,X-MC,3.05,58.0,-0.20,1.13,13.11,X40,ATH,PHARMA
17,CIPLA,-1.81,13.88,17.17,33.43,29948.0,21257.0,174418.0,1648.14,-11.85,45.0,X-LC,3.14,18.0,0.71,1.15,19.07,X40N,ATH,PHARMA

In [19]:
# top 5 to accumulate based on lowest Gained%
df_tmp = df_portfolio_features[df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])].sort_values(by = 'Gained%', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
39,ICICIGI,-1.53,-15.42,40.56,18.89,68652.0,-30848.0,169261.0,2244.41,-28.90,30.0,X-MC,5.80,66.0,-0.45,1.12,0.00,X40,ATH,INSURANCE
58,PGHH,0.32,-34.42,101.30,32.01,141844.0,-73496.0,140024.0,17616.87,-55.58,37.0,X-MC,20.31,57.0,-0.52,0.93,0.36,X40,ATH,FMCG
47,ITC,-0.62,-26.45,61.86,19.06,154779.0,-89958.0,250208.0,452.00,-59.56,40.0,X-LC,12.55,1.0,-0.58,1.65,1.34,X40,NTT,FMCG
35,HDFCLIFE,-1.89,-9.39,46.46,32.71,63060.0,-14070.0,135730.0,811.41,-29.23,41.0,X-LC,15.38,31.0,-0.22,0.90,1.97,X40,ATH,INSURANCE
65,RELIANCE,-1.04,-17.19,51.31,25.30,85392.0,-34540.0,166423.0,1952.00,-19.26,45.0,X-LC,7.44,21.0,-0.40,1.10,2.49,XY25,BTT,REFINERIES

In [20]:
# top 5 to accumulate based on lowest CurrAlloc%
df_tmp = df_portfolio_features[df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])].sort_values(by = 'CurrAlloc%', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
10,BATAINDIA,-0.52,-55.15,201.47,35.20,116260.0,-70964.0,57706.0,2096.00,-24.33,51.0,X-SC,17.76,91.0,-0.61,0.38,14.44,X40,NTT,FOOTWEAR
64,RELAXO,-2.41,-48.06,193.23,52.31,145690.0,-69763.0,75397.0,1176.00,-44.73,54.0,X-SC,12.34,92.0,-0.48,0.50,68.58,X40N,NTT,FOOTWEAR
60,QUESS,-0.66,20.17,44.71,73.90,57378.0,21541.0,128334.0,424.00,-35.54,67.0,X-SC,31.72,80.0,0.38,0.85,74.95,XY24,NTT,MISC
35,HDFCLIFE,-1.89,-9.39,46.46,32.71,63060.0,-14070.0,135730.0,811.41,-29.23,41.0,X-LC,15.38,31.0,-0.22,0.90,1.97,X40,ATH,INSURANCE
28,GODREJCP,-0.85,-6.46,40.55,31.47,56369.0,-9602.0,139012.0,1469.04,-1.64,47.0,X-LC,6.33,32.0,-0.17,0.92,6.66,X40N,ATH,FMCG

In [21]:
# top 5 to accumulate based on CumlRnk
df_tmp = df_portfolio_features.sort_values(by = 'CumlRnk', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
47,ITC,-0.62,-26.45,61.86,19.06,154779.0,-89958.0,250208.0,452.00,-59.56,40.0,X-LC,12.55,1.0,-0.58,1.65,1.34,X40,NTT,FMCG
79,TCS,-0.78,-35.30,91.97,24.20,275650.0,-163556.0,299717.0,4230.71,-45.26,55.0,X-LC,19.85,2.0,-0.59,1.98,11.77,X40,ATH,IT
45,INFY,-1.41,-27.95,86.32,34.24,194599.0,-87449.0,225439.0,1972.00,-43.40,45.0,X-LC,20.85,3.0,-0.45,1.49,7.42,X40,NTT,IT
81,TMPV,-1.24,-24.96,82.01,36.58,218980.0,-88825.0,267016.0,600.00,-84.72,37.0,X-LC,7.75,4.0,-0.41,1.77,12.22,XY24,NTT,AUTO
59,PIDILITIND,-0.92,11.74,5.93,18.37,9350.0,16560.0,157670.0,1670.26,-21.72,53.0,X-LC,8.09,5.0,1.77,1.04,23.80,X40,ATH,CHEMICALS

In [22]:
# top 5 for average up
df_tmp = df_portfolio_features[(df_portfolio_features['Dev%_200'] > 5)].sort_values(by = 'CurrAlloc%', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
44,INDUSINDBK,-0.52,-21.90,70.15,32.89,42300.0,-16906.0,60300.0,1800.00,-383.61,71.0,L-MC,12.81,258.0,-0.40,0.40,48.66,XR,NTT,BANKS
64,RELAXO,-2.41,-48.06,193.23,52.31,145690.0,-69763.0,75397.0,1176.00,-44.73,54.0,X-SC,12.34,92.0,-0.48,0.50,68.58,X40N,NTT,FOOTWEAR
3,ALKYLAMINE,-1.16,-22.67,149.00,92.54,116326.0,-22892.0,78071.0,4520.85,-17.24,49.0,H-SC,11.92,142.0,-0.20,0.52,48.25,SR,ATH,CHEMICALS
83,TTKPRESTIG,-1.78,-15.04,17.81,0.09,15249.0,-15155.0,85622.0,770.00,98.72,63.0,M-SC,9.90,250.0,-0.99,0.57,52.46,OX40N,NTT,DURABLES
72,SIS,1.35,1.50,19.47,21.26,21942.0,1665.0,112697.0,528.00,2692.75,62.0,H-SC,25.02,168.0,0.08,0.75,67.56,OX40N,NTT,MISC

In [23]:
# top 5 RSP
df_tmp = df_portfolio_features.sort_values(by = 'RSP', ascending=False)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
60,QUESS,-0.66,20.17,44.71,73.90,57378.0,21541.0,128334.0,424.00,-35.54,67.0,X-SC,31.72,80.0,0.38,0.85,74.95,XY24,NTT,MISC
73,SONACOMS,-1.18,25.27,10.72,38.69,13584.0,25559.0,126718.0,801.69,-0.76,78.0,M-MC,25.02,193.0,1.88,0.84,79.78,AR,ATH,AUTO
83,TTKPRESTIG,-1.78,-15.04,17.81,0.09,15249.0,-15155.0,85622.0,770.00,98.72,63.0,M-SC,9.90,250.0,-0.99,0.57,52.46,OX40N,NTT,DURABLES
44,INDUSINDBK,-0.52,-21.90,70.15,32.89,42300.0,-16906.0,60300.0,1800.00,-383.61,71.0,L-MC,12.81,258.0,-0.40,0.40,48.66,XR,NTT,BANKS
22,DIXON,-0.73,2.10,35.08,37.92,93413.0,5487.0,266285.0,18931.72,-56.62,63.0,X-MC,7.22,54.0,0.06,1.76,44.89,X40N,ATH,IT

In [24]:
# Top N allocation
df_tmp = df_portfolio_features.sort_values(by = 'CurrAlloc%', ascending=False)
top_n_values = [10, 25, 50]

sum_df = pd.DataFrame({
    'Top_N': top_n_values,
    'Sum_Alloc%': [df_tmp['CurrAlloc%'].head(n).sum() for n in top_n_values]
})

sum_df

   Top_N  Sum_Alloc%
0     10       19.15
1     25       42.35
2     50       72.58

In [25]:
# market-cap-wise allocation
df_tmp = df_portfolio_features[cols]
df_tmp.groupby(df_tmp['Conviction'].str[-2:])['CurrAlloc%'].sum().sort_values(ascending=False)

Conviction
SC    43.56
LC    30.10
MC    26.35
Name: CurrAlloc%, dtype: float64

In [26]:
# criteria-wise allocation
df_portfolio_features.groupby('Criteria')['CurrAlloc%'].sum().sort_values(ascending=False)

Criteria
XY24     27.47
X40      24.69
X40N     17.45
XR        8.93
OX40N     7.08
AR        6.99
XY25      6.50
SR        0.90
Name: CurrAlloc%, dtype: float64

In [27]:
# conviction-wise allocation
df_portfolio_features.groupby('Conviction')['CurrAlloc%'].sum().sort_values(ascending=False)

Conviction
X-LC    28.09
H-SC    22.83
X-MC    21.09
X-SC    10.23
M-SC     9.95
H-MC     2.71
M-MC     2.15
H-LC     1.21
M-LC     0.80
L-SC     0.55
L-MC     0.40
Name: CurrAlloc%, dtype: float64

In [28]:
# sector-wise stats
df_tmp = df_portfolio_features.groupby('Category')[['CurrAlloc%', 'Current', 'Current P/L', 'FTT Amt']].sum().sort_values(by=['Current', 'Current P/L'], ascending=False)
df_tmp['Current P/L%'] = round(df_tmp['Current P/L'] * 100 / df_tmp['Current'], 2)
df_tmp['FTT%'] = round(df_tmp['FTT Amt'] * 100 / df_tmp['Current'], 2)
cols = ['CurrAlloc%', 'Current P/L%', 'FTT%']
df_tmp[cols].sort_values(by=['CurrAlloc%'], ascending=False)

               CurrAlloc%  Current P/L%    FTT%
Category
FMCG                14.27        -22.73   65.79
FINANCE             11.28         -8.22   55.11
IT                  10.12        -47.13  119.95
MISC                 7.32        -21.17   73.16
AUTO                 6.69         -8.25   48.62
BANKS                5.55         -8.20   58.20
PAINTS               5.44        -19.66   40.07
PHARMA               5.25          6.62   22.28
INSURANCE            5.16         -6.24   42.08
ELECTRICAL           4.16        -12.45   52.01
CHEMICALS            2.15        -24.74   98.73
HEALTHCARE           2.11        -12.42   41.76
APPARELS             1.84          3.67   28.69
AC                   1.80        -17.20   48.98
FOOTWEAR             1.71        -70.87  139.38
REALTY               1.67         12.42    1.97
DURABLES             1.63        -57.27   95.53
BREWERIES            1.57          1.57   18.87
TRAVEL               1.51        -95.65  193.61
CERAMICS             1.43        -42.36   85.61
CABLES               1.25         21.87   62.45
ENGINEERING          1.25        -28.55   87.35
JEWELLERY            1.15        -84.52  148.64
REFINERIES           1.10        -20.75   51.31
CEMENT               1.08        -63.82  186.38
ENTERTAINMENT        0.71        -78.84  185.51
TEXTILES             0.42        -44.88   86.19
HOTELS               0.39        -90.47  157.65

In [29]:
# money to be made criteria-wise
df_portfolio_features.groupby('Criteria')['FTT Amt'].agg(['sum', 'count']).sort_values(by='sum', ascending=False)

                sum  count
Criteria
XY24      3444899.0     21
X40       1935819.0     19
XR        1327578.0     13
AR        1117535.0      9
X40N      1081417.0     13
OX40N      721654.0     10
XY25       453631.0      5
SR         282738.0      2

In [30]:
# money to be made conviction-wise
df_portfolio_features.groupby('Conviction')['FTT Amt'].agg(['sum', 'count']).sort_values(by='sum', ascending=False)

                  sum  count
Conviction
H-SC        3322327.0     24
X-LC        2023869.0     21
X-MC        1529493.0     15
M-SC        1411840.0     14
X-SC        1257921.0      9
H-MC         288141.0      2
L-SC         206934.0      2
M-LC         170716.0      1
M-MC          61538.0      2
H-LC          50192.0      1
L-MC          42300.0      1

In [31]:
# money to be made criteria and conviction-wise
df_portfolio_features.groupby(['Conviction', 'Criteria'])['FTT Amt'].agg(['sum', 'count']).sort_values(by='sum', ascending=False)

                           sum  count
Conviction Criteria
X-LC       X40       1051447.0     10
H-SC       XY24      1015744.0      6
           AR         940067.0      5
M-SC       XY24       829707.0      6
H-SC       XR         785961.0      7
X-SC       XY24       743358.0      4
X-MC       X40        673455.0      7
X-LC       X40N       399735.0      6
X-MC       X40N       378036.0      4
X-LC       XY24       368050.0      2
M-SC       OX40N      310888.0      5
X-SC       X40N       303646.0      3
H-SC       OX40N      297817.0      4
           SR         282738.0      2
H-MC       XY24       251409.0      1
X-MC       XY25       241371.0      2
           XY24       236631.0      2
X-SC       X40        210917.0      2
M-SC       XR         194285.0      2
M-LC       XR         170716.0      1
X-LC       XY25       164306.0      2
L-SC       OX40N      112949.0      1
           XR          93985.0      1
M-SC       AR          76960.0      1
H-LC       AR          50192.0      1
M-MC       XY25        47954.0      1
L-MC       XR          42300.0      1
X-LC       XR          40331.0      1
H-MC       AR          36732.0      1
M-MC       AR          13584.0      1

In [32]:
# notebook execution time

end_time = time.time()
execution_time = round(end_time - start_time, 0)
print(f"Notebook execution time: {execution_time} seconds")

Notebook execution time: 27.0 seconds