<a href="https://colab.research.google.com/github/ankit-rathi/Quantvesting_v2/blob/main/myStocks_Portfolio_Analysis.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
'''
!pip install pandas==2.2.2 -qq
!pip install pyxirr -qq
!pip install ta -qq
!pip install yfinance==0.2.59 -qq
'''

'\n!pip install pandas==2.2.2 -qq\n!pip install pyxirr -qq\n!pip install ta -qq\n!pip install yfinance==0.2.59 -qq\n'

In [2]:
# import libraries

import numpy as np
import pandas as pd
import datetime
import warnings
warnings.filterwarnings('ignore')
import yfinance as yfin
import ta
import matplotlib.pyplot as plt
import requests

In [3]:
# notebook start time
import time
import datetime
import pytz

start_time = time.time()

# function to print date timestamp
def print_date_time():
  tz_NY = pytz.timezone('Asia/Kolkata')
  datetime_NY = datetime.datetime.now(tz_NY)
  print("Run date time (IST):", datetime_NY.strftime("%Y-%m-%d %H:%M:%S"))

In [4]:
# function to get booked and reserved amount
def get_amt():
  # fetch the JSON data from the URL
  url = "https://raw.githubusercontent.com/ankit-rathi/Tradevesting_v1/main/data/myPortfolioAmts.json"
  response = requests.get(url)
  pf_amts = response.json()  # parse the JSON data

  # extract values from the JSON
  py_booked_amt_dm = pf_amts["py_booked_amt_dm"]
  py_booked_amt_sv = pf_amts["py_booked_amt_sv"]
  cy_booked_amt_dm = pf_amts["cy_booked_amt_dm"]
  cy_booked_amt_sv = pf_amts["cy_booked_amt_sv"]
  reserve_amt_dm = pf_amts["reserve_amt_dm"]
  reserve_amt_sv = pf_amts["reserve_amt_sv"]

  # perform calculations
  py_booked_amt = py_booked_amt_dm + py_booked_amt_sv
  cy_booked_amt = cy_booked_amt_dm + cy_booked_amt_sv
  reserve_amt = reserve_amt_dm + reserve_amt_sv
  total_booked_amt = py_booked_amt + cy_booked_amt

  return total_booked_amt, reserve_amt, cy_booked_amt, py_booked_amt

gen_output = 0

In [5]:
# function to format the amount
def format_amt(number):
    abs_number = abs(number)

    if abs_number >= 1_00_00_000:  # Crores
        formatted_amt = f"{number / 1_00_00_000:.2f} C"
    elif abs_number >= 1_00_000:  # Lakhs
        formatted_amt = f"{number / 1_00_000:.2f} L"
    elif abs_number >= 1_000:  # Thousands
        formatted_amt = f"{number / 1_000:.2f} K"
    else:
        formatted_amt = f"{number:.2f}"

    return formatted_amt

# function to set start and end date
def get_start_end_date():
  start_date = (datetime.date.today() + datetime.timedelta(days=-365)).strftime('%Y-%m-%d')
  end_date = (datetime.date.today() + datetime.timedelta(days=1)).strftime('%Y-%m-%d')
  return start_date, end_date

# function to fetch my portfolio csv
def get_mypfs_df():
  mypfs_df = pd.read_csv('https://raw.githubusercontent.com/ankit-rathi/Tradevesting_v1/main/data/myPortfolioStocks.csv')
  return mypfs_df

# function to fetch my prospects csv
def get_mypps_df():
  mypps_df = pd.read_csv('https://raw.githubusercontent.com/ankit-rathi/Tradevesting_v1/main/data/myProspectsScrips.csv')
  return mypps_df

# function to fetch screener data
def get_myscreen_df():
  myscreen_df = pd.read_csv('https://raw.githubusercontent.com/ankit-rathi/Tradevesting_v1/main/data/myScreenerDB.csv')
  return myscreen_df

# function to fetch momentum data
def get_myinvmt_df():
  myinvmt_df = pd.read_csv('https://raw.githubusercontent.com/ankit-rathi/Tradevesting_v1/main/data/myInvestments.csv')
  return myinvmt_df

# function to get the stock ids
def get_stock_ids(df_pf):
  stock_n100 = df_pf['Symbol'].unique()

  exclude = ['CADILAHC','MMTC', 'MASFIN']

  stock_ids = df_pf[~df_pf['Symbol'].isin(exclude) ]['Symbol'].unique()

  #mypf = mypf[mypf.Forecast.notnull()]
  #stock_ids = mypf['Symbol'].unique()

  #stock_ids.sort()
  return stock_ids

# get features from screener data
def get_screener_features():
  myscreen_df = get_myscreen_df()
  cols = ['Symbol', 'EPS', 'MedPE', 'ROCE%', 'ROE%', 'CapType']
  return myscreen_df[cols]

# get relative strength
def get_relative_strength(stock_list):

    # Dictionary to store stock tickers and their corresponding percentage price change
    stock_changes = {}

    # Loop through each stock and fetch its price data
    for stock in stock_list:
        try:
            # Download the stock data for the given date range
            stock_data = yfin.Ticker(stock + '.NS').history(period='1mo', interval='1d')[map(str.title, ['open', 'close', 'low', 'high', 'volume'])]

            # Calculate the percentage change for the stock
            if len(stock_data) > 0:
                start_price = stock_data['Close'].iloc[0]
                end_price = stock_data['Close'].iloc[-1]
                percent_change = round(((end_price - start_price) / start_price) * 100, 2)
                stock_changes[stock] = percent_change
            else:
                stock_changes[stock] = np.nan  # If no data is available, set to NaN

        except Exception as e:
            print(f"Error fetching data for {stock}: {e}")
            stock_changes[stock] = np.nan

    # Create a DataFrame with stock tickers and their percentage changes
    df = pd.DataFrame(list(stock_changes.items()), columns=['Symbol', 'Percent_Change'])

    # Drop any stocks with missing data (NaN values)
    df = df.dropna()

    # Calculate the percentile rank based on percentage change
    df['RSP'] = round(df['Percent_Change'].rank(pct=True) * 100, 2)
    cols = ['Symbol', 'RSP']
    df = df[cols]
    # Sort by percentile rank (optional)
    df = df.sort_values(by='RSP', ascending=False).reset_index(drop=True)

    return df

In [6]:
# function to get stock technicals
def stock_prec_dev(stock_symbol):
    #stock_symbol = 'ULTRACEMCO.NS'
    short_window = 20
    mid_window = 50
    long_window = 200
    moving_avg = 'SMA'

    start = datetime.datetime(*map(int, start_date.split('-')))
    end = datetime.datetime(*map(int, end_date.split('-')))

    stock_df = yfin.Ticker(stock_symbol + '.NS').history(period='max', interval='1d')[map(str.title, ['open', 'close', 'low', 'high', 'volume'])]

    stock_df['Max'] = round(max(stock_df['Close']),2)
    stock_df = stock_df[(stock_df.index <= end_date) & (stock_df.index >= start_date)]
    stock_df['200_SMA'] = round(stock_df['Close'].rolling(window = 200, min_periods = 1).mean(),0)
    stock_df['Dev%_200'] = round((stock_df['Close'] - stock_df['200_SMA'])*100/stock_df['200_SMA'],2)
    stock_df.dropna(axis = 0, inplace = True) # remove any null rows

    stock_df['20_SMA'] = stock_df['Close'].rolling(window=20).mean()
    stock_df['50_SMA'] = stock_df['Close'].rolling(window=50).mean()
    stock_df['Symbol'] = stock_symbol

    stock_df['Close'] = round(stock_df['Close'],2)
    stock_df['Min'] = round(min(stock_df['Close']),2)
    stock_df['RSI_14'] = ta.momentum.RSIIndicator(close=stock_df['Close'], window=14).rsi()
    stock_df['RSI_14'] = round(stock_df['RSI_14'],0)
    stock_df['Prev_Close'] = stock_df['Close'].shift(1)
    stock_df.drop(['Open', 'Low', 'High', 'Volume'], axis=1, inplace=True)
    stock_df = stock_df.tail(1)

    max_SMA = max(stock_df['20_SMA'].item(), stock_df['50_SMA'].item(), stock_df['200_SMA'].item())
    min_SMA = min(stock_df['20_SMA'].item(), stock_df['50_SMA'].item(), stock_df['200_SMA'].item())
    ABS_Spread = max_SMA - min_SMA
    stock_df['Spread%'] = round((ABS_Spread / stock_df['200_SMA'].item()) * 100,2)

    return stock_df

# function to compute stock attributes
def get_common_features(stock_ids, df_mypf):

  df_prec_dev = pd.DataFrame()
  df_tmp = get_screener_features()
  df_rs = get_relative_strength(stock_ids)

  for stock_id in stock_ids:
      tmp = stock_prec_dev(stock_id)
      tmp = tmp.reset_index()
      df_prec_dev = pd.concat([df_prec_dev, tmp], ignore_index = True)
  df_prec_dev = pd.merge(df_prec_dev, df_mypf, on= 'Symbol')
  df_prec_dev = pd.merge(df_prec_dev, df_tmp, on= 'Symbol', how='left')
  df_prec_dev = pd.merge(df_prec_dev, df_rs, on= 'Symbol', how='left')
  #print(df_prec_dev.columns)
  df_prec_dev['Curr_PE'] = round(df_prec_dev['Close']/df_prec_dev['EPS'],1)
  df_prec_dev['Dev%_PE'] = round((df_prec_dev['Curr_PE'] - df_prec_dev['MedPE'])*100/df_prec_dev['MedPE'],2)
  df_prec_dev['Conviction'] = df_prec_dev['Conviction'] + '-' + df_prec_dev['CapType']
  return df_prec_dev

# function to arrange stock features
def arrange_features(df_stocks, common_cols, diff_cols):
  df_stocks_common = df_stocks[common_cols].drop_duplicates()
  df_stocks_diff = df_stocks[diff_cols]
  df_stocks_diff['Investment'] = df_stocks_diff['AvgCost'] * df_stocks_diff['Shares']
  df_stocks_diff = df_stocks_diff.groupby(['Symbol'])[['Shares', 'Investment']].aggregate(['sum']).reset_index()
  df_stocks_diff.columns = ['Symbol', 'Shares', 'Investment']
  df_stocks_diff['AvgCost'] = round(df_stocks_diff['Investment']/df_stocks_diff['Shares'],2)
  df_stocks = pd.merge(df_stocks_diff, df_stocks_common, on='Symbol')
  return df_stocks

# plot fact distribution across dimension
def plot_pie_chart(df, dimension, fact):
  # grouping the data by category and calculating the sum of fact for each type
  grouped_data = df.groupby(dimension)[fact].sum()

  # sorting the grouped data in descending order
  grouped_data = grouped_data.sort_values(ascending=False)

  # creating a pie chart
  grouped_data.plot.pie(autopct='%1.1f%%', startangle=90, figsize=(6, 6))

  # adding a title and displaying the plot
  plt.title(f'{dimension} {fact} Distribution')
  plt.ylabel('')  # To hide the y-label
  plt.show()

In [7]:
# function to get portfolio features

def get_portfolio_features(df_common_features):

  print_date_time()
  print('-------------------')

  #df_common_features["Target"] = df_common_features["Target"].fillna(df_common_features["Max"])
  df_common_features['NTT'] = np.where(df_common_features['Strategy']== 'NTT', df_common_features["Target"], df_common_features['Max'])
  df_common_features['LTT'] = np.where(df_common_features['Strategy']== 'BTT', df_common_features["Target"], df_common_features['Max'])
  df_common_features['BOL'] = df_common_features['Min']

  tmp_df = df_common_features[df_common_features['Symbol'].isin(mypf_df[mypf_df['InPortfolio'] != 'NA'].Symbol.values)]
  print('qualified stocks: '+str(len(tmp_df['Symbol'].unique())))
  tmp_df1 = tmp_df[tmp_df['LatestQtr'] == 1]
  print('with latest results: '+str(len(tmp_df1['Symbol'].unique())))
  tmp_df1 = tmp_df1[tmp_df1['StarStock'] == 1]
  print('still star stocks: '+str(len(tmp_df1['Symbol'].unique())))
  tmp_df['Investment'] = tmp_df['AvgCost'] * tmp_df['Shares']
  tmp_df['Current'] = round(tmp_df['Close'] * tmp_df['Shares'],0)
  tmp_df['Previous'] = tmp_df['Prev_Close'] * tmp_df['Shares']
  tmp_df['EstimatedST'] = tmp_df['NTT'] * tmp_df['Shares']
  tmp_df['EstimatedLT'] = tmp_df['LTT'] * tmp_df['Shares']
  tmp_df['Current P/L'] = round((tmp_df['Current'] - tmp_df['Investment']),0)
  tmp_df['Today P/L%'] = round((tmp_df['Current'] - tmp_df['Previous'])*100/tmp_df['Previous'],2)
  tmp_df['Current P/L%'] = round((tmp_df['Current'] - tmp_df['Investment'])*100/tmp_df['Investment'],2)
  tmp_df['EstimatedST P/L%'] = round((tmp_df['EstimatedST'] - tmp_df['Investment'])*100/tmp_df['Investment'],2)
  tmp_df['EstimatedLT P/L%'] = round((tmp_df['EstimatedLT'] - tmp_df['Investment'])*100/tmp_df['Investment'],2)
  tmp_df['NTT%'] = round((tmp_df['NTT'] - tmp_df['Close'])*100/tmp_df['Close'],2)
  tmp_df['LTT%'] = round((tmp_df['LTT'] - tmp_df['Close'])*100/tmp_df['Close'],2)
  tmp_df['Gained%'] = round((tmp_df['Close'] - tmp_df['BOL'])*100/tmp_df['BOL'],2)
  investment = round(sum(tmp_df['AvgCost']*tmp_df['Shares']),0)
  current = round(sum(tmp_df['Close']*tmp_df['Shares']),0)
  tmp_df['InitAlloc%'] = round(tmp_df['Investment']*100/investment,2)
  tmp_df['CurrAlloc%'] = round(tmp_df['Current']*100/current,2)
  tmp_df['FTT'] = tmp_df['LTT']
  tmp_df.loc[tmp_df['Strategy'] == 'NTT', 'FTT'] = tmp_df['NTT']
  tmp_df['FTT%'] = tmp_df['LTT%']
  tmp_df.loc[tmp_df['Strategy'] == 'NTT', 'FTT%'] = tmp_df['NTT%']
  tmp_df['FTT Amt'] = round(tmp_df['FTT%'] * tmp_df['Current']/100,0)
  tmp_df['OTT%'] = round((tmp_df['FTT'] - tmp_df['AvgCost'])*100/tmp_df['AvgCost'],2)
  tmp_df['RRR Ind'] = round(tmp_df['Current P/L']/tmp_df['FTT Amt'],2)
  tmp_df['Risk Ind'] = round(tmp_df['Current P/L%']*tmp_df['CurrAlloc%'],0)

  return tmp_df

# function to print portfolio features
def print_portfolio_stats(df_portfolio_features, myinvmt_df):
  from pyxirr import xirr

  total_booked_amt, reserve_amt, cy_booked_amt, py_booked_amt = get_amt()

  dates = myinvmt_df['Date'].values
  dates = np.append(dates, datetime.date.today().strftime('%d-%b-%y'))
  investment = myinvmt_df['Investment'].values
  dates= pd.to_datetime(dates)

  current = round(sum(df_portfolio_features['Close']*df_portfolio_features['Shares']),0) + reserve_amt
  investment_xirr = np.append(investment, current)
  cagr = round(xirr(pd.DataFrame({"dates": dates, "amounts": investment_xirr}))*100,2)

  investment = -sum(investment)
  invested = round(sum(df_portfolio_features['AvgCost']*df_portfolio_features['Shares']),0) + reserve_amt
  previous = round(sum(df_portfolio_features['Prev_Close']*df_portfolio_features['Shares']),0) + reserve_amt
  cy_invested = investment + py_booked_amt

  today_pnl_amount = current-previous
  today_pnl_percentage = round((current-previous)*100/previous,2)

  curr_pnl_amount = current-invested
  curr_pnl_percentage = round((curr_pnl_amount)*100/(cy_invested),2)

  cy_pnl_amount = cy_booked_amt + curr_pnl_amount
  cy_pnl_percentage = round((cy_pnl_amount)*100/cy_invested,2)

  overall_pnl_amount = total_booked_amt + curr_pnl_amount
  overall_pnl_percentage = round((overall_pnl_amount)*100/investment,2)

  estimate_st = round(sum(df_portfolio_features['FTT']*df_portfolio_features['Shares']),0)  + reserve_amt
  est_st_pnl_amount = estimate_st-current
  est_st_pnl_percentage = round((est_st_pnl_amount)*100/current,2)

  estimate_lt = round(sum(df_portfolio_features['LTT']*df_portfolio_features['Shares']),0)  + reserve_amt
  est_lt_pnl_amount = estimate_lt-current
  est_lt_pnl_percentage = round((est_lt_pnl_amount)*100/current,2)

  total_profit = round(sum(df_portfolio_features[df_portfolio_features['Current P/L%'] > 0]['Current']) - sum(df_portfolio_features[df_portfolio_features['Current P/L%'] > 0]['Investment']),0)
  total_loss = round(sum(df_portfolio_features[df_portfolio_features['Current P/L%'] < 0]['Current']) - sum(df_portfolio_features[df_portfolio_features['Current P/L%'] < 0]['Investment']),0)

  cy_booked_percentage = round((cy_booked_amt)*100/current,2)
  py_booked_percentage = round((py_booked_amt)*100/investment,2)
  total_booked_percentage = round((total_booked_amt)*100/investment,2)

  print('-------------------')
  print('Initial Investment: ', format_amt(investment))
  print('CY Investment: ', format_amt(cy_invested))
  print('Reserve: ', format_amt(reserve_amt))
  print('Current: ',  format_amt(current))
  print('-------------------')
  print('Today PnL: '+ '{} ({}%)'.format(format_amt(today_pnl_amount), today_pnl_percentage))
  print('Current PnL: '+ '{} ({}%)'.format(format_amt(curr_pnl_amount), curr_pnl_percentage))
  print('CY Booked + Current PnL: '+ '{} ({}%)'.format(format_amt(cy_pnl_amount), cy_pnl_percentage))
  print('-------------------')
  print('Total profit: ', format_amt(total_profit))
  print('Total loss: ', format_amt(total_loss))
  print('-------------------')
  print('Total Booked + Current PnL: '+ '{} ({}%)'.format(format_amt(overall_pnl_amount), overall_pnl_percentage))
  print('Total Booked PnL: '+ '{} ({}%)'.format(format_amt(total_booked_amt), total_booked_percentage))
  print('Curr Year Booked PnL: '+ '{} ({}%)'.format(format_amt(cy_booked_amt), cy_booked_percentage))
  print('Prev Year Booked PnL: '+ '{} ({}%)'.format(format_amt(py_booked_amt), py_booked_percentage))
  print('===================')
  print('Est FTT: ',  format_amt(estimate_st))
  print('Est FTT PnL: '+ '{} ({}%)'.format(format_amt(est_st_pnl_amount), est_st_pnl_percentage))

  print('===================')
  print('Deployed: ', format_amt(investment))

  print('Current: ', format_amt(current))

  print('CAGR/XIRR %: '+'{}%'.format(cagr))

In [8]:
# get start and end date
start_date, end_date = get_start_end_date()

# get portfolio and prospects data
mypfs_df = get_mypfs_df()
mypps_df = get_mypps_df()
myinvmt_df = get_myinvmt_df()

# merge above datasets
mypf_df = pd.merge(mypfs_df, mypps_df, on="Symbol")

# seggregate dm and sv portfolio
dm_pf = mypf_df[mypf_df['InPortfolio'] == 'DM']
sv_pf = mypf_df[mypf_df['InPortfolio'] == 'SV']

# build portfolio stock dataframe
dm_stocks = get_stock_ids(dm_pf)
sv_stocks = get_stock_ids(sv_pf)
df_stocks = pd.concat([dm_pf,sv_pf], ignore_index = True)

# arrange common and diff stock features
common_cols = ['Symbol', 'Target', 'Criteria', 'Strategy', 'CumlRnk', 'LatestQtr', 'StarStock', 'Conviction', 'Category', 'InFolio', 'XIRR', 'MBQ']
diff_cols = ['Symbol', 'AvgCost', 'Shares']
df_stocks = arrange_features(df_stocks, common_cols, diff_cols)

# get common features
stock_ids = df_stocks['Symbol'].values
df_common_features = get_common_features(stock_ids, df_stocks)

df_common_features.reset_index(drop=True, inplace=True)
df_common_features.drop(['Date'], axis=1, inplace=True)
# get and print portfolio features
df_portfolio_features = get_portfolio_features(df_common_features)

print_portfolio_stats(df_portfolio_features, myinvmt_df)

df = df_portfolio_features
#plot_pie_chart(df, 'CapType', 'Current')
list_ox40n = list(df[df['MBQ'].str.contains('OX40N', na=False)]['Symbol'].values)

Run date time (IST): 2026-08-11 12:34:23
-------------------
qualified stocks: 88
with latest results: 30
still star stocks: 19
-------------------
Initial Investment:  1.46 C
CY Investment:  1.89 C
Reserve:  2.24 L
Current:  1.61 C
-------------------
Today PnL: -14.76 K (-0.09%)
Current PnL: -30.98 L (-16.4%)
CY Booked + Current PnL: -26.76 L (-14.16%)
-------------------
Total profit:  3.87 L
Total loss:  -34.85 L
-------------------
Total Booked + Current PnL: 16.11 L (11.03%)
Total Booked PnL: 47.09 L (32.24%)
Curr Year Booked PnL: 4.22 L (2.62%)
Prev Year Booked PnL: 42.87 L (29.35%)
===================
Est FTT:  2.67 C
Est FTT PnL: 1.06 C (65.52%)
===================
Deployed:  1.46 C
Current:  1.61 C
CAGR/XIRR %: 4.51%

In [9]:
# top 5 near their targets
cols = ['Symbol', 'Today P/L%', 'Current P/L%', 'FTT%', 'OTT%', 'FTT Amt', 'Current P/L', 'Current', 'FTT', 'Dev%_PE', 'RSI_14','Conviction', 'Spread%',  'CumlRnk', 'RRR Ind', 'CurrAlloc%', 'Gained%', 'Criteria', 'Strategy', 'Category']
df_tmp = df_portfolio_features[~df_portfolio_features['Symbol'].isin(['ENRIN','BLUSPRING','DIGITIDE'])]
df_tmp = df_tmp.sort_values(by = 'FTT Amt', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
55,MEDANTA,-2.04,23.71,2.76,27.12,6027.0,41844.0,218361.0,1486.00,19.85,62.0,X-SC,16.06,87.0,6.94,1.37,50.46,XY24,NTT,HEALTHCARE
52,M&M,-0.36,10.66,7.38,18.82,19655.0,25646.0,266327.0,3762.88,-3.65,69.0,X-LC,5.01,25.0,1.30,1.68,20.81,X40N,ATH,AUTO
80,UNITDSPR,0.50,11.66,8.16,20.77,21334.0,27296.0,261440.0,1644.00,-0.92,70.0,X-MC,7.55,64.0,1.28,1.65,25.67,X40N,NTT,BREWERIES
79,TTKPRESTIG,-1.61,-22.55,29.23,0.09,22816.0,-22721.0,78056.0,770.00,81.22,40.0,M-SC,12.82,250.0,-1.00,0.49,40.49,OX40N,NTT,DURABLES
69,SIS,0.59,0.48,20.69,21.26,23082.0,530.0,111562.0,528.00,2664.25,57.0,H-SC,23.05,168.0,0.02,0.70,65.88,OX40N,NTT,MISC

In [10]:
# top 5 today
df_tmp = df_portfolio_features.sort_values(by = 'Today P/L%', ascending=False)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
58,QUESS,6.88,36.35,27.54,73.90,40102.0,38820.0,145613.0,424.00,-26.72,68.0,X-SC,39.71,80.0,0.97,0.92,100.42,XY24,NTT,MISC
82,VALIANTORG,6.76,-35.99,172.08,74.15,180202.0,-58885.0,104720.0,838.00,-288.40,69.0,H-SC,4.40,145.0,-0.33,0.66,55.84,XR,NTT,CHEMICALS
25,FINCABLES,4.26,35.31,53.65,107.91,107183.0,52137.0,199781.0,1641.55,21.77,58.0,M-SC,17.30,220.0,0.49,1.26,50.30,OX40N,ATH,CABLES
87,ZYDUSLIFE,3.45,22.07,11.01,35.51,28167.0,46256.0,255830.0,1285.01,6.31,62.0,H-MC,15.57,120.0,1.64,1.61,34.63,AR,ATH,PHARMA
13,BSOFT,2.57,-41.01,151.87,48.59,126017.0,-57676.0,82977.0,819.60,-24.24,64.0,H-SC,16.78,172.0,-0.46,0.52,21.31,XR,ATH,IT

In [11]:
# bottom 5 today
df_tmp = df_portfolio_features.sort_values(by = 'Today P/L%', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
28,GODREJCP,-2.99,-7.34,44.22,33.64,102246.0,-18315.0,231222.0,1469.04,-4.16,38.0,X-LC,5.16,32.0,-0.18,1.46,3.95,X40N,ATH,FMCG
29,GREENPANEL,-2.61,-50.66,190.13,43.14,171733.0,-92754.0,90324.0,537.00,102.20,39.0,M-SC,10.32,225.0,-0.54,0.57,8.78,XY24,NTT,MISC
59,RAJESHEXPO,-2.37,-84.24,534.80,0.07,115645.0,-115553.0,21624.0,518.00,692.93,35.0,L-SC,36.35,268.0,-1.00,0.14,6.79,OX40N,NTT,JEWELLERY
81,VAIBHAVGBL,-2.33,-26.78,119.55,60.77,160002.0,-48938.0,133837.0,521.00,54.27,39.0,H-SC,11.20,160.0,-0.31,0.84,36.17,XR,NTT,JEWELLERY
55,MEDANTA,-2.04,23.71,2.76,27.12,6027.0,41844.0,218361.0,1486.00,19.85,62.0,X-SC,16.06,87.0,6.94,1.37,50.46,XY24,NTT,HEALTHCARE

In [12]:
# top 5 to exit based on CumlRnk
df_tmp = df_portfolio_features[~df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])]
df_tmp = df_tmp[(df_tmp['Current P/L%'] > -1) & (df_tmp['Current P/L%'] < 1)].sort_values(by = 'CumlRnk', ascending=False)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
69,SIS,0.59,0.48,20.69,21.26,23082.0,530.0,111562.0,528.0,2664.25,57.0,H-SC,23.05,168.0,0.02,0.7,65.88,OX40N,NTT,MISC

In [13]:
# OX40N stocks to exit
df_tmp = df_portfolio_features[(df_portfolio_features['Symbol'].isin(list_ox40n))].sort_values(by = 'Current P/L%', ascending=False)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
25,FINCABLES,4.26,35.31,53.65,107.91,107183.0,52137.0,199781.0,1641.55,21.77,58.0,M-SC,17.30,220.0,0.49,1.26,50.30,OX40N,ATH,CABLES
69,SIS,0.59,0.48,20.69,21.26,23082.0,530.0,111562.0,528.00,2664.25,57.0,H-SC,23.05,168.0,0.02,0.70,65.88,OX40N,NTT,MISC
43,INDIGOPNTS,1.75,-19.01,23.50,0.02,33222.0,-33187.0,141372.0,1408.00,115.40,67.0,M-SC,5.06,222.0,-1.00,0.89,60.40,OX40N,NTT,PAINTS
16,CERA,-1.22,-21.70,58.23,23.89,80197.0,-38179.0,137724.0,9475.00,-24.34,42.0,H-SC,12.66,153.0,-0.48,0.87,33.88,OX40N,NTT,CERAMICS
79,TTKPRESTIG,-1.61,-22.55,29.23,0.09,22816.0,-22721.0,78056.0,770.00,81.22,40.0,M-SC,12.82,250.0,-1.00,0.49,40.49,OX40N,NTT,DURABLES

In [14]:
# top 5 to book for rotation
df_tmp = df_portfolio_features[(df_portfolio_features['Current P/L%'] > 20) ].sort_values(by = 'CumlRnk', ascending=False)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
25,FINCABLES,4.26,35.31,53.65,107.91,107183.0,52137.0,199781.0,1641.55,21.77,58.0,M-SC,17.30,220.0,0.49,1.26,50.30,OX40N,ATH,CABLES
87,ZYDUSLIFE,3.45,22.07,11.01,35.51,28167.0,46256.0,255830.0,1285.01,6.31,62.0,H-MC,15.57,120.0,1.64,1.61,34.63,AR,ATH,PHARMA
55,MEDANTA,-2.04,23.71,2.76,27.12,6027.0,41844.0,218361.0,1486.00,19.85,62.0,X-SC,16.06,87.0,6.94,1.37,50.46,XY24,NTT,HEALTHCARE
58,QUESS,6.88,36.35,27.54,73.90,40102.0,38820.0,145613.0,424.00,-26.72,68.0,X-SC,39.71,80.0,0.97,0.92,100.42,XY24,NTT,MISC

In [15]:
# top 5 to monitor for exit
df_tmp = df_portfolio_features[~df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])]
df_tmp = df_tmp[(df_tmp['Current P/L%'] > 0) ].sort_values(by = 'Dev%_PE', ascending=False)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
69,SIS,0.59,0.48,20.69,21.26,23082.0,530.0,111562.0,528.00,2664.25,57.0,H-SC,23.05,168.0,0.02,0.70,65.88,OX40N,NTT,MISC
70,STARHEALTH,0.30,11.60,31.96,47.26,100267.0,32602.0,313725.0,761.00,76.17,47.0,H-SC,16.92,173.0,0.33,1.97,35.65,XY24,NTT,INSURANCE
25,FINCABLES,4.26,35.31,53.65,107.91,107183.0,52137.0,199781.0,1641.55,21.77,58.0,M-SC,17.30,220.0,0.49,1.26,50.30,OX40N,ATH,CABLES
87,ZYDUSLIFE,3.45,22.07,11.01,35.51,28167.0,46256.0,255830.0,1285.01,6.31,62.0,H-MC,15.57,120.0,1.64,1.61,34.63,AR,ATH,PHARMA

In [16]:
# top 5 to book for rotation from weak conviction
df_tmp = df_portfolio_features[~df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])]
df_tmp = df_tmp[~df_tmp['Criteria'].isin(['XY25','XY24','X40', 'X40N'])].sort_values(by = 'RRR Ind', ascending=False)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
87,ZYDUSLIFE,3.45,22.07,11.01,35.51,28167.0,46256.0,255830.0,1285.01,6.31,62.0,H-MC,15.57,120.0,1.64,1.61,34.63,AR,ATH,PHARMA
25,FINCABLES,4.26,35.31,53.65,107.91,107183.0,52137.0,199781.0,1641.55,21.77,58.0,M-SC,17.30,220.0,0.49,1.26,50.30,OX40N,ATH,CABLES
69,SIS,0.59,0.48,20.69,21.26,23082.0,530.0,111562.0,528.00,2664.25,57.0,H-SC,23.05,168.0,0.02,0.70,65.88,OX40N,NTT,MISC
3,ALKYLAMINE,2.51,-17.31,132.85,92.54,110908.0,-17479.0,83484.0,4520.85,-11.41,61.0,H-SC,13.64,142.0,-0.16,0.53,58.53,SR,ATH,CHEMICALS
42,INDIAMART,1.42,-23.51,162.67,100.92,153463.0,-28996.0,94340.0,4675.60,-65.43,40.0,H-SC,12.23,140.0,-0.19,0.59,2.12,AR,ATH,MISC

In [17]:
# top 5 to accumulate based on lowest RSI_14
df_tmp = df_portfolio_features[df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])].sort_values(by = 'RSI_14', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
34,HDFCBANK,-0.37,-11.05,47.33,31.05,123404.0,-32389.0,260731.0,1073.00,-25.96,34.0,X-LC,11.35,26.0,-0.26,1.64,1.20,X40,BTT,BANKS
57,PGHH,-0.38,-36.57,108.13,32.01,146443.0,-78088.0,135432.0,17616.87,-57.06,34.0,X-MC,19.23,57.0,-0.53,0.85,0.00,X40,ATH,FMCG
35,HDFCLIFE,-1.19,-8.50,52.08,39.15,119485.0,-21311.0,229426.0,811.41,-31.91,36.0,X-LC,16.13,31.0,-0.18,1.44,0.00,X40,ATH,INSURANCE
28,GODREJCP,-2.99,-7.34,44.22,33.64,102246.0,-18315.0,231222.0,1469.04,-4.16,38.0,X-LC,5.16,32.0,-0.18,1.46,3.95,X40N,ATH,FMCG
56,PAGEIND,-0.21,0.63,32.76,33.59,88472.0,1681.0,270060.0,51217.29,-27.90,39.0,X-MC,8.81,55.0,0.02,1.70,28.25,X40,ATH,APPARELS

In [18]:
# top 5 to accumulate based on Spread and CumlRnk
df_tmp = df_portfolio_features[df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])]
df_tmp = df_tmp[(df_tmp['CumlRnk'] < 100)].sort_values(by = 'Spread%', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
19,COLPAL,-1.21,-23.85,83.67,39.86,167800.0,-62815.0,200550.0,3683.41,-7.87,42.0,X-MC,1.64,62.0,-0.37,1.26,13.44,XY25,ATH,FMCG
11,BERGEPAINT,1.30,-0.95,26.52,25.32,67703.0,-2460.0,255289.0,680.00,-6.27,62.0,X-MC,2.13,68.0,-0.04,1.61,33.87,XY24,NTT,PAINTS
8,BAJAJHLDNG,2.36,3.58,23.81,28.24,63136.0,9162.0,265167.0,14274.15,-4.76,66.0,X-LC,2.74,28.0,0.15,1.67,33.46,X40,ATH,FINANCE
23,DMART,0.17,-1.02,32.77,31.42,101135.0,-3169.0,308621.0,5391.45,-17.73,54.0,X-LC,3.06,14.0,-0.03,1.94,11.37,X40N,ATH,FMCG
26,GILLETTE,-0.51,-10.05,44.22,29.72,100987.0,-25521.0,228375.0,10978.86,-30.84,42.0,X-SC,3.31,83.0,-0.25,1.44,4.95,X40,ATH,FMCG

In [19]:
# top 5 to accumulate based on lowest Gained%
df_tmp = df_portfolio_features[df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])].sort_values(by = 'Gained%', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
35,HDFCLIFE,-1.19,-8.50,52.08,39.15,119485.0,-21311.0,229426.0,811.41,-31.91,36.0,X-LC,16.13,31.0,-0.18,1.44,0.00,X40,ATH,INSURANCE
57,PGHH,-0.38,-36.57,108.13,32.01,146443.0,-78088.0,135432.0,17616.87,-57.06,34.0,X-MC,19.23,57.0,-0.53,0.85,0.00,X40,ATH,FMCG
34,HDFCBANK,-0.37,-11.05,47.33,31.05,123404.0,-32389.0,260731.0,1073.00,-25.96,34.0,X-LC,11.35,26.0,-0.26,1.64,1.20,X40,BTT,BANKS
20,DABUR,-0.46,-19.39,78.27,43.70,156513.0,-48102.0,199966.0,735.00,-26.86,41.0,X-MC,9.24,70.0,-0.31,1.26,1.75,XY24,BTT,FMCG
47,ITC,-0.48,-22.40,60.68,24.70,187079.0,-88973.0,308305.0,452.00,-59.16,44.0,X-LC,10.89,1.0,-0.48,1.94,2.09,X40,NTT,FMCG

In [20]:
# top 5 to accumulate based on lowest CurrAlloc%
df_tmp = df_portfolio_features[df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])].sort_values(by = 'CurrAlloc%', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
10,BATAINDIA,-1.72,-54.81,199.19,35.20,115821.0,-70524.0,58146.0,2096.00,-23.75,51.0,X-SC,13.64,91.0,-0.61,0.37,16.82,X40,NTT,FOOTWEAR
62,RELAXO,0.37,-44.96,176.71,52.31,141191.0,-65260.0,79900.0,1176.00,-41.44,61.0,X-SC,11.77,92.0,-0.46,0.50,78.65,X40N,NTT,FOOTWEAR
57,PGHH,-0.38,-36.57,108.13,32.01,146443.0,-78088.0,135432.0,17616.87,-57.06,34.0,X-MC,19.23,57.0,-0.53,0.85,0.00,X40,ATH,FMCG
58,QUESS,6.88,36.35,27.54,73.90,40102.0,38820.0,145613.0,424.00,-26.72,68.0,X-SC,39.71,80.0,0.97,0.92,100.42,XY24,NTT,MISC
40,ICICIPRULI,-0.69,-17.66,58.21,30.28,94427.0,-34787.0,162218.0,787.27,-39.83,45.0,X-MC,13.51,78.0,-0.37,1.02,8.08,X40,ATH,INSURANCE

In [21]:
# top 5 to accumulate based on CumlRnk
df_tmp = df_portfolio_features.sort_values(by = 'CumlRnk', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
47,ITC,-0.48,-22.40,60.68,24.70,187079.0,-88973.0,308305.0,452.00,-59.16,44.0,X-LC,10.89,1.0,-0.48,1.94,2.09,X40,NTT,FMCG
75,TCS,0.59,-28.37,73.38,24.20,243514.0,-131419.0,331854.0,4230.71,-39.36,62.0,X-LC,15.43,2.0,-0.54,2.09,23.75,X40,ATH,IT
45,INFY,0.63,-15.26,65.66,40.38,209473.0,-57443.0,319027.0,1972.00,-36.14,65.0,X-LC,16.24,3.0,-0.27,2.01,20.82,X40,NTT,IT
77,TMPV,-0.39,-17.74,73.54,42.75,251722.0,-73815.0,342292.0,600.00,-83.62,54.0,X-LC,5.14,4.0,-0.29,2.15,17.70,XY24,NTT,AUTO
33,HCLTECH,0.76,-8.53,35.53,23.97,100575.0,-26414.0,283072.0,1853.42,-6.95,70.0,X-LC,13.06,8.0,-0.26,1.78,33.58,X40,ATH,IT

In [22]:
# top 5 for average up
df_tmp = df_portfolio_features[(df_portfolio_features['Dev%_200'] > 5)].sort_values(by = 'CurrAlloc%', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
44,INDUSINDBK,-1.17,-25.43,78.22,32.89,45031.0,-19636.0,57570.0,1800.00,-371.01,52.0,L-MC,13.94,258.0,-0.44,0.36,41.93,XR,NTT,BANKS
62,RELAXO,0.37,-44.96,176.71,52.31,141191.0,-65260.0,79900.0,1176.00,-41.44,61.0,X-SC,11.77,92.0,-0.46,0.50,78.65,X40N,NTT,FOOTWEAR
3,ALKYLAMINE,2.51,-17.31,132.85,92.54,110908.0,-17479.0,83484.0,4520.85,-11.41,61.0,H-SC,13.64,142.0,-0.16,0.53,58.53,SR,ATH,CHEMICALS
12,BOSCH-HCIL,-0.44,-26.61,36.24,-0.01,33993.0,-34005.0,93800.0,2282.00,19095.65,83.0,M-SC,3.51,231.0,-1.00,0.59,59.66,OX40N,BTT,AC
82,VALIANTORG,6.76,-35.99,172.08,74.15,180202.0,-58885.0,104720.0,838.00,-288.40,69.0,H-SC,4.40,145.0,-0.33,0.66,55.84,XR,NTT,CHEMICALS

In [23]:
# top 5 RSP
df_tmp = df_portfolio_features.sort_values(by = 'RSP', ascending=False)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
12,BOSCH-HCIL,-0.44,-26.61,36.24,-0.01,33993.0,-34005.0,93800.0,2282.00,19095.65,83.0,M-SC,3.51,231.0,-1.00,0.59,59.66,OX40N,BTT,AC
33,HCLTECH,0.76,-8.53,35.53,23.97,100575.0,-26414.0,283072.0,1853.42,-6.95,70.0,X-LC,13.06,8.0,-0.26,1.78,33.58,X40,ATH,IT
58,QUESS,6.88,36.35,27.54,73.90,40102.0,38820.0,145613.0,424.00,-26.72,68.0,X-SC,39.71,80.0,0.97,0.92,100.42,XY24,NTT,MISC
68,SIEMENS,-0.49,4.65,19.35,24.90,37684.0,8655.0,194750.0,4648.66,63.58,64.0,H-LC,11.41,51.0,0.23,1.23,37.41,AR,ATH,ELECTRICAL
38,HYUNDAI,-0.04,14.94,25.23,43.94,72883.0,37541.0,288873.0,2782.73,-4.68,75.0,X-LC,4.23,29.0,0.52,1.82,32.63,X40N,ATH,AUTO

In [24]:
# Top N allocation
df_tmp = df_portfolio_features.sort_values(by = 'CurrAlloc%', ascending=False)
top_n_values = [10, 25, 50]

sum_df = pd.DataFrame({
    'Top_N': top_n_values,
    'Sum_Alloc%': [df_tmp['CurrAlloc%'].head(n).sum() for n in top_n_values]
})

sum_df

   Top_N  Sum_Alloc%
0     10       19.78
1     25       44.87
2     50       76.77

In [25]:
# market-cap-wise allocation
df_tmp = df_portfolio_features[cols]
df_tmp.groupby(df_tmp['Conviction'].str[-2:])['CurrAlloc%'].sum().sort_values(ascending=False)

Conviction
SC    39.28
LC    37.80
MC    22.88
Name: CurrAlloc%, dtype: float64

In [26]:
# criteria-wise allocation
df_portfolio_features.groupby('Criteria')['CurrAlloc%'].sum().sort_values(ascending=False)

Criteria
X40      26.37
XY24     24.88
X40N     18.55
XR        9.10
XY25      7.17
OX40N     6.92
AR        6.10
SR        0.87
Name: CurrAlloc%, dtype: float64

In [27]:
# conviction-wise allocation
df_portfolio_features.groupby('Conviction')['CurrAlloc%'].sum().sort_values(ascending=False)

Conviction
X-LC    35.77
H-SC    19.31
X-MC    18.66
X-SC     9.94
M-SC     9.52
H-MC     2.67
H-LC     1.23
M-MC     1.19
M-LC     0.80
L-SC     0.51
L-MC     0.36
Name: CurrAlloc%, dtype: float64

In [28]:
# sector-wise stats
df_tmp = df_portfolio_features.groupby('Category')[['CurrAlloc%', 'Current', 'Current P/L', 'FTT Amt']].sum().sort_values(by=['Current', 'Current P/L'], ascending=False)
df_tmp['Current P/L%'] = round(df_tmp['Current P/L'] * 100 / df_tmp['Current'], 2)
df_tmp['FTT%'] = round(df_tmp['FTT Amt'] * 100 / df_tmp['Current'], 2)
cols = ['CurrAlloc%', 'Current P/L%', 'FTT%']
df_tmp[cols].sort_values(by=['CurrAlloc%'], ascending=False)

               CurrAlloc%  Current P/L%    FTT%
Category
FMCG                15.45        -21.39   65.11
IT                  11.28        -32.91   98.88
FINANCE              9.25        -16.28   65.15
AUTO                 8.32         -2.35   39.01
MISC                 6.92        -21.76   74.00
BANKS                6.06        -10.78   58.56
PHARMA               5.65          7.84   18.30
INSURANCE            5.52         -5.68   43.05
PAINTS               5.47        -13.35   32.68
ELECTRICAL           4.10         -8.60   46.62
HEALTHCARE           2.08         -8.15   36.38
AC                   1.79        -12.02   42.39
APPARELS             1.70          0.62   32.76
REFINERIES           1.70        -10.59   47.73
FOOTWEAR             1.65        -68.31  135.80
BREWERIES            1.65         10.44    8.16
DURABLES             1.48        -64.02  103.93
TRAVEL               1.46        -92.22  188.46
CERAMICS             1.34        -44.16   87.95
CABLES               1.26         26.10   53.65
ENGINEERING          1.20        -26.60   84.51
CHEMICALS            1.19        -40.58  154.68
CEMENT               1.02        -65.94  190.09
JEWELLERY            0.98       -105.81  177.31
ENTERTAINMENT        0.68        -78.89  185.58
TEXTILES             0.39        -50.42   93.31
HOTELS               0.37        -93.71  162.04

In [29]:
# money to be made criteria-wise
df_portfolio_features.groupby('Criteria')['FTT Amt'].agg(['sum', 'count']).sort_values(by='sum', ascending=False)

                sum  count
Criteria
XY24      3447486.0     20
X40       2032684.0     18
XR        1349002.0     13
X40N      1135365.0     12
AR        1061859.0      8
OX40N      692312.0     10
XY25       559243.0      5
SR         279394.0      2

In [30]:
# money to be made conviction-wise
df_portfolio_features.groupby('Conviction')['FTT Amt'].agg(['sum', 'count']).sort_values(by='sum', ascending=False)

                  sum  count
Conviction
H-SC        3279857.0     23
X-LC        2373519.0     20
X-MC        1487778.0     14
M-SC        1405772.0     14
X-SC        1223413.0      9
H-MC         272955.0      2
L-SC         210630.0      2
M-LC         163995.0      1
M-MC          56711.0      1
L-MC          45031.0      1
H-LC          37684.0      1

In [31]:
# money to be made criteria and conviction-wise
df_portfolio_features.groupby(['Conviction', 'Criteria'])['FTT Amt'].agg(['sum', 'count']).sort_values(by='sum', ascending=False)

                           sum  count
Conviction Criteria
X-LC       X40       1156349.0      9
H-SC       XY24       989937.0      5
           AR         919320.0      5
M-SC       XY24       852429.0      6
H-SC       XR         798740.0      7
X-SC       XY24       711134.0      4
X-MC       X40        659527.0      7
X-LC       X40N       490601.0      6
           XY24       424982.0      2
X-MC       X40N       349293.0      3
X-SC       X40N       295471.0      3
H-SC       OX40N      292466.0      4
M-SC       OX40N      284201.0      5
H-SC       SR         279394.0      2
X-MC       XY25       254742.0      2
X-LC       XY25       247790.0      2
H-MC       XY24       244788.0      1
X-MC       XY24       224216.0      2
X-SC       X40        216808.0      2
M-SC       XR         192454.0      2
M-LC       XR         163995.0      1
L-SC       OX40N      115645.0      1
           XR          94985.0      1
M-SC       AR          76688.0      1
M-MC       XY25        56711.0      1
X-LC       XR          53797.0      1
L-MC       XR          45031.0      1
H-LC       AR          37684.0      1
H-MC       AR          28167.0      1

In [32]:
# notebook execution time

end_time = time.time()
execution_time = round(end_time - start_time, 0)
print(f"Notebook execution time: {execution_time} seconds")

Notebook execution time: 29.0 seconds