<a href="https://colab.research.google.com/github/ankit-rathi/Quantvesting_v2/blob/main/myStocks_Portfolio_Analysis.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
'''
!pip install pandas==2.2.2 -qq
!pip install pyxirr -qq
!pip install ta -qq
!pip install yfinance==0.2.59 -qq
'''

'\n!pip install pandas==2.2.2 -qq\n!pip install pyxirr -qq\n!pip install ta -qq\n!pip install yfinance==0.2.59 -qq\n'

In [2]:
# import libraries

import numpy as np
import pandas as pd
import datetime
import warnings
warnings.filterwarnings('ignore')
import yfinance as yfin
import ta
import matplotlib.pyplot as plt
import requests

In [3]:
# notebook start time
import time
import datetime
import pytz

start_time = time.time()

# function to print date timestamp
def print_date_time():
  tz_NY = pytz.timezone('Asia/Kolkata')
  datetime_NY = datetime.datetime.now(tz_NY)
  print("Run date time (IST):", datetime_NY.strftime("%Y-%m-%d %H:%M:%S"))

In [4]:
# function to get booked and reserved amount
def get_amt():
  # fetch the JSON data from the URL
  url = "https://raw.githubusercontent.com/ankit-rathi/Tradevesting_v1/main/data/myPortfolioAmts.json"
  response = requests.get(url)
  pf_amts = response.json()  # parse the JSON data

  # extract values from the JSON
  py_booked_amt_dm = pf_amts["py_booked_amt_dm"]
  py_booked_amt_sv = pf_amts["py_booked_amt_sv"]
  cy_booked_amt_dm = pf_amts["cy_booked_amt_dm"]
  cy_booked_amt_sv = pf_amts["cy_booked_amt_sv"]
  reserve_amt_dm = pf_amts["reserve_amt_dm"]
  reserve_amt_sv = pf_amts["reserve_amt_sv"]

  # perform calculations
  py_booked_amt = py_booked_amt_dm + py_booked_amt_sv
  cy_booked_amt = cy_booked_amt_dm + cy_booked_amt_sv
  reserve_amt = reserve_amt_dm + reserve_amt_sv
  total_booked_amt = py_booked_amt + cy_booked_amt

  return total_booked_amt, reserve_amt, cy_booked_amt, py_booked_amt

gen_output = 0

In [5]:
# function to format the amount
def format_amt(number):
    abs_number = abs(number)

    if abs_number >= 1_00_00_000:  # Crores
        formatted_amt = f"{number / 1_00_00_000:.2f} C"
    elif abs_number >= 1_00_000:  # Lakhs
        formatted_amt = f"{number / 1_00_000:.2f} L"
    elif abs_number >= 1_000:  # Thousands
        formatted_amt = f"{number / 1_000:.2f} K"
    else:
        formatted_amt = f"{number:.2f}"

    return formatted_amt

# function to set start and end date
def get_start_end_date():
  start_date = (datetime.date.today() + datetime.timedelta(days=-365)).strftime('%Y-%m-%d')
  end_date = (datetime.date.today() + datetime.timedelta(days=1)).strftime('%Y-%m-%d')
  return start_date, end_date

# function to fetch my portfolio csv
def get_mypfs_df():
  mypfs_df = pd.read_csv('https://raw.githubusercontent.com/ankit-rathi/Tradevesting_v1/main/data/myPortfolioStocks.csv')
  return mypfs_df

# function to fetch my prospects csv
def get_mypps_df():
  mypps_df = pd.read_csv('https://raw.githubusercontent.com/ankit-rathi/Tradevesting_v1/main/data/myProspectsScrips.csv')
  return mypps_df

# function to fetch screener data
def get_myscreen_df():
  myscreen_df = pd.read_csv('https://raw.githubusercontent.com/ankit-rathi/Tradevesting_v1/main/data/myScreenerDB.csv')
  return myscreen_df

# function to fetch momentum data
def get_myinvmt_df():
  myinvmt_df = pd.read_csv('https://raw.githubusercontent.com/ankit-rathi/Tradevesting_v1/main/data/myInvestments.csv')
  return myinvmt_df

# function to get the stock ids
def get_stock_ids(df_pf):
  stock_n100 = df_pf['Symbol'].unique()

  exclude = ['CADILAHC','MMTC', 'MASFIN']

  stock_ids = df_pf[~df_pf['Symbol'].isin(exclude) ]['Symbol'].unique()

  #mypf = mypf[mypf.Forecast.notnull()]
  #stock_ids = mypf['Symbol'].unique()

  #stock_ids.sort()
  return stock_ids

# get features from screener data
def get_screener_features():
  myscreen_df = get_myscreen_df()
  cols = ['Symbol', 'EPS', 'MedPE', 'ROCE%', 'ROE%', 'CapType']
  return myscreen_df[cols]

# get relative strength
def get_relative_strength(stock_list):

    # Dictionary to store stock tickers and their corresponding percentage price change
    stock_changes = {}

    # Loop through each stock and fetch its price data
    for stock in stock_list:
        try:
            # Download the stock data for the given date range
            stock_data = yfin.Ticker(stock + '.NS').history(period='1mo', interval='1d')[map(str.title, ['open', 'close', 'low', 'high', 'volume'])]

            # Calculate the percentage change for the stock
            if len(stock_data) > 0:
                start_price = stock_data['Close'].iloc[0]
                end_price = stock_data['Close'].iloc[-1]
                percent_change = round(((end_price - start_price) / start_price) * 100, 2)
                stock_changes[stock] = percent_change
            else:
                stock_changes[stock] = np.nan  # If no data is available, set to NaN

        except Exception as e:
            print(f"Error fetching data for {stock}: {e}")
            stock_changes[stock] = np.nan

    # Create a DataFrame with stock tickers and their percentage changes
    df = pd.DataFrame(list(stock_changes.items()), columns=['Symbol', 'Percent_Change'])

    # Drop any stocks with missing data (NaN values)
    df = df.dropna()

    # Calculate the percentile rank based on percentage change
    df['RSP'] = round(df['Percent_Change'].rank(pct=True) * 100, 2)
    cols = ['Symbol', 'RSP']
    df = df[cols]
    # Sort by percentile rank (optional)
    df = df.sort_values(by='RSP', ascending=False).reset_index(drop=True)

    return df

In [6]:
# function to get stock technicals
def stock_prec_dev(stock_symbol):
    #stock_symbol = 'ULTRACEMCO.NS'
    short_window = 20
    mid_window = 50
    long_window = 200
    moving_avg = 'SMA'

    start = datetime.datetime(*map(int, start_date.split('-')))
    end = datetime.datetime(*map(int, end_date.split('-')))

    stock_df = yfin.Ticker(stock_symbol + '.NS').history(period='max', interval='1d')[map(str.title, ['open', 'close', 'low', 'high', 'volume'])]

    stock_df['Max'] = round(max(stock_df['Close']),2)
    stock_df = stock_df[(stock_df.index <= end_date) & (stock_df.index >= start_date)]
    stock_df['200_SMA'] = round(stock_df['Close'].rolling(window = 200, min_periods = 1).mean(),0)
    stock_df['Dev%_200'] = round((stock_df['Close'] - stock_df['200_SMA'])*100/stock_df['200_SMA'],2)
    stock_df.dropna(axis = 0, inplace = True) # remove any null rows

    stock_df['20_SMA'] = stock_df['Close'].rolling(window=20).mean()
    stock_df['50_SMA'] = stock_df['Close'].rolling(window=50).mean()
    stock_df['Symbol'] = stock_symbol

    stock_df['Close'] = round(stock_df['Close'],2)
    stock_df['Min'] = round(min(stock_df['Close']),2)
    stock_df['RSI_14'] = ta.momentum.RSIIndicator(close=stock_df['Close'], window=14).rsi()
    stock_df['RSI_14'] = round(stock_df['RSI_14'],0)
    stock_df['Prev_Close'] = stock_df['Close'].shift(1)
    stock_df.drop(['Open', 'Low', 'High', 'Volume'], axis=1, inplace=True)
    stock_df = stock_df.tail(1)

    max_SMA = max(stock_df['20_SMA'].item(), stock_df['50_SMA'].item(), stock_df['200_SMA'].item())
    min_SMA = min(stock_df['20_SMA'].item(), stock_df['50_SMA'].item(), stock_df['200_SMA'].item())
    ABS_Spread = max_SMA - min_SMA
    stock_df['Spread%'] = round((ABS_Spread / stock_df['200_SMA'].item()) * 100,2)

    return stock_df

# function to compute stock attributes
def get_common_features(stock_ids, df_mypf):

  df_prec_dev = pd.DataFrame()
  df_tmp = get_screener_features()
  df_rs = get_relative_strength(stock_ids)

  for stock_id in stock_ids:
      tmp = stock_prec_dev(stock_id)
      tmp = tmp.reset_index()
      df_prec_dev = pd.concat([df_prec_dev, tmp], ignore_index = True)
  df_prec_dev = pd.merge(df_prec_dev, df_mypf, on= 'Symbol')
  df_prec_dev = pd.merge(df_prec_dev, df_tmp, on= 'Symbol', how='left')
  df_prec_dev = pd.merge(df_prec_dev, df_rs, on= 'Symbol', how='left')
  #print(df_prec_dev.columns)
  df_prec_dev['Curr_PE'] = round(df_prec_dev['Close']/df_prec_dev['EPS'],1)
  df_prec_dev['Dev%_PE'] = round((df_prec_dev['Curr_PE'] - df_prec_dev['MedPE'])*100/df_prec_dev['MedPE'],2)
  df_prec_dev['Conviction'] = df_prec_dev['Conviction'] + '-' + df_prec_dev['CapType']
  return df_prec_dev

# function to arrange stock features
def arrange_features(df_stocks, common_cols, diff_cols):
  df_stocks_common = df_stocks[common_cols].drop_duplicates()
  df_stocks_diff = df_stocks[diff_cols]
  df_stocks_diff['Investment'] = df_stocks_diff['AvgCost'] * df_stocks_diff['Shares']
  df_stocks_diff = df_stocks_diff.groupby(['Symbol'])[['Shares', 'Investment']].aggregate(['sum']).reset_index()
  df_stocks_diff.columns = ['Symbol', 'Shares', 'Investment']
  df_stocks_diff['AvgCost'] = round(df_stocks_diff['Investment']/df_stocks_diff['Shares'],2)
  df_stocks = pd.merge(df_stocks_diff, df_stocks_common, on='Symbol')
  return df_stocks

# plot fact distribution across dimension
def plot_pie_chart(df, dimension, fact):
  # grouping the data by category and calculating the sum of fact for each type
  grouped_data = df.groupby(dimension)[fact].sum()

  # sorting the grouped data in descending order
  grouped_data = grouped_data.sort_values(ascending=False)

  # creating a pie chart
  grouped_data.plot.pie(autopct='%1.1f%%', startangle=90, figsize=(6, 6))

  # adding a title and displaying the plot
  plt.title(f'{dimension} {fact} Distribution')
  plt.ylabel('')  # To hide the y-label
  plt.show()

In [7]:
# function to get portfolio features

def get_portfolio_features(df_common_features):

  print_date_time()
  print('-------------------')

  #df_common_features["Target"] = df_common_features["Target"].fillna(df_common_features["Max"])
  df_common_features['NTT'] = np.where(df_common_features['Strategy']== 'NTT', df_common_features["Target"], df_common_features['Max'])
  df_common_features['LTT'] = np.where(df_common_features['Strategy']== 'BTT', df_common_features["Target"], df_common_features['Max'])
  df_common_features['BOL'] = df_common_features['Min']

  tmp_df = df_common_features[df_common_features['Symbol'].isin(mypf_df[mypf_df['InPortfolio'] != 'NA'].Symbol.values)]
  print('qualified stocks: '+str(len(tmp_df['Symbol'].unique())))
  tmp_df1 = tmp_df[tmp_df['LatestQtr'] == 1]
  print('with latest results: '+str(len(tmp_df1['Symbol'].unique())))
  tmp_df1 = tmp_df1[tmp_df1['StarStock'] == 1]
  print('still star stocks: '+str(len(tmp_df1['Symbol'].unique())))
  tmp_df['Investment'] = tmp_df['AvgCost'] * tmp_df['Shares']
  tmp_df['Current'] = round(tmp_df['Close'] * tmp_df['Shares'],0)
  tmp_df['Previous'] = tmp_df['Prev_Close'] * tmp_df['Shares']
  tmp_df['EstimatedST'] = tmp_df['NTT'] * tmp_df['Shares']
  tmp_df['EstimatedLT'] = tmp_df['LTT'] * tmp_df['Shares']
  tmp_df['Current P/L'] = round((tmp_df['Current'] - tmp_df['Investment']),0)
  tmp_df['Today P/L%'] = round((tmp_df['Current'] - tmp_df['Previous'])*100/tmp_df['Previous'],2)
  tmp_df['Current P/L%'] = round((tmp_df['Current'] - tmp_df['Investment'])*100/tmp_df['Investment'],2)
  tmp_df['EstimatedST P/L%'] = round((tmp_df['EstimatedST'] - tmp_df['Investment'])*100/tmp_df['Investment'],2)
  tmp_df['EstimatedLT P/L%'] = round((tmp_df['EstimatedLT'] - tmp_df['Investment'])*100/tmp_df['Investment'],2)
  tmp_df['NTT%'] = round((tmp_df['NTT'] - tmp_df['Close'])*100/tmp_df['Close'],2)
  tmp_df['LTT%'] = round((tmp_df['LTT'] - tmp_df['Close'])*100/tmp_df['Close'],2)
  tmp_df['Gained%'] = round((tmp_df['Close'] - tmp_df['BOL'])*100/tmp_df['BOL'],2)
  investment = round(sum(tmp_df['AvgCost']*tmp_df['Shares']),0)
  current = round(sum(tmp_df['Close']*tmp_df['Shares']),0)
  tmp_df['InitAlloc%'] = round(tmp_df['Investment']*100/investment,2)
  tmp_df['CurrAlloc%'] = round(tmp_df['Current']*100/current,2)
  tmp_df['FTT'] = tmp_df['LTT']
  tmp_df.loc[tmp_df['Strategy'] == 'NTT', 'FTT'] = tmp_df['NTT']
  tmp_df['FTT%'] = tmp_df['LTT%']
  tmp_df.loc[tmp_df['Strategy'] == 'NTT', 'FTT%'] = tmp_df['NTT%']
  tmp_df['FTT Amt'] = round(tmp_df['FTT%'] * tmp_df['Current']/100,0)
  tmp_df['OTT%'] = round((tmp_df['FTT'] - tmp_df['AvgCost'])*100/tmp_df['AvgCost'],2)
  tmp_df['RRR Ind'] = round(tmp_df['Current P/L']/tmp_df['FTT Amt'],2)
  tmp_df['Risk Ind'] = round(tmp_df['Current P/L%']*tmp_df['CurrAlloc%'],0)

  return tmp_df

# function to print portfolio features
def print_portfolio_stats(df_portfolio_features, myinvmt_df):
  from pyxirr import xirr

  total_booked_amt, reserve_amt, cy_booked_amt, py_booked_amt = get_amt()

  dates = myinvmt_df['Date'].values
  dates = np.append(dates, datetime.date.today().strftime('%d-%b-%y'))
  investment = myinvmt_df['Investment'].values
  dates= pd.to_datetime(dates)

  current = round(sum(df_portfolio_features['Close']*df_portfolio_features['Shares']),0) + reserve_amt
  investment_xirr = np.append(investment, current)
  cagr = round(xirr(pd.DataFrame({"dates": dates, "amounts": investment_xirr}))*100,2)

  investment = -sum(investment)
  invested = round(sum(df_portfolio_features['AvgCost']*df_portfolio_features['Shares']),0) + reserve_amt
  previous = round(sum(df_portfolio_features['Prev_Close']*df_portfolio_features['Shares']),0) + reserve_amt
  cy_invested = investment + py_booked_amt

  today_pnl_amount = current-previous
  today_pnl_percentage = round((current-previous)*100/previous,2)

  curr_pnl_amount = current-invested
  curr_pnl_percentage = round((curr_pnl_amount)*100/(cy_invested),2)

  cy_pnl_amount = cy_booked_amt + curr_pnl_amount
  cy_pnl_percentage = round((cy_pnl_amount)*100/cy_invested,2)

  overall_pnl_amount = total_booked_amt + curr_pnl_amount
  overall_pnl_percentage = round((overall_pnl_amount)*100/investment,2)

  estimate_st = round(sum(df_portfolio_features['FTT']*df_portfolio_features['Shares']),0)  + reserve_amt
  est_st_pnl_amount = estimate_st-current
  est_st_pnl_percentage = round((est_st_pnl_amount)*100/current,2)

  estimate_lt = round(sum(df_portfolio_features['LTT']*df_portfolio_features['Shares']),0)  + reserve_amt
  est_lt_pnl_amount = estimate_lt-current
  est_lt_pnl_percentage = round((est_lt_pnl_amount)*100/current,2)

  total_profit = round(sum(df_portfolio_features[df_portfolio_features['Current P/L%'] > 0]['Current']) - sum(df_portfolio_features[df_portfolio_features['Current P/L%'] > 0]['Investment']),0)
  total_loss = round(sum(df_portfolio_features[df_portfolio_features['Current P/L%'] < 0]['Current']) - sum(df_portfolio_features[df_portfolio_features['Current P/L%'] < 0]['Investment']),0)

  cy_booked_percentage = round((cy_booked_amt)*100/current,2)
  py_booked_percentage = round((py_booked_amt)*100/investment,2)
  total_booked_percentage = round((total_booked_amt)*100/investment,2)

  print('-------------------')
  print('Initial Investment: ', format_amt(investment))
  print('CY Investment: ', format_amt(cy_invested))
  print('Reserve: ', format_amt(reserve_amt))
  print('Current: ',  format_amt(current))
  print('-------------------')
  print('Today PnL: '+ '{} ({}%)'.format(format_amt(today_pnl_amount), today_pnl_percentage))
  print('Current PnL: '+ '{} ({}%)'.format(format_amt(curr_pnl_amount), curr_pnl_percentage))
  print('CY Booked + Current PnL: '+ '{} ({}%)'.format(format_amt(cy_pnl_amount), cy_pnl_percentage))
  print('-------------------')
  print('Total profit: ', format_amt(total_profit))
  print('Total loss: ', format_amt(total_loss))
  print('-------------------')
  print('Total Booked + Current PnL: '+ '{} ({}%)'.format(format_amt(overall_pnl_amount), overall_pnl_percentage))
  print('Total Booked PnL: '+ '{} ({}%)'.format(format_amt(total_booked_amt), total_booked_percentage))
  print('Curr Year Booked PnL: '+ '{} ({}%)'.format(format_amt(cy_booked_amt), cy_booked_percentage))
  print('Prev Year Booked PnL: '+ '{} ({}%)'.format(format_amt(py_booked_amt), py_booked_percentage))
  print('===================')
  print('Est FTT: ',  format_amt(estimate_st))
  print('Est FTT PnL: '+ '{} ({}%)'.format(format_amt(est_st_pnl_amount), est_st_pnl_percentage))

  print('===================')
  print('Deployed: ', format_amt(investment))

  print('Current: ', format_amt(current))

  print('CAGR/XIRR %: '+'{}%'.format(cagr))

In [8]:
# get start and end date
start_date, end_date = get_start_end_date()

# get portfolio and prospects data
mypfs_df = get_mypfs_df()
mypps_df = get_mypps_df()
myinvmt_df = get_myinvmt_df()

# merge above datasets
mypf_df = pd.merge(mypfs_df, mypps_df, on="Symbol")

# seggregate dm and sv portfolio
dm_pf = mypf_df[mypf_df['InPortfolio'] == 'DM']
sv_pf = mypf_df[mypf_df['InPortfolio'] == 'SV']

# build portfolio stock dataframe
dm_stocks = get_stock_ids(dm_pf)
sv_stocks = get_stock_ids(sv_pf)
df_stocks = pd.concat([dm_pf,sv_pf], ignore_index = True)

# arrange common and diff stock features
common_cols = ['Symbol', 'Target', 'Criteria', 'Strategy', 'CumlRnk', 'LatestQtr', 'StarStock', 'Conviction', 'Category', 'InFolio', 'XIRR', 'MBQ']
diff_cols = ['Symbol', 'AvgCost', 'Shares']
df_stocks = arrange_features(df_stocks, common_cols, diff_cols)

# get common features
stock_ids = df_stocks['Symbol'].values
df_common_features = get_common_features(stock_ids, df_stocks)

df_common_features.reset_index(drop=True, inplace=True)
df_common_features.drop(['Date'], axis=1, inplace=True)
# get and print portfolio features
df_portfolio_features = get_portfolio_features(df_common_features)

print_portfolio_stats(df_portfolio_features, myinvmt_df)

df = df_portfolio_features
#plot_pie_chart(df, 'CapType', 'Current')
list_ox40n = list(df[df['MBQ'].str.contains('OX40N', na=False)]['Symbol'].values)

Run date time (IST): 2026-03-25 09:52:00
-------------------
qualified stocks: 86
with latest results: 26
still star stocks: 16
-------------------
Initial Investment:  1.36 C
CY Investment:  1.62 C
Reserve:  1.61 K
Current:  1.32 C
-------------------
Today PnL: 2.70 L (2.09%)
Current PnL: -45.61 L (-28.07%)
CY Booked + Current PnL: -29.72 L (-18.29%)
-------------------
Total profit:  57.16 K
Total loss:  -46.18 L
-------------------
Total Booked + Current PnL: -2.74 L (-2.02%)
Total Booked PnL: 42.87 L (31.64%)
Curr Year Booked PnL: 15.89 L (12.08%)
Prev Year Booked PnL: 26.98 L (19.91%)
===================
Est FTT:  2.48 C
Est FTT PnL: 1.16 C (88.49%)
===================
Deployed:  1.36 C
Current:  1.32 C
CAGR/XIRR %: -1.47%

In [9]:
# top 5 near their targets
cols = ['Symbol', 'Today P/L%', 'Current P/L%', 'FTT%', 'OTT%', 'FTT Amt', 'Current P/L', 'Current', 'FTT', 'Dev%_PE', 'RSI_14','Conviction', 'Spread%',  'CumlRnk', 'RRR Ind', 'CurrAlloc%', 'Gained%', 'Criteria', 'Strategy', 'Category']
df_tmp = df_portfolio_features[~df_portfolio_features['Symbol'].isin(['ENRIN','BLUSPRING','DIGITIDE'])]
df_tmp = df_tmp.sort_values(by = 'FTT Amt', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
50,MASFIN,2.15,-6.83,30.48,21.57,27825.0,-6690.0,91290.0,397.04,-19.60,47.0,H-SC,2.84,167.0,-0.24,0.69,24.51,XR,ATH,FINANCE
77,TTKPRESTIG,1.40,-42.19,73.15,0.09,42614.0,-42521.0,58256.0,770.00,35.11,36.0,M-SC,19.97,250.0,-1.00,0.44,1.40,OX40N,NTT,DURABLES
2,ABBOTINDIA,5.16,-10.09,31.32,18.07,50363.0,-18055.0,160800.0,35195.00,-23.42,50.0,X-MC,10.60,58.0,-0.36,1.22,5.16,X40,ATH,PHARMA
37,ICICIGI,1.66,-6.83,28.09,19.34,52369.0,-13676.0,186433.0,2252.93,-21.55,34.0,X-MC,4.06,66.0,-0.26,1.42,3.06,X40,ATH,INSURANCE
67,SONACOMS,2.01,-14.42,62.53,39.09,54133.0,-14587.0,86572.0,804.02,-32.22,45.0,M-MC,7.46,193.0,-0.27,0.66,22.47,AR,ATH,AUTO

In [10]:
# top 5 today
df_tmp = df_portfolio_features.sort_values(by = 'Today P/L%', ascending=False)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
2,ABBOTINDIA,5.16,-10.09,31.32,18.07,50363.0,-18055.0,160800.0,35195.00,-23.42,50.0,X-MC,10.60,58.0,-0.36,1.22,5.16,X40,ATH,PHARMA
56,RAJOOENG,4.86,-48.00,168.48,39.61,89800.0,-49200.0,53300.0,143.10,-64.86,35.0,H-SC,32.27,136.0,-0.55,0.41,4.86,AR,ATH,MISC
55,RAJESHEXPO,4.62,-82.85,483.53,0.07,113746.0,-113653.0,23524.0,518.00,762.37,20.0,L-SC,36.05,268.0,-1.00,0.18,4.62,OX40N,NTT,JEWELLERY
6,ASIANPAINT,4.53,-20.21,56.06,24.52,126788.0,-57274.0,226165.0,3460.25,-19.53,41.0,X-LC,9.84,30.0,-0.45,1.72,4.53,X40,ATH,PAINTS
25,EASEMYTRIP,4.22,-61.87,282.05,45.70,190181.0,-109387.0,67428.0,26.40,-29.98,43.0,M-SC,8.96,204.0,-0.58,0.51,11.09,XY24,NTT,TRAVEL

In [11]:
# bottom 5 today
df_tmp = df_portfolio_features.sort_values(by = 'Today P/L%', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
4,ALKYLAMINE,-0.90,-40.29,224.30,93.63,135213.0,-40681.0,60282.0,4546.37,-36.05,51.0,H-SC,25.89,142.0,-0.30,0.46,13.11,SR,ATH,CHEMICALS
78,UNITDSPR,-0.66,-3.09,24.62,20.77,55863.0,-7242.0,226902.0,1644.00,-14.02,46.0,X-MC,1.92,64.0,-0.13,1.73,3.45,X40N,NTT,BREWERIES
76,TRIDENT,-0.43,-32.26,89.72,28.51,56067.0,-29764.0,62491.0,48.00,-12.92,55.0,M-SC,14.09,223.0,-0.53,0.48,14.69,XR,NTT,TEXTILES
43,INFY,-0.35,-13.29,54.81,34.24,148710.0,-41569.0,271319.0,1972.00,-31.79,41.0,X-LC,15.08,3.0,-0.28,2.06,4.34,X40,NTT,IT
49,LAOPALA,0.18,-45.61,155.72,39.09,111044.0,-59795.0,71310.0,464.00,55.93,37.0,H-SC,15.70,154.0,-0.54,0.54,2.43,AR,NTT,CERAMICS

In [12]:
# top 5 to exit based on CumlRnk
df_tmp = df_portfolio_features[~df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])]
df_tmp = df_tmp[(df_tmp['Current P/L%'] > -1) & (df_tmp['Current P/L%'] < 1)].sort_values(by = 'CumlRnk', ascending=False)
df_tmp[cols].head()

Empty DataFrame
Columns: [Symbol, Today P/L%, Current P/L%, FTT%, OTT%, FTT Amt, Current P/L, Current, FTT, Dev%_PE, RSI_14, Conviction, Spread%, CumlRnk, RRR Ind, CurrAlloc%, Gained%, Criteria, Strategy, Category]
Index: []

In [13]:
# OX40N stocks to exit
df_tmp = df_portfolio_features[(df_portfolio_features['Symbol'].isin(list_ox40n))].sort_values(by = 'Current P/L%', ascending=False)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
26,FINCABLES,2.02,5.35,97.36,107.91,151431.0,7893.0,155537.0,1641.55,-5.12,47.0,M-SC,8.12,220.0,0.05,1.18,17.02,OX40N,ATH,CABLES
66,SIS,0.69,-35.01,86.57,21.26,62473.0,-38867.0,72165.0,528.00,1688.08,44.0,H-SC,14.37,168.0,-0.62,0.55,7.30,OX40N,NTT,MISC
18,CERA,1.59,-37.56,98.41,23.89,108088.0,-66069.0,109834.0,9475.00,-39.86,49.0,H-SC,19.02,153.0,-0.61,0.84,5.55,OX40N,NTT,CERAMICS
72,TATAELXSI,1.74,-38.71,115.40,32.03,93251.0,-51028.0,80807.0,9161.00,-23.39,41.0,H-SC,21.02,158.0,-0.55,0.61,5.29,OX40N,NTT,IT
77,TTKPRESTIG,1.40,-42.19,73.15,0.09,42614.0,-42521.0,58256.0,770.00,35.11,36.0,M-SC,19.97,250.0,-1.00,0.44,1.40,OX40N,NTT,DURABLES

In [14]:
# top 5 to book for rotation
df_tmp = df_portfolio_features[(df_portfolio_features['Current P/L%'] > 20) ].sort_values(by = 'CumlRnk', ascending=False)
df_tmp[cols].head()

Empty DataFrame
Columns: [Symbol, Today P/L%, Current P/L%, FTT%, OTT%, FTT Amt, Current P/L, Current, FTT, Dev%_PE, RSI_14, Conviction, Spread%, CumlRnk, RRR Ind, CurrAlloc%, Gained%, Criteria, Strategy, Category]
Index: []

In [15]:
# top 5 to monitor for exit
df_tmp = df_portfolio_features[~df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])]
df_tmp = df_tmp[(df_tmp['Current P/L%'] > 0) ].sort_values(by = 'Dev%_PE', ascending=False)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
26,FINCABLES,2.02,5.35,97.36,107.91,151431.0,7893.0,155537.0,1641.55,-5.12,47.0,M-SC,8.12,220.0,0.05,1.18,17.02,OX40N,ATH,CABLES
1,ABB,1.72,15.00,26.58,45.57,79970.0,39245.0,300864.0,7934.00,-26.10,57.0,H-MC,13.45,125.0,0.49,2.29,33.60,AR,NTT,ELECTRICAL

In [16]:
# top 5 to book for rotation from weak conviction
df_tmp = df_portfolio_features[~df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])]
df_tmp = df_tmp[~df_tmp['Criteria'].isin(['XY25','XY24','X40', 'X40N'])].sort_values(by = 'RRR Ind', ascending=False)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
1,ABB,1.72,15.00,26.58,45.57,79970.0,39245.0,300864.0,7934.00,-26.10,57.0,H-MC,13.45,125.0,0.49,2.29,33.60,AR,NTT,ELECTRICAL
26,FINCABLES,2.02,5.35,97.36,107.91,151431.0,7893.0,155537.0,1641.55,-5.12,47.0,M-SC,8.12,220.0,0.05,1.18,17.02,OX40N,ATH,CABLES
40,INDIAMART,3.67,-12.51,136.28,106.72,147057.0,-15428.0,107908.0,4810.62,-60.55,42.0,H-SC,11.95,140.0,-0.10,0.82,7.94,AR,ATH,MISC
85,ZYDUSLIFE,1.22,-5.38,43.35,35.63,85960.0,-11282.0,198292.0,1286.17,-17.57,49.0,H-MC,5.40,120.0,-0.13,1.51,10.39,AR,ATH,PHARMA
84,WIPRO,0.55,-22.16,121.31,72.27,160004.0,-37551.0,131897.0,420.00,-29.71,33.0,M-LC,17.70,98.0,-0.23,1.00,1.19,XR,NTT,IT

In [17]:
# top 5 to accumulate based on lowest RSI_14
df_tmp = df_portfolio_features[df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])].sort_values(by = 'RSI_14', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
53,PGHH,2.03,-27.40,81.82,32.01,126841.0,-58496.0,155024.0,17616.87,-50.89,23.0,X-MC,16.44,57.0,-0.46,1.18,2.46,X40,ATH,FMCG
58,RELAXO,2.73,-65.61,342.85,52.31,171161.0,-95237.0,49923.0,1176.00,-63.41,26.0,X-SC,27.44,92.0,-0.56,0.38,4.20,X40N,NTT,FOOTWEAR
38,ICICIPRULI,1.90,-9.37,44.24,30.73,78991.0,-18455.0,178550.0,790.00,-33.75,28.0,X-MC,4.92,78.0,-0.23,1.36,3.10,X40,ATH,INSURANCE
34,HDFCBANK,2.79,-8.49,40.28,28.37,86577.0,-19948.0,214937.0,1073.00,-22.01,28.0,X-LC,12.28,26.0,-0.23,1.63,2.79,X40,BTT,BANKS
12,BATAINDIA,2.70,-57.60,218.86,35.20,119410.0,-74110.0,54560.0,2096.00,-28.52,30.0,X-SC,31.76,91.0,-0.62,0.41,5.05,X40,NTT,FOOTWEAR

In [18]:
# top 5 to accumulate based on Spread and CumlRnk
df_tmp = df_portfolio_features[df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])]
df_tmp = df_tmp[(df_tmp['CumlRnk'] < 100)].sort_values(by = 'Spread%', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
78,UNITDSPR,-0.66,-3.09,24.62,20.77,55863.0,-7242.0,226902.0,1644.00,-14.02,46.0,X-MC,1.92,64.0,-0.13,1.73,3.45,X40N,NTT,BREWERIES
65,SIEMENS,2.67,-17.19,51.57,25.51,79469.0,-31995.0,154100.0,4671.50,29.40,45.0,H-LC,2.32,51.0,-0.40,1.17,13.48,AR,ATH,ELECTRICAL
59,RELIANCE,0.48,-8.94,37.60,25.30,68808.0,-17964.0,182999.0,1952.00,-11.19,53.0,X-LC,3.49,21.0,-0.26,1.39,22.18,XY25,BTT,REFINERIES
82,VOLTAS,3.30,5.23,37.98,45.20,76630.0,10023.0,201765.0,1856.00,20.46,42.0,X-MC,3.52,79.0,0.13,1.53,12.38,XY25,NTT,AC
37,ICICIGI,1.66,-6.83,28.09,19.34,52369.0,-13676.0,186433.0,2252.93,-21.55,34.0,X-MC,4.06,66.0,-0.26,1.42,3.06,X40,ATH,INSURANCE

In [19]:
# top 5 to accumulate based on lowest Gained%
df_tmp = df_portfolio_features[df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])].sort_values(by = 'Gained%', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
45,ITC,1.58,-22.07,52.78,19.06,139910.0,-75084.0,265082.0,452.00,-57.14,37.0,X-LC,18.81,1.0,-0.54,2.02,1.86,X40,NTT,FMCG
73,TCS,0.55,-29.20,78.76,26.57,258347.0,-135255.0,328018.0,4311.59,-40.02,32.0,X-LC,17.53,2.0,-0.52,2.49,2.37,X40,ATH,IT
53,PGHH,2.03,-27.40,81.82,32.01,126841.0,-58496.0,155024.0,17616.87,-50.89,23.0,X-MC,16.44,57.0,-0.46,1.18,2.46,X40,ATH,FMCG
21,DABUR,1.80,-16.13,71.33,43.70,148413.0,-40003.0,208065.0,735.00,-23.90,30.0,X-MC,7.08,70.0,-0.27,1.58,2.79,XY24,BTT,FMCG
34,HDFCBANK,2.79,-8.49,40.28,28.37,86577.0,-19948.0,214937.0,1073.00,-22.01,28.0,X-LC,12.28,26.0,-0.23,1.63,2.79,X40,BTT,BANKS

In [20]:
# top 5 to accumulate based on lowest CurrAlloc%
df_tmp = df_portfolio_features[df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])].sort_values(by = 'CurrAlloc%', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
58,RELAXO,2.73,-65.61,342.85,52.31,171161.0,-95237.0,49923.0,1176.00,-63.41,26.0,X-SC,27.44,92.0,-0.56,0.38,4.20,X40N,NTT,FOOTWEAR
12,BATAINDIA,2.70,-57.60,218.86,35.20,119410.0,-74110.0,54560.0,2096.00,-28.52,30.0,X-SC,31.76,91.0,-0.62,0.41,5.05,X40,NTT,FOOTWEAR
54,QUESS,0.89,-27.40,139.52,73.90,108177.0,-29258.0,77535.0,424.00,-60.88,39.0,X-SC,21.61,80.0,-0.27,0.59,4.21,XY24,NTT,MISC
36,HONAUT,2.77,-26.35,105.45,51.31,149765.0,-50813.0,142025.0,58357.33,-38.78,36.0,X-SC,16.17,90.0,-0.34,1.08,4.37,X40N,ATH,ELECTRICAL
51,MEDANTA,3.77,-13.56,47.06,27.12,71807.0,-23931.0,152586.0,1486.00,-16.14,37.0,X-SC,12.81,87.0,-0.33,1.16,4.22,XY24,NTT,HEALTHCARE

In [21]:
# top 5 to accumulate based on CumlRnk
df_tmp = df_portfolio_features.sort_values(by = 'CumlRnk', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
45,ITC,1.58,-22.07,52.78,19.06,139910.0,-75084.0,265082.0,452.00,-57.14,37.0,X-LC,18.81,1.0,-0.54,2.02,1.86,X40,NTT,FMCG
73,TCS,0.55,-29.20,78.76,26.57,258347.0,-135255.0,328018.0,4311.59,-40.02,32.0,X-LC,17.53,2.0,-0.52,2.49,2.37,X40,ATH,IT
43,INFY,-0.35,-13.29,54.81,34.24,148710.0,-41569.0,271319.0,1972.00,-31.79,41.0,X-LC,15.08,3.0,-0.28,2.06,4.34,X40,NTT,IT
75,TMPV,2.67,-27.27,87.79,36.58,227196.0,-97046.0,258795.0,600.00,-84.72,41.0,X-LC,7.50,4.0,-0.43,1.97,4.67,XY24,NTT,AUTO
33,HCLTECH,0.24,-10.66,38.62,23.83,83468.0,-25798.0,216126.0,1908.19,-6.12,46.0,X-LC,11.66,8.0,-0.31,1.64,4.94,X40,ATH,IT

In [22]:
# top 5 for average up
df_tmp = df_portfolio_features[(df_portfolio_features['Dev%_200'] > 5)].sort_values(by = 'CurrAlloc%', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
1,ABB,1.72,15.0,26.58,45.57,79970.0,39245.0,300864.0,7934.0,-26.1,57.0,H-MC,13.45,125.0,0.49,2.29,33.6,AR,NTT,ELECTRICAL

In [23]:
# top 5 RSP
df_tmp = df_portfolio_features.sort_values(by = 'RSP', ascending=False)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
30,HAPPSTMNDS,1.03,-49.63,266.97,84.85,172356.0,-63605.0,64560.0,1480.71,-40.12,56.0,H-SC,26.09,152.0,-0.37,0.49,19.56,AR,ATH,IT
69,SURYODAY,2.02,-27.05,68.66,23.03,89691.0,-48440.0,130631.0,216.00,42.54,50.0,H-SC,5.91,166.0,-0.54,0.99,27.67,XR,NTT,BANKS
2,ABBOTINDIA,5.16,-10.09,31.32,18.07,50363.0,-18055.0,160800.0,35195.00,-23.42,50.0,X-MC,10.60,58.0,-0.36,1.22,5.16,X40,ATH,PHARMA
80,VALIANTORG,2.11,-49.92,247.72,74.15,202982.0,-81665.0,81940.0,838.00,-247.22,53.0,H-SC,27.99,145.0,-0.40,0.62,21.94,XR,NTT,CHEMICALS
47,JSWINFRA,2.34,-12.05,32.38,16.43,63158.0,-26720.0,195054.0,342.00,-24.58,51.0,X-MC,11.52,61.0,-0.42,1.48,7.07,X40N,NTT,REALTY

In [24]:
# Top N allocation
df_tmp = df_portfolio_features.sort_values(by = 'CurrAlloc%', ascending=False)
top_n_values = [10, 25, 50]

sum_df = pd.DataFrame({
    'Top_N': top_n_values,
    'Sum_Alloc%': [df_tmp['CurrAlloc%'].head(n).sum() for n in top_n_values]
})

sum_df

   Top_N  Sum_Alloc%
0     10       20.77
1     25       45.78
2     50       78.14

In [25]:
# market-cap-wise allocation
df_tmp = df_portfolio_features[cols]
df_tmp.groupby(df_tmp['Conviction'].str[-2:])['CurrAlloc%'].sum().sort_values(ascending=False)

Conviction
SC    44.40
MC    30.18
LC    25.40
Name: CurrAlloc%, dtype: float64

In [26]:
# criteria-wise allocation
df_portfolio_features.groupby('Criteria')['CurrAlloc%'].sum().sort_values(ascending=False)

Criteria
XY24     27.06
X40      25.37
X40N     15.23
AR        9.19
XR        8.31
XY25      7.35
OX40N     6.65
SR        0.82
Name: CurrAlloc%, dtype: float64

In [27]:
# conviction-wise allocation
df_portfolio_features.groupby('Conviction')['CurrAlloc%'].sum().sort_values(ascending=False)

Conviction
X-LC    23.23
X-MC    22.68
H-SC    21.62
X-SC    12.28
M-SC     9.97
H-MC     5.11
M-MC     2.03
H-LC     1.17
M-LC     1.00
L-SC     0.53
L-MC     0.36
Name: CurrAlloc%, dtype: float64

In [28]:
# sector-wise stats
df_tmp = df_portfolio_features.groupby('Category')[['CurrAlloc%', 'Current', 'Current P/L', 'FTT Amt']].sum().sort_values(by=['Current', 'Current P/L'], ascending=False)
df_tmp['Current P/L%'] = round(df_tmp['Current P/L'] * 100 / df_tmp['Current'], 2)
df_tmp['FTT%'] = round(df_tmp['FTT Amt'] * 100 / df_tmp['Current'], 2)
cols = ['CurrAlloc%', 'Current P/L%', 'FTT%']
df_tmp[cols].sort_values(by=['CurrAlloc%'], ascending=False)

               CurrAlloc%  Current P/L%    FTT%
Category
FMCG                15.02        -26.51   71.43
FINANCE             13.11        -24.55   75.31
IT                  11.83        -44.59  118.17
MISC                 6.99        -46.19  109.69
ELECTRICAL           6.57        -12.06   54.97
PAINTS               5.08        -47.29   72.87
INSURANCE            4.70         -9.81   47.38
BANKS                4.55        -28.48   93.70
PHARMA               4.15         -7.61   41.49
AUTO                 3.73        -33.38   86.30
AC                   2.06        -17.75   49.67
HEALTHCARE           1.89        -44.20   81.83
TRAVEL               1.82        -86.73  180.23
FOOTWEAR             1.77        -89.75  165.83
DURABLES             1.75        -68.33  109.28
APPARELS             1.74        -17.61   57.73
BREWERIES            1.73         -3.19   24.62
REALTY               1.48        -13.70   32.38
REFINERIES           1.39         -9.82   37.60
CERAMICS             1.38        -69.48  120.97
CEMENT               1.25        -62.62  184.28
CABLES               1.18          5.07   97.36
ENGINEERING          1.11        -66.07  142.03
CHEMICALS            1.08        -86.02  237.79
JEWELLERY            1.03       -136.22  218.30
ENTERTAINMENT        0.76        -92.95  208.03
TEXTILES             0.48        -47.63   89.72
HOTELS               0.35       -149.11  236.98

In [29]:
# money to be made criteria-wise
df_portfolio_features.groupby('Criteria')['FTT Amt'].agg(['sum', 'count']).sort_values(by='sum', ascending=False)

                sum  count
Criteria
XY24      4038150.0     21
X40       1836341.0     16
XR        1399065.0     12
AR        1364072.0     10
X40N      1297565.0     10
OX40N      917374.0     10
XY25       473428.0      5
SR         311147.0      2

In [30]:
# money to be made conviction-wise
df_portfolio_features.groupby('Conviction')['FTT Amt'].agg(['sum', 'count']).sort_values(by='sum', ascending=False)

                  sum  count
Conviction
H-SC        3947283.0     24
X-MC        1750467.0     15
X-LC        1719704.0     13
M-SC        1607847.0     14
X-SC        1567521.0     10
H-MC         407494.0      3
L-SC         221764.0      2
M-LC         160004.0      1
M-MC         119780.0      2
H-LC          79469.0      1
L-MC          55809.0      1

In [31]:
# money to be made criteria and conviction-wise
df_portfolio_features.groupby(['Conviction', 'Criteria'])['FTT Amt'].agg(['sum', 'count']).sort_values(by='sum', ascending=False)

                           sum  count
Conviction Criteria
H-SC       XY24      1370987.0      6
           AR         986219.0      5
M-SC       XY24       929594.0      6
X-LC       X40        926281.0      7
H-SC       XR         884870.0      7
X-SC       XY24       851886.0      4
X-MC       X40        696429.0      7
           X40N       525014.0      4
X-SC       X40N       502004.0      4
M-SC       OX40N      409568.0      5
H-SC       OX40N      394060.0      4
X-LC       XY24       373624.0      2
H-SC       SR         311147.0      2
X-LC       X40N       270547.0      2
X-MC       XY24       270495.0      2
           XY25       258529.0      2
H-MC       XY24       241564.0      1
X-SC       X40        213631.0      2
M-SC       XR         190364.0      2
H-MC       AR         165930.0      2
M-LC       XR         160004.0      1
X-LC       XY25       149252.0      2
L-SC       OX40N      113746.0      1
           XR         108018.0      1
H-LC       AR          79469.0      1
M-SC       AR          78321.0      1
M-MC       XY25        65647.0      1
L-MC       XR          55809.0      1
M-MC       AR          54133.0      1

In [32]:
# notebook execution time

end_time = time.time()
execution_time = round(end_time - start_time, 0)
print(f"Notebook execution time: {execution_time} seconds")

Notebook execution time: 29.0 seconds