<a href="https://colab.research.google.com/github/ankit-rathi/Quantvesting_v2/blob/main/myStocks_Portfolio_Analysis.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
'''
!pip install pandas==2.2.2 -qq
!pip install pyxirr -qq
!pip install ta -qq
!pip install yfinance==0.2.59 -qq
'''

'\n!pip install pandas==2.2.2 -qq\n!pip install pyxirr -qq\n!pip install ta -qq\n!pip install yfinance==0.2.59 -qq\n'

In [2]:
# import libraries

import numpy as np
import pandas as pd
import datetime
import warnings
warnings.filterwarnings('ignore')
import yfinance as yfin
import ta
import matplotlib.pyplot as plt
import requests

In [3]:
# notebook start time
import time
import datetime
import pytz

start_time = time.time()

# function to print date timestamp
def print_date_time():
  tz_NY = pytz.timezone('Asia/Kolkata')
  datetime_NY = datetime.datetime.now(tz_NY)
  print("Run date time (IST):", datetime_NY.strftime("%Y-%m-%d %H:%M:%S"))

In [4]:
# function to get booked and reserved amount
def get_amt():
  # fetch the JSON data from the URL
  url = "https://raw.githubusercontent.com/ankit-rathi/Tradevesting_v1/main/data/myPortfolioAmts.json"
  response = requests.get(url)
  pf_amts = response.json()  # parse the JSON data

  # extract values from the JSON
  py_booked_amt_dm = pf_amts["py_booked_amt_dm"]
  py_booked_amt_sv = pf_amts["py_booked_amt_sv"]
  cy_booked_amt_dm = pf_amts["cy_booked_amt_dm"]
  cy_booked_amt_sv = pf_amts["cy_booked_amt_sv"]
  reserve_amt_dm = pf_amts["reserve_amt_dm"]
  reserve_amt_sv = pf_amts["reserve_amt_sv"]

  # perform calculations
  py_booked_amt = py_booked_amt_dm + py_booked_amt_sv
  cy_booked_amt = cy_booked_amt_dm + cy_booked_amt_sv
  reserve_amt = reserve_amt_dm + reserve_amt_sv
  total_booked_amt = py_booked_amt + cy_booked_amt

  return total_booked_amt, reserve_amt, cy_booked_amt, py_booked_amt

gen_output = 0

In [5]:
# function to format the amount
def format_amt(number):
    abs_number = abs(number)

    if abs_number >= 1_00_00_000:  # Crores
        formatted_amt = f"{number / 1_00_00_000:.2f} C"
    elif abs_number >= 1_00_000:  # Lakhs
        formatted_amt = f"{number / 1_00_000:.2f} L"
    elif abs_number >= 1_000:  # Thousands
        formatted_amt = f"{number / 1_000:.2f} K"
    else:
        formatted_amt = f"{number:.2f}"

    return formatted_amt

# function to set start and end date
def get_start_end_date():
  start_date = (datetime.date.today() + datetime.timedelta(days=-365)).strftime('%Y-%m-%d')
  end_date = (datetime.date.today() + datetime.timedelta(days=1)).strftime('%Y-%m-%d')
  return start_date, end_date

# function to fetch my portfolio csv
def get_mypfs_df():
  mypfs_df = pd.read_csv('https://raw.githubusercontent.com/ankit-rathi/Tradevesting_v1/main/data/myPortfolioStocks.csv')
  return mypfs_df

# function to fetch my prospects csv
def get_mypps_df():
  mypps_df = pd.read_csv('https://raw.githubusercontent.com/ankit-rathi/Tradevesting_v1/main/data/myProspectsScrips.csv')
  return mypps_df

# function to fetch screener data
def get_myscreen_df():
  myscreen_df = pd.read_csv('https://raw.githubusercontent.com/ankit-rathi/Tradevesting_v1/main/data/myScreenerDB.csv')
  return myscreen_df

# function to fetch momentum data
def get_myinvmt_df():
  myinvmt_df = pd.read_csv('https://raw.githubusercontent.com/ankit-rathi/Tradevesting_v1/main/data/myInvestments.csv')
  return myinvmt_df

# function to get the stock ids
def get_stock_ids(df_pf):
  stock_n100 = df_pf['Symbol'].unique()

  exclude = ['CADILAHC','MMTC', 'MASFIN']

  stock_ids = df_pf[~df_pf['Symbol'].isin(exclude) ]['Symbol'].unique()

  #mypf = mypf[mypf.Forecast.notnull()]
  #stock_ids = mypf['Symbol'].unique()

  #stock_ids.sort()
  return stock_ids

# get features from screener data
def get_screener_features():
  myscreen_df = get_myscreen_df()
  cols = ['Symbol', 'EPS', 'MedPE', 'ROCE%', 'ROE%', 'CapType']
  return myscreen_df[cols]

# get relative strength
def get_relative_strength(stock_list):

    # Dictionary to store stock tickers and their corresponding percentage price change
    stock_changes = {}

    # Loop through each stock and fetch its price data
    for stock in stock_list:
        try:
            # Download the stock data for the given date range
            stock_data = yfin.Ticker(stock + '.NS').history(period='1mo', interval='1d')[map(str.title, ['open', 'close', 'low', 'high', 'volume'])]

            # Calculate the percentage change for the stock
            if len(stock_data) > 0:
                start_price = stock_data['Close'].iloc[0]
                end_price = stock_data['Close'].iloc[-1]
                percent_change = round(((end_price - start_price) / start_price) * 100, 2)
                stock_changes[stock] = percent_change
            else:
                stock_changes[stock] = np.nan  # If no data is available, set to NaN

        except Exception as e:
            print(f"Error fetching data for {stock}: {e}")
            stock_changes[stock] = np.nan

    # Create a DataFrame with stock tickers and their percentage changes
    df = pd.DataFrame(list(stock_changes.items()), columns=['Symbol', 'Percent_Change'])

    # Drop any stocks with missing data (NaN values)
    df = df.dropna()

    # Calculate the percentile rank based on percentage change
    df['RSP'] = round(df['Percent_Change'].rank(pct=True) * 100, 2)
    cols = ['Symbol', 'RSP']
    df = df[cols]
    # Sort by percentile rank (optional)
    df = df.sort_values(by='RSP', ascending=False).reset_index(drop=True)

    return df

In [6]:
# function to get stock technicals
def stock_prec_dev(stock_symbol):
    #stock_symbol = 'ULTRACEMCO.NS'
    short_window = 20
    mid_window = 50
    long_window = 200
    moving_avg = 'SMA'

    start = datetime.datetime(*map(int, start_date.split('-')))
    end = datetime.datetime(*map(int, end_date.split('-')))

    stock_df = yfin.Ticker(stock_symbol + '.NS').history(period='max', interval='1d')[map(str.title, ['open', 'close', 'low', 'high', 'volume'])]

    stock_df['Max'] = round(max(stock_df['Close']),2)
    stock_df = stock_df[(stock_df.index <= end_date) & (stock_df.index >= start_date)]
    stock_df['200_SMA'] = round(stock_df['Close'].rolling(window = 200, min_periods = 1).mean(),0)
    stock_df['Dev%_200'] = round((stock_df['Close'] - stock_df['200_SMA'])*100/stock_df['200_SMA'],2)
    stock_df.dropna(axis = 0, inplace = True) # remove any null rows

    stock_df['20_SMA'] = stock_df['Close'].rolling(window=20).mean()
    stock_df['50_SMA'] = stock_df['Close'].rolling(window=50).mean()
    stock_df['Symbol'] = stock_symbol

    stock_df['Close'] = round(stock_df['Close'],2)
    stock_df['Min'] = round(min(stock_df['Close']),2)
    stock_df['RSI_14'] = ta.momentum.RSIIndicator(close=stock_df['Close'], window=14).rsi()
    stock_df['RSI_14'] = round(stock_df['RSI_14'],0)
    stock_df['Prev_Close'] = stock_df['Close'].shift(1)
    stock_df.drop(['Open', 'Low', 'High', 'Volume'], axis=1, inplace=True)
    stock_df = stock_df.tail(1)

    max_SMA = max(stock_df['20_SMA'].item(), stock_df['50_SMA'].item(), stock_df['200_SMA'].item())
    min_SMA = min(stock_df['20_SMA'].item(), stock_df['50_SMA'].item(), stock_df['200_SMA'].item())
    ABS_Spread = max_SMA - min_SMA
    stock_df['Spread%'] = round((ABS_Spread / stock_df['200_SMA'].item()) * 100,2)

    return stock_df

# function to compute stock attributes
def get_common_features(stock_ids, df_mypf):

  df_prec_dev = pd.DataFrame()
  df_tmp = get_screener_features()
  df_rs = get_relative_strength(stock_ids)

  for stock_id in stock_ids:
      tmp = stock_prec_dev(stock_id)
      tmp = tmp.reset_index()
      df_prec_dev = pd.concat([df_prec_dev, tmp], ignore_index = True)
  df_prec_dev = pd.merge(df_prec_dev, df_mypf, on= 'Symbol')
  df_prec_dev = pd.merge(df_prec_dev, df_tmp, on= 'Symbol', how='left')
  df_prec_dev = pd.merge(df_prec_dev, df_rs, on= 'Symbol', how='left')
  #print(df_prec_dev.columns)
  df_prec_dev['Curr_PE'] = round(df_prec_dev['Close']/df_prec_dev['EPS'],1)
  df_prec_dev['Dev%_PE'] = round((df_prec_dev['Curr_PE'] - df_prec_dev['MedPE'])*100/df_prec_dev['MedPE'],2)
  df_prec_dev['Conviction'] = df_prec_dev['Conviction'] + '-' + df_prec_dev['CapType']
  return df_prec_dev

# function to arrange stock features
def arrange_features(df_stocks, common_cols, diff_cols):
  df_stocks_common = df_stocks[common_cols].drop_duplicates()
  df_stocks_diff = df_stocks[diff_cols]
  df_stocks_diff['Investment'] = df_stocks_diff['AvgCost'] * df_stocks_diff['Shares']
  df_stocks_diff = df_stocks_diff.groupby(['Symbol'])[['Shares', 'Investment']].aggregate(['sum']).reset_index()
  df_stocks_diff.columns = ['Symbol', 'Shares', 'Investment']
  df_stocks_diff['AvgCost'] = round(df_stocks_diff['Investment']/df_stocks_diff['Shares'],2)
  df_stocks = pd.merge(df_stocks_diff, df_stocks_common, on='Symbol')
  return df_stocks

# plot fact distribution across dimension
def plot_pie_chart(df, dimension, fact):
  # grouping the data by category and calculating the sum of fact for each type
  grouped_data = df.groupby(dimension)[fact].sum()

  # sorting the grouped data in descending order
  grouped_data = grouped_data.sort_values(ascending=False)

  # creating a pie chart
  grouped_data.plot.pie(autopct='%1.1f%%', startangle=90, figsize=(6, 6))

  # adding a title and displaying the plot
  plt.title(f'{dimension} {fact} Distribution')
  plt.ylabel('')  # To hide the y-label
  plt.show()

In [7]:
# function to get portfolio features

def get_portfolio_features(df_common_features):

  print_date_time()
  print('-------------------')

  #df_common_features["Target"] = df_common_features["Target"].fillna(df_common_features["Max"])
  df_common_features['NTT'] = np.where(df_common_features['Strategy']== 'NTT', df_common_features["Target"], df_common_features['Max'])
  df_common_features['LTT'] = np.where(df_common_features['Strategy']== 'BTT', df_common_features["Target"], df_common_features['Max'])
  df_common_features['BOL'] = df_common_features['Min']

  tmp_df = df_common_features[df_common_features['Symbol'].isin(mypf_df[mypf_df['InPortfolio'] != 'NA'].Symbol.values)]
  print('qualified stocks: '+str(len(tmp_df['Symbol'].unique())))
  tmp_df1 = tmp_df[tmp_df['LatestQtr'] == 1]
  print('with latest results: '+str(len(tmp_df1['Symbol'].unique())))
  tmp_df1 = tmp_df1[tmp_df1['StarStock'] == 1]
  print('still star stocks: '+str(len(tmp_df1['Symbol'].unique())))
  tmp_df['Investment'] = tmp_df['AvgCost'] * tmp_df['Shares']
  tmp_df['Current'] = round(tmp_df['Close'] * tmp_df['Shares'],0)
  tmp_df['Previous'] = tmp_df['Prev_Close'] * tmp_df['Shares']
  tmp_df['EstimatedST'] = tmp_df['NTT'] * tmp_df['Shares']
  tmp_df['EstimatedLT'] = tmp_df['LTT'] * tmp_df['Shares']
  tmp_df['Current P/L'] = round((tmp_df['Current'] - tmp_df['Investment']),0)
  tmp_df['Today P/L%'] = round((tmp_df['Current'] - tmp_df['Previous'])*100/tmp_df['Previous'],2)
  tmp_df['Current P/L%'] = round((tmp_df['Current'] - tmp_df['Investment'])*100/tmp_df['Investment'],2)
  tmp_df['EstimatedST P/L%'] = round((tmp_df['EstimatedST'] - tmp_df['Investment'])*100/tmp_df['Investment'],2)
  tmp_df['EstimatedLT P/L%'] = round((tmp_df['EstimatedLT'] - tmp_df['Investment'])*100/tmp_df['Investment'],2)
  tmp_df['NTT%'] = round((tmp_df['NTT'] - tmp_df['Close'])*100/tmp_df['Close'],2)
  tmp_df['LTT%'] = round((tmp_df['LTT'] - tmp_df['Close'])*100/tmp_df['Close'],2)
  tmp_df['Gained%'] = round((tmp_df['Close'] - tmp_df['BOL'])*100/tmp_df['BOL'],2)
  investment = round(sum(tmp_df['AvgCost']*tmp_df['Shares']),0)
  current = round(sum(tmp_df['Close']*tmp_df['Shares']),0)
  tmp_df['InitAlloc%'] = round(tmp_df['Investment']*100/investment,2)
  tmp_df['CurrAlloc%'] = round(tmp_df['Current']*100/current,2)
  tmp_df['FTT'] = tmp_df['LTT']
  tmp_df.loc[tmp_df['Strategy'] == 'NTT', 'FTT'] = tmp_df['NTT']
  tmp_df['FTT%'] = tmp_df['LTT%']
  tmp_df.loc[tmp_df['Strategy'] == 'NTT', 'FTT%'] = tmp_df['NTT%']
  tmp_df['FTT Amt'] = round(tmp_df['FTT%'] * tmp_df['Current']/100,0)
  tmp_df['OTT%'] = round((tmp_df['FTT'] - tmp_df['AvgCost'])*100/tmp_df['AvgCost'],2)
  tmp_df['RRR Ind'] = round(tmp_df['Current P/L']/tmp_df['FTT Amt'],2)
  tmp_df['Risk Ind'] = round(tmp_df['Current P/L%']*tmp_df['CurrAlloc%'],0)

  return tmp_df

# function to print portfolio features
def print_portfolio_stats(df_portfolio_features, myinvmt_df):
  from pyxirr import xirr

  total_booked_amt, reserve_amt, cy_booked_amt, py_booked_amt = get_amt()

  dates = myinvmt_df['Date'].values
  dates = np.append(dates, datetime.date.today().strftime('%d-%b-%y'))
  investment = myinvmt_df['Investment'].values
  dates= pd.to_datetime(dates)

  current = round(sum(df_portfolio_features['Close']*df_portfolio_features['Shares']),0) + reserve_amt
  investment_xirr = np.append(investment, current)
  cagr = round(xirr(pd.DataFrame({"dates": dates, "amounts": investment_xirr}))*100,2)

  investment = -sum(investment)
  invested = round(sum(df_portfolio_features['AvgCost']*df_portfolio_features['Shares']),0) + reserve_amt
  previous = round(sum(df_portfolio_features['Prev_Close']*df_portfolio_features['Shares']),0) + reserve_amt
  cy_invested = investment + py_booked_amt

  today_pnl_amount = current-previous
  today_pnl_percentage = round((current-previous)*100/previous,2)

  curr_pnl_amount = current-invested
  curr_pnl_percentage = round((curr_pnl_amount)*100/(cy_invested),2)

  cy_pnl_amount = cy_booked_amt + curr_pnl_amount
  cy_pnl_percentage = round((cy_pnl_amount)*100/cy_invested,2)

  overall_pnl_amount = total_booked_amt + curr_pnl_amount
  overall_pnl_percentage = round((overall_pnl_amount)*100/investment,2)

  estimate_st = round(sum(df_portfolio_features['FTT']*df_portfolio_features['Shares']),0)  + reserve_amt
  est_st_pnl_amount = estimate_st-current
  est_st_pnl_percentage = round((est_st_pnl_amount)*100/current,2)

  estimate_lt = round(sum(df_portfolio_features['LTT']*df_portfolio_features['Shares']),0)  + reserve_amt
  est_lt_pnl_amount = estimate_lt-current
  est_lt_pnl_percentage = round((est_lt_pnl_amount)*100/current,2)

  total_profit = round(sum(df_portfolio_features[df_portfolio_features['Current P/L%'] > 0]['Current']) - sum(df_portfolio_features[df_portfolio_features['Current P/L%'] > 0]['Investment']),0)
  total_loss = round(sum(df_portfolio_features[df_portfolio_features['Current P/L%'] < 0]['Current']) - sum(df_portfolio_features[df_portfolio_features['Current P/L%'] < 0]['Investment']),0)

  cy_booked_percentage = round((cy_booked_amt)*100/current,2)
  py_booked_percentage = round((py_booked_amt)*100/investment,2)
  total_booked_percentage = round((total_booked_amt)*100/investment,2)

  print('-------------------')
  print('Initial Investment: ', format_amt(investment))
  print('CY Investment: ', format_amt(cy_invested))
  print('Reserve: ', format_amt(reserve_amt))
  print('Current: ',  format_amt(current))
  print('-------------------')
  print('Today PnL: '+ '{} ({}%)'.format(format_amt(today_pnl_amount), today_pnl_percentage))
  print('Current PnL: '+ '{} ({}%)'.format(format_amt(curr_pnl_amount), curr_pnl_percentage))
  print('CY Booked + Current PnL: '+ '{} ({}%)'.format(format_amt(cy_pnl_amount), cy_pnl_percentage))
  print('-------------------')
  print('Total profit: ', format_amt(total_profit))
  print('Total loss: ', format_amt(total_loss))
  print('-------------------')
  print('Total Booked + Current PnL: '+ '{} ({}%)'.format(format_amt(overall_pnl_amount), overall_pnl_percentage))
  print('Total Booked PnL: '+ '{} ({}%)'.format(format_amt(total_booked_amt), total_booked_percentage))
  print('Curr Year Booked PnL: '+ '{} ({}%)'.format(format_amt(cy_booked_amt), cy_booked_percentage))
  print('Prev Year Booked PnL: '+ '{} ({}%)'.format(format_amt(py_booked_amt), py_booked_percentage))
  print('===================')
  print('Est FTT: ',  format_amt(estimate_st))
  print('Est FTT PnL: '+ '{} ({}%)'.format(format_amt(est_st_pnl_amount), est_st_pnl_percentage))

  print('===================')
  print('Deployed: ', format_amt(investment))

  print('Current: ', format_amt(current))

  print('CAGR/XIRR %: '+'{}%'.format(cagr))

In [8]:
# get start and end date
start_date, end_date = get_start_end_date()

# get portfolio and prospects data
mypfs_df = get_mypfs_df()
mypps_df = get_mypps_df()
myinvmt_df = get_myinvmt_df()

# merge above datasets
mypf_df = pd.merge(mypfs_df, mypps_df, on="Symbol")

# seggregate dm and sv portfolio
dm_pf = mypf_df[mypf_df['InPortfolio'] == 'DM']
sv_pf = mypf_df[mypf_df['InPortfolio'] == 'SV']

# build portfolio stock dataframe
dm_stocks = get_stock_ids(dm_pf)
sv_stocks = get_stock_ids(sv_pf)
df_stocks = pd.concat([dm_pf,sv_pf], ignore_index = True)

# arrange common and diff stock features
common_cols = ['Symbol', 'Target', 'Criteria', 'Strategy', 'CumlRnk', 'LatestQtr', 'StarStock', 'Conviction', 'Category', 'InFolio', 'XIRR', 'MBQ']
diff_cols = ['Symbol', 'AvgCost', 'Shares']
df_stocks = arrange_features(df_stocks, common_cols, diff_cols)

# get common features
stock_ids = df_stocks['Symbol'].values
df_common_features = get_common_features(stock_ids, df_stocks)

df_common_features.reset_index(drop=True, inplace=True)
df_common_features.drop(['Date'], axis=1, inplace=True)
# get and print portfolio features
df_portfolio_features = get_portfolio_features(df_common_features)

print_portfolio_stats(df_portfolio_features, myinvmt_df)

df = df_portfolio_features
#plot_pie_chart(df, 'CapType', 'Current')
list_ox40n = list(df[df['MBQ'].str.contains('OX40N', na=False)]['Symbol'].values)

Run date time (IST): 2026-08-21 11:28:30
-------------------
qualified stocks: 87
with latest results: 30
still star stocks: 19

-------------------
Initial Investment:  1.46 C
CY Investment:  1.89 C
Reserve:  3.69 L
Current:  1.58 C
-------------------
Today PnL: -23.68 K (-0.15%)
Current PnL: -35.00 L (-18.53%)
CY Booked + Current PnL: -29.94 L (-15.85%)
-------------------
Total profit:  3.46 L
Total loss:  -38.47 L
-------------------
Total Booked + Current PnL: 12.93 L (8.85%)
Total Booked PnL: 47.93 L (32.82%)
Curr Year Booked PnL: 5.06 L (3.2%)
Prev Year Booked PnL: 42.87 L (29.35%)
===================
Est FTT:  2.67 C
Est FTT PnL: 1.09 C (69.11%)
===================
Deployed:  1.46 C
Current:  1.58 C
CAGR/XIRR %: 3.54%

In [9]:
# top 5 near their targets
cols = ['Symbol', 'Today P/L%', 'Current P/L%', 'FTT%', 'OTT%', 'FTT Amt', 'Current P/L', 'Current', 'FTT', 'Dev%_PE', 'RSI_14','Conviction', 'Spread%',  'CumlRnk', 'RRR Ind', 'CurrAlloc%', 'Gained%', 'Criteria', 'Strategy', 'Category']
df_tmp = df_portfolio_features[~df_portfolio_features['Symbol'].isin(['ENRIN','BLUSPRING','DIGITIDE'])]
df_tmp = df_tmp.sort_values(by = 'FTT Amt', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
66,SIEMENS,0.51,4.78,5.78,10.83,11270.0,8890.0,194985.0,4125.00,-15.10,57.0,H-LC,14.27,51.0,0.79,1.26,37.57,AR,NTT,ELECTRICAL
78,UNITDSPR,1.22,13.32,6.57,20.77,17432.0,31183.0,265327.0,1644.00,-3.33,64.0,X-MC,11.37,64.0,1.79,1.72,27.54,X40N,NTT,BREWERIES
77,TTKPRESTIG,0.44,-23.60,31.02,0.09,23882.0,-23788.0,76989.0,770.00,-6.90,40.0,M-SC,9.40,250.0,-1.00,0.50,38.57,OX40N,NTT,DURABLES
52,M&M,0.05,8.20,9.82,18.82,25573.0,19733.0,260414.0,3762.88,-6.55,59.0,X-LC,5.03,25.0,0.77,1.69,18.13,X40N,ATH,AUTO
67,SIS,1.39,-3.78,26.03,21.26,27808.0,-4200.0,106832.0,528.00,105.28,43.0,H-SC,20.45,168.0,-0.15,0.69,58.84,OX40N,NTT,MISC

In [10]:
# top 5 today
df_tmp = df_portfolio_features.sort_values(by = 'Today P/L%', ascending=False)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
69,SURYODAY,3.89,-10.21,37.03,23.03,59538.0,-18288.0,160783.0,216.00,-26.71,42.0,H-SC,15.28,166.0,-0.31,1.04,36.48,XR,NTT,BANKS
31,HATHWAY,3.45,-40.45,191.01,73.29,123660.0,-43980.0,64740.0,31.40,NaN,49.0,NaN,2.73,171.0,-0.36,0.42,21.65,XR,NTT,ENTERTAINMENT
21,DEN,2.81,-46.68,166.43,42.07,74960.0,-39424.0,45040.0,75.00,NaN,54.0,NaN,5.45,235.0,-0.53,0.29,22.50,AR,NTT,ENTERTAINMENT
40,ICICIPRULI,2.76,-15.06,53.37,30.28,89307.0,-29669.0,167336.0,787.27,-45.52,56.0,X-MC,12.17,78.0,-0.33,1.08,11.49,X40,ATH,INSURANCE
14,CAMPUS,2.65,-22.33,71.60,33.28,93303.0,-37463.0,130312.0,393.00,NaN,58.0,NaN,10.31,218.0,-0.40,0.84,6.58,XY24,NTT,FOOTWEAR

In [11]:
# bottom 5 today
df_tmp = df_portfolio_features.sort_values(by = 'Today P/L%', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
51,LAOPALA,-4.19,-47.66,165.74,39.09,113734.0,-62483.0,68622.0,464.00,NaN,38.0,NaN,3.82,154.0,-0.55,0.44,9.39,AR,NTT,CERAMICS
0,5PAISA,-4.17,-25.99,52.56,12.90,84989.0,-56797.0,161699.0,593.00,3.70,57.0,H-SC,11.87,170.0,-0.67,1.05,56.04,OX40N,NTT,FINANCE
27,GLAXO,-3.77,17.14,15.83,35.69,36955.0,34164.0,233448.0,3380.16,-12.14,71.0,X-MC,10.66,56.0,0.92,1.51,38.75,X40,ATH,PHARMA
57,RAJESHEXPO,-2.53,-84.76,556.53,0.07,116359.0,-116269.0,20908.0,518.00,NaN,33.0,NaN,36.58,268.0,-1.00,0.14,3.26,OX40N,NTT,JEWELLERY
11,BERGEPAINT,-2.30,-3.51,29.87,25.32,74290.0,-9039.0,248710.0,680.00,-16.10,49.0,X-MC,5.79,68.0,-0.12,1.61,30.42,XY24,NTT,PAINTS

In [12]:
# top 5 to exit based on CumlRnk
df_tmp = df_portfolio_features[~df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])]
df_tmp = df_tmp[(df_tmp['Current P/L%'] > -1) & (df_tmp['Current P/L%'] < 1)].sort_values(by = 'CumlRnk', ascending=False)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
79,UTIAMC,0.68,-0.99,52.66,51.15,115922.0,-2198.0,220132.0,1371.68,25.0,45.0,M-SC,7.58,229.0,-0.02,1.43,3.11,XY24,ATH,FINANCE

In [13]:
# OX40N stocks to exit
df_tmp = df_portfolio_features[(df_portfolio_features['Symbol'].isin(list_ox40n))].sort_values(by = 'Current P/L%', ascending=False)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
25,FINCABLES,-1.63,60.88,29.24,107.91,69453.0,89883.0,237527.0,1641.55,17.33,66.0,M-SC,22.69,220.0,1.29,1.54,78.70,OX40N,ATH,CABLES
67,SIS,1.39,-3.78,26.03,21.26,27808.0,-4200.0,106832.0,528.00,105.28,43.0,H-SC,20.45,168.0,-0.15,0.69,58.84,OX40N,NTT,MISC
43,INDIGOPNTS,-0.76,-19.01,23.50,0.02,33222.0,-33187.0,141372.0,1408.00,-22.73,61.0,M-SC,7.48,222.0,-1.00,0.92,60.40,OX40N,NTT,PAINTS
16,CERA,0.45,-23.05,61.00,23.89,82567.0,-40548.0,135355.0,9475.00,NaN,44.0,NaN,12.98,153.0,-0.49,0.88,31.58,OX40N,NTT,CERAMICS
12,BOSCH-HCIL,-1.35,-23.41,30.55,-0.01,29905.0,-29917.0,97888.0,2282.00,766.12,74.0,M-SC,10.39,231.0,-1.00,0.63,66.62,OX40N,BTT,AC

In [14]:
# top 5 to book for rotation
df_tmp = df_portfolio_features[(df_portfolio_features['Current P/L%'] > 20) ].sort_values(by = 'CumlRnk', ascending=False)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
25,FINCABLES,-1.63,60.88,29.24,107.91,69453.0,89883.0,237527.0,1641.55,17.33,66.0,M-SC,22.69,220.0,1.29,1.54,78.7,OX40N,ATH,CABLES

In [15]:
# top 5 to monitor for exit
df_tmp = df_portfolio_features[~df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])]
df_tmp = df_tmp[(df_tmp['Current P/L%'] > 0) ].sort_values(by = 'Dev%_PE', ascending=False)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
25,FINCABLES,-1.63,60.88,29.24,107.91,69453.0,89883.0,237527.0,1641.55,17.33,66.0,M-SC,22.69,220.0,1.29,1.54,78.70,OX40N,ATH,CABLES
68,STARHEALTH,-1.72,10.84,32.86,47.26,102393.0,30480.0,311603.0,761.00,-2.33,43.0,H-SC,15.99,173.0,0.30,2.02,34.73,XY24,NTT,INSURANCE

In [16]:
# top 5 to book for rotation from weak conviction
df_tmp = df_portfolio_features[~df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])]
df_tmp = df_tmp[~df_tmp['Criteria'].isin(['XY25','XY24','X40', 'X40N'])].sort_values(by = 'RRR Ind', ascending=False)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
25,FINCABLES,-1.63,60.88,29.24,107.91,69453.0,89883.0,237527.0,1641.55,17.33,66.0,M-SC,22.69,220.0,1.29,1.54,78.70,OX40N,ATH,CABLES
67,SIS,1.39,-3.78,26.03,21.26,27808.0,-4200.0,106832.0,528.00,105.28,43.0,H-SC,20.45,168.0,-0.15,0.69,58.84,OX40N,NTT,MISC
3,ALKYLAMINE,-1.27,-17.75,134.10,92.54,111359.0,-17921.0,83042.0,4520.85,NaN,56.0,NaN,14.95,142.0,-0.16,0.54,57.69,SR,ATH,CHEMICALS
42,INDIAMART,0.61,-25.02,167.96,100.92,155329.0,-30856.0,92480.0,4675.60,NaN,37.0,NaN,13.69,140.0,-0.20,0.60,0.61,AR,ATH,MISC
71,TANLA,0.36,-35.03,234.40,117.25,412319.0,-94857.0,175904.0,1922.32,NaN,47.0,NaN,15.15,147.0,-0.23,1.14,54.01,AR,ATH,IT

In [17]:
# top 5 to accumulate based on lowest RSI_14
df_tmp = df_portfolio_features[df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])].sort_values(by = 'RSI_14', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
56,PGHH,-0.21,-38.39,114.28,32.01,150328.0,-81976.0,131544.0,17616.87,-54.65,27.0,X-SC,19.42,57.0,-0.55,0.85,0.00,X40,ATH,FMCG
55,PAGEIND,0.89,-7.26,43.26,32.85,107668.0,-19494.0,248885.0,50936.08,-31.08,31.0,X-MC,8.57,55.0,-0.18,1.61,18.85,X40,ATH,APPARELS
20,DABUR,-0.14,-21.90,84.00,43.70,162736.0,-54335.0,193733.0,735.00,-32.67,32.0,X-MC,10.51,70.0,-0.33,1.26,0.00,XY24,BTT,FMCG
1,ABBOTINDIA,-0.65,-12.95,32.53,15.37,50649.0,-23155.0,155700.0,34390.26,-29.03,32.0,X-MC,3.07,58.0,-0.46,1.01,5.47,X40,ATH,PHARMA
19,COLPAL,-1.16,-28.32,95.12,39.86,179568.0,-74585.0,188780.0,3683.41,-13.17,32.0,X-MC,2.30,62.0,-0.42,1.22,6.78,XY25,ATH,FMCG

In [18]:
# top 5 to accumulate based on Spread and CumlRnk
df_tmp = df_portfolio_features[df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])]
df_tmp = df_tmp[(df_tmp['CumlRnk'] < 100)].sort_values(by = 'Spread%', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
50,KOTAKBANK,1.31,5.80,12.40,18.92,31447.0,13904.0,253606.0,452.46,-10.58,62.0,X-LC,2.03,12.0,0.44,1.64,14.10,X40,ATH,BANKS
19,COLPAL,-1.16,-28.32,95.12,39.86,179568.0,-74585.0,188780.0,3683.41,-13.17,32.0,X-MC,2.30,62.0,-0.42,1.22,6.78,XY25,ATH,FMCG
23,DMART,-1.64,-4.94,38.24,31.42,113343.0,-15390.0,296400.0,5391.45,-20.25,40.0,X-LC,2.33,14.0,-0.14,1.92,6.96,X40N,ATH,FMCG
1,ABBOTINDIA,-0.65,-12.95,32.53,15.37,50649.0,-23155.0,155700.0,34390.26,-29.03,32.0,X-MC,3.07,58.0,-0.46,1.01,5.47,X40,ATH,PHARMA
26,GILLETTE,0.36,-11.00,45.76,29.72,103399.0,-27936.0,225960.0,10978.86,-35.84,39.0,X-SC,3.74,83.0,-0.27,1.46,3.84,X40,ATH,FMCG

In [19]:
# top 5 to accumulate based on lowest Gained%
df_tmp = df_portfolio_features[df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])].sort_values(by = 'Gained%', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
20,DABUR,-0.14,-21.90,84.00,43.70,162736.0,-54335.0,193733.0,735.00,-32.67,32.0,X-MC,10.51,70.0,-0.33,1.26,0.00,XY24,BTT,FMCG
36,HINDUNILVR,-0.40,-16.27,45.19,21.56,127329.0,-54753.0,281764.0,2922.00,-42.35,36.0,X-LC,6.65,9.0,-0.43,1.83,0.00,XY25,NTT,FMCG
56,PGHH,-0.21,-38.39,114.28,32.01,150328.0,-81976.0,131544.0,17616.87,-54.65,27.0,X-SC,19.42,57.0,-0.55,0.85,0.00,X40,ATH,FMCG
83,VOLTAS,0.51,-4.11,51.42,45.20,94538.0,-7887.0,183855.0,1856.00,32.05,36.0,X-MC,5.17,79.0,-0.08,1.19,0.77,XY25,NTT,AC
47,ITC,-0.70,-25.58,67.56,24.70,199738.0,-101632.0,295646.0,452.00,-30.75,36.0,X-LC,10.48,1.0,-0.51,1.92,1.01,X40,NTT,FMCG

In [20]:
# top 5 to accumulate based on lowest CurrAlloc%
df_tmp = df_portfolio_features[df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])].sort_values(by = 'CurrAlloc%', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
56,PGHH,-0.21,-38.39,114.28,32.01,150328.0,-81976.0,131544.0,17616.87,-54.65,27.0,X-SC,19.42,57.0,-0.55,0.85,0.00,X40,ATH,FMCG
1,ABBOTINDIA,-0.65,-12.95,32.53,15.37,50649.0,-23155.0,155700.0,34390.26,-29.03,32.0,X-MC,3.07,58.0,-0.46,1.01,5.47,X40,ATH,PHARMA
2,ACC,1.38,-41.53,198.97,74.81,311945.0,-111348.0,156780.0,3906.00,-41.79,40.0,X-SC,11.59,85.0,-0.36,1.02,4.74,XY24,BTT,CEMENT
40,ICICIPRULI,2.76,-15.06,53.37,30.28,89307.0,-29669.0,167336.0,787.27,-45.52,56.0,X-MC,12.17,78.0,-0.33,1.08,11.49,X40,ATH,INSURANCE
39,ICICIGI,0.54,-13.95,38.16,18.89,65710.0,-27912.0,172197.0,2244.41,-14.33,42.0,X-MC,10.13,66.0,-0.42,1.12,2.59,X40,ATH,INSURANCE

In [21]:
# top 5 to accumulate based on CumlRnk
df_tmp = df_portfolio_features.sort_values(by = 'CumlRnk', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
47,ITC,-0.70,-25.58,67.56,24.70,199738.0,-101632.0,295646.0,452.00,-30.75,36.0,X-LC,10.48,1.0,-0.51,1.92,1.01,X40,NTT,FMCG
73,TCS,0.03,-32.52,84.05,24.20,262760.0,-150650.0,312623.0,4230.71,-43.98,48.0,X-LC,13.66,2.0,-0.57,2.03,16.58,X40,ATH,IT
45,INFY,0.07,-19.50,74.39,40.38,225442.0,-73416.0,303054.0,1972.00,-40.86,49.0,X-LC,15.60,3.0,-0.33,1.96,14.77,X40,NTT,IT
75,TMPV,-0.31,-24.04,87.94,42.75,277941.0,-100049.0,316058.0,600.00,-84.91,34.0,X-LC,4.38,4.0,-0.36,2.05,8.68,XY24,NTT,AUTO
33,HCLTECH,-0.73,-12.04,40.93,23.97,111422.0,-37260.0,272226.0,1853.42,-14.26,53.0,X-LC,10.70,8.0,-0.33,1.76,28.46,X40,ATH,IT

In [22]:
# top 5 for average up
df_tmp = df_portfolio_features[(df_portfolio_features['Dev%_200'] > 5)].sort_values(by = 'CurrAlloc%', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
44,INDUSINDBK,-0.50,-25.95,79.46,32.89,45428.0,-20036.0,57171.0,1800.00,320.94,48.0,L-MC,12.18,258.0,-0.44,0.37,40.95,XR,NTT,BANKS
3,ALKYLAMINE,-1.27,-17.75,134.10,92.54,111359.0,-17921.0,83042.0,4520.85,NaN,56.0,NaN,14.95,142.0,-0.16,0.54,57.69,SR,ATH,CHEMICALS
12,BOSCH-HCIL,-1.35,-23.41,30.55,-0.01,29905.0,-29917.0,97888.0,2282.00,766.12,74.0,M-SC,10.39,231.0,-1.00,0.63,66.62,OX40N,BTT,AC
81,VALIANTORG,-2.04,-35.56,170.24,74.15,179491.0,-58171.0,105434.0,838.00,NaN,57.0,NaN,8.81,145.0,-0.32,0.68,56.90,XR,NTT,CHEMICALS
67,SIS,1.39,-3.78,26.03,21.26,27808.0,-4200.0,106832.0,528.00,105.28,43.0,H-SC,20.45,168.0,-0.15,0.69,58.84,OX40N,NTT,MISC

In [23]:
# top 5 RSP
df_tmp = df_portfolio_features.sort_values(by = 'RSP', ascending=False)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
12,BOSCH-HCIL,-1.35,-23.41,30.55,-0.01,29905.0,-29917.0,97888.0,2282.00,766.12,74.0,M-SC,10.39,231.0,-1.00,0.63,66.62,OX40N,BTT,AC
25,FINCABLES,-1.63,60.88,29.24,107.91,69453.0,89883.0,237527.0,1641.55,17.33,66.0,M-SC,22.69,220.0,1.29,1.54,78.70,OX40N,ATH,CABLES
27,GLAXO,-3.77,17.14,15.83,35.69,36955.0,34164.0,233448.0,3380.16,-12.14,71.0,X-MC,10.66,56.0,0.92,1.51,38.75,X40,ATH,PHARMA
81,VALIANTORG,-2.04,-35.56,170.24,74.15,179491.0,-58171.0,105434.0,838.00,NaN,57.0,NaN,8.81,145.0,-0.32,0.68,56.90,XR,NTT,CHEMICALS
38,HYUNDAI,2.46,15.25,24.89,43.94,72095.0,38321.0,289653.0,2782.73,19.49,67.0,X-LC,5.69,29.0,0.53,1.88,32.99,X40N,ATH,AUTO

In [24]:
# Top N allocation
df_tmp = df_portfolio_features.sort_values(by = 'CurrAlloc%', ascending=False)
top_n_values = [10, 25, 50]

sum_df = pd.DataFrame({
    'Top_N': top_n_values,
    'Sum_Alloc%': [df_tmp['CurrAlloc%'].head(n).sum() for n in top_n_values]
})

sum_df

   Top_N  Sum_Alloc%
0     10       19.67
1     25       45.01
2     50       77.60

In [25]:
# market-cap-wise allocation
df_tmp = df_portfolio_features[cols]
df_tmp.groupby(df_tmp['Conviction'].str[-2:])['CurrAlloc%'].sum().sort_values(ascending=False)

Conviction
LC    38.10
MC    22.14
SC    21.59
Name: CurrAlloc%, dtype: float64

In [26]:
# criteria-wise allocation
df_portfolio_features.groupby('Criteria')['CurrAlloc%'].sum().sort_values(ascending=False)

Criteria
X40      26.71
XY24     24.00
X40N     18.69
XR        9.16
OX40N     7.32
XY25      7.15
AR        6.09
SR        0.87
Name: CurrAlloc%, dtype: float64

In [27]:
# conviction-wise allocation
df_portfolio_features.groupby('Conviction')['CurrAlloc%'].sum().sort_values(ascending=False)

Conviction
X-LC    34.43
X-MC    19.58
H-SC     8.56
X-SC     7.62
M-SC     5.41
H-LC     2.85
M-MC     1.17
H-MC     1.02
M-LC     0.82
L-MC     0.37
Name: CurrAlloc%, dtype: float64

In [28]:
# sector-wise stats
df_tmp = df_portfolio_features.groupby('Category')[['CurrAlloc%', 'Current', 'Current P/L', 'FTT Amt']].sum().sort_values(by=['Current', 'Current P/L'], ascending=False)
df_tmp['Current P/L%'] = round(df_tmp['Current P/L'] * 100 / df_tmp['Current'], 2)
df_tmp['FTT%'] = round(df_tmp['FTT Amt'] * 100 / df_tmp['Current'], 2)
cols = ['CurrAlloc%', 'Current P/L%', 'FTT%']
df_tmp[cols].sort_values(by=['CurrAlloc%'], ascending=False)

               CurrAlloc%  Current P/L%    FTT%
Category
FMCG                15.34        -25.99   71.28
IT                  11.24        -37.52  105.73
FINANCE             10.78        -16.21   66.27
AUTO                 8.29         -5.81   43.70
BANKS                6.29        -10.06   57.52
MISC                 5.95        -34.41   88.48
PHARMA               5.81          7.57   18.65
INSURANCE            5.74         -4.81   41.86
PAINTS               5.44        -17.44   37.47
ELECTRICAL           4.17         -9.79   44.17
AC                   1.82        -13.42   44.17
REFINERIES           1.74        -11.35   48.76
BREWERIES            1.72         11.75    6.57
FOOTWEAR             1.68        -70.09  138.28
APPARELS             1.61         -7.83   43.26
CABLES               1.54         37.84   29.24
DURABLES             1.48        -69.63  110.90
TRAVEL               1.41       -104.84  207.40
CERAMICS             1.32        -50.51   96.24
ENGINEERING          1.26        -24.87   81.98
CHEMICALS            1.22        -40.37  154.32
CEMENT               1.02        -71.02  198.97
JEWELLERY            0.97       -115.52  190.40
ENTERTAINMENT        0.71        -75.97  180.93
HEALTHCARE           0.69        -69.85  112.49
TEXTILES             0.39        -51.89   95.20
HOTELS               0.36       -103.93  175.86

In [29]:
# money to be made criteria-wise
df_portfolio_features.groupby('Criteria')['FTT Amt'].agg(['sum', 'count']).sort_values(by='sum', ascending=False)

                sum  count
Criteria
XY24      3626088.0     19
X40       2099871.0     18
XR        1384681.0     13
X40N      1196634.0     12
AR        1066620.0      8
OX40N      663018.0     10
XY25       597155.0      5
SR         282002.0      2

In [30]:
# money to be made conviction-wise
df_portfolio_features.groupby('Conviction')['FTT Amt'].agg(['sum', 'count']).sort_values(by='sum', ascending=False)

                  sum  count
Conviction
X-LC        2416192.0     19
X-MC        1479368.0     14
X-SC        1102076.0      6
H-SC         831139.0      8
M-SC         330206.0      6
H-MC         255910.0      1
M-LC         166119.0      1
M-MC          65195.0      1
H-LC          50270.0      2
L-MC          45428.0      1

In [31]:
# money to be made criteria and conviction-wise
df_portfolio_features.groupby(['Conviction', 'Criteria'])['FTT Amt'].agg(['sum', 'count']).sort_values(by='sum', ascending=False)

                           sum  count
Conviction Criteria
X-LC       X40       1216055.0      9
X-SC       XY24       675195.0      2
H-SC       XY24       525866.0      3
X-MC       X40        514847.0      6
X-LC       XY24       461124.0      2
X-MC       X40N       453389.0      4
X-LC       X40N       419608.0      5
X-MC       XY25       274106.0      2
X-LC       XY25       257854.0      2
H-MC       XY24       255910.0      1
X-SC       X40        253727.0      2
X-MC       XY24       237026.0      2
H-SC       OX40N      217107.0      3
X-SC       X40N       173154.0      2
M-LC       XR         166119.0      1
M-SC       OX40N      156462.0      4
           XY24       115922.0      1
H-SC       XR          88166.0      2
M-MC       XY25        65195.0      1
X-LC       XR          61551.0      1
M-SC       XR          57822.0      1
H-LC       AR          50270.0      2
L-MC       XR          45428.0      1

In [32]:
# notebook execution time

end_time = time.time()
execution_time = round(end_time - start_time, 0)
print(f"Notebook execution time: {execution_time} seconds")

Notebook execution time: 37.0 seconds