<a href="https://colab.research.google.com/github/ankit-rathi/Quantvesting_v2/blob/main/myStocks_Portfolio_Analysis.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
'''
!pip install pandas==2.2.2 -qq
!pip install pyxirr -qq
!pip install ta -qq
!pip install yfinance==0.2.59 -qq
'''

'\n!pip install pandas==2.2.2 -qq\n!pip install pyxirr -qq\n!pip install ta -qq\n!pip install yfinance==0.2.59 -qq\n'

In [2]:
# import libraries

import numpy as np
import pandas as pd
import datetime
import warnings
warnings.filterwarnings('ignore')
import yfinance as yfin
import ta
import matplotlib.pyplot as plt
import requests

In [3]:
# notebook start time
import time
import datetime
import pytz

start_time = time.time()

# function to print date timestamp
def print_date_time():
  tz_NY = pytz.timezone('Asia/Kolkata')
  datetime_NY = datetime.datetime.now(tz_NY)
  print("Run date time (IST):", datetime_NY.strftime("%Y-%m-%d %H:%M:%S"))

In [4]:
# function to get booked and reserved amount
def get_amt():
  # fetch the JSON data from the URL
  url = "https://raw.githubusercontent.com/ankit-rathi/Tradevesting_v1/main/data/myPortfolioAmts.json"
  response = requests.get(url)
  pf_amts = response.json()  # parse the JSON data

  # extract values from the JSON
  py_booked_amt_dm = pf_amts["py_booked_amt_dm"]
  py_booked_amt_sv = pf_amts["py_booked_amt_sv"]
  cy_booked_amt_dm = pf_amts["cy_booked_amt_dm"]
  cy_booked_amt_sv = pf_amts["cy_booked_amt_sv"]
  reserve_amt_dm = pf_amts["reserve_amt_dm"]
  reserve_amt_sv = pf_amts["reserve_amt_sv"]

  # perform calculations
  py_booked_amt = py_booked_amt_dm + py_booked_amt_sv
  cy_booked_amt = cy_booked_amt_dm + cy_booked_amt_sv
  reserve_amt = reserve_amt_dm + reserve_amt_sv
  total_booked_amt = py_booked_amt + cy_booked_amt

  return total_booked_amt, reserve_amt, cy_booked_amt, py_booked_amt

gen_output = 0

In [5]:
# function to format the amount
def format_amt(number):
    abs_number = abs(number)

    if abs_number >= 1_00_00_000:  # Crores
        formatted_amt = f"{number / 1_00_00_000:.2f} C"
    elif abs_number >= 1_00_000:  # Lakhs
        formatted_amt = f"{number / 1_00_000:.2f} L"
    elif abs_number >= 1_000:  # Thousands
        formatted_amt = f"{number / 1_000:.2f} K"
    else:
        formatted_amt = f"{number:.2f}"

    return formatted_amt

# function to set start and end date
def get_start_end_date():
  start_date = (datetime.date.today() + datetime.timedelta(days=-365)).strftime('%Y-%m-%d')
  end_date = (datetime.date.today() + datetime.timedelta(days=1)).strftime('%Y-%m-%d')
  return start_date, end_date

# function to fetch my portfolio csv
def get_mypfs_df():
  mypfs_df = pd.read_csv('https://raw.githubusercontent.com/ankit-rathi/Tradevesting_v1/main/data/myPortfolioStocks.csv')
  return mypfs_df

# function to fetch my prospects csv
def get_mypps_df():
  mypps_df = pd.read_csv('https://raw.githubusercontent.com/ankit-rathi/Tradevesting_v1/main/data/myProspectsScrips.csv')
  return mypps_df

# function to fetch screener data
def get_myscreen_df():
  myscreen_df = pd.read_csv('https://raw.githubusercontent.com/ankit-rathi/Tradevesting_v1/main/data/myScreenerDB.csv')
  return myscreen_df

# function to fetch momentum data
def get_myinvmt_df():
  myinvmt_df = pd.read_csv('https://raw.githubusercontent.com/ankit-rathi/Tradevesting_v1/main/data/myInvestments.csv')
  return myinvmt_df

# function to get the stock ids
def get_stock_ids(df_pf):
  stock_n100 = df_pf['Symbol'].unique()

  exclude = ['CADILAHC','MMTC', 'MASFIN']

  stock_ids = df_pf[~df_pf['Symbol'].isin(exclude) ]['Symbol'].unique()

  #mypf = mypf[mypf.Forecast.notnull()]
  #stock_ids = mypf['Symbol'].unique()

  #stock_ids.sort()
  return stock_ids

# get features from screener data
def get_screener_features():
  myscreen_df = get_myscreen_df()
  cols = ['Symbol', 'EPS', 'MedPE', 'ROCE%', 'ROE%', 'CapType']
  return myscreen_df[cols]

# get relative strength
def get_relative_strength(stock_list):

    # Dictionary to store stock tickers and their corresponding percentage price change
    stock_changes = {}

    # Loop through each stock and fetch its price data
    for stock in stock_list:
        try:
            # Download the stock data for the given date range
            stock_data = yfin.Ticker(stock + '.NS').history(period='1mo', interval='1d')[map(str.title, ['open', 'close', 'low', 'high', 'volume'])]

            # Calculate the percentage change for the stock
            if len(stock_data) > 0:
                start_price = stock_data['Close'].iloc[0]
                end_price = stock_data['Close'].iloc[-1]
                percent_change = round(((end_price - start_price) / start_price) * 100, 2)
                stock_changes[stock] = percent_change
            else:
                stock_changes[stock] = np.nan  # If no data is available, set to NaN

        except Exception as e:
            print(f"Error fetching data for {stock}: {e}")
            stock_changes[stock] = np.nan

    # Create a DataFrame with stock tickers and their percentage changes
    df = pd.DataFrame(list(stock_changes.items()), columns=['Symbol', 'Percent_Change'])

    # Drop any stocks with missing data (NaN values)
    df = df.dropna()

    # Calculate the percentile rank based on percentage change
    df['RSP'] = round(df['Percent_Change'].rank(pct=True) * 100, 2)
    cols = ['Symbol', 'RSP']
    df = df[cols]
    # Sort by percentile rank (optional)
    df = df.sort_values(by='RSP', ascending=False).reset_index(drop=True)

    return df

In [6]:
# function to get stock technicals
def stock_prec_dev(stock_symbol):
    #stock_symbol = 'ULTRACEMCO.NS'
    short_window = 20
    mid_window = 50
    long_window = 200
    moving_avg = 'SMA'

    start = datetime.datetime(*map(int, start_date.split('-')))
    end = datetime.datetime(*map(int, end_date.split('-')))

    stock_df = yfin.Ticker(stock_symbol + '.NS').history(period='max', interval='1d')[map(str.title, ['open', 'close', 'low', 'high', 'volume'])]

    stock_df['Max'] = round(max(stock_df['Close']),2)
    stock_df = stock_df[(stock_df.index <= end_date) & (stock_df.index >= start_date)]
    stock_df['200_SMA'] = round(stock_df['Close'].rolling(window = 200, min_periods = 1).mean(),0)
    stock_df['Dev%_200'] = round((stock_df['Close'] - stock_df['200_SMA'])*100/stock_df['200_SMA'],2)
    stock_df.dropna(axis = 0, inplace = True) # remove any null rows

    stock_df['20_SMA'] = stock_df['Close'].rolling(window=20).mean()
    stock_df['50_SMA'] = stock_df['Close'].rolling(window=50).mean()
    stock_df['Symbol'] = stock_symbol

    stock_df['Close'] = round(stock_df['Close'],2)
    stock_df['Min'] = round(min(stock_df['Close']),2)
    stock_df['RSI_14'] = ta.momentum.RSIIndicator(close=stock_df['Close'], window=14).rsi()
    stock_df['RSI_14'] = round(stock_df['RSI_14'],0)
    stock_df['Prev_Close'] = stock_df['Close'].shift(1)
    stock_df.drop(['Open', 'Low', 'High', 'Volume'], axis=1, inplace=True)
    stock_df = stock_df.tail(1)

    max_SMA = max(stock_df['20_SMA'].item(), stock_df['50_SMA'].item(), stock_df['200_SMA'].item())
    min_SMA = min(stock_df['20_SMA'].item(), stock_df['50_SMA'].item(), stock_df['200_SMA'].item())
    ABS_Spread = max_SMA - min_SMA
    stock_df['Spread%'] = round((ABS_Spread / stock_df['200_SMA'].item()) * 100,2)

    return stock_df

# function to compute stock attributes
def get_common_features(stock_ids, df_mypf):

  df_prec_dev = pd.DataFrame()
  df_tmp = get_screener_features()
  df_rs = get_relative_strength(stock_ids)

  for stock_id in stock_ids:
      tmp = stock_prec_dev(stock_id)
      tmp = tmp.reset_index()
      df_prec_dev = pd.concat([df_prec_dev, tmp], ignore_index = True)
  df_prec_dev = pd.merge(df_prec_dev, df_mypf, on= 'Symbol')
  df_prec_dev = pd.merge(df_prec_dev, df_tmp, on= 'Symbol', how='left')
  df_prec_dev = pd.merge(df_prec_dev, df_rs, on= 'Symbol', how='left')
  #print(df_prec_dev.columns)
  df_prec_dev['Curr_PE'] = round(df_prec_dev['Close']/df_prec_dev['EPS'],1)
  df_prec_dev['Dev%_PE'] = round((df_prec_dev['Curr_PE'] - df_prec_dev['MedPE'])*100/df_prec_dev['MedPE'],2)
  df_prec_dev['Conviction'] = df_prec_dev['Conviction'] + '-' + df_prec_dev['CapType']
  return df_prec_dev

# function to arrange stock features
def arrange_features(df_stocks, common_cols, diff_cols):
  df_stocks_common = df_stocks[common_cols].drop_duplicates()
  df_stocks_diff = df_stocks[diff_cols]
  df_stocks_diff['Investment'] = df_stocks_diff['AvgCost'] * df_stocks_diff['Shares']
  df_stocks_diff = df_stocks_diff.groupby(['Symbol'])[['Shares', 'Investment']].aggregate(['sum']).reset_index()
  df_stocks_diff.columns = ['Symbol', 'Shares', 'Investment']
  df_stocks_diff['AvgCost'] = round(df_stocks_diff['Investment']/df_stocks_diff['Shares'],2)
  df_stocks = pd.merge(df_stocks_diff, df_stocks_common, on='Symbol')
  return df_stocks

# plot fact distribution across dimension
def plot_pie_chart(df, dimension, fact):
  # grouping the data by category and calculating the sum of fact for each type
  grouped_data = df.groupby(dimension)[fact].sum()

  # sorting the grouped data in descending order
  grouped_data = grouped_data.sort_values(ascending=False)

  # creating a pie chart
  grouped_data.plot.pie(autopct='%1.1f%%', startangle=90, figsize=(6, 6))

  # adding a title and displaying the plot
  plt.title(f'{dimension} {fact} Distribution')
  plt.ylabel('')  # To hide the y-label
  plt.show()

In [7]:
# function to get portfolio features

def get_portfolio_features(df_common_features):

  print_date_time()
  print('-------------------')

  #df_common_features["Target"] = df_common_features["Target"].fillna(df_common_features["Max"])
  df_common_features['NTT'] = np.where(df_common_features['Strategy']== 'NTT', df_common_features["Target"], df_common_features['Max'])
  df_common_features['LTT'] = np.where(df_common_features['Strategy']== 'BTT', df_common_features["Target"], df_common_features['Max'])
  df_common_features['BOL'] = df_common_features['Min']

  tmp_df = df_common_features[df_common_features['Symbol'].isin(mypf_df[mypf_df['InPortfolio'] != 'NA'].Symbol.values)]
  print('qualified stocks: '+str(len(tmp_df['Symbol'].unique())))
  tmp_df1 = tmp_df[tmp_df['LatestQtr'] == 1]
  print('with latest results: '+str(len(tmp_df1['Symbol'].unique())))
  tmp_df1 = tmp_df1[tmp_df1['StarStock'] == 1]
  print('still star stocks: '+str(len(tmp_df1['Symbol'].unique())))
  tmp_df['Investment'] = tmp_df['AvgCost'] * tmp_df['Shares']
  tmp_df['Current'] = round(tmp_df['Close'] * tmp_df['Shares'],0)
  tmp_df['Previous'] = tmp_df['Prev_Close'] * tmp_df['Shares']
  tmp_df['EstimatedST'] = tmp_df['NTT'] * tmp_df['Shares']
  tmp_df['EstimatedLT'] = tmp_df['LTT'] * tmp_df['Shares']
  tmp_df['Current P/L'] = round((tmp_df['Current'] - tmp_df['Investment']),0)
  tmp_df['Today P/L%'] = round((tmp_df['Current'] - tmp_df['Previous'])*100/tmp_df['Previous'],2)
  tmp_df['Current P/L%'] = round((tmp_df['Current'] - tmp_df['Investment'])*100/tmp_df['Investment'],2)
  tmp_df['EstimatedST P/L%'] = round((tmp_df['EstimatedST'] - tmp_df['Investment'])*100/tmp_df['Investment'],2)
  tmp_df['EstimatedLT P/L%'] = round((tmp_df['EstimatedLT'] - tmp_df['Investment'])*100/tmp_df['Investment'],2)
  tmp_df['NTT%'] = round((tmp_df['NTT'] - tmp_df['Close'])*100/tmp_df['Close'],2)
  tmp_df['LTT%'] = round((tmp_df['LTT'] - tmp_df['Close'])*100/tmp_df['Close'],2)
  tmp_df['Gained%'] = round((tmp_df['Close'] - tmp_df['BOL'])*100/tmp_df['BOL'],2)
  investment = round(sum(tmp_df['AvgCost']*tmp_df['Shares']),0)
  current = round(sum(tmp_df['Close']*tmp_df['Shares']),0)
  tmp_df['InitAlloc%'] = round(tmp_df['Investment']*100/investment,2)
  tmp_df['CurrAlloc%'] = round(tmp_df['Current']*100/current,2)
  tmp_df['FTT'] = tmp_df['LTT']
  tmp_df.loc[tmp_df['Strategy'] == 'NTT', 'FTT'] = tmp_df['NTT']
  tmp_df['FTT%'] = tmp_df['LTT%']
  tmp_df.loc[tmp_df['Strategy'] == 'NTT', 'FTT%'] = tmp_df['NTT%']
  tmp_df['FTT Amt'] = round(tmp_df['FTT%'] * tmp_df['Current']/100,0)
  tmp_df['OTT%'] = round((tmp_df['FTT'] - tmp_df['AvgCost'])*100/tmp_df['AvgCost'],2)
  tmp_df['RRR Ind'] = round(tmp_df['Current P/L']/tmp_df['FTT Amt'],2)
  tmp_df['Risk Ind'] = round(tmp_df['Current P/L%']*tmp_df['CurrAlloc%'],0)

  return tmp_df

# function to print portfolio features
def print_portfolio_stats(df_portfolio_features, myinvmt_df):
  from pyxirr import xirr

  total_booked_amt, reserve_amt, cy_booked_amt, py_booked_amt = get_amt()

  dates = myinvmt_df['Date'].values
  dates = np.append(dates, datetime.date.today().strftime('%d-%b-%y'))
  investment = myinvmt_df['Investment'].values
  dates= pd.to_datetime(dates)

  current = round(sum(df_portfolio_features['Close']*df_portfolio_features['Shares']),0) + reserve_amt
  investment_xirr = np.append(investment, current)
  cagr = round(xirr(pd.DataFrame({"dates": dates, "amounts": investment_xirr}))*100,2)

  investment = -sum(investment)
  invested = round(sum(df_portfolio_features['AvgCost']*df_portfolio_features['Shares']),0) + reserve_amt
  previous = round(sum(df_portfolio_features['Prev_Close']*df_portfolio_features['Shares']),0) + reserve_amt
  cy_invested = investment + py_booked_amt

  today_pnl_amount = current-previous
  today_pnl_percentage = round((current-previous)*100/previous,2)

  curr_pnl_amount = current-invested
  curr_pnl_percentage = round((curr_pnl_amount)*100/(cy_invested),2)

  cy_pnl_amount = cy_booked_amt + curr_pnl_amount
  cy_pnl_percentage = round((cy_pnl_amount)*100/cy_invested,2)

  overall_pnl_amount = total_booked_amt + curr_pnl_amount
  overall_pnl_percentage = round((overall_pnl_amount)*100/investment,2)

  estimate_st = round(sum(df_portfolio_features['FTT']*df_portfolio_features['Shares']),0)  + reserve_amt
  est_st_pnl_amount = estimate_st-current
  est_st_pnl_percentage = round((est_st_pnl_amount)*100/current,2)

  estimate_lt = round(sum(df_portfolio_features['LTT']*df_portfolio_features['Shares']),0)  + reserve_amt
  est_lt_pnl_amount = estimate_lt-current
  est_lt_pnl_percentage = round((est_lt_pnl_amount)*100/current,2)

  total_profit = round(sum(df_portfolio_features[df_portfolio_features['Current P/L%'] > 0]['Current']) - sum(df_portfolio_features[df_portfolio_features['Current P/L%'] > 0]['Investment']),0)
  total_loss = round(sum(df_portfolio_features[df_portfolio_features['Current P/L%'] < 0]['Current']) - sum(df_portfolio_features[df_portfolio_features['Current P/L%'] < 0]['Investment']),0)

  cy_booked_percentage = round((cy_booked_amt)*100/current,2)
  py_booked_percentage = round((py_booked_amt)*100/investment,2)
  total_booked_percentage = round((total_booked_amt)*100/investment,2)

  print('-------------------')
  print('Initial Investment: ', format_amt(investment))
  print('CY Investment: ', format_amt(cy_invested))
  print('Reserve: ', format_amt(reserve_amt))
  print('Current: ',  format_amt(current))
  print('-------------------')
  print('Today PnL: '+ '{} ({}%)'.format(format_amt(today_pnl_amount), today_pnl_percentage))
  print('Current PnL: '+ '{} ({}%)'.format(format_amt(curr_pnl_amount), curr_pnl_percentage))
  print('CY Booked + Current PnL: '+ '{} ({}%)'.format(format_amt(cy_pnl_amount), cy_pnl_percentage))
  print('-------------------')
  print('Total profit: ', format_amt(total_profit))
  print('Total loss: ', format_amt(total_loss))
  print('-------------------')
  print('Total Booked + Current PnL: '+ '{} ({}%)'.format(format_amt(overall_pnl_amount), overall_pnl_percentage))
  print('Total Booked PnL: '+ '{} ({}%)'.format(format_amt(total_booked_amt), total_booked_percentage))
  print('Curr Year Booked PnL: '+ '{} ({}%)'.format(format_amt(cy_booked_amt), cy_booked_percentage))
  print('Prev Year Booked PnL: '+ '{} ({}%)'.format(format_amt(py_booked_amt), py_booked_percentage))
  print('===================')
  print('Est FTT: ',  format_amt(estimate_st))
  print('Est FTT PnL: '+ '{} ({}%)'.format(format_amt(est_st_pnl_amount), est_st_pnl_percentage))

  print('===================')
  print('Deployed: ', format_amt(investment))

  print('Current: ', format_amt(current))

  print('CAGR/XIRR %: '+'{}%'.format(cagr))

In [8]:
# get start and end date
start_date, end_date = get_start_end_date()

# get portfolio and prospects data
mypfs_df = get_mypfs_df()
mypps_df = get_mypps_df()
myinvmt_df = get_myinvmt_df()

# merge above datasets
mypf_df = pd.merge(mypfs_df, mypps_df, on="Symbol")

# seggregate dm and sv portfolio
dm_pf = mypf_df[mypf_df['InPortfolio'] == 'DM']
sv_pf = mypf_df[mypf_df['InPortfolio'] == 'SV']

# build portfolio stock dataframe
dm_stocks = get_stock_ids(dm_pf)
sv_stocks = get_stock_ids(sv_pf)
df_stocks = pd.concat([dm_pf,sv_pf], ignore_index = True)

# arrange common and diff stock features
common_cols = ['Symbol', 'Target', 'Criteria', 'Strategy', 'CumlRnk', 'LatestQtr', 'StarStock', 'Conviction', 'Category', 'InFolio', 'XIRR', 'MBQ']
diff_cols = ['Symbol', 'AvgCost', 'Shares']
df_stocks = arrange_features(df_stocks, common_cols, diff_cols)

# get common features
stock_ids = df_stocks['Symbol'].values
df_common_features = get_common_features(stock_ids, df_stocks)

df_common_features.reset_index(drop=True, inplace=True)
df_common_features.drop(['Date'], axis=1, inplace=True)
# get and print portfolio features
df_portfolio_features = get_portfolio_features(df_common_features)

print_portfolio_stats(df_portfolio_features, myinvmt_df)

df = df_portfolio_features
#plot_pie_chart(df, 'CapType', 'Current')
list_ox40n = list(df[df['MBQ'].str.contains('OX40N', na=False)]['Symbol'].values)

Run date time (IST): 2026-03-12 15:31:40
-------------------
qualified stocks: 86
with latest results: 26
still star stocks: 15
-------------------
Initial Investment:  1.36 C
CY Investment:  1.62 C
Reserve:  66.25 K
Current:  1.36 C
-------------------
Today PnL: -86.62 K (-0.63%)
Current PnL: -41.15 L (-25.33%)
CY Booked + Current PnL: -25.47 L (-15.68%)
-------------------
Total profit:  1.16 L
Total loss:  -42.32 L
-------------------
Total Booked + Current PnL: 1.51 L (1.11%)
Total Booked PnL: 42.66 L (31.48%)
Curr Year Booked PnL: 15.68 L (11.55%)
Prev Year Booked PnL: 26.98 L (19.91%)
===================
Est FTT:  2.47 C
Est FTT PnL: 1.12 C (82.13%)
===================
Deployed:  1.36 C
Current:  1.36 C
CAGR/XIRR %: 0.1%

In [9]:
# top 5 near their targets
cols = ['Symbol', 'Today P/L%', 'Current P/L%', 'FTT%', 'OTT%', 'FTT Amt', 'Current P/L', 'Current', 'FTT', 'Dev%_PE', 'RSI_14','Conviction', 'Spread%',  'CumlRnk', 'RRR Ind', 'CurrAlloc%', 'Gained%', 'Criteria', 'Strategy', 'Category']
df_tmp = df_portfolio_features[~df_portfolio_features['Symbol'].isin(['ENRIN','BLUSPRING','DIGITIDE'])]
df_tmp = df_tmp.sort_values(by = 'FTT Amt', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
19,COALINDIA,5.23,15.60,1.79,17.67,3113.0,23476.0,173937.0,478.51,39.17,70.0,L-LC,12.20,185.0,7.54,1.29,35.07,XY25,ATH,MINING
77,TTKPRESTIG,8.00,-24.83,33.15,0.09,25113.0,-25020.0,75757.0,770.00,75.88,60.0,M-SC,15.24,250.0,-1.00,0.56,28.00,OX40N,NTT,DURABLES
50,MASFIN,0.21,-6.90,30.58,21.57,27894.0,-6765.0,91215.0,397.04,-19.60,39.0,H-SC,4.16,167.0,-0.24,0.68,26.54,XR,ATH,FINANCE
37,ICICIGI,-1.06,-1.72,21.43,19.34,42145.0,-3447.0,196662.0,2252.93,-17.38,41.0,X-MC,1.77,66.0,-0.08,1.46,12.16,X40,ATH,INSURANCE
78,UNITDSPR,-1.35,0.16,20.57,20.77,48241.0,378.0,234522.0,1644.00,-11.09,47.0,X-MC,1.41,64.0,0.01,1.74,6.88,X40N,NTT,BREWERIES

In [10]:
# top 5 today
df_tmp = df_portfolio_features.sort_values(by = 'Today P/L%', ascending=False)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
77,TTKPRESTIG,8.00,-24.83,33.15,0.09,25113.0,-25020.0,75757.0,770.00,75.88,60.0,M-SC,15.24,250.0,-1.00,0.56,28.00,OX40N,NTT,DURABLES
30,GREENPANEL,5.34,-45.28,161.58,43.14,161874.0,-82896.0,100182.0,537.00,124.16,45.0,M-SC,19.89,225.0,-0.51,0.74,5.34,XY24,NTT,MISC
19,COALINDIA,5.23,15.60,1.79,17.67,3113.0,23476.0,173937.0,478.51,39.17,70.0,L-LC,12.20,185.0,7.54,1.29,35.07,XY25,ATH,MINING
57,RECLTD,3.14,-7.01,29.84,20.74,56375.0,-14245.0,188925.0,446.00,1.56,47.0,M-MC,5.07,191.0,-0.25,1.40,5.89,XY25,NTT,FINANCE
1,ABB,2.05,17.59,23.79,45.57,73186.0,46013.0,307632.0,7934.00,-24.43,69.0,H-MC,10.55,125.0,0.63,2.28,36.61,AR,NTT,ELECTRICAL

In [11]:
# bottom 5 today
df_tmp = df_portfolio_features.sort_values(by = 'Today P/L%', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
69,SURYODAY,-5.76,-28.05,70.99,23.03,91468.0,-50225.0,128846.0,216.00,40.35,46.0,H-SC,7.51,166.0,-0.55,0.95,27.84,XR,NTT,BANKS
42,INDUSINDBK,-5.22,-38.62,116.52,32.89,55215.0,-29820.0,47387.0,1800.00,-323.39,30.0,L-MC,10.59,258.0,-0.54,0.35,30.50,XR,NTT,BANKS
81,VBL,-4.68,-16.97,63.40,35.67,166266.0,-53592.0,262250.0,671.64,-26.66,29.0,X-LC,5.10,13.0,-0.32,1.94,0.00,X40N,ATH,FMCG
21,COLPAL,-3.88,-24.98,88.62,41.51,175095.0,-65785.0,197580.0,3726.84,-9.21,32.0,X-MC,4.13,62.0,-0.38,1.46,0.00,XY25,ATH,FMCG
10,BAJAJHLDNG,-3.81,-12.47,47.63,29.22,79263.0,-23712.0,166413.0,14451.52,-19.11,24.0,X-LC,12.33,28.0,-0.30,1.23,0.00,X40,ATH,FINANCE

In [12]:
# top 5 to exit based on CumlRnk
df_tmp = df_portfolio_features[~df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])]
df_tmp = df_tmp[(df_tmp['Current P/L%'] > -1) & (df_tmp['Current P/L%'] < 1)].sort_values(by = 'CumlRnk', ascending=False)
df_tmp[cols].head()

Empty DataFrame
Columns: [Symbol, Today P/L%, Current P/L%, FTT%, OTT%, FTT Amt, Current P/L, Current, FTT, Dev%_PE, RSI_14, Conviction, Spread%, CumlRnk, RRR Ind, CurrAlloc%, Gained%, Criteria, Strategy, Category]
Index: []

In [13]:
# OX40N stocks to exit
df_tmp = df_portfolio_features[(df_portfolio_features['Symbol'].isin(list_ox40n))].sort_values(by = 'Current P/L%', ascending=False)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
27,FINCABLES,0.74,13.29,83.53,107.91,139714.0,19618.0,167262.0,1641.55,1.98,56.0,M-SC,7.74,220.0,0.14,1.24,25.84,OX40N,ATH,CABLES
77,TTKPRESTIG,8.00,-24.83,33.15,0.09,25113.0,-25020.0,75757.0,770.00,75.88,60.0,M-SC,15.24,250.0,-1.00,0.56,28.00,OX40N,NTT,DURABLES
66,SIS,-1.20,-33.86,83.33,21.26,61198.0,-37592.0,73440.0,528.00,1719.69,35.0,H-SC,10.61,168.0,-0.61,0.54,1.24,OX40N,NTT,MISC
48,KANSAINER,0.56,-37.24,80.79,13.47,136740.0,-100413.0,169254.0,340.00,-46.01,29.0,H-SC,16.73,162.0,-0.73,1.25,1.47,XY24,NTT,PAINTS
70,SYMPHONY,-0.69,-37.58,60.15,-0.03,64258.0,-64311.0,106830.0,1306.00,-49.88,46.0,M-SC,13.73,205.0,-1.00,0.79,8.03,OX40N,NTT,DURABLES

In [14]:
# top 5 to book for rotation
df_tmp = df_portfolio_features[(df_portfolio_features['Current P/L%'] > 20) ].sort_values(by = 'CumlRnk', ascending=False)
df_tmp[cols].head()

Empty DataFrame
Columns: [Symbol, Today P/L%, Current P/L%, FTT%, OTT%, FTT Amt, Current P/L, Current, FTT, Dev%_PE, RSI_14, Conviction, Spread%, CumlRnk, RRR Ind, CurrAlloc%, Gained%, Criteria, Strategy, Category]
Index: []

In [15]:
# top 5 to monitor for exit
df_tmp = df_portfolio_features[~df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])]
df_tmp = df_tmp[(df_tmp['Current P/L%'] > 0) ].sort_values(by = 'Dev%_PE', ascending=False)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
19,COALINDIA,5.23,15.60,1.79,17.67,3113.0,23476.0,173937.0,478.51,39.17,70.0,L-LC,12.20,185.0,7.54,1.29,35.07,XY25,ATH,MINING
27,FINCABLES,0.74,13.29,83.53,107.91,139714.0,19618.0,167262.0,1641.55,1.98,56.0,M-SC,7.74,220.0,0.14,1.24,25.84,OX40N,ATH,CABLES
1,ABB,2.05,17.59,23.79,45.57,73186.0,46013.0,307632.0,7934.00,-24.43,69.0,H-MC,10.55,125.0,0.63,2.28,36.61,AR,NTT,ELECTRICAL

In [16]:
# top 5 to book for rotation from weak conviction
df_tmp = df_portfolio_features[~df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])]
df_tmp = df_tmp[~df_tmp['Criteria'].isin(['XY25','XY24','X40', 'X40N'])].sort_values(by = 'RRR Ind', ascending=False)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
1,ABB,2.05,17.59,23.79,45.57,73186.0,46013.0,307632.0,7934.00,-24.43,69.0,H-MC,10.55,125.0,0.63,2.28,36.61,AR,NTT,ELECTRICAL
27,FINCABLES,0.74,13.29,83.53,107.91,139714.0,19618.0,167262.0,1641.55,1.98,56.0,M-SC,7.74,220.0,0.14,1.24,25.84,OX40N,ATH,CABLES
40,INDIAMART,-1.41,-9.75,129.04,106.72,143642.0,-12020.0,111316.0,4810.62,-59.38,41.0,H-SC,9.46,140.0,-0.08,0.82,11.35,AR,ATH,MISC
85,ZYDUSLIFE,-0.53,-3.31,40.27,35.63,81601.0,-6939.0,202635.0,1286.17,-15.77,53.0,H-MC,5.02,120.0,-0.09,1.50,12.81,AR,ATH,PHARMA
84,WIPRO,0.14,-16.94,107.40,72.27,151159.0,-28704.0,140744.0,420.00,-25.02,35.0,M-LC,15.05,98.0,-0.19,1.04,3.64,XR,NTT,IT

In [17]:
# top 5 to accumulate based on lowest RSI_14
df_tmp = df_portfolio_features[df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])].sort_values(by = 'RSI_14', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
58,RELAXO,-0.66,-60.80,288.57,52.31,164191.0,-88262.0,56898.0,1176.00,-58.28,18.0,X-SC,19.55,92.0,-0.54,0.42,0.00,X40N,NTT,FOOTWEAR
8,AWL,-1.81,-39.34,175.33,67.02,378951.0,-140173.0,216136.0,485.00,-67.29,20.0,X-SC,23.39,81.0,-0.37,1.60,0.31,XY24,NTT,FMCG
73,TCS,-0.91,-28.30,76.53,26.57,254207.0,-131107.0,332166.0,4311.59,-39.36,20.0,X-LC,14.45,2.0,-0.52,2.46,0.00,X40,ATH,IT
12,BATAINDIA,-0.66,-53.95,193.58,35.20,114712.0,-69412.0,59258.0,2096.00,-22.31,21.0,X-SC,26.23,91.0,-0.61,0.44,0.00,X40,NTT,FOOTWEAR
3,ACC,-1.58,-35.85,172.50,74.81,296714.0,-96120.0,172008.0,3906.00,-54.32,21.0,X-SC,12.81,85.0,-0.32,1.27,0.00,XY24,BTT,CEMENT

In [18]:
# top 5 to accumulate based on Spread and CumlRnk
df_tmp = df_portfolio_features[df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])]
df_tmp = df_tmp[(df_tmp['CumlRnk'] < 100)].sort_values(by = 'Spread%', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
78,UNITDSPR,-1.35,0.16,20.57,20.77,48241.0,378.0,234522.0,1644.00,-11.09,47.0,X-MC,1.41,64.0,0.01,1.74,6.88,X40N,NTT,BREWERIES
22,DABUR,-2.65,-10.19,60.01,43.70,133693.0,-25283.0,222785.0,735.00,-18.54,30.0,X-MC,1.52,70.0,-0.19,1.65,3.32,XY24,BTT,FMCG
37,ICICIGI,-1.06,-1.72,21.43,19.34,42145.0,-3447.0,196662.0,2252.93,-17.38,41.0,X-MC,1.77,66.0,-0.08,1.46,12.16,X40,ATH,INSURANCE
75,TMPV,-3.22,-26.12,84.87,36.58,223111.0,-92955.0,262886.0,600.00,-84.72,32.0,X-LC,1.79,4.0,-0.42,1.95,0.00,XY24,NTT,AUTO
59,RELIANCE,0.14,-10.63,40.21,25.30,72215.0,-21369.0,179594.0,1952.00,-13.11,45.0,X-LC,2.74,21.0,-0.30,1.33,19.91,XY25,BTT,REFINERIES

In [19]:
# top 5 to accumulate based on lowest Gained%
df_tmp = df_portfolio_features[df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])].sort_values(by = 'Gained%', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
3,ACC,-1.58,-35.85,172.50,74.81,296714.0,-96120.0,172008.0,3906.00,-54.32,21.0,X-SC,12.81,85.0,-0.32,1.27,0.0,XY24,BTT,CEMENT
12,BATAINDIA,-0.66,-53.95,193.58,35.20,114712.0,-69412.0,59258.0,2096.00,-22.31,21.0,X-SC,26.23,91.0,-0.61,0.44,0.0,X40,NTT,FOOTWEAR
10,BAJAJHLDNG,-3.81,-12.47,47.63,29.22,79263.0,-23712.0,166413.0,14451.52,-19.11,24.0,X-LC,12.33,28.0,-0.30,1.23,0.0,X40,ATH,FINANCE
13,BERGEPAINT,-1.85,-22.10,60.87,25.32,122216.0,-56967.0,200782.0,680.00,-26.28,25.0,X-MC,15.67,68.0,-0.47,1.49,0.0,XY24,NTT,PAINTS
21,COLPAL,-3.88,-24.98,88.62,41.51,175095.0,-65785.0,197580.0,3726.84,-9.21,32.0,X-MC,4.13,62.0,-0.38,1.46,0.0,XY25,ATH,FMCG

In [20]:
# top 5 to accumulate based on lowest CurrAlloc%
df_tmp = df_portfolio_features[df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])].sort_values(by = 'CurrAlloc%', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
58,RELAXO,-0.66,-60.80,288.57,52.31,164191.0,-88262.0,56898.0,1176.00,-58.28,18.0,X-SC,19.55,92.0,-0.54,0.42,0.00,X40N,NTT,FOOTWEAR
12,BATAINDIA,-0.66,-53.95,193.58,35.20,114712.0,-69412.0,59258.0,2096.00,-22.31,21.0,X-SC,26.23,91.0,-0.61,0.44,0.00,X40,NTT,FOOTWEAR
54,QUESS,-1.51,-21.98,122.89,73.90,102393.0,-23472.0,83321.0,424.00,-58.13,41.0,X-SC,18.35,80.0,-0.23,0.62,2.78,XY24,NTT,MISC
36,HONAUT,-0.23,-20.71,90.83,51.31,138879.0,-39938.0,152900.0,58357.33,-34.10,42.0,X-SC,13.78,90.0,-0.29,1.13,2.96,X40N,ATH,ELECTRICAL
2,ABBOTINDIA,-1.89,-10.48,31.89,18.07,51059.0,-18745.0,160110.0,35195.00,-23.83,45.0,X-MC,11.11,58.0,-0.37,1.19,1.50,X40,ATH,PHARMA

In [21]:
# top 5 to accumulate based on CumlRnk
df_tmp = df_portfolio_features.sort_values(by = 'CumlRnk', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
45,ITC,-1.59,-19.90,48.64,19.06,132531.0,-67692.0,272474.0,452.00,-55.92,33.0,X-LC,17.06,1.0,-0.51,2.02,0.0,X40,NTT,FMCG
73,TCS,-0.91,-28.30,76.53,26.57,254207.0,-131107.0,332166.0,4311.59,-39.36,20.0,X-LC,14.45,2.0,-0.52,2.46,0.0,X40,ATH,IT
43,INFY,-0.82,-13.83,55.79,34.24,150418.0,-43273.0,269615.0,1972.00,-32.15,25.0,X-LC,12.75,3.0,-0.29,2.00,0.0,X40,NTT,IT
75,TMPV,-3.22,-26.12,84.87,36.58,223111.0,-92955.0,262886.0,600.00,-84.72,32.0,X-LC,1.79,4.0,-0.42,1.95,0.0,XY24,NTT,AUTO
34,HCLTECH,0.58,-11.86,40.50,23.83,86355.0,-28702.0,213222.0,1908.19,-7.36,30.0,X-LC,9.80,8.0,-0.33,1.58,2.3,X40,ATH,IT

In [22]:
# top 5 for average up
df_tmp = df_portfolio_features[(df_portfolio_features['Dev%_200'] > 5)].sort_values(by = 'CurrAlloc%', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
67,SONACOMS,-1.17,-11.72,57.56,39.09,51402.0,-11857.0,89302.0,804.02,-30.06,48.0,M-MC,9.84,193.0,-0.23,0.66,26.33,AR,ATH,AUTO
27,FINCABLES,0.74,13.29,83.53,107.91,139714.0,19618.0,167262.0,1641.55,1.98,56.0,M-SC,7.74,220.0,0.14,1.24,25.84,OX40N,ATH,CABLES
19,COALINDIA,5.23,15.60,1.79,17.67,3113.0,23476.0,173937.0,478.51,39.17,70.0,L-LC,12.20,185.0,7.54,1.29,35.07,XY25,ATH,MINING
82,VOLTAS,-1.50,13.39,28.05,45.20,60984.0,25668.0,217410.0,1856.00,29.81,46.0,X-MC,9.35,79.0,0.42,1.61,21.09,XY25,NTT,AC
11,BANDHANBNK,-2.44,-14.37,124.71,92.42,297475.0,-40026.0,238533.0,400.00,104.74,56.0,H-SC,9.87,174.0,-0.13,1.77,31.40,XY24,NTT,BANKS

In [23]:
# top 5 RSP
df_tmp = df_portfolio_features.sort_values(by = 'RSP', ascending=False)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
19,COALINDIA,5.23,15.60,1.79,17.67,3113.0,23476.0,173937.0,478.51,39.17,70.0,L-LC,12.20,185.0,7.54,1.29,35.07,XY25,ATH,MINING
1,ABB,2.05,17.59,23.79,45.57,73186.0,46013.0,307632.0,7934.00,-24.43,69.0,H-MC,10.55,125.0,0.63,2.28,36.61,AR,NTT,ELECTRICAL
27,FINCABLES,0.74,13.29,83.53,107.91,139714.0,19618.0,167262.0,1641.55,1.98,56.0,M-SC,7.74,220.0,0.14,1.24,25.84,OX40N,ATH,CABLES
31,HAPPSTMNDS,-0.64,-48.93,261.99,84.85,171467.0,-62717.0,65448.0,1480.71,-39.37,61.0,H-SC,28.36,152.0,-0.37,0.48,21.20,AR,ATH,IT
26,EASEMYTRIP,-1.50,-60.04,264.64,45.70,186963.0,-106167.0,70648.0,26.40,-26.57,42.0,M-SC,18.20,204.0,-0.57,0.52,16.40,XY24,NTT,TRAVEL

In [24]:
# Top N allocation
df_tmp = df_portfolio_features.sort_values(by = 'CurrAlloc%', ascending=False)
top_n_values = [10, 25, 50]

sum_df = pd.DataFrame({
    'Top_N': top_n_values,
    'Sum_Alloc%': [df_tmp['CurrAlloc%'].head(n).sum() for n in top_n_values]
})

sum_df

   Top_N  Sum_Alloc%
0     10       20.35
1     25       45.19
2     50       77.78

In [25]:
# market-cap-wise allocation
df_tmp = df_portfolio_features[cols]
df_tmp.groupby(df_tmp['Conviction'].str[-2:])['CurrAlloc%'].sum().sort_values(ascending=False)

Conviction
SC    44.72
MC    30.45
LC    24.86
Name: CurrAlloc%, dtype: float64

In [26]:
# criteria-wise allocation
df_portfolio_features.groupby('Criteria')['CurrAlloc%'].sum().sort_values(ascending=False)

Criteria
XY24     27.32
X40      23.72
X40N     15.06
AR        9.28
XY25      8.67
XR        8.22
OX40N     6.98
SR        0.78
Name: CurrAlloc%, dtype: float64

In [27]:
# conviction-wise allocation
df_portfolio_features.groupby('Conviction')['CurrAlloc%'].sum().sort_values(ascending=False)

Conviction
X-MC    22.97
H-SC    21.74
X-LC    21.30
X-SC    12.07
M-SC    10.33
H-MC     5.07
M-MC     2.06
L-LC     1.29
H-LC     1.23
M-LC     1.04
L-SC     0.58
L-MC     0.35
Name: CurrAlloc%, dtype: float64

In [28]:
# sector-wise stats
df_tmp = df_portfolio_features.groupby('Category')[['CurrAlloc%', 'Current', 'Current P/L', 'FTT Amt']].sum().sort_values(by=['Current', 'Current P/L'], ascending=False)
df_tmp['Current P/L%'] = round(df_tmp['Current P/L'] * 100 / df_tmp['Current'], 2)
df_tmp['FTT%'] = round(df_tmp['FTT Amt'] * 100 / df_tmp['Current'], 2)
cols = ['CurrAlloc%', 'Current P/L%', 'FTT%']
df_tmp[cols].sort_values(by=['CurrAlloc%'], ascending=False)

               CurrAlloc%  Current P/L%    FTT%
Category
FMCG                15.06        -22.74   66.32
FINANCE             12.85        -23.82   74.29
IT                  11.74        -42.18  114.54
MISC                 7.02        -41.30  102.68
ELECTRICAL           6.74         -6.30   47.00
PAINTS               5.17        -41.17   65.68
INSURANCE            4.75         -5.73   41.92
PHARMA               4.17         -4.37   37.22
AUTO                 3.68        -31.72   83.98
BANKS                3.07        -28.95  107.09
AC                   2.16         -9.54   39.24
HEALTHCARE           1.99        -32.66   67.28
DURABLES             1.94        -47.72   83.66
FOOTWEAR             1.87        -74.74  144.81
TRAVEL               1.81        -82.13  173.32
BREWERIES            1.74          0.16   20.57
APPARELS             1.60        -24.24   66.62
REALTY               1.45        -13.44   32.07
CERAMICS             1.35        -67.49  118.38
REFINERIES           1.33        -11.90   40.21
MINING               1.29         13.50    1.79
CEMENT               1.27        -55.88  172.50
CABLES               1.24         11.73   83.53
JEWELLERY            1.12       -111.53  185.02
ENGINEERING          1.11        -61.95  136.03
CHEMICALS            0.95       -107.00  275.88
ENTERTAINMENT        0.77        -86.73  198.10
TEXTILES             0.43        -60.30  106.01
HOTELS               0.36       -132.38  214.34

In [29]:
# money to be made criteria-wise
df_portfolio_features.groupby('Criteria')['FTT Amt'].agg(['sum', 'count']).sort_values(by='sum', ascending=False)

                sum  count
Criteria
XY24      3906539.0     21
X40       1669346.0     15
XR        1382405.0     12
AR        1317401.0     10
X40N      1266487.0     10
OX40N      847498.0     10
XY25       446292.0      6
SR         315106.0      2

In [30]:
# money to be made conviction-wise
df_portfolio_features.groupby('Conviction')['FTT Amt'].agg(['sum', 'count']).sort_values(by='sum', ascending=False)

                  sum  count
Conviction
H-SC        3857811.0     24
X-MC        1631839.0     15
X-LC        1598890.0     12
X-SC        1550153.0     10
M-SC        1522455.0     14
H-MC         393508.0      3
L-SC         211812.0      2
M-LC         151159.0      1
M-MC         107777.0      2
H-LC          67342.0      1
L-MC          55215.0      1
L-LC           3113.0      1

In [31]:
# money to be made criteria and conviction-wise
df_portfolio_features.groupby(['Conviction', 'Criteria'])['FTT Amt'].agg(['sum', 'count']).sort_values(by='sum', ascending=False)

                           sum  count
Conviction Criteria
H-SC       XY24      1310280.0      6
           AR         967088.0      5
M-SC       XY24       899293.0      6
H-SC       XR         880647.0      7
X-SC       XY24       835862.0      4
X-LC       X40        829150.0      6
X-MC       X40        635867.0      7
X-SC       X40N       509962.0      4
X-MC       X40N       503984.0      4
H-SC       OX40N      384690.0      4
X-LC       XY24       366474.0      2
M-SC       OX40N      355731.0      5
H-SC       SR         315106.0      2
X-MC       XY24       255909.0      2
X-LC       X40N       252541.0      2
H-MC       XY24       238721.0      1
X-MC       XY25       236079.0      2
X-SC       X40        204329.0      2
M-SC       XR         190649.0      2
H-MC       AR         154787.0      2
M-LC       XR         151159.0      1
X-LC       XY25       150725.0      2
L-SC       OX40N      107077.0      1
           XR         104735.0      1
M-SC       AR          76782.0      1
H-LC       AR          67342.0      1
M-MC       XY25        56375.0      1
L-MC       XR          55215.0      1
M-MC       AR          51402.0      1
L-LC       XY25         3113.0      1

In [32]:
# notebook execution time

end_time = time.time()
execution_time = round(end_time - start_time, 0)
print(f"Notebook execution time: {execution_time} seconds")

Notebook execution time: 25.0 seconds