<a href="https://colab.research.google.com/github/ankit-rathi/Quantvesting_v2/blob/main/myStocks_Portfolio_Analysis.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
'''
!pip install pandas==2.2.2 -qq
!pip install pyxirr -qq
!pip install ta -qq
!pip install yfinance==0.2.59 -qq
'''

'\n!pip install pandas==2.2.2 -qq\n!pip install pyxirr -qq\n!pip install ta -qq\n!pip install yfinance==0.2.59 -qq\n'

In [2]:
# import libraries

import numpy as np
import pandas as pd
import datetime
import warnings
warnings.filterwarnings('ignore')
import yfinance as yfin
import ta
import matplotlib.pyplot as plt
import requests

In [3]:
# notebook start time
import time
import datetime
import pytz

start_time = time.time()

# function to print date timestamp
def print_date_time():
  tz_NY = pytz.timezone('Asia/Kolkata')
  datetime_NY = datetime.datetime.now(tz_NY)
  print("Run date time (IST):", datetime_NY.strftime("%Y-%m-%d %H:%M:%S"))

In [4]:
# function to get booked and reserved amount
def get_amt():
  # fetch the JSON data from the URL
  url = "https://raw.githubusercontent.com/ankit-rathi/Tradevesting_v1/main/data/myPortfolioAmts.json"
  response = requests.get(url)
  pf_amts = response.json()  # parse the JSON data

  # extract values from the JSON
  py_booked_amt_dm = pf_amts["py_booked_amt_dm"]
  py_booked_amt_sv = pf_amts["py_booked_amt_sv"]
  cy_booked_amt_dm = pf_amts["cy_booked_amt_dm"]
  cy_booked_amt_sv = pf_amts["cy_booked_amt_sv"]
  reserve_amt_dm = pf_amts["reserve_amt_dm"]
  reserve_amt_sv = pf_amts["reserve_amt_sv"]

  # perform calculations
  py_booked_amt = py_booked_amt_dm + py_booked_amt_sv
  cy_booked_amt = cy_booked_amt_dm + cy_booked_amt_sv
  reserve_amt = reserve_amt_dm + reserve_amt_sv
  total_booked_amt = py_booked_amt + cy_booked_amt

  return total_booked_amt, reserve_amt, cy_booked_amt, py_booked_amt

gen_output = 0

In [5]:
# function to format the amount
def format_amt(number):
    abs_number = abs(number)

    if abs_number >= 1_00_00_000:  # Crores
        formatted_amt = f"{number / 1_00_00_000:.2f} C"
    elif abs_number >= 1_00_000:  # Lakhs
        formatted_amt = f"{number / 1_00_000:.2f} L"
    elif abs_number >= 1_000:  # Thousands
        formatted_amt = f"{number / 1_000:.2f} K"
    else:
        formatted_amt = f"{number:.2f}"

    return formatted_amt

# function to set start and end date
def get_start_end_date():
  start_date = (datetime.date.today() + datetime.timedelta(days=-365)).strftime('%Y-%m-%d')
  end_date = (datetime.date.today() + datetime.timedelta(days=1)).strftime('%Y-%m-%d')
  return start_date, end_date

# function to fetch my portfolio csv
def get_mypfs_df():
  mypfs_df = pd.read_csv('https://raw.githubusercontent.com/ankit-rathi/Tradevesting_v1/main/data/myPortfolioStocks.csv')
  return mypfs_df

# function to fetch my prospects csv
def get_mypps_df():
  mypps_df = pd.read_csv('https://raw.githubusercontent.com/ankit-rathi/Tradevesting_v1/main/data/myProspectsScrips.csv')
  return mypps_df

# function to fetch screener data
def get_myscreen_df():
  myscreen_df = pd.read_csv('https://raw.githubusercontent.com/ankit-rathi/Tradevesting_v1/main/data/myScreenerDB.csv')
  return myscreen_df

# function to fetch momentum data
def get_myinvmt_df():
  myinvmt_df = pd.read_csv('https://raw.githubusercontent.com/ankit-rathi/Tradevesting_v1/main/data/myInvestments.csv')
  return myinvmt_df

# function to get the stock ids
def get_stock_ids(df_pf):
  stock_n100 = df_pf['Symbol'].unique()

  exclude = ['CADILAHC','MMTC', 'MASFIN']

  stock_ids = df_pf[~df_pf['Symbol'].isin(exclude) ]['Symbol'].unique()

  #mypf = mypf[mypf.Forecast.notnull()]
  #stock_ids = mypf['Symbol'].unique()

  #stock_ids.sort()
  return stock_ids

# get features from screener data
def get_screener_features():
  myscreen_df = get_myscreen_df()
  cols = ['Symbol', 'EPS', 'MedPE', 'ROCE%', 'ROE%', 'CapType']
  return myscreen_df[cols]

# get relative strength
def get_relative_strength(stock_list):

    # Dictionary to store stock tickers and their corresponding percentage price change
    stock_changes = {}

    # Loop through each stock and fetch its price data
    for stock in stock_list:
        try:
            # Download the stock data for the given date range
            stock_data = yfin.Ticker(stock + '.NS').history(period='1mo', interval='1d')[map(str.title, ['open', 'close', 'low', 'high', 'volume'])]

            # Calculate the percentage change for the stock
            if len(stock_data) > 0:
                start_price = stock_data['Close'].iloc[0]
                end_price = stock_data['Close'].iloc[-1]
                percent_change = round(((end_price - start_price) / start_price) * 100, 2)
                stock_changes[stock] = percent_change
            else:
                stock_changes[stock] = np.nan  # If no data is available, set to NaN

        except Exception as e:
            print(f"Error fetching data for {stock}: {e}")
            stock_changes[stock] = np.nan

    # Create a DataFrame with stock tickers and their percentage changes
    df = pd.DataFrame(list(stock_changes.items()), columns=['Symbol', 'Percent_Change'])

    # Drop any stocks with missing data (NaN values)
    df = df.dropna()

    # Calculate the percentile rank based on percentage change
    df['RSP'] = round(df['Percent_Change'].rank(pct=True) * 100, 2)
    cols = ['Symbol', 'RSP']
    df = df[cols]
    # Sort by percentile rank (optional)
    df = df.sort_values(by='RSP', ascending=False).reset_index(drop=True)

    return df

In [6]:
# function to get stock technicals
def stock_prec_dev(stock_symbol):
    #stock_symbol = 'ULTRACEMCO.NS'
    short_window = 20
    mid_window = 50
    long_window = 200
    moving_avg = 'SMA'

    start = datetime.datetime(*map(int, start_date.split('-')))
    end = datetime.datetime(*map(int, end_date.split('-')))

    stock_df = yfin.Ticker(stock_symbol + '.NS').history(period='max', interval='1d')[map(str.title, ['open', 'close', 'low', 'high', 'volume'])]

    stock_df['Max'] = round(max(stock_df['Close']),2)
    stock_df = stock_df[(stock_df.index <= end_date) & (stock_df.index >= start_date)]
    stock_df['200_SMA'] = round(stock_df['Close'].rolling(window = 200, min_periods = 1).mean(),0)
    stock_df['Dev%_200'] = round((stock_df['Close'] - stock_df['200_SMA'])*100/stock_df['200_SMA'],2)
    stock_df.dropna(axis = 0, inplace = True) # remove any null rows

    stock_df['20_SMA'] = stock_df['Close'].rolling(window=20).mean()
    stock_df['50_SMA'] = stock_df['Close'].rolling(window=50).mean()
    stock_df['Symbol'] = stock_symbol

    stock_df['Close'] = round(stock_df['Close'],2)
    stock_df['Min'] = round(min(stock_df['Close']),2)
    stock_df['RSI_14'] = ta.momentum.RSIIndicator(close=stock_df['Close'], window=14).rsi()
    stock_df['RSI_14'] = round(stock_df['RSI_14'],0)
    stock_df['Prev_Close'] = stock_df['Close'].shift(1)
    stock_df.drop(['Open', 'Low', 'High', 'Volume'], axis=1, inplace=True)
    stock_df = stock_df.tail(1)

    max_SMA = max(stock_df['20_SMA'].item(), stock_df['50_SMA'].item(), stock_df['200_SMA'].item())
    min_SMA = min(stock_df['20_SMA'].item(), stock_df['50_SMA'].item(), stock_df['200_SMA'].item())
    ABS_Spread = max_SMA - min_SMA
    stock_df['Spread%'] = round((ABS_Spread / stock_df['200_SMA'].item()) * 100,2)

    return stock_df

# function to compute stock attributes
def get_common_features(stock_ids, df_mypf):

  df_prec_dev = pd.DataFrame()
  df_tmp = get_screener_features()
  df_rs = get_relative_strength(stock_ids)

  for stock_id in stock_ids:
      tmp = stock_prec_dev(stock_id)
      tmp = tmp.reset_index()
      df_prec_dev = pd.concat([df_prec_dev, tmp], ignore_index = True)
  df_prec_dev = pd.merge(df_prec_dev, df_mypf, on= 'Symbol')
  df_prec_dev = pd.merge(df_prec_dev, df_tmp, on= 'Symbol', how='left')
  df_prec_dev = pd.merge(df_prec_dev, df_rs, on= 'Symbol', how='left')
  #print(df_prec_dev.columns)
  df_prec_dev['Curr_PE'] = round(df_prec_dev['Close']/df_prec_dev['EPS'],1)
  df_prec_dev['Dev%_PE'] = round((df_prec_dev['Curr_PE'] - df_prec_dev['MedPE'])*100/df_prec_dev['MedPE'],2)
  df_prec_dev['Conviction'] = df_prec_dev['Conviction'] + '-' + df_prec_dev['CapType']
  return df_prec_dev

# function to arrange stock features
def arrange_features(df_stocks, common_cols, diff_cols):
  df_stocks_common = df_stocks[common_cols].drop_duplicates()
  df_stocks_diff = df_stocks[diff_cols]
  df_stocks_diff['Investment'] = df_stocks_diff['AvgCost'] * df_stocks_diff['Shares']
  df_stocks_diff = df_stocks_diff.groupby(['Symbol'])[['Shares', 'Investment']].aggregate(['sum']).reset_index()
  df_stocks_diff.columns = ['Symbol', 'Shares', 'Investment']
  df_stocks_diff['AvgCost'] = round(df_stocks_diff['Investment']/df_stocks_diff['Shares'],2)
  df_stocks = pd.merge(df_stocks_diff, df_stocks_common, on='Symbol')
  return df_stocks

# plot fact distribution across dimension
def plot_pie_chart(df, dimension, fact):
  # grouping the data by category and calculating the sum of fact for each type
  grouped_data = df.groupby(dimension)[fact].sum()

  # sorting the grouped data in descending order
  grouped_data = grouped_data.sort_values(ascending=False)

  # creating a pie chart
  grouped_data.plot.pie(autopct='%1.1f%%', startangle=90, figsize=(6, 6))

  # adding a title and displaying the plot
  plt.title(f'{dimension} {fact} Distribution')
  plt.ylabel('')  # To hide the y-label
  plt.show()

In [7]:
# function to get portfolio features

def get_portfolio_features(df_common_features):

  print_date_time()
  print('-------------------')

  #df_common_features["Target"] = df_common_features["Target"].fillna(df_common_features["Max"])
  df_common_features['NTT'] = np.where(df_common_features['Strategy']== 'NTT', df_common_features["Target"], df_common_features['Max'])
  df_common_features['LTT'] = np.where(df_common_features['Strategy']== 'BTT', df_common_features["Target"], df_common_features['Max'])
  df_common_features['BOL'] = df_common_features['Min']

  tmp_df = df_common_features[df_common_features['Symbol'].isin(mypf_df[mypf_df['InPortfolio'] != 'NA'].Symbol.values)]
  print('qualified stocks: '+str(len(tmp_df['Symbol'].unique())))
  tmp_df1 = tmp_df[tmp_df['LatestQtr'] == 1]
  print('with latest results: '+str(len(tmp_df1['Symbol'].unique())))
  tmp_df1 = tmp_df1[tmp_df1['StarStock'] == 1]
  print('still star stocks: '+str(len(tmp_df1['Symbol'].unique())))
  tmp_df['Investment'] = tmp_df['AvgCost'] * tmp_df['Shares']
  tmp_df['Current'] = round(tmp_df['Close'] * tmp_df['Shares'],0)
  tmp_df['Previous'] = tmp_df['Prev_Close'] * tmp_df['Shares']
  tmp_df['EstimatedST'] = tmp_df['NTT'] * tmp_df['Shares']
  tmp_df['EstimatedLT'] = tmp_df['LTT'] * tmp_df['Shares']
  tmp_df['Current P/L'] = round((tmp_df['Current'] - tmp_df['Investment']),0)
  tmp_df['Today P/L%'] = round((tmp_df['Current'] - tmp_df['Previous'])*100/tmp_df['Previous'],2)
  tmp_df['Current P/L%'] = round((tmp_df['Current'] - tmp_df['Investment'])*100/tmp_df['Investment'],2)
  tmp_df['EstimatedST P/L%'] = round((tmp_df['EstimatedST'] - tmp_df['Investment'])*100/tmp_df['Investment'],2)
  tmp_df['EstimatedLT P/L%'] = round((tmp_df['EstimatedLT'] - tmp_df['Investment'])*100/tmp_df['Investment'],2)
  tmp_df['NTT%'] = round((tmp_df['NTT'] - tmp_df['Close'])*100/tmp_df['Close'],2)
  tmp_df['LTT%'] = round((tmp_df['LTT'] - tmp_df['Close'])*100/tmp_df['Close'],2)
  tmp_df['Gained%'] = round((tmp_df['Close'] - tmp_df['BOL'])*100/tmp_df['BOL'],2)
  investment = round(sum(tmp_df['AvgCost']*tmp_df['Shares']),0)
  current = round(sum(tmp_df['Close']*tmp_df['Shares']),0)
  tmp_df['InitAlloc%'] = round(tmp_df['Investment']*100/investment,2)
  tmp_df['CurrAlloc%'] = round(tmp_df['Current']*100/current,2)
  tmp_df['FTT'] = tmp_df['LTT']
  tmp_df.loc[tmp_df['Strategy'] == 'NTT', 'FTT'] = tmp_df['NTT']
  tmp_df['FTT%'] = tmp_df['LTT%']
  tmp_df.loc[tmp_df['Strategy'] == 'NTT', 'FTT%'] = tmp_df['NTT%']
  tmp_df['FTT Amt'] = round(tmp_df['FTT%'] * tmp_df['Current']/100,0)
  tmp_df['OTT%'] = round((tmp_df['FTT'] - tmp_df['AvgCost'])*100/tmp_df['AvgCost'],2)
  tmp_df['RRR Ind'] = round(tmp_df['Current P/L']/tmp_df['FTT Amt'],2)
  tmp_df['Risk Ind'] = round(tmp_df['Current P/L%']*tmp_df['CurrAlloc%'],0)

  return tmp_df

# function to print portfolio features
def print_portfolio_stats(df_portfolio_features, myinvmt_df):
  from pyxirr import xirr

  total_booked_amt, reserve_amt, cy_booked_amt, py_booked_amt = get_amt()

  dates = myinvmt_df['Date'].values
  dates = np.append(dates, datetime.date.today().strftime('%d-%b-%y'))
  investment = myinvmt_df['Investment'].values
  dates= pd.to_datetime(dates)

  current = round(sum(df_portfolio_features['Close']*df_portfolio_features['Shares']),0) + reserve_amt
  investment_xirr = np.append(investment, current)
  cagr = round(xirr(pd.DataFrame({"dates": dates, "amounts": investment_xirr}))*100,2)

  investment = -sum(investment)
  invested = round(sum(df_portfolio_features['AvgCost']*df_portfolio_features['Shares']),0) + reserve_amt
  previous = round(sum(df_portfolio_features['Prev_Close']*df_portfolio_features['Shares']),0) + reserve_amt
  cy_invested = investment + py_booked_amt

  today_pnl_amount = current-previous
  today_pnl_percentage = round((current-previous)*100/previous,2)

  curr_pnl_amount = current-invested
  curr_pnl_percentage = round((curr_pnl_amount)*100/(cy_invested),2)

  cy_pnl_amount = cy_booked_amt + curr_pnl_amount
  cy_pnl_percentage = round((cy_pnl_amount)*100/cy_invested,2)

  overall_pnl_amount = total_booked_amt + curr_pnl_amount
  overall_pnl_percentage = round((overall_pnl_amount)*100/investment,2)

  estimate_st = round(sum(df_portfolio_features['FTT']*df_portfolio_features['Shares']),0)  + reserve_amt
  est_st_pnl_amount = estimate_st-current
  est_st_pnl_percentage = round((est_st_pnl_amount)*100/current,2)

  estimate_lt = round(sum(df_portfolio_features['LTT']*df_portfolio_features['Shares']),0)  + reserve_amt
  est_lt_pnl_amount = estimate_lt-current
  est_lt_pnl_percentage = round((est_lt_pnl_amount)*100/current,2)

  total_profit = round(sum(df_portfolio_features[df_portfolio_features['Current P/L%'] > 0]['Current']) - sum(df_portfolio_features[df_portfolio_features['Current P/L%'] > 0]['Investment']),0)
  total_loss = round(sum(df_portfolio_features[df_portfolio_features['Current P/L%'] < 0]['Current']) - sum(df_portfolio_features[df_portfolio_features['Current P/L%'] < 0]['Investment']),0)

  cy_booked_percentage = round((cy_booked_amt)*100/current,2)
  py_booked_percentage = round((py_booked_amt)*100/investment,2)
  total_booked_percentage = round((total_booked_amt)*100/investment,2)

  print('-------------------')
  print('Initial Investment: ', format_amt(investment))
  print('CY Investment: ', format_amt(cy_invested))
  print('Reserve: ', format_amt(reserve_amt))
  print('Current: ',  format_amt(current))
  print('-------------------')
  print('Today PnL: '+ '{} ({}%)'.format(format_amt(today_pnl_amount), today_pnl_percentage))
  print('Current PnL: '+ '{} ({}%)'.format(format_amt(curr_pnl_amount), curr_pnl_percentage))
  print('CY Booked + Current PnL: '+ '{} ({}%)'.format(format_amt(cy_pnl_amount), cy_pnl_percentage))
  print('-------------------')
  print('Total profit: ', format_amt(total_profit))
  print('Total loss: ', format_amt(total_loss))
  print('-------------------')
  print('Total Booked + Current PnL: '+ '{} ({}%)'.format(format_amt(overall_pnl_amount), overall_pnl_percentage))
  print('Total Booked PnL: '+ '{} ({}%)'.format(format_amt(total_booked_amt), total_booked_percentage))
  print('Curr Year Booked PnL: '+ '{} ({}%)'.format(format_amt(cy_booked_amt), cy_booked_percentage))
  print('Prev Year Booked PnL: '+ '{} ({}%)'.format(format_amt(py_booked_amt), py_booked_percentage))
  print('===================')
  print('Est FTT: ',  format_amt(estimate_st))
  print('Est FTT PnL: '+ '{} ({}%)'.format(format_amt(est_st_pnl_amount), est_st_pnl_percentage))

  print('===================')
  print('Deployed: ', format_amt(investment))

  print('Current: ', format_amt(current))

  print('CAGR/XIRR %: '+'{}%'.format(cagr))

In [8]:
# get start and end date
start_date, end_date = get_start_end_date()

# get portfolio and prospects data
mypfs_df = get_mypfs_df()
mypps_df = get_mypps_df()
myinvmt_df = get_myinvmt_df()

# merge above datasets
mypf_df = pd.merge(mypfs_df, mypps_df, on="Symbol")

# seggregate dm and sv portfolio
dm_pf = mypf_df[mypf_df['InPortfolio'] == 'DM']
sv_pf = mypf_df[mypf_df['InPortfolio'] == 'SV']

# build portfolio stock dataframe
dm_stocks = get_stock_ids(dm_pf)
sv_stocks = get_stock_ids(sv_pf)
df_stocks = pd.concat([dm_pf,sv_pf], ignore_index = True)

# arrange common and diff stock features
common_cols = ['Symbol', 'Target', 'Criteria', 'Strategy', 'CumlRnk', 'LatestQtr', 'StarStock', 'Conviction', 'Category', 'InFolio', 'XIRR', 'MBQ']
diff_cols = ['Symbol', 'AvgCost', 'Shares']
df_stocks = arrange_features(df_stocks, common_cols, diff_cols)

# get common features
stock_ids = df_stocks['Symbol'].values
df_common_features = get_common_features(stock_ids, df_stocks)

df_common_features.reset_index(drop=True, inplace=True)
df_common_features.drop(['Date'], axis=1, inplace=True)
# get and print portfolio features
df_portfolio_features = get_portfolio_features(df_common_features)

print_portfolio_stats(df_portfolio_features, myinvmt_df)

df = df_portfolio_features
#plot_pie_chart(df, 'CapType', 'Current')
list_ox40n = list(df[df['MBQ'].str.contains('OX40N', na=False)]['Symbol'].values)

Run date time (IST): 2026-08-17 10:51:30
-------------------
qualified stocks: 88
with latest results: 30
still star stocks: 19
-------------------
Initial Investment:  1.46 C
CY Investment:  1.89 C
Reserve:  2.21 L
Current:  1.59 C
-------------------
Today PnL: -87.49 K (-0.55%)
Current PnL: -33.71 L (-17.85%)
CY Booked + Current PnL: -29.07 L (-15.39%)
-------------------
Total profit:  3.77 L
Total loss:  -37.48 L
-------------------
Total Booked + Current PnL: 13.80 L (9.45%)
Total Booked PnL: 47.52 L (32.53%)
Curr Year Booked PnL: 4.65 L (2.93%)
Prev Year Booked PnL: 42.87 L (29.35%)
===================
Est FTT:  2.68 C
Est FTT PnL: 1.09 C (68.6%)
===================
Deployed:  1.46 C
Current:  1.59 C
CAGR/XIRR %: 3.81%

In [9]:
# top 5 near their targets
cols = ['Symbol', 'Today P/L%', 'Current P/L%', 'FTT%', 'OTT%', 'FTT Amt', 'Current P/L', 'Current', 'FTT', 'Dev%_PE', 'RSI_14','Conviction', 'Spread%',  'CumlRnk', 'RRR Ind', 'CurrAlloc%', 'Gained%', 'Criteria', 'Strategy', 'Category']
df_tmp = df_portfolio_features[~df_portfolio_features['Symbol'].isin(['ENRIN','BLUSPRING','DIGITIDE'])]
df_tmp = df_tmp.sort_values(by = 'FTT Amt', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
79,UNITDSPR,0.05,12.88,6.98,20.77,18449.0,30168.0,264312.0,1644.00,0.15,66.0,X-MC,9.96,64.0,1.64,1.69,27.05,X40N,NTT,BREWERIES
78,TTKPRESTIG,-0.59,-22.99,29.98,0.09,23266.0,-23173.0,77604.0,770.00,80.15,41.0,M-SC,10.51,250.0,-1.00,0.50,39.68,OX40N,NTT,DURABLES
68,SIS,-1.18,-2.48,24.35,21.26,26364.0,-2759.0,108273.0,528.00,2582.90,44.0,H-SC,21.95,168.0,-0.10,0.69,60.99,OX40N,NTT,MISC
52,M&M,-1.01,7.16,10.88,18.82,28062.0,17240.0,257921.0,3762.88,-6.78,56.0,X-LC,4.74,25.0,0.61,1.65,17.00,X40N,ATH,AUTO
54,MASFIN,0.33,-7.38,31.25,21.57,28359.0,-7230.0,90750.0,397.04,-20.05,42.0,H-SC,1.02,167.0,-0.25,0.58,8.17,XR,ATH,FINANCE

In [10]:
# top 5 today
df_tmp = df_portfolio_features.sort_values(by = 'Today P/L%', ascending=False)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
25,FINCABLES,4.57,65.13,25.91,107.91,63171.0,96167.0,243811.0,1641.55,48.66,75.0,M-SC,18.91,220.0,1.52,1.56,83.43,OX40N,ATH,CABLES
18,COFFEEDAY,3.57,-49.53,168.01,35.27,96290.0,-56237.0,57312.0,80.00,-61.77,42.0,L-SC,4.00,266.0,-0.58,0.37,41.34,XR,NTT,HOTELS
58,RAJESHEXPO,2.54,-83.83,518.95,0.07,115093.0,-114999.0,22178.0,518.00,713.13,42.0,L-SC,37.10,268.0,-1.00,0.14,9.53,OX40N,NTT,JEWELLERY
5,ATULAUTO,1.90,-13.07,67.46,45.57,115599.0,-25772.0,171360.0,844.00,3716.22,49.0,M-SC,10.60,248.0,-0.22,1.09,31.87,XY24,NTT,AUTO
43,INDIGOPNTS,1.40,-17.26,20.88,0.02,30158.0,-30124.0,144435.0,1408.00,120.42,69.0,M-SC,6.68,222.0,-1.00,0.92,63.87,OX40N,NTT,PAINTS

In [11]:
# bottom 5 today
df_tmp = df_portfolio_features.sort_values(by = 'Today P/L%', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
82,VALIANTORG,-4.99,-35.93,171.81,74.15,180095.0,-58783.0,104822.0,838.0,-288.40,58.0,H-SC,6.38,145.0,-0.33,0.67,55.99,XR,NTT,CHEMICALS
24,EASEMYTRIP,-4.53,-66.28,332.08,45.70,197989.0,-117194.0,59621.0,26.4,-38.00,32.0,M-SC,7.08,204.0,-0.59,0.38,4.44,XY24,NTT,TRAVEL
29,GREENPANEL,-3.15,-54.94,217.68,43.14,179569.0,-100586.0,82492.0,537.0,84.75,30.0,M-SC,10.88,225.0,-0.56,0.53,0.00,XY24,NTT,MISC
65,SFL,-2.99,-33.19,89.53,26.63,156852.0,-87023.0,175195.0,1287.0,32.67,38.0,M-SC,20.13,242.0,-0.55,1.12,46.21,XY24,NTT,MISC
45,INFY,-2.76,-18.66,72.59,40.38,222283.0,-70253.0,306217.0,1972.0,-38.68,52.0,X-LC,16.01,3.0,-0.32,1.96,15.96,X40,NTT,IT

In [12]:
# top 5 to exit based on CumlRnk
df_tmp = df_portfolio_features[~df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])]
df_tmp = df_tmp[(df_tmp['Current P/L%'] > -1) & (df_tmp['Current P/L%'] < 1)].sort_values(by = 'CumlRnk', ascending=False)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
80,UTIAMC,-0.24,-0.18,51.42,51.15,114118.0,-397.0,221933.0,1371.68,-19.83,47.0,M-SC,7.73,229.0,-0.0,1.42,3.96,XY24,ATH,FINANCE

In [13]:
# OX40N stocks to exit
df_tmp = df_portfolio_features[(df_portfolio_features['Symbol'].isin(list_ox40n))].sort_values(by = 'Current P/L%', ascending=False)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
25,FINCABLES,4.57,65.13,25.91,107.91,63171.0,96167.0,243811.0,1641.55,48.66,75.0,M-SC,18.91,220.0,1.52,1.56,83.43,OX40N,ATH,CABLES
68,SIS,-1.18,-2.48,24.35,21.26,26364.0,-2759.0,108273.0,528.00,2582.90,44.0,H-SC,21.95,168.0,-0.10,0.69,60.99,OX40N,NTT,MISC
43,INDIGOPNTS,1.40,-17.26,20.88,0.02,30158.0,-30124.0,144435.0,1408.00,120.42,69.0,M-SC,6.68,222.0,-1.00,0.92,63.87,OX40N,NTT,PAINTS
78,TTKPRESTIG,-0.59,-22.99,29.98,0.09,23266.0,-23173.0,77604.0,770.00,80.15,41.0,M-SC,10.51,250.0,-1.00,0.50,39.68,OX40N,NTT,DURABLES
16,CERA,-2.35,-24.35,63.76,23.89,84851.0,-42825.0,133078.0,9475.00,-26.97,35.0,H-SC,12.56,153.0,-0.50,0.85,29.36,OX40N,NTT,CERAMICS

In [14]:
# top 5 to book for rotation
df_tmp = df_portfolio_features[(df_portfolio_features['Current P/L%'] > 20) ].sort_values(by = 'CumlRnk', ascending=False)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
25,FINCABLES,4.57,65.13,25.91,107.91,63171.0,96167.0,243811.0,1641.55,48.66,75.0,M-SC,18.91,220.0,1.52,1.56,83.43,OX40N,ATH,CABLES
87,ZYDUSLIFE,0.47,20.27,12.67,35.51,31935.0,42476.0,252050.0,1285.01,4.50,52.0,H-MC,15.92,120.0,1.33,1.61,32.64,AR,ATH,PHARMA
57,QUESS,0.65,39.45,24.71,73.90,36798.0,42127.0,148920.0,424.00,-25.07,71.0,X-SC,43.20,80.0,1.14,0.95,104.97,XY24,NTT,MISC

In [15]:
# top 5 to monitor for exit
df_tmp = df_portfolio_features[~df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])]
df_tmp = df_tmp[(df_tmp['Current P/L%'] > 0) ].sort_values(by = 'Dev%_PE', ascending=False)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
69,STARHEALTH,0.18,13.44,29.82,47.26,95094.0,37770.0,318893.0,761.00,78.95,52.0,H-SC,16.54,173.0,0.40,2.04,37.88,XY24,NTT,INSURANCE
25,FINCABLES,4.57,65.13,25.91,107.91,63171.0,96167.0,243811.0,1641.55,48.66,75.0,M-SC,18.91,220.0,1.52,1.56,83.43,OX40N,ATH,CABLES
87,ZYDUSLIFE,0.47,20.27,12.67,35.51,31935.0,42476.0,252050.0,1285.01,4.50,52.0,H-MC,15.92,120.0,1.33,1.61,32.64,AR,ATH,PHARMA

In [16]:
# top 5 to book for rotation from weak conviction
df_tmp = df_portfolio_features[~df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])]
df_tmp = df_tmp[~df_tmp['Criteria'].isin(['XY25','XY24','X40', 'X40N'])].sort_values(by = 'RRR Ind', ascending=False)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
25,FINCABLES,4.57,65.13,25.91,107.91,63171.0,96167.0,243811.0,1641.55,48.66,75.0,M-SC,18.91,220.0,1.52,1.56,83.43,OX40N,ATH,CABLES
87,ZYDUSLIFE,0.47,20.27,12.67,35.51,31935.0,42476.0,252050.0,1285.01,4.50,52.0,H-MC,15.92,120.0,1.33,1.61,32.64,AR,ATH,PHARMA
68,SIS,-1.18,-2.48,24.35,21.26,26364.0,-2759.0,108273.0,528.00,2582.90,44.0,H-SC,21.95,168.0,-0.10,0.69,60.99,OX40N,NTT,MISC
3,ALKYLAMINE,0.29,-17.86,134.40,92.54,111463.0,-18029.0,82934.0,4520.85,-12.07,58.0,H-SC,14.06,142.0,-0.16,0.53,57.48,SR,ATH,CHEMICALS
42,INDIAMART,-0.94,-23.81,163.71,100.92,153837.0,-29367.0,93969.0,4675.60,-65.62,40.0,H-SC,13.37,140.0,-0.19,0.60,1.72,AR,ATH,MISC

In [17]:
# top 5 to accumulate based on lowest RSI_14
df_tmp = df_portfolio_features[df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])].sort_values(by = 'RSI_14', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
28,GODREJCP,-0.57,-15.49,57.26,32.90,120752.0,-38654.0,210883.0,1460.96,-12.53,31.0,X-LC,5.71,32.0,-0.32,1.35,2.65,X40N,ATH,FMCG
34,HDFCBANK,-0.28,-11.45,48.00,31.05,124584.0,-33570.0,259550.0,1073.00,-26.46,33.0,X-LC,12.64,26.0,-0.27,1.66,0.74,X40,BTT,BANKS
56,PGHH,-0.47,-37.16,110.06,32.01,147683.0,-79336.0,134184.0,17616.87,-57.46,33.0,X-MC,19.60,57.0,-0.54,0.86,0.00,X40,ATH,FMCG
55,PAGEIND,0.71,-3.47,38.39,33.59,99457.0,-9309.0,259070.0,51217.29,-30.79,33.0,X-MC,8.65,55.0,-0.09,1.65,23.03,X40,ATH,APPARELS
20,DABUR,-0.00,-20.77,81.37,43.70,159929.0,-51522.0,196546.0,735.00,-28.15,35.0,X-MC,9.84,70.0,-0.32,1.25,0.01,XY24,BTT,FMCG

In [18]:
# top 5 to accumulate based on Spread and CumlRnk
df_tmp = df_portfolio_features[df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])]
df_tmp = df_tmp[(df_tmp['CumlRnk'] < 100)].sort_values(by = 'Spread%', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
19,COLPAL,-0.66,-25.27,87.17,39.86,171551.0,-66565.0,196800.0,3683.41,-9.66,37.0,X-MC,1.60,62.0,-0.39,1.26,11.32,XY25,ATH,FMCG
23,DMART,-0.82,-1.85,33.90,31.42,103741.0,-5768.0,306022.0,5391.45,-18.35,50.0,X-LC,2.47,14.0,-0.06,1.95,10.43,X40N,ATH,FMCG
50,KOTAKBANK,0.23,3.04,15.41,18.92,38061.0,7290.0,246992.0,452.46,-10.27,52.0,X-LC,2.64,12.0,0.19,1.58,11.13,X40,ATH,BANKS
26,GILLETTE,-0.15,-10.34,44.68,29.72,101716.0,-26241.0,227655.0,10978.86,-31.02,41.0,X-SC,3.37,83.0,-0.26,1.45,4.62,X40,ATH,FMCG
84,VOLTAS,-2.70,0.51,44.46,45.20,85683.0,978.0,192720.0,1856.00,15.04,45.0,X-MC,3.91,79.0,0.01,1.23,5.62,XY25,NTT,AC

In [19]:
# top 5 to accumulate based on lowest Gained%
df_tmp = df_portfolio_features[df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])].sort_values(by = 'Gained%', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
56,PGHH,-0.47,-37.16,110.06,32.01,147683.0,-79336.0,134184.0,17616.87,-57.46,33.0,X-MC,19.60,57.0,-0.54,0.86,0.00,X40,ATH,FMCG
20,DABUR,-0.00,-20.77,81.37,43.70,159929.0,-51522.0,196546.0,735.00,-28.15,35.0,X-MC,9.84,70.0,-0.32,1.25,0.01,XY24,BTT,FMCG
47,ITC,-0.84,-23.90,63.86,24.70,193069.0,-94946.0,302332.0,452.00,-59.97,38.0,X-LC,10.78,1.0,-0.49,1.93,0.11,X40,NTT,FMCG
34,HDFCBANK,-0.28,-11.45,48.00,31.05,124584.0,-33570.0,259550.0,1073.00,-26.46,33.0,X-LC,12.64,26.0,-0.27,1.66,0.74,X40,BTT,BANKS
35,HDFCLIFE,1.05,-7.14,49.84,39.15,116050.0,-17892.0,232845.0,811.41,-30.91,43.0,X-LC,16.63,31.0,-0.15,1.49,1.05,X40,ATH,INSURANCE

In [20]:
# top 5 to accumulate based on lowest CurrAlloc%
df_tmp = df_portfolio_features[df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])].sort_values(by = 'CurrAlloc%', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
10,BATAINDIA,-1.16,-51.82,180.63,35.20,111978.0,-66677.0,61993.0,2096.00,-18.70,64.0,X-SC,12.34,91.0,-0.60,0.40,24.55,X40,NTT,FOOTWEAR
61,RELAXO,-1.39,-49.39,200.96,52.31,147627.0,-71699.0,73461.0,1176.00,-46.08,44.0,X-SC,13.29,92.0,-0.49,0.47,64.25,X40N,NTT,FOOTWEAR
56,PGHH,-0.47,-37.16,110.06,32.01,147683.0,-79336.0,134184.0,17616.87,-57.46,33.0,X-MC,19.60,57.0,-0.54,0.86,0.00,X40,ATH,FMCG
57,QUESS,0.65,39.45,24.71,73.90,36798.0,42127.0,148920.0,424.00,-25.07,71.0,X-SC,43.20,80.0,1.14,0.95,104.97,XY24,NTT,MISC
2,ACC,-1.01,-41.46,198.62,74.81,311754.0,-111168.0,156960.0,3906.00,-58.35,38.0,X-SC,11.78,85.0,-0.36,1.00,4.86,XY24,BTT,CEMENT

In [21]:
# top 5 to accumulate based on CumlRnk
df_tmp = df_portfolio_features.sort_values(by = 'CumlRnk', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
47,ITC,-0.84,-23.90,63.86,24.70,193069.0,-94946.0,302332.0,452.00,-59.97,38.0,X-LC,10.78,1.0,-0.49,1.93,0.11,X40,NTT,FMCG
74,TCS,-1.99,-32.07,82.83,24.20,260669.0,-148569.0,314704.0,4230.71,-42.64,49.0,X-LC,14.71,2.0,-0.57,2.01,17.36,X40,ATH,IT
45,INFY,-2.76,-18.66,72.59,40.38,222283.0,-70253.0,306217.0,1972.00,-38.68,52.0,X-LC,16.01,3.0,-0.32,1.96,15.96,X40,NTT,IT
76,TMPV,-1.17,-21.34,81.49,42.75,266712.0,-88813.0,327294.0,600.00,-84.72,41.0,X-LC,4.43,4.0,-0.33,2.09,12.54,XY24,NTT,AUTO
33,HCLTECH,-1.88,-10.75,38.90,23.97,107450.0,-33265.0,276221.0,1853.42,-9.02,59.0,X-LC,11.94,8.0,-0.31,1.76,30.34,X40,ATH,IT

In [22]:
# top 5 for average up
df_tmp = df_portfolio_features[(df_portfolio_features['Dev%_200'] > 5)].sort_values(by = 'CurrAlloc%', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
44,INDUSINDBK,-1.78,-25.69,78.84,32.89,45231.0,-19836.0,57370.0,1800.00,-370.31,51.0,L-MC,13.48,258.0,-0.44,0.37,41.44,XR,NTT,BANKS
61,RELAXO,-1.39,-49.39,200.96,52.31,147627.0,-71699.0,73461.0,1176.00,-46.08,44.0,X-SC,13.29,92.0,-0.49,0.47,64.25,X40N,NTT,FOOTWEAR
3,ALKYLAMINE,0.29,-17.86,134.40,92.54,111463.0,-18029.0,82934.0,4520.85,-12.07,58.0,H-SC,14.06,142.0,-0.16,0.53,57.48,SR,ATH,CHEMICALS
12,BOSCH-HCIL,-0.93,-28.19,39.25,-0.01,36021.0,-36032.0,91773.0,2282.00,18682.61,69.0,M-SC,5.61,231.0,-1.00,0.59,56.21,OX40N,BTT,AC
82,VALIANTORG,-4.99,-35.93,171.81,74.15,180095.0,-58783.0,104822.0,838.00,-288.40,58.0,H-SC,6.38,145.0,-0.33,0.67,55.99,XR,NTT,CHEMICALS

In [23]:
# top 5 RSP
df_tmp = df_portfolio_features.sort_values(by = 'RSP', ascending=False)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
25,FINCABLES,4.57,65.13,25.91,107.91,63171.0,96167.0,243811.0,1641.55,48.66,75.0,M-SC,18.91,220.0,1.52,1.56,83.43,OX40N,ATH,CABLES
12,BOSCH-HCIL,-0.93,-28.19,39.25,-0.01,36021.0,-36032.0,91773.0,2282.00,18682.61,69.0,M-SC,5.61,231.0,-1.00,0.59,56.21,OX40N,BTT,AC
57,QUESS,0.65,39.45,24.71,73.90,36798.0,42127.0,148920.0,424.00,-25.07,71.0,X-SC,43.20,80.0,1.14,0.95,104.97,XY24,NTT,MISC
82,VALIANTORG,-4.99,-35.93,171.81,74.15,180095.0,-58783.0,104822.0,838.00,-288.40,58.0,H-SC,6.38,145.0,-0.33,0.67,55.99,XR,NTT,CHEMICALS
11,BERGEPAINT,0.61,1.30,23.70,25.32,61883.0,3359.0,261108.0,680.00,-4.22,62.0,X-MC,4.13,68.0,0.05,1.67,36.92,XY24,NTT,PAINTS

In [24]:
# Top N allocation
df_tmp = df_portfolio_features.sort_values(by = 'CurrAlloc%', ascending=False)
top_n_values = [10, 25, 50]

sum_df = pd.DataFrame({
    'Top_N': top_n_values,
    'Sum_Alloc%': [df_tmp['CurrAlloc%'].head(n).sum() for n in top_n_values]
})

sum_df

   Top_N  Sum_Alloc%
0     10       19.64
1     25       44.80
2     50       76.96

In [25]:
# market-cap-wise allocation
df_tmp = df_portfolio_features[cols]
df_tmp.groupby(df_tmp['Conviction'].str[-2:])['CurrAlloc%'].sum().sort_values(ascending=False)

Conviction
SC    39.38
LC    37.56
MC    23.13
Name: CurrAlloc%, dtype: float64

In [26]:
# criteria-wise allocation
df_portfolio_features.groupby('Criteria')['CurrAlloc%'].sum().sort_values(ascending=False)

Criteria
X40      26.48
XY24     24.80
X40N     18.38
XR        9.04
OX40N     7.23
XY25      7.20
AR        6.08
SR        0.86
Name: CurrAlloc%, dtype: float64

In [27]:
# conviction-wise allocation
df_portfolio_features.groupby('Conviction')['CurrAlloc%'].sum().sort_values(ascending=False)

Conviction
X-LC    35.50
H-SC    19.10
X-MC    18.93
M-SC    11.23
X-SC     8.54
H-MC     2.65
H-LC     1.25
M-MC     1.18
M-LC     0.81
L-SC     0.51
L-MC     0.37
Name: CurrAlloc%, dtype: float64

In [28]:
# sector-wise stats
df_tmp = df_portfolio_features.groupby('Category')[['CurrAlloc%', 'Current', 'Current P/L', 'FTT Amt']].sum().sort_values(by=['Current', 'Current P/L'], ascending=False)
df_tmp['Current P/L%'] = round(df_tmp['Current P/L'] * 100 / df_tmp['Current'], 2)
df_tmp['FTT%'] = round(df_tmp['FTT Amt'] * 100 / df_tmp['Current'], 2)
cols = ['CurrAlloc%', 'Current P/L%', 'FTT%']
df_tmp[cols].sort_values(by=['CurrAlloc%'], ascending=False)

               CurrAlloc%  Current P/L%    FTT%
Category
FMCG                15.37        -23.79   68.30
IT                  11.08        -37.55  105.82
FINANCE             10.59        -16.53   66.73
AUTO                 8.24         -4.83   42.38
MISC                 6.89        -24.30   77.63
BANKS                6.08        -12.38   60.85
PHARMA               5.69          6.97   19.42
INSURANCE            5.68         -4.50   41.46
PAINTS               5.52        -14.01   33.46
ELECTRICAL           4.16         -8.49   46.47
AC                   1.82        -12.32   42.78
REFINERIES           1.69        -12.37   50.12
BREWERIES            1.69         11.41    6.98
FOOTWEAR             1.66        -70.24  138.51
APPARELS             1.65         -3.59   38.39
CABLES               1.56         39.44   25.91
DURABLES             1.48        -68.04  108.92
TRAVEL               1.42       -101.27  202.06
CERAMICS             1.33        -47.34   92.11
CHEMICALS            1.20        -40.91  155.29
ENGINEERING          1.19        -30.39   90.03
CEMENT               1.00        -70.83  198.62
JEWELLERY            0.95       -114.66  189.24
ENTERTAINMENT        0.69        -79.21  186.09
HEALTHCARE           0.68        -70.62  113.45
TEXTILES             0.39        -52.82   96.40
HOTELS               0.37        -98.12  168.01

In [29]:
# money to be made criteria-wise
df_portfolio_features.groupby('Criteria')['FTT Amt'].agg(['sum', 'count']).sort_values(by='sum', ascending=False)

                sum  count
Criteria
XY24      3630661.0     20
X40       2079989.0     18
XR        1386875.0     13
X40N      1202845.0     12
AR        1079906.0      8
OX40N      661412.0     10
XY25       571197.0      5
SR         282192.0      2

In [30]:
# money to be made conviction-wise
df_portfolio_features.groupby('Conviction')['FTT Amt'].agg(['sum', 'count']).sort_values(by='sum', ascending=False)

                  sum  count
Conviction
H-SC        3364989.0     23
X-LC        2499937.0     20
M-SC        1498135.0     15
X-MC        1489820.0     14
X-SC        1240142.0      8
H-MC         283012.0      2
L-SC         211383.0      2
M-LC         165751.0      1
M-MC          60588.0      1
L-MC          45231.0      1
H-LC          36089.0      1

In [31]:
# money to be made criteria and conviction-wise
df_portfolio_features.groupby(['Conviction', 'Criteria'])['FTT Amt'].agg(['sum', 'count']).sort_values(by='sum', ascending=False)

                           sum  count
Conviction Criteria
X-LC       X40       1202549.0      9
H-SC       XY24      1017134.0      5
M-SC       XY24       984248.0      7
H-SC       AR         936201.0      5
           XR         825704.0      7
X-SC       XY24       708427.0      3
X-MC       X40        663746.0      7
X-LC       X40N       537796.0      6
           XY24       447963.0      2
X-MC       X40N       347028.0      3
X-SC       X40N       318021.0      3
H-SC       OX40N      303758.0      4
           SR         282192.0      2
X-MC       XY25       257234.0      2
X-LC       XY25       253375.0      2
H-MC       XY24       251077.0      1
M-SC       OX40N      242561.0      5
X-MC       XY24       221812.0      2
X-SC       X40        213694.0      2
M-SC       XR         195645.0      2
M-LC       XR         165751.0      1
L-SC       OX40N      115093.0      1
           XR          96290.0      1
M-SC       AR          75681.0      1
M-MC       XY25        60588.0      1
X-LC       XR          58254.0      1
L-MC       XR          45231.0      1
H-LC       AR          36089.0      1
H-MC       AR          31935.0      1

In [32]:
# notebook execution time

end_time = time.time()
execution_time = round(end_time - start_time, 0)
print(f"Notebook execution time: {execution_time} seconds")

Notebook execution time: 38.0 seconds