<a href="https://colab.research.google.com/github/ankit-rathi/Quantvesting_v2/blob/main/myStocks_Portfolio_Analysis.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
'''
!pip install pandas==2.2.2 -qq
!pip install pyxirr -qq
!pip install ta -qq
!pip install yfinance==0.2.59 -qq
'''

'\n!pip install pandas==2.2.2 -qq\n!pip install pyxirr -qq\n!pip install ta -qq\n!pip install yfinance==0.2.59 -qq\n'

In [2]:
# import libraries

import numpy as np
import pandas as pd
import datetime
import warnings
warnings.filterwarnings('ignore')
import yfinance as yfin
import ta
import matplotlib.pyplot as plt
import requests

In [3]:
# notebook start time
import time
import datetime
import pytz

start_time = time.time()

# function to print date timestamp
def print_date_time():
  tz_NY = pytz.timezone('Asia/Kolkata')
  datetime_NY = datetime.datetime.now(tz_NY)
  print("Run date time (IST):", datetime_NY.strftime("%Y-%m-%d %H:%M:%S"))

In [4]:
# function to get booked and reserved amount
def get_amt():
  # fetch the JSON data from the URL
  url = "https://raw.githubusercontent.com/ankit-rathi/Tradevesting_v1/main/data/myPortfolioAmts.json"
  response = requests.get(url)
  pf_amts = response.json()  # parse the JSON data

  # extract values from the JSON
  py_booked_amt_dm = pf_amts["py_booked_amt_dm"]
  py_booked_amt_sv = pf_amts["py_booked_amt_sv"]
  cy_booked_amt_dm = pf_amts["cy_booked_amt_dm"]
  cy_booked_amt_sv = pf_amts["cy_booked_amt_sv"]
  reserve_amt_dm = pf_amts["reserve_amt_dm"]
  reserve_amt_sv = pf_amts["reserve_amt_sv"]

  # perform calculations
  py_booked_amt = py_booked_amt_dm + py_booked_amt_sv
  cy_booked_amt = cy_booked_amt_dm + cy_booked_amt_sv
  reserve_amt = reserve_amt_dm + reserve_amt_sv
  total_booked_amt = py_booked_amt + cy_booked_amt

  return total_booked_amt, reserve_amt, cy_booked_amt, py_booked_amt

gen_output = 0

In [5]:
# function to format the amount
def format_amt(number):
    abs_number = abs(number)

    if abs_number >= 1_00_00_000:  # Crores
        formatted_amt = f"{number / 1_00_00_000:.2f} C"
    elif abs_number >= 1_00_000:  # Lakhs
        formatted_amt = f"{number / 1_00_000:.2f} L"
    elif abs_number >= 1_000:  # Thousands
        formatted_amt = f"{number / 1_000:.2f} K"
    else:
        formatted_amt = f"{number:.2f}"

    return formatted_amt

# function to set start and end date
def get_start_end_date():
  start_date = (datetime.date.today() + datetime.timedelta(days=-365)).strftime('%Y-%m-%d')
  end_date = (datetime.date.today() + datetime.timedelta(days=1)).strftime('%Y-%m-%d')
  return start_date, end_date

# function to fetch my portfolio csv
def get_mypfs_df():
  mypfs_df = pd.read_csv('https://raw.githubusercontent.com/ankit-rathi/Tradevesting_v1/main/data/myPortfolioStocks.csv')
  return mypfs_df

# function to fetch my prospects csv
def get_mypps_df():
  mypps_df = pd.read_csv('https://raw.githubusercontent.com/ankit-rathi/Tradevesting_v1/main/data/myProspectsScrips.csv')
  return mypps_df

# function to fetch screener data
def get_myscreen_df():
  myscreen_df = pd.read_csv('https://raw.githubusercontent.com/ankit-rathi/Tradevesting_v1/main/data/myScreenerDB.csv')
  return myscreen_df

# function to fetch momentum data
def get_myinvmt_df():
  myinvmt_df = pd.read_csv('https://raw.githubusercontent.com/ankit-rathi/Tradevesting_v1/main/data/myInvestments.csv')
  return myinvmt_df

# function to get the stock ids
def get_stock_ids(df_pf):
  stock_n100 = df_pf['Symbol'].unique()

  exclude = ['CADILAHC','MMTC', 'MASFIN']

  stock_ids = df_pf[~df_pf['Symbol'].isin(exclude) ]['Symbol'].unique()

  #mypf = mypf[mypf.Forecast.notnull()]
  #stock_ids = mypf['Symbol'].unique()

  #stock_ids.sort()
  return stock_ids

# get features from screener data
def get_screener_features():
  myscreen_df = get_myscreen_df()
  cols = ['Symbol', 'EPS', 'MedPE', 'ROCE%', 'ROE%', 'CapType']
  return myscreen_df[cols]

# get relative strength
def get_relative_strength(stock_list):

    # Dictionary to store stock tickers and their corresponding percentage price change
    stock_changes = {}

    # Loop through each stock and fetch its price data
    for stock in stock_list:
        try:
            # Download the stock data for the given date range
            stock_data = yfin.Ticker(stock + '.NS').history(period='1mo', interval='1d')[map(str.title, ['open', 'close', 'low', 'high', 'volume'])]

            # Calculate the percentage change for the stock
            if len(stock_data) > 0:
                start_price = stock_data['Close'].iloc[0]
                end_price = stock_data['Close'].iloc[-1]
                percent_change = round(((end_price - start_price) / start_price) * 100, 2)
                stock_changes[stock] = percent_change
            else:
                stock_changes[stock] = np.nan  # If no data is available, set to NaN

        except Exception as e:
            print(f"Error fetching data for {stock}: {e}")
            stock_changes[stock] = np.nan

    # Create a DataFrame with stock tickers and their percentage changes
    df = pd.DataFrame(list(stock_changes.items()), columns=['Symbol', 'Percent_Change'])

    # Drop any stocks with missing data (NaN values)
    df = df.dropna()

    # Calculate the percentile rank based on percentage change
    df['RSP'] = round(df['Percent_Change'].rank(pct=True) * 100, 2)
    cols = ['Symbol', 'RSP']
    df = df[cols]
    # Sort by percentile rank (optional)
    df = df.sort_values(by='RSP', ascending=False).reset_index(drop=True)

    return df

In [6]:
# function to get stock technicals
def stock_prec_dev(stock_symbol):
    #stock_symbol = 'ULTRACEMCO.NS'
    short_window = 20
    mid_window = 50
    long_window = 200
    moving_avg = 'SMA'

    start = datetime.datetime(*map(int, start_date.split('-')))
    end = datetime.datetime(*map(int, end_date.split('-')))

    stock_df = yfin.Ticker(stock_symbol + '.NS').history(period='max', interval='1d')[map(str.title, ['open', 'close', 'low', 'high', 'volume'])]

    stock_df['Max'] = round(max(stock_df['Close']),2)
    stock_df = stock_df[(stock_df.index <= end_date) & (stock_df.index >= start_date)]
    stock_df['200_SMA'] = round(stock_df['Close'].rolling(window = 200, min_periods = 1).mean(),0)
    stock_df['Dev%_200'] = round((stock_df['Close'] - stock_df['200_SMA'])*100/stock_df['200_SMA'],2)
    stock_df.dropna(axis = 0, inplace = True) # remove any null rows

    stock_df['20_SMA'] = stock_df['Close'].rolling(window=20).mean()
    stock_df['50_SMA'] = stock_df['Close'].rolling(window=50).mean()
    stock_df['Symbol'] = stock_symbol

    stock_df['Close'] = round(stock_df['Close'],2)
    stock_df['Min'] = round(min(stock_df['Close']),2)
    stock_df['RSI_14'] = ta.momentum.RSIIndicator(close=stock_df['Close'], window=14).rsi()
    stock_df['RSI_14'] = round(stock_df['RSI_14'],0)
    stock_df['Prev_Close'] = stock_df['Close'].shift(1)
    stock_df.drop(['Open', 'Low', 'High', 'Volume'], axis=1, inplace=True)
    stock_df = stock_df.tail(1)

    max_SMA = max(stock_df['20_SMA'].item(), stock_df['50_SMA'].item(), stock_df['200_SMA'].item())
    min_SMA = min(stock_df['20_SMA'].item(), stock_df['50_SMA'].item(), stock_df['200_SMA'].item())
    ABS_Spread = max_SMA - min_SMA
    stock_df['Spread%'] = round((ABS_Spread / stock_df['200_SMA'].item()) * 100,2)

    return stock_df

# function to compute stock attributes
def get_common_features(stock_ids, df_mypf):

  df_prec_dev = pd.DataFrame()
  df_tmp = get_screener_features()
  df_rs = get_relative_strength(stock_ids)

  for stock_id in stock_ids:
      tmp = stock_prec_dev(stock_id)
      tmp = tmp.reset_index()
      df_prec_dev = pd.concat([df_prec_dev, tmp], ignore_index = True)
  df_prec_dev = pd.merge(df_prec_dev, df_mypf, on= 'Symbol')
  df_prec_dev = pd.merge(df_prec_dev, df_tmp, on= 'Symbol', how='left')
  df_prec_dev = pd.merge(df_prec_dev, df_rs, on= 'Symbol', how='left')
  #print(df_prec_dev.columns)
  df_prec_dev['Curr_PE'] = round(df_prec_dev['Close']/df_prec_dev['EPS'],1)
  df_prec_dev['Dev%_PE'] = round((df_prec_dev['Curr_PE'] - df_prec_dev['MedPE'])*100/df_prec_dev['MedPE'],2)
  df_prec_dev['Conviction'] = df_prec_dev['Conviction'] + '-' + df_prec_dev['CapType']
  return df_prec_dev

# function to arrange stock features
def arrange_features(df_stocks, common_cols, diff_cols):
  df_stocks_common = df_stocks[common_cols].drop_duplicates()
  df_stocks_diff = df_stocks[diff_cols]
  df_stocks_diff['Investment'] = df_stocks_diff['AvgCost'] * df_stocks_diff['Shares']
  df_stocks_diff = df_stocks_diff.groupby(['Symbol'])[['Shares', 'Investment']].aggregate(['sum']).reset_index()
  df_stocks_diff.columns = ['Symbol', 'Shares', 'Investment']
  df_stocks_diff['AvgCost'] = round(df_stocks_diff['Investment']/df_stocks_diff['Shares'],2)
  df_stocks = pd.merge(df_stocks_diff, df_stocks_common, on='Symbol')
  return df_stocks

# plot fact distribution across dimension
def plot_pie_chart(df, dimension, fact):
  # grouping the data by category and calculating the sum of fact for each type
  grouped_data = df.groupby(dimension)[fact].sum()

  # sorting the grouped data in descending order
  grouped_data = grouped_data.sort_values(ascending=False)

  # creating a pie chart
  grouped_data.plot.pie(autopct='%1.1f%%', startangle=90, figsize=(6, 6))

  # adding a title and displaying the plot
  plt.title(f'{dimension} {fact} Distribution')
  plt.ylabel('')  # To hide the y-label
  plt.show()

In [7]:
# function to get portfolio features

def get_portfolio_features(df_common_features):

  print_date_time()
  print('-------------------')

  #df_common_features["Target"] = df_common_features["Target"].fillna(df_common_features["Max"])
  df_common_features['NTT'] = np.where(df_common_features['Strategy']== 'NTT', df_common_features["Target"], df_common_features['Max'])
  df_common_features['LTT'] = np.where(df_common_features['Strategy']== 'BTT', df_common_features["Target"], df_common_features['Max'])
  df_common_features['BOL'] = df_common_features['Min']

  tmp_df = df_common_features[df_common_features['Symbol'].isin(mypf_df[mypf_df['InPortfolio'] != 'NA'].Symbol.values)]
  print('qualified stocks: '+str(len(tmp_df['Symbol'].unique())))
  tmp_df1 = tmp_df[tmp_df['LatestQtr'] == 1]
  print('with latest results: '+str(len(tmp_df1['Symbol'].unique())))
  tmp_df1 = tmp_df1[tmp_df1['StarStock'] == 1]
  print('still star stocks: '+str(len(tmp_df1['Symbol'].unique())))
  tmp_df['Investment'] = tmp_df['AvgCost'] * tmp_df['Shares']
  tmp_df['Current'] = round(tmp_df['Close'] * tmp_df['Shares'],0)
  tmp_df['Previous'] = tmp_df['Prev_Close'] * tmp_df['Shares']
  tmp_df['EstimatedST'] = tmp_df['NTT'] * tmp_df['Shares']
  tmp_df['EstimatedLT'] = tmp_df['LTT'] * tmp_df['Shares']
  tmp_df['Current P/L'] = round((tmp_df['Current'] - tmp_df['Investment']),0)
  tmp_df['Today P/L%'] = round((tmp_df['Current'] - tmp_df['Previous'])*100/tmp_df['Previous'],2)
  tmp_df['Current P/L%'] = round((tmp_df['Current'] - tmp_df['Investment'])*100/tmp_df['Investment'],2)
  tmp_df['EstimatedST P/L%'] = round((tmp_df['EstimatedST'] - tmp_df['Investment'])*100/tmp_df['Investment'],2)
  tmp_df['EstimatedLT P/L%'] = round((tmp_df['EstimatedLT'] - tmp_df['Investment'])*100/tmp_df['Investment'],2)
  tmp_df['NTT%'] = round((tmp_df['NTT'] - tmp_df['Close'])*100/tmp_df['Close'],2)
  tmp_df['LTT%'] = round((tmp_df['LTT'] - tmp_df['Close'])*100/tmp_df['Close'],2)
  tmp_df['Gained%'] = round((tmp_df['Close'] - tmp_df['BOL'])*100/tmp_df['BOL'],2)
  investment = round(sum(tmp_df['AvgCost']*tmp_df['Shares']),0)
  current = round(sum(tmp_df['Close']*tmp_df['Shares']),0)
  tmp_df['InitAlloc%'] = round(tmp_df['Investment']*100/investment,2)
  tmp_df['CurrAlloc%'] = round(tmp_df['Current']*100/current,2)
  tmp_df['FTT'] = tmp_df['LTT']
  tmp_df.loc[tmp_df['Strategy'] == 'NTT', 'FTT'] = tmp_df['NTT']
  tmp_df['FTT%'] = tmp_df['LTT%']
  tmp_df.loc[tmp_df['Strategy'] == 'NTT', 'FTT%'] = tmp_df['NTT%']
  tmp_df['FTT Amt'] = round(tmp_df['FTT%'] * tmp_df['Current']/100,0)
  tmp_df['OTT%'] = round((tmp_df['FTT'] - tmp_df['AvgCost'])*100/tmp_df['AvgCost'],2)
  tmp_df['RRR Ind'] = round(tmp_df['Current P/L']/tmp_df['FTT Amt'],2)
  tmp_df['Risk Ind'] = round(tmp_df['Current P/L%']*tmp_df['CurrAlloc%'],0)

  return tmp_df

# function to print portfolio features
def print_portfolio_stats(df_portfolio_features, myinvmt_df):
  from pyxirr import xirr

  total_booked_amt, reserve_amt, cy_booked_amt, py_booked_amt = get_amt()

  dates = myinvmt_df['Date'].values
  dates = np.append(dates, datetime.date.today().strftime('%d-%b-%y'))
  investment = myinvmt_df['Investment'].values
  dates= pd.to_datetime(dates)

  current = round(sum(df_portfolio_features['Close']*df_portfolio_features['Shares']),0) + reserve_amt
  investment_xirr = np.append(investment, current)
  cagr = round(xirr(pd.DataFrame({"dates": dates, "amounts": investment_xirr}))*100,2)

  investment = -sum(investment)
  invested = round(sum(df_portfolio_features['AvgCost']*df_portfolio_features['Shares']),0) + reserve_amt
  previous = round(sum(df_portfolio_features['Prev_Close']*df_portfolio_features['Shares']),0) + reserve_amt
  cy_invested = investment + py_booked_amt

  today_pnl_amount = current-previous
  today_pnl_percentage = round((current-previous)*100/previous,2)

  curr_pnl_amount = current-invested
  curr_pnl_percentage = round((curr_pnl_amount)*100/(cy_invested),2)

  cy_pnl_amount = cy_booked_amt + curr_pnl_amount
  cy_pnl_percentage = round((cy_pnl_amount)*100/cy_invested,2)

  overall_pnl_amount = total_booked_amt + curr_pnl_amount
  overall_pnl_percentage = round((overall_pnl_amount)*100/investment,2)

  estimate_st = round(sum(df_portfolio_features['FTT']*df_portfolio_features['Shares']),0)  + reserve_amt
  est_st_pnl_amount = estimate_st-current
  est_st_pnl_percentage = round((est_st_pnl_amount)*100/current,2)

  estimate_lt = round(sum(df_portfolio_features['LTT']*df_portfolio_features['Shares']),0)  + reserve_amt
  est_lt_pnl_amount = estimate_lt-current
  est_lt_pnl_percentage = round((est_lt_pnl_amount)*100/current,2)

  total_profit = round(sum(df_portfolio_features[df_portfolio_features['Current P/L%'] > 0]['Current']) - sum(df_portfolio_features[df_portfolio_features['Current P/L%'] > 0]['Investment']),0)
  total_loss = round(sum(df_portfolio_features[df_portfolio_features['Current P/L%'] < 0]['Current']) - sum(df_portfolio_features[df_portfolio_features['Current P/L%'] < 0]['Investment']),0)

  cy_booked_percentage = round((cy_booked_amt)*100/current,2)
  py_booked_percentage = round((py_booked_amt)*100/investment,2)
  total_booked_percentage = round((total_booked_amt)*100/investment,2)

  print('-------------------')
  print('Initial Investment: ', format_amt(investment))
  print('CY Investment: ', format_amt(cy_invested))
  print('Reserve: ', format_amt(reserve_amt))
  print('Current: ',  format_amt(current))
  print('-------------------')
  print('Today PnL: '+ '{} ({}%)'.format(format_amt(today_pnl_amount), today_pnl_percentage))
  print('Current PnL: '+ '{} ({}%)'.format(format_amt(curr_pnl_amount), curr_pnl_percentage))
  print('CY Booked + Current PnL: '+ '{} ({}%)'.format(format_amt(cy_pnl_amount), cy_pnl_percentage))
  print('-------------------')
  print('Total profit: ', format_amt(total_profit))
  print('Total loss: ', format_amt(total_loss))
  print('-------------------')
  print('Total Booked + Current PnL: '+ '{} ({}%)'.format(format_amt(overall_pnl_amount), overall_pnl_percentage))
  print('Total Booked PnL: '+ '{} ({}%)'.format(format_amt(total_booked_amt), total_booked_percentage))
  print('Curr Year Booked PnL: '+ '{} ({}%)'.format(format_amt(cy_booked_amt), cy_booked_percentage))
  print('Prev Year Booked PnL: '+ '{} ({}%)'.format(format_amt(py_booked_amt), py_booked_percentage))
  print('===================')
  print('Est FTT: ',  format_amt(estimate_st))
  print('Est FTT PnL: '+ '{} ({}%)'.format(format_amt(est_st_pnl_amount), est_st_pnl_percentage))

  print('===================')
  print('Deployed: ', format_amt(investment))

  print('Current: ', format_amt(current))

  print('CAGR/XIRR %: '+'{}%'.format(cagr))

In [8]:
# get start and end date
start_date, end_date = get_start_end_date()

# get portfolio and prospects data
mypfs_df = get_mypfs_df()
mypps_df = get_mypps_df()
myinvmt_df = get_myinvmt_df()

# merge above datasets
mypf_df = pd.merge(mypfs_df, mypps_df, on="Symbol")

# seggregate dm and sv portfolio
dm_pf = mypf_df[mypf_df['InPortfolio'] == 'DM']
sv_pf = mypf_df[mypf_df['InPortfolio'] == 'SV']

# build portfolio stock dataframe
dm_stocks = get_stock_ids(dm_pf)
sv_stocks = get_stock_ids(sv_pf)
df_stocks = pd.concat([dm_pf,sv_pf], ignore_index = True)

# arrange common and diff stock features
common_cols = ['Symbol', 'Target', 'Criteria', 'Strategy', 'CumlRnk', 'LatestQtr', 'StarStock', 'Conviction', 'Category', 'InFolio', 'XIRR', 'MBQ']
diff_cols = ['Symbol', 'AvgCost', 'Shares']
df_stocks = arrange_features(df_stocks, common_cols, diff_cols)

# get common features
stock_ids = df_stocks['Symbol'].values
df_common_features = get_common_features(stock_ids, df_stocks)

df_common_features.reset_index(drop=True, inplace=True)
df_common_features.drop(['Date'], axis=1, inplace=True)
# get and print portfolio features
df_portfolio_features = get_portfolio_features(df_common_features)

print_portfolio_stats(df_portfolio_features, myinvmt_df)

df = df_portfolio_features
#plot_pie_chart(df, 'CapType', 'Current')
list_ox40n = list(df[df['MBQ'].str.contains('OX40N', na=False)]['Symbol'].values)

Run date time (IST): 2026-04-03 12:48:16
-------------------
qualified stocks: 86
with latest results: 26
still star stocks: 16
-------------------
Initial Investment:  1.36 C
CY Investment:  1.62 C
Reserve:  1.61 K
Current:  1.29 C
-------------------
Today PnL: 55.26 K (0.43%)
Current PnL: -47.70 L (-29.36%)
CY Booked + Current PnL: -31.81 L (-19.58%)
-------------------
Total profit:  46.86 K
Total loss:  -48.17 L
-------------------
Total Booked + Current PnL: -4.83 L (-3.56%)
Total Booked PnL: 42.87 L (31.64%)
Curr Year Booked PnL: 15.89 L (12.28%)
Prev Year Booked PnL: 26.98 L (19.91%)
===================
Est FTT:  2.48 C
Est FTT PnL: 1.18 C (91.53%)
===================
Deployed:  1.36 C
Current:  1.29 C
CAGR/XIRR %: -2.22%

In [9]:
# top 5 near their targets
cols = ['Symbol', 'Today P/L%', 'Current P/L%', 'FTT%', 'OTT%', 'FTT Amt', 'Current P/L', 'Current', 'FTT', 'Dev%_PE', 'RSI_14','Conviction', 'Spread%',  'CumlRnk', 'RRR Ind', 'CurrAlloc%', 'Gained%', 'Criteria', 'Strategy', 'Category']
df_tmp = df_portfolio_features[~df_portfolio_features['Symbol'].isin(['ENRIN','BLUSPRING','DIGITIDE'])]
df_tmp = df_tmp.sort_values(by = 'FTT Amt', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
50,MASFIN,0.80,-9.49,34.32,21.57,30435.0,-9300.0,88680.0,397.04,-21.86,45.0,H-SC,4.89,167.0,-0.31,0.69,20.95,XR,ATH,FINANCE
77,TTKPRESTIG,-0.37,-42.34,73.60,0.09,42765.0,-42672.0,58105.0,770.00,34.90,38.0,M-SC,22.13,250.0,-1.00,0.45,3.46,OX40N,NTT,DURABLES
2,ABBOTINDIA,-0.77,-11.82,33.90,18.07,53464.0,-21145.0,157710.0,35195.00,-25.06,47.0,X-MC,10.43,58.0,-0.40,1.22,3.14,X40,ATH,PHARMA
67,SONACOMS,-0.14,-14.10,61.92,39.09,53806.0,-14263.0,86896.0,804.02,-31.95,48.0,M-MC,6.74,193.0,-0.27,0.67,22.93,AR,ATH,AUTO
42,INDUSINDBK,-0.88,-42.51,131.15,32.89,58212.0,-32820.0,44386.0,1800.00,-308.68,38.0,L-MC,6.70,258.0,-0.56,0.34,15.21,XR,NTT,BANKS

In [10]:
# top 5 today
df_tmp = df_portfolio_features.sort_values(by = 'Today P/L%', ascending=False)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
15,BSOFT,6.06,-32.77,124.27,50.79,117518.0,-46086.0,94567.0,831.70,-13.80,51.0,H-SC,8.33,172.0,-0.39,0.73,11.52,XR,ATH,IT
0,5PAISA,5.61,-45.67,107.79,12.90,127966.0,-99778.0,118718.0,593.00,75.48,46.0,H-SC,16.49,170.0,-0.78,0.92,14.56,OX40N,NTT,FINANCE
55,RAJESHEXPO,4.83,-83.14,493.49,0.07,114139.0,-114048.0,23129.0,518.00,747.22,27.0,L-SC,42.39,268.0,-1.00,0.18,8.58,OX40N,NTT,JEWELLERY
12,BATAINDIA,4.63,-57.61,218.95,35.20,119422.0,-74127.0,54543.0,2096.00,-28.52,39.0,X-SC,34.00,91.0,-0.62,0.42,8.17,X40,NTT,FOOTWEAR
52,PAGEIND,4.06,-11.46,51.48,34.11,122324.0,-30764.0,237615.0,51418.64,-36.57,62.0,X-MC,20.31,55.0,-0.25,1.84,12.40,X40,ATH,APPARELS

In [11]:
# bottom 5 today
df_tmp = df_portfolio_features.sort_values(by = 'Today P/L%', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
19,COFFEEDAY,-7.64,-62.77,263.31,35.27,111322.0,-71271.0,42278.0,80.00,-71.83,35.0,L-SC,31.51,266.0,-0.64,0.33,4.26,XR,NTT,HOTELS
23,DIXON,-3.25,-27.73,90.83,37.92,171205.0,-72308.0,188490.0,18931.72,-69.27,44.0,X-MC,27.82,54.0,-0.42,1.46,2.56,X40N,ATH,IT
47,JSWINFRA,-2.70,-17.87,41.76,16.43,76063.0,-39630.0,182144.0,342.00,-29.52,42.0,X-MC,11.90,61.0,-0.52,1.41,0.19,X40N,NTT,REALTY
6,ASIANPAINT,-2.55,-21.95,59.53,24.52,131703.0,-62201.0,221238.0,3460.26,-21.27,41.0,X-LC,11.57,30.0,-0.47,1.71,2.25,X40,ATH,PAINTS
78,UNITDSPR,-2.25,-10.29,34.62,20.77,72718.0,-24098.0,210046.0,1644.00,-20.49,37.0,X-MC,3.74,64.0,-0.33,1.62,0.20,X40N,NTT,BREWERIES

In [12]:
# top 5 to exit based on CumlRnk
df_tmp = df_portfolio_features[~df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])]
df_tmp = df_tmp[(df_tmp['Current P/L%'] > -1) & (df_tmp['Current P/L%'] < 1)].sort_values(by = 'CumlRnk', ascending=False)
df_tmp[cols].head()

Empty DataFrame
Columns: [Symbol, Today P/L%, Current P/L%, FTT%, OTT%, FTT Amt, Current P/L, Current, FTT, Dev%_PE, RSI_14, Conviction, Spread%, CumlRnk, RRR Ind, CurrAlloc%, Gained%, Criteria, Strategy, Category]
Index: []

In [13]:
# OX40N stocks to exit
df_tmp = df_portfolio_features[(df_portfolio_features['Symbol'].isin(list_ox40n))].sort_values(by = 'Current P/L%', ascending=False)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
26,FINCABLES,-0.14,1.03,105.80,107.91,157812.0,1517.0,149161.0,1641.55,-9.18,44.0,M-SC,5.65,220.0,0.01,1.15,12.22,OX40N,ATH,CABLES
66,SIS,0.16,-33.89,83.43,21.26,61239.0,-37630.0,73402.0,528.00,1718.65,48.0,H-SC,14.73,168.0,-0.61,0.57,9.14,OX40N,NTT,MISC
18,CERA,0.21,-38.84,102.57,23.89,110343.0,-68325.0,107578.0,9475.00,-41.05,46.0,H-SC,19.29,153.0,-0.62,0.83,3.38,OX40N,NTT,CERAMICS
72,TATAELXSI,2.77,-38.87,116.00,32.03,93479.0,-51250.0,80585.0,9161.00,-23.56,45.0,H-SC,21.76,158.0,-0.55,0.62,6.66,OX40N,NTT,IT
48,KANSAINER,1.73,-40.39,90.37,13.47,145261.0,-108927.0,160740.0,340.00,-48.71,46.0,H-SC,23.10,162.0,-0.75,1.24,12.28,XY24,NTT,PAINTS

In [14]:
# top 5 to book for rotation
df_tmp = df_portfolio_features[(df_portfolio_features['Current P/L%'] > 20) ].sort_values(by = 'CumlRnk', ascending=False)
df_tmp[cols].head()

Empty DataFrame
Columns: [Symbol, Today P/L%, Current P/L%, FTT%, OTT%, FTT Amt, Current P/L, Current, FTT, Dev%_PE, RSI_14, Conviction, Spread%, CumlRnk, RRR Ind, CurrAlloc%, Gained%, Criteria, Strategy, Category]
Index: []

In [15]:
# top 5 to monitor for exit
df_tmp = df_portfolio_features[~df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])]
df_tmp = df_tmp[(df_tmp['Current P/L%'] > 0) ].sort_values(by = 'Dev%_PE', ascending=False)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
26,FINCABLES,-0.14,1.03,105.80,107.91,157812.0,1517.0,149161.0,1641.55,-9.18,44.0,M-SC,5.65,220.0,0.01,1.15,12.22,OX40N,ATH,CABLES
1,ABB,1.30,12.69,29.18,45.57,86027.0,33197.0,294816.0,7934.00,-27.57,53.0,H-MC,13.34,125.0,0.39,2.28,30.92,AR,NTT,ELECTRICAL

In [16]:
# top 5 to book for rotation from weak conviction
df_tmp = df_portfolio_features[~df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])]
df_tmp = df_tmp[~df_tmp['Criteria'].isin(['XY25','XY24','X40', 'X40N'])].sort_values(by = 'RRR Ind', ascending=False)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
1,ABB,1.30,12.69,29.18,45.57,86027.0,33197.0,294816.0,7934.00,-27.57,53.0,H-MC,13.34,125.0,0.39,2.28,30.92,AR,NTT,ELECTRICAL
26,FINCABLES,-0.14,1.03,105.80,107.91,157812.0,1517.0,149161.0,1641.55,-9.18,44.0,M-SC,5.65,220.0,0.01,1.15,12.22,OX40N,ATH,CABLES
40,INDIAMART,-0.98,-13.24,138.28,106.72,147962.0,-16334.0,107002.0,4810.62,-60.94,43.0,H-SC,12.94,140.0,-0.11,0.83,7.04,AR,ATH,MISC
85,ZYDUSLIFE,0.12,-8.86,48.82,35.63,93246.0,-18575.0,190999.0,1286.17,-20.72,41.0,H-MC,5.64,120.0,-0.20,1.48,6.33,AR,ATH,PHARMA
84,WIPRO,1.95,-20.06,115.48,72.27,156432.0,-33986.0,135462.0,420.00,-27.84,45.0,M-LC,18.16,98.0,-0.22,1.05,3.93,XR,NTT,IT

In [17]:
# top 5 to accumulate based on lowest RSI_14
df_tmp = df_portfolio_features[df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])].sort_values(by = 'RSI_14', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
38,ICICIPRULI,-1.94,-16.70,56.93,30.73,93427.0,-32897.0,164108.0,790.00,-39.03,19.0,X-MC,8.72,78.0,-0.35,1.27,0.00,X40,ATH,INSURANCE
37,ICICIGI,-0.34,-10.53,33.38,19.34,59765.0,-21064.0,179045.0,2252.93,-24.74,28.0,X-MC,5.97,66.0,-0.35,1.38,0.00,X40,ATH,INSURANCE
21,DABUR,0.55,-18.42,76.15,43.70,154102.0,-45702.0,202366.0,735.00,-25.93,30.0,X-MC,10.93,70.0,-0.30,1.56,1.66,XY24,BTT,FMCG
32,HAVELLS,-0.45,-24.41,74.73,32.08,185275.0,-80065.0,247926.0,2062.85,-28.94,30.0,X-MC,11.29,63.0,-0.43,1.92,0.00,X40,ATH,ELECTRICAL
34,HDFCBANK,1.17,-10.17,42.90,28.37,90520.0,-23882.0,211003.0,1073.00,-23.49,33.0,X-LC,15.50,26.0,-0.26,1.63,2.65,X40,BTT,BANKS

In [18]:
# top 5 to accumulate based on Spread and CumlRnk
df_tmp = df_portfolio_features[df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])]
df_tmp = df_tmp[(df_tmp['CumlRnk'] < 100)].sort_values(by = 'Spread%', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
65,SIEMENS,0.32,-18.68,54.35,25.51,82248.0,-34765.0,151330.0,4671.50,27.11,44.0,H-LC,0.37,51.0,-0.42,1.17,11.44,AR,ATH,ELECTRICAL
82,VOLTAS,-1.14,-3.35,50.23,45.20,93081.0,-6432.0,185310.0,1856.00,10.70,33.0,X-MC,2.99,79.0,-0.07,1.43,3.21,XY25,NTT,AC
78,UNITDSPR,-2.25,-10.29,34.62,20.77,72718.0,-24098.0,210046.0,1644.00,-20.49,37.0,X-MC,3.74,64.0,-0.33,1.62,0.20,X40N,NTT,BREWERIES
59,RELIANCE,-1.37,-13.31,44.54,25.30,77595.0,-26749.0,174214.0,1952.00,-15.42,40.0,X-LC,3.88,21.0,-0.34,1.35,16.32,XY25,BTT,REFINERIES
37,ICICIGI,-0.34,-10.53,33.38,19.34,59765.0,-21064.0,179045.0,2252.93,-24.74,28.0,X-MC,5.97,66.0,-0.35,1.38,0.00,X40,ATH,INSURANCE

In [19]:
# top 5 to accumulate based on lowest Gained%
df_tmp = df_portfolio_features[df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])].sort_values(by = 'Gained%', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
37,ICICIGI,-0.34,-10.53,33.38,19.34,59765.0,-21064.0,179045.0,2252.93,-24.74,28.0,X-MC,5.97,66.0,-0.35,1.38,0.00,X40,ATH,INSURANCE
38,ICICIPRULI,-1.94,-16.70,56.93,30.73,93427.0,-32897.0,164108.0,790.00,-39.03,19.0,X-MC,8.72,78.0,-0.35,1.27,0.00,X40,ATH,INSURANCE
32,HAVELLS,-0.45,-24.41,74.73,32.08,185275.0,-80065.0,247926.0,2062.85,-28.94,30.0,X-MC,11.29,63.0,-0.43,1.92,0.00,X40,ATH,ELECTRICAL
47,JSWINFRA,-2.70,-17.87,41.76,16.43,76063.0,-39630.0,182144.0,342.00,-29.52,42.0,X-MC,11.90,61.0,-0.52,1.41,0.19,X40N,NTT,REALTY
78,UNITDSPR,-2.25,-10.29,34.62,20.77,72718.0,-24098.0,210046.0,1644.00,-20.49,37.0,X-MC,3.74,64.0,-0.33,1.62,0.20,X40N,NTT,BREWERIES

In [20]:
# top 5 to accumulate based on lowest CurrAlloc%
df_tmp = df_portfolio_features[df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])].sort_values(by = 'CurrAlloc%', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
58,RELAXO,2.69,-65.36,339.71,52.31,170810.0,-94879.0,50281.0,1176.00,-63.12,38.0,X-SC,31.39,92.0,-0.56,0.39,12.42,X40N,NTT,FOOTWEAR
12,BATAINDIA,4.63,-57.61,218.95,35.20,119422.0,-74127.0,54543.0,2096.00,-28.52,39.0,X-SC,34.00,91.0,-0.62,0.42,8.17,X40,NTT,FOOTWEAR
54,QUESS,1.47,-26.63,137.00,73.90,107350.0,-28435.0,78358.0,424.00,-60.33,45.0,X-SC,22.32,80.0,-0.26,0.61,5.41,XY24,NTT,MISC
36,HONAUT,-1.48,-30.29,117.06,51.31,157358.0,-58413.0,134425.0,58357.33,-41.98,33.0,X-SC,17.97,90.0,-0.37,1.04,2.13,X40N,ATH,ELECTRICAL
51,MEDANTA,1.13,-14.42,48.54,27.12,73325.0,-25457.0,151060.0,1486.00,-17.09,40.0,X-SC,15.16,87.0,-0.35,1.17,4.09,XY24,NTT,HEALTHCARE

In [21]:
# top 5 to accumulate based on CumlRnk
df_tmp = df_portfolio_features.sort_values(by = 'CumlRnk', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
45,ITC,0.39,-22.86,54.35,19.06,142611.0,-77772.0,262394.0,452.00,-57.54,38.0,X-LC,19.70,1.0,-0.55,2.03,1.79,X40,NTT,FMCG
73,TCS,1.76,-28.06,75.93,26.57,253071.0,-129978.0,333295.0,4311.59,-39.04,43.0,X-LC,18.58,2.0,-0.51,2.58,4.02,X40,ATH,IT
43,INFY,1.97,-11.45,51.60,34.24,142968.0,-35818.0,277070.0,1972.00,-30.33,49.0,X-LC,14.96,3.0,-0.25,2.14,6.55,X40,NTT,IT
75,TMPV,0.12,-30.96,97.82,36.58,240317.0,-110168.0,245673.0,600.00,-85.81,37.0,X-LC,11.19,4.0,-0.46,1.90,2.40,XY24,NTT,AUTO
33,HCLTECH,3.53,-9.00,36.09,23.83,79450.0,-21779.0,220145.0,1908.19,-4.47,53.0,X-LC,11.46,8.0,-0.27,1.70,6.89,X40,ATH,IT

In [22]:
# top 5 for average up
df_tmp = df_portfolio_features[(df_portfolio_features['Dev%_200'] > 5)].sort_values(by = 'CurrAlloc%', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
24,DMART,2.14,4.87,23.59,29.60,61745.0,12144.0,261744.0,5391.45,-11.57,73.0,X-LC,6.35,14.0,0.20,2.02,19.64,X40N,ATH,FMCG
1,ABB,1.30,12.69,29.18,45.57,86027.0,33197.0,294816.0,7934.00,-27.57,53.0,H-MC,13.34,125.0,0.39,2.28,30.92,AR,NTT,ELECTRICAL

In [23]:
# top 5 RSP
df_tmp = df_portfolio_features.sort_values(by = 'RSP', ascending=False)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
24,DMART,2.14,4.87,23.59,29.60,61745.0,12144.0,261744.0,5391.45,-11.57,73.0,X-LC,6.35,14.0,0.20,2.02,19.64,X40N,ATH,FMCG
30,HAPPSTMNDS,0.10,-50.92,276.63,84.85,174011.0,-65261.0,62904.0,1480.71,-41.60,52.0,H-SC,24.35,152.0,-0.38,0.49,16.49,AR,ATH,IT
52,PAGEIND,4.06,-11.46,51.48,34.11,122324.0,-30764.0,237615.0,51418.64,-36.57,62.0,X-MC,20.31,55.0,-0.25,1.84,12.40,X40,ATH,APPARELS
5,ANGELONE,0.10,-1.29,25.80,24.18,77674.0,-3938.0,301062.0,303.00,-85.87,55.0,X-SC,9.59,97.0,-0.05,2.33,15.88,X40N,NTT,FINANCE
80,VALIANTORG,0.69,-51.71,260.66,74.15,205919.0,-84606.0,78999.0,838.00,-242.23,51.0,H-SC,27.62,145.0,-0.41,0.61,17.56,XR,NTT,CHEMICALS

In [24]:
# Top N allocation
df_tmp = df_portfolio_features.sort_values(by = 'CurrAlloc%', ascending=False)
top_n_values = [10, 25, 50]

sum_df = pd.DataFrame({
    'Top_N': top_n_values,
    'Sum_Alloc%': [df_tmp['CurrAlloc%'].head(n).sum() for n in top_n_values]
})

sum_df

   Top_N  Sum_Alloc%
0     10       21.17
1     25       46.29
2     50       78.11

In [25]:
# market-cap-wise allocation
df_tmp = df_portfolio_features[cols]
df_tmp.groupby(df_tmp['Conviction'].str[-2:])['CurrAlloc%'].sum().sort_values(ascending=False)

Conviction
SC    44.62
MC    29.62
LC    25.81
Name: CurrAlloc%, dtype: float64

In [26]:
# criteria-wise allocation
df_portfolio_features.groupby('Criteria')['CurrAlloc%'].sum().sort_values(ascending=False)

Criteria
XY24     27.08
X40      25.41
X40N     15.42
AR        9.18
XR        8.30
XY25      7.17
OX40N     6.69
SR        0.80
Name: CurrAlloc%, dtype: float64

In [27]:
# conviction-wise allocation
df_portfolio_features.groupby('Conviction')['CurrAlloc%'].sum().sort_values(ascending=False)

Conviction
X-LC    23.59
X-MC    22.18
H-SC    21.82
X-SC    12.37
M-SC     9.92
H-MC     5.05
M-MC     2.05
H-LC     1.17
M-LC     1.05
L-SC     0.51
L-MC     0.34
Name: CurrAlloc%, dtype: float64

In [28]:
# sector-wise stats
df_tmp = df_portfolio_features.groupby('Category')[['CurrAlloc%', 'Current', 'Current P/L', 'FTT Amt']].sum().sort_values(by=['Current', 'Current P/L'], ascending=False)
df_tmp['Current P/L%'] = round(df_tmp['Current P/L'] * 100 / df_tmp['Current'], 2)
df_tmp['FTT%'] = round(df_tmp['FTT Amt'] * 100 / df_tmp['Current'], 2)
cols = ['CurrAlloc%', 'Current P/L%', 'FTT%']
df_tmp[cols].sort_values(by=['CurrAlloc%'], ascending=False)

               CurrAlloc%  Current P/L%    FTT%
Category
FMCG                15.31        -26.02   70.76
FINANCE             13.18        -26.07   77.45
IT                  12.13        -43.65  116.75
MISC                 7.04        -47.39  111.42
ELECTRICAL           6.41        -16.90   61.67
PAINTS               5.24        -45.40   70.65
INSURANCE            4.63        -13.27   52.03
BANKS                4.48        -32.73  100.11
PHARMA               4.13        -10.14   44.80
AUTO                 3.64        -38.71   93.74
AC                   1.92        -28.44   63.27
HEALTHCARE           1.92        -44.41   82.10
APPARELS             1.84        -12.95   51.48
FOOTWEAR             1.82        -87.36  162.48
TRAVEL               1.78        -94.26  191.52
DURABLES             1.77        -69.29  110.47
BREWERIES            1.62        -11.47   34.62
REALTY               1.41        -21.76   41.76
CERAMICS             1.37        -73.26  125.89
REFINERIES           1.35        -15.35   44.54
CEMENT               1.23        -68.52  194.59
CABLES               1.15          1.02  105.80
ENGINEERING          1.08        -72.74  151.75
CHEMICALS            1.05        -94.94  253.98
JEWELLERY            1.00       -147.38  233.33
ENTERTAINMENT        0.76        -95.74  212.47
TEXTILES             0.46        -54.85   99.00
HOTELS               0.33       -168.58  263.31

In [29]:
# money to be made criteria-wise
df_portfolio_features.groupby('Criteria')['FTT Amt'].agg(['sum', 'count']).sort_values(by='sum', ascending=False)

                sum  count
Criteria
XY24      4093582.0     21
X40       1887284.0     16
XR        1417117.0     12
AR        1385306.0     10
X40N      1306344.0     10
OX40N      927144.0     10
XY25       512750.0      5
SR         316156.0      2

In [30]:
# money to be made conviction-wise
df_portfolio_features.groupby('Conviction')['FTT Amt'].agg(['sum', 'count']).sort_values(by='sum', ascending=False)

                  sum  count
Conviction
H-SC        3969895.0     24
X-MC        1864152.0     15
X-LC        1725341.0     13
M-SC        1634383.0     14
X-SC        1582962.0     10
H-MC         426123.0      3
L-SC         225461.0      2
M-LC         156432.0      1
M-MC         120474.0      2
H-LC          82248.0      1
L-MC          58212.0      1

In [31]:
# money to be made criteria and conviction-wise
df_portfolio_features.groupby(['Conviction', 'Criteria'])['FTT Amt'].agg(['sum', 'count']).sort_values(by='sum', ascending=False)

                           sum  count
Conviction Criteria
H-SC       XY24      1372459.0      6
           AR         989995.0      5
M-SC       XY24       941528.0      6
X-LC       X40        933132.0      7
H-SC       XR         898258.0      7
X-SC       XY24       859959.0      4
X-MC       X40        732387.0      7
           X40N       572418.0      4
X-SC       X40N       501238.0      4
M-SC       OX40N      419978.0      5
X-LC       XY24       396257.0      2
H-SC       OX40N      393027.0      4
           SR         316156.0      2
X-MC       XY25       282818.0      2
           XY24       276529.0      2
H-MC       XY24       246850.0      1
X-LC       X40N       232688.0      2
X-SC       X40        221765.0      2
M-SC       XR         192893.0      2
H-MC       AR         179273.0      2
X-LC       XY25       163264.0      2
M-LC       XR         156432.0      1
L-SC       OX40N      114139.0      1
           XR         111322.0      1
H-LC       AR          82248.0      1
M-SC       AR          79984.0      1
M-MC       XY25        66668.0      1
L-MC       XR          58212.0      1
M-MC       AR          53806.0      1

In [32]:
# notebook execution time

end_time = time.time()
execution_time = round(end_time - start_time, 0)
print(f"Notebook execution time: {execution_time} seconds")

Notebook execution time: 23.0 seconds