<a href="https://colab.research.google.com/github/ankit-rathi/Quantvesting_v2/blob/main/myStocks_Portfolio_Analysis.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
'''
!pip install pandas==2.2.2 -qq
!pip install pyxirr -qq
!pip install ta -qq
!pip install yfinance==0.2.59 -qq
'''

'\n!pip install pandas==2.2.2 -qq\n!pip install pyxirr -qq\n!pip install ta -qq\n!pip install yfinance==0.2.59 -qq\n'

In [2]:
# import libraries

import numpy as np
import pandas as pd
import datetime
import warnings
warnings.filterwarnings('ignore')
import yfinance as yfin
import ta
import matplotlib.pyplot as plt
import requests

In [3]:
# notebook start time
import time
import datetime
import pytz

start_time = time.time()

# function to print date timestamp
def print_date_time():
  tz_NY = pytz.timezone('Asia/Kolkata')
  datetime_NY = datetime.datetime.now(tz_NY)
  print("Run date time (IST):", datetime_NY.strftime("%Y-%m-%d %H:%M:%S"))

In [4]:
# function to get booked and reserved amount
def get_amt():
  # fetch the JSON data from the URL
  url = "https://raw.githubusercontent.com/ankit-rathi/Tradevesting_v1/main/data/myPortfolioAmts.json"
  response = requests.get(url)
  pf_amts = response.json()  # parse the JSON data

  # extract values from the JSON
  py_booked_amt_dm = pf_amts["py_booked_amt_dm"]
  py_booked_amt_sv = pf_amts["py_booked_amt_sv"]
  cy_booked_amt_dm = pf_amts["cy_booked_amt_dm"]
  cy_booked_amt_sv = pf_amts["cy_booked_amt_sv"]
  reserve_amt_dm = pf_amts["reserve_amt_dm"]
  reserve_amt_sv = pf_amts["reserve_amt_sv"]

  # perform calculations
  py_booked_amt = py_booked_amt_dm + py_booked_amt_sv
  cy_booked_amt = cy_booked_amt_dm + cy_booked_amt_sv
  reserve_amt = reserve_amt_dm + reserve_amt_sv
  total_booked_amt = py_booked_amt + cy_booked_amt

  return total_booked_amt, reserve_amt, cy_booked_amt, py_booked_amt

gen_output = 0

In [5]:
# function to format the amount
def format_amt(number):
    abs_number = abs(number)

    if abs_number >= 1_00_00_000:  # Crores
        formatted_amt = f"{number / 1_00_00_000:.2f} C"
    elif abs_number >= 1_00_000:  # Lakhs
        formatted_amt = f"{number / 1_00_000:.2f} L"
    elif abs_number >= 1_000:  # Thousands
        formatted_amt = f"{number / 1_000:.2f} K"
    else:
        formatted_amt = f"{number:.2f}"

    return formatted_amt

# function to set start and end date
def get_start_end_date():
  start_date = (datetime.date.today() + datetime.timedelta(days=-365)).strftime('%Y-%m-%d')
  end_date = (datetime.date.today() + datetime.timedelta(days=1)).strftime('%Y-%m-%d')
  return start_date, end_date

# function to fetch my portfolio csv
def get_mypfs_df():
  mypfs_df = pd.read_csv('https://raw.githubusercontent.com/ankit-rathi/Tradevesting_v1/main/data/myPortfolioStocks.csv')
  return mypfs_df

# function to fetch my prospects csv
def get_mypps_df():
  mypps_df = pd.read_csv('https://raw.githubusercontent.com/ankit-rathi/Tradevesting_v1/main/data/myProspectsScrips.csv')
  return mypps_df

# function to fetch screener data
def get_myscreen_df():
  myscreen_df = pd.read_csv('https://raw.githubusercontent.com/ankit-rathi/Tradevesting_v1/main/data/myScreenerDB.csv')
  return myscreen_df

# function to fetch momentum data
def get_myinvmt_df():
  myinvmt_df = pd.read_csv('https://raw.githubusercontent.com/ankit-rathi/Tradevesting_v1/main/data/myInvestments.csv')
  return myinvmt_df

# function to get the stock ids
def get_stock_ids(df_pf):
  stock_n100 = df_pf['Symbol'].unique()

  exclude = ['CADILAHC','MMTC', 'MASFIN']

  stock_ids = df_pf[~df_pf['Symbol'].isin(exclude) ]['Symbol'].unique()

  #mypf = mypf[mypf.Forecast.notnull()]
  #stock_ids = mypf['Symbol'].unique()

  #stock_ids.sort()
  return stock_ids

# get features from screener data
def get_screener_features():
  myscreen_df = get_myscreen_df()
  cols = ['Symbol', 'EPS', 'MedPE', 'ROCE%', 'ROE%', 'CapType']
  return myscreen_df[cols]

# get relative strength
def get_relative_strength(stock_list):

    # Dictionary to store stock tickers and their corresponding percentage price change
    stock_changes = {}

    # Loop through each stock and fetch its price data
    for stock in stock_list:
        try:
            # Download the stock data for the given date range
            stock_data = yfin.Ticker(stock + '.NS').history(period='1mo', interval='1d')[map(str.title, ['open', 'close', 'low', 'high', 'volume'])]

            # Calculate the percentage change for the stock
            if len(stock_data) > 0:
                start_price = stock_data['Close'].iloc[0]
                end_price = stock_data['Close'].iloc[-1]
                percent_change = round(((end_price - start_price) / start_price) * 100, 2)
                stock_changes[stock] = percent_change
            else:
                stock_changes[stock] = np.nan  # If no data is available, set to NaN

        except Exception as e:
            print(f"Error fetching data for {stock}: {e}")
            stock_changes[stock] = np.nan

    # Create a DataFrame with stock tickers and their percentage changes
    df = pd.DataFrame(list(stock_changes.items()), columns=['Symbol', 'Percent_Change'])

    # Drop any stocks with missing data (NaN values)
    df = df.dropna()

    # Calculate the percentile rank based on percentage change
    df['RSP'] = round(df['Percent_Change'].rank(pct=True) * 100, 2)
    cols = ['Symbol', 'RSP']
    df = df[cols]
    # Sort by percentile rank (optional)
    df = df.sort_values(by='RSP', ascending=False).reset_index(drop=True)

    return df

In [6]:
# function to get stock technicals
def stock_prec_dev(stock_symbol):
    #stock_symbol = 'ULTRACEMCO.NS'
    short_window = 20
    mid_window = 50
    long_window = 200
    moving_avg = 'SMA'

    start = datetime.datetime(*map(int, start_date.split('-')))
    end = datetime.datetime(*map(int, end_date.split('-')))

    stock_df = yfin.Ticker(stock_symbol + '.NS').history(period='max', interval='1d')[map(str.title, ['open', 'close', 'low', 'high', 'volume'])]

    stock_df['Max'] = round(max(stock_df['Close']),2)
    stock_df = stock_df[(stock_df.index <= end_date) & (stock_df.index >= start_date)]
    stock_df['200_SMA'] = round(stock_df['Close'].rolling(window = 200, min_periods = 1).mean(),0)
    stock_df['Dev%_200'] = round((stock_df['Close'] - stock_df['200_SMA'])*100/stock_df['200_SMA'],2)
    stock_df.dropna(axis = 0, inplace = True) # remove any null rows

    stock_df['20_SMA'] = stock_df['Close'].rolling(window=20).mean()
    stock_df['50_SMA'] = stock_df['Close'].rolling(window=50).mean()
    stock_df['Symbol'] = stock_symbol

    stock_df['Close'] = round(stock_df['Close'],2)
    stock_df['Min'] = round(min(stock_df['Close']),2)
    stock_df['RSI_14'] = ta.momentum.RSIIndicator(close=stock_df['Close'], window=14).rsi()
    stock_df['RSI_14'] = round(stock_df['RSI_14'],0)
    stock_df['Prev_Close'] = stock_df['Close'].shift(1)
    stock_df.drop(['Open', 'Low', 'High', 'Volume'], axis=1, inplace=True)
    stock_df = stock_df.tail(1)

    max_SMA = max(stock_df['20_SMA'].item(), stock_df['50_SMA'].item(), stock_df['200_SMA'].item())
    min_SMA = min(stock_df['20_SMA'].item(), stock_df['50_SMA'].item(), stock_df['200_SMA'].item())
    ABS_Spread = max_SMA - min_SMA
    stock_df['Spread%'] = round((ABS_Spread / stock_df['200_SMA'].item()) * 100,2)

    return stock_df

# function to compute stock attributes
def get_common_features(stock_ids, df_mypf):

  df_prec_dev = pd.DataFrame()
  df_tmp = get_screener_features()
  df_rs = get_relative_strength(stock_ids)

  for stock_id in stock_ids:
      tmp = stock_prec_dev(stock_id)
      tmp = tmp.reset_index()
      df_prec_dev = pd.concat([df_prec_dev, tmp], ignore_index = True)
  df_prec_dev = pd.merge(df_prec_dev, df_mypf, on= 'Symbol')
  df_prec_dev = pd.merge(df_prec_dev, df_tmp, on= 'Symbol', how='left')
  df_prec_dev = pd.merge(df_prec_dev, df_rs, on= 'Symbol', how='left')
  #print(df_prec_dev.columns)
  df_prec_dev['Curr_PE'] = round(df_prec_dev['Close']/df_prec_dev['EPS'],1)
  df_prec_dev['Dev%_PE'] = round((df_prec_dev['Curr_PE'] - df_prec_dev['MedPE'])*100/df_prec_dev['MedPE'],2)
  df_prec_dev['Conviction'] = df_prec_dev['Conviction'] + '-' + df_prec_dev['CapType']
  return df_prec_dev

# function to arrange stock features
def arrange_features(df_stocks, common_cols, diff_cols):
  df_stocks_common = df_stocks[common_cols].drop_duplicates()
  df_stocks_diff = df_stocks[diff_cols]
  df_stocks_diff['Investment'] = df_stocks_diff['AvgCost'] * df_stocks_diff['Shares']
  df_stocks_diff = df_stocks_diff.groupby(['Symbol'])[['Shares', 'Investment']].aggregate(['sum']).reset_index()
  df_stocks_diff.columns = ['Symbol', 'Shares', 'Investment']
  df_stocks_diff['AvgCost'] = round(df_stocks_diff['Investment']/df_stocks_diff['Shares'],2)
  df_stocks = pd.merge(df_stocks_diff, df_stocks_common, on='Symbol')
  return df_stocks

# plot fact distribution across dimension
def plot_pie_chart(df, dimension, fact):
  # grouping the data by category and calculating the sum of fact for each type
  grouped_data = df.groupby(dimension)[fact].sum()

  # sorting the grouped data in descending order
  grouped_data = grouped_data.sort_values(ascending=False)

  # creating a pie chart
  grouped_data.plot.pie(autopct='%1.1f%%', startangle=90, figsize=(6, 6))

  # adding a title and displaying the plot
  plt.title(f'{dimension} {fact} Distribution')
  plt.ylabel('')  # To hide the y-label
  plt.show()

In [7]:
# function to get portfolio features

def get_portfolio_features(df_common_features):

  print_date_time()
  print('-------------------')

  #df_common_features["Target"] = df_common_features["Target"].fillna(df_common_features["Max"])
  df_common_features['NTT'] = np.where(df_common_features['Strategy']== 'NTT', df_common_features["Target"], df_common_features['Max'])
  df_common_features['LTT'] = np.where(df_common_features['Strategy']== 'BTT', df_common_features["Target"], df_common_features['Max'])
  df_common_features['BOL'] = df_common_features['Min']

  tmp_df = df_common_features[df_common_features['Symbol'].isin(mypf_df[mypf_df['InPortfolio'] != 'NA'].Symbol.values)]
  print('qualified stocks: '+str(len(tmp_df['Symbol'].unique())))
  tmp_df1 = tmp_df[tmp_df['LatestQtr'] == 1]
  print('with latest results: '+str(len(tmp_df1['Symbol'].unique())))
  tmp_df1 = tmp_df1[tmp_df1['StarStock'] == 1]
  print('still star stocks: '+str(len(tmp_df1['Symbol'].unique())))
  tmp_df['Investment'] = tmp_df['AvgCost'] * tmp_df['Shares']
  tmp_df['Current'] = round(tmp_df['Close'] * tmp_df['Shares'],0)
  tmp_df['Previous'] = tmp_df['Prev_Close'] * tmp_df['Shares']
  tmp_df['EstimatedST'] = tmp_df['NTT'] * tmp_df['Shares']
  tmp_df['EstimatedLT'] = tmp_df['LTT'] * tmp_df['Shares']
  tmp_df['Current P/L'] = round((tmp_df['Current'] - tmp_df['Investment']),0)
  tmp_df['Today P/L%'] = round((tmp_df['Current'] - tmp_df['Previous'])*100/tmp_df['Previous'],2)
  tmp_df['Current P/L%'] = round((tmp_df['Current'] - tmp_df['Investment'])*100/tmp_df['Investment'],2)
  tmp_df['EstimatedST P/L%'] = round((tmp_df['EstimatedST'] - tmp_df['Investment'])*100/tmp_df['Investment'],2)
  tmp_df['EstimatedLT P/L%'] = round((tmp_df['EstimatedLT'] - tmp_df['Investment'])*100/tmp_df['Investment'],2)
  tmp_df['NTT%'] = round((tmp_df['NTT'] - tmp_df['Close'])*100/tmp_df['Close'],2)
  tmp_df['LTT%'] = round((tmp_df['LTT'] - tmp_df['Close'])*100/tmp_df['Close'],2)
  tmp_df['Gained%'] = round((tmp_df['Close'] - tmp_df['BOL'])*100/tmp_df['BOL'],2)
  investment = round(sum(tmp_df['AvgCost']*tmp_df['Shares']),0)
  current = round(sum(tmp_df['Close']*tmp_df['Shares']),0)
  tmp_df['InitAlloc%'] = round(tmp_df['Investment']*100/investment,2)
  tmp_df['CurrAlloc%'] = round(tmp_df['Current']*100/current,2)
  tmp_df['FTT'] = tmp_df['LTT']
  tmp_df.loc[tmp_df['Strategy'] == 'NTT', 'FTT'] = tmp_df['NTT']
  tmp_df['FTT%'] = tmp_df['LTT%']
  tmp_df.loc[tmp_df['Strategy'] == 'NTT', 'FTT%'] = tmp_df['NTT%']
  tmp_df['FTT Amt'] = round(tmp_df['FTT%'] * tmp_df['Current']/100,0)
  tmp_df['OTT%'] = round((tmp_df['FTT'] - tmp_df['AvgCost'])*100/tmp_df['AvgCost'],2)
  tmp_df['RRR Ind'] = round(tmp_df['Current P/L']/tmp_df['FTT Amt'],2)
  tmp_df['Risk Ind'] = round(tmp_df['Current P/L%']*tmp_df['CurrAlloc%'],0)

  return tmp_df

# function to print portfolio features
def print_portfolio_stats(df_portfolio_features, myinvmt_df):
  from pyxirr import xirr

  total_booked_amt, reserve_amt, cy_booked_amt, py_booked_amt = get_amt()

  dates = myinvmt_df['Date'].values
  dates = np.append(dates, datetime.date.today().strftime('%d-%b-%y'))
  investment = myinvmt_df['Investment'].values
  dates= pd.to_datetime(dates)

  current = round(sum(df_portfolio_features['Close']*df_portfolio_features['Shares']),0) + reserve_amt
  investment_xirr = np.append(investment, current)
  cagr = round(xirr(pd.DataFrame({"dates": dates, "amounts": investment_xirr}))*100,2)

  investment = -sum(investment)
  invested = round(sum(df_portfolio_features['AvgCost']*df_portfolio_features['Shares']),0) + reserve_amt
  previous = round(sum(df_portfolio_features['Prev_Close']*df_portfolio_features['Shares']),0) + reserve_amt
  cy_invested = investment + py_booked_amt

  today_pnl_amount = current-previous
  today_pnl_percentage = round((current-previous)*100/previous,2)

  curr_pnl_amount = current-invested
  curr_pnl_percentage = round((curr_pnl_amount)*100/(cy_invested),2)

  cy_pnl_amount = cy_booked_amt + curr_pnl_amount
  cy_pnl_percentage = round((cy_pnl_amount)*100/cy_invested,2)

  overall_pnl_amount = total_booked_amt + curr_pnl_amount
  overall_pnl_percentage = round((overall_pnl_amount)*100/investment,2)

  estimate_st = round(sum(df_portfolio_features['FTT']*df_portfolio_features['Shares']),0)  + reserve_amt
  est_st_pnl_amount = estimate_st-current
  est_st_pnl_percentage = round((est_st_pnl_amount)*100/current,2)

  estimate_lt = round(sum(df_portfolio_features['LTT']*df_portfolio_features['Shares']),0)  + reserve_amt
  est_lt_pnl_amount = estimate_lt-current
  est_lt_pnl_percentage = round((est_lt_pnl_amount)*100/current,2)

  total_profit = round(sum(df_portfolio_features[df_portfolio_features['Current P/L%'] > 0]['Current']) - sum(df_portfolio_features[df_portfolio_features['Current P/L%'] > 0]['Investment']),0)
  total_loss = round(sum(df_portfolio_features[df_portfolio_features['Current P/L%'] < 0]['Current']) - sum(df_portfolio_features[df_portfolio_features['Current P/L%'] < 0]['Investment']),0)

  cy_booked_percentage = round((cy_booked_amt)*100/current,2)
  py_booked_percentage = round((py_booked_amt)*100/investment,2)
  total_booked_percentage = round((total_booked_amt)*100/investment,2)

  print('-------------------')
  print('Initial Investment: ', format_amt(investment))
  print('CY Investment: ', format_amt(cy_invested))
  print('Reserve: ', format_amt(reserve_amt))
  print('Current: ',  format_amt(current))
  print('-------------------')
  print('Today PnL: '+ '{} ({}%)'.format(format_amt(today_pnl_amount), today_pnl_percentage))
  print('Current PnL: '+ '{} ({}%)'.format(format_amt(curr_pnl_amount), curr_pnl_percentage))
  print('CY Booked + Current PnL: '+ '{} ({}%)'.format(format_amt(cy_pnl_amount), cy_pnl_percentage))
  print('-------------------')
  print('Total profit: ', format_amt(total_profit))
  print('Total loss: ', format_amt(total_loss))
  print('-------------------')
  print('Total Booked + Current PnL: '+ '{} ({}%)'.format(format_amt(overall_pnl_amount), overall_pnl_percentage))
  print('Total Booked PnL: '+ '{} ({}%)'.format(format_amt(total_booked_amt), total_booked_percentage))
  print('Curr Year Booked PnL: '+ '{} ({}%)'.format(format_amt(cy_booked_amt), cy_booked_percentage))
  print('Prev Year Booked PnL: '+ '{} ({}%)'.format(format_amt(py_booked_amt), py_booked_percentage))
  print('===================')
  print('Est FTT: ',  format_amt(estimate_st))
  print('Est FTT PnL: '+ '{} ({}%)'.format(format_amt(est_st_pnl_amount), est_st_pnl_percentage))

  print('===================')
  print('Deployed: ', format_amt(investment))

  print('Current: ', format_amt(current))

  print('CAGR/XIRR %: '+'{}%'.format(cagr))

In [8]:
# get start and end date
start_date, end_date = get_start_end_date()

# get portfolio and prospects data
mypfs_df = get_mypfs_df()
mypps_df = get_mypps_df()
myinvmt_df = get_myinvmt_df()

# merge above datasets
mypf_df = pd.merge(mypfs_df, mypps_df, on="Symbol")

# seggregate dm and sv portfolio
dm_pf = mypf_df[mypf_df['InPortfolio'] == 'DM']
sv_pf = mypf_df[mypf_df['InPortfolio'] == 'SV']

# build portfolio stock dataframe
dm_stocks = get_stock_ids(dm_pf)
sv_stocks = get_stock_ids(sv_pf)
df_stocks = pd.concat([dm_pf,sv_pf], ignore_index = True)

# arrange common and diff stock features
common_cols = ['Symbol', 'Target', 'Criteria', 'Strategy', 'CumlRnk', 'LatestQtr', 'StarStock', 'Conviction', 'Category', 'InFolio', 'XIRR', 'MBQ']
diff_cols = ['Symbol', 'AvgCost', 'Shares']
df_stocks = arrange_features(df_stocks, common_cols, diff_cols)

# get common features
stock_ids = df_stocks['Symbol'].values
df_common_features = get_common_features(stock_ids, df_stocks)

df_common_features.reset_index(drop=True, inplace=True)
df_common_features.drop(['Date'], axis=1, inplace=True)
# get and print portfolio features
df_portfolio_features = get_portfolio_features(df_common_features)

print_portfolio_stats(df_portfolio_features, myinvmt_df)

df = df_portfolio_features
#plot_pie_chart(df, 'CapType', 'Current')
list_ox40n = list(df[df['MBQ'].str.contains('OX40N', na=False)]['Symbol'].values)

Run date time (IST): 2026-03-02 13:56:40
-------------------
qualified stocks: 86
with latest results: 26
still star stocks: 15
-------------------
Initial Investment:  1.33 C
CY Investment:  1.60 C
Reserve:  2.44 L
Current:  1.33 C
-------------------
Today PnL: -3.86 L (-2.81%)
Current PnL: -41.23 L (-25.77%)
CY Booked + Current PnL: -25.55 L (-15.97%)
-------------------
Total profit:  1.08 L
Total loss:  -42.31 L
-------------------
Total Booked + Current PnL: 1.43 L (1.07%)
Total Booked PnL: 42.66 L (32.07%)
Curr Year Booked PnL: 15.68 L (11.77%)
Prev Year Booked PnL: 26.98 L (20.29%)
===================
Est FTT:  2.41 C
Est FTT PnL: 1.08 C (80.96%)
===================
Deployed:  1.33 C
Current:  1.33 C
CAGR/XIRR %: 0.08%

In [9]:
# top 5 near their targets
cols = ['Symbol', 'Today P/L%', 'Current P/L%', 'FTT%', 'OTT%', 'FTT Amt', 'Current P/L', 'Current', 'FTT', 'Dev%_PE', 'RSI_14','Conviction', 'Spread%',  'CumlRnk', 'RRR Ind', 'CurrAlloc%', 'Gained%', 'Criteria', 'Strategy', 'Category']
df_tmp = df_portfolio_features[~df_portfolio_features['Symbol'].isin(['ENRIN','BLUSPRING','DIGITIDE'])]
df_tmp = df_tmp.sort_values(by = 'FTT Amt', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
19,COALINDIA,-2.26,3.50,13.69,17.67,21320.0,5272.0,155733.0,478.51,24.82,49.0,L-LC,10.79,185.0,0.25,1.19,25.01,XY25,ATH,MINING
50,MASFIN,-3.19,-3.86,26.45,21.57,24916.0,-3780.0,94200.0,397.04,-16.89,41.0,H-SC,6.67,167.0,-0.15,0.72,37.47,XR,ATH,FINANCE
77,TTKPRESTIG,-2.79,-33.95,51.54,0.09,34306.0,-34216.0,66561.0,770.00,54.54,27.0,M-SC,12.01,250.0,-1.00,0.51,0.00,OX40N,NTT,DURABLES
37,ICICIGI,-2.31,0.72,18.48,19.34,37248.0,1450.0,201559.0,2252.93,-15.18,48.0,X-MC,1.09,66.0,0.04,1.54,16.78,X40,ATH,INSURANCE
51,MEDANTA,-0.68,-5.56,31.39,24.08,37632.0,-7064.0,119886.0,1486.00,-6.15,48.0,X-SC,7.95,87.0,-0.19,0.92,9.81,XY24,NTT,HEALTHCARE

In [10]:
# top 5 today
df_tmp = df_portfolio_features.sort_values(by = 'Today P/L%', ascending=False)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
27,FINCABLES,2.33,18.42,75.57,107.91,132130.0,27201.0,174845.0,1641.55,6.54,77.0,M-SC,6.70,220.0,0.21,1.34,31.54,OX40N,ATH,CABLES
2,ABBOTINDIA,1.06,-10.06,31.28,18.07,50317.0,-17995.0,160860.0,35195.00,-23.42,48.0,X-MC,11.50,58.0,-0.36,1.23,1.98,X40,ATH,PHARMA
63,SFL,0.46,-45.88,134.00,26.63,190146.0,-120318.0,141900.0,1287.00,7.45,43.0,M-SC,12.20,242.0,-0.63,1.09,8.92,XY24,NTT,MISC
66,SIS,0.03,-29.86,72.89,21.26,56765.0,-33155.0,77877.0,528.00,1829.53,41.0,H-SC,5.92,168.0,-0.58,0.60,7.36,OX40N,NTT,MISC
44,IRCTC,-0.33,-31.59,123.55,52.93,228634.0,-85454.0,185054.0,1269.00,-49.35,30.0,H-MC,12.27,119.0,-0.37,1.42,0.00,XY24,BTT,TRAVEL

In [11]:
# bottom 5 today
df_tmp = df_portfolio_features.sort_values(by = 'Today P/L%', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
26,EASEMYTRIP,-8.24,-56.35,233.75,45.70,180422.0,-99629.0,77186.0,26.4,-19.77,50.0,M-SC,18.12,204.0,-0.55,0.59,27.17,XY24,NTT,TRAVEL
69,SURYODAY,-6.88,-29.94,75.62,23.03,94865.0,-53621.0,125450.0,216.0,35.96,43.0,H-SC,5.90,166.0,-0.57,0.96,24.47,XR,NTT,BANKS
58,RELAXO,-6.71,-57.94,262.12,52.31,160032.0,-84107.0,61053.0,1176.0,-55.18,25.0,X-SC,15.49,92.0,-0.53,0.47,0.00,X40N,NTT,FOOTWEAR
74,TITAGARH,-5.38,-37.56,133.40,45.74,201729.0,-90956.0,151221.0,1548.0,-16.76,21.0,H-SC,12.09,175.0,-0.45,1.16,0.00,XY24,NTT,ENGINEERING
76,TRIDENT,-5.32,-35.15,98.18,28.51,58734.0,-32432.0,59823.0,48.0,-16.51,35.0,M-SC,9.03,223.0,-0.55,0.46,2.37,XR,NTT,TEXTILES

In [12]:
# top 5 to exit based on CumlRnk
df_tmp = df_portfolio_features[~df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])]
df_tmp = df_tmp[(df_tmp['Current P/L%'] > -1) & (df_tmp['Current P/L%'] < 1)].sort_values(by = 'CumlRnk', ascending=False)
df_tmp[cols].head()

Empty DataFrame
Columns: [Symbol, Today P/L%, Current P/L%, FTT%, OTT%, FTT Amt, Current P/L, Current, FTT, Dev%_PE, RSI_14, Conviction, Spread%, CumlRnk, RRR Ind, CurrAlloc%, Gained%, Criteria, Strategy, Category]
Index: []

In [13]:
# OX40N stocks to exit
df_tmp = df_portfolio_features[(df_portfolio_features['Symbol'].isin(list_ox40n))].sort_values(by = 'Current P/L%', ascending=False)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
27,FINCABLES,2.33,18.42,75.57,107.91,132130.0,27201.0,174845.0,1641.55,6.54,77.0,M-SC,6.70,220.0,0.21,1.34,31.54,OX40N,ATH,CABLES
66,SIS,0.03,-29.86,72.89,21.26,56765.0,-33155.0,77877.0,528.00,1829.53,41.0,H-SC,5.92,168.0,-0.58,0.60,7.36,OX40N,NTT,MISC
77,TTKPRESTIG,-2.79,-33.95,51.54,0.09,34306.0,-34216.0,66561.0,770.00,54.54,27.0,M-SC,12.01,250.0,-1.00,0.51,0.00,OX40N,NTT,DURABLES
48,KANSAINER,-4.58,-35.19,75.10,13.47,131246.0,-94905.0,174762.0,340.00,-44.35,30.0,H-SC,13.47,162.0,-0.72,1.34,0.00,XY24,NTT,PAINTS
41,INDIGOPNTS,-3.50,-35.78,55.75,0.02,62494.0,-62463.0,112096.0,1408.00,70.76,22.0,M-SC,12.69,222.0,-1.00,0.86,0.00,OX40N,NTT,PAINTS

In [14]:
# top 5 to book for rotation
df_tmp = df_portfolio_features[(df_portfolio_features['Current P/L%'] > 20) ].sort_values(by = 'CumlRnk', ascending=False)
df_tmp[cols].head()

Empty DataFrame
Columns: [Symbol, Today P/L%, Current P/L%, FTT%, OTT%, FTT Amt, Current P/L, Current, FTT, Dev%_PE, RSI_14, Conviction, Spread%, CumlRnk, RRR Ind, CurrAlloc%, Gained%, Criteria, Strategy, Category]
Index: []

In [15]:
# top 5 to monitor for exit
df_tmp = df_portfolio_features[~df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])]
df_tmp = df_tmp[(df_tmp['Current P/L%'] > 0) ].sort_values(by = 'Dev%_PE', ascending=False)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
19,COALINDIA,-2.26,3.50,13.69,17.67,21320.0,5272.0,155733.0,478.51,24.82,49.0,L-LC,10.79,185.0,0.25,1.19,25.01,XY25,ATH,MINING
27,FINCABLES,2.33,18.42,75.57,107.91,132130.0,27201.0,174845.0,1641.55,6.54,77.0,M-SC,6.70,220.0,0.21,1.34,31.54,OX40N,ATH,CABLES
1,ABB,-2.72,8.40,34.29,45.57,97241.0,21965.0,283584.0,7934.00,-30.32,57.0,H-MC,8.91,125.0,0.23,2.17,25.93,AR,NTT,ELECTRICAL

In [16]:
# top 5 to book for rotation from weak conviction
df_tmp = df_portfolio_features[~df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])]
df_tmp = df_tmp[~df_tmp['Criteria'].isin(['XY25','XY24','X40', 'X40N'])].sort_values(by = 'RRR Ind', ascending=False)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
1,ABB,-2.72,8.40,34.29,45.57,97241.0,21965.0,283584.0,7934.00,-30.32,57.0,H-MC,8.91,125.0,0.23,2.17,25.93,AR,NTT,ELECTRICAL
27,FINCABLES,2.33,18.42,75.57,107.91,132130.0,27201.0,174845.0,1641.55,6.54,77.0,M-SC,6.70,220.0,0.21,1.34,31.54,OX40N,ATH,CABLES
40,INDIAMART,-1.50,-9.76,129.08,106.72,143666.0,-12036.0,111300.0,4810.62,-59.38,35.0,H-SC,8.20,140.0,-0.08,0.85,11.34,AR,ATH,MISC
85,ZYDUSLIFE,-2.61,-5.35,43.29,35.63,85874.0,-11204.0,198370.0,1286.17,-17.57,47.0,H-MC,4.92,120.0,-0.13,1.52,10.43,AR,ATH,PHARMA
50,MASFIN,-3.19,-3.86,26.45,21.57,24916.0,-3780.0,94200.0,397.04,-16.89,41.0,H-SC,6.67,167.0,-0.15,0.72,37.47,XR,ATH,FINANCE

In [17]:
# top 5 to accumulate based on lowest RSI_14
df_tmp = df_portfolio_features[df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])].sort_values(by = 'RSI_14', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
8,AWL,-4.81,-41.66,169.43,57.19,322376.0,-135856.0,190271.0,485.00,-66.62,13.0,X-SC,19.48,81.0,-0.42,1.46,0.0,XY24,NTT,FMCG
12,BATAINDIA,-3.86,-51.07,176.33,35.20,111010.0,-65714.0,62956.0,2096.00,-17.40,22.0,X-SC,22.67,91.0,-0.59,0.48,0.0,X40,NTT,FOOTWEAR
53,PGHH,-1.59,-16.29,57.70,32.01,103131.0,-34784.0,178736.0,17616.87,-43.37,22.0,X-MC,9.70,57.0,-0.34,1.37,0.0,X40,ATH,FMCG
43,INFY,-1.92,-13.20,54.65,34.24,148427.0,-41292.0,271596.0,1972.00,-31.79,22.0,X-LC,9.40,3.0,-0.28,2.08,0.0,X40,NTT,IT
9,BAJAJHFL,-3.61,-28.13,116.33,55.47,203401.0,-68438.0,174848.0,181.50,-38.44,23.0,X-MC,17.47,60.0,-0.34,1.34,0.0,X40N,ATH,FINANCE

In [18]:
# top 5 to accumulate based on Spread and CumlRnk
df_tmp = df_portfolio_features[df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])]
df_tmp = df_tmp[(df_tmp['CumlRnk'] < 100)].sort_values(by = 'Spread%', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
37,ICICIGI,-2.31,0.72,18.48,19.34,37248.0,1450.0,201559.0,2252.93,-15.18,48.0,X-MC,1.09,66.0,0.04,1.54,16.78,X40,ATH,INSURANCE
78,UNITDSPR,-2.04,-0.64,21.54,20.77,50112.0,-1497.0,232647.0,1644.00,-11.86,41.0,X-MC,1.40,64.0,-0.03,1.78,6.42,X40N,NTT,BREWERIES
22,DABUR,-2.94,-1.61,46.05,43.70,112397.0,-3992.0,244076.0,735.00,-10.79,43.0,X-MC,1.51,70.0,-0.04,1.87,13.20,XY24,BTT,FMCG
59,RELIANCE,-3.53,-13.68,45.16,25.30,78337.0,-27497.0,173466.0,1952.00,-15.80,32.0,X-LC,2.19,21.0,-0.35,1.33,16.19,XY25,BTT,REFINERIES
5,ANGELONE,-4.85,-90.91,1266.89,24.20,351385.0,-277514.0,27736.0,3033.00,-86.88,30.0,X-SC,2.47,97.0,-0.79,0.21,16.16,X40N,NTT,FINANCE

In [19]:
# top 5 to accumulate based on lowest Gained%
df_tmp = df_portfolio_features[df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])].sort_values(by = 'Gained%', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
3,ACC,-2.84,-34.98,152.46,64.15,235886.0,-83231.0,154720.0,3906.00,-50.74,26.0,X-SC,9.65,85.0,-0.35,1.18,0.0,XY24,BTT,CEMENT
10,BAJAJHLDNG,-2.38,-5.69,37.02,29.22,66376.0,-10826.0,179299.0,14451.52,-12.59,37.0,X-LC,11.85,28.0,-0.16,1.37,0.0,X40,ATH,FINANCE
9,BAJAJHFL,-3.61,-28.13,116.33,55.47,203401.0,-68438.0,174848.0,181.50,-38.44,23.0,X-MC,17.47,60.0,-0.34,1.34,0.0,X40N,ATH,FINANCE
8,AWL,-4.81,-41.66,169.43,57.19,322376.0,-135856.0,190271.0,485.00,-66.62,13.0,X-SC,19.48,81.0,-0.42,1.46,0.0,XY24,NTT,FMCG
12,BATAINDIA,-3.86,-51.07,176.33,35.20,111010.0,-65714.0,62956.0,2096.00,-17.40,22.0,X-SC,22.67,91.0,-0.59,0.48,0.0,X40,NTT,FOOTWEAR

In [20]:
# top 5 to accumulate based on lowest CurrAlloc%
df_tmp = df_portfolio_features[df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])].sort_values(by = 'CurrAlloc%', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
5,ANGELONE,-4.85,-90.91,1266.89,24.20,351385.0,-277514.0,27736.0,3033.0,-86.88,30.0,X-SC,2.47,97.0,-0.79,0.21,16.16,X40N,NTT,FINANCE
54,QUESS,-2.63,-35.79,122.46,42.84,51116.0,-23265.0,41741.0,424.0,-58.13,34.0,X-SC,17.18,80.0,-0.46,0.32,0.41,XY24,NTT,MISC
58,RELAXO,-6.71,-57.94,262.12,52.31,160032.0,-84107.0,61053.0,1176.0,-55.18,25.0,X-SC,15.49,92.0,-0.53,0.47,0.00,X40N,NTT,FOOTWEAR
12,BATAINDIA,-3.86,-51.07,176.33,35.20,111010.0,-65714.0,62956.0,2096.0,-17.40,22.0,X-SC,22.67,91.0,-0.59,0.48,0.00,X40,NTT,FOOTWEAR
51,MEDANTA,-0.68,-5.56,31.39,24.08,37632.0,-7064.0,119886.0,1486.0,-6.15,48.0,X-SC,7.95,87.0,-0.19,0.92,9.81,XY24,NTT,HEALTHCARE

In [21]:
# top 5 to accumulate based on CumlRnk
df_tmp = df_portfolio_features.sort_values(by = 'CumlRnk', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
45,ITC,-0.46,-17.78,44.80,19.06,125299.0,-60480.0,279686.0,452.00,-54.71,38.0,X-LC,17.16,1.0,-0.48,2.14,1.27,X40,NTT,FMCG
73,TCS,-1.74,-25.72,66.37,23.58,213277.0,-111283.0,321346.0,4311.59,-35.43,28.0,X-LC,9.93,2.0,-0.52,2.46,0.69,X40,ATH,IT
43,INFY,-1.92,-13.20,54.65,34.24,148427.0,-41292.0,271596.0,1972.00,-31.79,22.0,X-LC,9.40,3.0,-0.28,2.08,0.00,X40,NTT,IT
75,TMPV,-4.25,-18.58,63.76,33.33,169139.0,-60526.0,265274.0,600.00,-82.53,45.0,X-LC,3.84,4.0,-0.36,2.03,8.45,XY24,NTT,AUTO
34,HCLTECH,-2.19,-11.83,40.44,23.83,86265.0,-28608.0,213316.0,1908.19,-7.36,27.0,X-LC,6.72,8.0,-0.33,1.63,2.34,X40,ATH,IT

In [22]:
# top 5 for average up
df_tmp = df_portfolio_features[(df_portfolio_features['Dev%_200'] > 5)].sort_values(by = 'CurrAlloc%', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
42,INDUSINDBK,-2.27,-30.97,92.50,32.89,49301.0,-23908.0,53298.0,1800.00,-350.70,54.0,L-MC,12.11,258.0,-0.48,0.41,46.78,XR,NTT,BANKS
67,SONACOMS,-5.05,-12.21,58.43,39.09,51893.0,-12347.0,88812.0,804.02,-30.46,45.0,M-MC,11.14,193.0,-0.24,0.68,25.64,AR,ATH,AUTO
19,COALINDIA,-2.26,3.50,13.69,17.67,21320.0,5272.0,155733.0,478.51,24.82,49.0,L-LC,10.79,185.0,0.25,1.19,25.01,XY25,ATH,MINING
27,FINCABLES,2.33,18.42,75.57,107.91,132130.0,27201.0,174845.0,1641.55,6.54,77.0,M-SC,6.70,220.0,0.21,1.34,31.54,OX40N,ATH,CABLES
82,VOLTAS,-4.34,16.84,24.26,45.20,54352.0,32298.0,224040.0,1856.00,33.74,52.0,X-MC,9.61,79.0,0.59,1.71,24.79,XY25,NTT,AC

In [23]:
# top 5 RSP
df_tmp = df_portfolio_features.sort_values(by = 'RSP', ascending=False)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
27,FINCABLES,2.33,18.42,75.57,107.91,132130.0,27201.0,174845.0,1641.55,6.54,77.0,M-SC,6.70,220.0,0.21,1.34,31.54,OX40N,ATH,CABLES
26,EASEMYTRIP,-8.24,-56.35,233.75,45.70,180422.0,-99629.0,77186.0,26.40,-19.77,50.0,M-SC,18.12,204.0,-0.55,0.59,27.17,XY24,NTT,TRAVEL
11,BANDHANBNK,-3.26,-15.31,127.21,92.42,300097.0,-42652.0,235907.0,400.00,102.59,61.0,H-SC,8.56,174.0,-0.14,1.80,29.95,XY24,NTT,BANKS
83,WHIRLPOOL,-2.91,-28.27,153.62,81.92,126498.0,-32453.0,82345.0,2270.00,-58.03,52.0,M-SC,25.96,210.0,-0.26,0.63,15.67,XR,NTT,DURABLES
82,VOLTAS,-4.34,16.84,24.26,45.20,54352.0,32298.0,224040.0,1856.00,33.74,52.0,X-MC,9.61,79.0,0.59,1.71,24.79,XY25,NTT,AC

In [24]:
# Top N allocation
df_tmp = df_portfolio_features.sort_values(by = 'CurrAlloc%', ascending=False)
top_n_values = [10, 25, 50]

sum_df = pd.DataFrame({
    'Top_N': top_n_values,
    'Sum_Alloc%': [df_tmp['CurrAlloc%'].head(n).sum() for n in top_n_values]
})

sum_df

   Top_N  Sum_Alloc%
0     10       20.85
1     25       45.92
2     50       78.02

In [25]:
# market-cap-wise allocation
df_tmp = df_portfolio_features[cols]
df_tmp.groupby(df_tmp['Conviction'].str[-2:])['CurrAlloc%'].sum().sort_values(ascending=False)

Conviction
SC    43.80
MC    30.93
LC    25.30
Name: CurrAlloc%, dtype: float64

In [26]:
# criteria-wise allocation
df_portfolio_features.groupby('Criteria')['CurrAlloc%'].sum().sort_values(ascending=False)

Criteria
XY24     27.44
X40      24.46
X40N     12.90
AR        9.32
XY25      9.07
XR        8.60
OX40N     7.40
SR        0.84
Name: CurrAlloc%, dtype: float64

In [27]:
# conviction-wise allocation
df_portfolio_features.groupby('Conviction')['CurrAlloc%'].sum().sort_values(ascending=False)

Conviction
X-MC    23.32
H-SC    22.63
X-LC    21.81
M-SC    11.01
X-SC     9.46
H-MC     5.11
M-MC     2.09
H-LC     1.26
L-LC     1.19
M-LC     1.04
L-SC     0.70
L-MC     0.41
Name: CurrAlloc%, dtype: float64

In [28]:
# sector-wise stats
df_tmp = df_portfolio_features.groupby('Category')[['CurrAlloc%', 'Current', 'Current P/L', 'FTT Amt']].sum().sort_values(by=['Current', 'Current P/L'], ascending=False)
df_tmp['Current P/L%'] = round(df_tmp['Current P/L'] * 100 / df_tmp['Current'], 2)
df_tmp['FTT%'] = round(df_tmp['FTT Amt'] * 100 / df_tmp['Current'], 2)
cols = ['CurrAlloc%', 'Current P/L%', 'FTT%']
df_tmp[cols].sort_values(by=['CurrAlloc%'], ascending=False)

               CurrAlloc%  Current P/L%    FTT%
Category
FMCG                16.02        -17.81   57.66
IT                  11.63        -44.09  116.30
FINANCE             11.14        -43.21   99.56
MISC                 6.94        -43.33  101.97
ELECTRICAL           6.51        -10.20   50.40
PAINTS               5.12        -38.10   58.61
INSURANCE            5.08         -2.14   37.10
PHARMA               4.31         -4.26   37.08
AUTO                 3.93        -21.43   67.73
BANKS                3.17        -28.98  107.14
AC                   2.29         -6.54   35.43
FOOTWEAR             2.03        -66.46  133.20
TRAVEL               2.01        -70.58  155.99
DURABLES             1.92        -53.95   91.40
BREWERIES            1.78         -0.64   21.54
HEALTHCARE           1.71        -37.86   71.88
REALTY               1.44        -17.78   37.13
CERAMICS             1.44        -63.77  113.53
APPARELS             1.42        -27.86   66.40
CABLES               1.34         15.56   75.57
REFINERIES           1.33        -15.85   45.16
JEWELLERY            1.22       -101.68  171.74
MINING               1.19          3.39   13.69
CEMENT               1.18        -53.79  152.46
ENGINEERING          1.16        -60.15  133.40
CHEMICALS            1.04        -94.86  253.83
ENTERTAINMENT        0.80        -85.06  195.44
TEXTILES             0.46        -54.21   98.18
HOTELS               0.42       -106.42  179.23

In [29]:
# money to be made criteria-wise
df_portfolio_features.groupby('Criteria')['FTT Amt'].agg(['sum', 'count']).sort_values(by='sum', ascending=False)

                sum  count
Criteria
XY24      3541263.0     21
X40       1522348.0     15
X40N      1434078.0     10
XR        1367589.0     12
AR        1353745.0     10
OX40N      826264.0     10
XY25       430410.0      6
SR         308987.0      2

In [30]:
# money to be made conviction-wise
df_portfolio_features.groupby('Conviction')['FTT Amt'].agg(['sum', 'count']).sort_values(by='sum', ascending=False)

                  sum  count
Conviction
H-SC        3836048.0     24
X-SC        1567724.0     10
M-SC        1478780.0     14
X-MC        1463596.0     15
X-LC        1420147.0     12
H-MC         411749.0      3
L-SC         199598.0      2
M-LC         155303.0      1
M-MC         112824.0      2
H-LC          68294.0      1
L-MC          49301.0      1
L-LC          21320.0      1

In [31]:
# money to be made criteria and conviction-wise
df_portfolio_features.groupby(['Conviction', 'Criteria'])['FTT Amt'].agg(['sum', 'count']).sort_values(by='sum', ascending=False)

                           sum  count
Conviction Criteria
H-SC       XY24      1298572.0      6
           AR         973691.0      5
           XR         879162.0      7
M-SC       XY24       867175.0      6
X-LC       X40        742621.0      6
X-SC       X40N       724838.0      4
           XY24       647010.0      4
X-MC       X40        583851.0      7
           X40N       465139.0      4
H-SC       OX40N      375636.0      4
M-SC       OX40N      349621.0      5
H-SC       SR         308987.0      2
X-LC       XY24       292298.0      2
           X40N       244101.0      2
H-MC       XY24       228634.0      1
X-MC       XY24       207574.0      2
           XY25       207032.0      2
X-SC       X40        195876.0      2
M-SC       XR         185232.0      2
H-MC       AR         183115.0      2
M-LC       XR         155303.0      1
X-LC       XY25       141127.0      2
L-SC       OX40N      101007.0      1
           XR          98591.0      1
M-SC       AR          76752.0      1
H-LC       AR          68294.0      1
M-MC       XY25        60931.0      1
           AR          51893.0      1
L-MC       XR          49301.0      1
L-LC       XY25        21320.0      1

In [32]:
# notebook execution time

end_time = time.time()
execution_time = round(end_time - start_time, 0)
print(f"Notebook execution time: {execution_time} seconds")

Notebook execution time: 37.0 seconds