<a href="https://colab.research.google.com/github/ankit-rathi/Quantvesting_v2/blob/main/myStocks_Portfolio_Analysis.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
'''
!pip install pandas==2.2.2 -qq
!pip install pyxirr -qq
!pip install ta -qq
!pip install yfinance==0.2.59 -qq
'''

'\n!pip install pandas==2.2.2 -qq\n!pip install pyxirr -qq\n!pip install ta -qq\n!pip install yfinance==0.2.59 -qq\n'

In [2]:
# import libraries

import numpy as np
import pandas as pd
import datetime
import warnings
warnings.filterwarnings('ignore')
import yfinance as yfin
import ta
import matplotlib.pyplot as plt
import requests

In [3]:
# notebook start time
import time
import datetime
import pytz

start_time = time.time()

# function to print date timestamp
def print_date_time():
  tz_NY = pytz.timezone('Asia/Kolkata')
  datetime_NY = datetime.datetime.now(tz_NY)
  print("Run date time (IST):", datetime_NY.strftime("%Y-%m-%d %H:%M:%S"))

In [4]:
# function to get booked and reserved amount
def get_amt():
  # fetch the JSON data from the URL
  url = "https://raw.githubusercontent.com/ankit-rathi/Tradevesting_v1/main/data/myPortfolioAmts.json"
  response = requests.get(url)
  pf_amts = response.json()  # parse the JSON data

  # extract values from the JSON
  py_booked_amt_dm = pf_amts["py_booked_amt_dm"]
  py_booked_amt_sv = pf_amts["py_booked_amt_sv"]
  cy_booked_amt_dm = pf_amts["cy_booked_amt_dm"]
  cy_booked_amt_sv = pf_amts["cy_booked_amt_sv"]
  reserve_amt_dm = pf_amts["reserve_amt_dm"]
  reserve_amt_sv = pf_amts["reserve_amt_sv"]

  # perform calculations
  py_booked_amt = py_booked_amt_dm + py_booked_amt_sv
  cy_booked_amt = cy_booked_amt_dm + cy_booked_amt_sv
  reserve_amt = reserve_amt_dm + reserve_amt_sv
  total_booked_amt = py_booked_amt + cy_booked_amt

  return total_booked_amt, reserve_amt, cy_booked_amt, py_booked_amt

gen_output = 0

In [5]:
# function to format the amount
def format_amt(number):
    abs_number = abs(number)

    if abs_number >= 1_00_00_000:  # Crores
        formatted_amt = f"{number / 1_00_00_000:.2f} C"
    elif abs_number >= 1_00_000:  # Lakhs
        formatted_amt = f"{number / 1_00_000:.2f} L"
    elif abs_number >= 1_000:  # Thousands
        formatted_amt = f"{number / 1_000:.2f} K"
    else:
        formatted_amt = f"{number:.2f}"

    return formatted_amt

# function to set start and end date
def get_start_end_date():
  start_date = (datetime.date.today() + datetime.timedelta(days=-365)).strftime('%Y-%m-%d')
  end_date = (datetime.date.today() + datetime.timedelta(days=1)).strftime('%Y-%m-%d')
  return start_date, end_date

# function to fetch my portfolio csv
def get_mypfs_df():
  mypfs_df = pd.read_csv('https://raw.githubusercontent.com/ankit-rathi/Tradevesting_v1/main/data/myPortfolioStocks.csv')
  return mypfs_df

# function to fetch my prospects csv
def get_mypps_df():
  mypps_df = pd.read_csv('https://raw.githubusercontent.com/ankit-rathi/Tradevesting_v1/main/data/myProspectsScrips.csv')
  return mypps_df

# function to fetch screener data
def get_myscreen_df():
  myscreen_df = pd.read_csv('https://raw.githubusercontent.com/ankit-rathi/Tradevesting_v1/main/data/myScreenerDB.csv')
  return myscreen_df

# function to fetch momentum data
def get_myinvmt_df():
  myinvmt_df = pd.read_csv('https://raw.githubusercontent.com/ankit-rathi/Tradevesting_v1/main/data/myInvestments.csv')
  return myinvmt_df

# function to get the stock ids
def get_stock_ids(df_pf):
  stock_n100 = df_pf['Symbol'].unique()

  exclude = ['CADILAHC','MMTC', 'MASFIN']

  stock_ids = df_pf[~df_pf['Symbol'].isin(exclude) ]['Symbol'].unique()

  #mypf = mypf[mypf.Forecast.notnull()]
  #stock_ids = mypf['Symbol'].unique()

  #stock_ids.sort()
  return stock_ids

# get features from screener data
def get_screener_features():
  myscreen_df = get_myscreen_df()
  cols = ['Symbol', 'EPS', 'MedPE', 'ROCE%', 'ROE%', 'CapType']
  return myscreen_df[cols]

# get relative strength
def get_relative_strength(stock_list):

    # Dictionary to store stock tickers and their corresponding percentage price change
    stock_changes = {}

    # Loop through each stock and fetch its price data
    for stock in stock_list:
        try:
            # Download the stock data for the given date range
            stock_data = yfin.Ticker(stock + '.NS').history(period='1mo', interval='1d')[map(str.title, ['open', 'close', 'low', 'high', 'volume'])]

            # Calculate the percentage change for the stock
            if len(stock_data) > 0:
                start_price = stock_data['Close'].iloc[0]
                end_price = stock_data['Close'].iloc[-1]
                percent_change = round(((end_price - start_price) / start_price) * 100, 2)
                stock_changes[stock] = percent_change
            else:
                stock_changes[stock] = np.nan  # If no data is available, set to NaN

        except Exception as e:
            print(f"Error fetching data for {stock}: {e}")
            stock_changes[stock] = np.nan

    # Create a DataFrame with stock tickers and their percentage changes
    df = pd.DataFrame(list(stock_changes.items()), columns=['Symbol', 'Percent_Change'])

    # Drop any stocks with missing data (NaN values)
    df = df.dropna()

    # Calculate the percentile rank based on percentage change
    df['RSP'] = round(df['Percent_Change'].rank(pct=True) * 100, 2)
    cols = ['Symbol', 'RSP']
    df = df[cols]
    # Sort by percentile rank (optional)
    df = df.sort_values(by='RSP', ascending=False).reset_index(drop=True)

    return df

In [6]:
# function to get stock technicals
def stock_prec_dev(stock_symbol):
    #stock_symbol = 'ULTRACEMCO.NS'
    short_window = 20
    mid_window = 50
    long_window = 200
    moving_avg = 'SMA'

    start = datetime.datetime(*map(int, start_date.split('-')))
    end = datetime.datetime(*map(int, end_date.split('-')))

    stock_df = yfin.Ticker(stock_symbol + '.NS').history(period='max', interval='1d')[map(str.title, ['open', 'close', 'low', 'high', 'volume'])]

    stock_df['Max'] = round(max(stock_df['Close']),2)
    stock_df = stock_df[(stock_df.index <= end_date) & (stock_df.index >= start_date)]
    stock_df['200_SMA'] = round(stock_df['Close'].rolling(window = 200, min_periods = 1).mean(),0)
    stock_df['Dev%_200'] = round((stock_df['Close'] - stock_df['200_SMA'])*100/stock_df['200_SMA'],2)
    stock_df.dropna(axis = 0, inplace = True) # remove any null rows

    stock_df['20_SMA'] = stock_df['Close'].rolling(window=20).mean()
    stock_df['50_SMA'] = stock_df['Close'].rolling(window=50).mean()
    stock_df['Symbol'] = stock_symbol

    stock_df['Close'] = round(stock_df['Close'],2)
    stock_df['Min'] = round(min(stock_df['Close']),2)
    stock_df['RSI_14'] = ta.momentum.RSIIndicator(close=stock_df['Close'], window=14).rsi()
    stock_df['RSI_14'] = round(stock_df['RSI_14'],0)
    stock_df['Prev_Close'] = stock_df['Close'].shift(1)
    stock_df.drop(['Open', 'Low', 'High', 'Volume'], axis=1, inplace=True)
    stock_df = stock_df.tail(1)

    max_SMA = max(stock_df['20_SMA'].item(), stock_df['50_SMA'].item(), stock_df['200_SMA'].item())
    min_SMA = min(stock_df['20_SMA'].item(), stock_df['50_SMA'].item(), stock_df['200_SMA'].item())
    ABS_Spread = max_SMA - min_SMA
    stock_df['Spread%'] = round((ABS_Spread / stock_df['200_SMA'].item()) * 100,2)

    return stock_df

# function to compute stock attributes
def get_common_features(stock_ids, df_mypf):

  df_prec_dev = pd.DataFrame()
  df_tmp = get_screener_features()
  df_rs = get_relative_strength(stock_ids)

  for stock_id in stock_ids:
      tmp = stock_prec_dev(stock_id)
      tmp = tmp.reset_index()
      df_prec_dev = pd.concat([df_prec_dev, tmp], ignore_index = True)
  df_prec_dev = pd.merge(df_prec_dev, df_mypf, on= 'Symbol')
  df_prec_dev = pd.merge(df_prec_dev, df_tmp, on= 'Symbol', how='left')
  df_prec_dev = pd.merge(df_prec_dev, df_rs, on= 'Symbol', how='left')
  #print(df_prec_dev.columns)
  df_prec_dev['Curr_PE'] = round(df_prec_dev['Close']/df_prec_dev['EPS'],1)
  df_prec_dev['Dev%_PE'] = round((df_prec_dev['Curr_PE'] - df_prec_dev['MedPE'])*100/df_prec_dev['MedPE'],2)
  df_prec_dev['Conviction'] = df_prec_dev['Conviction'] + '-' + df_prec_dev['CapType']
  return df_prec_dev

# function to arrange stock features
def arrange_features(df_stocks, common_cols, diff_cols):
  df_stocks_common = df_stocks[common_cols].drop_duplicates()
  df_stocks_diff = df_stocks[diff_cols]
  df_stocks_diff['Investment'] = df_stocks_diff['AvgCost'] * df_stocks_diff['Shares']
  df_stocks_diff = df_stocks_diff.groupby(['Symbol'])[['Shares', 'Investment']].aggregate(['sum']).reset_index()
  df_stocks_diff.columns = ['Symbol', 'Shares', 'Investment']
  df_stocks_diff['AvgCost'] = round(df_stocks_diff['Investment']/df_stocks_diff['Shares'],2)
  df_stocks = pd.merge(df_stocks_diff, df_stocks_common, on='Symbol')
  return df_stocks

# plot fact distribution across dimension
def plot_pie_chart(df, dimension, fact):
  # grouping the data by category and calculating the sum of fact for each type
  grouped_data = df.groupby(dimension)[fact].sum()

  # sorting the grouped data in descending order
  grouped_data = grouped_data.sort_values(ascending=False)

  # creating a pie chart
  grouped_data.plot.pie(autopct='%1.1f%%', startangle=90, figsize=(6, 6))

  # adding a title and displaying the plot
  plt.title(f'{dimension} {fact} Distribution')
  plt.ylabel('')  # To hide the y-label
  plt.show()

In [7]:
# function to get portfolio features

def get_portfolio_features(df_common_features):

  print_date_time()
  print('-------------------')

  #df_common_features["Target"] = df_common_features["Target"].fillna(df_common_features["Max"])
  df_common_features['NTT'] = np.where(df_common_features['Strategy']== 'NTT', df_common_features["Target"], df_common_features['Max'])
  df_common_features['LTT'] = np.where(df_common_features['Strategy']== 'BTT', df_common_features["Target"], df_common_features['Max'])
  df_common_features['BOL'] = df_common_features['Min']

  tmp_df = df_common_features[df_common_features['Symbol'].isin(mypf_df[mypf_df['InPortfolio'] != 'NA'].Symbol.values)]
  print('qualified stocks: '+str(len(tmp_df['Symbol'].unique())))
  tmp_df1 = tmp_df[tmp_df['LatestQtr'] == 1]
  print('with latest results: '+str(len(tmp_df1['Symbol'].unique())))
  tmp_df1 = tmp_df1[tmp_df1['StarStock'] == 1]
  print('still star stocks: '+str(len(tmp_df1['Symbol'].unique())))
  tmp_df['Investment'] = tmp_df['AvgCost'] * tmp_df['Shares']
  tmp_df['Current'] = round(tmp_df['Close'] * tmp_df['Shares'],0)
  tmp_df['Previous'] = tmp_df['Prev_Close'] * tmp_df['Shares']
  tmp_df['EstimatedST'] = tmp_df['NTT'] * tmp_df['Shares']
  tmp_df['EstimatedLT'] = tmp_df['LTT'] * tmp_df['Shares']
  tmp_df['Current P/L'] = round((tmp_df['Current'] - tmp_df['Investment']),0)
  tmp_df['Today P/L%'] = round((tmp_df['Current'] - tmp_df['Previous'])*100/tmp_df['Previous'],2)
  tmp_df['Current P/L%'] = round((tmp_df['Current'] - tmp_df['Investment'])*100/tmp_df['Investment'],2)
  tmp_df['EstimatedST P/L%'] = round((tmp_df['EstimatedST'] - tmp_df['Investment'])*100/tmp_df['Investment'],2)
  tmp_df['EstimatedLT P/L%'] = round((tmp_df['EstimatedLT'] - tmp_df['Investment'])*100/tmp_df['Investment'],2)
  tmp_df['NTT%'] = round((tmp_df['NTT'] - tmp_df['Close'])*100/tmp_df['Close'],2)
  tmp_df['LTT%'] = round((tmp_df['LTT'] - tmp_df['Close'])*100/tmp_df['Close'],2)
  tmp_df['Gained%'] = round((tmp_df['Close'] - tmp_df['BOL'])*100/tmp_df['BOL'],2)
  investment = round(sum(tmp_df['AvgCost']*tmp_df['Shares']),0)
  current = round(sum(tmp_df['Close']*tmp_df['Shares']),0)
  tmp_df['InitAlloc%'] = round(tmp_df['Investment']*100/investment,2)
  tmp_df['CurrAlloc%'] = round(tmp_df['Current']*100/current,2)
  tmp_df['FTT'] = tmp_df['LTT']
  tmp_df.loc[tmp_df['Strategy'] == 'NTT', 'FTT'] = tmp_df['NTT']
  tmp_df['FTT%'] = tmp_df['LTT%']
  tmp_df.loc[tmp_df['Strategy'] == 'NTT', 'FTT%'] = tmp_df['NTT%']
  tmp_df['FTT Amt'] = round(tmp_df['FTT%'] * tmp_df['Current']/100,0)
  tmp_df['OTT%'] = round((tmp_df['FTT'] - tmp_df['AvgCost'])*100/tmp_df['AvgCost'],2)
  tmp_df['RRR Ind'] = round(tmp_df['Current P/L']/tmp_df['FTT Amt'],2)
  tmp_df['Risk Ind'] = round(tmp_df['Current P/L%']*tmp_df['CurrAlloc%'],0)

  return tmp_df

# function to print portfolio features
def print_portfolio_stats(df_portfolio_features, myinvmt_df):
  from pyxirr import xirr

  total_booked_amt, reserve_amt, cy_booked_amt, py_booked_amt = get_amt()

  dates = myinvmt_df['Date'].values
  dates = np.append(dates, datetime.date.today().strftime('%d-%b-%y'))
  investment = myinvmt_df['Investment'].values
  dates= pd.to_datetime(dates)

  current = round(sum(df_portfolio_features['Close']*df_portfolio_features['Shares']),0) + reserve_amt
  investment_xirr = np.append(investment, current)
  cagr = round(xirr(pd.DataFrame({"dates": dates, "amounts": investment_xirr}))*100,2)

  investment = -sum(investment)
  invested = round(sum(df_portfolio_features['AvgCost']*df_portfolio_features['Shares']),0) + reserve_amt
  previous = round(sum(df_portfolio_features['Prev_Close']*df_portfolio_features['Shares']),0) + reserve_amt
  cy_invested = investment + py_booked_amt

  today_pnl_amount = current-previous
  today_pnl_percentage = round((current-previous)*100/previous,2)

  curr_pnl_amount = current-invested
  curr_pnl_percentage = round((curr_pnl_amount)*100/(cy_invested),2)

  cy_pnl_amount = cy_booked_amt + curr_pnl_amount
  cy_pnl_percentage = round((cy_pnl_amount)*100/cy_invested,2)

  overall_pnl_amount = total_booked_amt + curr_pnl_amount
  overall_pnl_percentage = round((overall_pnl_amount)*100/investment,2)

  estimate_st = round(sum(df_portfolio_features['FTT']*df_portfolio_features['Shares']),0)  + reserve_amt
  est_st_pnl_amount = estimate_st-current
  est_st_pnl_percentage = round((est_st_pnl_amount)*100/current,2)

  estimate_lt = round(sum(df_portfolio_features['LTT']*df_portfolio_features['Shares']),0)  + reserve_amt
  est_lt_pnl_amount = estimate_lt-current
  est_lt_pnl_percentage = round((est_lt_pnl_amount)*100/current,2)

  total_profit = round(sum(df_portfolio_features[df_portfolio_features['Current P/L%'] > 0]['Current']) - sum(df_portfolio_features[df_portfolio_features['Current P/L%'] > 0]['Investment']),0)
  total_loss = round(sum(df_portfolio_features[df_portfolio_features['Current P/L%'] < 0]['Current']) - sum(df_portfolio_features[df_portfolio_features['Current P/L%'] < 0]['Investment']),0)

  cy_booked_percentage = round((cy_booked_amt)*100/current,2)
  py_booked_percentage = round((py_booked_amt)*100/investment,2)
  total_booked_percentage = round((total_booked_amt)*100/investment,2)

  print('-------------------')
  print('Initial Investment: ', format_amt(investment))
  print('CY Investment: ', format_amt(cy_invested))
  print('Reserve: ', format_amt(reserve_amt))
  print('Current: ',  format_amt(current))
  print('-------------------')
  print('Today PnL: '+ '{} ({}%)'.format(format_amt(today_pnl_amount), today_pnl_percentage))
  print('Current PnL: '+ '{} ({}%)'.format(format_amt(curr_pnl_amount), curr_pnl_percentage))
  print('CY Booked + Current PnL: '+ '{} ({}%)'.format(format_amt(cy_pnl_amount), cy_pnl_percentage))
  print('-------------------')
  print('Total profit: ', format_amt(total_profit))
  print('Total loss: ', format_amt(total_loss))
  print('-------------------')
  print('Total Booked + Current PnL: '+ '{} ({}%)'.format(format_amt(overall_pnl_amount), overall_pnl_percentage))
  print('Total Booked PnL: '+ '{} ({}%)'.format(format_amt(total_booked_amt), total_booked_percentage))
  print('Curr Year Booked PnL: '+ '{} ({}%)'.format(format_amt(cy_booked_amt), cy_booked_percentage))
  print('Prev Year Booked PnL: '+ '{} ({}%)'.format(format_amt(py_booked_amt), py_booked_percentage))
  print('===================')
  print('Est FTT: ',  format_amt(estimate_st))
  print('Est FTT PnL: '+ '{} ({}%)'.format(format_amt(est_st_pnl_amount), est_st_pnl_percentage))

  print('===================')
  print('Deployed: ', format_amt(investment))

  print('Current: ', format_amt(current))

  print('CAGR/XIRR %: '+'{}%'.format(cagr))

In [8]:
# get start and end date
start_date, end_date = get_start_end_date()

# get portfolio and prospects data
mypfs_df = get_mypfs_df()
mypps_df = get_mypps_df()
myinvmt_df = get_myinvmt_df()

# merge above datasets
mypf_df = pd.merge(mypfs_df, mypps_df, on="Symbol")

# seggregate dm and sv portfolio
dm_pf = mypf_df[mypf_df['InPortfolio'] == 'DM']
sv_pf = mypf_df[mypf_df['InPortfolio'] == 'SV']

# build portfolio stock dataframe
dm_stocks = get_stock_ids(dm_pf)
sv_stocks = get_stock_ids(sv_pf)
df_stocks = pd.concat([dm_pf,sv_pf], ignore_index = True)

# arrange common and diff stock features
common_cols = ['Symbol', 'Target', 'Criteria', 'Strategy', 'CumlRnk', 'LatestQtr', 'StarStock', 'Conviction', 'Category', 'InFolio', 'XIRR', 'MBQ']
diff_cols = ['Symbol', 'AvgCost', 'Shares']
df_stocks = arrange_features(df_stocks, common_cols, diff_cols)

# get common features
stock_ids = df_stocks['Symbol'].values
df_common_features = get_common_features(stock_ids, df_stocks)

df_common_features.reset_index(drop=True, inplace=True)
df_common_features.drop(['Date'], axis=1, inplace=True)
# get and print portfolio features
df_portfolio_features = get_portfolio_features(df_common_features)

print_portfolio_stats(df_portfolio_features, myinvmt_df)

df = df_portfolio_features
#plot_pie_chart(df, 'CapType', 'Current')
list_ox40n = list(df[df['MBQ'].str.contains('OX40N', na=False)]['Symbol'].values)

Run date time (IST): 2026-04-29 15:23:11
-------------------
qualified stocks: 92
with latest results: 31
still star stocks: 20
-------------------
Initial Investment:  1.40 C
CY Investment:  1.82 C
Reserve:  1.49 K
Current:  1.49 C
-------------------
Today PnL: 44.84 K (0.3%)
Current PnL: -33.96 L (-18.62%)
CY Booked + Current PnL: -31.88 L (-17.48%)
-------------------
Total profit:  1.43 L
Total loss:  -35.39 L
-------------------
Total Booked + Current PnL: 10.99 L (7.87%)
Total Booked PnL: 44.95 L (32.22%)
Curr Year Booked PnL: 2.08 L (1.39%)
Prev Year Booked PnL: 42.87 L (30.73%)
===================
Est FTT:  2.56 C
Est FTT PnL: 1.06 C (71.24%)
===================
Deployed:  1.40 C
Current:  1.49 C
CAGR/XIRR %: 3.36%

In [9]:
# top 5 near their targets
cols = ['Symbol', 'Today P/L%', 'Current P/L%', 'FTT%', 'OTT%', 'FTT Amt', 'Current P/L', 'Current', 'FTT', 'Dev%_PE', 'RSI_14','Conviction', 'Spread%',  'CumlRnk', 'RRR Ind', 'CurrAlloc%', 'Gained%', 'Criteria', 'Strategy', 'Category']
df_tmp = df_portfolio_features[~df_portfolio_features['Symbol'].isin(['ENRIN','BLUSPRING','DIGITIDE'])]
df_tmp = df_tmp.sort_values(by = 'FTT Amt', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
55,MASFIN,2.23,-0.26,21.88,21.57,21382.0,-255.0,97725.0,397.04,-14.18,61.0,H-SC,0.81,167.0,-0.01,0.66,26.28,XR,ATH,FINANCE
51,KOTAKBANK,0.90,1.90,18.85,21.11,26597.0,2628.0,141100.0,453.24,-12.44,53.0,X-LC,9.37,12.0,0.10,0.95,7.91,X40,ATH,BANKS
59,PIDILITIND,-0.18,-1.49,20.15,18.37,28011.0,-2100.0,139010.0,1670.26,-31.00,53.0,X-LC,7.61,5.0,-0.07,0.93,9.15,X40,ATH,CHEMICALS
53,M&M,2.03,2.24,20.68,23.38,29321.0,3105.0,141786.0,3802.40,-13.39,50.0,X-LC,8.92,25.0,0.11,0.95,9.16,X40N,ATH,AUTO
83,TTKPRESTIG,0.75,-32.69,48.71,0.09,33041.0,-32945.0,67832.0,770.00,57.52,59.0,M-SC,19.29,250.0,-1.00,0.45,20.78,OX40N,NTT,DURABLES

In [10]:
# top 5 today
df_tmp = df_portfolio_features.sort_values(by = 'Today P/L%', ascending=False)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
9,BANDHANBNK,10.98,-4.63,101.76,92.42,270344.0,-12891.0,265668.0,400.0,127.73,73.0,H-SC,4.54,174.0,-0.05,1.78,46.35,XY24,NTT,BANKS
29,GREENPANEL,7.20,-40.69,141.34,43.14,153474.0,-74493.0,108585.0,537.0,142.89,64.0,M-SC,19.13,225.0,-0.49,0.73,30.44,XY24,NTT,MISC
68,SATIN,5.35,0.01,51.82,51.83,143186.0,31.0,276315.0,274.0,-10.64,71.0,H-SC,7.56,159.0,0.00,1.85,34.61,XY24,NTT,FINANCE
47,ITC,3.76,-16.79,43.08,19.06,121936.0,-57120.0,283046.0,452.0,-54.31,62.0,X-LC,17.52,1.0,-0.47,1.90,9.80,X40,NTT,FMCG
72,SIS,3.40,-15.47,43.46,21.26,40789.0,-17179.0,93853.0,528.0,2225.39,80.0,H-SC,8.18,168.0,-0.42,0.63,39.55,OX40N,NTT,MISC

In [11]:
# bottom 5 today
df_tmp = df_portfolio_features.sort_values(by = 'Today P/L%', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
62,RAJOOENG,-16.06,-41.93,140.42,39.61,83578.0,-42980.0,59520.0,143.10,-60.64,44.0,H-SC,23.73,136.0,-0.51,0.40,27.51,AR,ATH,MISC
49,JSWINFRA,-4.29,-7.15,25.40,16.43,52301.0,-15863.0,205911.0,342.00,-20.31,54.0,X-MC,8.62,61.0,-0.30,1.38,16.40,X40N,NTT,REALTY
63,RECLTD,-3.58,-1.91,23.09,20.74,46017.0,-3878.0,199292.0,446.00,7.42,54.0,M-MC,3.39,191.0,-0.08,1.34,18.76,XY25,NTT,FINANCE
77,TANLA,-3.49,-38.97,259.99,119.69,429607.0,-105521.0,165240.0,1943.92,-38.40,63.0,H-SC,19.34,147.0,-0.25,1.11,43.07,AR,ATH,IT
88,VOLTAS,-2.91,14.78,26.50,45.20,58321.0,28338.0,220080.0,1856.00,31.44,57.0,X-MC,3.58,79.0,0.49,1.48,22.58,XY25,NTT,AC

In [12]:
# top 5 to exit based on CumlRnk
df_tmp = df_portfolio_features[~df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])]
df_tmp = df_tmp[(df_tmp['Current P/L%'] > -1) & (df_tmp['Current P/L%'] < 1)].sort_values(by = 'CumlRnk', ascending=False)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
55,MASFIN,2.23,-0.26,21.88,21.57,21382.0,-255.0,97725.0,397.04,-14.18,61.0,H-SC,0.81,167.0,-0.01,0.66,26.28,XR,ATH,FINANCE
68,SATIN,5.35,0.01,51.82,51.83,143186.0,31.0,276315.0,274.00,-10.64,71.0,H-SC,7.56,159.0,0.00,1.85,34.61,XY24,NTT,FINANCE

In [13]:
# OX40N stocks to exit
df_tmp = df_portfolio_features[(df_portfolio_features['Symbol'].isin(list_ox40n))].sort_values(by = 'Current P/L%', ascending=False)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
25,FINCABLES,0.04,27.26,63.37,107.91,119071.0,40254.0,187898.0,1641.55,14.66,73.0,M-SC,9.04,220.0,0.34,1.26,41.36,OX40N,ATH,CABLES
72,SIS,3.40,-15.47,43.46,21.26,40789.0,-17179.0,93853.0,528.00,2225.39,80.0,H-SC,8.18,168.0,-0.42,0.63,39.55,OX40N,NTT,MISC
16,CERA,1.61,-30.55,78.38,23.89,95758.0,-53732.0,122171.0,9475.00,-32.94,60.0,H-SC,12.46,153.0,-0.56,0.82,17.41,OX40N,NTT,CERAMICS
83,TTKPRESTIG,0.75,-32.69,48.71,0.09,33041.0,-32945.0,67832.0,770.00,57.52,59.0,M-SC,19.29,250.0,-1.00,0.45,20.78,OX40N,NTT,DURABLES
50,KANSAINER,-0.87,-34.02,71.98,13.47,128074.0,-91737.0,177930.0,340.00,-43.31,55.0,H-SC,16.46,162.0,-0.72,1.19,24.28,XY24,NTT,PAINTS

In [14]:
# top 5 to book for rotation
df_tmp = df_portfolio_features[(df_portfolio_features['Current P/L%'] > 20) ].sort_values(by = 'CumlRnk', ascending=False)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
25,FINCABLES,0.04,27.26,63.37,107.91,119071.0,40254.0,187898.0,1641.55,14.66,73.0,M-SC,9.04,220.0,0.34,1.26,41.36,OX40N,ATH,CABLES

In [15]:
# top 5 to monitor for exit
df_tmp = df_portfolio_features[~df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])]
df_tmp = df_tmp[(df_tmp['Current P/L%'] > 0) ].sort_values(by = 'Dev%_PE', ascending=False)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
74,STARHEALTH,3.21,3.31,42.54,47.26,123554.0,9319.0,290442.0,761.00,62.96,77.0,H-SC,6.01,173.0,0.08,1.95,50.42,XY24,NTT,INSURANCE
25,FINCABLES,0.04,27.26,63.37,107.91,119071.0,40254.0,187898.0,1641.55,14.66,73.0,M-SC,9.04,220.0,0.34,1.26,41.36,OX40N,ATH,CABLES
68,SATIN,5.35,0.01,51.82,51.83,143186.0,31.0,276315.0,274.00,-10.64,71.0,H-SC,7.56,159.0,0.00,1.85,34.61,XY24,NTT,FINANCE
73,SONACOMS,-0.18,3.40,34.52,39.09,36107.0,3439.0,104598.0,804.02,-18.04,64.0,M-MC,15.26,193.0,0.10,0.70,47.97,AR,ATH,AUTO

In [16]:
# top 5 to book for rotation from weak conviction
df_tmp = df_portfolio_features[~df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])]
df_tmp = df_tmp[~df_tmp['Criteria'].isin(['XY25','XY24','X40', 'X40N'])].sort_values(by = 'RRR Ind', ascending=False)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
25,FINCABLES,0.04,27.26,63.37,107.91,119071.0,40254.0,187898.0,1641.55,14.66,73.0,M-SC,9.04,220.0,0.34,1.26,41.36,OX40N,ATH,CABLES
73,SONACOMS,-0.18,3.40,34.52,39.09,36107.0,3439.0,104598.0,804.02,-18.04,64.0,M-MC,15.26,193.0,0.10,0.70,47.97,AR,ATH,AUTO
55,MASFIN,2.23,-0.26,21.88,21.57,21382.0,-255.0,97725.0,397.04,-14.18,61.0,H-SC,0.81,167.0,-0.01,0.66,26.28,XR,ATH,FINANCE
42,INDIAMART,0.13,-8.38,125.64,106.72,141968.0,-10340.0,112996.0,4810.62,-58.59,53.0,H-SC,9.56,140.0,-0.07,0.76,8.56,AR,ATH,MISC
91,ZYDUSLIFE,-0.10,-4.00,41.28,35.63,83055.0,-8376.0,201198.0,1286.17,-16.67,49.0,H-MC,3.89,120.0,-0.10,1.35,5.79,AR,ATH,PHARMA

In [17]:
# top 5 to accumulate based on lowest RSI_14
df_tmp = df_portfolio_features[df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])].sort_values(by = 'RSI_14', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
33,HCLTECH,0.23,-22.21,56.20,21.51,105766.0,-53728.0,188196.0,1872.35,-18.11,30.0,X-LC,8.65,8.0,-0.51,1.26,0.23,X40,ATH,IT
45,INFY,1.29,-20.56,68.98,34.24,171464.0,-64317.0,248571.0,1972.00,-37.59,33.0,X-LC,13.46,3.0,-0.38,1.67,1.29,X40,NTT,IT
40,ICICIPRULI,0.56,-13.38,50.92,30.73,86892.0,-26360.0,170645.0,790.00,-36.62,38.0,X-MC,13.21,78.0,-0.30,1.14,3.98,X40,ATH,INSURANCE
1,ABBOTINDIA,0.34,-14.69,38.40,18.07,58591.0,-26275.0,152580.0,35195.00,-27.31,42.0,X-MC,11.98,58.0,-0.45,1.02,0.99,X40,ATH,PHARMA
34,HDFCBANK,-0.58,-6.92,37.91,28.37,82883.0,-16253.0,218632.0,1073.00,-21.03,43.0,X-LC,16.48,26.0,-0.20,1.47,6.36,X40,BTT,BANKS

In [18]:
# top 5 to accumulate based on Spread and CumlRnk
df_tmp = df_portfolio_features[df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])]
df_tmp = df_tmp[(df_tmp['CumlRnk'] < 100)].sort_values(by = 'Spread%', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
88,VOLTAS,-2.91,14.78,26.50,45.20,58321.0,28338.0,220080.0,1856.0,31.44,57.0,X-MC,3.58,79.0,0.49,1.48,22.58,XY25,NTT,AC
84,UNITDSPR,-0.91,0.04,20.71,20.77,48513.0,103.0,234247.0,1644.0,-11.25,57.0,X-MC,4.15,64.0,0.00,1.57,11.74,X40N,NTT,BREWERIES
87,VBL,0.65,5.42,28.53,35.50,94997.0,17130.0,332972.0,670.8,-6.97,75.0,X-LC,5.80,13.0,0.18,2.23,36.72,X40N,ATH,FMCG
81,TMPV,0.30,-19.91,70.53,36.58,201009.0,-70843.0,284998.0,600.0,-83.62,56.0,X-LC,5.81,4.0,-0.35,1.91,18.79,XY24,NTT,AUTO
65,RELIANCE,2.75,-8.39,36.78,25.30,67711.0,-16867.0,184096.0,1952.0,-10.80,61.0,X-LC,5.92,21.0,-0.25,1.23,9.39,XY25,BTT,REFINERIES

In [19]:
# top 5 to accumulate based on lowest Gained%
df_tmp = df_portfolio_features[df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])].sort_values(by = 'Gained%', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
33,HCLTECH,0.23,-22.21,56.20,21.51,105766.0,-53728.0,188196.0,1872.35,-18.11,30.0,X-LC,8.65,8.0,-0.51,1.26,0.23,X40,ATH,IT
1,ABBOTINDIA,0.34,-14.69,38.40,18.07,58591.0,-26275.0,152580.0,35195.00,-27.31,42.0,X-MC,11.98,58.0,-0.45,1.02,0.99,X40,ATH,PHARMA
45,INFY,1.29,-20.56,68.98,34.24,171464.0,-64317.0,248571.0,1972.00,-37.59,33.0,X-LC,13.46,3.0,-0.38,1.67,1.29,X40,NTT,IT
40,ICICIPRULI,0.56,-13.38,50.92,30.73,86892.0,-26360.0,170645.0,790.00,-36.62,38.0,X-MC,13.21,78.0,-0.30,1.14,3.98,X40,ATH,INSURANCE
39,ICICIGI,-0.08,-6.23,27.26,19.34,51154.0,-12457.0,187652.0,2252.93,-21.06,43.0,X-MC,6.26,66.0,-0.24,1.26,4.81,X40,ATH,INSURANCE

In [20]:
# top 5 to accumulate based on lowest CurrAlloc%
df_tmp = df_portfolio_features[df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])].sort_values(by = 'CurrAlloc%', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
64,RELAXO,-0.44,-60.76,288.12,52.31,164125.0,-88196.0,56964.0,1176.00,-58.18,53.0,X-SC,27.75,92.0,-0.54,0.38,27.36,X40N,NTT,FOOTWEAR
10,BATAINDIA,-0.23,-53.31,189.56,35.20,113888.0,-68590.0,60080.0,2096.00,-21.30,49.0,X-SC,27.59,91.0,-0.60,0.40,19.15,X40,NTT,FOOTWEAR
60,QUESS,1.44,-16.86,109.17,73.90,96929.0,-18006.0,88787.0,424.00,-55.37,62.0,X-SC,15.40,80.0,-0.19,0.60,19.44,XY24,NTT,MISC
59,PIDILITIND,-0.18,-1.49,20.15,18.37,28011.0,-2100.0,139010.0,1670.26,-31.00,53.0,X-LC,7.61,5.0,-0.07,0.93,9.15,X40,ATH,CHEMICALS
51,KOTAKBANK,0.90,1.90,18.85,21.11,26597.0,2628.0,141100.0,453.24,-12.44,53.0,X-LC,9.37,12.0,0.10,0.95,7.91,X40,ATH,BANKS

In [21]:
# top 5 to accumulate based on CumlRnk
df_tmp = df_portfolio_features.sort_values(by = 'CumlRnk', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
47,ITC,3.76,-16.79,43.08,19.06,121936.0,-57120.0,283046.0,452.00,-54.31,62.0,X-LC,17.52,1.0,-0.47,1.90,9.80,X40,NTT,FMCG
79,TCS,1.12,-27.43,74.42,26.57,250194.0,-127081.0,336192.0,4311.59,-38.71,46.0,X-LC,14.47,2.0,-0.51,2.25,4.92,X40,ATH,IT
45,INFY,1.29,-20.56,68.98,34.24,171464.0,-64317.0,248571.0,1972.00,-37.59,33.0,X-LC,13.46,3.0,-0.38,1.67,1.29,X40,NTT,IT
81,TMPV,0.30,-19.91,70.53,36.58,201009.0,-70843.0,284998.0,600.00,-83.62,56.0,X-LC,5.81,4.0,-0.35,1.91,18.79,XY24,NTT,AUTO
59,PIDILITIND,-0.18,-1.49,20.15,18.37,28011.0,-2100.0,139010.0,1670.26,-31.00,53.0,X-LC,7.61,5.0,-0.07,0.93,9.15,X40,ATH,CHEMICALS

In [22]:
# top 5 for average up
df_tmp = df_portfolio_features[(df_portfolio_features['Dev%_200'] > 5)].sort_values(by = 'CurrAlloc%', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
44,INDUSINDBK,3.01,-32.65,97.31,32.89,50599.0,-25208.0,51998.0,1800.00,-345.10,63.0,L-MC,3.92,258.0,-0.50,0.35,27.99,XR,NTT,BANKS
72,SIS,3.40,-15.47,43.46,21.26,40789.0,-17179.0,93853.0,528.00,2225.39,80.0,H-SC,8.18,168.0,-0.42,0.63,39.55,OX40N,NTT,MISC
73,SONACOMS,-0.18,3.40,34.52,39.09,36107.0,3439.0,104598.0,804.02,-18.04,64.0,M-MC,15.26,193.0,0.10,0.70,47.97,AR,ATH,AUTO
75,SURYODAY,1.66,-13.13,41.63,23.03,64760.0,-23511.0,155560.0,216.00,68.86,69.0,H-SC,5.39,166.0,-0.36,1.04,32.66,XR,NTT,BANKS
5,ATULAUTO,1.27,-15.15,71.56,45.57,119693.0,-29869.0,167263.0,844.00,3624.32,62.0,M-SC,1.07,248.0,-0.25,1.12,28.72,XY24,NTT,AUTO

In [23]:
# top 5 RSP
df_tmp = df_portfolio_features.sort_values(by = 'RSP', ascending=False)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
61,RAJESHEXPO,-1.63,-75.85,314.40,0.07,104145.0,-104052.0,33125.0,518.00,1114.65,57.0,L-SC,34.08,268.0,-1.00,0.22,55.51,OX40N,NTT,JEWELLERY
77,TANLA,-3.49,-38.97,259.99,119.69,429607.0,-105521.0,165240.0,1943.92,-38.40,63.0,H-SC,19.34,147.0,-0.25,1.11,43.07,AR,ATH,IT
9,BANDHANBNK,10.98,-4.63,101.76,92.42,270344.0,-12891.0,265668.0,400.00,127.73,73.0,H-SC,4.54,174.0,-0.05,1.78,46.35,XY24,NTT,BANKS
86,VALIANTORG,0.44,-42.51,202.91,74.15,190859.0,-69544.0,94061.0,838.00,-269.06,59.0,H-SC,17.37,145.0,-0.36,0.63,39.98,XR,NTT,CHEMICALS
80,TITAGARH,-0.31,-26.23,97.55,45.74,174284.0,-63516.0,178661.0,1548.00,-1.77,67.0,H-SC,14.93,175.0,-0.36,1.20,36.31,XY24,NTT,ENGINEERING

In [24]:
# Top N allocation
df_tmp = df_portfolio_features.sort_values(by = 'CurrAlloc%', ascending=False)
top_n_values = [10, 25, 50]

sum_df = pd.DataFrame({
    'Top_N': top_n_values,
    'Sum_Alloc%': [df_tmp['CurrAlloc%'].head(n).sum() for n in top_n_values]
})

sum_df

   Top_N  Sum_Alloc%
0     10       19.20
1     25       42.74
2     50       72.71

In [25]:
# market-cap-wise allocation
df_tmp = df_portfolio_features[cols]
df_tmp.groupby(df_tmp['Conviction'].str[-2:])['CurrAlloc%'].sum().sort_values(ascending=False)

Conviction
SC    42.22
LC    31.87
MC    25.92
Name: CurrAlloc%, dtype: float64

In [26]:
# criteria-wise allocation
df_portfolio_features.groupby('Criteria')['CurrAlloc%'].sum().sort_values(ascending=False)

Criteria
XY24     26.92
X40      25.56
X40N     17.04
XR        9.03
XY25      7.03
OX40N     6.87
AR        6.76
SR        0.80
Name: CurrAlloc%, dtype: float64

In [27]:
# conviction-wise allocation
df_portfolio_features.groupby('Conviction')['CurrAlloc%'].sum().sort_values(ascending=False)

Conviction
X-LC    29.67
H-SC    21.92
X-MC    20.98
M-SC    10.05
X-SC     9.69
H-MC     2.55
M-MC     2.04
H-LC     1.27
M-LC     0.93
L-SC     0.56
L-MC     0.35
Name: CurrAlloc%, dtype: float64

In [28]:
# sector-wise stats
df_tmp = df_portfolio_features.groupby('Category')[['CurrAlloc%', 'Current', 'Current P/L', 'FTT Amt']].sum().sort_values(by=['Current', 'Current P/L'], ascending=False)
df_tmp['Current P/L%'] = round(df_tmp['Current P/L'] * 100 / df_tmp['Current'], 2)
df_tmp['FTT%'] = round(df_tmp['FTT Amt'] * 100 / df_tmp['Current'], 2)
cols = ['CurrAlloc%', 'Current P/L%', 'FTT%']
df_tmp[cols].sort_values(by=['CurrAlloc%'], ascending=False)

               CurrAlloc%  Current P/L%    FTT%
Category
FMCG                15.77        -12.38   52.04
FINANCE             10.76        -14.93   64.92
IT                  10.58        -42.72  114.99
MISC                 6.84        -31.61   88.78
AUTO                 6.66        -10.28   51.62
BANKS                5.59         -9.03   59.45
INSURANCE            5.33         -4.22   39.68
PAINTS               5.06        -30.33   52.96
PHARMA               4.74         -4.83   38.53
ELECTRICAL           4.09        -16.01   57.30
AC                   2.01         -6.62   35.53
CHEMICALS            2.00        -35.72  116.61
HEALTHCARE           1.90        -25.83   58.66
DURABLES             1.82        -42.28   76.89
FOOTWEAR             1.75        -68.76  136.42
APPARELS             1.73         -4.20   39.74
TRAVEL               1.72        -74.25  161.50
BREWERIES            1.57          0.04   20.71
REALTY               1.38         -7.70   25.40
CERAMICS             1.29        -59.57  108.05
CABLES               1.26         21.42   63.37
REFINERIES           1.23         -9.16   36.78
ENGINEERING          1.20        -35.55   97.55
CEMENT               1.16        -55.40  171.67
JEWELLERY            1.05       -103.53  174.24
ENTERTAINMENT        0.75        -73.21  176.51
TEXTILES             0.43        -43.93   84.97
HOTELS               0.34       -121.58  199.74

In [29]:
# money to be made criteria-wise
df_portfolio_features.groupby('Criteria')['FTT Amt'].agg(['sum', 'count']).sort_values(by='sum', ascending=False)

                sum  count
Criteria
XY24      3580614.0     21
X40       1889038.0     19
XR        1334866.0     13
AR        1183636.0      9
X40N      1182853.0     13
OX40N      767073.0     10
XY25       391909.0      5
SR         299894.0      2

In [30]:
# money to be made conviction-wise
df_portfolio_features.groupby('Conviction')['FTT Amt'].agg(['sum', 'count']).sort_values(by='sum', ascending=False)

                  sum  count
Conviction
H-SC        3525747.0     24
X-LC        1871674.0     21
X-MC        1603745.0     15
M-SC        1416978.0     14
X-SC        1357874.0      9
H-MC         317425.0      2
L-SC         206502.0      2
M-LC         152462.0      1
M-MC          82124.0      2
L-MC          50599.0      1
H-LC          44753.0      1

In [31]:
# money to be made criteria and conviction-wise
df_portfolio_features.groupby(['Conviction', 'Criteria'])['FTT Amt'].agg(['sum', 'count']).sort_values(by='sum', ascending=False)

                           sum  count
Conviction Criteria
H-SC       XY24      1130085.0      6
X-LC       X40       1014235.0     10
H-SC       AR         944715.0      5
M-SC       XY24       845383.0      6
H-SC       XR         812699.0      7
X-SC       XY24       795800.0      4
X-MC       X40        673448.0      7
           X40N       473864.0      4
X-SC       X40N       360719.0      3
X-LC       X40N       348270.0      6
H-SC       OX40N      338354.0      4
X-LC       XY24       336242.0      2
M-SC       OX40N      324574.0      5
H-SC       SR         299894.0      2
X-MC       XY24       238734.0      2
H-MC       XY24       234370.0      1
X-MC       XY25       217699.0      2
X-SC       X40        201355.0      2
M-SC       XR         172015.0      2
M-LC       XR         152462.0      1
X-LC       XY25       128193.0      2
L-SC       OX40N      104145.0      1
           XR         102357.0      1
H-MC       AR          83055.0      1
M-SC       AR          75006.0      1
L-MC       XR          50599.0      1
M-MC       XY25        46017.0      1
H-LC       AR          44753.0      1
X-LC       XR          44734.0      1
M-MC       AR          36107.0      1

In [32]:
# notebook execution time

end_time = time.time()
execution_time = round(end_time - start_time, 0)
print(f"Notebook execution time: {execution_time} seconds")

Notebook execution time: 51.0 seconds