<a href="https://colab.research.google.com/github/ankit-rathi/Quantvesting_v2/blob/main/myStocks_Portfolio_Analysis.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
'''
!pip install pandas==2.2.2 -qq
!pip install pyxirr -qq
!pip install ta -qq
!pip install yfinance==0.2.59 -qq
'''

'\n!pip install pandas==2.2.2 -qq\n!pip install pyxirr -qq\n!pip install ta -qq\n!pip install yfinance==0.2.59 -qq\n'

In [2]:
# import libraries

import numpy as np
import pandas as pd
import datetime
import warnings
warnings.filterwarnings('ignore')
import yfinance as yfin
import ta
import matplotlib.pyplot as plt
import requests

In [3]:
# notebook start time
import time
import datetime
import pytz

start_time = time.time()

# function to print date timestamp
def print_date_time():
  tz_NY = pytz.timezone('Asia/Kolkata')
  datetime_NY = datetime.datetime.now(tz_NY)
  print("Run date time (IST):", datetime_NY.strftime("%Y-%m-%d %H:%M:%S"))

In [4]:
# function to get booked and reserved amount
def get_amt():
  # fetch the JSON data from the URL
  url = "https://raw.githubusercontent.com/ankit-rathi/Tradevesting_v1/main/data/myPortfolioAmts.json"
  response = requests.get(url)
  pf_amts = response.json()  # parse the JSON data

  # extract values from the JSON
  py_booked_amt_dm = pf_amts["py_booked_amt_dm"]
  py_booked_amt_sv = pf_amts["py_booked_amt_sv"]
  cy_booked_amt_dm = pf_amts["cy_booked_amt_dm"]
  cy_booked_amt_sv = pf_amts["cy_booked_amt_sv"]
  reserve_amt_dm = pf_amts["reserve_amt_dm"]
  reserve_amt_sv = pf_amts["reserve_amt_sv"]

  # perform calculations
  py_booked_amt = py_booked_amt_dm + py_booked_amt_sv
  cy_booked_amt = cy_booked_amt_dm + cy_booked_amt_sv
  reserve_amt = reserve_amt_dm + reserve_amt_sv
  total_booked_amt = py_booked_amt + cy_booked_amt

  return total_booked_amt, reserve_amt, cy_booked_amt, py_booked_amt

gen_output = 0

In [5]:
# function to format the amount
def format_amt(number):
    abs_number = abs(number)

    if abs_number >= 1_00_00_000:  # Crores
        formatted_amt = f"{number / 1_00_00_000:.2f} C"
    elif abs_number >= 1_00_000:  # Lakhs
        formatted_amt = f"{number / 1_00_000:.2f} L"
    elif abs_number >= 1_000:  # Thousands
        formatted_amt = f"{number / 1_000:.2f} K"
    else:
        formatted_amt = f"{number:.2f}"

    return formatted_amt

# function to set start and end date
def get_start_end_date():
  start_date = (datetime.date.today() + datetime.timedelta(days=-365)).strftime('%Y-%m-%d')
  end_date = (datetime.date.today() + datetime.timedelta(days=1)).strftime('%Y-%m-%d')
  return start_date, end_date

# function to fetch my portfolio csv
def get_mypfs_df():
  mypfs_df = pd.read_csv('https://raw.githubusercontent.com/ankit-rathi/Tradevesting_v1/main/data/myPortfolioStocks.csv')
  return mypfs_df

# function to fetch my prospects csv
def get_mypps_df():
  mypps_df = pd.read_csv('https://raw.githubusercontent.com/ankit-rathi/Tradevesting_v1/main/data/myProspectsScrips.csv')
  return mypps_df

# function to fetch screener data
def get_myscreen_df():
  myscreen_df = pd.read_csv('https://raw.githubusercontent.com/ankit-rathi/Tradevesting_v1/main/data/myScreenerDB.csv')
  return myscreen_df

# function to fetch momentum data
def get_myinvmt_df():
  myinvmt_df = pd.read_csv('https://raw.githubusercontent.com/ankit-rathi/Tradevesting_v1/main/data/myInvestments.csv')
  return myinvmt_df

# function to get the stock ids
def get_stock_ids(df_pf):
  stock_n100 = df_pf['Symbol'].unique()

  exclude = ['CADILAHC','MMTC', 'MASFIN']

  stock_ids = df_pf[~df_pf['Symbol'].isin(exclude) ]['Symbol'].unique()

  #mypf = mypf[mypf.Forecast.notnull()]
  #stock_ids = mypf['Symbol'].unique()

  #stock_ids.sort()
  return stock_ids

# get features from screener data
def get_screener_features():
  myscreen_df = get_myscreen_df()
  cols = ['Symbol', 'EPS', 'MedPE', 'ROCE%', 'ROE%', 'CapType']
  return myscreen_df[cols]

# get relative strength
def get_relative_strength(stock_list):

    # Dictionary to store stock tickers and their corresponding percentage price change
    stock_changes = {}

    # Loop through each stock and fetch its price data
    for stock in stock_list:
        try:
            # Download the stock data for the given date range
            stock_data = yfin.Ticker(stock + '.NS').history(period='1mo', interval='1d')[map(str.title, ['open', 'close', 'low', 'high', 'volume'])]

            # Calculate the percentage change for the stock
            if len(stock_data) > 0:
                start_price = stock_data['Close'].iloc[0]
                end_price = stock_data['Close'].iloc[-1]
                percent_change = round(((end_price - start_price) / start_price) * 100, 2)
                stock_changes[stock] = percent_change
            else:
                stock_changes[stock] = np.nan  # If no data is available, set to NaN

        except Exception as e:
            print(f"Error fetching data for {stock}: {e}")
            stock_changes[stock] = np.nan

    # Create a DataFrame with stock tickers and their percentage changes
    df = pd.DataFrame(list(stock_changes.items()), columns=['Symbol', 'Percent_Change'])

    # Drop any stocks with missing data (NaN values)
    df = df.dropna()

    # Calculate the percentile rank based on percentage change
    df['RSP'] = round(df['Percent_Change'].rank(pct=True) * 100, 2)
    cols = ['Symbol', 'RSP']
    df = df[cols]
    # Sort by percentile rank (optional)
    df = df.sort_values(by='RSP', ascending=False).reset_index(drop=True)

    return df

In [6]:
# function to get stock technicals
def stock_prec_dev(stock_symbol):
    #stock_symbol = 'ULTRACEMCO.NS'
    short_window = 20
    mid_window = 50
    long_window = 200
    moving_avg = 'SMA'

    start = datetime.datetime(*map(int, start_date.split('-')))
    end = datetime.datetime(*map(int, end_date.split('-')))

    stock_df = yfin.Ticker(stock_symbol + '.NS').history(period='max', interval='1d')[map(str.title, ['open', 'close', 'low', 'high', 'volume'])]

    stock_df['Max'] = round(max(stock_df['Close']),2)
    stock_df = stock_df[(stock_df.index <= end_date) & (stock_df.index >= start_date)]
    stock_df['200_SMA'] = round(stock_df['Close'].rolling(window = 200, min_periods = 1).mean(),0)
    stock_df['Dev%_200'] = round((stock_df['Close'] - stock_df['200_SMA'])*100/stock_df['200_SMA'],2)
    stock_df.dropna(axis = 0, inplace = True) # remove any null rows

    stock_df['20_SMA'] = stock_df['Close'].rolling(window=20).mean()
    stock_df['50_SMA'] = stock_df['Close'].rolling(window=50).mean()
    stock_df['Symbol'] = stock_symbol

    stock_df['Close'] = round(stock_df['Close'],2)
    stock_df['Min'] = round(min(stock_df['Close']),2)
    stock_df['RSI_14'] = ta.momentum.RSIIndicator(close=stock_df['Close'], window=14).rsi()
    stock_df['RSI_14'] = round(stock_df['RSI_14'],0)
    stock_df['Prev_Close'] = stock_df['Close'].shift(1)
    stock_df.drop(['Open', 'Low', 'High', 'Volume'], axis=1, inplace=True)
    stock_df = stock_df.tail(1)

    max_SMA = max(stock_df['20_SMA'].item(), stock_df['50_SMA'].item(), stock_df['200_SMA'].item())
    min_SMA = min(stock_df['20_SMA'].item(), stock_df['50_SMA'].item(), stock_df['200_SMA'].item())
    ABS_Spread = max_SMA - min_SMA
    stock_df['Spread%'] = round((ABS_Spread / stock_df['200_SMA'].item()) * 100,2)

    return stock_df

# function to compute stock attributes
def get_common_features(stock_ids, df_mypf):

  df_prec_dev = pd.DataFrame()
  df_tmp = get_screener_features()
  df_rs = get_relative_strength(stock_ids)

  for stock_id in stock_ids:
      tmp = stock_prec_dev(stock_id)
      tmp = tmp.reset_index()
      df_prec_dev = pd.concat([df_prec_dev, tmp], ignore_index = True)
  df_prec_dev = pd.merge(df_prec_dev, df_mypf, on= 'Symbol')
  df_prec_dev = pd.merge(df_prec_dev, df_tmp, on= 'Symbol', how='left')
  df_prec_dev = pd.merge(df_prec_dev, df_rs, on= 'Symbol', how='left')
  #print(df_prec_dev.columns)
  df_prec_dev['Curr_PE'] = round(df_prec_dev['Close']/df_prec_dev['EPS'],1)
  df_prec_dev['Dev%_PE'] = round((df_prec_dev['Curr_PE'] - df_prec_dev['MedPE'])*100/df_prec_dev['MedPE'],2)
  df_prec_dev['Conviction'] = df_prec_dev['Conviction'] + '-' + df_prec_dev['CapType']
  return df_prec_dev

# function to arrange stock features
def arrange_features(df_stocks, common_cols, diff_cols):
  df_stocks_common = df_stocks[common_cols].drop_duplicates()
  df_stocks_diff = df_stocks[diff_cols]
  df_stocks_diff['Investment'] = df_stocks_diff['AvgCost'] * df_stocks_diff['Shares']
  df_stocks_diff = df_stocks_diff.groupby(['Symbol'])[['Shares', 'Investment']].aggregate(['sum']).reset_index()
  df_stocks_diff.columns = ['Symbol', 'Shares', 'Investment']
  df_stocks_diff['AvgCost'] = round(df_stocks_diff['Investment']/df_stocks_diff['Shares'],2)
  df_stocks = pd.merge(df_stocks_diff, df_stocks_common, on='Symbol')
  return df_stocks

# plot fact distribution across dimension
def plot_pie_chart(df, dimension, fact):
  # grouping the data by category and calculating the sum of fact for each type
  grouped_data = df.groupby(dimension)[fact].sum()

  # sorting the grouped data in descending order
  grouped_data = grouped_data.sort_values(ascending=False)

  # creating a pie chart
  grouped_data.plot.pie(autopct='%1.1f%%', startangle=90, figsize=(6, 6))

  # adding a title and displaying the plot
  plt.title(f'{dimension} {fact} Distribution')
  plt.ylabel('')  # To hide the y-label
  plt.show()

In [7]:
# function to get portfolio features

def get_portfolio_features(df_common_features):

  print_date_time()
  print('-------------------')

  #df_common_features["Target"] = df_common_features["Target"].fillna(df_common_features["Max"])
  df_common_features['NTT'] = np.where(df_common_features['Strategy']== 'NTT', df_common_features["Target"], df_common_features['Max'])
  df_common_features['LTT'] = np.where(df_common_features['Strategy']== 'BTT', df_common_features["Target"], df_common_features['Max'])
  df_common_features['BOL'] = df_common_features['Min']

  tmp_df = df_common_features[df_common_features['Symbol'].isin(mypf_df[mypf_df['InPortfolio'] != 'NA'].Symbol.values)]
  print('qualified stocks: '+str(len(tmp_df['Symbol'].unique())))
  tmp_df1 = tmp_df[tmp_df['LatestQtr'] == 1]
  print('with latest results: '+str(len(tmp_df1['Symbol'].unique())))
  tmp_df1 = tmp_df1[tmp_df1['StarStock'] == 1]
  print('still star stocks: '+str(len(tmp_df1['Symbol'].unique())))
  tmp_df['Investment'] = tmp_df['AvgCost'] * tmp_df['Shares']
  tmp_df['Current'] = round(tmp_df['Close'] * tmp_df['Shares'],0)
  tmp_df['Previous'] = tmp_df['Prev_Close'] * tmp_df['Shares']
  tmp_df['EstimatedST'] = tmp_df['NTT'] * tmp_df['Shares']
  tmp_df['EstimatedLT'] = tmp_df['LTT'] * tmp_df['Shares']
  tmp_df['Current P/L'] = round((tmp_df['Current'] - tmp_df['Investment']),0)
  tmp_df['Today P/L%'] = round((tmp_df['Current'] - tmp_df['Previous'])*100/tmp_df['Previous'],2)
  tmp_df['Current P/L%'] = round((tmp_df['Current'] - tmp_df['Investment'])*100/tmp_df['Investment'],2)
  tmp_df['EstimatedST P/L%'] = round((tmp_df['EstimatedST'] - tmp_df['Investment'])*100/tmp_df['Investment'],2)
  tmp_df['EstimatedLT P/L%'] = round((tmp_df['EstimatedLT'] - tmp_df['Investment'])*100/tmp_df['Investment'],2)
  tmp_df['NTT%'] = round((tmp_df['NTT'] - tmp_df['Close'])*100/tmp_df['Close'],2)
  tmp_df['LTT%'] = round((tmp_df['LTT'] - tmp_df['Close'])*100/tmp_df['Close'],2)
  tmp_df['Gained%'] = round((tmp_df['Close'] - tmp_df['BOL'])*100/tmp_df['BOL'],2)
  investment = round(sum(tmp_df['AvgCost']*tmp_df['Shares']),0)
  current = round(sum(tmp_df['Close']*tmp_df['Shares']),0)
  tmp_df['InitAlloc%'] = round(tmp_df['Investment']*100/investment,2)
  tmp_df['CurrAlloc%'] = round(tmp_df['Current']*100/current,2)
  tmp_df['FTT'] = tmp_df['LTT']
  tmp_df.loc[tmp_df['Strategy'] == 'NTT', 'FTT'] = tmp_df['NTT']
  tmp_df['FTT%'] = tmp_df['LTT%']
  tmp_df.loc[tmp_df['Strategy'] == 'NTT', 'FTT%'] = tmp_df['NTT%']
  tmp_df['FTT Amt'] = round(tmp_df['FTT%'] * tmp_df['Current']/100,0)
  tmp_df['OTT%'] = round((tmp_df['FTT'] - tmp_df['AvgCost'])*100/tmp_df['AvgCost'],2)
  tmp_df['RRR Ind'] = round(tmp_df['Current P/L']/tmp_df['FTT Amt'],2)
  tmp_df['Risk Ind'] = round(tmp_df['Current P/L%']*tmp_df['CurrAlloc%'],0)

  return tmp_df

# function to print portfolio features
def print_portfolio_stats(df_portfolio_features, myinvmt_df):
  from pyxirr import xirr

  total_booked_amt, reserve_amt, cy_booked_amt, py_booked_amt = get_amt()

  dates = myinvmt_df['Date'].values
  dates = np.append(dates, datetime.date.today().strftime('%d-%b-%y'))
  investment = myinvmt_df['Investment'].values
  dates= pd.to_datetime(dates)

  current = round(sum(df_portfolio_features['Close']*df_portfolio_features['Shares']),0) + reserve_amt
  investment_xirr = np.append(investment, current)
  cagr = round(xirr(pd.DataFrame({"dates": dates, "amounts": investment_xirr}))*100,2)

  investment = -sum(investment)
  invested = round(sum(df_portfolio_features['AvgCost']*df_portfolio_features['Shares']),0) + reserve_amt
  previous = round(sum(df_portfolio_features['Prev_Close']*df_portfolio_features['Shares']),0) + reserve_amt
  cy_invested = investment + py_booked_amt

  today_pnl_amount = current-previous
  today_pnl_percentage = round((current-previous)*100/previous,2)

  curr_pnl_amount = current-invested
  curr_pnl_percentage = round((curr_pnl_amount)*100/(cy_invested),2)

  cy_pnl_amount = cy_booked_amt + curr_pnl_amount
  cy_pnl_percentage = round((cy_pnl_amount)*100/cy_invested,2)

  overall_pnl_amount = total_booked_amt + curr_pnl_amount
  overall_pnl_percentage = round((overall_pnl_amount)*100/investment,2)

  estimate_st = round(sum(df_portfolio_features['FTT']*df_portfolio_features['Shares']),0)  + reserve_amt
  est_st_pnl_amount = estimate_st-current
  est_st_pnl_percentage = round((est_st_pnl_amount)*100/current,2)

  estimate_lt = round(sum(df_portfolio_features['LTT']*df_portfolio_features['Shares']),0)  + reserve_amt
  est_lt_pnl_amount = estimate_lt-current
  est_lt_pnl_percentage = round((est_lt_pnl_amount)*100/current,2)

  total_profit = round(sum(df_portfolio_features[df_portfolio_features['Current P/L%'] > 0]['Current']) - sum(df_portfolio_features[df_portfolio_features['Current P/L%'] > 0]['Investment']),0)
  total_loss = round(sum(df_portfolio_features[df_portfolio_features['Current P/L%'] < 0]['Current']) - sum(df_portfolio_features[df_portfolio_features['Current P/L%'] < 0]['Investment']),0)

  cy_booked_percentage = round((cy_booked_amt)*100/current,2)
  py_booked_percentage = round((py_booked_amt)*100/investment,2)
  total_booked_percentage = round((total_booked_amt)*100/investment,2)

  print('-------------------')
  print('Initial Investment: ', format_amt(investment))
  print('CY Investment: ', format_amt(cy_invested))
  print('Reserve: ', format_amt(reserve_amt))
  print('Current: ',  format_amt(current))
  print('-------------------')
  print('Today PnL: '+ '{} ({}%)'.format(format_amt(today_pnl_amount), today_pnl_percentage))
  print('Current PnL: '+ '{} ({}%)'.format(format_amt(curr_pnl_amount), curr_pnl_percentage))
  print('CY Booked + Current PnL: '+ '{} ({}%)'.format(format_amt(cy_pnl_amount), cy_pnl_percentage))
  print('-------------------')
  print('Total profit: ', format_amt(total_profit))
  print('Total loss: ', format_amt(total_loss))
  print('-------------------')
  print('Total Booked + Current PnL: '+ '{} ({}%)'.format(format_amt(overall_pnl_amount), overall_pnl_percentage))
  print('Total Booked PnL: '+ '{} ({}%)'.format(format_amt(total_booked_amt), total_booked_percentage))
  print('Curr Year Booked PnL: '+ '{} ({}%)'.format(format_amt(cy_booked_amt), cy_booked_percentage))
  print('Prev Year Booked PnL: '+ '{} ({}%)'.format(format_amt(py_booked_amt), py_booked_percentage))
  print('===================')
  print('Est FTT: ',  format_amt(estimate_st))
  print('Est FTT PnL: '+ '{} ({}%)'.format(format_amt(est_st_pnl_amount), est_st_pnl_percentage))

  print('===================')
  print('Deployed: ', format_amt(investment))

  print('Current: ', format_amt(current))

  print('CAGR/XIRR %: '+'{}%'.format(cagr))

In [8]:
# get start and end date
start_date, end_date = get_start_end_date()

# get portfolio and prospects data
mypfs_df = get_mypfs_df()
mypps_df = get_mypps_df()
myinvmt_df = get_myinvmt_df()

# merge above datasets
mypf_df = pd.merge(mypfs_df, mypps_df, on="Symbol")

# seggregate dm and sv portfolio
dm_pf = mypf_df[mypf_df['InPortfolio'] == 'DM']
sv_pf = mypf_df[mypf_df['InPortfolio'] == 'SV']

# build portfolio stock dataframe
dm_stocks = get_stock_ids(dm_pf)
sv_stocks = get_stock_ids(sv_pf)
df_stocks = pd.concat([dm_pf,sv_pf], ignore_index = True)

# arrange common and diff stock features
common_cols = ['Symbol', 'Target', 'Criteria', 'Strategy', 'CumlRnk', 'LatestQtr', 'StarStock', 'Conviction', 'Category', 'InFolio', 'XIRR', 'MBQ']
diff_cols = ['Symbol', 'AvgCost', 'Shares']
df_stocks = arrange_features(df_stocks, common_cols, diff_cols)

# get common features
stock_ids = df_stocks['Symbol'].values
df_common_features = get_common_features(stock_ids, df_stocks)

df_common_features.reset_index(drop=True, inplace=True)
df_common_features.drop(['Date'], axis=1, inplace=True)
# get and print portfolio features
df_portfolio_features = get_portfolio_features(df_common_features)

print_portfolio_stats(df_portfolio_features, myinvmt_df)

df = df_portfolio_features
#plot_pie_chart(df, 'CapType', 'Current')
list_ox40n = list(df[df['MBQ'].str.contains('OX40N', na=False)]['Symbol'].values)

Run date time (IST): 2026-08-05 16:03:13
-------------------
qualified stocks: 88
with latest results: 30
still star stocks: 19
-------------------
Initial Investment:  1.46 C
CY Investment:  1.89 C
Reserve:  2.24 L
Current:  1.62 C
-------------------
Today PnL: 13.03 K (0.08%)
Current PnL: -29.65 L (-15.7%)
CY Booked + Current PnL: -25.43 L (-13.46%)
-------------------
Total profit:  3.92 L
Total loss:  -33.57 L
-------------------
Total Booked + Current PnL: 17.44 L (11.94%)
Total Booked PnL: 47.09 L (32.24%)
Curr Year Booked PnL: 4.22 L (2.6%)
Prev Year Booked PnL: 42.87 L (29.35%)
===================
Est FTT:  2.67 C
Est FTT PnL: 1.04 C (64.19%)
===================
Deployed:  1.46 C
Current:  1.62 C
CAGR/XIRR %: 4.92%

In [9]:
# top 5 near their targets
cols = ['Symbol', 'Today P/L%', 'Current P/L%', 'FTT%', 'OTT%', 'FTT Amt', 'Current P/L', 'Current', 'FTT', 'Dev%_PE', 'RSI_14','Conviction', 'Spread%',  'CumlRnk', 'RRR Ind', 'CurrAlloc%', 'Gained%', 'Criteria', 'Strategy', 'Category']
df_tmp = df_portfolio_features[~df_portfolio_features['Symbol'].isin(['ENRIN','BLUSPRING','DIGITIDE'])]
df_tmp = df_tmp.sort_values(by = 'FTT Amt', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
55,MEDANTA,-1.73,20.64,5.37,27.12,11436.0,36438.0,212955.0,1486.00,16.99,60.0,X-SC,14.57,87.0,3.19,1.33,46.74,XY24,NTT,HEALTHCARE
79,TTKPRESTIG,-0.40,-18.33,22.56,0.09,18567.0,-18476.0,82301.0,770.00,91.04,49.0,M-SC,13.75,250.0,-1.00,0.51,48.13,OX40N,NTT,DURABLES
80,UNITDSPR,-0.33,11.66,8.16,20.77,21334.0,27296.0,261440.0,1644.00,-0.92,71.0,X-MC,6.70,64.0,1.28,1.63,25.67,X40N,NTT,BREWERIES
52,M&M,0.65,9.11,8.90,18.82,23372.0,21929.0,262610.0,3762.88,-5.04,70.0,X-LC,6.22,25.0,0.94,1.64,19.13,X40N,ATH,AUTO
69,SIS,0.12,-1.12,22.63,21.26,24845.0,-1242.0,109790.0,528.00,2620.73,51.0,H-SC,23.22,168.0,-0.05,0.69,63.24,OX40N,NTT,MISC

In [10]:
# top 5 today
df_tmp = df_portfolio_features.sort_values(by = 'Today P/L%', ascending=False)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
12,BOSCH-HCIL,5.86,-33.23,49.76,-0.01,42462.0,-42472.0,85333.0,2282.00,17356.52,77.0,M-SC,5.19,231.0,-1.00,0.53,45.25,OX40N,BTT,AC
49,KANSAINER,5.76,-29.79,61.61,13.47,116654.0,-80325.0,189342.0,340.00,-39.58,58.0,H-SC,5.89,162.0,-0.69,1.18,33.83,XY24,NTT,PAINTS
5,ATULAUTO,4.15,0.20,45.28,45.57,89438.0,391.0,197523.0,844.00,4300.00,78.0,M-SC,7.69,248.0,0.00,1.23,52.00,XY24,NTT,AUTO
0,5PAISA,3.95,-30.09,61.49,12.90,93929.0,-65741.0,152755.0,593.00,124.76,53.0,H-SC,12.12,170.0,-0.70,0.95,47.41,OX40N,NTT,FINANCE
30,HAPPSTMNDS,3.27,-49.96,265.90,83.08,170516.0,-64037.0,64128.0,1466.54,-40.49,65.0,H-SC,10.95,152.0,-0.38,0.40,20.12,AR,ATH,IT

In [11]:
# bottom 5 today
df_tmp = df_portfolio_features.sort_values(by = 'Today P/L%', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
81,VAIBHAVGBL,-7.39,-22.81,108.28,60.77,152767.0,-41690.0,141085.0,521.00,62.53,47.0,H-SC,12.29,160.0,-0.27,0.88,43.54,XR,NTT,JEWELLERY
72,SYMPHONY,-4.10,-50.65,102.56,-0.03,86624.0,-86679.0,84462.0,1306.00,-60.32,32.0,M-SC,14.06,205.0,-1.00,0.53,0.00,OX40N,NTT,DURABLES
27,GLAXO,-2.92,3.16,31.54,35.69,64839.0,6292.0,205576.0,3380.16,-21.29,57.0,X-MC,6.38,56.0,0.10,1.28,22.18,X40,ATH,PHARMA
58,QUESS,-2.65,28.99,34.82,73.90,47965.0,30958.0,137751.0,424.00,-30.58,60.0,X-SC,38.48,80.0,0.65,0.86,87.78,XY24,NTT,MISC
84,VOLTAS,-2.05,1.74,42.71,45.20,83317.0,3333.0,195075.0,1856.00,16.53,45.0,X-MC,4.36,79.0,0.04,1.22,6.92,XY25,NTT,AC

In [12]:
# top 5 to exit based on CumlRnk
df_tmp = df_portfolio_features[~df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])]
df_tmp = df_tmp[(df_tmp['Current P/L%'] > -1) & (df_tmp['Current P/L%'] < 1)].sort_values(by = 'CumlRnk', ascending=False)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
5,ATULAUTO,4.15,0.20,45.28,45.57,89438.0,391.0,197523.0,844.0,4300.00,78.0,M-SC,7.69,248.0,0.00,1.23,52.00,XY24,NTT,AUTO
61,RECLTD,-0.54,-0.92,21.86,20.74,44004.0,-1870.0,201300.0,446.0,9.37,58.0,M-MC,2.95,191.0,-0.04,1.26,21.34,XY25,NTT,FINANCE

In [13]:
# OX40N stocks to exit
df_tmp = df_portfolio_features[(df_portfolio_features['Symbol'].isin(list_ox40n))].sort_values(by = 'Current P/L%', ascending=False)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
25,FINCABLES,1.02,27.08,63.61,107.91,119349.0,39982.0,187626.0,1641.55,14.16,45.0,M-SC,18.08,220.0,0.34,1.17,41.16,OX40N,ATH,CABLES
69,SIS,0.12,-1.12,22.63,21.26,24845.0,-1242.0,109790.0,528.00,2620.73,51.0,H-SC,23.22,168.0,-0.05,0.69,63.24,OX40N,NTT,MISC
16,CERA,-0.10,-17.70,50.53,23.89,73154.0,-31129.0,144774.0,9475.00,-20.53,57.0,H-SC,13.03,153.0,-0.43,0.90,40.73,OX40N,NTT,CERAMICS
79,TTKPRESTIG,-0.40,-18.33,22.56,0.09,18567.0,-18476.0,82301.0,770.00,91.04,49.0,M-SC,13.75,250.0,-1.00,0.51,48.13,OX40N,NTT,DURABLES
43,INDIGOPNTS,0.15,-22.51,29.08,0.02,39333.0,-39300.0,135259.0,1408.00,106.47,57.0,M-SC,4.36,222.0,-1.00,0.84,53.46,OX40N,NTT,PAINTS

In [14]:
# top 5 to book for rotation
df_tmp = df_portfolio_features[(df_portfolio_features['Current P/L%'] > 20) ].sort_values(by = 'CumlRnk', ascending=False)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
25,FINCABLES,1.02,27.08,63.61,107.91,119349.0,39982.0,187626.0,1641.55,14.16,45.0,M-SC,18.08,220.0,0.34,1.17,41.16,OX40N,ATH,CABLES
55,MEDANTA,-1.73,20.64,5.37,27.12,11436.0,36438.0,212955.0,1486.00,16.99,60.0,X-SC,14.57,87.0,3.19,1.33,46.74,XY24,NTT,HEALTHCARE
58,QUESS,-2.65,28.99,34.82,73.90,47965.0,30958.0,137751.0,424.00,-30.58,60.0,X-SC,38.48,80.0,0.65,0.86,87.78,XY24,NTT,MISC

In [15]:
# top 5 to monitor for exit
df_tmp = df_portfolio_features[~df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])]
df_tmp = df_tmp[(df_tmp['Current P/L%'] > 0) ].sort_values(by = 'Dev%_PE', ascending=False)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
5,ATULAUTO,4.15,0.20,45.28,45.57,89438.0,391.0,197523.0,844.00,4300.00,78.0,M-SC,7.69,248.0,0.00,1.23,52.00,XY24,NTT,AUTO
70,STARHEALTH,0.07,13.80,29.40,47.26,94058.0,38803.0,319926.0,761.00,79.65,52.0,H-SC,18.47,173.0,0.41,2.00,38.33,XY24,NTT,INSURANCE
25,FINCABLES,1.02,27.08,63.61,107.91,119349.0,39982.0,187626.0,1641.55,14.16,45.0,M-SC,18.08,220.0,0.34,1.17,41.16,OX40N,ATH,CABLES
87,ZYDUSLIFE,-0.79,18.22,14.62,35.51,36223.0,38189.0,247763.0,1285.01,2.70,51.0,H-MC,16.15,120.0,1.05,1.55,30.39,AR,ATH,PHARMA

In [16]:
# top 5 to book for rotation from weak conviction
df_tmp = df_portfolio_features[~df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])]
df_tmp = df_tmp[~df_tmp['Criteria'].isin(['XY25','XY24','X40', 'X40N'])].sort_values(by = 'RRR Ind', ascending=False)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
87,ZYDUSLIFE,-0.79,18.22,14.62,35.51,36223.0,38189.0,247763.0,1285.01,2.70,51.0,H-MC,16.15,120.0,1.05,1.55,30.39,AR,ATH,PHARMA
25,FINCABLES,1.02,27.08,63.61,107.91,119349.0,39982.0,187626.0,1641.55,14.16,45.0,M-SC,18.08,220.0,0.34,1.17,41.16,OX40N,ATH,CABLES
69,SIS,0.12,-1.12,22.63,21.26,24845.0,-1242.0,109790.0,528.00,2620.73,51.0,H-SC,23.22,168.0,-0.05,0.69,63.24,OX40N,NTT,MISC
3,ALKYLAMINE,0.97,-17.38,133.06,92.54,110987.0,-17552.0,83411.0,4520.85,-11.57,64.0,H-SC,13.53,142.0,-0.16,0.52,58.39,SR,ATH,CHEMICALS
42,INDIAMART,0.05,-23.69,163.31,100.92,153694.0,-29224.0,94112.0,4675.60,-65.62,37.0,H-SC,11.36,140.0,-0.19,0.59,1.88,AR,ATH,MISC

In [17]:
# top 5 to accumulate based on lowest RSI_14
df_tmp = df_portfolio_features[df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])].sort_values(by = 'RSI_14', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
83,VBL,-0.46,-11.44,53.19,35.66,165730.0,-40263.0,311581.0,669.42,-22.02,34.0,X-LC,7.72,13.0,-0.24,1.94,14.72,X40N,ATH,FMCG
57,PGHH,-1.79,-36.42,107.64,32.01,146123.0,-77768.0,135752.0,17616.87,-57.06,35.0,X-MC,19.17,57.0,-0.53,0.85,0.09,X40,ATH,FMCG
34,HDFCBANK,-0.94,-10.23,45.99,31.05,121013.0,-29990.0,263130.0,1073.00,-25.47,36.0,X-LC,9.97,26.0,-0.25,1.64,2.13,X40,BTT,BANKS
20,DABUR,1.06,-19.06,77.54,43.70,155693.0,-47278.0,200790.0,735.00,-26.49,41.0,X-MC,8.91,70.0,-0.30,1.25,2.17,XY24,BTT,FMCG
35,HDFCLIFE,1.69,-6.54,48.88,39.15,114550.0,-16387.0,234350.0,811.41,-30.46,42.0,X-LC,15.94,31.0,-0.14,1.46,1.69,X40,ATH,INSURANCE

In [18]:
# top 5 to accumulate based on Spread and CumlRnk
df_tmp = df_portfolio_features[df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])]
df_tmp = df_tmp[(df_tmp['CumlRnk'] < 100)].sort_values(by = 'Spread%', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
19,COLPAL,1.49,-22.54,80.56,39.86,164342.0,-59365.0,204000.0,3683.41,-6.30,46.0,X-MC,1.68,62.0,-0.36,1.27,15.39,XY25,ATH,FMCG
11,BERGEPAINT,2.91,0.47,24.72,25.32,64017.0,1221.0,258970.0,680.00,-5.01,69.0,X-MC,1.85,68.0,0.02,1.62,35.80,XY24,NTT,PAINTS
8,BAJAJHLDNG,0.18,3.28,24.17,28.24,63907.0,8403.0,264408.0,14274.15,-4.76,70.0,X-LC,2.39,28.0,0.13,1.65,33.08,X40,ATH,FINANCE
23,DMART,-1.91,-3.81,36.63,31.42,109852.0,-11894.0,299896.0,5391.45,-20.05,44.0,X-LC,3.00,14.0,-0.11,1.87,8.22,X40N,ATH,FMCG
17,CIPLA,-0.08,11.29,12.98,25.73,34841.0,27223.0,268419.0,1648.14,-8.67,56.0,X-LC,3.25,18.0,0.78,1.68,23.49,X40N,ATH,PHARMA

In [19]:
# top 5 to accumulate based on lowest Gained%
df_tmp = df_portfolio_features[df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])].sort_values(by = 'Gained%', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
57,PGHH,-1.79,-36.42,107.64,32.01,146123.0,-77768.0,135752.0,17616.87,-57.06,35.0,X-MC,19.17,57.0,-0.53,0.85,0.09,X40,ATH,FMCG
63,RELIANCE,-0.84,-12.40,52.50,33.59,137088.0,-36957.0,261120.0,1952.00,-20.03,45.0,X-LC,7.78,21.0,-0.27,1.63,1.68,XY25,BTT,REFINERIES
35,HDFCLIFE,1.69,-6.54,48.88,39.15,114550.0,-16387.0,234350.0,811.41,-30.46,42.0,X-LC,15.94,31.0,-0.14,1.46,1.69,X40,ATH,INSURANCE
34,HDFCBANK,-0.94,-10.23,45.99,31.05,121013.0,-29990.0,263130.0,1073.00,-25.47,36.0,X-LC,9.97,26.0,-0.25,1.64,2.13,X40,BTT,BANKS
20,DABUR,1.06,-19.06,77.54,43.70,155693.0,-47278.0,200790.0,735.00,-26.49,41.0,X-MC,8.91,70.0,-0.30,1.25,2.17,XY24,BTT,FMCG

In [20]:
# top 5 to accumulate based on lowest CurrAlloc%
df_tmp = df_portfolio_features[df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])].sort_values(by = 'CurrAlloc%', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
10,BATAINDIA,2.89,-52.91,187.10,35.20,113371.0,-68076.0,60594.0,2096.00,-20.58,67.0,X-SC,15.10,91.0,-0.60,0.38,21.74,X40,NTT,FOOTWEAR
62,RELAXO,2.35,-46.10,182.59,52.31,142851.0,-66924.0,78236.0,1176.00,-42.60,58.0,X-SC,10.55,92.0,-0.47,0.49,74.93,X40N,NTT,FOOTWEAR
57,PGHH,-1.79,-36.42,107.64,32.01,146123.0,-77768.0,135752.0,17616.87,-57.06,35.0,X-MC,19.17,57.0,-0.53,0.85,0.09,X40,ATH,FMCG
58,QUESS,-2.65,28.99,34.82,73.90,47965.0,30958.0,137751.0,424.00,-30.58,60.0,X-SC,38.48,80.0,0.65,0.86,87.78,XY24,NTT,MISC
2,ACC,0.67,-37.61,180.20,74.81,301439.0,-100848.0,167280.0,3906.00,-55.67,57.0,X-SC,12.40,85.0,-0.33,1.04,11.75,XY24,BTT,CEMENT

In [21]:
# top 5 to accumulate based on CumlRnk
df_tmp = df_portfolio_features.sort_values(by = 'CumlRnk', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
47,ITC,-0.71,-20.84,57.52,24.70,180899.0,-82781.0,314497.0,452.00,-58.35,54.0,X-LC,11.98,1.0,-0.46,1.96,4.14,X40,NTT,FMCG
75,TCS,-1.91,-29.16,75.33,24.20,247209.0,-135105.0,328168.0,4230.71,-40.02,62.0,X-LC,16.07,2.0,-0.55,2.05,22.38,X40,ATH,IT
45,INFY,0.56,-16.43,67.97,40.38,213855.0,-61838.0,314632.0,1972.00,-37.23,63.0,X-LC,16.66,3.0,-0.29,1.96,19.15,X40,NTT,IT
77,TMPV,0.36,-16.78,71.53,42.75,247710.0,-69805.0,346302.0,600.00,-83.62,58.0,X-LC,5.97,4.0,-0.28,2.16,19.08,XY24,NTT,AUTO
33,HCLTECH,-1.45,-9.71,37.29,23.97,104207.0,-30036.0,279450.0,1853.42,-7.78,70.0,X-LC,14.17,8.0,-0.29,1.74,31.87,X40,ATH,IT

In [22]:
# top 5 for average up
df_tmp = df_portfolio_features[(df_portfolio_features['Dev%_200'] > 5)].sort_values(by = 'CurrAlloc%', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
44,INDUSINDBK,-0.68,-24.77,76.64,32.89,44515.0,-19124.0,58083.0,1800.00,-373.11,56.0,L-MC,14.30,258.0,-0.43,0.36,43.20,XR,NTT,BANKS
18,COFFEEDAY,1.46,-42.31,134.47,35.27,88091.0,-48039.0,65510.0,80.00,-55.73,66.0,L-SC,5.49,266.0,-0.55,0.41,61.55,XR,NTT,HOTELS
62,RELAXO,2.35,-46.10,182.59,52.31,142851.0,-66924.0,78236.0,1176.00,-42.60,58.0,X-SC,10.55,92.0,-0.47,0.49,74.93,X40N,NTT,FOOTWEAR
79,TTKPRESTIG,-0.40,-18.33,22.56,0.09,18567.0,-18476.0,82301.0,770.00,91.04,49.0,M-SC,13.75,250.0,-1.00,0.51,48.13,OX40N,NTT,DURABLES
3,ALKYLAMINE,0.97,-17.38,133.06,92.54,110987.0,-17552.0,83411.0,4520.85,-11.57,64.0,H-SC,13.53,142.0,-0.16,0.52,58.39,SR,ATH,CHEMICALS

In [23]:
# top 5 RSP
df_tmp = df_portfolio_features.sort_values(by = 'RSP', ascending=False)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
33,HCLTECH,-1.45,-9.71,37.29,23.97,104207.0,-30036.0,279450.0,1853.42,-7.78,70.0,X-LC,14.17,8.0,-0.29,1.74,31.87,X40,ATH,IT
75,TCS,-1.91,-29.16,75.33,24.20,247209.0,-135105.0,328168.0,4230.71,-40.02,62.0,X-LC,16.07,2.0,-0.55,2.05,22.38,X40,ATH,IT
13,BSOFT,0.14,-41.32,153.24,48.59,126471.0,-58122.0,82531.0,819.60,-24.62,65.0,H-SC,18.30,172.0,-0.46,0.52,20.66,XR,ATH,IT
30,HAPPSTMNDS,3.27,-49.96,265.90,83.08,170516.0,-64037.0,64128.0,1466.54,-40.49,65.0,H-SC,10.95,152.0,-0.38,0.40,20.12,AR,ATH,IT
5,ATULAUTO,4.15,0.20,45.28,45.57,89438.0,391.0,197523.0,844.00,4300.00,78.0,M-SC,7.69,248.0,0.00,1.23,52.00,XY24,NTT,AUTO

In [24]:
# Top N allocation
df_tmp = df_portfolio_features.sort_values(by = 'CurrAlloc%', ascending=False)
top_n_values = [10, 25, 50]

sum_df = pd.DataFrame({
    'Top_N': top_n_values,
    'Sum_Alloc%': [df_tmp['CurrAlloc%'].head(n).sum() for n in top_n_values]
})

sum_df

   Top_N  Sum_Alloc%
0     10       19.67
1     25       44.64
2     50       76.83

In [25]:
# market-cap-wise allocation
df_tmp = df_portfolio_features[cols]
df_tmp.groupby(df_tmp['Conviction'].str[-2:])['CurrAlloc%'].sum().sort_values(ascending=False)

Conviction
SC    39.36
LC    37.59
MC    23.00
Name: CurrAlloc%, dtype: float64

In [26]:
# criteria-wise allocation
df_portfolio_features.groupby('Criteria')['CurrAlloc%'].sum().sort_values(ascending=False)

Criteria
X40      26.39
XY24     25.18
X40N     18.45
XR        9.15
XY25      7.20
OX40N     6.70
AR        6.02
SR        0.86
Name: CurrAlloc%, dtype: float64

In [27]:
# conviction-wise allocation
df_portfolio_features.groupby('Conviction')['CurrAlloc%'].sum().sort_values(ascending=False)

Conviction
X-LC    35.54
H-SC    19.25
X-MC    18.79
X-SC     9.89
M-SC     9.67
H-MC     2.59
M-MC     1.26
H-LC     1.24
M-LC     0.81
L-SC     0.55
L-MC     0.36
Name: CurrAlloc%, dtype: float64

In [28]:
# sector-wise stats
df_tmp = df_portfolio_features.groupby('Category')[['CurrAlloc%', 'Current', 'Current P/L', 'FTT Amt']].sum().sort_values(by=['Current', 'Current P/L'], ascending=False)
df_tmp['Current P/L%'] = round(df_tmp['Current P/L'] * 100 / df_tmp['Current'], 2)
df_tmp['FTT%'] = round(df_tmp['FTT Amt'] * 100 / df_tmp['Current'], 2)
cols = ['CurrAlloc%', 'Current P/L%', 'FTT%']
df_tmp[cols].sort_values(by=['CurrAlloc%'], ascending=False)

               CurrAlloc%  Current P/L%    FTT%
Category
FMCG                15.39        -20.77   64.27
IT                  11.13        -33.66   99.99
FINANCE              9.36        -13.90   61.76
AUTO                 8.42         -0.17   36.27
MISC                 7.08        -18.35   69.13
BANKS                6.04        -10.35   57.93
INSURANCE            5.62         -3.08   39.53
PHARMA               5.55          6.70   19.76
PAINTS               5.40        -13.91   33.34
ELECTRICAL           4.13         -6.82   44.23
HEALTHCARE           2.03         -9.91   38.60
APPARELS             1.76          4.99   26.92
AC                   1.75        -13.96   44.86
FOOTWEAR             1.67        -64.94  131.08
BREWERIES            1.63         10.44    8.16
REFINERIES           1.63        -14.15   52.50
DURABLES             1.50        -60.38   99.40
TRAVEL               1.44        -94.19  191.42
CERAMICS             1.38        -38.39   80.43
ENGINEERING          1.21        -24.53   81.49
CABLES               1.17         21.31   63.61
CHEMICALS            1.13        -46.30  165.05
CEMENT               1.04        -60.29  180.20
JEWELLERY            1.02        -95.46  163.37
ENTERTAINMENT        0.68        -76.74  182.15
HOTELS               0.41        -73.33  134.47
TEXTILES             0.38        -49.94   92.69

In [29]:
# money to be made criteria-wise
df_portfolio_features.groupby('Criteria')['FTT Amt'].agg(['sum', 'count']).sort_values(by='sum', ascending=False)

                sum  count
Criteria
XY24      3366279.0     20
X40       1993618.0     18
XR        1334280.0     13
X40N      1125164.0     12
AR        1067591.0      8
OX40N      715741.0     10
XY25       545878.0      5
SR         279359.0      2

In [30]:
# money to be made conviction-wise
df_portfolio_features.groupby('Conviction')['FTT Amt'].agg(['sum', 'count']).sort_values(by='sum', ascending=False)

                  sum  count
Conviction
H-SC        3270431.0     23
X-LC        2364079.0     20
X-MC        1441512.0     14
M-SC        1363575.0     14
X-SC        1218093.0      9
H-MC         283574.0      2
L-SC         202754.0      2
M-LC         161941.0      1
L-MC          44515.0      1
M-MC          44004.0      1
H-LC          33432.0      1

In [31]:
# money to be made criteria and conviction-wise
df_portfolio_features.groupby(['Conviction', 'Criteria'])['FTT Amt'].agg(['sum', 'count']).sort_values(by='sum', ascending=False)

                           sum  count
Conviction Criteria
X-LC       X40       1147058.0      9
H-SC       XY24       982099.0      5
           AR         921842.0      5
           XR         792388.0      7
M-SC       XY24       789636.0      6
X-SC       XY24       718452.0      4
X-MC       X40        634452.0      7
X-LC       X40N       497940.0      6
           XY24       409031.0      2
X-MC       X40N       339691.0      3
M-SC       OX40N      306335.0      5
H-SC       OX40N      294743.0      4
X-SC       X40N       287533.0      3
H-SC       SR         279359.0      2
X-LC       XY25       254215.0      2
X-MC       XY25       247659.0      2
H-MC       XY24       247351.0      1
X-MC       XY24       219710.0      2
X-SC       X40        212108.0      2
M-SC       XR         191510.0      2
M-LC       XR         161941.0      1
L-SC       OX40N      114663.0      1
           XR          88091.0      1
M-SC       AR          76094.0      1
X-LC       XR          55835.0      1
L-MC       XR          44515.0      1
M-MC       XY25        44004.0      1
H-MC       AR          36223.0      1
H-LC       AR          33432.0      1

In [32]:
# notebook execution time

end_time = time.time()
execution_time = round(end_time - start_time, 0)
print(f"Notebook execution time: {execution_time} seconds")

Notebook execution time: 50.0 seconds