<a href="https://colab.research.google.com/github/ankit-rathi/Quantvesting_v2/blob/main/myStocks_Portfolio_Analysis.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
'''
!pip install pandas==2.2.2 -qq
!pip install pyxirr -qq
!pip install ta -qq
!pip install yfinance==0.2.59 -qq
'''

'\n!pip install pandas==2.2.2 -qq\n!pip install pyxirr -qq\n!pip install ta -qq\n!pip install yfinance==0.2.59 -qq\n'

In [2]:
# import libraries

import numpy as np
import pandas as pd
import datetime
import warnings
warnings.filterwarnings('ignore')
import yfinance as yfin
import ta
import matplotlib.pyplot as plt
import requests

In [3]:
# notebook start time
import time
import datetime
import pytz

start_time = time.time()

# function to print date timestamp
def print_date_time():
  tz_NY = pytz.timezone('Asia/Kolkata')
  datetime_NY = datetime.datetime.now(tz_NY)
  print("Run date time (IST):", datetime_NY.strftime("%Y-%m-%d %H:%M:%S"))

In [4]:
# function to get booked and reserved amount
def get_amt():
  # fetch the JSON data from the URL
  url = "https://raw.githubusercontent.com/ankit-rathi/Tradevesting_v1/main/data/myPortfolioAmts.json"
  response = requests.get(url)
  pf_amts = response.json()  # parse the JSON data

  # extract values from the JSON
  py_booked_amt_dm = pf_amts["py_booked_amt_dm"]
  py_booked_amt_sv = pf_amts["py_booked_amt_sv"]
  cy_booked_amt_dm = pf_amts["cy_booked_amt_dm"]
  cy_booked_amt_sv = pf_amts["cy_booked_amt_sv"]
  reserve_amt_dm = pf_amts["reserve_amt_dm"]
  reserve_amt_sv = pf_amts["reserve_amt_sv"]

  # perform calculations
  py_booked_amt = py_booked_amt_dm + py_booked_amt_sv
  cy_booked_amt = cy_booked_amt_dm + cy_booked_amt_sv
  reserve_amt = reserve_amt_dm + reserve_amt_sv
  total_booked_amt = py_booked_amt + cy_booked_amt

  return total_booked_amt, reserve_amt, cy_booked_amt, py_booked_amt

gen_output = 0

In [5]:
# function to format the amount
def format_amt(number):
    abs_number = abs(number)

    if abs_number >= 1_00_00_000:  # Crores
        formatted_amt = f"{number / 1_00_00_000:.2f} C"
    elif abs_number >= 1_00_000:  # Lakhs
        formatted_amt = f"{number / 1_00_000:.2f} L"
    elif abs_number >= 1_000:  # Thousands
        formatted_amt = f"{number / 1_000:.2f} K"
    else:
        formatted_amt = f"{number:.2f}"

    return formatted_amt

# function to set start and end date
def get_start_end_date():
  start_date = (datetime.date.today() + datetime.timedelta(days=-365)).strftime('%Y-%m-%d')
  end_date = (datetime.date.today() + datetime.timedelta(days=1)).strftime('%Y-%m-%d')
  return start_date, end_date

# function to fetch my portfolio csv
def get_mypfs_df():
  mypfs_df = pd.read_csv('https://raw.githubusercontent.com/ankit-rathi/Tradevesting_v1/main/data/myPortfolioStocks.csv')
  return mypfs_df

# function to fetch my prospects csv
def get_mypps_df():
  mypps_df = pd.read_csv('https://raw.githubusercontent.com/ankit-rathi/Tradevesting_v1/main/data/myProspectsScrips.csv')
  return mypps_df

# function to fetch screener data
def get_myscreen_df():
  myscreen_df = pd.read_csv('https://raw.githubusercontent.com/ankit-rathi/Tradevesting_v1/main/data/myScreenerDB.csv')
  return myscreen_df

# function to fetch momentum data
def get_myinvmt_df():
  myinvmt_df = pd.read_csv('https://raw.githubusercontent.com/ankit-rathi/Tradevesting_v1/main/data/myInvestments.csv')
  return myinvmt_df

# function to get the stock ids
def get_stock_ids(df_pf):
  stock_n100 = df_pf['Symbol'].unique()

  exclude = ['CADILAHC','MMTC', 'MASFIN']

  stock_ids = df_pf[~df_pf['Symbol'].isin(exclude) ]['Symbol'].unique()

  #mypf = mypf[mypf.Forecast.notnull()]
  #stock_ids = mypf['Symbol'].unique()

  #stock_ids.sort()
  return stock_ids

# get features from screener data
def get_screener_features():
  myscreen_df = get_myscreen_df()
  cols = ['Symbol', 'EPS', 'MedPE', 'ROCE%', 'ROE%', 'CapType']
  return myscreen_df[cols]

# get relative strength
def get_relative_strength(stock_list):

    # Dictionary to store stock tickers and their corresponding percentage price change
    stock_changes = {}

    # Loop through each stock and fetch its price data
    for stock in stock_list:
        try:
            # Download the stock data for the given date range
            stock_data = yfin.Ticker(stock + '.NS').history(period='1mo', interval='1d')[map(str.title, ['open', 'close', 'low', 'high', 'volume'])]

            # Calculate the percentage change for the stock
            if len(stock_data) > 0:
                start_price = stock_data['Close'].iloc[0]
                end_price = stock_data['Close'].iloc[-1]
                percent_change = round(((end_price - start_price) / start_price) * 100, 2)
                stock_changes[stock] = percent_change
            else:
                stock_changes[stock] = np.nan  # If no data is available, set to NaN

        except Exception as e:
            print(f"Error fetching data for {stock}: {e}")
            stock_changes[stock] = np.nan

    # Create a DataFrame with stock tickers and their percentage changes
    df = pd.DataFrame(list(stock_changes.items()), columns=['Symbol', 'Percent_Change'])

    # Drop any stocks with missing data (NaN values)
    df = df.dropna()

    # Calculate the percentile rank based on percentage change
    df['RSP'] = round(df['Percent_Change'].rank(pct=True) * 100, 2)
    cols = ['Symbol', 'RSP']
    df = df[cols]
    # Sort by percentile rank (optional)
    df = df.sort_values(by='RSP', ascending=False).reset_index(drop=True)

    return df

In [6]:
# function to get stock technicals
def stock_prec_dev(stock_symbol):
    #stock_symbol = 'ULTRACEMCO.NS'
    short_window = 20
    mid_window = 50
    long_window = 200
    moving_avg = 'SMA'

    start = datetime.datetime(*map(int, start_date.split('-')))
    end = datetime.datetime(*map(int, end_date.split('-')))

    stock_df = yfin.Ticker(stock_symbol + '.NS').history(period='max', interval='1d')[map(str.title, ['open', 'close', 'low', 'high', 'volume'])]

    stock_df['Max'] = round(max(stock_df['Close']),2)
    stock_df = stock_df[(stock_df.index <= end_date) & (stock_df.index >= start_date)]
    stock_df['200_SMA'] = round(stock_df['Close'].rolling(window = 200, min_periods = 1).mean(),0)
    stock_df['Dev%_200'] = round((stock_df['Close'] - stock_df['200_SMA'])*100/stock_df['200_SMA'],2)
    stock_df.dropna(axis = 0, inplace = True) # remove any null rows

    stock_df['20_SMA'] = stock_df['Close'].rolling(window=20).mean()
    stock_df['50_SMA'] = stock_df['Close'].rolling(window=50).mean()
    stock_df['Symbol'] = stock_symbol

    stock_df['Close'] = round(stock_df['Close'],2)
    stock_df['Min'] = round(min(stock_df['Close']),2)
    stock_df['RSI_14'] = ta.momentum.RSIIndicator(close=stock_df['Close'], window=14).rsi()
    stock_df['RSI_14'] = round(stock_df['RSI_14'],0)
    stock_df['Prev_Close'] = stock_df['Close'].shift(1)
    stock_df.drop(['Open', 'Low', 'High', 'Volume'], axis=1, inplace=True)
    stock_df = stock_df.tail(1)

    max_SMA = max(stock_df['20_SMA'].item(), stock_df['50_SMA'].item(), stock_df['200_SMA'].item())
    min_SMA = min(stock_df['20_SMA'].item(), stock_df['50_SMA'].item(), stock_df['200_SMA'].item())
    ABS_Spread = max_SMA - min_SMA
    stock_df['Spread%'] = round((ABS_Spread / stock_df['200_SMA'].item()) * 100,2)

    return stock_df

# function to compute stock attributes
def get_common_features(stock_ids, df_mypf):

  df_prec_dev = pd.DataFrame()
  df_tmp = get_screener_features()
  df_rs = get_relative_strength(stock_ids)

  for stock_id in stock_ids:
      tmp = stock_prec_dev(stock_id)
      tmp = tmp.reset_index()
      df_prec_dev = pd.concat([df_prec_dev, tmp], ignore_index = True)
  df_prec_dev = pd.merge(df_prec_dev, df_mypf, on= 'Symbol')
  df_prec_dev = pd.merge(df_prec_dev, df_tmp, on= 'Symbol', how='left')
  df_prec_dev = pd.merge(df_prec_dev, df_rs, on= 'Symbol', how='left')
  #print(df_prec_dev.columns)
  df_prec_dev['Curr_PE'] = round(df_prec_dev['Close']/df_prec_dev['EPS'],1)
  df_prec_dev['Dev%_PE'] = round((df_prec_dev['Curr_PE'] - df_prec_dev['MedPE'])*100/df_prec_dev['MedPE'],2)
  df_prec_dev['Conviction'] = df_prec_dev['Conviction'] + '-' + df_prec_dev['CapType']
  return df_prec_dev

# function to arrange stock features
def arrange_features(df_stocks, common_cols, diff_cols):
  df_stocks_common = df_stocks[common_cols].drop_duplicates()
  df_stocks_diff = df_stocks[diff_cols]
  df_stocks_diff['Investment'] = df_stocks_diff['AvgCost'] * df_stocks_diff['Shares']
  df_stocks_diff = df_stocks_diff.groupby(['Symbol'])[['Shares', 'Investment']].aggregate(['sum']).reset_index()
  df_stocks_diff.columns = ['Symbol', 'Shares', 'Investment']
  df_stocks_diff['AvgCost'] = round(df_stocks_diff['Investment']/df_stocks_diff['Shares'],2)
  df_stocks = pd.merge(df_stocks_diff, df_stocks_common, on='Symbol')
  return df_stocks

# plot fact distribution across dimension
def plot_pie_chart(df, dimension, fact):
  # grouping the data by category and calculating the sum of fact for each type
  grouped_data = df.groupby(dimension)[fact].sum()

  # sorting the grouped data in descending order
  grouped_data = grouped_data.sort_values(ascending=False)

  # creating a pie chart
  grouped_data.plot.pie(autopct='%1.1f%%', startangle=90, figsize=(6, 6))

  # adding a title and displaying the plot
  plt.title(f'{dimension} {fact} Distribution')
  plt.ylabel('')  # To hide the y-label
  plt.show()

In [7]:
# function to get portfolio features

def get_portfolio_features(df_common_features):

  print_date_time()
  print('-------------------')

  #df_common_features["Target"] = df_common_features["Target"].fillna(df_common_features["Max"])
  df_common_features['NTT'] = np.where(df_common_features['Strategy']== 'NTT', df_common_features["Target"], df_common_features['Max'])
  df_common_features['LTT'] = np.where(df_common_features['Strategy']== 'BTT', df_common_features["Target"], df_common_features['Max'])
  df_common_features['BOL'] = df_common_features['Min']

  tmp_df = df_common_features[df_common_features['Symbol'].isin(mypf_df[mypf_df['InPortfolio'] != 'NA'].Symbol.values)]
  print('qualified stocks: '+str(len(tmp_df['Symbol'].unique())))
  tmp_df1 = tmp_df[tmp_df['LatestQtr'] == 1]
  print('with latest results: '+str(len(tmp_df1['Symbol'].unique())))
  tmp_df1 = tmp_df1[tmp_df1['StarStock'] == 1]
  print('still star stocks: '+str(len(tmp_df1['Symbol'].unique())))
  tmp_df['Investment'] = tmp_df['AvgCost'] * tmp_df['Shares']
  tmp_df['Current'] = round(tmp_df['Close'] * tmp_df['Shares'],0)
  tmp_df['Previous'] = tmp_df['Prev_Close'] * tmp_df['Shares']
  tmp_df['EstimatedST'] = tmp_df['NTT'] * tmp_df['Shares']
  tmp_df['EstimatedLT'] = tmp_df['LTT'] * tmp_df['Shares']
  tmp_df['Current P/L'] = round((tmp_df['Current'] - tmp_df['Investment']),0)
  tmp_df['Today P/L%'] = round((tmp_df['Current'] - tmp_df['Previous'])*100/tmp_df['Previous'],2)
  tmp_df['Current P/L%'] = round((tmp_df['Current'] - tmp_df['Investment'])*100/tmp_df['Investment'],2)
  tmp_df['EstimatedST P/L%'] = round((tmp_df['EstimatedST'] - tmp_df['Investment'])*100/tmp_df['Investment'],2)
  tmp_df['EstimatedLT P/L%'] = round((tmp_df['EstimatedLT'] - tmp_df['Investment'])*100/tmp_df['Investment'],2)
  tmp_df['NTT%'] = round((tmp_df['NTT'] - tmp_df['Close'])*100/tmp_df['Close'],2)
  tmp_df['LTT%'] = round((tmp_df['LTT'] - tmp_df['Close'])*100/tmp_df['Close'],2)
  tmp_df['Gained%'] = round((tmp_df['Close'] - tmp_df['BOL'])*100/tmp_df['BOL'],2)
  investment = round(sum(tmp_df['AvgCost']*tmp_df['Shares']),0)
  current = round(sum(tmp_df['Close']*tmp_df['Shares']),0)
  tmp_df['InitAlloc%'] = round(tmp_df['Investment']*100/investment,2)
  tmp_df['CurrAlloc%'] = round(tmp_df['Current']*100/current,2)
  tmp_df['FTT'] = tmp_df['LTT']
  tmp_df.loc[tmp_df['Strategy'] == 'NTT', 'FTT'] = tmp_df['NTT']
  tmp_df['FTT%'] = tmp_df['LTT%']
  tmp_df.loc[tmp_df['Strategy'] == 'NTT', 'FTT%'] = tmp_df['NTT%']
  tmp_df['FTT Amt'] = round(tmp_df['FTT%'] * tmp_df['Current']/100,0)
  tmp_df['OTT%'] = round((tmp_df['FTT'] - tmp_df['AvgCost'])*100/tmp_df['AvgCost'],2)
  tmp_df['RRR Ind'] = round(tmp_df['Current P/L']/tmp_df['FTT Amt'],2)
  tmp_df['Risk Ind'] = round(tmp_df['Current P/L%']*tmp_df['CurrAlloc%'],0)

  return tmp_df

# function to print portfolio features
def print_portfolio_stats(df_portfolio_features, myinvmt_df):
  from pyxirr import xirr

  total_booked_amt, reserve_amt, cy_booked_amt, py_booked_amt = get_amt()

  dates = myinvmt_df['Date'].values
  dates = np.append(dates, datetime.date.today().strftime('%d-%b-%y'))
  investment = myinvmt_df['Investment'].values
  dates= pd.to_datetime(dates)

  current = round(sum(df_portfolio_features['Close']*df_portfolio_features['Shares']),0) + reserve_amt
  investment_xirr = np.append(investment, current)
  cagr = round(xirr(pd.DataFrame({"dates": dates, "amounts": investment_xirr}))*100,2)

  investment = -sum(investment)
  invested = round(sum(df_portfolio_features['AvgCost']*df_portfolio_features['Shares']),0) + reserve_amt
  previous = round(sum(df_portfolio_features['Prev_Close']*df_portfolio_features['Shares']),0) + reserve_amt
  cy_invested = investment + py_booked_amt

  today_pnl_amount = current-previous
  today_pnl_percentage = round((current-previous)*100/previous,2)

  curr_pnl_amount = current-invested
  curr_pnl_percentage = round((curr_pnl_amount)*100/(cy_invested),2)

  cy_pnl_amount = cy_booked_amt + curr_pnl_amount
  cy_pnl_percentage = round((cy_pnl_amount)*100/cy_invested,2)

  overall_pnl_amount = total_booked_amt + curr_pnl_amount
  overall_pnl_percentage = round((overall_pnl_amount)*100/investment,2)

  estimate_st = round(sum(df_portfolio_features['FTT']*df_portfolio_features['Shares']),0)  + reserve_amt
  est_st_pnl_amount = estimate_st-current
  est_st_pnl_percentage = round((est_st_pnl_amount)*100/current,2)

  estimate_lt = round(sum(df_portfolio_features['LTT']*df_portfolio_features['Shares']),0)  + reserve_amt
  est_lt_pnl_amount = estimate_lt-current
  est_lt_pnl_percentage = round((est_lt_pnl_amount)*100/current,2)

  total_profit = round(sum(df_portfolio_features[df_portfolio_features['Current P/L%'] > 0]['Current']) - sum(df_portfolio_features[df_portfolio_features['Current P/L%'] > 0]['Investment']),0)
  total_loss = round(sum(df_portfolio_features[df_portfolio_features['Current P/L%'] < 0]['Current']) - sum(df_portfolio_features[df_portfolio_features['Current P/L%'] < 0]['Investment']),0)

  cy_booked_percentage = round((cy_booked_amt)*100/current,2)
  py_booked_percentage = round((py_booked_amt)*100/investment,2)
  total_booked_percentage = round((total_booked_amt)*100/investment,2)

  print('-------------------')
  print('Initial Investment: ', format_amt(investment))
  print('CY Investment: ', format_amt(cy_invested))
  print('Reserve: ', format_amt(reserve_amt))
  print('Current: ',  format_amt(current))
  print('-------------------')
  print('Today PnL: '+ '{} ({}%)'.format(format_amt(today_pnl_amount), today_pnl_percentage))
  print('Current PnL: '+ '{} ({}%)'.format(format_amt(curr_pnl_amount), curr_pnl_percentage))
  print('CY Booked + Current PnL: '+ '{} ({}%)'.format(format_amt(cy_pnl_amount), cy_pnl_percentage))
  print('-------------------')
  print('Total profit: ', format_amt(total_profit))
  print('Total loss: ', format_amt(total_loss))
  print('-------------------')
  print('Total Booked + Current PnL: '+ '{} ({}%)'.format(format_amt(overall_pnl_amount), overall_pnl_percentage))
  print('Total Booked PnL: '+ '{} ({}%)'.format(format_amt(total_booked_amt), total_booked_percentage))
  print('Curr Year Booked PnL: '+ '{} ({}%)'.format(format_amt(cy_booked_amt), cy_booked_percentage))
  print('Prev Year Booked PnL: '+ '{} ({}%)'.format(format_amt(py_booked_amt), py_booked_percentage))
  print('===================')
  print('Est FTT: ',  format_amt(estimate_st))
  print('Est FTT PnL: '+ '{} ({}%)'.format(format_amt(est_st_pnl_amount), est_st_pnl_percentage))

  print('===================')
  print('Deployed: ', format_amt(investment))

  print('Current: ', format_amt(current))

  print('CAGR/XIRR %: '+'{}%'.format(cagr))

In [8]:
# get start and end date
start_date, end_date = get_start_end_date()

# get portfolio and prospects data
mypfs_df = get_mypfs_df()
mypps_df = get_mypps_df()
myinvmt_df = get_myinvmt_df()

# merge above datasets
mypf_df = pd.merge(mypfs_df, mypps_df, on="Symbol")

# seggregate dm and sv portfolio
dm_pf = mypf_df[mypf_df['InPortfolio'] == 'DM']
sv_pf = mypf_df[mypf_df['InPortfolio'] == 'SV']

# build portfolio stock dataframe
dm_stocks = get_stock_ids(dm_pf)
sv_stocks = get_stock_ids(sv_pf)
df_stocks = pd.concat([dm_pf,sv_pf], ignore_index = True)

# arrange common and diff stock features
common_cols = ['Symbol', 'Target', 'Criteria', 'Strategy', 'CumlRnk', 'LatestQtr', 'StarStock', 'Conviction', 'Category', 'InFolio', 'XIRR', 'MBQ']
diff_cols = ['Symbol', 'AvgCost', 'Shares']
df_stocks = arrange_features(df_stocks, common_cols, diff_cols)

# get common features
stock_ids = df_stocks['Symbol'].values
df_common_features = get_common_features(stock_ids, df_stocks)

df_common_features.reset_index(drop=True, inplace=True)
df_common_features.drop(['Date'], axis=1, inplace=True)
# get and print portfolio features
df_portfolio_features = get_portfolio_features(df_common_features)

print_portfolio_stats(df_portfolio_features, myinvmt_df)

df = df_portfolio_features
#plot_pie_chart(df, 'CapType', 'Current')
list_ox40n = list(df[df['MBQ'].str.contains('OX40N', na=False)]['Symbol'].values)

Run date time (IST): 2026-03-12 11:01:53
-------------------
qualified stocks: 86
with latest results: 26
still star stocks: 15
-------------------
Initial Investment:  1.36 C
CY Investment:  1.62 C
Reserve:  66.25 K
Current:  1.36 C
-------------------
Today PnL: -1.10 L (-0.81%)
Current PnL: -41.39 L (-25.47%)
CY Booked + Current PnL: -25.71 L (-15.82%)
-------------------
Total profit:  1.03 L
Total loss:  -42.42 L
-------------------
Total Booked + Current PnL: 1.27 L (0.94%)
Total Booked PnL: 42.66 L (31.48%)
Curr Year Booked PnL: 15.68 L (11.57%)
Prev Year Booked PnL: 26.98 L (19.91%)
===================
Est FTT:  2.47 C
Est FTT PnL: 1.12 C (82.45%)
===================
Deployed:  1.36 C
Current:  1.36 C
CAGR/XIRR %: 0.01%

In [9]:
# top 5 near their targets
cols = ['Symbol', 'Today P/L%', 'Current P/L%', 'FTT%', 'OTT%', 'FTT Amt', 'Current P/L', 'Current', 'FTT', 'Dev%_PE', 'RSI_14','Conviction', 'Spread%',  'CumlRnk', 'RRR Ind', 'CurrAlloc%', 'Gained%', 'Criteria', 'Strategy', 'Category']
df_tmp = df_portfolio_features[~df_portfolio_features['Symbol'].isin(['ENRIN','BLUSPRING','DIGITIDE'])]
df_tmp = df_tmp.sort_values(by = 'FTT Amt', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
19,COALINDIA,3.73,13.96,3.26,17.67,5590.0,20998.0,171458.0,478.51,37.73,68.0,L-LC,12.11,185.0,3.76,1.27,33.15,XY25,ATH,MINING
77,TTKPRESTIG,5.94,-26.26,35.74,0.09,26558.0,-26467.0,74310.0,770.00,72.47,58.0,M-SC,15.33,250.0,-1.00,0.55,25.55,OX40N,NTT,DURABLES
50,MASFIN,-0.13,-7.23,31.04,21.57,28215.0,-7080.0,90900.0,397.04,-20.05,39.0,H-SC,4.15,167.0,-0.25,0.67,26.10,XR,ATH,FINANCE
37,ICICIGI,-1.28,-1.94,21.70,19.34,42581.0,-3882.0,196227.0,2252.93,-17.63,41.0,X-MC,1.78,66.0,-0.09,1.45,11.92,X40,ATH,INSURANCE
78,UNITDSPR,-1.87,-0.37,21.21,20.77,49480.0,-860.0,233284.0,1644.00,-11.71,46.0,X-MC,1.39,64.0,-0.02,1.73,6.32,X40N,NTT,BREWERIES

In [10]:
# top 5 today
df_tmp = df_portfolio_features.sort_values(by = 'Today P/L%', ascending=False)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
77,TTKPRESTIG,5.94,-26.26,35.74,0.09,26558.0,-26467.0,74310.0,770.00,72.47,58.0,M-SC,15.33,250.0,-1.00,0.55,25.55,OX40N,NTT,DURABLES
19,COALINDIA,3.73,13.96,3.26,17.67,5590.0,20998.0,171458.0,478.51,37.73,68.0,L-LC,12.11,185.0,3.76,1.27,33.15,XY25,ATH,MINING
57,RECLTD,1.43,-8.55,32.03,20.74,59509.0,-17380.0,185790.0,446.00,1.56,44.0,M-MC,5.15,191.0,-0.29,1.38,4.13,XY25,NTT,FINANCE
59,RELIANCE,1.32,-9.59,38.59,25.30,70116.0,-19267.0,181696.0,1952.00,-11.96,49.0,X-LC,2.68,21.0,-0.27,1.35,21.31,XY25,BTT,REFINERIES
41,INDIGOPNTS,0.80,-41.04,69.64,0.02,71673.0,-71639.0,102920.0,1408.00,56.81,17.0,M-SC,17.26,222.0,-1.00,0.76,0.80,OX40N,NTT,PAINTS

In [11]:
# bottom 5 today
df_tmp = df_portfolio_features.sort_values(by = 'Today P/L%', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
55,RAJESHEXPO,-4.91,-78.95,375.49,0.07,108400.0,-108308.0,28869.0,518.00,958.08,21.0,L-SC,21.06,268.0,-1.00,0.21,0.00,OX40N,NTT,JEWELLERY
42,INDUSINDBK,-4.86,-38.39,115.69,32.89,55033.0,-29638.0,47569.0,1800.00,-324.09,31.0,L-MC,10.61,258.0,-0.54,0.35,31.00,XR,NTT,BANKS
69,SURYODAY,-3.31,-26.18,66.67,23.03,88132.0,-46879.0,132192.0,216.00,44.74,49.0,H-SC,7.39,166.0,-0.53,0.98,31.16,XR,NTT,BANKS
81,VBL,-3.26,-15.73,60.99,35.67,162340.0,-49668.0,266174.0,671.64,-25.54,31.0,X-LC,5.03,13.0,-0.31,1.97,0.00,X40N,ATH,FMCG
82,VOLTAS,-2.49,12.24,29.36,45.20,63189.0,23478.0,215220.0,1856.00,28.46,44.0,X-MC,9.30,79.0,0.37,1.60,19.87,XY25,NTT,AC

In [12]:
# top 5 to exit based on CumlRnk
df_tmp = df_portfolio_features[~df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])]
df_tmp = df_tmp[(df_tmp['Current P/L%'] > -1) & (df_tmp['Current P/L%'] < 1)].sort_values(by = 'CumlRnk', ascending=False)
df_tmp[cols].head()

Empty DataFrame
Columns: [Symbol, Today P/L%, Current P/L%, FTT%, OTT%, FTT Amt, Current P/L, Current, FTT, Dev%_PE, RSI_14, Conviction, Spread%, CumlRnk, RRR Ind, CurrAlloc%, Gained%, Criteria, Strategy, Category]
Index: []

In [13]:
# OX40N stocks to exit
df_tmp = df_portfolio_features[(df_portfolio_features['Symbol'].isin(list_ox40n))].sort_values(by = 'Current P/L%', ascending=False)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
27,FINCABLES,-0.05,12.40,84.97,107.91,141010.0,18309.0,165953.0,1641.55,0.96,55.0,M-SC,7.72,220.0,0.13,1.23,24.85,OX40N,ATH,CABLES
77,TTKPRESTIG,5.94,-26.26,35.74,0.09,26558.0,-26467.0,74310.0,770.00,72.47,58.0,M-SC,15.33,250.0,-1.00,0.55,25.55,OX40N,NTT,DURABLES
66,SIS,-1.54,-34.09,83.97,21.26,61453.0,-37847.0,73185.0,528.00,1713.47,34.0,H-SC,10.62,168.0,-0.62,0.54,0.89,OX40N,NTT,MISC
70,SYMPHONY,0.37,-36.92,58.47,-0.03,63127.0,-63177.0,107964.0,1306.00,-49.31,48.0,M-SC,13.68,205.0,-1.00,0.80,9.18,OX40N,NTT,DURABLES
48,KANSAINER,0.62,-37.20,80.68,13.47,136641.0,-100305.0,169362.0,340.00,-46.01,29.0,H-SC,16.72,162.0,-0.73,1.26,1.54,XY24,NTT,PAINTS

In [14]:
# top 5 to book for rotation
df_tmp = df_portfolio_features[(df_portfolio_features['Current P/L%'] > 20) ].sort_values(by = 'CumlRnk', ascending=False)
df_tmp[cols].head()

Empty DataFrame
Columns: [Symbol, Today P/L%, Current P/L%, FTT%, OTT%, FTT Amt, Current P/L, Current, FTT, Dev%_PE, RSI_14, Conviction, Spread%, CumlRnk, RRR Ind, CurrAlloc%, Gained%, Criteria, Strategy, Category]
Index: []

In [15]:
# top 5 to monitor for exit
df_tmp = df_portfolio_features[~df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])]
df_tmp = df_tmp[(df_tmp['Current P/L%'] > 0) ].sort_values(by = 'Dev%_PE', ascending=False)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
19,COALINDIA,3.73,13.96,3.26,17.67,5590.0,20998.0,171458.0,478.51,37.73,68.0,L-LC,12.11,185.0,3.76,1.27,33.15,XY25,ATH,MINING
27,FINCABLES,-0.05,12.40,84.97,107.91,141010.0,18309.0,165953.0,1641.55,0.96,55.0,M-SC,7.72,220.0,0.13,1.23,24.85,OX40N,ATH,CABLES
1,ABB,0.08,15.31,26.24,45.57,79161.0,40061.0,301680.0,7934.00,-25.90,66.0,H-MC,10.46,125.0,0.51,2.24,33.97,AR,NTT,ELECTRICAL

In [16]:
# top 5 to book for rotation from weak conviction
df_tmp = df_portfolio_features[~df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])]
df_tmp = df_tmp[~df_tmp['Criteria'].isin(['XY25','XY24','X40', 'X40N'])].sort_values(by = 'RRR Ind', ascending=False)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
1,ABB,0.08,15.31,26.24,45.57,79161.0,40061.0,301680.0,7934.00,-25.90,66.0,H-MC,10.46,125.0,0.51,2.24,33.97,AR,NTT,ELECTRICAL
27,FINCABLES,-0.05,12.40,84.97,107.91,141010.0,18309.0,165953.0,1641.55,0.96,55.0,M-SC,7.72,220.0,0.13,1.23,24.85,OX40N,ATH,CABLES
85,ZYDUSLIFE,0.24,-2.56,39.20,35.63,80048.0,-5370.0,204204.0,1286.17,-15.32,55.0,H-MC,5.00,120.0,-0.07,1.51,13.68,AR,ATH,PHARMA
40,INDIAMART,-1.19,-9.54,128.53,106.72,143394.0,-11771.0,111565.0,4810.62,-59.18,41.0,H-SC,9.45,140.0,-0.08,0.83,11.60,AR,ATH,MISC
84,WIPRO,0.52,-16.62,106.60,72.27,150612.0,-28161.0,141287.0,420.00,-24.55,37.0,M-LC,15.03,98.0,-0.19,1.05,4.04,XR,NTT,IT

In [17]:
# top 5 to accumulate based on lowest RSI_14
df_tmp = df_portfolio_features[df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])].sort_values(by = 'RSI_14', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
58,RELAXO,-1.12,-60.98,290.37,52.31,164451.0,-88525.0,56635.0,1176.00,-58.47,18.0,X-SC,19.56,92.0,-0.54,0.42,0.00,X40N,NTT,FOOTWEAR
12,BATAINDIA,-1.19,-54.19,195.15,35.20,115025.0,-69728.0,58942.0,2096.00,-22.74,20.0,X-SC,26.25,91.0,-0.61,0.44,0.00,X40,NTT,FOOTWEAR
8,AWL,-0.72,-38.67,172.30,67.02,376546.0,-137768.0,218541.0,485.00,-67.02,21.0,X-SC,23.35,81.0,-0.37,1.62,1.43,XY24,NTT,FMCG
73,TCS,-0.13,-27.74,75.15,26.57,251586.0,-128495.0,334778.0,4311.59,-38.71,21.0,X-LC,14.42,2.0,-0.51,2.48,0.00,X40,ATH,IT
3,ACC,-0.66,-35.25,169.98,74.81,295112.0,-94512.0,173616.0,3906.00,-53.87,22.0,X-SC,12.77,85.0,-0.32,1.29,0.00,XY24,BTT,CEMENT

In [18]:
# top 5 to accumulate based on Spread and CumlRnk
df_tmp = df_portfolio_features[df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])]
df_tmp = df_tmp[(df_tmp['CumlRnk'] < 100)].sort_values(by = 'Spread%', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
78,UNITDSPR,-1.87,-0.37,21.21,20.77,49480.0,-860.0,233284.0,1644.00,-11.71,46.0,X-MC,1.39,64.0,-0.02,1.73,6.32,X40N,NTT,BREWERIES
22,DABUR,-2.13,-9.71,59.16,43.70,132502.0,-24095.0,223973.0,735.00,-17.99,31.0,X-MC,1.51,70.0,-0.18,1.66,3.88,XY24,BTT,FMCG
75,TMPV,-2.04,-25.22,82.65,36.58,219919.0,-89756.0,266085.0,600.00,-84.72,33.0,X-LC,1.77,4.0,-0.41,1.97,0.00,XY24,NTT,AUTO
37,ICICIGI,-1.28,-1.94,21.70,19.34,42581.0,-3882.0,196227.0,2252.93,-17.63,41.0,X-MC,1.78,66.0,-0.09,1.45,11.92,X40,ATH,INSURANCE
59,RELIANCE,1.32,-9.59,38.59,25.30,70116.0,-19267.0,181696.0,1952.00,-11.96,49.0,X-LC,2.68,21.0,-0.27,1.35,21.31,XY25,BTT,REFINERIES

In [19]:
# top 5 to accumulate based on lowest Gained%
df_tmp = df_portfolio_features[df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])].sort_values(by = 'Gained%', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
3,ACC,-0.66,-35.25,169.98,74.81,295112.0,-94512.0,173616.0,3906.00,-53.87,22.0,X-SC,12.77,85.0,-0.32,1.29,0.0,XY24,BTT,CEMENT
12,BATAINDIA,-1.19,-54.19,195.15,35.20,115025.0,-69728.0,58942.0,2096.00,-22.74,20.0,X-SC,26.25,91.0,-0.61,0.44,0.0,X40,NTT,FOOTWEAR
10,BAJAJHLDNG,-1.90,-10.73,44.75,29.22,75953.0,-20397.0,169728.0,14451.52,-17.81,27.0,X-LC,12.26,28.0,-0.27,1.26,0.0,X40,ATH,FINANCE
9,BAJAJHFL,-1.00,-25.95,118.94,62.13,240488.0,-70853.0,202193.0,181.50,-39.10,29.0,X-MC,19.09,60.0,-0.29,1.50,0.0,X40N,ATH,FINANCE
21,COLPAL,-2.08,-23.57,85.15,41.51,171398.0,-62075.0,201290.0,3726.84,-7.42,34.0,X-MC,4.14,62.0,-0.36,1.49,0.0,XY25,ATH,FMCG

In [20]:
# top 5 to accumulate based on lowest CurrAlloc%
df_tmp = df_portfolio_features[df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])].sort_values(by = 'CurrAlloc%', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
58,RELAXO,-1.12,-60.98,290.37,52.31,164451.0,-88525.0,56635.0,1176.00,-58.47,18.0,X-SC,19.56,92.0,-0.54,0.42,0.00,X40N,NTT,FOOTWEAR
12,BATAINDIA,-1.19,-54.19,195.15,35.20,115025.0,-69728.0,58942.0,2096.00,-22.74,20.0,X-SC,26.25,91.0,-0.61,0.44,0.00,X40,NTT,FOOTWEAR
54,QUESS,-0.59,-21.25,120.83,73.90,101613.0,-22697.0,84096.0,424.00,-57.58,43.0,X-SC,18.32,80.0,-0.22,0.62,3.74,XY24,NTT,MISC
36,HONAUT,-0.24,-20.72,90.87,51.31,138918.0,-39963.0,152875.0,58357.33,-34.10,42.0,X-SC,13.78,90.0,-0.29,1.13,2.95,X40N,ATH,ELECTRICAL
2,ABBOTINDIA,-1.51,-10.13,31.37,18.07,50424.0,-18115.0,160740.0,35195.00,-23.42,47.0,X-MC,11.09,58.0,-0.36,1.19,1.90,X40,ATH,PHARMA

In [21]:
# top 5 to accumulate based on CumlRnk
df_tmp = df_portfolio_features.sort_values(by = 'CumlRnk', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
45,ITC,-0.74,-19.22,47.38,19.06,130202.0,-65363.0,274803.0,452.00,-55.52,36.0,X-LC,17.02,1.0,-0.50,2.04,0.23,X40,NTT,FMCG
73,TCS,-0.13,-27.74,75.15,26.57,251586.0,-128495.0,334778.0,4311.59,-38.71,21.0,X-LC,14.42,2.0,-0.51,2.48,0.00,X40,ATH,IT
43,INFY,-0.06,-13.17,54.61,34.24,148366.0,-41206.0,271682.0,1972.00,-31.79,26.0,X-LC,12.72,3.0,-0.28,2.01,0.00,X40,NTT,IT
75,TMPV,-2.04,-25.22,82.65,36.58,219919.0,-89756.0,266085.0,600.00,-84.72,33.0,X-LC,1.77,4.0,-0.41,1.97,0.00,XY24,NTT,AUTO
34,HCLTECH,0.71,-11.75,40.32,23.83,86085.0,-28420.0,213504.0,1908.19,-7.36,30.0,X-LC,9.80,8.0,-0.33,1.58,2.43,X40,ATH,IT

In [22]:
# top 5 for average up
df_tmp = df_portfolio_features[(df_portfolio_features['Dev%_200'] > 5)].sort_values(by = 'CurrAlloc%', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
67,SONACOMS,-1.26,-11.80,57.70,39.09,51482.0,-11935.0,89224.0,804.02,-30.06,48.0,M-MC,9.83,193.0,-0.23,0.66,26.22,AR,ATH,AUTO
27,FINCABLES,-0.05,12.40,84.97,107.91,141010.0,18309.0,165953.0,1641.55,0.96,55.0,M-SC,7.72,220.0,0.13,1.23,24.85,OX40N,ATH,CABLES
19,COALINDIA,3.73,13.96,3.26,17.67,5590.0,20998.0,171458.0,478.51,37.73,68.0,L-LC,12.11,185.0,3.76,1.27,33.15,XY25,ATH,MINING
11,BANDHANBNK,-1.62,-13.65,122.83,92.42,295459.0,-38016.0,240543.0,400.00,106.18,58.0,H-SC,9.90,174.0,-0.13,1.78,32.51,XY24,NTT,BANKS
1,ABB,0.08,15.31,26.24,45.57,79161.0,40061.0,301680.0,7934.00,-25.90,66.0,H-MC,10.46,125.0,0.51,2.24,33.97,AR,NTT,ELECTRICAL

In [23]:
# top 5 RSP
df_tmp = df_portfolio_features.sort_values(by = 'RSP', ascending=False)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
19,COALINDIA,3.73,13.96,3.26,17.67,5590.0,20998.0,171458.0,478.51,37.73,68.0,L-LC,12.11,185.0,3.76,1.27,33.15,XY25,ATH,MINING
1,ABB,0.08,15.31,26.24,45.57,79161.0,40061.0,301680.0,7934.00,-25.90,66.0,H-MC,10.46,125.0,0.51,2.24,33.97,AR,NTT,ELECTRICAL
27,FINCABLES,-0.05,12.40,84.97,107.91,141010.0,18309.0,165953.0,1641.55,0.96,55.0,M-SC,7.72,220.0,0.13,1.23,24.85,OX40N,ATH,CABLES
26,EASEMYTRIP,-1.22,-59.93,263.64,45.70,186770.0,-105972.0,70843.0,26.40,-26.57,42.0,M-SC,18.19,204.0,-0.57,0.53,16.72,XY24,NTT,TRAVEL
31,HAPPSTMNDS,-1.35,-49.30,264.57,84.85,171928.0,-63181.0,64984.0,1480.71,-39.74,60.0,H-SC,28.39,152.0,-0.37,0.48,20.34,AR,ATH,IT

In [24]:
# Top N allocation
df_tmp = df_portfolio_features.sort_values(by = 'CurrAlloc%', ascending=False)
top_n_values = [10, 25, 50]

sum_df = pd.DataFrame({
    'Top_N': top_n_values,
    'Sum_Alloc%': [df_tmp['CurrAlloc%'].head(n).sum() for n in top_n_values]
})

sum_df

   Top_N  Sum_Alloc%
0     10       20.40
1     25       45.20
2     50       77.78

In [25]:
# market-cap-wise allocation
df_tmp = df_portfolio_features[cols]
df_tmp.groupby(df_tmp['Conviction'].str[-2:])['CurrAlloc%'].sum().sort_values(ascending=False)

Conviction
SC    44.64
MC    30.36
LC    24.98
Name: CurrAlloc%, dtype: float64

In [26]:
# criteria-wise allocation
df_portfolio_features.groupby('Criteria')['CurrAlloc%'].sum().sort_values(ascending=False)

Criteria
XY24     27.23
X40      23.80
X40N     15.05
AR        9.23
XY25      8.67
XR        8.25
OX40N     6.97
SR        0.78
Name: CurrAlloc%, dtype: float64

In [27]:
# conviction-wise allocation
df_portfolio_features.groupby('Conviction')['CurrAlloc%'].sum().sort_values(ascending=False)

Conviction
X-MC    22.94
H-SC    21.69
X-LC    21.44
X-SC    12.13
M-SC    10.24
H-MC     5.03
M-MC     2.04
L-LC     1.27
H-LC     1.22
M-LC     1.05
L-SC     0.58
L-MC     0.35
Name: CurrAlloc%, dtype: float64

In [28]:
# sector-wise stats
df_tmp = df_portfolio_features.groupby('Category')[['CurrAlloc%', 'Current', 'Current P/L', 'FTT Amt']].sum().sort_values(by=['Current', 'Current P/L'], ascending=False)
df_tmp['Current P/L%'] = round(df_tmp['Current P/L'] * 100 / df_tmp['Current'], 2)
df_tmp['FTT%'] = round(df_tmp['FTT Amt'] * 100 / df_tmp['Current'], 2)
cols = ['CurrAlloc%', 'Current P/L%', 'FTT%']
df_tmp[cols].sort_values(by=['CurrAlloc%'], ascending=False)

               CurrAlloc%  Current P/L%    FTT%
Category
FMCG                15.15        -22.23   65.63
FINANCE             12.82        -24.19   74.80
IT                  11.75        -42.01  114.28
MISC                 6.96        -42.77  104.80
ELECTRICAL           6.68         -7.52   48.69
PAINTS               5.22        -39.99   64.30
INSURANCE            4.71         -6.88   43.45
PHARMA               4.17         -4.37   37.22
AUTO                 3.69        -31.19   83.24
BANKS                3.11        -27.25  104.36
AC                   2.15        -10.63   40.63
HEALTHCARE           1.98        -33.83   68.75
DURABLES             1.95        -47.28   83.11
FOOTWEAR             1.84        -77.79  149.08
TRAVEL               1.81        -83.81  175.85
BREWERIES            1.73         -0.37   21.21
APPARELS             1.61        -23.34   65.41
REALTY               1.45        -13.02   31.59
CERAMICS             1.35        -68.62  119.85
REFINERIES           1.35        -10.60   38.59
CEMENT               1.29        -54.44  169.98
MINING               1.27         12.25    3.26
CABLES               1.23         11.03   84.97
JEWELLERY            1.10       -115.47  190.34
ENGINEERING          1.10        -63.61  138.45
CHEMICALS            0.96       -104.72  271.74
ENTERTAINMENT        0.76        -88.87  201.52
TEXTILES             0.42        -62.68  109.06
HOTELS               0.37       -130.57  211.89

In [29]:
# money to be made criteria-wise
df_portfolio_features.groupby('Criteria')['FTT Amt'].agg(['sum', 'count']).sort_values(by='sum', ascending=False)

                sum  count
Criteria
XY24      3924189.0     21
X40       1662020.0     15
XR        1380480.0     12
AR        1326360.0     10
X40N      1268021.0     10
OX40N      850748.0     10
XY25       448512.0      6
SR         314715.0      2

In [30]:
# money to be made conviction-wise
df_portfolio_features.groupby('Conviction')['FTT Amt'].agg(['sum', 'count']).sort_values(by='sum', ascending=False)

                  sum  count
Conviction
H-SC        3868714.0     24
X-MC        1637666.0     15
X-LC        1581788.0     12
X-SC        1545490.0     10
M-SC        1536538.0     14
H-MC         400391.0      3
L-SC         212752.0      2
M-LC         150612.0      1
M-MC         110991.0      2
H-LC          69480.0      1
L-MC          55033.0      1
L-LC           5590.0      1

In [31]:
# money to be made criteria and conviction-wise
df_portfolio_features.groupby(['Conviction', 'Criteria'])['FTT Amt'].agg(['sum', 'count']).sort_values(by='sum', ascending=False)

                           sum  count
Conviction Criteria
H-SC       XY24      1319672.0      6
           AR         968412.0      5
M-SC       XY24       911845.0      6
H-SC       XR         880093.0      7
X-SC       XY24       831482.0      4
X-LC       X40        815905.0      6
X-MC       X40        639877.0      7
           X40N       510118.0      4
X-SC       X40N       507770.0      4
H-SC       OX40N      385822.0      4
X-LC       XY24       366924.0      2
M-SC       OX40N      356526.0      5
H-SC       SR         314715.0      2
X-MC       XY24       253084.0      2
X-LC       X40N       250133.0      2
H-MC       XY24       241182.0      1
X-MC       XY25       234587.0      2
X-SC       X40        206238.0      2
M-SC       XR         190390.0      2
H-MC       AR         159209.0      2
M-LC       XR         150612.0      1
X-LC       XY25       148826.0      2
L-SC       OX40N      108400.0      1
           XR         104352.0      1
M-SC       AR          77777.0      1
H-LC       AR          69480.0      1
M-MC       XY25        59509.0      1
L-MC       XR          55033.0      1
M-MC       AR          51482.0      1
L-LC       XY25         5590.0      1

In [32]:
# notebook execution time

end_time = time.time()
execution_time = round(end_time - start_time, 0)
print(f"Notebook execution time: {execution_time} seconds")

Notebook execution time: 25.0 seconds