<a href="https://colab.research.google.com/github/ankit-rathi/Quantvesting_v2/blob/main/myStocks_Portfolio_Analysis.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
'''
!pip install pandas==2.2.2 -qq
!pip install pyxirr -qq
!pip install ta -qq
!pip install yfinance==0.2.59 -qq
'''

'\n!pip install pandas==2.2.2 -qq\n!pip install pyxirr -qq\n!pip install ta -qq\n!pip install yfinance==0.2.59 -qq\n'

In [2]:
# import libraries

import numpy as np
import pandas as pd
import datetime
import warnings
warnings.filterwarnings('ignore')
import yfinance as yfin
import ta
import matplotlib.pyplot as plt
import requests

In [3]:
# notebook start time
import time
import datetime
import pytz

start_time = time.time()

# function to print date timestamp
def print_date_time():
  tz_NY = pytz.timezone('Asia/Kolkata')
  datetime_NY = datetime.datetime.now(tz_NY)
  print("Run date time (IST):", datetime_NY.strftime("%Y-%m-%d %H:%M:%S"))

In [4]:
# function to get booked and reserved amount
def get_amt():
  # fetch the JSON data from the URL
  url = "https://raw.githubusercontent.com/ankit-rathi/Tradevesting_v1/main/data/myPortfolioAmts.json"
  response = requests.get(url)
  pf_amts = response.json()  # parse the JSON data

  # extract values from the JSON
  py_booked_amt_dm = pf_amts["py_booked_amt_dm"]
  py_booked_amt_sv = pf_amts["py_booked_amt_sv"]
  cy_booked_amt_dm = pf_amts["cy_booked_amt_dm"]
  cy_booked_amt_sv = pf_amts["cy_booked_amt_sv"]
  reserve_amt_dm = pf_amts["reserve_amt_dm"]
  reserve_amt_sv = pf_amts["reserve_amt_sv"]

  # perform calculations
  py_booked_amt = py_booked_amt_dm + py_booked_amt_sv
  cy_booked_amt = cy_booked_amt_dm + cy_booked_amt_sv
  reserve_amt = reserve_amt_dm + reserve_amt_sv
  total_booked_amt = py_booked_amt + cy_booked_amt

  return total_booked_amt, reserve_amt, cy_booked_amt, py_booked_amt

gen_output = 0

In [5]:
# function to format the amount
def format_amt(number):
    abs_number = abs(number)

    if abs_number >= 1_00_00_000:  # Crores
        formatted_amt = f"{number / 1_00_00_000:.2f} C"
    elif abs_number >= 1_00_000:  # Lakhs
        formatted_amt = f"{number / 1_00_000:.2f} L"
    elif abs_number >= 1_000:  # Thousands
        formatted_amt = f"{number / 1_000:.2f} K"
    else:
        formatted_amt = f"{number:.2f}"

    return formatted_amt

# function to set start and end date
def get_start_end_date():
  start_date = (datetime.date.today() + datetime.timedelta(days=-365)).strftime('%Y-%m-%d')
  end_date = (datetime.date.today() + datetime.timedelta(days=1)).strftime('%Y-%m-%d')
  return start_date, end_date

# function to fetch my portfolio csv
def get_mypfs_df():
  mypfs_df = pd.read_csv('https://raw.githubusercontent.com/ankit-rathi/Tradevesting_v1/main/data/myPortfolioStocks.csv')
  return mypfs_df

# function to fetch my prospects csv
def get_mypps_df():
  mypps_df = pd.read_csv('https://raw.githubusercontent.com/ankit-rathi/Tradevesting_v1/main/data/myProspectsScrips.csv')
  return mypps_df

# function to fetch screener data
def get_myscreen_df():
  myscreen_df = pd.read_csv('https://raw.githubusercontent.com/ankit-rathi/Tradevesting_v1/main/data/myScreenerDB.csv')
  return myscreen_df

# function to fetch momentum data
def get_myinvmt_df():
  myinvmt_df = pd.read_csv('https://raw.githubusercontent.com/ankit-rathi/Tradevesting_v1/main/data/myInvestments.csv')
  return myinvmt_df

# function to get the stock ids
def get_stock_ids(df_pf):
  stock_n100 = df_pf['Symbol'].unique()

  exclude = ['CADILAHC','MMTC', 'MASFIN']

  stock_ids = df_pf[~df_pf['Symbol'].isin(exclude) ]['Symbol'].unique()

  #mypf = mypf[mypf.Forecast.notnull()]
  #stock_ids = mypf['Symbol'].unique()

  #stock_ids.sort()
  return stock_ids

# get features from screener data
def get_screener_features():
  myscreen_df = get_myscreen_df()
  cols = ['Symbol', 'EPS', 'MedPE', 'ROCE%', 'ROE%', 'CapType']
  return myscreen_df[cols]

# get relative strength
def get_relative_strength(stock_list):

    # Dictionary to store stock tickers and their corresponding percentage price change
    stock_changes = {}

    # Loop through each stock and fetch its price data
    for stock in stock_list:
        try:
            # Download the stock data for the given date range
            stock_data = yfin.Ticker(stock + '.NS').history(period='1mo', interval='1d')[map(str.title, ['open', 'close', 'low', 'high', 'volume'])]

            # Calculate the percentage change for the stock
            if len(stock_data) > 0:
                start_price = stock_data['Close'].iloc[0]
                end_price = stock_data['Close'].iloc[-1]
                percent_change = round(((end_price - start_price) / start_price) * 100, 2)
                stock_changes[stock] = percent_change
            else:
                stock_changes[stock] = np.nan  # If no data is available, set to NaN

        except Exception as e:
            print(f"Error fetching data for {stock}: {e}")
            stock_changes[stock] = np.nan

    # Create a DataFrame with stock tickers and their percentage changes
    df = pd.DataFrame(list(stock_changes.items()), columns=['Symbol', 'Percent_Change'])

    # Drop any stocks with missing data (NaN values)
    df = df.dropna()

    # Calculate the percentile rank based on percentage change
    df['RSP'] = round(df['Percent_Change'].rank(pct=True) * 100, 2)
    cols = ['Symbol', 'RSP']
    df = df[cols]
    # Sort by percentile rank (optional)
    df = df.sort_values(by='RSP', ascending=False).reset_index(drop=True)

    return df

In [6]:
# function to get stock technicals
def stock_prec_dev(stock_symbol):
    #stock_symbol = 'ULTRACEMCO.NS'
    short_window = 20
    mid_window = 50
    long_window = 200
    moving_avg = 'SMA'

    start = datetime.datetime(*map(int, start_date.split('-')))
    end = datetime.datetime(*map(int, end_date.split('-')))

    stock_df = yfin.Ticker(stock_symbol + '.NS').history(period='max', interval='1d')[map(str.title, ['open', 'close', 'low', 'high', 'volume'])]

    stock_df['Max'] = round(max(stock_df['Close']),2)
    stock_df = stock_df[(stock_df.index <= end_date) & (stock_df.index >= start_date)]
    stock_df['200_SMA'] = round(stock_df['Close'].rolling(window = 200, min_periods = 1).mean(),0)
    stock_df['Dev%_200'] = round((stock_df['Close'] - stock_df['200_SMA'])*100/stock_df['200_SMA'],2)
    stock_df.dropna(axis = 0, inplace = True) # remove any null rows

    stock_df['20_SMA'] = stock_df['Close'].rolling(window=20).mean()
    stock_df['50_SMA'] = stock_df['Close'].rolling(window=50).mean()
    stock_df['Symbol'] = stock_symbol

    stock_df['Close'] = round(stock_df['Close'],2)
    stock_df['Min'] = round(min(stock_df['Close']),2)
    stock_df['RSI_14'] = ta.momentum.RSIIndicator(close=stock_df['Close'], window=14).rsi()
    stock_df['RSI_14'] = round(stock_df['RSI_14'],0)
    stock_df['Prev_Close'] = stock_df['Close'].shift(1)
    stock_df.drop(['Open', 'Low', 'High', 'Volume'], axis=1, inplace=True)
    stock_df = stock_df.tail(1)

    max_SMA = max(stock_df['20_SMA'].item(), stock_df['50_SMA'].item(), stock_df['200_SMA'].item())
    min_SMA = min(stock_df['20_SMA'].item(), stock_df['50_SMA'].item(), stock_df['200_SMA'].item())
    ABS_Spread = max_SMA - min_SMA
    stock_df['Spread%'] = round((ABS_Spread / stock_df['200_SMA'].item()) * 100,2)

    return stock_df

# function to compute stock attributes
def get_common_features(stock_ids, df_mypf):

  df_prec_dev = pd.DataFrame()
  df_tmp = get_screener_features()
  df_rs = get_relative_strength(stock_ids)

  for stock_id in stock_ids:
      tmp = stock_prec_dev(stock_id)
      tmp = tmp.reset_index()
      df_prec_dev = pd.concat([df_prec_dev, tmp], ignore_index = True)
  df_prec_dev = pd.merge(df_prec_dev, df_mypf, on= 'Symbol')
  df_prec_dev = pd.merge(df_prec_dev, df_tmp, on= 'Symbol', how='left')
  df_prec_dev = pd.merge(df_prec_dev, df_rs, on= 'Symbol', how='left')
  #print(df_prec_dev.columns)
  df_prec_dev['Curr_PE'] = round(df_prec_dev['Close']/df_prec_dev['EPS'],1)
  df_prec_dev['Dev%_PE'] = round((df_prec_dev['Curr_PE'] - df_prec_dev['MedPE'])*100/df_prec_dev['MedPE'],2)
  df_prec_dev['Conviction'] = df_prec_dev['Conviction'] + '-' + df_prec_dev['CapType']
  return df_prec_dev

# function to arrange stock features
def arrange_features(df_stocks, common_cols, diff_cols):
  df_stocks_common = df_stocks[common_cols].drop_duplicates()
  df_stocks_diff = df_stocks[diff_cols]
  df_stocks_diff['Investment'] = df_stocks_diff['AvgCost'] * df_stocks_diff['Shares']
  df_stocks_diff = df_stocks_diff.groupby(['Symbol'])[['Shares', 'Investment']].aggregate(['sum']).reset_index()
  df_stocks_diff.columns = ['Symbol', 'Shares', 'Investment']
  df_stocks_diff['AvgCost'] = round(df_stocks_diff['Investment']/df_stocks_diff['Shares'],2)
  df_stocks = pd.merge(df_stocks_diff, df_stocks_common, on='Symbol')
  return df_stocks

# plot fact distribution across dimension
def plot_pie_chart(df, dimension, fact):
  # grouping the data by category and calculating the sum of fact for each type
  grouped_data = df.groupby(dimension)[fact].sum()

  # sorting the grouped data in descending order
  grouped_data = grouped_data.sort_values(ascending=False)

  # creating a pie chart
  grouped_data.plot.pie(autopct='%1.1f%%', startangle=90, figsize=(6, 6))

  # adding a title and displaying the plot
  plt.title(f'{dimension} {fact} Distribution')
  plt.ylabel('')  # To hide the y-label
  plt.show()

In [7]:
# function to get portfolio features

def get_portfolio_features(df_common_features):

  print_date_time()
  print('-------------------')

  #df_common_features["Target"] = df_common_features["Target"].fillna(df_common_features["Max"])
  df_common_features['NTT'] = np.where(df_common_features['Strategy']== 'NTT', df_common_features["Target"], df_common_features['Max'])
  df_common_features['LTT'] = np.where(df_common_features['Strategy']== 'BTT', df_common_features["Target"], df_common_features['Max'])
  df_common_features['BOL'] = df_common_features['Min']

  tmp_df = df_common_features[df_common_features['Symbol'].isin(mypf_df[mypf_df['InPortfolio'] != 'NA'].Symbol.values)]
  print('qualified stocks: '+str(len(tmp_df['Symbol'].unique())))
  tmp_df1 = tmp_df[tmp_df['LatestQtr'] == 1]
  print('with latest results: '+str(len(tmp_df1['Symbol'].unique())))
  tmp_df1 = tmp_df1[tmp_df1['StarStock'] == 1]
  print('still star stocks: '+str(len(tmp_df1['Symbol'].unique())))
  tmp_df['Investment'] = tmp_df['AvgCost'] * tmp_df['Shares']
  tmp_df['Current'] = round(tmp_df['Close'] * tmp_df['Shares'],0)
  tmp_df['Previous'] = tmp_df['Prev_Close'] * tmp_df['Shares']
  tmp_df['EstimatedST'] = tmp_df['NTT'] * tmp_df['Shares']
  tmp_df['EstimatedLT'] = tmp_df['LTT'] * tmp_df['Shares']
  tmp_df['Current P/L'] = round((tmp_df['Current'] - tmp_df['Investment']),0)
  tmp_df['Today P/L%'] = round((tmp_df['Current'] - tmp_df['Previous'])*100/tmp_df['Previous'],2)
  tmp_df['Current P/L%'] = round((tmp_df['Current'] - tmp_df['Investment'])*100/tmp_df['Investment'],2)
  tmp_df['EstimatedST P/L%'] = round((tmp_df['EstimatedST'] - tmp_df['Investment'])*100/tmp_df['Investment'],2)
  tmp_df['EstimatedLT P/L%'] = round((tmp_df['EstimatedLT'] - tmp_df['Investment'])*100/tmp_df['Investment'],2)
  tmp_df['NTT%'] = round((tmp_df['NTT'] - tmp_df['Close'])*100/tmp_df['Close'],2)
  tmp_df['LTT%'] = round((tmp_df['LTT'] - tmp_df['Close'])*100/tmp_df['Close'],2)
  tmp_df['Gained%'] = round((tmp_df['Close'] - tmp_df['BOL'])*100/tmp_df['BOL'],2)
  investment = round(sum(tmp_df['AvgCost']*tmp_df['Shares']),0)
  current = round(sum(tmp_df['Close']*tmp_df['Shares']),0)
  tmp_df['InitAlloc%'] = round(tmp_df['Investment']*100/investment,2)
  tmp_df['CurrAlloc%'] = round(tmp_df['Current']*100/current,2)
  tmp_df['FTT'] = tmp_df['LTT']
  tmp_df.loc[tmp_df['Strategy'] == 'NTT', 'FTT'] = tmp_df['NTT']
  tmp_df['FTT%'] = tmp_df['LTT%']
  tmp_df.loc[tmp_df['Strategy'] == 'NTT', 'FTT%'] = tmp_df['NTT%']
  tmp_df['FTT Amt'] = round(tmp_df['FTT%'] * tmp_df['Current']/100,0)
  tmp_df['OTT%'] = round((tmp_df['FTT'] - tmp_df['AvgCost'])*100/tmp_df['AvgCost'],2)
  tmp_df['RRR Ind'] = round(tmp_df['Current P/L']/tmp_df['FTT Amt'],2)
  tmp_df['Risk Ind'] = round(tmp_df['Current P/L%']*tmp_df['CurrAlloc%'],0)

  return tmp_df

# function to print portfolio features
def print_portfolio_stats(df_portfolio_features, myinvmt_df):
  from pyxirr import xirr

  total_booked_amt, reserve_amt, cy_booked_amt, py_booked_amt = get_amt()

  dates = myinvmt_df['Date'].values
  dates = np.append(dates, datetime.date.today().strftime('%d-%b-%y'))
  investment = myinvmt_df['Investment'].values
  dates= pd.to_datetime(dates)

  current = round(sum(df_portfolio_features['Close']*df_portfolio_features['Shares']),0) + reserve_amt
  investment_xirr = np.append(investment, current)
  cagr = round(xirr(pd.DataFrame({"dates": dates, "amounts": investment_xirr}))*100,2)

  investment = -sum(investment)
  invested = round(sum(df_portfolio_features['AvgCost']*df_portfolio_features['Shares']),0) + reserve_amt
  previous = round(sum(df_portfolio_features['Prev_Close']*df_portfolio_features['Shares']),0) + reserve_amt
  cy_invested = investment + py_booked_amt

  today_pnl_amount = current-previous
  today_pnl_percentage = round((current-previous)*100/previous,2)

  curr_pnl_amount = current-invested
  curr_pnl_percentage = round((curr_pnl_amount)*100/(cy_invested),2)

  cy_pnl_amount = cy_booked_amt + curr_pnl_amount
  cy_pnl_percentage = round((cy_pnl_amount)*100/cy_invested,2)

  overall_pnl_amount = total_booked_amt + curr_pnl_amount
  overall_pnl_percentage = round((overall_pnl_amount)*100/investment,2)

  estimate_st = round(sum(df_portfolio_features['FTT']*df_portfolio_features['Shares']),0)  + reserve_amt
  est_st_pnl_amount = estimate_st-current
  est_st_pnl_percentage = round((est_st_pnl_amount)*100/current,2)

  estimate_lt = round(sum(df_portfolio_features['LTT']*df_portfolio_features['Shares']),0)  + reserve_amt
  est_lt_pnl_amount = estimate_lt-current
  est_lt_pnl_percentage = round((est_lt_pnl_amount)*100/current,2)

  total_profit = round(sum(df_portfolio_features[df_portfolio_features['Current P/L%'] > 0]['Current']) - sum(df_portfolio_features[df_portfolio_features['Current P/L%'] > 0]['Investment']),0)
  total_loss = round(sum(df_portfolio_features[df_portfolio_features['Current P/L%'] < 0]['Current']) - sum(df_portfolio_features[df_portfolio_features['Current P/L%'] < 0]['Investment']),0)

  cy_booked_percentage = round((cy_booked_amt)*100/current,2)
  py_booked_percentage = round((py_booked_amt)*100/investment,2)
  total_booked_percentage = round((total_booked_amt)*100/investment,2)

  print('-------------------')
  print('Initial Investment: ', format_amt(investment))
  print('CY Investment: ', format_amt(cy_invested))
  print('Reserve: ', format_amt(reserve_amt))
  print('Current: ',  format_amt(current))
  print('-------------------')
  print('Today PnL: '+ '{} ({}%)'.format(format_amt(today_pnl_amount), today_pnl_percentage))
  print('Current PnL: '+ '{} ({}%)'.format(format_amt(curr_pnl_amount), curr_pnl_percentage))
  print('CY Booked + Current PnL: '+ '{} ({}%)'.format(format_amt(cy_pnl_amount), cy_pnl_percentage))
  print('-------------------')
  print('Total profit: ', format_amt(total_profit))
  print('Total loss: ', format_amt(total_loss))
  print('-------------------')
  print('Total Booked + Current PnL: '+ '{} ({}%)'.format(format_amt(overall_pnl_amount), overall_pnl_percentage))
  print('Total Booked PnL: '+ '{} ({}%)'.format(format_amt(total_booked_amt), total_booked_percentage))
  print('Curr Year Booked PnL: '+ '{} ({}%)'.format(format_amt(cy_booked_amt), cy_booked_percentage))
  print('Prev Year Booked PnL: '+ '{} ({}%)'.format(format_amt(py_booked_amt), py_booked_percentage))
  print('===================')
  print('Est FTT: ',  format_amt(estimate_st))
  print('Est FTT PnL: '+ '{} ({}%)'.format(format_amt(est_st_pnl_amount), est_st_pnl_percentage))

  print('===================')
  print('Deployed: ', format_amt(investment))

  print('Current: ', format_amt(current))

  print('CAGR/XIRR %: '+'{}%'.format(cagr))

In [8]:
# get start and end date
start_date, end_date = get_start_end_date()

# get portfolio and prospects data
mypfs_df = get_mypfs_df()
mypps_df = get_mypps_df()
myinvmt_df = get_myinvmt_df()

# merge above datasets
mypf_df = pd.merge(mypfs_df, mypps_df, on="Symbol")

# seggregate dm and sv portfolio
dm_pf = mypf_df[mypf_df['InPortfolio'] == 'DM']
sv_pf = mypf_df[mypf_df['InPortfolio'] == 'SV']

# build portfolio stock dataframe
dm_stocks = get_stock_ids(dm_pf)
sv_stocks = get_stock_ids(sv_pf)
df_stocks = pd.concat([dm_pf,sv_pf], ignore_index = True)

# arrange common and diff stock features
common_cols = ['Symbol', 'Target', 'Criteria', 'Strategy', 'CumlRnk', 'LatestQtr', 'StarStock', 'Conviction', 'Category', 'InFolio', 'XIRR', 'MBQ']
diff_cols = ['Symbol', 'AvgCost', 'Shares']
df_stocks = arrange_features(df_stocks, common_cols, diff_cols)

# get common features
stock_ids = df_stocks['Symbol'].values
df_common_features = get_common_features(stock_ids, df_stocks)

df_common_features.reset_index(drop=True, inplace=True)
df_common_features.drop(['Date'], axis=1, inplace=True)
# get and print portfolio features
df_portfolio_features = get_portfolio_features(df_common_features)

print_portfolio_stats(df_portfolio_features, myinvmt_df)

df = df_portfolio_features
#plot_pie_chart(df, 'CapType', 'Current')
list_ox40n = list(df[df['MBQ'].str.contains('OX40N', na=False)]['Symbol'].values)

Run date time (IST): 2026-08-18 09:51:02
-------------------
qualified stocks: 87
with latest results: 30
still star stocks: 19
-------------------
Initial Investment:  1.46 C
CY Investment:  1.89 C
Reserve:  3.69 L
Current:  1.58 C
-------------------
Today PnL: -81.53 K (-0.51%)
Current PnL: -34.52 L (-18.27%)
CY Booked + Current PnL: -29.46 L (-15.59%)
-------------------
Total profit:  3.33 L
Total loss:  -37.84 L
-------------------
Total Booked + Current PnL: 13.41 L (9.18%)
Total Booked PnL: 47.93 L (32.82%)
Curr Year Booked PnL: 5.06 L (3.19%)
Prev Year Booked PnL: 42.87 L (29.35%)
===================
Est FTT:  2.67 C
Est FTT PnL: 1.09 C (68.61%)
===================
Deployed:  1.46 C
Current:  1.58 C
CAGR/XIRR %: 3.69%

In [9]:
# top 5 near their targets
cols = ['Symbol', 'Today P/L%', 'Current P/L%', 'FTT%', 'OTT%', 'FTT Amt', 'Current P/L', 'Current', 'FTT', 'Dev%_PE', 'RSI_14','Conviction', 'Spread%',  'CumlRnk', 'RRR Ind', 'CurrAlloc%', 'Gained%', 'Criteria', 'Strategy', 'Category']
df_tmp = df_portfolio_features[~df_portfolio_features['Symbol'].isin(['ENRIN','BLUSPRING','DIGITIDE'])]
df_tmp = df_tmp.sort_values(by = 'FTT Amt', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
66,SIEMENS,0.14,6.09,4.47,10.83,8825.0,11330.0,197425.0,4125.00,-14.10,63.0,H-LC,13.59,51.0,1.28,1.28,39.29,AR,NTT,ELECTRICAL
78,UNITDSPR,-0.58,12.83,7.03,20.77,18573.0,30048.0,264192.0,1644.00,-3.81,65.0,X-MC,10.48,64.0,1.62,1.71,27.00,X40N,NTT,BREWERIES
77,TTKPRESTIG,0.07,-22.98,29.96,0.09,23254.0,-23159.0,77618.0,770.00,-6.23,41.0,M-SC,10.20,250.0,-1.00,0.50,39.70,OX40N,NTT,DURABLES
52,M&M,0.77,7.88,10.14,18.82,26329.0,18973.0,259654.0,3762.88,-6.96,58.0,X-LC,4.79,25.0,0.72,1.68,17.78,X40N,ATH,AUTO
67,SIS,0.71,-3.68,25.89,21.26,27689.0,-4085.0,106947.0,528.00,105.28,42.0,H-SC,21.63,168.0,-0.15,0.69,59.01,OX40N,NTT,MISC

In [10]:
# top 5 today
df_tmp = df_portfolio_features.sort_values(by = 'Today P/L%', ascending=False)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
0,5PAISA,3.83,-24.13,48.81,12.90,80915.0,-52720.0,165776.0,593.00,6.47,64.0,H-SC,11.17,170.0,-0.65,1.07,59.98,OX40N,NTT,FINANCE
18,COFFEEDAY,3.57,-49.53,168.01,35.27,96290.0,-56237.0,57312.0,80.00,NaN,42.0,NaN,4.00,266.0,-0.58,0.37,41.34,XR,NTT,HOTELS
12,BOSCH-HCIL,2.10,-25.99,35.11,-0.01,33208.0,-33221.0,94584.0,2282.00,736.88,74.0,M-SC,5.71,231.0,-1.00,0.61,61.00,OX40N,BTT,AC
24,EASEMYTRIP,1.79,-65.56,323.08,45.70,196723.0,-115925.0,60890.0,26.40,NaN,36.0,NaN,7.33,204.0,-0.59,0.39,6.67,XY24,NTT,TRAVEL
82,VBL,1.68,-10.60,51.74,35.66,162743.0,-37304.0,314540.0,669.42,-26.83,42.0,X-LC,7.36,13.0,-0.23,2.03,15.81,X40N,ATH,FMCG

In [11]:
# bottom 5 today
df_tmp = df_portfolio_features.sort_values(by = 'Today P/L%', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
81,VALIANTORG,-7.78,-37.81,180.03,74.15,183172.0,-61860.0,101745.0,838.00,NaN,53.0,NaN,6.21,145.0,-0.34,0.66,51.41,XR,NTT,CHEMICALS
60,RELAXO,-4.19,-50.83,209.76,52.31,149714.0,-73786.0,71374.0,1176.00,NaN,40.0,NaN,13.45,92.0,-0.49,0.46,59.58,X40N,NTT,FOOTWEAR
19,COLPAL,-3.96,-27.76,93.61,39.86,178093.0,-73115.0,190250.0,3683.41,-12.49,30.0,X-MC,1.62,62.0,-0.41,1.23,7.62,XY25,ATH,FMCG
33,HCLTECH,-3.65,-12.35,41.44,23.97,112407.0,-38233.0,271253.0,1853.42,-14.68,53.0,X-LC,11.97,8.0,-0.34,1.75,28.00,X40,ATH,IT
58,RAJOOENG,-3.59,-52.05,191.15,39.61,93950.0,-53350.0,49150.0,143.10,NaN,35.0,NaN,15.71,136.0,-0.57,0.32,5.29,AR,ATH,MISC

In [12]:
# top 5 to exit based on CumlRnk
df_tmp = df_portfolio_features[~df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])]
df_tmp = df_tmp[(df_tmp['Current P/L%'] > -1) & (df_tmp['Current P/L%'] < 1)].sort_values(by = 'CumlRnk', ascending=False)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
79,UTIAMC,-0.86,-0.8,52.38,51.15,115524.0,-1781.0,220549.0,1371.68,25.5,45.0,M-SC,7.66,229.0,-0.02,1.43,3.31,XY24,ATH,FINANCE

In [13]:
# OX40N stocks to exit
df_tmp = df_portfolio_features[(df_portfolio_features['Symbol'].isin(list_ox40n))].sort_values(by = 'Current P/L%', ascending=False)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
25,FINCABLES,-0.95,65.70,25.48,107.91,62335.0,96999.0,244643.0,1641.55,20.71,73.0,M-SC,19.19,220.0,1.56,1.58,84.05,OX40N,ATH,CABLES
67,SIS,0.71,-3.68,25.89,21.26,27689.0,-4085.0,106947.0,528.00,105.28,42.0,H-SC,21.63,168.0,-0.15,0.69,59.01,OX40N,NTT,MISC
43,INDIGOPNTS,-0.53,-18.83,23.23,0.02,32913.0,-32877.0,141682.0,1408.00,-22.52,62.0,M-SC,6.70,222.0,-1.00,0.92,60.75,OX40N,NTT,PAINTS
77,TTKPRESTIG,0.07,-22.98,29.96,0.09,23254.0,-23159.0,77618.0,770.00,-6.23,41.0,M-SC,10.20,250.0,-1.00,0.50,39.70,OX40N,NTT,DURABLES
0,5PAISA,3.83,-24.13,48.81,12.90,80915.0,-52720.0,165776.0,593.00,6.47,64.0,H-SC,11.17,170.0,-0.65,1.07,59.98,OX40N,NTT,FINANCE

In [14]:
# top 5 to book for rotation
df_tmp = df_portfolio_features[(df_portfolio_features['Current P/L%'] > 20) ].sort_values(by = 'CumlRnk', ascending=False)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
25,FINCABLES,-0.95,65.7,25.48,107.91,62335.0,96999.0,244643.0,1641.55,20.71,73.0,M-SC,19.19,220.0,1.56,1.58,84.05,OX40N,ATH,CABLES

In [15]:
# top 5 to monitor for exit
df_tmp = df_portfolio_features[~df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])]
df_tmp = df_tmp[(df_tmp['Current P/L%'] > 0) ].sort_values(by = 'Dev%_PE', ascending=False)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
25,FINCABLES,-0.95,65.70,25.48,107.91,62335.0,96999.0,244643.0,1641.55,20.71,73.0,M-SC,19.19,220.0,1.56,1.58,84.05,OX40N,ATH,CABLES
68,STARHEALTH,-0.73,12.41,31.00,47.26,97963.0,34887.0,316010.0,761.00,-0.86,49.0,H-SC,16.48,173.0,0.36,2.04,36.63,XY24,NTT,INSURANCE

In [16]:
# top 5 to book for rotation from weak conviction
df_tmp = df_portfolio_features[~df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])]
df_tmp = df_tmp[~df_tmp['Criteria'].isin(['XY25','XY24','X40', 'X40N'])].sort_values(by = 'RRR Ind', ascending=False)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
25,FINCABLES,-0.95,65.70,25.48,107.91,62335.0,96999.0,244643.0,1641.55,20.71,73.0,M-SC,19.19,220.0,1.56,1.58,84.05,OX40N,ATH,CABLES
67,SIS,0.71,-3.68,25.89,21.26,27689.0,-4085.0,106947.0,528.00,105.28,42.0,H-SC,21.63,168.0,-0.15,0.69,59.01,OX40N,NTT,MISC
3,ALKYLAMINE,-0.73,-18.70,136.82,92.54,112311.0,-18876.0,82087.0,4520.85,NaN,55.0,NaN,14.00,142.0,-0.17,0.53,55.88,SR,ATH,CHEMICALS
42,INDIAMART,-0.33,-23.34,162.09,100.92,153259.0,-28784.0,94552.0,4675.60,NaN,42.0,NaN,13.34,140.0,-0.19,0.61,2.35,AR,ATH,MISC
71,TANLA,-2.86,-36.10,239.99,117.25,415211.0,-97749.0,173012.0,1922.32,NaN,44.0,NaN,15.42,147.0,-0.24,1.12,51.48,AR,ATH,IT

In [17]:
# top 5 to accumulate based on lowest RSI_14
df_tmp = df_portfolio_features[df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])].sort_values(by = 'RSI_14', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
28,GODREJCP,-1.32,-16.13,58.46,32.90,122353.0,-40243.0,209294.0,1460.97,-17.72,30.0,X-MC,5.75,32.0,-0.33,1.35,1.88,X40N,ATH,FMCG
19,COLPAL,-3.96,-27.76,93.61,39.86,178093.0,-73115.0,190250.0,3683.41,-12.49,30.0,X-MC,1.62,62.0,-0.41,1.23,7.62,XY25,ATH,FMCG
56,PGHH,-0.65,-37.27,110.44,32.01,147928.0,-79576.0,133944.0,17616.87,-53.84,33.0,X-SC,19.61,57.0,-0.54,0.87,0.00,X40,ATH,FMCG
47,ITC,-0.26,-24.86,65.96,24.70,196888.0,-98782.0,298496.0,452.00,-29.94,34.0,X-LC,10.43,1.0,-0.50,1.93,0.00,X40,NTT,FMCG
55,PAGEIND,0.86,-3.33,38.18,33.59,99060.0,-8924.0,259455.0,51217.29,-28.15,34.0,X-MC,8.66,55.0,-0.09,1.68,23.21,X40,ATH,APPARELS

In [18]:
# top 5 to accumulate based on Spread and CumlRnk
df_tmp = df_portfolio_features[df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])]
df_tmp = df_tmp[(df_tmp['CumlRnk'] < 100)].sort_values(by = 'Spread%', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
19,COLPAL,-3.96,-27.76,93.61,39.86,178093.0,-73115.0,190250.0,3683.41,-12.49,30.0,X-MC,1.62,62.0,-0.41,1.23,7.62,XY25,ATH,FMCG
50,KOTAKBANK,-0.50,2.70,15.79,18.92,38871.0,6470.0,246172.0,452.46,-13.30,50.0,X-LC,2.33,12.0,0.17,1.59,10.76,X40,ATH,BANKS
23,DMART,-0.85,-3.45,36.12,31.42,108731.0,-10762.0,301028.0,5391.45,-19.00,45.0,X-LC,2.39,14.0,-0.10,1.95,8.63,X40N,ATH,FMCG
26,GILLETTE,-0.33,-10.86,45.52,29.72,103028.0,-27561.0,226335.0,10978.86,-35.66,38.0,X-SC,3.52,83.0,-0.27,1.46,4.01,X40,ATH,FMCG
8,BAJAJHLDNG,-1.39,1.66,26.15,28.24,68054.0,4240.0,260245.0,14274.15,-8.09,57.0,X-LC,4.13,28.0,0.06,1.68,30.98,X40,ATH,FINANCE

In [19]:
# top 5 to accumulate based on lowest Gained%
df_tmp = df_portfolio_features[df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])].sort_values(by = 'Gained%', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
20,DABUR,-0.82,-21.12,82.18,43.70,160804.0,-52395.0,195673.0,735.00,-31.92,35.0,X-MC,9.88,70.0,-0.33,1.26,0.00,XY24,BTT,FMCG
47,ITC,-0.26,-24.86,65.96,24.70,196888.0,-98782.0,298496.0,452.00,-29.94,34.0,X-LC,10.43,1.0,-0.50,1.93,0.00,X40,NTT,FMCG
56,PGHH,-0.65,-37.27,110.44,32.01,147928.0,-79576.0,133944.0,17616.87,-53.84,33.0,X-SC,19.61,57.0,-0.54,0.87,0.00,X40,ATH,FMCG
35,HDFCLIFE,-0.51,-7.35,50.19,39.15,116595.0,-18429.0,232308.0,811.41,-31.88,43.0,X-LC,16.48,31.0,-0.16,1.50,0.82,X40,ATH,INSURANCE
34,HDFCBANK,-0.41,-11.33,47.80,31.05,124236.0,-33212.0,259908.0,1073.00,-28.50,34.0,X-LC,12.72,26.0,-0.27,1.68,0.88,X40,BTT,BANKS

In [20]:
# top 5 to accumulate based on lowest CurrAlloc%
df_tmp = df_portfolio_features[df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])].sort_values(by = 'CurrAlloc%', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
56,PGHH,-0.65,-37.27,110.44,32.01,147928.0,-79576.0,133944.0,17616.87,-53.84,33.0,X-SC,19.61,57.0,-0.54,0.87,0.00,X40,ATH,FMCG
2,ACC,-0.49,-41.36,198.12,74.81,311492.0,-110904.0,157224.0,3906.00,-41.79,38.0,X-SC,11.67,85.0,-0.36,1.02,5.04,XY24,BTT,CEMENT
1,ABBOTINDIA,-0.98,-10.11,28.35,15.37,45578.0,-18085.0,160770.0,34390.26,-26.75,42.0,X-MC,4.70,58.0,-0.40,1.04,8.90,X40,ATH,PHARMA
40,ICICIPRULI,-0.62,-16.27,55.59,30.28,91699.0,-32049.0,164956.0,787.27,-46.34,50.0,X-MC,12.80,78.0,-0.35,1.07,9.90,X40,ATH,INSURANCE
39,ICICIGI,-0.47,-14.26,38.66,18.89,66330.0,-28537.0,171572.0,2244.41,-14.59,40.0,X-MC,10.53,66.0,-0.43,1.11,2.22,X40,ATH,INSURANCE

In [21]:
# top 5 to accumulate based on CumlRnk
df_tmp = df_portfolio_features.sort_values(by = 'CumlRnk', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
47,ITC,-0.26,-24.86,65.96,24.70,196888.0,-98782.0,298496.0,452.00,-29.94,34.0,X-LC,10.43,1.0,-0.50,1.93,0.00,X40,NTT,FMCG
73,TCS,-1.01,-32.78,84.76,24.20,263965.0,-151847.0,311426.0,4230.71,-44.31,47.0,X-LC,14.31,2.0,-0.58,2.01,16.13,X40,ATH,IT
45,INFY,-1.84,-20.35,76.24,40.38,228617.0,-76605.0,299865.0,1972.00,-41.25,46.0,X-LC,15.92,3.0,-0.34,1.94,13.56,X40,NTT,IT
75,TMPV,-0.73,-22.01,83.04,42.75,269483.0,-91585.0,324522.0,600.00,-83.84,39.0,X-LC,4.37,4.0,-0.34,2.10,11.59,XY24,NTT,AUTO
33,HCLTECH,-3.65,-12.35,41.44,23.97,112407.0,-38233.0,271253.0,1853.42,-14.68,53.0,X-LC,11.97,8.0,-0.34,1.75,28.00,X40,ATH,IT

In [22]:
# top 5 for average up
df_tmp = df_portfolio_features[(df_portfolio_features['Dev%_200'] > 5)].sort_values(by = 'CurrAlloc%', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
44,INDUSINDBK,-0.37,-24.92,76.99,32.89,44630.0,-19238.0,57969.0,1800.00,326.64,53.0,L-MC,13.19,258.0,-0.43,0.37,42.92,XR,NTT,BANKS
3,ALKYLAMINE,-0.73,-18.70,136.82,92.54,112311.0,-18876.0,82087.0,4520.85,NaN,55.0,NaN,14.00,142.0,-0.17,0.53,55.88,SR,ATH,CHEMICALS
12,BOSCH-HCIL,2.10,-25.99,35.11,-0.01,33208.0,-33221.0,94584.0,2282.00,736.88,74.0,M-SC,5.71,231.0,-1.00,0.61,61.00,OX40N,BTT,AC
81,VALIANTORG,-7.78,-37.81,180.03,74.15,183172.0,-61860.0,101745.0,838.00,NaN,53.0,NaN,6.21,145.0,-0.34,0.66,51.41,XR,NTT,CHEMICALS
67,SIS,0.71,-3.68,25.89,21.26,27689.0,-4085.0,106947.0,528.00,105.28,42.0,H-SC,21.63,168.0,-0.15,0.69,59.01,OX40N,NTT,MISC

In [23]:
# top 5 RSP
df_tmp = df_portfolio_features.sort_values(by = 'RSP', ascending=False)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
25,FINCABLES,-0.95,65.70,25.48,107.91,62335.0,96999.0,244643.0,1641.55,20.71,73.0,M-SC,19.19,220.0,1.56,1.58,84.05,OX40N,ATH,CABLES
12,BOSCH-HCIL,2.10,-25.99,35.11,-0.01,33208.0,-33221.0,94584.0,2282.00,736.88,74.0,M-SC,5.71,231.0,-1.00,0.61,61.00,OX40N,BTT,AC
38,HYUNDAI,1.19,14.62,25.57,43.94,73662.0,36748.0,288080.0,2782.73,18.84,66.0,X-LC,5.01,29.0,0.50,1.86,32.27,X40N,ATH,AUTO
30,HAPPSTMNDS,-0.69,-47.09,246.00,83.08,166827.0,-60349.0,67816.0,1466.54,NaN,68.0,NaN,8.94,152.0,-0.36,0.44,27.02,AR,ATH,IT
81,VALIANTORG,-7.78,-37.81,180.03,74.15,183172.0,-61860.0,101745.0,838.00,NaN,53.0,NaN,6.21,145.0,-0.34,0.66,51.41,XR,NTT,CHEMICALS

In [24]:
# Top N allocation
df_tmp = df_portfolio_features.sort_values(by = 'CurrAlloc%', ascending=False)
top_n_values = [10, 25, 50]

sum_df = pd.DataFrame({
    'Top_N': top_n_values,
    'Sum_Alloc%': [df_tmp['CurrAlloc%'].head(n).sum() for n in top_n_values]
})

sum_df

   Top_N  Sum_Alloc%
0     10       19.77
1     25       45.19
2     50       77.59

In [25]:
# market-cap-wise allocation
df_tmp = df_portfolio_features[cols]
df_tmp.groupby(df_tmp['Conviction'].str[-2:])['CurrAlloc%'].sum().sort_values(ascending=False)

Conviction
LC    38.13
MC    22.22
SC    21.63
Name: CurrAlloc%, dtype: float64

In [26]:
# criteria-wise allocation
df_portfolio_features.groupby('Criteria')['CurrAlloc%'].sum().sort_values(ascending=False)

Criteria
X40      26.63
XY24     24.04
X40N     18.61
XR        9.12
OX40N     7.34
XY25      7.26
AR        6.16
SR        0.86
Name: CurrAlloc%, dtype: float64

In [27]:
# conviction-wise allocation
df_portfolio_features.groupby('Conviction')['CurrAlloc%'].sum().sort_values(ascending=False)

Conviction
X-LC    34.42
X-MC    19.59
H-SC     8.52
X-SC     7.67
M-SC     5.44
H-LC     2.90
M-MC     1.21
H-MC     1.05
M-LC     0.81
L-MC     0.37
Name: CurrAlloc%, dtype: float64

In [28]:
# sector-wise stats
df_tmp = df_portfolio_features.groupby('Category')[['CurrAlloc%', 'Current', 'Current P/L', 'FTT Amt']].sum().sort_values(by=['Current', 'Current P/L'], ascending=False)
df_tmp['Current P/L%'] = round(df_tmp['Current P/L'] * 100 / df_tmp['Current'], 2)
df_tmp['FTT%'] = round(df_tmp['FTT Amt'] * 100 / df_tmp['Current'], 2)
cols = ['CurrAlloc%', 'Current P/L%', 'FTT%']
df_tmp[cols].sort_values(by=['CurrAlloc%'], ascending=False)

               CurrAlloc%  Current P/L%    FTT%
Category
FMCG                15.46        -24.67   69.49
IT                  11.11        -38.74  107.55
FINANCE             10.76        -15.92   65.86
AUTO                 8.34         -4.86   42.41
BANKS                6.14        -12.28   60.70
MISC                 5.98        -33.16   86.72
PHARMA               5.76          7.01   19.37
INSURANCE            5.72         -4.99   42.11
PAINTS               5.52        -15.39   35.07
ELECTRICAL           4.22         -8.34   42.26
AC                   1.83        -12.72   43.28
REFINERIES           1.75        -10.32   47.38
BREWERIES            1.71         11.37    7.03
APPARELS             1.68         -3.44   38.18
FOOTWEAR             1.66        -71.32  140.01
CABLES               1.58         39.65   25.48
DURABLES             1.50        -67.29  107.99
TRAVEL               1.44       -100.42  200.78
CERAMICS             1.33        -48.91   94.14
ENGINEERING          1.20        -30.26   89.83
CHEMICALS            1.19        -43.92  160.74
CEMENT               1.02        -70.54  198.12
JEWELLERY            0.96       -114.76  189.37
ENTERTAINMENT        0.70        -79.35  186.31
HEALTHCARE           0.69        -70.52  113.32
TEXTILES             0.40        -50.49   93.39
HOTELS               0.37        -98.12  168.01

In [29]:
# money to be made criteria-wise
df_portfolio_features.groupby('Criteria')['FTT Amt'].agg(['sum', 'count']).sort_values(by='sum', ascending=False)

                sum  count
Criteria
XY24      3606012.0     19
X40       2106581.0     18
XR        1388785.0     13
X40N      1198318.0     12
AR        1054967.0      8
OX40N      655157.0     10
XY25       576882.0      5
SR         282538.0      2

In [30]:
# money to be made conviction-wise
df_portfolio_features.groupby('Conviction')['FTT Amt'].agg(['sum', 'count']).sort_values(by='sum', ascending=False)

                  sum  count
Conviction
X-LC        2400656.0     19
X-MC        1473667.0     14
X-SC        1092626.0      6
H-SC         830782.0      8
M-SC         324487.0      6
H-MC         251401.0      1
M-LC         167303.0      1
M-MC          58432.0      1
L-MC          44630.0      1
H-LC          41941.0      2

In [31]:
# money to be made criteria and conviction-wise
df_portfolio_features.groupby(['Conviction', 'Criteria'])['FTT Amt'].agg(['sum', 'count']).sort_values(by='sum', ascending=False)

                           sum  count
Conviction Criteria
X-LC       X40       1229152.0      9
X-SC       XY24       670278.0      2
H-SC       XY24       525395.0      3
X-MC       X40        514763.0      6
           X40N       466191.0      4
X-LC       XY24       450291.0      2
           X40N       411021.0      5
X-MC       XY25       267580.0      2
H-MC       XY24       251401.0      1
X-SC       X40        250956.0      2
X-LC       XY25       250870.0      2
X-MC       XY24       225133.0      2
H-SC       OX40N      212268.0      3
X-SC       X40N       171392.0      2
M-LC       XR         167303.0      1
M-SC       OX40N      151710.0      4
           XY24       115524.0      1
H-SC       XR          93119.0      2
X-LC       XR          59322.0      1
M-MC       XY25        58432.0      1
M-SC       XR          57253.0      1
L-MC       XR          44630.0      1
H-LC       AR          41941.0      2

In [32]:
# notebook execution time

end_time = time.time()
execution_time = round(end_time - start_time, 0)
print(f"Notebook execution time: {execution_time} seconds")

Notebook execution time: 38.0 seconds