<a href="https://colab.research.google.com/github/ankit-rathi/Quantvesting_v2/blob/main/myStocks_Portfolio_Analysis.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
'''
!pip install pandas==2.2.2 -qq
!pip install pyxirr -qq
!pip install ta -qq
!pip install yfinance==0.2.59 -qq
'''

'\n!pip install pandas==2.2.2 -qq\n!pip install pyxirr -qq\n!pip install ta -qq\n!pip install yfinance==0.2.59 -qq\n'

In [2]:
# import libraries

import numpy as np
import pandas as pd
import datetime
import warnings
warnings.filterwarnings('ignore')
import yfinance as yfin
import ta
import matplotlib.pyplot as plt
import requests

In [3]:
# notebook start time
import time
import datetime
import pytz

start_time = time.time()

# function to print date timestamp
def print_date_time():
  tz_NY = pytz.timezone('Asia/Kolkata')
  datetime_NY = datetime.datetime.now(tz_NY)
  print("Run date time (IST):", datetime_NY.strftime("%Y-%m-%d %H:%M:%S"))

In [4]:
# function to get booked and reserved amount
def get_amt():
  # fetch the JSON data from the URL
  url = "https://raw.githubusercontent.com/ankit-rathi/Tradevesting_v1/main/data/myPortfolioAmts.json"
  response = requests.get(url)
  pf_amts = response.json()  # parse the JSON data

  # extract values from the JSON
  py_booked_amt_dm = pf_amts["py_booked_amt_dm"]
  py_booked_amt_sv = pf_amts["py_booked_amt_sv"]
  cy_booked_amt_dm = pf_amts["cy_booked_amt_dm"]
  cy_booked_amt_sv = pf_amts["cy_booked_amt_sv"]
  reserve_amt_dm = pf_amts["reserve_amt_dm"]
  reserve_amt_sv = pf_amts["reserve_amt_sv"]

  # perform calculations
  py_booked_amt = py_booked_amt_dm + py_booked_amt_sv
  cy_booked_amt = cy_booked_amt_dm + cy_booked_amt_sv
  reserve_amt = reserve_amt_dm + reserve_amt_sv
  total_booked_amt = py_booked_amt + cy_booked_amt

  return total_booked_amt, reserve_amt, cy_booked_amt, py_booked_amt

gen_output = 0

In [5]:
# function to format the amount
def format_amt(number):
    abs_number = abs(number)

    if abs_number >= 1_00_00_000:  # Crores
        formatted_amt = f"{number / 1_00_00_000:.2f} C"
    elif abs_number >= 1_00_000:  # Lakhs
        formatted_amt = f"{number / 1_00_000:.2f} L"
    elif abs_number >= 1_000:  # Thousands
        formatted_amt = f"{number / 1_000:.2f} K"
    else:
        formatted_amt = f"{number:.2f}"

    return formatted_amt

# function to set start and end date
def get_start_end_date():
  start_date = (datetime.date.today() + datetime.timedelta(days=-365)).strftime('%Y-%m-%d')
  end_date = (datetime.date.today() + datetime.timedelta(days=1)).strftime('%Y-%m-%d')
  return start_date, end_date

# function to fetch my portfolio csv
def get_mypfs_df():
  mypfs_df = pd.read_csv('https://raw.githubusercontent.com/ankit-rathi/Tradevesting_v1/main/data/myPortfolioStocks.csv')
  return mypfs_df

# function to fetch my prospects csv
def get_mypps_df():
  mypps_df = pd.read_csv('https://raw.githubusercontent.com/ankit-rathi/Tradevesting_v1/main/data/myProspectsScrips.csv')
  return mypps_df

# function to fetch screener data
def get_myscreen_df():
  myscreen_df = pd.read_csv('https://raw.githubusercontent.com/ankit-rathi/Tradevesting_v1/main/data/myScreenerDB.csv')
  return myscreen_df

# function to fetch momentum data
def get_myinvmt_df():
  myinvmt_df = pd.read_csv('https://raw.githubusercontent.com/ankit-rathi/Tradevesting_v1/main/data/myInvestments.csv')
  return myinvmt_df

# function to get the stock ids
def get_stock_ids(df_pf):
  stock_n100 = df_pf['Symbol'].unique()

  exclude = ['CADILAHC','MMTC', 'MASFIN']

  stock_ids = df_pf[~df_pf['Symbol'].isin(exclude) ]['Symbol'].unique()

  #mypf = mypf[mypf.Forecast.notnull()]
  #stock_ids = mypf['Symbol'].unique()

  #stock_ids.sort()
  return stock_ids

# get features from screener data
def get_screener_features():
  myscreen_df = get_myscreen_df()
  cols = ['Symbol', 'EPS', 'MedPE', 'ROCE%', 'ROE%', 'CapType']
  return myscreen_df[cols]

# get relative strength
def get_relative_strength(stock_list):

    # Dictionary to store stock tickers and their corresponding percentage price change
    stock_changes = {}

    # Loop through each stock and fetch its price data
    for stock in stock_list:
        try:
            # Download the stock data for the given date range
            stock_data = yfin.Ticker(stock + '.NS').history(period='1mo', interval='1d')[map(str.title, ['open', 'close', 'low', 'high', 'volume'])]

            # Calculate the percentage change for the stock
            if len(stock_data) > 0:
                start_price = stock_data['Close'].iloc[0]
                end_price = stock_data['Close'].iloc[-1]
                percent_change = round(((end_price - start_price) / start_price) * 100, 2)
                stock_changes[stock] = percent_change
            else:
                stock_changes[stock] = np.nan  # If no data is available, set to NaN

        except Exception as e:
            print(f"Error fetching data for {stock}: {e}")
            stock_changes[stock] = np.nan

    # Create a DataFrame with stock tickers and their percentage changes
    df = pd.DataFrame(list(stock_changes.items()), columns=['Symbol', 'Percent_Change'])

    # Drop any stocks with missing data (NaN values)
    df = df.dropna()

    # Calculate the percentile rank based on percentage change
    df['RSP'] = round(df['Percent_Change'].rank(pct=True) * 100, 2)
    cols = ['Symbol', 'RSP']
    df = df[cols]
    # Sort by percentile rank (optional)
    df = df.sort_values(by='RSP', ascending=False).reset_index(drop=True)

    return df

In [6]:
# function to get stock technicals
def stock_prec_dev(stock_symbol):
    #stock_symbol = 'ULTRACEMCO.NS'
    short_window = 20
    mid_window = 50
    long_window = 200
    moving_avg = 'SMA'

    start = datetime.datetime(*map(int, start_date.split('-')))
    end = datetime.datetime(*map(int, end_date.split('-')))

    stock_df = yfin.Ticker(stock_symbol + '.NS').history(period='max', interval='1d')[map(str.title, ['open', 'close', 'low', 'high', 'volume'])]

    stock_df['Max'] = round(max(stock_df['Close']),2)
    stock_df = stock_df[(stock_df.index <= end_date) & (stock_df.index >= start_date)]
    stock_df['200_SMA'] = round(stock_df['Close'].rolling(window = 200, min_periods = 1).mean(),0)
    stock_df['Dev%_200'] = round((stock_df['Close'] - stock_df['200_SMA'])*100/stock_df['200_SMA'],2)
    stock_df.dropna(axis = 0, inplace = True) # remove any null rows

    stock_df['20_SMA'] = stock_df['Close'].rolling(window=20).mean()
    stock_df['50_SMA'] = stock_df['Close'].rolling(window=50).mean()
    stock_df['Symbol'] = stock_symbol

    stock_df['Close'] = round(stock_df['Close'],2)
    stock_df['Min'] = round(min(stock_df['Close']),2)
    stock_df['RSI_14'] = ta.momentum.RSIIndicator(close=stock_df['Close'], window=14).rsi()
    stock_df['RSI_14'] = round(stock_df['RSI_14'],0)
    stock_df['Prev_Close'] = stock_df['Close'].shift(1)
    stock_df.drop(['Open', 'Low', 'High', 'Volume'], axis=1, inplace=True)
    stock_df = stock_df.tail(1)

    max_SMA = max(stock_df['20_SMA'].item(), stock_df['50_SMA'].item(), stock_df['200_SMA'].item())
    min_SMA = min(stock_df['20_SMA'].item(), stock_df['50_SMA'].item(), stock_df['200_SMA'].item())
    ABS_Spread = max_SMA - min_SMA
    stock_df['Spread%'] = round((ABS_Spread / stock_df['200_SMA'].item()) * 100,2)

    return stock_df

# function to compute stock attributes
def get_common_features(stock_ids, df_mypf):

  df_prec_dev = pd.DataFrame()
  df_tmp = get_screener_features()
  df_rs = get_relative_strength(stock_ids)

  for stock_id in stock_ids:
      tmp = stock_prec_dev(stock_id)
      tmp = tmp.reset_index()
      df_prec_dev = pd.concat([df_prec_dev, tmp], ignore_index = True)
  df_prec_dev = pd.merge(df_prec_dev, df_mypf, on= 'Symbol')
  df_prec_dev = pd.merge(df_prec_dev, df_tmp, on= 'Symbol', how='left')
  df_prec_dev = pd.merge(df_prec_dev, df_rs, on= 'Symbol', how='left')
  #print(df_prec_dev.columns)
  df_prec_dev['Curr_PE'] = round(df_prec_dev['Close']/df_prec_dev['EPS'],1)
  df_prec_dev['Dev%_PE'] = round((df_prec_dev['Curr_PE'] - df_prec_dev['MedPE'])*100/df_prec_dev['MedPE'],2)
  df_prec_dev['Conviction'] = df_prec_dev['Conviction'] + '-' + df_prec_dev['CapType']
  return df_prec_dev

# function to arrange stock features
def arrange_features(df_stocks, common_cols, diff_cols):
  df_stocks_common = df_stocks[common_cols].drop_duplicates()
  df_stocks_diff = df_stocks[diff_cols]
  df_stocks_diff['Investment'] = df_stocks_diff['AvgCost'] * df_stocks_diff['Shares']
  df_stocks_diff = df_stocks_diff.groupby(['Symbol'])[['Shares', 'Investment']].aggregate(['sum']).reset_index()
  df_stocks_diff.columns = ['Symbol', 'Shares', 'Investment']
  df_stocks_diff['AvgCost'] = round(df_stocks_diff['Investment']/df_stocks_diff['Shares'],2)
  df_stocks = pd.merge(df_stocks_diff, df_stocks_common, on='Symbol')
  return df_stocks

# plot fact distribution across dimension
def plot_pie_chart(df, dimension, fact):
  # grouping the data by category and calculating the sum of fact for each type
  grouped_data = df.groupby(dimension)[fact].sum()

  # sorting the grouped data in descending order
  grouped_data = grouped_data.sort_values(ascending=False)

  # creating a pie chart
  grouped_data.plot.pie(autopct='%1.1f%%', startangle=90, figsize=(6, 6))

  # adding a title and displaying the plot
  plt.title(f'{dimension} {fact} Distribution')
  plt.ylabel('')  # To hide the y-label
  plt.show()

In [7]:
# function to get portfolio features

def get_portfolio_features(df_common_features):

  print_date_time()
  print('-------------------')

  #df_common_features["Target"] = df_common_features["Target"].fillna(df_common_features["Max"])
  df_common_features['NTT'] = np.where(df_common_features['Strategy']== 'NTT', df_common_features["Target"], df_common_features['Max'])
  df_common_features['LTT'] = np.where(df_common_features['Strategy']== 'BTT', df_common_features["Target"], df_common_features['Max'])
  df_common_features['BOL'] = df_common_features['Min']

  tmp_df = df_common_features[df_common_features['Symbol'].isin(mypf_df[mypf_df['InPortfolio'] != 'NA'].Symbol.values)]
  print('qualified stocks: '+str(len(tmp_df['Symbol'].unique())))
  tmp_df1 = tmp_df[tmp_df['LatestQtr'] == 1]
  print('with latest results: '+str(len(tmp_df1['Symbol'].unique())))
  tmp_df1 = tmp_df1[tmp_df1['StarStock'] == 1]
  print('still star stocks: '+str(len(tmp_df1['Symbol'].unique())))
  tmp_df['Investment'] = tmp_df['AvgCost'] * tmp_df['Shares']
  tmp_df['Current'] = round(tmp_df['Close'] * tmp_df['Shares'],0)
  tmp_df['Previous'] = tmp_df['Prev_Close'] * tmp_df['Shares']
  tmp_df['EstimatedST'] = tmp_df['NTT'] * tmp_df['Shares']
  tmp_df['EstimatedLT'] = tmp_df['LTT'] * tmp_df['Shares']
  tmp_df['Current P/L'] = round((tmp_df['Current'] - tmp_df['Investment']),0)
  tmp_df['Today P/L%'] = round((tmp_df['Current'] - tmp_df['Previous'])*100/tmp_df['Previous'],2)
  tmp_df['Current P/L%'] = round((tmp_df['Current'] - tmp_df['Investment'])*100/tmp_df['Investment'],2)
  tmp_df['EstimatedST P/L%'] = round((tmp_df['EstimatedST'] - tmp_df['Investment'])*100/tmp_df['Investment'],2)
  tmp_df['EstimatedLT P/L%'] = round((tmp_df['EstimatedLT'] - tmp_df['Investment'])*100/tmp_df['Investment'],2)
  tmp_df['NTT%'] = round((tmp_df['NTT'] - tmp_df['Close'])*100/tmp_df['Close'],2)
  tmp_df['LTT%'] = round((tmp_df['LTT'] - tmp_df['Close'])*100/tmp_df['Close'],2)
  tmp_df['Gained%'] = round((tmp_df['Close'] - tmp_df['BOL'])*100/tmp_df['BOL'],2)
  investment = round(sum(tmp_df['AvgCost']*tmp_df['Shares']),0)
  current = round(sum(tmp_df['Close']*tmp_df['Shares']),0)
  tmp_df['InitAlloc%'] = round(tmp_df['Investment']*100/investment,2)
  tmp_df['CurrAlloc%'] = round(tmp_df['Current']*100/current,2)
  tmp_df['FTT'] = tmp_df['LTT']
  tmp_df.loc[tmp_df['Strategy'] == 'NTT', 'FTT'] = tmp_df['NTT']
  tmp_df['FTT%'] = tmp_df['LTT%']
  tmp_df.loc[tmp_df['Strategy'] == 'NTT', 'FTT%'] = tmp_df['NTT%']
  tmp_df['FTT Amt'] = round(tmp_df['FTT%'] * tmp_df['Current']/100,0)
  tmp_df['OTT%'] = round((tmp_df['FTT'] - tmp_df['AvgCost'])*100/tmp_df['AvgCost'],2)
  tmp_df['RRR Ind'] = round(tmp_df['Current P/L']/tmp_df['FTT Amt'],2)
  tmp_df['Risk Ind'] = round(tmp_df['Current P/L%']*tmp_df['CurrAlloc%'],0)

  return tmp_df

# function to print portfolio features
def print_portfolio_stats(df_portfolio_features, myinvmt_df):
  from pyxirr import xirr

  total_booked_amt, reserve_amt, cy_booked_amt, py_booked_amt = get_amt()

  dates = myinvmt_df['Date'].values
  dates = np.append(dates, datetime.date.today().strftime('%d-%b-%y'))
  investment = myinvmt_df['Investment'].values
  dates= pd.to_datetime(dates)

  current = round(sum(df_portfolio_features['Close']*df_portfolio_features['Shares']),0) + reserve_amt
  investment_xirr = np.append(investment, current)
  cagr = round(xirr(pd.DataFrame({"dates": dates, "amounts": investment_xirr}))*100,2)

  investment = -sum(investment)
  invested = round(sum(df_portfolio_features['AvgCost']*df_portfolio_features['Shares']),0) + reserve_amt
  previous = round(sum(df_portfolio_features['Prev_Close']*df_portfolio_features['Shares']),0) + reserve_amt
  cy_invested = investment + py_booked_amt

  today_pnl_amount = current-previous
  today_pnl_percentage = round((current-previous)*100/previous,2)

  curr_pnl_amount = current-invested
  curr_pnl_percentage = round((curr_pnl_amount)*100/(cy_invested),2)

  cy_pnl_amount = cy_booked_amt + curr_pnl_amount
  cy_pnl_percentage = round((cy_pnl_amount)*100/cy_invested,2)

  overall_pnl_amount = total_booked_amt + curr_pnl_amount
  overall_pnl_percentage = round((overall_pnl_amount)*100/investment,2)

  estimate_st = round(sum(df_portfolio_features['FTT']*df_portfolio_features['Shares']),0)  + reserve_amt
  est_st_pnl_amount = estimate_st-current
  est_st_pnl_percentage = round((est_st_pnl_amount)*100/current,2)

  estimate_lt = round(sum(df_portfolio_features['LTT']*df_portfolio_features['Shares']),0)  + reserve_amt
  est_lt_pnl_amount = estimate_lt-current
  est_lt_pnl_percentage = round((est_lt_pnl_amount)*100/current,2)

  total_profit = round(sum(df_portfolio_features[df_portfolio_features['Current P/L%'] > 0]['Current']) - sum(df_portfolio_features[df_portfolio_features['Current P/L%'] > 0]['Investment']),0)
  total_loss = round(sum(df_portfolio_features[df_portfolio_features['Current P/L%'] < 0]['Current']) - sum(df_portfolio_features[df_portfolio_features['Current P/L%'] < 0]['Investment']),0)

  cy_booked_percentage = round((cy_booked_amt)*100/current,2)
  py_booked_percentage = round((py_booked_amt)*100/investment,2)
  total_booked_percentage = round((total_booked_amt)*100/investment,2)

  print('-------------------')
  print('Initial Investment: ', format_amt(investment))
  print('CY Investment: ', format_amt(cy_invested))
  print('Reserve: ', format_amt(reserve_amt))
  print('Current: ',  format_amt(current))
  print('-------------------')
  print('Today PnL: '+ '{} ({}%)'.format(format_amt(today_pnl_amount), today_pnl_percentage))
  print('Current PnL: '+ '{} ({}%)'.format(format_amt(curr_pnl_amount), curr_pnl_percentage))
  print('CY Booked + Current PnL: '+ '{} ({}%)'.format(format_amt(cy_pnl_amount), cy_pnl_percentage))
  print('-------------------')
  print('Total profit: ', format_amt(total_profit))
  print('Total loss: ', format_amt(total_loss))
  print('-------------------')
  print('Total Booked + Current PnL: '+ '{} ({}%)'.format(format_amt(overall_pnl_amount), overall_pnl_percentage))
  print('Total Booked PnL: '+ '{} ({}%)'.format(format_amt(total_booked_amt), total_booked_percentage))
  print('Curr Year Booked PnL: '+ '{} ({}%)'.format(format_amt(cy_booked_amt), cy_booked_percentage))
  print('Prev Year Booked PnL: '+ '{} ({}%)'.format(format_amt(py_booked_amt), py_booked_percentage))
  print('===================')
  print('Est FTT: ',  format_amt(estimate_st))
  print('Est FTT PnL: '+ '{} ({}%)'.format(format_amt(est_st_pnl_amount), est_st_pnl_percentage))

  print('===================')
  print('Deployed: ', format_amt(investment))

  print('Current: ', format_amt(current))

  print('CAGR/XIRR %: '+'{}%'.format(cagr))

In [8]:
# get start and end date
start_date, end_date = get_start_end_date()

# get portfolio and prospects data
mypfs_df = get_mypfs_df()
mypps_df = get_mypps_df()
myinvmt_df = get_myinvmt_df()

# merge above datasets
mypf_df = pd.merge(mypfs_df, mypps_df, on="Symbol")

# seggregate dm and sv portfolio
dm_pf = mypf_df[mypf_df['InPortfolio'] == 'DM']
sv_pf = mypf_df[mypf_df['InPortfolio'] == 'SV']

# build portfolio stock dataframe
dm_stocks = get_stock_ids(dm_pf)
sv_stocks = get_stock_ids(sv_pf)
df_stocks = pd.concat([dm_pf,sv_pf], ignore_index = True)

# arrange common and diff stock features
common_cols = ['Symbol', 'Target', 'Criteria', 'Strategy', 'CumlRnk', 'LatestQtr', 'StarStock', 'Conviction', 'Category', 'InFolio', 'XIRR', 'MBQ']
diff_cols = ['Symbol', 'AvgCost', 'Shares']
df_stocks = arrange_features(df_stocks, common_cols, diff_cols)

# get common features
stock_ids = df_stocks['Symbol'].values
df_common_features = get_common_features(stock_ids, df_stocks)

df_common_features.reset_index(drop=True, inplace=True)
df_common_features.drop(['Date'], axis=1, inplace=True)
# get and print portfolio features
df_portfolio_features = get_portfolio_features(df_common_features)

print_portfolio_stats(df_portfolio_features, myinvmt_df)

df = df_portfolio_features
#plot_pie_chart(df, 'CapType', 'Current')
list_ox40n = list(df[df['MBQ'].str.contains('OX40N', na=False)]['Symbol'].values)

Run date time (IST): 2026-05-05 12:58:51
-------------------
qualified stocks: 92
with latest results: 31
still star stocks: 20
-------------------
Initial Investment:  1.40 C
CY Investment:  1.82 C
Reserve:  1.49 K
Current:  1.49 C
-------------------
Today PnL: 19.60 K (0.13%)
Current PnL: -34.02 L (-18.66%)
CY Booked + Current PnL: -31.94 L (-17.52%)
-------------------
Total profit:  1.34 L
Total loss:  -35.37 L
-------------------
Total Booked + Current PnL: 10.93 L (7.83%)
Total Booked PnL: 44.95 L (32.22%)
Curr Year Booked PnL: 2.08 L (1.39%)
Prev Year Booked PnL: 42.87 L (30.73%)
===================
Est FTT:  2.55 C
Est FTT PnL: 1.06 C (71.26%)
===================
Deployed:  1.40 C
Current:  1.49 C
CAGR/XIRR %: 3.31%

In [9]:
# top 5 near their targets
cols = ['Symbol', 'Today P/L%', 'Current P/L%', 'FTT%', 'OTT%', 'FTT Amt', 'Current P/L', 'Current', 'FTT', 'Dev%_PE', 'RSI_14','Conviction', 'Spread%',  'CumlRnk', 'RRR Ind', 'CurrAlloc%', 'Gained%', 'Criteria', 'Strategy', 'Category']
df_tmp = df_portfolio_features[~df_portfolio_features['Symbol'].isin(['ENRIN','BLUSPRING','DIGITIDE'])]
df_tmp = df_tmp.sort_values(by = 'FTT Amt', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
55,MASFIN,-0.79,5.39,15.35,21.57,15850.0,5280.0,103260.0,397.04,-9.21,69.0,H-SC,2.49,167.0,0.33,0.69,33.44,XR,ATH,FINANCE
51,KOTAKBANK,0.34,-0.36,21.54,21.11,29719.0,-500.0,137973.0,453.24,-14.61,46.0,X-LC,7.90,12.0,-0.02,0.93,5.52,X40,ATH,BANKS
53,M&M,0.51,1.31,21.79,23.38,30615.0,1818.0,140499.0,3802.40,-14.09,48.0,X-LC,8.30,25.0,0.06,0.94,6.52,X40N,ATH,AUTO
59,PIDILITIND,-0.26,-3.54,22.71,18.37,30911.0,-5000.0,136110.0,1670.26,-32.45,47.0,X-LC,6.33,5.0,-0.16,0.91,6.87,X40,ATH,CHEMICALS
83,TTKPRESTIG,-1.03,-31.00,45.05,0.09,31328.0,-31236.0,69541.0,770.00,61.37,61.0,M-SC,17.20,250.0,-1.00,0.47,23.83,OX40N,NTT,DURABLES

In [10]:
# top 5 today
df_tmp = df_portfolio_features.sort_values(by = 'Today P/L%', ascending=False)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
80,TITAGARH,9.46,-20.71,83.79,45.74,160904.0,-50144.0,192033.0,1548.00,5.62,73.0,H-SC,14.51,175.0,-0.31,1.29,46.52,XY24,NTT,ENGINEERING
60,QUESS,9.15,-5.26,83.55,73.90,84534.0,-5615.0,101178.0,424.00,-49.31,76.0,X-SC,14.45,80.0,-0.07,0.68,36.11,XY24,NTT,MISC
15,CAMS,8.10,3.52,20.25,24.48,52795.0,8860.0,260716.0,950.00,-0.83,69.0,X-SC,6.38,89.0,0.17,1.75,26.93,X40N,NTT,MISC
25,FINCABLES,5.64,35.98,52.89,107.91,106189.0,53129.0,200773.0,1641.55,22.27,78.0,M-SC,13.19,220.0,0.50,1.35,51.05,OX40N,ATH,CABLES
29,GREENPANEL,2.69,-36.33,124.82,43.14,145495.0,-66514.0,116564.0,537.00,160.98,73.0,M-SC,18.48,225.0,-0.46,0.78,40.02,XY24,NTT,MISC

In [11]:
# bottom 5 today
df_tmp = df_portfolio_features.sort_values(by = 'Today P/L%', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
88,VOLTAS,-4.17,9.02,33.18,45.20,69359.0,17298.0,209040.0,1856.00,24.80,47.0,X-MC,1.94,79.0,0.25,1.40,14.58,XY25,NTT,AC
76,SYMPHONY,-2.43,-38.42,62.33,-0.03,65693.0,-65745.0,105396.0,1306.00,-50.64,50.0,M-SC,11.81,205.0,-1.00,0.71,16.89,OX40N,NTT,DURABLES
42,INDIAMART,-2.39,-12.14,135.30,106.72,146608.0,-14978.0,108358.0,4810.62,-60.35,39.0,H-SC,9.32,140.0,-0.10,0.73,4.10,AR,ATH,MISC
5,ATULAUTO,-2.34,-16.35,74.02,45.57,122059.0,-32232.0,164900.0,844.00,3570.27,58.0,M-SC,3.13,248.0,-0.26,1.11,26.90,XY24,NTT,AUTO
89,WHIRLPOOL,-1.73,-21.65,132.19,81.92,118897.0,-24854.0,89944.0,2270.00,-54.14,66.0,M-SC,18.27,210.0,-0.21,0.60,26.34,XR,NTT,DURABLES

In [12]:
# top 5 to exit based on CumlRnk
df_tmp = df_portfolio_features[~df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])]
df_tmp = df_tmp[(df_tmp['Current P/L%'] > -1) & (df_tmp['Current P/L%'] < 1)].sort_values(by = 'CumlRnk', ascending=False)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
73,SONACOMS,0.02,-0.43,39.70,39.09,39986.0,-438.0,100721.0,804.02,-21.15,54.0,M-MC,18.50,193.0,-0.01,0.68,42.48,AR,ATH,AUTO
9,BANDHANBNK,-0.06,-0.60,93.58,92.42,259108.0,-1675.0,276884.0,400.00,137.79,77.0,H-SC,10.66,174.0,-0.01,1.86,52.53,XY24,NTT,BANKS
74,STARHEALTH,-0.08,0.53,46.49,47.26,131384.0,1485.0,282608.0,761.00,58.55,65.0,H-SC,7.36,173.0,0.01,1.89,46.36,XY24,NTT,INSURANCE

In [13]:
# OX40N stocks to exit
df_tmp = df_portfolio_features[(df_portfolio_features['Symbol'].isin(list_ox40n))].sort_values(by = 'Current P/L%', ascending=False)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
25,FINCABLES,5.64,35.98,52.89,107.91,106189.0,53129.0,200773.0,1641.55,22.27,78.0,M-SC,13.19,220.0,0.50,1.35,51.05,OX40N,ATH,CABLES
72,SIS,-0.09,-8.10,31.95,21.26,32601.0,-8994.0,102038.0,528.00,2428.50,80.0,H-SC,7.55,168.0,-0.28,0.68,51.72,OX40N,NTT,MISC
16,CERA,1.51,-29.65,76.10,23.89,94175.0,-52151.0,123752.0,9475.00,-32.22,61.0,H-SC,11.94,153.0,-0.55,0.83,18.92,OX40N,NTT,CERAMICS
83,TTKPRESTIG,-1.03,-31.00,45.05,0.09,31328.0,-31236.0,69541.0,770.00,61.37,61.0,M-SC,17.20,250.0,-1.00,0.47,23.83,OX40N,NTT,DURABLES
50,KANSAINER,-1.61,-35.41,75.69,13.47,131828.0,-95499.0,174168.0,340.00,-44.56,50.0,H-SC,16.25,162.0,-0.72,1.17,21.66,XY24,NTT,PAINTS

In [14]:
# top 5 to book for rotation
df_tmp = df_portfolio_features[(df_portfolio_features['Current P/L%'] > 20) ].sort_values(by = 'CumlRnk', ascending=False)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
25,FINCABLES,5.64,35.98,52.89,107.91,106189.0,53129.0,200773.0,1641.55,22.27,78.0,M-SC,13.19,220.0,0.5,1.35,51.05,OX40N,ATH,CABLES

In [15]:
# top 5 to monitor for exit
df_tmp = df_portfolio_features[~df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])]
df_tmp = df_tmp[(df_tmp['Current P/L%'] > 0) ].sort_values(by = 'Dev%_PE', ascending=False)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
74,STARHEALTH,-0.08,0.53,46.49,47.26,131384.0,1485.0,282608.0,761.00,58.55,65.0,H-SC,7.36,173.0,0.01,1.89,46.36,XY24,NTT,INSURANCE
25,FINCABLES,5.64,35.98,52.89,107.91,106189.0,53129.0,200773.0,1641.55,22.27,78.0,M-SC,13.19,220.0,0.50,1.35,51.05,OX40N,ATH,CABLES
68,SATIN,-1.09,3.35,46.92,51.83,133972.0,9248.0,285532.0,274.00,-8.02,69.0,H-SC,11.86,159.0,0.07,1.91,39.10,XY24,NTT,FINANCE
55,MASFIN,-0.79,5.39,15.35,21.57,15850.0,5280.0,103260.0,397.04,-9.21,69.0,H-SC,2.49,167.0,0.33,0.69,33.44,XR,ATH,FINANCE

In [16]:
# top 5 to book for rotation from weak conviction
df_tmp = df_portfolio_features[~df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])]
df_tmp = df_tmp[~df_tmp['Criteria'].isin(['XY25','XY24','X40', 'X40N'])].sort_values(by = 'RRR Ind', ascending=False)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
25,FINCABLES,5.64,35.98,52.89,107.91,106189.0,53129.0,200773.0,1641.55,22.27,78.0,M-SC,13.19,220.0,0.50,1.35,51.05,OX40N,ATH,CABLES
55,MASFIN,-0.79,5.39,15.35,21.57,15850.0,5280.0,103260.0,397.04,-9.21,69.0,H-SC,2.49,167.0,0.33,0.69,33.44,XR,ATH,FINANCE
73,SONACOMS,0.02,-0.43,39.70,39.09,39986.0,-438.0,100721.0,804.02,-21.15,54.0,M-MC,18.50,193.0,-0.01,0.68,42.48,AR,ATH,AUTO
42,INDIAMART,-2.39,-12.14,135.30,106.72,146608.0,-14978.0,108358.0,4810.62,-60.35,39.0,H-SC,9.32,140.0,-0.10,0.73,4.10,AR,ATH,MISC
91,ZYDUSLIFE,0.50,-4.37,41.82,35.63,83818.0,-9149.0,200425.0,1286.17,-16.67,48.0,H-MC,3.86,120.0,-0.11,1.34,5.38,AR,ATH,PHARMA

In [17]:
# top 5 to accumulate based on lowest RSI_14
df_tmp = df_portfolio_features[df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])].sort_values(by = 'RSI_14', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
33,HCLTECH,0.03,-22.07,55.91,21.51,105413.0,-53383.0,188541.0,1872.35,-18.11,31.0,X-LC,10.19,8.0,-0.51,1.26,0.41,X40,ATH,IT
45,INFY,0.30,-20.22,68.27,34.24,170412.0,-63273.0,249615.0,1972.00,-37.23,35.0,X-LC,14.46,3.0,-0.37,1.67,1.72,X40,NTT,IT
1,ABBOTINDIA,-0.39,-15.08,39.03,18.07,59283.0,-26965.0,151890.0,35195.00,-27.72,40.0,X-MC,12.02,58.0,-0.45,1.02,0.54,X40,ATH,PHARMA
34,HDFCBANK,-1.30,-7.97,39.48,28.37,85345.0,-18712.0,216173.0,1073.00,-22.01,41.0,X-LC,15.51,26.0,-0.22,1.45,5.16,X40,BTT,BANKS
2,ACC,-0.99,-38.05,182.16,74.81,302597.0,-102012.0,166116.0,3906.00,-56.11,42.0,X-SC,17.37,85.0,-0.34,1.11,10.34,XY24,BTT,CEMENT

In [18]:
# top 5 to accumulate based on Spread and CumlRnk
df_tmp = df_portfolio_features[df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])]
df_tmp = df_tmp[(df_tmp['CumlRnk'] < 100)].sort_values(by = 'Spread%', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
88,VOLTAS,-4.17,9.02,33.18,45.20,69359.0,17298.0,209040.0,1856.00,24.80,47.0,X-MC,1.94,79.0,0.25,1.40,14.58,XY25,NTT,AC
84,UNITDSPR,-0.72,-3.61,25.29,20.77,57079.0,-8446.0,225698.0,1644.00,-14.48,48.0,X-MC,3.07,64.0,-0.15,1.51,7.66,X40N,NTT,BREWERIES
65,RELIANCE,0.11,-5.98,33.27,25.30,62862.0,-12017.0,188946.0,1952.00,-8.50,67.0,X-LC,4.40,21.0,-0.19,1.27,12.27,XY25,BTT,REFINERIES
81,TMPV,-0.34,-22.17,75.49,36.58,209061.0,-78902.0,276939.0,600.00,-83.62,49.0,X-LC,4.78,4.0,-0.38,1.86,15.43,XY24,NTT,AUTO
19,COLPAL,-0.12,-17.59,71.71,41.51,155639.0,-46325.0,217040.0,3726.84,-0.25,64.0,X-MC,5.21,62.0,-0.30,1.46,21.34,XY25,ATH,FMCG

In [19]:
# top 5 to accumulate based on lowest Gained%
df_tmp = df_portfolio_features[df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])].sort_values(by = 'Gained%', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
33,HCLTECH,0.03,-22.07,55.91,21.51,105413.0,-53383.0,188541.0,1872.35,-18.11,31.0,X-LC,10.19,8.0,-0.51,1.26,0.41,X40,ATH,IT
1,ABBOTINDIA,-0.39,-15.08,39.03,18.07,59283.0,-26965.0,151890.0,35195.00,-27.72,40.0,X-MC,12.02,58.0,-0.45,1.02,0.54,X40,ATH,PHARMA
45,INFY,0.30,-20.22,68.27,34.24,170412.0,-63273.0,249615.0,1972.00,-37.23,35.0,X-LC,14.46,3.0,-0.37,1.67,1.72,X40,NTT,IT
79,TCS,-0.14,-28.72,77.58,26.57,256175.0,-133065.0,330208.0,4311.59,-39.69,42.0,X-LC,13.90,2.0,-0.52,2.21,3.06,X40,ATH,IT
39,ICICIGI,0.60,-6.38,27.47,19.34,51463.0,-12765.0,187344.0,2252.93,-21.30,43.0,X-MC,5.55,66.0,-0.25,1.26,4.64,X40,ATH,INSURANCE

In [20]:
# top 5 to accumulate based on lowest CurrAlloc%
df_tmp = df_portfolio_features[df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])].sort_values(by = 'CurrAlloc%', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
64,RELAXO,-0.45,-61.19,292.39,52.31,164744.0,-88816.0,56344.0,1176.00,-58.67,50.0,X-SC,25.53,92.0,-0.54,0.38,25.98,X40N,NTT,FOOTWEAR
10,BATAINDIA,0.33,-53.31,189.60,35.20,113895.0,-68599.0,60071.0,2096.00,-21.30,50.0,X-SC,26.12,91.0,-0.60,0.40,19.14,X40,NTT,FOOTWEAR
60,QUESS,9.15,-5.26,83.55,73.90,84534.0,-5615.0,101178.0,424.00,-49.31,76.0,X-SC,14.45,80.0,-0.07,0.68,36.11,XY24,NTT,MISC
59,PIDILITIND,-0.26,-3.54,22.71,18.37,30911.0,-5000.0,136110.0,1670.26,-32.45,47.0,X-LC,6.33,5.0,-0.16,0.91,6.87,X40,ATH,CHEMICALS
51,KOTAKBANK,0.34,-0.36,21.54,21.11,29719.0,-500.0,137973.0,453.24,-14.61,46.0,X-LC,7.90,12.0,-0.02,0.93,5.52,X40,ATH,BANKS

In [21]:
# top 5 to accumulate based on CumlRnk
df_tmp = df_portfolio_features.sort_values(by = 'CumlRnk', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
47,ITC,0.18,-17.91,45.03,19.06,125741.0,-60928.0,279238.0,452.00,-55.12,56.0,X-LC,15.89,1.0,-0.48,1.87,8.32,X40,NTT,FMCG
79,TCS,-0.14,-28.72,77.58,26.57,256175.0,-133065.0,330208.0,4311.59,-39.69,42.0,X-LC,13.90,2.0,-0.52,2.21,3.06,X40,ATH,IT
45,INFY,0.30,-20.22,68.27,34.24,170412.0,-63273.0,249615.0,1972.00,-37.23,35.0,X-LC,14.46,3.0,-0.37,1.67,1.72,X40,NTT,IT
81,TMPV,-0.34,-22.17,75.49,36.58,209061.0,-78902.0,276939.0,600.00,-83.62,49.0,X-LC,4.78,4.0,-0.38,1.86,15.43,XY24,NTT,AUTO
59,PIDILITIND,-0.26,-3.54,22.71,18.37,30911.0,-5000.0,136110.0,1670.26,-32.45,47.0,X-LC,6.33,5.0,-0.16,0.91,6.87,X40,ATH,CHEMICALS

In [22]:
# top 5 for average up
df_tmp = df_portfolio_features[(df_portfolio_features['Dev%_200'] > 5)].sort_values(by = 'CurrAlloc%', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
44,INDUSINDBK,-0.22,-32.68,97.39,32.89,50621.0,-25228.0,51978.0,1800.00,-344.40,62.0,L-MC,3.64,258.0,-0.50,0.35,27.94,XR,NTT,BANKS
72,SIS,-0.09,-8.10,31.95,21.26,32601.0,-8994.0,102038.0,528.00,2428.50,80.0,H-SC,7.55,168.0,-0.28,0.68,51.72,OX40N,NTT,MISC
73,SONACOMS,0.02,-0.43,39.70,39.09,39986.0,-438.0,100721.0,804.02,-21.15,54.0,M-MC,18.50,193.0,-0.01,0.68,42.48,AR,ATH,AUTO
55,MASFIN,-0.79,5.39,15.35,21.57,15850.0,5280.0,103260.0,397.04,-9.21,69.0,H-SC,2.49,167.0,0.33,0.69,33.44,XR,ATH,FINANCE
75,SURYODAY,1.00,-10.31,37.18,23.03,59714.0,-18462.0,160609.0,216.00,75.44,73.0,H-SC,7.75,166.0,-0.31,1.08,36.97,XR,NTT,BANKS

In [23]:
# top 5 RSP
df_tmp = df_portfolio_features.sort_values(by = 'RSP', ascending=False)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
72,SIS,-0.09,-8.10,31.95,21.26,32601.0,-8994.0,102038.0,528.00,2428.50,80.0,H-SC,7.55,168.0,-0.28,0.68,51.72,OX40N,NTT,MISC
9,BANDHANBNK,-0.06,-0.60,93.58,92.42,259108.0,-1675.0,276884.0,400.00,137.79,77.0,H-SC,10.66,174.0,-0.01,1.86,52.53,XY24,NTT,BANKS
25,FINCABLES,5.64,35.98,52.89,107.91,106189.0,53129.0,200773.0,1641.55,22.27,78.0,M-SC,13.19,220.0,0.50,1.35,51.05,OX40N,ATH,CABLES
80,TITAGARH,9.46,-20.71,83.79,45.74,160904.0,-50144.0,192033.0,1548.00,5.62,73.0,H-SC,14.51,175.0,-0.31,1.29,46.52,XY24,NTT,ENGINEERING
29,GREENPANEL,2.69,-36.33,124.82,43.14,145495.0,-66514.0,116564.0,537.00,160.98,73.0,M-SC,18.48,225.0,-0.46,0.78,40.02,XY24,NTT,MISC

In [24]:
# Top N allocation
df_tmp = df_portfolio_features.sort_values(by = 'CurrAlloc%', ascending=False)
top_n_values = [10, 25, 50]

sum_df = pd.DataFrame({
    'Top_N': top_n_values,
    'Sum_Alloc%': [df_tmp['CurrAlloc%'].head(n).sum() for n in top_n_values]
})

sum_df

   Top_N  Sum_Alloc%
0     10       19.03
1     25       42.50
2     50       72.68

In [25]:
# market-cap-wise allocation
df_tmp = df_portfolio_features[cols]
df_tmp.groupby(df_tmp['Conviction'].str[-2:])['CurrAlloc%'].sum().sort_values(ascending=False)

Conviction
SC    42.62
LC    31.60
MC    25.78
Name: CurrAlloc%, dtype: float64

In [26]:
# criteria-wise allocation
df_portfolio_features.groupby('Criteria')['CurrAlloc%'].sum().sort_values(ascending=False)

Criteria
XY24     27.19
X40      25.41
X40N     16.85
XR        9.09
XY25      6.98
OX40N     6.97
AR        6.68
SR        0.83
Name: CurrAlloc%, dtype: float64

In [27]:
# conviction-wise allocation
df_portfolio_features.groupby('Conviction')['CurrAlloc%'].sum().sort_values(ascending=False)

Conviction
X-LC    29.38
H-SC    22.14
X-MC    20.86
M-SC    10.11
X-SC     9.83
H-MC     2.58
M-MC     1.99
H-LC     1.29
M-LC     0.93
L-SC     0.54
L-MC     0.35
Name: CurrAlloc%, dtype: float64

In [28]:
# sector-wise stats
df_tmp = df_portfolio_features.groupby('Category')[['CurrAlloc%', 'Current', 'Current P/L', 'FTT Amt']].sum().sort_values(by=['Current', 'Current P/L'], ascending=False)
df_tmp['Current P/L%'] = round(df_tmp['Current P/L'] * 100 / df_tmp['Current'], 2)
df_tmp['FTT%'] = round(df_tmp['FTT Amt'] * 100 / df_tmp['Current'], 2)
cols = ['CurrAlloc%', 'Current P/L%', 'FTT%']
df_tmp[cols].sort_values(by=['CurrAlloc%'], ascending=False)

               CurrAlloc%  Current P/L%    FTT%
Category
FMCG                15.62        -13.55   53.61
FINANCE             10.78        -14.59   64.44
IT                  10.55        -43.07  115.11
MISC                 7.08        -27.09   82.30
AUTO                 6.58        -11.74   53.64
BANKS                5.67         -7.65   57.43
INSURANCE            5.30         -4.70   40.33
PAINTS               5.04        -31.10   53.87
PHARMA               4.73         -4.96   38.70
ELECTRICAL           4.08        -16.26   57.65
CHEMICALS            1.97        -37.81  119.93
HEALTHCARE           1.93        -23.76   56.06
AC                   1.93        -10.96   41.05
DURABLES             1.78        -46.00   81.52
TRAVEL               1.75        -71.74  157.73
APPARELS             1.73         -3.90   39.35
FOOTWEAR             1.72        -72.08  141.08
BREWERIES            1.51         -3.74   25.29
REALTY               1.38         -7.50   25.16
CABLES               1.35         26.46   52.89
CERAMICS             1.30        -58.49  106.64
ENGINEERING          1.29        -26.11   83.79
REFINERIES           1.27         -6.36   33.27
CEMENT               1.11        -61.41  182.16
JEWELLERY            1.05       -103.98  174.86
ENTERTAINMENT        0.74        -76.90  182.39
TEXTILES             0.43        -43.21   84.05
HOTELS               0.33       -131.92  213.73

In [29]:
# money to be made criteria-wise
df_portfolio_features.groupby('Criteria')['FTT Amt'].agg(['sum', 'count']).sort_values(by='sum', ascending=False)

                sum  count
Criteria
XY24      3541745.0     21
X40       1910916.0     19
XR        1325288.0     13
X40N      1212492.0     13
AR        1189371.0      9
OX40N      753666.0     10
XY25       399490.0      5
SR         295765.0      2

In [30]:
# money to be made conviction-wise
df_portfolio_features.groupby('Conviction')['FTT Amt'].agg(['sum', 'count']).sort_values(by='sum', ascending=False)

                  sum  count
Conviction
H-SC        3484977.0     24
X-LC        1916858.0     21
X-MC        1620371.0     15
M-SC        1411925.0     14
X-SC        1336693.0      9
H-MC         312771.0      2
L-SC         210564.0      2
M-LC         152838.0      1
M-MC          89658.0      2
L-MC          50621.0      1
H-LC          41457.0      1

In [31]:
# money to be made criteria and conviction-wise
df_portfolio_features.groupby(['Conviction', 'Criteria'])['FTT Amt'].agg(['sum', 'count']).sort_values(by='sum', ascending=False)

                           sum  count
Conviction Criteria
H-SC       XY24      1110092.0      6
X-LC       X40       1032610.0     10
H-SC       AR         948400.0      5
M-SC       XY24       844157.0      6
H-SC       XR         801994.0      7
X-SC       XY24       777800.0      4
X-MC       X40        674096.0      7
           X40N       485706.0      4
X-LC       X40N       372103.0      6
X-SC       X40N       354683.0      3
X-LC       XY24       345172.0      2
H-SC       OX40N      328726.0      4
M-SC       OX40N      319018.0      5
H-SC       SR         295765.0      2
X-MC       XY24       235571.0      2
H-MC       XY24       228953.0      1
X-MC       XY25       224998.0      2
X-SC       X40        204210.0      2
M-SC       XR         173040.0      2
M-LC       XR         152838.0      1
X-LC       XY25       124820.0      2
L-SC       OX40N      105922.0      1
           XR         104642.0      1
H-MC       AR          83818.0      1
M-SC       AR          75710.0      1
L-MC       XR          50621.0      1
M-MC       XY25        49672.0      1
X-LC       XR          42153.0      1
H-LC       AR          41457.0      1
M-MC       AR          39986.0      1

In [32]:
# notebook execution time

end_time = time.time()
execution_time = round(end_time - start_time, 0)
print(f"Notebook execution time: {execution_time} seconds")

Notebook execution time: 29.0 seconds