<a href="https://colab.research.google.com/github/ankit-rathi/Quantvesting_v2/blob/main/myStocks_Portfolio_Analysis.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
'''
!pip install pandas==2.2.2 -qq
!pip install pyxirr -qq
!pip install ta -qq
!pip install yfinance==0.2.59 -qq
'''

'\n!pip install pandas==2.2.2 -qq\n!pip install pyxirr -qq\n!pip install ta -qq\n!pip install yfinance==0.2.59 -qq\n'

In [2]:
# import libraries

import numpy as np
import pandas as pd
import datetime
import warnings
warnings.filterwarnings('ignore')
import yfinance as yfin
import ta
import matplotlib.pyplot as plt
import requests

In [3]:
# notebook start time
import time
import datetime
import pytz

start_time = time.time()

# function to print date timestamp
def print_date_time():
  tz_NY = pytz.timezone('Asia/Kolkata')
  datetime_NY = datetime.datetime.now(tz_NY)
  print("Run date time (IST):", datetime_NY.strftime("%Y-%m-%d %H:%M:%S"))

In [4]:
# function to get booked and reserved amount
def get_amt():
  # fetch the JSON data from the URL
  url = "https://raw.githubusercontent.com/ankit-rathi/Tradevesting_v1/main/data/myPortfolioAmts.json"
  response = requests.get(url)
  pf_amts = response.json()  # parse the JSON data

  # extract values from the JSON
  py_booked_amt_dm = pf_amts["py_booked_amt_dm"]
  py_booked_amt_sv = pf_amts["py_booked_amt_sv"]
  cy_booked_amt_dm = pf_amts["cy_booked_amt_dm"]
  cy_booked_amt_sv = pf_amts["cy_booked_amt_sv"]
  reserve_amt_dm = pf_amts["reserve_amt_dm"]
  reserve_amt_sv = pf_amts["reserve_amt_sv"]

  # perform calculations
  py_booked_amt = py_booked_amt_dm + py_booked_amt_sv
  cy_booked_amt = cy_booked_amt_dm + cy_booked_amt_sv
  reserve_amt = reserve_amt_dm + reserve_amt_sv
  total_booked_amt = py_booked_amt + cy_booked_amt

  return total_booked_amt, reserve_amt, cy_booked_amt, py_booked_amt

gen_output = 0

In [5]:
# function to format the amount
def format_amt(number):
    abs_number = abs(number)

    if abs_number >= 1_00_00_000:  # Crores
        formatted_amt = f"{number / 1_00_00_000:.2f} C"
    elif abs_number >= 1_00_000:  # Lakhs
        formatted_amt = f"{number / 1_00_000:.2f} L"
    elif abs_number >= 1_000:  # Thousands
        formatted_amt = f"{number / 1_000:.2f} K"
    else:
        formatted_amt = f"{number:.2f}"

    return formatted_amt

# function to set start and end date
def get_start_end_date():
  start_date = (datetime.date.today() + datetime.timedelta(days=-365)).strftime('%Y-%m-%d')
  end_date = (datetime.date.today() + datetime.timedelta(days=1)).strftime('%Y-%m-%d')
  return start_date, end_date

# function to fetch my portfolio csv
def get_mypfs_df():
  mypfs_df = pd.read_csv('https://raw.githubusercontent.com/ankit-rathi/Tradevesting_v1/main/data/myPortfolioStocks.csv')
  return mypfs_df

# function to fetch my prospects csv
def get_mypps_df():
  mypps_df = pd.read_csv('https://raw.githubusercontent.com/ankit-rathi/Tradevesting_v1/main/data/myProspectsScrips.csv')
  return mypps_df

# function to fetch screener data
def get_myscreen_df():
  myscreen_df = pd.read_csv('https://raw.githubusercontent.com/ankit-rathi/Tradevesting_v1/main/data/myScreenerDB.csv')
  return myscreen_df

# function to fetch momentum data
def get_myinvmt_df():
  myinvmt_df = pd.read_csv('https://raw.githubusercontent.com/ankit-rathi/Tradevesting_v1/main/data/myInvestments.csv')
  return myinvmt_df

# function to get the stock ids
def get_stock_ids(df_pf):
  stock_n100 = df_pf['Symbol'].unique()

  exclude = ['CADILAHC','MMTC', 'MASFIN']

  stock_ids = df_pf[~df_pf['Symbol'].isin(exclude) ]['Symbol'].unique()

  #mypf = mypf[mypf.Forecast.notnull()]
  #stock_ids = mypf['Symbol'].unique()

  #stock_ids.sort()
  return stock_ids

# get features from screener data
def get_screener_features():
  myscreen_df = get_myscreen_df()
  cols = ['Symbol', 'EPS', 'MedPE', 'ROCE%', 'ROE%', 'CapType']
  return myscreen_df[cols]

# get relative strength
def get_relative_strength(stock_list):

    # Dictionary to store stock tickers and their corresponding percentage price change
    stock_changes = {}

    # Loop through each stock and fetch its price data
    for stock in stock_list:
        try:
            # Download the stock data for the given date range
            stock_data = yfin.Ticker(stock + '.NS').history(period='1mo', interval='1d')[map(str.title, ['open', 'close', 'low', 'high', 'volume'])]

            # Calculate the percentage change for the stock
            if len(stock_data) > 0:
                start_price = stock_data['Close'].iloc[0]
                end_price = stock_data['Close'].iloc[-1]
                percent_change = round(((end_price - start_price) / start_price) * 100, 2)
                stock_changes[stock] = percent_change
            else:
                stock_changes[stock] = np.nan  # If no data is available, set to NaN

        except Exception as e:
            print(f"Error fetching data for {stock}: {e}")
            stock_changes[stock] = np.nan

    # Create a DataFrame with stock tickers and their percentage changes
    df = pd.DataFrame(list(stock_changes.items()), columns=['Symbol', 'Percent_Change'])

    # Drop any stocks with missing data (NaN values)
    df = df.dropna()

    # Calculate the percentile rank based on percentage change
    df['RSP'] = round(df['Percent_Change'].rank(pct=True) * 100, 2)
    cols = ['Symbol', 'RSP']
    df = df[cols]
    # Sort by percentile rank (optional)
    df = df.sort_values(by='RSP', ascending=False).reset_index(drop=True)

    return df

In [6]:
# function to get stock technicals
def stock_prec_dev(stock_symbol):
    #stock_symbol = 'ULTRACEMCO.NS'
    short_window = 20
    mid_window = 50
    long_window = 200
    moving_avg = 'SMA'

    start = datetime.datetime(*map(int, start_date.split('-')))
    end = datetime.datetime(*map(int, end_date.split('-')))

    stock_df = yfin.Ticker(stock_symbol + '.NS').history(period='max', interval='1d')[map(str.title, ['open', 'close', 'low', 'high', 'volume'])]

    stock_df['Max'] = round(max(stock_df['Close']),2)
    stock_df = stock_df[(stock_df.index <= end_date) & (stock_df.index >= start_date)]
    stock_df['200_SMA'] = round(stock_df['Close'].rolling(window = 200, min_periods = 1).mean(),0)
    stock_df['Dev%_200'] = round((stock_df['Close'] - stock_df['200_SMA'])*100/stock_df['200_SMA'],2)
    stock_df.dropna(axis = 0, inplace = True) # remove any null rows

    stock_df['20_SMA'] = stock_df['Close'].rolling(window=20).mean()
    stock_df['50_SMA'] = stock_df['Close'].rolling(window=50).mean()
    stock_df['Symbol'] = stock_symbol

    stock_df['Close'] = round(stock_df['Close'],2)
    stock_df['Min'] = round(min(stock_df['Close']),2)
    stock_df['RSI_14'] = ta.momentum.RSIIndicator(close=stock_df['Close'], window=14).rsi()
    stock_df['RSI_14'] = round(stock_df['RSI_14'],0)
    stock_df['Prev_Close'] = stock_df['Close'].shift(1)
    stock_df.drop(['Open', 'Low', 'High', 'Volume'], axis=1, inplace=True)
    stock_df = stock_df.tail(1)

    max_SMA = max(stock_df['20_SMA'].item(), stock_df['50_SMA'].item(), stock_df['200_SMA'].item())
    min_SMA = min(stock_df['20_SMA'].item(), stock_df['50_SMA'].item(), stock_df['200_SMA'].item())
    ABS_Spread = max_SMA - min_SMA
    stock_df['Spread%'] = round((ABS_Spread / stock_df['200_SMA'].item()) * 100,2)

    return stock_df

# function to compute stock attributes
def get_common_features(stock_ids, df_mypf):

  df_prec_dev = pd.DataFrame()
  df_tmp = get_screener_features()
  df_rs = get_relative_strength(stock_ids)

  for stock_id in stock_ids:
      tmp = stock_prec_dev(stock_id)
      tmp = tmp.reset_index()
      df_prec_dev = pd.concat([df_prec_dev, tmp], ignore_index = True)
  df_prec_dev = pd.merge(df_prec_dev, df_mypf, on= 'Symbol')
  df_prec_dev = pd.merge(df_prec_dev, df_tmp, on= 'Symbol', how='left')
  df_prec_dev = pd.merge(df_prec_dev, df_rs, on= 'Symbol', how='left')
  #print(df_prec_dev.columns)
  df_prec_dev['Curr_PE'] = round(df_prec_dev['Close']/df_prec_dev['EPS'],1)
  df_prec_dev['Dev%_PE'] = round((df_prec_dev['Curr_PE'] - df_prec_dev['MedPE'])*100/df_prec_dev['MedPE'],2)
  df_prec_dev['Conviction'] = df_prec_dev['Conviction'] + '-' + df_prec_dev['CapType']
  return df_prec_dev

# function to arrange stock features
def arrange_features(df_stocks, common_cols, diff_cols):
  df_stocks_common = df_stocks[common_cols].drop_duplicates()
  df_stocks_diff = df_stocks[diff_cols]
  df_stocks_diff['Investment'] = df_stocks_diff['AvgCost'] * df_stocks_diff['Shares']
  df_stocks_diff = df_stocks_diff.groupby(['Symbol'])[['Shares', 'Investment']].aggregate(['sum']).reset_index()
  df_stocks_diff.columns = ['Symbol', 'Shares', 'Investment']
  df_stocks_diff['AvgCost'] = round(df_stocks_diff['Investment']/df_stocks_diff['Shares'],2)
  df_stocks = pd.merge(df_stocks_diff, df_stocks_common, on='Symbol')
  return df_stocks

# plot fact distribution across dimension
def plot_pie_chart(df, dimension, fact):
  # grouping the data by category and calculating the sum of fact for each type
  grouped_data = df.groupby(dimension)[fact].sum()

  # sorting the grouped data in descending order
  grouped_data = grouped_data.sort_values(ascending=False)

  # creating a pie chart
  grouped_data.plot.pie(autopct='%1.1f%%', startangle=90, figsize=(6, 6))

  # adding a title and displaying the plot
  plt.title(f'{dimension} {fact} Distribution')
  plt.ylabel('')  # To hide the y-label
  plt.show()

In [7]:
# function to get portfolio features

def get_portfolio_features(df_common_features):

  print_date_time()
  print('-------------------')

  #df_common_features["Target"] = df_common_features["Target"].fillna(df_common_features["Max"])
  df_common_features['NTT'] = np.where(df_common_features['Strategy']== 'NTT', df_common_features["Target"], df_common_features['Max'])
  df_common_features['LTT'] = np.where(df_common_features['Strategy']== 'BTT', df_common_features["Target"], df_common_features['Max'])
  df_common_features['BOL'] = df_common_features['Min']

  tmp_df = df_common_features[df_common_features['Symbol'].isin(mypf_df[mypf_df['InPortfolio'] != 'NA'].Symbol.values)]
  print('qualified stocks: '+str(len(tmp_df['Symbol'].unique())))
  tmp_df1 = tmp_df[tmp_df['LatestQtr'] == 1]
  print('with latest results: '+str(len(tmp_df1['Symbol'].unique())))
  tmp_df1 = tmp_df1[tmp_df1['StarStock'] == 1]
  print('still star stocks: '+str(len(tmp_df1['Symbol'].unique())))
  tmp_df['Investment'] = tmp_df['AvgCost'] * tmp_df['Shares']
  tmp_df['Current'] = round(tmp_df['Close'] * tmp_df['Shares'],0)
  tmp_df['Previous'] = tmp_df['Prev_Close'] * tmp_df['Shares']
  tmp_df['EstimatedST'] = tmp_df['NTT'] * tmp_df['Shares']
  tmp_df['EstimatedLT'] = tmp_df['LTT'] * tmp_df['Shares']
  tmp_df['Current P/L'] = round((tmp_df['Current'] - tmp_df['Investment']),0)
  tmp_df['Today P/L%'] = round((tmp_df['Current'] - tmp_df['Previous'])*100/tmp_df['Previous'],2)
  tmp_df['Current P/L%'] = round((tmp_df['Current'] - tmp_df['Investment'])*100/tmp_df['Investment'],2)
  tmp_df['EstimatedST P/L%'] = round((tmp_df['EstimatedST'] - tmp_df['Investment'])*100/tmp_df['Investment'],2)
  tmp_df['EstimatedLT P/L%'] = round((tmp_df['EstimatedLT'] - tmp_df['Investment'])*100/tmp_df['Investment'],2)
  tmp_df['NTT%'] = round((tmp_df['NTT'] - tmp_df['Close'])*100/tmp_df['Close'],2)
  tmp_df['LTT%'] = round((tmp_df['LTT'] - tmp_df['Close'])*100/tmp_df['Close'],2)
  tmp_df['Gained%'] = round((tmp_df['Close'] - tmp_df['BOL'])*100/tmp_df['BOL'],2)
  investment = round(sum(tmp_df['AvgCost']*tmp_df['Shares']),0)
  current = round(sum(tmp_df['Close']*tmp_df['Shares']),0)
  tmp_df['InitAlloc%'] = round(tmp_df['Investment']*100/investment,2)
  tmp_df['CurrAlloc%'] = round(tmp_df['Current']*100/current,2)
  tmp_df['FTT'] = tmp_df['LTT']
  tmp_df.loc[tmp_df['Strategy'] == 'NTT', 'FTT'] = tmp_df['NTT']
  tmp_df['FTT%'] = tmp_df['LTT%']
  tmp_df.loc[tmp_df['Strategy'] == 'NTT', 'FTT%'] = tmp_df['NTT%']
  tmp_df['FTT Amt'] = round(tmp_df['FTT%'] * tmp_df['Current']/100,0)
  tmp_df['OTT%'] = round((tmp_df['FTT'] - tmp_df['AvgCost'])*100/tmp_df['AvgCost'],2)
  tmp_df['RRR Ind'] = round(tmp_df['Current P/L']/tmp_df['FTT Amt'],2)
  tmp_df['Risk Ind'] = round(tmp_df['Current P/L%']*tmp_df['CurrAlloc%'],0)

  return tmp_df

# function to print portfolio features
def print_portfolio_stats(df_portfolio_features, myinvmt_df):
  from pyxirr import xirr

  total_booked_amt, reserve_amt, cy_booked_amt, py_booked_amt = get_amt()

  dates = myinvmt_df['Date'].values
  dates = np.append(dates, datetime.date.today().strftime('%d-%b-%y'))
  investment = myinvmt_df['Investment'].values
  dates= pd.to_datetime(dates)

  current = round(sum(df_portfolio_features['Close']*df_portfolio_features['Shares']),0) + reserve_amt
  investment_xirr = np.append(investment, current)
  cagr = round(xirr(pd.DataFrame({"dates": dates, "amounts": investment_xirr}))*100,2)

  investment = -sum(investment)
  invested = round(sum(df_portfolio_features['AvgCost']*df_portfolio_features['Shares']),0) + reserve_amt
  previous = round(sum(df_portfolio_features['Prev_Close']*df_portfolio_features['Shares']),0) + reserve_amt
  cy_invested = investment + py_booked_amt

  today_pnl_amount = current-previous
  today_pnl_percentage = round((current-previous)*100/previous,2)

  curr_pnl_amount = current-invested
  curr_pnl_percentage = round((curr_pnl_amount)*100/(cy_invested),2)

  cy_pnl_amount = cy_booked_amt + curr_pnl_amount
  cy_pnl_percentage = round((cy_pnl_amount)*100/cy_invested,2)

  overall_pnl_amount = total_booked_amt + curr_pnl_amount
  overall_pnl_percentage = round((overall_pnl_amount)*100/investment,2)

  estimate_st = round(sum(df_portfolio_features['FTT']*df_portfolio_features['Shares']),0)  + reserve_amt
  est_st_pnl_amount = estimate_st-current
  est_st_pnl_percentage = round((est_st_pnl_amount)*100/current,2)

  estimate_lt = round(sum(df_portfolio_features['LTT']*df_portfolio_features['Shares']),0)  + reserve_amt
  est_lt_pnl_amount = estimate_lt-current
  est_lt_pnl_percentage = round((est_lt_pnl_amount)*100/current,2)

  total_profit = round(sum(df_portfolio_features[df_portfolio_features['Current P/L%'] > 0]['Current']) - sum(df_portfolio_features[df_portfolio_features['Current P/L%'] > 0]['Investment']),0)
  total_loss = round(sum(df_portfolio_features[df_portfolio_features['Current P/L%'] < 0]['Current']) - sum(df_portfolio_features[df_portfolio_features['Current P/L%'] < 0]['Investment']),0)

  cy_booked_percentage = round((cy_booked_amt)*100/current,2)
  py_booked_percentage = round((py_booked_amt)*100/investment,2)
  total_booked_percentage = round((total_booked_amt)*100/investment,2)

  print('-------------------')
  print('Initial Investment: ', format_amt(investment))
  print('CY Investment: ', format_amt(cy_invested))
  print('Reserve: ', format_amt(reserve_amt))
  print('Current: ',  format_amt(current))
  print('-------------------')
  print('Today PnL: '+ '{} ({}%)'.format(format_amt(today_pnl_amount), today_pnl_percentage))
  print('Current PnL: '+ '{} ({}%)'.format(format_amt(curr_pnl_amount), curr_pnl_percentage))
  print('CY Booked + Current PnL: '+ '{} ({}%)'.format(format_amt(cy_pnl_amount), cy_pnl_percentage))
  print('-------------------')
  print('Total profit: ', format_amt(total_profit))
  print('Total loss: ', format_amt(total_loss))
  print('-------------------')
  print('Total Booked + Current PnL: '+ '{} ({}%)'.format(format_amt(overall_pnl_amount), overall_pnl_percentage))
  print('Total Booked PnL: '+ '{} ({}%)'.format(format_amt(total_booked_amt), total_booked_percentage))
  print('Curr Year Booked PnL: '+ '{} ({}%)'.format(format_amt(cy_booked_amt), cy_booked_percentage))
  print('Prev Year Booked PnL: '+ '{} ({}%)'.format(format_amt(py_booked_amt), py_booked_percentage))
  print('===================')
  print('Est FTT: ',  format_amt(estimate_st))
  print('Est FTT PnL: '+ '{} ({}%)'.format(format_amt(est_st_pnl_amount), est_st_pnl_percentage))

  print('===================')
  print('Deployed: ', format_amt(investment))

  print('Current: ', format_amt(current))

  print('CAGR/XIRR %: '+'{}%'.format(cagr))

In [8]:
# get start and end date
start_date, end_date = get_start_end_date()

# get portfolio and prospects data
mypfs_df = get_mypfs_df()
mypps_df = get_mypps_df()
myinvmt_df = get_myinvmt_df()

# merge above datasets
mypf_df = pd.merge(mypfs_df, mypps_df, on="Symbol")

# seggregate dm and sv portfolio
dm_pf = mypf_df[mypf_df['InPortfolio'] == 'DM']
sv_pf = mypf_df[mypf_df['InPortfolio'] == 'SV']

# build portfolio stock dataframe
dm_stocks = get_stock_ids(dm_pf)
sv_stocks = get_stock_ids(sv_pf)
df_stocks = pd.concat([dm_pf,sv_pf], ignore_index = True)

# arrange common and diff stock features
common_cols = ['Symbol', 'Target', 'Criteria', 'Strategy', 'CumlRnk', 'LatestQtr', 'StarStock', 'Conviction', 'Category', 'InFolio', 'XIRR', 'MBQ']
diff_cols = ['Symbol', 'AvgCost', 'Shares']
df_stocks = arrange_features(df_stocks, common_cols, diff_cols)

# get common features
stock_ids = df_stocks['Symbol'].values
df_common_features = get_common_features(stock_ids, df_stocks)

df_common_features.reset_index(drop=True, inplace=True)
df_common_features.drop(['Date'], axis=1, inplace=True)
# get and print portfolio features
df_portfolio_features = get_portfolio_features(df_common_features)

print_portfolio_stats(df_portfolio_features, myinvmt_df)

df = df_portfolio_features
#plot_pie_chart(df, 'CapType', 'Current')
list_ox40n = list(df[df['MBQ'].str.contains('OX40N', na=False)]['Symbol'].values)

Run date time (IST): 2026-08-24 13:27:04
-------------------
qualified stocks: 87
with latest results: 30
still star stocks: 19
-------------------
Initial Investment:  1.46 C
CY Investment:  1.89 C
Reserve:  3.69 L
Current:  1.58 C
-------------------
Today PnL: -35.89 K (-0.23%)
Current PnL: -35.41 L (-18.74%)
CY Booked + Current PnL: -30.35 L (-16.07%)
-------------------
Total profit:  3.54 L
Total loss:  -38.96 L
-------------------
Total Booked + Current PnL: 12.52 L (8.57%)
Total Booked PnL: 47.93 L (32.82%)
Curr Year Booked PnL: 5.06 L (3.21%)
Prev Year Booked PnL: 42.87 L (29.35%)
===================
Est FTT:  2.67 C
Est FTT PnL: 1.10 C (69.54%)
===================
Deployed:  1.46 C
Current:  1.58 C
CAGR/XIRR %: 3.41%

In [9]:
# top 5 near their targets
cols = ['Symbol', 'Today P/L%', 'Current P/L%', 'FTT%', 'OTT%', 'FTT Amt', 'Current P/L', 'Current', 'FTT', 'Dev%_PE', 'RSI_14','Conviction', 'Spread%',  'CumlRnk', 'RRR Ind', 'CurrAlloc%', 'Gained%', 'Criteria', 'Strategy', 'Category']
df_tmp = df_portfolio_features[~df_portfolio_features['Symbol'].isin(['ENRIN','BLUSPRING','DIGITIDE'])]
df_tmp = df_tmp.sort_values(by = 'FTT Amt', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
66,SIEMENS,4.31,9.86,0.88,10.83,1799.0,18350.0,204445.0,4125.00,-10.89,69.0,H-LC,14.73,51.0,10.20,1.33,44.25,AR,NTT,ELECTRICAL
78,UNITDSPR,-0.37,13.88,6.04,20.77,16106.0,32508.0,266652.0,1644.00,-2.84,64.0,X-MC,12.14,64.0,2.02,1.73,28.18,X40N,NTT,BREWERIES
77,TTKPRESTIG,-1.16,-23.98,31.67,0.09,24262.0,-24168.0,76609.0,770.00,-7.57,40.0,M-SC,8.49,250.0,-1.00,0.50,37.89,OX40N,NTT,DURABLES
52,M&M,0.29,8.06,9.96,18.82,25903.0,19391.0,260072.0,3762.88,-6.96,58.0,X-LC,5.10,25.0,0.75,1.69,17.97,X40N,ATH,AUTO
67,SIS,0.78,-3.31,25.42,21.26,27290.0,-3677.0,107355.0,528.00,106.30,45.0,H-SC,20.08,168.0,-0.13,0.70,59.62,OX40N,NTT,MISC

In [10]:
# top 5 today
df_tmp = df_portfolio_features.sort_values(by = 'Today P/L%', ascending=False)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
66,SIEMENS,4.31,9.86,0.88,10.83,1799.0,18350.0,204445.0,4125.00,-10.89,69.0,H-LC,14.73,51.0,10.20,1.33,44.25,AR,NTT,ELECTRICAL
6,AWL,3.23,-33.12,149.74,67.02,356805.0,-118026.0,238283.0,485.00,-50.79,56.0,X-SC,8.19,81.0,-0.33,1.55,13.30,XY24,NTT,FMCG
25,FINCABLES,2.74,64.02,26.76,107.91,64803.0,94521.0,242165.0,1641.55,19.75,68.0,M-SC,23.65,220.0,1.46,1.57,82.19,OX40N,ATH,CABLES
71,TANLA,1.69,-34.44,231.38,117.25,410725.0,-93250.0,177511.0,1922.32,NaN,49.0,NaN,14.92,147.0,-0.23,1.15,55.41,AR,ATH,IT
74,TITAGARH,1.43,-19.44,80.92,45.74,157865.0,-47089.0,195088.0,1548.00,NaN,54.0,NaN,7.70,175.0,-0.30,1.27,48.85,XY24,NTT,ENGINEERING

In [11]:
# bottom 5 today
df_tmp = df_portfolio_features.sort_values(by = 'Today P/L%', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
80,VAIBHAVGBL,-3.19,-32.47,138.06,60.77,170409.0,-59344.0,123431.0,521.0,NaN,32.0,NaN,6.24,160.0,-0.35,0.80,26.38,XR,NTT,JEWELLERY
12,BOSCH-HCIL,-2.67,-26.42,35.90,-0.01,33759.0,-33770.0,94035.0,2282.0,732.03,63.0,M-SC,11.96,231.0,-1.00,0.61,60.06,OX40N,BTT,AC
62,REPCOHOME,-2.24,-24.29,150.71,89.82,326917.0,-69587.0,216918.0,880.0,NaN,32.0,NaN,5.35,161.0,-0.21,1.41,4.28,XY24,NTT,FINANCE
70,SYMPHONY,-2.18,-54.14,117.98,-0.03,92601.0,-92652.0,78489.0,1306.0,NaN,28.0,NaN,17.18,205.0,-1.00,0.51,0.00,OX40N,NTT,DURABLES
24,EASEMYTRIP,-2.08,-66.23,331.37,45.70,197891.0,-117096.0,59719.0,26.4,NaN,36.0,NaN,8.24,204.0,-0.59,0.39,4.62,XY24,NTT,TRAVEL

In [12]:
# top 5 to exit based on CumlRnk
df_tmp = df_portfolio_features[~df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])]
df_tmp = df_tmp[(df_tmp['Current P/L%'] > -1) & (df_tmp['Current P/L%'] < 1)].sort_values(by = 'CumlRnk', ascending=False)
df_tmp[cols].head()

Empty DataFrame
Columns: [Symbol, Today P/L%, Current P/L%, FTT%, OTT%, FTT Amt, Current P/L, Current, FTT, Dev%_PE, RSI_14, Conviction, Spread%, CumlRnk, RRR Ind, CurrAlloc%, Gained%, Criteria, Strategy, Category]
Index: []

In [13]:
# OX40N stocks to exit
df_tmp = df_portfolio_features[(df_portfolio_features['Symbol'].isin(list_ox40n))].sort_values(by = 'Current P/L%', ascending=False)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
25,FINCABLES,2.74,64.02,26.76,107.91,64803.0,94521.0,242165.0,1641.55,19.75,68.0,M-SC,23.65,220.0,1.46,1.57,82.19,OX40N,ATH,CABLES
67,SIS,0.78,-3.31,25.42,21.26,27290.0,-3677.0,107355.0,528.00,106.30,45.0,H-SC,20.08,168.0,-0.13,0.70,59.62,OX40N,NTT,MISC
43,INDIGOPNTS,-0.10,-18.27,22.37,0.02,31916.0,-31885.0,142674.0,1408.00,-22.11,61.0,M-SC,8.40,222.0,-1.00,0.93,61.87,OX40N,NTT,PAINTS
16,CERA,-0.56,-23.74,62.45,23.89,83775.0,-41755.0,134148.0,9475.00,NaN,41.0,NaN,12.93,153.0,-0.50,0.87,30.40,OX40N,NTT,CERAMICS
77,TTKPRESTIG,-1.16,-23.98,31.67,0.09,24262.0,-24168.0,76609.0,770.00,-7.57,40.0,M-SC,8.49,250.0,-1.00,0.50,37.89,OX40N,NTT,DURABLES

In [14]:
# top 5 to book for rotation
df_tmp = df_portfolio_features[(df_portfolio_features['Current P/L%'] > 20) ].sort_values(by = 'CumlRnk', ascending=False)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
25,FINCABLES,2.74,64.02,26.76,107.91,64803.0,94521.0,242165.0,1641.55,19.75,68.0,M-SC,23.65,220.0,1.46,1.57,82.19,OX40N,ATH,CABLES

In [15]:
# top 5 to monitor for exit
df_tmp = df_portfolio_features[~df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])]
df_tmp = df_tmp[(df_tmp['Current P/L%'] > 0) ].sort_values(by = 'Dev%_PE', ascending=False)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
25,FINCABLES,2.74,64.02,26.76,107.91,64803.0,94521.0,242165.0,1641.55,19.75,68.0,M-SC,23.65,220.0,1.46,1.57,82.19,OX40N,ATH,CABLES
68,STARHEALTH,-0.56,11.32,32.29,47.26,101047.0,31813.0,312936.0,761.00,-1.84,45.0,H-SC,15.60,173.0,0.31,2.03,35.31,XY24,NTT,INSURANCE

In [16]:
# top 5 to book for rotation from weak conviction
df_tmp = df_portfolio_features[~df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])]
df_tmp = df_tmp[~df_tmp['Criteria'].isin(['XY25','XY24','X40', 'X40N'])].sort_values(by = 'RRR Ind', ascending=False)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
25,FINCABLES,2.74,64.02,26.76,107.91,64803.0,94521.0,242165.0,1641.55,19.75,68.0,M-SC,23.65,220.0,1.46,1.57,82.19,OX40N,ATH,CABLES
3,ALKYLAMINE,0.65,-12.01,118.82,92.54,105557.0,-12125.0,88838.0,4520.85,NaN,67.0,NaN,16.26,142.0,-0.11,0.58,68.70,SR,ATH,CHEMICALS
67,SIS,0.78,-3.31,25.42,21.26,27290.0,-3677.0,107355.0,528.00,106.30,45.0,H-SC,20.08,168.0,-0.13,0.70,59.62,OX40N,NTT,MISC
42,INDIAMART,-0.05,-25.17,168.50,100.92,155515.0,-31042.0,92294.0,4675.60,NaN,37.0,NaN,13.47,140.0,-0.20,0.60,0.41,AR,ATH,MISC
71,TANLA,1.69,-34.44,231.38,117.25,410725.0,-93250.0,177511.0,1922.32,NaN,49.0,NaN,14.92,147.0,-0.23,1.15,55.41,AR,ATH,IT

In [17]:
# top 5 to accumulate based on lowest RSI_14
df_tmp = df_portfolio_features[df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])].sort_values(by = 'RSI_14', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
56,PGHH,-0.60,-39.00,116.42,32.01,151625.0,-83280.0,130240.0,17616.87,-55.19,24.0,X-SC,19.81,57.0,-0.55,0.85,0.00,X40,ATH,FMCG
19,COLPAL,-0.55,-28.67,96.07,39.86,180477.0,-75505.0,187860.0,3683.41,-13.63,31.0,X-MC,2.85,62.0,-0.42,1.22,6.26,XY25,ATH,FMCG
75,TMPV,-1.18,-25.26,90.99,42.75,282986.0,-105099.0,311008.0,600.00,-84.91,31.0,X-LC,4.32,4.0,-0.37,2.02,6.94,XY24,NTT,AUTO
55,PAGEIND,0.23,-7.25,43.24,32.85,107633.0,-19459.0,248920.0,50936.07,-31.08,31.0,X-MC,8.51,55.0,-0.18,1.62,18.86,X40,ATH,APPARELS
28,GODREJCP,-1.21,-16.15,58.51,32.90,122418.0,-40311.0,209226.0,1460.97,-17.72,32.0,X-MC,8.15,32.0,-0.33,1.36,1.85,X40N,ATH,FMCG

In [18]:
# top 5 to accumulate based on Spread and CumlRnk
df_tmp = df_portfolio_features[df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])]
df_tmp = df_tmp[(df_tmp['CumlRnk'] < 100)].sort_values(by = 'Spread%', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
50,KOTAKBANK,-0.76,5.06,13.19,18.92,33218.0,12140.0,251842.0,452.46,-11.03,58.0,X-LC,2.12,12.0,0.37,1.64,13.31,X40,ATH,BANKS
1,ABBOTINDIA,-0.71,-12.63,32.04,15.37,50069.0,-22585.0,156270.0,34390.26,-28.82,34.0,X-MC,2.54,58.0,-0.45,1.02,5.86,X40,ATH,PHARMA
23,DMART,0.34,-4.47,37.57,31.42,111903.0,-13938.0,297852.0,5391.45,-19.87,42.0,X-LC,2.54,14.0,-0.12,1.94,7.48,X40N,ATH,FMCG
19,COLPAL,-0.55,-28.67,96.07,39.86,180477.0,-75505.0,187860.0,3683.41,-13.63,31.0,X-MC,2.85,62.0,-0.42,1.22,6.26,XY25,ATH,FMCG
53,MARUTI,-0.30,-1.54,26.59,24.64,64729.0,-3806.0,243432.0,17120.06,-7.22,42.0,X-LC,3.82,33.0,-0.06,1.58,11.00,XR,ATH,AUTO

In [19]:
# top 5 to accumulate based on lowest Gained%
df_tmp = df_portfolio_features[df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])].sort_values(by = 'Gained%', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
20,DABUR,-0.95,-22.44,85.28,43.70,164079.0,-55668.0,192400.0,735.00,-33.05,32.0,X-MC,10.66,70.0,-0.34,1.25,0.00,XY24,BTT,FMCG
36,HINDUNILVR,-0.10,-16.26,45.16,21.56,127264.0,-54711.0,281806.0,2922.00,-42.35,37.0,X-LC,7.10,9.0,-0.43,1.83,0.00,XY25,NTT,FMCG
56,PGHH,-0.60,-39.00,116.42,32.01,151625.0,-83280.0,130240.0,17616.87,-55.19,24.0,X-SC,19.81,57.0,-0.55,0.85,0.00,X40,ATH,FMCG
47,ITC,-0.59,-26.12,68.78,24.70,201875.0,-103769.0,293509.0,452.00,-31.16,34.0,X-LC,10.78,1.0,-0.51,1.91,0.28,X40,NTT,FMCG
34,HDFCBANK,-0.12,-11.32,47.79,31.05,124219.0,-33194.0,259926.0,1073.00,-28.50,37.0,X-LC,12.67,26.0,-0.27,1.69,0.89,X40,BTT,BANKS

In [20]:
# top 5 to accumulate based on lowest CurrAlloc%
df_tmp = df_portfolio_features[df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])].sort_values(by = 'CurrAlloc%', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
56,PGHH,-0.60,-39.00,116.42,32.01,151625.0,-83280.0,130240.0,17616.87,-55.19,24.0,X-SC,19.81,57.0,-0.55,0.85,0.00,X40,ATH,FMCG
2,ACC,-0.54,-41.80,200.37,74.81,312673.0,-112080.0,156048.0,3906.00,-42.24,38.0,X-SC,11.36,85.0,-0.36,1.01,4.25,XY24,BTT,CEMENT
1,ABBOTINDIA,-0.71,-12.63,32.04,15.37,50069.0,-22585.0,156270.0,34390.26,-28.82,34.0,X-MC,2.54,58.0,-0.45,1.02,5.86,X40,ATH,PHARMA
40,ICICIPRULI,-1.08,-15.70,54.53,30.28,90564.0,-30924.0,166081.0,787.27,-45.99,53.0,X-MC,11.81,78.0,-0.34,1.08,10.65,X40,ATH,INSURANCE
39,ICICIGI,0.31,-14.08,38.37,18.89,65970.0,-28177.0,171932.0,2244.41,-14.33,42.0,X-MC,10.11,66.0,-0.43,1.12,2.43,X40,ATH,INSURANCE

In [21]:
# top 5 to accumulate based on CumlRnk
df_tmp = df_portfolio_features.sort_values(by = 'CumlRnk', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
47,ITC,-0.59,-26.12,68.78,24.70,201875.0,-103769.0,293509.0,452.00,-31.16,34.0,X-LC,10.78,1.0,-0.51,1.91,0.28,X40,NTT,FMCG
73,TCS,-0.25,-32.59,84.25,24.20,263098.0,-150990.0,312283.0,4230.71,-43.98,48.0,X-LC,13.44,2.0,-0.57,2.03,16.45,X40,ATH,IT
45,INFY,1.42,-19.07,73.45,40.38,223794.0,-71781.0,304689.0,1972.00,-40.47,51.0,X-LC,15.48,3.0,-0.32,1.98,15.39,X40,NTT,IT
75,TMPV,-1.18,-25.26,90.99,42.75,282986.0,-105099.0,311008.0,600.00,-84.91,31.0,X-LC,4.32,4.0,-0.37,2.02,6.94,XY24,NTT,AUTO
33,HCLTECH,1.28,-11.77,40.50,23.97,110595.0,-36412.0,273074.0,1853.42,-14.26,54.0,X-LC,10.02,8.0,-0.33,1.78,28.86,X40,ATH,IT

In [22]:
# top 5 for average up
df_tmp = df_portfolio_features[(df_portfolio_features['Dev%_200'] > 5)].sort_values(by = 'CurrAlloc%', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
44,INDUSINDBK,0.82,-25.15,77.53,32.89,44806.0,-19414.0,57792.0,1800.00,325.21,52.0,L-MC,11.96,258.0,-0.43,0.38,42.48,XR,NTT,BANKS
30,HAPPSTMNDS,-1.00,-45.06,233.23,83.08,164231.0,-57749.0,70416.0,1466.54,NaN,68.0,NaN,6.72,152.0,-0.35,0.46,31.89,AR,ATH,IT
3,ALKYLAMINE,0.65,-12.01,118.82,92.54,105557.0,-12125.0,88838.0,4520.85,NaN,67.0,NaN,16.26,142.0,-0.11,0.58,68.70,SR,ATH,CHEMICALS
12,BOSCH-HCIL,-2.67,-26.42,35.90,-0.01,33759.0,-33770.0,94035.0,2282.00,732.03,63.0,M-SC,11.96,231.0,-1.00,0.61,60.06,OX40N,BTT,AC
81,VALIANTORG,-0.89,-37.65,179.33,74.15,182917.0,-61605.0,102000.0,838.00,NaN,52.0,NaN,10.32,145.0,-0.34,0.66,51.79,XR,NTT,CHEMICALS

In [23]:
# top 5 RSP
df_tmp = df_portfolio_features.sort_values(by = 'RSP', ascending=False)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
25,FINCABLES,2.74,64.02,26.76,107.91,64803.0,94521.0,242165.0,1641.55,19.75,68.0,M-SC,23.65,220.0,1.46,1.57,82.19,OX40N,ATH,CABLES
12,BOSCH-HCIL,-2.67,-26.42,35.90,-0.01,33759.0,-33770.0,94035.0,2282.00,732.03,63.0,M-SC,11.96,231.0,-1.00,0.61,60.06,OX40N,BTT,AC
30,HAPPSTMNDS,-1.00,-45.06,233.23,83.08,164231.0,-57749.0,70416.0,1466.54,NaN,68.0,NaN,6.72,152.0,-0.35,0.46,31.89,AR,ATH,IT
27,GLAXO,1.31,18.03,14.97,35.69,35211.0,35924.0,235208.0,3380.16,-11.57,71.0,X-MC,12.25,56.0,1.02,1.53,39.79,X40,ATH,PHARMA
3,ALKYLAMINE,0.65,-12.01,118.82,92.54,105557.0,-12125.0,88838.0,4520.85,NaN,67.0,NaN,16.26,142.0,-0.11,0.58,68.70,SR,ATH,CHEMICALS

In [24]:
# Top N allocation
df_tmp = df_portfolio_features.sort_values(by = 'CurrAlloc%', ascending=False)
top_n_values = [10, 25, 50]

sum_df = pd.DataFrame({
    'Top_N': top_n_values,
    'Sum_Alloc%': [df_tmp['CurrAlloc%'].head(n).sum() for n in top_n_values]
})

sum_df

   Top_N  Sum_Alloc%
0     10       19.62
1     25       44.96
2     50       77.66

In [25]:
# market-cap-wise allocation
df_tmp = df_portfolio_features[cols]
df_tmp.groupby(df_tmp['Conviction'].str[-2:])['CurrAlloc%'].sum().sort_values(ascending=False)

Conviction
LC    38.12
MC    22.14
SC    21.66
Name: CurrAlloc%, dtype: float64

In [26]:
# criteria-wise allocation
df_portfolio_features.groupby('Criteria')['CurrAlloc%'].sum().sort_values(ascending=False)

Criteria
X40      26.75
XY24     23.96
X40N     18.68
XR        9.11
OX40N     7.30
XY25      7.14
AR        6.19
SR        0.90
Name: CurrAlloc%, dtype: float64

In [27]:
# conviction-wise allocation
df_portfolio_features.groupby('Conviction')['CurrAlloc%'].sum().sort_values(ascending=False)

Conviction
X-LC    34.37
X-MC    19.58
H-SC     8.56
X-SC     7.68
M-SC     5.42
H-LC     2.92
M-MC     1.16
H-MC     1.02
M-LC     0.83
L-MC     0.38
Name: CurrAlloc%, dtype: float64

In [28]:
# sector-wise stats
df_tmp = df_portfolio_features.groupby('Category')[['CurrAlloc%', 'Current', 'Current P/L', 'FTT Amt']].sum().sort_values(by=['Current', 'Current P/L'], ascending=False)
df_tmp['Current P/L%'] = round(df_tmp['Current P/L'] * 100 / df_tmp['Current'], 2)
df_tmp['FTT%'] = round(df_tmp['FTT Amt'] * 100 / df_tmp['Current'], 2)
cols = ['CurrAlloc%', 'Current P/L%', 'FTT%']
df_tmp[cols].sort_values(by=['CurrAlloc%'], ascending=False)

               CurrAlloc%  Current P/L%    FTT%
Category
FMCG                15.33        -26.48   71.84
IT                  11.31        -37.09  105.08
FINANCE             10.64        -17.98   68.80
AUTO                 8.23         -6.72   44.95
BANKS                6.30        -10.35   57.94
MISC                 5.96        -34.81   89.04
PHARMA               5.85          7.67   18.51
INSURANCE            5.77         -4.57   41.55
PAINTS               5.45        -17.46   37.49
ELECTRICAL           4.25         -8.29   42.20
AC                   1.81        -14.63   45.71
BREWERIES            1.73         12.19    6.04
REFINERIES           1.73        -11.90   49.49
FOOTWEAR             1.68        -70.64  139.06
APPARELS             1.62         -7.82   43.24
CABLES               1.57         39.03   26.76
DURABLES             1.47        -71.47  113.18
TRAVEL               1.41       -106.03  209.20
CERAMICS             1.30        -52.75   99.16
ENGINEERING          1.27        -24.14   80.92
CHEMICALS            1.24        -38.63  151.16
CEMENT               1.01        -71.82  200.37
JEWELLERY            0.93       -122.02  199.16
ENTERTAINMENT        0.72        -76.71  182.10
HEALTHCARE           0.70        -69.17  111.64
TEXTILES             0.39        -52.89   96.48
HOTELS               0.36       -104.28  176.34

In [29]:
# money to be made criteria-wise
df_portfolio_features.groupby('Criteria')['FTT Amt'].agg(['sum', 'count']).sort_values(by='sum', ascending=False)

                sum  count
Criteria
XY24      3640629.0     19
X40       2108771.0     18
XR        1396327.0     13
X40N      1207093.0     12
AR        1055518.0      8
OX40N      668931.0     10
XY25       600120.0      5
SR         277008.0      2

In [30]:
# money to be made conviction-wise
df_portfolio_features.groupby('Conviction')['FTT Amt'].agg(['sum', 'count']).sort_values(by='sum', ascending=False)

                  sum  count
Conviction
X-LC        2440065.0     19
X-MC        1490440.0     14
X-SC        1094809.0      6
H-SC         834594.0      8
M-SC         330767.0      6
H-MC         256299.0      1
M-LC         164717.0      1
M-MC          66872.0      1
L-MC          44806.0      1
H-LC          41854.0      2

In [31]:
# money to be made criteria and conviction-wise
df_portfolio_features.groupby(['Conviction', 'Criteria'])['FTT Amt'].agg(['sum', 'count']).sort_values(by='sum', ascending=False)

                           sum  count
Conviction Criteria
X-LC       X40       1220511.0      9
X-SC       XY24       669478.0      2
H-SC       XY24       525856.0      3
X-MC       X40        516553.0      6
X-LC       XY24       468804.0      2
X-MC       X40N       458904.0      4
X-LC       X40N       426924.0      5
X-MC       XY25       274151.0      2
X-LC       XY25       259097.0      2
H-MC       XY24       256299.0      1
X-SC       X40        254890.0      2
X-MC       XY24       240832.0      2
H-SC       OX40N      221222.0      3
X-SC       X40N       170441.0      2
M-LC       XR         164717.0      1
M-SC       OX40N      154740.0      4
           XY24       117809.0      1
H-SC       XR          87516.0      2
M-MC       XY25        66872.0      1
X-LC       XR          64729.0      1
M-SC       XR          58218.0      1
L-MC       XR          44806.0      1
H-LC       AR          41854.0      2

In [32]:
# notebook execution time

end_time = time.time()
execution_time = round(end_time - start_time, 0)
print(f"Notebook execution time: {execution_time} seconds")

Notebook execution time: 30.0 seconds