<a href="https://colab.research.google.com/github/ankit-rathi/Quantvesting_v2/blob/main/myStocks_Portfolio_Analysis.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
'''
!pip install pandas==2.2.2 -qq
!pip install pyxirr -qq
!pip install ta -qq
!pip install yfinance==0.2.59 -qq
'''

'\n!pip install pandas==2.2.2 -qq\n!pip install pyxirr -qq\n!pip install ta -qq\n!pip install yfinance==0.2.59 -qq\n'

In [2]:
# import libraries

import numpy as np
import pandas as pd
import datetime
import warnings
warnings.filterwarnings('ignore')
import yfinance as yfin
import ta
import matplotlib.pyplot as plt
import requests

In [3]:
# notebook start time
import time
import datetime
import pytz

start_time = time.time()

# function to print date timestamp
def print_date_time():
  tz_NY = pytz.timezone('Asia/Kolkata')
  datetime_NY = datetime.datetime.now(tz_NY)
  print("Run date time (IST):", datetime_NY.strftime("%Y-%m-%d %H:%M:%S"))

In [4]:
# function to get booked and reserved amount
def get_amt():
  # fetch the JSON data from the URL
  url = "https://raw.githubusercontent.com/ankit-rathi/Tradevesting_v1/main/data/myPortfolioAmts.json"
  response = requests.get(url)
  pf_amts = response.json()  # parse the JSON data

  # extract values from the JSON
  py_booked_amt_dm = pf_amts["py_booked_amt_dm"]
  py_booked_amt_sv = pf_amts["py_booked_amt_sv"]
  cy_booked_amt_dm = pf_amts["cy_booked_amt_dm"]
  cy_booked_amt_sv = pf_amts["cy_booked_amt_sv"]
  reserve_amt_dm = pf_amts["reserve_amt_dm"]
  reserve_amt_sv = pf_amts["reserve_amt_sv"]

  # perform calculations
  py_booked_amt = py_booked_amt_dm + py_booked_amt_sv
  cy_booked_amt = cy_booked_amt_dm + cy_booked_amt_sv
  reserve_amt = reserve_amt_dm + reserve_amt_sv
  total_booked_amt = py_booked_amt + cy_booked_amt

  return total_booked_amt, reserve_amt, cy_booked_amt, py_booked_amt

gen_output = 0

In [5]:
# function to format the amount
def format_amt(number):
    abs_number = abs(number)

    if abs_number >= 1_00_00_000:  # Crores
        formatted_amt = f"{number / 1_00_00_000:.2f} C"
    elif abs_number >= 1_00_000:  # Lakhs
        formatted_amt = f"{number / 1_00_000:.2f} L"
    elif abs_number >= 1_000:  # Thousands
        formatted_amt = f"{number / 1_000:.2f} K"
    else:
        formatted_amt = f"{number:.2f}"

    return formatted_amt

# function to set start and end date
def get_start_end_date():
  start_date = (datetime.date.today() + datetime.timedelta(days=-365)).strftime('%Y-%m-%d')
  end_date = (datetime.date.today() + datetime.timedelta(days=1)).strftime('%Y-%m-%d')
  return start_date, end_date

# function to fetch my portfolio csv
def get_mypfs_df():
  mypfs_df = pd.read_csv('https://raw.githubusercontent.com/ankit-rathi/Tradevesting_v1/main/data/myPortfolioStocks.csv')
  return mypfs_df

# function to fetch my prospects csv
def get_mypps_df():
  mypps_df = pd.read_csv('https://raw.githubusercontent.com/ankit-rathi/Tradevesting_v1/main/data/myProspectsScrips.csv')
  return mypps_df

# function to fetch screener data
def get_myscreen_df():
  myscreen_df = pd.read_csv('https://raw.githubusercontent.com/ankit-rathi/Tradevesting_v1/main/data/myScreenerDB.csv')
  return myscreen_df

# function to fetch momentum data
def get_myinvmt_df():
  myinvmt_df = pd.read_csv('https://raw.githubusercontent.com/ankit-rathi/Tradevesting_v1/main/data/myInvestments.csv')
  return myinvmt_df

# function to get the stock ids
def get_stock_ids(df_pf):
  stock_n100 = df_pf['Symbol'].unique()

  exclude = ['CADILAHC','MMTC', 'MASFIN']

  stock_ids = df_pf[~df_pf['Symbol'].isin(exclude) ]['Symbol'].unique()

  #mypf = mypf[mypf.Forecast.notnull()]
  #stock_ids = mypf['Symbol'].unique()

  #stock_ids.sort()
  return stock_ids

# get features from screener data
def get_screener_features():
  myscreen_df = get_myscreen_df()
  cols = ['Symbol', 'EPS', 'MedPE', 'ROCE%', 'ROE%', 'CapType']
  return myscreen_df[cols]

# get relative strength
def get_relative_strength(stock_list):

    # Dictionary to store stock tickers and their corresponding percentage price change
    stock_changes = {}

    # Loop through each stock and fetch its price data
    for stock in stock_list:
        try:
            # Download the stock data for the given date range
            stock_data = yfin.Ticker(stock + '.NS').history(period='1mo', interval='1d')[map(str.title, ['open', 'close', 'low', 'high', 'volume'])]

            # Calculate the percentage change for the stock
            if len(stock_data) > 0:
                start_price = stock_data['Close'].iloc[0]
                end_price = stock_data['Close'].iloc[-1]
                percent_change = round(((end_price - start_price) / start_price) * 100, 2)
                stock_changes[stock] = percent_change
            else:
                stock_changes[stock] = np.nan  # If no data is available, set to NaN

        except Exception as e:
            print(f"Error fetching data for {stock}: {e}")
            stock_changes[stock] = np.nan

    # Create a DataFrame with stock tickers and their percentage changes
    df = pd.DataFrame(list(stock_changes.items()), columns=['Symbol', 'Percent_Change'])

    # Drop any stocks with missing data (NaN values)
    df = df.dropna()

    # Calculate the percentile rank based on percentage change
    df['RSP'] = round(df['Percent_Change'].rank(pct=True) * 100, 2)
    cols = ['Symbol', 'RSP']
    df = df[cols]
    # Sort by percentile rank (optional)
    df = df.sort_values(by='RSP', ascending=False).reset_index(drop=True)

    return df

In [6]:
# function to get stock technicals
def stock_prec_dev(stock_symbol):
    #stock_symbol = 'ULTRACEMCO.NS'
    short_window = 20
    mid_window = 50
    long_window = 200
    moving_avg = 'SMA'

    start = datetime.datetime(*map(int, start_date.split('-')))
    end = datetime.datetime(*map(int, end_date.split('-')))

    stock_df = yfin.Ticker(stock_symbol + '.NS').history(period='max', interval='1d')[map(str.title, ['open', 'close', 'low', 'high', 'volume'])]

    stock_df['Max'] = round(max(stock_df['Close']),2)
    stock_df = stock_df[(stock_df.index <= end_date) & (stock_df.index >= start_date)]
    stock_df['200_SMA'] = round(stock_df['Close'].rolling(window = 200, min_periods = 1).mean(),0)
    stock_df['Dev%_200'] = round((stock_df['Close'] - stock_df['200_SMA'])*100/stock_df['200_SMA'],2)
    stock_df.dropna(axis = 0, inplace = True) # remove any null rows

    stock_df['20_SMA'] = stock_df['Close'].rolling(window=20).mean()
    stock_df['50_SMA'] = stock_df['Close'].rolling(window=50).mean()
    stock_df['Symbol'] = stock_symbol

    stock_df['Close'] = round(stock_df['Close'],2)
    stock_df['Min'] = round(min(stock_df['Close']),2)
    stock_df['RSI_14'] = ta.momentum.RSIIndicator(close=stock_df['Close'], window=14).rsi()
    stock_df['RSI_14'] = round(stock_df['RSI_14'],0)
    stock_df['Prev_Close'] = stock_df['Close'].shift(1)
    stock_df.drop(['Open', 'Low', 'High', 'Volume'], axis=1, inplace=True)
    stock_df = stock_df.tail(1)

    max_SMA = max(stock_df['20_SMA'].item(), stock_df['50_SMA'].item(), stock_df['200_SMA'].item())
    min_SMA = min(stock_df['20_SMA'].item(), stock_df['50_SMA'].item(), stock_df['200_SMA'].item())
    ABS_Spread = max_SMA - min_SMA
    stock_df['Spread%'] = round((ABS_Spread / stock_df['200_SMA'].item()) * 100,2)

    return stock_df

# function to compute stock attributes
def get_common_features(stock_ids, df_mypf):

  df_prec_dev = pd.DataFrame()
  df_tmp = get_screener_features()
  df_rs = get_relative_strength(stock_ids)

  for stock_id in stock_ids:
      tmp = stock_prec_dev(stock_id)
      tmp = tmp.reset_index()
      df_prec_dev = pd.concat([df_prec_dev, tmp], ignore_index = True)
  df_prec_dev = pd.merge(df_prec_dev, df_mypf, on= 'Symbol')
  df_prec_dev = pd.merge(df_prec_dev, df_tmp, on= 'Symbol', how='left')
  df_prec_dev = pd.merge(df_prec_dev, df_rs, on= 'Symbol', how='left')
  #print(df_prec_dev.columns)
  df_prec_dev['Curr_PE'] = round(df_prec_dev['Close']/df_prec_dev['EPS'],1)
  df_prec_dev['Dev%_PE'] = round((df_prec_dev['Curr_PE'] - df_prec_dev['MedPE'])*100/df_prec_dev['MedPE'],2)
  df_prec_dev['Conviction'] = df_prec_dev['Conviction'] + '-' + df_prec_dev['CapType']
  return df_prec_dev

# function to arrange stock features
def arrange_features(df_stocks, common_cols, diff_cols):
  df_stocks_common = df_stocks[common_cols].drop_duplicates()
  df_stocks_diff = df_stocks[diff_cols]
  df_stocks_diff['Investment'] = df_stocks_diff['AvgCost'] * df_stocks_diff['Shares']
  df_stocks_diff = df_stocks_diff.groupby(['Symbol'])[['Shares', 'Investment']].aggregate(['sum']).reset_index()
  df_stocks_diff.columns = ['Symbol', 'Shares', 'Investment']
  df_stocks_diff['AvgCost'] = round(df_stocks_diff['Investment']/df_stocks_diff['Shares'],2)
  df_stocks = pd.merge(df_stocks_diff, df_stocks_common, on='Symbol')
  return df_stocks

# plot fact distribution across dimension
def plot_pie_chart(df, dimension, fact):
  # grouping the data by category and calculating the sum of fact for each type
  grouped_data = df.groupby(dimension)[fact].sum()

  # sorting the grouped data in descending order
  grouped_data = grouped_data.sort_values(ascending=False)

  # creating a pie chart
  grouped_data.plot.pie(autopct='%1.1f%%', startangle=90, figsize=(6, 6))

  # adding a title and displaying the plot
  plt.title(f'{dimension} {fact} Distribution')
  plt.ylabel('')  # To hide the y-label
  plt.show()

In [7]:
# function to get portfolio features

def get_portfolio_features(df_common_features):

  print_date_time()
  print('-------------------')

  #df_common_features["Target"] = df_common_features["Target"].fillna(df_common_features["Max"])
  df_common_features['NTT'] = np.where(df_common_features['Strategy']== 'NTT', df_common_features["Target"], df_common_features['Max'])
  df_common_features['LTT'] = np.where(df_common_features['Strategy']== 'BTT', df_common_features["Target"], df_common_features['Max'])
  df_common_features['BOL'] = df_common_features['Min']

  tmp_df = df_common_features[df_common_features['Symbol'].isin(mypf_df[mypf_df['InPortfolio'] != 'NA'].Symbol.values)]
  print('qualified stocks: '+str(len(tmp_df['Symbol'].unique())))
  tmp_df1 = tmp_df[tmp_df['LatestQtr'] == 1]
  print('with latest results: '+str(len(tmp_df1['Symbol'].unique())))
  tmp_df1 = tmp_df1[tmp_df1['StarStock'] == 1]
  print('still star stocks: '+str(len(tmp_df1['Symbol'].unique())))
  tmp_df['Investment'] = tmp_df['AvgCost'] * tmp_df['Shares']
  tmp_df['Current'] = round(tmp_df['Close'] * tmp_df['Shares'],0)
  tmp_df['Previous'] = tmp_df['Prev_Close'] * tmp_df['Shares']
  tmp_df['EstimatedST'] = tmp_df['NTT'] * tmp_df['Shares']
  tmp_df['EstimatedLT'] = tmp_df['LTT'] * tmp_df['Shares']
  tmp_df['Current P/L'] = round((tmp_df['Current'] - tmp_df['Investment']),0)
  tmp_df['Today P/L%'] = round((tmp_df['Current'] - tmp_df['Previous'])*100/tmp_df['Previous'],2)
  tmp_df['Current P/L%'] = round((tmp_df['Current'] - tmp_df['Investment'])*100/tmp_df['Investment'],2)
  tmp_df['EstimatedST P/L%'] = round((tmp_df['EstimatedST'] - tmp_df['Investment'])*100/tmp_df['Investment'],2)
  tmp_df['EstimatedLT P/L%'] = round((tmp_df['EstimatedLT'] - tmp_df['Investment'])*100/tmp_df['Investment'],2)
  tmp_df['NTT%'] = round((tmp_df['NTT'] - tmp_df['Close'])*100/tmp_df['Close'],2)
  tmp_df['LTT%'] = round((tmp_df['LTT'] - tmp_df['Close'])*100/tmp_df['Close'],2)
  tmp_df['Gained%'] = round((tmp_df['Close'] - tmp_df['BOL'])*100/tmp_df['BOL'],2)
  investment = round(sum(tmp_df['AvgCost']*tmp_df['Shares']),0)
  current = round(sum(tmp_df['Close']*tmp_df['Shares']),0)
  tmp_df['InitAlloc%'] = round(tmp_df['Investment']*100/investment,2)
  tmp_df['CurrAlloc%'] = round(tmp_df['Current']*100/current,2)
  tmp_df['FTT'] = tmp_df['LTT']
  tmp_df.loc[tmp_df['Strategy'] == 'NTT', 'FTT'] = tmp_df['NTT']
  tmp_df['FTT%'] = tmp_df['LTT%']
  tmp_df.loc[tmp_df['Strategy'] == 'NTT', 'FTT%'] = tmp_df['NTT%']
  tmp_df['FTT Amt'] = round(tmp_df['FTT%'] * tmp_df['Current']/100,0)
  tmp_df['OTT%'] = round((tmp_df['FTT'] - tmp_df['AvgCost'])*100/tmp_df['AvgCost'],2)
  tmp_df['RRR Ind'] = round(tmp_df['Current P/L']/tmp_df['FTT Amt'],2)
  tmp_df['Risk Ind'] = round(tmp_df['Current P/L%']*tmp_df['CurrAlloc%'],0)

  return tmp_df

# function to print portfolio features
def print_portfolio_stats(df_portfolio_features, myinvmt_df):
  from pyxirr import xirr

  total_booked_amt, reserve_amt, cy_booked_amt, py_booked_amt = get_amt()

  dates = myinvmt_df['Date'].values
  dates = np.append(dates, datetime.date.today().strftime('%d-%b-%y'))
  investment = myinvmt_df['Investment'].values
  dates= pd.to_datetime(dates)

  current = round(sum(df_portfolio_features['Close']*df_portfolio_features['Shares']),0) + reserve_amt
  investment_xirr = np.append(investment, current)
  cagr = round(xirr(pd.DataFrame({"dates": dates, "amounts": investment_xirr}))*100,2)

  investment = -sum(investment)
  invested = round(sum(df_portfolio_features['AvgCost']*df_portfolio_features['Shares']),0) + reserve_amt
  previous = round(sum(df_portfolio_features['Prev_Close']*df_portfolio_features['Shares']),0) + reserve_amt
  cy_invested = investment + py_booked_amt

  today_pnl_amount = current-previous
  today_pnl_percentage = round((current-previous)*100/previous,2)

  curr_pnl_amount = current-invested
  curr_pnl_percentage = round((curr_pnl_amount)*100/(cy_invested),2)

  cy_pnl_amount = cy_booked_amt + curr_pnl_amount
  cy_pnl_percentage = round((cy_pnl_amount)*100/cy_invested,2)

  overall_pnl_amount = total_booked_amt + curr_pnl_amount
  overall_pnl_percentage = round((overall_pnl_amount)*100/investment,2)

  estimate_st = round(sum(df_portfolio_features['FTT']*df_portfolio_features['Shares']),0)  + reserve_amt
  est_st_pnl_amount = estimate_st-current
  est_st_pnl_percentage = round((est_st_pnl_amount)*100/current,2)

  estimate_lt = round(sum(df_portfolio_features['LTT']*df_portfolio_features['Shares']),0)  + reserve_amt
  est_lt_pnl_amount = estimate_lt-current
  est_lt_pnl_percentage = round((est_lt_pnl_amount)*100/current,2)

  total_profit = round(sum(df_portfolio_features[df_portfolio_features['Current P/L%'] > 0]['Current']) - sum(df_portfolio_features[df_portfolio_features['Current P/L%'] > 0]['Investment']),0)
  total_loss = round(sum(df_portfolio_features[df_portfolio_features['Current P/L%'] < 0]['Current']) - sum(df_portfolio_features[df_portfolio_features['Current P/L%'] < 0]['Investment']),0)

  cy_booked_percentage = round((cy_booked_amt)*100/current,2)
  py_booked_percentage = round((py_booked_amt)*100/investment,2)
  total_booked_percentage = round((total_booked_amt)*100/investment,2)

  print('-------------------')
  print('Initial Investment: ', format_amt(investment))
  print('CY Investment: ', format_amt(cy_invested))
  print('Reserve: ', format_amt(reserve_amt))
  print('Current: ',  format_amt(current))
  print('-------------------')
  print('Today PnL: '+ '{} ({}%)'.format(format_amt(today_pnl_amount), today_pnl_percentage))
  print('Current PnL: '+ '{} ({}%)'.format(format_amt(curr_pnl_amount), curr_pnl_percentage))
  print('CY Booked + Current PnL: '+ '{} ({}%)'.format(format_amt(cy_pnl_amount), cy_pnl_percentage))
  print('-------------------')
  print('Total profit: ', format_amt(total_profit))
  print('Total loss: ', format_amt(total_loss))
  print('-------------------')
  print('Total Booked + Current PnL: '+ '{} ({}%)'.format(format_amt(overall_pnl_amount), overall_pnl_percentage))
  print('Total Booked PnL: '+ '{} ({}%)'.format(format_amt(total_booked_amt), total_booked_percentage))
  print('Curr Year Booked PnL: '+ '{} ({}%)'.format(format_amt(cy_booked_amt), cy_booked_percentage))
  print('Prev Year Booked PnL: '+ '{} ({}%)'.format(format_amt(py_booked_amt), py_booked_percentage))
  print('===================')
  print('Est FTT: ',  format_amt(estimate_st))
  print('Est FTT PnL: '+ '{} ({}%)'.format(format_amt(est_st_pnl_amount), est_st_pnl_percentage))

  print('===================')
  print('Deployed: ', format_amt(investment))

  print('Current: ', format_amt(current))

  print('CAGR/XIRR %: '+'{}%'.format(cagr))

In [8]:
# get start and end date
start_date, end_date = get_start_end_date()

# get portfolio and prospects data
mypfs_df = get_mypfs_df()
mypps_df = get_mypps_df()
myinvmt_df = get_myinvmt_df()

# merge above datasets
mypf_df = pd.merge(mypfs_df, mypps_df, on="Symbol")

# seggregate dm and sv portfolio
dm_pf = mypf_df[mypf_df['InPortfolio'] == 'DM']
sv_pf = mypf_df[mypf_df['InPortfolio'] == 'SV']

# build portfolio stock dataframe
dm_stocks = get_stock_ids(dm_pf)
sv_stocks = get_stock_ids(sv_pf)
df_stocks = pd.concat([dm_pf,sv_pf], ignore_index = True)

# arrange common and diff stock features
common_cols = ['Symbol', 'Target', 'Criteria', 'Strategy', 'CumlRnk', 'LatestQtr', 'StarStock', 'Conviction', 'Category', 'InFolio', 'XIRR', 'MBQ']
diff_cols = ['Symbol', 'AvgCost', 'Shares']
df_stocks = arrange_features(df_stocks, common_cols, diff_cols)

# get common features
stock_ids = df_stocks['Symbol'].values
df_common_features = get_common_features(stock_ids, df_stocks)

df_common_features.reset_index(drop=True, inplace=True)
df_common_features.drop(['Date'], axis=1, inplace=True)
# get and print portfolio features
df_portfolio_features = get_portfolio_features(df_common_features)

print_portfolio_stats(df_portfolio_features, myinvmt_df)

df = df_portfolio_features
#plot_pie_chart(df, 'CapType', 'Current')
list_ox40n = list(df[df['MBQ'].str.contains('OX40N', na=False)]['Symbol'].values)

Run date time (IST): 2026-04-17 10:19:22
-------------------
qualified stocks: 86
with latest results: 26
still star stocks: 16

-------------------
Initial Investment:  1.36 C
CY Investment:  1.62 C
Reserve:  1.61 K
Current:  1.44 C
-------------------
Today PnL: 1.75 L (1.23%)
Current PnL: -33.21 L (-20.44%)
CY Booked + Current PnL: -17.32 L (-10.66%)
-------------------
Total profit:  2.20 L
Total loss:  -35.41 L
-------------------
Total Booked + Current PnL: 9.66 L (7.13%)
Total Booked PnL: 42.87 L (31.64%)
Curr Year Booked PnL: 15.89 L (11.04%)
Prev Year Booked PnL: 26.98 L (19.91%)
===================
Est FTT:  2.48 C
Est FTT PnL: 1.04 C (72.25%)
===================
Deployed:  1.36 C
Current:  1.44 C
CAGR/XIRR %: 2.91%

In [9]:
# top 5 near their targets
cols = ['Symbol', 'Today P/L%', 'Current P/L%', 'FTT%', 'OTT%', 'FTT Amt', 'Current P/L', 'Current', 'FTT', 'Dev%_PE', 'RSI_14','Conviction', 'Spread%',  'CumlRnk', 'RRR Ind', 'CurrAlloc%', 'Gained%', 'Criteria', 'Strategy', 'Category']
df_tmp = df_portfolio_features[~df_portfolio_features['Symbol'].isin(['ENRIN','BLUSPRING','DIGITIDE'])]
df_tmp = df_tmp.sort_values(by = 'FTT Amt', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
5,ANGELONE,2.82,23.30,0.71,24.18,2670.0,71075.0,376075.0,303.00,-82.34,74.0,X-SC,1.94,97.0,26.62,2.61,43.88,X40N,NTT,FINANCE
50,MASFIN,-0.41,-3.12,25.49,21.57,24195.0,-3060.0,94920.0,397.04,-16.44,57.0,H-SC,3.85,167.0,-0.13,0.66,22.66,XR,ATH,FINANCE
77,TTKPRESTIG,1.04,-36.69,58.11,0.09,37072.0,-36980.0,63797.0,770.00,48.13,52.0,M-SC,23.40,250.0,-1.00,0.44,13.60,OX40N,NTT,DURABLES
67,SONACOMS,1.23,1.72,36.74,39.09,37805.0,1741.0,102900.0,804.02,-19.39,69.0,M-MC,9.15,193.0,0.05,0.72,45.57,AR,ATH,AUTO
37,ICICIGI,0.23,0.17,19.13,19.34,38347.0,348.0,200457.0,2252.93,-15.67,65.0,X-MC,7.31,66.0,0.01,1.39,11.96,X40,ATH,INSURANCE

In [10]:
# top 5 today
df_tmp = df_portfolio_features.sort_values(by = 'Today P/L%', ascending=False)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
20,COLPAL,6.60,-19.96,76.80,41.51,161887.0,-52575.0,210790.0,3726.84,-3.16,65.0,X-MC,12.80,62.0,-0.32,1.46,17.85,XY25,ATH,FMCG
78,UNITDSPR,3.40,-4.71,26.73,20.77,59639.0,-11026.0,223118.0,1644.00,-15.56,52.0,X-MC,6.41,64.0,-0.18,1.55,6.43,X40N,NTT,BREWERIES
65,SIEMENS,3.34,-1.05,26.84,25.51,49425.0,-1950.0,184145.0,4671.50,54.62,71.0,H-LC,1.79,51.0,-0.04,1.28,31.06,AR,ATH,ELECTRICAL
35,HINDUNILVR,3.26,-14.07,32.28,13.67,71303.0,-36173.0,220890.0,2922.00,-36.16,57.0,X-LC,11.80,9.0,-0.51,1.54,7.64,XY25,NTT,FMCG
5,ANGELONE,2.82,23.30,0.71,24.18,2670.0,71075.0,376075.0,303.00,-82.34,74.0,X-SC,1.94,97.0,26.62,2.61,43.88,X40N,NTT,FINANCE

In [11]:
# bottom 5 today
df_tmp = df_portfolio_features.sort_values(by = 'Today P/L%', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
84,WIPRO,-2.79,-16.16,105.48,72.27,149843.0,-27390.0,142058.0,420.00,-24.55,53.0,M-LC,16.25,98.0,-0.18,0.99,8.99,XR,NTT,IT
51,MEDANTA,-1.38,-7.86,37.96,27.12,61742.0,-13867.0,162650.0,1486.00,-10.75,55.0,X-SC,15.97,87.0,-0.22,1.13,12.07,XY24,NTT,HEALTHCARE
69,SURYODAY,-0.70,-18.65,51.24,23.03,74644.0,-33395.0,145676.0,216.00,57.89,62.0,H-SC,3.99,166.0,-0.45,1.01,24.23,XR,NTT,BANKS
33,HCLTECH,-0.66,-6.50,32.45,23.83,73399.0,-15734.0,226190.0,1908.19,-1.57,56.0,X-LC,8.13,8.0,-0.21,1.57,9.83,X40,ATH,IT
42,INDUSINDBK,-0.53,-37.73,113.42,32.89,54526.0,-29132.0,48074.0,1800.00,-326.19,52.0,L-MC,7.53,258.0,-0.53,0.33,18.33,XR,NTT,BANKS

In [12]:
# top 5 to exit based on CumlRnk
df_tmp = df_portfolio_features[~df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])]
df_tmp = df_tmp[(df_tmp['Current P/L%'] > -1) & (df_tmp['Current P/L%'] < 1)].sort_values(by = 'CumlRnk', ascending=False)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
57,RECLTD,1.65,0.22,20.48,20.74,41699.0,440.0,203610.0,446.00,11.33,66.0,M-MC,6.09,191.0,0.01,1.42,21.34,XY25,NTT,FINANCE
85,ZYDUSLIFE,0.60,-0.38,36.15,35.63,75474.0,-795.0,208779.0,1286.17,-13.51,65.0,H-MC,5.43,120.0,-0.01,1.45,14.91,AR,ATH,PHARMA

In [13]:
# OX40N stocks to exit
df_tmp = df_portfolio_features[(df_portfolio_features['Symbol'].isin(list_ox40n))].sort_values(by = 'Current P/L%', ascending=False)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
26,FINCABLES,1.70,17.68,76.68,107.91,133225.0,26098.0,173742.0,1641.55,6.04,65.0,M-SC,2.37,220.0,0.20,1.21,30.71,OX40N,ATH,CABLES
66,SIS,1.50,-25.50,62.76,21.26,51916.0,-28310.0,82722.0,528.00,1949.74,70.0,H-SC,12.08,168.0,-0.55,0.57,23.00,OX40N,NTT,MISC
18,CERA,1.21,-30.24,77.60,23.89,95218.0,-53200.0,122703.0,9475.00,-32.70,68.0,H-SC,14.60,153.0,-0.56,0.85,17.92,OX40N,NTT,CERAMICS
48,KANSAINER,1.08,-32.47,68.04,13.47,123899.0,-87570.0,182097.0,340.00,-42.07,64.0,H-SC,21.82,162.0,-0.71,1.27,27.20,XY24,NTT,PAINTS
72,TATAELXSI,1.45,-32.84,96.59,32.03,85521.0,-43295.0,88540.0,9161.00,-15.99,62.0,H-SC,19.31,158.0,-0.51,0.62,17.19,OX40N,NTT,IT

In [14]:
# top 5 to book for rotation
df_tmp = df_portfolio_features[(df_portfolio_features['Current P/L%'] > 20) ].sort_values(by = 'CumlRnk', ascending=False)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
1,ABB,2.57,29.54,12.37,45.57,41922.0,77285.0,338904.0,7934.0,-16.77,74.0,H-MC,17.06,125.0,1.84,2.36,50.50,AR,NTT,ELECTRICAL
5,ANGELONE,2.82,23.30,0.71,24.18,2670.0,71075.0,376075.0,303.0,-82.34,74.0,X-SC,1.94,97.0,26.62,2.61,43.88,X40N,NTT,FINANCE

In [15]:
# top 5 to monitor for exit
df_tmp = df_portfolio_features[~df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])]
df_tmp = df_tmp[(df_tmp['Current P/L%'] > 0) ].sort_values(by = 'Dev%_PE', ascending=False)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
57,RECLTD,1.65,0.22,20.48,20.74,41699.0,440.0,203610.0,446.00,11.33,66.0,M-MC,6.09,191.0,0.01,1.42,21.34,XY25,NTT,FINANCE
26,FINCABLES,1.70,17.68,76.68,107.91,133225.0,26098.0,173742.0,1641.55,6.04,65.0,M-SC,2.37,220.0,0.20,1.21,30.71,OX40N,ATH,CABLES
1,ABB,2.57,29.54,12.37,45.57,41922.0,77285.0,338904.0,7934.00,-16.77,74.0,H-MC,17.06,125.0,1.84,2.36,50.50,AR,NTT,ELECTRICAL
67,SONACOMS,1.23,1.72,36.74,39.09,37805.0,1741.0,102900.0,804.02,-19.39,69.0,M-MC,9.15,193.0,0.05,0.72,45.57,AR,ATH,AUTO

In [16]:
# top 5 to book for rotation from weak conviction
df_tmp = df_portfolio_features[~df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])]
df_tmp = df_tmp[~df_tmp['Criteria'].isin(['XY25','XY24','X40', 'X40N'])].sort_values(by = 'RRR Ind', ascending=False)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
1,ABB,2.57,29.54,12.37,45.57,41922.0,77285.0,338904.0,7934.00,-16.77,74.0,H-MC,17.06,125.0,1.84,2.36,50.50,AR,NTT,ELECTRICAL
26,FINCABLES,1.70,17.68,76.68,107.91,133225.0,26098.0,173742.0,1641.55,6.04,65.0,M-SC,2.37,220.0,0.20,1.21,30.71,OX40N,ATH,CABLES
67,SONACOMS,1.23,1.72,36.74,39.09,37805.0,1741.0,102900.0,804.02,-19.39,69.0,M-MC,9.15,193.0,0.05,0.72,45.57,AR,ATH,AUTO
85,ZYDUSLIFE,0.60,-0.38,36.15,35.63,75474.0,-795.0,208779.0,1286.17,-13.51,65.0,H-MC,5.43,120.0,-0.01,1.45,14.91,AR,ATH,PHARMA
40,INDIAMART,0.97,-6.46,121.01,106.72,139603.0,-7971.0,115365.0,4810.62,-57.81,62.0,H-SC,12.49,140.0,-0.06,0.80,10.84,AR,ATH,MISC

In [17]:
# top 5 to accumulate based on lowest RSI_14
df_tmp = df_portfolio_features[df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])].sort_values(by = 'RSI_14', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
2,ABBOTINDIA,-0.33,-13.53,36.55,18.07,56525.0,-24205.0,154650.0,35195.00,-26.49,43.0,X-MC,11.74,58.0,-0.43,1.07,1.14,X40,ATH,PHARMA
38,ICICIPRULI,-0.43,-8.07,42.20,30.73,76428.0,-15896.0,181109.0,790.00,-32.72,47.0,X-MC,12.55,78.0,-0.21,1.26,10.36,X40,ATH,INSURANCE
53,PGHH,1.30,-25.13,76.33,32.01,122018.0,-53664.0,159856.0,17616.87,-49.41,47.0,X-MC,21.59,57.0,-0.44,1.11,9.33,X40,ATH,FMCG
59,RELIANCE,0.52,-13.32,44.56,25.30,77619.0,-26774.0,174189.0,1952.00,-15.42,47.0,X-LC,5.48,21.0,-0.34,1.21,6.37,XY25,BTT,REFINERIES
34,HDFCBANK,0.72,-4.15,33.92,28.37,76366.0,-9748.0,225137.0,1073.00,-18.56,48.0,X-LC,17.24,26.0,-0.13,1.56,9.52,X40,BTT,BANKS

In [18]:
# top 5 to accumulate based on Spread and CumlRnk
df_tmp = df_portfolio_features[df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])]
df_tmp = df_tmp[(df_tmp['CumlRnk'] < 100)].sort_values(by = 'Spread%', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
65,SIEMENS,3.34,-1.05,26.84,25.51,49425.0,-1950.0,184145.0,4671.50,54.62,71.0,H-LC,1.79,51.0,-0.04,1.28,31.06,AR,ATH,ELECTRICAL
5,ANGELONE,2.82,23.30,0.71,24.18,2670.0,71075.0,376075.0,303.00,-82.34,74.0,X-SC,1.94,97.0,26.62,2.61,43.88,X40N,NTT,FINANCE
24,DMART,2.25,8.85,19.07,29.60,51809.0,22080.0,271680.0,5391.45,-8.18,69.0,X-LC,4.03,14.0,0.43,1.89,24.18,X40N,ATH,FMCG
59,RELIANCE,0.52,-13.32,44.56,25.30,77619.0,-26774.0,174189.0,1952.00,-15.42,47.0,X-LC,5.48,21.0,-0.34,1.21,6.37,XY25,BTT,REFINERIES
78,UNITDSPR,3.40,-4.71,26.73,20.77,59639.0,-11026.0,223118.0,1644.00,-15.56,52.0,X-MC,6.41,64.0,-0.18,1.55,6.43,X40N,NTT,BREWERIES

In [19]:
# top 5 to accumulate based on lowest Gained%
df_tmp = df_portfolio_features[df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])].sort_values(by = 'Gained%', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
2,ABBOTINDIA,-0.33,-13.53,36.55,18.07,56525.0,-24205.0,154650.0,35195.0,-26.49,43.0,X-MC,11.74,58.0,-0.43,1.07,1.14,X40,ATH,PHARMA
59,RELIANCE,0.52,-13.32,44.56,25.30,77619.0,-26774.0,174189.0,1952.0,-15.42,47.0,X-LC,5.48,21.0,-0.34,1.21,6.37,XY25,BTT,REFINERIES
78,UNITDSPR,3.40,-4.71,26.73,20.77,59639.0,-11026.0,223118.0,1644.0,-15.56,52.0,X-MC,6.41,64.0,-0.18,1.55,6.43,X40N,NTT,BREWERIES
21,DABUR,2.55,-14.28,67.64,43.70,143835.0,-35420.0,212648.0,735.0,-22.24,48.0,X-MC,14.75,70.0,-0.25,1.48,6.82,XY24,BTT,FMCG
8,AWL,1.33,-36.46,162.84,67.02,368680.0,-129903.0,226406.0,485.0,-65.82,52.0,X-SC,24.06,81.0,-0.35,1.57,7.09,XY24,NTT,FMCG

In [20]:
# top 5 to accumulate based on lowest CurrAlloc%
df_tmp = df_portfolio_features[df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])].sort_values(by = 'CurrAlloc%', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
58,RELAXO,1.74,-59.88,279.65,52.31,162854.0,-86925.0,58235.0,1176.00,-57.31,59.0,X-SC,32.46,92.0,-0.53,0.40,30.21,X40N,NTT,FOOTWEAR
12,BATAINDIA,1.57,-51.08,176.41,35.20,111031.0,-65731.0,62939.0,2096.00,-17.55,62.0,X-SC,32.69,91.0,-0.59,0.44,24.82,X40,NTT,FOOTWEAR
54,QUESS,1.65,-18.23,112.66,73.90,98384.0,-19465.0,87328.0,424.00,-55.92,63.0,X-SC,20.34,80.0,-0.20,0.61,17.48,XY24,NTT,MISC
2,ABBOTINDIA,-0.33,-13.53,36.55,18.07,56525.0,-24205.0,154650.0,35195.00,-26.49,43.0,X-MC,11.74,58.0,-0.43,1.07,1.14,X40,ATH,PHARMA
53,PGHH,1.30,-25.13,76.33,32.01,122018.0,-53664.0,159856.0,17616.87,-49.41,47.0,X-MC,21.59,57.0,-0.44,1.11,9.33,X40,ATH,FMCG

In [21]:
# top 5 to accumulate based on CumlRnk
df_tmp = df_portfolio_features.sort_values(by = 'CumlRnk', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
45,ITC,1.65,-18.77,46.56,19.06,128657.0,-63840.0,276326.0,452.00,-55.52,56.0,X-LC,19.37,1.0,-0.50,1.92,7.19,X40,NTT,FMCG
73,TCS,0.13,-24.25,67.10,26.57,235459.0,-112366.0,350907.0,4311.59,-35.76,56.0,X-LC,16.95,2.0,-0.48,2.44,9.52,X40,ATH,IT
43,INFY,-0.30,-10.47,49.94,34.24,139901.0,-32750.0,280138.0,1972.00,-29.61,51.0,X-LC,13.40,3.0,-0.23,1.95,7.73,X40,NTT,IT
75,TMPV,1.01,-18.08,66.71,36.58,194472.0,-64322.0,291519.0,600.00,-82.53,64.0,X-LC,10.61,4.0,-0.33,2.03,21.51,XY24,NTT,AUTO
33,HCLTECH,-0.66,-6.50,32.45,23.83,73399.0,-15734.0,226190.0,1908.19,-1.57,56.0,X-LC,8.13,8.0,-0.21,1.57,9.83,X40,ATH,IT

In [22]:
# top 5 for average up
df_tmp = df_portfolio_features[(df_portfolio_features['Dev%_200'] > 5)].sort_values(by = 'CurrAlloc%', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
67,SONACOMS,1.23,1.72,36.74,39.09,37805.0,1741.0,102900.0,804.02,-19.39,69.0,M-MC,9.15,193.0,0.05,0.72,45.57,AR,ATH,AUTO
69,SURYODAY,-0.70,-18.65,51.24,23.03,74644.0,-33395.0,145676.0,216.00,57.89,62.0,H-SC,3.99,166.0,-0.45,1.01,24.23,XR,NTT,BANKS
26,FINCABLES,1.70,17.68,76.68,107.91,133225.0,26098.0,173742.0,1641.55,6.04,65.0,M-SC,2.37,220.0,0.20,1.21,30.71,OX40N,ATH,CABLES
65,SIEMENS,3.34,-1.05,26.84,25.51,49425.0,-1950.0,184145.0,4671.50,54.62,71.0,H-LC,1.79,51.0,-0.04,1.28,31.06,AR,ATH,ELECTRICAL
11,BANDHANBNK,0.14,-16.09,129.32,92.42,302267.0,-44823.0,233736.0,400.00,100.43,60.0,H-SC,4.87,174.0,-0.15,1.62,28.76,XY24,NTT,BANKS

In [23]:
# top 5 RSP
df_tmp = df_portfolio_features.sort_values(by = 'RSP', ascending=False)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
80,VALIANTORG,1.54,-39.30,186.91,74.15,185615.0,-64298.0,99307.0,838.00,-278.42,68.0,H-SC,19.29,145.0,-0.35,0.69,47.78,XR,NTT,CHEMICALS
5,ANGELONE,2.82,23.30,0.71,24.18,2670.0,71075.0,376075.0,303.00,-82.34,74.0,X-SC,1.94,97.0,26.62,2.61,43.88,X40N,NTT,FINANCE
55,RAJESHEXPO,1.45,-75.10,301.86,0.07,103109.0,-103019.0,34158.0,518.00,1152.53,65.0,L-SC,42.39,268.0,-1.00,0.24,60.36,OX40N,NTT,JEWELLERY
52,PAGEIND,2.80,-0.85,35.26,34.11,93829.0,-2274.0,266105.0,51418.63,-28.90,77.0,X-MC,15.39,55.0,-0.02,1.85,25.88,X40,ATH,APPARELS
71,TANLA,1.51,-44.06,292.75,119.69,443385.0,-119306.0,151455.0,1943.92,-43.33,65.0,H-SC,23.48,147.0,-0.27,1.05,31.13,AR,ATH,IT

In [24]:
# Top N allocation
df_tmp = df_portfolio_features.sort_values(by = 'CurrAlloc%', ascending=False)
top_n_values = [10, 25, 50]

sum_df = pd.DataFrame({
    'Top_N': top_n_values,
    'Sum_Alloc%': [df_tmp['CurrAlloc%'].head(n).sum() for n in top_n_values]
})

sum_df

   Top_N  Sum_Alloc%
0     10       21.10
1     25       45.71
2     50       77.70

In [25]:
# market-cap-wise allocation
df_tmp = df_portfolio_features[cols]
df_tmp.groupby(df_tmp['Conviction'].str[-2:])['CurrAlloc%'].sum().sort_values(ascending=False)

Conviction
SC    45.33
MC    29.55
LC    25.12
Name: CurrAlloc%, dtype: float64

In [26]:
# criteria-wise allocation
df_portfolio_features.groupby('Criteria')['CurrAlloc%'].sum().sort_values(ascending=False)

Criteria
XY24     27.12
X40      24.47
X40N     15.88
AR        9.39
XR        8.40
XY25      7.10
OX40N     6.85
SR        0.79
Name: CurrAlloc%, dtype: float64

In [27]:
# conviction-wise allocation
df_portfolio_features.groupby('Conviction')['CurrAlloc%'].sum().sort_values(ascending=False)

Conviction
X-LC    22.85
H-SC    22.14
X-MC    21.98
X-SC    12.45
M-SC    10.12
H-MC     5.10
M-MC     2.14
H-LC     1.28
M-LC     0.99
L-SC     0.62
L-MC     0.33
Name: CurrAlloc%, dtype: float64

In [28]:
# sector-wise stats
df_tmp = df_portfolio_features.groupby('Category')[['CurrAlloc%', 'Current', 'Current P/L', 'FTT Amt']].sum().sort_values(by=['Current', 'Current P/L'], ascending=False)
df_tmp['Current P/L%'] = round(df_tmp['Current P/L'] * 100 / df_tmp['Current'], 2)
df_tmp['FTT%'] = round(df_tmp['FTT Amt'] * 100 / df_tmp['Current'], 2)
cols = ['CurrAlloc%', 'Current P/L%', 'FTT%']
df_tmp[cols].sort_values(by=['CurrAlloc%'], ascending=False)

               CurrAlloc%  Current P/L%    FTT%
Category
FMCG                14.72        -17.95   59.80
FINANCE             13.52        -10.44   55.44
IT                  11.60        -35.08  103.82
MISC                 7.18        -29.71   86.05
ELECTRICAL           6.69         -0.76   39.33
PAINTS               5.31        -29.02   51.42
INSURANCE            4.53         -4.03   39.63
BANKS                4.52        -17.94   77.81
PHARMA               3.89         -4.97   38.02
AUTO                 3.85        -18.28   65.20
AC                   1.99        -11.13   41.27
HEALTHCARE           1.91        -30.06   64.00
APPARELS             1.85         -0.85   35.26
FOOTWEAR             1.83        -67.28  134.35
TRAVEL               1.83        -69.91  154.99
DURABLES             1.73        -54.87   92.54
BREWERIES            1.55         -4.94   26.73
REALTY               1.45         -6.59   24.11
CERAMICS             1.35        -58.18  106.24
REFINERIES           1.21        -15.37   44.56
CABLES               1.21         15.02   76.68
CEMENT               1.20        -55.17  171.25
ENGINEERING          1.19        -41.29  105.91
JEWELLERY            1.13        -97.93  166.70
CHEMICALS            1.12        -63.78  197.40
ENTERTAINMENT        0.81        -65.67  164.48
TEXTILES             0.45        -42.72   83.42
HOTELS               0.38       -109.27  183.09

In [29]:
# money to be made criteria-wise
df_portfolio_features.groupby('Criteria')['FTT Amt'].agg(['sum', 'count']).sort_values(by='sum', ascending=False)

                sum  count
Criteria
XY24      3692751.0     21
X40       1653619.0     16
XR        1281610.0     12
AR        1223234.0     10
X40N      1016070.0     10
OX40N      805521.0     10
XY25       418683.0      5
SR         305304.0      2

In [30]:
# money to be made conviction-wise
df_portfolio_features.groupby('Conviction')['FTT Amt'].agg(['sum', 'count']).sort_values(by='sum', ascending=False)

                  sum  count
Conviction
H-SC        3605585.0     24
X-MC        1570529.0     15
X-LC        1488902.0     13
M-SC        1459227.0     14
X-SC        1390718.0     10
H-MC         346081.0      3
L-SC         202452.0      2
M-LC         149843.0      1
M-MC          79504.0      2
L-MC          54526.0      1
H-LC          49425.0      1

In [31]:
# money to be made criteria and conviction-wise
df_portfolio_features.groupby(['Conviction', 'Criteria'])['FTT Amt'].agg(['sum', 'count']).sort_values(by='sum', ascending=False)

                           sum  count
Conviction Criteria
H-SC       XY24      1214568.0      6
           AR         945614.0      5
M-SC       XY24       846022.0      6
X-LC       X40        825045.0      7
X-SC       XY24       824726.0      4
H-SC       XR         794216.0      7
X-MC       X40        625471.0      7
           X40N       475170.0      4
X-SC       X40N       362889.0      4
M-SC       OX40N      356529.0      5
H-SC       OX40N      345883.0      4
X-LC       XY24       336924.0      2
H-SC       SR         305304.0      2
X-MC       XY24       241826.0      2
H-MC       XY24       228685.0      1
X-MC       XY25       228062.0      2
X-SC       X40        203103.0      2
M-SC       XR         183682.0      2
X-LC       X40N       178011.0      2
M-LC       XR         149843.0      1
X-LC       XY25       148922.0      2
H-MC       AR         117396.0      2
L-SC       OX40N      103109.0      1
           XR          99343.0      1
M-SC       AR          72994.0      1
L-MC       XR          54526.0      1
H-LC       AR          49425.0      1
M-MC       XY25        41699.0      1
           AR          37805.0      1

In [32]:
# notebook execution time

end_time = time.time()
execution_time = round(end_time - start_time, 0)
print(f"Notebook execution time: {execution_time} seconds")

Notebook execution time: 35.0 seconds