<a href="https://colab.research.google.com/github/ankit-rathi/Quantvesting_v2/blob/main/myStocks_Portfolio_Analysis.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
'''
!pip install pandas==2.2.2 -qq
!pip install pyxirr -qq
!pip install ta -qq
!pip install yfinance==0.2.59 -qq
'''

'\n!pip install pandas==2.2.2 -qq\n!pip install pyxirr -qq\n!pip install ta -qq\n!pip install yfinance==0.2.59 -qq\n'

In [2]:
# import libraries

import numpy as np
import pandas as pd
import datetime
import warnings
warnings.filterwarnings('ignore')
import yfinance as yfin
import ta
import matplotlib.pyplot as plt
import requests

In [3]:
# notebook start time
import time
import datetime
import pytz

start_time = time.time()

# function to print date timestamp
def print_date_time():
  tz_NY = pytz.timezone('Asia/Kolkata')
  datetime_NY = datetime.datetime.now(tz_NY)
  print("Run date time (IST):", datetime_NY.strftime("%Y-%m-%d %H:%M:%S"))

In [4]:
# function to get booked and reserved amount
def get_amt():
  # fetch the JSON data from the URL
  url = "https://raw.githubusercontent.com/ankit-rathi/Tradevesting_v1/main/data/myPortfolioAmts.json"
  response = requests.get(url)
  pf_amts = response.json()  # parse the JSON data

  # extract values from the JSON
  py_booked_amt_dm = pf_amts["py_booked_amt_dm"]
  py_booked_amt_sv = pf_amts["py_booked_amt_sv"]
  cy_booked_amt_dm = pf_amts["cy_booked_amt_dm"]
  cy_booked_amt_sv = pf_amts["cy_booked_amt_sv"]
  reserve_amt_dm = pf_amts["reserve_amt_dm"]
  reserve_amt_sv = pf_amts["reserve_amt_sv"]

  # perform calculations
  py_booked_amt = py_booked_amt_dm + py_booked_amt_sv
  cy_booked_amt = cy_booked_amt_dm + cy_booked_amt_sv
  reserve_amt = reserve_amt_dm + reserve_amt_sv
  total_booked_amt = py_booked_amt + cy_booked_amt

  return total_booked_amt, reserve_amt, cy_booked_amt, py_booked_amt

gen_output = 0

In [5]:
# function to format the amount
def format_amt(number):
    abs_number = abs(number)

    if abs_number >= 1_00_00_000:  # Crores
        formatted_amt = f"{number / 1_00_00_000:.2f} C"
    elif abs_number >= 1_00_000:  # Lakhs
        formatted_amt = f"{number / 1_00_000:.2f} L"
    elif abs_number >= 1_000:  # Thousands
        formatted_amt = f"{number / 1_000:.2f} K"
    else:
        formatted_amt = f"{number:.2f}"

    return formatted_amt

# function to set start and end date
def get_start_end_date():
  start_date = (datetime.date.today() + datetime.timedelta(days=-365)).strftime('%Y-%m-%d')
  end_date = (datetime.date.today() + datetime.timedelta(days=1)).strftime('%Y-%m-%d')
  return start_date, end_date

# function to fetch my portfolio csv
def get_mypfs_df():
  mypfs_df = pd.read_csv('https://raw.githubusercontent.com/ankit-rathi/Tradevesting_v1/main/data/myPortfolioStocks.csv')
  return mypfs_df

# function to fetch my prospects csv
def get_mypps_df():
  mypps_df = pd.read_csv('https://raw.githubusercontent.com/ankit-rathi/Tradevesting_v1/main/data/myProspectsScrips.csv')
  return mypps_df

# function to fetch screener data
def get_myscreen_df():
  myscreen_df = pd.read_csv('https://raw.githubusercontent.com/ankit-rathi/Tradevesting_v1/main/data/myScreenerDB.csv')
  return myscreen_df

# function to fetch momentum data
def get_myinvmt_df():
  myinvmt_df = pd.read_csv('https://raw.githubusercontent.com/ankit-rathi/Tradevesting_v1/main/data/myInvestments.csv')
  return myinvmt_df

# function to get the stock ids
def get_stock_ids(df_pf):
  stock_n100 = df_pf['Symbol'].unique()

  exclude = ['CADILAHC','MMTC', 'MASFIN']

  stock_ids = df_pf[~df_pf['Symbol'].isin(exclude) ]['Symbol'].unique()

  #mypf = mypf[mypf.Forecast.notnull()]
  #stock_ids = mypf['Symbol'].unique()

  #stock_ids.sort()
  return stock_ids

# get features from screener data
def get_screener_features():
  myscreen_df = get_myscreen_df()
  cols = ['Symbol', 'EPS', 'MedPE', 'ROCE%', 'ROE%', 'CapType']
  return myscreen_df[cols]

# get relative strength
def get_relative_strength(stock_list):

    # Dictionary to store stock tickers and their corresponding percentage price change
    stock_changes = {}

    # Loop through each stock and fetch its price data
    for stock in stock_list:
        try:
            # Download the stock data for the given date range
            stock_data = yfin.Ticker(stock + '.NS').history(period='1mo', interval='1d')[map(str.title, ['open', 'close', 'low', 'high', 'volume'])]

            # Calculate the percentage change for the stock
            if len(stock_data) > 0:
                start_price = stock_data['Close'].iloc[0]
                end_price = stock_data['Close'].iloc[-1]
                percent_change = round(((end_price - start_price) / start_price) * 100, 2)
                stock_changes[stock] = percent_change
            else:
                stock_changes[stock] = np.nan  # If no data is available, set to NaN

        except Exception as e:
            print(f"Error fetching data for {stock}: {e}")
            stock_changes[stock] = np.nan

    # Create a DataFrame with stock tickers and their percentage changes
    df = pd.DataFrame(list(stock_changes.items()), columns=['Symbol', 'Percent_Change'])

    # Drop any stocks with missing data (NaN values)
    df = df.dropna()

    # Calculate the percentile rank based on percentage change
    df['RSP'] = round(df['Percent_Change'].rank(pct=True) * 100, 2)
    cols = ['Symbol', 'RSP']
    df = df[cols]
    # Sort by percentile rank (optional)
    df = df.sort_values(by='RSP', ascending=False).reset_index(drop=True)

    return df

In [6]:
# function to get stock technicals
def stock_prec_dev(stock_symbol):
    #stock_symbol = 'ULTRACEMCO.NS'
    short_window = 20
    mid_window = 50
    long_window = 200
    moving_avg = 'SMA'

    start = datetime.datetime(*map(int, start_date.split('-')))
    end = datetime.datetime(*map(int, end_date.split('-')))

    stock_df = yfin.Ticker(stock_symbol + '.NS').history(period='max', interval='1d')[map(str.title, ['open', 'close', 'low', 'high', 'volume'])]

    stock_df['Max'] = round(max(stock_df['Close']),2)
    stock_df = stock_df[(stock_df.index <= end_date) & (stock_df.index >= start_date)]
    stock_df['200_SMA'] = round(stock_df['Close'].rolling(window = 200, min_periods = 1).mean(),0)
    stock_df['Dev%_200'] = round((stock_df['Close'] - stock_df['200_SMA'])*100/stock_df['200_SMA'],2)
    stock_df.dropna(axis = 0, inplace = True) # remove any null rows

    stock_df['20_SMA'] = stock_df['Close'].rolling(window=20).mean()
    stock_df['50_SMA'] = stock_df['Close'].rolling(window=50).mean()
    stock_df['Symbol'] = stock_symbol

    stock_df['Close'] = round(stock_df['Close'],2)
    stock_df['Min'] = round(min(stock_df['Close']),2)
    stock_df['RSI_14'] = ta.momentum.RSIIndicator(close=stock_df['Close'], window=14).rsi()
    stock_df['RSI_14'] = round(stock_df['RSI_14'],0)
    stock_df['Prev_Close'] = stock_df['Close'].shift(1)
    stock_df.drop(['Open', 'Low', 'High', 'Volume'], axis=1, inplace=True)
    stock_df = stock_df.tail(1)

    max_SMA = max(stock_df['20_SMA'].item(), stock_df['50_SMA'].item(), stock_df['200_SMA'].item())
    min_SMA = min(stock_df['20_SMA'].item(), stock_df['50_SMA'].item(), stock_df['200_SMA'].item())
    ABS_Spread = max_SMA - min_SMA
    stock_df['Spread%'] = round((ABS_Spread / stock_df['200_SMA'].item()) * 100,2)

    return stock_df

# function to compute stock attributes
def get_common_features(stock_ids, df_mypf):

  df_prec_dev = pd.DataFrame()
  df_tmp = get_screener_features()
  df_rs = get_relative_strength(stock_ids)

  for stock_id in stock_ids:
      tmp = stock_prec_dev(stock_id)
      tmp = tmp.reset_index()
      df_prec_dev = pd.concat([df_prec_dev, tmp], ignore_index = True)
  df_prec_dev = pd.merge(df_prec_dev, df_mypf, on= 'Symbol')
  df_prec_dev = pd.merge(df_prec_dev, df_tmp, on= 'Symbol', how='left')
  df_prec_dev = pd.merge(df_prec_dev, df_rs, on= 'Symbol', how='left')
  #print(df_prec_dev.columns)
  df_prec_dev['Curr_PE'] = round(df_prec_dev['Close']/df_prec_dev['EPS'],1)
  df_prec_dev['Dev%_PE'] = round((df_prec_dev['Curr_PE'] - df_prec_dev['MedPE'])*100/df_prec_dev['MedPE'],2)
  df_prec_dev['Conviction'] = df_prec_dev['Conviction'] + '-' + df_prec_dev['CapType']
  return df_prec_dev

# function to arrange stock features
def arrange_features(df_stocks, common_cols, diff_cols):
  df_stocks_common = df_stocks[common_cols].drop_duplicates()
  df_stocks_diff = df_stocks[diff_cols]
  df_stocks_diff['Investment'] = df_stocks_diff['AvgCost'] * df_stocks_diff['Shares']
  df_stocks_diff = df_stocks_diff.groupby(['Symbol'])[['Shares', 'Investment']].aggregate(['sum']).reset_index()
  df_stocks_diff.columns = ['Symbol', 'Shares', 'Investment']
  df_stocks_diff['AvgCost'] = round(df_stocks_diff['Investment']/df_stocks_diff['Shares'],2)
  df_stocks = pd.merge(df_stocks_diff, df_stocks_common, on='Symbol')
  return df_stocks

# plot fact distribution across dimension
def plot_pie_chart(df, dimension, fact):
  # grouping the data by category and calculating the sum of fact for each type
  grouped_data = df.groupby(dimension)[fact].sum()

  # sorting the grouped data in descending order
  grouped_data = grouped_data.sort_values(ascending=False)

  # creating a pie chart
  grouped_data.plot.pie(autopct='%1.1f%%', startangle=90, figsize=(6, 6))

  # adding a title and displaying the plot
  plt.title(f'{dimension} {fact} Distribution')
  plt.ylabel('')  # To hide the y-label
  plt.show()

In [7]:
# function to get portfolio features

def get_portfolio_features(df_common_features):

  print_date_time()
  print('-------------------')

  #df_common_features["Target"] = df_common_features["Target"].fillna(df_common_features["Max"])
  df_common_features['NTT'] = np.where(df_common_features['Strategy']== 'NTT', df_common_features["Target"], df_common_features['Max'])
  df_common_features['LTT'] = np.where(df_common_features['Strategy']== 'BTT', df_common_features["Target"], df_common_features['Max'])
  df_common_features['BOL'] = df_common_features['Min']

  tmp_df = df_common_features[df_common_features['Symbol'].isin(mypf_df[mypf_df['InPortfolio'] != 'NA'].Symbol.values)]
  print('qualified stocks: '+str(len(tmp_df['Symbol'].unique())))
  tmp_df1 = tmp_df[tmp_df['LatestQtr'] == 1]
  print('with latest results: '+str(len(tmp_df1['Symbol'].unique())))
  tmp_df1 = tmp_df1[tmp_df1['StarStock'] == 1]
  print('still star stocks: '+str(len(tmp_df1['Symbol'].unique())))
  tmp_df['Investment'] = tmp_df['AvgCost'] * tmp_df['Shares']
  tmp_df['Current'] = round(tmp_df['Close'] * tmp_df['Shares'],0)
  tmp_df['Previous'] = tmp_df['Prev_Close'] * tmp_df['Shares']
  tmp_df['EstimatedST'] = tmp_df['NTT'] * tmp_df['Shares']
  tmp_df['EstimatedLT'] = tmp_df['LTT'] * tmp_df['Shares']
  tmp_df['Current P/L'] = round((tmp_df['Current'] - tmp_df['Investment']),0)
  tmp_df['Today P/L%'] = round((tmp_df['Current'] - tmp_df['Previous'])*100/tmp_df['Previous'],2)
  tmp_df['Current P/L%'] = round((tmp_df['Current'] - tmp_df['Investment'])*100/tmp_df['Investment'],2)
  tmp_df['EstimatedST P/L%'] = round((tmp_df['EstimatedST'] - tmp_df['Investment'])*100/tmp_df['Investment'],2)
  tmp_df['EstimatedLT P/L%'] = round((tmp_df['EstimatedLT'] - tmp_df['Investment'])*100/tmp_df['Investment'],2)
  tmp_df['NTT%'] = round((tmp_df['NTT'] - tmp_df['Close'])*100/tmp_df['Close'],2)
  tmp_df['LTT%'] = round((tmp_df['LTT'] - tmp_df['Close'])*100/tmp_df['Close'],2)
  tmp_df['Gained%'] = round((tmp_df['Close'] - tmp_df['BOL'])*100/tmp_df['BOL'],2)
  investment = round(sum(tmp_df['AvgCost']*tmp_df['Shares']),0)
  current = round(sum(tmp_df['Close']*tmp_df['Shares']),0)
  tmp_df['InitAlloc%'] = round(tmp_df['Investment']*100/investment,2)
  tmp_df['CurrAlloc%'] = round(tmp_df['Current']*100/current,2)
  tmp_df['FTT'] = tmp_df['LTT']
  tmp_df.loc[tmp_df['Strategy'] == 'NTT', 'FTT'] = tmp_df['NTT']
  tmp_df['FTT%'] = tmp_df['LTT%']
  tmp_df.loc[tmp_df['Strategy'] == 'NTT', 'FTT%'] = tmp_df['NTT%']
  tmp_df['FTT Amt'] = round(tmp_df['FTT%'] * tmp_df['Current']/100,0)
  tmp_df['OTT%'] = round((tmp_df['FTT'] - tmp_df['AvgCost'])*100/tmp_df['AvgCost'],2)
  tmp_df['RRR Ind'] = round(tmp_df['Current P/L']/tmp_df['FTT Amt'],2)
  tmp_df['Risk Ind'] = round(tmp_df['Current P/L%']*tmp_df['CurrAlloc%'],0)

  return tmp_df

# function to print portfolio features
def print_portfolio_stats(df_portfolio_features, myinvmt_df):
  from pyxirr import xirr

  total_booked_amt, reserve_amt, cy_booked_amt, py_booked_amt = get_amt()

  dates = myinvmt_df['Date'].values
  dates = np.append(dates, datetime.date.today().strftime('%d-%b-%y'))
  investment = myinvmt_df['Investment'].values
  dates= pd.to_datetime(dates)

  current = round(sum(df_portfolio_features['Close']*df_portfolio_features['Shares']),0) + reserve_amt
  investment_xirr = np.append(investment, current)
  cagr = round(xirr(pd.DataFrame({"dates": dates, "amounts": investment_xirr}))*100,2)

  investment = -sum(investment)
  invested = round(sum(df_portfolio_features['AvgCost']*df_portfolio_features['Shares']),0) + reserve_amt
  previous = round(sum(df_portfolio_features['Prev_Close']*df_portfolio_features['Shares']),0) + reserve_amt
  cy_invested = investment + py_booked_amt

  today_pnl_amount = current-previous
  today_pnl_percentage = round((current-previous)*100/previous,2)

  curr_pnl_amount = current-invested
  curr_pnl_percentage = round((curr_pnl_amount)*100/(cy_invested),2)

  cy_pnl_amount = cy_booked_amt + curr_pnl_amount
  cy_pnl_percentage = round((cy_pnl_amount)*100/cy_invested,2)

  overall_pnl_amount = total_booked_amt + curr_pnl_amount
  overall_pnl_percentage = round((overall_pnl_amount)*100/investment,2)

  estimate_st = round(sum(df_portfolio_features['FTT']*df_portfolio_features['Shares']),0)  + reserve_amt
  est_st_pnl_amount = estimate_st-current
  est_st_pnl_percentage = round((est_st_pnl_amount)*100/current,2)

  estimate_lt = round(sum(df_portfolio_features['LTT']*df_portfolio_features['Shares']),0)  + reserve_amt
  est_lt_pnl_amount = estimate_lt-current
  est_lt_pnl_percentage = round((est_lt_pnl_amount)*100/current,2)

  total_profit = round(sum(df_portfolio_features[df_portfolio_features['Current P/L%'] > 0]['Current']) - sum(df_portfolio_features[df_portfolio_features['Current P/L%'] > 0]['Investment']),0)
  total_loss = round(sum(df_portfolio_features[df_portfolio_features['Current P/L%'] < 0]['Current']) - sum(df_portfolio_features[df_portfolio_features['Current P/L%'] < 0]['Investment']),0)

  cy_booked_percentage = round((cy_booked_amt)*100/current,2)
  py_booked_percentage = round((py_booked_amt)*100/investment,2)
  total_booked_percentage = round((total_booked_amt)*100/investment,2)

  print('-------------------')
  print('Initial Investment: ', format_amt(investment))
  print('CY Investment: ', format_amt(cy_invested))
  print('Reserve: ', format_amt(reserve_amt))
  print('Current: ',  format_amt(current))
  print('-------------------')
  print('Today PnL: '+ '{} ({}%)'.format(format_amt(today_pnl_amount), today_pnl_percentage))
  print('Current PnL: '+ '{} ({}%)'.format(format_amt(curr_pnl_amount), curr_pnl_percentage))
  print('CY Booked + Current PnL: '+ '{} ({}%)'.format(format_amt(cy_pnl_amount), cy_pnl_percentage))
  print('-------------------')
  print('Total profit: ', format_amt(total_profit))
  print('Total loss: ', format_amt(total_loss))
  print('-------------------')
  print('Total Booked + Current PnL: '+ '{} ({}%)'.format(format_amt(overall_pnl_amount), overall_pnl_percentage))
  print('Total Booked PnL: '+ '{} ({}%)'.format(format_amt(total_booked_amt), total_booked_percentage))
  print('Curr Year Booked PnL: '+ '{} ({}%)'.format(format_amt(cy_booked_amt), cy_booked_percentage))
  print('Prev Year Booked PnL: '+ '{} ({}%)'.format(format_amt(py_booked_amt), py_booked_percentage))
  print('===================')
  print('Est FTT: ',  format_amt(estimate_st))
  print('Est FTT PnL: '+ '{} ({}%)'.format(format_amt(est_st_pnl_amount), est_st_pnl_percentage))

  print('===================')
  print('Deployed: ', format_amt(investment))

  print('Current: ', format_amt(current))

  print('CAGR/XIRR %: '+'{}%'.format(cagr))

In [8]:
# get start and end date
start_date, end_date = get_start_end_date()

# get portfolio and prospects data
mypfs_df = get_mypfs_df()
mypps_df = get_mypps_df()
myinvmt_df = get_myinvmt_df()

# merge above datasets
mypf_df = pd.merge(mypfs_df, mypps_df, on="Symbol")

# seggregate dm and sv portfolio
dm_pf = mypf_df[mypf_df['InPortfolio'] == 'DM']
sv_pf = mypf_df[mypf_df['InPortfolio'] == 'SV']

# build portfolio stock dataframe
dm_stocks = get_stock_ids(dm_pf)
sv_stocks = get_stock_ids(sv_pf)
df_stocks = pd.concat([dm_pf,sv_pf], ignore_index = True)

# arrange common and diff stock features
common_cols = ['Symbol', 'Target', 'Criteria', 'Strategy', 'CumlRnk', 'LatestQtr', 'StarStock', 'Conviction', 'Category', 'InFolio', 'XIRR', 'MBQ']
diff_cols = ['Symbol', 'AvgCost', 'Shares']
df_stocks = arrange_features(df_stocks, common_cols, diff_cols)

# get common features
stock_ids = df_stocks['Symbol'].values
df_common_features = get_common_features(stock_ids, df_stocks)

df_common_features.reset_index(drop=True, inplace=True)
df_common_features.drop(['Date'], axis=1, inplace=True)
# get and print portfolio features
df_portfolio_features = get_portfolio_features(df_common_features)

print_portfolio_stats(df_portfolio_features, myinvmt_df)

df = df_portfolio_features
#plot_pie_chart(df, 'CapType', 'Current')
list_ox40n = list(df[df['MBQ'].str.contains('OX40N', na=False)]['Symbol'].values)

Run date time (IST): 2026-03-27 11:33:32
-------------------
qualified stocks: 86
with latest results: 26
still star stocks: 16
-------------------
Initial Investment:  1.36 C
CY Investment:  1.62 C
Reserve:  1.61 K
Current:  1.29 C
-------------------
Today PnL: -2.63 L (-2.0%)
Current PnL: -48.35 L (-29.75%)
CY Booked + Current PnL: -32.46 L (-19.98%)
-------------------
Total profit:  42.32 K
Total loss:  -48.77 L
-------------------
Total Booked + Current PnL: -5.48 L (-4.04%)
Total Booked PnL: 42.87 L (31.64%)
Curr Year Booked PnL: 15.89 L (12.34%)
Prev Year Booked PnL: 26.98 L (19.91%)
===================
Est FTT:  2.48 C
Est FTT PnL: 1.19 C (92.49%)
===================
Deployed:  1.36 C
Current:  1.29 C
CAGR/XIRR %: -2.48%

In [9]:
# top 5 near their targets
cols = ['Symbol', 'Today P/L%', 'Current P/L%', 'FTT%', 'OTT%', 'FTT Amt', 'Current P/L', 'Current', 'FTT', 'Dev%_PE', 'RSI_14','Conviction', 'Spread%',  'CumlRnk', 'RRR Ind', 'CurrAlloc%', 'Gained%', 'Criteria', 'Strategy', 'Category']
df_tmp = df_portfolio_features[~df_portfolio_features['Symbol'].isin(['ENRIN','BLUSPRING','DIGITIDE'])]
df_tmp = df_tmp.sort_values(by = 'FTT Amt', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
50,MASFIN,-2.22,-9.66,34.57,21.57,30600.0,-9465.0,88515.0,397.04,-22.31,41.0,H-SC,3.49,167.0,-0.31,0.69,20.73,XR,ATH,FINANCE
77,TTKPRESTIG,-1.78,-43.79,78.08,0.09,44228.0,-44133.0,56644.0,770.00,31.48,33.0,M-SC,20.67,250.0,-1.00,0.44,0.00,OX40N,NTT,DURABLES
2,ABBOTINDIA,-0.23,-11.62,33.59,18.07,53096.0,-20785.0,158070.0,35195.00,-24.86,46.0,X-MC,10.45,58.0,-0.39,1.23,3.37,X40,ATH,PHARMA
37,ICICIGI,-1.37,-7.51,29.03,19.34,53728.0,-15033.0,185076.0,2252.93,-22.28,34.0,X-MC,4.48,66.0,-0.28,1.44,2.31,X40,ATH,INSURANCE
67,SONACOMS,-4.21,-15.25,64.12,39.09,54971.0,-15427.0,85732.0,804.02,-32.89,45.0,M-MC,6.72,193.0,-0.28,0.67,21.28,AR,ATH,AUTO

In [10]:
# top 5 today
df_tmp = df_portfolio_features.sort_values(by = 'Today P/L%', ascending=False)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
48,KANSAINER,1.32,-41.29,93.29,13.47,147687.0,-111357.0,158310.0,340.00,-49.54,40.0,H-SC,21.61,162.0,-0.75,1.23,10.58,XY24,NTT,PAINTS
73,TCS,1.15,-29.40,79.29,26.57,259320.0,-136220.0,327053.0,4311.58,-40.35,33.0,X-LC,17.83,2.0,-0.53,2.54,2.07,X40,ATH,IT
84,WIPRO,0.62,-21.98,120.80,72.27,159701.0,-37245.0,132203.0,420.00,-29.71,34.0,M-LC,17.97,98.0,-0.23,1.03,1.43,XR,NTT,IT
68,STARHEALTH,0.34,-10.85,65.18,47.26,163355.0,-30502.0,250621.0,761.00,40.70,52.0,H-SC,0.21,173.0,-0.19,1.95,34.28,XY24,NTT,INSURANCE
85,ZYDUSLIFE,0.29,-4.43,41.91,35.63,83942.0,-9282.0,200292.0,1286.17,-16.67,52.0,H-MC,5.28,120.0,-0.11,1.56,11.50,AR,ATH,PHARMA

In [11]:
# bottom 5 today
df_tmp = df_portfolio_features.sort_values(by = 'Today P/L%', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
14,BOSCH-HCIL,-6.21,-50.43,101.73,-0.01,64443.0,-64458.0,63347.0,2282.0,12856.52,24.0,M-SC,5.88,231.0,-1.00,0.49,0.00,OX40N,BTT,AC
80,VALIANTORG,-5.15,-53.41,273.79,74.15,208696.0,-87380.0,76225.0,838.0,-237.24,46.0,H-SC,28.03,145.0,-0.42,0.59,13.43,XR,NTT,CHEMICALS
56,RAJOOENG,-5.11,-49.63,177.16,39.61,91468.0,-50870.0,51630.0,143.1,-66.01,34.0,H-SC,32.89,136.0,-0.56,0.40,1.57,AR,ATH,MISC
60,REPCOHOME,-5.09,-24.13,150.18,89.82,326464.0,-69123.0,217382.0,880.0,-62.00,42.0,H-SC,8.47,161.0,-0.21,1.69,7.34,XY24,NTT,FINANCE
55,RAJESHEXPO,-5.00,-83.65,512.22,0.07,114850.0,-114755.0,22422.0,518.0,721.97,19.0,L-SC,37.59,268.0,-1.00,0.17,0.00,OX40N,NTT,JEWELLERY

In [12]:
# top 5 to exit based on CumlRnk
df_tmp = df_portfolio_features[~df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])]
df_tmp = df_tmp[(df_tmp['Current P/L%'] > -1) & (df_tmp['Current P/L%'] < 1)].sort_values(by = 'CumlRnk', ascending=False)
df_tmp[cols].head()

Empty DataFrame
Columns: [Symbol, Today P/L%, Current P/L%, FTT%, OTT%, FTT Amt, Current P/L, Current, FTT, Dev%_PE, RSI_14, Conviction, Spread%, CumlRnk, RRR Ind, CurrAlloc%, Gained%, Criteria, Strategy, Category]
Index: []

In [13]:
# OX40N stocks to exit
df_tmp = df_portfolio_features[(df_portfolio_features['Symbol'].isin(list_ox40n))].sort_values(by = 'Current P/L%', ascending=False)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
26,FINCABLES,-2.90,2.34,103.16,107.91,155871.0,3452.0,151096.0,1641.55,-8.17,44.0,M-SC,7.91,220.0,0.02,1.17,13.67,OX40N,ATH,CABLES
66,SIS,-1.01,-35.01,86.57,21.26,62473.0,-38867.0,72165.0,528.00,1688.08,44.0,H-SC,14.48,168.0,-0.62,0.56,7.30,OX40N,NTT,MISC
18,CERA,0.00,-38.18,100.39,23.89,109175.0,-67152.0,108751.0,9475.00,-40.33,47.0,H-SC,19.11,153.0,-0.62,0.84,4.51,OX40N,NTT,CERAMICS
72,TATAELXSI,-0.56,-39.61,118.64,32.03,94449.0,-52225.0,79610.0,9161.00,-24.40,38.0,H-SC,21.23,158.0,-0.55,0.62,3.73,OX40N,NTT,IT
48,KANSAINER,1.32,-41.29,93.29,13.47,147687.0,-111357.0,158310.0,340.00,-49.54,40.0,H-SC,21.61,162.0,-0.75,1.23,10.58,XY24,NTT,PAINTS

In [14]:
# top 5 to book for rotation
df_tmp = df_portfolio_features[(df_portfolio_features['Current P/L%'] > 20) ].sort_values(by = 'CumlRnk', ascending=False)
df_tmp[cols].head()

Empty DataFrame
Columns: [Symbol, Today P/L%, Current P/L%, FTT%, OTT%, FTT Amt, Current P/L, Current, FTT, Dev%_PE, RSI_14, Conviction, Spread%, CumlRnk, RRR Ind, CurrAlloc%, Gained%, Criteria, Strategy, Category]
Index: []

In [15]:
# top 5 to monitor for exit
df_tmp = df_portfolio_features[~df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])]
df_tmp = df_tmp[(df_tmp['Current P/L%'] > 0) ].sort_values(by = 'Dev%_PE', ascending=False)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
26,FINCABLES,-2.90,2.34,103.16,107.91,155871.0,3452.0,151096.0,1641.55,-8.17,44.0,M-SC,7.91,220.0,0.02,1.17,13.67,OX40N,ATH,CABLES
1,ABB,-1.86,11.86,30.13,45.57,88177.0,31037.0,292656.0,7934.00,-28.16,51.0,H-MC,13.35,125.0,0.35,2.27,29.96,AR,NTT,ELECTRICAL

In [16]:
# top 5 to book for rotation from weak conviction
df_tmp = df_portfolio_features[~df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])]
df_tmp = df_tmp[~df_tmp['Criteria'].isin(['XY25','XY24','X40', 'X40N'])].sort_values(by = 'RRR Ind', ascending=False)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
1,ABB,-1.86,11.86,30.13,45.57,88177.0,31037.0,292656.0,7934.00,-28.16,51.0,H-MC,13.35,125.0,0.35,2.27,29.96,AR,NTT,ELECTRICAL
26,FINCABLES,-2.90,2.34,103.16,107.91,155871.0,3452.0,151096.0,1641.55,-8.17,44.0,M-SC,7.91,220.0,0.02,1.17,13.67,OX40N,ATH,CABLES
85,ZYDUSLIFE,0.29,-4.43,41.91,35.63,83942.0,-9282.0,200292.0,1286.17,-16.67,52.0,H-MC,5.28,120.0,-0.11,1.56,11.50,AR,ATH,PHARMA
40,INDIAMART,-1.08,-14.32,141.27,106.72,149290.0,-17659.0,105677.0,4810.62,-61.33,37.0,H-SC,12.34,140.0,-0.12,0.82,5.71,AR,ATH,MISC
84,WIPRO,0.62,-21.98,120.80,72.27,159701.0,-37245.0,132203.0,420.00,-29.71,34.0,M-LC,17.97,98.0,-0.23,1.03,1.43,XR,NTT,IT

In [17]:
# top 5 to accumulate based on lowest RSI_14
df_tmp = df_portfolio_features[df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])].sort_values(by = 'RSI_14', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
53,PGHH,-1.32,-28.61,84.92,32.01,129445.0,-61088.0,152432.0,17616.87,-51.69,20.0,X-MC,17.09,57.0,-0.47,1.18,0.75,X40,ATH,FMCG
38,ICICIPRULI,-2.47,-12.75,49.83,30.73,85650.0,-25121.0,171884.0,790.00,-36.16,21.0,X-MC,5.59,78.0,-0.29,1.33,0.00,X40,ATH,INSURANCE
9,BAJAJHFL,-3.40,-31.72,137.44,62.13,256239.0,-86609.0,186437.0,181.50,-43.90,23.0,X-MC,20.60,60.0,-0.34,1.45,0.00,X40N,ATH,FINANCE
58,RELAXO,-3.44,-66.77,358.30,52.31,172848.0,-96919.0,48241.0,1176.00,-64.57,24.0,X-SC,28.44,92.0,-0.56,0.37,0.69,X40N,NTT,FOOTWEAR
3,ACC,-3.54,-40.95,196.02,74.81,310378.0,-109788.0,158340.0,3906.00,-57.90,28.0,X-SC,19.10,85.0,-0.35,1.23,0.00,XY24,BTT,CEMENT

In [18]:
# top 5 to accumulate based on Spread and CumlRnk
df_tmp = df_portfolio_features[df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])]
df_tmp = df_tmp[(df_tmp['CumlRnk'] < 100)].sort_values(by = 'Spread%', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
65,SIEMENS,-1.73,-18.12,53.29,25.51,81201.0,-33720.0,152375.0,4671.50,27.94,43.0,H-LC,1.81,51.0,-0.42,1.18,12.21,AR,ATH,ELECTRICAL
78,UNITDSPR,-3.00,-6.55,29.22,20.77,63939.0,-15326.0,218818.0,1644.00,-17.10,40.0,X-MC,2.39,64.0,-0.24,1.70,0.00,X40N,NTT,BREWERIES
82,VOLTAS,-2.80,4.09,39.50,45.20,78832.0,7833.0,199575.0,1856.00,19.11,41.0,X-MC,3.37,79.0,0.10,1.55,11.16,XY25,NTT,AC
59,RELIANCE,-3.28,-12.27,42.83,25.30,75511.0,-24659.0,176304.0,1952.00,-14.65,41.0,X-LC,3.62,21.0,-0.33,1.37,17.71,XY25,BTT,REFINERIES
37,ICICIGI,-1.37,-7.51,29.03,19.34,53728.0,-15033.0,185076.0,2252.93,-22.28,34.0,X-MC,4.48,66.0,-0.28,1.44,2.31,X40,ATH,INSURANCE

In [19]:
# top 5 to accumulate based on lowest Gained%
df_tmp = df_portfolio_features[df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])].sort_values(by = 'Gained%', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
3,ACC,-3.54,-40.95,196.02,74.81,310378.0,-109788.0,158340.0,3906.0,-57.90,28.0,X-SC,19.10,85.0,-0.35,1.23,0.0,XY24,BTT,CEMENT
9,BAJAJHFL,-3.40,-31.72,137.44,62.13,256239.0,-86609.0,186437.0,181.5,-43.90,23.0,X-MC,20.60,60.0,-0.34,1.45,0.0,X40N,ATH,FINANCE
38,ICICIPRULI,-2.47,-12.75,49.83,30.73,85650.0,-25121.0,171884.0,790.0,-36.16,21.0,X-MC,5.59,78.0,-0.29,1.33,0.0,X40,ATH,INSURANCE
75,TMPV,-4.80,-31.10,98.22,36.58,240823.0,-110654.0,245187.0,600.0,-85.81,34.0,X-LC,8.35,4.0,-0.46,1.90,0.0,XY24,NTT,AUTO
78,UNITDSPR,-3.00,-6.55,29.22,20.77,63939.0,-15326.0,218818.0,1644.0,-17.10,40.0,X-MC,2.39,64.0,-0.24,1.70,0.0,X40N,NTT,BREWERIES

In [20]:
# top 5 to accumulate based on lowest CurrAlloc%
df_tmp = df_portfolio_features[df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])].sort_values(by = 'CurrAlloc%', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
58,RELAXO,-3.44,-66.77,358.30,52.31,172848.0,-96919.0,48241.0,1176.00,-64.57,24.0,X-SC,28.44,92.0,-0.56,0.37,0.69,X40N,NTT,FOOTWEAR
12,BATAINDIA,-2.46,-58.47,225.57,35.20,120533.0,-75235.0,53435.0,2096.00,-29.96,29.0,X-SC,32.29,91.0,-0.62,0.41,2.88,X40,NTT,FOOTWEAR
54,QUESS,-0.96,-28.24,142.34,73.90,109078.0,-30161.0,76632.0,424.00,-61.43,38.0,X-SC,21.75,80.0,-0.28,0.60,3.00,XY24,NTT,MISC
36,HONAUT,-1.81,-28.19,110.71,51.31,153306.0,-54363.0,138475.0,58357.33,-40.26,31.0,X-SC,16.59,90.0,-0.35,1.08,1.76,X40N,ATH,ELECTRICAL
51,MEDANTA,-2.27,-15.46,50.36,27.12,75154.0,-27284.0,149233.0,1486.00,-18.04,33.0,X-SC,13.41,87.0,-0.36,1.16,1.93,XY24,NTT,HEALTHCARE

In [21]:
# top 5 to accumulate based on CumlRnk
df_tmp = df_portfolio_features.sort_values(by = 'CumlRnk', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
45,ITC,-0.83,-22.76,54.13,19.06,142228.0,-77414.0,262752.0,452.00,-57.54,35.0,X-LC,18.95,1.0,-0.54,2.04,0.96,X40,NTT,FMCG
73,TCS,1.15,-29.40,79.29,26.57,259320.0,-136220.0,327053.0,4311.58,-40.35,33.0,X-LC,17.83,2.0,-0.53,2.54,2.07,X40,ATH,IT
43,INFY,-0.49,-13.35,54.93,34.24,148919.0,-41782.0,271106.0,1972.00,-31.79,41.0,X-LC,15.07,3.0,-0.28,2.11,4.26,X40,NTT,IT
75,TMPV,-4.80,-31.10,98.22,36.58,240823.0,-110654.0,245187.0,600.00,-85.81,34.0,X-LC,8.35,4.0,-0.46,1.90,0.00,XY24,NTT,AUTO
33,HCLTECH,-0.29,-10.62,38.55,23.83,83359.0,-25688.0,216236.0,1908.19,-6.12,46.0,X-LC,11.59,8.0,-0.31,1.68,4.99,X40,ATH,IT

In [22]:
# top 5 for average up
df_tmp = df_portfolio_features[(df_portfolio_features['Dev%_200'] > 5)].sort_values(by = 'CurrAlloc%', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
1,ABB,-1.86,11.86,30.13,45.57,88177.0,31037.0,292656.0,7934.0,-28.16,51.0,H-MC,13.35,125.0,0.35,2.27,29.96,AR,NTT,ELECTRICAL

In [23]:
# top 5 RSP
df_tmp = df_portfolio_features.sort_values(by = 'RSP', ascending=False)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
30,HAPPSTMNDS,-0.53,-50.56,273.92,84.85,173556.0,-64805.0,63360.0,1480.71,-41.23,53.0,H-SC,25.64,152.0,-0.37,0.49,17.33,AR,ATH,IT
24,DMART,-0.15,-6.13,38.06,29.60,89177.0,-15294.0,234306.0,5391.45,-20.85,55.0,X-LC,6.86,14.0,-0.17,1.82,7.10,X40N,ATH,FMCG
5,ANGELONE,-2.20,-3.84,29.14,24.18,85464.0,-11712.0,293288.0,303.00,-85.87,52.0,X-SC,10.13,97.0,-0.14,2.28,12.89,X40N,NTT,FINANCE
1,ABB,-1.86,11.86,30.13,45.57,88177.0,31037.0,292656.0,7934.00,-28.16,51.0,H-MC,13.35,125.0,0.35,2.27,29.96,AR,NTT,ELECTRICAL
52,PAGEIND,-1.85,-16.46,60.53,34.11,135714.0,-44169.0,224210.0,51418.64,-40.08,50.0,X-MC,21.03,55.0,-0.33,1.74,6.06,X40,ATH,APPARELS

In [24]:
# Top N allocation
df_tmp = df_portfolio_features.sort_values(by = 'CurrAlloc%', ascending=False)
top_n_values = [10, 25, 50]

sum_df = pd.DataFrame({
    'Top_N': top_n_values,
    'Sum_Alloc%': [df_tmp['CurrAlloc%'].head(n).sum() for n in top_n_values]
})

sum_df

   Top_N  Sum_Alloc%
0     10       20.86
1     25       46.07
2     50       78.40

In [25]:
# market-cap-wise allocation
df_tmp = df_portfolio_features[cols]
df_tmp.groupby(df_tmp['Conviction'].str[-2:])['CurrAlloc%'].sum().sort_values(ascending=False)

Conviction
SC    44.16
MC    30.14
LC    25.68
Name: CurrAlloc%, dtype: float64

In [26]:
# criteria-wise allocation
df_portfolio_features.groupby('Criteria')['CurrAlloc%'].sum().sort_values(ascending=False)

Criteria
XY24     26.95
X40      25.57
X40N     15.26
AR        9.17
XR        8.25
XY25      7.39
OX40N     6.60
SR        0.79
Name: CurrAlloc%, dtype: float64

In [27]:
# conviction-wise allocation
df_portfolio_features.groupby('Conviction')['CurrAlloc%'].sum().sort_values(ascending=False)

Conviction
X-LC    23.47
X-MC    22.63
H-SC    21.54
X-SC    12.29
M-SC     9.82
H-MC     5.12
M-MC     2.04
H-LC     1.18
M-LC     1.03
L-SC     0.51
L-MC     0.35
Name: CurrAlloc%, dtype: float64

In [28]:
# sector-wise stats
df_tmp = df_portfolio_features.groupby('Category')[['CurrAlloc%', 'Current', 'Current P/L', 'FTT Amt']].sum().sort_values(by=['Current', 'Current P/L'], ascending=False)
df_tmp['Current P/L%'] = round(df_tmp['Current P/L'] * 100 / df_tmp['Current'], 2)
df_tmp['FTT%'] = round(df_tmp['FTT Amt'] * 100 / df_tmp['Current'], 2)
cols = ['CurrAlloc%', 'Current P/L%', 'FTT%']
df_tmp[cols].sort_values(by=['CurrAlloc%'], ascending=False)

               CurrAlloc%  Current P/L%    FTT%
Category
FMCG                15.17        -27.82   73.20
FINANCE             13.05        -28.01   80.18
IT                  11.93        -46.63  121.25
MISC                 6.97        -49.39  114.29
ELECTRICAL           6.55        -14.79   58.74
PAINTS               5.24        -45.90   71.24
INSURANCE            4.72        -11.63   49.83
BANKS                4.57        -30.60   96.89
PHARMA               4.21         -8.52   42.68
AUTO                 3.63        -40.02   95.58
AC                   2.04        -21.54   54.49
HEALTHCARE           1.88        -48.06   86.70
FOOTWEAR             1.79        -90.81  167.32
TRAVEL               1.78        -94.89  192.48
DURABLES             1.75        -72.04  113.89
APPARELS             1.74        -19.70   60.53
BREWERIES            1.70         -7.00   29.22
REALTY               1.49        -15.58   34.57
CERAMICS             1.37        -73.57  126.30
REFINERIES           1.37        -13.99   42.83
CEMENT               1.23        -69.34  196.02
CABLES               1.17          2.28  103.16
ENGINEERING          1.07        -76.02  156.52
CHEMICALS            1.03        -98.60  260.63
JEWELLERY            0.99       -151.18  238.44
ENTERTAINMENT        0.74       -102.56  223.37
TEXTILES             0.46        -54.08   98.02
HOTELS               0.34       -162.61  255.24

In [29]:
# money to be made criteria-wise
df_portfolio_features.groupby('Criteria')['FTT Amt'].agg(['sum', 'count']).sort_values(by='sum', ascending=False)

                sum  count
Criteria
XY24      4128302.0     21
X40       1880545.0     16
XR        1429775.0     12
AR        1389750.0     10
X40N      1335403.0     10
OX40N      940199.0     10
XY25       489450.0      5
SR         317063.0      2

In [30]:
# money to be made conviction-wise
df_portfolio_features.groupby('Conviction')['FTT Amt'].agg(['sum', 'count']).sort_values(by='sum', ascending=False)

                  sum  count
Conviction
H-SC        4018167.0     24
X-MC        1818396.0     15
X-LC        1754711.0     13
M-SC        1651913.0     14
X-SC        1600251.0     10
H-MC         419233.0      3
L-SC         225211.0      2
M-LC         159701.0      1
M-MC         124165.0      2
H-LC          81201.0      1
L-MC          57538.0      1

In [31]:
# money to be made criteria and conviction-wise
df_portfolio_features.groupby(['Conviction', 'Criteria'])['FTT Amt'].agg(['sum', 'count']).sort_values(by='sum', ascending=False)

                           sum  count
Conviction Criteria
H-SC       XY24      1390619.0      6
           AR        1000610.0      5
M-SC       XY24       953415.0      6
X-LC       X40        933661.0      7
H-SC       XR         907959.0      7
X-SC       XY24       865499.0      4
X-MC       X40        724651.0      7
           X40N       554220.0      4
X-SC       X40N       512519.0      4
M-SC       OX40N      423433.0      5
H-SC       OX40N      401916.0      4
X-LC       XY24       393928.0      2
H-SC       SR         317063.0      2
X-MC       XY24       277727.0      2
X-LC       X40N       268664.0      2
X-MC       XY25       261798.0      2
H-MC       XY24       247114.0      1
X-SC       X40        222233.0      2
M-SC       XR         194216.0      2
H-MC       AR         172119.0      2
M-LC       XR         159701.0      1
X-LC       XY25       158458.0      2
L-SC       OX40N      114850.0      1
           XR         110361.0      1
H-LC       AR          81201.0      1
M-SC       AR          80849.0      1
M-MC       XY25        69194.0      1
L-MC       XR          57538.0      1
M-MC       AR          54971.0      1

In [32]:
# notebook execution time

end_time = time.time()
execution_time = round(end_time - start_time, 0)
print(f"Notebook execution time: {execution_time} seconds")

Notebook execution time: 32.0 seconds