<a href="https://colab.research.google.com/github/ankit-rathi/Quantvesting_v2/blob/main/myStocks_Portfolio_Analysis.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
'''
!pip install pandas==2.2.2 -qq
!pip install pyxirr -qq
!pip install ta -qq
!pip install yfinance==0.2.59 -qq
'''

'\n!pip install pandas==2.2.2 -qq\n!pip install pyxirr -qq\n!pip install ta -qq\n!pip install yfinance==0.2.59 -qq\n'

In [2]:
# import libraries

import numpy as np
import pandas as pd
import datetime
import warnings
warnings.filterwarnings('ignore')
import yfinance as yfin
import ta
import matplotlib.pyplot as plt
import requests

In [3]:
# notebook start time
import time
import datetime
import pytz

start_time = time.time()

# function to print date timestamp
def print_date_time():
  tz_NY = pytz.timezone('Asia/Kolkata')
  datetime_NY = datetime.datetime.now(tz_NY)
  print("Run date time (IST):", datetime_NY.strftime("%Y-%m-%d %H:%M:%S"))

In [4]:
# function to get booked and reserved amount
def get_amt():
  # fetch the JSON data from the URL
  url = "https://raw.githubusercontent.com/ankit-rathi/Tradevesting_v1/main/data/myPortfolioAmts.json"
  response = requests.get(url)
  pf_amts = response.json()  # parse the JSON data

  # extract values from the JSON
  py_booked_amt_dm = pf_amts["py_booked_amt_dm"]
  py_booked_amt_sv = pf_amts["py_booked_amt_sv"]
  cy_booked_amt_dm = pf_amts["cy_booked_amt_dm"]
  cy_booked_amt_sv = pf_amts["cy_booked_amt_sv"]
  reserve_amt_dm = pf_amts["reserve_amt_dm"]
  reserve_amt_sv = pf_amts["reserve_amt_sv"]

  # perform calculations
  py_booked_amt = py_booked_amt_dm + py_booked_amt_sv
  cy_booked_amt = cy_booked_amt_dm + cy_booked_amt_sv
  reserve_amt = reserve_amt_dm + reserve_amt_sv
  total_booked_amt = py_booked_amt + cy_booked_amt

  return total_booked_amt, reserve_amt, cy_booked_amt, py_booked_amt

gen_output = 0

In [5]:
# function to format the amount
def format_amt(number):
    abs_number = abs(number)

    if abs_number >= 1_00_00_000:  # Crores
        formatted_amt = f"{number / 1_00_00_000:.2f} C"
    elif abs_number >= 1_00_000:  # Lakhs
        formatted_amt = f"{number / 1_00_000:.2f} L"
    elif abs_number >= 1_000:  # Thousands
        formatted_amt = f"{number / 1_000:.2f} K"
    else:
        formatted_amt = f"{number:.2f}"

    return formatted_amt

# function to set start and end date
def get_start_end_date():
  start_date = (datetime.date.today() + datetime.timedelta(days=-365)).strftime('%Y-%m-%d')
  end_date = (datetime.date.today() + datetime.timedelta(days=1)).strftime('%Y-%m-%d')
  return start_date, end_date

# function to fetch my portfolio csv
def get_mypfs_df():
  mypfs_df = pd.read_csv('https://raw.githubusercontent.com/ankit-rathi/Tradevesting_v1/main/data/myPortfolioStocks.csv')
  return mypfs_df

# function to fetch my prospects csv
def get_mypps_df():
  mypps_df = pd.read_csv('https://raw.githubusercontent.com/ankit-rathi/Tradevesting_v1/main/data/myProspectsScrips.csv')
  return mypps_df

# function to fetch screener data
def get_myscreen_df():
  myscreen_df = pd.read_csv('https://raw.githubusercontent.com/ankit-rathi/Tradevesting_v1/main/data/myScreenerDB.csv')
  return myscreen_df

# function to fetch momentum data
def get_myinvmt_df():
  myinvmt_df = pd.read_csv('https://raw.githubusercontent.com/ankit-rathi/Tradevesting_v1/main/data/myInvestments.csv')
  return myinvmt_df

# function to get the stock ids
def get_stock_ids(df_pf):
  stock_n100 = df_pf['Symbol'].unique()

  exclude = ['CADILAHC','MMTC', 'MASFIN']

  stock_ids = df_pf[~df_pf['Symbol'].isin(exclude) ]['Symbol'].unique()

  #mypf = mypf[mypf.Forecast.notnull()]
  #stock_ids = mypf['Symbol'].unique()

  #stock_ids.sort()
  return stock_ids

# get features from screener data
def get_screener_features():
  myscreen_df = get_myscreen_df()
  cols = ['Symbol', 'EPS', 'MedPE', 'ROCE%', 'ROE%', 'CapType']
  return myscreen_df[cols]

# get relative strength
def get_relative_strength(stock_list):

    # Dictionary to store stock tickers and their corresponding percentage price change
    stock_changes = {}

    # Loop through each stock and fetch its price data
    for stock in stock_list:
        try:
            # Download the stock data for the given date range
            stock_data = yfin.Ticker(stock + '.NS').history(period='1mo', interval='1d')[map(str.title, ['open', 'close', 'low', 'high', 'volume'])]

            # Calculate the percentage change for the stock
            if len(stock_data) > 0:
                start_price = stock_data['Close'].iloc[0]
                end_price = stock_data['Close'].iloc[-1]
                percent_change = round(((end_price - start_price) / start_price) * 100, 2)
                stock_changes[stock] = percent_change
            else:
                stock_changes[stock] = np.nan  # If no data is available, set to NaN

        except Exception as e:
            print(f"Error fetching data for {stock}: {e}")
            stock_changes[stock] = np.nan

    # Create a DataFrame with stock tickers and their percentage changes
    df = pd.DataFrame(list(stock_changes.items()), columns=['Symbol', 'Percent_Change'])

    # Drop any stocks with missing data (NaN values)
    df = df.dropna()

    # Calculate the percentile rank based on percentage change
    df['RSP'] = round(df['Percent_Change'].rank(pct=True) * 100, 2)
    cols = ['Symbol', 'RSP']
    df = df[cols]
    # Sort by percentile rank (optional)
    df = df.sort_values(by='RSP', ascending=False).reset_index(drop=True)

    return df

In [6]:
# function to get stock technicals
def stock_prec_dev(stock_symbol):
    #stock_symbol = 'ULTRACEMCO.NS'
    short_window = 20
    mid_window = 50
    long_window = 200
    moving_avg = 'SMA'

    start = datetime.datetime(*map(int, start_date.split('-')))
    end = datetime.datetime(*map(int, end_date.split('-')))

    stock_df = yfin.Ticker(stock_symbol + '.NS').history(period='max', interval='1d')[map(str.title, ['open', 'close', 'low', 'high', 'volume'])]

    stock_df['Max'] = round(max(stock_df['Close']),2)
    stock_df = stock_df[(stock_df.index <= end_date) & (stock_df.index >= start_date)]
    stock_df['200_SMA'] = round(stock_df['Close'].rolling(window = 200, min_periods = 1).mean(),0)
    stock_df['Dev%_200'] = round((stock_df['Close'] - stock_df['200_SMA'])*100/stock_df['200_SMA'],2)
    stock_df.dropna(axis = 0, inplace = True) # remove any null rows

    stock_df['20_SMA'] = stock_df['Close'].rolling(window=20).mean()
    stock_df['50_SMA'] = stock_df['Close'].rolling(window=50).mean()
    stock_df['Symbol'] = stock_symbol

    stock_df['Close'] = round(stock_df['Close'],2)
    stock_df['Min'] = round(min(stock_df['Close']),2)
    stock_df['RSI_14'] = ta.momentum.RSIIndicator(close=stock_df['Close'], window=14).rsi()
    stock_df['RSI_14'] = round(stock_df['RSI_14'],0)
    stock_df['Prev_Close'] = stock_df['Close'].shift(1)
    stock_df.drop(['Open', 'Low', 'High', 'Volume'], axis=1, inplace=True)
    stock_df = stock_df.tail(1)

    max_SMA = max(stock_df['20_SMA'].item(), stock_df['50_SMA'].item(), stock_df['200_SMA'].item())
    min_SMA = min(stock_df['20_SMA'].item(), stock_df['50_SMA'].item(), stock_df['200_SMA'].item())
    ABS_Spread = max_SMA - min_SMA
    stock_df['Spread%'] = round((ABS_Spread / stock_df['200_SMA'].item()) * 100,2)

    return stock_df

# function to compute stock attributes
def get_common_features(stock_ids, df_mypf):

  df_prec_dev = pd.DataFrame()
  df_tmp = get_screener_features()
  df_rs = get_relative_strength(stock_ids)

  for stock_id in stock_ids:
      tmp = stock_prec_dev(stock_id)
      tmp = tmp.reset_index()
      df_prec_dev = pd.concat([df_prec_dev, tmp], ignore_index = True)
  df_prec_dev = pd.merge(df_prec_dev, df_mypf, on= 'Symbol')
  df_prec_dev = pd.merge(df_prec_dev, df_tmp, on= 'Symbol', how='left')
  df_prec_dev = pd.merge(df_prec_dev, df_rs, on= 'Symbol', how='left')
  #print(df_prec_dev.columns)
  df_prec_dev['Curr_PE'] = round(df_prec_dev['Close']/df_prec_dev['EPS'],1)
  df_prec_dev['Dev%_PE'] = round((df_prec_dev['Curr_PE'] - df_prec_dev['MedPE'])*100/df_prec_dev['MedPE'],2)
  df_prec_dev['Conviction'] = df_prec_dev['Conviction'] + '-' + df_prec_dev['CapType']
  return df_prec_dev

# function to arrange stock features
def arrange_features(df_stocks, common_cols, diff_cols):
  df_stocks_common = df_stocks[common_cols].drop_duplicates()
  df_stocks_diff = df_stocks[diff_cols]
  df_stocks_diff['Investment'] = df_stocks_diff['AvgCost'] * df_stocks_diff['Shares']
  df_stocks_diff = df_stocks_diff.groupby(['Symbol'])[['Shares', 'Investment']].aggregate(['sum']).reset_index()
  df_stocks_diff.columns = ['Symbol', 'Shares', 'Investment']
  df_stocks_diff['AvgCost'] = round(df_stocks_diff['Investment']/df_stocks_diff['Shares'],2)
  df_stocks = pd.merge(df_stocks_diff, df_stocks_common, on='Symbol')
  return df_stocks

# plot fact distribution across dimension
def plot_pie_chart(df, dimension, fact):
  # grouping the data by category and calculating the sum of fact for each type
  grouped_data = df.groupby(dimension)[fact].sum()

  # sorting the grouped data in descending order
  grouped_data = grouped_data.sort_values(ascending=False)

  # creating a pie chart
  grouped_data.plot.pie(autopct='%1.1f%%', startangle=90, figsize=(6, 6))

  # adding a title and displaying the plot
  plt.title(f'{dimension} {fact} Distribution')
  plt.ylabel('')  # To hide the y-label
  plt.show()

In [7]:
# function to get portfolio features

def get_portfolio_features(df_common_features):

  print_date_time()
  print('-------------------')

  #df_common_features["Target"] = df_common_features["Target"].fillna(df_common_features["Max"])
  df_common_features['NTT'] = np.where(df_common_features['Strategy']== 'NTT', df_common_features["Target"], df_common_features['Max'])
  df_common_features['LTT'] = np.where(df_common_features['Strategy']== 'BTT', df_common_features["Target"], df_common_features['Max'])
  df_common_features['BOL'] = df_common_features['Min']

  tmp_df = df_common_features[df_common_features['Symbol'].isin(mypf_df[mypf_df['InPortfolio'] != 'NA'].Symbol.values)]
  print('qualified stocks: '+str(len(tmp_df['Symbol'].unique())))
  tmp_df1 = tmp_df[tmp_df['LatestQtr'] == 1]
  print('with latest results: '+str(len(tmp_df1['Symbol'].unique())))
  tmp_df1 = tmp_df1[tmp_df1['StarStock'] == 1]
  print('still star stocks: '+str(len(tmp_df1['Symbol'].unique())))
  tmp_df['Investment'] = tmp_df['AvgCost'] * tmp_df['Shares']
  tmp_df['Current'] = round(tmp_df['Close'] * tmp_df['Shares'],0)
  tmp_df['Previous'] = tmp_df['Prev_Close'] * tmp_df['Shares']
  tmp_df['EstimatedST'] = tmp_df['NTT'] * tmp_df['Shares']
  tmp_df['EstimatedLT'] = tmp_df['LTT'] * tmp_df['Shares']
  tmp_df['Current P/L'] = round((tmp_df['Current'] - tmp_df['Investment']),0)
  tmp_df['Today P/L%'] = round((tmp_df['Current'] - tmp_df['Previous'])*100/tmp_df['Previous'],2)
  tmp_df['Current P/L%'] = round((tmp_df['Current'] - tmp_df['Investment'])*100/tmp_df['Investment'],2)
  tmp_df['EstimatedST P/L%'] = round((tmp_df['EstimatedST'] - tmp_df['Investment'])*100/tmp_df['Investment'],2)
  tmp_df['EstimatedLT P/L%'] = round((tmp_df['EstimatedLT'] - tmp_df['Investment'])*100/tmp_df['Investment'],2)
  tmp_df['NTT%'] = round((tmp_df['NTT'] - tmp_df['Close'])*100/tmp_df['Close'],2)
  tmp_df['LTT%'] = round((tmp_df['LTT'] - tmp_df['Close'])*100/tmp_df['Close'],2)
  tmp_df['Gained%'] = round((tmp_df['Close'] - tmp_df['BOL'])*100/tmp_df['BOL'],2)
  investment = round(sum(tmp_df['AvgCost']*tmp_df['Shares']),0)
  current = round(sum(tmp_df['Close']*tmp_df['Shares']),0)
  tmp_df['InitAlloc%'] = round(tmp_df['Investment']*100/investment,2)
  tmp_df['CurrAlloc%'] = round(tmp_df['Current']*100/current,2)
  tmp_df['FTT'] = tmp_df['LTT']
  tmp_df.loc[tmp_df['Strategy'] == 'NTT', 'FTT'] = tmp_df['NTT']
  tmp_df['FTT%'] = tmp_df['LTT%']
  tmp_df.loc[tmp_df['Strategy'] == 'NTT', 'FTT%'] = tmp_df['NTT%']
  tmp_df['FTT Amt'] = round(tmp_df['FTT%'] * tmp_df['Current']/100,0)
  tmp_df['OTT%'] = round((tmp_df['FTT'] - tmp_df['AvgCost'])*100/tmp_df['AvgCost'],2)
  tmp_df['RRR Ind'] = round(tmp_df['Current P/L']/tmp_df['FTT Amt'],2)
  tmp_df['Risk Ind'] = round(tmp_df['Current P/L%']*tmp_df['CurrAlloc%'],0)

  return tmp_df

# function to print portfolio features
def print_portfolio_stats(df_portfolio_features, myinvmt_df):
  from pyxirr import xirr

  total_booked_amt, reserve_amt, cy_booked_amt, py_booked_amt = get_amt()

  dates = myinvmt_df['Date'].values
  dates = np.append(dates, datetime.date.today().strftime('%d-%b-%y'))
  investment = myinvmt_df['Investment'].values
  dates= pd.to_datetime(dates)

  current = round(sum(df_portfolio_features['Close']*df_portfolio_features['Shares']),0) + reserve_amt
  investment_xirr = np.append(investment, current)
  cagr = round(xirr(pd.DataFrame({"dates": dates, "amounts": investment_xirr}))*100,2)

  investment = -sum(investment)
  invested = round(sum(df_portfolio_features['AvgCost']*df_portfolio_features['Shares']),0) + reserve_amt
  previous = round(sum(df_portfolio_features['Prev_Close']*df_portfolio_features['Shares']),0) + reserve_amt
  cy_invested = investment + py_booked_amt

  today_pnl_amount = current-previous
  today_pnl_percentage = round((current-previous)*100/previous,2)

  curr_pnl_amount = current-invested
  curr_pnl_percentage = round((curr_pnl_amount)*100/(cy_invested),2)

  cy_pnl_amount = cy_booked_amt + curr_pnl_amount
  cy_pnl_percentage = round((cy_pnl_amount)*100/cy_invested,2)

  overall_pnl_amount = total_booked_amt + curr_pnl_amount
  overall_pnl_percentage = round((overall_pnl_amount)*100/investment,2)

  estimate_st = round(sum(df_portfolio_features['FTT']*df_portfolio_features['Shares']),0)  + reserve_amt
  est_st_pnl_amount = estimate_st-current
  est_st_pnl_percentage = round((est_st_pnl_amount)*100/current,2)

  estimate_lt = round(sum(df_portfolio_features['LTT']*df_portfolio_features['Shares']),0)  + reserve_amt
  est_lt_pnl_amount = estimate_lt-current
  est_lt_pnl_percentage = round((est_lt_pnl_amount)*100/current,2)

  total_profit = round(sum(df_portfolio_features[df_portfolio_features['Current P/L%'] > 0]['Current']) - sum(df_portfolio_features[df_portfolio_features['Current P/L%'] > 0]['Investment']),0)
  total_loss = round(sum(df_portfolio_features[df_portfolio_features['Current P/L%'] < 0]['Current']) - sum(df_portfolio_features[df_portfolio_features['Current P/L%'] < 0]['Investment']),0)

  cy_booked_percentage = round((cy_booked_amt)*100/current,2)
  py_booked_percentage = round((py_booked_amt)*100/investment,2)
  total_booked_percentage = round((total_booked_amt)*100/investment,2)

  print('-------------------')
  print('Initial Investment: ', format_amt(investment))
  print('CY Investment: ', format_amt(cy_invested))
  print('Reserve: ', format_amt(reserve_amt))
  print('Current: ',  format_amt(current))
  print('-------------------')
  print('Today PnL: '+ '{} ({}%)'.format(format_amt(today_pnl_amount), today_pnl_percentage))
  print('Current PnL: '+ '{} ({}%)'.format(format_amt(curr_pnl_amount), curr_pnl_percentage))
  print('CY Booked + Current PnL: '+ '{} ({}%)'.format(format_amt(cy_pnl_amount), cy_pnl_percentage))
  print('-------------------')
  print('Total profit: ', format_amt(total_profit))
  print('Total loss: ', format_amt(total_loss))
  print('-------------------')
  print('Total Booked + Current PnL: '+ '{} ({}%)'.format(format_amt(overall_pnl_amount), overall_pnl_percentage))
  print('Total Booked PnL: '+ '{} ({}%)'.format(format_amt(total_booked_amt), total_booked_percentage))
  print('Curr Year Booked PnL: '+ '{} ({}%)'.format(format_amt(cy_booked_amt), cy_booked_percentage))
  print('Prev Year Booked PnL: '+ '{} ({}%)'.format(format_amt(py_booked_amt), py_booked_percentage))
  print('===================')
  print('Est FTT: ',  format_amt(estimate_st))
  print('Est FTT PnL: '+ '{} ({}%)'.format(format_amt(est_st_pnl_amount), est_st_pnl_percentage))

  print('===================')
  print('Deployed: ', format_amt(investment))

  print('Current: ', format_amt(current))

  print('CAGR/XIRR %: '+'{}%'.format(cagr))

In [8]:
# get start and end date
start_date, end_date = get_start_end_date()

# get portfolio and prospects data
mypfs_df = get_mypfs_df()
mypps_df = get_mypps_df()
myinvmt_df = get_myinvmt_df()

# merge above datasets
mypf_df = pd.merge(mypfs_df, mypps_df, on="Symbol")

# seggregate dm and sv portfolio
dm_pf = mypf_df[mypf_df['InPortfolio'] == 'DM']
sv_pf = mypf_df[mypf_df['InPortfolio'] == 'SV']

# build portfolio stock dataframe
dm_stocks = get_stock_ids(dm_pf)
sv_stocks = get_stock_ids(sv_pf)
df_stocks = pd.concat([dm_pf,sv_pf], ignore_index = True)

# arrange common and diff stock features
common_cols = ['Symbol', 'Target', 'Criteria', 'Strategy', 'CumlRnk', 'LatestQtr', 'StarStock', 'Conviction', 'Category', 'InFolio', 'XIRR', 'MBQ']
diff_cols = ['Symbol', 'AvgCost', 'Shares']
df_stocks = arrange_features(df_stocks, common_cols, diff_cols)

# get common features
stock_ids = df_stocks['Symbol'].values
df_common_features = get_common_features(stock_ids, df_stocks)

df_common_features.reset_index(drop=True, inplace=True)
df_common_features.drop(['Date'], axis=1, inplace=True)
# get and print portfolio features
df_portfolio_features = get_portfolio_features(df_common_features)

print_portfolio_stats(df_portfolio_features, myinvmt_df)

df = df_portfolio_features
#plot_pie_chart(df, 'CapType', 'Current')
list_ox40n = list(df[df['MBQ'].str.contains('OX40N', na=False)]['Symbol'].values)

Run date time (IST): 2026-07-02 11:29:03
-------------------
qualified stocks: 92
with latest results: 31
still star stocks: 20
-------------------
Initial Investment:  1.40 C
CY Investment:  1.82 C
Reserve:  1.49 K
Current:  1.53 C
-------------------
Today PnL: 98.34 K (0.65%)
Current PnL: -30.21 L (-16.57%)
CY Booked + Current PnL: -28.13 L (-15.43%)
-------------------
Total profit:  4.83 L
Total loss:  -35.04 L
-------------------
Total Booked + Current PnL: 14.74 L (10.56%)
Total Booked PnL: 44.95 L (32.22%)
Curr Year Booked PnL: 2.08 L (1.36%)
Prev Year Booked PnL: 42.87 L (30.73%)
===================
Est FTT:  2.55 C
Est FTT PnL: 1.02 C (66.71%)
===================
Deployed:  1.40 C
Current:  1.53 C
CAGR/XIRR %: 4.24%

In [9]:
# top 5 near their targets
cols = ['Symbol', 'Today P/L%', 'Current P/L%', 'FTT%', 'OTT%', 'FTT Amt', 'Current P/L', 'Current', 'FTT', 'Dev%_PE', 'RSI_14','Conviction', 'Spread%',  'CumlRnk', 'RRR Ind', 'CurrAlloc%', 'Gained%', 'Criteria', 'Strategy', 'Category']
df_tmp = df_portfolio_features[~df_portfolio_features['Symbol'].isin(['ENRIN','BLUSPRING','DIGITIDE'])]
df_tmp = df_tmp.sort_values(by = 'FTT Amt', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
59,PIDILITIND,1.13,13.37,4.40,18.37,7039.0,18870.0,159980.0,1670.26,-20.60,70.0,X-LC,6.45,5.0,2.68,1.05,25.61,X40,ATH,CHEMICALS
49,JSWINFRA,-0.77,11.63,4.30,16.43,10645.0,25790.0,247564.0,342.00,-4.38,67.0,X-MC,9.18,61.0,2.42,1.62,40.36,X40N,NTT,REALTY
83,TTKPRESTIG,1.97,-16.44,19.78,0.09,16657.0,-16564.0,84213.0,770.00,95.52,80.0,M-SC,6.40,250.0,-0.99,0.55,49.95,OX40N,NTT,DURABLES
51,KOTAKBANK,-0.61,6.35,13.88,21.11,20440.0,8788.0,147260.0,453.24,-8.97,52.0,X-LC,4.44,12.0,0.43,0.96,12.62,X40,ATH,BANKS
56,MEDANTA,1.10,14.85,10.68,27.12,21652.0,26216.0,202733.0,1486.00,11.29,73.0,X-SC,6.35,87.0,1.21,1.33,39.69,XY24,NTT,HEALTHCARE

In [10]:
# top 5 today
df_tmp = df_portfolio_features.sort_values(by = 'Today P/L%', ascending=False)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
43,INDIGOPNTS,5.62,-23.25,30.32,0.02,40620.0,-40589.0,133970.0,1408.00,104.24,69.0,M-SC,5.77,222.0,-1.00,0.88,52.00,OX40N,NTT,PAINTS
45,INFY,5.38,-29.32,89.93,34.24,198887.0,-91730.0,221158.0,1972.00,-44.48,41.0,X-LC,20.06,3.0,-0.46,1.45,5.38,X40,NTT,IT
61,RAJESHEXPO,4.99,-82.29,465.01,0.07,112974.0,-112882.0,24295.0,518.00,790.15,44.0,L-SC,38.82,268.0,-1.00,0.16,19.98,OX40N,NTT,JEWELLERY
73,SONACOMS,4.74,12.23,23.57,38.69,26759.0,12372.0,113531.0,801.69,-11.02,73.0,M-MC,18.02,193.0,0.46,0.74,61.07,AR,ATH,AUTO
33,HCLTECH,4.35,-29.96,73.49,21.51,124517.0,-72490.0,169434.0,1872.35,-26.39,39.0,X-LC,20.34,8.0,-0.58,1.11,4.35,X40,ATH,IT

In [11]:
# bottom 5 today
df_tmp = df_portfolio_features.sort_values(by = 'Today P/L%', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
23,DMART,-2.97,0.96,28.37,29.60,71492.0,2400.0,252000.0,5391.45,-14.87,46.0,X-LC,3.88,14.0,0.03,1.65,15.19,X40N,ATH,FMCG
27,GLAXO,-2.03,-3.06,39.98,35.69,77232.0,-6108.0,193176.0,3380.16,-25.91,63.0,X-MC,6.47,56.0,-0.08,1.26,14.81,X40,ATH,PHARMA
57,PAGEIND,-1.66,11.85,19.43,33.59,58328.0,31816.0,300195.0,51217.29,-19.73,69.0,X-MC,7.73,55.0,0.55,1.96,42.56,X40,ATH,APPARELS
80,TITAGARH,-1.50,-17.41,76.45,45.74,152918.0,-42153.0,200024.0,1548.00,10.09,53.0,H-SC,9.18,175.0,-0.28,1.31,52.61,XY24,NTT,ENGINEERING
19,COLPAL,-1.42,-22.45,80.35,39.86,164107.0,-59125.0,204240.0,3683.41,-6.07,52.0,X-MC,3.60,62.0,-0.36,1.34,15.53,XY25,ATH,FMCG

In [12]:
# top 5 to exit based on CumlRnk
df_tmp = df_portfolio_features[~df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])]
df_tmp = df_tmp[(df_tmp['Current P/L%'] > -1) & (df_tmp['Current P/L%'] < 1)].sort_values(by = 'CumlRnk', ascending=False)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
63,RECLTD,-0.57,-0.38,21.2,20.74,42909.0,-770.0,202400.0,446.0,9.37,61.0,M-MC,1.75,191.0,-0.02,1.32,20.62,XY25,NTT,FINANCE

In [13]:
# OX40N stocks to exit
df_tmp = df_portfolio_features[(df_portfolio_features['Symbol'].isin(list_ox40n))].sort_values(by = 'Current P/L%', ascending=False)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
25,FINCABLES,0.03,45.00,43.39,107.91,92888.0,66434.0,214078.0,1641.55,30.39,56.0,M-SC,26.30,220.0,0.72,1.40,61.06,OX40N,ATH,CABLES
72,SIS,1.24,-2.28,24.09,21.26,26138.0,-2530.0,108502.0,528.00,2588.60,54.0,H-SC,25.17,168.0,-0.10,0.71,61.33,OX40N,NTT,MISC
16,CERA,1.16,-14.80,45.41,23.89,68055.0,-26035.0,149868.0,9475.00,-17.90,66.0,H-SC,11.66,153.0,-0.38,0.98,44.02,OX40N,NTT,CERAMICS
83,TTKPRESTIG,1.97,-16.44,19.78,0.09,16657.0,-16564.0,84213.0,770.00,95.52,80.0,M-SC,6.40,250.0,-0.99,0.55,49.95,OX40N,NTT,DURABLES
43,INDIGOPNTS,5.62,-23.25,30.32,0.02,40620.0,-40589.0,133970.0,1408.00,104.24,69.0,M-SC,5.77,222.0,-1.00,0.88,52.00,OX40N,NTT,PAINTS

In [14]:
# top 5 to book for rotation
df_tmp = df_portfolio_features[(df_portfolio_features['Current P/L%'] > 20) ].sort_values(by = 'CumlRnk', ascending=False)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
25,FINCABLES,0.03,45.0,43.39,107.91,92888.0,66434.0,214078.0,1641.55,30.39,56.0,M-SC,26.30,220.0,0.72,1.40,61.06,OX40N,ATH,CABLES
68,SATIN,2.48,42.9,6.25,51.83,24676.0,118530.0,394814.0,274.00,27.46,68.0,H-SC,41.88,159.0,4.80,2.58,92.33,XY24,NTT,FINANCE

In [15]:
# top 5 to monitor for exit
df_tmp = df_portfolio_features[~df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])]
df_tmp = df_tmp[(df_tmp['Current P/L%'] > 0) ].sort_values(by = 'Dev%_PE', ascending=False)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
75,SURYODAY,2.94,4.67,17.55,23.03,32893.0,8354.0,187425.0,216.00,103.95,69.0,H-SC,20.20,166.0,0.25,1.23,57.81,XR,NTT,BANKS
74,STARHEALTH,0.55,14.17,28.98,47.26,93014.0,39837.0,320960.0,761.00,80.11,74.0,H-SC,14.48,173.0,0.43,2.10,40.85,XY24,NTT,INSURANCE
25,FINCABLES,0.03,45.00,43.39,107.91,92888.0,66434.0,214078.0,1641.55,30.39,56.0,M-SC,26.30,220.0,0.72,1.40,61.06,OX40N,ATH,CABLES
68,SATIN,2.48,42.90,6.25,51.83,24676.0,118530.0,394814.0,274.00,27.46,68.0,H-SC,41.88,159.0,4.80,2.58,92.33,XY24,NTT,FINANCE
91,ZYDUSLIFE,-0.66,16.20,16.72,35.63,40717.0,33946.0,243520.0,1286.17,1.35,58.0,H-MC,14.23,120.0,0.83,1.59,28.04,AR,ATH,PHARMA

In [16]:
# top 5 to book for rotation from weak conviction
df_tmp = df_portfolio_features[~df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])]
df_tmp = df_tmp[~df_tmp['Criteria'].isin(['XY25','XY24','X40', 'X40N'])].sort_values(by = 'RRR Ind', ascending=False)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
91,ZYDUSLIFE,-0.66,16.20,16.72,35.63,40717.0,33946.0,243520.0,1286.17,1.35,58.0,H-MC,14.23,120.0,0.83,1.59,28.04,AR,ATH,PHARMA
25,FINCABLES,0.03,45.00,43.39,107.91,92888.0,66434.0,214078.0,1641.55,30.39,56.0,M-SC,26.30,220.0,0.72,1.40,61.06,OX40N,ATH,CABLES
73,SONACOMS,4.74,12.23,23.57,38.69,26759.0,12372.0,113531.0,801.69,-11.02,73.0,M-MC,18.02,193.0,0.46,0.74,61.07,AR,ATH,AUTO
75,SURYODAY,2.94,4.67,17.55,23.03,32893.0,8354.0,187425.0,216.00,103.95,69.0,H-SC,20.20,166.0,0.25,1.23,57.81,XR,NTT,BANKS
72,SIS,1.24,-2.28,24.09,21.26,26138.0,-2530.0,108502.0,528.00,2588.60,54.0,H-SC,25.17,168.0,-0.10,0.71,61.33,OX40N,NTT,MISC

In [17]:
# top 5 to accumulate based on lowest RSI_14
df_tmp = df_portfolio_features[df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])].sort_values(by = 'RSI_14', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
33,HCLTECH,4.35,-29.96,73.49,21.51,124517.0,-72490.0,169434.0,1872.35,-26.39,39.0,X-LC,20.34,8.0,-0.58,1.11,4.35,X40,ATH,IT
81,TMPV,-0.50,-21.23,73.39,36.58,205712.0,-75541.0,280300.0,600.00,-83.62,39.0,X-LC,7.97,4.0,-0.37,1.83,17.80,XY24,NTT,AUTO
79,TCS,3.49,-39.77,107.33,24.88,299499.0,-184228.0,279045.0,4253.91,-48.87,39.0,X-LC,21.59,2.0,-0.62,1.82,3.49,X40,ATH,IT
1,ABBOTINDIA,0.23,-14.09,37.43,18.07,57515.0,-25195.0,153660.0,35195.00,-26.90,41.0,X-MC,6.63,58.0,-0.44,1.00,1.71,X40,ATH,PHARMA
45,INFY,5.38,-29.32,89.93,34.24,198887.0,-91730.0,221158.0,1972.00,-44.48,41.0,X-LC,20.06,3.0,-0.46,1.45,5.38,X40,NTT,IT

In [18]:
# top 5 to accumulate based on Spread and CumlRnk
df_tmp = df_portfolio_features[df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])]
df_tmp = df_tmp[(df_tmp['CumlRnk'] < 100)].sort_values(by = 'Spread%', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
17,CIPLA,0.23,18.20,12.89,33.43,23336.0,27879.0,181040.0,1648.14,-8.67,68.0,X-LC,2.19,18.0,1.19,1.18,23.59,X40N,ATH,PHARMA
11,BERGEPAINT,0.34,-4.71,31.50,25.32,77371.0,-12127.0,245622.0,680.00,-9.89,50.0,X-MC,2.89,68.0,-0.16,1.61,27.84,XY24,NTT,PAINTS
84,UNITDSPR,0.85,0.19,20.54,20.77,48185.0,447.0,234591.0,1644.00,-11.09,60.0,X-MC,3.16,64.0,0.01,1.53,11.91,X40N,NTT,BREWERIES
19,COLPAL,-1.42,-22.45,80.35,39.86,164107.0,-59125.0,204240.0,3683.41,-6.07,52.0,X-MC,3.60,62.0,-0.36,1.34,15.53,XY25,ATH,FMCG
23,DMART,-2.97,0.96,28.37,29.60,71492.0,2400.0,252000.0,5391.45,-14.87,46.0,X-LC,3.88,14.0,0.03,1.65,15.19,X40N,ATH,FMCG

In [19]:
# top 5 to accumulate based on lowest Gained%
df_tmp = df_portfolio_features[df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])].sort_values(by = 'Gained%', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
58,PGHH,-0.21,-33.01,97.06,32.01,138835.0,-70480.0,143040.0,17616.87,-54.64,41.0,X-MC,20.97,57.0,-0.51,0.94,1.44,X40,ATH,FMCG
1,ABBOTINDIA,0.23,-14.09,37.43,18.07,57515.0,-25195.0,153660.0,35195.00,-26.90,41.0,X-MC,6.63,58.0,-0.44,1.00,1.71,X40,ATH,PHARMA
65,RELIANCE,-0.47,-16.44,49.95,25.30,83882.0,-33031.0,167932.0,1952.00,-18.49,46.0,X-LC,7.87,21.0,-0.39,1.10,3.42,XY25,BTT,REFINERIES
79,TCS,3.49,-39.77,107.33,24.88,299499.0,-184228.0,279045.0,4253.91,-48.87,39.0,X-LC,21.59,2.0,-0.62,1.82,3.49,X40,ATH,IT
33,HCLTECH,4.35,-29.96,73.49,21.51,124517.0,-72490.0,169434.0,1872.35,-26.39,39.0,X-LC,20.34,8.0,-0.58,1.11,4.35,X40,ATH,IT

In [20]:
# top 5 to accumulate based on lowest CurrAlloc%
df_tmp = df_portfolio_features[df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])].sort_values(by = 'CurrAlloc%', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
10,BATAINDIA,1.96,-55.14,201.37,35.20,116243.0,-70944.0,57726.0,2096.00,-24.33,49.0,X-SC,20.52,91.0,-0.61,0.38,14.49,X40,NTT,FOOTWEAR
64,RELAXO,-0.62,-47.23,188.62,52.31,144485.0,-68559.0,76601.0,1176.00,-43.86,70.0,X-SC,11.03,92.0,-0.47,0.50,71.27,X40N,NTT,FOOTWEAR
60,QUESS,3.69,16.27,49.56,73.90,61540.0,17380.0,124173.0,424.00,-37.74,84.0,X-SC,17.91,80.0,0.28,0.81,69.27,XY24,NTT,MISC
53,M&M,0.67,1.16,20.68,22.08,29012.0,1611.0,140292.0,3762.31,-14.09,55.0,X-LC,9.33,25.0,0.06,0.92,7.50,X40N,ATH,AUTO
35,HDFCLIFE,0.24,-6.56,42.03,32.71,58829.0,-9832.0,139968.0,811.41,-27.10,42.0,X-LC,16.12,31.0,-0.17,0.92,5.15,X40,ATH,INSURANCE

In [21]:
# top 5 to accumulate based on CumlRnk
df_tmp = df_portfolio_features.sort_values(by = 'CumlRnk', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
47,ITC,-0.41,-23.85,56.35,19.06,145966.0,-81132.0,259034.0,452.00,-58.35,49.0,X-LC,13.61,1.0,-0.56,1.69,4.37,X40,NTT,FMCG
79,TCS,3.49,-39.77,107.33,24.88,299499.0,-184228.0,279045.0,4253.91,-48.87,39.0,X-LC,21.59,2.0,-0.62,1.82,3.49,X40,ATH,IT
45,INFY,5.38,-29.32,89.93,34.24,198887.0,-91730.0,221158.0,1972.00,-44.48,41.0,X-LC,20.06,3.0,-0.46,1.45,5.38,X40,NTT,IT
81,TMPV,-0.50,-21.23,73.39,36.58,205712.0,-75541.0,280300.0,600.00,-83.62,39.0,X-LC,7.97,4.0,-0.37,1.83,17.80,XY24,NTT,AUTO
59,PIDILITIND,1.13,13.37,4.40,18.37,7039.0,18870.0,159980.0,1670.26,-20.60,70.0,X-LC,6.45,5.0,2.68,1.05,25.61,X40,ATH,CHEMICALS

In [22]:
# top 5 for average up
df_tmp = df_portfolio_features[(df_portfolio_features['Dev%_200'] > 5)].sort_values(by = 'CurrAlloc%', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
44,INDUSINDBK,-0.43,-30.78,91.99,32.89,49159.0,-23766.0,53440.0,1800.00,-351.40,57.0,L-MC,7.14,258.0,-0.48,0.35,31.75,XR,NTT,BANKS
64,RELAXO,-0.62,-47.23,188.62,52.31,144485.0,-68559.0,76601.0,1176.00,-43.86,70.0,X-SC,11.03,92.0,-0.47,0.50,71.27,X40N,NTT,FOOTWEAR
3,ALKYLAMINE,3.29,-22.32,147.85,92.54,115962.0,-22531.0,78432.0,4520.85,-16.74,57.0,H-SC,8.58,142.0,-0.19,0.51,48.94,SR,ATH,CHEMICALS
83,TTKPRESTIG,1.97,-16.44,19.78,0.09,16657.0,-16564.0,84213.0,770.00,95.52,80.0,M-SC,6.40,250.0,-0.99,0.55,49.95,OX40N,NTT,DURABLES
72,SIS,1.24,-2.28,24.09,21.26,26138.0,-2530.0,108502.0,528.00,2588.60,54.0,H-SC,25.17,168.0,-0.10,0.71,61.33,OX40N,NTT,MISC

In [23]:
# top 5 RSP
df_tmp = df_portfolio_features.sort_values(by = 'RSP', ascending=False)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
60,QUESS,3.69,16.27,49.56,73.90,61540.0,17380.0,124173.0,424.0,-37.74,84.0,X-SC,17.91,80.0,0.28,0.81,69.27,XY24,NTT,MISC
69,SFL,2.51,-25.68,70.37,26.63,137146.0,-67325.0,194893.0,1287.0,47.69,71.0,M-SC,18.14,242.0,-0.49,1.27,62.43,XY24,NTT,MISC
64,RELAXO,-0.62,-47.23,188.62,52.31,144485.0,-68559.0,76601.0,1176.0,-43.86,70.0,X-SC,11.03,92.0,-0.47,0.50,71.27,X40N,NTT,FOOTWEAR
83,TTKPRESTIG,1.97,-16.44,19.78,0.09,16657.0,-16564.0,84213.0,770.0,95.52,80.0,M-SC,6.40,250.0,-0.99,0.55,49.95,OX40N,NTT,DURABLES
49,JSWINFRA,-0.77,11.63,4.30,16.43,10645.0,25790.0,247564.0,342.0,-4.38,67.0,X-MC,9.18,61.0,2.42,1.62,40.36,X40N,NTT,REALTY

In [24]:
# Top N allocation
df_tmp = df_portfolio_features.sort_values(by = 'CurrAlloc%', ascending=False)
top_n_values = [10, 25, 50]

sum_df = pd.DataFrame({
    'Top_N': top_n_values,
    'Sum_Alloc%': [df_tmp['CurrAlloc%'].head(n).sum() for n in top_n_values]
})

sum_df

   Top_N  Sum_Alloc%
0     10       19.52
1     25       42.67
2     50       72.85

In [25]:
# market-cap-wise allocation
df_tmp = df_portfolio_features[cols]
df_tmp.groupby(df_tmp['Conviction'].str[-2:])['CurrAlloc%'].sum().sort_values(ascending=False)

Conviction
SC    43.92
LC    30.26
MC    25.85
Name: CurrAlloc%, dtype: float64

In [26]:
# criteria-wise allocation
df_portfolio_features.groupby('Criteria')['CurrAlloc%'].sum().sort_values(ascending=False)

Criteria
XY24     28.06
X40      24.45
X40N     17.43
XR        8.85
OX40N     7.23
AR        6.69
XY25      6.45
SR        0.87
Name: CurrAlloc%, dtype: float64

In [27]:
# conviction-wise allocation
df_portfolio_features.groupby('Conviction')['CurrAlloc%'].sum().sort_values(ascending=False)

Conviction
X-LC    28.30
H-SC    23.01
X-MC    20.77
M-SC    10.24
X-SC    10.10
H-MC     2.67
M-MC     2.06
H-LC     1.17
M-LC     0.79
L-SC     0.57
L-MC     0.35
Name: CurrAlloc%, dtype: float64

In [28]:
# sector-wise stats
df_tmp = df_portfolio_features.groupby('Category')[['CurrAlloc%', 'Current', 'Current P/L', 'FTT Amt']].sum().sort_values(by=['Current', 'Current P/L'], ascending=False)
df_tmp['Current P/L%'] = round(df_tmp['Current P/L'] * 100 / df_tmp['Current'], 2)
df_tmp['FTT%'] = round(df_tmp['FTT Amt'] * 100 / df_tmp['Current'], 2)
cols = ['CurrAlloc%', 'Current P/L%', 'FTT%']
df_tmp[cols].sort_values(by=['CurrAlloc%'], ascending=False)

               CurrAlloc%  Current P/L%    FTT%
Category
FMCG                14.54        -19.08   60.86
FINANCE             11.41         -5.69   51.48
IT                   9.39        -56.81  135.22
MISC                 7.20        -21.57   73.73
AUTO                 6.65         -7.66   47.80
BANKS                5.81         -2.27   49.55
PAINTS               5.56        -16.02   35.81
INSURANCE            5.30         -2.36   36.89
PHARMA               5.03          3.96   25.77
ELECTRICAL           4.09        -12.91   52.75
CHEMICALS            2.18        -21.60   93.74
HEALTHCARE           2.12        -10.67   39.56
APPARELS             1.96         10.60   19.43
AC                   1.76        -19.11   51.40
FOOTWEAR             1.75        -65.52  131.89
DURABLES             1.63        -55.17   92.92
REALTY               1.62         10.42    4.30
TRAVEL               1.54        -90.65  186.12
BREWERIES            1.53          0.19   20.54
CERAMICS             1.44        -39.04   81.28
CABLES               1.40         31.03   43.39
ENGINEERING          1.31        -21.07   76.45
REFINERIES           1.10        -19.67   49.95
CEMENT               1.07        -64.27  187.16
JEWELLERY            1.04       -101.76  171.86
ENTERTAINMENT        0.76        -66.92  166.48
TEXTILES             0.43        -39.16   78.84
HOTELS               0.41        -81.97  146.15

In [29]:
# money to be made criteria-wise
df_portfolio_features.groupby('Criteria')['FTT Amt'].agg(['sum', 'count']).sort_values(by='sum', ascending=False)

                sum  count
Criteria
XY24      3308614.0     21
X40       1937996.0     19
XR        1329811.0     13
AR        1151236.0      9
X40N      1052947.0     13
OX40N      687441.0     10
XY25       450571.0      5
SR         284675.0      2

In [30]:
# money to be made conviction-wise
df_portfolio_features.groupby('Conviction')['FTT Amt'].agg(['sum', 'count']).sort_values(by='sum', ascending=False)

                  sum  count
Conviction
H-SC        3259052.0     24
X-LC        1954299.0     21
X-MC        1541442.0     15
M-SC        1352531.0     14
X-SC        1257728.0      9
H-MC         289852.0      2
L-SC         204172.0      2
M-LC         170990.0      1
M-MC          69668.0      2
H-LC          54398.0      1
L-MC          49159.0      1

In [31]:
# money to be made criteria and conviction-wise
df_portfolio_features.groupby(['Conviction', 'Criteria'])['FTT Amt'].agg(['sum', 'count']).sort_values(by='sum', ascending=False)

                           sum  count
Conviction Criteria
X-LC       X40       1060669.0     10
H-SC       AR         956753.0      5
           XY24       926870.0      6
M-SC       XY24       810652.0      6
H-SC       XR         799095.0      7
X-SC       XY24       752439.0      4
X-MC       X40        660285.0      7
           X40N       413797.0      4
X-LC       XY24       352238.0      2
           X40N       350903.0      6
H-SC       OX40N      291659.0      4
X-SC       X40N       288247.0      3
H-SC       SR         284675.0      2
M-SC       OX40N      282808.0      5
X-MC       XY25       250080.0      2
H-MC       XY24       249135.0      1
X-MC       XY24       217280.0      2
X-SC       X40        217042.0      2
M-SC       XR         186462.0      2
M-LC       XR         170990.0      1
X-LC       XY25       157582.0      2
L-SC       OX40N      112974.0      1
           XR          91198.0      1
M-SC       AR          72609.0      1
H-LC       AR          54398.0      1
L-MC       XR          49159.0      1
M-MC       XY25        42909.0      1
H-MC       AR          40717.0      1
X-LC       XR          32907.0      1
M-MC       AR          26759.0      1

In [32]:
# notebook execution time

end_time = time.time()
execution_time = round(end_time - start_time, 0)
print(f"Notebook execution time: {execution_time} seconds")

Notebook execution time: 31.0 seconds