<a href="https://colab.research.google.com/github/ankit-rathi/Quantvesting_v2/blob/main/myStocks_Portfolio_Analysis.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
'''
!pip install pandas==2.2.2 -qq
!pip install pyxirr -qq
!pip install ta -qq
!pip install yfinance==0.2.59 -qq
'''

'\n!pip install pandas==2.2.2 -qq\n!pip install pyxirr -qq\n!pip install ta -qq\n!pip install yfinance==0.2.59 -qq\n'

In [2]:
# import libraries

import numpy as np
import pandas as pd
import datetime
import warnings
warnings.filterwarnings('ignore')
import yfinance as yfin
import ta
import matplotlib.pyplot as plt
import requests

In [3]:
# notebook start time
import time
import datetime
import pytz

start_time = time.time()

# function to print date timestamp
def print_date_time():
  tz_NY = pytz.timezone('Asia/Kolkata')
  datetime_NY = datetime.datetime.now(tz_NY)
  print("Run date time (IST):", datetime_NY.strftime("%Y-%m-%d %H:%M:%S"))

In [4]:
# function to get booked and reserved amount
def get_amt():
  # fetch the JSON data from the URL
  url = "https://raw.githubusercontent.com/ankit-rathi/Tradevesting_v1/main/data/myPortfolioAmts.json"
  response = requests.get(url)
  pf_amts = response.json()  # parse the JSON data

  # extract values from the JSON
  py_booked_amt_dm = pf_amts["py_booked_amt_dm"]
  py_booked_amt_sv = pf_amts["py_booked_amt_sv"]
  cy_booked_amt_dm = pf_amts["cy_booked_amt_dm"]
  cy_booked_amt_sv = pf_amts["cy_booked_amt_sv"]
  reserve_amt_dm = pf_amts["reserve_amt_dm"]
  reserve_amt_sv = pf_amts["reserve_amt_sv"]

  # perform calculations
  py_booked_amt = py_booked_amt_dm + py_booked_amt_sv
  cy_booked_amt = cy_booked_amt_dm + cy_booked_amt_sv
  reserve_amt = reserve_amt_dm + reserve_amt_sv
  total_booked_amt = py_booked_amt + cy_booked_amt

  return total_booked_amt, reserve_amt, cy_booked_amt, py_booked_amt

gen_output = 0

In [5]:
# function to format the amount
def format_amt(number):
    abs_number = abs(number)

    if abs_number >= 1_00_00_000:  # Crores
        formatted_amt = f"{number / 1_00_00_000:.2f} C"
    elif abs_number >= 1_00_000:  # Lakhs
        formatted_amt = f"{number / 1_00_000:.2f} L"
    elif abs_number >= 1_000:  # Thousands
        formatted_amt = f"{number / 1_000:.2f} K"
    else:
        formatted_amt = f"{number:.2f}"

    return formatted_amt

# function to set start and end date
def get_start_end_date():
  start_date = (datetime.date.today() + datetime.timedelta(days=-365)).strftime('%Y-%m-%d')
  end_date = (datetime.date.today() + datetime.timedelta(days=1)).strftime('%Y-%m-%d')
  return start_date, end_date

# function to fetch my portfolio csv
def get_mypfs_df():
  mypfs_df = pd.read_csv('https://raw.githubusercontent.com/ankit-rathi/Tradevesting_v1/main/data/myPortfolioStocks.csv')
  return mypfs_df

# function to fetch my prospects csv
def get_mypps_df():
  mypps_df = pd.read_csv('https://raw.githubusercontent.com/ankit-rathi/Tradevesting_v1/main/data/myProspectsScrips.csv')
  return mypps_df

# function to fetch screener data
def get_myscreen_df():
  myscreen_df = pd.read_csv('https://raw.githubusercontent.com/ankit-rathi/Tradevesting_v1/main/data/myScreenerDB.csv')
  return myscreen_df

# function to fetch momentum data
def get_myinvmt_df():
  myinvmt_df = pd.read_csv('https://raw.githubusercontent.com/ankit-rathi/Tradevesting_v1/main/data/myInvestments.csv')
  return myinvmt_df

# function to get the stock ids
def get_stock_ids(df_pf):
  stock_n100 = df_pf['Symbol'].unique()

  exclude = ['CADILAHC','MMTC', 'MASFIN']

  stock_ids = df_pf[~df_pf['Symbol'].isin(exclude) ]['Symbol'].unique()

  #mypf = mypf[mypf.Forecast.notnull()]
  #stock_ids = mypf['Symbol'].unique()

  #stock_ids.sort()
  return stock_ids

# get features from screener data
def get_screener_features():
  myscreen_df = get_myscreen_df()
  cols = ['Symbol', 'EPS', 'MedPE', 'ROCE%', 'ROE%', 'CapType']
  return myscreen_df[cols]

# get relative strength
def get_relative_strength(stock_list):

    # Dictionary to store stock tickers and their corresponding percentage price change
    stock_changes = {}

    # Loop through each stock and fetch its price data
    for stock in stock_list:
        try:
            # Download the stock data for the given date range
            stock_data = yfin.Ticker(stock + '.NS').history(period='1mo', interval='1d')[map(str.title, ['open', 'close', 'low', 'high', 'volume'])]

            # Calculate the percentage change for the stock
            if len(stock_data) > 0:
                start_price = stock_data['Close'].iloc[0]
                end_price = stock_data['Close'].iloc[-1]
                percent_change = round(((end_price - start_price) / start_price) * 100, 2)
                stock_changes[stock] = percent_change
            else:
                stock_changes[stock] = np.nan  # If no data is available, set to NaN

        except Exception as e:
            print(f"Error fetching data for {stock}: {e}")
            stock_changes[stock] = np.nan

    # Create a DataFrame with stock tickers and their percentage changes
    df = pd.DataFrame(list(stock_changes.items()), columns=['Symbol', 'Percent_Change'])

    # Drop any stocks with missing data (NaN values)
    df = df.dropna()

    # Calculate the percentile rank based on percentage change
    df['RSP'] = round(df['Percent_Change'].rank(pct=True) * 100, 2)
    cols = ['Symbol', 'RSP']
    df = df[cols]
    # Sort by percentile rank (optional)
    df = df.sort_values(by='RSP', ascending=False).reset_index(drop=True)

    return df

In [6]:
# function to get stock technicals
def stock_prec_dev(stock_symbol):
    #stock_symbol = 'ULTRACEMCO.NS'
    short_window = 20
    mid_window = 50
    long_window = 200
    moving_avg = 'SMA'

    start = datetime.datetime(*map(int, start_date.split('-')))
    end = datetime.datetime(*map(int, end_date.split('-')))

    stock_df = yfin.Ticker(stock_symbol + '.NS').history(period='max', interval='1d')[map(str.title, ['open', 'close', 'low', 'high', 'volume'])]

    stock_df['Max'] = round(max(stock_df['Close']),2)
    stock_df = stock_df[(stock_df.index <= end_date) & (stock_df.index >= start_date)]
    stock_df['200_SMA'] = round(stock_df['Close'].rolling(window = 200, min_periods = 1).mean(),0)
    stock_df['Dev%_200'] = round((stock_df['Close'] - stock_df['200_SMA'])*100/stock_df['200_SMA'],2)
    stock_df.dropna(axis = 0, inplace = True) # remove any null rows

    stock_df['20_SMA'] = stock_df['Close'].rolling(window=20).mean()
    stock_df['50_SMA'] = stock_df['Close'].rolling(window=50).mean()
    stock_df['Symbol'] = stock_symbol

    stock_df['Close'] = round(stock_df['Close'],2)
    stock_df['Min'] = round(min(stock_df['Close']),2)
    stock_df['RSI_14'] = ta.momentum.RSIIndicator(close=stock_df['Close'], window=14).rsi()
    stock_df['RSI_14'] = round(stock_df['RSI_14'],0)
    stock_df['Prev_Close'] = stock_df['Close'].shift(1)
    stock_df.drop(['Open', 'Low', 'High', 'Volume'], axis=1, inplace=True)
    stock_df = stock_df.tail(1)

    max_SMA = max(stock_df['20_SMA'].item(), stock_df['50_SMA'].item(), stock_df['200_SMA'].item())
    min_SMA = min(stock_df['20_SMA'].item(), stock_df['50_SMA'].item(), stock_df['200_SMA'].item())
    ABS_Spread = max_SMA - min_SMA
    stock_df['Spread%'] = round((ABS_Spread / stock_df['200_SMA'].item()) * 100,2)

    return stock_df

# function to compute stock attributes
def get_common_features(stock_ids, df_mypf):

  df_prec_dev = pd.DataFrame()
  df_tmp = get_screener_features()
  df_rs = get_relative_strength(stock_ids)

  for stock_id in stock_ids:
      tmp = stock_prec_dev(stock_id)
      tmp = tmp.reset_index()
      df_prec_dev = pd.concat([df_prec_dev, tmp], ignore_index = True)
  df_prec_dev = pd.merge(df_prec_dev, df_mypf, on= 'Symbol')
  df_prec_dev = pd.merge(df_prec_dev, df_tmp, on= 'Symbol', how='left')
  df_prec_dev = pd.merge(df_prec_dev, df_rs, on= 'Symbol', how='left')
  #print(df_prec_dev.columns)
  df_prec_dev['Curr_PE'] = round(df_prec_dev['Close']/df_prec_dev['EPS'],1)
  df_prec_dev['Dev%_PE'] = round((df_prec_dev['Curr_PE'] - df_prec_dev['MedPE'])*100/df_prec_dev['MedPE'],2)
  df_prec_dev['Conviction'] = df_prec_dev['Conviction'] + '-' + df_prec_dev['CapType']
  return df_prec_dev

# function to arrange stock features
def arrange_features(df_stocks, common_cols, diff_cols):
  df_stocks_common = df_stocks[common_cols].drop_duplicates()
  df_stocks_diff = df_stocks[diff_cols]
  df_stocks_diff['Investment'] = df_stocks_diff['AvgCost'] * df_stocks_diff['Shares']
  df_stocks_diff = df_stocks_diff.groupby(['Symbol'])[['Shares', 'Investment']].aggregate(['sum']).reset_index()
  df_stocks_diff.columns = ['Symbol', 'Shares', 'Investment']
  df_stocks_diff['AvgCost'] = round(df_stocks_diff['Investment']/df_stocks_diff['Shares'],2)
  df_stocks = pd.merge(df_stocks_diff, df_stocks_common, on='Symbol')
  return df_stocks

# plot fact distribution across dimension
def plot_pie_chart(df, dimension, fact):
  # grouping the data by category and calculating the sum of fact for each type
  grouped_data = df.groupby(dimension)[fact].sum()

  # sorting the grouped data in descending order
  grouped_data = grouped_data.sort_values(ascending=False)

  # creating a pie chart
  grouped_data.plot.pie(autopct='%1.1f%%', startangle=90, figsize=(6, 6))

  # adding a title and displaying the plot
  plt.title(f'{dimension} {fact} Distribution')
  plt.ylabel('')  # To hide the y-label
  plt.show()

In [7]:
# function to get portfolio features

def get_portfolio_features(df_common_features):

  print_date_time()
  print('-------------------')

  #df_common_features["Target"] = df_common_features["Target"].fillna(df_common_features["Max"])
  df_common_features['NTT'] = np.where(df_common_features['Strategy']== 'NTT', df_common_features["Target"], df_common_features['Max'])
  df_common_features['LTT'] = np.where(df_common_features['Strategy']== 'BTT', df_common_features["Target"], df_common_features['Max'])
  df_common_features['BOL'] = df_common_features['Min']

  tmp_df = df_common_features[df_common_features['Symbol'].isin(mypf_df[mypf_df['InPortfolio'] != 'NA'].Symbol.values)]
  print('qualified stocks: '+str(len(tmp_df['Symbol'].unique())))
  tmp_df1 = tmp_df[tmp_df['LatestQtr'] == 1]
  print('with latest results: '+str(len(tmp_df1['Symbol'].unique())))
  tmp_df1 = tmp_df1[tmp_df1['StarStock'] == 1]
  print('still star stocks: '+str(len(tmp_df1['Symbol'].unique())))
  tmp_df['Investment'] = tmp_df['AvgCost'] * tmp_df['Shares']
  tmp_df['Current'] = round(tmp_df['Close'] * tmp_df['Shares'],0)
  tmp_df['Previous'] = tmp_df['Prev_Close'] * tmp_df['Shares']
  tmp_df['EstimatedST'] = tmp_df['NTT'] * tmp_df['Shares']
  tmp_df['EstimatedLT'] = tmp_df['LTT'] * tmp_df['Shares']
  tmp_df['Current P/L'] = round((tmp_df['Current'] - tmp_df['Investment']),0)
  tmp_df['Today P/L%'] = round((tmp_df['Current'] - tmp_df['Previous'])*100/tmp_df['Previous'],2)
  tmp_df['Current P/L%'] = round((tmp_df['Current'] - tmp_df['Investment'])*100/tmp_df['Investment'],2)
  tmp_df['EstimatedST P/L%'] = round((tmp_df['EstimatedST'] - tmp_df['Investment'])*100/tmp_df['Investment'],2)
  tmp_df['EstimatedLT P/L%'] = round((tmp_df['EstimatedLT'] - tmp_df['Investment'])*100/tmp_df['Investment'],2)
  tmp_df['NTT%'] = round((tmp_df['NTT'] - tmp_df['Close'])*100/tmp_df['Close'],2)
  tmp_df['LTT%'] = round((tmp_df['LTT'] - tmp_df['Close'])*100/tmp_df['Close'],2)
  tmp_df['Gained%'] = round((tmp_df['Close'] - tmp_df['BOL'])*100/tmp_df['BOL'],2)
  investment = round(sum(tmp_df['AvgCost']*tmp_df['Shares']),0)
  current = round(sum(tmp_df['Close']*tmp_df['Shares']),0)
  tmp_df['InitAlloc%'] = round(tmp_df['Investment']*100/investment,2)
  tmp_df['CurrAlloc%'] = round(tmp_df['Current']*100/current,2)
  tmp_df['FTT'] = tmp_df['LTT']
  tmp_df.loc[tmp_df['Strategy'] == 'NTT', 'FTT'] = tmp_df['NTT']
  tmp_df['FTT%'] = tmp_df['LTT%']
  tmp_df.loc[tmp_df['Strategy'] == 'NTT', 'FTT%'] = tmp_df['NTT%']
  tmp_df['FTT Amt'] = round(tmp_df['FTT%'] * tmp_df['Current']/100,0)
  tmp_df['OTT%'] = round((tmp_df['FTT'] - tmp_df['AvgCost'])*100/tmp_df['AvgCost'],2)
  tmp_df['RRR Ind'] = round(tmp_df['Current P/L']/tmp_df['FTT Amt'],2)
  tmp_df['Risk Ind'] = round(tmp_df['Current P/L%']*tmp_df['CurrAlloc%'],0)

  return tmp_df

# function to print portfolio features
def print_portfolio_stats(df_portfolio_features, myinvmt_df):
  from pyxirr import xirr

  total_booked_amt, reserve_amt, cy_booked_amt, py_booked_amt = get_amt()

  dates = myinvmt_df['Date'].values
  dates = np.append(dates, datetime.date.today().strftime('%d-%b-%y'))
  investment = myinvmt_df['Investment'].values
  dates= pd.to_datetime(dates)

  current = round(sum(df_portfolio_features['Close']*df_portfolio_features['Shares']),0) + reserve_amt
  investment_xirr = np.append(investment, current)
  cagr = round(xirr(pd.DataFrame({"dates": dates, "amounts": investment_xirr}))*100,2)

  investment = -sum(investment)
  invested = round(sum(df_portfolio_features['AvgCost']*df_portfolio_features['Shares']),0) + reserve_amt
  previous = round(sum(df_portfolio_features['Prev_Close']*df_portfolio_features['Shares']),0) + reserve_amt
  cy_invested = investment + py_booked_amt

  today_pnl_amount = current-previous
  today_pnl_percentage = round((current-previous)*100/previous,2)

  curr_pnl_amount = current-invested
  curr_pnl_percentage = round((curr_pnl_amount)*100/(cy_invested),2)

  cy_pnl_amount = cy_booked_amt + curr_pnl_amount
  cy_pnl_percentage = round((cy_pnl_amount)*100/cy_invested,2)

  overall_pnl_amount = total_booked_amt + curr_pnl_amount
  overall_pnl_percentage = round((overall_pnl_amount)*100/investment,2)

  estimate_st = round(sum(df_portfolio_features['FTT']*df_portfolio_features['Shares']),0)  + reserve_amt
  est_st_pnl_amount = estimate_st-current
  est_st_pnl_percentage = round((est_st_pnl_amount)*100/current,2)

  estimate_lt = round(sum(df_portfolio_features['LTT']*df_portfolio_features['Shares']),0)  + reserve_amt
  est_lt_pnl_amount = estimate_lt-current
  est_lt_pnl_percentage = round((est_lt_pnl_amount)*100/current,2)

  total_profit = round(sum(df_portfolio_features[df_portfolio_features['Current P/L%'] > 0]['Current']) - sum(df_portfolio_features[df_portfolio_features['Current P/L%'] > 0]['Investment']),0)
  total_loss = round(sum(df_portfolio_features[df_portfolio_features['Current P/L%'] < 0]['Current']) - sum(df_portfolio_features[df_portfolio_features['Current P/L%'] < 0]['Investment']),0)

  cy_booked_percentage = round((cy_booked_amt)*100/current,2)
  py_booked_percentage = round((py_booked_amt)*100/investment,2)
  total_booked_percentage = round((total_booked_amt)*100/investment,2)

  print('-------------------')
  print('Initial Investment: ', format_amt(investment))
  print('CY Investment: ', format_amt(cy_invested))
  print('Reserve: ', format_amt(reserve_amt))
  print('Current: ',  format_amt(current))
  print('-------------------')
  print('Today PnL: '+ '{} ({}%)'.format(format_amt(today_pnl_amount), today_pnl_percentage))
  print('Current PnL: '+ '{} ({}%)'.format(format_amt(curr_pnl_amount), curr_pnl_percentage))
  print('CY Booked + Current PnL: '+ '{} ({}%)'.format(format_amt(cy_pnl_amount), cy_pnl_percentage))
  print('-------------------')
  print('Total profit: ', format_amt(total_profit))
  print('Total loss: ', format_amt(total_loss))
  print('-------------------')
  print('Total Booked + Current PnL: '+ '{} ({}%)'.format(format_amt(overall_pnl_amount), overall_pnl_percentage))
  print('Total Booked PnL: '+ '{} ({}%)'.format(format_amt(total_booked_amt), total_booked_percentage))
  print('Curr Year Booked PnL: '+ '{} ({}%)'.format(format_amt(cy_booked_amt), cy_booked_percentage))
  print('Prev Year Booked PnL: '+ '{} ({}%)'.format(format_amt(py_booked_amt), py_booked_percentage))
  print('===================')
  print('Est FTT: ',  format_amt(estimate_st))
  print('Est FTT PnL: '+ '{} ({}%)'.format(format_amt(est_st_pnl_amount), est_st_pnl_percentage))

  print('===================')
  print('Deployed: ', format_amt(investment))

  print('Current: ', format_amt(current))

  print('CAGR/XIRR %: '+'{}%'.format(cagr))

In [8]:
# get start and end date
start_date, end_date = get_start_end_date()

# get portfolio and prospects data
mypfs_df = get_mypfs_df()
mypps_df = get_mypps_df()
myinvmt_df = get_myinvmt_df()

# merge above datasets
mypf_df = pd.merge(mypfs_df, mypps_df, on="Symbol")

# seggregate dm and sv portfolio
dm_pf = mypf_df[mypf_df['InPortfolio'] == 'DM']
sv_pf = mypf_df[mypf_df['InPortfolio'] == 'SV']

# build portfolio stock dataframe
dm_stocks = get_stock_ids(dm_pf)
sv_stocks = get_stock_ids(sv_pf)
df_stocks = pd.concat([dm_pf,sv_pf], ignore_index = True)

# arrange common and diff stock features
common_cols = ['Symbol', 'Target', 'Criteria', 'Strategy', 'CumlRnk', 'LatestQtr', 'StarStock', 'Conviction', 'Category', 'InFolio', 'XIRR', 'MBQ']
diff_cols = ['Symbol', 'AvgCost', 'Shares']
df_stocks = arrange_features(df_stocks, common_cols, diff_cols)

# get common features
stock_ids = df_stocks['Symbol'].values
df_common_features = get_common_features(stock_ids, df_stocks)

df_common_features.reset_index(drop=True, inplace=True)
df_common_features.drop(['Date'], axis=1, inplace=True)
# get and print portfolio features
df_portfolio_features = get_portfolio_features(df_common_features)

print_portfolio_stats(df_portfolio_features, myinvmt_df)

df = df_portfolio_features
#plot_pie_chart(df, 'CapType', 'Current')
list_ox40n = list(df[df['MBQ'].str.contains('OX40N', na=False)]['Symbol'].values)

Run date time (IST): 2026-06-10 16:11:17
-------------------
qualified stocks: 92
with latest results: 31
still star stocks: 20

-------------------
Initial Investment:  1.40 C
CY Investment:  1.82 C
Reserve:  1.49 K
Current:  1.47 C
-------------------
Today PnL: -95.99 K (-0.65%)
Current PnL: -36.05 L (-19.77%)
CY Booked + Current PnL: -33.97 L (-18.63%)
-------------------
Total profit:  2.23 L
Total loss:  -38.27 L
-------------------
Total Booked + Current PnL: 8.90 L (6.38%)
Total Booked PnL: 44.95 L (32.22%)
Curr Year Booked PnL: 2.08 L (1.41%)
Prev Year Booked PnL: 42.87 L (30.73%)
===================
Est FTT:  2.55 C
Est FTT PnL: 1.08 C (73.43%)
===================
Deployed:  1.40 C
Current:  1.47 C
CAGR/XIRR %: 2.51%

In [9]:
# top 5 near their targets
cols = ['Symbol', 'Today P/L%', 'Current P/L%', 'FTT%', 'OTT%', 'FTT Amt', 'Current P/L', 'Current', 'FTT', 'Dev%_PE', 'RSI_14','Conviction', 'Spread%',  'CumlRnk', 'RRR Ind', 'CurrAlloc%', 'Gained%', 'Criteria', 'Strategy', 'Category']
df_tmp = df_portfolio_features[~df_portfolio_features['Symbol'].isin(['ENRIN','BLUSPRING','DIGITIDE'])]
df_tmp = df_tmp.sort_values(by = 'FTT Amt', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
59,PIDILITIND,1.67,6.76,10.87,18.37,16376.0,9540.0,150650.0,1670.26,-25.18,64.0,X-LC,3.99,5.0,0.58,1.02,18.29,X40,ATH,CHEMICALS
51,KOTAKBANK,1.68,3.70,16.78,21.11,24096.0,5124.0,143597.0,453.24,-11.14,57.0,X-LC,6.84,12.0,0.21,0.98,9.82,X40,ATH,BANKS
72,SIS,-1.36,-4.59,27.09,21.26,28699.0,-5092.0,105940.0,528.00,2524.87,62.0,H-SC,20.63,168.0,-0.18,0.72,57.52,OX40N,NTT,MISC
83,TTKPRESTIG,0.12,-29.19,41.36,0.09,29513.0,-29421.0,71356.0,770.00,65.64,57.0,M-SC,12.64,250.0,-1.00,0.49,27.06,OX40N,NTT,DURABLES
55,MASFIN,-2.06,-9.06,33.68,21.57,30009.0,-8880.0,89100.0,397.04,-21.41,37.0,H-SC,2.36,167.0,-0.30,0.61,6.20,XR,ATH,FINANCE

In [10]:
# top 5 today
df_tmp = df_portfolio_features.sort_values(by = 'Today P/L%', ascending=False)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
24,EASEMYTRIP,12.07,-51.32,199.32,45.70,171547.0,-90749.0,86066.0,26.40,-10.53,68.0,M-SC,5.01,204.0,-0.53,0.59,50.77,XY24,NTT,TRAVEL
11,BERGEPAINT,2.95,-4.78,31.60,25.32,77557.0,-12316.0,245433.0,680.00,-9.89,58.0,X-MC,5.39,68.0,-0.16,1.67,27.74,XY24,NTT,PAINTS
37,HONAUT,2.86,-6.32,61.52,51.31,111136.0,-12188.0,180650.0,58357.33,-22.15,67.0,X-SC,6.78,90.0,-0.11,1.23,37.25,X40N,ATH,ELECTRICAL
52,LAOPALA,2.70,-46.95,162.19,39.09,112802.0,-61556.0,69549.0,464.00,52.27,52.0,H-SC,15.54,154.0,-0.55,0.47,7.91,AR,NTT,CERAMICS
69,SFL,2.30,-31.47,84.77,26.63,152340.0,-82508.0,179710.0,1287.00,36.12,75.0,M-SC,8.93,242.0,-0.54,1.22,49.78,XY24,NTT,MISC

In [11]:
# bottom 5 today
df_tmp = df_portfolio_features.sort_values(by = 'Today P/L%', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
61,RAJESHEXPO,-4.99,-83.65,511.86,0.07,114836.0,-114742.0,22435.0,518.00,721.97,26.0,L-SC,31.99,268.0,-1.00,0.15,5.32,OX40N,NTT,JEWELLERY
18,COFFEEDAY,-4.69,-43.98,141.47,35.27,89989.0,-49939.0,63610.0,80.00,-57.75,55.0,L-SC,18.13,266.0,-0.55,0.43,56.87,XR,NTT,HOTELS
44,INDUSINDBK,-4.21,-34.74,103.63,32.89,52214.0,-26822.0,50385.0,1800.00,-337.39,44.0,L-MC,7.27,258.0,-0.51,0.34,24.02,XR,NTT,BANKS
25,FINCABLES,-3.64,25.96,65.06,107.91,120993.0,38328.0,185972.0,1641.55,13.14,45.0,M-SC,24.26,220.0,0.32,1.26,39.91,OX40N,ATH,CABLES
9,BANDHANBNK,-3.47,-3.91,100.24,92.42,268320.0,-10881.0,267678.0,400.00,129.89,51.0,H-SC,20.85,174.0,-0.04,1.82,47.46,XY24,NTT,BANKS

In [12]:
# top 5 to exit based on CumlRnk
df_tmp = df_portfolio_features[~df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])]
df_tmp = df_tmp[(df_tmp['Current P/L%'] > -1) & (df_tmp['Current P/L%'] < 1)].sort_values(by = 'CumlRnk', ascending=False)
df_tmp[cols].head()

Empty DataFrame
Columns: [Symbol, Today P/L%, Current P/L%, FTT%, OTT%, FTT Amt, Current P/L, Current, FTT, Dev%_PE, RSI_14, Conviction, Spread%, CumlRnk, RRR Ind, CurrAlloc%, Gained%, Criteria, Strategy, Category]
Index: []

In [13]:
# OX40N stocks to exit
df_tmp = df_portfolio_features[(df_portfolio_features['Symbol'].isin(list_ox40n))].sort_values(by = 'Current P/L%', ascending=False)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
25,FINCABLES,-3.64,25.96,65.06,107.91,120993.0,38328.0,185972.0,1641.55,13.14,45.0,M-SC,24.26,220.0,0.32,1.26,39.91,OX40N,ATH,CABLES
72,SIS,-1.36,-4.59,27.09,21.26,28699.0,-5092.0,105940.0,528.00,2524.87,62.0,H-SC,20.63,168.0,-0.18,0.72,57.52,OX40N,NTT,MISC
16,CERA,0.59,-23.25,61.43,23.89,82929.0,-40905.0,134998.0,9475.00,-26.01,62.0,H-SC,4.36,153.0,-0.49,0.92,29.73,OX40N,NTT,CERAMICS
50,KANSAINER,2.23,-28.45,58.58,13.47,113036.0,-76707.0,192960.0,340.00,-38.54,55.0,H-SC,8.44,162.0,-0.68,1.31,34.78,XY24,NTT,PAINTS
83,TTKPRESTIG,0.12,-29.19,41.36,0.09,29513.0,-29421.0,71356.0,770.00,65.64,57.0,M-SC,12.64,250.0,-1.00,0.49,27.06,OX40N,NTT,DURABLES

In [14]:
# top 5 to book for rotation
df_tmp = df_portfolio_features[(df_portfolio_features['Current P/L%'] > 20) ].sort_values(by = 'CumlRnk', ascending=False)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
25,FINCABLES,-3.64,25.96,65.06,107.91,120993.0,38328.0,185972.0,1641.55,13.14,45.0,M-SC,24.26,220.0,0.32,1.26,39.91,OX40N,ATH,CABLES
68,SATIN,-3.42,29.57,17.18,51.83,61503.0,81710.0,357994.0,274.00,15.64,63.0,H-SC,41.41,159.0,1.33,2.43,74.40,XY24,NTT,FINANCE

In [15]:
# top 5 to monitor for exit
df_tmp = df_portfolio_features[~df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])]
df_tmp = df_tmp[(df_tmp['Current P/L%'] > 0) ].sort_values(by = 'Dev%_PE', ascending=False)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
74,STARHEALTH,0.58,1.48,45.12,47.26,128716.0,4151.0,285274.0,761.00,60.18,55.0,H-SC,9.84,173.0,0.03,1.94,25.24,XY24,NTT,INSURANCE
68,SATIN,-3.42,29.57,17.18,51.83,61503.0,81710.0,357994.0,274.00,15.64,63.0,H-SC,41.41,159.0,1.33,2.43,74.40,XY24,NTT,FINANCE
25,FINCABLES,-3.64,25.96,65.06,107.91,120993.0,38328.0,185972.0,1641.55,13.14,45.0,M-SC,24.26,220.0,0.32,1.26,39.91,OX40N,ATH,CABLES
91,ZYDUSLIFE,-0.66,15.82,17.11,35.63,41530.0,33150.0,242724.0,1286.17,0.90,70.0,H-MC,11.68,120.0,0.80,1.65,27.62,AR,ATH,PHARMA
73,SONACOMS,-2.09,1.94,36.45,39.09,37587.0,1960.0,103119.0,804.02,-19.25,49.0,M-MC,18.49,193.0,0.05,0.70,45.88,AR,ATH,AUTO

In [16]:
# top 5 to book for rotation from weak conviction
df_tmp = df_portfolio_features[~df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])]
df_tmp = df_tmp[~df_tmp['Criteria'].isin(['XY25','XY24','X40', 'X40N'])].sort_values(by = 'RRR Ind', ascending=False)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
91,ZYDUSLIFE,-0.66,15.82,17.11,35.63,41530.0,33150.0,242724.0,1286.17,0.90,70.0,H-MC,11.68,120.0,0.80,1.65,27.62,AR,ATH,PHARMA
25,FINCABLES,-3.64,25.96,65.06,107.91,120993.0,38328.0,185972.0,1641.55,13.14,45.0,M-SC,24.26,220.0,0.32,1.26,39.91,OX40N,ATH,CABLES
73,SONACOMS,-2.09,1.94,36.45,39.09,37587.0,1960.0,103119.0,804.02,-19.25,49.0,M-MC,18.49,193.0,0.05,0.70,45.88,AR,ATH,AUTO
42,INDIAMART,-0.03,-13.63,139.33,106.72,148428.0,-16806.0,106530.0,4810.62,-61.13,47.0,H-SC,11.04,140.0,-0.11,0.72,3.13,AR,ATH,MISC
75,SURYODAY,-2.84,-3.17,27.06,23.03,46922.0,-5671.0,173400.0,216.00,88.60,59.0,H-SC,17.83,166.0,-0.12,1.18,46.00,XR,NTT,BANKS

In [17]:
# top 5 to accumulate based on lowest RSI_14
df_tmp = df_portfolio_features[df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])].sort_values(by = 'RSI_14', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
35,HDFCLIFE,-1.97,-10.12,48.18,33.18,64870.0,-15160.0,134640.0,814.30,-29.79,26.0,X-LC,15.55,31.0,-0.23,0.92,0.0,X40,ATH,INSURANCE
40,ICICIPRULI,-1.89,-22.92,69.01,30.28,104792.0,-45154.0,151851.0,787.27,-43.61,28.0,X-MC,15.69,78.0,-0.43,1.03,0.0,X40,ATH,INSURANCE
65,RELIANCE,-0.82,-19.20,55.07,25.30,89425.0,-38578.0,162385.0,1952.00,-21.18,29.0,X-LC,6.97,21.0,-0.43,1.10,0.0,XY25,BTT,REFINERIES
58,PGHH,-0.02,-32.33,95.08,32.01,137379.0,-69032.0,144488.0,17616.87,-54.24,31.0,X-MC,18.84,57.0,-0.50,0.98,0.0,X40,ATH,FMCG
27,GLAXO,-0.90,-12.69,55.42,35.69,96426.0,-25292.0,173992.0,3380.16,-33.30,34.0,X-MC,8.84,56.0,-0.26,1.18,0.5,X40,ATH,PHARMA

In [18]:
# top 5 to accumulate based on Spread and CumlRnk
df_tmp = df_portfolio_features[df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])]
df_tmp = df_tmp[(df_tmp['CumlRnk'] < 100)].sort_values(by = 'Spread%', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
57,PAGEIND,-2.44,-1.00,34.94,33.59,92830.0,-2694.0,265685.0,51217.29,-29.03,52.0,X-MC,3.09,55.0,-0.03,1.81,26.17,X40,ATH,APPARELS
49,JSWINFRA,-1.49,-5.15,22.76,16.43,47874.0,-11431.0,210343.0,342.00,-18.74,54.0,X-MC,3.15,61.0,-0.24,1.43,18.90,X40N,NTT,REALTY
15,CAMS,-1.15,-2.90,28.19,24.48,68942.0,-7293.0,244563.0,950.00,-6.92,42.0,X-SC,3.66,89.0,-0.11,1.66,19.06,X40N,NTT,MISC
19,COLPAL,1.63,-21.92,79.13,39.86,162715.0,-57735.0,205630.0,3683.41,-5.63,50.0,X-MC,3.77,62.0,-0.35,1.40,16.32,XY25,ATH,FMCG
59,PIDILITIND,1.67,6.76,10.87,18.37,16376.0,9540.0,150650.0,1670.26,-25.18,64.0,X-LC,3.99,5.0,0.58,1.02,18.29,X40,ATH,CHEMICALS

In [19]:
# top 5 to accumulate based on lowest Gained%
df_tmp = df_portfolio_features[df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])].sort_values(by = 'Gained%', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
40,ICICIPRULI,-1.89,-22.92,69.01,30.28,104792.0,-45154.0,151851.0,787.27,-43.61,28.0,X-MC,15.69,78.0,-0.43,1.03,0.00,X40,ATH,INSURANCE
35,HDFCLIFE,-1.97,-10.12,48.18,33.18,64870.0,-15160.0,134640.0,814.30,-29.79,26.0,X-LC,15.55,31.0,-0.23,0.92,0.00,X40,ATH,INSURANCE
65,RELIANCE,-0.82,-19.20,55.07,25.30,89425.0,-38578.0,162385.0,1952.00,-21.18,29.0,X-LC,6.97,21.0,-0.43,1.10,0.00,XY25,BTT,REFINERIES
58,PGHH,-0.02,-32.33,95.08,32.01,137379.0,-69032.0,144488.0,17616.87,-54.24,31.0,X-MC,18.84,57.0,-0.50,0.98,0.00,X40,ATH,FMCG
79,TCS,0.13,-36.77,97.50,24.88,285607.0,-170343.0,292930.0,4253.91,-46.57,36.0,X-LC,18.79,2.0,-0.60,1.99,0.13,X40,ATH,IT

In [20]:
# top 5 to accumulate based on lowest CurrAlloc%
df_tmp = df_portfolio_features[df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])].sort_values(by = 'CurrAlloc%', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
10,BATAINDIA,-0.64,-57.16,215.64,35.20,118852.0,-73554.0,55116.0,2096.0,-27.80,39.0,X-SC,25.54,91.0,-0.62,0.37,9.31,X40,NTT,FOOTWEAR
64,RELAXO,-0.72,-55.37,241.27,52.31,156307.0,-80375.0,64785.0,1176.0,-52.47,64.0,X-SC,20.67,92.0,-0.51,0.44,44.85,X40N,NTT,FOOTWEAR
60,QUESS,0.40,-2.34,78.07,73.90,81421.0,-2501.0,104292.0,424.0,-47.66,73.0,X-SC,4.81,80.0,-0.03,0.71,42.17,XY24,NTT,MISC
53,M&M,-1.26,-4.20,28.79,23.38,38251.0,-5819.0,132862.0,3802.4,-18.96,39.0,X-LC,10.50,25.0,-0.15,0.90,0.73,X40N,ATH,AUTO
35,HDFCLIFE,-1.97,-10.12,48.18,33.18,64870.0,-15160.0,134640.0,814.3,-29.79,26.0,X-LC,15.55,31.0,-0.23,0.92,0.00,X40,ATH,INSURANCE

In [21]:
# top 5 to accumulate based on CumlRnk
df_tmp = df_portfolio_features.sort_values(by = 'CumlRnk', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
47,ITC,1.30,-25.29,59.35,19.06,150838.0,-86016.0,254150.0,452.00,-59.16,42.0,X-LC,14.93,1.0,-0.57,1.73,2.40,X40,NTT,FMCG
79,TCS,0.13,-36.77,97.50,24.88,285607.0,-170343.0,292930.0,4253.91,-46.57,36.0,X-LC,18.79,2.0,-0.60,1.99,0.13,X40,ATH,IT
45,INFY,-0.87,-22.03,72.18,34.24,176082.0,-68939.0,243949.0,1972.00,-38.68,46.0,X-LC,17.19,3.0,-0.39,1.66,6.86,X40,NTT,IT
81,TMPV,-1.75,-13.27,57.48,36.58,177389.0,-47231.0,308610.0,600.00,-82.53,54.0,X-LC,15.74,4.0,-0.27,2.10,28.63,XY24,NTT,AUTO
59,PIDILITIND,1.67,6.76,10.87,18.37,16376.0,9540.0,150650.0,1670.26,-25.18,64.0,X-LC,3.99,5.0,0.58,1.02,18.29,X40,ATH,CHEMICALS

In [22]:
# top 5 for average up
df_tmp = df_portfolio_features[(df_portfolio_features['Dev%_200'] > 5)].sort_values(by = 'CurrAlloc%', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
3,ALKYLAMINE,-2.94,-23.47,153.01,93.63,118226.0,-23696.0,77267.0,4546.37,-18.07,58.0,H-SC,9.38,142.0,-0.20,0.53,45.90,SR,ATH,CHEMICALS
24,EASEMYTRIP,12.07,-51.32,199.32,45.70,171547.0,-90749.0,86066.0,26.40,-10.53,68.0,M-SC,5.01,204.0,-0.53,0.59,50.77,XY24,NTT,TRAVEL
73,SONACOMS,-2.09,1.94,36.45,39.09,37587.0,1960.0,103119.0,804.02,-19.25,49.0,M-MC,18.49,193.0,0.05,0.70,45.88,AR,ATH,AUTO
60,QUESS,0.40,-2.34,78.07,73.90,81421.0,-2501.0,104292.0,424.00,-47.66,73.0,X-SC,4.81,80.0,-0.03,0.71,42.17,XY24,NTT,MISC
72,SIS,-1.36,-4.59,27.09,21.26,28699.0,-5092.0,105940.0,528.00,2524.87,62.0,H-SC,20.63,168.0,-0.18,0.72,57.52,OX40N,NTT,MISC

In [23]:
# top 5 RSP
df_tmp = df_portfolio_features.sort_values(by = 'RSP', ascending=False)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
18,COFFEEDAY,-4.69,-43.98,141.47,35.27,89989.0,-49939.0,63610.0,80.00,-57.75,55.0,L-SC,18.13,266.0,-0.55,0.43,56.87,XR,NTT,HOTELS
37,HONAUT,2.86,-6.32,61.52,51.31,111136.0,-12188.0,180650.0,58357.33,-22.15,67.0,X-SC,6.78,90.0,-0.11,1.23,37.25,X40N,ATH,ELECTRICAL
69,SFL,2.30,-31.47,84.77,26.63,152340.0,-82508.0,179710.0,1287.00,36.12,75.0,M-SC,8.93,242.0,-0.54,1.22,49.78,XY24,NTT,MISC
24,EASEMYTRIP,12.07,-51.32,199.32,45.70,171547.0,-90749.0,86066.0,26.40,-10.53,68.0,M-SC,5.01,204.0,-0.53,0.59,50.77,XY24,NTT,TRAVEL
91,ZYDUSLIFE,-0.66,15.82,17.11,35.63,41530.0,33150.0,242724.0,1286.17,0.90,70.0,H-MC,11.68,120.0,0.80,1.65,27.62,AR,ATH,PHARMA

In [24]:
# Top N allocation
df_tmp = df_portfolio_features.sort_values(by = 'CurrAlloc%', ascending=False)
top_n_values = [10, 25, 50]

sum_df = pd.DataFrame({
    'Top_N': top_n_values,
    'Sum_Alloc%': [df_tmp['CurrAlloc%'].head(n).sum() for n in top_n_values]
})

sum_df

   Top_N  Sum_Alloc%
0     10       19.65
1     25       42.86
2     50       72.82

In [25]:
# market-cap-wise allocation
df_tmp = df_portfolio_features[cols]
df_tmp.groupby(df_tmp['Conviction'].str[-2:])['CurrAlloc%'].sum().sort_values(ascending=False)

Conviction
SC    43.13
LC    31.22
MC    25.66
Name: CurrAlloc%, dtype: float64

In [26]:
# criteria-wise allocation
df_portfolio_features.groupby('Criteria')['CurrAlloc%'].sum().sort_values(ascending=False)

Criteria
XY24     28.00
X40      24.90
X40N     17.05
XR        8.85
OX40N     6.87
AR        6.86
XY25      6.59
SR        0.89
Name: CurrAlloc%, dtype: float64

In [27]:
# conviction-wise allocation
df_portfolio_features.groupby('Conviction')['CurrAlloc%'].sum().sort_values(ascending=False)

Conviction
X-LC    29.15
H-SC    22.64
X-MC    20.53
M-SC    10.04
X-SC     9.87
H-MC     2.79
M-MC     2.00
H-LC     1.22
M-LC     0.85
L-SC     0.58
L-MC     0.34
Name: CurrAlloc%, dtype: float64

In [28]:
# sector-wise stats
df_tmp = df_portfolio_features.groupby('Category')[['CurrAlloc%', 'Current', 'Current P/L', 'FTT Amt']].sum().sort_values(by=['Current', 'Current P/L'], ascending=False)
df_tmp['Current P/L%'] = round(df_tmp['Current P/L'] * 100 / df_tmp['Current'], 2)
df_tmp['FTT%'] = round(df_tmp['FTT Amt'] * 100 / df_tmp['Current'], 2)
cols = ['CurrAlloc%', 'Current P/L%', 'FTT%']
df_tmp[cols].sort_values(by=['CurrAlloc%'], ascending=False)

               CurrAlloc%  Current P/L%    FTT%
Category
FMCG                14.98        -20.05   62.16
FINANCE             10.85        -15.51   65.75
IT                  10.07        -52.23  128.34
MISC                 7.13        -27.86   83.41
AUTO                 6.77         -9.89   51.09
BANKS                5.75         -7.49   57.19
PAINTS               5.68        -17.81   38.27
INSURANCE            5.14         -9.62   46.69
PHARMA               5.07          0.71   30.02
ELECTRICAL           4.10        -17.34   58.76
CHEMICALS            2.18        -26.83  102.41
HEALTHCARE           2.04        -19.22   50.33
AC                   1.83        -18.74   50.94
APPARELS             1.81         -1.01   34.94
TRAVEL               1.73        -76.74  165.24
FOOTWEAR             1.72        -74.07  143.86
DURABLES             1.59        -66.28  106.73
BREWERIES            1.47         -8.05   30.49
REALTY               1.43         -5.43   22.76
CERAMICS             1.39        -50.09   95.69
ENGINEERING          1.29        -27.40   85.67
CABLES               1.26         20.61   65.06
REFINERIES           1.10        -23.76   55.07
CEMENT               1.07        -69.76  196.76
JEWELLERY            1.01       -115.40  190.24
ENTERTAINMENT        0.72        -80.52  188.18
HOTELS               0.43        -78.51  141.47
TEXTILES             0.40        -56.41  101.01

In [29]:
# money to be made criteria-wise
df_portfolio_features.groupby('Criteria')['FTT Amt'].agg(['sum', 'count']).sort_values(by='sum', ascending=False)

                sum  count
Criteria
XY24      3478730.0     21
X40       2020536.0     19
XR        1382449.0     13
X40N      1211248.0     13
AR        1174168.0      9
OX40N      781448.0     10
XY25       465774.0      5
SR         289630.0      2

In [30]:
# money to be made conviction-wise
df_portfolio_features.groupby('Conviction')['FTT Amt'].agg(['sum', 'count']).sort_values(by='sum', ascending=False)

                  sum  count
Conviction
H-SC        3458797.0     24
X-LC        1999154.0     21
X-MC        1696957.0     15
M-SC        1440259.0     14
X-SC        1350546.0      9
H-MC         288194.0      2
L-SC         204825.0      2
M-LC         167545.0      1
M-MC          91053.0      2
H-LC          54439.0      1
L-MC          52214.0      1

In [31]:
# money to be made criteria and conviction-wise
df_portfolio_features.groupby(['Conviction', 'Criteria'])['FTT Amt'].agg(['sum', 'count']).sort_values(by='sum', ascending=False)

                           sum  count
Conviction Criteria
X-LC       X40       1076812.0     10
H-SC       XY24      1047073.0      6
           AR         963667.0      5
           XR         829735.0      7
M-SC       XY24       828833.0      6
X-SC       XY24       796999.0      4
X-MC       X40        726562.0      7
           X40N       496269.0      4
X-LC       X40N       378594.0      6
M-SC       OX40N      337920.0      5
X-SC       X40N       336385.0      3
X-LC       XY24       332658.0      2
H-SC       OX40N      328692.0      4
           SR         289630.0      2
X-MC       XY25       247623.0      2
H-MC       XY24       246664.0      1
X-MC       XY24       226503.0      2
X-SC       X40        217162.0      2
M-SC       XR         196561.0      2
M-LC       XR         167545.0      1
X-LC       XY25       164685.0      2
L-SC       OX40N      114836.0      1
           XR          89989.0      1
M-SC       AR          76945.0      1
H-LC       AR          54439.0      1
M-MC       XY25        53466.0      1
L-MC       XR          52214.0      1
X-LC       XR          46405.0      1
H-MC       AR          41530.0      1
M-MC       AR          37587.0      1

In [32]:
# notebook execution time

end_time = time.time()
execution_time = round(end_time - start_time, 0)
print(f"Notebook execution time: {execution_time} seconds")

Notebook execution time: 30.0 seconds