<a href="https://colab.research.google.com/github/ankit-rathi/Quantvesting_v2/blob/main/myStocks_Portfolio_Analysis.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
'''
!pip install pandas==2.2.2 -qq
!pip install pyxirr -qq
!pip install ta -qq
!pip install yfinance==0.2.59 -qq
'''

'\n!pip install pandas==2.2.2 -qq\n!pip install pyxirr -qq\n!pip install ta -qq\n!pip install yfinance==0.2.59 -qq\n'

In [2]:
# import libraries

import numpy as np
import pandas as pd
import datetime
import warnings
warnings.filterwarnings('ignore')
import yfinance as yfin
import ta
import matplotlib.pyplot as plt
import requests

In [3]:
# notebook start time
import time
import datetime
import pytz

start_time = time.time()

# function to print date timestamp
def print_date_time():
  tz_NY = pytz.timezone('Asia/Kolkata')
  datetime_NY = datetime.datetime.now(tz_NY)
  print("Run date time (IST):", datetime_NY.strftime("%Y-%m-%d %H:%M:%S"))

In [4]:
# function to get booked and reserved amount
def get_amt():
  # fetch the JSON data from the URL
  url = "https://raw.githubusercontent.com/ankit-rathi/Tradevesting_v1/main/data/myPortfolioAmts.json"
  response = requests.get(url)
  pf_amts = response.json()  # parse the JSON data

  # extract values from the JSON
  py_booked_amt_dm = pf_amts["py_booked_amt_dm"]
  py_booked_amt_sv = pf_amts["py_booked_amt_sv"]
  cy_booked_amt_dm = pf_amts["cy_booked_amt_dm"]
  cy_booked_amt_sv = pf_amts["cy_booked_amt_sv"]
  reserve_amt_dm = pf_amts["reserve_amt_dm"]
  reserve_amt_sv = pf_amts["reserve_amt_sv"]

  # perform calculations
  py_booked_amt = py_booked_amt_dm + py_booked_amt_sv
  cy_booked_amt = cy_booked_amt_dm + cy_booked_amt_sv
  reserve_amt = reserve_amt_dm + reserve_amt_sv
  total_booked_amt = py_booked_amt + cy_booked_amt

  return total_booked_amt, reserve_amt, cy_booked_amt, py_booked_amt

gen_output = 0

In [5]:
# function to format the amount
def format_amt(number):
    abs_number = abs(number)

    if abs_number >= 1_00_00_000:  # Crores
        formatted_amt = f"{number / 1_00_00_000:.2f} C"
    elif abs_number >= 1_00_000:  # Lakhs
        formatted_amt = f"{number / 1_00_000:.2f} L"
    elif abs_number >= 1_000:  # Thousands
        formatted_amt = f"{number / 1_000:.2f} K"
    else:
        formatted_amt = f"{number:.2f}"

    return formatted_amt

# function to set start and end date
def get_start_end_date():
  start_date = (datetime.date.today() + datetime.timedelta(days=-365)).strftime('%Y-%m-%d')
  end_date = (datetime.date.today() + datetime.timedelta(days=1)).strftime('%Y-%m-%d')
  return start_date, end_date

# function to fetch my portfolio csv
def get_mypfs_df():
  mypfs_df = pd.read_csv('https://raw.githubusercontent.com/ankit-rathi/Tradevesting_v1/main/data/myPortfolioStocks.csv')
  return mypfs_df

# function to fetch my prospects csv
def get_mypps_df():
  mypps_df = pd.read_csv('https://raw.githubusercontent.com/ankit-rathi/Tradevesting_v1/main/data/myProspectsScrips.csv')
  return mypps_df

# function to fetch screener data
def get_myscreen_df():
  myscreen_df = pd.read_csv('https://raw.githubusercontent.com/ankit-rathi/Tradevesting_v1/main/data/myScreenerDB.csv')
  return myscreen_df

# function to fetch momentum data
def get_myinvmt_df():
  myinvmt_df = pd.read_csv('https://raw.githubusercontent.com/ankit-rathi/Tradevesting_v1/main/data/myInvestments.csv')
  return myinvmt_df

# function to get the stock ids
def get_stock_ids(df_pf):
  stock_n100 = df_pf['Symbol'].unique()

  exclude = ['CADILAHC','MMTC', 'MASFIN']

  stock_ids = df_pf[~df_pf['Symbol'].isin(exclude) ]['Symbol'].unique()

  #mypf = mypf[mypf.Forecast.notnull()]
  #stock_ids = mypf['Symbol'].unique()

  #stock_ids.sort()
  return stock_ids

# get features from screener data
def get_screener_features():
  myscreen_df = get_myscreen_df()
  cols = ['Symbol', 'EPS', 'MedPE', 'ROCE%', 'ROE%', 'CapType']
  return myscreen_df[cols]

# get relative strength
def get_relative_strength(stock_list):

    # Dictionary to store stock tickers and their corresponding percentage price change
    stock_changes = {}

    # Loop through each stock and fetch its price data
    for stock in stock_list:
        try:
            # Download the stock data for the given date range
            stock_data = yfin.Ticker(stock + '.NS').history(period='1mo', interval='1d')[map(str.title, ['open', 'close', 'low', 'high', 'volume'])]

            # Calculate the percentage change for the stock
            if len(stock_data) > 0:
                start_price = stock_data['Close'].iloc[0]
                end_price = stock_data['Close'].iloc[-1]
                percent_change = round(((end_price - start_price) / start_price) * 100, 2)
                stock_changes[stock] = percent_change
            else:
                stock_changes[stock] = np.nan  # If no data is available, set to NaN

        except Exception as e:
            print(f"Error fetching data for {stock}: {e}")
            stock_changes[stock] = np.nan

    # Create a DataFrame with stock tickers and their percentage changes
    df = pd.DataFrame(list(stock_changes.items()), columns=['Symbol', 'Percent_Change'])

    # Drop any stocks with missing data (NaN values)
    df = df.dropna()

    # Calculate the percentile rank based on percentage change
    df['RSP'] = round(df['Percent_Change'].rank(pct=True) * 100, 2)
    cols = ['Symbol', 'RSP']
    df = df[cols]
    # Sort by percentile rank (optional)
    df = df.sort_values(by='RSP', ascending=False).reset_index(drop=True)

    return df

In [6]:
# function to get stock technicals
def stock_prec_dev(stock_symbol):
    #stock_symbol = 'ULTRACEMCO.NS'
    short_window = 20
    mid_window = 50
    long_window = 200
    moving_avg = 'SMA'

    start = datetime.datetime(*map(int, start_date.split('-')))
    end = datetime.datetime(*map(int, end_date.split('-')))

    stock_df = yfin.Ticker(stock_symbol + '.NS').history(period='max', interval='1d')[map(str.title, ['open', 'close', 'low', 'high', 'volume'])]

    stock_df['Max'] = round(max(stock_df['Close']),2)
    stock_df = stock_df[(stock_df.index <= end_date) & (stock_df.index >= start_date)]
    stock_df['200_SMA'] = round(stock_df['Close'].rolling(window = 200, min_periods = 1).mean(),0)
    stock_df['Dev%_200'] = round((stock_df['Close'] - stock_df['200_SMA'])*100/stock_df['200_SMA'],2)
    stock_df.dropna(axis = 0, inplace = True) # remove any null rows

    stock_df['20_SMA'] = stock_df['Close'].rolling(window=20).mean()
    stock_df['50_SMA'] = stock_df['Close'].rolling(window=50).mean()
    stock_df['Symbol'] = stock_symbol

    stock_df['Close'] = round(stock_df['Close'],2)
    stock_df['Min'] = round(min(stock_df['Close']),2)
    stock_df['RSI_14'] = ta.momentum.RSIIndicator(close=stock_df['Close'], window=14).rsi()
    stock_df['RSI_14'] = round(stock_df['RSI_14'],0)
    stock_df['Prev_Close'] = stock_df['Close'].shift(1)
    stock_df.drop(['Open', 'Low', 'High', 'Volume'], axis=1, inplace=True)
    stock_df = stock_df.tail(1)

    max_SMA = max(stock_df['20_SMA'].item(), stock_df['50_SMA'].item(), stock_df['200_SMA'].item())
    min_SMA = min(stock_df['20_SMA'].item(), stock_df['50_SMA'].item(), stock_df['200_SMA'].item())
    ABS_Spread = max_SMA - min_SMA
    stock_df['Spread%'] = round((ABS_Spread / stock_df['200_SMA'].item()) * 100,2)

    return stock_df

# function to compute stock attributes
def get_common_features(stock_ids, df_mypf):

  df_prec_dev = pd.DataFrame()
  df_tmp = get_screener_features()
  df_rs = get_relative_strength(stock_ids)

  for stock_id in stock_ids:
      tmp = stock_prec_dev(stock_id)
      tmp = tmp.reset_index()
      df_prec_dev = pd.concat([df_prec_dev, tmp], ignore_index = True)
  df_prec_dev = pd.merge(df_prec_dev, df_mypf, on= 'Symbol')
  df_prec_dev = pd.merge(df_prec_dev, df_tmp, on= 'Symbol', how='left')
  df_prec_dev = pd.merge(df_prec_dev, df_rs, on= 'Symbol', how='left')
  #print(df_prec_dev.columns)
  df_prec_dev['Curr_PE'] = round(df_prec_dev['Close']/df_prec_dev['EPS'],1)
  df_prec_dev['Dev%_PE'] = round((df_prec_dev['Curr_PE'] - df_prec_dev['MedPE'])*100/df_prec_dev['MedPE'],2)
  df_prec_dev['Conviction'] = df_prec_dev['Conviction'] + '-' + df_prec_dev['CapType']
  return df_prec_dev

# function to arrange stock features
def arrange_features(df_stocks, common_cols, diff_cols):
  df_stocks_common = df_stocks[common_cols].drop_duplicates()
  df_stocks_diff = df_stocks[diff_cols]
  df_stocks_diff['Investment'] = df_stocks_diff['AvgCost'] * df_stocks_diff['Shares']
  df_stocks_diff = df_stocks_diff.groupby(['Symbol'])[['Shares', 'Investment']].aggregate(['sum']).reset_index()
  df_stocks_diff.columns = ['Symbol', 'Shares', 'Investment']
  df_stocks_diff['AvgCost'] = round(df_stocks_diff['Investment']/df_stocks_diff['Shares'],2)
  df_stocks = pd.merge(df_stocks_diff, df_stocks_common, on='Symbol')
  return df_stocks

# plot fact distribution across dimension
def plot_pie_chart(df, dimension, fact):
  # grouping the data by category and calculating the sum of fact for each type
  grouped_data = df.groupby(dimension)[fact].sum()

  # sorting the grouped data in descending order
  grouped_data = grouped_data.sort_values(ascending=False)

  # creating a pie chart
  grouped_data.plot.pie(autopct='%1.1f%%', startangle=90, figsize=(6, 6))

  # adding a title and displaying the plot
  plt.title(f'{dimension} {fact} Distribution')
  plt.ylabel('')  # To hide the y-label
  plt.show()

In [7]:
# function to get portfolio features

def get_portfolio_features(df_common_features):

  print_date_time()
  print('-------------------')

  #df_common_features["Target"] = df_common_features["Target"].fillna(df_common_features["Max"])
  df_common_features['NTT'] = np.where(df_common_features['Strategy']== 'NTT', df_common_features["Target"], df_common_features['Max'])
  df_common_features['LTT'] = np.where(df_common_features['Strategy']== 'BTT', df_common_features["Target"], df_common_features['Max'])
  df_common_features['BOL'] = df_common_features['Min']

  tmp_df = df_common_features[df_common_features['Symbol'].isin(mypf_df[mypf_df['InPortfolio'] != 'NA'].Symbol.values)]
  print('qualified stocks: '+str(len(tmp_df['Symbol'].unique())))
  tmp_df1 = tmp_df[tmp_df['LatestQtr'] == 1]
  print('with latest results: '+str(len(tmp_df1['Symbol'].unique())))
  tmp_df1 = tmp_df1[tmp_df1['StarStock'] == 1]
  print('still star stocks: '+str(len(tmp_df1['Symbol'].unique())))
  tmp_df['Investment'] = tmp_df['AvgCost'] * tmp_df['Shares']
  tmp_df['Current'] = round(tmp_df['Close'] * tmp_df['Shares'],0)
  tmp_df['Previous'] = tmp_df['Prev_Close'] * tmp_df['Shares']
  tmp_df['EstimatedST'] = tmp_df['NTT'] * tmp_df['Shares']
  tmp_df['EstimatedLT'] = tmp_df['LTT'] * tmp_df['Shares']
  tmp_df['Current P/L'] = round((tmp_df['Current'] - tmp_df['Investment']),0)
  tmp_df['Today P/L%'] = round((tmp_df['Current'] - tmp_df['Previous'])*100/tmp_df['Previous'],2)
  tmp_df['Current P/L%'] = round((tmp_df['Current'] - tmp_df['Investment'])*100/tmp_df['Investment'],2)
  tmp_df['EstimatedST P/L%'] = round((tmp_df['EstimatedST'] - tmp_df['Investment'])*100/tmp_df['Investment'],2)
  tmp_df['EstimatedLT P/L%'] = round((tmp_df['EstimatedLT'] - tmp_df['Investment'])*100/tmp_df['Investment'],2)
  tmp_df['NTT%'] = round((tmp_df['NTT'] - tmp_df['Close'])*100/tmp_df['Close'],2)
  tmp_df['LTT%'] = round((tmp_df['LTT'] - tmp_df['Close'])*100/tmp_df['Close'],2)
  tmp_df['Gained%'] = round((tmp_df['Close'] - tmp_df['BOL'])*100/tmp_df['BOL'],2)
  investment = round(sum(tmp_df['AvgCost']*tmp_df['Shares']),0)
  current = round(sum(tmp_df['Close']*tmp_df['Shares']),0)
  tmp_df['InitAlloc%'] = round(tmp_df['Investment']*100/investment,2)
  tmp_df['CurrAlloc%'] = round(tmp_df['Current']*100/current,2)
  tmp_df['FTT'] = tmp_df['LTT']
  tmp_df.loc[tmp_df['Strategy'] == 'NTT', 'FTT'] = tmp_df['NTT']
  tmp_df['FTT%'] = tmp_df['LTT%']
  tmp_df.loc[tmp_df['Strategy'] == 'NTT', 'FTT%'] = tmp_df['NTT%']
  tmp_df['FTT Amt'] = round(tmp_df['FTT%'] * tmp_df['Current']/100,0)
  tmp_df['OTT%'] = round((tmp_df['FTT'] - tmp_df['AvgCost'])*100/tmp_df['AvgCost'],2)
  tmp_df['RRR Ind'] = round(tmp_df['Current P/L']/tmp_df['FTT Amt'],2)
  tmp_df['Risk Ind'] = round(tmp_df['Current P/L%']*tmp_df['CurrAlloc%'],0)

  return tmp_df

# function to print portfolio features
def print_portfolio_stats(df_portfolio_features, myinvmt_df):
  from pyxirr import xirr

  total_booked_amt, reserve_amt, cy_booked_amt, py_booked_amt = get_amt()

  dates = myinvmt_df['Date'].values
  dates = np.append(dates, datetime.date.today().strftime('%d-%b-%y'))
  investment = myinvmt_df['Investment'].values
  dates= pd.to_datetime(dates)

  current = round(sum(df_portfolio_features['Close']*df_portfolio_features['Shares']),0) + reserve_amt
  investment_xirr = np.append(investment, current)
  cagr = round(xirr(pd.DataFrame({"dates": dates, "amounts": investment_xirr}))*100,2)

  investment = -sum(investment)
  invested = round(sum(df_portfolio_features['AvgCost']*df_portfolio_features['Shares']),0) + reserve_amt
  previous = round(sum(df_portfolio_features['Prev_Close']*df_portfolio_features['Shares']),0) + reserve_amt
  cy_invested = investment + py_booked_amt

  today_pnl_amount = current-previous
  today_pnl_percentage = round((current-previous)*100/previous,2)

  curr_pnl_amount = current-invested
  curr_pnl_percentage = round((curr_pnl_amount)*100/(cy_invested),2)

  cy_pnl_amount = cy_booked_amt + curr_pnl_amount
  cy_pnl_percentage = round((cy_pnl_amount)*100/cy_invested,2)

  overall_pnl_amount = total_booked_amt + curr_pnl_amount
  overall_pnl_percentage = round((overall_pnl_amount)*100/investment,2)

  estimate_st = round(sum(df_portfolio_features['FTT']*df_portfolio_features['Shares']),0)  + reserve_amt
  est_st_pnl_amount = estimate_st-current
  est_st_pnl_percentage = round((est_st_pnl_amount)*100/current,2)

  estimate_lt = round(sum(df_portfolio_features['LTT']*df_portfolio_features['Shares']),0)  + reserve_amt
  est_lt_pnl_amount = estimate_lt-current
  est_lt_pnl_percentage = round((est_lt_pnl_amount)*100/current,2)

  total_profit = round(sum(df_portfolio_features[df_portfolio_features['Current P/L%'] > 0]['Current']) - sum(df_portfolio_features[df_portfolio_features['Current P/L%'] > 0]['Investment']),0)
  total_loss = round(sum(df_portfolio_features[df_portfolio_features['Current P/L%'] < 0]['Current']) - sum(df_portfolio_features[df_portfolio_features['Current P/L%'] < 0]['Investment']),0)

  cy_booked_percentage = round((cy_booked_amt)*100/current,2)
  py_booked_percentage = round((py_booked_amt)*100/investment,2)
  total_booked_percentage = round((total_booked_amt)*100/investment,2)

  print('-------------------')
  print('Initial Investment: ', format_amt(investment))
  print('CY Investment: ', format_amt(cy_invested))
  print('Reserve: ', format_amt(reserve_amt))
  print('Current: ',  format_amt(current))
  print('-------------------')
  print('Today PnL: '+ '{} ({}%)'.format(format_amt(today_pnl_amount), today_pnl_percentage))
  print('Current PnL: '+ '{} ({}%)'.format(format_amt(curr_pnl_amount), curr_pnl_percentage))
  print('CY Booked + Current PnL: '+ '{} ({}%)'.format(format_amt(cy_pnl_amount), cy_pnl_percentage))
  print('-------------------')
  print('Total profit: ', format_amt(total_profit))
  print('Total loss: ', format_amt(total_loss))
  print('-------------------')
  print('Total Booked + Current PnL: '+ '{} ({}%)'.format(format_amt(overall_pnl_amount), overall_pnl_percentage))
  print('Total Booked PnL: '+ '{} ({}%)'.format(format_amt(total_booked_amt), total_booked_percentage))
  print('Curr Year Booked PnL: '+ '{} ({}%)'.format(format_amt(cy_booked_amt), cy_booked_percentage))
  print('Prev Year Booked PnL: '+ '{} ({}%)'.format(format_amt(py_booked_amt), py_booked_percentage))
  print('===================')
  print('Est FTT: ',  format_amt(estimate_st))
  print('Est FTT PnL: '+ '{} ({}%)'.format(format_amt(est_st_pnl_amount), est_st_pnl_percentage))

  print('===================')
  print('Deployed: ', format_amt(investment))

  print('Current: ', format_amt(current))

  print('CAGR/XIRR %: '+'{}%'.format(cagr))

In [8]:
# get start and end date
start_date, end_date = get_start_end_date()

# get portfolio and prospects data
mypfs_df = get_mypfs_df()
mypps_df = get_mypps_df()
myinvmt_df = get_myinvmt_df()

# merge above datasets
mypf_df = pd.merge(mypfs_df, mypps_df, on="Symbol")

# seggregate dm and sv portfolio
dm_pf = mypf_df[mypf_df['InPortfolio'] == 'DM']
sv_pf = mypf_df[mypf_df['InPortfolio'] == 'SV']

# build portfolio stock dataframe
dm_stocks = get_stock_ids(dm_pf)
sv_stocks = get_stock_ids(sv_pf)
df_stocks = pd.concat([dm_pf,sv_pf], ignore_index = True)

# arrange common and diff stock features
common_cols = ['Symbol', 'Target', 'Criteria', 'Strategy', 'CumlRnk', 'LatestQtr', 'StarStock', 'Conviction', 'Category', 'InFolio', 'XIRR', 'MBQ']
diff_cols = ['Symbol', 'AvgCost', 'Shares']
df_stocks = arrange_features(df_stocks, common_cols, diff_cols)

# get common features
stock_ids = df_stocks['Symbol'].values
df_common_features = get_common_features(stock_ids, df_stocks)

df_common_features.reset_index(drop=True, inplace=True)
df_common_features.drop(['Date'], axis=1, inplace=True)
# get and print portfolio features
df_portfolio_features = get_portfolio_features(df_common_features)

print_portfolio_stats(df_portfolio_features, myinvmt_df)

df = df_portfolio_features
#plot_pie_chart(df, 'CapType', 'Current')
list_ox40n = list(df[df['MBQ'].str.contains('OX40N', na=False)]['Symbol'].values)

Run date time (IST): 2026-05-20 15:25:29
-------------------
qualified stocks: 92
with latest results: 31
still star stocks: 20
-------------------
Initial Investment:  1.40 C
CY Investment:  1.82 C
Reserve:  1.49 K
Current:  1.48 C
-------------------
Today PnL: -33.78 K (-0.23%)
Current PnL: -35.37 L (-19.39%)
CY Booked + Current PnL: -33.29 L (-18.25%)
-------------------
Total profit:  1.97 L
Total loss:  -37.34 L
-------------------
Total Booked + Current PnL: 9.58 L (6.87%)
Total Booked PnL: 44.95 L (32.22%)
Curr Year Booked PnL: 2.08 L (1.41%)
Prev Year Booked PnL: 42.87 L (30.73%)
===================
Est FTT:  2.55 C
Est FTT PnL: 1.08 C (72.81%)
===================
Deployed:  1.40 C
Current:  1.48 C
CAGR/XIRR %: 2.8%

In [9]:
# top 5 near their targets
cols = ['Symbol', 'Today P/L%', 'Current P/L%', 'FTT%', 'OTT%', 'FTT Amt', 'Current P/L', 'Current', 'FTT', 'Dev%_PE', 'RSI_14','Conviction', 'Spread%',  'CumlRnk', 'RRR Ind', 'CurrAlloc%', 'Gained%', 'Criteria', 'Strategy', 'Category']
df_tmp = df_portfolio_features[~df_portfolio_features['Symbol'].isin(['ENRIN','BLUSPRING','DIGITIDE'])]
df_tmp = df_tmp.sort_values(by = 'FTT Amt', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
59,PIDILITIND,0.06,3.23,14.66,18.37,21355.0,4560.0,145670.0,1670.26,-27.64,58.0,X-LC,5.59,5.0,0.21,0.99,14.38,X40,ATH,CHEMICALS
51,KOTAKBANK,0.31,2.38,18.29,21.11,25929.0,3294.0,141766.0,453.24,-12.01,53.0,X-LC,7.73,12.0,0.13,0.96,8.42,X40,ATH,BANKS
55,MASFIN,-0.90,-5.14,28.16,21.57,26172.0,-5040.0,92940.0,397.04,-18.25,38.0,H-SC,5.43,167.0,-0.19,0.63,14.75,XR,ATH,FINANCE
83,TTKPRESTIG,4.00,-29.38,41.73,0.09,29700.0,-29605.0,71172.0,770.00,65.21,61.0,M-SC,16.46,250.0,-1.00,0.48,26.73,OX40N,NTT,DURABLES
53,M&M,0.96,1.30,21.80,23.38,30626.0,1805.0,140486.0,3802.40,-14.09,47.0,X-LC,8.71,25.0,0.06,0.95,6.51,X40N,ATH,AUTO

In [10]:
# top 5 today
df_tmp = df_portfolio_features.sort_values(by = 'Today P/L%', ascending=False)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
71,SIEMENS,4.05,-0.73,26.44,25.51,48843.0,-1365.0,184730.0,4671.50,55.24,54.0,H-LC,16.02,51.0,-0.03,1.25,29.70,AR,ATH,ELECTRICAL
30,HAPPSTMNDS,4.01,-53.19,294.86,84.85,176916.0,-68165.0,60000.0,1480.71,-44.39,52.0,H-SC,20.01,152.0,-0.39,0.41,11.11,AR,ATH,IT
83,TTKPRESTIG,4.00,-29.38,41.73,0.09,29700.0,-29605.0,71172.0,770.00,65.21,61.0,M-SC,16.46,250.0,-1.00,0.48,26.73,OX40N,NTT,DURABLES
37,HONAUT,3.83,-21.72,93.30,51.31,140836.0,-41888.0,150950.0,58357.33,-34.96,52.0,X-SC,12.11,90.0,-0.30,1.02,14.68,X40N,ATH,ELECTRICAL
43,INDIGOPNTS,2.99,-30.08,43.05,0.02,52544.0,-52506.0,122053.0,1408.00,86.38,65.0,M-SC,19.75,222.0,-1.00,0.83,38.48,OX40N,NTT,PAINTS

In [11]:
# bottom 5 today
df_tmp = df_portfolio_features.sort_values(by = 'Today P/L%', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
86,VALIANTORG,-3.68,-39.63,188.47,74.15,186152.0,-64835.0,98770.0,838.0,-277.79,55.0,H-SC,10.32,145.0,-0.35,0.67,46.98,XR,NTT,CHEMICALS
6,AWL,-2.76,-32.30,146.69,67.02,353857.0,-115081.0,241228.0,485.0,-63.54,49.0,X-SC,18.14,81.0,-0.33,1.63,14.10,XY24,NTT,FMCG
5,ATULAUTO,-2.63,-16.54,74.42,45.57,122440.0,-32606.0,164526.0,844.0,3564.86,51.0,M-SC,8.18,248.0,-0.27,1.11,26.61,XY24,NTT,AUTO
40,ICICIPRULI,-2.55,-15.80,55.25,30.73,91651.0,-31120.0,165885.0,790.0,-38.45,37.0,X-MC,12.12,78.0,-0.34,1.12,1.08,X40,ATH,INSURANCE
72,SIS,-2.51,-9.49,33.98,21.26,34149.0,-10536.0,100496.0,528.0,2390.16,64.0,H-SC,14.93,168.0,-0.31,0.68,49.42,OX40N,NTT,MISC

In [12]:
# top 5 to exit based on CumlRnk
df_tmp = df_portfolio_features[~df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])]
df_tmp = df_tmp[(df_tmp['Current P/L%'] > -1) & (df_tmp['Current P/L%'] < 1)].sort_values(by = 'CumlRnk', ascending=False)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
74,STARHEALTH,0.59,0.65,46.3,47.26,131011.0,1839.0,282962.0,761.0,58.79,60.0,H-SC,10.28,173.0,0.01,1.91,24.23,XY24,NTT,INSURANCE

In [13]:
# OX40N stocks to exit
df_tmp = df_portfolio_features[(df_portfolio_features['Symbol'].isin(list_ox40n))].sort_values(by = 'Current P/L%', ascending=False)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
25,FINCABLES,-1.36,31.96,57.56,107.91,112142.0,47182.0,194826.0,1641.55,18.72,56.0,M-SC,24.92,220.0,0.42,1.32,46.57,OX40N,ATH,CABLES
72,SIS,-2.51,-9.49,33.98,21.26,34149.0,-10536.0,100496.0,528.00,2390.16,64.0,H-SC,14.93,168.0,-0.31,0.68,49.42,OX40N,NTT,MISC
16,CERA,-0.74,-25.07,65.33,23.89,86113.0,-44090.0,131813.0,9475.00,-27.68,59.0,H-SC,7.87,153.0,-0.51,0.89,26.67,OX40N,NTT,CERAMICS
50,KANSAINER,-0.34,-28.32,58.31,13.47,112709.0,-76374.0,193293.0,340.00,-38.33,59.0,H-SC,13.90,162.0,-0.68,1.31,35.02,XY24,NTT,PAINTS
83,TTKPRESTIG,4.00,-29.38,41.73,0.09,29700.0,-29605.0,71172.0,770.00,65.21,61.0,M-SC,16.46,250.0,-1.00,0.48,26.73,OX40N,NTT,DURABLES

In [14]:
# top 5 to book for rotation
df_tmp = df_portfolio_features[(df_portfolio_features['Current P/L%'] > 20) ].sort_values(by = 'CumlRnk', ascending=False)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
25,FINCABLES,-1.36,31.96,57.56,107.91,112142.0,47182.0,194826.0,1641.55,18.72,56.0,M-SC,24.92,220.0,0.42,1.32,46.57,OX40N,ATH,CABLES
68,SATIN,0.13,23.36,23.09,51.83,78694.0,64532.0,340816.0,274.00,10.38,78.0,H-SC,29.17,159.0,0.82,2.31,66.03,XY24,NTT,FINANCE

In [15]:
# top 5 to monitor for exit
df_tmp = df_portfolio_features[~df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])]
df_tmp = df_tmp[(df_tmp['Current P/L%'] > 0) ].sort_values(by = 'Dev%_PE', ascending=False)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
74,STARHEALTH,0.59,0.65,46.30,47.26,131011.0,1839.0,282962.0,761.00,58.79,60.0,H-SC,10.28,173.0,0.01,1.91,24.23,XY24,NTT,INSURANCE
25,FINCABLES,-1.36,31.96,57.56,107.91,112142.0,47182.0,194826.0,1641.55,18.72,56.0,M-SC,24.92,220.0,0.42,1.32,46.57,OX40N,ATH,CABLES
68,SATIN,0.13,23.36,23.09,51.83,78694.0,64532.0,340816.0,274.00,10.38,78.0,H-SC,29.17,159.0,0.82,2.31,66.03,XY24,NTT,FINANCE
91,ZYDUSLIFE,2.12,9.72,23.61,35.63,54291.0,20376.0,229950.0,1286.17,-4.50,71.0,H-MC,2.84,120.0,0.38,1.56,20.90,AR,ATH,PHARMA
73,SONACOMS,1.60,1.90,36.49,39.09,37615.0,1925.0,103084.0,804.02,-19.25,56.0,M-MC,19.16,193.0,0.05,0.70,45.83,AR,ATH,AUTO

In [16]:
# top 5 to book for rotation from weak conviction
df_tmp = df_portfolio_features[~df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])]
df_tmp = df_tmp[~df_tmp['Criteria'].isin(['XY25','XY24','X40', 'X40N'])].sort_values(by = 'RRR Ind', ascending=False)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
25,FINCABLES,-1.36,31.96,57.56,107.91,112142.0,47182.0,194826.0,1641.55,18.72,56.0,M-SC,24.92,220.0,0.42,1.32,46.57,OX40N,ATH,CABLES
91,ZYDUSLIFE,2.12,9.72,23.61,35.63,54291.0,20376.0,229950.0,1286.17,-4.50,71.0,H-MC,2.84,120.0,0.38,1.56,20.90,AR,ATH,PHARMA
73,SONACOMS,1.60,1.90,36.49,39.09,37615.0,1925.0,103084.0,804.02,-19.25,56.0,M-MC,19.16,193.0,0.05,0.70,45.83,AR,ATH,AUTO
42,INDIAMART,0.95,-13.99,140.35,106.72,148883.0,-17256.0,106080.0,4810.62,-61.13,41.0,H-SC,10.12,140.0,-0.12,0.72,2.69,AR,ATH,MISC
55,MASFIN,-0.90,-5.14,28.16,21.57,26172.0,-5040.0,92940.0,397.04,-18.25,38.0,H-SC,5.43,167.0,-0.19,0.63,14.75,XR,ATH,FINANCE

In [17]:
# top 5 to accumulate based on lowest RSI_14
df_tmp = df_portfolio_features[df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])].sort_values(by = 'RSI_14', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
23,DMART,-1.98,-0.19,29.85,29.60,74362.0,-480.0,249120.0,5391.45,-15.86,36.0,X-LC,6.09,14.0,-0.01,1.69,13.87,X40N,ATH,FMCG
40,ICICIPRULI,-2.55,-15.80,55.25,30.73,91651.0,-31120.0,165885.0,790.00,-38.45,37.0,X-MC,12.12,78.0,-0.34,1.12,1.08,X40,ATH,INSURANCE
58,PGHH,-0.74,-27.81,82.86,32.01,127724.0,-59376.0,154144.0,17616.87,-51.15,37.0,X-MC,17.11,57.0,-0.46,1.04,5.43,X40,ATH,FMCG
33,HCLTECH,-0.87,-24.12,60.14,21.51,110395.0,-58360.0,183564.0,1872.35,-20.18,38.0,X-LC,18.27,8.0,-0.53,1.24,4.02,X40,ATH,IT
26,GILLETTE,0.25,-9.24,42.93,29.72,98930.0,-23451.0,230445.0,10978.86,-30.33,39.0,X-SC,8.77,83.0,-0.24,1.56,5.90,X40,ATH,FMCG

In [18]:
# top 5 to accumulate based on Spread and CumlRnk
df_tmp = df_portfolio_features[df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])]
df_tmp = df_tmp[(df_tmp['CumlRnk'] < 100)].sort_values(by = 'Spread%', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
88,VOLTAS,-0.44,1.46,43.11,45.20,83864.0,2793.0,194535.0,1856.00,16.12,44.0,X-MC,1.47,79.0,0.03,1.32,6.29,XY25,NTT,AC
84,UNITDSPR,-1.73,-5.80,28.21,20.77,62219.0,-13588.0,220556.0,1644.00,-16.49,46.0,X-MC,3.26,64.0,-0.22,1.49,5.21,X40N,NTT,BREWERIES
65,RELIANCE,2.89,-12.64,43.43,25.30,76244.0,-25407.0,175556.0,1952.00,-15.03,46.0,X-LC,3.63,21.0,-0.33,1.19,4.32,XY25,BTT,REFINERIES
39,ICICIGI,-2.34,-5.71,26.56,19.34,50116.0,-11418.0,188691.0,2252.93,-20.57,45.0,X-MC,4.97,66.0,-0.23,1.28,5.39,X40,ATH,INSURANCE
19,COLPAL,0.04,-16.88,70.25,41.51,153784.0,-44455.0,218910.0,3726.84,0.65,61.0,X-MC,5.46,62.0,-0.29,1.48,22.38,XY25,ATH,FMCG

In [19]:
# top 5 to accumulate based on lowest Gained%
df_tmp = df_portfolio_features[df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])].sort_values(by = 'Gained%', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
40,ICICIPRULI,-2.55,-15.80,55.25,30.73,91651.0,-31120.0,165885.0,790.00,-38.45,37.0,X-MC,12.12,78.0,-0.34,1.12,1.08,X40,ATH,INSURANCE
32,HAVELLS,0.07,-22.65,70.75,32.08,179493.0,-74290.0,253701.0,2062.85,-27.23,42.0,X-MC,12.26,63.0,-0.41,1.72,2.33,X40,ATH,ELECTRICAL
79,TCS,-0.08,-31.74,85.43,26.57,270153.0,-147046.0,316227.0,4311.59,-42.31,40.0,X-LC,16.84,2.0,-0.54,2.14,3.53,X40,ATH,IT
27,GLAXO,-1.90,-5.91,47.88,39.15,89781.0,-11772.0,187512.0,3466.20,-28.12,41.0,X-MC,6.32,56.0,-0.13,1.27,3.74,X40,ATH,PHARMA
34,HDFCBANK,-0.33,-9.09,41.20,28.37,87975.0,-21353.0,213532.0,1073.00,-22.51,42.0,X-LC,16.23,26.0,-0.24,1.44,3.88,X40,BTT,BANKS

In [20]:
# top 5 to accumulate based on lowest CurrAlloc%
df_tmp = df_portfolio_features[df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])].sort_values(by = 'CurrAlloc%', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
64,RELAXO,0.05,-62.33,304.26,52.31,166397.0,-90471.0,54689.0,1176.00,-59.93,45.0,X-SC,25.13,92.0,-0.54,0.37,22.28,X40N,NTT,FOOTWEAR
10,BATAINDIA,-0.54,-55.68,205.09,35.20,116944.0,-71649.0,57021.0,2096.00,-25.20,39.0,X-SC,25.99,91.0,-0.61,0.39,13.09,X40,NTT,FOOTWEAR
60,QUESS,-1.85,-17.30,110.27,73.90,97394.0,-18470.0,88323.0,424.00,-55.37,49.0,X-SC,11.32,80.0,-0.19,0.60,20.40,XY24,NTT,MISC
28,GODREJCP,0.25,-8.30,43.38,31.47,59115.0,-12342.0,136272.0,1469.04,-3.49,43.0,X-LC,8.11,32.0,-0.21,0.92,4.56,X40N,ATH,FMCG
53,M&M,0.96,1.30,21.80,23.38,30626.0,1805.0,140486.0,3802.40,-14.09,47.0,X-LC,8.71,25.0,0.06,0.95,6.51,X40N,ATH,AUTO

In [21]:
# top 5 to accumulate based on CumlRnk
df_tmp = df_portfolio_features.sort_values(by = 'CumlRnk', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
47,ITC,-0.84,-18.95,46.90,19.06,129303.0,-64467.0,275699.0,452.00,-55.52,51.0,X-LC,15.10,1.0,-0.50,1.87,6.95,X40,NTT,FMCG
79,TCS,-0.08,-31.74,85.43,26.57,270153.0,-147046.0,316227.0,4311.59,-42.31,40.0,X-LC,16.84,2.0,-0.54,2.14,3.53,X40,ATH,IT
45,INFY,-0.58,-19.00,65.73,34.24,166592.0,-59439.0,253449.0,1972.00,-36.14,49.0,X-LC,19.14,3.0,-0.36,1.71,8.67,X40,NTT,IT
81,TMPV,-0.06,-17.83,66.20,36.58,193575.0,-63431.0,292410.0,600.00,-82.53,59.0,X-LC,6.14,4.0,-0.33,1.98,21.88,XY24,NTT,AUTO
59,PIDILITIND,0.06,3.23,14.66,18.37,21355.0,4560.0,145670.0,1670.26,-27.64,58.0,X-LC,5.59,5.0,0.21,0.99,14.38,X40,ATH,CHEMICALS

In [22]:
# top 5 for average up
df_tmp = df_portfolio_features[(df_portfolio_features['Dev%_200'] > 5)].sort_values(by = 'CurrAlloc%', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
44,INDUSINDBK,0.52,-33.56,100.02,32.89,51304.0,-25912.0,51294.0,1800.00,-341.60,53.0,L-MC,8.11,258.0,-0.51,0.35,26.26,XR,NTT,BANKS
72,SIS,-2.51,-9.49,33.98,21.26,34149.0,-10536.0,100496.0,528.00,2390.16,64.0,H-SC,14.93,168.0,-0.31,0.68,49.42,OX40N,NTT,MISC
73,SONACOMS,1.60,1.90,36.49,39.09,37615.0,1925.0,103084.0,804.02,-19.25,56.0,M-MC,19.16,193.0,0.05,0.70,45.83,AR,ATH,AUTO
75,SURYODAY,-1.06,-8.39,34.30,23.03,56268.0,-15024.0,164047.0,216.00,79.82,55.0,H-SC,16.39,166.0,-0.27,1.11,38.12,XR,NTT,BANKS
71,SIEMENS,4.05,-0.73,26.44,25.51,48843.0,-1365.0,184730.0,4671.50,55.24,54.0,H-LC,16.02,51.0,-0.03,1.25,29.70,AR,ATH,ELECTRICAL

In [23]:
# top 5 RSP
df_tmp = df_portfolio_features.sort_values(by = 'RSP', ascending=False)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
68,SATIN,0.13,23.36,23.09,51.83,78694.0,64532.0,340816.0,274.00,10.38,78.0,H-SC,29.17,159.0,0.82,2.31,66.03,XY24,NTT,FINANCE
3,ALKYLAMINE,0.49,-24.40,156.13,93.63,119166.0,-24638.0,76325.0,4546.37,-19.07,65.0,H-SC,14.60,142.0,-0.21,0.52,44.12,SR,ATH,CHEMICALS
72,SIS,-2.51,-9.49,33.98,21.26,34149.0,-10536.0,100496.0,528.00,2390.16,64.0,H-SC,14.93,168.0,-0.31,0.68,49.42,OX40N,NTT,MISC
43,INDIGOPNTS,2.99,-30.08,43.05,0.02,52544.0,-52506.0,122053.0,1408.00,86.38,65.0,M-SC,19.75,222.0,-1.00,0.83,38.48,OX40N,NTT,PAINTS
56,MEDANTA,-0.10,6.00,19.93,27.12,37290.0,10587.0,187104.0,1486.00,2.73,66.0,X-SC,9.25,87.0,0.28,1.27,28.93,XY24,NTT,HEALTHCARE

In [24]:
# Top N allocation
df_tmp = df_portfolio_features.sort_values(by = 'CurrAlloc%', ascending=False)
top_n_values = [10, 25, 50]

sum_df = pd.DataFrame({
    'Top_N': top_n_values,
    'Sum_Alloc%': [df_tmp['CurrAlloc%'].head(n).sum() for n in top_n_values]
})

sum_df

   Top_N  Sum_Alloc%
0     10       19.54
1     25       43.05
2     50       72.97

In [25]:
# market-cap-wise allocation
df_tmp = df_portfolio_features[cols]
df_tmp.groupby(df_tmp['Conviction'].str[-2:])['CurrAlloc%'].sum().sort_values(ascending=False)

Conviction
SC    42.46
LC    31.68
MC    25.89
Name: CurrAlloc%, dtype: float64

In [26]:
# criteria-wise allocation
df_portfolio_features.groupby('Criteria')['CurrAlloc%'].sum().sort_values(ascending=False)

Criteria
XY24     27.44
X40      25.66
X40N     16.68
XR        8.89
OX40N     6.95
AR        6.82
XY25      6.72
SR        0.87
Name: CurrAlloc%, dtype: float64

In [27]:
# conviction-wise allocation
df_portfolio_features.groupby('Conviction')['CurrAlloc%'].sum().sort_values(ascending=False)

Conviction
X-LC    29.50
H-SC    22.32
X-MC    20.87
M-SC     9.94
X-SC     9.69
H-MC     2.73
M-MC     1.94
H-LC     1.25
M-LC     0.93
L-SC     0.51
L-MC     0.35
Name: CurrAlloc%, dtype: float64

In [28]:
# sector-wise stats
df_tmp = df_portfolio_features.groupby('Category')[['CurrAlloc%', 'Current', 'Current P/L', 'FTT Amt']].sum().sort_values(by=['Current', 'Current P/L'], ascending=False)
df_tmp['Current P/L%'] = round(df_tmp['Current P/L'] * 100 / df_tmp['Current'], 2)
df_tmp['FTT%'] = round(df_tmp['FTT Amt'] * 100 / df_tmp['Current'], 2)
cols = ['CurrAlloc%', 'Current P/L%', 'FTT%']
df_tmp[cols].sort_values(by=['CurrAlloc%'], ascending=False)

               CurrAlloc%  Current P/L%    FTT%
Category
FMCG                15.38        -16.42   57.45
FINANCE             10.83        -15.20   65.30
IT                  10.35        -47.22  121.34
MISC                 6.89        -31.64   88.83
AUTO                 6.70        -10.61   52.08
BANKS                5.61         -9.56   60.22
PAINTS               5.58        -19.75   40.55
INSURANCE            5.31         -5.38   41.24
PHARMA               5.11          1.93   29.59
ELECTRICAL           3.99        -19.94   62.64
CHEMICALS            2.18        -26.47  101.84
HEALTHCARE           2.05        -18.10   48.93
AC                   1.83        -18.61   50.77
APPARELS             1.81         -0.05   34.18
TRAVEL               1.70        -78.64  168.09
FOOTWEAR             1.65        -81.08  153.68
DURABLES             1.65        -58.59   97.17
BREWERIES            1.49         -6.16   28.21
REALTY               1.34        -11.90   30.29
CERAMICS             1.34        -55.05  102.15
CABLES               1.32         24.22   57.56
REFINERIES           1.19        -14.47   43.43
ENGINEERING          1.15        -42.28  107.35
CEMENT               1.10        -65.35  189.05
JEWELLERY            1.05       -106.11  177.72
ENTERTAINMENT        0.70        -85.90  196.77
TEXTILES             0.41        -53.96   97.86
HOTELS               0.32       -143.37  229.22

In [29]:
# money to be made criteria-wise
df_portfolio_features.groupby('Criteria')['FTT Amt'].agg(['sum', 'count']).sort_values(by='sum', ascending=False)

                sum  count
Criteria
XY24      3541242.0     21
X40       1911074.0     19
XR        1369994.0     13
X40N      1257754.0     13
AR        1178370.0      9
OX40N      765600.0     10
XY25       447059.0      5
SR         290864.0      2

In [30]:
# money to be made conviction-wise
df_portfolio_features.groupby('Conviction')['FTT Amt'].agg(['sum', 'count']).sort_values(by='sum', ascending=False)

                  sum  count
Conviction
H-SC        3489042.0     24
X-LC        1938122.0     21
X-MC        1647276.0     15
M-SC        1448048.0     14
X-SC        1373658.0      9
H-MC         295740.0      2
L-SC         215461.0      2
M-LC         155034.0      1
M-MC          99429.0      2
L-MC          51304.0      1
H-LC          48843.0      1

In [31]:
# money to be made criteria and conviction-wise
df_portfolio_features.groupby(['Conviction', 'Criteria'])['FTT Amt'].agg(['sum', 'count']).sort_values(by='sum', ascending=False)

                           sum  count
Conviction Criteria
H-SC       XY24      1084114.0      6
X-LC       X40       1018158.0     10
H-SC       AR         960581.0      5
M-SC       XY24       857804.0      6
H-SC       XR         820698.0      7
X-SC       XY24       795097.0      4
X-MC       X40        677042.0      7
           X40N       514085.0      4
X-LC       X40N       380982.0      6
X-SC       X40N       362687.0      3
X-LC       XY24       344277.0      2
H-SC       OX40N      332785.0      4
M-SC       OX40N      324299.0      5
H-SC       SR         290864.0      2
H-MC       XY24       241449.0      1
X-MC       XY25       237648.0      2
           XY24       218501.0      2
X-SC       X40        215874.0      2
M-SC       XR         188905.0      2
M-LC       XR         155034.0      1
X-LC       XY25       147597.0      2
L-SC       OX40N      108516.0      1
           XR         106945.0      1
M-SC       AR          77040.0      1
M-MC       XY25        61814.0      1
H-MC       AR          54291.0      1
L-MC       XR          51304.0      1
H-LC       AR          48843.0      1
X-LC       XR          47108.0      1
M-MC       AR          37615.0      1

In [32]:
# notebook execution time

end_time = time.time()
execution_time = round(end_time - start_time, 0)
print(f"Notebook execution time: {execution_time} seconds")

Notebook execution time: 63.0 seconds