<a href="https://colab.research.google.com/github/ankit-rathi/Quantvesting_v2/blob/main/myStocks_Portfolio_Analysis.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
'''
!pip install pandas==2.2.2 -qq
!pip install pyxirr -qq
!pip install ta -qq
!pip install yfinance==0.2.59 -qq
'''

'\n!pip install pandas==2.2.2 -qq\n!pip install pyxirr -qq\n!pip install ta -qq\n!pip install yfinance==0.2.59 -qq\n'

In [2]:
# import libraries

import numpy as np
import pandas as pd
import datetime
import warnings
warnings.filterwarnings('ignore')
import yfinance as yfin
import ta
import matplotlib.pyplot as plt
import requests

In [3]:
# notebook start time
import time
import datetime
import pytz

start_time = time.time()

# function to print date timestamp
def print_date_time():
  tz_NY = pytz.timezone('Asia/Kolkata')
  datetime_NY = datetime.datetime.now(tz_NY)
  print("Run date time (IST):", datetime_NY.strftime("%Y-%m-%d %H:%M:%S"))

In [4]:
# function to get booked and reserved amount
def get_amt():
  # fetch the JSON data from the URL
  url = "https://raw.githubusercontent.com/ankit-rathi/Tradevesting_v1/main/data/myPortfolioAmts.json"
  response = requests.get(url)
  pf_amts = response.json()  # parse the JSON data

  # extract values from the JSON
  py_booked_amt_dm = pf_amts["py_booked_amt_dm"]
  py_booked_amt_sv = pf_amts["py_booked_amt_sv"]
  cy_booked_amt_dm = pf_amts["cy_booked_amt_dm"]
  cy_booked_amt_sv = pf_amts["cy_booked_amt_sv"]
  reserve_amt_dm = pf_amts["reserve_amt_dm"]
  reserve_amt_sv = pf_amts["reserve_amt_sv"]

  # perform calculations
  py_booked_amt = py_booked_amt_dm + py_booked_amt_sv
  cy_booked_amt = cy_booked_amt_dm + cy_booked_amt_sv
  reserve_amt = reserve_amt_dm + reserve_amt_sv
  total_booked_amt = py_booked_amt + cy_booked_amt

  return total_booked_amt, reserve_amt, cy_booked_amt, py_booked_amt

gen_output = 0

In [5]:
# function to format the amount
def format_amt(number):
    abs_number = abs(number)

    if abs_number >= 1_00_00_000:  # Crores
        formatted_amt = f"{number / 1_00_00_000:.2f} C"
    elif abs_number >= 1_00_000:  # Lakhs
        formatted_amt = f"{number / 1_00_000:.2f} L"
    elif abs_number >= 1_000:  # Thousands
        formatted_amt = f"{number / 1_000:.2f} K"
    else:
        formatted_amt = f"{number:.2f}"

    return formatted_amt

# function to set start and end date
def get_start_end_date():
  start_date = (datetime.date.today() + datetime.timedelta(days=-365)).strftime('%Y-%m-%d')
  end_date = (datetime.date.today() + datetime.timedelta(days=1)).strftime('%Y-%m-%d')
  return start_date, end_date

# function to fetch my portfolio csv
def get_mypfs_df():
  mypfs_df = pd.read_csv('https://raw.githubusercontent.com/ankit-rathi/Tradevesting_v1/main/data/myPortfolioStocks.csv')
  return mypfs_df

# function to fetch my prospects csv
def get_mypps_df():
  mypps_df = pd.read_csv('https://raw.githubusercontent.com/ankit-rathi/Tradevesting_v1/main/data/myProspectsScrips.csv')
  return mypps_df

# function to fetch screener data
def get_myscreen_df():
  myscreen_df = pd.read_csv('https://raw.githubusercontent.com/ankit-rathi/Tradevesting_v1/main/data/myScreenerDB.csv')
  return myscreen_df

# function to fetch momentum data
def get_myinvmt_df():
  myinvmt_df = pd.read_csv('https://raw.githubusercontent.com/ankit-rathi/Tradevesting_v1/main/data/myInvestments.csv')
  return myinvmt_df

# function to get the stock ids
def get_stock_ids(df_pf):
  stock_n100 = df_pf['Symbol'].unique()

  exclude = ['CADILAHC','MMTC', 'MASFIN']

  stock_ids = df_pf[~df_pf['Symbol'].isin(exclude) ]['Symbol'].unique()

  #mypf = mypf[mypf.Forecast.notnull()]
  #stock_ids = mypf['Symbol'].unique()

  #stock_ids.sort()
  return stock_ids

# get features from screener data
def get_screener_features():
  myscreen_df = get_myscreen_df()
  cols = ['Symbol', 'EPS', 'MedPE', 'ROCE%', 'ROE%', 'CapType']
  return myscreen_df[cols]

# get relative strength
def get_relative_strength(stock_list):

    # Dictionary to store stock tickers and their corresponding percentage price change
    stock_changes = {}

    # Loop through each stock and fetch its price data
    for stock in stock_list:
        try:
            # Download the stock data for the given date range
            stock_data = yfin.Ticker(stock + '.NS').history(period='1mo', interval='1d')[map(str.title, ['open', 'close', 'low', 'high', 'volume'])]

            # Calculate the percentage change for the stock
            if len(stock_data) > 0:
                start_price = stock_data['Close'].iloc[0]
                end_price = stock_data['Close'].iloc[-1]
                percent_change = round(((end_price - start_price) / start_price) * 100, 2)
                stock_changes[stock] = percent_change
            else:
                stock_changes[stock] = np.nan  # If no data is available, set to NaN

        except Exception as e:
            print(f"Error fetching data for {stock}: {e}")
            stock_changes[stock] = np.nan

    # Create a DataFrame with stock tickers and their percentage changes
    df = pd.DataFrame(list(stock_changes.items()), columns=['Symbol', 'Percent_Change'])

    # Drop any stocks with missing data (NaN values)
    df = df.dropna()

    # Calculate the percentile rank based on percentage change
    df['RSP'] = round(df['Percent_Change'].rank(pct=True) * 100, 2)
    cols = ['Symbol', 'RSP']
    df = df[cols]
    # Sort by percentile rank (optional)
    df = df.sort_values(by='RSP', ascending=False).reset_index(drop=True)

    return df

In [6]:
# function to get stock technicals
def stock_prec_dev(stock_symbol):
    #stock_symbol = 'ULTRACEMCO.NS'
    short_window = 20
    mid_window = 50
    long_window = 200
    moving_avg = 'SMA'

    start = datetime.datetime(*map(int, start_date.split('-')))
    end = datetime.datetime(*map(int, end_date.split('-')))

    stock_df = yfin.Ticker(stock_symbol + '.NS').history(period='max', interval='1d')[map(str.title, ['open', 'close', 'low', 'high', 'volume'])]

    stock_df['Max'] = round(max(stock_df['Close']),2)
    stock_df = stock_df[(stock_df.index <= end_date) & (stock_df.index >= start_date)]
    stock_df['200_SMA'] = round(stock_df['Close'].rolling(window = 200, min_periods = 1).mean(),0)
    stock_df['Dev%_200'] = round((stock_df['Close'] - stock_df['200_SMA'])*100/stock_df['200_SMA'],2)
    stock_df.dropna(axis = 0, inplace = True) # remove any null rows

    stock_df['20_SMA'] = stock_df['Close'].rolling(window=20).mean()
    stock_df['50_SMA'] = stock_df['Close'].rolling(window=50).mean()
    stock_df['Symbol'] = stock_symbol

    stock_df['Close'] = round(stock_df['Close'],2)
    stock_df['Min'] = round(min(stock_df['Close']),2)
    stock_df['RSI_14'] = ta.momentum.RSIIndicator(close=stock_df['Close'], window=14).rsi()
    stock_df['RSI_14'] = round(stock_df['RSI_14'],0)
    stock_df['Prev_Close'] = stock_df['Close'].shift(1)
    stock_df.drop(['Open', 'Low', 'High', 'Volume'], axis=1, inplace=True)
    stock_df = stock_df.tail(1)

    max_SMA = max(stock_df['20_SMA'].item(), stock_df['50_SMA'].item(), stock_df['200_SMA'].item())
    min_SMA = min(stock_df['20_SMA'].item(), stock_df['50_SMA'].item(), stock_df['200_SMA'].item())
    ABS_Spread = max_SMA - min_SMA
    stock_df['Spread%'] = round((ABS_Spread / stock_df['200_SMA'].item()) * 100,2)

    return stock_df

# function to compute stock attributes
def get_common_features(stock_ids, df_mypf):

  df_prec_dev = pd.DataFrame()
  df_tmp = get_screener_features()
  df_rs = get_relative_strength(stock_ids)

  for stock_id in stock_ids:
      tmp = stock_prec_dev(stock_id)
      tmp = tmp.reset_index()
      df_prec_dev = pd.concat([df_prec_dev, tmp], ignore_index = True)
  df_prec_dev = pd.merge(df_prec_dev, df_mypf, on= 'Symbol')
  df_prec_dev = pd.merge(df_prec_dev, df_tmp, on= 'Symbol', how='left')
  df_prec_dev = pd.merge(df_prec_dev, df_rs, on= 'Symbol', how='left')
  #print(df_prec_dev.columns)
  df_prec_dev['Curr_PE'] = round(df_prec_dev['Close']/df_prec_dev['EPS'],1)
  df_prec_dev['Dev%_PE'] = round((df_prec_dev['Curr_PE'] - df_prec_dev['MedPE'])*100/df_prec_dev['MedPE'],2)
  df_prec_dev['Conviction'] = df_prec_dev['Conviction'] + '-' + df_prec_dev['CapType']
  return df_prec_dev

# function to arrange stock features
def arrange_features(df_stocks, common_cols, diff_cols):
  df_stocks_common = df_stocks[common_cols].drop_duplicates()
  df_stocks_diff = df_stocks[diff_cols]
  df_stocks_diff['Investment'] = df_stocks_diff['AvgCost'] * df_stocks_diff['Shares']
  df_stocks_diff = df_stocks_diff.groupby(['Symbol'])[['Shares', 'Investment']].aggregate(['sum']).reset_index()
  df_stocks_diff.columns = ['Symbol', 'Shares', 'Investment']
  df_stocks_diff['AvgCost'] = round(df_stocks_diff['Investment']/df_stocks_diff['Shares'],2)
  df_stocks = pd.merge(df_stocks_diff, df_stocks_common, on='Symbol')
  return df_stocks

# plot fact distribution across dimension
def plot_pie_chart(df, dimension, fact):
  # grouping the data by category and calculating the sum of fact for each type
  grouped_data = df.groupby(dimension)[fact].sum()

  # sorting the grouped data in descending order
  grouped_data = grouped_data.sort_values(ascending=False)

  # creating a pie chart
  grouped_data.plot.pie(autopct='%1.1f%%', startangle=90, figsize=(6, 6))

  # adding a title and displaying the plot
  plt.title(f'{dimension} {fact} Distribution')
  plt.ylabel('')  # To hide the y-label
  plt.show()

In [7]:
# function to get portfolio features

def get_portfolio_features(df_common_features):

  print_date_time()
  print('-------------------')

  #df_common_features["Target"] = df_common_features["Target"].fillna(df_common_features["Max"])
  df_common_features['NTT'] = np.where(df_common_features['Strategy']== 'NTT', df_common_features["Target"], df_common_features['Max'])
  df_common_features['LTT'] = np.where(df_common_features['Strategy']== 'BTT', df_common_features["Target"], df_common_features['Max'])
  df_common_features['BOL'] = df_common_features['Min']

  tmp_df = df_common_features[df_common_features['Symbol'].isin(mypf_df[mypf_df['InPortfolio'] != 'NA'].Symbol.values)]
  print('qualified stocks: '+str(len(tmp_df['Symbol'].unique())))
  tmp_df1 = tmp_df[tmp_df['LatestQtr'] == 1]
  print('with latest results: '+str(len(tmp_df1['Symbol'].unique())))
  tmp_df1 = tmp_df1[tmp_df1['StarStock'] == 1]
  print('still star stocks: '+str(len(tmp_df1['Symbol'].unique())))
  tmp_df['Investment'] = tmp_df['AvgCost'] * tmp_df['Shares']
  tmp_df['Current'] = round(tmp_df['Close'] * tmp_df['Shares'],0)
  tmp_df['Previous'] = tmp_df['Prev_Close'] * tmp_df['Shares']
  tmp_df['EstimatedST'] = tmp_df['NTT'] * tmp_df['Shares']
  tmp_df['EstimatedLT'] = tmp_df['LTT'] * tmp_df['Shares']
  tmp_df['Current P/L'] = round((tmp_df['Current'] - tmp_df['Investment']),0)
  tmp_df['Today P/L%'] = round((tmp_df['Current'] - tmp_df['Previous'])*100/tmp_df['Previous'],2)
  tmp_df['Current P/L%'] = round((tmp_df['Current'] - tmp_df['Investment'])*100/tmp_df['Investment'],2)
  tmp_df['EstimatedST P/L%'] = round((tmp_df['EstimatedST'] - tmp_df['Investment'])*100/tmp_df['Investment'],2)
  tmp_df['EstimatedLT P/L%'] = round((tmp_df['EstimatedLT'] - tmp_df['Investment'])*100/tmp_df['Investment'],2)
  tmp_df['NTT%'] = round((tmp_df['NTT'] - tmp_df['Close'])*100/tmp_df['Close'],2)
  tmp_df['LTT%'] = round((tmp_df['LTT'] - tmp_df['Close'])*100/tmp_df['Close'],2)
  tmp_df['Gained%'] = round((tmp_df['Close'] - tmp_df['BOL'])*100/tmp_df['BOL'],2)
  investment = round(sum(tmp_df['AvgCost']*tmp_df['Shares']),0)
  current = round(sum(tmp_df['Close']*tmp_df['Shares']),0)
  tmp_df['InitAlloc%'] = round(tmp_df['Investment']*100/investment,2)
  tmp_df['CurrAlloc%'] = round(tmp_df['Current']*100/current,2)
  tmp_df['FTT'] = tmp_df['LTT']
  tmp_df.loc[tmp_df['Strategy'] == 'NTT', 'FTT'] = tmp_df['NTT']
  tmp_df['FTT%'] = tmp_df['LTT%']
  tmp_df.loc[tmp_df['Strategy'] == 'NTT', 'FTT%'] = tmp_df['NTT%']
  tmp_df['FTT Amt'] = round(tmp_df['FTT%'] * tmp_df['Current']/100,0)
  tmp_df['OTT%'] = round((tmp_df['FTT'] - tmp_df['AvgCost'])*100/tmp_df['AvgCost'],2)
  tmp_df['RRR Ind'] = round(tmp_df['Current P/L']/tmp_df['FTT Amt'],2)
  tmp_df['Risk Ind'] = round(tmp_df['Current P/L%']*tmp_df['CurrAlloc%'],0)

  return tmp_df

# function to print portfolio features
def print_portfolio_stats(df_portfolio_features, myinvmt_df):
  from pyxirr import xirr

  total_booked_amt, reserve_amt, cy_booked_amt, py_booked_amt = get_amt()

  dates = myinvmt_df['Date'].values
  dates = np.append(dates, datetime.date.today().strftime('%d-%b-%y'))
  investment = myinvmt_df['Investment'].values
  dates= pd.to_datetime(dates)

  current = round(sum(df_portfolio_features['Close']*df_portfolio_features['Shares']),0) + reserve_amt
  investment_xirr = np.append(investment, current)
  cagr = round(xirr(pd.DataFrame({"dates": dates, "amounts": investment_xirr}))*100,2)

  investment = -sum(investment)
  invested = round(sum(df_portfolio_features['AvgCost']*df_portfolio_features['Shares']),0) + reserve_amt
  previous = round(sum(df_portfolio_features['Prev_Close']*df_portfolio_features['Shares']),0) + reserve_amt
  cy_invested = investment + py_booked_amt

  today_pnl_amount = current-previous
  today_pnl_percentage = round((current-previous)*100/previous,2)

  curr_pnl_amount = current-invested
  curr_pnl_percentage = round((curr_pnl_amount)*100/(cy_invested),2)

  cy_pnl_amount = cy_booked_amt + curr_pnl_amount
  cy_pnl_percentage = round((cy_pnl_amount)*100/cy_invested,2)

  overall_pnl_amount = total_booked_amt + curr_pnl_amount
  overall_pnl_percentage = round((overall_pnl_amount)*100/investment,2)

  estimate_st = round(sum(df_portfolio_features['FTT']*df_portfolio_features['Shares']),0)  + reserve_amt
  est_st_pnl_amount = estimate_st-current
  est_st_pnl_percentage = round((est_st_pnl_amount)*100/current,2)

  estimate_lt = round(sum(df_portfolio_features['LTT']*df_portfolio_features['Shares']),0)  + reserve_amt
  est_lt_pnl_amount = estimate_lt-current
  est_lt_pnl_percentage = round((est_lt_pnl_amount)*100/current,2)

  total_profit = round(sum(df_portfolio_features[df_portfolio_features['Current P/L%'] > 0]['Current']) - sum(df_portfolio_features[df_portfolio_features['Current P/L%'] > 0]['Investment']),0)
  total_loss = round(sum(df_portfolio_features[df_portfolio_features['Current P/L%'] < 0]['Current']) - sum(df_portfolio_features[df_portfolio_features['Current P/L%'] < 0]['Investment']),0)

  cy_booked_percentage = round((cy_booked_amt)*100/current,2)
  py_booked_percentage = round((py_booked_amt)*100/investment,2)
  total_booked_percentage = round((total_booked_amt)*100/investment,2)

  print('-------------------')
  print('Initial Investment: ', format_amt(investment))
  print('CY Investment: ', format_amt(cy_invested))
  print('Reserve: ', format_amt(reserve_amt))
  print('Current: ',  format_amt(current))
  print('-------------------')
  print('Today PnL: '+ '{} ({}%)'.format(format_amt(today_pnl_amount), today_pnl_percentage))
  print('Current PnL: '+ '{} ({}%)'.format(format_amt(curr_pnl_amount), curr_pnl_percentage))
  print('CY Booked + Current PnL: '+ '{} ({}%)'.format(format_amt(cy_pnl_amount), cy_pnl_percentage))
  print('-------------------')
  print('Total profit: ', format_amt(total_profit))
  print('Total loss: ', format_amt(total_loss))
  print('-------------------')
  print('Total Booked + Current PnL: '+ '{} ({}%)'.format(format_amt(overall_pnl_amount), overall_pnl_percentage))
  print('Total Booked PnL: '+ '{} ({}%)'.format(format_amt(total_booked_amt), total_booked_percentage))
  print('Curr Year Booked PnL: '+ '{} ({}%)'.format(format_amt(cy_booked_amt), cy_booked_percentage))
  print('Prev Year Booked PnL: '+ '{} ({}%)'.format(format_amt(py_booked_amt), py_booked_percentage))
  print('===================')
  print('Est FTT: ',  format_amt(estimate_st))
  print('Est FTT PnL: '+ '{} ({}%)'.format(format_amt(est_st_pnl_amount), est_st_pnl_percentage))

  print('===================')
  print('Deployed: ', format_amt(investment))

  print('Current: ', format_amt(current))

  print('CAGR/XIRR %: '+'{}%'.format(cagr))

In [8]:
# get start and end date
start_date, end_date = get_start_end_date()

# get portfolio and prospects data
mypfs_df = get_mypfs_df()
mypps_df = get_mypps_df()
myinvmt_df = get_myinvmt_df()

# merge above datasets
mypf_df = pd.merge(mypfs_df, mypps_df, on="Symbol")

# seggregate dm and sv portfolio
dm_pf = mypf_df[mypf_df['InPortfolio'] == 'DM']
sv_pf = mypf_df[mypf_df['InPortfolio'] == 'SV']

# build portfolio stock dataframe
dm_stocks = get_stock_ids(dm_pf)
sv_stocks = get_stock_ids(sv_pf)
df_stocks = pd.concat([dm_pf,sv_pf], ignore_index = True)

# arrange common and diff stock features
common_cols = ['Symbol', 'Target', 'Criteria', 'Strategy', 'CumlRnk', 'LatestQtr', 'StarStock', 'Conviction', 'Category', 'InFolio', 'XIRR', 'MBQ']
diff_cols = ['Symbol', 'AvgCost', 'Shares']
df_stocks = arrange_features(df_stocks, common_cols, diff_cols)

# get common features
stock_ids = df_stocks['Symbol'].values
df_common_features = get_common_features(stock_ids, df_stocks)

df_common_features.reset_index(drop=True, inplace=True)
df_common_features.drop(['Date'], axis=1, inplace=True)
# get and print portfolio features
df_portfolio_features = get_portfolio_features(df_common_features)

print_portfolio_stats(df_portfolio_features, myinvmt_df)

df = df_portfolio_features
#plot_pie_chart(df, 'CapType', 'Current')
list_ox40n = list(df[df['MBQ'].str.contains('OX40N', na=False)]['Symbol'].values)

Run date time (IST): 2026-04-21 15:48:30
-------------------
qualified stocks: 85
with latest results: 25
still star stocks: 15
-------------------
Initial Investment:  1.36 C
CY Investment:  1.78 C
Reserve:  1.61 K
Current:  1.41 C
-------------------
Today PnL: 1.15 L (0.82%)
Current PnL: -33.15 L (-18.59%)
CY Booked + Current PnL: -32.19 L (-18.05%)
-------------------
Total profit:  1.78 L
Total loss:  -34.94 L
-------------------
Total Booked + Current PnL: 10.68 L (7.88%)
Total Booked PnL: 43.83 L (32.35%)
Curr Year Booked PnL: 96.00 K (0.68%)
Prev Year Booked PnL: 42.87 L (31.64%)
===================
Est FTT:  2.44 C
Est FTT PnL: 1.03 C (73.21%)
===================
Deployed:  1.36 C
Current:  1.41 C
CAGR/XIRR %: 1.88%

In [9]:
# top 5 near their targets
cols = ['Symbol', 'Today P/L%', 'Current P/L%', 'FTT%', 'OTT%', 'FTT Amt', 'Current P/L', 'Current', 'FTT', 'Dev%_PE', 'RSI_14','Conviction', 'Spread%',  'CumlRnk', 'RRR Ind', 'CurrAlloc%', 'Gained%', 'Criteria', 'Strategy', 'Category']
df_tmp = df_portfolio_features[~df_portfolio_features['Symbol'].isin(['ENRIN','BLUSPRING','DIGITIDE'])]
df_tmp = df_tmp.sort_values(by = 'FTT Amt', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
49,MASFIN,0.32,-3.28,25.69,21.57,24346.0,-3210.0,94770.0,397.04,-16.44,56.0,H-SC,3.30,167.0,-0.13,0.67,22.47,XR,ATH,FINANCE
1,ABB,1.36,33.11,9.36,45.57,32595.0,86621.0,348240.0,7934.00,-14.42,77.0,H-MC,18.41,125.0,2.66,2.47,54.64,AR,NTT,ELECTRICAL
56,RECLTD,0.17,3.78,16.34,20.74,34452.0,7672.0,210842.0,446.00,15.23,71.0,M-MC,4.83,191.0,0.22,1.50,25.65,XY25,NTT,FINANCE
76,TTKPRESTIG,1.29,-34.88,53.69,0.09,35237.0,-35146.0,65631.0,770.00,52.40,56.0,M-SC,22.93,250.0,-1.00,0.47,16.86,OX40N,NTT,DURABLES
66,SONACOMS,0.82,0.56,38.31,39.09,38972.0,568.0,101727.0,804.02,-20.33,64.0,M-MC,10.47,193.0,0.01,0.72,43.91,AR,ATH,AUTO

In [10]:
# top 5 today
df_tmp = df_portfolio_features.sort_values(by = 'Today P/L%', ascending=False)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
40,INDIGOPNTS,4.60,-37.89,61.04,0.02,66175.0,-66146.0,108413.0,1408.00,65.18,62.0,M-SC,27.57,222.0,-1.00,0.77,23.00,OX40N,NTT,PAINTS
4,ALKYLAMINE,4.45,-37.38,209.21,93.63,132269.0,-37740.0,63223.0,4546.37,-32.89,60.0,H-SC,23.85,142.0,-0.29,0.45,19.38,SR,ATH,CHEMICALS
77,UNITDSPR,4.23,0.12,20.62,20.77,48341.0,292.0,234436.0,1644.00,-11.25,61.0,X-MC,6.13,64.0,0.01,1.66,11.83,X40N,NTT,BREWERIES
52,PGHH,4.10,-22.52,70.38,32.01,116437.0,-48080.0,165440.0,17616.87,-47.53,57.0,X-MC,21.30,57.0,-0.41,1.17,13.15,X40,ATH,FMCG
80,VBL,3.98,-2.01,38.28,35.50,118474.0,-6348.0,309494.0,670.80,-13.53,71.0,X-LC,9.76,13.0,-0.05,2.20,27.08,X40N,ATH,FMCG

In [11]:
# bottom 5 today
df_tmp = df_portfolio_features.sort_values(by = 'Today P/L%', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
54,RAJESHEXPO,-4.77,-77.45,343.72,0.07,106333.0,-106241.0,30936.0,518.00,1033.84,53.0,L-SC,41.18,268.0,-1.00,0.22,45.24,OX40N,NTT,JEWELLERY
36,ICICIGI,-1.95,-2.53,22.44,19.34,43767.0,-5069.0,195040.0,2252.93,-18.12,54.0,X-MC,7.13,66.0,-0.12,1.38,8.93,X40,ATH,INSURANCE
37,ICICIPRULI,-1.40,-8.97,43.61,30.73,78207.0,-17672.0,179333.0,790.00,-33.41,45.0,X-MC,12.95,78.0,-0.23,1.27,9.28,X40,ATH,INSURANCE
18,COFFEEDAY,-1.16,-54.11,194.77,35.27,101493.0,-61440.0,52109.0,80.00,-65.79,54.0,L-SC,31.23,266.0,-0.61,0.37,28.50,XR,NTT,HOTELS
51,PAGEIND,-1.16,-0.99,35.45,34.11,94198.0,-2659.0,265720.0,51418.64,-29.03,74.0,X-MC,14.66,55.0,-0.03,1.89,25.70,X40,ATH,APPARELS

In [12]:
# top 5 to exit based on CumlRnk
df_tmp = df_portfolio_features[~df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])]
df_tmp = df_tmp[(df_tmp['Current P/L%'] > -1) & (df_tmp['Current P/L%'] < 1)].sort_values(by = 'CumlRnk', ascending=False)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
66,SONACOMS,0.82,0.56,38.31,39.09,38972.0,568.0,101727.0,804.02,-20.33,64.0,M-MC,10.47,193.0,0.01,0.72,43.91,AR,ATH,AUTO
67,STARHEALTH,1.50,-0.53,48.04,47.26,134340.0,-1480.0,279643.0,761.00,56.93,75.0,H-SC,2.53,173.0,-0.01,1.98,44.82,XY24,NTT,INSURANCE

In [13]:
# OX40N stocks to exit
df_tmp = df_portfolio_features[(df_portfolio_features['Symbol'].isin(list_ox40n))].sort_values(by = 'Current P/L%', ascending=False)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
25,FINCABLES,0.73,20.77,72.16,107.91,128664.0,30660.0,178304.0,1641.55,8.57,68.0,M-SC,3.45,220.0,0.24,1.27,34.14,OX40N,ATH,CABLES
65,SIS,3.26,-22.60,56.68,21.26,48708.0,-25097.0,85935.0,528.00,2029.53,75.0,H-SC,10.14,168.0,-0.52,0.61,27.77,OX40N,NTT,MISC
17,CERA,-0.21,-30.76,78.94,23.89,96141.0,-54113.0,121790.0,9475.00,-33.17,66.0,H-SC,13.52,153.0,-0.56,0.86,17.04,OX40N,NTT,CERAMICS
47,KANSAINER,1.06,-31.17,64.86,13.47,120391.0,-84051.0,185616.0,340.00,-40.82,67.0,H-SC,20.11,162.0,-0.70,1.32,29.65,XY24,NTT,PAINTS
71,TATAELXSI,2.97,-32.97,96.98,32.03,85694.0,-43472.0,88363.0,9161.00,-16.16,61.0,H-SC,18.30,158.0,-0.51,0.63,16.95,OX40N,NTT,IT

In [14]:
# top 5 to book for rotation
df_tmp = df_portfolio_features[(df_portfolio_features['Current P/L%'] > 20) ].sort_values(by = 'CumlRnk', ascending=False)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
25,FINCABLES,0.73,20.77,72.16,107.91,128664.0,30660.0,178304.0,1641.55,8.57,68.0,M-SC,3.45,220.0,0.24,1.27,34.14,OX40N,ATH,CABLES
1,ABB,1.36,33.11,9.36,45.57,32595.0,86621.0,348240.0,7934.00,-14.42,77.0,H-MC,18.41,125.0,2.66,2.47,54.64,AR,NTT,ELECTRICAL

In [15]:
# top 5 to monitor for exit
df_tmp = df_portfolio_features[~df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])]
df_tmp = df_tmp[(df_tmp['Current P/L%'] > 0) ].sort_values(by = 'Dev%_PE', ascending=False)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
56,RECLTD,0.17,3.78,16.34,20.74,34452.0,7672.0,210842.0,446.00,15.23,71.0,M-MC,4.83,191.0,0.22,1.50,25.65,XY25,NTT,FINANCE
25,FINCABLES,0.73,20.77,72.16,107.91,128664.0,30660.0,178304.0,1641.55,8.57,68.0,M-SC,3.45,220.0,0.24,1.27,34.14,OX40N,ATH,CABLES
1,ABB,1.36,33.11,9.36,45.57,32595.0,86621.0,348240.0,7934.00,-14.42,77.0,H-MC,18.41,125.0,2.66,2.47,54.64,AR,NTT,ELECTRICAL
66,SONACOMS,0.82,0.56,38.31,39.09,38972.0,568.0,101727.0,804.02,-20.33,64.0,M-MC,10.47,193.0,0.01,0.72,43.91,AR,ATH,AUTO

In [16]:
# top 5 to book for rotation from weak conviction
df_tmp = df_portfolio_features[~df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])]
df_tmp = df_tmp[~df_tmp['Criteria'].isin(['XY25','XY24','X40', 'X40N'])].sort_values(by = 'RRR Ind', ascending=False)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
1,ABB,1.36,33.11,9.36,45.57,32595.0,86621.0,348240.0,7934.00,-14.42,77.0,H-MC,18.41,125.0,2.66,2.47,54.64,AR,NTT,ELECTRICAL
25,FINCABLES,0.73,20.77,72.16,107.91,128664.0,30660.0,178304.0,1641.55,8.57,68.0,M-SC,3.45,220.0,0.24,1.27,34.14,OX40N,ATH,CABLES
66,SONACOMS,0.82,0.56,38.31,39.09,38972.0,568.0,101727.0,804.02,-20.33,64.0,M-MC,10.47,193.0,0.01,0.72,43.91,AR,ATH,AUTO
84,ZYDUSLIFE,-0.84,-2.08,38.51,35.63,79031.0,-4353.0,205221.0,1286.17,-14.86,58.0,H-MC,4.93,120.0,-0.06,1.46,11.11,AR,ATH,PHARMA
39,INDIAMART,-0.81,-6.88,121.99,106.72,140107.0,-8485.0,114851.0,4810.62,-58.01,60.0,H-SC,11.96,140.0,-0.06,0.82,10.34,AR,ATH,MISC

In [17]:
# top 5 to accumulate based on lowest RSI_14
df_tmp = df_portfolio_features[df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])].sort_values(by = 'RSI_14', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
2,ABBOTINDIA,-0.65,-14.84,38.64,18.07,58853.0,-26545.0,152310.0,35195.0,-27.52,39.0,X-MC,11.82,58.0,-0.45,1.08,0.00,X40,ATH,PHARMA
37,ICICIPRULI,-1.40,-8.97,43.61,30.73,78207.0,-17672.0,179333.0,790.0,-33.41,45.0,X-MC,12.95,78.0,-0.23,1.27,9.28,X40,ATH,INSURANCE
45,JIOFIN,-1.01,-22.10,64.86,28.43,150736.0,-65925.0,232402.0,387.0,-23.29,46.0,X-LC,18.73,34.0,-0.44,1.65,4.75,XY24,BTT,FINANCE
58,RELIANCE,-0.73,-13.13,44.24,25.30,77232.0,-26387.0,174576.0,1952.0,-15.42,47.0,X-LC,5.61,21.0,-0.34,1.24,5.23,XY25,BTT,REFINERIES
33,HDFCBANK,2.05,-2.89,32.18,28.37,73403.0,-6783.0,228102.0,1073.0,-17.57,51.0,X-LC,17.50,26.0,-0.09,1.62,10.96,X40,BTT,BANKS

In [18]:
# top 5 to accumulate based on Spread and CumlRnk
df_tmp = df_portfolio_features[df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])]
df_tmp = df_tmp[(df_tmp['CumlRnk'] < 100)].sort_values(by = 'Spread%', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
64,SIEMENS,0.34,-0.01,25.52,25.51,47489.0,-10.0,186085.0,4671.50,56.28,72.0,H-LC,2.61,51.0,-0.00,1.32,31.65,AR,ATH,ELECTRICAL
23,DMART,-0.34,10.32,17.48,29.60,48134.0,25764.0,275364.0,5391.45,-6.93,69.0,X-LC,5.16,14.0,0.54,1.95,25.86,X40N,ATH,FMCG
58,RELIANCE,-0.73,-13.13,44.24,25.30,77232.0,-26387.0,174576.0,1952.00,-15.42,47.0,X-LC,5.61,21.0,-0.34,1.24,5.23,XY25,BTT,REFINERIES
77,UNITDSPR,4.23,0.12,20.62,20.77,48341.0,292.0,234436.0,1644.00,-11.25,61.0,X-MC,6.13,64.0,0.01,1.66,11.83,X40N,NTT,BREWERIES
81,VOLTAS,1.34,14.00,27.37,45.20,59825.0,26838.0,218580.0,1856.00,30.49,61.0,X-MC,6.91,79.0,0.45,1.55,21.75,XY25,NTT,AC

In [19]:
# top 5 to accumulate based on lowest Gained%
df_tmp = df_portfolio_features[df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])].sort_values(by = 'Gained%', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
2,ABBOTINDIA,-0.65,-14.84,38.64,18.07,58853.0,-26545.0,152310.0,35195.0,-27.52,39.0,X-MC,11.82,58.0,-0.45,1.08,0.00,X40,ATH,PHARMA
45,JIOFIN,-1.01,-22.10,64.86,28.43,150736.0,-65925.0,232402.0,387.0,-23.29,46.0,X-LC,18.73,34.0,-0.44,1.65,4.75,XY24,BTT,FINANCE
58,RELIANCE,-0.73,-13.13,44.24,25.30,77232.0,-26387.0,174576.0,1952.0,-15.42,47.0,X-LC,5.61,21.0,-0.34,1.24,5.23,XY25,BTT,REFINERIES
27,GLAXO,-0.10,-2.56,42.79,39.15,83095.0,-5092.0,194192.0,3466.2,-25.54,53.0,X-MC,10.92,56.0,-0.06,1.38,7.43,X40,ATH,PHARMA
42,INFY,0.05,-10.60,50.17,34.24,140332.0,-33176.0,279712.0,1972.0,-29.61,51.0,X-LC,12.79,3.0,-0.24,1.99,7.57,X40,NTT,IT

In [20]:
# top 5 to accumulate based on lowest CurrAlloc%
df_tmp = df_portfolio_features[df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])].sort_values(by = 'CurrAlloc%', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
57,RELAXO,0.25,-60.36,284.20,52.31,163543.0,-87615.0,57545.0,1176.0,-57.80,56.0,X-SC,31.69,92.0,-0.54,0.41,28.66,X40N,NTT,FOOTWEAR
11,BATAINDIA,0.60,-50.83,174.96,35.20,110699.0,-65399.0,63271.0,2096.0,-17.11,63.0,X-SC,31.55,91.0,-0.59,0.45,25.48,X40,NTT,FOOTWEAR
53,QUESS,1.49,-19.54,116.14,73.90,99790.0,-20871.0,85922.0,424.0,-56.47,59.0,X-SC,19.35,80.0,-0.21,0.61,15.58,XY24,NTT,MISC
2,ABBOTINDIA,-0.65,-14.84,38.64,18.07,58853.0,-26545.0,152310.0,35195.0,-27.52,39.0,X-MC,11.82,58.0,-0.45,1.08,0.00,X40,ATH,PHARMA
50,MEDANTA,0.18,-7.50,37.43,27.12,61114.0,-13241.0,163276.0,1486.0,-10.27,55.0,X-SC,15.60,87.0,-0.22,1.16,12.51,XY24,NTT,HEALTHCARE

In [21]:
# top 5 to accumulate based on CumlRnk
df_tmp = df_portfolio_features.sort_values(by = 'CumlRnk', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
44,ITC,1.52,-18.44,45.97,19.06,127542.0,-62720.0,277446.0,452.00,-55.12,57.0,X-LC,19.09,1.0,-0.49,1.97,7.63,X40,NTT,FMCG
72,TCS,1.20,-23.37,65.16,26.57,231336.0,-108245.0,355028.0,4311.58,-35.10,58.0,X-LC,16.11,2.0,-0.47,2.52,10.80,X40,ATH,IT
42,INFY,0.05,-10.60,50.17,34.24,140332.0,-33176.0,279712.0,1972.00,-29.61,51.0,X-LC,12.79,3.0,-0.24,1.99,7.57,X40,NTT,IT
74,TMPV,0.06,-18.99,68.59,36.58,197731.0,-67562.0,288279.0,600.00,-83.62,61.0,X-LC,9.67,4.0,-0.34,2.05,20.16,XY24,NTT,AUTO
32,HCLTECH,0.90,-6.47,32.40,23.83,73311.0,-15656.0,226268.0,1908.19,-1.57,55.0,X-LC,7.31,8.0,-0.21,1.61,9.86,X40,ATH,IT

In [22]:
# top 5 for average up
df_tmp = df_portfolio_features[(df_portfolio_features['Dev%_200'] > 5)].sort_values(by = 'CurrAlloc%', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
66,SONACOMS,0.82,0.56,38.31,39.09,38972.0,568.0,101727.0,804.02,-20.33,64.0,M-MC,10.47,193.0,0.01,0.72,43.91,AR,ATH,AUTO
68,SURYODAY,1.91,-16.30,47.00,23.03,70443.0,-29192.0,149879.0,216.00,62.28,66.0,H-SC,3.65,166.0,-0.41,1.06,27.82,XR,NTT,BANKS
25,FINCABLES,0.73,20.77,72.16,107.91,128664.0,30660.0,178304.0,1641.55,8.57,68.0,M-SC,3.45,220.0,0.24,1.27,34.14,OX40N,ATH,CABLES
64,SIEMENS,0.34,-0.01,25.52,25.51,47489.0,-10.0,186085.0,4671.50,56.28,72.0,H-LC,2.61,51.0,-0.00,1.32,31.65,AR,ATH,ELECTRICAL
56,RECLTD,0.17,3.78,16.34,20.74,34452.0,7672.0,210842.0,446.00,15.23,71.0,M-MC,4.83,191.0,0.22,1.50,25.65,XY25,NTT,FINANCE

In [23]:
# top 5 RSP
df_tmp = df_portfolio_features.sort_values(by = 'RSP', ascending=False)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
54,RAJESHEXPO,-4.77,-77.45,343.72,0.07,106333.0,-106241.0,30936.0,518.0,1033.84,53.0,L-SC,41.18,268.0,-1.00,0.22,45.24,OX40N,NTT,JEWELLERY
47,KANSAINER,1.06,-31.17,64.86,13.47,120391.0,-84051.0,185616.0,340.0,-40.82,67.0,H-SC,20.11,162.0,-0.70,1.32,29.65,XY24,NTT,PAINTS
55,RAJOOENG,0.69,-35.78,117.38,39.61,77271.0,-36670.0,65830.0,143.1,-56.61,61.0,H-SC,29.05,136.0,-0.47,0.47,41.02,AR,ATH,MISC
65,SIS,3.26,-22.60,56.68,21.26,48708.0,-25097.0,85935.0,528.0,2029.53,75.0,H-SC,10.14,168.0,-0.52,0.61,27.77,OX40N,NTT,MISC
80,VBL,3.98,-2.01,38.28,35.50,118474.0,-6348.0,309494.0,670.8,-13.53,71.0,X-LC,9.76,13.0,-0.05,2.20,27.08,X40N,ATH,FMCG

In [24]:
# Top N allocation
df_tmp = df_portfolio_features.sort_values(by = 'CurrAlloc%', ascending=False)
top_n_values = [10, 25, 50]

sum_df = pd.DataFrame({
    'Top_N': top_n_values,
    'Sum_Alloc%': [df_tmp['CurrAlloc%'].head(n).sum() for n in top_n_values]
})

sum_df

   Top_N  Sum_Alloc%
0     10       21.00
1     25       46.22
2     50       78.41

In [25]:
# market-cap-wise allocation
df_tmp = df_portfolio_features[cols]
df_tmp.groupby(df_tmp['Conviction'].str[-2:])['CurrAlloc%'].sum().sort_values(ascending=False)

Conviction
SC    43.73
MC    30.42
LC    25.86
Name: CurrAlloc%, dtype: float64

In [26]:
# criteria-wise allocation
df_portfolio_features.groupby('Criteria')['CurrAlloc%'].sum().sort_values(ascending=False)

Criteria
XY24     27.87
X40      25.08
X40N     13.71
AR        9.60
XR        8.43
XY25      7.43
OX40N     7.08
SR        0.81
Name: CurrAlloc%, dtype: float64

In [27]:
# conviction-wise allocation
df_portfolio_features.groupby('Conviction')['CurrAlloc%'].sum().sort_values(ascending=False)

Conviction
X-LC    23.53
H-SC    22.68
X-MC    22.62
M-SC    10.38
X-SC    10.08
H-MC     5.23
M-MC     2.22
H-LC     1.32
M-LC     1.01
L-SC     0.59
L-MC     0.35
Name: CurrAlloc%, dtype: float64

In [28]:
# sector-wise stats
df_tmp = df_portfolio_features.groupby('Category')[['CurrAlloc%', 'Current', 'Current P/L', 'FTT Amt']].sum().sort_values(by=['Current', 'Current P/L'], ascending=False)
df_tmp['Current P/L%'] = round(df_tmp['Current P/L'] * 100 / df_tmp['Current'], 2)
df_tmp['FTT%'] = round(df_tmp['FTT Amt'] * 100 / df_tmp['Current'], 2)
cols = ['CurrAlloc%', 'Current P/L%', 'FTT%']
df_tmp[cols].sort_values(by=['CurrAlloc%'], ascending=False)

               CurrAlloc%  Current P/L%    FTT%
Category
FMCG                15.31        -15.79   56.88
IT                  11.85        -35.03  103.75
FINANCE             11.30        -15.85   66.23
MISC                 7.21        -32.00   89.34
ELECTRICAL           6.93          0.81   37.17
PAINTS               5.55        -26.05   47.94
BANKS                4.71        -16.13   75.07
INSURANCE            4.63         -3.70   39.19
PHARMA               3.92         -6.52   40.05
AUTO                 3.90        -19.04   66.27
AC                   2.09         -8.44   37.85
HEALTHCARE           1.94        -30.64   64.73
APPARELS             1.89         -1.00   35.45
FOOTWEAR             1.88        -67.14  134.16
TRAVEL               1.83        -73.32  160.11
DURABLES             1.82        -51.44   88.28
BREWERIES            1.66          0.12   20.62
REALTY               1.48         -6.23   23.68
CERAMICS             1.37        -58.87  107.13
CABLES               1.27         17.20   72.16
REFINERIES           1.24        -15.11   44.24
CEMENT               1.22        -55.38  171.63
ENGINEERING          1.19        -44.13  110.05
JEWELLERY            1.10       -105.58  177.01
CHEMICALS            1.10        -71.18  210.83
ENTERTAINMENT        0.80        -71.34  173.53
TEXTILES             0.45        -44.15   85.26
HOTELS               0.37       -117.91  194.77

In [29]:
# money to be made criteria-wise
df_portfolio_features.groupby('Criteria')['FTT Amt'].agg(['sum', 'count']).sort_values(by='sum', ascending=False)

                sum  count
Criteria
XY24      3669621.0     21
X40       1641012.0     16
XR        1300468.0     12
AR        1221363.0     10
X40N       989390.0      9
OX40N      795903.0     10
XY25       394669.0      5
SR         304647.0      2

In [30]:
# money to be made conviction-wise
df_portfolio_features.groupby('Conviction')['FTT Amt'].agg(['sum', 'count']).sort_values(by='sum', ascending=False)

                  sum  count
Conviction
H-SC        3595237.0     24
X-MC        1546611.0     15
X-LC        1462956.0     13
M-SC        1455582.0     14
X-SC        1382379.0      9
H-MC         342364.0      3
L-SC         207826.0      2
M-LC         149421.0      1
M-MC          73424.0      2
L-MC          53784.0      1
H-LC          47489.0      1

In [31]:
# money to be made criteria and conviction-wise
df_portfolio_features.groupby(['Conviction', 'Criteria'])['FTT Amt'].agg(['sum', 'count']).sort_values(by='sum', ascending=False)

                           sum  count
Conviction Criteria
H-SC       XY24      1182300.0      6
           AR         949482.0      5
M-SC       XY24       855256.0      6
X-SC       XY24       820891.0      4
H-SC       XR         817020.0      7
X-LC       X40        809508.0      7
X-MC       X40        628703.0      7
           X40N       464095.0      4
X-SC       X40N       358687.0      3
X-LC       XY24       348467.0      2
M-SC       OX40N      347782.0      5
H-SC       OX40N      341788.0      4
           SR         304647.0      2
X-MC       XY24       231969.0      2
H-MC       XY24       230738.0      1
X-MC       XY25       221844.0      2
X-SC       X40        202801.0      2
M-SC       XR         178750.0      2
X-LC       X40N       166608.0      2
M-LC       XR         149421.0      1
X-LC       XY25       138373.0      2
H-MC       AR         111626.0      2
L-SC       OX40N      106333.0      1
           XR         101493.0      1
M-SC       AR          73794.0      1
L-MC       XR          53784.0      1
H-LC       AR          47489.0      1
M-MC       AR          38972.0      1
           XY25        34452.0      1

In [32]:
# notebook execution time

end_time = time.time()
execution_time = round(end_time - start_time, 0)
print(f"Notebook execution time: {execution_time} seconds")

Notebook execution time: 26.0 seconds