<a href="https://colab.research.google.com/github/ankit-rathi/Quantvesting_v2/blob/main/myStocks_Portfolio_Analysis.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
'''
!pip install pandas==2.2.2 -qq
!pip install pyxirr -qq
!pip install ta -qq
!pip install yfinance==0.2.59 -qq
'''

'\n!pip install pandas==2.2.2 -qq\n!pip install pyxirr -qq\n!pip install ta -qq\n!pip install yfinance==0.2.59 -qq\n'

In [2]:
# import libraries

import numpy as np
import pandas as pd
import datetime
import warnings
warnings.filterwarnings('ignore')
import yfinance as yfin
import ta
import matplotlib.pyplot as plt
import requests

In [3]:
# notebook start time
import time
import datetime
import pytz

start_time = time.time()

# function to print date timestamp
def print_date_time():
  tz_NY = pytz.timezone('Asia/Kolkata')
  datetime_NY = datetime.datetime.now(tz_NY)
  print("Run date time (IST):", datetime_NY.strftime("%Y-%m-%d %H:%M:%S"))

In [4]:
# function to get booked and reserved amount
def get_amt():
  # fetch the JSON data from the URL
  url = "https://raw.githubusercontent.com/ankit-rathi/Tradevesting_v1/main/data/myPortfolioAmts.json"
  response = requests.get(url)
  pf_amts = response.json()  # parse the JSON data

  # extract values from the JSON
  py_booked_amt_dm = pf_amts["py_booked_amt_dm"]
  py_booked_amt_sv = pf_amts["py_booked_amt_sv"]
  cy_booked_amt_dm = pf_amts["cy_booked_amt_dm"]
  cy_booked_amt_sv = pf_amts["cy_booked_amt_sv"]
  reserve_amt_dm = pf_amts["reserve_amt_dm"]
  reserve_amt_sv = pf_amts["reserve_amt_sv"]

  # perform calculations
  py_booked_amt = py_booked_amt_dm + py_booked_amt_sv
  cy_booked_amt = cy_booked_amt_dm + cy_booked_amt_sv
  reserve_amt = reserve_amt_dm + reserve_amt_sv
  total_booked_amt = py_booked_amt + cy_booked_amt

  return total_booked_amt, reserve_amt, cy_booked_amt, py_booked_amt

gen_output = 0

In [5]:
# function to format the amount
def format_amt(number):
    abs_number = abs(number)

    if abs_number >= 1_00_00_000:  # Crores
        formatted_amt = f"{number / 1_00_00_000:.2f} C"
    elif abs_number >= 1_00_000:  # Lakhs
        formatted_amt = f"{number / 1_00_000:.2f} L"
    elif abs_number >= 1_000:  # Thousands
        formatted_amt = f"{number / 1_000:.2f} K"
    else:
        formatted_amt = f"{number:.2f}"

    return formatted_amt

# function to set start and end date
def get_start_end_date():
  start_date = (datetime.date.today() + datetime.timedelta(days=-365)).strftime('%Y-%m-%d')
  end_date = (datetime.date.today() + datetime.timedelta(days=1)).strftime('%Y-%m-%d')
  return start_date, end_date

# function to fetch my portfolio csv
def get_mypfs_df():
  mypfs_df = pd.read_csv('https://raw.githubusercontent.com/ankit-rathi/Tradevesting_v1/main/data/myPortfolioStocks.csv')
  return mypfs_df

# function to fetch my prospects csv
def get_mypps_df():
  mypps_df = pd.read_csv('https://raw.githubusercontent.com/ankit-rathi/Tradevesting_v1/main/data/myProspectsScrips.csv')
  return mypps_df

# function to fetch screener data
def get_myscreen_df():
  myscreen_df = pd.read_csv('https://raw.githubusercontent.com/ankit-rathi/Tradevesting_v1/main/data/myScreenerDB.csv')
  return myscreen_df

# function to fetch momentum data
def get_myinvmt_df():
  myinvmt_df = pd.read_csv('https://raw.githubusercontent.com/ankit-rathi/Tradevesting_v1/main/data/myInvestments.csv')
  return myinvmt_df

# function to get the stock ids
def get_stock_ids(df_pf):
  stock_n100 = df_pf['Symbol'].unique()

  exclude = ['CADILAHC','MMTC', 'MASFIN']

  stock_ids = df_pf[~df_pf['Symbol'].isin(exclude) ]['Symbol'].unique()

  #mypf = mypf[mypf.Forecast.notnull()]
  #stock_ids = mypf['Symbol'].unique()

  #stock_ids.sort()
  return stock_ids

# get features from screener data
def get_screener_features():
  myscreen_df = get_myscreen_df()
  cols = ['Symbol', 'EPS', 'MedPE', 'ROCE%', 'ROE%', 'CapType']
  return myscreen_df[cols]

# get relative strength
def get_relative_strength(stock_list):

    # Dictionary to store stock tickers and their corresponding percentage price change
    stock_changes = {}

    # Loop through each stock and fetch its price data
    for stock in stock_list:
        try:
            # Download the stock data for the given date range
            stock_data = yfin.Ticker(stock + '.NS').history(period='1mo', interval='1d')[map(str.title, ['open', 'close', 'low', 'high', 'volume'])]

            # Calculate the percentage change for the stock
            if len(stock_data) > 0:
                start_price = stock_data['Close'].iloc[0]
                end_price = stock_data['Close'].iloc[-1]
                percent_change = round(((end_price - start_price) / start_price) * 100, 2)
                stock_changes[stock] = percent_change
            else:
                stock_changes[stock] = np.nan  # If no data is available, set to NaN

        except Exception as e:
            print(f"Error fetching data for {stock}: {e}")
            stock_changes[stock] = np.nan

    # Create a DataFrame with stock tickers and their percentage changes
    df = pd.DataFrame(list(stock_changes.items()), columns=['Symbol', 'Percent_Change'])

    # Drop any stocks with missing data (NaN values)
    df = df.dropna()

    # Calculate the percentile rank based on percentage change
    df['RSP'] = round(df['Percent_Change'].rank(pct=True) * 100, 2)
    cols = ['Symbol', 'RSP']
    df = df[cols]
    # Sort by percentile rank (optional)
    df = df.sort_values(by='RSP', ascending=False).reset_index(drop=True)

    return df

In [6]:
# function to get stock technicals
def stock_prec_dev(stock_symbol):
    #stock_symbol = 'ULTRACEMCO.NS'
    short_window = 20
    mid_window = 50
    long_window = 200
    moving_avg = 'SMA'

    start = datetime.datetime(*map(int, start_date.split('-')))
    end = datetime.datetime(*map(int, end_date.split('-')))

    stock_df = yfin.Ticker(stock_symbol + '.NS').history(period='max', interval='1d')[map(str.title, ['open', 'close', 'low', 'high', 'volume'])]

    stock_df['Max'] = round(max(stock_df['Close']),2)
    stock_df = stock_df[(stock_df.index <= end_date) & (stock_df.index >= start_date)]
    stock_df['200_SMA'] = round(stock_df['Close'].rolling(window = 200, min_periods = 1).mean(),0)
    stock_df['Dev%_200'] = round((stock_df['Close'] - stock_df['200_SMA'])*100/stock_df['200_SMA'],2)
    stock_df.dropna(axis = 0, inplace = True) # remove any null rows

    stock_df['20_SMA'] = stock_df['Close'].rolling(window=20).mean()
    stock_df['50_SMA'] = stock_df['Close'].rolling(window=50).mean()
    stock_df['Symbol'] = stock_symbol

    stock_df['Close'] = round(stock_df['Close'],2)
    stock_df['Min'] = round(min(stock_df['Close']),2)
    stock_df['RSI_14'] = ta.momentum.RSIIndicator(close=stock_df['Close'], window=14).rsi()
    stock_df['RSI_14'] = round(stock_df['RSI_14'],0)
    stock_df['Prev_Close'] = stock_df['Close'].shift(1)
    stock_df.drop(['Open', 'Low', 'High', 'Volume'], axis=1, inplace=True)
    stock_df = stock_df.tail(1)

    max_SMA = max(stock_df['20_SMA'].item(), stock_df['50_SMA'].item(), stock_df['200_SMA'].item())
    min_SMA = min(stock_df['20_SMA'].item(), stock_df['50_SMA'].item(), stock_df['200_SMA'].item())
    ABS_Spread = max_SMA - min_SMA
    stock_df['Spread%'] = round((ABS_Spread / stock_df['200_SMA'].item()) * 100,2)

    return stock_df

# function to compute stock attributes
def get_common_features(stock_ids, df_mypf):

  df_prec_dev = pd.DataFrame()
  df_tmp = get_screener_features()
  df_rs = get_relative_strength(stock_ids)

  for stock_id in stock_ids:
      tmp = stock_prec_dev(stock_id)
      tmp = tmp.reset_index()
      df_prec_dev = pd.concat([df_prec_dev, tmp], ignore_index = True)
  df_prec_dev = pd.merge(df_prec_dev, df_mypf, on= 'Symbol')
  df_prec_dev = pd.merge(df_prec_dev, df_tmp, on= 'Symbol', how='left')
  df_prec_dev = pd.merge(df_prec_dev, df_rs, on= 'Symbol', how='left')
  #print(df_prec_dev.columns)
  df_prec_dev['Curr_PE'] = round(df_prec_dev['Close']/df_prec_dev['EPS'],1)
  df_prec_dev['Dev%_PE'] = round((df_prec_dev['Curr_PE'] - df_prec_dev['MedPE'])*100/df_prec_dev['MedPE'],2)
  df_prec_dev['Conviction'] = df_prec_dev['Conviction'] + '-' + df_prec_dev['CapType']
  return df_prec_dev

# function to arrange stock features
def arrange_features(df_stocks, common_cols, diff_cols):
  df_stocks_common = df_stocks[common_cols].drop_duplicates()
  df_stocks_diff = df_stocks[diff_cols]
  df_stocks_diff['Investment'] = df_stocks_diff['AvgCost'] * df_stocks_diff['Shares']
  df_stocks_diff = df_stocks_diff.groupby(['Symbol'])[['Shares', 'Investment']].aggregate(['sum']).reset_index()
  df_stocks_diff.columns = ['Symbol', 'Shares', 'Investment']
  df_stocks_diff['AvgCost'] = round(df_stocks_diff['Investment']/df_stocks_diff['Shares'],2)
  df_stocks = pd.merge(df_stocks_diff, df_stocks_common, on='Symbol')
  return df_stocks

# plot fact distribution across dimension
def plot_pie_chart(df, dimension, fact):
  # grouping the data by category and calculating the sum of fact for each type
  grouped_data = df.groupby(dimension)[fact].sum()

  # sorting the grouped data in descending order
  grouped_data = grouped_data.sort_values(ascending=False)

  # creating a pie chart
  grouped_data.plot.pie(autopct='%1.1f%%', startangle=90, figsize=(6, 6))

  # adding a title and displaying the plot
  plt.title(f'{dimension} {fact} Distribution')
  plt.ylabel('')  # To hide the y-label
  plt.show()

In [7]:
# function to get portfolio features

def get_portfolio_features(df_common_features):

  print_date_time()
  print('-------------------')

  #df_common_features["Target"] = df_common_features["Target"].fillna(df_common_features["Max"])
  df_common_features['NTT'] = np.where(df_common_features['Strategy']== 'NTT', df_common_features["Target"], df_common_features['Max'])
  df_common_features['LTT'] = np.where(df_common_features['Strategy']== 'BTT', df_common_features["Target"], df_common_features['Max'])
  df_common_features['BOL'] = df_common_features['Min']

  tmp_df = df_common_features[df_common_features['Symbol'].isin(mypf_df[mypf_df['InPortfolio'] != 'NA'].Symbol.values)]
  print('qualified stocks: '+str(len(tmp_df['Symbol'].unique())))
  tmp_df1 = tmp_df[tmp_df['LatestQtr'] == 1]
  print('with latest results: '+str(len(tmp_df1['Symbol'].unique())))
  tmp_df1 = tmp_df1[tmp_df1['StarStock'] == 1]
  print('still star stocks: '+str(len(tmp_df1['Symbol'].unique())))
  tmp_df['Investment'] = tmp_df['AvgCost'] * tmp_df['Shares']
  tmp_df['Current'] = round(tmp_df['Close'] * tmp_df['Shares'],0)
  tmp_df['Previous'] = tmp_df['Prev_Close'] * tmp_df['Shares']
  tmp_df['EstimatedST'] = tmp_df['NTT'] * tmp_df['Shares']
  tmp_df['EstimatedLT'] = tmp_df['LTT'] * tmp_df['Shares']
  tmp_df['Current P/L'] = round((tmp_df['Current'] - tmp_df['Investment']),0)
  tmp_df['Today P/L%'] = round((tmp_df['Current'] - tmp_df['Previous'])*100/tmp_df['Previous'],2)
  tmp_df['Current P/L%'] = round((tmp_df['Current'] - tmp_df['Investment'])*100/tmp_df['Investment'],2)
  tmp_df['EstimatedST P/L%'] = round((tmp_df['EstimatedST'] - tmp_df['Investment'])*100/tmp_df['Investment'],2)
  tmp_df['EstimatedLT P/L%'] = round((tmp_df['EstimatedLT'] - tmp_df['Investment'])*100/tmp_df['Investment'],2)
  tmp_df['NTT%'] = round((tmp_df['NTT'] - tmp_df['Close'])*100/tmp_df['Close'],2)
  tmp_df['LTT%'] = round((tmp_df['LTT'] - tmp_df['Close'])*100/tmp_df['Close'],2)
  tmp_df['Gained%'] = round((tmp_df['Close'] - tmp_df['BOL'])*100/tmp_df['BOL'],2)
  investment = round(sum(tmp_df['AvgCost']*tmp_df['Shares']),0)
  current = round(sum(tmp_df['Close']*tmp_df['Shares']),0)
  tmp_df['InitAlloc%'] = round(tmp_df['Investment']*100/investment,2)
  tmp_df['CurrAlloc%'] = round(tmp_df['Current']*100/current,2)
  tmp_df['FTT'] = tmp_df['LTT']
  tmp_df.loc[tmp_df['Strategy'] == 'NTT', 'FTT'] = tmp_df['NTT']
  tmp_df['FTT%'] = tmp_df['LTT%']
  tmp_df.loc[tmp_df['Strategy'] == 'NTT', 'FTT%'] = tmp_df['NTT%']
  tmp_df['FTT Amt'] = round(tmp_df['FTT%'] * tmp_df['Current']/100,0)
  tmp_df['OTT%'] = round((tmp_df['FTT'] - tmp_df['AvgCost'])*100/tmp_df['AvgCost'],2)
  tmp_df['RRR Ind'] = round(tmp_df['Current P/L']/tmp_df['FTT Amt'],2)
  tmp_df['Risk Ind'] = round(tmp_df['Current P/L%']*tmp_df['CurrAlloc%'],0)

  return tmp_df

# function to print portfolio features
def print_portfolio_stats(df_portfolio_features, myinvmt_df):
  from pyxirr import xirr

  total_booked_amt, reserve_amt, cy_booked_amt, py_booked_amt = get_amt()

  dates = myinvmt_df['Date'].values
  dates = np.append(dates, datetime.date.today().strftime('%d-%b-%y'))
  investment = myinvmt_df['Investment'].values
  dates= pd.to_datetime(dates)

  current = round(sum(df_portfolio_features['Close']*df_portfolio_features['Shares']),0) + reserve_amt
  investment_xirr = np.append(investment, current)
  cagr = round(xirr(pd.DataFrame({"dates": dates, "amounts": investment_xirr}))*100,2)

  investment = -sum(investment)
  invested = round(sum(df_portfolio_features['AvgCost']*df_portfolio_features['Shares']),0) + reserve_amt
  previous = round(sum(df_portfolio_features['Prev_Close']*df_portfolio_features['Shares']),0) + reserve_amt
  cy_invested = investment + py_booked_amt

  today_pnl_amount = current-previous
  today_pnl_percentage = round((current-previous)*100/previous,2)

  curr_pnl_amount = current-invested
  curr_pnl_percentage = round((curr_pnl_amount)*100/(cy_invested),2)

  cy_pnl_amount = cy_booked_amt + curr_pnl_amount
  cy_pnl_percentage = round((cy_pnl_amount)*100/cy_invested,2)

  overall_pnl_amount = total_booked_amt + curr_pnl_amount
  overall_pnl_percentage = round((overall_pnl_amount)*100/investment,2)

  estimate_st = round(sum(df_portfolio_features['FTT']*df_portfolio_features['Shares']),0)  + reserve_amt
  est_st_pnl_amount = estimate_st-current
  est_st_pnl_percentage = round((est_st_pnl_amount)*100/current,2)

  estimate_lt = round(sum(df_portfolio_features['LTT']*df_portfolio_features['Shares']),0)  + reserve_amt
  est_lt_pnl_amount = estimate_lt-current
  est_lt_pnl_percentage = round((est_lt_pnl_amount)*100/current,2)

  total_profit = round(sum(df_portfolio_features[df_portfolio_features['Current P/L%'] > 0]['Current']) - sum(df_portfolio_features[df_portfolio_features['Current P/L%'] > 0]['Investment']),0)
  total_loss = round(sum(df_portfolio_features[df_portfolio_features['Current P/L%'] < 0]['Current']) - sum(df_portfolio_features[df_portfolio_features['Current P/L%'] < 0]['Investment']),0)

  cy_booked_percentage = round((cy_booked_amt)*100/current,2)
  py_booked_percentage = round((py_booked_amt)*100/investment,2)
  total_booked_percentage = round((total_booked_amt)*100/investment,2)

  print('-------------------')
  print('Initial Investment: ', format_amt(investment))
  print('CY Investment: ', format_amt(cy_invested))
  print('Reserve: ', format_amt(reserve_amt))
  print('Current: ',  format_amt(current))
  print('-------------------')
  print('Today PnL: '+ '{} ({}%)'.format(format_amt(today_pnl_amount), today_pnl_percentage))
  print('Current PnL: '+ '{} ({}%)'.format(format_amt(curr_pnl_amount), curr_pnl_percentage))
  print('CY Booked + Current PnL: '+ '{} ({}%)'.format(format_amt(cy_pnl_amount), cy_pnl_percentage))
  print('-------------------')
  print('Total profit: ', format_amt(total_profit))
  print('Total loss: ', format_amt(total_loss))
  print('-------------------')
  print('Total Booked + Current PnL: '+ '{} ({}%)'.format(format_amt(overall_pnl_amount), overall_pnl_percentage))
  print('Total Booked PnL: '+ '{} ({}%)'.format(format_amt(total_booked_amt), total_booked_percentage))
  print('Curr Year Booked PnL: '+ '{} ({}%)'.format(format_amt(cy_booked_amt), cy_booked_percentage))
  print('Prev Year Booked PnL: '+ '{} ({}%)'.format(format_amt(py_booked_amt), py_booked_percentage))
  print('===================')
  print('Est FTT: ',  format_amt(estimate_st))
  print('Est FTT PnL: '+ '{} ({}%)'.format(format_amt(est_st_pnl_amount), est_st_pnl_percentage))

  print('===================')
  print('Deployed: ', format_amt(investment))

  print('Current: ', format_amt(current))

  print('CAGR/XIRR %: '+'{}%'.format(cagr))

In [8]:
# get start and end date
start_date, end_date = get_start_end_date()

# get portfolio and prospects data
mypfs_df = get_mypfs_df()
mypps_df = get_mypps_df()
myinvmt_df = get_myinvmt_df()

# merge above datasets
mypf_df = pd.merge(mypfs_df, mypps_df, on="Symbol")

# seggregate dm and sv portfolio
dm_pf = mypf_df[mypf_df['InPortfolio'] == 'DM']
sv_pf = mypf_df[mypf_df['InPortfolio'] == 'SV']

# build portfolio stock dataframe
dm_stocks = get_stock_ids(dm_pf)
sv_stocks = get_stock_ids(sv_pf)
df_stocks = pd.concat([dm_pf,sv_pf], ignore_index = True)

# arrange common and diff stock features
common_cols = ['Symbol', 'Target', 'Criteria', 'Strategy', 'CumlRnk', 'LatestQtr', 'StarStock', 'Conviction', 'Category', 'InFolio', 'XIRR', 'MBQ']
diff_cols = ['Symbol', 'AvgCost', 'Shares']
df_stocks = arrange_features(df_stocks, common_cols, diff_cols)

# get common features
stock_ids = df_stocks['Symbol'].values
df_common_features = get_common_features(stock_ids, df_stocks)

df_common_features.reset_index(drop=True, inplace=True)
df_common_features.drop(['Date'], axis=1, inplace=True)
# get and print portfolio features
df_portfolio_features = get_portfolio_features(df_common_features)

print_portfolio_stats(df_portfolio_features, myinvmt_df)

df = df_portfolio_features
#plot_pie_chart(df, 'CapType', 'Current')
list_ox40n = list(df[df['MBQ'].str.contains('OX40N', na=False)]['Symbol'].values)

Run date time (IST): 2026-04-22 15:49:19
-------------------
qualified stocks: 90
with latest results: 28
still star stocks: 17
-------------------
Initial Investment:  1.38 C
CY Investment:  1.80 C
Reserve:  1.84 K
Current:  1.48 C
-------------------
Today PnL: 67.88 K (0.46%)
Current PnL: -32.47 L (-18.0%)
CY Booked + Current PnL: -31.51 L (-17.47%)
-------------------
Total profit:  2.18 L
Total loss:  -34.66 L
-------------------
Total Booked + Current PnL: 11.36 L (8.26%)
Total Booked PnL: 43.83 L (31.88%)
Curr Year Booked PnL: 96.00 K (0.65%)
Prev Year Booked PnL: 42.87 L (31.18%)
===================
Est FTT:  2.52 C
Est FTT PnL: 1.05 C (70.88%)
===================
Deployed:  1.38 C
Current:  1.48 C
CAGR/XIRR %: 3.43%

In [9]:
# top 5 near their targets
cols = ['Symbol', 'Today P/L%', 'Current P/L%', 'FTT%', 'OTT%', 'FTT Amt', 'Current P/L', 'Current', 'FTT', 'Dev%_PE', 'RSI_14','Conviction', 'Spread%',  'CumlRnk', 'RRR Ind', 'CurrAlloc%', 'Gained%', 'Criteria', 'Strategy', 'Category']
df_tmp = df_portfolio_features[~df_portfolio_features['Symbol'].isin(['ENRIN','BLUSPRING','DIGITIDE'])]
df_tmp = df_tmp.sort_values(by = 'FTT Amt', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
1,ABB,4.58,39.20,4.57,45.57,16643.0,102557.0,364176.0,7934.00,-10.59,82.0,H-MC,19.49,125.0,6.16,2.47,61.72,AR,NTT,ELECTRICAL
54,MASFIN,2.26,-1.09,22.90,21.57,22194.0,-1065.0,96915.0,397.04,-14.63,61.0,H-SC,2.89,167.0,-0.05,0.66,25.24,XR,ATH,FINANCE
53,MARUTI,-0.92,-1.32,29.65,27.95,31635.0,-1424.0,106696.0,17292.00,-18.36,50.0,X-LC,12.11,33.0,-0.05,0.72,15.24,XR,ATH,AUTO
61,RECLTD,-0.00,3.78,16.34,20.74,34452.0,7672.0,210842.0,446.00,15.23,71.0,M-MC,4.08,191.0,0.22,1.43,25.65,XY25,NTT,FINANCE
81,TTKPRESTIG,0.94,-34.26,52.26,0.09,34621.0,-34530.0,66247.0,770.00,53.68,58.0,M-SC,22.63,250.0,-1.00,0.45,17.96,OX40N,NTT,DURABLES

In [10]:
# top 5 today
df_tmp = df_portfolio_features.sort_values(by = 'Today P/L%', ascending=False)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
7,AWL,5.89,-31.26,142.99,67.02,350195.0,-111400.0,244909.0,485.0,-63.00,66.0,X-SC,22.80,81.0,-0.32,1.66,15.84,XY24,NTT,FMCG
59,RAJESHEXPO,4.99,-76.32,322.62,0.07,104790.0,-104696.0,32481.0,518.0,1090.66,58.0,L-SC,40.48,268.0,-1.00,0.22,52.49,OX40N,NTT,JEWELLERY
1,ABB,4.58,39.20,4.57,45.57,16643.0,102557.0,364176.0,7934.0,-10.59,82.0,H-MC,19.49,125.0,6.16,2.47,61.72,AR,NTT,ELECTRICAL
0,5PAISA,3.97,-35.54,75.16,12.90,105850.0,-77663.0,140833.0,593.0,107.93,67.0,H-SC,13.45,170.0,-0.73,0.95,35.91,OX40N,NTT,FINANCE
67,SFL,3.73,-44.46,127.99,26.63,186406.0,-116577.0,145641.0,1287.0,10.38,63.0,M-SC,16.44,242.0,-0.63,0.99,21.38,XY24,NTT,MISC

In [11]:
# bottom 5 today
df_tmp = df_portfolio_features.sort_values(by = 'Today P/L%', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
34,HCLTECH,-10.82,-16.59,48.46,23.83,97788.0,-40132.0,201792.0,1908.19,-12.32,32.0,X-LC,7.27,8.0,-0.41,1.37,0.00,X40,ATH,IT
76,TATAELXSI,-6.20,-37.13,109.99,32.03,91169.0,-48947.0,82888.0,9161.00,-21.37,47.0,H-SC,17.84,158.0,-0.54,0.56,9.70,OX40N,NTT,IT
46,INFY,-3.40,-13.64,55.45,34.24,149833.0,-42676.0,270212.0,1972.00,-32.15,42.0,X-LC,12.57,3.0,-0.28,1.83,3.92,X40,NTT,IT
77,TCS,-2.76,-25.48,69.85,26.57,241147.0,-118037.0,345236.0,4311.58,-37.07,50.0,X-LC,15.69,2.0,-0.49,2.34,7.75,X40,ATH,IT
22,DEN,-2.67,-46.75,166.81,42.07,75024.0,-39488.0,44976.0,75.00,60.62,55.0,M-SC,16.50,235.0,-0.53,0.30,22.32,AR,NTT,ENTERTAINMENT

In [12]:
# top 5 to exit based on CumlRnk
df_tmp = df_portfolio_features[~df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])]
df_tmp = df_tmp[(df_tmp['Current P/L%'] > -1) & (df_tmp['Current P/L%'] < 1)].sort_values(by = 'CumlRnk', ascending=False)
df_tmp[cols].head()

Empty DataFrame
Columns: [Symbol, Today P/L%, Current P/L%, FTT%, OTT%, FTT Amt, Current P/L, Current, FTT, Dev%_PE, RSI_14, Conviction, Spread%, CumlRnk, RRR Ind, CurrAlloc%, Gained%, Criteria, Strategy, Category]
Index: []

In [13]:
# OX40N stocks to exit
df_tmp = df_portfolio_features[(df_portfolio_features['Symbol'].isin(list_ox40n))].sort_values(by = 'Current P/L%', ascending=False)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
26,FINCABLES,2.34,23.59,68.23,107.91,124503.0,34831.0,182475.0,1641.55,11.11,71.0,M-SC,4.22,220.0,0.28,1.24,37.28,OX40N,ATH,CABLES
70,SIS,0.13,-22.50,56.47,21.26,48592.0,-24982.0,86050.0,528.00,2032.12,75.0,H-SC,9.24,168.0,-0.51,0.58,27.94,OX40N,NTT,MISC
17,CERA,3.66,-28.23,72.62,23.89,91679.0,-49658.0,126245.0,9475.00,-30.79,72.0,H-SC,13.22,153.0,-0.54,0.86,21.32,OX40N,NTT,CERAMICS
51,KANSAINER,-1.07,-31.90,66.63,13.47,122357.0,-86031.0,183636.0,340.00,-41.45,64.0,H-SC,19.33,162.0,-0.70,1.24,28.27,XY24,NTT,PAINTS
81,TTKPRESTIG,0.94,-34.26,52.26,0.09,34621.0,-34530.0,66247.0,770.00,53.68,58.0,M-SC,22.63,250.0,-1.00,0.45,17.96,OX40N,NTT,DURABLES

In [14]:
# top 5 to book for rotation
df_tmp = df_portfolio_features[(df_portfolio_features['Current P/L%'] > 20) ].sort_values(by = 'CumlRnk', ascending=False)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
26,FINCABLES,2.34,23.59,68.23,107.91,124503.0,34831.0,182475.0,1641.55,11.11,71.0,M-SC,4.22,220.0,0.28,1.24,37.28,OX40N,ATH,CABLES
1,ABB,4.58,39.20,4.57,45.57,16643.0,102557.0,364176.0,7934.00,-10.59,82.0,H-MC,19.49,125.0,6.16,2.47,61.72,AR,NTT,ELECTRICAL

In [15]:
# top 5 to monitor for exit
df_tmp = df_portfolio_features[~df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])]
df_tmp = df_tmp[(df_tmp['Current P/L%'] > 0) ].sort_values(by = 'Dev%_PE', ascending=False)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
61,RECLTD,-0.00,3.78,16.34,20.74,34452.0,7672.0,210842.0,446.00,15.23,71.0,M-MC,4.08,191.0,0.22,1.43,25.65,XY25,NTT,FINANCE
26,FINCABLES,2.34,23.59,68.23,107.91,124503.0,34831.0,182475.0,1641.55,11.11,71.0,M-SC,4.22,220.0,0.28,1.24,37.28,OX40N,ATH,CABLES
1,ABB,4.58,39.20,4.57,45.57,16643.0,102557.0,364176.0,7934.00,-10.59,82.0,H-MC,19.49,125.0,6.16,2.47,61.72,AR,NTT,ELECTRICAL
71,SONACOMS,1.23,1.80,36.63,39.09,37721.0,1820.0,102979.0,804.02,-19.39,66.0,M-MC,11.41,193.0,0.05,0.70,45.68,AR,ATH,AUTO

In [16]:
# top 5 to book for rotation from weak conviction
df_tmp = df_portfolio_features[~df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])]
df_tmp = df_tmp[~df_tmp['Criteria'].isin(['XY25','XY24','X40', 'X40N'])].sort_values(by = 'RRR Ind', ascending=False)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
1,ABB,4.58,39.20,4.57,45.57,16643.0,102557.0,364176.0,7934.00,-10.59,82.0,H-MC,19.49,125.0,6.16,2.47,61.72,AR,NTT,ELECTRICAL
26,FINCABLES,2.34,23.59,68.23,107.91,124503.0,34831.0,182475.0,1641.55,11.11,71.0,M-SC,4.22,220.0,0.28,1.24,37.28,OX40N,ATH,CABLES
71,SONACOMS,1.23,1.80,36.63,39.09,37721.0,1820.0,102979.0,804.02,-19.39,66.0,M-MC,11.41,193.0,0.05,0.70,45.68,AR,ATH,AUTO
89,ZYDUSLIFE,0.14,-1.94,38.31,35.63,78730.0,-4066.0,205508.0,1286.17,-14.86,58.0,H-MC,4.65,120.0,-0.05,1.39,10.30,AR,ATH,PHARMA
54,MASFIN,2.26,-1.09,22.90,21.57,22194.0,-1065.0,96915.0,397.04,-14.63,61.0,H-SC,2.89,167.0,-0.05,0.66,25.24,XR,ATH,FINANCE

In [17]:
# top 5 to accumulate based on lowest RSI_14
df_tmp = df_portfolio_features[df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])].sort_values(by = 'RSI_14', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
34,HCLTECH,-10.82,-16.59,48.46,23.83,97788.0,-40132.0,201792.0,1908.19,-12.32,32.0,X-LC,7.27,8.0,-0.41,1.37,0.00,X40,ATH,IT
2,ABBOTINDIA,0.14,-14.72,38.45,18.07,58644.0,-26335.0,152520.0,35195.00,-27.52,39.0,X-MC,11.86,58.0,-0.45,1.03,0.14,X40,ATH,PHARMA
41,ICICIPRULI,-1.83,-10.63,46.28,30.73,81479.0,-20949.0,176056.0,790.00,-34.67,41.0,X-MC,12.99,78.0,-0.26,1.19,7.28,X40,ATH,INSURANCE
46,INFY,-3.40,-13.64,55.45,34.24,149833.0,-42676.0,270212.0,1972.00,-32.15,42.0,X-LC,12.57,3.0,-0.28,1.83,3.92,X40,NTT,IT
36,HDFCLIFE,-1.65,-1.57,34.81,32.69,41003.0,-1882.0,117790.0,814.30,-22.84,43.0,X-LC,17.83,31.0,-0.05,0.80,6.70,X40,ATH,INSURANCE

In [18]:
# top 5 to accumulate based on Spread and CumlRnk
df_tmp = df_portfolio_features[df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])]
df_tmp = df_tmp[(df_tmp['CumlRnk'] < 100)].sort_values(by = 'Spread%', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
69,SIEMENS,3.29,3.29,21.52,25.51,41365.0,6120.0,192215.0,4671.50,61.49,76.0,H-LC,3.72,51.0,0.15,1.30,35.67,AR,ATH,ELECTRICAL
63,RELIANCE,0.65,-12.57,43.31,25.30,76100.0,-25252.0,175711.0,1952.00,-14.65,49.0,X-LC,5.69,21.0,-0.33,1.19,5.91,XY25,BTT,REFINERIES
24,DMART,0.12,10.45,17.34,29.60,47804.0,26088.0,275688.0,5391.45,-6.84,69.0,X-LC,5.74,14.0,0.55,1.87,26.01,X40N,ATH,FMCG
82,UNITDSPR,2.19,2.31,18.04,20.77,43217.0,5418.0,239562.0,1644.00,-9.24,64.0,X-MC,5.75,64.0,0.13,1.62,14.28,X40N,NTT,BREWERIES
86,VOLTAS,1.67,15.91,25.27,45.20,56160.0,30498.0,222240.0,1856.00,32.66,64.0,X-MC,6.51,79.0,0.54,1.51,23.78,XY25,NTT,AC

In [19]:
# top 5 to accumulate based on lowest Gained%
df_tmp = df_portfolio_features[df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])].sort_values(by = 'Gained%', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
34,HCLTECH,-10.82,-16.59,48.46,23.83,97788.0,-40132.0,201792.0,1908.19,-12.32,32.0,X-LC,7.27,8.0,-0.41,1.37,0.00,X40,ATH,IT
2,ABBOTINDIA,0.14,-14.72,38.45,18.07,58644.0,-26335.0,152520.0,35195.00,-27.52,39.0,X-MC,11.86,58.0,-0.45,1.03,0.14,X40,ATH,PHARMA
18,CIPLA,0.31,0.44,34.56,35.15,42299.0,535.0,122394.0,1663.60,-22.43,46.0,X-LC,15.83,18.0,0.01,0.83,3.68,X40N,ATH,PHARMA
46,INFY,-3.40,-13.64,55.45,34.24,149833.0,-42676.0,270212.0,1972.00,-32.15,42.0,X-LC,12.57,3.0,-0.28,1.83,3.92,X40,NTT,IT
63,RELIANCE,0.65,-12.57,43.31,25.30,76100.0,-25252.0,175711.0,1952.00,-14.65,49.0,X-LC,5.69,21.0,-0.33,1.19,5.91,XY25,BTT,REFINERIES

In [20]:
# top 5 to accumulate based on lowest CurrAlloc%
df_tmp = df_portfolio_features[df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])].sort_values(by = 'CurrAlloc%', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
62,RELAXO,1.84,-59.63,277.26,52.31,162483.0,-86557.0,58603.0,1176.0,-57.02,59.0,X-SC,31.04,92.0,-0.53,0.40,31.03,X40N,NTT,FOOTWEAR
11,BATAINDIA,1.57,-50.05,170.70,35.20,109704.0,-64403.0,64267.0,2096.0,-15.81,66.0,X-SC,30.79,91.0,-0.59,0.44,27.46,X40,NTT,FOOTWEAR
58,QUESS,0.82,-18.89,114.39,73.90,99088.0,-20170.0,86623.0,424.0,-56.47,60.0,X-SC,18.57,80.0,-0.20,0.59,16.53,XY24,NTT,MISC
53,MARUTI,-0.92,-1.32,29.65,27.95,31635.0,-1424.0,106696.0,17292.0,-18.36,50.0,X-LC,12.11,33.0,-0.05,0.72,15.24,XR,ATH,AUTO
36,HDFCLIFE,-1.65,-1.57,34.81,32.69,41003.0,-1882.0,117790.0,814.3,-22.84,43.0,X-LC,17.83,31.0,-0.05,0.80,6.70,X40,ATH,INSURANCE

In [21]:
# top 5 to accumulate based on CumlRnk
df_tmp = df_portfolio_features.sort_values(by = 'CumlRnk', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
48,ITC,-1.34,-19.53,47.95,19.06,131253.0,-66438.0,273728.0,452.00,-55.92,52.0,X-LC,18.77,1.0,-0.51,1.85,6.19,X40,NTT,FMCG
77,TCS,-2.76,-25.48,69.85,26.57,241147.0,-118037.0,345236.0,4311.58,-37.07,50.0,X-LC,15.69,2.0,-0.49,2.34,7.75,X40,ATH,IT
46,INFY,-3.40,-13.64,55.45,34.24,149833.0,-42676.0,270212.0,1972.00,-32.15,42.0,X-LC,12.57,3.0,-0.28,1.83,3.92,X40,NTT,IT
79,TMPV,1.67,-17.63,65.81,36.58,192888.0,-62743.0,293098.0,600.00,-82.53,64.0,X-LC,8.95,4.0,-0.33,1.99,22.16,XY24,NTT,AUTO
34,HCLTECH,-10.82,-16.59,48.46,23.83,97788.0,-40132.0,201792.0,1908.19,-12.32,32.0,X-LC,7.27,8.0,-0.41,1.37,0.00,X40,ATH,IT

In [22]:
# top 5 for average up
df_tmp = df_portfolio_features[(df_portfolio_features['Dev%_200'] > 5)].sort_values(by = 'CurrAlloc%', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
71,SONACOMS,1.23,1.80,36.63,39.09,37721.0,1820.0,102979.0,804.02,-19.39,66.0,M-MC,11.41,193.0,0.05,0.70,45.68,AR,ATH,AUTO
73,SURYODAY,1.26,-15.25,45.17,23.03,68553.0,-27305.0,151766.0,216.00,64.47,68.0,H-SC,3.44,166.0,-0.40,1.03,29.43,XR,NTT,BANKS
26,FINCABLES,2.34,23.59,68.23,107.91,124503.0,34831.0,182475.0,1641.55,11.11,71.0,M-SC,4.22,220.0,0.28,1.24,37.28,OX40N,ATH,CABLES
69,SIEMENS,3.29,3.29,21.52,25.51,41365.0,6120.0,192215.0,4671.50,61.49,76.0,H-LC,3.72,51.0,0.15,1.30,35.67,AR,ATH,ELECTRICAL
61,RECLTD,-0.00,3.78,16.34,20.74,34452.0,7672.0,210842.0,446.00,15.23,71.0,M-MC,4.08,191.0,0.22,1.43,25.65,XY25,NTT,FINANCE

In [23]:
# top 5 RSP
df_tmp = df_portfolio_features.sort_values(by = 'RSP', ascending=False)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
59,RAJESHEXPO,4.99,-76.32,322.62,0.07,104790.0,-104696.0,32481.0,518.0,1090.66,58.0,L-SC,40.48,268.0,-1.00,0.22,52.49,OX40N,NTT,JEWELLERY
60,RAJOOENG,2.89,-33.92,111.28,39.61,75370.0,-34770.0,67730.0,143.1,-55.26,64.0,H-SC,27.45,136.0,-0.46,0.46,45.09,AR,ATH,MISC
85,VBL,2.03,-0.02,35.53,35.50,112196.0,-64.0,315778.0,670.8,-11.77,73.0,X-LC,8.79,13.0,-0.00,2.14,29.66,X40N,ATH,FMCG
69,SIEMENS,3.29,3.29,21.52,25.51,41365.0,6120.0,192215.0,4671.5,61.49,76.0,H-LC,3.72,51.0,0.15,1.30,35.67,AR,ATH,ELECTRICAL
51,KANSAINER,-1.07,-31.90,66.63,13.47,122357.0,-86031.0,183636.0,340.0,-41.45,64.0,H-SC,19.33,162.0,-0.70,1.24,28.27,XY24,NTT,PAINTS

In [24]:
# Top N allocation
df_tmp = df_portfolio_features.sort_values(by = 'CurrAlloc%', ascending=False)
top_n_values = [10, 25, 50]

sum_df = pd.DataFrame({
    'Top_N': top_n_values,
    'Sum_Alloc%': [df_tmp['CurrAlloc%'].head(n).sum() for n in top_n_values]
})

sum_df

   Top_N  Sum_Alloc%
0     10       20.09
1     25       44.38
2     50       75.18

In [25]:
# market-cap-wise allocation
df_tmp = df_portfolio_features[cols]
df_tmp.groupby(df_tmp['Conviction'].str[-2:])['CurrAlloc%'].sum().sort_values(ascending=False)

Conviction
SC    42.17
MC    29.28
LC    28.57
Name: CurrAlloc%, dtype: float64

In [26]:
# criteria-wise allocation
df_portfolio_features.groupby('Criteria')['CurrAlloc%'].sum().sort_values(ascending=False)

Criteria
XY24     26.88
X40      24.45
X40N     15.72
AR        9.33
XR        8.83
XY25      7.18
OX40N     6.84
SR        0.79
Name: CurrAlloc%, dtype: float64

In [27]:
# conviction-wise allocation
df_portfolio_features.groupby('Conviction')['CurrAlloc%'].sum().sort_values(ascending=False)

Conviction
X-LC    26.31
H-SC    21.75
X-MC    21.72
M-SC    10.02
X-SC     9.82
H-MC     5.09
M-MC     2.13
H-LC     1.30
M-LC     0.96
L-SC     0.58
L-MC     0.34
Name: CurrAlloc%, dtype: float64

In [28]:
# sector-wise stats
df_tmp = df_portfolio_features.groupby('Category')[['CurrAlloc%', 'Current', 'Current P/L', 'FTT Amt']].sum().sort_values(by=['Current', 'Current P/L'], ascending=False)
df_tmp['Current P/L%'] = round(df_tmp['Current P/L'] * 100 / df_tmp['Current'], 2)
df_tmp['FTT%'] = round(df_tmp['FTT Amt'] * 100 / df_tmp['Current'], 2)
cols = ['CurrAlloc%', 'Current P/L%', 'FTT%']
df_tmp[cols].sort_values(by=['CurrAlloc%'], ascending=False)

               CurrAlloc%  Current P/L%    FTT%
Category
FMCG                15.69        -13.32   53.36
IT                  10.99        -39.00  109.74
FINANCE             10.89        -14.74   64.65
MISC                 6.95        -30.87   87.72
ELECTRICAL           6.80          3.45   33.52
AUTO                 5.31        -13.01   57.58
PAINTS               5.30        -25.90   47.76
INSURANCE            5.18         -4.37   39.85
PHARMA               4.59         -4.71   38.32
BANKS                4.49        -16.15   75.11
AC                   2.03         -6.73   35.67
HEALTHCARE           1.90        -27.64   60.95
FOOTWEAR             1.81        -66.31  133.00
APPARELS             1.80         -1.28   35.83
TRAVEL               1.75        -73.05  159.70
DURABLES             1.74        -50.38   86.97
BREWERIES            1.62          2.26   18.04
REALTY               1.42         -5.74   23.11
CERAMICS             1.34        -55.84  103.18
CABLES               1.24         19.09   68.23
REFINERIES           1.19        -14.37   43.31
CEMENT               1.18        -54.48  170.05
ENGINEERING          1.15        -42.95  108.33
JEWELLERY            1.07       -101.77  171.87
CHEMICALS            1.04        -70.99  210.49
ENTERTAINMENT        0.75        -72.58  175.51
TEXTILES             0.44        -43.10   83.91
HOTELS               0.36       -116.23  192.50

In [29]:
# money to be made criteria-wise
df_portfolio_features.groupby('Criteria')['FTT Amt'].agg(['sum', 'count']).sort_values(by='sum', ascending=False)

                sum  count
Criteria
XY24      3632697.0     21
X40       1724775.0     17
XR        1326965.0     13
AR        1194843.0     10
X40N      1114462.0     12
OX40N      781898.0     10
XY25       382887.0      5
SR         302712.0      2

In [30]:
# money to be made conviction-wise
df_portfolio_features.groupby('Conviction')['FTT Amt'].agg(['sum', 'count']).sort_values(by='sum', ascending=False)

                  sum  count
Conviction
H-SC        3582502.0     24
X-LC        1704258.0     18
X-MC        1528056.0     15
M-SC        1439867.0     14
X-SC        1357034.0      9
H-MC         326988.0      3
L-SC         205876.0      2
M-LC         150117.0      1
M-MC          72173.0      2
L-MC          53003.0      1
H-LC          41365.0      1

In [31]:
# money to be made criteria and conviction-wise
df_portfolio_features.groupby(['Conviction', 'Criteria'])['FTT Amt'].agg(['sum', 'count']).sort_values(by='sum', ascending=False)

                           sum  count
Conviction Criteria
H-SC       XY24      1183187.0      6
           AR         945360.0      5
X-LC       X40        898570.0      8
M-SC       XY24       847854.0      6
H-SC       XR         813953.0      7
X-SC       XY24       800930.0      4
X-MC       X40        625010.0      7
           X40N       456810.0      4
X-SC       X40N       354909.0      3
X-LC       XY24       339899.0      2
M-SC       OX40N      339818.0      5
H-SC       OX40N      337290.0      4
X-LC       X40N       302743.0      5
H-SC       SR         302712.0      2
H-MC       XY24       231615.0      1
X-MC       XY24       229212.0      2
           XY25       217024.0      2
X-SC       X40        201195.0      2
M-SC       XR         177171.0      2
M-LC       XR         150117.0      1
X-LC       XY25       131411.0      2
L-SC       OX40N      104790.0      1
           XR         101086.0      1
H-MC       AR          95373.0      2
M-SC       AR          75024.0      1
L-MC       XR          53003.0      1
H-LC       AR          41365.0      1
M-MC       AR          37721.0      1
           XY25        34452.0      1
X-LC       XR          31635.0      1

In [32]:
# notebook execution time

end_time = time.time()
execution_time = round(end_time - start_time, 0)
print(f"Notebook execution time: {execution_time} seconds")

Notebook execution time: 35.0 seconds