<a href="https://colab.research.google.com/github/ankit-rathi/Quantvesting_v2/blob/main/myStocks_Portfolio_Analysis.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
'''
!pip install pandas==2.2.2 -qq
!pip install pyxirr -qq
!pip install ta -qq
!pip install yfinance==0.2.59 -qq
'''

'\n!pip install pandas==2.2.2 -qq\n!pip install pyxirr -qq\n!pip install ta -qq\n!pip install yfinance==0.2.59 -qq\n'

In [2]:
# import libraries

import numpy as np
import pandas as pd
import datetime
import warnings
warnings.filterwarnings('ignore')
import yfinance as yfin
import ta
import matplotlib.pyplot as plt
import requests

In [3]:
# notebook start time
import time
import datetime
import pytz

start_time = time.time()

# function to print date timestamp
def print_date_time():
  tz_NY = pytz.timezone('Asia/Kolkata')
  datetime_NY = datetime.datetime.now(tz_NY)
  print("Run date time (IST):", datetime_NY.strftime("%Y-%m-%d %H:%M:%S"))

In [4]:
# function to get booked and reserved amount
def get_amt():
  # fetch the JSON data from the URL
  url = "https://raw.githubusercontent.com/ankit-rathi/Tradevesting_v1/main/data/myPortfolioAmts.json"
  response = requests.get(url)
  pf_amts = response.json()  # parse the JSON data

  # extract values from the JSON
  py_booked_amt_dm = pf_amts["py_booked_amt_dm"]
  py_booked_amt_sv = pf_amts["py_booked_amt_sv"]
  cy_booked_amt_dm = pf_amts["cy_booked_amt_dm"]
  cy_booked_amt_sv = pf_amts["cy_booked_amt_sv"]
  reserve_amt_dm = pf_amts["reserve_amt_dm"]
  reserve_amt_sv = pf_amts["reserve_amt_sv"]

  # perform calculations
  py_booked_amt = py_booked_amt_dm + py_booked_amt_sv
  cy_booked_amt = cy_booked_amt_dm + cy_booked_amt_sv
  reserve_amt = reserve_amt_dm + reserve_amt_sv
  total_booked_amt = py_booked_amt + cy_booked_amt

  return total_booked_amt, reserve_amt, cy_booked_amt, py_booked_amt

gen_output = 0

In [5]:
# function to format the amount
def format_amt(number):
    abs_number = abs(number)

    if abs_number >= 1_00_00_000:  # Crores
        formatted_amt = f"{number / 1_00_00_000:.2f} C"
    elif abs_number >= 1_00_000:  # Lakhs
        formatted_amt = f"{number / 1_00_000:.2f} L"
    elif abs_number >= 1_000:  # Thousands
        formatted_amt = f"{number / 1_000:.2f} K"
    else:
        formatted_amt = f"{number:.2f}"

    return formatted_amt

# function to set start and end date
def get_start_end_date():
  start_date = (datetime.date.today() + datetime.timedelta(days=-365)).strftime('%Y-%m-%d')
  end_date = (datetime.date.today() + datetime.timedelta(days=1)).strftime('%Y-%m-%d')
  return start_date, end_date

# function to fetch my portfolio csv
def get_mypfs_df():
  mypfs_df = pd.read_csv('https://raw.githubusercontent.com/ankit-rathi/Tradevesting_v1/main/data/myPortfolioStocks.csv')
  return mypfs_df

# function to fetch my prospects csv
def get_mypps_df():
  mypps_df = pd.read_csv('https://raw.githubusercontent.com/ankit-rathi/Tradevesting_v1/main/data/myProspectsScrips.csv')
  return mypps_df

# function to fetch screener data
def get_myscreen_df():
  myscreen_df = pd.read_csv('https://raw.githubusercontent.com/ankit-rathi/Tradevesting_v1/main/data/myScreenerDB.csv')
  return myscreen_df

# function to fetch momentum data
def get_myinvmt_df():
  myinvmt_df = pd.read_csv('https://raw.githubusercontent.com/ankit-rathi/Tradevesting_v1/main/data/myInvestments.csv')
  return myinvmt_df

# function to get the stock ids
def get_stock_ids(df_pf):
  stock_n100 = df_pf['Symbol'].unique()

  exclude = ['CADILAHC','MMTC', 'MASFIN']

  stock_ids = df_pf[~df_pf['Symbol'].isin(exclude) ]['Symbol'].unique()

  #mypf = mypf[mypf.Forecast.notnull()]
  #stock_ids = mypf['Symbol'].unique()

  #stock_ids.sort()
  return stock_ids

# get features from screener data
def get_screener_features():
  myscreen_df = get_myscreen_df()
  cols = ['Symbol', 'EPS', 'MedPE', 'ROCE%', 'ROE%', 'CapType']
  return myscreen_df[cols]

# get relative strength
def get_relative_strength(stock_list):

    # Dictionary to store stock tickers and their corresponding percentage price change
    stock_changes = {}

    # Loop through each stock and fetch its price data
    for stock in stock_list:
        try:
            # Download the stock data for the given date range
            stock_data = yfin.Ticker(stock + '.NS').history(period='1mo', interval='1d')[map(str.title, ['open', 'close', 'low', 'high', 'volume'])]

            # Calculate the percentage change for the stock
            if len(stock_data) > 0:
                start_price = stock_data['Close'].iloc[0]
                end_price = stock_data['Close'].iloc[-1]
                percent_change = round(((end_price - start_price) / start_price) * 100, 2)
                stock_changes[stock] = percent_change
            else:
                stock_changes[stock] = np.nan  # If no data is available, set to NaN

        except Exception as e:
            print(f"Error fetching data for {stock}: {e}")
            stock_changes[stock] = np.nan

    # Create a DataFrame with stock tickers and their percentage changes
    df = pd.DataFrame(list(stock_changes.items()), columns=['Symbol', 'Percent_Change'])

    # Drop any stocks with missing data (NaN values)
    df = df.dropna()

    # Calculate the percentile rank based on percentage change
    df['RSP'] = round(df['Percent_Change'].rank(pct=True) * 100, 2)
    cols = ['Symbol', 'RSP']
    df = df[cols]
    # Sort by percentile rank (optional)
    df = df.sort_values(by='RSP', ascending=False).reset_index(drop=True)

    return df

In [6]:
# function to get stock technicals
def stock_prec_dev(stock_symbol):
    #stock_symbol = 'ULTRACEMCO.NS'
    short_window = 20
    mid_window = 50
    long_window = 200
    moving_avg = 'SMA'

    start = datetime.datetime(*map(int, start_date.split('-')))
    end = datetime.datetime(*map(int, end_date.split('-')))

    stock_df = yfin.Ticker(stock_symbol + '.NS').history(period='max', interval='1d')[map(str.title, ['open', 'close', 'low', 'high', 'volume'])]

    stock_df['Max'] = round(max(stock_df['Close']),2)
    stock_df = stock_df[(stock_df.index <= end_date) & (stock_df.index >= start_date)]
    stock_df['200_SMA'] = round(stock_df['Close'].rolling(window = 200, min_periods = 1).mean(),0)
    stock_df['Dev%_200'] = round((stock_df['Close'] - stock_df['200_SMA'])*100/stock_df['200_SMA'],2)
    stock_df.dropna(axis = 0, inplace = True) # remove any null rows

    stock_df['20_SMA'] = stock_df['Close'].rolling(window=20).mean()
    stock_df['50_SMA'] = stock_df['Close'].rolling(window=50).mean()
    stock_df['Symbol'] = stock_symbol

    stock_df['Close'] = round(stock_df['Close'],2)
    stock_df['Min'] = round(min(stock_df['Close']),2)
    stock_df['RSI_14'] = ta.momentum.RSIIndicator(close=stock_df['Close'], window=14).rsi()
    stock_df['RSI_14'] = round(stock_df['RSI_14'],0)
    stock_df['Prev_Close'] = stock_df['Close'].shift(1)
    stock_df.drop(['Open', 'Low', 'High', 'Volume'], axis=1, inplace=True)
    stock_df = stock_df.tail(1)

    max_SMA = max(stock_df['20_SMA'].item(), stock_df['50_SMA'].item(), stock_df['200_SMA'].item())
    min_SMA = min(stock_df['20_SMA'].item(), stock_df['50_SMA'].item(), stock_df['200_SMA'].item())
    ABS_Spread = max_SMA - min_SMA
    stock_df['Spread%'] = round((ABS_Spread / stock_df['200_SMA'].item()) * 100,2)

    return stock_df

# function to compute stock attributes
def get_common_features(stock_ids, df_mypf):

  df_prec_dev = pd.DataFrame()
  df_tmp = get_screener_features()
  df_rs = get_relative_strength(stock_ids)

  for stock_id in stock_ids:
      tmp = stock_prec_dev(stock_id)
      tmp = tmp.reset_index()
      df_prec_dev = pd.concat([df_prec_dev, tmp], ignore_index = True)
  df_prec_dev = pd.merge(df_prec_dev, df_mypf, on= 'Symbol')
  df_prec_dev = pd.merge(df_prec_dev, df_tmp, on= 'Symbol', how='left')
  df_prec_dev = pd.merge(df_prec_dev, df_rs, on= 'Symbol', how='left')
  #print(df_prec_dev.columns)
  df_prec_dev['Curr_PE'] = round(df_prec_dev['Close']/df_prec_dev['EPS'],1)
  df_prec_dev['Dev%_PE'] = round((df_prec_dev['Curr_PE'] - df_prec_dev['MedPE'])*100/df_prec_dev['MedPE'],2)
  df_prec_dev['Conviction'] = df_prec_dev['Conviction'] + '-' + df_prec_dev['CapType']
  return df_prec_dev

# function to arrange stock features
def arrange_features(df_stocks, common_cols, diff_cols):
  df_stocks_common = df_stocks[common_cols].drop_duplicates()
  df_stocks_diff = df_stocks[diff_cols]
  df_stocks_diff['Investment'] = df_stocks_diff['AvgCost'] * df_stocks_diff['Shares']
  df_stocks_diff = df_stocks_diff.groupby(['Symbol'])[['Shares', 'Investment']].aggregate(['sum']).reset_index()
  df_stocks_diff.columns = ['Symbol', 'Shares', 'Investment']
  df_stocks_diff['AvgCost'] = round(df_stocks_diff['Investment']/df_stocks_diff['Shares'],2)
  df_stocks = pd.merge(df_stocks_diff, df_stocks_common, on='Symbol')
  return df_stocks

# plot fact distribution across dimension
def plot_pie_chart(df, dimension, fact):
  # grouping the data by category and calculating the sum of fact for each type
  grouped_data = df.groupby(dimension)[fact].sum()

  # sorting the grouped data in descending order
  grouped_data = grouped_data.sort_values(ascending=False)

  # creating a pie chart
  grouped_data.plot.pie(autopct='%1.1f%%', startangle=90, figsize=(6, 6))

  # adding a title and displaying the plot
  plt.title(f'{dimension} {fact} Distribution')
  plt.ylabel('')  # To hide the y-label
  plt.show()

In [7]:
# function to get portfolio features

def get_portfolio_features(df_common_features):

  print_date_time()
  print('-------------------')

  #df_common_features["Target"] = df_common_features["Target"].fillna(df_common_features["Max"])
  df_common_features['NTT'] = np.where(df_common_features['Strategy']== 'NTT', df_common_features["Target"], df_common_features['Max'])
  df_common_features['LTT'] = np.where(df_common_features['Strategy']== 'BTT', df_common_features["Target"], df_common_features['Max'])
  df_common_features['BOL'] = df_common_features['Min']

  tmp_df = df_common_features[df_common_features['Symbol'].isin(mypf_df[mypf_df['InPortfolio'] != 'NA'].Symbol.values)]
  print('qualified stocks: '+str(len(tmp_df['Symbol'].unique())))
  tmp_df1 = tmp_df[tmp_df['LatestQtr'] == 1]
  print('with latest results: '+str(len(tmp_df1['Symbol'].unique())))
  tmp_df1 = tmp_df1[tmp_df1['StarStock'] == 1]
  print('still star stocks: '+str(len(tmp_df1['Symbol'].unique())))
  tmp_df['Investment'] = tmp_df['AvgCost'] * tmp_df['Shares']
  tmp_df['Current'] = round(tmp_df['Close'] * tmp_df['Shares'],0)
  tmp_df['Previous'] = tmp_df['Prev_Close'] * tmp_df['Shares']
  tmp_df['EstimatedST'] = tmp_df['NTT'] * tmp_df['Shares']
  tmp_df['EstimatedLT'] = tmp_df['LTT'] * tmp_df['Shares']
  tmp_df['Current P/L'] = round((tmp_df['Current'] - tmp_df['Investment']),0)
  tmp_df['Today P/L%'] = round((tmp_df['Current'] - tmp_df['Previous'])*100/tmp_df['Previous'],2)
  tmp_df['Current P/L%'] = round((tmp_df['Current'] - tmp_df['Investment'])*100/tmp_df['Investment'],2)
  tmp_df['EstimatedST P/L%'] = round((tmp_df['EstimatedST'] - tmp_df['Investment'])*100/tmp_df['Investment'],2)
  tmp_df['EstimatedLT P/L%'] = round((tmp_df['EstimatedLT'] - tmp_df['Investment'])*100/tmp_df['Investment'],2)
  tmp_df['NTT%'] = round((tmp_df['NTT'] - tmp_df['Close'])*100/tmp_df['Close'],2)
  tmp_df['LTT%'] = round((tmp_df['LTT'] - tmp_df['Close'])*100/tmp_df['Close'],2)
  tmp_df['Gained%'] = round((tmp_df['Close'] - tmp_df['BOL'])*100/tmp_df['BOL'],2)
  investment = round(sum(tmp_df['AvgCost']*tmp_df['Shares']),0)
  current = round(sum(tmp_df['Close']*tmp_df['Shares']),0)
  tmp_df['InitAlloc%'] = round(tmp_df['Investment']*100/investment,2)
  tmp_df['CurrAlloc%'] = round(tmp_df['Current']*100/current,2)
  tmp_df['FTT'] = tmp_df['LTT']
  tmp_df.loc[tmp_df['Strategy'] == 'NTT', 'FTT'] = tmp_df['NTT']
  tmp_df['FTT%'] = tmp_df['LTT%']
  tmp_df.loc[tmp_df['Strategy'] == 'NTT', 'FTT%'] = tmp_df['NTT%']
  tmp_df['FTT Amt'] = round(tmp_df['FTT%'] * tmp_df['Current']/100,0)
  tmp_df['OTT%'] = round((tmp_df['FTT'] - tmp_df['AvgCost'])*100/tmp_df['AvgCost'],2)
  tmp_df['RRR Ind'] = round(tmp_df['Current P/L']/tmp_df['FTT Amt'],2)
  tmp_df['Risk Ind'] = round(tmp_df['Current P/L%']*tmp_df['CurrAlloc%'],0)

  return tmp_df

# function to print portfolio features
def print_portfolio_stats(df_portfolio_features, myinvmt_df):
  from pyxirr import xirr

  total_booked_amt, reserve_amt, cy_booked_amt, py_booked_amt = get_amt()

  dates = myinvmt_df['Date'].values
  dates = np.append(dates, datetime.date.today().strftime('%d-%b-%y'))
  investment = myinvmt_df['Investment'].values
  dates= pd.to_datetime(dates)

  current = round(sum(df_portfolio_features['Close']*df_portfolio_features['Shares']),0) + reserve_amt
  investment_xirr = np.append(investment, current)
  cagr = round(xirr(pd.DataFrame({"dates": dates, "amounts": investment_xirr}))*100,2)

  investment = -sum(investment)
  invested = round(sum(df_portfolio_features['AvgCost']*df_portfolio_features['Shares']),0) + reserve_amt
  previous = round(sum(df_portfolio_features['Prev_Close']*df_portfolio_features['Shares']),0) + reserve_amt
  cy_invested = investment + py_booked_amt

  today_pnl_amount = current-previous
  today_pnl_percentage = round((current-previous)*100/previous,2)

  curr_pnl_amount = current-invested
  curr_pnl_percentage = round((curr_pnl_amount)*100/(cy_invested),2)

  cy_pnl_amount = cy_booked_amt + curr_pnl_amount
  cy_pnl_percentage = round((cy_pnl_amount)*100/cy_invested,2)

  overall_pnl_amount = total_booked_amt + curr_pnl_amount
  overall_pnl_percentage = round((overall_pnl_amount)*100/investment,2)

  estimate_st = round(sum(df_portfolio_features['FTT']*df_portfolio_features['Shares']),0)  + reserve_amt
  est_st_pnl_amount = estimate_st-current
  est_st_pnl_percentage = round((est_st_pnl_amount)*100/current,2)

  estimate_lt = round(sum(df_portfolio_features['LTT']*df_portfolio_features['Shares']),0)  + reserve_amt
  est_lt_pnl_amount = estimate_lt-current
  est_lt_pnl_percentage = round((est_lt_pnl_amount)*100/current,2)

  total_profit = round(sum(df_portfolio_features[df_portfolio_features['Current P/L%'] > 0]['Current']) - sum(df_portfolio_features[df_portfolio_features['Current P/L%'] > 0]['Investment']),0)
  total_loss = round(sum(df_portfolio_features[df_portfolio_features['Current P/L%'] < 0]['Current']) - sum(df_portfolio_features[df_portfolio_features['Current P/L%'] < 0]['Investment']),0)

  cy_booked_percentage = round((cy_booked_amt)*100/current,2)
  py_booked_percentage = round((py_booked_amt)*100/investment,2)
  total_booked_percentage = round((total_booked_amt)*100/investment,2)

  print('-------------------')
  print('Initial Investment: ', format_amt(investment))
  print('CY Investment: ', format_amt(cy_invested))
  print('Reserve: ', format_amt(reserve_amt))
  print('Current: ',  format_amt(current))
  print('-------------------')
  print('Today PnL: '+ '{} ({}%)'.format(format_amt(today_pnl_amount), today_pnl_percentage))
  print('Current PnL: '+ '{} ({}%)'.format(format_amt(curr_pnl_amount), curr_pnl_percentage))
  print('CY Booked + Current PnL: '+ '{} ({}%)'.format(format_amt(cy_pnl_amount), cy_pnl_percentage))
  print('-------------------')
  print('Total profit: ', format_amt(total_profit))
  print('Total loss: ', format_amt(total_loss))
  print('-------------------')
  print('Total Booked + Current PnL: '+ '{} ({}%)'.format(format_amt(overall_pnl_amount), overall_pnl_percentage))
  print('Total Booked PnL: '+ '{} ({}%)'.format(format_amt(total_booked_amt), total_booked_percentage))
  print('Curr Year Booked PnL: '+ '{} ({}%)'.format(format_amt(cy_booked_amt), cy_booked_percentage))
  print('Prev Year Booked PnL: '+ '{} ({}%)'.format(format_amt(py_booked_amt), py_booked_percentage))
  print('===================')
  print('Est FTT: ',  format_amt(estimate_st))
  print('Est FTT PnL: '+ '{} ({}%)'.format(format_amt(est_st_pnl_amount), est_st_pnl_percentage))

  print('===================')
  print('Deployed: ', format_amt(investment))

  print('Current: ', format_amt(current))

  print('CAGR/XIRR %: '+'{}%'.format(cagr))

In [8]:
# get start and end date
start_date, end_date = get_start_end_date()

# get portfolio and prospects data
mypfs_df = get_mypfs_df()
mypps_df = get_mypps_df()
myinvmt_df = get_myinvmt_df()

# merge above datasets
mypf_df = pd.merge(mypfs_df, mypps_df, on="Symbol")

# seggregate dm and sv portfolio
dm_pf = mypf_df[mypf_df['InPortfolio'] == 'DM']
sv_pf = mypf_df[mypf_df['InPortfolio'] == 'SV']

# build portfolio stock dataframe
dm_stocks = get_stock_ids(dm_pf)
sv_stocks = get_stock_ids(sv_pf)
df_stocks = pd.concat([dm_pf,sv_pf], ignore_index = True)

# arrange common and diff stock features
common_cols = ['Symbol', 'Target', 'Criteria', 'Strategy', 'CumlRnk', 'LatestQtr', 'StarStock', 'Conviction', 'Category', 'InFolio', 'XIRR', 'MBQ']
diff_cols = ['Symbol', 'AvgCost', 'Shares']
df_stocks = arrange_features(df_stocks, common_cols, diff_cols)

# get common features
stock_ids = df_stocks['Symbol'].values
df_common_features = get_common_features(stock_ids, df_stocks)

df_common_features.reset_index(drop=True, inplace=True)
df_common_features.drop(['Date'], axis=1, inplace=True)
# get and print portfolio features
df_portfolio_features = get_portfolio_features(df_common_features)

print_portfolio_stats(df_portfolio_features, myinvmt_df)

df = df_portfolio_features
#plot_pie_chart(df, 'CapType', 'Current')
list_ox40n = list(df[df['MBQ'].str.contains('OX40N', na=False)]['Symbol'].values)

Run date time (IST): 2026-03-13 11:39:48
-------------------
qualified stocks: 86
with latest results: 26
still star stocks: 15
-------------------
Initial Investment:  1.36 C
CY Investment:  1.62 C
Reserve:  66.25 K
Current:  1.35 C
-------------------
Today PnL: -1.18 L (-0.87%)
Current PnL: -42.33 L (-26.05%)
CY Booked + Current PnL: -26.65 L (-16.4%)
-------------------
Total profit:  1.08 L
Total loss:  -43.40 L
-------------------
Total Booked + Current PnL: 33.12 K (0.24%)
Total Booked PnL: 42.66 L (31.48%)
Curr Year Booked PnL: 15.68 L (11.65%)
Prev Year Booked PnL: 26.98 L (19.91%)
===================
Est FTT:  2.47 C
Est FTT PnL: 1.13 C (83.72%)
===================
Deployed:  1.36 C
Current:  1.35 C
CAGR/XIRR %: -0.34%

In [9]:
# top 5 near their targets
cols = ['Symbol', 'Today P/L%', 'Current P/L%', 'FTT%', 'OTT%', 'FTT Amt', 'Current P/L', 'Current', 'FTT', 'Dev%_PE', 'RSI_14','Conviction', 'Spread%',  'CumlRnk', 'RRR Ind', 'CurrAlloc%', 'Gained%', 'Criteria', 'Strategy', 'Category']
df_tmp = df_portfolio_features[~df_portfolio_features['Symbol'].isin(['ENRIN','BLUSPRING','DIGITIDE'])]
df_tmp = df_tmp.sort_values(by = 'FTT Amt', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
19,COALINDIA,0.49,16.17,1.29,17.67,2255.0,24328.0,174788.0,478.51,40.60,71.0,L-LC,12.67,185.0,10.79,1.31,35.74,XY25,ATH,MINING
77,TTKPRESTIG,1.04,-24.05,31.78,0.09,24325.0,-24234.0,76543.0,770.00,77.59,61.0,M-SC,15.19,250.0,-1.00,0.57,29.33,OX40N,NTT,DURABLES
50,MASFIN,-0.67,-7.53,31.47,21.57,28512.0,-7380.0,90600.0,397.04,-20.05,38.0,H-SC,3.61,167.0,-0.26,0.68,25.69,XR,ATH,FINANCE
37,ICICIGI,0.09,-1.64,21.33,19.34,41984.0,-3278.0,196831.0,2252.93,-17.38,42.0,X-MC,1.88,66.0,-0.08,1.47,11.39,X40,ATH,INSURANCE
78,UNITDSPR,-0.26,-0.10,20.88,20.77,48842.0,-224.0,233920.0,1644.00,-11.40,47.0,X-MC,1.28,64.0,-0.00,1.75,6.61,X40N,NTT,BREWERIES

In [10]:
# top 5 today
df_tmp = df_portfolio_features.sort_values(by = 'Today P/L%', ascending=False)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
35,HINDUNILVR,2.56,-14.74,33.33,13.67,73046.0,-37903.0,219160.0,2922.0,-36.70,37.0,X-LC,5.61,9.0,-0.52,1.64,2.80,XY25,NTT,FMCG
69,SURYODAY,1.60,-26.90,68.30,23.03,89409.0,-48164.0,130907.0,216.0,42.54,48.0,H-SC,7.66,166.0,-0.54,0.98,29.89,XR,NTT,BANKS
5,ANGELONE,1.35,-11.50,40.31,24.18,108812.0,-35062.0,269938.0,303.0,-87.39,33.0,X-SC,6.83,97.0,-0.32,2.02,13.05,X40N,NTT,FINANCE
48,KANSAINER,1.33,-36.40,78.42,13.47,134493.0,-98163.0,171504.0,340.0,-45.39,34.0,H-SC,16.98,162.0,-0.73,1.28,2.82,XY24,NTT,PAINTS
77,TTKPRESTIG,1.04,-24.05,31.78,0.09,24325.0,-24234.0,76543.0,770.0,77.59,61.0,M-SC,15.19,250.0,-1.00,0.57,29.33,OX40N,NTT,DURABLES

In [11]:
# bottom 5 today
df_tmp = df_portfolio_features.sort_values(by = 'Today P/L%', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
14,BOSCH-HCIL,-3.75,-44.05,78.70,-0.01,56280.0,-56293.0,71512.0,2282.0,14530.43,37.0,M-SC,2.45,231.0,-1.00,0.53,0.00,OX40N,BTT,AC
56,RAJOOENG,-3.34,-43.18,145.71,39.61,84862.0,-44260.0,58240.0,143.1,-61.60,38.0,H-SC,30.46,136.0,-0.52,0.43,0.00,AR,ATH,MISC
75,TMPV,-3.25,-28.52,91.08,36.58,231653.0,-101501.0,254340.0,600.0,-84.72,29.0,X-LC,2.05,4.0,-0.44,1.90,0.00,XY24,NTT,AUTO
13,BERGEPAINT,-3.08,-24.50,65.98,25.32,128402.0,-63141.0,194608.0,680.0,-28.64,21.0,X-MC,15.99,68.0,-0.49,1.45,0.00,XY24,NTT,PAINTS
7,ATULAUTO,-3.01,-28.94,104.85,45.57,146874.0,-57052.0,140080.0,844.0,3018.92,36.0,M-SC,4.07,248.0,-0.39,1.05,6.01,XY24,NTT,AUTO

In [12]:
# top 5 to exit based on CumlRnk
df_tmp = df_portfolio_features[~df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])]
df_tmp = df_tmp[(df_tmp['Current P/L%'] > -1) & (df_tmp['Current P/L%'] < 1)].sort_values(by = 'CumlRnk', ascending=False)
df_tmp[cols].head()

Empty DataFrame
Columns: [Symbol, Today P/L%, Current P/L%, FTT%, OTT%, FTT Amt, Current P/L, Current, FTT, Dev%_PE, RSI_14, Conviction, Spread%, CumlRnk, RRR Ind, CurrAlloc%, Gained%, Criteria, Strategy, Category]
Index: []

In [13]:
# OX40N stocks to exit
df_tmp = df_portfolio_features[(df_portfolio_features['Symbol'].isin(list_ox40n))].sort_values(by = 'Current P/L%', ascending=False)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
27,FINCABLES,-2.98,9.91,89.16,107.91,144688.0,14635.0,162279.0,1641.55,-1.07,52.0,M-SC,7.75,220.0,0.10,1.21,22.09,OX40N,ATH,CABLES
77,TTKPRESTIG,1.04,-24.05,31.78,0.09,24325.0,-24234.0,76543.0,770.00,77.59,61.0,M-SC,15.19,250.0,-1.00,0.57,29.33,OX40N,NTT,DURABLES
66,SIS,-2.36,-35.42,87.77,21.26,62936.0,-39326.0,71706.0,528.00,1676.68,31.0,H-SC,11.48,168.0,-0.62,0.54,0.00,OX40N,NTT,MISC
48,KANSAINER,1.33,-36.40,78.42,13.47,134493.0,-98163.0,171504.0,340.00,-45.39,34.0,H-SC,16.98,162.0,-0.73,1.28,2.82,XY24,NTT,PAINTS
72,TATAELXSI,-0.73,-38.05,113.12,32.03,92387.0,-50163.0,81672.0,9161.00,-22.55,28.0,H-SC,17.73,158.0,-0.54,0.61,0.00,OX40N,NTT,IT

In [14]:
# top 5 to book for rotation
df_tmp = df_portfolio_features[(df_portfolio_features['Current P/L%'] > 20) ].sort_values(by = 'CumlRnk', ascending=False)
df_tmp[cols].head()

Empty DataFrame
Columns: [Symbol, Today P/L%, Current P/L%, FTT%, OTT%, FTT Amt, Current P/L, Current, FTT, Dev%_PE, RSI_14, Conviction, Spread%, CumlRnk, RRR Ind, CurrAlloc%, Gained%, Criteria, Strategy, Category]
Index: []

In [15]:
# top 5 to monitor for exit
df_tmp = df_portfolio_features[~df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])]
df_tmp = df_tmp[(df_tmp['Current P/L%'] > 0) ].sort_values(by = 'Dev%_PE', ascending=False)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
19,COALINDIA,0.49,16.17,1.29,17.67,2255.0,24328.0,174788.0,478.51,40.60,71.0,L-LC,12.67,185.0,10.79,1.31,35.74,XY25,ATH,MINING
27,FINCABLES,-2.98,9.91,89.16,107.91,144688.0,14635.0,162279.0,1641.55,-1.07,52.0,M-SC,7.75,220.0,0.10,1.21,22.09,OX40N,ATH,CABLES
1,ABB,0.90,18.65,22.68,45.57,70402.0,48797.0,310416.0,7934.00,-23.74,70.0,H-MC,11.14,125.0,0.69,2.32,37.85,AR,NTT,ELECTRICAL

In [16]:
# top 5 to book for rotation from weak conviction
df_tmp = df_portfolio_features[~df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])]
df_tmp = df_tmp[~df_tmp['Criteria'].isin(['XY25','XY24','X40', 'X40N'])].sort_values(by = 'RRR Ind', ascending=False)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
1,ABB,0.90,18.65,22.68,45.57,70402.0,48797.0,310416.0,7934.00,-23.74,70.0,H-MC,11.14,125.0,0.69,2.32,37.85,AR,NTT,ELECTRICAL
27,FINCABLES,-2.98,9.91,89.16,107.91,144688.0,14635.0,162279.0,1641.55,-1.07,52.0,M-SC,7.75,220.0,0.10,1.21,22.09,OX40N,ATH,CABLES
40,INDIAMART,0.41,-9.37,128.10,106.72,143186.0,-11559.0,111777.0,4810.62,-59.18,42.0,H-SC,9.61,140.0,-0.08,0.83,11.82,AR,ATH,MISC
85,ZYDUSLIFE,-0.86,-4.14,41.49,35.63,83349.0,-8685.0,200889.0,1286.17,-16.67,50.0,H-MC,5.03,120.0,-0.10,1.50,11.84,AR,ATH,PHARMA
84,WIPRO,-1.19,-17.93,109.90,72.27,152838.0,-30378.0,139070.0,420.00,-25.96,33.0,M-LC,15.09,98.0,-0.20,1.04,2.41,XR,NTT,IT

In [17]:
# top 5 to accumulate based on lowest RSI_14
df_tmp = df_portfolio_features[df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])].sort_values(by = 'RSI_14', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
58,RELAXO,-1.74,-61.48,295.43,52.31,165178.0,-89249.0,55911.0,1176.00,-58.96,17.0,X-SC,20.17,92.0,-0.54,0.42,0.0,X40N,NTT,FOOTWEAR
3,ACC,-1.82,-37.02,177.55,74.81,299839.0,-99252.0,168876.0,3906.00,-55.22,19.0,X-SC,13.45,85.0,-0.33,1.26,0.0,XY24,BTT,CEMENT
12,BATAINDIA,-1.74,-54.75,198.79,35.20,115743.0,-70446.0,58224.0,2096.00,-23.61,19.0,X-SC,26.88,91.0,-0.61,0.43,0.0,X40,NTT,FOOTWEAR
73,TCS,-0.45,-28.63,77.34,26.57,255730.0,-132616.0,330657.0,4311.58,-39.69,20.0,X-LC,14.83,2.0,-0.52,2.47,0.0,X40,ATH,IT
13,BERGEPAINT,-3.08,-24.50,65.98,25.32,128402.0,-63141.0,194608.0,680.00,-28.64,21.0,X-MC,15.99,68.0,-0.49,1.45,0.0,XY24,NTT,PAINTS

In [18]:
# top 5 to accumulate based on Spread and CumlRnk
df_tmp = df_portfolio_features[df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])]
df_tmp = df_tmp[(df_tmp['CumlRnk'] < 100)].sort_values(by = 'Spread%', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
78,UNITDSPR,-0.26,-0.10,20.88,20.77,48842.0,-224.0,233920.0,1644.00,-11.40,47.0,X-MC,1.28,64.0,-0.00,1.75,6.61,X40N,NTT,BREWERIES
37,ICICIGI,0.09,-1.64,21.33,19.34,41984.0,-3278.0,196831.0,2252.93,-17.38,42.0,X-MC,1.88,66.0,-0.08,1.47,11.39,X40,ATH,INSURANCE
22,DABUR,0.27,-9.95,59.57,43.70,133074.0,-24677.0,223391.0,735.00,-18.36,31.0,X-MC,1.93,70.0,-0.19,1.67,3.61,XY24,BTT,FMCG
75,TMPV,-3.25,-28.52,91.08,36.58,231653.0,-101501.0,254340.0,600.00,-84.72,29.0,X-LC,2.05,4.0,-0.44,1.90,0.00,XY24,NTT,AUTO
59,RELIANCE,0.17,-10.48,39.97,25.30,71907.0,-21060.0,179903.0,1952.00,-12.73,46.0,X-LC,2.93,21.0,-0.29,1.34,20.11,XY25,BTT,REFINERIES

In [19]:
# top 5 to accumulate based on lowest Gained%
df_tmp = df_portfolio_features[df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])].sort_values(by = 'Gained%', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
3,ACC,-1.82,-37.02,177.55,74.81,299839.0,-99252.0,168876.0,3906.00,-55.22,19.0,X-SC,13.45,85.0,-0.33,1.26,0.0,XY24,BTT,CEMENT
12,BATAINDIA,-1.74,-54.75,198.79,35.20,115743.0,-70446.0,58224.0,2096.00,-23.61,19.0,X-SC,26.88,91.0,-0.61,0.43,0.0,X40,NTT,FOOTWEAR
13,BERGEPAINT,-3.08,-24.50,65.98,25.32,128402.0,-63141.0,194608.0,680.00,-28.64,21.0,X-MC,15.99,68.0,-0.49,1.45,0.0,XY24,NTT,PAINTS
43,INFY,-0.02,-13.85,55.83,34.24,150491.0,-43336.0,269552.0,1972.00,-32.15,25.0,X-LC,13.09,3.0,-0.29,2.01,0.0,X40,NTT,IT
52,PAGEIND,-1.85,-21.00,69.75,34.11,147891.0,-56349.0,212030.0,51418.64,-43.35,29.0,X-MC,20.48,55.0,-0.38,1.58,0.0,X40,ATH,APPARELS

In [20]:
# top 5 to accumulate based on lowest CurrAlloc%
df_tmp = df_portfolio_features[df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])].sort_values(by = 'CurrAlloc%', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
58,RELAXO,-1.74,-61.48,295.43,52.31,165178.0,-89249.0,55911.0,1176.00,-58.96,17.0,X-SC,20.17,92.0,-0.54,0.42,0.00,X40N,NTT,FOOTWEAR
12,BATAINDIA,-1.74,-54.75,198.79,35.20,115743.0,-70446.0,58224.0,2096.00,-23.61,19.0,X-SC,26.88,91.0,-0.61,0.43,0.00,X40,NTT,FOOTWEAR
54,QUESS,-2.11,-23.62,127.69,73.90,104149.0,-25229.0,81564.0,424.00,-58.68,37.0,X-SC,18.43,80.0,-0.24,0.61,0.62,XY24,NTT,MISC
36,HONAUT,-0.51,-21.11,91.81,51.31,139666.0,-40713.0,152125.0,58357.33,-34.47,41.0,X-SC,13.90,90.0,-0.29,1.14,2.44,X40N,ATH,ELECTRICAL
2,ABBOTINDIA,0.04,-10.45,31.84,18.07,50998.0,-18685.0,160170.0,35195.00,-23.83,46.0,X-MC,11.05,58.0,-0.37,1.20,1.54,X40,ATH,PHARMA

In [21]:
# top 5 to accumulate based on CumlRnk
df_tmp = df_portfolio_features.sort_values(by = 'CumlRnk', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
45,ITC,0.02,-19.89,48.61,19.06,132471.0,-67648.0,272518.0,452.00,-55.92,34.0,X-LC,17.23,1.0,-0.51,2.03,0.02,X40,NTT,FMCG
73,TCS,-0.45,-28.63,77.34,26.57,255730.0,-132616.0,330657.0,4311.58,-39.69,20.0,X-LC,14.83,2.0,-0.52,2.47,0.00,X40,ATH,IT
43,INFY,-0.02,-13.85,55.83,34.24,150491.0,-43336.0,269552.0,1972.00,-32.15,25.0,X-LC,13.09,3.0,-0.29,2.01,0.00,X40,NTT,IT
75,TMPV,-3.25,-28.52,91.08,36.58,231653.0,-101501.0,254340.0,600.00,-84.72,29.0,X-LC,2.05,4.0,-0.44,1.90,0.00,XY24,NTT,AUTO
34,HCLTECH,-0.38,-12.20,41.03,23.83,87156.0,-29503.0,212421.0,1908.19,-7.78,29.0,X-LC,9.88,8.0,-0.34,1.59,1.91,X40,ATH,IT

In [22]:
# top 5 for average up
df_tmp = df_portfolio_features[(df_portfolio_features['Dev%_200'] > 5)].sort_values(by = 'CurrAlloc%', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
67,SONACOMS,-1.53,-13.07,60.00,39.09,52763.0,-13221.0,87938.0,804.02,-31.14,45.0,M-MC,9.52,193.0,-0.25,0.66,24.40,AR,ATH,AUTO
19,COALINDIA,0.49,16.17,1.29,17.67,2255.0,24328.0,174788.0,478.51,40.60,71.0,L-LC,12.67,185.0,10.79,1.31,35.74,XY25,ATH,MINING
11,BANDHANBNK,-0.43,-14.74,125.68,92.42,298493.0,-41057.0,237502.0,400.00,104.02,55.0,H-SC,9.72,174.0,-0.14,1.77,30.83,XY24,NTT,BANKS
1,ABB,0.90,18.65,22.68,45.57,70402.0,48797.0,310416.0,7934.00,-23.74,70.0,H-MC,11.14,125.0,0.69,2.32,37.85,AR,NTT,ELECTRICAL

In [23]:
# top 5 RSP
df_tmp = df_portfolio_features.sort_values(by = 'RSP', ascending=False)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
19,COALINDIA,0.49,16.17,1.29,17.67,2255.0,24328.0,174788.0,478.51,40.60,71.0,L-LC,12.67,185.0,10.79,1.31,35.74,XY25,ATH,MINING
1,ABB,0.90,18.65,22.68,45.57,70402.0,48797.0,310416.0,7934.00,-23.74,70.0,H-MC,11.14,125.0,0.69,2.32,37.85,AR,NTT,ELECTRICAL
26,EASEMYTRIP,-1.24,-60.54,269.23,45.70,187842.0,-107045.0,69770.0,26.40,-27.55,41.0,M-SC,18.24,204.0,-0.57,0.52,14.95,XY24,NTT,TRAVEL
11,BANDHANBNK,-0.43,-14.74,125.68,92.42,298493.0,-41057.0,237502.0,400.00,104.02,55.0,H-SC,9.72,174.0,-0.14,1.77,30.83,XY24,NTT,BANKS
31,HAPPSTMNDS,-2.71,-50.32,272.08,84.85,173239.0,-64493.0,63672.0,1480.71,-40.86,56.0,H-SC,28.05,152.0,-0.37,0.48,17.91,AR,ATH,IT

In [24]:
# Top N allocation
df_tmp = df_portfolio_features.sort_values(by = 'CurrAlloc%', ascending=False)
top_n_values = [10, 25, 50]

sum_df = pd.DataFrame({
    'Top_N': top_n_values,
    'Sum_Alloc%': [df_tmp['CurrAlloc%'].head(n).sum() for n in top_n_values]
})

sum_df

   Top_N  Sum_Alloc%
0     10       20.43
1     25       45.33
2     50       77.86

In [25]:
# market-cap-wise allocation
df_tmp = df_portfolio_features[cols]
df_tmp.groupby(df_tmp['Conviction'].str[-2:])['CurrAlloc%'].sum().sort_values(ascending=False)

Conviction
SC    44.63
MC    30.36
LC    25.01
Name: CurrAlloc%, dtype: float64

In [26]:
# criteria-wise allocation
df_portfolio_features.groupby('Criteria')['CurrAlloc%'].sum().sort_values(ascending=False)

Criteria
XY24     27.19
X40      23.73
X40N     15.13
AR        9.30
XY25      8.74
XR        8.23
OX40N     6.92
SR        0.76
Name: CurrAlloc%, dtype: float64

In [27]:
# conviction-wise allocation
df_portfolio_features.groupby('Conviction')['CurrAlloc%'].sum().sort_values(ascending=False)

Conviction
X-MC    22.85
H-SC    21.71
X-LC    21.43
X-SC    12.11
M-SC    10.22
H-MC     5.11
M-MC     2.05
L-LC     1.31
H-LC     1.23
M-LC     1.04
L-SC     0.59
L-MC     0.35
Name: CurrAlloc%, dtype: float64

In [28]:
# sector-wise stats
df_tmp = df_portfolio_features.groupby('Category')[['CurrAlloc%', 'Current', 'Current P/L', 'FTT Amt']].sum().sort_values(by=['Current', 'Current P/L'], ascending=False)
df_tmp['Current P/L%'] = round(df_tmp['Current P/L'] * 100 / df_tmp['Current'], 2)
df_tmp['FTT%'] = round(df_tmp['FTT Amt'] * 100 / df_tmp['Current'], 2)
cols = ['CurrAlloc%', 'Current P/L%', 'FTT%']
df_tmp[cols].sort_values(by=['CurrAlloc%'], ascending=False)

               CurrAlloc%  Current P/L%    FTT%
Category
FMCG                15.23        -22.38   65.83
FINANCE             12.88        -24.62   75.40
IT                  11.71        -43.77  116.94
MISC                 7.00        -42.76  104.77
ELECTRICAL           6.76         -7.05   48.04
PAINTS               5.16        -42.50   67.25
INSURANCE            4.77         -6.18   42.51
PHARMA               4.16         -5.57   38.80
AUTO                 3.61        -35.61   89.41
BANKS                3.10        -28.87  106.95
AC                   2.11        -12.88   43.48
HEALTHCARE           1.97        -35.50   70.86
DURABLES             1.94        -48.94   85.17
FOOTWEAR             1.85        -78.15  149.59
TRAVEL               1.81        -84.05  176.21
BREWERIES            1.75         -0.10   20.88
APPARELS             1.58        -26.58   69.75
REALTY               1.44        -15.03   33.93
CERAMICS             1.34        -70.65  122.49
REFINERIES           1.34        -11.71   39.97
MINING               1.31         13.92    1.29
CEMENT               1.26        -58.77  177.55
CABLES               1.21          9.02   89.16
JEWELLERY            1.12       -113.27  187.36
ENGINEERING          1.10        -64.30  139.44
CHEMICALS            0.93       -112.01  284.97
ENTERTAINMENT        0.77        -88.81  201.42
TEXTILES             0.42        -62.11  108.33
HOTELS               0.37       -131.56  213.23

In [29]:
# money to be made criteria-wise
df_portfolio_features.groupby('Criteria')['FTT Amt'].agg(['sum', 'count']).sort_values(by='sum', ascending=False)

                sum  count
Criteria
XY24      3955672.0     21
X40       1693389.0     15
XR        1390269.0     12
AR        1327025.0     10
X40N      1273672.0     10
OX40N      863637.0     10
XY25       447270.0      6
SR         317683.0      2

In [30]:
# money to be made conviction-wise
df_portfolio_features.groupby('Conviction')['FTT Amt'].agg(['sum', 'count']).sort_values(by='sum', ascending=False)

                  sum  count
Conviction
H-SC        3884057.0     24
X-MC        1672712.0     15
X-LC        1603889.0     12
X-SC        1560275.0     10
M-SC        1548865.0     14
H-MC         394179.0      3
L-SC         212480.0      2
M-LC         152838.0      1
M-MC         112006.0      2
H-LC          69086.0      1
L-MC          55975.0      1
L-LC           2255.0      1

In [31]:
# money to be made criteria and conviction-wise
df_portfolio_features.groupby(['Conviction', 'Criteria'])['FTT Amt'].agg(['sum', 'count']).sort_values(by='sum', ascending=False)

                           sum  count
Conviction Criteria
H-SC       XY24      1318987.0      6
           AR         973921.0      5
M-SC       XY24       912214.0      6
H-SC       XR         883667.0      7
X-SC       XY24       844301.0      4
X-LC       X40        830892.0      6
X-MC       X40        656286.0      7
           X40N       514131.0      4
X-SC       X40N       509763.0      4
H-SC       OX40N      389799.0      4
X-LC       XY24       378266.0      2
M-SC       OX40N      365920.0      5
H-SC       SR         317683.0      2
X-MC       XY24       261476.0      2
X-LC       X40N       249778.0      2
X-MC       XY25       240819.0      2
H-MC       XY24       240428.0      1
X-SC       X40        206211.0      2
M-SC       XR         193227.0      2
H-MC       AR         153751.0      2
M-LC       XR         152838.0      1
X-LC       XY25       144953.0      2
L-SC       OX40N      107918.0      1
           XR         104562.0      1
M-SC       AR          77504.0      1
H-LC       AR          69086.0      1
M-MC       XY25        59243.0      1
L-MC       XR          55975.0      1
M-MC       AR          52763.0      1
L-LC       XY25         2255.0      1

In [32]:
# notebook execution time

end_time = time.time()
execution_time = round(end_time - start_time, 0)
print(f"Notebook execution time: {execution_time} seconds")

Notebook execution time: 29.0 seconds