<a href="https://colab.research.google.com/github/ankit-rathi/Quantvesting_v2/blob/main/myStocks_Portfolio_Analysis.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
'''
!pip install pandas==2.2.2 -qq
!pip install pyxirr -qq
!pip install ta -qq
!pip install yfinance==0.2.59 -qq
'''

'\n!pip install pandas==2.2.2 -qq\n!pip install pyxirr -qq\n!pip install ta -qq\n!pip install yfinance==0.2.59 -qq\n'

In [2]:
# import libraries

import numpy as np
import pandas as pd
import datetime
import warnings
warnings.filterwarnings('ignore')
import yfinance as yfin
import ta
import matplotlib.pyplot as plt
import requests

In [3]:
# notebook start time
import time
import datetime
import pytz

start_time = time.time()

# function to print date timestamp
def print_date_time():
  tz_NY = pytz.timezone('Asia/Kolkata')
  datetime_NY = datetime.datetime.now(tz_NY)
  print("Run date time (IST):", datetime_NY.strftime("%Y-%m-%d %H:%M:%S"))

In [4]:
# function to get booked and reserved amount
def get_amt():
  # fetch the JSON data from the URL
  url = "https://raw.githubusercontent.com/ankit-rathi/Tradevesting_v1/main/data/myPortfolioAmts.json"
  response = requests.get(url)
  pf_amts = response.json()  # parse the JSON data

  # extract values from the JSON
  py_booked_amt_dm = pf_amts["py_booked_amt_dm"]
  py_booked_amt_sv = pf_amts["py_booked_amt_sv"]
  cy_booked_amt_dm = pf_amts["cy_booked_amt_dm"]
  cy_booked_amt_sv = pf_amts["cy_booked_amt_sv"]
  reserve_amt_dm = pf_amts["reserve_amt_dm"]
  reserve_amt_sv = pf_amts["reserve_amt_sv"]

  # perform calculations
  py_booked_amt = py_booked_amt_dm + py_booked_amt_sv
  cy_booked_amt = cy_booked_amt_dm + cy_booked_amt_sv
  reserve_amt = reserve_amt_dm + reserve_amt_sv
  total_booked_amt = py_booked_amt + cy_booked_amt

  return total_booked_amt, reserve_amt, cy_booked_amt, py_booked_amt

gen_output = 0

In [5]:
# function to format the amount
def format_amt(number):
    abs_number = abs(number)

    if abs_number >= 1_00_00_000:  # Crores
        formatted_amt = f"{number / 1_00_00_000:.2f} C"
    elif abs_number >= 1_00_000:  # Lakhs
        formatted_amt = f"{number / 1_00_000:.2f} L"
    elif abs_number >= 1_000:  # Thousands
        formatted_amt = f"{number / 1_000:.2f} K"
    else:
        formatted_amt = f"{number:.2f}"

    return formatted_amt

# function to set start and end date
def get_start_end_date():
  start_date = (datetime.date.today() + datetime.timedelta(days=-365)).strftime('%Y-%m-%d')
  end_date = (datetime.date.today() + datetime.timedelta(days=1)).strftime('%Y-%m-%d')
  return start_date, end_date

# function to fetch my portfolio csv
def get_mypfs_df():
  mypfs_df = pd.read_csv('https://raw.githubusercontent.com/ankit-rathi/Tradevesting_v1/main/data/myPortfolioStocks.csv')
  return mypfs_df

# function to fetch my prospects csv
def get_mypps_df():
  mypps_df = pd.read_csv('https://raw.githubusercontent.com/ankit-rathi/Tradevesting_v1/main/data/myProspectsScrips.csv')
  return mypps_df

# function to fetch screener data
def get_myscreen_df():
  myscreen_df = pd.read_csv('https://raw.githubusercontent.com/ankit-rathi/Tradevesting_v1/main/data/myScreenerDB.csv')
  return myscreen_df

# function to fetch momentum data
def get_myinvmt_df():
  myinvmt_df = pd.read_csv('https://raw.githubusercontent.com/ankit-rathi/Tradevesting_v1/main/data/myInvestments.csv')
  return myinvmt_df

# function to get the stock ids
def get_stock_ids(df_pf):
  stock_n100 = df_pf['Symbol'].unique()

  exclude = ['CADILAHC','MMTC', 'MASFIN']

  stock_ids = df_pf[~df_pf['Symbol'].isin(exclude) ]['Symbol'].unique()

  #mypf = mypf[mypf.Forecast.notnull()]
  #stock_ids = mypf['Symbol'].unique()

  #stock_ids.sort()
  return stock_ids

# get features from screener data
def get_screener_features():
  myscreen_df = get_myscreen_df()
  cols = ['Symbol', 'EPS', 'MedPE', 'ROCE%', 'ROE%', 'CapType']
  return myscreen_df[cols]

# get relative strength
def get_relative_strength(stock_list):

    # Dictionary to store stock tickers and their corresponding percentage price change
    stock_changes = {}

    # Loop through each stock and fetch its price data
    for stock in stock_list:
        try:
            # Download the stock data for the given date range
            stock_data = yfin.Ticker(stock + '.NS').history(period='1mo', interval='1d')[map(str.title, ['open', 'close', 'low', 'high', 'volume'])]

            # Calculate the percentage change for the stock
            if len(stock_data) > 0:
                start_price = stock_data['Close'].iloc[0]
                end_price = stock_data['Close'].iloc[-1]
                percent_change = round(((end_price - start_price) / start_price) * 100, 2)
                stock_changes[stock] = percent_change
            else:
                stock_changes[stock] = np.nan  # If no data is available, set to NaN

        except Exception as e:
            print(f"Error fetching data for {stock}: {e}")
            stock_changes[stock] = np.nan

    # Create a DataFrame with stock tickers and their percentage changes
    df = pd.DataFrame(list(stock_changes.items()), columns=['Symbol', 'Percent_Change'])

    # Drop any stocks with missing data (NaN values)
    df = df.dropna()

    # Calculate the percentile rank based on percentage change
    df['RSP'] = round(df['Percent_Change'].rank(pct=True) * 100, 2)
    cols = ['Symbol', 'RSP']
    df = df[cols]
    # Sort by percentile rank (optional)
    df = df.sort_values(by='RSP', ascending=False).reset_index(drop=True)

    return df

In [6]:
# function to get stock technicals
def stock_prec_dev(stock_symbol):
    #stock_symbol = 'ULTRACEMCO.NS'
    short_window = 20
    mid_window = 50
    long_window = 200
    moving_avg = 'SMA'

    start = datetime.datetime(*map(int, start_date.split('-')))
    end = datetime.datetime(*map(int, end_date.split('-')))

    stock_df = yfin.Ticker(stock_symbol + '.NS').history(period='max', interval='1d')[map(str.title, ['open', 'close', 'low', 'high', 'volume'])]

    stock_df['Max'] = round(max(stock_df['Close']),2)
    stock_df = stock_df[(stock_df.index <= end_date) & (stock_df.index >= start_date)]
    stock_df['200_SMA'] = round(stock_df['Close'].rolling(window = 200, min_periods = 1).mean(),0)
    stock_df['Dev%_200'] = round((stock_df['Close'] - stock_df['200_SMA'])*100/stock_df['200_SMA'],2)
    stock_df.dropna(axis = 0, inplace = True) # remove any null rows

    stock_df['20_SMA'] = stock_df['Close'].rolling(window=20).mean()
    stock_df['50_SMA'] = stock_df['Close'].rolling(window=50).mean()
    stock_df['Symbol'] = stock_symbol

    stock_df['Close'] = round(stock_df['Close'],2)
    stock_df['Min'] = round(min(stock_df['Close']),2)
    stock_df['RSI_14'] = ta.momentum.RSIIndicator(close=stock_df['Close'], window=14).rsi()
    stock_df['RSI_14'] = round(stock_df['RSI_14'],0)
    stock_df['Prev_Close'] = stock_df['Close'].shift(1)
    stock_df.drop(['Open', 'Low', 'High', 'Volume'], axis=1, inplace=True)
    stock_df = stock_df.tail(1)

    max_SMA = max(stock_df['20_SMA'].item(), stock_df['50_SMA'].item(), stock_df['200_SMA'].item())
    min_SMA = min(stock_df['20_SMA'].item(), stock_df['50_SMA'].item(), stock_df['200_SMA'].item())
    ABS_Spread = max_SMA - min_SMA
    stock_df['Spread%'] = round((ABS_Spread / stock_df['200_SMA'].item()) * 100,2)

    return stock_df

# function to compute stock attributes
def get_common_features(stock_ids, df_mypf):

  df_prec_dev = pd.DataFrame()
  df_tmp = get_screener_features()
  df_rs = get_relative_strength(stock_ids)

  for stock_id in stock_ids:
      tmp = stock_prec_dev(stock_id)
      tmp = tmp.reset_index()
      df_prec_dev = pd.concat([df_prec_dev, tmp], ignore_index = True)
  df_prec_dev = pd.merge(df_prec_dev, df_mypf, on= 'Symbol')
  df_prec_dev = pd.merge(df_prec_dev, df_tmp, on= 'Symbol', how='left')
  df_prec_dev = pd.merge(df_prec_dev, df_rs, on= 'Symbol', how='left')
  #print(df_prec_dev.columns)
  df_prec_dev['Curr_PE'] = round(df_prec_dev['Close']/df_prec_dev['EPS'],1)
  df_prec_dev['Dev%_PE'] = round((df_prec_dev['Curr_PE'] - df_prec_dev['MedPE'])*100/df_prec_dev['MedPE'],2)
  df_prec_dev['Conviction'] = df_prec_dev['Conviction'] + '-' + df_prec_dev['CapType']
  return df_prec_dev

# function to arrange stock features
def arrange_features(df_stocks, common_cols, diff_cols):
  df_stocks_common = df_stocks[common_cols].drop_duplicates()
  df_stocks_diff = df_stocks[diff_cols]
  df_stocks_diff['Investment'] = df_stocks_diff['AvgCost'] * df_stocks_diff['Shares']
  df_stocks_diff = df_stocks_diff.groupby(['Symbol'])[['Shares', 'Investment']].aggregate(['sum']).reset_index()
  df_stocks_diff.columns = ['Symbol', 'Shares', 'Investment']
  df_stocks_diff['AvgCost'] = round(df_stocks_diff['Investment']/df_stocks_diff['Shares'],2)
  df_stocks = pd.merge(df_stocks_diff, df_stocks_common, on='Symbol')
  return df_stocks

# plot fact distribution across dimension
def plot_pie_chart(df, dimension, fact):
  # grouping the data by category and calculating the sum of fact for each type
  grouped_data = df.groupby(dimension)[fact].sum()

  # sorting the grouped data in descending order
  grouped_data = grouped_data.sort_values(ascending=False)

  # creating a pie chart
  grouped_data.plot.pie(autopct='%1.1f%%', startangle=90, figsize=(6, 6))

  # adding a title and displaying the plot
  plt.title(f'{dimension} {fact} Distribution')
  plt.ylabel('')  # To hide the y-label
  plt.show()

In [7]:
# function to get portfolio features

def get_portfolio_features(df_common_features):

  print_date_time()
  print('-------------------')

  #df_common_features["Target"] = df_common_features["Target"].fillna(df_common_features["Max"])
  df_common_features['NTT'] = np.where(df_common_features['Strategy']== 'NTT', df_common_features["Target"], df_common_features['Max'])
  df_common_features['LTT'] = np.where(df_common_features['Strategy']== 'BTT', df_common_features["Target"], df_common_features['Max'])
  df_common_features['BOL'] = df_common_features['Min']

  tmp_df = df_common_features[df_common_features['Symbol'].isin(mypf_df[mypf_df['InPortfolio'] != 'NA'].Symbol.values)]
  print('qualified stocks: '+str(len(tmp_df['Symbol'].unique())))
  tmp_df1 = tmp_df[tmp_df['LatestQtr'] == 1]
  print('with latest results: '+str(len(tmp_df1['Symbol'].unique())))
  tmp_df1 = tmp_df1[tmp_df1['StarStock'] == 1]
  print('still star stocks: '+str(len(tmp_df1['Symbol'].unique())))
  tmp_df['Investment'] = tmp_df['AvgCost'] * tmp_df['Shares']
  tmp_df['Current'] = round(tmp_df['Close'] * tmp_df['Shares'],0)
  tmp_df['Previous'] = tmp_df['Prev_Close'] * tmp_df['Shares']
  tmp_df['EstimatedST'] = tmp_df['NTT'] * tmp_df['Shares']
  tmp_df['EstimatedLT'] = tmp_df['LTT'] * tmp_df['Shares']
  tmp_df['Current P/L'] = round((tmp_df['Current'] - tmp_df['Investment']),0)
  tmp_df['Today P/L%'] = round((tmp_df['Current'] - tmp_df['Previous'])*100/tmp_df['Previous'],2)
  tmp_df['Current P/L%'] = round((tmp_df['Current'] - tmp_df['Investment'])*100/tmp_df['Investment'],2)
  tmp_df['EstimatedST P/L%'] = round((tmp_df['EstimatedST'] - tmp_df['Investment'])*100/tmp_df['Investment'],2)
  tmp_df['EstimatedLT P/L%'] = round((tmp_df['EstimatedLT'] - tmp_df['Investment'])*100/tmp_df['Investment'],2)
  tmp_df['NTT%'] = round((tmp_df['NTT'] - tmp_df['Close'])*100/tmp_df['Close'],2)
  tmp_df['LTT%'] = round((tmp_df['LTT'] - tmp_df['Close'])*100/tmp_df['Close'],2)
  tmp_df['Gained%'] = round((tmp_df['Close'] - tmp_df['BOL'])*100/tmp_df['BOL'],2)
  investment = round(sum(tmp_df['AvgCost']*tmp_df['Shares']),0)
  current = round(sum(tmp_df['Close']*tmp_df['Shares']),0)
  tmp_df['InitAlloc%'] = round(tmp_df['Investment']*100/investment,2)
  tmp_df['CurrAlloc%'] = round(tmp_df['Current']*100/current,2)
  tmp_df['FTT'] = tmp_df['LTT']
  tmp_df.loc[tmp_df['Strategy'] == 'NTT', 'FTT'] = tmp_df['NTT']
  tmp_df['FTT%'] = tmp_df['LTT%']
  tmp_df.loc[tmp_df['Strategy'] == 'NTT', 'FTT%'] = tmp_df['NTT%']
  tmp_df['FTT Amt'] = round(tmp_df['FTT%'] * tmp_df['Current']/100,0)
  tmp_df['OTT%'] = round((tmp_df['FTT'] - tmp_df['AvgCost'])*100/tmp_df['AvgCost'],2)
  tmp_df['RRR Ind'] = round(tmp_df['Current P/L']/tmp_df['FTT Amt'],2)
  tmp_df['Risk Ind'] = round(tmp_df['Current P/L%']*tmp_df['CurrAlloc%'],0)

  return tmp_df

# function to print portfolio features
def print_portfolio_stats(df_portfolio_features, myinvmt_df):
  from pyxirr import xirr

  total_booked_amt, reserve_amt, cy_booked_amt, py_booked_amt = get_amt()

  dates = myinvmt_df['Date'].values
  dates = np.append(dates, datetime.date.today().strftime('%d-%b-%y'))
  investment = myinvmt_df['Investment'].values
  dates= pd.to_datetime(dates)

  current = round(sum(df_portfolio_features['Close']*df_portfolio_features['Shares']),0) + reserve_amt
  investment_xirr = np.append(investment, current)
  cagr = round(xirr(pd.DataFrame({"dates": dates, "amounts": investment_xirr}))*100,2)

  investment = -sum(investment)
  invested = round(sum(df_portfolio_features['AvgCost']*df_portfolio_features['Shares']),0) + reserve_amt
  previous = round(sum(df_portfolio_features['Prev_Close']*df_portfolio_features['Shares']),0) + reserve_amt
  cy_invested = investment + py_booked_amt

  today_pnl_amount = current-previous
  today_pnl_percentage = round((current-previous)*100/previous,2)

  curr_pnl_amount = current-invested
  curr_pnl_percentage = round((curr_pnl_amount)*100/(cy_invested),2)

  cy_pnl_amount = cy_booked_amt + curr_pnl_amount
  cy_pnl_percentage = round((cy_pnl_amount)*100/cy_invested,2)

  overall_pnl_amount = total_booked_amt + curr_pnl_amount
  overall_pnl_percentage = round((overall_pnl_amount)*100/investment,2)

  estimate_st = round(sum(df_portfolio_features['FTT']*df_portfolio_features['Shares']),0)  + reserve_amt
  est_st_pnl_amount = estimate_st-current
  est_st_pnl_percentage = round((est_st_pnl_amount)*100/current,2)

  estimate_lt = round(sum(df_portfolio_features['LTT']*df_portfolio_features['Shares']),0)  + reserve_amt
  est_lt_pnl_amount = estimate_lt-current
  est_lt_pnl_percentage = round((est_lt_pnl_amount)*100/current,2)

  total_profit = round(sum(df_portfolio_features[df_portfolio_features['Current P/L%'] > 0]['Current']) - sum(df_portfolio_features[df_portfolio_features['Current P/L%'] > 0]['Investment']),0)
  total_loss = round(sum(df_portfolio_features[df_portfolio_features['Current P/L%'] < 0]['Current']) - sum(df_portfolio_features[df_portfolio_features['Current P/L%'] < 0]['Investment']),0)

  cy_booked_percentage = round((cy_booked_amt)*100/current,2)
  py_booked_percentage = round((py_booked_amt)*100/investment,2)
  total_booked_percentage = round((total_booked_amt)*100/investment,2)

  print('-------------------')
  print('Initial Investment: ', format_amt(investment))
  print('CY Investment: ', format_amt(cy_invested))
  print('Reserve: ', format_amt(reserve_amt))
  print('Current: ',  format_amt(current))
  print('-------------------')
  print('Today PnL: '+ '{} ({}%)'.format(format_amt(today_pnl_amount), today_pnl_percentage))
  print('Current PnL: '+ '{} ({}%)'.format(format_amt(curr_pnl_amount), curr_pnl_percentage))
  print('CY Booked + Current PnL: '+ '{} ({}%)'.format(format_amt(cy_pnl_amount), cy_pnl_percentage))
  print('-------------------')
  print('Total profit: ', format_amt(total_profit))
  print('Total loss: ', format_amt(total_loss))
  print('-------------------')
  print('Total Booked + Current PnL: '+ '{} ({}%)'.format(format_amt(overall_pnl_amount), overall_pnl_percentage))
  print('Total Booked PnL: '+ '{} ({}%)'.format(format_amt(total_booked_amt), total_booked_percentage))
  print('Curr Year Booked PnL: '+ '{} ({}%)'.format(format_amt(cy_booked_amt), cy_booked_percentage))
  print('Prev Year Booked PnL: '+ '{} ({}%)'.format(format_amt(py_booked_amt), py_booked_percentage))
  print('===================')
  print('Est FTT: ',  format_amt(estimate_st))
  print('Est FTT PnL: '+ '{} ({}%)'.format(format_amt(est_st_pnl_amount), est_st_pnl_percentage))

  print('===================')
  print('Deployed: ', format_amt(investment))

  print('Current: ', format_amt(current))

  print('CAGR/XIRR %: '+'{}%'.format(cagr))

In [8]:
# get start and end date
start_date, end_date = get_start_end_date()

# get portfolio and prospects data
mypfs_df = get_mypfs_df()
mypps_df = get_mypps_df()
myinvmt_df = get_myinvmt_df()

# merge above datasets
mypf_df = pd.merge(mypfs_df, mypps_df, on="Symbol")

# seggregate dm and sv portfolio
dm_pf = mypf_df[mypf_df['InPortfolio'] == 'DM']
sv_pf = mypf_df[mypf_df['InPortfolio'] == 'SV']

# build portfolio stock dataframe
dm_stocks = get_stock_ids(dm_pf)
sv_stocks = get_stock_ids(sv_pf)
df_stocks = pd.concat([dm_pf,sv_pf], ignore_index = True)

# arrange common and diff stock features
common_cols = ['Symbol', 'Target', 'Criteria', 'Strategy', 'CumlRnk', 'LatestQtr', 'StarStock', 'Conviction', 'Category', 'InFolio', 'XIRR', 'MBQ']
diff_cols = ['Symbol', 'AvgCost', 'Shares']
df_stocks = arrange_features(df_stocks, common_cols, diff_cols)

# get common features
stock_ids = df_stocks['Symbol'].values
df_common_features = get_common_features(stock_ids, df_stocks)

df_common_features.reset_index(drop=True, inplace=True)
df_common_features.drop(['Date'], axis=1, inplace=True)
# get and print portfolio features
df_portfolio_features = get_portfolio_features(df_common_features)

print_portfolio_stats(df_portfolio_features, myinvmt_df)

df = df_portfolio_features
#plot_pie_chart(df, 'CapType', 'Current')
list_ox40n = list(df[df['MBQ'].str.contains('OX40N', na=False)]['Symbol'].values)

Run date time (IST): 2026-03-24 16:06:03
-------------------
qualified stocks: 86
with latest results: 26
still star stocks: 16
-------------------
Initial Investment:  1.36 C
CY Investment:  1.62 C
Reserve:  1.61 K
Current:  1.29 C
-------------------
Today PnL: 2.42 L (1.91%)
Current PnL: -48.00 L (-29.54%)
CY Booked + Current PnL: -32.11 L (-19.76%)
-------------------
Total profit:  42.54 K
Total loss:  -48.42 L
-------------------
Total Booked + Current PnL: -5.13 L (-3.78%)
Total Booked PnL: 42.87 L (31.64%)
Curr Year Booked PnL: 15.89 L (12.31%)
Prev Year Booked PnL: 26.98 L (19.91%)
===================
Est FTT:  2.48 C
Est FTT PnL: 1.19 C (91.97%)
===================
Deployed:  1.36 C
Current:  1.29 C
CAGR/XIRR %: -2.36%

In [9]:
# top 5 near their targets
cols = ['Symbol', 'Today P/L%', 'Current P/L%', 'FTT%', 'OTT%', 'FTT Amt', 'Current P/L', 'Current', 'FTT', 'Dev%_PE', 'RSI_14','Conviction', 'Spread%',  'CumlRnk', 'RRR Ind', 'CurrAlloc%', 'Gained%', 'Criteria', 'Strategy', 'Category']
df_tmp = df_portfolio_features[~df_portfolio_features['Symbol'].isin(['ENRIN','BLUSPRING','DIGITIDE'])]
df_tmp = df_tmp.sort_values(by = 'FTT Amt', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
50,MASFIN,1.57,-8.79,33.28,21.57,29742.0,-8610.0,89370.0,397.04,-21.41,42.0,H-SC,2.35,167.0,-0.29,0.69,21.90,XR,ATH,FINANCE
77,TTKPRESTIG,-3.92,-42.99,75.58,0.09,43421.0,-43327.0,57450.0,770.00,33.40,34.0,M-SC,19.19,250.0,-1.00,0.44,0.00,OX40N,NTT,DURABLES
2,ABBOTINDIA,5.16,-10.09,31.32,18.07,50363.0,-18055.0,160800.0,35195.00,-23.42,50.0,X-MC,10.60,58.0,-0.36,1.25,5.16,X40,ATH,PHARMA
67,SONACOMS,2.01,-14.42,62.53,39.09,54133.0,-14587.0,86572.0,804.02,-32.22,45.0,M-MC,7.46,193.0,-0.27,0.67,22.47,AR,ATH,AUTO
78,UNITDSPR,4.14,-2.45,23.80,20.77,54363.0,-5728.0,228416.0,1644.00,-13.41,47.0,X-MC,1.62,64.0,-0.11,1.77,4.14,X40N,NTT,BREWERIES

In [10]:
# top 5 today
df_tmp = df_portfolio_features.sort_values(by = 'Today P/L%', ascending=False)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
4,ALKYLAMINE,14.14,-39.75,221.37,93.63,134664.0,-40131.0,60832.0,4546.37,-35.55,53.0,H-SC,25.72,142.0,-0.30,0.47,14.14,SR,ATH,CHEMICALS
60,REPCOHOME,6.70,-22.53,145.02,89.82,321879.0,-64550.0,221955.0,880.00,-61.25,44.0,H-SC,7.84,161.0,-0.20,1.72,9.60,XY24,NTT,FINANCE
66,SIS,6.56,-35.45,87.87,21.26,62975.0,-39364.0,71668.0,528.00,1675.65,43.0,H-SC,14.21,168.0,-0.63,0.56,6.56,OX40N,NTT,MISC
7,ATULAUTO,5.48,-28.85,104.58,45.57,146691.0,-56865.0,140267.0,844.00,3024.32,42.0,M-SC,4.41,248.0,-0.39,1.09,6.15,XY24,NTT,AUTO
2,ABBOTINDIA,5.16,-10.09,31.32,18.07,50363.0,-18055.0,160800.0,35195.00,-23.42,50.0,X-MC,10.60,58.0,-0.36,1.25,5.16,X40,ATH,PHARMA

In [11]:
# bottom 5 today
df_tmp = df_portfolio_features.sort_values(by = 'Today P/L%', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
55,RAJESHEXPO,-4.99,-83.61,510.49,0.07,114784.0,-114692.0,22485.0,518.0,724.49,14.0,L-SC,34.55,268.0,-1.00,0.17,0.00,OX40N,NTT,JEWELLERY
77,TTKPRESTIG,-3.92,-42.99,75.58,0.09,43421.0,-43327.0,57450.0,770.0,33.40,34.0,M-SC,19.19,250.0,-1.00,0.44,0.00,OX40N,NTT,DURABLES
80,VALIANTORG,-2.26,-50.95,255.04,74.15,204670.0,-83355.0,80250.0,838.0,-244.10,51.0,H-SC,28.24,145.0,-0.41,0.62,19.42,XR,NTT,CHEMICALS
0,5PAISA,-1.93,-47.87,116.58,12.90,132786.0,-104595.0,113901.0,593.0,68.27,30.0,H-SC,13.74,170.0,-0.79,0.88,0.00,OX40N,NTT,FINANCE
14,BOSCH-HCIL,-1.86,-46.96,88.52,-0.01,60006.0,-60017.0,67788.0,2282.0,13769.57,31.0,M-SC,4.68,231.0,-1.00,0.53,0.00,OX40N,BTT,AC

In [12]:
# top 5 to exit based on CumlRnk
df_tmp = df_portfolio_features[~df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])]
df_tmp = df_tmp[(df_tmp['Current P/L%'] > -1) & (df_tmp['Current P/L%'] < 1)].sort_values(by = 'CumlRnk', ascending=False)
df_tmp[cols].head()

Empty DataFrame
Columns: [Symbol, Today P/L%, Current P/L%, FTT%, OTT%, FTT Amt, Current P/L, Current, FTT, Dev%_PE, RSI_14, Conviction, Spread%, CumlRnk, RRR Ind, CurrAlloc%, Gained%, Criteria, Strategy, Category]
Index: []

In [13]:
# OX40N stocks to exit
df_tmp = df_portfolio_features[(df_portfolio_features['Symbol'].isin(list_ox40n))].sort_values(by = 'Current P/L%', ascending=False)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
26,FINCABLES,0.82,3.26,101.36,107.91,154525.0,4808.0,152452.0,1641.55,-7.15,44.0,M-SC,8.18,220.0,0.03,1.18,14.69,OX40N,ATH,CABLES
66,SIS,6.56,-35.45,87.87,21.26,62975.0,-39364.0,71668.0,528.00,1675.65,43.0,H-SC,14.21,168.0,-0.63,0.56,6.56,OX40N,NTT,MISC
18,CERA,2.57,-38.54,101.56,23.89,109805.0,-67785.0,108118.0,9475.00,-40.81,46.0,H-SC,18.96,153.0,-0.62,0.84,3.90,OX40N,NTT,CERAMICS
72,TATAELXSI,1.20,-39.75,119.15,32.03,94634.0,-52411.0,79424.0,9161.00,-24.56,37.0,H-SC,20.95,158.0,-0.55,0.62,3.49,OX40N,NTT,IT
77,TTKPRESTIG,-3.92,-42.99,75.58,0.09,43421.0,-43327.0,57450.0,770.00,33.40,34.0,M-SC,19.19,250.0,-1.00,0.44,0.00,OX40N,NTT,DURABLES

In [14]:
# top 5 to book for rotation
df_tmp = df_portfolio_features[(df_portfolio_features['Current P/L%'] > 20) ].sort_values(by = 'CumlRnk', ascending=False)
df_tmp[cols].head()

Empty DataFrame
Columns: [Symbol, Today P/L%, Current P/L%, FTT%, OTT%, FTT Amt, Current P/L, Current, FTT, Dev%_PE, RSI_14, Conviction, Spread%, CumlRnk, RRR Ind, CurrAlloc%, Gained%, Criteria, Strategy, Category]
Index: []

In [15]:
# top 5 to monitor for exit
df_tmp = df_portfolio_features[~df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])]
df_tmp = df_tmp[(df_tmp['Current P/L%'] > 0) ].sort_values(by = 'Dev%_PE', ascending=False)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
26,FINCABLES,0.82,3.26,101.36,107.91,154525.0,4808.0,152452.0,1641.55,-7.15,44.0,M-SC,8.18,220.0,0.03,1.18,14.69,OX40N,ATH,CABLES
1,ABB,1.99,13.06,28.76,45.57,85065.0,34157.0,295776.0,7934.00,-27.37,54.0,H-MC,13.29,125.0,0.40,2.29,31.34,AR,NTT,ELECTRICAL

In [16]:
# top 5 to book for rotation from weak conviction
df_tmp = df_portfolio_features[~df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])]
df_tmp = df_tmp[~df_tmp['Criteria'].isin(['XY25','XY24','X40', 'X40N'])].sort_values(by = 'RRR Ind', ascending=False)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
1,ABB,1.99,13.06,28.76,45.57,85065.0,34157.0,295776.0,7934.00,-27.37,54.0,H-MC,13.29,125.0,0.40,2.29,31.34,AR,NTT,ELECTRICAL
26,FINCABLES,0.82,3.26,101.36,107.91,154525.0,4808.0,152452.0,1641.55,-7.15,44.0,M-SC,8.18,220.0,0.03,1.18,14.69,OX40N,ATH,CABLES
40,INDIAMART,-0.33,-15.61,144.95,106.72,150874.0,-19249.0,104087.0,4810.62,-61.91,30.0,H-SC,11.65,140.0,-0.13,0.81,4.12,AR,ATH,MISC
85,ZYDUSLIFE,3.00,-6.53,45.10,35.63,88348.0,-13680.0,195894.0,1286.17,-18.47,46.0,H-MC,5.41,120.0,-0.15,1.52,9.06,AR,ATH,PHARMA
84,WIPRO,0.64,-22.59,122.53,72.27,160728.0,-38274.0,131174.0,420.00,-30.18,31.0,M-LC,17.83,98.0,-0.24,1.02,0.64,XR,NTT,IT

In [17]:
# top 5 to accumulate based on lowest RSI_14
df_tmp = df_portfolio_features[df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])].sort_values(by = 'RSI_14', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
53,PGHH,0.42,-28.84,85.52,32.01,129936.0,-61584.0,151936.0,17616.87,-51.83,14.0,X-MC,15.85,57.0,-0.47,1.18,0.42,X40,ATH,FMCG
58,RELAXO,1.43,-66.52,354.93,52.31,172489.0,-96562.0,48598.0,1176.00,-64.38,20.0,X-SC,26.57,92.0,-0.56,0.38,1.43,X40N,NTT,FOOTWEAR
38,ICICIPRULI,1.18,-11.06,46.98,30.73,82321.0,-21780.0,175225.0,790.00,-34.90,22.0,X-MC,4.43,78.0,-0.26,1.36,1.18,X40,ATH,INSURANCE
12,BATAINDIA,2.28,-58.71,227.47,35.20,120841.0,-75546.0,53124.0,2096.00,-30.40,24.0,X-SC,31.21,91.0,-0.63,0.41,2.29,X40,NTT,FOOTWEAR
51,MEDANTA,0.43,-16.70,52.60,27.12,77345.0,-29473.0,147044.0,1486.00,-19.31,25.0,X-SC,12.31,87.0,-0.38,1.14,0.43,XY24,NTT,HEALTHCARE

In [18]:
# top 5 to accumulate based on Spread and CumlRnk
df_tmp = df_portfolio_features[df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])]
df_tmp = df_tmp[(df_tmp['CumlRnk'] < 100)].sort_values(by = 'Spread%', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
78,UNITDSPR,4.14,-2.45,23.80,20.77,54363.0,-5728.0,228416.0,1644.00,-13.41,47.0,X-MC,1.62,64.0,-0.11,1.77,4.14,X40N,NTT,BREWERIES
65,SIEMENS,0.45,-19.35,55.62,25.51,83480.0,-36005.0,150090.0,4671.50,26.07,40.0,H-LC,2.79,51.0,-0.43,1.16,10.53,AR,ATH,ELECTRICAL
59,RELIANCE,0.28,-9.38,38.26,25.30,69680.0,-18841.0,182122.0,1952.00,-11.57,51.0,X-LC,3.45,21.0,-0.27,1.41,21.60,XY25,BTT,REFINERIES
37,ICICIGI,0.46,-8.35,30.22,19.34,55421.0,-16718.0,183391.0,2252.93,-23.02,27.0,X-MC,3.73,66.0,-0.30,1.42,1.38,X40,ATH,INSURANCE
82,VOLTAS,4.07,1.86,42.54,45.20,83087.0,3573.0,195315.0,1856.00,16.67,35.0,X-MC,3.99,79.0,0.04,1.51,8.79,XY25,NTT,AC

In [19]:
# top 5 to accumulate based on lowest Gained%
df_tmp = df_portfolio_features[df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])].sort_values(by = 'Gained%', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
32,HAVELLS,0.26,-20.98,67.14,32.08,174015.0,-68809.0,259182.0,2062.85,-25.66,32.0,X-MC,8.60,63.0,-0.40,2.01,0.26,X40,ATH,ELECTRICAL
45,ITC,0.28,-23.28,55.19,19.06,144024.0,-79206.0,260960.0,452.00,-57.95,30.0,X-LC,18.66,1.0,-0.55,2.02,0.28,X40,NTT,FMCG
9,BAJAJHFL,0.31,-29.66,130.48,62.13,250614.0,-80975.0,192071.0,181.50,-42.15,26.0,X-MC,20.42,60.0,-0.32,1.49,0.31,X40N,ATH,FINANCE
3,ACC,0.34,-40.28,192.74,74.81,308608.0,-108012.0,160116.0,3906.00,-57.46,25.0,X-SC,17.76,85.0,-0.35,1.24,0.34,XY24,BTT,CEMENT
53,PGHH,0.42,-28.84,85.52,32.01,129936.0,-61584.0,151936.0,17616.87,-51.83,14.0,X-MC,15.85,57.0,-0.47,1.18,0.42,X40,ATH,FMCG

In [20]:
# top 5 to accumulate based on lowest CurrAlloc%
df_tmp = df_portfolio_features[df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])].sort_values(by = 'CurrAlloc%', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
58,RELAXO,1.43,-66.52,354.93,52.31,172489.0,-96562.0,48598.0,1176.00,-64.38,20.0,X-SC,26.57,92.0,-0.56,0.38,1.43,X40N,NTT,FOOTWEAR
12,BATAINDIA,2.28,-58.71,227.47,35.20,120841.0,-75546.0,53124.0,2096.00,-30.40,24.0,X-SC,31.21,91.0,-0.63,0.41,2.29,X40,NTT,FOOTWEAR
54,QUESS,3.29,-28.04,141.65,73.90,108859.0,-29942.0,76851.0,424.00,-61.43,38.0,X-SC,21.46,80.0,-0.28,0.60,3.29,XY24,NTT,MISC
36,HONAUT,1.56,-28.33,111.13,51.31,153582.0,-54638.0,138200.0,58357.33,-40.38,27.0,X-SC,15.84,90.0,-0.36,1.07,1.56,X40N,ATH,ELECTRICAL
51,MEDANTA,0.43,-16.70,52.60,27.12,77345.0,-29473.0,147044.0,1486.00,-19.31,25.0,X-SC,12.31,87.0,-0.38,1.14,0.43,XY24,NTT,HEALTHCARE

In [21]:
# top 5 to accumulate based on CumlRnk
df_tmp = df_portfolio_features.sort_values(by = 'CumlRnk', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
45,ITC,0.28,-23.28,55.19,19.06,144024.0,-79206.0,260960.0,452.00,-57.95,30.0,X-LC,18.66,1.0,-0.55,2.02,0.28,X40,NTT,FMCG
73,TCS,0.63,-29.58,79.74,26.57,260141.0,-137036.0,326237.0,4311.58,-40.35,30.0,X-LC,17.38,2.0,-0.53,2.53,1.82,X40,ATH,IT
43,INFY,1.71,-12.98,54.27,34.24,147765.0,-40610.0,272278.0,1972.00,-31.42,42.0,X-LC,15.19,3.0,-0.27,2.11,4.71,X40,NTT,IT
75,TMPV,1.95,-29.16,92.80,36.58,233923.0,-103769.0,252072.0,600.00,-85.81,35.0,X-LC,6.70,4.0,-0.44,1.95,1.95,XY24,NTT,AUTO
33,HCLTECH,1.08,-10.88,38.95,23.83,83979.0,-26316.0,215608.0,1908.19,-6.53,45.0,X-LC,11.84,8.0,-0.31,1.67,4.69,X40,ATH,IT

In [22]:
# top 5 for average up
df_tmp = df_portfolio_features[(df_portfolio_features['Dev%_200'] > 5)].sort_values(by = 'CurrAlloc%', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
1,ABB,1.99,13.06,28.76,45.57,85065.0,34157.0,295776.0,7934.0,-27.37,54.0,H-MC,13.29,125.0,0.4,2.29,31.34,AR,NTT,ELECTRICAL

In [23]:
# top 5 RSP
df_tmp = df_portfolio_features.sort_values(by = 'RSP', ascending=False)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
30,HAPPSTMNDS,1.72,-50.14,270.73,84.85,173007.0,-64261.0,63904.0,1480.71,-40.67,55.0,H-SC,26.63,152.0,-0.37,0.49,18.34,AR,ATH,IT
69,SURYODAY,0.13,-28.50,72.07,23.03,92279.0,-51030.0,128041.0,216.00,40.35,46.0,H-SC,6.34,166.0,-0.55,0.99,25.14,XR,NTT,BANKS
33,HCLTECH,1.08,-10.88,38.95,23.83,83979.0,-26316.0,215608.0,1908.19,-6.53,45.0,X-LC,11.84,8.0,-0.31,1.67,4.69,X40,ATH,IT
1,ABB,1.99,13.06,28.76,45.57,85065.0,34157.0,295776.0,7934.00,-27.37,54.0,H-MC,13.29,125.0,0.40,2.29,31.34,AR,NTT,ELECTRICAL
2,ABBOTINDIA,5.16,-10.09,31.32,18.07,50363.0,-18055.0,160800.0,35195.00,-23.42,50.0,X-MC,10.60,58.0,-0.36,1.25,5.16,X40,ATH,PHARMA

In [24]:
# Top N allocation
df_tmp = df_portfolio_features.sort_values(by = 'CurrAlloc%', ascending=False)
top_n_values = [10, 25, 50]

sum_df = pd.DataFrame({
    'Top_N': top_n_values,
    'Sum_Alloc%': [df_tmp['CurrAlloc%'].head(n).sum() for n in top_n_values]
})

sum_df

   Top_N  Sum_Alloc%
0     10       20.78
1     25       45.92
2     50       78.19

In [25]:
# market-cap-wise allocation
df_tmp = df_portfolio_features[cols]
df_tmp.groupby(df_tmp['Conviction'].str[-2:])['CurrAlloc%'].sum().sort_values(ascending=False)

Conviction
SC    44.24
MC    30.19
LC    25.57
Name: CurrAlloc%, dtype: float64

In [26]:
# criteria-wise allocation
df_portfolio_features.groupby('Criteria')['CurrAlloc%'].sum().sort_values(ascending=False)

Criteria
XY24     26.91
X40      25.57
X40N     15.22
AR        9.16
XR        8.31
XY25      7.35
OX40N     6.65
SR        0.83
Name: CurrAlloc%, dtype: float64

In [27]:
# conviction-wise allocation
df_portfolio_features.groupby('Conviction')['CurrAlloc%'].sum().sort_values(ascending=False)

Conviction
X-LC    23.39
X-MC    22.69
H-SC    21.58
X-SC    12.21
M-SC     9.94
H-MC     5.11
M-MC     2.04
H-LC     1.16
M-LC     1.02
L-SC     0.51
L-MC     0.35
Name: CurrAlloc%, dtype: float64

In [28]:
# sector-wise stats
df_tmp = df_portfolio_features.groupby('Category')[['CurrAlloc%', 'Current', 'Current P/L', 'FTT Amt']].sum().sort_values(by=['Current', 'Current P/L'], ascending=False)
df_tmp['Current P/L%'] = round(df_tmp['Current P/L'] * 100 / df_tmp['Current'], 2)
df_tmp['FTT%'] = round(df_tmp['FTT Amt'] * 100 / df_tmp['Current'], 2)
cols = ['CurrAlloc%', 'Current P/L%', 'FTT%']
df_tmp[cols].sort_values(by=['CurrAlloc%'], ascending=False)

               CurrAlloc%  Current P/L%    FTT%
Category
FMCG                15.02        -28.79   74.52
FINANCE             13.08        -27.22   79.07
IT                  11.95        -46.05  120.37
MISC                 6.94        -49.85  114.95
ELECTRICAL           6.53        -14.86   58.84
PAINTS               5.09        -49.67   75.66
INSURANCE            4.70        -11.84   50.12
BANKS                4.56        -30.59   96.88
PHARMA               4.20         -8.55   42.72
AUTO                 3.71        -36.59   90.78
AC                   2.04        -21.45   54.39
HEALTHCARE           1.87        -48.25   86.94
TRAVEL               1.80        -92.29  188.57
BREWERIES            1.77         -2.51   23.80
FOOTWEAR             1.77        -93.89  171.64
DURABLES             1.74        -71.29  112.96
APPARELS             1.74        -19.18   59.83
REALTY               1.48        -16.36   35.47
REFINERIES           1.41        -10.35   38.26
CERAMICS             1.39        -71.22  123.24
CEMENT               1.24        -67.46  192.74
CABLES               1.18          3.15  101.36
ENGINEERING          1.09        -72.35  151.18
CHEMICALS            1.09        -87.53  240.52
JEWELLERY            1.03       -140.11  223.52
ENTERTAINMENT        0.75        -99.41  218.35
TEXTILES             0.49        -46.99   88.90
HOTELS               0.34       -156.68  247.22

In [29]:
# money to be made criteria-wise
df_portfolio_features.groupby('Criteria')['FTT Amt'].agg(['sum', 'count']).sort_values(by='sum', ascending=False)

                sum  count
Criteria
XY24      4122957.0     21
X40       1874017.0     16
XR        1418477.0     12
AR        1387262.0     10
X40N      1337338.0     10
OX40N      933241.0     10
XY25       490276.0      5
SR         311939.0      2

In [30]:
# money to be made conviction-wise
df_portfolio_features.groupby('Conviction')['FTT Amt'].agg(['sum', 'count']).sort_values(by='sum', ascending=False)

                  sum  count
Conviction
H-SC        4006183.0     24
X-MC        1804917.0     15
X-LC        1755117.0     13
M-SC        1634759.0     14
X-SC        1606845.0     10
H-MC         419175.0      3
L-SC         224147.0      2
M-LC         160728.0      1
M-MC         122998.0      2
H-LC          83480.0      1
L-MC          57158.0      1

In [31]:
# money to be made criteria and conviction-wise
df_portfolio_features.groupby(['Conviction', 'Criteria'])['FTT Amt'].agg(['sum', 'count']).sort_values(by='sum', ascending=False)

                           sum  count
Conviction Criteria
H-SC       XY24      1397583.0      6
           AR         996410.0      5
M-SC       XY24       945499.0      6
X-LC       X40        936226.0      7
H-SC       XR         900051.0      7
X-SC       XY24       868887.0      4
X-MC       X40        719354.0      7
           X40N       538981.0      4
X-SC       X40N       519521.0      4
M-SC       OX40N      418257.0      5
H-SC       OX40N      400200.0      4
X-LC       XY24       386683.0      2
H-SC       SR         311939.0      2
X-LC       X40N       278836.0      2
X-MC       XY24       278543.0      2
           XY25       268039.0      2
H-MC       XY24       245762.0      1
X-SC       X40        218437.0      2
M-SC       XR         191177.0      2
H-MC       AR         173413.0      2
M-LC       XR         160728.0      1
X-LC       XY25       153372.0      2
L-SC       OX40N      114784.0      1
           XR         109363.0      1
H-LC       AR          83480.0      1
M-SC       AR          79826.0      1
M-MC       XY25        68865.0      1
L-MC       XR          57158.0      1
M-MC       AR          54133.0      1

In [32]:
# notebook execution time

end_time = time.time()
execution_time = round(end_time - start_time, 0)
print(f"Notebook execution time: {execution_time} seconds")

Notebook execution time: 27.0 seconds