<a href="https://colab.research.google.com/github/ankit-rathi/Quantvesting_v2/blob/main/myStocks_Portfolio_Analysis.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
'''
!pip install pandas==2.2.2 -qq
!pip install pyxirr -qq
!pip install ta -qq
!pip install yfinance==0.2.59 -qq
'''

'\n!pip install pandas==2.2.2 -qq\n!pip install pyxirr -qq\n!pip install ta -qq\n!pip install yfinance==0.2.59 -qq\n'

In [2]:
# import libraries

import numpy as np
import pandas as pd
import datetime
import warnings
warnings.filterwarnings('ignore')
import yfinance as yfin
import ta
import matplotlib.pyplot as plt
import requests

In [3]:
# notebook start time
import time
import datetime
import pytz

start_time = time.time()

# function to print date timestamp
def print_date_time():
  tz_NY = pytz.timezone('Asia/Kolkata')
  datetime_NY = datetime.datetime.now(tz_NY)
  print("Run date time (IST):", datetime_NY.strftime("%Y-%m-%d %H:%M:%S"))

In [4]:
# function to get booked and reserved amount
def get_amt():
  # fetch the JSON data from the URL
  url = "https://raw.githubusercontent.com/ankit-rathi/Tradevesting_v1/main/data/myPortfolioAmts.json"
  response = requests.get(url)
  pf_amts = response.json()  # parse the JSON data

  # extract values from the JSON
  py_booked_amt_dm = pf_amts["py_booked_amt_dm"]
  py_booked_amt_sv = pf_amts["py_booked_amt_sv"]
  cy_booked_amt_dm = pf_amts["cy_booked_amt_dm"]
  cy_booked_amt_sv = pf_amts["cy_booked_amt_sv"]
  reserve_amt_dm = pf_amts["reserve_amt_dm"]
  reserve_amt_sv = pf_amts["reserve_amt_sv"]

  # perform calculations
  py_booked_amt = py_booked_amt_dm + py_booked_amt_sv
  cy_booked_amt = cy_booked_amt_dm + cy_booked_amt_sv
  reserve_amt = reserve_amt_dm + reserve_amt_sv
  total_booked_amt = py_booked_amt + cy_booked_amt

  return total_booked_amt, reserve_amt, cy_booked_amt, py_booked_amt

gen_output = 0

In [5]:
# function to format the amount
def format_amt(number):
    abs_number = abs(number)

    if abs_number >= 1_00_00_000:  # Crores
        formatted_amt = f"{number / 1_00_00_000:.2f} C"
    elif abs_number >= 1_00_000:  # Lakhs
        formatted_amt = f"{number / 1_00_000:.2f} L"
    elif abs_number >= 1_000:  # Thousands
        formatted_amt = f"{number / 1_000:.2f} K"
    else:
        formatted_amt = f"{number:.2f}"

    return formatted_amt

# function to set start and end date
def get_start_end_date():
  start_date = (datetime.date.today() + datetime.timedelta(days=-365)).strftime('%Y-%m-%d')
  end_date = (datetime.date.today() + datetime.timedelta(days=1)).strftime('%Y-%m-%d')
  return start_date, end_date

# function to fetch my portfolio csv
def get_mypfs_df():
  mypfs_df = pd.read_csv('https://raw.githubusercontent.com/ankit-rathi/Tradevesting_v1/main/data/myPortfolioStocks.csv')
  return mypfs_df

# function to fetch my prospects csv
def get_mypps_df():
  mypps_df = pd.read_csv('https://raw.githubusercontent.com/ankit-rathi/Tradevesting_v1/main/data/myProspectsScrips.csv')
  return mypps_df

# function to fetch screener data
def get_myscreen_df():
  myscreen_df = pd.read_csv('https://raw.githubusercontent.com/ankit-rathi/Tradevesting_v1/main/data/myScreenerDB.csv')
  return myscreen_df

# function to fetch momentum data
def get_myinvmt_df():
  myinvmt_df = pd.read_csv('https://raw.githubusercontent.com/ankit-rathi/Tradevesting_v1/main/data/myInvestments.csv')
  return myinvmt_df

# function to get the stock ids
def get_stock_ids(df_pf):
  stock_n100 = df_pf['Symbol'].unique()

  exclude = ['CADILAHC','MMTC', 'MASFIN']

  stock_ids = df_pf[~df_pf['Symbol'].isin(exclude) ]['Symbol'].unique()

  #mypf = mypf[mypf.Forecast.notnull()]
  #stock_ids = mypf['Symbol'].unique()

  #stock_ids.sort()
  return stock_ids

# get features from screener data
def get_screener_features():
  myscreen_df = get_myscreen_df()
  cols = ['Symbol', 'EPS', 'MedPE', 'ROCE%', 'ROE%', 'CapType']
  return myscreen_df[cols]

# get relative strength
def get_relative_strength(stock_list):

    # Dictionary to store stock tickers and their corresponding percentage price change
    stock_changes = {}

    # Loop through each stock and fetch its price data
    for stock in stock_list:
        try:
            # Download the stock data for the given date range
            stock_data = yfin.Ticker(stock + '.NS').history(period='1mo', interval='1d')[map(str.title, ['open', 'close', 'low', 'high', 'volume'])]

            # Calculate the percentage change for the stock
            if len(stock_data) > 0:
                start_price = stock_data['Close'].iloc[0]
                end_price = stock_data['Close'].iloc[-1]
                percent_change = round(((end_price - start_price) / start_price) * 100, 2)
                stock_changes[stock] = percent_change
            else:
                stock_changes[stock] = np.nan  # If no data is available, set to NaN

        except Exception as e:
            print(f"Error fetching data for {stock}: {e}")
            stock_changes[stock] = np.nan

    # Create a DataFrame with stock tickers and their percentage changes
    df = pd.DataFrame(list(stock_changes.items()), columns=['Symbol', 'Percent_Change'])

    # Drop any stocks with missing data (NaN values)
    df = df.dropna()

    # Calculate the percentile rank based on percentage change
    df['RSP'] = round(df['Percent_Change'].rank(pct=True) * 100, 2)
    cols = ['Symbol', 'RSP']
    df = df[cols]
    # Sort by percentile rank (optional)
    df = df.sort_values(by='RSP', ascending=False).reset_index(drop=True)

    return df

In [6]:
# function to get stock technicals
def stock_prec_dev(stock_symbol):
    #stock_symbol = 'ULTRACEMCO.NS'
    short_window = 20
    mid_window = 50
    long_window = 200
    moving_avg = 'SMA'

    start = datetime.datetime(*map(int, start_date.split('-')))
    end = datetime.datetime(*map(int, end_date.split('-')))

    stock_df = yfin.Ticker(stock_symbol + '.NS').history(period='max', interval='1d')[map(str.title, ['open', 'close', 'low', 'high', 'volume'])]

    stock_df['Max'] = round(max(stock_df['Close']),2)
    stock_df = stock_df[(stock_df.index <= end_date) & (stock_df.index >= start_date)]
    stock_df['200_SMA'] = round(stock_df['Close'].rolling(window = 200, min_periods = 1).mean(),0)
    stock_df['Dev%_200'] = round((stock_df['Close'] - stock_df['200_SMA'])*100/stock_df['200_SMA'],2)
    stock_df.dropna(axis = 0, inplace = True) # remove any null rows

    stock_df['20_SMA'] = stock_df['Close'].rolling(window=20).mean()
    stock_df['50_SMA'] = stock_df['Close'].rolling(window=50).mean()
    stock_df['Symbol'] = stock_symbol

    stock_df['Close'] = round(stock_df['Close'],2)
    stock_df['Min'] = round(min(stock_df['Close']),2)
    stock_df['RSI_14'] = ta.momentum.RSIIndicator(close=stock_df['Close'], window=14).rsi()
    stock_df['RSI_14'] = round(stock_df['RSI_14'],0)
    stock_df['Prev_Close'] = stock_df['Close'].shift(1)
    stock_df.drop(['Open', 'Low', 'High', 'Volume'], axis=1, inplace=True)
    stock_df = stock_df.tail(1)

    max_SMA = max(stock_df['20_SMA'].item(), stock_df['50_SMA'].item(), stock_df['200_SMA'].item())
    min_SMA = min(stock_df['20_SMA'].item(), stock_df['50_SMA'].item(), stock_df['200_SMA'].item())
    ABS_Spread = max_SMA - min_SMA
    stock_df['Spread%'] = round((ABS_Spread / stock_df['200_SMA'].item()) * 100,2)

    return stock_df

# function to compute stock attributes
def get_common_features(stock_ids, df_mypf):

  df_prec_dev = pd.DataFrame()
  df_tmp = get_screener_features()
  df_rs = get_relative_strength(stock_ids)

  for stock_id in stock_ids:
      tmp = stock_prec_dev(stock_id)
      tmp = tmp.reset_index()
      df_prec_dev = pd.concat([df_prec_dev, tmp], ignore_index = True)
  df_prec_dev = pd.merge(df_prec_dev, df_mypf, on= 'Symbol')
  df_prec_dev = pd.merge(df_prec_dev, df_tmp, on= 'Symbol', how='left')
  df_prec_dev = pd.merge(df_prec_dev, df_rs, on= 'Symbol', how='left')
  #print(df_prec_dev.columns)
  df_prec_dev['Curr_PE'] = round(df_prec_dev['Close']/df_prec_dev['EPS'],1)
  df_prec_dev['Dev%_PE'] = round((df_prec_dev['Curr_PE'] - df_prec_dev['MedPE'])*100/df_prec_dev['MedPE'],2)
  df_prec_dev['Conviction'] = df_prec_dev['Conviction'] + '-' + df_prec_dev['CapType']
  return df_prec_dev

# function to arrange stock features
def arrange_features(df_stocks, common_cols, diff_cols):
  df_stocks_common = df_stocks[common_cols].drop_duplicates()
  df_stocks_diff = df_stocks[diff_cols]
  df_stocks_diff['Investment'] = df_stocks_diff['AvgCost'] * df_stocks_diff['Shares']
  df_stocks_diff = df_stocks_diff.groupby(['Symbol'])[['Shares', 'Investment']].aggregate(['sum']).reset_index()
  df_stocks_diff.columns = ['Symbol', 'Shares', 'Investment']
  df_stocks_diff['AvgCost'] = round(df_stocks_diff['Investment']/df_stocks_diff['Shares'],2)
  df_stocks = pd.merge(df_stocks_diff, df_stocks_common, on='Symbol')
  return df_stocks

# plot fact distribution across dimension
def plot_pie_chart(df, dimension, fact):
  # grouping the data by category and calculating the sum of fact for each type
  grouped_data = df.groupby(dimension)[fact].sum()

  # sorting the grouped data in descending order
  grouped_data = grouped_data.sort_values(ascending=False)

  # creating a pie chart
  grouped_data.plot.pie(autopct='%1.1f%%', startangle=90, figsize=(6, 6))

  # adding a title and displaying the plot
  plt.title(f'{dimension} {fact} Distribution')
  plt.ylabel('')  # To hide the y-label
  plt.show()

In [7]:
# function to get portfolio features

def get_portfolio_features(df_common_features):

  print_date_time()
  print('-------------------')

  #df_common_features["Target"] = df_common_features["Target"].fillna(df_common_features["Max"])
  df_common_features['NTT'] = np.where(df_common_features['Strategy']== 'NTT', df_common_features["Target"], df_common_features['Max'])
  df_common_features['LTT'] = np.where(df_common_features['Strategy']== 'BTT', df_common_features["Target"], df_common_features['Max'])
  df_common_features['BOL'] = df_common_features['Min']

  tmp_df = df_common_features[df_common_features['Symbol'].isin(mypf_df[mypf_df['InPortfolio'] != 'NA'].Symbol.values)]
  print('qualified stocks: '+str(len(tmp_df['Symbol'].unique())))
  tmp_df1 = tmp_df[tmp_df['LatestQtr'] == 1]
  print('with latest results: '+str(len(tmp_df1['Symbol'].unique())))
  tmp_df1 = tmp_df1[tmp_df1['StarStock'] == 1]
  print('still star stocks: '+str(len(tmp_df1['Symbol'].unique())))
  tmp_df['Investment'] = tmp_df['AvgCost'] * tmp_df['Shares']
  tmp_df['Current'] = round(tmp_df['Close'] * tmp_df['Shares'],0)
  tmp_df['Previous'] = tmp_df['Prev_Close'] * tmp_df['Shares']
  tmp_df['EstimatedST'] = tmp_df['NTT'] * tmp_df['Shares']
  tmp_df['EstimatedLT'] = tmp_df['LTT'] * tmp_df['Shares']
  tmp_df['Current P/L'] = round((tmp_df['Current'] - tmp_df['Investment']),0)
  tmp_df['Today P/L%'] = round((tmp_df['Current'] - tmp_df['Previous'])*100/tmp_df['Previous'],2)
  tmp_df['Current P/L%'] = round((tmp_df['Current'] - tmp_df['Investment'])*100/tmp_df['Investment'],2)
  tmp_df['EstimatedST P/L%'] = round((tmp_df['EstimatedST'] - tmp_df['Investment'])*100/tmp_df['Investment'],2)
  tmp_df['EstimatedLT P/L%'] = round((tmp_df['EstimatedLT'] - tmp_df['Investment'])*100/tmp_df['Investment'],2)
  tmp_df['NTT%'] = round((tmp_df['NTT'] - tmp_df['Close'])*100/tmp_df['Close'],2)
  tmp_df['LTT%'] = round((tmp_df['LTT'] - tmp_df['Close'])*100/tmp_df['Close'],2)
  tmp_df['Gained%'] = round((tmp_df['Close'] - tmp_df['BOL'])*100/tmp_df['BOL'],2)
  investment = round(sum(tmp_df['AvgCost']*tmp_df['Shares']),0)
  current = round(sum(tmp_df['Close']*tmp_df['Shares']),0)
  tmp_df['InitAlloc%'] = round(tmp_df['Investment']*100/investment,2)
  tmp_df['CurrAlloc%'] = round(tmp_df['Current']*100/current,2)
  tmp_df['FTT'] = tmp_df['LTT']
  tmp_df.loc[tmp_df['Strategy'] == 'NTT', 'FTT'] = tmp_df['NTT']
  tmp_df['FTT%'] = tmp_df['LTT%']
  tmp_df.loc[tmp_df['Strategy'] == 'NTT', 'FTT%'] = tmp_df['NTT%']
  tmp_df['FTT Amt'] = round(tmp_df['FTT%'] * tmp_df['Current']/100,0)
  tmp_df['OTT%'] = round((tmp_df['FTT'] - tmp_df['AvgCost'])*100/tmp_df['AvgCost'],2)
  tmp_df['RRR Ind'] = round(tmp_df['Current P/L']/tmp_df['FTT Amt'],2)
  tmp_df['Risk Ind'] = round(tmp_df['Current P/L%']*tmp_df['CurrAlloc%'],0)

  return tmp_df

# function to print portfolio features
def print_portfolio_stats(df_portfolio_features, myinvmt_df):
  from pyxirr import xirr

  total_booked_amt, reserve_amt, cy_booked_amt, py_booked_amt = get_amt()

  dates = myinvmt_df['Date'].values
  dates = np.append(dates, datetime.date.today().strftime('%d-%b-%y'))
  investment = myinvmt_df['Investment'].values
  dates= pd.to_datetime(dates)

  current = round(sum(df_portfolio_features['Close']*df_portfolio_features['Shares']),0) + reserve_amt
  investment_xirr = np.append(investment, current)
  cagr = round(xirr(pd.DataFrame({"dates": dates, "amounts": investment_xirr}))*100,2)

  investment = -sum(investment)
  invested = round(sum(df_portfolio_features['AvgCost']*df_portfolio_features['Shares']),0) + reserve_amt
  previous = round(sum(df_portfolio_features['Prev_Close']*df_portfolio_features['Shares']),0) + reserve_amt
  cy_invested = investment + py_booked_amt

  today_pnl_amount = current-previous
  today_pnl_percentage = round((current-previous)*100/previous,2)

  curr_pnl_amount = current-invested
  curr_pnl_percentage = round((curr_pnl_amount)*100/(cy_invested),2)

  cy_pnl_amount = cy_booked_amt + curr_pnl_amount
  cy_pnl_percentage = round((cy_pnl_amount)*100/cy_invested,2)

  overall_pnl_amount = total_booked_amt + curr_pnl_amount
  overall_pnl_percentage = round((overall_pnl_amount)*100/investment,2)

  estimate_st = round(sum(df_portfolio_features['FTT']*df_portfolio_features['Shares']),0)  + reserve_amt
  est_st_pnl_amount = estimate_st-current
  est_st_pnl_percentage = round((est_st_pnl_amount)*100/current,2)

  estimate_lt = round(sum(df_portfolio_features['LTT']*df_portfolio_features['Shares']),0)  + reserve_amt
  est_lt_pnl_amount = estimate_lt-current
  est_lt_pnl_percentage = round((est_lt_pnl_amount)*100/current,2)

  total_profit = round(sum(df_portfolio_features[df_portfolio_features['Current P/L%'] > 0]['Current']) - sum(df_portfolio_features[df_portfolio_features['Current P/L%'] > 0]['Investment']),0)
  total_loss = round(sum(df_portfolio_features[df_portfolio_features['Current P/L%'] < 0]['Current']) - sum(df_portfolio_features[df_portfolio_features['Current P/L%'] < 0]['Investment']),0)

  cy_booked_percentage = round((cy_booked_amt)*100/current,2)
  py_booked_percentage = round((py_booked_amt)*100/investment,2)
  total_booked_percentage = round((total_booked_amt)*100/investment,2)

  print('-------------------')
  print('Initial Investment: ', format_amt(investment))
  print('CY Investment: ', format_amt(cy_invested))
  print('Reserve: ', format_amt(reserve_amt))
  print('Current: ',  format_amt(current))
  print('-------------------')
  print('Today PnL: '+ '{} ({}%)'.format(format_amt(today_pnl_amount), today_pnl_percentage))
  print('Current PnL: '+ '{} ({}%)'.format(format_amt(curr_pnl_amount), curr_pnl_percentage))
  print('CY Booked + Current PnL: '+ '{} ({}%)'.format(format_amt(cy_pnl_amount), cy_pnl_percentage))
  print('-------------------')
  print('Total profit: ', format_amt(total_profit))
  print('Total loss: ', format_amt(total_loss))
  print('-------------------')
  print('Total Booked + Current PnL: '+ '{} ({}%)'.format(format_amt(overall_pnl_amount), overall_pnl_percentage))
  print('Total Booked PnL: '+ '{} ({}%)'.format(format_amt(total_booked_amt), total_booked_percentage))
  print('Curr Year Booked PnL: '+ '{} ({}%)'.format(format_amt(cy_booked_amt), cy_booked_percentage))
  print('Prev Year Booked PnL: '+ '{} ({}%)'.format(format_amt(py_booked_amt), py_booked_percentage))
  print('===================')
  print('Est FTT: ',  format_amt(estimate_st))
  print('Est FTT PnL: '+ '{} ({}%)'.format(format_amt(est_st_pnl_amount), est_st_pnl_percentage))

  print('===================')
  print('Deployed: ', format_amt(investment))

  print('Current: ', format_amt(current))

  print('CAGR/XIRR %: '+'{}%'.format(cagr))

In [8]:
# get start and end date
start_date, end_date = get_start_end_date()

# get portfolio and prospects data
mypfs_df = get_mypfs_df()
mypps_df = get_mypps_df()
myinvmt_df = get_myinvmt_df()

# merge above datasets
mypf_df = pd.merge(mypfs_df, mypps_df, on="Symbol")

# seggregate dm and sv portfolio
dm_pf = mypf_df[mypf_df['InPortfolio'] == 'DM']
sv_pf = mypf_df[mypf_df['InPortfolio'] == 'SV']

# build portfolio stock dataframe
dm_stocks = get_stock_ids(dm_pf)
sv_stocks = get_stock_ids(sv_pf)
df_stocks = pd.concat([dm_pf,sv_pf], ignore_index = True)

# arrange common and diff stock features
common_cols = ['Symbol', 'Target', 'Criteria', 'Strategy', 'CumlRnk', 'LatestQtr', 'StarStock', 'Conviction', 'Category', 'InFolio', 'XIRR', 'MBQ']
diff_cols = ['Symbol', 'AvgCost', 'Shares']
df_stocks = arrange_features(df_stocks, common_cols, diff_cols)

# get common features
stock_ids = df_stocks['Symbol'].values
df_common_features = get_common_features(stock_ids, df_stocks)

df_common_features.reset_index(drop=True, inplace=True)
df_common_features.drop(['Date'], axis=1, inplace=True)
# get and print portfolio features
df_portfolio_features = get_portfolio_features(df_common_features)

print_portfolio_stats(df_portfolio_features, myinvmt_df)

df = df_portfolio_features
#plot_pie_chart(df, 'CapType', 'Current')
list_ox40n = list(df[df['MBQ'].str.contains('OX40N', na=False)]['Symbol'].values)

Run date time (IST): 2026-06-08 17:01:29
-------------------
qualified stocks: 92
with latest results: 31
still star stocks: 20
-------------------
Initial Investment:  1.40 C
CY Investment:  1.82 C
Reserve:  1.49 K
Current:  1.46 C
-------------------
Today PnL: -2.18 L (-1.47%)
Current PnL: -37.01 L (-20.29%)
CY Booked + Current PnL: -34.93 L (-19.15%)
-------------------
Total profit:  2.15 L
Total loss:  -39.15 L
-------------------
Total Booked + Current PnL: 7.94 L (5.69%)
Total Booked PnL: 44.95 L (32.22%)
Curr Year Booked PnL: 2.08 L (1.42%)
Prev Year Booked PnL: 42.87 L (30.73%)
===================
Est FTT:  2.55 C
Est FTT PnL: 1.09 C (74.57%)
===================
Deployed:  1.40 C
Current:  1.46 C
CAGR/XIRR %: 2.2%

In [9]:
# top 5 near their targets
cols = ['Symbol', 'Today P/L%', 'Current P/L%', 'FTT%', 'OTT%', 'FTT Amt', 'Current P/L', 'Current', 'FTT', 'Dev%_PE', 'RSI_14','Conviction', 'Spread%',  'CumlRnk', 'RRR Ind', 'CurrAlloc%', 'Gained%', 'Criteria', 'Strategy', 'Category']
df_tmp = df_portfolio_features[~df_portfolio_features['Symbol'].isin(['ENRIN','BLUSPRING','DIGITIDE'])]
df_tmp = df_tmp.sort_values(by = 'FTT Amt', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
59,PIDILITIND,-1.14,3.45,14.42,18.37,21050.0,4870.0,145980.0,1670.26,-27.53,53.0,X-LC,4.10,5.0,0.23,1.00,14.62,X40,ATH,CHEMICALS
51,KOTAKBANK,-0.09,0.76,20.19,21.11,28171.0,1054.0,139527.0,453.24,-13.74,45.0,X-LC,7.01,12.0,0.04,0.95,6.71,X40,ATH,BANKS
55,MASFIN,-3.20,-9.26,33.98,21.57,30210.0,-9075.0,88905.0,397.04,-21.86,34.0,H-SC,1.42,167.0,-0.30,0.61,5.97,XR,ATH,FINANCE
72,SIS,-2.53,-6.64,29.89,21.26,30983.0,-7374.0,103658.0,528.00,2468.39,60.0,H-SC,19.30,168.0,-0.24,0.71,54.12,OX40N,NTT,MISC
17,CIPLA,-0.96,12.37,18.75,33.43,32269.0,18939.0,172100.0,1648.14,-12.91,57.0,X-LC,7.86,18.0,0.59,1.18,17.49,X40N,ATH,PHARMA

In [10]:
# top 5 today
df_tmp = df_portfolio_features.sort_values(by = 'Today P/L%', ascending=False)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
69,SFL,4.45,-33.95,91.70,26.63,158832.0,-89010.0,173208.0,1287.00,31.11,71.0,M-SC,7.82,242.0,-0.56,1.19,44.36,XY24,NTT,MISC
27,GLAXO,0.91,-12.33,54.78,35.69,95703.0,-24580.0,174704.0,3380.16,-33.11,34.0,X-MC,8.31,56.0,-0.26,1.20,0.91,X40,ATH,PHARMA
3,ALKYLAMINE,0.76,-23.82,154.16,93.63,118577.0,-24045.0,76918.0,4546.37,-18.40,59.0,H-SC,9.28,142.0,-0.20,0.53,45.24,SR,ATH,CHEMICALS
57,PAGEIND,0.53,0.55,32.86,33.59,88673.0,1471.0,269850.0,51217.29,-27.90,58.0,X-MC,2.84,55.0,0.02,1.85,28.15,X40,ATH,APPARELS
42,INDIAMART,0.40,-13.69,139.52,106.72,148512.0,-16891.0,106445.0,4810.62,-61.13,46.0,H-SC,11.36,140.0,-0.11,0.73,3.05,AR,ATH,MISC

In [11]:
# bottom 5 today
df_tmp = df_portfolio_features.sort_values(by = 'Today P/L%', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
90,WIPRO,-8.37,-25.45,131.07,72.27,165572.0,-43125.0,126323.0,420.00,-32.52,31.0,M-LC,12.65,98.0,-0.26,0.86,0.00,XR,NTT,IT
86,VALIANTORG,-5.43,-43.95,210.72,74.15,193226.0,-71907.0,91698.0,838.00,-264.69,42.0,H-SC,5.79,145.0,-0.37,0.63,36.46,XR,NTT,CHEMICALS
18,COFFEEDAY,-5.00,-38.27,119.12,35.27,83502.0,-43450.0,70099.0,80.00,-51.71,66.0,L-SC,19.41,266.0,-0.52,0.48,72.87,XR,NTT,HOTELS
61,RAJESHEXPO,-4.99,-81.88,452.24,0.07,112413.0,-112320.0,24857.0,518.00,811.62,31.0,L-SC,30.87,268.0,-1.00,0.17,16.70,OX40N,NTT,JEWELLERY
25,FINCABLES,-3.58,29.14,61.00,107.91,116306.0,43021.0,190665.0,1641.55,16.18,48.0,M-SC,25.29,220.0,0.37,1.30,43.44,OX40N,ATH,CABLES

In [12]:
# top 5 to exit based on CumlRnk
df_tmp = df_portfolio_features[~df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])]
df_tmp = df_tmp[(df_tmp['Current P/L%'] > -1) & (df_tmp['Current P/L%'] < 1)].sort_values(by = 'CumlRnk', ascending=False)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
74,STARHEALTH,-1.38,0.38,46.7,47.26,131787.0,1077.0,282200.0,761.0,58.32,50.0,H-SC,9.79,173.0,0.01,1.93,23.9,XY24,NTT,INSURANCE

In [13]:
# OX40N stocks to exit
df_tmp = df_portfolio_features[(df_portfolio_features['Symbol'].isin(list_ox40n))].sort_values(by = 'Current P/L%', ascending=False)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
25,FINCABLES,-3.58,29.14,61.00,107.91,116306.0,43021.0,190665.0,1641.55,16.18,48.0,M-SC,25.29,220.0,0.37,1.30,43.44,OX40N,ATH,CABLES
72,SIS,-2.53,-6.64,29.89,21.26,30983.0,-7374.0,103658.0,528.00,2468.39,60.0,H-SC,19.30,168.0,-0.24,0.71,54.12,OX40N,NTT,MISC
16,CERA,-0.72,-28.44,73.12,23.89,92043.0,-50024.0,125879.0,9475.00,-31.03,45.0,H-SC,5.23,153.0,-0.54,0.86,20.97,OX40N,NTT,CERAMICS
50,KANSAINER,-0.10,-29.69,61.39,13.47,116397.0,-80064.0,189603.0,340.00,-39.58,48.0,H-SC,9.24,162.0,-0.69,1.30,32.44,XY24,NTT,PAINTS
83,TTKPRESTIG,-2.84,-32.60,48.51,0.09,32950.0,-32853.0,67924.0,770.00,57.74,46.0,M-SC,13.50,250.0,-1.00,0.46,20.95,OX40N,NTT,DURABLES

In [14]:
# top 5 to book for rotation
df_tmp = df_portfolio_features[(df_portfolio_features['Current P/L%'] > 20) ].sort_values(by = 'CumlRnk', ascending=False)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
25,FINCABLES,-3.58,29.14,61.00,107.91,116306.0,43021.0,190665.0,1641.55,16.18,48.0,M-SC,25.29,220.0,0.37,1.30,43.44,OX40N,ATH,CABLES
68,SATIN,-1.70,31.49,15.47,51.83,56201.0,87007.0,363291.0,274.00,18.27,70.0,H-SC,41.50,159.0,1.55,2.49,76.98,XY24,NTT,FINANCE

In [15]:
# top 5 to monitor for exit
df_tmp = df_portfolio_features[~df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])]
df_tmp = df_tmp[(df_tmp['Current P/L%'] > 0) ].sort_values(by = 'Dev%_PE', ascending=False)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
74,STARHEALTH,-1.38,0.38,46.70,47.26,131787.0,1077.0,282200.0,761.00,58.32,50.0,H-SC,9.79,173.0,0.01,1.93,23.90,XY24,NTT,INSURANCE
68,SATIN,-1.70,31.49,15.47,51.83,56201.0,87007.0,363291.0,274.00,18.27,70.0,H-SC,41.50,159.0,1.55,2.49,76.98,XY24,NTT,FINANCE
25,FINCABLES,-3.58,29.14,61.00,107.91,116306.0,43021.0,190665.0,1641.55,16.18,48.0,M-SC,25.29,220.0,0.37,1.30,43.44,OX40N,ATH,CABLES
91,ZYDUSLIFE,-0.13,14.69,18.26,35.63,43890.0,30786.0,240360.0,1286.17,0.00,70.0,H-MC,10.04,120.0,0.70,1.64,26.38,AR,ATH,PHARMA
73,SONACOMS,-2.33,1.76,36.68,39.09,37760.0,1785.0,102944.0,804.02,-19.39,48.0,M-MC,18.81,193.0,0.05,0.70,45.63,AR,ATH,AUTO

In [16]:
# top 5 to book for rotation from weak conviction
df_tmp = df_portfolio_features[~df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])]
df_tmp = df_tmp[~df_tmp['Criteria'].isin(['XY25','XY24','X40', 'X40N'])].sort_values(by = 'RRR Ind', ascending=False)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
91,ZYDUSLIFE,-0.13,14.69,18.26,35.63,43890.0,30786.0,240360.0,1286.17,0.00,70.0,H-MC,10.04,120.0,0.70,1.64,26.38,AR,ATH,PHARMA
25,FINCABLES,-3.58,29.14,61.00,107.91,116306.0,43021.0,190665.0,1641.55,16.18,48.0,M-SC,25.29,220.0,0.37,1.30,43.44,OX40N,ATH,CABLES
73,SONACOMS,-2.33,1.76,36.68,39.09,37760.0,1785.0,102944.0,804.02,-19.39,48.0,M-MC,18.81,193.0,0.05,0.70,45.63,AR,ATH,AUTO
42,INDIAMART,0.40,-13.69,139.52,106.72,148512.0,-16891.0,106445.0,4810.62,-61.13,46.0,H-SC,11.36,140.0,-0.11,0.73,3.05,AR,ATH,MISC
75,SURYODAY,-0.91,-3.01,26.86,23.03,46649.0,-5396.0,173675.0,216.00,88.60,63.0,H-SC,18.72,166.0,-0.12,1.19,46.23,XR,NTT,BANKS

In [17]:
# top 5 to accumulate based on lowest RSI_14
df_tmp = df_portfolio_features[df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])].sort_values(by = 'RSI_14', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
65,RELIANCE,-2.15,-18.91,54.52,25.30,88849.0,-37997.0,162966.0,1952.00,-21.18,28.0,X-LC,6.40,21.0,-0.43,1.12,0.00,XY25,BTT,REFINERIES
35,HDFCLIFE,-1.87,-7.67,44.24,33.18,61191.0,-11485.0,138315.0,814.30,-27.88,30.0,X-LC,15.24,31.0,-0.19,0.95,0.00,X40,ATH,INSURANCE
40,ICICIPRULI,-1.62,-21.33,65.60,30.28,101667.0,-42025.0,154980.0,787.27,-42.46,31.0,X-MC,14.66,78.0,-0.41,1.06,0.03,X40,ATH,INSURANCE
58,PGHH,-2.81,-31.54,92.84,32.01,135702.0,-67352.0,146168.0,17616.87,-53.70,33.0,X-MC,18.57,57.0,-0.50,1.00,0.00,X40,ATH,FMCG
27,GLAXO,0.91,-12.33,54.78,35.69,95703.0,-24580.0,174704.0,3380.16,-33.11,34.0,X-MC,8.31,56.0,-0.26,1.20,0.91,X40,ATH,PHARMA

In [18]:
# top 5 to accumulate based on Spread and CumlRnk
df_tmp = df_portfolio_features[df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])]
df_tmp = df_tmp[(df_tmp['CumlRnk'] < 100)].sort_values(by = 'Spread%', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
57,PAGEIND,0.53,0.55,32.86,33.59,88673.0,1471.0,269850.0,51217.29,-27.90,58.0,X-MC,2.84,55.0,0.02,1.85,28.15,X40,ATH,APPARELS
49,JSWINFRA,-3.47,-8.61,27.40,16.43,55534.0,-19094.0,202680.0,342.00,-21.66,46.0,X-MC,3.53,61.0,-0.34,1.39,14.57,X40N,NTT,REALTY
59,PIDILITIND,-1.14,3.45,14.42,18.37,21050.0,4870.0,145980.0,1670.26,-27.53,53.0,X-LC,4.10,5.0,0.23,1.00,14.62,X40,ATH,CHEMICALS
23,DMART,-1.95,-2.32,32.69,29.60,79698.0,-5802.0,243798.0,5391.45,-17.64,38.0,X-LC,4.12,14.0,-0.07,1.67,11.44,X40N,ATH,FMCG
19,COLPAL,0.30,-23.85,83.67,39.86,167800.0,-62815.0,200550.0,3683.41,-7.87,40.0,X-MC,4.17,62.0,-0.37,1.37,13.44,XY25,ATH,FMCG

In [19]:
# top 5 to accumulate based on lowest Gained%
df_tmp = df_portfolio_features[df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])].sort_values(by = 'Gained%', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
35,HDFCLIFE,-1.87,-7.67,44.24,33.18,61191.0,-11485.0,138315.0,814.30,-27.88,30.0,X-LC,15.24,31.0,-0.19,0.95,0.0,X40,ATH,INSURANCE
32,HAVELLS,-0.89,-26.99,80.01,31.42,191594.0,-88528.0,239463.0,2052.62,-31.36,36.0,X-MC,14.13,63.0,-0.46,1.64,0.0,X40,ATH,ELECTRICAL
65,RELIANCE,-2.15,-18.91,54.52,25.30,88849.0,-37997.0,162966.0,1952.00,-21.18,28.0,X-LC,6.40,21.0,-0.43,1.12,0.0,XY25,BTT,REFINERIES
58,PGHH,-2.81,-31.54,92.84,32.01,135702.0,-67352.0,146168.0,17616.87,-53.70,33.0,X-MC,18.57,57.0,-0.50,1.00,0.0,X40,ATH,FMCG
79,TCS,-2.16,-36.84,97.73,24.88,285948.0,-170683.0,292590.0,4253.91,-46.57,36.0,X-LC,18.62,2.0,-0.60,2.00,0.0,X40,ATH,IT

In [20]:
# top 5 to accumulate based on lowest CurrAlloc%
df_tmp = df_portfolio_features[df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])].sort_values(by = 'CurrAlloc%', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
10,BATAINDIA,-0.91,-57.52,218.27,35.20,119306.0,-74010.0,54660.0,2096.00,-28.38,34.0,X-SC,25.49,91.0,-0.62,0.37,8.40,X40,NTT,FOOTWEAR
64,RELAXO,-3.30,-58.67,268.48,52.31,161088.0,-85160.0,60000.0,1176.00,-55.96,55.0,X-SC,21.76,92.0,-0.53,0.41,34.15,X40N,NTT,FOOTWEAR
60,QUESS,0.15,-3.18,79.62,73.90,82322.0,-3399.0,103394.0,424.00,-48.21,72.0,X-SC,5.55,80.0,-0.04,0.71,40.95,XY24,NTT,MISC
28,GODREJCP,-0.10,-10.78,47.35,31.47,62787.0,-16013.0,132601.0,1469.04,-6.17,39.0,X-LC,10.01,32.0,-0.26,0.91,1.74,X40N,ATH,FMCG
53,M&M,-2.45,-3.76,28.20,23.38,37639.0,-5211.0,133470.0,3802.40,-18.26,39.0,X-LC,10.10,25.0,-0.14,0.91,1.19,X40N,ATH,AUTO

In [21]:
# top 5 to accumulate based on CumlRnk
df_tmp = df_portfolio_features.sort_values(by = 'CumlRnk', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
47,ITC,-0.45,-26.39,61.75,19.06,154614.0,-89779.0,250387.0,452.00,-59.56,35.0,X-LC,14.81,1.0,-0.58,1.71,0.88,X40,NTT,FMCG
79,TCS,-2.16,-36.84,97.73,24.88,285948.0,-170683.0,292590.0,4253.91,-46.57,36.0,X-LC,18.62,2.0,-0.60,2.00,0.00,X40,ATH,IT
45,INFY,-0.83,-19.15,66.05,34.24,167079.0,-59929.0,252959.0,1972.00,-36.50,49.0,X-LC,17.61,3.0,-0.36,1.73,8.46,X40,NTT,IT
81,TMPV,-2.21,-11.45,54.24,36.58,170905.0,-40751.0,315090.0,600.00,-81.44,60.0,X-LC,17.03,4.0,-0.24,2.16,31.33,XY24,NTT,AUTO
59,PIDILITIND,-1.14,3.45,14.42,18.37,21050.0,4870.0,145980.0,1670.26,-27.53,53.0,X-LC,4.10,5.0,0.23,1.00,14.62,X40,ATH,CHEMICALS

In [22]:
# top 5 for average up
df_tmp = df_portfolio_features[(df_portfolio_features['Dev%_200'] > 5)].sort_values(by = 'CurrAlloc%', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
44,INDUSINDBK,-1.08,-33.92,101.11,32.89,51584.0,-26188.0,51018.0,1800.00,-340.20,47.0,L-MC,7.27,258.0,-0.51,0.35,25.58,XR,NTT,BANKS
18,COFFEEDAY,-5.00,-38.27,119.12,35.27,83502.0,-43450.0,70099.0,80.00,-51.71,66.0,L-SC,19.41,266.0,-0.52,0.48,72.87,XR,NTT,HOTELS
3,ALKYLAMINE,0.76,-23.82,154.16,93.63,118577.0,-24045.0,76918.0,4546.37,-18.40,59.0,H-SC,9.28,142.0,-0.20,0.53,45.24,SR,ATH,CHEMICALS
73,SONACOMS,-2.33,1.76,36.68,39.09,37760.0,1785.0,102944.0,804.02,-19.39,48.0,M-MC,18.81,193.0,0.05,0.70,45.63,AR,ATH,AUTO
72,SIS,-2.53,-6.64,29.89,21.26,30983.0,-7374.0,103658.0,528.00,2468.39,60.0,H-SC,19.30,168.0,-0.24,0.71,54.12,OX40N,NTT,MISC

In [23]:
# top 5 RSP
df_tmp = df_portfolio_features.sort_values(by = 'RSP', ascending=False)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
18,COFFEEDAY,-5.00,-38.27,119.12,35.27,83502.0,-43450.0,70099.0,80.00,-51.71,66.0,L-SC,19.41,266.0,-0.52,0.48,72.87,XR,NTT,HOTELS
91,ZYDUSLIFE,-0.13,14.69,18.26,35.63,43890.0,30786.0,240360.0,1286.17,0.00,70.0,H-MC,10.04,120.0,0.70,1.64,26.38,AR,ATH,PHARMA
69,SFL,4.45,-33.95,91.70,26.63,158832.0,-89010.0,173208.0,1287.00,31.11,71.0,M-SC,7.82,242.0,-0.56,1.19,44.36,XY24,NTT,MISC
37,HONAUT,-0.46,-10.44,68.96,51.31,119094.0,-20138.0,172700.0,58357.33,-25.60,60.0,X-SC,7.32,90.0,-0.17,1.18,31.21,X40N,ATH,ELECTRICAL
68,SATIN,-1.70,31.49,15.47,51.83,56201.0,87007.0,363291.0,274.00,18.27,70.0,H-SC,41.50,159.0,1.55,2.49,76.98,XY24,NTT,FINANCE

In [24]:
# Top N allocation
df_tmp = df_portfolio_features.sort_values(by = 'CurrAlloc%', ascending=False)
top_n_values = [10, 25, 50]

sum_df = pd.DataFrame({
    'Top_N': top_n_values,
    'Sum_Alloc%': [df_tmp['CurrAlloc%'].head(n).sum() for n in top_n_values]
})

sum_df

   Top_N  Sum_Alloc%
0     10       19.87
1     25       42.86
2     50       72.89

In [25]:
# market-cap-wise allocation
df_tmp = df_portfolio_features[cols]
df_tmp.groupby(df_tmp['Conviction'].str[-2:])['CurrAlloc%'].sum().sort_values(ascending=False)

Conviction
SC    43.06
LC    31.36
MC    25.58
Name: CurrAlloc%, dtype: float64

In [26]:
# criteria-wise allocation
df_portfolio_features.groupby('Criteria')['CurrAlloc%'].sum().sort_values(ascending=False)

Criteria
XY24     27.95
X40      25.01
X40N     16.98
XR        8.96
AR        6.87
OX40N     6.82
XY25      6.53
SR        0.88
Name: CurrAlloc%, dtype: float64

In [27]:
# conviction-wise allocation
df_portfolio_features.groupby('Conviction')['CurrAlloc%'].sum().sort_values(ascending=False)

Conviction
X-LC    29.26
H-SC    22.67
X-MC    20.45
M-SC     9.95
X-SC     9.79
H-MC     2.79
M-MC     1.99
H-LC     1.24
M-LC     0.86
L-SC     0.65
L-MC     0.35
Name: CurrAlloc%, dtype: float64

In [28]:
# sector-wise stats
df_tmp = df_portfolio_features.groupby('Category')[['CurrAlloc%', 'Current', 'Current P/L', 'FTT Amt']].sum().sort_values(by=['Current', 'Current P/L'], ascending=False)
df_tmp['Current P/L%'] = round(df_tmp['Current P/L'] * 100 / df_tmp['Current'], 2)
df_tmp['FTT%'] = round(df_tmp['FTT Amt'] * 100 / df_tmp['Current'], 2)
cols = ['CurrAlloc%', 'Current P/L%', 'FTT%']
df_tmp[cols].sort_values(by=['CurrAlloc%'], ascending=False)

               CurrAlloc%  Current P/L%    FTT%
Category
FMCG                14.89        -21.52   64.15
FINANCE             10.86        -16.27   66.84
IT                  10.22        -50.74  126.11
MISC                 7.12        -28.86   84.84
AUTO                 6.86         -9.03   49.91
BANKS                5.77         -7.65   57.42
PAINTS               5.55        -21.67   42.80
INSURANCE            5.20         -8.99   45.84
PHARMA               5.08          0.13   30.78
ELECTRICAL           4.06        -19.14   61.19
CHEMICALS            2.16        -28.95  105.80
HEALTHCARE           2.06        -18.62   49.58
APPARELS             1.85          0.55   32.86
AC                   1.82        -19.85   52.34
FOOTWEAR             1.71        -76.66  147.50
TRAVEL               1.60        -91.47  187.34
DURABLES             1.55        -70.00  111.36
BREWERIES            1.46         -9.92   32.74
REALTY               1.39         -9.42   27.40
CERAMICS             1.32        -58.87  107.14
ENGINEERING          1.31        -26.73   84.69
CABLES               1.30         22.56   61.00
REFINERIES           1.12        -23.32   54.52
CEMENT               1.08        -69.31  195.98
JEWELLERY            1.03       -112.15  185.86
ENTERTAINMENT        0.74        -78.87  185.56
HOTELS               0.48        -61.98  119.12
TEXTILES             0.41        -55.43   99.75

In [29]:
# money to be made criteria-wise
df_portfolio_features.groupby('Criteria')['FTT Amt'].agg(['sum', 'count']).sort_values(by='sum', ascending=False)

                sum  count
Criteria
XY24      3515113.0     21
X40       2028335.0     19
XR        1371910.0     13
X40N      1241168.0     13
AR        1179394.0      9
OX40N      791867.0     10
XY25       481247.0      5
SR         290725.0      2

In [30]:
# money to be made conviction-wise
df_portfolio_features.groupby('Conviction')['FTT Amt'].agg(['sum', 'count']).sort_values(by='sum', ascending=False)

                  sum  count
Conviction
H-SC        3473901.0     24
X-LC        2012362.0     21
X-MC        1730383.0     15
M-SC        1463168.0     14
X-SC        1370981.0      9
H-MC         289332.0      2
L-SC         195915.0      2
M-LC         165572.0      1
M-MC          94194.0      2
H-LC          52367.0      1
L-MC          51584.0      1

In [31]:
# money to be made criteria and conviction-wise
df_portfolio_features.groupby(['Conviction', 'Criteria'])['FTT Amt'].agg(['sum', 'count']).sort_values(by='sum', ascending=False)

                           sum  count
Conviction Criteria
X-LC       X40       1084842.0     10
H-SC       XY24      1052679.0      6
           AR         968576.0      5
M-SC       XY24       845759.0      6
H-SC       XR         826749.0      7
X-SC       XY24       801530.0      4
X-MC       X40        723469.0      7
           X40N       509910.0      4
X-LC       X40N       381831.0      6
X-SC       X40N       349427.0      3
M-SC       OX40N      344282.0      5
H-SC       OX40N      335172.0      4
X-LC       XY24       327466.0      2
H-SC       SR         290725.0      2
X-MC       XY25       254767.0      2
H-MC       XY24       245442.0      1
X-MC       XY24       242237.0      2
X-SC       X40        220024.0      2
M-SC       XR         196326.0      2
X-LC       XY25       170046.0      2
M-LC       XR         165572.0      1
L-SC       OX40N      112413.0      1
           XR          83502.0      1
M-SC       AR          76801.0      1
M-MC       XY25        56434.0      1
H-LC       AR          52367.0      1
L-MC       XR          51584.0      1
X-LC       XR          48177.0      1
H-MC       AR          43890.0      1
M-MC       AR          37760.0      1

In [32]:
# notebook execution time

end_time = time.time()
execution_time = round(end_time - start_time, 0)
print(f"Notebook execution time: {execution_time} seconds")

Notebook execution time: 51.0 seconds