<a href="https://colab.research.google.com/github/ankit-rathi/Quantvesting_v2/blob/main/myStocks_Portfolio_Analysis.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
'''
!pip install pandas==2.2.2 -qq
!pip install pyxirr -qq
!pip install ta -qq
!pip install yfinance==0.2.59 -qq
'''

'\n!pip install pandas==2.2.2 -qq\n!pip install pyxirr -qq\n!pip install ta -qq\n!pip install yfinance==0.2.59 -qq\n'

In [2]:
# import libraries

import numpy as np
import pandas as pd
import datetime
import warnings
warnings.filterwarnings('ignore')
import yfinance as yfin
import ta
import matplotlib.pyplot as plt
import requests

In [3]:
# notebook start time
import time
import datetime
import pytz

start_time = time.time()

# function to print date timestamp
def print_date_time():
  tz_NY = pytz.timezone('Asia/Kolkata')
  datetime_NY = datetime.datetime.now(tz_NY)
  print("Run date time (IST):", datetime_NY.strftime("%Y-%m-%d %H:%M:%S"))

In [4]:
# function to get booked and reserved amount
def get_amt():
  # fetch the JSON data from the URL
  url = "https://raw.githubusercontent.com/ankit-rathi/Tradevesting_v1/main/data/myPortfolioAmts.json"
  response = requests.get(url)
  pf_amts = response.json()  # parse the JSON data

  # extract values from the JSON
  py_booked_amt_dm = pf_amts["py_booked_amt_dm"]
  py_booked_amt_sv = pf_amts["py_booked_amt_sv"]
  cy_booked_amt_dm = pf_amts["cy_booked_amt_dm"]
  cy_booked_amt_sv = pf_amts["cy_booked_amt_sv"]
  reserve_amt_dm = pf_amts["reserve_amt_dm"]
  reserve_amt_sv = pf_amts["reserve_amt_sv"]

  # perform calculations
  py_booked_amt = py_booked_amt_dm + py_booked_amt_sv
  cy_booked_amt = cy_booked_amt_dm + cy_booked_amt_sv
  reserve_amt = reserve_amt_dm + reserve_amt_sv
  total_booked_amt = py_booked_amt + cy_booked_amt

  return total_booked_amt, reserve_amt, cy_booked_amt, py_booked_amt

gen_output = 0

In [5]:
# function to format the amount
def format_amt(number):
    abs_number = abs(number)

    if abs_number >= 1_00_00_000:  # Crores
        formatted_amt = f"{number / 1_00_00_000:.2f} C"
    elif abs_number >= 1_00_000:  # Lakhs
        formatted_amt = f"{number / 1_00_000:.2f} L"
    elif abs_number >= 1_000:  # Thousands
        formatted_amt = f"{number / 1_000:.2f} K"
    else:
        formatted_amt = f"{number:.2f}"

    return formatted_amt

# function to set start and end date
def get_start_end_date():
  start_date = (datetime.date.today() + datetime.timedelta(days=-365)).strftime('%Y-%m-%d')
  end_date = (datetime.date.today() + datetime.timedelta(days=1)).strftime('%Y-%m-%d')
  return start_date, end_date

# function to fetch my portfolio csv
def get_mypfs_df():
  mypfs_df = pd.read_csv('https://raw.githubusercontent.com/ankit-rathi/Tradevesting_v1/main/data/myPortfolioStocks.csv')
  return mypfs_df

# function to fetch my prospects csv
def get_mypps_df():
  mypps_df = pd.read_csv('https://raw.githubusercontent.com/ankit-rathi/Tradevesting_v1/main/data/myProspectsScrips.csv')
  return mypps_df

# function to fetch screener data
def get_myscreen_df():
  myscreen_df = pd.read_csv('https://raw.githubusercontent.com/ankit-rathi/Tradevesting_v1/main/data/myScreenerDB.csv')
  return myscreen_df

# function to fetch momentum data
def get_myinvmt_df():
  myinvmt_df = pd.read_csv('https://raw.githubusercontent.com/ankit-rathi/Tradevesting_v1/main/data/myInvestments.csv')
  return myinvmt_df

# function to get the stock ids
def get_stock_ids(df_pf):
  stock_n100 = df_pf['Symbol'].unique()

  exclude = ['CADILAHC','MMTC', 'MASFIN']

  stock_ids = df_pf[~df_pf['Symbol'].isin(exclude) ]['Symbol'].unique()

  #mypf = mypf[mypf.Forecast.notnull()]
  #stock_ids = mypf['Symbol'].unique()

  #stock_ids.sort()
  return stock_ids

# get features from screener data
def get_screener_features():
  myscreen_df = get_myscreen_df()
  cols = ['Symbol', 'EPS', 'MedPE', 'ROCE%', 'ROE%', 'CapType']
  return myscreen_df[cols]

# get relative strength
def get_relative_strength(stock_list):

    # Dictionary to store stock tickers and their corresponding percentage price change
    stock_changes = {}

    # Loop through each stock and fetch its price data
    for stock in stock_list:
        try:
            # Download the stock data for the given date range
            stock_data = yfin.Ticker(stock + '.NS').history(period='1mo', interval='1d')[map(str.title, ['open', 'close', 'low', 'high', 'volume'])]

            # Calculate the percentage change for the stock
            if len(stock_data) > 0:
                start_price = stock_data['Close'].iloc[0]
                end_price = stock_data['Close'].iloc[-1]
                percent_change = round(((end_price - start_price) / start_price) * 100, 2)
                stock_changes[stock] = percent_change
            else:
                stock_changes[stock] = np.nan  # If no data is available, set to NaN

        except Exception as e:
            print(f"Error fetching data for {stock}: {e}")
            stock_changes[stock] = np.nan

    # Create a DataFrame with stock tickers and their percentage changes
    df = pd.DataFrame(list(stock_changes.items()), columns=['Symbol', 'Percent_Change'])

    # Drop any stocks with missing data (NaN values)
    df = df.dropna()

    # Calculate the percentile rank based on percentage change
    df['RSP'] = round(df['Percent_Change'].rank(pct=True) * 100, 2)
    cols = ['Symbol', 'RSP']
    df = df[cols]
    # Sort by percentile rank (optional)
    df = df.sort_values(by='RSP', ascending=False).reset_index(drop=True)

    return df

In [6]:
# function to get stock technicals
def stock_prec_dev(stock_symbol):
    #stock_symbol = 'ULTRACEMCO.NS'
    short_window = 20
    mid_window = 50
    long_window = 200
    moving_avg = 'SMA'

    start = datetime.datetime(*map(int, start_date.split('-')))
    end = datetime.datetime(*map(int, end_date.split('-')))

    stock_df = yfin.Ticker(stock_symbol + '.NS').history(period='max', interval='1d')[map(str.title, ['open', 'close', 'low', 'high', 'volume'])]

    stock_df['Max'] = round(max(stock_df['Close']),2)
    stock_df = stock_df[(stock_df.index <= end_date) & (stock_df.index >= start_date)]
    stock_df['200_SMA'] = round(stock_df['Close'].rolling(window = 200, min_periods = 1).mean(),0)
    stock_df['Dev%_200'] = round((stock_df['Close'] - stock_df['200_SMA'])*100/stock_df['200_SMA'],2)
    stock_df.dropna(axis = 0, inplace = True) # remove any null rows

    stock_df['20_SMA'] = stock_df['Close'].rolling(window=20).mean()
    stock_df['50_SMA'] = stock_df['Close'].rolling(window=50).mean()
    stock_df['Symbol'] = stock_symbol

    stock_df['Close'] = round(stock_df['Close'],2)
    stock_df['Min'] = round(min(stock_df['Close']),2)
    stock_df['RSI_14'] = ta.momentum.RSIIndicator(close=stock_df['Close'], window=14).rsi()
    stock_df['RSI_14'] = round(stock_df['RSI_14'],0)
    stock_df['Prev_Close'] = stock_df['Close'].shift(1)
    stock_df.drop(['Open', 'Low', 'High', 'Volume'], axis=1, inplace=True)
    stock_df = stock_df.tail(1)

    max_SMA = max(stock_df['20_SMA'].item(), stock_df['50_SMA'].item(), stock_df['200_SMA'].item())
    min_SMA = min(stock_df['20_SMA'].item(), stock_df['50_SMA'].item(), stock_df['200_SMA'].item())
    ABS_Spread = max_SMA - min_SMA
    stock_df['Spread%'] = round((ABS_Spread / stock_df['200_SMA'].item()) * 100,2)

    return stock_df

# function to compute stock attributes
def get_common_features(stock_ids, df_mypf):

  df_prec_dev = pd.DataFrame()
  df_tmp = get_screener_features()
  df_rs = get_relative_strength(stock_ids)

  for stock_id in stock_ids:
      tmp = stock_prec_dev(stock_id)
      tmp = tmp.reset_index()
      df_prec_dev = pd.concat([df_prec_dev, tmp], ignore_index = True)
  df_prec_dev = pd.merge(df_prec_dev, df_mypf, on= 'Symbol')
  df_prec_dev = pd.merge(df_prec_dev, df_tmp, on= 'Symbol', how='left')
  df_prec_dev = pd.merge(df_prec_dev, df_rs, on= 'Symbol', how='left')
  #print(df_prec_dev.columns)
  df_prec_dev['Curr_PE'] = round(df_prec_dev['Close']/df_prec_dev['EPS'],1)
  df_prec_dev['Dev%_PE'] = round((df_prec_dev['Curr_PE'] - df_prec_dev['MedPE'])*100/df_prec_dev['MedPE'],2)
  df_prec_dev['Conviction'] = df_prec_dev['Conviction'] + '-' + df_prec_dev['CapType']
  return df_prec_dev

# function to arrange stock features
def arrange_features(df_stocks, common_cols, diff_cols):
  df_stocks_common = df_stocks[common_cols].drop_duplicates()
  df_stocks_diff = df_stocks[diff_cols]
  df_stocks_diff['Investment'] = df_stocks_diff['AvgCost'] * df_stocks_diff['Shares']
  df_stocks_diff = df_stocks_diff.groupby(['Symbol'])[['Shares', 'Investment']].aggregate(['sum']).reset_index()
  df_stocks_diff.columns = ['Symbol', 'Shares', 'Investment']
  df_stocks_diff['AvgCost'] = round(df_stocks_diff['Investment']/df_stocks_diff['Shares'],2)
  df_stocks = pd.merge(df_stocks_diff, df_stocks_common, on='Symbol')
  return df_stocks

# plot fact distribution across dimension
def plot_pie_chart(df, dimension, fact):
  # grouping the data by category and calculating the sum of fact for each type
  grouped_data = df.groupby(dimension)[fact].sum()

  # sorting the grouped data in descending order
  grouped_data = grouped_data.sort_values(ascending=False)

  # creating a pie chart
  grouped_data.plot.pie(autopct='%1.1f%%', startangle=90, figsize=(6, 6))

  # adding a title and displaying the plot
  plt.title(f'{dimension} {fact} Distribution')
  plt.ylabel('')  # To hide the y-label
  plt.show()

In [7]:
# function to get portfolio features

def get_portfolio_features(df_common_features):

  print_date_time()
  print('-------------------')

  #df_common_features["Target"] = df_common_features["Target"].fillna(df_common_features["Max"])
  df_common_features['NTT'] = np.where(df_common_features['Strategy']== 'NTT', df_common_features["Target"], df_common_features['Max'])
  df_common_features['LTT'] = np.where(df_common_features['Strategy']== 'BTT', df_common_features["Target"], df_common_features['Max'])
  df_common_features['BOL'] = df_common_features['Min']

  tmp_df = df_common_features[df_common_features['Symbol'].isin(mypf_df[mypf_df['InPortfolio'] != 'NA'].Symbol.values)]
  print('qualified stocks: '+str(len(tmp_df['Symbol'].unique())))
  tmp_df1 = tmp_df[tmp_df['LatestQtr'] == 1]
  print('with latest results: '+str(len(tmp_df1['Symbol'].unique())))
  tmp_df1 = tmp_df1[tmp_df1['StarStock'] == 1]
  print('still star stocks: '+str(len(tmp_df1['Symbol'].unique())))
  tmp_df['Investment'] = tmp_df['AvgCost'] * tmp_df['Shares']
  tmp_df['Current'] = round(tmp_df['Close'] * tmp_df['Shares'],0)
  tmp_df['Previous'] = tmp_df['Prev_Close'] * tmp_df['Shares']
  tmp_df['EstimatedST'] = tmp_df['NTT'] * tmp_df['Shares']
  tmp_df['EstimatedLT'] = tmp_df['LTT'] * tmp_df['Shares']
  tmp_df['Current P/L'] = round((tmp_df['Current'] - tmp_df['Investment']),0)
  tmp_df['Today P/L%'] = round((tmp_df['Current'] - tmp_df['Previous'])*100/tmp_df['Previous'],2)
  tmp_df['Current P/L%'] = round((tmp_df['Current'] - tmp_df['Investment'])*100/tmp_df['Investment'],2)
  tmp_df['EstimatedST P/L%'] = round((tmp_df['EstimatedST'] - tmp_df['Investment'])*100/tmp_df['Investment'],2)
  tmp_df['EstimatedLT P/L%'] = round((tmp_df['EstimatedLT'] - tmp_df['Investment'])*100/tmp_df['Investment'],2)
  tmp_df['NTT%'] = round((tmp_df['NTT'] - tmp_df['Close'])*100/tmp_df['Close'],2)
  tmp_df['LTT%'] = round((tmp_df['LTT'] - tmp_df['Close'])*100/tmp_df['Close'],2)
  tmp_df['Gained%'] = round((tmp_df['Close'] - tmp_df['BOL'])*100/tmp_df['BOL'],2)
  investment = round(sum(tmp_df['AvgCost']*tmp_df['Shares']),0)
  current = round(sum(tmp_df['Close']*tmp_df['Shares']),0)
  tmp_df['InitAlloc%'] = round(tmp_df['Investment']*100/investment,2)
  tmp_df['CurrAlloc%'] = round(tmp_df['Current']*100/current,2)
  tmp_df['FTT'] = tmp_df['LTT']
  tmp_df.loc[tmp_df['Strategy'] == 'NTT', 'FTT'] = tmp_df['NTT']
  tmp_df['FTT%'] = tmp_df['LTT%']
  tmp_df.loc[tmp_df['Strategy'] == 'NTT', 'FTT%'] = tmp_df['NTT%']
  tmp_df['FTT Amt'] = round(tmp_df['FTT%'] * tmp_df['Current']/100,0)
  tmp_df['OTT%'] = round((tmp_df['FTT'] - tmp_df['AvgCost'])*100/tmp_df['AvgCost'],2)
  tmp_df['RRR Ind'] = round(tmp_df['Current P/L']/tmp_df['FTT Amt'],2)
  tmp_df['Risk Ind'] = round(tmp_df['Current P/L%']*tmp_df['CurrAlloc%'],0)

  return tmp_df

# function to print portfolio features
def print_portfolio_stats(df_portfolio_features, myinvmt_df):
  from pyxirr import xirr

  total_booked_amt, reserve_amt, cy_booked_amt, py_booked_amt = get_amt()

  dates = myinvmt_df['Date'].values
  dates = np.append(dates, datetime.date.today().strftime('%d-%b-%y'))
  investment = myinvmt_df['Investment'].values
  dates= pd.to_datetime(dates)

  current = round(sum(df_portfolio_features['Close']*df_portfolio_features['Shares']),0) + reserve_amt
  investment_xirr = np.append(investment, current)
  cagr = round(xirr(pd.DataFrame({"dates": dates, "amounts": investment_xirr}))*100,2)

  investment = -sum(investment)
  invested = round(sum(df_portfolio_features['AvgCost']*df_portfolio_features['Shares']),0) + reserve_amt
  previous = round(sum(df_portfolio_features['Prev_Close']*df_portfolio_features['Shares']),0) + reserve_amt
  cy_invested = investment + py_booked_amt

  today_pnl_amount = current-previous
  today_pnl_percentage = round((current-previous)*100/previous,2)

  curr_pnl_amount = current-invested
  curr_pnl_percentage = round((curr_pnl_amount)*100/(cy_invested),2)

  cy_pnl_amount = cy_booked_amt + curr_pnl_amount
  cy_pnl_percentage = round((cy_pnl_amount)*100/cy_invested,2)

  overall_pnl_amount = total_booked_amt + curr_pnl_amount
  overall_pnl_percentage = round((overall_pnl_amount)*100/investment,2)

  estimate_st = round(sum(df_portfolio_features['FTT']*df_portfolio_features['Shares']),0)  + reserve_amt
  est_st_pnl_amount = estimate_st-current
  est_st_pnl_percentage = round((est_st_pnl_amount)*100/current,2)

  estimate_lt = round(sum(df_portfolio_features['LTT']*df_portfolio_features['Shares']),0)  + reserve_amt
  est_lt_pnl_amount = estimate_lt-current
  est_lt_pnl_percentage = round((est_lt_pnl_amount)*100/current,2)

  total_profit = round(sum(df_portfolio_features[df_portfolio_features['Current P/L%'] > 0]['Current']) - sum(df_portfolio_features[df_portfolio_features['Current P/L%'] > 0]['Investment']),0)
  total_loss = round(sum(df_portfolio_features[df_portfolio_features['Current P/L%'] < 0]['Current']) - sum(df_portfolio_features[df_portfolio_features['Current P/L%'] < 0]['Investment']),0)

  cy_booked_percentage = round((cy_booked_amt)*100/current,2)
  py_booked_percentage = round((py_booked_amt)*100/investment,2)
  total_booked_percentage = round((total_booked_amt)*100/investment,2)

  print('-------------------')
  print('Initial Investment: ', format_amt(investment))
  print('CY Investment: ', format_amt(cy_invested))
  print('Reserve: ', format_amt(reserve_amt))
  print('Current: ',  format_amt(current))
  print('-------------------')
  print('Today PnL: '+ '{} ({}%)'.format(format_amt(today_pnl_amount), today_pnl_percentage))
  print('Current PnL: '+ '{} ({}%)'.format(format_amt(curr_pnl_amount), curr_pnl_percentage))
  print('CY Booked + Current PnL: '+ '{} ({}%)'.format(format_amt(cy_pnl_amount), cy_pnl_percentage))
  print('-------------------')
  print('Total profit: ', format_amt(total_profit))
  print('Total loss: ', format_amt(total_loss))
  print('-------------------')
  print('Total Booked + Current PnL: '+ '{} ({}%)'.format(format_amt(overall_pnl_amount), overall_pnl_percentage))
  print('Total Booked PnL: '+ '{} ({}%)'.format(format_amt(total_booked_amt), total_booked_percentage))
  print('Curr Year Booked PnL: '+ '{} ({}%)'.format(format_amt(cy_booked_amt), cy_booked_percentage))
  print('Prev Year Booked PnL: '+ '{} ({}%)'.format(format_amt(py_booked_amt), py_booked_percentage))
  print('===================')
  print('Est FTT: ',  format_amt(estimate_st))
  print('Est FTT PnL: '+ '{} ({}%)'.format(format_amt(est_st_pnl_amount), est_st_pnl_percentage))

  print('===================')
  print('Deployed: ', format_amt(investment))

  print('Current: ', format_amt(current))

  print('CAGR/XIRR %: '+'{}%'.format(cagr))

In [8]:
# get start and end date
start_date, end_date = get_start_end_date()

# get portfolio and prospects data
mypfs_df = get_mypfs_df()
mypps_df = get_mypps_df()
myinvmt_df = get_myinvmt_df()

# merge above datasets
mypf_df = pd.merge(mypfs_df, mypps_df, on="Symbol")

# seggregate dm and sv portfolio
dm_pf = mypf_df[mypf_df['InPortfolio'] == 'DM']
sv_pf = mypf_df[mypf_df['InPortfolio'] == 'SV']

# build portfolio stock dataframe
dm_stocks = get_stock_ids(dm_pf)
sv_stocks = get_stock_ids(sv_pf)
df_stocks = pd.concat([dm_pf,sv_pf], ignore_index = True)

# arrange common and diff stock features
common_cols = ['Symbol', 'Target', 'Criteria', 'Strategy', 'CumlRnk', 'LatestQtr', 'StarStock', 'Conviction', 'Category', 'InFolio', 'XIRR', 'MBQ']
diff_cols = ['Symbol', 'AvgCost', 'Shares']
df_stocks = arrange_features(df_stocks, common_cols, diff_cols)

# get common features
stock_ids = df_stocks['Symbol'].values
df_common_features = get_common_features(stock_ids, df_stocks)

df_common_features.reset_index(drop=True, inplace=True)
df_common_features.drop(['Date'], axis=1, inplace=True)
# get and print portfolio features
df_portfolio_features = get_portfolio_features(df_common_features)

print_portfolio_stats(df_portfolio_features, myinvmt_df)

df = df_portfolio_features
#plot_pie_chart(df, 'CapType', 'Current')
list_ox40n = list(df[df['MBQ'].str.contains('OX40N', na=False)]['Symbol'].values)

Run date time (IST): 2026-03-09 12:12:12
-------------------
qualified stocks: 86
with latest results: 26
still star stocks: 15
-------------------
Initial Investment:  1.36 C
CY Investment:  1.62 C
Reserve:  66.25 K
Current:  1.35 C
-------------------
Today PnL: -3.16 L (-2.3%)
Current PnL: -42.41 L (-26.1%)
CY Booked + Current PnL: -26.73 L (-16.45%)
-------------------
Total profit:  88.24 K
Total loss:  -43.29 L
-------------------
Total Booked + Current PnL: 25.35 K (0.19%)
Total Booked PnL: 42.66 L (31.48%)
Curr Year Booked PnL: 15.68 L (11.66%)
Prev Year Booked PnL: 26.98 L (19.91%)
===================
Est FTT:  2.47 C
Est FTT PnL: 1.13 C (83.83%)
===================
Deployed:  1.36 C
Current:  1.35 C
CAGR/XIRR %: -0.37%

In [9]:
# top 5 near their targets
cols = ['Symbol', 'Today P/L%', 'Current P/L%', 'FTT%', 'OTT%', 'FTT Amt', 'Current P/L', 'Current', 'FTT', 'Dev%_PE', 'RSI_14','Conviction', 'Spread%',  'CumlRnk', 'RRR Ind', 'CurrAlloc%', 'Gained%', 'Criteria', 'Strategy', 'Category']
df_tmp = df_portfolio_features[~df_portfolio_features['Symbol'].isin(['ENRIN','BLUSPRING','DIGITIDE'])]
df_tmp = df_tmp.sort_values(by = 'FTT Amt', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
19,COALINDIA,-0.87,7.37,9.60,17.67,15508.0,11082.0,161542.0,478.51,29.12,56.0,L-LC,11.29,185.0,0.71,1.21,25.45,XY25,ATH,MINING
50,MASFIN,-1.60,-9.34,34.09,21.57,30282.0,-9150.0,88830.0,397.04,-21.86,32.0,H-SC,5.38,167.0,-0.30,0.66,23.95,XR,ATH,FINANCE
37,ICICIGI,-0.74,-1.14,20.72,19.34,40990.0,-2281.0,197828.0,2252.93,-16.89,43.0,X-MC,1.56,66.0,-0.06,1.48,12.83,X40,ATH,INSURANCE
77,TTKPRESTIG,-3.14,-40.96,69.53,0.09,41370.0,-41277.0,59500.0,770.00,38.10,17.0,M-SC,14.27,250.0,-1.00,0.44,0.00,OX40N,NTT,DURABLES
2,ABBOTINDIA,-0.53,-8.82,29.49,18.07,48092.0,-15775.0,163080.0,35195.00,-22.40,52.0,X-MC,11.09,58.0,-0.33,1.22,3.39,X40,ATH,PHARMA

In [10]:
# top 5 today
df_tmp = df_portfolio_features.sort_values(by = 'Today P/L%', ascending=False)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
70,SYMPHONY,0.99,-41.65,71.31,-0.03,71216.0,-71273.0,99868.0,1306.00,-53.10,29.0,M-SC,12.07,205.0,-1.00,0.75,0.99,OX40N,NTT,DURABLES
25,DMART,0.94,-5.96,37.81,29.60,88752.0,-14868.0,234732.0,5391.45,-20.67,56.0,X-LC,7.73,14.0,-0.17,1.75,8.56,X40N,ATH,FMCG
31,HAPPSTMNDS,0.70,-57.57,335.70,84.85,182540.0,-73789.0,54376.0,1480.71,-49.60,26.0,H-SC,29.02,152.0,-0.40,0.41,0.70,AR,ATH,IT
84,WIPRO,0.59,-19.38,113.69,72.27,155303.0,-32846.0,136602.0,420.00,-27.37,23.0,M-LC,13.31,98.0,-0.21,1.02,0.59,XR,NTT,IT
40,INDIAMART,0.23,-8.67,126.34,106.72,142317.0,-10690.0,112646.0,4810.62,-58.79,42.0,H-SC,8.96,140.0,-0.08,0.84,12.68,AR,ATH,MISC

In [11]:
# bottom 5 today
df_tmp = df_portfolio_features.sort_values(by = 'Today P/L%', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
75,TMPV,-5.52,-24.56,81.05,36.58,217566.0,-87407.0,268434.0,600.0,-84.72,30.0,X-LC,2.68,4.0,-0.40,2.01,0.00,XY24,NTT,AUTO
7,ATULAUTO,-5.26,-27.25,100.09,45.57,143541.0,-53720.0,143412.0,844.0,3094.59,37.0,M-SC,7.28,248.0,-0.37,1.07,8.53,XY24,NTT,AUTO
55,RAJESHEXPO,-5.00,-78.18,358.61,0.07,107339.0,-107245.0,29932.0,518.0,997.22,18.0,L-SC,15.34,268.0,-1.00,0.22,0.00,OX40N,NTT,JEWELLERY
11,BANDHANBNK,-4.75,-16.14,129.45,92.42,302398.0,-44957.0,233602.0,400.0,100.43,54.0,H-SC,9.83,174.0,-0.15,1.75,28.69,XY24,NTT,BANKS
74,TITAGARH,-4.60,-38.90,138.52,45.74,204971.0,-94205.0,147972.0,1548.0,-18.55,29.0,H-SC,14.61,175.0,-0.46,1.11,1.10,XY24,NTT,ENGINEERING

In [12]:
# top 5 to exit based on CumlRnk
df_tmp = df_portfolio_features[~df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])]
df_tmp = df_tmp[(df_tmp['Current P/L%'] > -1) & (df_tmp['Current P/L%'] < 1)].sort_values(by = 'CumlRnk', ascending=False)
df_tmp[cols].head()

Empty DataFrame
Columns: [Symbol, Today P/L%, Current P/L%, FTT%, OTT%, FTT Amt, Current P/L, Current, FTT, Dev%_PE, RSI_14, Conviction, Spread%, CumlRnk, RRR Ind, CurrAlloc%, Gained%, Criteria, Strategy, Category]
Index: []

In [13]:
# OX40N stocks to exit
df_tmp = df_portfolio_features[(df_portfolio_features['Symbol'].isin(list_ox40n))].sort_values(by = 'Current P/L%', ascending=False)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
27,FINCABLES,-1.06,21.41,71.25,107.91,127715.0,31605.0,179249.0,1641.55,9.08,69.0,M-SC,7.21,220.0,0.25,1.34,34.86,OX40N,ATH,CABLES
66,SIS,-4.01,-34.33,84.65,21.26,61724.0,-38115.0,72917.0,528.00,1706.74,32.0,H-SC,8.37,168.0,-0.62,0.54,0.52,OX40N,NTT,MISC
48,KANSAINER,-2.65,-38.53,84.60,13.47,140235.0,-103905.0,165762.0,340.00,-47.26,22.0,H-SC,15.62,162.0,-0.74,1.24,0.00,XY24,NTT,PAINTS
72,TATAELXSI,-1.60,-38.59,115.00,32.03,93103.0,-50876.0,80959.0,9161.00,-23.22,25.0,H-SC,15.18,158.0,-0.55,0.60,0.00,OX40N,NTT,IT
18,CERA,-3.00,-39.85,105.98,23.89,112127.0,-70103.0,105800.0,9475.00,-42.00,25.0,H-SC,15.62,153.0,-0.63,0.79,0.00,OX40N,NTT,CERAMICS

In [14]:
# top 5 to book for rotation
df_tmp = df_portfolio_features[(df_portfolio_features['Current P/L%'] > 20) ].sort_values(by = 'CumlRnk', ascending=False)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
27,FINCABLES,-1.06,21.41,71.25,107.91,127715.0,31605.0,179249.0,1641.55,9.08,69.0,M-SC,7.21,220.0,0.25,1.34,34.86,OX40N,ATH,CABLES

In [15]:
# top 5 to monitor for exit
df_tmp = df_portfolio_features[~df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])]
df_tmp = df_tmp[(df_tmp['Current P/L%'] > 0) ].sort_values(by = 'Dev%_PE', ascending=False)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
19,COALINDIA,-0.87,7.37,9.60,17.67,15508.0,11082.0,161542.0,478.51,29.12,56.0,L-LC,11.29,185.0,0.71,1.21,25.45,XY25,ATH,MINING
27,FINCABLES,-1.06,21.41,71.25,107.91,127715.0,31605.0,179249.0,1641.55,9.08,69.0,M-SC,7.21,220.0,0.25,1.34,34.86,OX40N,ATH,CABLES
1,ABB,-2.81,8.09,34.67,45.57,98044.0,21173.0,282792.0,7934.00,-30.51,54.0,H-MC,9.30,125.0,0.22,2.11,25.58,AR,NTT,ELECTRICAL

In [16]:
# top 5 to book for rotation from weak conviction
df_tmp = df_portfolio_features[~df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])]
df_tmp = df_tmp[~df_tmp['Criteria'].isin(['XY25','XY24','X40', 'X40N'])].sort_values(by = 'RRR Ind', ascending=False)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
27,FINCABLES,-1.06,21.41,71.25,107.91,127715.0,31605.0,179249.0,1641.55,9.08,69.0,M-SC,7.21,220.0,0.25,1.34,34.86,OX40N,ATH,CABLES
1,ABB,-2.81,8.09,34.67,45.57,98044.0,21173.0,282792.0,7934.00,-30.51,54.0,H-MC,9.30,125.0,0.22,2.11,25.58,AR,NTT,ELECTRICAL
40,INDIAMART,0.23,-8.67,126.34,106.72,142317.0,-10690.0,112646.0,4810.62,-58.79,42.0,H-SC,8.96,140.0,-0.08,0.84,12.68,AR,ATH,MISC
85,ZYDUSLIFE,-2.10,-5.74,43.88,35.63,86686.0,-12022.0,197552.0,1286.17,-18.02,46.0,H-MC,5.14,120.0,-0.14,1.48,9.98,AR,ATH,PHARMA
84,WIPRO,0.59,-19.38,113.69,72.27,155303.0,-32846.0,136602.0,420.00,-27.37,23.0,M-LC,13.31,98.0,-0.21,1.02,0.59,XR,NTT,IT

In [17]:
# top 5 to accumulate based on lowest RSI_14
df_tmp = df_portfolio_features[df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])].sort_values(by = 'RSI_14', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
8,AWL,-0.70,-39.39,175.57,67.02,379147.0,-140357.0,215952.0,485.00,-67.43,12.0,X-SC,21.76,81.0,-0.37,1.61,0.00,XY24,NTT,FMCG
53,PGHH,-2.00,-20.07,65.15,32.01,111193.0,-42848.0,170672.0,17616.87,-45.92,14.0,X-MC,10.57,57.0,-0.39,1.28,0.00,X40,ATH,FMCG
3,ACC,-3.48,-35.15,169.58,74.81,294845.0,-94260.0,173868.0,3906.00,-53.87,17.0,X-SC,11.17,85.0,-0.32,1.30,0.00,XY24,BTT,CEMENT
9,BAJAJHFL,-2.25,-26.53,120.67,62.13,242074.0,-72438.0,200608.0,181.50,-39.53,21.0,X-MC,18.06,60.0,-0.30,1.50,0.00,X40N,ATH,FINANCE
46,JIOFIN,-3.99,-23.74,68.41,28.43,155634.0,-70825.0,227502.0,387.00,-24.95,21.0,X-LC,13.90,34.0,-0.46,1.70,7.79,XY24,BTT,FINANCE

In [18]:
# top 5 to accumulate based on Spread and CumlRnk
df_tmp = df_portfolio_features[df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])]
df_tmp = df_tmp[(df_tmp['CumlRnk'] < 100)].sort_values(by = 'Spread%', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
22,DABUR,-2.76,-9.01,57.93,43.70,130759.0,-22349.0,225719.0,735.00,-17.44,27.0,X-MC,0.96,70.0,-0.17,1.69,4.69,XY24,BTT,FMCG
78,UNITDSPR,-3.04,-1.01,22.00,20.77,50989.0,-2374.0,231770.0,1644.00,-12.17,45.0,X-MC,1.52,64.0,-0.05,1.73,5.63,X40N,NTT,BREWERIES
37,ICICIGI,-0.74,-1.14,20.72,19.34,40990.0,-2281.0,197828.0,2252.93,-16.89,43.0,X-MC,1.56,66.0,-0.06,1.48,12.83,X40,ATH,INSURANCE
59,RELIANCE,-0.42,-10.20,39.54,25.30,71353.0,-20505.0,180458.0,1952.00,-12.34,46.0,X-LC,2.14,21.0,-0.29,1.35,20.48,XY25,BTT,REFINERIES
75,TMPV,-5.52,-24.56,81.05,36.58,217566.0,-87407.0,268434.0,600.00,-84.72,30.0,X-LC,2.68,4.0,-0.40,2.01,0.00,XY24,NTT,AUTO

In [19]:
# top 5 to accumulate based on lowest Gained%
df_tmp = df_portfolio_features[df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])].sort_values(by = 'Gained%', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
3,ACC,-3.48,-35.15,169.58,74.81,294845.0,-94260.0,173868.0,3906.00,-53.87,17.0,X-SC,11.17,85.0,-0.32,1.30,0.0,XY24,BTT,CEMENT
10,BAJAJHLDNG,-3.09,-8.49,41.21,29.22,71696.0,-16147.0,173978.0,14451.52,-15.20,31.0,X-LC,11.90,28.0,-0.23,1.30,0.0,X40,ATH,FINANCE
9,BAJAJHFL,-2.25,-26.53,120.67,62.13,242074.0,-72438.0,200608.0,181.50,-39.53,21.0,X-MC,18.06,60.0,-0.30,1.50,0.0,X40N,ATH,FINANCE
8,AWL,-0.70,-39.39,175.57,67.02,379147.0,-140357.0,215952.0,485.00,-67.43,12.0,X-SC,21.76,81.0,-0.37,1.61,0.0,XY24,NTT,FMCG
12,BATAINDIA,-3.35,-53.63,191.58,35.20,114306.0,-69005.0,59665.0,2096.00,-21.73,21.0,X-SC,24.18,91.0,-0.60,0.45,0.0,X40,NTT,FOOTWEAR

In [20]:
# top 5 to accumulate based on lowest CurrAlloc%
df_tmp = df_portfolio_features[df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])].sort_values(by = 'CurrAlloc%', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
58,RELAXO,-1.74,-59.05,271.92,52.31,161646.0,-85714.0,59446.0,1176.00,-56.44,22.0,X-SC,17.51,92.0,-0.53,0.44,0.00,X40N,NTT,FOOTWEAR
12,BATAINDIA,-3.35,-53.63,191.58,35.20,114306.0,-69005.0,59665.0,2096.00,-21.73,21.0,X-SC,24.18,91.0,-0.60,0.45,0.00,X40,NTT,FOOTWEAR
54,QUESS,-3.11,-24.59,130.61,73.90,105182.0,-26262.0,80531.0,424.00,-59.23,31.0,X-SC,17.69,80.0,-0.25,0.60,0.00,XY24,NTT,MISC
36,HONAUT,-1.49,-23.46,97.69,51.31,144190.0,-45238.0,147600.0,58357.33,-36.31,28.0,X-SC,13.36,90.0,-0.31,1.10,0.00,X40N,ATH,ELECTRICAL
65,SIEMENS,-2.65,-14.50,46.79,25.51,74452.0,-26975.0,159120.0,4671.50,33.57,49.0,H-LC,3.36,51.0,-0.36,1.19,17.18,AR,ATH,ELECTRICAL

In [21]:
# top 5 to accumulate based on CumlRnk
df_tmp = df_portfolio_features.sort_values(by = 'CumlRnk', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
45,ITC,-1.24,-19.44,47.78,19.06,130937.0,-66124.0,274042.0,452.00,-55.92,33.0,X-LC,16.97,1.0,-0.51,2.05,0.00,X40,NTT,FMCG
73,TCS,-0.79,-25.51,69.93,26.57,241310.0,-118200.0,345073.0,4311.59,-37.07,25.0,X-LC,12.51,2.0,-0.49,2.58,0.00,X40,ATH,IT
43,INFY,-1.01,-11.83,52.25,34.24,144146.0,-37010.0,275878.0,1972.00,-30.70,27.0,X-LC,10.91,3.0,-0.26,2.06,1.54,X40,NTT,IT
75,TMPV,-5.52,-24.56,81.05,36.58,217566.0,-87407.0,268434.0,600.00,-84.72,30.0,X-LC,2.68,4.0,-0.40,2.01,0.00,XY24,NTT,AUTO
34,HCLTECH,0.02,-11.94,40.62,23.83,86541.0,-28875.0,213049.0,1908.19,-7.36,27.0,X-LC,8.69,8.0,-0.33,1.59,2.22,X40,ATH,IT

In [22]:
# top 5 for average up
df_tmp = df_portfolio_features[(df_portfolio_features['Dev%_200'] > 5)].sort_values(by = 'CurrAlloc%', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
42,INDUSINDBK,-4.28,-35.14,104.88,32.89,52521.0,-27130.0,50077.0,1800.00,-335.99,37.0,L-MC,11.88,258.0,-0.52,0.37,37.91,XR,NTT,BANKS
19,COALINDIA,-0.87,7.37,9.60,17.67,15508.0,11082.0,161542.0,478.51,29.12,56.0,L-LC,11.29,185.0,0.71,1.21,25.45,XY25,ATH,MINING
27,FINCABLES,-1.06,21.41,71.25,107.91,127715.0,31605.0,179249.0,1641.55,9.08,69.0,M-SC,7.21,220.0,0.25,1.34,34.86,OX40N,ATH,CABLES
11,BANDHANBNK,-4.75,-16.14,129.45,92.42,302398.0,-44957.0,233602.0,400.00,100.43,54.0,H-SC,9.83,174.0,-0.15,1.75,28.69,XY24,NTT,BANKS
1,ABB,-2.81,8.09,34.67,45.57,98044.0,21173.0,282792.0,7934.00,-30.51,54.0,H-MC,9.30,125.0,0.22,2.11,25.58,AR,NTT,ELECTRICAL

In [23]:
# top 5 RSP
df_tmp = df_portfolio_features.sort_values(by = 'RSP', ascending=False)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
27,FINCABLES,-1.06,21.41,71.25,107.91,127715.0,31605.0,179249.0,1641.55,9.08,69.0,M-SC,7.21,220.0,0.25,1.34,34.86,OX40N,ATH,CABLES
11,BANDHANBNK,-4.75,-16.14,129.45,92.42,302398.0,-44957.0,233602.0,400.00,100.43,54.0,H-SC,9.83,174.0,-0.15,1.75,28.69,XY24,NTT,BANKS
26,EASEMYTRIP,-3.87,-60.26,266.67,45.70,187357.0,-106557.0,70258.0,26.40,-27.06,41.0,M-SC,18.16,204.0,-0.57,0.52,15.76,XY24,NTT,TRAVEL
19,COALINDIA,-0.87,7.37,9.60,17.67,15508.0,11082.0,161542.0,478.51,29.12,56.0,L-LC,11.29,185.0,0.71,1.21,25.45,XY25,ATH,MINING
65,SIEMENS,-2.65,-14.50,46.79,25.51,74452.0,-26975.0,159120.0,4671.50,33.57,49.0,H-LC,3.36,51.0,-0.36,1.19,17.18,AR,ATH,ELECTRICAL

In [24]:
# Top N allocation
df_tmp = df_portfolio_features.sort_values(by = 'CurrAlloc%', ascending=False)
top_n_values = [10, 25, 50]

sum_df = pd.DataFrame({
    'Top_N': top_n_values,
    'Sum_Alloc%': [df_tmp['CurrAlloc%'].head(n).sum() for n in top_n_values]
})

sum_df

   Top_N  Sum_Alloc%
0     10       20.54
1     25       45.42
2     50       78.02

In [25]:
# market-cap-wise allocation
df_tmp = df_portfolio_features[cols]
df_tmp.groupby(df_tmp['Conviction'].str[-2:])['CurrAlloc%'].sum().sort_values(ascending=False)

Conviction
SC    44.37
MC    30.41
LC    25.23
Name: CurrAlloc%, dtype: float64

In [26]:
# criteria-wise allocation
df_portfolio_features.groupby('Criteria')['CurrAlloc%'].sum().sort_values(ascending=False)

Criteria
XY24     27.21
X40      24.14
X40N     15.04
AR        8.99
XY25      8.75
XR        8.18
OX40N     6.92
SR        0.78
Name: CurrAlloc%, dtype: float64

In [27]:
# conviction-wise allocation
df_portfolio_features.groupby('Conviction')['CurrAlloc%'].sum().sort_values(ascending=False)

Conviction
X-MC    23.15
X-LC    21.81
H-SC    21.48
X-SC    12.07
M-SC    10.23
H-MC     4.91
M-MC     1.98
L-LC     1.21
H-LC     1.19
M-LC     1.02
L-SC     0.59
L-MC     0.37
Name: CurrAlloc%, dtype: float64

In [28]:
# sector-wise stats
df_tmp = df_portfolio_features.groupby('Category')[['CurrAlloc%', 'Current', 'Current P/L', 'FTT Amt']].sum().sort_values(by=['Current', 'Current P/L'], ascending=False)
df_tmp['Current P/L%'] = round(df_tmp['Current P/L'] * 100 / df_tmp['Current'], 2)
df_tmp['FTT%'] = round(df_tmp['FTT Amt'] * 100 / df_tmp['Current'], 2)
cols = ['CurrAlloc%', 'Current P/L%', 'FTT%']
df_tmp[cols].sort_values(by=['CurrAlloc%'], ascending=False)

               CurrAlloc%  Current P/L%    FTT%
Category
FMCG                15.49        -20.58   63.39
FINANCE             12.69        -26.34   77.82
IT                  11.69        -43.86  117.08
MISC                 6.92        -44.71  107.58
ELECTRICAL           6.47        -11.74   54.53
PAINTS               5.22        -41.17   65.68
INSURANCE            4.76         -6.47   42.91
PHARMA               4.20         -4.80   37.79
AUTO                 3.73        -30.98   82.95
BANKS                3.10        -28.92  107.04
AC                   2.15        -11.12   41.25
HEALTHCARE           1.97        -35.58   70.95
FOOTWEAR             1.90        -73.94  143.69
TRAVEL               1.84        -81.61  172.54
DURABLES             1.78        -62.00  101.41
BREWERIES            1.73         -1.02   22.00
APPARELS             1.63        -23.38   65.47
REALTY               1.46        -13.57   32.23
CERAMICS             1.35        -69.56  121.08
REFINERIES           1.35        -11.36   39.54
CABLES               1.34         17.63   71.25
CEMENT               1.30        -54.21  169.58
MINING               1.21          6.86    9.60
JEWELLERY            1.11       -115.54  190.42
ENGINEERING          1.11        -63.66  138.52
CHEMICALS            0.95       -107.61  276.98
ENTERTAINMENT        0.77        -88.49  200.91
TEXTILES             0.42        -62.75  109.15
HOTELS               0.37       -128.17  208.64

In [29]:
# money to be made criteria-wise
df_portfolio_features.groupby('Criteria')['FTT Amt'].agg(['sum', 'count']).sort_values(by='sum', ascending=False)

                sum  count
Criteria
XY24      3956985.0     21
X40       1644998.0     15
XR        1394211.0     12
AR        1367634.0     10
X40N      1286586.0     10
OX40N      863974.0     10
XY25       447497.0      6
SR         314593.0      2

In [30]:
# money to be made conviction-wise
df_portfolio_features.groupby('Conviction')['FTT Amt'].agg(['sum', 'count']).sort_values(by='sum', ascending=False)

                  sum  count
Conviction
H-SC        3914714.0     24
X-MC        1638963.0     15
X-SC        1565957.0     10
X-LC        1556363.0     12
M-SC        1549079.0     14
H-MC         422370.0      3
L-SC         211171.0      2
M-LC         155303.0      1
M-MC         120077.0      2
H-LC          74452.0      1
L-MC          52521.0      1
L-LC          15508.0      1

In [31]:
# money to be made criteria and conviction-wise
df_portfolio_features.groupby(['Conviction', 'Criteria'])['FTT Amt'].agg(['sum', 'count']).sort_values(by='sum', ascending=False)

                           sum  count
Conviction Criteria
H-SC       XY24      1341222.0      6
           AR         977684.0      5
M-SC       XY24       913473.0      6
H-SC       XR         891191.0      7
X-SC       XY24       839808.0      4
X-LC       X40        801170.0      6
X-MC       X40        636635.0      7
           X40N       529950.0      4
X-SC       X40N       518956.0      4
H-SC       OX40N      390024.0      4
X-LC       XY24       373200.0      2
M-SC       OX40N      366611.0      5
H-SC       SR         314593.0      2
X-MC       XY24       251642.0      2
X-LC       X40N       237680.0      2
H-MC       XY24       237640.0      1
X-MC       XY25       220736.0      2
X-SC       X40        207193.0      2
M-SC       XR         191364.0      2
H-MC       AR         184730.0      2
M-LC       XR         155303.0      1
X-LC       XY25       144313.0      2
L-SC       OX40N      107339.0      1
           XR         103832.0      1
M-SC       AR          77631.0      1
H-LC       AR          74452.0      1
M-MC       XY25        66940.0      1
           AR          53137.0      1
L-MC       XR          52521.0      1
L-LC       XY25        15508.0      1

In [32]:
# notebook execution time

end_time = time.time()
execution_time = round(end_time - start_time, 0)
print(f"Notebook execution time: {execution_time} seconds")

Notebook execution time: 25.0 seconds