<a href="https://colab.research.google.com/github/ankit-rathi/Quantvesting_v2/blob/main/myStocks_Portfolio_Analysis.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
'''
!pip install pandas==2.2.2 -qq
!pip install pyxirr -qq
!pip install ta -qq
!pip install yfinance==0.2.59 -qq
'''

'\n!pip install pandas==2.2.2 -qq\n!pip install pyxirr -qq\n!pip install ta -qq\n!pip install yfinance==0.2.59 -qq\n'

In [2]:
# import libraries

import numpy as np
import pandas as pd
import datetime
import warnings
warnings.filterwarnings('ignore')
import yfinance as yfin
import ta
import matplotlib.pyplot as plt
import requests

In [3]:
# notebook start time
import time
import datetime
import pytz

start_time = time.time()

# function to print date timestamp
def print_date_time():
  tz_NY = pytz.timezone('Asia/Kolkata')
  datetime_NY = datetime.datetime.now(tz_NY)
  print("Run date time (IST):", datetime_NY.strftime("%Y-%m-%d %H:%M:%S"))

In [4]:
# function to get booked and reserved amount
def get_amt():
  # fetch the JSON data from the URL
  url = "https://raw.githubusercontent.com/ankit-rathi/Tradevesting_v1/main/data/myPortfolioAmts.json"
  response = requests.get(url)
  pf_amts = response.json()  # parse the JSON data

  # extract values from the JSON
  py_booked_amt_dm = pf_amts["py_booked_amt_dm"]
  py_booked_amt_sv = pf_amts["py_booked_amt_sv"]
  cy_booked_amt_dm = pf_amts["cy_booked_amt_dm"]
  cy_booked_amt_sv = pf_amts["cy_booked_amt_sv"]
  reserve_amt_dm = pf_amts["reserve_amt_dm"]
  reserve_amt_sv = pf_amts["reserve_amt_sv"]

  # perform calculations
  py_booked_amt = py_booked_amt_dm + py_booked_amt_sv
  cy_booked_amt = cy_booked_amt_dm + cy_booked_amt_sv
  reserve_amt = reserve_amt_dm + reserve_amt_sv
  total_booked_amt = py_booked_amt + cy_booked_amt

  return total_booked_amt, reserve_amt, cy_booked_amt, py_booked_amt

gen_output = 0

In [5]:
# function to format the amount
def format_amt(number):
    abs_number = abs(number)

    if abs_number >= 1_00_00_000:  # Crores
        formatted_amt = f"{number / 1_00_00_000:.2f} C"
    elif abs_number >= 1_00_000:  # Lakhs
        formatted_amt = f"{number / 1_00_000:.2f} L"
    elif abs_number >= 1_000:  # Thousands
        formatted_amt = f"{number / 1_000:.2f} K"
    else:
        formatted_amt = f"{number:.2f}"

    return formatted_amt

# function to set start and end date
def get_start_end_date():
  start_date = (datetime.date.today() + datetime.timedelta(days=-365)).strftime('%Y-%m-%d')
  end_date = (datetime.date.today() + datetime.timedelta(days=1)).strftime('%Y-%m-%d')
  return start_date, end_date

# function to fetch my portfolio csv
def get_mypfs_df():
  mypfs_df = pd.read_csv('https://raw.githubusercontent.com/ankit-rathi/Tradevesting_v1/main/data/myPortfolioStocks.csv')
  return mypfs_df

# function to fetch my prospects csv
def get_mypps_df():
  mypps_df = pd.read_csv('https://raw.githubusercontent.com/ankit-rathi/Tradevesting_v1/main/data/myProspectsScrips.csv')
  return mypps_df

# function to fetch screener data
def get_myscreen_df():
  myscreen_df = pd.read_csv('https://raw.githubusercontent.com/ankit-rathi/Tradevesting_v1/main/data/myScreenerDB.csv')
  return myscreen_df

# function to fetch momentum data
def get_myinvmt_df():
  myinvmt_df = pd.read_csv('https://raw.githubusercontent.com/ankit-rathi/Tradevesting_v1/main/data/myInvestments.csv')
  return myinvmt_df

# function to get the stock ids
def get_stock_ids(df_pf):
  stock_n100 = df_pf['Symbol'].unique()

  exclude = ['CADILAHC','MMTC', 'MASFIN']

  stock_ids = df_pf[~df_pf['Symbol'].isin(exclude) ]['Symbol'].unique()

  #mypf = mypf[mypf.Forecast.notnull()]
  #stock_ids = mypf['Symbol'].unique()

  #stock_ids.sort()
  return stock_ids

# get features from screener data
def get_screener_features():
  myscreen_df = get_myscreen_df()
  cols = ['Symbol', 'EPS', 'MedPE', 'ROCE%', 'ROE%', 'CapType']
  return myscreen_df[cols]

# get relative strength
def get_relative_strength(stock_list):

    # Dictionary to store stock tickers and their corresponding percentage price change
    stock_changes = {}

    # Loop through each stock and fetch its price data
    for stock in stock_list:
        try:
            # Download the stock data for the given date range
            stock_data = yfin.Ticker(stock + '.NS').history(period='1mo', interval='1d')[map(str.title, ['open', 'close', 'low', 'high', 'volume'])]

            # Calculate the percentage change for the stock
            if len(stock_data) > 0:
                start_price = stock_data['Close'].iloc[0]
                end_price = stock_data['Close'].iloc[-1]
                percent_change = round(((end_price - start_price) / start_price) * 100, 2)
                stock_changes[stock] = percent_change
            else:
                stock_changes[stock] = np.nan  # If no data is available, set to NaN

        except Exception as e:
            print(f"Error fetching data for {stock}: {e}")
            stock_changes[stock] = np.nan

    # Create a DataFrame with stock tickers and their percentage changes
    df = pd.DataFrame(list(stock_changes.items()), columns=['Symbol', 'Percent_Change'])

    # Drop any stocks with missing data (NaN values)
    df = df.dropna()

    # Calculate the percentile rank based on percentage change
    df['RSP'] = round(df['Percent_Change'].rank(pct=True) * 100, 2)
    cols = ['Symbol', 'RSP']
    df = df[cols]
    # Sort by percentile rank (optional)
    df = df.sort_values(by='RSP', ascending=False).reset_index(drop=True)

    return df

In [6]:
# function to get stock technicals
def stock_prec_dev(stock_symbol):
    #stock_symbol = 'ULTRACEMCO.NS'
    short_window = 20
    mid_window = 50
    long_window = 200
    moving_avg = 'SMA'

    start = datetime.datetime(*map(int, start_date.split('-')))
    end = datetime.datetime(*map(int, end_date.split('-')))

    stock_df = yfin.Ticker(stock_symbol + '.NS').history(period='max', interval='1d')[map(str.title, ['open', 'close', 'low', 'high', 'volume'])]

    stock_df['Max'] = round(max(stock_df['Close']),2)
    stock_df = stock_df[(stock_df.index <= end_date) & (stock_df.index >= start_date)]
    stock_df['200_SMA'] = round(stock_df['Close'].rolling(window = 200, min_periods = 1).mean(),0)
    stock_df['Dev%_200'] = round((stock_df['Close'] - stock_df['200_SMA'])*100/stock_df['200_SMA'],2)
    stock_df.dropna(axis = 0, inplace = True) # remove any null rows

    stock_df['20_SMA'] = stock_df['Close'].rolling(window=20).mean()
    stock_df['50_SMA'] = stock_df['Close'].rolling(window=50).mean()
    stock_df['Symbol'] = stock_symbol

    stock_df['Close'] = round(stock_df['Close'],2)
    stock_df['Min'] = round(min(stock_df['Close']),2)
    stock_df['RSI_14'] = ta.momentum.RSIIndicator(close=stock_df['Close'], window=14).rsi()
    stock_df['RSI_14'] = round(stock_df['RSI_14'],0)
    stock_df['Prev_Close'] = stock_df['Close'].shift(1)
    stock_df.drop(['Open', 'Low', 'High', 'Volume'], axis=1, inplace=True)
    stock_df = stock_df.tail(1)

    max_SMA = max(stock_df['20_SMA'].item(), stock_df['50_SMA'].item(), stock_df['200_SMA'].item())
    min_SMA = min(stock_df['20_SMA'].item(), stock_df['50_SMA'].item(), stock_df['200_SMA'].item())
    ABS_Spread = max_SMA - min_SMA
    stock_df['Spread%'] = round((ABS_Spread / stock_df['200_SMA'].item()) * 100,2)

    return stock_df

# function to compute stock attributes
def get_common_features(stock_ids, df_mypf):

  df_prec_dev = pd.DataFrame()
  df_tmp = get_screener_features()
  df_rs = get_relative_strength(stock_ids)

  for stock_id in stock_ids:
      tmp = stock_prec_dev(stock_id)
      tmp = tmp.reset_index()
      df_prec_dev = pd.concat([df_prec_dev, tmp], ignore_index = True)
  df_prec_dev = pd.merge(df_prec_dev, df_mypf, on= 'Symbol')
  df_prec_dev = pd.merge(df_prec_dev, df_tmp, on= 'Symbol', how='left')
  df_prec_dev = pd.merge(df_prec_dev, df_rs, on= 'Symbol', how='left')
  #print(df_prec_dev.columns)
  df_prec_dev['Curr_PE'] = round(df_prec_dev['Close']/df_prec_dev['EPS'],1)
  df_prec_dev['Dev%_PE'] = round((df_prec_dev['Curr_PE'] - df_prec_dev['MedPE'])*100/df_prec_dev['MedPE'],2)
  df_prec_dev['Conviction'] = df_prec_dev['Conviction'] + '-' + df_prec_dev['CapType']
  return df_prec_dev

# function to arrange stock features
def arrange_features(df_stocks, common_cols, diff_cols):
  df_stocks_common = df_stocks[common_cols].drop_duplicates()
  df_stocks_diff = df_stocks[diff_cols]
  df_stocks_diff['Investment'] = df_stocks_diff['AvgCost'] * df_stocks_diff['Shares']
  df_stocks_diff = df_stocks_diff.groupby(['Symbol'])[['Shares', 'Investment']].aggregate(['sum']).reset_index()
  df_stocks_diff.columns = ['Symbol', 'Shares', 'Investment']
  df_stocks_diff['AvgCost'] = round(df_stocks_diff['Investment']/df_stocks_diff['Shares'],2)
  df_stocks = pd.merge(df_stocks_diff, df_stocks_common, on='Symbol')
  return df_stocks

# plot fact distribution across dimension
def plot_pie_chart(df, dimension, fact):
  # grouping the data by category and calculating the sum of fact for each type
  grouped_data = df.groupby(dimension)[fact].sum()

  # sorting the grouped data in descending order
  grouped_data = grouped_data.sort_values(ascending=False)

  # creating a pie chart
  grouped_data.plot.pie(autopct='%1.1f%%', startangle=90, figsize=(6, 6))

  # adding a title and displaying the plot
  plt.title(f'{dimension} {fact} Distribution')
  plt.ylabel('')  # To hide the y-label
  plt.show()

In [7]:
# function to get portfolio features

def get_portfolio_features(df_common_features):

  print_date_time()
  print('-------------------')

  #df_common_features["Target"] = df_common_features["Target"].fillna(df_common_features["Max"])
  df_common_features['NTT'] = np.where(df_common_features['Strategy']== 'NTT', df_common_features["Target"], df_common_features['Max'])
  df_common_features['LTT'] = np.where(df_common_features['Strategy']== 'BTT', df_common_features["Target"], df_common_features['Max'])
  df_common_features['BOL'] = df_common_features['Min']

  tmp_df = df_common_features[df_common_features['Symbol'].isin(mypf_df[mypf_df['InPortfolio'] != 'NA'].Symbol.values)]
  print('qualified stocks: '+str(len(tmp_df['Symbol'].unique())))
  tmp_df1 = tmp_df[tmp_df['LatestQtr'] == 1]
  print('with latest results: '+str(len(tmp_df1['Symbol'].unique())))
  tmp_df1 = tmp_df1[tmp_df1['StarStock'] == 1]
  print('still star stocks: '+str(len(tmp_df1['Symbol'].unique())))
  tmp_df['Investment'] = tmp_df['AvgCost'] * tmp_df['Shares']
  tmp_df['Current'] = round(tmp_df['Close'] * tmp_df['Shares'],0)
  tmp_df['Previous'] = tmp_df['Prev_Close'] * tmp_df['Shares']
  tmp_df['EstimatedST'] = tmp_df['NTT'] * tmp_df['Shares']
  tmp_df['EstimatedLT'] = tmp_df['LTT'] * tmp_df['Shares']
  tmp_df['Current P/L'] = round((tmp_df['Current'] - tmp_df['Investment']),0)
  tmp_df['Today P/L%'] = round((tmp_df['Current'] - tmp_df['Previous'])*100/tmp_df['Previous'],2)
  tmp_df['Current P/L%'] = round((tmp_df['Current'] - tmp_df['Investment'])*100/tmp_df['Investment'],2)
  tmp_df['EstimatedST P/L%'] = round((tmp_df['EstimatedST'] - tmp_df['Investment'])*100/tmp_df['Investment'],2)
  tmp_df['EstimatedLT P/L%'] = round((tmp_df['EstimatedLT'] - tmp_df['Investment'])*100/tmp_df['Investment'],2)
  tmp_df['NTT%'] = round((tmp_df['NTT'] - tmp_df['Close'])*100/tmp_df['Close'],2)
  tmp_df['LTT%'] = round((tmp_df['LTT'] - tmp_df['Close'])*100/tmp_df['Close'],2)
  tmp_df['Gained%'] = round((tmp_df['Close'] - tmp_df['BOL'])*100/tmp_df['BOL'],2)
  investment = round(sum(tmp_df['AvgCost']*tmp_df['Shares']),0)
  current = round(sum(tmp_df['Close']*tmp_df['Shares']),0)
  tmp_df['InitAlloc%'] = round(tmp_df['Investment']*100/investment,2)
  tmp_df['CurrAlloc%'] = round(tmp_df['Current']*100/current,2)
  tmp_df['FTT'] = tmp_df['LTT']
  tmp_df.loc[tmp_df['Strategy'] == 'NTT', 'FTT'] = tmp_df['NTT']
  tmp_df['FTT%'] = tmp_df['LTT%']
  tmp_df.loc[tmp_df['Strategy'] == 'NTT', 'FTT%'] = tmp_df['NTT%']
  tmp_df['FTT Amt'] = round(tmp_df['FTT%'] * tmp_df['Current']/100,0)
  tmp_df['OTT%'] = round((tmp_df['FTT'] - tmp_df['AvgCost'])*100/tmp_df['AvgCost'],2)
  tmp_df['RRR Ind'] = round(tmp_df['Current P/L']/tmp_df['FTT Amt'],2)
  tmp_df['Risk Ind'] = round(tmp_df['Current P/L%']*tmp_df['CurrAlloc%'],0)

  return tmp_df

# function to print portfolio features
def print_portfolio_stats(df_portfolio_features, myinvmt_df):
  from pyxirr import xirr

  total_booked_amt, reserve_amt, cy_booked_amt, py_booked_amt = get_amt()

  dates = myinvmt_df['Date'].values
  dates = np.append(dates, datetime.date.today().strftime('%d-%b-%y'))
  investment = myinvmt_df['Investment'].values
  dates= pd.to_datetime(dates)

  current = round(sum(df_portfolio_features['Close']*df_portfolio_features['Shares']),0) + reserve_amt
  investment_xirr = np.append(investment, current)
  cagr = round(xirr(pd.DataFrame({"dates": dates, "amounts": investment_xirr}))*100,2)

  investment = -sum(investment)
  invested = round(sum(df_portfolio_features['AvgCost']*df_portfolio_features['Shares']),0) + reserve_amt
  previous = round(sum(df_portfolio_features['Prev_Close']*df_portfolio_features['Shares']),0) + reserve_amt
  cy_invested = investment + py_booked_amt

  today_pnl_amount = current-previous
  today_pnl_percentage = round((current-previous)*100/previous,2)

  curr_pnl_amount = current-invested
  curr_pnl_percentage = round((curr_pnl_amount)*100/(cy_invested),2)

  cy_pnl_amount = cy_booked_amt + curr_pnl_amount
  cy_pnl_percentage = round((cy_pnl_amount)*100/cy_invested,2)

  overall_pnl_amount = total_booked_amt + curr_pnl_amount
  overall_pnl_percentage = round((overall_pnl_amount)*100/investment,2)

  estimate_st = round(sum(df_portfolio_features['FTT']*df_portfolio_features['Shares']),0)  + reserve_amt
  est_st_pnl_amount = estimate_st-current
  est_st_pnl_percentage = round((est_st_pnl_amount)*100/current,2)

  estimate_lt = round(sum(df_portfolio_features['LTT']*df_portfolio_features['Shares']),0)  + reserve_amt
  est_lt_pnl_amount = estimate_lt-current
  est_lt_pnl_percentage = round((est_lt_pnl_amount)*100/current,2)

  total_profit = round(sum(df_portfolio_features[df_portfolio_features['Current P/L%'] > 0]['Current']) - sum(df_portfolio_features[df_portfolio_features['Current P/L%'] > 0]['Investment']),0)
  total_loss = round(sum(df_portfolio_features[df_portfolio_features['Current P/L%'] < 0]['Current']) - sum(df_portfolio_features[df_portfolio_features['Current P/L%'] < 0]['Investment']),0)

  cy_booked_percentage = round((cy_booked_amt)*100/current,2)
  py_booked_percentage = round((py_booked_amt)*100/investment,2)
  total_booked_percentage = round((total_booked_amt)*100/investment,2)

  print('-------------------')
  print('Initial Investment: ', format_amt(investment))
  print('CY Investment: ', format_amt(cy_invested))
  print('Reserve: ', format_amt(reserve_amt))
  print('Current: ',  format_amt(current))
  print('-------------------')
  print('Today PnL: '+ '{} ({}%)'.format(format_amt(today_pnl_amount), today_pnl_percentage))
  print('Current PnL: '+ '{} ({}%)'.format(format_amt(curr_pnl_amount), curr_pnl_percentage))
  print('CY Booked + Current PnL: '+ '{} ({}%)'.format(format_amt(cy_pnl_amount), cy_pnl_percentage))
  print('-------------------')
  print('Total profit: ', format_amt(total_profit))
  print('Total loss: ', format_amt(total_loss))
  print('-------------------')
  print('Total Booked + Current PnL: '+ '{} ({}%)'.format(format_amt(overall_pnl_amount), overall_pnl_percentage))
  print('Total Booked PnL: '+ '{} ({}%)'.format(format_amt(total_booked_amt), total_booked_percentage))
  print('Curr Year Booked PnL: '+ '{} ({}%)'.format(format_amt(cy_booked_amt), cy_booked_percentage))
  print('Prev Year Booked PnL: '+ '{} ({}%)'.format(format_amt(py_booked_amt), py_booked_percentage))
  print('===================')
  print('Est FTT: ',  format_amt(estimate_st))
  print('Est FTT PnL: '+ '{} ({}%)'.format(format_amt(est_st_pnl_amount), est_st_pnl_percentage))

  print('===================')
  print('Deployed: ', format_amt(investment))

  print('Current: ', format_amt(current))

  print('CAGR/XIRR %: '+'{}%'.format(cagr))

In [8]:
# get start and end date
start_date, end_date = get_start_end_date()

# get portfolio and prospects data
mypfs_df = get_mypfs_df()
mypps_df = get_mypps_df()
myinvmt_df = get_myinvmt_df()

# merge above datasets
mypf_df = pd.merge(mypfs_df, mypps_df, on="Symbol")

# seggregate dm and sv portfolio
dm_pf = mypf_df[mypf_df['InPortfolio'] == 'DM']
sv_pf = mypf_df[mypf_df['InPortfolio'] == 'SV']

# build portfolio stock dataframe
dm_stocks = get_stock_ids(dm_pf)
sv_stocks = get_stock_ids(sv_pf)
df_stocks = pd.concat([dm_pf,sv_pf], ignore_index = True)

# arrange common and diff stock features
common_cols = ['Symbol', 'Target', 'Criteria', 'Strategy', 'CumlRnk', 'LatestQtr', 'StarStock', 'Conviction', 'Category', 'InFolio', 'XIRR', 'MBQ']
diff_cols = ['Symbol', 'AvgCost', 'Shares']
df_stocks = arrange_features(df_stocks, common_cols, diff_cols)

# get common features
stock_ids = df_stocks['Symbol'].values
df_common_features = get_common_features(stock_ids, df_stocks)

df_common_features.reset_index(drop=True, inplace=True)
df_common_features.drop(['Date'], axis=1, inplace=True)
# get and print portfolio features
df_portfolio_features = get_portfolio_features(df_common_features)

print_portfolio_stats(df_portfolio_features, myinvmt_df)

df = df_portfolio_features
#plot_pie_chart(df, 'CapType', 'Current')
list_ox40n = list(df[df['MBQ'].str.contains('OX40N', na=False)]['Symbol'].values)

Run date time (IST): 2026-03-05 14:11:08
-------------------
qualified stocks: 86
with latest results: 26
still star stocks: 15
-------------------
Initial Investment:  1.33 C
CY Investment:  1.60 C
Reserve:  2.44 L
Current:  1.34 C
-------------------
Today PnL: 4.90 K (0.04%)
Current PnL: -40.09 L (-25.06%)
CY Booked + Current PnL: -24.41 L (-15.26%)
-------------------
Total profit:  95.98 K
Total loss:  -41.05 L
-------------------
Total Booked + Current PnL: 2.57 L (1.93%)
Total Booked PnL: 42.66 L (32.07%)
Curr Year Booked PnL: 15.68 L (11.67%)
Prev Year Booked PnL: 26.98 L (20.29%)
===================
Est FTT:  2.41 C
Est FTT PnL: 1.07 C (79.43%)
===================
Deployed:  1.33 C
Current:  1.34 C
CAGR/XIRR %: 0.5%

In [9]:
# top 5 near their targets
cols = ['Symbol', 'Today P/L%', 'Current P/L%', 'FTT%', 'OTT%', 'FTT Amt', 'Current P/L', 'Current', 'FTT', 'Dev%_PE', 'RSI_14','Conviction', 'Spread%',  'CumlRnk', 'RRR Ind', 'CurrAlloc%', 'Gained%', 'Criteria', 'Strategy', 'Category']
df_tmp = df_portfolio_features[~df_portfolio_features['Symbol'].isin(['ENRIN','BLUSPRING','DIGITIDE'])]
df_tmp = df_tmp.sort_values(by = 'FTT Amt', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
19,COALINDIA,4.78,12.12,4.95,17.67,8351.0,18242.0,168702.0,478.51,34.86,67.0,L-LC,11.36,185.0,2.18,1.28,32.52,XY25,ATH,MINING
50,MASFIN,-1.34,-7.56,31.51,21.57,28539.0,-7410.0,90570.0,397.04,-20.51,35.0,H-SC,6.36,167.0,-0.26,0.69,26.38,XR,ATH,FINANCE
77,TTKPRESTIG,-0.90,-36.93,58.70,0.09,37310.0,-37216.0,63561.0,770.00,47.49,22.0,M-SC,12.90,250.0,-1.00,0.48,0.00,OX40N,NTT,DURABLES
51,MEDANTA,-0.87,-8.15,35.09,24.08,40915.0,-10350.0,116600.0,1486.00,-8.85,42.0,X-SC,8.07,87.0,-0.25,0.88,6.80,XY24,NTT,HEALTHCARE
37,ICICIGI,-0.39,-2.10,21.90,19.34,42904.0,-4200.0,195909.0,2252.93,-17.63,40.0,X-MC,1.41,66.0,-0.10,1.49,11.73,X40,ATH,INSURANCE

In [10]:
# top 5 today
df_tmp = df_portfolio_features.sort_values(by = 'Today P/L%', ascending=False)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
19,COALINDIA,4.78,12.12,4.95,17.67,8351.0,18242.0,168702.0,478.51,34.86,67.0,L-LC,11.36,185.0,2.18,1.28,32.52,XY25,ATH,MINING
47,JSWINFRA,3.95,-12.69,33.36,16.43,64592.0,-28154.0,193620.0,342.00,-25.25,48.0,X-MC,11.29,61.0,-0.44,1.47,3.95,X40N,NTT,REALTY
57,RECLTD,2.84,-8.47,31.91,20.74,59338.0,-17215.0,185955.0,446.00,1.56,39.0,M-MC,3.66,191.0,-0.29,1.41,2.84,XY25,NTT,FINANCE
11,BANDHANBNK,2.76,-12.31,119.42,92.42,291722.0,-34277.0,244282.0,400.00,109.77,68.0,H-SC,9.30,174.0,-0.12,1.85,34.57,XY24,NTT,BANKS
81,VBL,2.68,-10.87,52.21,35.67,146981.0,-34324.0,281518.0,671.64,-21.38,41.0,X-LC,4.47,13.0,-0.23,2.13,2.68,X40N,ATH,FMCG

In [11]:
# bottom 5 today
df_tmp = df_portfolio_features.sort_values(by = 'Today P/L%', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
55,RAJESHEXPO,-5.00,-75.83,314.04,0.07,104117.0,-104023.0,33154.0,518.0,1114.65,21.0,L-SC,12.54,268.0,-1.00,0.25,0.00,OX40N,NTT,JEWELLERY
16,CAMPUS,-3.58,-19.69,65.96,33.28,88874.0,-33036.0,134739.0,393.0,-35.29,27.0,M-SC,3.88,218.0,-0.37,1.02,4.43,XY24,NTT,FOOTWEAR
20,COFFEEDAY,-2.75,-53.38,190.17,35.27,100665.0,-60615.0,52934.0,80.0,-63.78,30.0,L-SC,15.53,266.0,-0.60,0.40,18.17,XR,NTT,HOTELS
26,EASEMYTRIP,-2.59,-58.44,250.60,45.70,184136.0,-103337.0,73478.0,26.4,-23.66,45.0,M-SC,18.07,204.0,-0.56,0.56,21.06,XY24,NTT,TRAVEL
7,ATULAUTO,-2.51,-23.68,90.73,45.57,136503.0,-46682.0,150450.0,844.0,3251.35,42.0,M-SC,7.26,248.0,-0.34,1.14,13.86,XY24,NTT,AUTO

In [12]:
# top 5 to exit based on CumlRnk
df_tmp = df_portfolio_features[~df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])]
df_tmp = df_tmp[(df_tmp['Current P/L%'] > -1) & (df_tmp['Current P/L%'] < 1)].sort_values(by = 'CumlRnk', ascending=False)
df_tmp[cols].head()

Empty DataFrame
Columns: [Symbol, Today P/L%, Current P/L%, FTT%, OTT%, FTT Amt, Current P/L, Current, FTT, Dev%_PE, RSI_14, Conviction, Spread%, CumlRnk, RRR Ind, CurrAlloc%, Gained%, Criteria, Strategy, Category]
Index: []

In [13]:
# OX40N stocks to exit
df_tmp = df_portfolio_features[(df_portfolio_features['Symbol'].isin(list_ox40n))].sort_values(by = 'Current P/L%', ascending=False)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
27,FINCABLES,1.81,14.68,81.30,107.91,137656.0,21675.0,169319.0,1641.55,2.99,65.0,M-SC,6.13,220.0,0.16,1.28,27.38,OX40N,ATH,CABLES
66,SIS,-1.02,-32.88,80.67,21.26,60119.0,-36508.0,74524.0,528.00,1746.63,34.0,H-SC,7.19,168.0,-0.61,0.56,2.74,OX40N,NTT,MISC
48,KANSAINER,-0.53,-35.29,75.36,13.47,131504.0,-95166.0,174501.0,340.00,-44.35,29.0,H-SC,14.72,162.0,-0.72,1.32,0.00,XY24,NTT,PAINTS
41,INDIGOPNTS,-2.03,-36.79,58.23,0.02,64252.0,-64218.0,110341.0,1408.00,68.53,20.0,M-SC,13.69,222.0,-1.00,0.84,0.00,OX40N,NTT,PAINTS
77,TTKPRESTIG,-0.90,-36.93,58.70,0.09,37310.0,-37216.0,63561.0,770.00,47.49,22.0,M-SC,12.90,250.0,-1.00,0.48,0.00,OX40N,NTT,DURABLES

In [14]:
# top 5 to book for rotation
df_tmp = df_portfolio_features[(df_portfolio_features['Current P/L%'] > 20) ].sort_values(by = 'CumlRnk', ascending=False)
df_tmp[cols].head()

Empty DataFrame
Columns: [Symbol, Today P/L%, Current P/L%, FTT%, OTT%, FTT Amt, Current P/L, Current, FTT, Dev%_PE, RSI_14, Conviction, Spread%, CumlRnk, RRR Ind, CurrAlloc%, Gained%, Criteria, Strategy, Category]
Index: []

In [15]:
# top 5 to monitor for exit
df_tmp = df_portfolio_features[~df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])]
df_tmp = df_tmp[(df_tmp['Current P/L%'] > 0) ].sort_values(by = 'Dev%_PE', ascending=False)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
19,COALINDIA,4.78,12.12,4.95,17.67,8351.0,18242.0,168702.0,478.51,34.86,67.0,L-LC,11.36,185.0,2.18,1.28,32.52,XY25,ATH,MINING
27,FINCABLES,1.81,14.68,81.30,107.91,137656.0,21675.0,169319.0,1641.55,2.99,65.0,M-SC,6.13,220.0,0.16,1.28,27.38,OX40N,ATH,CABLES
1,ABB,1.23,8.29,34.42,45.57,97519.0,21701.0,283320.0,7934.00,-30.42,56.0,H-MC,8.97,125.0,0.22,2.15,25.81,AR,NTT,ELECTRICAL

In [16]:
# top 5 to book for rotation from weak conviction
df_tmp = df_portfolio_features[~df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])]
df_tmp = df_tmp[~df_tmp['Criteria'].isin(['XY25','XY24','X40', 'X40N'])].sort_values(by = 'RRR Ind', ascending=False)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
1,ABB,1.23,8.29,34.42,45.57,97519.0,21701.0,283320.0,7934.00,-30.42,56.0,H-MC,8.97,125.0,0.22,2.15,25.81,AR,NTT,ELECTRICAL
27,FINCABLES,1.81,14.68,81.30,107.91,137656.0,21675.0,169319.0,1641.55,2.99,65.0,M-SC,6.13,220.0,0.16,1.28,27.38,OX40N,ATH,CABLES
40,INDIAMART,-1.00,-11.48,133.53,106.72,145788.0,-14156.0,109180.0,4810.62,-60.16,31.0,H-SC,8.50,140.0,-0.10,0.83,9.22,AR,ATH,MISC
85,ZYDUSLIFE,1.66,-3.85,41.07,35.63,82755.0,-8077.0,201497.0,1286.17,-16.22,52.0,H-MC,4.97,120.0,-0.10,1.53,12.18,AR,ATH,PHARMA
84,WIPRO,-0.89,-20.51,116.71,72.27,157206.0,-34750.0,134698.0,420.00,-28.30,19.0,M-LC,11.86,98.0,-0.22,1.02,0.00,XR,NTT,IT

In [17]:
# top 5 to accumulate based on lowest RSI_14
df_tmp = df_portfolio_features[df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])].sort_values(by = 'RSI_14', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
8,AWL,-1.20,-42.46,173.18,57.19,324990.0,-138467.0,187660.0,485.00,-67.02,12.0,X-SC,20.64,81.0,-0.43,1.42,0.00,XY24,NTT,FMCG
53,PGHH,-1.23,-16.91,58.88,32.01,104458.0,-36112.0,177408.0,17616.87,-43.77,21.0,X-MC,9.96,57.0,-0.35,1.34,0.00,X40,ATH,FMCG
12,BATAINDIA,0.94,-52.30,183.47,35.20,112596.0,-67300.0,61370.0,2096.00,-19.57,22.0,X-SC,23.45,91.0,-0.60,0.47,0.94,X40,NTT,FOOTWEAR
3,ACC,-1.29,-36.54,158.68,64.15,239607.0,-86951.0,151000.0,3906.00,-52.08,22.0,X-SC,10.32,85.0,-0.36,1.14,0.00,XY24,BTT,CEMENT
46,JIOFIN,-1.33,-23.41,62.54,24.48,128061.0,-62599.0,204766.0,387.00,-22.22,23.0,X-LC,13.12,34.0,-0.49,1.55,11.68,XY24,BTT,FINANCE

In [18]:
# top 5 to accumulate based on Spread and CumlRnk
df_tmp = df_portfolio_features[df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])]
df_tmp = df_tmp[(df_tmp['CumlRnk'] < 100)].sort_values(by = 'Spread%', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
22,DABUR,-0.52,-5.21,51.59,43.70,121315.0,-12916.0,235152.0,735.00,-13.93,34.0,X-MC,1.27,70.0,-0.11,1.78,9.06,XY24,BTT,FMCG
78,UNITDSPR,-0.37,-3.63,25.31,20.77,57111.0,-8497.0,225647.0,1644.00,-14.48,34.0,X-MC,1.31,64.0,-0.15,1.71,2.84,X40N,NTT,BREWERIES
37,ICICIGI,-0.39,-2.10,21.90,19.34,42904.0,-4200.0,195909.0,2252.93,-17.63,40.0,X-MC,1.41,66.0,-0.10,1.49,11.73,X40,ATH,INSURANCE
59,RELIANCE,2.39,-11.60,41.75,25.30,74167.0,-23317.0,177646.0,1952.00,-13.88,41.0,X-LC,2.18,21.0,-0.31,1.35,18.61,XY25,BTT,REFINERIES
35,HINDUNILVR,-1.15,-13.04,30.71,13.67,68649.0,-33523.0,223540.0,2922.00,-35.45,35.0,X-LC,2.83,9.0,-0.49,1.69,4.89,XY25,NTT,FMCG

In [19]:
# top 5 to accumulate based on lowest Gained%
df_tmp = df_portfolio_features[df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])].sort_values(by = 'Gained%', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
3,ACC,-1.29,-36.54,158.68,64.15,239607.0,-86951.0,151000.0,3906.00,-52.08,22.0,X-SC,10.32,85.0,-0.36,1.14,0.0,XY24,BTT,CEMENT
8,AWL,-1.20,-42.46,173.18,57.19,324990.0,-138467.0,187660.0,485.00,-67.02,12.0,X-SC,20.64,81.0,-0.43,1.42,0.0,XY24,NTT,FMCG
9,BAJAJHFL,-0.27,-28.12,116.30,55.47,203371.0,-68418.0,174868.0,181.50,-38.22,23.0,X-MC,18.10,60.0,-0.34,1.33,0.0,X40N,ATH,FINANCE
13,BERGEPAINT,-0.84,-22.50,56.30,21.14,99198.0,-51144.0,176195.0,680.00,-24.23,25.0,X-MC,14.61,68.0,-0.52,1.34,0.0,XY24,NTT,PAINTS
24,DIXON,-1.29,-30.63,89.22,31.26,142823.0,-70688.0,160080.0,18931.72,-69.03,34.0,X-MC,24.55,54.0,-0.49,1.21,0.0,X40N,ATH,IT

In [20]:
# top 5 to accumulate based on lowest CurrAlloc%
df_tmp = df_portfolio_features[df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])].sort_values(by = 'CurrAlloc%', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
54,QUESS,1.06,-35.87,122.75,42.84,51171.0,-23319.0,41687.0,424.00,-58.13,36.0,X-SC,17.02,80.0,-0.46,0.32,1.06,XY24,NTT,MISC
58,RELAXO,-1.44,-58.35,265.67,52.31,160627.0,-84699.0,60461.0,1176.00,-55.67,24.0,X-SC,16.51,92.0,-0.53,0.46,0.00,X40N,NTT,FOOTWEAR
12,BATAINDIA,0.94,-52.30,183.47,35.20,112596.0,-67300.0,61370.0,2096.00,-19.57,22.0,X-SC,23.45,91.0,-0.60,0.47,0.94,X40,NTT,FOOTWEAR
51,MEDANTA,-0.87,-8.15,35.09,24.08,40915.0,-10350.0,116600.0,1486.00,-8.85,42.0,X-SC,8.07,87.0,-0.25,0.88,6.80,XY24,NTT,HEALTHCARE
36,HONAUT,-0.50,-26.38,94.69,43.32,113533.0,-42972.0,119900.0,58357.33,-35.33,31.0,X-SC,12.86,90.0,-0.38,0.91,0.00,X40N,ATH,ELECTRICAL

In [21]:
# top 5 to accumulate based on CumlRnk
df_tmp = df_portfolio_features.sort_values(by = 'CumlRnk', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
45,ITC,-0.61,-18.33,45.78,19.06,127179.0,-62361.0,277805.0,452.00,-55.12,37.0,X-LC,16.94,1.0,-0.49,2.11,0.59,X40,NTT,FMCG
73,TCS,-1.26,-26.76,68.73,23.58,217776.0,-115772.0,316857.0,4311.59,-36.41,26.0,X-LC,11.41,2.0,-0.53,2.40,0.00,X40,ATH,IT
43,INFY,-0.61,-11.54,51.76,34.24,143257.0,-36116.0,276772.0,1972.00,-30.33,27.0,X-LC,10.36,3.0,-0.25,2.10,1.87,X40,NTT,IT
75,TMPV,-0.58,-22.41,71.85,33.33,181626.0,-73015.0,252785.0,600.00,-83.62,36.0,X-LC,3.23,4.0,-0.40,1.92,3.34,XY24,NTT,AUTO
34,HCLTECH,-1.58,-12.88,42.14,23.83,88819.0,-31152.0,210772.0,1908.19,-8.60,26.0,X-LC,7.92,8.0,-0.35,1.60,1.12,X40,ATH,IT

In [22]:
# top 5 for average up
df_tmp = df_portfolio_features[(df_portfolio_features['Dev%_200'] > 5)].sort_values(by = 'CurrAlloc%', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
42,INDUSINDBK,0.09,-31.46,93.88,32.89,49680.0,-24288.0,52919.0,1800.00,-349.30,51.0,L-MC,12.09,258.0,-0.49,0.40,45.73,XR,NTT,BANKS
67,SONACOMS,0.33,-12.97,59.83,39.09,52671.0,-13125.0,88034.0,804.02,-31.00,43.0,M-MC,10.63,193.0,-0.25,0.67,24.54,AR,ATH,AUTO
27,FINCABLES,1.81,14.68,81.30,107.91,137656.0,21675.0,169319.0,1641.55,2.99,65.0,M-SC,6.13,220.0,0.16,1.28,27.38,OX40N,ATH,CABLES
19,COALINDIA,4.78,12.12,4.95,17.67,8351.0,18242.0,168702.0,478.51,34.86,67.0,L-LC,11.36,185.0,2.18,1.28,32.52,XY25,ATH,MINING
82,VOLTAS,2.49,15.37,25.85,45.20,57185.0,29478.0,221220.0,1856.00,32.11,49.0,X-MC,9.94,79.0,0.52,1.68,23.22,XY25,NTT,AC

In [23]:
# top 5 RSP
df_tmp = df_portfolio_features.sort_values(by = 'RSP', ascending=False)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
27,FINCABLES,1.81,14.68,81.30,107.91,137656.0,21675.0,169319.0,1641.55,2.99,65.0,M-SC,6.13,220.0,0.16,1.28,27.38,OX40N,ATH,CABLES
11,BANDHANBNK,2.76,-12.31,119.42,92.42,291722.0,-34277.0,244282.0,400.00,109.77,68.0,H-SC,9.30,174.0,-0.12,1.85,34.57,XY24,NTT,BANKS
26,EASEMYTRIP,-2.59,-58.44,250.60,45.70,184136.0,-103337.0,73478.0,26.40,-23.66,45.0,M-SC,18.07,204.0,-0.56,0.56,21.06,XY24,NTT,TRAVEL
83,WHIRLPOOL,-0.12,-27.96,152.53,81.92,126141.0,-32099.0,82699.0,2270.00,-57.77,52.0,M-SC,25.82,210.0,-0.25,0.63,16.17,XR,NTT,DURABLES
19,COALINDIA,4.78,12.12,4.95,17.67,8351.0,18242.0,168702.0,478.51,34.86,67.0,L-LC,11.36,185.0,2.18,1.28,32.52,XY25,ATH,MINING

In [24]:
# Top N allocation
df_tmp = df_portfolio_features.sort_values(by = 'CurrAlloc%', ascending=False)
top_n_values = [10, 25, 50]

sum_df = pd.DataFrame({
    'Top_N': top_n_values,
    'Sum_Alloc%': [df_tmp['CurrAlloc%'].head(n).sum() for n in top_n_values]
})

sum_df

   Top_N  Sum_Alloc%
0     10       20.80
1     25       45.67
2     50       77.71

In [25]:
# market-cap-wise allocation
df_tmp = df_portfolio_features[cols]
df_tmp.groupby(df_tmp['Conviction'].str[-2:])['CurrAlloc%'].sum().sort_values(ascending=False)

Conviction
SC    44.68
MC    30.37
LC    24.98
Name: CurrAlloc%, dtype: float64

In [26]:
# criteria-wise allocation
df_portfolio_features.groupby('Criteria')['CurrAlloc%'].sum().sort_values(ascending=False)

Criteria
XY24     26.58
X40      24.07
X40N     14.68
AR        9.17
XY25      9.07
XR        8.49
OX40N     7.15
SR        0.82
Name: CurrAlloc%, dtype: float64

In [27]:
# conviction-wise allocation
df_portfolio_features.groupby('Conviction')['CurrAlloc%'].sum().sort_values(ascending=False)

Conviction
X-MC    22.84
H-SC    22.28
X-LC    21.47
X-SC    11.17
M-SC    10.58
H-MC     5.05
M-MC     2.08
L-LC     1.28
H-LC     1.21
M-LC     1.02
L-SC     0.65
L-MC     0.40
Name: CurrAlloc%, dtype: float64

In [28]:
# sector-wise stats
df_tmp = df_portfolio_features.groupby('Category')[['CurrAlloc%', 'Current', 'Current P/L', 'FTT Amt']].sum().sort_values(by=['Current', 'Current P/L'], ascending=False)
df_tmp['Current P/L%'] = round(df_tmp['Current P/L'] * 100 / df_tmp['Current'], 2)
df_tmp['FTT%'] = round(df_tmp['FTT Amt'] * 100 / df_tmp['Current'], 2)
cols = ['CurrAlloc%', 'Current P/L%', 'FTT%']
df_tmp[cols].sort_values(by=['CurrAlloc%'], ascending=False)

               CurrAlloc%  Current P/L%    FTT%
Category
FMCG                15.72        -18.93   59.14
FINANCE             12.85        -23.27   71.78
IT                  11.47        -44.86  117.45
MISC                 6.77        -45.61  105.17
ELECTRICAL           6.41        -11.10   51.64
PAINTS               5.01        -39.92   60.70
INSURANCE            4.91         -4.87   40.76
PHARMA               4.27         -4.39   37.25
AUTO                 3.73        -27.04   75.48
BANKS                3.26        -24.37   99.73
AC                   2.25         -7.69   36.89
FOOTWEAR             1.95        -72.12  141.13
TRAVEL               1.93        -75.72  163.70
DURABLES             1.86        -58.05   96.50
BREWERIES            1.71         -3.77   25.31
HEALTHCARE           1.65        -41.57   76.50
REALTY               1.47        -14.54   33.36
APPARELS             1.42        -26.31   64.38
CERAMICS             1.41        -65.81  116.19
REFINERIES           1.35        -13.13   41.75
CABLES               1.28         12.80   81.30
MINING               1.28         10.81    4.95
JEWELLERY            1.17       -106.65  178.46
CEMENT               1.14        -57.58  158.68
ENGINEERING          1.11        -64.97  140.43
CHEMICALS            1.02        -96.85  257.45
ENTERTAINMENT        0.79        -85.81  196.63
TEXTILES             0.44        -58.06  103.13
HOTELS               0.40       -114.51  190.17

In [29]:
# money to be made criteria-wise
df_portfolio_features.groupby('Criteria')['FTT Amt'].agg(['sum', 'count']).sort_values(by='sum', ascending=False)

                sum  count
Criteria
XY24      3620022.0     21
X40       1547894.0     15
XR        1370744.0     12
AR        1364625.0     10
X40N      1185863.0     10
OX40N      848965.0     10
XY25       421557.0      6
SR         310971.0      2

In [30]:
# money to be made conviction-wise
df_portfolio_features.groupby('Conviction')['FTT Amt'].agg(['sum', 'count']).sort_values(by='sum', ascending=False)

                  sum  count
Conviction
H-SC        3854392.0     24
M-SC        1523161.0     14
X-MC        1501736.0     15
X-LC        1441503.0     12
X-SC        1331269.0     10
H-MC         412870.0      3
L-SC         204782.0      2
M-LC         157206.0      1
M-MC         112009.0      2
H-LC          73682.0      1
L-MC          49680.0      1
L-LC           8351.0      1

In [31]:
# money to be made criteria and conviction-wise
df_portfolio_features.groupby(['Conviction', 'Criteria'])['FTT Amt'].agg(['sum', 'count']).sort_values(by='sum', ascending=False)

                           sum  count
Conviction Criteria
H-SC       XY24      1304635.0      6
           AR         981246.0      5
M-SC       XY24       895908.0      6
H-SC       XR         876859.0      7
X-LC       X40        747633.0      6
X-SC       XY24       656683.0      4
X-MC       X40        602274.0      7
X-SC       X40N       476599.0      4
X-MC       X40N       467897.0      4
H-SC       OX40N      380681.0      4
M-SC       OX40N      364167.0      5
H-SC       SR         310971.0      2
X-LC       XY24       309687.0      2
           X40N       241367.0      2
H-MC       XY24       232596.0      1
X-MC       XY24       220513.0      2
           XY25       211052.0      2
X-SC       X40        197987.0      2
M-SC       XR         186334.0      2
H-MC       AR         180274.0      2
M-LC       XR         157206.0      1
X-LC       XY25       142816.0      2
L-SC       OX40N      104117.0      1
           XR         100665.0      1
M-SC       AR          76752.0      1
H-LC       AR          73682.0      1
M-MC       XY25        59338.0      1
           AR          52671.0      1
L-MC       XR          49680.0      1
L-LC       XY25         8351.0      1

In [32]:
# notebook execution time

end_time = time.time()
execution_time = round(end_time - start_time, 0)
print(f"Notebook execution time: {execution_time} seconds")

Notebook execution time: 36.0 seconds