<a href="https://colab.research.google.com/github/ankit-rathi/Quantvesting_v2/blob/main/myStocks_Portfolio_Analysis.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
'''
!pip install pandas==2.2.2 -qq
!pip install pyxirr -qq
!pip install ta -qq
!pip install yfinance==0.2.59 -qq
'''

'\n!pip install pandas==2.2.2 -qq\n!pip install pyxirr -qq\n!pip install ta -qq\n!pip install yfinance==0.2.59 -qq\n'

In [2]:
# import libraries

import numpy as np
import pandas as pd
import datetime
import warnings
warnings.filterwarnings('ignore')
import yfinance as yfin
import ta
import matplotlib.pyplot as plt
import requests

In [3]:
# notebook start time
import time
import datetime
import pytz

start_time = time.time()

# function to print date timestamp
def print_date_time():
  tz_NY = pytz.timezone('Asia/Kolkata')
  datetime_NY = datetime.datetime.now(tz_NY)
  print("Run date time (IST):", datetime_NY.strftime("%Y-%m-%d %H:%M:%S"))

In [4]:
# function to get booked and reserved amount
def get_amt():
  # fetch the JSON data from the URL
  url = "https://raw.githubusercontent.com/ankit-rathi/Tradevesting_v1/main/data/myPortfolioAmts.json"
  response = requests.get(url)
  pf_amts = response.json()  # parse the JSON data

  # extract values from the JSON
  py_booked_amt_dm = pf_amts["py_booked_amt_dm"]
  py_booked_amt_sv = pf_amts["py_booked_amt_sv"]
  cy_booked_amt_dm = pf_amts["cy_booked_amt_dm"]
  cy_booked_amt_sv = pf_amts["cy_booked_amt_sv"]
  reserve_amt_dm = pf_amts["reserve_amt_dm"]
  reserve_amt_sv = pf_amts["reserve_amt_sv"]

  # perform calculations
  py_booked_amt = py_booked_amt_dm + py_booked_amt_sv
  cy_booked_amt = cy_booked_amt_dm + cy_booked_amt_sv
  reserve_amt = reserve_amt_dm + reserve_amt_sv
  total_booked_amt = py_booked_amt + cy_booked_amt

  return total_booked_amt, reserve_amt, cy_booked_amt, py_booked_amt

gen_output = 0

In [5]:
# function to format the amount
def format_amt(number):
    abs_number = abs(number)

    if abs_number >= 1_00_00_000:  # Crores
        formatted_amt = f"{number / 1_00_00_000:.2f} C"
    elif abs_number >= 1_00_000:  # Lakhs
        formatted_amt = f"{number / 1_00_000:.2f} L"
    elif abs_number >= 1_000:  # Thousands
        formatted_amt = f"{number / 1_000:.2f} K"
    else:
        formatted_amt = f"{number:.2f}"

    return formatted_amt

# function to set start and end date
def get_start_end_date():
  start_date = (datetime.date.today() + datetime.timedelta(days=-365)).strftime('%Y-%m-%d')
  end_date = (datetime.date.today() + datetime.timedelta(days=1)).strftime('%Y-%m-%d')
  return start_date, end_date

# function to fetch my portfolio csv
def get_mypfs_df():
  mypfs_df = pd.read_csv('https://raw.githubusercontent.com/ankit-rathi/Tradevesting_v1/main/data/myPortfolioStocks.csv')
  return mypfs_df

# function to fetch my prospects csv
def get_mypps_df():
  mypps_df = pd.read_csv('https://raw.githubusercontent.com/ankit-rathi/Tradevesting_v1/main/data/myProspectsScrips.csv')
  return mypps_df

# function to fetch screener data
def get_myscreen_df():
  myscreen_df = pd.read_csv('https://raw.githubusercontent.com/ankit-rathi/Tradevesting_v1/main/data/myScreenerDB.csv')
  return myscreen_df

# function to fetch momentum data
def get_myinvmt_df():
  myinvmt_df = pd.read_csv('https://raw.githubusercontent.com/ankit-rathi/Tradevesting_v1/main/data/myInvestments.csv')
  return myinvmt_df

# function to get the stock ids
def get_stock_ids(df_pf):
  stock_n100 = df_pf['Symbol'].unique()

  exclude = ['CADILAHC','MMTC', 'MASFIN']

  stock_ids = df_pf[~df_pf['Symbol'].isin(exclude) ]['Symbol'].unique()

  #mypf = mypf[mypf.Forecast.notnull()]
  #stock_ids = mypf['Symbol'].unique()

  #stock_ids.sort()
  return stock_ids

# get features from screener data
def get_screener_features():
  myscreen_df = get_myscreen_df()
  cols = ['Symbol', 'EPS', 'MedPE', 'ROCE%', 'ROE%', 'CapType']
  return myscreen_df[cols]

# get relative strength
def get_relative_strength(stock_list):

    # Dictionary to store stock tickers and their corresponding percentage price change
    stock_changes = {}

    # Loop through each stock and fetch its price data
    for stock in stock_list:
        try:
            # Download the stock data for the given date range
            stock_data = yfin.Ticker(stock + '.NS').history(period='1mo', interval='1d')[map(str.title, ['open', 'close', 'low', 'high', 'volume'])]

            # Calculate the percentage change for the stock
            if len(stock_data) > 0:
                start_price = stock_data['Close'].iloc[0]
                end_price = stock_data['Close'].iloc[-1]
                percent_change = round(((end_price - start_price) / start_price) * 100, 2)
                stock_changes[stock] = percent_change
            else:
                stock_changes[stock] = np.nan  # If no data is available, set to NaN

        except Exception as e:
            print(f"Error fetching data for {stock}: {e}")
            stock_changes[stock] = np.nan

    # Create a DataFrame with stock tickers and their percentage changes
    df = pd.DataFrame(list(stock_changes.items()), columns=['Symbol', 'Percent_Change'])

    # Drop any stocks with missing data (NaN values)
    df = df.dropna()

    # Calculate the percentile rank based on percentage change
    df['RSP'] = round(df['Percent_Change'].rank(pct=True) * 100, 2)
    cols = ['Symbol', 'RSP']
    df = df[cols]
    # Sort by percentile rank (optional)
    df = df.sort_values(by='RSP', ascending=False).reset_index(drop=True)

    return df

In [6]:
# function to get stock technicals
def stock_prec_dev(stock_symbol):
    #stock_symbol = 'ULTRACEMCO.NS'
    short_window = 20
    mid_window = 50
    long_window = 200
    moving_avg = 'SMA'

    start = datetime.datetime(*map(int, start_date.split('-')))
    end = datetime.datetime(*map(int, end_date.split('-')))

    stock_df = yfin.Ticker(stock_symbol + '.NS').history(period='max', interval='1d')[map(str.title, ['open', 'close', 'low', 'high', 'volume'])]

    stock_df['Max'] = round(max(stock_df['Close']),2)
    stock_df = stock_df[(stock_df.index <= end_date) & (stock_df.index >= start_date)]
    stock_df['200_SMA'] = round(stock_df['Close'].rolling(window = 200, min_periods = 1).mean(),0)
    stock_df['Dev%_200'] = round((stock_df['Close'] - stock_df['200_SMA'])*100/stock_df['200_SMA'],2)
    stock_df.dropna(axis = 0, inplace = True) # remove any null rows

    stock_df['20_SMA'] = stock_df['Close'].rolling(window=20).mean()
    stock_df['50_SMA'] = stock_df['Close'].rolling(window=50).mean()
    stock_df['Symbol'] = stock_symbol

    stock_df['Close'] = round(stock_df['Close'],2)
    stock_df['Min'] = round(min(stock_df['Close']),2)
    stock_df['RSI_14'] = ta.momentum.RSIIndicator(close=stock_df['Close'], window=14).rsi()
    stock_df['RSI_14'] = round(stock_df['RSI_14'],0)
    stock_df['Prev_Close'] = stock_df['Close'].shift(1)
    stock_df.drop(['Open', 'Low', 'High', 'Volume'], axis=1, inplace=True)
    stock_df = stock_df.tail(1)

    max_SMA = max(stock_df['20_SMA'].item(), stock_df['50_SMA'].item(), stock_df['200_SMA'].item())
    min_SMA = min(stock_df['20_SMA'].item(), stock_df['50_SMA'].item(), stock_df['200_SMA'].item())
    ABS_Spread = max_SMA - min_SMA
    stock_df['Spread%'] = round((ABS_Spread / stock_df['200_SMA'].item()) * 100,2)

    return stock_df

# function to compute stock attributes
def get_common_features(stock_ids, df_mypf):

  df_prec_dev = pd.DataFrame()
  df_tmp = get_screener_features()
  df_rs = get_relative_strength(stock_ids)

  for stock_id in stock_ids:
      tmp = stock_prec_dev(stock_id)
      tmp = tmp.reset_index()
      df_prec_dev = pd.concat([df_prec_dev, tmp], ignore_index = True)
  df_prec_dev = pd.merge(df_prec_dev, df_mypf, on= 'Symbol')
  df_prec_dev = pd.merge(df_prec_dev, df_tmp, on= 'Symbol', how='left')
  df_prec_dev = pd.merge(df_prec_dev, df_rs, on= 'Symbol', how='left')
  #print(df_prec_dev.columns)
  df_prec_dev['Curr_PE'] = round(df_prec_dev['Close']/df_prec_dev['EPS'],1)
  df_prec_dev['Dev%_PE'] = round((df_prec_dev['Curr_PE'] - df_prec_dev['MedPE'])*100/df_prec_dev['MedPE'],2)
  df_prec_dev['Conviction'] = df_prec_dev['Conviction'] + '-' + df_prec_dev['CapType']
  return df_prec_dev

# function to arrange stock features
def arrange_features(df_stocks, common_cols, diff_cols):
  df_stocks_common = df_stocks[common_cols].drop_duplicates()
  df_stocks_diff = df_stocks[diff_cols]
  df_stocks_diff['Investment'] = df_stocks_diff['AvgCost'] * df_stocks_diff['Shares']
  df_stocks_diff = df_stocks_diff.groupby(['Symbol'])[['Shares', 'Investment']].aggregate(['sum']).reset_index()
  df_stocks_diff.columns = ['Symbol', 'Shares', 'Investment']
  df_stocks_diff['AvgCost'] = round(df_stocks_diff['Investment']/df_stocks_diff['Shares'],2)
  df_stocks = pd.merge(df_stocks_diff, df_stocks_common, on='Symbol')
  return df_stocks

# plot fact distribution across dimension
def plot_pie_chart(df, dimension, fact):
  # grouping the data by category and calculating the sum of fact for each type
  grouped_data = df.groupby(dimension)[fact].sum()

  # sorting the grouped data in descending order
  grouped_data = grouped_data.sort_values(ascending=False)

  # creating a pie chart
  grouped_data.plot.pie(autopct='%1.1f%%', startangle=90, figsize=(6, 6))

  # adding a title and displaying the plot
  plt.title(f'{dimension} {fact} Distribution')
  plt.ylabel('')  # To hide the y-label
  plt.show()

In [7]:
# function to get portfolio features

def get_portfolio_features(df_common_features):

  print_date_time()
  print('-------------------')

  #df_common_features["Target"] = df_common_features["Target"].fillna(df_common_features["Max"])
  df_common_features['NTT'] = np.where(df_common_features['Strategy']== 'NTT', df_common_features["Target"], df_common_features['Max'])
  df_common_features['LTT'] = np.where(df_common_features['Strategy']== 'BTT', df_common_features["Target"], df_common_features['Max'])
  df_common_features['BOL'] = df_common_features['Min']

  tmp_df = df_common_features[df_common_features['Symbol'].isin(mypf_df[mypf_df['InPortfolio'] != 'NA'].Symbol.values)]
  print('qualified stocks: '+str(len(tmp_df['Symbol'].unique())))
  tmp_df1 = tmp_df[tmp_df['LatestQtr'] == 1]
  print('with latest results: '+str(len(tmp_df1['Symbol'].unique())))
  tmp_df1 = tmp_df1[tmp_df1['StarStock'] == 1]
  print('still star stocks: '+str(len(tmp_df1['Symbol'].unique())))
  tmp_df['Investment'] = tmp_df['AvgCost'] * tmp_df['Shares']
  tmp_df['Current'] = round(tmp_df['Close'] * tmp_df['Shares'],0)
  tmp_df['Previous'] = tmp_df['Prev_Close'] * tmp_df['Shares']
  tmp_df['EstimatedST'] = tmp_df['NTT'] * tmp_df['Shares']
  tmp_df['EstimatedLT'] = tmp_df['LTT'] * tmp_df['Shares']
  tmp_df['Current P/L'] = round((tmp_df['Current'] - tmp_df['Investment']),0)
  tmp_df['Today P/L%'] = round((tmp_df['Current'] - tmp_df['Previous'])*100/tmp_df['Previous'],2)
  tmp_df['Current P/L%'] = round((tmp_df['Current'] - tmp_df['Investment'])*100/tmp_df['Investment'],2)
  tmp_df['EstimatedST P/L%'] = round((tmp_df['EstimatedST'] - tmp_df['Investment'])*100/tmp_df['Investment'],2)
  tmp_df['EstimatedLT P/L%'] = round((tmp_df['EstimatedLT'] - tmp_df['Investment'])*100/tmp_df['Investment'],2)
  tmp_df['NTT%'] = round((tmp_df['NTT'] - tmp_df['Close'])*100/tmp_df['Close'],2)
  tmp_df['LTT%'] = round((tmp_df['LTT'] - tmp_df['Close'])*100/tmp_df['Close'],2)
  tmp_df['Gained%'] = round((tmp_df['Close'] - tmp_df['BOL'])*100/tmp_df['BOL'],2)
  investment = round(sum(tmp_df['AvgCost']*tmp_df['Shares']),0)
  current = round(sum(tmp_df['Close']*tmp_df['Shares']),0)
  tmp_df['InitAlloc%'] = round(tmp_df['Investment']*100/investment,2)
  tmp_df['CurrAlloc%'] = round(tmp_df['Current']*100/current,2)
  tmp_df['FTT'] = tmp_df['LTT']
  tmp_df.loc[tmp_df['Strategy'] == 'NTT', 'FTT'] = tmp_df['NTT']
  tmp_df['FTT%'] = tmp_df['LTT%']
  tmp_df.loc[tmp_df['Strategy'] == 'NTT', 'FTT%'] = tmp_df['NTT%']
  tmp_df['FTT Amt'] = round(tmp_df['FTT%'] * tmp_df['Current']/100,0)
  tmp_df['OTT%'] = round((tmp_df['FTT'] - tmp_df['AvgCost'])*100/tmp_df['AvgCost'],2)
  tmp_df['RRR Ind'] = round(tmp_df['Current P/L']/tmp_df['FTT Amt'],2)
  tmp_df['Risk Ind'] = round(tmp_df['Current P/L%']*tmp_df['CurrAlloc%'],0)

  return tmp_df

# function to print portfolio features
def print_portfolio_stats(df_portfolio_features, myinvmt_df):
  from pyxirr import xirr

  total_booked_amt, reserve_amt, cy_booked_amt, py_booked_amt = get_amt()

  dates = myinvmt_df['Date'].values
  dates = np.append(dates, datetime.date.today().strftime('%d-%b-%y'))
  investment = myinvmt_df['Investment'].values
  dates= pd.to_datetime(dates)

  current = round(sum(df_portfolio_features['Close']*df_portfolio_features['Shares']),0) + reserve_amt
  investment_xirr = np.append(investment, current)
  cagr = round(xirr(pd.DataFrame({"dates": dates, "amounts": investment_xirr}))*100,2)

  investment = -sum(investment)
  invested = round(sum(df_portfolio_features['AvgCost']*df_portfolio_features['Shares']),0) + reserve_amt
  previous = round(sum(df_portfolio_features['Prev_Close']*df_portfolio_features['Shares']),0) + reserve_amt
  cy_invested = investment + py_booked_amt

  today_pnl_amount = current-previous
  today_pnl_percentage = round((current-previous)*100/previous,2)

  curr_pnl_amount = current-invested
  curr_pnl_percentage = round((curr_pnl_amount)*100/(cy_invested),2)

  cy_pnl_amount = cy_booked_amt + curr_pnl_amount
  cy_pnl_percentage = round((cy_pnl_amount)*100/cy_invested,2)

  overall_pnl_amount = total_booked_amt + curr_pnl_amount
  overall_pnl_percentage = round((overall_pnl_amount)*100/investment,2)

  estimate_st = round(sum(df_portfolio_features['FTT']*df_portfolio_features['Shares']),0)  + reserve_amt
  est_st_pnl_amount = estimate_st-current
  est_st_pnl_percentage = round((est_st_pnl_amount)*100/current,2)

  estimate_lt = round(sum(df_portfolio_features['LTT']*df_portfolio_features['Shares']),0)  + reserve_amt
  est_lt_pnl_amount = estimate_lt-current
  est_lt_pnl_percentage = round((est_lt_pnl_amount)*100/current,2)

  total_profit = round(sum(df_portfolio_features[df_portfolio_features['Current P/L%'] > 0]['Current']) - sum(df_portfolio_features[df_portfolio_features['Current P/L%'] > 0]['Investment']),0)
  total_loss = round(sum(df_portfolio_features[df_portfolio_features['Current P/L%'] < 0]['Current']) - sum(df_portfolio_features[df_portfolio_features['Current P/L%'] < 0]['Investment']),0)

  cy_booked_percentage = round((cy_booked_amt)*100/current,2)
  py_booked_percentage = round((py_booked_amt)*100/investment,2)
  total_booked_percentage = round((total_booked_amt)*100/investment,2)

  print('-------------------')
  print('Initial Investment: ', format_amt(investment))
  print('CY Investment: ', format_amt(cy_invested))
  print('Reserve: ', format_amt(reserve_amt))
  print('Current: ',  format_amt(current))
  print('-------------------')
  print('Today PnL: '+ '{} ({}%)'.format(format_amt(today_pnl_amount), today_pnl_percentage))
  print('Current PnL: '+ '{} ({}%)'.format(format_amt(curr_pnl_amount), curr_pnl_percentage))
  print('CY Booked + Current PnL: '+ '{} ({}%)'.format(format_amt(cy_pnl_amount), cy_pnl_percentage))
  print('-------------------')
  print('Total profit: ', format_amt(total_profit))
  print('Total loss: ', format_amt(total_loss))
  print('-------------------')
  print('Total Booked + Current PnL: '+ '{} ({}%)'.format(format_amt(overall_pnl_amount), overall_pnl_percentage))
  print('Total Booked PnL: '+ '{} ({}%)'.format(format_amt(total_booked_amt), total_booked_percentage))
  print('Curr Year Booked PnL: '+ '{} ({}%)'.format(format_amt(cy_booked_amt), cy_booked_percentage))
  print('Prev Year Booked PnL: '+ '{} ({}%)'.format(format_amt(py_booked_amt), py_booked_percentage))
  print('===================')
  print('Est FTT: ',  format_amt(estimate_st))
  print('Est FTT PnL: '+ '{} ({}%)'.format(format_amt(est_st_pnl_amount), est_st_pnl_percentage))

  print('===================')
  print('Deployed: ', format_amt(investment))

  print('Current: ', format_amt(current))

  print('CAGR/XIRR %: '+'{}%'.format(cagr))

In [8]:
# get start and end date
start_date, end_date = get_start_end_date()

# get portfolio and prospects data
mypfs_df = get_mypfs_df()
mypps_df = get_mypps_df()
myinvmt_df = get_myinvmt_df()

# merge above datasets
mypf_df = pd.merge(mypfs_df, mypps_df, on="Symbol")

# seggregate dm and sv portfolio
dm_pf = mypf_df[mypf_df['InPortfolio'] == 'DM']
sv_pf = mypf_df[mypf_df['InPortfolio'] == 'SV']

# build portfolio stock dataframe
dm_stocks = get_stock_ids(dm_pf)
sv_stocks = get_stock_ids(sv_pf)
df_stocks = pd.concat([dm_pf,sv_pf], ignore_index = True)

# arrange common and diff stock features
common_cols = ['Symbol', 'Target', 'Criteria', 'Strategy', 'CumlRnk', 'LatestQtr', 'StarStock', 'Conviction', 'Category', 'InFolio', 'XIRR', 'MBQ']
diff_cols = ['Symbol', 'AvgCost', 'Shares']
df_stocks = arrange_features(df_stocks, common_cols, diff_cols)

# get common features
stock_ids = df_stocks['Symbol'].values
df_common_features = get_common_features(stock_ids, df_stocks)

df_common_features.reset_index(drop=True, inplace=True)
df_common_features.drop(['Date'], axis=1, inplace=True)
# get and print portfolio features
df_portfolio_features = get_portfolio_features(df_common_features)

print_portfolio_stats(df_portfolio_features, myinvmt_df)

df = df_portfolio_features
#plot_pie_chart(df, 'CapType', 'Current')
list_ox40n = list(df[df['MBQ'].str.contains('OX40N', na=False)]['Symbol'].values)

Run date time (IST): 2026-08-07 11:26:26
-------------------
qualified stocks: 88
with latest results: 30
still star stocks: 19
-------------------
Initial Investment:  1.46 C
CY Investment:  1.89 C
Reserve:  2.24 L
Current:  1.62 C
-------------------
Today PnL: -12.99 K (-0.08%)
Current PnL: -30.26 L (-16.02%)
CY Booked + Current PnL: -26.04 L (-13.78%)
-------------------
Total profit:  3.61 L
Total loss:  -33.87 L
-------------------
Total Booked + Current PnL: 16.83 L (11.53%)
Total Booked PnL: 47.09 L (32.24%)
Curr Year Booked PnL: 4.22 L (2.61%)
Prev Year Booked PnL: 42.87 L (29.35%)
===================
Est FTT:  2.67 C
Est FTT PnL: 1.05 C (64.78%)
===================
Deployed:  1.46 C
Current:  1.62 C
CAGR/XIRR %: 4.74%

In [9]:
# top 5 near their targets
cols = ['Symbol', 'Today P/L%', 'Current P/L%', 'FTT%', 'OTT%', 'FTT Amt', 'Current P/L', 'Current', 'FTT', 'Dev%_PE', 'RSI_14','Conviction', 'Spread%',  'CumlRnk', 'RRR Ind', 'CurrAlloc%', 'Gained%', 'Criteria', 'Strategy', 'Category']
df_tmp = df_portfolio_features[~df_portfolio_features['Symbol'].isin(['ENRIN','BLUSPRING','DIGITIDE'])]
df_tmp = df_tmp.sort_values(by = 'FTT Amt', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
55,MEDANTA,1.41,25.29,1.46,27.12,3229.0,44638.0,221155.0,1486.00,21.43,68.0,X-SC,15.41,87.0,13.82,1.39,52.39,XY24,NTT,HEALTHCARE
79,TTKPRESTIG,0.18,-18.19,22.35,0.09,18426.0,-18332.0,82445.0,770.00,91.46,49.0,M-SC,13.83,250.0,-0.99,0.52,48.39,OX40N,NTT,DURABLES
80,UNITDSPR,-0.14,11.50,8.31,20.77,21694.0,26918.0,261062.0,1644.00,-1.08,70.0,X-MC,7.12,64.0,1.24,1.64,25.49,X40N,NTT,BREWERIES
52,M&M,1.67,9.35,8.66,18.82,22792.0,22507.0,263188.0,3762.88,-4.70,67.0,X-LC,5.74,25.0,0.99,1.65,19.39,X40N,ATH,AUTO
69,SIS,1.20,0.06,21.18,21.26,23532.0,72.0,111104.0,528.00,2652.85,56.0,H-SC,22.84,168.0,0.00,0.70,65.19,OX40N,NTT,MISC

In [10]:
# top 5 today
df_tmp = df_portfolio_features.sort_values(by = 'Today P/L%', ascending=False)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
78,TRIDENT,2.93,-31.38,87.28,28.51,55253.0,-28948.0,63306.0,48.00,-11.82,58.0,M-SC,3.36,223.0,-0.52,0.40,18.60,XR,NTT,TEXTILES
25,FINCABLES,2.78,30.61,59.18,107.91,114125.0,45200.0,192844.0,1641.55,17.71,52.0,M-SC,17.62,220.0,0.40,1.21,45.08,OX40N,ATH,CABLES
62,RELAXO,2.51,-44.75,175.67,52.31,140889.0,-64959.0,80201.0,1176.00,-41.15,61.0,X-SC,11.10,92.0,-0.46,0.50,79.32,X40N,NTT,FOOTWEAR
75,TCS,2.38,-28.68,74.14,24.20,244967.0,-132861.0,330412.0,4230.71,-39.69,62.0,X-LC,15.69,2.0,-0.54,2.07,23.21,X40,ATH,IT
12,BOSCH-HCIL,2.32,-26.24,35.56,-0.01,33522.0,-33535.0,94270.0,2282.00,19182.61,85.0,M-SC,3.84,231.0,-1.00,0.59,60.46,OX40N,BTT,AC

In [11]:
# bottom 5 today
df_tmp = df_portfolio_features.sort_values(by = 'Today P/L%', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
18,COFFEEDAY,-5.04,-45.21,146.91,35.27,91390.0,-51341.0,62208.0,80.00,-57.75,53.0,L-SC,5.65,266.0,-0.56,0.39,53.41,XR,NTT,HOTELS
39,ICICIGI,-2.47,-13.00,36.65,18.89,63805.0,-26015.0,174094.0,2244.41,-26.70,44.0,X-MC,9.41,66.0,-0.41,1.09,3.72,X40,ATH,INSURANCE
66,SFL,-2.47,-33.11,89.32,26.63,156657.0,-86830.0,175388.0,1287.00,32.84,33.0,M-SC,24.60,242.0,-0.55,1.10,46.38,XY24,NTT,MISC
3,ALKYLAMINE,-2.21,-19.21,138.33,92.54,112832.0,-19396.0,81567.0,4520.85,-13.41,57.0,H-SC,13.35,142.0,-0.17,0.51,54.89,SR,ATH,CHEMICALS
51,LAOPALA,-2.16,-42.49,141.84,39.09,106949.0,-55704.0,75401.0,464.00,64.71,59.0,H-SC,6.25,154.0,-0.52,0.47,16.99,AR,NTT,CERAMICS

In [12]:
# top 5 to exit based on CumlRnk
df_tmp = df_portfolio_features[~df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])]
df_tmp = df_tmp[(df_tmp['Current P/L%'] > -1) & (df_tmp['Current P/L%'] < 1)].sort_values(by = 'CumlRnk', ascending=False)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
61,RECLTD,1.73,-0.45,21.28,20.74,43041.0,-908.0,202262.0,446.0,9.37,59.0,M-MC,3.43,191.0,-0.02,1.27,21.92,XY25,NTT,FINANCE
69,SIS,1.20,0.06,21.18,21.26,23532.0,72.0,111104.0,528.0,2652.85,56.0,H-SC,22.84,168.0,0.00,0.70,65.19,OX40N,NTT,MISC

In [13]:
# OX40N stocks to exit
df_tmp = df_portfolio_features[(df_portfolio_features['Symbol'].isin(list_ox40n))].sort_values(by = 'Current P/L%', ascending=False)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
25,FINCABLES,2.78,30.61,59.18,107.91,114125.0,45200.0,192844.0,1641.55,17.71,52.0,M-SC,17.62,220.0,0.40,1.21,45.08,OX40N,ATH,CABLES
69,SIS,1.20,0.06,21.18,21.26,23532.0,72.0,111104.0,528.00,2652.85,56.0,H-SC,22.84,168.0,0.00,0.70,65.19,OX40N,NTT,MISC
79,TTKPRESTIG,0.18,-18.19,22.35,0.09,18426.0,-18332.0,82445.0,770.00,91.46,49.0,M-SC,13.83,250.0,-0.99,0.52,48.39,OX40N,NTT,DURABLES
16,CERA,-1.26,-18.35,51.73,23.89,74297.0,-32279.0,143624.0,9475.00,-21.24,53.0,H-SC,12.93,153.0,-0.43,0.90,39.61,OX40N,NTT,CERAMICS
43,INDIGOPNTS,2.26,-20.77,26.23,0.02,36279.0,-36249.0,138310.0,1408.00,110.94,61.0,M-SC,4.63,222.0,-1.00,0.87,56.92,OX40N,NTT,PAINTS

In [14]:
# top 5 to book for rotation
df_tmp = df_portfolio_features[(df_portfolio_features['Current P/L%'] > 20) ].sort_values(by = 'CumlRnk', ascending=False)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
25,FINCABLES,2.78,30.61,59.18,107.91,114125.0,45200.0,192844.0,1641.55,17.71,52.0,M-SC,17.62,220.0,0.40,1.21,45.08,OX40N,ATH,CABLES
55,MEDANTA,1.41,25.29,1.46,27.12,3229.0,44638.0,221155.0,1486.00,21.43,68.0,X-SC,15.41,87.0,13.82,1.39,52.39,XY24,NTT,HEALTHCARE
58,QUESS,-1.65,25.95,38.07,73.90,51208.0,27717.0,134510.0,424.00,-32.23,57.0,X-SC,39.40,80.0,0.54,0.84,85.13,XY24,NTT,MISC

In [15]:
# top 5 to monitor for exit
df_tmp = df_portfolio_features[~df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])]
df_tmp = df_tmp[(df_tmp['Current P/L%'] > 0) ].sort_values(by = 'Dev%_PE', ascending=False)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
69,SIS,1.20,0.06,21.18,21.26,23532.0,72.0,111104.0,528.00,2652.85,56.0,H-SC,22.84,168.0,0.00,0.70,65.19,OX40N,NTT,MISC
70,STARHEALTH,-0.31,10.66,33.08,47.26,102907.0,29963.0,311086.0,761.00,74.55,44.0,H-SC,17.63,173.0,0.29,1.95,34.51,XY24,NTT,INSURANCE
25,FINCABLES,2.78,30.61,59.18,107.91,114125.0,45200.0,192844.0,1641.55,17.71,52.0,M-SC,17.62,220.0,0.40,1.21,45.08,OX40N,ATH,CABLES
87,ZYDUSLIFE,-0.55,16.20,16.62,35.51,40473.0,33946.0,243520.0,1285.01,1.35,44.0,H-MC,15.53,120.0,0.84,1.53,28.15,AR,ATH,PHARMA

In [16]:
# top 5 to book for rotation from weak conviction
df_tmp = df_portfolio_features[~df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])]
df_tmp = df_tmp[~df_tmp['Criteria'].isin(['XY25','XY24','X40', 'X40N'])].sort_values(by = 'RRR Ind', ascending=False)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
87,ZYDUSLIFE,-0.55,16.20,16.62,35.51,40473.0,33946.0,243520.0,1285.01,1.35,44.0,H-MC,15.53,120.0,0.84,1.53,28.15,AR,ATH,PHARMA
25,FINCABLES,2.78,30.61,59.18,107.91,114125.0,45200.0,192844.0,1641.55,17.71,52.0,M-SC,17.62,220.0,0.40,1.21,45.08,OX40N,ATH,CABLES
69,SIS,1.20,0.06,21.18,21.26,23532.0,72.0,111104.0,528.00,2652.85,56.0,H-SC,22.84,168.0,0.00,0.70,65.19,OX40N,NTT,MISC
3,ALKYLAMINE,-2.21,-19.21,138.33,92.54,112832.0,-19396.0,81567.0,4520.85,-13.41,57.0,H-SC,13.35,142.0,-0.17,0.51,54.89,SR,ATH,CHEMICALS
42,INDIAMART,-0.64,-24.18,165.01,100.92,154298.0,-29828.0,93508.0,4675.60,-65.82,36.0,H-SC,11.62,140.0,-0.19,0.59,1.22,AR,ATH,MISC

In [17]:
# top 5 to accumulate based on lowest RSI_14
df_tmp = df_portfolio_features[df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])].sort_values(by = 'RSI_14', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
34,HDFCBANK,-0.08,-10.39,46.25,31.05,121483.0,-30455.0,262665.0,1073.00,-25.47,35.0,X-LC,10.56,26.0,-0.25,1.65,1.95,X40,BTT,BANKS
57,PGHH,0.18,-36.31,107.27,32.01,145879.0,-77528.0,135992.0,17616.87,-56.92,36.0,X-MC,19.18,57.0,-0.53,0.85,0.27,X40,ATH,FMCG
83,VBL,-0.18,-10.19,51.04,35.66,161287.0,-35842.0,316002.0,669.42,-20.90,39.0,X-LC,7.74,13.0,-0.22,1.98,16.34,X40N,ATH,FMCG
20,DABUR,-0.07,-19.64,78.83,43.70,157136.0,-48733.0,199335.0,735.00,-27.04,39.0,X-MC,9.13,70.0,-0.31,1.25,1.43,XY24,BTT,FMCG
35,HDFCLIFE,0.18,-6.79,49.29,39.15,115193.0,-17032.0,233705.0,811.41,-30.57,41.0,X-LC,15.94,31.0,-0.15,1.46,1.41,X40,ATH,INSURANCE

In [18]:
# top 5 to accumulate based on Spread and CumlRnk
df_tmp = df_portfolio_features[df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])]
df_tmp = df_tmp[(df_tmp['CumlRnk'] < 100)].sort_values(by = 'Spread%', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
19,COLPAL,-0.51,-23.38,82.53,39.86,166546.0,-61565.0,201800.0,3683.41,-7.20,44.0,X-MC,1.64,62.0,-0.37,1.26,14.15,XY25,ATH,FMCG
11,BERGEPAINT,-1.93,-1.46,27.17,25.32,69007.0,-3766.0,253983.0,680.00,-6.90,62.0,X-MC,2.10,68.0,-0.05,1.59,33.19,XY24,NTT,PAINTS
8,BAJAJHLDNG,-1.02,2.23,25.44,28.24,66581.0,5712.0,261717.0,14274.15,-6.07,65.0,X-LC,2.59,28.0,0.09,1.64,31.72,X40,ATH,FINANCE
23,DMART,-0.39,-4.55,37.68,31.42,112142.0,-14174.0,297616.0,5391.45,-20.59,42.0,X-LC,3.23,14.0,-0.13,1.86,7.40,X40N,ATH,FMCG
26,GILLETTE,-0.31,-9.37,43.14,29.72,99265.0,-23796.0,230100.0,10978.86,-30.33,45.0,X-SC,3.41,83.0,-0.24,1.44,5.74,X40,ATH,FMCG

In [19]:
# top 5 to accumulate based on lowest Gained%
df_tmp = df_portfolio_features[df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])].sort_values(by = 'Gained%', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
57,PGHH,0.18,-36.31,107.27,32.01,145879.0,-77528.0,135992.0,17616.87,-56.92,36.0,X-MC,19.18,57.0,-0.53,0.85,0.27,X40,ATH,FMCG
35,HDFCLIFE,0.18,-6.79,49.29,39.15,115193.0,-17032.0,233705.0,811.41,-30.57,41.0,X-LC,15.94,31.0,-0.15,1.46,1.41,X40,ATH,INSURANCE
20,DABUR,-0.07,-19.64,78.83,43.70,157136.0,-48733.0,199335.0,735.00,-27.04,39.0,X-MC,9.13,70.0,-0.31,1.25,1.43,XY24,BTT,FMCG
34,HDFCBANK,-0.08,-10.39,46.25,31.05,121483.0,-30455.0,262665.0,1073.00,-25.47,35.0,X-LC,10.56,26.0,-0.25,1.65,1.95,X40,BTT,BANKS
47,ITC,-0.28,-21.35,58.54,24.70,182920.0,-84808.0,312470.0,452.00,-58.75,50.0,X-LC,11.32,1.0,-0.46,1.96,3.47,X40,NTT,FMCG

In [20]:
# top 5 to accumulate based on lowest CurrAlloc%
df_tmp = df_portfolio_features[df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])].sort_values(by = 'CurrAlloc%', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
10,BATAINDIA,-0.99,-53.37,189.96,35.20,113970.0,-68673.0,59997.0,2096.00,-21.30,63.0,X-SC,14.79,91.0,-0.60,0.38,20.54,X40,NTT,FOOTWEAR
62,RELAXO,2.51,-44.75,175.67,52.31,140889.0,-64959.0,80201.0,1176.00,-41.15,61.0,X-SC,11.10,92.0,-0.46,0.50,79.32,X40N,NTT,FOOTWEAR
58,QUESS,-1.65,25.95,38.07,73.90,51208.0,27717.0,134510.0,424.00,-32.23,57.0,X-SC,39.40,80.0,0.54,0.84,85.13,XY24,NTT,MISC
57,PGHH,0.18,-36.31,107.27,32.01,145879.0,-77528.0,135992.0,17616.87,-56.92,36.0,X-MC,19.18,57.0,-0.53,0.85,0.27,X40,ATH,FMCG
40,ICICIPRULI,-1.97,-16.21,55.48,30.28,91581.0,-31935.0,165070.0,787.27,-38.68,50.0,X-MC,13.70,78.0,-0.35,1.03,9.98,X40,ATH,INSURANCE

In [21]:
# top 5 to accumulate based on CumlRnk
df_tmp = df_portfolio_features.sort_values(by = 'CumlRnk', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
47,ITC,-0.28,-21.35,58.54,24.70,182920.0,-84808.0,312470.0,452.00,-58.75,50.0,X-LC,11.32,1.0,-0.46,1.96,3.47,X40,NTT,FMCG
75,TCS,2.38,-28.68,74.14,24.20,244967.0,-132861.0,330412.0,4230.71,-39.69,62.0,X-LC,15.69,2.0,-0.54,2.07,23.21,X40,ATH,IT
45,INFY,0.77,-16.43,67.97,40.38,213855.0,-61838.0,314632.0,1972.00,-37.23,62.0,X-LC,16.36,3.0,-0.29,1.97,19.15,X40,NTT,IT
77,TMPV,0.29,-17.60,73.24,42.75,251130.0,-73221.0,342886.0,600.00,-83.62,55.0,X-LC,5.39,4.0,-0.29,2.15,17.90,XY24,NTT,AUTO
33,HCLTECH,0.99,-9.83,37.47,23.97,104570.0,-30409.0,279077.0,1853.42,-8.19,68.0,X-LC,13.59,8.0,-0.29,1.75,31.69,X40,ATH,IT

In [22]:
# top 5 for average up
df_tmp = df_portfolio_features[(df_portfolio_features['Dev%_200'] > 5)].sort_values(by = 'CurrAlloc%', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
44,INDUSINDBK,-0.88,-25.63,78.70,32.89,45186.0,-19790.0,57416.0,1800.00,-370.31,52.0,L-MC,13.87,258.0,-0.44,0.36,41.55,XR,NTT,BANKS
62,RELAXO,2.51,-44.75,175.67,52.31,140889.0,-64959.0,80201.0,1176.00,-41.15,61.0,X-SC,11.10,92.0,-0.46,0.50,79.32,X40N,NTT,FOOTWEAR
3,ALKYLAMINE,-2.21,-19.21,138.33,92.54,112832.0,-19396.0,81567.0,4520.85,-13.41,57.0,H-SC,13.35,142.0,-0.17,0.51,54.89,SR,ATH,CHEMICALS
79,TTKPRESTIG,0.18,-18.19,22.35,0.09,18426.0,-18332.0,82445.0,770.00,91.46,49.0,M-SC,13.83,250.0,-0.99,0.52,48.39,OX40N,NTT,DURABLES
12,BOSCH-HCIL,2.32,-26.24,35.56,-0.01,33522.0,-33535.0,94270.0,2282.00,19182.61,85.0,M-SC,3.84,231.0,-1.00,0.59,60.46,OX40N,BTT,AC

In [23]:
# top 5 RSP
df_tmp = df_portfolio_features.sort_values(by = 'RSP', ascending=False)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
12,BOSCH-HCIL,2.32,-26.24,35.56,-0.01,33522.0,-33535.0,94270.0,2282.00,19182.61,85.0,M-SC,3.84,231.0,-1.00,0.59,60.46,OX40N,BTT,AC
30,HAPPSTMNDS,-0.63,-49.61,263.36,83.08,170067.0,-63589.0,64576.0,1466.54,-40.12,65.0,H-SC,10.40,152.0,-0.37,0.40,20.95,AR,ATH,IT
33,HCLTECH,0.99,-9.83,37.47,23.97,104570.0,-30409.0,279077.0,1853.42,-8.19,68.0,X-LC,13.59,8.0,-0.29,1.75,31.69,X40,ATH,IT
75,TCS,2.38,-28.68,74.14,24.20,244967.0,-132861.0,330412.0,4230.71,-39.69,62.0,X-LC,15.69,2.0,-0.54,2.07,23.21,X40,ATH,IT
5,ATULAUTO,-1.63,-1.43,47.68,45.57,92647.0,-2822.0,194310.0,844.00,4224.32,73.0,M-SC,8.55,248.0,-0.03,1.22,49.53,XY24,NTT,AUTO

In [24]:
# Top N allocation
df_tmp = df_portfolio_features.sort_values(by = 'CurrAlloc%', ascending=False)
top_n_values = [10, 25, 50]

sum_df = pd.DataFrame({
    'Top_N': top_n_values,
    'Sum_Alloc%': [df_tmp['CurrAlloc%'].head(n).sum() for n in top_n_values]
})

sum_df

   Top_N  Sum_Alloc%
0     10       19.69
1     25       44.61
2     50       76.85

In [25]:
# market-cap-wise allocation
df_tmp = df_portfolio_features[cols]
df_tmp.groupby(df_tmp['Conviction'].str[-2:])['CurrAlloc%'].sum().sort_values(ascending=False)

Conviction
SC    39.38
LC    37.70
MC    22.95
Name: CurrAlloc%, dtype: float64

In [26]:
# criteria-wise allocation
df_portfolio_features.groupby('Criteria')['CurrAlloc%'].sum().sort_values(ascending=False)

Criteria
X40      26.37
XY24     25.10
X40N     18.46
XR        9.09
XY25      7.28
OX40N     6.89
AR        5.99
SR        0.85
Name: CurrAlloc%, dtype: float64

In [27]:
# conviction-wise allocation
df_portfolio_features.groupby('Conviction')['CurrAlloc%'].sum().sort_values(ascending=False)

Conviction
X-LC    35.65
H-SC    19.22
X-MC    18.73
X-SC     9.93
M-SC     9.70
H-MC     2.59
M-MC     1.27
H-LC     1.24
M-LC     0.81
L-SC     0.53
L-MC     0.36
Name: CurrAlloc%, dtype: float64

In [28]:
# sector-wise stats
df_tmp = df_portfolio_features.groupby('Category')[['CurrAlloc%', 'Current', 'Current P/L', 'FTT Amt']].sum().sort_values(by=['Current', 'Current P/L'], ascending=False)
df_tmp['Current P/L%'] = round(df_tmp['Current P/L'] * 100 / df_tmp['Current'], 2)
df_tmp['FTT%'] = round(df_tmp['FTT Amt'] * 100 / df_tmp['Current'], 2)
cols = ['CurrAlloc%', 'Current P/L%', 'FTT%']
df_tmp[cols].sort_values(by=['CurrAlloc%'], ascending=False)

               CurrAlloc%  Current P/L%    FTT%
Category
FMCG                15.51        -20.37   63.72
IT                  11.16        -33.77  100.17
FINANCE              9.36        -14.41   62.48
AUTO                 8.39         -1.09   37.29
MISC                 6.86        -22.60   75.21
BANKS                6.07        -10.31   57.89
PHARMA               5.57          6.67   19.79
INSURANCE            5.53         -5.09   42.25
PAINTS               5.38        -14.68   34.24
ELECTRICAL           4.13         -7.35   44.93
HEALTHCARE           2.09         -7.49   35.54
AC                   1.80        -11.45   41.67
APPARELS             1.76          4.51   27.56
REFINERIES           1.70         -9.78   46.66
FOOTWEAR             1.67        -65.92  132.45
BREWERIES            1.64         10.31    8.31
DURABLES             1.54        -58.17   96.65
TRAVEL               1.47        -91.12  186.82
CERAMICS             1.37        -40.17   82.75
ENGINEERING          1.22        -24.77   81.84
CABLES               1.21         23.44   59.18
CHEMICALS            1.11        -48.56  169.14
CEMENT               1.03        -63.00  184.94
JEWELLERY            0.99       -101.73  171.81
ENTERTAINMENT        0.68        -77.08  182.68
TEXTILES             0.40        -45.73   87.28
HOTELS               0.39        -82.53  146.91

In [29]:
# money to be made criteria-wise
df_portfolio_features.groupby('Criteria')['FTT Amt'].agg(['sum', 'count']).sort_values(by='sum', ascending=False)

                sum  count
Criteria
XY24      3397715.0     20
X40       2015963.0     18
XR        1347143.0     13
X40N      1135367.0     12
AR        1074640.0      8
OX40N      695025.0     10
XY25       538096.0      5
SR         281286.0      2

In [30]:
# money to be made conviction-wise
df_portfolio_features.groupby('Conviction')['FTT Amt'].agg(['sum', 'count']).sort_values(by='sum', ascending=False)

                  sum  count
Conviction
H-SC        3284627.0     23
X-LC        2369367.0     20
X-MC        1464642.0     14
M-SC        1372846.0     14
X-SC        1218059.0      9
H-MC         284804.0      2
L-SC         206401.0      2
M-LC         162066.0      1
L-MC          45186.0      1
M-MC          43041.0      1
H-LC          34196.0      1

In [31]:
# money to be made criteria and conviction-wise
df_portfolio_features.groupby(['Conviction', 'Criteria'])['FTT Amt'].agg(['sum', 'count']).sort_values(by='sum', ascending=False)

                           sum  count
Conviction Criteria
X-LC       X40       1161695.0      9
H-SC       XY24       984095.0      5
           AR         923669.0      5
M-SC       XY24       821067.0      6
H-SC       XR         802945.0      7
X-SC       XY24       707696.0      4
X-MC       X40        641033.0      7
X-LC       X40N       493280.0      6
           XY24       414383.0      2
X-MC       X40N       344959.0      3
X-SC       X40N       297128.0      3
H-SC       OX40N      292632.0      4
M-SC       OX40N      287382.0      5
H-SC       SR         281286.0      2
X-MC       XY25       252507.0      2
H-MC       XY24       244331.0      1
X-LC       XY25       242548.0      2
X-MC       XY24       226143.0      2
X-SC       X40        213235.0      2
M-SC       XR         188095.0      2
M-LC       XR         162066.0      1
L-SC       OX40N      115011.0      1
           XR          91390.0      1
M-SC       AR          76302.0      1
X-LC       XR          57461.0      1
L-MC       XR          45186.0      1
M-MC       XY25        43041.0      1
H-MC       AR          40473.0      1
H-LC       AR          34196.0      1

In [32]:
# notebook execution time

end_time = time.time()
execution_time = round(end_time - start_time, 0)
print(f"Notebook execution time: {execution_time} seconds")

Notebook execution time: 26.0 seconds