<a href="https://colab.research.google.com/github/ankit-rathi/Quantvesting_v2/blob/main/myStocks_Portfolio_Analysis.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
'''
!pip install pandas==2.2.2 -qq
!pip install pyxirr -qq
!pip install ta -qq
!pip install yfinance==0.2.59 -qq
'''

'\n!pip install pandas==2.2.2 -qq\n!pip install pyxirr -qq\n!pip install ta -qq\n!pip install yfinance==0.2.59 -qq\n'

In [2]:
# import libraries

import numpy as np
import pandas as pd
import datetime
import warnings
warnings.filterwarnings('ignore')
import yfinance as yfin
import ta
import matplotlib.pyplot as plt
import requests

In [3]:
# notebook start time
import time
import datetime
import pytz

start_time = time.time()

# function to print date timestamp
def print_date_time():
  tz_NY = pytz.timezone('Asia/Kolkata')
  datetime_NY = datetime.datetime.now(tz_NY)
  print("Run date time (IST):", datetime_NY.strftime("%Y-%m-%d %H:%M:%S"))

In [4]:
# function to get booked and reserved amount
def get_amt():
  # fetch the JSON data from the URL
  url = "https://raw.githubusercontent.com/ankit-rathi/Tradevesting_v1/main/data/myPortfolioAmts.json"
  response = requests.get(url)
  pf_amts = response.json()  # parse the JSON data

  # extract values from the JSON
  py_booked_amt_dm = pf_amts["py_booked_amt_dm"]
  py_booked_amt_sv = pf_amts["py_booked_amt_sv"]
  cy_booked_amt_dm = pf_amts["cy_booked_amt_dm"]
  cy_booked_amt_sv = pf_amts["cy_booked_amt_sv"]
  reserve_amt_dm = pf_amts["reserve_amt_dm"]
  reserve_amt_sv = pf_amts["reserve_amt_sv"]

  # perform calculations
  py_booked_amt = py_booked_amt_dm + py_booked_amt_sv
  cy_booked_amt = cy_booked_amt_dm + cy_booked_amt_sv
  reserve_amt = reserve_amt_dm + reserve_amt_sv
  total_booked_amt = py_booked_amt + cy_booked_amt

  return total_booked_amt, reserve_amt, cy_booked_amt, py_booked_amt

gen_output = 0

In [5]:
# function to format the amount
def format_amt(number):
    abs_number = abs(number)

    if abs_number >= 1_00_00_000:  # Crores
        formatted_amt = f"{number / 1_00_00_000:.2f} C"
    elif abs_number >= 1_00_000:  # Lakhs
        formatted_amt = f"{number / 1_00_000:.2f} L"
    elif abs_number >= 1_000:  # Thousands
        formatted_amt = f"{number / 1_000:.2f} K"
    else:
        formatted_amt = f"{number:.2f}"

    return formatted_amt

# function to set start and end date
def get_start_end_date():
  start_date = (datetime.date.today() + datetime.timedelta(days=-365)).strftime('%Y-%m-%d')
  end_date = (datetime.date.today() + datetime.timedelta(days=1)).strftime('%Y-%m-%d')
  return start_date, end_date

# function to fetch my portfolio csv
def get_mypfs_df():
  mypfs_df = pd.read_csv('https://raw.githubusercontent.com/ankit-rathi/Tradevesting_v1/main/data/myPortfolioStocks.csv')
  return mypfs_df

# function to fetch my prospects csv
def get_mypps_df():
  mypps_df = pd.read_csv('https://raw.githubusercontent.com/ankit-rathi/Tradevesting_v1/main/data/myProspectsScrips.csv')
  return mypps_df

# function to fetch screener data
def get_myscreen_df():
  myscreen_df = pd.read_csv('https://raw.githubusercontent.com/ankit-rathi/Tradevesting_v1/main/data/myScreenerDB.csv')
  return myscreen_df

# function to fetch momentum data
def get_myinvmt_df():
  myinvmt_df = pd.read_csv('https://raw.githubusercontent.com/ankit-rathi/Tradevesting_v1/main/data/myInvestments.csv')
  return myinvmt_df

# function to get the stock ids
def get_stock_ids(df_pf):
  stock_n100 = df_pf['Symbol'].unique()

  exclude = ['CADILAHC','MMTC', 'MASFIN']

  stock_ids = df_pf[~df_pf['Symbol'].isin(exclude) ]['Symbol'].unique()

  #mypf = mypf[mypf.Forecast.notnull()]
  #stock_ids = mypf['Symbol'].unique()

  #stock_ids.sort()
  return stock_ids

# get features from screener data
def get_screener_features():
  myscreen_df = get_myscreen_df()
  cols = ['Symbol', 'EPS', 'MedPE', 'ROCE%', 'ROE%', 'CapType']
  return myscreen_df[cols]

# get relative strength
def get_relative_strength(stock_list):

    # Dictionary to store stock tickers and their corresponding percentage price change
    stock_changes = {}

    # Loop through each stock and fetch its price data
    for stock in stock_list:
        try:
            # Download the stock data for the given date range
            stock_data = yfin.Ticker(stock + '.NS').history(period='1mo', interval='1d')[map(str.title, ['open', 'close', 'low', 'high', 'volume'])]

            # Calculate the percentage change for the stock
            if len(stock_data) > 0:
                start_price = stock_data['Close'].iloc[0]
                end_price = stock_data['Close'].iloc[-1]
                percent_change = round(((end_price - start_price) / start_price) * 100, 2)
                stock_changes[stock] = percent_change
            else:
                stock_changes[stock] = np.nan  # If no data is available, set to NaN

        except Exception as e:
            print(f"Error fetching data for {stock}: {e}")
            stock_changes[stock] = np.nan

    # Create a DataFrame with stock tickers and their percentage changes
    df = pd.DataFrame(list(stock_changes.items()), columns=['Symbol', 'Percent_Change'])

    # Drop any stocks with missing data (NaN values)
    df = df.dropna()

    # Calculate the percentile rank based on percentage change
    df['RSP'] = round(df['Percent_Change'].rank(pct=True) * 100, 2)
    cols = ['Symbol', 'RSP']
    df = df[cols]
    # Sort by percentile rank (optional)
    df = df.sort_values(by='RSP', ascending=False).reset_index(drop=True)

    return df

In [6]:
# function to get stock technicals
def stock_prec_dev(stock_symbol):
    #stock_symbol = 'ULTRACEMCO.NS'
    short_window = 20
    mid_window = 50
    long_window = 200
    moving_avg = 'SMA'

    start = datetime.datetime(*map(int, start_date.split('-')))
    end = datetime.datetime(*map(int, end_date.split('-')))

    stock_df = yfin.Ticker(stock_symbol + '.NS').history(period='max', interval='1d')[map(str.title, ['open', 'close', 'low', 'high', 'volume'])]

    stock_df['Max'] = round(max(stock_df['Close']),2)
    stock_df = stock_df[(stock_df.index <= end_date) & (stock_df.index >= start_date)]
    stock_df['200_SMA'] = round(stock_df['Close'].rolling(window = 200, min_periods = 1).mean(),0)
    stock_df['Dev%_200'] = round((stock_df['Close'] - stock_df['200_SMA'])*100/stock_df['200_SMA'],2)
    stock_df.dropna(axis = 0, inplace = True) # remove any null rows

    stock_df['20_SMA'] = stock_df['Close'].rolling(window=20).mean()
    stock_df['50_SMA'] = stock_df['Close'].rolling(window=50).mean()
    stock_df['Symbol'] = stock_symbol

    stock_df['Close'] = round(stock_df['Close'],2)
    stock_df['Min'] = round(min(stock_df['Close']),2)
    stock_df['RSI_14'] = ta.momentum.RSIIndicator(close=stock_df['Close'], window=14).rsi()
    stock_df['RSI_14'] = round(stock_df['RSI_14'],0)
    stock_df['Prev_Close'] = stock_df['Close'].shift(1)
    stock_df.drop(['Open', 'Low', 'High', 'Volume'], axis=1, inplace=True)
    stock_df = stock_df.tail(1)

    max_SMA = max(stock_df['20_SMA'].item(), stock_df['50_SMA'].item(), stock_df['200_SMA'].item())
    min_SMA = min(stock_df['20_SMA'].item(), stock_df['50_SMA'].item(), stock_df['200_SMA'].item())
    ABS_Spread = max_SMA - min_SMA
    stock_df['Spread%'] = round((ABS_Spread / stock_df['200_SMA'].item()) * 100,2)

    return stock_df

# function to compute stock attributes
def get_common_features(stock_ids, df_mypf):

  df_prec_dev = pd.DataFrame()
  df_tmp = get_screener_features()
  df_rs = get_relative_strength(stock_ids)

  for stock_id in stock_ids:
      tmp = stock_prec_dev(stock_id)
      tmp = tmp.reset_index()
      df_prec_dev = pd.concat([df_prec_dev, tmp], ignore_index = True)
  df_prec_dev = pd.merge(df_prec_dev, df_mypf, on= 'Symbol')
  df_prec_dev = pd.merge(df_prec_dev, df_tmp, on= 'Symbol', how='left')
  df_prec_dev = pd.merge(df_prec_dev, df_rs, on= 'Symbol', how='left')
  #print(df_prec_dev.columns)
  df_prec_dev['Curr_PE'] = round(df_prec_dev['Close']/df_prec_dev['EPS'],1)
  df_prec_dev['Dev%_PE'] = round((df_prec_dev['Curr_PE'] - df_prec_dev['MedPE'])*100/df_prec_dev['MedPE'],2)
  df_prec_dev['Conviction'] = df_prec_dev['Conviction'] + '-' + df_prec_dev['CapType']
  return df_prec_dev

# function to arrange stock features
def arrange_features(df_stocks, common_cols, diff_cols):
  df_stocks_common = df_stocks[common_cols].drop_duplicates()
  df_stocks_diff = df_stocks[diff_cols]
  df_stocks_diff['Investment'] = df_stocks_diff['AvgCost'] * df_stocks_diff['Shares']
  df_stocks_diff = df_stocks_diff.groupby(['Symbol'])[['Shares', 'Investment']].aggregate(['sum']).reset_index()
  df_stocks_diff.columns = ['Symbol', 'Shares', 'Investment']
  df_stocks_diff['AvgCost'] = round(df_stocks_diff['Investment']/df_stocks_diff['Shares'],2)
  df_stocks = pd.merge(df_stocks_diff, df_stocks_common, on='Symbol')
  return df_stocks

# plot fact distribution across dimension
def plot_pie_chart(df, dimension, fact):
  # grouping the data by category and calculating the sum of fact for each type
  grouped_data = df.groupby(dimension)[fact].sum()

  # sorting the grouped data in descending order
  grouped_data = grouped_data.sort_values(ascending=False)

  # creating a pie chart
  grouped_data.plot.pie(autopct='%1.1f%%', startangle=90, figsize=(6, 6))

  # adding a title and displaying the plot
  plt.title(f'{dimension} {fact} Distribution')
  plt.ylabel('')  # To hide the y-label
  plt.show()

In [7]:
# function to get portfolio features

def get_portfolio_features(df_common_features):

  print_date_time()
  print('-------------------')

  #df_common_features["Target"] = df_common_features["Target"].fillna(df_common_features["Max"])
  df_common_features['NTT'] = np.where(df_common_features['Strategy']== 'NTT', df_common_features["Target"], df_common_features['Max'])
  df_common_features['LTT'] = np.where(df_common_features['Strategy']== 'BTT', df_common_features["Target"], df_common_features['Max'])
  df_common_features['BOL'] = df_common_features['Min']

  tmp_df = df_common_features[df_common_features['Symbol'].isin(mypf_df[mypf_df['InPortfolio'] != 'NA'].Symbol.values)]
  print('qualified stocks: '+str(len(tmp_df['Symbol'].unique())))
  tmp_df1 = tmp_df[tmp_df['LatestQtr'] == 1]
  print('with latest results: '+str(len(tmp_df1['Symbol'].unique())))
  tmp_df1 = tmp_df1[tmp_df1['StarStock'] == 1]
  print('still star stocks: '+str(len(tmp_df1['Symbol'].unique())))
  tmp_df['Investment'] = tmp_df['AvgCost'] * tmp_df['Shares']
  tmp_df['Current'] = round(tmp_df['Close'] * tmp_df['Shares'],0)
  tmp_df['Previous'] = tmp_df['Prev_Close'] * tmp_df['Shares']
  tmp_df['EstimatedST'] = tmp_df['NTT'] * tmp_df['Shares']
  tmp_df['EstimatedLT'] = tmp_df['LTT'] * tmp_df['Shares']
  tmp_df['Current P/L'] = round((tmp_df['Current'] - tmp_df['Investment']),0)
  tmp_df['Today P/L%'] = round((tmp_df['Current'] - tmp_df['Previous'])*100/tmp_df['Previous'],2)
  tmp_df['Current P/L%'] = round((tmp_df['Current'] - tmp_df['Investment'])*100/tmp_df['Investment'],2)
  tmp_df['EstimatedST P/L%'] = round((tmp_df['EstimatedST'] - tmp_df['Investment'])*100/tmp_df['Investment'],2)
  tmp_df['EstimatedLT P/L%'] = round((tmp_df['EstimatedLT'] - tmp_df['Investment'])*100/tmp_df['Investment'],2)
  tmp_df['NTT%'] = round((tmp_df['NTT'] - tmp_df['Close'])*100/tmp_df['Close'],2)
  tmp_df['LTT%'] = round((tmp_df['LTT'] - tmp_df['Close'])*100/tmp_df['Close'],2)
  tmp_df['Gained%'] = round((tmp_df['Close'] - tmp_df['BOL'])*100/tmp_df['BOL'],2)
  investment = round(sum(tmp_df['AvgCost']*tmp_df['Shares']),0)
  current = round(sum(tmp_df['Close']*tmp_df['Shares']),0)
  tmp_df['InitAlloc%'] = round(tmp_df['Investment']*100/investment,2)
  tmp_df['CurrAlloc%'] = round(tmp_df['Current']*100/current,2)
  tmp_df['FTT'] = tmp_df['LTT']
  tmp_df.loc[tmp_df['Strategy'] == 'NTT', 'FTT'] = tmp_df['NTT']
  tmp_df['FTT%'] = tmp_df['LTT%']
  tmp_df.loc[tmp_df['Strategy'] == 'NTT', 'FTT%'] = tmp_df['NTT%']
  tmp_df['FTT Amt'] = round(tmp_df['FTT%'] * tmp_df['Current']/100,0)
  tmp_df['OTT%'] = round((tmp_df['FTT'] - tmp_df['AvgCost'])*100/tmp_df['AvgCost'],2)
  tmp_df['RRR Ind'] = round(tmp_df['Current P/L']/tmp_df['FTT Amt'],2)
  tmp_df['Risk Ind'] = round(tmp_df['Current P/L%']*tmp_df['CurrAlloc%'],0)

  return tmp_df

# function to print portfolio features
def print_portfolio_stats(df_portfolio_features, myinvmt_df):
  from pyxirr import xirr

  total_booked_amt, reserve_amt, cy_booked_amt, py_booked_amt = get_amt()

  dates = myinvmt_df['Date'].values
  dates = np.append(dates, datetime.date.today().strftime('%d-%b-%y'))
  investment = myinvmt_df['Investment'].values
  dates= pd.to_datetime(dates)

  current = round(sum(df_portfolio_features['Close']*df_portfolio_features['Shares']),0) + reserve_amt
  investment_xirr = np.append(investment, current)
  cagr = round(xirr(pd.DataFrame({"dates": dates, "amounts": investment_xirr}))*100,2)

  investment = -sum(investment)
  invested = round(sum(df_portfolio_features['AvgCost']*df_portfolio_features['Shares']),0) + reserve_amt
  previous = round(sum(df_portfolio_features['Prev_Close']*df_portfolio_features['Shares']),0) + reserve_amt
  cy_invested = investment + py_booked_amt

  today_pnl_amount = current-previous
  today_pnl_percentage = round((current-previous)*100/previous,2)

  curr_pnl_amount = current-invested
  curr_pnl_percentage = round((curr_pnl_amount)*100/(cy_invested),2)

  cy_pnl_amount = cy_booked_amt + curr_pnl_amount
  cy_pnl_percentage = round((cy_pnl_amount)*100/cy_invested,2)

  overall_pnl_amount = total_booked_amt + curr_pnl_amount
  overall_pnl_percentage = round((overall_pnl_amount)*100/investment,2)

  estimate_st = round(sum(df_portfolio_features['FTT']*df_portfolio_features['Shares']),0)  + reserve_amt
  est_st_pnl_amount = estimate_st-current
  est_st_pnl_percentage = round((est_st_pnl_amount)*100/current,2)

  estimate_lt = round(sum(df_portfolio_features['LTT']*df_portfolio_features['Shares']),0)  + reserve_amt
  est_lt_pnl_amount = estimate_lt-current
  est_lt_pnl_percentage = round((est_lt_pnl_amount)*100/current,2)

  total_profit = round(sum(df_portfolio_features[df_portfolio_features['Current P/L%'] > 0]['Current']) - sum(df_portfolio_features[df_portfolio_features['Current P/L%'] > 0]['Investment']),0)
  total_loss = round(sum(df_portfolio_features[df_portfolio_features['Current P/L%'] < 0]['Current']) - sum(df_portfolio_features[df_portfolio_features['Current P/L%'] < 0]['Investment']),0)

  cy_booked_percentage = round((cy_booked_amt)*100/current,2)
  py_booked_percentage = round((py_booked_amt)*100/investment,2)
  total_booked_percentage = round((total_booked_amt)*100/investment,2)

  print('-------------------')
  print('Initial Investment: ', format_amt(investment))
  print('CY Investment: ', format_amt(cy_invested))
  print('Reserve: ', format_amt(reserve_amt))
  print('Current: ',  format_amt(current))
  print('-------------------')
  print('Today PnL: '+ '{} ({}%)'.format(format_amt(today_pnl_amount), today_pnl_percentage))
  print('Current PnL: '+ '{} ({}%)'.format(format_amt(curr_pnl_amount), curr_pnl_percentage))
  print('CY Booked + Current PnL: '+ '{} ({}%)'.format(format_amt(cy_pnl_amount), cy_pnl_percentage))
  print('-------------------')
  print('Total profit: ', format_amt(total_profit))
  print('Total loss: ', format_amt(total_loss))
  print('-------------------')
  print('Total Booked + Current PnL: '+ '{} ({}%)'.format(format_amt(overall_pnl_amount), overall_pnl_percentage))
  print('Total Booked PnL: '+ '{} ({}%)'.format(format_amt(total_booked_amt), total_booked_percentage))
  print('Curr Year Booked PnL: '+ '{} ({}%)'.format(format_amt(cy_booked_amt), cy_booked_percentage))
  print('Prev Year Booked PnL: '+ '{} ({}%)'.format(format_amt(py_booked_amt), py_booked_percentage))
  print('===================')
  print('Est FTT: ',  format_amt(estimate_st))
  print('Est FTT PnL: '+ '{} ({}%)'.format(format_amt(est_st_pnl_amount), est_st_pnl_percentage))

  print('===================')
  print('Deployed: ', format_amt(investment))

  print('Current: ', format_amt(current))

  print('CAGR/XIRR %: '+'{}%'.format(cagr))

In [8]:
# get start and end date
start_date, end_date = get_start_end_date()

# get portfolio and prospects data
mypfs_df = get_mypfs_df()
mypps_df = get_mypps_df()
myinvmt_df = get_myinvmt_df()

# merge above datasets
mypf_df = pd.merge(mypfs_df, mypps_df, on="Symbol")

# seggregate dm and sv portfolio
dm_pf = mypf_df[mypf_df['InPortfolio'] == 'DM']
sv_pf = mypf_df[mypf_df['InPortfolio'] == 'SV']

# build portfolio stock dataframe
dm_stocks = get_stock_ids(dm_pf)
sv_stocks = get_stock_ids(sv_pf)
df_stocks = pd.concat([dm_pf,sv_pf], ignore_index = True)

# arrange common and diff stock features
common_cols = ['Symbol', 'Target', 'Criteria', 'Strategy', 'CumlRnk', 'LatestQtr', 'StarStock', 'Conviction', 'Category', 'InFolio', 'XIRR', 'MBQ']
diff_cols = ['Symbol', 'AvgCost', 'Shares']
df_stocks = arrange_features(df_stocks, common_cols, diff_cols)

# get common features
stock_ids = df_stocks['Symbol'].values
df_common_features = get_common_features(stock_ids, df_stocks)

df_common_features.reset_index(drop=True, inplace=True)
df_common_features.drop(['Date'], axis=1, inplace=True)
# get and print portfolio features
df_portfolio_features = get_portfolio_features(df_common_features)

print_portfolio_stats(df_portfolio_features, myinvmt_df)

df = df_portfolio_features
#plot_pie_chart(df, 'CapType', 'Current')
list_ox40n = list(df[df['MBQ'].str.contains('OX40N', na=False)]['Symbol'].values)

Run date time (IST): 2026-07-27 11:19:45
-------------------
qualified stocks: 92
with latest results: 31
still star stocks: 20
-------------------
Initial Investment:  1.40 C
CY Investment:  1.82 C
Reserve:  1.49 K
Current:  1.52 C
-------------------
Today PnL: 1.26 L (0.83%)
Current PnL: -30.81 L (-16.89%)
CY Booked + Current PnL: -28.73 L (-15.75%)
-------------------
Total profit:  4.71 L
Total loss:  -35.52 L
-------------------
Total Booked + Current PnL: 14.14 L (10.14%)
Total Booked PnL: 44.95 L (32.22%)
Curr Year Booked PnL: 2.08 L (1.37%)
Prev Year Booked PnL: 42.87 L (30.73%)
===================
Est FTT:  2.55 C
Est FTT PnL: 1.02 C (67.23%)
===================
Deployed:  1.40 C
Current:  1.52 C
CAGR/XIRR %: 3.94%

In [9]:
# top 5 near their targets
cols = ['Symbol', 'Today P/L%', 'Current P/L%', 'FTT%', 'OTT%', 'FTT Amt', 'Current P/L', 'Current', 'FTT', 'Dev%_PE', 'RSI_14','Conviction', 'Spread%',  'CumlRnk', 'RRR Ind', 'CurrAlloc%', 'Gained%', 'Criteria', 'Strategy', 'Category']
df_tmp = df_portfolio_features[~df_portfolio_features['Symbol'].isin(['ENRIN','BLUSPRING','DIGITIDE'])]
df_tmp = df_tmp.sort_values(by = 'FTT Amt', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
59,PIDILITIND,2.71,14.34,2.78,17.52,4486.0,20240.0,161350.0,1658.32,-19.93,62.0,X-LC,8.05,5.0,4.51,1.06,27.60,X40,ATH,CHEMICALS
68,SATIN,-1.07,47.40,3.01,51.83,12258.0,130962.0,407246.0,274.00,31.41,59.0,H-SC,45.83,159.0,10.68,2.67,98.39,XY24,NTT,FINANCE
56,MEDANTA,1.90,19.50,6.37,27.12,13437.0,34430.0,210947.0,1486.00,15.88,69.0,X-SC,12.10,87.0,2.56,1.38,45.35,XY24,NTT,HEALTHCARE
83,TTKPRESTIG,2.00,-14.70,17.34,0.09,14906.0,-14815.0,85962.0,770.00,99.57,62.0,M-SC,11.80,250.0,-0.99,0.56,53.07,OX40N,NTT,DURABLES
73,SONACOMS,-0.30,23.83,12.00,38.69,15032.0,24106.0,125265.0,801.69,-1.84,72.0,M-MC,26.62,193.0,1.60,0.82,77.72,AR,ATH,AUTO

In [10]:
# top 5 today
df_tmp = df_portfolio_features.sort_values(by = 'Today P/L%', ascending=False)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
50,KANSAINER,5.01,-32.30,67.60,13.47,123420.0,-87093.0,182574.0,340.0,-41.86,49.0,H-SC,5.08,162.0,-0.71,1.20,29.05,XY24,NTT,PAINTS
85,VAIBHAVGBL,4.46,-18.79,97.96,60.77,145406.0,-34341.0,148434.0,521.0,71.35,63.0,H-SC,8.77,160.0,-0.24,0.97,51.02,XR,NTT,JEWELLERY
89,WHIRLPOOL,3.90,-35.76,183.20,81.92,135097.0,-41055.0,73743.0,2270.0,-62.43,55.0,M-SC,15.40,210.0,-0.30,0.48,5.83,XR,NTT,DURABLES
15,CAMS,3.48,3.24,20.57,24.48,53487.0,8168.0,260024.0,950.0,-1.06,55.0,X-SC,4.50,89.0,0.15,1.71,27.24,X40N,NTT,MISC
45,INFY,3.33,-26.78,83.34,34.24,190934.0,-83785.0,229103.0,1972.0,-42.31,50.0,X-LC,20.35,3.0,-0.44,1.50,9.16,X40,NTT,IT

In [11]:
# bottom 5 today
df_tmp = df_portfolio_features.sort_values(by = 'Today P/L%', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
67,ROUTE,-4.93,-58.98,309.89,68.16,169169.0,-78476.0,54590.0,2215.45,-66.75,46.0,H-SC,8.19,141.0,-0.46,0.36,30.05,SR,ATH,IT
75,SURYODAY,-1.55,8.29,13.62,23.03,26411.0,14841.0,193912.0,216.00,110.53,58.0,H-SC,24.55,166.0,0.56,1.27,64.60,XR,NTT,BANKS
68,SATIN,-1.07,47.40,3.01,51.83,12258.0,130962.0,407246.0,274.00,31.41,59.0,H-SC,45.83,159.0,10.68,2.67,98.39,XY24,NTT,FINANCE
0,5PAISA,-0.79,-29.53,60.21,12.90,92713.0,-64514.0,153982.0,593.00,127.16,53.0,H-SC,14.06,170.0,-0.70,1.01,48.59,OX40N,NTT,FINANCE
12,BOSCH-HCIL,-0.79,-42.06,72.58,-0.01,53745.0,-53756.0,74049.0,2282.00,15052.17,45.0,M-SC,6.91,231.0,-1.00,0.49,26.04,OX40N,BTT,AC

In [12]:
# top 5 to exit based on CumlRnk
df_tmp = df_portfolio_features[~df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])]
df_tmp = df_tmp[(df_tmp['Current P/L%'] > -1) & (df_tmp['Current P/L%'] < 1)].sort_values(by = 'CumlRnk', ascending=False)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
63,RECLTD,1.31,-0.83,21.74,20.74,43804.0,-1678.0,201492.0,446.0,9.37,60.0,M-MC,2.21,191.0,-0.04,1.32,20.08,XY25,NTT,FINANCE
72,SIS,-0.55,-0.06,21.34,21.26,23680.0,-69.0,110963.0,528.0,2649.74,54.0,H-SC,24.30,168.0,-0.00,0.73,64.99,OX40N,NTT,MISC

In [13]:
# OX40N stocks to exit
df_tmp = df_portfolio_features[(df_portfolio_features['Symbol'].isin(list_ox40n))].sort_values(by = 'Current P/L%', ascending=False)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
25,FINCABLES,-0.06,26.44,64.43,107.91,120279.0,39038.0,186682.0,1641.55,13.65,40.0,M-SC,20.33,220.0,0.32,1.23,40.45,OX40N,ATH,CABLES
72,SIS,-0.55,-0.06,21.34,21.26,23680.0,-69.0,110963.0,528.00,2649.74,54.0,H-SC,24.30,168.0,-0.00,0.73,64.99,OX40N,NTT,MISC
83,TTKPRESTIG,2.00,-14.70,17.34,0.09,14906.0,-14815.0,85962.0,770.00,99.57,62.0,M-SC,11.80,250.0,-0.99,0.56,53.07,OX40N,NTT,DURABLES
16,CERA,1.81,-19.90,54.67,23.89,77029.0,-35005.0,140898.0,9475.00,-22.67,50.0,H-SC,14.22,153.0,-0.45,0.92,36.97,OX40N,NTT,CERAMICS
43,INDIGOPNTS,3.19,-23.11,30.08,0.02,40373.0,-40341.0,134218.0,1408.00,104.80,59.0,M-SC,3.93,222.0,-1.00,0.88,52.28,OX40N,NTT,PAINTS

In [14]:
# top 5 to book for rotation
df_tmp = df_portfolio_features[(df_portfolio_features['Current P/L%'] > 20) ].sort_values(by = 'CumlRnk', ascending=False)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
25,FINCABLES,-0.06,26.44,64.43,107.91,120279.0,39038.0,186682.0,1641.55,13.65,40.0,M-SC,20.33,220.0,0.32,1.23,40.45,OX40N,ATH,CABLES
73,SONACOMS,-0.30,23.83,12.00,38.69,15032.0,24106.0,125265.0,801.69,-1.84,72.0,M-MC,26.62,193.0,1.60,0.82,77.72,AR,ATH,AUTO
68,SATIN,-1.07,47.40,3.01,51.83,12258.0,130962.0,407246.0,274.00,31.41,59.0,H-SC,45.83,159.0,10.68,2.67,98.39,XY24,NTT,FINANCE
60,QUESS,0.24,21.44,43.19,73.90,56014.0,22899.0,129692.0,424.00,-34.44,66.0,X-SC,35.56,80.0,0.41,0.85,76.80,XY24,NTT,MISC

In [15]:
# top 5 to monitor for exit
df_tmp = df_portfolio_features[~df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])]
df_tmp = df_tmp[(df_tmp['Current P/L%'] > 0) ].sort_values(by = 'Dev%_PE', ascending=False)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
75,SURYODAY,-1.55,8.29,13.62,23.03,26411.0,14841.0,193912.0,216.00,110.53,58.0,H-SC,24.55,166.0,0.56,1.27,64.60,XR,NTT,BANKS
74,STARHEALTH,-0.34,12.00,31.48,47.26,99120.0,33744.0,314867.0,761.00,76.87,51.0,H-SC,18.66,173.0,0.34,2.07,36.64,XY24,NTT,INSURANCE
68,SATIN,-1.07,47.40,3.01,51.83,12258.0,130962.0,407246.0,274.00,31.41,59.0,H-SC,45.83,159.0,10.68,2.67,98.39,XY24,NTT,FINANCE
25,FINCABLES,-0.06,26.44,64.43,107.91,120279.0,39038.0,186682.0,1641.55,13.65,40.0,M-SC,20.33,220.0,0.32,1.23,40.45,OX40N,ATH,CABLES
91,ZYDUSLIFE,-0.17,16.71,16.10,35.51,39381.0,35029.0,244603.0,1285.01,1.80,45.0,H-MC,17.10,120.0,0.89,1.61,28.72,AR,ATH,PHARMA

In [16]:
# top 5 to book for rotation from weak conviction
df_tmp = df_portfolio_features[~df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])]
df_tmp = df_tmp[~df_tmp['Criteria'].isin(['XY25','XY24','X40', 'X40N'])].sort_values(by = 'RRR Ind', ascending=False)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
73,SONACOMS,-0.30,23.83,12.00,38.69,15032.0,24106.0,125265.0,801.69,-1.84,72.0,M-MC,26.62,193.0,1.60,0.82,77.72,AR,ATH,AUTO
91,ZYDUSLIFE,-0.17,16.71,16.10,35.51,39381.0,35029.0,244603.0,1285.01,1.80,45.0,H-MC,17.10,120.0,0.89,1.61,28.72,AR,ATH,PHARMA
75,SURYODAY,-1.55,8.29,13.62,23.03,26411.0,14841.0,193912.0,216.00,110.53,58.0,H-SC,24.55,166.0,0.56,1.27,64.60,XR,NTT,BANKS
25,FINCABLES,-0.06,26.44,64.43,107.91,120279.0,39038.0,186682.0,1641.55,13.65,40.0,M-SC,20.33,220.0,0.32,1.23,40.45,OX40N,ATH,CABLES
72,SIS,-0.55,-0.06,21.34,21.26,23680.0,-69.0,110963.0,528.00,2649.74,54.0,H-SC,24.30,168.0,-0.00,0.73,64.99,OX40N,NTT,MISC

In [17]:
# top 5 to accumulate based on lowest RSI_14
df_tmp = df_portfolio_features[df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])].sort_values(by = 'RSI_14', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
87,VBL,0.04,-7.61,46.52,35.37,135755.0,-24021.0,291821.0,670.16,-18.49,31.0,X-LC,6.77,13.0,-0.18,1.92,19.94,X40N,ATH,FMCG
34,HDFCBANK,-0.23,-11.34,44.78,28.37,93254.0,-26636.0,208249.0,1073.00,-24.48,33.0,X-LC,10.54,26.0,-0.29,1.37,2.98,X40,BTT,BANKS
81,TMPV,1.08,-25.50,83.32,36.58,220892.0,-90728.0,265113.0,600.00,-84.72,37.0,X-LC,7.30,4.0,-0.41,1.74,11.42,XY24,NTT,AUTO
35,HDFCLIFE,-0.20,-9.40,46.48,32.71,63082.0,-14082.0,135718.0,811.41,-29.23,42.0,X-LC,15.81,31.0,-0.22,0.89,1.96,X40,ATH,INSURANCE
65,RELIANCE,0.33,-17.69,52.24,25.30,86407.0,-35559.0,165404.0,1952.00,-19.65,44.0,X-LC,7.68,21.0,-0.41,1.09,1.86,XY25,BTT,REFINERIES

In [18]:
# top 5 to accumulate based on Spread and CumlRnk
df_tmp = df_portfolio_features[df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])]
df_tmp = df_tmp[(df_tmp['CumlRnk'] < 100)].sort_values(by = 'Spread%', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
11,BERGEPAINT,0.48,-7.79,35.90,25.32,85322.0,-20083.0,237666.0,680.00,-12.89,48.0,X-MC,1.56,68.0,-0.24,1.56,23.70,XY24,NTT,PAINTS
19,COLPAL,2.39,-18.90,72.45,39.86,154746.0,-49775.0,213590.0,3683.41,-1.82,62.0,X-MC,1.64,62.0,-0.32,1.40,20.82,XY25,ATH,FMCG
23,DMART,0.11,-3.29,34.01,29.60,82099.0,-8202.0,241398.0,5391.45,-18.44,45.0,X-LC,1.77,14.0,-0.10,1.58,10.34,X40N,ATH,FMCG
1,ABBOTINDIA,-0.66,-6.67,23.62,15.37,39427.0,-11935.0,166920.0,34390.26,-20.56,68.0,X-MC,2.44,58.0,-0.30,1.10,13.07,X40,ATH,PHARMA
17,CIPLA,-0.09,14.10,16.95,33.43,29621.0,21592.0,174753.0,1648.14,-11.85,46.0,X-LC,2.81,18.0,0.73,1.15,19.30,X40N,ATH,PHARMA

In [19]:
# top 5 to accumulate based on lowest Gained%
df_tmp = df_portfolio_features[df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])].sort_values(by = 'Gained%', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
65,RELIANCE,0.33,-17.69,52.24,25.30,86407.0,-35559.0,165404.0,1952.00,-19.65,44.0,X-LC,7.68,21.0,-0.41,1.09,1.86,XY25,BTT,REFINERIES
35,HDFCLIFE,-0.20,-9.40,46.48,32.71,63082.0,-14082.0,135718.0,811.41,-29.23,42.0,X-LC,15.81,31.0,-0.22,0.89,1.96,X40,ATH,INSURANCE
34,HDFCBANK,-0.23,-11.34,44.78,28.37,93254.0,-26636.0,208249.0,1073.00,-24.48,33.0,X-LC,10.54,26.0,-0.29,1.37,2.98,X40,BTT,BANKS
58,PGHH,0.26,-32.57,95.79,32.01,137907.0,-69552.0,143968.0,17616.87,-54.37,51.0,X-MC,19.52,57.0,-0.50,0.94,3.18,X40,ATH,FMCG
47,ITC,1.04,-24.56,57.82,19.06,148374.0,-83552.0,256614.0,452.00,-58.75,55.0,X-LC,12.56,1.0,-0.56,1.68,3.94,X40,NTT,FMCG

In [20]:
# top 5 to accumulate based on lowest CurrAlloc%
df_tmp = df_portfolio_features[df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])].sort_values(by = 'CurrAlloc%', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
10,BATAINDIA,0.82,-55.13,201.32,35.20,116232.0,-70935.0,57735.0,2096.00,-24.33,52.0,X-SC,17.24,91.0,-0.61,0.38,14.50,X40,NTT,FOOTWEAR
64,RELAXO,1.14,-47.22,188.55,52.31,144465.0,-68541.0,76619.0,1176.00,-43.76,56.0,X-SC,9.99,92.0,-0.47,0.50,71.31,X40N,NTT,FOOTWEAR
60,QUESS,0.24,21.44,43.19,73.90,56014.0,22899.0,129692.0,424.00,-34.44,66.0,X-SC,35.56,80.0,0.41,0.85,76.80,XY24,NTT,MISC
35,HDFCLIFE,-0.20,-9.40,46.48,32.71,63082.0,-14082.0,135718.0,811.41,-29.23,42.0,X-LC,15.81,31.0,-0.22,0.89,1.96,X40,ATH,INSURANCE
28,GODREJCP,0.54,-4.67,37.91,31.47,53708.0,-6942.0,141672.0,1469.04,0.20,53.0,X-LC,6.03,32.0,-0.13,0.93,8.70,X40N,ATH,FMCG

In [21]:
# top 5 to accumulate based on CumlRnk
df_tmp = df_portfolio_features.sort_values(by = 'CumlRnk', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
47,ITC,1.04,-24.56,57.82,19.06,148374.0,-83552.0,256614.0,452.00,-58.75,55.0,X-LC,12.56,1.0,-0.56,1.68,3.94,X40,NTT,FMCG
79,TCS,1.85,-32.60,84.26,24.20,263107.0,-151017.0,312256.0,4230.71,-42.97,64.0,X-LC,18.54,2.0,-0.57,2.05,16.44,X40,ATH,IT
45,INFY,3.33,-26.78,83.34,34.24,190934.0,-83785.0,229103.0,1972.00,-42.31,50.0,X-LC,20.35,3.0,-0.44,1.50,9.16,X40,NTT,IT
81,TMPV,1.08,-25.50,83.32,36.58,220892.0,-90728.0,265113.0,600.00,-84.72,37.0,X-LC,7.30,4.0,-0.41,1.74,11.42,XY24,NTT,AUTO
59,PIDILITIND,2.71,14.34,2.78,17.52,4486.0,20240.0,161350.0,1658.32,-19.93,62.0,X-LC,8.05,5.0,4.51,1.06,27.60,X40,ATH,CHEMICALS

In [22]:
# top 5 for average up
df_tmp = df_portfolio_features[(df_portfolio_features['Dev%_200'] > 5)].sort_values(by = 'CurrAlloc%', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
44,INDUSINDBK,0.94,-25.77,79.03,32.89,45291.0,-19898.0,57308.0,1800.00,-369.61,54.0,L-MC,13.80,258.0,-0.44,0.38,41.29,XR,NTT,BANKS
64,RELAXO,1.14,-47.22,188.55,52.31,144465.0,-68541.0,76619.0,1176.00,-43.76,56.0,X-SC,9.99,92.0,-0.47,0.50,71.31,X40N,NTT,FOOTWEAR
3,ALKYLAMINE,1.54,-22.61,148.81,92.54,116267.0,-22832.0,78131.0,4520.85,-17.07,50.0,H-SC,12.51,142.0,-0.20,0.51,48.36,SR,ATH,CHEMICALS
83,TTKPRESTIG,2.00,-14.70,17.34,0.09,14906.0,-14815.0,85962.0,770.00,99.57,62.0,M-SC,11.80,250.0,-0.99,0.56,53.07,OX40N,NTT,DURABLES
72,SIS,-0.55,-0.06,21.34,21.26,23680.0,-69.0,110963.0,528.00,2649.74,54.0,H-SC,24.30,168.0,-0.00,0.73,64.99,OX40N,NTT,MISC

In [23]:
# top 5 RSP
df_tmp = df_portfolio_features.sort_values(by = 'RSP', ascending=False)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
60,QUESS,0.24,21.44,43.19,73.90,56014.0,22899.0,129692.0,424.00,-34.44,66.0,X-SC,35.56,80.0,0.41,0.85,76.80,XY24,NTT,MISC
33,HCLTECH,1.89,-15.96,43.12,20.28,87669.0,-38609.0,203315.0,1853.42,-11.91,71.0,X-LC,16.35,8.0,-0.44,1.33,26.50,X40,ATH,IT
22,DIXON,0.10,0.97,36.59,37.92,96356.0,2542.0,263340.0,18931.72,-57.11,61.0,X-MC,8.47,54.0,0.03,1.73,43.29,X40N,ATH,IT
73,SONACOMS,-0.30,23.83,12.00,38.69,15032.0,24106.0,125265.0,801.69,-1.84,72.0,M-MC,26.62,193.0,1.60,0.82,77.72,AR,ATH,AUTO
30,HAPPSTMNDS,2.79,-52.19,282.96,83.08,173375.0,-66893.0,61272.0,1466.54,-43.09,59.0,H-SC,12.21,152.0,-0.39,0.40,14.77,AR,ATH,IT

In [24]:
# Top N allocation
df_tmp = df_portfolio_features.sort_values(by = 'CurrAlloc%', ascending=False)
top_n_values = [10, 25, 50]

sum_df = pd.DataFrame({
    'Top_N': top_n_values,
    'Sum_Alloc%': [df_tmp['CurrAlloc%'].head(n).sum() for n in top_n_values]
})

sum_df

   Top_N  Sum_Alloc%
0     10       19.26
1     25       42.37
2     50       72.73

In [25]:
# market-cap-wise allocation
df_tmp = df_portfolio_features[cols]
df_tmp.groupby(df_tmp['Conviction'].str[-2:])['CurrAlloc%'].sum().sort_values(ascending=False)

Conviction
SC    43.44
LC    30.19
MC    26.35
Name: CurrAlloc%, dtype: float64

In [26]:
# criteria-wise allocation
df_portfolio_features.groupby('Criteria')['CurrAlloc%'].sum().sort_values(ascending=False)

Criteria
XY24     27.32
X40      24.92
X40N     17.41
XR        8.94
OX40N     7.00
AR        6.98
XY25      6.54
SR        0.87
Name: CurrAlloc%, dtype: float64

In [27]:
# conviction-wise allocation
df_portfolio_features.groupby('Conviction')['CurrAlloc%'].sum().sort_values(ascending=False)

Conviction
X-LC    28.17
H-SC    22.78
X-MC    21.16
X-SC    10.19
M-SC     9.94
H-MC     2.67
M-MC     2.14
H-LC     1.21
M-LC     0.81
L-SC     0.53
L-MC     0.38
Name: CurrAlloc%, dtype: float64

In [28]:
# sector-wise stats
df_tmp = df_portfolio_features.groupby('Category')[['CurrAlloc%', 'Current', 'Current P/L', 'FTT Amt']].sum().sort_values(by=['Current', 'Current P/L'], ascending=False)
df_tmp['Current P/L%'] = round(df_tmp['Current P/L'] * 100 / df_tmp['Current'], 2)
df_tmp['FTT%'] = round(df_tmp['FTT Amt'] * 100 / df_tmp['Current'], 2)
cols = ['CurrAlloc%', 'Current P/L%', 'FTT%']
df_tmp[cols].sort_values(by=['CurrAlloc%'], ascending=False)

               CurrAlloc%  Current P/L%    FTT%
Category
FMCG                14.31        -21.31   63.86
FINANCE             11.31         -6.93   53.26
IT                  10.31        -43.41  114.38
MISC                 7.31        -20.36   72.01
AUTO                 6.62         -8.40   48.82
PAINTS               5.46        -18.57   38.80
BANKS                5.44         -9.55   60.17
INSURANCE            5.21         -4.26   39.43
PHARMA               5.18          5.84   22.67
ELECTRICAL           4.16        -11.61   50.86
CHEMICALS            2.16        -23.40   96.25
HEALTHCARE           2.13         -9.99   38.69
APPARELS             1.84          4.43   27.68
AC                   1.79        -17.39   49.23
FOOTWEAR             1.70        -70.56  138.95
BREWERIES            1.69          9.32    9.51
DURABLES             1.63        -55.29   93.06
REALTY               1.59          8.55    6.48
TRAVEL               1.50        -95.77  193.80
CERAMICS             1.40        -43.80   87.49
ENGINEERING          1.23        -29.69   89.01
CABLES               1.23         20.91   64.43
JEWELLERY            1.12        -86.03  150.66
REFINERIES           1.09        -21.50   52.24
CEMENT               1.06        -65.45  189.23
ENTERTAINMENT        0.72        -77.64  183.59
TEXTILES             0.41        -48.81   91.24
HOTELS               0.38        -94.22  162.73

In [29]:
# money to be made criteria-wise
df_portfolio_features.groupby('Criteria')['FTT Amt'].agg(['sum', 'count']).sort_values(by='sum', ascending=False)

                sum  count
Criteria
XY24      3435207.0     21
X40       1866008.0     19
XR        1316334.0     13
AR        1110456.0      9
X40N      1066084.0     13
OX40N      724546.0     10
XY25       439757.0      5
SR         285436.0      2

In [30]:
# money to be made conviction-wise
df_portfolio_features.groupby('Conviction')['FTT Amt'].agg(['sum', 'count']).sort_values(by='sum', ascending=False)

                  sum  count
Conviction
H-SC        3300952.0     24
X-LC        1977579.0     21
X-MC        1487534.0     15
M-SC        1406269.0     14
X-SC        1249385.0      9
H-MC         291331.0      2
L-SC         208852.0      2
M-LC         169131.0      1
M-MC          58836.0      2
H-LC          48668.0      1
L-MC          45291.0      1

In [31]:
# money to be made criteria and conviction-wise
df_portfolio_features.groupby(['Conviction', 'Criteria'])['FTT Amt'].agg(['sum', 'count']).sort_values(by='sum', ascending=False)

                           sum  count
Conviction Criteria
X-LC       X40       1010706.0     10
H-SC       XY24      1010248.0      6
           AR         931022.0      5
M-SC       XY24       827196.0      6
H-SC       XR         774471.0      7
X-SC       XY24       740931.0      4
X-MC       X40        647105.0      7
X-LC       X40N       394975.0      6
X-MC       X40N       370852.0      4
X-LC       XY24       370302.0      2
M-SC       OX40N      311057.0      5
X-SC       X40N       300257.0      3
H-SC       OX40N      299775.0      4
           SR         285436.0      2
H-MC       XY24       251950.0      1
X-MC       XY25       234997.0      2
           XY24       234580.0      2
X-SC       X40        208197.0      2
M-SC       XR         191663.0      2
M-LC       XR         169131.0      1
X-LC       XY25       160956.0      2
L-SC       OX40N      113714.0      1
           XR          95138.0      1
M-SC       AR          76353.0      1
H-LC       AR          48668.0      1
L-MC       XR          45291.0      1
M-MC       XY25        43804.0      1
X-LC       XR          40640.0      1
H-MC       AR          39381.0      1
M-MC       AR          15032.0      1

In [32]:
# notebook execution time

end_time = time.time()
execution_time = round(end_time - start_time, 0)
print(f"Notebook execution time: {execution_time} seconds")

Notebook execution time: 36.0 seconds