<a href="https://colab.research.google.com/github/ankit-rathi/Quantvesting_v2/blob/main/myStocks_Portfolio_Analysis.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
'''
!pip install pandas==2.2.2 -qq
!pip install pyxirr -qq
!pip install ta -qq
!pip install yfinance==0.2.59 -qq
'''

'\n!pip install pandas==2.2.2 -qq\n!pip install pyxirr -qq\n!pip install ta -qq\n!pip install yfinance==0.2.59 -qq\n'

In [2]:
# import libraries

import numpy as np
import pandas as pd
import datetime
import warnings
warnings.filterwarnings('ignore')
import yfinance as yfin
import ta
import matplotlib.pyplot as plt
import requests

In [3]:
# notebook start time
import time
import datetime
import pytz

start_time = time.time()

# function to print date timestamp
def print_date_time():
  tz_NY = pytz.timezone('Asia/Kolkata')
  datetime_NY = datetime.datetime.now(tz_NY)
  print("Run date time (IST):", datetime_NY.strftime("%Y-%m-%d %H:%M:%S"))

In [4]:
# function to get booked and reserved amount
def get_amt():
  # fetch the JSON data from the URL
  url = "https://raw.githubusercontent.com/ankit-rathi/Tradevesting_v1/main/data/myPortfolioAmts.json"
  response = requests.get(url)
  pf_amts = response.json()  # parse the JSON data

  # extract values from the JSON
  py_booked_amt_dm = pf_amts["py_booked_amt_dm"]
  py_booked_amt_sv = pf_amts["py_booked_amt_sv"]
  cy_booked_amt_dm = pf_amts["cy_booked_amt_dm"]
  cy_booked_amt_sv = pf_amts["cy_booked_amt_sv"]
  reserve_amt_dm = pf_amts["reserve_amt_dm"]
  reserve_amt_sv = pf_amts["reserve_amt_sv"]

  # perform calculations
  py_booked_amt = py_booked_amt_dm + py_booked_amt_sv
  cy_booked_amt = cy_booked_amt_dm + cy_booked_amt_sv
  reserve_amt = reserve_amt_dm + reserve_amt_sv
  total_booked_amt = py_booked_amt + cy_booked_amt

  return total_booked_amt, reserve_amt, cy_booked_amt, py_booked_amt

gen_output = 0

In [5]:
# function to format the amount
def format_amt(number):
    abs_number = abs(number)

    if abs_number >= 1_00_00_000:  # Crores
        formatted_amt = f"{number / 1_00_00_000:.2f} C"
    elif abs_number >= 1_00_000:  # Lakhs
        formatted_amt = f"{number / 1_00_000:.2f} L"
    elif abs_number >= 1_000:  # Thousands
        formatted_amt = f"{number / 1_000:.2f} K"
    else:
        formatted_amt = f"{number:.2f}"

    return formatted_amt

# function to set start and end date
def get_start_end_date():
  start_date = (datetime.date.today() + datetime.timedelta(days=-365)).strftime('%Y-%m-%d')
  end_date = (datetime.date.today() + datetime.timedelta(days=1)).strftime('%Y-%m-%d')
  return start_date, end_date

# function to fetch my portfolio csv
def get_mypfs_df():
  mypfs_df = pd.read_csv('https://raw.githubusercontent.com/ankit-rathi/Tradevesting_v1/main/data/myPortfolioStocks.csv')
  return mypfs_df

# function to fetch my prospects csv
def get_mypps_df():
  mypps_df = pd.read_csv('https://raw.githubusercontent.com/ankit-rathi/Tradevesting_v1/main/data/myProspectsScrips.csv')
  return mypps_df

# function to fetch screener data
def get_myscreen_df():
  myscreen_df = pd.read_csv('https://raw.githubusercontent.com/ankit-rathi/Tradevesting_v1/main/data/myScreenerDB.csv')
  return myscreen_df

# function to fetch momentum data
def get_myinvmt_df():
  myinvmt_df = pd.read_csv('https://raw.githubusercontent.com/ankit-rathi/Tradevesting_v1/main/data/myInvestments.csv')
  return myinvmt_df

# function to get the stock ids
def get_stock_ids(df_pf):
  stock_n100 = df_pf['Symbol'].unique()

  exclude = ['CADILAHC','MMTC', 'MASFIN']

  stock_ids = df_pf[~df_pf['Symbol'].isin(exclude) ]['Symbol'].unique()

  #mypf = mypf[mypf.Forecast.notnull()]
  #stock_ids = mypf['Symbol'].unique()

  #stock_ids.sort()
  return stock_ids

# get features from screener data
def get_screener_features():
  myscreen_df = get_myscreen_df()
  cols = ['Symbol', 'EPS', 'MedPE', 'ROCE%', 'ROE%', 'CapType']
  return myscreen_df[cols]

# get relative strength
def get_relative_strength(stock_list):

    # Dictionary to store stock tickers and their corresponding percentage price change
    stock_changes = {}

    # Loop through each stock and fetch its price data
    for stock in stock_list:
        try:
            # Download the stock data for the given date range
            stock_data = yfin.Ticker(stock + '.NS').history(period='1mo', interval='1d')[map(str.title, ['open', 'close', 'low', 'high', 'volume'])]

            # Calculate the percentage change for the stock
            if len(stock_data) > 0:
                start_price = stock_data['Close'].iloc[0]
                end_price = stock_data['Close'].iloc[-1]
                percent_change = round(((end_price - start_price) / start_price) * 100, 2)
                stock_changes[stock] = percent_change
            else:
                stock_changes[stock] = np.nan  # If no data is available, set to NaN

        except Exception as e:
            print(f"Error fetching data for {stock}: {e}")
            stock_changes[stock] = np.nan

    # Create a DataFrame with stock tickers and their percentage changes
    df = pd.DataFrame(list(stock_changes.items()), columns=['Symbol', 'Percent_Change'])

    # Drop any stocks with missing data (NaN values)
    df = df.dropna()

    # Calculate the percentile rank based on percentage change
    df['RSP'] = round(df['Percent_Change'].rank(pct=True) * 100, 2)
    cols = ['Symbol', 'RSP']
    df = df[cols]
    # Sort by percentile rank (optional)
    df = df.sort_values(by='RSP', ascending=False).reset_index(drop=True)

    return df

In [6]:
# function to get stock technicals
def stock_prec_dev(stock_symbol):
    #stock_symbol = 'ULTRACEMCO.NS'
    short_window = 20
    mid_window = 50
    long_window = 200
    moving_avg = 'SMA'

    start = datetime.datetime(*map(int, start_date.split('-')))
    end = datetime.datetime(*map(int, end_date.split('-')))

    stock_df = yfin.Ticker(stock_symbol + '.NS').history(period='max', interval='1d')[map(str.title, ['open', 'close', 'low', 'high', 'volume'])]

    stock_df['Max'] = round(max(stock_df['Close']),2)
    stock_df = stock_df[(stock_df.index <= end_date) & (stock_df.index >= start_date)]
    stock_df['200_SMA'] = round(stock_df['Close'].rolling(window = 200, min_periods = 1).mean(),0)
    stock_df['Dev%_200'] = round((stock_df['Close'] - stock_df['200_SMA'])*100/stock_df['200_SMA'],2)
    stock_df.dropna(axis = 0, inplace = True) # remove any null rows

    stock_df['20_SMA'] = stock_df['Close'].rolling(window=20).mean()
    stock_df['50_SMA'] = stock_df['Close'].rolling(window=50).mean()
    stock_df['Symbol'] = stock_symbol

    stock_df['Close'] = round(stock_df['Close'],2)
    stock_df['Min'] = round(min(stock_df['Close']),2)
    stock_df['RSI_14'] = ta.momentum.RSIIndicator(close=stock_df['Close'], window=14).rsi()
    stock_df['RSI_14'] = round(stock_df['RSI_14'],0)
    stock_df['Prev_Close'] = stock_df['Close'].shift(1)
    stock_df.drop(['Open', 'Low', 'High', 'Volume'], axis=1, inplace=True)
    stock_df = stock_df.tail(1)

    max_SMA = max(stock_df['20_SMA'].item(), stock_df['50_SMA'].item(), stock_df['200_SMA'].item())
    min_SMA = min(stock_df['20_SMA'].item(), stock_df['50_SMA'].item(), stock_df['200_SMA'].item())
    ABS_Spread = max_SMA - min_SMA
    stock_df['Spread%'] = round((ABS_Spread / stock_df['200_SMA'].item()) * 100,2)

    return stock_df

# function to compute stock attributes
def get_common_features(stock_ids, df_mypf):

  df_prec_dev = pd.DataFrame()
  df_tmp = get_screener_features()
  df_rs = get_relative_strength(stock_ids)

  for stock_id in stock_ids:
      tmp = stock_prec_dev(stock_id)
      tmp = tmp.reset_index()
      df_prec_dev = pd.concat([df_prec_dev, tmp], ignore_index = True)
  df_prec_dev = pd.merge(df_prec_dev, df_mypf, on= 'Symbol')
  df_prec_dev = pd.merge(df_prec_dev, df_tmp, on= 'Symbol', how='left')
  df_prec_dev = pd.merge(df_prec_dev, df_rs, on= 'Symbol', how='left')
  #print(df_prec_dev.columns)
  df_prec_dev['Curr_PE'] = round(df_prec_dev['Close']/df_prec_dev['EPS'],1)
  df_prec_dev['Dev%_PE'] = round((df_prec_dev['Curr_PE'] - df_prec_dev['MedPE'])*100/df_prec_dev['MedPE'],2)
  df_prec_dev['Conviction'] = df_prec_dev['Conviction'] + '-' + df_prec_dev['CapType']
  return df_prec_dev

# function to arrange stock features
def arrange_features(df_stocks, common_cols, diff_cols):
  df_stocks_common = df_stocks[common_cols].drop_duplicates()
  df_stocks_diff = df_stocks[diff_cols]
  df_stocks_diff['Investment'] = df_stocks_diff['AvgCost'] * df_stocks_diff['Shares']
  df_stocks_diff = df_stocks_diff.groupby(['Symbol'])[['Shares', 'Investment']].aggregate(['sum']).reset_index()
  df_stocks_diff.columns = ['Symbol', 'Shares', 'Investment']
  df_stocks_diff['AvgCost'] = round(df_stocks_diff['Investment']/df_stocks_diff['Shares'],2)
  df_stocks = pd.merge(df_stocks_diff, df_stocks_common, on='Symbol')
  return df_stocks

# plot fact distribution across dimension
def plot_pie_chart(df, dimension, fact):
  # grouping the data by category and calculating the sum of fact for each type
  grouped_data = df.groupby(dimension)[fact].sum()

  # sorting the grouped data in descending order
  grouped_data = grouped_data.sort_values(ascending=False)

  # creating a pie chart
  grouped_data.plot.pie(autopct='%1.1f%%', startangle=90, figsize=(6, 6))

  # adding a title and displaying the plot
  plt.title(f'{dimension} {fact} Distribution')
  plt.ylabel('')  # To hide the y-label
  plt.show()

In [7]:
# function to get portfolio features

def get_portfolio_features(df_common_features):

  print_date_time()
  print('-------------------')

  #df_common_features["Target"] = df_common_features["Target"].fillna(df_common_features["Max"])
  df_common_features['NTT'] = np.where(df_common_features['Strategy']== 'NTT', df_common_features["Target"], df_common_features['Max'])
  df_common_features['LTT'] = np.where(df_common_features['Strategy']== 'BTT', df_common_features["Target"], df_common_features['Max'])
  df_common_features['BOL'] = df_common_features['Min']

  tmp_df = df_common_features[df_common_features['Symbol'].isin(mypf_df[mypf_df['InPortfolio'] != 'NA'].Symbol.values)]
  print('qualified stocks: '+str(len(tmp_df['Symbol'].unique())))
  tmp_df1 = tmp_df[tmp_df['LatestQtr'] == 1]
  print('with latest results: '+str(len(tmp_df1['Symbol'].unique())))
  tmp_df1 = tmp_df1[tmp_df1['StarStock'] == 1]
  print('still star stocks: '+str(len(tmp_df1['Symbol'].unique())))
  tmp_df['Investment'] = tmp_df['AvgCost'] * tmp_df['Shares']
  tmp_df['Current'] = round(tmp_df['Close'] * tmp_df['Shares'],0)
  tmp_df['Previous'] = tmp_df['Prev_Close'] * tmp_df['Shares']
  tmp_df['EstimatedST'] = tmp_df['NTT'] * tmp_df['Shares']
  tmp_df['EstimatedLT'] = tmp_df['LTT'] * tmp_df['Shares']
  tmp_df['Current P/L'] = round((tmp_df['Current'] - tmp_df['Investment']),0)
  tmp_df['Today P/L%'] = round((tmp_df['Current'] - tmp_df['Previous'])*100/tmp_df['Previous'],2)
  tmp_df['Current P/L%'] = round((tmp_df['Current'] - tmp_df['Investment'])*100/tmp_df['Investment'],2)
  tmp_df['EstimatedST P/L%'] = round((tmp_df['EstimatedST'] - tmp_df['Investment'])*100/tmp_df['Investment'],2)
  tmp_df['EstimatedLT P/L%'] = round((tmp_df['EstimatedLT'] - tmp_df['Investment'])*100/tmp_df['Investment'],2)
  tmp_df['NTT%'] = round((tmp_df['NTT'] - tmp_df['Close'])*100/tmp_df['Close'],2)
  tmp_df['LTT%'] = round((tmp_df['LTT'] - tmp_df['Close'])*100/tmp_df['Close'],2)
  tmp_df['Gained%'] = round((tmp_df['Close'] - tmp_df['BOL'])*100/tmp_df['BOL'],2)
  investment = round(sum(tmp_df['AvgCost']*tmp_df['Shares']),0)
  current = round(sum(tmp_df['Close']*tmp_df['Shares']),0)
  tmp_df['InitAlloc%'] = round(tmp_df['Investment']*100/investment,2)
  tmp_df['CurrAlloc%'] = round(tmp_df['Current']*100/current,2)
  tmp_df['FTT'] = tmp_df['LTT']
  tmp_df.loc[tmp_df['Strategy'] == 'NTT', 'FTT'] = tmp_df['NTT']
  tmp_df['FTT%'] = tmp_df['LTT%']
  tmp_df.loc[tmp_df['Strategy'] == 'NTT', 'FTT%'] = tmp_df['NTT%']
  tmp_df['FTT Amt'] = round(tmp_df['FTT%'] * tmp_df['Current']/100,0)
  tmp_df['OTT%'] = round((tmp_df['FTT'] - tmp_df['AvgCost'])*100/tmp_df['AvgCost'],2)
  tmp_df['RRR Ind'] = round(tmp_df['Current P/L']/tmp_df['FTT Amt'],2)
  tmp_df['Risk Ind'] = round(tmp_df['Current P/L%']*tmp_df['CurrAlloc%'],0)

  return tmp_df

# function to print portfolio features
def print_portfolio_stats(df_portfolio_features, myinvmt_df):
  from pyxirr import xirr

  total_booked_amt, reserve_amt, cy_booked_amt, py_booked_amt = get_amt()

  dates = myinvmt_df['Date'].values
  dates = np.append(dates, datetime.date.today().strftime('%d-%b-%y'))
  investment = myinvmt_df['Investment'].values
  dates= pd.to_datetime(dates)

  current = round(sum(df_portfolio_features['Close']*df_portfolio_features['Shares']),0) + reserve_amt
  investment_xirr = np.append(investment, current)
  cagr = round(xirr(pd.DataFrame({"dates": dates, "amounts": investment_xirr}))*100,2)

  investment = -sum(investment)
  invested = round(sum(df_portfolio_features['AvgCost']*df_portfolio_features['Shares']),0) + reserve_amt
  previous = round(sum(df_portfolio_features['Prev_Close']*df_portfolio_features['Shares']),0) + reserve_amt
  cy_invested = investment + py_booked_amt

  today_pnl_amount = current-previous
  today_pnl_percentage = round((current-previous)*100/previous,2)

  curr_pnl_amount = current-invested
  curr_pnl_percentage = round((curr_pnl_amount)*100/(cy_invested),2)

  cy_pnl_amount = cy_booked_amt + curr_pnl_amount
  cy_pnl_percentage = round((cy_pnl_amount)*100/cy_invested,2)

  overall_pnl_amount = total_booked_amt + curr_pnl_amount
  overall_pnl_percentage = round((overall_pnl_amount)*100/investment,2)

  estimate_st = round(sum(df_portfolio_features['FTT']*df_portfolio_features['Shares']),0)  + reserve_amt
  est_st_pnl_amount = estimate_st-current
  est_st_pnl_percentage = round((est_st_pnl_amount)*100/current,2)

  estimate_lt = round(sum(df_portfolio_features['LTT']*df_portfolio_features['Shares']),0)  + reserve_amt
  est_lt_pnl_amount = estimate_lt-current
  est_lt_pnl_percentage = round((est_lt_pnl_amount)*100/current,2)

  total_profit = round(sum(df_portfolio_features[df_portfolio_features['Current P/L%'] > 0]['Current']) - sum(df_portfolio_features[df_portfolio_features['Current P/L%'] > 0]['Investment']),0)
  total_loss = round(sum(df_portfolio_features[df_portfolio_features['Current P/L%'] < 0]['Current']) - sum(df_portfolio_features[df_portfolio_features['Current P/L%'] < 0]['Investment']),0)

  cy_booked_percentage = round((cy_booked_amt)*100/current,2)
  py_booked_percentage = round((py_booked_amt)*100/investment,2)
  total_booked_percentage = round((total_booked_amt)*100/investment,2)

  print('-------------------')
  print('Initial Investment: ', format_amt(investment))
  print('CY Investment: ', format_amt(cy_invested))
  print('Reserve: ', format_amt(reserve_amt))
  print('Current: ',  format_amt(current))
  print('-------------------')
  print('Today PnL: '+ '{} ({}%)'.format(format_amt(today_pnl_amount), today_pnl_percentage))
  print('Current PnL: '+ '{} ({}%)'.format(format_amt(curr_pnl_amount), curr_pnl_percentage))
  print('CY Booked + Current PnL: '+ '{} ({}%)'.format(format_amt(cy_pnl_amount), cy_pnl_percentage))
  print('-------------------')
  print('Total profit: ', format_amt(total_profit))
  print('Total loss: ', format_amt(total_loss))
  print('-------------------')
  print('Total Booked + Current PnL: '+ '{} ({}%)'.format(format_amt(overall_pnl_amount), overall_pnl_percentage))
  print('Total Booked PnL: '+ '{} ({}%)'.format(format_amt(total_booked_amt), total_booked_percentage))
  print('Curr Year Booked PnL: '+ '{} ({}%)'.format(format_amt(cy_booked_amt), cy_booked_percentage))
  print('Prev Year Booked PnL: '+ '{} ({}%)'.format(format_amt(py_booked_amt), py_booked_percentage))
  print('===================')
  print('Est FTT: ',  format_amt(estimate_st))
  print('Est FTT PnL: '+ '{} ({}%)'.format(format_amt(est_st_pnl_amount), est_st_pnl_percentage))

  print('===================')
  print('Deployed: ', format_amt(investment))

  print('Current: ', format_amt(current))

  print('CAGR/XIRR %: '+'{}%'.format(cagr))

In [8]:
# get start and end date
start_date, end_date = get_start_end_date()

# get portfolio and prospects data
mypfs_df = get_mypfs_df()
mypps_df = get_mypps_df()
myinvmt_df = get_myinvmt_df()

# merge above datasets
mypf_df = pd.merge(mypfs_df, mypps_df, on="Symbol")

# seggregate dm and sv portfolio
dm_pf = mypf_df[mypf_df['InPortfolio'] == 'DM']
sv_pf = mypf_df[mypf_df['InPortfolio'] == 'SV']

# build portfolio stock dataframe
dm_stocks = get_stock_ids(dm_pf)
sv_stocks = get_stock_ids(sv_pf)
df_stocks = pd.concat([dm_pf,sv_pf], ignore_index = True)

# arrange common and diff stock features
common_cols = ['Symbol', 'Target', 'Criteria', 'Strategy', 'CumlRnk', 'LatestQtr', 'StarStock', 'Conviction', 'Category', 'InFolio', 'XIRR', 'MBQ']
diff_cols = ['Symbol', 'AvgCost', 'Shares']
df_stocks = arrange_features(df_stocks, common_cols, diff_cols)

# get common features
stock_ids = df_stocks['Symbol'].values
df_common_features = get_common_features(stock_ids, df_stocks)

df_common_features.reset_index(drop=True, inplace=True)
df_common_features.drop(['Date'], axis=1, inplace=True)
# get and print portfolio features
df_portfolio_features = get_portfolio_features(df_common_features)

print_portfolio_stats(df_portfolio_features, myinvmt_df)

df = df_portfolio_features
#plot_pie_chart(df, 'CapType', 'Current')
list_ox40n = list(df[df['MBQ'].str.contains('OX40N', na=False)]['Symbol'].values)

Run date time (IST): 2026-06-17 17:28:18
-------------------
qualified stocks: 92
with latest results: 31
still star stocks: 20
-------------------
Initial Investment:  1.40 C
CY Investment:  1.82 C
Reserve:  1.49 K
Current:  1.52 C
-------------------
Today PnL: 51.07 K (0.34%)
Current PnL: -31.43 L (-17.24%)
CY Booked + Current PnL: -29.36 L (-16.1%)
-------------------
Total profit:  3.38 L
Total loss:  -34.81 L
-------------------
Total Booked + Current PnL: 13.52 L (9.69%)
Total Booked PnL: 44.95 L (32.22%)
Curr Year Booked PnL: 2.08 L (1.37%)
Prev Year Booked PnL: 42.87 L (30.73%)
===================
Est FTT:  2.55 C
Est FTT PnL: 1.03 C (68.16%)
===================
Deployed:  1.40 C
Current:  1.52 C
CAGR/XIRR %: 3.94%

In [9]:
# top 5 near their targets
cols = ['Symbol', 'Today P/L%', 'Current P/L%', 'FTT%', 'OTT%', 'FTT Amt', 'Current P/L', 'Current', 'FTT', 'Dev%_PE', 'RSI_14','Conviction', 'Spread%',  'CumlRnk', 'RRR Ind', 'CurrAlloc%', 'Gained%', 'Criteria', 'Strategy', 'Category']
df_tmp = df_portfolio_features[~df_portfolio_features['Symbol'].isin(['ENRIN','BLUSPRING','DIGITIDE'])]
df_tmp = df_tmp.sort_values(by = 'FTT Amt', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
59,PIDILITIND,0.45,11.84,5.83,18.37,9201.0,16710.0,157820.0,1670.26,-21.72,74.0,X-LC,3.72,5.0,1.82,1.04,23.92,X40,ATH,CHEMICALS
51,KOTAKBANK,-0.82,8.08,12.05,21.11,18035.0,11192.0,149665.0,453.24,-7.24,66.0,X-LC,5.74,12.0,0.62,0.99,14.46,X40,ATH,BANKS
55,MASFIN,-0.13,-4.38,27.13,21.57,25418.0,-4290.0,93690.0,397.04,-17.34,52.0,H-SC,3.55,167.0,-0.17,0.62,11.68,XR,ATH,FINANCE
72,SIS,0.71,-2.07,23.83,21.26,25911.0,-2300.0,108732.0,528.00,2594.30,63.0,H-SC,22.26,168.0,-0.09,0.72,61.67,OX40N,NTT,MISC
83,TTKPRESTIG,0.64,-29.21,41.39,0.09,29529.0,-29434.0,71343.0,770.00,65.64,56.0,M-SC,10.66,250.0,-1.00,0.47,27.04,OX40N,NTT,DURABLES

In [10]:
# top 5 today
df_tmp = df_portfolio_features.sort_values(by = 'Today P/L%', ascending=False)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
86,VALIANTORG,8.35,-35.39,169.54,74.15,179214.0,-57899.0,105706.0,838.00,-290.27,61.0,H-SC,2.79,145.0,-0.32,0.70,57.31,XR,NTT,CHEMICALS
25,FINCABLES,6.11,41.85,46.57,107.91,97536.0,61796.0,209440.0,1641.55,27.85,60.0,M-SC,23.67,220.0,0.63,1.38,57.57,OX40N,ATH,CABLES
61,RAJESHEXPO,5.00,-82.91,485.64,0.07,113829.0,-113738.0,23439.0,518.00,758.59,38.0,L-SC,34.93,268.0,-1.00,0.15,15.76,OX40N,NTT,JEWELLERY
22,DIXON,4.89,-6.51,47.52,37.92,115867.0,-16971.0,243827.0,18931.72,-60.27,71.0,X-MC,13.36,54.0,-0.15,1.61,32.67,X40N,ATH,IT
64,RELAXO,3.82,-52.83,222.86,52.31,152612.0,-76681.0,68479.0,1176.00,-49.76,69.0,X-SC,17.66,92.0,-0.50,0.45,53.11,X40N,NTT,FOOTWEAR

In [11]:
# bottom 5 today
df_tmp = df_portfolio_features.sort_values(by = 'Today P/L%', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
81,TMPV,-8.30,-17.84,66.23,36.58,193637.0,-63471.0,292370.0,600.00,-82.53,42.0,X-LC,12.41,4.0,-0.33,1.93,21.86,XY24,NTT,AUTO
12,BOSCH-HCIL,-5.10,-43.95,78.41,-0.01,56165.0,-56175.0,71630.0,2282.00,14552.17,36.0,M-SC,8.38,231.0,-1.00,0.47,21.92,OX40N,BTT,AC
19,COLPAL,-2.99,-22.76,81.07,39.86,164913.0,-59945.0,203420.0,3683.41,-6.52,47.0,X-MC,3.19,62.0,-0.36,1.34,15.07,XY25,ATH,FMCG
50,KANSAINER,-2.12,-29.54,61.05,13.47,115994.0,-79668.0,189999.0,340.00,-39.37,46.0,H-SC,6.20,162.0,-0.69,1.25,32.72,XY24,NTT,PAINTS
6,AWL,-1.87,-33.33,150.53,67.02,357561.0,-118774.0,237535.0,485.00,-64.08,52.0,X-SC,14.55,81.0,-0.33,1.57,12.36,XY24,NTT,FMCG

In [12]:
# top 5 to exit based on CumlRnk
df_tmp = df_portfolio_features[~df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])]
df_tmp = df_tmp[(df_tmp['Current P/L%'] > -1) & (df_tmp['Current P/L%'] < 1)].sort_values(by = 'CumlRnk', ascending=False)
df_tmp[cols].head()

Empty DataFrame
Columns: [Symbol, Today P/L%, Current P/L%, FTT%, OTT%, FTT Amt, Current P/L, Current, FTT, Dev%_PE, RSI_14, Conviction, Spread%, CumlRnk, RRR Ind, CurrAlloc%, Gained%, Criteria, Strategy, Category]
Index: []

In [13]:
# OX40N stocks to exit
df_tmp = df_portfolio_features[(df_portfolio_features['Symbol'].isin(list_ox40n))].sort_values(by = 'Current P/L%', ascending=False)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
25,FINCABLES,6.11,41.85,46.57,107.91,97536.0,61796.0,209440.0,1641.55,27.85,60.0,M-SC,23.67,220.0,0.63,1.38,57.57,OX40N,ATH,CABLES
72,SIS,0.71,-2.07,23.83,21.26,25911.0,-2300.0,108732.0,528.00,2594.30,63.0,H-SC,22.26,168.0,-0.09,0.72,61.67,OX40N,NTT,MISC
16,CERA,-0.84,-19.51,53.91,23.89,76330.0,-34315.0,141588.0,9475.00,-22.43,66.0,H-SC,5.08,153.0,-0.45,0.93,36.07,OX40N,NTT,CERAMICS
43,INDIGOPNTS,-0.71,-27.44,37.84,0.02,47928.0,-47899.0,126660.0,1408.00,93.08,62.0,M-SC,10.29,222.0,-1.00,0.83,43.70,OX40N,NTT,PAINTS
83,TTKPRESTIG,0.64,-29.21,41.39,0.09,29529.0,-29434.0,71343.0,770.00,65.64,56.0,M-SC,10.66,250.0,-1.00,0.47,27.04,OX40N,NTT,DURABLES

In [14]:
# top 5 to book for rotation
df_tmp = df_portfolio_features[(df_portfolio_features['Current P/L%'] > 20) ].sort_values(by = 'CumlRnk', ascending=False)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
25,FINCABLES,6.11,41.85,46.57,107.91,97536.0,61796.0,209440.0,1641.55,27.85,60.0,M-SC,23.67,220.0,0.63,1.38,57.57,OX40N,ATH,CABLES
68,SATIN,1.82,30.55,16.30,51.83,58792.0,84404.0,360688.0,274.00,16.95,60.0,H-SC,40.67,159.0,1.44,2.38,75.71,XY24,NTT,FINANCE

In [15]:
# top 5 to monitor for exit
df_tmp = df_portfolio_features[~df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])]
df_tmp = df_tmp[(df_tmp['Current P/L%'] > 0) ].sort_values(by = 'Dev%_PE', ascending=False)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
9,BANDHANBNK,-1.38,2.83,87.13,92.42,249573.0,7879.0,286438.0,400.00,145.69,62.0,H-SC,22.30,174.0,0.03,1.89,57.79,XY24,NTT,BANKS
74,STARHEALTH,2.29,3.28,42.59,47.26,123653.0,9210.0,290333.0,761.00,62.96,60.0,H-SC,10.21,173.0,0.07,1.91,27.47,XY24,NTT,INSURANCE
25,FINCABLES,6.11,41.85,46.57,107.91,97536.0,61796.0,209440.0,1641.55,27.85,60.0,M-SC,23.67,220.0,0.63,1.38,57.57,OX40N,ATH,CABLES
68,SATIN,1.82,30.55,16.30,51.83,58792.0,84404.0,360688.0,274.00,16.95,60.0,H-SC,40.67,159.0,1.44,2.38,75.71,XY24,NTT,FINANCE
91,ZYDUSLIFE,-1.60,11.93,21.18,35.63,49682.0,24995.0,234569.0,1286.17,-2.70,53.0,H-MC,13.35,120.0,0.50,1.55,23.33,AR,ATH,PHARMA

In [16]:
# top 5 to book for rotation from weak conviction
df_tmp = df_portfolio_features[~df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])]
df_tmp = df_tmp[~df_tmp['Criteria'].isin(['XY25','XY24','X40', 'X40N'])].sort_values(by = 'RRR Ind', ascending=False)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
25,FINCABLES,6.11,41.85,46.57,107.91,97536.0,61796.0,209440.0,1641.55,27.85,60.0,M-SC,23.67,220.0,0.63,1.38,57.57,OX40N,ATH,CABLES
91,ZYDUSLIFE,-1.60,11.93,21.18,35.63,49682.0,24995.0,234569.0,1286.17,-2.70,53.0,H-MC,13.35,120.0,0.50,1.55,23.33,AR,ATH,PHARMA
73,SONACOMS,0.43,4.01,33.72,39.09,35480.0,4060.0,105219.0,804.02,-17.63,54.0,M-MC,18.55,193.0,0.11,0.69,48.85,AR,ATH,AUTO
42,INDIAMART,0.28,-10.19,130.17,106.72,144189.0,-12566.0,110770.0,4810.62,-59.57,63.0,H-SC,9.65,140.0,-0.09,0.73,7.23,AR,ATH,MISC
72,SIS,0.71,-2.07,23.83,21.26,25911.0,-2300.0,108732.0,528.00,2594.30,63.0,H-SC,22.26,168.0,-0.09,0.72,61.67,OX40N,NTT,MISC

In [17]:
# top 5 to accumulate based on lowest RSI_14
df_tmp = df_portfolio_features[df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])].sort_values(by = 'RSI_14', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
58,PGHH,-0.90,-32.59,95.84,32.01,137941.0,-69592.0,143928.0,17616.87,-54.37,33.0,X-MC,19.54,57.0,-0.50,0.95,0.04,X40,ATH,FMCG
1,ABBOTINDIA,-0.56,-12.93,35.60,18.07,55440.0,-23125.0,155730.0,35195.00,-25.88,42.0,X-MC,5.91,58.0,-0.42,1.03,3.08,X40,ATH,PHARMA
81,TMPV,-8.30,-17.84,66.23,36.58,193637.0,-63471.0,292370.0,600.00,-82.53,42.0,X-LC,12.41,4.0,-0.33,1.93,21.86,XY24,NTT,AUTO
17,CIPLA,-1.63,9.36,22.01,33.43,36867.0,14338.0,167499.0,1648.14,-15.37,45.0,X-LC,5.69,18.0,0.39,1.10,14.35,X40N,ATH,PHARMA
20,DABUR,-1.48,-16.13,71.33,43.70,148413.0,-40003.0,208065.0,735.00,-23.90,45.0,X-MC,11.10,70.0,-0.27,1.37,4.52,XY24,BTT,FMCG

In [18]:
# top 5 to accumulate based on Spread and CumlRnk
df_tmp = df_portfolio_features[df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])]
df_tmp = df_tmp[(df_tmp['CumlRnk'] < 100)].sort_values(by = 'Spread%', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
49,JSWINFRA,1.87,1.89,14.27,16.43,32246.0,4198.0,225972.0,342.00,-12.68,66.0,X-MC,1.46,61.0,0.13,1.49,27.74,X40N,NTT,REALTY
57,PAGEIND,0.60,2.50,30.32,33.59,83410.0,6721.0,275100.0,51217.29,-26.52,61.0,X-MC,3.02,55.0,0.08,1.81,30.64,X40,ATH,APPARELS
19,COLPAL,-2.99,-22.76,81.07,39.86,164913.0,-59945.0,203420.0,3683.41,-6.52,47.0,X-MC,3.19,62.0,-0.36,1.34,15.07,XY25,ATH,FMCG
11,BERGEPAINT,0.24,-5.70,32.89,25.32,79942.0,-14691.0,243058.0,680.00,-10.84,54.0,X-MC,3.20,68.0,-0.18,1.60,26.50,XY24,NTT,PAINTS
15,CAMS,1.90,5.77,17.68,24.48,47098.0,14536.0,266392.0,950.00,1.42,62.0,X-SC,3.35,89.0,0.31,1.76,29.69,X40N,NTT,MISC

In [19]:
# top 5 to accumulate based on lowest Gained%
df_tmp = df_portfolio_features[df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])].sort_values(by = 'Gained%', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
58,PGHH,-0.90,-32.59,95.84,32.01,137941.0,-69592.0,143928.0,17616.87,-54.37,33.0,X-MC,19.54,57.0,-0.50,0.95,0.04,X40,ATH,FMCG
1,ABBOTINDIA,-0.56,-12.93,35.60,18.07,55440.0,-23125.0,155730.0,35195.00,-25.88,42.0,X-MC,5.91,58.0,-0.42,1.03,3.08,X40,ATH,PHARMA
79,TCS,1.09,-34.74,91.36,24.88,276207.0,-160945.0,302328.0,4253.91,-44.61,47.0,X-LC,18.92,2.0,-0.58,1.99,4.09,X40,ATH,IT
28,GODREJCP,-1.40,-8.72,44.02,31.47,59718.0,-12954.0,135660.0,1469.04,-3.99,48.0,X-LC,9.53,32.0,-0.22,0.89,4.09,X40N,ATH,FMCG
20,DABUR,-1.48,-16.13,71.33,43.70,148413.0,-40003.0,208065.0,735.00,-23.90,45.0,X-MC,11.10,70.0,-0.27,1.37,4.52,XY24,BTT,FMCG

In [20]:
# top 5 to accumulate based on lowest CurrAlloc%
df_tmp = df_portfolio_features[df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])].sort_values(by = 'CurrAlloc%', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
10,BATAINDIA,-0.05,-56.23,208.92,35.20,117655.0,-72354.0,56316.0,2096.00,-26.21,48.0,X-SC,25.14,91.0,-0.61,0.37,11.69,X40,NTT,FOOTWEAR
64,RELAXO,3.82,-52.83,222.86,52.31,152612.0,-76681.0,68479.0,1176.00,-49.76,69.0,X-SC,17.66,92.0,-0.50,0.45,53.11,X40N,NTT,FOOTWEAR
60,QUESS,-0.21,2.24,70.09,73.90,76528.0,2392.0,109185.0,424.00,-44.90,78.0,X-SC,6.48,80.0,0.03,0.72,48.84,XY24,NTT,MISC
28,GODREJCP,-1.40,-8.72,44.02,31.47,59718.0,-12954.0,135660.0,1469.04,-3.99,48.0,X-LC,9.53,32.0,-0.22,0.89,4.09,X40N,ATH,FMCG
53,M&M,-0.16,1.66,21.37,23.38,30127.0,2299.0,140980.0,3802.40,-13.74,55.0,X-LC,10.50,25.0,0.08,0.93,6.88,X40N,ATH,AUTO

In [21]:
# top 5 to accumulate based on CumlRnk
df_tmp = df_portfolio_features.sort_values(by = 'CumlRnk', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
47,ITC,-0.31,-23.42,55.46,19.06,144480.0,-79654.0,260512.0,452.00,-57.95,53.0,X-LC,15.15,1.0,-0.55,1.72,4.96,X40,NTT,FMCG
79,TCS,1.09,-34.74,91.36,24.88,276207.0,-160945.0,302328.0,4253.91,-44.61,47.0,X-LC,18.92,2.0,-0.58,1.99,4.09,X40,ATH,IT
45,INFY,1.23,-21.19,70.34,34.24,173451.0,-66298.0,246590.0,1972.00,-37.95,50.0,X-LC,16.56,3.0,-0.38,1.63,8.01,X40,NTT,IT
81,TMPV,-8.30,-17.84,66.23,36.58,193637.0,-63471.0,292370.0,600.00,-82.53,42.0,X-LC,12.41,4.0,-0.33,1.93,21.86,XY24,NTT,AUTO
59,PIDILITIND,0.45,11.84,5.83,18.37,9201.0,16710.0,157820.0,1670.26,-21.72,74.0,X-LC,3.72,5.0,1.82,1.04,23.92,X40,ATH,CHEMICALS

In [22]:
# top 5 for average up
df_tmp = df_portfolio_features[(df_portfolio_features['Dev%_200'] > 5)].sort_values(by = 'CurrAlloc%', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
44,INDUSINDBK,1.10,-30.88,92.27,32.89,49238.0,-23844.0,53363.0,1800.00,-351.40,58.0,L-MC,7.49,258.0,-0.48,0.35,31.35,XR,NTT,BANKS
3,ALKYLAMINE,1.57,-22.64,150.30,93.63,117392.0,-22858.0,78105.0,4546.37,-17.07,58.0,H-SC,7.38,142.0,-0.19,0.51,47.48,SR,ATH,CHEMICALS
73,SONACOMS,0.43,4.01,33.72,39.09,35480.0,4060.0,105219.0,804.02,-17.63,54.0,M-MC,18.55,193.0,0.11,0.69,48.85,AR,ATH,AUTO
86,VALIANTORG,8.35,-35.39,169.54,74.15,179214.0,-57899.0,105706.0,838.00,-290.27,61.0,H-SC,2.79,145.0,-0.32,0.70,57.31,XR,NTT,CHEMICALS
72,SIS,0.71,-2.07,23.83,21.26,25911.0,-2300.0,108732.0,528.00,2594.30,63.0,H-SC,22.26,168.0,-0.09,0.72,61.67,OX40N,NTT,MISC

In [23]:
# top 5 RSP
df_tmp = df_portfolio_features.sort_values(by = 'RSP', ascending=False)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
18,COFFEEDAY,2.40,-42.24,134.19,35.27,88011.0,-47962.0,65587.0,80.00,-55.73,57.0,L-SC,14.85,266.0,-0.54,0.43,61.74,XR,NTT,HOTELS
37,HONAUT,-0.66,-5.67,60.41,51.31,109886.0,-10938.0,181900.0,58357.33,-21.53,64.0,X-SC,9.26,90.0,-0.10,1.20,38.20,X40N,ATH,ELECTRICAL
64,RELAXO,3.82,-52.83,222.86,52.31,152612.0,-76681.0,68479.0,1176.00,-49.76,69.0,X-SC,17.66,92.0,-0.50,0.45,53.11,X40N,NTT,FOOTWEAR
60,QUESS,-0.21,2.24,70.09,73.90,76528.0,2392.0,109185.0,424.00,-44.90,78.0,X-SC,6.48,80.0,0.03,0.72,48.84,XY24,NTT,MISC
80,TITAGARH,2.90,-13.35,68.19,45.74,143097.0,-32326.0,209851.0,1548.00,15.46,69.0,H-SC,5.47,175.0,-0.23,1.38,60.11,XY24,NTT,ENGINEERING

In [24]:
# Top N allocation
df_tmp = df_portfolio_features.sort_values(by = 'CurrAlloc%', ascending=False)
top_n_values = [10, 25, 50]

sum_df = pd.DataFrame({
    'Top_N': top_n_values,
    'Sum_Alloc%': [df_tmp['CurrAlloc%'].head(n).sum() for n in top_n_values]
})

sum_df

   Top_N  Sum_Alloc%
0     10       19.52
1     25       42.83
2     50       72.83

In [25]:
# market-cap-wise allocation
df_tmp = df_portfolio_features[cols]
df_tmp.groupby(df_tmp['Conviction'].str[-2:])['CurrAlloc%'].sum().sort_values(ascending=False)

Conviction
SC    43.33
LC    31.14
MC    25.56
Name: CurrAlloc%, dtype: float64

In [26]:
# criteria-wise allocation
df_portfolio_features.groupby('Criteria')['CurrAlloc%'].sum().sort_values(ascending=False)

Criteria
XY24     27.68
X40      24.86
X40N     17.35
XR        8.98
OX40N     6.94
AR        6.79
XY25      6.56
SR        0.87
Name: CurrAlloc%, dtype: float64

In [27]:
# conviction-wise allocation
df_portfolio_features.groupby('Conviction')['CurrAlloc%'].sum().sort_values(ascending=False)

Conviction
X-LC    29.07
H-SC    22.80
X-MC    20.55
M-SC    10.01
X-SC     9.94
H-MC     2.67
M-MC     1.99
H-LC     1.23
M-LC     0.84
L-SC     0.58
L-MC     0.35
Name: CurrAlloc%, dtype: float64

In [28]:
# sector-wise stats
df_tmp = df_portfolio_features.groupby('Category')[['CurrAlloc%', 'Current', 'Current P/L', 'FTT Amt']].sum().sort_values(by=['Current', 'Current P/L'], ascending=False)
df_tmp['Current P/L%'] = round(df_tmp['Current P/L'] * 100 / df_tmp['Current'], 2)
df_tmp['FTT%'] = round(df_tmp['FTT Amt'] * 100 / df_tmp['Current'], 2)
cols = ['CurrAlloc%', 'Current P/L%', 'FTT%']
df_tmp[cols].sort_values(by=['CurrAlloc%'], ascending=False)

               CurrAlloc%  Current P/L%    FTT%
Category
FMCG                14.83        -17.68   58.95
FINANCE             10.92        -11.43   59.88
IT                  10.14        -46.51  119.76
MISC                 7.23        -22.41   75.59
AUTO                 6.66         -8.43   49.09
BANKS                5.84         -2.67   50.14
PAINTS               5.52        -17.45   37.85
INSURANCE            5.18         -5.23   40.82
PHARMA               4.84         -0.97   32.22
ELECTRICAL           4.09        -14.11   54.39
CHEMICALS            2.25        -18.75   89.51
HEALTHCARE           2.03        -16.00   46.26
APPARELS             1.81          2.44   30.32
AC                   1.81        -16.38   47.94
FOOTWEAR             1.69        -71.89  140.81
TRAVEL               1.65        -78.64  168.10
DURABLES             1.55        -64.98  105.12
REALTY               1.49          1.86   14.27
BREWERIES            1.48         -4.08   25.69
CERAMICS             1.40        -44.35   88.21
ENGINEERING          1.38        -15.40   68.19
CABLES               1.38         29.51   46.57
REFINERIES           1.13        -16.89   46.47
JEWELLERY            1.07        -95.92  163.99
CEMENT               1.07        -65.51  189.33
ENTERTAINMENT        0.75        -70.00  171.39
HOTELS               0.43        -73.13  134.19
TEXTILES             0.41        -49.82   92.54

In [29]:
# money to be made criteria-wise
df_portfolio_features.groupby('Criteria')['FTT Amt'].agg(['sum', 'count']).sort_values(by='sum', ascending=False)

                sum  count
Criteria
XY24      3399732.0     21
X40       1913136.0     19
XR        1318934.0     13
AR        1156129.0      9
X40N      1090770.0     13
OX40N      736409.0     10
XY25       440694.0      5
SR         286720.0      2

In [30]:
# money to be made conviction-wise
df_portfolio_features.groupby('Conviction')['FTT Amt'].agg(['sum', 'count']).sort_values(by='sum', ascending=False)

                  sum  count
Conviction
H-SC        3326099.0     24
X-LC        1880786.0     21
X-MC        1599746.0     15
M-SC        1399768.0     14
X-SC        1296704.0      9
H-MC         293869.0      2
L-SC         201840.0      2
M-LC         163695.0      1
M-MC          83466.0      2
L-MC          49238.0      1
H-LC          47313.0      1

In [31]:
# money to be made criteria and conviction-wise
df_portfolio_features.groupby(['Conviction', 'Criteria'])['FTT Amt'].agg(['sum', 'count']).sort_values(by='sum', ascending=False)

                           sum  count
Conviction Criteria
X-LC       X40       1010281.0     10
H-SC       XY24       994137.0      6
           AR         949973.0      5
M-SC       XY24       821072.0      6
H-SC       XR         784305.0      7
X-SC       XY24       775770.0      4
X-MC       X40        691517.0      7
           X40N       439489.0      4
X-LC       X40N       341685.0      6
           XY24       336211.0      2
M-SC       OX40N      311616.0      5
H-SC       OX40N      310964.0      4
X-SC       X40N       309596.0      3
H-SC       SR         286720.0      2
H-MC       XY24       244187.0      1
X-MC       XY25       240385.0      2
           XY24       228355.0      2
X-SC       X40        211338.0      2
M-SC       XR         193399.0      2
M-LC       XR         163695.0      1
X-LC       XY25       152323.0      2
L-SC       OX40N      113829.0      1
           XR          88011.0      1
M-SC       AR          73681.0      1
H-MC       AR          49682.0      1
L-MC       XR          49238.0      1
M-MC       XY25        47986.0      1
H-LC       AR          47313.0      1
X-LC       XR          40286.0      1
M-MC       AR          35480.0      1

In [32]:
# notebook execution time

end_time = time.time()
execution_time = round(end_time - start_time, 0)
print(f"Notebook execution time: {execution_time} seconds")

Notebook execution time: 37.0 seconds