<a href="https://colab.research.google.com/github/ankit-rathi/Quantvesting_v2/blob/main/myStocks_Portfolio_Analysis.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
'''
!pip install pandas==2.2.2 -qq
!pip install pyxirr -qq
!pip install ta -qq
!pip install yfinance==0.2.59 -qq
'''

'\n!pip install pandas==2.2.2 -qq\n!pip install pyxirr -qq\n!pip install ta -qq\n!pip install yfinance==0.2.59 -qq\n'

In [2]:
# import libraries

import numpy as np
import pandas as pd
import datetime
import warnings
warnings.filterwarnings('ignore')
import yfinance as yfin
import ta
import matplotlib.pyplot as plt
import requests

In [3]:
# notebook start time
import time
import datetime
import pytz

start_time = time.time()

# function to print date timestamp
def print_date_time():
  tz_NY = pytz.timezone('Asia/Kolkata')
  datetime_NY = datetime.datetime.now(tz_NY)
  print("Run date time (IST):", datetime_NY.strftime("%Y-%m-%d %H:%M:%S"))

In [4]:
# function to get booked and reserved amount
def get_amt():
  # fetch the JSON data from the URL
  url = "https://raw.githubusercontent.com/ankit-rathi/Tradevesting_v1/main/data/myPortfolioAmts.json"
  response = requests.get(url)
  pf_amts = response.json()  # parse the JSON data

  # extract values from the JSON
  py_booked_amt_dm = pf_amts["py_booked_amt_dm"]
  py_booked_amt_sv = pf_amts["py_booked_amt_sv"]
  cy_booked_amt_dm = pf_amts["cy_booked_amt_dm"]
  cy_booked_amt_sv = pf_amts["cy_booked_amt_sv"]
  reserve_amt_dm = pf_amts["reserve_amt_dm"]
  reserve_amt_sv = pf_amts["reserve_amt_sv"]

  # perform calculations
  py_booked_amt = py_booked_amt_dm + py_booked_amt_sv
  cy_booked_amt = cy_booked_amt_dm + cy_booked_amt_sv
  reserve_amt = reserve_amt_dm + reserve_amt_sv
  total_booked_amt = py_booked_amt + cy_booked_amt

  return total_booked_amt, reserve_amt, cy_booked_amt, py_booked_amt

gen_output = 0

In [5]:
# function to format the amount
def format_amt(number):
    abs_number = abs(number)

    if abs_number >= 1_00_00_000:  # Crores
        formatted_amt = f"{number / 1_00_00_000:.2f} C"
    elif abs_number >= 1_00_000:  # Lakhs
        formatted_amt = f"{number / 1_00_000:.2f} L"
    elif abs_number >= 1_000:  # Thousands
        formatted_amt = f"{number / 1_000:.2f} K"
    else:
        formatted_amt = f"{number:.2f}"

    return formatted_amt

# function to set start and end date
def get_start_end_date():
  start_date = (datetime.date.today() + datetime.timedelta(days=-365)).strftime('%Y-%m-%d')
  end_date = (datetime.date.today() + datetime.timedelta(days=1)).strftime('%Y-%m-%d')
  return start_date, end_date

# function to fetch my portfolio csv
def get_mypfs_df():
  mypfs_df = pd.read_csv('https://raw.githubusercontent.com/ankit-rathi/Tradevesting_v1/main/data/myPortfolioStocks.csv')
  return mypfs_df

# function to fetch my prospects csv
def get_mypps_df():
  mypps_df = pd.read_csv('https://raw.githubusercontent.com/ankit-rathi/Tradevesting_v1/main/data/myProspectsScrips.csv')
  return mypps_df

# function to fetch screener data
def get_myscreen_df():
  myscreen_df = pd.read_csv('https://raw.githubusercontent.com/ankit-rathi/Tradevesting_v1/main/data/myScreenerDB.csv')
  return myscreen_df

# function to fetch momentum data
def get_myinvmt_df():
  myinvmt_df = pd.read_csv('https://raw.githubusercontent.com/ankit-rathi/Tradevesting_v1/main/data/myInvestments.csv')
  return myinvmt_df

# function to get the stock ids
def get_stock_ids(df_pf):
  stock_n100 = df_pf['Symbol'].unique()

  exclude = ['CADILAHC','MMTC', 'MASFIN']

  stock_ids = df_pf[~df_pf['Symbol'].isin(exclude) ]['Symbol'].unique()

  #mypf = mypf[mypf.Forecast.notnull()]
  #stock_ids = mypf['Symbol'].unique()

  #stock_ids.sort()
  return stock_ids

# get features from screener data
def get_screener_features():
  myscreen_df = get_myscreen_df()
  cols = ['Symbol', 'EPS', 'MedPE', 'ROCE%', 'ROE%', 'CapType']
  return myscreen_df[cols]

# get relative strength
def get_relative_strength(stock_list):

    # Dictionary to store stock tickers and their corresponding percentage price change
    stock_changes = {}

    # Loop through each stock and fetch its price data
    for stock in stock_list:
        try:
            # Download the stock data for the given date range
            stock_data = yfin.Ticker(stock + '.NS').history(period='1mo', interval='1d')[map(str.title, ['open', 'close', 'low', 'high', 'volume'])]

            # Calculate the percentage change for the stock
            if len(stock_data) > 0:
                start_price = stock_data['Close'].iloc[0]
                end_price = stock_data['Close'].iloc[-1]
                percent_change = round(((end_price - start_price) / start_price) * 100, 2)
                stock_changes[stock] = percent_change
            else:
                stock_changes[stock] = np.nan  # If no data is available, set to NaN

        except Exception as e:
            print(f"Error fetching data for {stock}: {e}")
            stock_changes[stock] = np.nan

    # Create a DataFrame with stock tickers and their percentage changes
    df = pd.DataFrame(list(stock_changes.items()), columns=['Symbol', 'Percent_Change'])

    # Drop any stocks with missing data (NaN values)
    df = df.dropna()

    # Calculate the percentile rank based on percentage change
    df['RSP'] = round(df['Percent_Change'].rank(pct=True) * 100, 2)
    cols = ['Symbol', 'RSP']
    df = df[cols]
    # Sort by percentile rank (optional)
    df = df.sort_values(by='RSP', ascending=False).reset_index(drop=True)

    return df

In [6]:
# function to get stock technicals
def stock_prec_dev(stock_symbol):
    #stock_symbol = 'ULTRACEMCO.NS'
    short_window = 20
    mid_window = 50
    long_window = 200
    moving_avg = 'SMA'

    start = datetime.datetime(*map(int, start_date.split('-')))
    end = datetime.datetime(*map(int, end_date.split('-')))

    stock_df = yfin.Ticker(stock_symbol + '.NS').history(period='max', interval='1d')[map(str.title, ['open', 'close', 'low', 'high', 'volume'])]

    stock_df['Max'] = round(max(stock_df['Close']),2)
    stock_df = stock_df[(stock_df.index <= end_date) & (stock_df.index >= start_date)]
    stock_df['200_SMA'] = round(stock_df['Close'].rolling(window = 200, min_periods = 1).mean(),0)
    stock_df['Dev%_200'] = round((stock_df['Close'] - stock_df['200_SMA'])*100/stock_df['200_SMA'],2)
    stock_df.dropna(axis = 0, inplace = True) # remove any null rows

    stock_df['20_SMA'] = stock_df['Close'].rolling(window=20).mean()
    stock_df['50_SMA'] = stock_df['Close'].rolling(window=50).mean()
    stock_df['Symbol'] = stock_symbol

    stock_df['Close'] = round(stock_df['Close'],2)
    stock_df['Min'] = round(min(stock_df['Close']),2)
    stock_df['RSI_14'] = ta.momentum.RSIIndicator(close=stock_df['Close'], window=14).rsi()
    stock_df['RSI_14'] = round(stock_df['RSI_14'],0)
    stock_df['Prev_Close'] = stock_df['Close'].shift(1)
    stock_df.drop(['Open', 'Low', 'High', 'Volume'], axis=1, inplace=True)
    stock_df = stock_df.tail(1)

    max_SMA = max(stock_df['20_SMA'].item(), stock_df['50_SMA'].item(), stock_df['200_SMA'].item())
    min_SMA = min(stock_df['20_SMA'].item(), stock_df['50_SMA'].item(), stock_df['200_SMA'].item())
    ABS_Spread = max_SMA - min_SMA
    stock_df['Spread%'] = round((ABS_Spread / stock_df['200_SMA'].item()) * 100,2)

    return stock_df

# function to compute stock attributes
def get_common_features(stock_ids, df_mypf):

  df_prec_dev = pd.DataFrame()
  df_tmp = get_screener_features()
  df_rs = get_relative_strength(stock_ids)

  for stock_id in stock_ids:
      tmp = stock_prec_dev(stock_id)
      tmp = tmp.reset_index()
      df_prec_dev = pd.concat([df_prec_dev, tmp], ignore_index = True)
  df_prec_dev = pd.merge(df_prec_dev, df_mypf, on= 'Symbol')
  df_prec_dev = pd.merge(df_prec_dev, df_tmp, on= 'Symbol', how='left')
  df_prec_dev = pd.merge(df_prec_dev, df_rs, on= 'Symbol', how='left')
  #print(df_prec_dev.columns)
  df_prec_dev['Curr_PE'] = round(df_prec_dev['Close']/df_prec_dev['EPS'],1)
  df_prec_dev['Dev%_PE'] = round((df_prec_dev['Curr_PE'] - df_prec_dev['MedPE'])*100/df_prec_dev['MedPE'],2)
  df_prec_dev['Conviction'] = df_prec_dev['Conviction'] + '-' + df_prec_dev['CapType']
  return df_prec_dev

# function to arrange stock features
def arrange_features(df_stocks, common_cols, diff_cols):
  df_stocks_common = df_stocks[common_cols].drop_duplicates()
  df_stocks_diff = df_stocks[diff_cols]
  df_stocks_diff['Investment'] = df_stocks_diff['AvgCost'] * df_stocks_diff['Shares']
  df_stocks_diff = df_stocks_diff.groupby(['Symbol'])[['Shares', 'Investment']].aggregate(['sum']).reset_index()
  df_stocks_diff.columns = ['Symbol', 'Shares', 'Investment']
  df_stocks_diff['AvgCost'] = round(df_stocks_diff['Investment']/df_stocks_diff['Shares'],2)
  df_stocks = pd.merge(df_stocks_diff, df_stocks_common, on='Symbol')
  return df_stocks

# plot fact distribution across dimension
def plot_pie_chart(df, dimension, fact):
  # grouping the data by category and calculating the sum of fact for each type
  grouped_data = df.groupby(dimension)[fact].sum()

  # sorting the grouped data in descending order
  grouped_data = grouped_data.sort_values(ascending=False)

  # creating a pie chart
  grouped_data.plot.pie(autopct='%1.1f%%', startangle=90, figsize=(6, 6))

  # adding a title and displaying the plot
  plt.title(f'{dimension} {fact} Distribution')
  plt.ylabel('')  # To hide the y-label
  plt.show()

In [7]:
# function to get portfolio features

def get_portfolio_features(df_common_features):

  print_date_time()
  print('-------------------')

  #df_common_features["Target"] = df_common_features["Target"].fillna(df_common_features["Max"])
  df_common_features['NTT'] = np.where(df_common_features['Strategy']== 'NTT', df_common_features["Target"], df_common_features['Max'])
  df_common_features['LTT'] = np.where(df_common_features['Strategy']== 'BTT', df_common_features["Target"], df_common_features['Max'])
  df_common_features['BOL'] = df_common_features['Min']

  tmp_df = df_common_features[df_common_features['Symbol'].isin(mypf_df[mypf_df['InPortfolio'] != 'NA'].Symbol.values)]
  print('qualified stocks: '+str(len(tmp_df['Symbol'].unique())))
  tmp_df1 = tmp_df[tmp_df['LatestQtr'] == 1]
  print('with latest results: '+str(len(tmp_df1['Symbol'].unique())))
  tmp_df1 = tmp_df1[tmp_df1['StarStock'] == 1]
  print('still star stocks: '+str(len(tmp_df1['Symbol'].unique())))
  tmp_df['Investment'] = tmp_df['AvgCost'] * tmp_df['Shares']
  tmp_df['Current'] = round(tmp_df['Close'] * tmp_df['Shares'],0)
  tmp_df['Previous'] = tmp_df['Prev_Close'] * tmp_df['Shares']
  tmp_df['EstimatedST'] = tmp_df['NTT'] * tmp_df['Shares']
  tmp_df['EstimatedLT'] = tmp_df['LTT'] * tmp_df['Shares']
  tmp_df['Current P/L'] = round((tmp_df['Current'] - tmp_df['Investment']),0)
  tmp_df['Today P/L%'] = round((tmp_df['Current'] - tmp_df['Previous'])*100/tmp_df['Previous'],2)
  tmp_df['Current P/L%'] = round((tmp_df['Current'] - tmp_df['Investment'])*100/tmp_df['Investment'],2)
  tmp_df['EstimatedST P/L%'] = round((tmp_df['EstimatedST'] - tmp_df['Investment'])*100/tmp_df['Investment'],2)
  tmp_df['EstimatedLT P/L%'] = round((tmp_df['EstimatedLT'] - tmp_df['Investment'])*100/tmp_df['Investment'],2)
  tmp_df['NTT%'] = round((tmp_df['NTT'] - tmp_df['Close'])*100/tmp_df['Close'],2)
  tmp_df['LTT%'] = round((tmp_df['LTT'] - tmp_df['Close'])*100/tmp_df['Close'],2)
  tmp_df['Gained%'] = round((tmp_df['Close'] - tmp_df['BOL'])*100/tmp_df['BOL'],2)
  investment = round(sum(tmp_df['AvgCost']*tmp_df['Shares']),0)
  current = round(sum(tmp_df['Close']*tmp_df['Shares']),0)
  tmp_df['InitAlloc%'] = round(tmp_df['Investment']*100/investment,2)
  tmp_df['CurrAlloc%'] = round(tmp_df['Current']*100/current,2)
  tmp_df['FTT'] = tmp_df['LTT']
  tmp_df.loc[tmp_df['Strategy'] == 'NTT', 'FTT'] = tmp_df['NTT']
  tmp_df['FTT%'] = tmp_df['LTT%']
  tmp_df.loc[tmp_df['Strategy'] == 'NTT', 'FTT%'] = tmp_df['NTT%']
  tmp_df['FTT Amt'] = round(tmp_df['FTT%'] * tmp_df['Current']/100,0)
  tmp_df['OTT%'] = round((tmp_df['FTT'] - tmp_df['AvgCost'])*100/tmp_df['AvgCost'],2)
  tmp_df['RRR Ind'] = round(tmp_df['Current P/L']/tmp_df['FTT Amt'],2)
  tmp_df['Risk Ind'] = round(tmp_df['Current P/L%']*tmp_df['CurrAlloc%'],0)

  return tmp_df

# function to print portfolio features
def print_portfolio_stats(df_portfolio_features, myinvmt_df):
  from pyxirr import xirr

  total_booked_amt, reserve_amt, cy_booked_amt, py_booked_amt = get_amt()

  dates = myinvmt_df['Date'].values
  dates = np.append(dates, datetime.date.today().strftime('%d-%b-%y'))
  investment = myinvmt_df['Investment'].values
  dates= pd.to_datetime(dates)

  current = round(sum(df_portfolio_features['Close']*df_portfolio_features['Shares']),0) + reserve_amt
  investment_xirr = np.append(investment, current)
  cagr = round(xirr(pd.DataFrame({"dates": dates, "amounts": investment_xirr}))*100,2)

  investment = -sum(investment)
  invested = round(sum(df_portfolio_features['AvgCost']*df_portfolio_features['Shares']),0) + reserve_amt
  previous = round(sum(df_portfolio_features['Prev_Close']*df_portfolio_features['Shares']),0) + reserve_amt
  cy_invested = investment + py_booked_amt

  today_pnl_amount = current-previous
  today_pnl_percentage = round((current-previous)*100/previous,2)

  curr_pnl_amount = current-invested
  curr_pnl_percentage = round((curr_pnl_amount)*100/(cy_invested),2)

  cy_pnl_amount = cy_booked_amt + curr_pnl_amount
  cy_pnl_percentage = round((cy_pnl_amount)*100/cy_invested,2)

  overall_pnl_amount = total_booked_amt + curr_pnl_amount
  overall_pnl_percentage = round((overall_pnl_amount)*100/investment,2)

  estimate_st = round(sum(df_portfolio_features['FTT']*df_portfolio_features['Shares']),0)  + reserve_amt
  est_st_pnl_amount = estimate_st-current
  est_st_pnl_percentage = round((est_st_pnl_amount)*100/current,2)

  estimate_lt = round(sum(df_portfolio_features['LTT']*df_portfolio_features['Shares']),0)  + reserve_amt
  est_lt_pnl_amount = estimate_lt-current
  est_lt_pnl_percentage = round((est_lt_pnl_amount)*100/current,2)

  total_profit = round(sum(df_portfolio_features[df_portfolio_features['Current P/L%'] > 0]['Current']) - sum(df_portfolio_features[df_portfolio_features['Current P/L%'] > 0]['Investment']),0)
  total_loss = round(sum(df_portfolio_features[df_portfolio_features['Current P/L%'] < 0]['Current']) - sum(df_portfolio_features[df_portfolio_features['Current P/L%'] < 0]['Investment']),0)

  cy_booked_percentage = round((cy_booked_amt)*100/current,2)
  py_booked_percentage = round((py_booked_amt)*100/investment,2)
  total_booked_percentage = round((total_booked_amt)*100/investment,2)

  print('-------------------')
  print('Initial Investment: ', format_amt(investment))
  print('CY Investment: ', format_amt(cy_invested))
  print('Reserve: ', format_amt(reserve_amt))
  print('Current: ',  format_amt(current))
  print('-------------------')
  print('Today PnL: '+ '{} ({}%)'.format(format_amt(today_pnl_amount), today_pnl_percentage))
  print('Current PnL: '+ '{} ({}%)'.format(format_amt(curr_pnl_amount), curr_pnl_percentage))
  print('CY Booked + Current PnL: '+ '{} ({}%)'.format(format_amt(cy_pnl_amount), cy_pnl_percentage))
  print('-------------------')
  print('Total profit: ', format_amt(total_profit))
  print('Total loss: ', format_amt(total_loss))
  print('-------------------')
  print('Total Booked + Current PnL: '+ '{} ({}%)'.format(format_amt(overall_pnl_amount), overall_pnl_percentage))
  print('Total Booked PnL: '+ '{} ({}%)'.format(format_amt(total_booked_amt), total_booked_percentage))
  print('Curr Year Booked PnL: '+ '{} ({}%)'.format(format_amt(cy_booked_amt), cy_booked_percentage))
  print('Prev Year Booked PnL: '+ '{} ({}%)'.format(format_amt(py_booked_amt), py_booked_percentage))
  print('===================')
  print('Est FTT: ',  format_amt(estimate_st))
  print('Est FTT PnL: '+ '{} ({}%)'.format(format_amt(est_st_pnl_amount), est_st_pnl_percentage))

  print('===================')
  print('Deployed: ', format_amt(investment))

  print('Current: ', format_amt(current))

  print('CAGR/XIRR %: '+'{}%'.format(cagr))

In [8]:
# get start and end date
start_date, end_date = get_start_end_date()

# get portfolio and prospects data
mypfs_df = get_mypfs_df()
mypps_df = get_mypps_df()
myinvmt_df = get_myinvmt_df()

# merge above datasets
mypf_df = pd.merge(mypfs_df, mypps_df, on="Symbol")

# seggregate dm and sv portfolio
dm_pf = mypf_df[mypf_df['InPortfolio'] == 'DM']
sv_pf = mypf_df[mypf_df['InPortfolio'] == 'SV']

# build portfolio stock dataframe
dm_stocks = get_stock_ids(dm_pf)
sv_stocks = get_stock_ids(sv_pf)
df_stocks = pd.concat([dm_pf,sv_pf], ignore_index = True)

# arrange common and diff stock features
common_cols = ['Symbol', 'Target', 'Criteria', 'Strategy', 'CumlRnk', 'LatestQtr', 'StarStock', 'Conviction', 'Category', 'InFolio', 'XIRR', 'MBQ']
diff_cols = ['Symbol', 'AvgCost', 'Shares']
df_stocks = arrange_features(df_stocks, common_cols, diff_cols)

# get common features
stock_ids = df_stocks['Symbol'].values
df_common_features = get_common_features(stock_ids, df_stocks)

df_common_features.reset_index(drop=True, inplace=True)
df_common_features.drop(['Date'], axis=1, inplace=True)
# get and print portfolio features
df_portfolio_features = get_portfolio_features(df_common_features)

print_portfolio_stats(df_portfolio_features, myinvmt_df)

df = df_portfolio_features
#plot_pie_chart(df, 'CapType', 'Current')
list_ox40n = list(df[df['MBQ'].str.contains('OX40N', na=False)]['Symbol'].values)

Run date time (IST): 2026-04-22 14:19:55
-------------------
qualified stocks: 90
with latest results: 28
still star stocks: 17
-------------------
Initial Investment:  1.38 C
CY Investment:  1.80 C
Reserve:  1.84 K
Current:  1.48 C
-------------------
Today PnL: 65.52 K (0.45%)
Current PnL: -32.50 L (-18.02%)
CY Booked + Current PnL: -31.54 L (-17.48%)
-------------------
Total profit:  2.23 L
Total loss:  -34.73 L
-------------------
Total Booked + Current PnL: 11.33 L (8.24%)
Total Booked PnL: 43.83 L (31.88%)
Curr Year Booked PnL: 96.00 K (0.65%)
Prev Year Booked PnL: 42.87 L (31.18%)
===================
Est FTT:  2.52 C
Est FTT PnL: 1.05 C (70.91%)
===================
Deployed:  1.38 C
Current:  1.48 C
CAGR/XIRR %: 3.42%

In [9]:
# top 5 near their targets
cols = ['Symbol', 'Today P/L%', 'Current P/L%', 'FTT%', 'OTT%', 'FTT Amt', 'Current P/L', 'Current', 'FTT', 'Dev%_PE', 'RSI_14','Conviction', 'Spread%',  'CumlRnk', 'RRR Ind', 'CurrAlloc%', 'Gained%', 'Criteria', 'Strategy', 'Category']
df_tmp = df_portfolio_features[~df_portfolio_features['Symbol'].isin(['ENRIN','BLUSPRING','DIGITIDE'])]
df_tmp = df_tmp.sort_values(by = 'FTT Amt', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
1,ABB,4.82,39.52,4.33,45.57,15805.0,103397.0,365016.0,7934.00,-10.30,82.0,H-MC,19.51,125.0,6.54,2.47,62.09,AR,NTT,ELECTRICAL
54,MASFIN,1.71,-1.62,23.57,21.57,22719.0,-1590.0,96390.0,397.04,-15.09,60.0,H-SC,2.91,167.0,-0.07,0.65,24.56,XR,ATH,FINANCE
53,MARUTI,-0.54,-0.94,29.16,27.95,31232.0,-1016.0,107104.0,17292.00,-18.07,51.0,X-LC,12.09,33.0,-0.03,0.73,15.69,XR,ATH,AUTO
61,RECLTD,0.09,3.87,16.24,20.74,34272.0,7865.0,211035.0,446.00,15.23,71.0,M-MC,4.08,191.0,0.23,1.43,25.76,XY25,NTT,FINANCE
81,TTKPRESTIG,1.40,-33.97,51.57,0.09,34319.0,-34229.0,66548.0,770.00,54.54,58.0,M-SC,22.61,250.0,-1.00,0.45,18.50,OX40N,NTT,DURABLES

In [10]:
# top 5 today
df_tmp = df_portfolio_features.sort_values(by = 'Today P/L%', ascending=False)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
7,AWL,5.20,-31.71,144.58,67.02,351783.0,-112995.0,243314.0,485.0,-63.27,65.0,X-SC,22.82,81.0,-0.32,1.65,15.09,XY24,NTT,FMCG
59,RAJESHEXPO,4.99,-76.32,322.62,0.07,104790.0,-104696.0,32481.0,518.0,1090.66,58.0,L-SC,40.48,268.0,-1.00,0.22,52.49,OX40N,NTT,JEWELLERY
1,ABB,4.82,39.52,4.33,45.57,15805.0,103397.0,365016.0,7934.0,-10.30,82.0,H-MC,19.51,125.0,6.54,2.47,62.09,AR,NTT,ELECTRICAL
17,CERA,4.08,-27.94,71.92,23.89,91167.0,-49141.0,126762.0,9475.0,-30.55,72.0,H-SC,13.22,153.0,-0.54,0.86,21.82,OX40N,NTT,CERAMICS
0,5PAISA,3.89,-35.60,75.31,12.90,105973.0,-77780.0,140716.0,593.0,106.73,67.0,H-SC,13.45,170.0,-0.73,0.95,35.79,OX40N,NTT,FINANCE

In [11]:
# bottom 5 today
df_tmp = df_portfolio_features.sort_values(by = 'Today P/L%', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
34,HCLTECH,-10.45,-16.24,47.85,23.83,96956.0,-39300.0,202624.0,1908.19,-11.91,33.0,X-LC,7.25,8.0,-0.41,1.37,0.00,X40,ATH,IT
76,TATAELXSI,-5.39,-36.59,108.20,32.03,90455.0,-48235.0,83600.0,9161.00,-20.70,48.0,H-SC,17.82,158.0,-0.53,0.57,10.65,OX40N,NTT,IT
46,INFY,-3.48,-13.71,55.58,34.24,150054.0,-42910.0,269978.0,1972.00,-32.15,41.0,X-LC,12.57,3.0,-0.29,1.83,3.83,X40,NTT,IT
77,TCS,-2.59,-25.35,69.55,26.57,240537.0,-117425.0,345848.0,4311.59,-36.74,51.0,X-LC,15.68,2.0,-0.49,2.34,7.94,X40,ATH,IT
22,DEN,-2.11,-46.45,165.30,42.07,74768.0,-39232.0,45232.0,75.00,60.62,56.0,M-SC,16.48,235.0,-0.52,0.31,23.02,AR,NTT,ENTERTAINMENT

In [12]:
# top 5 to exit based on CumlRnk
df_tmp = df_portfolio_features[~df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])]
df_tmp = df_tmp[(df_tmp['Current P/L%'] > -1) & (df_tmp['Current P/L%'] < 1)].sort_values(by = 'CumlRnk', ascending=False)
df_tmp[cols].head()

Empty DataFrame
Columns: [Symbol, Today P/L%, Current P/L%, FTT%, OTT%, FTT Amt, Current P/L, Current, FTT, Dev%_PE, RSI_14, Conviction, Spread%, CumlRnk, RRR Ind, CurrAlloc%, Gained%, Criteria, Strategy, Category]
Index: []

In [13]:
# OX40N stocks to exit
df_tmp = df_portfolio_features[(df_portfolio_features['Symbol'].isin(list_ox40n))].sort_values(by = 'Current P/L%', ascending=False)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
26,FINCABLES,2.47,23.75,68.01,107.91,124260.0,35064.0,182708.0,1641.55,11.11,71.0,M-SC,4.22,220.0,0.28,1.24,37.46,OX40N,ATH,CABLES
70,SIS,0.30,-22.37,56.21,21.26,48447.0,-24842.0,86190.0,528.00,2035.75,76.0,H-SC,9.23,168.0,-0.51,0.58,28.15,OX40N,NTT,MISC
17,CERA,4.08,-27.94,71.92,23.89,91167.0,-49141.0,126762.0,9475.00,-30.55,72.0,H-SC,13.22,153.0,-0.54,0.86,21.82,OX40N,NTT,CERAMICS
51,KANSAINER,0.37,-30.91,64.25,13.47,119698.0,-83367.0,186300.0,340.00,-40.61,67.0,H-SC,19.26,162.0,-0.70,1.26,30.13,XY24,NTT,PAINTS
81,TTKPRESTIG,1.40,-33.97,51.57,0.09,34319.0,-34229.0,66548.0,770.00,54.54,58.0,M-SC,22.61,250.0,-1.00,0.45,18.50,OX40N,NTT,DURABLES

In [14]:
# top 5 to book for rotation
df_tmp = df_portfolio_features[(df_portfolio_features['Current P/L%'] > 20) ].sort_values(by = 'CumlRnk', ascending=False)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
26,FINCABLES,2.47,23.75,68.01,107.91,124260.0,35064.0,182708.0,1641.55,11.11,71.0,M-SC,4.22,220.0,0.28,1.24,37.46,OX40N,ATH,CABLES
1,ABB,4.82,39.52,4.33,45.57,15805.0,103397.0,365016.0,7934.00,-10.30,82.0,H-MC,19.51,125.0,6.54,2.47,62.09,AR,NTT,ELECTRICAL

In [15]:
# top 5 to monitor for exit
df_tmp = df_portfolio_features[~df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])]
df_tmp = df_tmp[(df_tmp['Current P/L%'] > 0) ].sort_values(by = 'Dev%_PE', ascending=False)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
61,RECLTD,0.09,3.87,16.24,20.74,34272.0,7865.0,211035.0,446.00,15.23,71.0,M-MC,4.08,191.0,0.23,1.43,25.76,XY25,NTT,FINANCE
26,FINCABLES,2.47,23.75,68.01,107.91,124260.0,35064.0,182708.0,1641.55,11.11,71.0,M-SC,4.22,220.0,0.28,1.24,37.46,OX40N,ATH,CABLES
1,ABB,4.82,39.52,4.33,45.57,15805.0,103397.0,365016.0,7934.00,-10.30,82.0,H-MC,19.51,125.0,6.54,2.47,62.09,AR,NTT,ELECTRICAL
71,SONACOMS,1.60,2.17,36.14,39.09,37352.0,2196.0,103355.0,804.02,-18.98,66.0,M-MC,11.43,193.0,0.06,0.70,46.21,AR,ATH,AUTO

In [16]:
# top 5 to book for rotation from weak conviction
df_tmp = df_portfolio_features[~df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])]
df_tmp = df_tmp[~df_tmp['Criteria'].isin(['XY25','XY24','X40', 'X40N'])].sort_values(by = 'RRR Ind', ascending=False)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
1,ABB,4.82,39.52,4.33,45.57,15805.0,103397.0,365016.0,7934.00,-10.30,82.0,H-MC,19.51,125.0,6.54,2.47,62.09,AR,NTT,ELECTRICAL
26,FINCABLES,2.47,23.75,68.01,107.91,124260.0,35064.0,182708.0,1641.55,11.11,71.0,M-SC,4.22,220.0,0.28,1.24,37.46,OX40N,ATH,CABLES
71,SONACOMS,1.60,2.17,36.14,39.09,37352.0,2196.0,103355.0,804.02,-18.98,66.0,M-MC,11.43,193.0,0.06,0.70,46.21,AR,ATH,AUTO
89,ZYDUSLIFE,0.23,-1.86,38.19,35.63,78551.0,-3889.0,205685.0,1286.17,-14.41,58.0,H-MC,4.64,120.0,-0.05,1.39,10.40,AR,ATH,PHARMA
43,INDIAMART,0.26,-6.63,121.41,106.72,139807.0,-8183.0,115153.0,4810.62,-57.81,61.0,H-SC,11.54,140.0,-0.06,0.78,10.63,AR,ATH,MISC

In [17]:
# top 5 to accumulate based on lowest RSI_14
df_tmp = df_portfolio_features[df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])].sort_values(by = 'RSI_14', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
34,HCLTECH,-10.45,-16.24,47.85,23.83,96956.0,-39300.0,202624.0,1908.19,-11.91,33.0,X-LC,7.25,8.0,-0.41,1.37,0.00,X40,ATH,IT
2,ABBOTINDIA,0.35,-14.54,38.16,18.07,58328.0,-26005.0,152850.0,35195.00,-27.31,40.0,X-MC,11.85,58.0,-0.45,1.04,0.35,X40,ATH,PHARMA
41,ICICIPRULI,-1.86,-10.67,46.34,30.73,81554.0,-21014.0,175991.0,790.00,-34.67,41.0,X-MC,12.99,78.0,-0.26,1.19,7.24,X40,ATH,INSURANCE
46,INFY,-3.48,-13.71,55.58,34.24,150054.0,-42910.0,269978.0,1972.00,-32.15,41.0,X-LC,12.57,3.0,-0.29,1.83,3.83,X40,NTT,IT
36,HDFCLIFE,-1.74,-1.66,34.93,32.69,41106.0,-1990.0,117682.0,814.30,-22.96,43.0,X-LC,17.83,31.0,-0.05,0.80,6.61,X40,ATH,INSURANCE

In [18]:
# top 5 to accumulate based on Spread and CumlRnk
df_tmp = df_portfolio_features[df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])]
df_tmp = df_tmp[(df_tmp['CumlRnk'] < 100)].sort_values(by = 'Spread%', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
69,SIEMENS,3.25,3.24,21.57,25.51,41441.0,6030.0,192125.0,4671.50,61.28,76.0,H-LC,3.72,51.0,0.15,1.30,35.61,AR,ATH,ELECTRICAL
63,RELIANCE,0.44,-12.75,43.61,25.30,76464.0,-25626.0,175337.0,1952.00,-15.03,49.0,X-LC,5.70,21.0,-0.34,1.19,5.69,XY25,BTT,REFINERIES
24,DMART,0.17,10.51,17.28,29.60,47663.0,26226.0,275826.0,5391.45,-6.84,69.0,X-LC,5.74,14.0,0.55,1.87,26.08,X40N,ATH,FMCG
82,UNITDSPR,2.49,2.62,17.68,20.77,42482.0,6140.0,240284.0,1644.00,-8.94,65.0,X-MC,5.74,64.0,0.14,1.63,14.62,X40N,NTT,BREWERIES
86,VOLTAS,2.52,16.87,24.24,45.20,54318.0,32343.0,224085.0,1856.00,33.74,65.0,X-MC,6.48,79.0,0.60,1.52,24.81,XY25,NTT,AC

In [19]:
# top 5 to accumulate based on lowest Gained%
df_tmp = df_portfolio_features[df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])].sort_values(by = 'Gained%', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
34,HCLTECH,-10.45,-16.24,47.85,23.83,96956.0,-39300.0,202624.0,1908.19,-11.91,33.0,X-LC,7.25,8.0,-0.41,1.37,0.00,X40,ATH,IT
2,ABBOTINDIA,0.35,-14.54,38.16,18.07,58328.0,-26005.0,152850.0,35195.00,-27.31,40.0,X-MC,11.85,58.0,-0.45,1.04,0.35,X40,ATH,PHARMA
18,CIPLA,0.26,0.39,34.63,35.15,42364.0,475.0,122334.0,1663.60,-22.43,46.0,X-LC,15.83,18.0,0.01,0.83,3.63,X40N,ATH,PHARMA
46,INFY,-3.48,-13.71,55.58,34.24,150054.0,-42910.0,269978.0,1972.00,-32.15,41.0,X-LC,12.57,3.0,-0.29,1.83,3.83,X40,NTT,IT
63,RELIANCE,0.44,-12.75,43.61,25.30,76464.0,-25626.0,175337.0,1952.00,-15.03,49.0,X-LC,5.70,21.0,-0.34,1.19,5.69,XY25,BTT,REFINERIES

In [20]:
# top 5 to accumulate based on lowest CurrAlloc%
df_tmp = df_portfolio_features[df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])].sort_values(by = 'CurrAlloc%', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
62,RELAXO,1.56,-59.74,278.28,52.31,162641.0,-86715.0,58445.0,1176.0,-57.12,59.0,X-SC,31.05,92.0,-0.53,0.40,30.68,X40N,NTT,FOOTWEAR
11,BATAINDIA,0.62,-50.52,173.27,35.20,110305.0,-65009.0,63661.0,2096.0,-16.53,64.0,X-SC,30.82,91.0,-0.59,0.43,26.26,X40,NTT,FOOTWEAR
58,QUESS,0.67,-19.00,114.69,73.90,99208.0,-20292.0,86501.0,424.0,-56.47,60.0,X-SC,18.58,80.0,-0.20,0.59,16.36,XY24,NTT,MISC
53,MARUTI,-0.54,-0.94,29.16,27.95,31232.0,-1016.0,107104.0,17292.0,-18.07,51.0,X-LC,12.09,33.0,-0.03,0.73,15.69,XR,ATH,AUTO
36,HDFCLIFE,-1.74,-1.66,34.93,32.69,41106.0,-1990.0,117682.0,814.3,-22.96,43.0,X-LC,17.83,31.0,-0.05,0.80,6.61,X40,ATH,INSURANCE

In [21]:
# top 5 to accumulate based on CumlRnk
df_tmp = df_portfolio_features.sort_values(by = 'CumlRnk', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
48,ITC,-1.36,-19.54,47.98,19.06,131313.0,-66483.0,273683.0,452.00,-55.92,52.0,X-LC,18.77,1.0,-0.51,1.85,6.17,X40,NTT,FMCG
77,TCS,-2.59,-25.35,69.55,26.57,240537.0,-117425.0,345848.0,4311.59,-36.74,51.0,X-LC,15.68,2.0,-0.49,2.34,7.94,X40,ATH,IT
46,INFY,-3.48,-13.71,55.58,34.24,150054.0,-42910.0,269978.0,1972.00,-32.15,41.0,X-LC,12.57,3.0,-0.29,1.83,3.83,X40,NTT,IT
79,TMPV,1.83,-17.51,65.56,36.58,192447.0,-62297.0,293544.0,600.00,-82.53,64.0,X-LC,8.94,4.0,-0.32,1.99,22.35,XY24,NTT,AUTO
34,HCLTECH,-10.45,-16.24,47.85,23.83,96956.0,-39300.0,202624.0,1908.19,-11.91,33.0,X-LC,7.25,8.0,-0.41,1.37,0.00,X40,ATH,IT

In [22]:
# top 5 for average up
df_tmp = df_portfolio_features[(df_portfolio_features['Dev%_200'] > 5)].sort_values(by = 'CurrAlloc%', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
71,SONACOMS,1.60,2.17,36.14,39.09,37352.0,2196.0,103355.0,804.02,-18.98,66.0,M-MC,11.43,193.0,0.06,0.70,46.21,AR,ATH,AUTO
73,SURYODAY,1.27,-15.24,45.16,23.03,68542.0,-27295.0,151776.0,216.00,64.47,68.0,H-SC,3.44,166.0,-0.40,1.03,29.44,XR,NTT,BANKS
26,FINCABLES,2.47,23.75,68.01,107.91,124260.0,35064.0,182708.0,1641.55,11.11,71.0,M-SC,4.22,220.0,0.28,1.24,37.46,OX40N,ATH,CABLES
69,SIEMENS,3.25,3.24,21.57,25.51,41441.0,6030.0,192125.0,4671.50,61.28,76.0,H-LC,3.72,51.0,0.15,1.30,35.61,AR,ATH,ELECTRICAL
61,RECLTD,0.09,3.87,16.24,20.74,34272.0,7865.0,211035.0,446.00,15.23,71.0,M-MC,4.08,191.0,0.23,1.43,25.76,XY25,NTT,FINANCE

In [23]:
# top 5 RSP
df_tmp = df_portfolio_features.sort_values(by = 'RSP', ascending=False)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
59,RAJESHEXPO,4.99,-76.32,322.62,0.07,104790.0,-104696.0,32481.0,518.0,1090.66,58.0,L-SC,40.48,268.0,-1.00,0.22,52.49,OX40N,NTT,JEWELLERY
60,RAJOOENG,2.49,-34.18,112.09,39.61,75627.0,-35030.0,67470.0,143.1,-55.45,63.0,H-SC,27.46,136.0,-0.46,0.46,44.54,AR,ATH,MISC
51,KANSAINER,0.37,-30.91,64.25,13.47,119698.0,-83367.0,186300.0,340.0,-40.61,67.0,H-SC,19.26,162.0,-0.70,1.26,30.13,XY24,NTT,PAINTS
85,VBL,2.12,0.07,35.41,35.50,111919.0,223.0,316065.0,670.8,-11.61,73.0,X-LC,8.78,13.0,0.00,2.14,29.78,X40N,ATH,FMCG
69,SIEMENS,3.25,3.24,21.57,25.51,41441.0,6030.0,192125.0,4671.5,61.28,76.0,H-LC,3.72,51.0,0.15,1.30,35.61,AR,ATH,ELECTRICAL

In [24]:
# Top N allocation
df_tmp = df_portfolio_features.sort_values(by = 'CurrAlloc%', ascending=False)
top_n_values = [10, 25, 50]

sum_df = pd.DataFrame({
    'Top_N': top_n_values,
    'Sum_Alloc%': [df_tmp['CurrAlloc%'].head(n).sum() for n in top_n_values]
})

sum_df

   Top_N  Sum_Alloc%
0     10       20.05
1     25       44.35
2     50       75.14

In [25]:
# market-cap-wise allocation
df_tmp = df_portfolio_features[cols]
df_tmp.groupby(df_tmp['Conviction'].str[-2:])['CurrAlloc%'].sum().sort_values(ascending=False)

Conviction
SC    42.13
MC    29.28
LC    28.60
Name: CurrAlloc%, dtype: float64

In [26]:
# criteria-wise allocation
df_portfolio_features.groupby('Criteria')['CurrAlloc%'].sum().sort_values(ascending=False)

Criteria
XY24     26.85
X40      24.44
X40N     15.74
AR        9.34
XR        8.84
XY25      7.16
OX40N     6.85
SR        0.79
Name: CurrAlloc%, dtype: float64

In [27]:
# conviction-wise allocation
df_portfolio_features.groupby('Conviction')['CurrAlloc%'].sum().sort_values(ascending=False)

Conviction
X-LC    26.34
H-SC    21.77
X-MC    21.72
M-SC    10.01
X-SC     9.77
H-MC     5.09
M-MC     2.13
H-LC     1.30
M-LC     0.96
L-SC     0.58
L-MC     0.34
Name: CurrAlloc%, dtype: float64

In [28]:
# sector-wise stats
df_tmp = df_portfolio_features.groupby('Category')[['CurrAlloc%', 'Current', 'Current P/L', 'FTT Amt']].sum().sort_values(by=['Current', 'Current P/L'], ascending=False)
df_tmp['Current P/L%'] = round(df_tmp['Current P/L'] * 100 / df_tmp['Current'], 2)
df_tmp['FTT%'] = round(df_tmp['FTT Amt'] * 100 / df_tmp['Current'], 2)
cols = ['CurrAlloc%', 'Current P/L%', 'FTT%']
df_tmp[cols].sort_values(by=['CurrAlloc%'], ascending=False)

               CurrAlloc%  Current P/L%    FTT%
Category
FMCG                15.68        -13.39   53.47
IT                  10.99        -38.89  109.57
FINANCE             10.88        -14.80   64.72
MISC                 6.93        -31.29   88.32
ELECTRICAL           6.78          3.18   33.89
PAINTS               5.32        -25.48   47.27
AUTO                 5.32        -12.93   57.47
INSURANCE            5.17         -4.43   39.93
PHARMA               4.60         -4.52   38.08
BANKS                4.50        -16.15   75.11
AC                   2.04         -6.00   34.75
HEALTHCARE           1.89        -28.43   61.95
FOOTWEAR             1.80        -66.72  133.56
APPARELS             1.79         -1.51   36.14
TRAVEL               1.75        -73.26  160.01
DURABLES             1.74        -49.99   86.48
BREWERIES            1.63          2.56   17.68
REALTY               1.42         -5.78   23.15
CERAMICS             1.34        -55.14  102.27
CABLES               1.24         19.19   68.01
REFINERIES           1.19        -14.62   43.61
CEMENT               1.17        -54.88  170.74
ENGINEERING          1.15        -42.90  108.26
JEWELLERY            1.08       -100.79  170.55
CHEMICALS            1.05        -71.80  211.96
ENTERTAINMENT        0.76        -72.37  175.18
TEXTILES             0.44        -43.55   84.47
HOTELS               0.36       -115.05  190.91

In [29]:
# money to be made criteria-wise
df_portfolio_features.groupby('Criteria')['FTT Amt'].agg(['sum', 'count']).sort_values(by='sum', ascending=False)

                sum  count
Criteria
XY24      3636490.0     21
X40       1726640.0     17
XR        1327295.0     13
AR        1192791.0     10
X40N      1113767.0     12
OX40N      779436.0     10
XY25       383697.0      5
SR         303499.0      2

In [30]:
# money to be made conviction-wise
df_portfolio_features.groupby('Conviction')['FTT Amt'].agg(['sum', 'count']).sort_values(by='sum', ascending=False)

                  sum  count
Conviction
H-SC        3580644.0     24
X-LC        1701494.0     18
X-MC        1527868.0     15
M-SC        1441848.0     14
X-SC        1363469.0      9
H-MC         326174.0      3
L-SC         205590.0      2
M-LC         150443.0      1
M-MC          71624.0      2
L-MC          53020.0      1
H-LC          41441.0      1

In [31]:
# money to be made criteria and conviction-wise
df_portfolio_features.groupby(['Conviction', 'Criteria'])['FTT Amt'].agg(['sum', 'count']).sort_values(by='sum', ascending=False)

                           sum  count
Conviction Criteria
H-SC       XY24      1181628.0      6
           AR         944874.0      5
X-LC       X40        897303.0      8
M-SC       XY24       851277.0      6
H-SC       XR         814601.0      7
X-SC       XY24       804214.0      4
X-MC       X40        626757.0      7
           X40N       455601.0      4
X-SC       X40N       356675.0      3
X-LC       XY24       339268.0      2
M-SC       OX40N      338604.0      5
H-SC       OX40N      336042.0      4
           SR         303499.0      2
X-LC       X40N       301491.0      5
H-MC       XY24       231818.0      1
X-MC       XY24       228285.0      2
           XY25       217225.0      2
X-SC       X40        202580.0      2
M-SC       XR         177199.0      2
M-LC       XR         150443.0      1
X-LC       XY25       132200.0      2
L-SC       OX40N      104790.0      1
           XR         100800.0      1
H-MC       AR          94356.0      2
M-SC       AR          74768.0      1
L-MC       XR          53020.0      1
H-LC       AR          41441.0      1
M-MC       AR          37352.0      1
           XY25        34272.0      1
X-LC       XR          31232.0      1

In [32]:
# notebook execution time

end_time = time.time()
execution_time = round(end_time - start_time, 0)
print(f"Notebook execution time: {execution_time} seconds")

Notebook execution time: 31.0 seconds