<a href="https://colab.research.google.com/github/ankit-rathi/Quantvesting_v2/blob/main/myStocks_Portfolio_Analysis.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
'''
!pip install pandas==2.2.2 -qq
!pip install pyxirr -qq
!pip install ta -qq
!pip install yfinance==0.2.59 -qq
'''

'\n!pip install pandas==2.2.2 -qq\n!pip install pyxirr -qq\n!pip install ta -qq\n!pip install yfinance==0.2.59 -qq\n'

In [2]:
# import libraries

import numpy as np
import pandas as pd
import datetime
import warnings
warnings.filterwarnings('ignore')
import yfinance as yfin
import ta
import matplotlib.pyplot as plt
import requests

In [3]:
# notebook start time
import time
import datetime
import pytz

start_time = time.time()

# function to print date timestamp
def print_date_time():
  tz_NY = pytz.timezone('Asia/Kolkata')
  datetime_NY = datetime.datetime.now(tz_NY)
  print("Run date time (IST):", datetime_NY.strftime("%Y-%m-%d %H:%M:%S"))

In [4]:
# function to get booked and reserved amount
def get_amt():
  # fetch the JSON data from the URL
  url = "https://raw.githubusercontent.com/ankit-rathi/Tradevesting_v1/main/data/myPortfolioAmts.json"
  response = requests.get(url)
  pf_amts = response.json()  # parse the JSON data

  # extract values from the JSON
  py_booked_amt_dm = pf_amts["py_booked_amt_dm"]
  py_booked_amt_sv = pf_amts["py_booked_amt_sv"]
  cy_booked_amt_dm = pf_amts["cy_booked_amt_dm"]
  cy_booked_amt_sv = pf_amts["cy_booked_amt_sv"]
  reserve_amt_dm = pf_amts["reserve_amt_dm"]
  reserve_amt_sv = pf_amts["reserve_amt_sv"]

  # perform calculations
  py_booked_amt = py_booked_amt_dm + py_booked_amt_sv
  cy_booked_amt = cy_booked_amt_dm + cy_booked_amt_sv
  reserve_amt = reserve_amt_dm + reserve_amt_sv
  total_booked_amt = py_booked_amt + cy_booked_amt

  return total_booked_amt, reserve_amt, cy_booked_amt, py_booked_amt

gen_output = 0

In [5]:
# function to format the amount
def format_amt(number):
    abs_number = abs(number)

    if abs_number >= 1_00_00_000:  # Crores
        formatted_amt = f"{number / 1_00_00_000:.2f} C"
    elif abs_number >= 1_00_000:  # Lakhs
        formatted_amt = f"{number / 1_00_000:.2f} L"
    elif abs_number >= 1_000:  # Thousands
        formatted_amt = f"{number / 1_000:.2f} K"
    else:
        formatted_amt = f"{number:.2f}"

    return formatted_amt

# function to set start and end date
def get_start_end_date():
  start_date = (datetime.date.today() + datetime.timedelta(days=-365)).strftime('%Y-%m-%d')
  end_date = (datetime.date.today() + datetime.timedelta(days=1)).strftime('%Y-%m-%d')
  return start_date, end_date

# function to fetch my portfolio csv
def get_mypfs_df():
  mypfs_df = pd.read_csv('https://raw.githubusercontent.com/ankit-rathi/Tradevesting_v1/main/data/myPortfolioStocks.csv')
  return mypfs_df

# function to fetch my prospects csv
def get_mypps_df():
  mypps_df = pd.read_csv('https://raw.githubusercontent.com/ankit-rathi/Tradevesting_v1/main/data/myProspectsScrips.csv')
  return mypps_df

# function to fetch screener data
def get_myscreen_df():
  myscreen_df = pd.read_csv('https://raw.githubusercontent.com/ankit-rathi/Tradevesting_v1/main/data/myScreenerDB.csv')
  return myscreen_df

# function to fetch momentum data
def get_myinvmt_df():
  myinvmt_df = pd.read_csv('https://raw.githubusercontent.com/ankit-rathi/Tradevesting_v1/main/data/myInvestments.csv')
  return myinvmt_df

# function to get the stock ids
def get_stock_ids(df_pf):
  stock_n100 = df_pf['Symbol'].unique()

  exclude = ['CADILAHC','MMTC', 'MASFIN']

  stock_ids = df_pf[~df_pf['Symbol'].isin(exclude) ]['Symbol'].unique()

  #mypf = mypf[mypf.Forecast.notnull()]
  #stock_ids = mypf['Symbol'].unique()

  #stock_ids.sort()
  return stock_ids

# get features from screener data
def get_screener_features():
  myscreen_df = get_myscreen_df()
  cols = ['Symbol', 'EPS', 'MedPE', 'ROCE%', 'ROE%', 'CapType']
  return myscreen_df[cols]

# get relative strength
def get_relative_strength(stock_list):

    # Dictionary to store stock tickers and their corresponding percentage price change
    stock_changes = {}

    # Loop through each stock and fetch its price data
    for stock in stock_list:
        try:
            # Download the stock data for the given date range
            stock_data = yfin.Ticker(stock + '.NS').history(period='1mo', interval='1d')[map(str.title, ['open', 'close', 'low', 'high', 'volume'])]

            # Calculate the percentage change for the stock
            if len(stock_data) > 0:
                start_price = stock_data['Close'].iloc[0]
                end_price = stock_data['Close'].iloc[-1]
                percent_change = round(((end_price - start_price) / start_price) * 100, 2)
                stock_changes[stock] = percent_change
            else:
                stock_changes[stock] = np.nan  # If no data is available, set to NaN

        except Exception as e:
            print(f"Error fetching data for {stock}: {e}")
            stock_changes[stock] = np.nan

    # Create a DataFrame with stock tickers and their percentage changes
    df = pd.DataFrame(list(stock_changes.items()), columns=['Symbol', 'Percent_Change'])

    # Drop any stocks with missing data (NaN values)
    df = df.dropna()

    # Calculate the percentile rank based on percentage change
    df['RSP'] = round(df['Percent_Change'].rank(pct=True) * 100, 2)
    cols = ['Symbol', 'RSP']
    df = df[cols]
    # Sort by percentile rank (optional)
    df = df.sort_values(by='RSP', ascending=False).reset_index(drop=True)

    return df

In [6]:
# function to get stock technicals
def stock_prec_dev(stock_symbol):
    #stock_symbol = 'ULTRACEMCO.NS'
    short_window = 20
    mid_window = 50
    long_window = 200
    moving_avg = 'SMA'

    start = datetime.datetime(*map(int, start_date.split('-')))
    end = datetime.datetime(*map(int, end_date.split('-')))

    stock_df = yfin.Ticker(stock_symbol + '.NS').history(period='max', interval='1d')[map(str.title, ['open', 'close', 'low', 'high', 'volume'])]

    stock_df['Max'] = round(max(stock_df['Close']),2)
    stock_df = stock_df[(stock_df.index <= end_date) & (stock_df.index >= start_date)]
    stock_df['200_SMA'] = round(stock_df['Close'].rolling(window = 200, min_periods = 1).mean(),0)
    stock_df['Dev%_200'] = round((stock_df['Close'] - stock_df['200_SMA'])*100/stock_df['200_SMA'],2)
    stock_df.dropna(axis = 0, inplace = True) # remove any null rows

    stock_df['20_SMA'] = stock_df['Close'].rolling(window=20).mean()
    stock_df['50_SMA'] = stock_df['Close'].rolling(window=50).mean()
    stock_df['Symbol'] = stock_symbol

    stock_df['Close'] = round(stock_df['Close'],2)
    stock_df['Min'] = round(min(stock_df['Close']),2)
    stock_df['RSI_14'] = ta.momentum.RSIIndicator(close=stock_df['Close'], window=14).rsi()
    stock_df['RSI_14'] = round(stock_df['RSI_14'],0)
    stock_df['Prev_Close'] = stock_df['Close'].shift(1)
    stock_df.drop(['Open', 'Low', 'High', 'Volume'], axis=1, inplace=True)
    stock_df = stock_df.tail(1)

    max_SMA = max(stock_df['20_SMA'].item(), stock_df['50_SMA'].item(), stock_df['200_SMA'].item())
    min_SMA = min(stock_df['20_SMA'].item(), stock_df['50_SMA'].item(), stock_df['200_SMA'].item())
    ABS_Spread = max_SMA - min_SMA
    stock_df['Spread%'] = round((ABS_Spread / stock_df['200_SMA'].item()) * 100,2)

    return stock_df

# function to compute stock attributes
def get_common_features(stock_ids, df_mypf):

  df_prec_dev = pd.DataFrame()
  df_tmp = get_screener_features()
  df_rs = get_relative_strength(stock_ids)

  for stock_id in stock_ids:
      tmp = stock_prec_dev(stock_id)
      tmp = tmp.reset_index()
      df_prec_dev = pd.concat([df_prec_dev, tmp], ignore_index = True)
  df_prec_dev = pd.merge(df_prec_dev, df_mypf, on= 'Symbol')
  df_prec_dev = pd.merge(df_prec_dev, df_tmp, on= 'Symbol', how='left')
  df_prec_dev = pd.merge(df_prec_dev, df_rs, on= 'Symbol', how='left')
  #print(df_prec_dev.columns)
  df_prec_dev['Curr_PE'] = round(df_prec_dev['Close']/df_prec_dev['EPS'],1)
  df_prec_dev['Dev%_PE'] = round((df_prec_dev['Curr_PE'] - df_prec_dev['MedPE'])*100/df_prec_dev['MedPE'],2)
  df_prec_dev['Conviction'] = df_prec_dev['Conviction'] + '-' + df_prec_dev['CapType']
  return df_prec_dev

# function to arrange stock features
def arrange_features(df_stocks, common_cols, diff_cols):
  df_stocks_common = df_stocks[common_cols].drop_duplicates()
  df_stocks_diff = df_stocks[diff_cols]
  df_stocks_diff['Investment'] = df_stocks_diff['AvgCost'] * df_stocks_diff['Shares']
  df_stocks_diff = df_stocks_diff.groupby(['Symbol'])[['Shares', 'Investment']].aggregate(['sum']).reset_index()
  df_stocks_diff.columns = ['Symbol', 'Shares', 'Investment']
  df_stocks_diff['AvgCost'] = round(df_stocks_diff['Investment']/df_stocks_diff['Shares'],2)
  df_stocks = pd.merge(df_stocks_diff, df_stocks_common, on='Symbol')
  return df_stocks

# plot fact distribution across dimension
def plot_pie_chart(df, dimension, fact):
  # grouping the data by category and calculating the sum of fact for each type
  grouped_data = df.groupby(dimension)[fact].sum()

  # sorting the grouped data in descending order
  grouped_data = grouped_data.sort_values(ascending=False)

  # creating a pie chart
  grouped_data.plot.pie(autopct='%1.1f%%', startangle=90, figsize=(6, 6))

  # adding a title and displaying the plot
  plt.title(f'{dimension} {fact} Distribution')
  plt.ylabel('')  # To hide the y-label
  plt.show()

In [7]:
# function to get portfolio features

def get_portfolio_features(df_common_features):

  print_date_time()
  print('-------------------')

  #df_common_features["Target"] = df_common_features["Target"].fillna(df_common_features["Max"])
  df_common_features['NTT'] = np.where(df_common_features['Strategy']== 'NTT', df_common_features["Target"], df_common_features['Max'])
  df_common_features['LTT'] = np.where(df_common_features['Strategy']== 'BTT', df_common_features["Target"], df_common_features['Max'])
  df_common_features['BOL'] = df_common_features['Min']

  tmp_df = df_common_features[df_common_features['Symbol'].isin(mypf_df[mypf_df['InPortfolio'] != 'NA'].Symbol.values)]
  print('qualified stocks: '+str(len(tmp_df['Symbol'].unique())))
  tmp_df1 = tmp_df[tmp_df['LatestQtr'] == 1]
  print('with latest results: '+str(len(tmp_df1['Symbol'].unique())))
  tmp_df1 = tmp_df1[tmp_df1['StarStock'] == 1]
  print('still star stocks: '+str(len(tmp_df1['Symbol'].unique())))
  tmp_df['Investment'] = tmp_df['AvgCost'] * tmp_df['Shares']
  tmp_df['Current'] = round(tmp_df['Close'] * tmp_df['Shares'],0)
  tmp_df['Previous'] = tmp_df['Prev_Close'] * tmp_df['Shares']
  tmp_df['EstimatedST'] = tmp_df['NTT'] * tmp_df['Shares']
  tmp_df['EstimatedLT'] = tmp_df['LTT'] * tmp_df['Shares']
  tmp_df['Current P/L'] = round((tmp_df['Current'] - tmp_df['Investment']),0)
  tmp_df['Today P/L%'] = round((tmp_df['Current'] - tmp_df['Previous'])*100/tmp_df['Previous'],2)
  tmp_df['Current P/L%'] = round((tmp_df['Current'] - tmp_df['Investment'])*100/tmp_df['Investment'],2)
  tmp_df['EstimatedST P/L%'] = round((tmp_df['EstimatedST'] - tmp_df['Investment'])*100/tmp_df['Investment'],2)
  tmp_df['EstimatedLT P/L%'] = round((tmp_df['EstimatedLT'] - tmp_df['Investment'])*100/tmp_df['Investment'],2)
  tmp_df['NTT%'] = round((tmp_df['NTT'] - tmp_df['Close'])*100/tmp_df['Close'],2)
  tmp_df['LTT%'] = round((tmp_df['LTT'] - tmp_df['Close'])*100/tmp_df['Close'],2)
  tmp_df['Gained%'] = round((tmp_df['Close'] - tmp_df['BOL'])*100/tmp_df['BOL'],2)
  investment = round(sum(tmp_df['AvgCost']*tmp_df['Shares']),0)
  current = round(sum(tmp_df['Close']*tmp_df['Shares']),0)
  tmp_df['InitAlloc%'] = round(tmp_df['Investment']*100/investment,2)
  tmp_df['CurrAlloc%'] = round(tmp_df['Current']*100/current,2)
  tmp_df['FTT'] = tmp_df['LTT']
  tmp_df.loc[tmp_df['Strategy'] == 'NTT', 'FTT'] = tmp_df['NTT']
  tmp_df['FTT%'] = tmp_df['LTT%']
  tmp_df.loc[tmp_df['Strategy'] == 'NTT', 'FTT%'] = tmp_df['NTT%']
  tmp_df['FTT Amt'] = round(tmp_df['FTT%'] * tmp_df['Current']/100,0)
  tmp_df['OTT%'] = round((tmp_df['FTT'] - tmp_df['AvgCost'])*100/tmp_df['AvgCost'],2)
  tmp_df['RRR Ind'] = round(tmp_df['Current P/L']/tmp_df['FTT Amt'],2)
  tmp_df['Risk Ind'] = round(tmp_df['Current P/L%']*tmp_df['CurrAlloc%'],0)

  return tmp_df

# function to print portfolio features
def print_portfolio_stats(df_portfolio_features, myinvmt_df):
  from pyxirr import xirr

  total_booked_amt, reserve_amt, cy_booked_amt, py_booked_amt = get_amt()

  dates = myinvmt_df['Date'].values
  dates = np.append(dates, datetime.date.today().strftime('%d-%b-%y'))
  investment = myinvmt_df['Investment'].values
  dates= pd.to_datetime(dates)

  current = round(sum(df_portfolio_features['Close']*df_portfolio_features['Shares']),0) + reserve_amt
  investment_xirr = np.append(investment, current)
  cagr = round(xirr(pd.DataFrame({"dates": dates, "amounts": investment_xirr}))*100,2)

  investment = -sum(investment)
  invested = round(sum(df_portfolio_features['AvgCost']*df_portfolio_features['Shares']),0) + reserve_amt
  previous = round(sum(df_portfolio_features['Prev_Close']*df_portfolio_features['Shares']),0) + reserve_amt
  cy_invested = investment + py_booked_amt

  today_pnl_amount = current-previous
  today_pnl_percentage = round((current-previous)*100/previous,2)

  curr_pnl_amount = current-invested
  curr_pnl_percentage = round((curr_pnl_amount)*100/(cy_invested),2)

  cy_pnl_amount = cy_booked_amt + curr_pnl_amount
  cy_pnl_percentage = round((cy_pnl_amount)*100/cy_invested,2)

  overall_pnl_amount = total_booked_amt + curr_pnl_amount
  overall_pnl_percentage = round((overall_pnl_amount)*100/investment,2)

  estimate_st = round(sum(df_portfolio_features['FTT']*df_portfolio_features['Shares']),0)  + reserve_amt
  est_st_pnl_amount = estimate_st-current
  est_st_pnl_percentage = round((est_st_pnl_amount)*100/current,2)

  estimate_lt = round(sum(df_portfolio_features['LTT']*df_portfolio_features['Shares']),0)  + reserve_amt
  est_lt_pnl_amount = estimate_lt-current
  est_lt_pnl_percentage = round((est_lt_pnl_amount)*100/current,2)

  total_profit = round(sum(df_portfolio_features[df_portfolio_features['Current P/L%'] > 0]['Current']) - sum(df_portfolio_features[df_portfolio_features['Current P/L%'] > 0]['Investment']),0)
  total_loss = round(sum(df_portfolio_features[df_portfolio_features['Current P/L%'] < 0]['Current']) - sum(df_portfolio_features[df_portfolio_features['Current P/L%'] < 0]['Investment']),0)

  cy_booked_percentage = round((cy_booked_amt)*100/current,2)
  py_booked_percentage = round((py_booked_amt)*100/investment,2)
  total_booked_percentage = round((total_booked_amt)*100/investment,2)

  print('-------------------')
  print('Initial Investment: ', format_amt(investment))
  print('CY Investment: ', format_amt(cy_invested))
  print('Reserve: ', format_amt(reserve_amt))
  print('Current: ',  format_amt(current))
  print('-------------------')
  print('Today PnL: '+ '{} ({}%)'.format(format_amt(today_pnl_amount), today_pnl_percentage))
  print('Current PnL: '+ '{} ({}%)'.format(format_amt(curr_pnl_amount), curr_pnl_percentage))
  print('CY Booked + Current PnL: '+ '{} ({}%)'.format(format_amt(cy_pnl_amount), cy_pnl_percentage))
  print('-------------------')
  print('Total profit: ', format_amt(total_profit))
  print('Total loss: ', format_amt(total_loss))
  print('-------------------')
  print('Total Booked + Current PnL: '+ '{} ({}%)'.format(format_amt(overall_pnl_amount), overall_pnl_percentage))
  print('Total Booked PnL: '+ '{} ({}%)'.format(format_amt(total_booked_amt), total_booked_percentage))
  print('Curr Year Booked PnL: '+ '{} ({}%)'.format(format_amt(cy_booked_amt), cy_booked_percentage))
  print('Prev Year Booked PnL: '+ '{} ({}%)'.format(format_amt(py_booked_amt), py_booked_percentage))
  print('===================')
  print('Est FTT: ',  format_amt(estimate_st))
  print('Est FTT PnL: '+ '{} ({}%)'.format(format_amt(est_st_pnl_amount), est_st_pnl_percentage))

  print('===================')
  print('Deployed: ', format_amt(investment))

  print('Current: ', format_amt(current))

  print('CAGR/XIRR %: '+'{}%'.format(cagr))

In [8]:
# get start and end date
start_date, end_date = get_start_end_date()

# get portfolio and prospects data
mypfs_df = get_mypfs_df()
mypps_df = get_mypps_df()
myinvmt_df = get_myinvmt_df()

# merge above datasets
mypf_df = pd.merge(mypfs_df, mypps_df, on="Symbol")

# seggregate dm and sv portfolio
dm_pf = mypf_df[mypf_df['InPortfolio'] == 'DM']
sv_pf = mypf_df[mypf_df['InPortfolio'] == 'SV']

# build portfolio stock dataframe
dm_stocks = get_stock_ids(dm_pf)
sv_stocks = get_stock_ids(sv_pf)
df_stocks = pd.concat([dm_pf,sv_pf], ignore_index = True)

# arrange common and diff stock features
common_cols = ['Symbol', 'Target', 'Criteria', 'Strategy', 'CumlRnk', 'LatestQtr', 'StarStock', 'Conviction', 'Category', 'InFolio', 'XIRR', 'MBQ']
diff_cols = ['Symbol', 'AvgCost', 'Shares']
df_stocks = arrange_features(df_stocks, common_cols, diff_cols)

# get common features
stock_ids = df_stocks['Symbol'].values
df_common_features = get_common_features(stock_ids, df_stocks)

df_common_features.reset_index(drop=True, inplace=True)
df_common_features.drop(['Date'], axis=1, inplace=True)
# get and print portfolio features
df_portfolio_features = get_portfolio_features(df_common_features)

print_portfolio_stats(df_portfolio_features, myinvmt_df)

df = df_portfolio_features
#plot_pie_chart(df, 'CapType', 'Current')
list_ox40n = list(df[df['MBQ'].str.contains('OX40N', na=False)]['Symbol'].values)

Run date time (IST): 2026-03-11 10:47:58
-------------------
qualified stocks: 86
with latest results: 26
still star stocks: 15
-------------------
Initial Investment:  1.36 C
CY Investment:  1.62 C
Reserve:  66.25 K
Current:  1.38 C
-------------------
Today PnL: 45.14 K (0.33%)
Current PnL: -39.21 L (-24.13%)
CY Booked + Current PnL: -23.53 L (-14.48%)
-------------------
Total profit:  1.15 L
Total loss:  -40.36 L
-------------------
Total Booked + Current PnL: 3.45 L (2.55%)
Total Booked PnL: 42.66 L (31.48%)
Curr Year Booked PnL: 15.68 L (11.39%)
Prev Year Booked PnL: 26.98 L (19.91%)
===================
Est FTT:  2.47 C
Est FTT PnL: 1.10 C (79.56%)
===================
Deployed:  1.36 C
Current:  1.38 C
CAGR/XIRR %: 0.82%

In [9]:
# top 5 near their targets
cols = ['Symbol', 'Today P/L%', 'Current P/L%', 'FTT%', 'OTT%', 'FTT Amt', 'Current P/L', 'Current', 'FTT', 'Dev%_PE', 'RSI_14','Conviction', 'Spread%',  'CumlRnk', 'RRR Ind', 'CurrAlloc%', 'Gained%', 'Criteria', 'Strategy', 'Category']
df_tmp = df_portfolio_features[~df_portfolio_features['Symbol'].isin(['ENRIN','BLUSPRING','DIGITIDE'])]
df_tmp = df_tmp.sort_values(by = 'FTT Amt', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
19,COALINDIA,1.12,10.29,6.69,17.67,11102.0,15484.0,165945.0,478.51,33.43,62.0,L-LC,11.54,185.0,1.39,1.21,28.87,XY25,ATH,MINING
50,MASFIN,0.11,-5.17,28.20,21.57,26201.0,-5070.0,92910.0,397.04,-18.25,42.0,H-SC,4.68,167.0,-0.19,0.68,29.64,XR,ATH,FINANCE
77,TTKPRESTIG,8.23,-31.84,46.85,0.09,32181.0,-32087.0,68690.0,770.00,59.45,48.0,M-SC,15.25,250.0,-1.00,0.50,16.06,OX40N,NTT,DURABLES
37,ICICIGI,-0.76,-0.68,20.16,19.34,40068.0,-1359.0,198750.0,2252.93,-16.40,45.0,X-MC,1.67,66.0,-0.03,1.45,13.35,X40,ATH,INSURANCE
78,UNITDSPR,-0.70,2.64,17.66,20.77,42443.0,6192.0,240336.0,1644.00,-8.94,53.0,X-MC,1.53,64.0,0.15,1.75,9.53,X40N,NTT,BREWERIES

In [10]:
# top 5 today
df_tmp = df_portfolio_features.sort_values(by = 'Today P/L%', ascending=False)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
31,HAPPSTMNDS,9.60,-45.21,237.37,84.85,166691.0,-57941.0,70224.0,1480.71,-34.91,69.0,H-SC,28.39,152.0,-0.35,0.51,30.04,AR,ATH,IT
77,TTKPRESTIG,8.23,-31.84,46.85,0.09,32181.0,-32087.0,68690.0,770.00,59.45,48.0,M-SC,15.25,250.0,-1.00,0.50,16.06,OX40N,NTT,DURABLES
55,RAJESHEXPO,4.99,-77.85,351.85,0.07,106892.0,-106797.0,30380.0,518.00,1013.64,23.0,L-SC,18.85,268.0,-1.00,0.22,4.99,OX40N,NTT,JEWELLERY
70,SYMPHONY,4.82,-36.38,57.13,-0.03,62204.0,-62260.0,108881.0,1306.00,-48.93,49.0,M-SC,13.18,205.0,-1.00,0.79,10.11,OX40N,NTT,DURABLES
64,SHALBY,3.10,-42.40,117.20,25.10,122276.0,-76812.0,104331.0,327.00,667.15,41.0,M-SC,22.82,236.0,-0.63,0.76,4.78,XY24,NTT,HEALTHCARE

In [11]:
# bottom 5 today
df_tmp = df_portfolio_features.sort_values(by = 'Today P/L%', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
21,COLPAL,-4.14,-19.99,76.85,41.51,161946.0,-52635.0,210730.0,3726.84,-3.16,41.0,X-MC,4.14,62.0,-0.33,1.54,2.97,XY25,ATH,FMCG
27,FINCABLES,-2.45,14.78,81.15,107.91,137516.0,21815.0,169459.0,1641.55,3.50,59.0,M-SC,7.73,220.0,0.16,1.24,27.49,OX40N,ATH,CABLES
24,DIXON,-2.42,-22.45,77.86,37.92,157461.0,-58562.0,202236.0,18931.72,-67.00,48.0,X-MC,25.61,54.0,-0.37,1.48,8.57,X40N,ATH,IT
22,DABUR,-0.98,-6.90,54.35,43.70,125525.0,-17111.0,230957.0,735.00,-15.59,36.0,X-MC,1.01,70.0,-0.14,1.69,7.11,XY24,BTT,FMCG
41,INDIGOPNTS,-0.97,-40.94,69.34,0.02,71490.0,-71459.0,103100.0,1408.00,57.37,15.0,M-SC,16.58,222.0,-1.00,0.75,0.00,OX40N,NTT,PAINTS

In [12]:
# top 5 to exit based on CumlRnk
df_tmp = df_portfolio_features[~df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])]
df_tmp = df_tmp[(df_tmp['Current P/L%'] > -1) & (df_tmp['Current P/L%'] < 1)].sort_values(by = 'CumlRnk', ascending=False)
df_tmp[cols].head()

Empty DataFrame
Columns: [Symbol, Today P/L%, Current P/L%, FTT%, OTT%, FTT Amt, Current P/L, Current, FTT, Dev%_PE, RSI_14, Conviction, Spread%, CumlRnk, RRR Ind, CurrAlloc%, Gained%, Criteria, Strategy, Category]
Index: []

In [13]:
# OX40N stocks to exit
df_tmp = df_portfolio_features[(df_portfolio_features['Symbol'].isin(list_ox40n))].sort_values(by = 'Current P/L%', ascending=False)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
27,FINCABLES,-2.45,14.78,81.15,107.91,137516.0,21815.0,169459.0,1641.55,3.50,59.0,M-SC,7.73,220.0,0.16,1.24,27.49,OX40N,ATH,CABLES
77,TTKPRESTIG,8.23,-31.84,46.85,0.09,32181.0,-32087.0,68690.0,770.00,59.45,48.0,M-SC,15.25,250.0,-1.00,0.50,16.06,OX40N,NTT,DURABLES
66,SIS,1.27,-32.48,79.59,21.26,59669.0,-36062.0,74970.0,528.00,1757.51,39.0,H-SC,9.98,168.0,-0.60,0.55,3.35,OX40N,NTT,MISC
70,SYMPHONY,4.82,-36.38,57.13,-0.03,62204.0,-62260.0,108881.0,1306.00,-48.93,49.0,M-SC,13.18,205.0,-1.00,0.79,10.11,OX40N,NTT,DURABLES
72,TATAELXSI,0.24,-37.06,109.78,32.03,91088.0,-48862.0,82973.0,9161.00,-21.20,30.0,H-SC,16.56,158.0,-0.54,0.61,1.47,OX40N,NTT,IT

In [14]:
# top 5 to book for rotation
df_tmp = df_portfolio_features[(df_portfolio_features['Current P/L%'] > 20) ].sort_values(by = 'CumlRnk', ascending=False)
df_tmp[cols].head()

Empty DataFrame
Columns: [Symbol, Today P/L%, Current P/L%, FTT%, OTT%, FTT Amt, Current P/L, Current, FTT, Dev%_PE, RSI_14, Conviction, Spread%, CumlRnk, RRR Ind, CurrAlloc%, Gained%, Criteria, Strategy, Category]
Index: []

In [15]:
# top 5 to monitor for exit
df_tmp = df_portfolio_features[~df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])]
df_tmp = df_tmp[(df_tmp['Current P/L%'] > 0) ].sort_values(by = 'Dev%_PE', ascending=False)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
19,COALINDIA,1.12,10.29,6.69,17.67,11102.0,15484.0,165945.0,478.51,33.43,62.0,L-LC,11.54,185.0,1.39,1.21,28.87,XY25,ATH,MINING
27,FINCABLES,-2.45,14.78,81.15,107.91,137516.0,21815.0,169459.0,1641.55,3.50,59.0,M-SC,7.73,220.0,0.16,1.24,27.49,OX40N,ATH,CABLES
1,ABB,0.82,15.14,26.43,45.57,79614.0,39605.0,301224.0,7934.00,-26.00,66.0,H-MC,10.07,125.0,0.50,2.20,33.76,AR,NTT,ELECTRICAL

In [16]:
# top 5 to book for rotation from weak conviction
df_tmp = df_portfolio_features[~df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])]
df_tmp = df_tmp[~df_tmp['Criteria'].isin(['XY25','XY24','X40', 'X40N'])].sort_values(by = 'RRR Ind', ascending=False)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
1,ABB,0.82,15.14,26.43,45.57,79614.0,39605.0,301224.0,7934.00,-26.00,66.0,H-MC,10.07,125.0,0.50,2.20,33.76,AR,NTT,ELECTRICAL
27,FINCABLES,-2.45,14.78,81.15,107.91,137516.0,21815.0,169459.0,1641.55,3.50,59.0,M-SC,7.73,220.0,0.16,1.24,27.49,OX40N,ATH,CABLES
85,ZYDUSLIFE,1.10,-1.59,37.82,35.63,78003.0,-3326.0,206248.0,1286.17,-14.41,58.0,H-MC,5.02,120.0,-0.04,1.50,14.82,AR,ATH,PHARMA
40,INDIAMART,-0.33,-6.64,121.43,106.72,139817.0,-8194.0,115142.0,4810.62,-57.81,49.0,H-SC,9.11,140.0,-0.06,0.84,15.18,AR,ATH,MISC
67,SONACOMS,2.27,-9.46,53.63,39.09,49118.0,-9573.0,91586.0,804.02,-28.30,53.0,M-MC,10.20,193.0,-0.19,0.67,29.56,AR,ATH,AUTO

In [17]:
# top 5 to accumulate based on lowest RSI_14
df_tmp = df_portfolio_features[df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])].sort_values(by = 'RSI_14', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
58,RELAXO,-0.11,-60.16,282.31,52.31,163257.0,-87331.0,57829.0,1176.00,-57.60,20.0,X-SC,18.70,92.0,-0.53,0.42,0.00,X40N,NTT,FOOTWEAR
12,BATAINDIA,0.35,-53.59,191.35,35.20,114255.0,-68960.0,59710.0,2096.00,-21.73,22.0,X-SC,25.48,91.0,-0.60,0.44,0.35,X40,NTT,FOOTWEAR
8,AWL,0.16,-38.26,170.51,67.02,375103.0,-136320.0,219989.0,485.00,-66.76,22.0,X-SC,22.72,81.0,-0.36,1.61,2.10,XY24,NTT,FMCG
3,ACC,-0.08,-34.09,165.21,74.81,291986.0,-91392.0,176736.0,3906.00,-53.43,24.0,X-SC,12.18,85.0,-0.31,1.29,1.54,XY24,BTT,CEMENT
53,PGHH,-0.95,-19.78,64.57,32.01,110595.0,-42240.0,171280.0,17616.87,-45.79,24.0,X-MC,11.31,57.0,-0.38,1.25,0.95,X40,ATH,FMCG

In [18]:
# top 5 to accumulate based on Spread and CumlRnk
df_tmp = df_portfolio_features[df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])]
df_tmp = df_tmp[(df_tmp['CumlRnk'] < 100)].sort_values(by = 'Spread%', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
22,DABUR,-0.98,-6.90,54.35,43.70,125525.0,-17111.0,230957.0,735.00,-15.59,36.0,X-MC,1.01,70.0,-0.14,1.69,7.11,XY24,BTT,FMCG
78,UNITDSPR,-0.70,2.64,17.66,20.77,42443.0,6192.0,240336.0,1644.00,-8.94,53.0,X-MC,1.53,64.0,0.15,1.75,9.53,X40N,NTT,BREWERIES
37,ICICIGI,-0.76,-0.68,20.16,19.34,40068.0,-1359.0,198750.0,2252.93,-16.40,45.0,X-MC,1.67,66.0,-0.03,1.45,13.35,X40,ATH,INSURANCE
75,TMPV,-0.94,-22.16,75.46,36.58,209009.0,-78861.0,276980.0,600.00,-83.62,38.0,X-LC,1.91,4.0,-0.38,2.02,3.00,XY24,NTT,AUTO
59,RELIANCE,-0.49,-10.01,39.24,25.30,70964.0,-20118.0,180845.0,1952.00,-12.34,47.0,X-LC,2.43,21.0,-0.28,1.32,20.74,XY25,BTT,REFINERIES

In [19]:
# top 5 to accumulate based on lowest Gained%
df_tmp = df_portfolio_features[df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])].sort_values(by = 'Gained%', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
58,RELAXO,-0.11,-60.16,282.31,52.31,163257.0,-87331.0,57829.0,1176.00,-57.60,20.0,X-SC,18.70,92.0,-0.53,0.42,0.00,X40N,NTT,FOOTWEAR
73,TCS,-0.57,-26.22,71.56,26.57,244579.0,-121491.0,341782.0,4311.59,-37.40,24.0,X-LC,13.09,2.0,-0.50,2.49,0.00,X40,ATH,IT
13,BERGEPAINT,-0.52,-19.94,56.52,25.32,116637.0,-51385.0,206364.0,680.00,-24.23,30.0,X-MC,15.46,68.0,-0.44,1.51,0.06,XY24,NTT,PAINTS
10,BAJAJHLDNG,-0.24,-8.22,40.80,29.22,71191.0,-15637.0,174488.0,14451.52,-15.20,32.0,X-LC,11.98,28.0,-0.22,1.27,0.14,X40,ATH,FINANCE
12,BATAINDIA,0.35,-53.59,191.35,35.20,114255.0,-68960.0,59710.0,2096.00,-21.73,22.0,X-SC,25.48,91.0,-0.60,0.44,0.35,X40,NTT,FOOTWEAR

In [20]:
# top 5 to accumulate based on lowest CurrAlloc%
df_tmp = df_portfolio_features[df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])].sort_values(by = 'CurrAlloc%', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
58,RELAXO,-0.11,-60.16,282.31,52.31,163257.0,-87331.0,57829.0,1176.00,-57.60,20.0,X-SC,18.70,92.0,-0.53,0.42,0.00,X40N,NTT,FOOTWEAR
12,BATAINDIA,0.35,-53.59,191.35,35.20,114255.0,-68960.0,59710.0,2096.00,-21.73,22.0,X-SC,25.48,91.0,-0.60,0.44,0.35,X40,NTT,FOOTWEAR
54,QUESS,2.71,-20.23,117.99,73.90,100517.0,-21602.0,85191.0,424.00,-57.02,46.0,X-SC,17.90,80.0,-0.21,0.62,5.09,XY24,NTT,MISC
36,HONAUT,0.41,-19.91,88.92,51.31,137337.0,-38388.0,154450.0,58357.33,-33.36,46.0,X-SC,13.61,90.0,-0.28,1.13,4.01,X40N,ATH,ELECTRICAL
2,ABBOTINDIA,0.06,-10.01,31.20,18.07,50216.0,-17905.0,160950.0,35195.00,-23.42,47.0,X-MC,11.17,58.0,-0.36,1.17,2.03,X40,ATH,PHARMA

In [21]:
# top 5 to accumulate based on CumlRnk
df_tmp = df_portfolio_features.sort_values(by = 'CumlRnk', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
45,ITC,-0.06,-18.65,46.35,19.06,128264.0,-63436.0,276730.0,452.00,-55.52,38.0,X-LC,17.09,1.0,-0.49,2.02,0.93,X40,NTT,FMCG
73,TCS,-0.57,-26.22,71.56,26.57,244579.0,-121491.0,341782.0,4311.59,-37.40,24.0,X-LC,13.09,2.0,-0.50,2.49,0.00,X40,ATH,IT
43,INFY,-0.90,-12.59,53.58,34.24,146537.0,-39396.0,273492.0,1972.00,-31.06,27.0,X-LC,12.10,3.0,-0.27,2.00,0.67,X40,NTT,IT
75,TMPV,-0.94,-22.16,75.46,36.58,209009.0,-78861.0,276980.0,600.00,-83.62,38.0,X-LC,1.91,4.0,-0.38,2.02,3.00,XY24,NTT,AUTO
34,HCLTECH,-0.46,-12.05,40.81,23.83,86830.0,-29158.0,212766.0,1908.19,-7.78,28.0,X-LC,9.48,8.0,-0.34,1.55,2.08,X40,ATH,IT

In [22]:
# top 5 for average up
df_tmp = df_portfolio_features[(df_portfolio_features['Dev%_200'] > 5)].sort_values(by = 'CurrAlloc%', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
42,INDUSINDBK,-0.80,-34.18,101.91,32.89,51787.0,-26390.0,50816.0,1800.00,-339.50,41.0,L-MC,11.37,258.0,-0.51,0.37,39.94,XR,NTT,BANKS
67,SONACOMS,2.27,-9.46,53.63,39.09,49118.0,-9573.0,91586.0,804.02,-28.30,53.0,M-MC,10.20,193.0,-0.19,0.67,29.56,AR,ATH,AUTO
19,COALINDIA,1.12,10.29,6.69,17.67,11102.0,15484.0,165945.0,478.51,33.43,62.0,L-LC,11.54,185.0,1.39,1.21,28.87,XY25,ATH,MINING
27,FINCABLES,-2.45,14.78,81.15,107.91,137516.0,21815.0,169459.0,1641.55,3.50,59.0,M-SC,7.73,220.0,0.16,1.24,27.49,OX40N,ATH,CABLES
82,VOLTAS,2.49,16.17,24.98,45.20,55643.0,31008.0,222750.0,1856.00,32.93,51.0,X-MC,9.69,79.0,0.56,1.63,24.07,XY25,NTT,AC

In [23]:
# top 5 RSP
df_tmp = df_portfolio_features.sort_values(by = 'RSP', ascending=False)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
31,HAPPSTMNDS,9.60,-45.21,237.37,84.85,166691.0,-57941.0,70224.0,1480.71,-34.91,69.0,H-SC,28.39,152.0,-0.35,0.51,30.04,AR,ATH,IT
27,FINCABLES,-2.45,14.78,81.15,107.91,137516.0,21815.0,169459.0,1641.55,3.50,59.0,M-SC,7.73,220.0,0.16,1.24,27.49,OX40N,ATH,CABLES
1,ABB,0.82,15.14,26.43,45.57,79614.0,39605.0,301224.0,7934.00,-26.00,66.0,H-MC,10.07,125.0,0.50,2.20,33.76,AR,NTT,ELECTRICAL
11,BANDHANBNK,-0.59,-12.84,120.77,92.42,293207.0,-35778.0,242781.0,400.00,108.33,60.0,H-SC,10.00,174.0,-0.12,1.77,33.74,XY24,NTT,BANKS
26,EASEMYTRIP,1.50,-58.83,253.89,45.70,184819.0,-104020.0,72795.0,26.40,-24.39,45.0,M-SC,18.16,204.0,-0.56,0.53,19.94,XY24,NTT,TRAVEL

In [24]:
# Top N allocation
df_tmp = df_portfolio_features.sort_values(by = 'CurrAlloc%', ascending=False)
top_n_values = [10, 25, 50]

sum_df = pd.DataFrame({
    'Top_N': top_n_values,
    'Sum_Alloc%': [df_tmp['CurrAlloc%'].head(n).sum() for n in top_n_values]
})

sum_df

   Top_N  Sum_Alloc%
0     10       20.48
1     25       45.32
2     50       77.70

In [25]:
# market-cap-wise allocation
df_tmp = df_portfolio_features[cols]
df_tmp.groupby(df_tmp['Conviction'].str[-2:])['CurrAlloc%'].sum().sort_values(ascending=False)

Conviction
SC    44.70
MC    30.41
LC    24.89
Name: CurrAlloc%, dtype: float64

In [26]:
# criteria-wise allocation
df_portfolio_features.groupby('Criteria')['CurrAlloc%'].sum().sort_values(ascending=False)

Criteria
XY24     27.24
X40      23.71
X40N     15.17
AR        9.24
XY25      8.64
XR        8.29
OX40N     6.93
SR        0.78
Name: CurrAlloc%, dtype: float64

In [27]:
# conviction-wise allocation
df_portfolio_features.groupby('Conviction')['CurrAlloc%'].sum().sort_values(ascending=False)

Conviction
X-MC    23.02
H-SC    21.71
X-LC    21.45
X-SC    12.19
M-SC    10.21
H-MC     4.99
M-MC     2.03
H-LC     1.21
L-LC     1.21
M-LC     1.02
L-SC     0.59
L-MC     0.37
Name: CurrAlloc%, dtype: float64

In [28]:
# sector-wise stats
df_tmp = df_portfolio_features.groupby('Category')[['CurrAlloc%', 'Current', 'Current P/L', 'FTT Amt']].sum().sort_values(by=['Current', 'Current P/L'], ascending=False)
df_tmp['Current P/L%'] = round(df_tmp['Current P/L'] * 100 / df_tmp['Current'], 2)
df_tmp['FTT%'] = round(df_tmp['FTT Amt'] * 100 / df_tmp['Current'], 2)
cols = ['CurrAlloc%', 'Current P/L%', 'FTT%']
df_tmp[cols].sort_values(by=['CurrAlloc%'], ascending=False)

               CurrAlloc%  Current P/L%    FTT%
Category
FMCG                15.22        -19.82   62.36
FINANCE             12.84        -22.16   71.94
IT                  11.73        -40.13  111.44
MISC                 7.01        -39.77  100.49
ELECTRICAL           6.64         -6.53   47.32
PAINTS               5.18        -38.87   62.99
INSURANCE            4.68         -5.74   41.92
PHARMA               4.13         -3.58   36.19
AUTO                 3.76        -27.02   77.42
BANKS                3.14        -24.02   99.17
AC                   2.18         -7.26   36.34
HEALTHCARE           1.99        -31.15   65.37
DURABLES             1.89        -48.74   84.93
FOOTWEAR             1.84        -75.09  145.29
TRAVEL               1.82        -79.06  168.72
BREWERIES            1.75          2.58   17.66
APPARELS             1.61        -21.48   62.92
REALTY               1.45        -11.52   29.84
CERAMICS             1.34        -67.37  118.22
REFINERIES           1.32        -11.12   39.24
CEMENT               1.29        -51.71  165.21
CABLES               1.24         12.87   81.15
MINING               1.21          9.33    6.69
JEWELLERY            1.12       -107.23  179.24
ENGINEERING          1.10        -60.21  133.48
CHEMICALS            0.97        -99.15  261.63
ENTERTAINMENT        0.76        -84.76  194.95
TEXTILES             0.42        -60.51  106.27
HOTELS               0.37       -121.91  200.19

In [29]:
# money to be made criteria-wise
df_portfolio_features.groupby('Criteria')['FTT Amt'].agg(['sum', 'count']).sort_values(by='sum', ascending=False)

                sum  count
Criteria
XY24      3865390.0     21
X40       1622637.0     15
XR        1352213.0     12
AR        1305363.0     10
X40N      1221274.0     10
OX40N      843062.0     10
XY25       434263.0      6
SR         312481.0      2

In [30]:
# money to be made conviction-wise
df_portfolio_features.groupby('Conviction')['FTT Amt'].agg(['sum', 'count']).sort_values(by='sum', ascending=False)

                  sum  count
Conviction
H-SC        3816285.0     24
X-MC        1580233.0     15
X-LC        1533690.0     12
M-SC        1518556.0     14
X-SC        1512914.0     10
H-MC         394290.0      3
L-SC         209325.0      2
M-LC         151483.0      1
M-MC         108712.0      2
H-LC          68306.0      1
L-MC          51787.0      1
L-LC          11102.0      1

In [31]:
# money to be made criteria and conviction-wise
df_portfolio_features.groupby(['Conviction', 'Criteria'])['FTT Amt'].agg(['sum', 'count']).sort_values(by='sum', ascending=False)

                           sum  count
Conviction Criteria
H-SC       XY24      1310705.0      6
           AR         953922.0      5
M-SC       XY24       898653.0      6
H-SC       XR         859009.0      7
X-SC       XY24       823609.0      4
X-LC       X40        797749.0      6
X-MC       X40        623450.0      7
           X40N       497032.0      4
X-SC       X40N       487867.0      4
H-SC       OX40N      380168.0      4
M-SC       OX40N      356002.0      5
X-LC       XY24       353588.0      2
H-SC       SR         312481.0      2
X-MC       XY24       242162.0      2
H-MC       XY24       236673.0      1
X-LC       X40N       236375.0      2
X-MC       XY25       217589.0      2
X-SC       X40        201438.0      2
M-SC       XR         187501.0      2
H-MC       AR         157617.0      2
M-LC       XR         151483.0      1
X-LC       XY25       145978.0      2
L-SC       OX40N      106892.0      1
           XR         102433.0      1
M-SC       AR          76400.0      1
H-LC       AR          68306.0      1
M-MC       XY25        59594.0      1
L-MC       XR          51787.0      1
M-MC       AR          49118.0      1
L-LC       XY25        11102.0      1

In [32]:
# notebook execution time

end_time = time.time()
execution_time = round(end_time - start_time, 0)
print(f"Notebook execution time: {execution_time} seconds")

Notebook execution time: 25.0 seconds