<a href="https://colab.research.google.com/github/ankit-rathi/Quantvesting_v2/blob/main/myStocks_Portfolio_Analysis.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
'''
!pip install pandas==2.2.2 -qq
!pip install pyxirr -qq
!pip install ta -qq
!pip install yfinance==0.2.59 -qq
'''

'\n!pip install pandas==2.2.2 -qq\n!pip install pyxirr -qq\n!pip install ta -qq\n!pip install yfinance==0.2.59 -qq\n'

In [2]:
# import libraries

import numpy as np
import pandas as pd
import datetime
import warnings
warnings.filterwarnings('ignore')
import yfinance as yfin
import ta
import matplotlib.pyplot as plt
import requests

In [3]:
# notebook start time
import time
import datetime
import pytz

start_time = time.time()

# function to print date timestamp
def print_date_time():
  tz_NY = pytz.timezone('Asia/Kolkata')
  datetime_NY = datetime.datetime.now(tz_NY)
  print("Run date time (IST):", datetime_NY.strftime("%Y-%m-%d %H:%M:%S"))

In [4]:
# function to get booked and reserved amount
def get_amt():
  # fetch the JSON data from the URL
  url = "https://raw.githubusercontent.com/ankit-rathi/Tradevesting_v1/main/data/myPortfolioAmts.json"
  response = requests.get(url)
  pf_amts = response.json()  # parse the JSON data

  # extract values from the JSON
  py_booked_amt_dm = pf_amts["py_booked_amt_dm"]
  py_booked_amt_sv = pf_amts["py_booked_amt_sv"]
  cy_booked_amt_dm = pf_amts["cy_booked_amt_dm"]
  cy_booked_amt_sv = pf_amts["cy_booked_amt_sv"]
  reserve_amt_dm = pf_amts["reserve_amt_dm"]
  reserve_amt_sv = pf_amts["reserve_amt_sv"]

  # perform calculations
  py_booked_amt = py_booked_amt_dm + py_booked_amt_sv
  cy_booked_amt = cy_booked_amt_dm + cy_booked_amt_sv
  reserve_amt = reserve_amt_dm + reserve_amt_sv
  total_booked_amt = py_booked_amt + cy_booked_amt

  return total_booked_amt, reserve_amt, cy_booked_amt, py_booked_amt

gen_output = 0

In [5]:
# function to format the amount
def format_amt(number):
    abs_number = abs(number)

    if abs_number >= 1_00_00_000:  # Crores
        formatted_amt = f"{number / 1_00_00_000:.2f} C"
    elif abs_number >= 1_00_000:  # Lakhs
        formatted_amt = f"{number / 1_00_000:.2f} L"
    elif abs_number >= 1_000:  # Thousands
        formatted_amt = f"{number / 1_000:.2f} K"
    else:
        formatted_amt = f"{number:.2f}"

    return formatted_amt

# function to set start and end date
def get_start_end_date():
  start_date = (datetime.date.today() + datetime.timedelta(days=-365)).strftime('%Y-%m-%d')
  end_date = (datetime.date.today() + datetime.timedelta(days=1)).strftime('%Y-%m-%d')
  return start_date, end_date

# function to fetch my portfolio csv
def get_mypfs_df():
  mypfs_df = pd.read_csv('https://raw.githubusercontent.com/ankit-rathi/Tradevesting_v1/main/data/myPortfolioStocks.csv')
  return mypfs_df

# function to fetch my prospects csv
def get_mypps_df():
  mypps_df = pd.read_csv('https://raw.githubusercontent.com/ankit-rathi/Tradevesting_v1/main/data/myProspectsScrips.csv')
  return mypps_df

# function to fetch screener data
def get_myscreen_df():
  myscreen_df = pd.read_csv('https://raw.githubusercontent.com/ankit-rathi/Tradevesting_v1/main/data/myScreenerDB.csv')
  return myscreen_df

# function to fetch momentum data
def get_myinvmt_df():
  myinvmt_df = pd.read_csv('https://raw.githubusercontent.com/ankit-rathi/Tradevesting_v1/main/data/myInvestments.csv')
  return myinvmt_df

# function to get the stock ids
def get_stock_ids(df_pf):
  stock_n100 = df_pf['Symbol'].unique()

  exclude = ['CADILAHC','MMTC', 'MASFIN']

  stock_ids = df_pf[~df_pf['Symbol'].isin(exclude) ]['Symbol'].unique()

  #mypf = mypf[mypf.Forecast.notnull()]
  #stock_ids = mypf['Symbol'].unique()

  #stock_ids.sort()
  return stock_ids

# get features from screener data
def get_screener_features():
  myscreen_df = get_myscreen_df()
  cols = ['Symbol', 'EPS', 'MedPE', 'ROCE%', 'ROE%', 'CapType']
  return myscreen_df[cols]

# get relative strength
def get_relative_strength(stock_list):

    # Dictionary to store stock tickers and their corresponding percentage price change
    stock_changes = {}

    # Loop through each stock and fetch its price data
    for stock in stock_list:
        try:
            # Download the stock data for the given date range
            stock_data = yfin.Ticker(stock + '.NS').history(period='1mo', interval='1d')[map(str.title, ['open', 'close', 'low', 'high', 'volume'])]

            # Calculate the percentage change for the stock
            if len(stock_data) > 0:
                start_price = stock_data['Close'].iloc[0]
                end_price = stock_data['Close'].iloc[-1]
                percent_change = round(((end_price - start_price) / start_price) * 100, 2)
                stock_changes[stock] = percent_change
            else:
                stock_changes[stock] = np.nan  # If no data is available, set to NaN

        except Exception as e:
            print(f"Error fetching data for {stock}: {e}")
            stock_changes[stock] = np.nan

    # Create a DataFrame with stock tickers and their percentage changes
    df = pd.DataFrame(list(stock_changes.items()), columns=['Symbol', 'Percent_Change'])

    # Drop any stocks with missing data (NaN values)
    df = df.dropna()

    # Calculate the percentile rank based on percentage change
    df['RSP'] = round(df['Percent_Change'].rank(pct=True) * 100, 2)
    cols = ['Symbol', 'RSP']
    df = df[cols]
    # Sort by percentile rank (optional)
    df = df.sort_values(by='RSP', ascending=False).reset_index(drop=True)

    return df

In [6]:
# function to get stock technicals
def stock_prec_dev(stock_symbol):
    #stock_symbol = 'ULTRACEMCO.NS'
    short_window = 20
    mid_window = 50
    long_window = 200
    moving_avg = 'SMA'

    start = datetime.datetime(*map(int, start_date.split('-')))
    end = datetime.datetime(*map(int, end_date.split('-')))

    stock_df = yfin.Ticker(stock_symbol + '.NS').history(period='max', interval='1d')[map(str.title, ['open', 'close', 'low', 'high', 'volume'])]

    stock_df['Max'] = round(max(stock_df['Close']),2)
    stock_df = stock_df[(stock_df.index <= end_date) & (stock_df.index >= start_date)]
    stock_df['200_SMA'] = round(stock_df['Close'].rolling(window = 200, min_periods = 1).mean(),0)
    stock_df['Dev%_200'] = round((stock_df['Close'] - stock_df['200_SMA'])*100/stock_df['200_SMA'],2)
    stock_df.dropna(axis = 0, inplace = True) # remove any null rows

    stock_df['20_SMA'] = stock_df['Close'].rolling(window=20).mean()
    stock_df['50_SMA'] = stock_df['Close'].rolling(window=50).mean()
    stock_df['Symbol'] = stock_symbol

    stock_df['Close'] = round(stock_df['Close'],2)
    stock_df['Min'] = round(min(stock_df['Close']),2)
    stock_df['RSI_14'] = ta.momentum.RSIIndicator(close=stock_df['Close'], window=14).rsi()
    stock_df['RSI_14'] = round(stock_df['RSI_14'],0)
    stock_df['Prev_Close'] = stock_df['Close'].shift(1)
    stock_df.drop(['Open', 'Low', 'High', 'Volume'], axis=1, inplace=True)
    stock_df = stock_df.tail(1)

    max_SMA = max(stock_df['20_SMA'].item(), stock_df['50_SMA'].item(), stock_df['200_SMA'].item())
    min_SMA = min(stock_df['20_SMA'].item(), stock_df['50_SMA'].item(), stock_df['200_SMA'].item())
    ABS_Spread = max_SMA - min_SMA
    stock_df['Spread%'] = round((ABS_Spread / stock_df['200_SMA'].item()) * 100,2)

    return stock_df

# function to compute stock attributes
def get_common_features(stock_ids, df_mypf):

  df_prec_dev = pd.DataFrame()
  df_tmp = get_screener_features()
  df_rs = get_relative_strength(stock_ids)

  for stock_id in stock_ids:
      tmp = stock_prec_dev(stock_id)
      tmp = tmp.reset_index()
      df_prec_dev = pd.concat([df_prec_dev, tmp], ignore_index = True)
  df_prec_dev = pd.merge(df_prec_dev, df_mypf, on= 'Symbol')
  df_prec_dev = pd.merge(df_prec_dev, df_tmp, on= 'Symbol', how='left')
  df_prec_dev = pd.merge(df_prec_dev, df_rs, on= 'Symbol', how='left')
  #print(df_prec_dev.columns)
  df_prec_dev['Curr_PE'] = round(df_prec_dev['Close']/df_prec_dev['EPS'],1)
  df_prec_dev['Dev%_PE'] = round((df_prec_dev['Curr_PE'] - df_prec_dev['MedPE'])*100/df_prec_dev['MedPE'],2)
  df_prec_dev['Conviction'] = df_prec_dev['Conviction'] + '-' + df_prec_dev['CapType']
  return df_prec_dev

# function to arrange stock features
def arrange_features(df_stocks, common_cols, diff_cols):
  df_stocks_common = df_stocks[common_cols].drop_duplicates()
  df_stocks_diff = df_stocks[diff_cols]
  df_stocks_diff['Investment'] = df_stocks_diff['AvgCost'] * df_stocks_diff['Shares']
  df_stocks_diff = df_stocks_diff.groupby(['Symbol'])[['Shares', 'Investment']].aggregate(['sum']).reset_index()
  df_stocks_diff.columns = ['Symbol', 'Shares', 'Investment']
  df_stocks_diff['AvgCost'] = round(df_stocks_diff['Investment']/df_stocks_diff['Shares'],2)
  df_stocks = pd.merge(df_stocks_diff, df_stocks_common, on='Symbol')
  return df_stocks

# plot fact distribution across dimension
def plot_pie_chart(df, dimension, fact):
  # grouping the data by category and calculating the sum of fact for each type
  grouped_data = df.groupby(dimension)[fact].sum()

  # sorting the grouped data in descending order
  grouped_data = grouped_data.sort_values(ascending=False)

  # creating a pie chart
  grouped_data.plot.pie(autopct='%1.1f%%', startangle=90, figsize=(6, 6))

  # adding a title and displaying the plot
  plt.title(f'{dimension} {fact} Distribution')
  plt.ylabel('')  # To hide the y-label
  plt.show()

In [7]:
# function to get portfolio features

def get_portfolio_features(df_common_features):

  print_date_time()
  print('-------------------')

  #df_common_features["Target"] = df_common_features["Target"].fillna(df_common_features["Max"])
  df_common_features['NTT'] = np.where(df_common_features['Strategy']== 'NTT', df_common_features["Target"], df_common_features['Max'])
  df_common_features['LTT'] = np.where(df_common_features['Strategy']== 'BTT', df_common_features["Target"], df_common_features['Max'])
  df_common_features['BOL'] = df_common_features['Min']

  tmp_df = df_common_features[df_common_features['Symbol'].isin(mypf_df[mypf_df['InPortfolio'] != 'NA'].Symbol.values)]
  print('qualified stocks: '+str(len(tmp_df['Symbol'].unique())))
  tmp_df1 = tmp_df[tmp_df['LatestQtr'] == 1]
  print('with latest results: '+str(len(tmp_df1['Symbol'].unique())))
  tmp_df1 = tmp_df1[tmp_df1['StarStock'] == 1]
  print('still star stocks: '+str(len(tmp_df1['Symbol'].unique())))
  tmp_df['Investment'] = tmp_df['AvgCost'] * tmp_df['Shares']
  tmp_df['Current'] = round(tmp_df['Close'] * tmp_df['Shares'],0)
  tmp_df['Previous'] = tmp_df['Prev_Close'] * tmp_df['Shares']
  tmp_df['EstimatedST'] = tmp_df['NTT'] * tmp_df['Shares']
  tmp_df['EstimatedLT'] = tmp_df['LTT'] * tmp_df['Shares']
  tmp_df['Current P/L'] = round((tmp_df['Current'] - tmp_df['Investment']),0)
  tmp_df['Today P/L%'] = round((tmp_df['Current'] - tmp_df['Previous'])*100/tmp_df['Previous'],2)
  tmp_df['Current P/L%'] = round((tmp_df['Current'] - tmp_df['Investment'])*100/tmp_df['Investment'],2)
  tmp_df['EstimatedST P/L%'] = round((tmp_df['EstimatedST'] - tmp_df['Investment'])*100/tmp_df['Investment'],2)
  tmp_df['EstimatedLT P/L%'] = round((tmp_df['EstimatedLT'] - tmp_df['Investment'])*100/tmp_df['Investment'],2)
  tmp_df['NTT%'] = round((tmp_df['NTT'] - tmp_df['Close'])*100/tmp_df['Close'],2)
  tmp_df['LTT%'] = round((tmp_df['LTT'] - tmp_df['Close'])*100/tmp_df['Close'],2)
  tmp_df['Gained%'] = round((tmp_df['Close'] - tmp_df['BOL'])*100/tmp_df['BOL'],2)
  investment = round(sum(tmp_df['AvgCost']*tmp_df['Shares']),0)
  current = round(sum(tmp_df['Close']*tmp_df['Shares']),0)
  tmp_df['InitAlloc%'] = round(tmp_df['Investment']*100/investment,2)
  tmp_df['CurrAlloc%'] = round(tmp_df['Current']*100/current,2)
  tmp_df['FTT'] = tmp_df['LTT']
  tmp_df.loc[tmp_df['Strategy'] == 'NTT', 'FTT'] = tmp_df['NTT']
  tmp_df['FTT%'] = tmp_df['LTT%']
  tmp_df.loc[tmp_df['Strategy'] == 'NTT', 'FTT%'] = tmp_df['NTT%']
  tmp_df['FTT Amt'] = round(tmp_df['FTT%'] * tmp_df['Current']/100,0)
  tmp_df['OTT%'] = round((tmp_df['FTT'] - tmp_df['AvgCost'])*100/tmp_df['AvgCost'],2)
  tmp_df['RRR Ind'] = round(tmp_df['Current P/L']/tmp_df['FTT Amt'],2)
  tmp_df['Risk Ind'] = round(tmp_df['Current P/L%']*tmp_df['CurrAlloc%'],0)

  return tmp_df

# function to print portfolio features
def print_portfolio_stats(df_portfolio_features, myinvmt_df):
  from pyxirr import xirr

  total_booked_amt, reserve_amt, cy_booked_amt, py_booked_amt = get_amt()

  dates = myinvmt_df['Date'].values
  dates = np.append(dates, datetime.date.today().strftime('%d-%b-%y'))
  investment = myinvmt_df['Investment'].values
  dates= pd.to_datetime(dates)

  current = round(sum(df_portfolio_features['Close']*df_portfolio_features['Shares']),0) + reserve_amt
  investment_xirr = np.append(investment, current)
  cagr = round(xirr(pd.DataFrame({"dates": dates, "amounts": investment_xirr}))*100,2)

  investment = -sum(investment)
  invested = round(sum(df_portfolio_features['AvgCost']*df_portfolio_features['Shares']),0) + reserve_amt
  previous = round(sum(df_portfolio_features['Prev_Close']*df_portfolio_features['Shares']),0) + reserve_amt
  cy_invested = investment + py_booked_amt

  today_pnl_amount = current-previous
  today_pnl_percentage = round((current-previous)*100/previous,2)

  curr_pnl_amount = current-invested
  curr_pnl_percentage = round((curr_pnl_amount)*100/(cy_invested),2)

  cy_pnl_amount = cy_booked_amt + curr_pnl_amount
  cy_pnl_percentage = round((cy_pnl_amount)*100/cy_invested,2)

  overall_pnl_amount = total_booked_amt + curr_pnl_amount
  overall_pnl_percentage = round((overall_pnl_amount)*100/investment,2)

  estimate_st = round(sum(df_portfolio_features['FTT']*df_portfolio_features['Shares']),0)  + reserve_amt
  est_st_pnl_amount = estimate_st-current
  est_st_pnl_percentage = round((est_st_pnl_amount)*100/current,2)

  estimate_lt = round(sum(df_portfolio_features['LTT']*df_portfolio_features['Shares']),0)  + reserve_amt
  est_lt_pnl_amount = estimate_lt-current
  est_lt_pnl_percentage = round((est_lt_pnl_amount)*100/current,2)

  total_profit = round(sum(df_portfolio_features[df_portfolio_features['Current P/L%'] > 0]['Current']) - sum(df_portfolio_features[df_portfolio_features['Current P/L%'] > 0]['Investment']),0)
  total_loss = round(sum(df_portfolio_features[df_portfolio_features['Current P/L%'] < 0]['Current']) - sum(df_portfolio_features[df_portfolio_features['Current P/L%'] < 0]['Investment']),0)

  cy_booked_percentage = round((cy_booked_amt)*100/current,2)
  py_booked_percentage = round((py_booked_amt)*100/investment,2)
  total_booked_percentage = round((total_booked_amt)*100/investment,2)

  print('-------------------')
  print('Initial Investment: ', format_amt(investment))
  print('CY Investment: ', format_amt(cy_invested))
  print('Reserve: ', format_amt(reserve_amt))
  print('Current: ',  format_amt(current))
  print('-------------------')
  print('Today PnL: '+ '{} ({}%)'.format(format_amt(today_pnl_amount), today_pnl_percentage))
  print('Current PnL: '+ '{} ({}%)'.format(format_amt(curr_pnl_amount), curr_pnl_percentage))
  print('CY Booked + Current PnL: '+ '{} ({}%)'.format(format_amt(cy_pnl_amount), cy_pnl_percentage))
  print('-------------------')
  print('Total profit: ', format_amt(total_profit))
  print('Total loss: ', format_amt(total_loss))
  print('-------------------')
  print('Total Booked + Current PnL: '+ '{} ({}%)'.format(format_amt(overall_pnl_amount), overall_pnl_percentage))
  print('Total Booked PnL: '+ '{} ({}%)'.format(format_amt(total_booked_amt), total_booked_percentage))
  print('Curr Year Booked PnL: '+ '{} ({}%)'.format(format_amt(cy_booked_amt), cy_booked_percentage))
  print('Prev Year Booked PnL: '+ '{} ({}%)'.format(format_amt(py_booked_amt), py_booked_percentage))
  print('===================')
  print('Est FTT: ',  format_amt(estimate_st))
  print('Est FTT PnL: '+ '{} ({}%)'.format(format_amt(est_st_pnl_amount), est_st_pnl_percentage))

  print('===================')
  print('Deployed: ', format_amt(investment))

  print('Current: ', format_amt(current))

  print('CAGR/XIRR %: '+'{}%'.format(cagr))

In [8]:
# get start and end date
start_date, end_date = get_start_end_date()

# get portfolio and prospects data
mypfs_df = get_mypfs_df()
mypps_df = get_mypps_df()
myinvmt_df = get_myinvmt_df()

# merge above datasets
mypf_df = pd.merge(mypfs_df, mypps_df, on="Symbol")

# seggregate dm and sv portfolio
dm_pf = mypf_df[mypf_df['InPortfolio'] == 'DM']
sv_pf = mypf_df[mypf_df['InPortfolio'] == 'SV']

# build portfolio stock dataframe
dm_stocks = get_stock_ids(dm_pf)
sv_stocks = get_stock_ids(sv_pf)
df_stocks = pd.concat([dm_pf,sv_pf], ignore_index = True)

# arrange common and diff stock features
common_cols = ['Symbol', 'Target', 'Criteria', 'Strategy', 'CumlRnk', 'LatestQtr', 'StarStock', 'Conviction', 'Category', 'InFolio', 'XIRR', 'MBQ']
diff_cols = ['Symbol', 'AvgCost', 'Shares']
df_stocks = arrange_features(df_stocks, common_cols, diff_cols)

# get common features
stock_ids = df_stocks['Symbol'].values
df_common_features = get_common_features(stock_ids, df_stocks)

df_common_features.reset_index(drop=True, inplace=True)
df_common_features.drop(['Date'], axis=1, inplace=True)
# get and print portfolio features
df_portfolio_features = get_portfolio_features(df_common_features)

print_portfolio_stats(df_portfolio_features, myinvmt_df)

df = df_portfolio_features
#plot_pie_chart(df, 'CapType', 'Current')
list_ox40n = list(df[df['MBQ'].str.contains('OX40N', na=False)]['Symbol'].values)

Run date time (IST): 2026-03-16 10:10:03
-------------------
qualified stocks: 86
with latest results: 26
still star stocks: 15

-------------------
Initial Investment:  1.36 C
CY Investment:  1.62 C
Reserve:  66.25 K
Current:  1.32 C
-------------------
Today PnL: -1.02 L (-0.77%)
Current PnL: -44.85 L (-27.6%)
CY Booked + Current PnL: -29.17 L (-17.95%)
-------------------
Total profit:  89.78 K
Total loss:  -45.75 L
-------------------
Total Booked + Current PnL: -2.19 L (-1.62%)
Total Booked PnL: 42.66 L (31.48%)
Curr Year Booked PnL: 15.68 L (11.87%)
Prev Year Booked PnL: 26.98 L (19.91%)
===================
Est FTT:  2.47 C
Est FTT PnL: 1.15 C (87.23%)
===================
Deployed:  1.36 C
Current:  1.32 C
CAGR/XIRR %: -1.28%

In [9]:
# top 5 near their targets
cols = ['Symbol', 'Today P/L%', 'Current P/L%', 'FTT%', 'OTT%', 'FTT Amt', 'Current P/L', 'Current', 'FTT', 'Dev%_PE', 'RSI_14','Conviction', 'Spread%',  'CumlRnk', 'RRR Ind', 'CurrAlloc%', 'Gained%', 'Criteria', 'Strategy', 'Category']
df_tmp = df_portfolio_features[~df_portfolio_features['Symbol'].isin(['ENRIN','BLUSPRING','DIGITIDE'])]
df_tmp = df_tmp.sort_values(by = 'FTT Amt', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
19,COALINDIA,-0.50,14.26,2.98,17.67,5123.0,21460.0,171920.0,478.51,37.73,66.0,L-LC,13.39,185.0,4.19,1.31,33.51,XY25,ATH,MINING
50,MASFIN,-1.48,-9.02,33.62,21.57,29971.0,-8835.0,89145.0,397.04,-21.41,35.0,H-SC,2.99,167.0,-0.29,0.68,23.62,XR,ATH,FINANCE
77,TTKPRESTIG,-4.43,-32.67,48.65,0.09,33013.0,-32919.0,67858.0,770.00,57.52,47.0,M-SC,15.76,250.0,-1.00,0.52,14.65,OX40N,NTT,DURABLES
37,ICICIGI,-0.39,-3.07,23.12,19.34,44846.0,-6140.0,193969.0,2252.93,-18.36,37.0,X-MC,2.03,66.0,-0.14,1.48,7.22,X40,ATH,INSURANCE
2,ABBOTINDIA,-0.45,-9.96,31.13,18.07,50132.0,-17815.0,161040.0,35195.00,-23.42,48.0,X-MC,10.91,58.0,-0.36,1.23,2.09,X40,ATH,PHARMA

In [10]:
# top 5 today
df_tmp = df_portfolio_features.sort_values(by = 'Today P/L%', ascending=False)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
81,VBL,1.94,-17.36,64.18,35.67,167514.0,-54836.0,261006.0,671.64,-26.98,32.0,X-LC,5.90,13.0,-0.33,1.99,1.94,X40N,ATH,FMCG
42,INDUSINDBK,1.25,-39.13,118.30,32.89,55600.0,-30208.0,46999.0,1800.00,-321.29,31.0,L-MC,9.41,258.0,-0.54,0.36,29.43,XR,NTT,BANKS
8,AWL,1.13,-39.79,177.38,67.02,380553.0,-141768.0,214541.0,485.00,-67.56,23.0,X-SC,24.30,81.0,-0.37,1.63,1.13,XY24,NTT,FMCG
45,ITC,1.11,-19.72,48.29,19.06,131880.0,-67065.0,273101.0,452.00,-55.92,37.0,X-LC,17.17,1.0,-0.51,2.08,1.11,X40,NTT,FMCG
62,SATIN,0.84,-19.51,88.64,51.83,197116.0,-53906.0,222378.0,274.00,-27.73,39.0,H-SC,0.85,159.0,-0.27,1.69,8.33,XY24,NTT,FINANCE

In [11]:
# bottom 5 today
df_tmp = df_portfolio_features.sort_values(by = 'Today P/L%', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
31,HAPPSTMNDS,-5.95,-53.83,300.35,84.85,177735.0,-68989.0,59176.0,1480.71,-45.14,46.0,H-SC,27.84,152.0,-0.39,0.45,9.59,AR,ATH,IT
55,RAJESHEXPO,-4.96,-79.79,395.22,0.07,109551.0,-109458.0,27719.0,518.00,916.41,20.0,L-SC,24.53,268.0,-1.00,0.21,0.00,OX40N,NTT,JEWELLERY
77,TTKPRESTIG,-4.43,-32.67,48.65,0.09,33013.0,-32919.0,67858.0,770.00,57.52,47.0,M-SC,15.76,250.0,-1.00,0.52,14.65,OX40N,NTT,DURABLES
74,TITAGARH,-3.47,-41.89,150.81,45.74,212223.0,-101455.0,140722.0,1548.00,-22.58,25.0,H-SC,17.82,175.0,-0.48,1.07,0.00,XY24,NTT,ENGINEERING
54,QUESS,-3.42,-28.02,141.60,73.90,108847.0,-29924.0,76869.0,424.00,-61.43,30.0,X-SC,18.80,80.0,-0.27,0.58,0.00,XY24,NTT,MISC

In [12]:
# top 5 to exit based on CumlRnk
df_tmp = df_portfolio_features[~df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])]
df_tmp = df_tmp[(df_tmp['Current P/L%'] > -1) & (df_tmp['Current P/L%'] < 1)].sort_values(by = 'CumlRnk', ascending=False)
df_tmp[cols].head()

Empty DataFrame
Columns: [Symbol, Today P/L%, Current P/L%, FTT%, OTT%, FTT Amt, Current P/L, Current, FTT, Dev%_PE, RSI_14, Conviction, Spread%, CumlRnk, RRR Ind, CurrAlloc%, Gained%, Criteria, Strategy, Category]
Index: []

In [13]:
# OX40N stocks to exit
df_tmp = df_portfolio_features[(df_portfolio_features['Symbol'].isin(list_ox40n))].sort_values(by = 'Current P/L%', ascending=False)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
27,FINCABLES,-0.58,7.78,92.90,107.91,147838.0,11493.0,159137.0,1641.55,-3.09,49.0,M-SC,7.80,220.0,0.08,1.21,19.72,OX40N,ATH,CABLES
77,TTKPRESTIG,-4.43,-32.67,48.65,0.09,33013.0,-32919.0,67858.0,770.00,57.52,47.0,M-SC,15.76,250.0,-1.00,0.52,14.65,OX40N,NTT,DURABLES
66,SIS,-0.38,-36.07,89.69,21.26,63661.0,-40053.0,70979.0,528.00,1659.07,30.0,H-SC,12.24,168.0,-0.63,0.54,0.00,OX40N,NTT,MISC
70,SYMPHONY,0.74,-38.38,62.24,-0.03,65635.0,-65686.0,105455.0,1306.00,-50.45,44.0,M-SC,14.46,205.0,-1.00,0.80,6.64,OX40N,NTT,DURABLES
72,TATAELXSI,-0.58,-39.03,116.55,32.03,93683.0,-51455.0,80380.0,9161.00,-23.72,26.0,H-SC,18.14,158.0,-0.55,0.61,0.00,OX40N,NTT,IT

In [14]:
# top 5 to book for rotation
df_tmp = df_portfolio_features[(df_portfolio_features['Current P/L%'] > 20) ].sort_values(by = 'CumlRnk', ascending=False)
df_tmp[cols].head()

Empty DataFrame
Columns: [Symbol, Today P/L%, Current P/L%, FTT%, OTT%, FTT Amt, Current P/L, Current, FTT, Dev%_PE, RSI_14, Conviction, Spread%, CumlRnk, RRR Ind, CurrAlloc%, Gained%, Criteria, Strategy, Category]
Index: []

In [15]:
# top 5 to monitor for exit
df_tmp = df_portfolio_features[~df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])]
df_tmp = df_tmp[(df_tmp['Current P/L%'] > 0) ].sort_values(by = 'Dev%_PE', ascending=False)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
19,COALINDIA,-0.50,14.26,2.98,17.67,5123.0,21460.0,171920.0,478.51,37.73,66.0,L-LC,13.39,185.0,4.19,1.31,33.51,XY25,ATH,MINING
27,FINCABLES,-0.58,7.78,92.90,107.91,147838.0,11493.0,159137.0,1641.55,-3.09,49.0,M-SC,7.80,220.0,0.08,1.21,19.72,OX40N,ATH,CABLES
1,ABB,-1.81,15.16,26.41,45.57,79566.0,39653.0,301272.0,7934.00,-26.00,62.0,H-MC,11.51,125.0,0.50,2.29,33.78,AR,NTT,ELECTRICAL

In [16]:
# top 5 to book for rotation from weak conviction
df_tmp = df_portfolio_features[~df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])]
df_tmp = df_tmp[~df_tmp['Criteria'].isin(['XY25','XY24','X40', 'X40N'])].sort_values(by = 'RRR Ind', ascending=False)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
1,ABB,-1.81,15.16,26.41,45.57,79566.0,39653.0,301272.0,7934.00,-26.00,62.0,H-MC,11.51,125.0,0.50,2.29,33.78,AR,NTT,ELECTRICAL
27,FINCABLES,-0.58,7.78,92.90,107.91,147838.0,11493.0,159137.0,1641.55,-3.09,49.0,M-SC,7.80,220.0,0.08,1.21,19.72,OX40N,ATH,CABLES
40,INDIAMART,0.10,-9.58,128.63,106.72,143444.0,-11819.0,111517.0,4810.62,-59.18,41.0,H-SC,9.79,140.0,-0.08,0.85,11.56,AR,ATH,MISC
85,ZYDUSLIFE,-1.03,-5.46,43.46,35.63,86111.0,-11436.0,198138.0,1286.17,-17.57,45.0,H-MC,5.07,120.0,-0.13,1.51,10.31,AR,ATH,PHARMA
84,WIPRO,-0.54,-19.40,113.72,72.27,155320.0,-32867.0,136581.0,420.00,-27.37,29.0,M-LC,15.51,98.0,-0.21,1.04,0.57,XR,NTT,IT

In [17]:
# top 5 to accumulate based on lowest RSI_14
df_tmp = df_portfolio_features[df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])].sort_values(by = 'RSI_14', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
58,RELAXO,-2.22,-62.68,308.12,52.31,166915.0,-90988.0,54172.0,1176.00,-60.31,15.0,X-SC,20.86,92.0,-0.55,0.41,0.00,X40N,NTT,FOOTWEAR
12,BATAINDIA,-2.15,-55.86,206.28,35.20,117169.0,-71869.0,56801.0,2096.00,-25.49,17.0,X-SC,27.48,91.0,-0.61,0.43,0.00,X40,NTT,FOOTWEAR
13,BERGEPAINT,-2.27,-26.55,70.62,25.32,133691.0,-68438.0,189311.0,680.00,-30.53,18.0,X-MC,16.61,68.0,-0.51,1.44,0.00,XY24,NTT,PAINTS
3,ACC,0.34,-38.19,182.82,74.81,302991.0,-102396.0,165732.0,3906.00,-56.11,18.0,X-SC,14.10,85.0,-0.34,1.26,0.34,XY24,BTT,CEMENT
53,PGHH,-2.33,-22.99,71.42,32.01,117437.0,-49088.0,164432.0,17616.87,-47.93,18.0,X-MC,12.33,57.0,-0.42,1.25,0.00,X40,ATH,FMCG

In [18]:
# top 5 to accumulate based on Spread and CumlRnk
df_tmp = df_portfolio_features[df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])]
df_tmp = df_tmp[(df_tmp['CumlRnk'] < 100)].sort_values(by = 'Spread%', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
78,UNITDSPR,0.56,-2.90,24.38,20.77,55428.0,-6794.0,227350.0,1644.00,-13.87,42.0,X-MC,1.06,64.0,-0.12,1.73,3.61,X40N,NTT,BREWERIES
37,ICICIGI,-0.39,-3.07,23.12,19.34,44846.0,-6140.0,193969.0,2252.93,-18.36,37.0,X-MC,2.03,66.0,-0.14,1.48,7.22,X40,ATH,INSURANCE
75,TMPV,-1.23,-29.38,93.39,36.58,234691.0,-104539.0,251302.0,600.00,-85.81,28.0,X-LC,2.18,4.0,-0.45,1.91,0.00,XY24,NTT,AUTO
22,DABUR,0.33,-11.04,61.54,43.70,135803.0,-27393.0,220675.0,735.00,-19.28,30.0,X-MC,2.37,70.0,-0.20,1.68,2.35,XY24,BTT,FMCG
38,ICICIPRULI,0.21,-3.20,35.04,30.73,66825.0,-6295.0,190710.0,790.00,-29.17,26.0,X-MC,2.84,78.0,-0.09,1.45,9.10,X40,ATH,INSURANCE

In [19]:
# top 5 to accumulate based on lowest Gained%
df_tmp = df_portfolio_features[df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])].sort_values(by = 'Gained%', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
6,ASIANPAINT,-0.29,-21.17,57.97,24.52,129517.0,-60018.0,223421.0,3460.25,-20.55,27.0,X-LC,7.34,30.0,-0.46,1.70,0.0,X40,ATH,PAINTS
9,BAJAJHFL,-1.41,-27.66,124.10,62.13,245141.0,-75511.0,197535.0,181.50,-40.41,25.0,X-MC,19.07,60.0,-0.31,1.50,0.0,X40N,ATH,FINANCE
12,BATAINDIA,-2.15,-55.86,206.28,35.20,117169.0,-71869.0,56801.0,2096.00,-25.49,17.0,X-SC,27.48,91.0,-0.61,0.43,0.0,X40,NTT,FOOTWEAR
13,BERGEPAINT,-2.27,-26.55,70.62,25.32,133691.0,-68438.0,189311.0,680.00,-30.53,18.0,X-MC,16.61,68.0,-0.51,1.44,0.0,XY24,NTT,PAINTS
21,COLPAL,-0.07,-25.73,90.54,41.51,177087.0,-67775.0,195590.0,3726.84,-10.11,30.0,X-MC,4.14,62.0,-0.38,1.49,0.0,XY25,ATH,FMCG

In [20]:
# top 5 to accumulate based on lowest CurrAlloc%
df_tmp = df_portfolio_features[df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])].sort_values(by = 'CurrAlloc%', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
58,RELAXO,-2.22,-62.68,308.12,52.31,166915.0,-90988.0,54172.0,1176.00,-60.31,15.0,X-SC,20.86,92.0,-0.55,0.41,0.00,X40N,NTT,FOOTWEAR
12,BATAINDIA,-2.15,-55.86,206.28,35.20,117169.0,-71869.0,56801.0,2096.00,-25.49,17.0,X-SC,27.48,91.0,-0.61,0.43,0.00,X40,NTT,FOOTWEAR
54,QUESS,-3.42,-28.02,141.60,73.90,108847.0,-29924.0,76869.0,424.00,-61.43,30.0,X-SC,18.80,80.0,-0.27,0.58,0.00,XY24,NTT,MISC
36,HONAUT,-0.63,-22.58,95.44,51.31,142492.0,-43538.0,149300.0,58357.33,-35.58,36.0,X-SC,14.07,90.0,-0.31,1.14,0.54,X40N,ATH,ELECTRICAL
51,MEDANTA,-1.42,-9.59,40.60,27.12,64794.0,-16925.0,159592.0,1486.00,-12.33,35.0,X-SC,9.11,87.0,-0.26,1.21,2.61,XY24,NTT,HEALTHCARE

In [21]:
# top 5 to accumulate based on CumlRnk
df_tmp = df_portfolio_features.sort_values(by = 'CumlRnk', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
45,ITC,1.11,-19.72,48.29,19.06,131880.0,-67065.0,273101.0,452.00,-55.92,37.0,X-LC,17.17,1.0,-0.51,2.08,1.11,X40,NTT,FMCG
73,TCS,-0.81,-29.81,80.33,26.57,261214.0,-138097.0,325176.0,4311.59,-40.68,18.0,X-LC,15.22,2.0,-0.53,2.47,0.00,X40,ATH,IT
43,INFY,-0.90,-15.78,59.41,34.24,156547.0,-49386.0,263502.0,1972.00,-33.60,22.0,X-LC,13.47,3.0,-0.32,2.01,0.00,X40,NTT,IT
75,TMPV,-1.23,-29.38,93.39,36.58,234691.0,-104539.0,251302.0,600.00,-85.81,28.0,X-LC,2.18,4.0,-0.45,1.91,0.00,XY24,NTT,AUTO
34,HCLTECH,-0.05,-14.03,44.04,23.83,91601.0,-33930.0,207994.0,1908.19,-9.84,26.0,X-LC,10.15,8.0,-0.37,1.58,0.00,X40,ATH,IT

In [22]:
# top 5 for average up
df_tmp = df_portfolio_features[(df_portfolio_features['Dev%_200'] > 5)].sort_values(by = 'CurrAlloc%', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
19,COALINDIA,-0.50,14.26,2.98,17.67,5123.0,21460.0,171920.0,478.51,37.73,66.0,L-LC,13.39,185.0,4.19,1.31,33.51,XY25,ATH,MINING
1,ABB,-1.81,15.16,26.41,45.57,79566.0,39653.0,301272.0,7934.00,-26.00,62.0,H-MC,11.51,125.0,0.50,2.29,33.78,AR,NTT,ELECTRICAL

In [23]:
# top 5 RSP
df_tmp = df_portfolio_features.sort_values(by = 'RSP', ascending=False)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
19,COALINDIA,-0.50,14.26,2.98,17.67,5123.0,21460.0,171920.0,478.51,37.73,66.0,L-LC,13.39,185.0,4.19,1.31,33.51,XY25,ATH,MINING
1,ABB,-1.81,15.16,26.41,45.57,79566.0,39653.0,301272.0,7934.00,-26.00,62.0,H-MC,11.51,125.0,0.50,2.29,33.78,AR,NTT,ELECTRICAL
69,SURYODAY,-0.74,-25.38,64.89,23.03,86706.0,-45451.0,133620.0,216.00,44.74,51.0,H-SC,7.49,166.0,-0.52,1.02,32.58,XR,NTT,BANKS
27,FINCABLES,-0.58,7.78,92.90,107.91,147838.0,11493.0,159137.0,1641.55,-3.09,49.0,M-SC,7.80,220.0,0.08,1.21,19.72,OX40N,ATH,CABLES
2,ABBOTINDIA,-0.45,-9.96,31.13,18.07,50132.0,-17815.0,161040.0,35195.00,-23.42,48.0,X-MC,10.91,58.0,-0.36,1.23,2.09,X40,ATH,PHARMA

In [24]:
# Top N allocation
df_tmp = df_portfolio_features.sort_values(by = 'CurrAlloc%', ascending=False)
top_n_values = [10, 25, 50]

sum_df = pd.DataFrame({
    'Top_N': top_n_values,
    'Sum_Alloc%': [df_tmp['CurrAlloc%'].head(n).sum() for n in top_n_values]
})

sum_df

   Top_N  Sum_Alloc%
0     10       20.61
1     25       45.51
2     50       77.97

In [25]:
# market-cap-wise allocation
df_tmp = df_portfolio_features[cols]
df_tmp.groupby(df_tmp['Conviction'].str[-2:])['CurrAlloc%'].sum().sort_values(ascending=False)

Conviction
SC    44.54
MC    30.40
LC    25.05
Name: CurrAlloc%, dtype: float64

In [26]:
# criteria-wise allocation
df_portfolio_features.groupby('Criteria')['CurrAlloc%'].sum().sort_values(ascending=False)

Criteria
XY24     27.14
X40      23.88
X40N     15.09
AR        9.22
XY25      8.78
XR        8.24
OX40N     6.88
SR        0.76
Name: CurrAlloc%, dtype: float64

In [27]:
# conviction-wise allocation
df_portfolio_features.groupby('Conviction')['CurrAlloc%'].sum().sort_values(ascending=False)

Conviction
X-MC    22.91
H-SC    21.67
X-LC    21.49
X-SC    12.14
M-SC    10.16
H-MC     5.10
M-MC     2.03
L-LC     1.31
H-LC     1.21
M-LC     1.04
L-SC     0.57
L-MC     0.36
Name: CurrAlloc%, dtype: float64

In [28]:
# sector-wise stats
df_tmp = df_portfolio_features.groupby('Category')[['CurrAlloc%', 'Current', 'Current P/L', 'FTT Amt']].sum().sort_values(by=['Current', 'Current P/L'], ascending=False)
df_tmp['Current P/L%'] = round(df_tmp['Current P/L'] * 100 / df_tmp['Current'], 2)
df_tmp['FTT%'] = round(df_tmp['FTT Amt'] * 100 / df_tmp['Current'], 2)
cols = ['CurrAlloc%', 'Current P/L%', 'FTT%']
df_tmp[cols].sort_values(by=['CurrAlloc%'], ascending=False)

               CurrAlloc%  Current P/L%    FTT%
Category
FMCG                15.33        -24.03   68.07
FINANCE             12.92        -26.47   78.01
IT                  11.65        -47.19  122.10
MISC                 6.96        -46.59  110.27
ELECTRICAL           6.72         -9.79   51.82
PAINTS               5.10        -46.90   72.41
INSURANCE            4.84         -6.78   43.32
PHARMA               4.21         -6.39   39.88
AUTO                 3.60        -38.06   92.83
BANKS                3.12        -30.87  110.17
AC                   2.13        -14.11   45.05
HEALTHCARE           1.96        -38.61   74.78
DURABLES             1.90        -55.07   92.79
FOOTWEAR             1.85        -81.62  154.44
TRAVEL               1.81        -87.47  181.34
BREWERIES            1.73         -2.99   24.38
APPARELS             1.60        -27.44   70.91
REALTY               1.44        -17.12   36.36
REFINERIES           1.35        -13.22   41.87
CERAMICS             1.34        -73.99  126.85
MINING               1.31         12.48    2.98
CEMENT               1.26        -61.78  182.82
CABLES               1.21          7.22   92.90
JEWELLERY            1.10       -120.70  197.38
ENGINEERING          1.07        -72.10  150.81
CHEMICALS            0.94       -114.18  288.92
ENTERTAINMENT        0.76        -93.03  208.16
TEXTILES             0.42        -65.41  112.58
HOTELS               0.36       -140.31  225.07

In [29]:
# money to be made criteria-wise
df_portfolio_features.groupby('Criteria')['FTT Amt'].agg(['sum', 'count']).sort_values(by='sum', ascending=False)

                sum  count
Criteria
XY24      4029853.0     21
X40       1735132.0     15
XR        1409331.0     12
AR        1360094.0     10
X40N      1317939.0     10
OX40N      886285.0     10
XY25       463713.0      6
SR         318921.0      2

In [30]:
# money to be made conviction-wise
df_portfolio_features.groupby('Conviction')['FTT Amt'].agg(['sum', 'count']).sort_values(by='sum', ascending=False)

                  sum  count
Conviction
H-SC        3944866.0     24
X-MC        1723202.0     15
X-LC        1650682.0     12
X-SC        1586341.0     10
M-SC        1582206.0     14
H-MC         408090.0      3
L-SC         215899.0      2
M-LC         155320.0      1
M-MC         118729.0      2
H-LC          75210.0      1
L-MC          55600.0      1
L-LC           5123.0      1

In [31]:
# money to be made criteria and conviction-wise
df_portfolio_features.groupby(['Conviction', 'Criteria'])['FTT Amt'].agg(['sum', 'count']).sort_values(by='sum', ascending=False)

                           sum  count
Conviction Criteria
H-SC       XY24      1349009.0      6
           AR         984887.0      5
M-SC       XY24       927216.0      6
H-SC       XR         896508.0      7
X-SC       XY24       857185.0      4
X-LC       X40        854616.0      6
X-MC       X40        672551.0      7
           X40N       534583.0      4
X-SC       X40N       521191.0      4
H-SC       OX40N      395541.0      4
X-LC       XY24       384536.0      2
M-SC       OX40N      381193.0      5
H-SC       SR         318921.0      2
X-MC       XY24       269494.0      2
X-LC       X40N       262165.0      2
X-MC       XY25       246574.0      2
H-MC       XY24       242413.0      1
X-SC       X40        207965.0      2
M-SC       XR         195555.0      2
H-MC       AR         165677.0      2
M-LC       XR         155320.0      1
X-LC       XY25       149365.0      2
L-SC       OX40N      109551.0      1
           XR         106348.0      1
M-SC       AR          78242.0      1
H-LC       AR          75210.0      1
M-MC       XY25        62651.0      1
           AR          56078.0      1
L-MC       XR          55600.0      1
L-LC       XY25         5123.0      1

In [32]:
# notebook execution time

end_time = time.time()
execution_time = round(end_time - start_time, 0)
print(f"Notebook execution time: {execution_time} seconds")

Notebook execution time: 35.0 seconds