<a href="https://colab.research.google.com/github/ankit-rathi/Quantvesting_v2/blob/main/myStocks_Portfolio_Analysis.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
'''
!pip install pandas==2.2.2 -qq
!pip install pyxirr -qq
!pip install ta -qq
!pip install yfinance==0.2.59 -qq
'''

'\n!pip install pandas==2.2.2 -qq\n!pip install pyxirr -qq\n!pip install ta -qq\n!pip install yfinance==0.2.59 -qq\n'

In [2]:
# import libraries

import numpy as np
import pandas as pd
import datetime
import warnings
warnings.filterwarnings('ignore')
import yfinance as yfin
import ta
import matplotlib.pyplot as plt
import requests

In [3]:
# notebook start time
import time
import datetime
import pytz

start_time = time.time()

# function to print date timestamp
def print_date_time():
  tz_NY = pytz.timezone('Asia/Kolkata')
  datetime_NY = datetime.datetime.now(tz_NY)
  print("Run date time (IST):", datetime_NY.strftime("%Y-%m-%d %H:%M:%S"))

In [4]:
# function to get booked and reserved amount
def get_amt():
  # fetch the JSON data from the URL
  url = "https://raw.githubusercontent.com/ankit-rathi/Tradevesting_v1/main/data/myPortfolioAmts.json"
  response = requests.get(url)
  pf_amts = response.json()  # parse the JSON data

  # extract values from the JSON
  py_booked_amt_dm = pf_amts["py_booked_amt_dm"]
  py_booked_amt_sv = pf_amts["py_booked_amt_sv"]
  cy_booked_amt_dm = pf_amts["cy_booked_amt_dm"]
  cy_booked_amt_sv = pf_amts["cy_booked_amt_sv"]
  reserve_amt_dm = pf_amts["reserve_amt_dm"]
  reserve_amt_sv = pf_amts["reserve_amt_sv"]

  # perform calculations
  py_booked_amt = py_booked_amt_dm + py_booked_amt_sv
  cy_booked_amt = cy_booked_amt_dm + cy_booked_amt_sv
  reserve_amt = reserve_amt_dm + reserve_amt_sv
  total_booked_amt = py_booked_amt + cy_booked_amt

  return total_booked_amt, reserve_amt, cy_booked_amt, py_booked_amt

gen_output = 0

In [5]:
# function to format the amount
def format_amt(number):
    abs_number = abs(number)

    if abs_number >= 1_00_00_000:  # Crores
        formatted_amt = f"{number / 1_00_00_000:.2f} C"
    elif abs_number >= 1_00_000:  # Lakhs
        formatted_amt = f"{number / 1_00_000:.2f} L"
    elif abs_number >= 1_000:  # Thousands
        formatted_amt = f"{number / 1_000:.2f} K"
    else:
        formatted_amt = f"{number:.2f}"

    return formatted_amt

# function to set start and end date
def get_start_end_date():
  start_date = (datetime.date.today() + datetime.timedelta(days=-365)).strftime('%Y-%m-%d')
  end_date = (datetime.date.today() + datetime.timedelta(days=1)).strftime('%Y-%m-%d')
  return start_date, end_date

# function to fetch my portfolio csv
def get_mypfs_df():
  mypfs_df = pd.read_csv('https://raw.githubusercontent.com/ankit-rathi/Tradevesting_v1/main/data/myPortfolioStocks.csv')
  return mypfs_df

# function to fetch my prospects csv
def get_mypps_df():
  mypps_df = pd.read_csv('https://raw.githubusercontent.com/ankit-rathi/Tradevesting_v1/main/data/myProspectsScrips.csv')
  return mypps_df

# function to fetch screener data
def get_myscreen_df():
  myscreen_df = pd.read_csv('https://raw.githubusercontent.com/ankit-rathi/Tradevesting_v1/main/data/myScreenerDB.csv')
  return myscreen_df

# function to fetch momentum data
def get_myinvmt_df():
  myinvmt_df = pd.read_csv('https://raw.githubusercontent.com/ankit-rathi/Tradevesting_v1/main/data/myInvestments.csv')
  return myinvmt_df

# function to get the stock ids
def get_stock_ids(df_pf):
  stock_n100 = df_pf['Symbol'].unique()

  exclude = ['CADILAHC','MMTC', 'MASFIN']

  stock_ids = df_pf[~df_pf['Symbol'].isin(exclude) ]['Symbol'].unique()

  #mypf = mypf[mypf.Forecast.notnull()]
  #stock_ids = mypf['Symbol'].unique()

  #stock_ids.sort()
  return stock_ids

# get features from screener data
def get_screener_features():
  myscreen_df = get_myscreen_df()
  cols = ['Symbol', 'EPS', 'MedPE', 'ROCE%', 'ROE%', 'CapType']
  return myscreen_df[cols]

# get relative strength
def get_relative_strength(stock_list):

    # Dictionary to store stock tickers and their corresponding percentage price change
    stock_changes = {}

    # Loop through each stock and fetch its price data
    for stock in stock_list:
        try:
            # Download the stock data for the given date range
            stock_data = yfin.Ticker(stock + '.NS').history(period='1mo', interval='1d')[map(str.title, ['open', 'close', 'low', 'high', 'volume'])]

            # Calculate the percentage change for the stock
            if len(stock_data) > 0:
                start_price = stock_data['Close'].iloc[0]
                end_price = stock_data['Close'].iloc[-1]
                percent_change = round(((end_price - start_price) / start_price) * 100, 2)
                stock_changes[stock] = percent_change
            else:
                stock_changes[stock] = np.nan  # If no data is available, set to NaN

        except Exception as e:
            print(f"Error fetching data for {stock}: {e}")
            stock_changes[stock] = np.nan

    # Create a DataFrame with stock tickers and their percentage changes
    df = pd.DataFrame(list(stock_changes.items()), columns=['Symbol', 'Percent_Change'])

    # Drop any stocks with missing data (NaN values)
    df = df.dropna()

    # Calculate the percentile rank based on percentage change
    df['RSP'] = round(df['Percent_Change'].rank(pct=True) * 100, 2)
    cols = ['Symbol', 'RSP']
    df = df[cols]
    # Sort by percentile rank (optional)
    df = df.sort_values(by='RSP', ascending=False).reset_index(drop=True)

    return df

In [6]:
# function to get stock technicals
def stock_prec_dev(stock_symbol):
    #stock_symbol = 'ULTRACEMCO.NS'
    short_window = 20
    mid_window = 50
    long_window = 200
    moving_avg = 'SMA'

    start = datetime.datetime(*map(int, start_date.split('-')))
    end = datetime.datetime(*map(int, end_date.split('-')))

    stock_df = yfin.Ticker(stock_symbol + '.NS').history(period='max', interval='1d')[map(str.title, ['open', 'close', 'low', 'high', 'volume'])]

    stock_df['Max'] = round(max(stock_df['Close']),2)
    stock_df = stock_df[(stock_df.index <= end_date) & (stock_df.index >= start_date)]
    stock_df['200_SMA'] = round(stock_df['Close'].rolling(window = 200, min_periods = 1).mean(),0)
    stock_df['Dev%_200'] = round((stock_df['Close'] - stock_df['200_SMA'])*100/stock_df['200_SMA'],2)
    stock_df.dropna(axis = 0, inplace = True) # remove any null rows

    stock_df['20_SMA'] = stock_df['Close'].rolling(window=20).mean()
    stock_df['50_SMA'] = stock_df['Close'].rolling(window=50).mean()
    stock_df['Symbol'] = stock_symbol

    stock_df['Close'] = round(stock_df['Close'],2)
    stock_df['Min'] = round(min(stock_df['Close']),2)
    stock_df['RSI_14'] = ta.momentum.RSIIndicator(close=stock_df['Close'], window=14).rsi()
    stock_df['RSI_14'] = round(stock_df['RSI_14'],0)
    stock_df['Prev_Close'] = stock_df['Close'].shift(1)
    stock_df.drop(['Open', 'Low', 'High', 'Volume'], axis=1, inplace=True)
    stock_df = stock_df.tail(1)

    max_SMA = max(stock_df['20_SMA'].item(), stock_df['50_SMA'].item(), stock_df['200_SMA'].item())
    min_SMA = min(stock_df['20_SMA'].item(), stock_df['50_SMA'].item(), stock_df['200_SMA'].item())
    ABS_Spread = max_SMA - min_SMA
    stock_df['Spread%'] = round((ABS_Spread / stock_df['200_SMA'].item()) * 100,2)

    return stock_df

# function to compute stock attributes
def get_common_features(stock_ids, df_mypf):

  df_prec_dev = pd.DataFrame()
  df_tmp = get_screener_features()
  df_rs = get_relative_strength(stock_ids)

  for stock_id in stock_ids:
      tmp = stock_prec_dev(stock_id)
      tmp = tmp.reset_index()
      df_prec_dev = pd.concat([df_prec_dev, tmp], ignore_index = True)
  df_prec_dev = pd.merge(df_prec_dev, df_mypf, on= 'Symbol')
  df_prec_dev = pd.merge(df_prec_dev, df_tmp, on= 'Symbol', how='left')
  df_prec_dev = pd.merge(df_prec_dev, df_rs, on= 'Symbol', how='left')
  #print(df_prec_dev.columns)
  df_prec_dev['Curr_PE'] = round(df_prec_dev['Close']/df_prec_dev['EPS'],1)
  df_prec_dev['Dev%_PE'] = round((df_prec_dev['Curr_PE'] - df_prec_dev['MedPE'])*100/df_prec_dev['MedPE'],2)
  df_prec_dev['Conviction'] = df_prec_dev['Conviction'] + '-' + df_prec_dev['CapType']
  return df_prec_dev

# function to arrange stock features
def arrange_features(df_stocks, common_cols, diff_cols):
  df_stocks_common = df_stocks[common_cols].drop_duplicates()
  df_stocks_diff = df_stocks[diff_cols]
  df_stocks_diff['Investment'] = df_stocks_diff['AvgCost'] * df_stocks_diff['Shares']
  df_stocks_diff = df_stocks_diff.groupby(['Symbol'])[['Shares', 'Investment']].aggregate(['sum']).reset_index()
  df_stocks_diff.columns = ['Symbol', 'Shares', 'Investment']
  df_stocks_diff['AvgCost'] = round(df_stocks_diff['Investment']/df_stocks_diff['Shares'],2)
  df_stocks = pd.merge(df_stocks_diff, df_stocks_common, on='Symbol')
  return df_stocks

# plot fact distribution across dimension
def plot_pie_chart(df, dimension, fact):
  # grouping the data by category and calculating the sum of fact for each type
  grouped_data = df.groupby(dimension)[fact].sum()

  # sorting the grouped data in descending order
  grouped_data = grouped_data.sort_values(ascending=False)

  # creating a pie chart
  grouped_data.plot.pie(autopct='%1.1f%%', startangle=90, figsize=(6, 6))

  # adding a title and displaying the plot
  plt.title(f'{dimension} {fact} Distribution')
  plt.ylabel('')  # To hide the y-label
  plt.show()

In [7]:
# function to get portfolio features

def get_portfolio_features(df_common_features):

  print_date_time()
  print('-------------------')

  #df_common_features["Target"] = df_common_features["Target"].fillna(df_common_features["Max"])
  df_common_features['NTT'] = np.where(df_common_features['Strategy']== 'NTT', df_common_features["Target"], df_common_features['Max'])
  df_common_features['LTT'] = np.where(df_common_features['Strategy']== 'BTT', df_common_features["Target"], df_common_features['Max'])
  df_common_features['BOL'] = df_common_features['Min']

  tmp_df = df_common_features[df_common_features['Symbol'].isin(mypf_df[mypf_df['InPortfolio'] != 'NA'].Symbol.values)]
  print('qualified stocks: '+str(len(tmp_df['Symbol'].unique())))
  tmp_df1 = tmp_df[tmp_df['LatestQtr'] == 1]
  print('with latest results: '+str(len(tmp_df1['Symbol'].unique())))
  tmp_df1 = tmp_df1[tmp_df1['StarStock'] == 1]
  print('still star stocks: '+str(len(tmp_df1['Symbol'].unique())))
  tmp_df['Investment'] = tmp_df['AvgCost'] * tmp_df['Shares']
  tmp_df['Current'] = round(tmp_df['Close'] * tmp_df['Shares'],0)
  tmp_df['Previous'] = tmp_df['Prev_Close'] * tmp_df['Shares']
  tmp_df['EstimatedST'] = tmp_df['NTT'] * tmp_df['Shares']
  tmp_df['EstimatedLT'] = tmp_df['LTT'] * tmp_df['Shares']
  tmp_df['Current P/L'] = round((tmp_df['Current'] - tmp_df['Investment']),0)
  tmp_df['Today P/L%'] = round((tmp_df['Current'] - tmp_df['Previous'])*100/tmp_df['Previous'],2)
  tmp_df['Current P/L%'] = round((tmp_df['Current'] - tmp_df['Investment'])*100/tmp_df['Investment'],2)
  tmp_df['EstimatedST P/L%'] = round((tmp_df['EstimatedST'] - tmp_df['Investment'])*100/tmp_df['Investment'],2)
  tmp_df['EstimatedLT P/L%'] = round((tmp_df['EstimatedLT'] - tmp_df['Investment'])*100/tmp_df['Investment'],2)
  tmp_df['NTT%'] = round((tmp_df['NTT'] - tmp_df['Close'])*100/tmp_df['Close'],2)
  tmp_df['LTT%'] = round((tmp_df['LTT'] - tmp_df['Close'])*100/tmp_df['Close'],2)
  tmp_df['Gained%'] = round((tmp_df['Close'] - tmp_df['BOL'])*100/tmp_df['BOL'],2)
  investment = round(sum(tmp_df['AvgCost']*tmp_df['Shares']),0)
  current = round(sum(tmp_df['Close']*tmp_df['Shares']),0)
  tmp_df['InitAlloc%'] = round(tmp_df['Investment']*100/investment,2)
  tmp_df['CurrAlloc%'] = round(tmp_df['Current']*100/current,2)
  tmp_df['FTT'] = tmp_df['LTT']
  tmp_df.loc[tmp_df['Strategy'] == 'NTT', 'FTT'] = tmp_df['NTT']
  tmp_df['FTT%'] = tmp_df['LTT%']
  tmp_df.loc[tmp_df['Strategy'] == 'NTT', 'FTT%'] = tmp_df['NTT%']
  tmp_df['FTT Amt'] = round(tmp_df['FTT%'] * tmp_df['Current']/100,0)
  tmp_df['OTT%'] = round((tmp_df['FTT'] - tmp_df['AvgCost'])*100/tmp_df['AvgCost'],2)
  tmp_df['RRR Ind'] = round(tmp_df['Current P/L']/tmp_df['FTT Amt'],2)
  tmp_df['Risk Ind'] = round(tmp_df['Current P/L%']*tmp_df['CurrAlloc%'],0)

  return tmp_df

# function to print portfolio features
def print_portfolio_stats(df_portfolio_features, myinvmt_df):
  from pyxirr import xirr

  total_booked_amt, reserve_amt, cy_booked_amt, py_booked_amt = get_amt()

  dates = myinvmt_df['Date'].values
  dates = np.append(dates, datetime.date.today().strftime('%d-%b-%y'))
  investment = myinvmt_df['Investment'].values
  dates= pd.to_datetime(dates)

  current = round(sum(df_portfolio_features['Close']*df_portfolio_features['Shares']),0) + reserve_amt
  investment_xirr = np.append(investment, current)
  cagr = round(xirr(pd.DataFrame({"dates": dates, "amounts": investment_xirr}))*100,2)

  investment = -sum(investment)
  invested = round(sum(df_portfolio_features['AvgCost']*df_portfolio_features['Shares']),0) + reserve_amt
  previous = round(sum(df_portfolio_features['Prev_Close']*df_portfolio_features['Shares']),0) + reserve_amt
  cy_invested = investment + py_booked_amt

  today_pnl_amount = current-previous
  today_pnl_percentage = round((current-previous)*100/previous,2)

  curr_pnl_amount = current-invested
  curr_pnl_percentage = round((curr_pnl_amount)*100/(cy_invested),2)

  cy_pnl_amount = cy_booked_amt + curr_pnl_amount
  cy_pnl_percentage = round((cy_pnl_amount)*100/cy_invested,2)

  overall_pnl_amount = total_booked_amt + curr_pnl_amount
  overall_pnl_percentage = round((overall_pnl_amount)*100/investment,2)

  estimate_st = round(sum(df_portfolio_features['FTT']*df_portfolio_features['Shares']),0)  + reserve_amt
  est_st_pnl_amount = estimate_st-current
  est_st_pnl_percentage = round((est_st_pnl_amount)*100/current,2)

  estimate_lt = round(sum(df_portfolio_features['LTT']*df_portfolio_features['Shares']),0)  + reserve_amt
  est_lt_pnl_amount = estimate_lt-current
  est_lt_pnl_percentage = round((est_lt_pnl_amount)*100/current,2)

  total_profit = round(sum(df_portfolio_features[df_portfolio_features['Current P/L%'] > 0]['Current']) - sum(df_portfolio_features[df_portfolio_features['Current P/L%'] > 0]['Investment']),0)
  total_loss = round(sum(df_portfolio_features[df_portfolio_features['Current P/L%'] < 0]['Current']) - sum(df_portfolio_features[df_portfolio_features['Current P/L%'] < 0]['Investment']),0)

  cy_booked_percentage = round((cy_booked_amt)*100/current,2)
  py_booked_percentage = round((py_booked_amt)*100/investment,2)
  total_booked_percentage = round((total_booked_amt)*100/investment,2)

  print('-------------------')
  print('Initial Investment: ', format_amt(investment))
  print('CY Investment: ', format_amt(cy_invested))
  print('Reserve: ', format_amt(reserve_amt))
  print('Current: ',  format_amt(current))
  print('-------------------')
  print('Today PnL: '+ '{} ({}%)'.format(format_amt(today_pnl_amount), today_pnl_percentage))
  print('Current PnL: '+ '{} ({}%)'.format(format_amt(curr_pnl_amount), curr_pnl_percentage))
  print('CY Booked + Current PnL: '+ '{} ({}%)'.format(format_amt(cy_pnl_amount), cy_pnl_percentage))
  print('-------------------')
  print('Total profit: ', format_amt(total_profit))
  print('Total loss: ', format_amt(total_loss))
  print('-------------------')
  print('Total Booked + Current PnL: '+ '{} ({}%)'.format(format_amt(overall_pnl_amount), overall_pnl_percentage))
  print('Total Booked PnL: '+ '{} ({}%)'.format(format_amt(total_booked_amt), total_booked_percentage))
  print('Curr Year Booked PnL: '+ '{} ({}%)'.format(format_amt(cy_booked_amt), cy_booked_percentage))
  print('Prev Year Booked PnL: '+ '{} ({}%)'.format(format_amt(py_booked_amt), py_booked_percentage))
  print('===================')
  print('Est FTT: ',  format_amt(estimate_st))
  print('Est FTT PnL: '+ '{} ({}%)'.format(format_amt(est_st_pnl_amount), est_st_pnl_percentage))

  print('===================')
  print('Deployed: ', format_amt(investment))

  print('Current: ', format_amt(current))

  print('CAGR/XIRR %: '+'{}%'.format(cagr))

In [8]:
# get start and end date
start_date, end_date = get_start_end_date()

# get portfolio and prospects data
mypfs_df = get_mypfs_df()
mypps_df = get_mypps_df()
myinvmt_df = get_myinvmt_df()

# merge above datasets
mypf_df = pd.merge(mypfs_df, mypps_df, on="Symbol")

# seggregate dm and sv portfolio
dm_pf = mypf_df[mypf_df['InPortfolio'] == 'DM']
sv_pf = mypf_df[mypf_df['InPortfolio'] == 'SV']

# build portfolio stock dataframe
dm_stocks = get_stock_ids(dm_pf)
sv_stocks = get_stock_ids(sv_pf)
df_stocks = pd.concat([dm_pf,sv_pf], ignore_index = True)

# arrange common and diff stock features
common_cols = ['Symbol', 'Target', 'Criteria', 'Strategy', 'CumlRnk', 'LatestQtr', 'StarStock', 'Conviction', 'Category', 'InFolio', 'XIRR', 'MBQ']
diff_cols = ['Symbol', 'AvgCost', 'Shares']
df_stocks = arrange_features(df_stocks, common_cols, diff_cols)

# get common features
stock_ids = df_stocks['Symbol'].values
df_common_features = get_common_features(stock_ids, df_stocks)

df_common_features.reset_index(drop=True, inplace=True)
df_common_features.drop(['Date'], axis=1, inplace=True)
# get and print portfolio features
df_portfolio_features = get_portfolio_features(df_common_features)

print_portfolio_stats(df_portfolio_features, myinvmt_df)

df = df_portfolio_features
#plot_pie_chart(df, 'CapType', 'Current')
list_ox40n = list(df[df['MBQ'].str.contains('OX40N', na=False)]['Symbol'].values)

Run date time (IST): 2026-07-23 10:54:00
-------------------
qualified stocks: 92
with latest results: 31
still star stocks: 20
-------------------
Initial Investment:  1.40 C
CY Investment:  1.82 C
Reserve:  1.49 K
Current:  1.52 C
-------------------
Today PnL: -20.03 K (-0.13%)
Current PnL: -31.41 L (-17.22%)
CY Booked + Current PnL: -29.33 L (-16.08%)
-------------------
Total profit:  4.47 L
Total loss:  -35.88 L
-------------------
Total Booked + Current PnL: 13.54 L (9.71%)
Total Booked PnL: 44.95 L (32.22%)
Curr Year Booked PnL: 2.08 L (1.37%)
Prev Year Booked PnL: 42.87 L (30.73%)
===================
Est FTT:  2.55 C
Est FTT PnL: 1.03 C (67.93%)
===================
Deployed:  1.40 C
Current:  1.52 C
CAGR/XIRR %: 3.78%

In [9]:
# top 5 near their targets
cols = ['Symbol', 'Today P/L%', 'Current P/L%', 'FTT%', 'OTT%', 'FTT Amt', 'Current P/L', 'Current', 'FTT', 'Dev%_PE', 'RSI_14','Conviction', 'Spread%',  'CumlRnk', 'RRR Ind', 'CurrAlloc%', 'Gained%', 'Criteria', 'Strategy', 'Category']
df_tmp = df_portfolio_features[~df_portfolio_features['Symbol'].isin(['ENRIN','BLUSPRING','DIGITIDE'])]
df_tmp = df_tmp.sort_values(by = 'FTT Amt', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
59,PIDILITIND,-0.05,13.12,3.89,17.52,6210.0,18520.0,159630.0,1658.32,-20.71,60.0,X-LC,8.20,5.0,2.98,1.05,26.24,X40,ATH,CHEMICALS
49,JSWINFRA,-4.37,12.17,3.79,16.43,9428.0,26998.0,248772.0,342.00,-3.93,53.0,X-MC,19.02,61.0,2.86,1.64,41.05,X40N,NTT,REALTY
73,SONACOMS,0.17,25.89,10.17,38.69,12951.0,26189.0,127348.0,801.69,-0.22,80.0,M-MC,25.59,193.0,2.02,0.84,80.67,AR,ATH,AUTO
83,TTKPRESTIG,-0.58,-15.20,18.03,0.09,15408.0,-15319.0,85458.0,770.00,98.29,62.0,M-SC,10.24,250.0,-0.99,0.56,52.17,OX40N,NTT,DURABLES
56,MEDANTA,2.90,18.18,7.56,27.12,15771.0,32089.0,208606.0,1486.00,14.62,67.0,X-SC,11.31,87.0,2.03,1.37,43.74,XY24,NTT,HEALTHCARE

In [10]:
# top 5 today
df_tmp = df_portfolio_features.sort_values(by = 'Today P/L%', ascending=False)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
77,TANLA,13.76,-27.80,200.88,117.25,392726.0,-75258.0,195503.0,1922.32,-26.90,72.0,H-SC,5.75,147.0,-0.19,1.29,71.17,AR,ATH,IT
67,ROUTE,6.41,-53.48,261.50,68.16,161863.0,-71168.0,61898.0,2215.45,-62.40,70.0,H-SC,9.18,141.0,-0.44,0.41,47.46,SR,ATH,IT
62,RAJOOENG,4.46,-45.37,155.54,39.61,87102.0,-46500.0,56000.0,143.10,-63.13,67.0,H-SC,20.46,136.0,-0.53,0.37,19.97,AR,ATH,MISC
23,DMART,3.51,-1.08,31.02,29.60,76588.0,-2700.0,246900.0,5391.45,-16.57,52.0,X-LC,1.96,14.0,-0.04,1.63,12.85,X40N,ATH,FMCG
69,SFL,3.27,-24.24,67.14,26.63,133380.0,-63558.0,198660.0,1287.00,50.46,59.0,M-SC,24.79,242.0,-0.48,1.31,65.80,XY24,NTT,MISC

In [11]:
# bottom 5 today
df_tmp = df_portfolio_features.sort_values(by = 'Today P/L%', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
44,INDUSINDBK,-5.15,-25.12,77.48,32.89,44790.0,-19398.0,57809.0,1800.0,-372.41,56.0,L-MC,13.29,258.0,-0.43,0.38,42.52,XR,NTT,BANKS
49,JSWINFRA,-4.37,12.17,3.79,16.43,9428.0,26998.0,248772.0,342.0,-3.93,53.0,X-MC,19.02,61.0,2.86,1.64,41.05,X40N,NTT,REALTY
88,VOLTAS,-3.16,2.97,41.00,45.20,80952.0,5703.0,197445.0,1856.0,17.89,49.0,X-MC,5.29,79.0,0.07,1.30,8.21,XY25,NTT,AC
2,ACC,-2.92,-39.70,189.91,74.81,307039.0,-106452.0,161676.0,3906.0,-57.46,46.0,X-SC,13.70,85.0,-0.35,1.07,8.01,XY24,BTT,CEMENT
66,REPCOHOME,-2.88,-16.24,126.63,89.82,303873.0,-46536.0,239969.0,880.0,-58.27,39.0,H-SC,4.45,161.0,-0.15,1.58,15.36,XY24,NTT,FINANCE

In [12]:
# top 5 to exit based on CumlRnk
df_tmp = df_portfolio_features[~df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])]
df_tmp = df_tmp[(df_tmp['Current P/L%'] > -1) & (df_tmp['Current P/L%'] < 1)].sort_values(by = 'CumlRnk', ascending=False)
df_tmp[cols].head()

Empty DataFrame
Columns: [Symbol, Today P/L%, Current P/L%, FTT%, OTT%, FTT Amt, Current P/L, Current, FTT, Dev%_PE, RSI_14, Conviction, Spread%, CumlRnk, RRR Ind, CurrAlloc%, Gained%, Criteria, Strategy, Category]
Index: []

In [13]:
# OX40N stocks to exit
df_tmp = df_portfolio_features[(df_portfolio_features['Symbol'].isin(list_ox40n))].sort_values(by = 'Current P/L%', ascending=False)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
25,FINCABLES,-0.63,27.73,62.77,107.91,118378.0,40946.0,188590.0,1641.55,14.66,40.0,M-SC,20.85,220.0,0.35,1.24,41.88,OX40N,ATH,CABLES
72,SIS,-0.25,1.13,19.90,21.26,22346.0,1257.0,112289.0,528.00,2682.38,60.0,H-SC,24.63,168.0,0.06,0.74,66.96,OX40N,NTT,MISC
83,TTKPRESTIG,-0.58,-15.20,18.03,0.09,15408.0,-15319.0,85458.0,770.00,98.29,62.0,M-SC,10.24,250.0,-0.99,0.56,52.17,OX40N,NTT,DURABLES
16,CERA,-1.86,-20.04,54.95,23.89,77284.0,-35258.0,140645.0,9475.00,-22.91,48.0,H-SC,14.91,153.0,-0.46,0.93,36.72,OX40N,NTT,CERAMICS
69,SFL,3.27,-24.24,67.14,26.63,133380.0,-63558.0,198660.0,1287.00,50.46,59.0,M-SC,24.79,242.0,-0.48,1.31,65.80,XY24,NTT,MISC

In [14]:
# top 5 to book for rotation
df_tmp = df_portfolio_features[(df_portfolio_features['Current P/L%'] > 20) ].sort_values(by = 'CumlRnk', ascending=False)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
25,FINCABLES,-0.63,27.73,62.77,107.91,118378.0,40946.0,188590.0,1641.55,14.66,40.0,M-SC,20.85,220.0,0.35,1.24,41.88,OX40N,ATH,CABLES
73,SONACOMS,0.17,25.89,10.17,38.69,12951.0,26189.0,127348.0,801.69,-0.22,80.0,M-MC,25.59,193.0,2.02,0.84,80.67,AR,ATH,AUTO
68,SATIN,-0.60,42.36,6.66,51.83,26195.0,117030.0,393314.0,274.00,27.46,55.0,H-SC,44.98,159.0,4.47,2.59,91.60,XY24,NTT,FINANCE
60,QUESS,-1.05,21.61,43.00,73.90,55843.0,23074.0,129867.0,424.00,-34.44,68.0,X-SC,32.34,80.0,0.41,0.86,77.04,XY24,NTT,MISC

In [15]:
# top 5 to monitor for exit
df_tmp = df_portfolio_features[~df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])]
df_tmp = df_tmp[(df_tmp['Current P/L%'] > 0) ].sort_values(by = 'Dev%_PE', ascending=False)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
72,SIS,-0.25,1.13,19.90,21.26,22346.0,1257.0,112289.0,528.00,2682.38,60.0,H-SC,24.63,168.0,0.06,0.74,66.96,OX40N,NTT,MISC
75,SURYODAY,-2.75,5.47,16.65,23.03,31447.0,9802.0,188873.0,216.00,106.14,57.0,H-SC,22.50,166.0,0.31,1.24,60.32,XR,NTT,BANKS
74,STARHEALTH,-2.32,11.27,32.35,47.26,101191.0,31677.0,312800.0,761.00,75.71,49.0,H-SC,18.88,173.0,0.31,2.06,35.74,XY24,NTT,INSURANCE
68,SATIN,-0.60,42.36,6.66,51.83,26195.0,117030.0,393314.0,274.00,27.46,55.0,H-SC,44.98,159.0,4.47,2.59,91.60,XY24,NTT,FINANCE
25,FINCABLES,-0.63,27.73,62.77,107.91,118378.0,40946.0,188590.0,1641.55,14.66,40.0,M-SC,20.85,220.0,0.35,1.24,41.88,OX40N,ATH,CABLES

In [16]:
# top 5 to book for rotation from weak conviction
df_tmp = df_portfolio_features[~df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])]
df_tmp = df_tmp[~df_tmp['Criteria'].isin(['XY25','XY24','X40', 'X40N'])].sort_values(by = 'RRR Ind', ascending=False)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
73,SONACOMS,0.17,25.89,10.17,38.69,12951.0,26189.0,127348.0,801.69,-0.22,80.0,M-MC,25.59,193.0,2.02,0.84,80.67,AR,ATH,AUTO
91,ZYDUSLIFE,-0.09,18.66,14.30,35.63,35563.0,39117.0,248691.0,1286.17,3.15,51.0,H-MC,17.29,120.0,1.10,1.64,30.76,AR,ATH,PHARMA
25,FINCABLES,-0.63,27.73,62.77,107.91,118378.0,40946.0,188590.0,1641.55,14.66,40.0,M-SC,20.85,220.0,0.35,1.24,41.88,OX40N,ATH,CABLES
75,SURYODAY,-2.75,5.47,16.65,23.03,31447.0,9802.0,188873.0,216.00,106.14,57.0,H-SC,22.50,166.0,0.31,1.24,60.32,XR,NTT,BANKS
72,SIS,-0.25,1.13,19.90,21.26,22346.0,1257.0,112289.0,528.00,2682.38,60.0,H-SC,24.63,168.0,0.06,0.74,66.96,OX40N,NTT,MISC

In [17]:
# top 5 to accumulate based on lowest RSI_14
df_tmp = df_portfolio_features[df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])].sort_values(by = 'RSI_14', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
39,ICICIGI,-1.67,-15.42,40.56,18.89,68652.0,-30848.0,169261.0,2244.41,-28.90,30.0,X-MC,6.23,66.0,-0.45,1.12,0.00,X40,ATH,INSURANCE
87,VBL,0.84,-6.66,45.02,35.37,132728.0,-21022.0,294820.0,670.16,-17.53,34.0,X-LC,7.21,13.0,-0.16,1.94,21.17,X40N,ATH,FMCG
81,TMPV,-0.06,-25.45,83.21,36.58,220735.0,-90566.0,265275.0,600.00,-84.72,35.0,X-LC,7.62,4.0,-0.41,1.75,11.49,XY24,NTT,AUTO
34,HDFCBANK,-0.78,-10.60,43.58,28.37,91514.0,-24894.0,209991.0,1073.00,-23.99,35.0,X-LC,10.78,26.0,-0.27,1.38,3.84,X40,BTT,BANKS
35,HDFCLIFE,-0.39,-9.89,47.27,32.71,63806.0,-14817.0,134983.0,811.41,-29.68,39.0,X-LC,15.62,31.0,-0.23,0.89,1.41,X40,ATH,INSURANCE

In [18]:
# top 5 to accumulate based on Spread and CumlRnk
df_tmp = df_portfolio_features[df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])]
df_tmp = df_tmp[(df_tmp['CumlRnk'] < 100)].sort_values(by = 'Spread%', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
11,BERGEPAINT,-0.92,-7.53,35.53,25.32,84679.0,-19418.0,238331.0,680.00,-12.57,48.0,X-MC,1.78,68.0,-0.23,1.57,24.04,XY24,NTT,PAINTS
19,COLPAL,1.14,-19.62,74.01,39.86,156664.0,-51685.0,211680.0,3683.41,-2.71,60.0,X-MC,1.90,62.0,-0.33,1.39,19.74,XY25,ATH,FMCG
23,DMART,3.51,-1.08,31.02,29.60,76588.0,-2700.0,246900.0,5391.45,-16.57,52.0,X-LC,1.96,14.0,-0.04,1.63,12.85,X40N,ATH,FMCG
1,ABBOTINDIA,-0.16,-3.54,22.40,18.07,38647.0,-6325.0,172530.0,35195.00,-17.90,75.0,X-MC,2.70,58.0,-0.16,1.14,14.20,X40,ATH,PHARMA
17,CIPLA,-1.29,14.48,16.56,33.43,29036.0,22175.0,175336.0,1648.14,-11.50,47.0,X-LC,3.17,18.0,0.76,1.16,19.70,X40N,ATH,PHARMA

In [19]:
# top 5 to accumulate based on lowest Gained%
df_tmp = df_portfolio_features[df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])].sort_values(by = 'Gained%', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
39,ICICIGI,-1.67,-15.42,40.56,18.89,68652.0,-30848.0,169261.0,2244.41,-28.90,30.0,X-MC,6.23,66.0,-0.45,1.12,0.00,X40,ATH,INSURANCE
35,HDFCLIFE,-0.39,-9.89,47.27,32.71,63806.0,-14817.0,134983.0,811.41,-29.68,39.0,X-LC,15.62,31.0,-0.23,0.89,1.41,X40,ATH,INSURANCE
65,RELIANCE,-0.26,-17.50,51.88,25.30,86012.0,-35172.0,165791.0,1952.00,-19.65,44.0,X-LC,7.49,21.0,-0.41,1.09,2.10,XY25,BTT,REFINERIES
47,ITC,0.62,-25.58,59.97,19.06,151823.0,-87001.0,253165.0,452.00,-59.16,47.0,X-LC,12.64,1.0,-0.57,1.67,2.54,X40,NTT,FMCG
58,PGHH,-0.54,-32.93,96.81,32.01,138647.0,-70304.0,143216.0,17616.87,-54.64,49.0,X-MC,19.97,57.0,-0.51,0.94,2.64,X40,ATH,FMCG

In [20]:
# top 5 to accumulate based on lowest CurrAlloc%
df_tmp = df_portfolio_features[df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])].sort_values(by = 'CurrAlloc%', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
10,BATAINDIA,-0.90,-55.61,204.58,35.20,116848.0,-71554.0,57116.0,2096.00,-25.05,48.0,X-SC,17.51,91.0,-0.61,0.38,13.28,X40,NTT,FOOTWEAR
64,RELAXO,-1.03,-48.54,195.96,52.31,146386.0,-70458.0,74702.0,1176.00,-45.21,53.0,X-SC,11.54,92.0,-0.48,0.49,67.02,X40N,NTT,FOOTWEAR
60,QUESS,-1.05,21.61,43.00,73.90,55843.0,23074.0,129867.0,424.00,-34.44,68.0,X-SC,32.34,80.0,0.41,0.86,77.04,XY24,NTT,MISC
35,HDFCLIFE,-0.39,-9.89,47.27,32.71,63806.0,-14817.0,134983.0,811.41,-29.68,39.0,X-LC,15.62,31.0,-0.23,0.89,1.41,X40,ATH,INSURANCE
51,KOTAKBANK,0.81,2.67,17.75,20.90,25236.0,3700.0,142172.0,452.46,-12.01,49.0,X-LC,4.54,12.0,0.15,0.94,8.92,X40,ATH,BANKS

In [21]:
# top 5 to accumulate based on CumlRnk
df_tmp = df_portfolio_features.sort_values(by = 'CumlRnk', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
47,ITC,0.62,-25.58,59.97,19.06,151823.0,-87001.0,253165.0,452.00,-59.16,47.0,X-LC,12.64,1.0,-0.57,1.67,2.54,X40,NTT,FMCG
79,TCS,0.46,-34.87,90.70,24.20,273656.0,-161557.0,301716.0,4230.71,-44.94,57.0,X-LC,19.49,2.0,-0.59,1.99,12.51,X40,ATH,IT
45,INFY,-0.67,-28.86,88.71,34.24,197455.0,-90303.0,222585.0,1972.00,-44.12,43.0,X-LC,20.74,3.0,-0.46,1.47,6.06,X40,NTT,IT
81,TMPV,-0.06,-25.45,83.21,36.58,220735.0,-90566.0,265275.0,600.00,-84.72,35.0,X-LC,7.62,4.0,-0.41,1.75,11.49,XY24,NTT,AUTO
59,PIDILITIND,-0.05,13.12,3.89,17.52,6210.0,18520.0,159630.0,1658.32,-20.71,60.0,X-LC,8.20,5.0,2.98,1.05,26.24,X40,ATH,CHEMICALS

In [22]:
# top 5 for average up
df_tmp = df_portfolio_features[(df_portfolio_features['Dev%_200'] > 5)].sort_values(by = 'CurrAlloc%', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
44,INDUSINDBK,-5.15,-25.12,77.48,32.89,44790.0,-19398.0,57809.0,1800.00,-372.41,56.0,L-MC,13.29,258.0,-0.43,0.38,42.52,XR,NTT,BANKS
64,RELAXO,-1.03,-48.54,195.96,52.31,146386.0,-70458.0,74702.0,1176.00,-45.21,53.0,X-SC,11.54,92.0,-0.48,0.49,67.02,X40N,NTT,FOOTWEAR
3,ALKYLAMINE,1.24,-20.80,143.10,92.54,114433.0,-20996.0,79967.0,4520.85,-15.24,54.0,H-SC,12.05,142.0,-0.18,0.53,51.85,SR,ATH,CHEMICALS
83,TTKPRESTIG,-0.58,-15.20,18.03,0.09,15408.0,-15319.0,85458.0,770.00,98.29,62.0,M-SC,10.24,250.0,-0.99,0.56,52.17,OX40N,NTT,DURABLES
72,SIS,-0.25,1.13,19.90,21.26,22346.0,1257.0,112289.0,528.00,2682.38,60.0,H-SC,24.63,168.0,0.06,0.74,66.96,OX40N,NTT,MISC

In [23]:
# top 5 RSP
df_tmp = df_portfolio_features.sort_values(by = 'RSP', ascending=False)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
77,TANLA,13.76,-27.80,200.88,117.25,392726.0,-75258.0,195503.0,1922.32,-26.90,72.0,H-SC,5.75,147.0,-0.19,1.29,71.17,AR,ATH,IT
73,SONACOMS,0.17,25.89,10.17,38.69,12951.0,26189.0,127348.0,801.69,-0.22,80.0,M-MC,25.59,193.0,2.02,0.84,80.67,AR,ATH,AUTO
60,QUESS,-1.05,21.61,43.00,73.90,55843.0,23074.0,129867.0,424.00,-34.44,68.0,X-SC,32.34,80.0,0.41,0.86,77.04,XY24,NTT,MISC
83,TTKPRESTIG,-0.58,-15.20,18.03,0.09,15408.0,-15319.0,85458.0,770.00,98.29,62.0,M-SC,10.24,250.0,-0.99,0.56,52.17,OX40N,NTT,DURABLES
22,DIXON,0.73,1.88,35.38,37.92,94003.0,4898.0,265696.0,18931.72,-56.71,62.0,X-MC,7.53,54.0,0.05,1.75,44.57,X40N,ATH,IT

In [24]:
# Top N allocation
df_tmp = df_portfolio_features.sort_values(by = 'CurrAlloc%', ascending=False)
top_n_values = [10, 25, 50]

sum_df = pd.DataFrame({
    'Top_N': top_n_values,
    'Sum_Alloc%': [df_tmp['CurrAlloc%'].head(n).sum() for n in top_n_values]
})

sum_df

   Top_N  Sum_Alloc%
0     10       19.07
1     25       42.20
2     50       72.58

In [25]:
# market-cap-wise allocation
df_tmp = df_portfolio_features[cols]
df_tmp.groupby(df_tmp['Conviction'].str[-2:])['CurrAlloc%'].sum().sort_values(ascending=False)

Conviction
SC    43.48
LC    30.16
MC    26.36
Name: CurrAlloc%, dtype: float64

In [26]:
# criteria-wise allocation
df_portfolio_features.groupby('Criteria')['CurrAlloc%'].sum().sort_values(ascending=False)

Criteria
XY24     27.29
X40      24.74
X40N     17.50
XR        8.83
AR        7.17
OX40N     7.03
XY25      6.50
SR        0.94
Name: CurrAlloc%, dtype: float64

In [27]:
# conviction-wise allocation
df_portfolio_features.groupby('Conviction')['CurrAlloc%'].sum().sort_values(ascending=False)

Conviction
X-LC    28.14
H-SC    22.79
X-MC    21.14
X-SC    10.18
M-SC     9.97
H-MC     2.70
M-MC     2.14
H-LC     1.22
M-LC     0.80
L-SC     0.54
L-MC     0.38
Name: CurrAlloc%, dtype: float64

In [28]:
# sector-wise stats
df_tmp = df_portfolio_features.groupby('Category')[['CurrAlloc%', 'Current', 'Current P/L', 'FTT Amt']].sum().sort_values(by=['Current', 'Current P/L'], ascending=False)
df_tmp['Current P/L%'] = round(df_tmp['Current P/L'] * 100 / df_tmp['Current'], 2)
df_tmp['FTT%'] = round(df_tmp['FTT Amt'] * 100 / df_tmp['Current'], 2)
cols = ['CurrAlloc%', 'Current P/L%', 'FTT%']
df_tmp[cols].sort_values(by=['CurrAlloc%'], ascending=False)

               CurrAlloc%  Current P/L%    FTT%
Category
FMCG                14.39        -21.07   63.54
FINANCE             11.20         -8.44   55.42
IT                  10.28        -44.45  115.94
MISC                 7.31        -20.87   72.73
AUTO                 6.68         -8.11   48.42
BANKS                5.45         -9.66   60.33
PAINTS               5.39        -20.23   40.73
PHARMA               5.29          7.49   21.15
INSURANCE            5.14         -6.30   42.15
ELECTRICAL           4.16        -12.06   51.49
CHEMICALS            2.17        -23.16   95.86
HEALTHCARE           2.13        -10.66   39.54
APPARELS             1.84          4.04   28.19
AC                   1.79        -17.76   49.68
FOOTWEAR             1.70        -71.25  139.91
REALTY               1.64         10.85    3.79
DURABLES             1.63        -56.08   94.04
BREWERIES            1.62          4.58   15.23
TRAVEL               1.50        -97.07  195.75
CERAMICS             1.42        -43.08   86.54
CABLES               1.24         21.71   62.77
ENGINEERING          1.24        -28.52   87.30
JEWELLERY            1.12        -87.60  152.78
REFINERIES           1.09        -21.21   51.88
CEMENT               1.07        -65.84  189.91
ENTERTAINMENT        0.72        -79.03  185.81
TEXTILES             0.41        -47.45   89.50
HOTELS               0.38        -95.18  164.03

In [29]:
# money to be made criteria-wise
df_portfolio_features.groupby('Criteria')['FTT Amt'].agg(['sum', 'count']).sort_values(by='sum', ascending=False)

                sum  count
Criteria
XY24      3455287.0     21
X40       1915097.0     19
XR        1335778.0     13
AR        1088270.0      9
X40N      1065031.0     13
OX40N      725807.0     10
XY25       447308.0      5
SR         276296.0      2

In [30]:
# money to be made conviction-wise
df_portfolio_features.groupby('Conviction')['FTT Amt'].agg(['sum', 'count']).sort_values(by='sum', ascending=False)

                  sum  count
Conviction
H-SC        3313339.0     24
X-LC        2000733.0     21
X-MC        1508655.0     15
M-SC        1405592.0     14
X-SC        1258223.0      9
H-MC         288921.0      2
L-SC         208527.0      2
M-LC         170847.0      1
M-MC          60491.0      2
H-LC          48756.0      1
L-MC          44790.0      1

In [31]:
# money to be made criteria and conviction-wise
df_portfolio_features.groupby(['Conviction', 'Criteria'])['FTT Amt'].agg(['sum', 'count']).sort_values(by='sum', ascending=False)

                           sum  count
Conviction Criteria
X-LC       X40       1044234.0     10
H-SC       XY24      1031646.0      6
           AR         914346.0      5
M-SC       XY24       823747.0      6
H-SC       XR         789967.0      7
X-SC       XY24       740885.0      4
X-MC       X40        661246.0      7
X-LC       X40N       381955.0      6
X-MC       X40N       375355.0      4
X-LC       XY24       371213.0      2
M-SC       OX40N      311622.0      5
X-SC       X40N       307721.0      3
H-SC       OX40N      301084.0      4
           SR         276296.0      2
H-MC       XY24       253358.0      1
X-MC       XY25       237616.0      2
           XY24       234438.0      2
X-SC       X40        209617.0      2
M-SC       XR         193569.0      2
M-LC       XR         170847.0      1
X-LC       XY25       162152.0      2
L-SC       OX40N      113101.0      1
           XR          95426.0      1
M-SC       AR          76654.0      1
H-LC       AR          48756.0      1
M-MC       XY25        47540.0      1
L-MC       XR          44790.0      1
X-LC       XR          41179.0      1
H-MC       AR          35563.0      1
M-MC       AR          12951.0      1

In [32]:
# notebook execution time

end_time = time.time()
execution_time = round(end_time - start_time, 0)
print(f"Notebook execution time: {execution_time} seconds")

Notebook execution time: 28.0 seconds