<a href="https://colab.research.google.com/github/ankit-rathi/Quantvesting_v2/blob/main/myStocks_Portfolio_Analysis.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
'''
!pip install pandas==2.2.2 -qq
!pip install pyxirr -qq
!pip install ta -qq
!pip install yfinance==0.2.59 -qq
'''

'\n!pip install pandas==2.2.2 -qq\n!pip install pyxirr -qq\n!pip install ta -qq\n!pip install yfinance==0.2.59 -qq\n'

In [2]:
# import libraries

import numpy as np
import pandas as pd
import datetime
import warnings
warnings.filterwarnings('ignore')
import yfinance as yfin
import ta
import matplotlib.pyplot as plt
import requests

In [3]:
# notebook start time
import time
import datetime
import pytz

start_time = time.time()

# function to print date timestamp
def print_date_time():
  tz_NY = pytz.timezone('Asia/Kolkata')
  datetime_NY = datetime.datetime.now(tz_NY)
  print("Run date time (IST):", datetime_NY.strftime("%Y-%m-%d %H:%M:%S"))

In [4]:
# function to get booked and reserved amount
def get_amt():
  # fetch the JSON data from the URL
  url = "https://raw.githubusercontent.com/ankit-rathi/Tradevesting_v1/main/data/myPortfolioAmts.json"
  response = requests.get(url)
  pf_amts = response.json()  # parse the JSON data

  # extract values from the JSON
  py_booked_amt_dm = pf_amts["py_booked_amt_dm"]
  py_booked_amt_sv = pf_amts["py_booked_amt_sv"]
  cy_booked_amt_dm = pf_amts["cy_booked_amt_dm"]
  cy_booked_amt_sv = pf_amts["cy_booked_amt_sv"]
  reserve_amt_dm = pf_amts["reserve_amt_dm"]
  reserve_amt_sv = pf_amts["reserve_amt_sv"]

  # perform calculations
  py_booked_amt = py_booked_amt_dm + py_booked_amt_sv
  cy_booked_amt = cy_booked_amt_dm + cy_booked_amt_sv
  reserve_amt = reserve_amt_dm + reserve_amt_sv
  total_booked_amt = py_booked_amt + cy_booked_amt

  return total_booked_amt, reserve_amt, cy_booked_amt, py_booked_amt

gen_output = 0

In [5]:
# function to format the amount
def format_amt(number):
    abs_number = abs(number)

    if abs_number >= 1_00_00_000:  # Crores
        formatted_amt = f"{number / 1_00_00_000:.2f} C"
    elif abs_number >= 1_00_000:  # Lakhs
        formatted_amt = f"{number / 1_00_000:.2f} L"
    elif abs_number >= 1_000:  # Thousands
        formatted_amt = f"{number / 1_000:.2f} K"
    else:
        formatted_amt = f"{number:.2f}"

    return formatted_amt

# function to set start and end date
def get_start_end_date():
  start_date = (datetime.date.today() + datetime.timedelta(days=-365)).strftime('%Y-%m-%d')
  end_date = (datetime.date.today() + datetime.timedelta(days=1)).strftime('%Y-%m-%d')
  return start_date, end_date

# function to fetch my portfolio csv
def get_mypfs_df():
  mypfs_df = pd.read_csv('https://raw.githubusercontent.com/ankit-rathi/Tradevesting_v1/main/data/myPortfolioStocks.csv')
  return mypfs_df

# function to fetch my prospects csv
def get_mypps_df():
  mypps_df = pd.read_csv('https://raw.githubusercontent.com/ankit-rathi/Tradevesting_v1/main/data/myProspectsScrips.csv')
  return mypps_df

# function to fetch screener data
def get_myscreen_df():
  myscreen_df = pd.read_csv('https://raw.githubusercontent.com/ankit-rathi/Tradevesting_v1/main/data/myScreenerDB.csv')
  return myscreen_df

# function to fetch momentum data
def get_myinvmt_df():
  myinvmt_df = pd.read_csv('https://raw.githubusercontent.com/ankit-rathi/Tradevesting_v1/main/data/myInvestments.csv')
  return myinvmt_df

# function to get the stock ids
def get_stock_ids(df_pf):
  stock_n100 = df_pf['Symbol'].unique()

  exclude = ['CADILAHC','MMTC', 'MASFIN']

  stock_ids = df_pf[~df_pf['Symbol'].isin(exclude) ]['Symbol'].unique()

  #mypf = mypf[mypf.Forecast.notnull()]
  #stock_ids = mypf['Symbol'].unique()

  #stock_ids.sort()
  return stock_ids

# get features from screener data
def get_screener_features():
  myscreen_df = get_myscreen_df()
  cols = ['Symbol', 'EPS', 'MedPE', 'ROCE%', 'ROE%', 'CapType']
  return myscreen_df[cols]

# get relative strength
def get_relative_strength(stock_list):

    # Dictionary to store stock tickers and their corresponding percentage price change
    stock_changes = {}

    # Loop through each stock and fetch its price data
    for stock in stock_list:
        try:
            # Download the stock data for the given date range
            stock_data = yfin.Ticker(stock + '.NS').history(period='1mo', interval='1d')[map(str.title, ['open', 'close', 'low', 'high', 'volume'])]

            # Calculate the percentage change for the stock
            if len(stock_data) > 0:
                start_price = stock_data['Close'].iloc[0]
                end_price = stock_data['Close'].iloc[-1]
                percent_change = round(((end_price - start_price) / start_price) * 100, 2)
                stock_changes[stock] = percent_change
            else:
                stock_changes[stock] = np.nan  # If no data is available, set to NaN

        except Exception as e:
            print(f"Error fetching data for {stock}: {e}")
            stock_changes[stock] = np.nan

    # Create a DataFrame with stock tickers and their percentage changes
    df = pd.DataFrame(list(stock_changes.items()), columns=['Symbol', 'Percent_Change'])

    # Drop any stocks with missing data (NaN values)
    df = df.dropna()

    # Calculate the percentile rank based on percentage change
    df['RSP'] = round(df['Percent_Change'].rank(pct=True) * 100, 2)
    cols = ['Symbol', 'RSP']
    df = df[cols]
    # Sort by percentile rank (optional)
    df = df.sort_values(by='RSP', ascending=False).reset_index(drop=True)

    return df

In [6]:
# function to get stock technicals
def stock_prec_dev(stock_symbol):
    #stock_symbol = 'ULTRACEMCO.NS'
    short_window = 20
    mid_window = 50
    long_window = 200
    moving_avg = 'SMA'

    start = datetime.datetime(*map(int, start_date.split('-')))
    end = datetime.datetime(*map(int, end_date.split('-')))

    stock_df = yfin.Ticker(stock_symbol + '.NS').history(period='max', interval='1d')[map(str.title, ['open', 'close', 'low', 'high', 'volume'])]

    stock_df['Max'] = round(max(stock_df['Close']),2)
    stock_df = stock_df[(stock_df.index <= end_date) & (stock_df.index >= start_date)]
    stock_df['200_SMA'] = round(stock_df['Close'].rolling(window = 200, min_periods = 1).mean(),0)
    stock_df['Dev%_200'] = round((stock_df['Close'] - stock_df['200_SMA'])*100/stock_df['200_SMA'],2)
    stock_df.dropna(axis = 0, inplace = True) # remove any null rows

    stock_df['20_SMA'] = stock_df['Close'].rolling(window=20).mean()
    stock_df['50_SMA'] = stock_df['Close'].rolling(window=50).mean()
    stock_df['Symbol'] = stock_symbol

    stock_df['Close'] = round(stock_df['Close'],2)
    stock_df['Min'] = round(min(stock_df['Close']),2)
    stock_df['RSI_14'] = ta.momentum.RSIIndicator(close=stock_df['Close'], window=14).rsi()
    stock_df['RSI_14'] = round(stock_df['RSI_14'],0)
    stock_df['Prev_Close'] = stock_df['Close'].shift(1)
    stock_df.drop(['Open', 'Low', 'High', 'Volume'], axis=1, inplace=True)
    stock_df = stock_df.tail(1)

    max_SMA = max(stock_df['20_SMA'].item(), stock_df['50_SMA'].item(), stock_df['200_SMA'].item())
    min_SMA = min(stock_df['20_SMA'].item(), stock_df['50_SMA'].item(), stock_df['200_SMA'].item())
    ABS_Spread = max_SMA - min_SMA
    stock_df['Spread%'] = round((ABS_Spread / stock_df['200_SMA'].item()) * 100,2)

    return stock_df

# function to compute stock attributes
def get_common_features(stock_ids, df_mypf):

  df_prec_dev = pd.DataFrame()
  df_tmp = get_screener_features()
  df_rs = get_relative_strength(stock_ids)

  for stock_id in stock_ids:
      tmp = stock_prec_dev(stock_id)
      tmp = tmp.reset_index()
      df_prec_dev = pd.concat([df_prec_dev, tmp], ignore_index = True)
  df_prec_dev = pd.merge(df_prec_dev, df_mypf, on= 'Symbol')
  df_prec_dev = pd.merge(df_prec_dev, df_tmp, on= 'Symbol', how='left')
  df_prec_dev = pd.merge(df_prec_dev, df_rs, on= 'Symbol', how='left')
  #print(df_prec_dev.columns)
  df_prec_dev['Curr_PE'] = round(df_prec_dev['Close']/df_prec_dev['EPS'],1)
  df_prec_dev['Dev%_PE'] = round((df_prec_dev['Curr_PE'] - df_prec_dev['MedPE'])*100/df_prec_dev['MedPE'],2)
  df_prec_dev['Conviction'] = df_prec_dev['Conviction'] + '-' + df_prec_dev['CapType']
  return df_prec_dev

# function to arrange stock features
def arrange_features(df_stocks, common_cols, diff_cols):
  df_stocks_common = df_stocks[common_cols].drop_duplicates()
  df_stocks_diff = df_stocks[diff_cols]
  df_stocks_diff['Investment'] = df_stocks_diff['AvgCost'] * df_stocks_diff['Shares']
  df_stocks_diff = df_stocks_diff.groupby(['Symbol'])[['Shares', 'Investment']].aggregate(['sum']).reset_index()
  df_stocks_diff.columns = ['Symbol', 'Shares', 'Investment']
  df_stocks_diff['AvgCost'] = round(df_stocks_diff['Investment']/df_stocks_diff['Shares'],2)
  df_stocks = pd.merge(df_stocks_diff, df_stocks_common, on='Symbol')
  return df_stocks

# plot fact distribution across dimension
def plot_pie_chart(df, dimension, fact):
  # grouping the data by category and calculating the sum of fact for each type
  grouped_data = df.groupby(dimension)[fact].sum()

  # sorting the grouped data in descending order
  grouped_data = grouped_data.sort_values(ascending=False)

  # creating a pie chart
  grouped_data.plot.pie(autopct='%1.1f%%', startangle=90, figsize=(6, 6))

  # adding a title and displaying the plot
  plt.title(f'{dimension} {fact} Distribution')
  plt.ylabel('')  # To hide the y-label
  plt.show()

In [7]:
# function to get portfolio features

def get_portfolio_features(df_common_features):

  print_date_time()
  print('-------------------')

  #df_common_features["Target"] = df_common_features["Target"].fillna(df_common_features["Max"])
  df_common_features['NTT'] = np.where(df_common_features['Strategy']== 'NTT', df_common_features["Target"], df_common_features['Max'])
  df_common_features['LTT'] = np.where(df_common_features['Strategy']== 'BTT', df_common_features["Target"], df_common_features['Max'])
  df_common_features['BOL'] = df_common_features['Min']

  tmp_df = df_common_features[df_common_features['Symbol'].isin(mypf_df[mypf_df['InPortfolio'] != 'NA'].Symbol.values)]
  print('qualified stocks: '+str(len(tmp_df['Symbol'].unique())))
  tmp_df1 = tmp_df[tmp_df['LatestQtr'] == 1]
  print('with latest results: '+str(len(tmp_df1['Symbol'].unique())))
  tmp_df1 = tmp_df1[tmp_df1['StarStock'] == 1]
  print('still star stocks: '+str(len(tmp_df1['Symbol'].unique())))
  tmp_df['Investment'] = tmp_df['AvgCost'] * tmp_df['Shares']
  tmp_df['Current'] = round(tmp_df['Close'] * tmp_df['Shares'],0)
  tmp_df['Previous'] = tmp_df['Prev_Close'] * tmp_df['Shares']
  tmp_df['EstimatedST'] = tmp_df['NTT'] * tmp_df['Shares']
  tmp_df['EstimatedLT'] = tmp_df['LTT'] * tmp_df['Shares']
  tmp_df['Current P/L'] = round((tmp_df['Current'] - tmp_df['Investment']),0)
  tmp_df['Today P/L%'] = round((tmp_df['Current'] - tmp_df['Previous'])*100/tmp_df['Previous'],2)
  tmp_df['Current P/L%'] = round((tmp_df['Current'] - tmp_df['Investment'])*100/tmp_df['Investment'],2)
  tmp_df['EstimatedST P/L%'] = round((tmp_df['EstimatedST'] - tmp_df['Investment'])*100/tmp_df['Investment'],2)
  tmp_df['EstimatedLT P/L%'] = round((tmp_df['EstimatedLT'] - tmp_df['Investment'])*100/tmp_df['Investment'],2)
  tmp_df['NTT%'] = round((tmp_df['NTT'] - tmp_df['Close'])*100/tmp_df['Close'],2)
  tmp_df['LTT%'] = round((tmp_df['LTT'] - tmp_df['Close'])*100/tmp_df['Close'],2)
  tmp_df['Gained%'] = round((tmp_df['Close'] - tmp_df['BOL'])*100/tmp_df['BOL'],2)
  investment = round(sum(tmp_df['AvgCost']*tmp_df['Shares']),0)
  current = round(sum(tmp_df['Close']*tmp_df['Shares']),0)
  tmp_df['InitAlloc%'] = round(tmp_df['Investment']*100/investment,2)
  tmp_df['CurrAlloc%'] = round(tmp_df['Current']*100/current,2)
  tmp_df['FTT'] = tmp_df['LTT']
  tmp_df.loc[tmp_df['Strategy'] == 'NTT', 'FTT'] = tmp_df['NTT']
  tmp_df['FTT%'] = tmp_df['LTT%']
  tmp_df.loc[tmp_df['Strategy'] == 'NTT', 'FTT%'] = tmp_df['NTT%']
  tmp_df['FTT Amt'] = round(tmp_df['FTT%'] * tmp_df['Current']/100,0)
  tmp_df['OTT%'] = round((tmp_df['FTT'] - tmp_df['AvgCost'])*100/tmp_df['AvgCost'],2)
  tmp_df['RRR Ind'] = round(tmp_df['Current P/L']/tmp_df['FTT Amt'],2)
  tmp_df['Risk Ind'] = round(tmp_df['Current P/L%']*tmp_df['CurrAlloc%'],0)

  return tmp_df

# function to print portfolio features
def print_portfolio_stats(df_portfolio_features, myinvmt_df):
  from pyxirr import xirr

  total_booked_amt, reserve_amt, cy_booked_amt, py_booked_amt = get_amt()

  dates = myinvmt_df['Date'].values
  dates = np.append(dates, datetime.date.today().strftime('%d-%b-%y'))
  investment = myinvmt_df['Investment'].values
  dates= pd.to_datetime(dates)

  current = round(sum(df_portfolio_features['Close']*df_portfolio_features['Shares']),0) + reserve_amt
  investment_xirr = np.append(investment, current)
  cagr = round(xirr(pd.DataFrame({"dates": dates, "amounts": investment_xirr}))*100,2)

  investment = -sum(investment)
  invested = round(sum(df_portfolio_features['AvgCost']*df_portfolio_features['Shares']),0) + reserve_amt
  previous = round(sum(df_portfolio_features['Prev_Close']*df_portfolio_features['Shares']),0) + reserve_amt
  cy_invested = investment + py_booked_amt

  today_pnl_amount = current-previous
  today_pnl_percentage = round((current-previous)*100/previous,2)

  curr_pnl_amount = current-invested
  curr_pnl_percentage = round((curr_pnl_amount)*100/(cy_invested),2)

  cy_pnl_amount = cy_booked_amt + curr_pnl_amount
  cy_pnl_percentage = round((cy_pnl_amount)*100/cy_invested,2)

  overall_pnl_amount = total_booked_amt + curr_pnl_amount
  overall_pnl_percentage = round((overall_pnl_amount)*100/investment,2)

  estimate_st = round(sum(df_portfolio_features['FTT']*df_portfolio_features['Shares']),0)  + reserve_amt
  est_st_pnl_amount = estimate_st-current
  est_st_pnl_percentage = round((est_st_pnl_amount)*100/current,2)

  estimate_lt = round(sum(df_portfolio_features['LTT']*df_portfolio_features['Shares']),0)  + reserve_amt
  est_lt_pnl_amount = estimate_lt-current
  est_lt_pnl_percentage = round((est_lt_pnl_amount)*100/current,2)

  total_profit = round(sum(df_portfolio_features[df_portfolio_features['Current P/L%'] > 0]['Current']) - sum(df_portfolio_features[df_portfolio_features['Current P/L%'] > 0]['Investment']),0)
  total_loss = round(sum(df_portfolio_features[df_portfolio_features['Current P/L%'] < 0]['Current']) - sum(df_portfolio_features[df_portfolio_features['Current P/L%'] < 0]['Investment']),0)

  cy_booked_percentage = round((cy_booked_amt)*100/current,2)
  py_booked_percentage = round((py_booked_amt)*100/investment,2)
  total_booked_percentage = round((total_booked_amt)*100/investment,2)

  print('-------------------')
  print('Initial Investment: ', format_amt(investment))
  print('CY Investment: ', format_amt(cy_invested))
  print('Reserve: ', format_amt(reserve_amt))
  print('Current: ',  format_amt(current))
  print('-------------------')
  print('Today PnL: '+ '{} ({}%)'.format(format_amt(today_pnl_amount), today_pnl_percentage))
  print('Current PnL: '+ '{} ({}%)'.format(format_amt(curr_pnl_amount), curr_pnl_percentage))
  print('CY Booked + Current PnL: '+ '{} ({}%)'.format(format_amt(cy_pnl_amount), cy_pnl_percentage))
  print('-------------------')
  print('Total profit: ', format_amt(total_profit))
  print('Total loss: ', format_amt(total_loss))
  print('-------------------')
  print('Total Booked + Current PnL: '+ '{} ({}%)'.format(format_amt(overall_pnl_amount), overall_pnl_percentage))
  print('Total Booked PnL: '+ '{} ({}%)'.format(format_amt(total_booked_amt), total_booked_percentage))
  print('Curr Year Booked PnL: '+ '{} ({}%)'.format(format_amt(cy_booked_amt), cy_booked_percentage))
  print('Prev Year Booked PnL: '+ '{} ({}%)'.format(format_amt(py_booked_amt), py_booked_percentage))
  print('===================')
  print('Est FTT: ',  format_amt(estimate_st))
  print('Est FTT PnL: '+ '{} ({}%)'.format(format_amt(est_st_pnl_amount), est_st_pnl_percentage))

  print('===================')
  print('Deployed: ', format_amt(investment))

  print('Current: ', format_amt(current))

  print('CAGR/XIRR %: '+'{}%'.format(cagr))

In [8]:
# get start and end date
start_date, end_date = get_start_end_date()

# get portfolio and prospects data
mypfs_df = get_mypfs_df()
mypps_df = get_mypps_df()
myinvmt_df = get_myinvmt_df()

# merge above datasets
mypf_df = pd.merge(mypfs_df, mypps_df, on="Symbol")

# seggregate dm and sv portfolio
dm_pf = mypf_df[mypf_df['InPortfolio'] == 'DM']
sv_pf = mypf_df[mypf_df['InPortfolio'] == 'SV']

# build portfolio stock dataframe
dm_stocks = get_stock_ids(dm_pf)
sv_stocks = get_stock_ids(sv_pf)
df_stocks = pd.concat([dm_pf,sv_pf], ignore_index = True)

# arrange common and diff stock features
common_cols = ['Symbol', 'Target', 'Criteria', 'Strategy', 'CumlRnk', 'LatestQtr', 'StarStock', 'Conviction', 'Category', 'InFolio', 'XIRR', 'MBQ']
diff_cols = ['Symbol', 'AvgCost', 'Shares']
df_stocks = arrange_features(df_stocks, common_cols, diff_cols)

# get common features
stock_ids = df_stocks['Symbol'].values
df_common_features = get_common_features(stock_ids, df_stocks)

df_common_features.reset_index(drop=True, inplace=True)
df_common_features.drop(['Date'], axis=1, inplace=True)
# get and print portfolio features
df_portfolio_features = get_portfolio_features(df_common_features)

print_portfolio_stats(df_portfolio_features, myinvmt_df)

df = df_portfolio_features
#plot_pie_chart(df, 'CapType', 'Current')
list_ox40n = list(df[df['MBQ'].str.contains('OX40N', na=False)]['Symbol'].values)

Run date time (IST): 2026-03-09 15:37:36
-------------------
qualified stocks: 86
with latest results: 26
still star stocks: 15
-------------------
Initial Investment:  1.36 C
CY Investment:  1.62 C
Reserve:  66.25 K
Current:  1.35 C
-------------------
Today PnL: -2.43 L (-1.76%)
Current PnL: -41.67 L (-25.65%)
CY Booked + Current PnL: -25.99 L (-16.0%)
-------------------
Total profit:  95.54 K
Total loss:  -42.63 L
-------------------
Total Booked + Current PnL: 98.77 K (0.73%)
Total Booked PnL: 42.66 L (31.48%)
Curr Year Booked PnL: 15.68 L (11.59%)
Prev Year Booked PnL: 26.98 L (19.91%)
===================
Est FTT:  2.47 C
Est FTT PnL: 1.12 C (82.83%)
===================
Deployed:  1.36 C
Current:  1.35 C
CAGR/XIRR %: -0.09%

In [9]:
# top 5 near their targets
cols = ['Symbol', 'Today P/L%', 'Current P/L%', 'FTT%', 'OTT%', 'FTT Amt', 'Current P/L', 'Current', 'FTT', 'Dev%_PE', 'RSI_14','Conviction', 'Spread%',  'CumlRnk', 'RRR Ind', 'CurrAlloc%', 'Gained%', 'Criteria', 'Strategy', 'Category']
df_tmp = df_portfolio_features[~df_portfolio_features['Symbol'].isin(['ENRIN','BLUSPRING','DIGITIDE'])]
df_tmp = df_tmp.sort_values(by = 'FTT Amt', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
19,COALINDIA,-0.64,7.62,9.34,17.67,15124.0,11470.0,161930.0,478.51,29.12,57.0,L-LC,11.30,185.0,0.76,1.20,25.75,XY25,ATH,MINING
50,MASFIN,0.12,-7.76,31.80,21.57,28739.0,-7605.0,90375.0,397.04,-20.51,35.0,H-SC,5.46,167.0,-0.26,0.67,26.10,XR,ATH,FINANCE
37,ICICIGI,0.50,0.10,19.22,19.34,38499.0,199.0,200308.0,2252.93,-15.91,48.0,X-MC,1.54,66.0,0.01,1.49,14.24,X40,ATH,INSURANCE
77,TTKPRESTIG,-3.65,-41.27,70.43,0.09,41685.0,-41591.0,59186.0,770.00,37.46,17.0,M-SC,14.29,250.0,-1.00,0.44,0.00,OX40N,NTT,DURABLES
2,ABBOTINDIA,-0.51,-8.80,29.46,18.07,48052.0,-15745.0,163110.0,35195.00,-22.40,52.0,X-MC,11.09,58.0,-0.33,1.21,3.40,X40,ATH,PHARMA

In [10]:
# top 5 today
df_tmp = df_portfolio_features.sort_values(by = 'Today P/L%', ascending=False)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
40,INDIAMART,2.97,-6.17,120.32,106.72,139242.0,-7610.0,115726.0,4810.62,-57.62,51.0,H-SC,8.84,140.0,-0.05,0.86,15.76,AR,ATH,MISC
25,DMART,2.33,-4.66,35.93,29.60,85503.0,-11628.0,237972.0,5391.45,-19.60,60.0,X-LC,7.70,14.0,-0.14,1.77,10.06,X40N,ATH,FMCG
84,WIPRO,1.71,-18.48,111.32,72.27,153767.0,-31317.0,138131.0,420.00,-26.43,28.0,M-LC,13.27,98.0,-0.20,1.03,1.71,XR,NTT,IT
70,SYMPHONY,1.60,-41.29,70.28,-0.03,70610.0,-70671.0,100470.0,1306.00,-52.91,30.0,M-SC,12.04,205.0,-1.00,0.75,1.60,OX40N,NTT,DURABLES
69,SURYODAY,1.39,-25.36,64.84,23.03,86666.0,-45410.0,133661.0,216.00,44.74,52.0,H-SC,7.10,166.0,-0.52,0.99,32.62,XR,NTT,BANKS

In [11]:
# bottom 5 today
df_tmp = df_portfolio_features.sort_values(by = 'Today P/L%', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
4,ALKYLAMINE,-5.56,-44.38,248.14,93.63,139341.0,-44809.0,56154.0,4546.37,-40.38,18.0,H-SC,20.08,142.0,-0.32,0.42,0.00,SR,ATH,CHEMICALS
75,TMPV,-5.35,-24.43,80.72,36.58,217072.0,-86921.0,268920.0,600.00,-84.72,30.0,X-LC,2.68,4.0,-0.40,2.00,0.00,XY24,NTT,AUTO
7,ATULAUTO,-5.14,-27.16,99.86,45.57,143381.0,-53550.0,143582.0,844.00,3094.59,37.0,M-SC,7.28,248.0,-0.37,1.07,8.66,XY24,NTT,AUTO
55,RAJESHEXPO,-5.00,-78.18,358.61,0.07,107339.0,-107245.0,29932.0,518.00,997.22,18.0,L-SC,15.34,268.0,-1.00,0.22,0.00,OX40N,NTT,JEWELLERY
11,BANDHANBNK,-4.87,-16.24,129.73,92.42,302687.0,-45238.0,233321.0,400.00,100.43,54.0,H-SC,9.83,174.0,-0.15,1.73,28.53,XY24,NTT,BANKS

In [12]:
# top 5 to exit based on CumlRnk
df_tmp = df_portfolio_features[~df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])]
df_tmp = df_tmp[(df_tmp['Current P/L%'] > -1) & (df_tmp['Current P/L%'] < 1)].sort_values(by = 'CumlRnk', ascending=False)
df_tmp[cols].head()

Empty DataFrame
Columns: [Symbol, Today P/L%, Current P/L%, FTT%, OTT%, FTT Amt, Current P/L, Current, FTT, Dev%_PE, RSI_14, Conviction, Spread%, CumlRnk, RRR Ind, CurrAlloc%, Gained%, Criteria, Strategy, Category]
Index: []

In [13]:
# OX40N stocks to exit
df_tmp = df_portfolio_features[(df_portfolio_features['Symbol'].isin(list_ox40n))].sort_values(by = 'Current P/L%', ascending=False)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
27,FINCABLES,-0.66,21.91,70.55,107.91,126982.0,32344.0,179988.0,1641.55,9.59,70.0,M-SC,7.22,220.0,0.25,1.34,35.41,OX40N,ATH,CABLES
66,SIS,-3.94,-34.28,84.52,21.26,61673.0,-38064.0,72968.0,528.00,1708.29,32.0,H-SC,8.36,168.0,-0.62,0.54,0.59,OX40N,NTT,MISC
72,TATAELXSI,-0.61,-37.98,112.86,32.03,92286.0,-50065.0,81770.0,9161.00,-22.38,26.0,H-SC,15.14,158.0,-0.54,0.61,0.00,OX40N,NTT,IT
48,KANSAINER,-2.04,-38.15,83.46,13.47,139209.0,-102870.0,166797.0,340.00,-46.84,23.0,H-SC,15.60,162.0,-0.74,1.24,0.00,XY24,NTT,PAINTS
41,INDIGOPNTS,-4.03,-40.45,67.96,0.02,70644.0,-70610.0,103949.0,1408.00,58.48,15.0,M-SC,14.86,222.0,-1.00,0.77,0.00,OX40N,NTT,PAINTS

In [14]:
# top 5 to book for rotation
df_tmp = df_portfolio_features[(df_portfolio_features['Current P/L%'] > 20) ].sort_values(by = 'CumlRnk', ascending=False)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
27,FINCABLES,-0.66,21.91,70.55,107.91,126982.0,32344.0,179988.0,1641.55,9.59,70.0,M-SC,7.22,220.0,0.25,1.34,35.41,OX40N,ATH,CABLES

In [15]:
# top 5 to monitor for exit
df_tmp = df_portfolio_features[~df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])]
df_tmp = df_tmp[(df_tmp['Current P/L%'] > 0) ].sort_values(by = 'Dev%_PE', ascending=False)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
19,COALINDIA,-0.64,7.62,9.34,17.67,15124.0,11470.0,161930.0,478.51,29.12,57.0,L-LC,11.30,185.0,0.76,1.20,25.75,XY25,ATH,MINING
27,FINCABLES,-0.66,21.91,70.55,107.91,126982.0,32344.0,179988.0,1641.55,9.59,70.0,M-SC,7.22,220.0,0.25,1.34,35.41,OX40N,ATH,CABLES
1,ABB,-1.31,9.76,32.62,45.57,93672.0,25541.0,287160.0,7934.00,-29.43,58.0,H-MC,9.38,125.0,0.27,2.13,27.52,AR,NTT,ELECTRICAL

In [16]:
# top 5 to book for rotation from weak conviction
df_tmp = df_portfolio_features[~df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])]
df_tmp = df_tmp[~df_tmp['Criteria'].isin(['XY25','XY24','X40', 'X40N'])].sort_values(by = 'RRR Ind', ascending=False)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
1,ABB,-1.31,9.76,32.62,45.57,93672.0,25541.0,287160.0,7934.00,-29.43,58.0,H-MC,9.38,125.0,0.27,2.13,27.52,AR,NTT,ELECTRICAL
27,FINCABLES,-0.66,21.91,70.55,107.91,126982.0,32344.0,179988.0,1641.55,9.59,70.0,M-SC,7.22,220.0,0.25,1.34,35.41,OX40N,ATH,CABLES
40,INDIAMART,2.97,-6.17,120.32,106.72,139242.0,-7610.0,115726.0,4810.62,-57.62,51.0,H-SC,8.84,140.0,-0.05,0.86,15.76,AR,ATH,MISC
85,ZYDUSLIFE,-0.46,-4.16,41.52,35.63,83395.0,-8718.0,200856.0,1286.17,-16.67,50.0,H-MC,5.11,120.0,-0.10,1.49,11.82,AR,ATH,PHARMA
84,WIPRO,1.71,-18.48,111.32,72.27,153767.0,-31317.0,138131.0,420.00,-26.43,28.0,M-LC,13.27,98.0,-0.20,1.03,1.71,XR,NTT,IT

In [17]:
# top 5 to accumulate based on lowest RSI_14
df_tmp = df_portfolio_features[df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])].sort_values(by = 'RSI_14', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
8,AWL,-0.93,-39.53,176.20,67.02,379642.0,-140848.0,215461.0,485.00,-67.43,11.0,X-SC,21.77,81.0,-0.37,1.60,0.0,XY24,NTT,FMCG
53,PGHH,-2.58,-20.54,66.13,32.01,112199.0,-43856.0,169664.0,17616.87,-46.32,13.0,X-MC,10.60,57.0,-0.39,1.26,0.0,X40,ATH,FMCG
3,ACC,-3.38,-35.08,169.29,74.81,294666.0,-94068.0,174060.0,3906.00,-53.87,17.0,X-SC,11.17,85.0,-0.32,1.29,0.0,XY24,BTT,CEMENT
12,BATAINDIA,-3.52,-53.71,192.11,35.20,114415.0,-69113.0,59557.0,2096.00,-21.88,20.0,X-SC,24.19,91.0,-0.60,0.44,0.0,X40,NTT,FOOTWEAR
58,RELAXO,-3.36,-59.72,278.14,52.31,162623.0,-86692.0,58468.0,1176.00,-57.12,21.0,X-SC,17.57,92.0,-0.53,0.43,0.0,X40N,NTT,FOOTWEAR

In [18]:
# top 5 to accumulate based on Spread and CumlRnk
df_tmp = df_portfolio_features[df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])]
df_tmp = df_tmp[(df_tmp['CumlRnk'] < 100)].sort_values(by = 'Spread%', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
22,DABUR,-2.49,-8.75,57.49,43.70,130129.0,-21718.0,226350.0,735.00,-17.25,27.0,X-MC,0.96,70.0,-0.17,1.68,4.98,XY24,BTT,FMCG
78,UNITDSPR,-2.45,-0.40,21.26,20.77,49578.0,-946.0,233198.0,1644.00,-11.71,46.0,X-MC,1.53,64.0,-0.02,1.73,6.28,X40N,NTT,BREWERIES
37,ICICIGI,0.50,0.10,19.22,19.34,38499.0,199.0,200308.0,2252.93,-15.91,48.0,X-MC,1.54,66.0,0.01,1.49,14.24,X40,ATH,INSURANCE
59,RELIANCE,1.37,-8.59,37.08,25.30,68114.0,-17267.0,183696.0,1952.00,-10.80,51.0,X-LC,2.06,21.0,-0.25,1.36,22.65,XY25,BTT,REFINERIES
75,TMPV,-5.35,-24.43,80.72,36.58,217072.0,-86921.0,268920.0,600.00,-84.72,30.0,X-LC,2.68,4.0,-0.40,2.00,0.00,XY24,NTT,AUTO

In [19]:
# top 5 to accumulate based on lowest Gained%
df_tmp = df_portfolio_features[df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])].sort_values(by = 'Gained%', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
3,ACC,-3.38,-35.08,169.29,74.81,294666.0,-94068.0,174060.0,3906.00,-53.87,17.0,X-SC,11.17,85.0,-0.32,1.29,0.0,XY24,BTT,CEMENT
10,BAJAJHLDNG,-2.94,-8.35,40.99,29.22,71425.0,-15875.0,174250.0,14451.52,-15.20,31.0,X-LC,11.90,28.0,-0.22,1.29,0.0,X40,ATH,FINANCE
9,BAJAJHFL,-1.47,-25.95,118.94,62.13,240488.0,-70853.0,202193.0,181.50,-39.10,22.0,X-MC,18.02,60.0,-0.29,1.50,0.0,X40N,ATH,FINANCE
8,AWL,-0.93,-39.53,176.20,67.02,379642.0,-140848.0,215461.0,485.00,-67.43,11.0,X-SC,21.77,81.0,-0.37,1.60,0.0,XY24,NTT,FMCG
12,BATAINDIA,-3.52,-53.71,192.11,35.20,114415.0,-69113.0,59557.0,2096.00,-21.88,20.0,X-SC,24.19,91.0,-0.60,0.44,0.0,X40,NTT,FOOTWEAR

In [20]:
# top 5 to accumulate based on lowest CurrAlloc%
df_tmp = df_portfolio_features[df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])].sort_values(by = 'CurrAlloc%', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
58,RELAXO,-3.36,-59.72,278.14,52.31,162623.0,-86692.0,58468.0,1176.00,-57.12,21.0,X-SC,17.57,92.0,-0.53,0.43,0.00,X40N,NTT,FOOTWEAR
12,BATAINDIA,-3.52,-53.71,192.11,35.20,114415.0,-69113.0,59557.0,2096.00,-21.88,20.0,X-SC,24.19,91.0,-0.60,0.44,0.00,X40,NTT,FOOTWEAR
54,QUESS,-2.47,-24.09,129.09,73.90,104647.0,-25728.0,81065.0,424.00,-59.23,32.0,X-SC,17.67,80.0,-0.25,0.60,0.00,XY24,NTT,MISC
36,HONAUT,-0.88,-22.99,96.49,51.31,143288.0,-44338.0,148500.0,58357.33,-35.94,29.0,X-SC,13.34,90.0,-0.31,1.10,0.00,X40N,ATH,ELECTRICAL
65,SIEMENS,-1.22,-13.25,44.68,25.51,72134.0,-24650.0,161445.0,4671.50,35.65,51.0,H-LC,3.40,51.0,-0.34,1.20,18.89,AR,ATH,ELECTRICAL

In [21]:
# top 5 to accumulate based on CumlRnk
df_tmp = df_portfolio_features.sort_values(by = 'CumlRnk', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
45,ITC,-1.19,-19.40,47.71,19.06,130809.0,-65990.0,274176.0,452.00,-55.92,33.0,X-LC,16.96,1.0,-0.50,2.04,0.00,X40,NTT,FMCG
73,TCS,-1.18,-25.80,70.59,26.57,242636.0,-119547.0,343726.0,4311.58,-37.07,25.0,X-LC,12.52,2.0,-0.49,2.55,0.00,X40,ATH,IT
43,INFY,0.50,-10.48,49.96,34.24,139935.0,-32793.0,280095.0,1972.00,-29.61,31.0,X-LC,10.85,3.0,-0.23,2.08,3.10,X40,NTT,IT
75,TMPV,-5.35,-24.43,80.72,36.58,217072.0,-86921.0,268920.0,600.00,-84.72,30.0,X-LC,2.68,4.0,-0.40,2.00,0.00,XY24,NTT,AUTO
34,HCLTECH,0.14,-11.83,40.45,23.83,86280.0,-28624.0,213300.0,1908.19,-7.36,28.0,X-LC,8.69,8.0,-0.33,1.58,2.34,X40,ATH,IT

In [22]:
# top 5 for average up
df_tmp = df_portfolio_features[(df_portfolio_features['Dev%_200'] > 5)].sort_values(by = 'CurrAlloc%', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
42,INDUSINDBK,-3.99,-34.94,104.27,32.89,52373.0,-26978.0,50228.0,1800.00,-336.69,37.0,L-MC,11.89,258.0,-0.52,0.37,38.33,XR,NTT,BANKS
19,COALINDIA,-0.64,7.62,9.34,17.67,15124.0,11470.0,161930.0,478.51,29.12,57.0,L-LC,11.30,185.0,0.76,1.20,25.75,XY25,ATH,MINING
27,FINCABLES,-0.66,21.91,70.55,107.91,126982.0,32344.0,179988.0,1641.55,9.59,70.0,M-SC,7.22,220.0,0.25,1.34,35.41,OX40N,ATH,CABLES
11,BANDHANBNK,-4.87,-16.24,129.73,92.42,302687.0,-45238.0,233321.0,400.00,100.43,54.0,H-SC,9.83,174.0,-0.15,1.73,28.53,XY24,NTT,BANKS
1,ABB,-1.31,9.76,32.62,45.57,93672.0,25541.0,287160.0,7934.00,-29.43,58.0,H-MC,9.38,125.0,0.27,2.13,27.52,AR,NTT,ELECTRICAL

In [23]:
# top 5 RSP
df_tmp = df_portfolio_features.sort_values(by = 'RSP', ascending=False)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
27,FINCABLES,-0.66,21.91,70.55,107.91,126982.0,32344.0,179988.0,1641.55,9.59,70.0,M-SC,7.22,220.0,0.25,1.34,35.41,OX40N,ATH,CABLES
11,BANDHANBNK,-4.87,-16.24,129.73,92.42,302687.0,-45238.0,233321.0,400.00,100.43,54.0,H-SC,9.83,174.0,-0.15,1.73,28.53,XY24,NTT,BANKS
26,EASEMYTRIP,-3.74,-60.21,266.16,45.70,187257.0,-106460.0,70355.0,26.40,-27.06,41.0,M-SC,18.16,204.0,-0.57,0.52,15.92,XY24,NTT,TRAVEL
65,SIEMENS,-1.22,-13.25,44.68,25.51,72134.0,-24650.0,161445.0,4671.50,35.65,51.0,H-LC,3.40,51.0,-0.34,1.20,18.89,AR,ATH,ELECTRICAL
1,ABB,-1.31,9.76,32.62,45.57,93672.0,25541.0,287160.0,7934.00,-29.43,58.0,H-MC,9.38,125.0,0.27,2.13,27.52,AR,NTT,ELECTRICAL

In [24]:
# Top N allocation
df_tmp = df_portfolio_features.sort_values(by = 'CurrAlloc%', ascending=False)
top_n_values = [10, 25, 50]

sum_df = pd.DataFrame({
    'Top_N': top_n_values,
    'Sum_Alloc%': [df_tmp['CurrAlloc%'].head(n).sum() for n in top_n_values]
})

sum_df

   Top_N  Sum_Alloc%
0     10       20.59
1     25       45.40
2     50       78.00

In [25]:
# market-cap-wise allocation
df_tmp = df_portfolio_features[cols]
df_tmp.groupby(df_tmp['Conviction'].str[-2:])['CurrAlloc%'].sum().sort_values(ascending=False)

Conviction
SC    44.37
MC    30.40
LC    25.20
Name: CurrAlloc%, dtype: float64

In [26]:
# criteria-wise allocation
df_portfolio_features.groupby('Criteria')['CurrAlloc%'].sum().sort_values(ascending=False)

Criteria
XY24     27.14
X40      24.07
X40N     15.09
AR        9.05
XY25      8.72
XR        8.22
OX40N     6.91
SR        0.77
Name: CurrAlloc%, dtype: float64

In [27]:
# conviction-wise allocation
df_portfolio_features.groupby('Conviction')['CurrAlloc%'].sum().sort_values(ascending=False)

Conviction
X-MC    23.12
X-LC    21.77
H-SC    21.47
X-SC    12.09
M-SC    10.21
H-MC     4.93
M-MC     1.98
H-LC     1.20
L-LC     1.20
M-LC     1.03
L-SC     0.60
L-MC     0.37
Name: CurrAlloc%, dtype: float64

In [28]:
# sector-wise stats
df_tmp = df_portfolio_features.groupby('Category')[['CurrAlloc%', 'Current', 'Current P/L', 'FTT Amt']].sum().sort_values(by=['Current', 'Current P/L'], ascending=False)
df_tmp['Current P/L%'] = round(df_tmp['Current P/L'] * 100 / df_tmp['Current'], 2)
df_tmp['FTT%'] = round(df_tmp['FTT Amt'] * 100 / df_tmp['Current'], 2)
cols = ['CurrAlloc%', 'Current P/L%', 'FTT%']
df_tmp[cols].sort_values(by=['CurrAlloc%'], ascending=False)

               CurrAlloc%  Current P/L%    FTT%
Category
FMCG                15.45        -20.16   62.82
FINANCE             12.74        -25.30   76.36
IT                  11.67        -43.35  116.30
MISC                 6.92        -43.76  106.21
ELECTRICAL           6.51        -10.48   52.78
PAINTS               5.22        -40.07   64.40
INSURANCE            4.76         -6.02   42.30
PHARMA               4.20         -3.93   36.64
AUTO                 3.72        -30.79   82.69
BANKS                3.09        -28.19  105.88
AC                   2.14        -10.83   40.87
HEALTHCARE           1.96        -35.42   70.76
FOOTWEAR             1.88        -73.60  143.21
TRAVEL               1.83        -81.60  172.53
DURABLES             1.79        -61.22  100.44
BREWERIES            1.73         -0.41   21.26
APPARELS             1.62        -23.10   65.09
REALTY               1.48        -11.65   29.99
REFINERIES           1.36         -9.40   37.08
CABLES               1.34         17.97   70.55
CERAMICS             1.34        -70.69  122.55
CEMENT               1.29        -54.04  169.29
MINING               1.20          7.08    9.34
ENGINEERING          1.11        -62.24  136.44
JEWELLERY            1.09       -116.71  192.01
CHEMICALS            0.95       -107.37  276.55
ENTERTAINMENT        0.78        -85.80  196.62
TEXTILES             0.42        -62.53  108.88
HOTELS               0.38       -124.18  203.26

In [29]:
# money to be made criteria-wise
df_portfolio_features.groupby('Criteria')['FTT Amt'].agg(['sum', 'count']).sort_values(by='sum', ascending=False)

                sum  count
Criteria
XY24      3942988.0     21
X40       1632004.0     15
XR        1384883.0     12
AR        1353693.0     10
X40N      1268047.0     10
OX40N      862655.0     10
XY25       442801.0      6
SR         315968.0      2

In [30]:
# money to be made conviction-wise
df_portfolio_features.groupby('Conviction')['FTT Amt'].agg(['sum', 'count']).sort_values(by='sum', ascending=False)

                  sum  count
Conviction
H-SC        3903826.0     24
X-MC        1621369.0     15
X-SC        1552097.0     10
M-SC        1543967.0     14
X-LC        1543347.0     12
H-MC         414792.0      3
L-SC         210290.0      2
M-LC         153767.0      1
M-MC         119953.0      2
H-LC          72134.0      1
L-MC          52373.0      1
L-LC          15124.0      1

In [31]:
# money to be made criteria and conviction-wise
df_portfolio_features.groupby(['Conviction', 'Criteria'])['FTT Amt'].agg(['sum', 'count']).sort_values(by='sum', ascending=False)

                           sum  count
Conviction Criteria
H-SC       XY24      1336834.0      6
           AR         975204.0      5
M-SC       XY24       912472.0      6
H-SC       XR         885358.0      7
X-SC       XY24       838800.0      4
X-LC       X40        797507.0      6
X-MC       X40        631462.0      7
           X40N       523061.0      4
X-SC       X40N       510262.0      4
H-SC       OX40N      390462.0      4
X-LC       XY24       370273.0      2
M-SC       OX40N      364854.0      5
H-SC       SR         315968.0      2
X-MC       XY24       246884.0      2
H-MC       XY24       237725.0      1
X-LC       X40N       234724.0      2
X-MC       XY25       219962.0      2
X-SC       X40        203035.0      2
M-SC       XR         190434.0      2
H-MC       AR         177067.0      2
M-LC       XR         153767.0      1
X-LC       XY25       140843.0      2
L-SC       OX40N      107339.0      1
           XR         102951.0      1
M-SC       AR          76207.0      1
H-LC       AR          72134.0      1
M-MC       XY25        66872.0      1
           AR          53081.0      1
L-MC       XR          52373.0      1
L-LC       XY25        15124.0      1

In [32]:
# notebook execution time

end_time = time.time()
execution_time = round(end_time - start_time, 0)
print(f"Notebook execution time: {execution_time} seconds")

Notebook execution time: 27.0 seconds