<a href="https://colab.research.google.com/github/ankit-rathi/Quantvesting_v2/blob/main/myStocks_Portfolio_Analysis.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
'''
!pip install pandas==2.2.2 -qq
!pip install pyxirr -qq
!pip install ta -qq
!pip install yfinance==0.2.59 -qq
'''

'\n!pip install pandas==2.2.2 -qq\n!pip install pyxirr -qq\n!pip install ta -qq\n!pip install yfinance==0.2.59 -qq\n'

In [2]:
# import libraries

import numpy as np
import pandas as pd
import datetime
import warnings
warnings.filterwarnings('ignore')
import yfinance as yfin
import ta
import matplotlib.pyplot as plt
import requests

In [3]:
# notebook start time
import time
import datetime
import pytz

start_time = time.time()

# function to print date timestamp
def print_date_time():
  tz_NY = pytz.timezone('Asia/Kolkata')
  datetime_NY = datetime.datetime.now(tz_NY)
  print("Run date time (IST):", datetime_NY.strftime("%Y-%m-%d %H:%M:%S"))

In [4]:
# function to get booked and reserved amount
def get_amt():
  # fetch the JSON data from the URL
  url = "https://raw.githubusercontent.com/ankit-rathi/Tradevesting_v1/main/data/myPortfolioAmts.json"
  response = requests.get(url)
  pf_amts = response.json()  # parse the JSON data

  # extract values from the JSON
  py_booked_amt_dm = pf_amts["py_booked_amt_dm"]
  py_booked_amt_sv = pf_amts["py_booked_amt_sv"]
  cy_booked_amt_dm = pf_amts["cy_booked_amt_dm"]
  cy_booked_amt_sv = pf_amts["cy_booked_amt_sv"]
  reserve_amt_dm = pf_amts["reserve_amt_dm"]
  reserve_amt_sv = pf_amts["reserve_amt_sv"]

  # perform calculations
  py_booked_amt = py_booked_amt_dm + py_booked_amt_sv
  cy_booked_amt = cy_booked_amt_dm + cy_booked_amt_sv
  reserve_amt = reserve_amt_dm + reserve_amt_sv
  total_booked_amt = py_booked_amt + cy_booked_amt

  return total_booked_amt, reserve_amt, cy_booked_amt, py_booked_amt

gen_output = 0

In [5]:
# function to format the amount
def format_amt(number):
    abs_number = abs(number)

    if abs_number >= 1_00_00_000:  # Crores
        formatted_amt = f"{number / 1_00_00_000:.2f} C"
    elif abs_number >= 1_00_000:  # Lakhs
        formatted_amt = f"{number / 1_00_000:.2f} L"
    elif abs_number >= 1_000:  # Thousands
        formatted_amt = f"{number / 1_000:.2f} K"
    else:
        formatted_amt = f"{number:.2f}"

    return formatted_amt

# function to set start and end date
def get_start_end_date():
  start_date = (datetime.date.today() + datetime.timedelta(days=-365)).strftime('%Y-%m-%d')
  end_date = (datetime.date.today() + datetime.timedelta(days=1)).strftime('%Y-%m-%d')
  return start_date, end_date

# function to fetch my portfolio csv
def get_mypfs_df():
  mypfs_df = pd.read_csv('https://raw.githubusercontent.com/ankit-rathi/Tradevesting_v1/main/data/myPortfolioStocks.csv')
  return mypfs_df

# function to fetch my prospects csv
def get_mypps_df():
  mypps_df = pd.read_csv('https://raw.githubusercontent.com/ankit-rathi/Tradevesting_v1/main/data/myProspectsScrips.csv')
  return mypps_df

# function to fetch screener data
def get_myscreen_df():
  myscreen_df = pd.read_csv('https://raw.githubusercontent.com/ankit-rathi/Tradevesting_v1/main/data/myScreenerDB.csv')
  return myscreen_df

# function to fetch momentum data
def get_myinvmt_df():
  myinvmt_df = pd.read_csv('https://raw.githubusercontent.com/ankit-rathi/Tradevesting_v1/main/data/myInvestments.csv')
  return myinvmt_df

# function to get the stock ids
def get_stock_ids(df_pf):
  stock_n100 = df_pf['Symbol'].unique()

  exclude = ['CADILAHC','MMTC', 'MASFIN']

  stock_ids = df_pf[~df_pf['Symbol'].isin(exclude) ]['Symbol'].unique()

  #mypf = mypf[mypf.Forecast.notnull()]
  #stock_ids = mypf['Symbol'].unique()

  #stock_ids.sort()
  return stock_ids

# get features from screener data
def get_screener_features():
  myscreen_df = get_myscreen_df()
  cols = ['Symbol', 'EPS', 'MedPE', 'ROCE%', 'ROE%', 'CapType']
  return myscreen_df[cols]

# get relative strength
def get_relative_strength(stock_list):

    # Dictionary to store stock tickers and their corresponding percentage price change
    stock_changes = {}

    # Loop through each stock and fetch its price data
    for stock in stock_list:
        try:
            # Download the stock data for the given date range
            stock_data = yfin.Ticker(stock + '.NS').history(period='1mo', interval='1d')[map(str.title, ['open', 'close', 'low', 'high', 'volume'])]

            # Calculate the percentage change for the stock
            if len(stock_data) > 0:
                start_price = stock_data['Close'].iloc[0]
                end_price = stock_data['Close'].iloc[-1]
                percent_change = round(((end_price - start_price) / start_price) * 100, 2)
                stock_changes[stock] = percent_change
            else:
                stock_changes[stock] = np.nan  # If no data is available, set to NaN

        except Exception as e:
            print(f"Error fetching data for {stock}: {e}")
            stock_changes[stock] = np.nan

    # Create a DataFrame with stock tickers and their percentage changes
    df = pd.DataFrame(list(stock_changes.items()), columns=['Symbol', 'Percent_Change'])

    # Drop any stocks with missing data (NaN values)
    df = df.dropna()

    # Calculate the percentile rank based on percentage change
    df['RSP'] = round(df['Percent_Change'].rank(pct=True) * 100, 2)
    cols = ['Symbol', 'RSP']
    df = df[cols]
    # Sort by percentile rank (optional)
    df = df.sort_values(by='RSP', ascending=False).reset_index(drop=True)

    return df

In [6]:
# function to get stock technicals
def stock_prec_dev(stock_symbol):
    #stock_symbol = 'ULTRACEMCO.NS'
    short_window = 20
    mid_window = 50
    long_window = 200
    moving_avg = 'SMA'

    start = datetime.datetime(*map(int, start_date.split('-')))
    end = datetime.datetime(*map(int, end_date.split('-')))

    stock_df = yfin.Ticker(stock_symbol + '.NS').history(period='max', interval='1d')[map(str.title, ['open', 'close', 'low', 'high', 'volume'])]

    stock_df['Max'] = round(max(stock_df['Close']),2)
    stock_df = stock_df[(stock_df.index <= end_date) & (stock_df.index >= start_date)]
    stock_df['200_SMA'] = round(stock_df['Close'].rolling(window = 200, min_periods = 1).mean(),0)
    stock_df['Dev%_200'] = round((stock_df['Close'] - stock_df['200_SMA'])*100/stock_df['200_SMA'],2)
    stock_df.dropna(axis = 0, inplace = True) # remove any null rows

    stock_df['20_SMA'] = stock_df['Close'].rolling(window=20).mean()
    stock_df['50_SMA'] = stock_df['Close'].rolling(window=50).mean()
    stock_df['Symbol'] = stock_symbol

    stock_df['Close'] = round(stock_df['Close'],2)
    stock_df['Min'] = round(min(stock_df['Close']),2)
    stock_df['RSI_14'] = ta.momentum.RSIIndicator(close=stock_df['Close'], window=14).rsi()
    stock_df['RSI_14'] = round(stock_df['RSI_14'],0)
    stock_df['Prev_Close'] = stock_df['Close'].shift(1)
    stock_df.drop(['Open', 'Low', 'High', 'Volume'], axis=1, inplace=True)
    stock_df = stock_df.tail(1)

    max_SMA = max(stock_df['20_SMA'].item(), stock_df['50_SMA'].item(), stock_df['200_SMA'].item())
    min_SMA = min(stock_df['20_SMA'].item(), stock_df['50_SMA'].item(), stock_df['200_SMA'].item())
    ABS_Spread = max_SMA - min_SMA
    stock_df['Spread%'] = round((ABS_Spread / stock_df['200_SMA'].item()) * 100,2)

    return stock_df

# function to compute stock attributes
def get_common_features(stock_ids, df_mypf):

  df_prec_dev = pd.DataFrame()
  df_tmp = get_screener_features()
  df_rs = get_relative_strength(stock_ids)

  for stock_id in stock_ids:
      tmp = stock_prec_dev(stock_id)
      tmp = tmp.reset_index()
      df_prec_dev = pd.concat([df_prec_dev, tmp], ignore_index = True)
  df_prec_dev = pd.merge(df_prec_dev, df_mypf, on= 'Symbol')
  df_prec_dev = pd.merge(df_prec_dev, df_tmp, on= 'Symbol', how='left')
  df_prec_dev = pd.merge(df_prec_dev, df_rs, on= 'Symbol', how='left')
  #print(df_prec_dev.columns)
  df_prec_dev['Curr_PE'] = round(df_prec_dev['Close']/df_prec_dev['EPS'],1)
  df_prec_dev['Dev%_PE'] = round((df_prec_dev['Curr_PE'] - df_prec_dev['MedPE'])*100/df_prec_dev['MedPE'],2)
  df_prec_dev['Conviction'] = df_prec_dev['Conviction'] + '-' + df_prec_dev['CapType']
  return df_prec_dev

# function to arrange stock features
def arrange_features(df_stocks, common_cols, diff_cols):
  df_stocks_common = df_stocks[common_cols].drop_duplicates()
  df_stocks_diff = df_stocks[diff_cols]
  df_stocks_diff['Investment'] = df_stocks_diff['AvgCost'] * df_stocks_diff['Shares']
  df_stocks_diff = df_stocks_diff.groupby(['Symbol'])[['Shares', 'Investment']].aggregate(['sum']).reset_index()
  df_stocks_diff.columns = ['Symbol', 'Shares', 'Investment']
  df_stocks_diff['AvgCost'] = round(df_stocks_diff['Investment']/df_stocks_diff['Shares'],2)
  df_stocks = pd.merge(df_stocks_diff, df_stocks_common, on='Symbol')
  return df_stocks

# plot fact distribution across dimension
def plot_pie_chart(df, dimension, fact):
  # grouping the data by category and calculating the sum of fact for each type
  grouped_data = df.groupby(dimension)[fact].sum()

  # sorting the grouped data in descending order
  grouped_data = grouped_data.sort_values(ascending=False)

  # creating a pie chart
  grouped_data.plot.pie(autopct='%1.1f%%', startangle=90, figsize=(6, 6))

  # adding a title and displaying the plot
  plt.title(f'{dimension} {fact} Distribution')
  plt.ylabel('')  # To hide the y-label
  plt.show()

In [7]:
# function to get portfolio features

def get_portfolio_features(df_common_features):

  print_date_time()
  print('-------------------')

  #df_common_features["Target"] = df_common_features["Target"].fillna(df_common_features["Max"])
  df_common_features['NTT'] = np.where(df_common_features['Strategy']== 'NTT', df_common_features["Target"], df_common_features['Max'])
  df_common_features['LTT'] = np.where(df_common_features['Strategy']== 'BTT', df_common_features["Target"], df_common_features['Max'])
  df_common_features['BOL'] = df_common_features['Min']

  tmp_df = df_common_features[df_common_features['Symbol'].isin(mypf_df[mypf_df['InPortfolio'] != 'NA'].Symbol.values)]
  print('qualified stocks: '+str(len(tmp_df['Symbol'].unique())))
  tmp_df1 = tmp_df[tmp_df['LatestQtr'] == 1]
  print('with latest results: '+str(len(tmp_df1['Symbol'].unique())))
  tmp_df1 = tmp_df1[tmp_df1['StarStock'] == 1]
  print('still star stocks: '+str(len(tmp_df1['Symbol'].unique())))
  tmp_df['Investment'] = tmp_df['AvgCost'] * tmp_df['Shares']
  tmp_df['Current'] = round(tmp_df['Close'] * tmp_df['Shares'],0)
  tmp_df['Previous'] = tmp_df['Prev_Close'] * tmp_df['Shares']
  tmp_df['EstimatedST'] = tmp_df['NTT'] * tmp_df['Shares']
  tmp_df['EstimatedLT'] = tmp_df['LTT'] * tmp_df['Shares']
  tmp_df['Current P/L'] = round((tmp_df['Current'] - tmp_df['Investment']),0)
  tmp_df['Today P/L%'] = round((tmp_df['Current'] - tmp_df['Previous'])*100/tmp_df['Previous'],2)
  tmp_df['Current P/L%'] = round((tmp_df['Current'] - tmp_df['Investment'])*100/tmp_df['Investment'],2)
  tmp_df['EstimatedST P/L%'] = round((tmp_df['EstimatedST'] - tmp_df['Investment'])*100/tmp_df['Investment'],2)
  tmp_df['EstimatedLT P/L%'] = round((tmp_df['EstimatedLT'] - tmp_df['Investment'])*100/tmp_df['Investment'],2)
  tmp_df['NTT%'] = round((tmp_df['NTT'] - tmp_df['Close'])*100/tmp_df['Close'],2)
  tmp_df['LTT%'] = round((tmp_df['LTT'] - tmp_df['Close'])*100/tmp_df['Close'],2)
  tmp_df['Gained%'] = round((tmp_df['Close'] - tmp_df['BOL'])*100/tmp_df['BOL'],2)
  investment = round(sum(tmp_df['AvgCost']*tmp_df['Shares']),0)
  current = round(sum(tmp_df['Close']*tmp_df['Shares']),0)
  tmp_df['InitAlloc%'] = round(tmp_df['Investment']*100/investment,2)
  tmp_df['CurrAlloc%'] = round(tmp_df['Current']*100/current,2)
  tmp_df['FTT'] = tmp_df['LTT']
  tmp_df.loc[tmp_df['Strategy'] == 'NTT', 'FTT'] = tmp_df['NTT']
  tmp_df['FTT%'] = tmp_df['LTT%']
  tmp_df.loc[tmp_df['Strategy'] == 'NTT', 'FTT%'] = tmp_df['NTT%']
  tmp_df['FTT Amt'] = round(tmp_df['FTT%'] * tmp_df['Current']/100,0)
  tmp_df['OTT%'] = round((tmp_df['FTT'] - tmp_df['AvgCost'])*100/tmp_df['AvgCost'],2)
  tmp_df['RRR Ind'] = round(tmp_df['Current P/L']/tmp_df['FTT Amt'],2)
  tmp_df['Risk Ind'] = round(tmp_df['Current P/L%']*tmp_df['CurrAlloc%'],0)

  return tmp_df

# function to print portfolio features
def print_portfolio_stats(df_portfolio_features, myinvmt_df):
  from pyxirr import xirr

  total_booked_amt, reserve_amt, cy_booked_amt, py_booked_amt = get_amt()

  dates = myinvmt_df['Date'].values
  dates = np.append(dates, datetime.date.today().strftime('%d-%b-%y'))
  investment = myinvmt_df['Investment'].values
  dates= pd.to_datetime(dates)

  current = round(sum(df_portfolio_features['Close']*df_portfolio_features['Shares']),0) + reserve_amt
  investment_xirr = np.append(investment, current)
  cagr = round(xirr(pd.DataFrame({"dates": dates, "amounts": investment_xirr}))*100,2)

  investment = -sum(investment)
  invested = round(sum(df_portfolio_features['AvgCost']*df_portfolio_features['Shares']),0) + reserve_amt
  previous = round(sum(df_portfolio_features['Prev_Close']*df_portfolio_features['Shares']),0) + reserve_amt
  cy_invested = investment + py_booked_amt

  today_pnl_amount = current-previous
  today_pnl_percentage = round((current-previous)*100/previous,2)

  curr_pnl_amount = current-invested
  curr_pnl_percentage = round((curr_pnl_amount)*100/(cy_invested),2)

  cy_pnl_amount = cy_booked_amt + curr_pnl_amount
  cy_pnl_percentage = round((cy_pnl_amount)*100/cy_invested,2)

  overall_pnl_amount = total_booked_amt + curr_pnl_amount
  overall_pnl_percentage = round((overall_pnl_amount)*100/investment,2)

  estimate_st = round(sum(df_portfolio_features['FTT']*df_portfolio_features['Shares']),0)  + reserve_amt
  est_st_pnl_amount = estimate_st-current
  est_st_pnl_percentage = round((est_st_pnl_amount)*100/current,2)

  estimate_lt = round(sum(df_portfolio_features['LTT']*df_portfolio_features['Shares']),0)  + reserve_amt
  est_lt_pnl_amount = estimate_lt-current
  est_lt_pnl_percentage = round((est_lt_pnl_amount)*100/current,2)

  total_profit = round(sum(df_portfolio_features[df_portfolio_features['Current P/L%'] > 0]['Current']) - sum(df_portfolio_features[df_portfolio_features['Current P/L%'] > 0]['Investment']),0)
  total_loss = round(sum(df_portfolio_features[df_portfolio_features['Current P/L%'] < 0]['Current']) - sum(df_portfolio_features[df_portfolio_features['Current P/L%'] < 0]['Investment']),0)

  cy_booked_percentage = round((cy_booked_amt)*100/current,2)
  py_booked_percentage = round((py_booked_amt)*100/investment,2)
  total_booked_percentage = round((total_booked_amt)*100/investment,2)

  print('-------------------')
  print('Initial Investment: ', format_amt(investment))
  print('CY Investment: ', format_amt(cy_invested))
  print('Reserve: ', format_amt(reserve_amt))
  print('Current: ',  format_amt(current))
  print('-------------------')
  print('Today PnL: '+ '{} ({}%)'.format(format_amt(today_pnl_amount), today_pnl_percentage))
  print('Current PnL: '+ '{} ({}%)'.format(format_amt(curr_pnl_amount), curr_pnl_percentage))
  print('CY Booked + Current PnL: '+ '{} ({}%)'.format(format_amt(cy_pnl_amount), cy_pnl_percentage))
  print('-------------------')
  print('Total profit: ', format_amt(total_profit))
  print('Total loss: ', format_amt(total_loss))
  print('-------------------')
  print('Total Booked + Current PnL: '+ '{} ({}%)'.format(format_amt(overall_pnl_amount), overall_pnl_percentage))
  print('Total Booked PnL: '+ '{} ({}%)'.format(format_amt(total_booked_amt), total_booked_percentage))
  print('Curr Year Booked PnL: '+ '{} ({}%)'.format(format_amt(cy_booked_amt), cy_booked_percentage))
  print('Prev Year Booked PnL: '+ '{} ({}%)'.format(format_amt(py_booked_amt), py_booked_percentage))
  print('===================')
  print('Est FTT: ',  format_amt(estimate_st))
  print('Est FTT PnL: '+ '{} ({}%)'.format(format_amt(est_st_pnl_amount), est_st_pnl_percentage))

  print('===================')
  print('Deployed: ', format_amt(investment))

  print('Current: ', format_amt(current))

  print('CAGR/XIRR %: '+'{}%'.format(cagr))

In [8]:
# get start and end date
start_date, end_date = get_start_end_date()

# get portfolio and prospects data
mypfs_df = get_mypfs_df()
mypps_df = get_mypps_df()
myinvmt_df = get_myinvmt_df()

# merge above datasets
mypf_df = pd.merge(mypfs_df, mypps_df, on="Symbol")

# seggregate dm and sv portfolio
dm_pf = mypf_df[mypf_df['InPortfolio'] == 'DM']
sv_pf = mypf_df[mypf_df['InPortfolio'] == 'SV']

# build portfolio stock dataframe
dm_stocks = get_stock_ids(dm_pf)
sv_stocks = get_stock_ids(sv_pf)
df_stocks = pd.concat([dm_pf,sv_pf], ignore_index = True)

# arrange common and diff stock features
common_cols = ['Symbol', 'Target', 'Criteria', 'Strategy', 'CumlRnk', 'LatestQtr', 'StarStock', 'Conviction', 'Category', 'InFolio', 'XIRR', 'MBQ']
diff_cols = ['Symbol', 'AvgCost', 'Shares']
df_stocks = arrange_features(df_stocks, common_cols, diff_cols)

# get common features
stock_ids = df_stocks['Symbol'].values
df_common_features = get_common_features(stock_ids, df_stocks)

df_common_features.reset_index(drop=True, inplace=True)
df_common_features.drop(['Date'], axis=1, inplace=True)
# get and print portfolio features
df_portfolio_features = get_portfolio_features(df_common_features)

print_portfolio_stats(df_portfolio_features, myinvmt_df)

df = df_portfolio_features
#plot_pie_chart(df, 'CapType', 'Current')
list_ox40n = list(df[df['MBQ'].str.contains('OX40N', na=False)]['Symbol'].values)

Run date time (IST): 2026-07-02 17:23:12
-------------------
qualified stocks: 92
with latest results: 31
still star stocks: 20
-------------------
Initial Investment:  1.40 C
CY Investment:  1.82 C
Reserve:  1.49 K
Current:  1.53 C
-------------------
Today PnL: 1.31 L (0.86%)
Current PnL: -29.89 L (-16.39%)
CY Booked + Current PnL: -27.81 L (-15.25%)
-------------------
Total profit:  4.90 L
Total loss:  -34.79 L
-------------------
Total Booked + Current PnL: 15.06 L (10.8%)
Total Booked PnL: 44.95 L (32.22%)
Curr Year Booked PnL: 2.08 L (1.36%)
Prev Year Booked PnL: 42.87 L (30.73%)
===================
Est FTT:  2.55 C
Est FTT PnL: 1.02 C (66.35%)
===================
Deployed:  1.40 C
Current:  1.53 C
CAGR/XIRR %: 4.34%

In [9]:
# top 5 near their targets
cols = ['Symbol', 'Today P/L%', 'Current P/L%', 'FTT%', 'OTT%', 'FTT Amt', 'Current P/L', 'Current', 'FTT', 'Dev%_PE', 'RSI_14','Conviction', 'Spread%',  'CumlRnk', 'RRR Ind', 'CurrAlloc%', 'Gained%', 'Criteria', 'Strategy', 'Category']
df_tmp = df_portfolio_features[~df_portfolio_features['Symbol'].isin(['ENRIN','BLUSPRING','DIGITIDE'])]
df_tmp = df_tmp.sort_values(by = 'FTT Amt', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
59,PIDILITIND,1.49,13.77,4.04,18.37,6486.0,19430.0,160540.0,1670.26,-20.26,71.0,X-LC,6.47,5.0,3.00,1.05,26.05,X40,ATH,CHEMICALS
49,JSWINFRA,-0.89,11.49,4.43,16.43,10954.0,25488.0,247262.0,342.00,-4.38,66.0,X-MC,9.17,61.0,2.33,1.61,40.19,X40N,NTT,REALTY
83,TTKPRESTIG,2.46,-16.03,19.20,0.09,16247.0,-16158.0,84619.0,770.00,96.37,80.0,M-SC,6.39,250.0,-0.99,0.55,50.68,OX40N,NTT,DURABLES
51,KOTAKBANK,-0.29,6.69,13.51,21.11,19960.0,9268.0,147741.0,453.24,-8.54,54.0,X-LC,4.44,12.0,0.46,0.96,12.99,X40,ATH,BANKS
56,MEDANTA,1.30,15.08,10.46,27.12,21248.0,26623.0,203140.0,1486.00,11.60,73.0,X-SC,6.36,87.0,1.25,1.33,39.98,XY24,NTT,HEALTHCARE

In [10]:
# top 5 today
df_tmp = df_portfolio_features.sort_values(by = 'Today P/L%', ascending=False)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
73,SONACOMS,6.93,14.57,21.05,38.69,24397.0,14743.0,115902.0,801.69,-9.26,77.0,M-MC,18.15,193.0,0.60,0.76,64.44,AR,ATH,AUTO
0,5PAISA,6.01,-26.64,53.91,12.90,86410.0,-58211.0,160285.0,593.00,135.58,80.0,H-SC,1.16,170.0,-0.67,1.05,54.68,OX40N,NTT,FINANCE
45,INFY,5.64,-29.14,89.45,34.24,198321.0,-91176.0,221712.0,1972.00,-44.12,42.0,X-LC,20.05,3.0,-0.46,1.45,5.64,X40,NTT,IT
43,INDIGOPNTS,5.30,-23.49,30.72,0.02,41030.0,-40999.0,133560.0,1408.00,103.68,69.0,M-SC,5.78,222.0,-1.00,0.87,51.53,OX40N,NTT,PAINTS
61,RAJESHEXPO,4.99,-82.29,465.01,0.07,112974.0,-112882.0,24295.0,518.00,790.15,44.0,L-SC,38.82,268.0,-1.00,0.16,19.98,OX40N,NTT,JEWELLERY

In [11]:
# bottom 5 today
df_tmp = df_portfolio_features.sort_values(by = 'Today P/L%', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
23,DMART,-3.27,0.65,28.77,29.60,72276.0,1620.0,251220.0,5391.45,-15.14,46.0,X-LC,3.88,14.0,0.02,1.64,14.83,X40N,ATH,FMCG
27,GLAXO,-1.98,-3.02,39.92,35.69,77151.0,-6020.0,193264.0,3380.16,-25.91,63.0,X-MC,6.47,56.0,-0.08,1.26,14.86,X40,ATH,PHARMA
57,PAGEIND,-1.66,11.85,19.43,33.59,58328.0,31816.0,300195.0,51217.29,-19.73,69.0,X-MC,7.73,55.0,0.55,1.96,42.56,X40,ATH,APPARELS
25,FINCABLES,-1.28,43.10,45.30,107.91,95707.0,63629.0,211273.0,1641.55,28.87,54.0,M-SC,26.22,220.0,0.66,1.38,58.95,OX40N,ATH,CABLES
64,RELAXO,-1.11,-47.49,190.05,52.31,144866.0,-68935.0,76225.0,1176.00,-44.05,69.0,X-SC,11.04,92.0,-0.48,0.50,70.43,X40N,NTT,FOOTWEAR

In [12]:
# top 5 to exit based on CumlRnk
df_tmp = df_portfolio_features[~df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])]
df_tmp = df_tmp[(df_tmp['Current P/L%'] > -1) & (df_tmp['Current P/L%'] < 1)].sort_values(by = 'CumlRnk', ascending=False)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
63,RECLTD,-0.14,0.05,20.67,20.74,42018.0,110.0,203280.0,446.0,9.37,63.0,M-MC,1.77,191.0,0.0,1.33,21.14,XY25,NTT,FINANCE

In [13]:
# OX40N stocks to exit
df_tmp = df_portfolio_features[(df_portfolio_features['Symbol'].isin(list_ox40n))].sort_values(by = 'Current P/L%', ascending=False)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
25,FINCABLES,-1.28,43.10,45.30,107.91,95707.0,63629.0,211273.0,1641.55,28.87,54.0,M-SC,26.22,220.0,0.66,1.38,58.95,OX40N,ATH,CABLES
72,SIS,1.23,-2.29,24.10,21.26,26146.0,-2542.0,108490.0,528.00,2588.08,54.0,H-SC,25.17,168.0,-0.10,0.71,61.31,OX40N,NTT,MISC
16,CERA,0.54,-15.32,46.31,23.89,68978.0,-26955.0,148948.0,9475.00,-18.38,65.0,H-SC,11.62,153.0,-0.39,0.97,43.14,OX40N,NTT,CERAMICS
83,TTKPRESTIG,2.46,-16.03,19.20,0.09,16247.0,-16158.0,84619.0,770.00,96.37,80.0,M-SC,6.39,250.0,-0.99,0.55,50.68,OX40N,NTT,DURABLES
43,INDIGOPNTS,5.30,-23.49,30.72,0.02,41030.0,-40999.0,133560.0,1408.00,103.68,69.0,M-SC,5.78,222.0,-1.00,0.87,51.53,OX40N,NTT,PAINTS

In [14]:
# top 5 to book for rotation
df_tmp = df_portfolio_features[(df_portfolio_features['Current P/L%'] > 20) ].sort_values(by = 'CumlRnk', ascending=False)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
25,FINCABLES,-1.28,43.1,45.30,107.91,95707.0,63629.0,211273.0,1641.55,28.87,54.0,M-SC,26.22,220.0,0.66,1.38,58.95,OX40N,ATH,CABLES
68,SATIN,3.20,43.9,5.51,51.83,21906.0,121286.0,397570.0,274.00,28.78,69.0,H-SC,41.94,159.0,5.54,2.59,93.68,XY24,NTT,FINANCE

In [15]:
# top 5 to monitor for exit
df_tmp = df_portfolio_features[~df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])]
df_tmp = df_tmp[(df_tmp['Current P/L%'] > 0) ].sort_values(by = 'Dev%_PE', ascending=False)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
75,SURYODAY,2.91,4.64,17.58,23.03,32940.0,8303.0,187374.0,216.00,103.95,69.0,H-SC,20.20,166.0,0.25,1.22,57.76,XR,NTT,BANKS
74,STARHEALTH,0.29,13.88,29.31,47.26,93834.0,39021.0,320144.0,761.00,79.65,74.0,H-SC,14.46,173.0,0.42,2.09,40.49,XY24,NTT,INSURANCE
25,FINCABLES,-1.28,43.10,45.30,107.91,95707.0,63629.0,211273.0,1641.55,28.87,54.0,M-SC,26.22,220.0,0.66,1.38,58.95,OX40N,ATH,CABLES
68,SATIN,3.20,43.90,5.51,51.83,21906.0,121286.0,397570.0,274.00,28.78,69.0,H-SC,41.94,159.0,5.54,2.59,93.68,XY24,NTT,FINANCE
63,RECLTD,-0.14,0.05,20.67,20.74,42018.0,110.0,203280.0,446.00,9.37,63.0,M-MC,1.77,191.0,0.00,1.33,21.14,XY25,NTT,FINANCE

In [16]:
# top 5 to book for rotation from weak conviction
df_tmp = df_portfolio_features[~df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])]
df_tmp = df_tmp[~df_tmp['Criteria'].isin(['XY25','XY24','X40', 'X40N'])].sort_values(by = 'RRR Ind', ascending=False)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
91,ZYDUSLIFE,-0.85,15.98,16.95,35.63,41198.0,33482.0,243056.0,1286.17,0.90,57.0,H-MC,14.22,120.0,0.81,1.59,27.79,AR,ATH,PHARMA
25,FINCABLES,-1.28,43.10,45.30,107.91,95707.0,63629.0,211273.0,1641.55,28.87,54.0,M-SC,26.22,220.0,0.66,1.38,58.95,OX40N,ATH,CABLES
73,SONACOMS,6.93,14.57,21.05,38.69,24397.0,14743.0,115902.0,801.69,-9.26,77.0,M-MC,18.15,193.0,0.60,0.76,64.44,AR,ATH,AUTO
75,SURYODAY,2.91,4.64,17.58,23.03,32940.0,8303.0,187374.0,216.00,103.95,69.0,H-SC,20.20,166.0,0.25,1.22,57.76,XR,NTT,BANKS
72,SIS,1.23,-2.29,24.10,21.26,26146.0,-2542.0,108490.0,528.00,2588.08,54.0,H-SC,25.17,168.0,-0.10,0.71,61.31,OX40N,NTT,MISC

In [17]:
# top 5 to accumulate based on lowest RSI_14
df_tmp = df_portfolio_features[df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])].sort_values(by = 'RSI_14', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
33,HCLTECH,4.25,-30.04,73.67,21.51,124695.0,-72662.0,169262.0,1872.35,-26.39,39.0,X-LC,20.34,8.0,-0.58,1.10,4.24,X40,ATH,IT
58,PGHH,-0.81,-33.41,98.25,32.01,139688.0,-71344.0,142176.0,17616.87,-54.91,39.0,X-MC,20.99,57.0,-0.51,0.93,0.83,X40,ATH,FMCG
81,TMPV,-0.53,-21.25,73.44,36.58,205794.0,-75621.0,280220.0,600.00,-83.62,39.0,X-LC,7.97,4.0,-0.37,1.83,17.77,XY24,NTT,AUTO
26,GILLETTE,-0.47,-10.04,44.20,29.72,100955.0,-25491.0,228405.0,10978.86,-30.84,41.0,X-SC,6.34,83.0,-0.25,1.49,4.96,X40,ATH,FMCG
79,TCS,4.31,-39.29,105.69,24.88,297266.0,-182011.0,281262.0,4253.91,-48.54,41.0,X-LC,21.56,2.0,-0.61,1.84,4.31,X40,ATH,IT

In [18]:
# top 5 to accumulate based on Spread and CumlRnk
df_tmp = df_portfolio_features[df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])]
df_tmp = df_tmp[(df_tmp['CumlRnk'] < 100)].sort_values(by = 'Spread%', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
17,CIPLA,-0.05,17.88,13.20,33.43,23832.0,27383.0,180544.0,1648.14,-8.67,67.0,X-LC,2.18,18.0,1.15,1.18,23.25,X40N,ATH,PHARMA
11,BERGEPAINT,1.05,-4.03,30.58,25.32,75641.0,-10393.0,247356.0,680.00,-9.26,52.0,X-MC,2.93,68.0,-0.14,1.61,28.74,XY24,NTT,PAINTS
84,UNITDSPR,1.55,0.89,19.70,20.77,46536.0,2081.0,236225.0,1644.00,-10.48,62.0,X-MC,3.14,64.0,0.04,1.54,12.68,X40N,NTT,BREWERIES
19,COLPAL,-0.50,-21.72,78.68,39.86,162199.0,-57215.0,206150.0,3683.41,-5.18,55.0,X-MC,3.55,62.0,-0.35,1.34,16.61,XY25,ATH,FMCG
23,DMART,-3.27,0.65,28.77,29.60,72276.0,1620.0,251220.0,5391.45,-15.14,46.0,X-LC,3.88,14.0,0.02,1.64,14.83,X40N,ATH,FMCG

In [19]:
# top 5 to accumulate based on lowest Gained%
df_tmp = df_portfolio_features[df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])].sort_values(by = 'Gained%', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
58,PGHH,-0.81,-33.41,98.25,32.01,139688.0,-71344.0,142176.0,17616.87,-54.91,39.0,X-MC,20.99,57.0,-0.51,0.93,0.83,X40,ATH,FMCG
1,ABBOTINDIA,0.68,-13.70,36.81,18.07,56816.0,-24505.0,154350.0,35195.00,-26.49,44.0,X-MC,6.61,58.0,-0.43,1.01,2.16,X40,ATH,PHARMA
65,RELIANCE,-0.34,-16.33,49.75,25.30,83656.0,-32811.0,168152.0,1952.00,-18.49,46.0,X-LC,7.87,21.0,-0.39,1.10,3.55,XY25,BTT,REFINERIES
33,HCLTECH,4.25,-30.04,73.67,21.51,124695.0,-72662.0,169262.0,1872.35,-26.39,39.0,X-LC,20.34,8.0,-0.58,1.10,4.24,X40,ATH,IT
79,TCS,4.31,-39.29,105.69,24.88,297266.0,-182011.0,281262.0,4253.91,-48.54,41.0,X-LC,21.56,2.0,-0.61,1.84,4.31,X40,ATH,IT

In [20]:
# top 5 to accumulate based on lowest CurrAlloc%
df_tmp = df_portfolio_features[df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])].sort_values(by = 'CurrAlloc%', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
10,BATAINDIA,2.41,-54.94,200.05,35.20,115989.0,-70690.0,57980.0,2096.00,-24.04,50.0,X-SC,20.50,91.0,-0.61,0.38,14.99,X40,NTT,FOOTWEAR
64,RELAXO,-1.11,-47.49,190.05,52.31,144866.0,-68935.0,76225.0,1176.00,-44.05,69.0,X-SC,11.04,92.0,-0.48,0.50,70.43,X40N,NTT,FOOTWEAR
60,QUESS,3.71,16.29,49.53,73.90,61514.0,17402.0,124195.0,424.00,-37.19,84.0,X-SC,17.91,80.0,0.28,0.81,69.30,XY24,NTT,MISC
35,HDFCLIFE,0.25,-6.55,42.02,32.71,58820.0,-9819.0,139981.0,811.41,-27.10,42.0,X-LC,16.12,31.0,-0.17,0.91,5.16,X40,ATH,INSURANCE
28,GODREJCP,3.22,-3.60,36.38,31.47,52121.0,-5346.0,143268.0,1469.04,1.37,64.0,X-LC,8.16,32.0,-0.10,0.93,9.93,X40N,ATH,FMCG

In [21]:
# top 5 to accumulate based on CumlRnk
df_tmp = df_portfolio_features.sort_values(by = 'CumlRnk', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
47,ITC,-0.14,-23.64,55.92,19.06,145252.0,-80416.0,259750.0,452.00,-57.95,51.0,X-LC,13.59,1.0,-0.55,1.69,4.66,X40,NTT,FMCG
79,TCS,4.31,-39.29,105.69,24.88,297266.0,-182011.0,281262.0,4253.91,-48.54,41.0,X-LC,21.56,2.0,-0.61,1.84,4.31,X40,ATH,IT
45,INFY,5.64,-29.14,89.45,34.24,198321.0,-91176.0,221712.0,1972.00,-44.12,42.0,X-LC,20.05,3.0,-0.46,1.45,5.64,X40,NTT,IT
81,TMPV,-0.53,-21.25,73.44,36.58,205794.0,-75621.0,280220.0,600.00,-83.62,39.0,X-LC,7.97,4.0,-0.37,1.83,17.77,XY24,NTT,AUTO
59,PIDILITIND,1.49,13.77,4.04,18.37,6486.0,19430.0,160540.0,1670.26,-20.26,71.0,X-LC,6.47,5.0,3.00,1.05,26.05,X40,ATH,CHEMICALS

In [22]:
# top 5 for average up
df_tmp = df_portfolio_features[(df_portfolio_features['Dev%_200'] > 5)].sort_values(by = 'CurrAlloc%', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
44,INDUSINDBK,0.20,-30.34,90.78,32.89,48821.0,-23426.0,53780.0,1800.00,-352.80,59.0,L-MC,7.17,258.0,-0.48,0.35,32.59,XR,NTT,BANKS
64,RELAXO,-1.11,-47.49,190.05,52.31,144866.0,-68935.0,76225.0,1176.00,-44.05,69.0,X-SC,11.04,92.0,-0.48,0.50,70.43,X40N,NTT,FOOTWEAR
3,ALKYLAMINE,3.51,-22.15,147.32,92.54,115794.0,-22363.0,78600.0,4520.85,-16.57,57.0,H-SC,8.59,142.0,-0.19,0.51,49.25,SR,ATH,CHEMICALS
83,TTKPRESTIG,2.46,-16.03,19.20,0.09,16247.0,-16158.0,84619.0,770.00,96.37,80.0,M-SC,6.39,250.0,-0.99,0.55,50.68,OX40N,NTT,DURABLES
72,SIS,1.23,-2.29,24.10,21.26,26146.0,-2542.0,108490.0,528.00,2588.08,54.0,H-SC,25.17,168.0,-0.10,0.71,61.31,OX40N,NTT,MISC

In [23]:
# top 5 RSP
df_tmp = df_portfolio_features.sort_values(by = 'RSP', ascending=False)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
60,QUESS,3.71,16.29,49.53,73.90,61514.0,17402.0,124195.0,424.0,-37.19,84.0,X-SC,17.91,80.0,0.28,0.81,69.30,XY24,NTT,MISC
69,SFL,3.54,-24.93,68.68,26.63,135199.0,-65364.0,196854.0,1287.0,49.08,73.0,M-SC,18.20,242.0,-0.48,1.28,64.07,XY24,NTT,MISC
64,RELAXO,-1.11,-47.49,190.05,52.31,144866.0,-68935.0,76225.0,1176.0,-44.05,69.0,X-SC,11.04,92.0,-0.48,0.50,70.43,X40N,NTT,FOOTWEAR
83,TTKPRESTIG,2.46,-16.03,19.20,0.09,16247.0,-16158.0,84619.0,770.0,96.37,80.0,M-SC,6.39,250.0,-0.99,0.55,50.68,OX40N,NTT,DURABLES
49,JSWINFRA,-0.89,11.49,4.43,16.43,10954.0,25488.0,247262.0,342.0,-4.38,66.0,X-MC,9.17,61.0,2.33,1.61,40.19,X40N,NTT,REALTY

In [24]:
# Top N allocation
df_tmp = df_portfolio_features.sort_values(by = 'CurrAlloc%', ascending=False)
top_n_values = [10, 25, 50]

sum_df = pd.DataFrame({
    'Top_N': top_n_values,
    'Sum_Alloc%': [df_tmp['CurrAlloc%'].head(n).sum() for n in top_n_values]
})

sum_df

   Top_N  Sum_Alloc%
0     10       19.50
1     25       42.61
2     50       72.73

In [25]:
# market-cap-wise allocation
df_tmp = df_portfolio_features[cols]
df_tmp.groupby(df_tmp['Conviction'].str[-2:])['CurrAlloc%'].sum().sort_values(ascending=False)

Conviction
SC    43.89
LC    30.25
MC    25.88
Name: CurrAlloc%, dtype: float64

In [26]:
# criteria-wise allocation
df_portfolio_features.groupby('Criteria')['CurrAlloc%'].sum().sort_values(ascending=False)

Criteria
XY24     28.01
X40      24.42
X40N     17.45
XR        8.84
OX40N     7.23
AR        6.73
XY25      6.47
SR        0.87
Name: CurrAlloc%, dtype: float64

In [27]:
# conviction-wise allocation
df_portfolio_features.groupby('Conviction')['CurrAlloc%'].sum().sort_values(ascending=False)

Conviction
X-LC    28.29
H-SC    23.05
X-MC    20.77
M-SC    10.22
X-SC    10.05
H-MC     2.67
M-MC     2.09
H-LC     1.17
M-LC     0.79
L-SC     0.57
L-MC     0.35
Name: CurrAlloc%, dtype: float64

In [28]:
# sector-wise stats
df_tmp = df_portfolio_features.groupby('Category')[['CurrAlloc%', 'Current', 'Current P/L', 'FTT Amt']].sum().sort_values(by=['Current', 'Current P/L'], ascending=False)
df_tmp['Current P/L%'] = round(df_tmp['Current P/L'] * 100 / df_tmp['Current'], 2)
df_tmp['FTT%'] = round(df_tmp['FTT Amt'] * 100 / df_tmp['Current'], 2)
cols = ['CurrAlloc%', 'Current P/L%', 'FTT%']
df_tmp[cols].sort_values(by=['CurrAlloc%'], ascending=False)

               CurrAlloc%  Current P/L%    FTT%
Category
FMCG                14.47        -19.19   61.00
FINANCE             11.47         -4.90   50.36
IT                   9.43        -55.99  133.98
MISC                 7.22        -21.25   73.28
AUTO                 6.69         -6.82   46.66
BANKS                5.78         -2.35   49.67
PAINTS               5.56        -15.64   35.36
INSURANCE            5.27         -2.42   36.97
PHARMA               5.04          3.93   25.80
ELECTRICAL           4.09        -12.94   52.79
CHEMICALS            2.18        -21.66   93.84
HEALTHCARE           2.12        -10.55   39.40
APPARELS             1.96         10.60   19.43
AC                   1.75        -18.70   50.89
FOOTWEAR             1.75        -65.11  131.32
DURABLES             1.63        -54.79   92.45
REALTY               1.61         10.31    4.43
BREWERIES            1.54          0.88   19.70
TRAVEL               1.54        -90.05  185.20
CERAMICS             1.44        -39.02   81.26
CABLES               1.38         30.12   45.30
ENGINEERING          1.31        -20.21   75.19
REFINERIES           1.10        -19.51   49.75
CEMENT               1.06        -65.43  189.18
JEWELLERY            1.03       -102.91  173.41
ENTERTAINMENT        0.76        -66.29  165.47
TEXTILES             0.43        -39.36   79.10
HOTELS               0.41        -80.91  144.72

In [29]:
# money to be made criteria-wise
df_portfolio_features.groupby('Criteria')['FTT Amt'].agg(['sum', 'count']).sort_values(by='sum', ascending=False)

                sum  count
Criteria
XY24      3305467.0     21
X40       1933714.0     19
XR        1326843.0     13
AR        1147102.0      9
X40N      1044434.0     13
OX40N      684485.0     10
XY25       443822.0      5
SR         284696.0      2

In [30]:
# money to be made conviction-wise
df_portfolio_features.groupby('Conviction')['FTT Amt'].agg(['sum', 'count']).sort_values(by='sum', ascending=False)

                  sum  count
Conviction
H-SC        3246529.0     24
X-LC        1942308.0     21
X-MC        1530949.0     15
M-SC        1351596.0     14
X-SC        1264751.0      9
H-MC         289868.0      2
L-SC         203808.0      2
M-LC         170971.0      1
M-MC          66415.0      2
H-LC          54547.0      1
L-MC          48821.0      1

In [31]:
# money to be made criteria and conviction-wise
df_portfolio_features.groupby(['Conviction', 'Criteria'])['FTT Amt'].agg(['sum', 'count']).sort_values(by='sum', ascending=False)

                           sum  count
Conviction Criteria
X-LC       X40       1056730.0     10
H-SC       AR         954672.0      5
           XY24       924058.0      6
M-SC       XY24       807069.0      6
H-SC       XR         797263.0      7
X-SC       XY24       758760.0      4
X-MC       X40        660040.0      7
           X40N       408576.0      4
X-LC       XY24       351588.0      2
           X40N       346811.0      6
X-SC       X40N       289047.0      3
H-SC       OX40N      285840.0      4
M-SC       OX40N      285671.0      5
H-SC       SR         284696.0      2
H-MC       XY24       248670.0      1
X-MC       XY25       247011.0      2
X-SC       X40        216944.0      2
X-MC       XY24       215322.0      2
M-SC       XR         186568.0      2
M-LC       XR         170971.0      1
X-LC       XY25       154793.0      2
L-SC       OX40N      112974.0      1
           XR          90834.0      1
M-SC       AR          72288.0      1
H-LC       AR          54547.0      1
L-MC       XR          48821.0      1
M-MC       XY25        42018.0      1
H-MC       AR          41198.0      1
X-LC       XR          32386.0      1
M-MC       AR          24397.0      1

In [32]:
# notebook execution time

end_time = time.time()
execution_time = round(end_time - start_time, 0)
print(f"Notebook execution time: {execution_time} seconds")

Notebook execution time: 30.0 seconds