<a href="https://colab.research.google.com/github/ankit-rathi/Quantvesting_v2/blob/main/myStocks_Portfolio_Analysis.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
'''
!pip install pandas==2.2.2 -qq
!pip install pyxirr -qq
!pip install ta -qq
!pip install yfinance==0.2.59 -qq
'''

'\n!pip install pandas==2.2.2 -qq\n!pip install pyxirr -qq\n!pip install ta -qq\n!pip install yfinance==0.2.59 -qq\n'

In [2]:
# import libraries

import numpy as np
import pandas as pd
import datetime
import warnings
warnings.filterwarnings('ignore')
import yfinance as yfin
import ta
import matplotlib.pyplot as plt
import requests

In [3]:
# notebook start time
import time
import datetime
import pytz

start_time = time.time()

# function to print date timestamp
def print_date_time():
  tz_NY = pytz.timezone('Asia/Kolkata')
  datetime_NY = datetime.datetime.now(tz_NY)
  print("Run date time (IST):", datetime_NY.strftime("%Y-%m-%d %H:%M:%S"))

In [4]:
# function to get booked and reserved amount
def get_amt():
  # fetch the JSON data from the URL
  url = "https://raw.githubusercontent.com/ankit-rathi/Tradevesting_v1/main/data/myPortfolioAmts.json"
  response = requests.get(url)
  pf_amts = response.json()  # parse the JSON data

  # extract values from the JSON
  py_booked_amt_dm = pf_amts["py_booked_amt_dm"]
  py_booked_amt_sv = pf_amts["py_booked_amt_sv"]
  cy_booked_amt_dm = pf_amts["cy_booked_amt_dm"]
  cy_booked_amt_sv = pf_amts["cy_booked_amt_sv"]
  reserve_amt_dm = pf_amts["reserve_amt_dm"]
  reserve_amt_sv = pf_amts["reserve_amt_sv"]

  # perform calculations
  py_booked_amt = py_booked_amt_dm + py_booked_amt_sv
  cy_booked_amt = cy_booked_amt_dm + cy_booked_amt_sv
  reserve_amt = reserve_amt_dm + reserve_amt_sv
  total_booked_amt = py_booked_amt + cy_booked_amt

  return total_booked_amt, reserve_amt, cy_booked_amt, py_booked_amt

gen_output = 0

In [5]:
# function to format the amount
def format_amt(number):
    abs_number = abs(number)

    if abs_number >= 1_00_00_000:  # Crores
        formatted_amt = f"{number / 1_00_00_000:.2f} C"
    elif abs_number >= 1_00_000:  # Lakhs
        formatted_amt = f"{number / 1_00_000:.2f} L"
    elif abs_number >= 1_000:  # Thousands
        formatted_amt = f"{number / 1_000:.2f} K"
    else:
        formatted_amt = f"{number:.2f}"

    return formatted_amt

# function to set start and end date
def get_start_end_date():
  start_date = (datetime.date.today() + datetime.timedelta(days=-365)).strftime('%Y-%m-%d')
  end_date = (datetime.date.today() + datetime.timedelta(days=1)).strftime('%Y-%m-%d')
  return start_date, end_date

# function to fetch my portfolio csv
def get_mypfs_df():
  mypfs_df = pd.read_csv('https://raw.githubusercontent.com/ankit-rathi/Tradevesting_v1/main/data/myPortfolioStocks.csv')
  return mypfs_df

# function to fetch my prospects csv
def get_mypps_df():
  mypps_df = pd.read_csv('https://raw.githubusercontent.com/ankit-rathi/Tradevesting_v1/main/data/myProspectsScrips.csv')
  return mypps_df

# function to fetch screener data
def get_myscreen_df():
  myscreen_df = pd.read_csv('https://raw.githubusercontent.com/ankit-rathi/Tradevesting_v1/main/data/myScreenerDB.csv')
  return myscreen_df

# function to fetch momentum data
def get_myinvmt_df():
  myinvmt_df = pd.read_csv('https://raw.githubusercontent.com/ankit-rathi/Tradevesting_v1/main/data/myInvestments.csv')
  return myinvmt_df

# function to get the stock ids
def get_stock_ids(df_pf):
  stock_n100 = df_pf['Symbol'].unique()

  exclude = ['CADILAHC','MMTC', 'MASFIN']

  stock_ids = df_pf[~df_pf['Symbol'].isin(exclude) ]['Symbol'].unique()

  #mypf = mypf[mypf.Forecast.notnull()]
  #stock_ids = mypf['Symbol'].unique()

  #stock_ids.sort()
  return stock_ids

# get features from screener data
def get_screener_features():
  myscreen_df = get_myscreen_df()
  cols = ['Symbol', 'EPS', 'MedPE', 'ROCE%', 'ROE%', 'CapType']
  return myscreen_df[cols]

# get relative strength
def get_relative_strength(stock_list):

    # Dictionary to store stock tickers and their corresponding percentage price change
    stock_changes = {}

    # Loop through each stock and fetch its price data
    for stock in stock_list:
        try:
            # Download the stock data for the given date range
            stock_data = yfin.Ticker(stock + '.NS').history(period='1mo', interval='1d')[map(str.title, ['open', 'close', 'low', 'high', 'volume'])]

            # Calculate the percentage change for the stock
            if len(stock_data) > 0:
                start_price = stock_data['Close'].iloc[0]
                end_price = stock_data['Close'].iloc[-1]
                percent_change = round(((end_price - start_price) / start_price) * 100, 2)
                stock_changes[stock] = percent_change
            else:
                stock_changes[stock] = np.nan  # If no data is available, set to NaN

        except Exception as e:
            print(f"Error fetching data for {stock}: {e}")
            stock_changes[stock] = np.nan

    # Create a DataFrame with stock tickers and their percentage changes
    df = pd.DataFrame(list(stock_changes.items()), columns=['Symbol', 'Percent_Change'])

    # Drop any stocks with missing data (NaN values)
    df = df.dropna()

    # Calculate the percentile rank based on percentage change
    df['RSP'] = round(df['Percent_Change'].rank(pct=True) * 100, 2)
    cols = ['Symbol', 'RSP']
    df = df[cols]
    # Sort by percentile rank (optional)
    df = df.sort_values(by='RSP', ascending=False).reset_index(drop=True)

    return df

In [6]:
# function to get stock technicals
def stock_prec_dev(stock_symbol):
    #stock_symbol = 'ULTRACEMCO.NS'
    short_window = 20
    mid_window = 50
    long_window = 200
    moving_avg = 'SMA'

    start = datetime.datetime(*map(int, start_date.split('-')))
    end = datetime.datetime(*map(int, end_date.split('-')))

    stock_df = yfin.Ticker(stock_symbol + '.NS').history(period='max', interval='1d')[map(str.title, ['open', 'close', 'low', 'high', 'volume'])]

    stock_df['Max'] = round(max(stock_df['Close']),2)
    stock_df = stock_df[(stock_df.index <= end_date) & (stock_df.index >= start_date)]
    stock_df['200_SMA'] = round(stock_df['Close'].rolling(window = 200, min_periods = 1).mean(),0)
    stock_df['Dev%_200'] = round((stock_df['Close'] - stock_df['200_SMA'])*100/stock_df['200_SMA'],2)
    stock_df.dropna(axis = 0, inplace = True) # remove any null rows

    stock_df['20_SMA'] = stock_df['Close'].rolling(window=20).mean()
    stock_df['50_SMA'] = stock_df['Close'].rolling(window=50).mean()
    stock_df['Symbol'] = stock_symbol

    stock_df['Close'] = round(stock_df['Close'],2)
    stock_df['Min'] = round(min(stock_df['Close']),2)
    stock_df['RSI_14'] = ta.momentum.RSIIndicator(close=stock_df['Close'], window=14).rsi()
    stock_df['RSI_14'] = round(stock_df['RSI_14'],0)
    stock_df['Prev_Close'] = stock_df['Close'].shift(1)
    stock_df.drop(['Open', 'Low', 'High', 'Volume'], axis=1, inplace=True)
    stock_df = stock_df.tail(1)

    max_SMA = max(stock_df['20_SMA'].item(), stock_df['50_SMA'].item(), stock_df['200_SMA'].item())
    min_SMA = min(stock_df['20_SMA'].item(), stock_df['50_SMA'].item(), stock_df['200_SMA'].item())
    ABS_Spread = max_SMA - min_SMA
    stock_df['Spread%'] = round((ABS_Spread / stock_df['200_SMA'].item()) * 100,2)

    return stock_df

# function to compute stock attributes
def get_common_features(stock_ids, df_mypf):

  df_prec_dev = pd.DataFrame()
  df_tmp = get_screener_features()
  df_rs = get_relative_strength(stock_ids)

  for stock_id in stock_ids:
      tmp = stock_prec_dev(stock_id)
      tmp = tmp.reset_index()
      df_prec_dev = pd.concat([df_prec_dev, tmp], ignore_index = True)
  df_prec_dev = pd.merge(df_prec_dev, df_mypf, on= 'Symbol')
  df_prec_dev = pd.merge(df_prec_dev, df_tmp, on= 'Symbol', how='left')
  df_prec_dev = pd.merge(df_prec_dev, df_rs, on= 'Symbol', how='left')
  #print(df_prec_dev.columns)
  df_prec_dev['Curr_PE'] = round(df_prec_dev['Close']/df_prec_dev['EPS'],1)
  df_prec_dev['Dev%_PE'] = round((df_prec_dev['Curr_PE'] - df_prec_dev['MedPE'])*100/df_prec_dev['MedPE'],2)
  df_prec_dev['Conviction'] = df_prec_dev['Conviction'] + '-' + df_prec_dev['CapType']
  return df_prec_dev

# function to arrange stock features
def arrange_features(df_stocks, common_cols, diff_cols):
  df_stocks_common = df_stocks[common_cols].drop_duplicates()
  df_stocks_diff = df_stocks[diff_cols]
  df_stocks_diff['Investment'] = df_stocks_diff['AvgCost'] * df_stocks_diff['Shares']
  df_stocks_diff = df_stocks_diff.groupby(['Symbol'])[['Shares', 'Investment']].aggregate(['sum']).reset_index()
  df_stocks_diff.columns = ['Symbol', 'Shares', 'Investment']
  df_stocks_diff['AvgCost'] = round(df_stocks_diff['Investment']/df_stocks_diff['Shares'],2)
  df_stocks = pd.merge(df_stocks_diff, df_stocks_common, on='Symbol')
  return df_stocks

# plot fact distribution across dimension
def plot_pie_chart(df, dimension, fact):
  # grouping the data by category and calculating the sum of fact for each type
  grouped_data = df.groupby(dimension)[fact].sum()

  # sorting the grouped data in descending order
  grouped_data = grouped_data.sort_values(ascending=False)

  # creating a pie chart
  grouped_data.plot.pie(autopct='%1.1f%%', startangle=90, figsize=(6, 6))

  # adding a title and displaying the plot
  plt.title(f'{dimension} {fact} Distribution')
  plt.ylabel('')  # To hide the y-label
  plt.show()

In [7]:
# function to get portfolio features

def get_portfolio_features(df_common_features):

  print_date_time()
  print('-------------------')

  #df_common_features["Target"] = df_common_features["Target"].fillna(df_common_features["Max"])
  df_common_features['NTT'] = np.where(df_common_features['Strategy']== 'NTT', df_common_features["Target"], df_common_features['Max'])
  df_common_features['LTT'] = np.where(df_common_features['Strategy']== 'BTT', df_common_features["Target"], df_common_features['Max'])
  df_common_features['BOL'] = df_common_features['Min']

  tmp_df = df_common_features[df_common_features['Symbol'].isin(mypf_df[mypf_df['InPortfolio'] != 'NA'].Symbol.values)]
  print('qualified stocks: '+str(len(tmp_df['Symbol'].unique())))
  tmp_df1 = tmp_df[tmp_df['LatestQtr'] == 1]
  print('with latest results: '+str(len(tmp_df1['Symbol'].unique())))
  tmp_df1 = tmp_df1[tmp_df1['StarStock'] == 1]
  print('still star stocks: '+str(len(tmp_df1['Symbol'].unique())))
  tmp_df['Investment'] = tmp_df['AvgCost'] * tmp_df['Shares']
  tmp_df['Current'] = round(tmp_df['Close'] * tmp_df['Shares'],0)
  tmp_df['Previous'] = tmp_df['Prev_Close'] * tmp_df['Shares']
  tmp_df['EstimatedST'] = tmp_df['NTT'] * tmp_df['Shares']
  tmp_df['EstimatedLT'] = tmp_df['LTT'] * tmp_df['Shares']
  tmp_df['Current P/L'] = round((tmp_df['Current'] - tmp_df['Investment']),0)
  tmp_df['Today P/L%'] = round((tmp_df['Current'] - tmp_df['Previous'])*100/tmp_df['Previous'],2)
  tmp_df['Current P/L%'] = round((tmp_df['Current'] - tmp_df['Investment'])*100/tmp_df['Investment'],2)
  tmp_df['EstimatedST P/L%'] = round((tmp_df['EstimatedST'] - tmp_df['Investment'])*100/tmp_df['Investment'],2)
  tmp_df['EstimatedLT P/L%'] = round((tmp_df['EstimatedLT'] - tmp_df['Investment'])*100/tmp_df['Investment'],2)
  tmp_df['NTT%'] = round((tmp_df['NTT'] - tmp_df['Close'])*100/tmp_df['Close'],2)
  tmp_df['LTT%'] = round((tmp_df['LTT'] - tmp_df['Close'])*100/tmp_df['Close'],2)
  tmp_df['Gained%'] = round((tmp_df['Close'] - tmp_df['BOL'])*100/tmp_df['BOL'],2)
  investment = round(sum(tmp_df['AvgCost']*tmp_df['Shares']),0)
  current = round(sum(tmp_df['Close']*tmp_df['Shares']),0)
  tmp_df['InitAlloc%'] = round(tmp_df['Investment']*100/investment,2)
  tmp_df['CurrAlloc%'] = round(tmp_df['Current']*100/current,2)
  tmp_df['FTT'] = tmp_df['LTT']
  tmp_df.loc[tmp_df['Strategy'] == 'NTT', 'FTT'] = tmp_df['NTT']
  tmp_df['FTT%'] = tmp_df['LTT%']
  tmp_df.loc[tmp_df['Strategy'] == 'NTT', 'FTT%'] = tmp_df['NTT%']
  tmp_df['FTT Amt'] = round(tmp_df['FTT%'] * tmp_df['Current']/100,0)
  tmp_df['OTT%'] = round((tmp_df['FTT'] - tmp_df['AvgCost'])*100/tmp_df['AvgCost'],2)
  tmp_df['RRR Ind'] = round(tmp_df['Current P/L']/tmp_df['FTT Amt'],2)
  tmp_df['Risk Ind'] = round(tmp_df['Current P/L%']*tmp_df['CurrAlloc%'],0)

  return tmp_df

# function to print portfolio features
def print_portfolio_stats(df_portfolio_features, myinvmt_df):
  from pyxirr import xirr

  total_booked_amt, reserve_amt, cy_booked_amt, py_booked_amt = get_amt()

  dates = myinvmt_df['Date'].values
  dates = np.append(dates, datetime.date.today().strftime('%d-%b-%y'))
  investment = myinvmt_df['Investment'].values
  dates= pd.to_datetime(dates)

  current = round(sum(df_portfolio_features['Close']*df_portfolio_features['Shares']),0) + reserve_amt
  investment_xirr = np.append(investment, current)
  cagr = round(xirr(pd.DataFrame({"dates": dates, "amounts": investment_xirr}))*100,2)

  investment = -sum(investment)
  invested = round(sum(df_portfolio_features['AvgCost']*df_portfolio_features['Shares']),0) + reserve_amt
  previous = round(sum(df_portfolio_features['Prev_Close']*df_portfolio_features['Shares']),0) + reserve_amt
  cy_invested = investment + py_booked_amt

  today_pnl_amount = current-previous
  today_pnl_percentage = round((current-previous)*100/previous,2)

  curr_pnl_amount = current-invested
  curr_pnl_percentage = round((curr_pnl_amount)*100/(cy_invested),2)

  cy_pnl_amount = cy_booked_amt + curr_pnl_amount
  cy_pnl_percentage = round((cy_pnl_amount)*100/cy_invested,2)

  overall_pnl_amount = total_booked_amt + curr_pnl_amount
  overall_pnl_percentage = round((overall_pnl_amount)*100/investment,2)

  estimate_st = round(sum(df_portfolio_features['FTT']*df_portfolio_features['Shares']),0)  + reserve_amt
  est_st_pnl_amount = estimate_st-current
  est_st_pnl_percentage = round((est_st_pnl_amount)*100/current,2)

  estimate_lt = round(sum(df_portfolio_features['LTT']*df_portfolio_features['Shares']),0)  + reserve_amt
  est_lt_pnl_amount = estimate_lt-current
  est_lt_pnl_percentage = round((est_lt_pnl_amount)*100/current,2)

  total_profit = round(sum(df_portfolio_features[df_portfolio_features['Current P/L%'] > 0]['Current']) - sum(df_portfolio_features[df_portfolio_features['Current P/L%'] > 0]['Investment']),0)
  total_loss = round(sum(df_portfolio_features[df_portfolio_features['Current P/L%'] < 0]['Current']) - sum(df_portfolio_features[df_portfolio_features['Current P/L%'] < 0]['Investment']),0)

  cy_booked_percentage = round((cy_booked_amt)*100/current,2)
  py_booked_percentage = round((py_booked_amt)*100/investment,2)
  total_booked_percentage = round((total_booked_amt)*100/investment,2)

  print('-------------------')
  print('Initial Investment: ', format_amt(investment))
  print('CY Investment: ', format_amt(cy_invested))
  print('Reserve: ', format_amt(reserve_amt))
  print('Current: ',  format_amt(current))
  print('-------------------')
  print('Today PnL: '+ '{} ({}%)'.format(format_amt(today_pnl_amount), today_pnl_percentage))
  print('Current PnL: '+ '{} ({}%)'.format(format_amt(curr_pnl_amount), curr_pnl_percentage))
  print('CY Booked + Current PnL: '+ '{} ({}%)'.format(format_amt(cy_pnl_amount), cy_pnl_percentage))
  print('-------------------')
  print('Total profit: ', format_amt(total_profit))
  print('Total loss: ', format_amt(total_loss))
  print('-------------------')
  print('Total Booked + Current PnL: '+ '{} ({}%)'.format(format_amt(overall_pnl_amount), overall_pnl_percentage))
  print('Total Booked PnL: '+ '{} ({}%)'.format(format_amt(total_booked_amt), total_booked_percentage))
  print('Curr Year Booked PnL: '+ '{} ({}%)'.format(format_amt(cy_booked_amt), cy_booked_percentage))
  print('Prev Year Booked PnL: '+ '{} ({}%)'.format(format_amt(py_booked_amt), py_booked_percentage))
  print('===================')
  print('Est FTT: ',  format_amt(estimate_st))
  print('Est FTT PnL: '+ '{} ({}%)'.format(format_amt(est_st_pnl_amount), est_st_pnl_percentage))

  print('===================')
  print('Deployed: ', format_amt(investment))

  print('Current: ', format_amt(current))

  print('CAGR/XIRR %: '+'{}%'.format(cagr))

In [8]:
# get start and end date
start_date, end_date = get_start_end_date()

# get portfolio and prospects data
mypfs_df = get_mypfs_df()
mypps_df = get_mypps_df()
myinvmt_df = get_myinvmt_df()

# merge above datasets
mypf_df = pd.merge(mypfs_df, mypps_df, on="Symbol")

# seggregate dm and sv portfolio
dm_pf = mypf_df[mypf_df['InPortfolio'] == 'DM']
sv_pf = mypf_df[mypf_df['InPortfolio'] == 'SV']

# build portfolio stock dataframe
dm_stocks = get_stock_ids(dm_pf)
sv_stocks = get_stock_ids(sv_pf)
df_stocks = pd.concat([dm_pf,sv_pf], ignore_index = True)

# arrange common and diff stock features
common_cols = ['Symbol', 'Target', 'Criteria', 'Strategy', 'CumlRnk', 'LatestQtr', 'StarStock', 'Conviction', 'Category', 'InFolio', 'XIRR', 'MBQ']
diff_cols = ['Symbol', 'AvgCost', 'Shares']
df_stocks = arrange_features(df_stocks, common_cols, diff_cols)

# get common features
stock_ids = df_stocks['Symbol'].values
df_common_features = get_common_features(stock_ids, df_stocks)

df_common_features.reset_index(drop=True, inplace=True)
df_common_features.drop(['Date'], axis=1, inplace=True)
# get and print portfolio features
df_portfolio_features = get_portfolio_features(df_common_features)

print_portfolio_stats(df_portfolio_features, myinvmt_df)

df = df_portfolio_features
#plot_pie_chart(df, 'CapType', 'Current')
list_ox40n = list(df[df['MBQ'].str.contains('OX40N', na=False)]['Symbol'].values)

Run date time (IST): 2026-08-25 08:27:00
-------------------
qualified stocks: 87
with latest results: 30
still star stocks: 19

-------------------
Initial Investment:  1.46 C
CY Investment:  1.89 C
Reserve:  3.69 L
Current:  1.58 C
-------------------
Today PnL: -5.99 K (-0.04%)
Current PnL: -35.15 L (-18.61%)
CY Booked + Current PnL: -30.09 L (-15.93%)
-------------------
Total profit:  3.62 L
Total loss:  -38.77 L
-------------------
Total Booked + Current PnL: 12.78 L (8.75%)
Total Booked PnL: 47.93 L (32.82%)
Curr Year Booked PnL: 5.06 L (3.21%)
Prev Year Booked PnL: 42.87 L (29.35%)
===================
Est FTT:  2.67 C
Est FTT PnL: 1.09 C (69.26%)
===================
Deployed:  1.46 C
Current:  1.58 C
CAGR/XIRR %: 3.48%

In [9]:
# top 5 near their targets
cols = ['Symbol', 'Today P/L%', 'Current P/L%', 'FTT%', 'OTT%', 'FTT Amt', 'Current P/L', 'Current', 'FTT', 'Dev%_PE', 'RSI_14','Conviction', 'Spread%',  'CumlRnk', 'RRR Ind', 'CurrAlloc%', 'Gained%', 'Criteria', 'Strategy', 'Category']
df_tmp = df_portfolio_features[~df_portfolio_features['Symbol'].isin(['ENRIN','BLUSPRING','DIGITIDE'])]
df_tmp = df_tmp.sort_values(by = 'FTT Amt', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
66,SIEMENS,4.95,10.53,0.27,10.83,555.0,19605.0,205700.0,4125.00,-10.49,70.0,H-LC,14.77,51.0,35.32,1.33,45.13,AR,NTT,ELECTRICAL
78,UNITDSPR,0.78,14.30,5.66,20.77,15148.0,33488.0,267632.0,1644.00,-2.51,66.0,X-MC,11.98,64.0,2.21,1.74,28.65,X40N,NTT,BREWERIES
77,TTKPRESTIG,-0.17,-23.09,30.14,0.09,23360.0,-23271.0,77506.0,770.00,-6.45,42.0,M-SC,9.05,250.0,-1.00,0.50,39.50,OX40N,NTT,DURABLES
52,M&M,0.06,7.81,10.22,18.82,26518.0,18791.0,259472.0,3762.88,-6.96,57.0,X-LC,5.09,25.0,0.71,1.68,17.70,X40N,ATH,AUTO
67,SIS,1.10,-4.06,26.39,21.26,28112.0,-4506.0,106526.0,528.00,104.78,42.0,H-SC,20.12,168.0,-0.16,0.69,58.39,OX40N,NTT,MISC

In [10]:
# top 5 today
df_tmp = df_portfolio_features.sort_values(by = 'Today P/L%', ascending=False)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
30,HAPPSTMNDS,7.30,-44.50,229.89,83.08,163516.0,-57037.0,71128.0,1466.54,NaN,70.0,NaN,6.55,152.0,-0.35,0.46,33.23,AR,ATH,IT
3,ALKYLAMINE,6.70,-12.58,120.24,92.54,106131.0,-12697.0,88266.0,4520.85,NaN,67.0,NaN,15.58,142.0,-0.12,0.57,67.61,SR,ATH,CHEMICALS
66,SIEMENS,4.95,10.53,0.27,10.83,555.0,19605.0,205700.0,4125.00,-10.49,70.0,H-LC,14.77,51.0,35.32,1.33,45.13,AR,NTT,ELECTRICAL
6,AWL,3.06,-33.23,150.15,67.02,357193.0,-118418.0,237891.0,485.00,-50.79,56.0,X-SC,8.19,81.0,-0.33,1.54,13.12,XY24,NTT,FMCG
69,SURYODAY,2.78,-9.52,35.99,23.03,58310.0,-17054.0,162017.0,216.00,-25.86,44.0,H-SC,15.09,166.0,-0.29,1.05,37.52,XR,NTT,BANKS

In [11]:
# bottom 5 today
df_tmp = df_portfolio_features.sort_values(by = 'Today P/L%', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
80,VAIBHAVGBL,-2.90,-32.27,137.36,60.77,170049.0,-58977.0,123798.0,521.0,NaN,33.0,NaN,6.25,160.0,-0.35,0.80,26.75,XR,NTT,JEWELLERY
81,VALIANTORG,-2.65,-37.09,176.84,74.15,182000.0,-60687.0,102918.0,838.0,NaN,53.0,NaN,9.62,145.0,-0.33,0.67,53.16,XR,NTT,CHEMICALS
12,BOSCH-HCIL,-2.64,-24.40,32.27,-0.01,31178.0,-31188.0,96617.0,2282.0,754.87,70.0,M-SC,10.67,231.0,-1.00,0.63,64.46,OX40N,BTT,AC
57,RAJESHEXPO,-2.39,-85.07,570.20,0.07,116788.0,-116695.0,20482.0,518.0,NaN,29.0,NaN,37.15,268.0,-1.00,0.13,1.15,OX40N,NTT,JEWELLERY
24,EASEMYTRIP,-2.24,-66.28,332.08,45.70,197989.0,-117194.0,59621.0,26.4,NaN,36.0,NaN,8.24,204.0,-0.59,0.39,4.44,XY24,NTT,TRAVEL

In [12]:
# top 5 to exit based on CumlRnk
df_tmp = df_portfolio_features[~df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])]
df_tmp = df_tmp[(df_tmp['Current P/L%'] > -1) & (df_tmp['Current P/L%'] < 1)].sort_values(by = 'CumlRnk', ascending=False)
df_tmp[cols].head()

Empty DataFrame
Columns: [Symbol, Today P/L%, Current P/L%, FTT%, OTT%, FTT Amt, Current P/L, Current, FTT, Dev%_PE, RSI_14, Conviction, Spread%, CumlRnk, RRR Ind, CurrAlloc%, Gained%, Criteria, Strategy, Category]
Index: []

In [13]:
# OX40N stocks to exit
df_tmp = df_portfolio_features[(df_portfolio_features['Symbol'].isin(list_ox40n))].sort_values(by = 'Current P/L%', ascending=False)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
25,FINCABLES,2.47,63.59,27.09,107.91,65430.0,93885.0,241529.0,1641.55,19.27,68.0,M-SC,23.63,220.0,1.43,1.57,81.71,OX40N,ATH,CABLES
67,SIS,1.10,-4.06,26.39,21.26,28112.0,-4506.0,106526.0,528.00,104.78,42.0,H-SC,20.12,168.0,-0.16,0.69,58.39,OX40N,NTT,MISC
43,INDIGOPNTS,1.87,-18.18,22.24,0.02,31764.0,-31736.0,142823.0,1408.00,-21.90,61.0,M-SC,8.14,222.0,-1.00,0.93,62.04,OX40N,NTT,PAINTS
77,TTKPRESTIG,-0.17,-23.09,30.14,0.09,23360.0,-23271.0,77506.0,770.00,-6.45,42.0,M-SC,9.05,250.0,-1.00,0.50,39.50,OX40N,NTT,DURABLES
16,CERA,0.12,-23.31,61.54,23.89,83021.0,-40997.0,134906.0,9475.00,NaN,42.0,NaN,13.02,153.0,-0.49,0.88,31.14,OX40N,NTT,CERAMICS

In [14]:
# top 5 to book for rotation
df_tmp = df_portfolio_features[(df_portfolio_features['Current P/L%'] > 20) ].sort_values(by = 'CumlRnk', ascending=False)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
25,FINCABLES,2.47,63.59,27.09,107.91,65430.0,93885.0,241529.0,1641.55,19.27,68.0,M-SC,23.63,220.0,1.43,1.57,81.71,OX40N,ATH,CABLES

In [15]:
# top 5 to monitor for exit
df_tmp = df_portfolio_features[~df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])]
df_tmp = df_tmp[(df_tmp['Current P/L%'] > 0) ].sort_values(by = 'Dev%_PE', ascending=False)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
25,FINCABLES,2.47,63.59,27.09,107.91,65430.0,93885.0,241529.0,1641.55,19.27,68.0,M-SC,23.63,220.0,1.43,1.57,81.71,OX40N,ATH,CABLES
68,STARHEALTH,0.52,11.95,31.55,47.26,99289.0,33581.0,314704.0,761.00,-1.35,47.0,H-SC,15.77,173.0,0.34,2.04,36.07,XY24,NTT,INSURANCE

In [16]:
# top 5 to book for rotation from weak conviction
df_tmp = df_portfolio_features[~df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])]
df_tmp = df_tmp[~df_tmp['Criteria'].isin(['XY25','XY24','X40', 'X40N'])].sort_values(by = 'RRR Ind', ascending=False)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
25,FINCABLES,2.47,63.59,27.09,107.91,65430.0,93885.0,241529.0,1641.55,19.27,68.0,M-SC,23.63,220.0,1.43,1.57,81.71,OX40N,ATH,CABLES
3,ALKYLAMINE,6.70,-12.58,120.24,92.54,106131.0,-12697.0,88266.0,4520.85,NaN,67.0,NaN,15.58,142.0,-0.12,0.57,67.61,SR,ATH,CHEMICALS
67,SIS,1.10,-4.06,26.39,21.26,28112.0,-4506.0,106526.0,528.00,104.78,42.0,H-SC,20.12,168.0,-0.16,0.69,58.39,OX40N,NTT,MISC
42,INDIAMART,0.22,-24.97,167.79,100.92,155270.0,-30798.0,92538.0,4675.60,NaN,38.0,NaN,13.46,140.0,-0.20,0.60,0.67,AR,ATH,MISC
71,TANLA,-1.06,-36.21,240.60,117.25,415531.0,-98055.0,172706.0,1922.32,NaN,43.0,NaN,14.99,147.0,-0.24,1.12,51.21,AR,ATH,IT

In [17]:
# top 5 to accumulate based on lowest RSI_14
df_tmp = df_portfolio_features[df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])].sort_values(by = 'RSI_14', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
56,PGHH,-0.75,-39.10,116.76,32.01,151835.0,-83480.0,130040.0,17616.87,-55.19,24.0,X-SC,19.82,57.0,-0.55,0.84,0.00,X40,ATH,FMCG
55,PAGEIND,-0.07,-7.46,43.56,32.85,108186.0,-20019.0,248360.0,50936.07,-31.21,30.0,X-MC,8.63,55.0,-0.19,1.61,18.60,X40,ATH,APPARELS
75,TMPV,-1.10,-25.20,90.84,42.75,282745.0,-104851.0,311256.0,600.00,-84.91,31.0,X-LC,4.32,4.0,-0.37,2.02,7.03,XY24,NTT,AUTO
19,COLPAL,-1.10,-28.27,94.99,39.86,179436.0,-74465.0,188900.0,3683.41,-13.17,32.0,X-MC,2.32,62.0,-0.41,1.23,6.85,XY25,ATH,FMCG
20,DABUR,-0.51,-22.10,84.46,43.70,163217.0,-54820.0,193248.0,735.00,-32.86,33.0,X-MC,10.64,70.0,-0.34,1.25,0.00,XY24,BTT,FMCG

In [18]:
# top 5 to accumulate based on Spread and CumlRnk
df_tmp = df_portfolio_features[df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])]
df_tmp = df_tmp[(df_tmp['CumlRnk'] < 100)].sort_values(by = 'Spread%', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
50,KOTAKBANK,1.37,5.87,12.33,18.92,31289.0,14062.0,253764.0,452.46,-10.58,62.0,X-LC,2.09,12.0,0.45,1.65,14.18,X40,ATH,BANKS
19,COLPAL,-1.10,-28.27,94.99,39.86,179436.0,-74465.0,188900.0,3683.41,-13.17,32.0,X-MC,2.32,62.0,-0.41,1.23,6.85,XY25,ATH,FMCG
23,DMART,0.87,-3.96,36.84,31.42,110314.0,-12350.0,299440.0,5391.45,-19.48,44.0,X-LC,2.53,14.0,-0.11,1.94,8.05,X40N,ATH,FMCG
1,ABBOTINDIA,0.72,-11.37,30.17,15.37,47825.0,-20335.0,158520.0,34390.26,-27.79,39.0,X-MC,2.59,58.0,-0.43,1.03,7.38,X40,ATH,PHARMA
53,MARUTI,-1.77,-1.24,26.21,24.64,63997.0,-3068.0,244170.0,17120.06,-6.90,43.0,X-LC,3.86,33.0,-0.05,1.58,11.34,XR,ATH,AUTO

In [19]:
# top 5 to accumulate based on lowest Gained%
df_tmp = df_portfolio_features[df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])].sort_values(by = 'Gained%', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
20,DABUR,-0.51,-22.10,84.46,43.70,163217.0,-54820.0,193248.0,735.00,-32.86,33.0,X-MC,10.64,70.0,-0.34,1.25,0.00,XY24,BTT,FMCG
56,PGHH,-0.75,-39.10,116.76,32.01,151835.0,-83480.0,130040.0,17616.87,-55.19,24.0,X-SC,19.82,57.0,-0.55,0.84,0.00,X40,ATH,FMCG
36,HINDUNILVR,0.74,-15.55,43.94,21.56,124877.0,-52317.0,284200.0,2922.00,-41.80,40.0,X-LC,7.06,9.0,-0.42,1.84,0.74,XY25,NTT,FMCG
47,ITC,0.11,-25.60,67.59,24.70,199790.0,-101687.0,295591.0,452.00,-30.75,36.0,X-LC,10.75,1.0,-0.51,1.92,0.99,X40,NTT,FMCG
34,HDFCBANK,0.28,-10.96,47.19,31.05,123157.0,-32138.0,260982.0,1073.00,-27.99,40.0,X-LC,12.65,26.0,-0.26,1.69,1.30,X40,BTT,BANKS

In [20]:
# top 5 to accumulate based on lowest CurrAlloc%
df_tmp = df_portfolio_features[df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])].sort_values(by = 'CurrAlloc%', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
56,PGHH,-0.75,-39.10,116.76,32.01,151835.0,-83480.0,130040.0,17616.87,-55.19,24.0,X-SC,19.82,57.0,-0.55,0.84,0.00,X40,ATH,FMCG
2,ACC,-0.50,-41.78,200.25,74.81,312606.0,-112020.0,156108.0,3906.00,-42.24,38.0,X-SC,11.36,85.0,-0.36,1.01,4.29,XY24,BTT,CEMENT
1,ABBOTINDIA,0.72,-11.37,30.17,15.37,47825.0,-20335.0,158520.0,34390.26,-27.79,39.0,X-MC,2.59,58.0,-0.43,1.03,7.38,X40,ATH,PHARMA
40,ICICIPRULI,-0.73,-15.40,53.99,30.28,89984.0,-30337.0,166668.0,787.27,-45.75,54.0,X-MC,11.81,78.0,-0.34,1.08,11.04,X40,ATH,INSURANCE
39,ICICIGI,-0.49,-14.35,38.80,18.89,66504.0,-28707.0,171402.0,2244.41,-14.59,41.0,X-MC,10.05,66.0,-0.43,1.11,2.12,X40,ATH,INSURANCE

In [21]:
# top 5 to accumulate based on CumlRnk
df_tmp = df_portfolio_features.sort_values(by = 'CumlRnk', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
47,ITC,0.11,-25.60,67.59,24.70,199790.0,-101687.0,295591.0,452.00,-30.75,36.0,X-LC,10.75,1.0,-0.51,1.92,0.99,X40,NTT,FMCG
73,TCS,-0.78,-32.95,85.22,24.20,264726.0,-152635.0,310638.0,4230.71,-44.31,46.0,X-LC,13.45,2.0,-0.58,2.02,15.84,X40,ATH,IT
45,INFY,0.80,-19.56,74.51,40.38,225646.0,-73630.0,302840.0,1972.00,-40.86,49.0,X-LC,15.49,3.0,-0.33,1.97,14.69,X40,NTT,IT
75,TMPV,-1.10,-25.20,90.84,42.75,282745.0,-104851.0,311256.0,600.00,-84.91,31.0,X-LC,4.32,4.0,-0.37,2.02,7.03,XY24,NTT,AUTO
33,HCLTECH,1.50,-11.58,40.20,23.97,110009.0,-35832.0,273654.0,1853.42,-13.84,54.0,X-LC,10.01,8.0,-0.33,1.78,29.13,X40,ATH,IT

In [22]:
# top 5 for average up
df_tmp = df_portfolio_features[(df_portfolio_features['Dev%_200'] > 5)].sort_values(by = 'CurrAlloc%', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
44,INDUSINDBK,-0.24,-25.76,79.00,32.89,45282.0,-19888.0,57319.0,1800.00,322.36,49.0,L-MC,12.17,258.0,-0.44,0.37,41.32,XR,NTT,BANKS
30,HAPPSTMNDS,7.30,-44.50,229.89,83.08,163516.0,-57037.0,71128.0,1466.54,NaN,70.0,NaN,6.55,152.0,-0.35,0.46,33.23,AR,ATH,IT
3,ALKYLAMINE,6.70,-12.58,120.24,92.54,106131.0,-12697.0,88266.0,4520.85,NaN,67.0,NaN,15.58,142.0,-0.12,0.57,67.61,SR,ATH,CHEMICALS
12,BOSCH-HCIL,-2.64,-24.40,32.27,-0.01,31178.0,-31188.0,96617.0,2282.00,754.87,70.0,M-SC,10.67,231.0,-1.00,0.63,64.46,OX40N,BTT,AC
81,VALIANTORG,-2.65,-37.09,176.84,74.15,182000.0,-60687.0,102918.0,838.00,NaN,53.0,NaN,9.62,145.0,-0.33,0.67,53.16,XR,NTT,CHEMICALS

In [23]:
# top 5 RSP
df_tmp = df_portfolio_features.sort_values(by = 'RSP', ascending=False)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
25,FINCABLES,2.47,63.59,27.09,107.91,65430.0,93885.0,241529.0,1641.55,19.27,68.0,M-SC,23.63,220.0,1.43,1.57,81.71,OX40N,ATH,CABLES
27,GLAXO,1.02,17.69,15.30,35.69,35884.0,35252.0,234536.0,3380.16,-11.76,70.0,X-MC,12.23,56.0,0.98,1.52,39.39,X40,ATH,PHARMA
38,HYUNDAI,-0.53,14.16,26.09,43.94,74855.0,35578.0,286910.0,2782.73,18.18,62.0,X-LC,6.54,29.0,0.48,1.86,31.73,X40N,ATH,AUTO
66,SIEMENS,4.95,10.53,0.27,10.83,555.0,19605.0,205700.0,4125.00,-10.49,70.0,H-LC,14.77,51.0,35.32,1.33,45.13,AR,NTT,ELECTRICAL
45,INFY,0.80,-19.56,74.51,40.38,225646.0,-73630.0,302840.0,1972.00,-40.86,49.0,X-LC,15.49,3.0,-0.33,1.97,14.69,X40,NTT,IT

In [24]:
# Top N allocation
df_tmp = df_portfolio_features.sort_values(by = 'CurrAlloc%', ascending=False)
top_n_values = [10, 25, 50]

sum_df = pd.DataFrame({
    'Top_N': top_n_values,
    'Sum_Alloc%': [df_tmp['CurrAlloc%'].head(n).sum() for n in top_n_values]
})

sum_df

   Top_N  Sum_Alloc%
0     10       19.62
1     25       45.00
2     50       77.63

In [25]:
# market-cap-wise allocation
df_tmp = df_portfolio_features[cols]
df_tmp.groupby(df_tmp['Conviction'].str[-2:])['CurrAlloc%'].sum().sort_values(ascending=False)

Conviction
LC    38.12
MC    22.19
SC    21.63
Name: CurrAlloc%, dtype: float64

In [26]:
# criteria-wise allocation
df_portfolio_features.groupby('Criteria')['CurrAlloc%'].sum().sort_values(ascending=False)

Criteria
X40      26.72
XY24     23.92
X40N     18.68
XR        9.07
OX40N     7.34
XY25      7.18
AR        6.17
SR        0.90
Name: CurrAlloc%, dtype: float64

In [27]:
# conviction-wise allocation
df_portfolio_features.groupby('Conviction')['CurrAlloc%'].sum().sort_values(ascending=False)

Conviction
X-LC    34.36
X-MC    19.63
H-SC     8.55
X-SC     7.64
M-SC     5.44
H-LC     2.94
M-MC     1.17
H-MC     1.02
M-LC     0.82
L-MC     0.37
Name: CurrAlloc%, dtype: float64

In [28]:
# sector-wise stats
df_tmp = df_portfolio_features.groupby('Category')[['CurrAlloc%', 'Current', 'Current P/L', 'FTT Amt']].sum().sort_values(by=['Current', 'Current P/L'], ascending=False)
df_tmp['Current P/L%'] = round(df_tmp['Current P/L'] * 100 / df_tmp['Current'], 2)
df_tmp['FTT%'] = round(df_tmp['FTT Amt'] * 100 / df_tmp['Current'], 2)
cols = ['CurrAlloc%', 'Current P/L%', 'FTT%']
df_tmp[cols].sort_values(by=['CurrAlloc%'], ascending=False)

               CurrAlloc%  Current P/L%    FTT%
Category
FMCG                15.36        -25.86   71.00
IT                  11.24        -37.75  106.08
FINANCE             10.68        -17.35   67.90
AUTO                 8.21         -6.83   45.09
BANKS                6.27        -10.40   58.01
MISC                 5.92        -35.25   89.65
PHARMA               5.88          8.42   17.55
INSURANCE            5.77         -4.32   41.20
PAINTS               5.48        -16.95   36.90
ELECTRICAL           4.25         -7.85   41.62
AC                   1.84        -12.95   43.58
BREWERIES            1.74         12.51    5.66
REFINERIES           1.73        -11.56   49.03
FOOTWEAR             1.67        -71.33  140.03
APPARELS             1.61         -8.06   43.56
CABLES               1.57         38.87   27.09
DURABLES             1.48        -69.28  110.46
TRAVEL               1.41       -106.02  209.17
CERAMICS             1.31        -52.36   98.65
ENGINEERING          1.24        -26.23   83.97
CHEMICALS            1.24        -38.38  150.71
CEMENT               1.01        -71.76  200.25
JEWELLERY            0.93       -121.76  198.81
ENTERTAINMENT        0.70        -77.87  183.95
HEALTHCARE           0.69        -70.89  113.78
TEXTILES             0.39        -52.89   96.48
HOTELS               0.36       -103.37  175.10

In [29]:
# money to be made criteria-wise
df_portfolio_features.groupby('Criteria')['FTT Amt'].agg(['sum', 'count']).sort_values(by='sum', ascending=False)

                sum  count
Criteria
XY24      3641435.0     19
X40       2104475.0     18
XR        1395874.0     13
X40N      1200975.0     12
AR        1054752.0      8
OX40N      661604.0     10
XY25       592388.0      5
SR         276662.0      2

In [30]:
# money to be made conviction-wise
df_portfolio_features.groupby('Conviction')['FTT Amt'].agg(['sum', 'count']).sort_values(by='sum', ascending=False)

                  sum  count
Conviction
X-LC        2431102.0     19
X-MC        1477381.0     14
X-SC        1097999.0      6
H-SC         832744.0      8
M-SC         327203.0      6
H-MC         256185.0      1
M-LC         165892.0      1
M-MC          64960.0      1
L-MC          45282.0      1
H-LC          37015.0      2

In [31]:
# money to be made criteria and conviction-wise
df_portfolio_features.groupby(['Conviction', 'Criteria'])['FTT Amt'].agg(['sum', 'count']).sort_values(by='sum', ascending=False)

                           sum  count
Conviction Criteria
X-LC       X40       1218906.0      9
X-SC       XY24       669799.0      2
H-SC       XY24       526857.0      3
X-MC       X40        513157.0      6
X-LC       XY24       469803.0      2
X-MC       X40N       455559.0      4
X-LC       X40N       422511.0      5
X-MC       XY25       271543.0      2
H-MC       XY24       256185.0      1
X-LC       XY25       255885.0      2
X-SC       X40        255401.0      2
X-MC       XY24       237122.0      2
H-SC       OX40N      219218.0      3
X-SC       X40N       172799.0      2
M-LC       XR         165892.0      1
M-SC       OX40N      151732.0      4
           XY24       117253.0      1
H-SC       XR          86669.0      2
M-MC       XY25        64960.0      1
X-LC       XR          63997.0      1
M-SC       XR          58218.0      1
L-MC       XR          45282.0      1
H-LC       AR          37015.0      2

In [32]:
# notebook execution time

end_time = time.time()
execution_time = round(end_time - start_time, 0)
print(f"Notebook execution time: {execution_time} seconds")

Notebook execution time: 34.0 seconds