<a href="https://colab.research.google.com/github/ankit-rathi/Quantvesting_v2/blob/main/myStocks_Portfolio_Analysis.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
'''
!pip install pandas==2.2.2 -qq
!pip install pyxirr -qq
!pip install ta -qq
!pip install yfinance==0.2.59 -qq
'''

'\n!pip install pandas==2.2.2 -qq\n!pip install pyxirr -qq\n!pip install ta -qq\n!pip install yfinance==0.2.59 -qq\n'

In [2]:
# import libraries

import numpy as np
import pandas as pd
import datetime
import warnings
warnings.filterwarnings('ignore')
import yfinance as yfin
import ta
import matplotlib.pyplot as plt
import requests

In [3]:
# notebook start time
import time
import datetime
import pytz

start_time = time.time()

# function to print date timestamp
def print_date_time():
  tz_NY = pytz.timezone('Asia/Kolkata')
  datetime_NY = datetime.datetime.now(tz_NY)
  print("Run date time (IST):", datetime_NY.strftime("%Y-%m-%d %H:%M:%S"))

In [4]:
# function to get booked and reserved amount
def get_amt():
  # fetch the JSON data from the URL
  url = "https://raw.githubusercontent.com/ankit-rathi/Tradevesting_v1/main/data/myPortfolioAmts.json"
  response = requests.get(url)
  pf_amts = response.json()  # parse the JSON data

  # extract values from the JSON
  py_booked_amt_dm = pf_amts["py_booked_amt_dm"]
  py_booked_amt_sv = pf_amts["py_booked_amt_sv"]
  cy_booked_amt_dm = pf_amts["cy_booked_amt_dm"]
  cy_booked_amt_sv = pf_amts["cy_booked_amt_sv"]
  reserve_amt_dm = pf_amts["reserve_amt_dm"]
  reserve_amt_sv = pf_amts["reserve_amt_sv"]

  # perform calculations
  py_booked_amt = py_booked_amt_dm + py_booked_amt_sv
  cy_booked_amt = cy_booked_amt_dm + cy_booked_amt_sv
  reserve_amt = reserve_amt_dm + reserve_amt_sv
  total_booked_amt = py_booked_amt + cy_booked_amt

  return total_booked_amt, reserve_amt, cy_booked_amt, py_booked_amt

gen_output = 0

In [5]:
# function to format the amount
def format_amt(number):
    abs_number = abs(number)

    if abs_number >= 1_00_00_000:  # Crores
        formatted_amt = f"{number / 1_00_00_000:.2f} C"
    elif abs_number >= 1_00_000:  # Lakhs
        formatted_amt = f"{number / 1_00_000:.2f} L"
    elif abs_number >= 1_000:  # Thousands
        formatted_amt = f"{number / 1_000:.2f} K"
    else:
        formatted_amt = f"{number:.2f}"

    return formatted_amt

# function to set start and end date
def get_start_end_date():
  start_date = (datetime.date.today() + datetime.timedelta(days=-365)).strftime('%Y-%m-%d')
  end_date = (datetime.date.today() + datetime.timedelta(days=1)).strftime('%Y-%m-%d')
  return start_date, end_date

# function to fetch my portfolio csv
def get_mypfs_df():
  mypfs_df = pd.read_csv('https://raw.githubusercontent.com/ankit-rathi/Tradevesting_v1/main/data/myPortfolioStocks.csv')
  return mypfs_df

# function to fetch my prospects csv
def get_mypps_df():
  mypps_df = pd.read_csv('https://raw.githubusercontent.com/ankit-rathi/Tradevesting_v1/main/data/myProspectsScrips.csv')
  return mypps_df

# function to fetch screener data
def get_myscreen_df():
  myscreen_df = pd.read_csv('https://raw.githubusercontent.com/ankit-rathi/Tradevesting_v1/main/data/myScreenerDB.csv')
  return myscreen_df

# function to fetch momentum data
def get_myinvmt_df():
  myinvmt_df = pd.read_csv('https://raw.githubusercontent.com/ankit-rathi/Tradevesting_v1/main/data/myInvestments.csv')
  return myinvmt_df

# function to get the stock ids
def get_stock_ids(df_pf):
  stock_n100 = df_pf['Symbol'].unique()

  exclude = ['CADILAHC','MMTC', 'MASFIN']

  stock_ids = df_pf[~df_pf['Symbol'].isin(exclude) ]['Symbol'].unique()

  #mypf = mypf[mypf.Forecast.notnull()]
  #stock_ids = mypf['Symbol'].unique()

  #stock_ids.sort()
  return stock_ids

# get features from screener data
def get_screener_features():
  myscreen_df = get_myscreen_df()
  cols = ['Symbol', 'EPS', 'MedPE', 'ROCE%', 'ROE%', 'CapType']
  return myscreen_df[cols]

# get relative strength
def get_relative_strength(stock_list):

    # Dictionary to store stock tickers and their corresponding percentage price change
    stock_changes = {}

    # Loop through each stock and fetch its price data
    for stock in stock_list:
        try:
            # Download the stock data for the given date range
            stock_data = yfin.Ticker(stock + '.NS').history(period='1mo', interval='1d')[map(str.title, ['open', 'close', 'low', 'high', 'volume'])]

            # Calculate the percentage change for the stock
            if len(stock_data) > 0:
                start_price = stock_data['Close'].iloc[0]
                end_price = stock_data['Close'].iloc[-1]
                percent_change = round(((end_price - start_price) / start_price) * 100, 2)
                stock_changes[stock] = percent_change
            else:
                stock_changes[stock] = np.nan  # If no data is available, set to NaN

        except Exception as e:
            print(f"Error fetching data for {stock}: {e}")
            stock_changes[stock] = np.nan

    # Create a DataFrame with stock tickers and their percentage changes
    df = pd.DataFrame(list(stock_changes.items()), columns=['Symbol', 'Percent_Change'])

    # Drop any stocks with missing data (NaN values)
    df = df.dropna()

    # Calculate the percentile rank based on percentage change
    df['RSP'] = round(df['Percent_Change'].rank(pct=True) * 100, 2)
    cols = ['Symbol', 'RSP']
    df = df[cols]
    # Sort by percentile rank (optional)
    df = df.sort_values(by='RSP', ascending=False).reset_index(drop=True)

    return df

In [6]:
# function to get stock technicals
def stock_prec_dev(stock_symbol):
    #stock_symbol = 'ULTRACEMCO.NS'
    short_window = 20
    mid_window = 50
    long_window = 200
    moving_avg = 'SMA'

    start = datetime.datetime(*map(int, start_date.split('-')))
    end = datetime.datetime(*map(int, end_date.split('-')))

    stock_df = yfin.Ticker(stock_symbol + '.NS').history(period='max', interval='1d')[map(str.title, ['open', 'close', 'low', 'high', 'volume'])]

    stock_df['Max'] = round(max(stock_df['Close']),2)
    stock_df = stock_df[(stock_df.index <= end_date) & (stock_df.index >= start_date)]
    stock_df['200_SMA'] = round(stock_df['Close'].rolling(window = 200, min_periods = 1).mean(),0)
    stock_df['Dev%_200'] = round((stock_df['Close'] - stock_df['200_SMA'])*100/stock_df['200_SMA'],2)
    stock_df.dropna(axis = 0, inplace = True) # remove any null rows

    stock_df['20_SMA'] = stock_df['Close'].rolling(window=20).mean()
    stock_df['50_SMA'] = stock_df['Close'].rolling(window=50).mean()
    stock_df['Symbol'] = stock_symbol

    stock_df['Close'] = round(stock_df['Close'],2)
    stock_df['Min'] = round(min(stock_df['Close']),2)
    stock_df['RSI_14'] = ta.momentum.RSIIndicator(close=stock_df['Close'], window=14).rsi()
    stock_df['RSI_14'] = round(stock_df['RSI_14'],0)
    stock_df['Prev_Close'] = stock_df['Close'].shift(1)
    stock_df.drop(['Open', 'Low', 'High', 'Volume'], axis=1, inplace=True)
    stock_df = stock_df.tail(1)

    max_SMA = max(stock_df['20_SMA'].item(), stock_df['50_SMA'].item(), stock_df['200_SMA'].item())
    min_SMA = min(stock_df['20_SMA'].item(), stock_df['50_SMA'].item(), stock_df['200_SMA'].item())
    ABS_Spread = max_SMA - min_SMA
    stock_df['Spread%'] = round((ABS_Spread / stock_df['200_SMA'].item()) * 100,2)

    return stock_df

# function to compute stock attributes
def get_common_features(stock_ids, df_mypf):

  df_prec_dev = pd.DataFrame()
  df_tmp = get_screener_features()
  df_rs = get_relative_strength(stock_ids)

  for stock_id in stock_ids:
      tmp = stock_prec_dev(stock_id)
      tmp = tmp.reset_index()
      df_prec_dev = pd.concat([df_prec_dev, tmp], ignore_index = True)
  df_prec_dev = pd.merge(df_prec_dev, df_mypf, on= 'Symbol')
  df_prec_dev = pd.merge(df_prec_dev, df_tmp, on= 'Symbol', how='left')
  df_prec_dev = pd.merge(df_prec_dev, df_rs, on= 'Symbol', how='left')
  #print(df_prec_dev.columns)
  df_prec_dev['Curr_PE'] = round(df_prec_dev['Close']/df_prec_dev['EPS'],1)
  df_prec_dev['Dev%_PE'] = round((df_prec_dev['Curr_PE'] - df_prec_dev['MedPE'])*100/df_prec_dev['MedPE'],2)
  df_prec_dev['Conviction'] = df_prec_dev['Conviction'] + '-' + df_prec_dev['CapType']
  return df_prec_dev

# function to arrange stock features
def arrange_features(df_stocks, common_cols, diff_cols):
  df_stocks_common = df_stocks[common_cols].drop_duplicates()
  df_stocks_diff = df_stocks[diff_cols]
  df_stocks_diff['Investment'] = df_stocks_diff['AvgCost'] * df_stocks_diff['Shares']
  df_stocks_diff = df_stocks_diff.groupby(['Symbol'])[['Shares', 'Investment']].aggregate(['sum']).reset_index()
  df_stocks_diff.columns = ['Symbol', 'Shares', 'Investment']
  df_stocks_diff['AvgCost'] = round(df_stocks_diff['Investment']/df_stocks_diff['Shares'],2)
  df_stocks = pd.merge(df_stocks_diff, df_stocks_common, on='Symbol')
  return df_stocks

# plot fact distribution across dimension
def plot_pie_chart(df, dimension, fact):
  # grouping the data by category and calculating the sum of fact for each type
  grouped_data = df.groupby(dimension)[fact].sum()

  # sorting the grouped data in descending order
  grouped_data = grouped_data.sort_values(ascending=False)

  # creating a pie chart
  grouped_data.plot.pie(autopct='%1.1f%%', startangle=90, figsize=(6, 6))

  # adding a title and displaying the plot
  plt.title(f'{dimension} {fact} Distribution')
  plt.ylabel('')  # To hide the y-label
  plt.show()

In [7]:
# function to get portfolio features

def get_portfolio_features(df_common_features):

  print_date_time()
  print('-------------------')

  #df_common_features["Target"] = df_common_features["Target"].fillna(df_common_features["Max"])
  df_common_features['NTT'] = np.where(df_common_features['Strategy']== 'NTT', df_common_features["Target"], df_common_features['Max'])
  df_common_features['LTT'] = np.where(df_common_features['Strategy']== 'BTT', df_common_features["Target"], df_common_features['Max'])
  df_common_features['BOL'] = df_common_features['Min']

  tmp_df = df_common_features[df_common_features['Symbol'].isin(mypf_df[mypf_df['InPortfolio'] != 'NA'].Symbol.values)]
  print('qualified stocks: '+str(len(tmp_df['Symbol'].unique())))
  tmp_df1 = tmp_df[tmp_df['LatestQtr'] == 1]
  print('with latest results: '+str(len(tmp_df1['Symbol'].unique())))
  tmp_df1 = tmp_df1[tmp_df1['StarStock'] == 1]
  print('still star stocks: '+str(len(tmp_df1['Symbol'].unique())))
  tmp_df['Investment'] = tmp_df['AvgCost'] * tmp_df['Shares']
  tmp_df['Current'] = round(tmp_df['Close'] * tmp_df['Shares'],0)
  tmp_df['Previous'] = tmp_df['Prev_Close'] * tmp_df['Shares']
  tmp_df['EstimatedST'] = tmp_df['NTT'] * tmp_df['Shares']
  tmp_df['EstimatedLT'] = tmp_df['LTT'] * tmp_df['Shares']
  tmp_df['Current P/L'] = round((tmp_df['Current'] - tmp_df['Investment']),0)
  tmp_df['Today P/L%'] = round((tmp_df['Current'] - tmp_df['Previous'])*100/tmp_df['Previous'],2)
  tmp_df['Current P/L%'] = round((tmp_df['Current'] - tmp_df['Investment'])*100/tmp_df['Investment'],2)
  tmp_df['EstimatedST P/L%'] = round((tmp_df['EstimatedST'] - tmp_df['Investment'])*100/tmp_df['Investment'],2)
  tmp_df['EstimatedLT P/L%'] = round((tmp_df['EstimatedLT'] - tmp_df['Investment'])*100/tmp_df['Investment'],2)
  tmp_df['NTT%'] = round((tmp_df['NTT'] - tmp_df['Close'])*100/tmp_df['Close'],2)
  tmp_df['LTT%'] = round((tmp_df['LTT'] - tmp_df['Close'])*100/tmp_df['Close'],2)
  tmp_df['Gained%'] = round((tmp_df['Close'] - tmp_df['BOL'])*100/tmp_df['BOL'],2)
  investment = round(sum(tmp_df['AvgCost']*tmp_df['Shares']),0)
  current = round(sum(tmp_df['Close']*tmp_df['Shares']),0)
  tmp_df['InitAlloc%'] = round(tmp_df['Investment']*100/investment,2)
  tmp_df['CurrAlloc%'] = round(tmp_df['Current']*100/current,2)
  tmp_df['FTT'] = tmp_df['LTT']
  tmp_df.loc[tmp_df['Strategy'] == 'NTT', 'FTT'] = tmp_df['NTT']
  tmp_df['FTT%'] = tmp_df['LTT%']
  tmp_df.loc[tmp_df['Strategy'] == 'NTT', 'FTT%'] = tmp_df['NTT%']
  tmp_df['FTT Amt'] = round(tmp_df['FTT%'] * tmp_df['Current']/100,0)
  tmp_df['OTT%'] = round((tmp_df['FTT'] - tmp_df['AvgCost'])*100/tmp_df['AvgCost'],2)
  tmp_df['RRR Ind'] = round(tmp_df['Current P/L']/tmp_df['FTT Amt'],2)
  tmp_df['Risk Ind'] = round(tmp_df['Current P/L%']*tmp_df['CurrAlloc%'],0)

  return tmp_df

# function to print portfolio features
def print_portfolio_stats(df_portfolio_features, myinvmt_df):
  from pyxirr import xirr

  total_booked_amt, reserve_amt, cy_booked_amt, py_booked_amt = get_amt()

  dates = myinvmt_df['Date'].values
  dates = np.append(dates, datetime.date.today().strftime('%d-%b-%y'))
  investment = myinvmt_df['Investment'].values
  dates= pd.to_datetime(dates)

  current = round(sum(df_portfolio_features['Close']*df_portfolio_features['Shares']),0) + reserve_amt
  investment_xirr = np.append(investment, current)
  cagr = round(xirr(pd.DataFrame({"dates": dates, "amounts": investment_xirr}))*100,2)

  investment = -sum(investment)
  invested = round(sum(df_portfolio_features['AvgCost']*df_portfolio_features['Shares']),0) + reserve_amt
  previous = round(sum(df_portfolio_features['Prev_Close']*df_portfolio_features['Shares']),0) + reserve_amt
  cy_invested = investment + py_booked_amt

  today_pnl_amount = current-previous
  today_pnl_percentage = round((current-previous)*100/previous,2)

  curr_pnl_amount = current-invested
  curr_pnl_percentage = round((curr_pnl_amount)*100/(cy_invested),2)

  cy_pnl_amount = cy_booked_amt + curr_pnl_amount
  cy_pnl_percentage = round((cy_pnl_amount)*100/cy_invested,2)

  overall_pnl_amount = total_booked_amt + curr_pnl_amount
  overall_pnl_percentage = round((overall_pnl_amount)*100/investment,2)

  estimate_st = round(sum(df_portfolio_features['FTT']*df_portfolio_features['Shares']),0)  + reserve_amt
  est_st_pnl_amount = estimate_st-current
  est_st_pnl_percentage = round((est_st_pnl_amount)*100/current,2)

  estimate_lt = round(sum(df_portfolio_features['LTT']*df_portfolio_features['Shares']),0)  + reserve_amt
  est_lt_pnl_amount = estimate_lt-current
  est_lt_pnl_percentage = round((est_lt_pnl_amount)*100/current,2)

  total_profit = round(sum(df_portfolio_features[df_portfolio_features['Current P/L%'] > 0]['Current']) - sum(df_portfolio_features[df_portfolio_features['Current P/L%'] > 0]['Investment']),0)
  total_loss = round(sum(df_portfolio_features[df_portfolio_features['Current P/L%'] < 0]['Current']) - sum(df_portfolio_features[df_portfolio_features['Current P/L%'] < 0]['Investment']),0)

  cy_booked_percentage = round((cy_booked_amt)*100/current,2)
  py_booked_percentage = round((py_booked_amt)*100/investment,2)
  total_booked_percentage = round((total_booked_amt)*100/investment,2)

  print('-------------------')
  print('Initial Investment: ', format_amt(investment))
  print('CY Investment: ', format_amt(cy_invested))
  print('Reserve: ', format_amt(reserve_amt))
  print('Current: ',  format_amt(current))
  print('-------------------')
  print('Today PnL: '+ '{} ({}%)'.format(format_amt(today_pnl_amount), today_pnl_percentage))
  print('Current PnL: '+ '{} ({}%)'.format(format_amt(curr_pnl_amount), curr_pnl_percentage))
  print('CY Booked + Current PnL: '+ '{} ({}%)'.format(format_amt(cy_pnl_amount), cy_pnl_percentage))
  print('-------------------')
  print('Total profit: ', format_amt(total_profit))
  print('Total loss: ', format_amt(total_loss))
  print('-------------------')
  print('Total Booked + Current PnL: '+ '{} ({}%)'.format(format_amt(overall_pnl_amount), overall_pnl_percentage))
  print('Total Booked PnL: '+ '{} ({}%)'.format(format_amt(total_booked_amt), total_booked_percentage))
  print('Curr Year Booked PnL: '+ '{} ({}%)'.format(format_amt(cy_booked_amt), cy_booked_percentage))
  print('Prev Year Booked PnL: '+ '{} ({}%)'.format(format_amt(py_booked_amt), py_booked_percentage))
  print('===================')
  print('Est FTT: ',  format_amt(estimate_st))
  print('Est FTT PnL: '+ '{} ({}%)'.format(format_amt(est_st_pnl_amount), est_st_pnl_percentage))

  print('===================')
  print('Deployed: ', format_amt(investment))

  print('Current: ', format_amt(current))

  print('CAGR/XIRR %: '+'{}%'.format(cagr))

In [8]:
# get start and end date
start_date, end_date = get_start_end_date()

# get portfolio and prospects data
mypfs_df = get_mypfs_df()
mypps_df = get_mypps_df()
myinvmt_df = get_myinvmt_df()

# merge above datasets
mypf_df = pd.merge(mypfs_df, mypps_df, on="Symbol")

# seggregate dm and sv portfolio
dm_pf = mypf_df[mypf_df['InPortfolio'] == 'DM']
sv_pf = mypf_df[mypf_df['InPortfolio'] == 'SV']

# build portfolio stock dataframe
dm_stocks = get_stock_ids(dm_pf)
sv_stocks = get_stock_ids(sv_pf)
df_stocks = pd.concat([dm_pf,sv_pf], ignore_index = True)

# arrange common and diff stock features
common_cols = ['Symbol', 'Target', 'Criteria', 'Strategy', 'CumlRnk', 'LatestQtr', 'StarStock', 'Conviction', 'Category', 'InFolio', 'XIRR', 'MBQ']
diff_cols = ['Symbol', 'AvgCost', 'Shares']
df_stocks = arrange_features(df_stocks, common_cols, diff_cols)

# get common features
stock_ids = df_stocks['Symbol'].values
df_common_features = get_common_features(stock_ids, df_stocks)

df_common_features.reset_index(drop=True, inplace=True)
df_common_features.drop(['Date'], axis=1, inplace=True)
# get and print portfolio features
df_portfolio_features = get_portfolio_features(df_common_features)

print_portfolio_stats(df_portfolio_features, myinvmt_df)

df = df_portfolio_features
#plot_pie_chart(df, 'CapType', 'Current')
list_ox40n = list(df[df['MBQ'].str.contains('OX40N', na=False)]['Symbol'].values)

Run date time (IST): 2026-03-20 09:44:26
-------------------
qualified stocks: 86
with latest results: 26
still star stocks: 16
-------------------
Initial Investment:  1.36 C
CY Investment:  1.62 C
Reserve:  1.61 K
Current:  1.32 C
-------------------
Today PnL: 1.08 L (0.82%)
Current PnL: -44.87 L (-27.62%)
CY Booked + Current PnL: -28.98 L (-17.84%)
-------------------
Total profit:  74.37 K
Total loss:  -45.62 L
-------------------
Total Booked + Current PnL: -2.00 L (-1.48%)
Total Booked PnL: 42.87 L (31.64%)
Curr Year Booked PnL: 15.89 L (12.01%)
Prev Year Booked PnL: 26.98 L (19.91%)
===================
Est FTT:  2.48 C
Est FTT PnL: 1.16 C (87.43%)
===================
Deployed:  1.36 C
Current:  1.32 C
CAGR/XIRR %: -1.2%

In [9]:
# top 5 near their targets
cols = ['Symbol', 'Today P/L%', 'Current P/L%', 'FTT%', 'OTT%', 'FTT Amt', 'Current P/L', 'Current', 'FTT', 'Dev%_PE', 'RSI_14','Conviction', 'Spread%',  'CumlRnk', 'RRR Ind', 'CurrAlloc%', 'Gained%', 'Criteria', 'Strategy', 'Category']
df_tmp = df_portfolio_features[~df_portfolio_features['Symbol'].isin(['ENRIN','BLUSPRING','DIGITIDE'])]
df_tmp = df_tmp.sort_values(by = 'FTT Amt', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
50,MASFIN,0.92,-9.49,34.32,21.57,30435.0,-9300.0,88680.0,397.04,-21.86,38.0,H-SC,1.62,167.0,-0.31,0.67,20.95,XR,ATH,FINANCE
77,TTKPRESTIG,-1.87,-38.20,61.97,0.09,38593.0,-38500.0,62277.0,770.00,44.50,40.0,M-SC,18.01,250.0,-1.00,0.47,5.22,OX40N,NTT,DURABLES
37,ICICIGI,0.16,-4.92,25.52,19.34,48554.0,-9850.0,190259.0,2252.93,-20.08,33.0,X-MC,2.66,66.0,-0.20,1.44,5.17,X40,ATH,INSURANCE
2,ABBOTINDIA,0.28,-10.80,32.36,18.07,51627.0,-19315.0,159540.0,35195.00,-24.04,46.0,X-MC,10.68,58.0,-0.37,1.21,1.14,X40,ATH,PHARMA
67,SONACOMS,1.23,-12.66,59.26,39.09,52356.0,-12810.0,88349.0,804.02,-30.73,48.0,M-MC,8.15,193.0,-0.24,0.67,24.98,AR,ATH,AUTO

In [10]:
# top 5 today
df_tmp = df_portfolio_features.sort_values(by = 'Today P/L%', ascending=False)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
26,FINCABLES,3.67,11.58,86.33,107.91,142226.0,17103.0,164747.0,1641.55,0.46,54.0,M-SC,8.32,220.0,0.12,1.25,23.94,OX40N,ATH,CABLES
8,AWL,3.59,-37.12,165.61,67.02,371049.0,-132259.0,224050.0,485.00,-66.09,43.0,X-SC,25.76,81.0,-0.36,1.69,5.98,XY24,NTT,FMCG
72,TATAELXSI,3.27,-39.88,119.63,32.03,94810.0,-52582.0,79253.0,9161.00,-24.73,34.0,H-SC,20.18,158.0,-0.55,0.60,3.27,OX40N,NTT,IT
57,RECLTD,3.12,-7.82,30.98,20.74,58018.0,-15895.0,187275.0,446.00,1.56,50.0,M-MC,6.06,191.0,-0.27,1.42,5.98,XY25,NTT,FINANCE
74,TITAGARH,2.73,-39.87,142.39,45.74,207337.0,-96565.0,145612.0,1548.00,-19.89,37.0,H-SC,20.18,175.0,-0.47,1.10,2.73,XY24,NTT,ENGINEERING

In [11]:
# bottom 5 today
df_tmp = df_portfolio_features.sort_values(by = 'Today P/L%', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
73,TCS,-3.47,-30.84,83.00,26.57,265945.0,-142857.0,320416.0,4311.59,-41.33,23.0,X-LC,16.33,2.0,-0.54,2.42,0.00,X40,ATH,IT
30,HAPPSTMNDS,-3.20,-53.60,298.42,84.85,177452.0,-68701.0,59464.0,1480.71,-44.76,46.0,H-SC,27.63,152.0,-0.39,0.45,10.12,AR,ATH,IT
42,INDUSINDBK,-3.07,-39.73,120.51,32.89,56072.0,-30678.0,46529.0,1800.00,-319.19,33.0,L-MC,8.84,258.0,-0.55,0.35,28.14,XR,NTT,BANKS
78,UNITDSPR,-2.38,-5.32,27.55,20.77,61076.0,-12453.0,221691.0,1644.00,-16.02,39.0,X-MC,1.00,64.0,-0.20,1.68,1.03,X40N,NTT,BREWERIES
77,TTKPRESTIG,-1.87,-38.20,61.97,0.09,38593.0,-38500.0,62277.0,770.00,44.50,40.0,M-SC,18.01,250.0,-1.00,0.47,5.22,OX40N,NTT,DURABLES

In [12]:
# top 5 to exit based on CumlRnk
df_tmp = df_portfolio_features[~df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])]
df_tmp = df_tmp[(df_tmp['Current P/L%'] > -1) & (df_tmp['Current P/L%'] < 1)].sort_values(by = 'CumlRnk', ascending=False)
df_tmp[cols].head()

Empty DataFrame
Columns: [Symbol, Today P/L%, Current P/L%, FTT%, OTT%, FTT Amt, Current P/L, Current, FTT, Dev%_PE, RSI_14, Conviction, Spread%, CumlRnk, RRR Ind, CurrAlloc%, Gained%, Criteria, Strategy, Category]
Index: []

In [13]:
# OX40N stocks to exit
df_tmp = df_portfolio_features[(df_portfolio_features['Symbol'].isin(list_ox40n))].sort_values(by = 'Current P/L%', ascending=False)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
26,FINCABLES,3.67,11.58,86.33,107.91,142226.0,17103.0,164747.0,1641.55,0.46,54.0,M-SC,8.32,220.0,0.12,1.25,23.94,OX40N,ATH,CABLES
66,SIS,-0.38,-36.38,90.61,21.26,64002.0,-40397.0,70635.0,528.00,1650.26,34.0,H-SC,13.64,168.0,-0.63,0.53,1.80,OX40N,NTT,MISC
18,CERA,0.23,-37.64,98.67,23.89,108233.0,-66211.0,109692.0,9475.00,-39.86,47.0,H-SC,18.44,153.0,-0.61,0.83,5.41,OX40N,NTT,CERAMICS
77,TTKPRESTIG,-1.87,-38.20,61.97,0.09,38593.0,-38500.0,62277.0,770.00,44.50,40.0,M-SC,18.01,250.0,-1.00,0.47,5.22,OX40N,NTT,DURABLES
72,TATAELXSI,3.27,-39.88,119.63,32.03,94810.0,-52582.0,79253.0,9161.00,-24.73,34.0,H-SC,20.18,158.0,-0.55,0.60,3.27,OX40N,NTT,IT

In [14]:
# top 5 to book for rotation
df_tmp = df_portfolio_features[(df_portfolio_features['Current P/L%'] > 20) ].sort_values(by = 'CumlRnk', ascending=False)
df_tmp[cols].head()

Empty DataFrame
Columns: [Symbol, Today P/L%, Current P/L%, FTT%, OTT%, FTT Amt, Current P/L, Current, FTT, Dev%_PE, RSI_14, Conviction, Spread%, CumlRnk, RRR Ind, CurrAlloc%, Gained%, Criteria, Strategy, Category]
Index: []

In [15]:
# top 5 to monitor for exit
df_tmp = df_portfolio_features[~df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])]
df_tmp = df_tmp[(df_tmp['Current P/L%'] > 0) ].sort_values(by = 'Dev%_PE', ascending=False)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
26,FINCABLES,3.67,11.58,86.33,107.91,142226.0,17103.0,164747.0,1641.55,0.46,54.0,M-SC,8.32,220.0,0.12,1.25,23.94,OX40N,ATH,CABLES
1,ABB,2.36,16.70,24.74,45.57,75532.0,43685.0,305304.0,7934.00,-25.02,62.0,H-MC,13.08,125.0,0.58,2.31,35.57,AR,NTT,ELECTRICAL

In [16]:
# top 5 to book for rotation from weak conviction
df_tmp = df_portfolio_features[~df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])]
df_tmp = df_tmp[~df_tmp['Criteria'].isin(['XY25','XY24','X40', 'X40N'])].sort_values(by = 'RRR Ind', ascending=False)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
1,ABB,2.36,16.70,24.74,45.57,75532.0,43685.0,305304.0,7934.00,-25.02,62.0,H-MC,13.08,125.0,0.58,2.31,35.57,AR,NTT,ELECTRICAL
26,FINCABLES,3.67,11.58,86.33,107.91,142226.0,17103.0,164747.0,1641.55,0.46,54.0,M-SC,8.32,220.0,0.12,1.25,23.94,OX40N,ATH,CABLES
40,INDIAMART,-0.36,-13.12,137.95,106.72,147813.0,-16186.0,107150.0,4810.62,-60.74,35.0,H-SC,10.79,140.0,-0.11,0.81,7.19,AR,ATH,MISC
85,ZYDUSLIFE,1.33,-6.38,44.87,35.63,88037.0,-13370.0,196204.0,1286.17,-18.47,45.0,H-MC,5.30,120.0,-0.15,1.48,9.23,AR,ATH,PHARMA
84,WIPRO,0.79,-22.11,121.17,72.27,159920.0,-37468.0,131980.0,420.00,-29.71,29.0,M-LC,17.03,98.0,-0.23,1.00,0.79,XR,NTT,IT

In [17]:
# top 5 to accumulate based on lowest RSI_14
df_tmp = df_portfolio_features[df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])].sort_values(by = 'RSI_14', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
53,PGHH,-0.78,-26.25,79.00,32.01,124403.0,-56048.0,157472.0,17616.87,-50.08,15.0,X-MC,14.45,57.0,-0.45,1.19,0.00,X40,ATH,FMCG
12,BATAINDIA,1.53,-57.56,218.61,35.20,119365.0,-74068.0,54602.0,2096.00,-28.38,19.0,X-SC,29.92,91.0,-0.62,0.41,1.53,X40,NTT,FOOTWEAR
58,RELAXO,1.26,-64.24,325.86,52.31,169173.0,-93244.0,51916.0,1176.00,-61.96,23.0,X-SC,24.50,92.0,-0.55,0.39,1.27,X40N,NTT,FOOTWEAR
73,TCS,-3.47,-30.84,83.00,26.57,265945.0,-142857.0,320416.0,4311.59,-41.33,23.0,X-LC,16.33,2.0,-0.54,2.42,0.00,X40,ATH,IT
38,ICICIPRULI,0.03,-6.83,40.31,30.73,73991.0,-13451.0,183554.0,790.00,-31.81,24.0,X-MC,3.35,78.0,-0.18,1.39,5.01,X40,ATH,INSURANCE

In [18]:
# top 5 to accumulate based on Spread and CumlRnk
df_tmp = df_portfolio_features[df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])]
df_tmp = df_tmp[(df_tmp['CumlRnk'] < 100)].sort_values(by = 'Spread%', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
78,UNITDSPR,-2.38,-5.32,27.55,20.77,61076.0,-12453.0,221691.0,1644.00,-16.02,39.0,X-MC,1.00,64.0,-0.20,1.68,1.03,X40N,NTT,BREWERIES
37,ICICIGI,0.16,-4.92,25.52,19.34,48554.0,-9850.0,190259.0,2252.93,-20.08,33.0,X-MC,2.66,66.0,-0.20,1.44,5.17,X40,ATH,INSURANCE
38,ICICIPRULI,0.03,-6.83,40.31,30.73,73991.0,-13451.0,183554.0,790.00,-31.81,24.0,X-MC,3.35,78.0,-0.18,1.39,5.01,X40,ATH,INSURANCE
59,RELIANCE,-1.65,-11.11,40.96,25.30,73171.0,-22324.0,178639.0,1952.00,-13.49,44.0,X-LC,3.37,21.0,-0.31,1.35,19.27,XY25,BTT,REFINERIES
65,SIEMENS,2.08,-15.55,48.63,25.51,76424.0,-28940.0,157155.0,4671.50,31.90,46.0,H-LC,3.52,51.0,-0.38,1.19,15.73,AR,ATH,ELECTRICAL

In [19]:
# top 5 to accumulate based on lowest Gained%
df_tmp = df_portfolio_features[df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])].sort_values(by = 'Gained%', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
51,MEDANTA,-0.64,-13.76,47.41,27.12,72169.0,-24294.0,152223.0,1486.00,-16.46,29.0,X-SC,11.02,87.0,-0.34,1.15,0.00,XY24,NTT,HEALTHCARE
53,PGHH,-0.78,-26.25,79.00,32.01,124403.0,-56048.0,157472.0,17616.87,-50.08,15.0,X-MC,14.45,57.0,-0.45,1.19,0.00,X40,ATH,FMCG
34,HDFCBANK,-1.37,-5.81,36.29,28.37,80285.0,-13654.0,221231.0,1073.00,-20.04,25.0,X-LC,10.73,26.0,-0.17,1.67,0.00,X40,BTT,BANKS
73,TCS,-3.47,-30.84,83.00,26.57,265945.0,-142857.0,320416.0,4311.59,-41.33,23.0,X-LC,16.33,2.0,-0.54,2.42,0.00,X40,ATH,IT
35,HINDUNILVR,0.19,-19.04,40.40,13.67,84080.0,-48943.0,208120.0,2922.00,-39.91,26.0,X-LC,7.37,9.0,-0.58,1.57,0.19,XY25,NTT,FMCG

In [20]:
# top 5 to accumulate based on lowest CurrAlloc%
df_tmp = df_portfolio_features[df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])].sort_values(by = 'CurrAlloc%', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
58,RELAXO,1.26,-64.24,325.86,52.31,169173.0,-93244.0,51916.0,1176.00,-61.96,23.0,X-SC,24.50,92.0,-0.55,0.39,1.27,X40N,NTT,FOOTWEAR
12,BATAINDIA,1.53,-57.56,218.61,35.20,119365.0,-74068.0,54602.0,2096.00,-28.38,19.0,X-SC,29.92,91.0,-0.62,0.41,1.53,X40,NTT,FOOTWEAR
54,QUESS,1.03,-25.89,134.64,73.90,106564.0,-27646.0,79147.0,424.00,-60.33,39.0,X-SC,20.46,80.0,-0.26,0.60,3.15,XY24,NTT,MISC
36,HONAUT,1.58,-25.05,101.89,51.31,147257.0,-48313.0,144525.0,58357.33,-37.67,33.0,X-SC,14.97,90.0,-0.33,1.09,1.58,X40N,ATH,ELECTRICAL
51,MEDANTA,-0.64,-13.76,47.41,27.12,72169.0,-24294.0,152223.0,1486.00,-16.46,29.0,X-SC,11.02,87.0,-0.34,1.15,0.00,XY24,NTT,HEALTHCARE

In [21]:
# top 5 to accumulate based on CumlRnk
df_tmp = df_portfolio_features.sort_values(by = 'CumlRnk', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
45,ITC,1.66,-20.20,49.20,19.06,133550.0,-68723.0,271443.0,452.00,-56.33,40.0,X-LC,17.90,1.0,-0.51,2.05,1.66,X40,NTT,FMCG
73,TCS,-3.47,-30.84,83.00,26.57,265945.0,-142857.0,320416.0,4311.59,-41.33,23.0,X-LC,16.33,2.0,-0.54,2.42,0.00,X40,ATH,IT
43,INFY,1.64,-15.53,58.93,34.24,155746.0,-48598.0,264290.0,1972.00,-33.60,33.0,X-LC,14.87,3.0,-0.31,2.00,1.64,X40,NTT,IT
75,TMPV,1.71,-28.39,90.72,36.58,231178.0,-101015.0,254826.0,600.00,-84.72,35.0,X-LC,5.02,4.0,-0.44,1.93,1.71,XY24,NTT,AUTO
33,HCLTECH,1.68,-13.44,43.06,23.83,90171.0,-32517.0,209407.0,1908.19,-9.02,36.0,X-LC,11.53,8.0,-0.36,1.58,1.68,X40,ATH,IT

In [22]:
# top 5 for average up
df_tmp = df_portfolio_features[(df_portfolio_features['Dev%_200'] > 5)].sort_values(by = 'CurrAlloc%', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
67,SONACOMS,1.23,-12.66,59.26,39.09,52356.0,-12810.0,88349.0,804.02,-30.73,48.0,M-MC,8.15,193.0,-0.24,0.67,24.98,AR,ATH,AUTO
26,FINCABLES,3.67,11.58,86.33,107.91,142226.0,17103.0,164747.0,1641.55,0.46,54.0,M-SC,8.32,220.0,0.12,1.25,23.94,OX40N,ATH,CABLES
1,ABB,2.36,16.70,24.74,45.57,75532.0,43685.0,305304.0,7934.00,-25.02,62.0,H-MC,13.08,125.0,0.58,2.31,35.57,AR,NTT,ELECTRICAL

In [23]:
# top 5 RSP
df_tmp = df_portfolio_features.sort_values(by = 'RSP', ascending=False)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
26,FINCABLES,3.67,11.58,86.33,107.91,142226.0,17103.0,164747.0,1641.55,0.46,54.0,M-SC,8.32,220.0,0.12,1.25,23.94,OX40N,ATH,CABLES
30,HAPPSTMNDS,-3.20,-53.60,298.42,84.85,177452.0,-68701.0,59464.0,1480.71,-44.76,46.0,H-SC,27.63,152.0,-0.39,0.45,10.12,AR,ATH,IT
1,ABB,2.36,16.70,24.74,45.57,75532.0,43685.0,305304.0,7934.00,-25.02,62.0,H-MC,13.08,125.0,0.58,2.31,35.57,AR,NTT,ELECTRICAL
69,SURYODAY,1.09,-26.61,67.65,23.03,88904.0,-47654.0,131417.0,216.00,42.54,50.0,H-SC,6.51,166.0,-0.54,0.99,28.44,XR,NTT,BANKS
80,VALIANTORG,-1.70,-47.01,228.63,74.15,198222.0,-76905.0,86700.0,838.00,-255.96,61.0,H-SC,28.77,145.0,-0.39,0.66,29.02,XR,NTT,CHEMICALS

In [24]:
# Top N allocation
df_tmp = df_portfolio_features.sort_values(by = 'CurrAlloc%', ascending=False)
top_n_values = [10, 25, 50]

sum_df = pd.DataFrame({
    'Top_N': top_n_values,
    'Sum_Alloc%': [df_tmp['CurrAlloc%'].head(n).sum() for n in top_n_values]
})

sum_df

   Top_N  Sum_Alloc%
0     10       20.68
1     25       45.58
2     50       77.99

In [25]:
# market-cap-wise allocation
df_tmp = df_portfolio_features[cols]
df_tmp.groupby(df_tmp['Conviction'].str[-2:])['CurrAlloc%'].sum().sort_values(ascending=False)

Conviction
SC    44.55
MC    30.21
LC    25.23
Name: CurrAlloc%, dtype: float64

In [26]:
# criteria-wise allocation
df_portfolio_features.groupby('Criteria')['CurrAlloc%'].sum().sort_values(ascending=False)

Criteria
XY24     26.98
X40      25.38
X40N     15.17
AR        9.18
XR        8.32
XY25      7.34
OX40N     6.83
SR        0.79
Name: CurrAlloc%, dtype: float64

In [27]:
# conviction-wise allocation
df_portfolio_features.groupby('Conviction')['CurrAlloc%'].sum().sort_values(ascending=False)

Conviction
X-LC    23.04
X-MC    22.69
H-SC    21.61
X-SC    12.25
M-SC    10.15
H-MC     5.08
M-MC     2.09
H-LC     1.19
M-LC     1.00
L-SC     0.54
L-MC     0.35
Name: CurrAlloc%, dtype: float64

In [28]:
# sector-wise stats
df_tmp = df_portfolio_features.groupby('Category')[['CurrAlloc%', 'Current', 'Current P/L', 'FTT Amt']].sum().sort_values(by=['Current', 'Current P/L'], ascending=False)
df_tmp['Current P/L%'] = round(df_tmp['Current P/L'] * 100 / df_tmp['Current'], 2)
df_tmp['FTT%'] = round(df_tmp['FTT Amt'] * 100 / df_tmp['Current'], 2)
cols = ['CurrAlloc%', 'Current P/L%', 'FTT%']
df_tmp[cols].sort_values(by=['CurrAlloc%'], ascending=False)

               CurrAlloc%  Current P/L%    FTT%
Category
FMCG                15.07        -25.24   69.70
FINANCE             13.20        -23.12   73.29
IT                  11.60        -46.91  121.67
MISC                 6.96        -45.58  108.82
ELECTRICAL           6.67         -9.86   51.93
PAINTS               5.06        -47.32   72.91
INSURANCE            4.70         -9.26   46.65
BANKS                4.64        -25.33   88.94
PHARMA               4.15         -7.14   40.87
AUTO                 3.68        -34.52   87.89
AC                   2.10        -14.95   46.12
HEALTHCARE           1.89        -42.91   80.20
DURABLES             1.83        -60.40   99.42
TRAVEL               1.80        -87.37  181.19
FOOTWEAR             1.78        -87.08  162.09
APPARELS             1.68        -20.79   62.00
BREWERIES            1.68         -5.62   27.55
REALTY               1.46        -14.88   33.75
CERAMICS             1.39        -67.38  118.23
REFINERIES           1.35        -12.50   40.96
CABLES               1.25         10.38   86.33
CEMENT               1.24        -63.39  185.63
ENGINEERING          1.10        -66.32  142.39
CHEMICALS            1.08        -85.23  236.34
JEWELLERY            1.07       -125.97  204.48
ENTERTAINMENT        0.77        -89.87  203.10
TEXTILES             0.44        -56.93  101.68
HOTELS               0.35       -144.69  230.99

In [29]:
# money to be made criteria-wise
df_portfolio_features.groupby('Criteria')['FTT Amt'].agg(['sum', 'count']).sort_values(by='sum', ascending=False)

                sum  count
Criteria
XY24      4028636.0     21
X40       1817249.0     16
XR        1390822.0     12
AR        1357336.0     10
X40N      1295399.0     10
OX40N      889060.0     10
XY25       469665.0      5
SR         314802.0      2

In [30]:
# money to be made conviction-wise
df_portfolio_features.groupby('Conviction')['FTT Amt'].agg(['sum', 'count']).sort_values(by='sum', ascending=False)

                  sum  count
Conviction
H-SC        3934157.0     24
X-MC        1736352.0     15
X-LC        1727843.0     13
M-SC        1576304.0     14
X-SC        1560519.0     10
H-MC         406246.0      3
L-SC         218758.0      2
M-LC         159920.0      1
M-MC         110374.0      2
H-LC          76424.0      1
L-MC          56072.0      1

In [31]:
# money to be made criteria and conviction-wise
df_portfolio_features.groupby(['Conviction', 'Criteria'])['FTT Amt'].agg(['sum', 'count']).sort_values(by='sum', ascending=False)

                           sum  count
Conviction Criteria
H-SC       XY24      1364659.0      6
           AR         987034.0      5
X-LC       X40        933019.0      7
M-SC       XY24       920881.0      6
H-SC       XR         875167.0      7
X-SC       XY24       854401.0      4
X-MC       X40        679435.0      7
           X40N       530133.0      4
X-SC       X40N       501323.0      4
H-SC       OX40N      392495.0      4
M-SC       OX40N      385000.0      5
X-LC       XY24       373630.0      2
H-SC       SR         314802.0      2
X-MC       XY24       272388.0      2
X-LC       X40N       263943.0      2
X-MC       XY25       254396.0      2
H-MC       XY24       242677.0      1
X-SC       X40        204795.0      2
M-SC       XR         192470.0      2
H-MC       AR         163569.0      2
M-LC       XR         159920.0      1
X-LC       XY25       157251.0      2
L-SC       OX40N      111565.0      1
           XR         107193.0      1
M-SC       AR          77953.0      1
H-LC       AR          76424.0      1
M-MC       XY25        58018.0      1
L-MC       XR          56072.0      1
M-MC       AR          52356.0      1

In [32]:
# notebook execution time

end_time = time.time()
execution_time = round(end_time - start_time, 0)
print(f"Notebook execution time: {execution_time} seconds")

Notebook execution time: 25.0 seconds