<a href="https://colab.research.google.com/github/ankit-rathi/Quantvesting_v2/blob/main/myStocks_Portfolio_Analysis.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
'''
!pip install pandas==2.2.2 -qq
!pip install pyxirr -qq
!pip install ta -qq
!pip install yfinance==0.2.59 -qq
'''

'\n!pip install pandas==2.2.2 -qq\n!pip install pyxirr -qq\n!pip install ta -qq\n!pip install yfinance==0.2.59 -qq\n'

In [2]:
# import libraries

import numpy as np
import pandas as pd
import datetime
import warnings
warnings.filterwarnings('ignore')
import yfinance as yfin
import ta
import matplotlib.pyplot as plt
import requests

In [3]:
# notebook start time
import time
import datetime
import pytz

start_time = time.time()

# function to print date timestamp
def print_date_time():
  tz_NY = pytz.timezone('Asia/Kolkata')
  datetime_NY = datetime.datetime.now(tz_NY)
  print("Run date time (IST):", datetime_NY.strftime("%Y-%m-%d %H:%M:%S"))

In [4]:
# function to get booked and reserved amount
def get_amt():
  # fetch the JSON data from the URL
  url = "https://raw.githubusercontent.com/ankit-rathi/Tradevesting_v1/main/data/myPortfolioAmts.json"
  response = requests.get(url)
  pf_amts = response.json()  # parse the JSON data

  # extract values from the JSON
  py_booked_amt_dm = pf_amts["py_booked_amt_dm"]
  py_booked_amt_sv = pf_amts["py_booked_amt_sv"]
  cy_booked_amt_dm = pf_amts["cy_booked_amt_dm"]
  cy_booked_amt_sv = pf_amts["cy_booked_amt_sv"]
  reserve_amt_dm = pf_amts["reserve_amt_dm"]
  reserve_amt_sv = pf_amts["reserve_amt_sv"]

  # perform calculations
  py_booked_amt = py_booked_amt_dm + py_booked_amt_sv
  cy_booked_amt = cy_booked_amt_dm + cy_booked_amt_sv
  reserve_amt = reserve_amt_dm + reserve_amt_sv
  total_booked_amt = py_booked_amt + cy_booked_amt

  return total_booked_amt, reserve_amt, cy_booked_amt, py_booked_amt

gen_output = 0

In [5]:
# function to format the amount
def format_amt(number):
    abs_number = abs(number)

    if abs_number >= 1_00_00_000:  # Crores
        formatted_amt = f"{number / 1_00_00_000:.2f} C"
    elif abs_number >= 1_00_000:  # Lakhs
        formatted_amt = f"{number / 1_00_000:.2f} L"
    elif abs_number >= 1_000:  # Thousands
        formatted_amt = f"{number / 1_000:.2f} K"
    else:
        formatted_amt = f"{number:.2f}"

    return formatted_amt

# function to set start and end date
def get_start_end_date():
  start_date = (datetime.date.today() + datetime.timedelta(days=-365)).strftime('%Y-%m-%d')
  end_date = (datetime.date.today() + datetime.timedelta(days=1)).strftime('%Y-%m-%d')
  return start_date, end_date

# function to fetch my portfolio csv
def get_mypfs_df():
  mypfs_df = pd.read_csv('https://raw.githubusercontent.com/ankit-rathi/Tradevesting_v1/main/data/myPortfolioStocks.csv')
  return mypfs_df

# function to fetch my prospects csv
def get_mypps_df():
  mypps_df = pd.read_csv('https://raw.githubusercontent.com/ankit-rathi/Tradevesting_v1/main/data/myProspectsScrips.csv')
  return mypps_df

# function to fetch screener data
def get_myscreen_df():
  myscreen_df = pd.read_csv('https://raw.githubusercontent.com/ankit-rathi/Tradevesting_v1/main/data/myScreenerDB.csv')
  return myscreen_df

# function to fetch momentum data
def get_myinvmt_df():
  myinvmt_df = pd.read_csv('https://raw.githubusercontent.com/ankit-rathi/Tradevesting_v1/main/data/myInvestments.csv')
  return myinvmt_df

# function to get the stock ids
def get_stock_ids(df_pf):
  stock_n100 = df_pf['Symbol'].unique()

  exclude = ['CADILAHC','MMTC', 'MASFIN']

  stock_ids = df_pf[~df_pf['Symbol'].isin(exclude) ]['Symbol'].unique()

  #mypf = mypf[mypf.Forecast.notnull()]
  #stock_ids = mypf['Symbol'].unique()

  #stock_ids.sort()
  return stock_ids

# get features from screener data
def get_screener_features():
  myscreen_df = get_myscreen_df()
  cols = ['Symbol', 'EPS', 'MedPE', 'ROCE%', 'ROE%', 'CapType']
  return myscreen_df[cols]

# get relative strength
def get_relative_strength(stock_list):

    # Dictionary to store stock tickers and their corresponding percentage price change
    stock_changes = {}

    # Loop through each stock and fetch its price data
    for stock in stock_list:
        try:
            # Download the stock data for the given date range
            stock_data = yfin.Ticker(stock + '.NS').history(period='1mo', interval='1d')[map(str.title, ['open', 'close', 'low', 'high', 'volume'])]

            # Calculate the percentage change for the stock
            if len(stock_data) > 0:
                start_price = stock_data['Close'].iloc[0]
                end_price = stock_data['Close'].iloc[-1]
                percent_change = round(((end_price - start_price) / start_price) * 100, 2)
                stock_changes[stock] = percent_change
            else:
                stock_changes[stock] = np.nan  # If no data is available, set to NaN

        except Exception as e:
            print(f"Error fetching data for {stock}: {e}")
            stock_changes[stock] = np.nan

    # Create a DataFrame with stock tickers and their percentage changes
    df = pd.DataFrame(list(stock_changes.items()), columns=['Symbol', 'Percent_Change'])

    # Drop any stocks with missing data (NaN values)
    df = df.dropna()

    # Calculate the percentile rank based on percentage change
    df['RSP'] = round(df['Percent_Change'].rank(pct=True) * 100, 2)
    cols = ['Symbol', 'RSP']
    df = df[cols]
    # Sort by percentile rank (optional)
    df = df.sort_values(by='RSP', ascending=False).reset_index(drop=True)

    return df

In [6]:
# function to get stock technicals
def stock_prec_dev(stock_symbol):
    #stock_symbol = 'ULTRACEMCO.NS'
    short_window = 20
    mid_window = 50
    long_window = 200
    moving_avg = 'SMA'

    start = datetime.datetime(*map(int, start_date.split('-')))
    end = datetime.datetime(*map(int, end_date.split('-')))

    stock_df = yfin.Ticker(stock_symbol + '.NS').history(period='max', interval='1d')[map(str.title, ['open', 'close', 'low', 'high', 'volume'])]

    stock_df['Max'] = round(max(stock_df['Close']),2)
    stock_df = stock_df[(stock_df.index <= end_date) & (stock_df.index >= start_date)]
    stock_df['200_SMA'] = round(stock_df['Close'].rolling(window = 200, min_periods = 1).mean(),0)
    stock_df['Dev%_200'] = round((stock_df['Close'] - stock_df['200_SMA'])*100/stock_df['200_SMA'],2)
    stock_df.dropna(axis = 0, inplace = True) # remove any null rows

    stock_df['20_SMA'] = stock_df['Close'].rolling(window=20).mean()
    stock_df['50_SMA'] = stock_df['Close'].rolling(window=50).mean()
    stock_df['Symbol'] = stock_symbol

    stock_df['Close'] = round(stock_df['Close'],2)
    stock_df['Min'] = round(min(stock_df['Close']),2)
    stock_df['RSI_14'] = ta.momentum.RSIIndicator(close=stock_df['Close'], window=14).rsi()
    stock_df['RSI_14'] = round(stock_df['RSI_14'],0)
    stock_df['Prev_Close'] = stock_df['Close'].shift(1)
    stock_df.drop(['Open', 'Low', 'High', 'Volume'], axis=1, inplace=True)
    stock_df = stock_df.tail(1)

    max_SMA = max(stock_df['20_SMA'].item(), stock_df['50_SMA'].item(), stock_df['200_SMA'].item())
    min_SMA = min(stock_df['20_SMA'].item(), stock_df['50_SMA'].item(), stock_df['200_SMA'].item())
    ABS_Spread = max_SMA - min_SMA
    stock_df['Spread%'] = round((ABS_Spread / stock_df['200_SMA'].item()) * 100,2)

    return stock_df

# function to compute stock attributes
def get_common_features(stock_ids, df_mypf):

  df_prec_dev = pd.DataFrame()
  df_tmp = get_screener_features()
  df_rs = get_relative_strength(stock_ids)

  for stock_id in stock_ids:
      tmp = stock_prec_dev(stock_id)
      tmp = tmp.reset_index()
      df_prec_dev = pd.concat([df_prec_dev, tmp], ignore_index = True)
  df_prec_dev = pd.merge(df_prec_dev, df_mypf, on= 'Symbol')
  df_prec_dev = pd.merge(df_prec_dev, df_tmp, on= 'Symbol', how='left')
  df_prec_dev = pd.merge(df_prec_dev, df_rs, on= 'Symbol', how='left')
  #print(df_prec_dev.columns)
  df_prec_dev['Curr_PE'] = round(df_prec_dev['Close']/df_prec_dev['EPS'],1)
  df_prec_dev['Dev%_PE'] = round((df_prec_dev['Curr_PE'] - df_prec_dev['MedPE'])*100/df_prec_dev['MedPE'],2)
  df_prec_dev['Conviction'] = df_prec_dev['Conviction'] + '-' + df_prec_dev['CapType']
  return df_prec_dev

# function to arrange stock features
def arrange_features(df_stocks, common_cols, diff_cols):
  df_stocks_common = df_stocks[common_cols].drop_duplicates()
  df_stocks_diff = df_stocks[diff_cols]
  df_stocks_diff['Investment'] = df_stocks_diff['AvgCost'] * df_stocks_diff['Shares']
  df_stocks_diff = df_stocks_diff.groupby(['Symbol'])[['Shares', 'Investment']].aggregate(['sum']).reset_index()
  df_stocks_diff.columns = ['Symbol', 'Shares', 'Investment']
  df_stocks_diff['AvgCost'] = round(df_stocks_diff['Investment']/df_stocks_diff['Shares'],2)
  df_stocks = pd.merge(df_stocks_diff, df_stocks_common, on='Symbol')
  return df_stocks

# plot fact distribution across dimension
def plot_pie_chart(df, dimension, fact):
  # grouping the data by category and calculating the sum of fact for each type
  grouped_data = df.groupby(dimension)[fact].sum()

  # sorting the grouped data in descending order
  grouped_data = grouped_data.sort_values(ascending=False)

  # creating a pie chart
  grouped_data.plot.pie(autopct='%1.1f%%', startangle=90, figsize=(6, 6))

  # adding a title and displaying the plot
  plt.title(f'{dimension} {fact} Distribution')
  plt.ylabel('')  # To hide the y-label
  plt.show()

In [7]:
# function to get portfolio features

def get_portfolio_features(df_common_features):

  print_date_time()
  print('-------------------')

  #df_common_features["Target"] = df_common_features["Target"].fillna(df_common_features["Max"])
  df_common_features['NTT'] = np.where(df_common_features['Strategy']== 'NTT', df_common_features["Target"], df_common_features['Max'])
  df_common_features['LTT'] = np.where(df_common_features['Strategy']== 'BTT', df_common_features["Target"], df_common_features['Max'])
  df_common_features['BOL'] = df_common_features['Min']

  tmp_df = df_common_features[df_common_features['Symbol'].isin(mypf_df[mypf_df['InPortfolio'] != 'NA'].Symbol.values)]
  print('qualified stocks: '+str(len(tmp_df['Symbol'].unique())))
  tmp_df1 = tmp_df[tmp_df['LatestQtr'] == 1]
  print('with latest results: '+str(len(tmp_df1['Symbol'].unique())))
  tmp_df1 = tmp_df1[tmp_df1['StarStock'] == 1]
  print('still star stocks: '+str(len(tmp_df1['Symbol'].unique())))
  tmp_df['Investment'] = tmp_df['AvgCost'] * tmp_df['Shares']
  tmp_df['Current'] = round(tmp_df['Close'] * tmp_df['Shares'],0)
  tmp_df['Previous'] = tmp_df['Prev_Close'] * tmp_df['Shares']
  tmp_df['EstimatedST'] = tmp_df['NTT'] * tmp_df['Shares']
  tmp_df['EstimatedLT'] = tmp_df['LTT'] * tmp_df['Shares']
  tmp_df['Current P/L'] = round((tmp_df['Current'] - tmp_df['Investment']),0)
  tmp_df['Today P/L%'] = round((tmp_df['Current'] - tmp_df['Previous'])*100/tmp_df['Previous'],2)
  tmp_df['Current P/L%'] = round((tmp_df['Current'] - tmp_df['Investment'])*100/tmp_df['Investment'],2)
  tmp_df['EstimatedST P/L%'] = round((tmp_df['EstimatedST'] - tmp_df['Investment'])*100/tmp_df['Investment'],2)
  tmp_df['EstimatedLT P/L%'] = round((tmp_df['EstimatedLT'] - tmp_df['Investment'])*100/tmp_df['Investment'],2)
  tmp_df['NTT%'] = round((tmp_df['NTT'] - tmp_df['Close'])*100/tmp_df['Close'],2)
  tmp_df['LTT%'] = round((tmp_df['LTT'] - tmp_df['Close'])*100/tmp_df['Close'],2)
  tmp_df['Gained%'] = round((tmp_df['Close'] - tmp_df['BOL'])*100/tmp_df['BOL'],2)
  investment = round(sum(tmp_df['AvgCost']*tmp_df['Shares']),0)
  current = round(sum(tmp_df['Close']*tmp_df['Shares']),0)
  tmp_df['InitAlloc%'] = round(tmp_df['Investment']*100/investment,2)
  tmp_df['CurrAlloc%'] = round(tmp_df['Current']*100/current,2)
  tmp_df['FTT'] = tmp_df['LTT']
  tmp_df.loc[tmp_df['Strategy'] == 'NTT', 'FTT'] = tmp_df['NTT']
  tmp_df['FTT%'] = tmp_df['LTT%']
  tmp_df.loc[tmp_df['Strategy'] == 'NTT', 'FTT%'] = tmp_df['NTT%']
  tmp_df['FTT Amt'] = round(tmp_df['FTT%'] * tmp_df['Current']/100,0)
  tmp_df['OTT%'] = round((tmp_df['FTT'] - tmp_df['AvgCost'])*100/tmp_df['AvgCost'],2)
  tmp_df['RRR Ind'] = round(tmp_df['Current P/L']/tmp_df['FTT Amt'],2)
  tmp_df['Risk Ind'] = round(tmp_df['Current P/L%']*tmp_df['CurrAlloc%'],0)

  return tmp_df

# function to print portfolio features
def print_portfolio_stats(df_portfolio_features, myinvmt_df):
  from pyxirr import xirr

  total_booked_amt, reserve_amt, cy_booked_amt, py_booked_amt = get_amt()

  dates = myinvmt_df['Date'].values
  dates = np.append(dates, datetime.date.today().strftime('%d-%b-%y'))
  investment = myinvmt_df['Investment'].values
  dates= pd.to_datetime(dates)

  current = round(sum(df_portfolio_features['Close']*df_portfolio_features['Shares']),0) + reserve_amt
  investment_xirr = np.append(investment, current)
  cagr = round(xirr(pd.DataFrame({"dates": dates, "amounts": investment_xirr}))*100,2)

  investment = -sum(investment)
  invested = round(sum(df_portfolio_features['AvgCost']*df_portfolio_features['Shares']),0) + reserve_amt
  previous = round(sum(df_portfolio_features['Prev_Close']*df_portfolio_features['Shares']),0) + reserve_amt
  cy_invested = investment + py_booked_amt

  today_pnl_amount = current-previous
  today_pnl_percentage = round((current-previous)*100/previous,2)

  curr_pnl_amount = current-invested
  curr_pnl_percentage = round((curr_pnl_amount)*100/(cy_invested),2)

  cy_pnl_amount = cy_booked_amt + curr_pnl_amount
  cy_pnl_percentage = round((cy_pnl_amount)*100/cy_invested,2)

  overall_pnl_amount = total_booked_amt + curr_pnl_amount
  overall_pnl_percentage = round((overall_pnl_amount)*100/investment,2)

  estimate_st = round(sum(df_portfolio_features['FTT']*df_portfolio_features['Shares']),0)  + reserve_amt
  est_st_pnl_amount = estimate_st-current
  est_st_pnl_percentage = round((est_st_pnl_amount)*100/current,2)

  estimate_lt = round(sum(df_portfolio_features['LTT']*df_portfolio_features['Shares']),0)  + reserve_amt
  est_lt_pnl_amount = estimate_lt-current
  est_lt_pnl_percentage = round((est_lt_pnl_amount)*100/current,2)

  total_profit = round(sum(df_portfolio_features[df_portfolio_features['Current P/L%'] > 0]['Current']) - sum(df_portfolio_features[df_portfolio_features['Current P/L%'] > 0]['Investment']),0)
  total_loss = round(sum(df_portfolio_features[df_portfolio_features['Current P/L%'] < 0]['Current']) - sum(df_portfolio_features[df_portfolio_features['Current P/L%'] < 0]['Investment']),0)

  cy_booked_percentage = round((cy_booked_amt)*100/current,2)
  py_booked_percentage = round((py_booked_amt)*100/investment,2)
  total_booked_percentage = round((total_booked_amt)*100/investment,2)

  print('-------------------')
  print('Initial Investment: ', format_amt(investment))
  print('CY Investment: ', format_amt(cy_invested))
  print('Reserve: ', format_amt(reserve_amt))
  print('Current: ',  format_amt(current))
  print('-------------------')
  print('Today PnL: '+ '{} ({}%)'.format(format_amt(today_pnl_amount), today_pnl_percentage))
  print('Current PnL: '+ '{} ({}%)'.format(format_amt(curr_pnl_amount), curr_pnl_percentage))
  print('CY Booked + Current PnL: '+ '{} ({}%)'.format(format_amt(cy_pnl_amount), cy_pnl_percentage))
  print('-------------------')
  print('Total profit: ', format_amt(total_profit))
  print('Total loss: ', format_amt(total_loss))
  print('-------------------')
  print('Total Booked + Current PnL: '+ '{} ({}%)'.format(format_amt(overall_pnl_amount), overall_pnl_percentage))
  print('Total Booked PnL: '+ '{} ({}%)'.format(format_amt(total_booked_amt), total_booked_percentage))
  print('Curr Year Booked PnL: '+ '{} ({}%)'.format(format_amt(cy_booked_amt), cy_booked_percentage))
  print('Prev Year Booked PnL: '+ '{} ({}%)'.format(format_amt(py_booked_amt), py_booked_percentage))
  print('===================')
  print('Est FTT: ',  format_amt(estimate_st))
  print('Est FTT PnL: '+ '{} ({}%)'.format(format_amt(est_st_pnl_amount), est_st_pnl_percentage))

  print('===================')
  print('Deployed: ', format_amt(investment))

  print('Current: ', format_amt(current))

  print('CAGR/XIRR %: '+'{}%'.format(cagr))

In [8]:
# get start and end date
start_date, end_date = get_start_end_date()

# get portfolio and prospects data
mypfs_df = get_mypfs_df()
mypps_df = get_mypps_df()
myinvmt_df = get_myinvmt_df()

# merge above datasets
mypf_df = pd.merge(mypfs_df, mypps_df, on="Symbol")

# seggregate dm and sv portfolio
dm_pf = mypf_df[mypf_df['InPortfolio'] == 'DM']
sv_pf = mypf_df[mypf_df['InPortfolio'] == 'SV']

# build portfolio stock dataframe
dm_stocks = get_stock_ids(dm_pf)
sv_stocks = get_stock_ids(sv_pf)
df_stocks = pd.concat([dm_pf,sv_pf], ignore_index = True)

# arrange common and diff stock features
common_cols = ['Symbol', 'Target', 'Criteria', 'Strategy', 'CumlRnk', 'LatestQtr', 'StarStock', 'Conviction', 'Category', 'InFolio', 'XIRR', 'MBQ']
diff_cols = ['Symbol', 'AvgCost', 'Shares']
df_stocks = arrange_features(df_stocks, common_cols, diff_cols)

# get common features
stock_ids = df_stocks['Symbol'].values
df_common_features = get_common_features(stock_ids, df_stocks)

df_common_features.reset_index(drop=True, inplace=True)
df_common_features.drop(['Date'], axis=1, inplace=True)
# get and print portfolio features
df_portfolio_features = get_portfolio_features(df_common_features)

print_portfolio_stats(df_portfolio_features, myinvmt_df)

df = df_portfolio_features
#plot_pie_chart(df, 'CapType', 'Current')
list_ox40n = list(df[df['MBQ'].str.contains('OX40N', na=False)]['Symbol'].values)

Run date time (IST): 2026-03-24 13:13:34
-------------------
qualified stocks: 86
with latest results: 26
still star stocks: 16
-------------------
Initial Investment:  1.36 C
CY Investment:  1.62 C
Reserve:  1.61 K
Current:  1.29 C
-------------------
Today PnL: 2.45 L (1.93%)
Current PnL: -47.95 L (-29.51%)
CY Booked + Current PnL: -32.06 L (-19.73%)
-------------------
Total profit:  49.36 K
Total loss:  -48.45 L
-------------------
Total Booked + Current PnL: -5.08 L (-3.75%)
Total Booked PnL: 42.87 L (31.64%)
Curr Year Booked PnL: 15.89 L (12.3%)
Prev Year Booked PnL: 26.98 L (19.91%)
===================
Est FTT:  2.48 C
Est FTT PnL: 1.19 C (91.9%)
===================
Deployed:  1.36 C
Current:  1.29 C
CAGR/XIRR %: -2.35%

In [9]:
# top 5 near their targets
cols = ['Symbol', 'Today P/L%', 'Current P/L%', 'FTT%', 'OTT%', 'FTT Amt', 'Current P/L', 'Current', 'FTT', 'Dev%_PE', 'RSI_14','Conviction', 'Spread%',  'CumlRnk', 'RRR Ind', 'CurrAlloc%', 'Gained%', 'Criteria', 'Strategy', 'Category']
df_tmp = df_portfolio_features[~df_portfolio_features['Symbol'].isin(['ENRIN','BLUSPRING','DIGITIDE'])]
df_tmp = df_tmp.sort_values(by = 'FTT Amt', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
50,MASFIN,0.72,-9.55,34.41,21.57,30494.0,-9360.0,88620.0,397.04,-21.86,40.0,H-SC,2.38,167.0,-0.31,0.69,20.87,XR,ATH,FINANCE
77,TTKPRESTIG,-3.67,-42.84,75.12,0.09,43270.0,-43176.0,57601.0,770.00,33.62,34.0,M-SC,19.18,250.0,-1.00,0.45,0.00,OX40N,NTT,DURABLES
2,ABBOTINDIA,4.06,-11.03,32.71,18.07,52048.0,-19735.0,159120.0,35195.00,-24.24,48.0,X-MC,10.64,58.0,-0.38,1.23,4.06,X40,ATH,PHARMA
67,SONACOMS,2.10,-14.34,62.38,39.09,54053.0,-14508.0,86651.0,804.02,-32.08,46.0,M-MC,7.46,193.0,-0.27,0.67,22.58,AR,ATH,AUTO
37,ICICIGI,1.19,-7.69,29.28,19.34,54088.0,-15383.0,184726.0,2252.93,-22.28,30.0,X-MC,3.70,66.0,-0.28,1.43,2.12,X40,ATH,INSURANCE

In [10]:
# top 5 today
df_tmp = df_portfolio_features.sort_values(by = 'Today P/L%', ascending=False)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
4,ALKYLAMINE,9.29,-42.31,235.65,93.63,137252.0,-42719.0,58244.0,4546.37,-38.22,47.0,H-SC,25.88,142.0,-0.31,0.45,9.29,SR,ATH,CHEMICALS
7,ATULAUTO,4.99,-29.18,105.55,45.57,147352.0,-57528.0,139604.0,844.00,3008.11,42.0,M-SC,4.43,248.0,-0.39,1.08,5.65,XY24,NTT,AUTO
74,TITAGARH,4.48,-41.47,149.01,45.74,211201.0,-100441.0,141736.0,1548.00,-22.13,36.0,H-SC,21.58,175.0,-0.48,1.10,4.48,XY24,NTT,ENGINEERING
47,JSWINFRA,4.33,-14.30,35.85,16.43,68140.0,-31703.0,190071.0,342.00,-26.60,46.0,X-MC,11.57,61.0,-0.47,1.47,4.33,X40N,NTT,REALTY
2,ABBOTINDIA,4.06,-11.03,32.71,18.07,52048.0,-19735.0,159120.0,35195.00,-24.24,48.0,X-MC,10.64,58.0,-0.38,1.23,4.06,X40,ATH,PHARMA

In [11]:
# bottom 5 today
df_tmp = df_portfolio_features.sort_values(by = 'Today P/L%', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
55,RAJESHEXPO,-4.99,-83.61,510.49,0.07,114784.0,-114692.0,22485.0,518.0,724.49,14.0,L-SC,34.55,268.0,-1.00,0.17,0.00,OX40N,NTT,JEWELLERY
77,TTKPRESTIG,-3.67,-42.84,75.12,0.09,43270.0,-43176.0,57601.0,770.0,33.62,34.0,M-SC,19.18,250.0,-1.00,0.45,0.00,OX40N,NTT,DURABLES
69,SURYODAY,-3.17,-30.86,77.94,23.03,96504.0,-55253.0,123818.0,216.0,35.96,41.0,H-SC,6.49,166.0,-0.57,0.96,21.01,XR,NTT,BANKS
0,5PAISA,-1.56,-47.67,115.75,12.90,132346.0,-104158.0,114338.0,593.0,68.27,30.0,H-SC,13.72,170.0,-0.79,0.89,0.00,OX40N,NTT,FINANCE
76,TRIDENT,-1.32,-33.82,94.17,28.51,57498.0,-31196.0,61058.0,48.0,-14.85,51.0,M-SC,14.11,223.0,-0.54,0.47,12.06,XR,NTT,TEXTILES

In [12]:
# top 5 to exit based on CumlRnk
df_tmp = df_portfolio_features[~df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])]
df_tmp = df_tmp[(df_tmp['Current P/L%'] > -1) & (df_tmp['Current P/L%'] < 1)].sort_values(by = 'CumlRnk', ascending=False)
df_tmp[cols].head()

Empty DataFrame
Columns: [Symbol, Today P/L%, Current P/L%, FTT%, OTT%, FTT Amt, Current P/L, Current, FTT, Dev%_PE, RSI_14, Conviction, Spread%, CumlRnk, RRR Ind, CurrAlloc%, Gained%, Criteria, Strategy, Category]
Index: []

In [13]:
# OX40N stocks to exit
df_tmp = df_portfolio_features[(df_portfolio_features['Symbol'].isin(list_ox40n))].sort_values(by = 'Current P/L%', ascending=False)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
26,FINCABLES,3.37,5.87,96.39,107.91,150661.0,8660.0,156304.0,1641.55,-4.62,47.0,M-SC,8.25,220.0,0.06,1.21,17.59,OX40N,ATH,CABLES
66,SIS,3.60,-37.24,93.23,21.26,64962.0,-41353.0,69679.0,528.00,1626.42,37.0,H-SC,14.32,168.0,-0.64,0.54,3.60,OX40N,NTT,MISC
18,CERA,2.21,-38.75,102.27,23.89,110187.0,-68162.0,107741.0,9475.00,-40.81,45.0,H-SC,18.97,153.0,-0.62,0.83,3.54,OX40N,NTT,CERAMICS
72,TATAELXSI,1.44,-39.61,118.63,32.03,94446.0,-52221.0,79614.0,9161.00,-24.40,38.0,H-SC,20.94,158.0,-0.55,0.62,3.74,OX40N,NTT,IT
77,TTKPRESTIG,-3.67,-42.84,75.12,0.09,43270.0,-43176.0,57601.0,770.00,33.62,34.0,M-SC,19.18,250.0,-1.00,0.45,0.00,OX40N,NTT,DURABLES

In [14]:
# top 5 to book for rotation
df_tmp = df_portfolio_features[(df_portfolio_features['Current P/L%'] > 20) ].sort_values(by = 'CumlRnk', ascending=False)
df_tmp[cols].head()

Empty DataFrame
Columns: [Symbol, Today P/L%, Current P/L%, FTT%, OTT%, FTT Amt, Current P/L, Current, FTT, Dev%_PE, RSI_14, Conviction, Spread%, CumlRnk, RRR Ind, CurrAlloc%, Gained%, Criteria, Strategy, Category]
Index: []

In [15]:
# top 5 to monitor for exit
df_tmp = df_portfolio_features[~df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])]
df_tmp = df_tmp[(df_tmp['Current P/L%'] > 0) ].sort_values(by = 'Dev%_PE', ascending=False)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
26,FINCABLES,3.37,5.87,96.39,107.91,150661.0,8660.0,156304.0,1641.55,-4.62,47.0,M-SC,8.25,220.0,0.06,1.21,17.59,OX40N,ATH,CABLES
1,ABB,3.09,14.27,27.39,45.57,81881.0,37325.0,298944.0,7934.00,-26.59,56.0,H-MC,13.33,125.0,0.46,2.31,32.75,AR,NTT,ELECTRICAL

In [16]:
# top 5 to book for rotation from weak conviction
df_tmp = df_portfolio_features[~df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])]
df_tmp = df_tmp[~df_tmp['Criteria'].isin(['XY25','XY24','X40', 'X40N'])].sort_values(by = 'RRR Ind', ascending=False)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
1,ABB,3.09,14.27,27.39,45.57,81881.0,37325.0,298944.0,7934.00,-26.59,56.0,H-MC,13.33,125.0,0.46,2.31,32.75,AR,NTT,ELECTRICAL
26,FINCABLES,3.37,5.87,96.39,107.91,150661.0,8660.0,156304.0,1641.55,-4.62,47.0,M-SC,8.25,220.0,0.06,1.21,17.59,OX40N,ATH,CABLES
40,INDIAMART,-1.20,-15.32,144.13,106.72,150524.0,-18900.0,104436.0,4810.62,-61.72,30.0,H-SC,11.23,140.0,-0.13,0.81,4.47,AR,ATH,MISC
85,ZYDUSLIFE,2.53,-6.95,45.76,35.63,89237.0,-14564.0,195010.0,1286.17,-18.92,45.0,H-MC,5.42,120.0,-0.16,1.51,8.56,AR,ATH,PHARMA
84,WIPRO,1.16,-22.19,121.38,72.27,160046.0,-37593.0,131855.0,420.00,-29.71,33.0,M-LC,17.81,98.0,-0.23,1.02,1.16,XR,NTT,IT

In [17]:
# top 5 to accumulate based on lowest RSI_14
df_tmp = df_portfolio_features[df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])].sort_values(by = 'RSI_14', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
53,PGHH,0.68,-28.66,85.05,32.01,129548.0,-61200.0,152320.0,17616.87,-51.69,15.0,X-MC,15.84,57.0,-0.47,1.18,0.68,X40,ATH,FMCG
12,BATAINDIA,0.71,-59.35,232.59,35.20,121661.0,-76363.0,52307.0,2096.00,-31.41,20.0,X-SC,31.26,91.0,-0.63,0.40,0.71,X40,NTT,FOOTWEAR
58,RELAXO,1.69,-66.44,353.79,52.31,172366.0,-96440.0,48720.0,1176.00,-64.28,21.0,X-SC,26.56,92.0,-0.56,0.38,1.69,X40N,NTT,FOOTWEAR
9,BAJAJHFL,-0.76,-30.41,132.96,62.13,252653.0,-83024.0,190022.0,181.50,-42.81,24.0,X-MC,20.46,60.0,-0.33,1.47,0.00,X40N,ATH,FINANCE
38,ICICIPRULI,1.84,-10.47,46.01,30.73,81153.0,-20623.0,176382.0,790.00,-34.56,24.0,X-MC,4.41,78.0,-0.25,1.37,1.84,X40,ATH,INSURANCE

In [18]:
# top 5 to accumulate based on Spread and CumlRnk
df_tmp = df_portfolio_features[df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])]
df_tmp = df_tmp[(df_tmp['CumlRnk'] < 100)].sort_values(by = 'Spread%', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
78,UNITDSPR,3.56,-2.99,24.49,20.77,55627.0,-7001.0,227143.0,1644.00,-14.02,46.0,X-MC,1.64,64.0,-0.13,1.76,3.56,X40N,NTT,BREWERIES
65,SIEMENS,1.50,-18.51,54.02,25.51,81924.0,-34440.0,151655.0,4671.50,27.32,42.0,H-LC,2.82,51.0,-0.42,1.17,11.68,AR,ATH,ELECTRICAL
59,RELIANCE,0.50,-9.18,37.97,25.30,69299.0,-18454.0,182509.0,1952.00,-11.57,52.0,X-LC,3.44,21.0,-0.27,1.41,21.85,XY25,BTT,REFINERIES
37,ICICIGI,1.19,-7.69,29.28,19.34,54088.0,-15383.0,184726.0,2252.93,-22.28,30.0,X-MC,3.70,66.0,-0.28,1.43,2.12,X40,ATH,INSURANCE
82,VOLTAS,3.96,1.76,42.68,45.20,83277.0,3378.0,195120.0,1856.00,16.53,35.0,X-MC,3.98,79.0,0.04,1.51,8.68,XY25,NTT,AC

In [19]:
# top 5 to accumulate based on lowest Gained%
df_tmp = df_portfolio_features[df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])].sort_values(by = 'Gained%', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
9,BAJAJHFL,-0.76,-30.41,132.96,62.13,252653.0,-83024.0,190022.0,181.50,-42.81,24.0,X-MC,20.46,60.0,-0.33,1.47,0.00,X40N,ATH,FINANCE
45,ITC,0.36,-23.22,55.06,19.06,143808.0,-78982.0,261184.0,452.00,-57.95,31.0,X-LC,18.65,1.0,-0.55,2.02,0.36,X40,NTT,FMCG
51,MEDANTA,0.68,-16.49,52.22,27.12,76975.0,-29111.0,147406.0,1486.00,-18.99,26.0,X-SC,12.30,87.0,-0.38,1.14,0.68,XY24,NTT,HEALTHCARE
53,PGHH,0.68,-28.66,85.05,32.01,129548.0,-61200.0,152320.0,17616.87,-51.69,15.0,X-MC,15.84,57.0,-0.47,1.18,0.68,X40,ATH,FMCG
12,BATAINDIA,0.71,-59.35,232.59,35.20,121661.0,-76363.0,52307.0,2096.00,-31.41,20.0,X-SC,31.26,91.0,-0.63,0.40,0.71,X40,NTT,FOOTWEAR

In [20]:
# top 5 to accumulate based on lowest CurrAlloc%
df_tmp = df_portfolio_features[df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])].sort_values(by = 'CurrAlloc%', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
58,RELAXO,1.69,-66.44,353.79,52.31,172366.0,-96440.0,48720.0,1176.00,-64.28,21.0,X-SC,26.56,92.0,-0.56,0.38,1.69,X40N,NTT,FOOTWEAR
12,BATAINDIA,0.71,-59.35,232.59,35.20,121661.0,-76363.0,52307.0,2096.00,-31.41,20.0,X-SC,31.26,91.0,-0.63,0.40,0.71,X40,NTT,FOOTWEAR
54,QUESS,3.62,-27.81,140.88,73.90,108614.0,-29696.0,77097.0,424.00,-61.43,38.0,X-SC,21.45,80.0,-0.27,0.60,3.62,XY24,NTT,MISC
36,HONAUT,2.28,-27.83,109.65,51.31,152605.0,-53663.0,139175.0,58357.33,-40.01,29.0,X-SC,15.82,90.0,-0.35,1.08,2.28,X40N,ATH,ELECTRICAL
51,MEDANTA,0.68,-16.49,52.22,27.12,76975.0,-29111.0,147406.0,1486.00,-18.99,26.0,X-SC,12.30,87.0,-0.38,1.14,0.68,XY24,NTT,HEALTHCARE

In [21]:
# top 5 to accumulate based on CumlRnk
df_tmp = df_portfolio_features.sort_values(by = 'CumlRnk', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
45,ITC,0.36,-23.22,55.06,19.06,143808.0,-78982.0,261184.0,452.00,-57.95,31.0,X-LC,18.65,1.0,-0.55,2.02,0.36,X40,NTT,FMCG
73,TCS,1.21,-29.17,78.70,26.57,258236.0,-135146.0,328127.0,4311.59,-40.02,32.0,X-LC,17.35,2.0,-0.52,2.54,2.41,X40,ATH,IT
43,INFY,2.59,-12.23,52.95,34.24,145412.0,-38267.0,274621.0,1972.00,-31.06,44.0,X-LC,15.15,3.0,-0.26,2.13,5.61,X40,NTT,IT
75,TMPV,2.41,-28.84,91.94,36.58,232798.0,-102635.0,253206.0,600.00,-84.72,36.0,X-LC,6.68,4.0,-0.44,1.96,2.41,XY24,NTT,AUTO
33,HCLTECH,1.93,-10.13,37.80,23.83,82182.0,-24510.0,217414.0,1908.19,-5.71,47.0,X-LC,11.81,8.0,-0.30,1.68,5.56,X40,ATH,IT

In [22]:
# top 5 for average up
df_tmp = df_portfolio_features[(df_portfolio_features['Dev%_200'] > 5)].sort_values(by = 'CurrAlloc%', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
1,ABB,3.09,14.27,27.39,45.57,81881.0,37325.0,298944.0,7934.0,-26.59,56.0,H-MC,13.33,125.0,0.46,2.31,32.75,AR,NTT,ELECTRICAL

In [23]:
# top 5 RSP
df_tmp = df_portfolio_features.sort_values(by = 'RSP', ascending=False)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
30,HAPPSTMNDS,0.41,-50.78,275.58,84.85,173836.0,-65085.0,63080.0,1480.71,-41.42,53.0,H-SC,26.54,152.0,-0.37,0.49,16.81,AR,ATH,IT
69,SURYODAY,-3.17,-30.86,77.94,23.03,96504.0,-55253.0,123818.0,216.00,35.96,41.0,H-SC,6.49,166.0,-0.57,0.96,21.01,XR,NTT,BANKS
33,HCLTECH,1.93,-10.13,37.80,23.83,82182.0,-24510.0,217414.0,1908.19,-5.71,47.0,X-LC,11.81,8.0,-0.30,1.68,5.56,X40,ATH,IT
26,FINCABLES,3.37,5.87,96.39,107.91,150661.0,8660.0,156304.0,1641.55,-4.62,47.0,M-SC,8.25,220.0,0.06,1.21,17.59,OX40N,ATH,CABLES
1,ABB,3.09,14.27,27.39,45.57,81881.0,37325.0,298944.0,7934.00,-26.59,56.0,H-MC,13.33,125.0,0.46,2.31,32.75,AR,NTT,ELECTRICAL

In [24]:
# Top N allocation
df_tmp = df_portfolio_features.sort_values(by = 'CurrAlloc%', ascending=False)
top_n_values = [10, 25, 50]

sum_df = pd.DataFrame({
    'Top_N': top_n_values,
    'Sum_Alloc%': [df_tmp['CurrAlloc%'].head(n).sum() for n in top_n_values]
})

sum_df

   Top_N  Sum_Alloc%
0     10       20.86
1     25       45.97
2     50       78.26

In [25]:
# market-cap-wise allocation
df_tmp = df_portfolio_features[cols]
df_tmp.groupby(df_tmp['Conviction'].str[-2:])['CurrAlloc%'].sum().sort_values(ascending=False)

Conviction
SC    44.08
MC    30.20
LC    25.71
Name: CurrAlloc%, dtype: float64

In [26]:
# criteria-wise allocation
df_portfolio_features.groupby('Criteria')['CurrAlloc%'].sum().sort_values(ascending=False)

Criteria
XY24     26.82
X40      25.67
X40N     15.19
AR        9.19
XR        8.26
XY25      7.37
OX40N     6.68
SR        0.81
Name: CurrAlloc%, dtype: float64

In [27]:
# conviction-wise allocation
df_portfolio_features.groupby('Conviction')['CurrAlloc%'].sum().sort_values(ascending=False)

Conviction
X-LC    23.52
X-MC    22.70
H-SC    21.46
X-SC    12.18
M-SC     9.93
H-MC     5.12
M-MC     2.03
H-LC     1.17
M-LC     1.02
L-SC     0.51
L-MC     0.35
Name: CurrAlloc%, dtype: float64

In [28]:
# sector-wise stats
df_tmp = df_portfolio_features.groupby('Category')[['CurrAlloc%', 'Current', 'Current P/L', 'FTT Amt']].sum().sort_values(by=['Current', 'Current P/L'], ascending=False)
df_tmp['Current P/L%'] = round(df_tmp['Current P/L'] * 100 / df_tmp['Current'], 2)
df_tmp['FTT%'] = round(df_tmp['FTT Amt'] * 100 / df_tmp['Current'], 2)
cols = ['CurrAlloc%', 'Current P/L%', 'FTT%']
df_tmp[cols].sort_values(by=['CurrAlloc%'], ascending=False)

               CurrAlloc%  Current P/L%    FTT%
Category
FMCG                15.09        -28.17   73.68
FINANCE             12.98        -28.32   80.61
IT                  11.99        -45.53  119.59
MISC                 6.90        -50.44  115.79
ELECTRICAL           6.59        -13.69   57.22
PAINTS               5.09        -49.65   75.64
INSURANCE            4.71        -11.67   49.89
BANKS                4.55        -31.19   97.78
PHARMA               4.18         -8.85   43.11
AUTO                 3.71        -36.43   90.56
AC                   2.04        -21.04   53.86
HEALTHCARE           1.86        -48.52   87.28
TRAVEL               1.80        -92.33  188.63
BREWERIES            1.76         -3.08   24.49
DURABLES             1.76        -71.06  112.68
FOOTWEAR             1.75        -94.63  172.68
APPARELS             1.74        -19.35   60.06
REALTY               1.47        -16.68   35.85
REFINERIES           1.41        -10.11   37.97
CERAMICS             1.38        -72.01  124.27
CEMENT               1.24        -66.81  191.60
CABLES               1.21          5.54   96.39
ENGINEERING          1.10        -70.86  149.01
CHEMICALS            1.08        -89.87  244.78
JEWELLERY            1.04       -136.47  218.63
ENTERTAINMENT        0.75       -100.48  220.05
TEXTILES             0.47        -51.09   94.17
HOTELS               0.34       -155.13  245.13

In [29]:
# money to be made criteria-wise
df_portfolio_features.groupby('Criteria')['FTT Amt'].agg(['sum', 'count']).sort_values(by='sum', ascending=False)

                sum  count
Criteria
XY24      4132413.0     21
X40       1859708.0     16
XR        1424186.0     12
AR        1383870.0     10
X40N      1339024.0     10
OX40N      928784.0     10
XY25       488346.0      5
SR         314753.0      2

In [30]:
# money to be made conviction-wise
df_portfolio_features.groupby('Conviction')['FTT Amt'].agg(['sum', 'count']).sort_values(by='sum', ascending=False)

                  sum  count
Conviction
H-SC        4023579.0     24
X-MC        1802149.0     15
X-LC        1739175.0     13
M-SC        1633730.0     14
X-SC        1608932.0     10
H-MC         416926.0      3
L-SC         223882.0      2
M-LC         160046.0      1
M-MC         123320.0      2
H-LC          81924.0      1
L-MC          57421.0      1

In [31]:
# money to be made criteria and conviction-wise
df_portfolio_features.groupby(['Conviction', 'Criteria'])['FTT Amt'].agg(['sum', 'count']).sort_values(by='sum', ascending=False)

                           sum  count
Conviction Criteria
H-SC       XY24      1405939.0      6
           AR         996617.0      5
M-SC       XY24       948221.0      6
X-LC       X40        929010.0      7
H-SC       XR         904329.0      7
X-SC       XY24       870275.0      4
X-MC       X40        714433.0      7
           X40N       542748.0      4
X-SC       X40N       522392.0      4
M-SC       OX40N      412059.0      5
H-SC       OX40N      401941.0      4
X-LC       XY24       385152.0      2
H-SC       SR         314753.0      2
X-MC       XY24       277018.0      2
X-LC       X40N       273884.0      2
X-MC       XY25       267950.0      2
H-MC       XY24       245808.0      1
X-SC       X40        216265.0      2
M-SC       XR         193292.0      2
H-MC       AR         171118.0      2
M-LC       XR         160046.0      1
X-LC       XY25       151129.0      2
L-SC       OX40N      114784.0      1
           XR         109098.0      1
H-LC       AR          81924.0      1
M-SC       AR          80158.0      1
M-MC       XY25        69267.0      1
L-MC       XR          57421.0      1
M-MC       AR          54053.0      1

In [32]:
# notebook execution time

end_time = time.time()
execution_time = round(end_time - start_time, 0)
print(f"Notebook execution time: {execution_time} seconds")

Notebook execution time: 46.0 seconds