<a href="https://colab.research.google.com/github/ankit-rathi/Quantvesting_v2/blob/main/myStocks_Portfolio_Analysis.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
'''
!pip install pandas==2.2.2 -qq
!pip install pyxirr -qq
!pip install ta -qq
!pip install yfinance==0.2.59 -qq
'''

'\n!pip install pandas==2.2.2 -qq\n!pip install pyxirr -qq\n!pip install ta -qq\n!pip install yfinance==0.2.59 -qq\n'

In [2]:
# import libraries

import numpy as np
import pandas as pd
import datetime
import warnings
warnings.filterwarnings('ignore')
import yfinance as yfin
import ta
import matplotlib.pyplot as plt
import requests

In [3]:
# notebook start time
import time
import datetime
import pytz

start_time = time.time()

# function to print date timestamp
def print_date_time():
  tz_NY = pytz.timezone('Asia/Kolkata')
  datetime_NY = datetime.datetime.now(tz_NY)
  print("Run date time (IST):", datetime_NY.strftime("%Y-%m-%d %H:%M:%S"))

In [4]:
# function to get booked and reserved amount
def get_amt():
  # fetch the JSON data from the URL
  url = "https://raw.githubusercontent.com/ankit-rathi/Tradevesting_v1/main/data/myPortfolioAmts.json"
  response = requests.get(url)
  pf_amts = response.json()  # parse the JSON data

  # extract values from the JSON
  py_booked_amt_dm = pf_amts["py_booked_amt_dm"]
  py_booked_amt_sv = pf_amts["py_booked_amt_sv"]
  cy_booked_amt_dm = pf_amts["cy_booked_amt_dm"]
  cy_booked_amt_sv = pf_amts["cy_booked_amt_sv"]
  reserve_amt_dm = pf_amts["reserve_amt_dm"]
  reserve_amt_sv = pf_amts["reserve_amt_sv"]

  # perform calculations
  py_booked_amt = py_booked_amt_dm + py_booked_amt_sv
  cy_booked_amt = cy_booked_amt_dm + cy_booked_amt_sv
  reserve_amt = reserve_amt_dm + reserve_amt_sv
  total_booked_amt = py_booked_amt + cy_booked_amt

  return total_booked_amt, reserve_amt, cy_booked_amt, py_booked_amt

gen_output = 0

In [5]:
# function to format the amount
def format_amt(number):
    abs_number = abs(number)

    if abs_number >= 1_00_00_000:  # Crores
        formatted_amt = f"{number / 1_00_00_000:.2f} C"
    elif abs_number >= 1_00_000:  # Lakhs
        formatted_amt = f"{number / 1_00_000:.2f} L"
    elif abs_number >= 1_000:  # Thousands
        formatted_amt = f"{number / 1_000:.2f} K"
    else:
        formatted_amt = f"{number:.2f}"

    return formatted_amt

# function to set start and end date
def get_start_end_date():
  start_date = (datetime.date.today() + datetime.timedelta(days=-365)).strftime('%Y-%m-%d')
  end_date = (datetime.date.today() + datetime.timedelta(days=1)).strftime('%Y-%m-%d')
  return start_date, end_date

# function to fetch my portfolio csv
def get_mypfs_df():
  mypfs_df = pd.read_csv('https://raw.githubusercontent.com/ankit-rathi/Tradevesting_v1/main/data/myPortfolioStocks.csv')
  return mypfs_df

# function to fetch my prospects csv
def get_mypps_df():
  mypps_df = pd.read_csv('https://raw.githubusercontent.com/ankit-rathi/Tradevesting_v1/main/data/myProspectsScrips.csv')
  return mypps_df

# function to fetch screener data
def get_myscreen_df():
  myscreen_df = pd.read_csv('https://raw.githubusercontent.com/ankit-rathi/Tradevesting_v1/main/data/myScreenerDB.csv')
  return myscreen_df

# function to fetch momentum data
def get_myinvmt_df():
  myinvmt_df = pd.read_csv('https://raw.githubusercontent.com/ankit-rathi/Tradevesting_v1/main/data/myInvestments.csv')
  return myinvmt_df

# function to get the stock ids
def get_stock_ids(df_pf):
  stock_n100 = df_pf['Symbol'].unique()

  exclude = ['CADILAHC','MMTC', 'MASFIN']

  stock_ids = df_pf[~df_pf['Symbol'].isin(exclude) ]['Symbol'].unique()

  #mypf = mypf[mypf.Forecast.notnull()]
  #stock_ids = mypf['Symbol'].unique()

  #stock_ids.sort()
  return stock_ids

# get features from screener data
def get_screener_features():
  myscreen_df = get_myscreen_df()
  cols = ['Symbol', 'EPS', 'MedPE', 'ROCE%', 'ROE%', 'CapType']
  return myscreen_df[cols]

# get relative strength
def get_relative_strength(stock_list):

    # Dictionary to store stock tickers and their corresponding percentage price change
    stock_changes = {}

    # Loop through each stock and fetch its price data
    for stock in stock_list:
        try:
            # Download the stock data for the given date range
            stock_data = yfin.Ticker(stock + '.NS').history(period='1mo', interval='1d')[map(str.title, ['open', 'close', 'low', 'high', 'volume'])]

            # Calculate the percentage change for the stock
            if len(stock_data) > 0:
                start_price = stock_data['Close'].iloc[0]
                end_price = stock_data['Close'].iloc[-1]
                percent_change = round(((end_price - start_price) / start_price) * 100, 2)
                stock_changes[stock] = percent_change
            else:
                stock_changes[stock] = np.nan  # If no data is available, set to NaN

        except Exception as e:
            print(f"Error fetching data for {stock}: {e}")
            stock_changes[stock] = np.nan

    # Create a DataFrame with stock tickers and their percentage changes
    df = pd.DataFrame(list(stock_changes.items()), columns=['Symbol', 'Percent_Change'])

    # Drop any stocks with missing data (NaN values)
    df = df.dropna()

    # Calculate the percentile rank based on percentage change
    df['RSP'] = round(df['Percent_Change'].rank(pct=True) * 100, 2)
    cols = ['Symbol', 'RSP']
    df = df[cols]
    # Sort by percentile rank (optional)
    df = df.sort_values(by='RSP', ascending=False).reset_index(drop=True)

    return df

In [6]:
# function to get stock technicals
def stock_prec_dev(stock_symbol):
    #stock_symbol = 'ULTRACEMCO.NS'
    short_window = 20
    mid_window = 50
    long_window = 200
    moving_avg = 'SMA'

    start = datetime.datetime(*map(int, start_date.split('-')))
    end = datetime.datetime(*map(int, end_date.split('-')))

    stock_df = yfin.Ticker(stock_symbol + '.NS').history(period='max', interval='1d')[map(str.title, ['open', 'close', 'low', 'high', 'volume'])]

    stock_df['Max'] = round(max(stock_df['Close']),2)
    stock_df = stock_df[(stock_df.index <= end_date) & (stock_df.index >= start_date)]
    stock_df['200_SMA'] = round(stock_df['Close'].rolling(window = 200, min_periods = 1).mean(),0)
    stock_df['Dev%_200'] = round((stock_df['Close'] - stock_df['200_SMA'])*100/stock_df['200_SMA'],2)
    stock_df.dropna(axis = 0, inplace = True) # remove any null rows

    stock_df['20_SMA'] = stock_df['Close'].rolling(window=20).mean()
    stock_df['50_SMA'] = stock_df['Close'].rolling(window=50).mean()
    stock_df['Symbol'] = stock_symbol

    stock_df['Close'] = round(stock_df['Close'],2)
    stock_df['Min'] = round(min(stock_df['Close']),2)
    stock_df['RSI_14'] = ta.momentum.RSIIndicator(close=stock_df['Close'], window=14).rsi()
    stock_df['RSI_14'] = round(stock_df['RSI_14'],0)
    stock_df['Prev_Close'] = stock_df['Close'].shift(1)
    stock_df.drop(['Open', 'Low', 'High', 'Volume'], axis=1, inplace=True)
    stock_df = stock_df.tail(1)

    max_SMA = max(stock_df['20_SMA'].item(), stock_df['50_SMA'].item(), stock_df['200_SMA'].item())
    min_SMA = min(stock_df['20_SMA'].item(), stock_df['50_SMA'].item(), stock_df['200_SMA'].item())
    ABS_Spread = max_SMA - min_SMA
    stock_df['Spread%'] = round((ABS_Spread / stock_df['200_SMA'].item()) * 100,2)

    return stock_df

# function to compute stock attributes
def get_common_features(stock_ids, df_mypf):

  df_prec_dev = pd.DataFrame()
  df_tmp = get_screener_features()
  df_rs = get_relative_strength(stock_ids)

  for stock_id in stock_ids:
      tmp = stock_prec_dev(stock_id)
      tmp = tmp.reset_index()
      df_prec_dev = pd.concat([df_prec_dev, tmp], ignore_index = True)
  df_prec_dev = pd.merge(df_prec_dev, df_mypf, on= 'Symbol')
  df_prec_dev = pd.merge(df_prec_dev, df_tmp, on= 'Symbol', how='left')
  df_prec_dev = pd.merge(df_prec_dev, df_rs, on= 'Symbol', how='left')
  #print(df_prec_dev.columns)
  df_prec_dev['Curr_PE'] = round(df_prec_dev['Close']/df_prec_dev['EPS'],1)
  df_prec_dev['Dev%_PE'] = round((df_prec_dev['Curr_PE'] - df_prec_dev['MedPE'])*100/df_prec_dev['MedPE'],2)
  df_prec_dev['Conviction'] = df_prec_dev['Conviction'] + '-' + df_prec_dev['CapType']
  return df_prec_dev

# function to arrange stock features
def arrange_features(df_stocks, common_cols, diff_cols):
  df_stocks_common = df_stocks[common_cols].drop_duplicates()
  df_stocks_diff = df_stocks[diff_cols]
  df_stocks_diff['Investment'] = df_stocks_diff['AvgCost'] * df_stocks_diff['Shares']
  df_stocks_diff = df_stocks_diff.groupby(['Symbol'])[['Shares', 'Investment']].aggregate(['sum']).reset_index()
  df_stocks_diff.columns = ['Symbol', 'Shares', 'Investment']
  df_stocks_diff['AvgCost'] = round(df_stocks_diff['Investment']/df_stocks_diff['Shares'],2)
  df_stocks = pd.merge(df_stocks_diff, df_stocks_common, on='Symbol')
  return df_stocks

# plot fact distribution across dimension
def plot_pie_chart(df, dimension, fact):
  # grouping the data by category and calculating the sum of fact for each type
  grouped_data = df.groupby(dimension)[fact].sum()

  # sorting the grouped data in descending order
  grouped_data = grouped_data.sort_values(ascending=False)

  # creating a pie chart
  grouped_data.plot.pie(autopct='%1.1f%%', startangle=90, figsize=(6, 6))

  # adding a title and displaying the plot
  plt.title(f'{dimension} {fact} Distribution')
  plt.ylabel('')  # To hide the y-label
  plt.show()

In [7]:
# function to get portfolio features

def get_portfolio_features(df_common_features):

  print_date_time()
  print('-------------------')

  #df_common_features["Target"] = df_common_features["Target"].fillna(df_common_features["Max"])
  df_common_features['NTT'] = np.where(df_common_features['Strategy']== 'NTT', df_common_features["Target"], df_common_features['Max'])
  df_common_features['LTT'] = np.where(df_common_features['Strategy']== 'BTT', df_common_features["Target"], df_common_features['Max'])
  df_common_features['BOL'] = df_common_features['Min']

  tmp_df = df_common_features[df_common_features['Symbol'].isin(mypf_df[mypf_df['InPortfolio'] != 'NA'].Symbol.values)]
  print('qualified stocks: '+str(len(tmp_df['Symbol'].unique())))
  tmp_df1 = tmp_df[tmp_df['LatestQtr'] == 1]
  print('with latest results: '+str(len(tmp_df1['Symbol'].unique())))
  tmp_df1 = tmp_df1[tmp_df1['StarStock'] == 1]
  print('still star stocks: '+str(len(tmp_df1['Symbol'].unique())))
  tmp_df['Investment'] = tmp_df['AvgCost'] * tmp_df['Shares']
  tmp_df['Current'] = round(tmp_df['Close'] * tmp_df['Shares'],0)
  tmp_df['Previous'] = tmp_df['Prev_Close'] * tmp_df['Shares']
  tmp_df['EstimatedST'] = tmp_df['NTT'] * tmp_df['Shares']
  tmp_df['EstimatedLT'] = tmp_df['LTT'] * tmp_df['Shares']
  tmp_df['Current P/L'] = round((tmp_df['Current'] - tmp_df['Investment']),0)
  tmp_df['Today P/L%'] = round((tmp_df['Current'] - tmp_df['Previous'])*100/tmp_df['Previous'],2)
  tmp_df['Current P/L%'] = round((tmp_df['Current'] - tmp_df['Investment'])*100/tmp_df['Investment'],2)
  tmp_df['EstimatedST P/L%'] = round((tmp_df['EstimatedST'] - tmp_df['Investment'])*100/tmp_df['Investment'],2)
  tmp_df['EstimatedLT P/L%'] = round((tmp_df['EstimatedLT'] - tmp_df['Investment'])*100/tmp_df['Investment'],2)
  tmp_df['NTT%'] = round((tmp_df['NTT'] - tmp_df['Close'])*100/tmp_df['Close'],2)
  tmp_df['LTT%'] = round((tmp_df['LTT'] - tmp_df['Close'])*100/tmp_df['Close'],2)
  tmp_df['Gained%'] = round((tmp_df['Close'] - tmp_df['BOL'])*100/tmp_df['BOL'],2)
  investment = round(sum(tmp_df['AvgCost']*tmp_df['Shares']),0)
  current = round(sum(tmp_df['Close']*tmp_df['Shares']),0)
  tmp_df['InitAlloc%'] = round(tmp_df['Investment']*100/investment,2)
  tmp_df['CurrAlloc%'] = round(tmp_df['Current']*100/current,2)
  tmp_df['FTT'] = tmp_df['LTT']
  tmp_df.loc[tmp_df['Strategy'] == 'NTT', 'FTT'] = tmp_df['NTT']
  tmp_df['FTT%'] = tmp_df['LTT%']
  tmp_df.loc[tmp_df['Strategy'] == 'NTT', 'FTT%'] = tmp_df['NTT%']
  tmp_df['FTT Amt'] = round(tmp_df['FTT%'] * tmp_df['Current']/100,0)
  tmp_df['OTT%'] = round((tmp_df['FTT'] - tmp_df['AvgCost'])*100/tmp_df['AvgCost'],2)
  tmp_df['RRR Ind'] = round(tmp_df['Current P/L']/tmp_df['FTT Amt'],2)
  tmp_df['Risk Ind'] = round(tmp_df['Current P/L%']*tmp_df['CurrAlloc%'],0)

  return tmp_df

# function to print portfolio features
def print_portfolio_stats(df_portfolio_features, myinvmt_df):
  from pyxirr import xirr

  total_booked_amt, reserve_amt, cy_booked_amt, py_booked_amt = get_amt()

  dates = myinvmt_df['Date'].values
  dates = np.append(dates, datetime.date.today().strftime('%d-%b-%y'))
  investment = myinvmt_df['Investment'].values
  dates= pd.to_datetime(dates)

  current = round(sum(df_portfolio_features['Close']*df_portfolio_features['Shares']),0) + reserve_amt
  investment_xirr = np.append(investment, current)
  cagr = round(xirr(pd.DataFrame({"dates": dates, "amounts": investment_xirr}))*100,2)

  investment = -sum(investment)
  invested = round(sum(df_portfolio_features['AvgCost']*df_portfolio_features['Shares']),0) + reserve_amt
  previous = round(sum(df_portfolio_features['Prev_Close']*df_portfolio_features['Shares']),0) + reserve_amt
  cy_invested = investment + py_booked_amt

  today_pnl_amount = current-previous
  today_pnl_percentage = round((current-previous)*100/previous,2)

  curr_pnl_amount = current-invested
  curr_pnl_percentage = round((curr_pnl_amount)*100/(cy_invested),2)

  cy_pnl_amount = cy_booked_amt + curr_pnl_amount
  cy_pnl_percentage = round((cy_pnl_amount)*100/cy_invested,2)

  overall_pnl_amount = total_booked_amt + curr_pnl_amount
  overall_pnl_percentage = round((overall_pnl_amount)*100/investment,2)

  estimate_st = round(sum(df_portfolio_features['FTT']*df_portfolio_features['Shares']),0)  + reserve_amt
  est_st_pnl_amount = estimate_st-current
  est_st_pnl_percentage = round((est_st_pnl_amount)*100/current,2)

  estimate_lt = round(sum(df_portfolio_features['LTT']*df_portfolio_features['Shares']),0)  + reserve_amt
  est_lt_pnl_amount = estimate_lt-current
  est_lt_pnl_percentage = round((est_lt_pnl_amount)*100/current,2)

  total_profit = round(sum(df_portfolio_features[df_portfolio_features['Current P/L%'] > 0]['Current']) - sum(df_portfolio_features[df_portfolio_features['Current P/L%'] > 0]['Investment']),0)
  total_loss = round(sum(df_portfolio_features[df_portfolio_features['Current P/L%'] < 0]['Current']) - sum(df_portfolio_features[df_portfolio_features['Current P/L%'] < 0]['Investment']),0)

  cy_booked_percentage = round((cy_booked_amt)*100/current,2)
  py_booked_percentage = round((py_booked_amt)*100/investment,2)
  total_booked_percentage = round((total_booked_amt)*100/investment,2)

  print('-------------------')
  print('Initial Investment: ', format_amt(investment))
  print('CY Investment: ', format_amt(cy_invested))
  print('Reserve: ', format_amt(reserve_amt))
  print('Current: ',  format_amt(current))
  print('-------------------')
  print('Today PnL: '+ '{} ({}%)'.format(format_amt(today_pnl_amount), today_pnl_percentage))
  print('Current PnL: '+ '{} ({}%)'.format(format_amt(curr_pnl_amount), curr_pnl_percentage))
  print('CY Booked + Current PnL: '+ '{} ({}%)'.format(format_amt(cy_pnl_amount), cy_pnl_percentage))
  print('-------------------')
  print('Total profit: ', format_amt(total_profit))
  print('Total loss: ', format_amt(total_loss))
  print('-------------------')
  print('Total Booked + Current PnL: '+ '{} ({}%)'.format(format_amt(overall_pnl_amount), overall_pnl_percentage))
  print('Total Booked PnL: '+ '{} ({}%)'.format(format_amt(total_booked_amt), total_booked_percentage))
  print('Curr Year Booked PnL: '+ '{} ({}%)'.format(format_amt(cy_booked_amt), cy_booked_percentage))
  print('Prev Year Booked PnL: '+ '{} ({}%)'.format(format_amt(py_booked_amt), py_booked_percentage))
  print('===================')
  print('Est FTT: ',  format_amt(estimate_st))
  print('Est FTT PnL: '+ '{} ({}%)'.format(format_amt(est_st_pnl_amount), est_st_pnl_percentage))

  print('===================')
  print('Deployed: ', format_amt(investment))

  print('Current: ', format_amt(current))

  print('CAGR/XIRR %: '+'{}%'.format(cagr))

In [8]:
# get start and end date
start_date, end_date = get_start_end_date()

# get portfolio and prospects data
mypfs_df = get_mypfs_df()
mypps_df = get_mypps_df()
myinvmt_df = get_myinvmt_df()

# merge above datasets
mypf_df = pd.merge(mypfs_df, mypps_df, on="Symbol")

# seggregate dm and sv portfolio
dm_pf = mypf_df[mypf_df['InPortfolio'] == 'DM']
sv_pf = mypf_df[mypf_df['InPortfolio'] == 'SV']

# build portfolio stock dataframe
dm_stocks = get_stock_ids(dm_pf)
sv_stocks = get_stock_ids(sv_pf)
df_stocks = pd.concat([dm_pf,sv_pf], ignore_index = True)

# arrange common and diff stock features
common_cols = ['Symbol', 'Target', 'Criteria', 'Strategy', 'CumlRnk', 'LatestQtr', 'StarStock', 'Conviction', 'Category', 'InFolio', 'XIRR', 'MBQ']
diff_cols = ['Symbol', 'AvgCost', 'Shares']
df_stocks = arrange_features(df_stocks, common_cols, diff_cols)

# get common features
stock_ids = df_stocks['Symbol'].values
df_common_features = get_common_features(stock_ids, df_stocks)

df_common_features.reset_index(drop=True, inplace=True)
df_common_features.drop(['Date'], axis=1, inplace=True)
# get and print portfolio features
df_portfolio_features = get_portfolio_features(df_common_features)

print_portfolio_stats(df_portfolio_features, myinvmt_df)

df = df_portfolio_features
#plot_pie_chart(df, 'CapType', 'Current')
list_ox40n = list(df[df['MBQ'].str.contains('OX40N', na=False)]['Symbol'].values)

Run date time (IST): 2026-04-10 12:23:15
-------------------
qualified stocks: 86
with latest results: 26
still star stocks: 16
-------------------
Initial Investment:  1.36 C
CY Investment:  1.62 C
Reserve:  1.61 K
Current:  1.38 C
-------------------
Today PnL: 1.73 L (1.27%)
Current PnL: -39.00 L (-24.01%)
CY Booked + Current PnL: -23.11 L (-14.23%)
-------------------
Total profit:  1.46 L
Total loss:  -40.47 L
-------------------
Total Booked + Current PnL: 3.87 L (2.85%)
Total Booked PnL: 42.87 L (31.64%)
Curr Year Booked PnL: 15.89 L (11.5%)
Prev Year Booked PnL: 26.98 L (19.91%)
===================
Est FTT:  2.48 C
Est FTT PnL: 1.10 C (79.47%)
===================
Deployed:  1.36 C
Current:  1.38 C
CAGR/XIRR %: 0.93%

In [9]:
# top 5 near their targets
cols = ['Symbol', 'Today P/L%', 'Current P/L%', 'FTT%', 'OTT%', 'FTT Amt', 'Current P/L', 'Current', 'FTT', 'Dev%_PE', 'RSI_14','Conviction', 'Spread%',  'CumlRnk', 'RRR Ind', 'CurrAlloc%', 'Gained%', 'Criteria', 'Strategy', 'Category']
df_tmp = df_portfolio_features[~df_portfolio_features['Symbol'].isin(['ENRIN','BLUSPRING','DIGITIDE'])]
df_tmp = df_tmp.sort_values(by = 'FTT Amt', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
5,ANGELONE,1.40,17.11,6.04,24.18,21574.0,52188.0,357188.0,303.00,-82.85,73.0,X-SC,5.07,97.0,2.42,2.59,36.65,X40N,NTT,FINANCE
50,MASFIN,-0.92,-5.91,29.20,21.57,26919.0,-5790.0,92190.0,397.04,-18.70,52.0,H-SC,4.81,167.0,-0.22,0.67,19.13,XR,ATH,FINANCE
77,TTKPRESTIG,2.15,-37.49,60.12,0.09,37874.0,-37779.0,62998.0,770.00,46.21,49.0,M-SC,21.76,250.0,-1.00,0.46,12.18,OX40N,NTT,DURABLES
67,SONACOMS,5.42,-4.61,45.81,39.09,44204.0,-4664.0,96495.0,804.02,-24.39,63.0,M-MC,8.10,193.0,-0.11,0.70,36.51,AR,ATH,AUTO
37,ICICIGI,1.33,-5.07,25.71,19.34,48839.0,-10146.0,189963.0,2252.93,-20.08,50.0,X-MC,7.44,66.0,-0.21,1.38,6.10,X40,ATH,INSURANCE

In [10]:
# top 5 today
df_tmp = df_portfolio_features.sort_values(by = 'Today P/L%', ascending=False)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
22,DEN,5.90,-45.27,159.61,42.07,73778.0,-38240.0,46224.0,75.00,63.21,65.0,M-SC,21.62,235.0,-0.52,0.33,25.72,AR,NTT,ENTERTAINMENT
67,SONACOMS,5.42,-4.61,45.81,39.09,44204.0,-4664.0,96495.0,804.02,-24.39,63.0,M-MC,8.10,193.0,-0.11,0.70,36.51,AR,ATH,AUTO
55,RAJESHEXPO,4.99,-78.80,371.94,0.07,108182.0,-108091.0,29086.0,518.00,965.66,51.0,L-SC,44.12,268.0,-1.00,0.21,36.55,OX40N,NTT,JEWELLERY
31,HATHWAY,4.49,-38.30,180.86,73.29,121321.0,-41640.0,67080.0,31.40,678.99,65.0,H-SC,23.81,171.0,-0.34,0.49,26.04,XR,NTT,ENTERTAINMENT
13,BERGEPAINT,4.30,-16.39,49.88,25.32,107495.0,-42241.0,215508.0,680.00,-20.92,62.0,X-MC,19.22,68.0,-0.39,1.56,12.16,XY24,NTT,PAINTS

In [11]:
# bottom 5 today
df_tmp = df_portfolio_features.sort_values(by = 'Today P/L%', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
43,INFY,-3.60,-12.61,53.62,34.24,146612.0,-39460.0,273428.0,1972.00,-31.06,45.0,X-LC,14.31,3.0,-0.27,1.98,5.15,X40,NTT,IT
73,TCS,-3.09,-26.34,71.84,26.57,245135.0,-122049.0,341224.0,4311.59,-37.73,49.0,X-LC,18.16,2.0,-0.50,2.47,6.49,X40,ATH,IT
33,HCLTECH,-2.53,-7.34,33.65,23.83,75432.0,-17759.0,224165.0,1908.19,-2.81,54.0,X-LC,9.79,8.0,-0.24,1.62,8.84,X40,ATH,IT
80,VALIANTORG,-1.32,-45.03,216.82,74.15,194986.0,-73675.0,89930.0,838.00,-261.57,60.0,H-SC,22.82,145.0,-0.38,0.65,33.83,XR,NTT,CHEMICALS
24,DMART,-1.26,4.81,23.66,29.60,61895.0,12000.0,261600.0,5391.45,-11.66,64.0,X-LC,4.72,14.0,0.19,1.89,19.57,X40N,ATH,FMCG

In [12]:
# top 5 to exit based on CumlRnk
df_tmp = df_portfolio_features[~df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])]
df_tmp = df_tmp[(df_tmp['Current P/L%'] > -1) & (df_tmp['Current P/L%'] < 1)].sort_values(by = 'CumlRnk', ascending=False)
df_tmp[cols].head()

Empty DataFrame
Columns: [Symbol, Today P/L%, Current P/L%, FTT%, OTT%, FTT Amt, Current P/L, Current, FTT, Dev%_PE, RSI_14, Conviction, Spread%, CumlRnk, RRR Ind, CurrAlloc%, Gained%, Criteria, Strategy, Category]
Index: []

In [13]:
# OX40N stocks to exit
df_tmp = df_portfolio_features[(df_portfolio_features['Symbol'].isin(list_ox40n))].sort_values(by = 'Current P/L%', ascending=False)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
26,FINCABLES,1.25,8.16,92.23,107.91,147281.0,12045.0,159689.0,1641.55,-2.59,54.0,M-SC,1.74,220.0,0.08,1.16,20.14,OX40N,ATH,CABLES
66,SIS,0.20,-30.65,74.86,21.26,57640.0,-34035.0,76997.0,528.00,1807.77,58.0,H-SC,14.33,168.0,-0.59,0.56,14.48,OX40N,NTT,MISC
18,CERA,2.59,-32.48,83.49,23.89,99161.0,-57133.0,118770.0,9475.00,-34.84,64.0,H-SC,17.37,153.0,-0.58,0.86,14.14,OX40N,NTT,CERAMICS
72,TATAELXSI,-0.63,-36.24,107.08,32.03,90007.0,-47779.0,84056.0,9161.00,-20.19,52.0,H-SC,20.85,158.0,-0.53,0.61,11.25,OX40N,NTT,IT
48,KANSAINER,2.27,-36.75,79.41,13.47,135441.0,-99108.0,170559.0,340.00,-45.60,56.0,H-SC,23.35,162.0,-0.73,1.24,19.14,XY24,NTT,PAINTS

In [14]:
# top 5 to book for rotation
df_tmp = df_portfolio_features[(df_portfolio_features['Current P/L%'] > 20) ].sort_values(by = 'CumlRnk', ascending=False)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
1,ABB,3.76,25.92,15.61,45.57,51423.0,67805.0,329424.0,7934.0,-19.13,71.0,H-MC,15.34,125.0,1.32,2.39,46.29,AR,NTT,ELECTRICAL

In [15]:
# top 5 to monitor for exit
df_tmp = df_portfolio_features[~df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])]
df_tmp = df_tmp[(df_tmp['Current P/L%'] > 0) ].sort_values(by = 'Dev%_PE', ascending=False)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
26,FINCABLES,1.25,8.16,92.23,107.91,147281.0,12045.0,159689.0,1641.55,-2.59,54.0,M-SC,1.74,220.0,0.08,1.16,20.14,OX40N,ATH,CABLES
1,ABB,3.76,25.92,15.61,45.57,51423.0,67805.0,329424.0,7934.00,-19.13,71.0,H-MC,15.34,125.0,1.32,2.39,46.29,AR,NTT,ELECTRICAL

In [16]:
# top 5 to book for rotation from weak conviction
df_tmp = df_portfolio_features[~df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])]
df_tmp = df_tmp[~df_tmp['Criteria'].isin(['XY25','XY24','X40', 'X40N'])].sort_values(by = 'RRR Ind', ascending=False)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
1,ABB,3.76,25.92,15.61,45.57,51423.0,67805.0,329424.0,7934.00,-19.13,71.0,H-MC,15.34,125.0,1.32,2.39,46.29,AR,NTT,ELECTRICAL
26,FINCABLES,1.25,8.16,92.23,107.91,147281.0,12045.0,159689.0,1641.55,-2.59,54.0,M-SC,1.74,220.0,0.08,1.16,20.14,OX40N,ATH,CABLES
40,INDIAMART,0.28,-9.50,128.42,106.72,143340.0,-11718.0,111618.0,4810.62,-59.18,54.0,H-SC,13.03,140.0,-0.08,0.81,7.24,AR,ATH,MISC
85,ZYDUSLIFE,0.97,-3.93,41.18,35.63,82908.0,-8243.0,201331.0,1286.17,-16.22,56.0,H-MC,6.04,120.0,-0.10,1.46,12.08,AR,ATH,PHARMA
67,SONACOMS,5.42,-4.61,45.81,39.09,44204.0,-4664.0,96495.0,804.02,-24.39,63.0,M-MC,8.10,193.0,-0.11,0.70,36.51,AR,ATH,AUTO

In [17]:
# top 5 to accumulate based on lowest RSI_14
df_tmp = df_portfolio_features[df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])].sort_values(by = 'RSI_14', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
53,PGHH,0.50,-27.15,81.21,32.01,126324.0,-57968.0,155552.0,17616.87,-50.75,38.0,X-MC,20.91,57.0,-0.46,1.13,6.39,X40,ATH,FMCG
21,DABUR,0.48,-15.65,70.36,43.70,147230.0,-38815.0,209253.0,735.00,-23.53,42.0,X-MC,13.60,70.0,-0.26,1.52,5.12,XY24,BTT,FMCG
38,ICICIPRULI,0.74,-9.66,44.70,30.73,79557.0,-19025.0,177980.0,790.00,-33.87,43.0,X-MC,11.59,78.0,-0.24,1.29,8.45,X40,ATH,INSURANCE
2,ABBOTINDIA,0.19,-13.35,36.26,18.07,56196.0,-23875.0,154980.0,35195.00,-26.29,43.0,X-MC,11.34,58.0,-0.42,1.12,1.35,X40,ATH,PHARMA
78,UNITDSPR,0.96,-7.32,30.30,20.77,65755.0,-17132.0,217012.0,1644.00,-17.87,44.0,X-MC,5.38,64.0,-0.26,1.57,3.52,X40N,NTT,BREWERIES

In [18]:
# top 5 to accumulate based on Spread and CumlRnk
df_tmp = df_portfolio_features[df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])]
df_tmp = df_tmp[(df_tmp['CumlRnk'] < 100)].sort_values(by = 'Spread%', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
65,SIEMENS,4.16,-9.81,39.17,25.51,65739.0,-18265.0,167830.0,4671.50,40.86,62.0,H-LC,1.29,51.0,-0.28,1.22,23.05,AR,ATH,ELECTRICAL
24,DMART,-1.26,4.81,23.66,29.60,61895.0,12000.0,261600.0,5391.45,-11.66,64.0,X-LC,4.72,14.0,0.19,1.89,19.57,X40N,ATH,FMCG
59,RELIANCE,1.37,-13.46,44.79,25.30,77898.0,-27045.0,173918.0,1952.00,-15.80,45.0,X-LC,4.91,21.0,-0.35,1.26,11.05,XY25,BTT,REFINERIES
5,ANGELONE,1.40,17.11,6.04,24.18,21574.0,52188.0,357188.0,303.00,-82.85,73.0,X-SC,5.07,97.0,2.42,2.59,36.65,X40N,NTT,FINANCE
78,UNITDSPR,0.96,-7.32,30.30,20.77,65755.0,-17132.0,217012.0,1644.00,-17.87,44.0,X-MC,5.38,64.0,-0.26,1.57,3.52,X40N,NTT,BREWERIES

In [19]:
# top 5 to accumulate based on lowest Gained%
df_tmp = df_portfolio_features[df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])].sort_values(by = 'Gained%', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
2,ABBOTINDIA,0.19,-13.35,36.26,18.07,56196.0,-23875.0,154980.0,35195.0,-26.29,43.0,X-MC,11.34,58.0,-0.42,1.12,1.35,X40,ATH,PHARMA
78,UNITDSPR,0.96,-7.32,30.30,20.77,65755.0,-17132.0,217012.0,1644.0,-17.87,44.0,X-MC,5.38,64.0,-0.26,1.57,3.52,X40N,NTT,BREWERIES
35,HINDUNILVR,0.97,-16.21,35.66,13.67,76808.0,-41673.0,215390.0,2922.0,-37.77,50.0,X-LC,11.87,9.0,-0.54,1.56,4.96,XY25,NTT,FMCG
21,DABUR,0.48,-15.65,70.36,43.70,147230.0,-38815.0,209253.0,735.0,-23.53,42.0,X-MC,13.60,70.0,-0.26,1.52,5.12,XY24,BTT,FMCG
43,INFY,-3.60,-12.61,53.62,34.24,146612.0,-39460.0,273428.0,1972.0,-31.06,45.0,X-LC,14.31,3.0,-0.27,1.98,5.15,X40,NTT,IT

In [20]:
# top 5 to accumulate based on lowest CurrAlloc%
df_tmp = df_portfolio_features[df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])].sort_values(by = 'CurrAlloc%', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
58,RELAXO,2.99,-62.50,306.16,52.31,166655.0,-90726.0,54434.0,1176.00,-60.12,50.0,X-SC,33.12,92.0,-0.54,0.39,21.71,X40N,NTT,FOOTWEAR
12,BATAINDIA,1.48,-54.10,194.55,35.20,114907.0,-69607.0,59063.0,2096.00,-22.60,53.0,X-SC,34.14,91.0,-0.61,0.43,17.14,X40,NTT,FOOTWEAR
54,QUESS,2.98,-20.23,117.99,73.90,100517.0,-21602.0,85191.0,424.00,-57.02,60.0,X-SC,21.89,80.0,-0.21,0.62,14.60,XY24,NTT,MISC
36,HONAUT,1.82,-26.71,106.46,51.31,150455.0,-51513.0,141325.0,58357.33,-39.02,47.0,X-SC,19.16,90.0,-0.34,1.02,7.37,X40N,ATH,ELECTRICAL
2,ABBOTINDIA,0.19,-13.35,36.26,18.07,56196.0,-23875.0,154980.0,35195.00,-26.29,43.0,X-MC,11.34,58.0,-0.42,1.12,1.35,X40,ATH,PHARMA

In [21]:
# top 5 to accumulate based on CumlRnk
df_tmp = df_portfolio_features.sort_values(by = 'CumlRnk', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
45,ITC,0.50,-19.79,48.44,19.06,132160.0,-67334.0,272832.0,452.00,-55.92,52.0,X-LC,19.66,1.0,-0.51,1.98,5.84,X40,NTT,FMCG
73,TCS,-3.09,-26.34,71.84,26.57,245135.0,-122049.0,341224.0,4311.59,-37.73,49.0,X-LC,18.16,2.0,-0.50,2.47,6.49,X40,ATH,IT
43,INFY,-3.60,-12.61,53.62,34.24,146612.0,-39460.0,273428.0,1972.00,-31.06,45.0,X-LC,14.31,3.0,-0.27,1.98,5.15,X40,NTT,IT
75,TMPV,1.74,-22.82,76.97,36.58,211383.0,-81211.0,274630.0,600.00,-83.62,56.0,X-LC,12.48,4.0,-0.38,1.99,14.47,XY24,NTT,AUTO
33,HCLTECH,-2.53,-7.34,33.65,23.83,75432.0,-17759.0,224165.0,1908.19,-2.81,54.0,X-LC,9.79,8.0,-0.24,1.62,8.84,X40,ATH,IT

In [22]:
# top 5 for average up
df_tmp = df_portfolio_features[(df_portfolio_features['Dev%_200'] > 5)].sort_values(by = 'CurrAlloc%', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
67,SONACOMS,5.42,-4.61,45.81,39.09,44204.0,-4664.0,96495.0,804.02,-24.39,63.0,M-MC,8.10,193.0,-0.11,0.70,36.51,AR,ATH,AUTO
65,SIEMENS,4.16,-9.81,39.17,25.51,65739.0,-18265.0,167830.0,4671.50,40.86,62.0,H-LC,1.29,51.0,-0.28,1.22,23.05,AR,ATH,ELECTRICAL
62,SATIN,3.11,-10.78,70.19,51.83,173012.0,-29793.0,246491.0,274.00,-19.84,67.0,H-SC,3.05,159.0,-0.17,1.78,20.08,XY24,NTT,FINANCE
24,DMART,-1.26,4.81,23.66,29.60,61895.0,12000.0,261600.0,5391.45,-11.66,64.0,X-LC,4.72,14.0,0.19,1.89,19.57,X40N,ATH,FMCG
1,ABB,3.76,25.92,15.61,45.57,51423.0,67805.0,329424.0,7934.00,-19.13,71.0,H-MC,15.34,125.0,1.32,2.39,46.29,AR,NTT,ELECTRICAL

In [23]:
# top 5 RSP
df_tmp = df_portfolio_features.sort_values(by = 'RSP', ascending=False)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
5,ANGELONE,1.40,17.11,6.04,24.18,21574.0,52188.0,357188.0,303.00,-82.85,73.0,X-SC,5.07,97.0,2.42,2.59,36.65,X40N,NTT,FINANCE
80,VALIANTORG,-1.32,-45.03,216.82,74.15,194986.0,-73675.0,89930.0,838.00,-261.57,60.0,H-SC,22.82,145.0,-0.38,0.65,33.83,XR,NTT,CHEMICALS
52,PAGEIND,0.79,-5.49,41.90,34.11,106277.0,-14734.0,253645.0,51418.64,-32.17,72.0,X-MC,17.20,55.0,-0.14,1.84,19.98,X40,ATH,APPARELS
18,CERA,2.59,-32.48,83.49,23.89,99161.0,-57133.0,118770.0,9475.00,-34.84,64.0,H-SC,17.37,153.0,-0.58,0.86,14.14,OX40N,NTT,CERAMICS
31,HATHWAY,4.49,-38.30,180.86,73.29,121321.0,-41640.0,67080.0,31.40,678.99,65.0,H-SC,23.81,171.0,-0.34,0.49,26.04,XR,NTT,ENTERTAINMENT

In [24]:
# Top N allocation
df_tmp = df_portfolio_features.sort_values(by = 'CurrAlloc%', ascending=False)
top_n_values = [10, 25, 50]

sum_df = pd.DataFrame({
    'Top_N': top_n_values,
    'Sum_Alloc%': [df_tmp['CurrAlloc%'].head(n).sum() for n in top_n_values]
})

sum_df

   Top_N  Sum_Alloc%
0     10       21.09
1     25       46.01
2     50       77.81

In [25]:
# market-cap-wise allocation
df_tmp = df_portfolio_features[cols]
df_tmp.groupby(df_tmp['Conviction'].str[-2:])['CurrAlloc%'].sum().sort_values(ascending=False)

Conviction
SC    45.18
MC    29.54
LC    25.34
Name: CurrAlloc%, dtype: float64

In [26]:
# criteria-wise allocation
df_portfolio_features.groupby('Criteria')['CurrAlloc%'].sum().sort_values(ascending=False)

Criteria
XY24     27.24
X40      24.88
X40N     15.58
AR        9.38
XR        8.38
XY25      7.02
OX40N     6.78
SR        0.80
Name: CurrAlloc%, dtype: float64

In [27]:
# conviction-wise allocation
df_portfolio_features.groupby('Conviction')['CurrAlloc%'].sum().sort_values(ascending=False)

Conviction
X-LC    23.10
H-SC    22.05
X-MC    21.98
X-SC    12.47
M-SC    10.09
H-MC     5.13
M-MC     2.09
H-LC     1.22
M-LC     1.02
L-SC     0.57
L-MC     0.34
Name: CurrAlloc%, dtype: float64

In [28]:
# sector-wise stats
df_tmp = df_portfolio_features.groupby('Category')[['CurrAlloc%', 'Current', 'Current P/L', 'FTT Amt']].sum().sort_values(by=['Current', 'Current P/L'], ascending=False)
df_tmp['Current P/L%'] = round(df_tmp['Current P/L'] * 100 / df_tmp['Current'], 2)
df_tmp['FTT%'] = round(df_tmp['FTT Amt'] * 100 / df_tmp['Current'], 2)
cols = ['CurrAlloc%', 'Current P/L%', 'FTT%']
df_tmp[cols].sort_values(by=['CurrAlloc%'], ascending=False)

               CurrAlloc%  Current P/L%    FTT%
Category
FMCG                14.78        -22.47   65.92
FINANCE             13.53        -14.95   61.79
IT                  11.73        -39.13  109.93
MISC                 7.16        -35.79   94.77
ELECTRICAL           6.58         -6.73   47.60
PAINTS               5.28        -35.27   58.76
BANKS                4.61        -20.85   82.19
INSURANCE            4.53         -8.63   45.81
PHARMA               3.97         -7.18   40.92
AUTO                 3.76        -26.15   76.20
AC                   1.96        -18.15   50.18
HEALTHCARE           1.94        -32.92   67.61
TRAVEL               1.85        -75.42  163.26
APPARELS             1.84         -5.81   41.90
FOOTWEAR             1.81        -76.80  147.69
DURABLES             1.73        -61.92  101.31
BREWERIES            1.57         -7.89   30.30
REALTY               1.42        -12.89   31.44
CERAMICS             1.36        -64.04  113.88
REFINERIES           1.26        -15.55   44.79
CEMENT               1.23        -57.46  175.26
ENGINEERING          1.18        -48.86  116.94
CABLES               1.16          7.54   92.23
CHEMICALS            1.09        -76.23  220.00
JEWELLERY            1.09       -113.36  187.49
ENTERTAINMENT        0.82        -70.50  172.19
TEXTILES             0.46        -46.76   88.61
HOTELS               0.36       -126.59  206.51

In [29]:
# money to be made criteria-wise
df_portfolio_features.groupby('Criteria')['FTT Amt'].agg(['sum', 'count']).sort_values(by='sum', ascending=False)

                sum  count
Criteria
XY24      3836594.0     21
X40       1741061.0     16
XR        1335573.0     12
AR        1278606.0     10
X40N      1145559.0     10
OX40N      856955.0     10
XY25       471875.0      5
SR         309602.0      2

In [30]:
# money to be made conviction-wise
df_portfolio_features.groupby('Conviction')['FTT Amt'].agg(['sum', 'count']).sort_values(by='sum', ascending=False)

                  sum  count
Conviction
H-SC        3751424.0     24
X-MC        1700517.0     15
X-LC        1584734.0     13
M-SC        1526110.0     14
X-SC        1459820.0     10
H-MC         371288.0      3
L-SC         211668.0      2
M-LC         151509.0      1
M-MC          97670.0      2
H-LC          65739.0      1
L-MC          55346.0      1

In [31]:
# money to be made criteria and conviction-wise
df_portfolio_features.groupby(['Conviction', 'Criteria'])['FTT Amt'].agg(['sum', 'count']).sort_values(by='sum', ascending=False)

                           sum  count
Conviction Criteria
H-SC       XY24      1276610.0      6
           AR         960554.0      5
M-SC       XY24       882985.0      6
X-LC       X40        861645.0      7
H-SC       XR         837289.0      7
X-SC       XY24       831556.0      4
X-MC       X40        666784.0      7
           X40N       515305.0      4
X-SC       X40N       415632.0      4
M-SC       OX40N      381404.0      5
H-SC       OX40N      367369.0      4
X-LC       XY24       353761.0      2
H-SC       SR         309602.0      2
X-MC       XY25       263703.0      2
           XY24       254725.0      2
H-MC       XY24       236957.0      1
X-LC       X40N       214622.0      2
X-SC       X40        212632.0      2
M-SC       XR         187943.0      2
X-LC       XY25       154706.0      2
M-LC       XR         151509.0      1
H-MC       AR         134331.0      2
L-SC       OX40N      108182.0      1
           XR         103486.0      1
M-SC       AR          73778.0      1
H-LC       AR          65739.0      1
L-MC       XR          55346.0      1
M-MC       XY25        53466.0      1
           AR          44204.0      1

In [32]:
# notebook execution time

end_time = time.time()
execution_time = round(end_time - start_time, 0)
print(f"Notebook execution time: {execution_time} seconds")

Notebook execution time: 25.0 seconds