<a href="https://colab.research.google.com/github/ankit-rathi/Quantvesting_v2/blob/main/myStocks_Portfolio_Analysis.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
'''
!pip install pandas==2.2.2 -qq
!pip install pyxirr -qq
!pip install ta -qq
!pip install yfinance==0.2.59 -qq
'''

'\n!pip install pandas==2.2.2 -qq\n!pip install pyxirr -qq\n!pip install ta -qq\n!pip install yfinance==0.2.59 -qq\n'

In [2]:
# import libraries

import numpy as np
import pandas as pd
import datetime
import warnings
warnings.filterwarnings('ignore')
import yfinance as yfin
import ta
import matplotlib.pyplot as plt
import requests

In [3]:
# notebook start time
import time
import datetime
import pytz

start_time = time.time()

# function to print date timestamp
def print_date_time():
  tz_NY = pytz.timezone('Asia/Kolkata')
  datetime_NY = datetime.datetime.now(tz_NY)
  print("Run date time (IST):", datetime_NY.strftime("%Y-%m-%d %H:%M:%S"))

In [4]:
# function to get booked and reserved amount
def get_amt():
  # fetch the JSON data from the URL
  url = "https://raw.githubusercontent.com/ankit-rathi/Tradevesting_v1/main/data/myPortfolioAmts.json"
  response = requests.get(url)
  pf_amts = response.json()  # parse the JSON data

  # extract values from the JSON
  py_booked_amt_dm = pf_amts["py_booked_amt_dm"]
  py_booked_amt_sv = pf_amts["py_booked_amt_sv"]
  cy_booked_amt_dm = pf_amts["cy_booked_amt_dm"]
  cy_booked_amt_sv = pf_amts["cy_booked_amt_sv"]
  reserve_amt_dm = pf_amts["reserve_amt_dm"]
  reserve_amt_sv = pf_amts["reserve_amt_sv"]

  # perform calculations
  py_booked_amt = py_booked_amt_dm + py_booked_amt_sv
  cy_booked_amt = cy_booked_amt_dm + cy_booked_amt_sv
  reserve_amt = reserve_amt_dm + reserve_amt_sv
  total_booked_amt = py_booked_amt + cy_booked_amt

  return total_booked_amt, reserve_amt, cy_booked_amt, py_booked_amt

gen_output = 0

In [5]:
# function to format the amount
def format_amt(number):
    abs_number = abs(number)

    if abs_number >= 1_00_00_000:  # Crores
        formatted_amt = f"{number / 1_00_00_000:.2f} C"
    elif abs_number >= 1_00_000:  # Lakhs
        formatted_amt = f"{number / 1_00_000:.2f} L"
    elif abs_number >= 1_000:  # Thousands
        formatted_amt = f"{number / 1_000:.2f} K"
    else:
        formatted_amt = f"{number:.2f}"

    return formatted_amt

# function to set start and end date
def get_start_end_date():
  start_date = (datetime.date.today() + datetime.timedelta(days=-365)).strftime('%Y-%m-%d')
  end_date = (datetime.date.today() + datetime.timedelta(days=1)).strftime('%Y-%m-%d')
  return start_date, end_date

# function to fetch my portfolio csv
def get_mypfs_df():
  mypfs_df = pd.read_csv('https://raw.githubusercontent.com/ankit-rathi/Tradevesting_v1/main/data/myPortfolioStocks.csv')
  return mypfs_df

# function to fetch my prospects csv
def get_mypps_df():
  mypps_df = pd.read_csv('https://raw.githubusercontent.com/ankit-rathi/Tradevesting_v1/main/data/myProspectsScrips.csv')
  return mypps_df

# function to fetch screener data
def get_myscreen_df():
  myscreen_df = pd.read_csv('https://raw.githubusercontent.com/ankit-rathi/Tradevesting_v1/main/data/myScreenerDB.csv')
  return myscreen_df

# function to fetch momentum data
def get_myinvmt_df():
  myinvmt_df = pd.read_csv('https://raw.githubusercontent.com/ankit-rathi/Tradevesting_v1/main/data/myInvestments.csv')
  return myinvmt_df

# function to get the stock ids
def get_stock_ids(df_pf):
  stock_n100 = df_pf['Symbol'].unique()

  exclude = ['CADILAHC','MMTC', 'MASFIN']

  stock_ids = df_pf[~df_pf['Symbol'].isin(exclude) ]['Symbol'].unique()

  #mypf = mypf[mypf.Forecast.notnull()]
  #stock_ids = mypf['Symbol'].unique()

  #stock_ids.sort()
  return stock_ids

# get features from screener data
def get_screener_features():
  myscreen_df = get_myscreen_df()
  cols = ['Symbol', 'EPS', 'MedPE', 'ROCE%', 'ROE%', 'CapType']
  return myscreen_df[cols]

# get relative strength
def get_relative_strength(stock_list):

    # Dictionary to store stock tickers and their corresponding percentage price change
    stock_changes = {}

    # Loop through each stock and fetch its price data
    for stock in stock_list:
        try:
            # Download the stock data for the given date range
            stock_data = yfin.Ticker(stock + '.NS').history(period='1mo', interval='1d')[map(str.title, ['open', 'close', 'low', 'high', 'volume'])]

            # Calculate the percentage change for the stock
            if len(stock_data) > 0:
                start_price = stock_data['Close'].iloc[0]
                end_price = stock_data['Close'].iloc[-1]
                percent_change = round(((end_price - start_price) / start_price) * 100, 2)
                stock_changes[stock] = percent_change
            else:
                stock_changes[stock] = np.nan  # If no data is available, set to NaN

        except Exception as e:
            print(f"Error fetching data for {stock}: {e}")
            stock_changes[stock] = np.nan

    # Create a DataFrame with stock tickers and their percentage changes
    df = pd.DataFrame(list(stock_changes.items()), columns=['Symbol', 'Percent_Change'])

    # Drop any stocks with missing data (NaN values)
    df = df.dropna()

    # Calculate the percentile rank based on percentage change
    df['RSP'] = round(df['Percent_Change'].rank(pct=True) * 100, 2)
    cols = ['Symbol', 'RSP']
    df = df[cols]
    # Sort by percentile rank (optional)
    df = df.sort_values(by='RSP', ascending=False).reset_index(drop=True)

    return df

In [6]:
# function to get stock technicals
def stock_prec_dev(stock_symbol):
    #stock_symbol = 'ULTRACEMCO.NS'
    short_window = 20
    mid_window = 50
    long_window = 200
    moving_avg = 'SMA'

    start = datetime.datetime(*map(int, start_date.split('-')))
    end = datetime.datetime(*map(int, end_date.split('-')))

    stock_df = yfin.Ticker(stock_symbol + '.NS').history(period='max', interval='1d')[map(str.title, ['open', 'close', 'low', 'high', 'volume'])]

    stock_df['Max'] = round(max(stock_df['Close']),2)
    stock_df = stock_df[(stock_df.index <= end_date) & (stock_df.index >= start_date)]
    stock_df['200_SMA'] = round(stock_df['Close'].rolling(window = 200, min_periods = 1).mean(),0)
    stock_df['Dev%_200'] = round((stock_df['Close'] - stock_df['200_SMA'])*100/stock_df['200_SMA'],2)
    stock_df.dropna(axis = 0, inplace = True) # remove any null rows

    stock_df['20_SMA'] = stock_df['Close'].rolling(window=20).mean()
    stock_df['50_SMA'] = stock_df['Close'].rolling(window=50).mean()
    stock_df['Symbol'] = stock_symbol

    stock_df['Close'] = round(stock_df['Close'],2)
    stock_df['Min'] = round(min(stock_df['Close']),2)
    stock_df['RSI_14'] = ta.momentum.RSIIndicator(close=stock_df['Close'], window=14).rsi()
    stock_df['RSI_14'] = round(stock_df['RSI_14'],0)
    stock_df['Prev_Close'] = stock_df['Close'].shift(1)
    stock_df.drop(['Open', 'Low', 'High', 'Volume'], axis=1, inplace=True)
    stock_df = stock_df.tail(1)

    max_SMA = max(stock_df['20_SMA'].item(), stock_df['50_SMA'].item(), stock_df['200_SMA'].item())
    min_SMA = min(stock_df['20_SMA'].item(), stock_df['50_SMA'].item(), stock_df['200_SMA'].item())
    ABS_Spread = max_SMA - min_SMA
    stock_df['Spread%'] = round((ABS_Spread / stock_df['200_SMA'].item()) * 100,2)

    return stock_df

# function to compute stock attributes
def get_common_features(stock_ids, df_mypf):

  df_prec_dev = pd.DataFrame()
  df_tmp = get_screener_features()
  df_rs = get_relative_strength(stock_ids)

  for stock_id in stock_ids:
      tmp = stock_prec_dev(stock_id)
      tmp = tmp.reset_index()
      df_prec_dev = pd.concat([df_prec_dev, tmp], ignore_index = True)
  df_prec_dev = pd.merge(df_prec_dev, df_mypf, on= 'Symbol')
  df_prec_dev = pd.merge(df_prec_dev, df_tmp, on= 'Symbol', how='left')
  df_prec_dev = pd.merge(df_prec_dev, df_rs, on= 'Symbol', how='left')
  #print(df_prec_dev.columns)
  df_prec_dev['Curr_PE'] = round(df_prec_dev['Close']/df_prec_dev['EPS'],1)
  df_prec_dev['Dev%_PE'] = round((df_prec_dev['Curr_PE'] - df_prec_dev['MedPE'])*100/df_prec_dev['MedPE'],2)
  df_prec_dev['Conviction'] = df_prec_dev['Conviction'] + '-' + df_prec_dev['CapType']
  return df_prec_dev

# function to arrange stock features
def arrange_features(df_stocks, common_cols, diff_cols):
  df_stocks_common = df_stocks[common_cols].drop_duplicates()
  df_stocks_diff = df_stocks[diff_cols]
  df_stocks_diff['Investment'] = df_stocks_diff['AvgCost'] * df_stocks_diff['Shares']
  df_stocks_diff = df_stocks_diff.groupby(['Symbol'])[['Shares', 'Investment']].aggregate(['sum']).reset_index()
  df_stocks_diff.columns = ['Symbol', 'Shares', 'Investment']
  df_stocks_diff['AvgCost'] = round(df_stocks_diff['Investment']/df_stocks_diff['Shares'],2)
  df_stocks = pd.merge(df_stocks_diff, df_stocks_common, on='Symbol')
  return df_stocks

# plot fact distribution across dimension
def plot_pie_chart(df, dimension, fact):
  # grouping the data by category and calculating the sum of fact for each type
  grouped_data = df.groupby(dimension)[fact].sum()

  # sorting the grouped data in descending order
  grouped_data = grouped_data.sort_values(ascending=False)

  # creating a pie chart
  grouped_data.plot.pie(autopct='%1.1f%%', startangle=90, figsize=(6, 6))

  # adding a title and displaying the plot
  plt.title(f'{dimension} {fact} Distribution')
  plt.ylabel('')  # To hide the y-label
  plt.show()

In [7]:
# function to get portfolio features

def get_portfolio_features(df_common_features):

  print_date_time()
  print('-------------------')

  #df_common_features["Target"] = df_common_features["Target"].fillna(df_common_features["Max"])
  df_common_features['NTT'] = np.where(df_common_features['Strategy']== 'NTT', df_common_features["Target"], df_common_features['Max'])
  df_common_features['LTT'] = np.where(df_common_features['Strategy']== 'BTT', df_common_features["Target"], df_common_features['Max'])
  df_common_features['BOL'] = df_common_features['Min']

  tmp_df = df_common_features[df_common_features['Symbol'].isin(mypf_df[mypf_df['InPortfolio'] != 'NA'].Symbol.values)]
  print('qualified stocks: '+str(len(tmp_df['Symbol'].unique())))
  tmp_df1 = tmp_df[tmp_df['LatestQtr'] == 1]
  print('with latest results: '+str(len(tmp_df1['Symbol'].unique())))
  tmp_df1 = tmp_df1[tmp_df1['StarStock'] == 1]
  print('still star stocks: '+str(len(tmp_df1['Symbol'].unique())))
  tmp_df['Investment'] = tmp_df['AvgCost'] * tmp_df['Shares']
  tmp_df['Current'] = round(tmp_df['Close'] * tmp_df['Shares'],0)
  tmp_df['Previous'] = tmp_df['Prev_Close'] * tmp_df['Shares']
  tmp_df['EstimatedST'] = tmp_df['NTT'] * tmp_df['Shares']
  tmp_df['EstimatedLT'] = tmp_df['LTT'] * tmp_df['Shares']
  tmp_df['Current P/L'] = round((tmp_df['Current'] - tmp_df['Investment']),0)
  tmp_df['Today P/L%'] = round((tmp_df['Current'] - tmp_df['Previous'])*100/tmp_df['Previous'],2)
  tmp_df['Current P/L%'] = round((tmp_df['Current'] - tmp_df['Investment'])*100/tmp_df['Investment'],2)
  tmp_df['EstimatedST P/L%'] = round((tmp_df['EstimatedST'] - tmp_df['Investment'])*100/tmp_df['Investment'],2)
  tmp_df['EstimatedLT P/L%'] = round((tmp_df['EstimatedLT'] - tmp_df['Investment'])*100/tmp_df['Investment'],2)
  tmp_df['NTT%'] = round((tmp_df['NTT'] - tmp_df['Close'])*100/tmp_df['Close'],2)
  tmp_df['LTT%'] = round((tmp_df['LTT'] - tmp_df['Close'])*100/tmp_df['Close'],2)
  tmp_df['Gained%'] = round((tmp_df['Close'] - tmp_df['BOL'])*100/tmp_df['BOL'],2)
  investment = round(sum(tmp_df['AvgCost']*tmp_df['Shares']),0)
  current = round(sum(tmp_df['Close']*tmp_df['Shares']),0)
  tmp_df['InitAlloc%'] = round(tmp_df['Investment']*100/investment,2)
  tmp_df['CurrAlloc%'] = round(tmp_df['Current']*100/current,2)
  tmp_df['FTT'] = tmp_df['LTT']
  tmp_df.loc[tmp_df['Strategy'] == 'NTT', 'FTT'] = tmp_df['NTT']
  tmp_df['FTT%'] = tmp_df['LTT%']
  tmp_df.loc[tmp_df['Strategy'] == 'NTT', 'FTT%'] = tmp_df['NTT%']
  tmp_df['FTT Amt'] = round(tmp_df['FTT%'] * tmp_df['Current']/100,0)
  tmp_df['OTT%'] = round((tmp_df['FTT'] - tmp_df['AvgCost'])*100/tmp_df['AvgCost'],2)
  tmp_df['RRR Ind'] = round(tmp_df['Current P/L']/tmp_df['FTT Amt'],2)
  tmp_df['Risk Ind'] = round(tmp_df['Current P/L%']*tmp_df['CurrAlloc%'],0)

  return tmp_df

# function to print portfolio features
def print_portfolio_stats(df_portfolio_features, myinvmt_df):
  from pyxirr import xirr

  total_booked_amt, reserve_amt, cy_booked_amt, py_booked_amt = get_amt()

  dates = myinvmt_df['Date'].values
  dates = np.append(dates, datetime.date.today().strftime('%d-%b-%y'))
  investment = myinvmt_df['Investment'].values
  dates= pd.to_datetime(dates)

  current = round(sum(df_portfolio_features['Close']*df_portfolio_features['Shares']),0) + reserve_amt
  investment_xirr = np.append(investment, current)
  cagr = round(xirr(pd.DataFrame({"dates": dates, "amounts": investment_xirr}))*100,2)

  investment = -sum(investment)
  invested = round(sum(df_portfolio_features['AvgCost']*df_portfolio_features['Shares']),0) + reserve_amt
  previous = round(sum(df_portfolio_features['Prev_Close']*df_portfolio_features['Shares']),0) + reserve_amt
  cy_invested = investment + py_booked_amt

  today_pnl_amount = current-previous
  today_pnl_percentage = round((current-previous)*100/previous,2)

  curr_pnl_amount = current-invested
  curr_pnl_percentage = round((curr_pnl_amount)*100/(cy_invested),2)

  cy_pnl_amount = cy_booked_amt + curr_pnl_amount
  cy_pnl_percentage = round((cy_pnl_amount)*100/cy_invested,2)

  overall_pnl_amount = total_booked_amt + curr_pnl_amount
  overall_pnl_percentage = round((overall_pnl_amount)*100/investment,2)

  estimate_st = round(sum(df_portfolio_features['FTT']*df_portfolio_features['Shares']),0)  + reserve_amt
  est_st_pnl_amount = estimate_st-current
  est_st_pnl_percentage = round((est_st_pnl_amount)*100/current,2)

  estimate_lt = round(sum(df_portfolio_features['LTT']*df_portfolio_features['Shares']),0)  + reserve_amt
  est_lt_pnl_amount = estimate_lt-current
  est_lt_pnl_percentage = round((est_lt_pnl_amount)*100/current,2)

  total_profit = round(sum(df_portfolio_features[df_portfolio_features['Current P/L%'] > 0]['Current']) - sum(df_portfolio_features[df_portfolio_features['Current P/L%'] > 0]['Investment']),0)
  total_loss = round(sum(df_portfolio_features[df_portfolio_features['Current P/L%'] < 0]['Current']) - sum(df_portfolio_features[df_portfolio_features['Current P/L%'] < 0]['Investment']),0)

  cy_booked_percentage = round((cy_booked_amt)*100/current,2)
  py_booked_percentage = round((py_booked_amt)*100/investment,2)
  total_booked_percentage = round((total_booked_amt)*100/investment,2)

  print('-------------------')
  print('Initial Investment: ', format_amt(investment))
  print('CY Investment: ', format_amt(cy_invested))
  print('Reserve: ', format_amt(reserve_amt))
  print('Current: ',  format_amt(current))
  print('-------------------')
  print('Today PnL: '+ '{} ({}%)'.format(format_amt(today_pnl_amount), today_pnl_percentage))
  print('Current PnL: '+ '{} ({}%)'.format(format_amt(curr_pnl_amount), curr_pnl_percentage))
  print('CY Booked + Current PnL: '+ '{} ({}%)'.format(format_amt(cy_pnl_amount), cy_pnl_percentage))
  print('-------------------')
  print('Total profit: ', format_amt(total_profit))
  print('Total loss: ', format_amt(total_loss))
  print('-------------------')
  print('Total Booked + Current PnL: '+ '{} ({}%)'.format(format_amt(overall_pnl_amount), overall_pnl_percentage))
  print('Total Booked PnL: '+ '{} ({}%)'.format(format_amt(total_booked_amt), total_booked_percentage))
  print('Curr Year Booked PnL: '+ '{} ({}%)'.format(format_amt(cy_booked_amt), cy_booked_percentage))
  print('Prev Year Booked PnL: '+ '{} ({}%)'.format(format_amt(py_booked_amt), py_booked_percentage))
  print('===================')
  print('Est FTT: ',  format_amt(estimate_st))
  print('Est FTT PnL: '+ '{} ({}%)'.format(format_amt(est_st_pnl_amount), est_st_pnl_percentage))

  print('===================')
  print('Deployed: ', format_amt(investment))

  print('Current: ', format_amt(current))

  print('CAGR/XIRR %: '+'{}%'.format(cagr))

In [8]:
# get start and end date
start_date, end_date = get_start_end_date()

# get portfolio and prospects data
mypfs_df = get_mypfs_df()
mypps_df = get_mypps_df()
myinvmt_df = get_myinvmt_df()

# merge above datasets
mypf_df = pd.merge(mypfs_df, mypps_df, on="Symbol")

# seggregate dm and sv portfolio
dm_pf = mypf_df[mypf_df['InPortfolio'] == 'DM']
sv_pf = mypf_df[mypf_df['InPortfolio'] == 'SV']

# build portfolio stock dataframe
dm_stocks = get_stock_ids(dm_pf)
sv_stocks = get_stock_ids(sv_pf)
df_stocks = pd.concat([dm_pf,sv_pf], ignore_index = True)

# arrange common and diff stock features
common_cols = ['Symbol', 'Target', 'Criteria', 'Strategy', 'CumlRnk', 'LatestQtr', 'StarStock', 'Conviction', 'Category', 'InFolio', 'XIRR', 'MBQ']
diff_cols = ['Symbol', 'AvgCost', 'Shares']
df_stocks = arrange_features(df_stocks, common_cols, diff_cols)

# get common features
stock_ids = df_stocks['Symbol'].values
df_common_features = get_common_features(stock_ids, df_stocks)

df_common_features.reset_index(drop=True, inplace=True)
df_common_features.drop(['Date'], axis=1, inplace=True)
# get and print portfolio features
df_portfolio_features = get_portfolio_features(df_common_features)

print_portfolio_stats(df_portfolio_features, myinvmt_df)

df = df_portfolio_features
#plot_pie_chart(df, 'CapType', 'Current')
list_ox40n = list(df[df['MBQ'].str.contains('OX40N', na=False)]['Symbol'].values)

Run date time (IST): 2026-06-09 11:39:10
-------------------
qualified stocks: 92
with latest results: 31
still star stocks: 20
-------------------
Initial Investment:  1.40 C
CY Investment:  1.82 C
Reserve:  1.49 K
Current:  1.47 C
-------------------
Today PnL: 1.14 L (0.78%)
Current PnL: -35.87 L (-19.67%)
CY Booked + Current PnL: -33.79 L (-18.53%)
-------------------
Total profit:  2.42 L
Total loss:  -38.29 L
-------------------
Total Booked + Current PnL: 9.08 L (6.51%)
Total Booked PnL: 44.95 L (32.22%)
Curr Year Booked PnL: 2.08 L (1.41%)
Prev Year Booked PnL: 42.87 L (30.73%)
===================
Est FTT:  2.55 C
Est FTT PnL: 1.08 C (73.22%)
===================
Deployed:  1.40 C
Current:  1.47 C
CAGR/XIRR %: 2.57%

In [9]:
# top 5 near their targets
cols = ['Symbol', 'Today P/L%', 'Current P/L%', 'FTT%', 'OTT%', 'FTT Amt', 'Current P/L', 'Current', 'FTT', 'Dev%_PE', 'RSI_14','Conviction', 'Spread%',  'CumlRnk', 'RRR Ind', 'CurrAlloc%', 'Gained%', 'Criteria', 'Strategy', 'Category']
df_tmp = df_portfolio_features[~df_portfolio_features['Symbol'].isin(['ENRIN','BLUSPRING','DIGITIDE'])]
df_tmp = df_tmp.sort_values(by = 'FTT Amt', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
59,PIDILITIND,1.76,5.27,12.44,18.37,18480.0,7440.0,148550.0,1670.26,-26.30,60.0,X-LC,4.05,5.0,0.40,1.01,16.64,X40,ATH,CHEMICALS
72,SIS,4.03,-2.87,24.85,21.26,26798.0,-3192.0,107840.0,528.00,2572.02,66.0,H-SC,20.04,168.0,-0.12,0.73,60.34,OX40N,NTT,MISC
51,KOTAKBANK,0.50,1.27,19.59,21.11,27471.0,1758.0,140230.0,453.24,-13.31,47.0,X-LC,6.97,12.0,0.06,0.95,7.24,X40,ATH,BANKS
55,MASFIN,0.96,-8.39,32.70,21.57,29352.0,-8220.0,89760.0,397.04,-20.96,37.0,H-SC,1.92,167.0,-0.28,0.61,6.99,XR,ATH,FINANCE
83,TTKPRESTIG,4.18,-29.78,42.54,0.09,30104.0,-30011.0,70766.0,770.00,64.35,55.0,M-SC,13.16,250.0,-1.00,0.48,26.01,OX40N,NTT,DURABLES

In [10]:
# top 5 today
df_tmp = df_portfolio_features.sort_values(by = 'Today P/L%', ascending=False)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
64,RELAXO,6.39,-56.02,246.34,52.31,157251.0,-81325.0,63835.0,1176.00,-53.15,63.0,X-SC,21.33,92.0,-0.52,0.43,42.73,X40N,NTT,FOOTWEAR
16,CERA,4.96,-24.89,64.94,23.89,85801.0,-43779.0,132124.0,9475.00,-27.45,58.0,H-SC,4.70,153.0,-0.51,0.90,26.97,OX40N,NTT,CERAMICS
83,TTKPRESTIG,4.18,-29.78,42.54,0.09,30104.0,-30011.0,70766.0,770.00,64.35,55.0,M-SC,13.16,250.0,-1.00,0.48,26.01,OX40N,NTT,DURABLES
72,SIS,4.03,-2.87,24.85,21.26,26798.0,-3192.0,107840.0,528.00,2572.02,66.0,H-SC,20.04,168.0,-0.12,0.73,60.34,OX40N,NTT,MISC
3,ALKYLAMINE,3.04,-21.50,146.66,93.63,116240.0,-21705.0,79258.0,4546.37,-15.90,63.0,H-SC,9.48,142.0,-0.19,0.54,49.66,SR,ATH,CHEMICALS

In [11]:
# bottom 5 today
df_tmp = df_portfolio_features.sort_values(by = 'Today P/L%', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
61,RAJESHEXPO,-5.00,-82.79,481.30,0.07,113654.0,-113563.0,23614.0,518.00,764.90,28.0,L-SC,31.14,268.0,-1.00,0.16,10.86,OX40N,NTT,JEWELLERY
18,COFFEEDAY,-3.40,-40.36,126.82,35.27,85880.0,-45831.0,67718.0,80.00,-53.72,62.0,L-SC,18.73,266.0,-0.53,0.46,67.00,XR,NTT,HOTELS
45,INFY,-1.09,-20.04,67.89,34.24,169854.0,-62698.0,250190.0,1972.00,-37.23,47.0,X-LC,17.43,3.0,-0.37,1.70,7.27,X40,NTT,IT
89,WHIRLPOOL,-0.99,-38.14,194.10,81.92,137830.0,-43788.0,71010.0,2270.00,-63.73,27.0,M-SC,17.98,210.0,-0.32,0.48,0.00,XR,NTT,DURABLES
58,PGHH,-0.94,-32.19,94.67,32.01,137075.0,-68728.0,144792.0,17616.87,-54.11,32.0,X-MC,18.72,57.0,-0.50,0.98,0.00,X40,ATH,FMCG

In [12]:
# top 5 to exit based on CumlRnk
df_tmp = df_portfolio_features[~df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])]
df_tmp = df_tmp[(df_tmp['Current P/L%'] > -1) & (df_tmp['Current P/L%'] < 1)].sort_values(by = 'CumlRnk', ascending=False)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
74,STARHEALTH,0.2,0.59,46.4,47.26,131206.0,1648.0,282771.0,761.0,58.79,51.0,H-SC,9.65,173.0,0.01,1.92,24.15,XY24,NTT,INSURANCE

In [13]:
# OX40N stocks to exit
df_tmp = df_portfolio_features[(df_portfolio_features['Symbol'].isin(list_ox40n))].sort_values(by = 'Current P/L%', ascending=False)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
25,FINCABLES,1.02,30.46,59.37,107.91,114353.0,44966.0,192610.0,1641.55,17.20,49.0,M-SC,24.88,220.0,0.39,1.31,44.91,OX40N,ATH,CABLES
72,SIS,4.03,-2.87,24.85,21.26,26798.0,-3192.0,107840.0,528.00,2572.02,66.0,H-SC,20.04,168.0,-0.12,0.73,60.34,OX40N,NTT,MISC
16,CERA,4.96,-24.89,64.94,23.89,85801.0,-43779.0,132124.0,9475.00,-27.45,58.0,H-SC,4.70,153.0,-0.51,0.90,26.97,OX40N,NTT,CERAMICS
83,TTKPRESTIG,4.18,-29.78,42.54,0.09,30104.0,-30011.0,70766.0,770.00,64.35,55.0,M-SC,13.16,250.0,-1.00,0.48,26.01,OX40N,NTT,DURABLES
50,KANSAINER,-0.42,-29.99,62.07,13.47,117189.0,-80865.0,188802.0,340.00,-39.78,46.0,H-SC,8.81,162.0,-0.69,1.28,31.88,XY24,NTT,PAINTS

In [14]:
# top 5 to book for rotation
df_tmp = df_portfolio_features[(df_portfolio_features['Current P/L%'] > 20) ].sort_values(by = 'CumlRnk', ascending=False)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
25,FINCABLES,1.02,30.46,59.37,107.91,114353.0,44966.0,192610.0,1641.55,17.20,49.0,M-SC,24.88,220.0,0.39,1.31,44.91,OX40N,ATH,CABLES
68,SATIN,1.16,33.02,14.14,51.83,51967.0,91233.0,367517.0,274.00,19.58,71.0,H-SC,41.09,159.0,1.76,2.50,79.03,XY24,NTT,FINANCE

In [15]:
# top 5 to monitor for exit
df_tmp = df_portfolio_features[~df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])]
df_tmp = df_tmp[(df_tmp['Current P/L%'] > 0) ].sort_values(by = 'Dev%_PE', ascending=False)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
74,STARHEALTH,0.20,0.59,46.40,47.26,131206.0,1648.0,282771.0,761.00,58.79,51.0,H-SC,9.65,173.0,0.01,1.92,24.15,XY24,NTT,INSURANCE
68,SATIN,1.16,33.02,14.14,51.83,51967.0,91233.0,367517.0,274.00,19.58,71.0,H-SC,41.09,159.0,1.76,2.50,79.03,XY24,NTT,FINANCE
25,FINCABLES,1.02,30.46,59.37,107.91,114353.0,44966.0,192610.0,1641.55,17.20,49.0,M-SC,24.88,220.0,0.39,1.31,44.91,OX40N,ATH,CABLES
91,ZYDUSLIFE,1.88,16.85,16.07,35.63,39354.0,35316.0,244890.0,1286.17,1.80,74.0,H-MC,10.86,120.0,0.90,1.66,28.76,AR,ATH,PHARMA
73,SONACOMS,2.14,3.94,33.81,39.09,35551.0,3990.0,105149.0,804.02,-17.63,54.0,M-MC,18.74,193.0,0.11,0.71,48.75,AR,ATH,AUTO

In [16]:
# top 5 to book for rotation from weak conviction
df_tmp = df_portfolio_features[~df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])]
df_tmp = df_tmp[~df_tmp['Criteria'].isin(['XY25','XY24','X40', 'X40N'])].sort_values(by = 'RRR Ind', ascending=False)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
91,ZYDUSLIFE,1.88,16.85,16.07,35.63,39354.0,35316.0,244890.0,1286.17,1.80,74.0,H-MC,10.86,120.0,0.90,1.66,28.76,AR,ATH,PHARMA
25,FINCABLES,1.02,30.46,59.37,107.91,114353.0,44966.0,192610.0,1641.55,17.20,49.0,M-SC,24.88,220.0,0.39,1.31,44.91,OX40N,ATH,CABLES
73,SONACOMS,2.14,3.94,33.81,39.09,35551.0,3990.0,105149.0,804.02,-17.63,54.0,M-MC,18.74,193.0,0.11,0.71,48.75,AR,ATH,AUTO
75,SURYODAY,1.47,-1.59,25.02,23.03,44091.0,-2846.0,176225.0,216.00,92.98,66.0,H-SC,18.73,166.0,-0.06,1.20,48.38,XR,NTT,BANKS
42,INDIAMART,0.08,-13.62,139.32,106.72,148425.0,-16801.0,106535.0,4810.62,-61.13,47.0,H-SC,11.25,140.0,-0.11,0.72,3.13,AR,ATH,MISC

In [17]:
# top 5 to accumulate based on lowest RSI_14
df_tmp = df_portfolio_features[df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])].sort_values(by = 'RSI_14', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
35,HDFCLIFE,-0.61,-8.23,45.13,33.18,62040.0,-12330.0,137470.0,814.30,-28.33,29.0,X-LC,15.29,31.0,-0.20,0.93,0.00,X40,ATH,INSURANCE
65,RELIANCE,0.16,-18.78,54.27,25.30,88582.0,-37739.0,163224.0,1952.00,-20.80,29.0,X-LC,6.66,21.0,-0.43,1.11,0.16,XY25,BTT,REFINERIES
58,PGHH,-0.94,-32.19,94.67,32.01,137075.0,-68728.0,144792.0,17616.87,-54.11,32.0,X-MC,18.72,57.0,-0.50,0.98,0.00,X40,ATH,FMCG
40,ICICIPRULI,0.57,-20.88,64.67,30.28,100795.0,-41144.0,155861.0,787.27,-42.12,33.0,X-MC,15.18,78.0,-0.41,1.06,0.60,X40,ATH,INSURANCE
2,ACC,-0.32,-41.13,196.92,74.81,310858.0,-110268.0,157860.0,3906.00,-58.35,35.0,X-SC,17.39,85.0,-0.35,1.07,4.85,XY24,BTT,CEMENT

In [18]:
# top 5 to accumulate based on Spread and CumlRnk
df_tmp = df_portfolio_features[df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])]
df_tmp = df_tmp[(df_tmp['CumlRnk'] < 100)].sort_values(by = 'Spread%', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
57,PAGEIND,0.67,1.23,31.97,33.59,86853.0,3291.0,271670.0,51217.30,-27.40,60.0,X-MC,3.00,55.0,0.04,1.84,29.02,X40,ATH,APPARELS
49,JSWINFRA,2.61,-6.23,24.16,16.43,50244.0,-13809.0,207965.0,342.00,-19.64,52.0,X-MC,3.41,61.0,-0.27,1.41,17.56,X40N,NTT,REALTY
15,CAMS,0.72,-2.32,27.43,24.48,67482.0,-5841.0,246015.0,950.00,-6.47,43.0,X-SC,3.92,89.0,-0.09,1.67,19.77,X40N,NTT,MISC
19,COLPAL,0.23,-23.68,83.25,39.86,167341.0,-62355.0,201010.0,3683.41,-7.64,41.0,X-MC,4.02,62.0,-0.37,1.36,13.70,XY25,ATH,FMCG
59,PIDILITIND,1.76,5.27,12.44,18.37,18480.0,7440.0,148550.0,1670.26,-26.30,60.0,X-LC,4.05,5.0,0.40,1.01,16.64,X40,ATH,CHEMICALS

In [19]:
# top 5 to accumulate based on lowest Gained%
df_tmp = df_portfolio_features[df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])].sort_values(by = 'Gained%', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
35,HDFCLIFE,-0.61,-8.23,45.13,33.18,62040.0,-12330.0,137470.0,814.30,-28.33,29.0,X-LC,15.29,31.0,-0.20,0.93,0.00,X40,ATH,INSURANCE
58,PGHH,-0.94,-32.19,94.67,32.01,137075.0,-68728.0,144792.0,17616.87,-54.11,32.0,X-MC,18.72,57.0,-0.50,0.98,0.00,X40,ATH,FMCG
79,TCS,-0.02,-36.86,97.77,24.88,285999.0,-170751.0,292522.0,4253.91,-46.57,36.0,X-LC,18.72,2.0,-0.60,1.99,0.00,X40,ATH,IT
65,RELIANCE,0.16,-18.78,54.27,25.30,88582.0,-37739.0,163224.0,1952.00,-20.80,29.0,X-LC,6.66,21.0,-0.43,1.11,0.16,XY25,BTT,REFINERIES
34,HDFCBANK,-0.49,-12.06,45.98,28.37,94971.0,-28336.0,206549.0,1073.00,-25.47,37.0,X-LC,16.48,26.0,-0.30,1.40,0.48,X40,BTT,BANKS

In [20]:
# top 5 to accumulate based on lowest CurrAlloc%
df_tmp = df_portfolio_features[df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])].sort_values(by = 'CurrAlloc%', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
10,BATAINDIA,0.55,-57.29,216.54,35.20,119006.0,-73712.0,54958.0,2096.00,-27.94,37.0,X-SC,25.53,91.0,-0.62,0.37,9.00,X40,NTT,FOOTWEAR
64,RELAXO,6.39,-56.02,246.34,52.31,157251.0,-81325.0,63835.0,1176.00,-53.15,63.0,X-SC,21.33,92.0,-0.52,0.43,42.73,X40N,NTT,FOOTWEAR
60,QUESS,1.25,-1.98,77.41,73.90,81034.0,-2111.0,104682.0,424.00,-47.11,73.0,X-SC,4.94,80.0,-0.03,0.71,42.70,XY24,NTT,MISC
28,GODREJCP,1.00,-9.88,45.88,31.47,61448.0,-14683.0,133931.0,1469.04,-5.16,43.0,X-LC,10.03,32.0,-0.24,0.91,2.76,X40N,ATH,FMCG
53,M&M,1.50,-2.31,26.30,23.38,35630.0,-3204.0,135477.0,3802.40,-17.22,43.0,X-LC,10.29,25.0,-0.09,0.92,2.71,X40N,ATH,AUTO

In [21]:
# top 5 to accumulate based on CumlRnk
df_tmp = df_portfolio_features.sort_values(by = 'CumlRnk', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
47,ITC,0.09,-26.33,61.60,19.06,154376.0,-89555.0,250611.0,452.00,-59.56,35.0,X-LC,14.75,1.0,-0.58,1.70,0.97,X40,NTT,FMCG
79,TCS,-0.02,-36.86,97.77,24.88,285999.0,-170751.0,292522.0,4253.91,-46.57,36.0,X-LC,18.72,2.0,-0.60,1.99,0.00,X40,ATH,IT
45,INFY,-1.09,-20.04,67.89,34.24,169854.0,-62698.0,250190.0,1972.00,-37.23,47.0,X-LC,17.43,3.0,-0.37,1.70,7.27,X40,NTT,IT
81,TMPV,0.05,-11.41,54.16,36.58,170740.0,-40589.0,315252.0,600.00,-81.44,60.0,X-LC,16.50,4.0,-0.24,2.14,31.40,XY24,NTT,AUTO
59,PIDILITIND,1.76,5.27,12.44,18.37,18480.0,7440.0,148550.0,1670.26,-26.30,60.0,X-LC,4.05,5.0,0.40,1.01,16.64,X40,ATH,CHEMICALS

In [22]:
# top 5 for average up
df_tmp = df_portfolio_features[(df_portfolio_features['Dev%_200'] > 5)].sort_values(by = 'CurrAlloc%', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
44,INDUSINDBK,1.27,-33.08,98.59,32.89,50937.0,-25542.0,51665.0,1800.00,-343.00,51.0,L-MC,7.35,258.0,-0.50,0.35,27.17,XR,NTT,BANKS
3,ALKYLAMINE,3.04,-21.50,146.66,93.63,116240.0,-21705.0,79258.0,4546.37,-15.90,63.0,H-SC,9.48,142.0,-0.19,0.54,49.66,SR,ATH,CHEMICALS
60,QUESS,1.25,-1.98,77.41,73.90,81034.0,-2111.0,104682.0,424.00,-47.11,73.0,X-SC,4.94,80.0,-0.03,0.71,42.70,XY24,NTT,MISC
73,SONACOMS,2.14,3.94,33.81,39.09,35551.0,3990.0,105149.0,804.02,-17.63,54.0,M-MC,18.74,193.0,0.11,0.71,48.75,AR,ATH,AUTO
72,SIS,4.03,-2.87,24.85,21.26,26798.0,-3192.0,107840.0,528.00,2572.02,66.0,H-SC,20.04,168.0,-0.12,0.73,60.34,OX40N,NTT,MISC

In [23]:
# top 5 RSP
df_tmp = df_portfolio_features.sort_values(by = 'RSP', ascending=False)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
18,COFFEEDAY,-3.40,-40.36,126.82,35.27,85880.0,-45831.0,67718.0,80.00,-53.72,62.0,L-SC,18.73,266.0,-0.53,0.46,67.00,XR,NTT,HOTELS
37,HONAUT,1.68,-8.94,66.17,51.31,116195.0,-17238.0,175600.0,58357.33,-24.24,63.0,X-SC,6.85,90.0,-0.15,1.19,33.41,X40N,ATH,ELECTRICAL
69,SFL,0.39,-33.68,90.95,26.63,158155.0,-88326.0,173892.0,1287.00,31.63,72.0,M-SC,8.27,242.0,-0.56,1.18,44.93,XY24,NTT,MISC
91,ZYDUSLIFE,1.88,16.85,16.07,35.63,39354.0,35316.0,244890.0,1286.17,1.80,74.0,H-MC,10.86,120.0,0.90,1.66,28.76,AR,ATH,PHARMA
81,TMPV,0.05,-11.41,54.16,36.58,170740.0,-40589.0,315252.0,600.00,-81.44,60.0,X-LC,16.50,4.0,-0.24,2.14,31.40,XY24,NTT,AUTO

In [24]:
# Top N allocation
df_tmp = df_portfolio_features.sort_values(by = 'CurrAlloc%', ascending=False)
top_n_values = [10, 25, 50]

sum_df = pd.DataFrame({
    'Top_N': top_n_values,
    'Sum_Alloc%': [df_tmp['CurrAlloc%'].head(n).sum() for n in top_n_values]
})

sum_df

   Top_N  Sum_Alloc%
0     10       19.78
1     25       42.87
2     50       72.87

In [25]:
# market-cap-wise allocation
df_tmp = df_portfolio_features[cols]
df_tmp.groupby(df_tmp['Conviction'].str[-2:])['CurrAlloc%'].sum().sort_values(ascending=False)

Conviction
SC    43.09
LC    31.24
MC    25.67
Name: CurrAlloc%, dtype: float64

In [26]:
# criteria-wise allocation
df_portfolio_features.groupby('Criteria')['CurrAlloc%'].sum().sort_values(ascending=False)

Criteria
XY24     27.91
X40      24.92
X40N     17.03
XR        8.93
OX40N     6.91
AR        6.85
XY25      6.55
SR        0.90
Name: CurrAlloc%, dtype: float64

In [27]:
# conviction-wise allocation
df_portfolio_features.groupby('Conviction')['CurrAlloc%'].sum().sort_values(ascending=False)

Conviction
X-LC    29.16
H-SC    22.72
X-MC    20.50
M-SC     9.93
X-SC     9.82
H-MC     2.80
M-MC     2.02
H-LC     1.22
M-LC     0.86
L-SC     0.62
L-MC     0.35
Name: CurrAlloc%, dtype: float64

In [28]:
# sector-wise stats
df_tmp = df_portfolio_features.groupby('Category')[['CurrAlloc%', 'Current', 'Current P/L', 'FTT Amt']].sum().sort_values(by=['Current', 'Current P/L'], ascending=False)
df_tmp['Current P/L%'] = round(df_tmp['Current P/L'] * 100 / df_tmp['Current'], 2)
df_tmp['FTT%'] = round(df_tmp['FTT Amt'] * 100 / df_tmp['Current'], 2)
cols = ['CurrAlloc%', 'Current P/L%', 'FTT%']
df_tmp[cols].sort_values(by=['CurrAlloc%'], ascending=False)

               CurrAlloc%  Current P/L%    FTT%
Category
FMCG                14.87        -20.81   63.18
FINANCE             10.93        -14.61   64.45
IT                  10.16        -50.78  126.17
MISC                 7.12        -27.73   83.22
AUTO                 6.86         -8.42   49.07
BANKS                5.76         -7.05   56.54
PAINTS               5.55        -20.47   41.39
INSURANCE            5.20         -8.17   44.75
PHARMA               5.08          1.03   29.60
ELECTRICAL           4.05        -18.48   60.30
CHEMICALS            2.18        -26.25  101.49
HEALTHCARE           2.06        -17.89   48.65
APPARELS             1.84          1.21   31.97
AC                   1.84        -17.93   49.91
FOOTWEAR             1.71        -74.22  144.07
TRAVEL               1.59        -91.24  187.00
DURABLES             1.56        -68.28  109.22
BREWERIES            1.46         -8.85   31.46
REALTY               1.41         -6.64   24.16
CERAMICS             1.36        -53.96  100.74
CABLES               1.31         23.35   59.37
ENGINEERING          1.30        -26.12   83.80
REFINERIES           1.11        -23.12   54.27
CEMENT               1.07        -69.85  196.92
JEWELLERY            1.03       -111.59  185.11
ENTERTAINMENT        0.73        -79.77  186.99
HOTELS               0.46        -67.68  126.82
TEXTILES             0.40        -54.98   99.17

In [29]:
# money to be made criteria-wise
df_portfolio_features.groupby('Criteria')['FTT Amt'].agg(['sum', 'count']).sort_values(by='sum', ascending=False)

                sum  count
Criteria
XY24      3486453.0     21
X40       2012664.0     19
XR        1367796.0     13
X40N      1212236.0     13
AR        1172962.0      9
OX40N      774659.0     10
XY25       471724.0      5
SR         287535.0      2

In [30]:
# money to be made conviction-wise
df_portfolio_features.groupby('Conviction')['FTT Amt'].agg(['sum', 'count']).sort_values(by='sum', ascending=False)

                  sum  count
Conviction
H-SC        3441705.0     24
X-LC        1994263.0     21
X-MC        1697330.0     15
M-SC        1454859.0     14
X-SC        1355095.0      9
H-MC         284712.0      2
L-SC         199534.0      2
M-LC         165672.0      1
M-MC          88354.0      2
H-LC          53568.0      1
L-MC          50937.0      1

In [31]:
# money to be made criteria and conviction-wise
df_portfolio_features.groupby(['Conviction', 'Criteria'])['FTT Amt'].agg(['sum', 'count']).sort_values(by='sum', ascending=False)

                           sum  count
Conviction Criteria
X-LC       X40       1081433.0     10
H-SC       XY24      1041807.0      6
           AR         967449.0      5
M-SC       XY24       844399.0      6
H-SC       XR         820466.0      7
X-SC       XY24       796474.0      4
X-MC       X40        713538.0      7
           X40N       498293.0      4
X-LC       X40N       373015.0      6
X-SC       X40N       340928.0      3
M-SC       OX40N      336557.0      5
H-SC       OX40N      324448.0      4
X-LC       XY24       323180.0      2
H-SC       SR         287535.0      2
X-MC       XY25       250264.0      2
H-MC       XY24       245358.0      1
X-MC       XY24       235235.0      2
X-SC       X40        217693.0      2
M-SC       XR         196863.0      2
X-LC       XY25       168657.0      2
M-LC       XR         165672.0      1
L-SC       OX40N      113654.0      1
           XR          85880.0      1
M-SC       AR          77040.0      1
H-LC       AR          53568.0      1
M-MC       XY25        52803.0      1
L-MC       XR          50937.0      1
X-LC       XR          47978.0      1
H-MC       AR          39354.0      1
M-MC       AR          35551.0      1

In [32]:
# notebook execution time

end_time = time.time()
execution_time = round(end_time - start_time, 0)
print(f"Notebook execution time: {execution_time} seconds")

Notebook execution time: 36.0 seconds