<a href="https://colab.research.google.com/github/ankit-rathi/Quantvesting_v2/blob/main/myStocks_Portfolio_Analysis.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
'''
!pip install pandas==2.2.2 -qq
!pip install pyxirr -qq
!pip install ta -qq
!pip install yfinance==0.2.59 -qq
'''

'\n!pip install pandas==2.2.2 -qq\n!pip install pyxirr -qq\n!pip install ta -qq\n!pip install yfinance==0.2.59 -qq\n'

In [2]:
# import libraries

import numpy as np
import pandas as pd
import datetime
import warnings
warnings.filterwarnings('ignore')
import yfinance as yfin
import ta
import matplotlib.pyplot as plt
import requests

In [3]:
# notebook start time
import time
import datetime
import pytz

start_time = time.time()

# function to print date timestamp
def print_date_time():
  tz_NY = pytz.timezone('Asia/Kolkata')
  datetime_NY = datetime.datetime.now(tz_NY)
  print("Run date time (IST):", datetime_NY.strftime("%Y-%m-%d %H:%M:%S"))

In [4]:
# function to get booked and reserved amount
def get_amt():
  # fetch the JSON data from the URL
  url = "https://raw.githubusercontent.com/ankit-rathi/Tradevesting_v1/main/data/myPortfolioAmts.json"
  response = requests.get(url)
  pf_amts = response.json()  # parse the JSON data

  # extract values from the JSON
  py_booked_amt_dm = pf_amts["py_booked_amt_dm"]
  py_booked_amt_sv = pf_amts["py_booked_amt_sv"]
  cy_booked_amt_dm = pf_amts["cy_booked_amt_dm"]
  cy_booked_amt_sv = pf_amts["cy_booked_amt_sv"]
  reserve_amt_dm = pf_amts["reserve_amt_dm"]
  reserve_amt_sv = pf_amts["reserve_amt_sv"]

  # perform calculations
  py_booked_amt = py_booked_amt_dm + py_booked_amt_sv
  cy_booked_amt = cy_booked_amt_dm + cy_booked_amt_sv
  reserve_amt = reserve_amt_dm + reserve_amt_sv
  total_booked_amt = py_booked_amt + cy_booked_amt

  return total_booked_amt, reserve_amt, cy_booked_amt, py_booked_amt

gen_output = 0

In [5]:
# function to format the amount
def format_amt(number):
    abs_number = abs(number)

    if abs_number >= 1_00_00_000:  # Crores
        formatted_amt = f"{number / 1_00_00_000:.2f} C"
    elif abs_number >= 1_00_000:  # Lakhs
        formatted_amt = f"{number / 1_00_000:.2f} L"
    elif abs_number >= 1_000:  # Thousands
        formatted_amt = f"{number / 1_000:.2f} K"
    else:
        formatted_amt = f"{number:.2f}"

    return formatted_amt

# function to set start and end date
def get_start_end_date():
  start_date = (datetime.date.today() + datetime.timedelta(days=-365)).strftime('%Y-%m-%d')
  end_date = (datetime.date.today() + datetime.timedelta(days=1)).strftime('%Y-%m-%d')
  return start_date, end_date

# function to fetch my portfolio csv
def get_mypfs_df():
  mypfs_df = pd.read_csv('https://raw.githubusercontent.com/ankit-rathi/Tradevesting_v1/main/data/myPortfolioStocks.csv')
  return mypfs_df

# function to fetch my prospects csv
def get_mypps_df():
  mypps_df = pd.read_csv('https://raw.githubusercontent.com/ankit-rathi/Tradevesting_v1/main/data/myProspectsScrips.csv')
  return mypps_df

# function to fetch screener data
def get_myscreen_df():
  myscreen_df = pd.read_csv('https://raw.githubusercontent.com/ankit-rathi/Tradevesting_v1/main/data/myScreenerDB.csv')
  return myscreen_df

# function to fetch momentum data
def get_myinvmt_df():
  myinvmt_df = pd.read_csv('https://raw.githubusercontent.com/ankit-rathi/Tradevesting_v1/main/data/myInvestments.csv')
  return myinvmt_df

# function to get the stock ids
def get_stock_ids(df_pf):
  stock_n100 = df_pf['Symbol'].unique()

  exclude = ['CADILAHC','MMTC', 'MASFIN']

  stock_ids = df_pf[~df_pf['Symbol'].isin(exclude) ]['Symbol'].unique()

  #mypf = mypf[mypf.Forecast.notnull()]
  #stock_ids = mypf['Symbol'].unique()

  #stock_ids.sort()
  return stock_ids

# get features from screener data
def get_screener_features():
  myscreen_df = get_myscreen_df()
  cols = ['Symbol', 'EPS', 'MedPE', 'ROCE%', 'ROE%', 'CapType']
  return myscreen_df[cols]

# get relative strength
def get_relative_strength(stock_list):

    # Dictionary to store stock tickers and their corresponding percentage price change
    stock_changes = {}

    # Loop through each stock and fetch its price data
    for stock in stock_list:
        try:
            # Download the stock data for the given date range
            stock_data = yfin.Ticker(stock + '.NS').history(period='1mo', interval='1d')[map(str.title, ['open', 'close', 'low', 'high', 'volume'])]

            # Calculate the percentage change for the stock
            if len(stock_data) > 0:
                start_price = stock_data['Close'].iloc[0]
                end_price = stock_data['Close'].iloc[-1]
                percent_change = round(((end_price - start_price) / start_price) * 100, 2)
                stock_changes[stock] = percent_change
            else:
                stock_changes[stock] = np.nan  # If no data is available, set to NaN

        except Exception as e:
            print(f"Error fetching data for {stock}: {e}")
            stock_changes[stock] = np.nan

    # Create a DataFrame with stock tickers and their percentage changes
    df = pd.DataFrame(list(stock_changes.items()), columns=['Symbol', 'Percent_Change'])

    # Drop any stocks with missing data (NaN values)
    df = df.dropna()

    # Calculate the percentile rank based on percentage change
    df['RSP'] = round(df['Percent_Change'].rank(pct=True) * 100, 2)
    cols = ['Symbol', 'RSP']
    df = df[cols]
    # Sort by percentile rank (optional)
    df = df.sort_values(by='RSP', ascending=False).reset_index(drop=True)

    return df

In [6]:
# function to get stock technicals
def stock_prec_dev(stock_symbol):
    #stock_symbol = 'ULTRACEMCO.NS'
    short_window = 20
    mid_window = 50
    long_window = 200
    moving_avg = 'SMA'

    start = datetime.datetime(*map(int, start_date.split('-')))
    end = datetime.datetime(*map(int, end_date.split('-')))

    stock_df = yfin.Ticker(stock_symbol + '.NS').history(period='max', interval='1d')[map(str.title, ['open', 'close', 'low', 'high', 'volume'])]

    stock_df['Max'] = round(max(stock_df['Close']),2)
    stock_df = stock_df[(stock_df.index <= end_date) & (stock_df.index >= start_date)]
    stock_df['200_SMA'] = round(stock_df['Close'].rolling(window = 200, min_periods = 1).mean(),0)
    stock_df['Dev%_200'] = round((stock_df['Close'] - stock_df['200_SMA'])*100/stock_df['200_SMA'],2)
    stock_df.dropna(axis = 0, inplace = True) # remove any null rows

    stock_df['20_SMA'] = stock_df['Close'].rolling(window=20).mean()
    stock_df['50_SMA'] = stock_df['Close'].rolling(window=50).mean()
    stock_df['Symbol'] = stock_symbol

    stock_df['Close'] = round(stock_df['Close'],2)
    stock_df['Min'] = round(min(stock_df['Close']),2)
    stock_df['RSI_14'] = ta.momentum.RSIIndicator(close=stock_df['Close'], window=14).rsi()
    stock_df['RSI_14'] = round(stock_df['RSI_14'],0)
    stock_df['Prev_Close'] = stock_df['Close'].shift(1)
    stock_df.drop(['Open', 'Low', 'High', 'Volume'], axis=1, inplace=True)
    stock_df = stock_df.tail(1)

    max_SMA = max(stock_df['20_SMA'].item(), stock_df['50_SMA'].item(), stock_df['200_SMA'].item())
    min_SMA = min(stock_df['20_SMA'].item(), stock_df['50_SMA'].item(), stock_df['200_SMA'].item())
    ABS_Spread = max_SMA - min_SMA
    stock_df['Spread%'] = round((ABS_Spread / stock_df['200_SMA'].item()) * 100,2)

    return stock_df

# function to compute stock attributes
def get_common_features(stock_ids, df_mypf):

  df_prec_dev = pd.DataFrame()
  df_tmp = get_screener_features()
  df_rs = get_relative_strength(stock_ids)

  for stock_id in stock_ids:
      tmp = stock_prec_dev(stock_id)
      tmp = tmp.reset_index()
      df_prec_dev = pd.concat([df_prec_dev, tmp], ignore_index = True)
  df_prec_dev = pd.merge(df_prec_dev, df_mypf, on= 'Symbol')
  df_prec_dev = pd.merge(df_prec_dev, df_tmp, on= 'Symbol', how='left')
  df_prec_dev = pd.merge(df_prec_dev, df_rs, on= 'Symbol', how='left')
  #print(df_prec_dev.columns)
  df_prec_dev['Curr_PE'] = round(df_prec_dev['Close']/df_prec_dev['EPS'],1)
  df_prec_dev['Dev%_PE'] = round((df_prec_dev['Curr_PE'] - df_prec_dev['MedPE'])*100/df_prec_dev['MedPE'],2)
  df_prec_dev['Conviction'] = df_prec_dev['Conviction'] + '-' + df_prec_dev['CapType']
  return df_prec_dev

# function to arrange stock features
def arrange_features(df_stocks, common_cols, diff_cols):
  df_stocks_common = df_stocks[common_cols].drop_duplicates()
  df_stocks_diff = df_stocks[diff_cols]
  df_stocks_diff['Investment'] = df_stocks_diff['AvgCost'] * df_stocks_diff['Shares']
  df_stocks_diff = df_stocks_diff.groupby(['Symbol'])[['Shares', 'Investment']].aggregate(['sum']).reset_index()
  df_stocks_diff.columns = ['Symbol', 'Shares', 'Investment']
  df_stocks_diff['AvgCost'] = round(df_stocks_diff['Investment']/df_stocks_diff['Shares'],2)
  df_stocks = pd.merge(df_stocks_diff, df_stocks_common, on='Symbol')
  return df_stocks

# plot fact distribution across dimension
def plot_pie_chart(df, dimension, fact):
  # grouping the data by category and calculating the sum of fact for each type
  grouped_data = df.groupby(dimension)[fact].sum()

  # sorting the grouped data in descending order
  grouped_data = grouped_data.sort_values(ascending=False)

  # creating a pie chart
  grouped_data.plot.pie(autopct='%1.1f%%', startangle=90, figsize=(6, 6))

  # adding a title and displaying the plot
  plt.title(f'{dimension} {fact} Distribution')
  plt.ylabel('')  # To hide the y-label
  plt.show()

In [7]:
# function to get portfolio features

def get_portfolio_features(df_common_features):

  print_date_time()
  print('-------------------')

  #df_common_features["Target"] = df_common_features["Target"].fillna(df_common_features["Max"])
  df_common_features['NTT'] = np.where(df_common_features['Strategy']== 'NTT', df_common_features["Target"], df_common_features['Max'])
  df_common_features['LTT'] = np.where(df_common_features['Strategy']== 'BTT', df_common_features["Target"], df_common_features['Max'])
  df_common_features['BOL'] = df_common_features['Min']

  tmp_df = df_common_features[df_common_features['Symbol'].isin(mypf_df[mypf_df['InPortfolio'] != 'NA'].Symbol.values)]
  print('qualified stocks: '+str(len(tmp_df['Symbol'].unique())))
  tmp_df1 = tmp_df[tmp_df['LatestQtr'] == 1]
  print('with latest results: '+str(len(tmp_df1['Symbol'].unique())))
  tmp_df1 = tmp_df1[tmp_df1['StarStock'] == 1]
  print('still star stocks: '+str(len(tmp_df1['Symbol'].unique())))
  tmp_df['Investment'] = tmp_df['AvgCost'] * tmp_df['Shares']
  tmp_df['Current'] = round(tmp_df['Close'] * tmp_df['Shares'],0)
  tmp_df['Previous'] = tmp_df['Prev_Close'] * tmp_df['Shares']
  tmp_df['EstimatedST'] = tmp_df['NTT'] * tmp_df['Shares']
  tmp_df['EstimatedLT'] = tmp_df['LTT'] * tmp_df['Shares']
  tmp_df['Current P/L'] = round((tmp_df['Current'] - tmp_df['Investment']),0)
  tmp_df['Today P/L%'] = round((tmp_df['Current'] - tmp_df['Previous'])*100/tmp_df['Previous'],2)
  tmp_df['Current P/L%'] = round((tmp_df['Current'] - tmp_df['Investment'])*100/tmp_df['Investment'],2)
  tmp_df['EstimatedST P/L%'] = round((tmp_df['EstimatedST'] - tmp_df['Investment'])*100/tmp_df['Investment'],2)
  tmp_df['EstimatedLT P/L%'] = round((tmp_df['EstimatedLT'] - tmp_df['Investment'])*100/tmp_df['Investment'],2)
  tmp_df['NTT%'] = round((tmp_df['NTT'] - tmp_df['Close'])*100/tmp_df['Close'],2)
  tmp_df['LTT%'] = round((tmp_df['LTT'] - tmp_df['Close'])*100/tmp_df['Close'],2)
  tmp_df['Gained%'] = round((tmp_df['Close'] - tmp_df['BOL'])*100/tmp_df['BOL'],2)
  investment = round(sum(tmp_df['AvgCost']*tmp_df['Shares']),0)
  current = round(sum(tmp_df['Close']*tmp_df['Shares']),0)
  tmp_df['InitAlloc%'] = round(tmp_df['Investment']*100/investment,2)
  tmp_df['CurrAlloc%'] = round(tmp_df['Current']*100/current,2)
  tmp_df['FTT'] = tmp_df['LTT']
  tmp_df.loc[tmp_df['Strategy'] == 'NTT', 'FTT'] = tmp_df['NTT']
  tmp_df['FTT%'] = tmp_df['LTT%']
  tmp_df.loc[tmp_df['Strategy'] == 'NTT', 'FTT%'] = tmp_df['NTT%']
  tmp_df['FTT Amt'] = round(tmp_df['FTT%'] * tmp_df['Current']/100,0)
  tmp_df['OTT%'] = round((tmp_df['FTT'] - tmp_df['AvgCost'])*100/tmp_df['AvgCost'],2)
  tmp_df['RRR Ind'] = round(tmp_df['Current P/L']/tmp_df['FTT Amt'],2)
  tmp_df['Risk Ind'] = round(tmp_df['Current P/L%']*tmp_df['CurrAlloc%'],0)

  return tmp_df

# function to print portfolio features
def print_portfolio_stats(df_portfolio_features, myinvmt_df):
  from pyxirr import xirr

  total_booked_amt, reserve_amt, cy_booked_amt, py_booked_amt = get_amt()

  dates = myinvmt_df['Date'].values
  dates = np.append(dates, datetime.date.today().strftime('%d-%b-%y'))
  investment = myinvmt_df['Investment'].values
  dates= pd.to_datetime(dates)

  current = round(sum(df_portfolio_features['Close']*df_portfolio_features['Shares']),0) + reserve_amt
  investment_xirr = np.append(investment, current)
  cagr = round(xirr(pd.DataFrame({"dates": dates, "amounts": investment_xirr}))*100,2)

  investment = -sum(investment)
  invested = round(sum(df_portfolio_features['AvgCost']*df_portfolio_features['Shares']),0) + reserve_amt
  previous = round(sum(df_portfolio_features['Prev_Close']*df_portfolio_features['Shares']),0) + reserve_amt
  cy_invested = investment + py_booked_amt

  today_pnl_amount = current-previous
  today_pnl_percentage = round((current-previous)*100/previous,2)

  curr_pnl_amount = current-invested
  curr_pnl_percentage = round((curr_pnl_amount)*100/(cy_invested),2)

  cy_pnl_amount = cy_booked_amt + curr_pnl_amount
  cy_pnl_percentage = round((cy_pnl_amount)*100/cy_invested,2)

  overall_pnl_amount = total_booked_amt + curr_pnl_amount
  overall_pnl_percentage = round((overall_pnl_amount)*100/investment,2)

  estimate_st = round(sum(df_portfolio_features['FTT']*df_portfolio_features['Shares']),0)  + reserve_amt
  est_st_pnl_amount = estimate_st-current
  est_st_pnl_percentage = round((est_st_pnl_amount)*100/current,2)

  estimate_lt = round(sum(df_portfolio_features['LTT']*df_portfolio_features['Shares']),0)  + reserve_amt
  est_lt_pnl_amount = estimate_lt-current
  est_lt_pnl_percentage = round((est_lt_pnl_amount)*100/current,2)

  total_profit = round(sum(df_portfolio_features[df_portfolio_features['Current P/L%'] > 0]['Current']) - sum(df_portfolio_features[df_portfolio_features['Current P/L%'] > 0]['Investment']),0)
  total_loss = round(sum(df_portfolio_features[df_portfolio_features['Current P/L%'] < 0]['Current']) - sum(df_portfolio_features[df_portfolio_features['Current P/L%'] < 0]['Investment']),0)

  cy_booked_percentage = round((cy_booked_amt)*100/current,2)
  py_booked_percentage = round((py_booked_amt)*100/investment,2)
  total_booked_percentage = round((total_booked_amt)*100/investment,2)

  print('-------------------')
  print('Initial Investment: ', format_amt(investment))
  print('CY Investment: ', format_amt(cy_invested))
  print('Reserve: ', format_amt(reserve_amt))
  print('Current: ',  format_amt(current))
  print('-------------------')
  print('Today PnL: '+ '{} ({}%)'.format(format_amt(today_pnl_amount), today_pnl_percentage))
  print('Current PnL: '+ '{} ({}%)'.format(format_amt(curr_pnl_amount), curr_pnl_percentage))
  print('CY Booked + Current PnL: '+ '{} ({}%)'.format(format_amt(cy_pnl_amount), cy_pnl_percentage))
  print('-------------------')
  print('Total profit: ', format_amt(total_profit))
  print('Total loss: ', format_amt(total_loss))
  print('-------------------')
  print('Total Booked + Current PnL: '+ '{} ({}%)'.format(format_amt(overall_pnl_amount), overall_pnl_percentage))
  print('Total Booked PnL: '+ '{} ({}%)'.format(format_amt(total_booked_amt), total_booked_percentage))
  print('Curr Year Booked PnL: '+ '{} ({}%)'.format(format_amt(cy_booked_amt), cy_booked_percentage))
  print('Prev Year Booked PnL: '+ '{} ({}%)'.format(format_amt(py_booked_amt), py_booked_percentage))
  print('===================')
  print('Est FTT: ',  format_amt(estimate_st))
  print('Est FTT PnL: '+ '{} ({}%)'.format(format_amt(est_st_pnl_amount), est_st_pnl_percentage))

  print('===================')
  print('Deployed: ', format_amt(investment))

  print('Current: ', format_amt(current))

  print('CAGR/XIRR %: '+'{}%'.format(cagr))

In [8]:
# get start and end date
start_date, end_date = get_start_end_date()

# get portfolio and prospects data
mypfs_df = get_mypfs_df()
mypps_df = get_mypps_df()
myinvmt_df = get_myinvmt_df()

# merge above datasets
mypf_df = pd.merge(mypfs_df, mypps_df, on="Symbol")

# seggregate dm and sv portfolio
dm_pf = mypf_df[mypf_df['InPortfolio'] == 'DM']
sv_pf = mypf_df[mypf_df['InPortfolio'] == 'SV']

# build portfolio stock dataframe
dm_stocks = get_stock_ids(dm_pf)
sv_stocks = get_stock_ids(sv_pf)
df_stocks = pd.concat([dm_pf,sv_pf], ignore_index = True)

# arrange common and diff stock features
common_cols = ['Symbol', 'Target', 'Criteria', 'Strategy', 'CumlRnk', 'LatestQtr', 'StarStock', 'Conviction', 'Category', 'InFolio', 'XIRR', 'MBQ']
diff_cols = ['Symbol', 'AvgCost', 'Shares']
df_stocks = arrange_features(df_stocks, common_cols, diff_cols)

# get common features
stock_ids = df_stocks['Symbol'].values
df_common_features = get_common_features(stock_ids, df_stocks)

df_common_features.reset_index(drop=True, inplace=True)
df_common_features.drop(['Date'], axis=1, inplace=True)
# get and print portfolio features
df_portfolio_features = get_portfolio_features(df_common_features)

print_portfolio_stats(df_portfolio_features, myinvmt_df)

df = df_portfolio_features
#plot_pie_chart(df, 'CapType', 'Current')
list_ox40n = list(df[df['MBQ'].str.contains('OX40N', na=False)]['Symbol'].values)

Run date time (IST): 2026-08-20 15:05:41
-------------------
qualified stocks: 87
with latest results: 30
still star stocks: 19

-------------------
Initial Investment:  1.46 C
CY Investment:  1.89 C
Reserve:  3.69 L
Current:  1.58 C
-------------------
Today PnL: 59.27 K (0.38%)
Current PnL: -34.73 L (-18.38%)
CY Booked + Current PnL: -29.67 L (-15.7%)
-------------------
Total profit:  3.68 L
Total loss:  -38.40 L
-------------------
Total Booked + Current PnL: 13.20 L (9.04%)
Total Booked PnL: 47.93 L (32.82%)
Curr Year Booked PnL: 5.06 L (3.2%)
Prev Year Booked PnL: 42.87 L (29.35%)
===================
Est FTT:  2.67 C
Est FTT PnL: 1.09 C (68.82%)
===================
Deployed:  1.46 C
Current:  1.58 C
CAGR/XIRR %: 3.62%

In [9]:
# top 5 near their targets
cols = ['Symbol', 'Today P/L%', 'Current P/L%', 'FTT%', 'OTT%', 'FTT Amt', 'Current P/L', 'Current', 'FTT', 'Dev%_PE', 'RSI_14','Conviction', 'Spread%',  'CumlRnk', 'RRR Ind', 'CurrAlloc%', 'Gained%', 'Criteria', 'Strategy', 'Category']
df_tmp = df_portfolio_features[~df_portfolio_features['Symbol'].isin(['ENRIN','BLUSPRING','DIGITIDE'])]
df_tmp = df_tmp.sort_values(by = 'FTT Amt', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
66,SIEMENS,-0.17,4.57,5.98,10.83,11637.0,8510.0,194605.0,4125.00,-15.30,56.0,H-LC,14.08,51.0,0.73,1.26,37.30,AR,NTT,ELECTRICAL
78,UNITDSPR,1.05,13.13,6.75,20.77,17879.0,30736.0,264880.0,1644.00,-3.49,64.0,X-MC,11.36,64.0,1.72,1.71,27.33,X40N,NTT,BREWERIES
77,TTKPRESTIG,1.00,-23.18,30.30,0.09,23456.0,-23363.0,77414.0,770.00,-6.45,42.0,M-SC,9.42,250.0,-1.00,0.50,39.34,OX40N,NTT,DURABLES
52,M&M,1.02,8.94,9.07,18.82,23781.0,21511.0,262192.0,3762.88,-6.15,61.0,X-LC,4.90,25.0,0.90,1.70,18.94,X40N,ATH,AUTO
12,BOSCH-HCIL,0.47,-22.41,28.86,-0.01,28620.0,-28635.0,99170.0,2282.00,777.45,79.0,M-SC,9.29,231.0,-1.00,0.64,68.80,OX40N,BTT,AC

In [10]:
# top 5 today
df_tmp = df_portfolio_features.sort_values(by = 'Today P/L%', ascending=False)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
84,WHIRLPOOL,3.28,-37.63,191.70,81.92,137246.0,-43204.0,71594.0,2270.00,NaN,46.0,NaN,10.46,210.0,-0.31,0.46,3.28,XR,NTT,DURABLES
9,BANDHANBNK,3.11,-16.07,129.27,92.42,302220.0,-44769.0,233790.0,400.00,49.43,45.0,H-SC,11.64,174.0,-0.15,1.51,29.90,XY24,NTT,BANKS
16,CERA,3.07,-23.30,61.52,23.89,83002.0,-40985.0,134918.0,9475.00,NaN,42.0,NaN,12.86,153.0,-0.49,0.87,31.15,OX40N,NTT,CERAMICS
22,DIXON,2.61,8.11,27.57,37.92,77736.0,21162.0,281960.0,18931.72,-58.83,68.0,X-MC,15.80,54.0,0.27,1.82,53.42,X40N,ATH,IT
38,HYUNDAI,2.52,15.31,24.83,43.94,71960.0,38477.0,289809.0,2782.73,19.49,67.0,X-LC,5.69,29.0,0.53,1.88,33.06,X40N,ATH,AUTO

In [11]:
# bottom 5 today
df_tmp = df_portfolio_features.sort_values(by = 'Today P/L%', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
0,5PAISA,-3.85,-25.75,52.05,12.90,84446.0,-56256.0,162240.0,593.0,4.2,58.0,H-SC,11.61,170.0,-0.67,1.05,56.56,OX40N,NTT,FINANCE
59,RECLTD,-2.52,-11.07,35.77,20.74,64627.0,-22495.0,180675.0,446.0,-2.7,32.0,M-MC,2.40,191.0,-0.35,1.17,9.39,XY25,NTT,FINANCE
51,LAOPALA,-2.42,-46.69,160.92,39.09,112462.0,-61218.0,69887.0,464.0,NaN,42.0,NaN,3.88,154.0,-0.54,0.45,11.41,AR,NTT,CERAMICS
81,VALIANTORG,-2.02,-35.55,170.19,74.15,179467.0,-58154.0,105451.0,838.0,NaN,57.0,NaN,8.81,145.0,-0.32,0.68,56.93,XR,NTT,CHEMICALS
64,SFL,-1.61,-34.32,92.81,26.63,159833.0,-90003.0,172215.0,1287.0,NaN,37.0,NaN,19.47,242.0,-0.56,1.11,43.73,XY24,NTT,MISC

In [12]:
# top 5 to exit based on CumlRnk
df_tmp = df_portfolio_features[~df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])]
df_tmp = df_tmp[(df_tmp['Current P/L%'] > -1) & (df_tmp['Current P/L%'] < 1)].sort_values(by = 'CumlRnk', ascending=False)
df_tmp[cols].head()

Empty DataFrame
Columns: [Symbol, Today P/L%, Current P/L%, FTT%, OTT%, FTT Amt, Current P/L, Current, FTT, Dev%_PE, RSI_14, Conviction, Spread%, CumlRnk, RRR Ind, CurrAlloc%, Gained%, Criteria, Strategy, Category]
Index: []

In [13]:
# OX40N stocks to exit
df_tmp = df_portfolio_features[(df_portfolio_features['Symbol'].isin(list_ox40n))].sort_values(by = 'Current P/L%', ascending=False)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
25,FINCABLES,-0.44,65.66,25.51,107.91,62394.0,96943.0,244587.0,1641.55,20.71,73.0,M-SC,21.37,220.0,1.55,1.58,84.01,OX40N,ATH,CABLES
67,SIS,-0.27,-5.06,27.72,21.26,29222.0,-5615.0,105417.0,528.00,102.74,37.0,H-SC,20.47,168.0,-0.19,0.68,56.74,OX40N,NTT,MISC
43,INDIGOPNTS,-1.26,-19.42,24.13,0.02,33940.0,-33906.0,140653.0,1408.00,-23.14,58.0,M-SC,7.76,222.0,-1.00,0.91,59.58,OX40N,NTT,PAINTS
12,BOSCH-HCIL,0.47,-22.41,28.86,-0.01,28620.0,-28635.0,99170.0,2282.00,777.45,79.0,M-SC,9.29,231.0,-1.00,0.64,68.80,OX40N,BTT,AC
77,TTKPRESTIG,1.00,-23.18,30.30,0.09,23456.0,-23363.0,77414.0,770.00,-6.45,42.0,M-SC,9.42,250.0,-1.00,0.50,39.34,OX40N,NTT,DURABLES

In [14]:
# top 5 to book for rotation
df_tmp = df_portfolio_features[(df_portfolio_features['Current P/L%'] > 20) ].sort_values(by = 'CumlRnk', ascending=False)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
25,FINCABLES,-0.44,65.66,25.51,107.91,62394.0,96943.0,244587.0,1641.55,20.71,73.0,M-SC,21.37,220.0,1.55,1.58,84.01,OX40N,ATH,CABLES
27,GLAXO,-1.04,20.47,12.64,35.69,30345.0,40788.0,240072.0,3380.16,-9.68,82.0,X-MC,10.78,56.0,1.34,1.55,42.68,X40,ATH,PHARMA

In [15]:
# top 5 to monitor for exit
df_tmp = df_portfolio_features[~df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])]
df_tmp = df_tmp[(df_tmp['Current P/L%'] > 0) ].sort_values(by = 'Dev%_PE', ascending=False)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
25,FINCABLES,-0.44,65.66,25.51,107.91,62394.0,96943.0,244587.0,1641.55,20.71,73.0,M-SC,21.37,220.0,1.55,1.58,84.01,OX40N,ATH,CABLES
68,STARHEALTH,-1.12,11.51,32.06,47.26,100502.0,32357.0,313480.0,761.00,-1.59,45.0,H-SC,16.03,173.0,0.32,2.03,35.54,XY24,NTT,INSURANCE

In [16]:
# top 5 to book for rotation from weak conviction
df_tmp = df_portfolio_features[~df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])]
df_tmp = df_tmp[~df_tmp['Criteria'].isin(['XY25','XY24','X40', 'X40N'])].sort_values(by = 'RRR Ind', ascending=False)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
25,FINCABLES,-0.44,65.66,25.51,107.91,62394.0,96943.0,244587.0,1641.55,20.71,73.0,M-SC,21.37,220.0,1.55,1.58,84.01,OX40N,ATH,CABLES
3,ALKYLAMINE,-1.35,-17.82,134.29,92.54,111424.0,-17990.0,82973.0,4520.85,NaN,56.0,NaN,14.66,142.0,-0.16,0.54,57.56,SR,ATH,CHEMICALS
67,SIS,-0.27,-5.06,27.72,21.26,29222.0,-5615.0,105417.0,528.00,102.74,37.0,H-SC,20.47,168.0,-0.19,0.68,56.74,OX40N,NTT,MISC
42,INDIAMART,0.76,-24.91,167.56,100.92,155191.0,-30718.0,92618.0,4675.60,NaN,38.0,NaN,13.89,140.0,-0.20,0.60,0.76,AR,ATH,MISC
71,TANLA,0.28,-35.27,235.60,117.25,412953.0,-95484.0,175277.0,1922.32,NaN,46.0,NaN,15.58,147.0,-0.23,1.13,53.46,AR,ATH,IT

In [17]:
# top 5 to accumulate based on lowest RSI_14
df_tmp = df_portfolio_features[df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])].sort_values(by = 'RSI_14', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
56,PGHH,0.06,-38.22,113.69,32.01,149962.0,-81616.0,131904.0,17616.87,-54.65,28.0,X-SC,19.75,57.0,-0.54,0.85,0.06,X40,ATH,FMCG
55,PAGEIND,1.28,-6.91,42.72,32.85,106727.0,-18549.0,249830.0,50936.07,-30.81,32.0,X-MC,8.43,55.0,-0.17,1.62,19.30,X40,ATH,APPARELS
19,COLPAL,1.23,-27.75,93.59,39.86,178074.0,-73095.0,190270.0,3683.41,-12.49,33.0,X-MC,1.93,62.0,-0.41,1.23,7.63,XY25,ATH,FMCG
20,DABUR,0.07,-21.79,83.73,43.70,162456.0,-54044.0,194024.0,735.00,-32.48,33.0,X-MC,10.26,70.0,-0.33,1.26,0.08,XY24,BTT,FMCG
75,TMPV,-0.76,-24.14,88.18,42.75,278351.0,-100445.0,315662.0,600.00,-84.91,34.0,X-LC,4.61,4.0,-0.36,2.04,8.54,XY24,NTT,AUTO

In [18]:
# top 5 to accumulate based on Spread and CumlRnk
df_tmp = df_portfolio_features[df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])]
df_tmp = df_tmp[(df_tmp['CumlRnk'] < 100)].sort_values(by = 'Spread%', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
19,COLPAL,1.23,-27.75,93.59,39.86,178074.0,-73095.0,190270.0,3683.41,-12.49,33.0,X-MC,1.93,62.0,-0.41,1.23,7.63,XY25,ATH,FMCG
50,KOTAKBANK,2.09,4.71,13.57,18.92,34060.0,11290.0,250992.0,452.46,-11.48,58.0,X-LC,2.16,12.0,0.33,1.62,12.93,X40,ATH,BANKS
23,DMART,-0.04,-3.39,36.03,31.42,108532.0,-10564.0,301226.0,5391.45,-19.00,45.0,X-LC,2.40,14.0,-0.10,1.95,8.70,X40N,ATH,FMCG
1,ABBOTINDIA,-0.91,-12.22,31.44,15.37,49358.0,-21865.0,156990.0,34390.26,-28.62,35.0,X-MC,3.63,58.0,-0.44,1.02,6.34,X40,ATH,PHARMA
26,GILLETTE,0.17,-11.17,46.04,29.72,103832.0,-28371.0,225525.0,10978.86,-35.84,37.0,X-SC,3.75,83.0,-0.27,1.46,3.64,X40,ATH,FMCG

In [19]:
# top 5 to accumulate based on lowest Gained%
df_tmp = df_portfolio_features[df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])].sort_values(by = 'Gained%', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
56,PGHH,0.06,-38.22,113.69,32.01,149962.0,-81616.0,131904.0,17616.87,-54.65,28.0,X-SC,19.75,57.0,-0.54,0.85,0.06,X40,ATH,FMCG
20,DABUR,0.07,-21.79,83.73,43.70,162456.0,-54044.0,194024.0,735.00,-32.48,33.0,X-MC,10.26,70.0,-0.33,1.26,0.08,XY24,BTT,FMCG
83,VOLTAS,0.21,-4.12,51.44,45.20,94567.0,-7902.0,183840.0,1856.00,32.05,36.0,X-MC,4.78,79.0,-0.08,1.19,0.76,XY25,NTT,AC
34,HDFCBANK,0.75,-11.40,47.92,31.05,124445.0,-33427.0,259693.0,1073.00,-28.50,36.0,X-LC,12.90,26.0,-0.27,1.68,0.80,X40,BTT,BANKS
35,HDFCLIFE,0.84,-7.26,50.04,39.15,116365.0,-18193.0,232544.0,811.41,-31.77,44.0,X-LC,16.57,31.0,-0.16,1.50,0.92,X40,ATH,INSURANCE

In [20]:
# top 5 to accumulate based on lowest CurrAlloc%
df_tmp = df_portfolio_features[df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])].sort_values(by = 'CurrAlloc%', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
56,PGHH,0.06,-38.22,113.69,32.01,149962.0,-81616.0,131904.0,17616.87,-54.65,28.0,X-SC,19.75,57.0,-0.54,0.85,0.06,X40,ATH,FMCG
2,ACC,0.99,-41.76,200.14,74.81,312555.0,-111960.0,156168.0,3906.00,-42.24,38.0,X-SC,11.72,85.0,-0.36,1.01,4.33,XY24,BTT,CEMENT
1,ABBOTINDIA,-0.91,-12.22,31.44,15.37,49358.0,-21865.0,156990.0,34390.26,-28.62,35.0,X-MC,3.63,58.0,-0.44,1.02,6.34,X40,ATH,PHARMA
40,ICICIPRULI,0.90,-16.60,56.20,30.28,92339.0,-32701.0,164304.0,787.27,-46.58,49.0,X-MC,12.34,78.0,-0.35,1.06,9.47,X40,ATH,INSURANCE
39,ICICIGI,0.91,-13.64,37.66,18.89,65085.0,-27287.0,172822.0,2244.41,-13.82,43.0,X-MC,10.22,66.0,-0.42,1.12,2.96,X40,ATH,INSURANCE

In [21]:
# top 5 to accumulate based on CumlRnk
df_tmp = df_portfolio_features.sort_values(by = 'CumlRnk', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
47,ITC,1.39,-25.31,66.94,24.70,198639.0,-100536.0,296742.0,452.00,-30.35,36.0,X-LC,10.56,1.0,-0.51,1.92,1.39,X40,NTT,FMCG
73,TCS,0.13,-32.72,84.59,24.20,263677.0,-151561.0,311712.0,4230.71,-43.98,47.0,X-LC,14.04,2.0,-0.57,2.02,16.24,X40,ATH,IT
45,INFY,0.85,-19.61,74.62,40.38,225839.0,-73818.0,302652.0,1972.00,-40.86,49.0,X-LC,15.69,3.0,-0.33,1.96,14.61,X40,NTT,IT
75,TMPV,-0.76,-24.14,88.18,42.75,278351.0,-100445.0,315662.0,600.00,-84.91,34.0,X-LC,4.61,4.0,-0.36,2.04,8.54,XY24,NTT,AUTO
33,HCLTECH,-0.17,-11.54,40.15,23.97,109914.0,-35728.0,273758.0,1853.42,-13.84,55.0,X-LC,10.95,8.0,-0.33,1.77,29.18,X40,ATH,IT

In [22]:
# top 5 for average up
df_tmp = df_portfolio_features[(df_portfolio_features['Dev%_200'] > 5)].sort_values(by = 'CurrAlloc%', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
44,INDUSINDBK,-1.13,-25.79,79.07,32.89,45304.0,-19910.0,57296.0,1800.00,321.65,50.0,L-MC,12.92,258.0,-0.44,0.37,41.26,XR,NTT,BANKS
3,ALKYLAMINE,-1.35,-17.82,134.29,92.54,111424.0,-17990.0,82973.0,4520.85,NaN,56.0,NaN,14.66,142.0,-0.16,0.54,57.56,SR,ATH,CHEMICALS
12,BOSCH-HCIL,0.47,-22.41,28.86,-0.01,28620.0,-28635.0,99170.0,2282.00,777.45,79.0,M-SC,9.29,231.0,-1.00,0.64,68.80,OX40N,BTT,AC
67,SIS,-0.27,-5.06,27.72,21.26,29222.0,-5615.0,105417.0,528.00,102.74,37.0,H-SC,20.47,168.0,-0.19,0.68,56.74,OX40N,NTT,MISC
81,VALIANTORG,-2.02,-35.55,170.19,74.15,179467.0,-58154.0,105451.0,838.00,NaN,57.0,NaN,8.81,145.0,-0.32,0.68,56.93,XR,NTT,CHEMICALS

In [23]:
# top 5 RSP
df_tmp = df_portfolio_features.sort_values(by = 'RSP', ascending=False)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
12,BOSCH-HCIL,0.47,-22.41,28.86,-0.01,28620.0,-28635.0,99170.0,2282.00,777.45,79.0,M-SC,9.29,231.0,-1.00,0.64,68.80,OX40N,BTT,AC
25,FINCABLES,-0.44,65.66,25.51,107.91,62394.0,96943.0,244587.0,1641.55,20.71,73.0,M-SC,21.37,220.0,1.55,1.58,84.01,OX40N,ATH,CABLES
27,GLAXO,-1.04,20.47,12.64,35.69,30345.0,40788.0,240072.0,3380.16,-9.68,82.0,X-MC,10.78,56.0,1.34,1.55,42.68,X40,ATH,PHARMA
81,VALIANTORG,-2.02,-35.55,170.19,74.15,179467.0,-58154.0,105451.0,838.00,NaN,57.0,NaN,8.81,145.0,-0.32,0.68,56.93,XR,NTT,CHEMICALS
38,HYUNDAI,2.52,15.31,24.83,43.94,71960.0,38477.0,289809.0,2782.73,19.49,67.0,X-LC,5.69,29.0,0.53,1.88,33.06,X40N,ATH,AUTO

In [24]:
# Top N allocation
df_tmp = df_portfolio_features.sort_values(by = 'CurrAlloc%', ascending=False)
top_n_values = [10, 25, 50]

sum_df = pd.DataFrame({
    'Top_N': top_n_values,
    'Sum_Alloc%': [df_tmp['CurrAlloc%'].head(n).sum() for n in top_n_values]
})

sum_df

   Top_N  Sum_Alloc%
0     10       19.71
1     25       45.07
2     50       77.65

In [25]:
# market-cap-wise allocation
df_tmp = df_portfolio_features[cols]
df_tmp.groupby(df_tmp['Conviction'].str[-2:])['CurrAlloc%'].sum().sort_values(ascending=False)

Conviction
LC    38.09
MC    22.24
SC    21.54
Name: CurrAlloc%, dtype: float64

In [26]:
# criteria-wise allocation
df_portfolio_features.groupby('Criteria')['CurrAlloc%'].sum().sort_values(ascending=False)

Criteria
X40      26.69
XY24     23.93
X40N     18.77
XR        9.12
OX40N     7.34
XY25      7.17
AR        6.08
SR        0.87
Name: CurrAlloc%, dtype: float64

In [27]:
# conviction-wise allocation
df_portfolio_features.groupby('Conviction')['CurrAlloc%'].sum().sort_values(ascending=False)

Conviction
X-LC    34.43
X-MC    19.67
H-SC     8.49
X-SC     7.61
M-SC     5.44
H-LC     2.85
M-MC     1.17
H-MC     1.03
M-LC     0.81
L-MC     0.37
Name: CurrAlloc%, dtype: float64

In [28]:
# sector-wise stats
df_tmp = df_portfolio_features.groupby('Category')[['CurrAlloc%', 'Current', 'Current P/L', 'FTT Amt']].sum().sort_values(by=['Current', 'Current P/L'], ascending=False)
df_tmp['Current P/L%'] = round(df_tmp['Current P/L'] * 100 / df_tmp['Current'], 2)
df_tmp['FTT%'] = round(df_tmp['FTT Amt'] * 100 / df_tmp['Current'], 2)
cols = ['CurrAlloc%', 'Current P/L%', 'FTT%']
df_tmp[cols].sort_values(by=['CurrAlloc%'], ascending=False)

               CurrAlloc%  Current P/L%    FTT%
Category
FMCG                15.42        -25.15   70.15
IT                  11.23        -37.24  105.30
FINANCE             10.75        -16.10   66.12
AUTO                 8.30         -5.48   43.26
BANKS                6.20        -11.26   59.25
MISC                 5.91        -35.09   89.43
PHARMA               5.87          8.60   17.32
INSURANCE            5.71         -5.19   42.38
PAINTS               5.45        -17.05   37.01
ELECTRICAL           4.18         -9.60   43.92
AC                   1.83        -12.91   43.53
REFINERIES           1.73        -11.26   48.63
BREWERIES            1.71         11.60    6.75
FOOTWEAR             1.66        -72.01  140.98
APPARELS             1.62         -7.42   42.72
CABLES               1.58         39.64   25.51
DURABLES             1.48        -68.46  109.44
TRAVEL               1.41       -105.34  208.16
CERAMICS             1.32        -49.90   95.44
ENGINEERING          1.25        -25.18   82.43
CHEMICALS            1.22        -40.41  154.38
CEMENT               1.01        -71.69  200.14
JEWELLERY            0.97       -115.05  189.77
ENTERTAINMENT        0.70        -79.35  186.31
HEALTHCARE           0.70        -68.48  110.76
TEXTILES             0.39        -51.46   94.65
HOTELS               0.37       -100.82  171.65

In [29]:
# money to be made criteria-wise
df_portfolio_features.groupby('Criteria')['FTT Amt'].agg(['sum', 'count']).sort_values(by='sum', ascending=False)

                sum  count
Criteria
XY24      3629046.0     19
X40       2098402.0     18
XR        1385299.0     13
X40N      1180418.0     12
AR        1066593.0      8
OX40N      655853.0     10
XY25       590947.0      5
SR         281892.0      2

In [30]:
# money to be made conviction-wise
df_portfolio_features.groupby('Conviction')['FTT Amt'].agg(['sum', 'count']).sort_values(by='sum', ascending=False)

                  sum  count
Conviction
X-LC        2405942.0     19
X-MC        1461441.0     14
X-SC        1103229.0      6
H-SC         837163.0      8
M-SC         322761.0      6
H-MC         255278.0      1
M-LC         166269.0      1
M-MC          64627.0      1
H-LC          49918.0      2
L-MC          45304.0      1

In [31]:
# money to be made criteria and conviction-wise
df_portfolio_features.groupby(['Conviction', 'Criteria'])['FTT Amt'].agg(['sum', 'count']).sort_values(by='sum', ascending=False)

                           sum  count
Conviction Criteria
X-LC       X40       1221474.0      9
X-SC       XY24       675669.0      2
H-SC       XY24       527732.0      3
X-MC       X40        508330.0      6
X-LC       XY24       462112.0      2
X-MC       X40N       447004.0      4
X-LC       X40N       409133.0      5
X-MC       XY25       272641.0      2
H-MC       XY24       255278.0      1
X-SC       X40        253794.0      2
X-LC       XY25       253679.0      2
X-MC       XY24       233466.0      2
H-SC       OX40N      217839.0      3
X-SC       X40N       173766.0      2
M-LC       XR         166269.0      1
M-SC       OX40N      148410.0      4
           XY24       116700.0      1
H-SC       XR          91592.0      2
M-MC       XY25        64627.0      1
X-LC       XR          59544.0      1
M-SC       XR          57651.0      1
H-LC       AR          49918.0      2
L-MC       XR          45304.0      1

In [32]:
# notebook execution time

end_time = time.time()
execution_time = round(end_time - start_time, 0)
print(f"Notebook execution time: {execution_time} seconds")

Notebook execution time: 82.0 seconds