<a href="https://colab.research.google.com/github/ankit-rathi/Quantvesting_v2/blob/main/myStocks_Portfolio_Analysis.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
'''
!pip install pandas==2.2.2 -qq
!pip install pyxirr -qq
!pip install ta -qq
!pip install yfinance==0.2.59 -qq
'''

'\n!pip install pandas==2.2.2 -qq\n!pip install pyxirr -qq\n!pip install ta -qq\n!pip install yfinance==0.2.59 -qq\n'

In [2]:
# import libraries

import numpy as np
import pandas as pd
import datetime
import warnings
warnings.filterwarnings('ignore')
import yfinance as yfin
import ta
import matplotlib.pyplot as plt
import requests

In [3]:
# notebook start time
import time
import datetime
import pytz

start_time = time.time()

# function to print date timestamp
def print_date_time():
  tz_NY = pytz.timezone('Asia/Kolkata')
  datetime_NY = datetime.datetime.now(tz_NY)
  print("Run date time (IST):", datetime_NY.strftime("%Y-%m-%d %H:%M:%S"))

In [4]:
# function to get booked and reserved amount
def get_amt():
  # fetch the JSON data from the URL
  url = "https://raw.githubusercontent.com/ankit-rathi/Tradevesting_v1/main/data/myPortfolioAmts.json"
  response = requests.get(url)
  pf_amts = response.json()  # parse the JSON data

  # extract values from the JSON
  py_booked_amt_dm = pf_amts["py_booked_amt_dm"]
  py_booked_amt_sv = pf_amts["py_booked_amt_sv"]
  cy_booked_amt_dm = pf_amts["cy_booked_amt_dm"]
  cy_booked_amt_sv = pf_amts["cy_booked_amt_sv"]
  reserve_amt_dm = pf_amts["reserve_amt_dm"]
  reserve_amt_sv = pf_amts["reserve_amt_sv"]

  # perform calculations
  py_booked_amt = py_booked_amt_dm + py_booked_amt_sv
  cy_booked_amt = cy_booked_amt_dm + cy_booked_amt_sv
  reserve_amt = reserve_amt_dm + reserve_amt_sv
  total_booked_amt = py_booked_amt + cy_booked_amt

  return total_booked_amt, reserve_amt, cy_booked_amt, py_booked_amt

gen_output = 0

In [5]:
# function to format the amount
def format_amt(number):
    abs_number = abs(number)

    if abs_number >= 1_00_00_000:  # Crores
        formatted_amt = f"{number / 1_00_00_000:.2f} C"
    elif abs_number >= 1_00_000:  # Lakhs
        formatted_amt = f"{number / 1_00_000:.2f} L"
    elif abs_number >= 1_000:  # Thousands
        formatted_amt = f"{number / 1_000:.2f} K"
    else:
        formatted_amt = f"{number:.2f}"

    return formatted_amt

# function to set start and end date
def get_start_end_date():
  start_date = (datetime.date.today() + datetime.timedelta(days=-365)).strftime('%Y-%m-%d')
  end_date = (datetime.date.today() + datetime.timedelta(days=1)).strftime('%Y-%m-%d')
  return start_date, end_date

# function to fetch my portfolio csv
def get_mypfs_df():
  mypfs_df = pd.read_csv('https://raw.githubusercontent.com/ankit-rathi/Tradevesting_v1/main/data/myPortfolioStocks.csv')
  return mypfs_df

# function to fetch my prospects csv
def get_mypps_df():
  mypps_df = pd.read_csv('https://raw.githubusercontent.com/ankit-rathi/Tradevesting_v1/main/data/myProspectsScrips.csv')
  return mypps_df

# function to fetch screener data
def get_myscreen_df():
  myscreen_df = pd.read_csv('https://raw.githubusercontent.com/ankit-rathi/Tradevesting_v1/main/data/myScreenerDB.csv')
  return myscreen_df

# function to fetch momentum data
def get_myinvmt_df():
  myinvmt_df = pd.read_csv('https://raw.githubusercontent.com/ankit-rathi/Tradevesting_v1/main/data/myInvestments.csv')
  return myinvmt_df

# function to get the stock ids
def get_stock_ids(df_pf):
  stock_n100 = df_pf['Symbol'].unique()

  exclude = ['CADILAHC','MMTC', 'MASFIN']

  stock_ids = df_pf[~df_pf['Symbol'].isin(exclude) ]['Symbol'].unique()

  #mypf = mypf[mypf.Forecast.notnull()]
  #stock_ids = mypf['Symbol'].unique()

  #stock_ids.sort()
  return stock_ids

# get features from screener data
def get_screener_features():
  myscreen_df = get_myscreen_df()
  cols = ['Symbol', 'EPS', 'MedPE', 'ROCE%', 'ROE%', 'CapType']
  return myscreen_df[cols]

# get relative strength
def get_relative_strength(stock_list):

    # Dictionary to store stock tickers and their corresponding percentage price change
    stock_changes = {}

    # Loop through each stock and fetch its price data
    for stock in stock_list:
        try:
            # Download the stock data for the given date range
            stock_data = yfin.Ticker(stock + '.NS').history(period='1mo', interval='1d')[map(str.title, ['open', 'close', 'low', 'high', 'volume'])]

            # Calculate the percentage change for the stock
            if len(stock_data) > 0:
                start_price = stock_data['Close'].iloc[0]
                end_price = stock_data['Close'].iloc[-1]
                percent_change = round(((end_price - start_price) / start_price) * 100, 2)
                stock_changes[stock] = percent_change
            else:
                stock_changes[stock] = np.nan  # If no data is available, set to NaN

        except Exception as e:
            print(f"Error fetching data for {stock}: {e}")
            stock_changes[stock] = np.nan

    # Create a DataFrame with stock tickers and their percentage changes
    df = pd.DataFrame(list(stock_changes.items()), columns=['Symbol', 'Percent_Change'])

    # Drop any stocks with missing data (NaN values)
    df = df.dropna()

    # Calculate the percentile rank based on percentage change
    df['RSP'] = round(df['Percent_Change'].rank(pct=True) * 100, 2)
    cols = ['Symbol', 'RSP']
    df = df[cols]
    # Sort by percentile rank (optional)
    df = df.sort_values(by='RSP', ascending=False).reset_index(drop=True)

    return df

In [6]:
# function to get stock technicals
def stock_prec_dev(stock_symbol):
    #stock_symbol = 'ULTRACEMCO.NS'
    short_window = 20
    mid_window = 50
    long_window = 200
    moving_avg = 'SMA'

    start = datetime.datetime(*map(int, start_date.split('-')))
    end = datetime.datetime(*map(int, end_date.split('-')))

    stock_df = yfin.Ticker(stock_symbol + '.NS').history(period='max', interval='1d')[map(str.title, ['open', 'close', 'low', 'high', 'volume'])]

    stock_df['Max'] = round(max(stock_df['Close']),2)
    stock_df = stock_df[(stock_df.index <= end_date) & (stock_df.index >= start_date)]
    stock_df['200_SMA'] = round(stock_df['Close'].rolling(window = 200, min_periods = 1).mean(),0)
    stock_df['Dev%_200'] = round((stock_df['Close'] - stock_df['200_SMA'])*100/stock_df['200_SMA'],2)
    stock_df.dropna(axis = 0, inplace = True) # remove any null rows

    stock_df['20_SMA'] = stock_df['Close'].rolling(window=20).mean()
    stock_df['50_SMA'] = stock_df['Close'].rolling(window=50).mean()
    stock_df['Symbol'] = stock_symbol

    stock_df['Close'] = round(stock_df['Close'],2)
    stock_df['Min'] = round(min(stock_df['Close']),2)
    stock_df['RSI_14'] = ta.momentum.RSIIndicator(close=stock_df['Close'], window=14).rsi()
    stock_df['RSI_14'] = round(stock_df['RSI_14'],0)
    stock_df['Prev_Close'] = stock_df['Close'].shift(1)
    stock_df.drop(['Open', 'Low', 'High', 'Volume'], axis=1, inplace=True)
    stock_df = stock_df.tail(1)

    max_SMA = max(stock_df['20_SMA'].item(), stock_df['50_SMA'].item(), stock_df['200_SMA'].item())
    min_SMA = min(stock_df['20_SMA'].item(), stock_df['50_SMA'].item(), stock_df['200_SMA'].item())
    ABS_Spread = max_SMA - min_SMA
    stock_df['Spread%'] = round((ABS_Spread / stock_df['200_SMA'].item()) * 100,2)

    return stock_df

# function to compute stock attributes
def get_common_features(stock_ids, df_mypf):

  df_prec_dev = pd.DataFrame()
  df_tmp = get_screener_features()
  df_rs = get_relative_strength(stock_ids)

  for stock_id in stock_ids:
      tmp = stock_prec_dev(stock_id)
      tmp = tmp.reset_index()
      df_prec_dev = pd.concat([df_prec_dev, tmp], ignore_index = True)
  df_prec_dev = pd.merge(df_prec_dev, df_mypf, on= 'Symbol')
  df_prec_dev = pd.merge(df_prec_dev, df_tmp, on= 'Symbol', how='left')
  df_prec_dev = pd.merge(df_prec_dev, df_rs, on= 'Symbol', how='left')
  #print(df_prec_dev.columns)
  df_prec_dev['Curr_PE'] = round(df_prec_dev['Close']/df_prec_dev['EPS'],1)
  df_prec_dev['Dev%_PE'] = round((df_prec_dev['Curr_PE'] - df_prec_dev['MedPE'])*100/df_prec_dev['MedPE'],2)
  df_prec_dev['Conviction'] = df_prec_dev['Conviction'] + '-' + df_prec_dev['CapType']
  return df_prec_dev

# function to arrange stock features
def arrange_features(df_stocks, common_cols, diff_cols):
  df_stocks_common = df_stocks[common_cols].drop_duplicates()
  df_stocks_diff = df_stocks[diff_cols]
  df_stocks_diff['Investment'] = df_stocks_diff['AvgCost'] * df_stocks_diff['Shares']
  df_stocks_diff = df_stocks_diff.groupby(['Symbol'])[['Shares', 'Investment']].aggregate(['sum']).reset_index()
  df_stocks_diff.columns = ['Symbol', 'Shares', 'Investment']
  df_stocks_diff['AvgCost'] = round(df_stocks_diff['Investment']/df_stocks_diff['Shares'],2)
  df_stocks = pd.merge(df_stocks_diff, df_stocks_common, on='Symbol')
  return df_stocks

# plot fact distribution across dimension
def plot_pie_chart(df, dimension, fact):
  # grouping the data by category and calculating the sum of fact for each type
  grouped_data = df.groupby(dimension)[fact].sum()

  # sorting the grouped data in descending order
  grouped_data = grouped_data.sort_values(ascending=False)

  # creating a pie chart
  grouped_data.plot.pie(autopct='%1.1f%%', startangle=90, figsize=(6, 6))

  # adding a title and displaying the plot
  plt.title(f'{dimension} {fact} Distribution')
  plt.ylabel('')  # To hide the y-label
  plt.show()

In [7]:
# function to get portfolio features

def get_portfolio_features(df_common_features):

  print_date_time()
  print('-------------------')

  #df_common_features["Target"] = df_common_features["Target"].fillna(df_common_features["Max"])
  df_common_features['NTT'] = np.where(df_common_features['Strategy']== 'NTT', df_common_features["Target"], df_common_features['Max'])
  df_common_features['LTT'] = np.where(df_common_features['Strategy']== 'BTT', df_common_features["Target"], df_common_features['Max'])
  df_common_features['BOL'] = df_common_features['Min']

  tmp_df = df_common_features[df_common_features['Symbol'].isin(mypf_df[mypf_df['InPortfolio'] != 'NA'].Symbol.values)]
  print('qualified stocks: '+str(len(tmp_df['Symbol'].unique())))
  tmp_df1 = tmp_df[tmp_df['LatestQtr'] == 1]
  print('with latest results: '+str(len(tmp_df1['Symbol'].unique())))
  tmp_df1 = tmp_df1[tmp_df1['StarStock'] == 1]
  print('still star stocks: '+str(len(tmp_df1['Symbol'].unique())))
  tmp_df['Investment'] = tmp_df['AvgCost'] * tmp_df['Shares']
  tmp_df['Current'] = round(tmp_df['Close'] * tmp_df['Shares'],0)
  tmp_df['Previous'] = tmp_df['Prev_Close'] * tmp_df['Shares']
  tmp_df['EstimatedST'] = tmp_df['NTT'] * tmp_df['Shares']
  tmp_df['EstimatedLT'] = tmp_df['LTT'] * tmp_df['Shares']
  tmp_df['Current P/L'] = round((tmp_df['Current'] - tmp_df['Investment']),0)
  tmp_df['Today P/L%'] = round((tmp_df['Current'] - tmp_df['Previous'])*100/tmp_df['Previous'],2)
  tmp_df['Current P/L%'] = round((tmp_df['Current'] - tmp_df['Investment'])*100/tmp_df['Investment'],2)
  tmp_df['EstimatedST P/L%'] = round((tmp_df['EstimatedST'] - tmp_df['Investment'])*100/tmp_df['Investment'],2)
  tmp_df['EstimatedLT P/L%'] = round((tmp_df['EstimatedLT'] - tmp_df['Investment'])*100/tmp_df['Investment'],2)
  tmp_df['NTT%'] = round((tmp_df['NTT'] - tmp_df['Close'])*100/tmp_df['Close'],2)
  tmp_df['LTT%'] = round((tmp_df['LTT'] - tmp_df['Close'])*100/tmp_df['Close'],2)
  tmp_df['Gained%'] = round((tmp_df['Close'] - tmp_df['BOL'])*100/tmp_df['BOL'],2)
  investment = round(sum(tmp_df['AvgCost']*tmp_df['Shares']),0)
  current = round(sum(tmp_df['Close']*tmp_df['Shares']),0)
  tmp_df['InitAlloc%'] = round(tmp_df['Investment']*100/investment,2)
  tmp_df['CurrAlloc%'] = round(tmp_df['Current']*100/current,2)
  tmp_df['FTT'] = tmp_df['LTT']
  tmp_df.loc[tmp_df['Strategy'] == 'NTT', 'FTT'] = tmp_df['NTT']
  tmp_df['FTT%'] = tmp_df['LTT%']
  tmp_df.loc[tmp_df['Strategy'] == 'NTT', 'FTT%'] = tmp_df['NTT%']
  tmp_df['FTT Amt'] = round(tmp_df['FTT%'] * tmp_df['Current']/100,0)
  tmp_df['OTT%'] = round((tmp_df['FTT'] - tmp_df['AvgCost'])*100/tmp_df['AvgCost'],2)
  tmp_df['RRR Ind'] = round(tmp_df['Current P/L']/tmp_df['FTT Amt'],2)
  tmp_df['Risk Ind'] = round(tmp_df['Current P/L%']*tmp_df['CurrAlloc%'],0)

  return tmp_df

# function to print portfolio features
def print_portfolio_stats(df_portfolio_features, myinvmt_df):
  from pyxirr import xirr

  total_booked_amt, reserve_amt, cy_booked_amt, py_booked_amt = get_amt()

  dates = myinvmt_df['Date'].values
  dates = np.append(dates, datetime.date.today().strftime('%d-%b-%y'))
  investment = myinvmt_df['Investment'].values
  dates= pd.to_datetime(dates)

  current = round(sum(df_portfolio_features['Close']*df_portfolio_features['Shares']),0) + reserve_amt
  investment_xirr = np.append(investment, current)
  cagr = round(xirr(pd.DataFrame({"dates": dates, "amounts": investment_xirr}))*100,2)

  investment = -sum(investment)
  invested = round(sum(df_portfolio_features['AvgCost']*df_portfolio_features['Shares']),0) + reserve_amt
  previous = round(sum(df_portfolio_features['Prev_Close']*df_portfolio_features['Shares']),0) + reserve_amt
  cy_invested = investment + py_booked_amt

  today_pnl_amount = current-previous
  today_pnl_percentage = round((current-previous)*100/previous,2)

  curr_pnl_amount = current-invested
  curr_pnl_percentage = round((curr_pnl_amount)*100/(cy_invested),2)

  cy_pnl_amount = cy_booked_amt + curr_pnl_amount
  cy_pnl_percentage = round((cy_pnl_amount)*100/cy_invested,2)

  overall_pnl_amount = total_booked_amt + curr_pnl_amount
  overall_pnl_percentage = round((overall_pnl_amount)*100/investment,2)

  estimate_st = round(sum(df_portfolio_features['FTT']*df_portfolio_features['Shares']),0)  + reserve_amt
  est_st_pnl_amount = estimate_st-current
  est_st_pnl_percentage = round((est_st_pnl_amount)*100/current,2)

  estimate_lt = round(sum(df_portfolio_features['LTT']*df_portfolio_features['Shares']),0)  + reserve_amt
  est_lt_pnl_amount = estimate_lt-current
  est_lt_pnl_percentage = round((est_lt_pnl_amount)*100/current,2)

  total_profit = round(sum(df_portfolio_features[df_portfolio_features['Current P/L%'] > 0]['Current']) - sum(df_portfolio_features[df_portfolio_features['Current P/L%'] > 0]['Investment']),0)
  total_loss = round(sum(df_portfolio_features[df_portfolio_features['Current P/L%'] < 0]['Current']) - sum(df_portfolio_features[df_portfolio_features['Current P/L%'] < 0]['Investment']),0)

  cy_booked_percentage = round((cy_booked_amt)*100/current,2)
  py_booked_percentage = round((py_booked_amt)*100/investment,2)
  total_booked_percentage = round((total_booked_amt)*100/investment,2)

  print('-------------------')
  print('Initial Investment: ', format_amt(investment))
  print('CY Investment: ', format_amt(cy_invested))
  print('Reserve: ', format_amt(reserve_amt))
  print('Current: ',  format_amt(current))
  print('-------------------')
  print('Today PnL: '+ '{} ({}%)'.format(format_amt(today_pnl_amount), today_pnl_percentage))
  print('Current PnL: '+ '{} ({}%)'.format(format_amt(curr_pnl_amount), curr_pnl_percentage))
  print('CY Booked + Current PnL: '+ '{} ({}%)'.format(format_amt(cy_pnl_amount), cy_pnl_percentage))
  print('-------------------')
  print('Total profit: ', format_amt(total_profit))
  print('Total loss: ', format_amt(total_loss))
  print('-------------------')
  print('Total Booked + Current PnL: '+ '{} ({}%)'.format(format_amt(overall_pnl_amount), overall_pnl_percentage))
  print('Total Booked PnL: '+ '{} ({}%)'.format(format_amt(total_booked_amt), total_booked_percentage))
  print('Curr Year Booked PnL: '+ '{} ({}%)'.format(format_amt(cy_booked_amt), cy_booked_percentage))
  print('Prev Year Booked PnL: '+ '{} ({}%)'.format(format_amt(py_booked_amt), py_booked_percentage))
  print('===================')
  print('Est FTT: ',  format_amt(estimate_st))
  print('Est FTT PnL: '+ '{} ({}%)'.format(format_amt(est_st_pnl_amount), est_st_pnl_percentage))

  print('===================')
  print('Deployed: ', format_amt(investment))

  print('Current: ', format_amt(current))

  print('CAGR/XIRR %: '+'{}%'.format(cagr))

In [8]:
# get start and end date
start_date, end_date = get_start_end_date()

# get portfolio and prospects data
mypfs_df = get_mypfs_df()
mypps_df = get_mypps_df()
myinvmt_df = get_myinvmt_df()

# merge above datasets
mypf_df = pd.merge(mypfs_df, mypps_df, on="Symbol")

# seggregate dm and sv portfolio
dm_pf = mypf_df[mypf_df['InPortfolio'] == 'DM']
sv_pf = mypf_df[mypf_df['InPortfolio'] == 'SV']

# build portfolio stock dataframe
dm_stocks = get_stock_ids(dm_pf)
sv_stocks = get_stock_ids(sv_pf)
df_stocks = pd.concat([dm_pf,sv_pf], ignore_index = True)

# arrange common and diff stock features
common_cols = ['Symbol', 'Target', 'Criteria', 'Strategy', 'CumlRnk', 'LatestQtr', 'StarStock', 'Conviction', 'Category', 'InFolio', 'XIRR', 'MBQ']
diff_cols = ['Symbol', 'AvgCost', 'Shares']
df_stocks = arrange_features(df_stocks, common_cols, diff_cols)

# get common features
stock_ids = df_stocks['Symbol'].values
df_common_features = get_common_features(stock_ids, df_stocks)

df_common_features.reset_index(drop=True, inplace=True)
df_common_features.drop(['Date'], axis=1, inplace=True)
# get and print portfolio features
df_portfolio_features = get_portfolio_features(df_common_features)

print_portfolio_stats(df_portfolio_features, myinvmt_df)

df = df_portfolio_features
#plot_pie_chart(df, 'CapType', 'Current')
list_ox40n = list(df[df['MBQ'].str.contains('OX40N', na=False)]['Symbol'].values)

Run date time (IST): 2026-03-27 13:06:01
-------------------
qualified stocks: 86
with latest results: 26
still star stocks: 16
-------------------
Initial Investment:  1.36 C
CY Investment:  1.62 C
Reserve:  1.61 K
Current:  1.29 C
-------------------
Today PnL: -2.62 L (-1.99%)
Current PnL: -48.33 L (-29.75%)
CY Booked + Current PnL: -32.44 L (-19.97%)
-------------------
Total profit:  43.97 K
Total loss:  -48.77 L
-------------------
Total Booked + Current PnL: -5.46 L (-4.03%)
Total Booked PnL: 42.87 L (31.64%)
Curr Year Booked PnL: 15.89 L (12.34%)
Prev Year Booked PnL: 26.98 L (19.91%)
===================
Est FTT:  2.48 C
Est FTT PnL: 1.19 C (92.47%)
===================
Deployed:  1.36 C
Current:  1.29 C
CAGR/XIRR %: -2.48%

In [9]:
# top 5 near their targets
cols = ['Symbol', 'Today P/L%', 'Current P/L%', 'FTT%', 'OTT%', 'FTT Amt', 'Current P/L', 'Current', 'FTT', 'Dev%_PE', 'RSI_14','Conviction', 'Spread%',  'CumlRnk', 'RRR Ind', 'CurrAlloc%', 'Gained%', 'Criteria', 'Strategy', 'Category']
df_tmp = df_portfolio_features[~df_portfolio_features['Symbol'].isin(['ENRIN','BLUSPRING','DIGITIDE'])]
df_tmp = df_tmp.sort_values(by = 'FTT Amt', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
50,MASFIN,-1.54,-9.03,33.64,21.57,29983.0,-8850.0,89130.0,397.04,-21.41,43.0,H-SC,3.47,167.0,-0.30,0.69,21.57,XR,ATH,FINANCE
77,TTKPRESTIG,-0.60,-43.12,75.96,0.09,43545.0,-43451.0,57326.0,770.00,32.98,34.0,M-SC,20.63,250.0,-1.00,0.45,0.00,OX40N,NTT,DURABLES
2,ABBOTINDIA,-0.28,-11.67,33.67,18.07,53192.0,-20875.0,157980.0,35195.00,-24.86,46.0,X-MC,10.46,58.0,-0.39,1.23,3.32,X40,ATH,PHARMA
37,ICICIGI,-1.66,-7.78,29.40,19.34,54257.0,-15563.0,184546.0,2252.93,-22.53,33.0,X-MC,4.49,66.0,-0.29,1.43,2.02,X40,ATH,INSURANCE
67,SONACOMS,-4.80,-15.77,65.13,39.09,55496.0,-15951.0,85208.0,804.02,-33.30,44.0,M-MC,6.69,193.0,-0.29,0.66,20.54,AR,ATH,AUTO

In [10]:
# top 5 today
df_tmp = df_portfolio_features.sort_values(by = 'Today P/L%', ascending=False)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
73,TCS,1.58,-29.10,78.53,26.57,257924.0,-134833.0,328440.0,4311.59,-40.02,35.0,X-LC,17.81,2.0,-0.52,2.55,2.50,X40,ATH,IT
48,KANSAINER,0.95,-41.51,94.00,13.47,148270.0,-111933.0,157734.0,340.00,-49.75,40.0,H-SC,21.63,162.0,-0.75,1.22,10.18,XY24,NTT,PAINTS
84,WIPRO,0.93,-21.74,120.13,72.27,159300.0,-36842.0,132606.0,420.00,-29.24,35.0,M-LC,17.95,98.0,-0.23,1.03,1.74,XR,NTT,IT
30,HAPPSTMNDS,0.63,-49.99,269.62,84.85,172816.0,-64069.0,64096.0,1480.71,-40.49,55.0,H-SC,25.59,152.0,-0.37,0.50,18.70,AR,ATH,IT
69,SURYODAY,0.56,-26.41,67.20,23.03,88552.0,-47297.0,131774.0,216.00,42.54,51.0,H-SC,5.45,166.0,-0.53,1.02,28.79,XR,NTT,BANKS

In [11]:
# bottom 5 today
df_tmp = df_portfolio_features.sort_values(by = 'Today P/L%', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
14,BOSCH-HCIL,-7.54,-51.14,104.65,-0.01,65350.0,-65359.0,62446.0,2282.0,12682.61,23.0,M-SC,5.94,231.0,-1.00,0.48,0.00,OX40N,BTT,AC
80,VALIANTORG,-6.93,-54.28,280.91,74.15,210121.0,-88805.0,74800.0,838.0,-234.75,44.0,H-SC,28.10,145.0,-0.42,0.58,11.31,XR,NTT,CHEMICALS
56,RAJOOENG,-5.77,-49.98,179.11,39.61,91830.0,-51230.0,51270.0,143.1,-66.21,33.0,H-SC,32.91,136.0,-0.56,0.40,0.87,AR,ATH,MISC
22,DEN,-5.63,-53.99,208.77,42.07,81136.0,-45600.0,38864.0,75.0,37.31,27.0,M-SC,19.68,235.0,-0.56,0.30,0.00,AR,NTT,ENTERTAINMENT
64,SHALBY,-5.19,-49.57,148.05,25.10,135256.0,-89785.0,91358.0,327.0,571.45,35.0,M-SC,27.32,236.0,-0.66,0.71,0.18,XY24,NTT,HEALTHCARE

In [12]:
# top 5 to exit based on CumlRnk
df_tmp = df_portfolio_features[~df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])]
df_tmp = df_tmp[(df_tmp['Current P/L%'] > -1) & (df_tmp['Current P/L%'] < 1)].sort_values(by = 'CumlRnk', ascending=False)
df_tmp[cols].head()

Empty DataFrame
Columns: [Symbol, Today P/L%, Current P/L%, FTT%, OTT%, FTT Amt, Current P/L, Current, FTT, Dev%_PE, RSI_14, Conviction, Spread%, CumlRnk, RRR Ind, CurrAlloc%, Gained%, Criteria, Strategy, Category]
Index: []

In [13]:
# OX40N stocks to exit
df_tmp = df_portfolio_features[(df_portfolio_features['Symbol'].isin(list_ox40n))].sort_values(by = 'Current P/L%', ascending=False)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
26,FINCABLES,-3.12,2.10,103.63,107.91,156222.0,3106.0,150750.0,1641.55,-8.17,44.0,M-SC,7.90,220.0,0.02,1.17,13.41,OX40N,ATH,CABLES
66,SIS,0.38,-34.09,83.97,21.26,61453.0,-37847.0,73185.0,528.00,1713.47,47.0,H-SC,14.42,168.0,-0.62,0.57,8.82,OX40N,NTT,MISC
18,CERA,0.19,-38.06,100.01,23.89,108967.0,-66947.0,108956.0,9475.00,-40.33,47.0,H-SC,19.10,153.0,-0.61,0.85,4.71,OX40N,NTT,CERAMICS
72,TATAELXSI,-1.08,-39.93,119.79,32.03,94864.0,-52643.0,79192.0,9161.00,-24.90,38.0,H-SC,21.25,158.0,-0.55,0.61,3.19,OX40N,NTT,IT
48,KANSAINER,0.95,-41.51,94.00,13.47,148270.0,-111933.0,157734.0,340.00,-49.75,40.0,H-SC,21.63,162.0,-0.75,1.22,10.18,XY24,NTT,PAINTS

In [14]:
# top 5 to book for rotation
df_tmp = df_portfolio_features[(df_portfolio_features['Current P/L%'] > 20) ].sort_values(by = 'CumlRnk', ascending=False)
df_tmp[cols].head()

Empty DataFrame
Columns: [Symbol, Today P/L%, Current P/L%, FTT%, OTT%, FTT Amt, Current P/L, Current, FTT, Dev%_PE, RSI_14, Conviction, Spread%, CumlRnk, RRR Ind, CurrAlloc%, Gained%, Criteria, Strategy, Category]
Index: []

In [15]:
# top 5 to monitor for exit
df_tmp = df_portfolio_features[~df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])]
df_tmp = df_tmp[(df_tmp['Current P/L%'] > 0) ].sort_values(by = 'Dev%_PE', ascending=False)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
26,FINCABLES,-3.12,2.10,103.63,107.91,156222.0,3106.0,150750.0,1641.55,-8.17,44.0,M-SC,7.90,220.0,0.02,1.17,13.41,OX40N,ATH,CABLES
1,ABB,-1.18,12.64,29.23,45.57,86140.0,33077.0,294696.0,7934.00,-27.57,53.0,H-MC,13.39,125.0,0.38,2.29,30.86,AR,NTT,ELECTRICAL

In [16]:
# top 5 to book for rotation from weak conviction
df_tmp = df_portfolio_features[~df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])]
df_tmp = df_tmp[~df_tmp['Criteria'].isin(['XY25','XY24','X40', 'X40N'])].sort_values(by = 'RRR Ind', ascending=False)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
1,ABB,-1.18,12.64,29.23,45.57,86140.0,33077.0,294696.0,7934.00,-27.57,53.0,H-MC,13.39,125.0,0.38,2.29,30.86,AR,NTT,ELECTRICAL
26,FINCABLES,-3.12,2.10,103.63,107.91,156222.0,3106.0,150750.0,1641.55,-8.17,44.0,M-SC,7.90,220.0,0.02,1.17,13.41,OX40N,ATH,CABLES
40,INDIAMART,-0.60,-13.90,140.11,106.72,148777.0,-17150.0,106186.0,4810.62,-61.13,38.0,H-SC,12.32,140.0,-0.12,0.82,6.22,AR,ATH,MISC
85,ZYDUSLIFE,-0.19,-4.88,42.59,35.63,84900.0,-10232.0,199342.0,1286.17,-17.12,51.0,H-MC,5.29,120.0,-0.12,1.55,10.98,AR,ATH,PHARMA
84,WIPRO,0.93,-21.74,120.13,72.27,159300.0,-36842.0,132606.0,420.00,-29.24,35.0,M-LC,17.95,98.0,-0.23,1.03,1.74,XR,NTT,IT

In [17]:
# top 5 to accumulate based on lowest RSI_14
df_tmp = df_portfolio_features[df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])].sort_values(by = 'RSI_14', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
53,PGHH,-1.61,-28.82,85.46,32.01,129886.0,-61536.0,151984.0,17616.87,-51.83,19.0,X-MC,17.10,57.0,-0.47,1.18,0.45,X40,ATH,FMCG
38,ICICIPRULI,-1.85,-12.20,48.89,30.73,84568.0,-24029.0,172976.0,790.00,-35.82,22.0,X-MC,5.57,78.0,-0.28,1.34,0.00,X40,ATH,INSURANCE
9,BAJAJHFL,-3.51,-31.80,137.72,62.13,256459.0,-86828.0,186218.0,181.50,-43.90,23.0,X-MC,20.60,60.0,-0.34,1.45,0.00,X40N,ATH,FINANCE
58,RELAXO,-4.48,-67.12,363.27,52.31,173367.0,-97436.0,47724.0,1176.00,-64.96,23.0,X-SC,28.47,92.0,-0.56,0.37,0.00,X40N,NTT,FOOTWEAR
27,GILLETTE,-2.06,-11.09,45.91,29.72,103635.0,-28161.0,225735.0,10978.86,-31.71,28.0,X-SC,11.80,83.0,-0.27,1.75,0.00,X40,ATH,FMCG

In [18]:
# top 5 to accumulate based on Spread and CumlRnk
df_tmp = df_portfolio_features[df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])]
df_tmp = df_tmp[(df_tmp['CumlRnk'] < 100)].sort_values(by = 'Spread%', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
65,SIEMENS,-1.39,-17.83,52.75,25.51,80663.0,-33180.0,152915.0,4671.50,28.36,44.0,H-LC,1.82,51.0,-0.41,1.19,12.61,AR,ATH,ELECTRICAL
78,UNITDSPR,-3.02,-6.56,29.25,20.77,63994.0,-15360.0,218784.0,1644.00,-17.10,40.0,X-MC,2.39,64.0,-0.24,1.70,0.00,X40N,NTT,BREWERIES
82,VOLTAS,-2.82,4.06,39.53,45.20,78874.0,7788.0,199530.0,1856.00,19.11,41.0,X-MC,3.37,79.0,0.10,1.55,11.14,XY25,NTT,AC
59,RELIANCE,-4.35,-13.24,44.42,25.30,77449.0,-26607.0,174356.0,1952.00,-15.42,38.0,X-LC,3.67,21.0,-0.34,1.35,16.41,XY25,BTT,REFINERIES
37,ICICIGI,-1.66,-7.78,29.40,19.34,54257.0,-15563.0,184546.0,2252.93,-22.53,33.0,X-MC,4.49,66.0,-0.29,1.43,2.02,X40,ATH,INSURANCE

In [19]:
# top 5 to accumulate based on lowest Gained%
df_tmp = df_portfolio_features[df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])].sort_values(by = 'Gained%', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
3,ACC,-3.33,-40.82,195.37,74.81,310029.0,-109440.0,158688.0,3906.00,-57.90,29.0,X-SC,19.09,85.0,-0.35,1.23,0.0,XY24,BTT,CEMENT
9,BAJAJHFL,-3.51,-31.80,137.72,62.13,256459.0,-86828.0,186218.0,181.50,-43.90,23.0,X-MC,20.60,60.0,-0.34,1.45,0.0,X40N,ATH,FINANCE
27,GILLETTE,-2.06,-11.09,45.91,29.72,103635.0,-28161.0,225735.0,10978.86,-31.71,28.0,X-SC,11.80,83.0,-0.27,1.75,0.0,X40,ATH,FMCG
38,ICICIPRULI,-1.85,-12.20,48.89,30.73,84568.0,-24029.0,172976.0,790.00,-35.82,22.0,X-MC,5.57,78.0,-0.28,1.34,0.0,X40,ATH,INSURANCE
58,RELAXO,-4.48,-67.12,363.27,52.31,173367.0,-97436.0,47724.0,1176.00,-64.96,23.0,X-SC,28.47,92.0,-0.56,0.37,0.0,X40N,NTT,FOOTWEAR

In [20]:
# top 5 to accumulate based on lowest CurrAlloc%
df_tmp = df_portfolio_features[df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])].sort_values(by = 'CurrAlloc%', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
58,RELAXO,-4.48,-67.12,363.27,52.31,173367.0,-97436.0,47724.0,1176.00,-64.96,23.0,X-SC,28.47,92.0,-0.56,0.37,0.00,X40N,NTT,FOOTWEAR
12,BATAINDIA,-2.67,-58.56,226.28,35.20,120650.0,-75351.0,53319.0,2096.00,-30.11,29.0,X-SC,32.30,91.0,-0.62,0.41,2.66,X40,NTT,FOOTWEAR
54,QUESS,-1.25,-28.45,143.05,73.90,109303.0,-30384.0,76409.0,424.00,-61.43,37.0,X-SC,21.76,80.0,-0.28,0.59,2.70,XY24,NTT,MISC
36,HONAUT,-2.77,-28.89,112.79,51.31,154663.0,-55713.0,137125.0,58357.33,-40.87,30.0,X-SC,16.63,90.0,-0.36,1.06,0.77,X40N,ATH,ELECTRICAL
51,MEDANTA,-2.56,-15.71,50.80,27.12,75588.0,-27722.0,148795.0,1486.00,-18.36,33.0,X-SC,13.42,87.0,-0.37,1.16,1.63,XY24,NTT,HEALTHCARE

In [21]:
# top 5 to accumulate based on CumlRnk
df_tmp = df_portfolio_features.sort_values(by = 'CumlRnk', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
45,ITC,-0.08,-22.18,52.99,19.06,140277.0,-75443.0,264723.0,452.00,-57.14,36.0,X-LC,18.92,1.0,-0.54,2.06,1.72,X40,NTT,FMCG
73,TCS,1.58,-29.10,78.53,26.57,257924.0,-134833.0,328440.0,4311.59,-40.02,35.0,X-LC,17.81,2.0,-0.52,2.55,2.50,X40,ATH,IT
43,INFY,-0.20,-13.09,54.47,34.24,148113.0,-40972.0,271916.0,1972.00,-31.79,41.0,X-LC,15.05,3.0,-0.28,2.11,4.57,X40,NTT,IT
75,TMPV,-4.92,-31.19,98.48,36.58,241141.0,-110978.0,244863.0,600.00,-85.81,34.0,X-LC,8.36,4.0,-0.46,1.90,0.00,XY24,NTT,AUTO
33,HCLTECH,-0.35,-10.67,38.63,23.83,83483.0,-25814.0,216110.0,1908.19,-6.12,46.0,X-LC,11.60,8.0,-0.31,1.68,4.93,X40,ATH,IT

In [22]:
# top 5 for average up
df_tmp = df_portfolio_features[(df_portfolio_features['Dev%_200'] > 5)].sort_values(by = 'CurrAlloc%', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
1,ABB,-1.18,12.64,29.23,45.57,86140.0,33077.0,294696.0,7934.0,-27.57,53.0,H-MC,13.39,125.0,0.38,2.29,30.86,AR,NTT,ELECTRICAL

In [23]:
# top 5 RSP
df_tmp = df_portfolio_features.sort_values(by = 'RSP', ascending=False)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
30,HAPPSTMNDS,0.63,-49.99,269.62,84.85,172816.0,-64069.0,64096.0,1480.71,-40.49,55.0,H-SC,25.59,152.0,-0.37,0.50,18.70,AR,ATH,IT
24,DMART,0.29,-5.71,37.46,29.60,88158.0,-14262.0,235338.0,5391.45,-20.50,56.0,X-LC,6.86,14.0,-0.16,1.83,7.57,X40N,ATH,FMCG
5,ANGELONE,-1.81,-3.46,28.62,24.18,84275.0,-10538.0,294462.0,303.00,-85.87,52.0,X-SC,10.11,97.0,-0.13,2.29,13.34,X40N,NTT,FINANCE
1,ABB,-1.18,12.64,29.23,45.57,86140.0,33077.0,294696.0,7934.00,-27.57,53.0,H-MC,13.39,125.0,0.38,2.29,30.86,AR,NTT,ELECTRICAL
52,PAGEIND,-1.49,-16.14,59.93,34.11,134872.0,-43329.0,225050.0,51418.64,-39.83,51.0,X-MC,21.02,55.0,-0.32,1.75,6.46,X40,ATH,APPARELS

In [24]:
# Top N allocation
df_tmp = df_portfolio_features.sort_values(by = 'CurrAlloc%', ascending=False)
top_n_values = [10, 25, 50]

sum_df = pd.DataFrame({
    'Top_N': top_n_values,
    'Sum_Alloc%': [df_tmp['CurrAlloc%'].head(n).sum() for n in top_n_values]
})

sum_df

   Top_N  Sum_Alloc%
0     10       20.93
1     25       46.11
2     50       78.39

In [25]:
# market-cap-wise allocation
df_tmp = df_portfolio_features[cols]
df_tmp.groupby(df_tmp['Conviction'].str[-2:])['CurrAlloc%'].sum().sort_values(ascending=False)

Conviction
SC    44.09
MC    30.15
LC    25.72
Name: CurrAlloc%, dtype: float64

In [26]:
# criteria-wise allocation
df_portfolio_features.groupby('Criteria')['CurrAlloc%'].sum().sort_values(ascending=False)

Criteria
XY24     26.90
X40      25.58
X40N     15.29
AR        9.20
XR        8.24
XY25      7.35
OX40N     6.61
SR        0.79
Name: CurrAlloc%, dtype: float64

In [27]:
# conviction-wise allocation
df_portfolio_features.groupby('Conviction')['CurrAlloc%'].sum().sort_values(ascending=False)

Conviction
X-LC    23.50
X-MC    22.64
H-SC    21.54
X-SC    12.24
M-SC     9.80
H-MC     5.13
M-MC     2.03
H-LC     1.19
M-LC     1.03
L-SC     0.51
L-MC     0.35
Name: CurrAlloc%, dtype: float64

In [28]:
# sector-wise stats
df_tmp = df_portfolio_features.groupby('Category')[['CurrAlloc%', 'Current', 'Current P/L', 'FTT Amt']].sum().sort_values(by=['Current', 'Current P/L'], ascending=False)
df_tmp['Current P/L%'] = round(df_tmp['Current P/L'] * 100 / df_tmp['Current'], 2)
df_tmp['FTT%'] = round(df_tmp['FTT Amt'] * 100 / df_tmp['Current'], 2)
cols = ['CurrAlloc%', 'Current P/L%', 'FTT%']
df_tmp[cols].sort_values(by=['CurrAlloc%'], ascending=False)

               CurrAlloc%  Current P/L%    FTT%
Category
FMCG                15.17        -27.77   73.13
FINANCE             13.07        -27.78   79.85
IT                  11.96        -46.26  120.70
MISC                 6.96        -49.36  114.23
ELECTRICAL           6.55        -14.80   58.75
PAINTS               5.25        -45.87   71.20
INSURANCE            4.71        -11.66   49.86
BANKS                4.58        -30.29   96.42
PHARMA               4.20         -8.72   42.95
AUTO                 3.62        -40.25   95.90
AC                   2.03        -21.98   55.05
HEALTHCARE           1.87        -48.93   87.80
FOOTWEAR             1.79        -90.82  167.33
TRAVEL               1.77        -96.04  194.21
DURABLES             1.75        -71.75  113.53
APPARELS             1.75        -19.25   59.93
BREWERIES            1.70         -7.02   29.25
REALTY               1.49        -15.78   34.80
CERAMICS             1.38        -72.73  125.20
REFINERIES           1.35        -15.26   44.42
CEMENT               1.23        -68.97  195.37
CABLES               1.17          2.06  103.63
ENGINEERING          1.06        -76.72  157.55
CHEMICALS            1.02       -101.52  265.92
JEWELLERY            0.99       -149.89  236.71
ENTERTAINMENT        0.74       -103.43  224.76
TEXTILES             0.46        -54.40   98.43
HOTELS               0.34       -162.73  255.40

In [29]:
# money to be made criteria-wise
df_portfolio_features.groupby('Criteria')['FTT Amt'].agg(['sum', 'count']).sort_values(by='sum', ascending=False)

                sum  count
Criteria
XY24      4130209.0     21
X40       1880559.0     16
XR        1428958.0     12
AR        1386844.0     10
X40N      1332072.0     10
OX40N      940777.0     10
XY25       492151.0      5
SR         317777.0      2

In [30]:
# money to be made conviction-wise
df_portfolio_features.groupby('Conviction')['FTT Amt'].agg(['sum', 'count']).sort_values(by='sum', ascending=False)

                  sum  count
Conviction
H-SC        4016882.0     24
X-MC        1818263.0     15
X-LC        1751106.0     13
M-SC        1654159.0     14
X-SC        1604423.0     10
H-MC         418425.0      3
L-SC         225231.0      2
M-LC         159300.0      1
M-MC         123839.0      2
H-LC          80663.0      1
L-MC          57056.0      1

In [31]:
# money to be made criteria and conviction-wise
df_portfolio_features.groupby(['Conviction', 'Criteria'])['FTT Amt'].agg(['sum', 'count']).sort_values(by='sum', ascending=False)

                           sum  count
Conviction Criteria
H-SC       XY24      1390917.0      6
           AR         998509.0      5
M-SC       XY24       954554.0      6
X-LC       X40        931192.0      7
H-SC       XR         908176.0      7
X-SC       XY24       867007.0      4
X-MC       X40        725082.0      7
           X40N       553942.0      4
X-SC       X40N       513131.0      4
M-SC       OX40N      424424.0      5
H-SC       OX40N      401503.0      4
X-LC       XY24       394246.0      2
H-SC       SR         317777.0      2
X-MC       XY24       276100.0      2
X-LC       X40N       264999.0      2
X-MC       XY25       263139.0      2
H-MC       XY24       247385.0      1
X-SC       X40        224285.0      2
M-SC       XR         194045.0      2
H-MC       AR         171040.0      2
X-LC       XY25       160669.0      2
M-LC       XR         159300.0      1
L-SC       OX40N      114850.0      1
           XR         110381.0      1
M-SC       AR          81136.0      1
H-LC       AR          80663.0      1
M-MC       XY25        68343.0      1
L-MC       XR          57056.0      1
M-MC       AR          55496.0      1

In [32]:
# notebook execution time

end_time = time.time()
execution_time = round(end_time - start_time, 0)
print(f"Notebook execution time: {execution_time} seconds")

Notebook execution time: 25.0 seconds