<a href="https://colab.research.google.com/github/ankit-rathi/Quantvesting_v2/blob/main/myStocks_Portfolio_Analysis.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
'''
!pip install pandas==2.2.2 -qq
!pip install pyxirr -qq
!pip install ta -qq
!pip install yfinance==0.2.59 -qq
'''

'\n!pip install pandas==2.2.2 -qq\n!pip install pyxirr -qq\n!pip install ta -qq\n!pip install yfinance==0.2.59 -qq\n'

In [2]:
# import libraries

import numpy as np
import pandas as pd
import datetime
import warnings
warnings.filterwarnings('ignore')
import yfinance as yfin
import ta
import matplotlib.pyplot as plt
import requests

In [3]:
# notebook start time
import time
import datetime
import pytz

start_time = time.time()

# function to print date timestamp
def print_date_time():
  tz_NY = pytz.timezone('Asia/Kolkata')
  datetime_NY = datetime.datetime.now(tz_NY)
  print("Run date time (IST):", datetime_NY.strftime("%Y-%m-%d %H:%M:%S"))

In [4]:
# function to get booked and reserved amount
def get_amt():
  # fetch the JSON data from the URL
  url = "https://raw.githubusercontent.com/ankit-rathi/Tradevesting_v1/main/data/myPortfolioAmts.json"
  response = requests.get(url)
  pf_amts = response.json()  # parse the JSON data

  # extract values from the JSON
  py_booked_amt_dm = pf_amts["py_booked_amt_dm"]
  py_booked_amt_sv = pf_amts["py_booked_amt_sv"]
  cy_booked_amt_dm = pf_amts["cy_booked_amt_dm"]
  cy_booked_amt_sv = pf_amts["cy_booked_amt_sv"]
  reserve_amt_dm = pf_amts["reserve_amt_dm"]
  reserve_amt_sv = pf_amts["reserve_amt_sv"]

  # perform calculations
  py_booked_amt = py_booked_amt_dm + py_booked_amt_sv
  cy_booked_amt = cy_booked_amt_dm + cy_booked_amt_sv
  reserve_amt = reserve_amt_dm + reserve_amt_sv
  total_booked_amt = py_booked_amt + cy_booked_amt

  return total_booked_amt, reserve_amt, cy_booked_amt, py_booked_amt

gen_output = 0

In [5]:
# function to format the amount
def format_amt(number):
    abs_number = abs(number)

    if abs_number >= 1_00_00_000:  # Crores
        formatted_amt = f"{number / 1_00_00_000:.2f} C"
    elif abs_number >= 1_00_000:  # Lakhs
        formatted_amt = f"{number / 1_00_000:.2f} L"
    elif abs_number >= 1_000:  # Thousands
        formatted_amt = f"{number / 1_000:.2f} K"
    else:
        formatted_amt = f"{number:.2f}"

    return formatted_amt

# function to set start and end date
def get_start_end_date():
  start_date = (datetime.date.today() + datetime.timedelta(days=-365)).strftime('%Y-%m-%d')
  end_date = (datetime.date.today() + datetime.timedelta(days=1)).strftime('%Y-%m-%d')
  return start_date, end_date

# function to fetch my portfolio csv
def get_mypfs_df():
  mypfs_df = pd.read_csv('https://raw.githubusercontent.com/ankit-rathi/Tradevesting_v1/main/data/myPortfolioStocks.csv')
  return mypfs_df

# function to fetch my prospects csv
def get_mypps_df():
  mypps_df = pd.read_csv('https://raw.githubusercontent.com/ankit-rathi/Tradevesting_v1/main/data/myProspectsScrips.csv')
  return mypps_df

# function to fetch screener data
def get_myscreen_df():
  myscreen_df = pd.read_csv('https://raw.githubusercontent.com/ankit-rathi/Tradevesting_v1/main/data/myScreenerDB.csv')
  return myscreen_df

# function to fetch momentum data
def get_myinvmt_df():
  myinvmt_df = pd.read_csv('https://raw.githubusercontent.com/ankit-rathi/Tradevesting_v1/main/data/myInvestments.csv')
  return myinvmt_df

# function to get the stock ids
def get_stock_ids(df_pf):
  stock_n100 = df_pf['Symbol'].unique()

  exclude = ['CADILAHC','MMTC', 'MASFIN']

  stock_ids = df_pf[~df_pf['Symbol'].isin(exclude) ]['Symbol'].unique()

  #mypf = mypf[mypf.Forecast.notnull()]
  #stock_ids = mypf['Symbol'].unique()

  #stock_ids.sort()
  return stock_ids

# get features from screener data
def get_screener_features():
  myscreen_df = get_myscreen_df()
  cols = ['Symbol', 'EPS', 'MedPE', 'ROCE%', 'ROE%', 'CapType']
  return myscreen_df[cols]

# get relative strength
def get_relative_strength(stock_list):

    # Dictionary to store stock tickers and their corresponding percentage price change
    stock_changes = {}

    # Loop through each stock and fetch its price data
    for stock in stock_list:
        try:
            # Download the stock data for the given date range
            stock_data = yfin.Ticker(stock + '.NS').history(period='1mo', interval='1d')[map(str.title, ['open', 'close', 'low', 'high', 'volume'])]

            # Calculate the percentage change for the stock
            if len(stock_data) > 0:
                start_price = stock_data['Close'].iloc[0]
                end_price = stock_data['Close'].iloc[-1]
                percent_change = round(((end_price - start_price) / start_price) * 100, 2)
                stock_changes[stock] = percent_change
            else:
                stock_changes[stock] = np.nan  # If no data is available, set to NaN

        except Exception as e:
            print(f"Error fetching data for {stock}: {e}")
            stock_changes[stock] = np.nan

    # Create a DataFrame with stock tickers and their percentage changes
    df = pd.DataFrame(list(stock_changes.items()), columns=['Symbol', 'Percent_Change'])

    # Drop any stocks with missing data (NaN values)
    df = df.dropna()

    # Calculate the percentile rank based on percentage change
    df['RSP'] = round(df['Percent_Change'].rank(pct=True) * 100, 2)
    cols = ['Symbol', 'RSP']
    df = df[cols]
    # Sort by percentile rank (optional)
    df = df.sort_values(by='RSP', ascending=False).reset_index(drop=True)

    return df

In [6]:
# function to get stock technicals
def stock_prec_dev(stock_symbol):
    #stock_symbol = 'ULTRACEMCO.NS'
    short_window = 20
    mid_window = 50
    long_window = 200
    moving_avg = 'SMA'

    start = datetime.datetime(*map(int, start_date.split('-')))
    end = datetime.datetime(*map(int, end_date.split('-')))

    stock_df = yfin.Ticker(stock_symbol + '.NS').history(period='max', interval='1d')[map(str.title, ['open', 'close', 'low', 'high', 'volume'])]

    stock_df['Max'] = round(max(stock_df['Close']),2)
    stock_df = stock_df[(stock_df.index <= end_date) & (stock_df.index >= start_date)]
    stock_df['200_SMA'] = round(stock_df['Close'].rolling(window = 200, min_periods = 1).mean(),0)
    stock_df['Dev%_200'] = round((stock_df['Close'] - stock_df['200_SMA'])*100/stock_df['200_SMA'],2)
    stock_df.dropna(axis = 0, inplace = True) # remove any null rows

    stock_df['20_SMA'] = stock_df['Close'].rolling(window=20).mean()
    stock_df['50_SMA'] = stock_df['Close'].rolling(window=50).mean()
    stock_df['Symbol'] = stock_symbol

    stock_df['Close'] = round(stock_df['Close'],2)
    stock_df['Min'] = round(min(stock_df['Close']),2)
    stock_df['RSI_14'] = ta.momentum.RSIIndicator(close=stock_df['Close'], window=14).rsi()
    stock_df['RSI_14'] = round(stock_df['RSI_14'],0)
    stock_df['Prev_Close'] = stock_df['Close'].shift(1)
    stock_df.drop(['Open', 'Low', 'High', 'Volume'], axis=1, inplace=True)
    stock_df = stock_df.tail(1)

    max_SMA = max(stock_df['20_SMA'].item(), stock_df['50_SMA'].item(), stock_df['200_SMA'].item())
    min_SMA = min(stock_df['20_SMA'].item(), stock_df['50_SMA'].item(), stock_df['200_SMA'].item())
    ABS_Spread = max_SMA - min_SMA
    stock_df['Spread%'] = round((ABS_Spread / stock_df['200_SMA'].item()) * 100,2)

    return stock_df

# function to compute stock attributes
def get_common_features(stock_ids, df_mypf):

  df_prec_dev = pd.DataFrame()
  df_tmp = get_screener_features()
  df_rs = get_relative_strength(stock_ids)

  for stock_id in stock_ids:
      tmp = stock_prec_dev(stock_id)
      tmp = tmp.reset_index()
      df_prec_dev = pd.concat([df_prec_dev, tmp], ignore_index = True)
  df_prec_dev = pd.merge(df_prec_dev, df_mypf, on= 'Symbol')
  df_prec_dev = pd.merge(df_prec_dev, df_tmp, on= 'Symbol', how='left')
  df_prec_dev = pd.merge(df_prec_dev, df_rs, on= 'Symbol', how='left')
  #print(df_prec_dev.columns)
  df_prec_dev['Curr_PE'] = round(df_prec_dev['Close']/df_prec_dev['EPS'],1)
  df_prec_dev['Dev%_PE'] = round((df_prec_dev['Curr_PE'] - df_prec_dev['MedPE'])*100/df_prec_dev['MedPE'],2)
  df_prec_dev['Conviction'] = df_prec_dev['Conviction'] + '-' + df_prec_dev['CapType']
  return df_prec_dev

# function to arrange stock features
def arrange_features(df_stocks, common_cols, diff_cols):
  df_stocks_common = df_stocks[common_cols].drop_duplicates()
  df_stocks_diff = df_stocks[diff_cols]
  df_stocks_diff['Investment'] = df_stocks_diff['AvgCost'] * df_stocks_diff['Shares']
  df_stocks_diff = df_stocks_diff.groupby(['Symbol'])[['Shares', 'Investment']].aggregate(['sum']).reset_index()
  df_stocks_diff.columns = ['Symbol', 'Shares', 'Investment']
  df_stocks_diff['AvgCost'] = round(df_stocks_diff['Investment']/df_stocks_diff['Shares'],2)
  df_stocks = pd.merge(df_stocks_diff, df_stocks_common, on='Symbol')
  return df_stocks

# plot fact distribution across dimension
def plot_pie_chart(df, dimension, fact):
  # grouping the data by category and calculating the sum of fact for each type
  grouped_data = df.groupby(dimension)[fact].sum()

  # sorting the grouped data in descending order
  grouped_data = grouped_data.sort_values(ascending=False)

  # creating a pie chart
  grouped_data.plot.pie(autopct='%1.1f%%', startangle=90, figsize=(6, 6))

  # adding a title and displaying the plot
  plt.title(f'{dimension} {fact} Distribution')
  plt.ylabel('')  # To hide the y-label
  plt.show()

In [7]:
# function to get portfolio features

def get_portfolio_features(df_common_features):

  print_date_time()
  print('-------------------')

  #df_common_features["Target"] = df_common_features["Target"].fillna(df_common_features["Max"])
  df_common_features['NTT'] = np.where(df_common_features['Strategy']== 'NTT', df_common_features["Target"], df_common_features['Max'])
  df_common_features['LTT'] = np.where(df_common_features['Strategy']== 'BTT', df_common_features["Target"], df_common_features['Max'])
  df_common_features['BOL'] = df_common_features['Min']

  tmp_df = df_common_features[df_common_features['Symbol'].isin(mypf_df[mypf_df['InPortfolio'] != 'NA'].Symbol.values)]
  print('qualified stocks: '+str(len(tmp_df['Symbol'].unique())))
  tmp_df1 = tmp_df[tmp_df['LatestQtr'] == 1]
  print('with latest results: '+str(len(tmp_df1['Symbol'].unique())))
  tmp_df1 = tmp_df1[tmp_df1['StarStock'] == 1]
  print('still star stocks: '+str(len(tmp_df1['Symbol'].unique())))
  tmp_df['Investment'] = tmp_df['AvgCost'] * tmp_df['Shares']
  tmp_df['Current'] = round(tmp_df['Close'] * tmp_df['Shares'],0)
  tmp_df['Previous'] = tmp_df['Prev_Close'] * tmp_df['Shares']
  tmp_df['EstimatedST'] = tmp_df['NTT'] * tmp_df['Shares']
  tmp_df['EstimatedLT'] = tmp_df['LTT'] * tmp_df['Shares']
  tmp_df['Current P/L'] = round((tmp_df['Current'] - tmp_df['Investment']),0)
  tmp_df['Today P/L%'] = round((tmp_df['Current'] - tmp_df['Previous'])*100/tmp_df['Previous'],2)
  tmp_df['Current P/L%'] = round((tmp_df['Current'] - tmp_df['Investment'])*100/tmp_df['Investment'],2)
  tmp_df['EstimatedST P/L%'] = round((tmp_df['EstimatedST'] - tmp_df['Investment'])*100/tmp_df['Investment'],2)
  tmp_df['EstimatedLT P/L%'] = round((tmp_df['EstimatedLT'] - tmp_df['Investment'])*100/tmp_df['Investment'],2)
  tmp_df['NTT%'] = round((tmp_df['NTT'] - tmp_df['Close'])*100/tmp_df['Close'],2)
  tmp_df['LTT%'] = round((tmp_df['LTT'] - tmp_df['Close'])*100/tmp_df['Close'],2)
  tmp_df['Gained%'] = round((tmp_df['Close'] - tmp_df['BOL'])*100/tmp_df['BOL'],2)
  investment = round(sum(tmp_df['AvgCost']*tmp_df['Shares']),0)
  current = round(sum(tmp_df['Close']*tmp_df['Shares']),0)
  tmp_df['InitAlloc%'] = round(tmp_df['Investment']*100/investment,2)
  tmp_df['CurrAlloc%'] = round(tmp_df['Current']*100/current,2)
  tmp_df['FTT'] = tmp_df['LTT']
  tmp_df.loc[tmp_df['Strategy'] == 'NTT', 'FTT'] = tmp_df['NTT']
  tmp_df['FTT%'] = tmp_df['LTT%']
  tmp_df.loc[tmp_df['Strategy'] == 'NTT', 'FTT%'] = tmp_df['NTT%']
  tmp_df['FTT Amt'] = round(tmp_df['FTT%'] * tmp_df['Current']/100,0)
  tmp_df['OTT%'] = round((tmp_df['FTT'] - tmp_df['AvgCost'])*100/tmp_df['AvgCost'],2)
  tmp_df['RRR Ind'] = round(tmp_df['Current P/L']/tmp_df['FTT Amt'],2)
  tmp_df['Risk Ind'] = round(tmp_df['Current P/L%']*tmp_df['CurrAlloc%'],0)

  return tmp_df

# function to print portfolio features
def print_portfolio_stats(df_portfolio_features, myinvmt_df):
  from pyxirr import xirr

  total_booked_amt, reserve_amt, cy_booked_amt, py_booked_amt = get_amt()

  dates = myinvmt_df['Date'].values
  dates = np.append(dates, datetime.date.today().strftime('%d-%b-%y'))
  investment = myinvmt_df['Investment'].values
  dates= pd.to_datetime(dates)

  current = round(sum(df_portfolio_features['Close']*df_portfolio_features['Shares']),0) + reserve_amt
  investment_xirr = np.append(investment, current)
  cagr = round(xirr(pd.DataFrame({"dates": dates, "amounts": investment_xirr}))*100,2)

  investment = -sum(investment)
  invested = round(sum(df_portfolio_features['AvgCost']*df_portfolio_features['Shares']),0) + reserve_amt
  previous = round(sum(df_portfolio_features['Prev_Close']*df_portfolio_features['Shares']),0) + reserve_amt
  cy_invested = investment + py_booked_amt

  today_pnl_amount = current-previous
  today_pnl_percentage = round((current-previous)*100/previous,2)

  curr_pnl_amount = current-invested
  curr_pnl_percentage = round((curr_pnl_amount)*100/(cy_invested),2)

  cy_pnl_amount = cy_booked_amt + curr_pnl_amount
  cy_pnl_percentage = round((cy_pnl_amount)*100/cy_invested,2)

  overall_pnl_amount = total_booked_amt + curr_pnl_amount
  overall_pnl_percentage = round((overall_pnl_amount)*100/investment,2)

  estimate_st = round(sum(df_portfolio_features['FTT']*df_portfolio_features['Shares']),0)  + reserve_amt
  est_st_pnl_amount = estimate_st-current
  est_st_pnl_percentage = round((est_st_pnl_amount)*100/current,2)

  estimate_lt = round(sum(df_portfolio_features['LTT']*df_portfolio_features['Shares']),0)  + reserve_amt
  est_lt_pnl_amount = estimate_lt-current
  est_lt_pnl_percentage = round((est_lt_pnl_amount)*100/current,2)

  total_profit = round(sum(df_portfolio_features[df_portfolio_features['Current P/L%'] > 0]['Current']) - sum(df_portfolio_features[df_portfolio_features['Current P/L%'] > 0]['Investment']),0)
  total_loss = round(sum(df_portfolio_features[df_portfolio_features['Current P/L%'] < 0]['Current']) - sum(df_portfolio_features[df_portfolio_features['Current P/L%'] < 0]['Investment']),0)

  cy_booked_percentage = round((cy_booked_amt)*100/current,2)
  py_booked_percentage = round((py_booked_amt)*100/investment,2)
  total_booked_percentage = round((total_booked_amt)*100/investment,2)

  print('-------------------')
  print('Initial Investment: ', format_amt(investment))
  print('CY Investment: ', format_amt(cy_invested))
  print('Reserve: ', format_amt(reserve_amt))
  print('Current: ',  format_amt(current))
  print('-------------------')
  print('Today PnL: '+ '{} ({}%)'.format(format_amt(today_pnl_amount), today_pnl_percentage))
  print('Current PnL: '+ '{} ({}%)'.format(format_amt(curr_pnl_amount), curr_pnl_percentage))
  print('CY Booked + Current PnL: '+ '{} ({}%)'.format(format_amt(cy_pnl_amount), cy_pnl_percentage))
  print('-------------------')
  print('Total profit: ', format_amt(total_profit))
  print('Total loss: ', format_amt(total_loss))
  print('-------------------')
  print('Total Booked + Current PnL: '+ '{} ({}%)'.format(format_amt(overall_pnl_amount), overall_pnl_percentage))
  print('Total Booked PnL: '+ '{} ({}%)'.format(format_amt(total_booked_amt), total_booked_percentage))
  print('Curr Year Booked PnL: '+ '{} ({}%)'.format(format_amt(cy_booked_amt), cy_booked_percentage))
  print('Prev Year Booked PnL: '+ '{} ({}%)'.format(format_amt(py_booked_amt), py_booked_percentage))
  print('===================')
  print('Est FTT: ',  format_amt(estimate_st))
  print('Est FTT PnL: '+ '{} ({}%)'.format(format_amt(est_st_pnl_amount), est_st_pnl_percentage))

  print('===================')
  print('Deployed: ', format_amt(investment))

  print('Current: ', format_amt(current))

  print('CAGR/XIRR %: '+'{}%'.format(cagr))

In [8]:
# get start and end date
start_date, end_date = get_start_end_date()

# get portfolio and prospects data
mypfs_df = get_mypfs_df()
mypps_df = get_mypps_df()
myinvmt_df = get_myinvmt_df()

# merge above datasets
mypf_df = pd.merge(mypfs_df, mypps_df, on="Symbol")

# seggregate dm and sv portfolio
dm_pf = mypf_df[mypf_df['InPortfolio'] == 'DM']
sv_pf = mypf_df[mypf_df['InPortfolio'] == 'SV']

# build portfolio stock dataframe
dm_stocks = get_stock_ids(dm_pf)
sv_stocks = get_stock_ids(sv_pf)
df_stocks = pd.concat([dm_pf,sv_pf], ignore_index = True)

# arrange common and diff stock features
common_cols = ['Symbol', 'Target', 'Criteria', 'Strategy', 'CumlRnk', 'LatestQtr', 'StarStock', 'Conviction', 'Category', 'InFolio', 'XIRR', 'MBQ']
diff_cols = ['Symbol', 'AvgCost', 'Shares']
df_stocks = arrange_features(df_stocks, common_cols, diff_cols)

# get common features
stock_ids = df_stocks['Symbol'].values
df_common_features = get_common_features(stock_ids, df_stocks)

df_common_features.reset_index(drop=True, inplace=True)
df_common_features.drop(['Date'], axis=1, inplace=True)
# get and print portfolio features
df_portfolio_features = get_portfolio_features(df_common_features)

print_portfolio_stats(df_portfolio_features, myinvmt_df)

df = df_portfolio_features
#plot_pie_chart(df, 'CapType', 'Current')
list_ox40n = list(df[df['MBQ'].str.contains('OX40N', na=False)]['Symbol'].values)

Run date time (IST): 2026-04-22 12:27:48
-------------------
qualified stocks: 90
with latest results: 28
still star stocks: 17

-------------------
Initial Investment:  1.38 C
CY Investment:  1.80 C
Reserve:  1.84 K
Current:  1.48 C
-------------------
Today PnL: 72.61 K (0.49%)
Current PnL: -32.42 L (-17.98%)
CY Booked + Current PnL: -31.46 L (-17.44%)
-------------------
Total profit:  2.37 L
Total loss:  -34.80 L
-------------------
Total Booked + Current PnL: 11.41 L (8.29%)
Total Booked PnL: 43.83 L (31.88%)
Curr Year Booked PnL: 96.00 K (0.65%)
Prev Year Booked PnL: 42.87 L (31.18%)
===================
Est FTT:  2.52 C
Est FTT PnL: 1.05 C (70.83%)
===================
Deployed:  1.38 C
Current:  1.48 C
CAGR/XIRR %: 3.44%

In [9]:
# top 5 near their targets
cols = ['Symbol', 'Today P/L%', 'Current P/L%', 'FTT%', 'OTT%', 'FTT Amt', 'Current P/L', 'Current', 'FTT', 'Dev%_PE', 'RSI_14','Conviction', 'Spread%',  'CumlRnk', 'RRR Ind', 'CurrAlloc%', 'Gained%', 'Criteria', 'Strategy', 'Category']
df_tmp = df_portfolio_features[~df_portfolio_features['Symbol'].isin(['ENRIN','BLUSPRING','DIGITIDE'])]
df_tmp = df_tmp.sort_values(by = 'FTT Amt', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
1,ABB,7.45,43.03,1.78,45.57,6660.0,112565.0,374184.0,7934.00,-8.04,84.0,H-MC,19.66,125.0,16.90,2.53,66.16,AR,NTT,ELECTRICAL
54,MASFIN,2.79,-0.58,22.28,21.57,21703.0,-570.0,97410.0,397.04,-14.18,62.0,H-SC,2.88,167.0,-0.03,0.66,25.88,XR,ATH,FINANCE
53,MARUTI,-0.36,-0.76,28.93,27.95,31041.0,-824.0,107296.0,17292.00,-18.07,51.0,X-LC,12.08,33.0,-0.03,0.73,15.89,XR,ATH,AUTO
61,RECLTD,0.18,3.97,16.13,20.74,34071.0,8058.0,211228.0,446.00,15.23,71.0,M-MC,4.07,191.0,0.24,1.43,25.88,XY25,NTT,FINANCE
81,TTKPRESTIG,1.33,-34.01,51.68,0.09,34368.0,-34275.0,66502.0,770.00,54.32,58.0,M-SC,22.61,250.0,-1.00,0.45,18.42,OX40N,NTT,DURABLES

In [10]:
# top 5 today
df_tmp = df_portfolio_features.sort_values(by = 'Today P/L%', ascending=False)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
1,ABB,7.45,43.03,1.78,45.57,6660.0,112565.0,374184.0,7934.0,-8.04,84.0,H-MC,19.66,125.0,16.90,2.53,66.16,AR,NTT,ELECTRICAL
0,5PAISA,5.25,-34.75,73.04,12.90,104128.0,-75933.0,142563.0,593.0,110.34,68.0,H-SC,13.39,170.0,-0.73,0.97,37.58,OX40N,NTT,FINANCE
7,AWL,5.13,-31.76,144.75,67.02,351948.0,-113167.0,243142.0,485.0,-63.27,65.0,X-SC,22.83,81.0,-0.32,1.65,15.01,XY24,NTT,FMCG
59,RAJESHEXPO,4.99,-76.32,322.62,0.07,104790.0,-104696.0,32481.0,518.0,1090.66,58.0,L-SC,40.48,268.0,-1.00,0.22,52.49,OX40N,NTT,JEWELLERY
69,SIEMENS,4.10,4.09,20.58,25.51,39867.0,7620.0,193715.0,4671.5,62.74,76.0,H-LC,3.77,51.0,0.19,1.31,36.73,AR,ATH,ELECTRICAL

In [11]:
# bottom 5 today
df_tmp = df_portfolio_features.sort_values(by = 'Today P/L%', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
34,HCLTECH,-10.80,-16.57,48.43,23.83,97751.0,-40085.0,201839.0,1908.19,-12.32,32.0,X-LC,7.27,8.0,-0.41,1.37,0.00,X40,ATH,IT
76,TATAELXSI,-5.42,-36.60,108.26,32.03,90480.0,-48258.0,83577.0,9161.00,-20.70,48.0,H-SC,17.82,158.0,-0.53,0.57,10.62,OX40N,NTT,IT
46,INFY,-4.29,-14.44,56.89,34.24,152306.0,-45168.0,267720.0,1972.00,-32.51,40.0,X-LC,12.61,3.0,-0.30,1.81,2.96,X40,NTT,IT
77,TCS,-4.01,-26.44,72.06,26.57,245582.0,-122471.0,340802.0,4311.59,-37.73,47.0,X-LC,15.75,2.0,-0.50,2.31,6.36,X40,ATH,IT
14,BSOFT,-2.00,-29.93,115.19,50.79,113529.0,-42095.0,98558.0,831.70,-9.93,56.0,H-SC,6.53,172.0,-0.37,0.67,16.22,XR,ATH,IT

In [12]:
# top 5 to exit based on CumlRnk
df_tmp = df_portfolio_features[~df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])]
df_tmp = df_tmp[(df_tmp['Current P/L%'] > -1) & (df_tmp['Current P/L%'] < 1)].sort_values(by = 'CumlRnk', ascending=False)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
54,MASFIN,2.79,-0.58,22.28,21.57,21703.0,-570.0,97410.0,397.04,-14.18,62.0,H-SC,2.88,167.0,-0.03,0.66,25.88,XR,ATH,FINANCE

In [13]:
# OX40N stocks to exit
df_tmp = df_portfolio_features[(df_portfolio_features['Symbol'].isin(list_ox40n))].sort_values(by = 'Current P/L%', ascending=False)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
26,FINCABLES,2.57,23.87,67.85,107.91,124088.0,35242.0,182886.0,1641.55,11.62,71.0,M-SC,4.23,220.0,0.28,1.24,37.59,OX40N,ATH,CABLES
70,SIS,0.96,-21.86,55.18,21.26,47876.0,-24268.0,86764.0,528.00,2049.74,76.0,H-SC,9.19,168.0,-0.51,0.59,29.00,OX40N,NTT,MISC
17,CERA,1.80,-29.51,75.77,23.89,93944.0,-51917.0,123986.0,9475.00,-31.98,69.0,H-SC,13.26,153.0,-0.55,0.84,19.15,OX40N,NTT,CERAMICS
51,KANSAINER,0.52,-30.81,64.00,13.47,119416.0,-83079.0,186588.0,340.00,-40.61,67.0,H-SC,19.26,162.0,-0.70,1.26,30.33,XY24,NTT,PAINTS
81,TTKPRESTIG,1.33,-34.01,51.68,0.09,34368.0,-34275.0,66502.0,770.00,54.32,58.0,M-SC,22.61,250.0,-1.00,0.45,18.42,OX40N,NTT,DURABLES

In [14]:
# top 5 to book for rotation
df_tmp = df_portfolio_features[(df_portfolio_features['Current P/L%'] > 20) ].sort_values(by = 'CumlRnk', ascending=False)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
26,FINCABLES,2.57,23.87,67.85,107.91,124088.0,35242.0,182886.0,1641.55,11.62,71.0,M-SC,4.23,220.0,0.28,1.24,37.59,OX40N,ATH,CABLES
1,ABB,7.45,43.03,1.78,45.57,6660.0,112565.0,374184.0,7934.00,-8.04,84.0,H-MC,19.66,125.0,16.90,2.53,66.16,AR,NTT,ELECTRICAL

In [15]:
# top 5 to monitor for exit
df_tmp = df_portfolio_features[~df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])]
df_tmp = df_tmp[(df_tmp['Current P/L%'] > 0) ].sort_values(by = 'Dev%_PE', ascending=False)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
61,RECLTD,0.18,3.97,16.13,20.74,34071.0,8058.0,211228.0,446.00,15.23,71.0,M-MC,4.07,191.0,0.24,1.43,25.88,XY25,NTT,FINANCE
26,FINCABLES,2.57,23.87,67.85,107.91,124088.0,35242.0,182886.0,1641.55,11.62,71.0,M-SC,4.23,220.0,0.28,1.24,37.59,OX40N,ATH,CABLES
1,ABB,7.45,43.03,1.78,45.57,6660.0,112565.0,374184.0,7934.00,-8.04,84.0,H-MC,19.66,125.0,16.90,2.53,66.16,AR,NTT,ELECTRICAL
71,SONACOMS,2.14,2.72,35.41,39.09,36793.0,2747.0,103906.0,804.02,-18.58,67.0,M-MC,11.23,193.0,0.07,0.70,46.99,AR,ATH,AUTO

In [16]:
# top 5 to book for rotation from weak conviction
df_tmp = df_portfolio_features[~df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])]
df_tmp = df_tmp[~df_tmp['Criteria'].isin(['XY25','XY24','X40', 'X40N'])].sort_values(by = 'RRR Ind', ascending=False)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
1,ABB,7.45,43.03,1.78,45.57,6660.0,112565.0,374184.0,7934.00,-8.04,84.0,H-MC,19.66,125.0,16.90,2.53,66.16,AR,NTT,ELECTRICAL
26,FINCABLES,2.57,23.87,67.85,107.91,124088.0,35242.0,182886.0,1641.55,11.62,71.0,M-SC,4.23,220.0,0.28,1.24,37.59,OX40N,ATH,CABLES
71,SONACOMS,2.14,2.72,35.41,39.09,36793.0,2747.0,103906.0,804.02,-18.58,67.0,M-MC,11.23,193.0,0.07,0.70,46.99,AR,ATH,AUTO
54,MASFIN,2.79,-0.58,22.28,21.57,21703.0,-570.0,97410.0,397.04,-14.18,62.0,H-SC,2.88,167.0,-0.03,0.66,25.88,XR,ATH,FINANCE
89,ZYDUSLIFE,0.22,-1.87,38.21,35.63,78584.0,-3911.0,205663.0,1286.17,-14.41,58.0,H-MC,4.64,120.0,-0.05,1.39,10.39,AR,ATH,PHARMA

In [17]:
# top 5 to accumulate based on lowest RSI_14
df_tmp = df_portfolio_features[df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])].sort_values(by = 'RSI_14', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
34,HCLTECH,-10.80,-16.57,48.43,23.83,97751.0,-40085.0,201839.0,1908.19,-12.32,32.0,X-LC,7.27,8.0,-0.41,1.37,0.00,X40,ATH,IT
46,INFY,-4.29,-14.44,56.89,34.24,152306.0,-45168.0,267720.0,1972.00,-32.51,40.0,X-LC,12.61,3.0,-0.30,1.81,2.96,X40,NTT,IT
2,ABBOTINDIA,0.43,-14.47,38.05,18.07,58205.0,-25885.0,152970.0,35195.00,-27.31,41.0,X-MC,11.85,58.0,-0.44,1.04,0.43,X40,ATH,PHARMA
41,ICICIPRULI,-1.52,-10.35,45.82,30.73,80923.0,-20395.0,176610.0,790.00,-34.44,41.0,X-MC,12.98,78.0,-0.25,1.20,7.62,X40,ATH,INSURANCE
36,HDFCLIFE,-1.38,-1.30,34.44,32.69,40678.0,-1560.0,118112.0,814.30,-22.62,44.0,X-LC,17.82,31.0,-0.04,0.80,7.00,X40,ATH,INSURANCE

In [18]:
# top 5 to accumulate based on Spread and CumlRnk
df_tmp = df_portfolio_features[df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])]
df_tmp = df_tmp[(df_tmp['CumlRnk'] < 100)].sort_values(by = 'Spread%', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
69,SIEMENS,4.10,4.09,20.58,25.51,39867.0,7620.0,193715.0,4671.50,62.74,76.0,H-LC,3.77,51.0,0.19,1.31,36.73,AR,ATH,ELECTRICAL
63,RELIANCE,0.74,-12.49,43.18,25.30,75939.0,-25097.0,175866.0,1952.00,-14.65,50.0,X-LC,5.69,21.0,-0.33,1.19,6.01,XY25,BTT,REFINERIES
82,UNITDSPR,2.50,2.63,17.67,20.77,42461.0,6157.0,240301.0,1644.00,-8.94,65.0,X-MC,5.73,64.0,0.15,1.63,14.63,X40N,NTT,BREWERIES
24,DMART,0.53,10.90,16.86,29.60,46671.0,27216.0,276816.0,5391.45,-6.49,70.0,X-LC,5.75,14.0,0.58,1.88,26.53,X40N,ATH,FMCG
86,VOLTAS,2.46,16.80,24.31,45.20,54442.0,32208.0,223950.0,1856.00,33.74,65.0,X-MC,6.49,79.0,0.59,1.52,24.74,XY25,NTT,AC

In [19]:
# top 5 to accumulate based on lowest Gained%
df_tmp = df_portfolio_features[df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])].sort_values(by = 'Gained%', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
34,HCLTECH,-10.80,-16.57,48.43,23.83,97751.0,-40085.0,201839.0,1908.19,-12.32,32.0,X-LC,7.27,8.0,-0.41,1.37,0.00,X40,ATH,IT
2,ABBOTINDIA,0.43,-14.47,38.05,18.07,58205.0,-25885.0,152970.0,35195.00,-27.31,41.0,X-MC,11.85,58.0,-0.44,1.04,0.43,X40,ATH,PHARMA
46,INFY,-4.29,-14.44,56.89,34.24,152306.0,-45168.0,267720.0,1972.00,-32.51,40.0,X-LC,12.61,3.0,-0.30,1.81,2.96,X40,NTT,IT
18,CIPLA,0.17,0.30,34.75,35.15,42473.0,366.0,122225.0,1663.60,-22.78,45.0,X-LC,15.83,18.0,0.01,0.83,3.54,X40N,ATH,PHARMA
63,RELIANCE,0.74,-12.49,43.18,25.30,75939.0,-25097.0,175866.0,1952.00,-14.65,50.0,X-LC,5.69,21.0,-0.33,1.19,6.01,XY25,BTT,REFINERIES

In [20]:
# top 5 to accumulate based on lowest CurrAlloc%
df_tmp = df_portfolio_features[df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])].sort_values(by = 'CurrAlloc%', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
62,RELAXO,0.02,-60.35,284.11,52.31,163528.0,-87602.0,57558.0,1176.0,-57.80,56.0,X-SC,31.11,92.0,-0.54,0.39,28.69,X40N,NTT,FOOTWEAR
11,BATAINDIA,0.04,-50.81,174.85,35.20,110673.0,-65374.0,63296.0,2096.0,-16.97,63.0,X-SC,30.84,91.0,-0.59,0.43,25.53,X40,NTT,FOOTWEAR
58,QUESS,0.48,-19.15,115.10,73.90,99376.0,-20454.0,86339.0,424.0,-56.47,60.0,X-SC,18.59,80.0,-0.21,0.58,16.14,XY24,NTT,MISC
53,MARUTI,-0.36,-0.76,28.93,27.95,31041.0,-824.0,107296.0,17292.0,-18.07,51.0,X-LC,12.08,33.0,-0.03,0.73,15.89,XR,ATH,AUTO
36,HDFCLIFE,-1.38,-1.30,34.44,32.69,40678.0,-1560.0,118112.0,814.3,-22.62,44.0,X-LC,17.82,31.0,-0.04,0.80,7.00,X40,ATH,INSURANCE

In [21]:
# top 5 to accumulate based on CumlRnk
df_tmp = df_portfolio_features.sort_values(by = 'CumlRnk', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
48,ITC,-0.97,-19.23,47.40,19.06,130235.0,-65408.0,274758.0,452.00,-55.52,53.0,X-LC,18.76,1.0,-0.50,1.86,6.59,X40,NTT,FMCG
77,TCS,-4.01,-26.44,72.06,26.57,245582.0,-122471.0,340802.0,4311.59,-37.73,47.0,X-LC,15.75,2.0,-0.50,2.31,6.36,X40,ATH,IT
46,INFY,-4.29,-14.44,56.89,34.24,152306.0,-45168.0,267720.0,1972.00,-32.51,40.0,X-LC,12.61,3.0,-0.30,1.81,2.96,X40,NTT,IT
79,TMPV,2.77,-16.74,64.05,36.58,189753.0,-59583.0,296258.0,600.00,-82.53,65.0,X-LC,8.89,4.0,-0.31,2.01,23.48,XY24,NTT,AUTO
34,HCLTECH,-10.80,-16.57,48.43,23.83,97751.0,-40085.0,201839.0,1908.19,-12.32,32.0,X-LC,7.27,8.0,-0.41,1.37,0.00,X40,ATH,IT

In [22]:
# top 5 for average up
df_tmp = df_portfolio_features[(df_portfolio_features['Dev%_200'] > 5)].sort_values(by = 'CurrAlloc%', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
71,SONACOMS,2.14,2.72,35.41,39.09,36793.0,2747.0,103906.0,804.02,-18.58,67.0,M-MC,11.23,193.0,0.07,0.70,46.99,AR,ATH,AUTO
73,SURYODAY,0.44,-15.93,46.35,23.03,69776.0,-28529.0,150542.0,216.00,64.47,67.0,H-SC,3.46,166.0,-0.41,1.02,28.38,XR,NTT,BANKS
26,FINCABLES,2.57,23.87,67.85,107.91,124088.0,35242.0,182886.0,1641.55,11.62,71.0,M-SC,4.23,220.0,0.28,1.24,37.59,OX40N,ATH,CABLES
69,SIEMENS,4.10,4.09,20.58,25.51,39867.0,7620.0,193715.0,4671.50,62.74,76.0,H-LC,3.77,51.0,0.19,1.31,36.73,AR,ATH,ELECTRICAL
61,RECLTD,0.18,3.97,16.13,20.74,34071.0,8058.0,211228.0,446.00,15.23,71.0,M-MC,4.07,191.0,0.24,1.43,25.88,XY25,NTT,FINANCE

In [23]:
# top 5 RSP
df_tmp = df_portfolio_features.sort_values(by = 'RSP', ascending=False)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
59,RAJESHEXPO,4.99,-76.32,322.62,0.07,104790.0,-104696.0,32481.0,518.0,1090.66,58.0,L-SC,40.48,268.0,-1.00,0.22,52.49,OX40N,NTT,JEWELLERY
85,VBL,2.53,0.46,34.87,35.50,110646.0,1467.0,317309.0,670.8,-11.29,74.0,X-LC,8.76,13.0,0.01,2.15,30.29,X40N,ATH,FMCG
51,KANSAINER,0.52,-30.81,64.00,13.47,119416.0,-83079.0,186588.0,340.0,-40.61,67.0,H-SC,19.26,162.0,-0.70,1.26,30.33,XY24,NTT,PAINTS
60,RAJOOENG,1.55,-34.78,114.06,39.61,76249.0,-35650.0,66850.0,143.1,-55.84,63.0,H-SC,27.50,136.0,-0.47,0.45,43.21,AR,ATH,MISC
69,SIEMENS,4.10,4.09,20.58,25.51,39867.0,7620.0,193715.0,4671.5,62.74,76.0,H-LC,3.77,51.0,0.19,1.31,36.73,AR,ATH,ELECTRICAL

In [24]:
# Top N allocation
df_tmp = df_portfolio_features.sort_values(by = 'CurrAlloc%', ascending=False)
top_n_values = [10, 25, 50]

sum_df = pd.DataFrame({
    'Top_N': top_n_values,
    'Sum_Alloc%': [df_tmp['CurrAlloc%'].head(n).sum() for n in top_n_values]
})

sum_df

   Top_N  Sum_Alloc%
0     10       20.12
1     25       44.44
2     50       75.23

In [25]:
# market-cap-wise allocation
df_tmp = df_portfolio_features[cols]
df_tmp.groupby(df_tmp['Conviction'].str[-2:])['CurrAlloc%'].sum().sort_values(ascending=False)

Conviction
SC    42.07
MC    29.32
LC    28.64
Name: CurrAlloc%, dtype: float64

In [26]:
# criteria-wise allocation
df_portfolio_features.groupby('Criteria')['CurrAlloc%'].sum().sort_values(ascending=False)

Criteria
XY24     26.84
X40      24.39
X40N     15.76
AR        9.40
XR        8.81
XY25      7.19
OX40N     6.85
SR        0.79
Name: CurrAlloc%, dtype: float64

In [27]:
# conviction-wise allocation
df_portfolio_features.groupby('Conviction')['CurrAlloc%'].sum().sort_values(ascending=False)

Conviction
X-LC    26.38
H-SC    21.76
X-MC    21.70
M-SC     9.98
X-SC     9.76
H-MC     5.15
M-MC     2.13
H-LC     1.31
M-LC     0.95
L-SC     0.57
L-MC     0.34
Name: CurrAlloc%, dtype: float64

In [28]:
# sector-wise stats
df_tmp = df_portfolio_features.groupby('Category')[['CurrAlloc%', 'Current', 'Current P/L', 'FTT Amt']].sum().sort_values(by=['Current', 'Current P/L'], ascending=False)
df_tmp['Current P/L%'] = round(df_tmp['Current P/L'] * 100 / df_tmp['Current'], 2)
df_tmp['FTT%'] = round(df_tmp['FTT Amt'] * 100 / df_tmp['Current'], 2)
cols = ['CurrAlloc%', 'Current P/L%', 'FTT%']
df_tmp[cols].sort_values(by=['CurrAlloc%'], ascending=False)

               CurrAlloc%  Current P/L%    FTT%
Category
FMCG                15.73        -13.02   52.96
IT                  10.93        -39.70  110.80
FINANCE             10.92        -14.52   64.33
MISC                 6.91        -31.30   88.35
ELECTRICAL           6.84          4.17   32.52
AUTO                 5.36        -12.13   56.36
PAINTS               5.31        -25.68   47.51
INSURANCE            5.19         -4.28   39.72
PHARMA               4.58         -5.04   38.76
BANKS                4.48        -16.57   75.75
AC                   2.04         -6.38   35.22
HEALTHCARE           1.88        -28.41   61.92
APPARELS             1.80         -1.01   35.47
FOOTWEAR             1.79        -67.25  134.31
DURABLES             1.74        -50.10   86.62
TRAVEL               1.74        -73.71  160.68
BREWERIES            1.63          2.56   17.67
REALTY               1.42         -5.78   23.16
CERAMICS             1.32        -57.34  105.15
CABLES               1.24         19.27   67.85
REFINERIES           1.19        -14.27   43.18
CEMENT               1.17        -55.89  172.52
ENGINEERING          1.15        -43.12  108.58
JEWELLERY            1.07       -101.82  171.94
CHEMICALS            1.05        -70.70  209.96
ENTERTAINMENT        0.76        -71.60  173.94
TEXTILES             0.44        -43.21   84.05
HOTELS               0.35       -118.55  195.64

In [29]:
# money to be made criteria-wise
df_portfolio_features.groupby('Criteria')['FTT Amt'].agg(['sum', 'count']).sort_values(by='sum', ascending=False)

                sum  count
Criteria
XY24      3634897.0     21
X40       1735658.0     17
XR        1329084.0     13
AR        1181854.0     10
X40N      1111570.0     12
OX40N      781724.0     10
XY25       378186.0      5
SR         303583.0      2

In [30]:
# money to be made conviction-wise
df_portfolio_features.groupby('Conviction')['FTT Amt'].agg(['sum', 'count']).sort_values(by='sum', ascending=False)

                  sum  count
Conviction
H-SC        3583018.0     24
X-LC        1696890.0     18
X-MC        1531192.0     15
M-SC        1443544.0     14
X-SC        1363633.0      9
H-MC         317140.0      3
L-SC         206435.0      2
M-LC         150960.0      1
M-MC          70864.0      2
L-MC          53013.0      1
H-LC          39867.0      1

In [31]:
# money to be made criteria and conviction-wise
df_portfolio_features.groupby(['Conviction', 'Criteria'])['FTT Amt'].agg(['sum', 'count']).sort_values(by='sum', ascending=False)

                           sum  count
Conviction Criteria
H-SC       XY24      1181946.0      6
           AR         945872.0      5
X-LC       X40        903564.0      8
M-SC       XY24       851724.0      6
H-SC       XR         815189.0      7
X-SC       XY24       804924.0      4
X-MC       X40        630553.0      7
           X40N       456451.0      4
X-SC       X40N       357168.0      3
M-SC       OX40N      340506.0      5
H-SC       OX40N      336428.0      4
X-LC       XY24       335605.0      2
H-SC       SR         303583.0      2
X-LC       X40N       297951.0      5
H-MC       XY24       231896.0      1
X-MC       XY24       228802.0      2
           XY25       215386.0      2
X-SC       X40        201541.0      2
M-SC       XR         177236.0      2
M-LC       XR         150960.0      1
X-LC       XY25       128729.0      2
L-SC       OX40N      104790.0      1
           XR         101645.0      1
H-MC       AR          85244.0      2
M-SC       AR          74078.0      1
L-MC       XR          53013.0      1
H-LC       AR          39867.0      1
M-MC       AR          36793.0      1
           XY25        34071.0      1
X-LC       XR          31041.0      1

In [32]:
# notebook execution time

end_time = time.time()
execution_time = round(end_time - start_time, 0)
print(f"Notebook execution time: {execution_time} seconds")

Notebook execution time: 39.0 seconds