<a href="https://colab.research.google.com/github/ankit-rathi/Quantvesting_v2/blob/main/myStocks_Portfolio_Analysis.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
'''
!pip install pandas==2.2.2 -qq
!pip install pyxirr -qq
!pip install ta -qq
!pip install yfinance==0.2.59 -qq
'''

'\n!pip install pandas==2.2.2 -qq\n!pip install pyxirr -qq\n!pip install ta -qq\n!pip install yfinance==0.2.59 -qq\n'

In [2]:
# import libraries

import numpy as np
import pandas as pd
import datetime
import warnings
warnings.filterwarnings('ignore')
import yfinance as yfin
import ta
import matplotlib.pyplot as plt
import requests

In [3]:
# notebook start time
import time
import datetime
import pytz

start_time = time.time()

# function to print date timestamp
def print_date_time():
  tz_NY = pytz.timezone('Asia/Kolkata')
  datetime_NY = datetime.datetime.now(tz_NY)
  print("Run date time (IST):", datetime_NY.strftime("%Y-%m-%d %H:%M:%S"))

In [4]:
# function to get booked and reserved amount
def get_amt():
  # fetch the JSON data from the URL
  url = "https://raw.githubusercontent.com/ankit-rathi/Tradevesting_v1/main/data/myPortfolioAmts.json"
  response = requests.get(url)
  pf_amts = response.json()  # parse the JSON data

  # extract values from the JSON
  py_booked_amt_dm = pf_amts["py_booked_amt_dm"]
  py_booked_amt_sv = pf_amts["py_booked_amt_sv"]
  cy_booked_amt_dm = pf_amts["cy_booked_amt_dm"]
  cy_booked_amt_sv = pf_amts["cy_booked_amt_sv"]
  reserve_amt_dm = pf_amts["reserve_amt_dm"]
  reserve_amt_sv = pf_amts["reserve_amt_sv"]

  # perform calculations
  py_booked_amt = py_booked_amt_dm + py_booked_amt_sv
  cy_booked_amt = cy_booked_amt_dm + cy_booked_amt_sv
  reserve_amt = reserve_amt_dm + reserve_amt_sv
  total_booked_amt = py_booked_amt + cy_booked_amt

  return total_booked_amt, reserve_amt, cy_booked_amt, py_booked_amt

gen_output = 0

In [5]:
# function to format the amount
def format_amt(number):
    abs_number = abs(number)

    if abs_number >= 1_00_00_000:  # Crores
        formatted_amt = f"{number / 1_00_00_000:.2f} C"
    elif abs_number >= 1_00_000:  # Lakhs
        formatted_amt = f"{number / 1_00_000:.2f} L"
    elif abs_number >= 1_000:  # Thousands
        formatted_amt = f"{number / 1_000:.2f} K"
    else:
        formatted_amt = f"{number:.2f}"

    return formatted_amt

# function to set start and end date
def get_start_end_date():
  start_date = (datetime.date.today() + datetime.timedelta(days=-365)).strftime('%Y-%m-%d')
  end_date = (datetime.date.today() + datetime.timedelta(days=1)).strftime('%Y-%m-%d')
  return start_date, end_date

# function to fetch my portfolio csv
def get_mypfs_df():
  mypfs_df = pd.read_csv('https://raw.githubusercontent.com/ankit-rathi/Tradevesting_v1/main/data/myPortfolioStocks.csv')
  return mypfs_df

# function to fetch my prospects csv
def get_mypps_df():
  mypps_df = pd.read_csv('https://raw.githubusercontent.com/ankit-rathi/Tradevesting_v1/main/data/myProspectsScrips.csv')
  return mypps_df

# function to fetch screener data
def get_myscreen_df():
  myscreen_df = pd.read_csv('https://raw.githubusercontent.com/ankit-rathi/Tradevesting_v1/main/data/myScreenerDB.csv')
  return myscreen_df

# function to fetch momentum data
def get_myinvmt_df():
  myinvmt_df = pd.read_csv('https://raw.githubusercontent.com/ankit-rathi/Tradevesting_v1/main/data/myInvestments.csv')
  return myinvmt_df

# function to get the stock ids
def get_stock_ids(df_pf):
  stock_n100 = df_pf['Symbol'].unique()

  exclude = ['CADILAHC','MMTC', 'MASFIN']

  stock_ids = df_pf[~df_pf['Symbol'].isin(exclude) ]['Symbol'].unique()

  #mypf = mypf[mypf.Forecast.notnull()]
  #stock_ids = mypf['Symbol'].unique()

  #stock_ids.sort()
  return stock_ids

# get features from screener data
def get_screener_features():
  myscreen_df = get_myscreen_df()
  cols = ['Symbol', 'EPS', 'MedPE', 'ROCE%', 'ROE%', 'CapType']
  return myscreen_df[cols]

# get relative strength
def get_relative_strength(stock_list):

    # Dictionary to store stock tickers and their corresponding percentage price change
    stock_changes = {}

    # Loop through each stock and fetch its price data
    for stock in stock_list:
        try:
            # Download the stock data for the given date range
            stock_data = yfin.Ticker(stock + '.NS').history(period='1mo', interval='1d')[map(str.title, ['open', 'close', 'low', 'high', 'volume'])]

            # Calculate the percentage change for the stock
            if len(stock_data) > 0:
                start_price = stock_data['Close'].iloc[0]
                end_price = stock_data['Close'].iloc[-1]
                percent_change = round(((end_price - start_price) / start_price) * 100, 2)
                stock_changes[stock] = percent_change
            else:
                stock_changes[stock] = np.nan  # If no data is available, set to NaN

        except Exception as e:
            print(f"Error fetching data for {stock}: {e}")
            stock_changes[stock] = np.nan

    # Create a DataFrame with stock tickers and their percentage changes
    df = pd.DataFrame(list(stock_changes.items()), columns=['Symbol', 'Percent_Change'])

    # Drop any stocks with missing data (NaN values)
    df = df.dropna()

    # Calculate the percentile rank based on percentage change
    df['RSP'] = round(df['Percent_Change'].rank(pct=True) * 100, 2)
    cols = ['Symbol', 'RSP']
    df = df[cols]
    # Sort by percentile rank (optional)
    df = df.sort_values(by='RSP', ascending=False).reset_index(drop=True)

    return df

In [6]:
# function to get stock technicals
def stock_prec_dev(stock_symbol):
    #stock_symbol = 'ULTRACEMCO.NS'
    short_window = 20
    mid_window = 50
    long_window = 200
    moving_avg = 'SMA'

    start = datetime.datetime(*map(int, start_date.split('-')))
    end = datetime.datetime(*map(int, end_date.split('-')))

    stock_df = yfin.Ticker(stock_symbol + '.NS').history(period='max', interval='1d')[map(str.title, ['open', 'close', 'low', 'high', 'volume'])]

    stock_df['Max'] = round(max(stock_df['Close']),2)
    stock_df = stock_df[(stock_df.index <= end_date) & (stock_df.index >= start_date)]
    stock_df['200_SMA'] = round(stock_df['Close'].rolling(window = 200, min_periods = 1).mean(),0)
    stock_df['Dev%_200'] = round((stock_df['Close'] - stock_df['200_SMA'])*100/stock_df['200_SMA'],2)
    stock_df.dropna(axis = 0, inplace = True) # remove any null rows

    stock_df['20_SMA'] = stock_df['Close'].rolling(window=20).mean()
    stock_df['50_SMA'] = stock_df['Close'].rolling(window=50).mean()
    stock_df['Symbol'] = stock_symbol

    stock_df['Close'] = round(stock_df['Close'],2)
    stock_df['Min'] = round(min(stock_df['Close']),2)
    stock_df['RSI_14'] = ta.momentum.RSIIndicator(close=stock_df['Close'], window=14).rsi()
    stock_df['RSI_14'] = round(stock_df['RSI_14'],0)
    stock_df['Prev_Close'] = stock_df['Close'].shift(1)
    stock_df.drop(['Open', 'Low', 'High', 'Volume'], axis=1, inplace=True)
    stock_df = stock_df.tail(1)

    max_SMA = max(stock_df['20_SMA'].item(), stock_df['50_SMA'].item(), stock_df['200_SMA'].item())
    min_SMA = min(stock_df['20_SMA'].item(), stock_df['50_SMA'].item(), stock_df['200_SMA'].item())
    ABS_Spread = max_SMA - min_SMA
    stock_df['Spread%'] = round((ABS_Spread / stock_df['200_SMA'].item()) * 100,2)

    return stock_df

# function to compute stock attributes
def get_common_features(stock_ids, df_mypf):

  df_prec_dev = pd.DataFrame()
  df_tmp = get_screener_features()
  df_rs = get_relative_strength(stock_ids)

  for stock_id in stock_ids:
      tmp = stock_prec_dev(stock_id)
      tmp = tmp.reset_index()
      df_prec_dev = pd.concat([df_prec_dev, tmp], ignore_index = True)
  df_prec_dev = pd.merge(df_prec_dev, df_mypf, on= 'Symbol')
  df_prec_dev = pd.merge(df_prec_dev, df_tmp, on= 'Symbol', how='left')
  df_prec_dev = pd.merge(df_prec_dev, df_rs, on= 'Symbol', how='left')
  #print(df_prec_dev.columns)
  df_prec_dev['Curr_PE'] = round(df_prec_dev['Close']/df_prec_dev['EPS'],1)
  df_prec_dev['Dev%_PE'] = round((df_prec_dev['Curr_PE'] - df_prec_dev['MedPE'])*100/df_prec_dev['MedPE'],2)
  df_prec_dev['Conviction'] = df_prec_dev['Conviction'] + '-' + df_prec_dev['CapType']
  return df_prec_dev

# function to arrange stock features
def arrange_features(df_stocks, common_cols, diff_cols):
  df_stocks_common = df_stocks[common_cols].drop_duplicates()
  df_stocks_diff = df_stocks[diff_cols]
  df_stocks_diff['Investment'] = df_stocks_diff['AvgCost'] * df_stocks_diff['Shares']
  df_stocks_diff = df_stocks_diff.groupby(['Symbol'])[['Shares', 'Investment']].aggregate(['sum']).reset_index()
  df_stocks_diff.columns = ['Symbol', 'Shares', 'Investment']
  df_stocks_diff['AvgCost'] = round(df_stocks_diff['Investment']/df_stocks_diff['Shares'],2)
  df_stocks = pd.merge(df_stocks_diff, df_stocks_common, on='Symbol')
  return df_stocks

# plot fact distribution across dimension
def plot_pie_chart(df, dimension, fact):
  # grouping the data by category and calculating the sum of fact for each type
  grouped_data = df.groupby(dimension)[fact].sum()

  # sorting the grouped data in descending order
  grouped_data = grouped_data.sort_values(ascending=False)

  # creating a pie chart
  grouped_data.plot.pie(autopct='%1.1f%%', startangle=90, figsize=(6, 6))

  # adding a title and displaying the plot
  plt.title(f'{dimension} {fact} Distribution')
  plt.ylabel('')  # To hide the y-label
  plt.show()

In [7]:
# function to get portfolio features

def get_portfolio_features(df_common_features):

  print_date_time()
  print('-------------------')

  #df_common_features["Target"] = df_common_features["Target"].fillna(df_common_features["Max"])
  df_common_features['NTT'] = np.where(df_common_features['Strategy']== 'NTT', df_common_features["Target"], df_common_features['Max'])
  df_common_features['LTT'] = np.where(df_common_features['Strategy']== 'BTT', df_common_features["Target"], df_common_features['Max'])
  df_common_features['BOL'] = df_common_features['Min']

  tmp_df = df_common_features[df_common_features['Symbol'].isin(mypf_df[mypf_df['InPortfolio'] != 'NA'].Symbol.values)]
  print('qualified stocks: '+str(len(tmp_df['Symbol'].unique())))
  tmp_df1 = tmp_df[tmp_df['LatestQtr'] == 1]
  print('with latest results: '+str(len(tmp_df1['Symbol'].unique())))
  tmp_df1 = tmp_df1[tmp_df1['StarStock'] == 1]
  print('still star stocks: '+str(len(tmp_df1['Symbol'].unique())))
  tmp_df['Investment'] = tmp_df['AvgCost'] * tmp_df['Shares']
  tmp_df['Current'] = round(tmp_df['Close'] * tmp_df['Shares'],0)
  tmp_df['Previous'] = tmp_df['Prev_Close'] * tmp_df['Shares']
  tmp_df['EstimatedST'] = tmp_df['NTT'] * tmp_df['Shares']
  tmp_df['EstimatedLT'] = tmp_df['LTT'] * tmp_df['Shares']
  tmp_df['Current P/L'] = round((tmp_df['Current'] - tmp_df['Investment']),0)
  tmp_df['Today P/L%'] = round((tmp_df['Current'] - tmp_df['Previous'])*100/tmp_df['Previous'],2)
  tmp_df['Current P/L%'] = round((tmp_df['Current'] - tmp_df['Investment'])*100/tmp_df['Investment'],2)
  tmp_df['EstimatedST P/L%'] = round((tmp_df['EstimatedST'] - tmp_df['Investment'])*100/tmp_df['Investment'],2)
  tmp_df['EstimatedLT P/L%'] = round((tmp_df['EstimatedLT'] - tmp_df['Investment'])*100/tmp_df['Investment'],2)
  tmp_df['NTT%'] = round((tmp_df['NTT'] - tmp_df['Close'])*100/tmp_df['Close'],2)
  tmp_df['LTT%'] = round((tmp_df['LTT'] - tmp_df['Close'])*100/tmp_df['Close'],2)
  tmp_df['Gained%'] = round((tmp_df['Close'] - tmp_df['BOL'])*100/tmp_df['BOL'],2)
  investment = round(sum(tmp_df['AvgCost']*tmp_df['Shares']),0)
  current = round(sum(tmp_df['Close']*tmp_df['Shares']),0)
  tmp_df['InitAlloc%'] = round(tmp_df['Investment']*100/investment,2)
  tmp_df['CurrAlloc%'] = round(tmp_df['Current']*100/current,2)
  tmp_df['FTT'] = tmp_df['LTT']
  tmp_df.loc[tmp_df['Strategy'] == 'NTT', 'FTT'] = tmp_df['NTT']
  tmp_df['FTT%'] = tmp_df['LTT%']
  tmp_df.loc[tmp_df['Strategy'] == 'NTT', 'FTT%'] = tmp_df['NTT%']
  tmp_df['FTT Amt'] = round(tmp_df['FTT%'] * tmp_df['Current']/100,0)
  tmp_df['OTT%'] = round((tmp_df['FTT'] - tmp_df['AvgCost'])*100/tmp_df['AvgCost'],2)
  tmp_df['RRR Ind'] = round(tmp_df['Current P/L']/tmp_df['FTT Amt'],2)
  tmp_df['Risk Ind'] = round(tmp_df['Current P/L%']*tmp_df['CurrAlloc%'],0)

  return tmp_df

# function to print portfolio features
def print_portfolio_stats(df_portfolio_features, myinvmt_df):
  from pyxirr import xirr

  total_booked_amt, reserve_amt, cy_booked_amt, py_booked_amt = get_amt()

  dates = myinvmt_df['Date'].values
  dates = np.append(dates, datetime.date.today().strftime('%d-%b-%y'))
  investment = myinvmt_df['Investment'].values
  dates= pd.to_datetime(dates)

  current = round(sum(df_portfolio_features['Close']*df_portfolio_features['Shares']),0) + reserve_amt
  investment_xirr = np.append(investment, current)
  cagr = round(xirr(pd.DataFrame({"dates": dates, "amounts": investment_xirr}))*100,2)

  investment = -sum(investment)
  invested = round(sum(df_portfolio_features['AvgCost']*df_portfolio_features['Shares']),0) + reserve_amt
  previous = round(sum(df_portfolio_features['Prev_Close']*df_portfolio_features['Shares']),0) + reserve_amt
  cy_invested = investment + py_booked_amt

  today_pnl_amount = current-previous
  today_pnl_percentage = round((current-previous)*100/previous,2)

  curr_pnl_amount = current-invested
  curr_pnl_percentage = round((curr_pnl_amount)*100/(cy_invested),2)

  cy_pnl_amount = cy_booked_amt + curr_pnl_amount
  cy_pnl_percentage = round((cy_pnl_amount)*100/cy_invested,2)

  overall_pnl_amount = total_booked_amt + curr_pnl_amount
  overall_pnl_percentage = round((overall_pnl_amount)*100/investment,2)

  estimate_st = round(sum(df_portfolio_features['FTT']*df_portfolio_features['Shares']),0)  + reserve_amt
  est_st_pnl_amount = estimate_st-current
  est_st_pnl_percentage = round((est_st_pnl_amount)*100/current,2)

  estimate_lt = round(sum(df_portfolio_features['LTT']*df_portfolio_features['Shares']),0)  + reserve_amt
  est_lt_pnl_amount = estimate_lt-current
  est_lt_pnl_percentage = round((est_lt_pnl_amount)*100/current,2)

  total_profit = round(sum(df_portfolio_features[df_portfolio_features['Current P/L%'] > 0]['Current']) - sum(df_portfolio_features[df_portfolio_features['Current P/L%'] > 0]['Investment']),0)
  total_loss = round(sum(df_portfolio_features[df_portfolio_features['Current P/L%'] < 0]['Current']) - sum(df_portfolio_features[df_portfolio_features['Current P/L%'] < 0]['Investment']),0)

  cy_booked_percentage = round((cy_booked_amt)*100/current,2)
  py_booked_percentage = round((py_booked_amt)*100/investment,2)
  total_booked_percentage = round((total_booked_amt)*100/investment,2)

  print('-------------------')
  print('Initial Investment: ', format_amt(investment))
  print('CY Investment: ', format_amt(cy_invested))
  print('Reserve: ', format_amt(reserve_amt))
  print('Current: ',  format_amt(current))
  print('-------------------')
  print('Today PnL: '+ '{} ({}%)'.format(format_amt(today_pnl_amount), today_pnl_percentage))
  print('Current PnL: '+ '{} ({}%)'.format(format_amt(curr_pnl_amount), curr_pnl_percentage))
  print('CY Booked + Current PnL: '+ '{} ({}%)'.format(format_amt(cy_pnl_amount), cy_pnl_percentage))
  print('-------------------')
  print('Total profit: ', format_amt(total_profit))
  print('Total loss: ', format_amt(total_loss))
  print('-------------------')
  print('Total Booked + Current PnL: '+ '{} ({}%)'.format(format_amt(overall_pnl_amount), overall_pnl_percentage))
  print('Total Booked PnL: '+ '{} ({}%)'.format(format_amt(total_booked_amt), total_booked_percentage))
  print('Curr Year Booked PnL: '+ '{} ({}%)'.format(format_amt(cy_booked_amt), cy_booked_percentage))
  print('Prev Year Booked PnL: '+ '{} ({}%)'.format(format_amt(py_booked_amt), py_booked_percentage))
  print('===================')
  print('Est FTT: ',  format_amt(estimate_st))
  print('Est FTT PnL: '+ '{} ({}%)'.format(format_amt(est_st_pnl_amount), est_st_pnl_percentage))

  print('===================')
  print('Deployed: ', format_amt(investment))

  print('Current: ', format_amt(current))

  print('CAGR/XIRR %: '+'{}%'.format(cagr))

In [8]:
# get start and end date
start_date, end_date = get_start_end_date()

# get portfolio and prospects data
mypfs_df = get_mypfs_df()
mypps_df = get_mypps_df()
myinvmt_df = get_myinvmt_df()

# merge above datasets
mypf_df = pd.merge(mypfs_df, mypps_df, on="Symbol")

# seggregate dm and sv portfolio
dm_pf = mypf_df[mypf_df['InPortfolio'] == 'DM']
sv_pf = mypf_df[mypf_df['InPortfolio'] == 'SV']

# build portfolio stock dataframe
dm_stocks = get_stock_ids(dm_pf)
sv_stocks = get_stock_ids(sv_pf)
df_stocks = pd.concat([dm_pf,sv_pf], ignore_index = True)

# arrange common and diff stock features
common_cols = ['Symbol', 'Target', 'Criteria', 'Strategy', 'CumlRnk', 'LatestQtr', 'StarStock', 'Conviction', 'Category', 'InFolio', 'XIRR', 'MBQ']
diff_cols = ['Symbol', 'AvgCost', 'Shares']
df_stocks = arrange_features(df_stocks, common_cols, diff_cols)

# get common features
stock_ids = df_stocks['Symbol'].values
df_common_features = get_common_features(stock_ids, df_stocks)

df_common_features.reset_index(drop=True, inplace=True)
df_common_features.drop(['Date'], axis=1, inplace=True)
# get and print portfolio features
df_portfolio_features = get_portfolio_features(df_common_features)

print_portfolio_stats(df_portfolio_features, myinvmt_df)

df = df_portfolio_features
#plot_pie_chart(df, 'CapType', 'Current')
list_ox40n = list(df[df['MBQ'].str.contains('OX40N', na=False)]['Symbol'].values)

Run date time (IST): 2026-06-08 12:12:55
-------------------
qualified stocks: 92
with latest results: 31
still star stocks: 20
-------------------
Initial Investment:  1.40 C
CY Investment:  1.82 C
Reserve:  1.49 K
Current:  1.47 C
-------------------
Today PnL: -94.40 K (-0.64%)
Current PnL: -35.77 L (-19.61%)
CY Booked + Current PnL: -33.69 L (-18.47%)
-------------------
Total profit:  2.39 L
Total loss:  -38.16 L
-------------------
Total Booked + Current PnL: 9.18 L (6.58%)
Total Booked PnL: 44.95 L (32.22%)
Curr Year Booked PnL: 2.08 L (1.41%)
Prev Year Booked PnL: 42.87 L (30.73%)
===================
Est FTT:  2.55 C
Est FTT PnL: 1.08 C (73.11%)
===================
Deployed:  1.40 C
Current:  1.47 C
CAGR/XIRR %: 2.6%

In [9]:
# top 5 near their targets
cols = ['Symbol', 'Today P/L%', 'Current P/L%', 'FTT%', 'OTT%', 'FTT Amt', 'Current P/L', 'Current', 'FTT', 'Dev%_PE', 'RSI_14','Conviction', 'Spread%',  'CumlRnk', 'RRR Ind', 'CurrAlloc%', 'Gained%', 'Criteria', 'Strategy', 'Category']
df_tmp = df_portfolio_features[~df_portfolio_features['Symbol'].isin(['ENRIN','BLUSPRING','DIGITIDE'])]
df_tmp = df_tmp.sort_values(by = 'FTT Amt', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
59,PIDILITIND,-0.14,4.49,13.28,18.37,19581.0,6340.0,147450.0,1670.26,-26.86,58.0,X-LC,4.13,5.0,0.32,1.00,15.77,X40,ATH,CHEMICALS
51,KOTAKBANK,-0.17,0.68,20.29,21.11,28288.0,944.0,139416.0,453.24,-13.74,45.0,X-LC,7.01,12.0,0.03,0.95,6.62,X40,ATH,BANKS
55,MASFIN,-1.68,-7.84,31.91,21.57,28815.0,-7680.0,90300.0,397.04,-20.51,37.0,H-SC,1.37,167.0,-0.27,0.61,7.63,XR,ATH,FINANCE
72,SIS,-2.41,-6.53,29.73,21.26,30855.0,-7247.0,103785.0,528.00,2471.50,60.0,H-SC,19.30,168.0,-0.23,0.70,54.31,OX40N,NTT,MISC
83,TTKPRESTIG,-0.34,-30.87,44.78,0.09,31199.0,-31105.0,69672.0,770.00,61.79,52.0,M-SC,13.45,250.0,-1.00,0.47,24.06,OX40N,NTT,DURABLES

In [10]:
# top 5 today
df_tmp = df_portfolio_features.sort_values(by = 'Today P/L%', ascending=False)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
69,SFL,3.96,-34.25,92.61,26.63,159656.0,-89822.0,172396.0,1287.00,30.59,71.0,M-SC,7.81,242.0,-0.56,1.17,43.68,XY24,NTT,MISC
80,TITAGARH,2.15,-19.42,80.86,45.74,157794.0,-47032.0,195145.0,1548.00,7.41,61.0,H-SC,5.47,175.0,-0.30,1.32,48.89,XY24,NTT,ENGINEERING
3,ALKYLAMINE,1.95,-22.92,151.19,93.63,117665.0,-23137.0,77826.0,4546.37,-17.40,60.0,H-SC,9.32,142.0,-0.20,0.53,46.96,SR,ATH,CHEMICALS
16,CERA,1.95,-26.52,68.59,23.89,88659.0,-46643.0,129260.0,9475.00,-29.12,52.0,H-SC,5.31,153.0,-0.53,0.88,24.22,OX40N,NTT,CERAMICS
37,HONAUT,1.82,-8.39,65.18,51.31,115140.0,-16188.0,176650.0,58357.33,-23.87,64.0,X-SC,7.28,90.0,-0.14,1.20,34.21,X40N,ATH,ELECTRICAL

In [11]:
# bottom 5 today
df_tmp = df_portfolio_features.sort_values(by = 'Today P/L%', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
90,WIPRO,-6.43,-23.87,126.28,72.27,162900.0,-40449.0,128999.0,420.0,-31.12,34.0,M-LC,12.56,98.0,-0.25,0.88,0.00,XR,NTT,IT
18,COFFEEDAY,-5.00,-38.27,119.12,35.27,83502.0,-43450.0,70099.0,80.0,-51.71,66.0,L-SC,19.41,266.0,-0.52,0.48,72.87,XR,NTT,HOTELS
61,RAJESHEXPO,-4.99,-81.88,452.24,0.07,112413.0,-112320.0,24857.0,518.0,811.62,31.0,L-SC,30.87,268.0,-1.00,0.17,16.70,OX40N,NTT,JEWELLERY
49,JSWINFRA,-3.29,-8.44,27.16,16.43,55150.0,-18717.0,203057.0,342.0,-21.44,46.0,X-MC,3.53,61.0,-0.34,1.38,14.78,X40N,NTT,REALTY
86,VALIANTORG,-2.75,-42.36,202.15,74.15,190625.0,-69306.0,94299.0,838.0,-269.68,45.0,H-SC,5.87,145.0,-0.36,0.64,40.33,XR,NTT,CHEMICALS

In [12]:
# top 5 to exit based on CumlRnk
df_tmp = df_portfolio_features[~df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])]
df_tmp = df_tmp[(df_tmp['Current P/L%'] > -1) & (df_tmp['Current P/L%'] < 1)].sort_values(by = 'CumlRnk', ascending=False)
df_tmp[cols].head()

Empty DataFrame
Columns: [Symbol, Today P/L%, Current P/L%, FTT%, OTT%, FTT Amt, Current P/L, Current, FTT, Dev%_PE, RSI_14, Conviction, Spread%, CumlRnk, RRR Ind, CurrAlloc%, Gained%, Criteria, Strategy, Category]
Index: []

In [13]:
# OX40N stocks to exit
df_tmp = df_portfolio_features[(df_portfolio_features['Symbol'].isin(list_ox40n))].sort_values(by = 'Current P/L%', ascending=False)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
25,FINCABLES,-1.25,32.27,57.19,107.91,111683.0,47640.0,195284.0,1641.55,19.23,51.0,M-SC,25.44,220.0,0.43,1.32,46.92,OX40N,ATH,CABLES
72,SIS,-2.41,-6.53,29.73,21.26,30855.0,-7247.0,103785.0,528.00,2471.50,60.0,H-SC,19.30,168.0,-0.23,0.70,54.31,OX40N,NTT,MISC
16,CERA,1.95,-26.52,68.59,23.89,88659.0,-46643.0,129260.0,9475.00,-29.12,52.0,H-SC,5.31,153.0,-0.53,0.88,24.22,OX40N,NTT,CERAMICS
50,KANSAINER,0.27,-29.43,60.79,13.47,115692.0,-79353.0,190314.0,340.00,-39.37,49.0,H-SC,9.24,162.0,-0.69,1.29,32.94,XY24,NTT,PAINTS
83,TTKPRESTIG,-0.34,-30.87,44.78,0.09,31199.0,-31105.0,69672.0,770.00,61.79,52.0,M-SC,13.45,250.0,-1.00,0.47,24.06,OX40N,NTT,DURABLES

In [14]:
# top 5 to book for rotation
df_tmp = df_portfolio_features[(df_portfolio_features['Current P/L%'] > 20) ].sort_values(by = 'CumlRnk', ascending=False)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
25,FINCABLES,-1.25,32.27,57.19,107.91,111683.0,47640.0,195284.0,1641.55,19.23,51.0,M-SC,25.44,220.0,0.43,1.32,46.92,OX40N,ATH,CABLES
68,SATIN,-1.69,31.50,15.47,51.83,56203.0,87022.0,363306.0,274.00,18.27,70.0,H-SC,41.50,159.0,1.55,2.46,76.98,XY24,NTT,FINANCE

In [15]:
# top 5 to monitor for exit
df_tmp = df_portfolio_features[~df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])]
df_tmp = df_tmp[(df_tmp['Current P/L%'] > 0) ].sort_values(by = 'Dev%_PE', ascending=False)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
74,STARHEALTH,-0.57,1.21,45.51,47.26,129481.0,3389.0,284512.0,761.00,59.71,54.0,H-SC,9.83,173.0,0.03,1.93,24.91,XY24,NTT,INSURANCE
25,FINCABLES,-1.25,32.27,57.19,107.91,111683.0,47640.0,195284.0,1641.55,19.23,51.0,M-SC,25.44,220.0,0.43,1.32,46.92,OX40N,ATH,CABLES
68,SATIN,-1.69,31.50,15.47,51.83,56203.0,87022.0,363306.0,274.00,18.27,70.0,H-SC,41.50,159.0,1.55,2.46,76.98,XY24,NTT,FINANCE
91,ZYDUSLIFE,0.29,15.17,17.76,35.63,42868.0,31802.0,241376.0,1286.17,0.45,72.0,H-MC,10.07,120.0,0.74,1.64,26.91,AR,ATH,PHARMA
73,SONACOMS,-1.76,2.36,35.88,39.09,37153.0,2389.0,103548.0,804.02,-18.85,50.0,M-MC,18.84,193.0,0.06,0.70,46.48,AR,ATH,AUTO

In [16]:
# top 5 to book for rotation from weak conviction
df_tmp = df_portfolio_features[~df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])]
df_tmp = df_tmp[~df_tmp['Criteria'].isin(['XY25','XY24','X40', 'X40N'])].sort_values(by = 'RRR Ind', ascending=False)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
91,ZYDUSLIFE,0.29,15.17,17.76,35.63,42868.0,31802.0,241376.0,1286.17,0.45,72.0,H-MC,10.07,120.0,0.74,1.64,26.91,AR,ATH,PHARMA
25,FINCABLES,-1.25,32.27,57.19,107.91,111683.0,47640.0,195284.0,1641.55,19.23,51.0,M-SC,25.44,220.0,0.43,1.32,46.92,OX40N,ATH,CABLES
73,SONACOMS,-1.76,2.36,35.88,39.09,37153.0,2389.0,103548.0,804.02,-18.85,50.0,M-MC,18.84,193.0,0.06,0.70,46.48,AR,ATH,AUTO
42,INDIAMART,0.30,-13.78,139.76,106.72,148619.0,-16997.0,106339.0,4810.62,-61.13,46.0,H-SC,11.36,140.0,-0.11,0.72,2.95,AR,ATH,MISC
75,SURYODAY,-1.44,-3.54,27.55,23.03,47589.0,-6334.0,172737.0,216.00,88.60,61.0,H-SC,18.69,166.0,-0.13,1.17,45.44,XR,NTT,BANKS

In [17]:
# top 5 to accumulate based on lowest RSI_14
df_tmp = df_portfolio_features[df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])].sort_values(by = 'RSI_14', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
65,RELIANCE,-1.20,-18.12,53.04,25.30,87272.0,-36423.0,164540.0,1952.00,-20.42,30.0,X-LC,6.35,21.0,-0.42,1.12,0.00,XY25,BTT,REFINERIES
40,ICICIPRULI,-0.69,-20.59,64.05,30.28,100204.0,-40558.0,156447.0,787.27,-41.89,33.0,X-MC,14.63,78.0,-0.40,1.06,0.98,X40,ATH,INSURANCE
35,HDFCLIFE,-0.59,-6.46,42.39,33.18,59395.0,-9684.0,140116.0,814.30,-26.99,33.0,X-LC,15.19,31.0,-0.16,0.95,1.02,X40,ATH,INSURANCE
27,GLAXO,0.90,-12.34,54.80,35.69,95729.0,-24596.0,174688.0,3380.16,-33.11,34.0,X-MC,8.31,56.0,-0.26,1.19,0.90,X40,ATH,PHARMA
20,DABUR,-0.59,-17.56,74.32,43.70,151984.0,-43568.0,204500.0,735.00,-25.19,35.0,X-MC,9.61,70.0,-0.29,1.39,2.73,XY24,BTT,FMCG

In [18]:
# top 5 to accumulate based on Spread and CumlRnk
df_tmp = df_portfolio_features[df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])]
df_tmp = df_tmp[(df_tmp['CumlRnk'] < 100)].sort_values(by = 'Spread%', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
57,PAGEIND,0.51,0.52,32.89,33.59,88731.0,1401.0,269780.0,51217.30,-27.90,58.0,X-MC,2.84,55.0,0.02,1.83,28.12,X40,ATH,APPARELS
49,JSWINFRA,-3.29,-8.44,27.16,16.43,55150.0,-18717.0,203057.0,342.00,-21.44,46.0,X-MC,3.53,61.0,-0.34,1.38,14.78,X40N,NTT,REALTY
59,PIDILITIND,-0.14,4.49,13.28,18.37,19581.0,6340.0,147450.0,1670.26,-26.86,58.0,X-LC,4.13,5.0,0.32,1.00,15.77,X40,ATH,CHEMICALS
23,DMART,-0.79,-1.17,31.13,29.60,76795.0,-2910.0,246690.0,5391.45,-16.66,41.0,X-LC,4.15,14.0,-0.04,1.67,12.76,X40N,ATH,FMCG
19,COLPAL,0.71,-23.54,82.92,39.86,166976.0,-61995.0,201370.0,3683.41,-7.42,42.0,X-MC,4.16,62.0,-0.37,1.37,13.91,XY25,ATH,FMCG

In [19]:
# top 5 to accumulate based on lowest Gained%
df_tmp = df_portfolio_features[df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])].sort_values(by = 'Gained%', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
79,TCS,-1.27,-36.27,95.95,24.88,283285.0,-168031.0,295242.0,4253.91,-45.92,37.0,X-LC,18.58,2.0,-0.59,2.00,0.00,X40,ATH,IT
65,RELIANCE,-1.20,-18.12,53.04,25.30,87272.0,-36423.0,164540.0,1952.00,-20.42,30.0,X-LC,6.35,21.0,-0.42,1.12,0.00,XY25,BTT,REFINERIES
32,HAVELLS,-0.24,-26.52,78.85,31.42,190042.0,-86974.0,241017.0,2052.62,-30.94,37.0,X-MC,14.10,63.0,-0.46,1.64,0.39,X40,ATH,ELECTRICAL
27,GLAXO,0.90,-12.34,54.80,35.69,95729.0,-24596.0,174688.0,3380.16,-33.11,34.0,X-MC,8.31,56.0,-0.26,1.19,0.90,X40,ATH,PHARMA
34,HDFCBANK,-1.14,-11.64,45.28,28.37,93971.0,-27352.0,207533.0,1073.00,-24.98,38.0,X-LC,16.49,26.0,-0.29,1.41,0.96,X40,BTT,BANKS

In [20]:
# top 5 to accumulate based on lowest CurrAlloc%
df_tmp = df_portfolio_features[df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])].sort_values(by = 'CurrAlloc%', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
10,BATAINDIA,-0.63,-57.40,217.36,35.20,119150.0,-73853.0,54817.0,2096.00,-28.09,35.0,X-SC,25.48,91.0,-0.62,0.37,8.72,X40,NTT,FOOTWEAR
64,RELAXO,-1.64,-57.95,262.24,52.31,160056.0,-84126.0,61034.0,1176.00,-55.28,58.0,X-SC,21.73,92.0,-0.53,0.41,36.46,X40N,NTT,FOOTWEAR
60,QUESS,1.28,-2.09,77.61,73.90,81148.0,-2234.0,104559.0,424.00,-47.11,73.0,X-SC,5.52,80.0,-0.03,0.71,42.54,XY24,NTT,MISC
28,GODREJCP,-0.03,-10.71,47.24,31.47,62685.0,-15920.0,132694.0,1469.04,-6.00,40.0,X-LC,10.00,32.0,-0.25,0.90,1.81,X40N,ATH,FMCG
53,M&M,-1.75,-3.06,27.28,23.38,36673.0,-4248.0,134433.0,3802.40,-17.91,40.0,X-LC,10.07,25.0,-0.12,0.91,1.92,X40N,ATH,AUTO

In [21]:
# top 5 to accumulate based on CumlRnk
df_tmp = df_portfolio_features.sort_values(by = 'CumlRnk', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
47,ITC,0.87,-25.42,59.63,19.06,151283.0,-86464.0,253702.0,452.00,-59.16,40.0,X-LC,14.76,1.0,-0.57,1.72,2.22,X40,NTT,FMCG
79,TCS,-1.27,-36.27,95.95,24.88,283285.0,-168031.0,295242.0,4253.91,-45.92,37.0,X-LC,18.58,2.0,-0.59,2.00,0.00,X40,ATH,IT
45,INFY,-0.18,-18.63,64.98,34.24,165438.0,-58289.0,254599.0,1972.00,-36.14,50.0,X-LC,17.58,3.0,-0.35,1.73,9.16,X40,NTT,IT
81,TMPV,-2.16,-11.41,54.16,36.58,170740.0,-40589.0,315252.0,600.00,-81.44,60.0,X-LC,17.03,4.0,-0.24,2.14,31.40,XY24,NTT,AUTO
59,PIDILITIND,-0.14,4.49,13.28,18.37,19581.0,6340.0,147450.0,1670.26,-26.86,58.0,X-LC,4.13,5.0,0.32,1.00,15.77,X40,ATH,CHEMICALS

In [22]:
# top 5 for average up
df_tmp = df_portfolio_features[(df_portfolio_features['Dev%_200'] > 5)].sort_values(by = 'CurrAlloc%', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
44,INDUSINDBK,-1.09,-33.93,101.13,32.89,51588.0,-26194.0,51012.0,1800.00,-340.20,47.0,L-MC,7.27,258.0,-0.51,0.35,25.56,XR,NTT,BANKS
18,COFFEEDAY,-5.00,-38.27,119.12,35.27,83502.0,-43450.0,70099.0,80.00,-51.71,66.0,L-SC,19.41,266.0,-0.52,0.48,72.87,XR,NTT,HOTELS
3,ALKYLAMINE,1.95,-22.92,151.19,93.63,117665.0,-23137.0,77826.0,4546.37,-17.40,60.0,H-SC,9.32,142.0,-0.20,0.53,46.96,SR,ATH,CHEMICALS
73,SONACOMS,-1.76,2.36,35.88,39.09,37153.0,2389.0,103548.0,804.02,-18.85,50.0,M-MC,18.84,193.0,0.06,0.70,46.48,AR,ATH,AUTO
72,SIS,-2.41,-6.53,29.73,21.26,30855.0,-7247.0,103785.0,528.00,2471.50,60.0,H-SC,19.30,168.0,-0.23,0.70,54.31,OX40N,NTT,MISC

In [23]:
# top 5 RSP
df_tmp = df_portfolio_features.sort_values(by = 'RSP', ascending=False)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
18,COFFEEDAY,-5.00,-38.27,119.12,35.27,83502.0,-43450.0,70099.0,80.00,-51.71,66.0,L-SC,19.41,266.0,-0.52,0.48,72.87,XR,NTT,HOTELS
37,HONAUT,1.82,-8.39,65.18,51.31,115140.0,-16188.0,176650.0,58357.33,-23.87,64.0,X-SC,7.28,90.0,-0.14,1.20,34.21,X40N,ATH,ELECTRICAL
91,ZYDUSLIFE,0.29,15.17,17.76,35.63,42868.0,31802.0,241376.0,1286.17,0.45,72.0,H-MC,10.07,120.0,0.74,1.64,26.91,AR,ATH,PHARMA
69,SFL,3.96,-34.25,92.61,26.63,159656.0,-89822.0,172396.0,1287.00,30.59,71.0,M-SC,7.81,242.0,-0.56,1.17,43.68,XY24,NTT,MISC
68,SATIN,-1.69,31.50,15.47,51.83,56203.0,87022.0,363306.0,274.00,18.27,70.0,H-SC,41.50,159.0,1.55,2.46,76.98,XY24,NTT,FINANCE

In [24]:
# Top N allocation
df_tmp = df_portfolio_features.sort_values(by = 'CurrAlloc%', ascending=False)
top_n_values = [10, 25, 50]

sum_df = pd.DataFrame({
    'Top_N': top_n_values,
    'Sum_Alloc%': [df_tmp['CurrAlloc%'].head(n).sum() for n in top_n_values]
})

sum_df

   Top_N  Sum_Alloc%
0     10       19.79
1     25       42.76
2     50       72.82

In [25]:
# market-cap-wise allocation
df_tmp = df_portfolio_features[cols]
df_tmp.groupby(df_tmp['Conviction'].str[-2:])['CurrAlloc%'].sum().sort_values(ascending=False)

Conviction
SC    43.17
LC    31.31
MC    25.52
Name: CurrAlloc%, dtype: float64

In [26]:
# criteria-wise allocation
df_portfolio_features.groupby('Criteria')['CurrAlloc%'].sum().sort_values(ascending=False)

Criteria
XY24     27.92
X40      24.96
X40N     16.97
XR        8.99
OX40N     6.87
AR        6.86
XY25      6.55
SR        0.88
Name: CurrAlloc%, dtype: float64

In [27]:
# conviction-wise allocation
df_portfolio_features.groupby('Conviction')['CurrAlloc%'].sum().sort_values(ascending=False)

Conviction
X-LC    29.19
H-SC    22.68
X-MC    20.39
M-SC     9.99
X-SC     9.85
H-MC     2.79
M-MC     1.99
H-LC     1.24
M-LC     0.88
L-SC     0.65
L-MC     0.35
Name: CurrAlloc%, dtype: float64

In [28]:
# sector-wise stats
df_tmp = df_portfolio_features.groupby('Category')[['CurrAlloc%', 'Current', 'Current P/L', 'FTT Amt']].sum().sort_values(by=['Current', 'Current P/L'], ascending=False)
df_tmp['Current P/L%'] = round(df_tmp['Current P/L'] * 100 / df_tmp['Current'], 2)
df_tmp['FTT%'] = round(df_tmp['FTT Amt'] * 100 / df_tmp['Current'], 2)
cols = ['CurrAlloc%', 'Current P/L%', 'FTT%']
df_tmp[cols].sort_values(by=['CurrAlloc%'], ascending=False)

               CurrAlloc%  Current P/L%    FTT%
Category
FMCG                14.90        -20.56   62.85
FINANCE             10.87        -15.06   65.11
IT                  10.23        -49.29  123.93
MISC                 7.11        -27.88   83.43
AUTO                 6.84         -8.46   49.13
BANKS                5.73         -7.59   57.35
PAINTS               5.49        -21.88   43.05
INSURANCE            5.20         -8.00   44.52
PHARMA               5.06          0.57   30.21
ELECTRICAL           4.08        -17.76   59.32
CHEMICALS            2.17        -26.94  102.60
HEALTHCARE           2.09        -16.54   46.95
AC                   1.85        -16.81   48.49
APPARELS             1.83          0.52   32.89
FOOTWEAR             1.71        -74.15  143.98
TRAVEL               1.60        -90.09  185.28
DURABLES             1.56        -67.95  108.81
BREWERIES            1.45         -9.43   32.15
REALTY               1.38         -9.22   27.16
CERAMICS             1.35        -55.03  102.13
CABLES               1.32         24.40   57.19
ENGINEERING          1.32        -24.10   80.86
REFINERIES           1.12        -22.14   53.04
CEMENT               1.08        -68.23  194.08
JEWELLERY            1.03       -110.28  183.35
ENTERTAINMENT        0.74        -76.86  182.35
HOTELS               0.48        -61.98  119.12
TEXTILES             0.41        -54.40   98.43

In [29]:
# money to be made criteria-wise
df_portfolio_features.groupby('Criteria')['FTT Amt'].agg(['sum', 'count']).sort_values(by='sum', ascending=False)

                sum  count
Criteria
XY24      3480986.0     21
X40       2005188.0     19
XR        1359723.0     13
X40N      1220008.0     13
AR        1171611.0      9
OX40N      777356.0     10
XY25       471999.0      5
SR         289309.0      2

In [30]:
# money to be made conviction-wise
df_portfolio_features.groupby('Conviction')['FTT Amt'].agg(['sum', 'count']).sort_values(by='sum', ascending=False)

                  sum  count
Conviction
H-SC        3439834.0     24
X-LC        1984712.0     21
X-MC        1713210.0     15
M-SC        1443529.0     14
X-SC        1353162.0      9
H-MC         287504.0      2
L-SC         195915.0      2
M-LC         162900.0      1
M-MC          92902.0      2
L-MC          51588.0      1
H-LC          50924.0      1

In [31]:
# money to be made criteria and conviction-wise
df_portfolio_features.groupby(['Conviction', 'Criteria'])['FTT Amt'].agg(['sum', 'count']).sort_values(by='sum', ascending=False)

                           sum  count
Conviction Criteria
X-LC       X40       1071523.0     10
H-SC       XY24      1037579.0      6
           AR         964073.0      5
M-SC       XY24       836394.0      6
H-SC       XR         818771.0      7
X-SC       XY24       793886.0      4
X-MC       X40        716038.0      7
           X40N       505071.0      4
X-LC       X40N       373288.0      6
X-SC       X40N       341649.0      3
M-SC       OX40N      334841.0      5
H-SC       OX40N      330102.0      4
X-LC       XY24       323760.0      2
H-SC       SR         289309.0      2
X-MC       XY25       247370.0      2
           XY24       244731.0      2
H-MC       XY24       244636.0      1
X-SC       X40        217627.0      2
M-SC       XR         195701.0      2
X-LC       XY25       168880.0      2
M-LC       XR         162900.0      1
L-SC       OX40N      112413.0      1
           XR          83502.0      1
M-SC       AR          76593.0      1
M-MC       XY25        55749.0      1
L-MC       XR          51588.0      1
H-LC       AR          50924.0      1
X-LC       XR          47261.0      1
H-MC       AR          42868.0      1
M-MC       AR          37153.0      1

In [32]:
# notebook execution time

end_time = time.time()
execution_time = round(end_time - start_time, 0)
print(f"Notebook execution time: {execution_time} seconds")

Notebook execution time: 25.0 seconds