<a href="https://colab.research.google.com/github/ankit-rathi/Quantvesting_v2/blob/main/myStocks_Portfolio_Analysis.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
'''
!pip install pandas==2.2.2 -qq
!pip install pyxirr -qq
!pip install ta -qq
!pip install yfinance==0.2.59 -qq
'''

'\n!pip install pandas==2.2.2 -qq\n!pip install pyxirr -qq\n!pip install ta -qq\n!pip install yfinance==0.2.59 -qq\n'

In [2]:
# import libraries

import numpy as np
import pandas as pd
import datetime
import warnings
warnings.filterwarnings('ignore')
import yfinance as yfin
import ta
import matplotlib.pyplot as plt
import requests

In [3]:
# notebook start time
import time
import datetime
import pytz

start_time = time.time()

# function to print date timestamp
def print_date_time():
  tz_NY = pytz.timezone('Asia/Kolkata')
  datetime_NY = datetime.datetime.now(tz_NY)
  print("Run date time (IST):", datetime_NY.strftime("%Y-%m-%d %H:%M:%S"))

In [4]:
# function to get booked and reserved amount
def get_amt():
  # fetch the JSON data from the URL
  url = "https://raw.githubusercontent.com/ankit-rathi/Tradevesting_v1/main/data/myPortfolioAmts.json"
  response = requests.get(url)
  pf_amts = response.json()  # parse the JSON data

  # extract values from the JSON
  py_booked_amt_dm = pf_amts["py_booked_amt_dm"]
  py_booked_amt_sv = pf_amts["py_booked_amt_sv"]
  cy_booked_amt_dm = pf_amts["cy_booked_amt_dm"]
  cy_booked_amt_sv = pf_amts["cy_booked_amt_sv"]
  reserve_amt_dm = pf_amts["reserve_amt_dm"]
  reserve_amt_sv = pf_amts["reserve_amt_sv"]

  # perform calculations
  py_booked_amt = py_booked_amt_dm + py_booked_amt_sv
  cy_booked_amt = cy_booked_amt_dm + cy_booked_amt_sv
  reserve_amt = reserve_amt_dm + reserve_amt_sv
  total_booked_amt = py_booked_amt + cy_booked_amt

  return total_booked_amt, reserve_amt, cy_booked_amt, py_booked_amt

gen_output = 0

In [5]:
# function to format the amount
def format_amt(number):
    abs_number = abs(number)

    if abs_number >= 1_00_00_000:  # Crores
        formatted_amt = f"{number / 1_00_00_000:.2f} C"
    elif abs_number >= 1_00_000:  # Lakhs
        formatted_amt = f"{number / 1_00_000:.2f} L"
    elif abs_number >= 1_000:  # Thousands
        formatted_amt = f"{number / 1_000:.2f} K"
    else:
        formatted_amt = f"{number:.2f}"

    return formatted_amt

# function to set start and end date
def get_start_end_date():
  start_date = (datetime.date.today() + datetime.timedelta(days=-365)).strftime('%Y-%m-%d')
  end_date = (datetime.date.today() + datetime.timedelta(days=1)).strftime('%Y-%m-%d')
  return start_date, end_date

# function to fetch my portfolio csv
def get_mypfs_df():
  mypfs_df = pd.read_csv('https://raw.githubusercontent.com/ankit-rathi/Tradevesting_v1/main/data/myPortfolioStocks.csv')
  return mypfs_df

# function to fetch my prospects csv
def get_mypps_df():
  mypps_df = pd.read_csv('https://raw.githubusercontent.com/ankit-rathi/Tradevesting_v1/main/data/myProspectsScrips.csv')
  return mypps_df

# function to fetch screener data
def get_myscreen_df():
  myscreen_df = pd.read_csv('https://raw.githubusercontent.com/ankit-rathi/Tradevesting_v1/main/data/myScreenerDB.csv')
  return myscreen_df

# function to fetch momentum data
def get_myinvmt_df():
  myinvmt_df = pd.read_csv('https://raw.githubusercontent.com/ankit-rathi/Tradevesting_v1/main/data/myInvestments.csv')
  return myinvmt_df

# function to get the stock ids
def get_stock_ids(df_pf):
  stock_n100 = df_pf['Symbol'].unique()

  exclude = ['CADILAHC','MMTC', 'MASFIN']

  stock_ids = df_pf[~df_pf['Symbol'].isin(exclude) ]['Symbol'].unique()

  #mypf = mypf[mypf.Forecast.notnull()]
  #stock_ids = mypf['Symbol'].unique()

  #stock_ids.sort()
  return stock_ids

# get features from screener data
def get_screener_features():
  myscreen_df = get_myscreen_df()
  cols = ['Symbol', 'EPS', 'MedPE', 'ROCE%', 'ROE%', 'CapType']
  return myscreen_df[cols]

# get relative strength
def get_relative_strength(stock_list):

    # Dictionary to store stock tickers and their corresponding percentage price change
    stock_changes = {}

    # Loop through each stock and fetch its price data
    for stock in stock_list:
        try:
            # Download the stock data for the given date range
            stock_data = yfin.Ticker(stock + '.NS').history(period='1mo', interval='1d')[map(str.title, ['open', 'close', 'low', 'high', 'volume'])]

            # Calculate the percentage change for the stock
            if len(stock_data) > 0:
                start_price = stock_data['Close'].iloc[0]
                end_price = stock_data['Close'].iloc[-1]
                percent_change = round(((end_price - start_price) / start_price) * 100, 2)
                stock_changes[stock] = percent_change
            else:
                stock_changes[stock] = np.nan  # If no data is available, set to NaN

        except Exception as e:
            print(f"Error fetching data for {stock}: {e}")
            stock_changes[stock] = np.nan

    # Create a DataFrame with stock tickers and their percentage changes
    df = pd.DataFrame(list(stock_changes.items()), columns=['Symbol', 'Percent_Change'])

    # Drop any stocks with missing data (NaN values)
    df = df.dropna()

    # Calculate the percentile rank based on percentage change
    df['RSP'] = round(df['Percent_Change'].rank(pct=True) * 100, 2)
    cols = ['Symbol', 'RSP']
    df = df[cols]
    # Sort by percentile rank (optional)
    df = df.sort_values(by='RSP', ascending=False).reset_index(drop=True)

    return df

In [6]:
# function to get stock technicals
def stock_prec_dev(stock_symbol):
    #stock_symbol = 'ULTRACEMCO.NS'
    short_window = 20
    mid_window = 50
    long_window = 200
    moving_avg = 'SMA'

    start = datetime.datetime(*map(int, start_date.split('-')))
    end = datetime.datetime(*map(int, end_date.split('-')))

    stock_df = yfin.Ticker(stock_symbol + '.NS').history(period='max', interval='1d')[map(str.title, ['open', 'close', 'low', 'high', 'volume'])]

    stock_df['Max'] = round(max(stock_df['Close']),2)
    stock_df = stock_df[(stock_df.index <= end_date) & (stock_df.index >= start_date)]
    stock_df['200_SMA'] = round(stock_df['Close'].rolling(window = 200, min_periods = 1).mean(),0)
    stock_df['Dev%_200'] = round((stock_df['Close'] - stock_df['200_SMA'])*100/stock_df['200_SMA'],2)
    stock_df.dropna(axis = 0, inplace = True) # remove any null rows

    stock_df['20_SMA'] = stock_df['Close'].rolling(window=20).mean()
    stock_df['50_SMA'] = stock_df['Close'].rolling(window=50).mean()
    stock_df['Symbol'] = stock_symbol

    stock_df['Close'] = round(stock_df['Close'],2)
    stock_df['Min'] = round(min(stock_df['Close']),2)
    stock_df['RSI_14'] = ta.momentum.RSIIndicator(close=stock_df['Close'], window=14).rsi()
    stock_df['RSI_14'] = round(stock_df['RSI_14'],0)
    stock_df['Prev_Close'] = stock_df['Close'].shift(1)
    stock_df.drop(['Open', 'Low', 'High', 'Volume'], axis=1, inplace=True)
    stock_df = stock_df.tail(1)

    max_SMA = max(stock_df['20_SMA'].item(), stock_df['50_SMA'].item(), stock_df['200_SMA'].item())
    min_SMA = min(stock_df['20_SMA'].item(), stock_df['50_SMA'].item(), stock_df['200_SMA'].item())
    ABS_Spread = max_SMA - min_SMA
    stock_df['Spread%'] = round((ABS_Spread / stock_df['200_SMA'].item()) * 100,2)

    return stock_df

# function to compute stock attributes
def get_common_features(stock_ids, df_mypf):

  df_prec_dev = pd.DataFrame()
  df_tmp = get_screener_features()
  df_rs = get_relative_strength(stock_ids)

  for stock_id in stock_ids:
      tmp = stock_prec_dev(stock_id)
      tmp = tmp.reset_index()
      df_prec_dev = pd.concat([df_prec_dev, tmp], ignore_index = True)
  df_prec_dev = pd.merge(df_prec_dev, df_mypf, on= 'Symbol')
  df_prec_dev = pd.merge(df_prec_dev, df_tmp, on= 'Symbol', how='left')
  df_prec_dev = pd.merge(df_prec_dev, df_rs, on= 'Symbol', how='left')
  #print(df_prec_dev.columns)
  df_prec_dev['Curr_PE'] = round(df_prec_dev['Close']/df_prec_dev['EPS'],1)
  df_prec_dev['Dev%_PE'] = round((df_prec_dev['Curr_PE'] - df_prec_dev['MedPE'])*100/df_prec_dev['MedPE'],2)
  df_prec_dev['Conviction'] = df_prec_dev['Conviction'] + '-' + df_prec_dev['CapType']
  return df_prec_dev

# function to arrange stock features
def arrange_features(df_stocks, common_cols, diff_cols):
  df_stocks_common = df_stocks[common_cols].drop_duplicates()
  df_stocks_diff = df_stocks[diff_cols]
  df_stocks_diff['Investment'] = df_stocks_diff['AvgCost'] * df_stocks_diff['Shares']
  df_stocks_diff = df_stocks_diff.groupby(['Symbol'])[['Shares', 'Investment']].aggregate(['sum']).reset_index()
  df_stocks_diff.columns = ['Symbol', 'Shares', 'Investment']
  df_stocks_diff['AvgCost'] = round(df_stocks_diff['Investment']/df_stocks_diff['Shares'],2)
  df_stocks = pd.merge(df_stocks_diff, df_stocks_common, on='Symbol')
  return df_stocks

# plot fact distribution across dimension
def plot_pie_chart(df, dimension, fact):
  # grouping the data by category and calculating the sum of fact for each type
  grouped_data = df.groupby(dimension)[fact].sum()

  # sorting the grouped data in descending order
  grouped_data = grouped_data.sort_values(ascending=False)

  # creating a pie chart
  grouped_data.plot.pie(autopct='%1.1f%%', startangle=90, figsize=(6, 6))

  # adding a title and displaying the plot
  plt.title(f'{dimension} {fact} Distribution')
  plt.ylabel('')  # To hide the y-label
  plt.show()

In [7]:
# function to get portfolio features

def get_portfolio_features(df_common_features):

  print_date_time()
  print('-------------------')

  #df_common_features["Target"] = df_common_features["Target"].fillna(df_common_features["Max"])
  df_common_features['NTT'] = np.where(df_common_features['Strategy']== 'NTT', df_common_features["Target"], df_common_features['Max'])
  df_common_features['LTT'] = np.where(df_common_features['Strategy']== 'BTT', df_common_features["Target"], df_common_features['Max'])
  df_common_features['BOL'] = df_common_features['Min']

  tmp_df = df_common_features[df_common_features['Symbol'].isin(mypf_df[mypf_df['InPortfolio'] != 'NA'].Symbol.values)]
  print('qualified stocks: '+str(len(tmp_df['Symbol'].unique())))
  tmp_df1 = tmp_df[tmp_df['LatestQtr'] == 1]
  print('with latest results: '+str(len(tmp_df1['Symbol'].unique())))
  tmp_df1 = tmp_df1[tmp_df1['StarStock'] == 1]
  print('still star stocks: '+str(len(tmp_df1['Symbol'].unique())))
  tmp_df['Investment'] = tmp_df['AvgCost'] * tmp_df['Shares']
  tmp_df['Current'] = round(tmp_df['Close'] * tmp_df['Shares'],0)
  tmp_df['Previous'] = tmp_df['Prev_Close'] * tmp_df['Shares']
  tmp_df['EstimatedST'] = tmp_df['NTT'] * tmp_df['Shares']
  tmp_df['EstimatedLT'] = tmp_df['LTT'] * tmp_df['Shares']
  tmp_df['Current P/L'] = round((tmp_df['Current'] - tmp_df['Investment']),0)
  tmp_df['Today P/L%'] = round((tmp_df['Current'] - tmp_df['Previous'])*100/tmp_df['Previous'],2)
  tmp_df['Current P/L%'] = round((tmp_df['Current'] - tmp_df['Investment'])*100/tmp_df['Investment'],2)
  tmp_df['EstimatedST P/L%'] = round((tmp_df['EstimatedST'] - tmp_df['Investment'])*100/tmp_df['Investment'],2)
  tmp_df['EstimatedLT P/L%'] = round((tmp_df['EstimatedLT'] - tmp_df['Investment'])*100/tmp_df['Investment'],2)
  tmp_df['NTT%'] = round((tmp_df['NTT'] - tmp_df['Close'])*100/tmp_df['Close'],2)
  tmp_df['LTT%'] = round((tmp_df['LTT'] - tmp_df['Close'])*100/tmp_df['Close'],2)
  tmp_df['Gained%'] = round((tmp_df['Close'] - tmp_df['BOL'])*100/tmp_df['BOL'],2)
  investment = round(sum(tmp_df['AvgCost']*tmp_df['Shares']),0)
  current = round(sum(tmp_df['Close']*tmp_df['Shares']),0)
  tmp_df['InitAlloc%'] = round(tmp_df['Investment']*100/investment,2)
  tmp_df['CurrAlloc%'] = round(tmp_df['Current']*100/current,2)
  tmp_df['FTT'] = tmp_df['LTT']
  tmp_df.loc[tmp_df['Strategy'] == 'NTT', 'FTT'] = tmp_df['NTT']
  tmp_df['FTT%'] = tmp_df['LTT%']
  tmp_df.loc[tmp_df['Strategy'] == 'NTT', 'FTT%'] = tmp_df['NTT%']
  tmp_df['FTT Amt'] = round(tmp_df['FTT%'] * tmp_df['Current']/100,0)
  tmp_df['OTT%'] = round((tmp_df['FTT'] - tmp_df['AvgCost'])*100/tmp_df['AvgCost'],2)
  tmp_df['RRR Ind'] = round(tmp_df['Current P/L']/tmp_df['FTT Amt'],2)
  tmp_df['Risk Ind'] = round(tmp_df['Current P/L%']*tmp_df['CurrAlloc%'],0)

  return tmp_df

# function to print portfolio features
def print_portfolio_stats(df_portfolio_features, myinvmt_df):
  from pyxirr import xirr

  total_booked_amt, reserve_amt, cy_booked_amt, py_booked_amt = get_amt()

  dates = myinvmt_df['Date'].values
  dates = np.append(dates, datetime.date.today().strftime('%d-%b-%y'))
  investment = myinvmt_df['Investment'].values
  dates= pd.to_datetime(dates)

  current = round(sum(df_portfolio_features['Close']*df_portfolio_features['Shares']),0) + reserve_amt
  investment_xirr = np.append(investment, current)
  cagr = round(xirr(pd.DataFrame({"dates": dates, "amounts": investment_xirr}))*100,2)

  investment = -sum(investment)
  invested = round(sum(df_portfolio_features['AvgCost']*df_portfolio_features['Shares']),0) + reserve_amt
  previous = round(sum(df_portfolio_features['Prev_Close']*df_portfolio_features['Shares']),0) + reserve_amt
  cy_invested = investment + py_booked_amt

  today_pnl_amount = current-previous
  today_pnl_percentage = round((current-previous)*100/previous,2)

  curr_pnl_amount = current-invested
  curr_pnl_percentage = round((curr_pnl_amount)*100/(cy_invested),2)

  cy_pnl_amount = cy_booked_amt + curr_pnl_amount
  cy_pnl_percentage = round((cy_pnl_amount)*100/cy_invested,2)

  overall_pnl_amount = total_booked_amt + curr_pnl_amount
  overall_pnl_percentage = round((overall_pnl_amount)*100/investment,2)

  estimate_st = round(sum(df_portfolio_features['FTT']*df_portfolio_features['Shares']),0)  + reserve_amt
  est_st_pnl_amount = estimate_st-current
  est_st_pnl_percentage = round((est_st_pnl_amount)*100/current,2)

  estimate_lt = round(sum(df_portfolio_features['LTT']*df_portfolio_features['Shares']),0)  + reserve_amt
  est_lt_pnl_amount = estimate_lt-current
  est_lt_pnl_percentage = round((est_lt_pnl_amount)*100/current,2)

  total_profit = round(sum(df_portfolio_features[df_portfolio_features['Current P/L%'] > 0]['Current']) - sum(df_portfolio_features[df_portfolio_features['Current P/L%'] > 0]['Investment']),0)
  total_loss = round(sum(df_portfolio_features[df_portfolio_features['Current P/L%'] < 0]['Current']) - sum(df_portfolio_features[df_portfolio_features['Current P/L%'] < 0]['Investment']),0)

  cy_booked_percentage = round((cy_booked_amt)*100/current,2)
  py_booked_percentage = round((py_booked_amt)*100/investment,2)
  total_booked_percentage = round((total_booked_amt)*100/investment,2)

  print('-------------------')
  print('Initial Investment: ', format_amt(investment))
  print('CY Investment: ', format_amt(cy_invested))
  print('Reserve: ', format_amt(reserve_amt))
  print('Current: ',  format_amt(current))
  print('-------------------')
  print('Today PnL: '+ '{} ({}%)'.format(format_amt(today_pnl_amount), today_pnl_percentage))
  print('Current PnL: '+ '{} ({}%)'.format(format_amt(curr_pnl_amount), curr_pnl_percentage))
  print('CY Booked + Current PnL: '+ '{} ({}%)'.format(format_amt(cy_pnl_amount), cy_pnl_percentage))
  print('-------------------')
  print('Total profit: ', format_amt(total_profit))
  print('Total loss: ', format_amt(total_loss))
  print('-------------------')
  print('Total Booked + Current PnL: '+ '{} ({}%)'.format(format_amt(overall_pnl_amount), overall_pnl_percentage))
  print('Total Booked PnL: '+ '{} ({}%)'.format(format_amt(total_booked_amt), total_booked_percentage))
  print('Curr Year Booked PnL: '+ '{} ({}%)'.format(format_amt(cy_booked_amt), cy_booked_percentage))
  print('Prev Year Booked PnL: '+ '{} ({}%)'.format(format_amt(py_booked_amt), py_booked_percentage))
  print('===================')
  print('Est FTT: ',  format_amt(estimate_st))
  print('Est FTT PnL: '+ '{} ({}%)'.format(format_amt(est_st_pnl_amount), est_st_pnl_percentage))

  print('===================')
  print('Deployed: ', format_amt(investment))

  print('Current: ', format_amt(current))

  print('CAGR/XIRR %: '+'{}%'.format(cagr))

In [8]:
# get start and end date
start_date, end_date = get_start_end_date()

# get portfolio and prospects data
mypfs_df = get_mypfs_df()
mypps_df = get_mypps_df()
myinvmt_df = get_myinvmt_df()

# merge above datasets
mypf_df = pd.merge(mypfs_df, mypps_df, on="Symbol")

# seggregate dm and sv portfolio
dm_pf = mypf_df[mypf_df['InPortfolio'] == 'DM']
sv_pf = mypf_df[mypf_df['InPortfolio'] == 'SV']

# build portfolio stock dataframe
dm_stocks = get_stock_ids(dm_pf)
sv_stocks = get_stock_ids(sv_pf)
df_stocks = pd.concat([dm_pf,sv_pf], ignore_index = True)

# arrange common and diff stock features
common_cols = ['Symbol', 'Target', 'Criteria', 'Strategy', 'CumlRnk', 'LatestQtr', 'StarStock', 'Conviction', 'Category', 'InFolio', 'XIRR', 'MBQ']
diff_cols = ['Symbol', 'AvgCost', 'Shares']
df_stocks = arrange_features(df_stocks, common_cols, diff_cols)

# get common features
stock_ids = df_stocks['Symbol'].values
df_common_features = get_common_features(stock_ids, df_stocks)

df_common_features.reset_index(drop=True, inplace=True)
df_common_features.drop(['Date'], axis=1, inplace=True)
# get and print portfolio features
df_portfolio_features = get_portfolio_features(df_common_features)

print_portfolio_stats(df_portfolio_features, myinvmt_df)

df = df_portfolio_features
#plot_pie_chart(df, 'CapType', 'Current')
list_ox40n = list(df[df['MBQ'].str.contains('OX40N', na=False)]['Symbol'].values)

Run date time (IST): 2026-08-13 15:33:17
-------------------
qualified stocks: 88
with latest results: 30
still star stocks: 19
-------------------
Initial Investment:  1.46 C
CY Investment:  1.89 C
Reserve:  2.21 L
Current:  1.61 C
-------------------
Today PnL: -17.28 K (-0.11%)
Current PnL: -31.84 L (-16.85%)
CY Booked + Current PnL: -27.19 L (-14.39%)
-------------------
Total profit:  3.83 L
Total loss:  -35.67 L
-------------------
Total Booked + Current PnL: 15.68 L (10.73%)
Total Booked PnL: 47.52 L (32.53%)
Curr Year Booked PnL: 4.65 L (2.89%)
Prev Year Booked PnL: 42.87 L (29.35%)
===================
Est FTT:  2.68 C
Est FTT PnL: 1.07 C (66.64%)
===================
Deployed:  1.46 C
Current:  1.61 C
CAGR/XIRR %: 4.37%

In [9]:
# top 5 near their targets
cols = ['Symbol', 'Today P/L%', 'Current P/L%', 'FTT%', 'OTT%', 'FTT Amt', 'Current P/L', 'Current', 'FTT', 'Dev%_PE', 'RSI_14','Conviction', 'Spread%',  'CumlRnk', 'RRR Ind', 'CurrAlloc%', 'Gained%', 'Criteria', 'Strategy', 'Category']
df_tmp = df_portfolio_features[~df_portfolio_features['Symbol'].isin(['ENRIN','BLUSPRING','DIGITIDE'])]
df_tmp = df_tmp.sort_values(by = 'FTT Amt', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
78,TTKPRESTIG,2.50,-21.88,28.13,0.09,22145.0,-22053.0,78724.0,770.00,82.71,43.0,M-SC,11.50,250.0,-1.00,0.50,41.69,OX40N,NTT,DURABLES
79,UNITDSPR,-1.30,11.29,8.51,20.77,22175.0,26436.0,260580.0,1644.00,-1.23,63.0,X-MC,9.04,64.0,1.19,1.64,25.26,X40N,NTT,BREWERIES
68,SIS,-0.91,-0.14,21.44,21.26,23771.0,-158.0,110874.0,528.00,2647.15,53.0,H-SC,22.26,168.0,-0.01,0.70,64.85,OX40N,NTT,MISC
52,M&M,0.72,8.25,9.76,18.82,25429.0,19862.0,260543.0,3762.88,-5.74,60.0,X-LC,4.55,25.0,0.78,1.64,18.19,X40N,ATH,AUTO
87,ZYDUSLIFE,-3.13,23.09,10.08,35.51,26004.0,48399.0,257973.0,1285.01,7.21,59.0,H-MC,15.94,120.0,1.86,1.63,35.76,AR,ATH,PHARMA

In [10]:
# top 5 today
df_tmp = df_portfolio_features.sort_values(by = 'Today P/L%', ascending=False)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
82,VALIANTORG,5.00,-29.02,145.35,74.15,168791.0,-47478.0,116127.0,838.00,-308.98,79.0,H-SC,4.68,145.0,-0.28,0.73,72.81,XR,NTT,CHEMICALS
28,GODREJCP,3.52,-14.77,55.94,32.90,118971.0,-36861.0,212676.0,1460.97,-11.86,32.0,X-LC,5.07,32.0,-0.31,1.34,3.52,X40N,ATH,FMCG
21,DEN,2.59,-47.55,170.86,42.07,75698.0,-40160.0,44304.0,75.00,58.03,49.0,M-SC,5.65,235.0,-0.53,0.28,20.50,AR,NTT,ENTERTAINMENT
78,TTKPRESTIG,2.50,-21.88,28.13,0.09,22145.0,-22053.0,78724.0,770.00,82.71,43.0,M-SC,11.50,250.0,-1.00,0.50,41.69,OX40N,NTT,DURABLES
51,LAOPALA,2.33,-41.77,138.86,39.09,106011.0,-54761.0,76344.0,464.00,66.91,60.0,H-SC,4.97,154.0,-0.52,0.48,18.45,AR,NTT,CERAMICS

In [11]:
# bottom 5 today
df_tmp = df_portfolio_features.sort_values(by = 'Today P/L%', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
55,PAGEIND,-4.64,-4.75,40.24,33.59,102870.0,-12739.0,255640.0,51217.29,-31.67,29.0,X-MC,8.84,55.0,-0.12,1.61,21.40,X40,ATH,APPARELS
24,EASEMYTRIP,-4.33,-65.84,326.49,45.70,197206.0,-116413.0,60402.0,26.40,-37.27,28.0,M-SC,6.55,204.0,-0.59,0.38,5.81,XY24,NTT,TRAVEL
87,ZYDUSLIFE,-3.13,23.09,10.08,35.51,26004.0,48399.0,257973.0,1285.01,7.21,59.0,H-MC,15.94,120.0,1.86,1.63,35.76,AR,ATH,PHARMA
70,SURYODAY,-2.80,-10.92,38.12,23.03,60808.0,-19553.0,159518.0,216.00,73.25,35.0,H-SC,16.41,166.0,-0.32,1.01,35.40,XR,NTT,BANKS
29,GREENPANEL,-2.77,-54.21,212.63,43.14,178235.0,-99254.0,83824.0,537.00,87.98,30.0,M-SC,10.17,225.0,-0.56,0.53,0.95,XY24,NTT,MISC

In [12]:
# top 5 to exit based on CumlRnk
df_tmp = df_portfolio_features[~df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])]
df_tmp = df_tmp[(df_tmp['Current P/L%'] > -1) & (df_tmp['Current P/L%'] < 1)].sort_values(by = 'CumlRnk', ascending=False)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
80,UTIAMC,-0.94,0.11,50.98,51.15,113472.0,252.0,222582.0,1371.68,-19.39,48.0,M-SC,7.65,229.0,0.00,1.4,4.26,XY24,ATH,FINANCE
68,SIS,-0.91,-0.14,21.44,21.26,23771.0,-158.0,110874.0,528.00,2647.15,53.0,H-SC,22.26,168.0,-0.01,0.7,64.85,OX40N,NTT,MISC

In [13]:
# OX40N stocks to exit
df_tmp = df_portfolio_features[(df_portfolio_features['Symbol'].isin(list_ox40n))].sort_values(by = 'Current P/L%', ascending=False)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
25,FINCABLES,-2.40,58.23,31.40,107.91,73356.0,85975.0,233619.0,1641.55,42.57,72.0,M-SC,18.15,220.0,1.17,1.47,75.76,OX40N,ATH,CABLES
68,SIS,-0.91,-0.14,21.44,21.26,23771.0,-158.0,110874.0,528.00,2647.15,53.0,H-SC,22.26,168.0,-0.01,0.70,64.85,OX40N,NTT,MISC
43,INDIGOPNTS,0.74,-19.70,24.56,0.02,34426.0,-34389.0,140170.0,1408.00,113.73,63.0,M-SC,5.96,222.0,-1.00,0.88,59.03,OX40N,NTT,PAINTS
78,TTKPRESTIG,2.50,-21.88,28.13,0.09,22145.0,-22053.0,78724.0,770.00,82.71,43.0,M-SC,11.50,250.0,-1.00,0.50,41.69,OX40N,NTT,DURABLES
16,CERA,0.68,-22.52,59.90,23.89,81635.0,-39617.0,136286.0,9475.00,-25.30,40.0,H-SC,12.42,153.0,-0.49,0.86,32.48,OX40N,NTT,CERAMICS

In [14]:
# top 5 to book for rotation
df_tmp = df_portfolio_features[(df_portfolio_features['Current P/L%'] > 20) ].sort_values(by = 'CumlRnk', ascending=False)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
25,FINCABLES,-2.40,58.23,31.40,107.91,73356.0,85975.0,233619.0,1641.55,42.57,72.0,M-SC,18.15,220.0,1.17,1.47,75.76,OX40N,ATH,CABLES
87,ZYDUSLIFE,-3.13,23.09,10.08,35.51,26004.0,48399.0,257973.0,1285.01,7.21,59.0,H-MC,15.94,120.0,1.86,1.63,35.76,AR,ATH,PHARMA
57,QUESS,-0.30,36.66,27.25,73.90,39769.0,39149.0,145942.0,424.00,-26.72,68.0,X-SC,41.63,80.0,0.98,0.92,100.87,XY24,NTT,MISC

In [15]:
# top 5 to monitor for exit
df_tmp = df_portfolio_features[~df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])]
df_tmp = df_tmp[(df_tmp['Current P/L%'] > 0) ].sort_values(by = 'Dev%_PE', ascending=False)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
69,STARHEALTH,0.23,13.13,30.17,47.26,95947.0,36899.0,318022.0,761.00,78.49,51.0,H-SC,16.46,173.0,0.38,2.01,37.50,XY24,NTT,INSURANCE
25,FINCABLES,-2.40,58.23,31.40,107.91,73356.0,85975.0,233619.0,1641.55,42.57,72.0,M-SC,18.15,220.0,1.17,1.47,75.76,OX40N,ATH,CABLES
87,ZYDUSLIFE,-3.13,23.09,10.08,35.51,26004.0,48399.0,257973.0,1285.01,7.21,59.0,H-MC,15.94,120.0,1.86,1.63,35.76,AR,ATH,PHARMA
80,UTIAMC,-0.94,0.11,50.98,51.15,113472.0,252.0,222582.0,1371.68,-19.39,48.0,M-SC,7.65,229.0,0.00,1.40,4.26,XY24,ATH,FINANCE

In [16]:
# top 5 to book for rotation from weak conviction
df_tmp = df_portfolio_features[~df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])]
df_tmp = df_tmp[~df_tmp['Criteria'].isin(['XY25','XY24','X40', 'X40N'])].sort_values(by = 'RRR Ind', ascending=False)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
87,ZYDUSLIFE,-3.13,23.09,10.08,35.51,26004.0,48399.0,257973.0,1285.01,7.21,59.0,H-MC,15.94,120.0,1.86,1.63,35.76,AR,ATH,PHARMA
25,FINCABLES,-2.40,58.23,31.40,107.91,73356.0,85975.0,233619.0,1641.55,42.57,72.0,M-SC,18.15,220.0,1.17,1.47,75.76,OX40N,ATH,CABLES
68,SIS,-0.91,-0.14,21.44,21.26,23771.0,-158.0,110874.0,528.00,2647.15,53.0,H-SC,22.26,168.0,-0.01,0.70,64.85,OX40N,NTT,MISC
3,ALKYLAMINE,1.76,-18.10,135.08,92.54,111702.0,-18270.0,82693.0,4520.85,-12.24,57.0,H-SC,13.77,142.0,-0.16,0.52,57.03,SR,ATH,CHEMICALS
42,INDIAMART,1.06,-22.50,159.24,100.92,152219.0,-27745.0,95591.0,4675.60,-65.04,46.0,H-SC,12.95,140.0,-0.18,0.60,3.48,AR,ATH,MISC

In [17]:
# top 5 to accumulate based on lowest RSI_14
df_tmp = df_portfolio_features[df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])].sort_values(by = 'RSI_14', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
55,PAGEIND,-4.64,-4.75,40.24,33.59,102870.0,-12739.0,255640.0,51217.29,-31.67,29.0,X-MC,8.84,55.0,-0.12,1.61,21.40,X40,ATH,APPARELS
34,HDFCBANK,-0.55,-11.45,48.00,31.05,124584.0,-33570.0,259550.0,1073.00,-26.46,32.0,X-LC,12.04,26.0,-0.27,1.64,0.74,X40,BTT,BANKS
28,GODREJCP,3.52,-14.77,55.94,32.90,118971.0,-36861.0,212676.0,1460.97,-11.86,32.0,X-LC,5.07,32.0,-0.31,1.34,3.52,X40N,ATH,FMCG
56,PGHH,0.49,-36.40,107.57,32.01,146071.0,-77728.0,135792.0,17616.87,-56.92,37.0,X-MC,19.22,57.0,-0.53,0.86,0.49,X40,ATH,FMCG
20,DABUR,-0.30,-19.84,79.27,43.70,157628.0,-49218.0,198850.0,735.00,-27.23,39.0,X-MC,9.41,70.0,-0.31,1.25,1.19,XY24,BTT,FMCG

In [18]:
# top 5 to accumulate based on Spread and CumlRnk
df_tmp = df_portfolio_features[df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])]
df_tmp = df_tmp[(df_tmp['CumlRnk'] < 100)].sort_values(by = 'Spread%', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
19,COLPAL,-0.47,-24.23,84.59,39.86,168799.0,-63815.0,199550.0,3683.41,-8.32,41.0,X-MC,1.49,62.0,-0.38,1.26,12.88,XY25,ATH,FMCG
23,DMART,0.74,-0.79,32.47,31.42,100436.0,-2470.0,309320.0,5391.45,-17.46,54.0,X-LC,2.68,14.0,-0.02,1.95,11.62,X40N,ATH,FMCG
50,KOTAKBANK,0.49,3.13,15.31,18.92,37848.0,7510.0,247212.0,452.46,-9.84,53.0,X-LC,2.96,12.0,0.20,1.56,11.23,X40,ATH,BANKS
26,GILLETTE,0.08,-10.25,44.54,29.72,101491.0,-26031.0,227865.0,10978.86,-31.02,41.0,X-SC,3.19,83.0,-0.26,1.44,4.71,X40,ATH,FMCG
8,BAJAJHLDNG,-0.68,3.32,24.12,28.24,63797.0,8495.0,264500.0,14274.15,-4.76,64.0,X-LC,3.26,28.0,0.13,1.67,33.12,X40,ATH,FINANCE

In [19]:
# top 5 to accumulate based on lowest Gained%
df_tmp = df_portfolio_features[df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])].sort_values(by = 'Gained%', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
35,HDFCLIFE,0.20,-7.73,50.81,39.15,117555.0,-19376.0,231361.0,811.41,-31.24,39.0,X-LC,16.32,31.0,-0.16,1.46,0.39,X40,ATH,INSURANCE
56,PGHH,0.49,-36.40,107.57,32.01,146071.0,-77728.0,135792.0,17616.87,-56.92,37.0,X-MC,19.22,57.0,-0.53,0.86,0.49,X40,ATH,FMCG
34,HDFCBANK,-0.55,-11.45,48.00,31.05,124584.0,-33570.0,259550.0,1073.00,-26.46,32.0,X-LC,12.04,26.0,-0.27,1.64,0.74,X40,BTT,BANKS
47,ITC,0.85,-23.17,62.30,24.70,190162.0,-92042.0,305236.0,452.00,-59.56,41.0,X-LC,10.66,1.0,-0.48,1.93,1.07,X40,NTT,FMCG
20,DABUR,-0.30,-19.84,79.27,43.70,157628.0,-49218.0,198850.0,735.00,-27.23,39.0,X-MC,9.41,70.0,-0.31,1.25,1.19,XY24,BTT,FMCG

In [20]:
# top 5 to accumulate based on lowest CurrAlloc%
df_tmp = df_portfolio_features[df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])].sort_values(by = 'CurrAlloc%', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
10,BATAINDIA,1.75,-53.06,188.05,35.20,113573.0,-68275.0,60395.0,2096.00,-20.87,61.0,X-SC,12.86,91.0,-0.60,0.38,21.34,X40,NTT,FOOTWEAR
61,RELAXO,0.59,-45.68,180.37,52.31,142234.0,-66303.0,78857.0,1176.00,-42.12,57.0,X-SC,13.03,92.0,-0.47,0.50,76.31,X40N,NTT,FOOTWEAR
56,PGHH,0.49,-36.40,107.57,32.01,146071.0,-77728.0,135792.0,17616.87,-56.92,37.0,X-MC,19.22,57.0,-0.53,0.86,0.49,X40,ATH,FMCG
57,QUESS,-0.30,36.66,27.25,73.90,39769.0,39149.0,145942.0,424.00,-26.72,68.0,X-SC,41.63,80.0,0.98,0.92,100.87,XY24,NTT,MISC
2,ACC,-0.61,-40.71,194.86,74.81,309757.0,-109164.0,158964.0,3906.00,-57.90,41.0,X-SC,11.83,85.0,-0.35,1.00,6.20,XY24,BTT,CEMENT

In [21]:
# top 5 to accumulate based on CumlRnk
df_tmp = df_portfolio_features.sort_values(by = 'CumlRnk', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
47,ITC,0.85,-23.17,62.30,24.70,190162.0,-92042.0,305236.0,452.00,-59.56,41.0,X-LC,10.66,1.0,-0.48,1.93,1.07,X40,NTT,FMCG
74,TCS,1.08,-30.28,78.14,24.20,252392.0,-140273.0,323000.0,4230.71,-41.00,54.0,X-LC,15.02,2.0,-0.56,2.04,20.45,X40,ATH,IT
45,INFY,-0.09,-16.35,67.83,40.38,213597.0,-61570.0,314900.0,1972.00,-37.23,60.0,X-LC,16.15,3.0,-0.29,1.99,19.25,X40,NTT,IT
76,TMPV,1.92,-16.82,71.62,42.75,247880.0,-70003.0,346104.0,600.00,-83.62,57.0,X-LC,4.45,4.0,-0.28,2.18,19.01,XY24,NTT,AUTO
33,HCLTECH,0.34,-8.37,35.29,23.97,100079.0,-25896.0,283590.0,1853.42,-6.53,71.0,X-LC,12.40,8.0,-0.26,1.79,33.82,X40,ATH,IT

In [22]:
# top 5 for average up
df_tmp = df_portfolio_features[(df_portfolio_features['Dev%_200'] > 5)].sort_values(by = 'CurrAlloc%', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
44,INDUSINDBK,0.71,-24.35,75.66,32.89,44191.0,-18798.0,58408.0,1800.00,-375.21,56.0,L-MC,13.70,258.0,-0.43,0.37,44.00,XR,NTT,BANKS
61,RELAXO,0.59,-45.68,180.37,52.31,142234.0,-66303.0,78857.0,1176.00,-42.12,57.0,X-SC,13.03,92.0,-0.47,0.50,76.31,X40N,NTT,FOOTWEAR
78,TTKPRESTIG,2.50,-21.88,28.13,0.09,22145.0,-22053.0,78724.0,770.00,82.71,43.0,M-SC,11.50,250.0,-1.00,0.50,41.69,OX40N,NTT,DURABLES
3,ALKYLAMINE,1.76,-18.10,135.08,92.54,111702.0,-18270.0,82693.0,4520.85,-12.24,57.0,H-SC,13.77,142.0,-0.16,0.52,57.03,SR,ATH,CHEMICALS
12,BOSCH-HCIL,-1.67,-26.16,35.42,-0.01,33424.0,-33439.0,94366.0,2282.00,19204.35,78.0,M-SC,4.21,231.0,-1.00,0.60,60.62,OX40N,BTT,AC

In [23]:
# top 5 RSP
df_tmp = df_portfolio_features.sort_values(by = 'RSP', ascending=False)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
12,BOSCH-HCIL,-1.67,-26.16,35.42,-0.01,33424.0,-33439.0,94366.0,2282.00,19204.35,78.0,M-SC,4.21,231.0,-1.00,0.60,60.62,OX40N,BTT,AC
82,VALIANTORG,5.00,-29.02,145.35,74.15,168791.0,-47478.0,116127.0,838.00,-308.98,79.0,H-SC,4.68,145.0,-0.28,0.73,72.81,XR,NTT,CHEMICALS
25,FINCABLES,-2.40,58.23,31.40,107.91,73356.0,85975.0,233619.0,1641.55,42.57,72.0,M-SC,18.15,220.0,1.17,1.47,75.76,OX40N,ATH,CABLES
67,SIEMENS,-0.80,7.12,16.60,24.90,33092.0,13255.0,199350.0,4648.66,67.53,68.0,H-LC,12.67,51.0,0.40,1.26,40.65,AR,ATH,ELECTRICAL
33,HCLTECH,0.34,-8.37,35.29,23.97,100079.0,-25896.0,283590.0,1853.42,-6.53,71.0,X-LC,12.40,8.0,-0.26,1.79,33.82,X40,ATH,IT

In [24]:
# Top N allocation
df_tmp = df_portfolio_features.sort_values(by = 'CurrAlloc%', ascending=False)
top_n_values = [10, 25, 50]

sum_df = pd.DataFrame({
    'Top_N': top_n_values,
    'Sum_Alloc%': [df_tmp['CurrAlloc%'].head(n).sum() for n in top_n_values]
})

sum_df

   Top_N  Sum_Alloc%
0     10       19.85
1     25       44.82
2     50       76.84

In [25]:
# market-cap-wise allocation
df_tmp = df_portfolio_features[cols]
df_tmp.groupby(df_tmp['Conviction'].str[-2:])['CurrAlloc%'].sum().sort_values(ascending=False)

Conviction
SC    39.33
LC    37.74
MC    22.91
Name: CurrAlloc%, dtype: float64

In [26]:
# criteria-wise allocation
df_portfolio_features.groupby('Criteria')['CurrAlloc%'].sum().sort_values(ascending=False)

Criteria
X40      26.35
XY24     24.90
X40N     18.34
XR        9.06
XY25      7.23
OX40N     7.15
AR        6.10
SR        0.85
Name: CurrAlloc%, dtype: float64

In [27]:
# conviction-wise allocation
df_portfolio_features.groupby('Conviction')['CurrAlloc%'].sum().sort_values(ascending=False)

Conviction
X-LC    35.68
H-SC    19.26
X-MC    18.67
M-SC    11.07
X-SC     8.51
H-MC     2.67
H-LC     1.26
M-MC     1.20
M-LC     0.80
L-SC     0.49
L-MC     0.37
Name: CurrAlloc%, dtype: float64

In [28]:
# sector-wise stats
df_tmp = df_portfolio_features.groupby('Category')[['CurrAlloc%', 'Current', 'Current P/L', 'FTT Amt']].sum().sort_values(by=['Current', 'Current P/L'], ascending=False)
df_tmp['Current P/L%'] = round(df_tmp['Current P/L'] * 100 / df_tmp['Current'], 2)
df_tmp['FTT%'] = round(df_tmp['FTT Amt'] * 100 / df_tmp['Current'], 2)
cols = ['CurrAlloc%', 'Current P/L%', 'FTT%']
df_tmp[cols].sort_values(by=['CurrAlloc%'], ascending=False)

               CurrAlloc%  Current P/L%    FTT%
Category
FMCG                15.35        -22.62   66.71
IT                  11.11        -35.37  102.56
FINANCE             10.66        -14.13   63.29
AUTO                 8.31         -2.63   39.38
MISC                 6.88        -22.77   75.45
BANKS                6.07        -11.17   59.11
PHARMA               5.72          8.46   17.50
INSURANCE            5.60         -4.70   41.73
PAINTS               5.48        -13.40   32.75
ELECTRICAL           4.11         -8.42   46.39
AC                   1.82        -11.03   41.14
REFINERIES           1.70        -10.95   48.22
FOOTWEAR             1.67        -67.02  133.99
BREWERIES            1.64         10.15    8.51
APPARELS             1.61         -4.98   40.24
DURABLES             1.48        -65.53  105.80
CABLES               1.47         36.80   31.40
TRAVEL               1.42        -98.94  198.55
CERAMICS             1.34        -44.39   88.25
CHEMICALS            1.25        -33.07  141.08
ENGINEERING          1.22        -24.85   81.96
CEMENT               1.00        -68.67  194.86
JEWELLERY            0.97       -108.98  181.59
ENTERTAINMENT        0.69        -77.85  183.92
HEALTHCARE           0.68        -67.40  109.41
TEXTILES             0.38        -51.46   94.65
HOTELS               0.35       -102.53  173.97

In [29]:
# money to be made criteria-wise
df_portfolio_features.groupby('Criteria')['FTT Amt'].agg(['sum', 'count']).sort_values(by='sum', ascending=False)

                sum  count
Criteria
XY24      3564910.0     20
X40       2051543.0     18
XR        1358346.0     13
X40N      1171596.0     12
AR        1066150.0      8
OX40N      658991.0     10
XY25       554241.0      5
SR         281863.0      2

In [30]:
# money to be made conviction-wise
df_portfolio_features.groupby('Conviction')['FTT Amt'].agg(['sum', 'count']).sort_values(by='sum', ascending=False)

                  sum  count
Conviction
H-SC        3297563.0     23
X-LC        2403703.0     20
M-SC        1496918.0     15
X-MC        1494588.0     14
X-SC        1229623.0      8
H-MC         275246.0      2
L-SC         213342.0      2
M-LC         164641.0      1
M-MC          54733.0      1
L-MC          44191.0      1
H-LC          33092.0      1

In [31]:
# money to be made criteria and conviction-wise
df_portfolio_features.groupby(['Conviction', 'Criteria'])['FTT Amt'].agg(['sum', 'count']).sort_values(by='sum', ascending=False)

                           sum  count
Conviction Criteria
X-LC       X40       1168874.0      9
H-SC       XY24       993084.0      5
M-SC       XY24       975184.0      7
H-SC       AR         931356.0      5
           XR         799819.0      7
X-SC       XY24       708903.0      3
X-MC       X40        667605.0      7
X-LC       X40N       513834.0      6
           XY24       417391.0      2
X-MC       X40N       352106.0      3
X-SC       X40N       305656.0      3
H-SC       OX40N      291441.0      4
           SR         281863.0      2
X-MC       XY25       253771.0      2
M-SC       OX40N      251743.0      5
H-MC       XY24       249242.0      1
X-LC       XY25       245737.0      2
X-MC       XY24       221106.0      2
X-SC       X40        215064.0      2
M-SC       XR         194293.0      2
M-LC       XR         164641.0      1
L-SC       OX40N      115807.0      1
           XR          97535.0      1
M-SC       AR          75698.0      1
X-LC       XR          57867.0      1
M-MC       XY25        54733.0      1
L-MC       XR          44191.0      1
H-LC       AR          33092.0      1
H-MC       AR          26004.0      1

In [32]:
# notebook execution time

end_time = time.time()
execution_time = round(end_time - start_time, 0)
print(f"Notebook execution time: {execution_time} seconds")

Notebook execution time: 23.0 seconds