<a href="https://colab.research.google.com/github/ankit-rathi/Quantvesting_v2/blob/main/myStocks_Portfolio_Analysis.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
'''
!pip install pandas==2.2.2 -qq
!pip install pyxirr -qq
!pip install ta -qq
!pip install yfinance==0.2.59 -qq
'''

'\n!pip install pandas==2.2.2 -qq\n!pip install pyxirr -qq\n!pip install ta -qq\n!pip install yfinance==0.2.59 -qq\n'

In [2]:
# import libraries

import numpy as np
import pandas as pd
import datetime
import warnings
warnings.filterwarnings('ignore')
import yfinance as yfin
import ta
import matplotlib.pyplot as plt
import requests

In [3]:
# notebook start time
import time
import datetime
import pytz

start_time = time.time()

# function to print date timestamp
def print_date_time():
  tz_NY = pytz.timezone('Asia/Kolkata')
  datetime_NY = datetime.datetime.now(tz_NY)
  print("Run date time (IST):", datetime_NY.strftime("%Y-%m-%d %H:%M:%S"))

In [4]:
# function to get booked and reserved amount
def get_amt():
  # fetch the JSON data from the URL
  url = "https://raw.githubusercontent.com/ankit-rathi/Tradevesting_v1/main/data/myPortfolioAmts.json"
  response = requests.get(url)
  pf_amts = response.json()  # parse the JSON data

  # extract values from the JSON
  py_booked_amt_dm = pf_amts["py_booked_amt_dm"]
  py_booked_amt_sv = pf_amts["py_booked_amt_sv"]
  cy_booked_amt_dm = pf_amts["cy_booked_amt_dm"]
  cy_booked_amt_sv = pf_amts["cy_booked_amt_sv"]
  reserve_amt_dm = pf_amts["reserve_amt_dm"]
  reserve_amt_sv = pf_amts["reserve_amt_sv"]

  # perform calculations
  py_booked_amt = py_booked_amt_dm + py_booked_amt_sv
  cy_booked_amt = cy_booked_amt_dm + cy_booked_amt_sv
  reserve_amt = reserve_amt_dm + reserve_amt_sv
  total_booked_amt = py_booked_amt + cy_booked_amt

  return total_booked_amt, reserve_amt, cy_booked_amt, py_booked_amt

gen_output = 0

In [5]:
# function to format the amount
def format_amt(number):
    abs_number = abs(number)

    if abs_number >= 1_00_00_000:  # Crores
        formatted_amt = f"{number / 1_00_00_000:.2f} C"
    elif abs_number >= 1_00_000:  # Lakhs
        formatted_amt = f"{number / 1_00_000:.2f} L"
    elif abs_number >= 1_000:  # Thousands
        formatted_amt = f"{number / 1_000:.2f} K"
    else:
        formatted_amt = f"{number:.2f}"

    return formatted_amt

# function to set start and end date
def get_start_end_date():
  start_date = (datetime.date.today() + datetime.timedelta(days=-365)).strftime('%Y-%m-%d')
  end_date = (datetime.date.today() + datetime.timedelta(days=1)).strftime('%Y-%m-%d')
  return start_date, end_date

# function to fetch my portfolio csv
def get_mypfs_df():
  mypfs_df = pd.read_csv('https://raw.githubusercontent.com/ankit-rathi/Tradevesting_v1/main/data/myPortfolioStocks.csv')
  return mypfs_df

# function to fetch my prospects csv
def get_mypps_df():
  mypps_df = pd.read_csv('https://raw.githubusercontent.com/ankit-rathi/Tradevesting_v1/main/data/myProspectsScrips.csv')
  return mypps_df

# function to fetch screener data
def get_myscreen_df():
  myscreen_df = pd.read_csv('https://raw.githubusercontent.com/ankit-rathi/Tradevesting_v1/main/data/myScreenerDB.csv')
  return myscreen_df

# function to fetch momentum data
def get_myinvmt_df():
  myinvmt_df = pd.read_csv('https://raw.githubusercontent.com/ankit-rathi/Tradevesting_v1/main/data/myInvestments.csv')
  return myinvmt_df

# function to get the stock ids
def get_stock_ids(df_pf):
  stock_n100 = df_pf['Symbol'].unique()

  exclude = ['CADILAHC','MMTC', 'MASFIN']

  stock_ids = df_pf[~df_pf['Symbol'].isin(exclude) ]['Symbol'].unique()

  #mypf = mypf[mypf.Forecast.notnull()]
  #stock_ids = mypf['Symbol'].unique()

  #stock_ids.sort()
  return stock_ids

# get features from screener data
def get_screener_features():
  myscreen_df = get_myscreen_df()
  cols = ['Symbol', 'EPS', 'MedPE', 'ROCE%', 'ROE%', 'CapType']
  return myscreen_df[cols]

# get relative strength
def get_relative_strength(stock_list):

    # Dictionary to store stock tickers and their corresponding percentage price change
    stock_changes = {}

    # Loop through each stock and fetch its price data
    for stock in stock_list:
        try:
            # Download the stock data for the given date range
            stock_data = yfin.Ticker(stock + '.NS').history(period='1mo', interval='1d')[map(str.title, ['open', 'close', 'low', 'high', 'volume'])]

            # Calculate the percentage change for the stock
            if len(stock_data) > 0:
                start_price = stock_data['Close'].iloc[0]
                end_price = stock_data['Close'].iloc[-1]
                percent_change = round(((end_price - start_price) / start_price) * 100, 2)
                stock_changes[stock] = percent_change
            else:
                stock_changes[stock] = np.nan  # If no data is available, set to NaN

        except Exception as e:
            print(f"Error fetching data for {stock}: {e}")
            stock_changes[stock] = np.nan

    # Create a DataFrame with stock tickers and their percentage changes
    df = pd.DataFrame(list(stock_changes.items()), columns=['Symbol', 'Percent_Change'])

    # Drop any stocks with missing data (NaN values)
    df = df.dropna()

    # Calculate the percentile rank based on percentage change
    df['RSP'] = round(df['Percent_Change'].rank(pct=True) * 100, 2)
    cols = ['Symbol', 'RSP']
    df = df[cols]
    # Sort by percentile rank (optional)
    df = df.sort_values(by='RSP', ascending=False).reset_index(drop=True)

    return df

In [6]:
# function to get stock technicals
def stock_prec_dev(stock_symbol):
    #stock_symbol = 'ULTRACEMCO.NS'
    short_window = 20
    mid_window = 50
    long_window = 200
    moving_avg = 'SMA'

    start = datetime.datetime(*map(int, start_date.split('-')))
    end = datetime.datetime(*map(int, end_date.split('-')))

    stock_df = yfin.Ticker(stock_symbol + '.NS').history(period='max', interval='1d')[map(str.title, ['open', 'close', 'low', 'high', 'volume'])]

    stock_df['Max'] = round(max(stock_df['Close']),2)
    stock_df = stock_df[(stock_df.index <= end_date) & (stock_df.index >= start_date)]
    stock_df['200_SMA'] = round(stock_df['Close'].rolling(window = 200, min_periods = 1).mean(),0)
    stock_df['Dev%_200'] = round((stock_df['Close'] - stock_df['200_SMA'])*100/stock_df['200_SMA'],2)
    stock_df.dropna(axis = 0, inplace = True) # remove any null rows

    stock_df['20_SMA'] = stock_df['Close'].rolling(window=20).mean()
    stock_df['50_SMA'] = stock_df['Close'].rolling(window=50).mean()
    stock_df['Symbol'] = stock_symbol

    stock_df['Close'] = round(stock_df['Close'],2)
    stock_df['Min'] = round(min(stock_df['Close']),2)
    stock_df['RSI_14'] = ta.momentum.RSIIndicator(close=stock_df['Close'], window=14).rsi()
    stock_df['RSI_14'] = round(stock_df['RSI_14'],0)
    stock_df['Prev_Close'] = stock_df['Close'].shift(1)
    stock_df.drop(['Open', 'Low', 'High', 'Volume'], axis=1, inplace=True)
    stock_df = stock_df.tail(1)

    max_SMA = max(stock_df['20_SMA'].item(), stock_df['50_SMA'].item(), stock_df['200_SMA'].item())
    min_SMA = min(stock_df['20_SMA'].item(), stock_df['50_SMA'].item(), stock_df['200_SMA'].item())
    ABS_Spread = max_SMA - min_SMA
    stock_df['Spread%'] = round((ABS_Spread / stock_df['200_SMA'].item()) * 100,2)

    return stock_df

# function to compute stock attributes
def get_common_features(stock_ids, df_mypf):

  df_prec_dev = pd.DataFrame()
  df_tmp = get_screener_features()
  df_rs = get_relative_strength(stock_ids)

  for stock_id in stock_ids:
      tmp = stock_prec_dev(stock_id)
      tmp = tmp.reset_index()
      df_prec_dev = pd.concat([df_prec_dev, tmp], ignore_index = True)
  df_prec_dev = pd.merge(df_prec_dev, df_mypf, on= 'Symbol')
  df_prec_dev = pd.merge(df_prec_dev, df_tmp, on= 'Symbol', how='left')
  df_prec_dev = pd.merge(df_prec_dev, df_rs, on= 'Symbol', how='left')
  #print(df_prec_dev.columns)
  df_prec_dev['Curr_PE'] = round(df_prec_dev['Close']/df_prec_dev['EPS'],1)
  df_prec_dev['Dev%_PE'] = round((df_prec_dev['Curr_PE'] - df_prec_dev['MedPE'])*100/df_prec_dev['MedPE'],2)
  df_prec_dev['Conviction'] = df_prec_dev['Conviction'] + '-' + df_prec_dev['CapType']
  return df_prec_dev

# function to arrange stock features
def arrange_features(df_stocks, common_cols, diff_cols):
  df_stocks_common = df_stocks[common_cols].drop_duplicates()
  df_stocks_diff = df_stocks[diff_cols]
  df_stocks_diff['Investment'] = df_stocks_diff['AvgCost'] * df_stocks_diff['Shares']
  df_stocks_diff = df_stocks_diff.groupby(['Symbol'])[['Shares', 'Investment']].aggregate(['sum']).reset_index()
  df_stocks_diff.columns = ['Symbol', 'Shares', 'Investment']
  df_stocks_diff['AvgCost'] = round(df_stocks_diff['Investment']/df_stocks_diff['Shares'],2)
  df_stocks = pd.merge(df_stocks_diff, df_stocks_common, on='Symbol')
  return df_stocks

# plot fact distribution across dimension
def plot_pie_chart(df, dimension, fact):
  # grouping the data by category and calculating the sum of fact for each type
  grouped_data = df.groupby(dimension)[fact].sum()

  # sorting the grouped data in descending order
  grouped_data = grouped_data.sort_values(ascending=False)

  # creating a pie chart
  grouped_data.plot.pie(autopct='%1.1f%%', startangle=90, figsize=(6, 6))

  # adding a title and displaying the plot
  plt.title(f'{dimension} {fact} Distribution')
  plt.ylabel('')  # To hide the y-label
  plt.show()

In [7]:
# function to get portfolio features

def get_portfolio_features(df_common_features):

  print_date_time()
  print('-------------------')

  #df_common_features["Target"] = df_common_features["Target"].fillna(df_common_features["Max"])
  df_common_features['NTT'] = np.where(df_common_features['Strategy']== 'NTT', df_common_features["Target"], df_common_features['Max'])
  df_common_features['LTT'] = np.where(df_common_features['Strategy']== 'BTT', df_common_features["Target"], df_common_features['Max'])
  df_common_features['BOL'] = df_common_features['Min']

  tmp_df = df_common_features[df_common_features['Symbol'].isin(mypf_df[mypf_df['InPortfolio'] != 'NA'].Symbol.values)]
  print('qualified stocks: '+str(len(tmp_df['Symbol'].unique())))
  tmp_df1 = tmp_df[tmp_df['LatestQtr'] == 1]
  print('with latest results: '+str(len(tmp_df1['Symbol'].unique())))
  tmp_df1 = tmp_df1[tmp_df1['StarStock'] == 1]
  print('still star stocks: '+str(len(tmp_df1['Symbol'].unique())))
  tmp_df['Investment'] = tmp_df['AvgCost'] * tmp_df['Shares']
  tmp_df['Current'] = round(tmp_df['Close'] * tmp_df['Shares'],0)
  tmp_df['Previous'] = tmp_df['Prev_Close'] * tmp_df['Shares']
  tmp_df['EstimatedST'] = tmp_df['NTT'] * tmp_df['Shares']
  tmp_df['EstimatedLT'] = tmp_df['LTT'] * tmp_df['Shares']
  tmp_df['Current P/L'] = round((tmp_df['Current'] - tmp_df['Investment']),0)
  tmp_df['Today P/L%'] = round((tmp_df['Current'] - tmp_df['Previous'])*100/tmp_df['Previous'],2)
  tmp_df['Current P/L%'] = round((tmp_df['Current'] - tmp_df['Investment'])*100/tmp_df['Investment'],2)
  tmp_df['EstimatedST P/L%'] = round((tmp_df['EstimatedST'] - tmp_df['Investment'])*100/tmp_df['Investment'],2)
  tmp_df['EstimatedLT P/L%'] = round((tmp_df['EstimatedLT'] - tmp_df['Investment'])*100/tmp_df['Investment'],2)
  tmp_df['NTT%'] = round((tmp_df['NTT'] - tmp_df['Close'])*100/tmp_df['Close'],2)
  tmp_df['LTT%'] = round((tmp_df['LTT'] - tmp_df['Close'])*100/tmp_df['Close'],2)
  tmp_df['Gained%'] = round((tmp_df['Close'] - tmp_df['BOL'])*100/tmp_df['BOL'],2)
  investment = round(sum(tmp_df['AvgCost']*tmp_df['Shares']),0)
  current = round(sum(tmp_df['Close']*tmp_df['Shares']),0)
  tmp_df['InitAlloc%'] = round(tmp_df['Investment']*100/investment,2)
  tmp_df['CurrAlloc%'] = round(tmp_df['Current']*100/current,2)
  tmp_df['FTT'] = tmp_df['LTT']
  tmp_df.loc[tmp_df['Strategy'] == 'NTT', 'FTT'] = tmp_df['NTT']
  tmp_df['FTT%'] = tmp_df['LTT%']
  tmp_df.loc[tmp_df['Strategy'] == 'NTT', 'FTT%'] = tmp_df['NTT%']
  tmp_df['FTT Amt'] = round(tmp_df['FTT%'] * tmp_df['Current']/100,0)
  tmp_df['OTT%'] = round((tmp_df['FTT'] - tmp_df['AvgCost'])*100/tmp_df['AvgCost'],2)
  tmp_df['RRR Ind'] = round(tmp_df['Current P/L']/tmp_df['FTT Amt'],2)
  tmp_df['Risk Ind'] = round(tmp_df['Current P/L%']*tmp_df['CurrAlloc%'],0)

  return tmp_df

# function to print portfolio features
def print_portfolio_stats(df_portfolio_features, myinvmt_df):
  from pyxirr import xirr

  total_booked_amt, reserve_amt, cy_booked_amt, py_booked_amt = get_amt()

  dates = myinvmt_df['Date'].values
  dates = np.append(dates, datetime.date.today().strftime('%d-%b-%y'))
  investment = myinvmt_df['Investment'].values
  dates= pd.to_datetime(dates)

  current = round(sum(df_portfolio_features['Close']*df_portfolio_features['Shares']),0) + reserve_amt
  investment_xirr = np.append(investment, current)
  cagr = round(xirr(pd.DataFrame({"dates": dates, "amounts": investment_xirr}))*100,2)

  investment = -sum(investment)
  invested = round(sum(df_portfolio_features['AvgCost']*df_portfolio_features['Shares']),0) + reserve_amt
  previous = round(sum(df_portfolio_features['Prev_Close']*df_portfolio_features['Shares']),0) + reserve_amt
  cy_invested = investment + py_booked_amt

  today_pnl_amount = current-previous
  today_pnl_percentage = round((current-previous)*100/previous,2)

  curr_pnl_amount = current-invested
  curr_pnl_percentage = round((curr_pnl_amount)*100/(cy_invested),2)

  cy_pnl_amount = cy_booked_amt + curr_pnl_amount
  cy_pnl_percentage = round((cy_pnl_amount)*100/cy_invested,2)

  overall_pnl_amount = total_booked_amt + curr_pnl_amount
  overall_pnl_percentage = round((overall_pnl_amount)*100/investment,2)

  estimate_st = round(sum(df_portfolio_features['FTT']*df_portfolio_features['Shares']),0)  + reserve_amt
  est_st_pnl_amount = estimate_st-current
  est_st_pnl_percentage = round((est_st_pnl_amount)*100/current,2)

  estimate_lt = round(sum(df_portfolio_features['LTT']*df_portfolio_features['Shares']),0)  + reserve_amt
  est_lt_pnl_amount = estimate_lt-current
  est_lt_pnl_percentage = round((est_lt_pnl_amount)*100/current,2)

  total_profit = round(sum(df_portfolio_features[df_portfolio_features['Current P/L%'] > 0]['Current']) - sum(df_portfolio_features[df_portfolio_features['Current P/L%'] > 0]['Investment']),0)
  total_loss = round(sum(df_portfolio_features[df_portfolio_features['Current P/L%'] < 0]['Current']) - sum(df_portfolio_features[df_portfolio_features['Current P/L%'] < 0]['Investment']),0)

  cy_booked_percentage = round((cy_booked_amt)*100/current,2)
  py_booked_percentage = round((py_booked_amt)*100/investment,2)
  total_booked_percentage = round((total_booked_amt)*100/investment,2)

  print('-------------------')
  print('Initial Investment: ', format_amt(investment))
  print('CY Investment: ', format_amt(cy_invested))
  print('Reserve: ', format_amt(reserve_amt))
  print('Current: ',  format_amt(current))
  print('-------------------')
  print('Today PnL: '+ '{} ({}%)'.format(format_amt(today_pnl_amount), today_pnl_percentage))
  print('Current PnL: '+ '{} ({}%)'.format(format_amt(curr_pnl_amount), curr_pnl_percentage))
  print('CY Booked + Current PnL: '+ '{} ({}%)'.format(format_amt(cy_pnl_amount), cy_pnl_percentage))
  print('-------------------')
  print('Total profit: ', format_amt(total_profit))
  print('Total loss: ', format_amt(total_loss))
  print('-------------------')
  print('Total Booked + Current PnL: '+ '{} ({}%)'.format(format_amt(overall_pnl_amount), overall_pnl_percentage))
  print('Total Booked PnL: '+ '{} ({}%)'.format(format_amt(total_booked_amt), total_booked_percentage))
  print('Curr Year Booked PnL: '+ '{} ({}%)'.format(format_amt(cy_booked_amt), cy_booked_percentage))
  print('Prev Year Booked PnL: '+ '{} ({}%)'.format(format_amt(py_booked_amt), py_booked_percentage))
  print('===================')
  print('Est FTT: ',  format_amt(estimate_st))
  print('Est FTT PnL: '+ '{} ({}%)'.format(format_amt(est_st_pnl_amount), est_st_pnl_percentage))

  print('===================')
  print('Deployed: ', format_amt(investment))

  print('Current: ', format_amt(current))

  print('CAGR/XIRR %: '+'{}%'.format(cagr))

In [8]:
# get start and end date
start_date, end_date = get_start_end_date()

# get portfolio and prospects data
mypfs_df = get_mypfs_df()
mypps_df = get_mypps_df()
myinvmt_df = get_myinvmt_df()

# merge above datasets
mypf_df = pd.merge(mypfs_df, mypps_df, on="Symbol")

# seggregate dm and sv portfolio
dm_pf = mypf_df[mypf_df['InPortfolio'] == 'DM']
sv_pf = mypf_df[mypf_df['InPortfolio'] == 'SV']

# build portfolio stock dataframe
dm_stocks = get_stock_ids(dm_pf)
sv_stocks = get_stock_ids(sv_pf)
df_stocks = pd.concat([dm_pf,sv_pf], ignore_index = True)

# arrange common and diff stock features
common_cols = ['Symbol', 'Target', 'Criteria', 'Strategy', 'CumlRnk', 'LatestQtr', 'StarStock', 'Conviction', 'Category', 'InFolio', 'XIRR', 'MBQ']
diff_cols = ['Symbol', 'AvgCost', 'Shares']
df_stocks = arrange_features(df_stocks, common_cols, diff_cols)

# get common features
stock_ids = df_stocks['Symbol'].values
df_common_features = get_common_features(stock_ids, df_stocks)

df_common_features.reset_index(drop=True, inplace=True)
df_common_features.drop(['Date'], axis=1, inplace=True)
# get and print portfolio features
df_portfolio_features = get_portfolio_features(df_common_features)

print_portfolio_stats(df_portfolio_features, myinvmt_df)

df = df_portfolio_features
#plot_pie_chart(df, 'CapType', 'Current')
list_ox40n = list(df[df['MBQ'].str.contains('OX40N', na=False)]['Symbol'].values)

Run date time (IST): 2026-03-24 09:51:01
-------------------
qualified stocks: 86
with latest results: 26
still star stocks: 16
-------------------
Initial Investment:  1.36 C
CY Investment:  1.62 C
Reserve:  1.61 K
Current:  1.28 C
-------------------
Today PnL: 89.40 K (0.71%)
Current PnL: -49.51 L (-30.47%)
CY Booked + Current PnL: -33.62 L (-20.69%)
-------------------
Total profit:  39.47 K
Total loss:  -49.90 L
-------------------
Total Booked + Current PnL: -6.64 L (-4.9%)
Total Booked PnL: 42.87 L (31.64%)
Curr Year Booked PnL: 15.89 L (12.45%)
Prev Year Booked PnL: 26.98 L (19.91%)
===================
Est FTT:  2.48 C
Est FTT PnL: 1.20 C (94.24%)
===================
Deployed:  1.36 C
Current:  1.28 C
CAGR/XIRR %: -2.93%

In [9]:
# top 5 near their targets
cols = ['Symbol', 'Today P/L%', 'Current P/L%', 'FTT%', 'OTT%', 'FTT Amt', 'Current P/L', 'Current', 'FTT', 'Dev%_PE', 'RSI_14','Conviction', 'Spread%',  'CumlRnk', 'RRR Ind', 'CurrAlloc%', 'Gained%', 'Criteria', 'Strategy', 'Category']
df_tmp = df_portfolio_features[~df_portfolio_features['Symbol'].isin(['ENRIN','BLUSPRING','DIGITIDE'])]
df_tmp = df_tmp.sort_values(by = 'FTT Amt', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
50,MASFIN,0.48,-9.77,34.73,21.57,30705.0,-9570.0,88410.0,397.04,-22.31,40.0,H-SC,2.38,167.0,-0.31,0.69,20.59,XR,ATH,FINANCE
77,TTKPRESTIG,-3.60,-42.80,75.00,0.09,43230.0,-43137.0,57640.0,770.00,33.83,34.0,M-SC,19.18,250.0,-1.00,0.45,0.00,OX40N,NTT,DURABLES
67,SONACOMS,0.49,-15.70,64.99,39.09,55422.0,-15881.0,85278.0,804.02,-33.16,42.0,M-MC,7.38,193.0,-0.29,0.67,20.64,AR,ATH,AUTO
37,ICICIGI,0.04,-8.74,30.76,19.34,56176.0,-17482.0,182627.0,2252.93,-23.27,25.0,X-MC,3.75,66.0,-0.31,1.43,0.96,X40,ATH,INSURANCE
42,INDUSINDBK,0.12,-42.47,130.98,32.89,58181.0,-32786.0,44420.0,1800.00,-309.38,29.0,L-MC,8.15,258.0,-0.56,0.35,22.33,XR,NTT,BANKS

In [10]:
# top 5 today
df_tmp = df_portfolio_features.sort_values(by = 'Today P/L%', ascending=False)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
4,ALKYLAMINE,3.96,-45.12,252.84,93.63,140089.0,-45557.0,55406.0,4546.37,-41.22,38.0,H-SC,26.06,142.0,-0.33,0.43,3.96,SR,ATH,CHEMICALS
19,COFFEEDAY,3.40,-60.94,246.32,35.27,109248.0,-69197.0,44352.0,80.00,-69.82,27.0,L-SC,26.18,266.0,-0.63,0.35,3.40,XR,NTT,HOTELS
41,INDIGOPNTS,3.09,-47.79,91.56,0.02,83448.0,-83419.0,91140.0,1408.00,38.95,20.0,M-SC,24.40,222.0,-1.00,0.71,3.09,OX40N,NTT,PAINTS
5,ANGELONE,2.28,-7.40,34.10,24.18,96311.0,-22562.0,282438.0,303.00,-86.38,45.0,X-SC,10.30,97.0,-0.23,2.21,7.92,X40N,NTT,FINANCE
60,REPCOHOME,2.24,-25.77,155.70,89.82,331151.0,-73820.0,212685.0,880.00,-62.74,35.0,H-SC,8.03,161.0,-0.22,1.67,5.02,XY24,NTT,FINANCE

In [11]:
# bottom 5 today
df_tmp = df_portfolio_features.sort_values(by = 'Today P/L%', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
55,RAJESHEXPO,-4.37,-83.50,506.49,0.07,114639.0,-114543.0,22634.0,518.0,729.55,14.0,L-SC,34.53,268.0,-1.00,0.18,0.00,OX40N,NTT,JEWELLERY
77,TTKPRESTIG,-3.60,-42.80,75.00,0.09,43230.0,-43137.0,57640.0,770.0,33.83,34.0,M-SC,19.18,250.0,-1.00,0.45,0.00,OX40N,NTT,DURABLES
76,TRIDENT,-3.03,-34.97,97.61,28.51,58562.0,-32258.0,59996.0,48.0,-16.23,49.0,M-SC,14.19,223.0,-0.55,0.47,10.11,XR,NTT,TEXTILES
16,CAMPUS,-1.28,-26.63,81.65,33.28,100514.0,-44672.0,123103.0,393.0,-40.92,21.0,M-SC,10.51,218.0,-0.44,0.96,0.00,XY24,NTT,FOOTWEAR
69,SURYODAY,-1.25,-29.48,74.47,23.03,94038.0,-52795.0,126276.0,216.0,38.16,44.0,H-SC,6.40,166.0,-0.56,0.99,23.42,XR,NTT,BANKS

In [12]:
# top 5 to exit based on CumlRnk
df_tmp = df_portfolio_features[~df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])]
df_tmp = df_tmp[(df_tmp['Current P/L%'] > -1) & (df_tmp['Current P/L%'] < 1)].sort_values(by = 'CumlRnk', ascending=False)
df_tmp[cols].head()

Empty DataFrame
Columns: [Symbol, Today P/L%, Current P/L%, FTT%, OTT%, FTT Amt, Current P/L, Current, FTT, Dev%_PE, RSI_14, Conviction, Spread%, CumlRnk, RRR Ind, CurrAlloc%, Gained%, Criteria, Strategy, Category]
Index: []

In [13]:
# OX40N stocks to exit
df_tmp = df_portfolio_features[(df_portfolio_features['Symbol'].isin(list_ox40n))].sort_values(by = 'Current P/L%', ascending=False)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
26,FINCABLES,1.73,4.18,99.57,107.91,153156.0,6173.0,153817.0,1641.55,-6.14,46.0,M-SC,8.20,220.0,0.04,1.21,15.72,OX40N,ATH,CABLES
66,SIS,0.42,-39.17,99.36,21.26,67105.0,-43495.0,67537.0,528.00,1573.58,29.0,H-SC,14.45,168.0,-0.65,0.53,0.42,OX40N,NTT,MISC
18,CERA,1.29,-39.30,104.11,23.89,111154.0,-69137.0,106766.0,9475.00,-41.53,43.0,H-SC,18.99,153.0,-0.62,0.84,2.60,OX40N,NTT,CERAMICS
72,TATAELXSI,0.47,-40.19,120.75,32.03,95211.0,-52985.0,78850.0,9161.00,-25.24,36.0,H-SC,20.98,158.0,-0.56,0.62,2.74,OX40N,NTT,IT
77,TTKPRESTIG,-3.60,-42.80,75.00,0.09,43230.0,-43137.0,57640.0,770.00,33.83,34.0,M-SC,19.18,250.0,-1.00,0.45,0.00,OX40N,NTT,DURABLES

In [14]:
# top 5 to book for rotation
df_tmp = df_portfolio_features[(df_portfolio_features['Current P/L%'] > 20) ].sort_values(by = 'CumlRnk', ascending=False)
df_tmp[cols].head()

Empty DataFrame
Columns: [Symbol, Today P/L%, Current P/L%, FTT%, OTT%, FTT Amt, Current P/L, Current, FTT, Dev%_PE, RSI_14, Conviction, Spread%, CumlRnk, RRR Ind, CurrAlloc%, Gained%, Criteria, Strategy, Category]
Index: []

In [15]:
# top 5 to monitor for exit
df_tmp = df_portfolio_features[~df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])]
df_tmp = df_tmp[(df_tmp['Current P/L%'] > 0) ].sort_values(by = 'Dev%_PE', ascending=False)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
26,FINCABLES,1.73,4.18,99.57,107.91,153156.0,6173.0,153817.0,1641.55,-6.14,46.0,M-SC,8.20,220.0,0.04,1.21,15.72,OX40N,ATH,CABLES
1,ABB,1.70,12.73,29.13,45.57,85908.0,33293.0,294912.0,7934.00,-27.57,53.0,H-MC,13.28,125.0,0.39,2.31,30.96,AR,NTT,ELECTRICAL

In [16]:
# top 5 to book for rotation from weak conviction
df_tmp = df_portfolio_features[~df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])]
df_tmp = df_tmp[~df_tmp['Criteria'].isin(['XY25','XY24','X40', 'X40N'])].sort_values(by = 'RRR Ind', ascending=False)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
1,ABB,1.70,12.73,29.13,45.57,85908.0,33293.0,294912.0,7934.00,-27.57,53.0,H-MC,13.28,125.0,0.39,2.31,30.96,AR,NTT,ELECTRICAL
26,FINCABLES,1.73,4.18,99.57,107.91,153156.0,6173.0,153817.0,1641.55,-6.14,46.0,M-SC,8.20,220.0,0.04,1.21,15.72,OX40N,ATH,CABLES
40,INDIAMART,-0.58,-15.81,145.55,106.72,151127.0,-19504.0,103832.0,4810.62,-62.11,30.0,H-SC,11.66,140.0,-0.13,0.81,3.87,AR,ATH,MISC
85,ZYDUSLIFE,0.77,-8.55,48.30,35.63,92573.0,-17912.0,191662.0,1286.17,-20.27,40.0,H-MC,5.45,120.0,-0.19,1.50,6.70,AR,ATH,PHARMA
84,WIPRO,0.61,-22.61,122.59,72.27,160765.0,-38308.0,131140.0,420.00,-30.18,31.0,M-LC,17.83,98.0,-0.24,1.03,0.61,XR,NTT,IT

In [17]:
# top 5 to accumulate based on lowest RSI_14
df_tmp = df_portfolio_features[df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])].sort_values(by = 'RSI_14', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
53,PGHH,-0.81,-29.72,87.83,32.01,131801.0,-63456.0,150064.0,17616.87,-52.50,11.0,X-MC,15.89,57.0,-0.48,1.18,0.00,X40,ATH,FMCG
58,RELAXO,-0.67,-67.21,364.55,52.31,173497.0,-97568.0,47592.0,1176.00,-65.06,17.0,X-SC,26.64,92.0,-0.56,0.37,0.00,X40N,NTT,FOOTWEAR
12,BATAINDIA,0.12,-59.59,234.56,35.20,121971.0,-76670.0,52000.0,2096.00,-31.84,18.0,X-SC,31.28,91.0,-0.63,0.41,0.12,X40,NTT,FOOTWEAR
38,ICICIPRULI,0.29,-11.83,48.27,30.73,83842.0,-23312.0,173693.0,790.00,-35.47,19.0,X-MC,4.45,78.0,-0.28,1.36,0.29,X40,ATH,INSURANCE
34,HDFCBANK,0.72,-10.33,43.16,28.37,90899.0,-24275.0,210610.0,1073.00,-23.99,22.0,X-LC,12.36,26.0,-0.27,1.65,0.72,X40,BTT,BANKS

In [18]:
# top 5 to accumulate based on Spread and CumlRnk
df_tmp = df_portfolio_features[df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])]
df_tmp = df_tmp[(df_tmp['CumlRnk'] < 100)].sort_values(by = 'Spread%', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
78,UNITDSPR,1.00,-5.39,27.65,20.77,61250.0,-12625.0,221519.0,1644.00,-16.02,40.0,X-MC,1.76,64.0,-0.21,1.74,1.00,X40N,NTT,BREWERIES
65,SIEMENS,0.89,-19.00,54.95,25.51,82834.0,-35350.0,150745.0,4671.50,26.69,40.0,H-LC,2.80,51.0,-0.43,1.18,11.01,AR,ATH,ELECTRICAL
59,RELIANCE,0.09,-9.55,38.53,25.30,70038.0,-19189.0,181774.0,1952.00,-11.96,50.0,X-LC,3.46,21.0,-0.27,1.42,21.36,XY25,BTT,REFINERIES
37,ICICIGI,0.04,-8.74,30.76,19.34,56176.0,-17482.0,182627.0,2252.93,-23.27,25.0,X-MC,3.75,66.0,-0.31,1.43,0.96,X40,ATH,INSURANCE
82,VOLTAS,-0.04,-2.16,48.40,45.20,90801.0,-4137.0,187605.0,1856.00,12.06,27.0,X-MC,3.88,79.0,-0.05,1.47,4.49,XY25,NTT,AC

In [19]:
# top 5 to accumulate based on lowest Gained%
df_tmp = df_portfolio_features[df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])].sort_values(by = 'Gained%', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
2,ABBOTINDIA,-0.39,-14.84,38.64,18.07,58853.0,-26545.0,152310.0,35195.00,-27.52,34.0,X-MC,10.81,58.0,-0.45,1.19,0.00,X40,ATH,PHARMA
45,ITC,-0.33,-23.75,56.13,19.06,145597.0,-80774.0,259392.0,452.00,-58.35,29.0,X-LC,18.68,1.0,-0.55,2.03,0.00,X40,NTT,FMCG
58,RELAXO,-0.67,-67.21,364.55,52.31,173497.0,-97568.0,47592.0,1176.00,-65.06,17.0,X-SC,26.64,92.0,-0.56,0.37,0.00,X40N,NTT,FOOTWEAR
53,PGHH,-0.81,-29.72,87.83,32.01,131801.0,-63456.0,150064.0,17616.87,-52.50,11.0,X-MC,15.89,57.0,-0.48,1.18,0.00,X40,ATH,FMCG
12,BATAINDIA,0.12,-59.59,234.56,35.20,121971.0,-76670.0,52000.0,2096.00,-31.84,18.0,X-SC,31.28,91.0,-0.63,0.41,0.12,X40,NTT,FOOTWEAR

In [20]:
# top 5 to accumulate based on lowest CurrAlloc%
df_tmp = df_portfolio_features[df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])].sort_values(by = 'CurrAlloc%', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
58,RELAXO,-0.67,-67.21,364.55,52.31,173497.0,-97568.0,47592.0,1176.00,-65.06,17.0,X-SC,26.64,92.0,-0.56,0.37,0.00,X40N,NTT,FOOTWEAR
12,BATAINDIA,0.12,-59.59,234.56,35.20,121971.0,-76670.0,52000.0,2096.00,-31.84,18.0,X-SC,31.28,91.0,-0.63,0.41,0.12,X40,NTT,FOOTWEAR
54,QUESS,2.14,-28.84,144.37,73.90,109717.0,-30796.0,75997.0,424.00,-61.98,35.0,X-SC,21.50,80.0,-0.28,0.60,2.14,XY24,NTT,MISC
36,HONAUT,0.75,-28.90,112.83,51.31,154690.0,-55738.0,137100.0,58357.33,-40.87,24.0,X-SC,15.87,90.0,-0.36,1.07,0.75,X40N,ATH,ELECTRICAL
51,MEDANTA,2.18,-15.25,49.99,27.12,74783.0,-26921.0,149596.0,1486.00,-17.88,31.0,X-SC,12.24,87.0,-0.36,1.17,2.18,XY24,NTT,HEALTHCARE

In [21]:
# top 5 to accumulate based on CumlRnk
df_tmp = df_portfolio_features.sort_values(by = 'CumlRnk', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
45,ITC,-0.33,-23.75,56.13,19.06,145597.0,-80774.0,259392.0,452.00,-58.35,29.0,X-LC,18.68,1.0,-0.55,2.03,0.00,X40,NTT,FMCG
73,TCS,-0.28,-30.02,80.87,26.57,262178.0,-139076.0,324197.0,4311.58,-40.68,28.0,X-LC,17.05,2.0,-0.53,2.54,1.18,X40,ATH,IT
43,INFY,0.06,-14.40,56.82,34.24,152191.0,-45040.0,267848.0,1972.00,-32.51,37.0,X-LC,15.26,3.0,-0.30,2.10,3.01,X40,NTT,IT
75,TMPV,0.82,-29.95,94.96,36.58,236714.0,-106563.0,249278.0,600.00,-85.81,33.0,X-LC,6.75,4.0,-0.45,1.95,0.82,XY24,NTT,AUTO
33,HCLTECH,0.76,-11.16,39.40,23.83,84677.0,-27007.0,214917.0,1908.19,-6.53,44.0,X-LC,11.86,8.0,-0.32,1.68,4.35,X40,ATH,IT

In [22]:
# top 5 for average up
df_tmp = df_portfolio_features[(df_portfolio_features['Dev%_200'] > 5)].sort_values(by = 'CurrAlloc%', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
1,ABB,1.7,12.73,29.13,45.57,85908.0,33293.0,294912.0,7934.0,-27.57,53.0,H-MC,13.28,125.0,0.39,2.31,30.96,AR,NTT,ELECTRICAL

In [23]:
# top 5 RSP
df_tmp = df_portfolio_features.sort_values(by = 'RSP', ascending=False)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
30,HAPPSTMNDS,-0.78,-51.36,280.06,84.85,174578.0,-65829.0,62336.0,1480.71,-42.16,52.0,H-SC,26.58,152.0,-0.38,0.49,15.44,AR,ATH,IT
69,SURYODAY,-1.25,-29.48,74.47,23.03,94038.0,-52795.0,126276.0,216.00,38.16,44.0,H-SC,6.40,166.0,-0.56,0.99,23.42,XR,NTT,BANKS
33,HCLTECH,0.76,-11.16,39.40,23.83,84677.0,-27007.0,214917.0,1908.19,-6.53,44.0,X-LC,11.86,8.0,-0.32,1.68,4.35,X40,ATH,IT
1,ABB,1.70,12.73,29.13,45.57,85908.0,33293.0,294912.0,7934.00,-27.57,53.0,H-MC,13.28,125.0,0.39,2.31,30.96,AR,NTT,ELECTRICAL
26,FINCABLES,1.73,4.18,99.57,107.91,153156.0,6173.0,153817.0,1641.55,-6.14,46.0,M-SC,8.20,220.0,0.04,1.21,15.72,OX40N,ATH,CABLES

In [24]:
# Top N allocation
df_tmp = df_portfolio_features.sort_values(by = 'CurrAlloc%', ascending=False)
top_n_values = [10, 25, 50]

sum_df = pd.DataFrame({
    'Top_N': top_n_values,
    'Sum_Alloc%': [df_tmp['CurrAlloc%'].head(n).sum() for n in top_n_values]
})

sum_df

   Top_N  Sum_Alloc%
0     10       20.83
1     25       45.89
2     50       78.12

In [25]:
# market-cap-wise allocation
df_tmp = df_portfolio_features[cols]
df_tmp.groupby(df_tmp['Conviction'].str[-2:])['CurrAlloc%'].sum().sort_values(ascending=False)

Conviction
SC    44.26
MC    30.10
LC    25.62
Name: CurrAlloc%, dtype: float64

In [26]:
# criteria-wise allocation
df_portfolio_features.groupby('Criteria')['CurrAlloc%'].sum().sort_values(ascending=False)

Criteria
XY24     26.83
X40      25.58
X40N     15.14
AR        9.22
XR        8.33
XY25      7.34
OX40N     6.75
SR        0.79
Name: CurrAlloc%, dtype: float64

In [27]:
# conviction-wise allocation
df_portfolio_features.groupby('Conviction')['CurrAlloc%'].sum().sort_values(ascending=False)

Conviction
X-LC    23.41
X-MC    22.60
H-SC    21.54
X-SC    12.24
M-SC     9.95
H-MC     5.11
M-MC     2.04
H-LC     1.18
M-LC     1.03
L-SC     0.53
L-MC     0.35
Name: CurrAlloc%, dtype: float64

In [28]:
# sector-wise stats
df_tmp = df_portfolio_features.groupby('Category')[['CurrAlloc%', 'Current', 'Current P/L', 'FTT Amt']].sum().sort_values(by=['Current', 'Current P/L'], ascending=False)
df_tmp['Current P/L%'] = round(df_tmp['Current P/L'] * 100 / df_tmp['Current'], 2)
df_tmp['FTT%'] = round(df_tmp['FTT Amt'] * 100 / df_tmp['Current'], 2)
cols = ['CurrAlloc%', 'Current P/L%', 'FTT%']
df_tmp[cols].sort_values(by=['CurrAlloc%'], ascending=False)

               CurrAlloc%  Current P/L%    FTT%
Category
FMCG                15.07        -29.96   76.10
FINANCE             13.10        -28.53   80.90
IT                  11.99        -47.39  122.40
MISC                 6.92        -51.92  117.91
ELECTRICAL           6.60        -14.95   58.97
PAINTS               5.10        -51.19   77.44
INSURANCE            4.68        -13.55   52.40
BANKS                4.54        -32.82  100.24
PHARMA               4.13        -11.40   46.47
AUTO                 3.68        -39.10   94.29
AC                   2.01        -24.31   58.02
HEALTHCARE           1.90        -47.43   85.91
TRAVEL               1.80        -94.38  191.71
DURABLES             1.77        -71.16  112.80
BREWERIES            1.74         -5.70   27.65
FOOTWEAR             1.74        -98.30  177.81
APPARELS             1.73        -21.39   62.79
REALTY               1.44        -20.73   40.57
REFINERIES           1.42        -10.56   38.53
CERAMICS             1.39        -74.11  127.01
CEMENT               1.25        -67.48  192.78
CABLES               1.21          4.01   99.57
ENGINEERING          1.08        -76.15  156.72
CHEMICALS            1.07        -92.26  249.11
JEWELLERY            1.04       -140.75  224.40
ENTERTAINMENT        0.76        -99.56  218.58
TEXTILES             0.47        -53.77   97.61
HOTELS               0.35       -156.02  246.32

In [29]:
# money to be made criteria-wise
df_portfolio_features.groupby('Criteria')['FTT Amt'].agg(['sum', 'count']).sort_values(by='sum', ascending=False)

                sum  count
Criteria
XY24      4172727.0     21
X40       1909921.0     16
XR        1428684.0     12
AR        1395872.0     10
X40N      1368278.0     10
OX40N      930050.0     10
XY25       502720.0      5
SR         318398.0      2

In [30]:
# money to be made conviction-wise
df_portfolio_features.groupby('Conviction')['FTT Amt'].agg(['sum', 'count']).sort_values(by='sum', ascending=False)

                  sum  count
Conviction
H-SC        4044989.0     24
X-MC        1850246.0     15
X-LC        1787795.0     13
M-SC        1646950.0     14
X-SC        1619128.0     10
H-MC         426056.0      3
L-SC         223887.0      2
M-LC         160765.0      1
M-MC         125819.0      2
H-LC          82834.0      1
L-MC          58181.0      1

In [31]:
# money to be made criteria and conviction-wise
df_portfolio_features.groupby(['Conviction', 'Criteria'])['FTT Amt'].agg(['sum', 'count']).sort_values(by='sum', ascending=False)

                           sum  count
Conviction Criteria
H-SC       XY24      1419692.0      6
           AR         999359.0      5
M-SC       XY24       958813.0      6
X-LC       X40        955507.0      7
H-SC       XR         905233.0      7
X-SC       XY24       872960.0      4
X-MC       X40        736617.0      7
           X40N       555345.0      4
X-SC       X40N       528371.0      4
M-SC       OX40N      413104.0      5
H-SC       OX40N      402307.0      4
X-LC       XY24       392736.0      2
H-SC       SR         318398.0      2
X-LC       X40N       284562.0      2
X-MC       XY24       280951.0      2
           XY25       277333.0      2
H-MC       XY24       247575.0      1
X-SC       X40        217797.0      2
M-SC       XR         195257.0      2
H-MC       AR         178481.0      2
M-LC       XR         160765.0      1
X-LC       XY25       154990.0      2
L-SC       OX40N      114639.0      1
           XR         109248.0      1
H-LC       AR          82834.0      1
M-SC       AR          79776.0      1
M-MC       XY25        70397.0      1
L-MC       XR          58181.0      1
M-MC       AR          55422.0      1

In [32]:
# notebook execution time

end_time = time.time()
execution_time = round(end_time - start_time, 0)
print(f"Notebook execution time: {execution_time} seconds")

Notebook execution time: 47.0 seconds