<a href="https://colab.research.google.com/github/ankit-rathi/Quantvesting_v2/blob/main/myStocks_Portfolio_Analysis.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
'''
!pip install pandas==2.2.2 -qq
!pip install pyxirr -qq
!pip install ta -qq
!pip install yfinance==0.2.59 -qq
'''

'\n!pip install pandas==2.2.2 -qq\n!pip install pyxirr -qq\n!pip install ta -qq\n!pip install yfinance==0.2.59 -qq\n'

In [2]:
# import libraries

import numpy as np
import pandas as pd
import datetime
import warnings
warnings.filterwarnings('ignore')
import yfinance as yfin
import ta
import matplotlib.pyplot as plt
import requests

In [3]:
# notebook start time
import time
import datetime
import pytz

start_time = time.time()

# function to print date timestamp
def print_date_time():
  tz_NY = pytz.timezone('Asia/Kolkata')
  datetime_NY = datetime.datetime.now(tz_NY)
  print("Run date time (IST):", datetime_NY.strftime("%Y-%m-%d %H:%M:%S"))

In [4]:
# function to get booked and reserved amount
def get_amt():
  # fetch the JSON data from the URL
  url = "https://raw.githubusercontent.com/ankit-rathi/Tradevesting_v1/main/data/myPortfolioAmts.json"
  response = requests.get(url)
  pf_amts = response.json()  # parse the JSON data

  # extract values from the JSON
  py_booked_amt_dm = pf_amts["py_booked_amt_dm"]
  py_booked_amt_sv = pf_amts["py_booked_amt_sv"]
  cy_booked_amt_dm = pf_amts["cy_booked_amt_dm"]
  cy_booked_amt_sv = pf_amts["cy_booked_amt_sv"]
  reserve_amt_dm = pf_amts["reserve_amt_dm"]
  reserve_amt_sv = pf_amts["reserve_amt_sv"]

  # perform calculations
  py_booked_amt = py_booked_amt_dm + py_booked_amt_sv
  cy_booked_amt = cy_booked_amt_dm + cy_booked_amt_sv
  reserve_amt = reserve_amt_dm + reserve_amt_sv
  total_booked_amt = py_booked_amt + cy_booked_amt

  return total_booked_amt, reserve_amt, cy_booked_amt, py_booked_amt

gen_output = 0

In [5]:
# function to format the amount
def format_amt(number):
    abs_number = abs(number)

    if abs_number >= 1_00_00_000:  # Crores
        formatted_amt = f"{number / 1_00_00_000:.2f} C"
    elif abs_number >= 1_00_000:  # Lakhs
        formatted_amt = f"{number / 1_00_000:.2f} L"
    elif abs_number >= 1_000:  # Thousands
        formatted_amt = f"{number / 1_000:.2f} K"
    else:
        formatted_amt = f"{number:.2f}"

    return formatted_amt

# function to set start and end date
def get_start_end_date():
  start_date = (datetime.date.today() + datetime.timedelta(days=-365)).strftime('%Y-%m-%d')
  end_date = (datetime.date.today() + datetime.timedelta(days=1)).strftime('%Y-%m-%d')
  return start_date, end_date

# function to fetch my portfolio csv
def get_mypfs_df():
  mypfs_df = pd.read_csv('https://raw.githubusercontent.com/ankit-rathi/Tradevesting_v1/main/data/myPortfolioStocks.csv')
  return mypfs_df

# function to fetch my prospects csv
def get_mypps_df():
  mypps_df = pd.read_csv('https://raw.githubusercontent.com/ankit-rathi/Tradevesting_v1/main/data/myProspectsScrips.csv')
  return mypps_df

# function to fetch screener data
def get_myscreen_df():
  myscreen_df = pd.read_csv('https://raw.githubusercontent.com/ankit-rathi/Tradevesting_v1/main/data/myScreenerDB.csv')
  return myscreen_df

# function to fetch momentum data
def get_myinvmt_df():
  myinvmt_df = pd.read_csv('https://raw.githubusercontent.com/ankit-rathi/Tradevesting_v1/main/data/myInvestments.csv')
  return myinvmt_df

# function to get the stock ids
def get_stock_ids(df_pf):
  stock_n100 = df_pf['Symbol'].unique()

  exclude = ['CADILAHC','MMTC', 'MASFIN']

  stock_ids = df_pf[~df_pf['Symbol'].isin(exclude) ]['Symbol'].unique()

  #mypf = mypf[mypf.Forecast.notnull()]
  #stock_ids = mypf['Symbol'].unique()

  #stock_ids.sort()
  return stock_ids

# get features from screener data
def get_screener_features():
  myscreen_df = get_myscreen_df()
  cols = ['Symbol', 'EPS', 'MedPE', 'ROCE%', 'ROE%', 'CapType']
  return myscreen_df[cols]

# get relative strength
def get_relative_strength(stock_list):

    # Dictionary to store stock tickers and their corresponding percentage price change
    stock_changes = {}

    # Loop through each stock and fetch its price data
    for stock in stock_list:
        try:
            # Download the stock data for the given date range
            stock_data = yfin.Ticker(stock + '.NS').history(period='1mo', interval='1d')[map(str.title, ['open', 'close', 'low', 'high', 'volume'])]

            # Calculate the percentage change for the stock
            if len(stock_data) > 0:
                start_price = stock_data['Close'].iloc[0]
                end_price = stock_data['Close'].iloc[-1]
                percent_change = round(((end_price - start_price) / start_price) * 100, 2)
                stock_changes[stock] = percent_change
            else:
                stock_changes[stock] = np.nan  # If no data is available, set to NaN

        except Exception as e:
            print(f"Error fetching data for {stock}: {e}")
            stock_changes[stock] = np.nan

    # Create a DataFrame with stock tickers and their percentage changes
    df = pd.DataFrame(list(stock_changes.items()), columns=['Symbol', 'Percent_Change'])

    # Drop any stocks with missing data (NaN values)
    df = df.dropna()

    # Calculate the percentile rank based on percentage change
    df['RSP'] = round(df['Percent_Change'].rank(pct=True) * 100, 2)
    cols = ['Symbol', 'RSP']
    df = df[cols]
    # Sort by percentile rank (optional)
    df = df.sort_values(by='RSP', ascending=False).reset_index(drop=True)

    return df

In [6]:
# function to get stock technicals
def stock_prec_dev(stock_symbol):
    #stock_symbol = 'ULTRACEMCO.NS'
    short_window = 20
    mid_window = 50
    long_window = 200
    moving_avg = 'SMA'

    start = datetime.datetime(*map(int, start_date.split('-')))
    end = datetime.datetime(*map(int, end_date.split('-')))

    stock_df = yfin.Ticker(stock_symbol + '.NS').history(period='max', interval='1d')[map(str.title, ['open', 'close', 'low', 'high', 'volume'])]

    stock_df['Max'] = round(max(stock_df['Close']),2)
    stock_df = stock_df[(stock_df.index <= end_date) & (stock_df.index >= start_date)]
    stock_df['200_SMA'] = round(stock_df['Close'].rolling(window = 200, min_periods = 1).mean(),0)
    stock_df['Dev%_200'] = round((stock_df['Close'] - stock_df['200_SMA'])*100/stock_df['200_SMA'],2)
    stock_df.dropna(axis = 0, inplace = True) # remove any null rows

    stock_df['20_SMA'] = stock_df['Close'].rolling(window=20).mean()
    stock_df['50_SMA'] = stock_df['Close'].rolling(window=50).mean()
    stock_df['Symbol'] = stock_symbol

    stock_df['Close'] = round(stock_df['Close'],2)
    stock_df['Min'] = round(min(stock_df['Close']),2)
    stock_df['RSI_14'] = ta.momentum.RSIIndicator(close=stock_df['Close'], window=14).rsi()
    stock_df['RSI_14'] = round(stock_df['RSI_14'],0)
    stock_df['Prev_Close'] = stock_df['Close'].shift(1)
    stock_df.drop(['Open', 'Low', 'High', 'Volume'], axis=1, inplace=True)
    stock_df = stock_df.tail(1)

    max_SMA = max(stock_df['20_SMA'].item(), stock_df['50_SMA'].item(), stock_df['200_SMA'].item())
    min_SMA = min(stock_df['20_SMA'].item(), stock_df['50_SMA'].item(), stock_df['200_SMA'].item())
    ABS_Spread = max_SMA - min_SMA
    stock_df['Spread%'] = round((ABS_Spread / stock_df['200_SMA'].item()) * 100,2)

    return stock_df

# function to compute stock attributes
def get_common_features(stock_ids, df_mypf):

  df_prec_dev = pd.DataFrame()
  df_tmp = get_screener_features()
  df_rs = get_relative_strength(stock_ids)

  for stock_id in stock_ids:
      tmp = stock_prec_dev(stock_id)
      tmp = tmp.reset_index()
      df_prec_dev = pd.concat([df_prec_dev, tmp], ignore_index = True)
  df_prec_dev = pd.merge(df_prec_dev, df_mypf, on= 'Symbol')
  df_prec_dev = pd.merge(df_prec_dev, df_tmp, on= 'Symbol', how='left')
  df_prec_dev = pd.merge(df_prec_dev, df_rs, on= 'Symbol', how='left')
  #print(df_prec_dev.columns)
  df_prec_dev['Curr_PE'] = round(df_prec_dev['Close']/df_prec_dev['EPS'],1)
  df_prec_dev['Dev%_PE'] = round((df_prec_dev['Curr_PE'] - df_prec_dev['MedPE'])*100/df_prec_dev['MedPE'],2)
  df_prec_dev['Conviction'] = df_prec_dev['Conviction'] + '-' + df_prec_dev['CapType']
  return df_prec_dev

# function to arrange stock features
def arrange_features(df_stocks, common_cols, diff_cols):
  df_stocks_common = df_stocks[common_cols].drop_duplicates()
  df_stocks_diff = df_stocks[diff_cols]
  df_stocks_diff['Investment'] = df_stocks_diff['AvgCost'] * df_stocks_diff['Shares']
  df_stocks_diff = df_stocks_diff.groupby(['Symbol'])[['Shares', 'Investment']].aggregate(['sum']).reset_index()
  df_stocks_diff.columns = ['Symbol', 'Shares', 'Investment']
  df_stocks_diff['AvgCost'] = round(df_stocks_diff['Investment']/df_stocks_diff['Shares'],2)
  df_stocks = pd.merge(df_stocks_diff, df_stocks_common, on='Symbol')
  return df_stocks

# plot fact distribution across dimension
def plot_pie_chart(df, dimension, fact):
  # grouping the data by category and calculating the sum of fact for each type
  grouped_data = df.groupby(dimension)[fact].sum()

  # sorting the grouped data in descending order
  grouped_data = grouped_data.sort_values(ascending=False)

  # creating a pie chart
  grouped_data.plot.pie(autopct='%1.1f%%', startangle=90, figsize=(6, 6))

  # adding a title and displaying the plot
  plt.title(f'{dimension} {fact} Distribution')
  plt.ylabel('')  # To hide the y-label
  plt.show()

In [7]:
# function to get portfolio features

def get_portfolio_features(df_common_features):

  print_date_time()
  print('-------------------')

  #df_common_features["Target"] = df_common_features["Target"].fillna(df_common_features["Max"])
  df_common_features['NTT'] = np.where(df_common_features['Strategy']== 'NTT', df_common_features["Target"], df_common_features['Max'])
  df_common_features['LTT'] = np.where(df_common_features['Strategy']== 'BTT', df_common_features["Target"], df_common_features['Max'])
  df_common_features['BOL'] = df_common_features['Min']

  tmp_df = df_common_features[df_common_features['Symbol'].isin(mypf_df[mypf_df['InPortfolio'] != 'NA'].Symbol.values)]
  print('qualified stocks: '+str(len(tmp_df['Symbol'].unique())))
  tmp_df1 = tmp_df[tmp_df['LatestQtr'] == 1]
  print('with latest results: '+str(len(tmp_df1['Symbol'].unique())))
  tmp_df1 = tmp_df1[tmp_df1['StarStock'] == 1]
  print('still star stocks: '+str(len(tmp_df1['Symbol'].unique())))
  tmp_df['Investment'] = tmp_df['AvgCost'] * tmp_df['Shares']
  tmp_df['Current'] = round(tmp_df['Close'] * tmp_df['Shares'],0)
  tmp_df['Previous'] = tmp_df['Prev_Close'] * tmp_df['Shares']
  tmp_df['EstimatedST'] = tmp_df['NTT'] * tmp_df['Shares']
  tmp_df['EstimatedLT'] = tmp_df['LTT'] * tmp_df['Shares']
  tmp_df['Current P/L'] = round((tmp_df['Current'] - tmp_df['Investment']),0)
  tmp_df['Today P/L%'] = round((tmp_df['Current'] - tmp_df['Previous'])*100/tmp_df['Previous'],2)
  tmp_df['Current P/L%'] = round((tmp_df['Current'] - tmp_df['Investment'])*100/tmp_df['Investment'],2)
  tmp_df['EstimatedST P/L%'] = round((tmp_df['EstimatedST'] - tmp_df['Investment'])*100/tmp_df['Investment'],2)
  tmp_df['EstimatedLT P/L%'] = round((tmp_df['EstimatedLT'] - tmp_df['Investment'])*100/tmp_df['Investment'],2)
  tmp_df['NTT%'] = round((tmp_df['NTT'] - tmp_df['Close'])*100/tmp_df['Close'],2)
  tmp_df['LTT%'] = round((tmp_df['LTT'] - tmp_df['Close'])*100/tmp_df['Close'],2)
  tmp_df['Gained%'] = round((tmp_df['Close'] - tmp_df['BOL'])*100/tmp_df['BOL'],2)
  investment = round(sum(tmp_df['AvgCost']*tmp_df['Shares']),0)
  current = round(sum(tmp_df['Close']*tmp_df['Shares']),0)
  tmp_df['InitAlloc%'] = round(tmp_df['Investment']*100/investment,2)
  tmp_df['CurrAlloc%'] = round(tmp_df['Current']*100/current,2)
  tmp_df['FTT'] = tmp_df['LTT']
  tmp_df.loc[tmp_df['Strategy'] == 'NTT', 'FTT'] = tmp_df['NTT']
  tmp_df['FTT%'] = tmp_df['LTT%']
  tmp_df.loc[tmp_df['Strategy'] == 'NTT', 'FTT%'] = tmp_df['NTT%']
  tmp_df['FTT Amt'] = round(tmp_df['FTT%'] * tmp_df['Current']/100,0)
  tmp_df['OTT%'] = round((tmp_df['FTT'] - tmp_df['AvgCost'])*100/tmp_df['AvgCost'],2)
  tmp_df['RRR Ind'] = round(tmp_df['Current P/L']/tmp_df['FTT Amt'],2)
  tmp_df['Risk Ind'] = round(tmp_df['Current P/L%']*tmp_df['CurrAlloc%'],0)

  return tmp_df

# function to print portfolio features
def print_portfolio_stats(df_portfolio_features, myinvmt_df):
  from pyxirr import xirr

  total_booked_amt, reserve_amt, cy_booked_amt, py_booked_amt = get_amt()

  dates = myinvmt_df['Date'].values
  dates = np.append(dates, datetime.date.today().strftime('%d-%b-%y'))
  investment = myinvmt_df['Investment'].values
  dates= pd.to_datetime(dates)

  current = round(sum(df_portfolio_features['Close']*df_portfolio_features['Shares']),0) + reserve_amt
  investment_xirr = np.append(investment, current)
  cagr = round(xirr(pd.DataFrame({"dates": dates, "amounts": investment_xirr}))*100,2)

  investment = -sum(investment)
  invested = round(sum(df_portfolio_features['AvgCost']*df_portfolio_features['Shares']),0) + reserve_amt
  previous = round(sum(df_portfolio_features['Prev_Close']*df_portfolio_features['Shares']),0) + reserve_amt
  cy_invested = investment + py_booked_amt

  today_pnl_amount = current-previous
  today_pnl_percentage = round((current-previous)*100/previous,2)

  curr_pnl_amount = current-invested
  curr_pnl_percentage = round((curr_pnl_amount)*100/(cy_invested),2)

  cy_pnl_amount = cy_booked_amt + curr_pnl_amount
  cy_pnl_percentage = round((cy_pnl_amount)*100/cy_invested,2)

  overall_pnl_amount = total_booked_amt + curr_pnl_amount
  overall_pnl_percentage = round((overall_pnl_amount)*100/investment,2)

  estimate_st = round(sum(df_portfolio_features['FTT']*df_portfolio_features['Shares']),0)  + reserve_amt
  est_st_pnl_amount = estimate_st-current
  est_st_pnl_percentage = round((est_st_pnl_amount)*100/current,2)

  estimate_lt = round(sum(df_portfolio_features['LTT']*df_portfolio_features['Shares']),0)  + reserve_amt
  est_lt_pnl_amount = estimate_lt-current
  est_lt_pnl_percentage = round((est_lt_pnl_amount)*100/current,2)

  total_profit = round(sum(df_portfolio_features[df_portfolio_features['Current P/L%'] > 0]['Current']) - sum(df_portfolio_features[df_portfolio_features['Current P/L%'] > 0]['Investment']),0)
  total_loss = round(sum(df_portfolio_features[df_portfolio_features['Current P/L%'] < 0]['Current']) - sum(df_portfolio_features[df_portfolio_features['Current P/L%'] < 0]['Investment']),0)

  cy_booked_percentage = round((cy_booked_amt)*100/current,2)
  py_booked_percentage = round((py_booked_amt)*100/investment,2)
  total_booked_percentage = round((total_booked_amt)*100/investment,2)

  print('-------------------')
  print('Initial Investment: ', format_amt(investment))
  print('CY Investment: ', format_amt(cy_invested))
  print('Reserve: ', format_amt(reserve_amt))
  print('Current: ',  format_amt(current))
  print('-------------------')
  print('Today PnL: '+ '{} ({}%)'.format(format_amt(today_pnl_amount), today_pnl_percentage))
  print('Current PnL: '+ '{} ({}%)'.format(format_amt(curr_pnl_amount), curr_pnl_percentage))
  print('CY Booked + Current PnL: '+ '{} ({}%)'.format(format_amt(cy_pnl_amount), cy_pnl_percentage))
  print('-------------------')
  print('Total profit: ', format_amt(total_profit))
  print('Total loss: ', format_amt(total_loss))
  print('-------------------')
  print('Total Booked + Current PnL: '+ '{} ({}%)'.format(format_amt(overall_pnl_amount), overall_pnl_percentage))
  print('Total Booked PnL: '+ '{} ({}%)'.format(format_amt(total_booked_amt), total_booked_percentage))
  print('Curr Year Booked PnL: '+ '{} ({}%)'.format(format_amt(cy_booked_amt), cy_booked_percentage))
  print('Prev Year Booked PnL: '+ '{} ({}%)'.format(format_amt(py_booked_amt), py_booked_percentage))
  print('===================')
  print('Est FTT: ',  format_amt(estimate_st))
  print('Est FTT PnL: '+ '{} ({}%)'.format(format_amt(est_st_pnl_amount), est_st_pnl_percentage))

  print('===================')
  print('Deployed: ', format_amt(investment))

  print('Current: ', format_amt(current))

  print('CAGR/XIRR %: '+'{}%'.format(cagr))

In [8]:
# get start and end date
start_date, end_date = get_start_end_date()

# get portfolio and prospects data
mypfs_df = get_mypfs_df()
mypps_df = get_mypps_df()
myinvmt_df = get_myinvmt_df()

# merge above datasets
mypf_df = pd.merge(mypfs_df, mypps_df, on="Symbol")

# seggregate dm and sv portfolio
dm_pf = mypf_df[mypf_df['InPortfolio'] == 'DM']
sv_pf = mypf_df[mypf_df['InPortfolio'] == 'SV']

# build portfolio stock dataframe
dm_stocks = get_stock_ids(dm_pf)
sv_stocks = get_stock_ids(sv_pf)
df_stocks = pd.concat([dm_pf,sv_pf], ignore_index = True)

# arrange common and diff stock features
common_cols = ['Symbol', 'Target', 'Criteria', 'Strategy', 'CumlRnk', 'LatestQtr', 'StarStock', 'Conviction', 'Category', 'InFolio', 'XIRR', 'MBQ']
diff_cols = ['Symbol', 'AvgCost', 'Shares']
df_stocks = arrange_features(df_stocks, common_cols, diff_cols)

# get common features
stock_ids = df_stocks['Symbol'].values
df_common_features = get_common_features(stock_ids, df_stocks)

df_common_features.reset_index(drop=True, inplace=True)
df_common_features.drop(['Date'], axis=1, inplace=True)
# get and print portfolio features
df_portfolio_features = get_portfolio_features(df_common_features)

print_portfolio_stats(df_portfolio_features, myinvmt_df)

df = df_portfolio_features
#plot_pie_chart(df, 'CapType', 'Current')
list_ox40n = list(df[df['MBQ'].str.contains('OX40N', na=False)]['Symbol'].values)

Run date time (IST): 2026-04-17 12:28:31
-------------------
qualified stocks: 86
with latest results: 26
still star stocks: 16
-------------------
Initial Investment:  1.36 C
CY Investment:  1.62 C
Reserve:  1.61 K
Current:  1.44 C
-------------------
Today PnL: 1.82 L (1.28%)
Current PnL: -33.14 L (-20.39%)
CY Booked + Current PnL: -17.25 L (-10.62%)
-------------------
Total profit:  2.37 L
Total loss:  -35.51 L
-------------------
Total Booked + Current PnL: 9.73 L (7.18%)
Total Booked PnL: 42.87 L (31.64%)
Curr Year Booked PnL: 15.89 L (11.04%)
Prev Year Booked PnL: 26.98 L (19.91%)
===================
Est FTT:  2.48 C
Est FTT PnL: 1.04 C (72.15%)
===================
Deployed:  1.36 C
Current:  1.44 C
CAGR/XIRR %: 2.93%

In [9]:
# top 5 near their targets
cols = ['Symbol', 'Today P/L%', 'Current P/L%', 'FTT%', 'OTT%', 'FTT Amt', 'Current P/L', 'Current', 'FTT', 'Dev%_PE', 'RSI_14','Conviction', 'Spread%',  'CumlRnk', 'RRR Ind', 'CurrAlloc%', 'Gained%', 'Criteria', 'Strategy', 'Category']
df_tmp = df_portfolio_features[~df_portfolio_features['Symbol'].isin(['ENRIN','BLUSPRING','DIGITIDE'])]
df_tmp = df_tmp.sort_values(by = 'FTT Amt', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
5,ANGELONE,3.76,24.43,-0.20,24.18,-759.0,74525.0,379525.0,303.00,-81.84,75.0,X-SC,1.97,97.0,-98.19,2.64,45.20,X40N,NTT,FINANCE
50,MASFIN,-0.96,-3.66,26.18,21.57,24713.0,-3585.0,94395.0,397.04,-16.89,55.0,H-SC,3.86,167.0,-0.15,0.66,21.98,XR,ATH,FINANCE
77,TTKPRESTIG,3.02,-35.45,55.07,0.09,35822.0,-35729.0,65048.0,770.00,50.91,55.0,M-SC,23.32,250.0,-1.00,0.45,15.83,OX40N,NTT,DURABLES
67,SONACOMS,2.60,3.10,34.91,39.09,36408.0,3132.0,104291.0,804.02,-18.31,70.0,M-MC,9.22,193.0,0.09,0.72,47.53,AR,ATH,AUTO
57,RECLTD,3.05,1.60,18.84,20.74,38889.0,3245.0,206415.0,446.00,11.33,68.0,M-MC,6.01,191.0,0.08,1.43,23.01,XY25,NTT,FINANCE

In [10]:
# top 5 today
df_tmp = df_portfolio_features.sort_values(by = 'Today P/L%', ascending=False)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
62,SATIN,8.26,-3.01,56.54,51.83,151511.0,-8313.0,267971.0,274.00,-13.27,77.0,H-SC,1.54,159.0,-0.05,1.86,30.54,XY24,NTT,FINANCE
20,COLPAL,5.95,-20.45,77.89,41.51,163180.0,-53865.0,209500.0,3726.84,-3.83,64.0,X-MC,12.83,62.0,-0.33,1.46,17.12,XY25,ATH,FMCG
26,FINCABLES,4.47,20.87,72.01,107.91,128511.0,30819.0,178463.0,1641.55,8.57,68.0,M-SC,2.52,220.0,0.24,1.24,34.26,OX40N,ATH,CABLES
35,HINDUNILVR,4.31,-13.20,30.95,13.67,69062.0,-33923.0,223140.0,2922.00,-35.63,59.0,X-LC,11.75,9.0,-0.49,1.55,8.73,XY25,NTT,FMCG
24,DMART,3.93,10.63,17.15,29.60,47358.0,26538.0,276138.0,5391.45,-6.67,71.0,X-LC,4.09,14.0,0.56,1.92,26.22,X40N,ATH,FMCG

In [11]:
# bottom 5 today
df_tmp = df_portfolio_features.sort_values(by = 'Today P/L%', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
84,WIPRO,-2.75,-16.13,105.40,72.27,149788.0,-27334.0,142114.0,420.00,-24.09,53.0,M-LC,16.25,98.0,-0.18,0.99,9.03,XR,NTT,IT
80,VALIANTORG,-1.48,-41.10,195.70,74.15,188569.0,-67249.0,96356.0,838.00,-273.42,64.0,H-SC,19.35,145.0,-0.36,0.67,43.39,XR,NTT,CHEMICALS
33,HCLTECH,-1.23,-7.04,33.22,23.83,74707.0,-17037.0,224887.0,1908.19,-2.40,54.0,X-LC,8.15,8.0,-0.23,1.56,9.19,X40,ATH,IT
51,MEDANTA,-1.21,-7.70,37.72,27.12,61457.0,-13588.0,162929.0,1486.00,-10.59,55.0,X-SC,15.97,87.0,-0.22,1.13,12.27,XY24,NTT,HEALTHCARE
50,MASFIN,-0.96,-3.66,26.18,21.57,24713.0,-3585.0,94395.0,397.04,-16.89,55.0,H-SC,3.86,167.0,-0.15,0.66,21.98,XR,ATH,FINANCE

In [12]:
# top 5 to exit based on CumlRnk
df_tmp = df_portfolio_features[~df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])]
df_tmp = df_tmp[(df_tmp['Current P/L%'] > -1) & (df_tmp['Current P/L%'] < 1)].sort_values(by = 'CumlRnk', ascending=False)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
85,ZYDUSLIFE,0.8,-0.17,35.87,35.63,75044.0,-364.0,209210.0,1286.17,-13.06,65.0,H-MC,5.42,120.0,-0.0,1.45,15.15,AR,ATH,PHARMA

In [13]:
# OX40N stocks to exit
df_tmp = df_portfolio_features[(df_portfolio_features['Symbol'].isin(list_ox40n))].sort_values(by = 'Current P/L%', ascending=False)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
26,FINCABLES,4.47,20.87,72.01,107.91,128511.0,30819.0,178463.0,1641.55,8.57,68.0,M-SC,2.52,220.0,0.24,1.24,34.26,OX40N,ATH,CABLES
66,SIS,1.17,-25.74,63.29,21.26,52185.0,-28578.0,82454.0,528.00,1943.01,70.0,H-SC,12.10,168.0,-0.55,0.57,22.60,OX40N,NTT,MISC
18,CERA,0.68,-30.61,78.54,23.89,95863.0,-53847.0,122056.0,9475.00,-32.94,67.0,H-SC,14.63,153.0,-0.56,0.85,17.30,OX40N,NTT,CERAMICS
48,KANSAINER,1.61,-32.12,67.17,13.47,122955.0,-86616.0,183051.0,340.00,-41.65,65.0,H-SC,21.79,162.0,-0.70,1.27,27.86,XY24,NTT,PAINTS
72,TATAELXSI,0.01,-33.79,99.40,32.03,86766.0,-44545.0,87290.0,9161.00,-17.17,60.0,H-SC,19.36,158.0,-0.51,0.61,15.53,OX40N,NTT,IT

In [14]:
# top 5 to book for rotation
df_tmp = df_portfolio_features[(df_portfolio_features['Current P/L%'] > 20) ].sort_values(by = 'CumlRnk', ascending=False)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
26,FINCABLES,4.47,20.87,72.01,107.91,128511.0,30819.0,178463.0,1641.55,8.57,68.0,M-SC,2.52,220.0,0.24,1.24,34.26,OX40N,ATH,CABLES
1,ABB,2.39,29.31,12.57,45.57,42525.0,76685.0,338304.0,7934.00,-16.87,74.0,H-MC,17.07,125.0,1.80,2.35,50.23,AR,NTT,ELECTRICAL
5,ANGELONE,3.76,24.43,-0.20,24.18,-759.0,74525.0,379525.0,303.00,-81.84,75.0,X-SC,1.97,97.0,-98.19,2.64,45.20,X40N,NTT,FINANCE

In [15]:
# top 5 to monitor for exit
df_tmp = df_portfolio_features[~df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])]
df_tmp = df_tmp[(df_tmp['Current P/L%'] > 0) ].sort_values(by = 'Dev%_PE', ascending=False)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
57,RECLTD,3.05,1.60,18.84,20.74,38889.0,3245.0,206415.0,446.00,11.33,68.0,M-MC,6.01,191.0,0.08,1.43,23.01,XY25,NTT,FINANCE
26,FINCABLES,4.47,20.87,72.01,107.91,128511.0,30819.0,178463.0,1641.55,8.57,68.0,M-SC,2.52,220.0,0.24,1.24,34.26,OX40N,ATH,CABLES
1,ABB,2.39,29.31,12.57,45.57,42525.0,76685.0,338304.0,7934.00,-16.87,74.0,H-MC,17.07,125.0,1.80,2.35,50.23,AR,NTT,ELECTRICAL
67,SONACOMS,2.60,3.10,34.91,39.09,36408.0,3132.0,104291.0,804.02,-18.31,70.0,M-MC,9.22,193.0,0.09,0.72,47.53,AR,ATH,AUTO

In [16]:
# top 5 to book for rotation from weak conviction
df_tmp = df_portfolio_features[~df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])]
df_tmp = df_tmp[~df_tmp['Criteria'].isin(['XY25','XY24','X40', 'X40N'])].sort_values(by = 'RRR Ind', ascending=False)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
1,ABB,2.39,29.31,12.57,45.57,42525.0,76685.0,338304.0,7934.00,-16.87,74.0,H-MC,17.07,125.0,1.80,2.35,50.23,AR,NTT,ELECTRICAL
26,FINCABLES,4.47,20.87,72.01,107.91,128511.0,30819.0,178463.0,1641.55,8.57,68.0,M-SC,2.52,220.0,0.24,1.24,34.26,OX40N,ATH,CABLES
67,SONACOMS,2.60,3.10,34.91,39.09,36408.0,3132.0,104291.0,804.02,-18.31,70.0,M-MC,9.22,193.0,0.09,0.72,47.53,AR,ATH,AUTO
85,ZYDUSLIFE,0.80,-0.17,35.87,35.63,75044.0,-364.0,209210.0,1286.17,-13.06,65.0,H-MC,5.42,120.0,-0.00,1.45,15.15,AR,ATH,PHARMA
40,INDIAMART,0.44,-6.96,122.19,106.72,140213.0,-8586.0,114750.0,4810.62,-58.01,61.0,H-SC,12.52,140.0,-0.06,0.80,10.24,AR,ATH,MISC

In [17]:
# top 5 to accumulate based on lowest RSI_14
df_tmp = df_portfolio_features[df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])].sort_values(by = 'RSI_14', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
2,ABBOTINDIA,-0.19,-13.42,36.36,18.07,56307.0,-23995.0,154860.0,35195.00,-26.29,44.0,X-MC,11.74,58.0,-0.43,1.08,1.28,X40,ATH,PHARMA
38,ICICIPRULI,-0.55,-8.18,42.37,30.73,76646.0,-16108.0,180897.0,790.00,-32.84,47.0,X-MC,12.56,78.0,-0.21,1.26,10.23,X40,ATH,INSURANCE
53,PGHH,1.14,-25.25,76.61,32.01,122270.0,-53920.0,159600.0,17616.87,-49.41,47.0,X-MC,21.60,57.0,-0.44,1.11,9.16,X40,ATH,FMCG
34,HDFCBANK,0.57,-4.29,34.12,28.37,76702.0,-10085.0,224800.0,1073.00,-18.56,48.0,X-LC,17.25,26.0,-0.13,1.56,9.36,X40,BTT,BANKS
59,RELIANCE,1.43,-12.54,43.27,25.30,76052.0,-25201.0,175762.0,1952.00,-14.65,49.0,X-LC,5.44,21.0,-0.33,1.22,7.33,XY25,BTT,REFINERIES

In [18]:
# top 5 to accumulate based on Spread and CumlRnk
df_tmp = df_portfolio_features[df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])]
df_tmp = df_tmp[(df_tmp['CumlRnk'] < 100)].sort_values(by = 'Spread%', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
65,SIEMENS,2.81,-1.56,27.50,25.51,50380.0,-2895.0,183200.0,4671.50,53.78,71.0,H-LC,1.78,51.0,-0.06,1.27,30.39,AR,ATH,ELECTRICAL
5,ANGELONE,3.76,24.43,-0.20,24.18,-759.0,74525.0,379525.0,303.00,-81.84,75.0,X-SC,1.97,97.0,-98.19,2.64,45.20,X40N,NTT,FINANCE
24,DMART,3.93,10.63,17.15,29.60,47358.0,26538.0,276138.0,5391.45,-6.67,71.0,X-LC,4.09,14.0,0.56,1.92,26.22,X40N,ATH,FMCG
59,RELIANCE,1.43,-12.54,43.27,25.30,76052.0,-25201.0,175762.0,1952.00,-14.65,49.0,X-LC,5.44,21.0,-0.33,1.22,7.33,XY25,BTT,REFINERIES
78,UNITDSPR,3.85,-4.30,26.19,20.77,58687.0,-10062.0,224082.0,1644.00,-15.10,53.0,X-MC,6.39,64.0,-0.17,1.56,6.89,X40N,NTT,BREWERIES

In [19]:
# top 5 to accumulate based on lowest Gained%
df_tmp = df_portfolio_features[df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])].sort_values(by = 'Gained%', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
2,ABBOTINDIA,-0.19,-13.42,36.36,18.07,56307.0,-23995.0,154860.0,35195.0,-26.29,44.0,X-MC,11.74,58.0,-0.43,1.08,1.28,X40,ATH,PHARMA
8,AWL,1.01,-36.66,163.70,67.02,369422.0,-130639.0,225670.0,485.0,-65.95,51.0,X-SC,24.07,81.0,-0.35,1.57,6.74,XY24,NTT,FMCG
45,ITC,1.27,-19.07,47.11,19.06,129692.0,-64870.0,275296.0,452.0,-55.52,55.0,X-LC,19.38,1.0,-0.50,1.91,6.80,X40,NTT,FMCG
78,UNITDSPR,3.85,-4.30,26.19,20.77,58687.0,-10062.0,224082.0,1644.0,-15.10,53.0,X-MC,6.39,64.0,-0.17,1.56,6.89,X40N,NTT,BREWERIES
59,RELIANCE,1.43,-12.54,43.27,25.30,76052.0,-25201.0,175762.0,1952.0,-14.65,49.0,X-LC,5.44,21.0,-0.33,1.22,7.33,XY25,BTT,REFINERIES

In [20]:
# top 5 to accumulate based on lowest CurrAlloc%
df_tmp = df_portfolio_features[df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])].sort_values(by = 'CurrAlloc%', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
58,RELAXO,1.35,-60.04,281.11,52.31,163075.0,-87149.0,58011.0,1176.00,-57.41,58.0,X-SC,32.48,92.0,-0.53,0.40,29.71,X40N,NTT,FOOTWEAR
12,BATAINDIA,1.41,-51.16,176.85,35.20,111131.0,-65831.0,62839.0,2096.00,-17.55,62.0,X-SC,32.70,91.0,-0.59,0.44,24.63,X40,NTT,FOOTWEAR
54,QUESS,0.66,-19.02,114.75,73.90,99235.0,-20314.0,86479.0,424.00,-56.47,62.0,X-SC,20.38,80.0,-0.20,0.60,16.33,XY24,NTT,MISC
2,ABBOTINDIA,-0.19,-13.42,36.36,18.07,56307.0,-23995.0,154860.0,35195.00,-26.29,44.0,X-MC,11.74,58.0,-0.43,1.08,1.28,X40,ATH,PHARMA
53,PGHH,1.14,-25.25,76.61,32.01,122270.0,-53920.0,159600.0,17616.87,-49.41,47.0,X-MC,21.60,57.0,-0.44,1.11,9.16,X40,ATH,FMCG

In [21]:
# top 5 to accumulate based on CumlRnk
df_tmp = df_portfolio_features.sort_values(by = 'CumlRnk', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
45,ITC,1.27,-19.07,47.11,19.06,129692.0,-64870.0,275296.0,452.00,-55.52,55.0,X-LC,19.38,1.0,-0.50,1.91,6.80,X40,NTT,FMCG
73,TCS,0.14,-24.25,67.08,26.57,235416.0,-112325.0,350948.0,4311.59,-35.76,56.0,X-LC,16.95,2.0,-0.48,2.44,9.53,X40,ATH,IT
43,INFY,-0.52,-10.66,50.26,34.24,140497.0,-33347.0,279541.0,1972.00,-29.61,51.0,X-LC,13.41,3.0,-0.24,1.94,7.50,X40,NTT,IT
75,TMPV,0.56,-18.44,67.46,36.58,195784.0,-65618.0,290223.0,600.00,-82.53,63.0,X-LC,10.64,4.0,-0.34,2.02,20.97,XY24,NTT,AUTO
33,HCLTECH,-1.23,-7.04,33.22,23.83,74707.0,-17037.0,224887.0,1908.19,-2.40,54.0,X-LC,8.15,8.0,-0.23,1.56,9.19,X40,ATH,IT

In [22]:
# top 5 for average up
df_tmp = df_portfolio_features[(df_portfolio_features['Dev%_200'] > 5)].sort_values(by = 'CurrAlloc%', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
67,SONACOMS,2.60,3.10,34.91,39.09,36408.0,3132.0,104291.0,804.02,-18.31,70.0,M-MC,9.22,193.0,0.09,0.72,47.53,AR,ATH,AUTO
69,SURYODAY,-0.54,-18.52,51.00,23.03,74415.0,-33160.0,145911.0,216.00,60.09,63.0,H-SC,3.99,166.0,-0.45,1.01,24.43,XR,NTT,BANKS
26,FINCABLES,4.47,20.87,72.01,107.91,128511.0,30819.0,178463.0,1641.55,8.57,68.0,M-SC,2.52,220.0,0.24,1.24,34.26,OX40N,ATH,CABLES
65,SIEMENS,2.81,-1.56,27.50,25.51,50380.0,-2895.0,183200.0,4671.50,53.78,71.0,H-LC,1.78,51.0,-0.06,1.27,30.39,AR,ATH,ELECTRICAL
57,RECLTD,3.05,1.60,18.84,20.74,38889.0,3245.0,206415.0,446.00,11.33,68.0,M-MC,6.01,191.0,0.08,1.43,23.01,XY25,NTT,FINANCE

In [23]:
# top 5 RSP
df_tmp = df_portfolio_features.sort_values(by = 'RSP', ascending=False)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
80,VALIANTORG,-1.48,-41.10,195.70,74.15,188569.0,-67249.0,96356.0,838.00,-273.42,64.0,H-SC,19.35,145.0,-0.36,0.67,43.39,XR,NTT,CHEMICALS
5,ANGELONE,3.76,24.43,-0.20,24.18,-759.0,74525.0,379525.0,303.00,-81.84,75.0,X-SC,1.97,97.0,-98.19,2.64,45.20,X40N,NTT,FINANCE
52,PAGEIND,3.24,-0.42,34.67,34.11,92659.0,-1119.0,267260.0,51418.64,-28.65,78.0,X-MC,15.38,55.0,-0.01,1.86,26.42,X40,ATH,APPARELS
55,RAJESHEXPO,1.14,-75.18,303.11,0.07,103215.0,-103125.0,34052.0,518.00,1147.47,64.0,L-SC,42.40,268.0,-1.00,0.24,59.87,OX40N,NTT,JEWELLERY
24,DMART,3.93,10.63,17.15,29.60,47358.0,26538.0,276138.0,5391.45,-6.67,71.0,X-LC,4.09,14.0,0.56,1.92,26.22,X40N,ATH,FMCG

In [24]:
# Top N allocation
df_tmp = df_portfolio_features.sort_values(by = 'CurrAlloc%', ascending=False)
top_n_values = [10, 25, 50]

sum_df = pd.DataFrame({
    'Top_N': top_n_values,
    'Sum_Alloc%': [df_tmp['CurrAlloc%'].head(n).sum() for n in top_n_values]
})

sum_df

   Top_N  Sum_Alloc%
0     10       21.08
1     25       45.81
2     50       77.83

In [25]:
# market-cap-wise allocation
df_tmp = df_portfolio_features[cols]
df_tmp.groupby(df_tmp['Conviction'].str[-2:])['CurrAlloc%'].sum().sort_values(ascending=False)

Conviction
SC    45.36
MC    29.56
LC    25.11
Name: CurrAlloc%, dtype: float64

In [26]:
# criteria-wise allocation
df_portfolio_features.groupby('Criteria')['CurrAlloc%'].sum().sort_values(ascending=False)

Criteria
XY24     27.12
X40      24.47
X40N     15.92
AR        9.33
XR        8.37
XY25      7.15
OX40N     6.88
SR        0.79
Name: CurrAlloc%, dtype: float64

In [27]:
# conviction-wise allocation
df_portfolio_features.groupby('Conviction')['CurrAlloc%'].sum().sort_values(ascending=False)

Conviction
X-LC    22.85
H-SC    22.13
X-MC    21.99
X-SC    12.49
M-SC    10.13
H-MC     5.08
M-MC     2.15
H-LC     1.27
M-LC     0.99
L-SC     0.61
L-MC     0.34
Name: CurrAlloc%, dtype: float64

In [28]:
# sector-wise stats
df_tmp = df_portfolio_features.groupby('Category')[['CurrAlloc%', 'Current', 'Current P/L', 'FTT Amt']].sum().sort_values(by=['Current', 'Current P/L'], ascending=False)
df_tmp['Current P/L%'] = round(df_tmp['Current P/L'] * 100 / df_tmp['Current'], 2)
df_tmp['FTT%'] = round(df_tmp['FTT Amt'] * 100 / df_tmp['Current'], 2)
cols = ['CurrAlloc%', 'Current P/L%', 'FTT%']
df_tmp[cols].sort_values(by=['CurrAlloc%'], ascending=False)

               CurrAlloc%  Current P/L%    FTT%
Category
FMCG                14.75        -17.65   59.40
FINANCE             13.64         -9.51   54.14
IT                  11.54        -35.63  104.65
MISC                 7.18        -29.61   85.91
ELECTRICAL           6.66         -1.10   39.81
PAINTS               5.31        -28.94   51.33
BANKS                4.52        -18.24   78.26
INSURANCE            4.52         -4.26   39.94
PHARMA               3.90         -4.79   37.77
AUTO                 3.85        -18.16   65.04
AC                   2.01        -10.49   40.45
HEALTHCARE           1.90        -30.55   64.62
APPARELS             1.86         -0.42   34.67
TRAVEL               1.82        -70.47  155.83
FOOTWEAR             1.82        -68.73  136.38
DURABLES             1.74        -54.39   91.96
BREWERIES            1.56         -4.49   26.19
REALTY               1.44         -7.05   24.64
CERAMICS             1.34        -59.05  107.37
CABLES               1.24         17.27   72.01
REFINERIES           1.22        -14.34   43.27
CEMENT               1.19        -56.14  172.96
ENGINEERING          1.18        -43.00  108.40
JEWELLERY            1.12        -98.80  167.87
CHEMICALS            1.10        -67.00  203.24
ENTERTAINMENT        0.80        -66.31  165.51
TEXTILES             0.45        -43.49   84.40
HOTELS               0.37       -112.89  187.98

In [29]:
# money to be made criteria-wise
df_portfolio_features.groupby('Criteria')['FTT Amt'].agg(['sum', 'count']).sort_values(by='sum', ascending=False)

                sum  count
Criteria
XY24      3693225.0     21
X40       1655274.0     16
XR        1287018.0     12
AR        1226710.0     10
X40N      1007953.0     10
OX40N      802068.0     10
XY25       411299.0      5
SR         305602.0      2

In [30]:
# money to be made conviction-wise
df_portfolio_features.groupby('Conviction')['FTT Amt'].agg(['sum', 'count']).sort_values(by='sum', ascending=False)

                  sum  count
Conviction
H-SC        3605821.0     24
X-MC        1571834.0     15
X-LC        1487142.0     13
M-SC        1459754.0     14
X-SC        1384398.0     10
H-MC         347020.0      3
L-SC         203480.0      2
M-LC         149788.0      1
M-MC          75297.0      2
L-MC          54235.0      1
H-LC          50380.0      1

In [31]:
# money to be made criteria and conviction-wise
df_portfolio_features.groupby(['Conviction', 'Criteria'])['FTT Amt'].agg(['sum', 'count']).sort_values(by='sum', ascending=False)

                           sum  count
Conviction Criteria
H-SC       XY24      1205272.0      6
           AR         948847.0      5
M-SC       XY24       850765.0      6
X-LC       X40        827614.0      7
X-SC       XY24       827121.0      4
H-SC       XR         798545.0      7
X-MC       X40        626183.0      7
           X40N       476820.0      4
X-SC       X40N       355800.0      4
M-SC       OX40N      351298.0      5
H-SC       OX40N      347555.0      4
X-LC       XY24       339081.0      2
H-SC       SR         305602.0      2
X-MC       XY24       241535.0      2
H-MC       XY24       229451.0      1
X-MC       XY25       227296.0      2
X-SC       X40        201477.0      2
M-SC       XR         184185.0      2
X-LC       X40N       175333.0      2
M-LC       XR         149788.0      1
X-LC       XY25       145114.0      2
H-MC       AR         117569.0      2
L-SC       OX40N      103215.0      1
           XR         100265.0      1
M-SC       AR          73506.0      1
L-MC       XR          54235.0      1
H-LC       AR          50380.0      1
M-MC       XY25        38889.0      1
           AR          36408.0      1

In [32]:
# notebook execution time

end_time = time.time()
execution_time = round(end_time - start_time, 0)
print(f"Notebook execution time: {execution_time} seconds")

Notebook execution time: 50.0 seconds