<a href="https://colab.research.google.com/github/ankit-rathi/Quantvesting_v2/blob/main/myStocks_Portfolio_Analysis.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
'''
!pip install pandas==2.2.2 -qq
!pip install pyxirr -qq
!pip install ta -qq
!pip install yfinance==0.2.59 -qq
'''

'\n!pip install pandas==2.2.2 -qq\n!pip install pyxirr -qq\n!pip install ta -qq\n!pip install yfinance==0.2.59 -qq\n'

In [2]:
# import libraries

import numpy as np
import pandas as pd
import datetime
import warnings
warnings.filterwarnings('ignore')
import yfinance as yfin
import ta
import matplotlib.pyplot as plt
import requests

In [3]:
# notebook start time
import time
import datetime
import pytz

start_time = time.time()

# function to print date timestamp
def print_date_time():
  tz_NY = pytz.timezone('Asia/Kolkata')
  datetime_NY = datetime.datetime.now(tz_NY)
  print("Run date time (IST):", datetime_NY.strftime("%Y-%m-%d %H:%M:%S"))

In [4]:
# function to get booked and reserved amount
def get_amt():
  # fetch the JSON data from the URL
  url = "https://raw.githubusercontent.com/ankit-rathi/Tradevesting_v1/main/data/myPortfolioAmts.json"
  response = requests.get(url)
  pf_amts = response.json()  # parse the JSON data

  # extract values from the JSON
  py_booked_amt_dm = pf_amts["py_booked_amt_dm"]
  py_booked_amt_sv = pf_amts["py_booked_amt_sv"]
  cy_booked_amt_dm = pf_amts["cy_booked_amt_dm"]
  cy_booked_amt_sv = pf_amts["cy_booked_amt_sv"]
  reserve_amt_dm = pf_amts["reserve_amt_dm"]
  reserve_amt_sv = pf_amts["reserve_amt_sv"]

  # perform calculations
  py_booked_amt = py_booked_amt_dm + py_booked_amt_sv
  cy_booked_amt = cy_booked_amt_dm + cy_booked_amt_sv
  reserve_amt = reserve_amt_dm + reserve_amt_sv
  total_booked_amt = py_booked_amt + cy_booked_amt

  return total_booked_amt, reserve_amt, cy_booked_amt, py_booked_amt

gen_output = 0

In [5]:
# function to format the amount
def format_amt(number):
    abs_number = abs(number)

    if abs_number >= 1_00_00_000:  # Crores
        formatted_amt = f"{number / 1_00_00_000:.2f} C"
    elif abs_number >= 1_00_000:  # Lakhs
        formatted_amt = f"{number / 1_00_000:.2f} L"
    elif abs_number >= 1_000:  # Thousands
        formatted_amt = f"{number / 1_000:.2f} K"
    else:
        formatted_amt = f"{number:.2f}"

    return formatted_amt

# function to set start and end date
def get_start_end_date():
  start_date = (datetime.date.today() + datetime.timedelta(days=-365)).strftime('%Y-%m-%d')
  end_date = (datetime.date.today() + datetime.timedelta(days=1)).strftime('%Y-%m-%d')
  return start_date, end_date

# function to fetch my portfolio csv
def get_mypfs_df():
  mypfs_df = pd.read_csv('https://raw.githubusercontent.com/ankit-rathi/Tradevesting_v1/main/data/myPortfolioStocks.csv')
  return mypfs_df

# function to fetch my prospects csv
def get_mypps_df():
  mypps_df = pd.read_csv('https://raw.githubusercontent.com/ankit-rathi/Tradevesting_v1/main/data/myProspectsScrips.csv')
  return mypps_df

# function to fetch screener data
def get_myscreen_df():
  myscreen_df = pd.read_csv('https://raw.githubusercontent.com/ankit-rathi/Tradevesting_v1/main/data/myScreenerDB.csv')
  return myscreen_df

# function to fetch momentum data
def get_myinvmt_df():
  myinvmt_df = pd.read_csv('https://raw.githubusercontent.com/ankit-rathi/Tradevesting_v1/main/data/myInvestments.csv')
  return myinvmt_df

# function to get the stock ids
def get_stock_ids(df_pf):
  stock_n100 = df_pf['Symbol'].unique()

  exclude = ['CADILAHC','MMTC', 'MASFIN']

  stock_ids = df_pf[~df_pf['Symbol'].isin(exclude) ]['Symbol'].unique()

  #mypf = mypf[mypf.Forecast.notnull()]
  #stock_ids = mypf['Symbol'].unique()

  #stock_ids.sort()
  return stock_ids

# get features from screener data
def get_screener_features():
  myscreen_df = get_myscreen_df()
  cols = ['Symbol', 'EPS', 'MedPE', 'ROCE%', 'ROE%', 'CapType']
  return myscreen_df[cols]

# get relative strength
def get_relative_strength(stock_list):

    # Dictionary to store stock tickers and their corresponding percentage price change
    stock_changes = {}

    # Loop through each stock and fetch its price data
    for stock in stock_list:
        try:
            # Download the stock data for the given date range
            stock_data = yfin.Ticker(stock + '.NS').history(period='1mo', interval='1d')[map(str.title, ['open', 'close', 'low', 'high', 'volume'])]

            # Calculate the percentage change for the stock
            if len(stock_data) > 0:
                start_price = stock_data['Close'].iloc[0]
                end_price = stock_data['Close'].iloc[-1]
                percent_change = round(((end_price - start_price) / start_price) * 100, 2)
                stock_changes[stock] = percent_change
            else:
                stock_changes[stock] = np.nan  # If no data is available, set to NaN

        except Exception as e:
            print(f"Error fetching data for {stock}: {e}")
            stock_changes[stock] = np.nan

    # Create a DataFrame with stock tickers and their percentage changes
    df = pd.DataFrame(list(stock_changes.items()), columns=['Symbol', 'Percent_Change'])

    # Drop any stocks with missing data (NaN values)
    df = df.dropna()

    # Calculate the percentile rank based on percentage change
    df['RSP'] = round(df['Percent_Change'].rank(pct=True) * 100, 2)
    cols = ['Symbol', 'RSP']
    df = df[cols]
    # Sort by percentile rank (optional)
    df = df.sort_values(by='RSP', ascending=False).reset_index(drop=True)

    return df

In [6]:
# function to get stock technicals
def stock_prec_dev(stock_symbol):
    #stock_symbol = 'ULTRACEMCO.NS'
    short_window = 20
    mid_window = 50
    long_window = 200
    moving_avg = 'SMA'

    start = datetime.datetime(*map(int, start_date.split('-')))
    end = datetime.datetime(*map(int, end_date.split('-')))

    stock_df = yfin.Ticker(stock_symbol + '.NS').history(period='max', interval='1d')[map(str.title, ['open', 'close', 'low', 'high', 'volume'])]

    stock_df['Max'] = round(max(stock_df['Close']),2)
    stock_df = stock_df[(stock_df.index <= end_date) & (stock_df.index >= start_date)]
    stock_df['200_SMA'] = round(stock_df['Close'].rolling(window = 200, min_periods = 1).mean(),0)
    stock_df['Dev%_200'] = round((stock_df['Close'] - stock_df['200_SMA'])*100/stock_df['200_SMA'],2)
    stock_df.dropna(axis = 0, inplace = True) # remove any null rows

    stock_df['20_SMA'] = stock_df['Close'].rolling(window=20).mean()
    stock_df['50_SMA'] = stock_df['Close'].rolling(window=50).mean()
    stock_df['Symbol'] = stock_symbol

    stock_df['Close'] = round(stock_df['Close'],2)
    stock_df['Min'] = round(min(stock_df['Close']),2)
    stock_df['RSI_14'] = ta.momentum.RSIIndicator(close=stock_df['Close'], window=14).rsi()
    stock_df['RSI_14'] = round(stock_df['RSI_14'],0)
    stock_df['Prev_Close'] = stock_df['Close'].shift(1)
    stock_df.drop(['Open', 'Low', 'High', 'Volume'], axis=1, inplace=True)
    stock_df = stock_df.tail(1)

    max_SMA = max(stock_df['20_SMA'].item(), stock_df['50_SMA'].item(), stock_df['200_SMA'].item())
    min_SMA = min(stock_df['20_SMA'].item(), stock_df['50_SMA'].item(), stock_df['200_SMA'].item())
    ABS_Spread = max_SMA - min_SMA
    stock_df['Spread%'] = round((ABS_Spread / stock_df['200_SMA'].item()) * 100,2)

    return stock_df

# function to compute stock attributes
def get_common_features(stock_ids, df_mypf):

  df_prec_dev = pd.DataFrame()
  df_tmp = get_screener_features()
  df_rs = get_relative_strength(stock_ids)

  for stock_id in stock_ids:
      tmp = stock_prec_dev(stock_id)
      tmp = tmp.reset_index()
      df_prec_dev = pd.concat([df_prec_dev, tmp], ignore_index = True)
  df_prec_dev = pd.merge(df_prec_dev, df_mypf, on= 'Symbol')
  df_prec_dev = pd.merge(df_prec_dev, df_tmp, on= 'Symbol', how='left')
  df_prec_dev = pd.merge(df_prec_dev, df_rs, on= 'Symbol', how='left')
  #print(df_prec_dev.columns)
  df_prec_dev['Curr_PE'] = round(df_prec_dev['Close']/df_prec_dev['EPS'],1)
  df_prec_dev['Dev%_PE'] = round((df_prec_dev['Curr_PE'] - df_prec_dev['MedPE'])*100/df_prec_dev['MedPE'],2)
  df_prec_dev['Conviction'] = df_prec_dev['Conviction'] + '-' + df_prec_dev['CapType']
  return df_prec_dev

# function to arrange stock features
def arrange_features(df_stocks, common_cols, diff_cols):
  df_stocks_common = df_stocks[common_cols].drop_duplicates()
  df_stocks_diff = df_stocks[diff_cols]
  df_stocks_diff['Investment'] = df_stocks_diff['AvgCost'] * df_stocks_diff['Shares']
  df_stocks_diff = df_stocks_diff.groupby(['Symbol'])[['Shares', 'Investment']].aggregate(['sum']).reset_index()
  df_stocks_diff.columns = ['Symbol', 'Shares', 'Investment']
  df_stocks_diff['AvgCost'] = round(df_stocks_diff['Investment']/df_stocks_diff['Shares'],2)
  df_stocks = pd.merge(df_stocks_diff, df_stocks_common, on='Symbol')
  return df_stocks

# plot fact distribution across dimension
def plot_pie_chart(df, dimension, fact):
  # grouping the data by category and calculating the sum of fact for each type
  grouped_data = df.groupby(dimension)[fact].sum()

  # sorting the grouped data in descending order
  grouped_data = grouped_data.sort_values(ascending=False)

  # creating a pie chart
  grouped_data.plot.pie(autopct='%1.1f%%', startangle=90, figsize=(6, 6))

  # adding a title and displaying the plot
  plt.title(f'{dimension} {fact} Distribution')
  plt.ylabel('')  # To hide the y-label
  plt.show()

In [7]:
# function to get portfolio features

def get_portfolio_features(df_common_features):

  print_date_time()
  print('-------------------')

  #df_common_features["Target"] = df_common_features["Target"].fillna(df_common_features["Max"])
  df_common_features['NTT'] = np.where(df_common_features['Strategy']== 'NTT', df_common_features["Target"], df_common_features['Max'])
  df_common_features['LTT'] = np.where(df_common_features['Strategy']== 'BTT', df_common_features["Target"], df_common_features['Max'])
  df_common_features['BOL'] = df_common_features['Min']

  tmp_df = df_common_features[df_common_features['Symbol'].isin(mypf_df[mypf_df['InPortfolio'] != 'NA'].Symbol.values)]
  print('qualified stocks: '+str(len(tmp_df['Symbol'].unique())))
  tmp_df1 = tmp_df[tmp_df['LatestQtr'] == 1]
  print('with latest results: '+str(len(tmp_df1['Symbol'].unique())))
  tmp_df1 = tmp_df1[tmp_df1['StarStock'] == 1]
  print('still star stocks: '+str(len(tmp_df1['Symbol'].unique())))
  tmp_df['Investment'] = tmp_df['AvgCost'] * tmp_df['Shares']
  tmp_df['Current'] = round(tmp_df['Close'] * tmp_df['Shares'],0)
  tmp_df['Previous'] = tmp_df['Prev_Close'] * tmp_df['Shares']
  tmp_df['EstimatedST'] = tmp_df['NTT'] * tmp_df['Shares']
  tmp_df['EstimatedLT'] = tmp_df['LTT'] * tmp_df['Shares']
  tmp_df['Current P/L'] = round((tmp_df['Current'] - tmp_df['Investment']),0)
  tmp_df['Today P/L%'] = round((tmp_df['Current'] - tmp_df['Previous'])*100/tmp_df['Previous'],2)
  tmp_df['Current P/L%'] = round((tmp_df['Current'] - tmp_df['Investment'])*100/tmp_df['Investment'],2)
  tmp_df['EstimatedST P/L%'] = round((tmp_df['EstimatedST'] - tmp_df['Investment'])*100/tmp_df['Investment'],2)
  tmp_df['EstimatedLT P/L%'] = round((tmp_df['EstimatedLT'] - tmp_df['Investment'])*100/tmp_df['Investment'],2)
  tmp_df['NTT%'] = round((tmp_df['NTT'] - tmp_df['Close'])*100/tmp_df['Close'],2)
  tmp_df['LTT%'] = round((tmp_df['LTT'] - tmp_df['Close'])*100/tmp_df['Close'],2)
  tmp_df['Gained%'] = round((tmp_df['Close'] - tmp_df['BOL'])*100/tmp_df['BOL'],2)
  investment = round(sum(tmp_df['AvgCost']*tmp_df['Shares']),0)
  current = round(sum(tmp_df['Close']*tmp_df['Shares']),0)
  tmp_df['InitAlloc%'] = round(tmp_df['Investment']*100/investment,2)
  tmp_df['CurrAlloc%'] = round(tmp_df['Current']*100/current,2)
  tmp_df['FTT'] = tmp_df['LTT']
  tmp_df.loc[tmp_df['Strategy'] == 'NTT', 'FTT'] = tmp_df['NTT']
  tmp_df['FTT%'] = tmp_df['LTT%']
  tmp_df.loc[tmp_df['Strategy'] == 'NTT', 'FTT%'] = tmp_df['NTT%']
  tmp_df['FTT Amt'] = round(tmp_df['FTT%'] * tmp_df['Current']/100,0)
  tmp_df['OTT%'] = round((tmp_df['FTT'] - tmp_df['AvgCost'])*100/tmp_df['AvgCost'],2)
  tmp_df['RRR Ind'] = round(tmp_df['Current P/L']/tmp_df['FTT Amt'],2)
  tmp_df['Risk Ind'] = round(tmp_df['Current P/L%']*tmp_df['CurrAlloc%'],0)

  return tmp_df

# function to print portfolio features
def print_portfolio_stats(df_portfolio_features, myinvmt_df):
  from pyxirr import xirr

  total_booked_amt, reserve_amt, cy_booked_amt, py_booked_amt = get_amt()

  dates = myinvmt_df['Date'].values
  dates = np.append(dates, datetime.date.today().strftime('%d-%b-%y'))
  investment = myinvmt_df['Investment'].values
  dates= pd.to_datetime(dates)

  current = round(sum(df_portfolio_features['Close']*df_portfolio_features['Shares']),0) + reserve_amt
  investment_xirr = np.append(investment, current)
  cagr = round(xirr(pd.DataFrame({"dates": dates, "amounts": investment_xirr}))*100,2)

  investment = -sum(investment)
  invested = round(sum(df_portfolio_features['AvgCost']*df_portfolio_features['Shares']),0) + reserve_amt
  previous = round(sum(df_portfolio_features['Prev_Close']*df_portfolio_features['Shares']),0) + reserve_amt
  cy_invested = investment + py_booked_amt

  today_pnl_amount = current-previous
  today_pnl_percentage = round((current-previous)*100/previous,2)

  curr_pnl_amount = current-invested
  curr_pnl_percentage = round((curr_pnl_amount)*100/(cy_invested),2)

  cy_pnl_amount = cy_booked_amt + curr_pnl_amount
  cy_pnl_percentage = round((cy_pnl_amount)*100/cy_invested,2)

  overall_pnl_amount = total_booked_amt + curr_pnl_amount
  overall_pnl_percentage = round((overall_pnl_amount)*100/investment,2)

  estimate_st = round(sum(df_portfolio_features['FTT']*df_portfolio_features['Shares']),0)  + reserve_amt
  est_st_pnl_amount = estimate_st-current
  est_st_pnl_percentage = round((est_st_pnl_amount)*100/current,2)

  estimate_lt = round(sum(df_portfolio_features['LTT']*df_portfolio_features['Shares']),0)  + reserve_amt
  est_lt_pnl_amount = estimate_lt-current
  est_lt_pnl_percentage = round((est_lt_pnl_amount)*100/current,2)

  total_profit = round(sum(df_portfolio_features[df_portfolio_features['Current P/L%'] > 0]['Current']) - sum(df_portfolio_features[df_portfolio_features['Current P/L%'] > 0]['Investment']),0)
  total_loss = round(sum(df_portfolio_features[df_portfolio_features['Current P/L%'] < 0]['Current']) - sum(df_portfolio_features[df_portfolio_features['Current P/L%'] < 0]['Investment']),0)

  cy_booked_percentage = round((cy_booked_amt)*100/current,2)
  py_booked_percentage = round((py_booked_amt)*100/investment,2)
  total_booked_percentage = round((total_booked_amt)*100/investment,2)

  print('-------------------')
  print('Initial Investment: ', format_amt(investment))
  print('CY Investment: ', format_amt(cy_invested))
  print('Reserve: ', format_amt(reserve_amt))
  print('Current: ',  format_amt(current))
  print('-------------------')
  print('Today PnL: '+ '{} ({}%)'.format(format_amt(today_pnl_amount), today_pnl_percentage))
  print('Current PnL: '+ '{} ({}%)'.format(format_amt(curr_pnl_amount), curr_pnl_percentage))
  print('CY Booked + Current PnL: '+ '{} ({}%)'.format(format_amt(cy_pnl_amount), cy_pnl_percentage))
  print('-------------------')
  print('Total profit: ', format_amt(total_profit))
  print('Total loss: ', format_amt(total_loss))
  print('-------------------')
  print('Total Booked + Current PnL: '+ '{} ({}%)'.format(format_amt(overall_pnl_amount), overall_pnl_percentage))
  print('Total Booked PnL: '+ '{} ({}%)'.format(format_amt(total_booked_amt), total_booked_percentage))
  print('Curr Year Booked PnL: '+ '{} ({}%)'.format(format_amt(cy_booked_amt), cy_booked_percentage))
  print('Prev Year Booked PnL: '+ '{} ({}%)'.format(format_amt(py_booked_amt), py_booked_percentage))
  print('===================')
  print('Est FTT: ',  format_amt(estimate_st))
  print('Est FTT PnL: '+ '{} ({}%)'.format(format_amt(est_st_pnl_amount), est_st_pnl_percentage))

  print('===================')
  print('Deployed: ', format_amt(investment))

  print('Current: ', format_amt(current))

  print('CAGR/XIRR %: '+'{}%'.format(cagr))

In [8]:
# get start and end date
start_date, end_date = get_start_end_date()

# get portfolio and prospects data
mypfs_df = get_mypfs_df()
mypps_df = get_mypps_df()
myinvmt_df = get_myinvmt_df()

# merge above datasets
mypf_df = pd.merge(mypfs_df, mypps_df, on="Symbol")

# seggregate dm and sv portfolio
dm_pf = mypf_df[mypf_df['InPortfolio'] == 'DM']
sv_pf = mypf_df[mypf_df['InPortfolio'] == 'SV']

# build portfolio stock dataframe
dm_stocks = get_stock_ids(dm_pf)
sv_stocks = get_stock_ids(sv_pf)
df_stocks = pd.concat([dm_pf,sv_pf], ignore_index = True)

# arrange common and diff stock features
common_cols = ['Symbol', 'Target', 'Criteria', 'Strategy', 'CumlRnk', 'LatestQtr', 'StarStock', 'Conviction', 'Category', 'InFolio', 'XIRR', 'MBQ']
diff_cols = ['Symbol', 'AvgCost', 'Shares']
df_stocks = arrange_features(df_stocks, common_cols, diff_cols)

# get common features
stock_ids = df_stocks['Symbol'].values
df_common_features = get_common_features(stock_ids, df_stocks)

df_common_features.reset_index(drop=True, inplace=True)
df_common_features.drop(['Date'], axis=1, inplace=True)
# get and print portfolio features
df_portfolio_features = get_portfolio_features(df_common_features)

print_portfolio_stats(df_portfolio_features, myinvmt_df)

df = df_portfolio_features
#plot_pie_chart(df, 'CapType', 'Current')
list_ox40n = list(df[df['MBQ'].str.contains('OX40N', na=False)]['Symbol'].values)

Run date time (IST): 2026-06-22 18:41:19
-------------------
qualified stocks: 92
with latest results: 31
still star stocks: 20
-------------------
Initial Investment:  1.40 C
CY Investment:  1.82 C
Reserve:  1.49 K
Current:  1.53 C
-------------------
Today PnL: 60.43 K (0.4%)
Current PnL: -30.37 L (-16.65%)
CY Booked + Current PnL: -28.29 L (-15.51%)
-------------------
Total profit:  3.85 L
Total loss:  -34.22 L
-------------------
Total Booked + Current PnL: 14.58 L (10.45%)
Total Booked PnL: 44.95 L (32.22%)
Curr Year Booked PnL: 2.08 L (1.36%)
Prev Year Booked PnL: 42.87 L (30.73%)
===================
Est FTT:  2.55 C
Est FTT PnL: 1.02 C (66.93%)
===================
Deployed:  1.40 C
Current:  1.53 C
CAGR/XIRR %: 4.25%

In [9]:
# top 5 near their targets
cols = ['Symbol', 'Today P/L%', 'Current P/L%', 'FTT%', 'OTT%', 'FTT Amt', 'Current P/L', 'Current', 'FTT', 'Dev%_PE', 'RSI_14','Conviction', 'Spread%',  'CumlRnk', 'RRR Ind', 'CurrAlloc%', 'Gained%', 'Criteria', 'Strategy', 'Category']
df_tmp = df_portfolio_features[~df_portfolio_features['Symbol'].isin(['ENRIN','BLUSPRING','DIGITIDE'])]
df_tmp = df_tmp.sort_values(by = 'FTT Amt', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
59,PIDILITIND,-0.49,11.42,6.24,18.37,9811.0,16110.0,157220.0,1670.26,-21.94,71.0,X-LC,3.83,5.0,1.64,1.03,23.45,X40,ATH,CHEMICALS
51,KOTAKBANK,0.73,7.46,12.70,21.11,18897.0,10324.0,148796.0,453.24,-7.67,62.0,X-LC,5.36,12.0,0.55,0.97,13.79,X40,ATH,BANKS
55,MASFIN,-0.45,-2.76,25.01,21.57,23830.0,-2700.0,95280.0,397.04,-15.99,55.0,H-SC,3.12,167.0,-0.11,0.62,13.57,XR,ATH,FINANCE
72,SIS,0.76,-0.56,21.94,21.26,24225.0,-617.0,110415.0,528.00,2635.75,65.0,H-SC,23.58,168.0,-0.03,0.72,64.17,OX40N,NTT,MISC
49,JSWINFRA,-0.36,4.53,11.38,16.43,26381.0,10049.0,231823.0,342.00,-10.44,69.0,X-MC,2.33,61.0,0.38,1.52,31.44,X40N,NTT,REALTY

In [10]:
# top 5 today
df_tmp = df_portfolio_features.sort_values(by = 'Today P/L%', ascending=False)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
69,SFL,5.87,-27.02,73.51,26.63,140678.0,-70846.0,191372.0,1287.00,44.93,75.0,M-SC,10.67,242.0,-0.50,1.25,59.50,XY24,NTT,MISC
61,RAJESHEXPO,5.00,-80.22,405.96,0.07,110141.0,-110046.0,27131.0,518.00,894.95,53.0,L-SC,35.64,268.0,-1.00,0.18,33.99,OX40N,NTT,JEWELLERY
17,CIPLA,4.73,14.62,16.42,33.43,28825.0,22386.0,175547.0,1648.14,-11.14,62.0,X-LC,4.80,18.0,0.78,1.15,19.84,X40N,ATH,PHARMA
83,TTKPRESTIG,4.18,-26.70,36.55,0.09,27000.0,-26906.0,73871.0,770.00,71.40,63.0,M-SC,9.78,250.0,-1.00,0.48,31.54,OX40N,NTT,DURABLES
63,RECLTD,4.08,0.12,20.59,20.74,41884.0,248.0,203418.0,446.00,9.37,65.0,M-MC,2.04,191.0,0.01,1.33,21.22,XY25,NTT,FINANCE

In [11]:
# bottom 5 today
df_tmp = df_portfolio_features.sort_values(by = 'Today P/L%', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
87,VBL,-3.13,3.62,30.65,35.37,100306.0,11420.0,327262.0,670.16,-8.57,44.0,X-LC,12.49,13.0,0.11,2.14,34.51,X40N,ATH,FMCG
13,BSOFT,-2.86,-42.52,162.32,50.79,131232.0,-59805.0,80848.0,831.70,-26.17,42.0,H-SC,14.29,172.0,-0.46,0.53,2.41,XR,ATH,IT
44,INDUSINDBK,-2.79,-32.00,95.43,32.89,50101.0,-24706.0,52500.0,1800.00,-347.20,52.0,L-MC,7.52,258.0,-0.49,0.34,29.22,XR,NTT,BANKS
10,BATAINDIA,-2.23,-52.85,186.73,35.20,113295.0,-67997.0,60673.0,2096.00,-20.43,58.0,X-SC,23.64,91.0,-0.60,0.40,20.33,X40,NTT,FOOTWEAR
86,VALIANTORG,-2.23,-40.89,194.60,74.15,188203.0,-66892.0,96713.0,838.00,-274.05,49.0,H-SC,3.17,145.0,-0.36,0.63,43.92,XR,NTT,CHEMICALS

In [12]:
# top 5 to exit based on CumlRnk
df_tmp = df_portfolio_features[~df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])]
df_tmp = df_tmp[(df_tmp['Current P/L%'] > -1) & (df_tmp['Current P/L%'] < 1)].sort_values(by = 'CumlRnk', ascending=False)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
63,RECLTD,4.08,0.12,20.59,20.74,41884.0,248.0,203418.0,446.0,9.37,65.0,M-MC,2.04,191.0,0.01,1.33,21.22,XY25,NTT,FINANCE
9,BANDHANBNK,0.12,0.22,92.00,92.42,256829.0,603.0,279162.0,400.0,139.22,55.0,H-SC,23.00,174.0,0.00,1.83,53.78,XY24,NTT,BANKS
72,SIS,0.76,-0.56,21.94,21.26,24225.0,-617.0,110415.0,528.0,2635.75,65.0,H-SC,23.58,168.0,-0.03,0.72,64.17,OX40N,NTT,MISC
75,SURYODAY,0.05,-0.22,23.31,23.03,41649.0,-398.0,178673.0,216.0,95.18,61.0,H-SC,19.40,166.0,-0.01,1.17,50.44,XR,NTT,BANKS

In [13]:
# OX40N stocks to exit
df_tmp = df_portfolio_features[(df_portfolio_features['Symbol'].isin(list_ox40n))].sort_values(by = 'Current P/L%', ascending=False)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
25,FINCABLES,2.25,50.78,37.89,107.91,84352.0,74980.0,222624.0,1641.55,35.46,67.0,M-SC,24.96,220.0,0.89,1.46,67.49,OX40N,ATH,CABLES
72,SIS,0.76,-0.56,21.94,21.26,24225.0,-617.0,110415.0,528.00,2635.75,65.0,H-SC,23.58,168.0,-0.03,0.72,64.17,OX40N,NTT,MISC
16,CERA,3.31,-12.90,42.24,23.89,64718.0,-22689.0,153214.0,9475.00,-15.99,77.0,H-SC,6.90,153.0,-0.35,1.00,47.24,OX40N,NTT,CERAMICS
83,TTKPRESTIG,4.18,-26.70,36.55,0.09,27000.0,-26906.0,73871.0,770.00,71.40,63.0,M-SC,9.78,250.0,-1.00,0.48,31.54,OX40N,NTT,DURABLES
69,SFL,5.87,-27.02,73.51,26.63,140678.0,-70846.0,191372.0,1287.00,44.93,75.0,M-SC,10.67,242.0,-0.50,1.25,59.50,XY24,NTT,MISC

In [14]:
# top 5 to book for rotation
df_tmp = df_portfolio_features[(df_portfolio_features['Current P/L%'] > 20) ].sort_values(by = 'CumlRnk', ascending=False)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
25,FINCABLES,2.25,50.78,37.89,107.91,84352.0,74980.0,222624.0,1641.55,35.46,67.0,M-SC,24.96,220.0,0.89,1.46,67.49,OX40N,ATH,CABLES
68,SATIN,0.30,30.85,16.04,51.83,57987.0,85231.0,361515.0,274.00,16.95,60.0,H-SC,40.76,159.0,1.47,2.37,76.11,XY24,NTT,FINANCE

In [15]:
# top 5 to monitor for exit
df_tmp = df_portfolio_features[~df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])]
df_tmp = df_tmp[(df_tmp['Current P/L%'] > 0) ].sort_values(by = 'Dev%_PE', ascending=False)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
9,BANDHANBNK,0.12,0.22,92.00,92.42,256829.0,603.0,279162.0,400.00,139.22,55.0,H-SC,23.00,174.0,0.00,1.83,53.78,XY24,NTT,BANKS
74,STARHEALTH,0.28,12.60,30.78,47.26,97435.0,35431.0,316554.0,761.00,77.79,78.0,H-SC,11.34,173.0,0.36,2.07,38.98,XY24,NTT,INSURANCE
25,FINCABLES,2.25,50.78,37.89,107.91,84352.0,74980.0,222624.0,1641.55,35.46,67.0,M-SC,24.96,220.0,0.89,1.46,67.49,OX40N,ATH,CABLES
68,SATIN,0.30,30.85,16.04,51.83,57987.0,85231.0,361515.0,274.00,16.95,60.0,H-SC,40.76,159.0,1.47,2.37,76.11,XY24,NTT,FINANCE
63,RECLTD,4.08,0.12,20.59,20.74,41884.0,248.0,203418.0,446.00,9.37,65.0,M-MC,2.04,191.0,0.01,1.33,21.22,XY25,NTT,FINANCE

In [16]:
# top 5 to book for rotation from weak conviction
df_tmp = df_portfolio_features[~df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])]
df_tmp = df_tmp[~df_tmp['Criteria'].isin(['XY25','XY24','X40', 'X40N'])].sort_values(by = 'RRR Ind', ascending=False)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
25,FINCABLES,2.25,50.78,37.89,107.91,84352.0,74980.0,222624.0,1641.55,35.46,67.0,M-SC,24.96,220.0,0.89,1.46,67.49,OX40N,ATH,CABLES
91,ZYDUSLIFE,1.37,14.47,18.49,35.63,44357.0,30322.0,239896.0,1286.17,-0.45,59.0,H-MC,13.66,120.0,0.68,1.57,26.13,AR,ATH,PHARMA
73,SONACOMS,1.17,7.43,29.47,39.09,32027.0,7516.0,108675.0,804.02,-14.93,63.0,M-MC,18.52,193.0,0.23,0.71,53.74,AR,ATH,AUTO
75,SURYODAY,0.05,-0.22,23.31,23.03,41649.0,-398.0,178673.0,216.00,95.18,61.0,H-SC,19.40,166.0,-0.01,1.17,50.44,XR,NTT,BANKS
72,SIS,0.76,-0.56,21.94,21.26,24225.0,-617.0,110415.0,528.00,2635.75,65.0,H-SC,23.58,168.0,-0.03,0.72,64.17,OX40N,NTT,MISC

In [17]:
# top 5 to accumulate based on lowest RSI_14
df_tmp = df_portfolio_features[df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])].sort_values(by = 'RSI_14', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
45,INFY,1.33,-27.47,85.09,34.24,193095.0,-85958.0,226930.0,1972.00,-43.03,36.0,X-LC,16.94,3.0,-0.45,1.49,1.33,X40,NTT,IT
79,TCS,0.13,-37.54,99.92,24.88,289149.0,-173892.0,289381.0,4253.91,-47.23,38.0,X-LC,19.33,2.0,-0.60,1.89,0.13,X40,ATH,IT
20,DABUR,-0.30,-17.45,74.07,43.70,151689.0,-43277.0,204791.0,735.00,-25.01,40.0,X-MC,11.64,70.0,-0.29,1.34,2.87,XY24,BTT,FMCG
19,COLPAL,-0.79,-24.74,85.84,39.86,170135.0,-65165.0,198200.0,3683.41,-8.99,40.0,X-MC,3.80,62.0,-0.38,1.30,12.11,XY25,ATH,FMCG
33,HCLTECH,-0.11,-26.63,65.62,21.51,116468.0,-64436.0,177488.0,1872.35,-23.08,41.0,X-LC,18.42,8.0,-0.55,1.16,1.88,X40,ATH,IT

In [18]:
# top 5 to accumulate based on Spread and CumlRnk
df_tmp = df_portfolio_features[df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])]
df_tmp = df_tmp[(df_tmp['CumlRnk'] < 100)].sort_values(by = 'Spread%', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
49,JSWINFRA,-0.36,4.53,11.38,16.43,26381.0,10049.0,231823.0,342.00,-10.44,69.0,X-MC,2.33,61.0,0.38,1.52,31.44,X40N,NTT,REALTY
11,BERGEPAINT,-0.12,1.37,23.63,25.32,61739.0,3525.0,261274.0,680.00,-4.22,67.0,X-MC,3.08,68.0,0.06,1.71,35.98,XY24,NTT,PAINTS
56,MEDANTA,1.76,10.19,15.36,27.12,29876.0,17986.0,194503.0,1486.00,6.85,66.0,X-SC,3.16,87.0,0.60,1.27,34.02,XY24,NTT,HEALTHCARE
57,PAGEIND,-1.64,2.56,30.26,33.59,83288.0,6861.0,275240.0,51217.29,-26.52,58.0,X-MC,3.71,55.0,0.08,1.80,30.71,X40,ATH,APPARELS
19,COLPAL,-0.79,-24.74,85.84,39.86,170135.0,-65165.0,198200.0,3683.41,-8.99,40.0,X-MC,3.80,62.0,-0.38,1.30,12.11,XY25,ATH,FMCG

In [19]:
# top 5 to accumulate based on lowest Gained%
df_tmp = df_portfolio_features[df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])].sort_values(by = 'Gained%', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
79,TCS,0.13,-37.54,99.92,24.88,289149.0,-173892.0,289381.0,4253.91,-47.23,38.0,X-LC,19.33,2.0,-0.60,1.89,0.13,X40,ATH,IT
45,INFY,1.33,-27.47,85.09,34.24,193095.0,-85958.0,226930.0,1972.00,-43.03,36.0,X-LC,16.94,3.0,-0.45,1.49,1.33,X40,NTT,IT
58,PGHH,-1.27,-31.39,92.40,32.01,135370.0,-67016.0,146504.0,17616.87,-53.57,42.0,X-MC,19.79,57.0,-0.50,0.96,1.83,X40,ATH,FMCG
33,HCLTECH,-0.11,-26.63,65.62,21.51,116468.0,-64436.0,177488.0,1872.35,-23.08,41.0,X-LC,18.42,8.0,-0.55,1.16,1.88,X40,ATH,IT
20,DABUR,-0.30,-17.45,74.07,43.70,151689.0,-43277.0,204791.0,735.00,-25.01,40.0,X-MC,11.64,70.0,-0.29,1.34,2.87,XY24,BTT,FMCG

In [20]:
# top 5 to accumulate based on lowest CurrAlloc%
df_tmp = df_portfolio_features[df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])].sort_values(by = 'CurrAlloc%', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
10,BATAINDIA,-2.23,-52.85,186.73,35.20,113295.0,-67997.0,60673.0,2096.00,-20.43,58.0,X-SC,23.64,91.0,-0.60,0.40,20.33,X40,NTT,FOOTWEAR
64,RELAXO,0.11,-53.86,230.11,52.31,154116.0,-78185.0,66975.0,1176.00,-50.92,62.0,X-SC,15.88,92.0,-0.51,0.44,49.75,X40N,NTT,FOOTWEAR
60,QUESS,-1.60,0.84,72.44,73.90,78014.0,902.0,107695.0,424.00,-46.01,71.0,X-SC,8.71,80.0,0.01,0.70,46.81,XY24,NTT,MISC
28,GODREJCP,1.89,-8.76,44.09,31.47,59783.0,-13020.0,135594.0,1469.04,-3.99,49.0,X-LC,9.36,32.0,-0.22,0.89,4.04,X40N,ATH,FMCG
53,M&M,-0.37,-0.60,24.12,23.38,33250.0,-828.0,137853.0,3802.40,-15.83,48.0,X-LC,10.52,25.0,-0.02,0.90,4.51,X40N,ATH,AUTO

In [21]:
# top 5 to accumulate based on CumlRnk
df_tmp = df_portfolio_features.sort_values(by = 'CumlRnk', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
47,ITC,-0.43,-23.28,55.19,19.06,144024.0,-79206.0,260960.0,452.00,-57.95,53.0,X-LC,15.12,1.0,-0.55,1.71,5.14,X40,NTT,FMCG
79,TCS,0.13,-37.54,99.92,24.88,289149.0,-173892.0,289381.0,4253.91,-47.23,38.0,X-LC,19.33,2.0,-0.60,1.89,0.13,X40,ATH,IT
45,INFY,1.33,-27.47,85.09,34.24,193095.0,-85958.0,226930.0,1972.00,-43.03,36.0,X-LC,16.94,3.0,-0.45,1.49,1.33,X40,NTT,IT
81,TMPV,0.56,-17.71,65.98,36.58,193199.0,-63026.0,292815.0,600.00,-82.53,44.0,X-LC,11.03,4.0,-0.33,1.92,23.06,XY24,NTT,AUTO
59,PIDILITIND,-0.49,11.42,6.24,18.37,9811.0,16110.0,157220.0,1670.26,-21.94,71.0,X-LC,3.83,5.0,1.64,1.03,23.45,X40,ATH,CHEMICALS

In [22]:
# top 5 for average up
df_tmp = df_portfolio_features[(df_portfolio_features['Dev%_200'] > 5)].sort_values(by = 'CurrAlloc%', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
44,INDUSINDBK,-2.79,-32.00,95.43,32.89,50101.0,-24706.0,52500.0,1800.00,-347.20,52.0,L-MC,7.52,258.0,-0.49,0.34,29.22,XR,NTT,BANKS
21,DEN,-0.30,-37.53,127.41,42.07,67232.0,-31696.0,52768.0,75.00,86.53,76.0,M-SC,7.05,235.0,-0.47,0.35,43.52,AR,NTT,ENTERTAINMENT
3,ALKYLAMINE,-0.65,-21.91,147.96,93.63,116652.0,-22123.0,78840.0,4546.37,-16.40,58.0,H-SC,6.59,142.0,-0.19,0.52,48.87,SR,ATH,CHEMICALS
60,QUESS,-1.60,0.84,72.44,73.90,78014.0,902.0,107695.0,424.00,-46.01,71.0,X-SC,8.71,80.0,0.01,0.70,46.81,XY24,NTT,MISC
73,SONACOMS,1.17,7.43,29.47,39.09,32027.0,7516.0,108675.0,804.02,-14.93,63.0,M-MC,18.52,193.0,0.23,0.71,53.74,AR,ATH,AUTO

In [23]:
# top 5 RSP
df_tmp = df_portfolio_features.sort_values(by = 'RSP', ascending=False)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
18,COFFEEDAY,-1.22,-42.48,135.16,35.27,88284.0,-48231.0,65318.0,80.0,-55.73,56.0,L-SC,15.26,266.0,-0.55,0.43,61.08,XR,NTT,HOTELS
21,DEN,-0.30,-37.53,127.41,42.07,67232.0,-31696.0,52768.0,75.0,86.53,76.0,M-SC,7.05,235.0,-0.47,0.35,43.52,AR,NTT,ENTERTAINMENT
80,TITAGARH,-0.20,-13.33,68.15,45.74,143045.0,-32280.0,209897.0,1548.0,15.46,67.0,H-SC,6.57,175.0,-0.23,1.37,60.15,XY24,NTT,ENGINEERING
60,QUESS,-1.60,0.84,72.44,73.90,78014.0,902.0,107695.0,424.0,-46.01,71.0,X-SC,8.71,80.0,0.01,0.70,46.81,XY24,NTT,MISC
64,RELAXO,0.11,-53.86,230.11,52.31,154116.0,-78185.0,66975.0,1176.0,-50.92,62.0,X-SC,15.88,92.0,-0.51,0.44,49.75,X40N,NTT,FOOTWEAR

In [24]:
# Top N allocation
df_tmp = df_portfolio_features.sort_values(by = 'CurrAlloc%', ascending=False)
top_n_values = [10, 25, 50]

sum_df = pd.DataFrame({
    'Top_N': top_n_values,
    'Sum_Alloc%': [df_tmp['CurrAlloc%'].head(n).sum() for n in top_n_values]
})

sum_df

   Top_N  Sum_Alloc%
0     10       19.29
1     25       42.49
2     50       72.75

In [25]:
# market-cap-wise allocation
df_tmp = df_portfolio_features[cols]
df_tmp.groupby(df_tmp['Conviction'].str[-2:])['CurrAlloc%'].sum().sort_values(ascending=False)

Conviction
SC    43.70
LC    30.58
MC    25.73
Name: CurrAlloc%, dtype: float64

In [26]:
# criteria-wise allocation
df_portfolio_features.groupby('Criteria')['CurrAlloc%'].sum().sort_values(ascending=False)

Criteria
XY24     27.77
X40      24.61
X40N     17.30
XR        8.91
OX40N     7.21
AR        6.82
XY25      6.51
SR        0.88
Name: CurrAlloc%, dtype: float64

In [27]:
# conviction-wise allocation
df_portfolio_features.groupby('Conviction')['CurrAlloc%'].sum().sort_values(ascending=False)

Conviction
X-LC    28.53
H-SC    22.93
X-MC    20.67
M-SC    10.22
X-SC     9.94
H-MC     2.68
M-MC     2.04
H-LC     1.23
M-LC     0.82
L-SC     0.61
L-MC     0.34
Name: CurrAlloc%, dtype: float64

In [28]:
# sector-wise stats
df_tmp = df_portfolio_features.groupby('Category')[['CurrAlloc%', 'Current', 'Current P/L', 'FTT Amt']].sum().sort_values(by=['Current', 'Current P/L'], ascending=False)
df_tmp['Current P/L%'] = round(df_tmp['Current P/L'] * 100 / df_tmp['Current'], 2)
df_tmp['FTT%'] = round(df_tmp['FTT Amt'] * 100 / df_tmp['Current'], 2)
cols = ['CurrAlloc%', 'Current P/L%', 'FTT%']
df_tmp[cols].sort_values(by=['CurrAlloc%'], ascending=False)

               CurrAlloc%  Current P/L%    FTT%
Category
FMCG                14.51        -19.40   61.28
FINANCE             11.04         -9.30   56.83
IT                   9.70        -51.96  127.94
MISC                 7.24        -21.12   73.09
AUTO                 6.63         -8.26   48.85
BANKS                5.76         -3.19   50.90
PAINTS               5.60        -15.38   35.42
INSURANCE            5.40         -0.36   34.21
PHARMA               4.98          2.63   27.51
ELECTRICAL           4.11        -12.52   52.24
CHEMICALS            2.18        -21.91   94.56
HEALTHCARE           2.06        -13.32   42.89
AC                   1.84        -13.94   44.83
APPARELS             1.80          2.49   30.26
FOOTWEAR             1.72        -68.39  135.92
TRAVEL               1.61        -81.19  171.91
DURABLES             1.57        -60.25   99.24
REALTY               1.52          4.33   11.38
BREWERIES            1.51         -1.36   22.40
CERAMICS             1.47        -36.74   78.29
CABLES               1.46         33.68   37.89
ENGINEERING          1.37        -15.38   68.15
REFINERIES           1.12        -17.44   47.15
JEWELLERY            1.07        -96.03  164.14
CEMENT               1.06        -65.54  189.38
ENTERTAINMENT        0.83        -53.36  144.83
HOTELS               0.43        -73.84  135.16
TEXTILES             0.42        -42.94   83.70

In [29]:
# money to be made criteria-wise
df_portfolio_features.groupby('Criteria')['FTT Amt'].agg(['sum', 'count']).sort_values(by='sum', ascending=False)

                sum  count
Criteria
XY24      3352800.0     21
X40       1922530.0     19
XR        1319811.0     13
AR        1135570.0      9
X40N      1079475.0     13
OX40N      690110.0     10
XY25       441729.0      5
SR         285873.0      2

In [30]:
# money to be made conviction-wise
df_portfolio_features.groupby('Conviction')['FTT Amt'].agg(['sum', 'count']).sort_values(by='sum', ascending=False)

                  sum  count
Conviction
H-SC        3276331.0     24
X-LC        1930561.0     21
X-MC        1558019.0     15
M-SC        1355919.0     14
X-SC        1284821.0      9
H-MC         287960.0      2
L-SC         198425.0      2
M-LC         166674.0      1
M-MC          73911.0      2
L-MC          50101.0      1
H-LC          45176.0      1

In [31]:
# money to be made criteria and conviction-wise
df_portfolio_features.groupby(['Conviction', 'Criteria'])['FTT Amt'].agg(['sum', 'count']).sort_values(by='sum', ascending=False)

                           sum  count
Conviction Criteria
X-LC       X40       1045103.0     10
H-SC       XY24       968192.0      6
           AR         946778.0      5
M-SC       XY24       812031.0      6
H-SC       XR         784508.0      7
X-SC       XY24       780165.0      4
X-MC       X40        670092.0      7
           X40N       429055.0      4
X-LC       X40N       353099.0      6
           XY24       335381.0      2
X-SC       X40N       297321.0      3
H-SC       OX40N      290980.0      4
M-SC       OX40N      288989.0      5
H-SC       SR         285873.0      2
X-MC       XY25       245444.0      2
H-MC       XY24       243603.0      1
X-MC       XY24       213428.0      2
X-SC       X40        207335.0      2
M-SC       XR         187667.0      2
M-LC       XR         166674.0      1
X-LC       XY25       154401.0      2
L-SC       OX40N      110141.0      1
           XR          88284.0      1
M-SC       AR          67232.0      1
L-MC       XR          50101.0      1
H-LC       AR          45176.0      1
H-MC       AR          44357.0      1
X-LC       XR          42577.0      1
M-MC       XY25        41884.0      1
           AR          32027.0      1

In [32]:
# notebook execution time

end_time = time.time()
execution_time = round(end_time - start_time, 0)
print(f"Notebook execution time: {execution_time} seconds")

Notebook execution time: 30.0 seconds