<a href="https://colab.research.google.com/github/ankit-rathi/Quantvesting_v2/blob/main/myStocks_Portfolio_Analysis.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
'''
!pip install pandas==2.2.2 -qq
!pip install pyxirr -qq
!pip install ta -qq
!pip install yfinance==0.2.59 -qq
'''

'\n!pip install pandas==2.2.2 -qq\n!pip install pyxirr -qq\n!pip install ta -qq\n!pip install yfinance==0.2.59 -qq\n'

In [2]:
# import libraries

import numpy as np
import pandas as pd
import datetime
import warnings
warnings.filterwarnings('ignore')
import yfinance as yfin
import ta
import matplotlib.pyplot as plt
import requests

In [3]:
# notebook start time
import time
import datetime
import pytz

start_time = time.time()

# function to print date timestamp
def print_date_time():
  tz_NY = pytz.timezone('Asia/Kolkata')
  datetime_NY = datetime.datetime.now(tz_NY)
  print("Run date time (IST):", datetime_NY.strftime("%Y-%m-%d %H:%M:%S"))

In [4]:
# function to get booked and reserved amount
def get_amt():
  # fetch the JSON data from the URL
  url = "https://raw.githubusercontent.com/ankit-rathi/Tradevesting_v1/main/data/myPortfolioAmts.json"
  response = requests.get(url)
  pf_amts = response.json()  # parse the JSON data

  # extract values from the JSON
  py_booked_amt_dm = pf_amts["py_booked_amt_dm"]
  py_booked_amt_sv = pf_amts["py_booked_amt_sv"]
  cy_booked_amt_dm = pf_amts["cy_booked_amt_dm"]
  cy_booked_amt_sv = pf_amts["cy_booked_amt_sv"]
  reserve_amt_dm = pf_amts["reserve_amt_dm"]
  reserve_amt_sv = pf_amts["reserve_amt_sv"]

  # perform calculations
  py_booked_amt = py_booked_amt_dm + py_booked_amt_sv
  cy_booked_amt = cy_booked_amt_dm + cy_booked_amt_sv
  reserve_amt = reserve_amt_dm + reserve_amt_sv
  total_booked_amt = py_booked_amt + cy_booked_amt

  return total_booked_amt, reserve_amt, cy_booked_amt, py_booked_amt

gen_output = 0

In [5]:
# function to format the amount
def format_amt(number):
    abs_number = abs(number)

    if abs_number >= 1_00_00_000:  # Crores
        formatted_amt = f"{number / 1_00_00_000:.2f} C"
    elif abs_number >= 1_00_000:  # Lakhs
        formatted_amt = f"{number / 1_00_000:.2f} L"
    elif abs_number >= 1_000:  # Thousands
        formatted_amt = f"{number / 1_000:.2f} K"
    else:
        formatted_amt = f"{number:.2f}"

    return formatted_amt

# function to set start and end date
def get_start_end_date():
  start_date = (datetime.date.today() + datetime.timedelta(days=-365)).strftime('%Y-%m-%d')
  end_date = (datetime.date.today() + datetime.timedelta(days=1)).strftime('%Y-%m-%d')
  return start_date, end_date

# function to fetch my portfolio csv
def get_mypfs_df():
  mypfs_df = pd.read_csv('https://raw.githubusercontent.com/ankit-rathi/Tradevesting_v1/main/data/myPortfolioStocks.csv')
  return mypfs_df

# function to fetch my prospects csv
def get_mypps_df():
  mypps_df = pd.read_csv('https://raw.githubusercontent.com/ankit-rathi/Tradevesting_v1/main/data/myProspectsScrips.csv')
  return mypps_df

# function to fetch screener data
def get_myscreen_df():
  myscreen_df = pd.read_csv('https://raw.githubusercontent.com/ankit-rathi/Tradevesting_v1/main/data/myScreenerDB.csv')
  return myscreen_df

# function to fetch momentum data
def get_myinvmt_df():
  myinvmt_df = pd.read_csv('https://raw.githubusercontent.com/ankit-rathi/Tradevesting_v1/main/data/myInvestments.csv')
  return myinvmt_df

# function to get the stock ids
def get_stock_ids(df_pf):
  stock_n100 = df_pf['Symbol'].unique()

  exclude = ['CADILAHC','MMTC', 'MASFIN']

  stock_ids = df_pf[~df_pf['Symbol'].isin(exclude) ]['Symbol'].unique()

  #mypf = mypf[mypf.Forecast.notnull()]
  #stock_ids = mypf['Symbol'].unique()

  #stock_ids.sort()
  return stock_ids

# get features from screener data
def get_screener_features():
  myscreen_df = get_myscreen_df()
  cols = ['Symbol', 'EPS', 'MedPE', 'ROCE%', 'ROE%', 'CapType']
  return myscreen_df[cols]

# get relative strength
def get_relative_strength(stock_list):

    # Dictionary to store stock tickers and their corresponding percentage price change
    stock_changes = {}

    # Loop through each stock and fetch its price data
    for stock in stock_list:
        try:
            # Download the stock data for the given date range
            stock_data = yfin.Ticker(stock + '.NS').history(period='1mo', interval='1d')[map(str.title, ['open', 'close', 'low', 'high', 'volume'])]

            # Calculate the percentage change for the stock
            if len(stock_data) > 0:
                start_price = stock_data['Close'].iloc[0]
                end_price = stock_data['Close'].iloc[-1]
                percent_change = round(((end_price - start_price) / start_price) * 100, 2)
                stock_changes[stock] = percent_change
            else:
                stock_changes[stock] = np.nan  # If no data is available, set to NaN

        except Exception as e:
            print(f"Error fetching data for {stock}: {e}")
            stock_changes[stock] = np.nan

    # Create a DataFrame with stock tickers and their percentage changes
    df = pd.DataFrame(list(stock_changes.items()), columns=['Symbol', 'Percent_Change'])

    # Drop any stocks with missing data (NaN values)
    df = df.dropna()

    # Calculate the percentile rank based on percentage change
    df['RSP'] = round(df['Percent_Change'].rank(pct=True) * 100, 2)
    cols = ['Symbol', 'RSP']
    df = df[cols]
    # Sort by percentile rank (optional)
    df = df.sort_values(by='RSP', ascending=False).reset_index(drop=True)

    return df

In [6]:
# function to get stock technicals
def stock_prec_dev(stock_symbol):
    #stock_symbol = 'ULTRACEMCO.NS'
    short_window = 20
    mid_window = 50
    long_window = 200
    moving_avg = 'SMA'

    start = datetime.datetime(*map(int, start_date.split('-')))
    end = datetime.datetime(*map(int, end_date.split('-')))

    stock_df = yfin.Ticker(stock_symbol + '.NS').history(period='max', interval='1d')[map(str.title, ['open', 'close', 'low', 'high', 'volume'])]

    stock_df['Max'] = round(max(stock_df['Close']),2)
    stock_df = stock_df[(stock_df.index <= end_date) & (stock_df.index >= start_date)]
    stock_df['200_SMA'] = round(stock_df['Close'].rolling(window = 200, min_periods = 1).mean(),0)
    stock_df['Dev%_200'] = round((stock_df['Close'] - stock_df['200_SMA'])*100/stock_df['200_SMA'],2)
    stock_df.dropna(axis = 0, inplace = True) # remove any null rows

    stock_df['20_SMA'] = stock_df['Close'].rolling(window=20).mean()
    stock_df['50_SMA'] = stock_df['Close'].rolling(window=50).mean()
    stock_df['Symbol'] = stock_symbol

    stock_df['Close'] = round(stock_df['Close'],2)
    stock_df['Min'] = round(min(stock_df['Close']),2)
    stock_df['RSI_14'] = ta.momentum.RSIIndicator(close=stock_df['Close'], window=14).rsi()
    stock_df['RSI_14'] = round(stock_df['RSI_14'],0)
    stock_df['Prev_Close'] = stock_df['Close'].shift(1)
    stock_df.drop(['Open', 'Low', 'High', 'Volume'], axis=1, inplace=True)
    stock_df = stock_df.tail(1)

    max_SMA = max(stock_df['20_SMA'].item(), stock_df['50_SMA'].item(), stock_df['200_SMA'].item())
    min_SMA = min(stock_df['20_SMA'].item(), stock_df['50_SMA'].item(), stock_df['200_SMA'].item())
    ABS_Spread = max_SMA - min_SMA
    stock_df['Spread%'] = round((ABS_Spread / stock_df['200_SMA'].item()) * 100,2)

    return stock_df

# function to compute stock attributes
def get_common_features(stock_ids, df_mypf):

  df_prec_dev = pd.DataFrame()
  df_tmp = get_screener_features()
  df_rs = get_relative_strength(stock_ids)

  for stock_id in stock_ids:
      tmp = stock_prec_dev(stock_id)
      tmp = tmp.reset_index()
      df_prec_dev = pd.concat([df_prec_dev, tmp], ignore_index = True)
  df_prec_dev = pd.merge(df_prec_dev, df_mypf, on= 'Symbol')
  df_prec_dev = pd.merge(df_prec_dev, df_tmp, on= 'Symbol', how='left')
  df_prec_dev = pd.merge(df_prec_dev, df_rs, on= 'Symbol', how='left')
  #print(df_prec_dev.columns)
  df_prec_dev['Curr_PE'] = round(df_prec_dev['Close']/df_prec_dev['EPS'],1)
  df_prec_dev['Dev%_PE'] = round((df_prec_dev['Curr_PE'] - df_prec_dev['MedPE'])*100/df_prec_dev['MedPE'],2)
  df_prec_dev['Conviction'] = df_prec_dev['Conviction'] + '-' + df_prec_dev['CapType']
  return df_prec_dev

# function to arrange stock features
def arrange_features(df_stocks, common_cols, diff_cols):
  df_stocks_common = df_stocks[common_cols].drop_duplicates()
  df_stocks_diff = df_stocks[diff_cols]
  df_stocks_diff['Investment'] = df_stocks_diff['AvgCost'] * df_stocks_diff['Shares']
  df_stocks_diff = df_stocks_diff.groupby(['Symbol'])[['Shares', 'Investment']].aggregate(['sum']).reset_index()
  df_stocks_diff.columns = ['Symbol', 'Shares', 'Investment']
  df_stocks_diff['AvgCost'] = round(df_stocks_diff['Investment']/df_stocks_diff['Shares'],2)
  df_stocks = pd.merge(df_stocks_diff, df_stocks_common, on='Symbol')
  return df_stocks

# plot fact distribution across dimension
def plot_pie_chart(df, dimension, fact):
  # grouping the data by category and calculating the sum of fact for each type
  grouped_data = df.groupby(dimension)[fact].sum()

  # sorting the grouped data in descending order
  grouped_data = grouped_data.sort_values(ascending=False)

  # creating a pie chart
  grouped_data.plot.pie(autopct='%1.1f%%', startangle=90, figsize=(6, 6))

  # adding a title and displaying the plot
  plt.title(f'{dimension} {fact} Distribution')
  plt.ylabel('')  # To hide the y-label
  plt.show()

In [7]:
# function to get portfolio features

def get_portfolio_features(df_common_features):

  print_date_time()
  print('-------------------')

  #df_common_features["Target"] = df_common_features["Target"].fillna(df_common_features["Max"])
  df_common_features['NTT'] = np.where(df_common_features['Strategy']== 'NTT', df_common_features["Target"], df_common_features['Max'])
  df_common_features['LTT'] = np.where(df_common_features['Strategy']== 'BTT', df_common_features["Target"], df_common_features['Max'])
  df_common_features['BOL'] = df_common_features['Min']

  tmp_df = df_common_features[df_common_features['Symbol'].isin(mypf_df[mypf_df['InPortfolio'] != 'NA'].Symbol.values)]
  print('qualified stocks: '+str(len(tmp_df['Symbol'].unique())))
  tmp_df1 = tmp_df[tmp_df['LatestQtr'] == 1]
  print('with latest results: '+str(len(tmp_df1['Symbol'].unique())))
  tmp_df1 = tmp_df1[tmp_df1['StarStock'] == 1]
  print('still star stocks: '+str(len(tmp_df1['Symbol'].unique())))
  tmp_df['Investment'] = tmp_df['AvgCost'] * tmp_df['Shares']
  tmp_df['Current'] = round(tmp_df['Close'] * tmp_df['Shares'],0)
  tmp_df['Previous'] = tmp_df['Prev_Close'] * tmp_df['Shares']
  tmp_df['EstimatedST'] = tmp_df['NTT'] * tmp_df['Shares']
  tmp_df['EstimatedLT'] = tmp_df['LTT'] * tmp_df['Shares']
  tmp_df['Current P/L'] = round((tmp_df['Current'] - tmp_df['Investment']),0)
  tmp_df['Today P/L%'] = round((tmp_df['Current'] - tmp_df['Previous'])*100/tmp_df['Previous'],2)
  tmp_df['Current P/L%'] = round((tmp_df['Current'] - tmp_df['Investment'])*100/tmp_df['Investment'],2)
  tmp_df['EstimatedST P/L%'] = round((tmp_df['EstimatedST'] - tmp_df['Investment'])*100/tmp_df['Investment'],2)
  tmp_df['EstimatedLT P/L%'] = round((tmp_df['EstimatedLT'] - tmp_df['Investment'])*100/tmp_df['Investment'],2)
  tmp_df['NTT%'] = round((tmp_df['NTT'] - tmp_df['Close'])*100/tmp_df['Close'],2)
  tmp_df['LTT%'] = round((tmp_df['LTT'] - tmp_df['Close'])*100/tmp_df['Close'],2)
  tmp_df['Gained%'] = round((tmp_df['Close'] - tmp_df['BOL'])*100/tmp_df['BOL'],2)
  investment = round(sum(tmp_df['AvgCost']*tmp_df['Shares']),0)
  current = round(sum(tmp_df['Close']*tmp_df['Shares']),0)
  tmp_df['InitAlloc%'] = round(tmp_df['Investment']*100/investment,2)
  tmp_df['CurrAlloc%'] = round(tmp_df['Current']*100/current,2)
  tmp_df['FTT'] = tmp_df['LTT']
  tmp_df.loc[tmp_df['Strategy'] == 'NTT', 'FTT'] = tmp_df['NTT']
  tmp_df['FTT%'] = tmp_df['LTT%']
  tmp_df.loc[tmp_df['Strategy'] == 'NTT', 'FTT%'] = tmp_df['NTT%']
  tmp_df['FTT Amt'] = round(tmp_df['FTT%'] * tmp_df['Current']/100,0)
  tmp_df['OTT%'] = round((tmp_df['FTT'] - tmp_df['AvgCost'])*100/tmp_df['AvgCost'],2)
  tmp_df['RRR Ind'] = round(tmp_df['Current P/L']/tmp_df['FTT Amt'],2)
  tmp_df['Risk Ind'] = round(tmp_df['Current P/L%']*tmp_df['CurrAlloc%'],0)

  return tmp_df

# function to print portfolio features
def print_portfolio_stats(df_portfolio_features, myinvmt_df):
  from pyxirr import xirr

  total_booked_amt, reserve_amt, cy_booked_amt, py_booked_amt = get_amt()

  dates = myinvmt_df['Date'].values
  dates = np.append(dates, datetime.date.today().strftime('%d-%b-%y'))
  investment = myinvmt_df['Investment'].values
  dates= pd.to_datetime(dates)

  current = round(sum(df_portfolio_features['Close']*df_portfolio_features['Shares']),0) + reserve_amt
  investment_xirr = np.append(investment, current)
  cagr = round(xirr(pd.DataFrame({"dates": dates, "amounts": investment_xirr}))*100,2)

  investment = -sum(investment)
  invested = round(sum(df_portfolio_features['AvgCost']*df_portfolio_features['Shares']),0) + reserve_amt
  previous = round(sum(df_portfolio_features['Prev_Close']*df_portfolio_features['Shares']),0) + reserve_amt
  cy_invested = investment + py_booked_amt

  today_pnl_amount = current-previous
  today_pnl_percentage = round((current-previous)*100/previous,2)

  curr_pnl_amount = current-invested
  curr_pnl_percentage = round((curr_pnl_amount)*100/(cy_invested),2)

  cy_pnl_amount = cy_booked_amt + curr_pnl_amount
  cy_pnl_percentage = round((cy_pnl_amount)*100/cy_invested,2)

  overall_pnl_amount = total_booked_amt + curr_pnl_amount
  overall_pnl_percentage = round((overall_pnl_amount)*100/investment,2)

  estimate_st = round(sum(df_portfolio_features['FTT']*df_portfolio_features['Shares']),0)  + reserve_amt
  est_st_pnl_amount = estimate_st-current
  est_st_pnl_percentage = round((est_st_pnl_amount)*100/current,2)

  estimate_lt = round(sum(df_portfolio_features['LTT']*df_portfolio_features['Shares']),0)  + reserve_amt
  est_lt_pnl_amount = estimate_lt-current
  est_lt_pnl_percentage = round((est_lt_pnl_amount)*100/current,2)

  total_profit = round(sum(df_portfolio_features[df_portfolio_features['Current P/L%'] > 0]['Current']) - sum(df_portfolio_features[df_portfolio_features['Current P/L%'] > 0]['Investment']),0)
  total_loss = round(sum(df_portfolio_features[df_portfolio_features['Current P/L%'] < 0]['Current']) - sum(df_portfolio_features[df_portfolio_features['Current P/L%'] < 0]['Investment']),0)

  cy_booked_percentage = round((cy_booked_amt)*100/current,2)
  py_booked_percentage = round((py_booked_amt)*100/investment,2)
  total_booked_percentage = round((total_booked_amt)*100/investment,2)

  print('-------------------')
  print('Initial Investment: ', format_amt(investment))
  print('CY Investment: ', format_amt(cy_invested))
  print('Reserve: ', format_amt(reserve_amt))
  print('Current: ',  format_amt(current))
  print('-------------------')
  print('Today PnL: '+ '{} ({}%)'.format(format_amt(today_pnl_amount), today_pnl_percentage))
  print('Current PnL: '+ '{} ({}%)'.format(format_amt(curr_pnl_amount), curr_pnl_percentage))
  print('CY Booked + Current PnL: '+ '{} ({}%)'.format(format_amt(cy_pnl_amount), cy_pnl_percentage))
  print('-------------------')
  print('Total profit: ', format_amt(total_profit))
  print('Total loss: ', format_amt(total_loss))
  print('-------------------')
  print('Total Booked + Current PnL: '+ '{} ({}%)'.format(format_amt(overall_pnl_amount), overall_pnl_percentage))
  print('Total Booked PnL: '+ '{} ({}%)'.format(format_amt(total_booked_amt), total_booked_percentage))
  print('Curr Year Booked PnL: '+ '{} ({}%)'.format(format_amt(cy_booked_amt), cy_booked_percentage))
  print('Prev Year Booked PnL: '+ '{} ({}%)'.format(format_amt(py_booked_amt), py_booked_percentage))
  print('===================')
  print('Est FTT: ',  format_amt(estimate_st))
  print('Est FTT PnL: '+ '{} ({}%)'.format(format_amt(est_st_pnl_amount), est_st_pnl_percentage))

  print('===================')
  print('Deployed: ', format_amt(investment))

  print('Current: ', format_amt(current))

  print('CAGR/XIRR %: '+'{}%'.format(cagr))

In [8]:
# get start and end date
start_date, end_date = get_start_end_date()

# get portfolio and prospects data
mypfs_df = get_mypfs_df()
mypps_df = get_mypps_df()
myinvmt_df = get_myinvmt_df()

# merge above datasets
mypf_df = pd.merge(mypfs_df, mypps_df, on="Symbol")

# seggregate dm and sv portfolio
dm_pf = mypf_df[mypf_df['InPortfolio'] == 'DM']
sv_pf = mypf_df[mypf_df['InPortfolio'] == 'SV']

# build portfolio stock dataframe
dm_stocks = get_stock_ids(dm_pf)
sv_stocks = get_stock_ids(sv_pf)
df_stocks = pd.concat([dm_pf,sv_pf], ignore_index = True)

# arrange common and diff stock features
common_cols = ['Symbol', 'Target', 'Criteria', 'Strategy', 'CumlRnk', 'LatestQtr', 'StarStock', 'Conviction', 'Category', 'InFolio', 'XIRR', 'MBQ']
diff_cols = ['Symbol', 'AvgCost', 'Shares']
df_stocks = arrange_features(df_stocks, common_cols, diff_cols)

# get common features
stock_ids = df_stocks['Symbol'].values
df_common_features = get_common_features(stock_ids, df_stocks)

df_common_features.reset_index(drop=True, inplace=True)
df_common_features.drop(['Date'], axis=1, inplace=True)
# get and print portfolio features
df_portfolio_features = get_portfolio_features(df_common_features)

print_portfolio_stats(df_portfolio_features, myinvmt_df)

df = df_portfolio_features
#plot_pie_chart(df, 'CapType', 'Current')
list_ox40n = list(df[df['MBQ'].str.contains('OX40N', na=False)]['Symbol'].values)

Run date time (IST): 2026-07-17 10:43:23
-------------------
qualified stocks: 92
with latest results: 31
still star stocks: 20
-------------------
Initial Investment:  1.40 C
CY Investment:  1.82 C
Reserve:  1.49 K
Current:  1.52 C
-------------------
Today PnL: -51.85 K (-0.34%)
Current PnL: -30.74 L (-16.86%)
CY Booked + Current PnL: -28.66 L (-15.72%)
-------------------
Total profit:  4.61 L
Total loss:  -35.35 L
-------------------
Total Booked + Current PnL: 14.21 L (10.18%)
Total Booked PnL: 44.95 L (32.22%)
Curr Year Booked PnL: 2.08 L (1.36%)
Prev Year Booked PnL: 42.87 L (30.73%)
===================
Est FTT:  2.55 C
Est FTT PnL: 1.02 C (67.21%)
===================
Deployed:  1.40 C
Current:  1.52 C
CAGR/XIRR %: 4.01%

In [9]:
# top 5 near their targets
cols = ['Symbol', 'Today P/L%', 'Current P/L%', 'FTT%', 'OTT%', 'FTT Amt', 'Current P/L', 'Current', 'FTT', 'Dev%_PE', 'RSI_14','Conviction', 'Spread%',  'CumlRnk', 'RRR Ind', 'CurrAlloc%', 'Gained%', 'Criteria', 'Strategy', 'Category']
df_tmp = df_portfolio_features[~df_portfolio_features['Symbol'].isin(['ENRIN','BLUSPRING','DIGITIDE'])]
df_tmp = df_tmp.sort_values(by = 'FTT Amt', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
49,JSWINFRA,-1.78,13.45,2.63,16.43,6617.0,29830.0,251604.0,342.00,-2.81,58.0,X-MC,17.75,61.0,4.51,1.65,42.65,X40N,NTT,REALTY
59,PIDILITIND,-0.05,11.12,6.52,18.37,10223.0,15690.0,156800.0,1670.26,-22.17,51.0,X-LC,8.26,5.0,1.53,1.03,23.12,X40,ATH,CHEMICALS
83,TTKPRESTIG,1.10,-12.03,13.78,0.09,12217.0,-12123.0,88654.0,770.00,105.76,74.0,M-SC,8.52,250.0,-0.99,0.58,57.86,OX40N,NTT,DURABLES
73,SONACOMS,2.07,20.67,14.93,38.69,18225.0,20912.0,122071.0,801.69,-4.40,78.0,M-MC,23.12,193.0,1.15,0.80,73.19,AR,ATH,AUTO
72,SIS,0.25,1.03,20.03,21.26,22468.0,1142.0,112174.0,528.00,2679.79,62.0,H-SC,25.09,168.0,0.05,0.74,66.79,OX40N,NTT,MISC

In [10]:
# top 5 today
df_tmp = df_portfolio_features.sort_values(by = 'Today P/L%', ascending=False)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
64,RELAXO,12.64,-46.51,184.75,52.31,143447.0,-67516.0,77644.0,1176.00,-43.08,62.0,X-SC,11.93,92.0,-0.47,0.51,73.60,X40N,NTT,FOOTWEAR
48,JIOFIN,4.05,-18.63,57.83,28.43,140381.0,-55579.0,242748.0,387.00,-19.90,57.0,X-LC,10.71,34.0,-0.40,1.59,9.42,XY24,BTT,FINANCE
14,CAMPUS,3.23,-21.15,69.03,33.28,91321.0,-35483.0,132292.0,393.00,-36.46,48.0,M-SC,8.34,218.0,-0.39,0.87,6.24,XY24,NTT,FOOTWEAR
33,HCLTECH,2.53,-21.79,53.80,20.28,101790.0,-52723.0,189201.0,1853.42,-17.70,61.0,X-LC,18.45,8.0,-0.52,1.24,17.71,X40,ATH,IT
73,SONACOMS,2.07,20.67,14.93,38.69,18225.0,20912.0,122071.0,801.69,-4.40,78.0,M-MC,23.12,193.0,1.15,0.80,73.19,AR,ATH,AUTO

In [11]:
# bottom 5 today
df_tmp = df_portfolio_features.sort_values(by = 'Today P/L%', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
0,5PAISA,-5.67,-29.80,60.84,12.90,93316.0,-65117.0,153379.0,593.00,125.96,55.0,H-SC,10.88,170.0,-0.70,1.01,48.01,OX40N,NTT,FINANCE
40,ICICIPRULI,-4.36,-16.89,56.75,30.28,92919.0,-33271.0,163734.0,787.27,-39.26,51.0,X-MC,14.60,78.0,-0.36,1.07,9.09,X40,ATH,INSURANCE
21,DEN,-3.49,-47.09,168.53,42.07,75313.0,-39776.0,44688.0,75.00,58.03,43.0,M-SC,5.57,235.0,-0.53,0.29,21.54,AR,NTT,ENTERTAINMENT
85,VAIBHAVGBL,-3.25,-24.43,112.74,60.77,155721.0,-44651.0,138124.0,521.00,59.23,54.0,H-SC,5.86,160.0,-0.29,0.91,40.53,XR,NTT,JEWELLERY
55,MASFIN,-3.20,-4.10,26.77,21.57,25153.0,-4020.0,93960.0,397.04,-17.34,48.0,H-SC,0.86,167.0,-0.16,0.62,12.00,XR,ATH,FINANCE

In [12]:
# top 5 to exit based on CumlRnk
df_tmp = df_portfolio_features[~df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])]
df_tmp = df_tmp[(df_tmp['Current P/L%'] > -1) & (df_tmp['Current P/L%'] < 1)].sort_values(by = 'CumlRnk', ascending=False)
df_tmp[cols].head()

Empty DataFrame
Columns: [Symbol, Today P/L%, Current P/L%, FTT%, OTT%, FTT Amt, Current P/L, Current, FTT, Dev%_PE, RSI_14, Conviction, Spread%, CumlRnk, RRR Ind, CurrAlloc%, Gained%, Criteria, Strategy, Category]
Index: []

In [13]:
# OX40N stocks to exit
df_tmp = df_portfolio_features[(df_portfolio_features['Symbol'].isin(list_ox40n))].sort_values(by = 'Current P/L%', ascending=False)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
25,FINCABLES,-0.42,30.89,58.85,107.91,113725.0,45602.0,193246.0,1641.55,17.71,42.0,M-SC,24.90,220.0,0.40,1.27,45.39,OX40N,ATH,CABLES
72,SIS,0.25,1.03,20.03,21.26,22468.0,1142.0,112174.0,528.00,2679.79,62.0,H-SC,25.09,168.0,0.05,0.74,66.79,OX40N,NTT,MISC
83,TTKPRESTIG,1.10,-12.03,13.78,0.09,12217.0,-12123.0,88654.0,770.00,105.76,74.0,M-SC,8.52,250.0,-0.99,0.58,57.86,OX40N,NTT,DURABLES
16,CERA,-0.59,-20.62,56.07,23.89,78292.0,-36270.0,139633.0,9475.00,-23.39,45.0,H-SC,15.84,153.0,-0.46,0.92,35.74,OX40N,NTT,CERAMICS
43,INDIGOPNTS,-2.53,-24.91,33.21,0.02,43528.0,-43491.0,131068.0,1408.00,99.78,55.0,M-SC,3.50,222.0,-1.00,0.86,48.71,OX40N,NTT,PAINTS

In [14]:
# top 5 to book for rotation
df_tmp = df_portfolio_features[(df_portfolio_features['Current P/L%'] > 20) ].sort_values(by = 'CumlRnk', ascending=False)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
25,FINCABLES,-0.42,30.89,58.85,107.91,113725.0,45602.0,193246.0,1641.55,17.71,42.0,M-SC,24.90,220.0,0.40,1.27,45.39,OX40N,ATH,CABLES
73,SONACOMS,2.07,20.67,14.93,38.69,18225.0,20912.0,122071.0,801.69,-4.40,78.0,M-MC,23.12,193.0,1.15,0.80,73.19,AR,ATH,AUTO
68,SATIN,-2.87,43.25,6.00,51.83,23746.0,119480.0,395764.0,274.00,28.78,57.0,H-SC,44.09,159.0,5.03,2.60,92.80,XY24,NTT,FINANCE
91,ZYDUSLIFE,-0.94,20.54,12.52,35.63,31629.0,43051.0,252625.0,1286.17,4.95,59.0,H-MC,16.90,120.0,1.36,1.66,32.83,AR,ATH,PHARMA

In [15]:
# top 5 to monitor for exit
df_tmp = df_portfolio_features[~df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])]
df_tmp = df_tmp[(df_tmp['Current P/L%'] > 0) ].sort_values(by = 'Dev%_PE', ascending=False)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
72,SIS,0.25,1.03,20.03,21.26,22468.0,1142.0,112174.0,528.0,2679.79,62.0,H-SC,25.09,168.0,0.05,0.74,66.79,OX40N,NTT,MISC
9,BANDHANBNK,0.25,3.41,86.08,92.42,247950.0,9487.0,288046.0,400.0,147.13,58.0,H-SC,20.15,174.0,0.04,1.89,58.68,XY24,NTT,BANKS
75,SURYODAY,-2.54,2.14,20.46,23.03,37421.0,3825.0,182896.0,216.0,99.56,53.0,H-SC,21.87,166.0,0.10,1.20,55.25,XR,NTT,BANKS
74,STARHEALTH,-0.68,14.46,28.66,47.26,92221.0,40653.0,321776.0,761.0,80.57,62.0,H-SC,19.41,173.0,0.44,2.11,39.64,XY24,NTT,INSURANCE
68,SATIN,-2.87,43.25,6.00,51.83,23746.0,119480.0,395764.0,274.0,28.78,57.0,H-SC,44.09,159.0,5.03,2.60,92.80,XY24,NTT,FINANCE

In [16]:
# top 5 to book for rotation from weak conviction
df_tmp = df_portfolio_features[~df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])]
df_tmp = df_tmp[~df_tmp['Criteria'].isin(['XY25','XY24','X40', 'X40N'])].sort_values(by = 'RRR Ind', ascending=False)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
91,ZYDUSLIFE,-0.94,20.54,12.52,35.63,31629.0,43051.0,252625.0,1286.17,4.95,59.0,H-MC,16.90,120.0,1.36,1.66,32.83,AR,ATH,PHARMA
73,SONACOMS,2.07,20.67,14.93,38.69,18225.0,20912.0,122071.0,801.69,-4.40,78.0,M-MC,23.12,193.0,1.15,0.80,73.19,AR,ATH,AUTO
25,FINCABLES,-0.42,30.89,58.85,107.91,113725.0,45602.0,193246.0,1641.55,17.71,42.0,M-SC,24.90,220.0,0.40,1.27,45.39,OX40N,ATH,CABLES
75,SURYODAY,-2.54,2.14,20.46,23.03,37421.0,3825.0,182896.0,216.00,99.56,53.0,H-SC,21.87,166.0,0.10,1.20,55.25,XR,NTT,BANKS
72,SIS,0.25,1.03,20.03,21.26,22468.0,1142.0,112174.0,528.00,2679.79,62.0,H-SC,25.09,168.0,0.05,0.74,66.79,OX40N,NTT,MISC

In [17]:
# top 5 to accumulate based on lowest RSI_14
df_tmp = df_portfolio_features[df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])].sort_values(by = 'RSI_14', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
39,ICICIGI,-1.21,-15.02,39.91,18.89,67865.0,-30064.0,170045.0,2244.41,-28.41,30.0,X-MC,4.65,66.0,-0.44,1.12,0.00,X40,ATH,INSURANCE
87,VBL,-0.32,-6.06,44.10,35.37,130846.0,-19140.0,296702.0,670.16,-17.05,31.0,X-LC,8.00,13.0,-0.15,1.95,21.95,X40N,ATH,FMCG
58,PGHH,-0.36,-34.13,100.42,32.01,141231.0,-72880.0,140640.0,17616.87,-55.45,37.0,X-MC,20.23,57.0,-0.52,0.92,0.00,X40,ATH,FMCG
23,DMART,0.07,-4.96,36.37,29.60,86273.0,-12390.0,237210.0,5391.45,-19.87,37.0,X-LC,2.27,14.0,-0.14,1.56,8.42,X40N,ATH,FMCG
81,TMPV,0.33,-24.22,80.23,36.58,216339.0,-86192.0,269649.0,600.00,-84.72,38.0,X-LC,8.14,4.0,-0.40,1.77,13.32,XY24,NTT,AUTO

In [18]:
# top 5 to accumulate based on Spread and CumlRnk
df_tmp = df_portfolio_features[df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])]
df_tmp = df_tmp[(df_tmp['CumlRnk'] < 100)].sort_values(by = 'Spread%', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
23,DMART,0.07,-4.96,36.37,29.60,86273.0,-12390.0,237210.0,5391.45,-19.87,37.0,X-LC,2.27,14.0,-0.14,1.56,8.42,X40N,ATH,FMCG
11,BERGEPAINT,1.54,-7.99,36.20,25.32,85846.0,-20605.0,237144.0,680.00,-13.04,45.0,X-MC,2.53,68.0,-0.24,1.56,23.42,XY24,NTT,PAINTS
19,COLPAL,0.10,-23.94,83.89,39.86,168040.0,-63055.0,200310.0,3683.41,-7.87,45.0,X-MC,2.99,62.0,-0.38,1.31,13.31,XY25,ATH,FMCG
17,CIPLA,-0.83,14.77,16.26,33.43,28582.0,22621.0,175782.0,1648.14,-11.14,48.0,X-LC,3.09,18.0,0.79,1.15,20.00,X40N,ATH,PHARMA
8,BAJAJHLDNG,-0.07,-5.90,35.63,27.63,63745.0,-11217.0,178908.0,14274.15,-13.24,50.0,X-LC,3.86,28.0,-0.18,1.17,21.82,X40,ATH,FINANCE

In [19]:
# top 5 to accumulate based on lowest Gained%
df_tmp = df_portfolio_features[df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])].sort_values(by = 'Gained%', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
39,ICICIGI,-1.21,-15.02,39.91,18.89,67865.0,-30064.0,170045.0,2244.41,-28.41,30.0,X-MC,4.65,66.0,-0.44,1.12,0.00,X40,ATH,INSURANCE
58,PGHH,-0.36,-34.13,100.42,32.01,141231.0,-72880.0,140640.0,17616.87,-55.45,37.0,X-MC,20.23,57.0,-0.52,0.92,0.00,X40,ATH,FMCG
47,ITC,0.32,-26.18,61.28,19.06,153877.0,-89062.0,251104.0,452.00,-59.56,41.0,X-LC,12.66,1.0,-0.58,1.65,1.71,X40,NTT,FMCG
20,DABUR,-1.60,-17.03,73.19,43.70,150650.0,-42234.0,205834.0,735.00,-24.64,42.0,X-MC,9.04,70.0,-0.28,1.35,3.40,XY24,BTT,FMCG
32,HAVELLS,-0.37,-24.90,74.99,31.42,184723.0,-81661.0,246330.0,2052.62,-29.37,46.0,X-MC,10.93,63.0,-0.44,1.62,3.90,X40,ATH,ELECTRICAL

In [20]:
# top 5 to accumulate based on lowest CurrAlloc%
df_tmp = df_portfolio_features[df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])].sort_values(by = 'CurrAlloc%', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
10,BATAINDIA,1.31,-55.60,204.52,35.20,116840.0,-71541.0,57129.0,2096.00,-25.05,49.0,X-SC,18.60,91.0,-0.61,0.37,13.30,X40,NTT,FOOTWEAR
64,RELAXO,12.64,-46.51,184.75,52.31,143447.0,-67516.0,77644.0,1176.00,-43.08,62.0,X-SC,11.93,92.0,-0.47,0.51,73.60,X40N,NTT,FOOTWEAR
60,QUESS,-0.70,19.47,45.55,73.90,58117.0,20796.0,127589.0,424.00,-35.54,68.0,X-SC,28.58,80.0,0.36,0.84,73.93,XY24,NTT,MISC
35,HDFCLIFE,1.25,-6.01,41.19,32.71,57996.0,-8998.0,140802.0,811.41,-26.65,51.0,X-LC,14.99,31.0,-0.16,0.92,5.78,X40,ATH,INSURANCE
58,PGHH,-0.36,-34.13,100.42,32.01,141231.0,-72880.0,140640.0,17616.87,-55.45,37.0,X-MC,20.23,57.0,-0.52,0.92,0.00,X40,ATH,FMCG

In [21]:
# top 5 to accumulate based on CumlRnk
df_tmp = df_portfolio_features.sort_values(by = 'CumlRnk', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
47,ITC,0.32,-26.18,61.28,19.06,153877.0,-89062.0,251104.0,452.00,-59.56,41.0,X-LC,12.66,1.0,-0.58,1.65,1.71,X40,NTT,FMCG
79,TCS,1.34,-34.52,89.68,24.20,272030.0,-159939.0,303334.0,4230.71,-44.61,61.0,X-LC,20.95,2.0,-0.59,1.99,13.12,X40,ATH,IT
45,INFY,1.53,-25.19,79.44,34.24,185959.0,-78801.0,234087.0,1972.00,-41.22,53.0,X-LC,21.33,3.0,-0.42,1.54,11.54,X40,NTT,IT
81,TMPV,0.33,-24.22,80.23,36.58,216339.0,-86192.0,269649.0,600.00,-84.72,38.0,X-LC,8.14,4.0,-0.40,1.77,13.32,XY24,NTT,AUTO
59,PIDILITIND,-0.05,11.12,6.52,18.37,10223.0,15690.0,156800.0,1670.26,-22.17,51.0,X-LC,8.26,5.0,1.53,1.03,23.12,X40,ATH,CHEMICALS

In [22]:
# top 5 for average up
df_tmp = df_portfolio_features[(df_portfolio_features['Dev%_200'] > 5)].sort_values(by = 'CurrAlloc%', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
44,INDUSINDBK,1.61,-24.25,75.44,32.89,44119.0,-18724.0,58482.0,1800.00,-375.21,67.0,L-MC,10.87,258.0,-0.42,0.38,44.18,XR,NTT,BANKS
64,RELAXO,12.64,-46.51,184.75,52.31,143447.0,-67516.0,77644.0,1176.00,-43.08,62.0,X-SC,11.93,92.0,-0.47,0.51,73.60,X40N,NTT,FOOTWEAR
3,ALKYLAMINE,-3.17,-21.61,145.63,92.54,115254.0,-21821.0,79142.0,4520.85,-16.07,52.0,H-SC,11.43,142.0,-0.19,0.52,50.28,SR,ATH,CHEMICALS
83,TTKPRESTIG,1.10,-12.03,13.78,0.09,12217.0,-12123.0,88654.0,770.00,105.76,74.0,M-SC,8.52,250.0,-0.99,0.58,57.86,OX40N,NTT,DURABLES
72,SIS,0.25,1.03,20.03,21.26,22468.0,1142.0,112174.0,528.00,2679.79,62.0,H-SC,25.09,168.0,0.05,0.74,66.79,OX40N,NTT,MISC

In [23]:
# top 5 RSP
df_tmp = df_portfolio_features.sort_values(by = 'RSP', ascending=False)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
83,TTKPRESTIG,1.10,-12.03,13.78,0.09,12217.0,-12123.0,88654.0,770.00,105.76,74.0,M-SC,8.52,250.0,-0.99,0.58,57.86,OX40N,NTT,DURABLES
60,QUESS,-0.70,19.47,45.55,73.90,58117.0,20796.0,127589.0,424.00,-35.54,68.0,X-SC,28.58,80.0,0.36,0.84,73.93,XY24,NTT,MISC
73,SONACOMS,2.07,20.67,14.93,38.69,18225.0,20912.0,122071.0,801.69,-4.40,78.0,M-MC,23.12,193.0,1.15,0.80,73.19,AR,ATH,AUTO
0,5PAISA,-5.67,-29.80,60.84,12.90,93316.0,-65117.0,153379.0,593.00,125.96,55.0,H-SC,10.88,170.0,-0.70,1.01,48.01,OX40N,NTT,FINANCE
64,RELAXO,12.64,-46.51,184.75,52.31,143447.0,-67516.0,77644.0,1176.00,-43.08,62.0,X-SC,11.93,92.0,-0.47,0.51,73.60,X40N,NTT,FOOTWEAR

In [24]:
# Top N allocation
df_tmp = df_portfolio_features.sort_values(by = 'CurrAlloc%', ascending=False)
top_n_values = [10, 25, 50]

sum_df = pd.DataFrame({
    'Top_N': top_n_values,
    'Sum_Alloc%': [df_tmp['CurrAlloc%'].head(n).sum() for n in top_n_values]
})

sum_df

   Top_N  Sum_Alloc%
0     10       19.40
1     25       42.68
2     50       72.71

In [25]:
# market-cap-wise allocation
df_tmp = df_portfolio_features[cols]
df_tmp.groupby(df_tmp['Conviction'].str[-2:])['CurrAlloc%'].sum().sort_values(ascending=False)

Conviction
SC    43.70
LC    30.24
MC    26.07
Name: CurrAlloc%, dtype: float64

In [26]:
# criteria-wise allocation
df_portfolio_features.groupby('Criteria')['CurrAlloc%'].sum().sort_values(ascending=False)

Criteria
XY24     27.80
X40      24.63
X40N     17.37
XR        8.80
OX40N     7.06
AR        7.01
XY25      6.45
SR        0.89
Name: CurrAlloc%, dtype: float64

In [27]:
# conviction-wise allocation
df_portfolio_features.groupby('Conviction')['CurrAlloc%'].sum().sort_values(ascending=False)

Conviction
X-LC    28.24
H-SC    23.11
X-MC    20.89
X-SC    10.04
M-SC    10.00
H-MC     2.73
M-MC     2.07
H-LC     1.20
M-LC     0.80
L-SC     0.55
L-MC     0.38
Name: CurrAlloc%, dtype: float64

In [28]:
# sector-wise stats
df_tmp = df_portfolio_features.groupby('Category')[['CurrAlloc%', 'Current', 'Current P/L', 'FTT Amt']].sum().sort_values(by=['Current', 'Current P/L'], ascending=False)
df_tmp['Current P/L%'] = round(df_tmp['Current P/L'] * 100 / df_tmp['Current'], 2)
df_tmp['FTT%'] = round(df_tmp['FTT Amt'] * 100 / df_tmp['Current'], 2)
cols = ['CurrAlloc%', 'Current P/L%', 'FTT%']
df_tmp[cols].sort_values(by=['CurrAlloc%'], ascending=False)

               CurrAlloc%  Current P/L%    FTT%
Category
FMCG                14.11        -23.10   66.28
FINANCE             11.26         -7.43   53.97
IT                  10.23        -44.51  116.03
MISC                 7.18        -22.64   75.26
AUTO                 6.64         -7.99   48.26
BANKS                5.91         -0.79   47.36
PAINTS               5.41        -19.52   39.90
INSURANCE            5.22         -3.98   39.05
PHARMA               5.19          6.37   22.62
ELECTRICAL           4.10        -13.06   52.96
CHEMICALS            2.16        -23.52   96.80
HEALTHCARE           2.07        -13.20   42.74
AC                   1.84        -14.26   45.23
APPARELS             1.83          3.98   28.27
FOOTWEAR             1.75        -65.35  131.66
REALTY               1.65         11.86    2.63
DURABLES             1.65        -53.90   91.35
BREWERIES            1.55          0.76   19.85
TRAVEL               1.51        -94.79  192.32
CERAMICS             1.41        -43.55   87.16
ENGINEERING          1.29        -22.99   79.24
CABLES               1.27         23.60   58.85
REFINERIES           1.12        -17.96   47.80
CEMENT               1.07        -64.23  187.10
JEWELLERY            1.06        -98.83  167.92
ENTERTAINMENT        0.72        -75.48  180.14
TEXTILES             0.41        -48.98   91.46
HOTELS               0.40        -85.68  151.18

In [29]:
# money to be made criteria-wise
df_portfolio_features.groupby('Criteria')['FTT Amt'].agg(['sum', 'count']).sort_values(by='sum', ascending=False)

                sum  count
Criteria
XY24      3360827.0     21
X40       1914565.0     19
XR        1337491.0     13
AR        1106418.0      9
X40N      1071539.0     13
OX40N      719148.0     10
XY25       452283.0      5
SR         282295.0      2

In [30]:
# money to be made conviction-wise
df_portfolio_features.groupby('Conviction')['FTT Amt'].agg(['sum', 'count']).sort_values(by='sum', ascending=False)

                  sum  count
Conviction
H-SC        3254674.0     24
X-LC        1967746.0     21
X-MC        1532175.0     15
M-SC        1395704.0     14
X-SC        1271645.0      9
H-MC         282229.0      2
L-SC         206931.0      2
M-LC         169957.0      1
M-MC          69396.0      2
H-LC          49990.0      1
L-MC          44119.0      1

In [31]:
# money to be made criteria and conviction-wise
df_portfolio_features.groupby(['Conviction', 'Criteria'])['FTT Amt'].agg(['sum', 'count']).sort_values(by='sum', ascending=False)

                           sum  count
Conviction Criteria
X-LC       X40       1018136.0     10
H-SC       XY24       941376.0      6
           AR         931261.0      5
M-SC       XY24       823392.0      6
H-SC       XR         798010.0      7
X-SC       XY24       752243.0      4
X-MC       X40        684516.0      7
X-LC       X40N       393848.0      6
X-MC       X40N       370202.0      4
X-LC       XY24       356720.0      2
X-SC       X40N       307489.0      3
M-SC       OX40N      302935.0      5
H-SC       OX40N      301732.0      4
           SR         282295.0      2
H-MC       XY24       250600.0      1
X-MC       XY25       240961.0      2
           XY24       236496.0      2
X-SC       X40        211913.0      2
M-SC       XR         194064.0      2
M-LC       XR         169957.0      1
X-LC       XY25       160151.0      2
L-SC       OX40N      114481.0      1
           XR          92450.0      1
M-SC       AR          75313.0      1
M-MC       XY25        51171.0      1
H-LC       AR          49990.0      1
L-MC       XR          44119.0      1
X-LC       XR          38891.0      1
H-MC       AR          31629.0      1
M-MC       AR          18225.0      1

In [32]:
# notebook execution time

end_time = time.time()
execution_time = round(end_time - start_time, 0)
print(f"Notebook execution time: {execution_time} seconds")

Notebook execution time: 28.0 seconds