<a href="https://colab.research.google.com/github/ankit-rathi/Quantvesting_v2/blob/main/myStocks_Portfolio_Analysis.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
'''
!pip install pandas==2.2.2 -qq
!pip install pyxirr -qq
!pip install ta -qq
!pip install yfinance==0.2.59 -qq
'''

'\n!pip install pandas==2.2.2 -qq\n!pip install pyxirr -qq\n!pip install ta -qq\n!pip install yfinance==0.2.59 -qq\n'

In [2]:
# import libraries

import numpy as np
import pandas as pd
import datetime
import warnings
warnings.filterwarnings('ignore')
import yfinance as yfin
import ta
import matplotlib.pyplot as plt
import requests

In [3]:
# notebook start time
import time
import datetime
import pytz

start_time = time.time()

# function to print date timestamp
def print_date_time():
  tz_NY = pytz.timezone('Asia/Kolkata')
  datetime_NY = datetime.datetime.now(tz_NY)
  print("Run date time (IST):", datetime_NY.strftime("%Y-%m-%d %H:%M:%S"))

In [4]:
# function to get booked and reserved amount
def get_amt():
  # fetch the JSON data from the URL
  url = "https://raw.githubusercontent.com/ankit-rathi/Tradevesting_v1/main/data/myPortfolioAmts.json"
  response = requests.get(url)
  pf_amts = response.json()  # parse the JSON data

  # extract values from the JSON
  py_booked_amt_dm = pf_amts["py_booked_amt_dm"]
  py_booked_amt_sv = pf_amts["py_booked_amt_sv"]
  cy_booked_amt_dm = pf_amts["cy_booked_amt_dm"]
  cy_booked_amt_sv = pf_amts["cy_booked_amt_sv"]
  reserve_amt_dm = pf_amts["reserve_amt_dm"]
  reserve_amt_sv = pf_amts["reserve_amt_sv"]

  # perform calculations
  py_booked_amt = py_booked_amt_dm + py_booked_amt_sv
  cy_booked_amt = cy_booked_amt_dm + cy_booked_amt_sv
  reserve_amt = reserve_amt_dm + reserve_amt_sv
  total_booked_amt = py_booked_amt + cy_booked_amt

  return total_booked_amt, reserve_amt, cy_booked_amt, py_booked_amt

gen_output = 0

In [5]:
# function to format the amount
def format_amt(number):
    abs_number = abs(number)

    if abs_number >= 1_00_00_000:  # Crores
        formatted_amt = f"{number / 1_00_00_000:.2f} C"
    elif abs_number >= 1_00_000:  # Lakhs
        formatted_amt = f"{number / 1_00_000:.2f} L"
    elif abs_number >= 1_000:  # Thousands
        formatted_amt = f"{number / 1_000:.2f} K"
    else:
        formatted_amt = f"{number:.2f}"

    return formatted_amt

# function to set start and end date
def get_start_end_date():
  start_date = (datetime.date.today() + datetime.timedelta(days=-365)).strftime('%Y-%m-%d')
  end_date = (datetime.date.today() + datetime.timedelta(days=1)).strftime('%Y-%m-%d')
  return start_date, end_date

# function to fetch my portfolio csv
def get_mypfs_df():
  mypfs_df = pd.read_csv('https://raw.githubusercontent.com/ankit-rathi/Tradevesting_v1/main/data/myPortfolioStocks.csv')
  return mypfs_df

# function to fetch my prospects csv
def get_mypps_df():
  mypps_df = pd.read_csv('https://raw.githubusercontent.com/ankit-rathi/Tradevesting_v1/main/data/myProspectsScrips.csv')
  return mypps_df

# function to fetch screener data
def get_myscreen_df():
  myscreen_df = pd.read_csv('https://raw.githubusercontent.com/ankit-rathi/Tradevesting_v1/main/data/myScreenerDB.csv')
  return myscreen_df

# function to fetch momentum data
def get_myinvmt_df():
  myinvmt_df = pd.read_csv('https://raw.githubusercontent.com/ankit-rathi/Tradevesting_v1/main/data/myInvestments.csv')
  return myinvmt_df

# function to get the stock ids
def get_stock_ids(df_pf):
  stock_n100 = df_pf['Symbol'].unique()

  exclude = ['CADILAHC','MMTC', 'MASFIN']

  stock_ids = df_pf[~df_pf['Symbol'].isin(exclude) ]['Symbol'].unique()

  #mypf = mypf[mypf.Forecast.notnull()]
  #stock_ids = mypf['Symbol'].unique()

  #stock_ids.sort()
  return stock_ids

# get features from screener data
def get_screener_features():
  myscreen_df = get_myscreen_df()
  cols = ['Symbol', 'EPS', 'MedPE', 'ROCE%', 'ROE%', 'CapType']
  return myscreen_df[cols]

# get relative strength
def get_relative_strength(stock_list):

    # Dictionary to store stock tickers and their corresponding percentage price change
    stock_changes = {}

    # Loop through each stock and fetch its price data
    for stock in stock_list:
        try:
            # Download the stock data for the given date range
            stock_data = yfin.Ticker(stock + '.NS').history(period='1mo', interval='1d')[map(str.title, ['open', 'close', 'low', 'high', 'volume'])]

            # Calculate the percentage change for the stock
            if len(stock_data) > 0:
                start_price = stock_data['Close'].iloc[0]
                end_price = stock_data['Close'].iloc[-1]
                percent_change = round(((end_price - start_price) / start_price) * 100, 2)
                stock_changes[stock] = percent_change
            else:
                stock_changes[stock] = np.nan  # If no data is available, set to NaN

        except Exception as e:
            print(f"Error fetching data for {stock}: {e}")
            stock_changes[stock] = np.nan

    # Create a DataFrame with stock tickers and their percentage changes
    df = pd.DataFrame(list(stock_changes.items()), columns=['Symbol', 'Percent_Change'])

    # Drop any stocks with missing data (NaN values)
    df = df.dropna()

    # Calculate the percentile rank based on percentage change
    df['RSP'] = round(df['Percent_Change'].rank(pct=True) * 100, 2)
    cols = ['Symbol', 'RSP']
    df = df[cols]
    # Sort by percentile rank (optional)
    df = df.sort_values(by='RSP', ascending=False).reset_index(drop=True)

    return df

In [6]:
# function to get stock technicals
def stock_prec_dev(stock_symbol):
    #stock_symbol = 'ULTRACEMCO.NS'
    short_window = 20
    mid_window = 50
    long_window = 200
    moving_avg = 'SMA'

    start = datetime.datetime(*map(int, start_date.split('-')))
    end = datetime.datetime(*map(int, end_date.split('-')))

    stock_df = yfin.Ticker(stock_symbol + '.NS').history(period='max', interval='1d')[map(str.title, ['open', 'close', 'low', 'high', 'volume'])]

    stock_df['Max'] = round(max(stock_df['Close']),2)
    stock_df = stock_df[(stock_df.index <= end_date) & (stock_df.index >= start_date)]
    stock_df['200_SMA'] = round(stock_df['Close'].rolling(window = 200, min_periods = 1).mean(),0)
    stock_df['Dev%_200'] = round((stock_df['Close'] - stock_df['200_SMA'])*100/stock_df['200_SMA'],2)
    stock_df.dropna(axis = 0, inplace = True) # remove any null rows

    stock_df['20_SMA'] = stock_df['Close'].rolling(window=20).mean()
    stock_df['50_SMA'] = stock_df['Close'].rolling(window=50).mean()
    stock_df['Symbol'] = stock_symbol

    stock_df['Close'] = round(stock_df['Close'],2)
    stock_df['Min'] = round(min(stock_df['Close']),2)
    stock_df['RSI_14'] = ta.momentum.RSIIndicator(close=stock_df['Close'], window=14).rsi()
    stock_df['RSI_14'] = round(stock_df['RSI_14'],0)
    stock_df['Prev_Close'] = stock_df['Close'].shift(1)
    stock_df.drop(['Open', 'Low', 'High', 'Volume'], axis=1, inplace=True)
    stock_df = stock_df.tail(1)

    max_SMA = max(stock_df['20_SMA'].item(), stock_df['50_SMA'].item(), stock_df['200_SMA'].item())
    min_SMA = min(stock_df['20_SMA'].item(), stock_df['50_SMA'].item(), stock_df['200_SMA'].item())
    ABS_Spread = max_SMA - min_SMA
    stock_df['Spread%'] = round((ABS_Spread / stock_df['200_SMA'].item()) * 100,2)

    return stock_df

# function to compute stock attributes
def get_common_features(stock_ids, df_mypf):

  df_prec_dev = pd.DataFrame()
  df_tmp = get_screener_features()
  df_rs = get_relative_strength(stock_ids)

  for stock_id in stock_ids:
      tmp = stock_prec_dev(stock_id)
      tmp = tmp.reset_index()
      df_prec_dev = pd.concat([df_prec_dev, tmp], ignore_index = True)
  df_prec_dev = pd.merge(df_prec_dev, df_mypf, on= 'Symbol')
  df_prec_dev = pd.merge(df_prec_dev, df_tmp, on= 'Symbol', how='left')
  df_prec_dev = pd.merge(df_prec_dev, df_rs, on= 'Symbol', how='left')
  #print(df_prec_dev.columns)
  df_prec_dev['Curr_PE'] = round(df_prec_dev['Close']/df_prec_dev['EPS'],1)
  df_prec_dev['Dev%_PE'] = round((df_prec_dev['Curr_PE'] - df_prec_dev['MedPE'])*100/df_prec_dev['MedPE'],2)
  df_prec_dev['Conviction'] = df_prec_dev['Conviction'] + '-' + df_prec_dev['CapType']
  return df_prec_dev

# function to arrange stock features
def arrange_features(df_stocks, common_cols, diff_cols):
  df_stocks_common = df_stocks[common_cols].drop_duplicates()
  df_stocks_diff = df_stocks[diff_cols]
  df_stocks_diff['Investment'] = df_stocks_diff['AvgCost'] * df_stocks_diff['Shares']
  df_stocks_diff = df_stocks_diff.groupby(['Symbol'])[['Shares', 'Investment']].aggregate(['sum']).reset_index()
  df_stocks_diff.columns = ['Symbol', 'Shares', 'Investment']
  df_stocks_diff['AvgCost'] = round(df_stocks_diff['Investment']/df_stocks_diff['Shares'],2)
  df_stocks = pd.merge(df_stocks_diff, df_stocks_common, on='Symbol')
  return df_stocks

# plot fact distribution across dimension
def plot_pie_chart(df, dimension, fact):
  # grouping the data by category and calculating the sum of fact for each type
  grouped_data = df.groupby(dimension)[fact].sum()

  # sorting the grouped data in descending order
  grouped_data = grouped_data.sort_values(ascending=False)

  # creating a pie chart
  grouped_data.plot.pie(autopct='%1.1f%%', startangle=90, figsize=(6, 6))

  # adding a title and displaying the plot
  plt.title(f'{dimension} {fact} Distribution')
  plt.ylabel('')  # To hide the y-label
  plt.show()

In [7]:
# function to get portfolio features

def get_portfolio_features(df_common_features):

  print_date_time()
  print('-------------------')

  #df_common_features["Target"] = df_common_features["Target"].fillna(df_common_features["Max"])
  df_common_features['NTT'] = np.where(df_common_features['Strategy']== 'NTT', df_common_features["Target"], df_common_features['Max'])
  df_common_features['LTT'] = np.where(df_common_features['Strategy']== 'BTT', df_common_features["Target"], df_common_features['Max'])
  df_common_features['BOL'] = df_common_features['Min']

  tmp_df = df_common_features[df_common_features['Symbol'].isin(mypf_df[mypf_df['InPortfolio'] != 'NA'].Symbol.values)]
  print('qualified stocks: '+str(len(tmp_df['Symbol'].unique())))
  tmp_df1 = tmp_df[tmp_df['LatestQtr'] == 1]
  print('with latest results: '+str(len(tmp_df1['Symbol'].unique())))
  tmp_df1 = tmp_df1[tmp_df1['StarStock'] == 1]
  print('still star stocks: '+str(len(tmp_df1['Symbol'].unique())))
  tmp_df['Investment'] = tmp_df['AvgCost'] * tmp_df['Shares']
  tmp_df['Current'] = round(tmp_df['Close'] * tmp_df['Shares'],0)
  tmp_df['Previous'] = tmp_df['Prev_Close'] * tmp_df['Shares']
  tmp_df['EstimatedST'] = tmp_df['NTT'] * tmp_df['Shares']
  tmp_df['EstimatedLT'] = tmp_df['LTT'] * tmp_df['Shares']
  tmp_df['Current P/L'] = round((tmp_df['Current'] - tmp_df['Investment']),0)
  tmp_df['Today P/L%'] = round((tmp_df['Current'] - tmp_df['Previous'])*100/tmp_df['Previous'],2)
  tmp_df['Current P/L%'] = round((tmp_df['Current'] - tmp_df['Investment'])*100/tmp_df['Investment'],2)
  tmp_df['EstimatedST P/L%'] = round((tmp_df['EstimatedST'] - tmp_df['Investment'])*100/tmp_df['Investment'],2)
  tmp_df['EstimatedLT P/L%'] = round((tmp_df['EstimatedLT'] - tmp_df['Investment'])*100/tmp_df['Investment'],2)
  tmp_df['NTT%'] = round((tmp_df['NTT'] - tmp_df['Close'])*100/tmp_df['Close'],2)
  tmp_df['LTT%'] = round((tmp_df['LTT'] - tmp_df['Close'])*100/tmp_df['Close'],2)
  tmp_df['Gained%'] = round((tmp_df['Close'] - tmp_df['BOL'])*100/tmp_df['BOL'],2)
  investment = round(sum(tmp_df['AvgCost']*tmp_df['Shares']),0)
  current = round(sum(tmp_df['Close']*tmp_df['Shares']),0)
  tmp_df['InitAlloc%'] = round(tmp_df['Investment']*100/investment,2)
  tmp_df['CurrAlloc%'] = round(tmp_df['Current']*100/current,2)
  tmp_df['FTT'] = tmp_df['LTT']
  tmp_df.loc[tmp_df['Strategy'] == 'NTT', 'FTT'] = tmp_df['NTT']
  tmp_df['FTT%'] = tmp_df['LTT%']
  tmp_df.loc[tmp_df['Strategy'] == 'NTT', 'FTT%'] = tmp_df['NTT%']
  tmp_df['FTT Amt'] = round(tmp_df['FTT%'] * tmp_df['Current']/100,0)
  tmp_df['OTT%'] = round((tmp_df['FTT'] - tmp_df['AvgCost'])*100/tmp_df['AvgCost'],2)
  tmp_df['RRR Ind'] = round(tmp_df['Current P/L']/tmp_df['FTT Amt'],2)
  tmp_df['Risk Ind'] = round(tmp_df['Current P/L%']*tmp_df['CurrAlloc%'],0)

  return tmp_df

# function to print portfolio features
def print_portfolio_stats(df_portfolio_features, myinvmt_df):
  from pyxirr import xirr

  total_booked_amt, reserve_amt, cy_booked_amt, py_booked_amt = get_amt()

  dates = myinvmt_df['Date'].values
  dates = np.append(dates, datetime.date.today().strftime('%d-%b-%y'))
  investment = myinvmt_df['Investment'].values
  dates= pd.to_datetime(dates)

  current = round(sum(df_portfolio_features['Close']*df_portfolio_features['Shares']),0) + reserve_amt
  investment_xirr = np.append(investment, current)
  cagr = round(xirr(pd.DataFrame({"dates": dates, "amounts": investment_xirr}))*100,2)

  investment = -sum(investment)
  invested = round(sum(df_portfolio_features['AvgCost']*df_portfolio_features['Shares']),0) + reserve_amt
  previous = round(sum(df_portfolio_features['Prev_Close']*df_portfolio_features['Shares']),0) + reserve_amt
  cy_invested = investment + py_booked_amt

  today_pnl_amount = current-previous
  today_pnl_percentage = round((current-previous)*100/previous,2)

  curr_pnl_amount = current-invested
  curr_pnl_percentage = round((curr_pnl_amount)*100/(cy_invested),2)

  cy_pnl_amount = cy_booked_amt + curr_pnl_amount
  cy_pnl_percentage = round((cy_pnl_amount)*100/cy_invested,2)

  overall_pnl_amount = total_booked_amt + curr_pnl_amount
  overall_pnl_percentage = round((overall_pnl_amount)*100/investment,2)

  estimate_st = round(sum(df_portfolio_features['FTT']*df_portfolio_features['Shares']),0)  + reserve_amt
  est_st_pnl_amount = estimate_st-current
  est_st_pnl_percentage = round((est_st_pnl_amount)*100/current,2)

  estimate_lt = round(sum(df_portfolio_features['LTT']*df_portfolio_features['Shares']),0)  + reserve_amt
  est_lt_pnl_amount = estimate_lt-current
  est_lt_pnl_percentage = round((est_lt_pnl_amount)*100/current,2)

  total_profit = round(sum(df_portfolio_features[df_portfolio_features['Current P/L%'] > 0]['Current']) - sum(df_portfolio_features[df_portfolio_features['Current P/L%'] > 0]['Investment']),0)
  total_loss = round(sum(df_portfolio_features[df_portfolio_features['Current P/L%'] < 0]['Current']) - sum(df_portfolio_features[df_portfolio_features['Current P/L%'] < 0]['Investment']),0)

  cy_booked_percentage = round((cy_booked_amt)*100/current,2)
  py_booked_percentage = round((py_booked_amt)*100/investment,2)
  total_booked_percentage = round((total_booked_amt)*100/investment,2)

  print('-------------------')
  print('Initial Investment: ', format_amt(investment))
  print('CY Investment: ', format_amt(cy_invested))
  print('Reserve: ', format_amt(reserve_amt))
  print('Current: ',  format_amt(current))
  print('-------------------')
  print('Today PnL: '+ '{} ({}%)'.format(format_amt(today_pnl_amount), today_pnl_percentage))
  print('Current PnL: '+ '{} ({}%)'.format(format_amt(curr_pnl_amount), curr_pnl_percentage))
  print('CY Booked + Current PnL: '+ '{} ({}%)'.format(format_amt(cy_pnl_amount), cy_pnl_percentage))
  print('-------------------')
  print('Total profit: ', format_amt(total_profit))
  print('Total loss: ', format_amt(total_loss))
  print('-------------------')
  print('Total Booked + Current PnL: '+ '{} ({}%)'.format(format_amt(overall_pnl_amount), overall_pnl_percentage))
  print('Total Booked PnL: '+ '{} ({}%)'.format(format_amt(total_booked_amt), total_booked_percentage))
  print('Curr Year Booked PnL: '+ '{} ({}%)'.format(format_amt(cy_booked_amt), cy_booked_percentage))
  print('Prev Year Booked PnL: '+ '{} ({}%)'.format(format_amt(py_booked_amt), py_booked_percentage))
  print('===================')
  print('Est FTT: ',  format_amt(estimate_st))
  print('Est FTT PnL: '+ '{} ({}%)'.format(format_amt(est_st_pnl_amount), est_st_pnl_percentage))

  print('===================')
  print('Deployed: ', format_amt(investment))

  print('Current: ', format_amt(current))

  print('CAGR/XIRR %: '+'{}%'.format(cagr))

In [8]:
# get start and end date
start_date, end_date = get_start_end_date()

# get portfolio and prospects data
mypfs_df = get_mypfs_df()
mypps_df = get_mypps_df()
myinvmt_df = get_myinvmt_df()

# merge above datasets
mypf_df = pd.merge(mypfs_df, mypps_df, on="Symbol")

# seggregate dm and sv portfolio
dm_pf = mypf_df[mypf_df['InPortfolio'] == 'DM']
sv_pf = mypf_df[mypf_df['InPortfolio'] == 'SV']

# build portfolio stock dataframe
dm_stocks = get_stock_ids(dm_pf)
sv_stocks = get_stock_ids(sv_pf)
df_stocks = pd.concat([dm_pf,sv_pf], ignore_index = True)

# arrange common and diff stock features
common_cols = ['Symbol', 'Target', 'Criteria', 'Strategy', 'CumlRnk', 'LatestQtr', 'StarStock', 'Conviction', 'Category', 'InFolio', 'XIRR', 'MBQ']
diff_cols = ['Symbol', 'AvgCost', 'Shares']
df_stocks = arrange_features(df_stocks, common_cols, diff_cols)

# get common features
stock_ids = df_stocks['Symbol'].values
df_common_features = get_common_features(stock_ids, df_stocks)

df_common_features.reset_index(drop=True, inplace=True)
df_common_features.drop(['Date'], axis=1, inplace=True)
# get and print portfolio features
df_portfolio_features = get_portfolio_features(df_common_features)

print_portfolio_stats(df_portfolio_features, myinvmt_df)

df = df_portfolio_features
#plot_pie_chart(df, 'CapType', 'Current')
list_ox40n = list(df[df['MBQ'].str.contains('OX40N', na=False)]['Symbol'].values)

Run date time (IST): 2026-06-03 12:22:45
-------------------
qualified stocks: 92
with latest results: 31
still star stocks: 20
-------------------
Initial Investment:  1.40 C
CY Investment:  1.82 C
Reserve:  1.49 K
Current:  1.47 C
-------------------
Today PnL: -1.97 L (-1.32%)
Current PnL: -36.09 L (-19.79%)
CY Booked + Current PnL: -34.01 L (-18.65%)
-------------------
Total profit:  2.00 L
Total loss:  -38.10 L
-------------------
Total Booked + Current PnL: 8.86 L (6.35%)
Total Booked PnL: 44.95 L (32.22%)
Curr Year Booked PnL: 2.08 L (1.41%)
Prev Year Booked PnL: 42.87 L (30.73%)
===================
Est FTT:  2.55 C
Est FTT PnL: 1.08 C (73.5%)
===================
Deployed:  1.40 C
Current:  1.47 C
CAGR/XIRR %: 2.52%

In [9]:
# top 5 near their targets
cols = ['Symbol', 'Today P/L%', 'Current P/L%', 'FTT%', 'OTT%', 'FTT Amt', 'Current P/L', 'Current', 'FTT', 'Dev%_PE', 'RSI_14','Conviction', 'Spread%',  'CumlRnk', 'RRR Ind', 'CurrAlloc%', 'Gained%', 'Criteria', 'Strategy', 'Category']
df_tmp = df_portfolio_features[~df_portfolio_features['Symbol'].isin(['ENRIN','BLUSPRING','DIGITIDE'])]
df_tmp = df_tmp.sort_values(by = 'FTT Amt', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
59,PIDILITIND,0.44,3.54,14.32,18.37,20922.0,4990.0,146100.0,1670.26,-27.53,55.0,X-LC,4.51,5.0,0.24,0.99,14.71,X40,ATH,CHEMICALS
55,MASFIN,-0.84,-6.06,29.41,21.57,27069.0,-5940.0,92040.0,397.04,-19.15,42.0,H-SC,2.09,167.0,-0.22,0.63,9.71,XR,ATH,FINANCE
72,SIS,1.35,-3.99,26.30,21.26,28037.0,-4429.0,106603.0,528.00,2541.45,71.0,H-SC,18.47,168.0,-0.16,0.72,58.50,OX40N,NTT,MISC
51,KOTAKBANK,-0.83,0.44,20.57,21.11,28609.0,610.0,139083.0,453.24,-13.74,44.0,X-LC,7.26,12.0,0.02,0.95,6.37,X40,ATH,BANKS
83,TTKPRESTIG,-0.50,-30.26,43.52,0.09,30587.0,-30495.0,70282.0,770.00,63.07,56.0,M-SC,14.78,250.0,-1.00,0.48,25.15,OX40N,NTT,DURABLES

In [10]:
# top 5 today
df_tmp = df_portfolio_features.sort_values(by = 'Today P/L%', ascending=False)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
86,VALIANTORG,3.30,-38.56,183.44,74.15,184396.0,-63084.0,100521.0,838.00,-280.91,55.0,H-SC,7.21,145.0,-0.34,0.68,49.59,XR,NTT,CHEMICALS
23,DMART,3.06,0.51,28.95,29.60,72626.0,1266.0,250866.0,5391.45,-15.23,47.0,X-LC,3.49,14.0,0.02,1.71,14.67,X40N,ATH,FMCG
3,ALKYLAMINE,2.22,-22.56,150.05,93.63,117314.0,-22780.0,78183.0,4546.37,-17.07,63.0,H-SC,10.09,142.0,-0.19,0.53,47.63,SR,ATH,CHEMICALS
64,RELAXO,1.95,-56.66,251.41,52.31,158172.0,-82246.0,62914.0,1176.00,-53.83,66.0,X-SC,23.15,92.0,-0.52,0.43,40.67,X40N,NTT,FOOTWEAR
80,TITAGARH,1.68,-20.12,82.45,45.74,159497.0,-48730.0,193447.0,1548.00,6.51,62.0,H-SC,7.28,175.0,-0.31,1.32,47.60,XY24,NTT,ENGINEERING

In [11]:
# bottom 5 today
df_tmp = df_portfolio_features.sort_values(by = 'Today P/L%', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
79,TCS,-8.75,-34.46,90.53,24.88,274892.0,-159626.0,303647.0,4253.91,-44.61,42.0,X-LC,18.06,2.0,-0.58,2.06,0.76,X40,ATH,IT
13,BSOFT,-5.54,-40.95,155.36,50.79,129033.0,-57599.0,83054.0,831.70,-24.24,44.0,H-SC,13.81,172.0,-0.45,0.56,5.20,XR,ATH,IT
78,TATAELXSI,-5.15,-38.07,113.20,32.03,92418.0,-50194.0,81641.0,9161.00,-22.55,51.0,H-SC,15.19,158.0,-0.54,0.56,8.05,OX40N,NTT,IT
33,HCLTECH,-4.82,-23.20,58.20,21.51,108141.0,-56114.0,185810.0,1872.35,-19.35,46.0,X-LC,18.53,8.0,-0.52,1.26,5.29,X40,ATH,IT
85,VAIBHAVGBL,-4.28,-30.66,131.86,60.77,167107.0,-56044.0,126731.0,521.00,46.01,52.0,H-SC,5.34,160.0,-0.34,0.86,28.14,XR,NTT,JEWELLERY

In [12]:
# top 5 to exit based on CumlRnk
df_tmp = df_portfolio_features[~df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])]
df_tmp = df_tmp[(df_tmp['Current P/L%'] > -1) & (df_tmp['Current P/L%'] < 1)].sort_values(by = 'CumlRnk', ascending=False)
df_tmp[cols].head()

Empty DataFrame
Columns: [Symbol, Today P/L%, Current P/L%, FTT%, OTT%, FTT Amt, Current P/L, Current, FTT, Dev%_PE, RSI_14, Conviction, Spread%, CumlRnk, RRR Ind, CurrAlloc%, Gained%, Criteria, Strategy, Category]
Index: []

In [13]:
# OX40N stocks to exit
df_tmp = df_portfolio_features[(df_portfolio_features['Symbol'].isin(list_ox40n))].sort_values(by = 'Current P/L%', ascending=False)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
25,FINCABLES,-1.85,24.58,66.89,107.91,123033.0,36289.0,183933.0,1641.55,12.13,43.0,M-SC,27.24,220.0,0.29,1.25,38.38,OX40N,ATH,CABLES
72,SIS,1.35,-3.99,26.30,21.26,28037.0,-4429.0,106603.0,528.00,2541.45,71.0,H-SC,18.47,168.0,-0.16,0.72,58.50,OX40N,NTT,MISC
16,CERA,-1.03,-27.46,70.80,23.89,90335.0,-48311.0,127592.0,9475.00,-30.07,49.0,H-SC,6.89,153.0,-0.53,0.87,22.62,OX40N,NTT,CERAMICS
50,KANSAINER,-0.35,-28.50,58.69,13.47,113169.0,-76842.0,192825.0,340.00,-38.54,55.0,H-SC,10.90,162.0,-0.68,1.31,34.69,XY24,NTT,PAINTS
83,TTKPRESTIG,-0.50,-30.26,43.52,0.09,30587.0,-30495.0,70282.0,770.00,63.07,56.0,M-SC,14.78,250.0,-1.00,0.48,25.15,OX40N,NTT,DURABLES

In [14]:
# top 5 to book for rotation
df_tmp = df_portfolio_features[(df_portfolio_features['Current P/L%'] > 20) ].sort_values(by = 'CumlRnk', ascending=False)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
25,FINCABLES,-1.85,24.58,66.89,107.91,123033.0,36289.0,183933.0,1641.55,12.13,43.0,M-SC,27.24,220.0,0.29,1.25,38.38,OX40N,ATH,CABLES
68,SATIN,-1.81,25.75,20.74,51.83,72057.0,71146.0,347430.0,274.00,13.01,66.0,H-SC,39.31,159.0,0.99,2.36,69.25,XY24,NTT,FINANCE

In [15]:
# top 5 to monitor for exit
df_tmp = df_portfolio_features[~df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])]
df_tmp = df_tmp[(df_tmp['Current P/L%'] > 0) ].sort_values(by = 'Dev%_PE', ascending=False)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
74,STARHEALTH,-1.14,2.10,44.24,47.26,126975.0,5891.0,287014.0,761.00,61.10,60.0,H-SC,9.81,173.0,0.05,1.95,26.01,XY24,NTT,INSURANCE
68,SATIN,-1.81,25.75,20.74,51.83,72057.0,71146.0,347430.0,274.00,13.01,66.0,H-SC,39.31,159.0,0.99,2.36,69.25,XY24,NTT,FINANCE
25,FINCABLES,-1.85,24.58,66.89,107.91,123033.0,36289.0,183933.0,1641.55,12.13,43.0,M-SC,27.24,220.0,0.29,1.25,38.38,OX40N,ATH,CABLES
91,ZYDUSLIFE,-0.72,12.89,20.15,35.63,47671.0,27006.0,236580.0,1286.17,-1.80,66.0,H-MC,7.89,120.0,0.57,1.61,24.39,AR,ATH,PHARMA
73,SONACOMS,-1.68,3.98,33.77,39.09,35521.0,4025.0,105184.0,804.02,-17.63,55.0,M-MC,18.86,193.0,0.11,0.72,48.80,AR,ATH,AUTO

In [16]:
# top 5 to book for rotation from weak conviction
df_tmp = df_portfolio_features[~df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])]
df_tmp = df_tmp[~df_tmp['Criteria'].isin(['XY25','XY24','X40', 'X40N'])].sort_values(by = 'RRR Ind', ascending=False)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
91,ZYDUSLIFE,-0.72,12.89,20.15,35.63,47671.0,27006.0,236580.0,1286.17,-1.80,66.0,H-MC,7.89,120.0,0.57,1.61,24.39,AR,ATH,PHARMA
25,FINCABLES,-1.85,24.58,66.89,107.91,123033.0,36289.0,183933.0,1641.55,12.13,43.0,M-SC,27.24,220.0,0.29,1.25,38.38,OX40N,ATH,CABLES
73,SONACOMS,-1.68,3.98,33.77,39.09,35521.0,4025.0,105184.0,804.02,-17.63,55.0,M-MC,18.86,193.0,0.11,0.72,48.80,AR,ATH,AUTO
75,SURYODAY,1.27,-2.56,26.27,23.03,45836.0,-4590.0,174481.0,216.00,90.79,65.0,H-SC,19.89,166.0,-0.10,1.19,46.91,XR,NTT,BANKS
42,INDIAMART,0.28,-15.05,143.34,106.72,150186.0,-18560.0,104776.0,4810.62,-61.72,38.0,H-SC,11.14,140.0,-0.12,0.71,1.43,AR,ATH,MISC

In [17]:
# top 5 to accumulate based on lowest RSI_14
df_tmp = df_portfolio_features[df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])].sort_values(by = 'RSI_14', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
40,ICICIPRULI,-1.55,-21.41,66.33,30.73,102701.0,-42171.0,154834.0,790.00,-42.46,28.0,X-MC,12.96,78.0,-0.41,1.05,0.00,X40,ATH,INSURANCE
27,GLAXO,-0.72,-12.76,55.55,35.69,96573.0,-25436.0,173848.0,3380.16,-33.30,29.0,X-MC,7.18,56.0,-0.26,1.18,0.00,X40,ATH,PHARMA
47,ITC,-2.40,-27.18,63.50,19.06,157289.0,-92467.0,247699.0,452.00,-59.97,30.0,X-LC,14.50,1.0,-0.59,1.68,0.00,X40,NTT,FMCG
20,DABUR,-1.92,-18.40,76.11,43.70,154058.0,-45653.0,202415.0,735.00,-25.93,30.0,X-MC,9.80,70.0,-0.30,1.38,1.68,XY24,BTT,FMCG
36,HINDUNILVR,-0.31,-18.80,39.99,13.67,83471.0,-48333.0,208730.0,2922.00,-39.73,32.0,X-LC,6.92,9.0,-0.58,1.42,1.71,XY25,NTT,FMCG

In [18]:
# top 5 to accumulate based on Spread and CumlRnk
df_tmp = df_portfolio_features[df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])]
df_tmp = df_tmp[(df_tmp['CumlRnk'] < 100)].sort_values(by = 'Spread%', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
23,DMART,3.06,0.51,28.95,29.60,72626.0,1266.0,250866.0,5391.45,-15.23,47.0,X-LC,3.49,14.0,0.02,1.71,14.67,X40N,ATH,FMCG
57,PAGEIND,0.29,-2.26,36.67,33.59,96195.0,-6054.0,262325.0,51217.29,-29.91,52.0,X-MC,3.60,55.0,-0.06,1.78,24.58,X40,ATH,APPARELS
49,JSWINFRA,-2.47,-8.46,27.18,16.43,55181.0,-18755.0,203019.0,342.00,-21.44,46.0,X-MC,4.42,61.0,-0.34,1.38,14.76,X40N,NTT,REALTY
59,PIDILITIND,0.44,3.54,14.32,18.37,20922.0,4990.0,146100.0,1670.26,-27.53,55.0,X-LC,4.51,5.0,0.24,0.99,14.71,X40,ATH,CHEMICALS
19,COLPAL,0.42,-23.79,83.52,39.86,167633.0,-62655.0,200710.0,3683.41,-7.87,39.0,X-MC,4.65,62.0,-0.37,1.36,13.53,XY25,ATH,FMCG

In [19]:
# top 5 to accumulate based on lowest Gained%
df_tmp = df_portfolio_features[df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])].sort_values(by = 'Gained%', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
27,GLAXO,-0.72,-12.76,55.55,35.69,96573.0,-25436.0,173848.0,3380.16,-33.30,29.0,X-MC,7.18,56.0,-0.26,1.18,0.0,X40,ATH,PHARMA
47,ITC,-2.40,-27.18,63.50,19.06,157289.0,-92467.0,247699.0,452.00,-59.97,30.0,X-LC,14.50,1.0,-0.59,1.68,0.0,X40,NTT,FMCG
40,ICICIPRULI,-1.55,-21.41,66.33,30.73,102701.0,-42171.0,154834.0,790.00,-42.46,28.0,X-MC,12.96,78.0,-0.41,1.05,0.0,X40,ATH,INSURANCE
28,GODREJCP,-2.19,-12.55,50.33,31.47,65413.0,-18646.0,129968.0,1469.04,-8.01,34.0,X-LC,9.83,32.0,-0.29,0.88,0.0,X40N,ATH,FMCG
88,VOLTAS,-2.14,-5.04,52.90,45.20,96323.0,-9657.0,182085.0,1856.00,8.67,35.0,X-MC,8.06,79.0,-0.10,1.24,0.0,XY25,NTT,AC

In [20]:
# top 5 to accumulate based on lowest CurrAlloc%
df_tmp = df_portfolio_features[df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])].sort_values(by = 'CurrAlloc%', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
10,BATAINDIA,-1.66,-57.48,217.99,35.20,119260.0,-73961.0,54709.0,2096.00,-28.23,33.0,X-SC,25.11,91.0,-0.62,0.37,8.50,X40,NTT,FOOTWEAR
64,RELAXO,1.95,-56.66,251.41,52.31,158172.0,-82246.0,62914.0,1176.00,-53.83,66.0,X-SC,23.15,92.0,-0.52,0.43,40.67,X40N,NTT,FOOTWEAR
60,QUESS,-1.26,-13.79,101.72,73.90,93646.0,-14730.0,92063.0,424.00,-53.72,55.0,X-SC,7.95,80.0,-0.16,0.63,25.50,XY24,NTT,MISC
28,GODREJCP,-2.19,-12.55,50.33,31.47,65413.0,-18646.0,129968.0,1469.04,-8.01,34.0,X-LC,9.83,32.0,-0.29,0.88,0.00,X40N,ATH,FMCG
53,M&M,0.59,-2.14,26.07,23.38,35382.0,-2961.0,135720.0,3802.40,-17.22,42.0,X-LC,8.91,25.0,-0.08,0.92,2.90,X40N,ATH,AUTO

In [21]:
# top 5 to accumulate based on CumlRnk
df_tmp = df_portfolio_features.sort_values(by = 'CumlRnk', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
47,ITC,-2.40,-27.18,63.50,19.06,157289.0,-92467.0,247699.0,452.00,-59.97,30.0,X-LC,14.50,1.0,-0.59,1.68,0.00,X40,NTT,FMCG
79,TCS,-8.75,-34.46,90.53,24.88,274892.0,-159626.0,303647.0,4253.91,-44.61,42.0,X-LC,18.06,2.0,-0.58,2.06,0.76,X40,ATH,IT
45,INFY,-4.10,-17.04,61.81,34.24,160448.0,-53305.0,259583.0,1972.00,-34.69,55.0,X-LC,18.03,3.0,-0.33,1.77,11.30,X40,NTT,IT
81,TMPV,-0.31,-11.45,54.24,36.58,170905.0,-40751.0,315090.0,600.00,-81.44,64.0,X-LC,19.03,4.0,-0.24,2.14,31.33,XY24,NTT,AUTO
59,PIDILITIND,0.44,3.54,14.32,18.37,20922.0,4990.0,146100.0,1670.26,-27.53,55.0,X-LC,4.51,5.0,0.24,0.99,14.71,X40,ATH,CHEMICALS

In [22]:
# top 5 for average up
df_tmp = df_portfolio_features[(df_portfolio_features['Dev%_200'] > 5)].sort_values(by = 'CurrAlloc%', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
44,INDUSINDBK,-2.67,-34.43,102.68,32.89,51979.0,-26584.0,50622.0,1800.00,-338.10,45.0,L-MC,8.15,258.0,-0.51,0.34,24.60,XR,NTT,BANKS
3,ALKYLAMINE,2.22,-22.56,150.05,93.63,117314.0,-22780.0,78183.0,4546.37,-17.07,63.0,H-SC,10.09,142.0,-0.19,0.53,47.63,SR,ATH,CHEMICALS
18,COFFEEDAY,-0.15,-31.18,96.56,35.27,75456.0,-35405.0,78144.0,80.00,-47.69,89.0,L-SC,22.07,266.0,-0.47,0.53,92.71,XR,NTT,HOTELS
72,SIS,1.35,-3.99,26.30,21.26,28037.0,-4429.0,106603.0,528.00,2541.45,71.0,H-SC,18.47,168.0,-0.16,0.72,58.50,OX40N,NTT,MISC
73,SONACOMS,-1.68,3.98,33.77,39.09,35521.0,4025.0,105184.0,804.02,-17.63,55.0,M-MC,18.86,193.0,0.11,0.72,48.80,AR,ATH,AUTO

In [23]:
# top 5 RSP
df_tmp = df_portfolio_features.sort_values(by = 'RSP', ascending=False)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
18,COFFEEDAY,-0.15,-31.18,96.56,35.27,75456.0,-35405.0,78144.0,80.00,-47.69,89.0,L-SC,22.07,266.0,-0.47,0.53,92.71,XR,NTT,HOTELS
68,SATIN,-1.81,25.75,20.74,51.83,72057.0,71146.0,347430.0,274.00,13.01,66.0,H-SC,39.31,159.0,0.99,2.36,69.25,XY24,NTT,FINANCE
91,ZYDUSLIFE,-0.72,12.89,20.15,35.63,47671.0,27006.0,236580.0,1286.17,-1.80,66.0,H-MC,7.89,120.0,0.57,1.61,24.39,AR,ATH,PHARMA
3,ALKYLAMINE,2.22,-22.56,150.05,93.63,117314.0,-22780.0,78183.0,4546.37,-17.07,63.0,H-SC,10.09,142.0,-0.19,0.53,47.63,SR,ATH,CHEMICALS
69,SFL,-1.93,-41.62,116.92,26.63,178971.0,-109147.0,153071.0,1287.00,15.91,53.0,M-SC,8.80,242.0,-0.61,1.04,27.58,XY24,NTT,MISC

In [24]:
# Top N allocation
df_tmp = df_portfolio_features.sort_values(by = 'CurrAlloc%', ascending=False)
top_n_values = [10, 25, 50]

sum_df = pd.DataFrame({
    'Top_N': top_n_values,
    'Sum_Alloc%': [df_tmp['CurrAlloc%'].head(n).sum() for n in top_n_values]
})

sum_df

   Top_N  Sum_Alloc%
0     10       19.76
1     25       42.76
2     50       72.53

In [25]:
# market-cap-wise allocation
df_tmp = df_portfolio_features[cols]
df_tmp.groupby(df_tmp['Conviction'].str[-2:])['CurrAlloc%'].sum().sort_values(ascending=False)

Conviction
SC    43.11
LC    31.57
MC    25.29
Name: CurrAlloc%, dtype: float64

In [26]:
# criteria-wise allocation
df_portfolio_features.groupby('Criteria')['CurrAlloc%'].sum().sort_values(ascending=False)

Criteria
XY24     27.68
X40      25.01
X40N     17.00
XR        9.20
OX40N     6.92
AR        6.90
XY25      6.37
SR        0.89
Name: CurrAlloc%, dtype: float64

In [27]:
# conviction-wise allocation
df_portfolio_features.groupby('Conviction')['CurrAlloc%'].sum().sort_values(ascending=False)

Conviction
X-LC    29.36
H-SC    22.78
X-MC    20.27
M-SC     9.87
X-SC     9.74
H-MC     2.75
M-MC     1.93
H-LC     1.25
M-LC     0.96
L-SC     0.72
L-MC     0.34
Name: CurrAlloc%, dtype: float64

In [28]:
# sector-wise stats
df_tmp = df_portfolio_features.groupby('Category')[['CurrAlloc%', 'Current', 'Current P/L', 'FTT Amt']].sum().sort_values(by=['Current', 'Current P/L'], ascending=False)
df_tmp['Current P/L%'] = round(df_tmp['Current P/L'] * 100 / df_tmp['Current'], 2)
df_tmp['FTT%'] = round(df_tmp['FTT Amt'] * 100 / df_tmp['Current'], 2)
cols = ['CurrAlloc%', 'Current P/L%', 'FTT%']
df_tmp[cols].sort_values(by=['CurrAlloc%'], ascending=False)

               CurrAlloc%  Current P/L%    FTT%
Category
FMCG                14.89        -20.78   63.15
FINANCE             10.76        -16.41   67.05
IT                  10.47        -46.45  119.67
AUTO                 6.89         -7.98   48.46
MISC                 6.88        -32.26   89.72
BANKS                5.73         -7.76   57.58
PAINTS               5.58        -20.00   40.83
INSURANCE            5.20         -8.17   44.87
PHARMA               5.01         -0.48   31.85
ELECTRICAL           4.08        -17.81   59.38
CHEMICALS            2.20        -24.90   99.33
HEALTHCARE           2.07        -17.69   48.40
APPARELS             1.78         -2.31   36.67
FOOTWEAR             1.78        -68.62  136.23
AC                   1.76        -23.89   57.48
DURABLES             1.60        -64.88  104.99
TRAVEL               1.60        -90.75  186.27
BREWERIES            1.47         -8.43   30.94
REALTY               1.38         -9.24   27.18
CERAMICS             1.34        -56.32  103.81
ENGINEERING          1.32        -25.19   82.45
CABLES               1.25         19.73   66.89
REFINERIES           1.14        -19.61   49.87
CEMENT               1.10        -65.29  188.95
JEWELLERY            1.05       -107.73  179.89
ENTERTAINMENT        0.71        -84.84  195.09
HOTELS               0.53        -45.31   96.56
TEXTILES             0.40        -55.37   99.67

In [29]:
# money to be made criteria-wise
df_portfolio_features.groupby('Criteria')['FTT Amt'].agg(['sum', 'count']).sort_values(by='sum', ascending=False)

                sum  count
Criteria
XY24      3525320.0     21
X40       2001730.0     19
XR        1327485.0     13
X40N      1224443.0     13
AR        1169300.0      9
OX40N      776091.0     10
XY25       498355.0      5
SR         288289.0      2

In [30]:
# money to be made conviction-wise
df_portfolio_features.groupby('Conviction')['FTT Amt'].agg(['sum', 'count']).sort_values(by='sum', ascending=False)

                  sum  count
Conviction
H-SC        3435320.0     24
X-LC        1966953.0     21
X-MC        1736111.0     15
M-SC        1466943.0     14
X-SC        1370921.0      9
H-MC         294290.0      2
L-SC         185430.0      2
M-LC         151173.0      1
M-MC         102656.0      2
L-MC          51979.0      1
H-LC          49237.0      1

In [31]:
# money to be made criteria and conviction-wise
df_portfolio_features.groupby(['Conviction', 'Criteria'])['FTT Amt'].agg(['sum', 'count']).sort_values(by='sum', ascending=False)

                           sum  count
Conviction Criteria
X-LC       X40       1058405.0     10
H-SC       XY24      1054141.0      6
           AR         958503.0      5
M-SC       XY24       853588.0      6
H-SC       XR         809714.0      7
X-SC       XY24       807164.0      4
X-MC       X40        725108.0      7
           X40N       507404.0      4
X-LC       X40N       371499.0      6
X-SC       X40N       345540.0      3
M-SC       OX40N      341444.0      5
H-SC       OX40N      324673.0      4
X-LC       XY24       324165.0      2
H-SC       SR         288289.0      2
X-MC       XY25       263956.0      2
H-MC       XY24       246619.0      1
X-MC       XY24       239643.0      2
X-SC       X40        218217.0      2
M-SC       XR         193543.0      2
X-LC       XY25       167264.0      2
M-LC       XR         151173.0      1
L-SC       OX40N      109974.0      1
M-SC       AR          78368.0      1
L-SC       XR          75456.0      1
M-MC       XY25        67135.0      1
L-MC       XR          51979.0      1
H-LC       AR          49237.0      1
H-MC       AR          47671.0      1
X-LC       XR          45620.0      1
M-MC       AR          35521.0      1

In [32]:
# notebook execution time

end_time = time.time()
execution_time = round(end_time - start_time, 0)
print(f"Notebook execution time: {execution_time} seconds")

Notebook execution time: 25.0 seconds