<a href="https://colab.research.google.com/github/ankit-rathi/Quantvesting_v2/blob/main/myStocks_Portfolio_Analysis.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
'''
!pip install pandas==2.2.2 -qq
!pip install pyxirr -qq
!pip install ta -qq
!pip install yfinance==0.2.59 -qq
'''

'\n!pip install pandas==2.2.2 -qq\n!pip install pyxirr -qq\n!pip install ta -qq\n!pip install yfinance==0.2.59 -qq\n'

In [2]:
# import libraries

import numpy as np
import pandas as pd
import datetime
import warnings
warnings.filterwarnings('ignore')
import yfinance as yfin
import ta
import matplotlib.pyplot as plt
import requests

In [3]:
# notebook start time
import time
import datetime
import pytz

start_time = time.time()

# function to print date timestamp
def print_date_time():
  tz_NY = pytz.timezone('Asia/Kolkata')
  datetime_NY = datetime.datetime.now(tz_NY)
  print("Run date time (IST):", datetime_NY.strftime("%Y-%m-%d %H:%M:%S"))

In [4]:
# function to get booked and reserved amount
def get_amt():
  # fetch the JSON data from the URL
  url = "https://raw.githubusercontent.com/ankit-rathi/Tradevesting_v1/main/data/myPortfolioAmts.json"
  response = requests.get(url)
  pf_amts = response.json()  # parse the JSON data

  # extract values from the JSON
  py_booked_amt_dm = pf_amts["py_booked_amt_dm"]
  py_booked_amt_sv = pf_amts["py_booked_amt_sv"]
  cy_booked_amt_dm = pf_amts["cy_booked_amt_dm"]
  cy_booked_amt_sv = pf_amts["cy_booked_amt_sv"]
  reserve_amt_dm = pf_amts["reserve_amt_dm"]
  reserve_amt_sv = pf_amts["reserve_amt_sv"]

  # perform calculations
  py_booked_amt = py_booked_amt_dm + py_booked_amt_sv
  cy_booked_amt = cy_booked_amt_dm + cy_booked_amt_sv
  reserve_amt = reserve_amt_dm + reserve_amt_sv
  total_booked_amt = py_booked_amt + cy_booked_amt

  return total_booked_amt, reserve_amt, cy_booked_amt, py_booked_amt

gen_output = 0

In [5]:
# function to format the amount
def format_amt(number):
    abs_number = abs(number)

    if abs_number >= 1_00_00_000:  # Crores
        formatted_amt = f"{number / 1_00_00_000:.2f} C"
    elif abs_number >= 1_00_000:  # Lakhs
        formatted_amt = f"{number / 1_00_000:.2f} L"
    elif abs_number >= 1_000:  # Thousands
        formatted_amt = f"{number / 1_000:.2f} K"
    else:
        formatted_amt = f"{number:.2f}"

    return formatted_amt

# function to set start and end date
def get_start_end_date():
  start_date = (datetime.date.today() + datetime.timedelta(days=-365)).strftime('%Y-%m-%d')
  end_date = (datetime.date.today() + datetime.timedelta(days=1)).strftime('%Y-%m-%d')
  return start_date, end_date

# function to fetch my portfolio csv
def get_mypfs_df():
  mypfs_df = pd.read_csv('https://raw.githubusercontent.com/ankit-rathi/Tradevesting_v1/main/data/myPortfolioStocks.csv')
  return mypfs_df

# function to fetch my prospects csv
def get_mypps_df():
  mypps_df = pd.read_csv('https://raw.githubusercontent.com/ankit-rathi/Tradevesting_v1/main/data/myProspectsScrips.csv')
  return mypps_df

# function to fetch screener data
def get_myscreen_df():
  myscreen_df = pd.read_csv('https://raw.githubusercontent.com/ankit-rathi/Tradevesting_v1/main/data/myScreenerDB.csv')
  return myscreen_df

# function to fetch momentum data
def get_myinvmt_df():
  myinvmt_df = pd.read_csv('https://raw.githubusercontent.com/ankit-rathi/Tradevesting_v1/main/data/myInvestments.csv')
  return myinvmt_df

# function to get the stock ids
def get_stock_ids(df_pf):
  stock_n100 = df_pf['Symbol'].unique()

  exclude = ['CADILAHC','MMTC', 'MASFIN']

  stock_ids = df_pf[~df_pf['Symbol'].isin(exclude) ]['Symbol'].unique()

  #mypf = mypf[mypf.Forecast.notnull()]
  #stock_ids = mypf['Symbol'].unique()

  #stock_ids.sort()
  return stock_ids

# get features from screener data
def get_screener_features():
  myscreen_df = get_myscreen_df()
  cols = ['Symbol', 'EPS', 'MedPE', 'ROCE%', 'ROE%', 'CapType']
  return myscreen_df[cols]

# get relative strength
def get_relative_strength(stock_list):

    # Dictionary to store stock tickers and their corresponding percentage price change
    stock_changes = {}

    # Loop through each stock and fetch its price data
    for stock in stock_list:
        try:
            # Download the stock data for the given date range
            stock_data = yfin.Ticker(stock + '.NS').history(period='1mo', interval='1d')[map(str.title, ['open', 'close', 'low', 'high', 'volume'])]

            # Calculate the percentage change for the stock
            if len(stock_data) > 0:
                start_price = stock_data['Close'].iloc[0]
                end_price = stock_data['Close'].iloc[-1]
                percent_change = round(((end_price - start_price) / start_price) * 100, 2)
                stock_changes[stock] = percent_change
            else:
                stock_changes[stock] = np.nan  # If no data is available, set to NaN

        except Exception as e:
            print(f"Error fetching data for {stock}: {e}")
            stock_changes[stock] = np.nan

    # Create a DataFrame with stock tickers and their percentage changes
    df = pd.DataFrame(list(stock_changes.items()), columns=['Symbol', 'Percent_Change'])

    # Drop any stocks with missing data (NaN values)
    df = df.dropna()

    # Calculate the percentile rank based on percentage change
    df['RSP'] = round(df['Percent_Change'].rank(pct=True) * 100, 2)
    cols = ['Symbol', 'RSP']
    df = df[cols]
    # Sort by percentile rank (optional)
    df = df.sort_values(by='RSP', ascending=False).reset_index(drop=True)

    return df

In [6]:
# function to get stock technicals
def stock_prec_dev(stock_symbol):
    #stock_symbol = 'ULTRACEMCO.NS'
    short_window = 20
    mid_window = 50
    long_window = 200
    moving_avg = 'SMA'

    start = datetime.datetime(*map(int, start_date.split('-')))
    end = datetime.datetime(*map(int, end_date.split('-')))

    stock_df = yfin.Ticker(stock_symbol + '.NS').history(period='max', interval='1d')[map(str.title, ['open', 'close', 'low', 'high', 'volume'])]

    stock_df['Max'] = round(max(stock_df['Close']),2)
    stock_df = stock_df[(stock_df.index <= end_date) & (stock_df.index >= start_date)]
    stock_df['200_SMA'] = round(stock_df['Close'].rolling(window = 200, min_periods = 1).mean(),0)
    stock_df['Dev%_200'] = round((stock_df['Close'] - stock_df['200_SMA'])*100/stock_df['200_SMA'],2)
    stock_df.dropna(axis = 0, inplace = True) # remove any null rows

    stock_df['20_SMA'] = stock_df['Close'].rolling(window=20).mean()
    stock_df['50_SMA'] = stock_df['Close'].rolling(window=50).mean()
    stock_df['Symbol'] = stock_symbol

    stock_df['Close'] = round(stock_df['Close'],2)
    stock_df['Min'] = round(min(stock_df['Close']),2)
    stock_df['RSI_14'] = ta.momentum.RSIIndicator(close=stock_df['Close'], window=14).rsi()
    stock_df['RSI_14'] = round(stock_df['RSI_14'],0)
    stock_df['Prev_Close'] = stock_df['Close'].shift(1)
    stock_df.drop(['Open', 'Low', 'High', 'Volume'], axis=1, inplace=True)
    stock_df = stock_df.tail(1)

    max_SMA = max(stock_df['20_SMA'].item(), stock_df['50_SMA'].item(), stock_df['200_SMA'].item())
    min_SMA = min(stock_df['20_SMA'].item(), stock_df['50_SMA'].item(), stock_df['200_SMA'].item())
    ABS_Spread = max_SMA - min_SMA
    stock_df['Spread%'] = round((ABS_Spread / stock_df['200_SMA'].item()) * 100,2)

    return stock_df

# function to compute stock attributes
def get_common_features(stock_ids, df_mypf):

  df_prec_dev = pd.DataFrame()
  df_tmp = get_screener_features()
  df_rs = get_relative_strength(stock_ids)

  for stock_id in stock_ids:
      tmp = stock_prec_dev(stock_id)
      tmp = tmp.reset_index()
      df_prec_dev = pd.concat([df_prec_dev, tmp], ignore_index = True)
  df_prec_dev = pd.merge(df_prec_dev, df_mypf, on= 'Symbol')
  df_prec_dev = pd.merge(df_prec_dev, df_tmp, on= 'Symbol', how='left')
  df_prec_dev = pd.merge(df_prec_dev, df_rs, on= 'Symbol', how='left')
  #print(df_prec_dev.columns)
  df_prec_dev['Curr_PE'] = round(df_prec_dev['Close']/df_prec_dev['EPS'],1)
  df_prec_dev['Dev%_PE'] = round((df_prec_dev['Curr_PE'] - df_prec_dev['MedPE'])*100/df_prec_dev['MedPE'],2)
  df_prec_dev['Conviction'] = df_prec_dev['Conviction'] + '-' + df_prec_dev['CapType']
  return df_prec_dev

# function to arrange stock features
def arrange_features(df_stocks, common_cols, diff_cols):
  df_stocks_common = df_stocks[common_cols].drop_duplicates()
  df_stocks_diff = df_stocks[diff_cols]
  df_stocks_diff['Investment'] = df_stocks_diff['AvgCost'] * df_stocks_diff['Shares']
  df_stocks_diff = df_stocks_diff.groupby(['Symbol'])[['Shares', 'Investment']].aggregate(['sum']).reset_index()
  df_stocks_diff.columns = ['Symbol', 'Shares', 'Investment']
  df_stocks_diff['AvgCost'] = round(df_stocks_diff['Investment']/df_stocks_diff['Shares'],2)
  df_stocks = pd.merge(df_stocks_diff, df_stocks_common, on='Symbol')
  return df_stocks

# plot fact distribution across dimension
def plot_pie_chart(df, dimension, fact):
  # grouping the data by category and calculating the sum of fact for each type
  grouped_data = df.groupby(dimension)[fact].sum()

  # sorting the grouped data in descending order
  grouped_data = grouped_data.sort_values(ascending=False)

  # creating a pie chart
  grouped_data.plot.pie(autopct='%1.1f%%', startangle=90, figsize=(6, 6))

  # adding a title and displaying the plot
  plt.title(f'{dimension} {fact} Distribution')
  plt.ylabel('')  # To hide the y-label
  plt.show()

In [7]:
# function to get portfolio features

def get_portfolio_features(df_common_features):

  print_date_time()
  print('-------------------')

  #df_common_features["Target"] = df_common_features["Target"].fillna(df_common_features["Max"])
  df_common_features['NTT'] = np.where(df_common_features['Strategy']== 'NTT', df_common_features["Target"], df_common_features['Max'])
  df_common_features['LTT'] = np.where(df_common_features['Strategy']== 'BTT', df_common_features["Target"], df_common_features['Max'])
  df_common_features['BOL'] = df_common_features['Min']

  tmp_df = df_common_features[df_common_features['Symbol'].isin(mypf_df[mypf_df['InPortfolio'] != 'NA'].Symbol.values)]
  print('qualified stocks: '+str(len(tmp_df['Symbol'].unique())))
  tmp_df1 = tmp_df[tmp_df['LatestQtr'] == 1]
  print('with latest results: '+str(len(tmp_df1['Symbol'].unique())))
  tmp_df1 = tmp_df1[tmp_df1['StarStock'] == 1]
  print('still star stocks: '+str(len(tmp_df1['Symbol'].unique())))
  tmp_df['Investment'] = tmp_df['AvgCost'] * tmp_df['Shares']
  tmp_df['Current'] = round(tmp_df['Close'] * tmp_df['Shares'],0)
  tmp_df['Previous'] = tmp_df['Prev_Close'] * tmp_df['Shares']
  tmp_df['EstimatedST'] = tmp_df['NTT'] * tmp_df['Shares']
  tmp_df['EstimatedLT'] = tmp_df['LTT'] * tmp_df['Shares']
  tmp_df['Current P/L'] = round((tmp_df['Current'] - tmp_df['Investment']),0)
  tmp_df['Today P/L%'] = round((tmp_df['Current'] - tmp_df['Previous'])*100/tmp_df['Previous'],2)
  tmp_df['Current P/L%'] = round((tmp_df['Current'] - tmp_df['Investment'])*100/tmp_df['Investment'],2)
  tmp_df['EstimatedST P/L%'] = round((tmp_df['EstimatedST'] - tmp_df['Investment'])*100/tmp_df['Investment'],2)
  tmp_df['EstimatedLT P/L%'] = round((tmp_df['EstimatedLT'] - tmp_df['Investment'])*100/tmp_df['Investment'],2)
  tmp_df['NTT%'] = round((tmp_df['NTT'] - tmp_df['Close'])*100/tmp_df['Close'],2)
  tmp_df['LTT%'] = round((tmp_df['LTT'] - tmp_df['Close'])*100/tmp_df['Close'],2)
  tmp_df['Gained%'] = round((tmp_df['Close'] - tmp_df['BOL'])*100/tmp_df['BOL'],2)
  investment = round(sum(tmp_df['AvgCost']*tmp_df['Shares']),0)
  current = round(sum(tmp_df['Close']*tmp_df['Shares']),0)
  tmp_df['InitAlloc%'] = round(tmp_df['Investment']*100/investment,2)
  tmp_df['CurrAlloc%'] = round(tmp_df['Current']*100/current,2)
  tmp_df['FTT'] = tmp_df['LTT']
  tmp_df.loc[tmp_df['Strategy'] == 'NTT', 'FTT'] = tmp_df['NTT']
  tmp_df['FTT%'] = tmp_df['LTT%']
  tmp_df.loc[tmp_df['Strategy'] == 'NTT', 'FTT%'] = tmp_df['NTT%']
  tmp_df['FTT Amt'] = round(tmp_df['FTT%'] * tmp_df['Current']/100,0)
  tmp_df['OTT%'] = round((tmp_df['FTT'] - tmp_df['AvgCost'])*100/tmp_df['AvgCost'],2)
  tmp_df['RRR Ind'] = round(tmp_df['Current P/L']/tmp_df['FTT Amt'],2)
  tmp_df['Risk Ind'] = round(tmp_df['Current P/L%']*tmp_df['CurrAlloc%'],0)

  return tmp_df

# function to print portfolio features
def print_portfolio_stats(df_portfolio_features, myinvmt_df):
  from pyxirr import xirr

  total_booked_amt, reserve_amt, cy_booked_amt, py_booked_amt = get_amt()

  dates = myinvmt_df['Date'].values
  dates = np.append(dates, datetime.date.today().strftime('%d-%b-%y'))
  investment = myinvmt_df['Investment'].values
  dates= pd.to_datetime(dates)

  current = round(sum(df_portfolio_features['Close']*df_portfolio_features['Shares']),0) + reserve_amt
  investment_xirr = np.append(investment, current)
  cagr = round(xirr(pd.DataFrame({"dates": dates, "amounts": investment_xirr}))*100,2)

  investment = -sum(investment)
  invested = round(sum(df_portfolio_features['AvgCost']*df_portfolio_features['Shares']),0) + reserve_amt
  previous = round(sum(df_portfolio_features['Prev_Close']*df_portfolio_features['Shares']),0) + reserve_amt
  cy_invested = investment + py_booked_amt

  today_pnl_amount = current-previous
  today_pnl_percentage = round((current-previous)*100/previous,2)

  curr_pnl_amount = current-invested
  curr_pnl_percentage = round((curr_pnl_amount)*100/(cy_invested),2)

  cy_pnl_amount = cy_booked_amt + curr_pnl_amount
  cy_pnl_percentage = round((cy_pnl_amount)*100/cy_invested,2)

  overall_pnl_amount = total_booked_amt + curr_pnl_amount
  overall_pnl_percentage = round((overall_pnl_amount)*100/investment,2)

  estimate_st = round(sum(df_portfolio_features['FTT']*df_portfolio_features['Shares']),0)  + reserve_amt
  est_st_pnl_amount = estimate_st-current
  est_st_pnl_percentage = round((est_st_pnl_amount)*100/current,2)

  estimate_lt = round(sum(df_portfolio_features['LTT']*df_portfolio_features['Shares']),0)  + reserve_amt
  est_lt_pnl_amount = estimate_lt-current
  est_lt_pnl_percentage = round((est_lt_pnl_amount)*100/current,2)

  total_profit = round(sum(df_portfolio_features[df_portfolio_features['Current P/L%'] > 0]['Current']) - sum(df_portfolio_features[df_portfolio_features['Current P/L%'] > 0]['Investment']),0)
  total_loss = round(sum(df_portfolio_features[df_portfolio_features['Current P/L%'] < 0]['Current']) - sum(df_portfolio_features[df_portfolio_features['Current P/L%'] < 0]['Investment']),0)

  cy_booked_percentage = round((cy_booked_amt)*100/current,2)
  py_booked_percentage = round((py_booked_amt)*100/investment,2)
  total_booked_percentage = round((total_booked_amt)*100/investment,2)

  print('-------------------')
  print('Initial Investment: ', format_amt(investment))
  print('CY Investment: ', format_amt(cy_invested))
  print('Reserve: ', format_amt(reserve_amt))
  print('Current: ',  format_amt(current))
  print('-------------------')
  print('Today PnL: '+ '{} ({}%)'.format(format_amt(today_pnl_amount), today_pnl_percentage))
  print('Current PnL: '+ '{} ({}%)'.format(format_amt(curr_pnl_amount), curr_pnl_percentage))
  print('CY Booked + Current PnL: '+ '{} ({}%)'.format(format_amt(cy_pnl_amount), cy_pnl_percentage))
  print('-------------------')
  print('Total profit: ', format_amt(total_profit))
  print('Total loss: ', format_amt(total_loss))
  print('-------------------')
  print('Total Booked + Current PnL: '+ '{} ({}%)'.format(format_amt(overall_pnl_amount), overall_pnl_percentage))
  print('Total Booked PnL: '+ '{} ({}%)'.format(format_amt(total_booked_amt), total_booked_percentage))
  print('Curr Year Booked PnL: '+ '{} ({}%)'.format(format_amt(cy_booked_amt), cy_booked_percentage))
  print('Prev Year Booked PnL: '+ '{} ({}%)'.format(format_amt(py_booked_amt), py_booked_percentage))
  print('===================')
  print('Est FTT: ',  format_amt(estimate_st))
  print('Est FTT PnL: '+ '{} ({}%)'.format(format_amt(est_st_pnl_amount), est_st_pnl_percentage))

  print('===================')
  print('Deployed: ', format_amt(investment))

  print('Current: ', format_amt(current))

  print('CAGR/XIRR %: '+'{}%'.format(cagr))

In [8]:
# get start and end date
start_date, end_date = get_start_end_date()

# get portfolio and prospects data
mypfs_df = get_mypfs_df()
mypps_df = get_mypps_df()
myinvmt_df = get_myinvmt_df()

# merge above datasets
mypf_df = pd.merge(mypfs_df, mypps_df, on="Symbol")

# seggregate dm and sv portfolio
dm_pf = mypf_df[mypf_df['InPortfolio'] == 'DM']
sv_pf = mypf_df[mypf_df['InPortfolio'] == 'SV']

# build portfolio stock dataframe
dm_stocks = get_stock_ids(dm_pf)
sv_stocks = get_stock_ids(sv_pf)
df_stocks = pd.concat([dm_pf,sv_pf], ignore_index = True)

# arrange common and diff stock features
common_cols = ['Symbol', 'Target', 'Criteria', 'Strategy', 'CumlRnk', 'LatestQtr', 'StarStock', 'Conviction', 'Category', 'InFolio', 'XIRR', 'MBQ']
diff_cols = ['Symbol', 'AvgCost', 'Shares']
df_stocks = arrange_features(df_stocks, common_cols, diff_cols)

# get common features
stock_ids = df_stocks['Symbol'].values
df_common_features = get_common_features(stock_ids, df_stocks)

df_common_features.reset_index(drop=True, inplace=True)
df_common_features.drop(['Date'], axis=1, inplace=True)
# get and print portfolio features
df_portfolio_features = get_portfolio_features(df_common_features)

print_portfolio_stats(df_portfolio_features, myinvmt_df)

df = df_portfolio_features
#plot_pie_chart(df, 'CapType', 'Current')
list_ox40n = list(df[df['MBQ'].str.contains('OX40N', na=False)]['Symbol'].values)

Run date time (IST): 2026-04-16 15:26:36
-------------------
qualified stocks: 86
with latest results: 26
still star stocks: 16
-------------------
Initial Investment:  1.36 C
CY Investment:  1.62 C
Reserve:  1.61 K
Current:  1.42 C
-------------------
Today PnL: 1.08 L (0.76%)
Current PnL: -34.94 L (-21.5%)
CY Booked + Current PnL: -19.05 L (-11.72%)
-------------------
Total profit:  1.90 L
Total loss:  -36.84 L
-------------------
Total Booked + Current PnL: 7.93 L (5.86%)
Total Booked PnL: 42.87 L (31.64%)
Curr Year Booked PnL: 15.89 L (11.18%)
Prev Year Booked PnL: 26.98 L (19.91%)
===================
Est FTT:  2.48 C
Est FTT PnL: 1.06 C (74.33%)
===================
Deployed:  1.36 C
Current:  1.42 C
CAGR/XIRR %: 2.32%

In [9]:
# top 5 near their targets
cols = ['Symbol', 'Today P/L%', 'Current P/L%', 'FTT%', 'OTT%', 'FTT Amt', 'Current P/L', 'Current', 'FTT', 'Dev%_PE', 'RSI_14','Conviction', 'Spread%',  'CumlRnk', 'RRR Ind', 'CurrAlloc%', 'Gained%', 'Criteria', 'Strategy', 'Category']
df_tmp = df_portfolio_features[~df_portfolio_features['Symbol'].isin(['ENRIN','BLUSPRING','DIGITIDE'])]
df_tmp = df_tmp.sort_values(by = 'FTT Amt', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
5,ANGELONE,-1.71,19.95,3.53,24.18,12915.0,60850.0,365850.0,303.00,-82.85,72.0,X-SC,1.18,97.0,4.71,2.57,39.96,X40N,NTT,FINANCE
50,MASFIN,1.05,-2.94,25.25,21.57,24013.0,-2880.0,95100.0,397.04,-16.44,57.0,H-SC,4.25,167.0,-0.12,0.67,22.89,XR,ATH,FINANCE
77,TTKPRESTIG,0.26,-37.34,59.75,0.09,37727.0,-37635.0,63142.0,770.00,46.64,50.0,M-SC,23.36,250.0,-1.00,0.44,12.43,OX40N,NTT,DURABLES
67,SONACOMS,-0.53,0.79,38.01,39.09,38753.0,796.0,101955.0,804.02,-20.20,68.0,M-MC,9.00,193.0,0.02,0.72,44.23,AR,ATH,AUTO
37,ICICIGI,1.40,-0.20,19.58,19.34,39104.0,-394.0,199715.0,2252.93,-16.16,64.0,X-MC,7.47,66.0,-0.01,1.40,11.54,X40,ATH,INSURANCE

In [10]:
# top 5 today
df_tmp = df_portfolio_features.sort_values(by = 'Today P/L%', ascending=False)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
80,VALIANTORG,7.88,-40.22,191.33,74.15,187123.0,-65804.0,97801.0,838.00,-275.92,67.0,H-SC,19.89,145.0,-0.35,0.69,45.54,XR,NTT,CHEMICALS
55,RAJESHEXPO,5.00,-75.46,307.71,0.07,103600.0,-103509.0,33668.0,518.00,1133.59,64.0,L-SC,43.08,268.0,-1.00,0.24,58.06,OX40N,NTT,JEWELLERY
36,HONAUT,4.20,-17.60,83.63,51.31,132888.0,-33938.0,158900.0,58357.33,-31.51,67.0,X-SC,18.83,90.0,-0.26,1.12,20.72,X40N,ATH,ELECTRICAL
81,VBL,3.92,-6.47,44.88,35.50,132573.0,-20448.0,295394.0,670.80,-17.37,68.0,X-LC,11.87,13.0,-0.15,2.08,21.29,X40N,ATH,FMCG
68,STARHEALTH,3.66,-3.91,53.26,47.26,143868.0,-11000.0,270123.0,761.00,51.60,69.0,H-SC,1.32,173.0,-0.08,1.90,39.89,XY24,NTT,INSURANCE

In [11]:
# bottom 5 today
df_tmp = df_portfolio_features.sort_values(by = 'Today P/L%', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
14,BOSCH-HCIL,-2.08,-41.68,71.45,-0.01,53256.0,-53269.0,74536.0,2282.0,15160.87,56.0,M-SC,9.00,231.0,-1.00,0.52,26.87,OX40N,BTT,AC
34,HDFCBANK,-1.99,-5.04,35.17,28.37,78449.0,-11827.0,223058.0,1073.0,-19.05,46.0,X-LC,17.13,26.0,-0.15,1.57,8.51,X40,BTT,BANKS
5,ANGELONE,-1.71,19.95,3.53,24.18,12915.0,60850.0,365850.0,303.0,-82.85,72.0,X-SC,1.18,97.0,4.71,2.57,39.96,X40N,NTT,FINANCE
21,DABUR,-1.43,-16.51,72.11,43.70,149354.0,-40949.0,207119.0,735.0,-24.27,42.0,X-MC,14.56,70.0,-0.27,1.46,4.04,XY24,BTT,FMCG
7,ATULAUTO,-1.28,-19.66,81.19,45.57,128582.0,-38760.0,158372.0,844.0,3424.32,59.0,M-SC,7.54,248.0,-0.30,1.11,21.87,XY24,NTT,AUTO

In [12]:
# top 5 to exit based on CumlRnk
df_tmp = df_portfolio_features[~df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])]
df_tmp = df_tmp[(df_tmp['Current P/L%'] > -1) & (df_tmp['Current P/L%'] < 1)].sort_values(by = 'CumlRnk', ascending=False)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
67,SONACOMS,-0.53,0.79,38.01,39.09,38753.0,796.0,101955.0,804.02,-20.2,68.0,M-MC,9.0,193.0,0.02,0.72,44.23,AR,ATH,AUTO

In [13]:
# OX40N stocks to exit
df_tmp = df_portfolio_features[(df_portfolio_features['Symbol'].isin(list_ox40n))].sort_values(by = 'Current P/L%', ascending=False)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
26,FINCABLES,3.56,15.90,79.39,107.91,135847.0,23470.0,171114.0,1641.55,4.01,63.0,M-SC,1.87,220.0,0.17,1.20,28.74,OX40N,ATH,CABLES
66,SIS,0.13,-26.81,65.67,21.26,53369.0,-29764.0,81268.0,528.00,1913.99,67.0,H-SC,12.81,168.0,-0.56,0.57,20.83,OX40N,NTT,MISC
18,CERA,-0.39,-30.99,79.52,23.89,96534.0,-54507.0,121396.0,9475.00,-33.41,67.0,H-SC,15.36,153.0,-0.56,0.85,16.66,OX40N,NTT,CERAMICS
48,KANSAINER,2.28,-32.99,69.35,13.47,125311.0,-88974.0,180693.0,340.00,-42.48,63.0,H-SC,22.35,162.0,-0.71,1.27,26.21,XY24,NTT,PAINTS
72,TATAELXSI,1.21,-33.77,99.35,32.03,86746.0,-44521.0,87314.0,9161.00,-17.17,60.0,H-SC,19.86,158.0,-0.51,0.61,15.56,OX40N,NTT,IT

In [14]:
# top 5 to book for rotation
df_tmp = df_portfolio_features[(df_portfolio_features['Current P/L%'] > 20) ].sort_values(by = 'CumlRnk', ascending=False)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
1,ABB,0.12,26.26,15.29,45.57,50505.0,68693.0,330312.0,7934.0,-18.83,70.0,H-MC,16.42,125.0,1.36,2.32,46.68,AR,NTT,ELECTRICAL

In [15]:
# top 5 to monitor for exit
df_tmp = df_portfolio_features[~df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])]
df_tmp = df_tmp[(df_tmp['Current P/L%'] > 0) ].sort_values(by = 'Dev%_PE', ascending=False)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
26,FINCABLES,3.56,15.90,79.39,107.91,135847.0,23470.0,171114.0,1641.55,4.01,63.0,M-SC,1.87,220.0,0.17,1.20,28.74,OX40N,ATH,CABLES
1,ABB,0.12,26.26,15.29,45.57,50505.0,68693.0,330312.0,7934.00,-18.83,70.0,H-MC,16.42,125.0,1.36,2.32,46.68,AR,NTT,ELECTRICAL
67,SONACOMS,-0.53,0.79,38.01,39.09,38753.0,796.0,101955.0,804.02,-20.20,68.0,M-MC,9.00,193.0,0.02,0.72,44.23,AR,ATH,AUTO

In [16]:
# top 5 to book for rotation from weak conviction
df_tmp = df_portfolio_features[~df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])]
df_tmp = df_tmp[~df_tmp['Criteria'].isin(['XY25','XY24','X40', 'X40N'])].sort_values(by = 'RRR Ind', ascending=False)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
1,ABB,0.12,26.26,15.29,45.57,50505.0,68693.0,330312.0,7934.00,-18.83,70.0,H-MC,16.42,125.0,1.36,2.32,46.68,AR,NTT,ELECTRICAL
26,FINCABLES,3.56,15.90,79.39,107.91,135847.0,23470.0,171114.0,1641.55,4.01,63.0,M-SC,1.87,220.0,0.17,1.20,28.74,OX40N,ATH,CABLES
67,SONACOMS,-0.53,0.79,38.01,39.09,38753.0,796.0,101955.0,804.02,-20.20,68.0,M-MC,9.00,193.0,0.02,0.72,44.23,AR,ATH,AUTO
85,ZYDUSLIFE,0.29,-1.01,37.01,35.63,76782.0,-2110.0,207464.0,1286.17,-13.96,63.0,H-MC,5.73,120.0,-0.03,1.46,15.50,AR,ATH,PHARMA
40,INDIAMART,1.54,-7.49,123.46,106.72,140865.0,-9238.0,114098.0,4810.62,-58.20,60.0,H-SC,12.72,140.0,-0.07,0.80,9.62,AR,ATH,MISC

In [17]:
# top 5 to accumulate based on lowest RSI_14
df_tmp = df_portfolio_features[df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])].sort_values(by = 'RSI_14', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
21,DABUR,-1.43,-16.51,72.11,43.70,149354.0,-40949.0,207119.0,735.00,-24.27,42.0,X-MC,14.56,70.0,-0.27,1.46,4.04,XY24,BTT,FMCG
2,ABBOTINDIA,-0.42,-13.23,36.07,18.07,55977.0,-23665.0,155190.0,35195.00,-26.09,44.0,X-MC,11.67,58.0,-0.42,1.09,1.49,X40,ATH,PHARMA
53,PGHH,-0.13,-25.91,78.17,32.01,123665.0,-55320.0,158200.0,17616.87,-49.95,44.0,X-MC,21.62,57.0,-0.45,1.11,8.20,X40,ATH,FMCG
78,UNITDSPR,0.36,-7.67,30.80,20.77,66586.0,-17957.0,216187.0,1644.00,-18.18,45.0,X-MC,6.39,64.0,-0.27,1.52,3.13,X40N,NTT,BREWERIES
59,RELIANCE,0.07,-13.66,45.13,25.30,78303.0,-27458.0,173505.0,1952.00,-15.80,46.0,X-LC,5.32,21.0,-0.35,1.22,8.96,XY25,BTT,REFINERIES

In [18]:
# top 5 to accumulate based on Spread and CumlRnk
df_tmp = df_portfolio_features[df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])]
df_tmp = df_tmp[(df_tmp['CumlRnk'] < 100)].sort_values(by = 'Spread%', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
5,ANGELONE,-1.71,19.95,3.53,24.18,12915.0,60850.0,365850.0,303.00,-82.85,72.0,X-SC,1.18,97.0,4.71,2.57,39.96,X40N,NTT,FINANCE
65,SIEMENS,-0.25,-4.16,30.96,25.51,55217.0,-7745.0,178350.0,4671.50,49.82,68.0,H-LC,1.52,51.0,-0.14,1.25,26.94,AR,ATH,ELECTRICAL
24,DMART,-0.86,6.61,21.57,29.60,57395.0,16488.0,266088.0,5391.45,-10.15,66.0,X-LC,3.66,14.0,0.29,1.87,21.62,X40N,ATH,FMCG
59,RELIANCE,0.07,-13.66,45.13,25.30,78303.0,-27458.0,173505.0,1952.00,-15.80,46.0,X-LC,5.32,21.0,-0.35,1.22,8.96,XY25,BTT,REFINERIES
78,UNITDSPR,0.36,-7.67,30.80,20.77,66586.0,-17957.0,216187.0,1644.00,-18.18,45.0,X-MC,6.39,64.0,-0.27,1.52,3.13,X40N,NTT,BREWERIES

In [19]:
# top 5 to accumulate based on lowest Gained%
df_tmp = df_portfolio_features[df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])].sort_values(by = 'Gained%', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
2,ABBOTINDIA,-0.42,-13.23,36.07,18.07,55977.0,-23665.0,155190.0,35195.0,-26.09,44.0,X-MC,11.67,58.0,-0.42,1.09,1.49,X40,ATH,PHARMA
78,UNITDSPR,0.36,-7.67,30.80,20.77,66586.0,-17957.0,216187.0,1644.0,-18.18,45.0,X-MC,6.39,64.0,-0.27,1.52,3.13,X40N,NTT,BREWERIES
21,DABUR,-1.43,-16.51,72.11,43.70,149354.0,-40949.0,207119.0,735.0,-24.27,42.0,X-MC,14.56,70.0,-0.27,1.46,4.04,XY24,BTT,FMCG
35,HINDUNILVR,-0.81,-16.74,36.53,13.67,78182.0,-43043.0,214020.0,2922.0,-38.12,48.0,X-LC,11.90,9.0,-0.55,1.51,4.29,XY25,NTT,FMCG
45,ITC,0.48,-20.06,48.93,19.06,133058.0,-68230.0,271936.0,452.0,-56.33,51.0,X-LC,19.37,1.0,-0.51,1.91,5.49,X40,NTT,FMCG

In [20]:
# top 5 to accumulate based on lowest CurrAlloc%
df_tmp = df_portfolio_features[df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])].sort_values(by = 'CurrAlloc%', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
58,RELAXO,-0.03,-60.50,285.57,52.31,163746.0,-87820.0,57340.0,1176.00,-57.99,57.0,X-SC,32.91,92.0,-0.54,0.40,28.21,X40N,NTT,FOOTWEAR
12,BATAINDIA,0.93,-51.79,180.46,35.20,111939.0,-66640.0,62030.0,2096.00,-18.70,60.0,X-SC,33.29,91.0,-0.60,0.44,23.02,X40,NTT,FOOTWEAR
54,QUESS,0.52,-19.53,116.11,73.90,99780.0,-20857.0,85936.0,424.00,-56.47,60.0,X-SC,20.87,80.0,-0.21,0.60,15.60,XY24,NTT,MISC
2,ABBOTINDIA,-0.42,-13.23,36.07,18.07,55977.0,-23665.0,155190.0,35195.00,-26.09,44.0,X-MC,11.67,58.0,-0.42,1.09,1.49,X40,ATH,PHARMA
53,PGHH,-0.13,-25.91,78.17,32.01,123665.0,-55320.0,158200.0,17616.87,-49.95,44.0,X-MC,21.62,57.0,-0.45,1.11,8.20,X40,ATH,FMCG

In [21]:
# top 5 to accumulate based on CumlRnk
df_tmp = df_portfolio_features.sort_values(by = 'CumlRnk', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
45,ITC,0.48,-20.06,48.93,19.06,133058.0,-68230.0,271936.0,452.00,-56.33,51.0,X-LC,19.37,1.0,-0.51,1.91,5.49,X40,NTT,FMCG
73,TCS,0.86,-24.35,67.32,26.57,235920.0,-112828.0,350445.0,4311.59,-36.09,55.0,X-LC,17.32,2.0,-0.48,2.46,9.37,X40,ATH,IT
43,INFY,0.90,-10.34,49.73,34.24,139503.0,-32367.0,280521.0,1972.00,-29.61,52.0,X-LC,13.69,3.0,-0.23,1.97,7.88,X40,NTT,IT
75,TMPV,-0.61,-19.03,68.68,36.58,197879.0,-67724.0,288117.0,600.00,-83.62,62.0,X-LC,11.25,4.0,-0.34,2.03,20.09,XY24,NTT,AUTO
33,HCLTECH,-0.19,-6.00,31.74,23.83,72181.0,-14510.0,227414.0,1908.19,-1.16,57.0,X-LC,8.56,8.0,-0.20,1.60,10.42,X40,ATH,IT

In [22]:
# top 5 for average up
df_tmp = df_portfolio_features[(df_portfolio_features['Dev%_200'] > 5)].sort_values(by = 'CurrAlloc%', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
67,SONACOMS,-0.53,0.79,38.01,39.09,38753.0,796.0,101955.0,804.02,-20.20,68.0,M-MC,9.00,193.0,0.02,0.72,44.23,AR,ATH,AUTO
69,SURYODAY,3.32,-18.04,50.13,23.03,73570.0,-32313.0,146758.0,216.00,60.09,64.0,H-SC,4.05,166.0,-0.44,1.03,25.16,XR,NTT,BANKS
26,FINCABLES,3.56,15.90,79.39,107.91,135847.0,23470.0,171114.0,1641.55,4.01,63.0,M-SC,1.87,220.0,0.17,1.20,28.74,OX40N,ATH,CABLES
65,SIEMENS,-0.25,-4.16,30.96,25.51,55217.0,-7745.0,178350.0,4671.50,49.82,68.0,H-LC,1.52,51.0,-0.14,1.25,26.94,AR,ATH,ELECTRICAL
11,BANDHANBNK,0.16,-16.28,129.83,92.42,302782.0,-45345.0,233214.0,400.00,99.71,60.0,H-SC,4.99,174.0,-0.15,1.64,28.47,XY24,NTT,BANKS

In [23]:
# top 5 RSP
df_tmp = df_portfolio_features.sort_values(by = 'RSP', ascending=False)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
80,VALIANTORG,7.88,-40.22,191.33,74.15,187123.0,-65804.0,97801.0,838.00,-275.92,67.0,H-SC,19.89,145.0,-0.35,0.69,45.54,XR,NTT,CHEMICALS
5,ANGELONE,-1.71,19.95,3.53,24.18,12915.0,60850.0,365850.0,303.00,-82.85,72.0,X-SC,1.18,97.0,4.71,2.57,39.96,X40N,NTT,FINANCE
52,PAGEIND,1.51,-3.29,38.67,34.11,100372.0,-8819.0,259560.0,51418.64,-30.66,74.0,X-MC,15.73,55.0,-0.09,1.83,22.78,X40,ATH,APPARELS
55,RAJESHEXPO,5.00,-75.46,307.71,0.07,103600.0,-103509.0,33668.0,518.00,1133.59,64.0,L-SC,43.08,268.0,-1.00,0.24,58.06,OX40N,NTT,JEWELLERY
67,SONACOMS,-0.53,0.79,38.01,39.09,38753.0,796.0,101955.0,804.02,-20.20,68.0,M-MC,9.00,193.0,0.02,0.72,44.23,AR,ATH,AUTO

In [24]:
# Top N allocation
df_tmp = df_portfolio_features.sort_values(by = 'CurrAlloc%', ascending=False)
top_n_values = [10, 25, 50]

sum_df = pd.DataFrame({
    'Top_N': top_n_values,
    'Sum_Alloc%': [df_tmp['CurrAlloc%'].head(n).sum() for n in top_n_values]
})

sum_df

   Top_N  Sum_Alloc%
0     10       21.02
1     25       45.64
2     50       77.62

In [25]:
# market-cap-wise allocation
df_tmp = df_portfolio_features[cols]
df_tmp.groupby(df_tmp['Conviction'].str[-2:])['CurrAlloc%'].sum().sort_values(ascending=False)

Conviction
SC    45.42
MC    29.43
LC    25.15
Name: CurrAlloc%, dtype: float64

In [26]:
# criteria-wise allocation
df_portfolio_features.groupby('Criteria')['CurrAlloc%'].sum().sort_values(ascending=False)

Criteria
XY24     27.24
X40      24.55
X40N     15.76
AR        9.33
XR        8.48
XY25      7.02
OX40N     6.83
SR        0.79
Name: CurrAlloc%, dtype: float64

In [27]:
# conviction-wise allocation
df_portfolio_features.groupby('Conviction')['CurrAlloc%'].sum().sort_values(ascending=False)

Conviction
X-LC    22.87
H-SC    22.20
X-MC    21.91
X-SC    12.44
M-SC    10.16
H-MC     5.05
M-MC     2.13
H-LC     1.25
M-LC     1.03
L-SC     0.62
L-MC     0.34
Name: CurrAlloc%, dtype: float64

In [28]:
# sector-wise stats
df_tmp = df_portfolio_features.groupby('Category')[['CurrAlloc%', 'Current', 'Current P/L', 'FTT Amt']].sum().sort_values(by=['Current', 'Current P/L'], ascending=False)
df_tmp['Current P/L%'] = round(df_tmp['Current P/L'] * 100 / df_tmp['Current'], 2)
df_tmp['FTT%'] = round(df_tmp['FTT Amt'] * 100 / df_tmp['Current'], 2)
cols = ['CurrAlloc%', 'Current P/L%', 'FTT%']
df_tmp[cols].sort_values(by=['CurrAlloc%'], ascending=False)

               CurrAlloc%  Current P/L%    FTT%
Category
FMCG                14.55        -20.74   63.58
FINANCE             13.48        -12.09   57.77
IT                  11.72        -35.14  103.90
MISC                 7.19        -31.21   88.21
ELECTRICAL           6.60         -3.18   42.68
PAINTS               5.33        -30.05   52.63
INSURANCE            4.58         -4.07   39.69
BANKS                4.58        -18.18   78.17
PHARMA               3.91         -5.72   38.99
AUTO                 3.86        -19.27   66.59
AC                   2.01        -11.68   41.97
HEALTHCARE           1.94        -29.83   63.71
FOOTWEAR             1.84        -69.07  136.86
APPARELS             1.83         -3.40   38.67
TRAVEL               1.82        -73.14  159.83
DURABLES             1.74        -56.30   94.33
BREWERIES            1.52         -8.31   30.80
REALTY               1.45         -7.70   25.39
CERAMICS             1.35        -59.90  108.47
REFINERIES           1.22        -15.83   45.13
CEMENT               1.22        -54.84  170.69
CABLES               1.20         13.72   79.39
ENGINEERING          1.19        -43.58  109.25
CHEMICALS            1.12        -66.21  201.82
JEWELLERY            1.11       -102.67  173.08
ENTERTAINMENT        0.81        -67.76  167.81
TEXTILES             0.45        -44.21   85.33
HOTELS               0.38       -111.82  186.53

In [29]:
# money to be made criteria-wise
df_portfolio_features.groupby('Criteria')['FTT Amt'].agg(['sum', 'count']).sort_values(by='sum', ascending=False)

                sum  count
Criteria
XY24      3727096.0     21
X40       1682007.0     16
XR        1286934.0     12
AR        1245775.0     10
X40N      1058616.0     10
OX40N      818229.0     10
XY25       443478.0      5
SR         306721.0      2

In [30]:
# money to be made conviction-wise
df_portfolio_features.groupby('Conviction')['FTT Amt'].agg(['sum', 'count']).sort_values(by='sum', ascending=False)

                  sum  count
Conviction
H-SC        3635921.0     24
X-MC        1620460.0     15
X-LC        1523671.0     13
M-SC        1474329.0     14
X-SC        1411792.0     10
H-MC         360190.0      3
L-SC         203591.0      2
M-LC         145734.0      1
M-MC          83613.0      2
H-LC          55217.0      1
L-MC          54338.0      1

In [31]:
# money to be made criteria and conviction-wise
df_portfolio_features.groupby(['Conviction', 'Criteria'])['FTT Amt'].agg(['sum', 'count']).sort_values(by='sum', ascending=False)

                           sum  count
Conviction Criteria
H-SC       XY24      1224836.0      6
           AR         950853.0      5
M-SC       XY24       852675.0      6
X-LC       X40        835129.0      7
X-SC       XY24       826480.0      4
H-SC       XR         801522.0      7
X-MC       X40        640853.0      7
           X40N       489361.0      4
X-SC       X40N       379287.0      4
M-SC       OX40N      362640.0      5
H-SC       OX40N      351989.0      4
X-LC       XY24       342089.0      2
H-SC       SR         306721.0      2
X-MC       XY24       248113.0      2
           XY25       242133.0      2
H-MC       XY24       232903.0      1
X-SC       X40        206025.0      2
X-LC       X40N       189968.0      2
M-SC       XR         185349.0      2
X-LC       XY25       156485.0      2
M-LC       XR         145734.0      1
H-MC       AR         127287.0      2
L-SC       OX40N      103600.0      1
           XR          99991.0      1
M-SC       AR          73665.0      1
H-LC       AR          55217.0      1
L-MC       XR          54338.0      1
M-MC       XY25        44860.0      1
           AR          38753.0      1

In [32]:
# notebook execution time

end_time = time.time()
execution_time = round(end_time - start_time, 0)
print(f"Notebook execution time: {execution_time} seconds")

Notebook execution time: 24.0 seconds