<a href="https://colab.research.google.com/github/ankit-rathi/Quantvesting_v2/blob/main/myStocks_Portfolio_Analysis.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
'''
!pip install pandas==2.2.2 -qq
!pip install pyxirr -qq
!pip install ta -qq
!pip install yfinance==0.2.59 -qq
'''

'\n!pip install pandas==2.2.2 -qq\n!pip install pyxirr -qq\n!pip install ta -qq\n!pip install yfinance==0.2.59 -qq\n'

In [2]:
# import libraries

import numpy as np
import pandas as pd
import datetime
import warnings
warnings.filterwarnings('ignore')
import yfinance as yfin
import ta
import matplotlib.pyplot as plt
import requests

In [3]:
# notebook start time
import time
import datetime
import pytz

start_time = time.time()

# function to print date timestamp
def print_date_time():
  tz_NY = pytz.timezone('Asia/Kolkata')
  datetime_NY = datetime.datetime.now(tz_NY)
  print("Run date time (IST):", datetime_NY.strftime("%Y-%m-%d %H:%M:%S"))

In [4]:
# function to get booked and reserved amount
def get_amt():
  # fetch the JSON data from the URL
  url = "https://raw.githubusercontent.com/ankit-rathi/Tradevesting_v1/main/data/myPortfolioAmts.json"
  response = requests.get(url)
  pf_amts = response.json()  # parse the JSON data

  # extract values from the JSON
  py_booked_amt_dm = pf_amts["py_booked_amt_dm"]
  py_booked_amt_sv = pf_amts["py_booked_amt_sv"]
  cy_booked_amt_dm = pf_amts["cy_booked_amt_dm"]
  cy_booked_amt_sv = pf_amts["cy_booked_amt_sv"]
  reserve_amt_dm = pf_amts["reserve_amt_dm"]
  reserve_amt_sv = pf_amts["reserve_amt_sv"]

  # perform calculations
  py_booked_amt = py_booked_amt_dm + py_booked_amt_sv
  cy_booked_amt = cy_booked_amt_dm + cy_booked_amt_sv
  reserve_amt = reserve_amt_dm + reserve_amt_sv
  total_booked_amt = py_booked_amt + cy_booked_amt

  return total_booked_amt, reserve_amt, cy_booked_amt, py_booked_amt

gen_output = 0

In [5]:
# function to format the amount
def format_amt(number):
    abs_number = abs(number)

    if abs_number >= 1_00_00_000:  # Crores
        formatted_amt = f"{number / 1_00_00_000:.2f} C"
    elif abs_number >= 1_00_000:  # Lakhs
        formatted_amt = f"{number / 1_00_000:.2f} L"
    elif abs_number >= 1_000:  # Thousands
        formatted_amt = f"{number / 1_000:.2f} K"
    else:
        formatted_amt = f"{number:.2f}"

    return formatted_amt

# function to set start and end date
def get_start_end_date():
  start_date = (datetime.date.today() + datetime.timedelta(days=-365)).strftime('%Y-%m-%d')
  end_date = (datetime.date.today() + datetime.timedelta(days=1)).strftime('%Y-%m-%d')
  return start_date, end_date

# function to fetch my portfolio csv
def get_mypfs_df():
  mypfs_df = pd.read_csv('https://raw.githubusercontent.com/ankit-rathi/Tradevesting_v1/main/data/myPortfolioStocks.csv')
  return mypfs_df

# function to fetch my prospects csv
def get_mypps_df():
  mypps_df = pd.read_csv('https://raw.githubusercontent.com/ankit-rathi/Tradevesting_v1/main/data/myProspectsScrips.csv')
  return mypps_df

# function to fetch screener data
def get_myscreen_df():
  myscreen_df = pd.read_csv('https://raw.githubusercontent.com/ankit-rathi/Tradevesting_v1/main/data/myScreenerDB.csv')
  return myscreen_df

# function to fetch momentum data
def get_myinvmt_df():
  myinvmt_df = pd.read_csv('https://raw.githubusercontent.com/ankit-rathi/Tradevesting_v1/main/data/myInvestments.csv')
  return myinvmt_df

# function to get the stock ids
def get_stock_ids(df_pf):
  stock_n100 = df_pf['Symbol'].unique()

  exclude = ['CADILAHC','MMTC', 'MASFIN']

  stock_ids = df_pf[~df_pf['Symbol'].isin(exclude) ]['Symbol'].unique()

  #mypf = mypf[mypf.Forecast.notnull()]
  #stock_ids = mypf['Symbol'].unique()

  #stock_ids.sort()
  return stock_ids

# get features from screener data
def get_screener_features():
  myscreen_df = get_myscreen_df()
  cols = ['Symbol', 'EPS', 'MedPE', 'ROCE%', 'ROE%', 'CapType']
  return myscreen_df[cols]

# get relative strength
def get_relative_strength(stock_list):

    # Dictionary to store stock tickers and their corresponding percentage price change
    stock_changes = {}

    # Loop through each stock and fetch its price data
    for stock in stock_list:
        try:
            # Download the stock data for the given date range
            stock_data = yfin.Ticker(stock + '.NS').history(period='1mo', interval='1d')[map(str.title, ['open', 'close', 'low', 'high', 'volume'])]

            # Calculate the percentage change for the stock
            if len(stock_data) > 0:
                start_price = stock_data['Close'].iloc[0]
                end_price = stock_data['Close'].iloc[-1]
                percent_change = round(((end_price - start_price) / start_price) * 100, 2)
                stock_changes[stock] = percent_change
            else:
                stock_changes[stock] = np.nan  # If no data is available, set to NaN

        except Exception as e:
            print(f"Error fetching data for {stock}: {e}")
            stock_changes[stock] = np.nan

    # Create a DataFrame with stock tickers and their percentage changes
    df = pd.DataFrame(list(stock_changes.items()), columns=['Symbol', 'Percent_Change'])

    # Drop any stocks with missing data (NaN values)
    df = df.dropna()

    # Calculate the percentile rank based on percentage change
    df['RSP'] = round(df['Percent_Change'].rank(pct=True) * 100, 2)
    cols = ['Symbol', 'RSP']
    df = df[cols]
    # Sort by percentile rank (optional)
    df = df.sort_values(by='RSP', ascending=False).reset_index(drop=True)

    return df

In [6]:
# function to get stock technicals
def stock_prec_dev(stock_symbol):
    #stock_symbol = 'ULTRACEMCO.NS'
    short_window = 20
    mid_window = 50
    long_window = 200
    moving_avg = 'SMA'

    start = datetime.datetime(*map(int, start_date.split('-')))
    end = datetime.datetime(*map(int, end_date.split('-')))

    stock_df = yfin.Ticker(stock_symbol + '.NS').history(period='max', interval='1d')[map(str.title, ['open', 'close', 'low', 'high', 'volume'])]

    stock_df['Max'] = round(max(stock_df['Close']),2)
    stock_df = stock_df[(stock_df.index <= end_date) & (stock_df.index >= start_date)]
    stock_df['200_SMA'] = round(stock_df['Close'].rolling(window = 200, min_periods = 1).mean(),0)
    stock_df['Dev%_200'] = round((stock_df['Close'] - stock_df['200_SMA'])*100/stock_df['200_SMA'],2)
    stock_df.dropna(axis = 0, inplace = True) # remove any null rows

    stock_df['20_SMA'] = stock_df['Close'].rolling(window=20).mean()
    stock_df['50_SMA'] = stock_df['Close'].rolling(window=50).mean()
    stock_df['Symbol'] = stock_symbol

    stock_df['Close'] = round(stock_df['Close'],2)
    stock_df['Min'] = round(min(stock_df['Close']),2)
    stock_df['RSI_14'] = ta.momentum.RSIIndicator(close=stock_df['Close'], window=14).rsi()
    stock_df['RSI_14'] = round(stock_df['RSI_14'],0)
    stock_df['Prev_Close'] = stock_df['Close'].shift(1)
    stock_df.drop(['Open', 'Low', 'High', 'Volume'], axis=1, inplace=True)
    stock_df = stock_df.tail(1)

    max_SMA = max(stock_df['20_SMA'].item(), stock_df['50_SMA'].item(), stock_df['200_SMA'].item())
    min_SMA = min(stock_df['20_SMA'].item(), stock_df['50_SMA'].item(), stock_df['200_SMA'].item())
    ABS_Spread = max_SMA - min_SMA
    stock_df['Spread%'] = round((ABS_Spread / stock_df['200_SMA'].item()) * 100,2)

    return stock_df

# function to compute stock attributes
def get_common_features(stock_ids, df_mypf):

  df_prec_dev = pd.DataFrame()
  df_tmp = get_screener_features()
  df_rs = get_relative_strength(stock_ids)

  for stock_id in stock_ids:
      tmp = stock_prec_dev(stock_id)
      tmp = tmp.reset_index()
      df_prec_dev = pd.concat([df_prec_dev, tmp], ignore_index = True)
  df_prec_dev = pd.merge(df_prec_dev, df_mypf, on= 'Symbol')
  df_prec_dev = pd.merge(df_prec_dev, df_tmp, on= 'Symbol', how='left')
  df_prec_dev = pd.merge(df_prec_dev, df_rs, on= 'Symbol', how='left')
  #print(df_prec_dev.columns)
  df_prec_dev['Curr_PE'] = round(df_prec_dev['Close']/df_prec_dev['EPS'],1)
  df_prec_dev['Dev%_PE'] = round((df_prec_dev['Curr_PE'] - df_prec_dev['MedPE'])*100/df_prec_dev['MedPE'],2)
  df_prec_dev['Conviction'] = df_prec_dev['Conviction'] + '-' + df_prec_dev['CapType']
  return df_prec_dev

# function to arrange stock features
def arrange_features(df_stocks, common_cols, diff_cols):
  df_stocks_common = df_stocks[common_cols].drop_duplicates()
  df_stocks_diff = df_stocks[diff_cols]
  df_stocks_diff['Investment'] = df_stocks_diff['AvgCost'] * df_stocks_diff['Shares']
  df_stocks_diff = df_stocks_diff.groupby(['Symbol'])[['Shares', 'Investment']].aggregate(['sum']).reset_index()
  df_stocks_diff.columns = ['Symbol', 'Shares', 'Investment']
  df_stocks_diff['AvgCost'] = round(df_stocks_diff['Investment']/df_stocks_diff['Shares'],2)
  df_stocks = pd.merge(df_stocks_diff, df_stocks_common, on='Symbol')
  return df_stocks

# plot fact distribution across dimension
def plot_pie_chart(df, dimension, fact):
  # grouping the data by category and calculating the sum of fact for each type
  grouped_data = df.groupby(dimension)[fact].sum()

  # sorting the grouped data in descending order
  grouped_data = grouped_data.sort_values(ascending=False)

  # creating a pie chart
  grouped_data.plot.pie(autopct='%1.1f%%', startangle=90, figsize=(6, 6))

  # adding a title and displaying the plot
  plt.title(f'{dimension} {fact} Distribution')
  plt.ylabel('')  # To hide the y-label
  plt.show()

In [7]:
# function to get portfolio features

def get_portfolio_features(df_common_features):

  print_date_time()
  print('-------------------')

  #df_common_features["Target"] = df_common_features["Target"].fillna(df_common_features["Max"])
  df_common_features['NTT'] = np.where(df_common_features['Strategy']== 'NTT', df_common_features["Target"], df_common_features['Max'])
  df_common_features['LTT'] = np.where(df_common_features['Strategy']== 'BTT', df_common_features["Target"], df_common_features['Max'])
  df_common_features['BOL'] = df_common_features['Min']

  tmp_df = df_common_features[df_common_features['Symbol'].isin(mypf_df[mypf_df['InPortfolio'] != 'NA'].Symbol.values)]
  print('qualified stocks: '+str(len(tmp_df['Symbol'].unique())))
  tmp_df1 = tmp_df[tmp_df['LatestQtr'] == 1]
  print('with latest results: '+str(len(tmp_df1['Symbol'].unique())))
  tmp_df1 = tmp_df1[tmp_df1['StarStock'] == 1]
  print('still star stocks: '+str(len(tmp_df1['Symbol'].unique())))
  tmp_df['Investment'] = tmp_df['AvgCost'] * tmp_df['Shares']
  tmp_df['Current'] = round(tmp_df['Close'] * tmp_df['Shares'],0)
  tmp_df['Previous'] = tmp_df['Prev_Close'] * tmp_df['Shares']
  tmp_df['EstimatedST'] = tmp_df['NTT'] * tmp_df['Shares']
  tmp_df['EstimatedLT'] = tmp_df['LTT'] * tmp_df['Shares']
  tmp_df['Current P/L'] = round((tmp_df['Current'] - tmp_df['Investment']),0)
  tmp_df['Today P/L%'] = round((tmp_df['Current'] - tmp_df['Previous'])*100/tmp_df['Previous'],2)
  tmp_df['Current P/L%'] = round((tmp_df['Current'] - tmp_df['Investment'])*100/tmp_df['Investment'],2)
  tmp_df['EstimatedST P/L%'] = round((tmp_df['EstimatedST'] - tmp_df['Investment'])*100/tmp_df['Investment'],2)
  tmp_df['EstimatedLT P/L%'] = round((tmp_df['EstimatedLT'] - tmp_df['Investment'])*100/tmp_df['Investment'],2)
  tmp_df['NTT%'] = round((tmp_df['NTT'] - tmp_df['Close'])*100/tmp_df['Close'],2)
  tmp_df['LTT%'] = round((tmp_df['LTT'] - tmp_df['Close'])*100/tmp_df['Close'],2)
  tmp_df['Gained%'] = round((tmp_df['Close'] - tmp_df['BOL'])*100/tmp_df['BOL'],2)
  investment = round(sum(tmp_df['AvgCost']*tmp_df['Shares']),0)
  current = round(sum(tmp_df['Close']*tmp_df['Shares']),0)
  tmp_df['InitAlloc%'] = round(tmp_df['Investment']*100/investment,2)
  tmp_df['CurrAlloc%'] = round(tmp_df['Current']*100/current,2)
  tmp_df['FTT'] = tmp_df['LTT']
  tmp_df.loc[tmp_df['Strategy'] == 'NTT', 'FTT'] = tmp_df['NTT']
  tmp_df['FTT%'] = tmp_df['LTT%']
  tmp_df.loc[tmp_df['Strategy'] == 'NTT', 'FTT%'] = tmp_df['NTT%']
  tmp_df['FTT Amt'] = round(tmp_df['FTT%'] * tmp_df['Current']/100,0)
  tmp_df['OTT%'] = round((tmp_df['FTT'] - tmp_df['AvgCost'])*100/tmp_df['AvgCost'],2)
  tmp_df['RRR Ind'] = round(tmp_df['Current P/L']/tmp_df['FTT Amt'],2)
  tmp_df['Risk Ind'] = round(tmp_df['Current P/L%']*tmp_df['CurrAlloc%'],0)

  return tmp_df

# function to print portfolio features
def print_portfolio_stats(df_portfolio_features, myinvmt_df):
  from pyxirr import xirr

  total_booked_amt, reserve_amt, cy_booked_amt, py_booked_amt = get_amt()

  dates = myinvmt_df['Date'].values
  dates = np.append(dates, datetime.date.today().strftime('%d-%b-%y'))
  investment = myinvmt_df['Investment'].values
  dates= pd.to_datetime(dates)

  current = round(sum(df_portfolio_features['Close']*df_portfolio_features['Shares']),0) + reserve_amt
  investment_xirr = np.append(investment, current)
  cagr = round(xirr(pd.DataFrame({"dates": dates, "amounts": investment_xirr}))*100,2)

  investment = -sum(investment)
  invested = round(sum(df_portfolio_features['AvgCost']*df_portfolio_features['Shares']),0) + reserve_amt
  previous = round(sum(df_portfolio_features['Prev_Close']*df_portfolio_features['Shares']),0) + reserve_amt
  cy_invested = investment + py_booked_amt

  today_pnl_amount = current-previous
  today_pnl_percentage = round((current-previous)*100/previous,2)

  curr_pnl_amount = current-invested
  curr_pnl_percentage = round((curr_pnl_amount)*100/(cy_invested),2)

  cy_pnl_amount = cy_booked_amt + curr_pnl_amount
  cy_pnl_percentage = round((cy_pnl_amount)*100/cy_invested,2)

  overall_pnl_amount = total_booked_amt + curr_pnl_amount
  overall_pnl_percentage = round((overall_pnl_amount)*100/investment,2)

  estimate_st = round(sum(df_portfolio_features['FTT']*df_portfolio_features['Shares']),0)  + reserve_amt
  est_st_pnl_amount = estimate_st-current
  est_st_pnl_percentage = round((est_st_pnl_amount)*100/current,2)

  estimate_lt = round(sum(df_portfolio_features['LTT']*df_portfolio_features['Shares']),0)  + reserve_amt
  est_lt_pnl_amount = estimate_lt-current
  est_lt_pnl_percentage = round((est_lt_pnl_amount)*100/current,2)

  total_profit = round(sum(df_portfolio_features[df_portfolio_features['Current P/L%'] > 0]['Current']) - sum(df_portfolio_features[df_portfolio_features['Current P/L%'] > 0]['Investment']),0)
  total_loss = round(sum(df_portfolio_features[df_portfolio_features['Current P/L%'] < 0]['Current']) - sum(df_portfolio_features[df_portfolio_features['Current P/L%'] < 0]['Investment']),0)

  cy_booked_percentage = round((cy_booked_amt)*100/current,2)
  py_booked_percentage = round((py_booked_amt)*100/investment,2)
  total_booked_percentage = round((total_booked_amt)*100/investment,2)

  print('-------------------')
  print('Initial Investment: ', format_amt(investment))
  print('CY Investment: ', format_amt(cy_invested))
  print('Reserve: ', format_amt(reserve_amt))
  print('Current: ',  format_amt(current))
  print('-------------------')
  print('Today PnL: '+ '{} ({}%)'.format(format_amt(today_pnl_amount), today_pnl_percentage))
  print('Current PnL: '+ '{} ({}%)'.format(format_amt(curr_pnl_amount), curr_pnl_percentage))
  print('CY Booked + Current PnL: '+ '{} ({}%)'.format(format_amt(cy_pnl_amount), cy_pnl_percentage))
  print('-------------------')
  print('Total profit: ', format_amt(total_profit))
  print('Total loss: ', format_amt(total_loss))
  print('-------------------')
  print('Total Booked + Current PnL: '+ '{} ({}%)'.format(format_amt(overall_pnl_amount), overall_pnl_percentage))
  print('Total Booked PnL: '+ '{} ({}%)'.format(format_amt(total_booked_amt), total_booked_percentage))
  print('Curr Year Booked PnL: '+ '{} ({}%)'.format(format_amt(cy_booked_amt), cy_booked_percentage))
  print('Prev Year Booked PnL: '+ '{} ({}%)'.format(format_amt(py_booked_amt), py_booked_percentage))
  print('===================')
  print('Est FTT: ',  format_amt(estimate_st))
  print('Est FTT PnL: '+ '{} ({}%)'.format(format_amt(est_st_pnl_amount), est_st_pnl_percentage))

  print('===================')
  print('Deployed: ', format_amt(investment))

  print('Current: ', format_amt(current))

  print('CAGR/XIRR %: '+'{}%'.format(cagr))

In [8]:
# get start and end date
start_date, end_date = get_start_end_date()

# get portfolio and prospects data
mypfs_df = get_mypfs_df()
mypps_df = get_mypps_df()
myinvmt_df = get_myinvmt_df()

# merge above datasets
mypf_df = pd.merge(mypfs_df, mypps_df, on="Symbol")

# seggregate dm and sv portfolio
dm_pf = mypf_df[mypf_df['InPortfolio'] == 'DM']
sv_pf = mypf_df[mypf_df['InPortfolio'] == 'SV']

# build portfolio stock dataframe
dm_stocks = get_stock_ids(dm_pf)
sv_stocks = get_stock_ids(sv_pf)
df_stocks = pd.concat([dm_pf,sv_pf], ignore_index = True)

# arrange common and diff stock features
common_cols = ['Symbol', 'Target', 'Criteria', 'Strategy', 'CumlRnk', 'LatestQtr', 'StarStock', 'Conviction', 'Category', 'InFolio', 'XIRR', 'MBQ']
diff_cols = ['Symbol', 'AvgCost', 'Shares']
df_stocks = arrange_features(df_stocks, common_cols, diff_cols)

# get common features
stock_ids = df_stocks['Symbol'].values
df_common_features = get_common_features(stock_ids, df_stocks)

df_common_features.reset_index(drop=True, inplace=True)
df_common_features.drop(['Date'], axis=1, inplace=True)
# get and print portfolio features
df_portfolio_features = get_portfolio_features(df_common_features)

print_portfolio_stats(df_portfolio_features, myinvmt_df)

df = df_portfolio_features
#plot_pie_chart(df, 'CapType', 'Current')
list_ox40n = list(df[df['MBQ'].str.contains('OX40N', na=False)]['Symbol'].values)

Run date time (IST): 2026-06-02 12:11:37
-------------------
qualified stocks: 92
with latest results: 31
still star stocks: 20

-------------------
Initial Investment:  1.40 C
CY Investment:  1.82 C
Reserve:  1.49 K
Current:  1.48 C
-------------------
Today PnL: 1.01 K (0.01%)
Current PnL: -35.58 L (-19.51%)
CY Booked + Current PnL: -33.50 L (-18.37%)
-------------------
Total profit:  1.86 L
Total loss:  -37.44 L
-------------------
Total Booked + Current PnL: 9.37 L (6.72%)
Total Booked PnL: 44.95 L (32.22%)
Curr Year Booked PnL: 2.08 L (1.41%)
Prev Year Booked PnL: 42.87 L (30.73%)
===================
Est FTT:  2.55 C
Est FTT PnL: 1.08 C (72.9%)
===================
Deployed:  1.40 C
Current:  1.48 C
CAGR/XIRR %: 2.69%

In [9]:
# top 5 near their targets
cols = ['Symbol', 'Today P/L%', 'Current P/L%', 'FTT%', 'OTT%', 'FTT Amt', 'Current P/L', 'Current', 'FTT', 'Dev%_PE', 'RSI_14','Conviction', 'Spread%',  'CumlRnk', 'RRR Ind', 'CurrAlloc%', 'Gained%', 'Criteria', 'Strategy', 'Category']
df_tmp = df_portfolio_features[~df_portfolio_features['Symbol'].isin(['ENRIN','BLUSPRING','DIGITIDE'])]
df_tmp = df_tmp.sort_values(by = 'FTT Amt', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
59,PIDILITIND,-1.45,1.76,16.31,18.37,23421.0,2490.0,143600.0,1670.26,-28.76,48.0,X-LC,4.54,5.0,0.11,0.97,12.75,X40,ATH,CHEMICALS
55,MASFIN,1.43,-5.43,28.55,21.57,26453.0,-5325.0,92655.0,397.04,-18.25,43.0,H-SC,2.71,167.0,-0.20,0.63,10.44,XR,ATH,FINANCE
51,KOTAKBANK,-0.03,0.81,20.13,21.11,28102.0,1128.0,139601.0,453.24,-13.31,45.0,X-LC,7.30,12.0,0.04,0.95,6.76,X40,ATH,BANKS
83,TTKPRESTIG,0.88,-29.05,41.06,0.09,29360.0,-29271.0,71506.0,770.00,66.06,60.0,M-SC,15.10,250.0,-1.00,0.48,27.33,OX40N,NTT,DURABLES
72,SIS,-1.14,-7.46,31.03,21.26,31884.0,-8280.0,102752.0,528.00,2446.11,64.0,H-SC,18.44,168.0,-0.26,0.70,52.78,OX40N,NTT,MISC

In [10]:
# top 5 today
df_tmp = df_portfolio_features.sort_values(by = 'Today P/L%', ascending=False)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
3,ALKYLAMINE,6.10,-27.53,167.17,93.63,122323.0,-27790.0,73173.0,4546.37,-22.40,55.0,H-SC,10.40,142.0,-0.23,0.50,38.17,SR,ATH,CHEMICALS
79,TCS,6.07,-28.46,74.57,24.88,247129.0,-131868.0,331405.0,4253.91,-39.36,62.0,X-LC,17.89,2.0,-0.53,2.25,9.97,X40,ATH,IT
67,ROUTE,5.99,-59.45,314.65,68.16,169798.0,-79102.0,53964.0,2215.45,-67.06,57.0,H-SC,21.64,141.0,-0.47,0.37,28.56,SR,ATH,IT
45,INFY,5.96,-13.26,54.76,34.24,148621.0,-41483.0,271405.0,1972.00,-31.79,66.0,X-LC,18.26,3.0,-0.28,1.84,16.37,X40,NTT,IT
13,BSOFT,5.14,-37.52,141.32,50.79,124200.0,-52767.0,87886.0,831.70,-19.98,53.0,H-SC,13.20,172.0,-0.42,0.60,11.32,XR,ATH,IT

In [11]:
# bottom 5 today
df_tmp = df_portfolio_features.sort_values(by = 'Today P/L%', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
61,RAJESHEXPO,-5.00,-79.37,385.02,0.07,108968.0,-108875.0,28302.0,518.00,937.88,42.0,L-SC,31.07,268.0,-1.00,0.19,32.87,OX40N,NTT,JEWELLERY
43,INDIGOPNTS,-3.42,-31.54,46.10,0.02,55092.0,-55054.0,119505.0,1408.00,82.48,54.0,M-SC,15.85,222.0,-1.00,0.81,35.59,OX40N,NTT,PAINTS
28,GODREJCP,-2.98,-12.39,50.07,31.47,65188.0,-18420.0,130194.0,1469.04,-7.84,35.0,X-LC,9.36,32.0,-0.28,0.88,0.00,X40N,ATH,FMCG
63,RECLTD,-2.88,-12.87,38.57,20.74,68276.0,-26152.0,177018.0,446.00,-4.30,31.0,M-MC,3.17,191.0,-0.38,1.20,5.49,XY25,NTT,FINANCE
91,ZYDUSLIFE,-2.64,12.03,21.06,35.63,49447.0,25216.0,234790.0,1286.17,-2.70,64.0,H-MC,7.23,120.0,0.51,1.59,23.45,AR,ATH,PHARMA

In [12]:
# top 5 to exit based on CumlRnk
df_tmp = df_portfolio_features[~df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])]
df_tmp = df_tmp[(df_tmp['Current P/L%'] > -1) & (df_tmp['Current P/L%'] < 1)].sort_values(by = 'CumlRnk', ascending=False)
df_tmp[cols].head()

Empty DataFrame
Columns: [Symbol, Today P/L%, Current P/L%, FTT%, OTT%, FTT Amt, Current P/L, Current, FTT, Dev%_PE, RSI_14, Conviction, Spread%, CumlRnk, RRR Ind, CurrAlloc%, Gained%, Criteria, Strategy, Category]
Index: []

In [13]:
# OX40N stocks to exit
df_tmp = df_portfolio_features[(df_portfolio_features['Symbol'].isin(list_ox40n))].sort_values(by = 'Current P/L%', ascending=False)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
25,FINCABLES,-1.28,23.74,68.02,107.91,124272.0,35055.0,182699.0,1641.55,11.11,42.0,M-SC,27.61,220.0,0.28,1.24,37.45,OX40N,ATH,CABLES
72,SIS,-1.14,-7.46,31.03,21.26,31884.0,-8280.0,102752.0,528.00,2446.11,64.0,H-SC,18.44,168.0,-0.26,0.70,52.78,OX40N,NTT,MISC
16,CERA,-0.47,-27.35,70.54,23.89,90142.0,-48115.0,127788.0,9475.00,-29.83,49.0,H-SC,6.99,153.0,-0.53,0.87,22.80,OX40N,NTT,CERAMICS
50,KANSAINER,-0.27,-28.40,58.49,13.47,112931.0,-76590.0,193077.0,340.00,-38.54,55.0,H-SC,11.27,162.0,-0.68,1.31,34.87,XY24,NTT,PAINTS
83,TTKPRESTIG,0.88,-29.05,41.06,0.09,29360.0,-29271.0,71506.0,770.00,66.06,60.0,M-SC,15.10,250.0,-1.00,0.48,27.33,OX40N,NTT,DURABLES

In [14]:
# top 5 to book for rotation
df_tmp = df_portfolio_features[(df_portfolio_features['Current P/L%'] > 20) ].sort_values(by = 'CumlRnk', ascending=False)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
25,FINCABLES,-1.28,23.74,68.02,107.91,124272.0,35055.0,182699.0,1641.55,11.11,42.0,M-SC,27.61,220.0,0.28,1.24,37.45,OX40N,ATH,CABLES
68,SATIN,3.16,26.63,19.91,51.83,69655.0,73565.0,349849.0,274.00,13.01,69.0,H-SC,39.05,159.0,1.06,2.37,70.43,XY24,NTT,FINANCE

In [15]:
# top 5 to monitor for exit
df_tmp = df_portfolio_features[~df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])]
df_tmp = df_tmp[(df_tmp['Current P/L%'] > 0) ].sort_values(by = 'Dev%_PE', ascending=False)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
74,STARHEALTH,-1.72,1.36,45.28,47.26,129024.0,3824.0,284947.0,761.00,59.94,57.0,H-SC,9.79,173.0,0.03,1.93,25.10,XY24,NTT,INSURANCE
68,SATIN,3.16,26.63,19.91,51.83,69655.0,73565.0,349849.0,274.00,13.01,69.0,H-SC,39.05,159.0,1.06,2.37,70.43,XY24,NTT,FINANCE
25,FINCABLES,-1.28,23.74,68.02,107.91,124272.0,35055.0,182699.0,1641.55,11.11,42.0,M-SC,27.61,220.0,0.28,1.24,37.45,OX40N,ATH,CABLES
91,ZYDUSLIFE,-2.64,12.03,21.06,35.63,49447.0,25216.0,234790.0,1286.17,-2.70,64.0,H-MC,7.23,120.0,0.51,1.59,23.45,AR,ATH,PHARMA
73,SONACOMS,-0.09,3.74,34.08,39.09,35763.0,3780.0,104939.0,804.02,-17.77,55.0,M-MC,18.79,193.0,0.11,0.71,48.45,AR,ATH,AUTO

In [16]:
# top 5 to book for rotation from weak conviction
df_tmp = df_portfolio_features[~df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])]
df_tmp = df_tmp[~df_tmp['Criteria'].isin(['XY25','XY24','X40', 'X40N'])].sort_values(by = 'RRR Ind', ascending=False)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
91,ZYDUSLIFE,-2.64,12.03,21.06,35.63,49447.0,25216.0,234790.0,1286.17,-2.70,64.0,H-MC,7.23,120.0,0.51,1.59,23.45,AR,ATH,PHARMA
25,FINCABLES,-1.28,23.74,68.02,107.91,124272.0,35055.0,182699.0,1641.55,11.11,42.0,M-SC,27.61,220.0,0.28,1.24,37.45,OX40N,ATH,CABLES
73,SONACOMS,-0.09,3.74,34.08,39.09,35763.0,3780.0,104939.0,804.02,-17.77,55.0,M-MC,18.79,193.0,0.11,0.71,48.45,AR,ATH,AUTO
42,INDIAMART,-0.89,-15.55,144.79,106.72,150807.0,-19180.0,104156.0,4810.62,-61.91,35.0,H-SC,11.05,140.0,-0.13,0.71,0.83,AR,ATH,MISC
90,WIPRO,1.04,-14.46,101.39,72.27,146957.0,-24506.0,144942.0,420.00,-22.68,64.0,M-LC,12.62,98.0,-0.17,0.98,11.20,XR,NTT,IT

In [17]:
# top 5 to accumulate based on lowest RSI_14
df_tmp = df_portfolio_features[df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])].sort_values(by = 'RSI_14', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
27,GLAXO,-1.61,-12.93,55.84,35.69,96894.0,-25764.0,173520.0,3380.16,-33.48,29.0,X-MC,6.91,56.0,-0.27,1.18,0.00,X40,ATH,PHARMA
47,ITC,0.04,-26.31,61.57,19.06,154329.0,-89510.0,250656.0,452.00,-59.56,29.0,X-LC,14.39,1.0,-0.58,1.70,0.04,X40,NTT,FMCG
40,ICICIPRULI,-2.18,-20.91,65.29,30.73,101730.0,-41193.0,155812.0,790.00,-42.12,29.0,X-MC,12.38,78.0,-0.40,1.06,0.00,X40,ATH,INSURANCE
36,HINDUNILVR,-0.84,-19.60,41.38,13.67,85520.0,-50393.0,206670.0,2922.00,-40.26,29.0,X-LC,7.03,9.0,-0.59,1.40,0.71,XY25,NTT,FMCG
23,DMART,-1.52,-3.61,34.45,29.60,82887.0,-9000.0,240600.0,5391.45,-18.71,30.0,X-LC,3.29,14.0,-0.11,1.63,9.97,X40N,ATH,FMCG

In [18]:
# top 5 to accumulate based on Spread and CumlRnk
df_tmp = df_portfolio_features[df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])]
df_tmp = df_tmp[(df_tmp['CumlRnk'] < 100)].sort_values(by = 'Spread%', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
23,DMART,-1.52,-3.61,34.45,29.60,82887.0,-9000.0,240600.0,5391.45,-18.71,30.0,X-LC,3.29,14.0,-0.11,1.63,9.97,X40N,ATH,FMCG
57,PAGEIND,-1.37,-4.24,39.50,33.59,101517.0,-11374.0,257005.0,51217.29,-31.29,46.0,X-MC,4.04,55.0,-0.11,1.74,22.05,X40,ATH,APPARELS
59,PIDILITIND,-1.45,1.76,16.31,18.37,23421.0,2490.0,143600.0,1670.26,-28.76,48.0,X-LC,4.54,5.0,0.11,0.97,12.75,X40,ATH,CHEMICALS
49,JSWINFRA,-0.20,-6.94,25.11,16.43,51822.0,-15395.0,206379.0,342.00,-20.31,51.0,X-MC,4.55,61.0,-0.30,1.40,16.66,X40N,NTT,REALTY
65,RELIANCE,-1.21,-16.29,49.69,25.30,83587.0,-32747.0,168216.0,1952.00,-18.49,35.0,X-LC,4.73,21.0,-0.39,1.14,0.00,XY25,BTT,REFINERIES

In [19]:
# top 5 to accumulate based on lowest Gained%
df_tmp = df_portfolio_features[df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])].sort_values(by = 'Gained%', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
27,GLAXO,-1.61,-12.93,55.84,35.69,96894.0,-25764.0,173520.0,3380.16,-33.48,29.0,X-MC,6.91,56.0,-0.27,1.18,0.00,X40,ATH,PHARMA
28,GODREJCP,-2.98,-12.39,50.07,31.47,65188.0,-18420.0,130194.0,1469.04,-7.84,35.0,X-LC,9.36,32.0,-0.28,0.88,0.00,X40N,ATH,FMCG
40,ICICIPRULI,-2.18,-20.91,65.29,30.73,101730.0,-41193.0,155812.0,790.00,-42.12,29.0,X-MC,12.38,78.0,-0.40,1.06,0.00,X40,ATH,INSURANCE
65,RELIANCE,-1.21,-16.29,49.69,25.30,83587.0,-32747.0,168216.0,1952.00,-18.49,35.0,X-LC,4.73,21.0,-0.39,1.14,0.00,XY25,BTT,REFINERIES
47,ITC,0.04,-26.31,61.57,19.06,154329.0,-89510.0,250656.0,452.00,-59.56,29.0,X-LC,14.39,1.0,-0.58,1.70,0.04,X40,NTT,FMCG

In [20]:
# top 5 to accumulate based on lowest CurrAlloc%
df_tmp = df_portfolio_features[df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])].sort_values(by = 'CurrAlloc%', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
10,BATAINDIA,-0.50,-57.37,217.14,35.20,119112.0,-73815.0,54855.0,2096.00,-28.09,31.0,X-SC,24.97,91.0,-0.62,0.37,8.79,X40,NTT,FOOTWEAR
64,RELAXO,-0.59,-57.80,260.90,52.31,159827.0,-83900.0,61260.0,1176.00,-55.09,62.0,X-SC,23.42,92.0,-0.52,0.42,36.97,X40N,NTT,FOOTWEAR
60,QUESS,0.30,-14.97,104.52,73.90,94906.0,-15991.0,90802.0,424.00,-54.27,53.0,X-SC,8.28,80.0,-0.17,0.62,23.78,XY24,NTT,MISC
28,GODREJCP,-2.98,-12.39,50.07,31.47,65188.0,-18420.0,130194.0,1469.04,-7.84,35.0,X-LC,9.36,32.0,-0.28,0.88,0.00,X40N,ATH,FMCG
53,M&M,0.26,-3.37,27.68,23.38,37094.0,-4671.0,134010.0,3802.40,-18.26,38.0,X-LC,8.93,25.0,-0.13,0.91,1.60,X40N,ATH,AUTO

In [21]:
# top 5 to accumulate based on CumlRnk
df_tmp = df_portfolio_features.sort_values(by = 'CumlRnk', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
47,ITC,0.04,-26.31,61.57,19.06,154329.0,-89510.0,250656.0,452.00,-59.56,29.0,X-LC,14.39,1.0,-0.58,1.70,0.04,X40,NTT,FMCG
79,TCS,6.07,-28.46,74.57,24.88,247129.0,-131868.0,331405.0,4253.91,-39.36,62.0,X-LC,17.89,2.0,-0.53,2.25,9.97,X40,ATH,IT
45,INFY,5.96,-13.26,54.76,34.24,148621.0,-41483.0,271405.0,1972.00,-31.79,66.0,X-LC,18.26,3.0,-0.28,1.84,16.37,X40,NTT,IT
81,TMPV,-1.27,-13.50,57.89,36.58,178185.0,-48041.0,307800.0,600.00,-82.53,59.0,X-LC,19.64,4.0,-0.27,2.09,28.29,XY24,NTT,AUTO
59,PIDILITIND,-1.45,1.76,16.31,18.37,23421.0,2490.0,143600.0,1670.26,-28.76,48.0,X-LC,4.54,5.0,0.11,0.97,12.75,X40,ATH,CHEMICALS

In [22]:
# top 5 for average up
df_tmp = df_portfolio_features[(df_portfolio_features['Dev%_200'] > 5)].sort_values(by = 'CurrAlloc%', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
44,INDUSINDBK,0.52,-33.12,98.71,32.89,50967.0,-25574.0,51633.0,1800.00,-343.00,51.0,L-MC,8.58,258.0,-0.50,0.35,27.09,XR,NTT,BANKS
18,COFFEEDAY,2.85,-33.48,103.36,35.27,78071.0,-38016.0,75533.0,80.00,-49.70,88.0,L-SC,23.35,266.0,-0.49,0.51,86.27,XR,NTT,HOTELS
72,SIS,-1.14,-7.46,31.03,21.26,31884.0,-8280.0,102752.0,528.00,2446.11,64.0,H-SC,18.44,168.0,-0.26,0.70,52.78,OX40N,NTT,MISC
73,SONACOMS,-0.09,3.74,34.08,39.09,35763.0,3780.0,104939.0,804.02,-17.77,55.0,M-MC,18.79,193.0,0.11,0.71,48.45,AR,ATH,AUTO
75,SURYODAY,1.58,-5.66,30.42,23.03,51389.0,-10139.0,168932.0,216.00,84.21,59.0,H-SC,19.15,166.0,-0.20,1.14,42.24,XR,NTT,BANKS

In [23]:
# top 5 RSP
df_tmp = df_portfolio_features.sort_values(by = 'RSP', ascending=False)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
18,COFFEEDAY,2.85,-33.48,103.36,35.27,78071.0,-38016.0,75533.0,80.00,-49.70,88.0,L-SC,23.35,266.0,-0.49,0.51,86.27,XR,NTT,HOTELS
68,SATIN,3.16,26.63,19.91,51.83,69655.0,73565.0,349849.0,274.00,13.01,69.0,H-SC,39.05,159.0,1.06,2.37,70.43,XY24,NTT,FINANCE
91,ZYDUSLIFE,-2.64,12.03,21.06,35.63,49447.0,25216.0,234790.0,1286.17,-2.70,64.0,H-MC,7.23,120.0,0.51,1.59,23.45,AR,ATH,PHARMA
69,SFL,-0.44,-40.59,113.13,26.63,176249.0,-106425.0,155793.0,1287.00,17.98,57.0,M-SC,9.04,242.0,-0.60,1.06,29.85,XY24,NTT,MISC
37,HONAUT,0.33,-8.77,65.86,51.31,115864.0,-16913.0,175925.0,58357.33,-24.12,65.0,X-SC,9.32,90.0,-0.15,1.19,33.66,X40N,ATH,ELECTRICAL

In [24]:
# Top N allocation
df_tmp = df_portfolio_features.sort_values(by = 'CurrAlloc%', ascending=False)
top_n_values = [10, 25, 50]

sum_df = pd.DataFrame({
    'Top_N': top_n_values,
    'Sum_Alloc%': [df_tmp['CurrAlloc%'].head(n).sum() for n in top_n_values]
})

sum_df

   Top_N  Sum_Alloc%
0     10       19.89
1     25       42.94
2     50       72.67

In [25]:
# market-cap-wise allocation
df_tmp = df_portfolio_features[cols]
df_tmp.groupby(df_tmp['Conviction'].str[-2:])['CurrAlloc%'].sum().sort_values(ascending=False)

Conviction
SC    43.08
LC    31.68
MC    25.28
Name: CurrAlloc%, dtype: float64

In [26]:
# criteria-wise allocation
df_portfolio_features.groupby('Criteria')['CurrAlloc%'].sum().sort_values(ascending=False)

Criteria
XY24     27.61
X40      25.30
X40N     16.94
XR        9.19
OX40N     6.91
AR        6.90
XY25      6.32
SR        0.87
Name: CurrAlloc%, dtype: float64

In [27]:
# conviction-wise allocation
df_portfolio_features.groupby('Conviction')['CurrAlloc%'].sum().sort_values(ascending=False)

Conviction
X-LC    29.45
H-SC    22.77
X-MC    20.29
M-SC     9.86
X-SC     9.75
H-MC     2.73
M-MC     1.91
H-LC     1.25
M-LC     0.98
L-SC     0.70
L-MC     0.35
Name: CurrAlloc%, dtype: float64

In [28]:
# sector-wise stats
df_tmp = df_portfolio_features.groupby('Category')[['CurrAlloc%', 'Current', 'Current P/L', 'FTT Amt']].sum().sort_values(by=['Current', 'Current P/L'], ascending=False)
df_tmp['Current P/L%'] = round(df_tmp['Current P/L'] * 100 / df_tmp['Current'], 2)
df_tmp['FTT%'] = round(df_tmp['FTT Amt'] * 100 / df_tmp['Current'], 2)
cols = ['CurrAlloc%', 'Current P/L%', 'FTT%']
df_tmp[cols].sort_values(by=['CurrAlloc%'], ascending=False)

               CurrAlloc%  Current P/L%    FTT%
Category
FMCG                14.81        -21.09   63.57
IT                  10.93        -39.72  109.58
FINANCE             10.80        -15.84   66.22
MISC                 6.92        -31.59   88.75
AUTO                 6.79         -9.43   50.45
BANKS                5.72         -7.53   57.26
PAINTS               5.55        -20.20   41.07
INSURANCE            5.19         -8.25   44.97
PHARMA               4.98         -0.78   32.23
ELECTRICAL           4.10        -16.81   58.04
CHEMICALS            2.13        -28.86  105.65
HEALTHCARE           2.00        -20.91   52.46
AC                   1.77        -22.28   55.44
FOOTWEAR             1.75        -71.07  139.67
APPARELS             1.74         -4.43   39.50
DURABLES             1.60        -63.11  102.78
TRAVEL               1.60        -89.28  184.06
BREWERIES            1.47         -8.14   30.60
REALTY               1.40         -7.46   25.11
CERAMICS             1.33        -56.69  104.30
ENGINEERING          1.28        -27.97   86.51
CABLES               1.24         19.19   68.02
REFINERIES           1.14        -19.47   49.69
CEMENT               1.10        -65.87  189.96
JEWELLERY            1.07       -102.21  172.46
ENTERTAINMENT        0.72        -83.84  193.49
HOTELS               0.51        -50.33  103.36
TEXTILES             0.40        -55.11   99.34

In [29]:
# money to be made criteria-wise
df_portfolio_features.groupby('Criteria')['FTT Amt'].agg(['sum', 'count']).sort_values(by='sum', ascending=False)

                sum  count
Criteria
XY24      3525127.0     21
X40       1952200.0     19
XR        1325139.0     13
X40N      1225398.0     13
AR        1164280.0      9
OX40N      772353.0     10
XY25       502956.0      5
SR         292121.0      2

In [30]:
# money to be made conviction-wise
df_portfolio_features.groupby('Conviction')['FTT Amt'].agg(['sum', 'count']).sort_values(by='sum', ascending=False)

                  sum  count
Conviction
H-SC        3427251.0     24
X-LC        1945747.0     21
X-MC        1725423.0     15
M-SC        1462808.0     14
X-SC        1365453.0      9
H-MC         295017.0      2
L-SC         187039.0      2
M-LC         146957.0      1
M-MC         104039.0      2
L-MC          50967.0      1
H-LC          48873.0      1

In [31]:
# money to be made criteria and conviction-wise
df_portfolio_features.groupby(['Conviction', 'Criteria'])['FTT Amt'].agg(['sum', 'count']).sort_values(by='sum', ascending=False)

                           sum  count
Conviction Criteria
H-SC       XY24      1050879.0      6
X-LC       X40       1010794.0     10
H-SC       AR         952519.0      5
M-SC       XY24       853367.0      6
X-SC       XY24       812316.0      4
H-SC       XR         807624.0      7
X-MC       X40        726058.0      7
           X40N       499361.0      4
X-LC       X40N       388248.0      6
M-SC       OX40N      339277.0      5
X-SC       X40N       337789.0      3
X-LC       XY24       328564.0      2
H-SC       OX40N      324108.0      4
           SR         292121.0      2
X-MC       XY25       265573.0      2
H-MC       XY24       245570.0      1
X-MC       XY24       234431.0      2
X-SC       X40        215348.0      2
M-SC       XR         192486.0      2
X-LC       XY25       169107.0      2
M-LC       XR         146957.0      1
L-SC       OX40N      108968.0      1
           XR          78071.0      1
M-SC       AR          77678.0      1
M-MC       XY25        68276.0      1
L-MC       XR          50967.0      1
H-MC       AR          49447.0      1
X-LC       XR          49034.0      1
H-LC       AR          48873.0      1
M-MC       AR          35763.0      1

In [32]:
# notebook execution time

end_time = time.time()
execution_time = round(end_time - start_time, 0)
print(f"Notebook execution time: {execution_time} seconds")

Notebook execution time: 35.0 seconds