<a href="https://colab.research.google.com/github/ankit-rathi/Quantvesting_v2/blob/main/myStocks_Portfolio_Analysis.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
'''
!pip install pandas==2.2.2 -qq
!pip install pyxirr -qq
!pip install ta -qq
!pip install yfinance==0.2.59 -qq
'''

'\n!pip install pandas==2.2.2 -qq\n!pip install pyxirr -qq\n!pip install ta -qq\n!pip install yfinance==0.2.59 -qq\n'

In [2]:
# import libraries

import numpy as np
import pandas as pd
import datetime
import warnings
warnings.filterwarnings('ignore')
import yfinance as yfin
import ta
import matplotlib.pyplot as plt
import requests

In [3]:
# notebook start time
import time
import datetime
import pytz

start_time = time.time()

# function to print date timestamp
def print_date_time():
  tz_NY = pytz.timezone('Asia/Kolkata')
  datetime_NY = datetime.datetime.now(tz_NY)
  print("Run date time (IST):", datetime_NY.strftime("%Y-%m-%d %H:%M:%S"))

In [4]:
# function to get booked and reserved amount
def get_amt():
  # fetch the JSON data from the URL
  url = "https://raw.githubusercontent.com/ankit-rathi/Tradevesting_v1/main/data/myPortfolioAmts.json"
  response = requests.get(url)
  pf_amts = response.json()  # parse the JSON data

  # extract values from the JSON
  py_booked_amt_dm = pf_amts["py_booked_amt_dm"]
  py_booked_amt_sv = pf_amts["py_booked_amt_sv"]
  cy_booked_amt_dm = pf_amts["cy_booked_amt_dm"]
  cy_booked_amt_sv = pf_amts["cy_booked_amt_sv"]
  reserve_amt_dm = pf_amts["reserve_amt_dm"]
  reserve_amt_sv = pf_amts["reserve_amt_sv"]

  # perform calculations
  py_booked_amt = py_booked_amt_dm + py_booked_amt_sv
  cy_booked_amt = cy_booked_amt_dm + cy_booked_amt_sv
  reserve_amt = reserve_amt_dm + reserve_amt_sv
  total_booked_amt = py_booked_amt + cy_booked_amt

  return total_booked_amt, reserve_amt, cy_booked_amt, py_booked_amt

gen_output = 0

In [5]:
# function to format the amount
def format_amt(number):
    abs_number = abs(number)

    if abs_number >= 1_00_00_000:  # Crores
        formatted_amt = f"{number / 1_00_00_000:.2f} C"
    elif abs_number >= 1_00_000:  # Lakhs
        formatted_amt = f"{number / 1_00_000:.2f} L"
    elif abs_number >= 1_000:  # Thousands
        formatted_amt = f"{number / 1_000:.2f} K"
    else:
        formatted_amt = f"{number:.2f}"

    return formatted_amt

# function to set start and end date
def get_start_end_date():
  start_date = (datetime.date.today() + datetime.timedelta(days=-365)).strftime('%Y-%m-%d')
  end_date = (datetime.date.today() + datetime.timedelta(days=1)).strftime('%Y-%m-%d')
  return start_date, end_date

# function to fetch my portfolio csv
def get_mypfs_df():
  mypfs_df = pd.read_csv('https://raw.githubusercontent.com/ankit-rathi/Tradevesting_v1/main/data/myPortfolioStocks.csv')
  return mypfs_df

# function to fetch my prospects csv
def get_mypps_df():
  mypps_df = pd.read_csv('https://raw.githubusercontent.com/ankit-rathi/Tradevesting_v1/main/data/myProspectsScrips.csv')
  return mypps_df

# function to fetch screener data
def get_myscreen_df():
  myscreen_df = pd.read_csv('https://raw.githubusercontent.com/ankit-rathi/Tradevesting_v1/main/data/myScreenerDB.csv')
  return myscreen_df

# function to fetch momentum data
def get_myinvmt_df():
  myinvmt_df = pd.read_csv('https://raw.githubusercontent.com/ankit-rathi/Tradevesting_v1/main/data/myInvestments.csv')
  return myinvmt_df

# function to get the stock ids
def get_stock_ids(df_pf):
  stock_n100 = df_pf['Symbol'].unique()

  exclude = ['CADILAHC','MMTC', 'MASFIN']

  stock_ids = df_pf[~df_pf['Symbol'].isin(exclude) ]['Symbol'].unique()

  #mypf = mypf[mypf.Forecast.notnull()]
  #stock_ids = mypf['Symbol'].unique()

  #stock_ids.sort()
  return stock_ids

# get features from screener data
def get_screener_features():
  myscreen_df = get_myscreen_df()
  cols = ['Symbol', 'EPS', 'MedPE', 'ROCE%', 'ROE%', 'CapType']
  return myscreen_df[cols]

# get relative strength
def get_relative_strength(stock_list):

    # Dictionary to store stock tickers and their corresponding percentage price change
    stock_changes = {}

    # Loop through each stock and fetch its price data
    for stock in stock_list:
        try:
            # Download the stock data for the given date range
            stock_data = yfin.Ticker(stock + '.NS').history(period='1mo', interval='1d')[map(str.title, ['open', 'close', 'low', 'high', 'volume'])]

            # Calculate the percentage change for the stock
            if len(stock_data) > 0:
                start_price = stock_data['Close'].iloc[0]
                end_price = stock_data['Close'].iloc[-1]
                percent_change = round(((end_price - start_price) / start_price) * 100, 2)
                stock_changes[stock] = percent_change
            else:
                stock_changes[stock] = np.nan  # If no data is available, set to NaN

        except Exception as e:
            print(f"Error fetching data for {stock}: {e}")
            stock_changes[stock] = np.nan

    # Create a DataFrame with stock tickers and their percentage changes
    df = pd.DataFrame(list(stock_changes.items()), columns=['Symbol', 'Percent_Change'])

    # Drop any stocks with missing data (NaN values)
    df = df.dropna()

    # Calculate the percentile rank based on percentage change
    df['RSP'] = round(df['Percent_Change'].rank(pct=True) * 100, 2)
    cols = ['Symbol', 'RSP']
    df = df[cols]
    # Sort by percentile rank (optional)
    df = df.sort_values(by='RSP', ascending=False).reset_index(drop=True)

    return df

In [6]:
# function to get stock technicals
def stock_prec_dev(stock_symbol):
    #stock_symbol = 'ULTRACEMCO.NS'
    short_window = 20
    mid_window = 50
    long_window = 200
    moving_avg = 'SMA'

    start = datetime.datetime(*map(int, start_date.split('-')))
    end = datetime.datetime(*map(int, end_date.split('-')))

    stock_df = yfin.Ticker(stock_symbol + '.NS').history(period='max', interval='1d')[map(str.title, ['open', 'close', 'low', 'high', 'volume'])]

    stock_df['Max'] = round(max(stock_df['Close']),2)
    stock_df = stock_df[(stock_df.index <= end_date) & (stock_df.index >= start_date)]
    stock_df['200_SMA'] = round(stock_df['Close'].rolling(window = 200, min_periods = 1).mean(),0)
    stock_df['Dev%_200'] = round((stock_df['Close'] - stock_df['200_SMA'])*100/stock_df['200_SMA'],2)
    stock_df.dropna(axis = 0, inplace = True) # remove any null rows

    stock_df['20_SMA'] = stock_df['Close'].rolling(window=20).mean()
    stock_df['50_SMA'] = stock_df['Close'].rolling(window=50).mean()
    stock_df['Symbol'] = stock_symbol

    stock_df['Close'] = round(stock_df['Close'],2)
    stock_df['Min'] = round(min(stock_df['Close']),2)
    stock_df['RSI_14'] = ta.momentum.RSIIndicator(close=stock_df['Close'], window=14).rsi()
    stock_df['RSI_14'] = round(stock_df['RSI_14'],0)
    stock_df['Prev_Close'] = stock_df['Close'].shift(1)
    stock_df.drop(['Open', 'Low', 'High', 'Volume'], axis=1, inplace=True)
    stock_df = stock_df.tail(1)

    max_SMA = max(stock_df['20_SMA'].item(), stock_df['50_SMA'].item(), stock_df['200_SMA'].item())
    min_SMA = min(stock_df['20_SMA'].item(), stock_df['50_SMA'].item(), stock_df['200_SMA'].item())
    ABS_Spread = max_SMA - min_SMA
    stock_df['Spread%'] = round((ABS_Spread / stock_df['200_SMA'].item()) * 100,2)

    return stock_df

# function to compute stock attributes
def get_common_features(stock_ids, df_mypf):

  df_prec_dev = pd.DataFrame()
  df_tmp = get_screener_features()
  df_rs = get_relative_strength(stock_ids)

  for stock_id in stock_ids:
      tmp = stock_prec_dev(stock_id)
      tmp = tmp.reset_index()
      df_prec_dev = pd.concat([df_prec_dev, tmp], ignore_index = True)
  df_prec_dev = pd.merge(df_prec_dev, df_mypf, on= 'Symbol')
  df_prec_dev = pd.merge(df_prec_dev, df_tmp, on= 'Symbol', how='left')
  df_prec_dev = pd.merge(df_prec_dev, df_rs, on= 'Symbol', how='left')
  #print(df_prec_dev.columns)
  df_prec_dev['Curr_PE'] = round(df_prec_dev['Close']/df_prec_dev['EPS'],1)
  df_prec_dev['Dev%_PE'] = round((df_prec_dev['Curr_PE'] - df_prec_dev['MedPE'])*100/df_prec_dev['MedPE'],2)
  df_prec_dev['Conviction'] = df_prec_dev['Conviction'] + '-' + df_prec_dev['CapType']
  return df_prec_dev

# function to arrange stock features
def arrange_features(df_stocks, common_cols, diff_cols):
  df_stocks_common = df_stocks[common_cols].drop_duplicates()
  df_stocks_diff = df_stocks[diff_cols]
  df_stocks_diff['Investment'] = df_stocks_diff['AvgCost'] * df_stocks_diff['Shares']
  df_stocks_diff = df_stocks_diff.groupby(['Symbol'])[['Shares', 'Investment']].aggregate(['sum']).reset_index()
  df_stocks_diff.columns = ['Symbol', 'Shares', 'Investment']
  df_stocks_diff['AvgCost'] = round(df_stocks_diff['Investment']/df_stocks_diff['Shares'],2)
  df_stocks = pd.merge(df_stocks_diff, df_stocks_common, on='Symbol')
  return df_stocks

# plot fact distribution across dimension
def plot_pie_chart(df, dimension, fact):
  # grouping the data by category and calculating the sum of fact for each type
  grouped_data = df.groupby(dimension)[fact].sum()

  # sorting the grouped data in descending order
  grouped_data = grouped_data.sort_values(ascending=False)

  # creating a pie chart
  grouped_data.plot.pie(autopct='%1.1f%%', startangle=90, figsize=(6, 6))

  # adding a title and displaying the plot
  plt.title(f'{dimension} {fact} Distribution')
  plt.ylabel('')  # To hide the y-label
  plt.show()

In [7]:
# function to get portfolio features

def get_portfolio_features(df_common_features):

  print_date_time()
  print('-------------------')

  #df_common_features["Target"] = df_common_features["Target"].fillna(df_common_features["Max"])
  df_common_features['NTT'] = np.where(df_common_features['Strategy']== 'NTT', df_common_features["Target"], df_common_features['Max'])
  df_common_features['LTT'] = np.where(df_common_features['Strategy']== 'BTT', df_common_features["Target"], df_common_features['Max'])
  df_common_features['BOL'] = df_common_features['Min']

  tmp_df = df_common_features[df_common_features['Symbol'].isin(mypf_df[mypf_df['InPortfolio'] != 'NA'].Symbol.values)]
  print('qualified stocks: '+str(len(tmp_df['Symbol'].unique())))
  tmp_df1 = tmp_df[tmp_df['LatestQtr'] == 1]
  print('with latest results: '+str(len(tmp_df1['Symbol'].unique())))
  tmp_df1 = tmp_df1[tmp_df1['StarStock'] == 1]
  print('still star stocks: '+str(len(tmp_df1['Symbol'].unique())))
  tmp_df['Investment'] = tmp_df['AvgCost'] * tmp_df['Shares']
  tmp_df['Current'] = round(tmp_df['Close'] * tmp_df['Shares'],0)
  tmp_df['Previous'] = tmp_df['Prev_Close'] * tmp_df['Shares']
  tmp_df['EstimatedST'] = tmp_df['NTT'] * tmp_df['Shares']
  tmp_df['EstimatedLT'] = tmp_df['LTT'] * tmp_df['Shares']
  tmp_df['Current P/L'] = round((tmp_df['Current'] - tmp_df['Investment']),0)
  tmp_df['Today P/L%'] = round((tmp_df['Current'] - tmp_df['Previous'])*100/tmp_df['Previous'],2)
  tmp_df['Current P/L%'] = round((tmp_df['Current'] - tmp_df['Investment'])*100/tmp_df['Investment'],2)
  tmp_df['EstimatedST P/L%'] = round((tmp_df['EstimatedST'] - tmp_df['Investment'])*100/tmp_df['Investment'],2)
  tmp_df['EstimatedLT P/L%'] = round((tmp_df['EstimatedLT'] - tmp_df['Investment'])*100/tmp_df['Investment'],2)
  tmp_df['NTT%'] = round((tmp_df['NTT'] - tmp_df['Close'])*100/tmp_df['Close'],2)
  tmp_df['LTT%'] = round((tmp_df['LTT'] - tmp_df['Close'])*100/tmp_df['Close'],2)
  tmp_df['Gained%'] = round((tmp_df['Close'] - tmp_df['BOL'])*100/tmp_df['BOL'],2)
  investment = round(sum(tmp_df['AvgCost']*tmp_df['Shares']),0)
  current = round(sum(tmp_df['Close']*tmp_df['Shares']),0)
  tmp_df['InitAlloc%'] = round(tmp_df['Investment']*100/investment,2)
  tmp_df['CurrAlloc%'] = round(tmp_df['Current']*100/current,2)
  tmp_df['FTT'] = tmp_df['LTT']
  tmp_df.loc[tmp_df['Strategy'] == 'NTT', 'FTT'] = tmp_df['NTT']
  tmp_df['FTT%'] = tmp_df['LTT%']
  tmp_df.loc[tmp_df['Strategy'] == 'NTT', 'FTT%'] = tmp_df['NTT%']
  tmp_df['FTT Amt'] = round(tmp_df['FTT%'] * tmp_df['Current']/100,0)
  tmp_df['OTT%'] = round((tmp_df['FTT'] - tmp_df['AvgCost'])*100/tmp_df['AvgCost'],2)
  tmp_df['RRR Ind'] = round(tmp_df['Current P/L']/tmp_df['FTT Amt'],2)
  tmp_df['Risk Ind'] = round(tmp_df['Current P/L%']*tmp_df['CurrAlloc%'],0)

  return tmp_df

# function to print portfolio features
def print_portfolio_stats(df_portfolio_features, myinvmt_df):
  from pyxirr import xirr

  total_booked_amt, reserve_amt, cy_booked_amt, py_booked_amt = get_amt()

  dates = myinvmt_df['Date'].values
  dates = np.append(dates, datetime.date.today().strftime('%d-%b-%y'))
  investment = myinvmt_df['Investment'].values
  dates= pd.to_datetime(dates)

  current = round(sum(df_portfolio_features['Close']*df_portfolio_features['Shares']),0) + reserve_amt
  investment_xirr = np.append(investment, current)
  cagr = round(xirr(pd.DataFrame({"dates": dates, "amounts": investment_xirr}))*100,2)

  investment = -sum(investment)
  invested = round(sum(df_portfolio_features['AvgCost']*df_portfolio_features['Shares']),0) + reserve_amt
  previous = round(sum(df_portfolio_features['Prev_Close']*df_portfolio_features['Shares']),0) + reserve_amt
  cy_invested = investment + py_booked_amt

  today_pnl_amount = current-previous
  today_pnl_percentage = round((current-previous)*100/previous,2)

  curr_pnl_amount = current-invested
  curr_pnl_percentage = round((curr_pnl_amount)*100/(cy_invested),2)

  cy_pnl_amount = cy_booked_amt + curr_pnl_amount
  cy_pnl_percentage = round((cy_pnl_amount)*100/cy_invested,2)

  overall_pnl_amount = total_booked_amt + curr_pnl_amount
  overall_pnl_percentage = round((overall_pnl_amount)*100/investment,2)

  estimate_st = round(sum(df_portfolio_features['FTT']*df_portfolio_features['Shares']),0)  + reserve_amt
  est_st_pnl_amount = estimate_st-current
  est_st_pnl_percentage = round((est_st_pnl_amount)*100/current,2)

  estimate_lt = round(sum(df_portfolio_features['LTT']*df_portfolio_features['Shares']),0)  + reserve_amt
  est_lt_pnl_amount = estimate_lt-current
  est_lt_pnl_percentage = round((est_lt_pnl_amount)*100/current,2)

  total_profit = round(sum(df_portfolio_features[df_portfolio_features['Current P/L%'] > 0]['Current']) - sum(df_portfolio_features[df_portfolio_features['Current P/L%'] > 0]['Investment']),0)
  total_loss = round(sum(df_portfolio_features[df_portfolio_features['Current P/L%'] < 0]['Current']) - sum(df_portfolio_features[df_portfolio_features['Current P/L%'] < 0]['Investment']),0)

  cy_booked_percentage = round((cy_booked_amt)*100/current,2)
  py_booked_percentage = round((py_booked_amt)*100/investment,2)
  total_booked_percentage = round((total_booked_amt)*100/investment,2)

  print('-------------------')
  print('Initial Investment: ', format_amt(investment))
  print('CY Investment: ', format_amt(cy_invested))
  print('Reserve: ', format_amt(reserve_amt))
  print('Current: ',  format_amt(current))
  print('-------------------')
  print('Today PnL: '+ '{} ({}%)'.format(format_amt(today_pnl_amount), today_pnl_percentage))
  print('Current PnL: '+ '{} ({}%)'.format(format_amt(curr_pnl_amount), curr_pnl_percentage))
  print('CY Booked + Current PnL: '+ '{} ({}%)'.format(format_amt(cy_pnl_amount), cy_pnl_percentage))
  print('-------------------')
  print('Total profit: ', format_amt(total_profit))
  print('Total loss: ', format_amt(total_loss))
  print('-------------------')
  print('Total Booked + Current PnL: '+ '{} ({}%)'.format(format_amt(overall_pnl_amount), overall_pnl_percentage))
  print('Total Booked PnL: '+ '{} ({}%)'.format(format_amt(total_booked_amt), total_booked_percentage))
  print('Curr Year Booked PnL: '+ '{} ({}%)'.format(format_amt(cy_booked_amt), cy_booked_percentage))
  print('Prev Year Booked PnL: '+ '{} ({}%)'.format(format_amt(py_booked_amt), py_booked_percentage))
  print('===================')
  print('Est FTT: ',  format_amt(estimate_st))
  print('Est FTT PnL: '+ '{} ({}%)'.format(format_amt(est_st_pnl_amount), est_st_pnl_percentage))

  print('===================')
  print('Deployed: ', format_amt(investment))

  print('Current: ', format_amt(current))

  print('CAGR/XIRR %: '+'{}%'.format(cagr))

In [8]:
# get start and end date
start_date, end_date = get_start_end_date()

# get portfolio and prospects data
mypfs_df = get_mypfs_df()
mypps_df = get_mypps_df()
myinvmt_df = get_myinvmt_df()

# merge above datasets
mypf_df = pd.merge(mypfs_df, mypps_df, on="Symbol")

# seggregate dm and sv portfolio
dm_pf = mypf_df[mypf_df['InPortfolio'] == 'DM']
sv_pf = mypf_df[mypf_df['InPortfolio'] == 'SV']

# build portfolio stock dataframe
dm_stocks = get_stock_ids(dm_pf)
sv_stocks = get_stock_ids(sv_pf)
df_stocks = pd.concat([dm_pf,sv_pf], ignore_index = True)

# arrange common and diff stock features
common_cols = ['Symbol', 'Target', 'Criteria', 'Strategy', 'CumlRnk', 'LatestQtr', 'StarStock', 'Conviction', 'Category', 'InFolio', 'XIRR', 'MBQ']
diff_cols = ['Symbol', 'AvgCost', 'Shares']
df_stocks = arrange_features(df_stocks, common_cols, diff_cols)

# get common features
stock_ids = df_stocks['Symbol'].values
df_common_features = get_common_features(stock_ids, df_stocks)

df_common_features.reset_index(drop=True, inplace=True)
df_common_features.drop(['Date'], axis=1, inplace=True)
# get and print portfolio features
df_portfolio_features = get_portfolio_features(df_common_features)

print_portfolio_stats(df_portfolio_features, myinvmt_df)

df = df_portfolio_features
#plot_pie_chart(df, 'CapType', 'Current')
list_ox40n = list(df[df['MBQ'].str.contains('OX40N', na=False)]['Symbol'].values)

Run date time (IST): 2026-04-08 15:45:57
-------------------
qualified stocks: 86
with latest results: 26
still star stocks: 16
-------------------
Initial Investment:  1.36 C
CY Investment:  1.62 C
Reserve:  1.61 K
Current:  1.36 C
-------------------
Today PnL: 4.80 L (3.65%)
Current PnL: -40.70 L (-25.05%)
CY Booked + Current PnL: -24.81 L (-15.27%)
-------------------
Total profit:  1.07 L
Total loss:  -41.76 L
-------------------
Total Booked + Current PnL: 2.17 L (1.6%)
Total Booked PnL: 42.87 L (31.64%)
Curr Year Booked PnL: 15.89 L (11.65%)
Prev Year Booked PnL: 26.98 L (19.91%)
===================
Est FTT:  2.48 C
Est FTT PnL: 1.11 C (81.69%)
===================
Deployed:  1.36 C
Current:  1.36 C
CAGR/XIRR %: 0.33%

In [9]:
# top 5 near their targets
cols = ['Symbol', 'Today P/L%', 'Current P/L%', 'FTT%', 'OTT%', 'FTT Amt', 'Current P/L', 'Current', 'FTT', 'Dev%_PE', 'RSI_14','Conviction', 'Spread%',  'CumlRnk', 'RRR Ind', 'CurrAlloc%', 'Gained%', 'Criteria', 'Strategy', 'Category']
df_tmp = df_portfolio_features[~df_portfolio_features['Symbol'].isin(['ENRIN','BLUSPRING','DIGITIDE'])]
df_tmp = df_tmp.sort_values(by = 'FTT Amt', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
50,MASFIN,4.09,-4.61,27.44,21.57,25647.0,-4515.0,93465.0,397.04,-17.80,54.0,H-SC,4.84,167.0,-0.18,0.69,22.97,XR,ATH,FINANCE
77,TTKPRESTIG,2.29,-37.42,59.95,0.09,37806.0,-37714.0,63063.0,770.00,46.42,49.0,M-SC,22.14,250.0,-1.00,0.46,12.29,OX40N,NTT,DURABLES
5,ANGELONE,8.74,9.68,13.22,24.18,44224.0,29525.0,334525.0,303.00,-83.85,67.0,X-SC,7.61,97.0,0.67,2.45,27.98,X40N,NTT,FINANCE
67,SONACOMS,3.60,-7.67,50.65,39.09,47306.0,-7761.0,93398.0,804.02,-26.82,59.0,M-MC,7.68,193.0,-0.16,0.68,32.12,AR,ATH,AUTO
37,ICICIGI,1.38,-7.27,28.70,19.34,53254.0,-14556.0,185553.0,2252.93,-22.04,42.0,X-MC,6.92,66.0,-0.27,1.36,3.64,X40,ATH,INSURANCE

In [10]:
# top 5 today
df_tmp = df_portfolio_features.sort_values(by = 'Today P/L%', ascending=False)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
25,EASEMYTRIP,17.41,-56.46,234.60,45.70,180621.0,-99824.0,76991.0,26.4,-20.01,62.0,M-SC,14.59,204.0,-0.55,0.56,34.87,XY24,NTT,TRAVEL
11,BANDHANBNK,10.47,-20.75,142.79,92.42,315230.0,-57794.0,220765.0,400.0,89.66,54.0,H-SC,2.37,174.0,-0.18,1.62,21.61,XY24,NTT,BANKS
14,BOSCH-HCIL,9.96,-44.07,78.78,-0.01,56310.0,-56327.0,71478.0,2282.0,14530.43,53.0,M-SC,9.53,231.0,-1.00,0.52,21.67,OX40N,BTT,AC
19,COFFEEDAY,9.57,-56.46,210.68,35.27,104160.0,-64109.0,49440.0,80.0,-65.79,51.0,L-SC,32.94,266.0,-0.62,0.36,21.92,XR,NTT,HOTELS
56,RAJOOENG,9.21,-39.40,130.36,39.61,80980.0,-40380.0,62120.0,143.1,-59.10,59.0,H-SC,33.63,136.0,-0.50,0.46,33.08,AR,ATH,MISC

In [11]:
# bottom 5 today
df_tmp = df_portfolio_features.sort_values(by = 'Today P/L%', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
24,DMART,-2.18,5.02,23.41,29.60,61364.0,12528.0,262128.0,5391.45,-11.48,66.0,X-LC,5.35,14.0,0.20,1.92,19.81,X40N,ATH,FMCG
53,PGHH,-1.28,-28.18,83.82,32.01,128533.0,-60176.0,153344.0,17616.87,-51.42,34.0,X-MC,20.32,57.0,-0.47,1.12,4.88,X40,ATH,FMCG
84,WIPRO,-0.63,-16.57,106.47,72.27,150524.0,-28071.0,141377.0,420.00,-24.55,55.0,M-LC,17.76,98.0,-0.19,1.04,8.47,XR,NTT,IT
49,LAOPALA,-0.50,-47.83,166.59,39.09,113951.0,-62703.0,68402.0,464.00,49.34,40.0,H-SC,18.57,154.0,-0.55,0.50,6.13,AR,NTT,CERAMICS
36,HONAUT,-0.24,-29.60,114.94,51.31,156031.0,-57088.0,135750.0,58357.33,-41.49,37.0,X-SC,18.75,90.0,-0.37,1.00,3.13,X40N,ATH,ELECTRICAL

In [12]:
# top 5 to exit based on CumlRnk
df_tmp = df_portfolio_features[~df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])]
df_tmp = df_tmp[(df_tmp['Current P/L%'] > -1) & (df_tmp['Current P/L%'] < 1)].sort_values(by = 'CumlRnk', ascending=False)
df_tmp[cols].head()

Empty DataFrame
Columns: [Symbol, Today P/L%, Current P/L%, FTT%, OTT%, FTT Amt, Current P/L, Current, FTT, Dev%_PE, RSI_14, Conviction, Spread%, CumlRnk, RRR Ind, CurrAlloc%, Gained%, Criteria, Strategy, Category]
Index: []

In [13]:
# OX40N stocks to exit
df_tmp = df_portfolio_features[(df_portfolio_features['Symbol'].isin(list_ox40n))].sort_values(by = 'Current P/L%', ascending=False)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
26,FINCABLES,4.64,7.42,93.56,107.91,148381.0,10951.0,158595.0,1641.55,-3.60,53.0,M-SC,3.13,220.0,0.07,1.16,19.32,OX40N,ATH,CABLES
66,SIS,1.94,-32.52,79.71,21.26,59718.0,-36113.0,74919.0,528.00,1756.48,53.0,H-SC,14.73,168.0,-0.60,0.55,11.39,OX40N,NTT,MISC
18,CERA,5.08,-33.93,87.50,23.89,101700.0,-59675.0,116228.0,9475.00,-36.28,61.0,H-SC,18.55,153.0,-0.59,0.85,11.69,OX40N,NTT,CERAMICS
72,TATAELXSI,1.76,-36.09,106.59,32.03,89806.0,-47581.0,84254.0,9161.00,-20.03,53.0,H-SC,21.33,158.0,-0.53,0.62,11.51,OX40N,NTT,IT
48,KANSAINER,5.49,-37.20,80.70,13.47,136661.0,-100323.0,169344.0,340.00,-46.01,55.0,H-SC,23.43,162.0,-0.73,1.24,18.29,XY24,NTT,PAINTS

In [14]:
# top 5 to book for rotation
df_tmp = df_portfolio_features[(df_portfolio_features['Current P/L%'] > 20) ].sort_values(by = 'CumlRnk', ascending=False)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
1,ABB,4.72,20.45,20.85,45.57,65703.0,53501.0,315120.0,7934.0,-22.56,65.0,H-MC,14.34,125.0,0.81,2.31,39.93,AR,NTT,ELECTRICAL

In [15]:
# top 5 to monitor for exit
df_tmp = df_portfolio_features[~df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])]
df_tmp = df_tmp[(df_tmp['Current P/L%'] > 0) ].sort_values(by = 'Dev%_PE', ascending=False)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
26,FINCABLES,4.64,7.42,93.56,107.91,148381.0,10951.0,158595.0,1641.55,-3.60,53.0,M-SC,3.13,220.0,0.07,1.16,19.32,OX40N,ATH,CABLES
1,ABB,4.72,20.45,20.85,45.57,65703.0,53501.0,315120.0,7934.00,-22.56,65.0,H-MC,14.34,125.0,0.81,2.31,39.93,AR,NTT,ELECTRICAL

In [16]:
# top 5 to book for rotation from weak conviction
df_tmp = df_portfolio_features[~df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])]
df_tmp = df_tmp[~df_tmp['Criteria'].isin(['XY25','XY24','X40', 'X40N'])].sort_values(by = 'RRR Ind', ascending=False)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
1,ABB,4.72,20.45,20.85,45.57,65703.0,53501.0,315120.0,7934.00,-22.56,65.0,H-MC,14.34,125.0,0.81,2.31,39.93,AR,NTT,ELECTRICAL
26,FINCABLES,4.64,7.42,93.56,107.91,148381.0,10951.0,158595.0,1641.55,-3.60,53.0,M-SC,3.13,220.0,0.07,1.16,19.32,OX40N,ATH,CABLES
40,INDIAMART,2.03,-9.96,129.60,106.72,143916.0,-12290.0,111046.0,4810.62,-59.38,52.0,H-SC,12.85,140.0,-0.09,0.81,7.72,AR,ATH,MISC
85,ZYDUSLIFE,2.07,-5.98,44.26,35.63,87207.0,-12541.0,197033.0,1286.17,-18.02,51.0,H-MC,6.04,120.0,-0.14,1.44,9.69,AR,ATH,PHARMA
67,SONACOMS,3.60,-7.67,50.65,39.09,47306.0,-7761.0,93398.0,804.02,-26.82,59.0,M-MC,7.68,193.0,-0.16,0.68,32.12,AR,ATH,AUTO

In [17]:
# top 5 to accumulate based on lowest RSI_14
df_tmp = df_portfolio_features[df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])].sort_values(by = 'RSI_14', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
53,PGHH,-1.28,-28.18,83.82,32.01,128533.0,-60176.0,153344.0,17616.87,-51.42,34.0,X-MC,20.32,57.0,-0.47,1.12,4.88,X40,ATH,FMCG
36,HONAUT,-0.24,-29.60,114.94,51.31,156031.0,-57088.0,135750.0,58357.33,-41.49,37.0,X-SC,18.75,90.0,-0.37,1.00,3.13,X40N,ATH,ELECTRICAL
21,DABUR,3.14,-16.47,72.03,43.70,149258.0,-40852.0,207216.0,735.00,-24.27,39.0,X-MC,12.91,70.0,-0.27,1.52,4.09,XY24,BTT,FMCG
82,VOLTAS,3.66,-1.05,46.74,45.20,88675.0,-2022.0,189720.0,1856.00,13.28,40.0,X-MC,5.00,79.0,-0.02,1.39,5.67,XY25,NTT,AC
38,ICICIPRULI,4.83,-10.38,45.86,30.73,80971.0,-20443.0,176562.0,790.00,-34.44,41.0,X-MC,10.81,78.0,-0.25,1.29,7.59,X40,ATH,INSURANCE

In [18]:
# top 5 to accumulate based on Spread and CumlRnk
df_tmp = df_portfolio_features[df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])]
df_tmp = df_tmp[(df_tmp['CumlRnk'] < 100)].sort_values(by = 'Spread%', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
65,SIEMENS,4.90,-13.32,44.80,25.51,72265.0,-24790.0,161305.0,4671.50,35.44,56.0,H-LC,0.94,51.0,-0.34,1.18,18.79,AR,ATH,ELECTRICAL
59,RELIANCE,3.31,-13.48,44.83,25.30,77944.0,-27097.0,173866.0,1952.00,-15.80,44.0,X-LC,4.44,21.0,-0.35,1.27,14.46,XY25,BTT,REFINERIES
78,UNITDSPR,0.86,-8.26,31.65,20.77,67982.0,-19350.0,214794.0,1644.00,-18.64,42.0,X-MC,4.59,64.0,-0.28,1.57,2.46,X40N,NTT,BREWERIES
82,VOLTAS,3.66,-1.05,46.74,45.20,88675.0,-2022.0,189720.0,1856.00,13.28,40.0,X-MC,5.00,79.0,-0.02,1.39,5.67,XY25,NTT,AC
24,DMART,-2.18,5.02,23.41,29.60,61364.0,12528.0,262128.0,5391.45,-11.48,66.0,X-LC,5.35,14.0,0.20,1.92,19.81,X40N,ATH,FMCG

In [19]:
# top 5 to accumulate based on lowest Gained%
df_tmp = df_portfolio_features[df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])].sort_values(by = 'Gained%', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
2,ABBOTINDIA,0.72,-13.28,36.15,18.07,56069.0,-23755.0,155100.0,35195.00,-26.29,43.0,X-MC,11.09,58.0,-0.42,1.14,1.43,X40,ATH,PHARMA
78,UNITDSPR,0.86,-8.26,31.65,20.77,67982.0,-19350.0,214794.0,1644.00,-18.64,42.0,X-MC,4.59,64.0,-0.28,1.57,2.46,X40N,NTT,BREWERIES
36,HONAUT,-0.24,-29.60,114.94,51.31,156031.0,-57088.0,135750.0,58357.33,-41.49,37.0,X-SC,18.75,90.0,-0.37,1.00,3.13,X40N,ATH,ELECTRICAL
37,ICICIGI,1.38,-7.27,28.70,19.34,53254.0,-14556.0,185553.0,2252.93,-22.04,42.0,X-MC,6.92,66.0,-0.27,1.36,3.64,X40,ATH,INSURANCE
8,AWL,-0.04,-38.37,170.98,67.02,375486.0,-136701.0,219608.0,485.00,-66.76,44.0,X-SC,25.69,81.0,-0.36,1.61,3.88,XY24,NTT,FMCG

In [20]:
# top 5 to accumulate based on lowest CurrAlloc%
df_tmp = df_portfolio_features[df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])].sort_values(by = 'CurrAlloc%', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
58,RELAXO,3.80,-63.72,319.81,52.31,168425.0,-92496.0,52664.0,1176.00,-61.38,45.0,X-SC,32.69,92.0,-0.55,0.39,17.75,X40N,NTT,FOOTWEAR
12,BATAINDIA,5.17,-54.58,197.66,35.20,115520.0,-70226.0,58444.0,2096.00,-23.32,51.0,X-SC,34.36,91.0,-0.61,0.43,15.91,X40,NTT,FOOTWEAR
54,QUESS,3.56,-22.54,124.50,73.90,102988.0,-24072.0,82721.0,424.00,-58.13,55.0,X-SC,22.42,80.0,-0.23,0.61,11.28,XY24,NTT,MISC
36,HONAUT,-0.24,-29.60,114.94,51.31,156031.0,-57088.0,135750.0,58357.33,-41.49,37.0,X-SC,18.75,90.0,-0.37,1.00,3.13,X40N,ATH,ELECTRICAL
53,PGHH,-1.28,-28.18,83.82,32.01,128533.0,-60176.0,153344.0,17616.87,-51.42,34.0,X-MC,20.32,57.0,-0.47,1.12,4.88,X40,ATH,FMCG

In [21]:
# top 5 to accumulate based on CumlRnk
df_tmp = df_portfolio_features.sort_values(by = 'CumlRnk', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
45,ITC,1.34,-20.33,49.45,19.06,134007.0,-69171.0,270995.0,452.00,-56.33,49.0,X-LC,19.77,1.0,-0.52,1.99,5.13,X40,NTT,FMCG
73,TCS,0.76,-24.87,68.47,26.57,238311.0,-115222.0,348051.0,4311.59,-36.41,55.0,X-LC,18.47,2.0,-0.48,2.55,8.62,X40,ATH,IT
43,INFY,0.51,-8.36,46.49,34.24,133306.0,-26147.0,286741.0,1972.00,-27.79,58.0,X-LC,14.50,3.0,-0.20,2.10,10.27,X40,NTT,IT
75,TMPV,8.44,-23.80,79.24,36.58,214858.0,-84693.0,271148.0,600.00,-84.72,54.0,X-LC,12.41,4.0,-0.39,1.99,13.01,XY24,NTT,AUTO
33,HCLTECH,1.35,-5.19,30.61,23.83,70212.0,-12547.0,229377.0,1908.19,-0.33,62.0,X-LC,10.53,8.0,-0.18,1.68,11.37,X40,ATH,IT

In [22]:
# top 5 for average up
df_tmp = df_portfolio_features[(df_portfolio_features['Dev%_200'] > 5)].sort_values(by = 'CurrAlloc%', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
67,SONACOMS,3.60,-7.67,50.65,39.09,47306.0,-7761.0,93398.0,804.02,-26.82,59.0,M-MC,7.68,193.0,-0.16,0.68,32.12,AR,ATH,AUTO
24,DMART,-2.18,5.02,23.41,29.60,61364.0,12528.0,262128.0,5391.45,-11.48,66.0,X-LC,5.35,14.0,0.20,1.92,19.81,X40N,ATH,FMCG
1,ABB,4.72,20.45,20.85,45.57,65703.0,53501.0,315120.0,7934.00,-22.56,65.0,H-MC,14.34,125.0,0.81,2.31,39.93,AR,NTT,ELECTRICAL
5,ANGELONE,8.74,9.68,13.22,24.18,44224.0,29525.0,334525.0,303.00,-83.85,67.0,X-SC,7.61,97.0,0.67,2.45,27.98,X40N,NTT,FINANCE

In [23]:
# top 5 RSP
df_tmp = df_portfolio_features.sort_values(by = 'RSP', ascending=False)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
80,VALIANTORG,1.01,-45.09,217.14,74.15,195083.0,-73763.0,89842.0,838.00,-261.57,60.0,H-SC,25.04,145.0,-0.38,0.66,33.70,XR,NTT,CHEMICALS
5,ANGELONE,8.74,9.68,13.22,24.18,44224.0,29525.0,334525.0,303.00,-83.85,67.0,X-SC,7.61,97.0,0.67,2.45,27.98,X40N,NTT,FINANCE
52,PAGEIND,0.81,-7.86,45.56,34.11,112658.0,-21104.0,247275.0,51418.64,-33.93,68.0,X-MC,18.59,55.0,-0.19,1.81,16.97,X40,ATH,APPARELS
30,HAPPSTMNDS,1.22,-52.26,287.21,84.85,175727.0,-66981.0,61184.0,1480.71,-43.28,49.0,H-SC,23.19,152.0,-0.38,0.45,13.30,AR,ATH,IT
18,CERA,5.08,-33.93,87.50,23.89,101700.0,-59675.0,116228.0,9475.00,-36.28,61.0,H-SC,18.55,153.0,-0.59,0.85,11.69,OX40N,NTT,CERAMICS

In [24]:
# Top N allocation
df_tmp = df_portfolio_features.sort_values(by = 'CurrAlloc%', ascending=False)
top_n_values = [10, 25, 50]

sum_df = pd.DataFrame({
    'Top_N': top_n_values,
    'Sum_Alloc%': [df_tmp['CurrAlloc%'].head(n).sum() for n in top_n_values]
})

sum_df

   Top_N  Sum_Alloc%
0     10       21.07
1     25       46.06
2     50       77.77

In [25]:
# market-cap-wise allocation
df_tmp = df_portfolio_features[cols]
df_tmp.groupby(df_tmp['Conviction'].str[-2:])['CurrAlloc%'].sum().sort_values(ascending=False)

Conviction
SC    45.03
MC    29.26
LC    25.68
Name: CurrAlloc%, dtype: float64

In [26]:
# criteria-wise allocation
df_portfolio_features.groupby('Criteria')['CurrAlloc%'].sum().sort_values(ascending=False)

Criteria
XY24     27.29
X40      25.09
X40N     15.41
AR        9.16
XR        8.47
XY25      7.01
OX40N     6.74
SR        0.80
Name: CurrAlloc%, dtype: float64

In [27]:
# conviction-wise allocation
df_portfolio_features.groupby('Conviction')['CurrAlloc%'].sum().sort_values(ascending=False)

Conviction
X-LC    23.46
H-SC    22.10
X-MC    21.82
X-SC    12.30
M-SC    10.07
H-MC     5.03
M-MC     2.06
H-LC     1.18
M-LC     1.04
L-SC     0.56
L-MC     0.35
Name: CurrAlloc%, dtype: float64

In [28]:
# sector-wise stats
df_tmp = df_portfolio_features.groupby('Category')[['CurrAlloc%', 'Current', 'Current P/L', 'FTT Amt']].sum().sort_values(by=['Current', 'Current P/L'], ascending=False)
df_tmp['Current P/L%'] = round(df_tmp['Current P/L'] * 100 / df_tmp['Current'], 2)
df_tmp['FTT%'] = round(df_tmp['FTT Amt'] * 100 / df_tmp['Current'], 2)
cols = ['CurrAlloc%', 'Current P/L%', 'FTT%']
df_tmp[cols].sort_values(by=['CurrAlloc%'], ascending=False)

               CurrAlloc%  Current P/L%    FTT%
Category
FMCG                14.79        -23.76   67.68
FINANCE             13.49        -16.69   64.24
IT                  11.99        -37.68  107.75
MISC                 7.13        -38.14   98.15
ELECTRICAL           6.41        -10.83   53.26
PAINTS               5.21        -38.84   62.96
BANKS                4.68        -20.52   81.69
INSURANCE            4.52         -9.81   47.38
PHARMA               3.96         -8.74   42.97
AUTO                 3.76        -27.60   78.23
HEALTHCARE           1.94        -34.79   69.96
AC                   1.91        -22.34   55.51
TRAVEL               1.84        -77.59  166.51
FOOTWEAR             1.84        -76.85  147.76
APPARELS             1.81         -8.53   45.56
DURABLES             1.75        -61.72  101.07
BREWERIES            1.57         -9.01   31.65
REALTY               1.41        -15.23   34.16
CERAMICS             1.35        -66.28  116.80
REFINERIES           1.27        -15.58   44.83
CEMENT               1.24        -58.36  176.82
ENGINEERING          1.18        -49.89  118.44
CABLES               1.16          6.91   93.56
CHEMICALS            1.10        -77.31  221.96
JEWELLERY            1.07       -120.95  197.71
ENTERTAINMENT        0.78        -82.37  191.13
TEXTILES             0.45        -48.92   91.39
HOTELS               0.36       -129.67  210.68

In [29]:
# money to be made criteria-wise
df_portfolio_features.groupby('Criteria')['FTT Amt'].agg(['sum', 'count']).sort_values(by='sum', ascending=False)

                sum  count
Criteria
XY24      3874041.0     21
X40       1750596.0     16
XR        1337061.0     12
AR        1320271.0     10
X40N      1197718.0     10
OX40N      871780.0     10
XY25       483092.0      5
SR         310548.0      2

In [30]:
# money to be made conviction-wise
df_portfolio_features.groupby('Conviction')['FTT Amt'].agg(['sum', 'count']).sort_values(by='sum', ascending=False)

                  sum  count
Conviction
H-SC        3778114.0     24
X-MC        1755806.0     15
X-LC        1573731.0     13
M-SC        1542899.0     14
X-SC        1506302.0     10
H-MC         391700.0      3
L-SC         214672.0      2
M-LC         150524.0      1
M-MC         104145.0      2
H-LC          72265.0      1
L-MC          54949.0      1

In [31]:
# money to be made criteria and conviction-wise
df_portfolio_features.groupby(['Conviction', 'Criteria'])['FTT Amt'].agg(['sum', 'count']).sort_values(by='sum', ascending=False)

                           sum  count
Conviction Criteria
H-SC       XY24      1285764.0      6
           AR         970060.0      5
M-SC       XY24       888215.0      6
X-LC       X40        844364.0      7
X-SC       XY24       842374.0      4
H-SC       XR         839775.0      7
X-MC       X40        691882.0      7
           X40N       527965.0      4
X-SC       X40N       449578.0      4
M-SC       OX40N      389301.0      5
H-SC       OX40N      371967.0      4
X-LC       XY24       353599.0      2
H-SC       SR         310548.0      2
X-MC       XY25       270660.0      2
           XY24       265299.0      2
H-MC       XY24       238790.0      1
X-LC       X40N       220175.0      2
X-SC       X40        214350.0      2
M-SC       XR         187653.0      2
X-LC       XY25       155593.0      2
H-MC       AR         152910.0      2
M-LC       XR         150524.0      1
L-SC       OX40N      110512.0      1
           XR         104160.0      1
M-SC       AR          77730.0      1
H-LC       AR          72265.0      1
M-MC       XY25        56839.0      1
L-MC       XR          54949.0      1
M-MC       AR          47306.0      1

In [32]:
# notebook execution time

end_time = time.time()
execution_time = round(end_time - start_time, 0)
print(f"Notebook execution time: {execution_time} seconds")

Notebook execution time: 34.0 seconds