<a href="https://colab.research.google.com/github/ankit-rathi/Quantvesting_v2/blob/main/myStocks_Portfolio_Analysis.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
'''
!pip install pandas==2.2.2 -qq
!pip install pyxirr -qq
!pip install ta -qq
!pip install yfinance==0.2.59 -qq
'''

'\n!pip install pandas==2.2.2 -qq\n!pip install pyxirr -qq\n!pip install ta -qq\n!pip install yfinance==0.2.59 -qq\n'

In [2]:
# import libraries

import numpy as np
import pandas as pd
import datetime
import warnings
warnings.filterwarnings('ignore')
import yfinance as yfin
import ta
import matplotlib.pyplot as plt
import requests

In [3]:
# notebook start time
import time
import datetime
import pytz

start_time = time.time()

# function to print date timestamp
def print_date_time():
  tz_NY = pytz.timezone('Asia/Kolkata')
  datetime_NY = datetime.datetime.now(tz_NY)
  print("Run date time (IST):", datetime_NY.strftime("%Y-%m-%d %H:%M:%S"))

In [4]:
# function to get booked and reserved amount
def get_amt():
  # fetch the JSON data from the URL
  url = "https://raw.githubusercontent.com/ankit-rathi/Tradevesting_v1/main/data/myPortfolioAmts.json"
  response = requests.get(url)
  pf_amts = response.json()  # parse the JSON data

  # extract values from the JSON
  py_booked_amt_dm = pf_amts["py_booked_amt_dm"]
  py_booked_amt_sv = pf_amts["py_booked_amt_sv"]
  cy_booked_amt_dm = pf_amts["cy_booked_amt_dm"]
  cy_booked_amt_sv = pf_amts["cy_booked_amt_sv"]
  reserve_amt_dm = pf_amts["reserve_amt_dm"]
  reserve_amt_sv = pf_amts["reserve_amt_sv"]

  # perform calculations
  py_booked_amt = py_booked_amt_dm + py_booked_amt_sv
  cy_booked_amt = cy_booked_amt_dm + cy_booked_amt_sv
  reserve_amt = reserve_amt_dm + reserve_amt_sv
  total_booked_amt = py_booked_amt + cy_booked_amt

  return total_booked_amt, reserve_amt, cy_booked_amt, py_booked_amt

gen_output = 0

In [5]:
# function to format the amount
def format_amt(number):
    abs_number = abs(number)

    if abs_number >= 1_00_00_000:  # Crores
        formatted_amt = f"{number / 1_00_00_000:.2f} C"
    elif abs_number >= 1_00_000:  # Lakhs
        formatted_amt = f"{number / 1_00_000:.2f} L"
    elif abs_number >= 1_000:  # Thousands
        formatted_amt = f"{number / 1_000:.2f} K"
    else:
        formatted_amt = f"{number:.2f}"

    return formatted_amt

# function to set start and end date
def get_start_end_date():
  start_date = (datetime.date.today() + datetime.timedelta(days=-365)).strftime('%Y-%m-%d')
  end_date = (datetime.date.today() + datetime.timedelta(days=1)).strftime('%Y-%m-%d')
  return start_date, end_date

# function to fetch my portfolio csv
def get_mypfs_df():
  mypfs_df = pd.read_csv('https://raw.githubusercontent.com/ankit-rathi/Tradevesting_v1/main/data/myPortfolioStocks.csv')
  return mypfs_df

# function to fetch my prospects csv
def get_mypps_df():
  mypps_df = pd.read_csv('https://raw.githubusercontent.com/ankit-rathi/Tradevesting_v1/main/data/myProspectsScrips.csv')
  return mypps_df

# function to fetch screener data
def get_myscreen_df():
  myscreen_df = pd.read_csv('https://raw.githubusercontent.com/ankit-rathi/Tradevesting_v1/main/data/myScreenerDB.csv')
  return myscreen_df

# function to fetch momentum data
def get_myinvmt_df():
  myinvmt_df = pd.read_csv('https://raw.githubusercontent.com/ankit-rathi/Tradevesting_v1/main/data/myInvestments.csv')
  return myinvmt_df

# function to get the stock ids
def get_stock_ids(df_pf):
  stock_n100 = df_pf['Symbol'].unique()

  exclude = ['CADILAHC','MMTC', 'MASFIN']

  stock_ids = df_pf[~df_pf['Symbol'].isin(exclude) ]['Symbol'].unique()

  #mypf = mypf[mypf.Forecast.notnull()]
  #stock_ids = mypf['Symbol'].unique()

  #stock_ids.sort()
  return stock_ids

# get features from screener data
def get_screener_features():
  myscreen_df = get_myscreen_df()
  cols = ['Symbol', 'EPS', 'MedPE', 'ROCE%', 'ROE%', 'CapType']
  return myscreen_df[cols]

# get relative strength
def get_relative_strength(stock_list):

    # Dictionary to store stock tickers and their corresponding percentage price change
    stock_changes = {}

    # Loop through each stock and fetch its price data
    for stock in stock_list:
        try:
            # Download the stock data for the given date range
            stock_data = yfin.Ticker(stock + '.NS').history(period='1mo', interval='1d')[map(str.title, ['open', 'close', 'low', 'high', 'volume'])]

            # Calculate the percentage change for the stock
            if len(stock_data) > 0:
                start_price = stock_data['Close'].iloc[0]
                end_price = stock_data['Close'].iloc[-1]
                percent_change = round(((end_price - start_price) / start_price) * 100, 2)
                stock_changes[stock] = percent_change
            else:
                stock_changes[stock] = np.nan  # If no data is available, set to NaN

        except Exception as e:
            print(f"Error fetching data for {stock}: {e}")
            stock_changes[stock] = np.nan

    # Create a DataFrame with stock tickers and their percentage changes
    df = pd.DataFrame(list(stock_changes.items()), columns=['Symbol', 'Percent_Change'])

    # Drop any stocks with missing data (NaN values)
    df = df.dropna()

    # Calculate the percentile rank based on percentage change
    df['RSP'] = round(df['Percent_Change'].rank(pct=True) * 100, 2)
    cols = ['Symbol', 'RSP']
    df = df[cols]
    # Sort by percentile rank (optional)
    df = df.sort_values(by='RSP', ascending=False).reset_index(drop=True)

    return df

In [6]:
# function to get stock technicals
def stock_prec_dev(stock_symbol):
    #stock_symbol = 'ULTRACEMCO.NS'
    short_window = 20
    mid_window = 50
    long_window = 200
    moving_avg = 'SMA'

    start = datetime.datetime(*map(int, start_date.split('-')))
    end = datetime.datetime(*map(int, end_date.split('-')))

    stock_df = yfin.Ticker(stock_symbol + '.NS').history(period='max', interval='1d')[map(str.title, ['open', 'close', 'low', 'high', 'volume'])]

    stock_df['Max'] = round(max(stock_df['Close']),2)
    stock_df = stock_df[(stock_df.index <= end_date) & (stock_df.index >= start_date)]
    stock_df['200_SMA'] = round(stock_df['Close'].rolling(window = 200, min_periods = 1).mean(),0)
    stock_df['Dev%_200'] = round((stock_df['Close'] - stock_df['200_SMA'])*100/stock_df['200_SMA'],2)
    stock_df.dropna(axis = 0, inplace = True) # remove any null rows

    stock_df['20_SMA'] = stock_df['Close'].rolling(window=20).mean()
    stock_df['50_SMA'] = stock_df['Close'].rolling(window=50).mean()
    stock_df['Symbol'] = stock_symbol

    stock_df['Close'] = round(stock_df['Close'],2)
    stock_df['Min'] = round(min(stock_df['Close']),2)
    stock_df['RSI_14'] = ta.momentum.RSIIndicator(close=stock_df['Close'], window=14).rsi()
    stock_df['RSI_14'] = round(stock_df['RSI_14'],0)
    stock_df['Prev_Close'] = stock_df['Close'].shift(1)
    stock_df.drop(['Open', 'Low', 'High', 'Volume'], axis=1, inplace=True)
    stock_df = stock_df.tail(1)

    max_SMA = max(stock_df['20_SMA'].item(), stock_df['50_SMA'].item(), stock_df['200_SMA'].item())
    min_SMA = min(stock_df['20_SMA'].item(), stock_df['50_SMA'].item(), stock_df['200_SMA'].item())
    ABS_Spread = max_SMA - min_SMA
    stock_df['Spread%'] = round((ABS_Spread / stock_df['200_SMA'].item()) * 100,2)

    return stock_df

# function to compute stock attributes
def get_common_features(stock_ids, df_mypf):

  df_prec_dev = pd.DataFrame()
  df_tmp = get_screener_features()
  df_rs = get_relative_strength(stock_ids)

  for stock_id in stock_ids:
      tmp = stock_prec_dev(stock_id)
      tmp = tmp.reset_index()
      df_prec_dev = pd.concat([df_prec_dev, tmp], ignore_index = True)
  df_prec_dev = pd.merge(df_prec_dev, df_mypf, on= 'Symbol')
  df_prec_dev = pd.merge(df_prec_dev, df_tmp, on= 'Symbol', how='left')
  df_prec_dev = pd.merge(df_prec_dev, df_rs, on= 'Symbol', how='left')
  #print(df_prec_dev.columns)
  df_prec_dev['Curr_PE'] = round(df_prec_dev['Close']/df_prec_dev['EPS'],1)
  df_prec_dev['Dev%_PE'] = round((df_prec_dev['Curr_PE'] - df_prec_dev['MedPE'])*100/df_prec_dev['MedPE'],2)
  df_prec_dev['Conviction'] = df_prec_dev['Conviction'] + '-' + df_prec_dev['CapType']
  return df_prec_dev

# function to arrange stock features
def arrange_features(df_stocks, common_cols, diff_cols):
  df_stocks_common = df_stocks[common_cols].drop_duplicates()
  df_stocks_diff = df_stocks[diff_cols]
  df_stocks_diff['Investment'] = df_stocks_diff['AvgCost'] * df_stocks_diff['Shares']
  df_stocks_diff = df_stocks_diff.groupby(['Symbol'])[['Shares', 'Investment']].aggregate(['sum']).reset_index()
  df_stocks_diff.columns = ['Symbol', 'Shares', 'Investment']
  df_stocks_diff['AvgCost'] = round(df_stocks_diff['Investment']/df_stocks_diff['Shares'],2)
  df_stocks = pd.merge(df_stocks_diff, df_stocks_common, on='Symbol')
  return df_stocks

# plot fact distribution across dimension
def plot_pie_chart(df, dimension, fact):
  # grouping the data by category and calculating the sum of fact for each type
  grouped_data = df.groupby(dimension)[fact].sum()

  # sorting the grouped data in descending order
  grouped_data = grouped_data.sort_values(ascending=False)

  # creating a pie chart
  grouped_data.plot.pie(autopct='%1.1f%%', startangle=90, figsize=(6, 6))

  # adding a title and displaying the plot
  plt.title(f'{dimension} {fact} Distribution')
  plt.ylabel('')  # To hide the y-label
  plt.show()

In [7]:
# function to get portfolio features

def get_portfolio_features(df_common_features):

  print_date_time()
  print('-------------------')

  #df_common_features["Target"] = df_common_features["Target"].fillna(df_common_features["Max"])
  df_common_features['NTT'] = np.where(df_common_features['Strategy']== 'NTT', df_common_features["Target"], df_common_features['Max'])
  df_common_features['LTT'] = np.where(df_common_features['Strategy']== 'BTT', df_common_features["Target"], df_common_features['Max'])
  df_common_features['BOL'] = df_common_features['Min']

  tmp_df = df_common_features[df_common_features['Symbol'].isin(mypf_df[mypf_df['InPortfolio'] != 'NA'].Symbol.values)]
  print('qualified stocks: '+str(len(tmp_df['Symbol'].unique())))
  tmp_df1 = tmp_df[tmp_df['LatestQtr'] == 1]
  print('with latest results: '+str(len(tmp_df1['Symbol'].unique())))
  tmp_df1 = tmp_df1[tmp_df1['StarStock'] == 1]
  print('still star stocks: '+str(len(tmp_df1['Symbol'].unique())))
  tmp_df['Investment'] = tmp_df['AvgCost'] * tmp_df['Shares']
  tmp_df['Current'] = round(tmp_df['Close'] * tmp_df['Shares'],0)
  tmp_df['Previous'] = tmp_df['Prev_Close'] * tmp_df['Shares']
  tmp_df['EstimatedST'] = tmp_df['NTT'] * tmp_df['Shares']
  tmp_df['EstimatedLT'] = tmp_df['LTT'] * tmp_df['Shares']
  tmp_df['Current P/L'] = round((tmp_df['Current'] - tmp_df['Investment']),0)
  tmp_df['Today P/L%'] = round((tmp_df['Current'] - tmp_df['Previous'])*100/tmp_df['Previous'],2)
  tmp_df['Current P/L%'] = round((tmp_df['Current'] - tmp_df['Investment'])*100/tmp_df['Investment'],2)
  tmp_df['EstimatedST P/L%'] = round((tmp_df['EstimatedST'] - tmp_df['Investment'])*100/tmp_df['Investment'],2)
  tmp_df['EstimatedLT P/L%'] = round((tmp_df['EstimatedLT'] - tmp_df['Investment'])*100/tmp_df['Investment'],2)
  tmp_df['NTT%'] = round((tmp_df['NTT'] - tmp_df['Close'])*100/tmp_df['Close'],2)
  tmp_df['LTT%'] = round((tmp_df['LTT'] - tmp_df['Close'])*100/tmp_df['Close'],2)
  tmp_df['Gained%'] = round((tmp_df['Close'] - tmp_df['BOL'])*100/tmp_df['BOL'],2)
  investment = round(sum(tmp_df['AvgCost']*tmp_df['Shares']),0)
  current = round(sum(tmp_df['Close']*tmp_df['Shares']),0)
  tmp_df['InitAlloc%'] = round(tmp_df['Investment']*100/investment,2)
  tmp_df['CurrAlloc%'] = round(tmp_df['Current']*100/current,2)
  tmp_df['FTT'] = tmp_df['LTT']
  tmp_df.loc[tmp_df['Strategy'] == 'NTT', 'FTT'] = tmp_df['NTT']
  tmp_df['FTT%'] = tmp_df['LTT%']
  tmp_df.loc[tmp_df['Strategy'] == 'NTT', 'FTT%'] = tmp_df['NTT%']
  tmp_df['FTT Amt'] = round(tmp_df['FTT%'] * tmp_df['Current']/100,0)
  tmp_df['OTT%'] = round((tmp_df['FTT'] - tmp_df['AvgCost'])*100/tmp_df['AvgCost'],2)
  tmp_df['RRR Ind'] = round(tmp_df['Current P/L']/tmp_df['FTT Amt'],2)
  tmp_df['Risk Ind'] = round(tmp_df['Current P/L%']*tmp_df['CurrAlloc%'],0)

  return tmp_df

# function to print portfolio features
def print_portfolio_stats(df_portfolio_features, myinvmt_df):
  from pyxirr import xirr

  total_booked_amt, reserve_amt, cy_booked_amt, py_booked_amt = get_amt()

  dates = myinvmt_df['Date'].values
  dates = np.append(dates, datetime.date.today().strftime('%d-%b-%y'))
  investment = myinvmt_df['Investment'].values
  dates= pd.to_datetime(dates)

  current = round(sum(df_portfolio_features['Close']*df_portfolio_features['Shares']),0) + reserve_amt
  investment_xirr = np.append(investment, current)
  cagr = round(xirr(pd.DataFrame({"dates": dates, "amounts": investment_xirr}))*100,2)

  investment = -sum(investment)
  invested = round(sum(df_portfolio_features['AvgCost']*df_portfolio_features['Shares']),0) + reserve_amt
  previous = round(sum(df_portfolio_features['Prev_Close']*df_portfolio_features['Shares']),0) + reserve_amt
  cy_invested = investment + py_booked_amt

  today_pnl_amount = current-previous
  today_pnl_percentage = round((current-previous)*100/previous,2)

  curr_pnl_amount = current-invested
  curr_pnl_percentage = round((curr_pnl_amount)*100/(cy_invested),2)

  cy_pnl_amount = cy_booked_amt + curr_pnl_amount
  cy_pnl_percentage = round((cy_pnl_amount)*100/cy_invested,2)

  overall_pnl_amount = total_booked_amt + curr_pnl_amount
  overall_pnl_percentage = round((overall_pnl_amount)*100/investment,2)

  estimate_st = round(sum(df_portfolio_features['FTT']*df_portfolio_features['Shares']),0)  + reserve_amt
  est_st_pnl_amount = estimate_st-current
  est_st_pnl_percentage = round((est_st_pnl_amount)*100/current,2)

  estimate_lt = round(sum(df_portfolio_features['LTT']*df_portfolio_features['Shares']),0)  + reserve_amt
  est_lt_pnl_amount = estimate_lt-current
  est_lt_pnl_percentage = round((est_lt_pnl_amount)*100/current,2)

  total_profit = round(sum(df_portfolio_features[df_portfolio_features['Current P/L%'] > 0]['Current']) - sum(df_portfolio_features[df_portfolio_features['Current P/L%'] > 0]['Investment']),0)
  total_loss = round(sum(df_portfolio_features[df_portfolio_features['Current P/L%'] < 0]['Current']) - sum(df_portfolio_features[df_portfolio_features['Current P/L%'] < 0]['Investment']),0)

  cy_booked_percentage = round((cy_booked_amt)*100/current,2)
  py_booked_percentage = round((py_booked_amt)*100/investment,2)
  total_booked_percentage = round((total_booked_amt)*100/investment,2)

  print('-------------------')
  print('Initial Investment: ', format_amt(investment))
  print('CY Investment: ', format_amt(cy_invested))
  print('Reserve: ', format_amt(reserve_amt))
  print('Current: ',  format_amt(current))
  print('-------------------')
  print('Today PnL: '+ '{} ({}%)'.format(format_amt(today_pnl_amount), today_pnl_percentage))
  print('Current PnL: '+ '{} ({}%)'.format(format_amt(curr_pnl_amount), curr_pnl_percentage))
  print('CY Booked + Current PnL: '+ '{} ({}%)'.format(format_amt(cy_pnl_amount), cy_pnl_percentage))
  print('-------------------')
  print('Total profit: ', format_amt(total_profit))
  print('Total loss: ', format_amt(total_loss))
  print('-------------------')
  print('Total Booked + Current PnL: '+ '{} ({}%)'.format(format_amt(overall_pnl_amount), overall_pnl_percentage))
  print('Total Booked PnL: '+ '{} ({}%)'.format(format_amt(total_booked_amt), total_booked_percentage))
  print('Curr Year Booked PnL: '+ '{} ({}%)'.format(format_amt(cy_booked_amt), cy_booked_percentage))
  print('Prev Year Booked PnL: '+ '{} ({}%)'.format(format_amt(py_booked_amt), py_booked_percentage))
  print('===================')
  print('Est FTT: ',  format_amt(estimate_st))
  print('Est FTT PnL: '+ '{} ({}%)'.format(format_amt(est_st_pnl_amount), est_st_pnl_percentage))

  print('===================')
  print('Deployed: ', format_amt(investment))

  print('Current: ', format_amt(current))

  print('CAGR/XIRR %: '+'{}%'.format(cagr))

In [8]:
# get start and end date
start_date, end_date = get_start_end_date()

# get portfolio and prospects data
mypfs_df = get_mypfs_df()
mypps_df = get_mypps_df()
myinvmt_df = get_myinvmt_df()

# merge above datasets
mypf_df = pd.merge(mypfs_df, mypps_df, on="Symbol")

# seggregate dm and sv portfolio
dm_pf = mypf_df[mypf_df['InPortfolio'] == 'DM']
sv_pf = mypf_df[mypf_df['InPortfolio'] == 'SV']

# build portfolio stock dataframe
dm_stocks = get_stock_ids(dm_pf)
sv_stocks = get_stock_ids(sv_pf)
df_stocks = pd.concat([dm_pf,sv_pf], ignore_index = True)

# arrange common and diff stock features
common_cols = ['Symbol', 'Target', 'Criteria', 'Strategy', 'CumlRnk', 'LatestQtr', 'StarStock', 'Conviction', 'Category', 'InFolio', 'XIRR', 'MBQ']
diff_cols = ['Symbol', 'AvgCost', 'Shares']
df_stocks = arrange_features(df_stocks, common_cols, diff_cols)

# get common features
stock_ids = df_stocks['Symbol'].values
df_common_features = get_common_features(stock_ids, df_stocks)

df_common_features.reset_index(drop=True, inplace=True)
df_common_features.drop(['Date'], axis=1, inplace=True)
# get and print portfolio features
df_portfolio_features = get_portfolio_features(df_common_features)

print_portfolio_stats(df_portfolio_features, myinvmt_df)

df = df_portfolio_features
#plot_pie_chart(df, 'CapType', 'Current')
list_ox40n = list(df[df['MBQ'].str.contains('OX40N', na=False)]['Symbol'].values)

Run date time (IST): 2026-04-23 15:57:47
-------------------
qualified stocks: 92
with latest results: 31
still star stocks: 20
-------------------
Initial Investment:  1.40 C
CY Investment:  1.82 C
Reserve:  1.49 K
Current:  1.49 C
-------------------
Today PnL: -96.70 K (-0.65%)
Current PnL: -34.41 L (-18.87%)
CY Booked + Current PnL: -32.33 L (-17.73%)
-------------------
Total profit:  1.10 L
Total loss:  -35.51 L
-------------------
Total Booked + Current PnL: 10.54 L (7.55%)
Total Booked PnL: 44.95 L (32.22%)
Curr Year Booked PnL: 2.08 L (1.4%)
Prev Year Booked PnL: 42.87 L (30.73%)
===================
Est FTT:  2.56 C
Est FTT PnL: 1.07 C (71.79%)
===================
Deployed:  1.40 C
Current:  1.49 C
CAGR/XIRR %: 3.23%

In [9]:
# top 5 near their targets
cols = ['Symbol', 'Today P/L%', 'Current P/L%', 'FTT%', 'OTT%', 'FTT Amt', 'Current P/L', 'Current', 'FTT', 'Dev%_PE', 'RSI_14','Conviction', 'Spread%',  'CumlRnk', 'RRR Ind', 'CurrAlloc%', 'Gained%', 'Criteria', 'Strategy', 'Category']
df_tmp = df_portfolio_features[~df_portfolio_features['Symbol'].isin(['ENRIN','BLUSPRING','DIGITIDE'])]
df_tmp = df_tmp.sort_values(by = 'FTT Amt', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
55,MASFIN,-1.01,-2.08,24.15,21.57,23170.0,-2040.0,95940.0,397.04,-15.54,58.0,H-SC,2.66,167.0,-0.09,0.64,23.98,XR,ATH,FINANCE
59,PIDILITIND,-1.19,-0.64,19.13,18.37,26822.0,-900.0,140210.0,1670.26,-30.44,56.0,X-LC,8.66,5.0,-0.03,0.94,10.09,X40,ATH,CHEMICALS
51,KOTAKBANK,-1.71,-1.03,22.37,21.11,30658.0,-1424.0,137048.0,453.24,-15.04,45.0,X-LC,10.15,12.0,-0.05,0.92,4.81,X40,ATH,BANKS
83,TTKPRESTIG,2.84,-32.40,48.06,0.09,32742.0,-32650.0,68127.0,770.00,58.16,62.0,M-SC,22.19,250.0,-1.00,0.46,21.31,OX40N,NTT,DURABLES
53,M&M,-3.24,-1.11,24.76,23.38,33957.0,-1535.0,137146.0,3802.40,-16.17,42.0,X-LC,9.27,25.0,-0.05,0.92,7.26,X40N,ATH,AUTO

In [10]:
# top 5 today
df_tmp = df_portfolio_features.sort_values(by = 'Today P/L%', ascending=False)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
62,RAJOOENG,6.38,-29.71,98.61,39.61,71049.0,-30450.0,72050.0,143.1,-52.38,69.0,H-SC,26.45,136.0,-0.43,0.48,54.35,AR,ATH,MISC
17,CIPLA,5.63,5.73,27.39,34.69,44353.0,8771.0,161932.0,1663.6,-18.19,64.0,X-LC,15.60,18.0,0.20,1.09,9.52,X40N,ATH,PHARMA
61,RAJESHEXPO,4.99,-75.14,302.52,0.07,103168.0,-103074.0,34103.0,518.0,1150.00,62.0,L-SC,39.12,268.0,-1.00,0.23,60.10,OX40N,NTT,JEWELLERY
48,JIOFIN,4.26,-17.48,55.63,28.43,136946.0,-52154.0,246173.0,387.0,-18.75,56.0,X-LC,18.31,34.0,-0.38,1.65,10.96,XY24,BTT,FINANCE
83,TTKPRESTIG,2.84,-32.40,48.06,0.09,32742.0,-32650.0,68127.0,770.0,58.16,62.0,M-SC,22.19,250.0,-1.00,0.46,21.31,OX40N,NTT,DURABLES

In [11]:
# bottom 5 today
df_tmp = df_portfolio_features.sort_values(by = 'Today P/L%', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
32,HAVELLS,-6.55,-19.31,63.68,32.08,168537.0,-63328.0,264663.0,2062.85,-24.09,45.0,X-MC,12.45,63.0,-0.38,1.78,6.75,X40,ATH,ELECTRICAL
22,DIXON,-3.55,-20.83,74.22,37.92,153238.0,-54334.0,206464.0,18931.72,-66.35,52.0,X-MC,24.40,54.0,-0.35,1.39,12.34,X40N,ATH,IT
53,M&M,-3.24,-1.11,24.76,23.38,33957.0,-1535.0,137146.0,3802.40,-16.17,42.0,X-LC,9.27,25.0,-0.05,0.92,7.26,X40N,ATH,AUTO
78,TATAELXSI,-2.96,-38.99,116.39,32.03,93619.0,-51399.0,80436.0,9161.00,-23.72,42.0,H-SC,17.70,158.0,-0.55,0.54,6.46,OX40N,NTT,IT
81,TMPV,-2.74,-19.89,70.48,36.58,200924.0,-70761.0,285080.0,600.00,-83.62,57.0,X-LC,8.42,4.0,-0.35,1.92,18.82,XY24,NTT,AUTO

In [12]:
# top 5 to exit based on CumlRnk
df_tmp = df_portfolio_features[~df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])]
df_tmp = df_tmp[(df_tmp['Current P/L%'] > -1) & (df_tmp['Current P/L%'] < 1)].sort_values(by = 'CumlRnk', ascending=False)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
73,SONACOMS,-2.36,-0.61,39.94,39.09,40158.0,-613.0,100546.0,804.02,-21.28,60.0,M-MC,11.89,193.0,-0.02,0.68,42.24,AR,ATH,AUTO
74,STARHEALTH,1.49,-0.07,47.37,47.26,133073.0,-201.0,280922.0,761.00,57.63,73.0,H-SC,3.61,173.0,-0.00,1.89,45.49,XY24,NTT,INSURANCE
91,ZYDUSLIFE,1.77,-0.21,35.91,35.63,75103.0,-431.0,209143.0,1286.17,-13.06,63.0,H-MC,4.35,120.0,-0.01,1.41,11.35,AR,ATH,PHARMA

In [13]:
# OX40N stocks to exit
df_tmp = df_portfolio_features[(df_portfolio_features['Symbol'].isin(list_ox40n))].sort_values(by = 'Current P/L%', ascending=False)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
25,FINCABLES,-0.76,22.65,69.51,107.91,125876.0,33447.0,181091.0,1641.55,10.10,69.0,M-SC,4.76,220.0,0.27,1.22,36.24,OX40N,ATH,CABLES
72,SIS,-2.33,-24.30,60.19,21.26,50588.0,-26984.0,84048.0,528.00,1982.90,67.0,H-SC,8.39,168.0,-0.53,0.57,24.97,OX40N,NTT,MISC
16,CERA,-0.35,-28.48,73.22,23.89,92114.0,-50098.0,125805.0,9475.00,-31.03,71.0,H-SC,12.99,153.0,-0.54,0.85,20.90,OX40N,NTT,CERAMICS
83,TTKPRESTIG,2.84,-32.40,48.06,0.09,32742.0,-32650.0,68127.0,770.00,58.16,62.0,M-SC,22.19,250.0,-1.00,0.46,21.31,OX40N,NTT,DURABLES
50,KANSAINER,-1.62,-33.01,69.38,13.47,125340.0,-89010.0,180657.0,340.00,-42.48,60.0,H-SC,18.58,162.0,-0.71,1.21,26.19,XY24,NTT,PAINTS

In [14]:
# top 5 to book for rotation
df_tmp = df_portfolio_features[(df_portfolio_features['Current P/L%'] > 20) ].sort_values(by = 'CumlRnk', ascending=False)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
25,FINCABLES,-0.76,22.65,69.51,107.91,125876.0,33447.0,181091.0,1641.55,10.1,69.0,M-SC,4.76,220.0,0.27,1.22,36.24,OX40N,ATH,CABLES

In [15]:
# top 5 to monitor for exit
df_tmp = df_portfolio_features[~df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])]
df_tmp = df_tmp[(df_tmp['Current P/L%'] > 0) ].sort_values(by = 'Dev%_PE', ascending=False)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
63,RECLTD,-1.80,1.91,18.48,20.74,38262.0,3878.0,207048.0,446.00,11.33,65.0,M-MC,3.73,191.0,0.10,1.39,23.39,XY25,NTT,FINANCE
25,FINCABLES,-0.76,22.65,69.51,107.91,125876.0,33447.0,181091.0,1641.55,10.10,69.0,M-SC,4.76,220.0,0.27,1.22,36.24,OX40N,ATH,CABLES

In [16]:
# top 5 to book for rotation from weak conviction
df_tmp = df_portfolio_features[~df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])]
df_tmp = df_tmp[~df_tmp['Criteria'].isin(['XY25','XY24','X40', 'X40N'])].sort_values(by = 'RRR Ind', ascending=False)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
25,FINCABLES,-0.76,22.65,69.51,107.91,125876.0,33447.0,181091.0,1641.55,10.10,69.0,M-SC,4.76,220.0,0.27,1.22,36.24,OX40N,ATH,CABLES
91,ZYDUSLIFE,1.77,-0.21,35.91,35.63,75103.0,-431.0,209143.0,1286.17,-13.06,63.0,H-MC,4.35,120.0,-0.01,1.41,11.35,AR,ATH,PHARMA
73,SONACOMS,-2.36,-0.61,39.94,39.09,40158.0,-613.0,100546.0,804.02,-21.28,60.0,M-MC,11.89,193.0,-0.02,0.68,42.24,AR,ATH,AUTO
42,INDIAMART,-0.42,-7.21,122.78,106.72,140519.0,-8888.0,114448.0,4810.62,-58.20,58.0,H-SC,11.12,140.0,-0.06,0.77,9.95,AR,ATH,MISC
55,MASFIN,-1.01,-2.08,24.15,21.57,23170.0,-2040.0,95940.0,397.04,-15.54,58.0,H-SC,2.66,167.0,-0.09,0.64,23.98,XR,ATH,FINANCE

In [17]:
# top 5 to accumulate based on lowest RSI_14
df_tmp = df_portfolio_features[df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])].sort_values(by = 'RSI_14', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
33,HCLTECH,-0.60,-17.09,49.36,23.83,99008.0,-41341.0,200583.0,1908.19,-12.74,31.0,X-LC,7.33,8.0,-0.42,1.35,0.00,X40,ATH,IT
45,INFY,-2.21,-15.55,58.96,34.24,155801.0,-48640.0,264248.0,1972.00,-33.60,37.0,X-LC,12.50,3.0,-0.31,1.78,1.62,X40,NTT,IT
1,ABBOTINDIA,-0.04,-14.76,38.51,18.07,58712.0,-26395.0,152460.0,35195.00,-27.52,39.0,X-MC,11.95,58.0,-0.45,1.02,0.10,X40,ATH,PHARMA
40,ICICIPRULI,-0.88,-11.42,47.58,30.73,83031.0,-22497.0,174508.0,790.00,-35.24,39.0,X-MC,13.13,78.0,-0.27,1.17,6.34,X40,ATH,INSURANCE
35,HDFCLIFE,-0.89,-2.09,36.02,33.18,52830.0,-3131.0,146669.0,814.30,-23.52,42.0,X-LC,17.89,31.0,-0.06,0.99,5.75,X40,ATH,INSURANCE

In [18]:
# top 5 to accumulate based on Spread and CumlRnk
df_tmp = df_portfolio_features[df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])]
df_tmp = df_tmp[(df_tmp['CumlRnk'] < 100)].sort_values(by = 'Spread%', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
71,SIEMENS,0.52,3.83,20.89,25.51,40364.0,7125.0,193220.0,4671.50,62.33,76.0,H-LC,4.78,51.0,0.18,1.30,36.38,AR,ATH,ELECTRICAL
84,UNITDSPR,-0.75,1.54,18.93,20.77,45007.0,3612.0,237756.0,1644.00,-10.02,62.0,X-MC,5.45,64.0,0.08,1.60,13.41,X40N,NTT,BREWERIES
65,RELIANCE,-1.37,-13.77,45.30,25.30,78504.0,-27664.0,173299.0,1952.00,-16.19,46.0,X-LC,5.87,21.0,-0.35,1.17,3.75,XY25,BTT,REFINERIES
88,VOLTAS,-2.44,13.08,28.40,45.20,61578.0,25083.0,216825.0,1856.00,29.40,58.0,X-MC,6.10,79.0,0.41,1.46,20.77,XY25,NTT,AC
23,DMART,-1.60,8.68,19.25,29.60,52220.0,21672.0,271272.0,5391.45,-8.36,64.0,X-LC,6.36,14.0,0.42,1.82,23.99,X40N,ATH,FMCG

In [19]:
# top 5 to accumulate based on lowest Gained%
df_tmp = df_portfolio_features[df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])].sort_values(by = 'Gained%', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
33,HCLTECH,-0.60,-17.09,49.36,23.83,99008.0,-41341.0,200583.0,1908.19,-12.74,31.0,X-LC,7.33,8.0,-0.42,1.35,0.00,X40,ATH,IT
1,ABBOTINDIA,-0.04,-14.76,38.51,18.07,58712.0,-26395.0,152460.0,35195.00,-27.52,39.0,X-MC,11.95,58.0,-0.45,1.02,0.10,X40,ATH,PHARMA
45,INFY,-2.21,-15.55,58.96,34.24,155801.0,-48640.0,264248.0,1972.00,-33.60,37.0,X-LC,12.50,3.0,-0.31,1.78,1.62,X40,NTT,IT
65,RELIANCE,-1.37,-13.77,45.30,25.30,78504.0,-27664.0,173299.0,1952.00,-16.19,46.0,X-LC,5.87,21.0,-0.35,1.17,3.75,XY25,BTT,REFINERIES
51,KOTAKBANK,-1.71,-1.03,22.37,21.11,30658.0,-1424.0,137048.0,453.24,-15.04,45.0,X-LC,10.15,12.0,-0.05,0.92,4.81,X40,ATH,BANKS

In [20]:
# top 5 to accumulate based on lowest CurrAlloc%
df_tmp = df_portfolio_features[df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])].sort_values(by = 'CurrAlloc%', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
64,RELAXO,-0.69,-59.91,279.89,52.31,162888.0,-86963.0,58197.0,1176.00,-57.31,58.0,X-SC,30.60,92.0,-0.53,0.39,30.12,X40N,NTT,FOOTWEAR
10,BATAINDIA,-2.48,-51.29,177.58,35.20,111295.0,-65997.0,62673.0,2096.00,-17.83,59.0,X-SC,30.12,91.0,-0.59,0.42,24.30,X40,NTT,FOOTWEAR
60,QUESS,-2.57,-20.97,120.04,73.90,101311.0,-22395.0,84398.0,424.00,-57.58,54.0,X-SC,18.24,80.0,-0.22,0.57,13.53,XY24,NTT,MISC
53,M&M,-3.24,-1.11,24.76,23.38,33957.0,-1535.0,137146.0,3802.40,-16.17,42.0,X-LC,9.27,25.0,-0.05,0.92,7.26,X40N,ATH,AUTO
51,KOTAKBANK,-1.71,-1.03,22.37,21.11,30658.0,-1424.0,137048.0,453.24,-15.04,45.0,X-LC,10.15,12.0,-0.05,0.92,4.81,X40,ATH,BANKS

In [21]:
# top 5 to accumulate based on CumlRnk
df_tmp = df_portfolio_features.sort_values(by = 'CumlRnk', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
47,ITC,-0.07,-19.58,48.05,19.06,131440.0,-66617.0,273549.0,452.00,-55.92,52.0,X-LC,18.70,1.0,-0.51,1.84,6.12,X40,NTT,FMCG
79,TCS,-0.66,-25.97,70.97,26.57,243402.0,-120308.0,342965.0,4311.59,-37.40,48.0,X-LC,15.35,2.0,-0.49,2.31,7.04,X40,ATH,IT
45,INFY,-2.21,-15.55,58.96,34.24,155801.0,-48640.0,264248.0,1972.00,-33.60,37.0,X-LC,12.50,3.0,-0.31,1.78,1.62,X40,NTT,IT
81,TMPV,-2.74,-19.89,70.48,36.58,200924.0,-70761.0,285080.0,600.00,-83.62,57.0,X-LC,8.42,4.0,-0.35,1.92,18.82,XY24,NTT,AUTO
59,PIDILITIND,-1.19,-0.64,19.13,18.37,26822.0,-900.0,140210.0,1670.26,-30.44,56.0,X-LC,8.66,5.0,-0.03,0.94,10.09,X40,ATH,CHEMICALS

In [22]:
# top 5 for average up
df_tmp = df_portfolio_features[(df_portfolio_features['Dev%_200'] > 5)].sort_values(by = 'CurrAlloc%', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
73,SONACOMS,-2.36,-0.61,39.94,39.09,40158.0,-613.0,100546.0,804.02,-21.28,60.0,M-MC,11.89,193.0,-0.02,0.68,42.24,AR,ATH,AUTO
75,SURYODAY,-2.18,-17.09,48.40,23.03,71855.0,-30610.0,148461.0,216.00,62.28,62.0,H-SC,3.28,166.0,-0.43,1.00,26.61,XR,NTT,BANKS
25,FINCABLES,-0.76,22.65,69.51,107.91,125876.0,33447.0,181091.0,1641.55,10.10,69.0,M-SC,4.76,220.0,0.27,1.22,36.24,OX40N,ATH,CABLES
71,SIEMENS,0.52,3.83,20.89,25.51,40364.0,7125.0,193220.0,4671.50,62.33,76.0,H-LC,4.78,51.0,0.18,1.30,36.38,AR,ATH,ELECTRICAL
63,RECLTD,-1.80,1.91,18.48,20.74,38262.0,3878.0,207048.0,446.00,11.33,65.0,M-MC,3.73,191.0,0.10,1.39,23.39,XY25,NTT,FINANCE

In [23]:
# top 5 RSP
df_tmp = df_portfolio_features.sort_values(by = 'RSP', ascending=False)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
61,RAJESHEXPO,4.99,-75.14,302.52,0.07,103168.0,-103074.0,34103.0,518.0,1150.00,62.0,L-SC,39.12,268.0,-1.00,0.23,60.10,OX40N,NTT,JEWELLERY
62,RAJOOENG,6.38,-29.71,98.61,39.61,71049.0,-30450.0,72050.0,143.1,-52.38,69.0,H-SC,26.45,136.0,-0.43,0.48,54.35,AR,ATH,MISC
71,SIEMENS,0.52,3.83,20.89,25.51,40364.0,7125.0,193220.0,4671.5,62.33,76.0,H-LC,4.78,51.0,0.18,1.30,36.38,AR,ATH,ELECTRICAL
87,VBL,-2.16,-2.18,38.52,35.50,119008.0,-6890.0,308952.0,670.8,-13.69,67.0,X-LC,7.89,13.0,-0.06,2.08,26.86,X40N,ATH,FMCG
66,REPCOHOME,0.39,-8.26,106.91,89.82,280997.0,-23670.0,262835.0,880.0,-53.80,70.0,H-SC,2.78,161.0,-0.08,1.77,26.35,XY24,NTT,FINANCE

In [24]:
# Top N allocation
df_tmp = df_portfolio_features.sort_values(by = 'CurrAlloc%', ascending=False)
top_n_values = [10, 25, 50]

sum_df = pd.DataFrame({
    'Top_N': top_n_values,
    'Sum_Alloc%': [df_tmp['CurrAlloc%'].head(n).sum() for n in top_n_values]
})

sum_df

   Top_N  Sum_Alloc%
0     10       18.98
1     25       42.70
2     50       72.77

In [25]:
# market-cap-wise allocation
df_tmp = df_portfolio_features[cols]
df_tmp.groupby(df_tmp['Conviction'].str[-2:])['CurrAlloc%'].sum().sort_values(ascending=False)

Conviction
SC    41.71
LC    32.03
MC    26.30
Name: CurrAlloc%, dtype: float64

In [26]:
# criteria-wise allocation
df_portfolio_features.groupby('Criteria')['CurrAlloc%'].sum().sort_values(ascending=False)

Criteria
XY24     26.50
X40      26.09
X40N     17.01
XR        8.97
XY25      7.06
AR        6.84
OX40N     6.78
SR        0.79
Name: CurrAlloc%, dtype: float64

In [27]:
# conviction-wise allocation
df_portfolio_features.groupby('Conviction')['CurrAlloc%'].sum().sort_values(ascending=False)

Conviction
X-LC    29.78
H-SC    21.51
X-MC    21.28
M-SC     9.89
X-SC     9.73
H-MC     2.62
M-MC     2.07
H-LC     1.30
M-LC     0.95
L-SC     0.58
L-MC     0.33
Name: CurrAlloc%, dtype: float64

In [28]:
# sector-wise stats
df_tmp = df_portfolio_features.groupby('Category')[['CurrAlloc%', 'Current', 'Current P/L', 'FTT Amt']].sum().sort_values(by=['Current', 'Current P/L'], ascending=False)
df_tmp['Current P/L%'] = round(df_tmp['Current P/L'] * 100 / df_tmp['Current'], 2)
df_tmp['FTT%'] = round(df_tmp['FTT Amt'] * 100 / df_tmp['Current'], 2)
cols = ['CurrAlloc%', 'Current P/L%', 'FTT%']
df_tmp[cols].sort_values(by=['CurrAlloc%'], ascending=False)

               CurrAlloc%  Current P/L%    FTT%
Category
FMCG                15.68        -13.49   53.55
FINANCE             10.80        -14.75   64.65
IT                  10.76        -40.92  112.63
MISC                 6.90        -30.69   87.46
AUTO                 6.59        -11.75   53.64
INSURANCE            5.34         -4.29   39.79
BANKS                5.30        -15.26   68.55
PAINTS               5.17        -28.10   50.35
PHARMA               4.86         -2.46   35.39
ELECTRICAL           4.18        -13.81   54.33
AC                   1.99         -7.98   37.25
CHEMICALS            1.98        -37.51  119.45
HEALTHCARE           1.87        -28.60   62.16
APPARELS             1.79         -0.99   35.44
DURABLES             1.76        -48.20   84.25
FOOTWEAR             1.76        -68.20  135.64
TRAVEL               1.72        -75.37  163.18
BREWERIES            1.60          1.52   18.93
REALTY               1.39         -7.08   24.67
CERAMICS             1.32        -56.53  104.08
CABLES               1.22         18.47   69.51
REFINERIES           1.17        -15.96   45.30
CEMENT               1.15        -57.01  174.47
ENGINEERING          1.14        -43.19  108.68
JEWELLERY            1.07       -100.34  169.95
ENTERTAINMENT        0.75        -72.95  176.10
TEXTILES             0.43        -43.71   84.69
HOTELS               0.35       -118.88  196.08

In [29]:
# money to be made criteria-wise
df_portfolio_features.groupby('Criteria')['FTT Amt'].agg(['sum', 'count']).sort_values(by='sum', ascending=False)

                sum  count
Criteria
XY24      3657481.0     21
X40       1828538.0     19
XR        1347344.0     13
X40N      1195909.0     13
AR        1172939.0      9
OX40N      784628.0     10
XY25       391581.0      5
SR         301789.0      2

In [30]:
# money to be made conviction-wise
df_portfolio_features.groupby('Conviction')['FTT Amt'].agg(['sum', 'count']).sort_values(by='sum', ascending=False)

                  sum  count
Conviction
H-SC        3593640.0     24
X-LC        1876524.0     21
X-MC        1569411.0     15
M-SC        1445592.0     14
X-SC        1357774.0      9
H-MC         309053.0      2
L-SC         204890.0      2
M-LC         150980.0      1
M-MC          78420.0      2
L-MC          53561.0      1
H-LC          40364.0      1

In [31]:
# money to be made criteria and conviction-wise
df_portfolio_features.groupby(['Conviction', 'Criteria'])['FTT Amt'].agg(['sum', 'count']).sort_values(by='sum', ascending=False)

                           sum  count
Conviction Criteria
H-SC       XY24      1186955.0      6
X-LC       X40        986116.0     10
H-SC       AR         942354.0      5
M-SC       XY24       856088.0      6
H-SC       XR         819553.0      7
X-SC       XY24       808852.0      4
X-MC       X40        644192.0      7
           X40N       472201.0      4
X-LC       X40N       373016.0      6
X-SC       X40N       350692.0      3
H-SC       OX40N      342989.0      4
M-SC       OX40N      338471.0      5
X-LC       XY24       337870.0      2
H-SC       SR         301789.0      2
H-MC       XY24       233950.0      1
X-MC       XY24       233766.0      2
           XY25       219252.0      2
X-SC       X40        198230.0      2
M-SC       XR         176073.0      2
M-LC       XR         150980.0      1
X-LC       XY25       134067.0      2
L-SC       OX40N      103168.0      1
           XR         101722.0      1
H-MC       AR          75103.0      1
M-SC       AR          74960.0      1
L-MC       XR          53561.0      1
X-LC       XR          45455.0      1
H-LC       AR          40364.0      1
M-MC       AR          40158.0      1
           XY25        38262.0      1

In [32]:
# notebook execution time

end_time = time.time()
execution_time = round(end_time - start_time, 0)
print(f"Notebook execution time: {execution_time} seconds")

Notebook execution time: 27.0 seconds