<a href="https://colab.research.google.com/github/ankit-rathi/Quantvesting_v2/blob/main/myStocks_Portfolio_Analysis.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
'''
!pip install pandas==2.2.2 -qq
!pip install pyxirr -qq
!pip install ta -qq
!pip install yfinance==0.2.59 -qq
'''

'\n!pip install pandas==2.2.2 -qq\n!pip install pyxirr -qq\n!pip install ta -qq\n!pip install yfinance==0.2.59 -qq\n'

In [2]:
# import libraries

import numpy as np
import pandas as pd
import datetime
import warnings
warnings.filterwarnings('ignore')
import yfinance as yfin
import ta
import matplotlib.pyplot as plt
import requests

In [3]:
# notebook start time
import time
import datetime
import pytz

start_time = time.time()

# function to print date timestamp
def print_date_time():
  tz_NY = pytz.timezone('Asia/Kolkata')
  datetime_NY = datetime.datetime.now(tz_NY)
  print("Run date time (IST):", datetime_NY.strftime("%Y-%m-%d %H:%M:%S"))

In [4]:
# function to get booked and reserved amount
def get_amt():
  # fetch the JSON data from the URL
  url = "https://raw.githubusercontent.com/ankit-rathi/Tradevesting_v1/main/data/myPortfolioAmts.json"
  response = requests.get(url)
  pf_amts = response.json()  # parse the JSON data

  # extract values from the JSON
  py_booked_amt_dm = pf_amts["py_booked_amt_dm"]
  py_booked_amt_sv = pf_amts["py_booked_amt_sv"]
  cy_booked_amt_dm = pf_amts["cy_booked_amt_dm"]
  cy_booked_amt_sv = pf_amts["cy_booked_amt_sv"]
  reserve_amt_dm = pf_amts["reserve_amt_dm"]
  reserve_amt_sv = pf_amts["reserve_amt_sv"]

  # perform calculations
  py_booked_amt = py_booked_amt_dm + py_booked_amt_sv
  cy_booked_amt = cy_booked_amt_dm + cy_booked_amt_sv
  reserve_amt = reserve_amt_dm + reserve_amt_sv
  total_booked_amt = py_booked_amt + cy_booked_amt

  return total_booked_amt, reserve_amt, cy_booked_amt, py_booked_amt

gen_output = 0

In [5]:
# function to format the amount
def format_amt(number):
    abs_number = abs(number)

    if abs_number >= 1_00_00_000:  # Crores
        formatted_amt = f"{number / 1_00_00_000:.2f} C"
    elif abs_number >= 1_00_000:  # Lakhs
        formatted_amt = f"{number / 1_00_000:.2f} L"
    elif abs_number >= 1_000:  # Thousands
        formatted_amt = f"{number / 1_000:.2f} K"
    else:
        formatted_amt = f"{number:.2f}"

    return formatted_amt

# function to set start and end date
def get_start_end_date():
  start_date = (datetime.date.today() + datetime.timedelta(days=-365)).strftime('%Y-%m-%d')
  end_date = (datetime.date.today() + datetime.timedelta(days=1)).strftime('%Y-%m-%d')
  return start_date, end_date

# function to fetch my portfolio csv
def get_mypfs_df():
  mypfs_df = pd.read_csv('https://raw.githubusercontent.com/ankit-rathi/Tradevesting_v1/main/data/myPortfolioStocks.csv')
  return mypfs_df

# function to fetch my prospects csv
def get_mypps_df():
  mypps_df = pd.read_csv('https://raw.githubusercontent.com/ankit-rathi/Tradevesting_v1/main/data/myProspectsScrips.csv')
  return mypps_df

# function to fetch screener data
def get_myscreen_df():
  myscreen_df = pd.read_csv('https://raw.githubusercontent.com/ankit-rathi/Tradevesting_v1/main/data/myScreenerDB.csv')
  return myscreen_df

# function to fetch momentum data
def get_myinvmt_df():
  myinvmt_df = pd.read_csv('https://raw.githubusercontent.com/ankit-rathi/Tradevesting_v1/main/data/myInvestments.csv')
  return myinvmt_df

# function to get the stock ids
def get_stock_ids(df_pf):
  stock_n100 = df_pf['Symbol'].unique()

  exclude = ['CADILAHC','MMTC', 'MASFIN']

  stock_ids = df_pf[~df_pf['Symbol'].isin(exclude) ]['Symbol'].unique()

  #mypf = mypf[mypf.Forecast.notnull()]
  #stock_ids = mypf['Symbol'].unique()

  #stock_ids.sort()
  return stock_ids

# get features from screener data
def get_screener_features():
  myscreen_df = get_myscreen_df()
  cols = ['Symbol', 'EPS', 'MedPE', 'ROCE%', 'ROE%', 'CapType']
  return myscreen_df[cols]

# get relative strength
def get_relative_strength(stock_list):

    # Dictionary to store stock tickers and their corresponding percentage price change
    stock_changes = {}

    # Loop through each stock and fetch its price data
    for stock in stock_list:
        try:
            # Download the stock data for the given date range
            stock_data = yfin.Ticker(stock + '.NS').history(period='1mo', interval='1d')[map(str.title, ['open', 'close', 'low', 'high', 'volume'])]

            # Calculate the percentage change for the stock
            if len(stock_data) > 0:
                start_price = stock_data['Close'].iloc[0]
                end_price = stock_data['Close'].iloc[-1]
                percent_change = round(((end_price - start_price) / start_price) * 100, 2)
                stock_changes[stock] = percent_change
            else:
                stock_changes[stock] = np.nan  # If no data is available, set to NaN

        except Exception as e:
            print(f"Error fetching data for {stock}: {e}")
            stock_changes[stock] = np.nan

    # Create a DataFrame with stock tickers and their percentage changes
    df = pd.DataFrame(list(stock_changes.items()), columns=['Symbol', 'Percent_Change'])

    # Drop any stocks with missing data (NaN values)
    df = df.dropna()

    # Calculate the percentile rank based on percentage change
    df['RSP'] = round(df['Percent_Change'].rank(pct=True) * 100, 2)
    cols = ['Symbol', 'RSP']
    df = df[cols]
    # Sort by percentile rank (optional)
    df = df.sort_values(by='RSP', ascending=False).reset_index(drop=True)

    return df

In [6]:
# function to get stock technicals
def stock_prec_dev(stock_symbol):
    #stock_symbol = 'ULTRACEMCO.NS'
    short_window = 20
    mid_window = 50
    long_window = 200
    moving_avg = 'SMA'

    start = datetime.datetime(*map(int, start_date.split('-')))
    end = datetime.datetime(*map(int, end_date.split('-')))

    stock_df = yfin.Ticker(stock_symbol + '.NS').history(period='max', interval='1d')[map(str.title, ['open', 'close', 'low', 'high', 'volume'])]

    stock_df['Max'] = round(max(stock_df['Close']),2)
    stock_df = stock_df[(stock_df.index <= end_date) & (stock_df.index >= start_date)]
    stock_df['200_SMA'] = round(stock_df['Close'].rolling(window = 200, min_periods = 1).mean(),0)
    stock_df['Dev%_200'] = round((stock_df['Close'] - stock_df['200_SMA'])*100/stock_df['200_SMA'],2)
    stock_df.dropna(axis = 0, inplace = True) # remove any null rows

    stock_df['20_SMA'] = stock_df['Close'].rolling(window=20).mean()
    stock_df['50_SMA'] = stock_df['Close'].rolling(window=50).mean()
    stock_df['Symbol'] = stock_symbol

    stock_df['Close'] = round(stock_df['Close'],2)
    stock_df['Min'] = round(min(stock_df['Close']),2)
    stock_df['RSI_14'] = ta.momentum.RSIIndicator(close=stock_df['Close'], window=14).rsi()
    stock_df['RSI_14'] = round(stock_df['RSI_14'],0)
    stock_df['Prev_Close'] = stock_df['Close'].shift(1)
    stock_df.drop(['Open', 'Low', 'High', 'Volume'], axis=1, inplace=True)
    stock_df = stock_df.tail(1)

    max_SMA = max(stock_df['20_SMA'].item(), stock_df['50_SMA'].item(), stock_df['200_SMA'].item())
    min_SMA = min(stock_df['20_SMA'].item(), stock_df['50_SMA'].item(), stock_df['200_SMA'].item())
    ABS_Spread = max_SMA - min_SMA
    stock_df['Spread%'] = round((ABS_Spread / stock_df['200_SMA'].item()) * 100,2)

    return stock_df

# function to compute stock attributes
def get_common_features(stock_ids, df_mypf):

  df_prec_dev = pd.DataFrame()
  df_tmp = get_screener_features()
  df_rs = get_relative_strength(stock_ids)

  for stock_id in stock_ids:
      tmp = stock_prec_dev(stock_id)
      tmp = tmp.reset_index()
      df_prec_dev = pd.concat([df_prec_dev, tmp], ignore_index = True)
  df_prec_dev = pd.merge(df_prec_dev, df_mypf, on= 'Symbol')
  df_prec_dev = pd.merge(df_prec_dev, df_tmp, on= 'Symbol', how='left')
  df_prec_dev = pd.merge(df_prec_dev, df_rs, on= 'Symbol', how='left')
  #print(df_prec_dev.columns)
  df_prec_dev['Curr_PE'] = round(df_prec_dev['Close']/df_prec_dev['EPS'],1)
  df_prec_dev['Dev%_PE'] = round((df_prec_dev['Curr_PE'] - df_prec_dev['MedPE'])*100/df_prec_dev['MedPE'],2)
  df_prec_dev['Conviction'] = df_prec_dev['Conviction'] + '-' + df_prec_dev['CapType']
  return df_prec_dev

# function to arrange stock features
def arrange_features(df_stocks, common_cols, diff_cols):
  df_stocks_common = df_stocks[common_cols].drop_duplicates()
  df_stocks_diff = df_stocks[diff_cols]
  df_stocks_diff['Investment'] = df_stocks_diff['AvgCost'] * df_stocks_diff['Shares']
  df_stocks_diff = df_stocks_diff.groupby(['Symbol'])[['Shares', 'Investment']].aggregate(['sum']).reset_index()
  df_stocks_diff.columns = ['Symbol', 'Shares', 'Investment']
  df_stocks_diff['AvgCost'] = round(df_stocks_diff['Investment']/df_stocks_diff['Shares'],2)
  df_stocks = pd.merge(df_stocks_diff, df_stocks_common, on='Symbol')
  return df_stocks

# plot fact distribution across dimension
def plot_pie_chart(df, dimension, fact):
  # grouping the data by category and calculating the sum of fact for each type
  grouped_data = df.groupby(dimension)[fact].sum()

  # sorting the grouped data in descending order
  grouped_data = grouped_data.sort_values(ascending=False)

  # creating a pie chart
  grouped_data.plot.pie(autopct='%1.1f%%', startangle=90, figsize=(6, 6))

  # adding a title and displaying the plot
  plt.title(f'{dimension} {fact} Distribution')
  plt.ylabel('')  # To hide the y-label
  plt.show()

In [7]:
# function to get portfolio features

def get_portfolio_features(df_common_features):

  print_date_time()
  print('-------------------')

  #df_common_features["Target"] = df_common_features["Target"].fillna(df_common_features["Max"])
  df_common_features['NTT'] = np.where(df_common_features['Strategy']== 'NTT', df_common_features["Target"], df_common_features['Max'])
  df_common_features['LTT'] = np.where(df_common_features['Strategy']== 'BTT', df_common_features["Target"], df_common_features['Max'])
  df_common_features['BOL'] = df_common_features['Min']

  tmp_df = df_common_features[df_common_features['Symbol'].isin(mypf_df[mypf_df['InPortfolio'] != 'NA'].Symbol.values)]
  print('qualified stocks: '+str(len(tmp_df['Symbol'].unique())))
  tmp_df1 = tmp_df[tmp_df['LatestQtr'] == 1]
  print('with latest results: '+str(len(tmp_df1['Symbol'].unique())))
  tmp_df1 = tmp_df1[tmp_df1['StarStock'] == 1]
  print('still star stocks: '+str(len(tmp_df1['Symbol'].unique())))
  tmp_df['Investment'] = tmp_df['AvgCost'] * tmp_df['Shares']
  tmp_df['Current'] = round(tmp_df['Close'] * tmp_df['Shares'],0)
  tmp_df['Previous'] = tmp_df['Prev_Close'] * tmp_df['Shares']
  tmp_df['EstimatedST'] = tmp_df['NTT'] * tmp_df['Shares']
  tmp_df['EstimatedLT'] = tmp_df['LTT'] * tmp_df['Shares']
  tmp_df['Current P/L'] = round((tmp_df['Current'] - tmp_df['Investment']),0)
  tmp_df['Today P/L%'] = round((tmp_df['Current'] - tmp_df['Previous'])*100/tmp_df['Previous'],2)
  tmp_df['Current P/L%'] = round((tmp_df['Current'] - tmp_df['Investment'])*100/tmp_df['Investment'],2)
  tmp_df['EstimatedST P/L%'] = round((tmp_df['EstimatedST'] - tmp_df['Investment'])*100/tmp_df['Investment'],2)
  tmp_df['EstimatedLT P/L%'] = round((tmp_df['EstimatedLT'] - tmp_df['Investment'])*100/tmp_df['Investment'],2)
  tmp_df['NTT%'] = round((tmp_df['NTT'] - tmp_df['Close'])*100/tmp_df['Close'],2)
  tmp_df['LTT%'] = round((tmp_df['LTT'] - tmp_df['Close'])*100/tmp_df['Close'],2)
  tmp_df['Gained%'] = round((tmp_df['Close'] - tmp_df['BOL'])*100/tmp_df['BOL'],2)
  investment = round(sum(tmp_df['AvgCost']*tmp_df['Shares']),0)
  current = round(sum(tmp_df['Close']*tmp_df['Shares']),0)
  tmp_df['InitAlloc%'] = round(tmp_df['Investment']*100/investment,2)
  tmp_df['CurrAlloc%'] = round(tmp_df['Current']*100/current,2)
  tmp_df['FTT'] = tmp_df['LTT']
  tmp_df.loc[tmp_df['Strategy'] == 'NTT', 'FTT'] = tmp_df['NTT']
  tmp_df['FTT%'] = tmp_df['LTT%']
  tmp_df.loc[tmp_df['Strategy'] == 'NTT', 'FTT%'] = tmp_df['NTT%']
  tmp_df['FTT Amt'] = round(tmp_df['FTT%'] * tmp_df['Current']/100,0)
  tmp_df['OTT%'] = round((tmp_df['FTT'] - tmp_df['AvgCost'])*100/tmp_df['AvgCost'],2)
  tmp_df['RRR Ind'] = round(tmp_df['Current P/L']/tmp_df['FTT Amt'],2)
  tmp_df['Risk Ind'] = round(tmp_df['Current P/L%']*tmp_df['CurrAlloc%'],0)

  return tmp_df

# function to print portfolio features
def print_portfolio_stats(df_portfolio_features, myinvmt_df):
  from pyxirr import xirr

  total_booked_amt, reserve_amt, cy_booked_amt, py_booked_amt = get_amt()

  dates = myinvmt_df['Date'].values
  dates = np.append(dates, datetime.date.today().strftime('%d-%b-%y'))
  investment = myinvmt_df['Investment'].values
  dates= pd.to_datetime(dates)

  current = round(sum(df_portfolio_features['Close']*df_portfolio_features['Shares']),0) + reserve_amt
  investment_xirr = np.append(investment, current)
  cagr = round(xirr(pd.DataFrame({"dates": dates, "amounts": investment_xirr}))*100,2)

  investment = -sum(investment)
  invested = round(sum(df_portfolio_features['AvgCost']*df_portfolio_features['Shares']),0) + reserve_amt
  previous = round(sum(df_portfolio_features['Prev_Close']*df_portfolio_features['Shares']),0) + reserve_amt
  cy_invested = investment + py_booked_amt

  today_pnl_amount = current-previous
  today_pnl_percentage = round((current-previous)*100/previous,2)

  curr_pnl_amount = current-invested
  curr_pnl_percentage = round((curr_pnl_amount)*100/(cy_invested),2)

  cy_pnl_amount = cy_booked_amt + curr_pnl_amount
  cy_pnl_percentage = round((cy_pnl_amount)*100/cy_invested,2)

  overall_pnl_amount = total_booked_amt + curr_pnl_amount
  overall_pnl_percentage = round((overall_pnl_amount)*100/investment,2)

  estimate_st = round(sum(df_portfolio_features['FTT']*df_portfolio_features['Shares']),0)  + reserve_amt
  est_st_pnl_amount = estimate_st-current
  est_st_pnl_percentage = round((est_st_pnl_amount)*100/current,2)

  estimate_lt = round(sum(df_portfolio_features['LTT']*df_portfolio_features['Shares']),0)  + reserve_amt
  est_lt_pnl_amount = estimate_lt-current
  est_lt_pnl_percentage = round((est_lt_pnl_amount)*100/current,2)

  total_profit = round(sum(df_portfolio_features[df_portfolio_features['Current P/L%'] > 0]['Current']) - sum(df_portfolio_features[df_portfolio_features['Current P/L%'] > 0]['Investment']),0)
  total_loss = round(sum(df_portfolio_features[df_portfolio_features['Current P/L%'] < 0]['Current']) - sum(df_portfolio_features[df_portfolio_features['Current P/L%'] < 0]['Investment']),0)

  cy_booked_percentage = round((cy_booked_amt)*100/current,2)
  py_booked_percentage = round((py_booked_amt)*100/investment,2)
  total_booked_percentage = round((total_booked_amt)*100/investment,2)

  print('-------------------')
  print('Initial Investment: ', format_amt(investment))
  print('CY Investment: ', format_amt(cy_invested))
  print('Reserve: ', format_amt(reserve_amt))
  print('Current: ',  format_amt(current))
  print('-------------------')
  print('Today PnL: '+ '{} ({}%)'.format(format_amt(today_pnl_amount), today_pnl_percentage))
  print('Current PnL: '+ '{} ({}%)'.format(format_amt(curr_pnl_amount), curr_pnl_percentage))
  print('CY Booked + Current PnL: '+ '{} ({}%)'.format(format_amt(cy_pnl_amount), cy_pnl_percentage))
  print('-------------------')
  print('Total profit: ', format_amt(total_profit))
  print('Total loss: ', format_amt(total_loss))
  print('-------------------')
  print('Total Booked + Current PnL: '+ '{} ({}%)'.format(format_amt(overall_pnl_amount), overall_pnl_percentage))
  print('Total Booked PnL: '+ '{} ({}%)'.format(format_amt(total_booked_amt), total_booked_percentage))
  print('Curr Year Booked PnL: '+ '{} ({}%)'.format(format_amt(cy_booked_amt), cy_booked_percentage))
  print('Prev Year Booked PnL: '+ '{} ({}%)'.format(format_amt(py_booked_amt), py_booked_percentage))
  print('===================')
  print('Est FTT: ',  format_amt(estimate_st))
  print('Est FTT PnL: '+ '{} ({}%)'.format(format_amt(est_st_pnl_amount), est_st_pnl_percentage))

  print('===================')
  print('Deployed: ', format_amt(investment))

  print('Current: ', format_amt(current))

  print('CAGR/XIRR %: '+'{}%'.format(cagr))

In [8]:
# get start and end date
start_date, end_date = get_start_end_date()

# get portfolio and prospects data
mypfs_df = get_mypfs_df()
mypps_df = get_mypps_df()
myinvmt_df = get_myinvmt_df()

# merge above datasets
mypf_df = pd.merge(mypfs_df, mypps_df, on="Symbol")

# seggregate dm and sv portfolio
dm_pf = mypf_df[mypf_df['InPortfolio'] == 'DM']
sv_pf = mypf_df[mypf_df['InPortfolio'] == 'SV']

# build portfolio stock dataframe
dm_stocks = get_stock_ids(dm_pf)
sv_stocks = get_stock_ids(sv_pf)
df_stocks = pd.concat([dm_pf,sv_pf], ignore_index = True)

# arrange common and diff stock features
common_cols = ['Symbol', 'Target', 'Criteria', 'Strategy', 'CumlRnk', 'LatestQtr', 'StarStock', 'Conviction', 'Category', 'InFolio', 'XIRR', 'MBQ']
diff_cols = ['Symbol', 'AvgCost', 'Shares']
df_stocks = arrange_features(df_stocks, common_cols, diff_cols)

# get common features
stock_ids = df_stocks['Symbol'].values
df_common_features = get_common_features(stock_ids, df_stocks)

df_common_features.reset_index(drop=True, inplace=True)
df_common_features.drop(['Date'], axis=1, inplace=True)
# get and print portfolio features
df_portfolio_features = get_portfolio_features(df_common_features)

print_portfolio_stats(df_portfolio_features, myinvmt_df)

df = df_portfolio_features
#plot_pie_chart(df, 'CapType', 'Current')
list_ox40n = list(df[df['MBQ'].str.contains('OX40N', na=False)]['Symbol'].values)

Run date time (IST): 2026-05-25 16:26:54
-------------------
qualified stocks: 92
with latest results: 31
still star stocks: 20
-------------------
Initial Investment:  1.40 C
CY Investment:  1.82 C
Reserve:  1.49 K
Current:  1.50 C
-------------------
Today PnL: 1.16 L (0.78%)
Current PnL: -33.25 L (-18.23%)
CY Booked + Current PnL: -31.17 L (-17.09%)
-------------------
Total profit:  2.22 L
Total loss:  -35.47 L
-------------------
Total Booked + Current PnL: 11.70 L (8.38%)
Total Booked PnL: 44.95 L (32.22%)
Curr Year Booked PnL: 2.08 L (1.39%)
Prev Year Booked PnL: 42.87 L (30.73%)
===================
Est FTT:  2.55 C
Est FTT PnL: 1.05 C (70.31%)
===================
Deployed:  1.40 C
Current:  1.50 C
CAGR/XIRR %: 3.47%

In [9]:
# top 5 near their targets
cols = ['Symbol', 'Today P/L%', 'Current P/L%', 'FTT%', 'OTT%', 'FTT Amt', 'Current P/L', 'Current', 'FTT', 'Dev%_PE', 'RSI_14','Conviction', 'Spread%',  'CumlRnk', 'RRR Ind', 'CurrAlloc%', 'Gained%', 'Criteria', 'Strategy', 'Category']
df_tmp = df_portfolio_features[~df_portfolio_features['Symbol'].isin(['ENRIN','BLUSPRING','DIGITIDE'])]
df_tmp = df_tmp.sort_values(by = 'FTT Amt', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
59,PIDILITIND,-0.08,4.68,13.07,18.37,19307.0,6610.0,147720.0,1670.26,-26.64,61.0,X-LC,5.41,5.0,0.34,0.99,15.99,X40,ATH,CHEMICALS
51,KOTAKBANK,2.26,4.97,15.37,21.11,22341.0,6882.0,145354.0,453.24,-9.84,60.0,X-LC,7.83,12.0,0.31,0.97,11.16,X40,ATH,BANKS
55,MASFIN,-0.83,-6.54,30.07,21.57,27537.0,-6405.0,91575.0,397.04,-19.60,36.0,H-SC,4.74,167.0,-0.23,0.61,9.15,XR,ATH,FINANCE
53,M&M,1.87,1.86,21.13,23.38,29847.0,2574.0,141255.0,3802.40,-13.74,49.0,X-LC,8.94,25.0,0.09,0.94,7.09,X40N,ATH,AUTO
17,CIPLA,1.05,14.47,17.66,34.69,30962.0,22163.0,175324.0,1663.60,-11.50,64.0,X-LC,9.91,18.0,0.72,1.17,18.58,X40N,ATH,PHARMA

In [10]:
# top 5 today
df_tmp = df_portfolio_features.sort_values(by = 'Today P/L%', ascending=False)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
80,TITAGARH,9.88,-21.66,86.04,45.74,163234.0,-52458.0,189719.0,1548.00,4.27,65.0,H-SC,10.62,175.0,-0.32,1.27,44.75,XY24,NTT,ENGINEERING
62,RAJOOENG,5.18,-43.54,147.28,39.61,85231.0,-44630.0,57870.0,143.10,-61.79,49.0,H-SC,21.86,136.0,-0.52,0.39,23.97,AR,ATH,MISC
61,RAJESHEXPO,5.00,-78.21,359.18,0.07,107377.0,-107282.0,29895.0,518.00,995.96,49.0,L-SC,32.31,268.0,-1.00,0.20,40.35,OX40N,NTT,JEWELLERY
85,VAIBHAVGBL,3.88,-29.27,127.29,60.77,164561.0,-53495.0,129280.0,521.00,49.31,57.0,H-SC,6.10,160.0,-0.33,0.86,30.71,XR,NTT,JEWELLERY
25,FINCABLES,3.66,35.38,53.57,107.91,107078.0,52240.0,199884.0,1641.55,21.77,59.0,M-SC,25.78,220.0,0.49,1.33,50.38,OX40N,ATH,CABLES

In [11]:
# bottom 5 today
df_tmp = df_portfolio_features.sort_values(by = 'Today P/L%', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
71,SIEMENS,-3.78,-1.46,27.38,25.51,50208.0,-2720.0,183375.0,4671.50,53.99,51.0,H-LC,15.16,51.0,-0.05,1.22,28.75,AR,ATH,ELECTRICAL
83,TTKPRESTIG,-2.91,-31.99,47.17,0.09,32330.0,-32238.0,68539.0,770.00,59.02,52.0,M-SC,15.51,250.0,-1.00,0.46,22.04,OX40N,NTT,DURABLES
37,HONAUT,-2.82,-10.79,69.62,51.31,119764.0,-20813.0,172025.0,58357.33,-25.84,67.0,X-SC,11.06,90.0,-0.17,1.15,30.69,X40N,ATH,ELECTRICAL
19,COLPAL,-2.78,-20.38,77.72,41.51,162979.0,-53665.0,209700.0,3726.84,-3.61,46.0,X-MC,5.55,62.0,-0.33,1.40,17.24,XY25,ATH,FMCG
57,PAGEIND,-2.31,0.54,33.40,34.11,90118.0,1436.0,269815.0,51418.64,-27.90,60.0,X-MC,6.93,55.0,0.02,1.80,27.63,X40,ATH,APPARELS

In [12]:
# top 5 to exit based on CumlRnk
df_tmp = df_portfolio_features[~df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])]
df_tmp = df_tmp[(df_tmp['Current P/L%'] > -1) & (df_tmp['Current P/L%'] < 1)].sort_values(by = 'CumlRnk', ascending=False)
df_tmp[cols].head()

Empty DataFrame
Columns: [Symbol, Today P/L%, Current P/L%, FTT%, OTT%, FTT Amt, Current P/L, Current, FTT, Dev%_PE, RSI_14, Conviction, Spread%, CumlRnk, RRR Ind, CurrAlloc%, Gained%, Criteria, Strategy, Category]
Index: []

In [13]:
# OX40N stocks to exit
df_tmp = df_portfolio_features[(df_portfolio_features['Symbol'].isin(list_ox40n))].sort_values(by = 'Current P/L%', ascending=False)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
25,FINCABLES,3.66,35.38,53.57,107.91,107078.0,52240.0,199884.0,1641.55,21.77,59.0,M-SC,25.78,220.0,0.49,1.33,50.38,OX40N,ATH,CABLES
72,SIS,-0.74,-10.51,35.51,21.26,35283.0,-11671.0,99361.0,528.00,2362.18,61.0,H-SC,15.70,168.0,-0.33,0.66,47.73,OX40N,NTT,MISC
16,CERA,0.37,-25.09,65.39,23.89,86162.0,-44136.0,131767.0,9475.00,-27.68,58.0,H-SC,7.04,153.0,-0.51,0.88,26.63,OX40N,NTT,CERAMICS
50,KANSAINER,0.19,-27.12,55.71,13.47,109484.0,-73143.0,196524.0,340.00,-37.29,62.0,H-SC,13.13,162.0,-0.67,1.31,37.27,XY24,NTT,PAINTS
43,INDIGOPNTS,-0.74,-29.25,41.37,0.02,51091.0,-51061.0,123498.0,1408.00,88.06,66.0,M-SC,18.68,222.0,-1.00,0.82,40.12,OX40N,NTT,PAINTS

In [14]:
# top 5 to book for rotation
df_tmp = df_portfolio_features[(df_portfolio_features['Current P/L%'] > 20) ].sort_values(by = 'CumlRnk', ascending=False)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
25,FINCABLES,3.66,35.38,53.57,107.91,107078.0,52240.0,199884.0,1641.55,21.77,59.0,M-SC,25.78,220.0,0.49,1.33,50.38,OX40N,ATH,CABLES

In [15]:
# top 5 to monitor for exit
df_tmp = df_portfolio_features[~df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])]
df_tmp = df_tmp[(df_tmp['Current P/L%'] > 0) ].sort_values(by = 'Dev%_PE', ascending=False)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
74,STARHEALTH,0.54,1.72,44.77,47.26,128022.0,4831.0,285954.0,761.00,60.64,62.0,H-SC,10.13,173.0,0.04,1.91,25.54,XY24,NTT,INSURANCE
25,FINCABLES,3.66,35.38,53.57,107.91,107078.0,52240.0,199884.0,1641.55,21.77,59.0,M-SC,25.78,220.0,0.49,1.33,50.38,OX40N,ATH,CABLES
68,SATIN,2.94,19.83,26.71,51.83,88431.0,54795.0,331079.0,274.00,7.75,65.0,H-SC,32.70,159.0,0.62,2.21,61.28,XY24,NTT,FINANCE
91,ZYDUSLIFE,3.27,13.14,19.87,35.63,47116.0,27548.0,237122.0,1286.17,-1.35,74.0,H-MC,3.75,120.0,0.58,1.58,24.67,AR,ATH,PHARMA
73,SONACOMS,0.15,2.87,35.21,39.09,36641.0,2905.0,104064.0,804.02,-18.44,58.0,M-MC,19.12,193.0,0.08,0.69,47.21,AR,ATH,AUTO

In [16]:
# top 5 to book for rotation from weak conviction
df_tmp = df_portfolio_features[~df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])]
df_tmp = df_tmp[~df_tmp['Criteria'].isin(['XY25','XY24','X40', 'X40N'])].sort_values(by = 'RRR Ind', ascending=False)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
91,ZYDUSLIFE,3.27,13.14,19.87,35.63,47116.0,27548.0,237122.0,1286.17,-1.35,74.0,H-MC,3.75,120.0,0.58,1.58,24.67,AR,ATH,PHARMA
25,FINCABLES,3.66,35.38,53.57,107.91,107078.0,52240.0,199884.0,1641.55,21.77,59.0,M-SC,25.78,220.0,0.49,1.33,50.38,OX40N,ATH,CABLES
73,SONACOMS,0.15,2.87,35.21,39.09,36641.0,2905.0,104064.0,804.02,-18.44,58.0,M-MC,19.12,193.0,0.08,0.69,47.21,AR,ATH,AUTO
42,INDIAMART,-0.03,-12.80,137.06,106.72,147412.0,-15783.0,107553.0,4810.62,-60.74,47.0,H-SC,10.46,140.0,-0.11,0.72,4.12,AR,ATH,MISC
90,WIPRO,1.84,-15.16,103.06,72.27,148153.0,-25694.0,143754.0,420.00,-23.62,64.0,M-LC,13.49,98.0,-0.17,0.96,10.29,XR,NTT,IT

In [17]:
# top 5 to accumulate based on lowest RSI_14
df_tmp = df_portfolio_features[df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])].sort_values(by = 'RSI_14', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
23,DMART,-0.48,-1.51,31.59,29.60,77658.0,-3768.0,245832.0,5391.45,-16.93,33.0,X-LC,4.76,14.0,-0.05,1.64,12.37,X40N,ATH,FMCG
27,GLAXO,-0.29,-7.67,50.70,39.15,93292.0,-15276.0,184008.0,3466.20,-29.42,36.0,X-MC,6.41,56.0,-0.16,1.23,1.80,X40,ATH,PHARMA
33,HCLTECH,0.15,-24.35,60.62,21.51,110944.0,-58909.0,183015.0,1872.35,-20.60,38.0,X-LC,18.68,8.0,-0.53,1.22,3.71,X40,ATH,IT
58,PGHH,0.77,-27.62,82.39,32.01,127329.0,-58976.0,154544.0,17616.87,-51.02,40.0,X-MC,17.65,57.0,-0.46,1.03,5.70,X40,ATH,FMCG
7,BAJAJHFL,0.28,-25.59,117.89,62.13,239516.0,-69877.0,203169.0,181.50,-38.88,42.0,X-MC,13.84,60.0,-0.29,1.36,13.97,X40N,ATH,FINANCE

In [18]:
# top 5 to accumulate based on Spread and CumlRnk
df_tmp = df_portfolio_features[df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])]
df_tmp = df_tmp[(df_tmp['CumlRnk'] < 100)].sort_values(by = 'Spread%', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
88,VOLTAS,1.25,0.45,44.55,45.20,85803.0,858.0,192600.0,1856.00,15.04,43.0,X-MC,3.39,79.0,0.01,1.28,5.23,XY25,NTT,AC
84,UNITDSPR,0.16,-5.67,28.03,20.77,61908.0,-13279.0,220865.0,1644.00,-16.33,47.0,X-MC,3.53,64.0,-0.21,1.47,5.36,X40N,NTT,BREWERIES
65,RELIANCE,0.92,-12.25,42.79,25.30,75457.0,-24620.0,176343.0,1952.00,-14.65,48.0,X-LC,3.86,21.0,-0.33,1.18,4.78,XY25,BTT,REFINERIES
23,DMART,-0.48,-1.51,31.59,29.60,77658.0,-3768.0,245832.0,5391.45,-16.93,33.0,X-LC,4.76,14.0,-0.05,1.64,12.37,X40N,ATH,FMCG
39,ICICIGI,1.54,-1.78,21.50,19.34,42260.0,-3553.0,196556.0,2252.93,-17.38,57.0,X-MC,4.95,66.0,-0.08,1.31,9.78,X40,ATH,INSURANCE

In [19]:
# top 5 to accumulate based on lowest Gained%
df_tmp = df_portfolio_features[df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])].sort_values(by = 'Gained%', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
27,GLAXO,-0.29,-7.67,50.70,39.15,93292.0,-15276.0,184008.0,3466.20,-29.42,36.0,X-MC,6.41,56.0,-0.16,1.23,1.80,X40,ATH,PHARMA
32,HAVELLS,0.24,-22.93,70.51,31.42,178248.0,-75193.0,252798.0,2052.62,-27.51,43.0,X-MC,12.47,63.0,-0.42,1.69,2.47,X40,ATH,ELECTRICAL
33,HCLTECH,0.15,-24.35,60.62,21.51,110944.0,-58909.0,183015.0,1872.35,-20.60,38.0,X-LC,18.68,8.0,-0.53,1.22,3.71,X40,ATH,IT
28,GODREJCP,-0.69,-8.68,43.97,31.47,59673.0,-12901.0,135713.0,1469.04,-3.99,43.0,X-LC,8.59,32.0,-0.22,0.91,4.13,X40N,ATH,FMCG
79,TCS,0.96,-32.24,84.30,24.88,264630.0,-149358.0,313915.0,4253.91,-42.64,43.0,X-LC,17.22,2.0,-0.56,2.09,4.16,X40,ATH,IT

In [20]:
# top 5 to accumulate based on lowest CurrAlloc%
df_tmp = df_portfolio_features[df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])].sort_values(by = 'CurrAlloc%', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
64,RELAXO,1.48,-61.31,293.64,52.31,164923.0,-88995.0,56165.0,1176.00,-58.76,52.0,X-SC,24.90,92.0,-0.54,0.37,25.58,X40N,NTT,FOOTWEAR
10,BATAINDIA,1.16,-55.09,201.06,35.20,116183.0,-70885.0,57785.0,2096.00,-24.19,44.0,X-SC,25.66,91.0,-0.61,0.39,14.60,X40,NTT,FOOTWEAR
60,QUESS,1.70,-15.44,105.65,73.90,95409.0,-16486.0,90307.0,424.00,-54.27,54.0,X-SC,10.41,80.0,-0.17,0.60,23.11,XY24,NTT,MISC
28,GODREJCP,-0.69,-8.68,43.97,31.47,59673.0,-12901.0,135713.0,1469.04,-3.99,43.0,X-LC,8.59,32.0,-0.22,0.91,4.13,X40N,ATH,FMCG
53,M&M,1.87,1.86,21.13,23.38,29847.0,2574.0,141255.0,3802.40,-13.74,49.0,X-LC,8.94,25.0,0.09,0.94,7.09,X40N,ATH,AUTO

In [21]:
# top 5 to accumulate based on CumlRnk
df_tmp = df_portfolio_features.sort_values(by = 'CumlRnk', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
47,ITC,0.75,-19.94,48.71,19.06,132656.0,-67827.0,272339.0,452.00,-55.92,46.0,X-LC,14.92,1.0,-0.51,1.82,5.65,X40,NTT,FMCG
79,TCS,0.96,-32.24,84.30,24.88,264630.0,-149358.0,313915.0,4253.91,-42.64,43.0,X-LC,17.22,2.0,-0.56,2.09,4.16,X40,ATH,IT
45,INFY,-0.51,-20.45,68.76,34.24,171137.0,-63998.0,248890.0,1972.00,-37.23,45.0,X-LC,19.04,3.0,-0.37,1.66,6.71,X40,NTT,IT
81,TMPV,2.72,-15.04,60.75,36.58,183667.0,-53509.0,302332.0,600.00,-82.53,65.0,X-LC,5.81,4.0,-0.29,2.02,26.01,XY24,NTT,AUTO
59,PIDILITIND,-0.08,4.68,13.07,18.37,19307.0,6610.0,147720.0,1670.26,-26.64,61.0,X-LC,5.41,5.0,0.34,0.99,15.99,X40,ATH,CHEMICALS

In [22]:
# top 5 for average up
df_tmp = df_portfolio_features[(df_portfolio_features['Dev%_200'] > 5)].sort_values(by = 'CurrAlloc%', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
44,INDUSINDBK,1.75,-31.63,94.36,32.89,49811.0,-24418.0,52788.0,1800.00,-348.60,60.0,L-MC,8.60,258.0,-0.49,0.35,29.93,XR,NTT,BANKS
72,SIS,-0.74,-10.51,35.51,21.26,35283.0,-11671.0,99361.0,528.00,2362.18,61.0,H-SC,15.70,168.0,-0.33,0.66,47.73,OX40N,NTT,MISC
73,SONACOMS,0.15,2.87,35.21,39.09,36641.0,2905.0,104064.0,804.02,-18.44,58.0,M-MC,19.12,193.0,0.08,0.69,47.21,AR,ATH,AUTO
75,SURYODAY,1.32,-8.00,33.74,23.03,55583.0,-14331.0,164740.0,216.00,79.82,56.0,H-SC,17.88,166.0,-0.26,1.10,38.71,XR,NTT,BANKS
5,ATULAUTO,1.03,-15.48,72.23,45.57,120347.0,-30515.0,166617.0,844.00,3608.11,53.0,M-SC,7.47,248.0,-0.25,1.11,28.22,XY24,NTT,AUTO

In [23]:
# top 5 RSP
df_tmp = df_portfolio_features.sort_values(by = 'RSP', ascending=False)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
68,SATIN,2.94,19.83,26.71,51.83,88431.0,54795.0,331079.0,274.00,7.75,65.0,H-SC,32.70,159.0,0.62,2.21,61.28,XY24,NTT,FINANCE
69,SFL,-0.54,-37.52,102.66,26.63,168201.0,-98375.0,163843.0,1287.00,24.03,68.0,M-SC,11.24,242.0,-0.58,1.09,36.56,XY24,NTT,MISC
43,INDIGOPNTS,-0.74,-29.25,41.37,0.02,51091.0,-51061.0,123498.0,1408.00,88.06,66.0,M-SC,18.68,222.0,-1.00,0.82,40.12,OX40N,NTT,PAINTS
91,ZYDUSLIFE,3.27,13.14,19.87,35.63,47116.0,27548.0,237122.0,1286.17,-1.35,74.0,H-MC,3.75,120.0,0.58,1.58,24.67,AR,ATH,PHARMA
72,SIS,-0.74,-10.51,35.51,21.26,35283.0,-11671.0,99361.0,528.00,2362.18,61.0,H-SC,15.70,168.0,-0.33,0.66,47.73,OX40N,NTT,MISC

In [24]:
# Top N allocation
df_tmp = df_portfolio_features.sort_values(by = 'CurrAlloc%', ascending=False)
top_n_values = [10, 25, 50]

sum_df = pd.DataFrame({
    'Top_N': top_n_values,
    'Sum_Alloc%': [df_tmp['CurrAlloc%'].head(n).sum() for n in top_n_values]
})

sum_df

   Top_N  Sum_Alloc%
0     10       19.37
1     25       42.67
2     50       72.88

In [25]:
# market-cap-wise allocation
df_tmp = df_portfolio_features[cols]
df_tmp.groupby(df_tmp['Conviction'].str[-2:])['CurrAlloc%'].sum().sort_values(ascending=False)

Conviction
SC    42.57
LC    31.62
MC    25.83
Name: CurrAlloc%, dtype: float64

In [26]:
# criteria-wise allocation
df_portfolio_features.groupby('Criteria')['CurrAlloc%'].sum().sort_values(ascending=False)

Criteria
XY24     27.55
X40      25.52
X40N     16.89
XR        8.88
OX40N     6.93
AR        6.81
XY25      6.59
SR        0.85
Name: CurrAlloc%, dtype: float64

In [27]:
# conviction-wise allocation
df_portfolio_features.groupby('Conviction')['CurrAlloc%'].sum().sort_values(ascending=False)

Conviction
X-LC    29.44
H-SC    22.30
X-MC    20.78
M-SC    10.04
X-SC     9.71
H-MC     2.75
M-MC     1.95
H-LC     1.22
M-LC     0.96
L-SC     0.52
L-MC     0.35
Name: CurrAlloc%, dtype: float64

In [28]:
# sector-wise stats
df_tmp = df_portfolio_features.groupby('Category')[['CurrAlloc%', 'Current', 'Current P/L', 'FTT Amt']].sum().sort_values(by=['Current', 'Current P/L'], ascending=False)
df_tmp['Current P/L%'] = round(df_tmp['Current P/L'] * 100 / df_tmp['Current'], 2)
df_tmp['FTT%'] = round(df_tmp['FTT Amt'] * 100 / df_tmp['Current'], 2)
cols = ['CurrAlloc%', 'Current P/L%', 'FTT%']
df_tmp[cols].sort_values(by=['CurrAlloc%'], ascending=False)

               CurrAlloc%  Current P/L%    FTT%
Category
FMCG                15.12        -16.87   58.06
FINANCE             10.77        -14.37   64.12
IT                  10.35        -45.14  117.70
MISC                 6.95        -28.55   84.40
AUTO                 6.76         -8.04   48.55
BANKS                5.65         -7.11   56.63
PAINTS               5.54        -18.59   39.19
INSURANCE            5.38         -2.72   37.68
PHARMA               5.09          2.86   28.36
ELECTRICAL           4.06        -16.23   57.25
CHEMICALS            2.14        -26.56  101.99
HEALTHCARE           2.06        -15.98   46.25
APPARELS             1.80          0.53   33.40
AC                   1.79        -18.63   50.80
TRAVEL               1.69        -76.53  164.92
FOOTWEAR             1.66        -77.88  149.20
DURABLES             1.61        -59.94   98.86
BREWERIES            1.47         -6.01   28.03
REALTY               1.40         -5.80   23.18
CERAMICS             1.34        -53.20   99.74
CABLES               1.33         26.14   53.57
ENGINEERING          1.27        -27.65   86.04
REFINERIES           1.18        -13.96   42.79
CEMENT               1.11        -61.64  182.57
JEWELLERY            1.06       -101.01  170.84
ENTERTAINMENT        0.71        -80.77  188.58
TEXTILES             0.41        -51.95   95.28
HOTELS               0.32       -134.22  216.83

In [29]:
# money to be made criteria-wise
df_portfolio_features.groupby('Criteria')['FTT Amt'].agg(['sum', 'count']).sort_values(by='sum', ascending=False)

                sum  count
Criteria
XY24      3470452.0     21
X40       1868986.0     19
XR        1348652.0     13
X40N      1192502.0     13
AR        1162212.0      9
OX40N      752290.0     10
XY25       453873.0      5
SR         292033.0      2

In [30]:
# money to be made conviction-wise
df_portfolio_features.groupby('Conviction')['FTT Amt'].agg(['sum', 'count']).sort_values(by='sum', ascending=False)

                  sum  count
Conviction
H-SC        3443638.0     24
X-LC        1879725.0     21
X-MC        1618632.0     15
M-SC        1411406.0     14
X-SC        1347734.0      9
H-MC         285472.0      2
L-SC         212496.0      2
M-LC         148153.0      1
M-MC          93725.0      2
H-LC          50208.0      1
L-MC          49811.0      1

In [31]:
# money to be made criteria and conviction-wise
df_portfolio_features.groupby(['Conviction', 'Criteria'])['FTT Amt'].agg(['sum', 'count']).sort_values(by='sum', ascending=False)

                           sum  count
Conviction Criteria
H-SC       XY24      1060229.0      6
X-LC       X40        995647.0     10
H-SC       AR         952295.0      5
M-SC       XY24       829397.0      6
H-SC       XR         812204.0      7
X-SC       XY24       792214.0      4
X-MC       X40        662014.0      7
           X40N       485056.0      4
X-LC       X40N       363251.0      6
X-SC       X40N       344195.0      3
X-LC       XY24       327476.0      2
H-SC       OX40N      326877.0      4
M-SC       OX40N      318036.0      5
H-SC       SR         292033.0      2
X-MC       XY25       248782.0      2
H-MC       XY24       238356.0      1
X-MC       XY24       222780.0      2
X-SC       X40        211325.0      2
M-SC       XR         188021.0      2
M-LC       XR         148153.0      1
X-LC       XY25       148007.0      2
L-SC       OX40N      107377.0      1
           XR         105119.0      1
M-SC       AR          75952.0      1
M-MC       XY25        57084.0      1
H-LC       AR          50208.0      1
L-MC       XR          49811.0      1
H-MC       AR          47116.0      1
X-LC       XR          45344.0      1
M-MC       AR          36641.0      1

In [32]:
# notebook execution time

end_time = time.time()
execution_time = round(end_time - start_time, 0)
print(f"Notebook execution time: {execution_time} seconds")

Notebook execution time: 25.0 seconds