<a href="https://colab.research.google.com/github/ankit-rathi/Quantvesting_v2/blob/main/myStocks_Portfolio_Analysis.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
'''
!pip install pandas==2.2.2 -qq
!pip install pyxirr -qq
!pip install ta -qq
!pip install yfinance==0.2.59 -qq
'''

'\n!pip install pandas==2.2.2 -qq\n!pip install pyxirr -qq\n!pip install ta -qq\n!pip install yfinance==0.2.59 -qq\n'

In [2]:
# import libraries

import numpy as np
import pandas as pd
import datetime
import warnings
warnings.filterwarnings('ignore')
import yfinance as yfin
import ta
import matplotlib.pyplot as plt
import requests

In [3]:
# notebook start time
import time
import datetime
import pytz

start_time = time.time()

# function to print date timestamp
def print_date_time():
  tz_NY = pytz.timezone('Asia/Kolkata')
  datetime_NY = datetime.datetime.now(tz_NY)
  print("Run date time (IST):", datetime_NY.strftime("%Y-%m-%d %H:%M:%S"))

In [4]:
# function to get booked and reserved amount
def get_amt():
  # fetch the JSON data from the URL
  url = "https://raw.githubusercontent.com/ankit-rathi/Tradevesting_v1/main/data/myPortfolioAmts.json"
  response = requests.get(url)
  pf_amts = response.json()  # parse the JSON data

  # extract values from the JSON
  py_booked_amt_dm = pf_amts["py_booked_amt_dm"]
  py_booked_amt_sv = pf_amts["py_booked_amt_sv"]
  cy_booked_amt_dm = pf_amts["cy_booked_amt_dm"]
  cy_booked_amt_sv = pf_amts["cy_booked_amt_sv"]
  reserve_amt_dm = pf_amts["reserve_amt_dm"]
  reserve_amt_sv = pf_amts["reserve_amt_sv"]

  # perform calculations
  py_booked_amt = py_booked_amt_dm + py_booked_amt_sv
  cy_booked_amt = cy_booked_amt_dm + cy_booked_amt_sv
  reserve_amt = reserve_amt_dm + reserve_amt_sv
  total_booked_amt = py_booked_amt + cy_booked_amt

  return total_booked_amt, reserve_amt, cy_booked_amt, py_booked_amt

gen_output = 0

In [5]:
# function to format the amount
def format_amt(number):
    abs_number = abs(number)

    if abs_number >= 1_00_00_000:  # Crores
        formatted_amt = f"{number / 1_00_00_000:.2f} C"
    elif abs_number >= 1_00_000:  # Lakhs
        formatted_amt = f"{number / 1_00_000:.2f} L"
    elif abs_number >= 1_000:  # Thousands
        formatted_amt = f"{number / 1_000:.2f} K"
    else:
        formatted_amt = f"{number:.2f}"

    return formatted_amt

# function to set start and end date
def get_start_end_date():
  start_date = (datetime.date.today() + datetime.timedelta(days=-365)).strftime('%Y-%m-%d')
  end_date = (datetime.date.today() + datetime.timedelta(days=1)).strftime('%Y-%m-%d')
  return start_date, end_date

# function to fetch my portfolio csv
def get_mypfs_df():
  mypfs_df = pd.read_csv('https://raw.githubusercontent.com/ankit-rathi/Tradevesting_v1/main/data/myPortfolioStocks.csv')
  return mypfs_df

# function to fetch my prospects csv
def get_mypps_df():
  mypps_df = pd.read_csv('https://raw.githubusercontent.com/ankit-rathi/Tradevesting_v1/main/data/myProspectsScrips.csv')
  return mypps_df

# function to fetch screener data
def get_myscreen_df():
  myscreen_df = pd.read_csv('https://raw.githubusercontent.com/ankit-rathi/Tradevesting_v1/main/data/myScreenerDB.csv')
  return myscreen_df

# function to fetch momentum data
def get_myinvmt_df():
  myinvmt_df = pd.read_csv('https://raw.githubusercontent.com/ankit-rathi/Tradevesting_v1/main/data/myInvestments.csv')
  return myinvmt_df

# function to get the stock ids
def get_stock_ids(df_pf):
  stock_n100 = df_pf['Symbol'].unique()

  exclude = ['CADILAHC','MMTC', 'MASFIN']

  stock_ids = df_pf[~df_pf['Symbol'].isin(exclude) ]['Symbol'].unique()

  #mypf = mypf[mypf.Forecast.notnull()]
  #stock_ids = mypf['Symbol'].unique()

  #stock_ids.sort()
  return stock_ids

# get features from screener data
def get_screener_features():
  myscreen_df = get_myscreen_df()
  cols = ['Symbol', 'EPS', 'MedPE', 'ROCE%', 'ROE%', 'CapType']
  return myscreen_df[cols]

# get relative strength
def get_relative_strength(stock_list):

    # Dictionary to store stock tickers and their corresponding percentage price change
    stock_changes = {}

    # Loop through each stock and fetch its price data
    for stock in stock_list:
        try:
            # Download the stock data for the given date range
            stock_data = yfin.Ticker(stock + '.NS').history(period='1mo', interval='1d')[map(str.title, ['open', 'close', 'low', 'high', 'volume'])]

            # Calculate the percentage change for the stock
            if len(stock_data) > 0:
                start_price = stock_data['Close'].iloc[0]
                end_price = stock_data['Close'].iloc[-1]
                percent_change = round(((end_price - start_price) / start_price) * 100, 2)
                stock_changes[stock] = percent_change
            else:
                stock_changes[stock] = np.nan  # If no data is available, set to NaN

        except Exception as e:
            print(f"Error fetching data for {stock}: {e}")
            stock_changes[stock] = np.nan

    # Create a DataFrame with stock tickers and their percentage changes
    df = pd.DataFrame(list(stock_changes.items()), columns=['Symbol', 'Percent_Change'])

    # Drop any stocks with missing data (NaN values)
    df = df.dropna()

    # Calculate the percentile rank based on percentage change
    df['RSP'] = round(df['Percent_Change'].rank(pct=True) * 100, 2)
    cols = ['Symbol', 'RSP']
    df = df[cols]
    # Sort by percentile rank (optional)
    df = df.sort_values(by='RSP', ascending=False).reset_index(drop=True)

    return df

In [6]:
# function to get stock technicals
def stock_prec_dev(stock_symbol):
    #stock_symbol = 'ULTRACEMCO.NS'
    short_window = 20
    mid_window = 50
    long_window = 200
    moving_avg = 'SMA'

    start = datetime.datetime(*map(int, start_date.split('-')))
    end = datetime.datetime(*map(int, end_date.split('-')))

    stock_df = yfin.Ticker(stock_symbol + '.NS').history(period='max', interval='1d')[map(str.title, ['open', 'close', 'low', 'high', 'volume'])]

    stock_df['Max'] = round(max(stock_df['Close']),2)
    stock_df = stock_df[(stock_df.index <= end_date) & (stock_df.index >= start_date)]
    stock_df['200_SMA'] = round(stock_df['Close'].rolling(window = 200, min_periods = 1).mean(),0)
    stock_df['Dev%_200'] = round((stock_df['Close'] - stock_df['200_SMA'])*100/stock_df['200_SMA'],2)
    stock_df.dropna(axis = 0, inplace = True) # remove any null rows

    stock_df['20_SMA'] = stock_df['Close'].rolling(window=20).mean()
    stock_df['50_SMA'] = stock_df['Close'].rolling(window=50).mean()
    stock_df['Symbol'] = stock_symbol

    stock_df['Close'] = round(stock_df['Close'],2)
    stock_df['Min'] = round(min(stock_df['Close']),2)
    stock_df['RSI_14'] = ta.momentum.RSIIndicator(close=stock_df['Close'], window=14).rsi()
    stock_df['RSI_14'] = round(stock_df['RSI_14'],0)
    stock_df['Prev_Close'] = stock_df['Close'].shift(1)
    stock_df.drop(['Open', 'Low', 'High', 'Volume'], axis=1, inplace=True)
    stock_df = stock_df.tail(1)

    max_SMA = max(stock_df['20_SMA'].item(), stock_df['50_SMA'].item(), stock_df['200_SMA'].item())
    min_SMA = min(stock_df['20_SMA'].item(), stock_df['50_SMA'].item(), stock_df['200_SMA'].item())
    ABS_Spread = max_SMA - min_SMA
    stock_df['Spread%'] = round((ABS_Spread / stock_df['200_SMA'].item()) * 100,2)

    return stock_df

# function to compute stock attributes
def get_common_features(stock_ids, df_mypf):

  df_prec_dev = pd.DataFrame()
  df_tmp = get_screener_features()
  df_rs = get_relative_strength(stock_ids)

  for stock_id in stock_ids:
      tmp = stock_prec_dev(stock_id)
      tmp = tmp.reset_index()
      df_prec_dev = pd.concat([df_prec_dev, tmp], ignore_index = True)
  df_prec_dev = pd.merge(df_prec_dev, df_mypf, on= 'Symbol')
  df_prec_dev = pd.merge(df_prec_dev, df_tmp, on= 'Symbol', how='left')
  df_prec_dev = pd.merge(df_prec_dev, df_rs, on= 'Symbol', how='left')
  #print(df_prec_dev.columns)
  df_prec_dev['Curr_PE'] = round(df_prec_dev['Close']/df_prec_dev['EPS'],1)
  df_prec_dev['Dev%_PE'] = round((df_prec_dev['Curr_PE'] - df_prec_dev['MedPE'])*100/df_prec_dev['MedPE'],2)
  df_prec_dev['Conviction'] = df_prec_dev['Conviction'] + '-' + df_prec_dev['CapType']
  return df_prec_dev

# function to arrange stock features
def arrange_features(df_stocks, common_cols, diff_cols):
  df_stocks_common = df_stocks[common_cols].drop_duplicates()
  df_stocks_diff = df_stocks[diff_cols]
  df_stocks_diff['Investment'] = df_stocks_diff['AvgCost'] * df_stocks_diff['Shares']
  df_stocks_diff = df_stocks_diff.groupby(['Symbol'])[['Shares', 'Investment']].aggregate(['sum']).reset_index()
  df_stocks_diff.columns = ['Symbol', 'Shares', 'Investment']
  df_stocks_diff['AvgCost'] = round(df_stocks_diff['Investment']/df_stocks_diff['Shares'],2)
  df_stocks = pd.merge(df_stocks_diff, df_stocks_common, on='Symbol')
  return df_stocks

# plot fact distribution across dimension
def plot_pie_chart(df, dimension, fact):
  # grouping the data by category and calculating the sum of fact for each type
  grouped_data = df.groupby(dimension)[fact].sum()

  # sorting the grouped data in descending order
  grouped_data = grouped_data.sort_values(ascending=False)

  # creating a pie chart
  grouped_data.plot.pie(autopct='%1.1f%%', startangle=90, figsize=(6, 6))

  # adding a title and displaying the plot
  plt.title(f'{dimension} {fact} Distribution')
  plt.ylabel('')  # To hide the y-label
  plt.show()

In [7]:
# function to get portfolio features

def get_portfolio_features(df_common_features):

  print_date_time()
  print('-------------------')

  #df_common_features["Target"] = df_common_features["Target"].fillna(df_common_features["Max"])
  df_common_features['NTT'] = np.where(df_common_features['Strategy']== 'NTT', df_common_features["Target"], df_common_features['Max'])
  df_common_features['LTT'] = np.where(df_common_features['Strategy']== 'BTT', df_common_features["Target"], df_common_features['Max'])
  df_common_features['BOL'] = df_common_features['Min']

  tmp_df = df_common_features[df_common_features['Symbol'].isin(mypf_df[mypf_df['InPortfolio'] != 'NA'].Symbol.values)]
  print('qualified stocks: '+str(len(tmp_df['Symbol'].unique())))
  tmp_df1 = tmp_df[tmp_df['LatestQtr'] == 1]
  print('with latest results: '+str(len(tmp_df1['Symbol'].unique())))
  tmp_df1 = tmp_df1[tmp_df1['StarStock'] == 1]
  print('still star stocks: '+str(len(tmp_df1['Symbol'].unique())))
  tmp_df['Investment'] = tmp_df['AvgCost'] * tmp_df['Shares']
  tmp_df['Current'] = round(tmp_df['Close'] * tmp_df['Shares'],0)
  tmp_df['Previous'] = tmp_df['Prev_Close'] * tmp_df['Shares']
  tmp_df['EstimatedST'] = tmp_df['NTT'] * tmp_df['Shares']
  tmp_df['EstimatedLT'] = tmp_df['LTT'] * tmp_df['Shares']
  tmp_df['Current P/L'] = round((tmp_df['Current'] - tmp_df['Investment']),0)
  tmp_df['Today P/L%'] = round((tmp_df['Current'] - tmp_df['Previous'])*100/tmp_df['Previous'],2)
  tmp_df['Current P/L%'] = round((tmp_df['Current'] - tmp_df['Investment'])*100/tmp_df['Investment'],2)
  tmp_df['EstimatedST P/L%'] = round((tmp_df['EstimatedST'] - tmp_df['Investment'])*100/tmp_df['Investment'],2)
  tmp_df['EstimatedLT P/L%'] = round((tmp_df['EstimatedLT'] - tmp_df['Investment'])*100/tmp_df['Investment'],2)
  tmp_df['NTT%'] = round((tmp_df['NTT'] - tmp_df['Close'])*100/tmp_df['Close'],2)
  tmp_df['LTT%'] = round((tmp_df['LTT'] - tmp_df['Close'])*100/tmp_df['Close'],2)
  tmp_df['Gained%'] = round((tmp_df['Close'] - tmp_df['BOL'])*100/tmp_df['BOL'],2)
  investment = round(sum(tmp_df['AvgCost']*tmp_df['Shares']),0)
  current = round(sum(tmp_df['Close']*tmp_df['Shares']),0)
  tmp_df['InitAlloc%'] = round(tmp_df['Investment']*100/investment,2)
  tmp_df['CurrAlloc%'] = round(tmp_df['Current']*100/current,2)
  tmp_df['FTT'] = tmp_df['LTT']
  tmp_df.loc[tmp_df['Strategy'] == 'NTT', 'FTT'] = tmp_df['NTT']
  tmp_df['FTT%'] = tmp_df['LTT%']
  tmp_df.loc[tmp_df['Strategy'] == 'NTT', 'FTT%'] = tmp_df['NTT%']
  tmp_df['FTT Amt'] = round(tmp_df['FTT%'] * tmp_df['Current']/100,0)
  tmp_df['OTT%'] = round((tmp_df['FTT'] - tmp_df['AvgCost'])*100/tmp_df['AvgCost'],2)
  tmp_df['RRR Ind'] = round(tmp_df['Current P/L']/tmp_df['FTT Amt'],2)
  tmp_df['Risk Ind'] = round(tmp_df['Current P/L%']*tmp_df['CurrAlloc%'],0)

  return tmp_df

# function to print portfolio features
def print_portfolio_stats(df_portfolio_features, myinvmt_df):
  from pyxirr import xirr

  total_booked_amt, reserve_amt, cy_booked_amt, py_booked_amt = get_amt()

  dates = myinvmt_df['Date'].values
  dates = np.append(dates, datetime.date.today().strftime('%d-%b-%y'))
  investment = myinvmt_df['Investment'].values
  dates= pd.to_datetime(dates)

  current = round(sum(df_portfolio_features['Close']*df_portfolio_features['Shares']),0) + reserve_amt
  investment_xirr = np.append(investment, current)
  cagr = round(xirr(pd.DataFrame({"dates": dates, "amounts": investment_xirr}))*100,2)

  investment = -sum(investment)
  invested = round(sum(df_portfolio_features['AvgCost']*df_portfolio_features['Shares']),0) + reserve_amt
  previous = round(sum(df_portfolio_features['Prev_Close']*df_portfolio_features['Shares']),0) + reserve_amt
  cy_invested = investment + py_booked_amt

  today_pnl_amount = current-previous
  today_pnl_percentage = round((current-previous)*100/previous,2)

  curr_pnl_amount = current-invested
  curr_pnl_percentage = round((curr_pnl_amount)*100/(cy_invested),2)

  cy_pnl_amount = cy_booked_amt + curr_pnl_amount
  cy_pnl_percentage = round((cy_pnl_amount)*100/cy_invested,2)

  overall_pnl_amount = total_booked_amt + curr_pnl_amount
  overall_pnl_percentage = round((overall_pnl_amount)*100/investment,2)

  estimate_st = round(sum(df_portfolio_features['FTT']*df_portfolio_features['Shares']),0)  + reserve_amt
  est_st_pnl_amount = estimate_st-current
  est_st_pnl_percentage = round((est_st_pnl_amount)*100/current,2)

  estimate_lt = round(sum(df_portfolio_features['LTT']*df_portfolio_features['Shares']),0)  + reserve_amt
  est_lt_pnl_amount = estimate_lt-current
  est_lt_pnl_percentage = round((est_lt_pnl_amount)*100/current,2)

  total_profit = round(sum(df_portfolio_features[df_portfolio_features['Current P/L%'] > 0]['Current']) - sum(df_portfolio_features[df_portfolio_features['Current P/L%'] > 0]['Investment']),0)
  total_loss = round(sum(df_portfolio_features[df_portfolio_features['Current P/L%'] < 0]['Current']) - sum(df_portfolio_features[df_portfolio_features['Current P/L%'] < 0]['Investment']),0)

  cy_booked_percentage = round((cy_booked_amt)*100/current,2)
  py_booked_percentage = round((py_booked_amt)*100/investment,2)
  total_booked_percentage = round((total_booked_amt)*100/investment,2)

  print('-------------------')
  print('Initial Investment: ', format_amt(investment))
  print('CY Investment: ', format_amt(cy_invested))
  print('Reserve: ', format_amt(reserve_amt))
  print('Current: ',  format_amt(current))
  print('-------------------')
  print('Today PnL: '+ '{} ({}%)'.format(format_amt(today_pnl_amount), today_pnl_percentage))
  print('Current PnL: '+ '{} ({}%)'.format(format_amt(curr_pnl_amount), curr_pnl_percentage))
  print('CY Booked + Current PnL: '+ '{} ({}%)'.format(format_amt(cy_pnl_amount), cy_pnl_percentage))
  print('-------------------')
  print('Total profit: ', format_amt(total_profit))
  print('Total loss: ', format_amt(total_loss))
  print('-------------------')
  print('Total Booked + Current PnL: '+ '{} ({}%)'.format(format_amt(overall_pnl_amount), overall_pnl_percentage))
  print('Total Booked PnL: '+ '{} ({}%)'.format(format_amt(total_booked_amt), total_booked_percentage))
  print('Curr Year Booked PnL: '+ '{} ({}%)'.format(format_amt(cy_booked_amt), cy_booked_percentage))
  print('Prev Year Booked PnL: '+ '{} ({}%)'.format(format_amt(py_booked_amt), py_booked_percentage))
  print('===================')
  print('Est FTT: ',  format_amt(estimate_st))
  print('Est FTT PnL: '+ '{} ({}%)'.format(format_amt(est_st_pnl_amount), est_st_pnl_percentage))

  print('===================')
  print('Deployed: ', format_amt(investment))

  print('Current: ', format_amt(current))

  print('CAGR/XIRR %: '+'{}%'.format(cagr))

In [8]:
# get start and end date
start_date, end_date = get_start_end_date()

# get portfolio and prospects data
mypfs_df = get_mypfs_df()
mypps_df = get_mypps_df()
myinvmt_df = get_myinvmt_df()

# merge above datasets
mypf_df = pd.merge(mypfs_df, mypps_df, on="Symbol")

# seggregate dm and sv portfolio
dm_pf = mypf_df[mypf_df['InPortfolio'] == 'DM']
sv_pf = mypf_df[mypf_df['InPortfolio'] == 'SV']

# build portfolio stock dataframe
dm_stocks = get_stock_ids(dm_pf)
sv_stocks = get_stock_ids(sv_pf)
df_stocks = pd.concat([dm_pf,sv_pf], ignore_index = True)

# arrange common and diff stock features
common_cols = ['Symbol', 'Target', 'Criteria', 'Strategy', 'CumlRnk', 'LatestQtr', 'StarStock', 'Conviction', 'Category', 'InFolio', 'XIRR', 'MBQ']
diff_cols = ['Symbol', 'AvgCost', 'Shares']
df_stocks = arrange_features(df_stocks, common_cols, diff_cols)

# get common features
stock_ids = df_stocks['Symbol'].values
df_common_features = get_common_features(stock_ids, df_stocks)

df_common_features.reset_index(drop=True, inplace=True)
df_common_features.drop(['Date'], axis=1, inplace=True)
# get and print portfolio features
df_portfolio_features = get_portfolio_features(df_common_features)

print_portfolio_stats(df_portfolio_features, myinvmt_df)

df = df_portfolio_features
#plot_pie_chart(df, 'CapType', 'Current')
list_ox40n = list(df[df['MBQ'].str.contains('OX40N', na=False)]['Symbol'].values)

Run date time (IST): 2026-03-06 14:07:47
-------------------
qualified stocks: 86
with latest results: 26
still star stocks: 15
-------------------
Initial Investment:  1.33 C
CY Investment:  1.60 C
Reserve:  2.44 L
Current:  1.36 C
-------------------
Today PnL: 17.15 K (0.13%)
Current PnL: -38.75 L (-24.22%)
CY Booked + Current PnL: -23.07 L (-14.42%)
-------------------
Total profit:  1.18 L
Total loss:  -39.93 L
-------------------
Total Booked + Current PnL: 3.91 L (2.94%)
Total Booked PnL: 42.66 L (32.07%)
Curr Year Booked PnL: 15.68 L (11.56%)
Prev Year Booked PnL: 26.98 L (20.29%)
===================
Est FTT:  2.41 C
Est FTT PnL: 1.05 C (77.66%)
===================
Deployed:  1.33 C
Current:  1.36 C
CAGR/XIRR %: 1.0%

In [9]:
# top 5 near their targets
cols = ['Symbol', 'Today P/L%', 'Current P/L%', 'FTT%', 'OTT%', 'FTT Amt', 'Current P/L', 'Current', 'FTT', 'Dev%_PE', 'RSI_14','Conviction', 'Spread%',  'CumlRnk', 'RRR Ind', 'CurrAlloc%', 'Gained%', 'Criteria', 'Strategy', 'Category']
df_tmp = df_portfolio_features[~df_portfolio_features['Symbol'].isin(['ENRIN','BLUSPRING','DIGITIDE'])]
df_tmp = df_tmp.sort_values(by = 'FTT Amt', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
19,COALINDIA,-1.67,8.67,8.28,17.67,13538.0,13042.0,163503.0,478.51,30.56,59.0,L-LC,11.18,185.0,0.96,1.23,26.97,XY25,ATH,MINING
50,MASFIN,-0.28,-7.47,31.38,21.57,28449.0,-7320.0,90660.0,397.04,-20.05,35.0,H-SC,6.19,167.0,-0.26,0.68,26.50,XR,ATH,FINANCE
77,TTKPRESTIG,-2.33,-38.79,63.52,0.09,39184.0,-39089.0,61688.0,770.00,43.22,19.0,M-SC,13.47,250.0,-1.00,0.46,0.00,OX40N,NTT,DURABLES
37,ICICIGI,0.34,-0.33,19.73,19.34,39351.0,-659.0,199450.0,2252.93,-16.16,46.0,X-MC,1.46,66.0,-0.02,1.50,13.75,X40,ATH,INSURANCE
51,MEDANTA,-0.15,-7.32,33.87,24.08,39851.0,-9290.0,117660.0,1486.00,-7.89,44.0,X-SC,8.17,87.0,-0.23,0.88,7.77,XY24,NTT,HEALTHCARE

In [10]:
# top 5 today
df_tmp = df_portfolio_features.sort_values(by = 'Today P/L%', ascending=False)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
78,UNITDSPR,5.08,2.34,18.01,20.77,43154.0,5469.0,239613.0,1644.00,-9.24,53.0,X-MC,1.50,64.0,0.13,1.80,9.20,X40N,NTT,BREWERIES
27,FINCABLES,4.58,21.59,70.99,107.91,127441.0,31876.0,179520.0,1641.55,9.59,71.0,M-SC,6.50,220.0,0.25,1.35,35.06,OX40N,ATH,CABLES
74,TITAGARH,4.18,-35.46,125.82,45.74,196649.0,-85883.0,156294.0,1548.00,-14.07,36.0,H-SC,13.90,175.0,-0.44,1.17,6.78,XY24,NTT,ENGINEERING
47,JSWINFRA,3.61,-7.78,26.25,16.43,53689.0,-17245.0,204529.0,342.00,-20.99,59.0,X-MC,11.07,61.0,-0.32,1.53,9.81,X40N,NTT,REALTY
56,RAJOOENG,3.60,-39.58,131.07,39.61,81172.0,-40570.0,61930.0,143.10,-59.10,46.0,H-SC,29.32,136.0,-0.50,0.46,5.88,AR,ATH,MISC

In [11]:
# bottom 5 today
df_tmp = df_portfolio_features.sort_values(by = 'Today P/L%', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
55,RAJESHEXPO,-5.00,-77.04,335.81,0.07,105773.0,-105679.0,31498.0,518.0,1054.04,19.0,L-SC,13.73,268.0,-1.00,0.24,0.00,OX40N,NTT,JEWELLERY
41,INDIGOPNTS,-2.61,-37.72,60.58,0.02,65864.0,-65836.0,108723.0,1408.0,65.74,18.0,M-SC,14.17,222.0,-1.00,0.82,0.00,OX40N,NTT,PAINTS
77,TTKPRESTIG,-2.33,-38.79,63.52,0.09,39184.0,-39089.0,61688.0,770.0,43.22,19.0,M-SC,13.47,250.0,-1.00,0.46,0.00,OX40N,NTT,DURABLES
5,ANGELONE,-2.04,-9.80,37.67,24.18,103635.0,-29888.0,275112.0,303.0,-86.88,30.0,X-SC,2.77,97.0,-0.29,2.06,15.22,X40N,NTT,FINANCE
38,ICICIPRULI,-1.97,1.79,28.43,30.73,57009.0,3518.0,200523.0,790.0,-25.50,34.0,X-MC,3.90,78.0,0.06,1.50,14.78,X40,ATH,INSURANCE

In [12]:
# top 5 to exit based on CumlRnk
df_tmp = df_portfolio_features[~df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])]
df_tmp = df_tmp[(df_tmp['Current P/L%'] > -1) & (df_tmp['Current P/L%'] < 1)].sort_values(by = 'CumlRnk', ascending=False)
df_tmp[cols].head()

Empty DataFrame
Columns: [Symbol, Today P/L%, Current P/L%, FTT%, OTT%, FTT Amt, Current P/L, Current, FTT, Dev%_PE, RSI_14, Conviction, Spread%, CumlRnk, RRR Ind, CurrAlloc%, Gained%, Criteria, Strategy, Category]
Index: []

In [13]:
# OX40N stocks to exit
df_tmp = df_portfolio_features[(df_portfolio_features['Symbol'].isin(list_ox40n))].sort_values(by = 'Current P/L%', ascending=False)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
27,FINCABLES,4.58,21.59,70.99,107.91,127441.0,31876.0,179520.0,1641.55,9.59,71.0,M-SC,6.50,220.0,0.25,1.35,35.06,OX40N,ATH,CABLES
66,SIS,1.18,-31.40,76.77,21.26,58474.0,-34864.0,76168.0,528.00,1787.56,39.0,H-SC,7.54,168.0,-0.60,0.57,5.01,OX40N,NTT,MISC
48,KANSAINER,-1.26,-36.27,78.06,13.47,134150.0,-97812.0,171855.0,340.00,-45.18,27.0,H-SC,14.95,162.0,-0.73,1.29,0.00,XY24,NTT,PAINTS
72,TATAELXSI,-1.20,-37.35,110.74,32.03,91463.0,-49242.0,82593.0,9161.00,-21.71,27.0,H-SC,14.47,158.0,-0.54,0.62,0.00,OX40N,NTT,IT
18,CERA,0.29,-37.52,98.30,23.89,108028.0,-66007.0,109896.0,9475.00,-39.62,32.0,H-SC,15.25,153.0,-0.61,0.82,0.29,OX40N,NTT,CERAMICS

In [14]:
# top 5 to book for rotation
df_tmp = df_portfolio_features[(df_portfolio_features['Current P/L%'] > 20) ].sort_values(by = 'CumlRnk', ascending=False)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
27,FINCABLES,4.58,21.59,70.99,107.91,127441.0,31876.0,179520.0,1641.55,9.59,71.0,M-SC,6.5,220.0,0.25,1.35,35.06,OX40N,ATH,CABLES

In [15]:
# top 5 to monitor for exit
df_tmp = df_portfolio_features[~df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])]
df_tmp = df_tmp[(df_tmp['Current P/L%'] > 0) ].sort_values(by = 'Dev%_PE', ascending=False)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
19,COALINDIA,-1.67,8.67,8.28,17.67,13538.0,13042.0,163503.0,478.51,30.56,59.0,L-LC,11.18,185.0,0.96,1.23,26.97,XY25,ATH,MINING
27,FINCABLES,4.58,21.59,70.99,107.91,127441.0,31876.0,179520.0,1641.55,9.59,71.0,M-SC,6.50,220.0,0.25,1.35,35.06,OX40N,ATH,CABLES
1,ABB,2.78,11.81,30.19,45.57,88309.0,30893.0,292512.0,7934.00,-28.16,62.0,H-MC,9.26,125.0,0.35,2.20,29.89,AR,NTT,ELECTRICAL

In [16]:
# top 5 to book for rotation from weak conviction
df_tmp = df_portfolio_features[~df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])]
df_tmp = df_tmp[~df_tmp['Criteria'].isin(['XY25','XY24','X40', 'X40N'])].sort_values(by = 'RRR Ind', ascending=False)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
1,ABB,2.78,11.81,30.19,45.57,88309.0,30893.0,292512.0,7934.00,-28.16,62.0,H-MC,9.26,125.0,0.35,2.20,29.89,AR,NTT,ELECTRICAL
27,FINCABLES,4.58,21.59,70.99,107.91,127441.0,31876.0,179520.0,1641.55,9.59,71.0,M-SC,6.50,220.0,0.25,1.35,35.06,OX40N,ATH,CABLES
40,INDIAMART,2.10,-8.90,126.91,106.72,142602.0,-10971.0,112365.0,4810.62,-58.98,41.0,H-SC,8.77,140.0,-0.08,0.84,12.40,AR,ATH,MISC
85,ZYDUSLIFE,0.02,-3.53,40.59,35.63,82066.0,-7392.0,202182.0,1286.17,-16.22,53.0,H-MC,5.09,120.0,-0.09,1.52,12.56,AR,ATH,PHARMA
67,SONACOMS,1.48,-10.30,55.07,39.09,49969.0,-10421.0,90738.0,804.02,-28.98,51.0,M-MC,10.65,193.0,-0.21,0.68,28.36,AR,ATH,AUTO

In [17]:
# top 5 to accumulate based on lowest RSI_14
df_tmp = df_portfolio_features[df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])].sort_values(by = 'RSI_14', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
8,AWL,-0.47,-42.31,172.47,57.19,324495.0,-137981.0,188146.0,485.00,-67.02,12.0,X-SC,21.04,81.0,-0.43,1.41,0.00,XY24,NTT,FMCG
53,PGHH,-1.29,-17.76,60.52,32.01,106273.0,-37920.0,175600.0,17616.87,-44.44,18.0,X-MC,10.18,57.0,-0.36,1.32,0.00,X40,ATH,FMCG
3,ACC,-0.88,-36.53,158.64,64.15,239578.0,-86931.0,151020.0,3906.00,-52.08,22.0,X-SC,10.64,85.0,-0.36,1.13,0.00,XY24,BTT,CEMENT
12,BATAINDIA,0.17,-51.98,181.55,35.20,112178.0,-66881.0,61789.0,2096.00,-18.99,24.0,X-SC,23.71,91.0,-0.60,0.46,1.63,X40,NTT,FOOTWEAR
58,RELAXO,0.06,-58.15,263.92,52.31,160337.0,-84408.0,60752.0,1176.00,-55.47,25.0,X-SC,16.88,92.0,-0.53,0.46,0.06,X40N,NTT,FOOTWEAR

In [18]:
# top 5 to accumulate based on Spread and CumlRnk
df_tmp = df_portfolio_features[df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])]
df_tmp = df_tmp[(df_tmp['CumlRnk'] < 100)].sort_values(by = 'Spread%', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
22,DABUR,-1.32,-5.87,52.66,43.70,122963.0,-14565.0,233503.0,735.00,-14.67,33.0,X-MC,1.07,70.0,-0.12,1.75,8.30,XY24,BTT,FMCG
37,ICICIGI,0.34,-0.33,19.73,19.34,39351.0,-659.0,199450.0,2252.93,-16.16,46.0,X-MC,1.46,66.0,-0.02,1.50,13.75,X40,ATH,INSURANCE
78,UNITDSPR,5.08,2.34,18.01,20.77,43154.0,5469.0,239613.0,1644.00,-9.24,53.0,X-MC,1.50,64.0,0.13,1.80,9.20,X40N,NTT,BREWERIES
59,RELIANCE,1.68,-9.32,38.18,25.30,69578.0,-18725.0,182238.0,1952.00,-11.57,49.0,X-LC,2.05,21.0,-0.27,1.37,21.67,XY25,BTT,REFINERIES
5,ANGELONE,-2.04,-9.80,37.67,24.18,103635.0,-29888.0,275112.0,303.00,-86.88,30.0,X-SC,2.77,97.0,-0.29,2.06,15.22,X40N,NTT,FINANCE

In [19]:
# top 5 to accumulate based on lowest Gained%
df_tmp = df_portfolio_features[df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])].sort_values(by = 'Gained%', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
3,ACC,-0.88,-36.53,158.64,64.15,239578.0,-86931.0,151020.0,3906.00,-52.08,22.0,X-SC,10.64,85.0,-0.36,1.13,0.00,XY24,BTT,CEMENT
8,AWL,-0.47,-42.31,172.47,57.19,324495.0,-137981.0,188146.0,485.00,-67.02,12.0,X-SC,21.04,81.0,-0.43,1.41,0.00,XY24,NTT,FMCG
53,PGHH,-1.29,-17.76,60.52,32.01,106273.0,-37920.0,175600.0,17616.87,-44.44,18.0,X-MC,10.18,57.0,-0.36,1.32,0.00,X40,ATH,FMCG
73,TCS,-0.54,-26.48,68.09,23.58,216567.0,-114569.0,318060.0,4311.59,-36.41,27.0,X-LC,11.95,2.0,-0.53,2.39,0.00,X40,ATH,IT
10,BAJAJHLDNG,-0.95,-5.56,36.83,29.22,66130.0,-10571.0,179554.0,14451.52,-12.59,37.0,X-LC,11.85,28.0,-0.16,1.35,0.02,X40,ATH,FINANCE

In [20]:
# top 5 to accumulate based on lowest CurrAlloc%
df_tmp = df_portfolio_features[df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])].sort_values(by = 'CurrAlloc%', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
54,QUESS,-0.68,-35.93,122.96,42.84,51209.0,-23359.0,41647.0,424.00,-58.13,36.0,X-SC,17.15,80.0,-0.46,0.31,0.96,XY24,NTT,MISC
12,BATAINDIA,0.17,-51.98,181.55,35.20,112178.0,-66881.0,61789.0,2096.00,-18.99,24.0,X-SC,23.71,91.0,-0.60,0.46,1.63,X40,NTT,FOOTWEAR
58,RELAXO,0.06,-58.15,263.92,52.31,160337.0,-84408.0,60752.0,1176.00,-55.47,25.0,X-SC,16.88,92.0,-0.53,0.46,0.06,X40N,NTT,FOOTWEAR
51,MEDANTA,-0.15,-7.32,33.87,24.08,39851.0,-9290.0,117660.0,1486.00,-7.89,44.0,X-SC,8.17,87.0,-0.23,0.88,7.77,XY24,NTT,HEALTHCARE
36,HONAUT,0.03,-26.43,94.82,43.32,113613.0,-43052.0,119820.0,58357.33,-35.45,31.0,X-SC,13.12,90.0,-0.38,0.90,0.03,X40N,ATH,ELECTRICAL

In [21]:
# top 5 to accumulate based on CumlRnk
df_tmp = df_portfolio_features.sort_values(by = 'CumlRnk', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
45,ITC,-0.30,-18.20,45.55,19.06,126744.0,-61913.0,278253.0,452.00,-55.12,37.0,X-LC,16.70,1.0,-0.49,2.09,0.75,X40,NTT,FMCG
73,TCS,-0.54,-26.48,68.09,23.58,216567.0,-114569.0,318060.0,4311.59,-36.41,27.0,X-LC,11.95,2.0,-0.53,2.39,0.00,X40,ATH,IT
43,INFY,0.29,-10.85,50.58,34.24,141090.0,-33943.0,278945.0,1972.00,-29.97,29.0,X-LC,10.58,3.0,-0.24,2.09,2.67,X40,NTT,IT
75,TMPV,-0.68,-21.61,70.09,33.33,179004.0,-70409.0,255391.0,600.00,-83.62,39.0,X-LC,3.03,4.0,-0.39,1.92,4.41,XY24,NTT,AUTO
34,HCLTECH,0.88,-11.35,39.69,23.83,85120.0,-27462.0,214462.0,1908.19,-6.95,30.0,X-LC,8.30,8.0,-0.32,1.61,2.89,X40,ATH,IT

In [22]:
# top 5 for average up
df_tmp = df_portfolio_features[(df_portfolio_features['Dev%_200'] > 5)].sort_values(by = 'CurrAlloc%', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
42,INDUSINDBK,-0.51,-31.16,93.05,32.89,49453.0,-24060.0,53147.0,1800.00,-350.00,52.0,L-MC,12.12,258.0,-0.49,0.40,46.36,XR,NTT,BANKS
67,SONACOMS,1.48,-10.30,55.07,39.09,49969.0,-10421.0,90738.0,804.02,-28.98,51.0,M-MC,10.65,193.0,-0.21,0.68,28.36,AR,ATH,AUTO
19,COALINDIA,-1.67,8.67,8.28,17.67,13538.0,13042.0,163503.0,478.51,30.56,59.0,L-LC,11.18,185.0,0.96,1.23,26.97,XY25,ATH,MINING
27,FINCABLES,4.58,21.59,70.99,107.91,127441.0,31876.0,179520.0,1641.55,9.59,71.0,M-SC,6.50,220.0,0.25,1.35,35.06,OX40N,ATH,CABLES
82,VOLTAS,-0.31,15.84,25.35,45.20,56304.0,30363.0,222105.0,1856.00,32.66,50.0,X-MC,10.09,79.0,0.54,1.67,23.71,XY25,NTT,AC

In [23]:
# top 5 RSP
df_tmp = df_portfolio_features.sort_values(by = 'RSP', ascending=False)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
27,FINCABLES,4.58,21.59,70.99,107.91,127441.0,31876.0,179520.0,1641.55,9.59,71.0,M-SC,6.50,220.0,0.25,1.35,35.06,OX40N,ATH,CABLES
11,BANDHANBNK,-0.24,-11.20,116.70,92.42,288659.0,-31208.0,247351.0,400.00,111.93,69.0,H-SC,9.74,174.0,-0.11,1.86,36.26,XY24,NTT,BANKS
26,EASEMYTRIP,-0.26,-58.28,249.21,45.70,183842.0,-103045.0,73770.0,26.40,-23.41,46.0,M-SC,18.06,204.0,-0.56,0.55,21.54,XY24,NTT,TRAVEL
83,WHIRLPOOL,-0.82,-27.77,151.84,81.92,125912.0,-31874.0,82924.0,2270.00,-57.64,52.0,M-SC,25.75,210.0,-0.25,0.62,16.48,XR,NTT,DURABLES
1,ABB,2.78,11.81,30.19,45.57,88309.0,30893.0,292512.0,7934.00,-28.16,62.0,H-MC,9.26,125.0,0.35,2.20,29.89,AR,NTT,ELECTRICAL

In [24]:
# Top N allocation
df_tmp = df_portfolio_features.sort_values(by = 'CurrAlloc%', ascending=False)
top_n_values = [10, 25, 50]

sum_df = pd.DataFrame({
    'Top_N': top_n_values,
    'Sum_Alloc%': [df_tmp['CurrAlloc%'].head(n).sum() for n in top_n_values]
})

sum_df

   Top_N  Sum_Alloc%
0     10       20.77
1     25       45.67
2     50       77.82

In [25]:
# market-cap-wise allocation
df_tmp = df_portfolio_features[cols]
df_tmp.groupby(df_tmp['Conviction'].str[-2:])['CurrAlloc%'].sum().sort_values(ascending=False)

Conviction
SC    44.59
MC    30.49
LC    24.91
Name: CurrAlloc%, dtype: float64

In [26]:
# criteria-wise allocation
df_portfolio_features.groupby('Criteria')['CurrAlloc%'].sum().sort_values(ascending=False)

Criteria
XY24     26.55
X40      23.97
X40N     14.78
AR        9.28
XY25      9.00
XR        8.45
OX40N     7.14
SR        0.82
Name: CurrAlloc%, dtype: float64

In [27]:
# conviction-wise allocation
df_portfolio_features.groupby('Conviction')['CurrAlloc%'].sum().sort_values(ascending=False)

Conviction
X-MC    22.92
H-SC    22.32
X-LC    21.42
X-SC    11.06
M-SC    10.57
H-MC     5.08
M-MC     2.09
H-LC     1.24
L-LC     1.23
M-LC     1.02
L-SC     0.64
L-MC     0.40
Name: CurrAlloc%, dtype: float64

In [28]:
# sector-wise stats
df_tmp = df_portfolio_features.groupby('Category')[['CurrAlloc%', 'Current', 'Current P/L', 'FTT Amt']].sum().sort_values(by=['Current', 'Current P/L'], ascending=False)
df_tmp['Current P/L%'] = round(df_tmp['Current P/L'] * 100 / df_tmp['Current'], 2)
df_tmp['FTT%'] = round(df_tmp['FTT Amt'] * 100 / df_tmp['Current'], 2)
cols = ['CurrAlloc%', 'Current P/L%', 'FTT%']
df_tmp[cols].sort_values(by=['CurrAlloc%'], ascending=False)

               CurrAlloc%  Current P/L%    FTT%
Category
FMCG                15.59        -18.77   58.94
FINANCE             12.77        -22.67   70.94
IT                  11.48        -43.42  115.29
MISC                 6.80        -43.17  101.73
ELECTRICAL           6.48         -8.84   48.55
PAINTS               4.96        -39.73   60.49
INSURANCE            4.88         -4.32   40.02
PHARMA               4.27         -3.40   35.95
AUTO                 3.74        -25.25   73.00
BANKS                3.25        -23.52   98.37
AC                   2.23         -7.81   37.04
FOOTWEAR             1.95        -69.73  137.78
TRAVEL               1.91        -75.06  162.71
DURABLES             1.83        -58.48   97.04
BREWERIES            1.80          2.28   18.01
HEALTHCARE           1.66        -38.81   73.06
REALTY               1.53         -8.43   26.25
APPARELS             1.43        -24.65   62.23
CERAMICS             1.40        -63.73  113.47
REFINERIES           1.37        -10.28   38.18
CABLES               1.35         17.76   70.99
MINING               1.23          7.98    8.28
ENGINEERING          1.17        -54.95  125.82
JEWELLERY            1.16       -107.57  179.69
CEMENT               1.13        -57.56  158.64
CHEMICALS            1.00        -98.87  261.12
ENTERTAINMENT        0.78        -85.11  195.51
TEXTILES             0.44        -56.28  100.84
HOTELS               0.40       -115.13  191.01

In [29]:
# money to be made criteria-wise
df_portfolio_features.groupby('Criteria')['FTT Amt'].agg(['sum', 'count']).sort_values(by='sum', ascending=False)

                sum  count
Criteria
XY24      3586507.0     21
X40       1528336.0     15
XR        1365043.0     12
AR        1335054.0     10
X40N      1150043.0     10
OX40N      841501.0     10
XY25       419254.0      6
SR         310746.0      2

In [30]:
# money to be made conviction-wise
df_portfolio_features.groupby('Conviction')['FTT Amt'].agg(['sum', 'count']).sort_values(by='sum', ascending=False)

                  sum  count
Conviction
H-SC        3819095.0     24
M-SC        1507708.0     14
X-MC        1458523.0     15
X-LC        1419149.0     12
X-SC        1328383.0     10
H-MC         402302.0      3
L-SC         206590.0      2
M-LC         155431.0      1
M-MC         107414.0      2
H-LC          68898.0      1
L-MC          49453.0      1
L-LC          13538.0      1

In [31]:
# money to be made criteria and conviction-wise
df_portfolio_features.groupby(['Conviction', 'Criteria'])['FTT Amt'].agg(['sum', 'count']).sort_values(by='sum', ascending=False)

                           sum  count
Conviction Criteria
H-SC       XY24      1287294.0      6
           AR         969094.0      5
M-SC       XY24       887881.0      6
H-SC       XR         873901.0      7
X-LC       X40        739097.0      6
X-SC       XY24       655133.0      4
X-MC       X40        591077.0      7
X-SC       X40N       475088.0      4
X-MC       X40N       439266.0      4
H-SC       OX40N      378060.0      4
M-SC       OX40N      357668.0      5
H-SC       SR         310746.0      2
X-LC       XY24       305076.0      2
           X40N       235689.0      2
H-MC       XY24       231927.0      1
X-MC       XY24       219196.0      2
           XY25       208984.0      2
X-SC       X40        198162.0      2
M-SC       XR         185441.0      2
H-MC       AR         170375.0      2
M-LC       XR         155431.0      1
X-LC       XY25       139287.0      2
L-SC       OX40N      105773.0      1
           XR         100817.0      1
M-SC       AR          76718.0      1
H-LC       AR          68898.0      1
M-MC       XY25        57445.0      1
           AR          49969.0      1
L-MC       XR          49453.0      1
L-LC       XY25        13538.0      1

In [32]:
# notebook execution time

end_time = time.time()
execution_time = round(end_time - start_time, 0)
print(f"Notebook execution time: {execution_time} seconds")

Notebook execution time: 25.0 seconds