<a href="https://colab.research.google.com/github/ankit-rathi/Quantvesting_v2/blob/main/myStocks_Portfolio_Analysis.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
'''
!pip install pandas==2.2.2 -qq
!pip install pyxirr -qq
!pip install ta -qq
!pip install yfinance==0.2.59 -qq
'''

'\n!pip install pandas==2.2.2 -qq\n!pip install pyxirr -qq\n!pip install ta -qq\n!pip install yfinance==0.2.59 -qq\n'

In [2]:
# import libraries

import numpy as np
import pandas as pd
import datetime
import warnings
warnings.filterwarnings('ignore')
import yfinance as yfin
import ta
import matplotlib.pyplot as plt
import requests

In [3]:
# notebook start time
import time
import datetime
import pytz

start_time = time.time()

# function to print date timestamp
def print_date_time():
  tz_NY = pytz.timezone('Asia/Kolkata')
  datetime_NY = datetime.datetime.now(tz_NY)
  print("Run date time (IST):", datetime_NY.strftime("%Y-%m-%d %H:%M:%S"))

In [4]:
# function to get booked and reserved amount
def get_amt():
  # fetch the JSON data from the URL
  url = "https://raw.githubusercontent.com/ankit-rathi/Tradevesting_v1/main/data/myPortfolioAmts.json"
  response = requests.get(url)
  pf_amts = response.json()  # parse the JSON data

  # extract values from the JSON
  py_booked_amt_dm = pf_amts["py_booked_amt_dm"]
  py_booked_amt_sv = pf_amts["py_booked_amt_sv"]
  cy_booked_amt_dm = pf_amts["cy_booked_amt_dm"]
  cy_booked_amt_sv = pf_amts["cy_booked_amt_sv"]
  reserve_amt_dm = pf_amts["reserve_amt_dm"]
  reserve_amt_sv = pf_amts["reserve_amt_sv"]

  # perform calculations
  py_booked_amt = py_booked_amt_dm + py_booked_amt_sv
  cy_booked_amt = cy_booked_amt_dm + cy_booked_amt_sv
  reserve_amt = reserve_amt_dm + reserve_amt_sv
  total_booked_amt = py_booked_amt + cy_booked_amt

  return total_booked_amt, reserve_amt, cy_booked_amt, py_booked_amt

gen_output = 0

In [5]:
# function to format the amount
def format_amt(number):
    abs_number = abs(number)

    if abs_number >= 1_00_00_000:  # Crores
        formatted_amt = f"{number / 1_00_00_000:.2f} C"
    elif abs_number >= 1_00_000:  # Lakhs
        formatted_amt = f"{number / 1_00_000:.2f} L"
    elif abs_number >= 1_000:  # Thousands
        formatted_amt = f"{number / 1_000:.2f} K"
    else:
        formatted_amt = f"{number:.2f}"

    return formatted_amt

# function to set start and end date
def get_start_end_date():
  start_date = (datetime.date.today() + datetime.timedelta(days=-365)).strftime('%Y-%m-%d')
  end_date = (datetime.date.today() + datetime.timedelta(days=1)).strftime('%Y-%m-%d')
  return start_date, end_date

# function to fetch my portfolio csv
def get_mypfs_df():
  mypfs_df = pd.read_csv('https://raw.githubusercontent.com/ankit-rathi/Tradevesting_v1/main/data/myPortfolioStocks.csv')
  return mypfs_df

# function to fetch my prospects csv
def get_mypps_df():
  mypps_df = pd.read_csv('https://raw.githubusercontent.com/ankit-rathi/Tradevesting_v1/main/data/myProspectsScrips.csv')
  return mypps_df

# function to fetch screener data
def get_myscreen_df():
  myscreen_df = pd.read_csv('https://raw.githubusercontent.com/ankit-rathi/Tradevesting_v1/main/data/myScreenerDB.csv')
  return myscreen_df

# function to fetch momentum data
def get_myinvmt_df():
  myinvmt_df = pd.read_csv('https://raw.githubusercontent.com/ankit-rathi/Tradevesting_v1/main/data/myInvestments.csv')
  return myinvmt_df

# function to get the stock ids
def get_stock_ids(df_pf):
  stock_n100 = df_pf['Symbol'].unique()

  exclude = ['CADILAHC','MMTC', 'MASFIN']

  stock_ids = df_pf[~df_pf['Symbol'].isin(exclude) ]['Symbol'].unique()

  #mypf = mypf[mypf.Forecast.notnull()]
  #stock_ids = mypf['Symbol'].unique()

  #stock_ids.sort()
  return stock_ids

# get features from screener data
def get_screener_features():
  myscreen_df = get_myscreen_df()
  cols = ['Symbol', 'EPS', 'MedPE', 'ROCE%', 'ROE%', 'CapType']
  return myscreen_df[cols]

# get relative strength
def get_relative_strength(stock_list):

    # Dictionary to store stock tickers and their corresponding percentage price change
    stock_changes = {}

    # Loop through each stock and fetch its price data
    for stock in stock_list:
        try:
            # Download the stock data for the given date range
            stock_data = yfin.Ticker(stock + '.NS').history(period='1mo', interval='1d')[map(str.title, ['open', 'close', 'low', 'high', 'volume'])]

            # Calculate the percentage change for the stock
            if len(stock_data) > 0:
                start_price = stock_data['Close'].iloc[0]
                end_price = stock_data['Close'].iloc[-1]
                percent_change = round(((end_price - start_price) / start_price) * 100, 2)
                stock_changes[stock] = percent_change
            else:
                stock_changes[stock] = np.nan  # If no data is available, set to NaN

        except Exception as e:
            print(f"Error fetching data for {stock}: {e}")
            stock_changes[stock] = np.nan

    # Create a DataFrame with stock tickers and their percentage changes
    df = pd.DataFrame(list(stock_changes.items()), columns=['Symbol', 'Percent_Change'])

    # Drop any stocks with missing data (NaN values)
    df = df.dropna()

    # Calculate the percentile rank based on percentage change
    df['RSP'] = round(df['Percent_Change'].rank(pct=True) * 100, 2)
    cols = ['Symbol', 'RSP']
    df = df[cols]
    # Sort by percentile rank (optional)
    df = df.sort_values(by='RSP', ascending=False).reset_index(drop=True)

    return df

In [6]:
# function to get stock technicals
def stock_prec_dev(stock_symbol):
    #stock_symbol = 'ULTRACEMCO.NS'
    short_window = 20
    mid_window = 50
    long_window = 200
    moving_avg = 'SMA'

    start = datetime.datetime(*map(int, start_date.split('-')))
    end = datetime.datetime(*map(int, end_date.split('-')))

    stock_df = yfin.Ticker(stock_symbol + '.NS').history(period='max', interval='1d')[map(str.title, ['open', 'close', 'low', 'high', 'volume'])]

    stock_df['Max'] = round(max(stock_df['Close']),2)
    stock_df = stock_df[(stock_df.index <= end_date) & (stock_df.index >= start_date)]
    stock_df['200_SMA'] = round(stock_df['Close'].rolling(window = 200, min_periods = 1).mean(),0)
    stock_df['Dev%_200'] = round((stock_df['Close'] - stock_df['200_SMA'])*100/stock_df['200_SMA'],2)
    stock_df.dropna(axis = 0, inplace = True) # remove any null rows

    stock_df['20_SMA'] = stock_df['Close'].rolling(window=20).mean()
    stock_df['50_SMA'] = stock_df['Close'].rolling(window=50).mean()
    stock_df['Symbol'] = stock_symbol

    stock_df['Close'] = round(stock_df['Close'],2)
    stock_df['Min'] = round(min(stock_df['Close']),2)
    stock_df['RSI_14'] = ta.momentum.RSIIndicator(close=stock_df['Close'], window=14).rsi()
    stock_df['RSI_14'] = round(stock_df['RSI_14'],0)
    stock_df['Prev_Close'] = stock_df['Close'].shift(1)
    stock_df.drop(['Open', 'Low', 'High', 'Volume'], axis=1, inplace=True)
    stock_df = stock_df.tail(1)

    max_SMA = max(stock_df['20_SMA'].item(), stock_df['50_SMA'].item(), stock_df['200_SMA'].item())
    min_SMA = min(stock_df['20_SMA'].item(), stock_df['50_SMA'].item(), stock_df['200_SMA'].item())
    ABS_Spread = max_SMA - min_SMA
    stock_df['Spread%'] = round((ABS_Spread / stock_df['200_SMA'].item()) * 100,2)

    return stock_df

# function to compute stock attributes
def get_common_features(stock_ids, df_mypf):

  df_prec_dev = pd.DataFrame()
  df_tmp = get_screener_features()
  df_rs = get_relative_strength(stock_ids)

  for stock_id in stock_ids:
      tmp = stock_prec_dev(stock_id)
      tmp = tmp.reset_index()
      df_prec_dev = pd.concat([df_prec_dev, tmp], ignore_index = True)
  df_prec_dev = pd.merge(df_prec_dev, df_mypf, on= 'Symbol')
  df_prec_dev = pd.merge(df_prec_dev, df_tmp, on= 'Symbol', how='left')
  df_prec_dev = pd.merge(df_prec_dev, df_rs, on= 'Symbol', how='left')
  #print(df_prec_dev.columns)
  df_prec_dev['Curr_PE'] = round(df_prec_dev['Close']/df_prec_dev['EPS'],1)
  df_prec_dev['Dev%_PE'] = round((df_prec_dev['Curr_PE'] - df_prec_dev['MedPE'])*100/df_prec_dev['MedPE'],2)
  df_prec_dev['Conviction'] = df_prec_dev['Conviction'] + '-' + df_prec_dev['CapType']
  return df_prec_dev

# function to arrange stock features
def arrange_features(df_stocks, common_cols, diff_cols):
  df_stocks_common = df_stocks[common_cols].drop_duplicates()
  df_stocks_diff = df_stocks[diff_cols]
  df_stocks_diff['Investment'] = df_stocks_diff['AvgCost'] * df_stocks_diff['Shares']
  df_stocks_diff = df_stocks_diff.groupby(['Symbol'])[['Shares', 'Investment']].aggregate(['sum']).reset_index()
  df_stocks_diff.columns = ['Symbol', 'Shares', 'Investment']
  df_stocks_diff['AvgCost'] = round(df_stocks_diff['Investment']/df_stocks_diff['Shares'],2)
  df_stocks = pd.merge(df_stocks_diff, df_stocks_common, on='Symbol')
  return df_stocks

# plot fact distribution across dimension
def plot_pie_chart(df, dimension, fact):
  # grouping the data by category and calculating the sum of fact for each type
  grouped_data = df.groupby(dimension)[fact].sum()

  # sorting the grouped data in descending order
  grouped_data = grouped_data.sort_values(ascending=False)

  # creating a pie chart
  grouped_data.plot.pie(autopct='%1.1f%%', startangle=90, figsize=(6, 6))

  # adding a title and displaying the plot
  plt.title(f'{dimension} {fact} Distribution')
  plt.ylabel('')  # To hide the y-label
  plt.show()

In [7]:
# function to get portfolio features

def get_portfolio_features(df_common_features):

  print_date_time()
  print('-------------------')

  #df_common_features["Target"] = df_common_features["Target"].fillna(df_common_features["Max"])
  df_common_features['NTT'] = np.where(df_common_features['Strategy']== 'NTT', df_common_features["Target"], df_common_features['Max'])
  df_common_features['LTT'] = np.where(df_common_features['Strategy']== 'BTT', df_common_features["Target"], df_common_features['Max'])
  df_common_features['BOL'] = df_common_features['Min']

  tmp_df = df_common_features[df_common_features['Symbol'].isin(mypf_df[mypf_df['InPortfolio'] != 'NA'].Symbol.values)]
  print('qualified stocks: '+str(len(tmp_df['Symbol'].unique())))
  tmp_df1 = tmp_df[tmp_df['LatestQtr'] == 1]
  print('with latest results: '+str(len(tmp_df1['Symbol'].unique())))
  tmp_df1 = tmp_df1[tmp_df1['StarStock'] == 1]
  print('still star stocks: '+str(len(tmp_df1['Symbol'].unique())))
  tmp_df['Investment'] = tmp_df['AvgCost'] * tmp_df['Shares']
  tmp_df['Current'] = round(tmp_df['Close'] * tmp_df['Shares'],0)
  tmp_df['Previous'] = tmp_df['Prev_Close'] * tmp_df['Shares']
  tmp_df['EstimatedST'] = tmp_df['NTT'] * tmp_df['Shares']
  tmp_df['EstimatedLT'] = tmp_df['LTT'] * tmp_df['Shares']
  tmp_df['Current P/L'] = round((tmp_df['Current'] - tmp_df['Investment']),0)
  tmp_df['Today P/L%'] = round((tmp_df['Current'] - tmp_df['Previous'])*100/tmp_df['Previous'],2)
  tmp_df['Current P/L%'] = round((tmp_df['Current'] - tmp_df['Investment'])*100/tmp_df['Investment'],2)
  tmp_df['EstimatedST P/L%'] = round((tmp_df['EstimatedST'] - tmp_df['Investment'])*100/tmp_df['Investment'],2)
  tmp_df['EstimatedLT P/L%'] = round((tmp_df['EstimatedLT'] - tmp_df['Investment'])*100/tmp_df['Investment'],2)
  tmp_df['NTT%'] = round((tmp_df['NTT'] - tmp_df['Close'])*100/tmp_df['Close'],2)
  tmp_df['LTT%'] = round((tmp_df['LTT'] - tmp_df['Close'])*100/tmp_df['Close'],2)
  tmp_df['Gained%'] = round((tmp_df['Close'] - tmp_df['BOL'])*100/tmp_df['BOL'],2)
  investment = round(sum(tmp_df['AvgCost']*tmp_df['Shares']),0)
  current = round(sum(tmp_df['Close']*tmp_df['Shares']),0)
  tmp_df['InitAlloc%'] = round(tmp_df['Investment']*100/investment,2)
  tmp_df['CurrAlloc%'] = round(tmp_df['Current']*100/current,2)
  tmp_df['FTT'] = tmp_df['LTT']
  tmp_df.loc[tmp_df['Strategy'] == 'NTT', 'FTT'] = tmp_df['NTT']
  tmp_df['FTT%'] = tmp_df['LTT%']
  tmp_df.loc[tmp_df['Strategy'] == 'NTT', 'FTT%'] = tmp_df['NTT%']
  tmp_df['FTT Amt'] = round(tmp_df['FTT%'] * tmp_df['Current']/100,0)
  tmp_df['OTT%'] = round((tmp_df['FTT'] - tmp_df['AvgCost'])*100/tmp_df['AvgCost'],2)
  tmp_df['RRR Ind'] = round(tmp_df['Current P/L']/tmp_df['FTT Amt'],2)
  tmp_df['Risk Ind'] = round(tmp_df['Current P/L%']*tmp_df['CurrAlloc%'],0)

  return tmp_df

# function to print portfolio features
def print_portfolio_stats(df_portfolio_features, myinvmt_df):
  from pyxirr import xirr

  total_booked_amt, reserve_amt, cy_booked_amt, py_booked_amt = get_amt()

  dates = myinvmt_df['Date'].values
  dates = np.append(dates, datetime.date.today().strftime('%d-%b-%y'))
  investment = myinvmt_df['Investment'].values
  dates= pd.to_datetime(dates)

  current = round(sum(df_portfolio_features['Close']*df_portfolio_features['Shares']),0) + reserve_amt
  investment_xirr = np.append(investment, current)
  cagr = round(xirr(pd.DataFrame({"dates": dates, "amounts": investment_xirr}))*100,2)

  investment = -sum(investment)
  invested = round(sum(df_portfolio_features['AvgCost']*df_portfolio_features['Shares']),0) + reserve_amt
  previous = round(sum(df_portfolio_features['Prev_Close']*df_portfolio_features['Shares']),0) + reserve_amt
  cy_invested = investment + py_booked_amt

  today_pnl_amount = current-previous
  today_pnl_percentage = round((current-previous)*100/previous,2)

  curr_pnl_amount = current-invested
  curr_pnl_percentage = round((curr_pnl_amount)*100/(cy_invested),2)

  cy_pnl_amount = cy_booked_amt + curr_pnl_amount
  cy_pnl_percentage = round((cy_pnl_amount)*100/cy_invested,2)

  overall_pnl_amount = total_booked_amt + curr_pnl_amount
  overall_pnl_percentage = round((overall_pnl_amount)*100/investment,2)

  estimate_st = round(sum(df_portfolio_features['FTT']*df_portfolio_features['Shares']),0)  + reserve_amt
  est_st_pnl_amount = estimate_st-current
  est_st_pnl_percentage = round((est_st_pnl_amount)*100/current,2)

  estimate_lt = round(sum(df_portfolio_features['LTT']*df_portfolio_features['Shares']),0)  + reserve_amt
  est_lt_pnl_amount = estimate_lt-current
  est_lt_pnl_percentage = round((est_lt_pnl_amount)*100/current,2)

  total_profit = round(sum(df_portfolio_features[df_portfolio_features['Current P/L%'] > 0]['Current']) - sum(df_portfolio_features[df_portfolio_features['Current P/L%'] > 0]['Investment']),0)
  total_loss = round(sum(df_portfolio_features[df_portfolio_features['Current P/L%'] < 0]['Current']) - sum(df_portfolio_features[df_portfolio_features['Current P/L%'] < 0]['Investment']),0)

  cy_booked_percentage = round((cy_booked_amt)*100/current,2)
  py_booked_percentage = round((py_booked_amt)*100/investment,2)
  total_booked_percentage = round((total_booked_amt)*100/investment,2)

  print('-------------------')
  print('Initial Investment: ', format_amt(investment))
  print('CY Investment: ', format_amt(cy_invested))
  print('Reserve: ', format_amt(reserve_amt))
  print('Current: ',  format_amt(current))
  print('-------------------')
  print('Today PnL: '+ '{} ({}%)'.format(format_amt(today_pnl_amount), today_pnl_percentage))
  print('Current PnL: '+ '{} ({}%)'.format(format_amt(curr_pnl_amount), curr_pnl_percentage))
  print('CY Booked + Current PnL: '+ '{} ({}%)'.format(format_amt(cy_pnl_amount), cy_pnl_percentage))
  print('-------------------')
  print('Total profit: ', format_amt(total_profit))
  print('Total loss: ', format_amt(total_loss))
  print('-------------------')
  print('Total Booked + Current PnL: '+ '{} ({}%)'.format(format_amt(overall_pnl_amount), overall_pnl_percentage))
  print('Total Booked PnL: '+ '{} ({}%)'.format(format_amt(total_booked_amt), total_booked_percentage))
  print('Curr Year Booked PnL: '+ '{} ({}%)'.format(format_amt(cy_booked_amt), cy_booked_percentage))
  print('Prev Year Booked PnL: '+ '{} ({}%)'.format(format_amt(py_booked_amt), py_booked_percentage))
  print('===================')
  print('Est FTT: ',  format_amt(estimate_st))
  print('Est FTT PnL: '+ '{} ({}%)'.format(format_amt(est_st_pnl_amount), est_st_pnl_percentage))

  print('===================')
  print('Deployed: ', format_amt(investment))

  print('Current: ', format_amt(current))

  print('CAGR/XIRR %: '+'{}%'.format(cagr))

In [8]:
# get start and end date
start_date, end_date = get_start_end_date()

# get portfolio and prospects data
mypfs_df = get_mypfs_df()
mypps_df = get_mypps_df()
myinvmt_df = get_myinvmt_df()

# merge above datasets
mypf_df = pd.merge(mypfs_df, mypps_df, on="Symbol")

# seggregate dm and sv portfolio
dm_pf = mypf_df[mypf_df['InPortfolio'] == 'DM']
sv_pf = mypf_df[mypf_df['InPortfolio'] == 'SV']

# build portfolio stock dataframe
dm_stocks = get_stock_ids(dm_pf)
sv_stocks = get_stock_ids(sv_pf)
df_stocks = pd.concat([dm_pf,sv_pf], ignore_index = True)

# arrange common and diff stock features
common_cols = ['Symbol', 'Target', 'Criteria', 'Strategy', 'CumlRnk', 'LatestQtr', 'StarStock', 'Conviction', 'Category', 'InFolio', 'XIRR', 'MBQ']
diff_cols = ['Symbol', 'AvgCost', 'Shares']
df_stocks = arrange_features(df_stocks, common_cols, diff_cols)

# get common features
stock_ids = df_stocks['Symbol'].values
df_common_features = get_common_features(stock_ids, df_stocks)

df_common_features.reset_index(drop=True, inplace=True)
df_common_features.drop(['Date'], axis=1, inplace=True)
# get and print portfolio features
df_portfolio_features = get_portfolio_features(df_common_features)

print_portfolio_stats(df_portfolio_features, myinvmt_df)

df = df_portfolio_features
#plot_pie_chart(df, 'CapType', 'Current')
list_ox40n = list(df[df['MBQ'].str.contains('OX40N', na=False)]['Symbol'].values)

Run date time (IST): 2026-05-04 13:39:34
-------------------
qualified stocks: 92
with latest results: 31
still star stocks: 20

-------------------
Initial Investment:  1.40 C
CY Investment:  1.82 C
Reserve:  1.49 K
Current:  1.48 C
-------------------
Today PnL: 64.49 K (0.44%)
Current PnL: -34.83 L (-19.1%)
CY Booked + Current PnL: -32.75 L (-17.96%)
-------------------
Total profit:  1.22 L
Total loss:  -36.05 L
-------------------
Total Booked + Current PnL: 10.12 L (7.25%)
Total Booked PnL: 44.95 L (32.22%)
Curr Year Booked PnL: 2.08 L (1.4%)
Prev Year Booked PnL: 42.87 L (30.73%)
===================
Est FTT:  2.55 C
Est FTT PnL: 1.07 C (72.2%)
===================
Deployed:  1.40 C
Current:  1.48 C
CAGR/XIRR %: 3.04%

In [9]:
# top 5 near their targets
cols = ['Symbol', 'Today P/L%', 'Current P/L%', 'FTT%', 'OTT%', 'FTT Amt', 'Current P/L', 'Current', 'FTT', 'Dev%_PE', 'RSI_14','Conviction', 'Spread%',  'CumlRnk', 'RRR Ind', 'CurrAlloc%', 'Gained%', 'Criteria', 'Strategy', 'Category']
df_tmp = df_portfolio_features[~df_portfolio_features['Symbol'].isin(['ENRIN','BLUSPRING','DIGITIDE'])]
df_tmp = df_tmp.sort_values(by = 'FTT Amt', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
55,MASFIN,2.07,6.23,14.44,21.57,15030.0,6105.0,104085.0,397.04,-8.31,72.0,H-SC,1.13,167.0,0.41,0.70,34.50,XR,ATH,FINANCE
83,TTKPRESTIG,7.21,-29.64,42.25,0.09,29959.0,-29867.0,70910.0,770.00,64.57,64.0,M-SC,17.73,250.0,-1.00,0.48,26.27,OX40N,NTT,DURABLES
51,KOTAKBANK,-3.30,-0.96,22.28,21.11,30555.0,-1332.0,137140.0,453.24,-15.04,45.0,X-LC,8.59,12.0,-0.04,0.92,4.88,X40,ATH,BANKS
59,PIDILITIND,-0.95,-3.44,22.58,18.37,30768.0,-4850.0,136260.0,1670.26,-32.34,47.0,X-LC,6.99,5.0,-0.16,0.92,6.99,X40,ATH,CHEMICALS
53,M&M,-0.21,0.29,23.02,23.38,32019.0,409.0,139090.0,3802.40,-15.13,46.0,X-LC,8.60,25.0,0.01,0.94,5.45,X40N,ATH,AUTO

In [10]:
# top 5 today
df_tmp = df_portfolio_features.sort_values(by = 'Today P/L%', ascending=False)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
72,SIS,12.98,-7.77,31.47,21.26,32228.0,-8624.0,102408.0,528.0,2437.82,81.0,H-SC,7.64,168.0,-0.27,0.69,52.27,OX40N,NTT,MISC
83,TTKPRESTIG,7.21,-29.64,42.25,0.09,29959.0,-29867.0,70910.0,770.0,64.57,64.0,M-SC,17.73,250.0,-1.00,0.48,26.27,OX40N,NTT,DURABLES
60,QUESS,6.90,-13.33,100.65,73.90,93156.0,-14239.0,92554.0,424.0,-53.17,66.0,X-SC,14.96,80.0,-0.15,0.62,24.51,XY24,NTT,MISC
56,MEDANTA,5.39,0.73,26.20,27.12,46584.0,1285.0,177802.0,1486.0,-2.35,65.0,X-SC,10.98,87.0,0.03,1.20,22.52,XY24,NTT,HEALTHCARE
68,SATIN,4.76,2.27,48.47,51.83,136950.0,6262.0,282546.0,274.0,-8.02,69.0,H-SC,10.07,159.0,0.05,1.90,37.64,XY24,NTT,FINANCE

In [11]:
# bottom 5 today
df_tmp = df_portfolio_features.sort_values(by = 'Today P/L%', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
73,SONACOMS,-5.95,-1.20,40.78,39.09,40756.0,-1217.0,99942.0,804.02,-21.69,54.0,M-MC,16.87,193.0,-0.03,0.67,41.38,AR,ATH,AUTO
23,DMART,-4.75,5.00,23.42,29.60,61382.0,12492.0,262092.0,5391.45,-11.48,50.0,X-LC,9.07,14.0,0.20,1.77,19.80,X40N,ATH,FMCG
51,KOTAKBANK,-3.30,-0.96,22.28,21.11,30555.0,-1332.0,137140.0,453.24,-15.04,45.0,X-LC,8.59,12.0,-0.04,0.92,4.88,X40,ATH,BANKS
86,VALIANTORG,-3.28,-45.21,217.85,74.15,195283.0,-73964.0,89641.0,838.00,-260.95,52.0,H-SC,17.13,145.0,-0.38,0.60,33.40,XR,NTT,CHEMICALS
18,COFFEEDAY,-2.88,-56.65,212.01,35.27,104370.0,-64320.0,49229.0,80.00,-65.79,46.0,L-SC,25.20,266.0,-0.62,0.33,21.40,XR,NTT,HOTELS

In [12]:
# top 5 to exit based on CumlRnk
df_tmp = df_portfolio_features[~df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])]
df_tmp = df_tmp[(df_tmp['Current P/L%'] > -1) & (df_tmp['Current P/L%'] < 1)].sort_values(by = 'CumlRnk', ascending=False)
df_tmp[cols].head()

Empty DataFrame
Columns: [Symbol, Today P/L%, Current P/L%, FTT%, OTT%, FTT Amt, Current P/L, Current, FTT, Dev%_PE, RSI_14, Conviction, Spread%, CumlRnk, RRR Ind, CurrAlloc%, Gained%, Criteria, Strategy, Category]
Index: []

In [13]:
# OX40N stocks to exit
df_tmp = df_portfolio_features[(df_portfolio_features['Symbol'].isin(list_ox40n))].sort_values(by = 'Current P/L%', ascending=False)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
25,FINCABLES,1.82,27.75,62.76,107.91,118370.0,40964.0,188608.0,1641.55,14.66,71.0,M-SC,11.60,220.0,0.35,1.27,41.90,OX40N,ATH,CABLES
72,SIS,12.98,-7.77,31.47,21.26,32228.0,-8624.0,102408.0,528.00,2437.82,81.0,H-SC,7.64,168.0,-0.27,0.69,52.27,OX40N,NTT,MISC
83,TTKPRESTIG,7.21,-29.64,42.25,0.09,29959.0,-29867.0,70910.0,770.00,64.57,64.0,M-SC,17.73,250.0,-1.00,0.48,26.27,OX40N,NTT,DURABLES
16,CERA,0.71,-30.83,79.11,23.89,96253.0,-54233.0,121670.0,9475.00,-33.17,58.0,H-SC,12.15,153.0,-0.56,0.82,16.92,OX40N,NTT,CERAMICS
50,KANSAINER,-0.19,-34.32,72.76,13.47,128879.0,-92538.0,177129.0,340.00,-43.52,54.0,H-SC,16.16,162.0,-0.72,1.19,23.73,XY24,NTT,PAINTS

In [14]:
# top 5 to book for rotation
df_tmp = df_portfolio_features[(df_portfolio_features['Current P/L%'] > 20) ].sort_values(by = 'CumlRnk', ascending=False)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
25,FINCABLES,1.82,27.75,62.76,107.91,118370.0,40964.0,188608.0,1641.55,14.66,71.0,M-SC,11.6,220.0,0.35,1.27,41.9,OX40N,ATH,CABLES

In [15]:
# top 5 to monitor for exit
df_tmp = df_portfolio_features[~df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])]
df_tmp = df_tmp[(df_tmp['Current P/L%'] > 0) ].sort_values(by = 'Dev%_PE', ascending=False)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
74,STARHEALTH,-0.28,1.44,45.17,47.26,128809.0,4042.0,285165.0,761.00,60.18,69.0,H-SC,7.10,173.0,0.03,1.92,47.68,XY24,NTT,INSURANCE
25,FINCABLES,1.82,27.75,62.76,107.91,118370.0,40964.0,188608.0,1641.55,14.66,71.0,M-SC,11.60,220.0,0.35,1.27,41.90,OX40N,ATH,CABLES
68,SATIN,4.76,2.27,48.47,51.83,136950.0,6262.0,282546.0,274.00,-8.02,69.0,H-SC,10.07,159.0,0.05,1.90,37.64,XY24,NTT,FINANCE
55,MASFIN,2.07,6.23,14.44,21.57,15030.0,6105.0,104085.0,397.04,-8.31,72.0,H-SC,1.13,167.0,0.41,0.70,34.50,XR,ATH,FINANCE

In [16]:
# top 5 to book for rotation from weak conviction
df_tmp = df_portfolio_features[~df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])]
df_tmp = df_tmp[~df_tmp['Criteria'].isin(['XY25','XY24','X40', 'X40N'])].sort_values(by = 'RRR Ind', ascending=False)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
55,MASFIN,2.07,6.23,14.44,21.57,15030.0,6105.0,104085.0,397.04,-8.31,72.0,H-SC,1.13,167.0,0.41,0.70,34.50,XR,ATH,FINANCE
25,FINCABLES,1.82,27.75,62.76,107.91,118370.0,40964.0,188608.0,1641.55,14.66,71.0,M-SC,11.60,220.0,0.35,1.27,41.90,OX40N,ATH,CABLES
73,SONACOMS,-5.95,-1.20,40.78,39.09,40756.0,-1217.0,99942.0,804.02,-21.69,54.0,M-MC,16.87,193.0,-0.03,0.67,41.38,AR,ATH,AUTO
42,INDIAMART,-2.00,-11.41,133.36,106.72,145709.0,-14076.0,109260.0,4810.62,-59.96,41.0,H-SC,9.33,140.0,-0.10,0.74,4.97,AR,ATH,MISC
91,ZYDUSLIFE,0.85,-5.15,42.99,35.63,85460.0,-10784.0,198790.0,1286.17,-17.57,46.0,H-MC,3.86,120.0,-0.13,1.34,4.52,AR,ATH,PHARMA

In [17]:
# top 5 to accumulate based on lowest RSI_14
df_tmp = df_portfolio_features[df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])].sort_values(by = 'RSI_14', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
33,HCLTECH,-0.58,-22.63,57.05,21.51,106783.0,-54749.0,187175.0,1872.35,-18.53,29.0,X-LC,9.26,8.0,-0.51,1.26,0.00,X40,ATH,IT
45,INFY,-1.29,-20.58,69.04,34.24,171555.0,-64402.0,248486.0,1972.00,-37.59,34.0,X-LC,13.83,3.0,-0.38,1.68,1.26,X40,NTT,IT
35,HDFCLIFE,-0.47,-4.46,39.40,33.18,56388.0,-6683.0,143117.0,814.30,-25.42,39.0,X-LC,17.49,31.0,-0.12,0.96,3.19,X40,ATH,INSURANCE
39,ICICIGI,-1.01,-7.54,29.08,19.34,53801.0,-15097.0,185012.0,2252.93,-22.28,39.0,X-MC,5.84,66.0,-0.28,1.25,3.33,X40,ATH,INSURANCE
27,GLAXO,0.20,-6.02,48.06,39.15,90007.0,-12004.0,187280.0,3466.20,-28.31,41.0,X-MC,8.20,56.0,-0.13,1.26,3.61,X40,ATH,PHARMA

In [18]:
# top 5 to accumulate based on Spread and CumlRnk
df_tmp = df_portfolio_features[df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])]
df_tmp = df_tmp[(df_tmp['CumlRnk'] < 100)].sort_values(by = 'Spread%', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
88,VOLTAS,0.93,12.94,28.56,45.20,61848.0,24813.0,216555.0,1856.00,29.27,54.0,X-MC,2.12,79.0,0.40,1.46,18.70,XY25,NTT,AC
84,UNITDSPR,-0.94,-3.53,25.19,20.77,56897.0,-8274.0,225870.0,1644.00,-14.48,48.0,X-MC,3.44,64.0,-0.15,1.52,7.75,X40N,NTT,BREWERIES
81,TMPV,0.18,-22.12,75.36,36.58,208854.0,-78699.0,277142.0,600.00,-83.62,49.0,X-LC,4.62,4.0,-0.38,1.87,15.51,XY24,NTT,AUTO
65,RELIANCE,1.95,-6.36,33.82,25.30,63640.0,-12791.0,188172.0,1952.00,-8.88,65.0,X-LC,5.25,21.0,-0.20,1.27,11.81,XY25,BTT,REFINERIES
87,VBL,-1.15,2.58,31.97,35.37,103575.0,8134.0,323976.0,670.16,-9.53,67.0,X-LC,5.37,13.0,0.08,2.18,33.16,X40N,ATH,FMCG

In [19]:
# top 5 to accumulate based on lowest Gained%
df_tmp = df_portfolio_features[df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])].sort_values(by = 'Gained%', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
33,HCLTECH,-0.58,-22.63,57.05,21.51,106783.0,-54749.0,187175.0,1872.35,-18.53,29.0,X-LC,9.26,8.0,-0.51,1.26,0.00,X40,ATH,IT
45,INFY,-1.29,-20.58,69.04,34.24,171555.0,-64402.0,248486.0,1972.00,-37.59,34.0,X-LC,13.83,3.0,-0.38,1.68,1.26,X40,NTT,IT
1,ABBOTINDIA,0.49,-14.25,37.70,18.07,57817.0,-25495.0,153360.0,35195.00,-27.11,45.0,X-MC,11.97,58.0,-0.44,1.03,1.51,X40,ATH,PHARMA
79,TCS,-1.90,-28.75,77.65,26.57,256301.0,-133201.0,330072.0,4311.59,-39.69,42.0,X-LC,13.98,2.0,-0.52,2.23,3.01,X40,ATH,IT
35,HDFCLIFE,-0.47,-4.46,39.40,33.18,56388.0,-6683.0,143117.0,814.30,-25.42,39.0,X-LC,17.49,31.0,-0.12,0.96,3.19,X40,ATH,INSURANCE

In [20]:
# top 5 to accumulate based on lowest CurrAlloc%
df_tmp = df_portfolio_features[df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])].sort_values(by = 'CurrAlloc%', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
64,RELAXO,0.69,-61.13,291.80,52.31,164657.0,-88732.0,56428.0,1176.00,-58.57,51.0,X-SC,26.13,92.0,-0.54,0.38,26.17,X40N,NTT,FOOTWEAR
10,BATAINDIA,-0.06,-53.68,191.92,35.20,114373.0,-69076.0,59594.0,2096.00,-21.88,47.0,X-SC,26.19,91.0,-0.60,0.40,18.19,X40,NTT,FOOTWEAR
60,QUESS,6.90,-13.33,100.65,73.90,93156.0,-14239.0,92554.0,424.00,-53.17,66.0,X-SC,14.96,80.0,-0.15,0.62,24.51,XY24,NTT,MISC
51,KOTAKBANK,-3.30,-0.96,22.28,21.11,30555.0,-1332.0,137140.0,453.24,-15.04,45.0,X-LC,8.59,12.0,-0.04,0.92,4.88,X40,ATH,BANKS
59,PIDILITIND,-0.95,-3.44,22.58,18.37,30768.0,-4850.0,136260.0,1670.26,-32.34,47.0,X-LC,6.99,5.0,-0.16,0.92,6.99,X40,ATH,CHEMICALS

In [21]:
# top 5 to accumulate based on CumlRnk
df_tmp = df_portfolio_features.sort_values(by = 'CumlRnk', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
47,ITC,-1.27,-18.11,45.38,19.06,126413.0,-61600.0,278566.0,452.00,-55.12,56.0,X-LC,16.66,1.0,-0.49,1.88,8.06,X40,NTT,FMCG
79,TCS,-1.90,-28.75,77.65,26.57,256301.0,-133201.0,330072.0,4311.59,-39.69,42.0,X-LC,13.98,2.0,-0.52,2.23,3.01,X40,ATH,IT
45,INFY,-1.29,-20.58,69.04,34.24,171555.0,-64402.0,248486.0,1972.00,-37.59,34.0,X-LC,13.83,3.0,-0.38,1.68,1.26,X40,NTT,IT
81,TMPV,0.18,-22.12,75.36,36.58,208854.0,-78699.0,277142.0,600.00,-83.62,49.0,X-LC,4.62,4.0,-0.38,1.87,15.51,XY24,NTT,AUTO
59,PIDILITIND,-0.95,-3.44,22.58,18.37,30768.0,-4850.0,136260.0,1670.26,-32.34,47.0,X-LC,6.99,5.0,-0.16,0.92,6.99,X40,ATH,CHEMICALS

In [22]:
# top 5 for average up
df_tmp = df_portfolio_features[(df_portfolio_features['Dev%_200'] > 5)].sort_values(by = 'CurrAlloc%', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
44,INDUSINDBK,0.37,-32.12,95.77,32.89,50192.0,-24798.0,52409.0,1800.00,-346.50,64.0,L-MC,3.90,258.0,-0.49,0.35,29.00,XR,NTT,BANKS
73,SONACOMS,-5.95,-1.20,40.78,39.09,40756.0,-1217.0,99942.0,804.02,-21.69,54.0,M-MC,16.87,193.0,-0.03,0.67,41.38,AR,ATH,AUTO
72,SIS,12.98,-7.77,31.47,21.26,32228.0,-8624.0,102408.0,528.00,2437.82,81.0,H-SC,7.64,168.0,-0.27,0.69,52.27,OX40N,NTT,MISC
55,MASFIN,2.07,6.23,14.44,21.57,15030.0,6105.0,104085.0,397.04,-8.31,72.0,H-SC,1.13,167.0,0.41,0.70,34.50,XR,ATH,FINANCE
75,SURYODAY,2.20,-11.00,38.24,23.03,60945.0,-19696.0,159375.0,216.00,73.25,72.0,H-SC,7.10,166.0,-0.32,1.07,35.92,XR,NTT,BANKS

In [23]:
# top 5 RSP
df_tmp = df_portfolio_features.sort_values(by = 'RSP', ascending=False)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
72,SIS,12.98,-7.77,31.47,21.26,32228.0,-8624.0,102408.0,528.00,2437.82,81.0,H-SC,7.64,168.0,-0.27,0.69,52.27,OX40N,NTT,MISC
9,BANDHANBNK,2.72,-1.31,94.98,92.42,261101.0,-3658.0,274901.0,400.00,135.63,76.0,H-SC,7.29,174.0,-0.01,1.85,51.44,XY24,NTT,BANKS
61,RAJESHEXPO,0.94,-76.76,330.52,0.07,105386.0,-105292.0,31885.0,518.00,1069.19,52.0,L-SC,31.44,268.0,-1.00,0.21,49.69,OX40N,NTT,JEWELLERY
68,SATIN,4.76,2.27,48.47,51.83,136950.0,6262.0,282546.0,274.00,-8.02,69.0,H-SC,10.07,159.0,0.05,1.90,37.64,XY24,NTT,FINANCE
87,VBL,-1.15,2.58,31.97,35.37,103575.0,8134.0,323976.0,670.16,-9.53,67.0,X-LC,5.37,13.0,0.08,2.18,33.16,X40N,ATH,FMCG

In [24]:
# Top N allocation
df_tmp = df_portfolio_features.sort_values(by = 'CurrAlloc%', ascending=False)
top_n_values = [10, 25, 50]

sum_df = pd.DataFrame({
    'Top_N': top_n_values,
    'Sum_Alloc%': [df_tmp['CurrAlloc%'].head(n).sum() for n in top_n_values]
})

sum_df

   Top_N  Sum_Alloc%
0     10       19.12
1     25       42.62
2     50       72.71

In [25]:
# market-cap-wise allocation
df_tmp = df_portfolio_features[cols]
df_tmp.groupby(df_tmp['Conviction'].str[-2:])['CurrAlloc%'].sum().sort_values(ascending=False)

Conviction
SC    42.39
LC    31.76
MC    25.85
Name: CurrAlloc%, dtype: float64

In [26]:
# criteria-wise allocation
df_portfolio_features.groupby('Criteria')['CurrAlloc%'].sum().sort_values(ascending=False)

Criteria
XY24     27.08
X40      25.53
X40N     16.77
XR        9.12
XY25      7.05
OX40N     6.92
AR        6.70
SR        0.83
Name: CurrAlloc%, dtype: float64

In [27]:
# conviction-wise allocation
df_portfolio_features.groupby('Conviction')['CurrAlloc%'].sum().sort_values(ascending=False)

Conviction
X-LC    29.52
H-SC    22.11
X-MC    20.98
M-SC    10.06
X-SC     9.68
H-MC     2.54
M-MC     1.98
H-LC     1.30
M-LC     0.94
L-SC     0.54
L-MC     0.35
Name: CurrAlloc%, dtype: float64

In [28]:
# sector-wise stats
df_tmp = df_portfolio_features.groupby('Category')[['CurrAlloc%', 'Current', 'Current P/L', 'FTT Amt']].sum().sort_values(by=['Current', 'Current P/L'], ascending=False)
df_tmp['Current P/L%'] = round(df_tmp['Current P/L'] * 100 / df_tmp['Current'], 2)
df_tmp['FTT%'] = round(df_tmp['FTT Amt'] * 100 / df_tmp['Current'], 2)
cols = ['CurrAlloc%', 'Current P/L%', 'FTT%']
df_tmp[cols].sort_values(by=['CurrAlloc%'], ascending=False)

               CurrAlloc%  Current P/L%    FTT%
Category
FMCG                15.64        -14.05   54.28
FINANCE             10.86        -14.36   64.10
IT                  10.56        -43.99  116.49
MISC                 6.82        -32.67   90.30
AUTO                 6.63        -11.43   53.20
BANKS                5.66         -7.96   57.88
INSURANCE            5.30         -5.25   41.06
PAINTS               5.10        -30.30   52.93
PHARMA               4.74         -5.26   39.09
ELECTRICAL           4.13        -15.77   56.98
AC                   1.99         -8.19   37.53
CHEMICALS            1.98        -37.94  120.15
HEALTHCARE           1.96        -22.89   54.96
DURABLES             1.83        -43.16   77.99
APPARELS             1.74         -4.17   39.71
FOOTWEAR             1.72        -72.85  142.15
TRAVEL               1.71        -75.86  163.91
BREWERIES            1.52         -3.66   25.19
REALTY               1.39         -7.42   25.07
CERAMICS             1.30        -59.64  108.14
CABLES               1.27         21.72   62.76
REFINERIES           1.27         -6.80   33.82
ENGINEERING          1.18        -38.77  102.25
CEMENT               1.14        -58.89  177.75
JEWELLERY            1.05       -104.25  175.21
ENTERTAINMENT        0.74        -75.71  180.51
TEXTILES             0.44        -42.72   83.42
HOTELS               0.33       -130.65  212.01

In [29]:
# money to be made criteria-wise
df_portfolio_features.groupby('Criteria')['FTT Amt'].agg(['sum', 'count']).sort_values(by='sum', ascending=False)

                sum  count
Criteria
XY24      3577171.0     21
X40       1918027.0     19
XR        1328047.0     13
X40N      1238664.0     13
AR        1192478.0      9
OX40N      764645.0     10
XY25       394579.0      5
SR         296184.0      2

In [30]:
# money to be made conviction-wise
df_portfolio_features.groupby('Conviction')['FTT Amt'].agg(['sum', 'count']).sort_values(by='sum', ascending=False)

                  sum  count
Conviction
H-SC        3504561.0     24
X-LC        1921877.0     21
X-MC        1622145.0     15
M-SC        1426389.0     14
X-SC        1368342.0      9
H-MC         321088.0      2
L-SC         209756.0      2
M-LC         152736.0      1
M-MC          91251.0      2
L-MC          50192.0      1
H-LC          41458.0      1

In [31]:
# money to be made criteria and conviction-wise
df_portfolio_features.groupby(['Conviction', 'Criteria'])['FTT Amt'].agg(['sum', 'count']).sort_values(by='sum', ascending=False)

                           sum  count
Conviction Criteria
H-SC       XY24      1122438.0      6
X-LC       X40       1036462.0     10
H-SC       AR         949106.0      5
M-SC       XY24       849692.0      6
H-SC       XR         807208.0      7
X-SC       XY24       785099.0      4
X-MC       X40        676512.0      7
           X40N       487033.0      4
X-SC       X40N       378190.0      3
X-LC       X40N       373441.0      6
           XY24       344162.0      2
M-SC       OX40N      329634.0      5
H-SC       OX40N      329625.0      4
           SR         296184.0      2
X-MC       XY24       240152.0      2
H-MC       XY24       235628.0      1
X-MC       XY25       218448.0      2
X-SC       X40        205053.0      2
M-SC       XR         171365.0      2
M-LC       XR         152736.0      1
X-LC       XY25       125636.0      2
L-SC       OX40N      105386.0      1
           XR         104370.0      1
H-MC       AR          85460.0      1
M-SC       AR          75698.0      1
M-MC       XY25        50495.0      1
L-MC       XR          50192.0      1
X-LC       XR          42176.0      1
H-LC       AR          41458.0      1
M-MC       AR          40756.0      1

In [32]:
# notebook execution time

end_time = time.time()
execution_time = round(end_time - start_time, 0)
print(f"Notebook execution time: {execution_time} seconds")

Notebook execution time: 37.0 seconds