<a href="https://colab.research.google.com/github/ankit-rathi/Quantvesting_v2/blob/main/myStocks_Portfolio_Analysis.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
'''
!pip install pandas==2.2.2 -qq
!pip install pyxirr -qq
!pip install ta -qq
!pip install yfinance==0.2.59 -qq
'''

'\n!pip install pandas==2.2.2 -qq\n!pip install pyxirr -qq\n!pip install ta -qq\n!pip install yfinance==0.2.59 -qq\n'

In [2]:
# import libraries

import numpy as np
import pandas as pd
import datetime
import warnings
warnings.filterwarnings('ignore')
import yfinance as yfin
import ta
import matplotlib.pyplot as plt
import requests

In [3]:
# notebook start time
import time
import datetime
import pytz

start_time = time.time()

# function to print date timestamp
def print_date_time():
  tz_NY = pytz.timezone('Asia/Kolkata')
  datetime_NY = datetime.datetime.now(tz_NY)
  print("Run date time (IST):", datetime_NY.strftime("%Y-%m-%d %H:%M:%S"))

In [4]:
# function to get booked and reserved amount
def get_amt():
  # fetch the JSON data from the URL
  url = "https://raw.githubusercontent.com/ankit-rathi/Tradevesting_v1/main/data/myPortfolioAmts.json"
  response = requests.get(url)
  pf_amts = response.json()  # parse the JSON data

  # extract values from the JSON
  py_booked_amt_dm = pf_amts["py_booked_amt_dm"]
  py_booked_amt_sv = pf_amts["py_booked_amt_sv"]
  cy_booked_amt_dm = pf_amts["cy_booked_amt_dm"]
  cy_booked_amt_sv = pf_amts["cy_booked_amt_sv"]
  reserve_amt_dm = pf_amts["reserve_amt_dm"]
  reserve_amt_sv = pf_amts["reserve_amt_sv"]

  # perform calculations
  py_booked_amt = py_booked_amt_dm + py_booked_amt_sv
  cy_booked_amt = cy_booked_amt_dm + cy_booked_amt_sv
  reserve_amt = reserve_amt_dm + reserve_amt_sv
  total_booked_amt = py_booked_amt + cy_booked_amt

  return total_booked_amt, reserve_amt, cy_booked_amt, py_booked_amt

gen_output = 0

In [5]:
# function to format the amount
def format_amt(number):
    abs_number = abs(number)

    if abs_number >= 1_00_00_000:  # Crores
        formatted_amt = f"{number / 1_00_00_000:.2f} C"
    elif abs_number >= 1_00_000:  # Lakhs
        formatted_amt = f"{number / 1_00_000:.2f} L"
    elif abs_number >= 1_000:  # Thousands
        formatted_amt = f"{number / 1_000:.2f} K"
    else:
        formatted_amt = f"{number:.2f}"

    return formatted_amt

# function to set start and end date
def get_start_end_date():
  start_date = (datetime.date.today() + datetime.timedelta(days=-365)).strftime('%Y-%m-%d')
  end_date = (datetime.date.today() + datetime.timedelta(days=1)).strftime('%Y-%m-%d')
  return start_date, end_date

# function to fetch my portfolio csv
def get_mypfs_df():
  mypfs_df = pd.read_csv('https://raw.githubusercontent.com/ankit-rathi/Tradevesting_v1/main/data/myPortfolioStocks.csv')
  return mypfs_df

# function to fetch my prospects csv
def get_mypps_df():
  mypps_df = pd.read_csv('https://raw.githubusercontent.com/ankit-rathi/Tradevesting_v1/main/data/myProspectsScrips.csv')
  return mypps_df

# function to fetch screener data
def get_myscreen_df():
  myscreen_df = pd.read_csv('https://raw.githubusercontent.com/ankit-rathi/Tradevesting_v1/main/data/myScreenerDB.csv')
  return myscreen_df

# function to fetch momentum data
def get_myinvmt_df():
  myinvmt_df = pd.read_csv('https://raw.githubusercontent.com/ankit-rathi/Tradevesting_v1/main/data/myInvestments.csv')
  return myinvmt_df

# function to get the stock ids
def get_stock_ids(df_pf):
  stock_n100 = df_pf['Symbol'].unique()

  exclude = ['CADILAHC','MMTC', 'MASFIN']

  stock_ids = df_pf[~df_pf['Symbol'].isin(exclude) ]['Symbol'].unique()

  #mypf = mypf[mypf.Forecast.notnull()]
  #stock_ids = mypf['Symbol'].unique()

  #stock_ids.sort()
  return stock_ids

# get features from screener data
def get_screener_features():
  myscreen_df = get_myscreen_df()
  cols = ['Symbol', 'EPS', 'MedPE', 'ROCE%', 'ROE%', 'CapType']
  return myscreen_df[cols]

# get relative strength
def get_relative_strength(stock_list):

    # Dictionary to store stock tickers and their corresponding percentage price change
    stock_changes = {}

    # Loop through each stock and fetch its price data
    for stock in stock_list:
        try:
            # Download the stock data for the given date range
            stock_data = yfin.Ticker(stock + '.NS').history(period='1mo', interval='1d')[map(str.title, ['open', 'close', 'low', 'high', 'volume'])]

            # Calculate the percentage change for the stock
            if len(stock_data) > 0:
                start_price = stock_data['Close'].iloc[0]
                end_price = stock_data['Close'].iloc[-1]
                percent_change = round(((end_price - start_price) / start_price) * 100, 2)
                stock_changes[stock] = percent_change
            else:
                stock_changes[stock] = np.nan  # If no data is available, set to NaN

        except Exception as e:
            print(f"Error fetching data for {stock}: {e}")
            stock_changes[stock] = np.nan

    # Create a DataFrame with stock tickers and their percentage changes
    df = pd.DataFrame(list(stock_changes.items()), columns=['Symbol', 'Percent_Change'])

    # Drop any stocks with missing data (NaN values)
    df = df.dropna()

    # Calculate the percentile rank based on percentage change
    df['RSP'] = round(df['Percent_Change'].rank(pct=True) * 100, 2)
    cols = ['Symbol', 'RSP']
    df = df[cols]
    # Sort by percentile rank (optional)
    df = df.sort_values(by='RSP', ascending=False).reset_index(drop=True)

    return df

In [6]:
# function to get stock technicals
def stock_prec_dev(stock_symbol):
    #stock_symbol = 'ULTRACEMCO.NS'
    short_window = 20
    mid_window = 50
    long_window = 200
    moving_avg = 'SMA'

    start = datetime.datetime(*map(int, start_date.split('-')))
    end = datetime.datetime(*map(int, end_date.split('-')))

    stock_df = yfin.Ticker(stock_symbol + '.NS').history(period='max', interval='1d')[map(str.title, ['open', 'close', 'low', 'high', 'volume'])]

    stock_df['Max'] = round(max(stock_df['Close']),2)
    stock_df = stock_df[(stock_df.index <= end_date) & (stock_df.index >= start_date)]
    stock_df['200_SMA'] = round(stock_df['Close'].rolling(window = 200, min_periods = 1).mean(),0)
    stock_df['Dev%_200'] = round((stock_df['Close'] - stock_df['200_SMA'])*100/stock_df['200_SMA'],2)
    stock_df.dropna(axis = 0, inplace = True) # remove any null rows

    stock_df['20_SMA'] = stock_df['Close'].rolling(window=20).mean()
    stock_df['50_SMA'] = stock_df['Close'].rolling(window=50).mean()
    stock_df['Symbol'] = stock_symbol

    stock_df['Close'] = round(stock_df['Close'],2)
    stock_df['Min'] = round(min(stock_df['Close']),2)
    stock_df['RSI_14'] = ta.momentum.RSIIndicator(close=stock_df['Close'], window=14).rsi()
    stock_df['RSI_14'] = round(stock_df['RSI_14'],0)
    stock_df['Prev_Close'] = stock_df['Close'].shift(1)
    stock_df.drop(['Open', 'Low', 'High', 'Volume'], axis=1, inplace=True)
    stock_df = stock_df.tail(1)

    max_SMA = max(stock_df['20_SMA'].item(), stock_df['50_SMA'].item(), stock_df['200_SMA'].item())
    min_SMA = min(stock_df['20_SMA'].item(), stock_df['50_SMA'].item(), stock_df['200_SMA'].item())
    ABS_Spread = max_SMA - min_SMA
    stock_df['Spread%'] = round((ABS_Spread / stock_df['200_SMA'].item()) * 100,2)

    return stock_df

# function to compute stock attributes
def get_common_features(stock_ids, df_mypf):

  df_prec_dev = pd.DataFrame()
  df_tmp = get_screener_features()
  df_rs = get_relative_strength(stock_ids)

  for stock_id in stock_ids:
      tmp = stock_prec_dev(stock_id)
      tmp = tmp.reset_index()
      df_prec_dev = pd.concat([df_prec_dev, tmp], ignore_index = True)
  df_prec_dev = pd.merge(df_prec_dev, df_mypf, on= 'Symbol')
  df_prec_dev = pd.merge(df_prec_dev, df_tmp, on= 'Symbol', how='left')
  df_prec_dev = pd.merge(df_prec_dev, df_rs, on= 'Symbol', how='left')
  #print(df_prec_dev.columns)
  df_prec_dev['Curr_PE'] = round(df_prec_dev['Close']/df_prec_dev['EPS'],1)
  df_prec_dev['Dev%_PE'] = round((df_prec_dev['Curr_PE'] - df_prec_dev['MedPE'])*100/df_prec_dev['MedPE'],2)
  df_prec_dev['Conviction'] = df_prec_dev['Conviction'] + '-' + df_prec_dev['CapType']
  return df_prec_dev

# function to arrange stock features
def arrange_features(df_stocks, common_cols, diff_cols):
  df_stocks_common = df_stocks[common_cols].drop_duplicates()
  df_stocks_diff = df_stocks[diff_cols]
  df_stocks_diff['Investment'] = df_stocks_diff['AvgCost'] * df_stocks_diff['Shares']
  df_stocks_diff = df_stocks_diff.groupby(['Symbol'])[['Shares', 'Investment']].aggregate(['sum']).reset_index()
  df_stocks_diff.columns = ['Symbol', 'Shares', 'Investment']
  df_stocks_diff['AvgCost'] = round(df_stocks_diff['Investment']/df_stocks_diff['Shares'],2)
  df_stocks = pd.merge(df_stocks_diff, df_stocks_common, on='Symbol')
  return df_stocks

# plot fact distribution across dimension
def plot_pie_chart(df, dimension, fact):
  # grouping the data by category and calculating the sum of fact for each type
  grouped_data = df.groupby(dimension)[fact].sum()

  # sorting the grouped data in descending order
  grouped_data = grouped_data.sort_values(ascending=False)

  # creating a pie chart
  grouped_data.plot.pie(autopct='%1.1f%%', startangle=90, figsize=(6, 6))

  # adding a title and displaying the plot
  plt.title(f'{dimension} {fact} Distribution')
  plt.ylabel('')  # To hide the y-label
  plt.show()

In [7]:
# function to get portfolio features

def get_portfolio_features(df_common_features):

  print_date_time()
  print('-------------------')

  #df_common_features["Target"] = df_common_features["Target"].fillna(df_common_features["Max"])
  df_common_features['NTT'] = np.where(df_common_features['Strategy']== 'NTT', df_common_features["Target"], df_common_features['Max'])
  df_common_features['LTT'] = np.where(df_common_features['Strategy']== 'BTT', df_common_features["Target"], df_common_features['Max'])
  df_common_features['BOL'] = df_common_features['Min']

  tmp_df = df_common_features[df_common_features['Symbol'].isin(mypf_df[mypf_df['InPortfolio'] != 'NA'].Symbol.values)]
  print('qualified stocks: '+str(len(tmp_df['Symbol'].unique())))
  tmp_df1 = tmp_df[tmp_df['LatestQtr'] == 1]
  print('with latest results: '+str(len(tmp_df1['Symbol'].unique())))
  tmp_df1 = tmp_df1[tmp_df1['StarStock'] == 1]
  print('still star stocks: '+str(len(tmp_df1['Symbol'].unique())))
  tmp_df['Investment'] = tmp_df['AvgCost'] * tmp_df['Shares']
  tmp_df['Current'] = round(tmp_df['Close'] * tmp_df['Shares'],0)
  tmp_df['Previous'] = tmp_df['Prev_Close'] * tmp_df['Shares']
  tmp_df['EstimatedST'] = tmp_df['NTT'] * tmp_df['Shares']
  tmp_df['EstimatedLT'] = tmp_df['LTT'] * tmp_df['Shares']
  tmp_df['Current P/L'] = round((tmp_df['Current'] - tmp_df['Investment']),0)
  tmp_df['Today P/L%'] = round((tmp_df['Current'] - tmp_df['Previous'])*100/tmp_df['Previous'],2)
  tmp_df['Current P/L%'] = round((tmp_df['Current'] - tmp_df['Investment'])*100/tmp_df['Investment'],2)
  tmp_df['EstimatedST P/L%'] = round((tmp_df['EstimatedST'] - tmp_df['Investment'])*100/tmp_df['Investment'],2)
  tmp_df['EstimatedLT P/L%'] = round((tmp_df['EstimatedLT'] - tmp_df['Investment'])*100/tmp_df['Investment'],2)
  tmp_df['NTT%'] = round((tmp_df['NTT'] - tmp_df['Close'])*100/tmp_df['Close'],2)
  tmp_df['LTT%'] = round((tmp_df['LTT'] - tmp_df['Close'])*100/tmp_df['Close'],2)
  tmp_df['Gained%'] = round((tmp_df['Close'] - tmp_df['BOL'])*100/tmp_df['BOL'],2)
  investment = round(sum(tmp_df['AvgCost']*tmp_df['Shares']),0)
  current = round(sum(tmp_df['Close']*tmp_df['Shares']),0)
  tmp_df['InitAlloc%'] = round(tmp_df['Investment']*100/investment,2)
  tmp_df['CurrAlloc%'] = round(tmp_df['Current']*100/current,2)
  tmp_df['FTT'] = tmp_df['LTT']
  tmp_df.loc[tmp_df['Strategy'] == 'NTT', 'FTT'] = tmp_df['NTT']
  tmp_df['FTT%'] = tmp_df['LTT%']
  tmp_df.loc[tmp_df['Strategy'] == 'NTT', 'FTT%'] = tmp_df['NTT%']
  tmp_df['FTT Amt'] = round(tmp_df['FTT%'] * tmp_df['Current']/100,0)
  tmp_df['OTT%'] = round((tmp_df['FTT'] - tmp_df['AvgCost'])*100/tmp_df['AvgCost'],2)
  tmp_df['RRR Ind'] = round(tmp_df['Current P/L']/tmp_df['FTT Amt'],2)
  tmp_df['Risk Ind'] = round(tmp_df['Current P/L%']*tmp_df['CurrAlloc%'],0)

  return tmp_df

# function to print portfolio features
def print_portfolio_stats(df_portfolio_features, myinvmt_df):
  from pyxirr import xirr

  total_booked_amt, reserve_amt, cy_booked_amt, py_booked_amt = get_amt()

  dates = myinvmt_df['Date'].values
  dates = np.append(dates, datetime.date.today().strftime('%d-%b-%y'))
  investment = myinvmt_df['Investment'].values
  dates= pd.to_datetime(dates)

  current = round(sum(df_portfolio_features['Close']*df_portfolio_features['Shares']),0) + reserve_amt
  investment_xirr = np.append(investment, current)
  cagr = round(xirr(pd.DataFrame({"dates": dates, "amounts": investment_xirr}))*100,2)

  investment = -sum(investment)
  invested = round(sum(df_portfolio_features['AvgCost']*df_portfolio_features['Shares']),0) + reserve_amt
  previous = round(sum(df_portfolio_features['Prev_Close']*df_portfolio_features['Shares']),0) + reserve_amt
  cy_invested = investment + py_booked_amt

  today_pnl_amount = current-previous
  today_pnl_percentage = round((current-previous)*100/previous,2)

  curr_pnl_amount = current-invested
  curr_pnl_percentage = round((curr_pnl_amount)*100/(cy_invested),2)

  cy_pnl_amount = cy_booked_amt + curr_pnl_amount
  cy_pnl_percentage = round((cy_pnl_amount)*100/cy_invested,2)

  overall_pnl_amount = total_booked_amt + curr_pnl_amount
  overall_pnl_percentage = round((overall_pnl_amount)*100/investment,2)

  estimate_st = round(sum(df_portfolio_features['FTT']*df_portfolio_features['Shares']),0)  + reserve_amt
  est_st_pnl_amount = estimate_st-current
  est_st_pnl_percentage = round((est_st_pnl_amount)*100/current,2)

  estimate_lt = round(sum(df_portfolio_features['LTT']*df_portfolio_features['Shares']),0)  + reserve_amt
  est_lt_pnl_amount = estimate_lt-current
  est_lt_pnl_percentage = round((est_lt_pnl_amount)*100/current,2)

  total_profit = round(sum(df_portfolio_features[df_portfolio_features['Current P/L%'] > 0]['Current']) - sum(df_portfolio_features[df_portfolio_features['Current P/L%'] > 0]['Investment']),0)
  total_loss = round(sum(df_portfolio_features[df_portfolio_features['Current P/L%'] < 0]['Current']) - sum(df_portfolio_features[df_portfolio_features['Current P/L%'] < 0]['Investment']),0)

  cy_booked_percentage = round((cy_booked_amt)*100/current,2)
  py_booked_percentage = round((py_booked_amt)*100/investment,2)
  total_booked_percentage = round((total_booked_amt)*100/investment,2)

  print('-------------------')
  print('Initial Investment: ', format_amt(investment))
  print('CY Investment: ', format_amt(cy_invested))
  print('Reserve: ', format_amt(reserve_amt))
  print('Current: ',  format_amt(current))
  print('-------------------')
  print('Today PnL: '+ '{} ({}%)'.format(format_amt(today_pnl_amount), today_pnl_percentage))
  print('Current PnL: '+ '{} ({}%)'.format(format_amt(curr_pnl_amount), curr_pnl_percentage))
  print('CY Booked + Current PnL: '+ '{} ({}%)'.format(format_amt(cy_pnl_amount), cy_pnl_percentage))
  print('-------------------')
  print('Total profit: ', format_amt(total_profit))
  print('Total loss: ', format_amt(total_loss))
  print('-------------------')
  print('Total Booked + Current PnL: '+ '{} ({}%)'.format(format_amt(overall_pnl_amount), overall_pnl_percentage))
  print('Total Booked PnL: '+ '{} ({}%)'.format(format_amt(total_booked_amt), total_booked_percentage))
  print('Curr Year Booked PnL: '+ '{} ({}%)'.format(format_amt(cy_booked_amt), cy_booked_percentage))
  print('Prev Year Booked PnL: '+ '{} ({}%)'.format(format_amt(py_booked_amt), py_booked_percentage))
  print('===================')
  print('Est FTT: ',  format_amt(estimate_st))
  print('Est FTT PnL: '+ '{} ({}%)'.format(format_amt(est_st_pnl_amount), est_st_pnl_percentage))

  print('===================')
  print('Deployed: ', format_amt(investment))

  print('Current: ', format_amt(current))

  print('CAGR/XIRR %: '+'{}%'.format(cagr))

In [8]:
# get start and end date
start_date, end_date = get_start_end_date()

# get portfolio and prospects data
mypfs_df = get_mypfs_df()
mypps_df = get_mypps_df()
myinvmt_df = get_myinvmt_df()

# merge above datasets
mypf_df = pd.merge(mypfs_df, mypps_df, on="Symbol")

# seggregate dm and sv portfolio
dm_pf = mypf_df[mypf_df['InPortfolio'] == 'DM']
sv_pf = mypf_df[mypf_df['InPortfolio'] == 'SV']

# build portfolio stock dataframe
dm_stocks = get_stock_ids(dm_pf)
sv_stocks = get_stock_ids(sv_pf)
df_stocks = pd.concat([dm_pf,sv_pf], ignore_index = True)

# arrange common and diff stock features
common_cols = ['Symbol', 'Target', 'Criteria', 'Strategy', 'CumlRnk', 'LatestQtr', 'StarStock', 'Conviction', 'Category', 'InFolio', 'XIRR', 'MBQ']
diff_cols = ['Symbol', 'AvgCost', 'Shares']
df_stocks = arrange_features(df_stocks, common_cols, diff_cols)

# get common features
stock_ids = df_stocks['Symbol'].values
df_common_features = get_common_features(stock_ids, df_stocks)

df_common_features.reset_index(drop=True, inplace=True)
df_common_features.drop(['Date'], axis=1, inplace=True)
# get and print portfolio features
df_portfolio_features = get_portfolio_features(df_common_features)

print_portfolio_stats(df_portfolio_features, myinvmt_df)

df = df_portfolio_features
#plot_pie_chart(df, 'CapType', 'Current')
list_ox40n = list(df[df['MBQ'].str.contains('OX40N', na=False)]['Symbol'].values)

Run date time (IST): 2026-04-27 13:24:30
-------------------
qualified stocks: 92
with latest results: 31
still star stocks: 20

-------------------
Initial Investment:  1.40 C
CY Investment:  1.82 C
Reserve:  1.49 K
Current:  1.50 C
-------------------
Today PnL: 2.97 L (2.03%)
Current PnL: -33.50 L (-18.37%)
CY Booked + Current PnL: -31.42 L (-17.23%)
-------------------
Total profit:  1.38 L
Total loss:  -34.88 L
-------------------
Total Booked + Current PnL: 11.45 L (8.21%)
Total Booked PnL: 44.95 L (32.22%)
Curr Year Booked PnL: 2.08 L (1.39%)
Prev Year Booked PnL: 42.87 L (30.73%)
===================
Est FTT:  2.56 C
Est FTT PnL: 1.06 C (70.71%)
===================
Deployed:  1.40 C
Current:  1.50 C
CAGR/XIRR %: 3.52%

In [9]:
# top 5 near their targets
cols = ['Symbol', 'Today P/L%', 'Current P/L%', 'FTT%', 'OTT%', 'FTT Amt', 'Current P/L', 'Current', 'FTT', 'Dev%_PE', 'RSI_14','Conviction', 'Spread%',  'CumlRnk', 'RRR Ind', 'CurrAlloc%', 'Gained%', 'Criteria', 'Strategy', 'Category']
df_tmp = df_portfolio_features[~df_portfolio_features['Symbol'].isin(['ENRIN','BLUSPRING','DIGITIDE'])]
df_tmp = df_tmp.sort_values(by = 'FTT Amt', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
55,MASFIN,0.87,-1.06,22.87,21.57,22171.0,-1035.0,96945.0,397.04,-14.63,60.0,H-SC,1.74,167.0,-0.05,0.65,25.28,XR,ATH,FINANCE
59,PIDILITIND,0.26,-0.94,19.48,18.37,27231.0,-1320.0,139790.0,1670.26,-30.66,55.0,X-LC,8.04,5.0,-0.05,0.93,9.76,X40,ATH,CHEMICALS
51,KOTAKBANK,1.70,0.78,20.17,21.11,28146.0,1074.0,139546.0,453.24,-13.74,50.0,X-LC,9.63,12.0,0.04,0.93,6.72,X40,ATH,BANKS
53,M&M,2.33,0.89,22.30,23.38,31201.0,1233.0,139914.0,3802.40,-14.43,47.0,X-LC,9.01,25.0,0.04,0.93,7.72,X40N,ATH,AUTO
83,TTKPRESTIG,1.00,-31.70,46.54,0.09,32035.0,-31943.0,68834.0,770.00,59.87,63.0,M-SC,20.81,250.0,-1.00,0.46,22.57,OX40N,NTT,DURABLES

In [10]:
# top 5 today
df_tmp = df_portfolio_features.sort_values(by = 'Today P/L%', ascending=False)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
77,TANLA,17.87,-35.29,239.49,119.69,419625.0,-95545.0,175216.0,1943.92,-34.70,75.0,H-SC,19.90,147.0,-0.23,1.17,51.70,AR,ATH,IT
76,SYMPHONY,8.03,-34.28,52.12,-0.03,58619.0,-58671.0,112470.0,1306.00,-47.22,65.0,M-SC,15.15,205.0,-1.00,0.75,24.73,OX40N,NTT,DURABLES
67,ROUTE,7.81,-59.28,312.98,68.16,169576.0,-78885.0,54181.0,2215.45,-67.06,63.0,H-SC,30.36,141.0,-0.47,0.36,29.08,SR,ATH,IT
70,SHALBY,6.82,-36.41,96.73,25.10,111423.0,-65953.0,115190.0,327.00,746.89,63.0,M-SC,23.02,236.0,-0.59,0.77,31.09,XY24,NTT,HEALTHCARE
86,VALIANTORG,6.59,-43.62,208.89,74.15,192678.0,-71366.0,92239.0,838.00,-265.94,57.0,H-SC,17.91,145.0,-0.37,0.62,37.26,XR,NTT,CHEMICALS

In [11]:
# bottom 5 today
df_tmp = df_portfolio_features.sort_values(by = 'Today P/L%', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
27,GLAXO,-1.29,-2.05,42.06,39.15,82101.0,-4084.0,195200.0,3466.20,-25.17,53.0,X-MC,9.32,56.0,-0.05,1.30,7.99,X40,ATH,PHARMA
5,ATULAUTO,-0.76,-14.65,70.56,45.57,118716.0,-28883.0,168249.0,844.00,3645.95,65.0,M-SC,2.75,248.0,-0.24,1.12,29.47,XY24,NTT,AUTO
10,BATAINDIA,-0.33,-52.59,185.17,35.20,112963.0,-67665.0,61005.0,2096.00,-20.00,53.0,X-SC,28.72,91.0,-0.60,0.41,20.99,X40,NTT,FOOTWEAR
58,PGHH,0.11,-22.73,70.85,32.01,116891.0,-48536.0,164984.0,17616.87,-47.80,55.0,X-MC,19.78,57.0,-0.42,1.10,12.84,X40,ATH,FMCG
16,CERA,0.18,-30.20,77.50,23.89,95150.0,-53129.0,122774.0,9475.00,-32.70,62.0,H-SC,12.69,153.0,-0.56,0.82,17.99,OX40N,NTT,CERAMICS

In [12]:
# top 5 to exit based on CumlRnk
df_tmp = df_portfolio_features[~df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])]
df_tmp = df_tmp[(df_tmp['Current P/L%'] > -1) & (df_tmp['Current P/L%'] < 1)].sort_values(by = 'CumlRnk', ascending=False)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
74,STARHEALTH,0.65,-0.15,47.48,47.26,133278.0,-419.0,280704.0,761.00,57.63,71.0,H-SC,4.79,173.0,-0.0,1.88,45.37,XY24,NTT,INSURANCE
91,ZYDUSLIFE,2.19,-0.06,35.71,35.63,74792.0,-132.0,209442.0,1286.17,-13.06,61.0,H-MC,4.05,120.0,-0.0,1.40,10.12,AR,ATH,PHARMA

In [13]:
# OX40N stocks to exit
df_tmp = df_portfolio_features[(df_portfolio_features['Symbol'].isin(list_ox40n))].sort_values(by = 'Current P/L%', ascending=False)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
25,FINCABLES,3.99,28.11,62.29,107.91,117822.0,41506.0,189150.0,1641.55,15.17,74.0,M-SC,6.83,220.0,0.35,1.26,42.30,OX40N,ATH,CABLES
72,SIS,1.19,-21.98,55.43,21.26,48016.0,-24408.0,86624.0,528.00,2046.63,72.0,H-SC,8.37,168.0,-0.51,0.58,28.80,OX40N,NTT,MISC
16,CERA,0.18,-30.20,77.50,23.89,95150.0,-53129.0,122774.0,9475.00,-32.70,62.0,H-SC,12.69,153.0,-0.56,0.82,17.99,OX40N,NTT,CERAMICS
83,TTKPRESTIG,1.00,-31.70,46.54,0.09,32035.0,-31943.0,68834.0,770.00,59.87,63.0,M-SC,20.81,250.0,-1.00,0.46,22.57,OX40N,NTT,DURABLES
50,KANSAINER,1.36,-33.31,70.14,13.47,126145.0,-89820.0,179847.0,340.00,-42.69,58.0,H-SC,16.54,162.0,-0.71,1.20,25.62,XY24,NTT,PAINTS

In [14]:
# top 5 to book for rotation
df_tmp = df_portfolio_features[(df_portfolio_features['Current P/L%'] > 20) ].sort_values(by = 'CumlRnk', ascending=False)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
25,FINCABLES,3.99,28.11,62.29,107.91,117822.0,41506.0,189150.0,1641.55,15.17,74.0,M-SC,6.83,220.0,0.35,1.26,42.3,OX40N,ATH,CABLES

In [15]:
# top 5 to monitor for exit
df_tmp = df_portfolio_features[~df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])]
df_tmp = df_tmp[(df_tmp['Current P/L%'] > 0) ].sort_values(by = 'Dev%_PE', ascending=False)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
25,FINCABLES,3.99,28.11,62.29,107.91,117822.0,41506.0,189150.0,1641.55,15.17,74.0,M-SC,6.83,220.0,0.35,1.26,42.30,OX40N,ATH,CABLES
63,RECLTD,0.84,2.10,18.26,20.74,37877.0,4262.0,207432.0,446.00,13.28,65.0,M-MC,3.59,191.0,0.11,1.39,23.62,XY25,NTT,FINANCE
73,SONACOMS,3.53,1.17,37.49,39.09,38367.0,1181.0,102340.0,804.02,-19.79,62.0,M-MC,13.42,193.0,0.03,0.68,44.77,AR,ATH,AUTO

In [16]:
# top 5 to book for rotation from weak conviction
df_tmp = df_portfolio_features[~df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])]
df_tmp = df_tmp[~df_tmp['Criteria'].isin(['XY25','XY24','X40', 'X40N'])].sort_values(by = 'RRR Ind', ascending=False)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
25,FINCABLES,3.99,28.11,62.29,107.91,117822.0,41506.0,189150.0,1641.55,15.17,74.0,M-SC,6.83,220.0,0.35,1.26,42.30,OX40N,ATH,CABLES
73,SONACOMS,3.53,1.17,37.49,39.09,38367.0,1181.0,102340.0,804.02,-19.79,62.0,M-MC,13.42,193.0,0.03,0.68,44.77,AR,ATH,AUTO
91,ZYDUSLIFE,2.19,-0.06,35.71,35.63,74792.0,-132.0,209442.0,1286.17,-13.06,61.0,H-MC,4.05,120.0,-0.00,1.40,10.12,AR,ATH,PHARMA
55,MASFIN,0.87,-1.06,22.87,21.57,22171.0,-1035.0,96945.0,397.04,-14.63,60.0,H-SC,1.74,167.0,-0.05,0.65,25.28,XR,ATH,FINANCE
42,INDIAMART,1.43,-8.16,125.09,106.72,141692.0,-10064.0,113272.0,4810.62,-58.59,54.0,H-SC,10.30,140.0,-0.07,0.76,8.82,AR,ATH,MISC

In [17]:
# top 5 to accumulate based on lowest RSI_14
df_tmp = df_portfolio_features[df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])].sort_values(by = 'RSI_14', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
45,INFY,1.56,-20.17,68.17,34.24,170264.0,-63124.0,249764.0,1972.00,-37.23,31.0,X-LC,12.97,3.0,-0.37,1.67,1.56,X40,NTT,IT
33,HCLTECH,1.47,-20.77,53.36,21.51,102281.0,-50243.0,191681.0,1872.35,-16.87,31.0,X-LC,7.98,8.0,-0.49,1.28,1.47,X40,ATH,IT
40,ICICIPRULI,0.93,-14.12,52.22,30.73,88353.0,-27811.0,169194.0,790.00,-37.19,35.0,X-MC,13.13,78.0,-0.31,1.13,3.10,X40,ATH,INSURANCE
1,ABBOTINDIA,1.19,-14.52,38.13,18.07,58293.0,-25975.0,152880.0,35195.00,-27.31,42.0,X-MC,11.94,58.0,-0.45,1.02,1.19,X40,ATH,PHARMA
35,HDFCLIFE,1.61,-2.25,36.24,33.18,53068.0,-3364.0,146436.0,814.30,-23.63,43.0,X-LC,17.73,31.0,-0.06,0.98,5.58,X40,ATH,INSURANCE

In [18]:
# top 5 to accumulate based on Spread and CumlRnk
df_tmp = df_portfolio_features[df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])]
df_tmp = df_tmp[(df_tmp['CumlRnk'] < 100)].sort_values(by = 'Spread%', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
88,VOLTAS,4.02,19.14,21.87,45.20,49959.0,36693.0,228435.0,1856.00,36.45,66.0,X-MC,4.60,79.0,0.73,1.53,27.23,XY25,NTT,AC
84,UNITDSPR,0.25,2.51,17.82,20.77,42770.0,5865.0,240009.0,1644.00,-9.09,64.0,X-MC,4.77,64.0,0.14,1.60,14.49,X40N,NTT,BREWERIES
87,VBL,3.09,2.13,32.67,35.50,105385.0,6731.0,322573.0,670.80,-9.85,72.0,X-LC,6.20,13.0,0.06,2.16,32.45,X40N,ATH,FMCG
65,RELIANCE,1.64,-13.37,44.64,25.30,77717.0,-26865.0,174098.0,1952.00,-15.80,48.0,X-LC,6.24,21.0,-0.35,1.16,3.45,XY25,BTT,REFINERIES
39,ICICIGI,0.62,-5.55,26.36,19.34,49820.0,-11111.0,188998.0,2252.93,-20.57,45.0,X-MC,6.44,66.0,-0.22,1.26,5.56,X40,ATH,INSURANCE

In [19]:
# top 5 to accumulate based on lowest Gained%
df_tmp = df_portfolio_features[df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])].sort_values(by = 'Gained%', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
1,ABBOTINDIA,1.19,-14.52,38.13,18.07,58293.0,-25975.0,152880.0,35195.00,-27.31,42.0,X-MC,11.94,58.0,-0.45,1.02,1.19,X40,ATH,PHARMA
33,HCLTECH,1.47,-20.77,53.36,21.51,102281.0,-50243.0,191681.0,1872.35,-16.87,31.0,X-LC,7.98,8.0,-0.49,1.28,1.47,X40,ATH,IT
45,INFY,1.56,-20.17,68.17,34.24,170264.0,-63124.0,249764.0,1972.00,-37.23,31.0,X-LC,12.97,3.0,-0.37,1.67,1.56,X40,NTT,IT
40,ICICIPRULI,0.93,-14.12,52.22,30.73,88353.0,-27811.0,169194.0,790.00,-37.19,35.0,X-MC,13.13,78.0,-0.31,1.13,3.10,X40,ATH,INSURANCE
65,RELIANCE,1.64,-13.37,44.64,25.30,77717.0,-26865.0,174098.0,1952.00,-15.80,48.0,X-LC,6.24,21.0,-0.35,1.16,3.45,XY25,BTT,REFINERIES

In [20]:
# top 5 to accumulate based on lowest CurrAlloc%
df_tmp = df_portfolio_features[df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])].sort_values(by = 'CurrAlloc%', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
64,RELAXO,2.43,-60.04,281.17,52.31,163084.0,-87158.0,58002.0,1176.00,-57.51,56.0,X-SC,29.07,92.0,-0.53,0.39,29.68,X40N,NTT,FOOTWEAR
10,BATAINDIA,-0.33,-52.59,185.17,35.20,112963.0,-67665.0,61005.0,2096.00,-20.00,53.0,X-SC,28.72,91.0,-0.60,0.41,20.99,X40,NTT,FOOTWEAR
60,QUESS,1.38,-20.94,119.96,73.90,101281.0,-22364.0,84429.0,424.00,-57.58,54.0,X-SC,17.05,80.0,-0.22,0.56,13.58,XY24,NTT,MISC
53,M&M,2.33,0.89,22.30,23.38,31201.0,1233.0,139914.0,3802.40,-14.43,47.0,X-LC,9.01,25.0,0.04,0.93,7.72,X40N,ATH,AUTO
51,KOTAKBANK,1.70,0.78,20.17,21.11,28146.0,1074.0,139546.0,453.24,-13.74,50.0,X-LC,9.63,12.0,0.04,0.93,6.72,X40,ATH,BANKS

In [21]:
# top 5 to accumulate based on CumlRnk
df_tmp = df_portfolio_features.sort_values(by = 'CumlRnk', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
47,ITC,0.78,-19.94,48.71,19.06,132656.0,-67827.0,272339.0,452.00,-55.92,50.0,X-LC,18.15,1.0,-0.51,1.82,5.65,X40,NTT,FMCG
79,TCS,2.00,-28.23,76.36,26.57,253892.0,-130780.0,332493.0,4311.58,-39.36,43.0,X-LC,14.99,2.0,-0.52,2.22,3.77,X40,ATH,IT
45,INFY,1.56,-20.17,68.17,34.24,170264.0,-63124.0,249764.0,1972.00,-37.23,31.0,X-LC,12.97,3.0,-0.37,1.67,1.56,X40,NTT,IT
81,TMPV,1.00,-19.42,69.49,36.58,199256.0,-69101.0,286740.0,600.00,-83.62,58.0,X-LC,6.94,4.0,-0.35,1.92,19.51,XY24,NTT,AUTO
59,PIDILITIND,0.26,-0.94,19.48,18.37,27231.0,-1320.0,139790.0,1670.26,-30.66,55.0,X-LC,8.04,5.0,-0.05,0.93,9.76,X40,ATH,CHEMICALS

In [22]:
# top 5 for average up
df_tmp = df_portfolio_features[(df_portfolio_features['Dev%_200'] > 5)].sort_values(by = 'CurrAlloc%', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
44,INDUSINDBK,5.24,-34.12,101.70,32.89,51732.0,-26340.0,50867.0,1800.00,-339.50,61.0,L-MC,4.88,258.0,-0.51,0.34,25.21,XR,NTT,BANKS
73,SONACOMS,3.53,1.17,37.49,39.09,38367.0,1181.0,102340.0,804.02,-19.79,62.0,M-MC,13.42,193.0,0.03,0.68,44.77,AR,ATH,AUTO
75,SURYODAY,2.96,-14.84,44.48,23.03,67828.0,-26581.0,152490.0,216.00,66.67,66.0,H-SC,4.17,166.0,-0.39,1.02,30.05,XR,NTT,BANKS
5,ATULAUTO,-0.76,-14.65,70.56,45.57,118716.0,-28883.0,168249.0,844.00,3645.95,65.0,M-SC,2.75,248.0,-0.24,1.12,29.47,XY24,NTT,AUTO
25,FINCABLES,3.99,28.11,62.29,107.91,117822.0,41506.0,189150.0,1641.55,15.17,74.0,M-SC,6.83,220.0,0.35,1.26,42.30,OX40N,ATH,CABLES

In [23]:
# top 5 RSP
df_tmp = df_portfolio_features.sort_values(by = 'RSP', ascending=False)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
61,RAJESHEXPO,2.09,-74.99,300.12,0.07,102962.0,-102870.0,34307.0,518.00,1157.58,62.0,L-SC,36.72,268.0,-1.00,0.23,61.06,OX40N,NTT,JEWELLERY
77,TANLA,17.87,-35.29,239.49,119.69,419625.0,-95545.0,175216.0,1943.92,-34.70,75.0,H-SC,19.90,147.0,-0.23,1.17,51.70,AR,ATH,IT
62,RAJOOENG,0.83,-30.09,99.69,39.61,71438.0,-30840.0,71660.0,143.10,-52.76,68.0,H-SC,24.59,136.0,-0.43,0.48,53.51,AR,ATH,MISC
80,TITAGARH,4.35,-25.66,96.05,45.74,172918.0,-62148.0,180029.0,1548.00,-0.87,71.0,H-SC,15.13,175.0,-0.36,1.20,37.36,XY24,NTT,ENGINEERING
87,VBL,3.09,2.13,32.67,35.50,105385.0,6731.0,322573.0,670.80,-9.85,72.0,X-LC,6.20,13.0,0.06,2.16,32.45,X40N,ATH,FMCG

In [24]:
# Top N allocation
df_tmp = df_portfolio_features.sort_values(by = 'CurrAlloc%', ascending=False)
top_n_values = [10, 25, 50]

sum_df = pd.DataFrame({
    'Top_N': top_n_values,
    'Sum_Alloc%': [df_tmp['CurrAlloc%'].head(n).sum() for n in top_n_values]
})

sum_df

   Top_N  Sum_Alloc%
0     10       18.86
1     25       42.58
2     50       72.74

In [25]:
# market-cap-wise allocation
df_tmp = df_portfolio_features[cols]
df_tmp.groupby(df_tmp['Conviction'].str[-2:])['CurrAlloc%'].sum().sort_values(ascending=False)

Conviction
SC    42.04
LC    31.67
MC    26.25
Name: CurrAlloc%, dtype: float64

In [26]:
# criteria-wise allocation
df_portfolio_features.groupby('Criteria')['CurrAlloc%'].sum().sort_values(ascending=False)

Criteria
XY24     26.62
X40      25.61
X40N     17.07
XR        8.99
XY25      7.10
AR        6.95
OX40N     6.82
SR        0.80
Name: CurrAlloc%, dtype: float64

In [27]:
# conviction-wise allocation
df_portfolio_features.groupby('Conviction')['CurrAlloc%'].sum().sort_values(ascending=False)

Conviction
X-LC    29.43
H-SC    21.69
X-MC    21.25
M-SC    10.00
X-SC     9.78
H-MC     2.59
M-MC     2.07
H-LC     1.29
M-LC     0.95
L-SC     0.57
L-MC     0.34
Name: CurrAlloc%, dtype: float64

In [28]:
# sector-wise stats
df_tmp = df_portfolio_features.groupby('Category')[['CurrAlloc%', 'Current', 'Current P/L', 'FTT Amt']].sum().sort_values(by=['Current', 'Current P/L'], ascending=False)
df_tmp['Current P/L%'] = round(df_tmp['Current P/L'] * 100 / df_tmp['Current'], 2)
df_tmp['FTT%'] = round(df_tmp['FTT Amt'] * 100 / df_tmp['Current'], 2)
cols = ['CurrAlloc%', 'Current P/L%', 'FTT%']
df_tmp[cols].sort_values(by=['CurrAlloc%'], ascending=False)

               CurrAlloc%  Current P/L%    FTT%
Category
FMCG                15.70        -12.67   52.44
FINANCE             10.79        -14.18   63.84
IT                  10.65        -41.34  112.91
MISC                 6.82        -31.53   88.66
AUTO                 6.63        -10.15   51.45
BANKS                5.38        -12.73   64.85
INSURANCE            5.25         -5.44   41.32
PAINTS               5.09        -29.13   51.56
PHARMA               4.81         -2.79   35.82
ELECTRICAL           4.14        -13.86   54.39
AC                   2.05         -4.14   32.38
CHEMICALS            1.99        -35.97  117.01
HEALTHCARE           1.93        -23.78   56.09
DURABLES             1.82        -42.00   76.55
APPARELS             1.77         -1.56   36.21
FOOTWEAR             1.75        -68.82  136.51
TRAVEL               1.70        -75.56  163.47
BREWERIES            1.60          2.44   17.82
REALTY               1.44         -3.11   20.05
CERAMICS             1.29        -58.84  107.10
CABLES               1.26         21.94   62.29
ENGINEERING          1.20        -34.52   96.05
CEMENT               1.17        -53.67  168.64
REFINERIES           1.16        -15.43   44.64
JEWELLERY            1.06       -101.33  171.27
ENTERTAINMENT        0.74        -73.28  176.63
TEXTILES             0.43        -42.56   83.21
HOTELS               0.34       -123.09  201.77

In [29]:
# money to be made criteria-wise
df_portfolio_features.groupby('Criteria')['FTT Amt'].agg(['sum', 'count']).sort_values(by='sum', ascending=False)

                sum  count
Criteria
XY24      3610245.0     21
X40       1867355.0     19
XR        1336569.0     13
X40N      1171201.0     13
AR        1149915.0      9
OX40N      770681.0     10
XY25       378684.0      5
SR         298752.0      2

In [30]:
# money to be made conviction-wise
df_portfolio_features.groupby('Conviction')['FTT Amt'].agg(['sum', 'count']).sort_values(by='sum', ascending=False)

                  sum  count
Conviction
H-SC        3547602.0     24
X-LC        1891417.0     21
X-MC        1551609.0     15
M-SC        1417734.0     14
X-SC        1341104.0      9
H-MC         310494.0      2
L-SC         205661.0      2
M-LC         149476.0      1
M-MC          76244.0      2
L-MC          51732.0      1
H-LC          40329.0      1

In [31]:
# money to be made criteria and conviction-wise
df_portfolio_features.groupby(['Conviction', 'Criteria'])['FTT Amt'].agg(['sum', 'count']).sort_values(by='sum', ascending=False)

                           sum  count
Conviction Criteria
H-SC       XY24      1167787.0      6
X-LC       X40       1014314.0     10
H-SC       AR         921371.0      5
M-SC       XY24       846577.0      6
H-SC       XR         816411.0      7
X-SC       XY24       786855.0      4
X-MC       X40        655721.0      7
           X40N       452744.0      4
X-LC       X40N       361528.0      6
X-SC       X40N       356929.0      3
H-SC       OX40N      343281.0      4
X-LC       XY24       334980.0      2
M-SC       OX40N      324438.0      5
H-SC       SR         298752.0      2
X-MC       XY24       238344.0      2
H-MC       XY24       235702.0      1
X-MC       XY25       204800.0      2
X-SC       X40        197320.0      2
M-SC       XR         171663.0      2
M-LC       XR         149476.0      1
X-LC       XY25       136007.0      2
L-SC       OX40N      102962.0      1
           XR         102699.0      1
M-SC       AR          75056.0      1
H-MC       AR          74792.0      1
L-MC       XR          51732.0      1
X-LC       XR          44588.0      1
H-LC       AR          40329.0      1
M-MC       AR          38367.0      1
           XY25        37877.0      1

In [32]:
# notebook execution time

end_time = time.time()
execution_time = round(end_time - start_time, 0)
print(f"Notebook execution time: {execution_time} seconds")

Notebook execution time: 38.0 seconds