<a href="https://colab.research.google.com/github/ankit-rathi/Quantvesting_v2/blob/main/myStocks_Portfolio_Analysis.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
'''
!pip install pandas==2.2.2 -qq
!pip install pyxirr -qq
!pip install ta -qq
!pip install yfinance==0.2.59 -qq
'''

'\n!pip install pandas==2.2.2 -qq\n!pip install pyxirr -qq\n!pip install ta -qq\n!pip install yfinance==0.2.59 -qq\n'

In [2]:
# import libraries

import numpy as np
import pandas as pd
import datetime
import warnings
warnings.filterwarnings('ignore')
import yfinance as yfin
import ta
import matplotlib.pyplot as plt
import requests

In [3]:
# notebook start time
import time
import datetime
import pytz

start_time = time.time()

# function to print date timestamp
def print_date_time():
  tz_NY = pytz.timezone('Asia/Kolkata')
  datetime_NY = datetime.datetime.now(tz_NY)
  print("Run date time (IST):", datetime_NY.strftime("%Y-%m-%d %H:%M:%S"))

In [4]:
# function to get booked and reserved amount
def get_amt():
  # fetch the JSON data from the URL
  url = "https://raw.githubusercontent.com/ankit-rathi/Tradevesting_v1/main/data/myPortfolioAmts.json"
  response = requests.get(url)
  pf_amts = response.json()  # parse the JSON data

  # extract values from the JSON
  py_booked_amt_dm = pf_amts["py_booked_amt_dm"]
  py_booked_amt_sv = pf_amts["py_booked_amt_sv"]
  cy_booked_amt_dm = pf_amts["cy_booked_amt_dm"]
  cy_booked_amt_sv = pf_amts["cy_booked_amt_sv"]
  reserve_amt_dm = pf_amts["reserve_amt_dm"]
  reserve_amt_sv = pf_amts["reserve_amt_sv"]

  # perform calculations
  py_booked_amt = py_booked_amt_dm + py_booked_amt_sv
  cy_booked_amt = cy_booked_amt_dm + cy_booked_amt_sv
  reserve_amt = reserve_amt_dm + reserve_amt_sv
  total_booked_amt = py_booked_amt + cy_booked_amt

  return total_booked_amt, reserve_amt, cy_booked_amt, py_booked_amt

gen_output = 0

In [5]:
# function to format the amount
def format_amt(number):
    abs_number = abs(number)

    if abs_number >= 1_00_00_000:  # Crores
        formatted_amt = f"{number / 1_00_00_000:.2f} C"
    elif abs_number >= 1_00_000:  # Lakhs
        formatted_amt = f"{number / 1_00_000:.2f} L"
    elif abs_number >= 1_000:  # Thousands
        formatted_amt = f"{number / 1_000:.2f} K"
    else:
        formatted_amt = f"{number:.2f}"

    return formatted_amt

# function to set start and end date
def get_start_end_date():
  start_date = (datetime.date.today() + datetime.timedelta(days=-365)).strftime('%Y-%m-%d')
  end_date = (datetime.date.today() + datetime.timedelta(days=1)).strftime('%Y-%m-%d')
  return start_date, end_date

# function to fetch my portfolio csv
def get_mypfs_df():
  mypfs_df = pd.read_csv('https://raw.githubusercontent.com/ankit-rathi/Tradevesting_v1/main/data/myPortfolioStocks.csv')
  return mypfs_df

# function to fetch my prospects csv
def get_mypps_df():
  mypps_df = pd.read_csv('https://raw.githubusercontent.com/ankit-rathi/Tradevesting_v1/main/data/myProspectsScrips.csv')
  return mypps_df

# function to fetch screener data
def get_myscreen_df():
  myscreen_df = pd.read_csv('https://raw.githubusercontent.com/ankit-rathi/Tradevesting_v1/main/data/myScreenerDB.csv')
  return myscreen_df

# function to fetch momentum data
def get_myinvmt_df():
  myinvmt_df = pd.read_csv('https://raw.githubusercontent.com/ankit-rathi/Tradevesting_v1/main/data/myInvestments.csv')
  return myinvmt_df

# function to get the stock ids
def get_stock_ids(df_pf):
  stock_n100 = df_pf['Symbol'].unique()

  exclude = ['CADILAHC','MMTC', 'MASFIN']

  stock_ids = df_pf[~df_pf['Symbol'].isin(exclude) ]['Symbol'].unique()

  #mypf = mypf[mypf.Forecast.notnull()]
  #stock_ids = mypf['Symbol'].unique()

  #stock_ids.sort()
  return stock_ids

# get features from screener data
def get_screener_features():
  myscreen_df = get_myscreen_df()
  cols = ['Symbol', 'EPS', 'MedPE', 'ROCE%', 'ROE%', 'CapType']
  return myscreen_df[cols]

# get relative strength
def get_relative_strength(stock_list):

    # Dictionary to store stock tickers and their corresponding percentage price change
    stock_changes = {}

    # Loop through each stock and fetch its price data
    for stock in stock_list:
        try:
            # Download the stock data for the given date range
            stock_data = yfin.Ticker(stock + '.NS').history(period='1mo', interval='1d')[map(str.title, ['open', 'close', 'low', 'high', 'volume'])]

            # Calculate the percentage change for the stock
            if len(stock_data) > 0:
                start_price = stock_data['Close'].iloc[0]
                end_price = stock_data['Close'].iloc[-1]
                percent_change = round(((end_price - start_price) / start_price) * 100, 2)
                stock_changes[stock] = percent_change
            else:
                stock_changes[stock] = np.nan  # If no data is available, set to NaN

        except Exception as e:
            print(f"Error fetching data for {stock}: {e}")
            stock_changes[stock] = np.nan

    # Create a DataFrame with stock tickers and their percentage changes
    df = pd.DataFrame(list(stock_changes.items()), columns=['Symbol', 'Percent_Change'])

    # Drop any stocks with missing data (NaN values)
    df = df.dropna()

    # Calculate the percentile rank based on percentage change
    df['RSP'] = round(df['Percent_Change'].rank(pct=True) * 100, 2)
    cols = ['Symbol', 'RSP']
    df = df[cols]
    # Sort by percentile rank (optional)
    df = df.sort_values(by='RSP', ascending=False).reset_index(drop=True)

    return df

In [6]:
# function to get stock technicals
def stock_prec_dev(stock_symbol):
    #stock_symbol = 'ULTRACEMCO.NS'
    short_window = 20
    mid_window = 50
    long_window = 200
    moving_avg = 'SMA'

    start = datetime.datetime(*map(int, start_date.split('-')))
    end = datetime.datetime(*map(int, end_date.split('-')))

    stock_df = yfin.Ticker(stock_symbol + '.NS').history(period='max', interval='1d')[map(str.title, ['open', 'close', 'low', 'high', 'volume'])]

    stock_df['Max'] = round(max(stock_df['Close']),2)
    stock_df = stock_df[(stock_df.index <= end_date) & (stock_df.index >= start_date)]
    stock_df['200_SMA'] = round(stock_df['Close'].rolling(window = 200, min_periods = 1).mean(),0)
    stock_df['Dev%_200'] = round((stock_df['Close'] - stock_df['200_SMA'])*100/stock_df['200_SMA'],2)
    stock_df.dropna(axis = 0, inplace = True) # remove any null rows

    stock_df['20_SMA'] = stock_df['Close'].rolling(window=20).mean()
    stock_df['50_SMA'] = stock_df['Close'].rolling(window=50).mean()
    stock_df['Symbol'] = stock_symbol

    stock_df['Close'] = round(stock_df['Close'],2)
    stock_df['Min'] = round(min(stock_df['Close']),2)
    stock_df['RSI_14'] = ta.momentum.RSIIndicator(close=stock_df['Close'], window=14).rsi()
    stock_df['RSI_14'] = round(stock_df['RSI_14'],0)
    stock_df['Prev_Close'] = stock_df['Close'].shift(1)
    stock_df.drop(['Open', 'Low', 'High', 'Volume'], axis=1, inplace=True)
    stock_df = stock_df.tail(1)

    max_SMA = max(stock_df['20_SMA'].item(), stock_df['50_SMA'].item(), stock_df['200_SMA'].item())
    min_SMA = min(stock_df['20_SMA'].item(), stock_df['50_SMA'].item(), stock_df['200_SMA'].item())
    ABS_Spread = max_SMA - min_SMA
    stock_df['Spread%'] = round((ABS_Spread / stock_df['200_SMA'].item()) * 100,2)

    return stock_df

# function to compute stock attributes
def get_common_features(stock_ids, df_mypf):

  df_prec_dev = pd.DataFrame()
  df_tmp = get_screener_features()
  df_rs = get_relative_strength(stock_ids)

  for stock_id in stock_ids:
      tmp = stock_prec_dev(stock_id)
      tmp = tmp.reset_index()
      df_prec_dev = pd.concat([df_prec_dev, tmp], ignore_index = True)
  df_prec_dev = pd.merge(df_prec_dev, df_mypf, on= 'Symbol')
  df_prec_dev = pd.merge(df_prec_dev, df_tmp, on= 'Symbol', how='left')
  df_prec_dev = pd.merge(df_prec_dev, df_rs, on= 'Symbol', how='left')
  #print(df_prec_dev.columns)
  df_prec_dev['Curr_PE'] = round(df_prec_dev['Close']/df_prec_dev['EPS'],1)
  df_prec_dev['Dev%_PE'] = round((df_prec_dev['Curr_PE'] - df_prec_dev['MedPE'])*100/df_prec_dev['MedPE'],2)
  df_prec_dev['Conviction'] = df_prec_dev['Conviction'] + '-' + df_prec_dev['CapType']
  return df_prec_dev

# function to arrange stock features
def arrange_features(df_stocks, common_cols, diff_cols):
  df_stocks_common = df_stocks[common_cols].drop_duplicates()
  df_stocks_diff = df_stocks[diff_cols]
  df_stocks_diff['Investment'] = df_stocks_diff['AvgCost'] * df_stocks_diff['Shares']
  df_stocks_diff = df_stocks_diff.groupby(['Symbol'])[['Shares', 'Investment']].aggregate(['sum']).reset_index()
  df_stocks_diff.columns = ['Symbol', 'Shares', 'Investment']
  df_stocks_diff['AvgCost'] = round(df_stocks_diff['Investment']/df_stocks_diff['Shares'],2)
  df_stocks = pd.merge(df_stocks_diff, df_stocks_common, on='Symbol')
  return df_stocks

# plot fact distribution across dimension
def plot_pie_chart(df, dimension, fact):
  # grouping the data by category and calculating the sum of fact for each type
  grouped_data = df.groupby(dimension)[fact].sum()

  # sorting the grouped data in descending order
  grouped_data = grouped_data.sort_values(ascending=False)

  # creating a pie chart
  grouped_data.plot.pie(autopct='%1.1f%%', startangle=90, figsize=(6, 6))

  # adding a title and displaying the plot
  plt.title(f'{dimension} {fact} Distribution')
  plt.ylabel('')  # To hide the y-label
  plt.show()

In [7]:
# function to get portfolio features

def get_portfolio_features(df_common_features):

  print_date_time()
  print('=================== PORTFOLIO QUALITY ====================')

  #df_common_features["Target"] = df_common_features["Target"].fillna(df_common_features["Max"])
  df_common_features['NTT'] = np.where(df_common_features['Strategy']== 'NTT', df_common_features["Target"], df_common_features['Max'])
  df_common_features['LTT'] = np.where(df_common_features['Strategy']== 'BTT', df_common_features["Target"], df_common_features['Max'])
  df_common_features['BOL'] = df_common_features['Min']

  tmp_df = df_common_features[df_common_features['Symbol'].isin(mypf_df[mypf_df['InPortfolio'] != 'NA'].Symbol.values)]
  print('qualified stocks: '+str(len(tmp_df['Symbol'].unique())))
  tmp_df1 = tmp_df[tmp_df['LatestQtr'] == 1]
  print('with latest results: '+str(len(tmp_df1['Symbol'].unique())))
  tmp_df1 = tmp_df1[tmp_df1['StarStock'] == 1]
  print('still star stocks: '+str(len(tmp_df1['Symbol'].unique())))
  tmp_df['Investment'] = tmp_df['AvgCost'] * tmp_df['Shares']
  tmp_df['Current'] = round(tmp_df['Close'] * tmp_df['Shares'],0)
  tmp_df['Previous'] = tmp_df['Prev_Close'] * tmp_df['Shares']
  tmp_df['EstimatedST'] = tmp_df['NTT'] * tmp_df['Shares']
  tmp_df['EstimatedLT'] = tmp_df['LTT'] * tmp_df['Shares']
  tmp_df['Current P/L'] = round((tmp_df['Current'] - tmp_df['Investment']),0)
  tmp_df['Today P/L%'] = round((tmp_df['Current'] - tmp_df['Previous'])*100/tmp_df['Previous'],2)
  tmp_df['Current P/L%'] = round((tmp_df['Current'] - tmp_df['Investment'])*100/tmp_df['Investment'],2)
  tmp_df['EstimatedST P/L%'] = round((tmp_df['EstimatedST'] - tmp_df['Investment'])*100/tmp_df['Investment'],2)
  tmp_df['EstimatedLT P/L%'] = round((tmp_df['EstimatedLT'] - tmp_df['Investment'])*100/tmp_df['Investment'],2)
  tmp_df['NTT%'] = round((tmp_df['NTT'] - tmp_df['Close'])*100/tmp_df['Close'],2)
  tmp_df['LTT%'] = round((tmp_df['LTT'] - tmp_df['Close'])*100/tmp_df['Close'],2)
  tmp_df['Gained%'] = round((tmp_df['Close'] - tmp_df['BOL'])*100/tmp_df['BOL'],2)
  investment = round(sum(tmp_df['AvgCost']*tmp_df['Shares']),0)
  current = round(sum(tmp_df['Close']*tmp_df['Shares']),0)
  tmp_df['InitAlloc%'] = round(tmp_df['Investment']*100/investment,2)
  tmp_df['CurrAlloc%'] = round(tmp_df['Current']*100/current,2)
  tmp_df['FTT'] = tmp_df['LTT']
  tmp_df.loc[tmp_df['Strategy'] == 'NTT', 'FTT'] = tmp_df['NTT']
  tmp_df['FTT%'] = tmp_df['LTT%']
  tmp_df.loc[tmp_df['Strategy'] == 'NTT', 'FTT%'] = tmp_df['NTT%']
  tmp_df['FTT Amt'] = round(tmp_df['FTT%'] * tmp_df['Current']/100,0)
  tmp_df['OTT%'] = round((tmp_df['FTT'] - tmp_df['AvgCost'])*100/tmp_df['AvgCost'],2)
  tmp_df['RRR Ind'] = round(tmp_df['Current P/L']/tmp_df['FTT Amt'],2)
  tmp_df['Risk Ind'] = round(tmp_df['Current P/L%']*tmp_df['CurrAlloc%'],0)

  return tmp_df

# function to print portfolio features
def print_portfolio_stats(df_portfolio_features, myinvmt_df):
  from pyxirr import xirr

  total_booked_amt, reserve_amt, cy_booked_amt, py_booked_amt = get_amt()

  dates = myinvmt_df['Date'].values
  dates = np.append(dates, datetime.date.today().strftime('%d-%b-%y'))
  investment = myinvmt_df['Investment'].values
  dates= pd.to_datetime(dates)

  current = round(sum(df_portfolio_features['Close']*df_portfolio_features['Shares']),0) + reserve_amt
  investment_xirr = np.append(investment, current)
  cagr = round(xirr(pd.DataFrame({"dates": dates, "amounts": investment_xirr}))*100,2)

  investment = -sum(investment)
  invested = round(sum(df_portfolio_features['AvgCost']*df_portfolio_features['Shares']),0) + reserve_amt
  previous = round(sum(df_portfolio_features['Prev_Close']*df_portfolio_features['Shares']),0) + reserve_amt
  cy_invested = investment + py_booked_amt

  today_pnl_amount = current-previous
  today_pnl_percentage = round((current-previous)*100/previous,2)

  curr_pnl_amount = current-invested
  curr_pnl_percentage = round((curr_pnl_amount)*100/(cy_invested),2)

  cy_pnl_amount = cy_booked_amt + curr_pnl_amount
  cy_pnl_percentage = round((cy_pnl_amount)*100/cy_invested,2)

  overall_pnl_amount = total_booked_amt + curr_pnl_amount
  overall_pnl_percentage = round((overall_pnl_amount)*100/investment,2)

  estimate_st = round(sum(df_portfolio_features['FTT']*df_portfolio_features['Shares']),0)  + reserve_amt
  est_st_pnl_amount = estimate_st-current
  est_st_pnl_percentage = round((est_st_pnl_amount)*100/current,2)

  estimate_lt = round(sum(df_portfolio_features['LTT']*df_portfolio_features['Shares']),0)  + reserve_amt
  est_lt_pnl_amount = estimate_lt-current
  est_lt_pnl_percentage = round((est_lt_pnl_amount)*100/current,2)

  total_profit = round(sum(df_portfolio_features[df_portfolio_features['Current P/L%'] > 0]['Current']) - sum(df_portfolio_features[df_portfolio_features['Current P/L%'] > 0]['Investment']),0)
  total_loss = round(sum(df_portfolio_features[df_portfolio_features['Current P/L%'] < 0]['Current']) - sum(df_portfolio_features[df_portfolio_features['Current P/L%'] < 0]['Investment']),0)

  cy_booked_percentage = round((cy_booked_amt)*100/current,2)
  py_booked_percentage = round((py_booked_amt)*100/investment,2)
  total_booked_percentage = round((total_booked_amt)*100/investment,2)

  print('=================== PORTFOLIO SNAPSHOT ===================')
  print('Deployed Value: ', format_amt(investment))
  print('Current Value:  ', format_amt(current))
  print('CAGR/XIRR %:    ', '{}%'.format(cagr))
  print('Est FTT Value:  ', format_amt(estimate_st))
  print('Future Upside:  ', '{} ({}%)'.format(
      format_amt(est_st_pnl_amount),
      est_st_pnl_percentage
  ))

  print('=================== PERFORMANCE ==========================')
  print('Current PnL:             {} ({}%)'.format(
      format_amt(curr_pnl_amount), curr_pnl_percentage
  ))
  print('Total Booked PnL:        {} ({}%)'.format(
      format_amt(total_booked_amt), total_booked_percentage
  ))
  print('Booked + Current PnL:    {} ({}%)'.format(
      format_amt(overall_pnl_amount), overall_pnl_percentage
  ))
  print('CY Booked PnL:           {} ({}%)'.format(
      format_amt(cy_booked_amt), cy_booked_percentage
  ))
  print('Prev Year Booked PnL:    {} ({}%)'.format(
      format_amt(py_booked_amt), py_booked_percentage
  ))

  print('=================== TODAY / OPERATIONS ===================')
  print('Today PnL:               {} ({}%)'.format(
      format_amt(today_pnl_amount), today_pnl_percentage
  ))
  print('CY Investment:           ', format_amt(cy_invested))
  print('Reserve:                 ', format_amt(reserve_amt))

  print('=================== P&L DETAIL ============================')
  print('Total Profit:            ', format_amt(total_profit))
  print('Total Loss:              ', format_amt(total_loss))
  print('============================================================')

In [8]:
# get start and end date
start_date, end_date = get_start_end_date()

# get portfolio and prospects data
mypfs_df = get_mypfs_df()
mypps_df = get_mypps_df()
myinvmt_df = get_myinvmt_df()

# merge above datasets
mypf_df = pd.merge(mypfs_df, mypps_df, on="Symbol")

# seggregate dm and sv portfolio
dm_pf = mypf_df[mypf_df['InPortfolio'] == 'DM']
sv_pf = mypf_df[mypf_df['InPortfolio'] == 'SV']

# build portfolio stock dataframe
dm_stocks = get_stock_ids(dm_pf)
sv_stocks = get_stock_ids(sv_pf)
df_stocks = pd.concat([dm_pf,sv_pf], ignore_index = True)

# arrange common and diff stock features
common_cols = ['Symbol', 'Target', 'Criteria', 'Strategy', 'CumlRnk', 'LatestQtr', 'StarStock', 'Conviction', 'Category', 'InFolio', 'XIRR', 'MBQ']
diff_cols = ['Symbol', 'AvgCost', 'Shares']
df_stocks = arrange_features(df_stocks, common_cols, diff_cols)

# get common features
stock_ids = df_stocks['Symbol'].values
df_common_features = get_common_features(stock_ids, df_stocks)

df_common_features.reset_index(drop=True, inplace=True)
df_common_features.drop(['Date'], axis=1, inplace=True)
# get and print portfolio features
df_portfolio_features = get_portfolio_features(df_common_features)

print_portfolio_stats(df_portfolio_features, myinvmt_df)

df = df_portfolio_features
#plot_pie_chart(df, 'CapType', 'Current')
list_ox40n = list(df[df['MBQ'].str.contains('OX40N', na=False)]['Symbol'].values)

Run date time (IST): 2026-09-21 20:03:17
=================== PORTFOLIO QUALITY ====================
qualified stocks: 86
with latest results: 86
still star stocks: 46
=================== PORTFOLIO SNAPSHOT ===================
Deployed Value:  1.49 C
Current Value:   1.54 C
CAGR/XIRR %:     1.48%
Est FTT Value:   2.75 C
Future Upside:   1.20 C (78.12%)
=================== PERFORMANCE ==========================
Current PnL:             -41.96 L (-21.86%)
Total Booked PnL:        48.10 L (32.27%)
Booked + Current PnL:    6.14 L (4.12%)
CY Booked PnL:           5.24 L (3.4%)
Prev Year Booked PnL:    42.87 L (28.76%)
=================== TODAY / OPERATIONS ===================
Today PnL:               16.24 K (0.11%)
CY Investment:            1.92 C
Reserve:                  0.00
=================== P&L DETAIL ============================
Total Profit:             2.84 L
Total Loss:               -44.80 L
============================================================

In [9]:
# top 5 near their targets
cols = ['Symbol', 'Today P/L%', 'Current P/L%', 'FTT%', 'OTT%', 'FTT Amt', 'Current P/L', 'Current', 'FTT', 'Dev%_PE', 'RSI_14','Conviction', 'Spread%',  'CumlRnk', 'RRR Ind', 'CurrAlloc%', 'Gained%', 'Criteria', 'Strategy', 'Category']
df_tmp = df_portfolio_features[~df_portfolio_features['Symbol'].isin(['ENRIN','BLUSPRING','DIGITIDE'])]
df_tmp = df_tmp.sort_values(by = 'FTT Amt', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
50,KOTAKBANK,0.56,9.02,9.08,18.92,23728.0,21622.0,261324.0,452.46,-7.85,54.0,X-LC,4.48,12.0,0.91,1.70,17.58,X40,ATH,BANKS
66,SIS,-1.80,-3.42,25.55,21.26,27400.0,-3792.0,107240.0,528.00,106.30,47.0,H-SC,16.21,168.0,-0.14,0.70,59.45,OX40N,NTT,MISC
85,ZYDUSLIFE,0.09,22.43,10.68,35.51,27403.0,47007.0,256581.0,1285.01,21.07,56.0,H-LC,13.91,120.0,1.72,1.66,35.03,AR,ATH,PHARMA
54,MASFIN,1.11,-10.55,35.55,21.26,31158.0,-10335.0,87645.0,396.02,-30.70,45.0,H-SC,5.68,167.0,-0.33,0.57,4.74,XR,ATH,FINANCE
76,TTKPRESTIG,-1.12,-31.77,46.69,0.09,32105.0,-32015.0,68762.0,770.00,-16.95,27.0,M-SC,7.58,250.0,-1.00,0.45,23.76,OX40N,NTT,DURABLES

In [10]:
# top 5 to accumulate
df_tmp = df_portfolio_features[df_portfolio_features['Conviction'].isin(['X-LC','H-LC'])]
df_tmp = df_tmp[(df_tmp['CumlRnk'] < 40) & (df_tmp['FTT%'] > 20)].sort_values(by = 'CurrAlloc%', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
53,MARUTI,0.41,-11.21,40.87,25.08,109272.0,-33752.0,267366.0,17120.06,-16.59,27.0,X-LC,8.61,33.0,-0.31,1.73,0.41,XR,ATH,AUTO
38,HYUNDAI,-2.93,10.90,29.79,43.94,83031.0,27388.0,278720.0,2782.73,14.92,46.0,X-LC,6.95,29.0,0.33,1.81,27.97,X40N,ATH,AUTO
52,M&M,0.11,-4.61,23.16,17.48,66515.0,-13877.0,287198.0,3762.88,-16.67,31.0,X-LC,2.77,25.0,-0.21,1.86,5.33,X40N,ATH,AUTO
4,ASIANPAINT,-0.45,-11.54,40.58,24.36,118833.0,-38196.0,292836.0,3430.49,-22.51,33.0,X-LC,4.30,30.0,-0.32,1.90,16.04,X40,ATH,PAINTS
45,INFY,-1.23,-24.87,89.89,42.66,270717.0,-99690.0,301165.0,1972.00,-45.53,37.0,X-LC,13.52,3.0,-0.37,1.95,5.40,X40,NTT,IT

In [11]:
# top 5 today
df_tmp = df_portfolio_features.sort_values(by = 'Today P/L%', ascending=False)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
29,GREENPANEL,4.83,-55.90,224.57,43.14,181318.0,-102338.0,80740.0,537.00,NaN,53.0,NaN,20.91,225.0,-0.56,0.52,9.40,XY24,NTT,MISC
58,RAJOOENG,4.23,-46.12,159.10,39.61,87871.0,-47270.0,55230.0,143.10,NaN,61.0,NaN,10.80,136.0,-0.54,0.36,18.32,AR,ATH,MISC
39,ICICIGI,3.50,-20.06,48.73,18.89,77951.0,-40144.0,159965.0,2244.41,-20.25,46.0,X-MC,14.96,66.0,-0.51,1.04,5.70,X40,ATH,INSURANCE
78,UTIAMC,3.33,1.91,48.32,51.15,109482.0,4246.0,226576.0,1371.68,29.00,61.0,M-SC,5.93,229.0,0.04,1.47,6.23,XY24,ATH,FINANCE
82,VOLTAS,2.81,-10.65,62.51,45.20,107089.0,-20427.0,171315.0,1856.00,23.00,39.0,X-MC,12.71,79.0,-0.19,1.11,2.81,XY25,NTT,AC

In [12]:
# bottom 5 today
df_tmp = df_portfolio_features.sort_values(by = 'Today P/L%', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
38,HYUNDAI,-2.93,10.90,29.79,43.94,83031.0,27388.0,278720.0,2782.73,14.92,46.0,X-LC,6.95,29.0,0.33,1.81,27.97,X40N,ATH,AUTO
32,HAVELLS,-2.59,-29.37,86.08,31.42,199405.0,-96340.0,231651.0,2052.62,-39.10,33.0,X-MC,8.58,63.0,-0.48,1.50,1.48,X40,ATH,ELECTRICAL
0,5PAISA,-2.26,-40.20,88.79,12.90,116018.0,-87830.0,130666.0,593.00,-16.18,31.0,H-SC,7.20,170.0,-0.76,0.85,26.09,OX40N,NTT,FINANCE
20,DABUR,-2.14,-24.38,90.02,43.70,168876.0,-60470.0,187598.0,735.00,-34.73,48.0,X-MC,14.63,70.0,-0.36,1.22,4.10,XY24,BTT,FMCG
37,HONAUT,-2.14,-10.07,67.78,50.88,117547.0,-19413.0,173425.0,58192.79,-29.78,43.0,X-SC,9.25,90.0,-0.17,1.13,32.13,X40N,ATH,ELECTRICAL

In [13]:
# top 5 to exit based on CumlRnk
df_tmp = df_portfolio_features[~df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])]
df_tmp = df_tmp[(df_tmp['Current P/L%'] > -1) & (df_tmp['Current P/L%'] < 1)].sort_values(by = 'CumlRnk', ascending=False)
df_tmp[cols].head()

Empty DataFrame
Columns: [Symbol, Today P/L%, Current P/L%, FTT%, OTT%, FTT Amt, Current P/L, Current, FTT, Dev%_PE, RSI_14, Conviction, Spread%, CumlRnk, RRR Ind, CurrAlloc%, Gained%, Criteria, Strategy, Category]
Index: []

In [14]:
# OX40N stocks to exit
df_tmp = df_portfolio_features[(df_portfolio_features['Symbol'].isin(list_ox40n))].sort_values(by = 'Current P/L%', ascending=False)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
25,FINCABLES,-0.81,77.28,16.45,106.44,43057.0,114100.0,261744.0,1629.94,29.41,62.0,M-SC,35.30,220.0,2.65,1.70,98.32,OX40N,ATH,CABLES
66,SIS,-1.80,-3.42,25.55,21.26,27400.0,-3792.0,107240.0,528.00,106.30,47.0,H-SC,16.21,168.0,-0.14,0.70,59.45,OX40N,NTT,MISC
43,INDIGOPNTS,2.80,-19.69,24.55,0.02,34415.0,-34377.0,140182.0,1408.00,-23.35,52.0,M-SC,11.38,222.0,-1.00,0.91,59.72,OX40N,NTT,PAINTS
12,BOSCH-HCIL,-0.49,-26.14,35.37,-0.01,33389.0,-33406.0,94399.0,2282.00,735.27,50.0,M-SC,20.89,231.0,-1.00,0.61,60.68,OX40N,BTT,AC
16,CERA,-2.07,-27.72,71.40,23.89,90781.0,-48759.0,127144.0,9475.00,NaN,37.0,NaN,8.03,153.0,-0.54,0.82,23.60,OX40N,NTT,CERAMICS

In [15]:
# top 5 to book for rotation
df_tmp = df_portfolio_features[(df_portfolio_features['Current P/L%'] > 20) ].sort_values(by = 'CumlRnk', ascending=False)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
25,FINCABLES,-0.81,77.28,16.45,106.44,43057.0,114100.0,261744.0,1629.94,29.41,62.0,M-SC,35.30,220.0,2.65,1.70,98.32,OX40N,ATH,CABLES
85,ZYDUSLIFE,0.09,22.43,10.68,35.51,27403.0,47007.0,256581.0,1285.01,21.07,56.0,H-LC,13.91,120.0,1.72,1.66,35.03,AR,ATH,PHARMA

In [16]:
# top 5 to monitor for exit
df_tmp = df_portfolio_features[~df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])]
df_tmp = df_tmp[(df_tmp['Current P/L%'] > 0) ].sort_values(by = 'Dev%_PE', ascending=False)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
25,FINCABLES,-0.81,77.28,16.45,106.44,43057.0,114100.0,261744.0,1629.94,29.41,62.0,M-SC,35.30,220.0,2.65,1.70,98.32,OX40N,ATH,CABLES
78,UTIAMC,3.33,1.91,48.32,51.15,109482.0,4246.0,226576.0,1371.68,29.00,61.0,M-SC,5.93,229.0,0.04,1.47,6.23,XY24,ATH,FINANCE
67,STARHEALTH,-0.76,5.06,40.17,47.26,118637.0,14215.0,295338.0,761.00,-7.47,38.0,H-SC,12.51,173.0,0.12,1.92,27.70,XY24,NTT,INSURANCE

In [17]:
# top 5 to book for rotation from weak conviction
df_tmp = df_portfolio_features[~df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])]
df_tmp = df_tmp[~df_tmp['Criteria'].isin(['XY25','XY24','X40', 'X40N'])].sort_values(by = 'RRR Ind', ascending=False)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
25,FINCABLES,-0.81,77.28,16.45,106.44,43057.0,114100.0,261744.0,1629.94,29.41,62.0,M-SC,35.30,220.0,2.65,1.70,98.32,OX40N,ATH,CABLES
66,SIS,-1.80,-3.42,25.55,21.26,27400.0,-3792.0,107240.0,528.00,106.30,47.0,H-SC,16.21,168.0,-0.14,0.70,59.45,OX40N,NTT,MISC
80,VALIANTORG,-0.87,-12.10,98.13,74.15,141114.0,-19802.0,143803.0,838.00,NaN,80.0,NaN,24.22,145.0,-0.14,0.93,114.00,XR,NTT,CHEMICALS
3,ALKYLAMINE,0.26,-20.45,142.03,92.54,114078.0,-20643.0,80320.0,4520.85,NaN,44.0,NaN,18.09,142.0,-0.18,0.52,52.52,SR,ATH,CHEMICALS
84,WIPRO,-1.37,-24.38,155.24,93.01,293764.0,-61008.0,189232.0,420.00,-36.01,32.0,M-LC,14.00,98.0,-0.21,1.23,0.00,XR,NTT,IT

In [18]:
# top 5 to accumulate based on lowest RSI_14
df_tmp = df_portfolio_features[df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])].sort_values(by = 'RSI_14', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
56,PGHH,-0.80,-44.35,135.45,31.02,160936.0,-94704.0,118816.0,17484.41,-59.08,24.0,X-SC,22.68,57.0,-0.59,0.77,0.00,X40,ATH,FMCG
53,MARUTI,0.41,-11.21,40.87,25.08,109272.0,-33752.0,267366.0,17120.06,-16.59,27.0,X-LC,8.61,33.0,-0.31,1.73,0.41,XR,ATH,AUTO
26,GILLETTE,-0.35,-16.72,54.53,28.69,115298.0,-42456.0,211440.0,10891.01,-39.86,30.0,X-SC,6.07,83.0,-0.37,1.37,0.00,X40,ATH,FMCG
11,BERGEPAINT,-1.76,-16.96,50.91,25.32,108965.0,-43714.0,214035.0,680.00,-27.80,30.0,X-MC,5.16,68.0,-0.40,1.39,12.24,XY24,NTT,PAINTS
52,M&M,0.11,-4.61,23.16,17.48,66515.0,-13877.0,287198.0,3762.88,-16.67,31.0,X-LC,2.77,25.0,-0.21,1.86,5.33,X40N,ATH,AUTO

In [19]:
# top 5 to accumulate based on Spread and CumlRnk
df_tmp = df_portfolio_features[df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])]
df_tmp = df_tmp[(df_tmp['CumlRnk'] < 100)].sort_values(by = 'Spread%', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
52,M&M,0.11,-4.61,23.16,17.48,66515.0,-13877.0,287198.0,3762.88,-16.67,31.0,X-LC,2.77,25.0,-0.21,1.86,5.33,X40N,ATH,AUTO
1,ABBOTINDIA,-1.14,-9.56,27.56,15.37,44581.0,-17095.0,161760.0,34390.26,-26.33,58.0,X-MC,3.11,58.0,-0.38,1.05,9.57,X40,ATH,PHARMA
17,CIPLA,-0.60,4.19,18.90,23.89,59206.0,12604.0,313259.0,1648.14,18.19,46.0,X-LC,3.37,18.0,0.21,2.03,17.33,X40N,ATH,PHARMA
15,CAMS,-0.59,-7.78,34.97,24.48,81225.0,-19586.0,232270.0,950.00,-12.13,35.0,X-SC,3.42,89.0,-0.24,1.51,14.02,X40N,NTT,MISC
7,BAJAJHFL,-1.87,-24.98,116.12,62.13,237845.0,-68219.0,204827.0,181.50,-37.42,49.0,X-MC,3.64,60.0,-0.29,1.33,14.90,X40N,ATH,FINANCE

In [20]:
# top 5 to accumulate based on lowest Gained%
df_tmp = df_portfolio_features[df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])].sort_values(by = 'Gained%', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
26,GILLETTE,-0.35,-16.72,54.53,28.69,115298.0,-42456.0,211440.0,10891.01,-39.86,30.0,X-SC,6.07,83.0,-0.37,1.37,0.00,X40,ATH,FMCG
56,PGHH,-0.80,-44.35,135.45,31.02,160936.0,-94704.0,118816.0,17484.41,-59.08,24.0,X-SC,22.68,57.0,-0.59,0.77,0.00,X40,ATH,FMCG
53,MARUTI,0.41,-11.21,40.87,25.08,109272.0,-33752.0,267366.0,17120.06,-16.59,27.0,X-LC,8.61,33.0,-0.31,1.73,0.41,XR,ATH,AUTO
36,HINDUNILVR,0.78,-17.31,50.08,24.10,156009.0,-65197.0,311520.0,2922.00,-44.17,41.0,X-LC,9.94,9.0,-0.42,2.02,1.04,XY25,NTT,FMCG
28,GODREJCP,-1.42,-21.08,68.41,32.90,134714.0,-52615.0,196922.0,1460.97,-22.56,34.0,X-MC,16.95,32.0,-0.39,1.28,1.23,X40N,ATH,FMCG

In [21]:
# top 5 to accumulate based on lowest CurrAlloc%
df_tmp = df_portfolio_features[df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])].sort_values(by = 'CurrAlloc%', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
56,PGHH,-0.80,-44.35,135.45,31.02,160936.0,-94704.0,118816.0,17484.41,-59.08,24.0,X-SC,22.68,57.0,-0.59,0.77,0.00,X40,ATH,FMCG
2,ACC,-0.27,-43.77,210.91,74.81,317959.0,-117372.0,150756.0,3906.00,-44.04,42.0,X-SC,12.96,85.0,-0.37,0.98,2.54,XY24,BTT,CEMENT
40,ICICIPRULI,0.20,-18.42,59.69,30.28,95933.0,-36287.0,160718.0,787.27,-47.63,52.0,X-MC,12.37,78.0,-0.38,1.04,7.74,X40,ATH,INSURANCE
39,ICICIGI,3.50,-20.06,48.73,18.89,77951.0,-40144.0,159965.0,2244.41,-20.25,46.0,X-MC,14.96,66.0,-0.51,1.04,5.70,X40,ATH,INSURANCE
1,ABBOTINDIA,-1.14,-9.56,27.56,15.37,44581.0,-17095.0,161760.0,34390.26,-26.33,58.0,X-MC,3.11,58.0,-0.38,1.05,9.57,X40,ATH,PHARMA

In [22]:
# top 5 to accumulate based on CumlRnk
df_tmp = df_portfolio_features.sort_values(by = 'CumlRnk', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
47,ITC,1.79,-23.97,69.29,28.70,230515.0,-104913.0,332682.0,452.00,-31.16,50.0,X-LC,12.35,1.0,-0.46,2.16,4.50,X40,NTT,FMCG
72,TCS,1.13,-35.89,98.75,27.42,309008.0,-175156.0,312919.0,4230.71,-48.00,36.0,X-LC,9.98,2.0,-0.57,2.03,7.96,X40,ATH,IT
45,INFY,-1.23,-24.87,89.89,42.66,270717.0,-99690.0,301165.0,1972.00,-45.53,37.0,X-LC,13.52,3.0,-0.37,1.95,5.40,X40,NTT,IT
74,TMPV,-0.71,-26.57,98.91,46.05,324916.0,-118875.0,328497.0,600.00,-85.99,39.0,X-LC,10.70,4.0,-0.37,2.13,2.69,XY24,NTT,AUTO
33,HCLTECH,2.54,-12.35,44.69,26.82,141402.0,-44566.0,316407.0,1853.42,-16.35,52.0,X-LC,4.55,8.0,-0.32,2.05,25.13,X40,ATH,IT

In [23]:
# top 5 for average up
df_tmp = df_portfolio_features[(df_portfolio_features['Dev%_200'] > 5)].sort_values(by = 'CurrAlloc%', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
3,ALKYLAMINE,0.26,-20.45,142.03,92.54,114078.0,-20643.0,80320.0,4520.85,NaN,44.0,NaN,18.09,142.0,-0.18,0.52,52.52,SR,ATH,CHEMICALS
12,BOSCH-HCIL,-0.49,-26.14,35.37,-0.01,33389.0,-33406.0,94399.0,2282.00,735.27,50.0,M-SC,20.89,231.0,-1.00,0.61,60.68,OX40N,BTT,AC
66,SIS,-1.80,-3.42,25.55,21.26,27400.0,-3792.0,107240.0,528.00,106.30,47.0,H-SC,16.21,168.0,-0.14,0.70,59.45,OX40N,NTT,MISC
43,INDIGOPNTS,2.80,-19.69,24.55,0.02,34415.0,-34377.0,140182.0,1408.00,-23.35,52.0,M-SC,11.38,222.0,-1.00,0.91,59.72,OX40N,NTT,PAINTS
80,VALIANTORG,-0.87,-12.10,98.13,74.15,141114.0,-19802.0,143803.0,838.00,NaN,80.0,NaN,24.22,145.0,-0.14,0.93,114.00,XR,NTT,CHEMICALS

In [24]:
# top 5 RSP
df_tmp = df_portfolio_features.sort_values(by = 'RSP', ascending=False)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
80,VALIANTORG,-0.87,-12.10,98.13,74.15,141114.0,-19802.0,143803.0,838.00,NaN,80.0,NaN,24.22,145.0,-0.14,0.93,114.00,XR,NTT,CHEMICALS
25,FINCABLES,-0.81,77.28,16.45,106.44,43057.0,114100.0,261744.0,1629.94,29.41,62.0,M-SC,35.30,220.0,2.65,1.70,98.32,OX40N,ATH,CABLES
58,RAJOOENG,4.23,-46.12,159.10,39.61,87871.0,-47270.0,55230.0,143.10,NaN,61.0,NaN,10.80,136.0,-0.54,0.36,18.32,AR,ATH,MISC
18,COFFEEDAY,-1.21,-49.02,165.34,35.27,95712.0,-55661.0,57888.0,80.00,NaN,46.0,NaN,0.38,266.0,-0.58,0.38,42.76,XR,NTT,HOTELS
85,ZYDUSLIFE,0.09,22.43,10.68,35.51,27403.0,47007.0,256581.0,1285.01,21.07,56.0,H-LC,13.91,120.0,1.72,1.66,35.03,AR,ATH,PHARMA

In [25]:
# Top N allocation
df_tmp = df_portfolio_features.sort_values(by = 'CurrAlloc%', ascending=False)
top_n_values = [10, 25, 50]

sum_df = pd.DataFrame({
    'Top_N': top_n_values,
    'Sum_Alloc%': [df_tmp['CurrAlloc%'].head(n).sum() for n in top_n_values]
})

sum_df

   Top_N  Sum_Alloc%
0     10       21.13
1     25       48.20
2     50       79.55

In [26]:
# market-cap-wise allocation
df_tmp = df_portfolio_features[cols]
df_tmp.groupby(df_tmp['Conviction'].str[-2:])['CurrAlloc%'].sum().sort_values(ascending=False)

Conviction
LC    40.97
MC    20.98
SC    20.77
Name: CurrAlloc%, dtype: float64

In [27]:
# criteria-wise allocation
df_portfolio_features.groupby('Criteria')['CurrAlloc%'].sum().sort_values(ascending=False)

Criteria
X40      28.23
XY24     23.35
X40N     18.89
XR        9.58
XY25      7.49
OX40N     7.08
AR        4.57
SR        0.83
Name: CurrAlloc%, dtype: float64

In [28]:
# conviction-wise allocation
df_portfolio_features.groupby('Conviction')['CurrAlloc%'].sum().sort_values(ascending=False)

Conviction
X-LC    38.08
X-MC    18.52
H-SC     8.04
X-SC     7.22
M-SC     5.51
H-LC     1.66
M-LC     1.23
M-MC     1.11
H-MC     1.00
L-MC     0.35
Name: CurrAlloc%, dtype: float64

In [29]:
# sector-wise stats
df_tmp = df_portfolio_features.groupby('Category')[['CurrAlloc%', 'Current', 'Current P/L', 'FTT Amt']].sum().sort_values(by=['Current', 'Current P/L'], ascending=False)
df_tmp['Current P/L%'] = round(df_tmp['Current P/L'] * 100 / df_tmp['Current'], 2)
df_tmp['FTT%'] = round(df_tmp['FTT Amt'] * 100 / df_tmp['Current'], 2)
cols = ['CurrAlloc%', 'Current P/L%', 'FTT%']
df_tmp[cols].sort_values(by=['CurrAlloc%'], ascending=False)

               CurrAlloc%  Current P/L%    FTT%
Category
FMCG                15.88        -28.50   75.64
IT                  11.41        -45.97  123.11
FINANCE             10.96        -19.41   70.42
AUTO                 8.52        -13.97   54.63
BANKS                6.76         -9.11   56.64
PHARMA               6.23          7.52   17.96
INSURANCE            5.96         -7.83   46.69
MISC                 5.73        -39.84   96.09
PAINTS               5.26        -27.36   49.83
ELECTRICAL           2.63        -28.58   78.25
REFINERIES           2.02        -14.63   56.49
AC                   1.72        -20.26   52.87
CABLES               1.70         43.59   16.45
APPARELS             1.63         -6.65   41.69
BREWERIES            1.56          2.56   17.68
FOOTWEAR             1.48        -93.64  171.27
CHEMICALS            1.45        -18.05  113.86
DURABLES             1.39        -81.00  125.04
TRAVEL               1.37       -113.06  219.75
ENGINEERING          1.24        -26.29   84.06
CERAMICS             1.23        -61.03  109.96
CEMENT               0.98        -77.86  210.91
JEWELLERY            0.88       -135.20  216.92
ENTERTAINMENT        0.66        -89.23  202.08
HEALTHCARE           0.62        -88.97  136.41
HOTELS               0.38        -96.15  165.34
TEXTILES             0.37        -62.25  108.51

In [30]:
# money to be made criteria-wise
df_portfolio_features.groupby('Criteria')['FTT Amt'].agg(['sum', 'count']).sort_values(by='sum', ascending=False)

                sum  count
Criteria
XY24      3836948.0     19
X40       2421014.0     18
XR        1577909.0     13
X40N      1430161.0     12
AR        1094249.0      7
OX40N      700098.0     10
XY25       693090.0      5
SR         287953.0      2

In [31]:
# money to be made conviction-wise
df_portfolio_features.groupby('Conviction')['FTT Amt'].agg(['sum', 'count']).sort_values(by='sum', ascending=False)

                  sum  count
Conviction
X-LC        2992122.0     19
X-MC        1649047.0     14
X-SC        1162834.0      6
H-SC         913354.0      8
M-SC         314146.0      6
M-LC         293764.0      1
H-MC         260248.0      1
M-MC          74693.0      1
L-MC          48106.0      1
H-LC          27403.0      1

In [32]:
# money to be made criteria and conviction-wise
df_portfolio_features.groupby(['Conviction', 'Criteria'])['FTT Amt'].agg(['sum', 'count']).sort_values(by='sum', ascending=False)

                           sum  count
Conviction Criteria
X-LC       X40       1459366.0      9
X-SC       XY24       687828.0      2
X-MC       X40        564169.0      6
H-SC       XY24       556731.0      3
X-LC       XY24       546633.0      2
           X40N       544678.0      5
X-MC       X40N       520813.0      4
X-LC       XY25       332173.0      2
M-LC       XR         293764.0      1
X-MC       XY25       286224.0      2
           XY24       277841.0      2
X-SC       X40        276234.0      2
H-MC       XY24       260248.0      1
H-SC       OX40N      255022.0      3
X-SC       X40N       198772.0      2
M-SC       OX40N      142966.0      4
           XY24       109482.0      1
X-LC       XR         109272.0      1
H-SC       XR         101601.0      2
M-MC       XY25        74693.0      1
M-SC       XR          61698.0      1
L-MC       XR          48106.0      1
H-LC       AR          27403.0      1

In [33]:
# notebook execution time

end_time = time.time()
execution_time = round(end_time - start_time, 0)
print(f"Notebook execution time: {execution_time} seconds")

Notebook execution time: 28.0 seconds