<a href="https://colab.research.google.com/github/ankit-rathi/Quantvesting_v2/blob/main/myStocks_Portfolio_Analysis.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
'''
!pip install pandas==2.2.2 -qq
!pip install pyxirr -qq
!pip install ta -qq
!pip install yfinance==0.2.59 -qq
'''

'\n!pip install pandas==2.2.2 -qq\n!pip install pyxirr -qq\n!pip install ta -qq\n!pip install yfinance==0.2.59 -qq\n'

In [2]:
# import libraries

import numpy as np
import pandas as pd
import datetime
import warnings
warnings.filterwarnings('ignore')
import yfinance as yfin
import ta
import matplotlib.pyplot as plt
import requests

In [3]:
# notebook start time
import time
import datetime
import pytz

start_time = time.time()

# function to print date timestamp
def print_date_time():
  tz_NY = pytz.timezone('Asia/Kolkata')
  datetime_NY = datetime.datetime.now(tz_NY)
  print("Run date time (IST):", datetime_NY.strftime("%Y-%m-%d %H:%M:%S"))

In [4]:
# function to get booked and reserved amount
def get_amt():
  # fetch the JSON data from the URL
  url = "https://raw.githubusercontent.com/ankit-rathi/Tradevesting_v1/main/data/myPortfolioAmts.json"
  response = requests.get(url)
  pf_amts = response.json()  # parse the JSON data

  # extract values from the JSON
  py_booked_amt_dm = pf_amts["py_booked_amt_dm"]
  py_booked_amt_sv = pf_amts["py_booked_amt_sv"]
  cy_booked_amt_dm = pf_amts["cy_booked_amt_dm"]
  cy_booked_amt_sv = pf_amts["cy_booked_amt_sv"]
  reserve_amt_dm = pf_amts["reserve_amt_dm"]
  reserve_amt_sv = pf_amts["reserve_amt_sv"]

  # perform calculations
  py_booked_amt = py_booked_amt_dm + py_booked_amt_sv
  cy_booked_amt = cy_booked_amt_dm + cy_booked_amt_sv
  reserve_amt = reserve_amt_dm + reserve_amt_sv
  total_booked_amt = py_booked_amt + cy_booked_amt

  return total_booked_amt, reserve_amt, cy_booked_amt, py_booked_amt

gen_output = 0

In [5]:
# function to format the amount
def format_amt(number):
    abs_number = abs(number)

    if abs_number >= 1_00_00_000:  # Crores
        formatted_amt = f"{number / 1_00_00_000:.2f} C"
    elif abs_number >= 1_00_000:  # Lakhs
        formatted_amt = f"{number / 1_00_000:.2f} L"
    elif abs_number >= 1_000:  # Thousands
        formatted_amt = f"{number / 1_000:.2f} K"
    else:
        formatted_amt = f"{number:.2f}"

    return formatted_amt

# function to set start and end date
def get_start_end_date():
  start_date = (datetime.date.today() + datetime.timedelta(days=-365)).strftime('%Y-%m-%d')
  end_date = (datetime.date.today() + datetime.timedelta(days=1)).strftime('%Y-%m-%d')
  return start_date, end_date

# function to fetch my portfolio csv
def get_mypfs_df():
  mypfs_df = pd.read_csv('https://raw.githubusercontent.com/ankit-rathi/Tradevesting_v1/main/data/myPortfolioStocks.csv')
  return mypfs_df

# function to fetch my prospects csv
def get_mypps_df():
  mypps_df = pd.read_csv('https://raw.githubusercontent.com/ankit-rathi/Tradevesting_v1/main/data/myProspectsScrips.csv')
  return mypps_df

# function to fetch screener data
def get_myscreen_df():
  myscreen_df = pd.read_csv('https://raw.githubusercontent.com/ankit-rathi/Tradevesting_v1/main/data/myScreenerDB.csv')
  return myscreen_df

# function to fetch momentum data
def get_myinvmt_df():
  myinvmt_df = pd.read_csv('https://raw.githubusercontent.com/ankit-rathi/Tradevesting_v1/main/data/myInvestments.csv')
  return myinvmt_df

# function to get the stock ids
def get_stock_ids(df_pf):
  stock_n100 = df_pf['Symbol'].unique()

  exclude = ['CADILAHC','MMTC', 'MASFIN']

  stock_ids = df_pf[~df_pf['Symbol'].isin(exclude) ]['Symbol'].unique()

  #mypf = mypf[mypf.Forecast.notnull()]
  #stock_ids = mypf['Symbol'].unique()

  #stock_ids.sort()
  return stock_ids

# get features from screener data
def get_screener_features():
  myscreen_df = get_myscreen_df()
  cols = ['Symbol', 'EPS', 'MedPE', 'ROCE%', 'ROE%', 'CapType']
  return myscreen_df[cols]

# get relative strength
def get_relative_strength(stock_list):

    # Dictionary to store stock tickers and their corresponding percentage price change
    stock_changes = {}

    # Loop through each stock and fetch its price data
    for stock in stock_list:
        try:
            # Download the stock data for the given date range
            stock_data = yfin.Ticker(stock + '.NS').history(period='1mo', interval='1d')[map(str.title, ['open', 'close', 'low', 'high', 'volume'])]

            # Calculate the percentage change for the stock
            if len(stock_data) > 0:
                start_price = stock_data['Close'].iloc[0]
                end_price = stock_data['Close'].iloc[-1]
                percent_change = round(((end_price - start_price) / start_price) * 100, 2)
                stock_changes[stock] = percent_change
            else:
                stock_changes[stock] = np.nan  # If no data is available, set to NaN

        except Exception as e:
            print(f"Error fetching data for {stock}: {e}")
            stock_changes[stock] = np.nan

    # Create a DataFrame with stock tickers and their percentage changes
    df = pd.DataFrame(list(stock_changes.items()), columns=['Symbol', 'Percent_Change'])

    # Drop any stocks with missing data (NaN values)
    df = df.dropna()

    # Calculate the percentile rank based on percentage change
    df['RSP'] = round(df['Percent_Change'].rank(pct=True) * 100, 2)
    cols = ['Symbol', 'RSP']
    df = df[cols]
    # Sort by percentile rank (optional)
    df = df.sort_values(by='RSP', ascending=False).reset_index(drop=True)

    return df

In [6]:
# function to get stock technicals
def stock_prec_dev(stock_symbol):
    #stock_symbol = 'ULTRACEMCO.NS'
    short_window = 20
    mid_window = 50
    long_window = 200
    moving_avg = 'SMA'

    start = datetime.datetime(*map(int, start_date.split('-')))
    end = datetime.datetime(*map(int, end_date.split('-')))

    stock_df = yfin.Ticker(stock_symbol + '.NS').history(period='max', interval='1d')[map(str.title, ['open', 'close', 'low', 'high', 'volume'])]

    stock_df['Max'] = round(max(stock_df['Close']),2)
    stock_df = stock_df[(stock_df.index <= end_date) & (stock_df.index >= start_date)]
    stock_df['200_SMA'] = round(stock_df['Close'].rolling(window = 200, min_periods = 1).mean(),0)
    stock_df['Dev%_200'] = round((stock_df['Close'] - stock_df['200_SMA'])*100/stock_df['200_SMA'],2)
    stock_df.dropna(axis = 0, inplace = True) # remove any null rows

    stock_df['20_SMA'] = stock_df['Close'].rolling(window=20).mean()
    stock_df['50_SMA'] = stock_df['Close'].rolling(window=50).mean()
    stock_df['Symbol'] = stock_symbol

    stock_df['Close'] = round(stock_df['Close'],2)
    stock_df['Min'] = round(min(stock_df['Close']),2)
    stock_df['RSI_14'] = ta.momentum.RSIIndicator(close=stock_df['Close'], window=14).rsi()
    stock_df['RSI_14'] = round(stock_df['RSI_14'],0)
    stock_df['Prev_Close'] = stock_df['Close'].shift(1)
    stock_df.drop(['Open', 'Low', 'High', 'Volume'], axis=1, inplace=True)
    stock_df = stock_df.tail(1)

    max_SMA = max(stock_df['20_SMA'].item(), stock_df['50_SMA'].item(), stock_df['200_SMA'].item())
    min_SMA = min(stock_df['20_SMA'].item(), stock_df['50_SMA'].item(), stock_df['200_SMA'].item())
    ABS_Spread = max_SMA - min_SMA
    stock_df['Spread%'] = round((ABS_Spread / stock_df['200_SMA'].item()) * 100,2)

    return stock_df

# function to compute stock attributes
def get_common_features(stock_ids, df_mypf):

  df_prec_dev = pd.DataFrame()
  df_tmp = get_screener_features()
  df_rs = get_relative_strength(stock_ids)

  for stock_id in stock_ids:
      tmp = stock_prec_dev(stock_id)
      tmp = tmp.reset_index()
      df_prec_dev = pd.concat([df_prec_dev, tmp], ignore_index = True)
  df_prec_dev = pd.merge(df_prec_dev, df_mypf, on= 'Symbol')
  df_prec_dev = pd.merge(df_prec_dev, df_tmp, on= 'Symbol', how='left')
  df_prec_dev = pd.merge(df_prec_dev, df_rs, on= 'Symbol', how='left')
  #print(df_prec_dev.columns)
  df_prec_dev['Curr_PE'] = round(df_prec_dev['Close']/df_prec_dev['EPS'],1)
  df_prec_dev['Dev%_PE'] = round((df_prec_dev['Curr_PE'] - df_prec_dev['MedPE'])*100/df_prec_dev['MedPE'],2)
  df_prec_dev['Conviction'] = df_prec_dev['Conviction'] + '-' + df_prec_dev['CapType']
  return df_prec_dev

# function to arrange stock features
def arrange_features(df_stocks, common_cols, diff_cols):
  df_stocks_common = df_stocks[common_cols].drop_duplicates()
  df_stocks_diff = df_stocks[diff_cols]
  df_stocks_diff['Investment'] = df_stocks_diff['AvgCost'] * df_stocks_diff['Shares']
  df_stocks_diff = df_stocks_diff.groupby(['Symbol'])[['Shares', 'Investment']].aggregate(['sum']).reset_index()
  df_stocks_diff.columns = ['Symbol', 'Shares', 'Investment']
  df_stocks_diff['AvgCost'] = round(df_stocks_diff['Investment']/df_stocks_diff['Shares'],2)
  df_stocks = pd.merge(df_stocks_diff, df_stocks_common, on='Symbol')
  return df_stocks

# plot fact distribution across dimension
def plot_pie_chart(df, dimension, fact):
  # grouping the data by category and calculating the sum of fact for each type
  grouped_data = df.groupby(dimension)[fact].sum()

  # sorting the grouped data in descending order
  grouped_data = grouped_data.sort_values(ascending=False)

  # creating a pie chart
  grouped_data.plot.pie(autopct='%1.1f%%', startangle=90, figsize=(6, 6))

  # adding a title and displaying the plot
  plt.title(f'{dimension} {fact} Distribution')
  plt.ylabel('')  # To hide the y-label
  plt.show()

In [7]:
# function to get portfolio features

def get_portfolio_features(df_common_features):

  print_date_time()
  print('-------------------')

  #df_common_features["Target"] = df_common_features["Target"].fillna(df_common_features["Max"])
  df_common_features['NTT'] = np.where(df_common_features['Strategy']== 'NTT', df_common_features["Target"], df_common_features['Max'])
  df_common_features['LTT'] = np.where(df_common_features['Strategy']== 'BTT', df_common_features["Target"], df_common_features['Max'])
  df_common_features['BOL'] = df_common_features['Min']

  tmp_df = df_common_features[df_common_features['Symbol'].isin(mypf_df[mypf_df['InPortfolio'] != 'NA'].Symbol.values)]
  print('qualified stocks: '+str(len(tmp_df['Symbol'].unique())))
  tmp_df1 = tmp_df[tmp_df['LatestQtr'] == 1]
  print('with latest results: '+str(len(tmp_df1['Symbol'].unique())))
  tmp_df1 = tmp_df1[tmp_df1['StarStock'] == 1]
  print('still star stocks: '+str(len(tmp_df1['Symbol'].unique())))
  tmp_df['Investment'] = tmp_df['AvgCost'] * tmp_df['Shares']
  tmp_df['Current'] = round(tmp_df['Close'] * tmp_df['Shares'],0)
  tmp_df['Previous'] = tmp_df['Prev_Close'] * tmp_df['Shares']
  tmp_df['EstimatedST'] = tmp_df['NTT'] * tmp_df['Shares']
  tmp_df['EstimatedLT'] = tmp_df['LTT'] * tmp_df['Shares']
  tmp_df['Current P/L'] = round((tmp_df['Current'] - tmp_df['Investment']),0)
  tmp_df['Today P/L%'] = round((tmp_df['Current'] - tmp_df['Previous'])*100/tmp_df['Previous'],2)
  tmp_df['Current P/L%'] = round((tmp_df['Current'] - tmp_df['Investment'])*100/tmp_df['Investment'],2)
  tmp_df['EstimatedST P/L%'] = round((tmp_df['EstimatedST'] - tmp_df['Investment'])*100/tmp_df['Investment'],2)
  tmp_df['EstimatedLT P/L%'] = round((tmp_df['EstimatedLT'] - tmp_df['Investment'])*100/tmp_df['Investment'],2)
  tmp_df['NTT%'] = round((tmp_df['NTT'] - tmp_df['Close'])*100/tmp_df['Close'],2)
  tmp_df['LTT%'] = round((tmp_df['LTT'] - tmp_df['Close'])*100/tmp_df['Close'],2)
  tmp_df['Gained%'] = round((tmp_df['Close'] - tmp_df['BOL'])*100/tmp_df['BOL'],2)
  investment = round(sum(tmp_df['AvgCost']*tmp_df['Shares']),0)
  current = round(sum(tmp_df['Close']*tmp_df['Shares']),0)
  tmp_df['InitAlloc%'] = round(tmp_df['Investment']*100/investment,2)
  tmp_df['CurrAlloc%'] = round(tmp_df['Current']*100/current,2)
  tmp_df['FTT'] = tmp_df['LTT']
  tmp_df.loc[tmp_df['Strategy'] == 'NTT', 'FTT'] = tmp_df['NTT']
  tmp_df['FTT%'] = tmp_df['LTT%']
  tmp_df.loc[tmp_df['Strategy'] == 'NTT', 'FTT%'] = tmp_df['NTT%']
  tmp_df['FTT Amt'] = round(tmp_df['FTT%'] * tmp_df['Current']/100,0)
  tmp_df['OTT%'] = round((tmp_df['FTT'] - tmp_df['AvgCost'])*100/tmp_df['AvgCost'],2)
  tmp_df['RRR Ind'] = round(tmp_df['Current P/L']/tmp_df['FTT Amt'],2)
  tmp_df['Risk Ind'] = round(tmp_df['Current P/L%']*tmp_df['CurrAlloc%'],0)

  return tmp_df

# function to print portfolio features
def print_portfolio_stats(df_portfolio_features, myinvmt_df):
  from pyxirr import xirr

  total_booked_amt, reserve_amt, cy_booked_amt, py_booked_amt = get_amt()

  dates = myinvmt_df['Date'].values
  dates = np.append(dates, datetime.date.today().strftime('%d-%b-%y'))
  investment = myinvmt_df['Investment'].values
  dates= pd.to_datetime(dates)

  current = round(sum(df_portfolio_features['Close']*df_portfolio_features['Shares']),0) + reserve_amt
  investment_xirr = np.append(investment, current)
  cagr = round(xirr(pd.DataFrame({"dates": dates, "amounts": investment_xirr}))*100,2)

  investment = -sum(investment)
  invested = round(sum(df_portfolio_features['AvgCost']*df_portfolio_features['Shares']),0) + reserve_amt
  previous = round(sum(df_portfolio_features['Prev_Close']*df_portfolio_features['Shares']),0) + reserve_amt
  cy_invested = investment + py_booked_amt

  today_pnl_amount = current-previous
  today_pnl_percentage = round((current-previous)*100/previous,2)

  curr_pnl_amount = current-invested
  curr_pnl_percentage = round((curr_pnl_amount)*100/(cy_invested),2)

  cy_pnl_amount = cy_booked_amt + curr_pnl_amount
  cy_pnl_percentage = round((cy_pnl_amount)*100/cy_invested,2)

  overall_pnl_amount = total_booked_amt + curr_pnl_amount
  overall_pnl_percentage = round((overall_pnl_amount)*100/investment,2)

  estimate_st = round(sum(df_portfolio_features['FTT']*df_portfolio_features['Shares']),0)  + reserve_amt
  est_st_pnl_amount = estimate_st-current
  est_st_pnl_percentage = round((est_st_pnl_amount)*100/current,2)

  estimate_lt = round(sum(df_portfolio_features['LTT']*df_portfolio_features['Shares']),0)  + reserve_amt
  est_lt_pnl_amount = estimate_lt-current
  est_lt_pnl_percentage = round((est_lt_pnl_amount)*100/current,2)

  total_profit = round(sum(df_portfolio_features[df_portfolio_features['Current P/L%'] > 0]['Current']) - sum(df_portfolio_features[df_portfolio_features['Current P/L%'] > 0]['Investment']),0)
  total_loss = round(sum(df_portfolio_features[df_portfolio_features['Current P/L%'] < 0]['Current']) - sum(df_portfolio_features[df_portfolio_features['Current P/L%'] < 0]['Investment']),0)

  cy_booked_percentage = round((cy_booked_amt)*100/current,2)
  py_booked_percentage = round((py_booked_amt)*100/investment,2)
  total_booked_percentage = round((total_booked_amt)*100/investment,2)

  print('-------------------')
  print('Initial Investment: ', format_amt(investment))
  print('CY Investment: ', format_amt(cy_invested))
  print('Reserve: ', format_amt(reserve_amt))
  print('Current: ',  format_amt(current))
  print('-------------------')
  print('Today PnL: '+ '{} ({}%)'.format(format_amt(today_pnl_amount), today_pnl_percentage))
  print('Current PnL: '+ '{} ({}%)'.format(format_amt(curr_pnl_amount), curr_pnl_percentage))
  print('CY Booked + Current PnL: '+ '{} ({}%)'.format(format_amt(cy_pnl_amount), cy_pnl_percentage))
  print('-------------------')
  print('Total profit: ', format_amt(total_profit))
  print('Total loss: ', format_amt(total_loss))
  print('-------------------')
  print('Total Booked + Current PnL: '+ '{} ({}%)'.format(format_amt(overall_pnl_amount), overall_pnl_percentage))
  print('Total Booked PnL: '+ '{} ({}%)'.format(format_amt(total_booked_amt), total_booked_percentage))
  print('Curr Year Booked PnL: '+ '{} ({}%)'.format(format_amt(cy_booked_amt), cy_booked_percentage))
  print('Prev Year Booked PnL: '+ '{} ({}%)'.format(format_amt(py_booked_amt), py_booked_percentage))
  print('===================')
  print('Est FTT: ',  format_amt(estimate_st))
  print('Est FTT PnL: '+ '{} ({}%)'.format(format_amt(est_st_pnl_amount), est_st_pnl_percentage))

  print('===================')
  print('Deployed: ', format_amt(investment))

  print('Current: ', format_amt(current))

  print('CAGR/XIRR %: '+'{}%'.format(cagr))

In [8]:
# get start and end date
start_date, end_date = get_start_end_date()

# get portfolio and prospects data
mypfs_df = get_mypfs_df()
mypps_df = get_mypps_df()
myinvmt_df = get_myinvmt_df()

# merge above datasets
mypf_df = pd.merge(mypfs_df, mypps_df, on="Symbol")

# seggregate dm and sv portfolio
dm_pf = mypf_df[mypf_df['InPortfolio'] == 'DM']
sv_pf = mypf_df[mypf_df['InPortfolio'] == 'SV']

# build portfolio stock dataframe
dm_stocks = get_stock_ids(dm_pf)
sv_stocks = get_stock_ids(sv_pf)
df_stocks = pd.concat([dm_pf,sv_pf], ignore_index = True)

# arrange common and diff stock features
common_cols = ['Symbol', 'Target', 'Criteria', 'Strategy', 'CumlRnk', 'LatestQtr', 'StarStock', 'Conviction', 'Category', 'InFolio', 'XIRR', 'MBQ']
diff_cols = ['Symbol', 'AvgCost', 'Shares']
df_stocks = arrange_features(df_stocks, common_cols, diff_cols)

# get common features
stock_ids = df_stocks['Symbol'].values
df_common_features = get_common_features(stock_ids, df_stocks)

df_common_features.reset_index(drop=True, inplace=True)
df_common_features.drop(['Date'], axis=1, inplace=True)
# get and print portfolio features
df_portfolio_features = get_portfolio_features(df_common_features)

print_portfolio_stats(df_portfolio_features, myinvmt_df)

df = df_portfolio_features
#plot_pie_chart(df, 'CapType', 'Current')
list_ox40n = list(df[df['MBQ'].str.contains('OX40N', na=False)]['Symbol'].values)

Run date time (IST): 2026-06-10 11:53:54
-------------------
qualified stocks: 92
with latest results: 31
still star stocks: 20

-------------------
Initial Investment:  1.40 C
CY Investment:  1.82 C
Reserve:  1.49 K
Current:  1.49 C
-------------------
Today PnL: 53.17 K (0.36%)
Current PnL: -34.56 L (-18.95%)
CY Booked + Current PnL: -32.48 L (-17.81%)
-------------------
Total profit:  2.58 L
Total loss:  -37.13 L
-------------------
Total Booked + Current PnL: 10.39 L (7.45%)
Total Booked PnL: 44.95 L (32.22%)
Curr Year Booked PnL: 2.08 L (1.4%)
Prev Year Booked PnL: 42.87 L (30.73%)
===================
Est FTT:  2.55 C
Est FTT PnL: 1.07 C (71.69%)
===================
Deployed:  1.40 C
Current:  1.49 C
CAGR/XIRR %: 2.99%

In [9]:
# top 5 near their targets
cols = ['Symbol', 'Today P/L%', 'Current P/L%', 'FTT%', 'OTT%', 'FTT Amt', 'Current P/L', 'Current', 'FTT', 'Dev%_PE', 'RSI_14','Conviction', 'Spread%',  'CumlRnk', 'RRR Ind', 'CurrAlloc%', 'Gained%', 'Criteria', 'Strategy', 'Category']
df_tmp = df_portfolio_features[~df_portfolio_features['Symbol'].isin(['ENRIN','BLUSPRING','DIGITIDE'])]
df_tmp = df_tmp.sort_values(by = 'FTT Amt', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
59,PIDILITIND,2.46,7.59,10.02,18.37,15212.0,10710.0,151820.0,1670.26,-24.63,66.0,X-LC,4.01,5.0,0.70,1.02,19.21,X40,ATH,CHEMICALS
51,KOTAKBANK,2.19,4.22,16.20,21.11,23380.0,5846.0,144318.0,453.24,-10.71,58.0,X-LC,6.84,12.0,0.25,0.97,10.37,X40,ATH,BANKS
72,SIS,-0.01,-3.28,25.37,21.26,27246.0,-3639.0,107393.0,528.00,2561.14,65.0,H-SC,20.72,168.0,-0.13,0.72,59.68,OX40N,NTT,MISC
55,MASFIN,-1.19,-8.25,32.50,21.57,29216.0,-8085.0,89895.0,397.04,-20.96,39.0,H-SC,2.33,167.0,-0.28,0.60,7.15,XR,ATH,FINANCE
83,TTKPRESTIG,-0.06,-29.32,41.61,0.09,29639.0,-29546.0,71231.0,770.00,65.42,56.0,M-SC,12.64,250.0,-1.00,0.48,26.84,OX40N,NTT,DURABLES

In [10]:
# top 5 today
df_tmp = df_portfolio_features.sort_values(by = 'Today P/L%', ascending=False)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
24,EASEMYTRIP,8.26,-52.98,209.86,45.70,174473.0,-93677.0,83138.0,26.40,-13.69,65.0,M-SC,5.18,204.0,-0.54,0.56,45.64,XY24,NTT,TRAVEL
69,SFL,4.20,-30.19,81.40,26.63,149004.0,-79167.0,183051.0,1287.00,38.71,77.0,M-SC,8.98,242.0,-0.53,1.23,52.56,XY24,NTT,MISC
37,HONAUT,3.20,-6.01,60.99,51.31,110544.0,-11588.0,181250.0,58357.33,-21.90,68.0,X-SC,6.79,90.0,-0.10,1.22,37.70,X40N,ATH,ELECTRICAL
62,RAJOOENG,3.18,-46.44,160.66,39.61,88202.0,-47600.0,54900.0,143.10,-63.71,46.0,H-SC,23.46,136.0,-0.54,0.37,17.61,AR,ATH,MISC
36,HINDUNILVR,2.77,-14.74,33.32,13.67,73031.0,-37883.0,219180.0,2922.00,-36.70,52.0,X-LC,7.81,9.0,-0.52,1.47,6.80,XY25,NTT,FMCG

In [11]:
# bottom 5 today
df_tmp = df_portfolio_features.sort_values(by = 'Today P/L%', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
61,RAJESHEXPO,-4.99,-83.65,511.86,0.07,114836.0,-114742.0,22435.0,518.00,721.97,26.0,L-SC,31.99,268.0,-1.00,0.15,5.32,OX40N,NTT,JEWELLERY
18,COFFEEDAY,-2.76,-42.85,136.69,35.27,88706.0,-48653.0,64896.0,80.00,-55.73,57.0,L-SC,18.09,266.0,-0.55,0.44,60.04,XR,NTT,HOTELS
12,BOSCH-HCIL,-2.16,-40.67,68.53,-0.01,51966.0,-51975.0,75830.0,2282.00,15421.74,45.0,M-SC,9.59,231.0,-1.00,0.51,29.07,OX40N,BTT,AC
25,FINCABLES,-1.97,28.15,62.24,107.91,117762.0,41563.0,189207.0,1641.55,15.17,47.0,M-SC,24.36,220.0,0.35,1.27,42.35,OX40N,ATH,CABLES
9,BANDHANBNK,-1.84,-2.28,96.91,92.42,263797.0,-6351.0,272208.0,400.00,133.48,56.0,H-SC,20.95,174.0,-0.02,1.83,49.95,XY24,NTT,BANKS

In [12]:
# top 5 to exit based on CumlRnk
df_tmp = df_portfolio_features[~df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])]
df_tmp = df_tmp[(df_tmp['Current P/L%'] > -1) & (df_tmp['Current P/L%'] < 1)].sort_values(by = 'CumlRnk', ascending=False)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
75,SURYODAY,-0.31,-0.65,23.84,23.03,42413.0,-1163.0,177908.0,216.0,92.98,67.0,H-SC,17.99,166.0,-0.03,1.2,49.79,XR,NTT,BANKS

In [13]:
# OX40N stocks to exit
df_tmp = df_portfolio_features[(df_portfolio_features['Symbol'].isin(list_ox40n))].sort_values(by = 'Current P/L%', ascending=False)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
25,FINCABLES,-1.97,28.15,62.24,107.91,117762.0,41563.0,189207.0,1641.55,15.17,47.0,M-SC,24.36,220.0,0.35,1.27,42.35,OX40N,ATH,CABLES
72,SIS,-0.01,-3.28,25.37,21.26,27246.0,-3639.0,107393.0,528.00,2561.14,65.0,H-SC,20.72,168.0,-0.13,0.72,59.68,OX40N,NTT,MISC
16,CERA,0.99,-22.95,60.80,23.89,82401.0,-40375.0,135528.0,9475.00,-25.78,62.0,H-SC,4.38,153.0,-0.49,0.91,30.24,OX40N,NTT,CERAMICS
50,KANSAINER,2.54,-28.23,58.10,13.47,112450.0,-76122.0,193545.0,340.00,-38.33,56.0,H-SC,8.44,162.0,-0.68,1.30,35.19,XY24,NTT,PAINTS
83,TTKPRESTIG,-0.06,-29.32,41.61,0.09,29639.0,-29546.0,71231.0,770.00,65.42,56.0,M-SC,12.64,250.0,-1.00,0.48,26.84,OX40N,NTT,DURABLES

In [14]:
# top 5 to book for rotation
df_tmp = df_portfolio_features[(df_portfolio_features['Current P/L%'] > 20) ].sort_values(by = 'CumlRnk', ascending=False)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
25,FINCABLES,-1.97,28.15,62.24,107.91,117762.0,41563.0,189207.0,1641.55,15.17,47.0,M-SC,24.36,220.0,0.35,1.27,42.35,OX40N,ATH,CABLES
68,SATIN,-1.30,32.41,14.67,51.83,53668.0,89548.0,365832.0,274.00,18.27,68.0,H-SC,41.57,159.0,1.67,2.46,78.21,XY24,NTT,FINANCE

In [15]:
# top 5 to monitor for exit
df_tmp = df_portfolio_features[~df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])]
df_tmp = df_tmp[(df_tmp['Current P/L%'] > 0) ].sort_values(by = 'Dev%_PE', ascending=False)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
74,STARHEALTH,1.18,2.09,44.25,47.26,126992.0,5864.0,286987.0,761.00,61.10,58.0,H-SC,9.88,173.0,0.05,1.93,26.00,XY24,NTT,INSURANCE
68,SATIN,-1.30,32.41,14.67,51.83,53668.0,89548.0,365832.0,274.00,18.27,68.0,H-SC,41.57,159.0,1.67,2.46,78.21,XY24,NTT,FINANCE
25,FINCABLES,-1.97,28.15,62.24,107.91,117762.0,41563.0,189207.0,1641.55,15.17,47.0,M-SC,24.36,220.0,0.35,1.27,42.35,OX40N,ATH,CABLES
91,ZYDUSLIFE,0.90,17.64,15.29,35.63,37697.0,36974.0,246548.0,1286.17,2.25,75.0,H-MC,11.77,120.0,0.98,1.66,29.63,AR,ATH,PHARMA
73,SONACOMS,-1.17,2.90,35.17,39.09,36608.0,2931.0,104090.0,804.02,-18.44,51.0,M-MC,18.55,193.0,0.08,0.70,47.25,AR,ATH,AUTO

In [16]:
# top 5 to book for rotation from weak conviction
df_tmp = df_portfolio_features[~df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])]
df_tmp = df_tmp[~df_tmp['Criteria'].isin(['XY25','XY24','X40', 'X40N'])].sort_values(by = 'RRR Ind', ascending=False)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
91,ZYDUSLIFE,0.90,17.64,15.29,35.63,37697.0,36974.0,246548.0,1286.17,2.25,75.0,H-MC,11.77,120.0,0.98,1.66,29.63,AR,ATH,PHARMA
25,FINCABLES,-1.97,28.15,62.24,107.91,117762.0,41563.0,189207.0,1641.55,15.17,47.0,M-SC,24.36,220.0,0.35,1.27,42.35,OX40N,ATH,CABLES
73,SONACOMS,-1.17,2.90,35.17,39.09,36608.0,2931.0,104090.0,804.02,-18.44,51.0,M-MC,18.55,193.0,0.08,0.70,47.25,AR,ATH,AUTO
75,SURYODAY,-0.31,-0.65,23.84,23.03,42413.0,-1163.0,177908.0,216.00,92.98,67.0,H-SC,17.99,166.0,-0.03,1.20,49.79,XR,NTT,BANKS
42,INDIAMART,-0.13,-13.71,139.57,106.72,148536.0,-16912.0,106424.0,4810.62,-61.13,46.0,H-SC,11.04,140.0,-0.11,0.72,3.03,AR,ATH,MISC

In [17]:
# top 5 to accumulate based on lowest RSI_14
df_tmp = df_portfolio_features[df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])].sort_values(by = 'RSI_14', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
35,HDFCLIFE,0.17,-8.16,45.01,33.18,61925.0,-12220.0,137580.0,814.30,-28.33,30.0,X-LC,15.47,31.0,-0.20,0.93,0.17,X40,ATH,INSURANCE
40,ICICIPRULI,0.05,-21.40,65.74,30.28,101798.0,-42155.0,154850.0,787.27,-42.46,31.0,X-MC,15.62,78.0,-0.41,1.04,0.05,X40,ATH,INSURANCE
58,PGHH,0.51,-31.97,94.04,32.01,136606.0,-68256.0,145264.0,17616.87,-53.97,33.0,X-MC,18.83,57.0,-0.50,0.98,0.51,X40,ATH,FMCG
65,RELIANCE,0.65,-18.00,52.81,25.30,87023.0,-36178.0,164785.0,1952.00,-20.03,34.0,X-LC,6.91,21.0,-0.42,1.11,1.12,XY25,BTT,REFINERIES
27,GLAXO,-0.65,-12.47,55.02,35.69,95977.0,-24844.0,174440.0,3380.16,-33.11,35.0,X-MC,8.83,56.0,-0.26,1.17,0.76,X40,ATH,PHARMA

In [18]:
# top 5 to accumulate based on Spread and CumlRnk
df_tmp = df_portfolio_features[df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])]
df_tmp = df_tmp[(df_tmp['CumlRnk'] < 100)].sort_values(by = 'Spread%', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
49,JSWINFRA,0.23,-3.50,20.66,16.43,44213.0,-7769.0,214005.0,342.00,-17.17,58.0,X-MC,3.12,61.0,-0.18,1.44,20.97,X40N,NTT,REALTY
57,PAGEIND,-0.42,1.04,32.21,33.59,87347.0,2801.0,271180.0,51217.29,-27.52,59.0,X-MC,3.15,55.0,0.03,1.82,28.78,X40,ATH,APPARELS
15,CAMS,-0.36,-2.12,27.18,24.48,67001.0,-5346.0,246510.0,950.00,-6.24,44.0,X-SC,3.70,89.0,-0.08,1.66,20.01,X40N,NTT,MISC
19,COLPAL,2.64,-21.14,77.35,39.86,160648.0,-55675.0,207690.0,3683.41,-4.51,54.0,X-MC,3.75,62.0,-0.35,1.40,17.48,XY25,ATH,FMCG
59,PIDILITIND,2.46,7.59,10.02,18.37,15212.0,10710.0,151820.0,1670.26,-24.63,66.0,X-LC,4.01,5.0,0.70,1.02,19.21,X40,ATH,CHEMICALS

In [19]:
# top 5 to accumulate based on lowest Gained%
df_tmp = df_portfolio_features[df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])].sort_values(by = 'Gained%', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
40,ICICIPRULI,0.05,-21.40,65.74,30.28,101798.0,-42155.0,154850.0,787.27,-42.46,31.0,X-MC,15.62,78.0,-0.41,1.04,0.05,X40,ATH,INSURANCE
35,HDFCLIFE,0.17,-8.16,45.01,33.18,61925.0,-12220.0,137580.0,814.30,-28.33,30.0,X-LC,15.47,31.0,-0.20,0.93,0.17,X40,ATH,INSURANCE
58,PGHH,0.51,-31.97,94.04,32.01,136606.0,-68256.0,145264.0,17616.87,-53.97,33.0,X-MC,18.83,57.0,-0.50,0.98,0.51,X40,ATH,FMCG
79,TCS,0.66,-36.44,96.48,24.88,284089.0,-168819.0,294454.0,4253.91,-46.25,38.0,X-LC,18.77,2.0,-0.59,1.98,0.66,X40,ATH,IT
27,GLAXO,-0.65,-12.47,55.02,35.69,95977.0,-24844.0,174440.0,3380.16,-33.11,35.0,X-MC,8.83,56.0,-0.26,1.17,0.76,X40,ATH,PHARMA

In [20]:
# top 5 to accumulate based on lowest CurrAlloc%
df_tmp = df_portfolio_features[df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])].sort_values(by = 'CurrAlloc%', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
10,BATAINDIA,0.70,-56.59,211.46,35.20,118111.0,-72815.0,55855.0,2096.00,-26.79,43.0,X-SC,25.49,91.0,-0.62,0.38,10.77,X40,NTT,FOOTWEAR
64,RELAXO,-1.02,-55.51,242.31,52.31,156501.0,-80573.0,64587.0,1176.00,-52.67,63.0,X-SC,20.67,92.0,-0.51,0.43,44.41,X40N,NTT,FOOTWEAR
60,QUESS,1.85,-0.93,75.53,73.90,79910.0,-994.0,105799.0,424.00,-46.56,75.0,X-SC,4.86,80.0,-0.01,0.71,44.23,XY24,NTT,MISC
53,M&M,-0.25,-3.22,27.49,23.38,36896.0,-4464.0,134217.0,3802.40,-17.91,41.0,X-LC,10.45,25.0,-0.12,0.90,1.76,X40N,ATH,AUTO
28,GODREJCP,1.46,-8.00,42.90,31.47,58655.0,-11890.0,136724.0,1469.04,-3.15,51.0,X-LC,9.93,32.0,-0.20,0.92,4.91,X40N,ATH,FMCG

In [21]:
# top 5 to accumulate based on CumlRnk
df_tmp = df_portfolio_features.sort_values(by = 'CumlRnk', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
47,ITC,1.46,-25.17,59.10,19.06,150441.0,-85612.0,254554.0,452.00,-58.75,42.0,X-LC,14.93,1.0,-0.57,1.71,2.56,X40,NTT,FMCG
79,TCS,0.66,-36.44,96.48,24.88,284089.0,-168819.0,294454.0,4253.91,-46.25,38.0,X-LC,18.77,2.0,-0.59,1.98,0.66,X40,ATH,IT
45,INFY,-0.10,-21.43,70.87,34.24,174215.0,-67065.0,245823.0,1972.00,-38.32,47.0,X-LC,17.16,3.0,-0.38,1.65,7.68,X40,NTT,IT
81,TMPV,-0.44,-12.11,55.40,36.58,173259.0,-43100.0,312741.0,600.00,-81.44,57.0,X-LC,15.72,4.0,-0.25,2.10,30.35,XY24,NTT,AUTO
59,PIDILITIND,2.46,7.59,10.02,18.37,15212.0,10710.0,151820.0,1670.26,-24.63,66.0,X-LC,4.01,5.0,0.70,1.02,19.21,X40,ATH,CHEMICALS

In [22]:
# top 5 for average up
df_tmp = df_portfolio_features[(df_portfolio_features['Dev%_200'] > 5)].sort_values(by = 'CurrAlloc%', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
44,INDUSINDBK,-1.56,-32.93,98.15,32.89,50821.0,-25428.0,51779.0,1800.00,-343.70,51.0,L-MC,7.41,258.0,-0.50,0.35,27.45,XR,NTT,BANKS
3,ALKYLAMINE,-1.03,-21.96,148.12,93.63,116702.0,-22174.0,78789.0,4546.37,-16.40,61.0,H-SC,9.44,142.0,-0.19,0.53,48.77,SR,ATH,CHEMICALS
24,EASEMYTRIP,8.26,-52.98,209.86,45.70,174473.0,-93677.0,83138.0,26.40,-13.69,65.0,M-SC,5.18,204.0,-0.54,0.56,45.64,XY24,NTT,TRAVEL
73,SONACOMS,-1.17,2.90,35.17,39.09,36608.0,2931.0,104090.0,804.02,-18.44,51.0,M-MC,18.55,193.0,0.08,0.70,47.25,AR,ATH,AUTO
60,QUESS,1.85,-0.93,75.53,73.90,79910.0,-994.0,105799.0,424.00,-46.56,75.0,X-SC,4.86,80.0,-0.01,0.71,44.23,XY24,NTT,MISC

In [23]:
# top 5 RSP
df_tmp = df_portfolio_features.sort_values(by = 'RSP', ascending=False)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
18,COFFEEDAY,-2.76,-42.85,136.69,35.27,88706.0,-48653.0,64896.0,80.00,-55.73,57.0,L-SC,18.09,266.0,-0.55,0.44,60.04,XR,NTT,HOTELS
37,HONAUT,3.20,-6.01,60.99,51.31,110544.0,-11588.0,181250.0,58357.33,-21.90,68.0,X-SC,6.79,90.0,-0.10,1.22,37.70,X40N,ATH,ELECTRICAL
69,SFL,4.20,-30.19,81.40,26.63,149004.0,-79167.0,183051.0,1287.00,38.71,77.0,M-SC,8.98,242.0,-0.53,1.23,52.56,XY24,NTT,MISC
91,ZYDUSLIFE,0.90,17.64,15.29,35.63,37697.0,36974.0,246548.0,1286.17,2.25,75.0,H-MC,11.77,120.0,0.98,1.66,29.63,AR,ATH,PHARMA
81,TMPV,-0.44,-12.11,55.40,36.58,173259.0,-43100.0,312741.0,600.00,-81.44,57.0,X-LC,15.72,4.0,-0.25,2.10,30.35,XY24,NTT,AUTO

In [24]:
# Top N allocation
df_tmp = df_portfolio_features.sort_values(by = 'CurrAlloc%', ascending=False)
top_n_values = [10, 25, 50]

sum_df = pd.DataFrame({
    'Top_N': top_n_values,
    'Sum_Alloc%': [df_tmp['CurrAlloc%'].head(n).sum() for n in top_n_values]
})

sum_df

   Top_N  Sum_Alloc%
0     10       19.67
1     25       42.84
2     50       72.81

In [25]:
# market-cap-wise allocation
df_tmp = df_portfolio_features[cols]
df_tmp.groupby(df_tmp['Conviction'].str[-2:])['CurrAlloc%'].sum().sort_values(ascending=False)

Conviction
SC    43.10
LC    31.19
MC    25.67
Name: CurrAlloc%, dtype: float64

In [26]:
# criteria-wise allocation
df_portfolio_features.groupby('Criteria')['CurrAlloc%'].sum().sort_values(ascending=False)

Criteria
XY24     27.94
X40      24.82
X40N     17.11
XR        8.87
OX40N     6.86
AR        6.86
XY25      6.61
SR        0.89
Name: CurrAlloc%, dtype: float64

In [27]:
# conviction-wise allocation
df_portfolio_features.groupby('Conviction')['CurrAlloc%'].sum().sort_values(ascending=False)

Conviction
X-LC    29.13
H-SC    22.63
X-MC    20.52
M-SC    10.02
X-SC     9.86
H-MC     2.79
M-MC     2.01
H-LC     1.21
M-LC     0.85
L-SC     0.59
L-MC     0.35
Name: CurrAlloc%, dtype: float64

In [28]:
# sector-wise stats
df_tmp = df_portfolio_features.groupby('Category')[['CurrAlloc%', 'Current', 'Current P/L', 'FTT Amt']].sum().sort_values(by=['Current', 'Current P/L'], ascending=False)
df_tmp['Current P/L%'] = round(df_tmp['Current P/L'] * 100 / df_tmp['Current'], 2)
df_tmp['FTT%'] = round(df_tmp['FTT Amt'] * 100 / df_tmp['Current'], 2)
cols = ['CurrAlloc%', 'Current P/L%', 'FTT%']
df_tmp[cols].sort_values(by=['CurrAlloc%'], ascending=False)

               CurrAlloc%  Current P/L%    FTT%
Category
FMCG                14.99        -18.71   60.35
FINANCE             10.88        -14.06   63.67
IT                  10.09        -50.43  125.65
MISC                 7.15        -26.18   81.00
AUTO                 6.78         -8.58   49.28
BANKS                5.75         -6.26   55.39
PAINTS               5.64        -17.49   37.90
INSURANCE            5.15         -8.27   44.88
PHARMA               5.05          1.37   29.16
ELECTRICAL           4.06        -17.11   58.44
CHEMICALS            2.19        -24.55   98.78
HEALTHCARE           2.04        -17.56   48.24
AC                   1.83        -17.23   49.02
APPARELS             1.82          1.03   32.21
FOOTWEAR             1.72        -72.69  141.93
TRAVEL               1.69        -78.05  167.20
DURABLES             1.56        -66.38  106.86
BREWERIES            1.47         -7.39   29.69
REALTY               1.44         -3.63   20.66
CERAMICS             1.37        -50.92   96.77
ENGINEERING          1.28        -26.90   84.95
CABLES               1.27         21.97   62.24
REFINERIES           1.11        -21.95   52.81
CEMENT               1.07        -69.23  195.84
JEWELLERY            1.00       -114.59  189.15
ENTERTAINMENT        0.72        -79.66  186.81
HOTELS               0.44        -74.97  136.69
TEXTILES             0.40        -54.98   99.17

In [29]:
# money to be made criteria-wise
df_portfolio_features.groupby('Criteria')['FTT Amt'].agg(['sum', 'count']).sort_values(by='sum', ascending=False)

                sum  count
Criteria
XY24      3440868.0     21
X40       1992912.0     19
XR        1363621.0     13
X40N      1179319.0     13
AR        1166450.0      9
OX40N      770498.0     10
XY25       453727.0      5
SR         287437.0      2

In [30]:
# money to be made conviction-wise
df_portfolio_features.groupby('Conviction')['FTT Amt'].agg(['sum', 'count']).sort_values(by='sum', ascending=False)

                  sum  count
Conviction
H-SC        3422573.0     24
X-LC        1956774.0     21
X-MC        1667283.0     15
M-SC        1425994.0     14
X-SC        1337141.0      9
H-MC         283294.0      2
L-SC         203542.0      2
M-LC         166096.0      1
M-MC          87980.0      2
H-LC          53334.0      1
L-MC          50821.0      1

In [31]:
# money to be made criteria and conviction-wise
df_portfolio_features.groupby(['Conviction', 'Criteria'])['FTT Amt'].agg(['sum', 'count']).sort_values(by='sum', ascending=False)

                           sum  count
Conviction Criteria
X-LC       X40       1062868.0     10
H-SC       XY24      1034132.0      6
           AR         961899.0      5
M-SC       XY24       819672.0      6
H-SC       XR         816770.0      7
X-SC       XY24       789324.0      4
X-MC       X40        716273.0      7
           X40N       482334.0      4
X-LC       X40N       362939.0      6
X-SC       X40N       334046.0      3
M-SC       OX40N      333327.0      5
X-LC       XY24       325768.0      2
H-SC       OX40N      322335.0      4
           SR         287437.0      2
H-MC       XY24       245597.0      1
X-MC       XY25       242301.0      2
           XY24       226375.0      2
X-SC       X40        213771.0      2
M-SC       XR         196083.0      2
M-LC       XR         166096.0      1
X-LC       XY25       160054.0      2
L-SC       OX40N      114836.0      1
           XR          88706.0      1
M-SC       AR          76912.0      1
H-LC       AR          53334.0      1
M-MC       XY25        51372.0      1
L-MC       XR          50821.0      1
X-LC       XR          45145.0      1
H-MC       AR          37697.0      1
M-MC       AR          36608.0      1

In [32]:
# notebook execution time

end_time = time.time()
execution_time = round(end_time - start_time, 0)
print(f"Notebook execution time: {execution_time} seconds")

Notebook execution time: 37.0 seconds