<a href="https://colab.research.google.com/github/ankit-rathi/Quantvesting_v2/blob/main/myStocks_Portfolio_Analysis.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
'''
!pip install pandas==2.2.2 -qq
!pip install pyxirr -qq
!pip install ta -qq
!pip install yfinance==0.2.59 -qq
'''

'\n!pip install pandas==2.2.2 -qq\n!pip install pyxirr -qq\n!pip install ta -qq\n!pip install yfinance==0.2.59 -qq\n'

In [2]:
# import libraries

import numpy as np
import pandas as pd
import datetime
import warnings
warnings.filterwarnings('ignore')
import yfinance as yfin
import ta
import matplotlib.pyplot as plt
import requests

In [3]:
# notebook start time
import time
import datetime
import pytz

start_time = time.time()

# function to print date timestamp
def print_date_time():
  tz_NY = pytz.timezone('Asia/Kolkata')
  datetime_NY = datetime.datetime.now(tz_NY)
  print("Run date time (IST):", datetime_NY.strftime("%Y-%m-%d %H:%M:%S"))

In [4]:
# function to get booked and reserved amount
def get_amt():
  # fetch the JSON data from the URL
  url = "https://raw.githubusercontent.com/ankit-rathi/Tradevesting_v1/main/data/myPortfolioAmts.json"
  response = requests.get(url)
  pf_amts = response.json()  # parse the JSON data

  # extract values from the JSON
  py_booked_amt_dm = pf_amts["py_booked_amt_dm"]
  py_booked_amt_sv = pf_amts["py_booked_amt_sv"]
  cy_booked_amt_dm = pf_amts["cy_booked_amt_dm"]
  cy_booked_amt_sv = pf_amts["cy_booked_amt_sv"]
  reserve_amt_dm = pf_amts["reserve_amt_dm"]
  reserve_amt_sv = pf_amts["reserve_amt_sv"]

  # perform calculations
  py_booked_amt = py_booked_amt_dm + py_booked_amt_sv
  cy_booked_amt = cy_booked_amt_dm + cy_booked_amt_sv
  reserve_amt = reserve_amt_dm + reserve_amt_sv
  total_booked_amt = py_booked_amt + cy_booked_amt

  return total_booked_amt, reserve_amt, cy_booked_amt, py_booked_amt

gen_output = 0

In [5]:
# function to format the amount
def format_amt(number):
    abs_number = abs(number)

    if abs_number >= 1_00_00_000:  # Crores
        formatted_amt = f"{number / 1_00_00_000:.2f} C"
    elif abs_number >= 1_00_000:  # Lakhs
        formatted_amt = f"{number / 1_00_000:.2f} L"
    elif abs_number >= 1_000:  # Thousands
        formatted_amt = f"{number / 1_000:.2f} K"
    else:
        formatted_amt = f"{number:.2f}"

    return formatted_amt

# function to set start and end date
def get_start_end_date():
  start_date = (datetime.date.today() + datetime.timedelta(days=-365)).strftime('%Y-%m-%d')
  end_date = (datetime.date.today() + datetime.timedelta(days=1)).strftime('%Y-%m-%d')
  return start_date, end_date

# function to fetch my portfolio csv
def get_mypfs_df():
  mypfs_df = pd.read_csv('https://raw.githubusercontent.com/ankit-rathi/Tradevesting_v1/main/data/myPortfolioStocks.csv')
  return mypfs_df

# function to fetch my prospects csv
def get_mypps_df():
  mypps_df = pd.read_csv('https://raw.githubusercontent.com/ankit-rathi/Tradevesting_v1/main/data/myProspectsScrips.csv')
  return mypps_df

# function to fetch screener data
def get_myscreen_df():
  myscreen_df = pd.read_csv('https://raw.githubusercontent.com/ankit-rathi/Tradevesting_v1/main/data/myScreenerDB.csv')
  return myscreen_df

# function to fetch momentum data
def get_myinvmt_df():
  myinvmt_df = pd.read_csv('https://raw.githubusercontent.com/ankit-rathi/Tradevesting_v1/main/data/myInvestments.csv')
  return myinvmt_df

# function to get the stock ids
def get_stock_ids(df_pf):
  stock_n100 = df_pf['Symbol'].unique()

  exclude = ['CADILAHC','MMTC', 'MASFIN']

  stock_ids = df_pf[~df_pf['Symbol'].isin(exclude) ]['Symbol'].unique()

  #mypf = mypf[mypf.Forecast.notnull()]
  #stock_ids = mypf['Symbol'].unique()

  #stock_ids.sort()
  return stock_ids

# get features from screener data
def get_screener_features():
  myscreen_df = get_myscreen_df()
  cols = ['Symbol', 'EPS', 'MedPE', 'ROCE%', 'ROE%', 'CapType']
  return myscreen_df[cols]

# get relative strength
def get_relative_strength(stock_list):

    # Dictionary to store stock tickers and their corresponding percentage price change
    stock_changes = {}

    # Loop through each stock and fetch its price data
    for stock in stock_list:
        try:
            # Download the stock data for the given date range
            stock_data = yfin.Ticker(stock + '.NS').history(period='1mo', interval='1d')[map(str.title, ['open', 'close', 'low', 'high', 'volume'])]

            # Calculate the percentage change for the stock
            if len(stock_data) > 0:
                start_price = stock_data['Close'].iloc[0]
                end_price = stock_data['Close'].iloc[-1]
                percent_change = round(((end_price - start_price) / start_price) * 100, 2)
                stock_changes[stock] = percent_change
            else:
                stock_changes[stock] = np.nan  # If no data is available, set to NaN

        except Exception as e:
            print(f"Error fetching data for {stock}: {e}")
            stock_changes[stock] = np.nan

    # Create a DataFrame with stock tickers and their percentage changes
    df = pd.DataFrame(list(stock_changes.items()), columns=['Symbol', 'Percent_Change'])

    # Drop any stocks with missing data (NaN values)
    df = df.dropna()

    # Calculate the percentile rank based on percentage change
    df['RSP'] = round(df['Percent_Change'].rank(pct=True) * 100, 2)
    cols = ['Symbol', 'RSP']
    df = df[cols]
    # Sort by percentile rank (optional)
    df = df.sort_values(by='RSP', ascending=False).reset_index(drop=True)

    return df

In [6]:
# function to get stock technicals
def stock_prec_dev(stock_symbol):
    #stock_symbol = 'ULTRACEMCO.NS'
    short_window = 20
    mid_window = 50
    long_window = 200
    moving_avg = 'SMA'

    start = datetime.datetime(*map(int, start_date.split('-')))
    end = datetime.datetime(*map(int, end_date.split('-')))

    stock_df = yfin.Ticker(stock_symbol + '.NS').history(period='max', interval='1d')[map(str.title, ['open', 'close', 'low', 'high', 'volume'])]

    stock_df['Max'] = round(max(stock_df['Close']),2)
    stock_df = stock_df[(stock_df.index <= end_date) & (stock_df.index >= start_date)]
    stock_df['200_SMA'] = round(stock_df['Close'].rolling(window = 200, min_periods = 1).mean(),0)
    stock_df['Dev%_200'] = round((stock_df['Close'] - stock_df['200_SMA'])*100/stock_df['200_SMA'],2)
    stock_df.dropna(axis = 0, inplace = True) # remove any null rows

    stock_df['20_SMA'] = stock_df['Close'].rolling(window=20).mean()
    stock_df['50_SMA'] = stock_df['Close'].rolling(window=50).mean()
    stock_df['Symbol'] = stock_symbol

    stock_df['Close'] = round(stock_df['Close'],2)
    stock_df['Min'] = round(min(stock_df['Close']),2)
    stock_df['RSI_14'] = ta.momentum.RSIIndicator(close=stock_df['Close'], window=14).rsi()
    stock_df['RSI_14'] = round(stock_df['RSI_14'],0)
    stock_df['Prev_Close'] = stock_df['Close'].shift(1)
    stock_df.drop(['Open', 'Low', 'High', 'Volume'], axis=1, inplace=True)
    stock_df = stock_df.tail(1)

    max_SMA = max(stock_df['20_SMA'].item(), stock_df['50_SMA'].item(), stock_df['200_SMA'].item())
    min_SMA = min(stock_df['20_SMA'].item(), stock_df['50_SMA'].item(), stock_df['200_SMA'].item())
    ABS_Spread = max_SMA - min_SMA
    stock_df['Spread%'] = round((ABS_Spread / stock_df['200_SMA'].item()) * 100,2)

    return stock_df

# function to compute stock attributes
def get_common_features(stock_ids, df_mypf):

  df_prec_dev = pd.DataFrame()
  df_tmp = get_screener_features()
  df_rs = get_relative_strength(stock_ids)

  for stock_id in stock_ids:
      tmp = stock_prec_dev(stock_id)
      tmp = tmp.reset_index()
      df_prec_dev = pd.concat([df_prec_dev, tmp], ignore_index = True)
  df_prec_dev = pd.merge(df_prec_dev, df_mypf, on= 'Symbol')
  df_prec_dev = pd.merge(df_prec_dev, df_tmp, on= 'Symbol', how='left')
  df_prec_dev = pd.merge(df_prec_dev, df_rs, on= 'Symbol', how='left')
  #print(df_prec_dev.columns)
  df_prec_dev['Curr_PE'] = round(df_prec_dev['Close']/df_prec_dev['EPS'],1)
  df_prec_dev['Dev%_PE'] = round((df_prec_dev['Curr_PE'] - df_prec_dev['MedPE'])*100/df_prec_dev['MedPE'],2)
  df_prec_dev['Conviction'] = df_prec_dev['Conviction'] + '-' + df_prec_dev['CapType']
  return df_prec_dev

# function to arrange stock features
def arrange_features(df_stocks, common_cols, diff_cols):
  df_stocks_common = df_stocks[common_cols].drop_duplicates()
  df_stocks_diff = df_stocks[diff_cols]
  df_stocks_diff['Investment'] = df_stocks_diff['AvgCost'] * df_stocks_diff['Shares']
  df_stocks_diff = df_stocks_diff.groupby(['Symbol'])[['Shares', 'Investment']].aggregate(['sum']).reset_index()
  df_stocks_diff.columns = ['Symbol', 'Shares', 'Investment']
  df_stocks_diff['AvgCost'] = round(df_stocks_diff['Investment']/df_stocks_diff['Shares'],2)
  df_stocks = pd.merge(df_stocks_diff, df_stocks_common, on='Symbol')
  return df_stocks

# plot fact distribution across dimension
def plot_pie_chart(df, dimension, fact):
  # grouping the data by category and calculating the sum of fact for each type
  grouped_data = df.groupby(dimension)[fact].sum()

  # sorting the grouped data in descending order
  grouped_data = grouped_data.sort_values(ascending=False)

  # creating a pie chart
  grouped_data.plot.pie(autopct='%1.1f%%', startangle=90, figsize=(6, 6))

  # adding a title and displaying the plot
  plt.title(f'{dimension} {fact} Distribution')
  plt.ylabel('')  # To hide the y-label
  plt.show()

In [7]:
# function to get portfolio features

def get_portfolio_features(df_common_features):

  print_date_time()
  print('-------------------')

  #df_common_features["Target"] = df_common_features["Target"].fillna(df_common_features["Max"])
  df_common_features['NTT'] = np.where(df_common_features['Strategy']== 'NTT', df_common_features["Target"], df_common_features['Max'])
  df_common_features['LTT'] = np.where(df_common_features['Strategy']== 'BTT', df_common_features["Target"], df_common_features['Max'])
  df_common_features['BOL'] = df_common_features['Min']

  tmp_df = df_common_features[df_common_features['Symbol'].isin(mypf_df[mypf_df['InPortfolio'] != 'NA'].Symbol.values)]
  print('qualified stocks: '+str(len(tmp_df['Symbol'].unique())))
  tmp_df1 = tmp_df[tmp_df['LatestQtr'] == 1]
  print('with latest results: '+str(len(tmp_df1['Symbol'].unique())))
  tmp_df1 = tmp_df1[tmp_df1['StarStock'] == 1]
  print('still star stocks: '+str(len(tmp_df1['Symbol'].unique())))
  tmp_df['Investment'] = tmp_df['AvgCost'] * tmp_df['Shares']
  tmp_df['Current'] = round(tmp_df['Close'] * tmp_df['Shares'],0)
  tmp_df['Previous'] = tmp_df['Prev_Close'] * tmp_df['Shares']
  tmp_df['EstimatedST'] = tmp_df['NTT'] * tmp_df['Shares']
  tmp_df['EstimatedLT'] = tmp_df['LTT'] * tmp_df['Shares']
  tmp_df['Current P/L'] = round((tmp_df['Current'] - tmp_df['Investment']),0)
  tmp_df['Today P/L%'] = round((tmp_df['Current'] - tmp_df['Previous'])*100/tmp_df['Previous'],2)
  tmp_df['Current P/L%'] = round((tmp_df['Current'] - tmp_df['Investment'])*100/tmp_df['Investment'],2)
  tmp_df['EstimatedST P/L%'] = round((tmp_df['EstimatedST'] - tmp_df['Investment'])*100/tmp_df['Investment'],2)
  tmp_df['EstimatedLT P/L%'] = round((tmp_df['EstimatedLT'] - tmp_df['Investment'])*100/tmp_df['Investment'],2)
  tmp_df['NTT%'] = round((tmp_df['NTT'] - tmp_df['Close'])*100/tmp_df['Close'],2)
  tmp_df['LTT%'] = round((tmp_df['LTT'] - tmp_df['Close'])*100/tmp_df['Close'],2)
  tmp_df['Gained%'] = round((tmp_df['Close'] - tmp_df['BOL'])*100/tmp_df['BOL'],2)
  investment = round(sum(tmp_df['AvgCost']*tmp_df['Shares']),0)
  current = round(sum(tmp_df['Close']*tmp_df['Shares']),0)
  tmp_df['InitAlloc%'] = round(tmp_df['Investment']*100/investment,2)
  tmp_df['CurrAlloc%'] = round(tmp_df['Current']*100/current,2)
  tmp_df['FTT'] = tmp_df['LTT']
  tmp_df.loc[tmp_df['Strategy'] == 'NTT', 'FTT'] = tmp_df['NTT']
  tmp_df['FTT%'] = tmp_df['LTT%']
  tmp_df.loc[tmp_df['Strategy'] == 'NTT', 'FTT%'] = tmp_df['NTT%']
  tmp_df['FTT Amt'] = round(tmp_df['FTT%'] * tmp_df['Current']/100,0)
  tmp_df['OTT%'] = round((tmp_df['FTT'] - tmp_df['AvgCost'])*100/tmp_df['AvgCost'],2)
  tmp_df['RRR Ind'] = round(tmp_df['Current P/L']/tmp_df['FTT Amt'],2)
  tmp_df['Risk Ind'] = round(tmp_df['Current P/L%']*tmp_df['CurrAlloc%'],0)

  return tmp_df

# function to print portfolio features
def print_portfolio_stats(df_portfolio_features, myinvmt_df):
  from pyxirr import xirr

  total_booked_amt, reserve_amt, cy_booked_amt, py_booked_amt = get_amt()

  dates = myinvmt_df['Date'].values
  dates = np.append(dates, datetime.date.today().strftime('%d-%b-%y'))
  investment = myinvmt_df['Investment'].values
  dates= pd.to_datetime(dates)

  current = round(sum(df_portfolio_features['Close']*df_portfolio_features['Shares']),0) + reserve_amt
  investment_xirr = np.append(investment, current)
  cagr = round(xirr(pd.DataFrame({"dates": dates, "amounts": investment_xirr}))*100,2)

  investment = -sum(investment)
  invested = round(sum(df_portfolio_features['AvgCost']*df_portfolio_features['Shares']),0) + reserve_amt
  previous = round(sum(df_portfolio_features['Prev_Close']*df_portfolio_features['Shares']),0) + reserve_amt
  cy_invested = investment + py_booked_amt

  today_pnl_amount = current-previous
  today_pnl_percentage = round((current-previous)*100/previous,2)

  curr_pnl_amount = current-invested
  curr_pnl_percentage = round((curr_pnl_amount)*100/(cy_invested),2)

  cy_pnl_amount = cy_booked_amt + curr_pnl_amount
  cy_pnl_percentage = round((cy_pnl_amount)*100/cy_invested,2)

  overall_pnl_amount = total_booked_amt + curr_pnl_amount
  overall_pnl_percentage = round((overall_pnl_amount)*100/investment,2)

  estimate_st = round(sum(df_portfolio_features['FTT']*df_portfolio_features['Shares']),0)  + reserve_amt
  est_st_pnl_amount = estimate_st-current
  est_st_pnl_percentage = round((est_st_pnl_amount)*100/current,2)

  estimate_lt = round(sum(df_portfolio_features['LTT']*df_portfolio_features['Shares']),0)  + reserve_amt
  est_lt_pnl_amount = estimate_lt-current
  est_lt_pnl_percentage = round((est_lt_pnl_amount)*100/current,2)

  total_profit = round(sum(df_portfolio_features[df_portfolio_features['Current P/L%'] > 0]['Current']) - sum(df_portfolio_features[df_portfolio_features['Current P/L%'] > 0]['Investment']),0)
  total_loss = round(sum(df_portfolio_features[df_portfolio_features['Current P/L%'] < 0]['Current']) - sum(df_portfolio_features[df_portfolio_features['Current P/L%'] < 0]['Investment']),0)

  cy_booked_percentage = round((cy_booked_amt)*100/current,2)
  py_booked_percentage = round((py_booked_amt)*100/investment,2)
  total_booked_percentage = round((total_booked_amt)*100/investment,2)

  print('-------------------')
  print('Initial Investment: ', format_amt(investment))
  print('CY Investment: ', format_amt(cy_invested))
  print('Reserve: ', format_amt(reserve_amt))
  print('Current: ',  format_amt(current))
  print('-------------------')
  print('Today PnL: '+ '{} ({}%)'.format(format_amt(today_pnl_amount), today_pnl_percentage))
  print('Current PnL: '+ '{} ({}%)'.format(format_amt(curr_pnl_amount), curr_pnl_percentage))
  print('CY Booked + Current PnL: '+ '{} ({}%)'.format(format_amt(cy_pnl_amount), cy_pnl_percentage))
  print('-------------------')
  print('Total profit: ', format_amt(total_profit))
  print('Total loss: ', format_amt(total_loss))
  print('-------------------')
  print('Total Booked + Current PnL: '+ '{} ({}%)'.format(format_amt(overall_pnl_amount), overall_pnl_percentage))
  print('Total Booked PnL: '+ '{} ({}%)'.format(format_amt(total_booked_amt), total_booked_percentage))
  print('Curr Year Booked PnL: '+ '{} ({}%)'.format(format_amt(cy_booked_amt), cy_booked_percentage))
  print('Prev Year Booked PnL: '+ '{} ({}%)'.format(format_amt(py_booked_amt), py_booked_percentage))
  print('===================')
  print('Est FTT: ',  format_amt(estimate_st))
  print('Est FTT PnL: '+ '{} ({}%)'.format(format_amt(est_st_pnl_amount), est_st_pnl_percentage))

  print('===================')
  print('Deployed: ', format_amt(investment))

  print('Current: ', format_amt(current))

  print('CAGR/XIRR %: '+'{}%'.format(cagr))

In [8]:
# get start and end date
start_date, end_date = get_start_end_date()

# get portfolio and prospects data
mypfs_df = get_mypfs_df()
mypps_df = get_mypps_df()
myinvmt_df = get_myinvmt_df()

# merge above datasets
mypf_df = pd.merge(mypfs_df, mypps_df, on="Symbol")

# seggregate dm and sv portfolio
dm_pf = mypf_df[mypf_df['InPortfolio'] == 'DM']
sv_pf = mypf_df[mypf_df['InPortfolio'] == 'SV']

# build portfolio stock dataframe
dm_stocks = get_stock_ids(dm_pf)
sv_stocks = get_stock_ids(sv_pf)
df_stocks = pd.concat([dm_pf,sv_pf], ignore_index = True)

# arrange common and diff stock features
common_cols = ['Symbol', 'Target', 'Criteria', 'Strategy', 'CumlRnk', 'LatestQtr', 'StarStock', 'Conviction', 'Category', 'InFolio', 'XIRR', 'MBQ']
diff_cols = ['Symbol', 'AvgCost', 'Shares']
df_stocks = arrange_features(df_stocks, common_cols, diff_cols)

# get common features
stock_ids = df_stocks['Symbol'].values
df_common_features = get_common_features(stock_ids, df_stocks)

df_common_features.reset_index(drop=True, inplace=True)
df_common_features.drop(['Date'], axis=1, inplace=True)
# get and print portfolio features
df_portfolio_features = get_portfolio_features(df_common_features)

print_portfolio_stats(df_portfolio_features, myinvmt_df)

df = df_portfolio_features
#plot_pie_chart(df, 'CapType', 'Current')
list_ox40n = list(df[df['MBQ'].str.contains('OX40N', na=False)]['Symbol'].values)

Run date time (IST): 2026-05-26 15:48:33
-------------------
qualified stocks: 92
with latest results: 31
still star stocks: 20

-------------------
Initial Investment:  1.40 C
CY Investment:  1.82 C
Reserve:  1.49 K
Current:  1.50 C
-------------------
Today PnL: 38.46 K (0.26%)
Current PnL: -32.87 L (-18.02%)
CY Booked + Current PnL: -30.79 L (-16.88%)
-------------------
Total profit:  2.32 L
Total loss:  -35.19 L
-------------------
Total Booked + Current PnL: 12.08 L (8.66%)
Total Booked PnL: 44.95 L (32.22%)
Curr Year Booked PnL: 2.08 L (1.38%)
Prev Year Booked PnL: 42.87 L (30.73%)
===================
Est FTT:  2.55 C
Est FTT PnL: 1.05 C (69.87%)
===================
Deployed:  1.40 C
Current:  1.50 C
CAGR/XIRR %: 3.59%

In [9]:
# top 5 near their targets
cols = ['Symbol', 'Today P/L%', 'Current P/L%', 'FTT%', 'OTT%', 'FTT Amt', 'Current P/L', 'Current', 'FTT', 'Dev%_PE', 'RSI_14','Conviction', 'Spread%',  'CumlRnk', 'RRR Ind', 'CurrAlloc%', 'Gained%', 'Criteria', 'Strategy', 'Category']
df_tmp = df_portfolio_features[~df_portfolio_features['Symbol'].isin(['ENRIN','BLUSPRING','DIGITIDE'])]
df_tmp = df_tmp.sort_values(by = 'FTT Amt', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
59,PIDILITIND,0.09,4.78,12.97,18.37,19176.0,6740.0,147850.0,1670.26,-26.64,62.0,X-LC,5.31,5.0,0.35,0.98,16.09,X40,ATH,CHEMICALS
51,KOTAKBANK,-1.07,3.85,16.62,21.11,23900.0,5328.0,143800.0,453.24,-10.71,56.0,X-LC,7.80,12.0,0.22,0.96,9.97,X40,ATH,BANKS
55,MASFIN,0.31,-6.25,29.67,21.57,27255.0,-6120.0,91860.0,397.04,-19.15,37.0,H-SC,4.54,167.0,-0.22,0.61,9.49,XR,ATH,FINANCE
17,CIPLA,0.25,14.76,17.36,34.69,30514.0,22609.0,175770.0,1663.60,-11.14,65.0,X-LC,9.79,18.0,0.74,1.17,18.88,X40N,ATH,PHARMA
53,M&M,-1.01,0.83,22.37,23.38,31280.0,1147.0,139828.0,3802.40,-14.43,47.0,X-LC,8.98,25.0,0.04,0.93,6.01,X40N,ATH,AUTO

In [10]:
# top 5 today
df_tmp = df_portfolio_features.sort_values(by = 'Today P/L%', ascending=False)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
14,CAMPUS,6.12,-15.04,56.89,33.28,81088.0,-25241.0,142534.0,393.00,-31.57,60.0,M-SC,7.94,218.0,-0.31,0.95,14.46,XY24,NTT,FOOTWEAR
0,5PAISA,5.02,-36.03,76.49,12.90,106915.0,-78720.0,139776.0,593.00,105.53,61.0,H-SC,6.94,170.0,-0.74,0.93,34.89,OX40N,NTT,FINANCE
61,RAJESHEXPO,5.00,-77.12,337.32,0.07,105881.0,-105788.0,31389.0,518.00,1050.25,56.0,L-SC,32.26,268.0,-1.00,0.21,47.36,OX40N,NTT,JEWELLERY
37,HONAUT,3.39,-7.77,64.06,51.31,113931.0,-14988.0,177850.0,58357.33,-23.26,70.0,X-SC,10.74,90.0,-0.13,1.18,35.12,X40N,ATH,ELECTRICAL
81,TMPV,3.31,-12.23,55.60,36.58,173659.0,-43505.0,312336.0,600.00,-81.44,70.0,X-LC,5.85,4.0,-0.25,2.08,30.18,XY24,NTT,AUTO

In [11]:
# bottom 5 today
df_tmp = df_portfolio_features.sort_values(by = 'Today P/L%', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
83,TTKPRESTIG,-1.99,-33.34,50.16,0.09,33696.0,-33600.0,67177.0,770.0,55.82,47.0,M-SC,15.59,250.0,-1.00,0.45,19.62,OX40N,NTT,DURABLES
13,BSOFT,-1.93,-41.19,156.38,50.79,129361.0,-57931.0,82722.0,831.7,-24.62,38.0,H-SC,10.87,172.0,-0.45,0.55,4.78,XR,ATH,IT
80,TITAGARH,-1.87,-23.13,89.58,45.74,166774.0,-56004.0,186173.0,1548.0,2.48,61.0,H-SC,10.22,175.0,-0.34,1.24,42.05,XY24,NTT,ENGINEERING
56,MEDANTA,-1.64,5.12,20.93,27.12,38835.0,9032.0,185549.0,1486.0,1.93,61.0,X-SC,8.21,87.0,0.23,1.23,27.85,XY24,NTT,HEALTHCARE
90,WIPRO,-1.50,-16.44,106.16,72.27,150314.0,-27856.0,141592.0,420.0,-24.55,58.0,M-LC,13.44,98.0,-0.19,0.94,8.63,XR,NTT,IT

In [12]:
# top 5 to exit based on CumlRnk
df_tmp = df_portfolio_features[~df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])]
df_tmp = df_tmp[(df_tmp['Current P/L%'] > -1) & (df_tmp['Current P/L%'] < 1)].sort_values(by = 'CumlRnk', ascending=False)
df_tmp[cols].head()

Empty DataFrame
Columns: [Symbol, Today P/L%, Current P/L%, FTT%, OTT%, FTT Amt, Current P/L, Current, FTT, Dev%_PE, RSI_14, Conviction, Spread%, CumlRnk, RRR Ind, CurrAlloc%, Gained%, Criteria, Strategy, Category]
Index: []

In [13]:
# OX40N stocks to exit
df_tmp = df_portfolio_features[(df_portfolio_features['Symbol'].isin(list_ox40n))].sort_values(by = 'Current P/L%', ascending=False)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
25,FINCABLES,1.61,37.57,51.13,107.91,103850.0,55466.0,203110.0,1641.55,23.80,62.0,M-SC,26.12,220.0,0.53,1.35,52.81,OX40N,ATH,CABLES
72,SIS,2.25,-8.50,32.53,21.26,33048.0,-9440.0,101592.0,528.00,2417.62,65.0,H-SC,16.49,168.0,-0.29,0.68,51.05,OX40N,NTT,MISC
16,CERA,0.24,-24.91,64.98,23.89,85831.0,-43814.0,132089.0,9475.00,-27.45,58.0,H-SC,7.12,153.0,-0.51,0.88,26.94,OX40N,NTT,CERAMICS
50,KANSAINER,-0.27,-27.32,56.14,13.47,110025.0,-73683.0,195984.0,340.00,-37.50,61.0,H-SC,12.84,162.0,-0.67,1.30,36.90,XY24,NTT,PAINTS
43,INDIGOPNTS,-0.56,-29.65,42.17,0.02,51786.0,-51756.0,122803.0,1408.00,87.50,64.0,M-SC,18.29,222.0,-1.00,0.82,39.33,OX40N,NTT,PAINTS

In [14]:
# top 5 to book for rotation
df_tmp = df_portfolio_features[(df_portfolio_features['Current P/L%'] > 20) ].sort_values(by = 'CumlRnk', ascending=False)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
25,FINCABLES,1.61,37.57,51.13,107.91,103850.0,55466.0,203110.0,1641.55,23.80,62.0,M-SC,26.12,220.0,0.53,1.35,52.81,OX40N,ATH,CABLES
68,SATIN,3.08,23.52,22.92,51.83,78220.0,64991.0,341275.0,274.00,10.38,69.0,H-SC,34.37,159.0,0.83,2.27,66.25,XY24,NTT,FINANCE

In [15]:
# top 5 to monitor for exit
df_tmp = df_portfolio_features[~df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])]
df_tmp = df_tmp[(df_tmp['Current P/L%'] > 0) ].sort_values(by = 'Dev%_PE', ascending=False)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
74,STARHEALTH,-0.30,1.41,45.22,47.26,128915.0,3960.0,285083.0,761.00,59.94,61.0,H-SC,10.20,173.0,0.03,1.90,25.16,XY24,NTT,INSURANCE
25,FINCABLES,1.61,37.57,51.13,107.91,103850.0,55466.0,203110.0,1641.55,23.80,62.0,M-SC,26.12,220.0,0.53,1.35,52.81,OX40N,ATH,CABLES
68,SATIN,3.08,23.52,22.92,51.83,78220.0,64991.0,341275.0,274.00,10.38,69.0,H-SC,34.37,159.0,0.83,2.27,66.25,XY24,NTT,FINANCE
91,ZYDUSLIFE,0.57,13.79,19.19,35.63,45762.0,28896.0,238470.0,1286.17,-0.90,75.0,H-MC,4.30,120.0,0.63,1.59,25.38,AR,ATH,PHARMA
73,SONACOMS,2.25,5.18,32.24,39.09,34303.0,5241.0,106400.0,804.02,-16.69,62.0,M-MC,18.98,193.0,0.15,0.71,50.52,AR,ATH,AUTO

In [16]:
# top 5 to book for rotation from weak conviction
df_tmp = df_portfolio_features[~df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])]
df_tmp = df_tmp[~df_tmp['Criteria'].isin(['XY25','XY24','X40', 'X40N'])].sort_values(by = 'RRR Ind', ascending=False)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
91,ZYDUSLIFE,0.57,13.79,19.19,35.63,45762.0,28896.0,238470.0,1286.17,-0.90,75.0,H-MC,4.30,120.0,0.63,1.59,25.38,AR,ATH,PHARMA
25,FINCABLES,1.61,37.57,51.13,107.91,103850.0,55466.0,203110.0,1641.55,23.80,62.0,M-SC,26.12,220.0,0.53,1.35,52.81,OX40N,ATH,CABLES
73,SONACOMS,2.25,5.18,32.24,39.09,34303.0,5241.0,106400.0,804.02,-16.69,62.0,M-MC,18.98,193.0,0.15,0.71,50.52,AR,ATH,AUTO
42,INDIAMART,0.42,-12.43,136.06,106.72,146957.0,-15327.0,108009.0,4810.62,-60.55,48.0,H-SC,10.54,140.0,-0.10,0.72,4.56,AR,ATH,MISC
90,WIPRO,-1.50,-16.44,106.16,72.27,150314.0,-27856.0,141592.0,420.00,-24.55,58.0,M-LC,13.44,98.0,-0.19,0.94,8.63,XR,NTT,IT

In [17]:
# top 5 to accumulate based on lowest RSI_14
df_tmp = df_portfolio_features[df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])].sort_values(by = 'RSI_14', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
23,DMART,0.16,-1.36,31.38,29.60,77263.0,-3384.0,246216.0,5391.45,-16.84,33.0,X-LC,4.23,14.0,-0.04,1.64,12.54,X40N,ATH,FMCG
27,GLAXO,-0.77,-8.38,51.87,39.15,94710.0,-16692.0,182592.0,3466.20,-29.97,34.0,X-MC,6.55,56.0,-0.18,1.21,1.01,X40,ATH,PHARMA
33,HCLTECH,-0.33,-24.60,61.15,21.51,111549.0,-59506.0,182418.0,1872.35,-20.60,37.0,X-LC,18.75,8.0,-0.53,1.21,3.37,X40,ATH,IT
79,TCS,-1.39,-33.18,86.89,24.88,268979.0,-153710.0,309563.0,4253.91,-43.30,39.0,X-LC,17.34,2.0,-0.57,2.06,2.72,X40,ATH,IT
88,VOLTAS,-0.98,-0.54,45.98,45.20,87688.0,-1032.0,190710.0,1856.00,13.82,41.0,X-MC,4.25,79.0,-0.01,1.27,4.20,XY25,NTT,AC

In [18]:
# top 5 to accumulate based on Spread and CumlRnk
df_tmp = df_portfolio_features[df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])]
df_tmp = df_tmp[(df_tmp['CumlRnk'] < 100)].sort_values(by = 'Spread%', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
84,UNITDSPR,0.72,-4.99,27.11,20.77,60310.0,-11679.0,222465.0,1644.00,-15.72,49.0,X-MC,3.74,64.0,-0.19,1.48,6.12,X40N,NTT,BREWERIES
65,RELIANCE,-0.78,-12.94,43.92,25.30,76844.0,-26000.0,174963.0,1952.00,-15.03,46.0,X-LC,3.91,21.0,-0.34,1.16,3.96,XY25,BTT,REFINERIES
23,DMART,0.16,-1.36,31.38,29.60,77263.0,-3384.0,246216.0,5391.45,-16.84,33.0,X-LC,4.23,14.0,-0.04,1.64,12.54,X40N,ATH,FMCG
88,VOLTAS,-0.98,-0.54,45.98,45.20,87688.0,-1032.0,190710.0,1856.00,13.82,41.0,X-MC,4.25,79.0,-0.01,1.27,4.20,XY25,NTT,AC
39,ICICIGI,0.32,-1.46,21.11,19.34,41627.0,-2917.0,197192.0,2252.93,-17.14,58.0,X-MC,4.96,66.0,-0.07,1.31,10.14,X40,ATH,INSURANCE

In [19]:
# top 5 to accumulate based on lowest Gained%
df_tmp = df_portfolio_features[df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])].sort_values(by = 'Gained%', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
27,GLAXO,-0.77,-8.38,51.87,39.15,94710.0,-16692.0,182592.0,3466.20,-29.97,34.0,X-MC,6.55,56.0,-0.18,1.21,1.01,X40,ATH,PHARMA
32,HAVELLS,-0.23,-23.10,70.91,31.42,178842.0,-75781.0,252210.0,2052.62,-27.65,42.0,X-MC,12.64,63.0,-0.42,1.68,2.24,X40,ATH,ELECTRICAL
79,TCS,-1.39,-33.18,86.89,24.88,268979.0,-153710.0,309563.0,4253.91,-43.30,39.0,X-LC,17.34,2.0,-0.57,2.06,2.72,X40,ATH,IT
33,HCLTECH,-0.33,-24.60,61.15,21.51,111549.0,-59506.0,182418.0,1872.35,-20.60,37.0,X-LC,18.75,8.0,-0.53,1.21,3.37,X40,ATH,IT
40,ICICIPRULI,-0.76,-13.50,51.14,30.73,87143.0,-26605.0,170400.0,790.00,-36.73,44.0,X-MC,11.91,78.0,-0.31,1.13,3.83,X40,ATH,INSURANCE

In [20]:
# top 5 to accumulate based on lowest CurrAlloc%
df_tmp = df_portfolio_features[df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])].sort_values(by = 'CurrAlloc%', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
64,RELAXO,0.92,-60.95,290.05,52.31,164406.0,-88478.0,56682.0,1176.00,-58.47,55.0,X-SC,24.74,92.0,-0.54,0.38,26.73,X40N,NTT,FOOTWEAR
10,BATAINDIA,0.36,-54.93,199.99,35.20,115978.0,-70678.0,57992.0,2096.00,-23.90,46.0,X-SC,25.47,91.0,-0.61,0.39,15.01,X40,NTT,FOOTWEAR
60,QUESS,-0.75,-16.07,107.19,73.90,96077.0,-17161.0,89632.0,424.00,-54.82,52.0,X-SC,9.86,80.0,-0.18,0.60,22.19,XY24,NTT,MISC
28,GODREJCP,1.12,-7.66,42.38,31.47,58158.0,-11385.0,137229.0,1469.04,-2.82,46.0,X-LC,8.75,32.0,-0.20,0.91,5.29,X40N,ATH,FMCG
53,M&M,-1.01,0.83,22.37,23.38,31280.0,1147.0,139828.0,3802.40,-14.43,47.0,X-LC,8.98,25.0,0.04,0.93,6.01,X40N,ATH,AUTO

In [21]:
# top 5 to accumulate based on CumlRnk
df_tmp = df_portfolio_features.sort_values(by = 'CumlRnk', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
47,ITC,-0.76,-20.55,49.84,19.06,134707.0,-69888.0,270278.0,452.00,-56.33,43.0,X-LC,14.72,1.0,-0.52,1.80,4.85,X40,NTT,FMCG
79,TCS,-1.39,-33.18,86.89,24.88,268979.0,-153710.0,309563.0,4253.91,-43.30,39.0,X-LC,17.34,2.0,-0.57,2.06,2.72,X40,ATH,IT
45,INFY,-0.07,-20.51,68.88,34.24,171318.0,-64168.0,248720.0,1972.00,-37.59,45.0,X-LC,18.88,3.0,-0.37,1.65,6.64,X40,NTT,IT
81,TMPV,3.31,-12.23,55.60,36.58,173659.0,-43505.0,312336.0,600.00,-81.44,70.0,X-LC,5.85,4.0,-0.25,2.08,30.18,XY24,NTT,AUTO
59,PIDILITIND,0.09,4.78,12.97,18.37,19176.0,6740.0,147850.0,1670.26,-26.64,62.0,X-LC,5.31,5.0,0.35,0.98,16.09,X40,ATH,CHEMICALS

In [22]:
# top 5 for average up
df_tmp = df_portfolio_features[(df_portfolio_features['Dev%_200'] > 5)].sort_values(by = 'CurrAlloc%', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
44,INDUSINDBK,0.67,-31.17,93.07,32.89,49458.0,-24066.0,53141.0,1800.00,-350.00,61.0,L-MC,8.75,258.0,-0.49,0.35,30.80,XR,NTT,BANKS
72,SIS,2.25,-8.50,32.53,21.26,33048.0,-9440.0,101592.0,528.00,2417.62,65.0,H-SC,16.49,168.0,-0.29,0.68,51.05,OX40N,NTT,MISC
73,SONACOMS,2.25,5.18,32.24,39.09,34303.0,5241.0,106400.0,804.02,-16.69,62.0,M-MC,18.98,193.0,0.15,0.71,50.52,AR,ATH,AUTO
75,SURYODAY,0.04,-7.97,33.69,23.03,55521.0,-14270.0,164801.0,216.00,79.82,56.0,H-SC,18.32,166.0,-0.26,1.10,38.76,XR,NTT,BANKS
37,HONAUT,3.39,-7.77,64.06,51.31,113931.0,-14988.0,177850.0,58357.33,-23.26,70.0,X-SC,10.74,90.0,-0.13,1.18,35.12,X40N,ATH,ELECTRICAL

In [23]:
# top 5 RSP
df_tmp = df_portfolio_features.sort_values(by = 'RSP', ascending=False)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
68,SATIN,3.08,23.52,22.92,51.83,78220.0,64991.0,341275.0,274.00,10.38,69.0,H-SC,34.37,159.0,0.83,2.27,66.25,XY24,NTT,FINANCE
69,SFL,-1.31,-38.34,105.36,26.63,170356.0,-100529.0,161689.0,1287.00,22.47,65.0,M-SC,10.90,242.0,-0.59,1.08,34.76,XY24,NTT,MISC
72,SIS,2.25,-8.50,32.53,21.26,33048.0,-9440.0,101592.0,528.00,2417.62,65.0,H-SC,16.49,168.0,-0.29,0.68,51.05,OX40N,NTT,MISC
91,ZYDUSLIFE,0.57,13.79,19.19,35.63,45762.0,28896.0,238470.0,1286.17,-0.90,75.0,H-MC,4.30,120.0,0.63,1.59,25.38,AR,ATH,PHARMA
43,INDIGOPNTS,-0.56,-29.65,42.17,0.02,51786.0,-51756.0,122803.0,1408.00,87.50,64.0,M-SC,18.29,222.0,-1.00,0.82,39.33,OX40N,NTT,PAINTS

In [24]:
# Top N allocation
df_tmp = df_portfolio_features.sort_values(by = 'CurrAlloc%', ascending=False)
top_n_values = [10, 25, 50]

sum_df = pd.DataFrame({
    'Top_N': top_n_values,
    'Sum_Alloc%': [df_tmp['CurrAlloc%'].head(n).sum() for n in top_n_values]
})

sum_df

   Top_N  Sum_Alloc%
0     10       19.44
1     25       42.73
2     50       72.82

In [25]:
# market-cap-wise allocation
df_tmp = df_portfolio_features[cols]
df_tmp.groupby(df_tmp['Conviction'].str[-2:])['CurrAlloc%'].sum().sort_values(ascending=False)

Conviction
SC    42.75
LC    31.51
MC    25.78
Name: CurrAlloc%, dtype: float64

In [26]:
# criteria-wise allocation
df_portfolio_features.groupby('Criteria')['CurrAlloc%'].sum().sort_values(ascending=False)

Criteria
XY24     27.66
X40      25.37
X40N     16.94
XR        8.84
OX40N     7.00
AR        6.86
XY25      6.52
SR        0.85
Name: CurrAlloc%, dtype: float64

In [27]:
# conviction-wise allocation
df_portfolio_features.groupby('Conviction')['CurrAlloc%'].sum().sort_values(ascending=False)

Conviction
X-LC    29.35
H-SC    22.38
X-MC    20.72
M-SC    10.06
X-SC     9.77
H-MC     2.76
M-MC     1.95
H-LC     1.22
M-LC     0.94
L-SC     0.54
L-MC     0.35
Name: CurrAlloc%, dtype: float64

In [28]:
# sector-wise stats
df_tmp = df_portfolio_features.groupby('Category')[['CurrAlloc%', 'Current', 'Current P/L', 'FTT Amt']].sum().sort_values(by=['Current', 'Current P/L'], ascending=False)
df_tmp['Current P/L%'] = round(df_tmp['Current P/L'] * 100 / df_tmp['Current'], 2)
df_tmp['FTT%'] = round(df_tmp['FTT Amt'] * 100 / df_tmp['Current'], 2)
cols = ['CurrAlloc%', 'Current P/L%', 'FTT%']
df_tmp[cols].sort_values(by=['CurrAlloc%'], ascending=False)

               CurrAlloc%  Current P/L%    FTT%
Category
FMCG                15.11        -16.58   57.67
FINANCE             10.85        -13.19   62.42
IT                  10.27        -45.96  118.93
MISC                 6.96        -28.46   84.26
AUTO                 6.81         -7.06   47.19
BANKS                5.66         -6.95   56.41
PAINTS               5.55        -18.20   38.73
INSURANCE            5.35         -2.95   37.99
PHARMA               5.07          2.84   28.39
ELECTRICAL           4.08        -15.15   55.79
CHEMICALS            2.13        -26.88  102.49
HEALTHCARE           2.03        -16.85   47.34
APPARELS             1.78         -0.09   34.23
AC                   1.78        -19.47   51.86
FOOTWEAR             1.72        -71.69  140.54
TRAVEL               1.69        -76.67  165.13
DURABLES             1.59        -61.58  100.90
BREWERIES            1.48         -5.25   27.11
REALTY               1.40         -5.30   22.60
CABLES               1.35         27.31   51.13
CERAMICS             1.34        -52.42   98.72
ENGINEERING          1.24        -30.08   89.58
REFINERIES           1.16        -14.86   43.92
CEMENT               1.13        -58.18  176.51
JEWELLERY            1.06       -100.35  169.95
ENTERTAINMENT        0.72        -79.18  186.04
TEXTILES             0.40        -52.76   96.32
HOTELS               0.33       -131.56  213.23

In [29]:
# money to be made criteria-wise
df_portfolio_features.groupby('Criteria')['FTT Amt'].agg(['sum', 'count']).sort_values(by='sum', ascending=False)

                sum  count
Criteria
XY24      3443737.0     21
X40       1878909.0     19
XR        1351848.0     13
X40N      1179426.0     13
AR        1153918.0      9
OX40N      741326.0     10
XY25       460391.0      5
SR         292925.0      2

In [30]:
# money to be made conviction-wise
df_portfolio_features.groupby('Conviction')['FTT Amt'].agg(['sum', 'count']).sort_values(by='sum', ascending=False)

                  sum  count
Conviction
H-SC        3425557.0     24
X-LC        1880026.0     21
X-MC        1614736.0     15
M-SC        1406352.0     14
X-SC        1337633.0      9
H-MC         284320.0      2
L-SC         210443.0      2
M-LC         150314.0      1
M-MC          93925.0      2
H-LC          49716.0      1
L-MC          49458.0      1

In [31]:
# money to be made criteria and conviction-wise
df_portfolio_features.groupby(['Conviction', 'Criteria'])['FTT Amt'].agg(['sum', 'count']).sort_values(by='sum', ascending=False)

                           sum  count
Conviction Criteria
H-SC       XY24      1052434.0      6
X-LC       X40       1006793.0     10
H-SC       AR         948473.0      5
M-SC       XY24       824377.0      6
H-SC       XR         814247.0      7
X-SC       XY24       792335.0      4
X-MC       X40        663506.0      7
           X40N       481048.0      4
X-LC       X40N       361690.0      6
X-SC       X40N       336688.0      3
X-LC       XY24       318523.0      2
M-SC       OX40N      317967.0      5
H-SC       OX40N      317478.0      4
           SR         292925.0      2
X-MC       XY25       252672.0      2
H-MC       XY24       238558.0      1
X-MC       XY24       217510.0      2
X-SC       X40        208610.0      2
M-SC       XR         188344.0      2
M-LC       XR         150314.0      1
X-LC       XY25       148097.0      2
L-SC       OX40N      105881.0      1
           XR         104562.0      1
M-SC       AR          75664.0      1
M-MC       XY25        59622.0      1
H-LC       AR          49716.0      1
L-MC       XR          49458.0      1
H-MC       AR          45762.0      1
X-LC       XR          44923.0      1
M-MC       AR          34303.0      1

In [32]:
# notebook execution time

end_time = time.time()
execution_time = round(end_time - start_time, 0)
print(f"Notebook execution time: {execution_time} seconds")

Notebook execution time: 28.0 seconds