<a href="https://colab.research.google.com/github/ankit-rathi/Quantvesting_v2/blob/main/myStocks_Portfolio_Analysis.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
'''
!pip install pandas==2.2.2 -qq
!pip install pyxirr -qq
!pip install ta -qq
!pip install yfinance==0.2.59 -qq
'''

'\n!pip install pandas==2.2.2 -qq\n!pip install pyxirr -qq\n!pip install ta -qq\n!pip install yfinance==0.2.59 -qq\n'

In [2]:
# import libraries

import numpy as np
import pandas as pd
import datetime
import warnings
warnings.filterwarnings('ignore')
import yfinance as yfin
import ta
import matplotlib.pyplot as plt
import requests

In [3]:
# notebook start time
import time
import datetime
import pytz

start_time = time.time()

# function to print date timestamp
def print_date_time():
  tz_NY = pytz.timezone('Asia/Kolkata')
  datetime_NY = datetime.datetime.now(tz_NY)
  print("Run date time (IST):", datetime_NY.strftime("%Y-%m-%d %H:%M:%S"))

In [4]:
# function to get booked and reserved amount
def get_amt():
  # fetch the JSON data from the URL
  url = "https://raw.githubusercontent.com/ankit-rathi/Tradevesting_v1/main/data/myPortfolioAmts.json"
  response = requests.get(url)
  pf_amts = response.json()  # parse the JSON data

  # extract values from the JSON
  py_booked_amt_dm = pf_amts["py_booked_amt_dm"]
  py_booked_amt_sv = pf_amts["py_booked_amt_sv"]
  cy_booked_amt_dm = pf_amts["cy_booked_amt_dm"]
  cy_booked_amt_sv = pf_amts["cy_booked_amt_sv"]
  reserve_amt_dm = pf_amts["reserve_amt_dm"]
  reserve_amt_sv = pf_amts["reserve_amt_sv"]

  # perform calculations
  py_booked_amt = py_booked_amt_dm + py_booked_amt_sv
  cy_booked_amt = cy_booked_amt_dm + cy_booked_amt_sv
  reserve_amt = reserve_amt_dm + reserve_amt_sv
  total_booked_amt = py_booked_amt + cy_booked_amt

  return total_booked_amt, reserve_amt, cy_booked_amt, py_booked_amt

gen_output = 0

In [5]:
# function to format the amount
def format_amt(number):
    abs_number = abs(number)

    if abs_number >= 1_00_00_000:  # Crores
        formatted_amt = f"{number / 1_00_00_000:.2f} C"
    elif abs_number >= 1_00_000:  # Lakhs
        formatted_amt = f"{number / 1_00_000:.2f} L"
    elif abs_number >= 1_000:  # Thousands
        formatted_amt = f"{number / 1_000:.2f} K"
    else:
        formatted_amt = f"{number:.2f}"

    return formatted_amt

# function to set start and end date
def get_start_end_date():
  start_date = (datetime.date.today() + datetime.timedelta(days=-365)).strftime('%Y-%m-%d')
  end_date = (datetime.date.today() + datetime.timedelta(days=1)).strftime('%Y-%m-%d')
  return start_date, end_date

# function to fetch my portfolio csv
def get_mypfs_df():
  mypfs_df = pd.read_csv('https://raw.githubusercontent.com/ankit-rathi/Tradevesting_v1/main/data/myPortfolioStocks.csv')
  return mypfs_df

# function to fetch my prospects csv
def get_mypps_df():
  mypps_df = pd.read_csv('https://raw.githubusercontent.com/ankit-rathi/Tradevesting_v1/main/data/myProspectsScrips.csv')
  return mypps_df

# function to fetch screener data
def get_myscreen_df():
  myscreen_df = pd.read_csv('https://raw.githubusercontent.com/ankit-rathi/Tradevesting_v1/main/data/myScreenerDB.csv')
  return myscreen_df

# function to fetch momentum data
def get_myinvmt_df():
  myinvmt_df = pd.read_csv('https://raw.githubusercontent.com/ankit-rathi/Tradevesting_v1/main/data/myInvestments.csv')
  return myinvmt_df

# function to get the stock ids
def get_stock_ids(df_pf):
  stock_n100 = df_pf['Symbol'].unique()

  exclude = ['CADILAHC','MMTC', 'MASFIN']

  stock_ids = df_pf[~df_pf['Symbol'].isin(exclude) ]['Symbol'].unique()

  #mypf = mypf[mypf.Forecast.notnull()]
  #stock_ids = mypf['Symbol'].unique()

  #stock_ids.sort()
  return stock_ids

# get features from screener data
def get_screener_features():
  myscreen_df = get_myscreen_df()
  cols = ['Symbol', 'EPS', 'MedPE', 'ROCE%', 'ROE%', 'CapType']
  return myscreen_df[cols]

# get relative strength
def get_relative_strength(stock_list):

    # Dictionary to store stock tickers and their corresponding percentage price change
    stock_changes = {}

    # Loop through each stock and fetch its price data
    for stock in stock_list:
        try:
            # Download the stock data for the given date range
            stock_data = yfin.Ticker(stock + '.NS').history(period='1mo', interval='1d')[map(str.title, ['open', 'close', 'low', 'high', 'volume'])]

            # Calculate the percentage change for the stock
            if len(stock_data) > 0:
                start_price = stock_data['Close'].iloc[0]
                end_price = stock_data['Close'].iloc[-1]
                percent_change = round(((end_price - start_price) / start_price) * 100, 2)
                stock_changes[stock] = percent_change
            else:
                stock_changes[stock] = np.nan  # If no data is available, set to NaN

        except Exception as e:
            print(f"Error fetching data for {stock}: {e}")
            stock_changes[stock] = np.nan

    # Create a DataFrame with stock tickers and their percentage changes
    df = pd.DataFrame(list(stock_changes.items()), columns=['Symbol', 'Percent_Change'])

    # Drop any stocks with missing data (NaN values)
    df = df.dropna()

    # Calculate the percentile rank based on percentage change
    df['RSP'] = round(df['Percent_Change'].rank(pct=True) * 100, 2)
    cols = ['Symbol', 'RSP']
    df = df[cols]
    # Sort by percentile rank (optional)
    df = df.sort_values(by='RSP', ascending=False).reset_index(drop=True)

    return df

In [6]:
# function to get stock technicals
def stock_prec_dev(stock_symbol):
    #stock_symbol = 'ULTRACEMCO.NS'
    short_window = 20
    mid_window = 50
    long_window = 200
    moving_avg = 'SMA'

    start = datetime.datetime(*map(int, start_date.split('-')))
    end = datetime.datetime(*map(int, end_date.split('-')))

    stock_df = yfin.Ticker(stock_symbol + '.NS').history(period='max', interval='1d')[map(str.title, ['open', 'close', 'low', 'high', 'volume'])]

    stock_df['Max'] = round(max(stock_df['Close']),2)
    stock_df = stock_df[(stock_df.index <= end_date) & (stock_df.index >= start_date)]
    stock_df['200_SMA'] = round(stock_df['Close'].rolling(window = 200, min_periods = 1).mean(),0)
    stock_df['Dev%_200'] = round((stock_df['Close'] - stock_df['200_SMA'])*100/stock_df['200_SMA'],2)
    stock_df.dropna(axis = 0, inplace = True) # remove any null rows

    stock_df['20_SMA'] = stock_df['Close'].rolling(window=20).mean()
    stock_df['50_SMA'] = stock_df['Close'].rolling(window=50).mean()
    stock_df['Symbol'] = stock_symbol

    stock_df['Close'] = round(stock_df['Close'],2)
    stock_df['Min'] = round(min(stock_df['Close']),2)
    stock_df['RSI_14'] = ta.momentum.RSIIndicator(close=stock_df['Close'], window=14).rsi()
    stock_df['RSI_14'] = round(stock_df['RSI_14'],0)
    stock_df['Prev_Close'] = stock_df['Close'].shift(1)
    stock_df.drop(['Open', 'Low', 'High', 'Volume'], axis=1, inplace=True)
    stock_df = stock_df.tail(1)

    max_SMA = max(stock_df['20_SMA'].item(), stock_df['50_SMA'].item(), stock_df['200_SMA'].item())
    min_SMA = min(stock_df['20_SMA'].item(), stock_df['50_SMA'].item(), stock_df['200_SMA'].item())
    ABS_Spread = max_SMA - min_SMA
    stock_df['Spread%'] = round((ABS_Spread / stock_df['200_SMA'].item()) * 100,2)

    return stock_df

# function to compute stock attributes
def get_common_features(stock_ids, df_mypf):

  df_prec_dev = pd.DataFrame()
  df_tmp = get_screener_features()
  df_rs = get_relative_strength(stock_ids)

  for stock_id in stock_ids:
      tmp = stock_prec_dev(stock_id)
      tmp = tmp.reset_index()
      df_prec_dev = pd.concat([df_prec_dev, tmp], ignore_index = True)
  df_prec_dev = pd.merge(df_prec_dev, df_mypf, on= 'Symbol')
  df_prec_dev = pd.merge(df_prec_dev, df_tmp, on= 'Symbol', how='left')
  df_prec_dev = pd.merge(df_prec_dev, df_rs, on= 'Symbol', how='left')
  #print(df_prec_dev.columns)
  df_prec_dev['Curr_PE'] = round(df_prec_dev['Close']/df_prec_dev['EPS'],1)
  df_prec_dev['Dev%_PE'] = round((df_prec_dev['Curr_PE'] - df_prec_dev['MedPE'])*100/df_prec_dev['MedPE'],2)
  df_prec_dev['Conviction'] = df_prec_dev['Conviction'] + '-' + df_prec_dev['CapType']
  return df_prec_dev

# function to arrange stock features
def arrange_features(df_stocks, common_cols, diff_cols):
  df_stocks_common = df_stocks[common_cols].drop_duplicates()
  df_stocks_diff = df_stocks[diff_cols]
  df_stocks_diff['Investment'] = df_stocks_diff['AvgCost'] * df_stocks_diff['Shares']
  df_stocks_diff = df_stocks_diff.groupby(['Symbol'])[['Shares', 'Investment']].aggregate(['sum']).reset_index()
  df_stocks_diff.columns = ['Symbol', 'Shares', 'Investment']
  df_stocks_diff['AvgCost'] = round(df_stocks_diff['Investment']/df_stocks_diff['Shares'],2)
  df_stocks = pd.merge(df_stocks_diff, df_stocks_common, on='Symbol')
  return df_stocks

# plot fact distribution across dimension
def plot_pie_chart(df, dimension, fact):
  # grouping the data by category and calculating the sum of fact for each type
  grouped_data = df.groupby(dimension)[fact].sum()

  # sorting the grouped data in descending order
  grouped_data = grouped_data.sort_values(ascending=False)

  # creating a pie chart
  grouped_data.plot.pie(autopct='%1.1f%%', startangle=90, figsize=(6, 6))

  # adding a title and displaying the plot
  plt.title(f'{dimension} {fact} Distribution')
  plt.ylabel('')  # To hide the y-label
  plt.show()

In [7]:
# function to get portfolio features

def get_portfolio_features(df_common_features):

  print_date_time()
  print('-------------------')

  #df_common_features["Target"] = df_common_features["Target"].fillna(df_common_features["Max"])
  df_common_features['NTT'] = np.where(df_common_features['Strategy']== 'NTT', df_common_features["Target"], df_common_features['Max'])
  df_common_features['LTT'] = np.where(df_common_features['Strategy']== 'BTT', df_common_features["Target"], df_common_features['Max'])
  df_common_features['BOL'] = df_common_features['Min']

  tmp_df = df_common_features[df_common_features['Symbol'].isin(mypf_df[mypf_df['InPortfolio'] != 'NA'].Symbol.values)]
  print('qualified stocks: '+str(len(tmp_df['Symbol'].unique())))
  tmp_df1 = tmp_df[tmp_df['LatestQtr'] == 1]
  print('with latest results: '+str(len(tmp_df1['Symbol'].unique())))
  tmp_df1 = tmp_df1[tmp_df1['StarStock'] == 1]
  print('still star stocks: '+str(len(tmp_df1['Symbol'].unique())))
  tmp_df['Investment'] = tmp_df['AvgCost'] * tmp_df['Shares']
  tmp_df['Current'] = round(tmp_df['Close'] * tmp_df['Shares'],0)
  tmp_df['Previous'] = tmp_df['Prev_Close'] * tmp_df['Shares']
  tmp_df['EstimatedST'] = tmp_df['NTT'] * tmp_df['Shares']
  tmp_df['EstimatedLT'] = tmp_df['LTT'] * tmp_df['Shares']
  tmp_df['Current P/L'] = round((tmp_df['Current'] - tmp_df['Investment']),0)
  tmp_df['Today P/L%'] = round((tmp_df['Current'] - tmp_df['Previous'])*100/tmp_df['Previous'],2)
  tmp_df['Current P/L%'] = round((tmp_df['Current'] - tmp_df['Investment'])*100/tmp_df['Investment'],2)
  tmp_df['EstimatedST P/L%'] = round((tmp_df['EstimatedST'] - tmp_df['Investment'])*100/tmp_df['Investment'],2)
  tmp_df['EstimatedLT P/L%'] = round((tmp_df['EstimatedLT'] - tmp_df['Investment'])*100/tmp_df['Investment'],2)
  tmp_df['NTT%'] = round((tmp_df['NTT'] - tmp_df['Close'])*100/tmp_df['Close'],2)
  tmp_df['LTT%'] = round((tmp_df['LTT'] - tmp_df['Close'])*100/tmp_df['Close'],2)
  tmp_df['Gained%'] = round((tmp_df['Close'] - tmp_df['BOL'])*100/tmp_df['BOL'],2)
  investment = round(sum(tmp_df['AvgCost']*tmp_df['Shares']),0)
  current = round(sum(tmp_df['Close']*tmp_df['Shares']),0)
  tmp_df['InitAlloc%'] = round(tmp_df['Investment']*100/investment,2)
  tmp_df['CurrAlloc%'] = round(tmp_df['Current']*100/current,2)
  tmp_df['FTT'] = tmp_df['LTT']
  tmp_df.loc[tmp_df['Strategy'] == 'NTT', 'FTT'] = tmp_df['NTT']
  tmp_df['FTT%'] = tmp_df['LTT%']
  tmp_df.loc[tmp_df['Strategy'] == 'NTT', 'FTT%'] = tmp_df['NTT%']
  tmp_df['FTT Amt'] = round(tmp_df['FTT%'] * tmp_df['Current']/100,0)
  tmp_df['OTT%'] = round((tmp_df['FTT'] - tmp_df['AvgCost'])*100/tmp_df['AvgCost'],2)
  tmp_df['RRR Ind'] = round(tmp_df['Current P/L']/tmp_df['FTT Amt'],2)
  tmp_df['Risk Ind'] = round(tmp_df['Current P/L%']*tmp_df['CurrAlloc%'],0)

  return tmp_df

# function to print portfolio features
def print_portfolio_stats(df_portfolio_features, myinvmt_df):
  from pyxirr import xirr

  total_booked_amt, reserve_amt, cy_booked_amt, py_booked_amt = get_amt()

  dates = myinvmt_df['Date'].values
  dates = np.append(dates, datetime.date.today().strftime('%d-%b-%y'))
  investment = myinvmt_df['Investment'].values
  dates= pd.to_datetime(dates)

  current = round(sum(df_portfolio_features['Close']*df_portfolio_features['Shares']),0) + reserve_amt
  investment_xirr = np.append(investment, current)
  cagr = round(xirr(pd.DataFrame({"dates": dates, "amounts": investment_xirr}))*100,2)

  investment = -sum(investment)
  invested = round(sum(df_portfolio_features['AvgCost']*df_portfolio_features['Shares']),0) + reserve_amt
  previous = round(sum(df_portfolio_features['Prev_Close']*df_portfolio_features['Shares']),0) + reserve_amt
  cy_invested = investment + py_booked_amt

  today_pnl_amount = current-previous
  today_pnl_percentage = round((current-previous)*100/previous,2)

  curr_pnl_amount = current-invested
  curr_pnl_percentage = round((curr_pnl_amount)*100/(cy_invested),2)

  cy_pnl_amount = cy_booked_amt + curr_pnl_amount
  cy_pnl_percentage = round((cy_pnl_amount)*100/cy_invested,2)

  overall_pnl_amount = total_booked_amt + curr_pnl_amount
  overall_pnl_percentage = round((overall_pnl_amount)*100/investment,2)

  estimate_st = round(sum(df_portfolio_features['FTT']*df_portfolio_features['Shares']),0)  + reserve_amt
  est_st_pnl_amount = estimate_st-current
  est_st_pnl_percentage = round((est_st_pnl_amount)*100/current,2)

  estimate_lt = round(sum(df_portfolio_features['LTT']*df_portfolio_features['Shares']),0)  + reserve_amt
  est_lt_pnl_amount = estimate_lt-current
  est_lt_pnl_percentage = round((est_lt_pnl_amount)*100/current,2)

  total_profit = round(sum(df_portfolio_features[df_portfolio_features['Current P/L%'] > 0]['Current']) - sum(df_portfolio_features[df_portfolio_features['Current P/L%'] > 0]['Investment']),0)
  total_loss = round(sum(df_portfolio_features[df_portfolio_features['Current P/L%'] < 0]['Current']) - sum(df_portfolio_features[df_portfolio_features['Current P/L%'] < 0]['Investment']),0)

  cy_booked_percentage = round((cy_booked_amt)*100/current,2)
  py_booked_percentage = round((py_booked_amt)*100/investment,2)
  total_booked_percentage = round((total_booked_amt)*100/investment,2)

  print('-------------------')
  print('Initial Investment: ', format_amt(investment))
  print('CY Investment: ', format_amt(cy_invested))
  print('Reserve: ', format_amt(reserve_amt))
  print('Current: ',  format_amt(current))
  print('-------------------')
  print('Today PnL: '+ '{} ({}%)'.format(format_amt(today_pnl_amount), today_pnl_percentage))
  print('Current PnL: '+ '{} ({}%)'.format(format_amt(curr_pnl_amount), curr_pnl_percentage))
  print('CY Booked + Current PnL: '+ '{} ({}%)'.format(format_amt(cy_pnl_amount), cy_pnl_percentage))
  print('-------------------')
  print('Total profit: ', format_amt(total_profit))
  print('Total loss: ', format_amt(total_loss))
  print('-------------------')
  print('Total Booked + Current PnL: '+ '{} ({}%)'.format(format_amt(overall_pnl_amount), overall_pnl_percentage))
  print('Total Booked PnL: '+ '{} ({}%)'.format(format_amt(total_booked_amt), total_booked_percentage))
  print('Curr Year Booked PnL: '+ '{} ({}%)'.format(format_amt(cy_booked_amt), cy_booked_percentage))
  print('Prev Year Booked PnL: '+ '{} ({}%)'.format(format_amt(py_booked_amt), py_booked_percentage))
  print('===================')
  print('Est FTT: ',  format_amt(estimate_st))
  print('Est FTT PnL: '+ '{} ({}%)'.format(format_amt(est_st_pnl_amount), est_st_pnl_percentage))

  print('===================')
  print('Deployed: ', format_amt(investment))

  print('Current: ', format_amt(current))

  print('CAGR/XIRR %: '+'{}%'.format(cagr))

In [8]:
# get start and end date
start_date, end_date = get_start_end_date()

# get portfolio and prospects data
mypfs_df = get_mypfs_df()
mypps_df = get_mypps_df()
myinvmt_df = get_myinvmt_df()

# merge above datasets
mypf_df = pd.merge(mypfs_df, mypps_df, on="Symbol")

# seggregate dm and sv portfolio
dm_pf = mypf_df[mypf_df['InPortfolio'] == 'DM']
sv_pf = mypf_df[mypf_df['InPortfolio'] == 'SV']

# build portfolio stock dataframe
dm_stocks = get_stock_ids(dm_pf)
sv_stocks = get_stock_ids(sv_pf)
df_stocks = pd.concat([dm_pf,sv_pf], ignore_index = True)

# arrange common and diff stock features
common_cols = ['Symbol', 'Target', 'Criteria', 'Strategy', 'CumlRnk', 'LatestQtr', 'StarStock', 'Conviction', 'Category', 'InFolio', 'XIRR', 'MBQ']
diff_cols = ['Symbol', 'AvgCost', 'Shares']
df_stocks = arrange_features(df_stocks, common_cols, diff_cols)

# get common features
stock_ids = df_stocks['Symbol'].values
df_common_features = get_common_features(stock_ids, df_stocks)

df_common_features.reset_index(drop=True, inplace=True)
df_common_features.drop(['Date'], axis=1, inplace=True)
# get and print portfolio features
df_portfolio_features = get_portfolio_features(df_common_features)

print_portfolio_stats(df_portfolio_features, myinvmt_df)

df = df_portfolio_features
#plot_pie_chart(df, 'CapType', 'Current')
list_ox40n = list(df[df['MBQ'].str.contains('OX40N', na=False)]['Symbol'].values)

Run date time (IST): 2026-07-22 13:24:31
-------------------
qualified stocks: 92
with latest results: 31
still star stocks: 20
-------------------
Initial Investment:  1.40 C
CY Investment:  1.82 C
Reserve:  1.49 K
Current:  1.51 C
-------------------
Today PnL: -1.48 L (-0.97%)
Current PnL: -32.07 L (-17.59%)
CY Booked + Current PnL: -29.99 L (-16.45%)
-------------------
Total profit:  4.27 L
Total loss:  -36.34 L
-------------------
Total Booked + Current PnL: 12.88 L (9.23%)
Total Booked PnL: 44.95 L (32.22%)
Curr Year Booked PnL: 2.08 L (1.38%)
Prev Year Booked PnL: 42.87 L (30.73%)
===================
Est FTT:  2.55 C
Est FTT PnL: 1.04 C (68.67%)
===================
Deployed:  1.40 C
Current:  1.51 C
CAGR/XIRR %: 3.58%

In [9]:
# top 5 near their targets
cols = ['Symbol', 'Today P/L%', 'Current P/L%', 'FTT%', 'OTT%', 'FTT Amt', 'Current P/L', 'Current', 'FTT', 'Dev%_PE', 'RSI_14','Conviction', 'Spread%',  'CumlRnk', 'RRR Ind', 'CurrAlloc%', 'Gained%', 'Criteria', 'Strategy', 'Category']
df_tmp = df_portfolio_features[~df_portfolio_features['Symbol'].isin(['ENRIN','BLUSPRING','DIGITIDE'])]
df_tmp = df_tmp.sort_values(by = 'FTT Amt', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
49,JSWINFRA,-3.79,12.85,3.17,16.43,7934.0,28508.0,250282.0,342.00,-3.25,54.0,X-MC,19.06,61.0,3.59,1.66,41.90,X40N,NTT,REALTY
59,PIDILITIND,-0.77,11.90,5.78,18.37,9127.0,16790.0,157900.0,1670.26,-21.61,53.0,X-LC,8.10,5.0,1.84,1.05,23.98,X40,ATH,CHEMICALS
73,SONACOMS,-1.41,24.97,10.98,38.69,13881.0,25261.0,126420.0,801.69,-1.03,77.0,M-MC,25.01,193.0,1.82,0.84,79.36,AR,ATH,AUTO
83,TTKPRESTIG,-1.48,-14.78,17.45,0.09,14987.0,-14893.0,85884.0,770.00,99.36,63.0,M-SC,9.91,250.0,-0.99,0.57,52.93,OX40N,NTT,DURABLES
56,MEDANTA,1.61,15.72,9.85,27.12,20121.0,27756.0,204273.0,1486.00,12.24,62.0,X-SC,11.18,87.0,1.38,1.35,40.76,XY24,NTT,HEALTHCARE

In [10]:
# top 5 today
df_tmp = df_portfolio_features.sort_values(by = 'Today P/L%', ascending=False)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
62,RAJOOENG,5.00,-45.08,154.22,39.61,86810.0,-46210.0,56290.0,143.10,-62.94,67.0,H-SC,20.44,136.0,-0.53,0.37,20.59,AR,ATH,MISC
58,PGHH,2.60,-32.93,96.84,32.01,138675.0,-70320.0,143200.0,17616.87,-54.64,48.0,X-MC,20.22,57.0,-0.51,0.95,2.63,X40,ATH,FMCG
1,ABBOTINDIA,2.12,-3.13,21.89,18.07,37924.0,-5605.0,173250.0,35195.00,-17.49,77.0,X-MC,2.99,58.0,-0.15,1.15,14.67,X40,ATH,PHARMA
21,DEN,2.04,-47.79,172.13,42.07,75902.0,-40368.0,44096.0,75.00,58.03,43.0,M-SC,5.32,235.0,-0.53,0.29,19.93,AR,NTT,ENTERTAINMENT
61,RAJESHEXPO,1.86,-82.80,481.70,0.07,113672.0,-113579.0,23598.0,518.00,764.90,43.0,L-SC,35.83,268.0,-1.00,0.16,16.54,OX40N,NTT,JEWELLERY

In [11]:
# bottom 5 today
df_tmp = df_portfolio_features.sort_values(by = 'Today P/L%', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
9,BANDHANBNK,-15.84,-15.46,127.60,92.42,300504.0,-43054.0,235505.0,400.0,101.87,31.0,H-SC,19.19,174.0,-0.14,1.56,29.73,XY24,NTT,BANKS
42,INDIAMART,-5.09,-21.78,156.86,100.92,151332.0,-26860.0,96476.0,4675.6,-64.65,34.0,H-SC,9.16,140.0,-0.18,0.64,0.00,AR,ATH,MISC
49,JSWINFRA,-3.79,12.85,3.17,16.43,7934.0,28508.0,250282.0,342.0,-3.25,54.0,X-MC,19.06,61.0,3.59,1.66,41.90,X40N,NTT,REALTY
88,VOLTAS,-3.36,2.76,41.30,45.20,81371.0,5283.0,197025.0,1856.0,17.62,49.0,X-MC,5.30,79.0,0.06,1.30,7.98,XY25,NTT,AC
64,RELAXO,-3.14,-48.45,195.44,52.31,146254.0,-70327.0,74833.0,1176.0,-45.12,53.0,X-SC,12.32,92.0,-0.48,0.50,67.32,X40N,NTT,FOOTWEAR

In [12]:
# top 5 to exit based on CumlRnk
df_tmp = df_portfolio_features[~df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])]
df_tmp = df_tmp[(df_tmp['Current P/L%'] > -1) & (df_tmp['Current P/L%'] < 1)].sort_values(by = 'CumlRnk', ascending=False)
df_tmp[cols].head()

Empty DataFrame
Columns: [Symbol, Today P/L%, Current P/L%, FTT%, OTT%, FTT Amt, Current P/L, Current, FTT, Dev%_PE, RSI_14, Conviction, Spread%, CumlRnk, RRR Ind, CurrAlloc%, Gained%, Criteria, Strategy, Category]
Index: []

In [13]:
# OX40N stocks to exit
df_tmp = df_portfolio_features[(df_portfolio_features['Symbol'].isin(list_ox40n))].sort_values(by = 'Current P/L%', ascending=False)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
25,FINCABLES,-0.67,27.75,62.76,107.91,118370.0,40964.0,188608.0,1641.55,14.66,39.0,M-SC,21.90,220.0,0.35,1.25,41.90,OX40N,ATH,CABLES
72,SIS,1.16,1.30,19.70,21.26,22159.0,1448.0,112480.0,528.00,2687.05,61.0,H-SC,25.00,168.0,0.07,0.74,67.24,OX40N,NTT,MISC
83,TTKPRESTIG,-1.48,-14.78,17.45,0.09,14987.0,-14893.0,85884.0,770.00,99.36,63.0,M-SC,9.91,250.0,-0.99,0.57,52.93,OX40N,NTT,DURABLES
16,CERA,-0.66,-19.69,54.27,23.89,76665.0,-34637.0,141266.0,9475.00,-22.43,50.0,H-SC,14.99,153.0,-0.45,0.94,37.32,OX40N,NTT,CERAMICS
43,INDIGOPNTS,-1.66,-24.69,32.82,0.02,43143.0,-43107.0,131452.0,1408.00,100.33,55.0,M-SC,3.64,222.0,-1.00,0.87,49.14,OX40N,NTT,PAINTS

In [14]:
# top 5 to book for rotation
df_tmp = df_portfolio_features[(df_portfolio_features['Current P/L%'] > 20) ].sort_values(by = 'CumlRnk', ascending=False)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
25,FINCABLES,-0.67,27.75,62.76,107.91,118370.0,40964.0,188608.0,1641.55,14.66,39.0,M-SC,21.90,220.0,0.35,1.25,41.90,OX40N,ATH,CABLES
73,SONACOMS,-1.41,24.97,10.98,38.69,13881.0,25261.0,126420.0,801.69,-1.03,77.0,M-MC,25.01,193.0,1.82,0.84,79.36,AR,ATH,AUTO
68,SATIN,-0.28,41.50,7.30,51.83,28540.0,114672.0,390956.0,274.00,26.15,55.0,H-SC,44.39,159.0,4.02,2.59,90.45,XY24,NTT,FINANCE
60,QUESS,-0.12,20.83,43.92,73.90,56672.0,22242.0,129035.0,424.00,-34.99,69.0,X-SC,31.76,80.0,0.39,0.85,75.90,XY24,NTT,MISC

In [15]:
# top 5 to monitor for exit
df_tmp = df_portfolio_features[~df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])]
df_tmp = df_tmp[(df_tmp['Current P/L%'] > 0) ].sort_values(by = 'Dev%_PE', ascending=False)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
72,SIS,1.16,1.30,19.70,21.26,22159.0,1448.0,112480.0,528.00,2687.05,61.0,H-SC,25.00,168.0,0.07,0.74,67.24,OX40N,NTT,MISC
75,SURYODAY,1.65,5.99,16.09,23.03,30537.0,10720.0,189791.0,216.00,106.14,60.0,H-SC,21.91,166.0,0.35,1.26,61.10,XR,NTT,BANKS
74,STARHEALTH,-0.65,11.73,31.80,47.26,99886.0,32983.0,314106.0,761.00,76.40,50.0,H-SC,18.99,173.0,0.33,2.08,36.31,XY24,NTT,INSURANCE
68,SATIN,-0.28,41.50,7.30,51.83,28540.0,114672.0,390956.0,274.00,26.15,55.0,H-SC,44.39,159.0,4.02,2.59,90.45,XY24,NTT,FINANCE
25,FINCABLES,-0.67,27.75,62.76,107.91,118370.0,40964.0,188608.0,1641.55,14.66,39.0,M-SC,21.90,220.0,0.35,1.25,41.90,OX40N,ATH,CABLES

In [16]:
# top 5 to book for rotation from weak conviction
df_tmp = df_portfolio_features[~df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])]
df_tmp = df_tmp[~df_tmp['Criteria'].isin(['XY25','XY24','X40', 'X40N'])].sort_values(by = 'RRR Ind', ascending=False)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
73,SONACOMS,-1.41,24.97,10.98,38.69,13881.0,25261.0,126420.0,801.69,-1.03,77.0,M-MC,25.01,193.0,1.82,0.84,79.36,AR,ATH,AUTO
91,ZYDUSLIFE,-1.89,18.26,14.68,35.63,36385.0,38278.0,247852.0,1286.17,3.15,50.0,H-MC,17.26,120.0,1.05,1.64,30.32,AR,ATH,PHARMA
25,FINCABLES,-0.67,27.75,62.76,107.91,118370.0,40964.0,188608.0,1641.55,14.66,39.0,M-SC,21.90,220.0,0.35,1.25,41.90,OX40N,ATH,CABLES
75,SURYODAY,1.65,5.99,16.09,23.03,30537.0,10720.0,189791.0,216.00,106.14,60.0,H-SC,21.91,166.0,0.35,1.26,61.10,XR,NTT,BANKS
72,SIS,1.16,1.30,19.70,21.26,22159.0,1448.0,112480.0,528.00,2687.05,61.0,H-SC,25.00,168.0,0.07,0.74,67.24,OX40N,NTT,MISC

In [17]:
# top 5 to accumulate based on lowest RSI_14
df_tmp = df_portfolio_features[df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])].sort_values(by = 'RSI_14', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
39,ICICIGI,-2.11,-15.91,41.39,18.89,69644.0,-31845.0,168264.0,2244.41,-29.15,29.0,X-MC,5.83,66.0,-0.46,1.11,0.00,X40,ATH,INSURANCE
87,VBL,-1.32,-7.62,46.53,35.37,135769.0,-24053.0,291789.0,670.16,-18.49,30.0,X-LC,7.62,13.0,-0.18,1.93,19.93,X40N,ATH,FMCG
81,TMPV,-1.69,-25.30,82.84,36.58,220190.0,-90039.0,265802.0,600.00,-84.72,36.0,X-LC,7.77,4.0,-0.41,1.76,11.71,XY24,NTT,AUTO
34,HDFCBANK,-1.23,-10.03,42.68,28.37,90194.0,-23559.0,211326.0,1073.00,-23.49,36.0,X-LC,10.87,26.0,-0.26,1.40,4.50,X40,BTT,BANKS
23,DMART,0.18,-4.26,35.38,29.60,84543.0,-10644.0,238956.0,5391.45,-19.25,40.0,X-LC,1.92,14.0,-0.13,1.58,9.22,X40N,ATH,FMCG

In [18]:
# top 5 to accumulate based on Spread and CumlRnk
df_tmp = df_portfolio_features[df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])]
df_tmp = df_tmp[(df_tmp['CumlRnk'] < 100)].sort_values(by = 'Spread%', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
11,BERGEPAINT,1.61,-8.11,36.38,25.32,86161.0,-20914.0,236835.0,680.00,-13.04,46.0,X-MC,1.77,68.0,-0.24,1.57,23.26,XY24,NTT,PAINTS
23,DMART,0.18,-4.26,35.38,29.60,84543.0,-10644.0,238956.0,5391.45,-19.25,40.0,X-LC,1.92,14.0,-0.13,1.58,9.22,X40N,ATH,FMCG
19,COLPAL,-0.10,-20.61,76.17,39.86,159256.0,-54285.0,209080.0,3683.41,-3.83,57.0,X-MC,1.96,62.0,-0.34,1.38,18.27,XY25,ATH,FMCG
1,ABBOTINDIA,2.12,-3.13,21.89,18.07,37924.0,-5605.0,173250.0,35195.00,-17.49,77.0,X-MC,2.99,58.0,-0.15,1.15,14.67,X40,ATH,PHARMA
17,CIPLA,-1.66,14.05,17.00,33.43,29695.0,21518.0,174679.0,1648.14,-11.85,45.0,X-LC,3.15,18.0,0.72,1.16,19.25,X40N,ATH,PHARMA

In [19]:
# top 5 to accumulate based on lowest Gained%
df_tmp = df_portfolio_features[df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])].sort_values(by = 'Gained%', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
39,ICICIGI,-2.11,-15.91,41.39,18.89,69644.0,-31845.0,168264.0,2244.41,-29.15,29.0,X-MC,5.83,66.0,-0.46,1.11,0.00,X40,ATH,INSURANCE
35,HDFCLIFE,-2.24,-9.72,46.99,32.71,63549.0,-14560.0,135240.0,811.41,-29.56,40.0,X-LC,15.39,31.0,-0.23,0.90,1.60,X40,ATH,INSURANCE
47,ITC,0.34,-25.73,60.31,19.06,152359.0,-87539.0,252627.0,452.00,-59.16,45.0,X-LC,12.51,1.0,-0.57,1.67,2.32,X40,NTT,FMCG
65,RELIANCE,-1.10,-17.23,51.39,25.30,85479.0,-34630.0,166333.0,1952.00,-19.26,45.0,X-LC,7.44,21.0,-0.41,1.10,2.43,XY25,BTT,REFINERIES
58,PGHH,2.60,-32.93,96.84,32.01,138675.0,-70320.0,143200.0,17616.87,-54.64,48.0,X-MC,20.22,57.0,-0.51,0.95,2.63,X40,ATH,FMCG

In [20]:
# top 5 to accumulate based on lowest CurrAlloc%
df_tmp = df_portfolio_features[df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])].sort_values(by = 'CurrAlloc%', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
10,BATAINDIA,-0.62,-55.20,201.78,35.20,116322.0,-71022.0,57648.0,2096.00,-24.48,51.0,X-SC,17.77,91.0,-0.61,0.38,14.33,X40,NTT,FOOTWEAR
64,RELAXO,-3.14,-48.45,195.44,52.31,146254.0,-70327.0,74833.0,1176.00,-45.12,53.0,X-SC,12.32,92.0,-0.48,0.50,67.32,X40N,NTT,FOOTWEAR
60,QUESS,-0.12,20.83,43.92,73.90,56672.0,22242.0,129035.0,424.00,-34.99,69.0,X-SC,31.76,80.0,0.39,0.85,75.90,XY24,NTT,MISC
35,HDFCLIFE,-2.24,-9.72,46.99,32.71,63549.0,-14560.0,135240.0,811.41,-29.56,40.0,X-LC,15.39,31.0,-0.23,0.90,1.60,X40,ATH,INSURANCE
28,GODREJCP,0.74,-4.96,38.33,31.47,54140.0,-7368.0,141246.0,1469.04,0.03,52.0,X-LC,6.30,32.0,-0.14,0.93,8.38,X40N,ATH,FMCG

In [21]:
# top 5 to accumulate based on CumlRnk
df_tmp = df_portfolio_features.sort_values(by = 'CumlRnk', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
47,ITC,0.34,-25.73,60.31,19.06,152359.0,-87539.0,252627.0,452.00,-59.16,45.0,X-LC,12.51,1.0,-0.57,1.67,2.32,X40,NTT,FMCG
79,TCS,-0.72,-35.27,91.86,24.20,275483.0,-163379.0,299894.0,4230.71,-45.26,55.0,X-LC,19.85,2.0,-0.59,1.98,11.83,X40,ATH,IT
45,INFY,-2.38,-28.66,88.17,34.24,196817.0,-89664.0,223224.0,1972.00,-43.76,43.0,X-LC,20.89,3.0,-0.46,1.48,6.36,X40,NTT,IT
81,TMPV,-1.69,-25.30,82.84,36.58,220190.0,-90039.0,265802.0,600.00,-84.72,36.0,X-LC,7.77,4.0,-0.41,1.76,11.71,XY24,NTT,AUTO
59,PIDILITIND,-0.77,11.90,5.78,18.37,9127.0,16790.0,157900.0,1670.26,-21.61,53.0,X-LC,8.10,5.0,1.84,1.05,23.98,X40,ATH,CHEMICALS

In [22]:
# top 5 for average up
df_tmp = df_portfolio_features[(df_portfolio_features['Dev%_200'] > 5)].sort_values(by = 'CurrAlloc%', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
44,INDUSINDBK,1.09,-20.63,67.44,32.89,41324.0,-15932.0,61275.0,1800.00,-388.52,75.0,L-MC,12.91,258.0,-0.39,0.41,51.07,XR,NTT,BANKS
64,RELAXO,-3.14,-48.45,195.44,52.31,146254.0,-70327.0,74833.0,1176.00,-45.12,53.0,X-SC,12.32,92.0,-0.48,0.50,67.32,X40N,NTT,FOOTWEAR
3,ALKYLAMINE,-1.80,-23.17,150.62,92.54,116833.0,-23395.0,77568.0,4520.85,-17.74,48.0,H-SC,11.88,142.0,-0.20,0.51,47.29,SR,ATH,CHEMICALS
83,TTKPRESTIG,-1.48,-14.78,17.45,0.09,14987.0,-14893.0,85884.0,770.00,99.36,63.0,M-SC,9.91,250.0,-0.99,0.57,52.93,OX40N,NTT,DURABLES
72,SIS,1.16,1.30,19.70,21.26,22159.0,1448.0,112480.0,528.00,2687.05,61.0,H-SC,25.00,168.0,0.07,0.74,67.24,OX40N,NTT,MISC

In [23]:
# top 5 RSP
df_tmp = df_portfolio_features.sort_values(by = 'RSP', ascending=False)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
60,QUESS,-0.12,20.83,43.92,73.90,56672.0,22242.0,129035.0,424.00,-34.99,69.0,X-SC,31.76,80.0,0.39,0.85,75.90,XY24,NTT,MISC
44,INDUSINDBK,1.09,-20.63,67.44,32.89,41324.0,-15932.0,61275.0,1800.00,-388.52,75.0,L-MC,12.91,258.0,-0.39,0.41,51.07,XR,NTT,BANKS
73,SONACOMS,-1.41,24.97,10.98,38.69,13881.0,25261.0,126420.0,801.69,-1.03,77.0,M-MC,25.01,193.0,1.82,0.84,79.36,AR,ATH,AUTO
83,TTKPRESTIG,-1.48,-14.78,17.45,0.09,14987.0,-14893.0,85884.0,770.00,99.36,63.0,M-SC,9.91,250.0,-0.99,0.57,52.93,OX40N,NTT,DURABLES
22,DIXON,-0.64,2.20,34.96,37.92,93180.0,5734.0,266532.0,18931.72,-56.54,63.0,X-MC,7.22,54.0,0.06,1.76,45.02,X40N,ATH,IT

In [24]:
# Top N allocation
df_tmp = df_portfolio_features.sort_values(by = 'CurrAlloc%', ascending=False)
top_n_values = [10, 25, 50]

sum_df = pd.DataFrame({
    'Top_N': top_n_values,
    'Sum_Alloc%': [df_tmp['CurrAlloc%'].head(n).sum() for n in top_n_values]
})

sum_df

   Top_N  Sum_Alloc%
0     10       19.10
1     25       42.31
2     50       72.58

In [25]:
# market-cap-wise allocation
df_tmp = df_portfolio_features[cols]
df_tmp.groupby(df_tmp['Conviction'].str[-2:])['CurrAlloc%'].sum().sort_values(ascending=False)

Conviction
SC    43.50
LC    30.11
MC    26.41
Name: CurrAlloc%, dtype: float64

In [26]:
# criteria-wise allocation
df_portfolio_features.groupby('Criteria')['CurrAlloc%'].sum().sort_values(ascending=False)

Criteria
XY24     27.41
X40      24.76
X40N     17.44
XR        8.93
OX40N     7.07
AR        7.00
XY25      6.52
SR        0.89
Name: CurrAlloc%, dtype: float64

In [27]:
# conviction-wise allocation
df_portfolio_features.groupby('Conviction')['CurrAlloc%'].sum().sort_values(ascending=False)

Conviction
X-LC    28.10
H-SC    22.78
X-MC    21.14
X-SC    10.20
M-SC     9.97
H-MC     2.71
M-MC     2.15
H-LC     1.21
M-LC     0.80
L-SC     0.55
L-MC     0.41
Name: CurrAlloc%, dtype: float64

In [28]:
# sector-wise stats
df_tmp = df_portfolio_features.groupby('Category')[['CurrAlloc%', 'Current', 'Current P/L', 'FTT Amt']].sum().sort_values(by=['Current', 'Current P/L'], ascending=False)
df_tmp['Current P/L%'] = round(df_tmp['Current P/L'] * 100 / df_tmp['Current'], 2)
df_tmp['FTT%'] = round(df_tmp['FTT Amt'] * 100 / df_tmp['Current'], 2)
cols = ['CurrAlloc%', 'Current P/L%', 'FTT%']
df_tmp[cols].sort_values(by=['CurrAlloc%'], ascending=False)

               CurrAlloc%  Current P/L%    FTT%
Category
FMCG                14.33        -22.10   64.93
FINANCE             11.25         -8.47   55.46
IT                  10.12        -47.37  120.31
MISC                 7.31        -21.25   73.28
AUTO                 6.67         -8.65   49.16
BANKS                5.56         -8.33   58.39
PAINTS               5.43        -20.22   40.73
PHARMA               5.29          7.16   21.57
INSURANCE            5.16         -6.28   42.13
ELECTRICAL           4.15        -12.78   52.45
CHEMICALS            2.16        -24.61   98.53
HEALTHCARE           2.10        -12.61   42.00
APPARELS             1.84          3.49   28.93
AC                   1.79        -17.84   49.79
FOOTWEAR             1.71        -71.27  139.95
REALTY               1.66         11.39    3.17
DURABLES             1.63        -57.06   95.27
BREWERIES            1.59          2.50   17.75
TRAVEL               1.51        -95.87  193.95
CERAMICS             1.43        -42.82   86.22
CABLES               1.25         21.72   62.76
ENGINEERING          1.24        -29.68   89.00
JEWELLERY            1.13        -87.32  152.41
REFINERIES           1.10        -20.82   51.39
CEMENT               1.08        -64.55  187.65
ENTERTAINMENT        0.72        -77.11  182.74
TEXTILES             0.42        -46.99   88.90
HOTELS               0.39        -91.39  158.90

In [29]:
# money to be made criteria-wise
df_portfolio_features.groupby('Criteria')['FTT Amt'].agg(['sum', 'count']).sort_values(by='sum', ascending=False)

                sum  count
Criteria
XY24      3456274.0     21
X40       1931003.0     19
XR        1330056.0     13
AR        1117330.0      9
X40N      1084204.0     13
OX40N      724539.0     10
XY25       450183.0      5
SR         283268.0      2

In [30]:
# money to be made conviction-wise
df_portfolio_features.groupby('Conviction')['FTT Amt'].agg(['sum', 'count']).sort_values(by='sum', ascending=False)

                  sum  count
Conviction
H-SC        3333173.0     24
X-LC        2028169.0     21
X-MC        1523331.0     15
M-SC        1412309.0     14
X-SC        1259884.0      9
H-MC         287963.0      2
L-SC         207944.0      2
M-LC         170828.0      1
M-MC          61150.0      2
H-LC          50782.0      1
L-MC          41324.0      1

In [31]:
# money to be made criteria and conviction-wise
df_portfolio_features.groupby(['Conviction', 'Criteria'])['FTT Amt'].agg(['sum', 'count']).sort_values(by='sum', ascending=False)

                           sum  count
Conviction Criteria
X-LC       X40       1053423.0     10
H-SC       XY24      1022090.0      6
           AR         940380.0      5
M-SC       XY24       830883.0      6
H-SC       XR         787227.0      7
X-SC       XY24       744518.0      4
X-MC       X40        667745.0      7
X-LC       X40N       400152.0      6
X-MC       X40N       378521.0      4
X-LC       XY24       370767.0      2
M-SC       OX40N      310659.0      5
X-SC       X40N       305531.0      3
H-SC       OX40N      300208.0      4
           SR         283268.0      2
H-MC       XY24       251578.0      1
X-MC       XY25       240627.0      2
           XY24       236438.0      2
X-SC       X40        209835.0      2
M-SC       XR         194865.0      2
M-LC       XR         170828.0      1
X-LC       XY25       162287.0      2
L-SC       OX40N      113672.0      1
           XR          94272.0      1
M-SC       AR          75902.0      1
H-LC       AR          50782.0      1
M-MC       XY25        47269.0      1
X-LC       XR          41540.0      1
L-MC       XR          41324.0      1
H-MC       AR          36385.0      1
M-MC       AR          13881.0      1

In [32]:
# notebook execution time

end_time = time.time()
execution_time = round(end_time - start_time, 0)
print(f"Notebook execution time: {execution_time} seconds")

Notebook execution time: 27.0 seconds