<a href="https://colab.research.google.com/github/ankit-rathi/Quantvesting_v2/blob/main/myStocks_Portfolio_Analysis.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
'''
!pip install pandas==2.2.2 -qq
!pip install pyxirr -qq
!pip install ta -qq
!pip install yfinance==0.2.59 -qq
'''

'\n!pip install pandas==2.2.2 -qq\n!pip install pyxirr -qq\n!pip install ta -qq\n!pip install yfinance==0.2.59 -qq\n'

In [2]:
# import libraries

import numpy as np
import pandas as pd
import datetime
import warnings
warnings.filterwarnings('ignore')
import yfinance as yfin
import ta
import matplotlib.pyplot as plt
import requests

In [3]:
# notebook start time
import time
import datetime
import pytz

start_time = time.time()

# function to print date timestamp
def print_date_time():
  tz_NY = pytz.timezone('Asia/Kolkata')
  datetime_NY = datetime.datetime.now(tz_NY)
  print("Run date time (IST):", datetime_NY.strftime("%Y-%m-%d %H:%M:%S"))

In [4]:
# function to get booked and reserved amount
def get_amt():
  # fetch the JSON data from the URL
  url = "https://raw.githubusercontent.com/ankit-rathi/Tradevesting_v1/main/data/myPortfolioAmts.json"
  response = requests.get(url)
  pf_amts = response.json()  # parse the JSON data

  # extract values from the JSON
  py_booked_amt_dm = pf_amts["py_booked_amt_dm"]
  py_booked_amt_sv = pf_amts["py_booked_amt_sv"]
  cy_booked_amt_dm = pf_amts["cy_booked_amt_dm"]
  cy_booked_amt_sv = pf_amts["cy_booked_amt_sv"]
  reserve_amt_dm = pf_amts["reserve_amt_dm"]
  reserve_amt_sv = pf_amts["reserve_amt_sv"]

  # perform calculations
  py_booked_amt = py_booked_amt_dm + py_booked_amt_sv
  cy_booked_amt = cy_booked_amt_dm + cy_booked_amt_sv
  reserve_amt = reserve_amt_dm + reserve_amt_sv
  total_booked_amt = py_booked_amt + cy_booked_amt

  return total_booked_amt, reserve_amt, cy_booked_amt, py_booked_amt

gen_output = 0

In [5]:
# function to format the amount
def format_amt(number):
    abs_number = abs(number)

    if abs_number >= 1_00_00_000:  # Crores
        formatted_amt = f"{number / 1_00_00_000:.2f} C"
    elif abs_number >= 1_00_000:  # Lakhs
        formatted_amt = f"{number / 1_00_000:.2f} L"
    elif abs_number >= 1_000:  # Thousands
        formatted_amt = f"{number / 1_000:.2f} K"
    else:
        formatted_amt = f"{number:.2f}"

    return formatted_amt

# function to set start and end date
def get_start_end_date():
  start_date = (datetime.date.today() + datetime.timedelta(days=-365)).strftime('%Y-%m-%d')
  end_date = (datetime.date.today() + datetime.timedelta(days=1)).strftime('%Y-%m-%d')
  return start_date, end_date

# function to fetch my portfolio csv
def get_mypfs_df():
  mypfs_df = pd.read_csv('https://raw.githubusercontent.com/ankit-rathi/Tradevesting_v1/main/data/myPortfolioStocks.csv')
  return mypfs_df

# function to fetch my prospects csv
def get_mypps_df():
  mypps_df = pd.read_csv('https://raw.githubusercontent.com/ankit-rathi/Tradevesting_v1/main/data/myProspectsScrips.csv')
  return mypps_df

# function to fetch screener data
def get_myscreen_df():
  myscreen_df = pd.read_csv('https://raw.githubusercontent.com/ankit-rathi/Tradevesting_v1/main/data/myScreenerDB.csv')
  return myscreen_df

# function to fetch momentum data
def get_myinvmt_df():
  myinvmt_df = pd.read_csv('https://raw.githubusercontent.com/ankit-rathi/Tradevesting_v1/main/data/myInvestments.csv')
  return myinvmt_df

# function to get the stock ids
def get_stock_ids(df_pf):
  stock_n100 = df_pf['Symbol'].unique()

  exclude = ['CADILAHC','MMTC', 'MASFIN']

  stock_ids = df_pf[~df_pf['Symbol'].isin(exclude) ]['Symbol'].unique()

  #mypf = mypf[mypf.Forecast.notnull()]
  #stock_ids = mypf['Symbol'].unique()

  #stock_ids.sort()
  return stock_ids

# get features from screener data
def get_screener_features():
  myscreen_df = get_myscreen_df()
  cols = ['Symbol', 'EPS', 'MedPE', 'ROCE%', 'ROE%', 'CapType']
  return myscreen_df[cols]

# get relative strength
def get_relative_strength(stock_list):

    # Dictionary to store stock tickers and their corresponding percentage price change
    stock_changes = {}

    # Loop through each stock and fetch its price data
    for stock in stock_list:
        try:
            # Download the stock data for the given date range
            stock_data = yfin.Ticker(stock + '.NS').history(period='1mo', interval='1d')[map(str.title, ['open', 'close', 'low', 'high', 'volume'])]

            # Calculate the percentage change for the stock
            if len(stock_data) > 0:
                start_price = stock_data['Close'].iloc[0]
                end_price = stock_data['Close'].iloc[-1]
                percent_change = round(((end_price - start_price) / start_price) * 100, 2)
                stock_changes[stock] = percent_change
            else:
                stock_changes[stock] = np.nan  # If no data is available, set to NaN

        except Exception as e:
            print(f"Error fetching data for {stock}: {e}")
            stock_changes[stock] = np.nan

    # Create a DataFrame with stock tickers and their percentage changes
    df = pd.DataFrame(list(stock_changes.items()), columns=['Symbol', 'Percent_Change'])

    # Drop any stocks with missing data (NaN values)
    df = df.dropna()

    # Calculate the percentile rank based on percentage change
    df['RSP'] = round(df['Percent_Change'].rank(pct=True) * 100, 2)
    cols = ['Symbol', 'RSP']
    df = df[cols]
    # Sort by percentile rank (optional)
    df = df.sort_values(by='RSP', ascending=False).reset_index(drop=True)

    return df

In [6]:
# function to get stock technicals
def stock_prec_dev(stock_symbol):
    #stock_symbol = 'ULTRACEMCO.NS'
    short_window = 20
    mid_window = 50
    long_window = 200
    moving_avg = 'SMA'

    start = datetime.datetime(*map(int, start_date.split('-')))
    end = datetime.datetime(*map(int, end_date.split('-')))

    stock_df = yfin.Ticker(stock_symbol + '.NS').history(period='max', interval='1d')[map(str.title, ['open', 'close', 'low', 'high', 'volume'])]

    stock_df['Max'] = round(max(stock_df['Close']),2)
    stock_df = stock_df[(stock_df.index <= end_date) & (stock_df.index >= start_date)]
    stock_df['200_SMA'] = round(stock_df['Close'].rolling(window = 200, min_periods = 1).mean(),0)
    stock_df['Dev%_200'] = round((stock_df['Close'] - stock_df['200_SMA'])*100/stock_df['200_SMA'],2)
    stock_df.dropna(axis = 0, inplace = True) # remove any null rows

    stock_df['20_SMA'] = stock_df['Close'].rolling(window=20).mean()
    stock_df['50_SMA'] = stock_df['Close'].rolling(window=50).mean()
    stock_df['Symbol'] = stock_symbol

    stock_df['Close'] = round(stock_df['Close'],2)
    stock_df['Min'] = round(min(stock_df['Close']),2)
    stock_df['RSI_14'] = ta.momentum.RSIIndicator(close=stock_df['Close'], window=14).rsi()
    stock_df['RSI_14'] = round(stock_df['RSI_14'],0)
    stock_df['Prev_Close'] = stock_df['Close'].shift(1)
    stock_df.drop(['Open', 'Low', 'High', 'Volume'], axis=1, inplace=True)
    stock_df = stock_df.tail(1)

    max_SMA = max(stock_df['20_SMA'].item(), stock_df['50_SMA'].item(), stock_df['200_SMA'].item())
    min_SMA = min(stock_df['20_SMA'].item(), stock_df['50_SMA'].item(), stock_df['200_SMA'].item())
    ABS_Spread = max_SMA - min_SMA
    stock_df['Spread%'] = round((ABS_Spread / stock_df['200_SMA'].item()) * 100,2)

    return stock_df

# function to compute stock attributes
def get_common_features(stock_ids, df_mypf):

  df_prec_dev = pd.DataFrame()
  df_tmp = get_screener_features()
  df_rs = get_relative_strength(stock_ids)

  for stock_id in stock_ids:
      tmp = stock_prec_dev(stock_id)
      tmp = tmp.reset_index()
      df_prec_dev = pd.concat([df_prec_dev, tmp], ignore_index = True)
  df_prec_dev = pd.merge(df_prec_dev, df_mypf, on= 'Symbol')
  df_prec_dev = pd.merge(df_prec_dev, df_tmp, on= 'Symbol', how='left')
  df_prec_dev = pd.merge(df_prec_dev, df_rs, on= 'Symbol', how='left')
  #print(df_prec_dev.columns)
  df_prec_dev['Curr_PE'] = round(df_prec_dev['Close']/df_prec_dev['EPS'],1)
  df_prec_dev['Dev%_PE'] = round((df_prec_dev['Curr_PE'] - df_prec_dev['MedPE'])*100/df_prec_dev['MedPE'],2)
  df_prec_dev['Conviction'] = df_prec_dev['Conviction'] + '-' + df_prec_dev['CapType']
  return df_prec_dev

# function to arrange stock features
def arrange_features(df_stocks, common_cols, diff_cols):
  df_stocks_common = df_stocks[common_cols].drop_duplicates()
  df_stocks_diff = df_stocks[diff_cols]
  df_stocks_diff['Investment'] = df_stocks_diff['AvgCost'] * df_stocks_diff['Shares']
  df_stocks_diff = df_stocks_diff.groupby(['Symbol'])[['Shares', 'Investment']].aggregate(['sum']).reset_index()
  df_stocks_diff.columns = ['Symbol', 'Shares', 'Investment']
  df_stocks_diff['AvgCost'] = round(df_stocks_diff['Investment']/df_stocks_diff['Shares'],2)
  df_stocks = pd.merge(df_stocks_diff, df_stocks_common, on='Symbol')
  return df_stocks

# plot fact distribution across dimension
def plot_pie_chart(df, dimension, fact):
  # grouping the data by category and calculating the sum of fact for each type
  grouped_data = df.groupby(dimension)[fact].sum()

  # sorting the grouped data in descending order
  grouped_data = grouped_data.sort_values(ascending=False)

  # creating a pie chart
  grouped_data.plot.pie(autopct='%1.1f%%', startangle=90, figsize=(6, 6))

  # adding a title and displaying the plot
  plt.title(f'{dimension} {fact} Distribution')
  plt.ylabel('')  # To hide the y-label
  plt.show()

In [7]:
# function to get portfolio features

def get_portfolio_features(df_common_features):

  print_date_time()
  print('-------------------')

  #df_common_features["Target"] = df_common_features["Target"].fillna(df_common_features["Max"])
  df_common_features['NTT'] = np.where(df_common_features['Strategy']== 'NTT', df_common_features["Target"], df_common_features['Max'])
  df_common_features['LTT'] = np.where(df_common_features['Strategy']== 'BTT', df_common_features["Target"], df_common_features['Max'])
  df_common_features['BOL'] = df_common_features['Min']

  tmp_df = df_common_features[df_common_features['Symbol'].isin(mypf_df[mypf_df['InPortfolio'] != 'NA'].Symbol.values)]
  print('qualified stocks: '+str(len(tmp_df['Symbol'].unique())))
  tmp_df1 = tmp_df[tmp_df['LatestQtr'] == 1]
  print('with latest results: '+str(len(tmp_df1['Symbol'].unique())))
  tmp_df1 = tmp_df1[tmp_df1['StarStock'] == 1]
  print('still star stocks: '+str(len(tmp_df1['Symbol'].unique())))
  tmp_df['Investment'] = tmp_df['AvgCost'] * tmp_df['Shares']
  tmp_df['Current'] = round(tmp_df['Close'] * tmp_df['Shares'],0)
  tmp_df['Previous'] = tmp_df['Prev_Close'] * tmp_df['Shares']
  tmp_df['EstimatedST'] = tmp_df['NTT'] * tmp_df['Shares']
  tmp_df['EstimatedLT'] = tmp_df['LTT'] * tmp_df['Shares']
  tmp_df['Current P/L'] = round((tmp_df['Current'] - tmp_df['Investment']),0)
  tmp_df['Today P/L%'] = round((tmp_df['Current'] - tmp_df['Previous'])*100/tmp_df['Previous'],2)
  tmp_df['Current P/L%'] = round((tmp_df['Current'] - tmp_df['Investment'])*100/tmp_df['Investment'],2)
  tmp_df['EstimatedST P/L%'] = round((tmp_df['EstimatedST'] - tmp_df['Investment'])*100/tmp_df['Investment'],2)
  tmp_df['EstimatedLT P/L%'] = round((tmp_df['EstimatedLT'] - tmp_df['Investment'])*100/tmp_df['Investment'],2)
  tmp_df['NTT%'] = round((tmp_df['NTT'] - tmp_df['Close'])*100/tmp_df['Close'],2)
  tmp_df['LTT%'] = round((tmp_df['LTT'] - tmp_df['Close'])*100/tmp_df['Close'],2)
  tmp_df['Gained%'] = round((tmp_df['Close'] - tmp_df['BOL'])*100/tmp_df['BOL'],2)
  investment = round(sum(tmp_df['AvgCost']*tmp_df['Shares']),0)
  current = round(sum(tmp_df['Close']*tmp_df['Shares']),0)
  tmp_df['InitAlloc%'] = round(tmp_df['Investment']*100/investment,2)
  tmp_df['CurrAlloc%'] = round(tmp_df['Current']*100/current,2)
  tmp_df['FTT'] = tmp_df['LTT']
  tmp_df.loc[tmp_df['Strategy'] == 'NTT', 'FTT'] = tmp_df['NTT']
  tmp_df['FTT%'] = tmp_df['LTT%']
  tmp_df.loc[tmp_df['Strategy'] == 'NTT', 'FTT%'] = tmp_df['NTT%']
  tmp_df['FTT Amt'] = round(tmp_df['FTT%'] * tmp_df['Current']/100,0)
  tmp_df['OTT%'] = round((tmp_df['FTT'] - tmp_df['AvgCost'])*100/tmp_df['AvgCost'],2)
  tmp_df['RRR Ind'] = round(tmp_df['Current P/L']/tmp_df['FTT Amt'],2)
  tmp_df['Risk Ind'] = round(tmp_df['Current P/L%']*tmp_df['CurrAlloc%'],0)

  return tmp_df

# function to print portfolio features
def print_portfolio_stats(df_portfolio_features, myinvmt_df):
  from pyxirr import xirr

  total_booked_amt, reserve_amt, cy_booked_amt, py_booked_amt = get_amt()

  dates = myinvmt_df['Date'].values
  dates = np.append(dates, datetime.date.today().strftime('%d-%b-%y'))
  investment = myinvmt_df['Investment'].values
  dates= pd.to_datetime(dates)

  current = round(sum(df_portfolio_features['Close']*df_portfolio_features['Shares']),0) + reserve_amt
  investment_xirr = np.append(investment, current)
  cagr = round(xirr(pd.DataFrame({"dates": dates, "amounts": investment_xirr}))*100,2)

  investment = -sum(investment)
  invested = round(sum(df_portfolio_features['AvgCost']*df_portfolio_features['Shares']),0) + reserve_amt
  previous = round(sum(df_portfolio_features['Prev_Close']*df_portfolio_features['Shares']),0) + reserve_amt
  cy_invested = investment + py_booked_amt

  today_pnl_amount = current-previous
  today_pnl_percentage = round((current-previous)*100/previous,2)

  curr_pnl_amount = current-invested
  curr_pnl_percentage = round((curr_pnl_amount)*100/(cy_invested),2)

  cy_pnl_amount = cy_booked_amt + curr_pnl_amount
  cy_pnl_percentage = round((cy_pnl_amount)*100/cy_invested,2)

  overall_pnl_amount = total_booked_amt + curr_pnl_amount
  overall_pnl_percentage = round((overall_pnl_amount)*100/investment,2)

  estimate_st = round(sum(df_portfolio_features['FTT']*df_portfolio_features['Shares']),0)  + reserve_amt
  est_st_pnl_amount = estimate_st-current
  est_st_pnl_percentage = round((est_st_pnl_amount)*100/current,2)

  estimate_lt = round(sum(df_portfolio_features['LTT']*df_portfolio_features['Shares']),0)  + reserve_amt
  est_lt_pnl_amount = estimate_lt-current
  est_lt_pnl_percentage = round((est_lt_pnl_amount)*100/current,2)

  total_profit = round(sum(df_portfolio_features[df_portfolio_features['Current P/L%'] > 0]['Current']) - sum(df_portfolio_features[df_portfolio_features['Current P/L%'] > 0]['Investment']),0)
  total_loss = round(sum(df_portfolio_features[df_portfolio_features['Current P/L%'] < 0]['Current']) - sum(df_portfolio_features[df_portfolio_features['Current P/L%'] < 0]['Investment']),0)

  cy_booked_percentage = round((cy_booked_amt)*100/current,2)
  py_booked_percentage = round((py_booked_amt)*100/investment,2)
  total_booked_percentage = round((total_booked_amt)*100/investment,2)

  print('-------------------')
  print('Initial Investment: ', format_amt(investment))
  print('CY Investment: ', format_amt(cy_invested))
  print('Reserve: ', format_amt(reserve_amt))
  print('Current: ',  format_amt(current))
  print('-------------------')
  print('Today PnL: '+ '{} ({}%)'.format(format_amt(today_pnl_amount), today_pnl_percentage))
  print('Current PnL: '+ '{} ({}%)'.format(format_amt(curr_pnl_amount), curr_pnl_percentage))
  print('CY Booked + Current PnL: '+ '{} ({}%)'.format(format_amt(cy_pnl_amount), cy_pnl_percentage))
  print('-------------------')
  print('Total profit: ', format_amt(total_profit))
  print('Total loss: ', format_amt(total_loss))
  print('-------------------')
  print('Total Booked + Current PnL: '+ '{} ({}%)'.format(format_amt(overall_pnl_amount), overall_pnl_percentage))
  print('Total Booked PnL: '+ '{} ({}%)'.format(format_amt(total_booked_amt), total_booked_percentage))
  print('Curr Year Booked PnL: '+ '{} ({}%)'.format(format_amt(cy_booked_amt), cy_booked_percentage))
  print('Prev Year Booked PnL: '+ '{} ({}%)'.format(format_amt(py_booked_amt), py_booked_percentage))
  print('===================')
  print('Est FTT: ',  format_amt(estimate_st))
  print('Est FTT PnL: '+ '{} ({}%)'.format(format_amt(est_st_pnl_amount), est_st_pnl_percentage))

  print('===================')
  print('Deployed: ', format_amt(investment))

  print('Current: ', format_amt(current))

  print('CAGR/XIRR %: '+'{}%'.format(cagr))

In [8]:
# get start and end date
start_date, end_date = get_start_end_date()

# get portfolio and prospects data
mypfs_df = get_mypfs_df()
mypps_df = get_mypps_df()
myinvmt_df = get_myinvmt_df()

# merge above datasets
mypf_df = pd.merge(mypfs_df, mypps_df, on="Symbol")

# seggregate dm and sv portfolio
dm_pf = mypf_df[mypf_df['InPortfolio'] == 'DM']
sv_pf = mypf_df[mypf_df['InPortfolio'] == 'SV']

# build portfolio stock dataframe
dm_stocks = get_stock_ids(dm_pf)
sv_stocks = get_stock_ids(sv_pf)
df_stocks = pd.concat([dm_pf,sv_pf], ignore_index = True)

# arrange common and diff stock features
common_cols = ['Symbol', 'Target', 'Criteria', 'Strategy', 'CumlRnk', 'LatestQtr', 'StarStock', 'Conviction', 'Category', 'InFolio', 'XIRR', 'MBQ']
diff_cols = ['Symbol', 'AvgCost', 'Shares']
df_stocks = arrange_features(df_stocks, common_cols, diff_cols)

# get common features
stock_ids = df_stocks['Symbol'].values
df_common_features = get_common_features(stock_ids, df_stocks)

df_common_features.reset_index(drop=True, inplace=True)
df_common_features.drop(['Date'], axis=1, inplace=True)
# get and print portfolio features
df_portfolio_features = get_portfolio_features(df_common_features)

print_portfolio_stats(df_portfolio_features, myinvmt_df)

df = df_portfolio_features
#plot_pie_chart(df, 'CapType', 'Current')
list_ox40n = list(df[df['MBQ'].str.contains('OX40N', na=False)]['Symbol'].values)

Run date time (IST): 2026-08-26 10:26:06
-------------------
qualified stocks: 87
with latest results: 30
still star stocks: 19
-------------------
Initial Investment:  1.46 C
CY Investment:  1.89 C
Reserve:  3.69 L
Current:  1.58 C
-------------------
Today PnL: 49.30 K (0.31%)
Current PnL: -34.91 L (-18.48%)
CY Booked + Current PnL: -29.85 L (-15.8%)
-------------------
Total profit:  3.87 L
Total loss:  -38.78 L
-------------------
Total Booked + Current PnL: 13.02 L (8.91%)
Total Booked PnL: 47.93 L (32.82%)
Curr Year Booked PnL: 5.06 L (3.2%)
Prev Year Booked PnL: 42.87 L (29.35%)
===================
Est FTT:  2.67 C
Est FTT PnL: 1.09 C (69.0%)
===================
Deployed:  1.46 C
Current:  1.58 C
CAGR/XIRR %: 3.54%

In [9]:
# top 5 near their targets
cols = ['Symbol', 'Today P/L%', 'Current P/L%', 'FTT%', 'OTT%', 'FTT Amt', 'Current P/L', 'Current', 'FTT', 'Dev%_PE', 'RSI_14','Conviction', 'Spread%',  'CumlRnk', 'RRR Ind', 'CurrAlloc%', 'Gained%', 'Criteria', 'Strategy', 'Category']
df_tmp = df_portfolio_features[~df_portfolio_features['Symbol'].isin(['ENRIN','BLUSPRING','DIGITIDE'])]
df_tmp = df_tmp.sort_values(by = 'FTT Amt', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
66,SIEMENS,-0.11,9.78,0.96,10.83,1961.0,18200.0,204295.0,4125.00,-11.09,67.0,H-LC,15.70,51.0,9.28,1.32,44.14,AR,NTT,ELECTRICAL
78,UNITDSPR,-1.16,12.54,7.31,20.77,19262.0,29360.0,263504.0,1644.00,-3.97,58.0,X-MC,12.33,64.0,1.52,1.71,26.66,X40N,NTT,BREWERIES
77,TTKPRESTIG,3.74,-20.72,26.25,0.09,20973.0,-20880.0,79897.0,770.00,-3.55,50.0,M-SC,8.22,250.0,-1.00,0.52,43.80,OX40N,NTT,DURABLES
52,M&M,-0.51,8.16,9.86,18.82,25668.0,19642.0,260323.0,3762.88,-6.55,58.0,X-LC,5.26,25.0,0.77,1.69,18.09,X40N,ATH,AUTO
50,KOTAKBANK,2.12,7.78,10.33,18.92,26689.0,18661.0,258363.0,452.46,-8.76,67.0,X-LC,2.11,12.0,0.70,1.67,16.24,X40,ATH,BANKS

In [10]:
# top 5 today
df_tmp = df_portfolio_features.sort_values(by = 'Today P/L%', ascending=False)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
63,ROUTE,6.47,-60.14,317.16,66.28,168222.0,-80026.0,53040.0,2190.73,NaN,51.0,NaN,6.72,141.0,-0.48,0.34,27.79,SR,ATH,IT
69,SURYODAY,3.96,-10.57,37.58,23.03,60181.0,-18931.0,160140.0,216.00,-26.71,44.0,H-SC,14.46,166.0,-0.31,1.04,35.93,XR,NTT,BANKS
77,TTKPRESTIG,3.74,-20.72,26.25,0.09,20973.0,-20880.0,79897.0,770.00,-3.55,50.0,M-SC,8.22,250.0,-1.00,0.52,43.80,OX40N,NTT,DURABLES
27,GLAXO,3.66,22.00,11.23,35.69,27302.0,43836.0,243120.0,3380.16,-8.54,75.0,X-MC,12.98,56.0,1.61,1.58,44.49,X40,ATH,PHARMA
8,BAJAJHLDNG,2.57,2.47,25.15,28.24,65978.0,6333.0,262338.0,14274.15,-7.44,57.0,X-LC,6.96,28.0,0.10,1.70,32.03,X40,ATH,FINANCE

In [11]:
# bottom 5 today
df_tmp = df_portfolio_features.sort_values(by = 'Today P/L%', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
60,RELAXO,-2.61,-52.38,219.83,52.31,151964.0,-76032.0,69128.0,1176.00,NaN,36.0,NaN,11.15,92.0,-0.50,0.45,54.56,X40N,NTT,FOOTWEAR
82,VBL,-1.86,-12.89,55.73,35.66,170803.0,-45361.0,306483.0,669.42,-28.82,40.0,X-LC,6.92,13.0,-0.27,1.99,12.84,X40N,ATH,FMCG
45,INFY,-1.40,-19.70,74.82,40.38,226184.0,-74166.0,302304.0,1972.00,-40.86,49.0,X-LC,15.34,3.0,-0.33,1.96,14.48,X40,NTT,IT
78,UNITDSPR,-1.16,12.54,7.31,20.77,19262.0,29360.0,263504.0,1644.00,-3.97,58.0,X-MC,12.33,64.0,1.52,1.71,26.66,X40N,NTT,BREWERIES
12,BOSCH-HCIL,-1.14,-27.15,37.25,-0.01,34684.0,-34694.0,93111.0,2282.00,723.85,60.0,M-SC,13.13,231.0,-1.00,0.60,58.49,OX40N,BTT,AC

In [12]:
# top 5 to exit based on CumlRnk
df_tmp = df_portfolio_features[~df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])]
df_tmp = df_tmp[(df_tmp['Current P/L%'] > -1) & (df_tmp['Current P/L%'] < 1)].sort_values(by = 'CumlRnk', ascending=False)
df_tmp[cols].head()

Empty DataFrame
Columns: [Symbol, Today P/L%, Current P/L%, FTT%, OTT%, FTT Amt, Current P/L, Current, FTT, Dev%_PE, RSI_14, Conviction, Spread%, CumlRnk, RRR Ind, CurrAlloc%, Gained%, Criteria, Strategy, Category]
Index: []

In [13]:
# OX40N stocks to exit
df_tmp = df_portfolio_features[(df_portfolio_features['Symbol'].isin(list_ox40n))].sort_values(by = 'Current P/L%', ascending=False)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
25,FINCABLES,1.31,61.65,28.62,107.91,68307.0,91024.0,238668.0,1641.55,17.82,64.0,M-SC,26.08,220.0,1.33,1.55,79.56,OX40N,ATH,CABLES
67,SIS,0.99,-3.04,25.06,21.26,26980.0,-3371.0,107661.0,528.00,106.81,47.0,H-SC,19.72,168.0,-0.12,0.70,60.08,OX40N,NTT,MISC
43,INDIGOPNTS,2.53,-16.79,20.20,0.02,29341.0,-29305.0,145254.0,1408.00,-20.66,64.0,M-SC,8.87,222.0,-1.00,0.94,64.80,OX40N,NTT,PAINTS
77,TTKPRESTIG,3.74,-20.72,26.25,0.09,20973.0,-20880.0,79897.0,770.00,-3.55,50.0,M-SC,8.22,250.0,-1.00,0.52,43.80,OX40N,NTT,DURABLES
16,CERA,-0.37,-24.54,64.17,23.89,85182.0,-43159.0,132744.0,9475.00,NaN,38.0,NaN,12.80,153.0,-0.51,0.86,29.04,OX40N,NTT,CERAMICS

In [14]:
# top 5 to book for rotation
df_tmp = df_portfolio_features[(df_portfolio_features['Current P/L%'] > 20) ].sort_values(by = 'CumlRnk', ascending=False)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
25,FINCABLES,1.31,61.65,28.62,107.91,68307.0,91024.0,238668.0,1641.55,17.82,64.0,M-SC,26.08,220.0,1.33,1.55,79.56,OX40N,ATH,CABLES
27,GLAXO,3.66,22.00,11.23,35.69,27302.0,43836.0,243120.0,3380.16,-8.54,75.0,X-MC,12.98,56.0,1.61,1.58,44.49,X40,ATH,PHARMA

In [15]:
# top 5 to monitor for exit
df_tmp = df_portfolio_features[~df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])]
df_tmp = df_tmp[(df_tmp['Current P/L%'] > 0) ].sort_values(by = 'Dev%_PE', ascending=False)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
25,FINCABLES,1.31,61.65,28.62,107.91,68307.0,91024.0,238668.0,1641.55,17.82,64.0,M-SC,26.08,220.0,1.33,1.55,79.56,OX40N,ATH,CABLES
68,STARHEALTH,1.54,12.59,30.79,47.26,97458.0,35403.0,316526.0,761.00,-0.86,50.0,H-SC,15.33,173.0,0.36,2.05,36.86,XY24,NTT,INSURANCE

In [16]:
# top 5 to book for rotation from weak conviction
df_tmp = df_portfolio_features[~df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])]
df_tmp = df_tmp[~df_tmp['Criteria'].isin(['XY25','XY24','X40', 'X40N'])].sort_values(by = 'RRR Ind', ascending=False)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
25,FINCABLES,1.31,61.65,28.62,107.91,68307.0,91024.0,238668.0,1641.55,17.82,64.0,M-SC,26.08,220.0,1.33,1.55,79.56,OX40N,ATH,CABLES
3,ALKYLAMINE,0.53,-10.78,115.80,92.54,104314.0,-10882.0,90081.0,4520.85,NaN,69.0,NaN,17.04,142.0,-0.10,0.58,71.06,SR,ATH,CHEMICALS
67,SIS,0.99,-3.04,25.06,21.26,26980.0,-3371.0,107661.0,528.00,106.81,47.0,H-SC,19.72,168.0,-0.12,0.70,60.08,OX40N,NTT,MISC
42,INDIAMART,0.39,-24.49,166.08,100.92,154674.0,-30204.0,93132.0,4675.60,NaN,42.0,NaN,13.17,140.0,-0.20,0.60,1.32,AR,ATH,MISC
71,TANLA,-1.13,-36.93,244.47,117.25,417464.0,-99998.0,170763.0,1922.32,NaN,41.0,NaN,14.61,147.0,-0.24,1.11,49.51,AR,ATH,IT

In [17]:
# top 5 to accumulate based on lowest RSI_14
df_tmp = df_portfolio_features[df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])].sort_values(by = 'RSI_14', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
56,PGHH,-0.49,-39.39,117.81,32.01,152456.0,-84112.0,129408.0,17616.87,-55.45,23.0,X-SC,20.06,57.0,-0.55,0.84,0.00,X40,ATH,FMCG
19,COLPAL,-0.46,-29.07,97.17,39.86,181523.0,-76555.0,186810.0,3683.41,-14.08,29.0,X-MC,4.11,62.0,-0.42,1.21,5.67,XY25,ATH,FMCG
20,DABUR,-0.23,-22.94,86.48,43.70,165318.0,-56905.0,191163.0,735.00,-33.61,30.0,X-MC,11.20,70.0,-0.34,1.24,0.00,XY24,BTT,FMCG
55,PAGEIND,-0.18,-7.42,43.50,32.85,108082.0,-19914.0,248465.0,50936.07,-31.21,31.0,X-MC,8.38,55.0,-0.18,1.61,18.65,X40,ATH,APPARELS
75,TMPV,0.08,-25.17,90.78,42.75,282648.0,-104752.0,311355.0,600.00,-84.91,31.0,X-LC,4.41,4.0,-0.37,2.02,7.06,XY24,NTT,AUTO

In [18]:
# top 5 to accumulate based on Spread and CumlRnk
df_tmp = df_portfolio_features[df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])]
df_tmp = df_tmp[(df_tmp['CumlRnk'] < 100)].sort_values(by = 'Spread%', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
23,DMART,-0.09,-4.79,38.03,31.42,112894.0,-14934.0,296856.0,5391.45,-20.15,41.0,X-LC,2.04,14.0,-0.13,1.92,7.12,X40N,ATH,FMCG
50,KOTAKBANK,2.12,7.78,10.33,18.92,26689.0,18661.0,258363.0,452.46,-8.76,67.0,X-LC,2.11,12.0,0.70,1.67,16.24,X40,ATH,BANKS
1,ABBOTINDIA,0.44,-10.98,29.60,15.37,47126.0,-19645.0,159210.0,34390.26,-27.58,42.0,X-MC,2.26,58.0,-0.42,1.03,7.85,X40,ATH,PHARMA
53,MARUTI,-0.28,-0.69,25.51,24.64,62632.0,-1718.0,245520.0,17120.06,-6.59,46.0,X-LC,3.65,33.0,-0.03,1.59,11.95,XR,ATH,AUTO
7,BAJAJHFL,0.31,-24.69,115.28,62.13,237053.0,-67414.0,205632.0,181.50,-37.18,43.0,X-MC,3.98,60.0,-0.28,1.33,15.35,X40N,ATH,FINANCE

In [19]:
# top 5 to accumulate based on lowest Gained%
df_tmp = df_portfolio_features[df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])].sort_values(by = 'Gained%', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
20,DABUR,-0.23,-22.94,86.48,43.70,165318.0,-56905.0,191163.0,735.00,-33.61,30.0,X-MC,11.20,70.0,-0.34,1.24,0.00,XY24,BTT,FMCG
56,PGHH,-0.49,-39.39,117.81,32.01,152456.0,-84112.0,129408.0,17616.87,-55.45,23.0,X-SC,20.06,57.0,-0.55,0.84,0.00,X40,ATH,FMCG
34,HDFCBANK,-0.33,-11.44,47.98,31.05,124549.0,-33534.0,259586.0,1073.00,-28.50,37.0,X-LC,12.63,26.0,-0.27,1.68,0.76,X40,BTT,BANKS
36,HINDUNILVR,0.86,-15.06,43.12,21.56,123253.0,-50679.0,285838.0,2922.00,-41.43,43.0,X-LC,7.06,9.0,-0.41,1.85,1.33,XY25,NTT,FMCG
83,VOLTAS,-0.78,-3.52,50.49,45.20,93404.0,-6747.0,184995.0,1856.00,32.91,39.0,X-MC,5.83,79.0,-0.07,1.20,1.39,XY25,NTT,AC

In [20]:
# top 5 to accumulate based on lowest CurrAlloc%
df_tmp = df_portfolio_features[df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])].sort_values(by = 'CurrAlloc%', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
56,PGHH,-0.49,-39.39,117.81,32.01,152456.0,-84112.0,129408.0,17616.87,-55.45,23.0,X-SC,20.06,57.0,-0.55,0.84,0.00,X40,ATH,FMCG
2,ACC,1.31,-41.01,196.36,74.81,310563.0,-109968.0,158160.0,3906.00,-41.34,44.0,X-SC,11.27,85.0,-0.35,1.02,5.66,XY24,BTT,CEMENT
1,ABBOTINDIA,0.44,-10.98,29.60,15.37,47126.0,-19645.0,159210.0,34390.26,-27.58,42.0,X-MC,2.26,58.0,-0.42,1.03,7.85,X40,ATH,PHARMA
40,ICICIPRULI,1.27,-14.32,52.06,30.28,87870.0,-28219.0,168786.0,787.27,-45.05,58.0,X-MC,11.55,78.0,-0.32,1.09,12.46,X40,ATH,INSURANCE
39,ICICIGI,-0.02,-14.42,38.92,18.89,66652.0,-28855.0,171254.0,2244.41,-14.84,41.0,X-MC,10.19,66.0,-0.43,1.11,2.03,X40,ATH,INSURANCE

In [21]:
# top 5 to accumulate based on CumlRnk
df_tmp = df_portfolio_features.sort_values(by = 'CumlRnk', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
47,ITC,0.15,-25.02,66.30,24.70,197503.0,-99385.0,297893.0,452.00,-29.94,40.0,X-LC,10.90,1.0,-0.50,1.93,1.78,X40,NTT,FMCG
73,TCS,-0.26,-32.77,84.72,24.20,263887.0,-151792.0,311481.0,4230.71,-44.31,47.0,X-LC,13.10,2.0,-0.58,2.02,16.15,X40,ATH,IT
45,INFY,-1.40,-19.70,74.82,40.38,226184.0,-74166.0,302304.0,1972.00,-40.86,49.0,X-LC,15.34,3.0,-0.33,1.96,14.48,X40,NTT,IT
75,TMPV,0.08,-25.17,90.78,42.75,282648.0,-104752.0,311355.0,600.00,-84.91,31.0,X-LC,4.41,4.0,-0.37,2.02,7.06,XY24,NTT,AUTO
33,HCLTECH,-0.18,-12.15,41.12,23.97,111795.0,-37612.0,271874.0,1853.42,-14.26,52.0,X-LC,9.40,8.0,-0.34,1.76,28.29,X40,ATH,IT

In [22]:
# top 5 for average up
df_tmp = df_portfolio_features[(df_portfolio_features['Dev%_200'] > 5)].sort_values(by = 'CurrAlloc%', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
44,INDUSINDBK,-0.84,-25.45,78.25,32.89,45040.0,-19648.0,57559.0,1800.00,323.79,50.0,L-MC,11.96,258.0,-0.44,0.37,41.91,XR,NTT,BANKS
30,HAPPSTMNDS,0.41,-44.10,227.50,83.08,162999.0,-56517.0,71648.0,1466.54,NaN,69.0,NaN,7.29,152.0,-0.35,0.46,34.20,AR,ATH,IT
77,TTKPRESTIG,3.74,-20.72,26.25,0.09,20973.0,-20880.0,79897.0,770.00,-3.55,50.0,M-SC,8.22,250.0,-1.00,0.52,43.80,OX40N,NTT,DURABLES
3,ALKYLAMINE,0.53,-10.78,115.80,92.54,104314.0,-10882.0,90081.0,4520.85,NaN,69.0,NaN,17.04,142.0,-0.10,0.58,71.06,SR,ATH,CHEMICALS
12,BOSCH-HCIL,-1.14,-27.15,37.25,-0.01,34684.0,-34694.0,93111.0,2282.00,723.85,60.0,M-SC,13.13,231.0,-1.00,0.60,58.49,OX40N,BTT,AC

In [23]:
# top 5 RSP
df_tmp = df_portfolio_features.sort_values(by = 'RSP', ascending=False)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
25,FINCABLES,1.31,61.65,28.62,107.91,68307.0,91024.0,238668.0,1641.55,17.82,64.0,M-SC,26.08,220.0,1.33,1.55,79.56,OX40N,ATH,CABLES
12,BOSCH-HCIL,-1.14,-27.15,37.25,-0.01,34684.0,-34694.0,93111.0,2282.00,723.85,60.0,M-SC,13.13,231.0,-1.00,0.60,58.49,OX40N,BTT,AC
27,GLAXO,3.66,22.00,11.23,35.69,27302.0,43836.0,243120.0,3380.16,-8.54,75.0,X-MC,12.98,56.0,1.61,1.58,44.49,X40,ATH,PHARMA
30,HAPPSTMNDS,0.41,-44.10,227.50,83.08,162999.0,-56517.0,71648.0,1466.54,NaN,69.0,NaN,7.29,152.0,-0.35,0.46,34.20,AR,ATH,IT
3,ALKYLAMINE,0.53,-10.78,115.80,92.54,104314.0,-10882.0,90081.0,4520.85,NaN,69.0,NaN,17.04,142.0,-0.10,0.58,71.06,SR,ATH,CHEMICALS

In [24]:
# Top N allocation
df_tmp = df_portfolio_features.sort_values(by = 'CurrAlloc%', ascending=False)
top_n_values = [10, 25, 50]

sum_df = pd.DataFrame({
    'Top_N': top_n_values,
    'Sum_Alloc%': [df_tmp['CurrAlloc%'].head(n).sum() for n in top_n_values]
})

sum_df

   Top_N  Sum_Alloc%
0     10       19.68
1     25       45.06
2     50       77.68

In [25]:
# market-cap-wise allocation
df_tmp = df_portfolio_features[cols]
df_tmp.groupby(df_tmp['Conviction'].str[-2:])['CurrAlloc%'].sum().sort_values(ascending=False)

Conviction
LC    38.19
MC    22.17
SC    21.66
Name: CurrAlloc%, dtype: float64

In [26]:
# criteria-wise allocation
df_portfolio_features.groupby('Criteria')['CurrAlloc%'].sum().sort_values(ascending=False)

Criteria
X40      26.81
XY24     23.90
X40N     18.69
XR        9.05
OX40N     7.28
XY25      7.16
AR        6.16
SR        0.92
Name: CurrAlloc%, dtype: float64

In [27]:
# conviction-wise allocation
df_portfolio_features.groupby('Conviction')['CurrAlloc%'].sum().sort_values(ascending=False)

Conviction
X-LC    34.43
X-MC    19.60
H-SC     8.52
X-SC     7.72
M-SC     5.42
H-LC     2.95
M-MC     1.17
H-MC     1.03
M-LC     0.81
L-MC     0.37
Name: CurrAlloc%, dtype: float64

In [28]:
# sector-wise stats
df_tmp = df_portfolio_features.groupby('Category')[['CurrAlloc%', 'Current', 'Current P/L', 'FTT Amt']].sum().sort_values(by=['Current', 'Current P/L'], ascending=False)
df_tmp['Current P/L%'] = round(df_tmp['Current P/L'] * 100 / df_tmp['Current'], 2)
df_tmp['FTT%'] = round(df_tmp['FTT Amt'] * 100 / df_tmp['Current'], 2)
cols = ['CurrAlloc%', 'Current P/L%', 'FTT%']
df_tmp[cols].sort_values(by=['CurrAlloc%'], ascending=False)

               CurrAlloc%  Current P/L%    FTT%
Category
FMCG                15.40        -25.49   70.50
IT                  11.23        -37.54  105.75
FINANCE             10.69        -17.08   67.50
AUTO                 8.27         -5.96   43.91
BANKS                6.27        -10.13   57.62
PHARMA               5.93          9.32   16.39
MISC                 5.90        -35.38   89.84
INSURANCE            5.79         -3.92   40.66
PAINTS               5.43        -17.40   37.43
ELECTRICAL           4.24         -8.01   41.83
AC                   1.80        -14.90   46.06
REFINERIES           1.73        -11.44   48.87
BREWERIES            1.71         11.14    7.31
FOOTWEAR             1.65        -73.14  142.57
APPARELS             1.61         -8.01   43.50
CABLES               1.55         38.14   28.62
DURABLES             1.49        -68.62  109.65
TRAVEL               1.42       -104.51  206.92
CERAMICS             1.29        -53.95  100.72
CHEMICALS            1.23        -38.74  151.36
ENGINEERING          1.23        -27.24   85.43
CEMENT               1.02        -69.53  196.36
JEWELLERY            0.94       -119.09  195.21
ENTERTAINMENT        0.70        -77.03  182.60
HEALTHCARE           0.69        -69.52  112.08
TEXTILES             0.39        -52.89   96.48
HOTELS               0.37        -98.99  169.18

In [29]:
# money to be made criteria-wise
df_portfolio_features.groupby('Criteria')['FTT Amt'].agg(['sum', 'count']).sort_values(by='sum', ascending=False)

                sum  count
Criteria
XY24      3636773.0     19
X40       2082387.0     18
XR        1397230.0     13
X40N      1198504.0     12
AR        1053216.0      8
OX40N      668889.0     10
XY25       594269.0      5
SR         272536.0      2

In [30]:
# money to be made conviction-wise
df_portfolio_features.groupby('Conviction')['FTT Amt'].agg(['sum', 'count']).sort_values(by='sum', ascending=False)

                  sum  count
Conviction
X-LC        2412186.0     19
X-MC        1477140.0     14
X-SC        1086400.0      6
H-SC         834780.0      8
M-SC         328923.0      6
H-MC         254988.0      1
M-LC         166703.0      1
M-MC          65369.0      1
L-MC          45040.0      1
H-LC          34700.0      2

In [31]:
# money to be made criteria and conviction-wise
df_portfolio_features.groupby(['Conviction', 'Criteria'])['FTT Amt'].agg(['sum', 'count']).sort_values(by='sum', ascending=False)

                           sum  count
Conviction Criteria
X-LC       X40       1207684.0      9
X-SC       XY24       658653.0      2
H-SC       XY24       524617.0      3
X-MC       X40        502345.0      6
X-LC       XY24       467756.0      2
X-MC       X40N       454281.0      4
X-LC       X40N       420141.0      5
X-MC       XY25       274927.0      2
X-SC       X40        255629.0      2
H-MC       XY24       254988.0      1
X-LC       XY25       253973.0      2
X-MC       XY24       245587.0      2
H-SC       OX40N      220984.0      3
X-SC       X40N       172118.0      2
M-LC       XR         166703.0      1
M-SC       OX40N      153305.0      4
           XY24       117400.0      1
H-SC       XR          89179.0      2
M-MC       XY25        65369.0      1
X-LC       XR          62632.0      1
M-SC       XR          58218.0      1
L-MC       XR          45040.0      1
H-LC       AR          34700.0      2

In [32]:
# notebook execution time

end_time = time.time()
execution_time = round(end_time - start_time, 0)
print(f"Notebook execution time: {execution_time} seconds")

Notebook execution time: 38.0 seconds