<a href="https://colab.research.google.com/github/ankit-rathi/Quantvesting_v2/blob/main/myStocks_Portfolio_Analysis.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
'''
!pip install pandas==2.2.2 -qq
!pip install pyxirr -qq
!pip install ta -qq
!pip install yfinance==0.2.59 -qq
'''

'\n!pip install pandas==2.2.2 -qq\n!pip install pyxirr -qq\n!pip install ta -qq\n!pip install yfinance==0.2.59 -qq\n'

In [2]:
# import libraries

import numpy as np
import pandas as pd
import datetime
import warnings
warnings.filterwarnings('ignore')
import yfinance as yfin
import ta
import matplotlib.pyplot as plt
import requests

In [3]:
# notebook start time
import time
import datetime
import pytz

start_time = time.time()

# function to print date timestamp
def print_date_time():
  tz_NY = pytz.timezone('Asia/Kolkata')
  datetime_NY = datetime.datetime.now(tz_NY)
  print("Run date time (IST):", datetime_NY.strftime("%Y-%m-%d %H:%M:%S"))

In [4]:
# function to get booked and reserved amount
def get_amt():
  # fetch the JSON data from the URL
  url = "https://raw.githubusercontent.com/ankit-rathi/Tradevesting_v1/main/data/myPortfolioAmts.json"
  response = requests.get(url)
  pf_amts = response.json()  # parse the JSON data

  # extract values from the JSON
  py_booked_amt_dm = pf_amts["py_booked_amt_dm"]
  py_booked_amt_sv = pf_amts["py_booked_amt_sv"]
  cy_booked_amt_dm = pf_amts["cy_booked_amt_dm"]
  cy_booked_amt_sv = pf_amts["cy_booked_amt_sv"]
  reserve_amt_dm = pf_amts["reserve_amt_dm"]
  reserve_amt_sv = pf_amts["reserve_amt_sv"]

  # perform calculations
  py_booked_amt = py_booked_amt_dm + py_booked_amt_sv
  cy_booked_amt = cy_booked_amt_dm + cy_booked_amt_sv
  reserve_amt = reserve_amt_dm + reserve_amt_sv
  total_booked_amt = py_booked_amt + cy_booked_amt

  return total_booked_amt, reserve_amt, cy_booked_amt, py_booked_amt

gen_output = 0

In [5]:
# function to format the amount
def format_amt(number):
    abs_number = abs(number)

    if abs_number >= 1_00_00_000:  # Crores
        formatted_amt = f"{number / 1_00_00_000:.2f} C"
    elif abs_number >= 1_00_000:  # Lakhs
        formatted_amt = f"{number / 1_00_000:.2f} L"
    elif abs_number >= 1_000:  # Thousands
        formatted_amt = f"{number / 1_000:.2f} K"
    else:
        formatted_amt = f"{number:.2f}"

    return formatted_amt

# function to set start and end date
def get_start_end_date():
  start_date = (datetime.date.today() + datetime.timedelta(days=-365)).strftime('%Y-%m-%d')
  end_date = (datetime.date.today() + datetime.timedelta(days=1)).strftime('%Y-%m-%d')
  return start_date, end_date

# function to fetch my portfolio csv
def get_mypfs_df():
  mypfs_df = pd.read_csv('https://raw.githubusercontent.com/ankit-rathi/Tradevesting_v1/main/data/myPortfolioStocks.csv')
  return mypfs_df

# function to fetch my prospects csv
def get_mypps_df():
  mypps_df = pd.read_csv('https://raw.githubusercontent.com/ankit-rathi/Tradevesting_v1/main/data/myProspectsScrips.csv')
  return mypps_df

# function to fetch screener data
def get_myscreen_df():
  myscreen_df = pd.read_csv('https://raw.githubusercontent.com/ankit-rathi/Tradevesting_v1/main/data/myScreenerDB.csv')
  return myscreen_df

# function to fetch momentum data
def get_myinvmt_df():
  myinvmt_df = pd.read_csv('https://raw.githubusercontent.com/ankit-rathi/Tradevesting_v1/main/data/myInvestments.csv')
  return myinvmt_df

# function to get the stock ids
def get_stock_ids(df_pf):
  stock_n100 = df_pf['Symbol'].unique()

  exclude = ['CADILAHC','MMTC', 'MASFIN']

  stock_ids = df_pf[~df_pf['Symbol'].isin(exclude) ]['Symbol'].unique()

  #mypf = mypf[mypf.Forecast.notnull()]
  #stock_ids = mypf['Symbol'].unique()

  #stock_ids.sort()
  return stock_ids

# get features from screener data
def get_screener_features():
  myscreen_df = get_myscreen_df()
  cols = ['Symbol', 'EPS', 'MedPE', 'ROCE%', 'ROE%', 'CapType']
  return myscreen_df[cols]

# get relative strength
def get_relative_strength(stock_list):

    # Dictionary to store stock tickers and their corresponding percentage price change
    stock_changes = {}

    # Loop through each stock and fetch its price data
    for stock in stock_list:
        try:
            # Download the stock data for the given date range
            stock_data = yfin.Ticker(stock + '.NS').history(period='1mo', interval='1d')[map(str.title, ['open', 'close', 'low', 'high', 'volume'])]

            # Calculate the percentage change for the stock
            if len(stock_data) > 0:
                start_price = stock_data['Close'].iloc[0]
                end_price = stock_data['Close'].iloc[-1]
                percent_change = round(((end_price - start_price) / start_price) * 100, 2)
                stock_changes[stock] = percent_change
            else:
                stock_changes[stock] = np.nan  # If no data is available, set to NaN

        except Exception as e:
            print(f"Error fetching data for {stock}: {e}")
            stock_changes[stock] = np.nan

    # Create a DataFrame with stock tickers and their percentage changes
    df = pd.DataFrame(list(stock_changes.items()), columns=['Symbol', 'Percent_Change'])

    # Drop any stocks with missing data (NaN values)
    df = df.dropna()

    # Calculate the percentile rank based on percentage change
    df['RSP'] = round(df['Percent_Change'].rank(pct=True) * 100, 2)
    cols = ['Symbol', 'RSP']
    df = df[cols]
    # Sort by percentile rank (optional)
    df = df.sort_values(by='RSP', ascending=False).reset_index(drop=True)

    return df

In [6]:
# function to get stock technicals
def stock_prec_dev(stock_symbol):
    #stock_symbol = 'ULTRACEMCO.NS'
    short_window = 20
    mid_window = 50
    long_window = 200
    moving_avg = 'SMA'

    start = datetime.datetime(*map(int, start_date.split('-')))
    end = datetime.datetime(*map(int, end_date.split('-')))

    stock_df = yfin.Ticker(stock_symbol + '.NS').history(period='max', interval='1d')[map(str.title, ['open', 'close', 'low', 'high', 'volume'])]

    stock_df['Max'] = round(max(stock_df['Close']),2)
    stock_df = stock_df[(stock_df.index <= end_date) & (stock_df.index >= start_date)]
    stock_df['200_SMA'] = round(stock_df['Close'].rolling(window = 200, min_periods = 1).mean(),0)
    stock_df['Dev%_200'] = round((stock_df['Close'] - stock_df['200_SMA'])*100/stock_df['200_SMA'],2)
    stock_df.dropna(axis = 0, inplace = True) # remove any null rows

    stock_df['20_SMA'] = stock_df['Close'].rolling(window=20).mean()
    stock_df['50_SMA'] = stock_df['Close'].rolling(window=50).mean()
    stock_df['Symbol'] = stock_symbol

    stock_df['Close'] = round(stock_df['Close'],2)
    stock_df['Min'] = round(min(stock_df['Close']),2)
    stock_df['RSI_14'] = ta.momentum.RSIIndicator(close=stock_df['Close'], window=14).rsi()
    stock_df['RSI_14'] = round(stock_df['RSI_14'],0)
    stock_df['Prev_Close'] = stock_df['Close'].shift(1)
    stock_df.drop(['Open', 'Low', 'High', 'Volume'], axis=1, inplace=True)
    stock_df = stock_df.tail(1)

    max_SMA = max(stock_df['20_SMA'].item(), stock_df['50_SMA'].item(), stock_df['200_SMA'].item())
    min_SMA = min(stock_df['20_SMA'].item(), stock_df['50_SMA'].item(), stock_df['200_SMA'].item())
    ABS_Spread = max_SMA - min_SMA
    stock_df['Spread%'] = round((ABS_Spread / stock_df['200_SMA'].item()) * 100,2)

    return stock_df

# function to compute stock attributes
def get_common_features(stock_ids, df_mypf):

  df_prec_dev = pd.DataFrame()
  df_tmp = get_screener_features()
  df_rs = get_relative_strength(stock_ids)

  for stock_id in stock_ids:
      tmp = stock_prec_dev(stock_id)
      tmp = tmp.reset_index()
      df_prec_dev = pd.concat([df_prec_dev, tmp], ignore_index = True)
  df_prec_dev = pd.merge(df_prec_dev, df_mypf, on= 'Symbol')
  df_prec_dev = pd.merge(df_prec_dev, df_tmp, on= 'Symbol', how='left')
  df_prec_dev = pd.merge(df_prec_dev, df_rs, on= 'Symbol', how='left')
  #print(df_prec_dev.columns)
  df_prec_dev['Curr_PE'] = round(df_prec_dev['Close']/df_prec_dev['EPS'],1)
  df_prec_dev['Dev%_PE'] = round((df_prec_dev['Curr_PE'] - df_prec_dev['MedPE'])*100/df_prec_dev['MedPE'],2)
  df_prec_dev['Conviction'] = df_prec_dev['Conviction'] + '-' + df_prec_dev['CapType']
  return df_prec_dev

# function to arrange stock features
def arrange_features(df_stocks, common_cols, diff_cols):
  df_stocks_common = df_stocks[common_cols].drop_duplicates()
  df_stocks_diff = df_stocks[diff_cols]
  df_stocks_diff['Investment'] = df_stocks_diff['AvgCost'] * df_stocks_diff['Shares']
  df_stocks_diff = df_stocks_diff.groupby(['Symbol'])[['Shares', 'Investment']].aggregate(['sum']).reset_index()
  df_stocks_diff.columns = ['Symbol', 'Shares', 'Investment']
  df_stocks_diff['AvgCost'] = round(df_stocks_diff['Investment']/df_stocks_diff['Shares'],2)
  df_stocks = pd.merge(df_stocks_diff, df_stocks_common, on='Symbol')
  return df_stocks

# plot fact distribution across dimension
def plot_pie_chart(df, dimension, fact):
  # grouping the data by category and calculating the sum of fact for each type
  grouped_data = df.groupby(dimension)[fact].sum()

  # sorting the grouped data in descending order
  grouped_data = grouped_data.sort_values(ascending=False)

  # creating a pie chart
  grouped_data.plot.pie(autopct='%1.1f%%', startangle=90, figsize=(6, 6))

  # adding a title and displaying the plot
  plt.title(f'{dimension} {fact} Distribution')
  plt.ylabel('')  # To hide the y-label
  plt.show()

In [7]:
# function to get portfolio features

def get_portfolio_features(df_common_features):

  print_date_time()
  print('-------------------')

  #df_common_features["Target"] = df_common_features["Target"].fillna(df_common_features["Max"])
  df_common_features['NTT'] = np.where(df_common_features['Strategy']== 'NTT', df_common_features["Target"], df_common_features['Max'])
  df_common_features['LTT'] = np.where(df_common_features['Strategy']== 'BTT', df_common_features["Target"], df_common_features['Max'])
  df_common_features['BOL'] = df_common_features['Min']

  tmp_df = df_common_features[df_common_features['Symbol'].isin(mypf_df[mypf_df['InPortfolio'] != 'NA'].Symbol.values)]
  print('qualified stocks: '+str(len(tmp_df['Symbol'].unique())))
  tmp_df1 = tmp_df[tmp_df['LatestQtr'] == 1]
  print('with latest results: '+str(len(tmp_df1['Symbol'].unique())))
  tmp_df1 = tmp_df1[tmp_df1['StarStock'] == 1]
  print('still star stocks: '+str(len(tmp_df1['Symbol'].unique())))
  tmp_df['Investment'] = tmp_df['AvgCost'] * tmp_df['Shares']
  tmp_df['Current'] = round(tmp_df['Close'] * tmp_df['Shares'],0)
  tmp_df['Previous'] = tmp_df['Prev_Close'] * tmp_df['Shares']
  tmp_df['EstimatedST'] = tmp_df['NTT'] * tmp_df['Shares']
  tmp_df['EstimatedLT'] = tmp_df['LTT'] * tmp_df['Shares']
  tmp_df['Current P/L'] = round((tmp_df['Current'] - tmp_df['Investment']),0)
  tmp_df['Today P/L%'] = round((tmp_df['Current'] - tmp_df['Previous'])*100/tmp_df['Previous'],2)
  tmp_df['Current P/L%'] = round((tmp_df['Current'] - tmp_df['Investment'])*100/tmp_df['Investment'],2)
  tmp_df['EstimatedST P/L%'] = round((tmp_df['EstimatedST'] - tmp_df['Investment'])*100/tmp_df['Investment'],2)
  tmp_df['EstimatedLT P/L%'] = round((tmp_df['EstimatedLT'] - tmp_df['Investment'])*100/tmp_df['Investment'],2)
  tmp_df['NTT%'] = round((tmp_df['NTT'] - tmp_df['Close'])*100/tmp_df['Close'],2)
  tmp_df['LTT%'] = round((tmp_df['LTT'] - tmp_df['Close'])*100/tmp_df['Close'],2)
  tmp_df['Gained%'] = round((tmp_df['Close'] - tmp_df['BOL'])*100/tmp_df['BOL'],2)
  investment = round(sum(tmp_df['AvgCost']*tmp_df['Shares']),0)
  current = round(sum(tmp_df['Close']*tmp_df['Shares']),0)
  tmp_df['InitAlloc%'] = round(tmp_df['Investment']*100/investment,2)
  tmp_df['CurrAlloc%'] = round(tmp_df['Current']*100/current,2)
  tmp_df['FTT'] = tmp_df['LTT']
  tmp_df.loc[tmp_df['Strategy'] == 'NTT', 'FTT'] = tmp_df['NTT']
  tmp_df['FTT%'] = tmp_df['LTT%']
  tmp_df.loc[tmp_df['Strategy'] == 'NTT', 'FTT%'] = tmp_df['NTT%']
  tmp_df['FTT Amt'] = round(tmp_df['FTT%'] * tmp_df['Current']/100,0)
  tmp_df['OTT%'] = round((tmp_df['FTT'] - tmp_df['AvgCost'])*100/tmp_df['AvgCost'],2)
  tmp_df['RRR Ind'] = round(tmp_df['Current P/L']/tmp_df['FTT Amt'],2)
  tmp_df['Risk Ind'] = round(tmp_df['Current P/L%']*tmp_df['CurrAlloc%'],0)

  return tmp_df

# function to print portfolio features
def print_portfolio_stats(df_portfolio_features, myinvmt_df):
  from pyxirr import xirr

  total_booked_amt, reserve_amt, cy_booked_amt, py_booked_amt = get_amt()

  dates = myinvmt_df['Date'].values
  dates = np.append(dates, datetime.date.today().strftime('%d-%b-%y'))
  investment = myinvmt_df['Investment'].values
  dates= pd.to_datetime(dates)

  current = round(sum(df_portfolio_features['Close']*df_portfolio_features['Shares']),0) + reserve_amt
  investment_xirr = np.append(investment, current)
  cagr = round(xirr(pd.DataFrame({"dates": dates, "amounts": investment_xirr}))*100,2)

  investment = -sum(investment)
  invested = round(sum(df_portfolio_features['AvgCost']*df_portfolio_features['Shares']),0) + reserve_amt
  previous = round(sum(df_portfolio_features['Prev_Close']*df_portfolio_features['Shares']),0) + reserve_amt
  cy_invested = investment + py_booked_amt

  today_pnl_amount = current-previous
  today_pnl_percentage = round((current-previous)*100/previous,2)

  curr_pnl_amount = current-invested
  curr_pnl_percentage = round((curr_pnl_amount)*100/(cy_invested),2)

  cy_pnl_amount = cy_booked_amt + curr_pnl_amount
  cy_pnl_percentage = round((cy_pnl_amount)*100/cy_invested,2)

  overall_pnl_amount = total_booked_amt + curr_pnl_amount
  overall_pnl_percentage = round((overall_pnl_amount)*100/investment,2)

  estimate_st = round(sum(df_portfolio_features['FTT']*df_portfolio_features['Shares']),0)  + reserve_amt
  est_st_pnl_amount = estimate_st-current
  est_st_pnl_percentage = round((est_st_pnl_amount)*100/current,2)

  estimate_lt = round(sum(df_portfolio_features['LTT']*df_portfolio_features['Shares']),0)  + reserve_amt
  est_lt_pnl_amount = estimate_lt-current
  est_lt_pnl_percentage = round((est_lt_pnl_amount)*100/current,2)

  total_profit = round(sum(df_portfolio_features[df_portfolio_features['Current P/L%'] > 0]['Current']) - sum(df_portfolio_features[df_portfolio_features['Current P/L%'] > 0]['Investment']),0)
  total_loss = round(sum(df_portfolio_features[df_portfolio_features['Current P/L%'] < 0]['Current']) - sum(df_portfolio_features[df_portfolio_features['Current P/L%'] < 0]['Investment']),0)

  cy_booked_percentage = round((cy_booked_amt)*100/current,2)
  py_booked_percentage = round((py_booked_amt)*100/investment,2)
  total_booked_percentage = round((total_booked_amt)*100/investment,2)

  print('-------------------')
  print('Initial Investment: ', format_amt(investment))
  print('CY Investment: ', format_amt(cy_invested))
  print('Reserve: ', format_amt(reserve_amt))
  print('Current: ',  format_amt(current))
  print('-------------------')
  print('Today PnL: '+ '{} ({}%)'.format(format_amt(today_pnl_amount), today_pnl_percentage))
  print('Current PnL: '+ '{} ({}%)'.format(format_amt(curr_pnl_amount), curr_pnl_percentage))
  print('CY Booked + Current PnL: '+ '{} ({}%)'.format(format_amt(cy_pnl_amount), cy_pnl_percentage))
  print('-------------------')
  print('Total profit: ', format_amt(total_profit))
  print('Total loss: ', format_amt(total_loss))
  print('-------------------')
  print('Total Booked + Current PnL: '+ '{} ({}%)'.format(format_amt(overall_pnl_amount), overall_pnl_percentage))
  print('Total Booked PnL: '+ '{} ({}%)'.format(format_amt(total_booked_amt), total_booked_percentage))
  print('Curr Year Booked PnL: '+ '{} ({}%)'.format(format_amt(cy_booked_amt), cy_booked_percentage))
  print('Prev Year Booked PnL: '+ '{} ({}%)'.format(format_amt(py_booked_amt), py_booked_percentage))
  print('===================')
  print('Est FTT: ',  format_amt(estimate_st))
  print('Est FTT PnL: '+ '{} ({}%)'.format(format_amt(est_st_pnl_amount), est_st_pnl_percentage))

  print('===================')
  print('Deployed: ', format_amt(investment))

  print('Current: ', format_amt(current))

  print('CAGR/XIRR %: '+'{}%'.format(cagr))

In [8]:
# get start and end date
start_date, end_date = get_start_end_date()

# get portfolio and prospects data
mypfs_df = get_mypfs_df()
mypps_df = get_mypps_df()
myinvmt_df = get_myinvmt_df()

# merge above datasets
mypf_df = pd.merge(mypfs_df, mypps_df, on="Symbol")

# seggregate dm and sv portfolio
dm_pf = mypf_df[mypf_df['InPortfolio'] == 'DM']
sv_pf = mypf_df[mypf_df['InPortfolio'] == 'SV']

# build portfolio stock dataframe
dm_stocks = get_stock_ids(dm_pf)
sv_stocks = get_stock_ids(sv_pf)
df_stocks = pd.concat([dm_pf,sv_pf], ignore_index = True)

# arrange common and diff stock features
common_cols = ['Symbol', 'Target', 'Criteria', 'Strategy', 'CumlRnk', 'LatestQtr', 'StarStock', 'Conviction', 'Category', 'InFolio', 'XIRR', 'MBQ']
diff_cols = ['Symbol', 'AvgCost', 'Shares']
df_stocks = arrange_features(df_stocks, common_cols, diff_cols)

# get common features
stock_ids = df_stocks['Symbol'].values
df_common_features = get_common_features(stock_ids, df_stocks)

df_common_features.reset_index(drop=True, inplace=True)
df_common_features.drop(['Date'], axis=1, inplace=True)
# get and print portfolio features
df_portfolio_features = get_portfolio_features(df_common_features)

print_portfolio_stats(df_portfolio_features, myinvmt_df)

df = df_portfolio_features
#plot_pie_chart(df, 'CapType', 'Current')
list_ox40n = list(df[df['MBQ'].str.contains('OX40N', na=False)]['Symbol'].values)

Run date time (IST): 2026-04-13 16:32:48
-------------------
qualified stocks: 86
with latest results: 26
still star stocks: 16
-------------------
Initial Investment:  1.36 C
CY Investment:  1.62 C
Reserve:  1.61 K
Current:  1.38 C
-------------------
Today PnL: -72.44 K (-0.52%)
Current PnL: -39.57 L (-24.35%)
CY Booked + Current PnL: -23.68 L (-14.57%)
-------------------
Total profit:  1.52 L
Total loss:  -41.09 L
-------------------
Total Booked + Current PnL: 3.30 L (2.43%)
Total Booked PnL: 42.87 L (31.64%)
Curr Year Booked PnL: 15.89 L (11.55%)
Prev Year Booked PnL: 26.98 L (19.91%)
===================
Est FTT:  2.48 C
Est FTT PnL: 1.10 C (80.21%)
===================
Deployed:  1.36 C
Current:  1.38 C
CAGR/XIRR %: 0.72%

In [9]:
# top 5 near their targets
cols = ['Symbol', 'Today P/L%', 'Current P/L%', 'FTT%', 'OTT%', 'FTT Amt', 'Current P/L', 'Current', 'FTT', 'Dev%_PE', 'RSI_14','Conviction', 'Spread%',  'CumlRnk', 'RRR Ind', 'CurrAlloc%', 'Gained%', 'Criteria', 'Strategy', 'Category']
df_tmp = df_portfolio_features[~df_portfolio_features['Symbol'].isin(['ENRIN','BLUSPRING','DIGITIDE'])]
df_tmp = df_tmp.sort_values(by = 'FTT Amt', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
50,MASFIN,-0.62,-6.14,29.52,21.57,27148.0,-6015.0,91965.0,397.04,-19.15,51.0,H-SC,4.70,167.0,-0.22,0.67,18.84,XR,ATH,FINANCE
5,ANGELONE,-0.19,14.94,8.04,24.18,28186.0,45575.0,350575.0,303.00,-83.35,71.0,X-SC,3.89,97.0,1.62,2.55,34.12,X40N,NTT,FINANCE
77,TTKPRESTIG,-1.14,-38.66,63.19,0.09,39059.0,-38965.0,61812.0,770.00,43.44,47.0,M-SC,22.31,250.0,-1.00,0.45,10.07,OX40N,NTT,DURABLES
67,SONACOMS,2.71,-1.51,41.23,39.09,41076.0,-1532.0,99627.0,804.02,-21.96,66.0,M-MC,8.46,193.0,-0.04,0.72,40.94,AR,ATH,AUTO
37,ICICIGI,-0.21,-5.59,26.41,19.34,49892.0,-11196.0,188913.0,2252.93,-20.57,48.0,X-MC,7.65,66.0,-0.22,1.37,5.51,X40,ATH,INSURANCE

In [10]:
# top 5 today
df_tmp = df_portfolio_features.sort_values(by = 'Today P/L%', ascending=False)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
7,ATULAUTO,11.36,-16.34,74.00,45.57,122039.0,-32215.0,164917.0,844.00,3570.27,65.0,M-SC,8.69,248.0,-0.26,1.20,26.91,XY24,NTT,AUTO
55,RAJESHEXPO,4.99,-77.74,349.50,0.07,106734.0,-106638.0,30539.0,518.00,1018.69,56.0,L-SC,44.10,268.0,-1.00,0.22,43.37,OX40N,NTT,JEWELLERY
82,VOLTAS,3.50,6.52,36.31,45.20,74160.0,12498.0,204240.0,1856.00,21.95,52.0,X-MC,6.46,79.0,0.17,1.48,13.76,XY25,NTT,AC
67,SONACOMS,2.71,-1.51,41.23,39.09,41076.0,-1532.0,99627.0,804.02,-21.96,66.0,M-MC,8.46,193.0,-0.04,0.72,40.94,AR,ATH,AUTO
12,BATAINDIA,2.52,-52.69,185.77,35.20,113089.0,-67794.0,60876.0,2096.00,-20.14,57.0,X-SC,33.92,91.0,-0.60,0.44,20.73,X40,NTT,FOOTWEAR

In [11]:
# bottom 5 today
df_tmp = df_portfolio_features.sort_values(by = 'Today P/L%', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
25,EASEMYTRIP,-4.24,-57.67,244.20,45.70,182769.0,-101971.0,74844.0,26.40,-22.20,57.0,M-SC,13.51,204.0,-0.56,0.54,31.11,XY24,NTT,TRAVEL
78,UNITDSPR,-2.89,-9.54,33.50,20.77,70959.0,-22326.0,211818.0,1644.00,-19.72,40.0,X-MC,5.84,64.0,-0.31,1.54,1.04,X40N,NTT,BREWERIES
71,TANLA,-2.88,-47.82,320.99,119.69,453546.0,-129465.0,141296.0,1943.92,-47.43,57.0,H-SC,25.52,147.0,-0.29,1.03,22.33,AR,ATH,IT
59,RELIANCE,-2.60,-15.58,48.43,25.30,82161.0,-31315.0,169648.0,1952.00,-17.72,40.0,X-LC,5.10,21.0,-0.38,1.23,6.54,XY25,BTT,REFINERIES
79,VAIBHAVGBL,-2.54,-34.61,145.87,60.77,174332.0,-63263.0,119512.0,521.00,37.74,53.0,H-SC,12.30,160.0,-0.36,0.87,20.84,XR,NTT,JEWELLERY

In [12]:
# top 5 to exit based on CumlRnk
df_tmp = df_portfolio_features[~df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])]
df_tmp = df_tmp[(df_tmp['Current P/L%'] > -1) & (df_tmp['Current P/L%'] < 1)].sort_values(by = 'CumlRnk', ascending=False)
df_tmp[cols].head()

Empty DataFrame
Columns: [Symbol, Today P/L%, Current P/L%, FTT%, OTT%, FTT Amt, Current P/L, Current, FTT, Dev%_PE, RSI_14, Conviction, Spread%, CumlRnk, RRR Ind, CurrAlloc%, Gained%, Criteria, Strategy, Category]
Index: []

In [13]:
# OX40N stocks to exit
df_tmp = df_portfolio_features[(df_portfolio_features['Symbol'].isin(list_ox40n))].sort_values(by = 'Current P/L%', ascending=False)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
26,FINCABLES,-0.12,7.25,93.86,107.91,148620.0,10698.0,158342.0,1641.55,-3.60,52.0,M-SC,1.58,220.0,0.07,1.15,19.13,OX40N,ATH,CABLES
66,SIS,0.63,-30.03,73.31,21.26,56952.0,-33346.0,77686.0,528.00,1824.87,60.0,H-SC,13.86,168.0,-0.59,0.56,15.51,OX40N,NTT,MISC
18,CERA,1.08,-31.77,81.59,23.89,97918.0,-55891.0,120012.0,9475.00,-34.13,66.0,H-SC,16.76,153.0,-0.57,0.87,15.33,OX40N,NTT,CERAMICS
72,TATAELXSI,-0.76,-36.42,107.67,32.03,90246.0,-48018.0,83817.0,9161.00,-20.53,52.0,H-SC,20.63,158.0,-0.53,0.61,10.93,OX40N,NTT,IT
48,KANSAINER,-1.50,-37.04,80.23,13.47,136219.0,-99882.0,169785.0,340.00,-45.81,55.0,H-SC,22.93,162.0,-0.73,1.23,18.60,XY24,NTT,PAINTS

In [14]:
# top 5 to book for rotation
df_tmp = df_portfolio_features[(df_portfolio_features['Current P/L%'] > 20) ].sort_values(by = 'CumlRnk', ascending=False)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
1,ABB,-0.45,25.28,16.19,45.57,53066.0,66149.0,327768.0,7934.0,-19.52,69.0,H-MC,15.74,125.0,1.25,2.38,45.55,AR,NTT,ELECTRICAL

In [15]:
# top 5 to monitor for exit
df_tmp = df_portfolio_features[~df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])]
df_tmp = df_tmp[(df_tmp['Current P/L%'] > 0) ].sort_values(by = 'Dev%_PE', ascending=False)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
26,FINCABLES,-0.12,7.25,93.86,107.91,148620.0,10698.0,158342.0,1641.55,-3.60,52.0,M-SC,1.58,220.0,0.07,1.15,19.13,OX40N,ATH,CABLES
1,ABB,-0.45,25.28,16.19,45.57,53066.0,66149.0,327768.0,7934.00,-19.52,69.0,H-MC,15.74,125.0,1.25,2.38,45.55,AR,NTT,ELECTRICAL

In [16]:
# top 5 to book for rotation from weak conviction
df_tmp = df_portfolio_features[~df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])]
df_tmp = df_tmp[~df_tmp['Criteria'].isin(['XY25','XY24','X40', 'X40N'])].sort_values(by = 'RRR Ind', ascending=False)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
1,ABB,-0.45,25.28,16.19,45.57,53066.0,66149.0,327768.0,7934.00,-19.52,69.0,H-MC,15.74,125.0,1.25,2.38,45.55,AR,NTT,ELECTRICAL
26,FINCABLES,-0.12,7.25,93.86,107.91,148620.0,10698.0,158342.0,1641.55,-3.60,52.0,M-SC,1.58,220.0,0.07,1.15,19.13,OX40N,ATH,CABLES
67,SONACOMS,2.71,-1.51,41.23,39.09,41076.0,-1532.0,99627.0,804.02,-21.96,66.0,M-MC,8.46,193.0,-0.04,0.72,40.94,AR,ATH,AUTO
85,ZYDUSLIFE,0.76,-2.73,39.44,35.63,80398.0,-5724.0,203850.0,1286.17,-15.32,59.0,H-MC,6.01,120.0,-0.07,1.48,13.49,AR,ATH,PHARMA
40,INDIAMART,0.32,-9.47,128.34,106.72,143304.0,-11676.0,111660.0,4810.62,-59.18,54.0,H-SC,13.02,140.0,-0.08,0.81,7.28,AR,ATH,MISC

In [17]:
# top 5 to accumulate based on lowest RSI_14
df_tmp = df_portfolio_features[df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])].sort_values(by = 'RSI_14', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
21,DABUR,-2.51,-16.96,73.04,43.70,150465.0,-42064.0,206004.0,735.00,-24.64,39.0,X-MC,14.03,70.0,-0.28,1.50,3.48,XY24,BTT,FMCG
59,RELIANCE,-2.60,-15.58,48.43,25.30,82161.0,-31315.0,169648.0,1952.00,-17.72,40.0,X-LC,5.10,21.0,-0.38,1.23,6.54,XY25,BTT,REFINERIES
78,UNITDSPR,-2.89,-9.54,33.50,20.77,70959.0,-22326.0,211818.0,1644.00,-19.72,40.0,X-MC,5.84,64.0,-0.31,1.54,1.04,X40N,NTT,BREWERIES
53,PGHH,0.07,-26.61,79.86,32.01,125150.0,-56808.0,156712.0,17616.87,-50.35,41.0,X-MC,21.19,57.0,-0.45,1.14,7.18,X40,ATH,FMCG
2,ABBOTINDIA,-0.21,-13.70,36.81,18.07,56816.0,-24505.0,154350.0,35195.00,-26.49,42.0,X-MC,11.51,58.0,-0.43,1.12,0.94,X40,ATH,PHARMA

In [18]:
# top 5 to accumulate based on Spread and CumlRnk
df_tmp = df_portfolio_features[df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])]
df_tmp = df_tmp[(df_tmp['CumlRnk'] < 100)].sort_values(by = 'Spread%', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
65,SIEMENS,-1.33,-10.17,39.72,25.51,66402.0,-18920.0,167175.0,4671.50,40.45,60.0,H-LC,1.44,51.0,-0.28,1.22,18.99,AR,ATH,ELECTRICAL
5,ANGELONE,-0.19,14.94,8.04,24.18,28186.0,45575.0,350575.0,303.00,-83.35,71.0,X-SC,3.89,97.0,1.62,2.55,34.12,X40N,NTT,FINANCE
24,DMART,1.08,6.92,21.21,29.60,56605.0,17280.0,266880.0,5391.45,-9.88,68.0,X-LC,4.34,14.0,0.31,1.94,21.99,X40N,ATH,FMCG
59,RELIANCE,-2.60,-15.58,48.43,25.30,82161.0,-31315.0,169648.0,1952.00,-17.72,40.0,X-LC,5.10,21.0,-0.38,1.23,6.54,XY25,BTT,REFINERIES
78,UNITDSPR,-2.89,-9.54,33.50,20.77,70959.0,-22326.0,211818.0,1644.00,-19.72,40.0,X-MC,5.84,64.0,-0.31,1.54,1.04,X40N,NTT,BREWERIES

In [19]:
# top 5 to accumulate based on lowest Gained%
df_tmp = df_portfolio_features[df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])].sort_values(by = 'Gained%', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
2,ABBOTINDIA,-0.21,-13.70,36.81,18.07,56816.0,-24505.0,154350.0,35195.0,-26.49,42.0,X-MC,11.51,58.0,-0.43,1.12,0.94,X40,ATH,PHARMA
78,UNITDSPR,-2.89,-9.54,33.50,20.77,70959.0,-22326.0,211818.0,1644.0,-19.72,40.0,X-MC,5.84,64.0,-0.31,1.54,1.04,X40N,NTT,BREWERIES
21,DABUR,-2.51,-16.96,73.04,43.70,150465.0,-42064.0,206004.0,735.0,-24.64,39.0,X-MC,14.03,70.0,-0.28,1.50,3.48,XY24,BTT,FMCG
35,HINDUNILVR,-1.30,-17.25,37.36,13.67,79472.0,-44343.0,212720.0,2922.0,-38.66,46.0,X-LC,11.94,9.0,-0.56,1.55,3.65,XY25,NTT,FMCG
45,ITC,-1.84,-21.34,51.35,19.06,137407.0,-72576.0,267590.0,452.0,-56.73,45.0,X-LC,19.59,1.0,-0.53,1.95,3.81,X40,NTT,FMCG

In [20]:
# top 5 to accumulate based on lowest CurrAlloc%
df_tmp = df_portfolio_features[df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])].sort_values(by = 'CurrAlloc%', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
58,RELAXO,1.63,-61.81,298.83,52.31,165653.0,-89726.0,55434.0,1176.00,-59.35,52.0,X-SC,33.23,92.0,-0.54,0.40,23.94,X40N,NTT,FOOTWEAR
12,BATAINDIA,2.52,-52.69,185.77,35.20,113089.0,-67794.0,60876.0,2096.00,-20.14,57.0,X-SC,33.92,91.0,-0.60,0.44,20.73,X40,NTT,FOOTWEAR
54,QUESS,-1.33,-21.81,122.41,73.90,102212.0,-23293.0,83500.0,424.00,-58.13,56.0,X-SC,21.64,80.0,-0.23,0.61,12.33,XY24,NTT,MISC
36,HONAUT,2.50,-24.03,99.17,51.31,145284.0,-46338.0,146500.0,58357.33,-36.81,54.0,X-SC,19.22,90.0,-0.32,1.07,11.30,X40N,ATH,ELECTRICAL
2,ABBOTINDIA,-0.21,-13.70,36.81,18.07,56816.0,-24505.0,154350.0,35195.00,-26.49,42.0,X-MC,11.51,58.0,-0.43,1.12,0.94,X40,ATH,PHARMA

In [21]:
# top 5 to accumulate based on CumlRnk
df_tmp = df_portfolio_features.sort_values(by = 'CumlRnk', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
45,ITC,-1.84,-21.34,51.35,19.06,137407.0,-72576.0,267590.0,452.00,-56.73,45.0,X-LC,19.59,1.0,-0.53,1.95,3.81,X40,NTT,FMCG
73,TCS,-2.05,-27.41,74.37,26.57,250087.0,-126999.0,336274.0,4311.59,-38.71,45.0,X-LC,18.01,2.0,-0.51,2.45,4.95,X40,ATH,IT
43,INFY,-1.21,-13.08,54.45,34.24,148081.0,-40930.0,271958.0,1972.00,-31.42,43.0,X-LC,14.22,3.0,-0.28,1.98,4.59,X40,NTT,IT
75,TMPV,0.85,-21.35,73.66,36.58,206141.0,-75986.0,279855.0,600.00,-83.62,59.0,X-LC,12.29,4.0,-0.37,2.03,16.64,XY24,NTT,AUTO
33,HCLTECH,-1.50,-7.24,33.50,23.83,75179.0,-17508.0,224416.0,1908.19,-2.40,54.0,X-LC,9.39,8.0,-0.23,1.63,8.96,X40,ATH,IT

In [22]:
# top 5 for average up
df_tmp = df_portfolio_features[(df_portfolio_features['Dev%_200'] > 5)].sort_values(by = 'CurrAlloc%', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
67,SONACOMS,2.71,-1.51,41.23,39.09,41076.0,-1532.0,99627.0,804.02,-21.96,66.0,M-MC,8.46,193.0,-0.04,0.72,40.94,AR,ATH,AUTO
7,ATULAUTO,11.36,-16.34,74.00,45.57,122039.0,-32215.0,164917.0,844.00,3570.27,65.0,M-SC,8.69,248.0,-0.26,1.20,26.91,XY24,NTT,AUTO
65,SIEMENS,-1.33,-10.17,39.72,25.51,66402.0,-18920.0,167175.0,4671.50,40.45,60.0,H-LC,1.44,51.0,-0.28,1.22,18.99,AR,ATH,ELECTRICAL
62,SATIN,1.27,-10.48,69.61,51.83,172169.0,-28951.0,247333.0,274.00,-19.84,68.0,H-SC,2.79,159.0,-0.17,1.80,20.49,XY24,NTT,FINANCE
24,DMART,1.08,6.92,21.21,29.60,56605.0,17280.0,266880.0,5391.45,-9.88,68.0,X-LC,4.34,14.0,0.31,1.94,21.99,X40N,ATH,FMCG

In [23]:
# top 5 RSP
df_tmp = df_portfolio_features.sort_values(by = 'RSP', ascending=False)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
5,ANGELONE,-0.19,14.94,8.04,24.18,28186.0,45575.0,350575.0,303.00,-83.35,71.0,X-SC,3.89,97.0,1.62,2.55,34.12,X40N,NTT,FINANCE
80,VALIANTORG,0.59,-45.14,217.46,74.15,195170.0,-73855.0,89750.0,838.00,-261.57,59.0,H-SC,21.80,145.0,-0.38,0.65,33.56,XR,NTT,CHEMICALS
7,ATULAUTO,11.36,-16.34,74.00,45.57,122039.0,-32215.0,164917.0,844.00,3570.27,65.0,M-SC,8.69,248.0,-0.26,1.20,26.91,XY24,NTT,AUTO
52,PAGEIND,-0.57,-6.49,43.43,34.11,108988.0,-17429.0,250950.0,51418.65,-32.92,69.0,X-MC,16.59,55.0,-0.16,1.82,18.71,X40,ATH,APPARELS
67,SONACOMS,2.71,-1.51,41.23,39.09,41076.0,-1532.0,99627.0,804.02,-21.96,66.0,M-MC,8.46,193.0,-0.04,0.72,40.94,AR,ATH,AUTO

In [24]:
# Top N allocation
df_tmp = df_portfolio_features.sort_values(by = 'CurrAlloc%', ascending=False)
top_n_values = [10, 25, 50]

sum_df = pd.DataFrame({
    'Top_N': top_n_values,
    'Sum_Alloc%': [df_tmp['CurrAlloc%'].head(n).sum() for n in top_n_values]
})

sum_df

   Top_N  Sum_Alloc%
0     10       21.09
1     25       45.89
2     50       77.80

In [25]:
# market-cap-wise allocation
df_tmp = df_portfolio_features[cols]
df_tmp.groupby(df_tmp['Conviction'].str[-2:])['CurrAlloc%'].sum().sort_values(ascending=False)

Conviction
SC    45.08
MC    29.58
LC    25.30
Name: CurrAlloc%, dtype: float64

In [26]:
# criteria-wise allocation
df_portfolio_features.groupby('Criteria')['CurrAlloc%'].sum().sort_values(ascending=False)

Criteria
XY24     27.29
X40      24.81
X40N     15.59
AR        9.36
XR        8.35
XY25      7.04
OX40N     6.74
SR        0.78
Name: CurrAlloc%, dtype: float64

In [27]:
# conviction-wise allocation
df_portfolio_features.groupby('Conviction')['CurrAlloc%'].sum().sort_values(ascending=False)

Conviction
X-LC    23.05
X-MC    22.00
H-SC    21.94
X-SC    12.44
M-SC    10.12
H-MC     5.13
M-MC     2.11
H-LC     1.22
M-LC     1.03
L-SC     0.58
L-MC     0.34
Name: CurrAlloc%, dtype: float64

In [28]:
# sector-wise stats
df_tmp = df_portfolio_features.groupby('Category')[['CurrAlloc%', 'Current', 'Current P/L', 'FTT Amt']].sum().sort_values(by=['Current', 'Current P/L'], ascending=False)
df_tmp['Current P/L%'] = round(df_tmp['Current P/L'] * 100 / df_tmp['Current'], 2)
df_tmp['FTT%'] = round(df_tmp['FTT Amt'] * 100 / df_tmp['Current'], 2)
cols = ['CurrAlloc%', 'Current P/L%', 'FTT%']
df_tmp[cols].sort_values(by=['CurrAlloc%'], ascending=False)

               CurrAlloc%  Current P/L%    FTT%
Category
FMCG                14.75        -23.22   66.94
FINANCE             13.46        -16.16   63.49
IT                  11.64        -40.81  112.46
MISC                 7.12        -36.96   96.46
ELECTRICAL           6.62         -6.55   47.35
PAINTS               5.29        -35.23   58.71
BANKS                4.57        -22.16   84.17
INSURANCE            4.53         -8.82   46.06
PHARMA               4.00         -6.60   40.15
AUTO                 3.95        -20.16   67.83
AC                   2.01        -15.12   46.33
HEALTHCARE           1.94        -34.04   69.02
APPARELS             1.82         -6.95   43.43
FOOTWEAR             1.82        -75.55  145.94
TRAVEL               1.81        -78.79  168.31
DURABLES             1.71        -64.73  104.80
BREWERIES            1.54        -10.54   33.50
REALTY               1.44        -12.30   30.75
CERAMICS             1.36        -63.31  112.93
REFINERIES           1.23        -18.46   48.43
CEMENT               1.23        -58.41  176.92
ENGINEERING          1.16        -52.44  122.16
CABLES               1.15          6.76   93.86
JEWELLERY            1.09       -113.23  187.31
CHEMICALS            1.08        -77.35  222.05
ENTERTAINMENT        0.83        -69.19  170.10
TEXTILES             0.45        -48.39   90.70
HOTELS               0.36       -127.81  208.17

In [29]:
# money to be made criteria-wise
df_portfolio_features.groupby('Criteria')['FTT Amt'].agg(['sum', 'count']).sort_values(by='sum', ascending=False)

                sum  count
Criteria
XY24      3842042.0     21
X40       1762150.0     16
XR        1342095.0     12
AR        1283118.0     10
X40N      1156806.0     10
OX40N      863735.0     10
XY25       471334.0      5
SR         311162.0      2

In [30]:
# money to be made conviction-wise
df_portfolio_features.groupby('Conviction')['FTT Amt'].agg(['sum', 'count']).sort_values(by='sum', ascending=False)

                  sum  count
Conviction
H-SC        3771336.0     24
X-MC        1707055.0     15
X-LC        1605479.0     13
M-SC        1525340.0     14
X-SC        1472241.0     10
H-MC         371807.0      3
L-SC         210492.0      2
M-LC         150840.0      1
M-MC          95526.0      2
H-LC          66402.0      1
L-MC          55924.0      1

In [31]:
# money to be made criteria and conviction-wise
df_portfolio_features.groupby(['Conviction', 'Criteria'])['FTT Amt'].agg(['sum', 'count']).sort_values(by='sum', ascending=False)

                           sum  count
Conviction Criteria
H-SC       XY24      1282804.0      6
           AR         968737.0      5
X-LC       X40        880043.0      7
M-SC       XY24       871960.0      6
H-SC       XR         841980.0      7
X-SC       XY24       840348.0      4
X-MC       X40        670078.0      7
           X40N       527097.0      4
X-SC       X40N       419864.0      4
M-SC       OX40N      390348.0      5
H-SC       OX40N      366653.0      4
X-LC       XY24       353958.0      2
H-SC       SR         311162.0      2
X-MC       XY25       255251.0      2
           XY24       254629.0      2
H-MC       XY24       238343.0      1
X-SC       X40        212029.0      2
X-LC       X40N       209845.0      2
M-SC       XR         189593.0      2
X-LC       XY25       161633.0      2
M-LC       XR         150840.0      1
H-MC       AR         133464.0      2
L-SC       OX40N      106734.0      1
           XR         103758.0      1
M-SC       AR          73439.0      1
H-LC       AR          66402.0      1
L-MC       XR          55924.0      1
M-MC       XY25        54450.0      1
           AR          41076.0      1

In [32]:
# notebook execution time

end_time = time.time()
execution_time = round(end_time - start_time, 0)
print(f"Notebook execution time: {execution_time} seconds")

Notebook execution time: 24.0 seconds