<a href="https://colab.research.google.com/github/ankit-rathi/Quantvesting_v2/blob/main/myStocks_Portfolio_Analysis.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
'''
!pip install pandas==2.2.2 -qq
!pip install pyxirr -qq
!pip install ta -qq
!pip install yfinance==0.2.59 -qq
'''

'\n!pip install pandas==2.2.2 -qq\n!pip install pyxirr -qq\n!pip install ta -qq\n!pip install yfinance==0.2.59 -qq\n'

In [2]:
# import libraries

import numpy as np
import pandas as pd
import datetime
import warnings
warnings.filterwarnings('ignore')
import yfinance as yfin
import ta
import matplotlib.pyplot as plt
import requests

In [3]:
# notebook start time
import time
import datetime
import pytz

start_time = time.time()

# function to print date timestamp
def print_date_time():
  tz_NY = pytz.timezone('Asia/Kolkata')
  datetime_NY = datetime.datetime.now(tz_NY)
  print("Run date time (IST):", datetime_NY.strftime("%Y-%m-%d %H:%M:%S"))

In [4]:
# function to get booked and reserved amount
def get_amt():
  # fetch the JSON data from the URL
  url = "https://raw.githubusercontent.com/ankit-rathi/Tradevesting_v1/main/data/myPortfolioAmts.json"
  response = requests.get(url)
  pf_amts = response.json()  # parse the JSON data

  # extract values from the JSON
  py_booked_amt_dm = pf_amts["py_booked_amt_dm"]
  py_booked_amt_sv = pf_amts["py_booked_amt_sv"]
  cy_booked_amt_dm = pf_amts["cy_booked_amt_dm"]
  cy_booked_amt_sv = pf_amts["cy_booked_amt_sv"]
  reserve_amt_dm = pf_amts["reserve_amt_dm"]
  reserve_amt_sv = pf_amts["reserve_amt_sv"]

  # perform calculations
  py_booked_amt = py_booked_amt_dm + py_booked_amt_sv
  cy_booked_amt = cy_booked_amt_dm + cy_booked_amt_sv
  reserve_amt = reserve_amt_dm + reserve_amt_sv
  total_booked_amt = py_booked_amt + cy_booked_amt

  return total_booked_amt, reserve_amt, cy_booked_amt, py_booked_amt

gen_output = 0

In [5]:
# function to format the amount
def format_amt(number):
    abs_number = abs(number)

    if abs_number >= 1_00_00_000:  # Crores
        formatted_amt = f"{number / 1_00_00_000:.2f} C"
    elif abs_number >= 1_00_000:  # Lakhs
        formatted_amt = f"{number / 1_00_000:.2f} L"
    elif abs_number >= 1_000:  # Thousands
        formatted_amt = f"{number / 1_000:.2f} K"
    else:
        formatted_amt = f"{number:.2f}"

    return formatted_amt

# function to set start and end date
def get_start_end_date():
  start_date = (datetime.date.today() + datetime.timedelta(days=-365)).strftime('%Y-%m-%d')
  end_date = (datetime.date.today() + datetime.timedelta(days=1)).strftime('%Y-%m-%d')
  return start_date, end_date

# function to fetch my portfolio csv
def get_mypfs_df():
  mypfs_df = pd.read_csv('https://raw.githubusercontent.com/ankit-rathi/Tradevesting_v1/main/data/myPortfolioStocks.csv')
  return mypfs_df

# function to fetch my prospects csv
def get_mypps_df():
  mypps_df = pd.read_csv('https://raw.githubusercontent.com/ankit-rathi/Tradevesting_v1/main/data/myProspectsScrips.csv')
  return mypps_df

# function to fetch screener data
def get_myscreen_df():
  myscreen_df = pd.read_csv('https://raw.githubusercontent.com/ankit-rathi/Tradevesting_v1/main/data/myScreenerDB.csv')
  return myscreen_df

# function to fetch momentum data
def get_myinvmt_df():
  myinvmt_df = pd.read_csv('https://raw.githubusercontent.com/ankit-rathi/Tradevesting_v1/main/data/myInvestments.csv')
  return myinvmt_df

# function to get the stock ids
def get_stock_ids(df_pf):
  stock_n100 = df_pf['Symbol'].unique()

  exclude = ['CADILAHC','MMTC', 'MASFIN']

  stock_ids = df_pf[~df_pf['Symbol'].isin(exclude) ]['Symbol'].unique()

  #mypf = mypf[mypf.Forecast.notnull()]
  #stock_ids = mypf['Symbol'].unique()

  #stock_ids.sort()
  return stock_ids

# get features from screener data
def get_screener_features():
  myscreen_df = get_myscreen_df()
  cols = ['Symbol', 'EPS', 'MedPE', 'ROCE%', 'ROE%', 'CapType']
  return myscreen_df[cols]

# get relative strength
def get_relative_strength(stock_list):

    # Dictionary to store stock tickers and their corresponding percentage price change
    stock_changes = {}

    # Loop through each stock and fetch its price data
    for stock in stock_list:
        try:
            # Download the stock data for the given date range
            stock_data = yfin.Ticker(stock + '.NS').history(period='1mo', interval='1d')[map(str.title, ['open', 'close', 'low', 'high', 'volume'])]

            # Calculate the percentage change for the stock
            if len(stock_data) > 0:
                start_price = stock_data['Close'].iloc[0]
                end_price = stock_data['Close'].iloc[-1]
                percent_change = round(((end_price - start_price) / start_price) * 100, 2)
                stock_changes[stock] = percent_change
            else:
                stock_changes[stock] = np.nan  # If no data is available, set to NaN

        except Exception as e:
            print(f"Error fetching data for {stock}: {e}")
            stock_changes[stock] = np.nan

    # Create a DataFrame with stock tickers and their percentage changes
    df = pd.DataFrame(list(stock_changes.items()), columns=['Symbol', 'Percent_Change'])

    # Drop any stocks with missing data (NaN values)
    df = df.dropna()

    # Calculate the percentile rank based on percentage change
    df['RSP'] = round(df['Percent_Change'].rank(pct=True) * 100, 2)
    cols = ['Symbol', 'RSP']
    df = df[cols]
    # Sort by percentile rank (optional)
    df = df.sort_values(by='RSP', ascending=False).reset_index(drop=True)

    return df

In [6]:
# function to get stock technicals
def stock_prec_dev(stock_symbol):
    #stock_symbol = 'ULTRACEMCO.NS'
    short_window = 20
    mid_window = 50
    long_window = 200
    moving_avg = 'SMA'

    start = datetime.datetime(*map(int, start_date.split('-')))
    end = datetime.datetime(*map(int, end_date.split('-')))

    stock_df = yfin.Ticker(stock_symbol + '.NS').history(period='max', interval='1d')[map(str.title, ['open', 'close', 'low', 'high', 'volume'])]

    stock_df['Max'] = round(max(stock_df['Close']),2)
    stock_df = stock_df[(stock_df.index <= end_date) & (stock_df.index >= start_date)]
    stock_df['200_SMA'] = round(stock_df['Close'].rolling(window = 200, min_periods = 1).mean(),0)
    stock_df['Dev%_200'] = round((stock_df['Close'] - stock_df['200_SMA'])*100/stock_df['200_SMA'],2)
    stock_df.dropna(axis = 0, inplace = True) # remove any null rows

    stock_df['20_SMA'] = stock_df['Close'].rolling(window=20).mean()
    stock_df['50_SMA'] = stock_df['Close'].rolling(window=50).mean()
    stock_df['Symbol'] = stock_symbol

    stock_df['Close'] = round(stock_df['Close'],2)
    stock_df['Min'] = round(min(stock_df['Close']),2)
    stock_df['RSI_14'] = ta.momentum.RSIIndicator(close=stock_df['Close'], window=14).rsi()
    stock_df['RSI_14'] = round(stock_df['RSI_14'],0)
    stock_df['Prev_Close'] = stock_df['Close'].shift(1)
    stock_df.drop(['Open', 'Low', 'High', 'Volume'], axis=1, inplace=True)
    stock_df = stock_df.tail(1)

    max_SMA = max(stock_df['20_SMA'].item(), stock_df['50_SMA'].item(), stock_df['200_SMA'].item())
    min_SMA = min(stock_df['20_SMA'].item(), stock_df['50_SMA'].item(), stock_df['200_SMA'].item())
    ABS_Spread = max_SMA - min_SMA
    stock_df['Spread%'] = round((ABS_Spread / stock_df['200_SMA'].item()) * 100,2)

    return stock_df

# function to compute stock attributes
def get_common_features(stock_ids, df_mypf):

  df_prec_dev = pd.DataFrame()
  df_tmp = get_screener_features()
  df_rs = get_relative_strength(stock_ids)

  for stock_id in stock_ids:
      tmp = stock_prec_dev(stock_id)
      tmp = tmp.reset_index()
      df_prec_dev = pd.concat([df_prec_dev, tmp], ignore_index = True)
  df_prec_dev = pd.merge(df_prec_dev, df_mypf, on= 'Symbol')
  df_prec_dev = pd.merge(df_prec_dev, df_tmp, on= 'Symbol', how='left')
  df_prec_dev = pd.merge(df_prec_dev, df_rs, on= 'Symbol', how='left')
  #print(df_prec_dev.columns)
  df_prec_dev['Curr_PE'] = round(df_prec_dev['Close']/df_prec_dev['EPS'],1)
  df_prec_dev['Dev%_PE'] = round((df_prec_dev['Curr_PE'] - df_prec_dev['MedPE'])*100/df_prec_dev['MedPE'],2)
  df_prec_dev['Conviction'] = df_prec_dev['Conviction'] + '-' + df_prec_dev['CapType']
  return df_prec_dev

# function to arrange stock features
def arrange_features(df_stocks, common_cols, diff_cols):
  df_stocks_common = df_stocks[common_cols].drop_duplicates()
  df_stocks_diff = df_stocks[diff_cols]
  df_stocks_diff['Investment'] = df_stocks_diff['AvgCost'] * df_stocks_diff['Shares']
  df_stocks_diff = df_stocks_diff.groupby(['Symbol'])[['Shares', 'Investment']].aggregate(['sum']).reset_index()
  df_stocks_diff.columns = ['Symbol', 'Shares', 'Investment']
  df_stocks_diff['AvgCost'] = round(df_stocks_diff['Investment']/df_stocks_diff['Shares'],2)
  df_stocks = pd.merge(df_stocks_diff, df_stocks_common, on='Symbol')
  return df_stocks

# plot fact distribution across dimension
def plot_pie_chart(df, dimension, fact):
  # grouping the data by category and calculating the sum of fact for each type
  grouped_data = df.groupby(dimension)[fact].sum()

  # sorting the grouped data in descending order
  grouped_data = grouped_data.sort_values(ascending=False)

  # creating a pie chart
  grouped_data.plot.pie(autopct='%1.1f%%', startangle=90, figsize=(6, 6))

  # adding a title and displaying the plot
  plt.title(f'{dimension} {fact} Distribution')
  plt.ylabel('')  # To hide the y-label
  plt.show()

In [7]:
# function to get portfolio features

def get_portfolio_features(df_common_features):

  print_date_time()
  print('-------------------')

  #df_common_features["Target"] = df_common_features["Target"].fillna(df_common_features["Max"])
  df_common_features['NTT'] = np.where(df_common_features['Strategy']== 'NTT', df_common_features["Target"], df_common_features['Max'])
  df_common_features['LTT'] = np.where(df_common_features['Strategy']== 'BTT', df_common_features["Target"], df_common_features['Max'])
  df_common_features['BOL'] = df_common_features['Min']

  tmp_df = df_common_features[df_common_features['Symbol'].isin(mypf_df[mypf_df['InPortfolio'] != 'NA'].Symbol.values)]
  print('qualified stocks: '+str(len(tmp_df['Symbol'].unique())))
  tmp_df1 = tmp_df[tmp_df['LatestQtr'] == 1]
  print('with latest results: '+str(len(tmp_df1['Symbol'].unique())))
  tmp_df1 = tmp_df1[tmp_df1['StarStock'] == 1]
  print('still star stocks: '+str(len(tmp_df1['Symbol'].unique())))
  tmp_df['Investment'] = tmp_df['AvgCost'] * tmp_df['Shares']
  tmp_df['Current'] = round(tmp_df['Close'] * tmp_df['Shares'],0)
  tmp_df['Previous'] = tmp_df['Prev_Close'] * tmp_df['Shares']
  tmp_df['EstimatedST'] = tmp_df['NTT'] * tmp_df['Shares']
  tmp_df['EstimatedLT'] = tmp_df['LTT'] * tmp_df['Shares']
  tmp_df['Current P/L'] = round((tmp_df['Current'] - tmp_df['Investment']),0)
  tmp_df['Today P/L%'] = round((tmp_df['Current'] - tmp_df['Previous'])*100/tmp_df['Previous'],2)
  tmp_df['Current P/L%'] = round((tmp_df['Current'] - tmp_df['Investment'])*100/tmp_df['Investment'],2)
  tmp_df['EstimatedST P/L%'] = round((tmp_df['EstimatedST'] - tmp_df['Investment'])*100/tmp_df['Investment'],2)
  tmp_df['EstimatedLT P/L%'] = round((tmp_df['EstimatedLT'] - tmp_df['Investment'])*100/tmp_df['Investment'],2)
  tmp_df['NTT%'] = round((tmp_df['NTT'] - tmp_df['Close'])*100/tmp_df['Close'],2)
  tmp_df['LTT%'] = round((tmp_df['LTT'] - tmp_df['Close'])*100/tmp_df['Close'],2)
  tmp_df['Gained%'] = round((tmp_df['Close'] - tmp_df['BOL'])*100/tmp_df['BOL'],2)
  investment = round(sum(tmp_df['AvgCost']*tmp_df['Shares']),0)
  current = round(sum(tmp_df['Close']*tmp_df['Shares']),0)
  tmp_df['InitAlloc%'] = round(tmp_df['Investment']*100/investment,2)
  tmp_df['CurrAlloc%'] = round(tmp_df['Current']*100/current,2)
  tmp_df['FTT'] = tmp_df['LTT']
  tmp_df.loc[tmp_df['Strategy'] == 'NTT', 'FTT'] = tmp_df['NTT']
  tmp_df['FTT%'] = tmp_df['LTT%']
  tmp_df.loc[tmp_df['Strategy'] == 'NTT', 'FTT%'] = tmp_df['NTT%']
  tmp_df['FTT Amt'] = round(tmp_df['FTT%'] * tmp_df['Current']/100,0)
  tmp_df['OTT%'] = round((tmp_df['FTT'] - tmp_df['AvgCost'])*100/tmp_df['AvgCost'],2)
  tmp_df['RRR Ind'] = round(tmp_df['Current P/L']/tmp_df['FTT Amt'],2)
  tmp_df['Risk Ind'] = round(tmp_df['Current P/L%']*tmp_df['CurrAlloc%'],0)

  return tmp_df

# function to print portfolio features
def print_portfolio_stats(df_portfolio_features, myinvmt_df):
  from pyxirr import xirr

  total_booked_amt, reserve_amt, cy_booked_amt, py_booked_amt = get_amt()

  dates = myinvmt_df['Date'].values
  dates = np.append(dates, datetime.date.today().strftime('%d-%b-%y'))
  investment = myinvmt_df['Investment'].values
  dates= pd.to_datetime(dates)

  current = round(sum(df_portfolio_features['Close']*df_portfolio_features['Shares']),0) + reserve_amt
  investment_xirr = np.append(investment, current)
  cagr = round(xirr(pd.DataFrame({"dates": dates, "amounts": investment_xirr}))*100,2)

  investment = -sum(investment)
  invested = round(sum(df_portfolio_features['AvgCost']*df_portfolio_features['Shares']),0) + reserve_amt
  previous = round(sum(df_portfolio_features['Prev_Close']*df_portfolio_features['Shares']),0) + reserve_amt
  cy_invested = investment + py_booked_amt

  today_pnl_amount = current-previous
  today_pnl_percentage = round((current-previous)*100/previous,2)

  curr_pnl_amount = current-invested
  curr_pnl_percentage = round((curr_pnl_amount)*100/(cy_invested),2)

  cy_pnl_amount = cy_booked_amt + curr_pnl_amount
  cy_pnl_percentage = round((cy_pnl_amount)*100/cy_invested,2)

  overall_pnl_amount = total_booked_amt + curr_pnl_amount
  overall_pnl_percentage = round((overall_pnl_amount)*100/investment,2)

  estimate_st = round(sum(df_portfolio_features['FTT']*df_portfolio_features['Shares']),0)  + reserve_amt
  est_st_pnl_amount = estimate_st-current
  est_st_pnl_percentage = round((est_st_pnl_amount)*100/current,2)

  estimate_lt = round(sum(df_portfolio_features['LTT']*df_portfolio_features['Shares']),0)  + reserve_amt
  est_lt_pnl_amount = estimate_lt-current
  est_lt_pnl_percentage = round((est_lt_pnl_amount)*100/current,2)

  total_profit = round(sum(df_portfolio_features[df_portfolio_features['Current P/L%'] > 0]['Current']) - sum(df_portfolio_features[df_portfolio_features['Current P/L%'] > 0]['Investment']),0)
  total_loss = round(sum(df_portfolio_features[df_portfolio_features['Current P/L%'] < 0]['Current']) - sum(df_portfolio_features[df_portfolio_features['Current P/L%'] < 0]['Investment']),0)

  cy_booked_percentage = round((cy_booked_amt)*100/current,2)
  py_booked_percentage = round((py_booked_amt)*100/investment,2)
  total_booked_percentage = round((total_booked_amt)*100/investment,2)

  print('-------------------')
  print('Initial Investment: ', format_amt(investment))
  print('CY Investment: ', format_amt(cy_invested))
  print('Reserve: ', format_amt(reserve_amt))
  print('Current: ',  format_amt(current))
  print('-------------------')
  print('Today PnL: '+ '{} ({}%)'.format(format_amt(today_pnl_amount), today_pnl_percentage))
  print('Current PnL: '+ '{} ({}%)'.format(format_amt(curr_pnl_amount), curr_pnl_percentage))
  print('CY Booked + Current PnL: '+ '{} ({}%)'.format(format_amt(cy_pnl_amount), cy_pnl_percentage))
  print('-------------------')
  print('Total profit: ', format_amt(total_profit))
  print('Total loss: ', format_amt(total_loss))
  print('-------------------')
  print('Total Booked + Current PnL: '+ '{} ({}%)'.format(format_amt(overall_pnl_amount), overall_pnl_percentage))
  print('Total Booked PnL: '+ '{} ({}%)'.format(format_amt(total_booked_amt), total_booked_percentage))
  print('Curr Year Booked PnL: '+ '{} ({}%)'.format(format_amt(cy_booked_amt), cy_booked_percentage))
  print('Prev Year Booked PnL: '+ '{} ({}%)'.format(format_amt(py_booked_amt), py_booked_percentage))
  print('===================')
  print('Est FTT: ',  format_amt(estimate_st))
  print('Est FTT PnL: '+ '{} ({}%)'.format(format_amt(est_st_pnl_amount), est_st_pnl_percentage))

  print('===================')
  print('Deployed: ', format_amt(investment))

  print('Current: ', format_amt(current))

  print('CAGR/XIRR %: '+'{}%'.format(cagr))

In [8]:
# get start and end date
start_date, end_date = get_start_end_date()

# get portfolio and prospects data
mypfs_df = get_mypfs_df()
mypps_df = get_mypps_df()
myinvmt_df = get_myinvmt_df()

# merge above datasets
mypf_df = pd.merge(mypfs_df, mypps_df, on="Symbol")

# seggregate dm and sv portfolio
dm_pf = mypf_df[mypf_df['InPortfolio'] == 'DM']
sv_pf = mypf_df[mypf_df['InPortfolio'] == 'SV']

# build portfolio stock dataframe
dm_stocks = get_stock_ids(dm_pf)
sv_stocks = get_stock_ids(sv_pf)
df_stocks = pd.concat([dm_pf,sv_pf], ignore_index = True)

# arrange common and diff stock features
common_cols = ['Symbol', 'Target', 'Criteria', 'Strategy', 'CumlRnk', 'LatestQtr', 'StarStock', 'Conviction', 'Category', 'InFolio', 'XIRR', 'MBQ']
diff_cols = ['Symbol', 'AvgCost', 'Shares']
df_stocks = arrange_features(df_stocks, common_cols, diff_cols)

# get common features
stock_ids = df_stocks['Symbol'].values
df_common_features = get_common_features(stock_ids, df_stocks)

df_common_features.reset_index(drop=True, inplace=True)
df_common_features.drop(['Date'], axis=1, inplace=True)
# get and print portfolio features
df_portfolio_features = get_portfolio_features(df_common_features)

print_portfolio_stats(df_portfolio_features, myinvmt_df)

df = df_portfolio_features
#plot_pie_chart(df, 'CapType', 'Current')
list_ox40n = list(df[df['MBQ'].str.contains('OX40N', na=False)]['Symbol'].values)

Run date time (IST): 2026-05-15 14:18:22
-------------------
qualified stocks: 92
with latest results: 31
still star stocks: 20
-------------------
Initial Investment:  1.40 C
CY Investment:  1.82 C
Reserve:  1.49 K
Current:  1.49 C
-------------------
Today PnL: 59.74 K (0.4%)
Current PnL: -34.41 L (-18.87%)
CY Booked + Current PnL: -32.33 L (-17.73%)
-------------------
Total profit:  2.11 L
Total loss:  -36.52 L
-------------------
Total Booked + Current PnL: 10.54 L (7.55%)
Total Booked PnL: 44.95 L (32.22%)
Curr Year Booked PnL: 2.08 L (1.4%)
Prev Year Booked PnL: 42.87 L (30.73%)
===================
Est FTT:  2.55 C
Est FTT PnL: 1.07 C (71.7%)
===================
Deployed:  1.40 C
Current:  1.49 C
CAGR/XIRR %: 3.14%

In [9]:
# top 5 near their targets
cols = ['Symbol', 'Today P/L%', 'Current P/L%', 'FTT%', 'OTT%', 'FTT Amt', 'Current P/L', 'Current', 'FTT', 'Dev%_PE', 'RSI_14','Conviction', 'Spread%',  'CumlRnk', 'RRR Ind', 'CurrAlloc%', 'Gained%', 'Criteria', 'Strategy', 'Category']
df_tmp = df_portfolio_features[~df_portfolio_features['Symbol'].isin(['ENRIN','BLUSPRING','DIGITIDE'])]
df_tmp = df_tmp.sort_values(by = 'FTT Amt', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
59,PIDILITIND,-0.89,4.22,13.58,18.37,19971.0,5950.0,147060.0,1670.26,-26.97,62.0,X-LC,5.60,5.0,0.30,0.99,15.47,X40,ATH,CHEMICALS
55,MASFIN,-0.71,-1.18,23.02,21.57,22289.0,-1155.0,96825.0,397.04,-14.63,46.0,H-SC,5.78,167.0,-0.05,0.65,20.19,XR,ATH,FINANCE
51,KOTAKBANK,1.30,3.73,16.75,21.11,24059.0,5162.0,143634.0,453.24,-11.14,59.0,X-LC,7.39,12.0,0.21,0.97,9.85,X40,ATH,BANKS
17,CIPLA,-0.12,16.18,15.93,34.69,28346.0,24779.0,177940.0,1663.60,-10.08,71.0,X-LC,10.89,18.0,0.87,1.20,20.35,X40N,ATH,PHARMA
53,M&M,-1.26,1.69,21.34,23.38,30094.0,2340.0,141021.0,3802.40,-13.74,47.0,X-LC,8.37,25.0,0.08,0.95,6.92,X40N,ATH,AUTO

In [10]:
# top 5 today
df_tmp = df_portfolio_features.sort_values(by = 'Today P/L%', ascending=False)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
69,SFL,9.40,-41.51,116.50,26.63,178674.0,-108850.0,153368.0,1287.0,16.08,64.0,M-SC,13.11,242.0,-0.61,1.03,27.82,XY24,NTT,MISC
81,TMPV,5.80,-18.42,67.41,36.58,195694.0,-65537.0,290304.0,600.0,-82.53,58.0,X-LC,5.97,4.0,-0.33,1.95,21.00,XY24,NTT,AUTO
5,ATULAUTO,5.70,-10.81,63.22,45.57,111150.0,-21318.0,175814.0,844.0,3813.51,65.0,M-SC,7.70,248.0,-0.19,1.18,35.30,XY24,NTT,AUTO
86,VALIANTORG,5.60,-37.68,179.43,74.15,182958.0,-61639.0,101966.0,838.0,-283.41,60.0,H-SC,12.12,145.0,-0.34,0.69,51.74,XR,NTT,CHEMICALS
84,UNITDSPR,4.68,-2.15,23.42,20.77,53656.0,-5040.0,229104.0,1644.0,-13.25,55.0,X-MC,3.00,64.0,-0.09,1.54,9.29,X40N,NTT,BREWERIES

In [11]:
# bottom 5 today
df_tmp = df_portfolio_features.sort_values(by = 'Today P/L%', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
88,VOLTAS,-3.37,-2.22,48.49,45.20,90911.0,-4257.0,187485.0,1856.00,11.92,35.0,X-MC,1.29,79.0,-0.05,1.26,2.43,XY25,NTT,AC
24,EASEMYTRIP,-2.90,-55.68,228.77,45.70,179257.0,-98458.0,78357.0,26.40,-18.55,55.0,M-SC,7.08,204.0,-0.55,0.53,37.26,XY24,NTT,TRAVEL
73,SONACOMS,-2.43,-0.82,40.24,39.09,40372.0,-832.0,100327.0,804.02,-21.42,50.0,M-MC,19.50,193.0,-0.02,0.67,41.93,AR,ATH,AUTO
29,GREENPANEL,-2.41,-45.38,162.07,43.14,162064.0,-83082.0,99996.0,537.00,124.16,41.0,M-SC,16.65,225.0,-0.51,0.67,20.12,XY24,NTT,MISC
71,SIEMENS,-2.41,-3.15,29.59,25.51,53332.0,-5860.0,180235.0,4671.50,51.28,49.0,H-LC,17.07,51.0,-0.11,1.21,26.54,AR,ATH,ELECTRICAL

In [12]:
# top 5 to exit based on CumlRnk
df_tmp = df_portfolio_features[~df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])]
df_tmp = df_tmp[(df_tmp['Current P/L%'] > -1) & (df_tmp['Current P/L%'] < 1)].sort_values(by = 'CumlRnk', ascending=False)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
73,SONACOMS,-2.43,-0.82,40.24,39.09,40372.0,-832.0,100327.0,804.02,-21.42,50.0,M-MC,19.5,193.0,-0.02,0.67,41.93,AR,ATH,AUTO

In [13]:
# OX40N stocks to exit
df_tmp = df_portfolio_features[(df_portfolio_features['Symbol'].isin(list_ox40n))].sort_values(by = 'Current P/L%', ascending=False)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
25,FINCABLES,-1.22,34.40,54.70,107.91,108544.0,50791.0,198435.0,1641.55,20.75,61.0,M-SC,23.95,220.0,0.47,1.33,49.29,OX40N,ATH,CABLES
72,SIS,1.31,-10.32,35.21,21.26,35061.0,-11454.0,99578.0,528.00,2367.36,66.0,H-SC,13.56,168.0,-0.33,0.67,48.06,OX40N,NTT,MISC
16,CERA,-0.05,-25.65,66.62,23.89,87132.0,-45113.0,130790.0,9475.00,-28.16,59.0,H-SC,9.09,153.0,-0.52,0.88,25.69,OX40N,NTT,CERAMICS
50,KANSAINER,-0.17,-26.05,53.44,13.47,106576.0,-70236.0,199431.0,340.00,-36.46,68.0,H-SC,14.76,162.0,-0.66,1.34,39.30,XY24,NTT,PAINTS
43,INDIGOPNTS,1.06,-29.82,42.52,0.02,52090.0,-52053.0,122506.0,1408.00,86.94,69.0,M-SC,20.31,222.0,-1.00,0.82,38.99,OX40N,NTT,PAINTS

In [14]:
# top 5 to book for rotation
df_tmp = df_portfolio_features[(df_portfolio_features['Current P/L%'] > 20) ].sort_values(by = 'CumlRnk', ascending=False)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
25,FINCABLES,-1.22,34.40,54.70,107.91,108544.0,50791.0,198435.0,1641.55,20.75,61.0,M-SC,23.95,220.0,0.47,1.33,49.29,OX40N,ATH,CABLES
68,SATIN,0.20,24.82,21.64,51.83,74627.0,68574.0,344858.0,274.00,11.70,84.0,H-SC,25.10,159.0,0.92,2.32,68.00,XY24,NTT,FINANCE

In [15]:
# top 5 to monitor for exit
df_tmp = df_portfolio_features[~df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])]
df_tmp = df_tmp[(df_tmp['Current P/L%'] > 0) ].sort_values(by = 'Dev%_PE', ascending=False)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
25,FINCABLES,-1.22,34.40,54.70,107.91,108544.0,50791.0,198435.0,1641.55,20.75,61.0,M-SC,23.95,220.0,0.47,1.33,49.29,OX40N,ATH,CABLES
68,SATIN,0.20,24.82,21.64,51.83,74627.0,68574.0,344858.0,274.00,11.70,84.0,H-SC,25.10,159.0,0.92,2.32,68.00,XY24,NTT,FINANCE
91,ZYDUSLIFE,2.05,6.72,27.09,35.63,60590.0,14089.0,223663.0,1286.17,-7.21,70.0,H-MC,3.04,120.0,0.23,1.50,17.60,AR,ATH,PHARMA

In [16]:
# top 5 to book for rotation from weak conviction
df_tmp = df_portfolio_features[~df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])]
df_tmp = df_tmp[~df_tmp['Criteria'].isin(['XY25','XY24','X40', 'X40N'])].sort_values(by = 'RRR Ind', ascending=False)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
25,FINCABLES,-1.22,34.40,54.70,107.91,108544.0,50791.0,198435.0,1641.55,20.75,61.0,M-SC,23.95,220.0,0.47,1.33,49.29,OX40N,ATH,CABLES
91,ZYDUSLIFE,2.05,6.72,27.09,35.63,60590.0,14089.0,223663.0,1286.17,-7.21,70.0,H-MC,3.04,120.0,0.23,1.50,17.60,AR,ATH,PHARMA
73,SONACOMS,-2.43,-0.82,40.24,39.09,40372.0,-832.0,100327.0,804.02,-21.42,50.0,M-MC,19.50,193.0,-0.02,0.67,41.93,AR,ATH,AUTO
55,MASFIN,-0.71,-1.18,23.02,21.57,22289.0,-1155.0,96825.0,397.04,-14.63,46.0,H-SC,5.78,167.0,-0.05,0.65,20.19,XR,ATH,FINANCE
42,INDIAMART,0.24,-15.09,143.45,106.72,150232.0,-18608.0,104728.0,4810.62,-61.72,32.0,H-SC,9.42,140.0,-0.12,0.70,0.62,AR,ATH,MISC

In [17]:
# top 5 to accumulate based on lowest RSI_14
df_tmp = df_portfolio_features[df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])].sort_values(by = 'RSI_14', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
33,HCLTECH,0.30,-26.84,66.08,21.51,116963.0,-64922.0,177002.0,1872.35,-23.08,25.0,X-LC,16.51,8.0,-0.56,1.19,0.30,X40,ATH,IT
79,TCS,1.10,-33.34,89.88,26.57,277563.0,-154458.0,308815.0,4311.59,-43.63,31.0,X-LC,15.77,2.0,-0.56,2.08,1.10,X40,ATH,IT
45,INFY,1.73,-24.17,77.04,34.24,182786.0,-75627.0,237261.0,1972.00,-40.49,32.0,X-LC,18.17,3.0,-0.41,1.60,1.73,X40,NTT,IT
88,VOLTAS,-3.37,-2.22,48.49,45.20,90911.0,-4257.0,187485.0,1856.00,11.92,35.0,X-MC,1.29,79.0,-0.05,1.26,2.43,XY25,NTT,AC
65,RELIANCE,-1.91,-14.25,46.13,25.30,79490.0,-28645.0,172318.0,1952.00,-16.57,39.0,X-LC,3.59,21.0,-0.36,1.16,2.39,XY25,BTT,REFINERIES

In [18]:
# top 5 to accumulate based on Spread and CumlRnk
df_tmp = df_portfolio_features[df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])]
df_tmp = df_tmp[(df_tmp['CumlRnk'] < 100)].sort_values(by = 'Spread%', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
88,VOLTAS,-3.37,-2.22,48.49,45.20,90911.0,-4257.0,187485.0,1856.00,11.92,35.0,X-MC,1.29,79.0,-0.05,1.26,2.43,XY25,NTT,AC
84,UNITDSPR,4.68,-2.15,23.42,20.77,53656.0,-5040.0,229104.0,1644.00,-13.25,55.0,X-MC,3.00,64.0,-0.09,1.54,9.29,X40N,NTT,BREWERIES
65,RELIANCE,-1.91,-14.25,46.13,25.30,79490.0,-28645.0,172318.0,1952.00,-16.57,39.0,X-LC,3.59,21.0,-0.36,1.16,2.39,XY25,BTT,REFINERIES
39,ICICIGI,-0.65,-2.70,22.66,19.34,44119.0,-5408.0,194701.0,2252.93,-18.12,55.0,X-MC,4.73,66.0,-0.12,1.31,8.74,X40,ATH,INSURANCE
19,COLPAL,0.72,-17.91,72.38,41.51,156486.0,-47165.0,216200.0,3726.84,-0.69,59.0,X-MC,5.40,62.0,-0.30,1.45,20.87,XY25,ATH,FMCG

In [19]:
# top 5 to accumulate based on lowest Gained%
df_tmp = df_portfolio_features[df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])].sort_values(by = 'Gained%', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
33,HCLTECH,0.30,-26.84,66.08,21.51,116963.0,-64922.0,177002.0,1872.35,-23.08,25.0,X-LC,16.51,8.0,-0.56,1.19,0.30,X40,ATH,IT
79,TCS,1.10,-33.34,89.88,26.57,277563.0,-154458.0,308815.0,4311.59,-43.63,31.0,X-LC,15.77,2.0,-0.56,2.08,1.10,X40,ATH,IT
45,INFY,1.73,-24.17,77.04,34.24,182786.0,-75627.0,237261.0,1972.00,-40.49,32.0,X-LC,18.17,3.0,-0.41,1.60,1.73,X40,NTT,IT
65,RELIANCE,-1.91,-14.25,46.13,25.30,79490.0,-28645.0,172318.0,1952.00,-16.57,39.0,X-LC,3.59,21.0,-0.36,1.16,2.39,XY25,BTT,REFINERIES
88,VOLTAS,-3.37,-2.22,48.49,45.20,90911.0,-4257.0,187485.0,1856.00,11.92,35.0,X-MC,1.29,79.0,-0.05,1.26,2.43,XY25,NTT,AC

In [20]:
# top 5 to accumulate based on lowest CurrAlloc%
df_tmp = df_portfolio_features[df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])].sort_values(by = 'CurrAlloc%', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
64,RELAXO,-0.48,-62.49,306.08,52.31,166645.0,-90715.0,54445.0,1176.00,-60.02,44.0,X-SC,25.00,92.0,-0.54,0.37,21.73,X40N,NTT,FOOTWEAR
10,BATAINDIA,-1.11,-54.99,200.39,35.20,116052.0,-70757.0,57913.0,2096.00,-24.04,40.0,X-SC,26.21,91.0,-0.61,0.39,14.86,X40,NTT,FOOTWEAR
60,QUESS,-1.30,-16.16,107.42,73.90,96180.0,-17257.0,89536.0,424.00,-54.82,52.0,X-SC,12.11,80.0,-0.18,0.60,22.06,XY24,NTT,MISC
28,GODREJCP,1.07,-6.53,40.66,31.47,56479.0,-9709.0,138905.0,1469.04,-1.64,46.0,X-LC,7.62,32.0,-0.17,0.93,6.58,X40N,ATH,FMCG
53,M&M,-1.26,1.69,21.34,23.38,30094.0,2340.0,141021.0,3802.40,-13.74,47.0,X-LC,8.37,25.0,0.08,0.95,6.92,X40N,ATH,AUTO

In [21]:
# top 5 to accumulate based on CumlRnk
df_tmp = df_portfolio_features.sort_values(by = 'CumlRnk', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
47,ITC,1.04,-18.24,45.62,19.06,126877.0,-62048.0,278118.0,452.00,-55.12,55.0,X-LC,15.50,1.0,-0.49,1.87,7.89,X40,NTT,FMCG
79,TCS,1.10,-33.34,89.88,26.57,277563.0,-154458.0,308815.0,4311.59,-43.63,31.0,X-LC,15.77,2.0,-0.56,2.08,1.10,X40,ATH,IT
45,INFY,1.73,-24.17,77.04,34.24,182786.0,-75627.0,237261.0,1972.00,-40.49,32.0,X-LC,18.17,3.0,-0.41,1.60,1.73,X40,NTT,IT
81,TMPV,5.80,-18.42,67.41,36.58,195694.0,-65537.0,290304.0,600.00,-82.53,58.0,X-LC,5.97,4.0,-0.33,1.95,21.00,XY24,NTT,AUTO
59,PIDILITIND,-0.89,4.22,13.58,18.37,19971.0,5950.0,147060.0,1670.26,-26.97,62.0,X-LC,5.60,5.0,0.30,0.99,15.47,X40,ATH,CHEMICALS

In [22]:
# top 5 for average up
df_tmp = df_portfolio_features[(df_portfolio_features['Dev%_200'] > 5)].sort_values(by = 'CurrAlloc%', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
44,INDUSINDBK,-0.98,-33.63,100.22,32.89,51356.0,-25964.0,51243.0,1800.00,-340.90,52.0,L-MC,7.67,258.0,-0.51,0.34,26.13,XR,NTT,BANKS
72,SIS,1.31,-10.32,35.21,21.26,35061.0,-11454.0,99578.0,528.00,2367.36,66.0,H-SC,13.56,168.0,-0.33,0.67,48.06,OX40N,NTT,MISC
73,SONACOMS,-2.43,-0.82,40.24,39.09,40372.0,-832.0,100327.0,804.02,-21.42,50.0,M-MC,19.50,193.0,-0.02,0.67,41.93,AR,ATH,AUTO
75,SURYODAY,-2.33,-4.31,28.57,23.03,48958.0,-7711.0,171360.0,216.00,86.40,64.0,H-SC,15.41,166.0,-0.16,1.15,44.28,XR,NTT,BANKS
5,ATULAUTO,5.70,-10.81,63.22,45.57,111150.0,-21318.0,175814.0,844.00,3813.51,65.0,M-SC,7.70,248.0,-0.19,1.18,35.30,XY24,NTT,AUTO

In [23]:
# top 5 RSP
df_tmp = df_portfolio_features.sort_values(by = 'RSP', ascending=False)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
68,SATIN,0.20,24.82,21.64,51.83,74627.0,68574.0,344858.0,274.00,11.70,84.0,H-SC,25.10,159.0,0.92,2.32,68.00,XY24,NTT,FINANCE
3,ALKYLAMINE,-0.47,-25.82,161.03,93.63,120600.0,-26070.0,74893.0,4546.37,-20.57,65.0,H-SC,16.11,142.0,-0.22,0.50,41.42,SR,ATH,CHEMICALS
72,SIS,1.31,-10.32,35.21,21.26,35061.0,-11454.0,99578.0,528.00,2367.36,66.0,H-SC,13.56,168.0,-0.33,0.67,48.06,OX40N,NTT,MISC
75,SURYODAY,-2.33,-4.31,28.57,23.03,48958.0,-7711.0,171360.0,216.00,86.40,64.0,H-SC,15.41,166.0,-0.16,1.15,44.28,XR,NTT,BANKS
25,FINCABLES,-1.22,34.40,54.70,107.91,108544.0,50791.0,198435.0,1641.55,20.75,61.0,M-SC,23.95,220.0,0.47,1.33,49.29,OX40N,ATH,CABLES

In [24]:
# Top N allocation
df_tmp = df_portfolio_features.sort_values(by = 'CurrAlloc%', ascending=False)
top_n_values = [10, 25, 50]

sum_df = pd.DataFrame({
    'Top_N': top_n_values,
    'Sum_Alloc%': [df_tmp['CurrAlloc%'].head(n).sum() for n in top_n_values]
})

sum_df

   Top_N  Sum_Alloc%
0     10       19.30
1     25       42.88
2     50       73.03

In [25]:
# market-cap-wise allocation
df_tmp = df_portfolio_features[cols]
df_tmp.groupby(df_tmp['Conviction'].str[-2:])['CurrAlloc%'].sum().sort_values(ascending=False)

Conviction
SC    42.58
LC    31.42
MC    26.01
Name: CurrAlloc%, dtype: float64

In [26]:
# criteria-wise allocation
df_portfolio_features.groupby('Criteria')['CurrAlloc%'].sum().sort_values(ascending=False)

Criteria
XY24     27.71
X40      25.52
X40N     16.79
XR        8.87
OX40N     6.97
XY25      6.69
AR        6.62
SR        0.84
Name: CurrAlloc%, dtype: float64

In [27]:
# conviction-wise allocation
df_portfolio_features.groupby('Conviction')['CurrAlloc%'].sum().sort_values(ascending=False)

Conviction
X-LC    29.32
H-SC    22.24
X-MC    21.03
M-SC    10.12
X-SC     9.70
H-MC     2.68
M-MC     1.96
H-LC     1.21
M-LC     0.89
L-SC     0.52
L-MC     0.34
Name: CurrAlloc%, dtype: float64

In [28]:
# sector-wise stats
df_tmp = df_portfolio_features.groupby('Category')[['CurrAlloc%', 'Current', 'Current P/L', 'FTT Amt']].sum().sort_values(by=['Current', 'Current P/L'], ascending=False)
df_tmp['Current P/L%'] = round(df_tmp['Current P/L'] * 100 / df_tmp['Current'], 2)
df_tmp['FTT%'] = round(df_tmp['FTT Amt'] * 100 / df_tmp['Current'], 2)
cols = ['CurrAlloc%', 'Current P/L%', 'FTT%']
df_tmp[cols].sort_values(by=['CurrAlloc%'], ascending=False)

               CurrAlloc%  Current P/L%    FTT%
Category
FMCG                15.52        -14.62   55.02
FINANCE             10.88        -14.03   63.62
IT                   9.99        -51.74  128.13
MISC                 6.95        -29.55   85.82
AUTO                 6.73         -9.23   50.18
BANKS                5.69         -7.28   56.89
PAINTS               5.65        -17.15   37.50
INSURANCE            5.34         -4.39   39.92
PHARMA               5.13          2.92   28.29
ELECTRICAL           3.90        -21.78   65.14
CHEMICALS            2.18        -25.24   99.88
HEALTHCARE           2.01        -19.54   50.74
AC                   1.79        -20.18   52.77
APPARELS             1.73         -4.30   39.88
TRAVEL               1.71        -76.31  164.60
FOOTWEAR             1.68        -77.31  148.40
DURABLES             1.68        -54.62   92.23
BREWERIES            1.54         -2.20   23.42
REALTY               1.36         -9.60   27.61
CERAMICS             1.34        -54.43  101.34
CABLES               1.33         25.60   54.70
ENGINEERING          1.18        -37.92  101.00
REFINERIES           1.16        -16.62   46.13
CEMENT               1.10        -63.33  185.53
JEWELLERY            1.02       -112.54  186.38
ENTERTAINMENT        0.69        -87.01  198.55
TEXTILES             0.41        -50.67   93.63
HOTELS               0.32       -141.29  226.40

In [29]:
# money to be made criteria-wise
df_portfolio_features.groupby('Criteria')['FTT Amt'].agg(['sum', 'count']).sort_values(by='sum', ascending=False)

                sum  count
Criteria
XY24      3474948.0     21
X40       1911135.0     19
XR        1362879.0     13
X40N      1226210.0     13
AR        1197489.0      9
OX40N      755736.0     10
XY25       444962.0      5
SR         293509.0      2

In [30]:
# money to be made conviction-wise
df_portfolio_features.groupby('Conviction')['FTT Amt'].agg(['sum', 'count']).sort_values(by='sum', ascending=False)

                  sum  count
Conviction
H-SC        3479694.0     24
X-LC        1937399.0     21
X-MC        1605477.0     15
M-SC        1410841.0     14
X-SC        1360964.0      9
H-MC         298933.0      2
L-SC         214662.0      2
M-LC         159879.0      1
M-MC          94331.0      2
H-LC          53332.0      1
L-MC          51356.0      1

In [31]:
# money to be made criteria and conviction-wise
df_portfolio_features.groupby(['Conviction', 'Criteria'])['FTT Amt'].agg(['sum', 'count']).sort_values(by='sum', ascending=False)

                           sum  count
Conviction Criteria
H-SC       XY24      1072006.0      6
X-LC       X40       1038745.0     10
H-SC       AR         964874.0      5
M-SC       XY24       834484.0      6
H-SC       XR         812022.0      7
X-SC       XY24       784886.0      4
X-MC       X40        661427.0      7
           X40N       498072.0      4
X-SC       X40N       365115.0      3
X-LC       X40N       363023.0      6
           XY24       346648.0      2
H-SC       OX40N      337283.0      4
M-SC       OX40N      310333.0      5
H-SC       SR         293509.0      2
X-MC       XY25       247397.0      2
H-MC       XY24       238343.0      1
X-SC       X40        210963.0      2
X-MC       XY24       198581.0      2
M-SC       XR         187703.0      2
M-LC       XR         159879.0      1
X-LC       XY25       143606.0      2
L-SC       OX40N      108120.0      1
           XR         106542.0      1
M-SC       AR          78321.0      1
H-MC       AR          60590.0      1
M-MC       XY25        53959.0      1
H-LC       AR          53332.0      1
L-MC       XR          51356.0      1
X-LC       XR          45377.0      1
M-MC       AR          40372.0      1

In [32]:
# notebook execution time

end_time = time.time()
execution_time = round(end_time - start_time, 0)
print(f"Notebook execution time: {execution_time} seconds")

Notebook execution time: 59.0 seconds