<a href="https://colab.research.google.com/github/ankit-rathi/Quantvesting_v2/blob/main/myStocks_Portfolio_Analysis.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
'''
!pip install pandas==2.2.2 -qq
!pip install pyxirr -qq
!pip install ta -qq
!pip install yfinance==0.2.59 -qq
'''

'\n!pip install pandas==2.2.2 -qq\n!pip install pyxirr -qq\n!pip install ta -qq\n!pip install yfinance==0.2.59 -qq\n'

In [2]:
# import libraries

import numpy as np
import pandas as pd
import datetime
import warnings
warnings.filterwarnings('ignore')
import yfinance as yfin
import ta
import matplotlib.pyplot as plt
import requests

In [3]:
# notebook start time
import time
import datetime
import pytz

start_time = time.time()

# function to print date timestamp
def print_date_time():
  tz_NY = pytz.timezone('Asia/Kolkata')
  datetime_NY = datetime.datetime.now(tz_NY)
  print("Run date time (IST):", datetime_NY.strftime("%Y-%m-%d %H:%M:%S"))

In [4]:
# function to get booked and reserved amount
def get_amt():
  # fetch the JSON data from the URL
  url = "https://raw.githubusercontent.com/ankit-rathi/Tradevesting_v1/main/data/myPortfolioAmts.json"
  response = requests.get(url)
  pf_amts = response.json()  # parse the JSON data

  # extract values from the JSON
  py_booked_amt_dm = pf_amts["py_booked_amt_dm"]
  py_booked_amt_sv = pf_amts["py_booked_amt_sv"]
  cy_booked_amt_dm = pf_amts["cy_booked_amt_dm"]
  cy_booked_amt_sv = pf_amts["cy_booked_amt_sv"]
  reserve_amt_dm = pf_amts["reserve_amt_dm"]
  reserve_amt_sv = pf_amts["reserve_amt_sv"]

  # perform calculations
  py_booked_amt = py_booked_amt_dm + py_booked_amt_sv
  cy_booked_amt = cy_booked_amt_dm + cy_booked_amt_sv
  reserve_amt = reserve_amt_dm + reserve_amt_sv
  total_booked_amt = py_booked_amt + cy_booked_amt

  return total_booked_amt, reserve_amt, cy_booked_amt, py_booked_amt

gen_output = 0

In [5]:
# function to format the amount
def format_amt(number):
    abs_number = abs(number)

    if abs_number >= 1_00_00_000:  # Crores
        formatted_amt = f"{number / 1_00_00_000:.2f} C"
    elif abs_number >= 1_00_000:  # Lakhs
        formatted_amt = f"{number / 1_00_000:.2f} L"
    elif abs_number >= 1_000:  # Thousands
        formatted_amt = f"{number / 1_000:.2f} K"
    else:
        formatted_amt = f"{number:.2f}"

    return formatted_amt

# function to set start and end date
def get_start_end_date():
  start_date = (datetime.date.today() + datetime.timedelta(days=-365)).strftime('%Y-%m-%d')
  end_date = (datetime.date.today() + datetime.timedelta(days=1)).strftime('%Y-%m-%d')
  return start_date, end_date

# function to fetch my portfolio csv
def get_mypfs_df():
  mypfs_df = pd.read_csv('https://raw.githubusercontent.com/ankit-rathi/Tradevesting_v1/main/data/myPortfolioStocks.csv')
  return mypfs_df

# function to fetch my prospects csv
def get_mypps_df():
  mypps_df = pd.read_csv('https://raw.githubusercontent.com/ankit-rathi/Tradevesting_v1/main/data/myProspectsScrips.csv')
  return mypps_df

# function to fetch screener data
def get_myscreen_df():
  myscreen_df = pd.read_csv('https://raw.githubusercontent.com/ankit-rathi/Tradevesting_v1/main/data/myScreenerDB.csv')
  return myscreen_df

# function to fetch momentum data
def get_myinvmt_df():
  myinvmt_df = pd.read_csv('https://raw.githubusercontent.com/ankit-rathi/Tradevesting_v1/main/data/myInvestments.csv')
  return myinvmt_df

# function to get the stock ids
def get_stock_ids(df_pf):
  stock_n100 = df_pf['Symbol'].unique()

  exclude = ['CADILAHC','MMTC', 'MASFIN']

  stock_ids = df_pf[~df_pf['Symbol'].isin(exclude) ]['Symbol'].unique()

  #mypf = mypf[mypf.Forecast.notnull()]
  #stock_ids = mypf['Symbol'].unique()

  #stock_ids.sort()
  return stock_ids

# get features from screener data
def get_screener_features():
  myscreen_df = get_myscreen_df()
  cols = ['Symbol', 'EPS', 'MedPE', 'ROCE%', 'ROE%', 'CapType']
  return myscreen_df[cols]

# get relative strength
def get_relative_strength(stock_list):

    # Dictionary to store stock tickers and their corresponding percentage price change
    stock_changes = {}

    # Loop through each stock and fetch its price data
    for stock in stock_list:
        try:
            # Download the stock data for the given date range
            stock_data = yfin.Ticker(stock + '.NS').history(period='1mo', interval='1d')[map(str.title, ['open', 'close', 'low', 'high', 'volume'])]

            # Calculate the percentage change for the stock
            if len(stock_data) > 0:
                start_price = stock_data['Close'].iloc[0]
                end_price = stock_data['Close'].iloc[-1]
                percent_change = round(((end_price - start_price) / start_price) * 100, 2)
                stock_changes[stock] = percent_change
            else:
                stock_changes[stock] = np.nan  # If no data is available, set to NaN

        except Exception as e:
            print(f"Error fetching data for {stock}: {e}")
            stock_changes[stock] = np.nan

    # Create a DataFrame with stock tickers and their percentage changes
    df = pd.DataFrame(list(stock_changes.items()), columns=['Symbol', 'Percent_Change'])

    # Drop any stocks with missing data (NaN values)
    df = df.dropna()

    # Calculate the percentile rank based on percentage change
    df['RSP'] = round(df['Percent_Change'].rank(pct=True) * 100, 2)
    cols = ['Symbol', 'RSP']
    df = df[cols]
    # Sort by percentile rank (optional)
    df = df.sort_values(by='RSP', ascending=False).reset_index(drop=True)

    return df

In [6]:
# function to get stock technicals
def stock_prec_dev(stock_symbol):
    #stock_symbol = 'ULTRACEMCO.NS'
    short_window = 20
    mid_window = 50
    long_window = 200
    moving_avg = 'SMA'

    start = datetime.datetime(*map(int, start_date.split('-')))
    end = datetime.datetime(*map(int, end_date.split('-')))

    stock_df = yfin.Ticker(stock_symbol + '.NS').history(period='max', interval='1d')[map(str.title, ['open', 'close', 'low', 'high', 'volume'])]

    stock_df['Max'] = round(max(stock_df['Close']),2)
    stock_df = stock_df[(stock_df.index <= end_date) & (stock_df.index >= start_date)]
    stock_df['200_SMA'] = round(stock_df['Close'].rolling(window = 200, min_periods = 1).mean(),0)
    stock_df['Dev%_200'] = round((stock_df['Close'] - stock_df['200_SMA'])*100/stock_df['200_SMA'],2)
    stock_df.dropna(axis = 0, inplace = True) # remove any null rows

    stock_df['20_SMA'] = stock_df['Close'].rolling(window=20).mean()
    stock_df['50_SMA'] = stock_df['Close'].rolling(window=50).mean()
    stock_df['Symbol'] = stock_symbol

    stock_df['Close'] = round(stock_df['Close'],2)
    stock_df['Min'] = round(min(stock_df['Close']),2)
    stock_df['RSI_14'] = ta.momentum.RSIIndicator(close=stock_df['Close'], window=14).rsi()
    stock_df['RSI_14'] = round(stock_df['RSI_14'],0)
    stock_df['Prev_Close'] = stock_df['Close'].shift(1)
    stock_df.drop(['Open', 'Low', 'High', 'Volume'], axis=1, inplace=True)
    stock_df = stock_df.tail(1)

    max_SMA = max(stock_df['20_SMA'].item(), stock_df['50_SMA'].item(), stock_df['200_SMA'].item())
    min_SMA = min(stock_df['20_SMA'].item(), stock_df['50_SMA'].item(), stock_df['200_SMA'].item())
    ABS_Spread = max_SMA - min_SMA
    stock_df['Spread%'] = round((ABS_Spread / stock_df['200_SMA'].item()) * 100,2)

    return stock_df

# function to compute stock attributes
def get_common_features(stock_ids, df_mypf):

  df_prec_dev = pd.DataFrame()
  df_tmp = get_screener_features()
  df_rs = get_relative_strength(stock_ids)

  for stock_id in stock_ids:
      tmp = stock_prec_dev(stock_id)
      tmp = tmp.reset_index()
      df_prec_dev = pd.concat([df_prec_dev, tmp], ignore_index = True)
  df_prec_dev = pd.merge(df_prec_dev, df_mypf, on= 'Symbol')
  df_prec_dev = pd.merge(df_prec_dev, df_tmp, on= 'Symbol', how='left')
  df_prec_dev = pd.merge(df_prec_dev, df_rs, on= 'Symbol', how='left')
  #print(df_prec_dev.columns)
  df_prec_dev['Curr_PE'] = round(df_prec_dev['Close']/df_prec_dev['EPS'],1)
  df_prec_dev['Dev%_PE'] = round((df_prec_dev['Curr_PE'] - df_prec_dev['MedPE'])*100/df_prec_dev['MedPE'],2)
  df_prec_dev['Conviction'] = df_prec_dev['Conviction'] + '-' + df_prec_dev['CapType']
  return df_prec_dev

# function to arrange stock features
def arrange_features(df_stocks, common_cols, diff_cols):
  df_stocks_common = df_stocks[common_cols].drop_duplicates()
  df_stocks_diff = df_stocks[diff_cols]
  df_stocks_diff['Investment'] = df_stocks_diff['AvgCost'] * df_stocks_diff['Shares']
  df_stocks_diff = df_stocks_diff.groupby(['Symbol'])[['Shares', 'Investment']].aggregate(['sum']).reset_index()
  df_stocks_diff.columns = ['Symbol', 'Shares', 'Investment']
  df_stocks_diff['AvgCost'] = round(df_stocks_diff['Investment']/df_stocks_diff['Shares'],2)
  df_stocks = pd.merge(df_stocks_diff, df_stocks_common, on='Symbol')
  return df_stocks

# plot fact distribution across dimension
def plot_pie_chart(df, dimension, fact):
  # grouping the data by category and calculating the sum of fact for each type
  grouped_data = df.groupby(dimension)[fact].sum()

  # sorting the grouped data in descending order
  grouped_data = grouped_data.sort_values(ascending=False)

  # creating a pie chart
  grouped_data.plot.pie(autopct='%1.1f%%', startangle=90, figsize=(6, 6))

  # adding a title and displaying the plot
  plt.title(f'{dimension} {fact} Distribution')
  plt.ylabel('')  # To hide the y-label
  plt.show()

In [7]:
# function to get portfolio features

def get_portfolio_features(df_common_features):

  print_date_time()
  print('-------------------')

  #df_common_features["Target"] = df_common_features["Target"].fillna(df_common_features["Max"])
  df_common_features['NTT'] = np.where(df_common_features['Strategy']== 'NTT', df_common_features["Target"], df_common_features['Max'])
  df_common_features['LTT'] = np.where(df_common_features['Strategy']== 'BTT', df_common_features["Target"], df_common_features['Max'])
  df_common_features['BOL'] = df_common_features['Min']

  tmp_df = df_common_features[df_common_features['Symbol'].isin(mypf_df[mypf_df['InPortfolio'] != 'NA'].Symbol.values)]
  print('qualified stocks: '+str(len(tmp_df['Symbol'].unique())))
  tmp_df1 = tmp_df[tmp_df['LatestQtr'] == 1]
  print('with latest results: '+str(len(tmp_df1['Symbol'].unique())))
  tmp_df1 = tmp_df1[tmp_df1['StarStock'] == 1]
  print('still star stocks: '+str(len(tmp_df1['Symbol'].unique())))
  tmp_df['Investment'] = tmp_df['AvgCost'] * tmp_df['Shares']
  tmp_df['Current'] = round(tmp_df['Close'] * tmp_df['Shares'],0)
  tmp_df['Previous'] = tmp_df['Prev_Close'] * tmp_df['Shares']
  tmp_df['EstimatedST'] = tmp_df['NTT'] * tmp_df['Shares']
  tmp_df['EstimatedLT'] = tmp_df['LTT'] * tmp_df['Shares']
  tmp_df['Current P/L'] = round((tmp_df['Current'] - tmp_df['Investment']),0)
  tmp_df['Today P/L%'] = round((tmp_df['Current'] - tmp_df['Previous'])*100/tmp_df['Previous'],2)
  tmp_df['Current P/L%'] = round((tmp_df['Current'] - tmp_df['Investment'])*100/tmp_df['Investment'],2)
  tmp_df['EstimatedST P/L%'] = round((tmp_df['EstimatedST'] - tmp_df['Investment'])*100/tmp_df['Investment'],2)
  tmp_df['EstimatedLT P/L%'] = round((tmp_df['EstimatedLT'] - tmp_df['Investment'])*100/tmp_df['Investment'],2)
  tmp_df['NTT%'] = round((tmp_df['NTT'] - tmp_df['Close'])*100/tmp_df['Close'],2)
  tmp_df['LTT%'] = round((tmp_df['LTT'] - tmp_df['Close'])*100/tmp_df['Close'],2)
  tmp_df['Gained%'] = round((tmp_df['Close'] - tmp_df['BOL'])*100/tmp_df['BOL'],2)
  investment = round(sum(tmp_df['AvgCost']*tmp_df['Shares']),0)
  current = round(sum(tmp_df['Close']*tmp_df['Shares']),0)
  tmp_df['InitAlloc%'] = round(tmp_df['Investment']*100/investment,2)
  tmp_df['CurrAlloc%'] = round(tmp_df['Current']*100/current,2)
  tmp_df['FTT'] = tmp_df['LTT']
  tmp_df.loc[tmp_df['Strategy'] == 'NTT', 'FTT'] = tmp_df['NTT']
  tmp_df['FTT%'] = tmp_df['LTT%']
  tmp_df.loc[tmp_df['Strategy'] == 'NTT', 'FTT%'] = tmp_df['NTT%']
  tmp_df['FTT Amt'] = round(tmp_df['FTT%'] * tmp_df['Current']/100,0)
  tmp_df['OTT%'] = round((tmp_df['FTT'] - tmp_df['AvgCost'])*100/tmp_df['AvgCost'],2)
  tmp_df['RRR Ind'] = round(tmp_df['Current P/L']/tmp_df['FTT Amt'],2)
  tmp_df['Risk Ind'] = round(tmp_df['Current P/L%']*tmp_df['CurrAlloc%'],0)

  return tmp_df

# function to print portfolio features
def print_portfolio_stats(df_portfolio_features, myinvmt_df):
  from pyxirr import xirr

  total_booked_amt, reserve_amt, cy_booked_amt, py_booked_amt = get_amt()

  dates = myinvmt_df['Date'].values
  dates = np.append(dates, datetime.date.today().strftime('%d-%b-%y'))
  investment = myinvmt_df['Investment'].values
  dates= pd.to_datetime(dates)

  current = round(sum(df_portfolio_features['Close']*df_portfolio_features['Shares']),0) + reserve_amt
  investment_xirr = np.append(investment, current)
  cagr = round(xirr(pd.DataFrame({"dates": dates, "amounts": investment_xirr}))*100,2)

  investment = -sum(investment)
  invested = round(sum(df_portfolio_features['AvgCost']*df_portfolio_features['Shares']),0) + reserve_amt
  previous = round(sum(df_portfolio_features['Prev_Close']*df_portfolio_features['Shares']),0) + reserve_amt
  cy_invested = investment + py_booked_amt

  today_pnl_amount = current-previous
  today_pnl_percentage = round((current-previous)*100/previous,2)

  curr_pnl_amount = current-invested
  curr_pnl_percentage = round((curr_pnl_amount)*100/(cy_invested),2)

  cy_pnl_amount = cy_booked_amt + curr_pnl_amount
  cy_pnl_percentage = round((cy_pnl_amount)*100/cy_invested,2)

  overall_pnl_amount = total_booked_amt + curr_pnl_amount
  overall_pnl_percentage = round((overall_pnl_amount)*100/investment,2)

  estimate_st = round(sum(df_portfolio_features['FTT']*df_portfolio_features['Shares']),0)  + reserve_amt
  est_st_pnl_amount = estimate_st-current
  est_st_pnl_percentage = round((est_st_pnl_amount)*100/current,2)

  estimate_lt = round(sum(df_portfolio_features['LTT']*df_portfolio_features['Shares']),0)  + reserve_amt
  est_lt_pnl_amount = estimate_lt-current
  est_lt_pnl_percentage = round((est_lt_pnl_amount)*100/current,2)

  total_profit = round(sum(df_portfolio_features[df_portfolio_features['Current P/L%'] > 0]['Current']) - sum(df_portfolio_features[df_portfolio_features['Current P/L%'] > 0]['Investment']),0)
  total_loss = round(sum(df_portfolio_features[df_portfolio_features['Current P/L%'] < 0]['Current']) - sum(df_portfolio_features[df_portfolio_features['Current P/L%'] < 0]['Investment']),0)

  cy_booked_percentage = round((cy_booked_amt)*100/current,2)
  py_booked_percentage = round((py_booked_amt)*100/investment,2)
  total_booked_percentage = round((total_booked_amt)*100/investment,2)

  print('-------------------')
  print('Initial Investment: ', format_amt(investment))
  print('CY Investment: ', format_amt(cy_invested))
  print('Reserve: ', format_amt(reserve_amt))
  print('Current: ',  format_amt(current))
  print('-------------------')
  print('Today PnL: '+ '{} ({}%)'.format(format_amt(today_pnl_amount), today_pnl_percentage))
  print('Current PnL: '+ '{} ({}%)'.format(format_amt(curr_pnl_amount), curr_pnl_percentage))
  print('CY Booked + Current PnL: '+ '{} ({}%)'.format(format_amt(cy_pnl_amount), cy_pnl_percentage))
  print('-------------------')
  print('Total profit: ', format_amt(total_profit))
  print('Total loss: ', format_amt(total_loss))
  print('-------------------')
  print('Total Booked + Current PnL: '+ '{} ({}%)'.format(format_amt(overall_pnl_amount), overall_pnl_percentage))
  print('Total Booked PnL: '+ '{} ({}%)'.format(format_amt(total_booked_amt), total_booked_percentage))
  print('Curr Year Booked PnL: '+ '{} ({}%)'.format(format_amt(cy_booked_amt), cy_booked_percentage))
  print('Prev Year Booked PnL: '+ '{} ({}%)'.format(format_amt(py_booked_amt), py_booked_percentage))
  print('===================')
  print('Est FTT: ',  format_amt(estimate_st))
  print('Est FTT PnL: '+ '{} ({}%)'.format(format_amt(est_st_pnl_amount), est_st_pnl_percentage))

  print('===================')
  print('Deployed: ', format_amt(investment))

  print('Current: ', format_amt(current))

  print('CAGR/XIRR %: '+'{}%'.format(cagr))

In [8]:
# get start and end date
start_date, end_date = get_start_end_date()

# get portfolio and prospects data
mypfs_df = get_mypfs_df()
mypps_df = get_mypps_df()
myinvmt_df = get_myinvmt_df()

# merge above datasets
mypf_df = pd.merge(mypfs_df, mypps_df, on="Symbol")

# seggregate dm and sv portfolio
dm_pf = mypf_df[mypf_df['InPortfolio'] == 'DM']
sv_pf = mypf_df[mypf_df['InPortfolio'] == 'SV']

# build portfolio stock dataframe
dm_stocks = get_stock_ids(dm_pf)
sv_stocks = get_stock_ids(sv_pf)
df_stocks = pd.concat([dm_pf,sv_pf], ignore_index = True)

# arrange common and diff stock features
common_cols = ['Symbol', 'Target', 'Criteria', 'Strategy', 'CumlRnk', 'LatestQtr', 'StarStock', 'Conviction', 'Category', 'InFolio', 'XIRR', 'MBQ']
diff_cols = ['Symbol', 'AvgCost', 'Shares']
df_stocks = arrange_features(df_stocks, common_cols, diff_cols)

# get common features
stock_ids = df_stocks['Symbol'].values
df_common_features = get_common_features(stock_ids, df_stocks)

df_common_features.reset_index(drop=True, inplace=True)
df_common_features.drop(['Date'], axis=1, inplace=True)
# get and print portfolio features
df_portfolio_features = get_portfolio_features(df_common_features)

print_portfolio_stats(df_portfolio_features, myinvmt_df)

df = df_portfolio_features
#plot_pie_chart(df, 'CapType', 'Current')
list_ox40n = list(df[df['MBQ'].str.contains('OX40N', na=False)]['Symbol'].values)

Run date time (IST): 2026-03-20 13:06:26
-------------------
qualified stocks: 86
with latest results: 26
still star stocks: 16
-------------------
Initial Investment:  1.36 C
CY Investment:  1.62 C
Reserve:  1.61 K
Current:  1.32 C
-------------------
Today PnL: 1.21 L (0.93%)
Current PnL: -44.99 L (-27.69%)
CY Booked + Current PnL: -29.10 L (-17.91%)
-------------------
Total profit:  67.82 K
Total loss:  -45.67 L
-------------------
Total Booked + Current PnL: -2.12 L (-1.56%)
Total Booked PnL: 42.87 L (31.64%)
Curr Year Booked PnL: 15.89 L (12.03%)
Prev Year Booked PnL: 26.98 L (19.91%)
===================
Est FTT:  2.48 C
Est FTT PnL: 1.16 C (87.6%)
===================
Deployed:  1.36 C
Current:  1.32 C
CAGR/XIRR %: -1.25%

In [9]:
# top 5 near their targets
cols = ['Symbol', 'Today P/L%', 'Current P/L%', 'FTT%', 'OTT%', 'FTT Amt', 'Current P/L', 'Current', 'FTT', 'Dev%_PE', 'RSI_14','Conviction', 'Spread%',  'CumlRnk', 'RRR Ind', 'CurrAlloc%', 'Gained%', 'Criteria', 'Strategy', 'Category']
df_tmp = df_portfolio_features[~df_portfolio_features['Symbol'].isin(['ENRIN','BLUSPRING','DIGITIDE'])]
df_tmp = df_tmp.sort_values(by = 'FTT Amt', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
50,MASFIN,2.34,-8.22,32.46,21.57,29190.0,-8055.0,89925.0,397.04,-20.96,42.0,H-SC,1.65,167.0,-0.28,0.68,22.65,XR,ATH,FINANCE
77,TTKPRESTIG,-2.19,-38.40,62.50,0.09,38796.0,-38703.0,62074.0,770.00,44.08,40.0,M-SC,18.02,250.0,-1.00,0.47,4.88,OX40N,NTT,DURABLES
37,ICICIGI,0.33,-4.76,25.30,19.34,48219.0,-9521.0,190588.0,2252.93,-19.83,34.0,X-MC,2.66,66.0,-0.20,1.44,5.36,X40,ATH,INSURANCE
2,ABBOTINDIA,0.77,-10.36,31.72,18.07,50854.0,-18535.0,160320.0,35195.00,-23.63,48.0,X-MC,10.66,58.0,-0.36,1.21,1.64,X40,ATH,PHARMA
67,SONACOMS,2.06,-11.95,57.98,39.09,51640.0,-12093.0,89066.0,804.02,-30.19,50.0,M-MC,8.19,193.0,-0.23,0.67,26.00,AR,ATH,AUTO

In [10]:
# top 5 today
df_tmp = df_portfolio_features.sort_values(by = 'Today P/L%', ascending=False)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
8,AWL,6.83,-35.15,157.54,67.02,364026.0,-125240.0,231069.0,485.00,-65.15,51.0,X-SC,25.64,81.0,-0.34,1.75,9.30,XY24,NTT,FMCG
30,HAPPSTMNDS,5.84,-50.89,276.44,84.85,173980.0,-65229.0,62936.0,1480.71,-41.60,54.0,H-SC,27.42,152.0,-0.37,0.48,16.55,AR,ATH,IT
72,TATAELXSI,5.04,-38.85,115.91,32.03,93443.0,-51218.0,80617.0,9161.00,-23.56,38.0,H-SC,20.11,158.0,-0.55,0.61,5.04,OX40N,NTT,IT
52,PAGEIND,3.60,-15.62,58.94,34.11,133470.0,-41929.0,226450.0,51418.64,-39.45,53.0,X-MC,21.09,55.0,-0.31,1.71,7.12,X40,ATH,APPARELS
12,BATAINDIA,3.09,-56.91,213.80,35.20,118531.0,-73230.0,55440.0,2096.00,-27.36,24.0,X-SC,29.88,91.0,-0.62,0.42,3.09,X40,NTT,FOOTWEAR

In [11]:
# bottom 5 today
df_tmp = df_portfolio_features.sort_values(by = 'Today P/L%', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
55,RAJESHEXPO,-3.19,-81.53,441.84,0.07,111936.0,-111843.0,25334.0,518.0,828.03,17.0,L-SC,30.95,268.0,-1.00,0.19,0.00,OX40N,NTT,JEWELLERY
69,SURYODAY,-2.97,-29.56,74.66,23.03,94178.0,-52928.0,126143.0,216.0,38.16,43.0,H-SC,6.70,166.0,-0.56,0.95,23.29,XR,NTT,BANKS
80,VALIANTORG,-2.61,-47.49,231.68,74.15,199015.0,-77704.0,85901.0,838.0,-254.71,60.0,H-SC,28.81,145.0,-0.39,0.65,27.83,XR,NTT,CHEMICALS
77,TTKPRESTIG,-2.19,-38.40,62.50,0.09,38796.0,-38703.0,62074.0,770.0,44.08,40.0,M-SC,18.02,250.0,-1.00,0.47,4.88,OX40N,NTT,DURABLES
70,SYMPHONY,-1.70,-41.10,69.72,-0.03,70281.0,-70337.0,100804.0,1306.0,-52.72,39.0,M-SC,15.05,205.0,-1.00,0.76,1.94,OX40N,NTT,DURABLES

In [12]:
# top 5 to exit based on CumlRnk
df_tmp = df_portfolio_features[~df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])]
df_tmp = df_tmp[(df_tmp['Current P/L%'] > -1) & (df_tmp['Current P/L%'] < 1)].sort_values(by = 'CumlRnk', ascending=False)
df_tmp[cols].head()

Empty DataFrame
Columns: [Symbol, Today P/L%, Current P/L%, FTT%, OTT%, FTT Amt, Current P/L, Current, FTT, Dev%_PE, RSI_14, Conviction, Spread%, CumlRnk, RRR Ind, CurrAlloc%, Gained%, Criteria, Strategy, Category]
Index: []

In [13]:
# OX40N stocks to exit
df_tmp = df_portfolio_features[(df_portfolio_features['Symbol'].isin(list_ox40n))].sort_values(by = 'Current P/L%', ascending=False)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
26,FINCABLES,3.04,10.90,87.48,107.91,143237.0,16093.0,163737.0,1641.55,-0.05,53.0,M-SC,8.30,220.0,0.11,1.24,23.19,OX40N,ATH,CABLES
66,SIS,-1.26,-36.95,92.31,21.26,64626.0,-41022.0,70010.0,528.00,1634.72,32.0,H-SC,13.68,168.0,-0.63,0.53,0.90,OX40N,NTT,MISC
18,CERA,-0.22,-37.92,99.56,23.89,108724.0,-66699.0,109204.0,9475.00,-40.10,46.0,H-SC,18.44,153.0,-0.61,0.83,4.94,OX40N,NTT,CERAMICS
77,TTKPRESTIG,-2.19,-38.40,62.50,0.09,38796.0,-38703.0,62074.0,770.00,44.08,40.0,M-SC,18.02,250.0,-1.00,0.47,4.88,OX40N,NTT,DURABLES
72,TATAELXSI,5.04,-38.85,115.91,32.03,93443.0,-51218.0,80617.0,9161.00,-23.56,38.0,H-SC,20.11,158.0,-0.55,0.61,5.04,OX40N,NTT,IT

In [14]:
# top 5 to book for rotation
df_tmp = df_portfolio_features[(df_portfolio_features['Current P/L%'] > 20) ].sort_values(by = 'CumlRnk', ascending=False)
df_tmp[cols].head()

Empty DataFrame
Columns: [Symbol, Today P/L%, Current P/L%, FTT%, OTT%, FTT Amt, Current P/L, Current, FTT, Dev%_PE, RSI_14, Conviction, Spread%, CumlRnk, RRR Ind, CurrAlloc%, Gained%, Criteria, Strategy, Category]
Index: []

In [15]:
# top 5 to monitor for exit
df_tmp = df_portfolio_features[~df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])]
df_tmp = df_tmp[(df_tmp['Current P/L%'] > 0) ].sort_values(by = 'Dev%_PE', ascending=False)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
26,FINCABLES,3.04,10.90,87.48,107.91,143237.0,16093.0,163737.0,1641.55,-0.05,53.0,M-SC,8.30,220.0,0.11,1.24,23.19,OX40N,ATH,CABLES
1,ABB,1.70,15.95,25.55,45.57,77502.0,41717.0,303336.0,7934.00,-25.51,61.0,H-MC,13.04,125.0,0.54,2.30,34.70,AR,NTT,ELECTRICAL

In [16]:
# top 5 to book for rotation from weak conviction
df_tmp = df_portfolio_features[~df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])]
df_tmp = df_tmp[~df_tmp['Criteria'].isin(['XY25','XY24','X40', 'X40N'])].sort_values(by = 'RRR Ind', ascending=False)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
1,ABB,1.70,15.95,25.55,45.57,77502.0,41717.0,303336.0,7934.00,-25.51,61.0,H-MC,13.04,125.0,0.54,2.30,34.70,AR,NTT,ELECTRICAL
26,FINCABLES,3.04,10.90,87.48,107.91,143237.0,16093.0,163737.0,1641.55,-0.05,53.0,M-SC,8.30,220.0,0.11,1.24,23.19,OX40N,ATH,CABLES
40,INDIAMART,-1.33,-13.97,140.29,106.72,148856.0,-17230.0,106106.0,4810.62,-61.13,33.0,H-SC,10.80,140.0,-0.12,0.80,6.14,AR,ATH,MISC
85,ZYDUSLIFE,1.81,-5.94,44.19,35.63,87113.0,-12442.0,197132.0,1286.17,-18.02,46.0,H-MC,5.29,120.0,-0.14,1.49,9.75,AR,ATH,PHARMA
67,SONACOMS,2.06,-11.95,57.98,39.09,51640.0,-12093.0,89066.0,804.02,-30.19,50.0,M-MC,8.19,193.0,-0.23,0.67,26.00,AR,ATH,AUTO

In [17]:
# top 5 to accumulate based on lowest RSI_14
df_tmp = df_portfolio_features[df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])].sort_values(by = 'RSI_14', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
53,PGHH,0.67,-25.18,76.43,32.01,122105.0,-53760.0,159760.0,17616.87,-49.41,19.0,X-MC,14.40,57.0,-0.44,1.21,0.67,X40,ATH,FMCG
38,ICICIPRULI,-1.03,-7.81,41.81,30.73,75933.0,-15390.0,181615.0,790.00,-32.61,22.0,X-MC,3.38,78.0,-0.20,1.37,3.90,X40,ATH,INSURANCE
58,RELAXO,0.84,-64.38,327.64,52.31,169390.0,-93460.0,51700.0,1176.00,-62.06,22.0,X-SC,24.51,92.0,-0.55,0.39,0.84,X40N,NTT,FOOTWEAR
12,BATAINDIA,3.09,-56.91,213.80,35.20,118531.0,-73230.0,55440.0,2096.00,-27.36,24.0,X-SC,29.88,91.0,-0.62,0.42,3.09,X40,NTT,FOOTWEAR
34,HDFCBANK,-1.41,-5.85,36.35,28.37,80382.0,-13752.0,221133.0,1073.00,-20.04,25.0,X-LC,10.73,26.0,-0.17,1.67,0.00,X40,BTT,BANKS

In [18]:
# top 5 to accumulate based on Spread and CumlRnk
df_tmp = df_portfolio_features[df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])]
df_tmp = df_tmp[(df_tmp['CumlRnk'] < 100)].sort_values(by = 'Spread%', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
78,UNITDSPR,1.54,-3.86,25.62,20.77,57670.0,-9048.0,225096.0,1644.00,-14.79,42.0,X-MC,1.10,64.0,-0.16,1.70,2.58,X40N,NTT,BREWERIES
37,ICICIGI,0.33,-4.76,25.30,19.34,48219.0,-9521.0,190588.0,2252.93,-19.83,34.0,X-MC,2.66,66.0,-0.20,1.44,5.36,X40,ATH,INSURANCE
59,RELIANCE,2.96,-8.48,36.91,25.30,67888.0,-17035.0,183928.0,1952.00,-10.80,54.0,X-LC,3.38,21.0,-0.25,1.39,22.80,XY25,BTT,REFINERIES
38,ICICIPRULI,-1.03,-7.81,41.81,30.73,75933.0,-15390.0,181615.0,790.00,-32.61,22.0,X-MC,3.38,78.0,-0.20,1.37,3.90,X40,ATH,INSURANCE
65,SIEMENS,2.38,-15.30,48.19,25.51,75957.0,-28475.0,157620.0,4671.50,32.32,47.0,H-LC,3.53,51.0,-0.37,1.19,16.07,AR,ATH,ELECTRICAL

In [19]:
# top 5 to accumulate based on lowest Gained%
df_tmp = df_portfolio_features[df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])].sort_values(by = 'Gained%', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
51,MEDANTA,-0.33,-13.49,46.94,27.12,71680.0,-23811.0,152706.0,1486.00,-16.14,29.0,X-SC,11.00,87.0,-0.33,1.16,0.00,XY24,NTT,HEALTHCARE
34,HDFCBANK,-1.41,-5.85,36.35,28.37,80382.0,-13752.0,221133.0,1073.00,-20.04,25.0,X-LC,10.73,26.0,-0.17,1.67,0.00,X40,BTT,BANKS
81,VBL,-0.52,-18.68,66.85,35.67,171689.0,-59015.0,256827.0,671.64,-28.26,32.0,X-LC,7.87,13.0,-0.34,1.94,0.31,X40N,ATH,FMCG
35,HINDUNILVR,0.52,-18.77,39.93,13.67,83382.0,-48243.0,208820.0,2922.00,-39.73,28.0,X-LC,7.35,9.0,-0.58,1.58,0.52,XY25,NTT,FMCG
73,TCS,0.53,-30.47,82.03,26.57,264243.0,-141143.0,322130.0,4311.59,-41.00,25.0,X-LC,16.70,2.0,-0.53,2.44,0.53,X40,ATH,IT

In [20]:
# top 5 to accumulate based on lowest CurrAlloc%
df_tmp = df_portfolio_features[df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])].sort_values(by = 'CurrAlloc%', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
58,RELAXO,0.84,-64.38,327.64,52.31,169390.0,-93460.0,51700.0,1176.00,-62.06,22.0,X-SC,24.51,92.0,-0.55,0.39,0.84,X40N,NTT,FOOTWEAR
12,BATAINDIA,3.09,-56.91,213.80,35.20,118531.0,-73230.0,55440.0,2096.00,-27.36,24.0,X-SC,29.88,91.0,-0.62,0.42,3.09,X40,NTT,FOOTWEAR
54,QUESS,0.29,-26.43,136.38,73.90,107146.0,-28229.0,78564.0,424.00,-60.33,37.0,X-SC,20.48,80.0,-0.26,0.59,2.39,XY24,NTT,MISC
36,HONAUT,1.14,-25.38,102.77,51.31,147886.0,-48938.0,143900.0,58357.33,-37.92,31.0,X-SC,14.99,90.0,-0.33,1.09,1.14,X40N,ATH,ELECTRICAL
51,MEDANTA,-0.33,-13.49,46.94,27.12,71680.0,-23811.0,152706.0,1486.00,-16.14,29.0,X-SC,11.00,87.0,-0.33,1.16,0.00,XY24,NTT,HEALTHCARE

In [21]:
# top 5 to accumulate based on CumlRnk
df_tmp = df_portfolio_features.sort_values(by = 'CumlRnk', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
45,ITC,3.02,-19.14,47.23,19.06,129917.0,-65094.0,275072.0,452.00,-55.52,44.0,X-LC,17.84,1.0,-0.50,2.08,3.02,X40,NTT,FMCG
73,TCS,0.53,-30.47,82.03,26.57,264243.0,-141143.0,322130.0,4311.59,-41.00,25.0,X-LC,16.70,2.0,-0.53,2.44,0.53,X40,ATH,IT
43,INFY,1.38,-15.75,59.34,34.24,156426.0,-49279.0,263609.0,1972.00,-33.60,32.0,X-LC,14.88,3.0,-0.32,2.00,1.38,X40,NTT,IT
75,TMPV,1.70,-28.40,90.75,36.58,231218.0,-101055.0,254786.0,600.00,-84.72,35.0,X-LC,5.02,4.0,-0.44,1.93,1.70,XY24,NTT,AUTO
33,HCLTECH,2.15,-13.04,42.40,23.83,89201.0,-31544.0,210380.0,1908.19,-8.60,38.0,X-LC,11.51,8.0,-0.35,1.59,2.15,X40,ATH,IT

In [22]:
# top 5 for average up
df_tmp = df_portfolio_features[(df_portfolio_features['Dev%_200'] > 5)].sort_values(by = 'CurrAlloc%', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
67,SONACOMS,2.06,-11.95,57.98,39.09,51640.0,-12093.0,89066.0,804.02,-30.19,50.0,M-MC,8.19,193.0,-0.23,0.67,26.00,AR,ATH,AUTO
26,FINCABLES,3.04,10.90,87.48,107.91,143237.0,16093.0,163737.0,1641.55,-0.05,53.0,M-SC,8.30,220.0,0.11,1.24,23.19,OX40N,ATH,CABLES
1,ABB,1.70,15.95,25.55,45.57,77502.0,41717.0,303336.0,7934.00,-25.51,61.0,H-MC,13.04,125.0,0.54,2.30,34.70,AR,NTT,ELECTRICAL

In [23]:
# top 5 RSP
df_tmp = df_portfolio_features.sort_values(by = 'RSP', ascending=False)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
26,FINCABLES,3.04,10.90,87.48,107.91,143237.0,16093.0,163737.0,1641.55,-0.05,53.0,M-SC,8.30,220.0,0.11,1.24,23.19,OX40N,ATH,CABLES
1,ABB,1.70,15.95,25.55,45.57,77502.0,41717.0,303336.0,7934.00,-25.51,61.0,H-MC,13.04,125.0,0.54,2.30,34.70,AR,NTT,ELECTRICAL
30,HAPPSTMNDS,5.84,-50.89,276.44,84.85,173980.0,-65229.0,62936.0,1480.71,-41.60,54.0,H-SC,27.42,152.0,-0.37,0.48,16.55,AR,ATH,IT
80,VALIANTORG,-2.61,-47.49,231.68,74.15,199015.0,-77704.0,85901.0,838.00,-254.71,60.0,H-SC,28.81,145.0,-0.39,0.65,27.83,XR,NTT,CHEMICALS
2,ABBOTINDIA,0.77,-10.36,31.72,18.07,50854.0,-18535.0,160320.0,35195.00,-23.63,48.0,X-MC,10.66,58.0,-0.36,1.21,1.64,X40,ATH,PHARMA

In [24]:
# Top N allocation
df_tmp = df_portfolio_features.sort_values(by = 'CurrAlloc%', ascending=False)
top_n_values = [10, 25, 50]

sum_df = pd.DataFrame({
    'Top_N': top_n_values,
    'Sum_Alloc%': [df_tmp['CurrAlloc%'].head(n).sum() for n in top_n_values]
})

sum_df

   Top_N  Sum_Alloc%
0     10       20.68
1     25       45.63
2     50       78.05

In [25]:
# market-cap-wise allocation
df_tmp = df_portfolio_features[cols]
df_tmp.groupby(df_tmp['Conviction'].str[-2:])['CurrAlloc%'].sum().sort_values(ascending=False)

Conviction
SC    44.52
MC    30.18
LC    25.29
Name: CurrAlloc%, dtype: float64

In [26]:
# criteria-wise allocation
df_portfolio_features.groupby('Criteria')['CurrAlloc%'].sum().sort_values(ascending=False)

Criteria
XY24     27.01
X40      25.45
X40N     15.14
AR        9.21
XR        8.29
XY25      7.32
OX40N     6.79
SR        0.78
Name: CurrAlloc%, dtype: float64

In [27]:
# conviction-wise allocation
df_portfolio_features.groupby('Conviction')['CurrAlloc%'].sum().sort_values(ascending=False)

Conviction
X-LC    23.10
X-MC    22.70
H-SC    21.57
X-SC    12.31
M-SC    10.10
H-MC     5.08
M-MC     2.05
H-LC     1.19
M-LC     1.00
L-SC     0.54
L-MC     0.35
Name: CurrAlloc%, dtype: float64

In [28]:
# sector-wise stats
df_tmp = df_portfolio_features.groupby('Category')[['CurrAlloc%', 'Current', 'Current P/L', 'FTT Amt']].sum().sort_values(by=['Current', 'Current P/L'], ascending=False)
df_tmp['Current P/L%'] = round(df_tmp['Current P/L'] * 100 / df_tmp['Current'], 2)
df_tmp['FTT%'] = round(df_tmp['FTT Amt'] * 100 / df_tmp['Current'], 2)
cols = ['CurrAlloc%', 'Current P/L%', 'FTT%']
df_tmp[cols].sort_values(by=['CurrAlloc%'], ascending=False)

               CurrAlloc%  Current P/L%    FTT%
Category
FMCG                15.17        -24.59   68.82
FINANCE             13.12        -23.92   74.42
IT                  11.66        -46.49  121.04
MISC                 6.95        -46.10  109.57
ELECTRICAL           6.64        -10.44   52.73
PAINTS               5.05        -47.57   73.19
INSURANCE            4.69         -9.22   46.60
BANKS                4.58        -26.75   91.08
PHARMA               4.16         -6.90   40.55
AUTO                 3.68        -34.59   87.99
AC                   2.08        -16.55   48.15
HEALTHCARE           1.90        -43.10   80.45
TRAVEL               1.80        -87.79  181.82
DURABLES             1.80        -62.13  101.57
FOOTWEAR             1.78        -87.56  162.76
APPARELS             1.71        -18.52   58.94
BREWERIES            1.70         -4.02   25.62
REALTY               1.46        -15.19   34.12
REFINERIES           1.39         -9.26   36.91
CERAMICS             1.38        -68.47  119.65
CEMENT               1.25        -62.67  184.36
CABLES               1.24          9.83   87.48
ENGINEERING          1.09        -68.79  145.99
JEWELLERY            1.07       -125.29  203.56
CHEMICALS            1.07        -87.01  239.58
ENTERTAINMENT        0.77        -91.19  205.22
TEXTILES             0.45        -54.66   98.76
HOTELS               0.35       -147.97  235.43

In [29]:
# money to be made criteria-wise
df_portfolio_features.groupby('Criteria')['FTT Amt'].agg(['sum', 'count']).sort_values(by='sum', ascending=False)

                sum  count
Criteria
XY24      4029901.0     21
X40       1809805.0     16
XR        1395559.0     12
AR        1355291.0     10
X40N      1300675.0     10
OX40N      894966.0     10
XY25       472453.0      5
SR         316009.0      2

In [30]:
# money to be made conviction-wise
df_portfolio_features.groupby('Conviction')['FTT Amt'].agg(['sum', 'count']).sort_values(by='sum', ascending=False)

                  sum  count
Conviction
H-SC        3943720.0     24
X-MC        1733915.0     15
X-LC        1722292.0     13
M-SC        1584604.0     14
X-SC        1557201.0     10
H-MC         407241.0      3
L-SC         219744.0      2
M-LC         160134.0      1
M-MC         114155.0      2
H-LC          75957.0      1
L-MC          55696.0      1

In [31]:
# money to be made criteria and conviction-wise
df_portfolio_features.groupby(['Conviction', 'Criteria'])['FTT Amt'].agg(['sum', 'count']).sort_values(by='sum', ascending=False)

                           sum  count
Conviction Criteria
H-SC       XY24      1369765.0      6
           AR         984902.0      5
X-LC       X40        929459.0      7
M-SC       XY24       924520.0      6
H-SC       XR         879813.0      7
X-SC       XY24       846736.0      4
X-MC       X40        676657.0      7
           X40N       527303.0      4
X-SC       X40N       506776.0      4
H-SC       OX40N      393231.0      4
M-SC       OX40N      389799.0      5
X-LC       XY24       374967.0      2
H-SC       SR         316009.0      2
X-MC       XY24       271287.0      2
X-LC       X40N       266596.0      2
X-MC       XY25       258668.0      2
H-MC       XY24       242626.0      1
X-SC       X40        203689.0      2
M-SC       XR         192108.0      2
H-MC       AR         164615.0      2
M-LC       XR         160134.0      1
X-LC       XY25       151270.0      2
L-SC       OX40N      111936.0      1
           XR         107808.0      1
M-SC       AR          78177.0      1
H-LC       AR          75957.0      1
M-MC       XY25        62515.0      1
L-MC       XR          55696.0      1
M-MC       AR          51640.0      1

In [32]:
# notebook execution time

end_time = time.time()
execution_time = round(end_time - start_time, 0)
print(f"Notebook execution time: {execution_time} seconds")

Notebook execution time: 28.0 seconds