<a href="https://colab.research.google.com/github/ankit-rathi/Quantvesting_v2/blob/main/myStocks_Portfolio_Analysis.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
'''
!pip install pandas==2.2.2 -qq
!pip install pyxirr -qq
!pip install ta -qq
!pip install yfinance==0.2.59 -qq
'''

'\n!pip install pandas==2.2.2 -qq\n!pip install pyxirr -qq\n!pip install ta -qq\n!pip install yfinance==0.2.59 -qq\n'

In [2]:
# import libraries

import numpy as np
import pandas as pd
import datetime
import warnings
warnings.filterwarnings('ignore')
import yfinance as yfin
import ta
import matplotlib.pyplot as plt
import requests

In [3]:
# notebook start time
import time
import datetime
import pytz

start_time = time.time()

# function to print date timestamp
def print_date_time():
  tz_NY = pytz.timezone('Asia/Kolkata')
  datetime_NY = datetime.datetime.now(tz_NY)
  print("Run date time (IST):", datetime_NY.strftime("%Y-%m-%d %H:%M:%S"))

In [4]:
# function to get booked and reserved amount
def get_amt():
  # fetch the JSON data from the URL
  url = "https://raw.githubusercontent.com/ankit-rathi/Tradevesting_v1/main/data/myPortfolioAmts.json"
  response = requests.get(url)
  pf_amts = response.json()  # parse the JSON data

  # extract values from the JSON
  py_booked_amt_dm = pf_amts["py_booked_amt_dm"]
  py_booked_amt_sv = pf_amts["py_booked_amt_sv"]
  cy_booked_amt_dm = pf_amts["cy_booked_amt_dm"]
  cy_booked_amt_sv = pf_amts["cy_booked_amt_sv"]
  reserve_amt_dm = pf_amts["reserve_amt_dm"]
  reserve_amt_sv = pf_amts["reserve_amt_sv"]

  # perform calculations
  py_booked_amt = py_booked_amt_dm + py_booked_amt_sv
  cy_booked_amt = cy_booked_amt_dm + cy_booked_amt_sv
  reserve_amt = reserve_amt_dm + reserve_amt_sv
  total_booked_amt = py_booked_amt + cy_booked_amt

  return total_booked_amt, reserve_amt, cy_booked_amt, py_booked_amt

gen_output = 0

In [5]:
# function to format the amount
def format_amt(number):
    abs_number = abs(number)

    if abs_number >= 1_00_00_000:  # Crores
        formatted_amt = f"{number / 1_00_00_000:.2f} C"
    elif abs_number >= 1_00_000:  # Lakhs
        formatted_amt = f"{number / 1_00_000:.2f} L"
    elif abs_number >= 1_000:  # Thousands
        formatted_amt = f"{number / 1_000:.2f} K"
    else:
        formatted_amt = f"{number:.2f}"

    return formatted_amt

# function to set start and end date
def get_start_end_date():
  start_date = (datetime.date.today() + datetime.timedelta(days=-365)).strftime('%Y-%m-%d')
  end_date = (datetime.date.today() + datetime.timedelta(days=1)).strftime('%Y-%m-%d')
  return start_date, end_date

# function to fetch my portfolio csv
def get_mypfs_df():
  mypfs_df = pd.read_csv('https://raw.githubusercontent.com/ankit-rathi/Tradevesting_v1/main/data/myPortfolioStocks.csv')
  return mypfs_df

# function to fetch my prospects csv
def get_mypps_df():
  mypps_df = pd.read_csv('https://raw.githubusercontent.com/ankit-rathi/Tradevesting_v1/main/data/myProspectsScrips.csv')
  return mypps_df

# function to fetch screener data
def get_myscreen_df():
  myscreen_df = pd.read_csv('https://raw.githubusercontent.com/ankit-rathi/Tradevesting_v1/main/data/myScreenerDB.csv')
  return myscreen_df

# function to fetch momentum data
def get_myinvmt_df():
  myinvmt_df = pd.read_csv('https://raw.githubusercontent.com/ankit-rathi/Tradevesting_v1/main/data/myInvestments.csv')
  return myinvmt_df

# function to get the stock ids
def get_stock_ids(df_pf):
  stock_n100 = df_pf['Symbol'].unique()

  exclude = ['CADILAHC','MMTC', 'MASFIN']

  stock_ids = df_pf[~df_pf['Symbol'].isin(exclude) ]['Symbol'].unique()

  #mypf = mypf[mypf.Forecast.notnull()]
  #stock_ids = mypf['Symbol'].unique()

  #stock_ids.sort()
  return stock_ids

# get features from screener data
def get_screener_features():
  myscreen_df = get_myscreen_df()
  cols = ['Symbol', 'EPS', 'MedPE', 'ROCE%', 'ROE%', 'CapType']
  return myscreen_df[cols]

# get relative strength
def get_relative_strength(stock_list):

    # Dictionary to store stock tickers and their corresponding percentage price change
    stock_changes = {}

    # Loop through each stock and fetch its price data
    for stock in stock_list:
        try:
            # Download the stock data for the given date range
            stock_data = yfin.Ticker(stock + '.NS').history(period='1mo', interval='1d')[map(str.title, ['open', 'close', 'low', 'high', 'volume'])]

            # Calculate the percentage change for the stock
            if len(stock_data) > 0:
                start_price = stock_data['Close'].iloc[0]
                end_price = stock_data['Close'].iloc[-1]
                percent_change = round(((end_price - start_price) / start_price) * 100, 2)
                stock_changes[stock] = percent_change
            else:
                stock_changes[stock] = np.nan  # If no data is available, set to NaN

        except Exception as e:
            print(f"Error fetching data for {stock}: {e}")
            stock_changes[stock] = np.nan

    # Create a DataFrame with stock tickers and their percentage changes
    df = pd.DataFrame(list(stock_changes.items()), columns=['Symbol', 'Percent_Change'])

    # Drop any stocks with missing data (NaN values)
    df = df.dropna()

    # Calculate the percentile rank based on percentage change
    df['RSP'] = round(df['Percent_Change'].rank(pct=True) * 100, 2)
    cols = ['Symbol', 'RSP']
    df = df[cols]
    # Sort by percentile rank (optional)
    df = df.sort_values(by='RSP', ascending=False).reset_index(drop=True)

    return df

In [6]:
# function to get stock technicals
def stock_prec_dev(stock_symbol):
    #stock_symbol = 'ULTRACEMCO.NS'
    short_window = 20
    mid_window = 50
    long_window = 200
    moving_avg = 'SMA'

    start = datetime.datetime(*map(int, start_date.split('-')))
    end = datetime.datetime(*map(int, end_date.split('-')))

    stock_df = yfin.Ticker(stock_symbol + '.NS').history(period='max', interval='1d')[map(str.title, ['open', 'close', 'low', 'high', 'volume'])]

    stock_df['Max'] = round(max(stock_df['Close']),2)
    stock_df = stock_df[(stock_df.index <= end_date) & (stock_df.index >= start_date)]
    stock_df['200_SMA'] = round(stock_df['Close'].rolling(window = 200, min_periods = 1).mean(),0)
    stock_df['Dev%_200'] = round((stock_df['Close'] - stock_df['200_SMA'])*100/stock_df['200_SMA'],2)
    stock_df.dropna(axis = 0, inplace = True) # remove any null rows

    stock_df['20_SMA'] = stock_df['Close'].rolling(window=20).mean()
    stock_df['50_SMA'] = stock_df['Close'].rolling(window=50).mean()
    stock_df['Symbol'] = stock_symbol

    stock_df['Close'] = round(stock_df['Close'],2)
    stock_df['Min'] = round(min(stock_df['Close']),2)
    stock_df['RSI_14'] = ta.momentum.RSIIndicator(close=stock_df['Close'], window=14).rsi()
    stock_df['RSI_14'] = round(stock_df['RSI_14'],0)
    stock_df['Prev_Close'] = stock_df['Close'].shift(1)
    stock_df.drop(['Open', 'Low', 'High', 'Volume'], axis=1, inplace=True)
    stock_df = stock_df.tail(1)

    max_SMA = max(stock_df['20_SMA'].item(), stock_df['50_SMA'].item(), stock_df['200_SMA'].item())
    min_SMA = min(stock_df['20_SMA'].item(), stock_df['50_SMA'].item(), stock_df['200_SMA'].item())
    ABS_Spread = max_SMA - min_SMA
    stock_df['Spread%'] = round((ABS_Spread / stock_df['200_SMA'].item()) * 100,2)

    return stock_df

# function to compute stock attributes
def get_common_features(stock_ids, df_mypf):

  df_prec_dev = pd.DataFrame()
  df_tmp = get_screener_features()
  df_rs = get_relative_strength(stock_ids)

  for stock_id in stock_ids:
      tmp = stock_prec_dev(stock_id)
      tmp = tmp.reset_index()
      df_prec_dev = pd.concat([df_prec_dev, tmp], ignore_index = True)
  df_prec_dev = pd.merge(df_prec_dev, df_mypf, on= 'Symbol')
  df_prec_dev = pd.merge(df_prec_dev, df_tmp, on= 'Symbol', how='left')
  df_prec_dev = pd.merge(df_prec_dev, df_rs, on= 'Symbol', how='left')
  #print(df_prec_dev.columns)
  df_prec_dev['Curr_PE'] = round(df_prec_dev['Close']/df_prec_dev['EPS'],1)
  df_prec_dev['Dev%_PE'] = round((df_prec_dev['Curr_PE'] - df_prec_dev['MedPE'])*100/df_prec_dev['MedPE'],2)
  df_prec_dev['Conviction'] = df_prec_dev['Conviction'] + '-' + df_prec_dev['CapType']
  return df_prec_dev

# function to arrange stock features
def arrange_features(df_stocks, common_cols, diff_cols):
  df_stocks_common = df_stocks[common_cols].drop_duplicates()
  df_stocks_diff = df_stocks[diff_cols]
  df_stocks_diff['Investment'] = df_stocks_diff['AvgCost'] * df_stocks_diff['Shares']
  df_stocks_diff = df_stocks_diff.groupby(['Symbol'])[['Shares', 'Investment']].aggregate(['sum']).reset_index()
  df_stocks_diff.columns = ['Symbol', 'Shares', 'Investment']
  df_stocks_diff['AvgCost'] = round(df_stocks_diff['Investment']/df_stocks_diff['Shares'],2)
  df_stocks = pd.merge(df_stocks_diff, df_stocks_common, on='Symbol')
  return df_stocks

# plot fact distribution across dimension
def plot_pie_chart(df, dimension, fact):
  # grouping the data by category and calculating the sum of fact for each type
  grouped_data = df.groupby(dimension)[fact].sum()

  # sorting the grouped data in descending order
  grouped_data = grouped_data.sort_values(ascending=False)

  # creating a pie chart
  grouped_data.plot.pie(autopct='%1.1f%%', startangle=90, figsize=(6, 6))

  # adding a title and displaying the plot
  plt.title(f'{dimension} {fact} Distribution')
  plt.ylabel('')  # To hide the y-label
  plt.show()

In [7]:
# function to get portfolio features

def get_portfolio_features(df_common_features):

  print_date_time()
  print('-------------------')

  #df_common_features["Target"] = df_common_features["Target"].fillna(df_common_features["Max"])
  df_common_features['NTT'] = np.where(df_common_features['Strategy']== 'NTT', df_common_features["Target"], df_common_features['Max'])
  df_common_features['LTT'] = np.where(df_common_features['Strategy']== 'BTT', df_common_features["Target"], df_common_features['Max'])
  df_common_features['BOL'] = df_common_features['Min']

  tmp_df = df_common_features[df_common_features['Symbol'].isin(mypf_df[mypf_df['InPortfolio'] != 'NA'].Symbol.values)]
  print('qualified stocks: '+str(len(tmp_df['Symbol'].unique())))
  tmp_df1 = tmp_df[tmp_df['LatestQtr'] == 1]
  print('with latest results: '+str(len(tmp_df1['Symbol'].unique())))
  tmp_df1 = tmp_df1[tmp_df1['StarStock'] == 1]
  print('still star stocks: '+str(len(tmp_df1['Symbol'].unique())))
  tmp_df['Investment'] = tmp_df['AvgCost'] * tmp_df['Shares']
  tmp_df['Current'] = round(tmp_df['Close'] * tmp_df['Shares'],0)
  tmp_df['Previous'] = tmp_df['Prev_Close'] * tmp_df['Shares']
  tmp_df['EstimatedST'] = tmp_df['NTT'] * tmp_df['Shares']
  tmp_df['EstimatedLT'] = tmp_df['LTT'] * tmp_df['Shares']
  tmp_df['Current P/L'] = round((tmp_df['Current'] - tmp_df['Investment']),0)
  tmp_df['Today P/L%'] = round((tmp_df['Current'] - tmp_df['Previous'])*100/tmp_df['Previous'],2)
  tmp_df['Current P/L%'] = round((tmp_df['Current'] - tmp_df['Investment'])*100/tmp_df['Investment'],2)
  tmp_df['EstimatedST P/L%'] = round((tmp_df['EstimatedST'] - tmp_df['Investment'])*100/tmp_df['Investment'],2)
  tmp_df['EstimatedLT P/L%'] = round((tmp_df['EstimatedLT'] - tmp_df['Investment'])*100/tmp_df['Investment'],2)
  tmp_df['NTT%'] = round((tmp_df['NTT'] - tmp_df['Close'])*100/tmp_df['Close'],2)
  tmp_df['LTT%'] = round((tmp_df['LTT'] - tmp_df['Close'])*100/tmp_df['Close'],2)
  tmp_df['Gained%'] = round((tmp_df['Close'] - tmp_df['BOL'])*100/tmp_df['BOL'],2)
  investment = round(sum(tmp_df['AvgCost']*tmp_df['Shares']),0)
  current = round(sum(tmp_df['Close']*tmp_df['Shares']),0)
  tmp_df['InitAlloc%'] = round(tmp_df['Investment']*100/investment,2)
  tmp_df['CurrAlloc%'] = round(tmp_df['Current']*100/current,2)
  tmp_df['FTT'] = tmp_df['LTT']
  tmp_df.loc[tmp_df['Strategy'] == 'NTT', 'FTT'] = tmp_df['NTT']
  tmp_df['FTT%'] = tmp_df['LTT%']
  tmp_df.loc[tmp_df['Strategy'] == 'NTT', 'FTT%'] = tmp_df['NTT%']
  tmp_df['FTT Amt'] = round(tmp_df['FTT%'] * tmp_df['Current']/100,0)
  tmp_df['OTT%'] = round((tmp_df['FTT'] - tmp_df['AvgCost'])*100/tmp_df['AvgCost'],2)
  tmp_df['RRR Ind'] = round(tmp_df['Current P/L']/tmp_df['FTT Amt'],2)
  tmp_df['Risk Ind'] = round(tmp_df['Current P/L%']*tmp_df['CurrAlloc%'],0)

  return tmp_df

# function to print portfolio features
def print_portfolio_stats(df_portfolio_features, myinvmt_df):
  from pyxirr import xirr

  total_booked_amt, reserve_amt, cy_booked_amt, py_booked_amt = get_amt()

  dates = myinvmt_df['Date'].values
  dates = np.append(dates, datetime.date.today().strftime('%d-%b-%y'))
  investment = myinvmt_df['Investment'].values
  dates= pd.to_datetime(dates)

  current = round(sum(df_portfolio_features['Close']*df_portfolio_features['Shares']),0) + reserve_amt
  investment_xirr = np.append(investment, current)
  cagr = round(xirr(pd.DataFrame({"dates": dates, "amounts": investment_xirr}))*100,2)

  investment = -sum(investment)
  invested = round(sum(df_portfolio_features['AvgCost']*df_portfolio_features['Shares']),0) + reserve_amt
  previous = round(sum(df_portfolio_features['Prev_Close']*df_portfolio_features['Shares']),0) + reserve_amt
  cy_invested = investment + py_booked_amt

  today_pnl_amount = current-previous
  today_pnl_percentage = round((current-previous)*100/previous,2)

  curr_pnl_amount = current-invested
  curr_pnl_percentage = round((curr_pnl_amount)*100/(cy_invested),2)

  cy_pnl_amount = cy_booked_amt + curr_pnl_amount
  cy_pnl_percentage = round((cy_pnl_amount)*100/cy_invested,2)

  overall_pnl_amount = total_booked_amt + curr_pnl_amount
  overall_pnl_percentage = round((overall_pnl_amount)*100/investment,2)

  estimate_st = round(sum(df_portfolio_features['FTT']*df_portfolio_features['Shares']),0)  + reserve_amt
  est_st_pnl_amount = estimate_st-current
  est_st_pnl_percentage = round((est_st_pnl_amount)*100/current,2)

  estimate_lt = round(sum(df_portfolio_features['LTT']*df_portfolio_features['Shares']),0)  + reserve_amt
  est_lt_pnl_amount = estimate_lt-current
  est_lt_pnl_percentage = round((est_lt_pnl_amount)*100/current,2)

  total_profit = round(sum(df_portfolio_features[df_portfolio_features['Current P/L%'] > 0]['Current']) - sum(df_portfolio_features[df_portfolio_features['Current P/L%'] > 0]['Investment']),0)
  total_loss = round(sum(df_portfolio_features[df_portfolio_features['Current P/L%'] < 0]['Current']) - sum(df_portfolio_features[df_portfolio_features['Current P/L%'] < 0]['Investment']),0)

  cy_booked_percentage = round((cy_booked_amt)*100/current,2)
  py_booked_percentage = round((py_booked_amt)*100/investment,2)
  total_booked_percentage = round((total_booked_amt)*100/investment,2)

  print('-------------------')
  print('Initial Investment: ', format_amt(investment))
  print('CY Investment: ', format_amt(cy_invested))
  print('Reserve: ', format_amt(reserve_amt))
  print('Current: ',  format_amt(current))
  print('-------------------')
  print('Today PnL: '+ '{} ({}%)'.format(format_amt(today_pnl_amount), today_pnl_percentage))
  print('Current PnL: '+ '{} ({}%)'.format(format_amt(curr_pnl_amount), curr_pnl_percentage))
  print('CY Booked + Current PnL: '+ '{} ({}%)'.format(format_amt(cy_pnl_amount), cy_pnl_percentage))
  print('-------------------')
  print('Total profit: ', format_amt(total_profit))
  print('Total loss: ', format_amt(total_loss))
  print('-------------------')
  print('Total Booked + Current PnL: '+ '{} ({}%)'.format(format_amt(overall_pnl_amount), overall_pnl_percentage))
  print('Total Booked PnL: '+ '{} ({}%)'.format(format_amt(total_booked_amt), total_booked_percentage))
  print('Curr Year Booked PnL: '+ '{} ({}%)'.format(format_amt(cy_booked_amt), cy_booked_percentage))
  print('Prev Year Booked PnL: '+ '{} ({}%)'.format(format_amt(py_booked_amt), py_booked_percentage))
  print('===================')
  print('Est FTT: ',  format_amt(estimate_st))
  print('Est FTT PnL: '+ '{} ({}%)'.format(format_amt(est_st_pnl_amount), est_st_pnl_percentage))

  print('===================')
  print('Deployed: ', format_amt(investment))

  print('Current: ', format_amt(current))

  print('CAGR/XIRR %: '+'{}%'.format(cagr))

In [8]:
# get start and end date
start_date, end_date = get_start_end_date()

# get portfolio and prospects data
mypfs_df = get_mypfs_df()
mypps_df = get_mypps_df()
myinvmt_df = get_myinvmt_df()

# merge above datasets
mypf_df = pd.merge(mypfs_df, mypps_df, on="Symbol")

# seggregate dm and sv portfolio
dm_pf = mypf_df[mypf_df['InPortfolio'] == 'DM']
sv_pf = mypf_df[mypf_df['InPortfolio'] == 'SV']

# build portfolio stock dataframe
dm_stocks = get_stock_ids(dm_pf)
sv_stocks = get_stock_ids(sv_pf)
df_stocks = pd.concat([dm_pf,sv_pf], ignore_index = True)

# arrange common and diff stock features
common_cols = ['Symbol', 'Target', 'Criteria', 'Strategy', 'CumlRnk', 'LatestQtr', 'StarStock', 'Conviction', 'Category', 'InFolio', 'XIRR', 'MBQ']
diff_cols = ['Symbol', 'AvgCost', 'Shares']
df_stocks = arrange_features(df_stocks, common_cols, diff_cols)

# get common features
stock_ids = df_stocks['Symbol'].values
df_common_features = get_common_features(stock_ids, df_stocks)

df_common_features.reset_index(drop=True, inplace=True)
df_common_features.drop(['Date'], axis=1, inplace=True)
# get and print portfolio features
df_portfolio_features = get_portfolio_features(df_common_features)

print_portfolio_stats(df_portfolio_features, myinvmt_df)

df = df_portfolio_features
#plot_pie_chart(df, 'CapType', 'Current')
list_ox40n = list(df[df['MBQ'].str.contains('OX40N', na=False)]['Symbol'].values)

Run date time (IST): 2026-06-25 17:37:56
-------------------
qualified stocks: 92
with latest results: 31
still star stocks: 20
-------------------
Initial Investment:  1.40 C
CY Investment:  1.82 C
Reserve:  1.49 K
Current:  1.52 C
-------------------
Today PnL: -26.92 K (-0.18%)
Current PnL: -31.52 L (-17.28%)
CY Booked + Current PnL: -29.44 L (-16.14%)
-------------------
Total profit:  3.94 L
Total loss:  -35.46 L
-------------------
Total Booked + Current PnL: 13.43 L (9.63%)
Total Booked PnL: 44.95 L (32.22%)
Curr Year Booked PnL: 2.08 L (1.37%)
Prev Year Booked PnL: 42.87 L (30.73%)
===================
Est FTT:  2.55 C
Est FTT PnL: 1.03 C (68.17%)
===================
Deployed:  1.40 C
Current:  1.52 C
CAGR/XIRR %: 3.88%

In [9]:
# top 5 near their targets
cols = ['Symbol', 'Today P/L%', 'Current P/L%', 'FTT%', 'OTT%', 'FTT Amt', 'Current P/L', 'Current', 'FTT', 'Dev%_PE', 'RSI_14','Conviction', 'Spread%',  'CumlRnk', 'RRR Ind', 'CurrAlloc%', 'Gained%', 'Criteria', 'Strategy', 'Category']
df_tmp = df_portfolio_features[~df_portfolio_features['Symbol'].isin(['ENRIN','BLUSPRING','DIGITIDE'])]
df_tmp = df_tmp.sort_values(by = 'FTT Amt', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
59,PIDILITIND,1.14,13.17,4.59,18.37,7330.0,18590.0,159700.0,1670.26,-20.71,74.0,X-LC,4.35,5.0,2.54,1.05,25.39,X40,ATH,CHEMICALS
49,JSWINFRA,-2.51,12.31,3.67,16.43,9141.0,27300.0,249074.0,342.00,-3.70,72.0,X-MC,4.76,61.0,2.99,1.64,41.22,X40N,NTT,REALTY
51,KOTAKBANK,0.75,9.29,10.82,21.11,16374.0,12858.0,151330.0,453.24,-6.37,67.0,X-LC,4.95,12.0,0.79,1.00,15.73,X40,ATH,BANKS
72,SIS,-1.38,-0.00,21.27,21.26,23615.0,-5.0,111027.0,528.00,2651.30,63.0,H-SC,24.95,168.0,-0.00,0.73,65.08,OX40N,NTT,MISC
55,MASFIN,-0.75,-4.49,27.28,21.57,25530.0,-4395.0,93585.0,397.04,-17.80,50.0,H-SC,3.12,167.0,-0.17,0.62,11.55,XR,ATH,FINANCE

In [10]:
# top 5 today
df_tmp = df_portfolio_features.sort_values(by = 'Today P/L%', ascending=False)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
64,RELAXO,12.09,-46.44,184.37,52.31,143342.0,-67413.0,77747.0,1176.0,-42.99,78.0,X-SC,14.28,92.0,-0.47,0.51,73.83,X40N,NTT,FOOTWEAR
66,REPCOHOME,7.44,-9.40,109.52,89.82,284270.0,-26945.0,259560.0,880.0,-54.55,70.0,H-SC,2.89,161.0,-0.09,1.71,24.78,XY24,NTT,FINANCE
53,M&M,3.84,3.26,19.49,23.38,27909.0,4518.0,143199.0,3802.4,-12.35,59.0,X-LC,10.51,25.0,0.16,0.94,8.57,X40N,ATH,AUTO
54,MARUTI,3.75,2.29,25.81,28.68,39023.0,3378.0,151195.0,17292.0,-16.04,60.0,X-LC,10.43,33.0,0.09,1.00,12.59,XR,ATH,AUTO
14,CAMPUS,2.17,-19.33,65.23,33.28,88280.0,-32438.0,135337.0,393.0,-35.08,48.0,M-SC,6.87,218.0,-0.37,0.89,8.68,XY24,NTT,FOOTWEAR

In [11]:
# bottom 5 today
df_tmp = df_portfolio_features.sort_values(by = 'Today P/L%', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
61,RAJESHEXPO,-5.00,-81.26,433.91,0.07,111558.0,-111467.0,25710.0,518.0,841.92,47.0,L-SC,37.05,268.0,-1.00,0.17,26.97,OX40N,NTT,JEWELLERY
9,BANDHANBNK,-4.72,-2.94,98.26,92.42,265654.0,-8201.0,270358.0,400.0,132.04,48.0,H-SC,23.26,174.0,-0.03,1.78,48.93,XY24,NTT,BANKS
24,EASEMYTRIP,-4.51,-60.26,266.67,45.70,187357.0,-106557.0,70258.0,26.4,-27.06,40.0,M-SC,4.49,204.0,-0.57,0.46,23.08,XY24,NTT,TRAVEL
21,DEN,-4.00,-40.82,140.08,42.07,70018.0,-34480.0,49984.0,75.0,78.76,61.0,M-SC,6.50,235.0,-0.49,0.33,35.94,AR,NTT,ENTERTAINMENT
80,TITAGARH,-3.65,-16.36,74.24,45.74,150386.0,-39610.0,202567.0,1548.0,11.43,57.0,H-SC,7.72,175.0,-0.26,1.34,54.55,XY24,NTT,ENGINEERING

In [12]:
# top 5 to exit based on CumlRnk
df_tmp = df_portfolio_features[~df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])]
df_tmp = df_tmp[(df_tmp['Current P/L%'] > -1) & (df_tmp['Current P/L%'] < 1)].sort_values(by = 'CumlRnk', ascending=False)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
72,SIS,-1.38,-0.0,21.27,21.26,23615.0,-5.0,111027.0,528.0,2651.3,63.0,H-SC,24.95,168.0,-0.0,0.73,65.08,OX40N,NTT,MISC

In [13]:
# OX40N stocks to exit
df_tmp = df_portfolio_features[(df_portfolio_features['Symbol'].isin(list_ox40n))].sort_values(by = 'Current P/L%', ascending=False)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
25,FINCABLES,-1.77,41.41,47.03,107.91,98192.0,61142.0,208786.0,1641.55,27.35,55.0,M-SC,24.21,220.0,0.62,1.38,57.08,OX40N,ATH,CABLES
72,SIS,-1.38,-0.00,21.27,21.26,23615.0,-5.0,111027.0,528.00,2651.30,63.0,H-SC,24.95,168.0,-0.00,0.73,65.08,OX40N,NTT,MISC
16,CERA,-0.16,-17.23,49.67,23.89,72321.0,-30301.0,145602.0,9475.00,-20.05,62.0,H-SC,8.48,153.0,-0.42,0.96,39.92,OX40N,NTT,CERAMICS
83,TTKPRESTIG,0.84,-25.83,34.96,0.09,26130.0,-26035.0,74742.0,770.00,73.53,63.0,M-SC,8.58,250.0,-1.00,0.49,33.09,OX40N,NTT,DURABLES
43,INDIGOPNTS,-2.10,-28.52,39.93,0.02,49823.0,-49784.0,124775.0,1408.00,90.29,55.0,M-SC,7.65,222.0,-1.00,0.82,41.57,OX40N,NTT,PAINTS

In [14]:
# top 5 to book for rotation
df_tmp = df_portfolio_features[(df_portfolio_features['Current P/L%'] > 20) ].sort_values(by = 'CumlRnk', ascending=False)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
25,FINCABLES,-1.77,41.41,47.03,107.91,98192.0,61142.0,208786.0,1641.55,27.35,55.0,M-SC,24.21,220.0,0.62,1.38,57.08,OX40N,ATH,CABLES
68,SATIN,-3.46,28.02,18.60,51.83,65790.0,77423.0,353707.0,274.00,14.32,53.0,H-SC,41.01,159.0,1.18,2.33,72.31,XY24,NTT,FINANCE

In [15]:
# top 5 to monitor for exit
df_tmp = df_portfolio_features[~df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])]
df_tmp = df_tmp[(df_tmp['Current P/L%'] > 0) ].sort_values(by = 'Dev%_PE', ascending=False)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
74,STARHEALTH,0.49,11.67,31.87,47.26,100053.0,32819.0,313942.0,761.00,76.17,72.0,H-SC,12.56,173.0,0.33,2.07,37.83,XY24,NTT,INSURANCE
25,FINCABLES,-1.77,41.41,47.03,107.91,98192.0,61142.0,208786.0,1641.55,27.35,55.0,M-SC,24.21,220.0,0.62,1.38,57.08,OX40N,ATH,CABLES
68,SATIN,-3.46,28.02,18.60,51.83,65790.0,77423.0,353707.0,274.00,14.32,53.0,H-SC,41.01,159.0,1.18,2.33,72.31,XY24,NTT,FINANCE
91,ZYDUSLIFE,0.19,16.14,16.78,35.63,40844.0,33835.0,243409.0,1286.17,0.90,61.0,H-MC,13.75,120.0,0.83,1.61,27.98,AR,ATH,PHARMA
73,SONACOMS,-0.01,7.13,29.46,38.69,31926.0,7210.0,108369.0,801.69,-15.07,62.0,M-MC,18.06,193.0,0.23,0.71,53.75,AR,ATH,AUTO

In [16]:
# top 5 to book for rotation from weak conviction
df_tmp = df_portfolio_features[~df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])]
df_tmp = df_tmp[~df_tmp['Criteria'].isin(['XY25','XY24','X40', 'X40N'])].sort_values(by = 'RRR Ind', ascending=False)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
91,ZYDUSLIFE,0.19,16.14,16.78,35.63,40844.0,33835.0,243409.0,1286.17,0.90,61.0,H-MC,13.75,120.0,0.83,1.61,27.98,AR,ATH,PHARMA
25,FINCABLES,-1.77,41.41,47.03,107.91,98192.0,61142.0,208786.0,1641.55,27.35,55.0,M-SC,24.21,220.0,0.62,1.38,57.08,OX40N,ATH,CABLES
73,SONACOMS,-0.01,7.13,29.46,38.69,31926.0,7210.0,108369.0,801.69,-15.07,62.0,M-MC,18.06,193.0,0.23,0.71,53.75,AR,ATH,AUTO
72,SIS,-1.38,-0.00,21.27,21.26,23615.0,-5.0,111027.0,528.00,2651.30,63.0,H-SC,24.95,168.0,-0.00,0.73,65.08,OX40N,NTT,MISC
75,SURYODAY,-0.86,-2.04,25.60,23.03,44908.0,-3651.0,175420.0,216.00,90.79,55.0,H-SC,19.41,166.0,-0.08,1.16,47.70,XR,NTT,BANKS

In [17]:
# top 5 to accumulate based on lowest RSI_14
df_tmp = df_portfolio_features[df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])].sort_values(by = 'RSI_14', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
45,INFY,-1.46,-29.12,89.40,34.24,198268.0,-91112.0,221776.0,1972.00,-44.12,36.0,X-LC,17.69,3.0,-0.46,1.46,1.16,X40,NTT,IT
33,HCLTECH,-1.18,-28.57,70.11,21.51,121157.0,-69114.0,172810.0,1872.35,-25.14,36.0,X-LC,18.73,8.0,-0.57,1.14,0.00,X40,ATH,IT
1,ABBOTINDIA,-0.04,-14.17,37.56,18.07,57658.0,-25345.0,153510.0,35195.00,-26.90,38.0,X-MC,6.26,58.0,-0.44,1.01,1.61,X40,ATH,PHARMA
79,TCS,-0.68,-38.51,103.08,24.88,293653.0,-178394.0,284879.0,4253.91,-47.89,38.0,X-LC,20.00,2.0,-0.61,1.88,1.70,X40,ATH,IT
58,PGHH,0.46,-32.41,95.30,32.01,137545.0,-69192.0,144328.0,17616.87,-54.24,39.0,X-MC,20.65,57.0,-0.50,0.95,0.46,X40,ATH,FMCG

In [18]:
# top 5 to accumulate based on Spread and CumlRnk
df_tmp = df_portfolio_features[df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])]
df_tmp = df_tmp[(df_tmp['CumlRnk'] < 100)].sort_values(by = 'Spread%', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
11,BERGEPAINT,1.53,-0.73,26.24,25.32,67137.0,-1890.0,255859.0,680.00,-6.11,60.0,X-MC,2.72,68.0,-0.03,1.69,33.16,XY24,NTT,PAINTS
17,CIPLA,0.15,16.59,14.45,33.43,25804.0,25411.0,178572.0,1648.14,-9.73,66.0,X-LC,3.70,18.0,0.98,1.18,21.91,X40N,ATH,PHARMA
56,MEDANTA,-0.46,12.27,13.23,27.12,26218.0,21655.0,198172.0,1486.00,8.75,69.0,X-SC,3.71,87.0,0.83,1.31,36.55,XY24,NTT,HEALTHCARE
19,COLPAL,1.41,-24.33,84.82,39.86,169046.0,-64065.0,199300.0,3683.41,-8.54,44.0,X-MC,4.10,62.0,-0.38,1.31,12.74,XY25,ATH,FMCG
84,UNITDSPR,1.90,1.73,18.71,20.77,44568.0,4059.0,238203.0,1644.00,-9.71,68.0,X-MC,4.11,64.0,0.09,1.57,13.63,X40N,NTT,BREWERIES

In [19]:
# top 5 to accumulate based on lowest Gained%
df_tmp = df_portfolio_features[df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])].sort_values(by = 'Gained%', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
33,HCLTECH,-1.18,-28.57,70.11,21.51,121157.0,-69114.0,172810.0,1872.35,-25.14,36.0,X-LC,18.73,8.0,-0.57,1.14,0.00,X40,ATH,IT
58,PGHH,0.46,-32.41,95.30,32.01,137545.0,-69192.0,144328.0,17616.87,-54.24,39.0,X-MC,20.65,57.0,-0.50,0.95,0.46,X40,ATH,FMCG
45,INFY,-1.46,-29.12,89.40,34.24,198268.0,-91112.0,221776.0,1972.00,-44.12,36.0,X-LC,17.69,3.0,-0.46,1.46,1.16,X40,NTT,IT
1,ABBOTINDIA,-0.04,-14.17,37.56,18.07,57658.0,-25345.0,153510.0,35195.00,-26.90,38.0,X-MC,6.26,58.0,-0.44,1.01,1.61,X40,ATH,PHARMA
79,TCS,-0.68,-38.51,103.08,24.88,293653.0,-178394.0,284879.0,4253.91,-47.89,38.0,X-LC,20.00,2.0,-0.61,1.88,1.70,X40,ATH,IT

In [20]:
# top 5 to accumulate based on lowest CurrAlloc%
df_tmp = df_portfolio_features[df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])].sort_values(by = 'CurrAlloc%', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
10,BATAINDIA,0.01,-53.87,193.11,35.20,114617.0,-69317.0,59353.0,2096.00,-22.17,54.0,X-SC,22.59,91.0,-0.60,0.39,17.71,X40,NTT,FOOTWEAR
64,RELAXO,12.09,-46.44,184.37,52.31,143342.0,-67413.0,77747.0,1176.00,-42.99,78.0,X-SC,14.28,92.0,-0.47,0.51,73.83,X40N,NTT,FOOTWEAR
60,QUESS,0.40,2.99,68.86,73.90,75734.0,3189.0,109982.0,424.00,-44.35,73.0,X-SC,11.57,80.0,0.04,0.73,49.93,XY24,NTT,MISC
28,GODREJCP,1.38,-7.41,41.99,31.47,57779.0,-11012.0,137602.0,1469.04,-2.65,54.0,X-LC,9.32,32.0,-0.19,0.91,5.58,X40N,ATH,FMCG
53,M&M,3.84,3.26,19.49,23.38,27909.0,4518.0,143199.0,3802.40,-12.35,59.0,X-LC,10.51,25.0,0.16,0.94,8.57,X40N,ATH,AUTO

In [21]:
# top 5 to accumulate based on CumlRnk
df_tmp = df_portfolio_features.sort_values(by = 'CumlRnk', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
47,ITC,-0.12,-23.61,55.86,19.06,145147.0,-80326.0,259840.0,452.00,-57.95,51.0,X-LC,14.72,1.0,-0.55,1.71,4.69,X40,NTT,FMCG
79,TCS,-0.68,-38.51,103.08,24.88,293653.0,-178394.0,284879.0,4253.91,-47.89,38.0,X-LC,20.00,2.0,-0.61,1.88,1.70,X40,ATH,IT
45,INFY,-1.46,-29.12,89.40,34.24,198268.0,-91112.0,221776.0,1972.00,-44.12,36.0,X-LC,17.69,3.0,-0.46,1.46,1.16,X40,NTT,IT
81,TMPV,1.00,-19.60,69.88,36.58,199921.0,-69749.0,286092.0,600.00,-83.62,41.0,X-LC,9.90,4.0,-0.35,1.89,20.23,XY24,NTT,AUTO
59,PIDILITIND,1.14,13.17,4.59,18.37,7330.0,18590.0,159700.0,1670.26,-20.71,74.0,X-LC,4.35,5.0,2.54,1.05,25.39,X40,ATH,CHEMICALS

In [22]:
# top 5 for average up
df_tmp = df_portfolio_features[(df_portfolio_features['Dev%_200'] > 5)].sort_values(by = 'CurrAlloc%', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
44,INDUSINDBK,-0.77,-32.16,95.88,32.89,50222.0,-24826.0,52380.0,1800.00,-346.50,52.0,L-MC,6.97,258.0,-0.49,0.35,29.14,XR,NTT,BANKS
3,ALKYLAMINE,0.97,-23.82,152.75,92.54,117486.0,-24049.0,76914.0,4520.85,-18.40,54.0,H-SC,7.67,142.0,-0.20,0.51,46.05,SR,ATH,CHEMICALS
64,RELAXO,12.09,-46.44,184.37,52.31,143342.0,-67413.0,77747.0,1176.00,-42.99,78.0,X-SC,14.28,92.0,-0.47,0.51,73.83,X40N,NTT,FOOTWEAR
73,SONACOMS,-0.01,7.13,29.46,38.69,31926.0,7210.0,108369.0,801.69,-15.07,62.0,M-MC,18.06,193.0,0.23,0.71,53.75,AR,ATH,AUTO
72,SIS,-1.38,-0.00,21.27,21.26,23615.0,-5.0,111027.0,528.00,2651.30,63.0,H-SC,24.95,168.0,-0.00,0.73,65.08,OX40N,NTT,MISC

In [23]:
# top 5 RSP
df_tmp = df_portfolio_features.sort_values(by = 'RSP', ascending=False)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
64,RELAXO,12.09,-46.44,184.37,52.31,143342.0,-67413.0,77747.0,1176.00,-42.99,78.0,X-SC,14.28,92.0,-0.47,0.51,73.83,X40N,NTT,FOOTWEAR
18,COFFEEDAY,-2.58,-43.71,140.31,35.27,89682.0,-49632.0,63917.0,80.00,-57.75,52.0,L-SC,16.79,266.0,-0.55,0.42,57.62,XR,NTT,HOTELS
60,QUESS,0.40,2.99,68.86,73.90,75734.0,3189.0,109982.0,424.00,-44.35,73.0,X-SC,11.57,80.0,0.04,0.73,49.93,XY24,NTT,MISC
49,JSWINFRA,-2.51,12.31,3.67,16.43,9141.0,27300.0,249074.0,342.00,-3.70,72.0,X-MC,4.76,61.0,2.99,1.64,41.22,X40N,NTT,REALTY
37,HONAUT,1.00,2.17,48.10,51.31,94769.0,4187.0,197025.0,58357.33,-15.00,74.0,X-SC,8.27,90.0,0.04,1.30,49.69,X40N,ATH,ELECTRICAL

In [24]:
# Top N allocation
df_tmp = df_portfolio_features.sort_values(by = 'CurrAlloc%', ascending=False)
top_n_values = [10, 25, 50]

sum_df = pd.DataFrame({
    'Top_N': top_n_values,
    'Sum_Alloc%': [df_tmp['CurrAlloc%'].head(n).sum() for n in top_n_values]
})

sum_df

   Top_N  Sum_Alloc%
0     10       19.21
1     25       42.61
2     50       72.72

In [25]:
# market-cap-wise allocation
df_tmp = df_portfolio_features[cols]
df_tmp.groupby(df_tmp['Conviction'].str[-2:])['CurrAlloc%'].sum().sort_values(ascending=False)

Conviction
SC    43.53
LC    30.57
MC    25.93
Name: CurrAlloc%, dtype: float64

In [26]:
# criteria-wise allocation
df_portfolio_features.groupby('Criteria')['CurrAlloc%'].sum().sort_values(ascending=False)

Criteria
XY24     27.72
X40      24.61
X40N     17.61
XR        8.87
OX40N     7.12
AR        6.77
XY25      6.47
SR        0.86
Name: CurrAlloc%, dtype: float64

In [27]:
# conviction-wise allocation
df_portfolio_features.groupby('Conviction')['CurrAlloc%'].sum().sort_values(ascending=False)

Conviction
X-LC    28.57
H-SC    22.81
X-MC    20.83
M-SC    10.09
X-SC    10.04
H-MC     2.72
M-MC     2.03
H-LC     1.20
M-LC     0.80
L-SC     0.59
L-MC     0.35
Name: CurrAlloc%, dtype: float64

In [28]:
# sector-wise stats
df_tmp = df_portfolio_features.groupby('Category')[['CurrAlloc%', 'Current', 'Current P/L', 'FTT Amt']].sum().sort_values(by=['Current', 'Current P/L'], ascending=False)
df_tmp['Current P/L%'] = round(df_tmp['Current P/L'] * 100 / df_tmp['Current'], 2)
df_tmp['FTT%'] = round(df_tmp['FTT Amt'] * 100 / df_tmp['Current'], 2)
cols = ['CurrAlloc%', 'Current P/L%', 'FTT%']
df_tmp[cols].sort_values(by=['CurrAlloc%'], ascending=False)

               CurrAlloc%  Current P/L%    FTT%
Category
FMCG                14.51        -20.26   62.45
FINANCE             11.11         -9.42   57.01
IT                   9.56        -55.42  133.13
MISC                 7.22        -22.47   75.02
AUTO                 6.65         -8.47   49.10
BANKS                5.77         -4.00   52.09
PAINTS               5.55        -17.09   37.06
INSURANCE            5.35         -2.26   36.76
PHARMA               5.04          3.01   27.01
ELECTRICAL           4.13        -12.95   52.82
CHEMICALS            2.20        -21.65   93.82
HEALTHCARE           2.10        -12.66   42.06
APPARELS             1.89          6.37   25.07
AC                   1.80        -17.44   49.28
FOOTWEAR             1.79        -62.09  127.09
REALTY               1.64         10.96    3.67
BREWERIES            1.57          1.70   18.71
TRAVEL               1.57        -88.07  182.24
DURABLES             1.57        -62.52  102.06
CERAMICS             1.43        -41.86   84.96
CABLES               1.38         29.28   47.03
ENGINEERING          1.34        -19.55   74.24
REFINERIES           1.12        -18.19   48.09
CEMENT               1.06        -67.01  191.95
JEWELLERY            1.04       -103.71  174.48
ENTERTAINMENT        0.79        -60.50  156.22
TEXTILES             0.43        -41.21   81.47
HOTELS               0.42        -77.65  140.31

In [29]:
# money to be made criteria-wise
df_portfolio_features.groupby('Criteria')['FTT Amt'].agg(['sum', 'count']).sort_values(by='sum', ascending=False)

                sum  count
Criteria
XY24      3395284.0     21
X40       1947974.0     19
XR        1339376.0     13
AR        1150587.0      9
X40N      1052441.0     13
OX40N      711531.0     10
XY25       453379.0      5
SR         288221.0      2

In [30]:
# money to be made conviction-wise
df_portfolio_features.groupby('Conviction')['FTT Amt'].agg(['sum', 'count']).sort_values(by='sum', ascending=False)

                  sum  count
Conviction
H-SC        3319832.0     24
X-LC        1952078.0     21
X-MC        1559449.0     15
M-SC        1387455.0     14
X-SC        1282442.0      9
H-MC         286943.0      2
L-SC         201240.0      2
M-LC         170275.0      1
M-MC          76670.0      2
H-LC          52187.0      1
L-MC          50222.0      1

In [31]:
# money to be made criteria and conviction-wise
df_portfolio_features.groupby(['Conviction', 'Criteria'])['FTT Amt'].agg(['sum', 'count']).sort_values(by='sum', ascending=False)

                           sum  count
Conviction Criteria
X-LC       X40       1060656.0     10
H-SC       XY24       980988.0      6
           AR         955612.0      5
M-SC       XY24       822301.0      6
H-SC       XR         801965.0      7
X-SC       XY24       781869.0      4
X-MC       X40        674909.0      7
           X40N       414425.0      4
X-LC       X40N       349852.0      6
           XY24       346006.0      2
M-SC       OX40N      306927.0      5
H-SC       OX40N      293046.0      4
           SR         288221.0      2
X-SC       X40N       288164.0      3
X-MC       XY25       252094.0      2
H-MC       XY24       246099.0      1
X-MC       XY24       218021.0      2
X-SC       X40        212409.0      2
M-SC       XR         188209.0      2
M-LC       XR         170275.0      1
X-LC       XY25       156541.0      2
L-SC       OX40N      111558.0      1
           XR          89682.0      1
M-SC       AR          70018.0      1
H-LC       AR          52187.0      1
L-MC       XR          50222.0      1
M-MC       XY25        44744.0      1
H-MC       AR          40844.0      1
X-LC       XR          39023.0      1
M-MC       AR          31926.0      1

In [32]:
# notebook execution time

end_time = time.time()
execution_time = round(end_time - start_time, 0)
print(f"Notebook execution time: {execution_time} seconds")

Notebook execution time: 33.0 seconds