<a href="https://colab.research.google.com/github/ankit-rathi/Quantvesting_v2/blob/main/myStocks_Portfolio_Analysis.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
'''
!pip install pandas==2.2.2 -qq
!pip install pyxirr -qq
!pip install ta -qq
!pip install yfinance==0.2.59 -qq
'''

'\n!pip install pandas==2.2.2 -qq\n!pip install pyxirr -qq\n!pip install ta -qq\n!pip install yfinance==0.2.59 -qq\n'

In [2]:
# import libraries

import numpy as np
import pandas as pd
import datetime
import warnings
warnings.filterwarnings('ignore')
import yfinance as yfin
import ta
import matplotlib.pyplot as plt
import requests

In [3]:
# notebook start time
import time
import datetime
import pytz

start_time = time.time()

# function to print date timestamp
def print_date_time():
  tz_NY = pytz.timezone('Asia/Kolkata')
  datetime_NY = datetime.datetime.now(tz_NY)
  print("Run date time (IST):", datetime_NY.strftime("%Y-%m-%d %H:%M:%S"))

In [4]:
# function to get booked and reserved amount
def get_amt():
  # fetch the JSON data from the URL
  url = "https://raw.githubusercontent.com/ankit-rathi/Tradevesting_v1/main/data/myPortfolioAmts.json"
  response = requests.get(url)
  pf_amts = response.json()  # parse the JSON data

  # extract values from the JSON
  py_booked_amt_dm = pf_amts["py_booked_amt_dm"]
  py_booked_amt_sv = pf_amts["py_booked_amt_sv"]
  cy_booked_amt_dm = pf_amts["cy_booked_amt_dm"]
  cy_booked_amt_sv = pf_amts["cy_booked_amt_sv"]
  reserve_amt_dm = pf_amts["reserve_amt_dm"]
  reserve_amt_sv = pf_amts["reserve_amt_sv"]

  # perform calculations
  py_booked_amt = py_booked_amt_dm + py_booked_amt_sv
  cy_booked_amt = cy_booked_amt_dm + cy_booked_amt_sv
  reserve_amt = reserve_amt_dm + reserve_amt_sv
  total_booked_amt = py_booked_amt + cy_booked_amt

  return total_booked_amt, reserve_amt, cy_booked_amt, py_booked_amt

gen_output = 0

In [5]:
# function to format the amount
def format_amt(number):
    abs_number = abs(number)

    if abs_number >= 1_00_00_000:  # Crores
        formatted_amt = f"{number / 1_00_00_000:.2f} C"
    elif abs_number >= 1_00_000:  # Lakhs
        formatted_amt = f"{number / 1_00_000:.2f} L"
    elif abs_number >= 1_000:  # Thousands
        formatted_amt = f"{number / 1_000:.2f} K"
    else:
        formatted_amt = f"{number:.2f}"

    return formatted_amt

# function to set start and end date
def get_start_end_date():
  start_date = (datetime.date.today() + datetime.timedelta(days=-365)).strftime('%Y-%m-%d')
  end_date = (datetime.date.today() + datetime.timedelta(days=1)).strftime('%Y-%m-%d')
  return start_date, end_date

# function to fetch my portfolio csv
def get_mypfs_df():
  mypfs_df = pd.read_csv('https://raw.githubusercontent.com/ankit-rathi/Tradevesting_v1/main/data/myPortfolioStocks.csv')
  return mypfs_df

# function to fetch my prospects csv
def get_mypps_df():
  mypps_df = pd.read_csv('https://raw.githubusercontent.com/ankit-rathi/Tradevesting_v1/main/data/myProspectsScrips.csv')
  return mypps_df

# function to fetch screener data
def get_myscreen_df():
  myscreen_df = pd.read_csv('https://raw.githubusercontent.com/ankit-rathi/Tradevesting_v1/main/data/myScreenerDB.csv')
  return myscreen_df

# function to fetch momentum data
def get_myinvmt_df():
  myinvmt_df = pd.read_csv('https://raw.githubusercontent.com/ankit-rathi/Tradevesting_v1/main/data/myInvestments.csv')
  return myinvmt_df

# function to get the stock ids
def get_stock_ids(df_pf):
  stock_n100 = df_pf['Symbol'].unique()

  exclude = ['CADILAHC','MMTC', 'MASFIN']

  stock_ids = df_pf[~df_pf['Symbol'].isin(exclude) ]['Symbol'].unique()

  #mypf = mypf[mypf.Forecast.notnull()]
  #stock_ids = mypf['Symbol'].unique()

  #stock_ids.sort()
  return stock_ids

# get features from screener data
def get_screener_features():
  myscreen_df = get_myscreen_df()
  cols = ['Symbol', 'EPS', 'MedPE', 'ROCE%', 'ROE%', 'CapType']
  return myscreen_df[cols]

# get relative strength
def get_relative_strength(stock_list):

    # Dictionary to store stock tickers and their corresponding percentage price change
    stock_changes = {}

    # Loop through each stock and fetch its price data
    for stock in stock_list:
        try:
            # Download the stock data for the given date range
            stock_data = yfin.Ticker(stock + '.NS').history(period='1mo', interval='1d')[map(str.title, ['open', 'close', 'low', 'high', 'volume'])]

            # Calculate the percentage change for the stock
            if len(stock_data) > 0:
                start_price = stock_data['Close'].iloc[0]
                end_price = stock_data['Close'].iloc[-1]
                percent_change = round(((end_price - start_price) / start_price) * 100, 2)
                stock_changes[stock] = percent_change
            else:
                stock_changes[stock] = np.nan  # If no data is available, set to NaN

        except Exception as e:
            print(f"Error fetching data for {stock}: {e}")
            stock_changes[stock] = np.nan

    # Create a DataFrame with stock tickers and their percentage changes
    df = pd.DataFrame(list(stock_changes.items()), columns=['Symbol', 'Percent_Change'])

    # Drop any stocks with missing data (NaN values)
    df = df.dropna()

    # Calculate the percentile rank based on percentage change
    df['RSP'] = round(df['Percent_Change'].rank(pct=True) * 100, 2)
    cols = ['Symbol', 'RSP']
    df = df[cols]
    # Sort by percentile rank (optional)
    df = df.sort_values(by='RSP', ascending=False).reset_index(drop=True)

    return df

In [6]:
# function to get stock technicals
def stock_prec_dev(stock_symbol):
    #stock_symbol = 'ULTRACEMCO.NS'
    short_window = 20
    mid_window = 50
    long_window = 200
    moving_avg = 'SMA'

    start = datetime.datetime(*map(int, start_date.split('-')))
    end = datetime.datetime(*map(int, end_date.split('-')))

    stock_df = yfin.Ticker(stock_symbol + '.NS').history(period='max', interval='1d')[map(str.title, ['open', 'close', 'low', 'high', 'volume'])]

    stock_df['Max'] = round(max(stock_df['Close']),2)
    stock_df = stock_df[(stock_df.index <= end_date) & (stock_df.index >= start_date)]
    stock_df['200_SMA'] = round(stock_df['Close'].rolling(window = 200, min_periods = 1).mean(),0)
    stock_df['Dev%_200'] = round((stock_df['Close'] - stock_df['200_SMA'])*100/stock_df['200_SMA'],2)
    stock_df.dropna(axis = 0, inplace = True) # remove any null rows

    stock_df['20_SMA'] = stock_df['Close'].rolling(window=20).mean()
    stock_df['50_SMA'] = stock_df['Close'].rolling(window=50).mean()
    stock_df['Symbol'] = stock_symbol

    stock_df['Close'] = round(stock_df['Close'],2)
    stock_df['Min'] = round(min(stock_df['Close']),2)
    stock_df['RSI_14'] = ta.momentum.RSIIndicator(close=stock_df['Close'], window=14).rsi()
    stock_df['RSI_14'] = round(stock_df['RSI_14'],0)
    stock_df['Prev_Close'] = stock_df['Close'].shift(1)
    stock_df.drop(['Open', 'Low', 'High', 'Volume'], axis=1, inplace=True)
    stock_df = stock_df.tail(1)

    max_SMA = max(stock_df['20_SMA'].item(), stock_df['50_SMA'].item(), stock_df['200_SMA'].item())
    min_SMA = min(stock_df['20_SMA'].item(), stock_df['50_SMA'].item(), stock_df['200_SMA'].item())
    ABS_Spread = max_SMA - min_SMA
    stock_df['Spread%'] = round((ABS_Spread / stock_df['200_SMA'].item()) * 100,2)

    return stock_df

# function to compute stock attributes
def get_common_features(stock_ids, df_mypf):

  df_prec_dev = pd.DataFrame()
  df_tmp = get_screener_features()
  df_rs = get_relative_strength(stock_ids)

  for stock_id in stock_ids:
      tmp = stock_prec_dev(stock_id)
      tmp = tmp.reset_index()
      df_prec_dev = pd.concat([df_prec_dev, tmp], ignore_index = True)
  df_prec_dev = pd.merge(df_prec_dev, df_mypf, on= 'Symbol')
  df_prec_dev = pd.merge(df_prec_dev, df_tmp, on= 'Symbol', how='left')
  df_prec_dev = pd.merge(df_prec_dev, df_rs, on= 'Symbol', how='left')
  #print(df_prec_dev.columns)
  df_prec_dev['Curr_PE'] = round(df_prec_dev['Close']/df_prec_dev['EPS'],1)
  df_prec_dev['Dev%_PE'] = round((df_prec_dev['Curr_PE'] - df_prec_dev['MedPE'])*100/df_prec_dev['MedPE'],2)
  df_prec_dev['Conviction'] = df_prec_dev['Conviction'] + '-' + df_prec_dev['CapType']
  return df_prec_dev

# function to arrange stock features
def arrange_features(df_stocks, common_cols, diff_cols):
  df_stocks_common = df_stocks[common_cols].drop_duplicates()
  df_stocks_diff = df_stocks[diff_cols]
  df_stocks_diff['Investment'] = df_stocks_diff['AvgCost'] * df_stocks_diff['Shares']
  df_stocks_diff = df_stocks_diff.groupby(['Symbol'])[['Shares', 'Investment']].aggregate(['sum']).reset_index()
  df_stocks_diff.columns = ['Symbol', 'Shares', 'Investment']
  df_stocks_diff['AvgCost'] = round(df_stocks_diff['Investment']/df_stocks_diff['Shares'],2)
  df_stocks = pd.merge(df_stocks_diff, df_stocks_common, on='Symbol')
  return df_stocks

# plot fact distribution across dimension
def plot_pie_chart(df, dimension, fact):
  # grouping the data by category and calculating the sum of fact for each type
  grouped_data = df.groupby(dimension)[fact].sum()

  # sorting the grouped data in descending order
  grouped_data = grouped_data.sort_values(ascending=False)

  # creating a pie chart
  grouped_data.plot.pie(autopct='%1.1f%%', startangle=90, figsize=(6, 6))

  # adding a title and displaying the plot
  plt.title(f'{dimension} {fact} Distribution')
  plt.ylabel('')  # To hide the y-label
  plt.show()

In [7]:
# function to get portfolio features

def get_portfolio_features(df_common_features):

  print_date_time()
  print('-------------------')

  #df_common_features["Target"] = df_common_features["Target"].fillna(df_common_features["Max"])
  df_common_features['NTT'] = np.where(df_common_features['Strategy']== 'NTT', df_common_features["Target"], df_common_features['Max'])
  df_common_features['LTT'] = np.where(df_common_features['Strategy']== 'BTT', df_common_features["Target"], df_common_features['Max'])
  df_common_features['BOL'] = df_common_features['Min']

  tmp_df = df_common_features[df_common_features['Symbol'].isin(mypf_df[mypf_df['InPortfolio'] != 'NA'].Symbol.values)]
  print('qualified stocks: '+str(len(tmp_df['Symbol'].unique())))
  tmp_df1 = tmp_df[tmp_df['LatestQtr'] == 1]
  print('with latest results: '+str(len(tmp_df1['Symbol'].unique())))
  tmp_df1 = tmp_df1[tmp_df1['StarStock'] == 1]
  print('still star stocks: '+str(len(tmp_df1['Symbol'].unique())))
  tmp_df['Investment'] = tmp_df['AvgCost'] * tmp_df['Shares']
  tmp_df['Current'] = round(tmp_df['Close'] * tmp_df['Shares'],0)
  tmp_df['Previous'] = tmp_df['Prev_Close'] * tmp_df['Shares']
  tmp_df['EstimatedST'] = tmp_df['NTT'] * tmp_df['Shares']
  tmp_df['EstimatedLT'] = tmp_df['LTT'] * tmp_df['Shares']
  tmp_df['Current P/L'] = round((tmp_df['Current'] - tmp_df['Investment']),0)
  tmp_df['Today P/L%'] = round((tmp_df['Current'] - tmp_df['Previous'])*100/tmp_df['Previous'],2)
  tmp_df['Current P/L%'] = round((tmp_df['Current'] - tmp_df['Investment'])*100/tmp_df['Investment'],2)
  tmp_df['EstimatedST P/L%'] = round((tmp_df['EstimatedST'] - tmp_df['Investment'])*100/tmp_df['Investment'],2)
  tmp_df['EstimatedLT P/L%'] = round((tmp_df['EstimatedLT'] - tmp_df['Investment'])*100/tmp_df['Investment'],2)
  tmp_df['NTT%'] = round((tmp_df['NTT'] - tmp_df['Close'])*100/tmp_df['Close'],2)
  tmp_df['LTT%'] = round((tmp_df['LTT'] - tmp_df['Close'])*100/tmp_df['Close'],2)
  tmp_df['Gained%'] = round((tmp_df['Close'] - tmp_df['BOL'])*100/tmp_df['BOL'],2)
  investment = round(sum(tmp_df['AvgCost']*tmp_df['Shares']),0)
  current = round(sum(tmp_df['Close']*tmp_df['Shares']),0)
  tmp_df['InitAlloc%'] = round(tmp_df['Investment']*100/investment,2)
  tmp_df['CurrAlloc%'] = round(tmp_df['Current']*100/current,2)
  tmp_df['FTT'] = tmp_df['LTT']
  tmp_df.loc[tmp_df['Strategy'] == 'NTT', 'FTT'] = tmp_df['NTT']
  tmp_df['FTT%'] = tmp_df['LTT%']
  tmp_df.loc[tmp_df['Strategy'] == 'NTT', 'FTT%'] = tmp_df['NTT%']
  tmp_df['FTT Amt'] = round(tmp_df['FTT%'] * tmp_df['Current']/100,0)
  tmp_df['OTT%'] = round((tmp_df['FTT'] - tmp_df['AvgCost'])*100/tmp_df['AvgCost'],2)
  tmp_df['RRR Ind'] = round(tmp_df['Current P/L']/tmp_df['FTT Amt'],2)
  tmp_df['Risk Ind'] = round(tmp_df['Current P/L%']*tmp_df['CurrAlloc%'],0)

  return tmp_df

# function to print portfolio features
def print_portfolio_stats(df_portfolio_features, myinvmt_df):
  from pyxirr import xirr

  total_booked_amt, reserve_amt, cy_booked_amt, py_booked_amt = get_amt()

  dates = myinvmt_df['Date'].values
  dates = np.append(dates, datetime.date.today().strftime('%d-%b-%y'))
  investment = myinvmt_df['Investment'].values
  dates= pd.to_datetime(dates)

  current = round(sum(df_portfolio_features['Close']*df_portfolio_features['Shares']),0) + reserve_amt
  investment_xirr = np.append(investment, current)
  cagr = round(xirr(pd.DataFrame({"dates": dates, "amounts": investment_xirr}))*100,2)

  investment = -sum(investment)
  invested = round(sum(df_portfolio_features['AvgCost']*df_portfolio_features['Shares']),0) + reserve_amt
  previous = round(sum(df_portfolio_features['Prev_Close']*df_portfolio_features['Shares']),0) + reserve_amt
  cy_invested = investment + py_booked_amt

  today_pnl_amount = current-previous
  today_pnl_percentage = round((current-previous)*100/previous,2)

  curr_pnl_amount = current-invested
  curr_pnl_percentage = round((curr_pnl_amount)*100/(cy_invested),2)

  cy_pnl_amount = cy_booked_amt + curr_pnl_amount
  cy_pnl_percentage = round((cy_pnl_amount)*100/cy_invested,2)

  overall_pnl_amount = total_booked_amt + curr_pnl_amount
  overall_pnl_percentage = round((overall_pnl_amount)*100/investment,2)

  estimate_st = round(sum(df_portfolio_features['FTT']*df_portfolio_features['Shares']),0)  + reserve_amt
  est_st_pnl_amount = estimate_st-current
  est_st_pnl_percentage = round((est_st_pnl_amount)*100/current,2)

  estimate_lt = round(sum(df_portfolio_features['LTT']*df_portfolio_features['Shares']),0)  + reserve_amt
  est_lt_pnl_amount = estimate_lt-current
  est_lt_pnl_percentage = round((est_lt_pnl_amount)*100/current,2)

  total_profit = round(sum(df_portfolio_features[df_portfolio_features['Current P/L%'] > 0]['Current']) - sum(df_portfolio_features[df_portfolio_features['Current P/L%'] > 0]['Investment']),0)
  total_loss = round(sum(df_portfolio_features[df_portfolio_features['Current P/L%'] < 0]['Current']) - sum(df_portfolio_features[df_portfolio_features['Current P/L%'] < 0]['Investment']),0)

  cy_booked_percentage = round((cy_booked_amt)*100/current,2)
  py_booked_percentage = round((py_booked_amt)*100/investment,2)
  total_booked_percentage = round((total_booked_amt)*100/investment,2)

  print('-------------------')
  print('Initial Investment: ', format_amt(investment))
  print('CY Investment: ', format_amt(cy_invested))
  print('Reserve: ', format_amt(reserve_amt))
  print('Current: ',  format_amt(current))
  print('-------------------')
  print('Today PnL: '+ '{} ({}%)'.format(format_amt(today_pnl_amount), today_pnl_percentage))
  print('Current PnL: '+ '{} ({}%)'.format(format_amt(curr_pnl_amount), curr_pnl_percentage))
  print('CY Booked + Current PnL: '+ '{} ({}%)'.format(format_amt(cy_pnl_amount), cy_pnl_percentage))
  print('-------------------')
  print('Total profit: ', format_amt(total_profit))
  print('Total loss: ', format_amt(total_loss))
  print('-------------------')
  print('Total Booked + Current PnL: '+ '{} ({}%)'.format(format_amt(overall_pnl_amount), overall_pnl_percentage))
  print('Total Booked PnL: '+ '{} ({}%)'.format(format_amt(total_booked_amt), total_booked_percentage))
  print('Curr Year Booked PnL: '+ '{} ({}%)'.format(format_amt(cy_booked_amt), cy_booked_percentage))
  print('Prev Year Booked PnL: '+ '{} ({}%)'.format(format_amt(py_booked_amt), py_booked_percentage))
  print('===================')
  print('Est FTT: ',  format_amt(estimate_st))
  print('Est FTT PnL: '+ '{} ({}%)'.format(format_amt(est_st_pnl_amount), est_st_pnl_percentage))

  print('===================')
  print('Deployed: ', format_amt(investment))

  print('Current: ', format_amt(current))

  print('CAGR/XIRR %: '+'{}%'.format(cagr))

In [8]:
# get start and end date
start_date, end_date = get_start_end_date()

# get portfolio and prospects data
mypfs_df = get_mypfs_df()
mypps_df = get_mypps_df()
myinvmt_df = get_myinvmt_df()

# merge above datasets
mypf_df = pd.merge(mypfs_df, mypps_df, on="Symbol")

# seggregate dm and sv portfolio
dm_pf = mypf_df[mypf_df['InPortfolio'] == 'DM']
sv_pf = mypf_df[mypf_df['InPortfolio'] == 'SV']

# build portfolio stock dataframe
dm_stocks = get_stock_ids(dm_pf)
sv_stocks = get_stock_ids(sv_pf)
df_stocks = pd.concat([dm_pf,sv_pf], ignore_index = True)

# arrange common and diff stock features
common_cols = ['Symbol', 'Target', 'Criteria', 'Strategy', 'CumlRnk', 'LatestQtr', 'StarStock', 'Conviction', 'Category', 'InFolio', 'XIRR', 'MBQ']
diff_cols = ['Symbol', 'AvgCost', 'Shares']
df_stocks = arrange_features(df_stocks, common_cols, diff_cols)

# get common features
stock_ids = df_stocks['Symbol'].values
df_common_features = get_common_features(stock_ids, df_stocks)

df_common_features.reset_index(drop=True, inplace=True)
df_common_features.drop(['Date'], axis=1, inplace=True)
# get and print portfolio features
df_portfolio_features = get_portfolio_features(df_common_features)

print_portfolio_stats(df_portfolio_features, myinvmt_df)

df = df_portfolio_features
#plot_pie_chart(df, 'CapType', 'Current')
list_ox40n = list(df[df['MBQ'].str.contains('OX40N', na=False)]['Symbol'].values)

Run date time (IST): 2026-03-03 13:26:17
-------------------
qualified stocks: 86
with latest results: 26
still star stocks: 15
-------------------
Initial Investment:  1.33 C
CY Investment:  1.60 C
Reserve:  2.44 L
Current:  1.34 C
-------------------
Today PnL: -2.70 L (-1.97%)
Current PnL: -40.13 L (-25.08%)
CY Booked + Current PnL: -24.45 L (-15.28%)
-------------------
Total profit:  1.16 L
Total loss:  -41.29 L
-------------------
Total Booked + Current PnL: 2.53 L (1.9%)
Total Booked PnL: 42.66 L (32.07%)
Curr Year Booked PnL: 15.68 L (11.67%)
Prev Year Booked PnL: 26.98 L (20.29%)
===================
Est FTT:  2.41 C
Est FTT PnL: 1.07 C (79.47%)
===================
Deployed:  1.33 C
Current:  1.34 C
CAGR/XIRR %: 0.49%

In [9]:
# top 5 near their targets
cols = ['Symbol', 'Today P/L%', 'Current P/L%', 'FTT%', 'OTT%', 'FTT Amt', 'Current P/L', 'Current', 'FTT', 'Dev%_PE', 'RSI_14','Conviction', 'Spread%',  'CumlRnk', 'RRR Ind', 'CurrAlloc%', 'Gained%', 'Criteria', 'Strategy', 'Category']
df_tmp = df_portfolio_features[~df_portfolio_features['Symbol'].isin(['ENRIN','BLUSPRING','DIGITIDE'])]
df_tmp = df_tmp.sort_values(by = 'FTT Amt', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
19,COALINDIA,-1.02,4.82,12.26,17.67,19335.0,7252.0,157712.0,478.51,26.26,53.0,L-LC,10.86,185.0,0.38,1.20,26.60,XY25,ATH,MINING
50,MASFIN,-2.77,-3.44,25.90,21.57,24503.0,-3375.0,94605.0,397.04,-16.89,42.0,H-SC,6.69,167.0,-0.14,0.72,38.06,XR,ATH,FINANCE
77,TTKPRESTIG,-4.12,-34.86,53.65,0.09,35222.0,-35126.0,65651.0,770.00,52.40,25.0,M-SC,12.06,250.0,-1.00,0.50,0.00,OX40N,NTT,DURABLES
51,MEDANTA,-0.77,-5.65,31.50,24.08,37731.0,-7170.0,119780.0,1486.00,-6.31,48.0,X-SC,7.96,87.0,-0.19,0.91,9.71,XY24,NTT,HEALTHCARE
37,ICICIGI,-0.32,0.41,18.86,19.34,37894.0,814.0,200923.0,2252.93,-15.42,47.0,X-MC,1.20,66.0,0.02,1.52,16.41,X40,ATH,INSURANCE

In [10]:
# top 5 today
df_tmp = df_portfolio_features.sort_values(by = 'Today P/L%', ascending=False)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
27,FINCABLES,3.58,19.87,73.44,107.91,129979.0,29342.0,176986.0,1641.55,8.07,78.0,M-SC,6.67,220.0,0.23,1.34,33.15,OX40N,ATH,CABLES
63,SFL,1.23,-45.47,132.21,26.63,189055.0,-119222.0,142996.0,1287.00,8.31,45.0,M-SC,12.19,242.0,-0.63,1.08,9.76,XY24,NTT,MISC
2,ABBOTINDIA,1.04,-10.08,31.30,18.07,50340.0,-18025.0,160830.0,35195.00,-23.42,48.0,X-MC,11.50,58.0,-0.36,1.22,1.96,X40,ATH,PHARMA
45,ITC,0.41,-17.06,43.54,19.06,122848.0,-58016.0,282150.0,452.00,-54.31,40.0,X-LC,17.12,1.0,-0.47,2.14,2.16,X40,NTT,FMCG
70,SYMPHONY,0.37,-39.10,64.14,-0.03,66853.0,-66911.0,104230.0,1306.00,-51.02,31.0,M-SC,9.36,205.0,-1.00,0.79,0.37,OX40N,NTT,DURABLES

In [11]:
# bottom 5 today
df_tmp = df_portfolio_features.sort_values(by = 'Today P/L%', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
26,EASEMYTRIP,-7.31,-55.91,230.41,45.70,179641.0,-98849.0,77966.0,26.4,-19.04,51.0,M-SC,18.10,204.0,-0.55,0.59,28.46,XY24,NTT,TRAVEL
69,SURYODAY,-5.25,-28.72,72.61,23.03,92682.0,-51428.0,127643.0,216.0,38.16,45.0,H-SC,5.82,166.0,-0.55,0.97,26.65,XR,NTT,BANKS
58,RELAXO,-5.19,-57.25,256.31,52.31,159038.0,-83111.0,62049.0,1176.0,-54.51,27.0,X-SC,15.43,92.0,-0.52,0.47,0.00,X40N,NTT,FOOTWEAR
8,AWL,-4.66,-41.57,169.01,57.19,322077.0,-135560.0,190567.0,485.0,-66.62,13.0,X-SC,19.47,81.0,-0.42,1.45,0.00,XY24,NTT,FMCG
76,TRIDENT,-4.46,-34.56,96.40,28.51,58194.0,-31888.0,60367.0,48.0,-15.68,36.0,M-SC,9.02,223.0,-0.55,0.46,3.30,XR,NTT,TEXTILES

In [12]:
# top 5 to exit based on CumlRnk
df_tmp = df_portfolio_features[~df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])]
df_tmp = df_tmp[(df_tmp['Current P/L%'] > -1) & (df_tmp['Current P/L%'] < 1)].sort_values(by = 'CumlRnk', ascending=False)
df_tmp[cols].head()

Empty DataFrame
Columns: [Symbol, Today P/L%, Current P/L%, FTT%, OTT%, FTT Amt, Current P/L, Current, FTT, Dev%_PE, RSI_14, Conviction, Spread%, CumlRnk, RRR Ind, CurrAlloc%, Gained%, Criteria, Strategy, Category]
Index: []

In [13]:
# OX40N stocks to exit
df_tmp = df_portfolio_features[(df_portfolio_features['Symbol'].isin(list_ox40n))].sort_values(by = 'Current P/L%', ascending=False)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
27,FINCABLES,3.58,19.87,73.44,107.91,129979.0,29342.0,176986.0,1641.55,8.07,78.0,M-SC,6.67,220.0,0.23,1.34,33.15,OX40N,ATH,CABLES
66,SIS,-0.18,-30.01,73.26,21.26,56931.0,-33321.0,77711.0,528.00,1825.39,41.0,H-SC,5.93,168.0,-0.59,0.59,7.13,OX40N,NTT,MISC
48,KANSAINER,-3.54,-34.48,73.20,13.47,129329.0,-92988.0,176679.0,340.00,-43.73,31.0,H-SC,13.43,162.0,-0.72,1.34,0.00,XY24,NTT,PAINTS
41,INDIGOPNTS,-1.98,-34.77,53.34,0.02,60735.0,-60696.0,113863.0,1408.00,73.55,23.0,M-SC,12.63,222.0,-1.00,0.86,0.00,OX40N,NTT,PAINTS
77,TTKPRESTIG,-4.12,-34.86,53.65,0.09,35222.0,-35126.0,65651.0,770.00,52.40,25.0,M-SC,12.06,250.0,-1.00,0.50,0.00,OX40N,NTT,DURABLES

In [14]:
# top 5 to book for rotation
df_tmp = df_portfolio_features[(df_portfolio_features['Current P/L%'] > 20) ].sort_values(by = 'CumlRnk', ascending=False)
df_tmp[cols].head()

Empty DataFrame
Columns: [Symbol, Today P/L%, Current P/L%, FTT%, OTT%, FTT Amt, Current P/L, Current, FTT, Dev%_PE, RSI_14, Conviction, Spread%, CumlRnk, RRR Ind, CurrAlloc%, Gained%, Criteria, Strategy, Category]
Index: []

In [15]:
# top 5 to monitor for exit
df_tmp = df_portfolio_features[~df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])]
df_tmp = df_tmp[(df_tmp['Current P/L%'] > 0) ].sort_values(by = 'Dev%_PE', ascending=False)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
19,COALINDIA,-1.02,4.82,12.26,17.67,19335.0,7252.0,157712.0,478.51,26.26,53.0,L-LC,10.86,185.0,0.38,1.20,26.60,XY25,ATH,MINING
27,FINCABLES,3.58,19.87,73.44,107.91,129979.0,29342.0,176986.0,1641.55,8.07,78.0,M-SC,6.67,220.0,0.23,1.34,33.15,OX40N,ATH,CABLES
1,ABB,-1.48,9.77,32.61,45.57,93651.0,25565.0,287184.0,7934.00,-29.43,60.0,H-MC,8.95,125.0,0.27,2.18,27.53,AR,NTT,ELECTRICAL

In [16]:
# top 5 to book for rotation from weak conviction
df_tmp = df_portfolio_features[~df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])]
df_tmp = df_tmp[~df_tmp['Criteria'].isin(['XY25','XY24','X40', 'X40N'])].sort_values(by = 'RRR Ind', ascending=False)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
1,ABB,-1.48,9.77,32.61,45.57,93651.0,25565.0,287184.0,7934.00,-29.43,60.0,H-MC,8.95,125.0,0.27,2.18,27.53,AR,NTT,ELECTRICAL
27,FINCABLES,3.58,19.87,73.44,107.91,129979.0,29342.0,176986.0,1641.55,8.07,78.0,M-SC,6.67,220.0,0.23,1.34,33.15,OX40N,ATH,CABLES
40,INDIAMART,-0.85,-9.17,127.58,106.72,142929.0,-11305.0,112031.0,4810.62,-58.98,37.0,H-SC,8.19,140.0,-0.08,0.85,12.07,AR,ATH,MISC
85,ZYDUSLIFE,-1.61,-4.37,41.82,35.63,83818.0,-9149.0,200425.0,1286.17,-16.67,50.0,H-MC,4.90,120.0,-0.11,1.52,11.58,AR,ATH,PHARMA
50,MASFIN,-2.77,-3.44,25.90,21.57,24503.0,-3375.0,94605.0,397.04,-16.89,42.0,H-SC,6.69,167.0,-0.14,0.72,38.06,XR,ATH,FINANCE

In [17]:
# top 5 to accumulate based on lowest RSI_14
df_tmp = df_portfolio_features[df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])].sort_values(by = 'RSI_14', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
8,AWL,-4.66,-41.57,169.01,57.19,322077.0,-135560.0,190567.0,485.00,-66.62,13.0,X-SC,19.47,81.0,-0.42,1.45,0.00,XY24,NTT,FMCG
43,INFY,-0.86,-12.26,53.00,34.24,145504.0,-38352.0,274536.0,1972.00,-31.06,23.0,X-LC,9.38,3.0,-0.26,2.08,1.05,X40,NTT,IT
53,PGHH,-1.15,-15.92,57.01,32.01,102344.0,-34000.0,179520.0,17616.87,-43.10,24.0,X-MC,9.68,57.0,-0.33,1.36,0.00,X40,ATH,FMCG
12,BATAINDIA,-2.47,-50.36,172.38,35.20,110096.0,-64802.0,63868.0,2096.00,-16.25,24.0,X-SC,22.62,91.0,-0.59,0.48,0.00,X40,NTT,FOOTWEAR
9,BAJAJHFL,-2.02,-26.95,112.83,55.47,200526.0,-65562.0,177724.0,181.50,-37.35,26.0,X-MC,17.41,60.0,-0.33,1.35,0.00,X40N,ATH,FINANCE

In [18]:
# top 5 to accumulate based on Spread and CumlRnk
df_tmp = df_portfolio_features[df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])]
df_tmp = df_tmp[(df_tmp['CumlRnk'] < 100)].sort_values(by = 'Spread%', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
37,ICICIGI,-0.32,0.41,18.86,19.34,37894.0,814.0,200923.0,2252.93,-15.42,47.0,X-MC,1.20,66.0,0.02,1.52,16.41,X40,ATH,INSURANCE
78,UNITDSPR,-1.03,0.39,20.30,20.77,47716.0,911.0,235055.0,1644.00,-10.94,44.0,X-MC,1.43,64.0,0.02,1.78,7.52,X40N,NTT,BREWERIES
22,DABUR,-2.10,-0.76,44.80,43.70,110291.0,-1882.0,246186.0,735.00,-9.86,46.0,X-MC,1.56,70.0,-0.02,1.87,14.18,XY24,BTT,FMCG
59,RELIANCE,-2.58,-12.83,43.74,25.30,76625.0,-25781.0,175182.0,1952.00,-15.03,34.0,X-LC,2.17,21.0,-0.34,1.33,17.34,XY25,BTT,REFINERIES
5,ANGELONE,-2.95,-90.73,1240.14,24.20,350836.0,-276960.0,28290.0,3033.00,-86.38,31.0,X-SC,2.43,97.0,-0.79,0.21,18.48,X40N,NTT,FINANCE

In [19]:
# top 5 to accumulate based on lowest Gained%
df_tmp = df_portfolio_features[df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])].sort_values(by = 'Gained%', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
3,ACC,-2.46,-34.73,151.48,64.15,235279.0,-82631.0,155320.0,3906.0,-50.74,27.0,X-SC,9.63,85.0,-0.35,1.18,0.0,XY24,BTT,CEMENT
12,BATAINDIA,-2.47,-50.36,172.38,35.20,110096.0,-64802.0,63868.0,2096.0,-16.25,24.0,X-SC,22.62,91.0,-0.59,0.48,0.0,X40,NTT,FOOTWEAR
9,BAJAJHFL,-2.02,-26.95,112.83,55.47,200526.0,-65562.0,177724.0,181.5,-37.35,26.0,X-MC,17.41,60.0,-0.33,1.35,0.0,X40N,ATH,FINANCE
8,AWL,-4.66,-41.57,169.01,57.19,322077.0,-135560.0,190567.0,485.0,-66.62,13.0,X-SC,19.47,81.0,-0.42,1.45,0.0,XY24,NTT,FMCG
13,BERGEPAINT,-1.91,-20.30,51.99,21.14,94204.0,-46142.0,181197.0,680.0,-22.02,30.0,X-MC,13.97,68.0,-0.49,1.37,0.0,XY24,NTT,PAINTS

In [20]:
# top 5 to accumulate based on lowest CurrAlloc%
df_tmp = df_portfolio_features[df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])].sort_values(by = 'CurrAlloc%', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
5,ANGELONE,-2.95,-90.73,1240.14,24.20,350836.0,-276960.0,28290.0,3033.0,-86.38,31.0,X-SC,2.43,97.0,-0.79,0.21,18.48,X40N,NTT,FINANCE
54,QUESS,-2.01,-35.38,121.06,42.84,50850.0,-23002.0,42004.0,424.0,-57.58,35.0,X-SC,17.17,80.0,-0.45,0.32,1.04,XY24,NTT,MISC
58,RELAXO,-5.19,-57.25,256.31,52.31,159038.0,-83111.0,62049.0,1176.0,-54.51,27.0,X-SC,15.43,92.0,-0.52,0.47,0.00,X40N,NTT,FOOTWEAR
12,BATAINDIA,-2.47,-50.36,172.38,35.20,110096.0,-64802.0,63868.0,2096.0,-16.25,24.0,X-SC,22.62,91.0,-0.59,0.48,0.00,X40,NTT,FOOTWEAR
51,MEDANTA,-0.77,-5.65,31.50,24.08,37731.0,-7170.0,119780.0,1486.0,-6.31,48.0,X-SC,7.96,87.0,-0.19,0.91,9.71,XY24,NTT,HEALTHCARE

In [21]:
# top 5 to accumulate based on CumlRnk
df_tmp = df_portfolio_features.sort_values(by = 'CumlRnk', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
45,ITC,0.41,-17.06,43.54,19.06,122848.0,-58016.0,282150.0,452.00,-54.31,40.0,X-LC,17.12,1.0,-0.47,2.14,2.16,X40,NTT,FMCG
73,TCS,-0.91,-25.09,64.97,23.58,210551.0,-108555.0,324074.0,4311.58,-35.10,29.0,X-LC,9.89,2.0,-0.52,2.46,1.55,X40,ATH,IT
43,INFY,-0.86,-12.26,53.00,34.24,145504.0,-38352.0,274536.0,1972.00,-31.06,23.0,X-LC,9.38,3.0,-0.26,2.08,1.05,X40,NTT,IT
75,TMPV,-3.15,-17.64,61.90,33.33,166086.0,-57486.0,268314.0,600.00,-82.53,48.0,X-LC,3.88,4.0,-0.35,2.03,9.69,XY24,NTT,AUTO
34,HCLTECH,-1.30,-11.03,39.18,23.83,84334.0,-26677.0,215247.0,1908.19,-6.53,28.0,X-LC,6.69,8.0,-0.32,1.63,3.27,X40,ATH,IT

In [22]:
# top 5 for average up
df_tmp = df_portfolio_features[(df_portfolio_features['Dev%_200'] > 5)].sort_values(by = 'CurrAlloc%', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
42,INDUSINDBK,-1.49,-30.42,90.98,32.89,48876.0,-23484.0,53722.0,1800.00,-352.80,57.0,L-MC,12.15,258.0,-0.48,0.41,47.95,XR,NTT,BANKS
67,SONACOMS,-3.23,-10.52,55.44,39.09,50184.0,-10640.0,90519.0,804.02,-29.11,49.0,M-MC,11.24,193.0,-0.21,0.69,28.05,AR,ATH,AUTO
19,COALINDIA,-1.02,4.82,12.26,17.67,19335.0,7252.0,157712.0,478.51,26.26,53.0,L-LC,10.86,185.0,0.38,1.20,26.60,XY25,ATH,MINING
65,SIEMENS,-2.25,-10.22,39.80,25.51,66498.0,-19015.0,167080.0,4671.50,40.24,60.0,H-LC,3.83,51.0,-0.29,1.27,23.04,AR,ATH,ELECTRICAL
27,FINCABLES,3.58,19.87,73.44,107.91,129979.0,29342.0,176986.0,1641.55,8.07,78.0,M-SC,6.67,220.0,0.23,1.34,33.15,OX40N,ATH,CABLES

In [23]:
# top 5 RSP
df_tmp = df_portfolio_features.sort_values(by = 'RSP', ascending=False)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
27,FINCABLES,3.58,19.87,73.44,107.91,129979.0,29342.0,176986.0,1641.55,8.07,78.0,M-SC,6.67,220.0,0.23,1.34,33.15,OX40N,ATH,CABLES
26,EASEMYTRIP,-7.31,-55.91,230.41,45.70,179641.0,-98849.0,77966.0,26.40,-19.04,51.0,M-SC,18.10,204.0,-0.55,0.59,28.46,XY24,NTT,TRAVEL
11,BANDHANBNK,-2.37,-14.54,125.15,92.42,297937.0,-40495.0,238064.0,400.00,104.02,64.0,H-SC,8.59,174.0,-0.14,1.81,31.14,XY24,NTT,BANKS
83,WHIRLPOOL,-0.81,-26.72,148.26,81.92,124716.0,-30678.0,84120.0,2270.00,-57.12,56.0,M-SC,25.93,210.0,-0.25,0.64,18.16,XR,NTT,DURABLES
82,VOLTAS,-3.98,17.27,23.81,45.20,53540.0,33123.0,224865.0,1856.00,34.28,52.0,X-MC,9.63,79.0,0.62,1.71,25.25,XY25,NTT,AC

In [24]:
# Top N allocation
df_tmp = df_portfolio_features.sort_values(by = 'CurrAlloc%', ascending=False)
top_n_values = [10, 25, 50]

sum_df = pd.DataFrame({
    'Top_N': top_n_values,
    'Sum_Alloc%': [df_tmp['CurrAlloc%'].head(n).sum() for n in top_n_values]
})

sum_df

   Top_N  Sum_Alloc%
0     10       20.83
1     25       45.91
2     50       78.00

In [25]:
# market-cap-wise allocation
df_tmp = df_portfolio_features[cols]
df_tmp.groupby(df_tmp['Conviction'].str[-2:])['CurrAlloc%'].sum().sort_values(ascending=False)

Conviction
SC    43.75
MC    30.89
LC    25.37
Name: CurrAlloc%, dtype: float64

In [26]:
# criteria-wise allocation
df_portfolio_features.groupby('Criteria')['CurrAlloc%'].sum().sort_values(ascending=False)

Criteria
XY24     27.40
X40      24.41
X40N     12.91
AR        9.33
XY25      9.09
XR        8.65
OX40N     7.38
SR        0.84
Name: CurrAlloc%, dtype: float64

In [27]:
# conviction-wise allocation
df_portfolio_features.groupby('Conviction')['CurrAlloc%'].sum().sort_values(ascending=False)

Conviction
X-MC    23.27
H-SC    22.60
X-LC    21.85
M-SC    11.02
X-SC     9.43
H-MC     5.11
M-MC     2.10
H-LC     1.27
L-LC     1.20
M-LC     1.05
L-SC     0.70
L-MC     0.41
Name: CurrAlloc%, dtype: float64

In [28]:
# sector-wise stats
df_tmp = df_portfolio_features.groupby('Category')[['CurrAlloc%', 'Current', 'Current P/L', 'FTT Amt']].sum().sort_values(by=['Current', 'Current P/L'], ascending=False)
df_tmp['Current P/L%'] = round(df_tmp['Current P/L'] * 100 / df_tmp['Current'], 2)
df_tmp['FTT%'] = round(df_tmp['FTT Amt'] * 100 / df_tmp['Current'], 2)
cols = ['CurrAlloc%', 'Current P/L%', 'FTT%']
df_tmp[cols].sort_values(by=['CurrAlloc%'], ascending=False)

               CurrAlloc%  Current P/L%    FTT%
Category
FMCG                16.00        -17.00   56.57
IT                  11.64        -42.62  114.09
FINANCE             11.17        -41.78   97.57
MISC                 6.93        -42.09  100.22
ELECTRICAL           6.53         -9.15   48.98
PAINTS               5.11        -36.84   57.17
INSURANCE            5.04         -2.00   36.91
PHARMA               4.28         -4.23   37.04
AUTO                 3.95        -19.75   65.40
BANKS                3.19        -27.52  104.78
AC                   2.29         -6.01   34.75
FOOTWEAR             2.03        -64.66  130.68
TRAVEL               2.00        -69.80  154.82
DURABLES             1.93        -52.25   89.29
BREWERIES            1.78          0.39   20.30
HEALTHCARE           1.70        -37.84   71.85
REALTY               1.44        -16.70   35.88
CERAMICS             1.42        -63.39  113.02
APPARELS             1.42        -26.73   64.94
CABLES               1.34         16.58   73.44
REFINERIES           1.33        -14.72   43.74
JEWELLERY            1.22        -98.60  167.59
MINING               1.20          4.60   12.26
CEMENT               1.18        -53.20  151.48
ENGINEERING          1.16        -58.22  130.58
CHEMICALS            1.05        -91.29  247.35
ENTERTAINMENT        0.80        -83.18  192.43
TEXTILES             0.46        -52.82   96.40
HOTELS               0.42       -103.86  175.77

In [29]:
# money to be made criteria-wise
df_portfolio_features.groupby('Criteria')['FTT Amt'].agg(['sum', 'count']).sort_values(by='sum', ascending=False)

                sum  count
Criteria
XY24      3514930.0     21
X40       1503212.0     15
X40N      1417257.0     10
XR        1351509.0     12
AR        1341703.0     10
OX40N      817854.0     10
XY25       419711.0      6
SR         308006.0      2

In [30]:
# money to be made conviction-wise
df_portfolio_features.groupby('Conviction')['FTT Amt'].agg(['sum', 'count']).sort_values(by='sum', ascending=False)

                  sum  count
Conviction
H-SC        3811610.0     24
X-SC        1561108.0     10
M-SC        1463633.0     14
X-MC        1446207.0     15
X-LC        1389852.0     12
H-MC         405681.0      3
L-SC         198436.0      2
M-LC         153890.0      1
M-MC         109056.0      2
H-LC          66498.0      1
L-MC          48876.0      1
L-LC          19335.0      1

In [31]:
# money to be made criteria and conviction-wise
df_portfolio_features.groupby(['Conviction', 'Criteria'])['FTT Amt'].agg(['sum', 'count']).sort_values(by='sum', ascending=False)

                           sum  count
Conviction Criteria
H-SC       XY24      1291199.0      6
           AR         971152.0      5
           XR         867931.0      7
M-SC       XY24       860325.0      6
X-LC       X40        728562.0      6
X-SC       X40N       720588.0      4
           XY24       645937.0      4
X-MC       X40        580067.0      7
           X40N       456916.0      4
H-SC       OX40N      373322.0      4
M-SC       OX40N      343998.0      5
H-SC       SR         308006.0      2
X-LC       XY24       284762.0      2
           X40N       239753.0      2
H-MC       XY24       228212.0      1
X-MC       XY25       204729.0      2
           XY24       204495.0      2
X-SC       X40        194583.0      2
M-SC       XR         182910.0      2
H-MC       AR         177469.0      2
M-LC       XR         153890.0      1
X-LC       XY25       136775.0      2
L-SC       OX40N      100534.0      1
           XR          97902.0      1
M-SC       AR          76400.0      1
H-LC       AR          66498.0      1
M-MC       XY25        58872.0      1
           AR          50184.0      1
L-MC       XR          48876.0      1
L-LC       XY25        19335.0      1

In [32]:
# notebook execution time

end_time = time.time()
execution_time = round(end_time - start_time, 0)
print(f"Notebook execution time: {execution_time} seconds")

Notebook execution time: 27.0 seconds