<a href="https://colab.research.google.com/github/ankit-rathi/Quantvesting_v2/blob/main/myStocks_Portfolio_Analysis.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
'''
!pip install pandas==2.2.2 -qq
!pip install pyxirr -qq
!pip install ta -qq
!pip install yfinance==0.2.59 -qq
'''

'\n!pip install pandas==2.2.2 -qq\n!pip install pyxirr -qq\n!pip install ta -qq\n!pip install yfinance==0.2.59 -qq\n'

In [2]:
# import libraries

import numpy as np
import pandas as pd
import datetime
import warnings
warnings.filterwarnings('ignore')
import yfinance as yfin
import ta
import matplotlib.pyplot as plt
import requests

In [3]:
# notebook start time
import time
import datetime
import pytz

start_time = time.time()

# function to print date timestamp
def print_date_time():
  tz_NY = pytz.timezone('Asia/Kolkata')
  datetime_NY = datetime.datetime.now(tz_NY)
  print("Run date time (IST):", datetime_NY.strftime("%Y-%m-%d %H:%M:%S"))

In [4]:
# function to get booked and reserved amount
def get_amt():
  # fetch the JSON data from the URL
  url = "https://raw.githubusercontent.com/ankit-rathi/Tradevesting_v1/main/data/myPortfolioAmts.json"
  response = requests.get(url)
  pf_amts = response.json()  # parse the JSON data

  # extract values from the JSON
  py_booked_amt_dm = pf_amts["py_booked_amt_dm"]
  py_booked_amt_sv = pf_amts["py_booked_amt_sv"]
  cy_booked_amt_dm = pf_amts["cy_booked_amt_dm"]
  cy_booked_amt_sv = pf_amts["cy_booked_amt_sv"]
  reserve_amt_dm = pf_amts["reserve_amt_dm"]
  reserve_amt_sv = pf_amts["reserve_amt_sv"]

  # perform calculations
  py_booked_amt = py_booked_amt_dm + py_booked_amt_sv
  cy_booked_amt = cy_booked_amt_dm + cy_booked_amt_sv
  reserve_amt = reserve_amt_dm + reserve_amt_sv
  total_booked_amt = py_booked_amt + cy_booked_amt

  return total_booked_amt, reserve_amt, cy_booked_amt, py_booked_amt

gen_output = 0

In [5]:
# function to format the amount
def format_amt(number):
    abs_number = abs(number)

    if abs_number >= 1_00_00_000:  # Crores
        formatted_amt = f"{number / 1_00_00_000:.2f} C"
    elif abs_number >= 1_00_000:  # Lakhs
        formatted_amt = f"{number / 1_00_000:.2f} L"
    elif abs_number >= 1_000:  # Thousands
        formatted_amt = f"{number / 1_000:.2f} K"
    else:
        formatted_amt = f"{number:.2f}"

    return formatted_amt

# function to set start and end date
def get_start_end_date():
  start_date = (datetime.date.today() + datetime.timedelta(days=-365)).strftime('%Y-%m-%d')
  end_date = (datetime.date.today() + datetime.timedelta(days=1)).strftime('%Y-%m-%d')
  return start_date, end_date

# function to fetch my portfolio csv
def get_mypfs_df():
  mypfs_df = pd.read_csv('https://raw.githubusercontent.com/ankit-rathi/Tradevesting_v1/main/data/myPortfolioStocks.csv')
  return mypfs_df

# function to fetch my prospects csv
def get_mypps_df():
  mypps_df = pd.read_csv('https://raw.githubusercontent.com/ankit-rathi/Tradevesting_v1/main/data/myProspectsScrips.csv')
  return mypps_df

# function to fetch screener data
def get_myscreen_df():
  myscreen_df = pd.read_csv('https://raw.githubusercontent.com/ankit-rathi/Tradevesting_v1/main/data/myScreenerDB.csv')
  return myscreen_df

# function to fetch momentum data
def get_myinvmt_df():
  myinvmt_df = pd.read_csv('https://raw.githubusercontent.com/ankit-rathi/Tradevesting_v1/main/data/myInvestments.csv')
  return myinvmt_df

# function to get the stock ids
def get_stock_ids(df_pf):
  stock_n100 = df_pf['Symbol'].unique()

  exclude = ['CADILAHC','MMTC', 'MASFIN']

  stock_ids = df_pf[~df_pf['Symbol'].isin(exclude) ]['Symbol'].unique()

  #mypf = mypf[mypf.Forecast.notnull()]
  #stock_ids = mypf['Symbol'].unique()

  #stock_ids.sort()
  return stock_ids

# get features from screener data
def get_screener_features():
  myscreen_df = get_myscreen_df()
  cols = ['Symbol', 'EPS', 'MedPE', 'ROCE%', 'ROE%', 'CapType']
  return myscreen_df[cols]

# get relative strength
def get_relative_strength(stock_list):

    # Dictionary to store stock tickers and their corresponding percentage price change
    stock_changes = {}

    # Loop through each stock and fetch its price data
    for stock in stock_list:
        try:
            # Download the stock data for the given date range
            stock_data = yfin.Ticker(stock + '.NS').history(period='1mo', interval='1d')[map(str.title, ['open', 'close', 'low', 'high', 'volume'])]

            # Calculate the percentage change for the stock
            if len(stock_data) > 0:
                start_price = stock_data['Close'].iloc[0]
                end_price = stock_data['Close'].iloc[-1]
                percent_change = round(((end_price - start_price) / start_price) * 100, 2)
                stock_changes[stock] = percent_change
            else:
                stock_changes[stock] = np.nan  # If no data is available, set to NaN

        except Exception as e:
            print(f"Error fetching data for {stock}: {e}")
            stock_changes[stock] = np.nan

    # Create a DataFrame with stock tickers and their percentage changes
    df = pd.DataFrame(list(stock_changes.items()), columns=['Symbol', 'Percent_Change'])

    # Drop any stocks with missing data (NaN values)
    df = df.dropna()

    # Calculate the percentile rank based on percentage change
    df['RSP'] = round(df['Percent_Change'].rank(pct=True) * 100, 2)
    cols = ['Symbol', 'RSP']
    df = df[cols]
    # Sort by percentile rank (optional)
    df = df.sort_values(by='RSP', ascending=False).reset_index(drop=True)

    return df

In [6]:
# function to get stock technicals
def stock_prec_dev(stock_symbol):
    #stock_symbol = 'ULTRACEMCO.NS'
    short_window = 20
    mid_window = 50
    long_window = 200
    moving_avg = 'SMA'

    start = datetime.datetime(*map(int, start_date.split('-')))
    end = datetime.datetime(*map(int, end_date.split('-')))

    stock_df = yfin.Ticker(stock_symbol + '.NS').history(period='max', interval='1d')[map(str.title, ['open', 'close', 'low', 'high', 'volume'])]

    stock_df['Max'] = round(max(stock_df['Close']),2)
    stock_df = stock_df[(stock_df.index <= end_date) & (stock_df.index >= start_date)]
    stock_df['200_SMA'] = round(stock_df['Close'].rolling(window = 200, min_periods = 1).mean(),0)
    stock_df['Dev%_200'] = round((stock_df['Close'] - stock_df['200_SMA'])*100/stock_df['200_SMA'],2)
    stock_df.dropna(axis = 0, inplace = True) # remove any null rows

    stock_df['20_SMA'] = stock_df['Close'].rolling(window=20).mean()
    stock_df['50_SMA'] = stock_df['Close'].rolling(window=50).mean()
    stock_df['Symbol'] = stock_symbol

    stock_df['Close'] = round(stock_df['Close'],2)
    stock_df['Min'] = round(min(stock_df['Close']),2)
    stock_df['RSI_14'] = ta.momentum.RSIIndicator(close=stock_df['Close'], window=14).rsi()
    stock_df['RSI_14'] = round(stock_df['RSI_14'],0)
    stock_df['Prev_Close'] = stock_df['Close'].shift(1)
    stock_df.drop(['Open', 'Low', 'High', 'Volume'], axis=1, inplace=True)
    stock_df = stock_df.tail(1)

    max_SMA = max(stock_df['20_SMA'].item(), stock_df['50_SMA'].item(), stock_df['200_SMA'].item())
    min_SMA = min(stock_df['20_SMA'].item(), stock_df['50_SMA'].item(), stock_df['200_SMA'].item())
    ABS_Spread = max_SMA - min_SMA
    stock_df['Spread%'] = round((ABS_Spread / stock_df['200_SMA'].item()) * 100,2)

    return stock_df

# function to compute stock attributes
def get_common_features(stock_ids, df_mypf):

  df_prec_dev = pd.DataFrame()
  df_tmp = get_screener_features()
  df_rs = get_relative_strength(stock_ids)

  for stock_id in stock_ids:
      tmp = stock_prec_dev(stock_id)
      tmp = tmp.reset_index()
      df_prec_dev = pd.concat([df_prec_dev, tmp], ignore_index = True)
  df_prec_dev = pd.merge(df_prec_dev, df_mypf, on= 'Symbol')
  df_prec_dev = pd.merge(df_prec_dev, df_tmp, on= 'Symbol', how='left')
  df_prec_dev = pd.merge(df_prec_dev, df_rs, on= 'Symbol', how='left')
  #print(df_prec_dev.columns)
  df_prec_dev['Curr_PE'] = round(df_prec_dev['Close']/df_prec_dev['EPS'],1)
  df_prec_dev['Dev%_PE'] = round((df_prec_dev['Curr_PE'] - df_prec_dev['MedPE'])*100/df_prec_dev['MedPE'],2)
  df_prec_dev['Conviction'] = df_prec_dev['Conviction'] + '-' + df_prec_dev['CapType']
  return df_prec_dev

# function to arrange stock features
def arrange_features(df_stocks, common_cols, diff_cols):
  df_stocks_common = df_stocks[common_cols].drop_duplicates()
  df_stocks_diff = df_stocks[diff_cols]
  df_stocks_diff['Investment'] = df_stocks_diff['AvgCost'] * df_stocks_diff['Shares']
  df_stocks_diff = df_stocks_diff.groupby(['Symbol'])[['Shares', 'Investment']].aggregate(['sum']).reset_index()
  df_stocks_diff.columns = ['Symbol', 'Shares', 'Investment']
  df_stocks_diff['AvgCost'] = round(df_stocks_diff['Investment']/df_stocks_diff['Shares'],2)
  df_stocks = pd.merge(df_stocks_diff, df_stocks_common, on='Symbol')
  return df_stocks

# plot fact distribution across dimension
def plot_pie_chart(df, dimension, fact):
  # grouping the data by category and calculating the sum of fact for each type
  grouped_data = df.groupby(dimension)[fact].sum()

  # sorting the grouped data in descending order
  grouped_data = grouped_data.sort_values(ascending=False)

  # creating a pie chart
  grouped_data.plot.pie(autopct='%1.1f%%', startangle=90, figsize=(6, 6))

  # adding a title and displaying the plot
  plt.title(f'{dimension} {fact} Distribution')
  plt.ylabel('')  # To hide the y-label
  plt.show()

In [7]:
# function to get portfolio features

def get_portfolio_features(df_common_features):

  print_date_time()
  print('-------------------')

  #df_common_features["Target"] = df_common_features["Target"].fillna(df_common_features["Max"])
  df_common_features['NTT'] = np.where(df_common_features['Strategy']== 'NTT', df_common_features["Target"], df_common_features['Max'])
  df_common_features['LTT'] = np.where(df_common_features['Strategy']== 'BTT', df_common_features["Target"], df_common_features['Max'])
  df_common_features['BOL'] = df_common_features['Min']

  tmp_df = df_common_features[df_common_features['Symbol'].isin(mypf_df[mypf_df['InPortfolio'] != 'NA'].Symbol.values)]
  print('qualified stocks: '+str(len(tmp_df['Symbol'].unique())))
  tmp_df1 = tmp_df[tmp_df['LatestQtr'] == 1]
  print('with latest results: '+str(len(tmp_df1['Symbol'].unique())))
  tmp_df1 = tmp_df1[tmp_df1['StarStock'] == 1]
  print('still star stocks: '+str(len(tmp_df1['Symbol'].unique())))
  tmp_df['Investment'] = tmp_df['AvgCost'] * tmp_df['Shares']
  tmp_df['Current'] = round(tmp_df['Close'] * tmp_df['Shares'],0)
  tmp_df['Previous'] = tmp_df['Prev_Close'] * tmp_df['Shares']
  tmp_df['EstimatedST'] = tmp_df['NTT'] * tmp_df['Shares']
  tmp_df['EstimatedLT'] = tmp_df['LTT'] * tmp_df['Shares']
  tmp_df['Current P/L'] = round((tmp_df['Current'] - tmp_df['Investment']),0)
  tmp_df['Today P/L%'] = round((tmp_df['Current'] - tmp_df['Previous'])*100/tmp_df['Previous'],2)
  tmp_df['Current P/L%'] = round((tmp_df['Current'] - tmp_df['Investment'])*100/tmp_df['Investment'],2)
  tmp_df['EstimatedST P/L%'] = round((tmp_df['EstimatedST'] - tmp_df['Investment'])*100/tmp_df['Investment'],2)
  tmp_df['EstimatedLT P/L%'] = round((tmp_df['EstimatedLT'] - tmp_df['Investment'])*100/tmp_df['Investment'],2)
  tmp_df['NTT%'] = round((tmp_df['NTT'] - tmp_df['Close'])*100/tmp_df['Close'],2)
  tmp_df['LTT%'] = round((tmp_df['LTT'] - tmp_df['Close'])*100/tmp_df['Close'],2)
  tmp_df['Gained%'] = round((tmp_df['Close'] - tmp_df['BOL'])*100/tmp_df['BOL'],2)
  investment = round(sum(tmp_df['AvgCost']*tmp_df['Shares']),0)
  current = round(sum(tmp_df['Close']*tmp_df['Shares']),0)
  tmp_df['InitAlloc%'] = round(tmp_df['Investment']*100/investment,2)
  tmp_df['CurrAlloc%'] = round(tmp_df['Current']*100/current,2)
  tmp_df['FTT'] = tmp_df['LTT']
  tmp_df.loc[tmp_df['Strategy'] == 'NTT', 'FTT'] = tmp_df['NTT']
  tmp_df['FTT%'] = tmp_df['LTT%']
  tmp_df.loc[tmp_df['Strategy'] == 'NTT', 'FTT%'] = tmp_df['NTT%']
  tmp_df['FTT Amt'] = round(tmp_df['FTT%'] * tmp_df['Current']/100,0)
  tmp_df['OTT%'] = round((tmp_df['FTT'] - tmp_df['AvgCost'])*100/tmp_df['AvgCost'],2)
  tmp_df['RRR Ind'] = round(tmp_df['Current P/L']/tmp_df['FTT Amt'],2)
  tmp_df['Risk Ind'] = round(tmp_df['Current P/L%']*tmp_df['CurrAlloc%'],0)

  return tmp_df

# function to print portfolio features
def print_portfolio_stats(df_portfolio_features, myinvmt_df):
  from pyxirr import xirr

  total_booked_amt, reserve_amt, cy_booked_amt, py_booked_amt = get_amt()

  dates = myinvmt_df['Date'].values
  dates = np.append(dates, datetime.date.today().strftime('%d-%b-%y'))
  investment = myinvmt_df['Investment'].values
  dates= pd.to_datetime(dates)

  current = round(sum(df_portfolio_features['Close']*df_portfolio_features['Shares']),0) + reserve_amt
  investment_xirr = np.append(investment, current)
  cagr = round(xirr(pd.DataFrame({"dates": dates, "amounts": investment_xirr}))*100,2)

  investment = -sum(investment)
  invested = round(sum(df_portfolio_features['AvgCost']*df_portfolio_features['Shares']),0) + reserve_amt
  previous = round(sum(df_portfolio_features['Prev_Close']*df_portfolio_features['Shares']),0) + reserve_amt
  cy_invested = investment + py_booked_amt

  today_pnl_amount = current-previous
  today_pnl_percentage = round((current-previous)*100/previous,2)

  curr_pnl_amount = current-invested
  curr_pnl_percentage = round((curr_pnl_amount)*100/(cy_invested),2)

  cy_pnl_amount = cy_booked_amt + curr_pnl_amount
  cy_pnl_percentage = round((cy_pnl_amount)*100/cy_invested,2)

  overall_pnl_amount = total_booked_amt + curr_pnl_amount
  overall_pnl_percentage = round((overall_pnl_amount)*100/investment,2)

  estimate_st = round(sum(df_portfolio_features['FTT']*df_portfolio_features['Shares']),0)  + reserve_amt
  est_st_pnl_amount = estimate_st-current
  est_st_pnl_percentage = round((est_st_pnl_amount)*100/current,2)

  estimate_lt = round(sum(df_portfolio_features['LTT']*df_portfolio_features['Shares']),0)  + reserve_amt
  est_lt_pnl_amount = estimate_lt-current
  est_lt_pnl_percentage = round((est_lt_pnl_amount)*100/current,2)

  total_profit = round(sum(df_portfolio_features[df_portfolio_features['Current P/L%'] > 0]['Current']) - sum(df_portfolio_features[df_portfolio_features['Current P/L%'] > 0]['Investment']),0)
  total_loss = round(sum(df_portfolio_features[df_portfolio_features['Current P/L%'] < 0]['Current']) - sum(df_portfolio_features[df_portfolio_features['Current P/L%'] < 0]['Investment']),0)

  cy_booked_percentage = round((cy_booked_amt)*100/current,2)
  py_booked_percentage = round((py_booked_amt)*100/investment,2)
  total_booked_percentage = round((total_booked_amt)*100/investment,2)

  print('-------------------')
  print('Initial Investment: ', format_amt(investment))
  print('CY Investment: ', format_amt(cy_invested))
  print('Reserve: ', format_amt(reserve_amt))
  print('Current: ',  format_amt(current))
  print('-------------------')
  print('Today PnL: '+ '{} ({}%)'.format(format_amt(today_pnl_amount), today_pnl_percentage))
  print('Current PnL: '+ '{} ({}%)'.format(format_amt(curr_pnl_amount), curr_pnl_percentage))
  print('CY Booked + Current PnL: '+ '{} ({}%)'.format(format_amt(cy_pnl_amount), cy_pnl_percentage))
  print('-------------------')
  print('Total profit: ', format_amt(total_profit))
  print('Total loss: ', format_amt(total_loss))
  print('-------------------')
  print('Total Booked + Current PnL: '+ '{} ({}%)'.format(format_amt(overall_pnl_amount), overall_pnl_percentage))
  print('Total Booked PnL: '+ '{} ({}%)'.format(format_amt(total_booked_amt), total_booked_percentage))
  print('Curr Year Booked PnL: '+ '{} ({}%)'.format(format_amt(cy_booked_amt), cy_booked_percentage))
  print('Prev Year Booked PnL: '+ '{} ({}%)'.format(format_amt(py_booked_amt), py_booked_percentage))
  print('===================')
  print('Est FTT: ',  format_amt(estimate_st))
  print('Est FTT PnL: '+ '{} ({}%)'.format(format_amt(est_st_pnl_amount), est_st_pnl_percentage))

  print('===================')
  print('Deployed: ', format_amt(investment))

  print('Current: ', format_amt(current))

  print('CAGR/XIRR %: '+'{}%'.format(cagr))

In [8]:
# get start and end date
start_date, end_date = get_start_end_date()

# get portfolio and prospects data
mypfs_df = get_mypfs_df()
mypps_df = get_mypps_df()
myinvmt_df = get_myinvmt_df()

# merge above datasets
mypf_df = pd.merge(mypfs_df, mypps_df, on="Symbol")

# seggregate dm and sv portfolio
dm_pf = mypf_df[mypf_df['InPortfolio'] == 'DM']
sv_pf = mypf_df[mypf_df['InPortfolio'] == 'SV']

# build portfolio stock dataframe
dm_stocks = get_stock_ids(dm_pf)
sv_stocks = get_stock_ids(sv_pf)
df_stocks = pd.concat([dm_pf,sv_pf], ignore_index = True)

# arrange common and diff stock features
common_cols = ['Symbol', 'Target', 'Criteria', 'Strategy', 'CumlRnk', 'LatestQtr', 'StarStock', 'Conviction', 'Category', 'InFolio', 'XIRR', 'MBQ']
diff_cols = ['Symbol', 'AvgCost', 'Shares']
df_stocks = arrange_features(df_stocks, common_cols, diff_cols)

# get common features
stock_ids = df_stocks['Symbol'].values
df_common_features = get_common_features(stock_ids, df_stocks)

df_common_features.reset_index(drop=True, inplace=True)
df_common_features.drop(['Date'], axis=1, inplace=True)
# get and print portfolio features
df_portfolio_features = get_portfolio_features(df_common_features)

print_portfolio_stats(df_portfolio_features, myinvmt_df)

df = df_portfolio_features
#plot_pie_chart(df, 'CapType', 'Current')
list_ox40n = list(df[df['MBQ'].str.contains('OX40N', na=False)]['Symbol'].values)

Run date time (IST): 2026-07-21 13:25:15
-------------------
qualified stocks: 92
with latest results: 31
still star stocks: 20
-------------------
Initial Investment:  1.40 C
CY Investment:  1.82 C
Reserve:  1.49 K
Current:  1.53 C
-------------------
Today PnL: -3.65 K (-0.02%)
Current PnL: -30.46 L (-16.7%)
CY Booked + Current PnL: -28.38 L (-15.56%)
-------------------
Total profit:  4.64 L
Total loss:  -35.10 L
-------------------
Total Booked + Current PnL: 14.49 L (10.38%)
Total Booked PnL: 44.95 L (32.22%)
Curr Year Booked PnL: 2.08 L (1.36%)
Prev Year Booked PnL: 42.87 L (30.73%)
===================
Est FTT:  2.55 C
Est FTT PnL: 1.02 C (66.89%)
===================
Deployed:  1.40 C
Current:  1.53 C
CAGR/XIRR %: 4.07%

In [9]:
# top 5 near their targets
cols = ['Symbol', 'Today P/L%', 'Current P/L%', 'FTT%', 'OTT%', 'FTT Amt', 'Current P/L', 'Current', 'FTT', 'Dev%_PE', 'RSI_14','Conviction', 'Spread%',  'CumlRnk', 'RRR Ind', 'CurrAlloc%', 'Gained%', 'Criteria', 'Strategy', 'Category']
df_tmp = df_portfolio_features[~df_portfolio_features['Symbol'].isin(['ENRIN','BLUSPRING','DIGITIDE'])]
df_tmp = df_tmp.sort_values(by = 'FTT Amt', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
49,JSWINFRA,0.99,17.64,-1.03,16.43,-2687.0,39116.0,260890.0,342.00,0.79,65.0,X-MC,18.60,61.0,-14.56,1.71,47.92,X40N,NTT,REALTY
59,PIDILITIND,0.70,11.74,5.93,18.37,9350.0,16560.0,157670.0,1670.26,-21.72,53.0,X-LC,8.12,5.0,1.77,1.03,23.80,X40,ATH,CHEMICALS
73,SONACOMS,2.14,26.26,9.84,38.69,12568.0,26565.0,127724.0,801.69,0.05,84.0,M-MC,24.25,193.0,2.11,0.84,81.21,AR,ATH,AUTO
83,TTKPRESTIG,-2.51,-14.78,17.45,0.09,14987.0,-14893.0,85884.0,770.00,99.36,64.0,M-SC,9.43,250.0,-0.99,0.56,52.93,OX40N,NTT,DURABLES
56,MEDANTA,1.91,14.80,10.73,27.12,21743.0,26125.0,202642.0,1486.00,11.29,60.0,X-SC,11.02,87.0,1.20,1.33,39.63,XY24,NTT,HEALTHCARE

In [10]:
# top 5 today
df_tmp = df_portfolio_features.sort_values(by = 'Today P/L%', ascending=False)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
62,RAJOOENG,6.81,-47.70,166.93,39.61,89491.0,-48890.0,53610.0,143.1,-64.67,57.0,H-SC,20.03,136.0,-0.55,0.35,14.85,AR,ATH,MISC
75,SURYODAY,4.82,7.34,14.62,23.03,28102.0,13148.0,192219.0,216.0,110.53,62.0,H-SC,22.39,166.0,0.47,1.26,63.16,XR,NTT,BANKS
61,RAJESHEXPO,4.69,-82.61,475.56,0.07,113421.0,-113327.0,23850.0,518.0,773.74,45.0,L-SC,35.10,268.0,-1.00,0.16,17.79,OX40N,NTT,JEWELLERY
44,INDUSINDBK,3.31,-21.66,69.63,32.89,42116.0,-16720.0,60486.0,1800.0,-385.01,73.0,L-MC,11.69,258.0,-0.40,0.40,49.12,XR,NTT,BANKS
0,5PAISA,2.72,-28.50,57.90,12.90,90457.0,-62267.0,156229.0,593.0,130.77,57.0,H-SC,12.32,170.0,-0.69,1.02,50.76,OX40N,NTT,FINANCE

In [11]:
# bottom 5 today
df_tmp = df_portfolio_features.sort_values(by = 'Today P/L%', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
64,RELAXO,-4.95,-46.20,183.10,52.31,142992.0,-67065.0,78095.0,1176.00,-42.70,59.0,X-SC,12.57,92.0,-0.47,0.51,74.61,X40N,NTT,FOOTWEAR
77,TANLA,-3.00,-35.92,239.03,117.25,414722.0,-97259.0,173502.0,1922.32,-35.11,58.0,H-SC,3.34,147.0,-0.23,1.14,51.90,AR,ATH,IT
28,GODREJCP,-2.85,-6.80,41.06,31.47,56871.0,-10108.0,138506.0,1469.04,-1.98,47.0,X-LC,6.52,32.0,-0.18,0.91,6.27,X40N,ATH,FMCG
22,DIXON,-2.83,3.28,33.55,37.92,90365.0,8546.0,269344.0,18931.72,-56.06,66.0,X-MC,6.92,54.0,0.09,1.76,46.55,X40N,ATH,IT
54,MARUTI,-2.74,-0.10,28.80,28.68,42530.0,-142.0,147675.0,17292.00,-17.78,44.0,X-LC,8.30,33.0,-0.00,0.97,9.97,XR,ATH,AUTO

In [12]:
# top 5 to exit based on CumlRnk
df_tmp = df_portfolio_features[~df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])]
df_tmp = df_tmp[(df_tmp['Current P/L%'] > -1) & (df_tmp['Current P/L%'] < 1)].sort_values(by = 'CumlRnk', ascending=False)
df_tmp[cols].head()

Empty DataFrame
Columns: [Symbol, Today P/L%, Current P/L%, FTT%, OTT%, FTT Amt, Current P/L, Current, FTT, Dev%_PE, RSI_14, Conviction, Spread%, CumlRnk, RRR Ind, CurrAlloc%, Gained%, Criteria, Strategy, Category]
Index: []

In [13]:
# OX40N stocks to exit
df_tmp = df_portfolio_features[(df_portfolio_features['Symbol'].isin(list_ox40n))].sort_values(by = 'Current P/L%', ascending=False)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
25,FINCABLES,-0.99,27.57,62.98,107.91,118620.0,40702.0,188346.0,1641.55,14.66,39.0,M-SC,22.83,220.0,0.34,1.23,41.70,OX40N,ATH,CABLES
72,SIS,1.79,1.36,19.63,21.26,22092.0,1512.0,112544.0,528.00,2688.60,61.0,H-SC,24.91,168.0,0.07,0.74,67.34,OX40N,NTT,MISC
83,TTKPRESTIG,-2.51,-14.78,17.45,0.09,14987.0,-14893.0,85884.0,770.00,99.36,64.0,M-SC,9.43,250.0,-0.99,0.56,52.93,OX40N,NTT,DURABLES
16,CERA,1.00,-18.34,51.72,23.89,74288.0,-32268.0,143635.0,9475.00,-21.24,55.0,H-SC,15.07,153.0,-0.43,0.94,39.63,OX40N,NTT,CERAMICS
43,INDIGOPNTS,2.20,-22.68,29.35,0.02,39615.0,-39585.0,134974.0,1408.00,105.92,61.0,M-SC,3.66,222.0,-1.00,0.88,53.14,OX40N,NTT,PAINTS

In [14]:
# top 5 to book for rotation
df_tmp = df_portfolio_features[(df_portfolio_features['Current P/L%'] > 20) ].sort_values(by = 'CumlRnk', ascending=False)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
25,FINCABLES,-0.99,27.57,62.98,107.91,118620.0,40702.0,188346.0,1641.55,14.66,39.0,M-SC,22.83,220.0,0.34,1.23,41.70,OX40N,ATH,CABLES
73,SONACOMS,2.14,26.26,9.84,38.69,12568.0,26565.0,127724.0,801.69,0.05,84.0,M-MC,24.25,193.0,2.11,0.84,81.21,AR,ATH,AUTO
68,SATIN,-0.24,41.56,7.26,51.83,28395.0,114825.0,391109.0,274.00,27.46,55.0,H-SC,44.39,159.0,4.04,2.56,90.53,XY24,NTT,FINANCE
91,ZYDUSLIFE,-0.74,20.27,12.77,35.63,32187.0,42476.0,252050.0,1286.17,4.50,57.0,H-MC,17.13,120.0,1.32,1.65,32.52,AR,ATH,PHARMA
60,QUESS,1.61,22.92,41.47,73.90,54437.0,24476.0,131269.0,424.00,-33.88,71.0,X-SC,31.88,80.0,0.45,0.86,78.95,XY24,NTT,MISC

In [15]:
# top 5 to monitor for exit
df_tmp = df_portfolio_features[~df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])]
df_tmp = df_tmp[(df_tmp['Current P/L%'] > 0) ].sort_values(by = 'Dev%_PE', ascending=False)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
72,SIS,1.79,1.36,19.63,21.26,22092.0,1512.0,112544.0,528.0,2688.60,61.0,H-SC,24.91,168.0,0.07,0.74,67.34,OX40N,NTT,MISC
9,BANDHANBNK,-1.52,1.02,90.47,92.42,254594.0,2854.0,281413.0,400.0,141.38,53.0,H-SC,20.15,174.0,0.01,1.84,55.02,XY24,NTT,BANKS
75,SURYODAY,4.82,7.34,14.62,23.03,28102.0,13148.0,192219.0,216.0,110.53,62.0,H-SC,22.39,166.0,0.47,1.26,63.16,XR,NTT,BANKS
74,STARHEALTH,0.45,13.32,29.95,47.26,95411.0,37443.0,318566.0,761.0,78.95,55.0,H-SC,19.34,173.0,0.39,2.09,38.24,XY24,NTT,INSURANCE
68,SATIN,-0.24,41.56,7.26,51.83,28395.0,114825.0,391109.0,274.0,27.46,55.0,H-SC,44.39,159.0,4.04,2.56,90.53,XY24,NTT,FINANCE

In [16]:
# top 5 to book for rotation from weak conviction
df_tmp = df_portfolio_features[~df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])]
df_tmp = df_tmp[~df_tmp['Criteria'].isin(['XY25','XY24','X40', 'X40N'])].sort_values(by = 'RRR Ind', ascending=False)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
73,SONACOMS,2.14,26.26,9.84,38.69,12568.0,26565.0,127724.0,801.69,0.05,84.0,M-MC,24.25,193.0,2.11,0.84,81.21,AR,ATH,AUTO
91,ZYDUSLIFE,-0.74,20.27,12.77,35.63,32187.0,42476.0,252050.0,1286.17,4.50,57.0,H-MC,17.13,120.0,1.32,1.65,32.52,AR,ATH,PHARMA
75,SURYODAY,4.82,7.34,14.62,23.03,28102.0,13148.0,192219.0,216.00,110.53,62.0,H-SC,22.39,166.0,0.47,1.26,63.16,XR,NTT,BANKS
25,FINCABLES,-0.99,27.57,62.98,107.91,118620.0,40702.0,188346.0,1641.55,14.66,39.0,M-SC,22.83,220.0,0.34,1.23,41.70,OX40N,ATH,CABLES
72,SIS,1.79,1.36,19.63,21.26,22092.0,1512.0,112544.0,528.00,2688.60,61.0,H-SC,24.91,168.0,0.07,0.74,67.34,OX40N,NTT,MISC

In [17]:
# top 5 to accumulate based on lowest RSI_14
df_tmp = df_portfolio_features[df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])].sort_values(by = 'RSI_14', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
39,ICICIGI,0.51,-14.16,38.50,18.89,66133.0,-28336.0,171773.0,2244.41,-27.68,32.0,X-MC,5.22,66.0,-0.43,1.12,0.51,X40,ATH,INSURANCE
87,VBL,-0.88,-6.29,44.46,35.37,131587.0,-19874.0,295968.0,670.16,-17.21,33.0,X-LC,7.75,13.0,-0.15,1.94,21.64,X40N,ATH,FMCG
58,PGHH,0.59,-34.27,100.83,32.01,141517.0,-73168.0,140352.0,17616.87,-55.58,38.0,X-MC,20.32,57.0,-0.52,0.92,0.59,X40,ATH,FMCG
23,DMART,0.56,-4.47,35.66,29.60,85030.0,-11154.0,238446.0,5391.45,-19.43,39.0,X-LC,2.14,14.0,-0.13,1.56,8.99,X40N,ATH,FMCG
81,TMPV,-0.97,-24.15,80.07,36.58,216103.0,-85949.0,269892.0,600.00,-84.72,39.0,X-LC,7.98,4.0,-0.40,1.77,13.43,XY24,NTT,AUTO

In [18]:
# top 5 to accumulate based on Spread and CumlRnk
df_tmp = df_portfolio_features[df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])]
df_tmp = df_tmp[(df_tmp['CumlRnk'] < 100)].sort_values(by = 'Spread%', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
11,BERGEPAINT,2.32,-6.91,34.61,25.32,83045.0,-17803.0,239946.0,680.00,-11.94,49.0,X-MC,1.79,68.0,-0.21,1.57,24.88,XY24,NTT,PAINTS
23,DMART,0.56,-4.47,35.66,29.60,85030.0,-11154.0,238446.0,5391.45,-19.43,39.0,X-LC,2.14,14.0,-0.13,1.56,8.99,X40N,ATH,FMCG
19,COLPAL,2.33,-20.64,76.24,39.86,159342.0,-54365.0,209000.0,3683.41,-4.06,58.0,X-MC,2.64,62.0,-0.34,1.37,18.22,XY25,ATH,FMCG
17,CIPLA,-0.74,15.85,15.18,33.43,26934.0,24271.0,177432.0,1648.14,-10.44,52.0,X-LC,3.18,18.0,0.90,1.16,21.13,X40N,ATH,PHARMA
1,ABBOTINDIA,2.50,-3.54,22.40,18.07,38647.0,-6325.0,172530.0,35195.00,-17.90,76.0,X-MC,3.52,58.0,-0.16,1.13,14.20,X40,ATH,PHARMA

In [19]:
# top 5 to accumulate based on lowest Gained%
df_tmp = df_portfolio_features[df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])].sort_values(by = 'Gained%', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
39,ICICIGI,0.51,-14.16,38.50,18.89,66133.0,-28336.0,171773.0,2244.41,-27.68,32.0,X-MC,5.22,66.0,-0.43,1.12,0.51,X40,ATH,INSURANCE
58,PGHH,0.59,-34.27,100.83,32.01,141517.0,-73168.0,140352.0,17616.87,-55.58,38.0,X-MC,20.32,57.0,-0.52,0.92,0.59,X40,ATH,FMCG
47,ITC,-0.99,-26.27,61.49,19.06,154211.0,-89376.0,250790.0,452.00,-59.56,42.0,X-LC,12.67,1.0,-0.58,1.64,1.58,X40,NTT,FMCG
35,HDFCLIFE,-0.75,-8.50,45.04,32.71,61734.0,-12735.0,137065.0,811.41,-28.56,43.0,X-LC,15.22,31.0,-0.21,0.90,2.97,X40,ATH,INSURANCE
65,RELIANCE,-1.28,-16.16,49.45,25.30,83317.0,-32476.0,168487.0,1952.00,-18.49,49.0,X-LC,7.34,21.0,-0.39,1.10,3.76,XY25,BTT,REFINERIES

In [20]:
# top 5 to accumulate based on lowest CurrAlloc%
df_tmp = df_portfolio_features[df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])].sort_values(by = 'CurrAlloc%', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
10,BATAINDIA,-0.72,-55.14,201.39,35.20,116246.0,-70948.0,57722.0,2096.00,-24.33,51.0,X-SC,17.95,91.0,-0.61,0.38,14.48,X40,NTT,FOOTWEAR
64,RELAXO,-4.95,-46.20,183.10,52.31,142992.0,-67065.0,78095.0,1176.00,-42.70,59.0,X-SC,12.57,92.0,-0.47,0.51,74.61,X40N,NTT,FOOTWEAR
60,QUESS,1.61,22.92,41.47,73.90,54437.0,24476.0,131269.0,424.00,-33.88,71.0,X-SC,31.88,80.0,0.45,0.86,78.95,XY24,NTT,MISC
35,HDFCLIFE,-0.75,-8.50,45.04,32.71,61734.0,-12735.0,137065.0,811.41,-28.56,43.0,X-LC,15.22,31.0,-0.21,0.90,2.97,X40,ATH,INSURANCE
28,GODREJCP,-2.85,-6.80,41.06,31.47,56871.0,-10108.0,138506.0,1469.04,-1.98,47.0,X-LC,6.52,32.0,-0.18,0.91,6.27,X40N,ATH,FMCG

In [21]:
# top 5 to accumulate based on CumlRnk
df_tmp = df_portfolio_features.sort_values(by = 'CumlRnk', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
47,ITC,-0.99,-26.27,61.49,19.06,154211.0,-89376.0,250790.0,452.00,-59.56,42.0,X-LC,12.67,1.0,-0.58,1.64,1.58,X40,NTT,FMCG
79,TCS,-1.32,-34.79,90.46,24.20,273277.0,-161176.0,302097.0,4230.71,-44.94,57.0,X-LC,20.14,2.0,-0.59,1.98,12.65,X40,ATH,IT
45,INFY,-1.61,-27.19,84.37,34.24,192216.0,-85063.0,227825.0,1972.00,-42.67,47.0,X-LC,20.93,3.0,-0.44,1.49,8.56,X40,NTT,IT
81,TMPV,-0.97,-24.15,80.07,36.58,216103.0,-85949.0,269892.0,600.00,-84.72,39.0,X-LC,7.98,4.0,-0.40,1.77,13.43,XY24,NTT,AUTO
59,PIDILITIND,0.70,11.74,5.93,18.37,9350.0,16560.0,157670.0,1670.26,-21.72,53.0,X-LC,8.12,5.0,1.77,1.03,23.80,X40,ATH,CHEMICALS

In [22]:
# top 5 for average up
df_tmp = df_portfolio_features[(df_portfolio_features['Dev%_200'] > 5)].sort_values(by = 'CurrAlloc%', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
44,INDUSINDBK,3.31,-21.66,69.63,32.89,42116.0,-16720.0,60486.0,1800.00,-385.01,73.0,L-MC,11.69,258.0,-0.40,0.40,49.12,XR,NTT,BANKS
64,RELAXO,-4.95,-46.20,183.10,52.31,142992.0,-67065.0,78095.0,1176.00,-42.70,59.0,X-SC,12.57,92.0,-0.47,0.51,74.61,X40N,NTT,FOOTWEAR
3,ALKYLAMINE,0.40,-21.88,146.48,92.54,115530.0,-22092.0,78871.0,4520.85,-16.40,51.0,H-SC,11.59,142.0,-0.19,0.52,49.77,SR,ATH,CHEMICALS
83,TTKPRESTIG,-2.51,-14.78,17.45,0.09,14987.0,-14893.0,85884.0,770.00,99.36,64.0,M-SC,9.43,250.0,-0.99,0.56,52.93,OX40N,NTT,DURABLES
72,SIS,1.79,1.36,19.63,21.26,22092.0,1512.0,112544.0,528.00,2688.60,61.0,H-SC,24.91,168.0,0.07,0.74,67.34,OX40N,NTT,MISC

In [23]:
# top 5 RSP
df_tmp = df_portfolio_features.sort_values(by = 'RSP', ascending=False)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
60,QUESS,1.61,22.92,41.47,73.90,54437.0,24476.0,131269.0,424.00,-33.88,71.0,X-SC,31.88,80.0,0.45,0.86,78.95,XY24,NTT,MISC
73,SONACOMS,2.14,26.26,9.84,38.69,12568.0,26565.0,127724.0,801.69,0.05,84.0,M-MC,24.25,193.0,2.11,0.84,81.21,AR,ATH,AUTO
64,RELAXO,-4.95,-46.20,183.10,52.31,142992.0,-67065.0,78095.0,1176.00,-42.70,59.0,X-SC,12.57,92.0,-0.47,0.51,74.61,X40N,NTT,FOOTWEAR
83,TTKPRESTIG,-2.51,-14.78,17.45,0.09,14987.0,-14893.0,85884.0,770.00,99.36,64.0,M-SC,9.43,250.0,-0.99,0.56,52.93,OX40N,NTT,DURABLES
44,INDUSINDBK,3.31,-21.66,69.63,32.89,42116.0,-16720.0,60486.0,1800.00,-385.01,73.0,L-MC,11.69,258.0,-0.40,0.40,49.12,XR,NTT,BANKS

In [24]:
# Top N allocation
df_tmp = df_portfolio_features.sort_values(by = 'CurrAlloc%', ascending=False)
top_n_values = [10, 25, 50]

sum_df = pd.DataFrame({
    'Top_N': top_n_values,
    'Sum_Alloc%': [df_tmp['CurrAlloc%'].head(n).sum() for n in top_n_values]
})

sum_df

   Top_N  Sum_Alloc%
0     10       19.28
1     25       42.51
2     50       72.62

In [25]:
# market-cap-wise allocation
df_tmp = df_portfolio_features[cols]
df_tmp.groupby(df_tmp['Conviction'].str[-2:])['CurrAlloc%'].sum().sort_values(ascending=False)

Conviction
SC    43.76
LC    29.93
MC    26.29
Name: CurrAlloc%, dtype: float64

In [26]:
# criteria-wise allocation
df_portfolio_features.groupby('Criteria')['CurrAlloc%'].sum().sort_values(ascending=False)

Criteria
XY24     27.70
X40      24.56
X40N     17.39
XR        8.88
OX40N     7.05
AR        7.01
XY25      6.49
SR        0.90
Name: CurrAlloc%, dtype: float64

In [27]:
# conviction-wise allocation
df_portfolio_features.groupby('Conviction')['CurrAlloc%'].sum().sort_values(ascending=False)

Conviction
X-LC    27.95
H-SC    23.10
X-MC    21.04
X-SC    10.19
M-SC     9.91
H-MC     2.72
M-MC     2.13
H-LC     1.19
M-LC     0.79
L-SC     0.56
L-MC     0.40
Name: CurrAlloc%, dtype: float64

In [28]:
# sector-wise stats
df_tmp = df_portfolio_features.groupby('Category')[['CurrAlloc%', 'Current', 'Current P/L', 'FTT Amt']].sum().sort_values(by=['Current', 'Current P/L'], ascending=False)
df_tmp['Current P/L%'] = round(df_tmp['Current P/L'] * 100 / df_tmp['Current'], 2)
df_tmp['FTT%'] = round(df_tmp['FTT Amt'] * 100 / df_tmp['Current'], 2)
cols = ['CurrAlloc%', 'Current P/L%', 'FTT%']
df_tmp[cols].sort_values(by=['CurrAlloc%'], ascending=False)

               CurrAlloc%  Current P/L%    FTT%
Category
FMCG                14.18        -22.20   65.07
FINANCE             11.19         -7.78   54.48
IT                  10.12        -45.80  117.95
MISC                 7.29        -20.55   72.28
AUTO                 6.64         -8.13   48.45
BANKS                5.85         -1.78   48.81
PAINTS               5.43        -18.56   38.78
PHARMA               5.24          7.53   21.09
INSURANCE            5.17         -4.91   40.29
ELECTRICAL           4.11        -12.36   51.88
CHEMICALS            2.15        -23.59   96.91
HEALTHCARE           2.08        -12.73   42.15
APPARELS             1.84          4.26   27.90
AC                   1.82        -14.79   45.91
FOOTWEAR             1.73        -67.54  134.72
REALTY               1.71         14.99   -1.03
DURABLES             1.62        -55.56   93.41
BREWERIES            1.56          1.88   18.50
TRAVEL               1.51        -95.08  192.75
CERAMICS             1.42        -41.58   84.59
ENGINEERING          1.27        -25.01   82.19
CABLES               1.23         21.61   62.98
JEWELLERY            1.11        -88.95  154.60
REFINERIES           1.10        -19.28   49.45
CEMENT               1.09        -61.03  181.49
ENTERTAINMENT        0.71        -76.88  182.38
TEXTILES             0.41        -48.57   90.93
HOTELS               0.40        -87.99  154.29

In [29]:
# money to be made criteria-wise
df_portfolio_features.groupby('Criteria')['FTT Amt'].agg(['sum', 'count']).sort_values(by='sum', ascending=False)

                sum  count
Criteria
XY24      3367056.0     21
X40       1918105.0     19
XR        1323400.0     13
AR        1104483.0      9
X40N      1062379.0     13
OX40N      714059.0     10
XY25       444409.0      5
SR         281614.0      2

In [30]:
# money to be made conviction-wise
df_portfolio_features.groupby('Conviction')['FTT Amt'].agg(['sum', 'count']).sort_values(by='sum', ascending=False)

                  sum  count
Conviction
H-SC        3246422.0     24
X-LC        2004620.0     21
X-MC        1500446.0     15
M-SC        1402720.0     14
X-SC        1246326.0      9
H-MC         283217.0      2
L-SC         206617.0      2
M-LC         170551.0      1
M-MC          61077.0      2
H-LC          51393.0      1
L-MC          42116.0      1

In [31]:
# money to be made criteria and conviction-wise
df_portfolio_features.groupby(['Conviction', 'Criteria'])['FTT Amt'].agg(['sum', 'count']).sort_values(by='sum', ascending=False)

                           sum  count
Conviction Criteria
X-LC       X40       1040092.0     10
H-SC       XY24       957477.0      6
           AR         931792.0      5
M-SC       XY24       826071.0      6
H-SC       XR         780525.0      7
X-SC       XY24       734924.0      4
X-MC       X40        667511.0      7
X-LC       X40N       396722.0      6
X-MC       X40N       364757.0      4
X-LC       XY24       363326.0      2
M-SC       OX40N      305624.0      5
X-SC       X40N       300900.0      3
H-SC       OX40N      295014.0      4
           SR         281614.0      2
H-MC       XY24       251030.0      1
X-MC       XY24       234228.0      2
           XY25       233950.0      2
X-SC       X40        210502.0      2
M-SC       XR         194482.0      2
M-LC       XR         170551.0      1
X-LC       XY25       161950.0      2
L-SC       OX40N      113421.0      1
           XR          93196.0      1
M-SC       AR          76543.0      1
H-LC       AR          51393.0      1
M-MC       XY25        48509.0      1
X-LC       XR          42530.0      1
L-MC       XR          42116.0      1
H-MC       AR          32187.0      1
M-MC       AR          12568.0      1

In [32]:
# notebook execution time

end_time = time.time()
execution_time = round(end_time - start_time, 0)
print(f"Notebook execution time: {execution_time} seconds")

Notebook execution time: 61.0 seconds