<a href="https://colab.research.google.com/github/ankit-rathi/Quantvesting_v2/blob/main/myStocks_Portfolio_Analysis.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
'''
!pip install pandas==2.2.2 -qq
!pip install pyxirr -qq
!pip install ta -qq
!pip install yfinance==0.2.59 -qq
'''

'\n!pip install pandas==2.2.2 -qq\n!pip install pyxirr -qq\n!pip install ta -qq\n!pip install yfinance==0.2.59 -qq\n'

In [2]:
# import libraries

import numpy as np
import pandas as pd
import datetime
import warnings
warnings.filterwarnings('ignore')
import yfinance as yfin
import ta
import matplotlib.pyplot as plt
import requests

In [3]:
# notebook start time
import time
import datetime
import pytz

start_time = time.time()

# function to print date timestamp
def print_date_time():
  tz_NY = pytz.timezone('Asia/Kolkata')
  datetime_NY = datetime.datetime.now(tz_NY)
  print("Run date time (IST):", datetime_NY.strftime("%Y-%m-%d %H:%M:%S"))

In [4]:
# function to get booked and reserved amount
def get_amt():
  # fetch the JSON data from the URL
  url = "https://raw.githubusercontent.com/ankit-rathi/Tradevesting_v1/main/data/myPortfolioAmts.json"
  response = requests.get(url)
  pf_amts = response.json()  # parse the JSON data

  # extract values from the JSON
  py_booked_amt_dm = pf_amts["py_booked_amt_dm"]
  py_booked_amt_sv = pf_amts["py_booked_amt_sv"]
  cy_booked_amt_dm = pf_amts["cy_booked_amt_dm"]
  cy_booked_amt_sv = pf_amts["cy_booked_amt_sv"]
  reserve_amt_dm = pf_amts["reserve_amt_dm"]
  reserve_amt_sv = pf_amts["reserve_amt_sv"]

  # perform calculations
  py_booked_amt = py_booked_amt_dm + py_booked_amt_sv
  cy_booked_amt = cy_booked_amt_dm + cy_booked_amt_sv
  reserve_amt = reserve_amt_dm + reserve_amt_sv
  total_booked_amt = py_booked_amt + cy_booked_amt

  return total_booked_amt, reserve_amt, cy_booked_amt, py_booked_amt

gen_output = 0

In [5]:
# function to format the amount
def format_amt(number):
    abs_number = abs(number)

    if abs_number >= 1_00_00_000:  # Crores
        formatted_amt = f"{number / 1_00_00_000:.2f} C"
    elif abs_number >= 1_00_000:  # Lakhs
        formatted_amt = f"{number / 1_00_000:.2f} L"
    elif abs_number >= 1_000:  # Thousands
        formatted_amt = f"{number / 1_000:.2f} K"
    else:
        formatted_amt = f"{number:.2f}"

    return formatted_amt

# function to set start and end date
def get_start_end_date():
  start_date = (datetime.date.today() + datetime.timedelta(days=-365)).strftime('%Y-%m-%d')
  end_date = (datetime.date.today() + datetime.timedelta(days=1)).strftime('%Y-%m-%d')
  return start_date, end_date

# function to fetch my portfolio csv
def get_mypfs_df():
  mypfs_df = pd.read_csv('https://raw.githubusercontent.com/ankit-rathi/Tradevesting_v1/main/data/myPortfolioStocks.csv')
  return mypfs_df

# function to fetch my prospects csv
def get_mypps_df():
  mypps_df = pd.read_csv('https://raw.githubusercontent.com/ankit-rathi/Tradevesting_v1/main/data/myProspectsScrips.csv')
  return mypps_df

# function to fetch screener data
def get_myscreen_df():
  myscreen_df = pd.read_csv('https://raw.githubusercontent.com/ankit-rathi/Tradevesting_v1/main/data/myScreenerDB.csv')
  return myscreen_df

# function to fetch momentum data
def get_myinvmt_df():
  myinvmt_df = pd.read_csv('https://raw.githubusercontent.com/ankit-rathi/Tradevesting_v1/main/data/myInvestments.csv')
  return myinvmt_df

# function to get the stock ids
def get_stock_ids(df_pf):
  stock_n100 = df_pf['Symbol'].unique()

  exclude = ['CADILAHC','MMTC', 'MASFIN']

  stock_ids = df_pf[~df_pf['Symbol'].isin(exclude) ]['Symbol'].unique()

  #mypf = mypf[mypf.Forecast.notnull()]
  #stock_ids = mypf['Symbol'].unique()

  #stock_ids.sort()
  return stock_ids

# get features from screener data
def get_screener_features():
  myscreen_df = get_myscreen_df()
  cols = ['Symbol', 'EPS', 'MedPE', 'ROCE%', 'ROE%', 'CapType']
  return myscreen_df[cols]

# get relative strength
def get_relative_strength(stock_list):

    # Dictionary to store stock tickers and their corresponding percentage price change
    stock_changes = {}

    # Loop through each stock and fetch its price data
    for stock in stock_list:
        try:
            # Download the stock data for the given date range
            stock_data = yfin.Ticker(stock + '.NS').history(period='1mo', interval='1d')[map(str.title, ['open', 'close', 'low', 'high', 'volume'])]

            # Calculate the percentage change for the stock
            if len(stock_data) > 0:
                start_price = stock_data['Close'].iloc[0]
                end_price = stock_data['Close'].iloc[-1]
                percent_change = round(((end_price - start_price) / start_price) * 100, 2)
                stock_changes[stock] = percent_change
            else:
                stock_changes[stock] = np.nan  # If no data is available, set to NaN

        except Exception as e:
            print(f"Error fetching data for {stock}: {e}")
            stock_changes[stock] = np.nan

    # Create a DataFrame with stock tickers and their percentage changes
    df = pd.DataFrame(list(stock_changes.items()), columns=['Symbol', 'Percent_Change'])

    # Drop any stocks with missing data (NaN values)
    df = df.dropna()

    # Calculate the percentile rank based on percentage change
    df['RSP'] = round(df['Percent_Change'].rank(pct=True) * 100, 2)
    cols = ['Symbol', 'RSP']
    df = df[cols]
    # Sort by percentile rank (optional)
    df = df.sort_values(by='RSP', ascending=False).reset_index(drop=True)

    return df

In [6]:
# function to get stock technicals
def stock_prec_dev(stock_symbol):
    #stock_symbol = 'ULTRACEMCO.NS'
    short_window = 20
    mid_window = 50
    long_window = 200
    moving_avg = 'SMA'

    start = datetime.datetime(*map(int, start_date.split('-')))
    end = datetime.datetime(*map(int, end_date.split('-')))

    stock_df = yfin.Ticker(stock_symbol + '.NS').history(period='max', interval='1d')[map(str.title, ['open', 'close', 'low', 'high', 'volume'])]

    stock_df['Max'] = round(max(stock_df['Close']),2)
    stock_df = stock_df[(stock_df.index <= end_date) & (stock_df.index >= start_date)]
    stock_df['200_SMA'] = round(stock_df['Close'].rolling(window = 200, min_periods = 1).mean(),0)
    stock_df['Dev%_200'] = round((stock_df['Close'] - stock_df['200_SMA'])*100/stock_df['200_SMA'],2)
    stock_df.dropna(axis = 0, inplace = True) # remove any null rows

    stock_df['20_SMA'] = stock_df['Close'].rolling(window=20).mean()
    stock_df['50_SMA'] = stock_df['Close'].rolling(window=50).mean()
    stock_df['Symbol'] = stock_symbol

    stock_df['Close'] = round(stock_df['Close'],2)
    stock_df['Min'] = round(min(stock_df['Close']),2)
    stock_df['RSI_14'] = ta.momentum.RSIIndicator(close=stock_df['Close'], window=14).rsi()
    stock_df['RSI_14'] = round(stock_df['RSI_14'],0)
    stock_df['Prev_Close'] = stock_df['Close'].shift(1)
    stock_df.drop(['Open', 'Low', 'High', 'Volume'], axis=1, inplace=True)
    stock_df = stock_df.tail(1)

    max_SMA = max(stock_df['20_SMA'].item(), stock_df['50_SMA'].item(), stock_df['200_SMA'].item())
    min_SMA = min(stock_df['20_SMA'].item(), stock_df['50_SMA'].item(), stock_df['200_SMA'].item())
    ABS_Spread = max_SMA - min_SMA
    stock_df['Spread%'] = round((ABS_Spread / stock_df['200_SMA'].item()) * 100,2)

    return stock_df

# function to compute stock attributes
def get_common_features(stock_ids, df_mypf):

  df_prec_dev = pd.DataFrame()
  df_tmp = get_screener_features()
  df_rs = get_relative_strength(stock_ids)

  for stock_id in stock_ids:
      tmp = stock_prec_dev(stock_id)
      tmp = tmp.reset_index()
      df_prec_dev = pd.concat([df_prec_dev, tmp], ignore_index = True)
  df_prec_dev = pd.merge(df_prec_dev, df_mypf, on= 'Symbol')
  df_prec_dev = pd.merge(df_prec_dev, df_tmp, on= 'Symbol', how='left')
  df_prec_dev = pd.merge(df_prec_dev, df_rs, on= 'Symbol', how='left')
  #print(df_prec_dev.columns)
  df_prec_dev['Curr_PE'] = round(df_prec_dev['Close']/df_prec_dev['EPS'],1)
  df_prec_dev['Dev%_PE'] = round((df_prec_dev['Curr_PE'] - df_prec_dev['MedPE'])*100/df_prec_dev['MedPE'],2)
  df_prec_dev['Conviction'] = df_prec_dev['Conviction'] + '-' + df_prec_dev['CapType']
  return df_prec_dev

# function to arrange stock features
def arrange_features(df_stocks, common_cols, diff_cols):
  df_stocks_common = df_stocks[common_cols].drop_duplicates()
  df_stocks_diff = df_stocks[diff_cols]
  df_stocks_diff['Investment'] = df_stocks_diff['AvgCost'] * df_stocks_diff['Shares']
  df_stocks_diff = df_stocks_diff.groupby(['Symbol'])[['Shares', 'Investment']].aggregate(['sum']).reset_index()
  df_stocks_diff.columns = ['Symbol', 'Shares', 'Investment']
  df_stocks_diff['AvgCost'] = round(df_stocks_diff['Investment']/df_stocks_diff['Shares'],2)
  df_stocks = pd.merge(df_stocks_diff, df_stocks_common, on='Symbol')
  return df_stocks

# plot fact distribution across dimension
def plot_pie_chart(df, dimension, fact):
  # grouping the data by category and calculating the sum of fact for each type
  grouped_data = df.groupby(dimension)[fact].sum()

  # sorting the grouped data in descending order
  grouped_data = grouped_data.sort_values(ascending=False)

  # creating a pie chart
  grouped_data.plot.pie(autopct='%1.1f%%', startangle=90, figsize=(6, 6))

  # adding a title and displaying the plot
  plt.title(f'{dimension} {fact} Distribution')
  plt.ylabel('')  # To hide the y-label
  plt.show()

In [7]:
# function to get portfolio features

def get_portfolio_features(df_common_features):

  print_date_time()
  print('-------------------')

  #df_common_features["Target"] = df_common_features["Target"].fillna(df_common_features["Max"])
  df_common_features['NTT'] = np.where(df_common_features['Strategy']== 'NTT', df_common_features["Target"], df_common_features['Max'])
  df_common_features['LTT'] = np.where(df_common_features['Strategy']== 'BTT', df_common_features["Target"], df_common_features['Max'])
  df_common_features['BOL'] = df_common_features['Min']

  tmp_df = df_common_features[df_common_features['Symbol'].isin(mypf_df[mypf_df['InPortfolio'] != 'NA'].Symbol.values)]
  print('qualified stocks: '+str(len(tmp_df['Symbol'].unique())))
  tmp_df1 = tmp_df[tmp_df['LatestQtr'] == 1]
  print('with latest results: '+str(len(tmp_df1['Symbol'].unique())))
  tmp_df1 = tmp_df1[tmp_df1['StarStock'] == 1]
  print('still star stocks: '+str(len(tmp_df1['Symbol'].unique())))
  tmp_df['Investment'] = tmp_df['AvgCost'] * tmp_df['Shares']
  tmp_df['Current'] = round(tmp_df['Close'] * tmp_df['Shares'],0)
  tmp_df['Previous'] = tmp_df['Prev_Close'] * tmp_df['Shares']
  tmp_df['EstimatedST'] = tmp_df['NTT'] * tmp_df['Shares']
  tmp_df['EstimatedLT'] = tmp_df['LTT'] * tmp_df['Shares']
  tmp_df['Current P/L'] = round((tmp_df['Current'] - tmp_df['Investment']),0)
  tmp_df['Today P/L%'] = round((tmp_df['Current'] - tmp_df['Previous'])*100/tmp_df['Previous'],2)
  tmp_df['Current P/L%'] = round((tmp_df['Current'] - tmp_df['Investment'])*100/tmp_df['Investment'],2)
  tmp_df['EstimatedST P/L%'] = round((tmp_df['EstimatedST'] - tmp_df['Investment'])*100/tmp_df['Investment'],2)
  tmp_df['EstimatedLT P/L%'] = round((tmp_df['EstimatedLT'] - tmp_df['Investment'])*100/tmp_df['Investment'],2)
  tmp_df['NTT%'] = round((tmp_df['NTT'] - tmp_df['Close'])*100/tmp_df['Close'],2)
  tmp_df['LTT%'] = round((tmp_df['LTT'] - tmp_df['Close'])*100/tmp_df['Close'],2)
  tmp_df['Gained%'] = round((tmp_df['Close'] - tmp_df['BOL'])*100/tmp_df['BOL'],2)
  investment = round(sum(tmp_df['AvgCost']*tmp_df['Shares']),0)
  current = round(sum(tmp_df['Close']*tmp_df['Shares']),0)
  tmp_df['InitAlloc%'] = round(tmp_df['Investment']*100/investment,2)
  tmp_df['CurrAlloc%'] = round(tmp_df['Current']*100/current,2)
  tmp_df['FTT'] = tmp_df['LTT']
  tmp_df.loc[tmp_df['Strategy'] == 'NTT', 'FTT'] = tmp_df['NTT']
  tmp_df['FTT%'] = tmp_df['LTT%']
  tmp_df.loc[tmp_df['Strategy'] == 'NTT', 'FTT%'] = tmp_df['NTT%']
  tmp_df['FTT Amt'] = round(tmp_df['FTT%'] * tmp_df['Current']/100,0)
  tmp_df['OTT%'] = round((tmp_df['FTT'] - tmp_df['AvgCost'])*100/tmp_df['AvgCost'],2)
  tmp_df['RRR Ind'] = round(tmp_df['Current P/L']/tmp_df['FTT Amt'],2)
  tmp_df['Risk Ind'] = round(tmp_df['Current P/L%']*tmp_df['CurrAlloc%'],0)

  return tmp_df

# function to print portfolio features
def print_portfolio_stats(df_portfolio_features, myinvmt_df):
  from pyxirr import xirr

  total_booked_amt, reserve_amt, cy_booked_amt, py_booked_amt = get_amt()

  dates = myinvmt_df['Date'].values
  dates = np.append(dates, datetime.date.today().strftime('%d-%b-%y'))
  investment = myinvmt_df['Investment'].values
  dates= pd.to_datetime(dates)

  current = round(sum(df_portfolio_features['Close']*df_portfolio_features['Shares']),0) + reserve_amt
  investment_xirr = np.append(investment, current)
  cagr = round(xirr(pd.DataFrame({"dates": dates, "amounts": investment_xirr}))*100,2)

  investment = -sum(investment)
  invested = round(sum(df_portfolio_features['AvgCost']*df_portfolio_features['Shares']),0) + reserve_amt
  previous = round(sum(df_portfolio_features['Prev_Close']*df_portfolio_features['Shares']),0) + reserve_amt
  cy_invested = investment + py_booked_amt

  today_pnl_amount = current-previous
  today_pnl_percentage = round((current-previous)*100/previous,2)

  curr_pnl_amount = current-invested
  curr_pnl_percentage = round((curr_pnl_amount)*100/(cy_invested),2)

  cy_pnl_amount = cy_booked_amt + curr_pnl_amount
  cy_pnl_percentage = round((cy_pnl_amount)*100/cy_invested,2)

  overall_pnl_amount = total_booked_amt + curr_pnl_amount
  overall_pnl_percentage = round((overall_pnl_amount)*100/investment,2)

  estimate_st = round(sum(df_portfolio_features['FTT']*df_portfolio_features['Shares']),0)  + reserve_amt
  est_st_pnl_amount = estimate_st-current
  est_st_pnl_percentage = round((est_st_pnl_amount)*100/current,2)

  estimate_lt = round(sum(df_portfolio_features['LTT']*df_portfolio_features['Shares']),0)  + reserve_amt
  est_lt_pnl_amount = estimate_lt-current
  est_lt_pnl_percentage = round((est_lt_pnl_amount)*100/current,2)

  total_profit = round(sum(df_portfolio_features[df_portfolio_features['Current P/L%'] > 0]['Current']) - sum(df_portfolio_features[df_portfolio_features['Current P/L%'] > 0]['Investment']),0)
  total_loss = round(sum(df_portfolio_features[df_portfolio_features['Current P/L%'] < 0]['Current']) - sum(df_portfolio_features[df_portfolio_features['Current P/L%'] < 0]['Investment']),0)

  cy_booked_percentage = round((cy_booked_amt)*100/current,2)
  py_booked_percentage = round((py_booked_amt)*100/investment,2)
  total_booked_percentage = round((total_booked_amt)*100/investment,2)

  print('-------------------')
  print('Initial Investment: ', format_amt(investment))
  print('CY Investment: ', format_amt(cy_invested))
  print('Reserve: ', format_amt(reserve_amt))
  print('Current: ',  format_amt(current))
  print('-------------------')
  print('Today PnL: '+ '{} ({}%)'.format(format_amt(today_pnl_amount), today_pnl_percentage))
  print('Current PnL: '+ '{} ({}%)'.format(format_amt(curr_pnl_amount), curr_pnl_percentage))
  print('CY Booked + Current PnL: '+ '{} ({}%)'.format(format_amt(cy_pnl_amount), cy_pnl_percentage))
  print('-------------------')
  print('Total profit: ', format_amt(total_profit))
  print('Total loss: ', format_amt(total_loss))
  print('-------------------')
  print('Total Booked + Current PnL: '+ '{} ({}%)'.format(format_amt(overall_pnl_amount), overall_pnl_percentage))
  print('Total Booked PnL: '+ '{} ({}%)'.format(format_amt(total_booked_amt), total_booked_percentage))
  print('Curr Year Booked PnL: '+ '{} ({}%)'.format(format_amt(cy_booked_amt), cy_booked_percentage))
  print('Prev Year Booked PnL: '+ '{} ({}%)'.format(format_amt(py_booked_amt), py_booked_percentage))
  print('===================')
  print('Est FTT: ',  format_amt(estimate_st))
  print('Est FTT PnL: '+ '{} ({}%)'.format(format_amt(est_st_pnl_amount), est_st_pnl_percentage))

  print('===================')
  print('Deployed: ', format_amt(investment))

  print('Current: ', format_amt(current))

  print('CAGR/XIRR %: '+'{}%'.format(cagr))

In [8]:
# get start and end date
start_date, end_date = get_start_end_date()

# get portfolio and prospects data
mypfs_df = get_mypfs_df()
mypps_df = get_mypps_df()
myinvmt_df = get_myinvmt_df()

# merge above datasets
mypf_df = pd.merge(mypfs_df, mypps_df, on="Symbol")

# seggregate dm and sv portfolio
dm_pf = mypf_df[mypf_df['InPortfolio'] == 'DM']
sv_pf = mypf_df[mypf_df['InPortfolio'] == 'SV']

# build portfolio stock dataframe
dm_stocks = get_stock_ids(dm_pf)
sv_stocks = get_stock_ids(sv_pf)
df_stocks = pd.concat([dm_pf,sv_pf], ignore_index = True)

# arrange common and diff stock features
common_cols = ['Symbol', 'Target', 'Criteria', 'Strategy', 'CumlRnk', 'LatestQtr', 'StarStock', 'Conviction', 'Category', 'InFolio', 'XIRR', 'MBQ']
diff_cols = ['Symbol', 'AvgCost', 'Shares']
df_stocks = arrange_features(df_stocks, common_cols, diff_cols)

# get common features
stock_ids = df_stocks['Symbol'].values
df_common_features = get_common_features(stock_ids, df_stocks)

df_common_features.reset_index(drop=True, inplace=True)
df_common_features.drop(['Date'], axis=1, inplace=True)
# get and print portfolio features
df_portfolio_features = get_portfolio_features(df_common_features)

print_portfolio_stats(df_portfolio_features, myinvmt_df)

df = df_portfolio_features
#plot_pie_chart(df, 'CapType', 'Current')
list_ox40n = list(df[df['MBQ'].str.contains('OX40N', na=False)]['Symbol'].values)

Run date time (IST): 2026-03-30 15:18:39
-------------------
qualified stocks: 86
with latest results: 26
still star stocks: 16
-------------------
Initial Investment:  1.36 C
CY Investment:  1.62 C
Reserve:  1.61 K
Current:  1.25 C
-------------------
Today PnL: -3.42 L (-2.67%)
Current PnL: -52.58 L (-32.36%)
CY Booked + Current PnL: -36.69 L (-22.58%)
-------------------
Total profit:  23.55 K
Total loss:  -52.82 L
-------------------
Total Booked + Current PnL: -9.71 L (-7.17%)
Total Booked PnL: 42.87 L (31.64%)
Curr Year Booked PnL: 15.89 L (12.76%)
Prev Year Booked PnL: 26.98 L (19.91%)
===================
Est FTT:  2.48 C
Est FTT PnL: 1.23 C (99.03%)
===================
Deployed:  1.36 C
Current:  1.25 C
CAGR/XIRR %: -4.08%

In [9]:
# top 5 near their targets
cols = ['Symbol', 'Today P/L%', 'Current P/L%', 'FTT%', 'OTT%', 'FTT Amt', 'Current P/L', 'Current', 'FTT', 'Dev%_PE', 'RSI_14','Conviction', 'Spread%',  'CumlRnk', 'RRR Ind', 'CurrAlloc%', 'Gained%', 'Criteria', 'Strategy', 'Category']
df_tmp = df_portfolio_features[~df_portfolio_features['Symbol'].isin(['ENRIN','BLUSPRING','DIGITIDE'])]
df_tmp = df_tmp.sort_values(by = 'FTT Amt', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
50,MASFIN,-4.88,-14.90,42.85,21.57,35730.0,-14595.0,83385.0,397.04,-26.83,33.0,H-SC,4.29,167.0,-0.41,0.67,13.73,XR,ATH,FINANCE
77,TTKPRESTIG,-2.84,-44.42,80.10,0.09,44863.0,-44768.0,56009.0,770.00,29.99,32.0,M-SC,21.29,250.0,-1.00,0.45,0.00,OX40N,NTT,DURABLES
2,ABBOTINDIA,-0.90,-13.11,35.89,18.07,55773.0,-23455.0,155400.0,35195.00,-26.09,42.0,X-MC,10.48,58.0,-0.42,1.25,1.63,X40,ATH,PHARMA
67,SONACOMS,-1.53,-16.75,67.07,39.09,56486.0,-16940.0,84219.0,804.02,-33.97,42.0,M-MC,6.42,193.0,-0.30,0.68,19.14,AR,ATH,AUTO
37,ICICIGI,-1.89,-9.21,31.44,19.34,57121.0,-18425.0,181684.0,2252.93,-23.51,30.0,X-MC,4.98,66.0,-0.32,1.46,0.43,X40,ATH,INSURANCE

In [10]:
# top 5 today
df_tmp = df_portfolio_features.sort_values(by = 'Today P/L%', ascending=False)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
53,PGHH,2.10,-30.09,88.82,32.01,132590.0,-64240.0,149280.0,17616.87,-52.76,24.0,X-MC,17.95,57.0,-0.48,1.20,2.10,X40,ATH,FMCG
29,GREENPANEL,1.41,-53.89,210.40,43.14,177628.0,-98654.0,84424.0,537.00,89.28,29.0,M-SC,24.64,225.0,-0.56,0.68,1.41,XY24,NTT,MISC
24,DMART,1.36,-4.89,36.27,29.60,86099.0,-12216.0,237384.0,5391.45,-19.78,58.0,X-LC,6.78,14.0,-0.14,1.91,8.50,X40N,ATH,FMCG
40,INDIAMART,0.83,-14.61,142.10,106.72,149647.0,-18025.0,105311.0,4810.62,-61.52,37.0,H-SC,12.68,140.0,-0.12,0.85,5.35,AR,ATH,MISC
28,GLAXO,0.73,-8.64,52.30,39.15,95224.0,-17212.0,182072.0,3466.20,-30.16,34.0,X-MC,10.45,56.0,-0.18,1.46,0.73,X40,ATH,PHARMA

In [11]:
# bottom 5 today
df_tmp = df_portfolio_features.sort_values(by = 'Today P/L%', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
56,RAJOOENG,-8.09,-54.44,206.42,39.61,96398.0,-55800.0,46700.0,143.10,-69.28,27.0,H-SC,33.11,136.0,-0.58,0.38,0.00,AR,ATH,MISC
69,SURYODAY,-7.53,-32.62,82.59,23.03,99658.0,-58405.0,120666.0,216.00,31.58,38.0,H-SC,5.77,166.0,-0.59,0.97,13.28,XR,NTT,BANKS
30,HAPPSTMNDS,-6.89,-54.79,308.87,84.85,178972.0,-70221.0,57944.0,1480.71,-46.25,43.0,H-SC,25.42,152.0,-0.39,0.47,7.30,AR,ATH,IT
19,COFFEEDAY,-6.09,-64.27,278.61,35.27,113032.0,-72979.0,40570.0,80.00,-71.83,24.0,L-SC,29.65,266.0,-0.65,0.33,0.00,XR,NTT,HOTELS
80,VALIANTORG,-5.77,-58.01,314.71,74.15,216218.0,-94901.0,68704.0,838.00,-223.52,39.0,H-SC,28.22,145.0,-0.44,0.55,2.24,XR,NTT,CHEMICALS

In [12]:
# top 5 to exit based on CumlRnk
df_tmp = df_portfolio_features[~df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])]
df_tmp = df_tmp[(df_tmp['Current P/L%'] > -1) & (df_tmp['Current P/L%'] < 1)].sort_values(by = 'CumlRnk', ascending=False)
df_tmp[cols].head()

Empty DataFrame
Columns: [Symbol, Today P/L%, Current P/L%, FTT%, OTT%, FTT Amt, Current P/L, Current, FTT, Dev%_PE, RSI_14, Conviction, Spread%, CumlRnk, RRR Ind, CurrAlloc%, Gained%, Criteria, Strategy, Category]
Index: []

In [13]:
# OX40N stocks to exit
df_tmp = df_portfolio_features[(df_portfolio_features['Symbol'].isin(list_ox40n))].sort_values(by = 'Current P/L%', ascending=False)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
26,FINCABLES,-3.55,-1.46,110.98,107.91,161470.0,-2149.0,145495.0,1641.55,-11.21,40.0,M-SC,7.33,220.0,-0.01,1.17,9.46,OX40N,ATH,CABLES
66,SIS,-2.93,-35.65,88.44,21.26,63191.0,-39581.0,71451.0,528.00,1670.47,43.0,H-SC,14.46,168.0,-0.63,0.57,6.24,OX40N,NTT,MISC
18,CERA,-1.54,-40.26,107.38,23.89,112842.0,-70816.0,105087.0,9475.00,-42.24,41.0,H-SC,19.33,153.0,-0.63,0.84,0.99,OX40N,NTT,CERAMICS
72,TATAELXSI,-4.34,-42.64,130.16,32.03,98435.0,-56209.0,75626.0,9161.00,-28.26,32.0,H-SC,21.56,158.0,-0.57,0.61,0.00,OX40N,NTT,IT
48,KANSAINER,-1.64,-44.03,102.73,13.47,155060.0,-118728.0,150939.0,340.00,-51.83,34.0,H-SC,22.43,162.0,-0.77,1.21,5.43,XY24,NTT,PAINTS

In [14]:
# top 5 to book for rotation
df_tmp = df_portfolio_features[(df_portfolio_features['Current P/L%'] > 20) ].sort_values(by = 'CumlRnk', ascending=False)
df_tmp[cols].head()

Empty DataFrame
Columns: [Symbol, Today P/L%, Current P/L%, FTT%, OTT%, FTT Amt, Current P/L, Current, FTT, Dev%_PE, RSI_14, Conviction, Spread%, CumlRnk, RRR Ind, CurrAlloc%, Gained%, Criteria, Strategy, Category]
Index: []

In [15]:
# top 5 to monitor for exit
df_tmp = df_portfolio_features[~df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])]
df_tmp = df_tmp[(df_tmp['Current P/L%'] > 0) ].sort_values(by = 'Dev%_PE', ascending=False)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
1,ABB,-2.69,9.0,33.55,45.57,95674.0,23549.0,285168.0,7934.0,-29.92,46.0,H-MC,13.2,125.0,0.25,2.29,26.63,AR,NTT,ELECTRICAL

In [16]:
# top 5 to book for rotation from weak conviction
df_tmp = df_portfolio_features[~df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])]
df_tmp = df_tmp[~df_tmp['Criteria'].isin(['XY25','XY24','X40', 'X40N'])].sort_values(by = 'RRR Ind', ascending=False)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
1,ABB,-2.69,9.00,33.55,45.57,95674.0,23549.0,285168.0,7934.00,-29.92,46.0,H-MC,13.20,125.0,0.25,2.29,26.63,AR,NTT,ELECTRICAL
26,FINCABLES,-3.55,-1.46,110.98,107.91,161470.0,-2149.0,145495.0,1641.55,-11.21,40.0,M-SC,7.33,220.0,-0.01,1.17,9.46,OX40N,ATH,CABLES
40,INDIAMART,0.83,-14.61,142.10,106.72,149647.0,-18025.0,105311.0,4810.62,-61.52,37.0,H-SC,12.68,140.0,-0.12,0.85,5.35,AR,ATH,MISC
85,ZYDUSLIFE,-2.77,-8.06,47.52,35.63,91561.0,-16895.0,192679.0,1286.17,-19.82,43.0,H-MC,5.32,120.0,-0.18,1.55,7.27,AR,ATH,PHARMA
84,WIPRO,-2.06,-23.03,123.82,72.27,161482.0,-39031.0,130417.0,420.00,-30.65,32.0,M-LC,18.22,98.0,-0.24,1.05,0.06,XR,NTT,IT

In [17]:
# top 5 to accumulate based on lowest RSI_14
df_tmp = df_portfolio_features[df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])].sort_values(by = 'RSI_14', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
9,BAJAJHFL,-3.57,-34.67,148.15,62.13,264282.0,-94658.0,178388.0,181.50,-46.30,19.0,X-MC,21.32,60.0,-0.36,1.43,0.0,X40N,ATH,FINANCE
38,ICICIPRULI,-3.51,-15.31,54.36,30.73,90698.0,-30158.0,166847.0,790.00,-38.11,19.0,X-MC,6.52,78.0,-0.33,1.34,0.0,X40,ATH,INSURANCE
58,RELAXO,-4.44,-69.09,392.77,52.31,176220.0,-100294.0,44866.0,1176.00,-67.09,20.0,X-SC,29.74,92.0,-0.57,0.36,0.0,X40N,NTT,FOOTWEAR
27,GILLETTE,-2.84,-14.23,51.24,29.72,111585.0,-36126.0,217770.0,10978.86,-34.13,23.0,X-SC,12.32,83.0,-0.32,1.75,0.0,X40,ATH,FMCG
12,BATAINDIA,-3.77,-60.76,244.54,35.20,123476.0,-78177.0,50493.0,2096.00,-33.86,24.0,X-SC,33.05,91.0,-0.63,0.41,0.0,X40,NTT,FOOTWEAR

In [18]:
# top 5 to accumulate based on Spread and CumlRnk
df_tmp = df_portfolio_features[df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])]
df_tmp = df_tmp[(df_tmp['CumlRnk'] < 100)].sort_values(by = 'Spread%', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
65,SIEMENS,-3.71,-21.12,59.13,25.51,86794.0,-39310.0,146785.0,4671.50,23.36,38.0,H-LC,1.19,51.0,-0.45,1.18,8.10,AR,ATH,ELECTRICAL
78,UNITDSPR,-2.59,-10.28,34.61,20.77,72703.0,-24080.0,210064.0,1644.00,-20.49,35.0,X-MC,2.93,64.0,-0.33,1.69,0.00,X40N,NTT,BREWERIES
82,VOLTAS,-4.05,-0.73,46.26,45.20,88056.0,-1392.0,190350.0,1856.00,13.69,36.0,X-MC,3.11,79.0,-0.02,1.53,6.02,XY25,NTT,AC
59,RELIANCE,-0.42,-13.82,45.40,25.30,78625.0,-27781.0,173182.0,1952.00,-16.19,37.0,X-LC,3.84,21.0,-0.35,1.39,15.63,XY25,BTT,REFINERIES
37,ICICIGI,-1.89,-9.21,31.44,19.34,57121.0,-18425.0,181684.0,2252.93,-23.51,30.0,X-MC,4.98,66.0,-0.32,1.46,0.43,X40,ATH,INSURANCE

In [19]:
# top 5 to accumulate based on lowest Gained%
df_tmp = df_portfolio_features[df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])].sort_values(by = 'Gained%', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
3,ACC,-4.39,-43.76,210.81,74.81,317910.0,-117324.0,150804.0,3906.00,-60.14,24.0,X-SC,19.93,85.0,-0.37,1.21,0.0,XY24,BTT,CEMENT
12,BATAINDIA,-3.77,-60.76,244.54,35.20,123476.0,-78177.0,50493.0,2096.00,-33.86,24.0,X-SC,33.05,91.0,-0.63,0.41,0.0,X40,NTT,FOOTWEAR
10,BAJAJHLDNG,-4.42,-21.80,65.24,29.22,97000.0,-41443.0,148682.0,14451.52,-27.59,26.0,X-LC,18.59,28.0,-0.43,1.19,0.0,X40,ATH,FINANCE
9,BAJAJHFL,-3.57,-34.67,148.15,62.13,264282.0,-94658.0,178388.0,181.50,-46.30,19.0,X-MC,21.32,60.0,-0.36,1.43,0.0,X40N,ATH,FINANCE
23,DIXON,-3.57,-29.62,95.96,37.92,176143.0,-77239.0,183559.0,18931.72,-70.08,40.0,X-MC,27.88,54.0,-0.44,1.47,0.0,X40N,ATH,IT

In [20]:
# top 5 to accumulate based on lowest CurrAlloc%
df_tmp = df_portfolio_features[df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])].sort_values(by = 'CurrAlloc%', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
58,RELAXO,-4.44,-69.09,392.77,52.31,176220.0,-100294.0,44866.0,1176.00,-67.09,20.0,X-SC,29.74,92.0,-0.57,0.36,0.00,X40N,NTT,FOOTWEAR
12,BATAINDIA,-3.77,-60.76,244.54,35.20,123476.0,-78177.0,50493.0,2096.00,-33.86,24.0,X-SC,33.05,91.0,-0.63,0.41,0.00,X40,NTT,FOOTWEAR
54,QUESS,-1.96,-30.02,148.51,73.90,110984.0,-32061.0,74732.0,424.00,-62.53,35.0,X-SC,22.28,80.0,-0.29,0.60,0.44,XY24,NTT,MISC
36,HONAUT,-2.44,-31.63,121.30,51.31,159934.0,-60988.0,131850.0,58357.33,-43.21,25.0,X-SC,17.22,90.0,-0.38,1.06,0.00,X40N,ATH,ELECTRICAL
51,MEDANTA,-2.38,-17.72,54.50,27.12,79151.0,-31285.0,145232.0,1486.00,-20.26,30.0,X-SC,14.16,87.0,-0.40,1.17,0.00,XY24,NTT,HEALTHCARE

In [21]:
# top 5 to accumulate based on CumlRnk
df_tmp = df_portfolio_features.sort_values(by = 'CumlRnk', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
45,ITC,-2.29,-24.15,56.97,19.06,146984.0,-82163.0,258003.0,452.00,-58.35,31.0,X-LC,19.33,1.0,-0.56,2.07,0.00,X40,NTT,FMCG
73,TCS,-1.15,-30.65,82.52,26.57,265103.0,-142014.0,321259.0,4311.59,-41.33,29.0,X-LC,18.19,2.0,-0.54,2.58,0.26,X40,ATH,IT
43,INFY,-1.32,-14.71,57.39,34.24,153156.0,-46020.0,266868.0,1972.00,-32.87,37.0,X-LC,15.08,3.0,-0.30,2.14,2.63,X40,NTT,IT
75,TMPV,-1.98,-32.35,101.88,36.58,245258.0,-115109.0,240732.0,600.00,-85.81,32.0,X-LC,9.64,4.0,-0.47,1.93,0.00,XY24,NTT,AUTO
33,HCLTECH,-1.46,-12.75,41.93,23.83,88508.0,-30838.0,211086.0,1908.19,-8.19,41.0,X-LC,11.62,8.0,-0.35,1.70,2.49,X40,ATH,IT

In [22]:
# top 5 for average up
df_tmp = df_portfolio_features[(df_portfolio_features['Dev%_200'] > 5)].sort_values(by = 'CurrAlloc%', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
1,ABB,-2.69,9.0,33.55,45.57,95674.0,23549.0,285168.0,7934.0,-29.92,46.0,H-MC,13.2,125.0,0.25,2.29,26.63,AR,NTT,ELECTRICAL

In [23]:
# top 5 RSP
df_tmp = df_portfolio_features.sort_values(by = 'RSP', ascending=False)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
30,HAPPSTMNDS,-6.89,-54.79,308.87,84.85,178972.0,-70221.0,57944.0,1480.71,-46.25,43.0,H-SC,25.42,152.0,-0.39,0.47,7.30,AR,ATH,IT
24,DMART,1.36,-4.89,36.27,29.60,86099.0,-12216.0,237384.0,5391.45,-19.78,58.0,X-LC,6.78,14.0,-0.14,1.91,8.50,X40N,ATH,FMCG
52,PAGEIND,0.06,-16.99,61.57,34.11,137163.0,-45604.0,222775.0,51418.64,-40.46,49.0,X-MC,20.97,55.0,-0.33,1.79,5.38,X40,ATH,APPARELS
5,ANGELONE,-3.09,-6.56,32.89,24.18,93736.0,-20000.0,285000.0,303.00,-86.38,47.0,X-SC,10.45,97.0,-0.21,2.29,9.70,X40N,NTT,FINANCE
1,ABB,-2.69,9.00,33.55,45.57,95674.0,23549.0,285168.0,7934.00,-29.92,46.0,H-MC,13.20,125.0,0.25,2.29,26.63,AR,NTT,ELECTRICAL

In [24]:
# Top N allocation
df_tmp = df_portfolio_features.sort_values(by = 'CurrAlloc%', ascending=False)
top_n_values = [10, 25, 50]

sum_df = pd.DataFrame({
    'Top_N': top_n_values,
    'Sum_Alloc%': [df_tmp['CurrAlloc%'].head(n).sum() for n in top_n_values]
})

sum_df

   Top_N  Sum_Alloc%
0     10       21.20
1     25       46.57
2     50       78.75

In [25]:
# market-cap-wise allocation
df_tmp = df_portfolio_features[cols]
df_tmp.groupby(df_tmp['Conviction'].str[-2:])['CurrAlloc%'].sum().sort_values(ascending=False)

Conviction
SC    43.83
MC    30.20
LC    25.98
Name: CurrAlloc%, dtype: float64

In [26]:
# criteria-wise allocation
df_portfolio_features.groupby('Criteria')['CurrAlloc%'].sum().sort_values(ascending=False)

Criteria
XY24     26.99
X40      25.78
X40N     15.31
AR        9.15
XR        8.11
XY25      7.36
OX40N     6.55
SR        0.76
Name: CurrAlloc%, dtype: float64

In [27]:
# conviction-wise allocation
df_portfolio_features.groupby('Conviction')['CurrAlloc%'].sum().sort_values(ascending=False)

Conviction
X-LC    23.75
X-MC    22.69
H-SC    21.35
X-SC    12.26
M-SC     9.72
H-MC     5.14
M-MC     2.03
H-LC     1.18
M-LC     1.05
L-SC     0.50
L-MC     0.34
Name: CurrAlloc%, dtype: float64

In [28]:
# sector-wise stats
df_tmp = df_portfolio_features.groupby('Category')[['CurrAlloc%', 'Current', 'Current P/L', 'FTT Amt']].sum().sort_values(by=['Current', 'Current P/L'], ascending=False)
df_tmp['Current P/L%'] = round(df_tmp['Current P/L'] * 100 / df_tmp['Current'], 2)
df_tmp['FTT%'] = round(df_tmp['FTT Amt'] * 100 / df_tmp['Current'], 2)
cols = ['CurrAlloc%', 'Current P/L%', 'FTT%']
df_tmp[cols].sort_values(by=['CurrAlloc%'], ascending=False)

               CurrAlloc%  Current P/L%    FTT%
Category
FMCG                15.35        -30.72   77.13
FINANCE             13.00        -32.61   86.65
IT                  11.97        -51.19  128.13
MISC                 6.96        -54.81  122.06
ELECTRICAL           6.54        -18.99   64.55
PAINTS               5.26        -50.33   76.43
INSURANCE            4.80        -13.49   52.33
BANKS                4.48        -37.73  107.65
PHARMA               4.26        -10.86   45.75
AUTO                 3.65        -43.82  100.88
AC                   2.01        -27.99   62.70
HEALTHCARE           1.87        -53.53   93.60
APPARELS             1.79        -20.47   61.57
FOOTWEAR             1.77       -100.52  180.92
DURABLES             1.76        -76.60  119.56
TRAVEL               1.76       -104.48  206.87
BREWERIES            1.69        -11.46   34.61
REALTY               1.46        -21.76   41.76
REFINERIES           1.39        -16.04   45.40
CERAMICS             1.36        -80.83  135.77
CEMENT               1.21        -77.80  210.81
CABLES               1.17         -1.48  110.98
ENGINEERING          1.05        -84.37  168.70
JEWELLERY            0.97       -165.88  258.25
CHEMICALS            0.97       -117.61  295.14
ENTERTAINMENT        0.73       -115.10  243.39
TEXTILES             0.45        -65.12  112.20
HOTELS               0.33       -179.88  278.61

In [29]:
# money to be made criteria-wise
df_portfolio_features.groupby('Criteria')['FTT Amt'].agg(['sum', 'count']).sort_values(by='sum', ascending=False)

                sum  count
Criteria
XY24      4232415.0     21
X40       1964340.0     16
XR        1483018.0     12
AR        1435029.0     10
X40N      1394547.0     10
OX40N      976076.0     10
XY25       524052.0      5
SR         324359.0      2

In [30]:
# money to be made conviction-wise
df_portfolio_features.groupby('Conviction')['FTT Amt'].agg(['sum', 'count']).sort_values(by='sum', ascending=False)

                  sum  count
Conviction
H-SC        4133733.0     24
X-MC        1907828.0     15
X-LC        1817245.0     13
M-SC        1707569.0     14
X-SC        1657043.0     10
H-MC         439546.0      3
L-SC         229003.0      2
M-LC         161482.0      1
M-MC         133819.0      2
H-LC          86794.0      1
L-MC          59774.0      1

In [31]:
# money to be made criteria and conviction-wise
df_portfolio_features.groupby(['Conviction', 'Criteria'])['FTT Amt'].agg(['sum', 'count']).sort_values(by='sum', ascending=False)

                           sum  count
Conviction Criteria
H-SC       XY24      1419983.0      6
           AR        1021347.0      5
M-SC       XY24       983611.0      6
X-LC       X40        977693.0      7
H-SC       XR         950162.0      7
X-SC       XY24       885166.0      4
X-MC       X40        751586.0      7
           X40N       589191.0      4
X-SC       X40N       536816.0      4
M-SC       OX40N      442223.0      5
H-SC       OX40N      417882.0      4
X-LC       XY24       406180.0      2
H-SC       SR         324359.0      2
X-MC       XY24       285164.0      2
           XY25       281887.0      2
X-LC       X40N       268540.0      2
H-MC       XY24       252311.0      1
X-SC       X40        235061.0      2
M-SC       XR         198568.0      2
H-MC       AR         187235.0      2
X-LC       XY25       164832.0      2
M-LC       XR         161482.0      1
L-SC       OX40N      115971.0      1
           XR         113032.0      1
H-LC       AR          86794.0      1
M-SC       AR          83167.0      1
M-MC       XY25        77333.0      1
L-MC       XR          59774.0      1
M-MC       AR          56486.0      1

In [32]:
# notebook execution time

end_time = time.time()
execution_time = round(end_time - start_time, 0)
print(f"Notebook execution time: {execution_time} seconds")

Notebook execution time: 22.0 seconds