<a href="https://colab.research.google.com/github/ankit-rathi/Quantvesting_v2/blob/main/myStocks_Portfolio_Analysis.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
'''
!pip install pandas==2.2.2 -qq
!pip install pyxirr -qq
!pip install ta -qq
!pip install yfinance==0.2.59 -qq
'''

'\n!pip install pandas==2.2.2 -qq\n!pip install pyxirr -qq\n!pip install ta -qq\n!pip install yfinance==0.2.59 -qq\n'

In [2]:
# import libraries

import numpy as np
import pandas as pd
import datetime
import warnings
warnings.filterwarnings('ignore')
import yfinance as yfin
import ta
import matplotlib.pyplot as plt
import requests

In [3]:
# notebook start time
import time
import datetime
import pytz

start_time = time.time()

# function to print date timestamp
def print_date_time():
  tz_NY = pytz.timezone('Asia/Kolkata')
  datetime_NY = datetime.datetime.now(tz_NY)
  print("Run date time (IST):", datetime_NY.strftime("%Y-%m-%d %H:%M:%S"))

In [4]:
# function to get booked and reserved amount
def get_amt():
  # fetch the JSON data from the URL
  url = "https://raw.githubusercontent.com/ankit-rathi/Tradevesting_v1/main/data/myPortfolioAmts.json"
  response = requests.get(url)
  pf_amts = response.json()  # parse the JSON data

  # extract values from the JSON
  py_booked_amt_dm = pf_amts["py_booked_amt_dm"]
  py_booked_amt_sv = pf_amts["py_booked_amt_sv"]
  cy_booked_amt_dm = pf_amts["cy_booked_amt_dm"]
  cy_booked_amt_sv = pf_amts["cy_booked_amt_sv"]
  reserve_amt_dm = pf_amts["reserve_amt_dm"]
  reserve_amt_sv = pf_amts["reserve_amt_sv"]

  # perform calculations
  py_booked_amt = py_booked_amt_dm + py_booked_amt_sv
  cy_booked_amt = cy_booked_amt_dm + cy_booked_amt_sv
  reserve_amt = reserve_amt_dm + reserve_amt_sv
  total_booked_amt = py_booked_amt + cy_booked_amt

  return total_booked_amt, reserve_amt, cy_booked_amt, py_booked_amt

gen_output = 0

In [5]:
# function to format the amount
def format_amt(number):
    abs_number = abs(number)

    if abs_number >= 1_00_00_000:  # Crores
        formatted_amt = f"{number / 1_00_00_000:.2f} C"
    elif abs_number >= 1_00_000:  # Lakhs
        formatted_amt = f"{number / 1_00_000:.2f} L"
    elif abs_number >= 1_000:  # Thousands
        formatted_amt = f"{number / 1_000:.2f} K"
    else:
        formatted_amt = f"{number:.2f}"

    return formatted_amt

# function to set start and end date
def get_start_end_date():
  start_date = (datetime.date.today() + datetime.timedelta(days=-365)).strftime('%Y-%m-%d')
  end_date = (datetime.date.today() + datetime.timedelta(days=1)).strftime('%Y-%m-%d')
  return start_date, end_date

# function to fetch my portfolio csv
def get_mypfs_df():
  mypfs_df = pd.read_csv('https://raw.githubusercontent.com/ankit-rathi/Tradevesting_v1/main/data/myPortfolioStocks.csv')
  return mypfs_df

# function to fetch my prospects csv
def get_mypps_df():
  mypps_df = pd.read_csv('https://raw.githubusercontent.com/ankit-rathi/Tradevesting_v1/main/data/myProspectsScrips.csv')
  return mypps_df

# function to fetch screener data
def get_myscreen_df():
  myscreen_df = pd.read_csv('https://raw.githubusercontent.com/ankit-rathi/Tradevesting_v1/main/data/myScreenerDB.csv')
  return myscreen_df

# function to fetch momentum data
def get_myinvmt_df():
  myinvmt_df = pd.read_csv('https://raw.githubusercontent.com/ankit-rathi/Tradevesting_v1/main/data/myInvestments.csv')
  return myinvmt_df

# function to get the stock ids
def get_stock_ids(df_pf):
  stock_n100 = df_pf['Symbol'].unique()

  exclude = ['CADILAHC','MMTC', 'MASFIN']

  stock_ids = df_pf[~df_pf['Symbol'].isin(exclude) ]['Symbol'].unique()

  #mypf = mypf[mypf.Forecast.notnull()]
  #stock_ids = mypf['Symbol'].unique()

  #stock_ids.sort()
  return stock_ids

# get features from screener data
def get_screener_features():
  myscreen_df = get_myscreen_df()
  cols = ['Symbol', 'EPS', 'MedPE', 'ROCE%', 'ROE%', 'CapType']
  return myscreen_df[cols]

# get relative strength
def get_relative_strength(stock_list):

    # Dictionary to store stock tickers and their corresponding percentage price change
    stock_changes = {}

    # Loop through each stock and fetch its price data
    for stock in stock_list:
        try:
            # Download the stock data for the given date range
            stock_data = yfin.Ticker(stock + '.NS').history(period='1mo', interval='1d')[map(str.title, ['open', 'close', 'low', 'high', 'volume'])]

            # Calculate the percentage change for the stock
            if len(stock_data) > 0:
                start_price = stock_data['Close'].iloc[0]
                end_price = stock_data['Close'].iloc[-1]
                percent_change = round(((end_price - start_price) / start_price) * 100, 2)
                stock_changes[stock] = percent_change
            else:
                stock_changes[stock] = np.nan  # If no data is available, set to NaN

        except Exception as e:
            print(f"Error fetching data for {stock}: {e}")
            stock_changes[stock] = np.nan

    # Create a DataFrame with stock tickers and their percentage changes
    df = pd.DataFrame(list(stock_changes.items()), columns=['Symbol', 'Percent_Change'])

    # Drop any stocks with missing data (NaN values)
    df = df.dropna()

    # Calculate the percentile rank based on percentage change
    df['RSP'] = round(df['Percent_Change'].rank(pct=True) * 100, 2)
    cols = ['Symbol', 'RSP']
    df = df[cols]
    # Sort by percentile rank (optional)
    df = df.sort_values(by='RSP', ascending=False).reset_index(drop=True)

    return df

In [6]:
# function to get stock technicals
def stock_prec_dev(stock_symbol):
    #stock_symbol = 'ULTRACEMCO.NS'
    short_window = 20
    mid_window = 50
    long_window = 200
    moving_avg = 'SMA'

    start = datetime.datetime(*map(int, start_date.split('-')))
    end = datetime.datetime(*map(int, end_date.split('-')))

    stock_df = yfin.Ticker(stock_symbol + '.NS').history(period='max', interval='1d')[map(str.title, ['open', 'close', 'low', 'high', 'volume'])]

    stock_df['Max'] = round(max(stock_df['Close']),2)
    stock_df = stock_df[(stock_df.index <= end_date) & (stock_df.index >= start_date)]
    stock_df['200_SMA'] = round(stock_df['Close'].rolling(window = 200, min_periods = 1).mean(),0)
    stock_df['Dev%_200'] = round((stock_df['Close'] - stock_df['200_SMA'])*100/stock_df['200_SMA'],2)
    stock_df.dropna(axis = 0, inplace = True) # remove any null rows

    stock_df['20_SMA'] = stock_df['Close'].rolling(window=20).mean()
    stock_df['50_SMA'] = stock_df['Close'].rolling(window=50).mean()
    stock_df['Symbol'] = stock_symbol

    stock_df['Close'] = round(stock_df['Close'],2)
    stock_df['Min'] = round(min(stock_df['Close']),2)
    stock_df['RSI_14'] = ta.momentum.RSIIndicator(close=stock_df['Close'], window=14).rsi()
    stock_df['RSI_14'] = round(stock_df['RSI_14'],0)
    stock_df['Prev_Close'] = stock_df['Close'].shift(1)
    stock_df.drop(['Open', 'Low', 'High', 'Volume'], axis=1, inplace=True)
    stock_df = stock_df.tail(1)

    max_SMA = max(stock_df['20_SMA'].item(), stock_df['50_SMA'].item(), stock_df['200_SMA'].item())
    min_SMA = min(stock_df['20_SMA'].item(), stock_df['50_SMA'].item(), stock_df['200_SMA'].item())
    ABS_Spread = max_SMA - min_SMA
    stock_df['Spread%'] = round((ABS_Spread / stock_df['200_SMA'].item()) * 100,2)

    return stock_df

# function to compute stock attributes
def get_common_features(stock_ids, df_mypf):

  df_prec_dev = pd.DataFrame()
  df_tmp = get_screener_features()
  df_rs = get_relative_strength(stock_ids)

  for stock_id in stock_ids:
      tmp = stock_prec_dev(stock_id)
      tmp = tmp.reset_index()
      df_prec_dev = pd.concat([df_prec_dev, tmp], ignore_index = True)
  df_prec_dev = pd.merge(df_prec_dev, df_mypf, on= 'Symbol')
  df_prec_dev = pd.merge(df_prec_dev, df_tmp, on= 'Symbol', how='left')
  df_prec_dev = pd.merge(df_prec_dev, df_rs, on= 'Symbol', how='left')
  #print(df_prec_dev.columns)
  df_prec_dev['Curr_PE'] = round(df_prec_dev['Close']/df_prec_dev['EPS'],1)
  df_prec_dev['Dev%_PE'] = round((df_prec_dev['Curr_PE'] - df_prec_dev['MedPE'])*100/df_prec_dev['MedPE'],2)
  df_prec_dev['Conviction'] = df_prec_dev['Conviction'] + '-' + df_prec_dev['CapType']
  return df_prec_dev

# function to arrange stock features
def arrange_features(df_stocks, common_cols, diff_cols):
  df_stocks_common = df_stocks[common_cols].drop_duplicates()
  df_stocks_diff = df_stocks[diff_cols]
  df_stocks_diff['Investment'] = df_stocks_diff['AvgCost'] * df_stocks_diff['Shares']
  df_stocks_diff = df_stocks_diff.groupby(['Symbol'])[['Shares', 'Investment']].aggregate(['sum']).reset_index()
  df_stocks_diff.columns = ['Symbol', 'Shares', 'Investment']
  df_stocks_diff['AvgCost'] = round(df_stocks_diff['Investment']/df_stocks_diff['Shares'],2)
  df_stocks = pd.merge(df_stocks_diff, df_stocks_common, on='Symbol')
  return df_stocks

# plot fact distribution across dimension
def plot_pie_chart(df, dimension, fact):
  # grouping the data by category and calculating the sum of fact for each type
  grouped_data = df.groupby(dimension)[fact].sum()

  # sorting the grouped data in descending order
  grouped_data = grouped_data.sort_values(ascending=False)

  # creating a pie chart
  grouped_data.plot.pie(autopct='%1.1f%%', startangle=90, figsize=(6, 6))

  # adding a title and displaying the plot
  plt.title(f'{dimension} {fact} Distribution')
  plt.ylabel('')  # To hide the y-label
  plt.show()

In [7]:
# function to get portfolio features

def get_portfolio_features(df_common_features):

  print_date_time()
  print('-------------------')

  #df_common_features["Target"] = df_common_features["Target"].fillna(df_common_features["Max"])
  df_common_features['NTT'] = np.where(df_common_features['Strategy']== 'NTT', df_common_features["Target"], df_common_features['Max'])
  df_common_features['LTT'] = np.where(df_common_features['Strategy']== 'BTT', df_common_features["Target"], df_common_features['Max'])
  df_common_features['BOL'] = df_common_features['Min']

  tmp_df = df_common_features[df_common_features['Symbol'].isin(mypf_df[mypf_df['InPortfolio'] != 'NA'].Symbol.values)]
  print('qualified stocks: '+str(len(tmp_df['Symbol'].unique())))
  tmp_df1 = tmp_df[tmp_df['LatestQtr'] == 1]
  print('with latest results: '+str(len(tmp_df1['Symbol'].unique())))
  tmp_df1 = tmp_df1[tmp_df1['StarStock'] == 1]
  print('still star stocks: '+str(len(tmp_df1['Symbol'].unique())))
  tmp_df['Investment'] = tmp_df['AvgCost'] * tmp_df['Shares']
  tmp_df['Current'] = round(tmp_df['Close'] * tmp_df['Shares'],0)
  tmp_df['Previous'] = tmp_df['Prev_Close'] * tmp_df['Shares']
  tmp_df['EstimatedST'] = tmp_df['NTT'] * tmp_df['Shares']
  tmp_df['EstimatedLT'] = tmp_df['LTT'] * tmp_df['Shares']
  tmp_df['Current P/L'] = round((tmp_df['Current'] - tmp_df['Investment']),0)
  tmp_df['Today P/L%'] = round((tmp_df['Current'] - tmp_df['Previous'])*100/tmp_df['Previous'],2)
  tmp_df['Current P/L%'] = round((tmp_df['Current'] - tmp_df['Investment'])*100/tmp_df['Investment'],2)
  tmp_df['EstimatedST P/L%'] = round((tmp_df['EstimatedST'] - tmp_df['Investment'])*100/tmp_df['Investment'],2)
  tmp_df['EstimatedLT P/L%'] = round((tmp_df['EstimatedLT'] - tmp_df['Investment'])*100/tmp_df['Investment'],2)
  tmp_df['NTT%'] = round((tmp_df['NTT'] - tmp_df['Close'])*100/tmp_df['Close'],2)
  tmp_df['LTT%'] = round((tmp_df['LTT'] - tmp_df['Close'])*100/tmp_df['Close'],2)
  tmp_df['Gained%'] = round((tmp_df['Close'] - tmp_df['BOL'])*100/tmp_df['BOL'],2)
  investment = round(sum(tmp_df['AvgCost']*tmp_df['Shares']),0)
  current = round(sum(tmp_df['Close']*tmp_df['Shares']),0)
  tmp_df['InitAlloc%'] = round(tmp_df['Investment']*100/investment,2)
  tmp_df['CurrAlloc%'] = round(tmp_df['Current']*100/current,2)
  tmp_df['FTT'] = tmp_df['LTT']
  tmp_df.loc[tmp_df['Strategy'] == 'NTT', 'FTT'] = tmp_df['NTT']
  tmp_df['FTT%'] = tmp_df['LTT%']
  tmp_df.loc[tmp_df['Strategy'] == 'NTT', 'FTT%'] = tmp_df['NTT%']
  tmp_df['FTT Amt'] = round(tmp_df['FTT%'] * tmp_df['Current']/100,0)
  tmp_df['OTT%'] = round((tmp_df['FTT'] - tmp_df['AvgCost'])*100/tmp_df['AvgCost'],2)
  tmp_df['RRR Ind'] = round(tmp_df['Current P/L']/tmp_df['FTT Amt'],2)
  tmp_df['Risk Ind'] = round(tmp_df['Current P/L%']*tmp_df['CurrAlloc%'],0)

  return tmp_df

# function to print portfolio features
def print_portfolio_stats(df_portfolio_features, myinvmt_df):
  from pyxirr import xirr

  total_booked_amt, reserve_amt, cy_booked_amt, py_booked_amt = get_amt()

  dates = myinvmt_df['Date'].values
  dates = np.append(dates, datetime.date.today().strftime('%d-%b-%y'))
  investment = myinvmt_df['Investment'].values
  dates= pd.to_datetime(dates)

  current = round(sum(df_portfolio_features['Close']*df_portfolio_features['Shares']),0) + reserve_amt
  investment_xirr = np.append(investment, current)
  cagr = round(xirr(pd.DataFrame({"dates": dates, "amounts": investment_xirr}))*100,2)

  investment = -sum(investment)
  invested = round(sum(df_portfolio_features['AvgCost']*df_portfolio_features['Shares']),0) + reserve_amt
  previous = round(sum(df_portfolio_features['Prev_Close']*df_portfolio_features['Shares']),0) + reserve_amt
  cy_invested = investment + py_booked_amt

  today_pnl_amount = current-previous
  today_pnl_percentage = round((current-previous)*100/previous,2)

  curr_pnl_amount = current-invested
  curr_pnl_percentage = round((curr_pnl_amount)*100/(cy_invested),2)

  cy_pnl_amount = cy_booked_amt + curr_pnl_amount
  cy_pnl_percentage = round((cy_pnl_amount)*100/cy_invested,2)

  overall_pnl_amount = total_booked_amt + curr_pnl_amount
  overall_pnl_percentage = round((overall_pnl_amount)*100/investment,2)

  estimate_st = round(sum(df_portfolio_features['FTT']*df_portfolio_features['Shares']),0)  + reserve_amt
  est_st_pnl_amount = estimate_st-current
  est_st_pnl_percentage = round((est_st_pnl_amount)*100/current,2)

  estimate_lt = round(sum(df_portfolio_features['LTT']*df_portfolio_features['Shares']),0)  + reserve_amt
  est_lt_pnl_amount = estimate_lt-current
  est_lt_pnl_percentage = round((est_lt_pnl_amount)*100/current,2)

  total_profit = round(sum(df_portfolio_features[df_portfolio_features['Current P/L%'] > 0]['Current']) - sum(df_portfolio_features[df_portfolio_features['Current P/L%'] > 0]['Investment']),0)
  total_loss = round(sum(df_portfolio_features[df_portfolio_features['Current P/L%'] < 0]['Current']) - sum(df_portfolio_features[df_portfolio_features['Current P/L%'] < 0]['Investment']),0)

  cy_booked_percentage = round((cy_booked_amt)*100/current,2)
  py_booked_percentage = round((py_booked_amt)*100/investment,2)
  total_booked_percentage = round((total_booked_amt)*100/investment,2)

  print('-------------------')
  print('Initial Investment: ', format_amt(investment))
  print('CY Investment: ', format_amt(cy_invested))
  print('Reserve: ', format_amt(reserve_amt))
  print('Current: ',  format_amt(current))
  print('-------------------')
  print('Today PnL: '+ '{} ({}%)'.format(format_amt(today_pnl_amount), today_pnl_percentage))
  print('Current PnL: '+ '{} ({}%)'.format(format_amt(curr_pnl_amount), curr_pnl_percentage))
  print('CY Booked + Current PnL: '+ '{} ({}%)'.format(format_amt(cy_pnl_amount), cy_pnl_percentage))
  print('-------------------')
  print('Total profit: ', format_amt(total_profit))
  print('Total loss: ', format_amt(total_loss))
  print('-------------------')
  print('Total Booked + Current PnL: '+ '{} ({}%)'.format(format_amt(overall_pnl_amount), overall_pnl_percentage))
  print('Total Booked PnL: '+ '{} ({}%)'.format(format_amt(total_booked_amt), total_booked_percentage))
  print('Curr Year Booked PnL: '+ '{} ({}%)'.format(format_amt(cy_booked_amt), cy_booked_percentage))
  print('Prev Year Booked PnL: '+ '{} ({}%)'.format(format_amt(py_booked_amt), py_booked_percentage))
  print('===================')
  print('Est FTT: ',  format_amt(estimate_st))
  print('Est FTT PnL: '+ '{} ({}%)'.format(format_amt(est_st_pnl_amount), est_st_pnl_percentage))

  print('===================')
  print('Deployed: ', format_amt(investment))

  print('Current: ', format_amt(current))

  print('CAGR/XIRR %: '+'{}%'.format(cagr))

In [8]:
# get start and end date
start_date, end_date = get_start_end_date()

# get portfolio and prospects data
mypfs_df = get_mypfs_df()
mypps_df = get_mypps_df()
myinvmt_df = get_myinvmt_df()

# merge above datasets
mypf_df = pd.merge(mypfs_df, mypps_df, on="Symbol")

# seggregate dm and sv portfolio
dm_pf = mypf_df[mypf_df['InPortfolio'] == 'DM']
sv_pf = mypf_df[mypf_df['InPortfolio'] == 'SV']

# build portfolio stock dataframe
dm_stocks = get_stock_ids(dm_pf)
sv_stocks = get_stock_ids(sv_pf)
df_stocks = pd.concat([dm_pf,sv_pf], ignore_index = True)

# arrange common and diff stock features
common_cols = ['Symbol', 'Target', 'Criteria', 'Strategy', 'CumlRnk', 'LatestQtr', 'StarStock', 'Conviction', 'Category', 'InFolio', 'XIRR', 'MBQ']
diff_cols = ['Symbol', 'AvgCost', 'Shares']
df_stocks = arrange_features(df_stocks, common_cols, diff_cols)

# get common features
stock_ids = df_stocks['Symbol'].values
df_common_features = get_common_features(stock_ids, df_stocks)

df_common_features.reset_index(drop=True, inplace=True)
df_common_features.drop(['Date'], axis=1, inplace=True)
# get and print portfolio features
df_portfolio_features = get_portfolio_features(df_common_features)

print_portfolio_stats(df_portfolio_features, myinvmt_df)

df = df_portfolio_features
#plot_pie_chart(df, 'CapType', 'Current')
list_ox40n = list(df[df['MBQ'].str.contains('OX40N', na=False)]['Symbol'].values)

Run date time (IST): 2026-03-17 12:15:25
-------------------
qualified stocks: 86
with latest results: 26
still star stocks: 16
-------------------
Initial Investment:  1.36 C
CY Investment:  1.62 C
Reserve:  1.61 K
Current:  1.32 C
-------------------
Today PnL: -1.12 L (-0.84%)
Current PnL: -45.26 L (-27.85%)
CY Booked + Current PnL: -29.37 L (-18.08%)
-------------------
Total profit:  67.08 K
Total loss:  -45.93 L
-------------------
Total Booked + Current PnL: -2.39 L (-1.76%)
Total Booked PnL: 42.87 L (31.64%)
Curr Year Booked PnL: 15.89 L (12.05%)
Prev Year Booked PnL: 26.98 L (19.91%)
===================
Est FTT:  2.48 C
Est FTT PnL: 1.16 C (87.98%)
===================
Deployed:  1.36 C
Current:  1.32 C
CAGR/XIRR %: -1.35%

In [9]:
# top 5 near their targets
cols = ['Symbol', 'Today P/L%', 'Current P/L%', 'FTT%', 'OTT%', 'FTT Amt', 'Current P/L', 'Current', 'FTT', 'Dev%_PE', 'RSI_14','Conviction', 'Spread%',  'CumlRnk', 'RRR Ind', 'CurrAlloc%', 'Gained%', 'Criteria', 'Strategy', 'Category']
df_tmp = df_portfolio_features[~df_portfolio_features['Symbol'].isin(['ENRIN','BLUSPRING','DIGITIDE'])]
df_tmp = df_tmp.sort_values(by = 'FTT Amt', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
50,MASFIN,-2.02,-9.52,34.36,21.57,30460.0,-9330.0,88650.0,397.04,-21.86,35.0,H-SC,2.96,167.0,-0.31,0.67,22.94,XR,ATH,FINANCE
77,TTKPRESTIG,-9.31,-36.10,56.65,0.09,36479.0,-36384.0,64393.0,770.00,49.41,42.0,M-SC,15.97,250.0,-1.00,0.49,8.80,OX40N,NTT,DURABLES
37,ICICIGI,0.09,-2.60,22.53,19.34,43911.0,-5207.0,194902.0,2252.93,-18.12,39.0,X-MC,2.03,66.0,-0.12,1.48,7.74,X40,ATH,INSURANCE
2,ABBOTINDIA,-1.56,-10.97,32.61,18.07,51928.0,-19615.0,159240.0,35195.00,-24.24,44.0,X-MC,10.95,58.0,-0.38,1.21,0.95,X40,ATH,PHARMA
67,SONACOMS,3.08,-13.33,60.48,39.09,53026.0,-13484.0,87675.0,804.02,-31.27,46.0,M-MC,9.29,193.0,-0.25,0.66,24.03,AR,ATH,AUTO

In [10]:
# top 5 today
df_tmp = df_portfolio_features.sort_values(by = 'Today P/L%', ascending=False)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
67,SONACOMS,3.08,-13.33,60.48,39.09,53026.0,-13484.0,87675.0,804.02,-31.27,46.0,M-MC,9.29,193.0,-0.25,0.66,24.03,AR,ATH,AUTO
34,HDFCBANK,2.89,0.56,27.65,28.37,65312.0,1324.0,236209.0,1073.00,-14.61,35.0,X-LC,8.85,26.0,0.02,1.79,2.89,X40,BTT,BANKS
38,ICICIPRULI,2.72,-0.78,31.75,30.73,62062.0,-1535.0,195470.0,790.00,-27.45,36.0,X-MC,2.88,78.0,-0.02,1.48,11.83,X40,ATH,INSURANCE
8,AWL,1.78,-39.41,175.63,67.02,379190.0,-140406.0,215903.0,485.00,-67.43,26.0,X-SC,24.28,81.0,-0.37,1.64,1.78,XY24,NTT,FMCG
45,ITC,1.74,-19.22,47.38,19.06,130202.0,-65363.0,274803.0,452.00,-55.52,39.0,X-LC,17.14,1.0,-0.50,2.08,1.74,X40,NTT,FMCG

In [11]:
# bottom 5 today
df_tmp = df_portfolio_features.sort_values(by = 'Today P/L%', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
11,BANDHANBNK,-9.36,-23.48,151.45,92.42,322841.0,-65392.0,213167.0,400.0,83.19,39.0,H-SC,9.32,174.0,-0.20,1.62,17.43,XY24,NTT,BANKS
77,TTKPRESTIG,-9.31,-36.10,56.65,0.09,36479.0,-36384.0,64393.0,770.0,49.41,42.0,M-SC,15.97,250.0,-1.00,0.49,8.80,OX40N,NTT,DURABLES
55,RAJESHEXPO,-8.69,-80.59,415.42,0.07,110635.0,-110545.0,26632.0,518.0,876.01,19.0,L-SC,24.64,268.0,-1.00,0.20,0.00,OX40N,NTT,JEWELLERY
58,RELAXO,-4.87,-63.69,319.48,52.31,168385.0,-92454.0,52706.0,1176.0,-61.38,14.0,X-SC,20.95,92.0,-0.55,0.40,0.00,X40N,NTT,FOOTWEAR
29,GREENPANEL,-4.70,-49.16,181.52,43.14,168970.0,-89992.0,93086.0,537.0,108.66,33.0,M-SC,20.58,225.0,-0.53,0.71,0.00,XY24,NTT,MISC

In [12]:
# top 5 to exit based on CumlRnk
df_tmp = df_portfolio_features[~df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])]
df_tmp = df_tmp[(df_tmp['Current P/L%'] > -1) & (df_tmp['Current P/L%'] < 1)].sort_values(by = 'CumlRnk', ascending=False)
df_tmp[cols].head()

Empty DataFrame
Columns: [Symbol, Today P/L%, Current P/L%, FTT%, OTT%, FTT Amt, Current P/L, Current, FTT, Dev%_PE, RSI_14, Conviction, Spread%, CumlRnk, RRR Ind, CurrAlloc%, Gained%, Criteria, Strategy, Category]
Index: []

In [13]:
# OX40N stocks to exit
df_tmp = df_portfolio_features[(df_portfolio_features['Symbol'].isin(list_ox40n))].sort_values(by = 'Current P/L%', ascending=False)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
26,FINCABLES,-1.01,7.32,93.73,107.91,148519.0,10810.0,158454.0,1641.55,-3.60,49.0,M-SC,7.79,220.0,0.07,1.20,19.21,OX40N,ATH,CABLES
77,TTKPRESTIG,-9.31,-36.10,56.65,0.09,36479.0,-36384.0,64393.0,770.00,49.41,42.0,M-SC,15.97,250.0,-1.00,0.49,8.80,OX40N,NTT,DURABLES
66,SIS,-1.48,-36.78,91.83,21.26,64455.0,-40843.0,70189.0,528.00,1639.38,29.0,H-SC,12.28,168.0,-0.63,0.53,0.00,OX40N,NTT,MISC
70,SYMPHONY,-1.51,-39.76,65.95,-0.03,67992.0,-68044.0,103097.0,1306.00,-51.59,40.0,M-SC,14.46,205.0,-1.00,0.78,4.26,OX40N,NTT,DURABLES
18,CERA,1.25,-40.10,106.84,23.89,112568.0,-70542.0,105361.0,9475.00,-42.24,33.0,H-SC,17.64,153.0,-0.63,0.80,1.25,OX40N,NTT,CERAMICS

In [14]:
# top 5 to book for rotation
df_tmp = df_portfolio_features[(df_portfolio_features['Current P/L%'] > 20) ].sort_values(by = 'CumlRnk', ascending=False)
df_tmp[cols].head()

Empty DataFrame
Columns: [Symbol, Today P/L%, Current P/L%, FTT%, OTT%, FTT Amt, Current P/L, Current, FTT, Dev%_PE, RSI_14, Conviction, Spread%, CumlRnk, RRR Ind, CurrAlloc%, Gained%, Criteria, Strategy, Category]
Index: []

In [15]:
# top 5 to monitor for exit
df_tmp = df_portfolio_features[~df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])]
df_tmp = df_tmp[(df_tmp['Current P/L%'] > 0) ].sort_values(by = 'Dev%_PE', ascending=False)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
26,FINCABLES,-1.01,7.32,93.73,107.91,148519.0,10810.0,158454.0,1641.55,-3.60,49.0,M-SC,7.79,220.0,0.07,1.20,19.21,OX40N,ATH,CABLES
1,ABB,-2.90,13.88,27.82,45.57,82886.0,36317.0,297936.0,7934.00,-26.78,59.0,H-MC,11.44,125.0,0.44,2.26,32.30,AR,NTT,ELECTRICAL

In [16]:
# top 5 to book for rotation from weak conviction
df_tmp = df_portfolio_features[~df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])]
df_tmp = df_tmp[~df_tmp['Criteria'].isin(['XY25','XY24','X40', 'X40N'])].sort_values(by = 'RRR Ind', ascending=False)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
1,ABB,-2.90,13.88,27.82,45.57,82886.0,36317.0,297936.0,7934.00,-26.78,59.0,H-MC,11.44,125.0,0.44,2.26,32.30,AR,NTT,ELECTRICAL
26,FINCABLES,-1.01,7.32,93.73,107.91,148519.0,10810.0,158454.0,1641.55,-3.60,49.0,M-SC,7.79,220.0,0.07,1.20,19.21,OX40N,ATH,CABLES
40,INDIAMART,-1.09,-10.67,131.40,106.72,144779.0,-13154.0,110182.0,4810.62,-59.77,38.0,H-SC,9.84,140.0,-0.09,0.84,10.22,AR,ATH,MISC
85,ZYDUSLIFE,-1.37,-5.78,43.95,35.63,86785.0,-12110.0,197464.0,1286.17,-18.02,44.0,H-MC,5.08,120.0,-0.14,1.50,9.93,AR,ATH,PHARMA
84,WIPRO,-3.62,-21.89,120.55,72.27,159547.0,-37099.0,132349.0,420.00,-29.71,25.0,M-LC,15.63,98.0,-0.23,1.00,0.00,XR,NTT,IT

In [17]:
# top 5 to accumulate based on lowest RSI_14
df_tmp = df_portfolio_features[df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])].sort_values(by = 'RSI_14', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
58,RELAXO,-4.87,-63.69,319.48,52.31,168385.0,-92454.0,52706.0,1176.00,-61.38,14.0,X-SC,20.95,92.0,-0.55,0.40,0.0,X40N,NTT,FOOTWEAR
12,BATAINDIA,-3.30,-56.37,209.92,35.20,117834.0,-72537.0,56133.0,2096.00,-26.35,16.0,X-SC,27.52,91.0,-0.62,0.43,0.0,X40,NTT,FOOTWEAR
53,PGHH,-4.49,-24.69,75.29,32.01,121066.0,-52720.0,160800.0,17616.87,-49.01,16.0,X-MC,12.41,57.0,-0.44,1.22,0.0,X40,ATH,FMCG
3,ACC,-0.17,-38.50,184.26,74.81,303830.0,-103236.0,164892.0,3906.00,-56.56,17.0,X-SC,14.12,85.0,-0.34,1.25,0.0,XY24,BTT,CEMENT
73,TCS,-0.97,-29.93,80.63,26.57,261751.0,-138641.0,324632.0,4311.59,-40.68,18.0,X-LC,15.22,2.0,-0.53,2.46,0.0,X40,ATH,IT

In [18]:
# top 5 to accumulate based on Spread and CumlRnk
df_tmp = df_portfolio_features[df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])]
df_tmp = df_tmp[(df_tmp['CumlRnk'] < 100)].sort_values(by = 'Spread%', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
78,UNITDSPR,-0.17,-3.39,25.01,20.77,56572.0,-7947.0,226197.0,1644.00,-14.33,41.0,X-MC,0.93,64.0,-0.14,1.72,3.09,X40N,NTT,BREWERIES
37,ICICIGI,0.09,-2.60,22.53,19.34,43911.0,-5207.0,194902.0,2252.93,-18.12,39.0,X-MC,2.03,66.0,-0.12,1.48,7.74,X40,ATH,INSURANCE
21,DABUR,0.20,-11.16,61.75,43.70,136087.0,-27684.0,220384.0,735.00,-19.28,29.0,X-MC,2.37,70.0,-0.20,1.67,2.21,XY24,BTT,FMCG
38,ICICIPRULI,2.72,-0.78,31.75,30.73,62062.0,-1535.0,195470.0,790.00,-27.45,36.0,X-MC,2.88,78.0,-0.02,1.48,11.83,X40,ATH,INSURANCE
75,TMPV,0.02,-28.42,90.81,36.58,231297.0,-101137.0,254704.0,600.00,-84.72,29.0,X-LC,2.98,4.0,-0.44,1.93,0.11,XY24,NTT,AUTO

In [19]:
# top 5 to accumulate based on lowest Gained%
df_tmp = df_portfolio_features[df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])].sort_values(by = 'Gained%', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
3,ACC,-0.17,-38.50,184.26,74.81,303830.0,-103236.0,164892.0,3906.00,-56.56,17.0,X-SC,14.12,85.0,-0.34,1.25,0.0,XY24,BTT,CEMENT
9,BAJAJHFL,-0.97,-27.33,123.11,62.13,244266.0,-74633.0,198413.0,181.50,-40.19,25.0,X-MC,19.05,60.0,-0.31,1.50,0.0,X40N,ATH,FINANCE
12,BATAINDIA,-3.30,-56.37,209.92,35.20,117834.0,-72537.0,56133.0,2096.00,-26.35,16.0,X-SC,27.52,91.0,-0.62,0.43,0.0,X40,NTT,FOOTWEAR
20,COLPAL,-0.42,-26.00,91.22,41.51,177788.0,-68465.0,194900.0,3726.84,-10.56,30.0,X-MC,4.15,62.0,-0.39,1.48,0.0,XY25,ATH,FMCG
54,QUESS,-3.36,-27.98,141.44,73.90,108791.0,-29876.0,76917.0,424.00,-61.43,30.0,X-SC,18.80,80.0,-0.27,0.58,0.0,XY24,NTT,MISC

In [20]:
# top 5 to accumulate based on lowest CurrAlloc%
df_tmp = df_portfolio_features[df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])].sort_values(by = 'CurrAlloc%', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
58,RELAXO,-4.87,-63.69,319.48,52.31,168385.0,-92454.0,52706.0,1176.00,-61.38,14.0,X-SC,20.95,92.0,-0.55,0.40,0.00,X40N,NTT,FOOTWEAR
12,BATAINDIA,-3.30,-56.37,209.92,35.20,117834.0,-72537.0,56133.0,2096.00,-26.35,16.0,X-SC,27.52,91.0,-0.62,0.43,0.00,X40,NTT,FOOTWEAR
54,QUESS,-3.36,-27.98,141.44,73.90,108791.0,-29876.0,76917.0,424.00,-61.43,30.0,X-SC,18.80,80.0,-0.27,0.58,0.00,XY24,NTT,MISC
36,HONAUT,-2.11,-23.73,98.39,51.31,144707.0,-45763.0,147075.0,58357.33,-36.56,33.0,X-SC,14.12,90.0,-0.32,1.12,0.00,X40N,ATH,ELECTRICAL
51,MEDANTA,-3.34,-11.35,43.39,27.12,67897.0,-20036.0,156481.0,1486.00,-14.08,32.0,X-SC,9.20,87.0,-0.30,1.19,0.61,XY24,NTT,HEALTHCARE

In [21]:
# top 5 to accumulate based on CumlRnk
df_tmp = df_portfolio_features.sort_values(by = 'CumlRnk', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
45,ITC,1.74,-19.22,47.38,19.06,130202.0,-65363.0,274803.0,452.00,-55.52,39.0,X-LC,17.14,1.0,-0.50,2.08,1.74,X40,NTT,FMCG
73,TCS,-0.97,-29.93,80.63,26.57,261751.0,-138641.0,324632.0,4311.59,-40.68,18.0,X-LC,15.22,2.0,-0.53,2.46,0.00,X40,ATH,IT
43,INFY,-1.15,-16.00,59.82,34.24,157220.0,-50067.0,262821.0,1972.00,-33.96,22.0,X-LC,13.48,3.0,-0.32,1.99,0.00,X40,NTT,IT
75,TMPV,0.02,-28.42,90.81,36.58,231297.0,-101137.0,254704.0,600.00,-84.72,29.0,X-LC,2.98,4.0,-0.44,1.93,0.11,XY24,NTT,AUTO
33,HCLTECH,-0.20,-14.16,44.26,23.83,91912.0,-34260.0,207664.0,1908.19,-9.84,26.0,X-LC,10.15,8.0,-0.37,1.58,0.00,X40,ATH,IT

In [22]:
# top 5 for average up
df_tmp = df_portfolio_features[(df_portfolio_features['Dev%_200'] > 5)].sort_values(by = 'CurrAlloc%', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
67,SONACOMS,3.08,-13.33,60.48,39.09,53026.0,-13484.0,87675.0,804.02,-31.27,46.0,M-MC,9.29,193.0,-0.25,0.66,24.03,AR,ATH,AUTO
1,ABB,-2.90,13.88,27.82,45.57,82886.0,36317.0,297936.0,7934.00,-26.78,59.0,H-MC,11.44,125.0,0.44,2.26,32.30,AR,NTT,ELECTRICAL

In [23]:
# top 5 RSP
df_tmp = df_portfolio_features.sort_values(by = 'RSP', ascending=False)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
1,ABB,-2.90,13.88,27.82,45.57,82886.0,36317.0,297936.0,7934.00,-26.78,59.0,H-MC,11.44,125.0,0.44,2.26,32.30,AR,NTT,ELECTRICAL
26,FINCABLES,-1.01,7.32,93.73,107.91,148519.0,10810.0,158454.0,1641.55,-3.60,49.0,M-SC,7.79,220.0,0.07,1.20,19.21,OX40N,ATH,CABLES
69,SURYODAY,-2.17,-26.46,67.30,23.03,88629.0,-47379.0,131692.0,216.00,42.54,49.0,H-SC,7.56,166.0,-0.53,1.00,30.66,XR,NTT,BANKS
2,ABBOTINDIA,-1.56,-10.97,32.61,18.07,51928.0,-19615.0,159240.0,35195.00,-24.24,44.0,X-MC,10.95,58.0,-0.38,1.21,0.95,X40,ATH,PHARMA
65,SIEMENS,-1.47,-15.08,47.81,25.51,75552.0,-28070.0,158025.0,4671.50,32.74,46.0,H-LC,3.79,51.0,-0.37,1.20,16.37,AR,ATH,ELECTRICAL

In [24]:
# Top N allocation
df_tmp = df_portfolio_features.sort_values(by = 'CurrAlloc%', ascending=False)
top_n_values = [10, 25, 50]

sum_df = pd.DataFrame({
    'Top_N': top_n_values,
    'Sum_Alloc%': [df_tmp['CurrAlloc%'].head(n).sum() for n in top_n_values]
})

sum_df

   Top_N  Sum_Alloc%
0     10       20.54
1     25       45.58
2     50       78.14

In [25]:
# market-cap-wise allocation
df_tmp = df_portfolio_features[cols]
df_tmp.groupby(df_tmp['Conviction'].str[-2:])['CurrAlloc%'].sum().sort_values(ascending=False)

Conviction
SC    44.14
MC    30.40
LC    25.43
Name: CurrAlloc%, dtype: float64

In [26]:
# criteria-wise allocation
df_portfolio_features.groupby('Criteria')['CurrAlloc%'].sum().sort_values(ascending=False)

Criteria
XY24     26.99
X40      25.68
X40N     14.98
AR        9.18
XR        8.16
XY25      7.46
OX40N     6.77
SR        0.75
Name: CurrAlloc%, dtype: float64

In [27]:
# conviction-wise allocation
df_portfolio_features.groupby('Conviction')['CurrAlloc%'].sum().sort_values(ascending=False)

Conviction
X-LC    23.23
X-MC    22.95
H-SC    21.46
X-SC    12.07
M-SC    10.05
H-MC     5.05
M-MC     2.05
H-LC     1.20
M-LC     1.00
L-SC     0.56
L-MC     0.35
Name: CurrAlloc%, dtype: float64

In [28]:
# sector-wise stats
df_tmp = df_portfolio_features.groupby('Category')[['CurrAlloc%', 'Current', 'Current P/L', 'FTT Amt']].sum().sort_values(by=['Current', 'Current P/L'], ascending=False)
df_tmp['Current P/L%'] = round(df_tmp['Current P/L'] * 100 / df_tmp['Current'], 2)
df_tmp['FTT%'] = round(df_tmp['FTT Amt'] * 100 / df_tmp['Current'], 2)
cols = ['CurrAlloc%', 'Current P/L%', 'FTT%']
df_tmp[cols].sort_values(by=['CurrAlloc%'], ascending=False)

               CurrAlloc%  Current P/L%    FTT%
Category
FMCG                15.23        -24.33   68.48
FINANCE             12.92        -26.06   77.43
IT                  11.55        -47.82  123.04
MISC                 6.90        -47.21  111.16
ELECTRICAL           6.66        -10.45   52.74
PAINTS               5.12        -46.09   71.46
INSURANCE            4.86         -5.75   41.94
BANKS                4.76        -22.70   84.98
PHARMA               4.18         -6.80   40.42
AUTO                 3.65        -35.74   89.60
AC                   2.14        -13.53   44.31
HEALTHCARE           1.92        -41.35   78.23
DURABLES             1.84        -59.03   97.72
FOOTWEAR             1.83        -83.07  156.48
TRAVEL               1.80        -88.38  182.71
BREWERIES            1.72         -3.51   25.01
APPARELS             1.62        -25.64   68.50
REALTY               1.45        -15.83   34.86
REFINERIES           1.36        -11.79   40.08
CERAMICS             1.36        -71.24  123.27
CEMENT               1.25        -62.61  184.26
CABLES               1.20          6.82   93.73
JEWELLERY            1.10       -121.15  197.98
ENGINEERING          1.08        -70.00  147.76
CHEMICALS            0.93       -113.83  288.29
ENTERTAINMENT        0.76        -91.90  206.35
TEXTILES             0.42        -67.34  115.05
HOTELS               0.36       -140.50  225.34

In [29]:
# money to be made criteria-wise
df_portfolio_features.groupby('Criteria')['FTT Amt'].agg(['sum', 'count']).sort_values(by='sum', ascending=False)

                sum  count
Criteria
XY24      4037804.0     21
X40       1788066.0     16
XR        1413230.0     12
AR        1361791.0     10
X40N      1324634.0     10
OX40N      899495.0     10
XY25       457391.0      5
SR         319443.0      2

In [30]:
# money to be made conviction-wise
df_portfolio_features.groupby('Conviction')['FTT Amt'].agg(['sum', 'count']).sort_values(by='sum', ascending=False)

                  sum  count
Conviction
H-SC        3962138.0     24
X-LC        1710127.0     13
X-MC        1709089.0     15
M-SC        1592672.0     14
X-SC        1591201.0     10
H-MC         412660.0      3
L-SC         217025.0      2
M-LC         159547.0      1
M-MC         115514.0      2
H-LC          75552.0      1
L-MC          56329.0      1

In [31]:
# money to be made criteria and conviction-wise
df_portfolio_features.groupby(['Conviction', 'Criteria'])['FTT Amt'].agg(['sum', 'count']).sort_values(by='sum', ascending=False)

                           sum  count
Conviction Criteria
H-SC       XY24      1363814.0      6
           AR         985589.0      5
M-SC       XY24       928187.0      6
X-LC       X40        914078.0      7
H-SC       XR         894379.0      7
X-SC       XY24       859708.0      4
X-MC       X40        668315.0      7
           X40N       532324.0      4
X-SC       X40N       525820.0      4
H-SC       OX40N      398913.0      4
M-SC       OX40N      389947.0      5
X-LC       XY24       380479.0      2
H-SC       SR         319443.0      2
X-LC       X40N       266490.0      2
X-MC       XY24       262627.0      2
           XY25       245823.0      2
H-MC       XY24       242989.0      1
X-SC       X40        205673.0      2
M-SC       XR         196585.0      2
H-MC       AR         169671.0      2
M-LC       XR         159547.0      1
X-LC       XY25       149080.0      2
L-SC       OX40N      110635.0      1
           XR         106390.0      1
M-SC       AR          77953.0      1
H-LC       AR          75552.0      1
M-MC       XY25        62488.0      1
L-MC       XR          56329.0      1
M-MC       AR          53026.0      1

In [32]:
# notebook execution time

end_time = time.time()
execution_time = round(end_time - start_time, 0)
print(f"Notebook execution time: {execution_time} seconds")

Notebook execution time: 28.0 seconds