<a href="https://colab.research.google.com/github/ankit-rathi/Quantvesting_v2/blob/main/myStocks_Portfolio_Analysis.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
'''
!pip install pandas==2.2.2 -qq
!pip install pyxirr -qq
!pip install ta -qq
!pip install yfinance==0.2.59 -qq
'''

'\n!pip install pandas==2.2.2 -qq\n!pip install pyxirr -qq\n!pip install ta -qq\n!pip install yfinance==0.2.59 -qq\n'

In [2]:
# import libraries

import numpy as np
import pandas as pd
import datetime
import warnings
warnings.filterwarnings('ignore')
import yfinance as yfin
import ta
import matplotlib.pyplot as plt
import requests

In [3]:
# notebook start time
import time
import datetime
import pytz

start_time = time.time()

# function to print date timestamp
def print_date_time():
  tz_NY = pytz.timezone('Asia/Kolkata')
  datetime_NY = datetime.datetime.now(tz_NY)
  print("Run date time (IST):", datetime_NY.strftime("%Y-%m-%d %H:%M:%S"))

In [4]:
# function to get booked and reserved amount
def get_amt():
  # fetch the JSON data from the URL
  url = "https://raw.githubusercontent.com/ankit-rathi/Tradevesting_v1/main/data/myPortfolioAmts.json"
  response = requests.get(url)
  pf_amts = response.json()  # parse the JSON data

  # extract values from the JSON
  py_booked_amt_dm = pf_amts["py_booked_amt_dm"]
  py_booked_amt_sv = pf_amts["py_booked_amt_sv"]
  cy_booked_amt_dm = pf_amts["cy_booked_amt_dm"]
  cy_booked_amt_sv = pf_amts["cy_booked_amt_sv"]
  reserve_amt_dm = pf_amts["reserve_amt_dm"]
  reserve_amt_sv = pf_amts["reserve_amt_sv"]

  # perform calculations
  py_booked_amt = py_booked_amt_dm + py_booked_amt_sv
  cy_booked_amt = cy_booked_amt_dm + cy_booked_amt_sv
  reserve_amt = reserve_amt_dm + reserve_amt_sv
  total_booked_amt = py_booked_amt + cy_booked_amt

  return total_booked_amt, reserve_amt, cy_booked_amt, py_booked_amt

gen_output = 0

In [5]:
# function to format the amount
def format_amt(number):
    abs_number = abs(number)

    if abs_number >= 1_00_00_000:  # Crores
        formatted_amt = f"{number / 1_00_00_000:.2f} C"
    elif abs_number >= 1_00_000:  # Lakhs
        formatted_amt = f"{number / 1_00_000:.2f} L"
    elif abs_number >= 1_000:  # Thousands
        formatted_amt = f"{number / 1_000:.2f} K"
    else:
        formatted_amt = f"{number:.2f}"

    return formatted_amt

# function to set start and end date
def get_start_end_date():
  start_date = (datetime.date.today() + datetime.timedelta(days=-365)).strftime('%Y-%m-%d')
  end_date = (datetime.date.today() + datetime.timedelta(days=1)).strftime('%Y-%m-%d')
  return start_date, end_date

# function to fetch my portfolio csv
def get_mypfs_df():
  mypfs_df = pd.read_csv('https://raw.githubusercontent.com/ankit-rathi/Tradevesting_v1/main/data/myPortfolioStocks.csv')
  return mypfs_df

# function to fetch my prospects csv
def get_mypps_df():
  mypps_df = pd.read_csv('https://raw.githubusercontent.com/ankit-rathi/Tradevesting_v1/main/data/myProspectsScrips.csv')
  return mypps_df

# function to fetch screener data
def get_myscreen_df():
  myscreen_df = pd.read_csv('https://raw.githubusercontent.com/ankit-rathi/Tradevesting_v1/main/data/myScreenerDB.csv')
  return myscreen_df

# function to fetch momentum data
def get_myinvmt_df():
  myinvmt_df = pd.read_csv('https://raw.githubusercontent.com/ankit-rathi/Tradevesting_v1/main/data/myInvestments.csv')
  return myinvmt_df

# function to get the stock ids
def get_stock_ids(df_pf):
  stock_n100 = df_pf['Symbol'].unique()

  exclude = ['CADILAHC','MMTC', 'MASFIN']

  stock_ids = df_pf[~df_pf['Symbol'].isin(exclude) ]['Symbol'].unique()

  #mypf = mypf[mypf.Forecast.notnull()]
  #stock_ids = mypf['Symbol'].unique()

  #stock_ids.sort()
  return stock_ids

# get features from screener data
def get_screener_features():
  myscreen_df = get_myscreen_df()
  cols = ['Symbol', 'EPS', 'MedPE', 'ROCE%', 'ROE%', 'CapType']
  return myscreen_df[cols]

# get relative strength
def get_relative_strength(stock_list):

    # Dictionary to store stock tickers and their corresponding percentage price change
    stock_changes = {}

    # Loop through each stock and fetch its price data
    for stock in stock_list:
        try:
            # Download the stock data for the given date range
            stock_data = yfin.Ticker(stock + '.NS').history(period='1mo', interval='1d')[map(str.title, ['open', 'close', 'low', 'high', 'volume'])]

            # Calculate the percentage change for the stock
            if len(stock_data) > 0:
                start_price = stock_data['Close'].iloc[0]
                end_price = stock_data['Close'].iloc[-1]
                percent_change = round(((end_price - start_price) / start_price) * 100, 2)
                stock_changes[stock] = percent_change
            else:
                stock_changes[stock] = np.nan  # If no data is available, set to NaN

        except Exception as e:
            print(f"Error fetching data for {stock}: {e}")
            stock_changes[stock] = np.nan

    # Create a DataFrame with stock tickers and their percentage changes
    df = pd.DataFrame(list(stock_changes.items()), columns=['Symbol', 'Percent_Change'])

    # Drop any stocks with missing data (NaN values)
    df = df.dropna()

    # Calculate the percentile rank based on percentage change
    df['RSP'] = round(df['Percent_Change'].rank(pct=True) * 100, 2)
    cols = ['Symbol', 'RSP']
    df = df[cols]
    # Sort by percentile rank (optional)
    df = df.sort_values(by='RSP', ascending=False).reset_index(drop=True)

    return df

In [6]:
# function to get stock technicals
def stock_prec_dev(stock_symbol):
    #stock_symbol = 'ULTRACEMCO.NS'
    short_window = 20
    mid_window = 50
    long_window = 200
    moving_avg = 'SMA'

    start = datetime.datetime(*map(int, start_date.split('-')))
    end = datetime.datetime(*map(int, end_date.split('-')))

    stock_df = yfin.Ticker(stock_symbol + '.NS').history(period='max', interval='1d')[map(str.title, ['open', 'close', 'low', 'high', 'volume'])]

    stock_df['Max'] = round(max(stock_df['Close']),2)
    stock_df = stock_df[(stock_df.index <= end_date) & (stock_df.index >= start_date)]
    stock_df['200_SMA'] = round(stock_df['Close'].rolling(window = 200, min_periods = 1).mean(),0)
    stock_df['Dev%_200'] = round((stock_df['Close'] - stock_df['200_SMA'])*100/stock_df['200_SMA'],2)
    stock_df.dropna(axis = 0, inplace = True) # remove any null rows

    stock_df['20_SMA'] = stock_df['Close'].rolling(window=20).mean()
    stock_df['50_SMA'] = stock_df['Close'].rolling(window=50).mean()
    stock_df['Symbol'] = stock_symbol

    stock_df['Close'] = round(stock_df['Close'],2)
    stock_df['Min'] = round(min(stock_df['Close']),2)
    stock_df['RSI_14'] = ta.momentum.RSIIndicator(close=stock_df['Close'], window=14).rsi()
    stock_df['RSI_14'] = round(stock_df['RSI_14'],0)
    stock_df['Prev_Close'] = stock_df['Close'].shift(1)
    stock_df.drop(['Open', 'Low', 'High', 'Volume'], axis=1, inplace=True)
    stock_df = stock_df.tail(1)

    max_SMA = max(stock_df['20_SMA'].item(), stock_df['50_SMA'].item(), stock_df['200_SMA'].item())
    min_SMA = min(stock_df['20_SMA'].item(), stock_df['50_SMA'].item(), stock_df['200_SMA'].item())
    ABS_Spread = max_SMA - min_SMA
    stock_df['Spread%'] = round((ABS_Spread / stock_df['200_SMA'].item()) * 100,2)

    return stock_df

# function to compute stock attributes
def get_common_features(stock_ids, df_mypf):

  df_prec_dev = pd.DataFrame()
  df_tmp = get_screener_features()
  df_rs = get_relative_strength(stock_ids)

  for stock_id in stock_ids:
      tmp = stock_prec_dev(stock_id)
      tmp = tmp.reset_index()
      df_prec_dev = pd.concat([df_prec_dev, tmp], ignore_index = True)
  df_prec_dev = pd.merge(df_prec_dev, df_mypf, on= 'Symbol')
  df_prec_dev = pd.merge(df_prec_dev, df_tmp, on= 'Symbol', how='left')
  df_prec_dev = pd.merge(df_prec_dev, df_rs, on= 'Symbol', how='left')
  #print(df_prec_dev.columns)
  df_prec_dev['Curr_PE'] = round(df_prec_dev['Close']/df_prec_dev['EPS'],1)
  df_prec_dev['Dev%_PE'] = round((df_prec_dev['Curr_PE'] - df_prec_dev['MedPE'])*100/df_prec_dev['MedPE'],2)
  df_prec_dev['Conviction'] = df_prec_dev['Conviction'] + '-' + df_prec_dev['CapType']
  return df_prec_dev

# function to arrange stock features
def arrange_features(df_stocks, common_cols, diff_cols):
  df_stocks_common = df_stocks[common_cols].drop_duplicates()
  df_stocks_diff = df_stocks[diff_cols]
  df_stocks_diff['Investment'] = df_stocks_diff['AvgCost'] * df_stocks_diff['Shares']
  df_stocks_diff = df_stocks_diff.groupby(['Symbol'])[['Shares', 'Investment']].aggregate(['sum']).reset_index()
  df_stocks_diff.columns = ['Symbol', 'Shares', 'Investment']
  df_stocks_diff['AvgCost'] = round(df_stocks_diff['Investment']/df_stocks_diff['Shares'],2)
  df_stocks = pd.merge(df_stocks_diff, df_stocks_common, on='Symbol')
  return df_stocks

# plot fact distribution across dimension
def plot_pie_chart(df, dimension, fact):
  # grouping the data by category and calculating the sum of fact for each type
  grouped_data = df.groupby(dimension)[fact].sum()

  # sorting the grouped data in descending order
  grouped_data = grouped_data.sort_values(ascending=False)

  # creating a pie chart
  grouped_data.plot.pie(autopct='%1.1f%%', startangle=90, figsize=(6, 6))

  # adding a title and displaying the plot
  plt.title(f'{dimension} {fact} Distribution')
  plt.ylabel('')  # To hide the y-label
  plt.show()

In [7]:
# function to get portfolio features

def get_portfolio_features(df_common_features):

  print_date_time()
  print('-------------------')

  #df_common_features["Target"] = df_common_features["Target"].fillna(df_common_features["Max"])
  df_common_features['NTT'] = np.where(df_common_features['Strategy']== 'NTT', df_common_features["Target"], df_common_features['Max'])
  df_common_features['LTT'] = np.where(df_common_features['Strategy']== 'BTT', df_common_features["Target"], df_common_features['Max'])
  df_common_features['BOL'] = df_common_features['Min']

  tmp_df = df_common_features[df_common_features['Symbol'].isin(mypf_df[mypf_df['InPortfolio'] != 'NA'].Symbol.values)]
  print('qualified stocks: '+str(len(tmp_df['Symbol'].unique())))
  tmp_df1 = tmp_df[tmp_df['LatestQtr'] == 1]
  print('with latest results: '+str(len(tmp_df1['Symbol'].unique())))
  tmp_df1 = tmp_df1[tmp_df1['StarStock'] == 1]
  print('still star stocks: '+str(len(tmp_df1['Symbol'].unique())))
  tmp_df['Investment'] = tmp_df['AvgCost'] * tmp_df['Shares']
  tmp_df['Current'] = round(tmp_df['Close'] * tmp_df['Shares'],0)
  tmp_df['Previous'] = tmp_df['Prev_Close'] * tmp_df['Shares']
  tmp_df['EstimatedST'] = tmp_df['NTT'] * tmp_df['Shares']
  tmp_df['EstimatedLT'] = tmp_df['LTT'] * tmp_df['Shares']
  tmp_df['Current P/L'] = round((tmp_df['Current'] - tmp_df['Investment']),0)
  tmp_df['Today P/L%'] = round((tmp_df['Current'] - tmp_df['Previous'])*100/tmp_df['Previous'],2)
  tmp_df['Current P/L%'] = round((tmp_df['Current'] - tmp_df['Investment'])*100/tmp_df['Investment'],2)
  tmp_df['EstimatedST P/L%'] = round((tmp_df['EstimatedST'] - tmp_df['Investment'])*100/tmp_df['Investment'],2)
  tmp_df['EstimatedLT P/L%'] = round((tmp_df['EstimatedLT'] - tmp_df['Investment'])*100/tmp_df['Investment'],2)
  tmp_df['NTT%'] = round((tmp_df['NTT'] - tmp_df['Close'])*100/tmp_df['Close'],2)
  tmp_df['LTT%'] = round((tmp_df['LTT'] - tmp_df['Close'])*100/tmp_df['Close'],2)
  tmp_df['Gained%'] = round((tmp_df['Close'] - tmp_df['BOL'])*100/tmp_df['BOL'],2)
  investment = round(sum(tmp_df['AvgCost']*tmp_df['Shares']),0)
  current = round(sum(tmp_df['Close']*tmp_df['Shares']),0)
  tmp_df['InitAlloc%'] = round(tmp_df['Investment']*100/investment,2)
  tmp_df['CurrAlloc%'] = round(tmp_df['Current']*100/current,2)
  tmp_df['FTT'] = tmp_df['LTT']
  tmp_df.loc[tmp_df['Strategy'] == 'NTT', 'FTT'] = tmp_df['NTT']
  tmp_df['FTT%'] = tmp_df['LTT%']
  tmp_df.loc[tmp_df['Strategy'] == 'NTT', 'FTT%'] = tmp_df['NTT%']
  tmp_df['FTT Amt'] = round(tmp_df['FTT%'] * tmp_df['Current']/100,0)
  tmp_df['OTT%'] = round((tmp_df['FTT'] - tmp_df['AvgCost'])*100/tmp_df['AvgCost'],2)
  tmp_df['RRR Ind'] = round(tmp_df['Current P/L']/tmp_df['FTT Amt'],2)
  tmp_df['Risk Ind'] = round(tmp_df['Current P/L%']*tmp_df['CurrAlloc%'],0)

  return tmp_df

# function to print portfolio features
def print_portfolio_stats(df_portfolio_features, myinvmt_df):
  from pyxirr import xirr

  total_booked_amt, reserve_amt, cy_booked_amt, py_booked_amt = get_amt()

  dates = myinvmt_df['Date'].values
  dates = np.append(dates, datetime.date.today().strftime('%d-%b-%y'))
  investment = myinvmt_df['Investment'].values
  dates= pd.to_datetime(dates)

  current = round(sum(df_portfolio_features['Close']*df_portfolio_features['Shares']),0) + reserve_amt
  investment_xirr = np.append(investment, current)
  cagr = round(xirr(pd.DataFrame({"dates": dates, "amounts": investment_xirr}))*100,2)

  investment = -sum(investment)
  invested = round(sum(df_portfolio_features['AvgCost']*df_portfolio_features['Shares']),0) + reserve_amt
  previous = round(sum(df_portfolio_features['Prev_Close']*df_portfolio_features['Shares']),0) + reserve_amt
  cy_invested = investment + py_booked_amt

  today_pnl_amount = current-previous
  today_pnl_percentage = round((current-previous)*100/previous,2)

  curr_pnl_amount = current-invested
  curr_pnl_percentage = round((curr_pnl_amount)*100/(cy_invested),2)

  cy_pnl_amount = cy_booked_amt + curr_pnl_amount
  cy_pnl_percentage = round((cy_pnl_amount)*100/cy_invested,2)

  overall_pnl_amount = total_booked_amt + curr_pnl_amount
  overall_pnl_percentage = round((overall_pnl_amount)*100/investment,2)

  estimate_st = round(sum(df_portfolio_features['FTT']*df_portfolio_features['Shares']),0)  + reserve_amt
  est_st_pnl_amount = estimate_st-current
  est_st_pnl_percentage = round((est_st_pnl_amount)*100/current,2)

  estimate_lt = round(sum(df_portfolio_features['LTT']*df_portfolio_features['Shares']),0)  + reserve_amt
  est_lt_pnl_amount = estimate_lt-current
  est_lt_pnl_percentage = round((est_lt_pnl_amount)*100/current,2)

  total_profit = round(sum(df_portfolio_features[df_portfolio_features['Current P/L%'] > 0]['Current']) - sum(df_portfolio_features[df_portfolio_features['Current P/L%'] > 0]['Investment']),0)
  total_loss = round(sum(df_portfolio_features[df_portfolio_features['Current P/L%'] < 0]['Current']) - sum(df_portfolio_features[df_portfolio_features['Current P/L%'] < 0]['Investment']),0)

  cy_booked_percentage = round((cy_booked_amt)*100/current,2)
  py_booked_percentage = round((py_booked_amt)*100/investment,2)
  total_booked_percentage = round((total_booked_amt)*100/investment,2)

  print('-------------------')
  print('Initial Investment: ', format_amt(investment))
  print('CY Investment: ', format_amt(cy_invested))
  print('Reserve: ', format_amt(reserve_amt))
  print('Current: ',  format_amt(current))
  print('-------------------')
  print('Today PnL: '+ '{} ({}%)'.format(format_amt(today_pnl_amount), today_pnl_percentage))
  print('Current PnL: '+ '{} ({}%)'.format(format_amt(curr_pnl_amount), curr_pnl_percentage))
  print('CY Booked + Current PnL: '+ '{} ({}%)'.format(format_amt(cy_pnl_amount), cy_pnl_percentage))
  print('-------------------')
  print('Total profit: ', format_amt(total_profit))
  print('Total loss: ', format_amt(total_loss))
  print('-------------------')
  print('Total Booked + Current PnL: '+ '{} ({}%)'.format(format_amt(overall_pnl_amount), overall_pnl_percentage))
  print('Total Booked PnL: '+ '{} ({}%)'.format(format_amt(total_booked_amt), total_booked_percentage))
  print('Curr Year Booked PnL: '+ '{} ({}%)'.format(format_amt(cy_booked_amt), cy_booked_percentage))
  print('Prev Year Booked PnL: '+ '{} ({}%)'.format(format_amt(py_booked_amt), py_booked_percentage))
  print('===================')
  print('Est FTT: ',  format_amt(estimate_st))
  print('Est FTT PnL: '+ '{} ({}%)'.format(format_amt(est_st_pnl_amount), est_st_pnl_percentage))

  print('===================')
  print('Deployed: ', format_amt(investment))

  print('Current: ', format_amt(current))

  print('CAGR/XIRR %: '+'{}%'.format(cagr))

In [8]:
# get start and end date
start_date, end_date = get_start_end_date()

# get portfolio and prospects data
mypfs_df = get_mypfs_df()
mypps_df = get_mypps_df()
myinvmt_df = get_myinvmt_df()

# merge above datasets
mypf_df = pd.merge(mypfs_df, mypps_df, on="Symbol")

# seggregate dm and sv portfolio
dm_pf = mypf_df[mypf_df['InPortfolio'] == 'DM']
sv_pf = mypf_df[mypf_df['InPortfolio'] == 'SV']

# build portfolio stock dataframe
dm_stocks = get_stock_ids(dm_pf)
sv_stocks = get_stock_ids(sv_pf)
df_stocks = pd.concat([dm_pf,sv_pf], ignore_index = True)

# arrange common and diff stock features
common_cols = ['Symbol', 'Target', 'Criteria', 'Strategy', 'CumlRnk', 'LatestQtr', 'StarStock', 'Conviction', 'Category', 'InFolio', 'XIRR', 'MBQ']
diff_cols = ['Symbol', 'AvgCost', 'Shares']
df_stocks = arrange_features(df_stocks, common_cols, diff_cols)

# get common features
stock_ids = df_stocks['Symbol'].values
df_common_features = get_common_features(stock_ids, df_stocks)

df_common_features.reset_index(drop=True, inplace=True)
df_common_features.drop(['Date'], axis=1, inplace=True)
# get and print portfolio features
df_portfolio_features = get_portfolio_features(df_common_features)

print_portfolio_stats(df_portfolio_features, myinvmt_df)

df = df_portfolio_features
#plot_pie_chart(df, 'CapType', 'Current')
list_ox40n = list(df[df['MBQ'].str.contains('OX40N', na=False)]['Symbol'].values)

Run date time (IST): 2026-04-06 15:12:45
-------------------
qualified stocks: 86
with latest results: 26
still star stocks: 16
-------------------
Initial Investment:  1.36 C
CY Investment:  1.62 C
Reserve:  1.61 K
Current:  1.31 C
-------------------
Today PnL: 1.62 L (1.26%)
Current PnL: -46.07 L (-28.36%)
CY Booked + Current PnL: -30.18 L (-18.58%)
-------------------
Total profit:  66.92 K
Total loss:  -46.74 L
-------------------
Total Booked + Current PnL: -3.20 L (-2.36%)
Total Booked PnL: 42.87 L (31.64%)
Curr Year Booked PnL: 15.89 L (12.13%)
Prev Year Booked PnL: 26.98 L (19.91%)
===================
Est FTT:  2.48 C
Est FTT PnL: 1.17 C (89.15%)
===================
Deployed:  1.36 C
Current:  1.31 C
CAGR/XIRR %: -1.61%

In [9]:
# top 5 near their targets
cols = ['Symbol', 'Today P/L%', 'Current P/L%', 'FTT%', 'OTT%', 'FTT Amt', 'Current P/L', 'Current', 'FTT', 'Dev%_PE', 'RSI_14','Conviction', 'Spread%',  'CumlRnk', 'RRR Ind', 'CurrAlloc%', 'Gained%', 'Criteria', 'Strategy', 'Category']
df_tmp = df_portfolio_features[~df_portfolio_features['Symbol'].isin(['ENRIN','BLUSPRING','DIGITIDE'])]
df_tmp = df_tmp.sort_values(by = 'FTT Amt', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
50,MASFIN,2.77,-6.98,30.69,21.57,27971.0,-6840.0,91140.0,397.04,-19.60,50.0,H-SC,4.89,167.0,-0.24,0.70,24.31,XR,ATH,FINANCE
77,TTKPRESTIG,3.27,-40.46,68.10,0.09,40863.0,-40772.0,60005.0,770.00,39.17,42.0,M-SC,22.26,250.0,-1.00,0.46,6.85,OX40N,NTT,DURABLES
24,DMART,4.53,9.62,18.23,29.60,49877.0,24000.0,273600.0,5391.45,-7.56,78.0,X-LC,6.01,14.0,0.48,2.09,25.06,X40N,ATH,FMCG
67,SONACOMS,2.42,-12.02,58.10,39.09,51707.0,-12163.0,88996.0,804.02,-30.33,52.0,M-MC,7.00,193.0,-0.24,0.68,25.90,AR,ATH,AUTO
2,ABBOTINDIA,-1.54,-13.18,35.99,18.07,55885.0,-23575.0,155280.0,35195.00,-26.09,43.0,X-MC,10.68,58.0,-0.42,1.19,1.55,X40,ATH,PHARMA

In [10]:
# top 5 today
df_tmp = df_portfolio_features.sort_values(by = 'Today P/L%', ascending=False)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
19,COFFEEDAY,8.13,-59.74,235.99,35.27,107883.0,-67834.0,45715.0,80.0,-69.82,43.0,L-SC,32.14,266.0,-0.63,0.35,12.74,XR,NTT,HOTELS
39,IEX,5.77,-14.28,73.38,48.63,125776.0,-28551.0,171403.0,219.0,-42.88,56.0,H-SC,15.84,137.0,-0.23,1.31,10.07,XR,NTT,MISC
69,SURYODAY,5.73,-24.18,62.27,23.03,84545.0,-43299.0,135772.0,216.0,46.93,56.0,H-SC,5.19,166.0,-0.51,1.04,22.85,XR,NTT,BANKS
56,RAJOOENG,5.37,-45.22,154.85,39.61,86948.0,-46350.0,56150.0,143.1,-62.94,49.0,H-SC,33.49,136.0,-0.53,0.43,20.29,AR,ATH,MISC
55,RAJESHEXPO,4.95,-82.30,465.50,0.07,112995.0,-112903.0,24274.0,518.0,790.15,33.0,L-SC,43.20,268.0,-1.00,0.19,13.96,OX40N,NTT,JEWELLERY

In [11]:
# bottom 5 today
df_tmp = df_portfolio_features.sort_values(by = 'Today P/L%', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
68,STARHEALTH,-3.38,-12.15,67.62,47.26,167005.0,-34147.0,246976.0,761.00,38.62,47.0,H-SC,0.37,173.0,-0.20,1.88,31.12,XY24,NTT,INSURANCE
59,RELIANCE,-3.34,-16.20,49.53,25.30,83407.0,-32566.0,168397.0,1952.00,-18.49,34.0,X-LC,4.01,21.0,-0.39,1.29,12.43,XY25,BTT,REFINERIES
0,5PAISA,-2.30,-46.91,112.68,12.90,130696.0,-102507.0,115989.0,593.00,70.67,43.0,H-SC,16.85,170.0,-0.78,0.89,11.93,OX40N,NTT,FINANCE
8,AWL,-2.04,-38.03,169.50,67.02,374275.0,-135498.0,220811.0,485.00,-66.62,45.0,X-SC,26.03,81.0,-0.36,1.69,4.45,XY24,NTT,FMCG
30,HAPPSTMNDS,-1.83,-51.82,283.65,84.85,175160.0,-66413.0,61752.0,1480.71,-42.72,50.0,H-SC,23.76,152.0,-0.38,0.47,14.36,AR,ATH,IT

In [12]:
# top 5 to exit based on CumlRnk
df_tmp = df_portfolio_features[~df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])]
df_tmp = df_tmp[(df_tmp['Current P/L%'] > -1) & (df_tmp['Current P/L%'] < 1)].sort_values(by = 'CumlRnk', ascending=False)
df_tmp[cols].head()

Empty DataFrame
Columns: [Symbol, Today P/L%, Current P/L%, FTT%, OTT%, FTT Amt, Current P/L, Current, FTT, Dev%_PE, RSI_14, Conviction, Spread%, CumlRnk, RRR Ind, CurrAlloc%, Gained%, Criteria, Strategy, Category]
Index: []

In [13]:
# OX40N stocks to exit
df_tmp = df_portfolio_features[(df_portfolio_features['Symbol'].isin(list_ox40n))].sort_values(by = 'Current P/L%', ascending=False)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
26,FINCABLES,1.76,2.80,102.25,107.91,155194.0,4135.0,151779.0,1641.55,-7.66,46.0,M-SC,5.05,220.0,0.03,1.16,14.19,OX40N,ATH,CABLES
66,SIS,0.75,-33.40,82.07,21.26,60691.0,-37082.0,73950.0,528.00,1732.64,50.0,H-SC,14.81,168.0,-0.61,0.56,9.95,OX40N,NTT,MISC
18,CERA,2.41,-37.37,97.81,23.89,107757.0,-65733.0,110170.0,9475.00,-39.62,51.0,H-SC,19.15,153.0,-0.61,0.84,5.87,OX40N,NTT,CERAMICS
72,TATAELXSI,0.80,-38.38,114.28,32.03,92831.0,-50604.0,81231.0,9161.00,-22.88,46.0,H-SC,21.68,158.0,-0.55,0.62,7.51,OX40N,NTT,IT
48,KANSAINER,1.09,-39.74,88.31,13.47,143499.0,-107172.0,162495.0,340.00,-48.30,48.0,H-SC,23.41,162.0,-0.75,1.24,13.50,XY24,NTT,PAINTS

In [14]:
# top 5 to book for rotation
df_tmp = df_portfolio_features[(df_portfolio_features['Current P/L%'] > 20) ].sort_values(by = 'CumlRnk', ascending=False)
df_tmp[cols].head()

Empty DataFrame
Columns: [Symbol, Today P/L%, Current P/L%, FTT%, OTT%, FTT Amt, Current P/L, Current, FTT, Dev%_PE, RSI_14, Conviction, Spread%, CumlRnk, RRR Ind, CurrAlloc%, Gained%, Criteria, Strategy, Category]
Index: []

In [15]:
# top 5 to monitor for exit
df_tmp = df_portfolio_features[~df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])]
df_tmp = df_tmp[(df_tmp['Current P/L%'] > 0) ].sort_values(by = 'Dev%_PE', ascending=False)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
26,FINCABLES,1.76,2.80,102.25,107.91,155194.0,4135.0,151779.0,1641.55,-7.66,46.0,M-SC,5.05,220.0,0.03,1.16,14.19,OX40N,ATH,CABLES
1,ABB,0.92,13.73,28.00,45.57,83308.0,35909.0,297528.0,7934.00,-26.88,55.0,H-MC,13.66,125.0,0.43,2.27,32.12,AR,NTT,ELECTRICAL

In [16]:
# top 5 to book for rotation from weak conviction
df_tmp = df_portfolio_features[~df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])]
df_tmp = df_tmp[~df_tmp['Criteria'].isin(['XY25','XY24','X40', 'X40N'])].sort_values(by = 'RRR Ind', ascending=False)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
1,ABB,0.92,13.73,28.00,45.57,83308.0,35909.0,297528.0,7934.00,-26.88,55.0,H-MC,13.66,125.0,0.43,2.27,32.12,AR,NTT,ELECTRICAL
26,FINCABLES,1.76,2.80,102.25,107.91,155194.0,4135.0,151779.0,1641.55,-7.66,46.0,M-SC,5.05,220.0,0.03,1.16,14.19,OX40N,ATH,CABLES
40,INDIAMART,2.34,-11.21,132.82,106.72,145450.0,-13827.0,109509.0,4810.62,-59.96,49.0,H-SC,12.89,140.0,-0.10,0.84,9.55,AR,ATH,MISC
85,ZYDUSLIFE,0.27,-8.62,48.42,35.63,92728.0,-18066.0,191508.0,1286.17,-20.27,42.0,H-MC,5.70,120.0,-0.19,1.46,6.61,AR,ATH,PHARMA
84,WIPRO,1.14,-19.15,113.06,72.27,154898.0,-32443.0,137005.0,420.00,-26.90,48.0,M-LC,18.12,98.0,-0.21,1.05,5.11,XR,NTT,IT

In [17]:
# top 5 to accumulate based on lowest RSI_14
df_tmp = df_portfolio_features[df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])].sort_values(by = 'RSI_14', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
38,ICICIPRULI,1.94,-15.08,53.95,30.73,90251.0,-29718.0,167287.0,790.00,-37.88,25.0,X-MC,9.48,78.0,-0.33,1.28,1.94,X40,ATH,INSURANCE
21,DABUR,-0.78,-19.06,77.54,43.70,155693.0,-47278.0,200790.0,735.00,-26.49,29.0,X-MC,11.66,70.0,-0.30,1.53,0.86,XY24,BTT,FMCG
37,ICICIGI,1.34,-9.32,31.61,19.34,57357.0,-18658.0,181451.0,2252.93,-23.76,33.0,X-MC,6.29,66.0,-0.33,1.38,1.34,X40,ATH,INSURANCE
20,COLPAL,0.13,-30.44,103.44,41.51,189492.0,-80175.0,183190.0,3726.84,-15.94,34.0,X-MC,10.87,62.0,-0.42,1.40,2.42,XY25,ATH,FMCG
59,RELIANCE,-3.34,-16.20,49.53,25.30,83407.0,-32566.0,168397.0,1952.00,-18.49,34.0,X-LC,4.01,21.0,-0.39,1.29,12.43,XY25,BTT,REFINERIES

In [18]:
# top 5 to accumulate based on Spread and CumlRnk
df_tmp = df_portfolio_features[df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])]
df_tmp = df_tmp[(df_tmp['CumlRnk'] < 100)].sort_values(by = 'Spread%', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
65,SIEMENS,0.70,-18.11,53.27,25.51,81178.0,-33705.0,152390.0,4671.50,27.94,45.0,H-LC,0.49,51.0,-0.42,1.16,12.22,AR,ATH,ELECTRICAL
82,VOLTAS,1.26,-2.13,48.36,45.20,90748.0,-4092.0,187650.0,1856.00,12.06,36.0,X-MC,3.46,79.0,-0.05,1.43,4.52,XY25,NTT,AC
78,UNITDSPR,1.51,-8.93,32.61,20.77,69534.0,-20916.0,213228.0,1644.00,-19.26,40.0,X-MC,3.88,64.0,-0.30,1.63,1.71,X40N,NTT,BREWERIES
59,RELIANCE,-3.34,-16.20,49.53,25.30,83407.0,-32566.0,168397.0,1952.00,-18.49,34.0,X-LC,4.01,21.0,-0.39,1.29,12.43,XY25,BTT,REFINERIES
24,DMART,4.53,9.62,18.23,29.60,49877.0,24000.0,273600.0,5391.45,-7.56,78.0,X-LC,6.01,14.0,0.48,2.09,25.06,X40N,ATH,FMCG

In [19]:
# top 5 to accumulate based on lowest Gained%
df_tmp = df_portfolio_features[df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])].sort_values(by = 'Gained%', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
47,JSWINFRA,-0.96,-18.66,43.13,16.43,77807.0,-41374.0,180400.0,342.00,-30.19,41.0,X-MC,11.73,61.0,-0.53,1.38,0.00,X40N,NTT,REALTY
21,DABUR,-0.78,-19.06,77.54,43.70,155693.0,-47278.0,200790.0,735.00,-26.49,29.0,X-MC,11.66,70.0,-0.30,1.53,0.86,XY24,BTT,FMCG
37,ICICIGI,1.34,-9.32,31.61,19.34,57357.0,-18658.0,181451.0,2252.93,-23.76,33.0,X-MC,6.29,66.0,-0.33,1.38,1.34,X40,ATH,INSURANCE
2,ABBOTINDIA,-1.54,-13.18,35.99,18.07,55885.0,-23575.0,155280.0,35195.00,-26.09,43.0,X-MC,10.68,58.0,-0.42,1.19,1.55,X40,ATH,PHARMA
35,HINDUNILVR,0.96,-18.89,40.14,13.67,83696.0,-48553.0,208510.0,2922.00,-39.73,38.0,X-LC,11.31,9.0,-0.58,1.59,1.60,XY25,NTT,FMCG

In [20]:
# top 5 to accumulate based on lowest CurrAlloc%
df_tmp = df_portfolio_features[df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])].sort_values(by = 'CurrAlloc%', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
58,RELAXO,2.26,-64.58,329.98,52.31,169669.0,-93742.0,51418.0,1176.00,-62.25,41.0,X-SC,31.87,92.0,-0.55,0.39,14.96,X40N,NTT,FOOTWEAR
12,BATAINDIA,1.52,-56.97,214.17,35.20,118592.0,-73297.0,55373.0,2096.00,-27.36,42.0,X-SC,34.12,91.0,-0.62,0.42,9.82,X40,NTT,FOOTWEAR
54,QUESS,-0.83,-27.24,138.99,73.90,108004.0,-29087.0,77706.0,424.00,-60.88,43.0,X-SC,22.56,80.0,-0.27,0.59,4.53,XY24,NTT,MISC
36,HONAUT,2.05,-28.87,112.71,51.31,154610.0,-55663.0,137175.0,58357.33,-40.87,38.0,X-SC,18.22,90.0,-0.36,1.05,4.22,X40N,ATH,ELECTRICAL
65,SIEMENS,0.70,-18.11,53.27,25.51,81178.0,-33705.0,152390.0,4671.50,27.94,45.0,H-LC,0.49,51.0,-0.42,1.16,12.22,AR,ATH,ELECTRICAL

In [21]:
# top 5 to accumulate based on CumlRnk
df_tmp = df_portfolio_features.sort_values(by = 'CumlRnk', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
45,ITC,0.84,-22.22,53.06,19.06,140391.0,-75577.0,264589.0,452.00,-57.14,41.0,X-LC,19.71,1.0,-0.54,2.02,2.64,X40,NTT,FMCG
73,TCS,0.99,-27.34,74.21,26.57,249791.0,-126673.0,336600.0,4311.59,-38.38,46.0,X-LC,18.66,2.0,-0.51,2.57,5.05,X40,ATH,IT
43,INFY,0.41,-11.09,50.98,34.24,141826.0,-34689.0,278199.0,1972.00,-29.97,50.0,X-LC,14.91,3.0,-0.24,2.12,6.99,X40,NTT,IT
75,TMPV,1.50,-29.92,94.90,36.58,236642.0,-106482.0,249359.0,600.00,-85.81,40.0,X-LC,11.79,4.0,-0.45,1.90,3.93,XY24,NTT,AUTO
33,HCLTECH,0.21,-8.81,35.80,23.83,78975.0,-21323.0,220601.0,1908.19,-4.05,53.0,X-LC,11.27,8.0,-0.27,1.68,7.11,X40,ATH,IT

In [22]:
# top 5 for average up
df_tmp = df_portfolio_features[(df_portfolio_features['Dev%_200'] > 5)].sort_values(by = 'CurrAlloc%', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
67,SONACOMS,2.42,-12.02,58.10,39.09,51707.0,-12163.0,88996.0,804.02,-30.33,52.0,M-MC,7.00,193.0,-0.24,0.68,25.90,AR,ATH,AUTO
24,DMART,4.53,9.62,18.23,29.60,49877.0,24000.0,273600.0,5391.45,-7.56,78.0,X-LC,6.01,14.0,0.48,2.09,25.06,X40N,ATH,FMCG
1,ABB,0.92,13.73,28.00,45.57,83308.0,35909.0,297528.0,7934.00,-26.88,55.0,H-MC,13.66,125.0,0.43,2.27,32.12,AR,NTT,ELECTRICAL

In [23]:
# top 5 RSP
df_tmp = df_portfolio_features.sort_values(by = 'RSP', ascending=False)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
24,DMART,4.53,9.62,18.23,29.60,49877.0,24000.0,273600.0,5391.45,-7.56,78.0,X-LC,6.01,14.0,0.48,2.09,25.06,X40N,ATH,FMCG
30,HAPPSTMNDS,-1.83,-51.82,283.65,84.85,175160.0,-66413.0,61752.0,1480.71,-42.72,50.0,H-SC,23.76,152.0,-0.38,0.47,14.36,AR,ATH,IT
5,ANGELONE,2.26,0.94,23.02,24.18,70873.0,2875.0,307875.0,303.00,-85.37,58.0,X-SC,9.07,97.0,0.04,2.35,18.50,X40N,NTT,FINANCE
80,VALIANTORG,3.46,-50.04,248.60,74.15,203188.0,-81872.0,81733.0,838.00,-247.22,53.0,H-SC,27.08,145.0,-0.40,0.62,21.63,XR,NTT,CHEMICALS
52,PAGEIND,2.46,-9.29,47.84,34.11,116471.0,-24919.0,243460.0,51418.64,-34.93,66.0,X-MC,19.71,55.0,-0.21,1.86,15.17,X40,ATH,APPARELS

In [24]:
# Top N allocation
df_tmp = df_portfolio_features.sort_values(by = 'CurrAlloc%', ascending=False)
top_n_values = [10, 25, 50]

sum_df = pd.DataFrame({
    'Top_N': top_n_values,
    'Sum_Alloc%': [df_tmp['CurrAlloc%'].head(n).sum() for n in top_n_values]
})

sum_df

   Top_N  Sum_Alloc%
0     10       21.09
1     25       46.20
2     50       78.01

In [25]:
# market-cap-wise allocation
df_tmp = df_portfolio_features[cols]
df_tmp.groupby(df_tmp['Conviction'].str[-2:])['CurrAlloc%'].sum().sort_values(ascending=False)

Conviction
SC    44.75
MC    29.54
LC    25.75
Name: CurrAlloc%, dtype: float64

In [26]:
# criteria-wise allocation
df_portfolio_features.groupby('Criteria')['CurrAlloc%'].sum().sort_values(ascending=False)

Criteria
XY24     27.08
X40      25.34
X40N     15.46
AR        9.15
XR        8.45
XY25      7.09
OX40N     6.67
SR        0.80
Name: CurrAlloc%, dtype: float64

In [27]:
# conviction-wise allocation
df_portfolio_features.groupby('Conviction')['CurrAlloc%'].sum().sort_values(ascending=False)

Conviction
X-LC    23.54
X-MC    22.13
H-SC    21.91
X-SC    12.33
M-SC     9.97
H-MC     5.01
M-MC     2.06
H-LC     1.16
M-LC     1.05
L-SC     0.54
L-MC     0.34
Name: CurrAlloc%, dtype: float64

In [28]:
# sector-wise stats
df_tmp = df_portfolio_features.groupby('Category')[['CurrAlloc%', 'Current', 'Current P/L', 'FTT Amt']].sum().sort_values(by=['Current', 'Current P/L'], ascending=False)
df_tmp['Current P/L%'] = round(df_tmp['Current P/L'] * 100 / df_tmp['Current'], 2)
df_tmp['FTT%'] = round(df_tmp['FTT Amt'] * 100 / df_tmp['Current'], 2)
cols = ['CurrAlloc%', 'Current P/L%', 'FTT%']
df_tmp[cols].sort_values(by=['CurrAlloc%'], ascending=False)

               CurrAlloc%  Current P/L%    FTT%
Category
FMCG                15.17        -25.68   70.31
FINANCE             13.23        -24.08   74.64
IT                  12.02        -43.02  115.80
MISC                 7.09        -44.25  106.92
ELECTRICAL           6.42        -15.19   59.30
PAINTS               5.24        -43.53   68.45
BANKS                4.60        -27.76   92.61
INSURANCE            4.54        -13.85   52.81
PHARMA               4.08         -9.96   44.57
AUTO                 3.66        -36.36   90.47
HEALTHCARE           1.96        -39.33   75.69
AC                   1.93        -26.28   60.52
APPARELS             1.86        -10.24   47.84
FOOTWEAR             1.84        -83.01  156.39
TRAVEL               1.77        -92.29  188.56
DURABLES             1.76        -68.32  109.28
BREWERIES            1.63         -9.81   32.61
CERAMICS             1.38        -69.70  121.26
REALTY               1.38        -22.93   43.13
REFINERIES           1.29        -19.34   49.53
CEMENT               1.25        -63.75  186.26
CABLES               1.16          2.72  102.25
ENGINEERING          1.12        -65.72  141.52
CHEMICALS            1.06        -90.47  245.86
JEWELLERY            1.02       -141.27  225.09
ENTERTAINMENT        0.77        -90.99  204.90
TEXTILES             0.46        -54.28   98.27
HOTELS               0.35       -148.38  235.99

In [29]:
# money to be made criteria-wise
df_portfolio_features.groupby('Criteria')['FTT Amt'].agg(['sum', 'count']).sort_values(by='sum', ascending=False)

                sum  count
Criteria
XY24      4047715.0     21
X40       1854393.0     16
XR        1386681.0     12
AR        1372620.0     10
X40N      1275173.0     10
OX40N      919207.0     10
XY25       512251.0      5
SR         315110.0      2

In [30]:
# money to be made conviction-wise
df_portfolio_features.groupby('Conviction')['FTT Amt'].agg(['sum', 'count']).sort_values(by='sum', ascending=False)

                  sum  count
Conviction
H-SC        3924105.0     24
X-MC        1834802.0     15
X-LC        1691380.0     13
M-SC        1613462.0     14
X-SC        1566411.0     10
H-MC         421689.0      3
L-SC         220878.0      2
M-LC         154898.0      1
M-MC         116615.0      2
H-LC          81178.0      1
L-MC          57732.0      1

In [31]:
# money to be made criteria and conviction-wise
df_portfolio_features.groupby(['Conviction', 'Criteria'])['FTT Amt'].agg(['sum', 'count']).sort_values(by='sum', ascending=False)

                           sum  count
Conviction Criteria
H-SC       XY24      1358376.0      6
           AR         984548.0      5
M-SC       XY24       928002.0      6
X-LC       X40        915507.0      7
H-SC       XR         874096.0      7
X-SC       XY24       855434.0      4
X-MC       X40        715784.0      7
           X40N       564815.0      4
X-SC       X40N       487875.0      4
M-SC       OX40N      414237.0      5
H-SC       OX40N      391975.0      4
X-LC       XY24       386287.0      2
H-SC       SR         315110.0      2
X-MC       XY25       280240.0      2
           XY24       273963.0      2
H-MC       XY24       245653.0      1
X-SC       X40        223102.0      2
X-LC       X40N       222483.0      2
M-SC       XR         192072.0      2
H-MC       AR         176036.0      2
X-LC       XY25       167103.0      2
M-LC       XR         154898.0      1
L-SC       OX40N      112995.0      1
           XR         107883.0      1
H-LC       AR          81178.0      1
M-SC       AR          79151.0      1
M-MC       XY25        64908.0      1
L-MC       XR          57732.0      1
M-MC       AR          51707.0      1

In [32]:
# notebook execution time

end_time = time.time()
execution_time = round(end_time - start_time, 0)
print(f"Notebook execution time: {execution_time} seconds")

Notebook execution time: 47.0 seconds