<a href="https://colab.research.google.com/github/ankit-rathi/Quantvesting_v2/blob/main/myStocks_Portfolio_Analysis.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
'''
!pip install pandas==2.2.2 -qq
!pip install pyxirr -qq
!pip install ta -qq
!pip install yfinance==0.2.59 -qq
'''

'\n!pip install pandas==2.2.2 -qq\n!pip install pyxirr -qq\n!pip install ta -qq\n!pip install yfinance==0.2.59 -qq\n'

In [2]:
# import libraries

import numpy as np
import pandas as pd
import datetime
import warnings
warnings.filterwarnings('ignore')
import yfinance as yfin
import ta
import matplotlib.pyplot as plt
import requests

In [3]:
# notebook start time
import time
import datetime
import pytz

start_time = time.time()

# function to print date timestamp
def print_date_time():
  tz_NY = pytz.timezone('Asia/Kolkata')
  datetime_NY = datetime.datetime.now(tz_NY)
  print("Run date time (IST):", datetime_NY.strftime("%Y-%m-%d %H:%M:%S"))

In [4]:
# function to get booked and reserved amount
def get_amt():
  # fetch the JSON data from the URL
  url = "https://raw.githubusercontent.com/ankit-rathi/Tradevesting_v1/main/data/myPortfolioAmts.json"
  response = requests.get(url)
  pf_amts = response.json()  # parse the JSON data

  # extract values from the JSON
  py_booked_amt_dm = pf_amts["py_booked_amt_dm"]
  py_booked_amt_sv = pf_amts["py_booked_amt_sv"]
  cy_booked_amt_dm = pf_amts["cy_booked_amt_dm"]
  cy_booked_amt_sv = pf_amts["cy_booked_amt_sv"]
  reserve_amt_dm = pf_amts["reserve_amt_dm"]
  reserve_amt_sv = pf_amts["reserve_amt_sv"]

  # perform calculations
  py_booked_amt = py_booked_amt_dm + py_booked_amt_sv
  cy_booked_amt = cy_booked_amt_dm + cy_booked_amt_sv
  reserve_amt = reserve_amt_dm + reserve_amt_sv
  total_booked_amt = py_booked_amt + cy_booked_amt

  return total_booked_amt, reserve_amt, cy_booked_amt, py_booked_amt

gen_output = 0

In [5]:
# function to format the amount
def format_amt(number):
    abs_number = abs(number)

    if abs_number >= 1_00_00_000:  # Crores
        formatted_amt = f"{number / 1_00_00_000:.2f} C"
    elif abs_number >= 1_00_000:  # Lakhs
        formatted_amt = f"{number / 1_00_000:.2f} L"
    elif abs_number >= 1_000:  # Thousands
        formatted_amt = f"{number / 1_000:.2f} K"
    else:
        formatted_amt = f"{number:.2f}"

    return formatted_amt

# function to set start and end date
def get_start_end_date():
  start_date = (datetime.date.today() + datetime.timedelta(days=-365)).strftime('%Y-%m-%d')
  end_date = (datetime.date.today() + datetime.timedelta(days=1)).strftime('%Y-%m-%d')
  return start_date, end_date

# function to fetch my portfolio csv
def get_mypfs_df():
  mypfs_df = pd.read_csv('https://raw.githubusercontent.com/ankit-rathi/Tradevesting_v1/main/data/myPortfolioStocks.csv')
  return mypfs_df

# function to fetch my prospects csv
def get_mypps_df():
  mypps_df = pd.read_csv('https://raw.githubusercontent.com/ankit-rathi/Tradevesting_v1/main/data/myProspectsScrips.csv')
  return mypps_df

# function to fetch screener data
def get_myscreen_df():
  myscreen_df = pd.read_csv('https://raw.githubusercontent.com/ankit-rathi/Tradevesting_v1/main/data/myScreenerDB.csv')
  return myscreen_df

# function to fetch momentum data
def get_myinvmt_df():
  myinvmt_df = pd.read_csv('https://raw.githubusercontent.com/ankit-rathi/Tradevesting_v1/main/data/myInvestments.csv')
  return myinvmt_df

# function to get the stock ids
def get_stock_ids(df_pf):
  stock_n100 = df_pf['Symbol'].unique()

  exclude = ['CADILAHC','MMTC', 'MASFIN']

  stock_ids = df_pf[~df_pf['Symbol'].isin(exclude) ]['Symbol'].unique()

  #mypf = mypf[mypf.Forecast.notnull()]
  #stock_ids = mypf['Symbol'].unique()

  #stock_ids.sort()
  return stock_ids

# get features from screener data
def get_screener_features():
  myscreen_df = get_myscreen_df()
  cols = ['Symbol', 'EPS', 'MedPE', 'ROCE%', 'ROE%', 'CapType']
  return myscreen_df[cols]

# get relative strength
def get_relative_strength(stock_list):

    # Dictionary to store stock tickers and their corresponding percentage price change
    stock_changes = {}

    # Loop through each stock and fetch its price data
    for stock in stock_list:
        try:
            # Download the stock data for the given date range
            stock_data = yfin.Ticker(stock + '.NS').history(period='1mo', interval='1d')[map(str.title, ['open', 'close', 'low', 'high', 'volume'])]

            # Calculate the percentage change for the stock
            if len(stock_data) > 0:
                start_price = stock_data['Close'].iloc[0]
                end_price = stock_data['Close'].iloc[-1]
                percent_change = round(((end_price - start_price) / start_price) * 100, 2)
                stock_changes[stock] = percent_change
            else:
                stock_changes[stock] = np.nan  # If no data is available, set to NaN

        except Exception as e:
            print(f"Error fetching data for {stock}: {e}")
            stock_changes[stock] = np.nan

    # Create a DataFrame with stock tickers and their percentage changes
    df = pd.DataFrame(list(stock_changes.items()), columns=['Symbol', 'Percent_Change'])

    # Drop any stocks with missing data (NaN values)
    df = df.dropna()

    # Calculate the percentile rank based on percentage change
    df['RSP'] = round(df['Percent_Change'].rank(pct=True) * 100, 2)
    cols = ['Symbol', 'RSP']
    df = df[cols]
    # Sort by percentile rank (optional)
    df = df.sort_values(by='RSP', ascending=False).reset_index(drop=True)

    return df

In [6]:
# function to get stock technicals
def stock_prec_dev(stock_symbol):
    #stock_symbol = 'ULTRACEMCO.NS'
    short_window = 20
    mid_window = 50
    long_window = 200
    moving_avg = 'SMA'

    start = datetime.datetime(*map(int, start_date.split('-')))
    end = datetime.datetime(*map(int, end_date.split('-')))

    stock_df = yfin.Ticker(stock_symbol + '.NS').history(period='max', interval='1d')[map(str.title, ['open', 'close', 'low', 'high', 'volume'])]

    stock_df['Max'] = round(max(stock_df['Close']),2)
    stock_df = stock_df[(stock_df.index <= end_date) & (stock_df.index >= start_date)]
    stock_df['200_SMA'] = round(stock_df['Close'].rolling(window = 200, min_periods = 1).mean(),0)
    stock_df['Dev%_200'] = round((stock_df['Close'] - stock_df['200_SMA'])*100/stock_df['200_SMA'],2)
    stock_df.dropna(axis = 0, inplace = True) # remove any null rows

    stock_df['20_SMA'] = stock_df['Close'].rolling(window=20).mean()
    stock_df['50_SMA'] = stock_df['Close'].rolling(window=50).mean()
    stock_df['Symbol'] = stock_symbol

    stock_df['Close'] = round(stock_df['Close'],2)
    stock_df['Min'] = round(min(stock_df['Close']),2)
    stock_df['RSI_14'] = ta.momentum.RSIIndicator(close=stock_df['Close'], window=14).rsi()
    stock_df['RSI_14'] = round(stock_df['RSI_14'],0)
    stock_df['Prev_Close'] = stock_df['Close'].shift(1)
    stock_df.drop(['Open', 'Low', 'High', 'Volume'], axis=1, inplace=True)
    stock_df = stock_df.tail(1)

    max_SMA = max(stock_df['20_SMA'].item(), stock_df['50_SMA'].item(), stock_df['200_SMA'].item())
    min_SMA = min(stock_df['20_SMA'].item(), stock_df['50_SMA'].item(), stock_df['200_SMA'].item())
    ABS_Spread = max_SMA - min_SMA
    stock_df['Spread%'] = round((ABS_Spread / stock_df['200_SMA'].item()) * 100,2)

    return stock_df

# function to compute stock attributes
def get_common_features(stock_ids, df_mypf):

  df_prec_dev = pd.DataFrame()
  df_tmp = get_screener_features()
  df_rs = get_relative_strength(stock_ids)

  for stock_id in stock_ids:
      tmp = stock_prec_dev(stock_id)
      tmp = tmp.reset_index()
      df_prec_dev = pd.concat([df_prec_dev, tmp], ignore_index = True)
  df_prec_dev = pd.merge(df_prec_dev, df_mypf, on= 'Symbol')
  df_prec_dev = pd.merge(df_prec_dev, df_tmp, on= 'Symbol', how='left')
  df_prec_dev = pd.merge(df_prec_dev, df_rs, on= 'Symbol', how='left')
  #print(df_prec_dev.columns)
  df_prec_dev['Curr_PE'] = round(df_prec_dev['Close']/df_prec_dev['EPS'],1)
  df_prec_dev['Dev%_PE'] = round((df_prec_dev['Curr_PE'] - df_prec_dev['MedPE'])*100/df_prec_dev['MedPE'],2)
  df_prec_dev['Conviction'] = df_prec_dev['Conviction'] + '-' + df_prec_dev['CapType']
  return df_prec_dev

# function to arrange stock features
def arrange_features(df_stocks, common_cols, diff_cols):
  df_stocks_common = df_stocks[common_cols].drop_duplicates()
  df_stocks_diff = df_stocks[diff_cols]
  df_stocks_diff['Investment'] = df_stocks_diff['AvgCost'] * df_stocks_diff['Shares']
  df_stocks_diff = df_stocks_diff.groupby(['Symbol'])[['Shares', 'Investment']].aggregate(['sum']).reset_index()
  df_stocks_diff.columns = ['Symbol', 'Shares', 'Investment']
  df_stocks_diff['AvgCost'] = round(df_stocks_diff['Investment']/df_stocks_diff['Shares'],2)
  df_stocks = pd.merge(df_stocks_diff, df_stocks_common, on='Symbol')
  return df_stocks

# plot fact distribution across dimension
def plot_pie_chart(df, dimension, fact):
  # grouping the data by category and calculating the sum of fact for each type
  grouped_data = df.groupby(dimension)[fact].sum()

  # sorting the grouped data in descending order
  grouped_data = grouped_data.sort_values(ascending=False)

  # creating a pie chart
  grouped_data.plot.pie(autopct='%1.1f%%', startangle=90, figsize=(6, 6))

  # adding a title and displaying the plot
  plt.title(f'{dimension} {fact} Distribution')
  plt.ylabel('')  # To hide the y-label
  plt.show()

In [7]:
# function to get portfolio features

def get_portfolio_features(df_common_features):

  print_date_time()
  print('-------------------')

  #df_common_features["Target"] = df_common_features["Target"].fillna(df_common_features["Max"])
  df_common_features['NTT'] = np.where(df_common_features['Strategy']== 'NTT', df_common_features["Target"], df_common_features['Max'])
  df_common_features['LTT'] = np.where(df_common_features['Strategy']== 'BTT', df_common_features["Target"], df_common_features['Max'])
  df_common_features['BOL'] = df_common_features['Min']

  tmp_df = df_common_features[df_common_features['Symbol'].isin(mypf_df[mypf_df['InPortfolio'] != 'NA'].Symbol.values)]
  print('qualified stocks: '+str(len(tmp_df['Symbol'].unique())))
  tmp_df1 = tmp_df[tmp_df['LatestQtr'] == 1]
  print('with latest results: '+str(len(tmp_df1['Symbol'].unique())))
  tmp_df1 = tmp_df1[tmp_df1['StarStock'] == 1]
  print('still star stocks: '+str(len(tmp_df1['Symbol'].unique())))
  tmp_df['Investment'] = tmp_df['AvgCost'] * tmp_df['Shares']
  tmp_df['Current'] = round(tmp_df['Close'] * tmp_df['Shares'],0)
  tmp_df['Previous'] = tmp_df['Prev_Close'] * tmp_df['Shares']
  tmp_df['EstimatedST'] = tmp_df['NTT'] * tmp_df['Shares']
  tmp_df['EstimatedLT'] = tmp_df['LTT'] * tmp_df['Shares']
  tmp_df['Current P/L'] = round((tmp_df['Current'] - tmp_df['Investment']),0)
  tmp_df['Today P/L%'] = round((tmp_df['Current'] - tmp_df['Previous'])*100/tmp_df['Previous'],2)
  tmp_df['Current P/L%'] = round((tmp_df['Current'] - tmp_df['Investment'])*100/tmp_df['Investment'],2)
  tmp_df['EstimatedST P/L%'] = round((tmp_df['EstimatedST'] - tmp_df['Investment'])*100/tmp_df['Investment'],2)
  tmp_df['EstimatedLT P/L%'] = round((tmp_df['EstimatedLT'] - tmp_df['Investment'])*100/tmp_df['Investment'],2)
  tmp_df['NTT%'] = round((tmp_df['NTT'] - tmp_df['Close'])*100/tmp_df['Close'],2)
  tmp_df['LTT%'] = round((tmp_df['LTT'] - tmp_df['Close'])*100/tmp_df['Close'],2)
  tmp_df['Gained%'] = round((tmp_df['Close'] - tmp_df['BOL'])*100/tmp_df['BOL'],2)
  investment = round(sum(tmp_df['AvgCost']*tmp_df['Shares']),0)
  current = round(sum(tmp_df['Close']*tmp_df['Shares']),0)
  tmp_df['InitAlloc%'] = round(tmp_df['Investment']*100/investment,2)
  tmp_df['CurrAlloc%'] = round(tmp_df['Current']*100/current,2)
  tmp_df['FTT'] = tmp_df['LTT']
  tmp_df.loc[tmp_df['Strategy'] == 'NTT', 'FTT'] = tmp_df['NTT']
  tmp_df['FTT%'] = tmp_df['LTT%']
  tmp_df.loc[tmp_df['Strategy'] == 'NTT', 'FTT%'] = tmp_df['NTT%']
  tmp_df['FTT Amt'] = round(tmp_df['FTT%'] * tmp_df['Current']/100,0)
  tmp_df['OTT%'] = round((tmp_df['FTT'] - tmp_df['AvgCost'])*100/tmp_df['AvgCost'],2)
  tmp_df['RRR Ind'] = round(tmp_df['Current P/L']/tmp_df['FTT Amt'],2)
  tmp_df['Risk Ind'] = round(tmp_df['Current P/L%']*tmp_df['CurrAlloc%'],0)

  return tmp_df

# function to print portfolio features
def print_portfolio_stats(df_portfolio_features, myinvmt_df):
  from pyxirr import xirr

  total_booked_amt, reserve_amt, cy_booked_amt, py_booked_amt = get_amt()

  dates = myinvmt_df['Date'].values
  dates = np.append(dates, datetime.date.today().strftime('%d-%b-%y'))
  investment = myinvmt_df['Investment'].values
  dates= pd.to_datetime(dates)

  current = round(sum(df_portfolio_features['Close']*df_portfolio_features['Shares']),0) + reserve_amt
  investment_xirr = np.append(investment, current)
  cagr = round(xirr(pd.DataFrame({"dates": dates, "amounts": investment_xirr}))*100,2)

  investment = -sum(investment)
  invested = round(sum(df_portfolio_features['AvgCost']*df_portfolio_features['Shares']),0) + reserve_amt
  previous = round(sum(df_portfolio_features['Prev_Close']*df_portfolio_features['Shares']),0) + reserve_amt
  cy_invested = investment + py_booked_amt

  today_pnl_amount = current-previous
  today_pnl_percentage = round((current-previous)*100/previous,2)

  curr_pnl_amount = current-invested
  curr_pnl_percentage = round((curr_pnl_amount)*100/(cy_invested),2)

  cy_pnl_amount = cy_booked_amt + curr_pnl_amount
  cy_pnl_percentage = round((cy_pnl_amount)*100/cy_invested,2)

  overall_pnl_amount = total_booked_amt + curr_pnl_amount
  overall_pnl_percentage = round((overall_pnl_amount)*100/investment,2)

  estimate_st = round(sum(df_portfolio_features['FTT']*df_portfolio_features['Shares']),0)  + reserve_amt
  est_st_pnl_amount = estimate_st-current
  est_st_pnl_percentage = round((est_st_pnl_amount)*100/current,2)

  estimate_lt = round(sum(df_portfolio_features['LTT']*df_portfolio_features['Shares']),0)  + reserve_amt
  est_lt_pnl_amount = estimate_lt-current
  est_lt_pnl_percentage = round((est_lt_pnl_amount)*100/current,2)

  total_profit = round(sum(df_portfolio_features[df_portfolio_features['Current P/L%'] > 0]['Current']) - sum(df_portfolio_features[df_portfolio_features['Current P/L%'] > 0]['Investment']),0)
  total_loss = round(sum(df_portfolio_features[df_portfolio_features['Current P/L%'] < 0]['Current']) - sum(df_portfolio_features[df_portfolio_features['Current P/L%'] < 0]['Investment']),0)

  cy_booked_percentage = round((cy_booked_amt)*100/current,2)
  py_booked_percentage = round((py_booked_amt)*100/investment,2)
  total_booked_percentage = round((total_booked_amt)*100/investment,2)

  print('-------------------')
  print('Initial Investment: ', format_amt(investment))
  print('CY Investment: ', format_amt(cy_invested))
  print('Reserve: ', format_amt(reserve_amt))
  print('Current: ',  format_amt(current))
  print('-------------------')
  print('Today PnL: '+ '{} ({}%)'.format(format_amt(today_pnl_amount), today_pnl_percentage))
  print('Current PnL: '+ '{} ({}%)'.format(format_amt(curr_pnl_amount), curr_pnl_percentage))
  print('CY Booked + Current PnL: '+ '{} ({}%)'.format(format_amt(cy_pnl_amount), cy_pnl_percentage))
  print('-------------------')
  print('Total profit: ', format_amt(total_profit))
  print('Total loss: ', format_amt(total_loss))
  print('-------------------')
  print('Total Booked + Current PnL: '+ '{} ({}%)'.format(format_amt(overall_pnl_amount), overall_pnl_percentage))
  print('Total Booked PnL: '+ '{} ({}%)'.format(format_amt(total_booked_amt), total_booked_percentage))
  print('Curr Year Booked PnL: '+ '{} ({}%)'.format(format_amt(cy_booked_amt), cy_booked_percentage))
  print('Prev Year Booked PnL: '+ '{} ({}%)'.format(format_amt(py_booked_amt), py_booked_percentage))
  print('===================')
  print('Est FTT: ',  format_amt(estimate_st))
  print('Est FTT PnL: '+ '{} ({}%)'.format(format_amt(est_st_pnl_amount), est_st_pnl_percentage))

  print('===================')
  print('Deployed: ', format_amt(investment))

  print('Current: ', format_amt(current))

  print('CAGR/XIRR %: '+'{}%'.format(cagr))

In [8]:
# get start and end date
start_date, end_date = get_start_end_date()

# get portfolio and prospects data
mypfs_df = get_mypfs_df()
mypps_df = get_mypps_df()
myinvmt_df = get_myinvmt_df()

# merge above datasets
mypf_df = pd.merge(mypfs_df, mypps_df, on="Symbol")

# seggregate dm and sv portfolio
dm_pf = mypf_df[mypf_df['InPortfolio'] == 'DM']
sv_pf = mypf_df[mypf_df['InPortfolio'] == 'SV']

# build portfolio stock dataframe
dm_stocks = get_stock_ids(dm_pf)
sv_stocks = get_stock_ids(sv_pf)
df_stocks = pd.concat([dm_pf,sv_pf], ignore_index = True)

# arrange common and diff stock features
common_cols = ['Symbol', 'Target', 'Criteria', 'Strategy', 'CumlRnk', 'LatestQtr', 'StarStock', 'Conviction', 'Category', 'InFolio', 'XIRR', 'MBQ']
diff_cols = ['Symbol', 'AvgCost', 'Shares']
df_stocks = arrange_features(df_stocks, common_cols, diff_cols)

# get common features
stock_ids = df_stocks['Symbol'].values
df_common_features = get_common_features(stock_ids, df_stocks)

df_common_features.reset_index(drop=True, inplace=True)
df_common_features.drop(['Date'], axis=1, inplace=True)
# get and print portfolio features
df_portfolio_features = get_portfolio_features(df_common_features)

print_portfolio_stats(df_portfolio_features, myinvmt_df)

df = df_portfolio_features
#plot_pie_chart(df, 'CapType', 'Current')
list_ox40n = list(df[df['MBQ'].str.contains('OX40N', na=False)]['Symbol'].values)

Run date time (IST): 2026-05-21 15:34:16
-------------------
qualified stocks: 92
with latest results: 31
still star stocks: 20
-------------------
Initial Investment:  1.40 C
CY Investment:  1.82 C
Reserve:  1.49 K
Current:  1.48 C
-------------------
Today PnL: 44.21 K (0.3%)
Current PnL: -34.92 L (-19.15%)
CY Booked + Current PnL: -32.84 L (-18.01%)
-------------------
Total profit:  1.90 L
Total loss:  -36.82 L
-------------------
Total Booked + Current PnL: 10.03 L (7.19%)
Total Booked PnL: 44.95 L (32.22%)
Curr Year Booked PnL: 2.08 L (1.4%)
Prev Year Booked PnL: 42.87 L (30.73%)
===================
Est FTT:  2.55 C
Est FTT PnL: 1.07 C (72.29%)
===================
Deployed:  1.40 C
Current:  1.48 C
CAGR/XIRR %: 2.95%

In [9]:
# top 5 near their targets
cols = ['Symbol', 'Today P/L%', 'Current P/L%', 'FTT%', 'OTT%', 'FTT Amt', 'Current P/L', 'Current', 'FTT', 'Dev%_PE', 'RSI_14','Conviction', 'Spread%',  'CumlRnk', 'RRR Ind', 'CurrAlloc%', 'Gained%', 'Criteria', 'Strategy', 'Category']
df_tmp = df_portfolio_features[~df_portfolio_features['Symbol'].isin(['ENRIN','BLUSPRING','DIGITIDE'])]
df_tmp = df_tmp.sort_values(by = 'FTT Amt', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
59,PIDILITIND,1.18,4.37,13.41,18.37,19750.0,6170.0,147280.0,1670.26,-26.86,61.0,X-LC,5.54,5.0,0.31,0.99,15.64,X40,ATH,CHEMICALS
51,KOTAKBANK,-0.61,1.76,19.01,21.11,26788.0,2442.0,140914.0,453.24,-12.87,51.0,X-LC,7.82,12.0,0.09,0.95,7.77,X40,ATH,BANKS
55,MASFIN,-1.19,-6.31,29.75,21.57,27310.0,-6180.0,91800.0,397.04,-19.15,35.0,H-SC,5.21,167.0,-0.23,0.62,9.42,XR,ATH,FINANCE
83,TTKPRESTIG,-0.16,-29.58,42.13,0.09,29899.0,-29808.0,70969.0,770.00,64.78,61.0,M-SC,16.08,250.0,-1.00,0.48,26.37,OX40N,NTT,DURABLES
53,M&M,-0.74,0.56,22.70,23.38,31656.0,774.0,139455.0,3802.40,-14.78,45.0,X-LC,8.81,25.0,0.02,0.94,5.73,X40N,ATH,AUTO

In [10]:
# top 5 today
df_tmp = df_portfolio_features.sort_values(by = 'Today P/L%', ascending=False)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
37,HONAUT,15.85,-9.34,66.90,51.31,116958.0,-18013.0,174825.0,58357.33,-24.61,72.0,X-SC,11.75,90.0,-0.15,1.18,32.82,X40N,ATH,ELECTRICAL
38,HYUNDAI,3.23,-1.90,52.25,49.35,79057.0,-2935.0,151306.0,2809.30,-20.86,51.0,X-LC,17.65,29.0,-0.04,1.02,9.09,X40N,ATH,AUTO
12,BOSCH-HCIL,2.83,-39.97,66.56,-0.01,51069.0,-51079.0,76726.0,2282.00,15595.65,49.0,M-SC,6.13,231.0,-1.00,0.52,30.60,OX40N,BTT,AC
0,5PAISA,2.59,-39.33,86.10,12.90,114132.0,-85938.0,132558.0,593.00,94.71,51.0,H-SC,7.61,170.0,-0.75,0.89,27.92,OX40N,NTT,FINANCE
89,WHIRLPOOL,2.51,-29.68,158.70,81.92,128111.0,-34073.0,80725.0,2270.00,-58.80,45.0,M-SC,16.19,210.0,-0.27,0.54,13.39,XR,NTT,DURABLES

In [11]:
# bottom 5 today
df_tmp = df_portfolio_features.sort_values(by = 'Today P/L%', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
68,SATIN,-2.21,20.59,25.91,51.83,86326.0,56892.0,333176.0,274.00,7.75,70.0,H-SC,30.75,159.0,0.66,2.25,62.31,XY24,NTT,FINANCE
3,ALKYLAMINE,-1.93,-25.79,160.93,93.63,120574.0,-26040.0,74923.0,4546.37,-20.57,62.0,H-SC,14.08,142.0,-0.22,0.51,41.47,SR,ATH,CHEMICALS
11,BERGEPAINT,-1.79,-7.98,36.18,25.32,85816.0,-20558.0,237191.0,680.00,-13.04,55.0,X-MC,10.23,68.0,-0.24,1.60,23.45,XY24,NTT,PAINTS
88,VOLTAS,-1.72,-0.37,45.74,45.20,87375.0,-717.0,191025.0,1856.00,14.09,41.0,X-MC,1.92,79.0,-0.01,1.29,4.37,XY25,NTT,AC
29,GREENPANEL,-1.58,-51.90,197.61,43.14,174005.0,-95023.0,88055.0,537.00,97.03,27.0,M-SC,16.55,225.0,-0.55,0.59,5.77,XY24,NTT,MISC

In [12]:
# top 5 to exit based on CumlRnk
df_tmp = df_portfolio_features[~df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])]
df_tmp = df_tmp[(df_tmp['Current P/L%'] > -1) & (df_tmp['Current P/L%'] < 1)].sort_values(by = 'CumlRnk', ascending=False)
df_tmp[cols].head()

Empty DataFrame
Columns: [Symbol, Today P/L%, Current P/L%, FTT%, OTT%, FTT Amt, Current P/L, Current, FTT, Dev%_PE, RSI_14, Conviction, Spread%, CumlRnk, RRR Ind, CurrAlloc%, Gained%, Criteria, Strategy, Category]
Index: []

In [13]:
# OX40N stocks to exit
df_tmp = df_portfolio_features[(df_portfolio_features['Symbol'].isin(list_ox40n))].sort_values(by = 'Current P/L%', ascending=False)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
25,FINCABLES,0.33,32.12,57.37,107.91,111906.0,47416.0,195060.0,1641.55,18.72,56.0,M-SC,25.35,220.0,0.42,1.32,46.75,OX40N,ATH,CABLES
72,SIS,-0.81,-10.02,34.76,21.26,34728.0,-11123.0,99909.0,528.00,2375.65,63.0,H-SC,15.18,168.0,-0.32,0.67,48.55,OX40N,NTT,MISC
16,CERA,0.69,-24.32,63.70,23.89,84800.0,-42779.0,133124.0,9475.00,-26.97,61.0,H-SC,7.44,153.0,-0.50,0.90,27.93,OX40N,NTT,CERAMICS
50,KANSAINER,1.57,-27.25,55.98,13.47,109818.0,-73494.0,196173.0,340.00,-37.50,62.0,H-SC,13.68,162.0,-0.67,1.32,37.03,XY24,NTT,PAINTS
43,INDIGOPNTS,0.80,-29.56,41.99,0.02,51630.0,-51601.0,122958.0,1408.00,87.50,66.0,M-SC,19.45,222.0,-1.00,0.83,39.50,OX40N,NTT,PAINTS

In [14]:
# top 5 to book for rotation
df_tmp = df_portfolio_features[(df_portfolio_features['Current P/L%'] > 20) ].sort_values(by = 'CumlRnk', ascending=False)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
25,FINCABLES,0.33,32.12,57.37,107.91,111906.0,47416.0,195060.0,1641.55,18.72,56.0,M-SC,25.35,220.0,0.42,1.32,46.75,OX40N,ATH,CABLES
68,SATIN,-2.21,20.59,25.91,51.83,86326.0,56892.0,333176.0,274.00,7.75,70.0,H-SC,30.75,159.0,0.66,2.25,62.31,XY24,NTT,FINANCE

In [15]:
# top 5 to monitor for exit
df_tmp = df_portfolio_features[~df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])]
df_tmp = df_tmp[(df_tmp['Current P/L%'] > 0) ].sort_values(by = 'Dev%_PE', ascending=False)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
74,STARHEALTH,1.32,1.91,44.50,47.26,127492.0,5375.0,286498.0,761.00,60.87,64.0,H-SC,10.15,173.0,0.04,1.93,25.78,XY24,NTT,INSURANCE
25,FINCABLES,0.33,32.12,57.37,107.91,111906.0,47416.0,195060.0,1641.55,18.72,56.0,M-SC,25.35,220.0,0.42,1.32,46.75,OX40N,ATH,CABLES
68,SATIN,-2.21,20.59,25.91,51.83,86326.0,56892.0,333176.0,274.00,7.75,70.0,H-SC,30.75,159.0,0.66,2.25,62.31,XY24,NTT,FINANCE
91,ZYDUSLIFE,-0.42,9.30,24.09,35.63,55179.0,19481.0,229055.0,1286.17,-4.95,70.0,H-MC,3.05,120.0,0.35,1.55,20.43,AR,ATH,PHARMA
73,SONACOMS,-0.73,1.08,37.60,39.09,38447.0,1093.0,102252.0,804.02,-19.93,54.0,M-MC,19.01,193.0,0.03,0.69,44.65,AR,ATH,AUTO

In [16]:
# top 5 to book for rotation from weak conviction
df_tmp = df_portfolio_features[~df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])]
df_tmp = df_tmp[~df_tmp['Criteria'].isin(['XY25','XY24','X40', 'X40N'])].sort_values(by = 'RRR Ind', ascending=False)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
25,FINCABLES,0.33,32.12,57.37,107.91,111906.0,47416.0,195060.0,1641.55,18.72,56.0,M-SC,25.35,220.0,0.42,1.32,46.75,OX40N,ATH,CABLES
91,ZYDUSLIFE,-0.42,9.30,24.09,35.63,55179.0,19481.0,229055.0,1286.17,-4.95,70.0,H-MC,3.05,120.0,0.35,1.55,20.43,AR,ATH,PHARMA
73,SONACOMS,-0.73,1.08,37.60,39.09,38447.0,1093.0,102252.0,804.02,-19.93,54.0,M-MC,19.01,193.0,0.03,0.69,44.65,AR,ATH,AUTO
42,INDIAMART,1.61,-12.76,136.95,106.72,147360.0,-15735.0,107601.0,4810.62,-60.74,47.0,H-SC,10.29,140.0,-0.11,0.73,4.17,AR,ATH,MISC
90,WIPRO,1.33,-18.08,110.27,72.27,153076.0,-30629.0,138819.0,420.00,-25.96,54.0,M-LC,13.99,98.0,-0.20,0.94,6.51,XR,NTT,IT

In [17]:
# top 5 to accumulate based on lowest RSI_14
df_tmp = df_portfolio_features[df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])].sort_values(by = 'RSI_14', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
23,DMART,-0.17,-0.55,30.32,29.60,75264.0,-1368.0,248232.0,5391.45,-16.12,35.0,X-LC,5.60,14.0,-0.02,1.67,13.46,X40N,ATH,FMCG
40,ICICIPRULI,0.17,-15.59,54.87,30.73,91245.0,-30712.0,166293.0,790.00,-38.22,37.0,X-MC,12.18,78.0,-0.34,1.12,1.33,X40,ATH,INSURANCE
27,GLAXO,-1.11,-6.84,49.36,39.15,91640.0,-13628.0,185656.0,3466.20,-28.86,38.0,X-MC,6.33,56.0,-0.15,1.25,2.71,X40,ATH,PHARMA
26,GILLETTE,-0.38,-9.55,43.42,29.72,99714.0,-24246.0,229650.0,10978.86,-30.50,38.0,X-SC,8.74,83.0,-0.24,1.55,5.54,X40,ATH,FMCG
33,HCLTECH,-0.14,-24.19,60.28,21.51,110558.0,-58517.0,183407.0,1872.35,-20.18,38.0,X-LC,18.50,8.0,-0.53,1.24,3.93,X40,ATH,IT

In [18]:
# top 5 to accumulate based on Spread and CumlRnk
df_tmp = df_portfolio_features[df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])]
df_tmp = df_tmp[(df_tmp['CumlRnk'] < 100)].sort_values(by = 'Spread%', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
88,VOLTAS,-1.72,-0.37,45.74,45.20,87375.0,-717.0,191025.0,1856.00,14.09,41.0,X-MC,1.92,79.0,-0.01,1.29,4.37,XY25,NTT,AC
84,UNITDSPR,-0.93,-6.52,29.18,20.77,63871.0,-15257.0,218887.0,1644.00,-17.10,44.0,X-MC,3.33,64.0,-0.24,1.48,4.41,X40N,NTT,BREWERIES
65,RELIANCE,-0.74,-13.37,44.64,25.30,77717.0,-26865.0,174098.0,1952.00,-15.80,44.0,X-LC,3.71,21.0,-0.35,1.17,3.45,XY25,BTT,REFINERIES
39,ICICIGI,0.91,-4.60,25.09,19.34,47898.0,-9203.0,190906.0,2252.93,-19.83,49.0,X-MC,4.98,66.0,-0.19,1.29,6.62,X40,ATH,INSURANCE
19,COLPAL,-0.94,-17.80,72.15,41.51,156198.0,-46875.0,216490.0,3726.84,-0.47,57.0,X-MC,5.50,62.0,-0.30,1.46,21.03,XY25,ATH,FMCG

In [19]:
# top 5 to accumulate based on lowest Gained%
df_tmp = df_portfolio_features[df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])].sort_values(by = 'Gained%', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
40,ICICIPRULI,0.17,-15.59,54.87,30.73,91245.0,-30712.0,166293.0,790.00,-38.22,37.0,X-MC,12.18,78.0,-0.34,1.12,1.33,X40,ATH,INSURANCE
32,HAVELLS,0.16,-22.55,70.53,32.08,179172.0,-73954.0,254037.0,2062.85,-27.08,42.0,X-MC,12.32,63.0,-0.41,1.71,2.46,X40,ATH,ELECTRICAL
27,GLAXO,-1.11,-6.84,49.36,39.15,91640.0,-13628.0,185656.0,3466.20,-28.86,38.0,X-MC,6.33,56.0,-0.15,1.25,2.71,X40,ATH,PHARMA
65,RELIANCE,-0.74,-13.37,44.64,25.30,77717.0,-26865.0,174098.0,1952.00,-15.80,44.0,X-LC,3.71,21.0,-0.35,1.17,3.45,XY25,BTT,REFINERIES
79,TCS,-0.01,-31.68,85.27,26.57,269879.0,-146774.0,316499.0,4311.59,-42.31,40.0,X-LC,17.06,2.0,-0.54,2.14,3.62,X40,ATH,IT

In [20]:
# top 5 to accumulate based on lowest CurrAlloc%
df_tmp = df_portfolio_features[df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])].sort_values(by = 'CurrAlloc%', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
64,RELAXO,0.86,-61.95,300.27,52.31,165851.0,-89926.0,55234.0,1176.00,-59.44,48.0,X-SC,25.08,92.0,-0.54,0.37,23.50,X40N,NTT,FOOTWEAR
10,BATAINDIA,0.28,-55.57,204.30,35.20,116798.0,-71500.0,57170.0,2096.00,-25.05,40.0,X-SC,25.95,91.0,-0.61,0.39,13.38,X40,NTT,FOOTWEAR
60,QUESS,-0.22,-17.39,110.51,73.90,97494.0,-18571.0,88222.0,424.00,-55.37,49.0,X-SC,11.19,80.0,-0.19,0.60,20.27,XY24,NTT,MISC
28,GODREJCP,-0.55,-8.96,44.41,31.47,60087.0,-13313.0,135301.0,1469.04,-4.16,41.0,X-LC,8.22,32.0,-0.22,0.91,3.81,X40N,ATH,FMCG
53,M&M,-0.74,0.56,22.70,23.38,31656.0,774.0,139455.0,3802.40,-14.78,45.0,X-LC,8.81,25.0,0.02,0.94,5.73,X40N,ATH,AUTO

In [21]:
# top 5 to accumulate based on CumlRnk
df_tmp = df_portfolio_features.sort_values(by = 'CumlRnk', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
47,ITC,0.16,-18.86,46.73,19.06,128981.0,-64153.0,276013.0,452.00,-55.52,51.0,X-LC,15.11,1.0,-0.50,1.86,7.07,X40,NTT,FMCG
79,TCS,-0.01,-31.68,85.27,26.57,269879.0,-146774.0,316499.0,4311.59,-42.31,40.0,X-LC,17.06,2.0,-0.54,2.14,3.62,X40,ATH,IT
45,INFY,-1.05,-19.59,66.95,34.24,168444.0,-61292.0,251596.0,1972.00,-36.87,48.0,X-LC,19.28,3.0,-0.36,1.70,7.87,X40,NTT,IT
81,TMPV,0.03,-17.75,66.04,36.58,193295.0,-63147.0,292694.0,600.00,-82.53,59.0,X-LC,6.11,4.0,-0.33,1.97,22.00,XY24,NTT,AUTO
59,PIDILITIND,1.18,4.37,13.41,18.37,19750.0,6170.0,147280.0,1670.26,-26.86,61.0,X-LC,5.54,5.0,0.31,0.99,15.64,X40,ATH,CHEMICALS

In [22]:
# top 5 for average up
df_tmp = df_portfolio_features[(df_portfolio_features['Dev%_200'] > 5)].sort_values(by = 'CurrAlloc%', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
44,INDUSINDBK,0.31,-33.56,100.01,32.89,51302.0,-25910.0,51297.0,1800.00,-341.60,53.0,L-MC,8.20,258.0,-0.51,0.35,26.26,XR,NTT,BANKS
72,SIS,-0.81,-10.02,34.76,21.26,34728.0,-11123.0,99909.0,528.00,2375.65,63.0,H-SC,15.18,168.0,-0.32,0.67,48.55,OX40N,NTT,MISC
73,SONACOMS,-0.73,1.08,37.60,39.09,38447.0,1093.0,102252.0,804.02,-19.93,54.0,M-MC,19.01,193.0,0.03,0.69,44.65,AR,ATH,AUTO
75,SURYODAY,-0.79,-9.05,35.27,23.03,57446.0,-16197.0,162874.0,216.00,77.63,54.0,H-SC,16.78,166.0,-0.28,1.10,37.14,XR,NTT,BANKS
5,ATULAUTO,0.57,-15.88,73.04,45.57,121126.0,-31297.0,165835.0,844.00,3591.89,52.0,M-SC,8.15,248.0,-0.26,1.12,27.62,XY24,NTT,AUTO

In [23]:
# top 5 RSP
df_tmp = df_portfolio_features.sort_values(by = 'RSP', ascending=False)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
68,SATIN,-2.21,20.59,25.91,51.83,86326.0,56892.0,333176.0,274.00,7.75,70.0,H-SC,30.75,159.0,0.66,2.25,62.31,XY24,NTT,FINANCE
3,ALKYLAMINE,-1.93,-25.79,160.93,93.63,120574.0,-26040.0,74923.0,4546.37,-20.57,62.0,H-SC,14.08,142.0,-0.22,0.51,41.47,SR,ATH,CHEMICALS
72,SIS,-0.81,-10.02,34.76,21.26,34728.0,-11123.0,99909.0,528.00,2375.65,63.0,H-SC,15.18,168.0,-0.32,0.67,48.55,OX40N,NTT,MISC
56,MEDANTA,0.01,6.09,19.82,27.12,37117.0,10753.0,187270.0,1486.00,2.89,67.0,X-SC,8.96,87.0,0.29,1.26,29.04,XY24,NTT,HEALTHCARE
17,CIPLA,0.17,13.50,18.67,34.69,32455.0,20675.0,173836.0,1663.60,-12.20,63.0,X-LC,10.25,18.0,0.64,1.17,17.57,X40N,ATH,PHARMA

In [24]:
# Top N allocation
df_tmp = df_portfolio_features.sort_values(by = 'CurrAlloc%', ascending=False)
top_n_values = [10, 25, 50]

sum_df = pd.DataFrame({
    'Top_N': top_n_values,
    'Sum_Alloc%': [df_tmp['CurrAlloc%'].head(n).sum() for n in top_n_values]
})

sum_df

   Top_N  Sum_Alloc%
0     10       19.43
1     25       42.81
2     50       72.84

In [25]:
# market-cap-wise allocation
df_tmp = df_portfolio_features[cols]
df_tmp.groupby(df_tmp['Conviction'].str[-2:])['CurrAlloc%'].sum().sort_values(ascending=False)

Conviction
SC    42.60
LC    31.61
MC    25.77
Name: CurrAlloc%, dtype: float64

In [26]:
# criteria-wise allocation
df_portfolio_features.groupby('Criteria')['CurrAlloc%'].sum().sort_values(ascending=False)

Criteria
XY24     27.38
X40      25.60
X40N     16.84
XR        8.90
OX40N     6.97
AR        6.80
XY25      6.63
SR        0.86
Name: CurrAlloc%, dtype: float64

In [27]:
# conviction-wise allocation
df_portfolio_features.groupby('Conviction')['CurrAlloc%'].sum().sort_values(ascending=False)

Conviction
X-LC    29.42
H-SC    22.29
X-MC    20.78
M-SC    10.01
X-SC     9.80
H-MC     2.71
M-MC     1.93
H-LC     1.25
M-LC     0.94
L-SC     0.50
L-MC     0.35
Name: CurrAlloc%, dtype: float64

In [28]:
# sector-wise stats
df_tmp = df_portfolio_features.groupby('Category')[['CurrAlloc%', 'Current', 'Current P/L', 'FTT Amt']].sum().sort_values(by=['Current', 'Current P/L'], ascending=False)
df_tmp['Current P/L%'] = round(df_tmp['Current P/L'] * 100 / df_tmp['Current'], 2)
df_tmp['FTT%'] = round(df_tmp['FTT Amt'] * 100 / df_tmp['Current'], 2)
cols = ['CurrAlloc%', 'Current P/L%', 'FTT%']
df_tmp[cols].sort_values(by=['CurrAlloc%'], ascending=False)

               CurrAlloc%  Current P/L%    FTT%
Category
FMCG                15.30        -16.60   57.69
FINANCE             10.76        -15.48   65.70
IT                  10.37        -46.68  120.53
MISC                 6.87        -31.57   88.72
AUTO                 6.71        -10.08   51.34
BANKS                5.57        -10.16   61.09
PAINTS               5.54        -19.97   40.80
INSURANCE            5.36         -4.26   39.74
PHARMA               5.09          1.85   29.70
ELECTRICAL           4.14        -14.97   55.89
CHEMICALS            2.17        -26.12  101.28
HEALTHCARE           2.06        -17.10   47.67
APPARELS             1.81          0.10   33.97
AC                   1.81        -19.34   51.71
TRAVEL               1.69        -79.13  168.83
FOOTWEAR             1.67        -78.61  150.23
DURABLES             1.65        -57.58   95.91
BREWERIES            1.48         -6.97   29.18
REALTY               1.35        -10.66   28.84
CERAMICS             1.35        -53.87  100.61
CABLES               1.32         24.31   57.37
REFINERIES           1.17        -15.43   44.64
ENGINEERING          1.16        -41.08  105.60
CEMENT               1.10        -64.20  187.04
JEWELLERY            1.06       -103.67  174.43
ENTERTAINMENT        0.70        -84.96  195.27
TEXTILES             0.41        -51.77   95.04
HOTELS               0.31       -143.68  229.63

In [29]:
# money to be made criteria-wise
df_portfolio_features.groupby('Criteria')['FTT Amt'].agg(['sum', 'count']).sort_values(by='sum', ascending=False)

                sum  count
Criteria
XY24      3537840.0     21
X40       1908218.0     19
XR        1362067.0     13
X40N      1225287.0     13
AR        1176466.0      9
OX40N      758265.0     10
XY25       457354.0      5
SR         292149.0      2

In [30]:
# money to be made conviction-wise
df_portfolio_features.groupby('Conviction')['FTT Amt'].agg(['sum', 'count']).sort_values(by='sum', ascending=False)

                  sum  count
Conviction
H-SC        3481148.0     24
X-LC        1934828.0     21
X-MC        1650924.0     15
M-SC        1434873.0     14
X-SC        1350902.0      9
H-MC         297025.0      2
L-SC         215812.0      2
M-LC         153076.0      1
M-MC         100207.0      2
L-MC          51302.0      1
H-LC          47549.0      1

In [31]:
# money to be made criteria and conviction-wise
df_portfolio_features.groupby(['Conviction', 'Criteria'])['FTT Amt'].agg(['sum', 'count']).sort_values(by='sum', ascending=False)

                           sum  count
Conviction Criteria
H-SC       XY24      1084998.0      6
X-LC       X40       1018294.0     10
H-SC       AR         958717.0      5
M-SC       XY24       850539.0      6
H-SC       XR         817705.0      7
X-SC       XY24       791887.0      4
X-MC       X40        673412.0      7
           X40N       508381.0      4
X-LC       X40N       374403.0      6
           XY24       343012.0      2
X-SC       X40N       342503.0      3
H-SC       OX40N      327579.0      4
M-SC       OX40N      321877.0      5
H-SC       SR         292149.0      2
X-MC       XY25       243573.0      2
H-MC       XY24       241846.0      1
X-MC       XY24       225558.0      2
X-SC       X40        216512.0      2
M-SC       XR         185883.0      2
M-LC       XR         153076.0      1
X-LC       XY25       152021.0      2
L-SC       OX40N      108809.0      1
           XR         107003.0      1
M-SC       AR          76574.0      1
M-MC       XY25        61760.0      1
H-MC       AR          55179.0      1
L-MC       XR          51302.0      1
H-LC       AR          47549.0      1
X-LC       XR          47098.0      1
M-MC       AR          38447.0      1

In [32]:
# notebook execution time

end_time = time.time()
execution_time = round(end_time - start_time, 0)
print(f"Notebook execution time: {execution_time} seconds")

Notebook execution time: 54.0 seconds