<a href="https://colab.research.google.com/github/ankit-rathi/Quantvesting_v2/blob/main/myStocks_Portfolio_Analysis.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
'''
!pip install pandas==2.2.2 -qq
!pip install pyxirr -qq
!pip install ta -qq
!pip install yfinance==0.2.59 -qq
'''

'\n!pip install pandas==2.2.2 -qq\n!pip install pyxirr -qq\n!pip install ta -qq\n!pip install yfinance==0.2.59 -qq\n'

In [2]:
# import libraries

import numpy as np
import pandas as pd
import datetime
import warnings
warnings.filterwarnings('ignore')
import yfinance as yfin
import ta
import matplotlib.pyplot as plt
import requests

In [3]:
# notebook start time
import time
import datetime
import pytz

start_time = time.time()

# function to print date timestamp
def print_date_time():
  tz_NY = pytz.timezone('Asia/Kolkata')
  datetime_NY = datetime.datetime.now(tz_NY)
  print("Run date time (IST):", datetime_NY.strftime("%Y-%m-%d %H:%M:%S"))

In [4]:
# function to get booked and reserved amount
def get_amt():
  # fetch the JSON data from the URL
  url = "https://raw.githubusercontent.com/ankit-rathi/Tradevesting_v1/main/data/myPortfolioAmts.json"
  response = requests.get(url)
  pf_amts = response.json()  # parse the JSON data

  # extract values from the JSON
  py_booked_amt_dm = pf_amts["py_booked_amt_dm"]
  py_booked_amt_sv = pf_amts["py_booked_amt_sv"]
  cy_booked_amt_dm = pf_amts["cy_booked_amt_dm"]
  cy_booked_amt_sv = pf_amts["cy_booked_amt_sv"]
  reserve_amt_dm = pf_amts["reserve_amt_dm"]
  reserve_amt_sv = pf_amts["reserve_amt_sv"]

  # perform calculations
  py_booked_amt = py_booked_amt_dm + py_booked_amt_sv
  cy_booked_amt = cy_booked_amt_dm + cy_booked_amt_sv
  reserve_amt = reserve_amt_dm + reserve_amt_sv
  total_booked_amt = py_booked_amt + cy_booked_amt

  return total_booked_amt, reserve_amt, cy_booked_amt, py_booked_amt

gen_output = 0

In [5]:
# function to format the amount
def format_amt(number):
    abs_number = abs(number)

    if abs_number >= 1_00_00_000:  # Crores
        formatted_amt = f"{number / 1_00_00_000:.2f} C"
    elif abs_number >= 1_00_000:  # Lakhs
        formatted_amt = f"{number / 1_00_000:.2f} L"
    elif abs_number >= 1_000:  # Thousands
        formatted_amt = f"{number / 1_000:.2f} K"
    else:
        formatted_amt = f"{number:.2f}"

    return formatted_amt

# function to set start and end date
def get_start_end_date():
  start_date = (datetime.date.today() + datetime.timedelta(days=-365)).strftime('%Y-%m-%d')
  end_date = (datetime.date.today() + datetime.timedelta(days=1)).strftime('%Y-%m-%d')
  return start_date, end_date

# function to fetch my portfolio csv
def get_mypfs_df():
  mypfs_df = pd.read_csv('https://raw.githubusercontent.com/ankit-rathi/Tradevesting_v1/main/data/myPortfolioStocks.csv')
  return mypfs_df

# function to fetch my prospects csv
def get_mypps_df():
  mypps_df = pd.read_csv('https://raw.githubusercontent.com/ankit-rathi/Tradevesting_v1/main/data/myProspectsScrips.csv')
  return mypps_df

# function to fetch screener data
def get_myscreen_df():
  myscreen_df = pd.read_csv('https://raw.githubusercontent.com/ankit-rathi/Tradevesting_v1/main/data/myScreenerDB.csv')
  return myscreen_df

# function to fetch momentum data
def get_myinvmt_df():
  myinvmt_df = pd.read_csv('https://raw.githubusercontent.com/ankit-rathi/Tradevesting_v1/main/data/myInvestments.csv')
  return myinvmt_df

# function to get the stock ids
def get_stock_ids(df_pf):
  stock_n100 = df_pf['Symbol'].unique()

  exclude = ['CADILAHC','MMTC', 'MASFIN']

  stock_ids = df_pf[~df_pf['Symbol'].isin(exclude) ]['Symbol'].unique()

  #mypf = mypf[mypf.Forecast.notnull()]
  #stock_ids = mypf['Symbol'].unique()

  #stock_ids.sort()
  return stock_ids

# get features from screener data
def get_screener_features():
  myscreen_df = get_myscreen_df()
  cols = ['Symbol', 'EPS', 'MedPE', 'ROCE%', 'ROE%', 'CapType']
  return myscreen_df[cols]

# get relative strength
def get_relative_strength(stock_list):

    # Dictionary to store stock tickers and their corresponding percentage price change
    stock_changes = {}

    # Loop through each stock and fetch its price data
    for stock in stock_list:
        try:
            # Download the stock data for the given date range
            stock_data = yfin.Ticker(stock + '.NS').history(period='1mo', interval='1d')[map(str.title, ['open', 'close', 'low', 'high', 'volume'])]

            # Calculate the percentage change for the stock
            if len(stock_data) > 0:
                start_price = stock_data['Close'].iloc[0]
                end_price = stock_data['Close'].iloc[-1]
                percent_change = round(((end_price - start_price) / start_price) * 100, 2)
                stock_changes[stock] = percent_change
            else:
                stock_changes[stock] = np.nan  # If no data is available, set to NaN

        except Exception as e:
            print(f"Error fetching data for {stock}: {e}")
            stock_changes[stock] = np.nan

    # Create a DataFrame with stock tickers and their percentage changes
    df = pd.DataFrame(list(stock_changes.items()), columns=['Symbol', 'Percent_Change'])

    # Drop any stocks with missing data (NaN values)
    df = df.dropna()

    # Calculate the percentile rank based on percentage change
    df['RSP'] = round(df['Percent_Change'].rank(pct=True) * 100, 2)
    cols = ['Symbol', 'RSP']
    df = df[cols]
    # Sort by percentile rank (optional)
    df = df.sort_values(by='RSP', ascending=False).reset_index(drop=True)

    return df

In [6]:
# function to get stock technicals
def stock_prec_dev(stock_symbol):
    #stock_symbol = 'ULTRACEMCO.NS'
    short_window = 20
    mid_window = 50
    long_window = 200
    moving_avg = 'SMA'

    start = datetime.datetime(*map(int, start_date.split('-')))
    end = datetime.datetime(*map(int, end_date.split('-')))

    stock_df = yfin.Ticker(stock_symbol + '.NS').history(period='max', interval='1d')[map(str.title, ['open', 'close', 'low', 'high', 'volume'])]

    stock_df['Max'] = round(max(stock_df['Close']),2)
    stock_df = stock_df[(stock_df.index <= end_date) & (stock_df.index >= start_date)]
    stock_df['200_SMA'] = round(stock_df['Close'].rolling(window = 200, min_periods = 1).mean(),0)
    stock_df['Dev%_200'] = round((stock_df['Close'] - stock_df['200_SMA'])*100/stock_df['200_SMA'],2)
    stock_df.dropna(axis = 0, inplace = True) # remove any null rows

    stock_df['20_SMA'] = stock_df['Close'].rolling(window=20).mean()
    stock_df['50_SMA'] = stock_df['Close'].rolling(window=50).mean()
    stock_df['Symbol'] = stock_symbol

    stock_df['Close'] = round(stock_df['Close'],2)
    stock_df['Min'] = round(min(stock_df['Close']),2)
    stock_df['RSI_14'] = ta.momentum.RSIIndicator(close=stock_df['Close'], window=14).rsi()
    stock_df['RSI_14'] = round(stock_df['RSI_14'],0)
    stock_df['Prev_Close'] = stock_df['Close'].shift(1)
    stock_df.drop(['Open', 'Low', 'High', 'Volume'], axis=1, inplace=True)
    stock_df = stock_df.tail(1)

    max_SMA = max(stock_df['20_SMA'].item(), stock_df['50_SMA'].item(), stock_df['200_SMA'].item())
    min_SMA = min(stock_df['20_SMA'].item(), stock_df['50_SMA'].item(), stock_df['200_SMA'].item())
    ABS_Spread = max_SMA - min_SMA
    stock_df['Spread%'] = round((ABS_Spread / stock_df['200_SMA'].item()) * 100,2)

    return stock_df

# function to compute stock attributes
def get_common_features(stock_ids, df_mypf):

  df_prec_dev = pd.DataFrame()
  df_tmp = get_screener_features()
  df_rs = get_relative_strength(stock_ids)

  for stock_id in stock_ids:
      tmp = stock_prec_dev(stock_id)
      tmp = tmp.reset_index()
      df_prec_dev = pd.concat([df_prec_dev, tmp], ignore_index = True)
  df_prec_dev = pd.merge(df_prec_dev, df_mypf, on= 'Symbol')
  df_prec_dev = pd.merge(df_prec_dev, df_tmp, on= 'Symbol', how='left')
  df_prec_dev = pd.merge(df_prec_dev, df_rs, on= 'Symbol', how='left')
  #print(df_prec_dev.columns)
  df_prec_dev['Curr_PE'] = round(df_prec_dev['Close']/df_prec_dev['EPS'],1)
  df_prec_dev['Dev%_PE'] = round((df_prec_dev['Curr_PE'] - df_prec_dev['MedPE'])*100/df_prec_dev['MedPE'],2)
  df_prec_dev['Conviction'] = df_prec_dev['Conviction'] + '-' + df_prec_dev['CapType']
  return df_prec_dev

# function to arrange stock features
def arrange_features(df_stocks, common_cols, diff_cols):
  df_stocks_common = df_stocks[common_cols].drop_duplicates()
  df_stocks_diff = df_stocks[diff_cols]
  df_stocks_diff['Investment'] = df_stocks_diff['AvgCost'] * df_stocks_diff['Shares']
  df_stocks_diff = df_stocks_diff.groupby(['Symbol'])[['Shares', 'Investment']].aggregate(['sum']).reset_index()
  df_stocks_diff.columns = ['Symbol', 'Shares', 'Investment']
  df_stocks_diff['AvgCost'] = round(df_stocks_diff['Investment']/df_stocks_diff['Shares'],2)
  df_stocks = pd.merge(df_stocks_diff, df_stocks_common, on='Symbol')
  return df_stocks

# plot fact distribution across dimension
def plot_pie_chart(df, dimension, fact):
  # grouping the data by category and calculating the sum of fact for each type
  grouped_data = df.groupby(dimension)[fact].sum()

  # sorting the grouped data in descending order
  grouped_data = grouped_data.sort_values(ascending=False)

  # creating a pie chart
  grouped_data.plot.pie(autopct='%1.1f%%', startangle=90, figsize=(6, 6))

  # adding a title and displaying the plot
  plt.title(f'{dimension} {fact} Distribution')
  plt.ylabel('')  # To hide the y-label
  plt.show()

In [7]:
# function to get portfolio features

def get_portfolio_features(df_common_features):

  print_date_time()
  print('-------------------')

  #df_common_features["Target"] = df_common_features["Target"].fillna(df_common_features["Max"])
  df_common_features['NTT'] = np.where(df_common_features['Strategy']== 'NTT', df_common_features["Target"], df_common_features['Max'])
  df_common_features['LTT'] = np.where(df_common_features['Strategy']== 'BTT', df_common_features["Target"], df_common_features['Max'])
  df_common_features['BOL'] = df_common_features['Min']

  tmp_df = df_common_features[df_common_features['Symbol'].isin(mypf_df[mypf_df['InPortfolio'] != 'NA'].Symbol.values)]
  print('qualified stocks: '+str(len(tmp_df['Symbol'].unique())))
  tmp_df1 = tmp_df[tmp_df['LatestQtr'] == 1]
  print('with latest results: '+str(len(tmp_df1['Symbol'].unique())))
  tmp_df1 = tmp_df1[tmp_df1['StarStock'] == 1]
  print('still star stocks: '+str(len(tmp_df1['Symbol'].unique())))
  tmp_df['Investment'] = tmp_df['AvgCost'] * tmp_df['Shares']
  tmp_df['Current'] = round(tmp_df['Close'] * tmp_df['Shares'],0)
  tmp_df['Previous'] = tmp_df['Prev_Close'] * tmp_df['Shares']
  tmp_df['EstimatedST'] = tmp_df['NTT'] * tmp_df['Shares']
  tmp_df['EstimatedLT'] = tmp_df['LTT'] * tmp_df['Shares']
  tmp_df['Current P/L'] = round((tmp_df['Current'] - tmp_df['Investment']),0)
  tmp_df['Today P/L%'] = round((tmp_df['Current'] - tmp_df['Previous'])*100/tmp_df['Previous'],2)
  tmp_df['Current P/L%'] = round((tmp_df['Current'] - tmp_df['Investment'])*100/tmp_df['Investment'],2)
  tmp_df['EstimatedST P/L%'] = round((tmp_df['EstimatedST'] - tmp_df['Investment'])*100/tmp_df['Investment'],2)
  tmp_df['EstimatedLT P/L%'] = round((tmp_df['EstimatedLT'] - tmp_df['Investment'])*100/tmp_df['Investment'],2)
  tmp_df['NTT%'] = round((tmp_df['NTT'] - tmp_df['Close'])*100/tmp_df['Close'],2)
  tmp_df['LTT%'] = round((tmp_df['LTT'] - tmp_df['Close'])*100/tmp_df['Close'],2)
  tmp_df['Gained%'] = round((tmp_df['Close'] - tmp_df['BOL'])*100/tmp_df['BOL'],2)
  investment = round(sum(tmp_df['AvgCost']*tmp_df['Shares']),0)
  current = round(sum(tmp_df['Close']*tmp_df['Shares']),0)
  tmp_df['InitAlloc%'] = round(tmp_df['Investment']*100/investment,2)
  tmp_df['CurrAlloc%'] = round(tmp_df['Current']*100/current,2)
  tmp_df['FTT'] = tmp_df['LTT']
  tmp_df.loc[tmp_df['Strategy'] == 'NTT', 'FTT'] = tmp_df['NTT']
  tmp_df['FTT%'] = tmp_df['LTT%']
  tmp_df.loc[tmp_df['Strategy'] == 'NTT', 'FTT%'] = tmp_df['NTT%']
  tmp_df['FTT Amt'] = round(tmp_df['FTT%'] * tmp_df['Current']/100,0)
  tmp_df['OTT%'] = round((tmp_df['FTT'] - tmp_df['AvgCost'])*100/tmp_df['AvgCost'],2)
  tmp_df['RRR Ind'] = round(tmp_df['Current P/L']/tmp_df['FTT Amt'],2)
  tmp_df['Risk Ind'] = round(tmp_df['Current P/L%']*tmp_df['CurrAlloc%'],0)

  return tmp_df

# function to print portfolio features
def print_portfolio_stats(df_portfolio_features, myinvmt_df):
  from pyxirr import xirr

  total_booked_amt, reserve_amt, cy_booked_amt, py_booked_amt = get_amt()

  dates = myinvmt_df['Date'].values
  dates = np.append(dates, datetime.date.today().strftime('%d-%b-%y'))
  investment = myinvmt_df['Investment'].values
  dates= pd.to_datetime(dates)

  current = round(sum(df_portfolio_features['Close']*df_portfolio_features['Shares']),0) + reserve_amt
  investment_xirr = np.append(investment, current)
  cagr = round(xirr(pd.DataFrame({"dates": dates, "amounts": investment_xirr}))*100,2)

  investment = -sum(investment)
  invested = round(sum(df_portfolio_features['AvgCost']*df_portfolio_features['Shares']),0) + reserve_amt
  previous = round(sum(df_portfolio_features['Prev_Close']*df_portfolio_features['Shares']),0) + reserve_amt
  cy_invested = investment + py_booked_amt

  today_pnl_amount = current-previous
  today_pnl_percentage = round((current-previous)*100/previous,2)

  curr_pnl_amount = current-invested
  curr_pnl_percentage = round((curr_pnl_amount)*100/(cy_invested),2)

  cy_pnl_amount = cy_booked_amt + curr_pnl_amount
  cy_pnl_percentage = round((cy_pnl_amount)*100/cy_invested,2)

  overall_pnl_amount = total_booked_amt + curr_pnl_amount
  overall_pnl_percentage = round((overall_pnl_amount)*100/investment,2)

  estimate_st = round(sum(df_portfolio_features['FTT']*df_portfolio_features['Shares']),0)  + reserve_amt
  est_st_pnl_amount = estimate_st-current
  est_st_pnl_percentage = round((est_st_pnl_amount)*100/current,2)

  estimate_lt = round(sum(df_portfolio_features['LTT']*df_portfolio_features['Shares']),0)  + reserve_amt
  est_lt_pnl_amount = estimate_lt-current
  est_lt_pnl_percentage = round((est_lt_pnl_amount)*100/current,2)

  total_profit = round(sum(df_portfolio_features[df_portfolio_features['Current P/L%'] > 0]['Current']) - sum(df_portfolio_features[df_portfolio_features['Current P/L%'] > 0]['Investment']),0)
  total_loss = round(sum(df_portfolio_features[df_portfolio_features['Current P/L%'] < 0]['Current']) - sum(df_portfolio_features[df_portfolio_features['Current P/L%'] < 0]['Investment']),0)

  cy_booked_percentage = round((cy_booked_amt)*100/current,2)
  py_booked_percentage = round((py_booked_amt)*100/investment,2)
  total_booked_percentage = round((total_booked_amt)*100/investment,2)

  print('-------------------')
  print('Initial Investment: ', format_amt(investment))
  print('CY Investment: ', format_amt(cy_invested))
  print('Reserve: ', format_amt(reserve_amt))
  print('Current: ',  format_amt(current))
  print('-------------------')
  print('Today PnL: '+ '{} ({}%)'.format(format_amt(today_pnl_amount), today_pnl_percentage))
  print('Current PnL: '+ '{} ({}%)'.format(format_amt(curr_pnl_amount), curr_pnl_percentage))
  print('CY Booked + Current PnL: '+ '{} ({}%)'.format(format_amt(cy_pnl_amount), cy_pnl_percentage))
  print('-------------------')
  print('Total profit: ', format_amt(total_profit))
  print('Total loss: ', format_amt(total_loss))
  print('-------------------')
  print('Total Booked + Current PnL: '+ '{} ({}%)'.format(format_amt(overall_pnl_amount), overall_pnl_percentage))
  print('Total Booked PnL: '+ '{} ({}%)'.format(format_amt(total_booked_amt), total_booked_percentage))
  print('Curr Year Booked PnL: '+ '{} ({}%)'.format(format_amt(cy_booked_amt), cy_booked_percentage))
  print('Prev Year Booked PnL: '+ '{} ({}%)'.format(format_amt(py_booked_amt), py_booked_percentage))
  print('===================')
  print('Est FTT: ',  format_amt(estimate_st))
  print('Est FTT PnL: '+ '{} ({}%)'.format(format_amt(est_st_pnl_amount), est_st_pnl_percentage))

  print('===================')
  print('Deployed: ', format_amt(investment))

  print('Current: ', format_amt(current))

  print('CAGR/XIRR %: '+'{}%'.format(cagr))

In [8]:
# get start and end date
start_date, end_date = get_start_end_date()

# get portfolio and prospects data
mypfs_df = get_mypfs_df()
mypps_df = get_mypps_df()
myinvmt_df = get_myinvmt_df()

# merge above datasets
mypf_df = pd.merge(mypfs_df, mypps_df, on="Symbol")

# seggregate dm and sv portfolio
dm_pf = mypf_df[mypf_df['InPortfolio'] == 'DM']
sv_pf = mypf_df[mypf_df['InPortfolio'] == 'SV']

# build portfolio stock dataframe
dm_stocks = get_stock_ids(dm_pf)
sv_stocks = get_stock_ids(sv_pf)
df_stocks = pd.concat([dm_pf,sv_pf], ignore_index = True)

# arrange common and diff stock features
common_cols = ['Symbol', 'Target', 'Criteria', 'Strategy', 'CumlRnk', 'LatestQtr', 'StarStock', 'Conviction', 'Category', 'InFolio', 'XIRR', 'MBQ']
diff_cols = ['Symbol', 'AvgCost', 'Shares']
df_stocks = arrange_features(df_stocks, common_cols, diff_cols)

# get common features
stock_ids = df_stocks['Symbol'].values
df_common_features = get_common_features(stock_ids, df_stocks)

df_common_features.reset_index(drop=True, inplace=True)
df_common_features.drop(['Date'], axis=1, inplace=True)
# get and print portfolio features
df_portfolio_features = get_portfolio_features(df_common_features)

print_portfolio_stats(df_portfolio_features, myinvmt_df)

df = df_portfolio_features
#plot_pie_chart(df, 'CapType', 'Current')
list_ox40n = list(df[df['MBQ'].str.contains('OX40N', na=False)]['Symbol'].values)

Run date time (IST): 2026-05-01 15:15:30
-------------------
qualified stocks: 92
with latest results: 31
still star stocks: 20
-------------------
Initial Investment:  1.40 C
CY Investment:  1.82 C
Reserve:  1.49 K
Current:  1.48 C
-------------------
Today PnL: -1.63 L (-1.09%)
Current PnL: -35.48 L (-19.45%)
CY Booked + Current PnL: -33.40 L (-18.31%)
-------------------
Total profit:  1.29 L
Total loss:  -36.77 L
-------------------
Total Booked + Current PnL: 9.47 L (6.79%)
Total Booked PnL: 44.95 L (32.22%)
Curr Year Booked PnL: 2.08 L (1.41%)
Prev Year Booked PnL: 42.87 L (30.73%)
===================
Est FTT:  2.55 C
Est FTT PnL: 1.08 C (72.95%)
===================
Deployed:  1.40 C
Current:  1.48 C
CAGR/XIRR %: 2.84%

In [9]:
# top 5 near their targets
cols = ['Symbol', 'Today P/L%', 'Current P/L%', 'FTT%', 'OTT%', 'FTT Amt', 'Current P/L', 'Current', 'FTT', 'Dev%_PE', 'RSI_14','Conviction', 'Spread%',  'CumlRnk', 'RRR Ind', 'CurrAlloc%', 'Gained%', 'Criteria', 'Strategy', 'Category']
df_tmp = df_portfolio_features[~df_portfolio_features['Symbol'].isin(['ENRIN','BLUSPRING','DIGITIDE'])]
df_tmp = df_tmp.sort_values(by = 'FTT Amt', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
55,MASFIN,4.30,4.07,16.81,21.57,17141.0,3990.0,101970.0,397.04,-10.12,69.0,H-SC,0.59,167.0,0.23,0.69,31.77,XR,ATH,FINANCE
51,KOTAKBANK,0.34,2.42,18.25,21.11,25882.0,3348.0,141821.0,453.24,-12.01,54.0,X-LC,8.77,12.0,0.13,0.96,8.46,X40,ATH,BANKS
59,PIDILITIND,-0.96,-2.51,21.41,18.37,29454.0,-3540.0,137570.0,1670.26,-31.67,50.0,X-LC,7.25,5.0,-0.12,0.93,8.02,X40,ATH,CHEMICALS
53,M&M,-1.74,0.51,22.76,23.38,31725.0,707.0,139388.0,3802.40,-14.78,46.0,X-LC,8.68,25.0,0.02,0.94,7.03,X40N,ATH,AUTO
73,SONACOMS,1.26,5.05,32.40,39.09,34431.0,5110.0,106269.0,804.02,-16.82,67.0,M-MC,16.35,193.0,0.15,0.72,50.33,AR,ATH,AUTO

In [10]:
# top 5 today
df_tmp = df_portfolio_features.sort_values(by = 'Today P/L%', ascending=False)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
55,MASFIN,4.30,4.07,16.81,21.57,17141.0,3990.0,101970.0,397.04,-10.12,69.0,H-SC,0.59,167.0,0.23,0.69,31.77,XR,ATH,FINANCE
29,GREENPANEL,3.06,-38.98,134.59,43.14,150348.0,-71370.0,111708.0,537.00,150.00,68.0,M-SC,18.76,225.0,-0.47,0.76,34.19,XY24,NTT,MISC
11,BERGEPAINT,2.00,-12.81,43.73,25.32,98271.0,-33027.0,224722.0,680.00,-17.61,60.0,X-MC,13.72,68.0,-0.34,1.52,16.96,XY24,NTT,PAINTS
73,SONACOMS,1.26,5.05,32.40,39.09,34431.0,5110.0,106269.0,804.02,-16.82,67.0,M-MC,16.35,193.0,0.15,0.72,50.33,AR,ATH,AUTO
45,INFY,1.22,-19.55,66.86,34.24,168302.0,-61165.0,251723.0,1972.00,-36.87,36.0,X-LC,13.58,3.0,-0.36,1.70,2.58,X40,NTT,IT

In [11]:
# bottom 5 today
df_tmp = df_portfolio_features.sort_values(by = 'Today P/L%', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
61,RAJESHEXPO,-4.56,-76.97,334.56,0.07,105681.0,-105589.0,31588.0,518.00,1057.83,51.0,L-SC,32.94,268.0,-1.00,0.21,48.30,OX40N,NTT,JEWELLERY
77,TANLA,-4.12,-42.14,275.49,117.25,431574.0,-114104.0,156657.0,1922.32,-41.68,57.0,H-SC,19.10,147.0,-0.26,1.06,37.16,AR,ATH,IT
20,DABUR,-3.18,-13.68,66.48,43.70,142352.0,-33940.0,214128.0,735.00,-21.68,47.0,X-MC,12.37,70.0,-0.24,1.45,7.56,XY24,BTT,FMCG
81,TMPV,-3.16,-22.25,75.67,36.58,209346.0,-79185.0,276656.0,600.00,-83.62,49.0,X-LC,5.17,4.0,-0.38,1.87,15.31,XY24,NTT,AUTO
72,SIS,-3.11,-18.37,48.54,21.26,43997.0,-20392.0,90640.0,528.00,2146.11,70.0,H-SC,8.09,168.0,-0.46,0.61,34.77,OX40N,NTT,MISC

In [12]:
# top 5 to exit based on CumlRnk
df_tmp = df_portfolio_features[~df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])]
df_tmp = df_tmp[(df_tmp['Current P/L%'] > -1) & (df_tmp['Current P/L%'] < 1)].sort_values(by = 'CumlRnk', ascending=False)
df_tmp[cols].head()

Empty DataFrame
Columns: [Symbol, Today P/L%, Current P/L%, FTT%, OTT%, FTT Amt, Current P/L, Current, FTT, Dev%_PE, RSI_14, Conviction, Spread%, CumlRnk, RRR Ind, CurrAlloc%, Gained%, Criteria, Strategy, Category]
Index: []

In [13]:
# OX40N stocks to exit
df_tmp = df_portfolio_features[(df_portfolio_features['Symbol'].isin(list_ox40n))].sort_values(by = 'Current P/L%', ascending=False)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
25,FINCABLES,-1.27,25.46,65.72,107.91,121735.0,37589.0,185233.0,1641.55,12.63,68.0,M-SC,10.33,220.0,0.31,1.25,39.36,OX40N,ATH,CABLES
72,SIS,-3.11,-18.37,48.54,21.26,43997.0,-20392.0,90640.0,528.00,2146.11,70.0,H-SC,8.09,168.0,-0.46,0.61,34.77,OX40N,NTT,MISC
16,CERA,-1.21,-31.32,80.39,23.89,97119.0,-55093.0,120810.0,9475.00,-33.65,56.0,H-SC,12.33,153.0,-0.57,0.82,16.10,OX40N,NTT,CERAMICS
50,KANSAINER,-0.27,-34.19,72.42,13.47,128524.0,-92196.0,177471.0,340.00,-43.52,54.0,H-SC,16.50,162.0,-0.72,1.20,23.96,XY24,NTT,PAINTS
83,TTKPRESTIG,-2.22,-34.37,52.51,0.09,34731.0,-34635.0,66142.0,770.00,53.47,53.0,M-SC,18.66,250.0,-1.00,0.45,17.77,OX40N,NTT,DURABLES

In [14]:
# top 5 to book for rotation
df_tmp = df_portfolio_features[(df_portfolio_features['Current P/L%'] > 20) ].sort_values(by = 'CumlRnk', ascending=False)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
25,FINCABLES,-1.27,25.46,65.72,107.91,121735.0,37589.0,185233.0,1641.55,12.63,68.0,M-SC,10.33,220.0,0.31,1.25,39.36,OX40N,ATH,CABLES

In [15]:
# top 5 to monitor for exit
df_tmp = df_portfolio_features[~df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])]
df_tmp = df_tmp[(df_tmp['Current P/L%'] > 0) ].sort_values(by = 'Dev%_PE', ascending=False)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
74,STARHEALTH,-1.43,1.72,44.77,47.26,128022.0,4831.0,285954.0,761.00,60.64,70.0,H-SC,6.51,173.0,0.04,1.94,48.09,XY24,NTT,INSURANCE
25,FINCABLES,-1.27,25.46,65.72,107.91,121735.0,37589.0,185233.0,1641.55,12.63,68.0,M-SC,10.33,220.0,0.31,1.25,39.36,OX40N,ATH,CABLES
55,MASFIN,4.30,4.07,16.81,21.57,17141.0,3990.0,101970.0,397.04,-10.12,69.0,H-SC,0.59,167.0,0.23,0.69,31.77,XR,ATH,FINANCE
73,SONACOMS,1.26,5.05,32.40,39.09,34431.0,5110.0,106269.0,804.02,-16.82,67.0,M-MC,16.35,193.0,0.15,0.72,50.33,AR,ATH,AUTO

In [16]:
# top 5 to book for rotation from weak conviction
df_tmp = df_portfolio_features[~df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])]
df_tmp = df_tmp[~df_tmp['Criteria'].isin(['XY25','XY24','X40', 'X40N'])].sort_values(by = 'RRR Ind', ascending=False)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
25,FINCABLES,-1.27,25.46,65.72,107.91,121735.0,37589.0,185233.0,1641.55,12.63,68.0,M-SC,10.33,220.0,0.31,1.25,39.36,OX40N,ATH,CABLES
55,MASFIN,4.30,4.07,16.81,21.57,17141.0,3990.0,101970.0,397.04,-10.12,69.0,H-SC,0.59,167.0,0.23,0.69,31.77,XR,ATH,FINANCE
73,SONACOMS,1.26,5.05,32.40,39.09,34431.0,5110.0,106269.0,804.02,-16.82,67.0,M-MC,16.35,193.0,0.15,0.72,50.33,AR,ATH,AUTO
42,INDIAMART,-1.28,-9.60,128.69,106.72,143478.0,-11845.0,111491.0,4810.62,-59.18,48.0,H-SC,9.29,140.0,-0.08,0.75,7.11,AR,ATH,MISC
91,ZYDUSLIFE,-2.08,-5.95,44.21,35.63,87142.0,-12464.0,197110.0,1286.17,-18.02,43.0,H-MC,3.85,120.0,-0.14,1.33,3.64,AR,ATH,PHARMA

In [17]:
# top 5 to accumulate based on lowest RSI_14
df_tmp = df_portfolio_features[df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])].sort_values(by = 'RSI_14', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
33,HCLTECH,-0.09,-22.18,56.15,21.51,105707.0,-53665.0,188259.0,1872.35,-18.11,30.0,X-LC,8.92,8.0,-0.51,1.27,0.26,X40,ATH,IT
40,ICICIPRULI,-2.00,-14.97,53.74,30.73,90023.0,-29490.0,167515.0,790.00,-37.77,35.0,X-MC,13.02,78.0,-0.33,1.13,2.08,X40,ATH,INSURANCE
45,INFY,1.22,-19.55,66.86,34.24,168302.0,-61165.0,251723.0,1972.00,-36.87,36.0,X-LC,13.58,3.0,-0.36,1.70,2.58,X40,NTT,IT
27,GLAXO,-1.28,-6.21,48.36,39.15,90391.0,-12372.0,186912.0,3466.20,-28.31,40.0,X-MC,8.40,56.0,-0.14,1.27,3.40,X40,ATH,PHARMA
35,HDFCLIFE,-1.26,-4.01,38.75,33.18,55719.0,-6010.0,143790.0,814.30,-25.08,40.0,X-LC,17.68,31.0,-0.11,0.97,3.67,X40,ATH,INSURANCE

In [18]:
# top 5 to accumulate based on Spread and CumlRnk
df_tmp = df_portfolio_features[df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])]
df_tmp = df_tmp[(df_tmp['CumlRnk'] < 100)].sort_values(by = 'Spread%', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
88,VOLTAS,-3.01,11.90,29.75,45.20,63832.0,22818.0,214560.0,1856.00,28.05,52.0,X-MC,2.84,79.0,0.36,1.45,19.51,XY25,NTT,AC
84,UNITDSPR,-2.77,-2.62,24.02,20.77,54766.0,-6141.0,228003.0,1644.00,-13.56,50.0,X-MC,3.75,64.0,-0.11,1.54,8.76,X40N,NTT,BREWERIES
81,TMPV,-3.16,-22.25,75.67,36.58,209346.0,-79185.0,276656.0,600.00,-83.62,49.0,X-LC,5.17,4.0,-0.38,1.87,15.31,XY24,NTT,AUTO
87,VBL,-1.70,3.77,30.46,35.37,99830.0,11899.0,327741.0,670.16,-8.41,71.0,X-LC,5.43,13.0,0.12,2.22,34.70,X40N,ATH,FMCG
65,RELIANCE,0.38,-8.16,36.43,25.30,67240.0,-16390.0,184573.0,1952.00,-10.42,62.0,X-LC,5.56,21.0,-0.24,1.25,9.67,XY25,BTT,REFINERIES

In [19]:
# top 5 to accumulate based on lowest Gained%
df_tmp = df_portfolio_features[df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])].sort_values(by = 'Gained%', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
33,HCLTECH,-0.09,-22.18,56.15,21.51,105707.0,-53665.0,188259.0,1872.35,-18.11,30.0,X-LC,8.92,8.0,-0.51,1.27,0.26,X40,ATH,IT
1,ABBOTINDIA,-0.16,-14.67,38.37,18.07,58556.0,-26245.0,152610.0,35195.00,-27.31,42.0,X-MC,11.93,58.0,-0.45,1.03,1.01,X40,ATH,PHARMA
40,ICICIPRULI,-2.00,-14.97,53.74,30.73,90023.0,-29490.0,167515.0,790.00,-37.77,35.0,X-MC,13.02,78.0,-0.33,1.13,2.08,X40,ATH,INSURANCE
45,INFY,1.22,-19.55,66.86,34.24,168302.0,-61165.0,251723.0,1972.00,-36.87,36.0,X-LC,13.58,3.0,-0.36,1.70,2.58,X40,NTT,IT
27,GLAXO,-1.28,-6.21,48.36,39.15,90391.0,-12372.0,186912.0,3466.20,-28.31,40.0,X-MC,8.40,56.0,-0.14,1.27,3.40,X40,ATH,PHARMA

In [20]:
# top 5 to accumulate based on lowest CurrAlloc%
df_tmp = df_portfolio_features[df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])].sort_values(by = 'CurrAlloc%', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
64,RELAXO,-1.99,-61.39,294.51,52.31,165046.0,-89119.0,56041.0,1176.00,-58.86,49.0,X-SC,26.81,92.0,-0.54,0.38,25.30,X40N,NTT,FOOTWEAR
10,BATAINDIA,-0.84,-53.66,191.74,35.20,114336.0,-69039.0,59631.0,2096.00,-21.88,48.0,X-SC,26.87,91.0,-0.60,0.40,18.26,X40,NTT,FOOTWEAR
60,QUESS,-2.62,-18.92,114.49,73.90,99130.0,-20209.0,86584.0,424.00,-56.47,56.0,X-SC,15.40,80.0,-0.20,0.59,16.47,XY24,NTT,MISC
59,PIDILITIND,-0.96,-2.51,21.41,18.37,29454.0,-3540.0,137570.0,1670.26,-31.67,50.0,X-LC,7.25,5.0,-0.12,0.93,8.02,X40,ATH,CHEMICALS
53,M&M,-1.74,0.51,22.76,23.38,31725.0,707.0,139388.0,3802.40,-14.78,46.0,X-LC,8.68,25.0,0.02,0.94,7.03,X40N,ATH,AUTO

In [21]:
# top 5 to accumulate based on CumlRnk
df_tmp = df_portfolio_features.sort_values(by = 'CumlRnk', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
47,ITC,-0.43,-17.06,43.54,19.06,122848.0,-58016.0,282150.0,452.00,-54.31,61.0,X-LC,16.92,1.0,-0.47,1.91,9.45,X40,NTT,FMCG
79,TCS,-0.03,-27.38,74.28,26.57,249915.0,-126823.0,336450.0,4311.58,-38.38,46.0,X-LC,14.16,2.0,-0.51,2.28,5.00,X40,ATH,IT
45,INFY,1.22,-19.55,66.86,34.24,168302.0,-61165.0,251723.0,1972.00,-36.87,36.0,X-LC,13.58,3.0,-0.36,1.70,2.58,X40,NTT,IT
81,TMPV,-3.16,-22.25,75.67,36.58,209346.0,-79185.0,276656.0,600.00,-83.62,49.0,X-LC,5.17,4.0,-0.38,1.87,15.31,XY24,NTT,AUTO
59,PIDILITIND,-0.96,-2.51,21.41,18.37,29454.0,-3540.0,137570.0,1670.26,-31.67,50.0,X-LC,7.25,5.0,-0.12,0.93,8.02,X40,ATH,CHEMICALS

In [22]:
# top 5 for average up
df_tmp = df_portfolio_features[(df_portfolio_features['Dev%_200'] > 5)].sort_values(by = 'CurrAlloc%', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
44,INDUSINDBK,0.25,-32.37,96.50,32.89,50387.0,-24992.0,52215.0,1800.00,-345.80,63.0,L-MC,3.91,258.0,-0.50,0.35,28.52,XR,NTT,BANKS
72,SIS,-3.11,-18.37,48.54,21.26,43997.0,-20392.0,90640.0,528.00,2146.11,70.0,H-SC,8.09,168.0,-0.46,0.61,34.77,OX40N,NTT,MISC
55,MASFIN,4.30,4.07,16.81,21.57,17141.0,3990.0,101970.0,397.04,-10.12,69.0,H-SC,0.59,167.0,0.23,0.69,31.77,XR,ATH,FINANCE
73,SONACOMS,1.26,5.05,32.40,39.09,34431.0,5110.0,106269.0,804.02,-16.82,67.0,M-MC,16.35,193.0,0.15,0.72,50.33,AR,ATH,AUTO
75,SURYODAY,0.19,-12.91,41.28,23.03,64375.0,-23123.0,155948.0,216.00,68.86,69.0,H-SC,6.35,166.0,-0.36,1.06,32.99,XR,NTT,BANKS

In [23]:
# top 5 RSP
df_tmp = df_portfolio_features.sort_values(by = 'RSP', ascending=False)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
61,RAJESHEXPO,-4.56,-76.97,334.56,0.07,105681.0,-105589.0,31588.0,518.00,1057.83,51.0,L-SC,32.94,268.0,-1.00,0.21,48.30,OX40N,NTT,JEWELLERY
9,BANDHANBNK,0.72,-3.93,100.28,92.42,268374.0,-10934.0,267625.0,400.00,129.89,74.0,H-SC,5.52,174.0,-0.04,1.81,47.43,XY24,NTT,BANKS
87,VBL,-1.70,3.77,30.46,35.37,99830.0,11899.0,327741.0,670.16,-8.41,71.0,X-LC,5.43,13.0,0.12,2.22,34.70,X40N,ATH,FMCG
29,GREENPANEL,3.06,-38.98,134.59,43.14,150348.0,-71370.0,111708.0,537.00,150.00,68.0,M-SC,18.76,225.0,-0.47,0.76,34.19,XY24,NTT,MISC
71,SIEMENS,0.83,2.32,22.67,25.51,43166.0,4315.0,190410.0,4671.50,59.82,68.0,H-LC,10.64,51.0,0.10,1.29,34.16,AR,ATH,ELECTRICAL

In [24]:
# Top N allocation
df_tmp = df_portfolio_features.sort_values(by = 'CurrAlloc%', ascending=False)
top_n_values = [10, 25, 50]

sum_df = pd.DataFrame({
    'Top_N': top_n_values,
    'Sum_Alloc%': [df_tmp['CurrAlloc%'].head(n).sum() for n in top_n_values]
})

sum_df

   Top_N  Sum_Alloc%
0     10       19.22
1     25       42.69
2     50       72.61

In [25]:
# market-cap-wise allocation
df_tmp = df_portfolio_features[cols]
df_tmp.groupby(df_tmp['Conviction'].str[-2:])['CurrAlloc%'].sum().sort_values(ascending=False)

Conviction
SC    42.12
LC    31.96
MC    25.86
Name: CurrAlloc%, dtype: float64

In [26]:
# criteria-wise allocation
df_portfolio_features.groupby('Criteria')['CurrAlloc%'].sum().sort_values(ascending=False)

Criteria
XY24     26.87
X40      25.68
X40N     16.98
XR        9.11
XY25      6.96
OX40N     6.82
AR        6.72
SR        0.80
Name: CurrAlloc%, dtype: float64

In [27]:
# conviction-wise allocation
df_portfolio_features.groupby('Conviction')['CurrAlloc%'].sum().sort_values(ascending=False)

Conviction
X-LC    29.73
H-SC    21.91
X-MC    20.95
M-SC    10.04
X-SC     9.62
H-MC     2.52
M-MC     2.04
H-LC     1.29
M-LC     0.94
L-SC     0.55
L-MC     0.35
Name: CurrAlloc%, dtype: float64

In [28]:
# sector-wise stats
df_tmp = df_portfolio_features.groupby('Category')[['CurrAlloc%', 'Current', 'Current P/L', 'FTT Amt']].sum().sort_values(by=['Current', 'Current P/L'], ascending=False)
df_tmp['Current P/L%'] = round(df_tmp['Current P/L'] * 100 / df_tmp['Current'], 2)
df_tmp['FTT%'] = round(df_tmp['FTT Amt'] * 100 / df_tmp['Current'], 2)
cols = ['CurrAlloc%', 'Current P/L%', 'FTT%']
df_tmp[cols].sort_values(by=['CurrAlloc%'], ascending=False)

               CurrAlloc%  Current P/L%    FTT%
Category
FMCG                15.69        -14.18   54.47
FINANCE             10.76        -16.05   66.52
IT                  10.62        -43.46  115.69
MISC                 6.79        -33.63   91.68
AUTO                 6.65        -11.29   53.01
BANKS                5.65         -8.84   59.16
INSURANCE            5.31         -5.60   41.53
PAINTS               5.13        -29.97   52.54
PHARMA               4.73         -5.99   40.05
ELECTRICAL           4.10        -16.64   58.16
CHEMICALS            2.00        -37.31  119.14
AC                   1.98         -9.27   38.90
HEALTHCARE           1.89        -27.72   61.05
DURABLES             1.81        -44.43   79.57
APPARELS             1.74         -4.23   39.78
FOOTWEAR             1.74        -71.91  140.85
TRAVEL               1.71        -77.09  165.77
BREWERIES            1.54         -2.69   24.02
REALTY               1.39         -8.00   25.74
CERAMICS             1.30        -60.69  109.52
CABLES               1.25         20.29   65.72
REFINERIES           1.25         -8.88   36.43
ENGINEERING          1.19        -38.23  101.46
CEMENT               1.16        -57.12  174.66
JEWELLERY            1.04       -107.66  179.80
ENTERTAINMENT        0.75        -74.94  179.28
TEXTILES             0.43        -43.82   84.83
HOTELS               0.34       -124.02  203.03

In [29]:
# money to be made criteria-wise
df_portfolio_features.groupby('Criteria')['FTT Amt'].agg(['sum', 'count']).sort_values(by='sum', ascending=False)

                sum  count
Criteria
XY24      3629140.0     21
X40       1907861.0     19
XR        1334710.0     13
X40N      1216193.0     13
AR        1189926.0      9
OX40N      783981.0     10
XY25       411665.0      5
SR         300817.0      2

In [30]:
# money to be made conviction-wise
df_portfolio_features.groupby('Conviction')['FTT Amt'].agg(['sum', 'count']).sort_values(by='sum', ascending=False)

                  sum  count
Conviction
H-SC        3551346.0     24
X-LC        1903433.0     21
X-MC        1638260.0     15
M-SC        1433279.0     14
X-SC        1383569.0      9
H-MC         324949.0      2
L-SC         208593.0      2
M-LC         152449.0      1
M-MC          84862.0      2
L-MC          50387.0      1
H-LC          43166.0      1

In [31]:
# money to be made criteria and conviction-wise
df_portfolio_features.groupby(['Conviction', 'Criteria'])['FTT Amt'].agg(['sum', 'count']).sort_values(by='sum', ascending=False)

                           sum  count
Conviction Criteria
H-SC       XY24      1144522.0      6
X-LC       X40       1017226.0     10
H-SC       AR         949553.0      5
M-SC       XY24       850597.0      6
H-SC       XR         812619.0      7
X-SC       XY24       807023.0      4
X-MC       X40        685534.0      7
           X40N       485208.0      4
X-SC       X40N       371445.0      3
X-LC       X40N       359540.0      6
           XY24       348568.0      2
H-SC       OX40N      343835.0      4
M-SC       OX40N      334465.0      5
H-SC       SR         300817.0      2
X-MC       XY24       240623.0      2
H-MC       XY24       237807.0      1
X-MC       XY25       226895.0      2
X-SC       X40        205101.0      2
M-SC       XR         172583.0      2
M-LC       XR         152449.0      1
X-LC       XY25       134339.0      2
L-SC       OX40N      105681.0      1
           XR         102912.0      1
H-MC       AR          87142.0      1
M-SC       AR          75634.0      1
M-MC       XY25        50431.0      1
L-MC       XR          50387.0      1
X-LC       XR          43760.0      1
H-LC       AR          43166.0      1
M-MC       AR          34431.0      1

In [32]:
# notebook execution time

end_time = time.time()
execution_time = round(end_time - start_time, 0)
print(f"Notebook execution time: {execution_time} seconds")

Notebook execution time: 29.0 seconds