<a href="https://colab.research.google.com/github/ankit-rathi/Quantvesting_v2/blob/main/myStocks_Portfolio_Analysis.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
'''
!pip install pandas==2.2.2 -qq
!pip install pyxirr -qq
!pip install ta -qq
!pip install yfinance==0.2.59 -qq
'''

'\n!pip install pandas==2.2.2 -qq\n!pip install pyxirr -qq\n!pip install ta -qq\n!pip install yfinance==0.2.59 -qq\n'

In [2]:
# import libraries

import numpy as np
import pandas as pd
import datetime
import warnings
warnings.filterwarnings('ignore')
import yfinance as yfin
import ta
import matplotlib.pyplot as plt
import requests

In [3]:
# notebook start time
import time
import datetime
import pytz

start_time = time.time()

# function to print date timestamp
def print_date_time():
  tz_NY = pytz.timezone('Asia/Kolkata')
  datetime_NY = datetime.datetime.now(tz_NY)
  print("Run date time (IST):", datetime_NY.strftime("%Y-%m-%d %H:%M:%S"))

In [4]:
# function to get booked and reserved amount
def get_amt():
  # fetch the JSON data from the URL
  url = "https://raw.githubusercontent.com/ankit-rathi/Tradevesting_v1/main/data/myPortfolioAmts.json"
  response = requests.get(url)
  pf_amts = response.json()  # parse the JSON data

  # extract values from the JSON
  py_booked_amt_dm = pf_amts["py_booked_amt_dm"]
  py_booked_amt_sv = pf_amts["py_booked_amt_sv"]
  cy_booked_amt_dm = pf_amts["cy_booked_amt_dm"]
  cy_booked_amt_sv = pf_amts["cy_booked_amt_sv"]
  reserve_amt_dm = pf_amts["reserve_amt_dm"]
  reserve_amt_sv = pf_amts["reserve_amt_sv"]

  # perform calculations
  py_booked_amt = py_booked_amt_dm + py_booked_amt_sv
  cy_booked_amt = cy_booked_amt_dm + cy_booked_amt_sv
  reserve_amt = reserve_amt_dm + reserve_amt_sv
  total_booked_amt = py_booked_amt + cy_booked_amt

  return total_booked_amt, reserve_amt, cy_booked_amt, py_booked_amt

gen_output = 0

In [5]:
# function to format the amount
def format_amt(number):
    abs_number = abs(number)

    if abs_number >= 1_00_00_000:  # Crores
        formatted_amt = f"{number / 1_00_00_000:.2f} C"
    elif abs_number >= 1_00_000:  # Lakhs
        formatted_amt = f"{number / 1_00_000:.2f} L"
    elif abs_number >= 1_000:  # Thousands
        formatted_amt = f"{number / 1_000:.2f} K"
    else:
        formatted_amt = f"{number:.2f}"

    return formatted_amt

# function to set start and end date
def get_start_end_date():
  start_date = (datetime.date.today() + datetime.timedelta(days=-365)).strftime('%Y-%m-%d')
  end_date = (datetime.date.today() + datetime.timedelta(days=1)).strftime('%Y-%m-%d')
  return start_date, end_date

# function to fetch my portfolio csv
def get_mypfs_df():
  mypfs_df = pd.read_csv('https://raw.githubusercontent.com/ankit-rathi/Tradevesting_v1/main/data/myPortfolioStocks.csv')
  return mypfs_df

# function to fetch my prospects csv
def get_mypps_df():
  mypps_df = pd.read_csv('https://raw.githubusercontent.com/ankit-rathi/Tradevesting_v1/main/data/myProspectsScrips.csv')
  return mypps_df

# function to fetch screener data
def get_myscreen_df():
  myscreen_df = pd.read_csv('https://raw.githubusercontent.com/ankit-rathi/Tradevesting_v1/main/data/myScreenerDB.csv')
  return myscreen_df

# function to fetch momentum data
def get_myinvmt_df():
  myinvmt_df = pd.read_csv('https://raw.githubusercontent.com/ankit-rathi/Tradevesting_v1/main/data/myInvestments.csv')
  return myinvmt_df

# function to get the stock ids
def get_stock_ids(df_pf):
  stock_n100 = df_pf['Symbol'].unique()

  exclude = ['CADILAHC','MMTC', 'MASFIN']

  stock_ids = df_pf[~df_pf['Symbol'].isin(exclude) ]['Symbol'].unique()

  #mypf = mypf[mypf.Forecast.notnull()]
  #stock_ids = mypf['Symbol'].unique()

  #stock_ids.sort()
  return stock_ids

# get features from screener data
def get_screener_features():
  myscreen_df = get_myscreen_df()
  cols = ['Symbol', 'EPS', 'MedPE', 'ROCE%', 'ROE%', 'CapType']
  return myscreen_df[cols]

# get relative strength
def get_relative_strength(stock_list):

    # Dictionary to store stock tickers and their corresponding percentage price change
    stock_changes = {}

    # Loop through each stock and fetch its price data
    for stock in stock_list:
        try:
            # Download the stock data for the given date range
            stock_data = yfin.Ticker(stock + '.NS').history(period='1mo', interval='1d')[map(str.title, ['open', 'close', 'low', 'high', 'volume'])]

            # Calculate the percentage change for the stock
            if len(stock_data) > 0:
                start_price = stock_data['Close'].iloc[0]
                end_price = stock_data['Close'].iloc[-1]
                percent_change = round(((end_price - start_price) / start_price) * 100, 2)
                stock_changes[stock] = percent_change
            else:
                stock_changes[stock] = np.nan  # If no data is available, set to NaN

        except Exception as e:
            print(f"Error fetching data for {stock}: {e}")
            stock_changes[stock] = np.nan

    # Create a DataFrame with stock tickers and their percentage changes
    df = pd.DataFrame(list(stock_changes.items()), columns=['Symbol', 'Percent_Change'])

    # Drop any stocks with missing data (NaN values)
    df = df.dropna()

    # Calculate the percentile rank based on percentage change
    df['RSP'] = round(df['Percent_Change'].rank(pct=True) * 100, 2)
    cols = ['Symbol', 'RSP']
    df = df[cols]
    # Sort by percentile rank (optional)
    df = df.sort_values(by='RSP', ascending=False).reset_index(drop=True)

    return df

In [6]:
# function to get stock technicals
def stock_prec_dev(stock_symbol):
    #stock_symbol = 'ULTRACEMCO.NS'
    short_window = 20
    mid_window = 50
    long_window = 200
    moving_avg = 'SMA'

    start = datetime.datetime(*map(int, start_date.split('-')))
    end = datetime.datetime(*map(int, end_date.split('-')))

    stock_df = yfin.Ticker(stock_symbol + '.NS').history(period='max', interval='1d')[map(str.title, ['open', 'close', 'low', 'high', 'volume'])]

    stock_df['Max'] = round(max(stock_df['Close']),2)
    stock_df = stock_df[(stock_df.index <= end_date) & (stock_df.index >= start_date)]
    stock_df['200_SMA'] = round(stock_df['Close'].rolling(window = 200, min_periods = 1).mean(),0)
    stock_df['Dev%_200'] = round((stock_df['Close'] - stock_df['200_SMA'])*100/stock_df['200_SMA'],2)
    stock_df.dropna(axis = 0, inplace = True) # remove any null rows

    stock_df['20_SMA'] = stock_df['Close'].rolling(window=20).mean()
    stock_df['50_SMA'] = stock_df['Close'].rolling(window=50).mean()
    stock_df['Symbol'] = stock_symbol

    stock_df['Close'] = round(stock_df['Close'],2)
    stock_df['Min'] = round(min(stock_df['Close']),2)
    stock_df['RSI_14'] = ta.momentum.RSIIndicator(close=stock_df['Close'], window=14).rsi()
    stock_df['RSI_14'] = round(stock_df['RSI_14'],0)
    stock_df['Prev_Close'] = stock_df['Close'].shift(1)
    stock_df.drop(['Open', 'Low', 'High', 'Volume'], axis=1, inplace=True)
    stock_df = stock_df.tail(1)

    max_SMA = max(stock_df['20_SMA'].item(), stock_df['50_SMA'].item(), stock_df['200_SMA'].item())
    min_SMA = min(stock_df['20_SMA'].item(), stock_df['50_SMA'].item(), stock_df['200_SMA'].item())
    ABS_Spread = max_SMA - min_SMA
    stock_df['Spread%'] = round((ABS_Spread / stock_df['200_SMA'].item()) * 100,2)

    return stock_df

# function to compute stock attributes
def get_common_features(stock_ids, df_mypf):

  df_prec_dev = pd.DataFrame()
  df_tmp = get_screener_features()
  df_rs = get_relative_strength(stock_ids)

  for stock_id in stock_ids:
      tmp = stock_prec_dev(stock_id)
      tmp = tmp.reset_index()
      df_prec_dev = pd.concat([df_prec_dev, tmp], ignore_index = True)
  df_prec_dev = pd.merge(df_prec_dev, df_mypf, on= 'Symbol')
  df_prec_dev = pd.merge(df_prec_dev, df_tmp, on= 'Symbol', how='left')
  df_prec_dev = pd.merge(df_prec_dev, df_rs, on= 'Symbol', how='left')
  #print(df_prec_dev.columns)
  df_prec_dev['Curr_PE'] = round(df_prec_dev['Close']/df_prec_dev['EPS'],1)
  df_prec_dev['Dev%_PE'] = round((df_prec_dev['Curr_PE'] - df_prec_dev['MedPE'])*100/df_prec_dev['MedPE'],2)
  df_prec_dev['Conviction'] = df_prec_dev['Conviction'] + '-' + df_prec_dev['CapType']
  return df_prec_dev

# function to arrange stock features
def arrange_features(df_stocks, common_cols, diff_cols):
  df_stocks_common = df_stocks[common_cols].drop_duplicates()
  df_stocks_diff = df_stocks[diff_cols]
  df_stocks_diff['Investment'] = df_stocks_diff['AvgCost'] * df_stocks_diff['Shares']
  df_stocks_diff = df_stocks_diff.groupby(['Symbol'])[['Shares', 'Investment']].aggregate(['sum']).reset_index()
  df_stocks_diff.columns = ['Symbol', 'Shares', 'Investment']
  df_stocks_diff['AvgCost'] = round(df_stocks_diff['Investment']/df_stocks_diff['Shares'],2)
  df_stocks = pd.merge(df_stocks_diff, df_stocks_common, on='Symbol')
  return df_stocks

# plot fact distribution across dimension
def plot_pie_chart(df, dimension, fact):
  # grouping the data by category and calculating the sum of fact for each type
  grouped_data = df.groupby(dimension)[fact].sum()

  # sorting the grouped data in descending order
  grouped_data = grouped_data.sort_values(ascending=False)

  # creating a pie chart
  grouped_data.plot.pie(autopct='%1.1f%%', startangle=90, figsize=(6, 6))

  # adding a title and displaying the plot
  plt.title(f'{dimension} {fact} Distribution')
  plt.ylabel('')  # To hide the y-label
  plt.show()

In [7]:
# function to get portfolio features

def get_portfolio_features(df_common_features):

  print_date_time()
  print('-------------------')

  #df_common_features["Target"] = df_common_features["Target"].fillna(df_common_features["Max"])
  df_common_features['NTT'] = np.where(df_common_features['Strategy']== 'NTT', df_common_features["Target"], df_common_features['Max'])
  df_common_features['LTT'] = np.where(df_common_features['Strategy']== 'BTT', df_common_features["Target"], df_common_features['Max'])
  df_common_features['BOL'] = df_common_features['Min']

  tmp_df = df_common_features[df_common_features['Symbol'].isin(mypf_df[mypf_df['InPortfolio'] != 'NA'].Symbol.values)]
  print('qualified stocks: '+str(len(tmp_df['Symbol'].unique())))
  tmp_df1 = tmp_df[tmp_df['LatestQtr'] == 1]
  print('with latest results: '+str(len(tmp_df1['Symbol'].unique())))
  tmp_df1 = tmp_df1[tmp_df1['StarStock'] == 1]
  print('still star stocks: '+str(len(tmp_df1['Symbol'].unique())))
  tmp_df['Investment'] = tmp_df['AvgCost'] * tmp_df['Shares']
  tmp_df['Current'] = round(tmp_df['Close'] * tmp_df['Shares'],0)
  tmp_df['Previous'] = tmp_df['Prev_Close'] * tmp_df['Shares']
  tmp_df['EstimatedST'] = tmp_df['NTT'] * tmp_df['Shares']
  tmp_df['EstimatedLT'] = tmp_df['LTT'] * tmp_df['Shares']
  tmp_df['Current P/L'] = round((tmp_df['Current'] - tmp_df['Investment']),0)
  tmp_df['Today P/L%'] = round((tmp_df['Current'] - tmp_df['Previous'])*100/tmp_df['Previous'],2)
  tmp_df['Current P/L%'] = round((tmp_df['Current'] - tmp_df['Investment'])*100/tmp_df['Investment'],2)
  tmp_df['EstimatedST P/L%'] = round((tmp_df['EstimatedST'] - tmp_df['Investment'])*100/tmp_df['Investment'],2)
  tmp_df['EstimatedLT P/L%'] = round((tmp_df['EstimatedLT'] - tmp_df['Investment'])*100/tmp_df['Investment'],2)
  tmp_df['NTT%'] = round((tmp_df['NTT'] - tmp_df['Close'])*100/tmp_df['Close'],2)
  tmp_df['LTT%'] = round((tmp_df['LTT'] - tmp_df['Close'])*100/tmp_df['Close'],2)
  tmp_df['Gained%'] = round((tmp_df['Close'] - tmp_df['BOL'])*100/tmp_df['BOL'],2)
  investment = round(sum(tmp_df['AvgCost']*tmp_df['Shares']),0)
  current = round(sum(tmp_df['Close']*tmp_df['Shares']),0)
  tmp_df['InitAlloc%'] = round(tmp_df['Investment']*100/investment,2)
  tmp_df['CurrAlloc%'] = round(tmp_df['Current']*100/current,2)
  tmp_df['FTT'] = tmp_df['LTT']
  tmp_df.loc[tmp_df['Strategy'] == 'NTT', 'FTT'] = tmp_df['NTT']
  tmp_df['FTT%'] = tmp_df['LTT%']
  tmp_df.loc[tmp_df['Strategy'] == 'NTT', 'FTT%'] = tmp_df['NTT%']
  tmp_df['FTT Amt'] = round(tmp_df['FTT%'] * tmp_df['Current']/100,0)
  tmp_df['OTT%'] = round((tmp_df['FTT'] - tmp_df['AvgCost'])*100/tmp_df['AvgCost'],2)
  tmp_df['RRR Ind'] = round(tmp_df['Current P/L']/tmp_df['FTT Amt'],2)
  tmp_df['Risk Ind'] = round(tmp_df['Current P/L%']*tmp_df['CurrAlloc%'],0)

  return tmp_df

# function to print portfolio features
def print_portfolio_stats(df_portfolio_features, myinvmt_df):
  from pyxirr import xirr

  total_booked_amt, reserve_amt, cy_booked_amt, py_booked_amt = get_amt()

  dates = myinvmt_df['Date'].values
  dates = np.append(dates, datetime.date.today().strftime('%d-%b-%y'))
  investment = myinvmt_df['Investment'].values
  dates= pd.to_datetime(dates)

  current = round(sum(df_portfolio_features['Close']*df_portfolio_features['Shares']),0) + reserve_amt
  investment_xirr = np.append(investment, current)
  cagr = round(xirr(pd.DataFrame({"dates": dates, "amounts": investment_xirr}))*100,2)

  investment = -sum(investment)
  invested = round(sum(df_portfolio_features['AvgCost']*df_portfolio_features['Shares']),0) + reserve_amt
  previous = round(sum(df_portfolio_features['Prev_Close']*df_portfolio_features['Shares']),0) + reserve_amt
  cy_invested = investment + py_booked_amt

  today_pnl_amount = current-previous
  today_pnl_percentage = round((current-previous)*100/previous,2)

  curr_pnl_amount = current-invested
  curr_pnl_percentage = round((curr_pnl_amount)*100/(cy_invested),2)

  cy_pnl_amount = cy_booked_amt + curr_pnl_amount
  cy_pnl_percentage = round((cy_pnl_amount)*100/cy_invested,2)

  overall_pnl_amount = total_booked_amt + curr_pnl_amount
  overall_pnl_percentage = round((overall_pnl_amount)*100/investment,2)

  estimate_st = round(sum(df_portfolio_features['FTT']*df_portfolio_features['Shares']),0)  + reserve_amt
  est_st_pnl_amount = estimate_st-current
  est_st_pnl_percentage = round((est_st_pnl_amount)*100/current,2)

  estimate_lt = round(sum(df_portfolio_features['LTT']*df_portfolio_features['Shares']),0)  + reserve_amt
  est_lt_pnl_amount = estimate_lt-current
  est_lt_pnl_percentage = round((est_lt_pnl_amount)*100/current,2)

  total_profit = round(sum(df_portfolio_features[df_portfolio_features['Current P/L%'] > 0]['Current']) - sum(df_portfolio_features[df_portfolio_features['Current P/L%'] > 0]['Investment']),0)
  total_loss = round(sum(df_portfolio_features[df_portfolio_features['Current P/L%'] < 0]['Current']) - sum(df_portfolio_features[df_portfolio_features['Current P/L%'] < 0]['Investment']),0)

  cy_booked_percentage = round((cy_booked_amt)*100/current,2)
  py_booked_percentage = round((py_booked_amt)*100/investment,2)
  total_booked_percentage = round((total_booked_amt)*100/investment,2)

  print('-------------------')
  print('Initial Investment: ', format_amt(investment))
  print('CY Investment: ', format_amt(cy_invested))
  print('Reserve: ', format_amt(reserve_amt))
  print('Current: ',  format_amt(current))
  print('-------------------')
  print('Today PnL: '+ '{} ({}%)'.format(format_amt(today_pnl_amount), today_pnl_percentage))
  print('Current PnL: '+ '{} ({}%)'.format(format_amt(curr_pnl_amount), curr_pnl_percentage))
  print('CY Booked + Current PnL: '+ '{} ({}%)'.format(format_amt(cy_pnl_amount), cy_pnl_percentage))
  print('-------------------')
  print('Total profit: ', format_amt(total_profit))
  print('Total loss: ', format_amt(total_loss))
  print('-------------------')
  print('Total Booked + Current PnL: '+ '{} ({}%)'.format(format_amt(overall_pnl_amount), overall_pnl_percentage))
  print('Total Booked PnL: '+ '{} ({}%)'.format(format_amt(total_booked_amt), total_booked_percentage))
  print('Curr Year Booked PnL: '+ '{} ({}%)'.format(format_amt(cy_booked_amt), cy_booked_percentage))
  print('Prev Year Booked PnL: '+ '{} ({}%)'.format(format_amt(py_booked_amt), py_booked_percentage))
  print('===================')
  print('Est FTT: ',  format_amt(estimate_st))
  print('Est FTT PnL: '+ '{} ({}%)'.format(format_amt(est_st_pnl_amount), est_st_pnl_percentage))

  print('===================')
  print('Deployed: ', format_amt(investment))

  print('Current: ', format_amt(current))

  print('CAGR/XIRR %: '+'{}%'.format(cagr))

In [8]:
# get start and end date
start_date, end_date = get_start_end_date()

# get portfolio and prospects data
mypfs_df = get_mypfs_df()
mypps_df = get_mypps_df()
myinvmt_df = get_myinvmt_df()

# merge above datasets
mypf_df = pd.merge(mypfs_df, mypps_df, on="Symbol")

# seggregate dm and sv portfolio
dm_pf = mypf_df[mypf_df['InPortfolio'] == 'DM']
sv_pf = mypf_df[mypf_df['InPortfolio'] == 'SV']

# build portfolio stock dataframe
dm_stocks = get_stock_ids(dm_pf)
sv_stocks = get_stock_ids(sv_pf)
df_stocks = pd.concat([dm_pf,sv_pf], ignore_index = True)

# arrange common and diff stock features
common_cols = ['Symbol', 'Target', 'Criteria', 'Strategy', 'CumlRnk', 'LatestQtr', 'StarStock', 'Conviction', 'Category', 'InFolio', 'XIRR', 'MBQ']
diff_cols = ['Symbol', 'AvgCost', 'Shares']
df_stocks = arrange_features(df_stocks, common_cols, diff_cols)

# get common features
stock_ids = df_stocks['Symbol'].values
df_common_features = get_common_features(stock_ids, df_stocks)

df_common_features.reset_index(drop=True, inplace=True)
df_common_features.drop(['Date'], axis=1, inplace=True)
# get and print portfolio features
df_portfolio_features = get_portfolio_features(df_common_features)

print_portfolio_stats(df_portfolio_features, myinvmt_df)

df = df_portfolio_features
#plot_pie_chart(df, 'CapType', 'Current')
list_ox40n = list(df[df['MBQ'].str.contains('OX40N', na=False)]['Symbol'].values)

Run date time (IST): 2026-05-11 11:28:24
-------------------
qualified stocks: 92
with latest results: 31
still star stocks: 20
-------------------
Initial Investment:  1.40 C
CY Investment:  1.82 C
Reserve:  1.49 K
Current:  1.51 C
-------------------
Today PnL: -1.46 L (-0.96%)
Current PnL: -31.97 L (-17.53%)
CY Booked + Current PnL: -29.89 L (-16.39%)
-------------------
Total profit:  2.09 L
Total loss:  -34.06 L
-------------------
Total Booked + Current PnL: 12.98 L (9.3%)
Total Booked PnL: 44.95 L (32.22%)
Curr Year Booked PnL: 2.08 L (1.38%)
Prev Year Booked PnL: 42.87 L (30.73%)
===================
Est FTT:  2.55 C
Est FTT PnL: 1.04 C (68.94%)
===================
Deployed:  1.40 C
Current:  1.51 C
CAGR/XIRR %: 3.96%

In [9]:
# top 5 near their targets
cols = ['Symbol', 'Today P/L%', 'Current P/L%', 'FTT%', 'OTT%', 'FTT Amt', 'Current P/L', 'Current', 'FTT', 'Dev%_PE', 'RSI_14','Conviction', 'Spread%',  'CumlRnk', 'RRR Ind', 'CurrAlloc%', 'Gained%', 'Criteria', 'Strategy', 'Category']
df_tmp = df_portfolio_features[~df_portfolio_features['Symbol'].isin(['ENRIN','BLUSPRING','DIGITIDE'])]
df_tmp = df_tmp.sort_values(by = 'FTT Amt', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
55,MASFIN,-0.55,5.59,15.13,21.57,15653.0,5475.0,103455.0,397.04,-8.76,67.0,H-SC,4.95,167.0,0.35,0.68,30.13,XR,ATH,FINANCE
59,PIDILITIND,-1.95,2.56,15.41,18.37,22301.0,3610.0,144720.0,1670.26,-28.20,61.0,X-LC,5.41,5.0,0.16,0.96,13.63,X40,ATH,CHEMICALS
53,M&M,-2.36,5.51,16.94,23.38,24788.0,7645.0,146326.0,3802.40,-10.61,54.0,X-LC,7.72,25.0,0.31,0.97,10.94,X40N,ATH,AUTO
51,KOTAKBANK,0.03,1.78,18.99,21.11,26763.0,2460.0,140933.0,453.24,-12.87,53.0,X-LC,7.35,12.0,0.09,0.93,7.78,X40,ATH,BANKS
83,TTKPRESTIG,0.52,-32.20,47.64,0.09,32549.0,-32454.0,68323.0,770.00,58.59,56.0,M-SC,17.17,250.0,-1.00,0.45,21.66,OX40N,NTT,DURABLES

In [10]:
# top 5 today
df_tmp = df_portfolio_features.sort_values(by = 'Today P/L%', ascending=False)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
86,VALIANTORG,5.95,-34.46,165.74,74.15,177705.0,-56386.0,107219.0,838.0,-292.76,69.0,H-SC,14.39,145.0,-0.32,0.71,59.56,XR,NTT,CHEMICALS
1,ABBOTINDIA,3.56,-7.24,27.29,18.07,45274.0,-12955.0,165900.0,35195.0,-21.17,73.0,X-MC,10.81,58.0,-0.29,1.10,9.81,X40,ATH,PHARMA
38,HYUNDAI,2.11,0.57,48.50,49.35,75237.0,887.0,155128.0,2809.3,-19.06,56.0,X-LC,17.75,29.0,0.01,1.03,11.85,X40N,ATH,AUTO
16,CERA,1.44,-23.31,61.55,23.89,83028.0,-41008.0,134895.0,9475.0,-26.01,76.0,H-SC,10.73,153.0,-0.49,0.89,29.63,OX40N,NTT,CERAMICS
56,MEDANTA,1.38,4.12,22.08,27.12,40582.0,7280.0,183797.0,1486.0,0.98,69.0,X-SC,10.41,87.0,0.18,1.22,26.65,XY24,NTT,HEALTHCARE

In [11]:
# bottom 5 today
df_tmp = df_portfolio_features.sort_values(by = 'Today P/L%', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
71,SIEMENS,-6.62,-4.09,30.87,25.51,55095.0,-7620.0,178475.0,4671.5,49.82,46.0,H-LC,17.04,51.0,-0.14,1.18,25.31,AR,ATH,ELECTRICAL
89,WHIRLPOOL,-4.28,-26.68,148.11,81.92,124666.0,-30627.0,84171.0,2270.0,-57.12,47.0,M-SC,17.11,210.0,-0.25,0.56,18.23,XR,NTT,DURABLES
11,BERGEPAINT,-3.57,-8.34,36.72,25.32,86748.0,-21508.0,236241.0,680.0,-13.36,64.0,X-MC,12.55,68.0,-0.25,1.56,22.95,XY24,NTT,PAINTS
61,RAJESHEXPO,-3.56,-77.27,340.33,0.07,106098.0,-106002.0,31175.0,518.0,1042.68,48.0,L-SC,31.36,268.0,-1.00,0.21,46.35,OX40N,NTT,JEWELLERY
62,RAJOOENG,-3.49,-42.05,140.91,39.61,83701.0,-43100.0,59400.0,143.1,-60.83,46.0,H-SC,22.98,136.0,-0.51,0.39,27.25,AR,ATH,MISC

In [12]:
# top 5 to exit based on CumlRnk
df_tmp = df_portfolio_features[~df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])]
df_tmp = df_tmp[(df_tmp['Current P/L%'] > -1) & (df_tmp['Current P/L%'] < 1)].sort_values(by = 'CumlRnk', ascending=False)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
73,SONACOMS,-0.74,-0.53,39.83,39.09,40079.0,-534.0,100625.0,804.02,-21.15,53.0,M-MC,19.98,193.0,-0.01,0.67,42.35,AR,ATH,AUTO
74,STARHEALTH,0.16,0.82,46.07,47.26,130573.0,2301.0,283424.0,761.00,59.02,64.0,H-SC,9.90,173.0,0.02,1.87,39.53,XY24,NTT,INSURANCE
91,ZYDUSLIFE,0.35,-0.52,36.34,35.63,75762.0,-1094.0,208480.0,1286.17,-13.51,60.0,H-MC,3.48,120.0,-0.01,1.38,9.62,AR,ATH,PHARMA

In [13]:
# OX40N stocks to exit
df_tmp = df_portfolio_features[(df_portfolio_features['Symbol'].isin(list_ox40n))].sort_values(by = 'Current P/L%', ascending=False)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
25,FINCABLES,-2.30,41.22,47.22,107.91,98456.0,60861.0,208505.0,1641.55,26.84,75.0,M-SC,20.05,220.0,0.62,1.38,56.87,OX40N,ATH,CABLES
72,SIS,-1.02,-11.29,36.70,21.26,36147.0,-12538.0,98494.0,528.00,2340.41,68.0,H-SC,11.39,168.0,-0.35,0.65,46.45,OX40N,NTT,MISC
16,CERA,1.44,-23.31,61.55,23.89,83028.0,-41008.0,134895.0,9475.00,-26.01,76.0,H-SC,10.73,153.0,-0.49,0.89,29.63,OX40N,NTT,CERAMICS
50,KANSAINER,-2.00,-27.93,57.44,13.47,111638.0,-75312.0,194355.0,340.00,-38.12,66.0,H-SC,15.46,162.0,-0.67,1.29,35.76,XY24,NTT,PAINTS
43,INDIGOPNTS,-0.22,-30.95,44.86,0.02,54069.0,-54031.0,120528.0,1408.00,83.59,73.0,M-SC,20.89,222.0,-1.00,0.80,36.75,OX40N,NTT,PAINTS

In [14]:
# top 5 to book for rotation
df_tmp = df_portfolio_features[(df_portfolio_features['Current P/L%'] > 20) ].sort_values(by = 'CumlRnk', ascending=False)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
25,FINCABLES,-2.3,41.22,47.22,107.91,98456.0,60861.0,208505.0,1641.55,26.84,75.0,M-SC,20.05,220.0,0.62,1.38,56.87,OX40N,ATH,CABLES

In [15]:
# top 5 to monitor for exit
df_tmp = df_portfolio_features[~df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])]
df_tmp = df_tmp[(df_tmp['Current P/L%'] > 0) ].sort_values(by = 'Dev%_PE', ascending=False)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
75,SURYODAY,-0.79,1.67,21.01,23.03,38253.0,2999.0,182070.0,216.00,97.37,82.0,H-SC,10.43,166.0,0.08,1.20,53.30,XR,NTT,BANKS
74,STARHEALTH,0.16,0.82,46.07,47.26,130573.0,2301.0,283424.0,761.00,59.02,64.0,H-SC,9.90,173.0,0.02,1.87,39.53,XY24,NTT,INSURANCE
25,FINCABLES,-2.30,41.22,47.22,107.91,98456.0,60861.0,208505.0,1641.55,26.84,75.0,M-SC,20.05,220.0,0.62,1.38,56.87,OX40N,ATH,CABLES
68,SATIN,1.35,19.47,27.09,51.83,89415.0,53784.0,330068.0,274.00,6.44,82.0,H-SC,18.78,159.0,0.60,2.18,60.79,XY24,NTT,FINANCE
55,MASFIN,-0.55,5.59,15.13,21.57,15653.0,5475.0,103455.0,397.04,-8.76,67.0,H-SC,4.95,167.0,0.35,0.68,30.13,XR,ATH,FINANCE

In [16]:
# top 5 to book for rotation from weak conviction
df_tmp = df_portfolio_features[~df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])]
df_tmp = df_tmp[~df_tmp['Criteria'].isin(['XY25','XY24','X40', 'X40N'])].sort_values(by = 'RRR Ind', ascending=False)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
25,FINCABLES,-2.30,41.22,47.22,107.91,98456.0,60861.0,208505.0,1641.55,26.84,75.0,M-SC,20.05,220.0,0.62,1.38,56.87,OX40N,ATH,CABLES
55,MASFIN,-0.55,5.59,15.13,21.57,15653.0,5475.0,103455.0,397.04,-8.76,67.0,H-SC,4.95,167.0,0.35,0.68,30.13,XR,ATH,FINANCE
75,SURYODAY,-0.79,1.67,21.01,23.03,38253.0,2999.0,182070.0,216.00,97.37,82.0,H-SC,10.43,166.0,0.08,1.20,53.30,XR,NTT,BANKS
73,SONACOMS,-0.74,-0.53,39.83,39.09,40079.0,-534.0,100625.0,804.02,-21.15,53.0,M-MC,19.98,193.0,-0.01,0.67,42.35,AR,ATH,AUTO
91,ZYDUSLIFE,0.35,-0.52,36.34,35.63,75762.0,-1094.0,208480.0,1286.17,-13.51,60.0,H-MC,3.48,120.0,-0.01,1.38,9.62,AR,ATH,PHARMA

In [17]:
# top 5 to accumulate based on lowest RSI_14
df_tmp = df_portfolio_features[df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])].sort_values(by = 'RSI_14', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
33,HCLTECH,0.03,-22.21,56.20,21.51,105766.0,-53728.0,188196.0,1872.35,-18.11,33.0,X-LC,13.04,8.0,-0.51,1.24,1.29,X40,ATH,IT
2,ACC,-2.77,-39.43,188.61,74.81,306318.0,-105720.0,162408.0,3906.00,-57.01,37.0,X-SC,16.74,85.0,-0.35,1.07,7.88,XY24,BTT,CEMENT
28,GODREJCP,-2.43,-8.98,45.15,32.12,61076.0,-13340.0,135274.0,1476.34,-4.32,38.0,X-LC,6.62,32.0,-0.22,0.89,3.28,X40N,ATH,FMCG
88,VOLTAS,-0.44,3.19,40.71,45.20,80545.0,6108.0,197850.0,1856.00,18.16,39.0,X-MC,2.44,79.0,0.08,1.31,8.10,XY25,NTT,AC
79,TCS,0.45,-29.39,79.26,26.57,259265.0,-136166.0,327107.0,4311.59,-40.35,40.0,X-LC,14.32,2.0,-0.53,2.16,2.09,X40,ATH,IT

In [18]:
# top 5 to accumulate based on Spread and CumlRnk
df_tmp = df_portfolio_features[df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])]
df_tmp = df_tmp[(df_tmp['CumlRnk'] < 100)].sort_values(by = 'Spread%', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
84,UNITDSPR,-0.74,-6.61,29.32,20.77,64112.0,-15480.0,218664.0,1644.00,-17.10,41.0,X-MC,2.44,64.0,-0.24,1.45,4.31,X40N,NTT,BREWERIES
88,VOLTAS,-0.44,3.19,40.71,45.20,80545.0,6108.0,197850.0,1856.00,18.16,39.0,X-MC,2.44,79.0,0.08,1.31,8.10,XY25,NTT,AC
65,RELIANCE,-1.22,-9.00,37.69,25.30,68929.0,-18080.0,182883.0,1952.00,-11.19,54.0,X-LC,3.40,21.0,-0.26,1.21,8.67,XY25,BTT,REFINERIES
39,ICICIGI,0.33,-2.85,22.84,19.34,44402.0,-5705.0,194404.0,2252.93,-18.36,56.0,X-MC,4.43,66.0,-0.13,1.29,8.58,X40,ATH,INSURANCE
19,COLPAL,-0.93,-17.34,71.19,41.51,154981.0,-45665.0,217700.0,3726.84,-0.02,62.0,X-MC,5.08,62.0,-0.29,1.44,21.71,XY25,ATH,FMCG

In [19]:
# top 5 to accumulate based on lowest Gained%
df_tmp = df_portfolio_features[df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])].sort_values(by = 'Gained%', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
33,HCLTECH,0.03,-22.21,56.20,21.51,105766.0,-53728.0,188196.0,1872.35,-18.11,33.0,X-LC,13.04,8.0,-0.51,1.24,1.29,X40,ATH,IT
79,TCS,0.45,-29.39,79.26,26.57,259265.0,-136166.0,327107.0,4311.59,-40.35,40.0,X-LC,14.32,2.0,-0.53,2.16,2.09,X40,ATH,IT
45,INFY,0.35,-19.45,66.65,34.24,167987.0,-60845.0,252043.0,1972.00,-36.50,40.0,X-LC,16.09,3.0,-0.36,1.67,2.71,X40,NTT,IT
28,GODREJCP,-2.43,-8.98,45.15,32.12,61076.0,-13340.0,135274.0,1476.34,-4.32,38.0,X-LC,6.62,32.0,-0.22,0.89,3.28,X40N,ATH,FMCG
84,UNITDSPR,-0.74,-6.61,29.32,20.77,64112.0,-15480.0,218664.0,1644.00,-17.10,41.0,X-MC,2.44,64.0,-0.24,1.45,4.31,X40N,NTT,BREWERIES

In [20]:
# top 5 to accumulate based on lowest CurrAlloc%
df_tmp = df_portfolio_features[df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])].sort_values(by = 'CurrAlloc%', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
64,RELAXO,-0.55,-60.22,282.87,52.31,163340.0,-87416.0,57744.0,1176.00,-57.60,55.0,X-SC,24.46,92.0,-0.54,0.38,29.11,X40N,NTT,FOOTWEAR
10,BATAINDIA,-1.00,-53.91,193.35,35.20,114664.0,-69366.0,59304.0,2096.00,-22.31,46.0,X-SC,26.19,91.0,-0.60,0.39,17.61,X40,NTT,FOOTWEAR
60,QUESS,-0.04,-8.33,89.71,73.90,87820.0,-8900.0,97893.0,424.00,-50.96,73.0,X-SC,13.36,80.0,-0.10,0.65,33.45,XY24,NTT,MISC
28,GODREJCP,-2.43,-8.98,45.15,32.12,61076.0,-13340.0,135274.0,1476.34,-4.32,38.0,X-LC,6.62,32.0,-0.22,0.89,3.28,X40N,ATH,FMCG
51,KOTAKBANK,0.03,1.78,18.99,21.11,26763.0,2460.0,140933.0,453.24,-12.87,53.0,X-LC,7.35,12.0,0.09,0.93,7.78,X40,ATH,BANKS

In [21]:
# top 5 to accumulate based on CumlRnk
df_tmp = df_portfolio_features.sort_values(by = 'CumlRnk', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
47,ITC,-0.10,-19.10,47.16,19.06,129787.0,-64960.0,275206.0,452.00,-55.52,50.0,X-LC,15.68,1.0,-0.50,1.82,6.76,X40,NTT,FMCG
79,TCS,0.45,-29.39,79.26,26.57,259265.0,-136166.0,327107.0,4311.59,-40.35,40.0,X-LC,14.32,2.0,-0.53,2.16,2.09,X40,ATH,IT
45,INFY,0.35,-19.45,66.65,34.24,167987.0,-60845.0,252043.0,1972.00,-36.50,40.0,X-LC,16.09,3.0,-0.36,1.67,2.71,X40,NTT,IT
81,TMPV,-2.01,-20.72,72.27,36.58,203890.0,-73718.0,282123.0,600.00,-83.62,51.0,X-LC,5.33,4.0,-0.36,1.87,17.59,XY24,NTT,AUTO
59,PIDILITIND,-1.95,2.56,15.41,18.37,22301.0,3610.0,144720.0,1670.26,-28.20,61.0,X-LC,5.41,5.0,0.16,0.96,13.63,X40,ATH,CHEMICALS

In [22]:
# top 5 for average up
df_tmp = df_portfolio_features[(df_portfolio_features['Dev%_200'] > 5)].sort_values(by = 'CurrAlloc%', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
44,INDUSINDBK,-2.94,-31.87,95.06,32.89,50002.0,-24606.0,52600.0,1800.00,-347.90,59.0,L-MC,6.41,258.0,-0.49,0.35,29.47,XR,NTT,BANKS
12,BOSCH-HCIL,1.06,-35.90,55.98,-0.01,45863.0,-45877.0,81928.0,2282.00,16660.87,64.0,M-SC,5.15,231.0,-1.00,0.54,39.45,OX40N,BTT,AC
72,SIS,-1.02,-11.29,36.70,21.26,36147.0,-12538.0,98494.0,528.00,2340.41,68.0,H-SC,11.39,168.0,-0.35,0.65,46.45,OX40N,NTT,MISC
73,SONACOMS,-0.74,-0.53,39.83,39.09,40079.0,-534.0,100625.0,804.02,-21.15,53.0,M-MC,19.98,193.0,-0.01,0.67,42.35,AR,ATH,AUTO
55,MASFIN,-0.55,5.59,15.13,21.57,15653.0,5475.0,103455.0,397.04,-8.76,67.0,H-SC,4.95,167.0,0.35,0.68,30.13,XR,ATH,FINANCE

In [23]:
# top 5 RSP
df_tmp = df_portfolio_features.sort_values(by = 'RSP', ascending=False)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
75,SURYODAY,-0.79,1.67,21.01,23.03,38253.0,2999.0,182070.0,216.00,97.37,82.0,H-SC,10.43,166.0,0.08,1.20,53.30,XR,NTT,BANKS
68,SATIN,1.35,19.47,27.09,51.83,89415.0,53784.0,330068.0,274.00,6.44,82.0,H-SC,18.78,159.0,0.60,2.18,60.79,XY24,NTT,FINANCE
25,FINCABLES,-2.30,41.22,47.22,107.91,98456.0,60861.0,208505.0,1641.55,26.84,75.0,M-SC,20.05,220.0,0.62,1.38,56.87,OX40N,ATH,CABLES
72,SIS,-1.02,-11.29,36.70,21.26,36147.0,-12538.0,98494.0,528.00,2340.41,68.0,H-SC,11.39,168.0,-0.35,0.65,46.45,OX40N,NTT,MISC
77,TANLA,-1.09,-36.86,244.10,117.25,417282.0,-99814.0,170947.0,1922.32,-36.34,63.0,H-SC,16.54,147.0,-0.24,1.13,49.67,AR,ATH,IT

In [24]:
# Top N allocation
df_tmp = df_portfolio_features.sort_values(by = 'CurrAlloc%', ascending=False)
top_n_values = [10, 25, 50]

sum_df = pd.DataFrame({
    'Top_N': top_n_values,
    'Sum_Alloc%': [df_tmp['CurrAlloc%'].head(n).sum() for n in top_n_values]
})

sum_df

   Top_N  Sum_Alloc%
0     10       19.09
1     25       42.39
2     50       72.62

In [25]:
# market-cap-wise allocation
df_tmp = df_portfolio_features[cols]
df_tmp.groupby(df_tmp['Conviction'].str[-2:])['CurrAlloc%'].sum().sort_values(ascending=False)

Conviction
SC    43.02
LC    31.25
MC    25.71
Name: CurrAlloc%, dtype: float64

In [26]:
# criteria-wise allocation
df_portfolio_features.groupby('Criteria')['CurrAlloc%'].sum().sort_values(ascending=False)

Criteria
XY24     27.35
X40      25.49
X40N     16.63
XR        9.23
OX40N     7.05
XY25      6.75
AR        6.64
SR        0.84
Name: CurrAlloc%, dtype: float64

In [27]:
# conviction-wise allocation
df_portfolio_features.groupby('Conviction')['CurrAlloc%'].sum().sort_values(ascending=False)

Conviction
X-LC    29.16
H-SC    22.62
X-MC    20.83
M-SC    10.14
X-SC     9.72
H-MC     2.58
M-MC     1.95
H-LC     1.18
M-LC     0.91
L-SC     0.54
L-MC     0.35
Name: CurrAlloc%, dtype: float64

In [28]:
# sector-wise stats
df_tmp = df_portfolio_features.groupby('Category')[['CurrAlloc%', 'Current', 'Current P/L', 'FTT Amt']].sum().sort_values(by=['Current', 'Current P/L'], ascending=False)
df_tmp['Current P/L%'] = round(df_tmp['Current P/L'] * 100 / df_tmp['Current'], 2)
df_tmp['FTT%'] = round(df_tmp['FTT Amt'] * 100 / df_tmp['Current'], 2)
cols = ['CurrAlloc%', 'Current P/L%', 'FTT%']
df_tmp[cols].sort_values(by=['CurrAlloc%'], ascending=False)

               CurrAlloc%  Current P/L%    FTT%
Category
FMCG                15.36        -13.83   53.99
FINANCE             10.86        -12.06   60.80
IT                  10.37        -43.64  115.95
MISC                 7.10        -25.02   79.32
AUTO                 6.64         -9.33   50.31
BANKS                5.70         -5.26   53.92
PAINTS               5.38        -21.16   42.19
INSURANCE            5.37         -1.96   36.66
PHARMA               4.88         -0.53   32.84
ELECTRICAL           3.89        -20.21   63.00
CHEMICALS            2.15        -25.27   99.93
HEALTHCARE           1.98        -19.63   50.84
AC                   1.85        -14.21   45.18
FOOTWEAR             1.70        -71.47  140.22
APPARELS             1.70         -4.14   39.67
TRAVEL               1.70        -73.87  160.93
DURABLES             1.69        -51.26   88.05
BREWERIES            1.45         -7.08   29.32
REALTY               1.41         -4.11   21.21
CABLES               1.38         29.19   47.22
CERAMICS             1.36        -48.86   94.08
ENGINEERING          1.23        -30.22   89.78
REFINERIES           1.21         -9.89   37.69
CEMENT               1.07        -65.10  188.61
JEWELLERY            1.07        -99.40  168.67
ENTERTAINMENT        0.72        -76.80  182.25
TEXTILES             0.43        -42.28   82.86
HOTELS               0.33       -129.14  209.96

In [29]:
# money to be made criteria-wise
df_portfolio_features.groupby('Criteria')['FTT Amt'].agg(['sum', 'count']).sort_values(by='sum', ascending=False)

                sum  count
Criteria
XY24      3460745.0     21
X40       1845996.0     19
XR        1286303.0     13
X40N      1211850.0     13
AR        1180197.0      9
OX40N      725716.0     10
XY25       420026.0      5
SR         292702.0      2

In [30]:
# money to be made conviction-wise
df_portfolio_features.groupby('Conviction')['FTT Amt'].agg(['sum', 'count']).sort_values(by='sum', ascending=False)

                  sum  count
Conviction
H-SC        3362930.0     24
X-LC        1889492.0     21
X-MC        1583477.0     15
M-SC        1385679.0     14
X-SC        1333090.0      9
H-MC         307612.0      2
L-SC         210144.0      2
M-LC         154532.0      1
M-MC          91482.0      2
H-LC          55095.0      1
L-MC          50002.0      1

In [31]:
# money to be made criteria and conviction-wise
df_portfolio_features.groupby(['Conviction', 'Criteria'])['FTT Amt'].agg(['sum', 'count']).sort_values(by='sum', ascending=False)

                           sum  count
Conviction Criteria
H-SC       XY24      1057427.0      6
X-LC       X40       1003379.0     10
H-SC       AR         933243.0      5
M-SC       XY24       832423.0      6
X-SC       XY24       781221.0      4
H-SC       XR         758787.0      7
X-MC       X40        641163.0      7
           X40N       495495.0      4
X-LC       X40N       365940.0      6
X-SC       X40N       350415.0      3
X-LC       XY24       346531.0      2
H-SC       OX40N      320771.0      4
M-SC       OX40N      298847.0      5
H-SC       SR         292702.0      2
X-MC       XY25       235526.0      2
H-MC       XY24       231850.0      1
X-MC       XY24       211293.0      2
X-SC       X40        201454.0      2
M-SC       XR         178391.0      2
M-LC       XR         154532.0      1
X-LC       XY25       133097.0      2
L-SC       OX40N      106098.0      1
           XR         104046.0      1
M-SC       AR          76018.0      1
H-MC       AR          75762.0      1
H-LC       AR          55095.0      1
M-MC       XY25        51403.0      1
L-MC       XR          50002.0      1
X-LC       XR          40545.0      1
M-MC       AR          40079.0      1

In [32]:
# notebook execution time

end_time = time.time()
execution_time = round(end_time - start_time, 0)
print(f"Notebook execution time: {execution_time} seconds")

Notebook execution time: 28.0 seconds