<a href="https://colab.research.google.com/github/ankit-rathi/Quantvesting_v2/blob/main/myStocks_Portfolio_Analysis.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
'''
!pip install pandas==2.2.2 -qq
!pip install pyxirr -qq
!pip install ta -qq
!pip install yfinance==0.2.59 -qq
'''

'\n!pip install pandas==2.2.2 -qq\n!pip install pyxirr -qq\n!pip install ta -qq\n!pip install yfinance==0.2.59 -qq\n'

In [2]:
# import libraries

import numpy as np
import pandas as pd
import datetime
import warnings
warnings.filterwarnings('ignore')
import yfinance as yfin
import ta
import matplotlib.pyplot as plt
import requests

In [3]:
# notebook start time
import time
import datetime
import pytz

start_time = time.time()

# function to print date timestamp
def print_date_time():
  tz_NY = pytz.timezone('Asia/Kolkata')
  datetime_NY = datetime.datetime.now(tz_NY)
  print("Run date time (IST):", datetime_NY.strftime("%Y-%m-%d %H:%M:%S"))

In [4]:
# function to get booked and reserved amount
def get_amt():
  # fetch the JSON data from the URL
  url = "https://raw.githubusercontent.com/ankit-rathi/Tradevesting_v1/main/data/myPortfolioAmts.json"
  response = requests.get(url)
  pf_amts = response.json()  # parse the JSON data

  # extract values from the JSON
  py_booked_amt_dm = pf_amts["py_booked_amt_dm"]
  py_booked_amt_sv = pf_amts["py_booked_amt_sv"]
  cy_booked_amt_dm = pf_amts["cy_booked_amt_dm"]
  cy_booked_amt_sv = pf_amts["cy_booked_amt_sv"]
  reserve_amt_dm = pf_amts["reserve_amt_dm"]
  reserve_amt_sv = pf_amts["reserve_amt_sv"]

  # perform calculations
  py_booked_amt = py_booked_amt_dm + py_booked_amt_sv
  cy_booked_amt = cy_booked_amt_dm + cy_booked_amt_sv
  reserve_amt = reserve_amt_dm + reserve_amt_sv
  total_booked_amt = py_booked_amt + cy_booked_amt

  return total_booked_amt, reserve_amt, cy_booked_amt, py_booked_amt

gen_output = 0

In [5]:
# function to format the amount
def format_amt(number):
    abs_number = abs(number)

    if abs_number >= 1_00_00_000:  # Crores
        formatted_amt = f"{number / 1_00_00_000:.2f} C"
    elif abs_number >= 1_00_000:  # Lakhs
        formatted_amt = f"{number / 1_00_000:.2f} L"
    elif abs_number >= 1_000:  # Thousands
        formatted_amt = f"{number / 1_000:.2f} K"
    else:
        formatted_amt = f"{number:.2f}"

    return formatted_amt

# function to set start and end date
def get_start_end_date():
  start_date = (datetime.date.today() + datetime.timedelta(days=-365)).strftime('%Y-%m-%d')
  end_date = (datetime.date.today() + datetime.timedelta(days=1)).strftime('%Y-%m-%d')
  return start_date, end_date

# function to fetch my portfolio csv
def get_mypfs_df():
  mypfs_df = pd.read_csv('https://raw.githubusercontent.com/ankit-rathi/Tradevesting_v1/main/data/myPortfolioStocks.csv')
  return mypfs_df

# function to fetch my prospects csv
def get_mypps_df():
  mypps_df = pd.read_csv('https://raw.githubusercontent.com/ankit-rathi/Tradevesting_v1/main/data/myProspectsScrips.csv')
  return mypps_df

# function to fetch screener data
def get_myscreen_df():
  myscreen_df = pd.read_csv('https://raw.githubusercontent.com/ankit-rathi/Tradevesting_v1/main/data/myScreenerDB.csv')
  return myscreen_df

# function to fetch momentum data
def get_myinvmt_df():
  myinvmt_df = pd.read_csv('https://raw.githubusercontent.com/ankit-rathi/Tradevesting_v1/main/data/myInvestments.csv')
  return myinvmt_df

# function to get the stock ids
def get_stock_ids(df_pf):
  stock_n100 = df_pf['Symbol'].unique()

  exclude = ['CADILAHC','MMTC', 'MASFIN']

  stock_ids = df_pf[~df_pf['Symbol'].isin(exclude) ]['Symbol'].unique()

  #mypf = mypf[mypf.Forecast.notnull()]
  #stock_ids = mypf['Symbol'].unique()

  #stock_ids.sort()
  return stock_ids

# get features from screener data
def get_screener_features():
  myscreen_df = get_myscreen_df()
  cols = ['Symbol', 'EPS', 'MedPE', 'ROCE%', 'ROE%', 'CapType']
  return myscreen_df[cols]

# get relative strength
def get_relative_strength(stock_list):

    # Dictionary to store stock tickers and their corresponding percentage price change
    stock_changes = {}

    # Loop through each stock and fetch its price data
    for stock in stock_list:
        try:
            # Download the stock data for the given date range
            stock_data = yfin.Ticker(stock + '.NS').history(period='1mo', interval='1d')[map(str.title, ['open', 'close', 'low', 'high', 'volume'])]

            # Calculate the percentage change for the stock
            if len(stock_data) > 0:
                start_price = stock_data['Close'].iloc[0]
                end_price = stock_data['Close'].iloc[-1]
                percent_change = round(((end_price - start_price) / start_price) * 100, 2)
                stock_changes[stock] = percent_change
            else:
                stock_changes[stock] = np.nan  # If no data is available, set to NaN

        except Exception as e:
            print(f"Error fetching data for {stock}: {e}")
            stock_changes[stock] = np.nan

    # Create a DataFrame with stock tickers and their percentage changes
    df = pd.DataFrame(list(stock_changes.items()), columns=['Symbol', 'Percent_Change'])

    # Drop any stocks with missing data (NaN values)
    df = df.dropna()

    # Calculate the percentile rank based on percentage change
    df['RSP'] = round(df['Percent_Change'].rank(pct=True) * 100, 2)
    cols = ['Symbol', 'RSP']
    df = df[cols]
    # Sort by percentile rank (optional)
    df = df.sort_values(by='RSP', ascending=False).reset_index(drop=True)

    return df

In [6]:
# function to get stock technicals
def stock_prec_dev(stock_symbol):
    #stock_symbol = 'ULTRACEMCO.NS'
    short_window = 20
    mid_window = 50
    long_window = 200
    moving_avg = 'SMA'

    start = datetime.datetime(*map(int, start_date.split('-')))
    end = datetime.datetime(*map(int, end_date.split('-')))

    stock_df = yfin.Ticker(stock_symbol + '.NS').history(period='max', interval='1d')[map(str.title, ['open', 'close', 'low', 'high', 'volume'])]

    stock_df['Max'] = round(max(stock_df['Close']),2)
    stock_df = stock_df[(stock_df.index <= end_date) & (stock_df.index >= start_date)]
    stock_df['200_SMA'] = round(stock_df['Close'].rolling(window = 200, min_periods = 1).mean(),0)
    stock_df['Dev%_200'] = round((stock_df['Close'] - stock_df['200_SMA'])*100/stock_df['200_SMA'],2)
    stock_df.dropna(axis = 0, inplace = True) # remove any null rows

    stock_df['20_SMA'] = stock_df['Close'].rolling(window=20).mean()
    stock_df['50_SMA'] = stock_df['Close'].rolling(window=50).mean()
    stock_df['Symbol'] = stock_symbol

    stock_df['Close'] = round(stock_df['Close'],2)
    stock_df['Min'] = round(min(stock_df['Close']),2)
    stock_df['RSI_14'] = ta.momentum.RSIIndicator(close=stock_df['Close'], window=14).rsi()
    stock_df['RSI_14'] = round(stock_df['RSI_14'],0)
    stock_df['Prev_Close'] = stock_df['Close'].shift(1)
    stock_df.drop(['Open', 'Low', 'High', 'Volume'], axis=1, inplace=True)
    stock_df = stock_df.tail(1)

    max_SMA = max(stock_df['20_SMA'].item(), stock_df['50_SMA'].item(), stock_df['200_SMA'].item())
    min_SMA = min(stock_df['20_SMA'].item(), stock_df['50_SMA'].item(), stock_df['200_SMA'].item())
    ABS_Spread = max_SMA - min_SMA
    stock_df['Spread%'] = round((ABS_Spread / stock_df['200_SMA'].item()) * 100,2)

    return stock_df

# function to compute stock attributes
def get_common_features(stock_ids, df_mypf):

  df_prec_dev = pd.DataFrame()
  df_tmp = get_screener_features()
  df_rs = get_relative_strength(stock_ids)

  for stock_id in stock_ids:
      tmp = stock_prec_dev(stock_id)
      tmp = tmp.reset_index()
      df_prec_dev = pd.concat([df_prec_dev, tmp], ignore_index = True)
  df_prec_dev = pd.merge(df_prec_dev, df_mypf, on= 'Symbol')
  df_prec_dev = pd.merge(df_prec_dev, df_tmp, on= 'Symbol', how='left')
  df_prec_dev = pd.merge(df_prec_dev, df_rs, on= 'Symbol', how='left')
  #print(df_prec_dev.columns)
  df_prec_dev['Curr_PE'] = round(df_prec_dev['Close']/df_prec_dev['EPS'],1)
  df_prec_dev['Dev%_PE'] = round((df_prec_dev['Curr_PE'] - df_prec_dev['MedPE'])*100/df_prec_dev['MedPE'],2)
  df_prec_dev['Conviction'] = df_prec_dev['Conviction'] + '-' + df_prec_dev['CapType']
  return df_prec_dev

# function to arrange stock features
def arrange_features(df_stocks, common_cols, diff_cols):
  df_stocks_common = df_stocks[common_cols].drop_duplicates()
  df_stocks_diff = df_stocks[diff_cols]
  df_stocks_diff['Investment'] = df_stocks_diff['AvgCost'] * df_stocks_diff['Shares']
  df_stocks_diff = df_stocks_diff.groupby(['Symbol'])[['Shares', 'Investment']].aggregate(['sum']).reset_index()
  df_stocks_diff.columns = ['Symbol', 'Shares', 'Investment']
  df_stocks_diff['AvgCost'] = round(df_stocks_diff['Investment']/df_stocks_diff['Shares'],2)
  df_stocks = pd.merge(df_stocks_diff, df_stocks_common, on='Symbol')
  return df_stocks

# plot fact distribution across dimension
def plot_pie_chart(df, dimension, fact):
  # grouping the data by category and calculating the sum of fact for each type
  grouped_data = df.groupby(dimension)[fact].sum()

  # sorting the grouped data in descending order
  grouped_data = grouped_data.sort_values(ascending=False)

  # creating a pie chart
  grouped_data.plot.pie(autopct='%1.1f%%', startangle=90, figsize=(6, 6))

  # adding a title and displaying the plot
  plt.title(f'{dimension} {fact} Distribution')
  plt.ylabel('')  # To hide the y-label
  plt.show()

In [7]:
# function to get portfolio features

def get_portfolio_features(df_common_features):

  print_date_time()
  print('-------------------')

  #df_common_features["Target"] = df_common_features["Target"].fillna(df_common_features["Max"])
  df_common_features['NTT'] = np.where(df_common_features['Strategy']== 'NTT', df_common_features["Target"], df_common_features['Max'])
  df_common_features['LTT'] = np.where(df_common_features['Strategy']== 'BTT', df_common_features["Target"], df_common_features['Max'])
  df_common_features['BOL'] = df_common_features['Min']

  tmp_df = df_common_features[df_common_features['Symbol'].isin(mypf_df[mypf_df['InPortfolio'] != 'NA'].Symbol.values)]
  print('qualified stocks: '+str(len(tmp_df['Symbol'].unique())))
  tmp_df1 = tmp_df[tmp_df['LatestQtr'] == 1]
  print('with latest results: '+str(len(tmp_df1['Symbol'].unique())))
  tmp_df1 = tmp_df1[tmp_df1['StarStock'] == 1]
  print('still star stocks: '+str(len(tmp_df1['Symbol'].unique())))
  tmp_df['Investment'] = tmp_df['AvgCost'] * tmp_df['Shares']
  tmp_df['Current'] = round(tmp_df['Close'] * tmp_df['Shares'],0)
  tmp_df['Previous'] = tmp_df['Prev_Close'] * tmp_df['Shares']
  tmp_df['EstimatedST'] = tmp_df['NTT'] * tmp_df['Shares']
  tmp_df['EstimatedLT'] = tmp_df['LTT'] * tmp_df['Shares']
  tmp_df['Current P/L'] = round((tmp_df['Current'] - tmp_df['Investment']),0)
  tmp_df['Today P/L%'] = round((tmp_df['Current'] - tmp_df['Previous'])*100/tmp_df['Previous'],2)
  tmp_df['Current P/L%'] = round((tmp_df['Current'] - tmp_df['Investment'])*100/tmp_df['Investment'],2)
  tmp_df['EstimatedST P/L%'] = round((tmp_df['EstimatedST'] - tmp_df['Investment'])*100/tmp_df['Investment'],2)
  tmp_df['EstimatedLT P/L%'] = round((tmp_df['EstimatedLT'] - tmp_df['Investment'])*100/tmp_df['Investment'],2)
  tmp_df['NTT%'] = round((tmp_df['NTT'] - tmp_df['Close'])*100/tmp_df['Close'],2)
  tmp_df['LTT%'] = round((tmp_df['LTT'] - tmp_df['Close'])*100/tmp_df['Close'],2)
  tmp_df['Gained%'] = round((tmp_df['Close'] - tmp_df['BOL'])*100/tmp_df['BOL'],2)
  investment = round(sum(tmp_df['AvgCost']*tmp_df['Shares']),0)
  current = round(sum(tmp_df['Close']*tmp_df['Shares']),0)
  tmp_df['InitAlloc%'] = round(tmp_df['Investment']*100/investment,2)
  tmp_df['CurrAlloc%'] = round(tmp_df['Current']*100/current,2)
  tmp_df['FTT'] = tmp_df['LTT']
  tmp_df.loc[tmp_df['Strategy'] == 'NTT', 'FTT'] = tmp_df['NTT']
  tmp_df['FTT%'] = tmp_df['LTT%']
  tmp_df.loc[tmp_df['Strategy'] == 'NTT', 'FTT%'] = tmp_df['NTT%']
  tmp_df['FTT Amt'] = round(tmp_df['FTT%'] * tmp_df['Current']/100,0)
  tmp_df['OTT%'] = round((tmp_df['FTT'] - tmp_df['AvgCost'])*100/tmp_df['AvgCost'],2)
  tmp_df['RRR Ind'] = round(tmp_df['Current P/L']/tmp_df['FTT Amt'],2)
  tmp_df['Risk Ind'] = round(tmp_df['Current P/L%']*tmp_df['CurrAlloc%'],0)

  return tmp_df

# function to print portfolio features
def print_portfolio_stats(df_portfolio_features, myinvmt_df):
  from pyxirr import xirr

  total_booked_amt, reserve_amt, cy_booked_amt, py_booked_amt = get_amt()

  dates = myinvmt_df['Date'].values
  dates = np.append(dates, datetime.date.today().strftime('%d-%b-%y'))
  investment = myinvmt_df['Investment'].values
  dates= pd.to_datetime(dates)

  current = round(sum(df_portfolio_features['Close']*df_portfolio_features['Shares']),0) + reserve_amt
  investment_xirr = np.append(investment, current)
  cagr = round(xirr(pd.DataFrame({"dates": dates, "amounts": investment_xirr}))*100,2)

  investment = -sum(investment)
  invested = round(sum(df_portfolio_features['AvgCost']*df_portfolio_features['Shares']),0) + reserve_amt
  previous = round(sum(df_portfolio_features['Prev_Close']*df_portfolio_features['Shares']),0) + reserve_amt
  cy_invested = investment + py_booked_amt

  today_pnl_amount = current-previous
  today_pnl_percentage = round((current-previous)*100/previous,2)

  curr_pnl_amount = current-invested
  curr_pnl_percentage = round((curr_pnl_amount)*100/(cy_invested),2)

  cy_pnl_amount = cy_booked_amt + curr_pnl_amount
  cy_pnl_percentage = round((cy_pnl_amount)*100/cy_invested,2)

  overall_pnl_amount = total_booked_amt + curr_pnl_amount
  overall_pnl_percentage = round((overall_pnl_amount)*100/investment,2)

  estimate_st = round(sum(df_portfolio_features['FTT']*df_portfolio_features['Shares']),0)  + reserve_amt
  est_st_pnl_amount = estimate_st-current
  est_st_pnl_percentage = round((est_st_pnl_amount)*100/current,2)

  estimate_lt = round(sum(df_portfolio_features['LTT']*df_portfolio_features['Shares']),0)  + reserve_amt
  est_lt_pnl_amount = estimate_lt-current
  est_lt_pnl_percentage = round((est_lt_pnl_amount)*100/current,2)

  total_profit = round(sum(df_portfolio_features[df_portfolio_features['Current P/L%'] > 0]['Current']) - sum(df_portfolio_features[df_portfolio_features['Current P/L%'] > 0]['Investment']),0)
  total_loss = round(sum(df_portfolio_features[df_portfolio_features['Current P/L%'] < 0]['Current']) - sum(df_portfolio_features[df_portfolio_features['Current P/L%'] < 0]['Investment']),0)

  cy_booked_percentage = round((cy_booked_amt)*100/current,2)
  py_booked_percentage = round((py_booked_amt)*100/investment,2)
  total_booked_percentage = round((total_booked_amt)*100/investment,2)

  print('-------------------')
  print('Initial Investment: ', format_amt(investment))
  print('CY Investment: ', format_amt(cy_invested))
  print('Reserve: ', format_amt(reserve_amt))
  print('Current: ',  format_amt(current))
  print('-------------------')
  print('Today PnL: '+ '{} ({}%)'.format(format_amt(today_pnl_amount), today_pnl_percentage))
  print('Current PnL: '+ '{} ({}%)'.format(format_amt(curr_pnl_amount), curr_pnl_percentage))
  print('CY Booked + Current PnL: '+ '{} ({}%)'.format(format_amt(cy_pnl_amount), cy_pnl_percentage))
  print('-------------------')
  print('Total profit: ', format_amt(total_profit))
  print('Total loss: ', format_amt(total_loss))
  print('-------------------')
  print('Total Booked + Current PnL: '+ '{} ({}%)'.format(format_amt(overall_pnl_amount), overall_pnl_percentage))
  print('Total Booked PnL: '+ '{} ({}%)'.format(format_amt(total_booked_amt), total_booked_percentage))
  print('Curr Year Booked PnL: '+ '{} ({}%)'.format(format_amt(cy_booked_amt), cy_booked_percentage))
  print('Prev Year Booked PnL: '+ '{} ({}%)'.format(format_amt(py_booked_amt), py_booked_percentage))
  print('===================')
  print('Est FTT: ',  format_amt(estimate_st))
  print('Est FTT PnL: '+ '{} ({}%)'.format(format_amt(est_st_pnl_amount), est_st_pnl_percentage))

  print('===================')
  print('Deployed: ', format_amt(investment))

  print('Current: ', format_amt(current))

  print('CAGR/XIRR %: '+'{}%'.format(cagr))

In [8]:
# get start and end date
start_date, end_date = get_start_end_date()

# get portfolio and prospects data
mypfs_df = get_mypfs_df()
mypps_df = get_mypps_df()
myinvmt_df = get_myinvmt_df()

# merge above datasets
mypf_df = pd.merge(mypfs_df, mypps_df, on="Symbol")

# seggregate dm and sv portfolio
dm_pf = mypf_df[mypf_df['InPortfolio'] == 'DM']
sv_pf = mypf_df[mypf_df['InPortfolio'] == 'SV']

# build portfolio stock dataframe
dm_stocks = get_stock_ids(dm_pf)
sv_stocks = get_stock_ids(sv_pf)
df_stocks = pd.concat([dm_pf,sv_pf], ignore_index = True)

# arrange common and diff stock features
common_cols = ['Symbol', 'Target', 'Criteria', 'Strategy', 'CumlRnk', 'LatestQtr', 'StarStock', 'Conviction', 'Category', 'InFolio', 'XIRR', 'MBQ']
diff_cols = ['Symbol', 'AvgCost', 'Shares']
df_stocks = arrange_features(df_stocks, common_cols, diff_cols)

# get common features
stock_ids = df_stocks['Symbol'].values
df_common_features = get_common_features(stock_ids, df_stocks)

df_common_features.reset_index(drop=True, inplace=True)
df_common_features.drop(['Date'], axis=1, inplace=True)
# get and print portfolio features
df_portfolio_features = get_portfolio_features(df_common_features)

print_portfolio_stats(df_portfolio_features, myinvmt_df)

df = df_portfolio_features
#plot_pie_chart(df, 'CapType', 'Current')
list_ox40n = list(df[df['MBQ'].str.contains('OX40N', na=False)]['Symbol'].values)

Run date time (IST): 2026-03-30 13:39:39
-------------------
qualified stocks: 86
with latest results: 26
still star stocks: 16
-------------------
Initial Investment:  1.36 C
CY Investment:  1.62 C
Reserve:  1.61 K
Current:  1.25 C
-------------------
Today PnL: -2.57 L (-2.01%)
Current PnL: -51.73 L (-31.84%)
CY Booked + Current PnL: -35.84 L (-22.06%)
-------------------
Total profit:  27.17 K
Total loss:  -52.00 L
-------------------
Total Booked + Current PnL: -8.86 L (-6.54%)
Total Booked PnL: 42.87 L (31.64%)
Curr Year Booked PnL: 15.89 L (12.67%)
Prev Year Booked PnL: 26.98 L (19.91%)
===================
Est FTT:  2.48 C
Est FTT PnL: 1.22 C (97.68%)
===================
Deployed:  1.36 C
Current:  1.25 C
CAGR/XIRR %: -3.75%

In [9]:
# top 5 near their targets
cols = ['Symbol', 'Today P/L%', 'Current P/L%', 'FTT%', 'OTT%', 'FTT Amt', 'Current P/L', 'Current', 'FTT', 'Dev%_PE', 'RSI_14','Conviction', 'Spread%',  'CumlRnk', 'RRR Ind', 'CurrAlloc%', 'Gained%', 'Criteria', 'Strategy', 'Category']
df_tmp = df_portfolio_features[~df_portfolio_features['Symbol'].isin(['ENRIN','BLUSPRING','DIGITIDE'])]
df_tmp = df_tmp.sort_values(by = 'FTT Amt', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
50,MASFIN,-0.75,-11.21,36.91,21.57,32112.0,-10980.0,87000.0,397.04,-23.67,39.0,H-SC,4.17,167.0,-0.34,0.69,18.66,XR,ATH,FINANCE
77,TTKPRESTIG,-2.60,-44.29,79.65,0.09,44721.0,-44630.0,56147.0,770.00,30.42,33.0,M-SC,21.29,250.0,-1.00,0.45,0.00,OX40N,NTT,DURABLES
2,ABBOTINDIA,-0.75,-12.98,35.68,18.07,55532.0,-23215.0,155640.0,35195.00,-25.88,43.0,X-MC,10.48,58.0,-0.42,1.24,1.79,X40,ATH,PHARMA
67,SONACOMS,-0.48,-15.86,65.30,39.09,55583.0,-16039.0,85120.0,804.02,-33.30,44.0,M-MC,6.44,193.0,-0.29,0.68,20.42,AR,ATH,AUTO
37,ICICIGI,-1.45,-8.80,30.86,19.34,56316.0,-17619.0,182490.0,2252.93,-23.27,31.0,X-MC,4.96,66.0,-0.31,1.46,0.88,X40,ATH,INSURANCE

In [10]:
# top 5 today
df_tmp = df_portfolio_features.sort_values(by = 'Today P/L%', ascending=False)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
53,PGHH,2.99,-29.48,87.19,32.01,131287.0,-62944.0,150576.0,17616.87,-52.36,26.0,X-MC,17.92,57.0,-0.48,1.20,2.99,X40,ATH,FMCG
15,BSOFT,1.75,-37.94,142.97,50.79,124793.0,-53367.0,87286.0,831.70,-20.37,38.0,H-SC,7.52,172.0,-0.43,0.70,1.75,XR,ATH,IT
24,DMART,0.99,-5.25,36.78,29.60,86985.0,-13098.0,236502.0,5391.45,-20.14,57.0,X-LC,6.79,14.0,-0.15,1.89,8.10,X40N,ATH,FMCG
59,RELIANCE,-0.19,-13.63,45.08,25.30,78245.0,-27393.0,173570.0,1952.00,-15.80,37.0,X-LC,3.83,21.0,-0.35,1.38,15.89,XY25,BTT,REFINERIES
67,SONACOMS,-0.48,-15.86,65.30,39.09,55583.0,-16039.0,85120.0,804.02,-33.30,44.0,M-MC,6.44,193.0,-0.29,0.68,20.42,AR,ATH,AUTO

In [11]:
# bottom 5 today
df_tmp = df_portfolio_features.sort_values(by = 'Today P/L%', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
56,RAJOOENG,-6.57,-53.69,201.45,39.61,95628.0,-55030.0,47470.0,143.1,-68.70,28.0,H-SC,33.07,136.0,-0.58,0.38,0.00,AR,ATH,MISC
19,COFFEEDAY,-5.33,-63.98,275.59,35.27,112705.0,-72653.0,40896.0,80.0,-71.83,25.0,L-SC,29.63,266.0,-0.64,0.33,0.00,XR,NTT,HOTELS
69,SURYODAY,-5.25,-30.95,78.19,23.03,96677.0,-55427.0,123644.0,216.0,33.77,41.0,H-SC,5.67,166.0,-0.57,0.99,16.08,XR,NTT,BANKS
49,LAOPALA,-5.00,-50.51,181.04,39.09,117466.0,-66221.0,64884.0,464.0,42.02,25.0,H-SC,16.84,154.0,-0.56,0.52,0.00,AR,NTT,CERAMICS
55,RAJESHEXPO,-5.00,-84.47,544.44,0.07,115971.0,-115876.0,21301.0,518.0,680.30,17.0,L-SC,39.57,268.0,-1.00,0.17,0.00,OX40N,NTT,JEWELLERY

In [12]:
# top 5 to exit based on CumlRnk
df_tmp = df_portfolio_features[~df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])]
df_tmp = df_tmp[(df_tmp['Current P/L%'] > -1) & (df_tmp['Current P/L%'] < 1)].sort_values(by = 'CumlRnk', ascending=False)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
26,FINCABLES,-2.1,0.03,107.86,107.91,159291.0,39.0,147683.0,1641.55,-10.2,41.0,M-SC,7.38,220.0,0.0,1.18,11.11,OX40N,ATH,CABLES

In [13]:
# OX40N stocks to exit
df_tmp = df_portfolio_features[(df_portfolio_features['Symbol'].isin(list_ox40n))].sort_values(by = 'Current P/L%', ascending=False)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
26,FINCABLES,-2.10,0.03,107.86,107.91,159291.0,39.0,147683.0,1641.55,-10.20,41.0,M-SC,7.38,220.0,0.00,1.18,11.11,OX40N,ATH,CABLES
66,SIS,-1.61,-34.78,85.92,21.26,62223.0,-38612.0,72420.0,528.00,1694.30,45.0,H-SC,14.41,168.0,-0.62,0.58,7.68,OX40N,NTT,MISC
18,CERA,-1.51,-40.24,107.32,23.89,112812.0,-70786.0,105117.0,9475.00,-42.24,41.0,H-SC,19.33,153.0,-0.63,0.84,1.02,OX40N,NTT,CERAMICS
72,TATAELXSI,-2.93,-41.79,126.82,32.03,97318.0,-55098.0,76737.0,9161.00,-27.25,33.0,H-SC,21.50,158.0,-0.57,0.61,0.00,OX40N,NTT,IT
48,KANSAINER,-0.90,-43.61,101.23,13.47,153934.0,-117603.0,152064.0,340.00,-51.62,34.0,H-SC,22.41,162.0,-0.76,1.21,6.22,XY24,NTT,PAINTS

In [14]:
# top 5 to book for rotation
df_tmp = df_portfolio_features[(df_portfolio_features['Current P/L%'] > 20) ].sort_values(by = 'CumlRnk', ascending=False)
df_tmp[cols].head()

Empty DataFrame
Columns: [Symbol, Today P/L%, Current P/L%, FTT%, OTT%, FTT Amt, Current P/L, Current, FTT, Dev%_PE, RSI_14, Conviction, Spread%, CumlRnk, RRR Ind, CurrAlloc%, Gained%, Criteria, Strategy, Category]
Index: []

In [15]:
# top 5 to monitor for exit
df_tmp = df_portfolio_features[~df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])]
df_tmp = df_tmp[(df_tmp['Current P/L%'] > 0) ].sort_values(by = 'Dev%_PE', ascending=False)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
26,FINCABLES,-2.10,0.03,107.86,107.91,159291.0,39.0,147683.0,1641.55,-10.20,41.0,M-SC,7.38,220.0,0.00,1.18,11.11,OX40N,ATH,CABLES
1,ABB,-1.63,10.18,32.11,45.57,92562.0,26645.0,288264.0,7934.00,-29.24,48.0,H-MC,13.26,125.0,0.29,2.30,28.01,AR,NTT,ELECTRICAL

In [16]:
# top 5 to book for rotation from weak conviction
df_tmp = df_portfolio_features[~df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])]
df_tmp = df_tmp[~df_tmp['Criteria'].isin(['XY25','XY24','X40', 'X40N'])].sort_values(by = 'RRR Ind', ascending=False)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
1,ABB,-1.63,10.18,32.11,45.57,92562.0,26645.0,288264.0,7934.00,-29.24,48.0,H-MC,13.26,125.0,0.29,2.30,28.01,AR,NTT,ELECTRICAL
26,FINCABLES,-2.10,0.03,107.86,107.91,159291.0,39.0,147683.0,1641.55,-10.20,41.0,M-SC,7.38,220.0,0.00,1.18,11.11,OX40N,ATH,CABLES
40,INDIAMART,-1.53,-16.61,147.89,106.72,152108.0,-20484.0,102852.0,4810.62,-62.30,32.0,H-SC,12.78,140.0,-0.13,0.82,2.89,AR,ATH,MISC
85,ZYDUSLIFE,-1.31,-6.68,45.34,35.63,88673.0,-14000.0,195574.0,1286.17,-18.92,46.0,H-MC,5.30,120.0,-0.16,1.56,8.88,AR,ATH,PHARMA
84,WIPRO,-1.13,-22.30,121.72,72.27,160249.0,-37794.0,131654.0,420.00,-29.71,34.0,M-LC,18.18,98.0,-0.24,1.05,1.01,XR,NTT,IT

In [17]:
# top 5 to accumulate based on lowest RSI_14
df_tmp = df_portfolio_features[df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])].sort_values(by = 'RSI_14', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
9,BAJAJHFL,-2.98,-34.27,146.64,62.13,263198.0,-93560.0,179486.0,181.50,-45.86,19.0,X-MC,21.30,60.0,-0.36,1.43,0.0,X40N,ATH,FINANCE
38,ICICIPRULI,-3.57,-15.37,54.46,30.73,90803.0,-30272.0,166733.0,790.00,-38.11,19.0,X-MC,6.52,78.0,-0.33,1.33,0.0,X40,ATH,INSURANCE
58,RELAXO,-3.58,-68.81,388.37,52.31,175815.0,-99890.0,45270.0,1176.00,-66.80,20.0,X-SC,29.71,92.0,-0.57,0.36,0.0,X40N,NTT,FOOTWEAR
27,GILLETTE,-1.81,-13.32,49.67,29.72,109306.0,-33831.0,220065.0,10978.86,-33.44,24.0,X-SC,12.28,83.0,-0.31,1.76,0.0,X40,ATH,FMCG
12,BATAINDIA,-2.97,-60.43,241.70,35.20,123054.0,-77758.0,50912.0,2096.00,-33.29,25.0,X-SC,33.03,91.0,-0.63,0.41,0.0,X40,NTT,FOOTWEAR

In [18]:
# top 5 to accumulate based on Spread and CumlRnk
df_tmp = df_portfolio_features[df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])]
df_tmp = df_tmp[(df_tmp['CumlRnk'] < 100)].sort_values(by = 'Spread%', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
65,SIEMENS,-2.95,-20.50,57.87,25.51,85619.0,-38145.0,147950.0,4671.50,24.19,39.0,H-LC,1.21,51.0,-0.45,1.18,8.95,AR,ATH,ELECTRICAL
78,UNITDSPR,-1.92,-9.67,33.69,20.77,71257.0,-22636.0,211508.0,1644.00,-19.88,35.0,X-MC,2.89,64.0,-0.32,1.69,0.00,X40N,NTT,BREWERIES
82,VOLTAS,-3.11,0.25,44.83,45.20,86174.0,483.0,192225.0,1856.00,14.77,37.0,X-MC,3.13,79.0,0.01,1.53,7.07,XY25,NTT,AC
59,RELIANCE,-0.19,-13.63,45.08,25.30,78245.0,-27393.0,173570.0,1952.00,-15.80,37.0,X-LC,3.83,21.0,-0.35,1.38,15.89,XY25,BTT,REFINERIES
37,ICICIGI,-1.45,-8.80,30.86,19.34,56316.0,-17619.0,182490.0,2252.93,-23.27,31.0,X-MC,4.96,66.0,-0.31,1.46,0.88,X40,ATH,INSURANCE

In [19]:
# top 5 to accumulate based on lowest Gained%
df_tmp = df_portfolio_features[df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])].sort_values(by = 'Gained%', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
3,ACC,-3.41,-43.18,207.66,74.81,316374.0,-115776.0,152352.0,3906.00,-59.70,25.0,X-SC,19.94,85.0,-0.37,1.22,0.0,XY24,BTT,CEMENT
12,BATAINDIA,-2.97,-60.43,241.70,35.20,123054.0,-77758.0,50912.0,2096.00,-33.29,25.0,X-SC,33.03,91.0,-0.63,0.41,0.0,X40,NTT,FOOTWEAR
10,BAJAJHLDNG,-3.60,-21.13,63.83,29.22,95718.0,-40168.0,149957.0,14451.52,-26.94,27.0,X-LC,18.57,28.0,-0.42,1.20,0.0,X40,ATH,FINANCE
9,BAJAJHFL,-2.98,-34.27,146.64,62.13,263198.0,-93560.0,179486.0,181.50,-45.86,19.0,X-MC,21.30,60.0,-0.36,1.43,0.0,X40N,ATH,FINANCE
28,GLAXO,-0.55,-9.79,54.25,39.15,97524.0,-19516.0,179768.0,3466.20,-31.08,30.0,X-MC,10.50,56.0,-0.20,1.43,0.0,X40,ATH,PHARMA

In [20]:
# top 5 to accumulate based on lowest CurrAlloc%
df_tmp = df_portfolio_features[df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])].sort_values(by = 'CurrAlloc%', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
58,RELAXO,-3.58,-68.81,388.37,52.31,175815.0,-99890.0,45270.0,1176.00,-66.80,20.0,X-SC,29.71,92.0,-0.57,0.36,0.00,X40N,NTT,FOOTWEAR
12,BATAINDIA,-2.97,-60.43,241.70,35.20,123054.0,-77758.0,50912.0,2096.00,-33.29,25.0,X-SC,33.03,91.0,-0.63,0.41,0.00,X40,NTT,FOOTWEAR
54,QUESS,-1.71,-29.84,147.87,73.90,110790.0,-31869.0,74924.0,424.00,-62.53,35.0,X-SC,22.27,80.0,-0.29,0.60,0.70,XY24,NTT,MISC
36,HONAUT,-1.74,-31.13,119.72,51.31,158988.0,-60038.0,132800.0,58357.33,-42.72,26.0,X-SC,17.20,90.0,-0.38,1.06,0.00,X40N,ATH,ELECTRICAL
51,MEDANTA,-0.92,-16.49,52.22,27.12,76975.0,-29111.0,147406.0,1486.00,-18.99,32.0,X-SC,14.11,87.0,-0.38,1.18,0.68,XY24,NTT,HEALTHCARE

In [21]:
# top 5 to accumulate based on CumlRnk
df_tmp = df_portfolio_features.sort_values(by = 'CumlRnk', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
45,ITC,-1.44,-23.50,55.62,19.06,144747.0,-79923.0,260243.0,452.00,-57.95,33.0,X-LC,19.30,1.0,-0.55,2.08,0.00,X40,NTT,FMCG
73,TCS,-0.70,-30.34,81.69,26.57,263637.0,-140545.0,322728.0,4311.59,-41.00,29.0,X-LC,18.17,2.0,-0.53,2.57,0.72,X40,ATH,IT
43,INFY,-0.84,-14.29,56.63,34.24,151863.0,-44721.0,268167.0,1972.00,-32.51,38.0,X-LC,15.06,3.0,-0.29,2.14,3.13,X40,NTT,IT
75,TMPV,-1.25,-31.85,100.40,36.58,243484.0,-113327.0,242514.0,600.00,-85.81,33.0,X-LC,9.61,4.0,-0.47,1.93,0.00,XY24,NTT,AUTO
33,HCLTECH,-0.69,-12.07,40.83,23.83,86860.0,-29189.0,212735.0,1908.19,-7.78,42.0,X-LC,11.58,8.0,-0.34,1.70,3.29,X40,ATH,IT

In [22]:
# top 5 for average up
df_tmp = df_portfolio_features[(df_portfolio_features['Dev%_200'] > 5)].sort_values(by = 'CurrAlloc%', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
1,ABB,-1.63,10.18,32.11,45.57,92562.0,26645.0,288264.0,7934.0,-29.24,48.0,H-MC,13.26,125.0,0.29,2.3,28.01,AR,NTT,ELECTRICAL

In [23]:
# top 5 RSP
df_tmp = df_portfolio_features.sort_values(by = 'RSP', ascending=False)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
30,HAPPSTMNDS,-4.53,-53.64,298.74,84.85,177499.0,-68749.0,59416.0,1480.71,-44.95,45.0,H-SC,25.32,152.0,-0.39,0.47,10.03,AR,ATH,IT
24,DMART,0.99,-5.25,36.78,29.60,86985.0,-13098.0,236502.0,5391.45,-20.14,57.0,X-LC,6.79,14.0,-0.15,1.89,8.10,X40N,ATH,FMCG
5,ANGELONE,-2.04,-5.54,31.46,24.18,90636.0,-16900.0,288100.0,303.00,-86.38,49.0,X-SC,10.40,97.0,-0.19,2.30,10.89,X40N,NTT,FINANCE
52,PAGEIND,-0.57,-17.51,62.59,34.11,138559.0,-47004.0,221375.0,51418.65,-40.84,47.0,X-MC,20.99,55.0,-0.34,1.77,4.72,X40,ATH,APPARELS
1,ABB,-1.63,10.18,32.11,45.57,92562.0,26645.0,288264.0,7934.00,-29.24,48.0,H-MC,13.26,125.0,0.29,2.30,28.01,AR,NTT,ELECTRICAL

In [24]:
# Top N allocation
df_tmp = df_portfolio_features.sort_values(by = 'CurrAlloc%', ascending=False)
top_n_values = [10, 25, 50]

sum_df = pd.DataFrame({
    'Top_N': top_n_values,
    'Sum_Alloc%': [df_tmp['CurrAlloc%'].head(n).sum() for n in top_n_values]
})

sum_df

   Top_N  Sum_Alloc%
0     10       21.13
1     25       46.45
2     50       78.68

In [25]:
# market-cap-wise allocation
df_tmp = df_portfolio_features[cols]
df_tmp.groupby(df_tmp['Conviction'].str[-2:])['CurrAlloc%'].sum().sort_values(ascending=False)

Conviction
SC    43.91
MC    30.15
LC    25.95
Name: CurrAlloc%, dtype: float64

In [26]:
# criteria-wise allocation
df_portfolio_features.groupby('Criteria')['CurrAlloc%'].sum().sort_values(ascending=False)

Criteria
XY24     26.96
X40      25.71
X40N     15.31
AR        9.15
XR        8.19
XY25      7.35
OX40N     6.57
SR        0.77
Name: CurrAlloc%, dtype: float64

In [27]:
# conviction-wise allocation
df_portfolio_features.groupby('Conviction')['CurrAlloc%'].sum().sort_values(ascending=False)

Conviction
X-LC    23.72
X-MC    22.60
H-SC    21.42
X-SC    12.27
M-SC     9.72
H-MC     5.16
M-MC     2.04
H-LC     1.18
M-LC     1.05
L-SC     0.50
L-MC     0.35
Name: CurrAlloc%, dtype: float64

In [28]:
# sector-wise stats
df_tmp = df_portfolio_features.groupby('Category')[['CurrAlloc%', 'Current', 'Current P/L', 'FTT Amt']].sum().sort_values(by=['Current', 'Current P/L'], ascending=False)
df_tmp['Current P/L%'] = round(df_tmp['Current P/L'] * 100 / df_tmp['Current'], 2)
df_tmp['FTT%'] = round(df_tmp['FTT Amt'] * 100 / df_tmp['Current'], 2)
cols = ['CurrAlloc%', 'Current P/L%', 'FTT%']
df_tmp[cols].sort_values(by=['CurrAlloc%'], ascending=False)

               CurrAlloc%  Current P/L%    FTT%
Category
FMCG                15.30        -30.26   76.51
FINANCE             13.08        -31.01   84.40
IT                  12.02        -49.45  125.51
MISC                 6.91        -54.72  121.92
ELECTRICAL           6.53        -18.27   63.56
PAINTS               5.23        -50.25   76.34
INSURANCE            4.75        -13.93   52.91
BANKS                4.52        -36.18  105.31
PHARMA               4.23        -10.68   45.52
AUTO                 3.67        -42.04   98.40
AC                   2.00        -27.39   61.93
HEALTHCARE           1.90        -50.60   89.90
APPARELS             1.77        -21.23   62.59
TRAVEL               1.77       -102.07  203.25
DURABLES             1.75        -75.86  118.65
FOOTWEAR             1.75       -101.10  181.73
BREWERIES            1.69        -10.70   33.69
REALTY               1.46        -21.06   40.94
REFINERIES           1.38        -15.78   45.08
CERAMICS             1.36        -80.59  135.46
CEMENT               1.22        -75.99  207.66
CABLES               1.18          0.03  107.86
ENGINEERING          1.06        -81.41  164.39
CHEMICALS            1.00       -110.87  282.91
JEWELLERY            0.97       -162.37  253.53
ENTERTAINMENT        0.73       -110.19  235.55
TEXTILES             0.45        -62.89  109.33
HOTELS               0.33       -177.65  275.59

In [29]:
# money to be made criteria-wise
df_portfolio_features.groupby('Criteria')['FTT Amt'].agg(['sum', 'count']).sort_values(by='sum', ascending=False)

                sum  count
Criteria
XY24      4215247.0     21
X40       1953568.0     16
XR        1464234.0     12
AR        1424504.0     10
X40N      1381715.0     10
OX40N      969264.0     10
XY25       517426.0      5
SR         322669.0      2

In [30]:
# money to be made conviction-wise
df_portfolio_features.groupby('Conviction')['FTT Amt'].agg(['sum', 'count']).sort_values(by='sum', ascending=False)

                  sum  count
Conviction
H-SC        4104568.0     24
X-MC        1899446.0     15
X-LC        1804052.0     13
M-SC        1698765.0     14
X-SC        1646010.0     10
H-MC         432015.0      3
L-SC         228676.0      2
M-LC         160249.0      1
M-MC         129964.0      2
H-LC          85619.0      1
L-MC          59263.0      1

In [31]:
# money to be made criteria and conviction-wise
df_portfolio_features.groupby(['Conviction', 'Criteria'])['FTT Amt'].agg(['sum', 'count']).sort_values(by='sum', ascending=False)

                           sum  count
Conviction Criteria
H-SC       XY24      1413942.0      6
           AR        1019556.0      5
M-SC       XY24       979345.0      6
X-LC       X40        967885.0      7
H-SC       XR         934152.0      7
X-SC       XY24       881738.0      4
X-MC       X40        753323.0      7
           X40N       581142.0      4
X-SC       X40N       531912.0      4
M-SC       OX40N      439044.0      5
H-SC       OX40N      414249.0      4
X-LC       XY24       402573.0      2
H-SC       SR         322669.0      2
X-MC       XY24       286869.0      2
           XY25       278112.0      2
X-LC       X40N       268661.0      2
H-MC       XY24       250780.0      1
X-SC       X40        232360.0      2
M-SC       XR         197865.0      2
H-MC       AR         181235.0      2
X-LC       XY25       164933.0      2
M-LC       XR         160249.0      1
L-SC       OX40N      115971.0      1
           XR         112705.0      1
H-LC       AR          85619.0      1
M-SC       AR          82511.0      1
M-MC       XY25        74381.0      1
L-MC       XR          59263.0      1
M-MC       AR          55583.0      1

In [32]:
# notebook execution time

end_time = time.time()
execution_time = round(end_time - start_time, 0)
print(f"Notebook execution time: {execution_time} seconds")

Notebook execution time: 37.0 seconds