<a href="https://colab.research.google.com/github/ankit-rathi/Quantvesting_v2/blob/main/myStocks_Portfolio_Analysis.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
'''
!pip install pandas==2.2.2 -qq
!pip install pyxirr -qq
!pip install ta -qq
!pip install yfinance==0.2.59 -qq
'''

'\n!pip install pandas==2.2.2 -qq\n!pip install pyxirr -qq\n!pip install ta -qq\n!pip install yfinance==0.2.59 -qq\n'

In [2]:
# import libraries

import numpy as np
import pandas as pd
import datetime
import warnings
warnings.filterwarnings('ignore')
import yfinance as yfin
import ta
import matplotlib.pyplot as plt
import requests

In [3]:
# notebook start time
import time
import datetime
import pytz

start_time = time.time()

# function to print date timestamp
def print_date_time():
  tz_NY = pytz.timezone('Asia/Kolkata')
  datetime_NY = datetime.datetime.now(tz_NY)
  print("Run date time (IST):", datetime_NY.strftime("%Y-%m-%d %H:%M:%S"))

In [4]:
# function to get booked and reserved amount
def get_amt():
  # fetch the JSON data from the URL
  url = "https://raw.githubusercontent.com/ankit-rathi/Tradevesting_v1/main/data/myPortfolioAmts.json"
  response = requests.get(url)
  pf_amts = response.json()  # parse the JSON data

  # extract values from the JSON
  py_booked_amt_dm = pf_amts["py_booked_amt_dm"]
  py_booked_amt_sv = pf_amts["py_booked_amt_sv"]
  cy_booked_amt_dm = pf_amts["cy_booked_amt_dm"]
  cy_booked_amt_sv = pf_amts["cy_booked_amt_sv"]
  reserve_amt_dm = pf_amts["reserve_amt_dm"]
  reserve_amt_sv = pf_amts["reserve_amt_sv"]

  # perform calculations
  py_booked_amt = py_booked_amt_dm + py_booked_amt_sv
  cy_booked_amt = cy_booked_amt_dm + cy_booked_amt_sv
  reserve_amt = reserve_amt_dm + reserve_amt_sv
  total_booked_amt = py_booked_amt + cy_booked_amt

  return total_booked_amt, reserve_amt, cy_booked_amt, py_booked_amt

gen_output = 0

In [5]:
# function to format the amount
def format_amt(number):
    abs_number = abs(number)

    if abs_number >= 1_00_00_000:  # Crores
        formatted_amt = f"{number / 1_00_00_000:.2f} C"
    elif abs_number >= 1_00_000:  # Lakhs
        formatted_amt = f"{number / 1_00_000:.2f} L"
    elif abs_number >= 1_000:  # Thousands
        formatted_amt = f"{number / 1_000:.2f} K"
    else:
        formatted_amt = f"{number:.2f}"

    return formatted_amt

# function to set start and end date
def get_start_end_date():
  start_date = (datetime.date.today() + datetime.timedelta(days=-365)).strftime('%Y-%m-%d')
  end_date = (datetime.date.today() + datetime.timedelta(days=1)).strftime('%Y-%m-%d')
  return start_date, end_date

# function to fetch my portfolio csv
def get_mypfs_df():
  mypfs_df = pd.read_csv('https://raw.githubusercontent.com/ankit-rathi/Tradevesting_v1/main/data/myPortfolioStocks.csv')
  return mypfs_df

# function to fetch my prospects csv
def get_mypps_df():
  mypps_df = pd.read_csv('https://raw.githubusercontent.com/ankit-rathi/Tradevesting_v1/main/data/myProspectsScrips.csv')
  return mypps_df

# function to fetch screener data
def get_myscreen_df():
  myscreen_df = pd.read_csv('https://raw.githubusercontent.com/ankit-rathi/Tradevesting_v1/main/data/myScreenerDB.csv')
  return myscreen_df

# function to fetch momentum data
def get_myinvmt_df():
  myinvmt_df = pd.read_csv('https://raw.githubusercontent.com/ankit-rathi/Tradevesting_v1/main/data/myInvestments.csv')
  return myinvmt_df

# function to get the stock ids
def get_stock_ids(df_pf):
  stock_n100 = df_pf['Symbol'].unique()

  exclude = ['CADILAHC','MMTC', 'MASFIN']

  stock_ids = df_pf[~df_pf['Symbol'].isin(exclude) ]['Symbol'].unique()

  #mypf = mypf[mypf.Forecast.notnull()]
  #stock_ids = mypf['Symbol'].unique()

  #stock_ids.sort()
  return stock_ids

# get features from screener data
def get_screener_features():
  myscreen_df = get_myscreen_df()
  cols = ['Symbol', 'EPS', 'MedPE', 'ROCE%', 'ROE%', 'CapType']
  return myscreen_df[cols]

# get relative strength
def get_relative_strength(stock_list):

    # Dictionary to store stock tickers and their corresponding percentage price change
    stock_changes = {}

    # Loop through each stock and fetch its price data
    for stock in stock_list:
        try:
            # Download the stock data for the given date range
            stock_data = yfin.Ticker(stock + '.NS').history(period='1mo', interval='1d')[map(str.title, ['open', 'close', 'low', 'high', 'volume'])]

            # Calculate the percentage change for the stock
            if len(stock_data) > 0:
                start_price = stock_data['Close'].iloc[0]
                end_price = stock_data['Close'].iloc[-1]
                percent_change = round(((end_price - start_price) / start_price) * 100, 2)
                stock_changes[stock] = percent_change
            else:
                stock_changes[stock] = np.nan  # If no data is available, set to NaN

        except Exception as e:
            print(f"Error fetching data for {stock}: {e}")
            stock_changes[stock] = np.nan

    # Create a DataFrame with stock tickers and their percentage changes
    df = pd.DataFrame(list(stock_changes.items()), columns=['Symbol', 'Percent_Change'])

    # Drop any stocks with missing data (NaN values)
    df = df.dropna()

    # Calculate the percentile rank based on percentage change
    df['RSP'] = round(df['Percent_Change'].rank(pct=True) * 100, 2)
    cols = ['Symbol', 'RSP']
    df = df[cols]
    # Sort by percentile rank (optional)
    df = df.sort_values(by='RSP', ascending=False).reset_index(drop=True)

    return df

In [6]:
# function to get stock technicals
def stock_prec_dev(stock_symbol):
    #stock_symbol = 'ULTRACEMCO.NS'
    short_window = 20
    mid_window = 50
    long_window = 200
    moving_avg = 'SMA'

    start = datetime.datetime(*map(int, start_date.split('-')))
    end = datetime.datetime(*map(int, end_date.split('-')))

    stock_df = yfin.Ticker(stock_symbol + '.NS').history(period='max', interval='1d')[map(str.title, ['open', 'close', 'low', 'high', 'volume'])]

    stock_df['Max'] = round(max(stock_df['Close']),2)
    stock_df = stock_df[(stock_df.index <= end_date) & (stock_df.index >= start_date)]
    stock_df['200_SMA'] = round(stock_df['Close'].rolling(window = 200, min_periods = 1).mean(),0)
    stock_df['Dev%_200'] = round((stock_df['Close'] - stock_df['200_SMA'])*100/stock_df['200_SMA'],2)
    stock_df.dropna(axis = 0, inplace = True) # remove any null rows

    stock_df['20_SMA'] = stock_df['Close'].rolling(window=20).mean()
    stock_df['50_SMA'] = stock_df['Close'].rolling(window=50).mean()
    stock_df['Symbol'] = stock_symbol

    stock_df['Close'] = round(stock_df['Close'],2)
    stock_df['Min'] = round(min(stock_df['Close']),2)
    stock_df['RSI_14'] = ta.momentum.RSIIndicator(close=stock_df['Close'], window=14).rsi()
    stock_df['RSI_14'] = round(stock_df['RSI_14'],0)
    stock_df['Prev_Close'] = stock_df['Close'].shift(1)
    stock_df.drop(['Open', 'Low', 'High', 'Volume'], axis=1, inplace=True)
    stock_df = stock_df.tail(1)

    max_SMA = max(stock_df['20_SMA'].item(), stock_df['50_SMA'].item(), stock_df['200_SMA'].item())
    min_SMA = min(stock_df['20_SMA'].item(), stock_df['50_SMA'].item(), stock_df['200_SMA'].item())
    ABS_Spread = max_SMA - min_SMA
    stock_df['Spread%'] = round((ABS_Spread / stock_df['200_SMA'].item()) * 100,2)

    return stock_df

# function to compute stock attributes
def get_common_features(stock_ids, df_mypf):

  df_prec_dev = pd.DataFrame()
  df_tmp = get_screener_features()
  df_rs = get_relative_strength(stock_ids)

  for stock_id in stock_ids:
      tmp = stock_prec_dev(stock_id)
      tmp = tmp.reset_index()
      df_prec_dev = pd.concat([df_prec_dev, tmp], ignore_index = True)
  df_prec_dev = pd.merge(df_prec_dev, df_mypf, on= 'Symbol')
  df_prec_dev = pd.merge(df_prec_dev, df_tmp, on= 'Symbol', how='left')
  df_prec_dev = pd.merge(df_prec_dev, df_rs, on= 'Symbol', how='left')
  #print(df_prec_dev.columns)
  df_prec_dev['Curr_PE'] = round(df_prec_dev['Close']/df_prec_dev['EPS'],1)
  df_prec_dev['Dev%_PE'] = round((df_prec_dev['Curr_PE'] - df_prec_dev['MedPE'])*100/df_prec_dev['MedPE'],2)
  df_prec_dev['Conviction'] = df_prec_dev['Conviction'] + '-' + df_prec_dev['CapType']
  return df_prec_dev

# function to arrange stock features
def arrange_features(df_stocks, common_cols, diff_cols):
  df_stocks_common = df_stocks[common_cols].drop_duplicates()
  df_stocks_diff = df_stocks[diff_cols]
  df_stocks_diff['Investment'] = df_stocks_diff['AvgCost'] * df_stocks_diff['Shares']
  df_stocks_diff = df_stocks_diff.groupby(['Symbol'])[['Shares', 'Investment']].aggregate(['sum']).reset_index()
  df_stocks_diff.columns = ['Symbol', 'Shares', 'Investment']
  df_stocks_diff['AvgCost'] = round(df_stocks_diff['Investment']/df_stocks_diff['Shares'],2)
  df_stocks = pd.merge(df_stocks_diff, df_stocks_common, on='Symbol')
  return df_stocks

# plot fact distribution across dimension
def plot_pie_chart(df, dimension, fact):
  # grouping the data by category and calculating the sum of fact for each type
  grouped_data = df.groupby(dimension)[fact].sum()

  # sorting the grouped data in descending order
  grouped_data = grouped_data.sort_values(ascending=False)

  # creating a pie chart
  grouped_data.plot.pie(autopct='%1.1f%%', startangle=90, figsize=(6, 6))

  # adding a title and displaying the plot
  plt.title(f'{dimension} {fact} Distribution')
  plt.ylabel('')  # To hide the y-label
  plt.show()

In [7]:
# function to get portfolio features

def get_portfolio_features(df_common_features):

  print_date_time()
  print('-------------------')

  #df_common_features["Target"] = df_common_features["Target"].fillna(df_common_features["Max"])
  df_common_features['NTT'] = np.where(df_common_features['Strategy']== 'NTT', df_common_features["Target"], df_common_features['Max'])
  df_common_features['LTT'] = np.where(df_common_features['Strategy']== 'BTT', df_common_features["Target"], df_common_features['Max'])
  df_common_features['BOL'] = df_common_features['Min']

  tmp_df = df_common_features[df_common_features['Symbol'].isin(mypf_df[mypf_df['InPortfolio'] != 'NA'].Symbol.values)]
  print('qualified stocks: '+str(len(tmp_df['Symbol'].unique())))
  tmp_df1 = tmp_df[tmp_df['LatestQtr'] == 1]
  print('with latest results: '+str(len(tmp_df1['Symbol'].unique())))
  tmp_df1 = tmp_df1[tmp_df1['StarStock'] == 1]
  print('still star stocks: '+str(len(tmp_df1['Symbol'].unique())))
  tmp_df['Investment'] = tmp_df['AvgCost'] * tmp_df['Shares']
  tmp_df['Current'] = round(tmp_df['Close'] * tmp_df['Shares'],0)
  tmp_df['Previous'] = tmp_df['Prev_Close'] * tmp_df['Shares']
  tmp_df['EstimatedST'] = tmp_df['NTT'] * tmp_df['Shares']
  tmp_df['EstimatedLT'] = tmp_df['LTT'] * tmp_df['Shares']
  tmp_df['Current P/L'] = round((tmp_df['Current'] - tmp_df['Investment']),0)
  tmp_df['Today P/L%'] = round((tmp_df['Current'] - tmp_df['Previous'])*100/tmp_df['Previous'],2)
  tmp_df['Current P/L%'] = round((tmp_df['Current'] - tmp_df['Investment'])*100/tmp_df['Investment'],2)
  tmp_df['EstimatedST P/L%'] = round((tmp_df['EstimatedST'] - tmp_df['Investment'])*100/tmp_df['Investment'],2)
  tmp_df['EstimatedLT P/L%'] = round((tmp_df['EstimatedLT'] - tmp_df['Investment'])*100/tmp_df['Investment'],2)
  tmp_df['NTT%'] = round((tmp_df['NTT'] - tmp_df['Close'])*100/tmp_df['Close'],2)
  tmp_df['LTT%'] = round((tmp_df['LTT'] - tmp_df['Close'])*100/tmp_df['Close'],2)
  tmp_df['Gained%'] = round((tmp_df['Close'] - tmp_df['BOL'])*100/tmp_df['BOL'],2)
  investment = round(sum(tmp_df['AvgCost']*tmp_df['Shares']),0)
  current = round(sum(tmp_df['Close']*tmp_df['Shares']),0)
  tmp_df['InitAlloc%'] = round(tmp_df['Investment']*100/investment,2)
  tmp_df['CurrAlloc%'] = round(tmp_df['Current']*100/current,2)
  tmp_df['FTT'] = tmp_df['LTT']
  tmp_df.loc[tmp_df['Strategy'] == 'NTT', 'FTT'] = tmp_df['NTT']
  tmp_df['FTT%'] = tmp_df['LTT%']
  tmp_df.loc[tmp_df['Strategy'] == 'NTT', 'FTT%'] = tmp_df['NTT%']
  tmp_df['FTT Amt'] = round(tmp_df['FTT%'] * tmp_df['Current']/100,0)
  tmp_df['OTT%'] = round((tmp_df['FTT'] - tmp_df['AvgCost'])*100/tmp_df['AvgCost'],2)
  tmp_df['RRR Ind'] = round(tmp_df['Current P/L']/tmp_df['FTT Amt'],2)
  tmp_df['Risk Ind'] = round(tmp_df['Current P/L%']*tmp_df['CurrAlloc%'],0)

  return tmp_df

# function to print portfolio features
def print_portfolio_stats(df_portfolio_features, myinvmt_df):
  from pyxirr import xirr

  total_booked_amt, reserve_amt, cy_booked_amt, py_booked_amt = get_amt()

  dates = myinvmt_df['Date'].values
  dates = np.append(dates, datetime.date.today().strftime('%d-%b-%y'))
  investment = myinvmt_df['Investment'].values
  dates= pd.to_datetime(dates)

  current = round(sum(df_portfolio_features['Close']*df_portfolio_features['Shares']),0) + reserve_amt
  investment_xirr = np.append(investment, current)
  cagr = round(xirr(pd.DataFrame({"dates": dates, "amounts": investment_xirr}))*100,2)

  investment = -sum(investment)
  invested = round(sum(df_portfolio_features['AvgCost']*df_portfolio_features['Shares']),0) + reserve_amt
  previous = round(sum(df_portfolio_features['Prev_Close']*df_portfolio_features['Shares']),0) + reserve_amt
  cy_invested = investment + py_booked_amt

  today_pnl_amount = current-previous
  today_pnl_percentage = round((current-previous)*100/previous,2)

  curr_pnl_amount = current-invested
  curr_pnl_percentage = round((curr_pnl_amount)*100/(cy_invested),2)

  cy_pnl_amount = cy_booked_amt + curr_pnl_amount
  cy_pnl_percentage = round((cy_pnl_amount)*100/cy_invested,2)

  overall_pnl_amount = total_booked_amt + curr_pnl_amount
  overall_pnl_percentage = round((overall_pnl_amount)*100/investment,2)

  estimate_st = round(sum(df_portfolio_features['FTT']*df_portfolio_features['Shares']),0)  + reserve_amt
  est_st_pnl_amount = estimate_st-current
  est_st_pnl_percentage = round((est_st_pnl_amount)*100/current,2)

  estimate_lt = round(sum(df_portfolio_features['LTT']*df_portfolio_features['Shares']),0)  + reserve_amt
  est_lt_pnl_amount = estimate_lt-current
  est_lt_pnl_percentage = round((est_lt_pnl_amount)*100/current,2)

  total_profit = round(sum(df_portfolio_features[df_portfolio_features['Current P/L%'] > 0]['Current']) - sum(df_portfolio_features[df_portfolio_features['Current P/L%'] > 0]['Investment']),0)
  total_loss = round(sum(df_portfolio_features[df_portfolio_features['Current P/L%'] < 0]['Current']) - sum(df_portfolio_features[df_portfolio_features['Current P/L%'] < 0]['Investment']),0)

  cy_booked_percentage = round((cy_booked_amt)*100/current,2)
  py_booked_percentage = round((py_booked_amt)*100/investment,2)
  total_booked_percentage = round((total_booked_amt)*100/investment,2)

  print('-------------------')
  print('Initial Investment: ', format_amt(investment))
  print('CY Investment: ', format_amt(cy_invested))
  print('Reserve: ', format_amt(reserve_amt))
  print('Current: ',  format_amt(current))
  print('-------------------')
  print('Today PnL: '+ '{} ({}%)'.format(format_amt(today_pnl_amount), today_pnl_percentage))
  print('Current PnL: '+ '{} ({}%)'.format(format_amt(curr_pnl_amount), curr_pnl_percentage))
  print('CY Booked + Current PnL: '+ '{} ({}%)'.format(format_amt(cy_pnl_amount), cy_pnl_percentage))
  print('-------------------')
  print('Total profit: ', format_amt(total_profit))
  print('Total loss: ', format_amt(total_loss))
  print('-------------------')
  print('Total Booked + Current PnL: '+ '{} ({}%)'.format(format_amt(overall_pnl_amount), overall_pnl_percentage))
  print('Total Booked PnL: '+ '{} ({}%)'.format(format_amt(total_booked_amt), total_booked_percentage))
  print('Curr Year Booked PnL: '+ '{} ({}%)'.format(format_amt(cy_booked_amt), cy_booked_percentage))
  print('Prev Year Booked PnL: '+ '{} ({}%)'.format(format_amt(py_booked_amt), py_booked_percentage))
  print('===================')
  print('Est FTT: ',  format_amt(estimate_st))
  print('Est FTT PnL: '+ '{} ({}%)'.format(format_amt(est_st_pnl_amount), est_st_pnl_percentage))

  print('===================')
  print('Deployed: ', format_amt(investment))

  print('Current: ', format_amt(current))

  print('CAGR/XIRR %: '+'{}%'.format(cagr))

In [8]:
# get start and end date
start_date, end_date = get_start_end_date()

# get portfolio and prospects data
mypfs_df = get_mypfs_df()
mypps_df = get_mypps_df()
myinvmt_df = get_myinvmt_df()

# merge above datasets
mypf_df = pd.merge(mypfs_df, mypps_df, on="Symbol")

# seggregate dm and sv portfolio
dm_pf = mypf_df[mypf_df['InPortfolio'] == 'DM']
sv_pf = mypf_df[mypf_df['InPortfolio'] == 'SV']

# build portfolio stock dataframe
dm_stocks = get_stock_ids(dm_pf)
sv_stocks = get_stock_ids(sv_pf)
df_stocks = pd.concat([dm_pf,sv_pf], ignore_index = True)

# arrange common and diff stock features
common_cols = ['Symbol', 'Target', 'Criteria', 'Strategy', 'CumlRnk', 'LatestQtr', 'StarStock', 'Conviction', 'Category', 'InFolio', 'XIRR', 'MBQ']
diff_cols = ['Symbol', 'AvgCost', 'Shares']
df_stocks = arrange_features(df_stocks, common_cols, diff_cols)

# get common features
stock_ids = df_stocks['Symbol'].values
df_common_features = get_common_features(stock_ids, df_stocks)

df_common_features.reset_index(drop=True, inplace=True)
df_common_features.drop(['Date'], axis=1, inplace=True)
# get and print portfolio features
df_portfolio_features = get_portfolio_features(df_common_features)

print_portfolio_stats(df_portfolio_features, myinvmt_df)

df = df_portfolio_features
#plot_pie_chart(df, 'CapType', 'Current')
list_ox40n = list(df[df['MBQ'].str.contains('OX40N', na=False)]['Symbol'].values)

Run date time (IST): 2026-04-30 11:00:29
-------------------
qualified stocks: 92
with latest results: 31
still star stocks: 20

-------------------
Initial Investment:  1.40 C
CY Investment:  1.82 C
Reserve:  1.49 K
Current:  1.47 C
-------------------
Today PnL: -2.31 L (-1.55%)
Current PnL: -36.15 L (-19.82%)
CY Booked + Current PnL: -34.07 L (-18.68%)
-------------------
Total profit:  1.19 L
Total loss:  -37.35 L
-------------------
Total Booked + Current PnL: 8.80 L (6.3%)
Total Booked PnL: 44.95 L (32.22%)
Curr Year Booked PnL: 2.08 L (1.41%)
Prev Year Booked PnL: 42.87 L (30.73%)
===================
Est FTT:  2.55 C
Est FTT PnL: 1.08 C (73.74%)
===================
Deployed:  1.40 C
Current:  1.47 C
CAGR/XIRR %: 2.61%

In [9]:
# top 5 near their targets
cols = ['Symbol', 'Today P/L%', 'Current P/L%', 'FTT%', 'OTT%', 'FTT Amt', 'Current P/L', 'Current', 'FTT', 'Dev%_PE', 'RSI_14','Conviction', 'Spread%',  'CumlRnk', 'RRR Ind', 'CurrAlloc%', 'Gained%', 'Criteria', 'Strategy', 'Category']
df_tmp = df_portfolio_features[~df_portfolio_features['Symbol'].isin(['ENRIN','BLUSPRING','DIGITIDE'])]
df_tmp = df_tmp.sort_values(by = 'FTT Amt', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
55,MASFIN,3.76,3.54,17.42,21.57,17672.0,3465.0,101445.0,397.04,-10.57,68.0,H-SC,0.56,167.0,0.20,0.69,31.09,XR,ATH,FINANCE
51,KOTAKBANK,-0.13,1.94,18.80,21.11,26537.0,2682.0,141155.0,453.24,-12.44,53.0,X-LC,8.79,12.0,0.10,0.96,7.95,X40,ATH,BANKS
59,PIDILITIND,-1.87,-3.41,22.54,18.37,30722.0,-4810.0,136300.0,1670.26,-32.34,48.0,X-LC,7.29,5.0,-0.16,0.93,7.02,X40,ATH,CHEMICALS
53,M&M,-3.19,-0.98,24.60,23.38,33782.0,-1355.0,137326.0,3802.40,-16.17,44.0,X-LC,8.75,25.0,-0.04,0.93,5.45,X40N,ATH,AUTO
83,TTKPRESTIG,-3.03,-34.91,53.78,0.09,35275.0,-35185.0,65592.0,770.00,52.19,52.0,M-SC,18.70,250.0,-1.00,0.45,16.79,OX40N,NTT,DURABLES

In [10]:
# top 5 today
df_tmp = df_portfolio_features.sort_values(by = 'Today P/L%', ascending=False)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
55,MASFIN,3.76,3.54,17.42,21.57,17672.0,3465.0,101445.0,397.04,-10.57,68.0,H-SC,0.56,167.0,0.20,0.69,31.09,XR,ATH,FINANCE
29,GREENPANEL,0.97,-40.22,139.43,43.14,152605.0,-73629.0,109449.0,537.00,144.83,66.0,M-SC,18.80,225.0,-0.48,0.74,31.47,XY24,NTT,MISC
11,BERGEPAINT,0.51,-14.09,45.88,25.32,101588.0,-36328.0,221421.0,680.00,-18.71,57.0,X-MC,13.74,68.0,-0.36,1.51,15.24,XY24,NTT,PAINTS
71,SIEMENS,0.16,1.64,23.49,25.51,44431.0,3055.0,189150.0,4671.50,58.78,67.0,H-LC,10.60,51.0,0.07,1.29,33.27,AR,ATH,ELECTRICAL
70,SHALBY,0.15,-38.21,102.48,25.10,114696.0,-69223.0,111920.0,327.00,722.97,57.0,M-SC,22.89,236.0,-0.60,0.76,27.37,XY24,NTT,HEALTHCARE

In [11]:
# bottom 5 today
df_tmp = df_portfolio_features.sort_values(by = 'Today P/L%', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
61,RAJESHEXPO,-4.71,-77.01,335.26,0.07,105734.0,-105639.0,31538.0,518.0,1055.30,51.0,L-SC,32.94,268.0,-1.00,0.21,48.06,OX40N,NTT,JEWELLERY
15,CAMS,-3.55,-3.88,29.50,24.48,71416.0,-9768.0,242088.0,950.0,-7.82,55.0,X-SC,6.70,89.0,-0.14,1.65,17.86,X40N,NTT,MISC
80,TITAGARH,-3.48,-28.55,103.98,45.74,179916.0,-69148.0,173029.0,1548.0,-4.90,59.0,H-SC,14.86,175.0,-0.38,1.18,32.02,XY24,NTT,ENGINEERING
88,VOLTAS,-3.47,11.37,30.37,45.20,64852.0,21798.0,213540.0,1856.0,27.51,51.0,X-MC,2.86,79.0,0.34,1.45,18.94,XY25,NTT,AC
43,INDIGOPNTS,-3.33,-39.81,66.17,0.02,69525.0,-69488.0,105071.0,1408.0,60.16,52.0,M-SC,22.38,222.0,-1.00,0.71,19.21,OX40N,NTT,PAINTS

In [12]:
# top 5 to exit based on CumlRnk
df_tmp = df_portfolio_features[~df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])]
df_tmp = df_tmp[(df_tmp['Current P/L%'] > -1) & (df_tmp['Current P/L%'] < 1)].sort_values(by = 'CumlRnk', ascending=False)
df_tmp[cols].head()

Empty DataFrame
Columns: [Symbol, Today P/L%, Current P/L%, FTT%, OTT%, FTT Amt, Current P/L, Current, FTT, Dev%_PE, RSI_14, Conviction, Spread%, CumlRnk, RRR Ind, CurrAlloc%, Gained%, Criteria, Strategy, Category]
Index: []

In [13]:
# OX40N stocks to exit
df_tmp = df_portfolio_features[(df_portfolio_features['Symbol'].isin(list_ox40n))].sort_values(by = 'Current P/L%', ascending=False)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
25,FINCABLES,-1.37,25.33,65.89,107.91,121927.0,37402.0,185046.0,1641.55,12.63,68.0,M-SC,10.32,220.0,0.31,1.26,39.22,OX40N,ATH,CABLES
72,SIS,-0.85,-16.46,45.15,21.26,41879.0,-18276.0,92756.0,528.00,2198.45,77.0,H-SC,8.04,168.0,-0.44,0.63,37.91,OX40N,NTT,MISC
16,CERA,-1.05,-31.20,80.08,23.89,96910.0,-54886.0,121017.0,9475.00,-33.65,57.0,H-SC,12.32,153.0,-0.57,0.82,16.30,OX40N,NTT,CERAMICS
50,KANSAINER,-1.37,-34.91,74.34,13.47,130480.0,-94149.0,175518.0,340.00,-44.14,52.0,H-SC,16.52,162.0,-0.72,1.19,22.60,XY24,NTT,PAINTS
83,TTKPRESTIG,-3.03,-34.91,53.78,0.09,35275.0,-35185.0,65592.0,770.00,52.19,52.0,M-SC,18.70,250.0,-1.00,0.45,16.79,OX40N,NTT,DURABLES

In [14]:
# top 5 to book for rotation
df_tmp = df_portfolio_features[(df_portfolio_features['Current P/L%'] > 20) ].sort_values(by = 'CumlRnk', ascending=False)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
25,FINCABLES,-1.37,25.33,65.89,107.91,121927.0,37402.0,185046.0,1641.55,12.63,68.0,M-SC,10.32,220.0,0.31,1.26,39.22,OX40N,ATH,CABLES

In [15]:
# top 5 to monitor for exit
df_tmp = df_portfolio_features[~df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])]
df_tmp = df_tmp[(df_tmp['Current P/L%'] > 0) ].sort_values(by = 'Dev%_PE', ascending=False)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
74,STARHEALTH,-1.55,1.59,44.95,47.26,128377.0,4477.0,285600.0,761.00,60.41,70.0,H-SC,6.51,173.0,0.03,1.94,47.91,XY24,NTT,INSURANCE
25,FINCABLES,-1.37,25.33,65.89,107.91,121927.0,37402.0,185046.0,1641.55,12.63,68.0,M-SC,10.32,220.0,0.31,1.26,39.22,OX40N,ATH,CABLES
55,MASFIN,3.76,3.54,17.42,21.57,17672.0,3465.0,101445.0,397.04,-10.57,68.0,H-SC,0.56,167.0,0.20,0.69,31.09,XR,ATH,FINANCE
73,SONACOMS,-1.33,2.36,35.88,39.09,37153.0,2389.0,103548.0,804.02,-18.85,62.0,M-MC,16.19,193.0,0.06,0.70,46.48,AR,ATH,AUTO

In [16]:
# top 5 to book for rotation from weak conviction
df_tmp = df_portfolio_features[~df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])]
df_tmp = df_tmp[~df_tmp['Criteria'].isin(['XY25','XY24','X40', 'X40N'])].sort_values(by = 'RRR Ind', ascending=False)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
25,FINCABLES,-1.37,25.33,65.89,107.91,121927.0,37402.0,185046.0,1641.55,12.63,68.0,M-SC,10.32,220.0,0.31,1.26,39.22,OX40N,ATH,CABLES
55,MASFIN,3.76,3.54,17.42,21.57,17672.0,3465.0,101445.0,397.04,-10.57,68.0,H-SC,0.56,167.0,0.20,0.69,31.09,XR,ATH,FINANCE
73,SONACOMS,-1.33,2.36,35.88,39.09,37153.0,2389.0,103548.0,804.02,-18.85,62.0,M-MC,16.19,193.0,0.06,0.70,46.48,AR,ATH,AUTO
42,INDIAMART,-0.38,-8.78,126.63,106.72,142463.0,-10833.0,112503.0,4810.62,-58.79,51.0,H-SC,9.27,140.0,-0.08,0.77,8.09,AR,ATH,MISC
91,ZYDUSLIFE,-1.55,-5.44,43.43,35.63,86066.0,-11403.0,198171.0,1286.17,-17.57,45.0,H-MC,3.84,120.0,-0.13,1.35,4.19,AR,ATH,PHARMA

In [17]:
# top 5 to accumulate based on lowest RSI_14
df_tmp = df_portfolio_features[df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])].sort_values(by = 'RSI_14', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
33,HCLTECH,-0.40,-22.42,56.63,21.51,106282.0,-54246.0,187678.0,1872.35,-18.53,30.0,X-LC,8.94,8.0,-0.51,1.28,0.00,X40,ATH,IT
45,INFY,0.09,-20.45,68.75,34.24,171127.0,-63976.0,248912.0,1972.00,-37.23,33.0,X-LC,13.62,3.0,-0.37,1.69,1.43,X40,NTT,IT
40,ICICIPRULI,-1.49,-14.52,52.94,30.73,89148.0,-28610.0,168395.0,790.00,-37.54,35.0,X-MC,13.00,78.0,-0.32,1.15,2.61,X40,ATH,INSURANCE
35,HDFCLIFE,-2.26,-4.98,40.17,33.18,57175.0,-7467.0,142333.0,814.30,-25.87,38.0,X-LC,17.72,31.0,-0.13,0.97,2.62,X40,ATH,INSURANCE
39,ICICIGI,-1.37,-7.49,29.00,19.34,53684.0,-14991.0,185118.0,2252.93,-22.28,39.0,X-MC,6.11,66.0,-0.28,1.26,3.39,X40,ATH,INSURANCE

In [18]:
# top 5 to accumulate based on Spread and CumlRnk
df_tmp = df_portfolio_features[df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])]
df_tmp = df_tmp[(df_tmp['CumlRnk'] < 100)].sort_values(by = 'Spread%', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
88,VOLTAS,-3.47,11.37,30.37,45.20,64852.0,21798.0,213540.0,1856.00,27.51,51.0,X-MC,2.86,79.0,0.34,1.45,18.94,XY25,NTT,AC
84,UNITDSPR,-2.48,-2.33,23.65,20.77,54085.0,-5453.0,228691.0,1644.00,-13.41,51.0,X-MC,3.73,64.0,-0.10,1.56,9.09,X40N,NTT,BREWERIES
81,TMPV,-2.24,-21.51,74.01,36.58,206701.0,-76553.0,279288.0,600.00,-83.62,51.0,X-LC,5.12,4.0,-0.37,1.90,16.41,XY24,NTT,AUTO
87,VBL,-1.66,3.82,30.39,35.37,99649.0,12058.0,327900.0,670.16,-8.41,71.0,X-LC,5.42,13.0,0.12,2.23,34.77,X40N,ATH,FMCG
65,RELIANCE,-1.89,-10.24,39.59,25.30,71418.0,-20569.0,180394.0,1952.00,-12.73,55.0,X-LC,5.67,21.0,-0.29,1.23,7.19,XY25,BTT,REFINERIES

In [19]:
# top 5 to accumulate based on lowest Gained%
df_tmp = df_portfolio_features[df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])].sort_values(by = 'Gained%', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
33,HCLTECH,-0.40,-22.42,56.63,21.51,106282.0,-54246.0,187678.0,1872.35,-18.53,30.0,X-LC,8.94,8.0,-0.51,1.28,0.00,X40,ATH,IT
1,ABBOTINDIA,-0.51,-14.98,38.86,18.07,59094.0,-26785.0,152070.0,35195.00,-27.72,41.0,X-MC,11.95,58.0,-0.45,1.03,0.66,X40,ATH,PHARMA
45,INFY,0.09,-20.45,68.75,34.24,171127.0,-63976.0,248912.0,1972.00,-37.23,33.0,X-LC,13.62,3.0,-0.37,1.69,1.43,X40,NTT,IT
40,ICICIPRULI,-1.49,-14.52,52.94,30.73,89148.0,-28610.0,168395.0,790.00,-37.54,35.0,X-MC,13.00,78.0,-0.32,1.15,2.61,X40,ATH,INSURANCE
35,HDFCLIFE,-2.26,-4.98,40.17,33.18,57175.0,-7467.0,142333.0,814.30,-25.87,38.0,X-LC,17.72,31.0,-0.13,0.97,2.62,X40,ATH,INSURANCE

In [20]:
# top 5 to accumulate based on lowest CurrAlloc%
df_tmp = df_portfolio_features[df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])].sort_values(by = 'CurrAlloc%', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
64,RELAXO,-1.90,-61.36,294.13,52.31,164992.0,-89065.0,56095.0,1176.00,-58.86,49.0,X-SC,26.81,92.0,-0.54,0.38,25.42,X40N,NTT,FOOTWEAR
10,BATAINDIA,-1.10,-53.77,192.49,35.20,114489.0,-69192.0,59478.0,2096.00,-22.02,47.0,X-SC,26.88,91.0,-0.60,0.40,17.96,X40,NTT,FOOTWEAR
60,QUESS,-0.85,-17.45,110.66,73.90,97553.0,-18637.0,88156.0,424.00,-55.37,60.0,X-SC,15.36,80.0,-0.19,0.60,18.59,XY24,NTT,MISC
53,M&M,-3.19,-0.98,24.60,23.38,33782.0,-1355.0,137326.0,3802.40,-16.17,44.0,X-LC,8.75,25.0,-0.04,0.93,5.45,X40N,ATH,AUTO
59,PIDILITIND,-1.87,-3.41,22.54,18.37,30722.0,-4810.0,136300.0,1670.26,-32.34,48.0,X-LC,7.29,5.0,-0.16,0.93,7.02,X40,ATH,CHEMICALS

In [21]:
# top 5 to accumulate based on CumlRnk
df_tmp = df_portfolio_features.sort_values(by = 'CumlRnk', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
47,ITC,-0.40,-17.03,43.49,19.06,122746.0,-57926.0,282240.0,452.00,-54.31,61.0,X-LC,16.92,1.0,-0.47,1.92,9.49,X40,NTT,FMCG
79,TCS,-0.84,-27.96,75.70,26.57,252634.0,-129543.0,333730.0,4311.59,-39.04,44.0,X-LC,14.19,2.0,-0.51,2.27,4.16,X40,ATH,IT
45,INFY,0.09,-20.45,68.75,34.24,171127.0,-63976.0,248912.0,1972.00,-37.23,33.0,X-LC,13.62,3.0,-0.37,1.69,1.43,X40,NTT,IT
81,TMPV,-2.24,-21.51,74.01,36.58,206701.0,-76553.0,279288.0,600.00,-83.62,51.0,X-LC,5.12,4.0,-0.37,1.90,16.41,XY24,NTT,AUTO
59,PIDILITIND,-1.87,-3.41,22.54,18.37,30722.0,-4810.0,136300.0,1670.26,-32.34,48.0,X-LC,7.29,5.0,-0.16,0.93,7.02,X40,ATH,CHEMICALS

In [22]:
# top 5 for average up
df_tmp = df_portfolio_features[(df_portfolio_features['Dev%_200'] > 5)].sort_values(by = 'CurrAlloc%', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
44,INDUSINDBK,-1.16,-33.32,99.29,32.89,51116.0,-25724.0,51482.0,1800.00,-342.30,60.0,L-MC,3.88,258.0,-0.50,0.35,26.72,XR,NTT,BANKS
72,SIS,-0.85,-16.46,45.15,21.26,41879.0,-18276.0,92756.0,528.00,2198.45,77.0,H-SC,8.04,168.0,-0.44,0.63,37.91,OX40N,NTT,MISC
55,MASFIN,3.76,3.54,17.42,21.57,17672.0,3465.0,101445.0,397.04,-10.57,68.0,H-SC,0.56,167.0,0.20,0.69,31.09,XR,ATH,FINANCE
73,SONACOMS,-1.33,2.36,35.88,39.09,37153.0,2389.0,103548.0,804.02,-18.85,62.0,M-MC,16.19,193.0,0.06,0.70,46.48,AR,ATH,AUTO
75,SURYODAY,0.14,-12.96,41.35,23.03,64451.0,-23205.0,155866.0,216.00,68.86,69.0,H-SC,6.34,166.0,-0.36,1.06,32.92,XR,NTT,BANKS

In [23]:
# top 5 RSP
df_tmp = df_portfolio_features.sort_values(by = 'RSP', ascending=False)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
61,RAJESHEXPO,-4.71,-77.01,335.26,0.07,105734.0,-105639.0,31538.0,518.00,1055.30,51.0,L-SC,32.94,268.0,-1.00,0.21,48.06,OX40N,NTT,JEWELLERY
77,TANLA,-2.40,-41.10,268.86,117.25,428756.0,-111289.0,159472.0,1922.32,-40.45,60.0,H-SC,19.06,147.0,-0.26,1.08,39.62,AR,ATH,IT
9,BANDHANBNK,-0.68,-5.26,103.10,92.42,272094.0,-14646.0,263913.0,400.00,126.29,71.0,H-SC,5.43,174.0,-0.05,1.80,45.38,XY24,NTT,BANKS
0,5PAISA,0.13,-35.23,74.31,12.90,105166.0,-76973.0,141523.0,593.00,107.93,64.0,H-SC,9.02,170.0,-0.73,0.96,36.57,OX40N,NTT,FINANCE
86,VALIANTORG,-2.12,-43.68,209.23,74.15,192785.0,-71465.0,92140.0,838.00,-265.94,56.0,H-SC,17.11,145.0,-0.37,0.63,37.12,XR,NTT,CHEMICALS

In [24]:
# Top N allocation
df_tmp = df_portfolio_features.sort_values(by = 'CurrAlloc%', ascending=False)
top_n_values = [10, 25, 50]

sum_df = pd.DataFrame({
    'Top_N': top_n_values,
    'Sum_Alloc%': [df_tmp['CurrAlloc%'].head(n).sum() for n in top_n_values]
})

sum_df

   Top_N  Sum_Alloc%
0     10       19.26
1     25       42.75
2     50       72.67

In [25]:
# market-cap-wise allocation
df_tmp = df_portfolio_features[cols]
df_tmp.groupby(df_tmp['Conviction'].str[-2:])['CurrAlloc%'].sum().sort_values(ascending=False)

Conviction
SC    42.17
LC    31.91
MC    25.90
Name: CurrAlloc%, dtype: float64

In [26]:
# criteria-wise allocation
df_portfolio_features.groupby('Criteria')['CurrAlloc%'].sum().sort_values(ascending=False)

Criteria
XY24     26.89
X40      25.68
X40N     16.96
XR        9.10
XY25      6.95
OX40N     6.85
AR        6.75
SR        0.80
Name: CurrAlloc%, dtype: float64

In [27]:
# conviction-wise allocation
df_portfolio_features.groupby('Conviction')['CurrAlloc%'].sum().sort_values(ascending=False)

Conviction
X-LC    29.67
H-SC    21.95
X-MC    20.99
M-SC    10.02
X-SC     9.65
H-MC     2.54
M-MC     2.02
H-LC     1.29
M-LC     0.95
L-SC     0.55
L-MC     0.35
Name: CurrAlloc%, dtype: float64

In [28]:
# sector-wise stats
df_tmp = df_portfolio_features.groupby('Category')[['CurrAlloc%', 'Current', 'Current P/L', 'FTT Amt']].sum().sort_values(by=['Current', 'Current P/L'], ascending=False)
df_tmp['Current P/L%'] = round(df_tmp['Current P/L'] * 100 / df_tmp['Current'], 2)
df_tmp['FTT%'] = round(df_tmp['FTT Amt'] * 100 / df_tmp['Current'], 2)
cols = ['CurrAlloc%', 'Current P/L%', 'FTT%']
df_tmp[cols].sort_values(by=['CurrAlloc%'], ascending=False)

               CurrAlloc%  Current P/L%    FTT%
Category
FMCG                15.77        -14.14   54.41
FINANCE             10.78        -16.23   66.79
IT                  10.62        -44.24  116.86
MISC                 6.82        -33.75   91.85
AUTO                 6.62        -12.31   54.41
BANKS                5.63         -9.74   60.48
INSURANCE            5.32         -5.96   42.02
PAINTS               5.08        -31.83   54.73
PHARMA               4.76         -5.85   39.87
ELECTRICAL           4.11        -17.09   58.77
CHEMICALS            2.00        -38.21  120.57
AC                   1.98         -9.70   39.44
HEALTHCARE           1.90        -27.72   61.06
DURABLES             1.81        -45.84   81.32
FOOTWEAR             1.74        -72.20  141.24
APPARELS             1.74         -5.11   40.97
TRAVEL               1.71        -78.44  167.79
BREWERIES            1.56         -2.38   23.65
REALTY               1.36        -10.94   29.17
CERAMICS             1.29        -61.32  110.33
CABLES               1.26         20.21   65.89
REFINERIES           1.23        -11.40   39.59
ENGINEERING          1.18        -39.96  103.98
CEMENT               1.15        -58.24  176.63
JEWELLERY            1.04       -109.09  181.73
ENTERTAINMENT        0.75        -76.13  181.17
TEXTILES             0.43        -44.88   86.19
HOTELS               0.34       -125.13  204.53

In [29]:
# money to be made criteria-wise
df_portfolio_features.groupby('Criteria')['FTT Amt'].agg(['sum', 'count']).sort_values(by='sum', ascending=False)

                sum  count
Criteria
XY24      3643807.0     21
X40       1927249.0     19
XR        1344451.0     13
X40N      1232639.0     13
AR        1191179.0      9
OX40N      783807.0     10
XY25       417614.0      5
SR         301110.0      2

In [30]:
# money to be made conviction-wise
df_portfolio_features.groupby('Conviction')['FTT Amt'].agg(['sum', 'count']).sort_values(by='sum', ascending=False)

                  sum  count
Conviction
H-SC        3557229.0     24
X-LC        1935004.0     21
X-MC        1650420.0     15
M-SC        1444973.0     14
X-SC        1383996.0      9
H-MC         324898.0      2
L-SC         208895.0      2
M-LC         152646.0      1
M-MC          88248.0      2
L-MC          51116.0      1
H-LC          44431.0      1

In [31]:
# money to be made criteria and conviction-wise
df_portfolio_features.groupby(['Conviction', 'Criteria'])['FTT Amt'].agg(['sum', 'count']).sort_values(by='sum', ascending=False)

                           sum  count
Conviction Criteria
H-SC       XY24      1151090.0      6
X-LC       X40       1034210.0     10
H-SC       AR         947511.0      5
M-SC       XY24       856951.0      6
H-SC       XR         817614.0      7
X-SC       XY24       806191.0      4
X-MC       X40        688810.0      7
           X40N       492550.0      4
X-SC       X40N       373576.0      3
X-LC       X40N       366513.0      6
           XY24       348699.0      2
H-SC       OX40N      339904.0      4
M-SC       OX40N      338169.0      5
H-SC       SR         301110.0      2
X-MC       XY24       242044.0      2
H-MC       XY24       238832.0      1
X-MC       XY25       227016.0      2
X-SC       X40        204229.0      2
M-SC       XR         173835.0      2
M-LC       XR         152646.0      1
X-LC       XY25       139503.0      2
L-SC       OX40N      105734.0      1
           XR         103161.0      1
H-MC       AR          86066.0      1
M-SC       AR          76018.0      1
L-MC       XR          51116.0      1
M-MC       XY25        51095.0      1
X-LC       XR          46079.0      1
H-LC       AR          44431.0      1
M-MC       AR          37153.0      1

In [32]:
# notebook execution time

end_time = time.time()
execution_time = round(end_time - start_time, 0)
print(f"Notebook execution time: {execution_time} seconds")

Notebook execution time: 32.0 seconds