<a href="https://colab.research.google.com/github/ankit-rathi/Quantvesting_v2/blob/main/myStocks_Portfolio_Analysis.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
'''
!pip install pandas==2.2.2 -qq
!pip install pyxirr -qq
!pip install ta -qq
!pip install yfinance==0.2.59 -qq
'''

'\n!pip install pandas==2.2.2 -qq\n!pip install pyxirr -qq\n!pip install ta -qq\n!pip install yfinance==0.2.59 -qq\n'

In [2]:
# import libraries

import numpy as np
import pandas as pd
import datetime
import warnings
warnings.filterwarnings('ignore')
import yfinance as yfin
import ta
import matplotlib.pyplot as plt
import requests

In [3]:
# notebook start time
import time
import datetime
import pytz

start_time = time.time()

# function to print date timestamp
def print_date_time():
  tz_NY = pytz.timezone('Asia/Kolkata')
  datetime_NY = datetime.datetime.now(tz_NY)
  print("Run date time (IST):", datetime_NY.strftime("%Y-%m-%d %H:%M:%S"))

In [4]:
# function to get booked and reserved amount
def get_amt():
  # fetch the JSON data from the URL
  url = "https://raw.githubusercontent.com/ankit-rathi/Tradevesting_v1/main/data/myPortfolioAmts.json"
  response = requests.get(url)
  pf_amts = response.json()  # parse the JSON data

  # extract values from the JSON
  py_booked_amt_dm = pf_amts["py_booked_amt_dm"]
  py_booked_amt_sv = pf_amts["py_booked_amt_sv"]
  cy_booked_amt_dm = pf_amts["cy_booked_amt_dm"]
  cy_booked_amt_sv = pf_amts["cy_booked_amt_sv"]
  reserve_amt_dm = pf_amts["reserve_amt_dm"]
  reserve_amt_sv = pf_amts["reserve_amt_sv"]

  # perform calculations
  py_booked_amt = py_booked_amt_dm + py_booked_amt_sv
  cy_booked_amt = cy_booked_amt_dm + cy_booked_amt_sv
  reserve_amt = reserve_amt_dm + reserve_amt_sv
  total_booked_amt = py_booked_amt + cy_booked_amt

  return total_booked_amt, reserve_amt, cy_booked_amt, py_booked_amt

gen_output = 0

In [5]:
# function to format the amount
def format_amt(number):
    abs_number = abs(number)

    if abs_number >= 1_00_00_000:  # Crores
        formatted_amt = f"{number / 1_00_00_000:.2f} C"
    elif abs_number >= 1_00_000:  # Lakhs
        formatted_amt = f"{number / 1_00_000:.2f} L"
    elif abs_number >= 1_000:  # Thousands
        formatted_amt = f"{number / 1_000:.2f} K"
    else:
        formatted_amt = f"{number:.2f}"

    return formatted_amt

# function to set start and end date
def get_start_end_date():
  start_date = (datetime.date.today() + datetime.timedelta(days=-365)).strftime('%Y-%m-%d')
  end_date = (datetime.date.today() + datetime.timedelta(days=1)).strftime('%Y-%m-%d')
  return start_date, end_date

# function to fetch my portfolio csv
def get_mypfs_df():
  mypfs_df = pd.read_csv('https://raw.githubusercontent.com/ankit-rathi/Tradevesting_v1/main/data/myPortfolioStocks.csv')
  return mypfs_df

# function to fetch my prospects csv
def get_mypps_df():
  mypps_df = pd.read_csv('https://raw.githubusercontent.com/ankit-rathi/Tradevesting_v1/main/data/myProspectsScrips.csv')
  return mypps_df

# function to fetch screener data
def get_myscreen_df():
  myscreen_df = pd.read_csv('https://raw.githubusercontent.com/ankit-rathi/Tradevesting_v1/main/data/myScreenerDB.csv')
  return myscreen_df

# function to fetch momentum data
def get_myinvmt_df():
  myinvmt_df = pd.read_csv('https://raw.githubusercontent.com/ankit-rathi/Tradevesting_v1/main/data/myInvestments.csv')
  return myinvmt_df

# function to get the stock ids
def get_stock_ids(df_pf):
  stock_n100 = df_pf['Symbol'].unique()

  exclude = ['CADILAHC','MMTC', 'MASFIN']

  stock_ids = df_pf[~df_pf['Symbol'].isin(exclude) ]['Symbol'].unique()

  #mypf = mypf[mypf.Forecast.notnull()]
  #stock_ids = mypf['Symbol'].unique()

  #stock_ids.sort()
  return stock_ids

# get features from screener data
def get_screener_features():
  myscreen_df = get_myscreen_df()
  cols = ['Symbol', 'EPS', 'MedPE', 'ROCE%', 'ROE%', 'CapType']
  return myscreen_df[cols]

# get relative strength
def get_relative_strength(stock_list):

    # Dictionary to store stock tickers and their corresponding percentage price change
    stock_changes = {}

    # Loop through each stock and fetch its price data
    for stock in stock_list:
        try:
            # Download the stock data for the given date range
            stock_data = yfin.Ticker(stock + '.NS').history(period='1mo', interval='1d')[map(str.title, ['open', 'close', 'low', 'high', 'volume'])]

            # Calculate the percentage change for the stock
            if len(stock_data) > 0:
                start_price = stock_data['Close'].iloc[0]
                end_price = stock_data['Close'].iloc[-1]
                percent_change = round(((end_price - start_price) / start_price) * 100, 2)
                stock_changes[stock] = percent_change
            else:
                stock_changes[stock] = np.nan  # If no data is available, set to NaN

        except Exception as e:
            print(f"Error fetching data for {stock}: {e}")
            stock_changes[stock] = np.nan

    # Create a DataFrame with stock tickers and their percentage changes
    df = pd.DataFrame(list(stock_changes.items()), columns=['Symbol', 'Percent_Change'])

    # Drop any stocks with missing data (NaN values)
    df = df.dropna()

    # Calculate the percentile rank based on percentage change
    df['RSP'] = round(df['Percent_Change'].rank(pct=True) * 100, 2)
    cols = ['Symbol', 'RSP']
    df = df[cols]
    # Sort by percentile rank (optional)
    df = df.sort_values(by='RSP', ascending=False).reset_index(drop=True)

    return df

In [6]:
# function to get stock technicals
def stock_prec_dev(stock_symbol):
    #stock_symbol = 'ULTRACEMCO.NS'
    short_window = 20
    mid_window = 50
    long_window = 200
    moving_avg = 'SMA'

    start = datetime.datetime(*map(int, start_date.split('-')))
    end = datetime.datetime(*map(int, end_date.split('-')))

    stock_df = yfin.Ticker(stock_symbol + '.NS').history(period='max', interval='1d')[map(str.title, ['open', 'close', 'low', 'high', 'volume'])]

    stock_df['Max'] = round(max(stock_df['Close']),2)
    stock_df = stock_df[(stock_df.index <= end_date) & (stock_df.index >= start_date)]
    stock_df['200_SMA'] = round(stock_df['Close'].rolling(window = 200, min_periods = 1).mean(),0)
    stock_df['Dev%_200'] = round((stock_df['Close'] - stock_df['200_SMA'])*100/stock_df['200_SMA'],2)
    stock_df.dropna(axis = 0, inplace = True) # remove any null rows

    stock_df['20_SMA'] = stock_df['Close'].rolling(window=20).mean()
    stock_df['50_SMA'] = stock_df['Close'].rolling(window=50).mean()
    stock_df['Symbol'] = stock_symbol

    stock_df['Close'] = round(stock_df['Close'],2)
    stock_df['Min'] = round(min(stock_df['Close']),2)
    stock_df['RSI_14'] = ta.momentum.RSIIndicator(close=stock_df['Close'], window=14).rsi()
    stock_df['RSI_14'] = round(stock_df['RSI_14'],0)
    stock_df['Prev_Close'] = stock_df['Close'].shift(1)
    stock_df.drop(['Open', 'Low', 'High', 'Volume'], axis=1, inplace=True)
    stock_df = stock_df.tail(1)

    max_SMA = max(stock_df['20_SMA'].item(), stock_df['50_SMA'].item(), stock_df['200_SMA'].item())
    min_SMA = min(stock_df['20_SMA'].item(), stock_df['50_SMA'].item(), stock_df['200_SMA'].item())
    ABS_Spread = max_SMA - min_SMA
    stock_df['Spread%'] = round((ABS_Spread / stock_df['200_SMA'].item()) * 100,2)

    return stock_df

# function to compute stock attributes
def get_common_features(stock_ids, df_mypf):

  df_prec_dev = pd.DataFrame()
  df_tmp = get_screener_features()
  df_rs = get_relative_strength(stock_ids)

  for stock_id in stock_ids:
      tmp = stock_prec_dev(stock_id)
      tmp = tmp.reset_index()
      df_prec_dev = pd.concat([df_prec_dev, tmp], ignore_index = True)
  df_prec_dev = pd.merge(df_prec_dev, df_mypf, on= 'Symbol')
  df_prec_dev = pd.merge(df_prec_dev, df_tmp, on= 'Symbol', how='left')
  df_prec_dev = pd.merge(df_prec_dev, df_rs, on= 'Symbol', how='left')
  #print(df_prec_dev.columns)
  df_prec_dev['Curr_PE'] = round(df_prec_dev['Close']/df_prec_dev['EPS'],1)
  df_prec_dev['Dev%_PE'] = round((df_prec_dev['Curr_PE'] - df_prec_dev['MedPE'])*100/df_prec_dev['MedPE'],2)
  df_prec_dev['Conviction'] = df_prec_dev['Conviction'] + '-' + df_prec_dev['CapType']
  return df_prec_dev

# function to arrange stock features
def arrange_features(df_stocks, common_cols, diff_cols):
  df_stocks_common = df_stocks[common_cols].drop_duplicates()
  df_stocks_diff = df_stocks[diff_cols]
  df_stocks_diff['Investment'] = df_stocks_diff['AvgCost'] * df_stocks_diff['Shares']
  df_stocks_diff = df_stocks_diff.groupby(['Symbol'])[['Shares', 'Investment']].aggregate(['sum']).reset_index()
  df_stocks_diff.columns = ['Symbol', 'Shares', 'Investment']
  df_stocks_diff['AvgCost'] = round(df_stocks_diff['Investment']/df_stocks_diff['Shares'],2)
  df_stocks = pd.merge(df_stocks_diff, df_stocks_common, on='Symbol')
  return df_stocks

# plot fact distribution across dimension
def plot_pie_chart(df, dimension, fact):
  # grouping the data by category and calculating the sum of fact for each type
  grouped_data = df.groupby(dimension)[fact].sum()

  # sorting the grouped data in descending order
  grouped_data = grouped_data.sort_values(ascending=False)

  # creating a pie chart
  grouped_data.plot.pie(autopct='%1.1f%%', startangle=90, figsize=(6, 6))

  # adding a title and displaying the plot
  plt.title(f'{dimension} {fact} Distribution')
  plt.ylabel('')  # To hide the y-label
  plt.show()

In [7]:
# function to get portfolio features

def get_portfolio_features(df_common_features):

  print_date_time()
  print('-------------------')

  #df_common_features["Target"] = df_common_features["Target"].fillna(df_common_features["Max"])
  df_common_features['NTT'] = np.where(df_common_features['Strategy']== 'NTT', df_common_features["Target"], df_common_features['Max'])
  df_common_features['LTT'] = np.where(df_common_features['Strategy']== 'BTT', df_common_features["Target"], df_common_features['Max'])
  df_common_features['BOL'] = df_common_features['Min']

  tmp_df = df_common_features[df_common_features['Symbol'].isin(mypf_df[mypf_df['InPortfolio'] != 'NA'].Symbol.values)]
  print('qualified stocks: '+str(len(tmp_df['Symbol'].unique())))
  tmp_df1 = tmp_df[tmp_df['LatestQtr'] == 1]
  print('with latest results: '+str(len(tmp_df1['Symbol'].unique())))
  tmp_df1 = tmp_df1[tmp_df1['StarStock'] == 1]
  print('still star stocks: '+str(len(tmp_df1['Symbol'].unique())))
  tmp_df['Investment'] = tmp_df['AvgCost'] * tmp_df['Shares']
  tmp_df['Current'] = round(tmp_df['Close'] * tmp_df['Shares'],0)
  tmp_df['Previous'] = tmp_df['Prev_Close'] * tmp_df['Shares']
  tmp_df['EstimatedST'] = tmp_df['NTT'] * tmp_df['Shares']
  tmp_df['EstimatedLT'] = tmp_df['LTT'] * tmp_df['Shares']
  tmp_df['Current P/L'] = round((tmp_df['Current'] - tmp_df['Investment']),0)
  tmp_df['Today P/L%'] = round((tmp_df['Current'] - tmp_df['Previous'])*100/tmp_df['Previous'],2)
  tmp_df['Current P/L%'] = round((tmp_df['Current'] - tmp_df['Investment'])*100/tmp_df['Investment'],2)
  tmp_df['EstimatedST P/L%'] = round((tmp_df['EstimatedST'] - tmp_df['Investment'])*100/tmp_df['Investment'],2)
  tmp_df['EstimatedLT P/L%'] = round((tmp_df['EstimatedLT'] - tmp_df['Investment'])*100/tmp_df['Investment'],2)
  tmp_df['NTT%'] = round((tmp_df['NTT'] - tmp_df['Close'])*100/tmp_df['Close'],2)
  tmp_df['LTT%'] = round((tmp_df['LTT'] - tmp_df['Close'])*100/tmp_df['Close'],2)
  tmp_df['Gained%'] = round((tmp_df['Close'] - tmp_df['BOL'])*100/tmp_df['BOL'],2)
  investment = round(sum(tmp_df['AvgCost']*tmp_df['Shares']),0)
  current = round(sum(tmp_df['Close']*tmp_df['Shares']),0)
  tmp_df['InitAlloc%'] = round(tmp_df['Investment']*100/investment,2)
  tmp_df['CurrAlloc%'] = round(tmp_df['Current']*100/current,2)
  tmp_df['FTT'] = tmp_df['LTT']
  tmp_df.loc[tmp_df['Strategy'] == 'NTT', 'FTT'] = tmp_df['NTT']
  tmp_df['FTT%'] = tmp_df['LTT%']
  tmp_df.loc[tmp_df['Strategy'] == 'NTT', 'FTT%'] = tmp_df['NTT%']
  tmp_df['FTT Amt'] = round(tmp_df['FTT%'] * tmp_df['Current']/100,0)
  tmp_df['OTT%'] = round((tmp_df['FTT'] - tmp_df['AvgCost'])*100/tmp_df['AvgCost'],2)
  tmp_df['RRR Ind'] = round(tmp_df['Current P/L']/tmp_df['FTT Amt'],2)
  tmp_df['Risk Ind'] = round(tmp_df['Current P/L%']*tmp_df['CurrAlloc%'],0)

  return tmp_df

# function to print portfolio features
def print_portfolio_stats(df_portfolio_features, myinvmt_df):
  from pyxirr import xirr

  total_booked_amt, reserve_amt, cy_booked_amt, py_booked_amt = get_amt()

  dates = myinvmt_df['Date'].values
  dates = np.append(dates, datetime.date.today().strftime('%d-%b-%y'))
  investment = myinvmt_df['Investment'].values
  dates= pd.to_datetime(dates)

  current = round(sum(df_portfolio_features['Close']*df_portfolio_features['Shares']),0) + reserve_amt
  investment_xirr = np.append(investment, current)
  cagr = round(xirr(pd.DataFrame({"dates": dates, "amounts": investment_xirr}))*100,2)

  investment = -sum(investment)
  invested = round(sum(df_portfolio_features['AvgCost']*df_portfolio_features['Shares']),0) + reserve_amt
  previous = round(sum(df_portfolio_features['Prev_Close']*df_portfolio_features['Shares']),0) + reserve_amt
  cy_invested = investment + py_booked_amt

  today_pnl_amount = current-previous
  today_pnl_percentage = round((current-previous)*100/previous,2)

  curr_pnl_amount = current-invested
  curr_pnl_percentage = round((curr_pnl_amount)*100/(cy_invested),2)

  cy_pnl_amount = cy_booked_amt + curr_pnl_amount
  cy_pnl_percentage = round((cy_pnl_amount)*100/cy_invested,2)

  overall_pnl_amount = total_booked_amt + curr_pnl_amount
  overall_pnl_percentage = round((overall_pnl_amount)*100/investment,2)

  estimate_st = round(sum(df_portfolio_features['FTT']*df_portfolio_features['Shares']),0)  + reserve_amt
  est_st_pnl_amount = estimate_st-current
  est_st_pnl_percentage = round((est_st_pnl_amount)*100/current,2)

  estimate_lt = round(sum(df_portfolio_features['LTT']*df_portfolio_features['Shares']),0)  + reserve_amt
  est_lt_pnl_amount = estimate_lt-current
  est_lt_pnl_percentage = round((est_lt_pnl_amount)*100/current,2)

  total_profit = round(sum(df_portfolio_features[df_portfolio_features['Current P/L%'] > 0]['Current']) - sum(df_portfolio_features[df_portfolio_features['Current P/L%'] > 0]['Investment']),0)
  total_loss = round(sum(df_portfolio_features[df_portfolio_features['Current P/L%'] < 0]['Current']) - sum(df_portfolio_features[df_portfolio_features['Current P/L%'] < 0]['Investment']),0)

  cy_booked_percentage = round((cy_booked_amt)*100/current,2)
  py_booked_percentage = round((py_booked_amt)*100/investment,2)
  total_booked_percentage = round((total_booked_amt)*100/investment,2)

  print('-------------------')
  print('Initial Investment: ', format_amt(investment))
  print('CY Investment: ', format_amt(cy_invested))
  print('Reserve: ', format_amt(reserve_amt))
  print('Current: ',  format_amt(current))
  print('-------------------')
  print('Today PnL: '+ '{} ({}%)'.format(format_amt(today_pnl_amount), today_pnl_percentage))
  print('Current PnL: '+ '{} ({}%)'.format(format_amt(curr_pnl_amount), curr_pnl_percentage))
  print('CY Booked + Current PnL: '+ '{} ({}%)'.format(format_amt(cy_pnl_amount), cy_pnl_percentage))
  print('-------------------')
  print('Total profit: ', format_amt(total_profit))
  print('Total loss: ', format_amt(total_loss))
  print('-------------------')
  print('Total Booked + Current PnL: '+ '{} ({}%)'.format(format_amt(overall_pnl_amount), overall_pnl_percentage))
  print('Total Booked PnL: '+ '{} ({}%)'.format(format_amt(total_booked_amt), total_booked_percentage))
  print('Curr Year Booked PnL: '+ '{} ({}%)'.format(format_amt(cy_booked_amt), cy_booked_percentage))
  print('Prev Year Booked PnL: '+ '{} ({}%)'.format(format_amt(py_booked_amt), py_booked_percentage))
  print('===================')
  print('Est FTT: ',  format_amt(estimate_st))
  print('Est FTT PnL: '+ '{} ({}%)'.format(format_amt(est_st_pnl_amount), est_st_pnl_percentage))

  print('===================')
  print('Deployed: ', format_amt(investment))

  print('Current: ', format_amt(current))

  print('CAGR/XIRR %: '+'{}%'.format(cagr))

In [8]:
# get start and end date
start_date, end_date = get_start_end_date()

# get portfolio and prospects data
mypfs_df = get_mypfs_df()
mypps_df = get_mypps_df()
myinvmt_df = get_myinvmt_df()

# merge above datasets
mypf_df = pd.merge(mypfs_df, mypps_df, on="Symbol")

# seggregate dm and sv portfolio
dm_pf = mypf_df[mypf_df['InPortfolio'] == 'DM']
sv_pf = mypf_df[mypf_df['InPortfolio'] == 'SV']

# build portfolio stock dataframe
dm_stocks = get_stock_ids(dm_pf)
sv_stocks = get_stock_ids(sv_pf)
df_stocks = pd.concat([dm_pf,sv_pf], ignore_index = True)

# arrange common and diff stock features
common_cols = ['Symbol', 'Target', 'Criteria', 'Strategy', 'CumlRnk', 'LatestQtr', 'StarStock', 'Conviction', 'Category', 'InFolio', 'XIRR', 'MBQ']
diff_cols = ['Symbol', 'AvgCost', 'Shares']
df_stocks = arrange_features(df_stocks, common_cols, diff_cols)

# get common features
stock_ids = df_stocks['Symbol'].values
df_common_features = get_common_features(stock_ids, df_stocks)

df_common_features.reset_index(drop=True, inplace=True)
df_common_features.drop(['Date'], axis=1, inplace=True)
# get and print portfolio features
df_portfolio_features = get_portfolio_features(df_common_features)

print_portfolio_stats(df_portfolio_features, myinvmt_df)

df = df_portfolio_features
#plot_pie_chart(df, 'CapType', 'Current')
list_ox40n = list(df[df['MBQ'].str.contains('OX40N', na=False)]['Symbol'].values)

Run date time (IST): 2026-08-19 13:33:51
-------------------
qualified stocks: 87
with latest results: 30
still star stocks: 19
-------------------
Initial Investment:  1.46 C
CY Investment:  1.89 C
Reserve:  3.69 L
Current:  1.58 C
-------------------
Today PnL: -54.46 K (-0.34%)
Current PnL: -35.30 L (-18.69%)
CY Booked + Current PnL: -30.24 L (-16.01%)
-------------------
Total profit:  3.39 L
Total loss:  -38.69 L
-------------------
Total Booked + Current PnL: 12.63 L (8.65%)
Total Booked PnL: 47.93 L (32.82%)
Curr Year Booked PnL: 5.06 L (3.21%)
Prev Year Booked PnL: 42.87 L (29.35%)
===================
Est FTT:  2.67 C
Est FTT PnL: 1.09 C (69.43%)
===================
Deployed:  1.46 C
Current:  1.58 C
CAGR/XIRR %: 3.46%

In [9]:
# top 5 near their targets
cols = ['Symbol', 'Today P/L%', 'Current P/L%', 'FTT%', 'OTT%', 'FTT Amt', 'Current P/L', 'Current', 'FTT', 'Dev%_PE', 'RSI_14','Conviction', 'Spread%',  'CumlRnk', 'RRR Ind', 'CurrAlloc%', 'Gained%', 'Criteria', 'Strategy', 'Category']
df_tmp = df_portfolio_features[~df_portfolio_features['Symbol'].isin(['ENRIN','BLUSPRING','DIGITIDE'])]
df_tmp = df_tmp.sort_values(by = 'FTT Amt', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
66,SIEMENS,-1.24,5.00,5.55,10.83,10845.0,9310.0,195405.0,4125.00,-14.90,58.0,H-LC,13.93,51.0,0.86,1.27,37.87,AR,NTT,ELECTRICAL
78,UNITDSPR,-0.14,11.57,8.24,20.77,21526.0,27090.0,261234.0,1644.00,-4.95,59.0,X-MC,11.25,64.0,1.26,1.70,25.57,X40N,NTT,BREWERIES
77,TTKPRESTIG,-1.53,-23.89,31.51,0.09,24168.0,-24077.0,76700.0,770.00,-7.35,40.0,M-SC,9.66,250.0,-1.00,0.50,38.05,OX40N,NTT,DURABLES
52,M&M,-0.15,7.88,10.14,18.82,26328.0,18965.0,259646.0,3762.88,-6.96,58.0,X-LC,4.86,25.0,0.72,1.69,17.78,X40N,ATH,AUTO
54,MASFIN,-1.00,-7.46,31.36,21.57,28436.0,-7305.0,90675.0,397.04,-28.64,43.0,H-SC,1.16,167.0,-0.26,0.59,8.08,XR,ATH,FINANCE

In [10]:
# top 5 today
df_tmp = df_portfolio_features.sort_values(by = 'Today P/L%', ascending=False)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
0,5PAISA,6.20,-23.01,46.64,12.90,78462.0,-50266.0,168230.0,593.00,7.98,66.0,H-SC,11.31,170.0,-0.64,1.09,62.34,OX40N,NTT,FINANCE
27,GLAXO,4.30,20.48,12.63,35.69,30323.0,40804.0,240088.0,3380.16,-9.68,86.0,X-MC,9.81,56.0,1.35,1.56,42.69,X40,ATH,PHARMA
3,ALKYLAMINE,2.86,-15.89,128.90,92.54,109468.0,-16038.0,84925.0,4520.85,NaN,63.0,NaN,14.42,142.0,-0.15,0.55,61.27,SR,ATH,CHEMICALS
62,REPCOHOME,2.06,-23.04,146.64,89.82,323344.0,-66003.0,220502.0,880.00,NaN,32.0,NaN,4.12,161.0,-0.20,1.43,6.00,XY24,NTT,FINANCE
12,BOSCH-HCIL,1.96,-24.04,31.63,-0.01,30709.0,-30718.0,97087.0,2282.00,759.04,77.0,M-SC,6.86,231.0,-1.00,0.63,65.26,OX40N,BTT,AC

In [11]:
# bottom 5 today
df_tmp = df_portfolio_features.sort_values(by = 'Today P/L%', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
29,GREENPANEL,-4.33,-56.75,230.97,43.14,182877.0,-103900.0,79178.0,537.00,NaN,26.0,NaN,11.63,225.0,-0.57,0.51,0.00,XY24,NTT,MISC
60,RELAXO,-3.68,-51.20,212.10,52.31,150247.0,-74322.0,70838.0,1176.00,NaN,39.0,NaN,12.74,92.0,-0.49,0.46,58.39,X40N,NTT,FOOTWEAR
70,SYMPHONY,-2.62,-53.74,116.12,-0.03,91924.0,-91978.0,79163.0,1306.00,NaN,23.0,NaN,16.25,205.0,-1.00,0.51,0.00,OX40N,NTT,DURABLES
25,FINCABLES,-2.41,64.30,26.54,107.91,64382.0,94942.0,242586.0,1641.55,19.75,70.0,M-SC,20.37,220.0,1.47,1.58,82.51,OX40N,ATH,CABLES
83,VOLTAS,-2.23,-4.17,51.51,45.20,94650.0,-7992.0,183750.0,1856.00,31.93,35.0,X-MC,4.53,79.0,-0.08,1.19,0.71,XY25,NTT,AC

In [12]:
# top 5 to exit based on CumlRnk
df_tmp = df_portfolio_features[~df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])]
df_tmp = df_tmp[(df_tmp['Current P/L%'] > -1) & (df_tmp['Current P/L%'] < 1)].sort_values(by = 'CumlRnk', ascending=False)
df_tmp[cols].head()

Empty DataFrame
Columns: [Symbol, Today P/L%, Current P/L%, FTT%, OTT%, FTT Amt, Current P/L, Current, FTT, Dev%_PE, RSI_14, Conviction, Spread%, CumlRnk, RRR Ind, CurrAlloc%, Gained%, Criteria, Strategy, Category]
Index: []

In [13]:
# OX40N stocks to exit
df_tmp = df_portfolio_features[(df_portfolio_features['Symbol'].isin(list_ox40n))].sort_values(by = 'Current P/L%', ascending=False)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
25,FINCABLES,-2.41,64.30,26.54,107.91,64382.0,94942.0,242586.0,1641.55,19.75,70.0,M-SC,20.37,220.0,1.47,1.58,82.51,OX40N,ATH,CABLES
67,SIS,-0.11,-4.46,26.92,21.26,28557.0,-4952.0,106080.0,528.00,103.76,39.0,H-SC,21.59,168.0,-0.17,0.69,57.73,OX40N,NTT,MISC
43,INDIGOPNTS,-1.05,-18.39,22.56,0.02,32137.0,-32108.0,142451.0,1408.00,-22.11,63.0,M-SC,7.03,222.0,-1.00,0.93,61.62,OX40N,NTT,PAINTS
0,5PAISA,6.20,-23.01,46.64,12.90,78462.0,-50266.0,168230.0,593.00,7.98,66.0,H-SC,11.31,170.0,-0.64,1.09,62.34,OX40N,NTT,FINANCE
77,TTKPRESTIG,-1.53,-23.89,31.51,0.09,24168.0,-24077.0,76700.0,770.00,-7.35,40.0,M-SC,9.66,250.0,-1.00,0.50,38.05,OX40N,NTT,DURABLES

In [14]:
# top 5 to book for rotation
df_tmp = df_portfolio_features[(df_portfolio_features['Current P/L%'] > 20) ].sort_values(by = 'CumlRnk', ascending=False)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
25,FINCABLES,-2.41,64.30,26.54,107.91,64382.0,94942.0,242586.0,1641.55,19.75,70.0,M-SC,20.37,220.0,1.47,1.58,82.51,OX40N,ATH,CABLES
27,GLAXO,4.30,20.48,12.63,35.69,30323.0,40804.0,240088.0,3380.16,-9.68,86.0,X-MC,9.81,56.0,1.35,1.56,42.69,X40,ATH,PHARMA

In [15]:
# top 5 to monitor for exit
df_tmp = df_portfolio_features[~df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])]
df_tmp = df_tmp[(df_tmp['Current P/L%'] > 0) ].sort_values(by = 'Dev%_PE', ascending=False)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
25,FINCABLES,-2.41,64.30,26.54,107.91,64382.0,94942.0,242586.0,1641.55,19.75,70.0,M-SC,20.37,220.0,1.47,1.58,82.51,OX40N,ATH,CABLES
68,STARHEALTH,-0.09,12.96,30.36,47.26,96411.0,36437.0,317560.0,761.00,-0.37,50.0,H-SC,16.24,173.0,0.38,2.06,37.30,XY24,NTT,INSURANCE

In [16]:
# top 5 to book for rotation from weak conviction
df_tmp = df_portfolio_features[~df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])]
df_tmp = df_tmp[~df_tmp['Criteria'].isin(['XY25','XY24','X40', 'X40N'])].sort_values(by = 'RRR Ind', ascending=False)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
25,FINCABLES,-2.41,64.30,26.54,107.91,64382.0,94942.0,242586.0,1641.55,19.75,70.0,M-SC,20.37,220.0,1.47,1.58,82.51,OX40N,ATH,CABLES
3,ALKYLAMINE,2.86,-15.89,128.90,92.54,109468.0,-16038.0,84925.0,4520.85,NaN,63.0,NaN,14.42,142.0,-0.15,0.55,61.27,SR,ATH,CHEMICALS
67,SIS,-0.11,-4.46,26.92,21.26,28557.0,-4952.0,106080.0,528.00,103.76,39.0,H-SC,21.59,168.0,-0.17,0.69,57.73,OX40N,NTT,MISC
42,INDIAMART,-1.15,-25.53,169.81,100.92,155960.0,-31492.0,91844.0,4675.60,NaN,34.0,NaN,13.70,140.0,-0.20,0.60,0.00,AR,ATH,MISC
71,TANLA,-0.17,-34.93,233.88,117.25,412050.0,-94581.0,176180.0,1922.32,NaN,47.0,NaN,15.75,147.0,-0.23,1.14,54.25,AR,ATH,IT

In [17]:
# top 5 to accumulate based on lowest RSI_14
df_tmp = df_portfolio_features[df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])].sort_values(by = 'RSI_14', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
19,COLPAL,-1.84,-29.08,97.20,39.86,181560.0,-76575.0,186790.0,3683.41,-14.08,26.0,X-MC,1.54,62.0,-0.42,1.21,5.66,XY25,ATH,FMCG
47,ITC,-1.07,-26.31,69.23,24.70,202665.0,-104536.0,292742.0,452.00,-31.16,29.0,X-LC,10.68,1.0,-0.52,1.90,0.00,X40,NTT,FMCG
56,PGHH,-1.33,-38.15,113.45,32.01,149818.0,-81464.0,132056.0,17616.87,-54.51,29.0,X-SC,19.67,57.0,-0.54,0.86,0.00,X40,ATH,FMCG
55,PAGEIND,-1.73,-7.15,43.08,32.85,107355.0,-19179.0,249200.0,50936.07,-30.94,30.0,X-MC,8.54,55.0,-0.18,1.62,19.00,X40,ATH,APPARELS
34,HDFCBANK,-0.51,-12.15,49.17,31.05,126617.0,-35611.0,257509.0,1073.00,-29.01,31.0,X-LC,12.78,26.0,-0.28,1.67,0.00,X40,BTT,BANKS

In [18]:
# top 5 to accumulate based on Spread and CumlRnk
df_tmp = df_portfolio_features[df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])]
df_tmp = df_tmp[(df_tmp['CumlRnk'] < 100)].sort_values(by = 'Spread%', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
19,COLPAL,-1.84,-29.08,97.20,39.86,181560.0,-76575.0,186790.0,3683.41,-14.08,26.0,X-MC,1.54,62.0,-0.42,1.21,5.66,XY25,ATH,FMCG
50,KOTAKBANK,0.79,2.69,15.81,18.92,38915.0,6439.0,246141.0,452.46,-13.30,51.0,X-LC,2.25,12.0,0.17,1.60,10.75,X40,ATH,BANKS
23,DMART,-0.13,-2.74,35.12,31.42,106498.0,-8550.0,303240.0,5391.45,-18.43,48.0,X-LC,2.31,14.0,-0.08,1.97,9.43,X40N,ATH,FMCG
26,GILLETTE,-0.90,-11.37,46.37,29.72,104346.0,-28866.0,225030.0,10978.86,-36.01,36.0,X-SC,3.55,83.0,-0.28,1.46,3.41,X40,ATH,FMCG
1,ABBOTINDIA,-1.90,-11.45,30.29,15.37,47970.0,-20485.0,158370.0,34390.26,-27.99,37.0,X-MC,4.04,58.0,-0.43,1.03,7.28,X40,ATH,PHARMA

In [19]:
# top 5 to accumulate based on lowest Gained%
df_tmp = df_portfolio_features[df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])].sort_values(by = 'Gained%', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
20,DABUR,-0.81,-21.75,83.64,43.70,162363.0,-53947.0,194121.0,735.00,-32.48,33.0,X-MC,10.16,70.0,-0.33,1.26,0.0,XY24,BTT,FMCG
47,ITC,-1.07,-26.31,69.23,24.70,202665.0,-104536.0,292742.0,452.00,-31.16,29.0,X-LC,10.68,1.0,-0.52,1.90,0.0,X40,NTT,FMCG
36,HINDUNILVR,-0.93,-16.12,44.93,21.56,126817.0,-54263.0,282254.0,2922.00,-42.16,37.0,X-LC,6.41,9.0,-0.43,1.83,0.0,XY25,NTT,FMCG
34,HDFCBANK,-0.51,-12.15,49.17,31.05,126617.0,-35611.0,257509.0,1073.00,-29.01,31.0,X-LC,12.78,26.0,-0.28,1.67,0.0,X40,BTT,BANKS
56,PGHH,-1.33,-38.15,113.45,32.01,149818.0,-81464.0,132056.0,17616.87,-54.51,29.0,X-SC,19.67,57.0,-0.54,0.86,0.0,X40,ATH,FMCG

In [20]:
# top 5 to accumulate based on lowest CurrAlloc%
df_tmp = df_portfolio_features[df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])].sort_values(by = 'CurrAlloc%', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
56,PGHH,-1.33,-38.15,113.45,32.01,149818.0,-81464.0,132056.0,17616.87,-54.51,29.0,X-SC,19.67,57.0,-0.54,0.86,0.00,X40,ATH,FMCG
2,ACC,-1.23,-42.37,203.33,74.81,314194.0,-113604.0,154524.0,3906.00,-42.69,34.0,X-SC,11.71,85.0,-0.36,1.00,3.23,XY24,BTT,CEMENT
1,ABBOTINDIA,-1.90,-11.45,30.29,15.37,47970.0,-20485.0,158370.0,34390.26,-27.99,37.0,X-MC,4.04,58.0,-0.43,1.03,7.28,X40,ATH,PHARMA
40,ICICIPRULI,-1.36,-17.24,57.42,30.28,93614.0,-33972.0,163033.0,787.27,-46.93,46.0,X-MC,12.47,78.0,-0.36,1.06,8.62,X40,ATH,INSURANCE
39,ICICIGI,-0.36,-14.16,38.50,18.89,66133.0,-28336.0,171773.0,2244.41,-14.59,40.0,X-MC,10.53,66.0,-0.43,1.12,2.34,X40,ATH,INSURANCE

In [21]:
# top 5 to accumulate based on CumlRnk
df_tmp = df_portfolio_features.sort_values(by = 'CumlRnk', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
47,ITC,-1.07,-26.31,69.23,24.70,202665.0,-104536.0,292742.0,452.00,-31.16,29.0,X-LC,10.68,1.0,-0.52,1.90,0.00,X40,NTT,FMCG
73,TCS,0.07,-33.02,85.44,24.20,265107.0,-152989.0,310284.0,4230.71,-44.31,46.0,X-LC,14.11,2.0,-0.58,2.02,15.71,X40,ATH,IT
45,INFY,0.39,-20.32,76.18,40.38,228519.0,-76498.0,299972.0,1972.00,-41.25,47.0,X-LC,15.84,3.0,-0.33,1.95,13.60,X40,NTT,IT
75,TMPV,0.08,-23.14,85.73,42.75,274182.0,-96287.0,319820.0,600.00,-84.91,36.0,X-LC,4.51,4.0,-0.35,2.08,9.97,XY24,NTT,AUTO
33,HCLTECH,1.65,-11.75,40.47,23.97,110530.0,-36370.0,273116.0,1853.42,-13.84,55.0,X-LC,11.09,8.0,-0.33,1.77,28.88,X40,ATH,IT

In [22]:
# top 5 for average up
df_tmp = df_portfolio_features[(df_portfolio_features['Dev%_200'] > 5)].sort_values(by = 'CurrAlloc%', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
44,INDUSINDBK,-0.00,-25.39,78.11,32.89,44994.0,-19602.0,57604.0,1800.00,324.50,51.0,L-MC,12.74,258.0,-0.44,0.37,42.02,XR,NTT,BANKS
3,ALKYLAMINE,2.86,-15.89,128.90,92.54,109468.0,-16038.0,84925.0,4520.85,NaN,63.0,NaN,14.42,142.0,-0.15,0.55,61.27,SR,ATH,CHEMICALS
12,BOSCH-HCIL,1.96,-24.04,31.63,-0.01,30709.0,-30718.0,97087.0,2282.00,759.04,77.0,M-SC,6.86,231.0,-1.00,0.63,65.26,OX40N,BTT,AC
81,VALIANTORG,0.55,-35.58,170.32,74.15,179517.0,-58205.0,105400.0,838.00,NaN,58.0,NaN,7.09,145.0,-0.32,0.68,56.85,XR,NTT,CHEMICALS
67,SIS,-0.11,-4.46,26.92,21.26,28557.0,-4952.0,106080.0,528.00,103.76,39.0,H-SC,21.59,168.0,-0.17,0.69,57.73,OX40N,NTT,MISC

In [23]:
# top 5 RSP
df_tmp = df_portfolio_features.sort_values(by = 'RSP', ascending=False)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
12,BOSCH-HCIL,1.96,-24.04,31.63,-0.01,30709.0,-30718.0,97087.0,2282.00,759.04,77.0,M-SC,6.86,231.0,-1.00,0.63,65.26,OX40N,BTT,AC
25,FINCABLES,-2.41,64.30,26.54,107.91,64382.0,94942.0,242586.0,1641.55,19.75,70.0,M-SC,20.37,220.0,1.47,1.58,82.51,OX40N,ATH,CABLES
27,GLAXO,4.30,20.48,12.63,35.69,30323.0,40804.0,240088.0,3380.16,-9.68,86.0,X-MC,9.81,56.0,1.35,1.56,42.69,X40,ATH,PHARMA
81,VALIANTORG,0.55,-35.58,170.32,74.15,179517.0,-58205.0,105400.0,838.00,NaN,58.0,NaN,7.09,145.0,-0.32,0.68,56.85,XR,NTT,CHEMICALS
38,HYUNDAI,0.47,13.60,26.70,43.94,76234.0,34187.0,285519.0,2782.73,17.53,64.0,X-LC,5.31,29.0,0.45,1.85,31.09,X40N,ATH,AUTO

In [24]:
# Top N allocation
df_tmp = df_portfolio_features.sort_values(by = 'CurrAlloc%', ascending=False)
top_n_values = [10, 25, 50]

sum_df = pd.DataFrame({
    'Top_N': top_n_values,
    'Sum_Alloc%': [df_tmp['CurrAlloc%'].head(n).sum() for n in top_n_values]
})

sum_df

   Top_N  Sum_Alloc%
0     10       19.71
1     25       45.00
2     50       77.63

In [25]:
# market-cap-wise allocation
df_tmp = df_portfolio_features[cols]
df_tmp.groupby(df_tmp['Conviction'].str[-2:])['CurrAlloc%'].sum().sort_values(ascending=False)

Conviction
LC    38.00
MC    22.27
SC    21.59
Name: CurrAlloc%, dtype: float64

In [26]:
# criteria-wise allocation
df_portfolio_features.groupby('Criteria')['CurrAlloc%'].sum().sort_values(ascending=False)

Criteria
X40      26.66
XY24     24.01
X40N     18.67
XR        9.09
OX40N     7.37
XY25      7.18
AR        6.13
SR        0.88
Name: CurrAlloc%, dtype: float64

In [27]:
# conviction-wise allocation
df_portfolio_features.groupby('Conviction')['CurrAlloc%'].sum().sort_values(ascending=False)

Conviction
X-LC    34.33
X-MC    19.65
H-SC     8.53
X-SC     7.61
M-SC     5.45
H-LC     2.86
M-MC     1.21
H-MC     1.04
M-LC     0.81
L-MC     0.37
Name: CurrAlloc%, dtype: float64

In [28]:
# sector-wise stats
df_tmp = df_portfolio_features.groupby('Category')[['CurrAlloc%', 'Current', 'Current P/L', 'FTT Amt']].sum().sort_values(by=['Current', 'Current P/L'], ascending=False)
df_tmp['Current P/L%'] = round(df_tmp['Current P/L'] * 100 / df_tmp['Current'], 2)
df_tmp['FTT%'] = round(df_tmp['FTT Amt'] * 100 / df_tmp['Current'], 2)
cols = ['CurrAlloc%', 'Current P/L%', 'FTT%']
df_tmp[cols].sort_values(by=['CurrAlloc%'], ascending=False)

               CurrAlloc%  Current P/L%    FTT%
Category
FMCG                15.38        -25.86   71.12
IT                  11.18        -38.52  107.22
FINANCE             10.82        -15.82   65.71
AUTO                 8.30         -5.83   43.74
BANKS                6.12        -13.18   61.99
MISC                 5.98        -34.18   88.16
PHARMA               5.88          8.30   17.70
INSURANCE            5.74         -5.08   42.24
PAINTS               5.48        -16.77   36.69
ELECTRICAL           4.18         -9.74   44.10
AC                   1.82        -13.78   44.64
REFINERIES           1.74        -11.22   48.58
BREWERIES            1.70         10.37    8.24
FOOTWEAR             1.66        -72.64  141.86
APPARELS             1.62         -7.70   43.08
CABLES               1.58         39.14   26.54
DURABLES             1.46        -71.43  113.14
TRAVEL               1.43       -104.13  206.35
CERAMICS             1.33        -49.33   94.69
ENGINEERING          1.24        -27.05   85.16
CHEMICALS            1.23        -39.01  151.84
CEMENT               1.00        -73.52  203.33
JEWELLERY            0.96       -117.53  193.10
HEALTHCARE           0.70        -68.59  110.91
ENTERTAINMENT        0.70        -80.40  188.00
TEXTILES             0.39        -52.95   96.56
HOTELS               0.37       -101.16  172.11

In [29]:
# money to be made criteria-wise
df_portfolio_features.groupby('Criteria')['FTT Amt'].agg(['sum', 'count']).sort_values(by='sum', ascending=False)

                sum  count
Criteria
XY24      3631448.0     19
X40       2118359.0     18
XR        1397016.0     13
X40N      1206546.0     12
AR        1063081.0      8
OX40N      657239.0     10
XY25       592005.0      5
SR         280199.0      2

In [30]:
# money to be made conviction-wise
df_portfolio_features.groupby('Conviction')['FTT Amt'].agg(['sum', 'count']).sort_values(by='sum', ascending=False)

                  sum  count
Conviction
X-LC        2437828.0     19
X-MC        1477842.0     14
X-SC        1107379.0      6
H-SC         836259.0      8
M-SC         327761.0      6
H-MC         254182.0      1
M-LC         167282.0      1
M-MC          58776.0      1
H-LC          50438.0      2
L-MC          44994.0      1

In [31]:
# money to be made criteria and conviction-wise
df_portfolio_features.groupby(['Conviction', 'Criteria'])['FTT Amt'].agg(['sum', 'count']).sort_values(by='sum', ascending=False)

                           sum  count
Conviction Criteria
X-LC       X40       1241663.0      9
X-SC       XY24       678748.0      2
H-SC       XY24       529799.0      3
X-MC       X40        508115.0      6
           X40N       463528.0      4
X-LC       XY24       459089.0      2
           X40N       418304.0      5
X-MC       XY25       276210.0      2
X-LC       XY25       257019.0      2
H-MC       XY24       254182.0      1
X-SC       X40        254164.0      2
X-MC       XY24       229989.0      2
H-SC       OX40N      211718.0      3
X-SC       X40N       174467.0      2
M-LC       XR         167282.0      1
M-SC       OX40N      151396.0      4
           XY24       118123.0      1
H-SC       XR          94742.0      2
X-LC       XR          61753.0      1
M-MC       XY25        58776.0      1
M-SC       XR          58242.0      1
H-LC       AR          50438.0      2
L-MC       XR          44994.0      1

In [32]:
# notebook execution time

end_time = time.time()
execution_time = round(end_time - start_time, 0)
print(f"Notebook execution time: {execution_time} seconds")

Notebook execution time: 29.0 seconds