<a href="https://colab.research.google.com/github/ankit-rathi/Quantvesting_v2/blob/main/myStocks_Portfolio_Analysis.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
'''
!pip install pandas==2.2.2 -qq
!pip install pyxirr -qq
!pip install ta -qq
!pip install yfinance==0.2.59 -qq
'''

'\n!pip install pandas==2.2.2 -qq\n!pip install pyxirr -qq\n!pip install ta -qq\n!pip install yfinance==0.2.59 -qq\n'

In [2]:
# import libraries

import numpy as np
import pandas as pd
import datetime
import warnings
warnings.filterwarnings('ignore')
import yfinance as yfin
import ta
import matplotlib.pyplot as plt
import requests

In [3]:
# notebook start time
import time
import datetime
import pytz

start_time = time.time()

# function to print date timestamp
def print_date_time():
  tz_NY = pytz.timezone('Asia/Kolkata')
  datetime_NY = datetime.datetime.now(tz_NY)
  print("Run date time (IST):", datetime_NY.strftime("%Y-%m-%d %H:%M:%S"))

In [4]:
# function to get booked and reserved amount
def get_amt():
  # fetch the JSON data from the URL
  url = "https://raw.githubusercontent.com/ankit-rathi/Tradevesting_v1/main/data/myPortfolioAmts.json"
  response = requests.get(url)
  pf_amts = response.json()  # parse the JSON data

  # extract values from the JSON
  py_booked_amt_dm = pf_amts["py_booked_amt_dm"]
  py_booked_amt_sv = pf_amts["py_booked_amt_sv"]
  cy_booked_amt_dm = pf_amts["cy_booked_amt_dm"]
  cy_booked_amt_sv = pf_amts["cy_booked_amt_sv"]
  reserve_amt_dm = pf_amts["reserve_amt_dm"]
  reserve_amt_sv = pf_amts["reserve_amt_sv"]

  # perform calculations
  py_booked_amt = py_booked_amt_dm + py_booked_amt_sv
  cy_booked_amt = cy_booked_amt_dm + cy_booked_amt_sv
  reserve_amt = reserve_amt_dm + reserve_amt_sv
  total_booked_amt = py_booked_amt + cy_booked_amt

  return total_booked_amt, reserve_amt, cy_booked_amt, py_booked_amt

gen_output = 0

In [5]:
# function to format the amount
def format_amt(number):
    abs_number = abs(number)

    if abs_number >= 1_00_00_000:  # Crores
        formatted_amt = f"{number / 1_00_00_000:.2f} C"
    elif abs_number >= 1_00_000:  # Lakhs
        formatted_amt = f"{number / 1_00_000:.2f} L"
    elif abs_number >= 1_000:  # Thousands
        formatted_amt = f"{number / 1_000:.2f} K"
    else:
        formatted_amt = f"{number:.2f}"

    return formatted_amt

# function to set start and end date
def get_start_end_date():
  start_date = (datetime.date.today() + datetime.timedelta(days=-365)).strftime('%Y-%m-%d')
  end_date = (datetime.date.today() + datetime.timedelta(days=1)).strftime('%Y-%m-%d')
  return start_date, end_date

# function to fetch my portfolio csv
def get_mypfs_df():
  mypfs_df = pd.read_csv('https://raw.githubusercontent.com/ankit-rathi/Tradevesting_v1/main/data/myPortfolioStocks.csv')
  return mypfs_df

# function to fetch my prospects csv
def get_mypps_df():
  mypps_df = pd.read_csv('https://raw.githubusercontent.com/ankit-rathi/Tradevesting_v1/main/data/myProspectsScrips.csv')
  return mypps_df

# function to fetch screener data
def get_myscreen_df():
  myscreen_df = pd.read_csv('https://raw.githubusercontent.com/ankit-rathi/Tradevesting_v1/main/data/myScreenerDB.csv')
  return myscreen_df

# function to fetch momentum data
def get_myinvmt_df():
  myinvmt_df = pd.read_csv('https://raw.githubusercontent.com/ankit-rathi/Tradevesting_v1/main/data/myInvestments.csv')
  return myinvmt_df

# function to get the stock ids
def get_stock_ids(df_pf):
  stock_n100 = df_pf['Symbol'].unique()

  exclude = ['CADILAHC','MMTC', 'MASFIN']

  stock_ids = df_pf[~df_pf['Symbol'].isin(exclude) ]['Symbol'].unique()

  #mypf = mypf[mypf.Forecast.notnull()]
  #stock_ids = mypf['Symbol'].unique()

  #stock_ids.sort()
  return stock_ids

# get features from screener data
def get_screener_features():
  myscreen_df = get_myscreen_df()
  cols = ['Symbol', 'EPS', 'MedPE', 'ROCE%', 'ROE%', 'CapType']
  return myscreen_df[cols]

# get relative strength
def get_relative_strength(stock_list):

    # Dictionary to store stock tickers and their corresponding percentage price change
    stock_changes = {}

    # Loop through each stock and fetch its price data
    for stock in stock_list:
        try:
            # Download the stock data for the given date range
            stock_data = yfin.Ticker(stock + '.NS').history(period='1mo', interval='1d')[map(str.title, ['open', 'close', 'low', 'high', 'volume'])]

            # Calculate the percentage change for the stock
            if len(stock_data) > 0:
                start_price = stock_data['Close'].iloc[0]
                end_price = stock_data['Close'].iloc[-1]
                percent_change = round(((end_price - start_price) / start_price) * 100, 2)
                stock_changes[stock] = percent_change
            else:
                stock_changes[stock] = np.nan  # If no data is available, set to NaN

        except Exception as e:
            print(f"Error fetching data for {stock}: {e}")
            stock_changes[stock] = np.nan

    # Create a DataFrame with stock tickers and their percentage changes
    df = pd.DataFrame(list(stock_changes.items()), columns=['Symbol', 'Percent_Change'])

    # Drop any stocks with missing data (NaN values)
    df = df.dropna()

    # Calculate the percentile rank based on percentage change
    df['RSP'] = round(df['Percent_Change'].rank(pct=True) * 100, 2)
    cols = ['Symbol', 'RSP']
    df = df[cols]
    # Sort by percentile rank (optional)
    df = df.sort_values(by='RSP', ascending=False).reset_index(drop=True)

    return df

In [6]:
# function to get stock technicals
def stock_prec_dev(stock_symbol):
    #stock_symbol = 'ULTRACEMCO.NS'
    short_window = 20
    mid_window = 50
    long_window = 200
    moving_avg = 'SMA'

    start = datetime.datetime(*map(int, start_date.split('-')))
    end = datetime.datetime(*map(int, end_date.split('-')))

    stock_df = yfin.Ticker(stock_symbol + '.NS').history(period='max', interval='1d')[map(str.title, ['open', 'close', 'low', 'high', 'volume'])]

    stock_df['Max'] = round(max(stock_df['Close']),2)
    stock_df = stock_df[(stock_df.index <= end_date) & (stock_df.index >= start_date)]
    stock_df['200_SMA'] = round(stock_df['Close'].rolling(window = 200, min_periods = 1).mean(),0)
    stock_df['Dev%_200'] = round((stock_df['Close'] - stock_df['200_SMA'])*100/stock_df['200_SMA'],2)
    stock_df.dropna(axis = 0, inplace = True) # remove any null rows

    stock_df['20_SMA'] = stock_df['Close'].rolling(window=20).mean()
    stock_df['50_SMA'] = stock_df['Close'].rolling(window=50).mean()
    stock_df['Symbol'] = stock_symbol

    stock_df['Close'] = round(stock_df['Close'],2)
    stock_df['Min'] = round(min(stock_df['Close']),2)
    stock_df['RSI_14'] = ta.momentum.RSIIndicator(close=stock_df['Close'], window=14).rsi()
    stock_df['RSI_14'] = round(stock_df['RSI_14'],0)
    stock_df['Prev_Close'] = stock_df['Close'].shift(1)
    stock_df.drop(['Open', 'Low', 'High', 'Volume'], axis=1, inplace=True)
    stock_df = stock_df.tail(1)

    max_SMA = max(stock_df['20_SMA'].item(), stock_df['50_SMA'].item(), stock_df['200_SMA'].item())
    min_SMA = min(stock_df['20_SMA'].item(), stock_df['50_SMA'].item(), stock_df['200_SMA'].item())
    ABS_Spread = max_SMA - min_SMA
    stock_df['Spread%'] = round((ABS_Spread / stock_df['200_SMA'].item()) * 100,2)

    return stock_df

# function to compute stock attributes
def get_common_features(stock_ids, df_mypf):

  df_prec_dev = pd.DataFrame()
  df_tmp = get_screener_features()
  df_rs = get_relative_strength(stock_ids)

  for stock_id in stock_ids:
      tmp = stock_prec_dev(stock_id)
      tmp = tmp.reset_index()
      df_prec_dev = pd.concat([df_prec_dev, tmp], ignore_index = True)
  df_prec_dev = pd.merge(df_prec_dev, df_mypf, on= 'Symbol')
  df_prec_dev = pd.merge(df_prec_dev, df_tmp, on= 'Symbol', how='left')
  df_prec_dev = pd.merge(df_prec_dev, df_rs, on= 'Symbol', how='left')
  #print(df_prec_dev.columns)
  df_prec_dev['Curr_PE'] = round(df_prec_dev['Close']/df_prec_dev['EPS'],1)
  df_prec_dev['Dev%_PE'] = round((df_prec_dev['Curr_PE'] - df_prec_dev['MedPE'])*100/df_prec_dev['MedPE'],2)
  df_prec_dev['Conviction'] = df_prec_dev['Conviction'] + '-' + df_prec_dev['CapType']
  return df_prec_dev

# function to arrange stock features
def arrange_features(df_stocks, common_cols, diff_cols):
  df_stocks_common = df_stocks[common_cols].drop_duplicates()
  df_stocks_diff = df_stocks[diff_cols]
  df_stocks_diff['Investment'] = df_stocks_diff['AvgCost'] * df_stocks_diff['Shares']
  df_stocks_diff = df_stocks_diff.groupby(['Symbol'])[['Shares', 'Investment']].aggregate(['sum']).reset_index()
  df_stocks_diff.columns = ['Symbol', 'Shares', 'Investment']
  df_stocks_diff['AvgCost'] = round(df_stocks_diff['Investment']/df_stocks_diff['Shares'],2)
  df_stocks = pd.merge(df_stocks_diff, df_stocks_common, on='Symbol')
  return df_stocks

# plot fact distribution across dimension
def plot_pie_chart(df, dimension, fact):
  # grouping the data by category and calculating the sum of fact for each type
  grouped_data = df.groupby(dimension)[fact].sum()

  # sorting the grouped data in descending order
  grouped_data = grouped_data.sort_values(ascending=False)

  # creating a pie chart
  grouped_data.plot.pie(autopct='%1.1f%%', startangle=90, figsize=(6, 6))

  # adding a title and displaying the plot
  plt.title(f'{dimension} {fact} Distribution')
  plt.ylabel('')  # To hide the y-label
  plt.show()

In [7]:
# function to get portfolio features

def get_portfolio_features(df_common_features):

  print_date_time()
  print('-------------------')

  #df_common_features["Target"] = df_common_features["Target"].fillna(df_common_features["Max"])
  df_common_features['NTT'] = np.where(df_common_features['Strategy']== 'NTT', df_common_features["Target"], df_common_features['Max'])
  df_common_features['LTT'] = np.where(df_common_features['Strategy']== 'BTT', df_common_features["Target"], df_common_features['Max'])
  df_common_features['BOL'] = df_common_features['Min']

  tmp_df = df_common_features[df_common_features['Symbol'].isin(mypf_df[mypf_df['InPortfolio'] != 'NA'].Symbol.values)]
  print('qualified stocks: '+str(len(tmp_df['Symbol'].unique())))
  tmp_df1 = tmp_df[tmp_df['LatestQtr'] == 1]
  print('with latest results: '+str(len(tmp_df1['Symbol'].unique())))
  tmp_df1 = tmp_df1[tmp_df1['StarStock'] == 1]
  print('still star stocks: '+str(len(tmp_df1['Symbol'].unique())))
  tmp_df['Investment'] = tmp_df['AvgCost'] * tmp_df['Shares']
  tmp_df['Current'] = round(tmp_df['Close'] * tmp_df['Shares'],0)
  tmp_df['Previous'] = tmp_df['Prev_Close'] * tmp_df['Shares']
  tmp_df['EstimatedST'] = tmp_df['NTT'] * tmp_df['Shares']
  tmp_df['EstimatedLT'] = tmp_df['LTT'] * tmp_df['Shares']
  tmp_df['Current P/L'] = round((tmp_df['Current'] - tmp_df['Investment']),0)
  tmp_df['Today P/L%'] = round((tmp_df['Current'] - tmp_df['Previous'])*100/tmp_df['Previous'],2)
  tmp_df['Current P/L%'] = round((tmp_df['Current'] - tmp_df['Investment'])*100/tmp_df['Investment'],2)
  tmp_df['EstimatedST P/L%'] = round((tmp_df['EstimatedST'] - tmp_df['Investment'])*100/tmp_df['Investment'],2)
  tmp_df['EstimatedLT P/L%'] = round((tmp_df['EstimatedLT'] - tmp_df['Investment'])*100/tmp_df['Investment'],2)
  tmp_df['NTT%'] = round((tmp_df['NTT'] - tmp_df['Close'])*100/tmp_df['Close'],2)
  tmp_df['LTT%'] = round((tmp_df['LTT'] - tmp_df['Close'])*100/tmp_df['Close'],2)
  tmp_df['Gained%'] = round((tmp_df['Close'] - tmp_df['BOL'])*100/tmp_df['BOL'],2)
  investment = round(sum(tmp_df['AvgCost']*tmp_df['Shares']),0)
  current = round(sum(tmp_df['Close']*tmp_df['Shares']),0)
  tmp_df['InitAlloc%'] = round(tmp_df['Investment']*100/investment,2)
  tmp_df['CurrAlloc%'] = round(tmp_df['Current']*100/current,2)
  tmp_df['FTT'] = tmp_df['LTT']
  tmp_df.loc[tmp_df['Strategy'] == 'NTT', 'FTT'] = tmp_df['NTT']
  tmp_df['FTT%'] = tmp_df['LTT%']
  tmp_df.loc[tmp_df['Strategy'] == 'NTT', 'FTT%'] = tmp_df['NTT%']
  tmp_df['FTT Amt'] = round(tmp_df['FTT%'] * tmp_df['Current']/100,0)
  tmp_df['OTT%'] = round((tmp_df['FTT'] - tmp_df['AvgCost'])*100/tmp_df['AvgCost'],2)
  tmp_df['RRR Ind'] = round(tmp_df['Current P/L']/tmp_df['FTT Amt'],2)
  tmp_df['Risk Ind'] = round(tmp_df['Current P/L%']*tmp_df['CurrAlloc%'],0)

  return tmp_df

# function to print portfolio features
def print_portfolio_stats(df_portfolio_features, myinvmt_df):
  from pyxirr import xirr

  total_booked_amt, reserve_amt, cy_booked_amt, py_booked_amt = get_amt()

  dates = myinvmt_df['Date'].values
  dates = np.append(dates, datetime.date.today().strftime('%d-%b-%y'))
  investment = myinvmt_df['Investment'].values
  dates= pd.to_datetime(dates)

  current = round(sum(df_portfolio_features['Close']*df_portfolio_features['Shares']),0) + reserve_amt
  investment_xirr = np.append(investment, current)
  cagr = round(xirr(pd.DataFrame({"dates": dates, "amounts": investment_xirr}))*100,2)

  investment = -sum(investment)
  invested = round(sum(df_portfolio_features['AvgCost']*df_portfolio_features['Shares']),0) + reserve_amt
  previous = round(sum(df_portfolio_features['Prev_Close']*df_portfolio_features['Shares']),0) + reserve_amt
  cy_invested = investment + py_booked_amt

  today_pnl_amount = current-previous
  today_pnl_percentage = round((current-previous)*100/previous,2)

  curr_pnl_amount = current-invested
  curr_pnl_percentage = round((curr_pnl_amount)*100/(cy_invested),2)

  cy_pnl_amount = cy_booked_amt + curr_pnl_amount
  cy_pnl_percentage = round((cy_pnl_amount)*100/cy_invested,2)

  overall_pnl_amount = total_booked_amt + curr_pnl_amount
  overall_pnl_percentage = round((overall_pnl_amount)*100/investment,2)

  estimate_st = round(sum(df_portfolio_features['FTT']*df_portfolio_features['Shares']),0)  + reserve_amt
  est_st_pnl_amount = estimate_st-current
  est_st_pnl_percentage = round((est_st_pnl_amount)*100/current,2)

  estimate_lt = round(sum(df_portfolio_features['LTT']*df_portfolio_features['Shares']),0)  + reserve_amt
  est_lt_pnl_amount = estimate_lt-current
  est_lt_pnl_percentage = round((est_lt_pnl_amount)*100/current,2)

  total_profit = round(sum(df_portfolio_features[df_portfolio_features['Current P/L%'] > 0]['Current']) - sum(df_portfolio_features[df_portfolio_features['Current P/L%'] > 0]['Investment']),0)
  total_loss = round(sum(df_portfolio_features[df_portfolio_features['Current P/L%'] < 0]['Current']) - sum(df_portfolio_features[df_portfolio_features['Current P/L%'] < 0]['Investment']),0)

  cy_booked_percentage = round((cy_booked_amt)*100/current,2)
  py_booked_percentage = round((py_booked_amt)*100/investment,2)
  total_booked_percentage = round((total_booked_amt)*100/investment,2)

  print('-------------------')
  print('Initial Investment: ', format_amt(investment))
  print('CY Investment: ', format_amt(cy_invested))
  print('Reserve: ', format_amt(reserve_amt))
  print('Current: ',  format_amt(current))
  print('-------------------')
  print('Today PnL: '+ '{} ({}%)'.format(format_amt(today_pnl_amount), today_pnl_percentage))
  print('Current PnL: '+ '{} ({}%)'.format(format_amt(curr_pnl_amount), curr_pnl_percentage))
  print('CY Booked + Current PnL: '+ '{} ({}%)'.format(format_amt(cy_pnl_amount), cy_pnl_percentage))
  print('-------------------')
  print('Total profit: ', format_amt(total_profit))
  print('Total loss: ', format_amt(total_loss))
  print('-------------------')
  print('Total Booked + Current PnL: '+ '{} ({}%)'.format(format_amt(overall_pnl_amount), overall_pnl_percentage))
  print('Total Booked PnL: '+ '{} ({}%)'.format(format_amt(total_booked_amt), total_booked_percentage))
  print('Curr Year Booked PnL: '+ '{} ({}%)'.format(format_amt(cy_booked_amt), cy_booked_percentage))
  print('Prev Year Booked PnL: '+ '{} ({}%)'.format(format_amt(py_booked_amt), py_booked_percentage))
  print('===================')
  print('Est FTT: ',  format_amt(estimate_st))
  print('Est FTT PnL: '+ '{} ({}%)'.format(format_amt(est_st_pnl_amount), est_st_pnl_percentage))

  print('===================')
  print('Deployed: ', format_amt(investment))

  print('Current: ', format_amt(current))

  print('CAGR/XIRR %: '+'{}%'.format(cagr))

In [8]:
# get start and end date
start_date, end_date = get_start_end_date()

# get portfolio and prospects data
mypfs_df = get_mypfs_df()
mypps_df = get_mypps_df()
myinvmt_df = get_myinvmt_df()

# merge above datasets
mypf_df = pd.merge(mypfs_df, mypps_df, on="Symbol")

# seggregate dm and sv portfolio
dm_pf = mypf_df[mypf_df['InPortfolio'] == 'DM']
sv_pf = mypf_df[mypf_df['InPortfolio'] == 'SV']

# build portfolio stock dataframe
dm_stocks = get_stock_ids(dm_pf)
sv_stocks = get_stock_ids(sv_pf)
df_stocks = pd.concat([dm_pf,sv_pf], ignore_index = True)

# arrange common and diff stock features
common_cols = ['Symbol', 'Target', 'Criteria', 'Strategy', 'CumlRnk', 'LatestQtr', 'StarStock', 'Conviction', 'Category', 'InFolio', 'XIRR', 'MBQ']
diff_cols = ['Symbol', 'AvgCost', 'Shares']
df_stocks = arrange_features(df_stocks, common_cols, diff_cols)

# get common features
stock_ids = df_stocks['Symbol'].values
df_common_features = get_common_features(stock_ids, df_stocks)

df_common_features.reset_index(drop=True, inplace=True)
df_common_features.drop(['Date'], axis=1, inplace=True)
# get and print portfolio features
df_portfolio_features = get_portfolio_features(df_common_features)

print_portfolio_stats(df_portfolio_features, myinvmt_df)

df = df_portfolio_features
#plot_pie_chart(df, 'CapType', 'Current')
list_ox40n = list(df[df['MBQ'].str.contains('OX40N', na=False)]['Symbol'].values)

Run date time (IST): 2026-03-09 13:57:15
-------------------
qualified stocks: 86
with latest results: 26
still star stocks: 15
-------------------
Initial Investment:  1.36 C
CY Investment:  1.62 C
Reserve:  66.25 K
Current:  1.35 C
-------------------
Today PnL: -3.13 L (-2.27%)
Current PnL: -42.34 L (-26.06%)
CY Booked + Current PnL: -26.66 L (-16.41%)
-------------------
Total profit:  89.40 K
Total loss:  -43.23 L
-------------------
Total Booked + Current PnL: 32.20 K (0.24%)
Total Booked PnL: 42.66 L (31.48%)
Curr Year Booked PnL: 15.68 L (11.65%)
Prev Year Booked PnL: 26.98 L (19.91%)
===================
Est FTT:  2.47 C
Est FTT PnL: 1.13 C (83.73%)
===================
Deployed:  1.36 C
Current:  1.35 C
CAGR/XIRR %: -0.34%

In [9]:
# top 5 near their targets
cols = ['Symbol', 'Today P/L%', 'Current P/L%', 'FTT%', 'OTT%', 'FTT Amt', 'Current P/L', 'Current', 'FTT', 'Dev%_PE', 'RSI_14','Conviction', 'Spread%',  'CumlRnk', 'RRR Ind', 'CurrAlloc%', 'Gained%', 'Criteria', 'Strategy', 'Category']
df_tmp = df_portfolio_features[~df_portfolio_features['Symbol'].isin(['ENRIN','BLUSPRING','DIGITIDE'])]
df_tmp = df_tmp.sort_values(by = 'FTT Amt', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
19,COALINDIA,-0.60,7.66,9.30,17.67,15065.0,11526.0,161986.0,478.51,29.12,57.0,L-LC,11.30,185.0,0.77,1.21,25.79,XY25,ATH,MINING
50,MASFIN,-1.69,-9.43,34.23,21.57,30376.0,-9240.0,88740.0,397.04,-21.86,32.0,H-SC,5.37,167.0,-0.30,0.66,23.82,XR,ATH,FINANCE
37,ICICIGI,-0.35,-0.74,20.23,19.34,40181.0,-1486.0,198623.0,2252.93,-16.40,45.0,X-MC,1.55,66.0,-0.04,1.48,13.28,X40,ATH,INSURANCE
77,TTKPRESTIG,-2.88,-40.80,69.08,0.09,41211.0,-41120.0,59657.0,770.00,38.53,17.0,M-SC,14.26,250.0,-1.00,0.45,0.00,OX40N,NTT,DURABLES
2,ABBOTINDIA,-0.46,-8.75,29.39,18.07,47964.0,-15655.0,163200.0,35195.00,-22.40,52.0,X-MC,11.09,58.0,-0.33,1.22,3.46,X40,ATH,PHARMA

In [10]:
# top 5 today
df_tmp = df_portfolio_features.sort_values(by = 'Today P/L%', ascending=False)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
40,INDIAMART,2.25,-6.83,121.87,106.72,140047.0,-8421.0,114915.0,4810.62,-58.01,49.0,H-SC,8.87,140.0,-0.06,0.86,14.95,AR,ATH,MISC
65,SIEMENS,1.65,-12.17,42.91,25.51,70134.0,-22650.0,163445.0,4671.50,37.32,54.0,H-LC,3.38,51.0,-0.32,1.22,20.36,AR,ATH,ELECTRICAL
70,SYMPHONY,1.40,-41.41,70.63,-0.03,70819.0,-70874.0,100267.0,1306.00,-52.91,30.0,M-SC,12.05,205.0,-1.00,0.75,1.40,OX40N,NTT,DURABLES
25,DMART,1.04,-5.86,37.67,29.60,88512.0,-14634.0,234966.0,5391.45,-20.59,56.0,X-LC,7.72,14.0,-0.17,1.75,8.67,X40N,ATH,FMCG
84,WIPRO,0.55,-19.41,113.76,72.27,155344.0,-32894.0,136554.0,420.00,-27.37,23.0,M-LC,13.32,98.0,-0.21,1.02,0.55,XR,NTT,IT

In [11]:
# bottom 5 today
df_tmp = df_portfolio_features.sort_values(by = 'Today P/L%', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
75,TMPV,-6.00,-24.95,81.98,36.58,218933.0,-88784.0,267057.0,600.0,-84.72,30.0,X-LC,2.66,4.0,-0.41,1.99,0.00,XY24,NTT,AUTO
11,BANDHANBNK,-5.23,-16.56,130.60,92.42,303561.0,-46123.0,232436.0,400.0,99.71,53.0,H-SC,9.82,174.0,-0.15,1.74,28.04,XY24,NTT,BANKS
7,ATULAUTO,-5.22,-27.22,100.02,45.57,143492.0,-53669.0,143463.0,844.0,3094.59,37.0,M-SC,7.28,248.0,-0.37,1.07,8.57,XY24,NTT,AUTO
57,RECLTD,-5.06,-12.83,38.51,20.74,68201.0,-26070.0,177100.0,446.0,-4.30,33.0,M-MC,4.56,191.0,-0.38,1.32,0.00,XY25,NTT,FINANCE
55,RAJESHEXPO,-5.00,-78.18,358.61,0.07,107339.0,-107245.0,29932.0,518.0,997.22,18.0,L-SC,15.34,268.0,-1.00,0.22,0.00,OX40N,NTT,JEWELLERY

In [12]:
# top 5 to exit based on CumlRnk
df_tmp = df_portfolio_features[~df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])]
df_tmp = df_tmp[(df_tmp['Current P/L%'] > -1) & (df_tmp['Current P/L%'] < 1)].sort_values(by = 'CumlRnk', ascending=False)
df_tmp[cols].head()

Empty DataFrame
Columns: [Symbol, Today P/L%, Current P/L%, FTT%, OTT%, FTT Amt, Current P/L, Current, FTT, Dev%_PE, RSI_14, Conviction, Spread%, CumlRnk, RRR Ind, CurrAlloc%, Gained%, Criteria, Strategy, Category]
Index: []

In [13]:
# OX40N stocks to exit
df_tmp = df_portfolio_features[(df_portfolio_features['Symbol'].isin(list_ox40n))].sort_values(by = 'Current P/L%', ascending=False)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
27,FINCABLES,-1.49,20.89,71.99,107.91,128489.0,30838.0,178482.0,1641.55,8.57,68.0,M-SC,7.19,220.0,0.24,1.33,34.28,OX40N,ATH,CABLES
66,SIS,-3.83,-34.20,84.29,21.26,61581.0,-37974.0,73058.0,528.00,1710.36,32.0,H-SC,8.36,168.0,-0.62,0.55,0.72,OX40N,NTT,MISC
48,KANSAINER,-2.53,-38.45,84.37,13.47,140028.0,-103698.0,165969.0,340.00,-47.05,23.0,H-SC,15.62,162.0,-0.74,1.24,0.00,XY24,NTT,PAINTS
72,TATAELXSI,-1.87,-38.76,115.59,32.03,93324.0,-51098.0,80737.0,9161.00,-23.39,25.0,H-SC,15.19,158.0,-0.55,0.60,0.00,OX40N,NTT,IT
18,CERA,-4.25,-40.63,108.66,23.89,113486.0,-71462.0,104441.0,9475.00,-42.72,23.0,H-SC,15.67,153.0,-0.63,0.78,0.00,OX40N,NTT,CERAMICS

In [14]:
# top 5 to book for rotation
df_tmp = df_portfolio_features[(df_portfolio_features['Current P/L%'] > 20) ].sort_values(by = 'CumlRnk', ascending=False)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
27,FINCABLES,-1.49,20.89,71.99,107.91,128489.0,30838.0,178482.0,1641.55,8.57,68.0,M-SC,7.19,220.0,0.24,1.33,34.28,OX40N,ATH,CABLES

In [15]:
# top 5 to monitor for exit
df_tmp = df_portfolio_features[~df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])]
df_tmp = df_tmp[(df_tmp['Current P/L%'] > 0) ].sort_values(by = 'Dev%_PE', ascending=False)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
19,COALINDIA,-0.60,7.66,9.30,17.67,15065.0,11526.0,161986.0,478.51,29.12,57.0,L-LC,11.30,185.0,0.77,1.21,25.79,XY25,ATH,MINING
27,FINCABLES,-1.49,20.89,71.99,107.91,128489.0,30838.0,178482.0,1641.55,8.57,68.0,M-SC,7.19,220.0,0.24,1.33,34.28,OX40N,ATH,CABLES
1,ABB,-2.15,8.83,33.76,45.57,96119.0,23093.0,284712.0,7934.00,-30.02,55.0,H-MC,9.33,125.0,0.24,2.13,26.43,AR,NTT,ELECTRICAL

In [16]:
# top 5 to book for rotation from weak conviction
df_tmp = df_portfolio_features[~df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])]
df_tmp = df_tmp[~df_tmp['Criteria'].isin(['XY25','XY24','X40', 'X40N'])].sort_values(by = 'RRR Ind', ascending=False)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
1,ABB,-2.15,8.83,33.76,45.57,96119.0,23093.0,284712.0,7934.00,-30.02,55.0,H-MC,9.33,125.0,0.24,2.13,26.43,AR,NTT,ELECTRICAL
27,FINCABLES,-1.49,20.89,71.99,107.91,128489.0,30838.0,178482.0,1641.55,8.57,68.0,M-SC,7.19,220.0,0.24,1.33,34.28,OX40N,ATH,CABLES
40,INDIAMART,2.25,-6.83,121.87,106.72,140047.0,-8421.0,114915.0,4810.62,-58.01,49.0,H-SC,8.87,140.0,-0.06,0.86,14.95,AR,ATH,MISC
85,ZYDUSLIFE,-0.95,-4.63,42.22,35.63,84381.0,-9713.0,199861.0,1286.17,-17.12,49.0,H-MC,5.12,120.0,-0.12,1.49,11.26,AR,ATH,PHARMA
84,WIPRO,0.55,-19.41,113.76,72.27,155344.0,-32894.0,136554.0,420.00,-27.37,23.0,M-LC,13.32,98.0,-0.21,1.02,0.55,XR,NTT,IT

In [17]:
# top 5 to accumulate based on lowest RSI_14
df_tmp = df_portfolio_features[df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])].sort_values(by = 'RSI_14', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
8,AWL,-0.99,-39.57,176.37,67.02,379770.0,-140983.0,215326.0,485.00,-67.43,11.0,X-SC,21.77,81.0,-0.37,1.61,0.00,XY24,NTT,FMCG
53,PGHH,-2.72,-20.65,66.37,32.01,112447.0,-44096.0,169424.0,17616.87,-46.32,13.0,X-MC,10.60,57.0,-0.39,1.27,0.00,X40,ATH,FMCG
3,ACC,-3.64,-35.26,170.03,74.81,295138.0,-94548.0,173580.0,3906.00,-53.87,16.0,X-SC,11.18,85.0,-0.32,1.30,0.00,XY24,BTT,CEMENT
12,BATAINDIA,-3.73,-53.81,192.74,35.20,114542.0,-69242.0,59428.0,2096.00,-22.02,20.0,X-SC,24.19,91.0,-0.60,0.44,0.00,X40,NTT,FOOTWEAR
46,JIOFIN,-4.14,-23.86,68.66,28.43,155965.0,-71171.0,227156.0,387.00,-25.03,21.0,X-LC,13.91,34.0,-0.46,1.70,7.63,XY24,BTT,FINANCE

In [18]:
# top 5 to accumulate based on Spread and CumlRnk
df_tmp = df_portfolio_features[df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])]
df_tmp = df_tmp[(df_tmp['CumlRnk'] < 100)].sort_values(by = 'Spread%', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
22,DABUR,-2.71,-8.96,57.84,43.70,130626.0,-22228.0,225840.0,735.00,-17.44,27.0,X-MC,0.96,70.0,-0.17,1.69,4.74,XY24,BTT,FMCG
78,UNITDSPR,-3.30,-1.27,22.32,20.77,51597.0,-2976.0,231168.0,1644.00,-12.48,44.0,X-MC,1.51,64.0,-0.06,1.73,5.35,X40N,NTT,BREWERIES
37,ICICIGI,-0.35,-0.74,20.23,19.34,40181.0,-1486.0,198623.0,2252.93,-16.40,45.0,X-MC,1.55,66.0,-0.04,1.48,13.28,X40,ATH,INSURANCE
59,RELIANCE,0.27,-9.58,38.58,25.30,70103.0,-19254.0,181709.0,1952.00,-11.96,48.0,X-LC,2.11,21.0,-0.27,1.36,21.32,XY25,BTT,REFINERIES
75,TMPV,-6.00,-24.95,81.98,36.58,218933.0,-88784.0,267057.0,600.00,-84.72,30.0,X-LC,2.66,4.0,-0.41,1.99,0.00,XY24,NTT,AUTO

In [19]:
# top 5 to accumulate based on lowest Gained%
df_tmp = df_portfolio_features[df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])].sort_values(by = 'Gained%', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
3,ACC,-3.64,-35.26,170.03,74.81,295138.0,-94548.0,173580.0,3906.00,-53.87,16.0,X-SC,11.18,85.0,-0.32,1.30,0.0,XY24,BTT,CEMENT
10,BAJAJHLDNG,-3.14,-8.55,41.29,29.22,71793.0,-16249.0,173876.0,14451.52,-15.20,31.0,X-LC,11.90,28.0,-0.23,1.30,0.0,X40,ATH,FINANCE
9,BAJAJHFL,-2.35,-26.61,120.91,62.13,242289.0,-72658.0,200388.0,181.50,-39.53,21.0,X-MC,18.06,60.0,-0.30,1.50,0.0,X40N,ATH,FINANCE
8,AWL,-0.99,-39.57,176.37,67.02,379770.0,-140983.0,215326.0,485.00,-67.43,11.0,X-SC,21.77,81.0,-0.37,1.61,0.0,XY24,NTT,FMCG
12,BATAINDIA,-3.73,-53.81,192.74,35.20,114542.0,-69242.0,59428.0,2096.00,-22.02,20.0,X-SC,24.19,91.0,-0.60,0.44,0.0,X40,NTT,FOOTWEAR

In [20]:
# top 5 to accumulate based on lowest CurrAlloc%
df_tmp = df_portfolio_features[df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])].sort_values(by = 'CurrAlloc%', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
12,BATAINDIA,-3.73,-53.81,192.74,35.20,114542.0,-69242.0,59428.0,2096.00,-22.02,20.0,X-SC,24.19,91.0,-0.60,0.44,0.00,X40,NTT,FOOTWEAR
58,RELAXO,-2.97,-59.56,276.62,52.31,162384.0,-86457.0,58703.0,1176.00,-56.93,21.0,X-SC,17.56,92.0,-0.53,0.44,0.00,X40N,NTT,FOOTWEAR
54,QUESS,-2.49,-24.10,129.13,73.90,104662.0,-25741.0,81052.0,424.00,-59.23,32.0,X-SC,17.67,80.0,-0.25,0.61,0.00,XY24,NTT,MISC
36,HONAUT,-0.98,-23.07,96.69,51.31,143440.0,-44488.0,148350.0,58357.33,-36.07,29.0,X-SC,13.35,90.0,-0.31,1.11,0.00,X40N,ATH,ELECTRICAL
51,MEDANTA,-2.25,-7.18,36.95,27.12,60543.0,-12667.0,163850.0,1486.00,-9.96,39.0,X-SC,8.34,87.0,-0.21,1.22,5.35,XY24,NTT,HEALTHCARE

In [21]:
# top 5 to accumulate based on CumlRnk
df_tmp = df_portfolio_features.sort_values(by = 'CumlRnk', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
45,ITC,-1.60,-19.73,48.32,19.06,131941.0,-67110.0,273056.0,452.00,-55.92,32.0,X-LC,16.98,1.0,-0.51,2.04,0.00,X40,NTT,FMCG
73,TCS,-1.57,-26.10,71.26,26.57,243980.0,-120893.0,342380.0,4311.59,-37.40,24.0,X-LC,12.54,2.0,-0.50,2.56,0.00,X40,ATH,IT
43,INFY,-0.39,-11.28,51.31,34.24,142438.0,-35285.0,277603.0,1972.00,-30.33,28.0,X-LC,10.89,3.0,-0.25,2.07,2.18,X40,NTT,IT
75,TMPV,-6.00,-24.95,81.98,36.58,218933.0,-88784.0,267057.0,600.00,-84.72,30.0,X-LC,2.66,4.0,-0.41,1.99,0.00,XY24,NTT,AUTO
34,HCLTECH,-0.22,-12.15,40.96,23.83,87053.0,-29393.0,212531.0,1908.19,-7.78,27.0,X-LC,8.70,8.0,-0.34,1.59,1.97,X40,ATH,IT

In [22]:
# top 5 for average up
df_tmp = df_portfolio_features[(df_portfolio_features['Dev%_200'] > 5)].sort_values(by = 'CurrAlloc%', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
42,INDUSINDBK,-4.64,-35.38,105.66,32.89,52713.0,-27318.0,49889.0,1800.00,-334.59,36.0,L-MC,11.86,258.0,-0.52,0.37,37.39,XR,NTT,BANKS
19,COALINDIA,-0.60,7.66,9.30,17.67,15065.0,11526.0,161986.0,478.51,29.12,57.0,L-LC,11.30,185.0,0.77,1.21,25.79,XY25,ATH,MINING
27,FINCABLES,-1.49,20.89,71.99,107.91,128489.0,30838.0,178482.0,1641.55,8.57,68.0,M-SC,7.19,220.0,0.24,1.33,34.28,OX40N,ATH,CABLES
11,BANDHANBNK,-5.23,-16.56,130.60,92.42,303561.0,-46123.0,232436.0,400.00,99.71,53.0,H-SC,9.82,174.0,-0.15,1.74,28.04,XY24,NTT,BANKS
1,ABB,-2.15,8.83,33.76,45.57,96119.0,23093.0,284712.0,7934.00,-30.02,55.0,H-MC,9.33,125.0,0.24,2.13,26.43,AR,NTT,ELECTRICAL

In [23]:
# top 5 RSP
df_tmp = df_portfolio_features.sort_values(by = 'RSP', ascending=False)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
27,FINCABLES,-1.49,20.89,71.99,107.91,128489.0,30838.0,178482.0,1641.55,8.57,68.0,M-SC,7.19,220.0,0.24,1.33,34.28,OX40N,ATH,CABLES
11,BANDHANBNK,-5.23,-16.56,130.60,92.42,303561.0,-46123.0,232436.0,400.00,99.71,53.0,H-SC,9.82,174.0,-0.15,1.74,28.04,XY24,NTT,BANKS
26,EASEMYTRIP,-3.87,-60.26,266.67,45.70,187357.0,-106557.0,70258.0,26.40,-27.06,41.0,M-SC,18.16,204.0,-0.57,0.52,15.76,XY24,NTT,TRAVEL
65,SIEMENS,1.65,-12.17,42.91,25.51,70134.0,-22650.0,163445.0,4671.50,37.32,54.0,H-LC,3.38,51.0,-0.32,1.22,20.36,AR,ATH,ELECTRICAL
19,COALINDIA,-0.60,7.66,9.30,17.67,15065.0,11526.0,161986.0,478.51,29.12,57.0,L-LC,11.30,185.0,0.77,1.21,25.79,XY25,ATH,MINING

In [24]:
# Top N allocation
df_tmp = df_portfolio_features.sort_values(by = 'CurrAlloc%', ascending=False)
top_n_values = [10, 25, 50]

sum_df = pd.DataFrame({
    'Top_N': top_n_values,
    'Sum_Alloc%': [df_tmp['CurrAlloc%'].head(n).sum() for n in top_n_values]
})

sum_df

   Top_N  Sum_Alloc%
0     10       20.56
1     25       45.40
2     50       78.01

In [25]:
# market-cap-wise allocation
df_tmp = df_portfolio_features[cols]
df_tmp.groupby(df_tmp['Conviction'].str[-2:])['CurrAlloc%'].sum().sort_values(ascending=False)

Conviction
SC    44.41
MC    30.39
LC    25.21
Name: CurrAlloc%, dtype: float64

In [26]:
# criteria-wise allocation
df_portfolio_features.groupby('Criteria')['CurrAlloc%'].sum().sort_values(ascending=False)

Criteria
XY24     27.14
X40      24.09
X40N     15.10
AR        9.06
XY25      8.73
XR        8.20
OX40N     6.91
SR        0.78
Name: CurrAlloc%, dtype: float64

In [27]:
# conviction-wise allocation
df_portfolio_features.groupby('Conviction')['CurrAlloc%'].sum().sort_values(ascending=False)

Conviction
X-MC    23.12
X-LC    21.76
H-SC    21.47
X-SC    12.15
M-SC    10.20
H-MC     4.93
M-MC     1.97
H-LC     1.22
L-LC     1.21
M-LC     1.02
L-SC     0.59
L-MC     0.37
Name: CurrAlloc%, dtype: float64

In [28]:
# sector-wise stats
df_tmp = df_portfolio_features.groupby('Category')[['CurrAlloc%', 'Current', 'Current P/L', 'FTT Amt']].sum().sort_values(by=['Current', 'Current P/L'], ascending=False)
df_tmp['Current P/L%'] = round(df_tmp['Current P/L'] * 100 / df_tmp['Current'], 2)
df_tmp['FTT%'] = round(df_tmp['FTT Amt'] * 100 / df_tmp['Current'], 2)
cols = ['CurrAlloc%', 'Current P/L%', 'FTT%']
df_tmp[cols].sort_values(by=['CurrAlloc%'], ascending=False)

               CurrAlloc%  Current P/L%    FTT%
Category
FMCG                15.46        -20.74   63.61
FINANCE             12.74        -25.90   77.21
IT                  11.67        -44.18  117.55
MISC                 6.94        -44.47  107.22
ELECTRICAL           6.53        -10.89   53.35
PAINTS               5.22        -40.96   65.44
INSURANCE            4.73         -6.80   43.35
PHARMA               4.21         -4.33   37.17
AUTO                 3.71        -31.46   83.62
BANKS                3.10        -29.00  107.16
AC                   2.14        -11.19   41.33
HEALTHCARE           1.97        -35.61   71.00
FOOTWEAR             1.89        -74.05  143.84
TRAVEL               1.83        -82.28  173.55
DURABLES             1.79        -61.60  100.91
BREWERIES            1.73         -1.29   22.32
APPARELS             1.62        -23.42   65.52
REALTY               1.46        -13.04   31.61
REFINERIES           1.36        -10.60   38.58
CERAMICS             1.34        -70.84  122.75
CABLES               1.33         17.28   71.99
CEMENT               1.30        -54.47  170.03
MINING               1.21          7.12    9.30
JEWELLERY            1.11       -114.96  189.64
ENGINEERING          1.10        -63.68  138.54
CHEMICALS            0.96       -107.34  276.50
ENTERTAINMENT        0.77        -87.94  200.04
TEXTILES             0.42        -63.17  109.70
HOTELS               0.37       -128.51  209.12

In [29]:
# money to be made criteria-wise
df_portfolio_features.groupby('Criteria')['FTT Amt'].agg(['sum', 'count']).sort_values(by='sum', ascending=False)

                sum  count
Criteria
XY24      3962686.0     21
X40       1647974.0     15
XR        1392176.0     12
AR        1358168.0     10
X40N      1279988.0     10
OX40N      865656.0     10
XY25       447679.0      6
SR         315218.0      2

In [30]:
# money to be made conviction-wise
df_portfolio_features.groupby('Conviction')['FTT Amt'].agg(['sum', 'count']).sort_values(by='sum', ascending=False)

                  sum  count
Conviction
H-SC        3916006.0     24
X-MC        1638609.0     15
X-LC        1561579.0     12
X-SC        1557307.0     10
M-SC        1550651.0     14
H-MC         419046.0      3
L-SC         211251.0      2
M-LC         155344.0      1
M-MC         121840.0      2
H-LC          70134.0      1
L-MC          52713.0      1
L-LC          15065.0      1

In [31]:
# money to be made criteria and conviction-wise
df_portfolio_features.groupby(['Conviction', 'Criteria'])['FTT Amt'].agg(['sum', 'count']).sort_values(by='sum', ascending=False)

                           sum  count
Conviction Criteria
H-SC       XY24      1343944.0      6
           AR         976502.0      5
M-SC       XY24       915076.0      6
H-SC       XR         888729.0      7
X-SC       XY24       840113.0      4
X-LC       X40        804060.0      6
X-MC       X40        637851.0      7
           X40N       529908.0      4
X-SC       X40N       511131.0      4
H-SC       OX40N      391613.0      4
X-LC       XY24       374898.0      2
M-SC       OX40N      366704.0      5
H-SC       SR         315218.0      2
X-MC       XY24       250109.0      2
X-LC       X40N       238949.0      2
H-MC       XY24       238546.0      1
X-MC       XY25       220741.0      2
X-SC       X40        206063.0      2
M-SC       XR         191478.0      2
H-MC       AR         180500.0      2
M-LC       XR         155344.0      1
X-LC       XY25       143672.0      2
L-SC       OX40N      107339.0      1
           XR         103912.0      1
M-SC       AR          77393.0      1
H-LC       AR          70134.0      1
M-MC       XY25        68201.0      1
           AR          53639.0      1
L-MC       XR          52713.0      1
L-LC       XY25        15065.0      1

In [32]:
# notebook execution time

end_time = time.time()
execution_time = round(end_time - start_time, 0)
print(f"Notebook execution time: {execution_time} seconds")

Notebook execution time: 24.0 seconds