<a href="https://colab.research.google.com/github/ankit-rathi/Quantvesting_v2/blob/main/myStocks_Portfolio_Analysis.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
'''
!pip install pandas==2.2.2 -qq
!pip install pyxirr -qq
!pip install ta -qq
!pip install yfinance==0.2.59 -qq
'''

'\n!pip install pandas==2.2.2 -qq\n!pip install pyxirr -qq\n!pip install ta -qq\n!pip install yfinance==0.2.59 -qq\n'

In [2]:
# import libraries

import numpy as np
import pandas as pd
import datetime
import warnings
warnings.filterwarnings('ignore')
import yfinance as yfin
import ta
import matplotlib.pyplot as plt
import requests

In [3]:
# notebook start time
import time
import datetime
import pytz

start_time = time.time()

# function to print date timestamp
def print_date_time():
  tz_NY = pytz.timezone('Asia/Kolkata')
  datetime_NY = datetime.datetime.now(tz_NY)
  print("Run date time (IST):", datetime_NY.strftime("%Y-%m-%d %H:%M:%S"))

In [4]:
# function to get booked and reserved amount
def get_amt():
  # fetch the JSON data from the URL
  url = "https://raw.githubusercontent.com/ankit-rathi/Tradevesting_v1/main/data/myPortfolioAmts.json"
  response = requests.get(url)
  pf_amts = response.json()  # parse the JSON data

  # extract values from the JSON
  py_booked_amt_dm = pf_amts["py_booked_amt_dm"]
  py_booked_amt_sv = pf_amts["py_booked_amt_sv"]
  cy_booked_amt_dm = pf_amts["cy_booked_amt_dm"]
  cy_booked_amt_sv = pf_amts["cy_booked_amt_sv"]
  reserve_amt_dm = pf_amts["reserve_amt_dm"]
  reserve_amt_sv = pf_amts["reserve_amt_sv"]

  # perform calculations
  py_booked_amt = py_booked_amt_dm + py_booked_amt_sv
  cy_booked_amt = cy_booked_amt_dm + cy_booked_amt_sv
  reserve_amt = reserve_amt_dm + reserve_amt_sv
  total_booked_amt = py_booked_amt + cy_booked_amt

  return total_booked_amt, reserve_amt, cy_booked_amt, py_booked_amt

gen_output = 0

In [5]:
# function to format the amount
def format_amt(number):
    abs_number = abs(number)

    if abs_number >= 1_00_00_000:  # Crores
        formatted_amt = f"{number / 1_00_00_000:.2f} C"
    elif abs_number >= 1_00_000:  # Lakhs
        formatted_amt = f"{number / 1_00_000:.2f} L"
    elif abs_number >= 1_000:  # Thousands
        formatted_amt = f"{number / 1_000:.2f} K"
    else:
        formatted_amt = f"{number:.2f}"

    return formatted_amt

# function to set start and end date
def get_start_end_date():
  start_date = (datetime.date.today() + datetime.timedelta(days=-365)).strftime('%Y-%m-%d')
  end_date = (datetime.date.today() + datetime.timedelta(days=1)).strftime('%Y-%m-%d')
  return start_date, end_date

# function to fetch my portfolio csv
def get_mypfs_df():
  mypfs_df = pd.read_csv('https://raw.githubusercontent.com/ankit-rathi/Tradevesting_v1/main/data/myPortfolioStocks.csv')
  return mypfs_df

# function to fetch my prospects csv
def get_mypps_df():
  mypps_df = pd.read_csv('https://raw.githubusercontent.com/ankit-rathi/Tradevesting_v1/main/data/myProspectsScrips.csv')
  return mypps_df

# function to fetch screener data
def get_myscreen_df():
  myscreen_df = pd.read_csv('https://raw.githubusercontent.com/ankit-rathi/Tradevesting_v1/main/data/myScreenerDB.csv')
  return myscreen_df

# function to fetch momentum data
def get_myinvmt_df():
  myinvmt_df = pd.read_csv('https://raw.githubusercontent.com/ankit-rathi/Tradevesting_v1/main/data/myInvestments.csv')
  return myinvmt_df

# function to get the stock ids
def get_stock_ids(df_pf):
  stock_n100 = df_pf['Symbol'].unique()

  exclude = ['CADILAHC','MMTC', 'MASFIN']

  stock_ids = df_pf[~df_pf['Symbol'].isin(exclude) ]['Symbol'].unique()

  #mypf = mypf[mypf.Forecast.notnull()]
  #stock_ids = mypf['Symbol'].unique()

  #stock_ids.sort()
  return stock_ids

# get features from screener data
def get_screener_features():
  myscreen_df = get_myscreen_df()
  cols = ['Symbol', 'EPS', 'MedPE', 'ROCE%', 'ROE%', 'CapType']
  return myscreen_df[cols]

# get relative strength
def get_relative_strength(stock_list):

    # Dictionary to store stock tickers and their corresponding percentage price change
    stock_changes = {}

    # Loop through each stock and fetch its price data
    for stock in stock_list:
        try:
            # Download the stock data for the given date range
            stock_data = yfin.Ticker(stock + '.NS').history(period='1mo', interval='1d')[map(str.title, ['open', 'close', 'low', 'high', 'volume'])]

            # Calculate the percentage change for the stock
            if len(stock_data) > 0:
                start_price = stock_data['Close'].iloc[0]
                end_price = stock_data['Close'].iloc[-1]
                percent_change = round(((end_price - start_price) / start_price) * 100, 2)
                stock_changes[stock] = percent_change
            else:
                stock_changes[stock] = np.nan  # If no data is available, set to NaN

        except Exception as e:
            print(f"Error fetching data for {stock}: {e}")
            stock_changes[stock] = np.nan

    # Create a DataFrame with stock tickers and their percentage changes
    df = pd.DataFrame(list(stock_changes.items()), columns=['Symbol', 'Percent_Change'])

    # Drop any stocks with missing data (NaN values)
    df = df.dropna()

    # Calculate the percentile rank based on percentage change
    df['RSP'] = round(df['Percent_Change'].rank(pct=True) * 100, 2)
    cols = ['Symbol', 'RSP']
    df = df[cols]
    # Sort by percentile rank (optional)
    df = df.sort_values(by='RSP', ascending=False).reset_index(drop=True)

    return df

In [6]:
# function to get stock technicals
def stock_prec_dev(stock_symbol):
    #stock_symbol = 'ULTRACEMCO.NS'
    short_window = 20
    mid_window = 50
    long_window = 200
    moving_avg = 'SMA'

    start = datetime.datetime(*map(int, start_date.split('-')))
    end = datetime.datetime(*map(int, end_date.split('-')))

    stock_df = yfin.Ticker(stock_symbol + '.NS').history(period='max', interval='1d')[map(str.title, ['open', 'close', 'low', 'high', 'volume'])]

    stock_df['Max'] = round(max(stock_df['Close']),2)
    stock_df = stock_df[(stock_df.index <= end_date) & (stock_df.index >= start_date)]
    stock_df['200_SMA'] = round(stock_df['Close'].rolling(window = 200, min_periods = 1).mean(),0)
    stock_df['Dev%_200'] = round((stock_df['Close'] - stock_df['200_SMA'])*100/stock_df['200_SMA'],2)
    stock_df.dropna(axis = 0, inplace = True) # remove any null rows

    stock_df['20_SMA'] = stock_df['Close'].rolling(window=20).mean()
    stock_df['50_SMA'] = stock_df['Close'].rolling(window=50).mean()
    stock_df['Symbol'] = stock_symbol

    stock_df['Close'] = round(stock_df['Close'],2)
    stock_df['Min'] = round(min(stock_df['Close']),2)
    stock_df['RSI_14'] = ta.momentum.RSIIndicator(close=stock_df['Close'], window=14).rsi()
    stock_df['RSI_14'] = round(stock_df['RSI_14'],0)
    stock_df['Prev_Close'] = stock_df['Close'].shift(1)
    stock_df.drop(['Open', 'Low', 'High', 'Volume'], axis=1, inplace=True)
    stock_df = stock_df.tail(1)

    max_SMA = max(stock_df['20_SMA'].item(), stock_df['50_SMA'].item(), stock_df['200_SMA'].item())
    min_SMA = min(stock_df['20_SMA'].item(), stock_df['50_SMA'].item(), stock_df['200_SMA'].item())
    ABS_Spread = max_SMA - min_SMA
    stock_df['Spread%'] = round((ABS_Spread / stock_df['200_SMA'].item()) * 100,2)

    return stock_df

# function to compute stock attributes
def get_common_features(stock_ids, df_mypf):

  df_prec_dev = pd.DataFrame()
  df_tmp = get_screener_features()
  df_rs = get_relative_strength(stock_ids)

  for stock_id in stock_ids:
      tmp = stock_prec_dev(stock_id)
      tmp = tmp.reset_index()
      df_prec_dev = pd.concat([df_prec_dev, tmp], ignore_index = True)
  df_prec_dev = pd.merge(df_prec_dev, df_mypf, on= 'Symbol')
  df_prec_dev = pd.merge(df_prec_dev, df_tmp, on= 'Symbol', how='left')
  df_prec_dev = pd.merge(df_prec_dev, df_rs, on= 'Symbol', how='left')
  #print(df_prec_dev.columns)
  df_prec_dev['Curr_PE'] = round(df_prec_dev['Close']/df_prec_dev['EPS'],1)
  df_prec_dev['Dev%_PE'] = round((df_prec_dev['Curr_PE'] - df_prec_dev['MedPE'])*100/df_prec_dev['MedPE'],2)
  df_prec_dev['Conviction'] = df_prec_dev['Conviction'] + '-' + df_prec_dev['CapType']
  return df_prec_dev

# function to arrange stock features
def arrange_features(df_stocks, common_cols, diff_cols):
  df_stocks_common = df_stocks[common_cols].drop_duplicates()
  df_stocks_diff = df_stocks[diff_cols]
  df_stocks_diff['Investment'] = df_stocks_diff['AvgCost'] * df_stocks_diff['Shares']
  df_stocks_diff = df_stocks_diff.groupby(['Symbol'])[['Shares', 'Investment']].aggregate(['sum']).reset_index()
  df_stocks_diff.columns = ['Symbol', 'Shares', 'Investment']
  df_stocks_diff['AvgCost'] = round(df_stocks_diff['Investment']/df_stocks_diff['Shares'],2)
  df_stocks = pd.merge(df_stocks_diff, df_stocks_common, on='Symbol')
  return df_stocks

# plot fact distribution across dimension
def plot_pie_chart(df, dimension, fact):
  # grouping the data by category and calculating the sum of fact for each type
  grouped_data = df.groupby(dimension)[fact].sum()

  # sorting the grouped data in descending order
  grouped_data = grouped_data.sort_values(ascending=False)

  # creating a pie chart
  grouped_data.plot.pie(autopct='%1.1f%%', startangle=90, figsize=(6, 6))

  # adding a title and displaying the plot
  plt.title(f'{dimension} {fact} Distribution')
  plt.ylabel('')  # To hide the y-label
  plt.show()

In [7]:
# function to get portfolio features

def get_portfolio_features(df_common_features):

  print_date_time()
  print('-------------------')

  #df_common_features["Target"] = df_common_features["Target"].fillna(df_common_features["Max"])
  df_common_features['NTT'] = np.where(df_common_features['Strategy']== 'NTT', df_common_features["Target"], df_common_features['Max'])
  df_common_features['LTT'] = np.where(df_common_features['Strategy']== 'BTT', df_common_features["Target"], df_common_features['Max'])
  df_common_features['BOL'] = df_common_features['Min']

  tmp_df = df_common_features[df_common_features['Symbol'].isin(mypf_df[mypf_df['InPortfolio'] != 'NA'].Symbol.values)]
  print('qualified stocks: '+str(len(tmp_df['Symbol'].unique())))
  tmp_df1 = tmp_df[tmp_df['LatestQtr'] == 1]
  print('with latest results: '+str(len(tmp_df1['Symbol'].unique())))
  tmp_df1 = tmp_df1[tmp_df1['StarStock'] == 1]
  print('still star stocks: '+str(len(tmp_df1['Symbol'].unique())))
  tmp_df['Investment'] = tmp_df['AvgCost'] * tmp_df['Shares']
  tmp_df['Current'] = round(tmp_df['Close'] * tmp_df['Shares'],0)
  tmp_df['Previous'] = tmp_df['Prev_Close'] * tmp_df['Shares']
  tmp_df['EstimatedST'] = tmp_df['NTT'] * tmp_df['Shares']
  tmp_df['EstimatedLT'] = tmp_df['LTT'] * tmp_df['Shares']
  tmp_df['Current P/L'] = round((tmp_df['Current'] - tmp_df['Investment']),0)
  tmp_df['Today P/L%'] = round((tmp_df['Current'] - tmp_df['Previous'])*100/tmp_df['Previous'],2)
  tmp_df['Current P/L%'] = round((tmp_df['Current'] - tmp_df['Investment'])*100/tmp_df['Investment'],2)
  tmp_df['EstimatedST P/L%'] = round((tmp_df['EstimatedST'] - tmp_df['Investment'])*100/tmp_df['Investment'],2)
  tmp_df['EstimatedLT P/L%'] = round((tmp_df['EstimatedLT'] - tmp_df['Investment'])*100/tmp_df['Investment'],2)
  tmp_df['NTT%'] = round((tmp_df['NTT'] - tmp_df['Close'])*100/tmp_df['Close'],2)
  tmp_df['LTT%'] = round((tmp_df['LTT'] - tmp_df['Close'])*100/tmp_df['Close'],2)
  tmp_df['Gained%'] = round((tmp_df['Close'] - tmp_df['BOL'])*100/tmp_df['BOL'],2)
  investment = round(sum(tmp_df['AvgCost']*tmp_df['Shares']),0)
  current = round(sum(tmp_df['Close']*tmp_df['Shares']),0)
  tmp_df['InitAlloc%'] = round(tmp_df['Investment']*100/investment,2)
  tmp_df['CurrAlloc%'] = round(tmp_df['Current']*100/current,2)
  tmp_df['FTT'] = tmp_df['LTT']
  tmp_df.loc[tmp_df['Strategy'] == 'NTT', 'FTT'] = tmp_df['NTT']
  tmp_df['FTT%'] = tmp_df['LTT%']
  tmp_df.loc[tmp_df['Strategy'] == 'NTT', 'FTT%'] = tmp_df['NTT%']
  tmp_df['FTT Amt'] = round(tmp_df['FTT%'] * tmp_df['Current']/100,0)
  tmp_df['OTT%'] = round((tmp_df['FTT'] - tmp_df['AvgCost'])*100/tmp_df['AvgCost'],2)
  tmp_df['RRR Ind'] = round(tmp_df['Current P/L']/tmp_df['FTT Amt'],2)
  tmp_df['Risk Ind'] = round(tmp_df['Current P/L%']*tmp_df['CurrAlloc%'],0)

  return tmp_df

# function to print portfolio features
def print_portfolio_stats(df_portfolio_features, myinvmt_df):
  from pyxirr import xirr

  total_booked_amt, reserve_amt, cy_booked_amt, py_booked_amt = get_amt()

  dates = myinvmt_df['Date'].values
  dates = np.append(dates, datetime.date.today().strftime('%d-%b-%y'))
  investment = myinvmt_df['Investment'].values
  dates= pd.to_datetime(dates)

  current = round(sum(df_portfolio_features['Close']*df_portfolio_features['Shares']),0) + reserve_amt
  investment_xirr = np.append(investment, current)
  cagr = round(xirr(pd.DataFrame({"dates": dates, "amounts": investment_xirr}))*100,2)

  investment = -sum(investment)
  invested = round(sum(df_portfolio_features['AvgCost']*df_portfolio_features['Shares']),0) + reserve_amt
  previous = round(sum(df_portfolio_features['Prev_Close']*df_portfolio_features['Shares']),0) + reserve_amt
  cy_invested = investment + py_booked_amt

  today_pnl_amount = current-previous
  today_pnl_percentage = round((current-previous)*100/previous,2)

  curr_pnl_amount = current-invested
  curr_pnl_percentage = round((curr_pnl_amount)*100/(cy_invested),2)

  cy_pnl_amount = cy_booked_amt + curr_pnl_amount
  cy_pnl_percentage = round((cy_pnl_amount)*100/cy_invested,2)

  overall_pnl_amount = total_booked_amt + curr_pnl_amount
  overall_pnl_percentage = round((overall_pnl_amount)*100/investment,2)

  estimate_st = round(sum(df_portfolio_features['FTT']*df_portfolio_features['Shares']),0)  + reserve_amt
  est_st_pnl_amount = estimate_st-current
  est_st_pnl_percentage = round((est_st_pnl_amount)*100/current,2)

  estimate_lt = round(sum(df_portfolio_features['LTT']*df_portfolio_features['Shares']),0)  + reserve_amt
  est_lt_pnl_amount = estimate_lt-current
  est_lt_pnl_percentage = round((est_lt_pnl_amount)*100/current,2)

  total_profit = round(sum(df_portfolio_features[df_portfolio_features['Current P/L%'] > 0]['Current']) - sum(df_portfolio_features[df_portfolio_features['Current P/L%'] > 0]['Investment']),0)
  total_loss = round(sum(df_portfolio_features[df_portfolio_features['Current P/L%'] < 0]['Current']) - sum(df_portfolio_features[df_portfolio_features['Current P/L%'] < 0]['Investment']),0)

  cy_booked_percentage = round((cy_booked_amt)*100/current,2)
  py_booked_percentage = round((py_booked_amt)*100/investment,2)
  total_booked_percentage = round((total_booked_amt)*100/investment,2)

  print('-------------------')
  print('Initial Investment: ', format_amt(investment))
  print('CY Investment: ', format_amt(cy_invested))
  print('Reserve: ', format_amt(reserve_amt))
  print('Current: ',  format_amt(current))
  print('-------------------')
  print('Today PnL: '+ '{} ({}%)'.format(format_amt(today_pnl_amount), today_pnl_percentage))
  print('Current PnL: '+ '{} ({}%)'.format(format_amt(curr_pnl_amount), curr_pnl_percentage))
  print('CY Booked + Current PnL: '+ '{} ({}%)'.format(format_amt(cy_pnl_amount), cy_pnl_percentage))
  print('-------------------')
  print('Total profit: ', format_amt(total_profit))
  print('Total loss: ', format_amt(total_loss))
  print('-------------------')
  print('Total Booked + Current PnL: '+ '{} ({}%)'.format(format_amt(overall_pnl_amount), overall_pnl_percentage))
  print('Total Booked PnL: '+ '{} ({}%)'.format(format_amt(total_booked_amt), total_booked_percentage))
  print('Curr Year Booked PnL: '+ '{} ({}%)'.format(format_amt(cy_booked_amt), cy_booked_percentage))
  print('Prev Year Booked PnL: '+ '{} ({}%)'.format(format_amt(py_booked_amt), py_booked_percentage))
  print('===================')
  print('Est FTT: ',  format_amt(estimate_st))
  print('Est FTT PnL: '+ '{} ({}%)'.format(format_amt(est_st_pnl_amount), est_st_pnl_percentage))

  print('===================')
  print('Deployed: ', format_amt(investment))

  print('Current: ', format_amt(current))

  print('CAGR/XIRR %: '+'{}%'.format(cagr))

In [8]:
# get start and end date
start_date, end_date = get_start_end_date()

# get portfolio and prospects data
mypfs_df = get_mypfs_df()
mypps_df = get_mypps_df()
myinvmt_df = get_myinvmt_df()

# merge above datasets
mypf_df = pd.merge(mypfs_df, mypps_df, on="Symbol")

# seggregate dm and sv portfolio
dm_pf = mypf_df[mypf_df['InPortfolio'] == 'DM']
sv_pf = mypf_df[mypf_df['InPortfolio'] == 'SV']

# build portfolio stock dataframe
dm_stocks = get_stock_ids(dm_pf)
sv_stocks = get_stock_ids(sv_pf)
df_stocks = pd.concat([dm_pf,sv_pf], ignore_index = True)

# arrange common and diff stock features
common_cols = ['Symbol', 'Target', 'Criteria', 'Strategy', 'CumlRnk', 'LatestQtr', 'StarStock', 'Conviction', 'Category', 'InFolio', 'XIRR', 'MBQ']
diff_cols = ['Symbol', 'AvgCost', 'Shares']
df_stocks = arrange_features(df_stocks, common_cols, diff_cols)

# get common features
stock_ids = df_stocks['Symbol'].values
df_common_features = get_common_features(stock_ids, df_stocks)

df_common_features.reset_index(drop=True, inplace=True)
df_common_features.drop(['Date'], axis=1, inplace=True)
# get and print portfolio features
df_portfolio_features = get_portfolio_features(df_common_features)

print_portfolio_stats(df_portfolio_features, myinvmt_df)

df = df_portfolio_features
#plot_pie_chart(df, 'CapType', 'Current')
list_ox40n = list(df[df['MBQ'].str.contains('OX40N', na=False)]['Symbol'].values)

Run date time (IST): 2026-04-01 13:31:41
-------------------
qualified stocks: 86
with latest results: 26
still star stocks: 16
-------------------
Initial Investment:  1.36 C
CY Investment:  1.62 C
Reserve:  1.61 K
Current:  1.29 C
-------------------
Today PnL: 4.76 L (3.83%)
Current PnL: -47.97 L (-29.52%)
CY Booked + Current PnL: -32.08 L (-19.74%)
-------------------
Total profit:  40.87 K
Total loss:  -48.38 L
-------------------
Total Booked + Current PnL: -5.10 L (-3.76%)
Total Booked PnL: 42.87 L (31.64%)
Curr Year Booked PnL: 15.89 L (12.3%)
Prev Year Booked PnL: 26.98 L (19.91%)
===================
Est FTT:  2.48 C
Est FTT PnL: 1.19 C (91.93%)
===================
Deployed:  1.36 C
Current:  1.29 C
CAGR/XIRR %: -2.33%

In [9]:
# top 5 near their targets
cols = ['Symbol', 'Today P/L%', 'Current P/L%', 'FTT%', 'OTT%', 'FTT Amt', 'Current P/L', 'Current', 'FTT', 'Dev%_PE', 'RSI_14','Conviction', 'Spread%',  'CumlRnk', 'RRR Ind', 'CurrAlloc%', 'Gained%', 'Criteria', 'Strategy', 'Category']
df_tmp = df_portfolio_features[~df_portfolio_features['Symbol'].isin(['ENRIN','BLUSPRING','DIGITIDE'])]
df_tmp = df_tmp.sort_values(by = 'FTT Amt', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
50,MASFIN,5.27,-9.86,34.86,21.57,30788.0,-9660.0,88320.0,397.04,-22.31,44.0,H-SC,4.65,167.0,-0.31,0.68,20.46,XR,ATH,FINANCE
77,TTKPRESTIG,3.48,-42.34,73.58,0.09,42759.0,-42665.0,58112.0,770.00,34.90,38.0,M-SC,21.80,250.0,-1.00,0.45,3.48,OX40N,NTT,DURABLES
2,ABBOTINDIA,1.97,-11.35,33.19,18.07,52623.0,-20305.0,158550.0,35195.00,-24.65,48.0,X-MC,10.43,58.0,-0.39,1.23,3.69,X40,ATH,PHARMA
67,SONACOMS,4.32,-13.10,60.07,39.09,52803.0,-13257.0,87902.0,804.02,-31.14,49.0,M-MC,6.60,193.0,-0.25,0.68,24.35,AR,ATH,AUTO
37,ICICIGI,0.51,-8.92,31.03,19.34,56554.0,-17853.0,182256.0,2252.93,-23.27,32.0,X-MC,5.42,66.0,-0.32,1.41,0.75,X40,ATH,INSURANCE

In [10]:
# top 5 today
df_tmp = df_portfolio_features.sort_values(by = 'Today P/L%', ascending=False)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
80,VALIANTORG,17.29,-50.75,253.59,74.15,204343.0,-83025.0,80580.0,838.00,-244.73,52.0,H-SC,27.87,145.0,-0.41,0.62,19.91,XR,NTT,CHEMICALS
19,COFFEEDAY,12.36,-59.87,237.13,35.27,108041.0,-67987.0,45562.0,80.00,-69.82,40.0,L-SC,30.56,266.0,-0.63,0.35,12.36,XR,NTT,HOTELS
56,RAJOOENG,11.85,-49.06,174.09,39.61,90892.0,-50290.0,52210.0,143.10,-65.63,41.0,H-SC,33.72,136.0,-0.55,0.40,11.85,AR,ATH,MISC
71,TANLA,11.45,-52.46,362.12,119.69,466117.0,-142042.0,128719.0,1943.92,-51.95,47.0,H-SC,27.05,147.0,-0.30,1.00,11.45,AR,ATH,IT
25,EASEMYTRIP,9.91,-64.51,310.58,45.70,194870.0,-114071.0,62744.0,26.40,-34.84,41.0,M-SC,12.68,204.0,-0.59,0.49,9.91,XY24,NTT,TRAVEL

In [11]:
# bottom 5 today
df_tmp = df_portfolio_features.sort_values(by = 'Today P/L%', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
82,VOLTAS,-2.60,-3.02,49.71,45.20,92438.0,-5787.0,185955.0,1856.00,10.98,34.0,X-MC,2.82,79.0,-0.06,1.44,3.57,XY25,NTT,AC
85,ZYDUSLIFE,-0.49,-8.58,48.36,35.63,92656.0,-17978.0,191596.0,1286.17,-20.27,42.0,H-MC,5.40,120.0,-0.19,1.48,6.66,AR,ATH,PHARMA
32,HAVELLS,-0.16,-23.89,73.54,32.08,183576.0,-78364.0,249627.0,2062.85,-28.37,31.0,X-MC,10.81,63.0,-0.43,1.93,0.00,X40,ATH,ELECTRICAL
37,ICICIGI,0.51,-8.92,31.03,19.34,56554.0,-17853.0,182256.0,2252.93,-23.27,32.0,X-MC,5.42,66.0,-0.32,1.41,0.75,X40,ATH,INSURANCE
35,HINDUNILVR,0.52,-19.63,41.44,13.67,85611.0,-50473.0,206590.0,2922.00,-40.26,35.0,X-LC,10.49,9.0,-0.59,1.60,0.67,XY25,NTT,FMCG

In [12]:
# top 5 to exit based on CumlRnk
df_tmp = df_portfolio_features[~df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])]
df_tmp = df_tmp[(df_tmp['Current P/L%'] > -1) & (df_tmp['Current P/L%'] < 1)].sort_values(by = 'CumlRnk', ascending=False)
df_tmp[cols].head()

Empty DataFrame
Columns: [Symbol, Today P/L%, Current P/L%, FTT%, OTT%, FTT Amt, Current P/L, Current, FTT, Dev%_PE, RSI_14, Conviction, Spread%, CumlRnk, RRR Ind, CurrAlloc%, Gained%, Criteria, Strategy, Category]
Index: []

In [13]:
# OX40N stocks to exit
df_tmp = df_portfolio_features[(df_portfolio_features['Symbol'].isin(list_ox40n))].sort_values(by = 'Current P/L%', ascending=False)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
26,FINCABLES,3.81,2.09,103.65,107.91,156233.0,3087.0,150731.0,1641.55,-8.17,45.0,M-SC,6.62,220.0,0.02,1.17,13.40,OX40N,ATH,CABLES
66,SIS,3.10,-33.63,82.70,21.26,60946.0,-37337.0,73695.0,528.00,1725.91,49.0,H-SC,14.71,168.0,-0.61,0.57,9.57,OX40N,NTT,MISC
18,CERA,2.13,-39.07,103.33,23.89,110744.0,-68728.0,107175.0,9475.00,-41.29,45.0,H-SC,19.38,153.0,-0.62,0.83,2.99,OX40N,NTT,CERAMICS
72,TATAELXSI,4.02,-40.38,121.46,32.03,95461.0,-53240.0,78595.0,9161.00,-25.40,40.0,H-SC,21.72,158.0,-0.56,0.61,4.02,OX40N,NTT,IT
48,KANSAINER,5.47,-41.14,92.79,13.47,147280.0,-110943.0,158724.0,340.00,-49.34,44.0,H-SC,22.70,162.0,-0.75,1.23,10.87,XY24,NTT,PAINTS

In [14]:
# top 5 to book for rotation
df_tmp = df_portfolio_features[(df_portfolio_features['Current P/L%'] > 20) ].sort_values(by = 'CumlRnk', ascending=False)
df_tmp[cols].head()

Empty DataFrame
Columns: [Symbol, Today P/L%, Current P/L%, FTT%, OTT%, FTT Amt, Current P/L, Current, FTT, Dev%_PE, RSI_14, Conviction, Spread%, CumlRnk, RRR Ind, CurrAlloc%, Gained%, Criteria, Strategy, Category]
Index: []

In [15]:
# top 5 to monitor for exit
df_tmp = df_portfolio_features[~df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])]
df_tmp = df_tmp[(df_tmp['Current P/L%'] > 0) ].sort_values(by = 'Dev%_PE', ascending=False)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
26,FINCABLES,3.81,2.09,103.65,107.91,156233.0,3087.0,150731.0,1641.55,-8.17,45.0,M-SC,6.62,220.0,0.02,1.17,13.40,OX40N,ATH,CABLES
1,ABB,2.75,12.01,29.96,45.57,87795.0,31421.0,293040.0,7934.00,-28.06,52.0,H-MC,13.23,125.0,0.36,2.27,30.13,AR,NTT,ELECTRICAL

In [16]:
# top 5 to book for rotation from weak conviction
df_tmp = df_portfolio_features[~df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])]
df_tmp = df_tmp[~df_tmp['Criteria'].isin(['XY25','XY24','X40', 'X40N'])].sort_values(by = 'RRR Ind', ascending=False)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
1,ABB,2.75,12.01,29.96,45.57,87795.0,31421.0,293040.0,7934.00,-28.06,52.0,H-MC,13.23,125.0,0.36,2.27,30.13,AR,NTT,ELECTRICAL
26,FINCABLES,3.81,2.09,103.65,107.91,156233.0,3087.0,150731.0,1641.55,-8.17,45.0,M-SC,6.62,220.0,0.02,1.17,13.40,OX40N,ATH,CABLES
40,INDIAMART,2.89,-12.19,135.41,106.72,146657.0,-15030.0,108306.0,4810.62,-60.35,45.0,H-SC,12.80,140.0,-0.10,0.84,8.34,AR,ATH,MISC
85,ZYDUSLIFE,-0.49,-8.58,48.36,35.63,92656.0,-17978.0,191596.0,1286.17,-20.27,42.0,H-MC,5.40,120.0,-0.19,1.48,6.66,AR,ATH,PHARMA
84,WIPRO,2.17,-21.37,119.07,72.27,158655.0,-36203.0,133245.0,420.00,-29.24,40.0,M-LC,18.41,98.0,-0.23,1.03,2.23,XR,NTT,IT

In [17]:
# top 5 to accumulate based on lowest RSI_14
df_tmp = df_portfolio_features[df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])].sort_values(by = 'RSI_14', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
38,ICICIPRULI,1.43,-14.47,52.85,30.73,89049.0,-28512.0,168493.0,790.00,-37.42,23.0,X-MC,7.64,78.0,-0.32,1.30,1.43,X40,ATH,INSURANCE
21,DABUR,1.25,-18.75,76.85,43.70,154903.0,-46502.0,201566.0,735.00,-26.30,29.0,X-MC,10.20,70.0,-0.30,1.56,1.25,XY24,BTT,FMCG
32,HAVELLS,-0.16,-23.89,73.54,32.08,183576.0,-78364.0,249627.0,2062.85,-28.37,31.0,X-MC,10.81,63.0,-0.43,1.93,0.00,X40,ATH,ELECTRICAL
10,BAJAJHLDNG,1.99,-20.24,62.01,29.22,94032.0,-38485.0,151640.0,14451.52,-26.29,31.0,X-LC,19.19,28.0,-0.41,1.17,1.99,X40,ATH,FINANCE
34,HDFCBANK,2.06,-10.68,43.72,28.37,91722.0,-25090.0,209795.0,1073.00,-23.99,31.0,X-LC,14.89,26.0,-0.27,1.62,2.06,X40,BTT,BANKS

In [18]:
# top 5 to accumulate based on Spread and CumlRnk
df_tmp = df_portfolio_features[df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])]
df_tmp = df_tmp[(df_tmp['CumlRnk'] < 100)].sort_values(by = 'Spread%', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
65,SIEMENS,3.54,-18.35,53.73,25.51,81637.0,-34155.0,151940.0,4671.50,27.53,45.0,H-LC,0.54,51.0,-0.42,1.18,11.89,AR,ATH,ELECTRICAL
82,VOLTAS,-2.60,-3.02,49.71,45.20,92438.0,-5787.0,185955.0,1856.00,10.98,34.0,X-MC,2.82,79.0,-0.06,1.44,3.57,XY25,NTT,AC
78,UNITDSPR,2.58,-8.15,31.49,20.77,67720.0,-19092.0,215052.0,1644.00,-18.49,40.0,X-MC,3.27,64.0,-0.28,1.67,2.58,X40N,NTT,BREWERIES
59,RELIANCE,2.00,-12.01,42.40,25.30,74977.0,-24130.0,176833.0,1952.00,-14.26,44.0,X-LC,3.91,21.0,-0.32,1.37,18.06,XY25,BTT,REFINERIES
37,ICICIGI,0.51,-8.92,31.03,19.34,56554.0,-17853.0,182256.0,2252.93,-23.27,32.0,X-MC,5.42,66.0,-0.32,1.41,0.75,X40,ATH,INSURANCE

In [19]:
# top 5 to accumulate based on lowest Gained%
df_tmp = df_portfolio_features[df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])].sort_values(by = 'Gained%', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
32,HAVELLS,-0.16,-23.89,73.54,32.08,183576.0,-78364.0,249627.0,2062.85,-28.37,31.0,X-MC,10.81,63.0,-0.43,1.93,0.00,X40,ATH,ELECTRICAL
35,HINDUNILVR,0.52,-19.63,41.44,13.67,85611.0,-50473.0,206590.0,2922.00,-40.26,35.0,X-LC,10.49,9.0,-0.59,1.60,0.67,XY25,NTT,FMCG
37,ICICIGI,0.51,-8.92,31.03,19.34,56554.0,-17853.0,182256.0,2252.93,-23.27,32.0,X-MC,5.42,66.0,-0.32,1.41,0.75,X40,ATH,INSURANCE
21,DABUR,1.25,-18.75,76.85,43.70,154903.0,-46502.0,201566.0,735.00,-26.30,29.0,X-MC,10.20,70.0,-0.30,1.56,1.25,XY24,BTT,FMCG
38,ICICIPRULI,1.43,-14.47,52.85,30.73,89049.0,-28512.0,168493.0,790.00,-37.42,23.0,X-MC,7.64,78.0,-0.32,1.30,1.43,X40,ATH,INSURANCE

In [20]:
# top 5 to accumulate based on lowest CurrAlloc%
df_tmp = df_portfolio_features[df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])].sort_values(by = 'CurrAlloc%', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
58,RELAXO,8.65,-66.52,354.95,52.31,172492.0,-96564.0,48596.0,1176.00,-64.38,33.0,X-SC,30.66,92.0,-0.56,0.38,8.65,X40N,NTT,FOOTWEAR
12,BATAINDIA,4.78,-58.94,229.27,35.20,121133.0,-75836.0,52834.0,2096.00,-30.69,34.0,X-SC,33.60,91.0,-0.63,0.41,4.78,X40,NTT,FOOTWEAR
54,QUESS,3.74,-27.79,140.83,73.90,108600.0,-29679.0,77114.0,424.00,-61.43,42.0,X-SC,22.38,80.0,-0.27,0.60,3.74,XY24,NTT,MISC
36,HONAUT,4.33,-28.79,112.48,51.31,154463.0,-55513.0,137325.0,58357.33,-40.75,37.0,X-SC,17.59,90.0,-0.36,1.06,4.33,X40N,ATH,ELECTRICAL
51,MEDANTA,3.33,-15.04,49.62,27.12,74413.0,-26551.0,149966.0,1486.00,-17.72,38.0,X-SC,14.62,87.0,-0.36,1.16,3.33,XY24,NTT,HEALTHCARE

In [21]:
# top 5 to accumulate based on CumlRnk
df_tmp = df_portfolio_features.sort_values(by = 'CumlRnk', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
45,ITC,1.79,-22.86,54.35,19.06,142611.0,-77772.0,262394.0,452.00,-57.54,38.0,X-LC,19.39,1.0,-0.55,2.03,1.79,X40,NTT,FMCG
73,TCS,2.66,-28.91,78.04,26.57,257026.0,-133922.0,329351.0,4311.59,-39.69,38.0,X-LC,18.42,2.0,-0.52,2.55,2.79,X40,ATH,IT
43,INFY,2.18,-13.01,54.32,34.24,147855.0,-40695.0,272193.0,1972.00,-31.42,44.0,X-LC,15.11,3.0,-0.28,2.11,4.68,X40,NTT,IT
75,TMPV,2.31,-31.02,97.99,36.58,240536.0,-110371.0,245470.0,600.00,-85.81,36.0,X-LC,10.50,4.0,-0.46,1.90,2.31,XY24,NTT,AUTO
33,HCLTECH,1.11,-11.97,40.67,23.83,86615.0,-28954.0,212970.0,1908.19,-7.36,44.0,X-LC,11.67,8.0,-0.33,1.65,3.41,X40,ATH,IT

In [22]:
# top 5 for average up
df_tmp = df_portfolio_features[(df_portfolio_features['Dev%_200'] > 5)].sort_values(by = 'CurrAlloc%', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
67,SONACOMS,4.32,-13.10,60.07,39.09,52803.0,-13257.0,87902.0,804.02,-31.14,49.0,M-MC,6.60,193.0,-0.25,0.68,24.35,AR,ATH,AUTO
1,ABB,2.75,12.01,29.96,45.57,87795.0,31421.0,293040.0,7934.00,-28.06,52.0,H-MC,13.23,125.0,0.36,2.27,30.13,AR,NTT,ELECTRICAL

In [23]:
# top 5 RSP
df_tmp = df_portfolio_features.sort_values(by = 'RSP', ascending=False)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
30,HAPPSTMNDS,7.98,-51.33,279.82,84.85,174541.0,-65789.0,62376.0,1480.71,-42.16,51.0,H-SC,24.98,152.0,-0.38,0.48,15.51,AR,ATH,IT
24,DMART,7.81,2.55,26.38,29.60,67522.0,6360.0,255960.0,5391.45,-13.54,71.0,X-LC,6.59,14.0,0.09,1.98,17.00,X40N,ATH,FMCG
5,ANGELONE,6.49,-0.70,25.05,24.18,75870.0,-2125.0,302875.0,303.00,-85.37,56.0,X-SC,9.88,97.0,-0.03,2.35,16.58,X40N,NTT,FINANCE
80,VALIANTORG,17.29,-50.75,253.59,74.15,204343.0,-83025.0,80580.0,838.00,-244.73,52.0,H-SC,27.87,145.0,-0.41,0.62,19.91,XR,NTT,CHEMICALS
52,PAGEIND,3.16,-14.50,56.86,34.11,130471.0,-38919.0,229460.0,51418.65,-38.70,55.0,X-MC,20.76,55.0,-0.30,1.78,8.54,X40,ATH,APPARELS

In [24]:
# Top N allocation
df_tmp = df_portfolio_features.sort_values(by = 'CurrAlloc%', ascending=False)
top_n_values = [10, 25, 50]

sum_df = pd.DataFrame({
    'Top_N': top_n_values,
    'Sum_Alloc%': [df_tmp['CurrAlloc%'].head(n).sum() for n in top_n_values]
})

sum_df

   Top_N  Sum_Alloc%
0     10       21.07
1     25       46.23
2     50       78.29

In [25]:
# market-cap-wise allocation
df_tmp = df_portfolio_features[cols]
df_tmp.groupby(df_tmp['Conviction'].str[-2:])['CurrAlloc%'].sum().sort_values(ascending=False)

Conviction
SC    44.52
MC    29.80
LC    25.71
Name: CurrAlloc%, dtype: float64

In [26]:
# criteria-wise allocation
df_portfolio_features.groupby('Criteria')['CurrAlloc%'].sum().sort_values(ascending=False)

Criteria
XY24     27.06
X40      25.35
X40N     15.54
AR        9.17
XR        8.29
XY25      7.20
OX40N     6.63
SR        0.79
Name: CurrAlloc%, dtype: float64

In [27]:
# conviction-wise allocation
df_portfolio_features.groupby('Conviction')['CurrAlloc%'].sum().sort_values(ascending=False)

Conviction
X-LC    23.50
X-MC    22.35
H-SC    21.75
X-SC    12.36
M-SC     9.89
H-MC     5.05
M-MC     2.05
H-LC     1.18
M-LC     1.03
L-SC     0.52
L-MC     0.35
Name: CurrAlloc%, dtype: float64

In [28]:
# sector-wise stats
df_tmp = df_portfolio_features.groupby('Category')[['CurrAlloc%', 'Current', 'Current P/L', 'FTT Amt']].sum().sort_values(by=['Current', 'Current P/L'], ascending=False)
df_tmp['Current P/L%'] = round(df_tmp['Current P/L'] * 100 / df_tmp['Current'], 2)
df_tmp['FTT%'] = round(df_tmp['FTT Amt'] * 100 / df_tmp['Current'], 2)
cols = ['CurrAlloc%', 'Current P/L%', 'FTT%']
df_tmp[cols].sort_values(by=['CurrAlloc%'], ascending=False)

               CurrAlloc%  Current P/L%    FTT%
Category
FMCG                15.27        -26.69   71.67
FINANCE             13.18        -26.26   77.72
IT                  11.99        -45.53  119.60
MISC                 7.00        -48.33  112.76
ELECTRICAL           6.44        -16.42   61.00
PAINTS               5.24        -45.66   70.95
INSURANCE            4.67        -12.37   50.82
BANKS                4.51        -32.19   99.29
PHARMA               4.16         -9.48   43.95
AUTO                 3.66        -38.16   92.98
AC                   1.94        -27.87   62.54
HEALTHCARE           1.91        -45.22   83.11
TRAVEL               1.79        -94.38  191.71
APPARELS             1.78        -16.96   56.86
DURABLES             1.78        -68.81  109.89
FOOTWEAR             1.78        -92.94  170.30
BREWERIES            1.67         -8.88   31.49
REALTY               1.45        -18.44   37.90
REFINERIES           1.37        -13.65   42.40
CERAMICS             1.36        -75.27  128.51
CEMENT               1.23        -69.21  195.80
CABLES               1.17          2.05  103.65
ENGINEERING          1.08        -72.97  152.08
CHEMICALS            1.06        -92.79  250.09
JEWELLERY            0.98       -151.43  238.79
ENTERTAINMENT        0.75        -98.76  217.30
TEXTILES             0.46        -56.34  100.92
HOTELS               0.35       -149.22  237.13

In [29]:
# money to be made criteria-wise
df_portfolio_features.groupby('Criteria')['FTT Amt'].agg(['sum', 'count']).sort_values(by='sum', ascending=False)

                sum  count
Criteria
XY24      4103931.0     21
X40       1900335.0     16
XR        1420373.0     12
AR        1387686.0     10
X40N      1295664.0     10
OX40N      936931.0     10
XY25       510884.0      5
SR         317288.0      2

In [30]:
# money to be made conviction-wise
df_portfolio_features.groupby('Conviction')['FTT Amt'].agg(['sum', 'count']).sort_values(by='sum', ascending=False)

                  sum  count
Conviction
H-SC        3983704.0     24
X-MC        1848547.0     15
X-LC        1740858.0     13
M-SC        1643267.0     14
X-SC        1587652.0     10
H-MC         426758.0      3
L-SC         223186.0      2
M-LC         158655.0      1
M-MC         121079.0      2
H-LC          81637.0      1
L-MC          57749.0      1

In [31]:
# money to be made criteria and conviction-wise
df_portfolio_features.groupby(['Conviction', 'Criteria'])['FTT Amt'].agg(['sum', 'count']).sort_values(by='sum', ascending=False)

                           sum  count
Conviction Criteria
H-SC       XY24      1368970.0      6
           AR         992571.0      5
M-SC       XY24       950204.0      6
X-LC       X40        945818.0      7
H-SC       XR         903562.0      7
X-SC       XY24       863481.0      4
X-MC       X40        729624.0      7
           X40N       556701.0      4
X-SC       X40N       499278.0      4
M-SC       OX40N      420473.0      5
H-SC       OX40N      401313.0      4
X-LC       XY24       394767.0      2
H-SC       SR         317288.0      2
X-MC       XY25       282020.0      2
           XY24       280202.0      2
H-MC       XY24       246307.0      1
X-LC       X40N       239685.0      2
X-SC       X40        224893.0      2
M-SC       XR         192366.0      2
H-MC       AR         180451.0      2
X-LC       XY25       160588.0      2
M-LC       XR         158655.0      1
L-SC       OX40N      115145.0      1
           XR         108041.0      1
H-LC       AR          81637.0      1
M-SC       AR          80224.0      1
M-MC       XY25        68276.0      1
L-MC       XR          57749.0      1
M-MC       AR          52803.0      1

In [32]:
# notebook execution time

end_time = time.time()
execution_time = round(end_time - start_time, 0)
print(f"Notebook execution time: {execution_time} seconds")

Notebook execution time: 33.0 seconds