<a href="https://colab.research.google.com/github/ankit-rathi/Quantvesting_v2/blob/main/myStocks_Portfolio_Analysis.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
'''
!pip install pandas==2.2.2 -qq
!pip install pyxirr -qq
!pip install ta -qq
!pip install yfinance==0.2.59 -qq
'''

'\n!pip install pandas==2.2.2 -qq\n!pip install pyxirr -qq\n!pip install ta -qq\n!pip install yfinance==0.2.59 -qq\n'

In [2]:
# import libraries

import numpy as np
import pandas as pd
import datetime
import warnings
warnings.filterwarnings('ignore')
import yfinance as yfin
import ta
import matplotlib.pyplot as plt
import requests

In [3]:
# notebook start time
import time
import datetime
import pytz

start_time = time.time()

# function to print date timestamp
def print_date_time():
  tz_NY = pytz.timezone('Asia/Kolkata')
  datetime_NY = datetime.datetime.now(tz_NY)
  print("Run date time (IST):", datetime_NY.strftime("%Y-%m-%d %H:%M:%S"))

In [4]:
# function to get booked and reserved amount
def get_amt():
  # fetch the JSON data from the URL
  url = "https://raw.githubusercontent.com/ankit-rathi/Tradevesting_v1/main/data/myPortfolioAmts.json"
  response = requests.get(url)
  pf_amts = response.json()  # parse the JSON data

  # extract values from the JSON
  py_booked_amt_dm = pf_amts["py_booked_amt_dm"]
  py_booked_amt_sv = pf_amts["py_booked_amt_sv"]
  cy_booked_amt_dm = pf_amts["cy_booked_amt_dm"]
  cy_booked_amt_sv = pf_amts["cy_booked_amt_sv"]
  reserve_amt_dm = pf_amts["reserve_amt_dm"]
  reserve_amt_sv = pf_amts["reserve_amt_sv"]

  # perform calculations
  py_booked_amt = py_booked_amt_dm + py_booked_amt_sv
  cy_booked_amt = cy_booked_amt_dm + cy_booked_amt_sv
  reserve_amt = reserve_amt_dm + reserve_amt_sv
  total_booked_amt = py_booked_amt + cy_booked_amt

  return total_booked_amt, reserve_amt, cy_booked_amt, py_booked_amt

gen_output = 0

In [5]:
# function to format the amount
def format_amt(number):
    abs_number = abs(number)

    if abs_number >= 1_00_00_000:  # Crores
        formatted_amt = f"{number / 1_00_00_000:.2f} C"
    elif abs_number >= 1_00_000:  # Lakhs
        formatted_amt = f"{number / 1_00_000:.2f} L"
    elif abs_number >= 1_000:  # Thousands
        formatted_amt = f"{number / 1_000:.2f} K"
    else:
        formatted_amt = f"{number:.2f}"

    return formatted_amt

# function to set start and end date
def get_start_end_date():
  start_date = (datetime.date.today() + datetime.timedelta(days=-365)).strftime('%Y-%m-%d')
  end_date = (datetime.date.today() + datetime.timedelta(days=1)).strftime('%Y-%m-%d')
  return start_date, end_date

# function to fetch my portfolio csv
def get_mypfs_df():
  mypfs_df = pd.read_csv('https://raw.githubusercontent.com/ankit-rathi/Tradevesting_v1/main/data/myPortfolioStocks.csv')
  return mypfs_df

# function to fetch my prospects csv
def get_mypps_df():
  mypps_df = pd.read_csv('https://raw.githubusercontent.com/ankit-rathi/Tradevesting_v1/main/data/myProspectsScrips.csv')
  return mypps_df

# function to fetch screener data
def get_myscreen_df():
  myscreen_df = pd.read_csv('https://raw.githubusercontent.com/ankit-rathi/Tradevesting_v1/main/data/myScreenerDB.csv')
  return myscreen_df

# function to fetch momentum data
def get_myinvmt_df():
  myinvmt_df = pd.read_csv('https://raw.githubusercontent.com/ankit-rathi/Tradevesting_v1/main/data/myInvestments.csv')
  return myinvmt_df

# function to get the stock ids
def get_stock_ids(df_pf):
  stock_n100 = df_pf['Symbol'].unique()

  exclude = ['CADILAHC','MMTC', 'MASFIN']

  stock_ids = df_pf[~df_pf['Symbol'].isin(exclude) ]['Symbol'].unique()

  #mypf = mypf[mypf.Forecast.notnull()]
  #stock_ids = mypf['Symbol'].unique()

  #stock_ids.sort()
  return stock_ids

# get features from screener data
def get_screener_features():
  myscreen_df = get_myscreen_df()
  cols = ['Symbol', 'EPS', 'MedPE', 'ROCE%', 'ROE%', 'CapType']
  return myscreen_df[cols]

# get relative strength
def get_relative_strength(stock_list):

    # Dictionary to store stock tickers and their corresponding percentage price change
    stock_changes = {}

    # Loop through each stock and fetch its price data
    for stock in stock_list:
        try:
            # Download the stock data for the given date range
            stock_data = yfin.Ticker(stock + '.NS').history(period='1mo', interval='1d')[map(str.title, ['open', 'close', 'low', 'high', 'volume'])]

            # Calculate the percentage change for the stock
            if len(stock_data) > 0:
                start_price = stock_data['Close'].iloc[0]
                end_price = stock_data['Close'].iloc[-1]
                percent_change = round(((end_price - start_price) / start_price) * 100, 2)
                stock_changes[stock] = percent_change
            else:
                stock_changes[stock] = np.nan  # If no data is available, set to NaN

        except Exception as e:
            print(f"Error fetching data for {stock}: {e}")
            stock_changes[stock] = np.nan

    # Create a DataFrame with stock tickers and their percentage changes
    df = pd.DataFrame(list(stock_changes.items()), columns=['Symbol', 'Percent_Change'])

    # Drop any stocks with missing data (NaN values)
    df = df.dropna()

    # Calculate the percentile rank based on percentage change
    df['RSP'] = round(df['Percent_Change'].rank(pct=True) * 100, 2)
    cols = ['Symbol', 'RSP']
    df = df[cols]
    # Sort by percentile rank (optional)
    df = df.sort_values(by='RSP', ascending=False).reset_index(drop=True)

    return df

In [6]:
# function to get stock technicals
def stock_prec_dev(stock_symbol):
    #stock_symbol = 'ULTRACEMCO.NS'
    short_window = 20
    mid_window = 50
    long_window = 200
    moving_avg = 'SMA'

    start = datetime.datetime(*map(int, start_date.split('-')))
    end = datetime.datetime(*map(int, end_date.split('-')))

    stock_df = yfin.Ticker(stock_symbol + '.NS').history(period='max', interval='1d')[map(str.title, ['open', 'close', 'low', 'high', 'volume'])]

    stock_df['Max'] = round(max(stock_df['Close']),2)
    stock_df = stock_df[(stock_df.index <= end_date) & (stock_df.index >= start_date)]
    stock_df['200_SMA'] = round(stock_df['Close'].rolling(window = 200, min_periods = 1).mean(),0)
    stock_df['Dev%_200'] = round((stock_df['Close'] - stock_df['200_SMA'])*100/stock_df['200_SMA'],2)
    stock_df.dropna(axis = 0, inplace = True) # remove any null rows

    stock_df['20_SMA'] = stock_df['Close'].rolling(window=20).mean()
    stock_df['50_SMA'] = stock_df['Close'].rolling(window=50).mean()
    stock_df['Symbol'] = stock_symbol

    stock_df['Close'] = round(stock_df['Close'],2)
    stock_df['Min'] = round(min(stock_df['Close']),2)
    stock_df['RSI_14'] = ta.momentum.RSIIndicator(close=stock_df['Close'], window=14).rsi()
    stock_df['RSI_14'] = round(stock_df['RSI_14'],0)
    stock_df['Prev_Close'] = stock_df['Close'].shift(1)
    stock_df.drop(['Open', 'Low', 'High', 'Volume'], axis=1, inplace=True)
    stock_df = stock_df.tail(1)

    max_SMA = max(stock_df['20_SMA'].item(), stock_df['50_SMA'].item(), stock_df['200_SMA'].item())
    min_SMA = min(stock_df['20_SMA'].item(), stock_df['50_SMA'].item(), stock_df['200_SMA'].item())
    ABS_Spread = max_SMA - min_SMA
    stock_df['Spread%'] = round((ABS_Spread / stock_df['200_SMA'].item()) * 100,2)

    return stock_df

# function to compute stock attributes
def get_common_features(stock_ids, df_mypf):

  df_prec_dev = pd.DataFrame()
  df_tmp = get_screener_features()
  df_rs = get_relative_strength(stock_ids)

  for stock_id in stock_ids:
      tmp = stock_prec_dev(stock_id)
      tmp = tmp.reset_index()
      df_prec_dev = pd.concat([df_prec_dev, tmp], ignore_index = True)
  df_prec_dev = pd.merge(df_prec_dev, df_mypf, on= 'Symbol')
  df_prec_dev = pd.merge(df_prec_dev, df_tmp, on= 'Symbol', how='left')
  df_prec_dev = pd.merge(df_prec_dev, df_rs, on= 'Symbol', how='left')
  #print(df_prec_dev.columns)
  df_prec_dev['Curr_PE'] = round(df_prec_dev['Close']/df_prec_dev['EPS'],1)
  df_prec_dev['Dev%_PE'] = round((df_prec_dev['Curr_PE'] - df_prec_dev['MedPE'])*100/df_prec_dev['MedPE'],2)
  df_prec_dev['Conviction'] = df_prec_dev['Conviction'] + '-' + df_prec_dev['CapType']
  return df_prec_dev

# function to arrange stock features
def arrange_features(df_stocks, common_cols, diff_cols):
  df_stocks_common = df_stocks[common_cols].drop_duplicates()
  df_stocks_diff = df_stocks[diff_cols]
  df_stocks_diff['Investment'] = df_stocks_diff['AvgCost'] * df_stocks_diff['Shares']
  df_stocks_diff = df_stocks_diff.groupby(['Symbol'])[['Shares', 'Investment']].aggregate(['sum']).reset_index()
  df_stocks_diff.columns = ['Symbol', 'Shares', 'Investment']
  df_stocks_diff['AvgCost'] = round(df_stocks_diff['Investment']/df_stocks_diff['Shares'],2)
  df_stocks = pd.merge(df_stocks_diff, df_stocks_common, on='Symbol')
  return df_stocks

# plot fact distribution across dimension
def plot_pie_chart(df, dimension, fact):
  # grouping the data by category and calculating the sum of fact for each type
  grouped_data = df.groupby(dimension)[fact].sum()

  # sorting the grouped data in descending order
  grouped_data = grouped_data.sort_values(ascending=False)

  # creating a pie chart
  grouped_data.plot.pie(autopct='%1.1f%%', startangle=90, figsize=(6, 6))

  # adding a title and displaying the plot
  plt.title(f'{dimension} {fact} Distribution')
  plt.ylabel('')  # To hide the y-label
  plt.show()

In [7]:
# function to get portfolio features

def get_portfolio_features(df_common_features):

  print_date_time()
  print('-------------------')

  #df_common_features["Target"] = df_common_features["Target"].fillna(df_common_features["Max"])
  df_common_features['NTT'] = np.where(df_common_features['Strategy']== 'NTT', df_common_features["Target"], df_common_features['Max'])
  df_common_features['LTT'] = np.where(df_common_features['Strategy']== 'BTT', df_common_features["Target"], df_common_features['Max'])
  df_common_features['BOL'] = df_common_features['Min']

  tmp_df = df_common_features[df_common_features['Symbol'].isin(mypf_df[mypf_df['InPortfolio'] != 'NA'].Symbol.values)]
  print('qualified stocks: '+str(len(tmp_df['Symbol'].unique())))
  tmp_df1 = tmp_df[tmp_df['LatestQtr'] == 1]
  print('with latest results: '+str(len(tmp_df1['Symbol'].unique())))
  tmp_df1 = tmp_df1[tmp_df1['StarStock'] == 1]
  print('still star stocks: '+str(len(tmp_df1['Symbol'].unique())))
  tmp_df['Investment'] = tmp_df['AvgCost'] * tmp_df['Shares']
  tmp_df['Current'] = round(tmp_df['Close'] * tmp_df['Shares'],0)
  tmp_df['Previous'] = tmp_df['Prev_Close'] * tmp_df['Shares']
  tmp_df['EstimatedST'] = tmp_df['NTT'] * tmp_df['Shares']
  tmp_df['EstimatedLT'] = tmp_df['LTT'] * tmp_df['Shares']
  tmp_df['Current P/L'] = round((tmp_df['Current'] - tmp_df['Investment']),0)
  tmp_df['Today P/L%'] = round((tmp_df['Current'] - tmp_df['Previous'])*100/tmp_df['Previous'],2)
  tmp_df['Current P/L%'] = round((tmp_df['Current'] - tmp_df['Investment'])*100/tmp_df['Investment'],2)
  tmp_df['EstimatedST P/L%'] = round((tmp_df['EstimatedST'] - tmp_df['Investment'])*100/tmp_df['Investment'],2)
  tmp_df['EstimatedLT P/L%'] = round((tmp_df['EstimatedLT'] - tmp_df['Investment'])*100/tmp_df['Investment'],2)
  tmp_df['NTT%'] = round((tmp_df['NTT'] - tmp_df['Close'])*100/tmp_df['Close'],2)
  tmp_df['LTT%'] = round((tmp_df['LTT'] - tmp_df['Close'])*100/tmp_df['Close'],2)
  tmp_df['Gained%'] = round((tmp_df['Close'] - tmp_df['BOL'])*100/tmp_df['BOL'],2)
  investment = round(sum(tmp_df['AvgCost']*tmp_df['Shares']),0)
  current = round(sum(tmp_df['Close']*tmp_df['Shares']),0)
  tmp_df['InitAlloc%'] = round(tmp_df['Investment']*100/investment,2)
  tmp_df['CurrAlloc%'] = round(tmp_df['Current']*100/current,2)
  tmp_df['FTT'] = tmp_df['LTT']
  tmp_df.loc[tmp_df['Strategy'] == 'NTT', 'FTT'] = tmp_df['NTT']
  tmp_df['FTT%'] = tmp_df['LTT%']
  tmp_df.loc[tmp_df['Strategy'] == 'NTT', 'FTT%'] = tmp_df['NTT%']
  tmp_df['FTT Amt'] = round(tmp_df['FTT%'] * tmp_df['Current']/100,0)
  tmp_df['OTT%'] = round((tmp_df['FTT'] - tmp_df['AvgCost'])*100/tmp_df['AvgCost'],2)
  tmp_df['RRR Ind'] = round(tmp_df['Current P/L']/tmp_df['FTT Amt'],2)
  tmp_df['Risk Ind'] = round(tmp_df['Current P/L%']*tmp_df['CurrAlloc%'],0)

  return tmp_df

# function to print portfolio features
def print_portfolio_stats(df_portfolio_features, myinvmt_df):
  from pyxirr import xirr

  total_booked_amt, reserve_amt, cy_booked_amt, py_booked_amt = get_amt()

  dates = myinvmt_df['Date'].values
  dates = np.append(dates, datetime.date.today().strftime('%d-%b-%y'))
  investment = myinvmt_df['Investment'].values
  dates= pd.to_datetime(dates)

  current = round(sum(df_portfolio_features['Close']*df_portfolio_features['Shares']),0) + reserve_amt
  investment_xirr = np.append(investment, current)
  cagr = round(xirr(pd.DataFrame({"dates": dates, "amounts": investment_xirr}))*100,2)

  investment = -sum(investment)
  invested = round(sum(df_portfolio_features['AvgCost']*df_portfolio_features['Shares']),0) + reserve_amt
  previous = round(sum(df_portfolio_features['Prev_Close']*df_portfolio_features['Shares']),0) + reserve_amt
  cy_invested = investment + py_booked_amt

  today_pnl_amount = current-previous
  today_pnl_percentage = round((current-previous)*100/previous,2)

  curr_pnl_amount = current-invested
  curr_pnl_percentage = round((curr_pnl_amount)*100/(cy_invested),2)

  cy_pnl_amount = cy_booked_amt + curr_pnl_amount
  cy_pnl_percentage = round((cy_pnl_amount)*100/cy_invested,2)

  overall_pnl_amount = total_booked_amt + curr_pnl_amount
  overall_pnl_percentage = round((overall_pnl_amount)*100/investment,2)

  estimate_st = round(sum(df_portfolio_features['FTT']*df_portfolio_features['Shares']),0)  + reserve_amt
  est_st_pnl_amount = estimate_st-current
  est_st_pnl_percentage = round((est_st_pnl_amount)*100/current,2)

  estimate_lt = round(sum(df_portfolio_features['LTT']*df_portfolio_features['Shares']),0)  + reserve_amt
  est_lt_pnl_amount = estimate_lt-current
  est_lt_pnl_percentage = round((est_lt_pnl_amount)*100/current,2)

  total_profit = round(sum(df_portfolio_features[df_portfolio_features['Current P/L%'] > 0]['Current']) - sum(df_portfolio_features[df_portfolio_features['Current P/L%'] > 0]['Investment']),0)
  total_loss = round(sum(df_portfolio_features[df_portfolio_features['Current P/L%'] < 0]['Current']) - sum(df_portfolio_features[df_portfolio_features['Current P/L%'] < 0]['Investment']),0)

  cy_booked_percentage = round((cy_booked_amt)*100/current,2)
  py_booked_percentage = round((py_booked_amt)*100/investment,2)
  total_booked_percentage = round((total_booked_amt)*100/investment,2)

  print('-------------------')
  print('Initial Investment: ', format_amt(investment))
  print('CY Investment: ', format_amt(cy_invested))
  print('Reserve: ', format_amt(reserve_amt))
  print('Current: ',  format_amt(current))
  print('-------------------')
  print('Today PnL: '+ '{} ({}%)'.format(format_amt(today_pnl_amount), today_pnl_percentage))
  print('Current PnL: '+ '{} ({}%)'.format(format_amt(curr_pnl_amount), curr_pnl_percentage))
  print('CY Booked + Current PnL: '+ '{} ({}%)'.format(format_amt(cy_pnl_amount), cy_pnl_percentage))
  print('-------------------')
  print('Total profit: ', format_amt(total_profit))
  print('Total loss: ', format_amt(total_loss))
  print('-------------------')
  print('Total Booked + Current PnL: '+ '{} ({}%)'.format(format_amt(overall_pnl_amount), overall_pnl_percentage))
  print('Total Booked PnL: '+ '{} ({}%)'.format(format_amt(total_booked_amt), total_booked_percentage))
  print('Curr Year Booked PnL: '+ '{} ({}%)'.format(format_amt(cy_booked_amt), cy_booked_percentage))
  print('Prev Year Booked PnL: '+ '{} ({}%)'.format(format_amt(py_booked_amt), py_booked_percentage))
  print('===================')
  print('Est FTT: ',  format_amt(estimate_st))
  print('Est FTT PnL: '+ '{} ({}%)'.format(format_amt(est_st_pnl_amount), est_st_pnl_percentage))

  print('===================')
  print('Deployed: ', format_amt(investment))

  print('Current: ', format_amt(current))

  print('CAGR/XIRR %: '+'{}%'.format(cagr))

In [8]:
# get start and end date
start_date, end_date = get_start_end_date()

# get portfolio and prospects data
mypfs_df = get_mypfs_df()
mypps_df = get_mypps_df()
myinvmt_df = get_myinvmt_df()

# merge above datasets
mypf_df = pd.merge(mypfs_df, mypps_df, on="Symbol")

# seggregate dm and sv portfolio
dm_pf = mypf_df[mypf_df['InPortfolio'] == 'DM']
sv_pf = mypf_df[mypf_df['InPortfolio'] == 'SV']

# build portfolio stock dataframe
dm_stocks = get_stock_ids(dm_pf)
sv_stocks = get_stock_ids(sv_pf)
df_stocks = pd.concat([dm_pf,sv_pf], ignore_index = True)

# arrange common and diff stock features
common_cols = ['Symbol', 'Target', 'Criteria', 'Strategy', 'CumlRnk', 'LatestQtr', 'StarStock', 'Conviction', 'Category', 'InFolio', 'XIRR', 'MBQ']
diff_cols = ['Symbol', 'AvgCost', 'Shares']
df_stocks = arrange_features(df_stocks, common_cols, diff_cols)

# get common features
stock_ids = df_stocks['Symbol'].values
df_common_features = get_common_features(stock_ids, df_stocks)

df_common_features.reset_index(drop=True, inplace=True)
df_common_features.drop(['Date'], axis=1, inplace=True)
# get and print portfolio features
df_portfolio_features = get_portfolio_features(df_common_features)

print_portfolio_stats(df_portfolio_features, myinvmt_df)

df = df_portfolio_features
#plot_pie_chart(df, 'CapType', 'Current')
list_ox40n = list(df[df['MBQ'].str.contains('OX40N', na=False)]['Symbol'].values)

Run date time (IST): 2026-06-19 17:12:14
-------------------
qualified stocks: 92
with latest results: 31
still star stocks: 20
-------------------
Initial Investment:  1.40 C
CY Investment:  1.82 C
Reserve:  1.49 K
Current:  1.52 C
-------------------
Today PnL: -42.55 K (-0.28%)
Current PnL: -30.97 L (-16.98%)
CY Booked + Current PnL: -28.89 L (-15.84%)
-------------------
Total profit:  3.75 L
Total loss:  -34.72 L
-------------------
Total Booked + Current PnL: 13.98 L (10.02%)
Total Booked PnL: 44.95 L (32.22%)
Curr Year Booked PnL: 2.08 L (1.37%)
Prev Year Booked PnL: 42.87 L (30.73%)
===================
Est FTT:  2.55 C
Est FTT PnL: 1.03 C (67.6%)
===================
Deployed:  1.40 C
Current:  1.52 C
CAGR/XIRR %: 4.08%

In [9]:
# top 5 near their targets
cols = ['Symbol', 'Today P/L%', 'Current P/L%', 'FTT%', 'OTT%', 'FTT Amt', 'Current P/L', 'Current', 'FTT', 'Dev%_PE', 'RSI_14','Conviction', 'Spread%',  'CumlRnk', 'RRR Ind', 'CurrAlloc%', 'Gained%', 'Criteria', 'Strategy', 'Category']
df_tmp = df_portfolio_features[~df_portfolio_features['Symbol'].isin(['ENRIN','BLUSPRING','DIGITIDE'])]
df_tmp = df_tmp.sort_values(by = 'FTT Amt', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
59,PIDILITIND,-0.08,11.96,5.72,18.37,9037.0,16880.0,157990.0,1670.26,-21.61,74.0,X-LC,3.80,5.0,1.87,1.04,24.05,X40,ATH,CHEMICALS
51,KOTAKBANK,-0.92,6.68,13.52,21.11,19972.0,9250.0,147722.0,453.24,-8.54,59.0,X-LC,5.50,12.0,0.46,0.97,12.97,X40,ATH,BANKS
55,MASFIN,-0.31,-2.31,24.44,21.57,23393.0,-2265.0,95715.0,397.04,-15.99,57.0,H-SC,3.26,167.0,-0.10,0.63,14.09,XR,ATH,FINANCE
72,SIS,1.31,-1.30,22.86,21.26,25051.0,-1446.0,109586.0,528.00,2615.54,63.0,H-SC,22.93,168.0,-0.06,0.72,62.94,OX40N,NTT,MISC
49,JSWINFRA,0.06,4.91,10.98,16.43,25545.0,10879.0,232653.0,342.00,-9.99,70.0,X-MC,2.09,61.0,0.43,1.53,31.91,X40N,NTT,REALTY

In [10]:
# top 5 today
df_tmp = df_portfolio_features.sort_values(by = 'Today P/L%', ascending=False)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
11,BERGEPAINT,9.04,1.49,23.48,25.32,61420.0,3834.0,261583.0,680.0,-4.06,67.0,X-MC,3.02,68.0,0.06,1.72,36.14,XY24,NTT,PAINTS
21,DEN,5.65,-37.34,126.72,42.07,67070.0,-31536.0,52928.0,75.0,89.12,77.0,M-SC,7.43,235.0,-0.47,0.35,43.95,AR,NTT,ENTERTAINMENT
61,RAJESHEXPO,5.00,-81.16,431.23,0.07,111430.0,-111337.0,25840.0,518.0,846.97,48.0,L-SC,35.30,268.0,-1.00,0.17,27.61,OX40N,NTT,JEWELLERY
31,HATHWAY,5.00,-32.78,157.80,73.29,115320.0,-35640.0,73080.0,31.4,747.83,71.0,H-SC,9.27,171.0,-0.31,0.48,37.32,XR,NTT,ENTERTAINMENT
16,CERA,4.68,-15.69,46.94,23.89,69614.0,-27599.0,148304.0,9475.0,-18.62,73.0,H-SC,6.07,153.0,-0.40,0.97,42.52,OX40N,NTT,CERAMICS

In [11]:
# bottom 5 today
df_tmp = df_portfolio_features.sort_values(by = 'Today P/L%', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
45,INFY,-6.75,-28.43,87.56,34.24,196089.0,-88940.0,223948.0,1972.00,-43.76,33.0,X-LC,16.78,3.0,-0.45,1.47,0.00,X40,NTT,IT
86,VALIANTORG,-6.36,-39.54,188.02,74.15,185995.0,-64682.0,98923.0,838.00,-277.79,52.0,H-SC,3.22,145.0,-0.35,0.65,47.21,XR,NTT,CHEMICALS
10,BATAINDIA,-5.34,-51.77,180.33,35.20,111911.0,-66611.0,62059.0,2096.00,-18.70,63.0,X-SC,24.00,91.0,-0.60,0.41,23.08,X40,NTT,FOOTWEAR
40,ICICIPRULI,-4.18,-17.21,57.36,30.28,93553.0,-33907.0,163098.0,787.27,-39.48,50.0,X-MC,16.76,78.0,-0.36,1.07,8.67,X40,ATH,INSURANCE
6,AWL,-3.72,-36.53,163.14,67.02,368938.0,-130161.0,226148.0,485.00,-65.82,40.0,X-SC,14.96,81.0,-0.35,1.49,7.53,XY24,NTT,FMCG

In [12]:
# top 5 to exit based on CumlRnk
df_tmp = df_portfolio_features[~df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])]
df_tmp = df_tmp[(df_tmp['Current P/L%'] > -1) & (df_tmp['Current P/L%'] < 1)].sort_values(by = 'CumlRnk', ascending=False)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
9,BANDHANBNK,-2.89,0.10,92.22,92.42,257147.0,282.0,278841.0,400.0,139.22,55.0,H-SC,23.40,174.0,0.00,1.83,53.61,XY24,NTT,BANKS
75,SURYODAY,0.96,-0.27,23.37,23.03,41737.0,-479.0,178592.0,216.0,95.18,61.0,H-SC,18.92,166.0,-0.01,1.17,50.37,XR,NTT,BANKS

In [13]:
# OX40N stocks to exit
df_tmp = df_portfolio_features[(df_portfolio_features['Symbol'].isin(list_ox40n))].sort_values(by = 'Current P/L%', ascending=False)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
25,FINCABLES,0.49,47.47,40.99,107.91,89245.0,70080.0,217724.0,1641.55,32.42,65.0,M-SC,24.55,220.0,0.79,1.43,63.80,OX40N,ATH,CABLES
72,SIS,1.31,-1.30,22.86,21.26,25051.0,-1446.0,109586.0,528.00,2615.54,63.0,H-SC,22.93,168.0,-0.06,0.72,62.94,OX40N,NTT,MISC
16,CERA,4.68,-15.69,46.94,23.89,69614.0,-27599.0,148304.0,9475.00,-18.62,73.0,H-SC,6.07,153.0,-0.40,0.97,42.52,OX40N,NTT,CERAMICS
43,INDIGOPNTS,-0.21,-27.18,37.35,0.02,47479.0,-47440.0,127119.0,1408.00,93.64,63.0,M-SC,9.33,222.0,-1.00,0.84,44.22,OX40N,NTT,PAINTS
50,KANSAINER,0.80,-29.54,61.04,13.47,115986.0,-79650.0,190017.0,340.00,-39.37,47.0,H-SC,5.71,162.0,-0.69,1.25,32.73,XY24,NTT,PAINTS

In [14]:
# top 5 to book for rotation
df_tmp = df_portfolio_features[(df_portfolio_features['Current P/L%'] > 20) ].sort_values(by = 'CumlRnk', ascending=False)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
25,FINCABLES,0.49,47.47,40.99,107.91,89245.0,70080.0,217724.0,1641.55,32.42,65.0,M-SC,24.55,220.0,0.79,1.43,63.80,OX40N,ATH,CABLES
68,SATIN,1.73,30.46,16.38,51.83,59041.0,84159.0,360443.0,274.00,16.95,59.0,H-SC,41.01,159.0,1.43,2.37,75.59,XY24,NTT,FINANCE

In [15]:
# top 5 to monitor for exit
df_tmp = df_portfolio_features[~df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])]
df_tmp = df_tmp[(df_tmp['Current P/L%'] > 0) ].sort_values(by = 'Dev%_PE', ascending=False)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
9,BANDHANBNK,-2.89,0.10,92.22,92.42,257147.0,282.0,278841.0,400.00,139.22,55.0,H-SC,23.40,174.0,0.00,1.83,53.61,XY24,NTT,BANKS
74,STARHEALTH,2.58,12.28,31.15,47.26,98327.0,34533.0,315656.0,761.00,77.10,78.0,H-SC,10.98,173.0,0.35,2.07,38.58,XY24,NTT,INSURANCE
25,FINCABLES,0.49,47.47,40.99,107.91,89245.0,70080.0,217724.0,1641.55,32.42,65.0,M-SC,24.55,220.0,0.79,1.43,63.80,OX40N,ATH,CABLES
68,SATIN,1.73,30.46,16.38,51.83,59041.0,84159.0,360443.0,274.00,16.95,59.0,H-SC,41.01,159.0,1.43,2.37,75.59,XY24,NTT,FINANCE
91,ZYDUSLIFE,-0.33,12.92,20.11,35.63,47590.0,27073.0,236647.0,1286.17,-1.80,55.0,H-MC,13.59,120.0,0.57,1.55,24.42,AR,ATH,PHARMA

In [16]:
# top 5 to book for rotation from weak conviction
df_tmp = df_portfolio_features[~df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])]
df_tmp = df_tmp[~df_tmp['Criteria'].isin(['XY25','XY24','X40', 'X40N'])].sort_values(by = 'RRR Ind', ascending=False)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
25,FINCABLES,0.49,47.47,40.99,107.91,89245.0,70080.0,217724.0,1641.55,32.42,65.0,M-SC,24.55,220.0,0.79,1.43,63.80,OX40N,ATH,CABLES
91,ZYDUSLIFE,-0.33,12.92,20.11,35.63,47590.0,27073.0,236647.0,1286.17,-1.80,55.0,H-MC,13.59,120.0,0.57,1.55,24.42,AR,ATH,PHARMA
73,SONACOMS,1.45,6.18,30.99,39.09,33288.0,6256.0,107415.0,804.02,-15.88,60.0,M-MC,18.49,193.0,0.19,0.71,51.95,AR,ATH,AUTO
75,SURYODAY,0.96,-0.27,23.37,23.03,41737.0,-479.0,178592.0,216.00,95.18,61.0,H-SC,18.92,166.0,-0.01,1.17,50.37,XR,NTT,BANKS
72,SIS,1.31,-1.30,22.86,21.26,25051.0,-1446.0,109586.0,528.00,2615.54,63.0,H-SC,22.93,168.0,-0.06,0.72,62.94,OX40N,NTT,MISC

In [17]:
# top 5 to accumulate based on lowest RSI_14
df_tmp = df_portfolio_features[df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])].sort_values(by = 'RSI_14', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
45,INFY,-6.75,-28.43,87.56,34.24,196089.0,-88940.0,223948.0,1972.00,-43.76,33.0,X-LC,16.78,3.0,-0.45,1.47,0.00,X40,NTT,IT
79,TCS,-3.55,-37.62,100.18,24.88,289520.0,-174273.0,289000.0,4253.91,-47.23,37.0,X-LC,19.14,2.0,-0.60,1.90,0.00,X40,ATH,IT
6,AWL,-3.72,-36.53,163.14,67.02,368938.0,-130161.0,226148.0,485.00,-65.82,40.0,X-SC,14.96,81.0,-0.35,1.49,7.53,XY24,NTT,FMCG
20,DABUR,-1.21,-17.20,73.55,43.70,151070.0,-42670.0,205398.0,735.00,-24.82,41.0,X-MC,11.38,70.0,-0.28,1.35,3.18,XY24,BTT,FMCG
28,GODREJCP,-0.85,-10.45,46.82,31.47,62308.0,-15534.0,133080.0,1469.04,-5.83,42.0,X-LC,9.52,32.0,-0.25,0.87,2.11,X40N,ATH,FMCG

In [18]:
# top 5 to accumulate based on Spread and CumlRnk
df_tmp = df_portfolio_features[df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])]
df_tmp = df_tmp[(df_tmp['CumlRnk'] < 100)].sort_values(by = 'Spread%', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
49,JSWINFRA,0.06,4.91,10.98,16.43,25545.0,10879.0,232653.0,342.00,-9.99,70.0,X-MC,2.09,61.0,0.43,1.53,31.91,X40N,NTT,REALTY
11,BERGEPAINT,9.04,1.49,23.48,25.32,61420.0,3834.0,261583.0,680.00,-4.06,67.0,X-MC,3.02,68.0,0.06,1.72,36.14,XY24,NTT,PAINTS
56,MEDANTA,0.60,8.28,17.40,27.12,33258.0,14619.0,191136.0,1486.00,4.95,62.0,X-SC,3.39,87.0,0.44,1.26,31.70,XY24,NTT,HEALTHCARE
57,PAGEIND,-0.51,4.26,28.12,33.59,78687.0,11446.0,279825.0,51217.29,-25.26,64.0,X-MC,3.53,55.0,0.15,1.84,32.89,X40,ATH,APPARELS
19,COLPAL,-1.46,-24.14,84.37,39.86,168554.0,-63585.0,199780.0,3683.41,-8.32,42.0,X-MC,3.68,62.0,-0.38,1.31,13.01,XY25,ATH,FMCG

In [19]:
# top 5 to accumulate based on lowest Gained%
df_tmp = df_portfolio_features[df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])].sort_values(by = 'Gained%', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
45,INFY,-6.75,-28.43,87.56,34.24,196089.0,-88940.0,223948.0,1972.00,-43.76,33.0,X-LC,16.78,3.0,-0.45,1.47,0.00,X40,NTT,IT
79,TCS,-3.55,-37.62,100.18,24.88,289520.0,-174273.0,289000.0,4253.91,-47.23,37.0,X-LC,19.14,2.0,-0.60,1.90,0.00,X40,ATH,IT
33,HCLTECH,-2.59,-26.56,65.45,21.51,116290.0,-64247.0,177677.0,1872.35,-22.66,42.0,X-LC,18.36,8.0,-0.55,1.17,1.99,X40,ATH,IT
28,GODREJCP,-0.85,-10.45,46.82,31.47,62308.0,-15534.0,133080.0,1469.04,-5.83,42.0,X-LC,9.52,32.0,-0.25,0.87,2.11,X40N,ATH,FMCG
58,PGHH,2.99,-30.50,89.95,32.01,133479.0,-65128.0,148392.0,17616.87,-53.03,46.0,X-MC,19.69,57.0,-0.49,0.98,3.14,X40,ATH,FMCG

In [20]:
# top 5 to accumulate based on lowest CurrAlloc%
df_tmp = df_portfolio_features[df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])].sort_values(by = 'CurrAlloc%', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
10,BATAINDIA,-5.34,-51.77,180.33,35.20,111911.0,-66611.0,62059.0,2096.00,-18.70,63.0,X-SC,24.00,91.0,-0.60,0.41,23.08,X40,NTT,FOOTWEAR
64,RELAXO,-3.26,-53.91,230.48,52.31,154191.0,-78260.0,66900.0,1176.00,-50.92,62.0,X-SC,16.51,92.0,-0.51,0.44,49.58,X40N,NTT,FOOTWEAR
60,QUESS,-0.03,2.48,69.69,73.90,76271.0,2650.0,109443.0,424.00,-44.90,78.0,X-SC,7.77,80.0,0.03,0.72,49.19,XY24,NTT,MISC
28,GODREJCP,-0.85,-10.45,46.82,31.47,62308.0,-15534.0,133080.0,1469.04,-5.83,42.0,X-LC,9.52,32.0,-0.25,0.87,2.11,X40N,ATH,FMCG
53,M&M,-1.97,-0.23,23.66,23.38,32737.0,-315.0,138366.0,3802.40,-15.48,49.0,X-LC,10.43,25.0,-0.01,0.91,4.90,X40N,ATH,AUTO

In [21]:
# top 5 to accumulate based on CumlRnk
df_tmp = df_portfolio_features.sort_values(by = 'CumlRnk', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
47,ITC,0.46,-22.96,54.53,19.06,142912.0,-78086.0,262080.0,452.00,-57.54,55.0,X-LC,15.05,1.0,-0.55,1.72,5.60,X40,NTT,FMCG
79,TCS,-3.55,-37.62,100.18,24.88,289520.0,-174273.0,289000.0,4253.91,-47.23,37.0,X-LC,19.14,2.0,-0.60,1.90,0.00,X40,ATH,IT
45,INFY,-6.75,-28.43,87.56,34.24,196089.0,-88940.0,223948.0,1972.00,-43.76,33.0,X-LC,16.78,3.0,-0.45,1.47,0.00,X40,NTT,IT
81,TMPV,-0.59,-18.17,66.90,36.58,194809.0,-64646.0,291195.0,600.00,-82.53,43.0,X-LC,11.36,4.0,-0.33,1.91,22.38,XY24,NTT,AUTO
59,PIDILITIND,-0.08,11.96,5.72,18.37,9037.0,16880.0,157990.0,1670.26,-21.61,74.0,X-LC,3.80,5.0,1.87,1.04,24.05,X40,ATH,CHEMICALS

In [22]:
# top 5 for average up
df_tmp = df_portfolio_features[(df_portfolio_features['Dev%_200'] > 5)].sort_values(by = 'CurrAlloc%', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
21,DEN,5.65,-37.34,126.72,42.07,67070.0,-31536.0,52928.0,75.00,89.12,77.0,M-SC,7.43,235.0,-0.47,0.35,43.95,AR,NTT,ENTERTAINMENT
44,INDUSINDBK,0.93,-30.05,89.98,32.89,48594.0,-23202.0,54005.0,1800.00,-354.20,61.0,L-MC,7.68,258.0,-0.48,0.35,32.93,XR,NTT,BANKS
3,ALKYLAMINE,3.03,-21.40,146.36,93.63,116140.0,-21611.0,79352.0,4546.37,-15.90,60.0,H-SC,6.85,142.0,-0.19,0.52,49.84,SR,ATH,CHEMICALS
73,SONACOMS,1.45,6.18,30.99,39.09,33288.0,6256.0,107415.0,804.02,-15.88,60.0,M-MC,18.49,193.0,0.19,0.71,51.95,AR,ATH,AUTO
72,SIS,1.31,-1.30,22.86,21.26,25051.0,-1446.0,109586.0,528.00,2615.54,63.0,H-SC,22.93,168.0,-0.06,0.72,62.94,OX40N,NTT,MISC

In [23]:
# top 5 RSP
df_tmp = df_portfolio_features.sort_values(by = 'RSP', ascending=False)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
18,COFFEEDAY,-0.38,-41.77,132.29,35.27,87477.0,-47424.0,66125.0,80.00,-55.73,57.0,L-SC,14.43,266.0,-0.54,0.43,63.07,XR,NTT,HOTELS
37,HONAUT,0.78,-2.87,55.79,51.31,104495.0,-5538.0,187300.0,58357.33,-19.19,68.0,X-SC,8.69,90.0,-0.05,1.23,42.30,X40N,ATH,ELECTRICAL
80,TITAGARH,-1.09,-13.15,67.81,45.74,142617.0,-31858.0,210319.0,1548.00,15.69,68.0,H-SC,6.52,175.0,-0.22,1.38,60.47,XY24,NTT,ENGINEERING
21,DEN,5.65,-37.34,126.72,42.07,67070.0,-31536.0,52928.0,75.00,89.12,77.0,M-SC,7.43,235.0,-0.47,0.35,43.95,AR,NTT,ENTERTAINMENT
64,RELAXO,-3.26,-53.91,230.48,52.31,154191.0,-78260.0,66900.0,1176.00,-50.92,62.0,X-SC,16.51,92.0,-0.51,0.44,49.58,X40N,NTT,FOOTWEAR

In [24]:
# Top N allocation
df_tmp = df_portfolio_features.sort_values(by = 'CurrAlloc%', ascending=False)
top_n_values = [10, 25, 50]

sum_df = pd.DataFrame({
    'Top_N': top_n_values,
    'Sum_Alloc%': [df_tmp['CurrAlloc%'].head(n).sum() for n in top_n_values]
})

sum_df

   Top_N  Sum_Alloc%
0     10       19.47
1     25       42.63
2     50       72.63

In [25]:
# market-cap-wise allocation
df_tmp = df_portfolio_features[cols]
df_tmp.groupby(df_tmp['Conviction'].str[-2:])['CurrAlloc%'].sum().sort_values(ascending=False)

Conviction
SC    43.59
LC    30.62
MC    25.77
Name: CurrAlloc%, dtype: float64

In [26]:
# criteria-wise allocation
df_portfolio_features.groupby('Criteria')['CurrAlloc%'].sum().sort_values(ascending=False)

Criteria
XY24     27.75
X40      24.70
X40N     17.30
XR        8.96
OX40N     7.11
AR        6.82
XY25      6.46
SR        0.88
Name: CurrAlloc%, dtype: float64

In [27]:
# conviction-wise allocation
df_portfolio_features.groupby('Conviction')['CurrAlloc%'].sum().sort_values(ascending=False)

Conviction
X-LC    28.55
H-SC    22.92
X-MC    20.77
M-SC    10.14
X-SC     9.93
H-MC     2.66
M-MC     1.99
H-LC     1.24
M-LC     0.83
L-SC     0.60
L-MC     0.35
Name: CurrAlloc%, dtype: float64

In [28]:
# sector-wise stats
df_tmp = df_portfolio_features.groupby('Category')[['CurrAlloc%', 'Current', 'Current P/L', 'FTT Amt']].sum().sort_values(by=['Current', 'Current P/L'], ascending=False)
df_tmp['Current P/L%'] = round(df_tmp['Current P/L'] * 100 / df_tmp['Current'], 2)
df_tmp['FTT%'] = round(df_tmp['FTT Amt'] * 100 / df_tmp['Current'], 2)
cols = ['CurrAlloc%', 'Current P/L%', 'FTT%']
df_tmp[cols].sort_values(by=['CurrAlloc%'], ascending=False)

               CurrAlloc%  Current P/L%    FTT%
Category
FMCG                14.61        -18.98   60.72
FINANCE             10.97        -10.47   58.51
IT                   9.76        -51.76  127.64
MISC                 7.20        -22.29   74.76
AUTO                 6.62         -8.70   49.45
BANKS                5.76         -3.41   51.22
PAINTS               5.64        -14.92   34.88
INSURANCE            5.39         -0.74   34.72
PHARMA               4.91          0.97   29.69
ELECTRICAL           4.09        -13.60   53.69
CHEMICALS            2.21        -20.64   92.54
HEALTHCARE           2.04        -15.56   45.71
APPARELS             1.84          4.09   28.12
AC                   1.83        -14.55   45.62
FOOTWEAR             1.74        -67.23  134.29
TRAVEL               1.62        -81.13  171.82
DURABLES             1.55        -64.30  104.27
REALTY               1.53          4.68   10.98
BREWERIES            1.49         -3.09   24.50
CERAMICS             1.44        -39.29   81.61
CABLES               1.43         32.19   40.99
ENGINEERING          1.38        -15.15   67.81
REFINERIES           1.11        -18.97   49.06
JEWELLERY            1.08        -95.52  163.45
CEMENT               1.06        -66.34  190.78
ENTERTAINMENT        0.83        -53.31  144.74
HOTELS               0.43        -71.72  132.29
TEXTILES             0.42        -44.04   85.11

In [29]:
# money to be made criteria-wise
df_portfolio_features.groupby('Criteria')['FTT Amt'].agg(['sum', 'count']).sort_values(by='sum', ascending=False)

                sum  count
Criteria
XY24      3376187.0     21
X40       1921948.0     19
XR        1317306.0     13
AR        1138897.0      9
X40N      1087143.0     13
OX40N      711115.0     10
XY25       450911.0      5
SR         284805.0      2

In [30]:
# money to be made conviction-wise
df_portfolio_features.groupby('Conviction')['FTT Amt'].agg(['sum', 'count']).sort_values(by='sum', ascending=False)

                  sum  count
Conviction
H-SC        3288641.0     24
X-LC        1939090.0     21
X-MC        1555368.0     15
M-SC        1377859.0     14
X-SC        1292960.0      9
H-MC         291901.0      2
L-SC         198907.0      2
M-LC         166243.0      1
M-MC          83145.0      2
L-MC          48594.0      1
H-LC          45604.0      1

In [31]:
# money to be made criteria and conviction-wise
df_portfolio_features.groupby(['Conviction', 'Criteria'])['FTT Amt'].agg(['sum', 'count']).sort_values(by='sum', ascending=False)

                           sum  count
Conviction Criteria
X-LC       X40       1048347.0     10
H-SC       XY24       973685.0      6
           AR         945345.0      5
M-SC       XY24       823781.0      6
X-SC       XY24       785997.0      4
H-SC       XR         781917.0      7
X-MC       X40        667184.0      7
           X40N       430244.0      4
X-LC       X40N       356353.0      6
           XY24       335923.0      2
H-SC       OX40N      302889.0      4
X-SC       X40N       300546.0      3
M-SC       OX40N      296796.0      5
H-SC       SR         284805.0      2
X-MC       XY25       245450.0      2
H-MC       XY24       244311.0      1
X-MC       XY24       212490.0      2
X-SC       X40        206417.0      2
M-SC       XR         190212.0      2
M-LC       XR         166243.0      1
X-LC       XY25       155604.0      2
L-SC       OX40N      111430.0      1
           XR          87477.0      1
M-SC       AR          67070.0      1
M-MC       XY25        49857.0      1
L-MC       XR          48594.0      1
H-MC       AR          47590.0      1
H-LC       AR          45604.0      1
X-LC       XR          42863.0      1
M-MC       AR          33288.0      1

In [32]:
# notebook execution time

end_time = time.time()
execution_time = round(end_time - start_time, 0)
print(f"Notebook execution time: {execution_time} seconds")

Notebook execution time: 30.0 seconds