<a href="https://colab.research.google.com/github/ankit-rathi/Quantvesting_v2/blob/main/myStocks_Portfolio_Analysis.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
'''
!pip install pandas==2.2.2 -qq
!pip install pyxirr -qq
!pip install ta -qq
!pip install yfinance==0.2.59 -qq
'''

'\n!pip install pandas==2.2.2 -qq\n!pip install pyxirr -qq\n!pip install ta -qq\n!pip install yfinance==0.2.59 -qq\n'

In [2]:
# import libraries

import numpy as np
import pandas as pd
import datetime
import warnings
warnings.filterwarnings('ignore')
import yfinance as yfin
import ta
import matplotlib.pyplot as plt
import requests

In [3]:
# notebook start time
import time
import datetime
import pytz

start_time = time.time()

# function to print date timestamp
def print_date_time():
  tz_NY = pytz.timezone('Asia/Kolkata')
  datetime_NY = datetime.datetime.now(tz_NY)
  print("Run date time (IST):", datetime_NY.strftime("%Y-%m-%d %H:%M:%S"))

In [4]:
# function to get booked and reserved amount
def get_amt():
  # fetch the JSON data from the URL
  url = "https://raw.githubusercontent.com/ankit-rathi/Tradevesting_v1/main/data/myPortfolioAmts.json"
  response = requests.get(url)
  pf_amts = response.json()  # parse the JSON data

  # extract values from the JSON
  py_booked_amt_dm = pf_amts["py_booked_amt_dm"]
  py_booked_amt_sv = pf_amts["py_booked_amt_sv"]
  cy_booked_amt_dm = pf_amts["cy_booked_amt_dm"]
  cy_booked_amt_sv = pf_amts["cy_booked_amt_sv"]
  reserve_amt_dm = pf_amts["reserve_amt_dm"]
  reserve_amt_sv = pf_amts["reserve_amt_sv"]

  # perform calculations
  py_booked_amt = py_booked_amt_dm + py_booked_amt_sv
  cy_booked_amt = cy_booked_amt_dm + cy_booked_amt_sv
  reserve_amt = reserve_amt_dm + reserve_amt_sv
  total_booked_amt = py_booked_amt + cy_booked_amt

  return total_booked_amt, reserve_amt, cy_booked_amt, py_booked_amt

gen_output = 0

In [5]:
# function to format the amount
def format_amt(number):
    abs_number = abs(number)

    if abs_number >= 1_00_00_000:  # Crores
        formatted_amt = f"{number / 1_00_00_000:.2f} C"
    elif abs_number >= 1_00_000:  # Lakhs
        formatted_amt = f"{number / 1_00_000:.2f} L"
    elif abs_number >= 1_000:  # Thousands
        formatted_amt = f"{number / 1_000:.2f} K"
    else:
        formatted_amt = f"{number:.2f}"

    return formatted_amt

# function to set start and end date
def get_start_end_date():
  start_date = (datetime.date.today() + datetime.timedelta(days=-365)).strftime('%Y-%m-%d')
  end_date = (datetime.date.today() + datetime.timedelta(days=1)).strftime('%Y-%m-%d')
  return start_date, end_date

# function to fetch my portfolio csv
def get_mypfs_df():
  mypfs_df = pd.read_csv('https://raw.githubusercontent.com/ankit-rathi/Tradevesting_v1/main/data/myPortfolioStocks.csv')
  return mypfs_df

# function to fetch my prospects csv
def get_mypps_df():
  mypps_df = pd.read_csv('https://raw.githubusercontent.com/ankit-rathi/Tradevesting_v1/main/data/myProspectsScrips.csv')
  return mypps_df

# function to fetch screener data
def get_myscreen_df():
  myscreen_df = pd.read_csv('https://raw.githubusercontent.com/ankit-rathi/Tradevesting_v1/main/data/myScreenerDB.csv')
  return myscreen_df

# function to fetch momentum data
def get_myinvmt_df():
  myinvmt_df = pd.read_csv('https://raw.githubusercontent.com/ankit-rathi/Tradevesting_v1/main/data/myInvestments.csv')
  return myinvmt_df

# function to get the stock ids
def get_stock_ids(df_pf):
  stock_n100 = df_pf['Symbol'].unique()

  exclude = ['CADILAHC','MMTC', 'MASFIN']

  stock_ids = df_pf[~df_pf['Symbol'].isin(exclude) ]['Symbol'].unique()

  #mypf = mypf[mypf.Forecast.notnull()]
  #stock_ids = mypf['Symbol'].unique()

  #stock_ids.sort()
  return stock_ids

# get features from screener data
def get_screener_features():
  myscreen_df = get_myscreen_df()
  cols = ['Symbol', 'EPS', 'MedPE', 'ROCE%', 'ROE%', 'CapType']
  return myscreen_df[cols]

# get relative strength
def get_relative_strength(stock_list):

    # Dictionary to store stock tickers and their corresponding percentage price change
    stock_changes = {}

    # Loop through each stock and fetch its price data
    for stock in stock_list:
        try:
            # Download the stock data for the given date range
            stock_data = yfin.Ticker(stock + '.NS').history(period='1mo', interval='1d')[map(str.title, ['open', 'close', 'low', 'high', 'volume'])]

            # Calculate the percentage change for the stock
            if len(stock_data) > 0:
                start_price = stock_data['Close'].iloc[0]
                end_price = stock_data['Close'].iloc[-1]
                percent_change = round(((end_price - start_price) / start_price) * 100, 2)
                stock_changes[stock] = percent_change
            else:
                stock_changes[stock] = np.nan  # If no data is available, set to NaN

        except Exception as e:
            print(f"Error fetching data for {stock}: {e}")
            stock_changes[stock] = np.nan

    # Create a DataFrame with stock tickers and their percentage changes
    df = pd.DataFrame(list(stock_changes.items()), columns=['Symbol', 'Percent_Change'])

    # Drop any stocks with missing data (NaN values)
    df = df.dropna()

    # Calculate the percentile rank based on percentage change
    df['RSP'] = round(df['Percent_Change'].rank(pct=True) * 100, 2)
    cols = ['Symbol', 'RSP']
    df = df[cols]
    # Sort by percentile rank (optional)
    df = df.sort_values(by='RSP', ascending=False).reset_index(drop=True)

    return df

In [6]:
# function to get stock technicals
def stock_prec_dev(stock_symbol):
    #stock_symbol = 'ULTRACEMCO.NS'
    short_window = 20
    mid_window = 50
    long_window = 200
    moving_avg = 'SMA'

    start = datetime.datetime(*map(int, start_date.split('-')))
    end = datetime.datetime(*map(int, end_date.split('-')))

    stock_df = yfin.Ticker(stock_symbol + '.NS').history(period='max', interval='1d')[map(str.title, ['open', 'close', 'low', 'high', 'volume'])]

    stock_df['Max'] = round(max(stock_df['Close']),2)
    stock_df = stock_df[(stock_df.index <= end_date) & (stock_df.index >= start_date)]
    stock_df['200_SMA'] = round(stock_df['Close'].rolling(window = 200, min_periods = 1).mean(),0)
    stock_df['Dev%_200'] = round((stock_df['Close'] - stock_df['200_SMA'])*100/stock_df['200_SMA'],2)
    stock_df.dropna(axis = 0, inplace = True) # remove any null rows

    stock_df['20_SMA'] = stock_df['Close'].rolling(window=20).mean()
    stock_df['50_SMA'] = stock_df['Close'].rolling(window=50).mean()
    stock_df['Symbol'] = stock_symbol

    stock_df['Close'] = round(stock_df['Close'],2)
    stock_df['Min'] = round(min(stock_df['Close']),2)
    stock_df['RSI_14'] = ta.momentum.RSIIndicator(close=stock_df['Close'], window=14).rsi()
    stock_df['RSI_14'] = round(stock_df['RSI_14'],0)
    stock_df['Prev_Close'] = stock_df['Close'].shift(1)
    stock_df.drop(['Open', 'Low', 'High', 'Volume'], axis=1, inplace=True)
    stock_df = stock_df.tail(1)

    max_SMA = max(stock_df['20_SMA'].item(), stock_df['50_SMA'].item(), stock_df['200_SMA'].item())
    min_SMA = min(stock_df['20_SMA'].item(), stock_df['50_SMA'].item(), stock_df['200_SMA'].item())
    ABS_Spread = max_SMA - min_SMA
    stock_df['Spread%'] = round((ABS_Spread / stock_df['200_SMA'].item()) * 100,2)

    return stock_df

# function to compute stock attributes
def get_common_features(stock_ids, df_mypf):

  df_prec_dev = pd.DataFrame()
  df_tmp = get_screener_features()
  df_rs = get_relative_strength(stock_ids)

  for stock_id in stock_ids:
      tmp = stock_prec_dev(stock_id)
      tmp = tmp.reset_index()
      df_prec_dev = pd.concat([df_prec_dev, tmp], ignore_index = True)
  df_prec_dev = pd.merge(df_prec_dev, df_mypf, on= 'Symbol')
  df_prec_dev = pd.merge(df_prec_dev, df_tmp, on= 'Symbol', how='left')
  df_prec_dev = pd.merge(df_prec_dev, df_rs, on= 'Symbol', how='left')
  #print(df_prec_dev.columns)
  df_prec_dev['Curr_PE'] = round(df_prec_dev['Close']/df_prec_dev['EPS'],1)
  df_prec_dev['Dev%_PE'] = round((df_prec_dev['Curr_PE'] - df_prec_dev['MedPE'])*100/df_prec_dev['MedPE'],2)
  df_prec_dev['Conviction'] = df_prec_dev['Conviction'] + '-' + df_prec_dev['CapType']
  return df_prec_dev

# function to arrange stock features
def arrange_features(df_stocks, common_cols, diff_cols):
  df_stocks_common = df_stocks[common_cols].drop_duplicates()
  df_stocks_diff = df_stocks[diff_cols]
  df_stocks_diff['Investment'] = df_stocks_diff['AvgCost'] * df_stocks_diff['Shares']
  df_stocks_diff = df_stocks_diff.groupby(['Symbol'])[['Shares', 'Investment']].aggregate(['sum']).reset_index()
  df_stocks_diff.columns = ['Symbol', 'Shares', 'Investment']
  df_stocks_diff['AvgCost'] = round(df_stocks_diff['Investment']/df_stocks_diff['Shares'],2)
  df_stocks = pd.merge(df_stocks_diff, df_stocks_common, on='Symbol')
  return df_stocks

# plot fact distribution across dimension
def plot_pie_chart(df, dimension, fact):
  # grouping the data by category and calculating the sum of fact for each type
  grouped_data = df.groupby(dimension)[fact].sum()

  # sorting the grouped data in descending order
  grouped_data = grouped_data.sort_values(ascending=False)

  # creating a pie chart
  grouped_data.plot.pie(autopct='%1.1f%%', startangle=90, figsize=(6, 6))

  # adding a title and displaying the plot
  plt.title(f'{dimension} {fact} Distribution')
  plt.ylabel('')  # To hide the y-label
  plt.show()

In [7]:
# function to get portfolio features

def get_portfolio_features(df_common_features):

  print_date_time()
  print('-------------------')

  #df_common_features["Target"] = df_common_features["Target"].fillna(df_common_features["Max"])
  df_common_features['NTT'] = np.where(df_common_features['Strategy']== 'NTT', df_common_features["Target"], df_common_features['Max'])
  df_common_features['LTT'] = np.where(df_common_features['Strategy']== 'BTT', df_common_features["Target"], df_common_features['Max'])
  df_common_features['BOL'] = df_common_features['Min']

  tmp_df = df_common_features[df_common_features['Symbol'].isin(mypf_df[mypf_df['InPortfolio'] != 'NA'].Symbol.values)]
  print('qualified stocks: '+str(len(tmp_df['Symbol'].unique())))
  tmp_df1 = tmp_df[tmp_df['LatestQtr'] == 1]
  print('with latest results: '+str(len(tmp_df1['Symbol'].unique())))
  tmp_df1 = tmp_df1[tmp_df1['StarStock'] == 1]
  print('still star stocks: '+str(len(tmp_df1['Symbol'].unique())))
  tmp_df['Investment'] = tmp_df['AvgCost'] * tmp_df['Shares']
  tmp_df['Current'] = round(tmp_df['Close'] * tmp_df['Shares'],0)
  tmp_df['Previous'] = tmp_df['Prev_Close'] * tmp_df['Shares']
  tmp_df['EstimatedST'] = tmp_df['NTT'] * tmp_df['Shares']
  tmp_df['EstimatedLT'] = tmp_df['LTT'] * tmp_df['Shares']
  tmp_df['Current P/L'] = round((tmp_df['Current'] - tmp_df['Investment']),0)
  tmp_df['Today P/L%'] = round((tmp_df['Current'] - tmp_df['Previous'])*100/tmp_df['Previous'],2)
  tmp_df['Current P/L%'] = round((tmp_df['Current'] - tmp_df['Investment'])*100/tmp_df['Investment'],2)
  tmp_df['EstimatedST P/L%'] = round((tmp_df['EstimatedST'] - tmp_df['Investment'])*100/tmp_df['Investment'],2)
  tmp_df['EstimatedLT P/L%'] = round((tmp_df['EstimatedLT'] - tmp_df['Investment'])*100/tmp_df['Investment'],2)
  tmp_df['NTT%'] = round((tmp_df['NTT'] - tmp_df['Close'])*100/tmp_df['Close'],2)
  tmp_df['LTT%'] = round((tmp_df['LTT'] - tmp_df['Close'])*100/tmp_df['Close'],2)
  tmp_df['Gained%'] = round((tmp_df['Close'] - tmp_df['BOL'])*100/tmp_df['BOL'],2)
  investment = round(sum(tmp_df['AvgCost']*tmp_df['Shares']),0)
  current = round(sum(tmp_df['Close']*tmp_df['Shares']),0)
  tmp_df['InitAlloc%'] = round(tmp_df['Investment']*100/investment,2)
  tmp_df['CurrAlloc%'] = round(tmp_df['Current']*100/current,2)
  tmp_df['FTT'] = tmp_df['LTT']
  tmp_df.loc[tmp_df['Strategy'] == 'NTT', 'FTT'] = tmp_df['NTT']
  tmp_df['FTT%'] = tmp_df['LTT%']
  tmp_df.loc[tmp_df['Strategy'] == 'NTT', 'FTT%'] = tmp_df['NTT%']
  tmp_df['FTT Amt'] = round(tmp_df['FTT%'] * tmp_df['Current']/100,0)
  tmp_df['OTT%'] = round((tmp_df['FTT'] - tmp_df['AvgCost'])*100/tmp_df['AvgCost'],2)
  tmp_df['RRR Ind'] = round(tmp_df['Current P/L']/tmp_df['FTT Amt'],2)
  tmp_df['Risk Ind'] = round(tmp_df['Current P/L%']*tmp_df['CurrAlloc%'],0)

  return tmp_df

# function to print portfolio features
def print_portfolio_stats(df_portfolio_features, myinvmt_df):
  from pyxirr import xirr

  total_booked_amt, reserve_amt, cy_booked_amt, py_booked_amt = get_amt()

  dates = myinvmt_df['Date'].values
  dates = np.append(dates, datetime.date.today().strftime('%d-%b-%y'))
  investment = myinvmt_df['Investment'].values
  dates= pd.to_datetime(dates)

  current = round(sum(df_portfolio_features['Close']*df_portfolio_features['Shares']),0) + reserve_amt
  investment_xirr = np.append(investment, current)
  cagr = round(xirr(pd.DataFrame({"dates": dates, "amounts": investment_xirr}))*100,2)

  investment = -sum(investment)
  invested = round(sum(df_portfolio_features['AvgCost']*df_portfolio_features['Shares']),0) + reserve_amt
  previous = round(sum(df_portfolio_features['Prev_Close']*df_portfolio_features['Shares']),0) + reserve_amt
  cy_invested = investment + py_booked_amt

  today_pnl_amount = current-previous
  today_pnl_percentage = round((current-previous)*100/previous,2)

  curr_pnl_amount = current-invested
  curr_pnl_percentage = round((curr_pnl_amount)*100/(cy_invested),2)

  cy_pnl_amount = cy_booked_amt + curr_pnl_amount
  cy_pnl_percentage = round((cy_pnl_amount)*100/cy_invested,2)

  overall_pnl_amount = total_booked_amt + curr_pnl_amount
  overall_pnl_percentage = round((overall_pnl_amount)*100/investment,2)

  estimate_st = round(sum(df_portfolio_features['FTT']*df_portfolio_features['Shares']),0)  + reserve_amt
  est_st_pnl_amount = estimate_st-current
  est_st_pnl_percentage = round((est_st_pnl_amount)*100/current,2)

  estimate_lt = round(sum(df_portfolio_features['LTT']*df_portfolio_features['Shares']),0)  + reserve_amt
  est_lt_pnl_amount = estimate_lt-current
  est_lt_pnl_percentage = round((est_lt_pnl_amount)*100/current,2)

  total_profit = round(sum(df_portfolio_features[df_portfolio_features['Current P/L%'] > 0]['Current']) - sum(df_portfolio_features[df_portfolio_features['Current P/L%'] > 0]['Investment']),0)
  total_loss = round(sum(df_portfolio_features[df_portfolio_features['Current P/L%'] < 0]['Current']) - sum(df_portfolio_features[df_portfolio_features['Current P/L%'] < 0]['Investment']),0)

  cy_booked_percentage = round((cy_booked_amt)*100/current,2)
  py_booked_percentage = round((py_booked_amt)*100/investment,2)
  total_booked_percentage = round((total_booked_amt)*100/investment,2)

  print('-------------------')
  print('Initial Investment: ', format_amt(investment))
  print('CY Investment: ', format_amt(cy_invested))
  print('Reserve: ', format_amt(reserve_amt))
  print('Current: ',  format_amt(current))
  print('-------------------')
  print('Today PnL: '+ '{} ({}%)'.format(format_amt(today_pnl_amount), today_pnl_percentage))
  print('Current PnL: '+ '{} ({}%)'.format(format_amt(curr_pnl_amount), curr_pnl_percentage))
  print('CY Booked + Current PnL: '+ '{} ({}%)'.format(format_amt(cy_pnl_amount), cy_pnl_percentage))
  print('-------------------')
  print('Total profit: ', format_amt(total_profit))
  print('Total loss: ', format_amt(total_loss))
  print('-------------------')
  print('Total Booked + Current PnL: '+ '{} ({}%)'.format(format_amt(overall_pnl_amount), overall_pnl_percentage))
  print('Total Booked PnL: '+ '{} ({}%)'.format(format_amt(total_booked_amt), total_booked_percentage))
  print('Curr Year Booked PnL: '+ '{} ({}%)'.format(format_amt(cy_booked_amt), cy_booked_percentage))
  print('Prev Year Booked PnL: '+ '{} ({}%)'.format(format_amt(py_booked_amt), py_booked_percentage))
  print('===================')
  print('Est FTT: ',  format_amt(estimate_st))
  print('Est FTT PnL: '+ '{} ({}%)'.format(format_amt(est_st_pnl_amount), est_st_pnl_percentage))

  print('===================')
  print('Deployed: ', format_amt(investment))

  print('Current: ', format_amt(current))

  print('CAGR/XIRR %: '+'{}%'.format(cagr))

In [8]:
# get start and end date
start_date, end_date = get_start_end_date()

# get portfolio and prospects data
mypfs_df = get_mypfs_df()
mypps_df = get_mypps_df()
myinvmt_df = get_myinvmt_df()

# merge above datasets
mypf_df = pd.merge(mypfs_df, mypps_df, on="Symbol")

# seggregate dm and sv portfolio
dm_pf = mypf_df[mypf_df['InPortfolio'] == 'DM']
sv_pf = mypf_df[mypf_df['InPortfolio'] == 'SV']

# build portfolio stock dataframe
dm_stocks = get_stock_ids(dm_pf)
sv_stocks = get_stock_ids(sv_pf)
df_stocks = pd.concat([dm_pf,sv_pf], ignore_index = True)

# arrange common and diff stock features
common_cols = ['Symbol', 'Target', 'Criteria', 'Strategy', 'CumlRnk', 'LatestQtr', 'StarStock', 'Conviction', 'Category', 'InFolio', 'XIRR', 'MBQ']
diff_cols = ['Symbol', 'AvgCost', 'Shares']
df_stocks = arrange_features(df_stocks, common_cols, diff_cols)

# get common features
stock_ids = df_stocks['Symbol'].values
df_common_features = get_common_features(stock_ids, df_stocks)

df_common_features.reset_index(drop=True, inplace=True)
df_common_features.drop(['Date'], axis=1, inplace=True)
# get and print portfolio features
df_portfolio_features = get_portfolio_features(df_common_features)

print_portfolio_stats(df_portfolio_features, myinvmt_df)

df = df_portfolio_features
#plot_pie_chart(df, 'CapType', 'Current')
list_ox40n = list(df[df['MBQ'].str.contains('OX40N', na=False)]['Symbol'].values)

Run date time (IST): 2026-05-13 16:46:28
-------------------
qualified stocks: 92
with latest results: 31
still star stocks: 20
-------------------
Initial Investment:  1.40 C
CY Investment:  1.82 C
Reserve:  1.49 K
Current:  1.47 C
-------------------
Today PnL: 41.99 K (0.29%)
Current PnL: -35.95 L (-19.71%)
CY Booked + Current PnL: -33.87 L (-18.57%)
-------------------
Total profit:  1.64 L
Total loss:  -37.59 L
-------------------
Total Booked + Current PnL: 9.00 L (6.45%)
Total Booked PnL: 44.95 L (32.22%)
Curr Year Booked PnL: 2.08 L (1.41%)
Prev Year Booked PnL: 42.87 L (30.73%)
===================
Est FTT:  2.55 C
Est FTT PnL: 1.08 C (73.5%)
===================
Deployed:  1.40 C
Current:  1.47 C
CAGR/XIRR %: 2.63%

In [9]:
# top 5 near their targets
cols = ['Symbol', 'Today P/L%', 'Current P/L%', 'FTT%', 'OTT%', 'FTT Amt', 'Current P/L', 'Current', 'FTT', 'Dev%_PE', 'RSI_14','Conviction', 'Spread%',  'CumlRnk', 'RRR Ind', 'CurrAlloc%', 'Gained%', 'Criteria', 'Strategy', 'Category']
df_tmp = df_portfolio_features[~df_portfolio_features['Symbol'].isin(['ENRIN','BLUSPRING','DIGITIDE'])]
df_tmp = df_tmp.sort_values(by = 'FTT Amt', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
55,MASFIN,-1.93,-0.46,22.13,21.57,21583.0,-450.0,97530.0,397.04,-14.18,48.0,H-SC,5.57,167.0,-0.02,0.66,22.67,XR,ATH,FINANCE
59,PIDILITIND,-0.51,2.44,15.54,18.37,22465.0,3450.0,144560.0,1670.26,-28.20,59.0,X-LC,5.53,5.0,0.15,0.98,13.51,X40,ATH,CHEMICALS
51,KOTAKBANK,0.44,0.91,20.02,21.11,27974.0,1258.0,139730.0,453.24,-13.31,50.0,X-LC,7.35,12.0,0.04,0.95,6.86,X40,ATH,BANKS
53,M&M,-2.02,0.97,22.19,23.38,31073.0,1350.0,140031.0,3802.40,-14.43,45.0,X-LC,8.07,25.0,0.04,0.95,6.16,X40N,ATH,AUTO
83,TTKPRESTIG,0.45,-30.96,44.98,0.09,31294.0,-31203.0,69574.0,770.00,61.58,59.0,M-SC,17.09,250.0,-1.00,0.47,23.89,OX40N,NTT,DURABLES

In [10]:
# top 5 today
df_tmp = df_portfolio_features.sort_values(by = 'Today P/L%', ascending=False)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
22,DIXON,9.73,-18.96,70.19,37.92,148351.0,-49442.0,211356.0,18931.72,-65.54,53.0,X-MC,22.09,54.0,-0.33,1.44,15.00,X40N,ATH,IT
24,EASEMYTRIP,7.35,-56.46,234.60,45.70,180621.0,-99824.0,76991.0,26.40,-20.01,54.0,M-SC,6.83,204.0,-0.55,0.52,34.87,XY24,NTT,TRAVEL
43,INDIGOPNTS,4.94,-30.00,42.88,0.02,52398.0,-52363.0,122196.0,1408.00,86.38,70.0,M-SC,20.61,222.0,-1.00,0.83,38.64,OX40N,NTT,PAINTS
4,ASIANPAINT,4.47,-5.80,32.19,24.52,85946.0,-16444.0,266995.0,3460.25,-4.98,65.0,X-LC,6.88,30.0,-0.19,1.81,23.40,X40,ATH,PAINTS
11,BERGEPAINT,4.02,-6.44,33.94,25.32,81849.0,-16591.0,241158.0,680.00,-11.47,65.0,X-MC,12.10,68.0,-0.20,1.64,25.51,XY24,NTT,PAINTS

In [11]:
# bottom 5 today
df_tmp = df_portfolio_features.sort_values(by = 'Today P/L%', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
13,BSOFT,-3.89,-42.22,160.97,50.79,130817.0,-59385.0,81268.0,831.70,-25.78,26.0,H-SC,5.14,172.0,-0.45,0.55,0.00,XR,ATH,IT
69,SFL,-2.92,-46.83,138.16,26.63,192627.0,-122795.0,139423.0,1287.00,5.54,51.0,M-SC,13.37,242.0,-0.64,0.95,16.20,XY24,NTT,MISC
89,WHIRLPOOL,-2.70,-32.80,170.71,81.92,131698.0,-37651.0,77147.0,2270.00,-60.62,34.0,M-SC,16.89,210.0,-0.29,0.52,8.37,XR,NTT,DURABLES
20,DABUR,-2.14,-9.46,58.71,43.70,131865.0,-23464.0,224604.0,735.00,-17.81,54.0,X-MC,9.10,70.0,-0.18,1.53,12.83,XY24,BTT,FMCG
42,INDIAMART,-2.12,-15.38,144.29,106.72,150593.0,-18968.0,104368.0,4810.62,-61.91,31.0,H-SC,9.34,140.0,-0.13,0.71,0.27,AR,ATH,MISC

In [12]:
# top 5 to exit based on CumlRnk
df_tmp = df_portfolio_features[~df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])]
df_tmp = df_tmp[(df_tmp['Current P/L%'] > -1) & (df_tmp['Current P/L%'] < 1)].sort_values(by = 'CumlRnk', ascending=False)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
55,MASFIN,-1.93,-0.46,22.13,21.57,21583.0,-450.0,97530.0,397.04,-14.18,48.0,H-SC,5.57,167.0,-0.02,0.66,22.67,XR,ATH,FINANCE
91,ZYDUSLIFE,0.92,-0.95,36.94,35.63,76678.0,-2000.0,207574.0,1286.17,-13.96,56.0,H-MC,3.35,120.0,-0.03,1.41,9.14,AR,ATH,PHARMA

In [13]:
# OX40N stocks to exit
df_tmp = df_portfolio_features[(df_portfolio_features['Symbol'].isin(list_ox40n))].sort_values(by = 'Current P/L%', ascending=False)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
25,FINCABLES,0.39,36.49,52.33,107.91,105456.0,53877.0,201521.0,1641.55,22.78,65.0,M-SC,22.40,220.0,0.51,1.37,51.61,OX40N,ATH,CABLES
72,SIS,0.13,-14.12,41.20,21.26,39287.0,-15675.0,95357.0,528.00,2262.69,61.0,H-SC,12.57,168.0,-0.40,0.65,41.78,OX40N,NTT,MISC
16,CERA,-1.98,-24.05,63.11,23.89,84319.0,-42296.0,133607.0,9475.00,-26.73,64.0,H-SC,9.84,153.0,-0.50,0.91,28.40,OX40N,NTT,CERAMICS
50,KANSAINER,2.30,-26.99,55.43,13.47,109128.0,-72792.0,196875.0,340.00,-37.29,66.0,H-SC,15.13,162.0,-0.67,1.34,37.52,XY24,NTT,PAINTS
43,INDIGOPNTS,4.94,-30.00,42.88,0.02,52398.0,-52363.0,122196.0,1408.00,86.38,70.0,M-SC,20.61,222.0,-1.00,0.83,38.64,OX40N,NTT,PAINTS

In [14]:
# top 5 to book for rotation
df_tmp = df_portfolio_features[(df_portfolio_features['Current P/L%'] > 20) ].sort_values(by = 'CumlRnk', ascending=False)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
25,FINCABLES,0.39,36.49,52.33,107.91,105456.0,53877.0,201521.0,1641.55,22.78,65.0,M-SC,22.40,220.0,0.51,1.37,51.61,OX40N,ATH,CABLES
68,SATIN,0.16,24.93,21.53,51.83,74314.0,68880.0,345164.0,274.00,11.70,85.0,H-SC,22.21,159.0,0.93,2.34,68.15,XY24,NTT,FINANCE

In [15]:
# top 5 to monitor for exit
df_tmp = df_portfolio_features[~df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])]
df_tmp = df_tmp[(df_tmp['Current P/L%'] > 0) ].sort_values(by = 'Dev%_PE', ascending=False)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
25,FINCABLES,0.39,36.49,52.33,107.91,105456.0,53877.0,201521.0,1641.55,22.78,65.0,M-SC,22.40,220.0,0.51,1.37,51.61,OX40N,ATH,CABLES
68,SATIN,0.16,24.93,21.53,51.83,74314.0,68880.0,345164.0,274.00,11.70,85.0,H-SC,22.21,159.0,0.93,2.34,68.15,XY24,NTT,FINANCE
73,SONACOMS,1.24,2.30,35.96,39.09,37214.0,2327.0,103486.0,804.02,-18.98,58.0,M-MC,19.89,193.0,0.06,0.70,46.40,AR,ATH,AUTO

In [16]:
# top 5 to book for rotation from weak conviction
df_tmp = df_portfolio_features[~df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])]
df_tmp = df_tmp[~df_tmp['Criteria'].isin(['XY25','XY24','X40', 'X40N'])].sort_values(by = 'RRR Ind', ascending=False)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
25,FINCABLES,0.39,36.49,52.33,107.91,105456.0,53877.0,201521.0,1641.55,22.78,65.0,M-SC,22.40,220.0,0.51,1.37,51.61,OX40N,ATH,CABLES
73,SONACOMS,1.24,2.30,35.96,39.09,37214.0,2327.0,103486.0,804.02,-18.98,58.0,M-MC,19.89,193.0,0.06,0.70,46.40,AR,ATH,AUTO
55,MASFIN,-1.93,-0.46,22.13,21.57,21583.0,-450.0,97530.0,397.04,-14.18,48.0,H-SC,5.57,167.0,-0.02,0.66,22.67,XR,ATH,FINANCE
91,ZYDUSLIFE,0.92,-0.95,36.94,35.63,76678.0,-2000.0,207574.0,1286.17,-13.96,56.0,H-MC,3.35,120.0,-0.03,1.41,9.14,AR,ATH,PHARMA
75,SURYODAY,0.63,-1.04,24.33,23.03,43114.0,-1866.0,177205.0,216.00,92.98,73.0,H-SC,13.33,166.0,-0.04,1.20,49.20,XR,NTT,BANKS

In [17]:
# top 5 to accumulate based on lowest RSI_14
df_tmp = df_portfolio_features[df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])].sort_values(by = 'RSI_14', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
33,HCLTECH,-0.23,-25.81,63.78,21.51,114474.0,-62442.0,179482.0,1872.35,-22.25,26.0,X-LC,14.66,8.0,-0.55,1.22,0.00,X40,ATH,IT
79,TCS,-1.20,-33.28,89.70,26.57,277264.0,-154172.0,309101.0,4311.59,-43.63,28.0,X-LC,14.89,2.0,-0.56,2.10,0.00,X40,ATH,IT
45,INFY,-1.51,-23.54,75.59,34.24,180826.0,-73668.0,239220.0,1972.00,-39.77,30.0,X-LC,16.98,3.0,-0.41,1.63,0.00,X40,NTT,IT
88,VOLTAS,-0.84,-1.52,47.43,45.20,89564.0,-2907.0,188835.0,1856.00,12.74,33.0,X-MC,1.62,79.0,-0.03,1.28,3.17,XY25,NTT,AC
37,HONAUT,-0.84,-26.84,106.83,51.31,150710.0,-51763.0,141075.0,58357.33,-39.15,36.0,X-SC,12.34,90.0,-0.34,0.96,7.18,X40N,ATH,ELECTRICAL

In [18]:
# top 5 to accumulate based on Spread and CumlRnk
df_tmp = df_portfolio_features[df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])]
df_tmp = df_tmp[(df_tmp['CumlRnk'] < 100)].sort_values(by = 'Spread%', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
88,VOLTAS,-0.84,-1.52,47.43,45.20,89564.0,-2907.0,188835.0,1856.00,12.74,33.0,X-MC,1.62,79.0,-0.03,1.28,3.17,XY25,NTT,AC
84,UNITDSPR,0.71,-7.71,30.85,20.77,66667.0,-18043.0,216101.0,1644.00,-18.18,39.0,X-MC,2.78,64.0,-0.27,1.47,3.09,X40N,NTT,BREWERIES
65,RELIANCE,-0.38,-12.78,43.66,25.30,76529.0,-25678.0,175285.0,1952.00,-15.03,43.0,X-LC,3.52,21.0,-0.34,1.19,4.15,XY25,BTT,REFINERIES
39,ICICIGI,1.20,-4.43,24.87,19.34,47563.0,-8864.0,191245.0,2252.93,-19.59,50.0,X-MC,4.57,66.0,-0.19,1.30,6.81,X40,ATH,INSURANCE
19,COLPAL,0.44,-18.95,74.60,41.51,159234.0,-49915.0,213450.0,3726.84,-2.04,55.0,X-MC,5.26,62.0,-0.31,1.45,19.33,XY25,ATH,FMCG

In [19]:
# top 5 to accumulate based on lowest Gained%
df_tmp = df_portfolio_features[df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])].sort_values(by = 'Gained%', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
45,INFY,-1.51,-23.54,75.59,34.24,180826.0,-73668.0,239220.0,1972.00,-39.77,30.0,X-LC,16.98,3.0,-0.41,1.63,0.00,X40,NTT,IT
33,HCLTECH,-0.23,-25.81,63.78,21.51,114474.0,-62442.0,179482.0,1872.35,-22.25,26.0,X-LC,14.66,8.0,-0.55,1.22,0.00,X40,ATH,IT
79,TCS,-1.20,-33.28,89.70,26.57,277264.0,-154172.0,309101.0,4311.59,-43.63,28.0,X-LC,14.89,2.0,-0.56,2.10,0.00,X40,ATH,IT
32,HAVELLS,0.70,-23.22,72.02,32.08,181369.0,-76159.0,251832.0,2062.85,-27.80,39.0,X-MC,10.83,63.0,-0.42,1.71,1.58,X40,ATH,ELECTRICAL
34,HDFCBANK,-0.11,-10.32,43.14,28.37,90869.0,-24247.0,210638.0,1073.00,-23.99,37.0,X-LC,15.83,26.0,-0.27,1.43,2.47,X40,BTT,BANKS

In [20]:
# top 5 to accumulate based on lowest CurrAlloc%
df_tmp = df_portfolio_features[df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])].sort_values(by = 'CurrAlloc%', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
64,RELAXO,-0.95,-62.88,310.26,52.31,167199.0,-91270.0,53890.0,1176.00,-60.51,41.0,X-SC,24.74,92.0,-0.55,0.37,20.49,X40N,NTT,FOOTWEAR
10,BATAINDIA,0.24,-54.76,198.87,35.20,115758.0,-70462.0,58208.0,2096.00,-23.75,41.0,X-SC,26.22,91.0,-0.61,0.40,15.44,X40,NTT,FOOTWEAR
60,QUESS,-0.34,-14.73,103.93,73.90,94644.0,-15728.0,91065.0,424.00,-54.27,56.0,X-SC,12.76,80.0,-0.17,0.62,24.14,XY24,NTT,MISC
28,GODREJCP,0.03,-7.78,42.56,31.47,58331.0,-11558.0,137056.0,1469.04,-2.98,43.0,X-LC,7.14,32.0,-0.20,0.93,5.16,X40N,ATH,FMCG
51,KOTAKBANK,0.44,0.91,20.02,21.11,27974.0,1258.0,139730.0,453.24,-13.31,50.0,X-LC,7.35,12.0,0.04,0.95,6.86,X40,ATH,BANKS

In [21]:
# top 5 to accumulate based on CumlRnk
df_tmp = df_portfolio_features.sort_values(by = 'CumlRnk', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
47,ITC,1.25,-19.81,48.46,19.06,132193.0,-67379.0,272787.0,452.00,-55.92,47.0,X-LC,15.66,1.0,-0.51,1.85,5.82,X40,NTT,FMCG
79,TCS,-1.20,-33.28,89.70,26.57,277264.0,-154172.0,309101.0,4311.59,-43.63,28.0,X-LC,14.89,2.0,-0.56,2.10,0.00,X40,ATH,IT
45,INFY,-1.51,-23.54,75.59,34.24,180826.0,-73668.0,239220.0,1972.00,-39.77,30.0,X-LC,16.98,3.0,-0.41,1.63,0.00,X40,NTT,IT
81,TMPV,-0.00,-23.32,78.12,36.58,213149.0,-82993.0,272848.0,600.00,-83.62,45.0,X-LC,5.55,4.0,-0.39,1.85,13.72,XY24,NTT,AUTO
59,PIDILITIND,-0.51,2.44,15.54,18.37,22465.0,3450.0,144560.0,1670.26,-28.20,59.0,X-LC,5.53,5.0,0.15,0.98,13.51,X40,ATH,CHEMICALS

In [22]:
# top 5 for average up
df_tmp = df_portfolio_features[(df_portfolio_features['Dev%_200'] > 5)].sort_values(by = 'CurrAlloc%', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
44,INDUSINDBK,-0.04,-34.11,101.68,32.89,51727.0,-26334.0,50872.0,1800.00,-339.50,51.0,L-MC,7.04,258.0,-0.51,0.35,25.22,XR,NTT,BANKS
72,SIS,0.13,-14.12,41.20,21.26,39287.0,-15675.0,95357.0,528.00,2262.69,61.0,H-SC,12.57,168.0,-0.40,0.65,41.78,OX40N,NTT,MISC
73,SONACOMS,1.24,2.30,35.96,39.09,37214.0,2327.0,103486.0,804.02,-18.98,58.0,M-MC,19.89,193.0,0.06,0.70,46.40,AR,ATH,AUTO
5,ATULAUTO,2.98,-15.30,71.86,45.57,119988.0,-30158.0,166974.0,844.00,3618.92,57.0,M-SC,6.94,248.0,-0.25,1.13,28.49,XY24,NTT,AUTO
75,SURYODAY,0.63,-1.04,24.33,23.03,43114.0,-1866.0,177205.0,216.00,92.98,73.0,H-SC,13.33,166.0,-0.04,1.20,49.20,XR,NTT,BANKS

In [23]:
# top 5 RSP
df_tmp = df_portfolio_features.sort_values(by = 'RSP', ascending=False)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
68,SATIN,0.16,24.93,21.53,51.83,74314.0,68880.0,345164.0,274.00,11.70,85.0,H-SC,22.21,159.0,0.93,2.34,68.15,XY24,NTT,FINANCE
75,SURYODAY,0.63,-1.04,24.33,23.03,43114.0,-1866.0,177205.0,216.00,92.98,73.0,H-SC,13.33,166.0,-0.04,1.20,49.20,XR,NTT,BANKS
25,FINCABLES,0.39,36.49,52.33,107.91,105456.0,53877.0,201521.0,1641.55,22.78,65.0,M-SC,22.40,220.0,0.51,1.37,51.61,OX40N,ATH,CABLES
72,SIS,0.13,-14.12,41.20,21.26,39287.0,-15675.0,95357.0,528.00,2262.69,61.0,H-SC,12.57,168.0,-0.40,0.65,41.78,OX40N,NTT,MISC
43,INDIGOPNTS,4.94,-30.00,42.88,0.02,52398.0,-52363.0,122196.0,1408.00,86.38,70.0,M-SC,20.61,222.0,-1.00,0.83,38.64,OX40N,NTT,PAINTS

In [24]:
# Top N allocation
df_tmp = df_portfolio_features.sort_values(by = 'CurrAlloc%', ascending=False)
top_n_values = [10, 25, 50]

sum_df = pd.DataFrame({
    'Top_N': top_n_values,
    'Sum_Alloc%': [df_tmp['CurrAlloc%'].head(n).sum() for n in top_n_values]
})

sum_df

   Top_N  Sum_Alloc%
0     10       19.24
1     25       42.61
2     50       72.89

In [25]:
# market-cap-wise allocation
df_tmp = df_portfolio_features[cols]
df_tmp.groupby(df_tmp['Conviction'].str[-2:])['CurrAlloc%'].sum().sort_values(ascending=False)

Conviction
SC    42.84
LC    31.26
MC    25.89
Name: CurrAlloc%, dtype: float64

In [26]:
# criteria-wise allocation
df_portfolio_features.groupby('Criteria')['CurrAlloc%'].sum().sort_values(ascending=False)

Criteria
XY24     27.51
X40      25.50
X40N     16.70
XR        9.00
OX40N     7.06
XY25      6.75
AR        6.63
SR        0.84
Name: CurrAlloc%, dtype: float64

In [27]:
# conviction-wise allocation
df_portfolio_features.groupby('Conviction')['CurrAlloc%'].sum().sort_values(ascending=False)

Conviction
X-LC    29.17
H-SC    22.52
X-MC    20.95
M-SC    10.11
X-SC     9.69
H-MC     2.60
M-MC     1.99
H-LC     1.20
M-LC     0.89
L-SC     0.52
L-MC     0.35
Name: CurrAlloc%, dtype: float64

In [28]:
# sector-wise stats
df_tmp = df_portfolio_features.groupby('Category')[['CurrAlloc%', 'Current', 'Current P/L', 'FTT Amt']].sum().sort_values(by=['Current', 'Current P/L'], ascending=False)
df_tmp['Current P/L%'] = round(df_tmp['Current P/L'] * 100 / df_tmp['Current'], 2)
df_tmp['FTT%'] = round(df_tmp['FTT Amt'] * 100 / df_tmp['Current'], 2)
cols = ['CurrAlloc%', 'Current P/L%', 'FTT%']
df_tmp[cols].sort_values(by=['CurrAlloc%'], ascending=False)

               CurrAlloc%  Current P/L%    FTT%
Category
FMCG                15.48        -16.13   57.05
FINANCE             10.94        -14.44   64.21
IT                  10.18        -50.52  126.30
MISC                 6.96        -31.17   88.15
AUTO                 6.64        -11.78   53.69
BANKS                5.70         -8.17   58.19
PAINTS               5.62        -19.12   39.81
INSURANCE            5.37         -4.58   40.17
PHARMA               4.95         -1.66   34.33
ELECTRICAL           3.87        -24.13   68.31
CHEMICALS            2.13        -29.64  106.90
HEALTHCARE           1.99        -22.09   53.95
AC                   1.82        -19.24   51.57
TRAVEL               1.71        -77.68  166.65
FOOTWEAR             1.70        -77.64  148.87
DURABLES             1.68        -55.60   93.45
APPARELS             1.68         -8.52   45.54
BREWERIES            1.47         -8.35   30.85
CERAMICS             1.38        -51.51   97.55
REALTY               1.37         -9.63   27.64
CABLES               1.37         26.74   52.33
ENGINEERING          1.20        -37.26  100.04
REFINERIES           1.19        -14.65   43.66
CEMENT               1.11        -63.52  185.86
JEWELLERY            1.03       -110.74  183.96
ENTERTAINMENT        0.71        -82.64  191.56
TEXTILES             0.42        -49.10   91.62
HOTELS               0.32       -138.28  222.32

In [29]:
# money to be made criteria-wise
df_portfolio_features.groupby('Criteria')['FTT Amt'].agg(['sum', 'count']).sort_values(by='sum', ascending=False)

                sum  count
Criteria
XY24      3546232.0     21
X40       1948688.0     19
XR        1356249.0     13
X40N      1266518.0     13
AR        1207597.0      9
OX40N      753374.0     10
XY25       445510.0      5
SR         296398.0      2

In [30]:
# money to be made conviction-wise
df_portfolio_features.groupby('Conviction')['FTT Amt'].agg(['sum', 'count']).sort_values(by='sum', ascending=False)

                  sum  count
Conviction
H-SC        3471553.0     24
X-LC        2002685.0     21
X-MC        1649718.0     15
M-SC        1427242.0     14
X-SC        1378170.0      9
H-MC         315605.0      2
L-SC         213616.0      2
M-LC         161376.0      1
M-MC          91917.0      2
H-LC          56957.0      1
L-MC          51727.0      1

In [31]:
# money to be made criteria and conviction-wise
df_portfolio_features.groupby(['Conviction', 'Criteria'])['FTT Amt'].agg(['sum', 'count']).sort_values(by='sum', ascending=False)

                           sum  count
Conviction Criteria
H-SC       XY24      1075093.0      6
X-LC       X40       1059077.0     10
H-SC       AR         958684.0      5
M-SC       XY24       853731.0      6
H-SC       XR         802736.0      7
X-SC       XY24       797616.0      4
X-MC       X40        681441.0      7
           X40N       505765.0      4
X-LC       X40N       388369.0      6
X-SC       X40N       372384.0      3
X-LC       XY24       367151.0      2
H-SC       OX40N      338642.0      4
M-SC       OX40N      307060.0      5
H-SC       SR         296398.0      2
X-MC       XY25       248798.0      2
H-MC       XY24       238927.0      1
X-MC       XY24       213714.0      2
X-SC       X40        208170.0      2
M-SC       XR         188387.0      2
M-LC       XR         161376.0      1
X-LC       XY25       142009.0      2
L-SC       OX40N      107672.0      1
           XR         105944.0      1
M-SC       AR          78064.0      1
H-MC       AR          76678.0      1
H-LC       AR          56957.0      1
M-MC       XY25        54703.0      1
L-MC       XR          51727.0      1
X-LC       XR          46079.0      1
M-MC       AR          37214.0      1

In [32]:
# notebook execution time

end_time = time.time()
execution_time = round(end_time - start_time, 0)
print(f"Notebook execution time: {execution_time} seconds")

Notebook execution time: 27.0 seconds