<a href="https://colab.research.google.com/github/ankit-rathi/Quantvesting_v2/blob/main/myStocks_Portfolio_Analysis.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
'''
!pip install pandas==2.2.2 -qq
!pip install pyxirr -qq
!pip install ta -qq
!pip install yfinance==0.2.59 -qq
'''

'\n!pip install pandas==2.2.2 -qq\n!pip install pyxirr -qq\n!pip install ta -qq\n!pip install yfinance==0.2.59 -qq\n'

In [2]:
# import libraries

import numpy as np
import pandas as pd
import datetime
import warnings
warnings.filterwarnings('ignore')
import yfinance as yfin
import ta
import matplotlib.pyplot as plt
import requests

In [3]:
# notebook start time
import time
import datetime
import pytz

start_time = time.time()

# function to print date timestamp
def print_date_time():
  tz_NY = pytz.timezone('Asia/Kolkata')
  datetime_NY = datetime.datetime.now(tz_NY)
  print("Run date time (IST):", datetime_NY.strftime("%Y-%m-%d %H:%M:%S"))

In [4]:
# function to get booked and reserved amount
def get_amt():
  # fetch the JSON data from the URL
  url = "https://raw.githubusercontent.com/ankit-rathi/Tradevesting_v1/main/data/myPortfolioAmts.json"
  response = requests.get(url)
  pf_amts = response.json()  # parse the JSON data

  # extract values from the JSON
  py_booked_amt_dm = pf_amts["py_booked_amt_dm"]
  py_booked_amt_sv = pf_amts["py_booked_amt_sv"]
  cy_booked_amt_dm = pf_amts["cy_booked_amt_dm"]
  cy_booked_amt_sv = pf_amts["cy_booked_amt_sv"]
  reserve_amt_dm = pf_amts["reserve_amt_dm"]
  reserve_amt_sv = pf_amts["reserve_amt_sv"]

  # perform calculations
  py_booked_amt = py_booked_amt_dm + py_booked_amt_sv
  cy_booked_amt = cy_booked_amt_dm + cy_booked_amt_sv
  reserve_amt = reserve_amt_dm + reserve_amt_sv
  total_booked_amt = py_booked_amt + cy_booked_amt

  return total_booked_amt, reserve_amt, cy_booked_amt, py_booked_amt

gen_output = 0

In [5]:
# function to format the amount
def format_amt(number):
    abs_number = abs(number)

    if abs_number >= 1_00_00_000:  # Crores
        formatted_amt = f"{number / 1_00_00_000:.2f} C"
    elif abs_number >= 1_00_000:  # Lakhs
        formatted_amt = f"{number / 1_00_000:.2f} L"
    elif abs_number >= 1_000:  # Thousands
        formatted_amt = f"{number / 1_000:.2f} K"
    else:
        formatted_amt = f"{number:.2f}"

    return formatted_amt

# function to set start and end date
def get_start_end_date():
  start_date = (datetime.date.today() + datetime.timedelta(days=-365)).strftime('%Y-%m-%d')
  end_date = (datetime.date.today() + datetime.timedelta(days=1)).strftime('%Y-%m-%d')
  return start_date, end_date

# function to fetch my portfolio csv
def get_mypfs_df():
  mypfs_df = pd.read_csv('https://raw.githubusercontent.com/ankit-rathi/Tradevesting_v1/main/data/myPortfolioStocks.csv')
  return mypfs_df

# function to fetch my prospects csv
def get_mypps_df():
  mypps_df = pd.read_csv('https://raw.githubusercontent.com/ankit-rathi/Tradevesting_v1/main/data/myProspectsScrips.csv')
  return mypps_df

# function to fetch screener data
def get_myscreen_df():
  myscreen_df = pd.read_csv('https://raw.githubusercontent.com/ankit-rathi/Tradevesting_v1/main/data/myScreenerDB.csv')
  return myscreen_df

# function to fetch momentum data
def get_myinvmt_df():
  myinvmt_df = pd.read_csv('https://raw.githubusercontent.com/ankit-rathi/Tradevesting_v1/main/data/myInvestments.csv')
  return myinvmt_df

# function to get the stock ids
def get_stock_ids(df_pf):
  stock_n100 = df_pf['Symbol'].unique()

  exclude = ['CADILAHC','MMTC', 'MASFIN']

  stock_ids = df_pf[~df_pf['Symbol'].isin(exclude) ]['Symbol'].unique()

  #mypf = mypf[mypf.Forecast.notnull()]
  #stock_ids = mypf['Symbol'].unique()

  #stock_ids.sort()
  return stock_ids

# get features from screener data
def get_screener_features():
  myscreen_df = get_myscreen_df()
  cols = ['Symbol', 'EPS', 'MedPE', 'ROCE%', 'ROE%', 'CapType']
  return myscreen_df[cols]

# get relative strength
def get_relative_strength(stock_list):

    # Dictionary to store stock tickers and their corresponding percentage price change
    stock_changes = {}

    # Loop through each stock and fetch its price data
    for stock in stock_list:
        try:
            # Download the stock data for the given date range
            stock_data = yfin.Ticker(stock + '.NS').history(period='1mo', interval='1d')[map(str.title, ['open', 'close', 'low', 'high', 'volume'])]

            # Calculate the percentage change for the stock
            if len(stock_data) > 0:
                start_price = stock_data['Close'].iloc[0]
                end_price = stock_data['Close'].iloc[-1]
                percent_change = round(((end_price - start_price) / start_price) * 100, 2)
                stock_changes[stock] = percent_change
            else:
                stock_changes[stock] = np.nan  # If no data is available, set to NaN

        except Exception as e:
            print(f"Error fetching data for {stock}: {e}")
            stock_changes[stock] = np.nan

    # Create a DataFrame with stock tickers and their percentage changes
    df = pd.DataFrame(list(stock_changes.items()), columns=['Symbol', 'Percent_Change'])

    # Drop any stocks with missing data (NaN values)
    df = df.dropna()

    # Calculate the percentile rank based on percentage change
    df['RSP'] = round(df['Percent_Change'].rank(pct=True) * 100, 2)
    cols = ['Symbol', 'RSP']
    df = df[cols]
    # Sort by percentile rank (optional)
    df = df.sort_values(by='RSP', ascending=False).reset_index(drop=True)

    return df

In [6]:
# function to get stock technicals
def stock_prec_dev(stock_symbol):
    #stock_symbol = 'ULTRACEMCO.NS'
    short_window = 20
    mid_window = 50
    long_window = 200
    moving_avg = 'SMA'

    start = datetime.datetime(*map(int, start_date.split('-')))
    end = datetime.datetime(*map(int, end_date.split('-')))

    stock_df = yfin.Ticker(stock_symbol + '.NS').history(period='max', interval='1d')[map(str.title, ['open', 'close', 'low', 'high', 'volume'])]

    stock_df['Max'] = round(max(stock_df['Close']),2)
    stock_df = stock_df[(stock_df.index <= end_date) & (stock_df.index >= start_date)]
    stock_df['200_SMA'] = round(stock_df['Close'].rolling(window = 200, min_periods = 1).mean(),0)
    stock_df['Dev%_200'] = round((stock_df['Close'] - stock_df['200_SMA'])*100/stock_df['200_SMA'],2)
    stock_df.dropna(axis = 0, inplace = True) # remove any null rows

    stock_df['20_SMA'] = stock_df['Close'].rolling(window=20).mean()
    stock_df['50_SMA'] = stock_df['Close'].rolling(window=50).mean()
    stock_df['Symbol'] = stock_symbol

    stock_df['Close'] = round(stock_df['Close'],2)
    stock_df['Min'] = round(min(stock_df['Close']),2)
    stock_df['RSI_14'] = ta.momentum.RSIIndicator(close=stock_df['Close'], window=14).rsi()
    stock_df['RSI_14'] = round(stock_df['RSI_14'],0)
    stock_df['Prev_Close'] = stock_df['Close'].shift(1)
    stock_df.drop(['Open', 'Low', 'High', 'Volume'], axis=1, inplace=True)
    stock_df = stock_df.tail(1)

    max_SMA = max(stock_df['20_SMA'].item(), stock_df['50_SMA'].item(), stock_df['200_SMA'].item())
    min_SMA = min(stock_df['20_SMA'].item(), stock_df['50_SMA'].item(), stock_df['200_SMA'].item())
    ABS_Spread = max_SMA - min_SMA
    stock_df['Spread%'] = round((ABS_Spread / stock_df['200_SMA'].item()) * 100,2)

    return stock_df

# function to compute stock attributes
def get_common_features(stock_ids, df_mypf):

  df_prec_dev = pd.DataFrame()
  df_tmp = get_screener_features()
  df_rs = get_relative_strength(stock_ids)

  for stock_id in stock_ids:
      tmp = stock_prec_dev(stock_id)
      tmp = tmp.reset_index()
      df_prec_dev = pd.concat([df_prec_dev, tmp], ignore_index = True)
  df_prec_dev = pd.merge(df_prec_dev, df_mypf, on= 'Symbol')
  df_prec_dev = pd.merge(df_prec_dev, df_tmp, on= 'Symbol', how='left')
  df_prec_dev = pd.merge(df_prec_dev, df_rs, on= 'Symbol', how='left')
  #print(df_prec_dev.columns)
  df_prec_dev['Curr_PE'] = round(df_prec_dev['Close']/df_prec_dev['EPS'],1)
  df_prec_dev['Dev%_PE'] = round((df_prec_dev['Curr_PE'] - df_prec_dev['MedPE'])*100/df_prec_dev['MedPE'],2)
  df_prec_dev['Conviction'] = df_prec_dev['Conviction'] + '-' + df_prec_dev['CapType']
  return df_prec_dev

# function to arrange stock features
def arrange_features(df_stocks, common_cols, diff_cols):
  df_stocks_common = df_stocks[common_cols].drop_duplicates()
  df_stocks_diff = df_stocks[diff_cols]
  df_stocks_diff['Investment'] = df_stocks_diff['AvgCost'] * df_stocks_diff['Shares']
  df_stocks_diff = df_stocks_diff.groupby(['Symbol'])[['Shares', 'Investment']].aggregate(['sum']).reset_index()
  df_stocks_diff.columns = ['Symbol', 'Shares', 'Investment']
  df_stocks_diff['AvgCost'] = round(df_stocks_diff['Investment']/df_stocks_diff['Shares'],2)
  df_stocks = pd.merge(df_stocks_diff, df_stocks_common, on='Symbol')
  return df_stocks

# plot fact distribution across dimension
def plot_pie_chart(df, dimension, fact):
  # grouping the data by category and calculating the sum of fact for each type
  grouped_data = df.groupby(dimension)[fact].sum()

  # sorting the grouped data in descending order
  grouped_data = grouped_data.sort_values(ascending=False)

  # creating a pie chart
  grouped_data.plot.pie(autopct='%1.1f%%', startangle=90, figsize=(6, 6))

  # adding a title and displaying the plot
  plt.title(f'{dimension} {fact} Distribution')
  plt.ylabel('')  # To hide the y-label
  plt.show()

In [7]:
# function to get portfolio features

def get_portfolio_features(df_common_features):

  print_date_time()
  print('-------------------')

  #df_common_features["Target"] = df_common_features["Target"].fillna(df_common_features["Max"])
  df_common_features['NTT'] = np.where(df_common_features['Strategy']== 'NTT', df_common_features["Target"], df_common_features['Max'])
  df_common_features['LTT'] = np.where(df_common_features['Strategy']== 'BTT', df_common_features["Target"], df_common_features['Max'])
  df_common_features['BOL'] = df_common_features['Min']

  tmp_df = df_common_features[df_common_features['Symbol'].isin(mypf_df[mypf_df['InPortfolio'] != 'NA'].Symbol.values)]
  print('qualified stocks: '+str(len(tmp_df['Symbol'].unique())))
  tmp_df1 = tmp_df[tmp_df['LatestQtr'] == 1]
  print('with latest results: '+str(len(tmp_df1['Symbol'].unique())))
  tmp_df1 = tmp_df1[tmp_df1['StarStock'] == 1]
  print('still star stocks: '+str(len(tmp_df1['Symbol'].unique())))
  tmp_df['Investment'] = tmp_df['AvgCost'] * tmp_df['Shares']
  tmp_df['Current'] = round(tmp_df['Close'] * tmp_df['Shares'],0)
  tmp_df['Previous'] = tmp_df['Prev_Close'] * tmp_df['Shares']
  tmp_df['EstimatedST'] = tmp_df['NTT'] * tmp_df['Shares']
  tmp_df['EstimatedLT'] = tmp_df['LTT'] * tmp_df['Shares']
  tmp_df['Current P/L'] = round((tmp_df['Current'] - tmp_df['Investment']),0)
  tmp_df['Today P/L%'] = round((tmp_df['Current'] - tmp_df['Previous'])*100/tmp_df['Previous'],2)
  tmp_df['Current P/L%'] = round((tmp_df['Current'] - tmp_df['Investment'])*100/tmp_df['Investment'],2)
  tmp_df['EstimatedST P/L%'] = round((tmp_df['EstimatedST'] - tmp_df['Investment'])*100/tmp_df['Investment'],2)
  tmp_df['EstimatedLT P/L%'] = round((tmp_df['EstimatedLT'] - tmp_df['Investment'])*100/tmp_df['Investment'],2)
  tmp_df['NTT%'] = round((tmp_df['NTT'] - tmp_df['Close'])*100/tmp_df['Close'],2)
  tmp_df['LTT%'] = round((tmp_df['LTT'] - tmp_df['Close'])*100/tmp_df['Close'],2)
  tmp_df['Gained%'] = round((tmp_df['Close'] - tmp_df['BOL'])*100/tmp_df['BOL'],2)
  investment = round(sum(tmp_df['AvgCost']*tmp_df['Shares']),0)
  current = round(sum(tmp_df['Close']*tmp_df['Shares']),0)
  tmp_df['InitAlloc%'] = round(tmp_df['Investment']*100/investment,2)
  tmp_df['CurrAlloc%'] = round(tmp_df['Current']*100/current,2)
  tmp_df['FTT'] = tmp_df['LTT']
  tmp_df.loc[tmp_df['Strategy'] == 'NTT', 'FTT'] = tmp_df['NTT']
  tmp_df['FTT%'] = tmp_df['LTT%']
  tmp_df.loc[tmp_df['Strategy'] == 'NTT', 'FTT%'] = tmp_df['NTT%']
  tmp_df['FTT Amt'] = round(tmp_df['FTT%'] * tmp_df['Current']/100,0)
  tmp_df['OTT%'] = round((tmp_df['FTT'] - tmp_df['AvgCost'])*100/tmp_df['AvgCost'],2)
  tmp_df['RRR Ind'] = round(tmp_df['Current P/L']/tmp_df['FTT Amt'],2)
  tmp_df['Risk Ind'] = round(tmp_df['Current P/L%']*tmp_df['CurrAlloc%'],0)

  return tmp_df

# function to print portfolio features
def print_portfolio_stats(df_portfolio_features, myinvmt_df):
  from pyxirr import xirr

  total_booked_amt, reserve_amt, cy_booked_amt, py_booked_amt = get_amt()

  dates = myinvmt_df['Date'].values
  dates = np.append(dates, datetime.date.today().strftime('%d-%b-%y'))
  investment = myinvmt_df['Investment'].values
  dates= pd.to_datetime(dates)

  current = round(sum(df_portfolio_features['Close']*df_portfolio_features['Shares']),0) + reserve_amt
  investment_xirr = np.append(investment, current)
  cagr = round(xirr(pd.DataFrame({"dates": dates, "amounts": investment_xirr}))*100,2)

  investment = -sum(investment)
  invested = round(sum(df_portfolio_features['AvgCost']*df_portfolio_features['Shares']),0) + reserve_amt
  previous = round(sum(df_portfolio_features['Prev_Close']*df_portfolio_features['Shares']),0) + reserve_amt
  cy_invested = investment + py_booked_amt

  today_pnl_amount = current-previous
  today_pnl_percentage = round((current-previous)*100/previous,2)

  curr_pnl_amount = current-invested
  curr_pnl_percentage = round((curr_pnl_amount)*100/(cy_invested),2)

  cy_pnl_amount = cy_booked_amt + curr_pnl_amount
  cy_pnl_percentage = round((cy_pnl_amount)*100/cy_invested,2)

  overall_pnl_amount = total_booked_amt + curr_pnl_amount
  overall_pnl_percentage = round((overall_pnl_amount)*100/investment,2)

  estimate_st = round(sum(df_portfolio_features['FTT']*df_portfolio_features['Shares']),0)  + reserve_amt
  est_st_pnl_amount = estimate_st-current
  est_st_pnl_percentage = round((est_st_pnl_amount)*100/current,2)

  estimate_lt = round(sum(df_portfolio_features['LTT']*df_portfolio_features['Shares']),0)  + reserve_amt
  est_lt_pnl_amount = estimate_lt-current
  est_lt_pnl_percentage = round((est_lt_pnl_amount)*100/current,2)

  total_profit = round(sum(df_portfolio_features[df_portfolio_features['Current P/L%'] > 0]['Current']) - sum(df_portfolio_features[df_portfolio_features['Current P/L%'] > 0]['Investment']),0)
  total_loss = round(sum(df_portfolio_features[df_portfolio_features['Current P/L%'] < 0]['Current']) - sum(df_portfolio_features[df_portfolio_features['Current P/L%'] < 0]['Investment']),0)

  cy_booked_percentage = round((cy_booked_amt)*100/current,2)
  py_booked_percentage = round((py_booked_amt)*100/investment,2)
  total_booked_percentage = round((total_booked_amt)*100/investment,2)

  print('-------------------')
  print('Initial Investment: ', format_amt(investment))
  print('CY Investment: ', format_amt(cy_invested))
  print('Reserve: ', format_amt(reserve_amt))
  print('Current: ',  format_amt(current))
  print('-------------------')
  print('Today PnL: '+ '{} ({}%)'.format(format_amt(today_pnl_amount), today_pnl_percentage))
  print('Current PnL: '+ '{} ({}%)'.format(format_amt(curr_pnl_amount), curr_pnl_percentage))
  print('CY Booked + Current PnL: '+ '{} ({}%)'.format(format_amt(cy_pnl_amount), cy_pnl_percentage))
  print('-------------------')
  print('Total profit: ', format_amt(total_profit))
  print('Total loss: ', format_amt(total_loss))
  print('-------------------')
  print('Total Booked + Current PnL: '+ '{} ({}%)'.format(format_amt(overall_pnl_amount), overall_pnl_percentage))
  print('Total Booked PnL: '+ '{} ({}%)'.format(format_amt(total_booked_amt), total_booked_percentage))
  print('Curr Year Booked PnL: '+ '{} ({}%)'.format(format_amt(cy_booked_amt), cy_booked_percentage))
  print('Prev Year Booked PnL: '+ '{} ({}%)'.format(format_amt(py_booked_amt), py_booked_percentage))
  print('===================')
  print('Est FTT: ',  format_amt(estimate_st))
  print('Est FTT PnL: '+ '{} ({}%)'.format(format_amt(est_st_pnl_amount), est_st_pnl_percentage))

  print('===================')
  print('Deployed: ', format_amt(investment))

  print('Current: ', format_amt(current))

  print('CAGR/XIRR %: '+'{}%'.format(cagr))

In [8]:
# get start and end date
start_date, end_date = get_start_end_date()

# get portfolio and prospects data
mypfs_df = get_mypfs_df()
mypps_df = get_mypps_df()
myinvmt_df = get_myinvmt_df()

# merge above datasets
mypf_df = pd.merge(mypfs_df, mypps_df, on="Symbol")

# seggregate dm and sv portfolio
dm_pf = mypf_df[mypf_df['InPortfolio'] == 'DM']
sv_pf = mypf_df[mypf_df['InPortfolio'] == 'SV']

# build portfolio stock dataframe
dm_stocks = get_stock_ids(dm_pf)
sv_stocks = get_stock_ids(sv_pf)
df_stocks = pd.concat([dm_pf,sv_pf], ignore_index = True)

# arrange common and diff stock features
common_cols = ['Symbol', 'Target', 'Criteria', 'Strategy', 'CumlRnk', 'LatestQtr', 'StarStock', 'Conviction', 'Category', 'InFolio', 'XIRR', 'MBQ']
diff_cols = ['Symbol', 'AvgCost', 'Shares']
df_stocks = arrange_features(df_stocks, common_cols, diff_cols)

# get common features
stock_ids = df_stocks['Symbol'].values
df_common_features = get_common_features(stock_ids, df_stocks)

df_common_features.reset_index(drop=True, inplace=True)
df_common_features.drop(['Date'], axis=1, inplace=True)
# get and print portfolio features
df_portfolio_features = get_portfolio_features(df_common_features)

print_portfolio_stats(df_portfolio_features, myinvmt_df)

df = df_portfolio_features
#plot_pie_chart(df, 'CapType', 'Current')
list_ox40n = list(df[df['MBQ'].str.contains('OX40N', na=False)]['Symbol'].values)

Run date time (IST): 2026-06-04 15:59:02
-------------------
qualified stocks: 92
with latest results: 31
still star stocks: 20

-------------------
Initial Investment:  1.40 C
CY Investment:  1.82 C
Reserve:  1.49 K
Current:  1.48 C
-------------------
Today PnL: 42.82 K (0.29%)
Current PnL: -34.75 L (-19.05%)
CY Booked + Current PnL: -32.67 L (-17.91%)
-------------------
Total profit:  2.45 L
Total loss:  -37.19 L
-------------------
Total Booked + Current PnL: 10.20 L (7.31%)
Total Booked PnL: 44.95 L (32.22%)
Curr Year Booked PnL: 2.08 L (1.4%)
Prev Year Booked PnL: 42.87 L (30.73%)
===================
Est FTT:  2.55 C
Est FTT PnL: 1.07 C (71.93%)
===================
Deployed:  1.40 C
Current:  1.48 C
CAGR/XIRR %: 2.95%

In [9]:
# top 5 near their targets
cols = ['Symbol', 'Today P/L%', 'Current P/L%', 'FTT%', 'OTT%', 'FTT Amt', 'Current P/L', 'Current', 'FTT', 'Dev%_PE', 'RSI_14','Conviction', 'Spread%',  'CumlRnk', 'RRR Ind', 'CurrAlloc%', 'Gained%', 'Criteria', 'Strategy', 'Category']
df_tmp = df_portfolio_features[~df_portfolio_features['Symbol'].isin(['ENRIN','BLUSPRING','DIGITIDE'])]
df_tmp = df_tmp.sort_values(by = 'FTT Amt', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
59,PIDILITIND,0.13,4.25,13.54,18.37,19919.0,6000.0,147110.0,1670.26,-26.97,57.0,X-LC,4.42,5.0,0.30,0.99,15.51,X40,ATH,CHEMICALS
72,SIS,1.10,-2.62,24.53,21.26,26522.0,-2912.0,108120.0,528.00,2579.27,73.0,H-SC,18.93,168.0,-0.11,0.73,60.76,OX40N,NTT,MISC
51,KOTAKBANK,0.13,1.94,18.80,21.11,26537.0,2682.0,141155.0,453.24,-12.44,49.0,X-LC,7.16,12.0,0.10,0.95,7.95,X40,ATH,BANKS
55,MASFIN,-0.31,-6.35,29.82,21.57,27361.0,-6225.0,91755.0,397.04,-19.15,41.0,H-SC,0.99,167.0,-0.23,0.62,9.37,XR,ATH,FINANCE
83,TTKPRESTIG,0.06,-29.21,41.39,0.09,29529.0,-29434.0,71343.0,770.00,65.64,59.0,M-SC,14.18,250.0,-1.00,0.48,27.04,OX40N,NTT,DURABLES

In [10]:
# top 5 today
df_tmp = df_portfolio_features.sort_values(by = 'Today P/L%', ascending=False)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
88,VOLTAS,4.17,0.64,44.27,45.20,85430.0,1233.0,192975.0,1856.00,15.18,48.0,X-MC,8.33,79.0,0.01,1.30,5.43,XY25,NTT,AC
69,SFL,3.97,-38.69,106.53,26.63,171271.0,-101445.0,160773.0,1287.00,21.78,62.0,M-SC,8.42,242.0,-0.59,1.08,34.00,XY24,NTT,MISC
38,HYUNDAI,3.54,2.73,45.38,49.35,71908.0,4216.0,158457.0,2809.30,-17.27,60.0,X-LC,17.03,29.0,0.06,1.07,14.25,X40N,ATH,AUTO
57,PAGEIND,3.38,1.29,31.88,33.59,86664.0,3466.0,271845.0,51217.29,-27.40,62.0,X-MC,3.12,55.0,0.04,1.83,29.10,X40,ATH,APPARELS
46,IRCTC,3.27,-36.43,140.57,52.93,241731.0,-98543.0,171965.0,1269.00,-53.00,47.0,H-MC,15.91,119.0,-0.41,1.16,6.67,XY24,BTT,TRAVEL

In [11]:
# bottom 5 today
df_tmp = df_portfolio_features.sort_values(by = 'Today P/L%', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
61,RAJESHEXPO,-4.99,-79.92,398.46,0.07,109732.0,-109638.0,27539.0,518.00,908.84,39.0,L-SC,30.15,268.0,-1.00,0.19,29.29,OX40N,NTT,JEWELLERY
24,EASEMYTRIP,-3.62,-63.30,296.99,45.70,192720.0,-111924.0,64891.0,26.40,-32.65,30.0,M-SC,6.05,204.0,-0.58,0.44,13.68,XY24,NTT,TRAVEL
86,VALIANTORG,-2.10,-38.85,184.79,74.15,184873.0,-63560.0,100045.0,838.00,-279.66,54.0,H-SC,6.94,145.0,-0.34,0.67,48.88,XR,NTT,CHEMICALS
77,TANLA,-2.00,-41.49,271.28,117.25,429794.0,-112329.0,158432.0,1922.32,-40.86,50.0,H-SC,9.10,147.0,-0.26,1.07,38.71,AR,ATH,IT
3,ALKYLAMINE,-1.96,-23.30,152.46,93.63,118056.0,-23529.0,77434.0,4546.37,-17.90,60.0,H-SC,9.72,142.0,-0.20,0.52,46.22,SR,ATH,CHEMICALS

In [12]:
# top 5 to exit based on CumlRnk
df_tmp = df_portfolio_features[~df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])]
df_tmp = df_tmp[(df_tmp['Current P/L%'] > -1) & (df_tmp['Current P/L%'] < 1)].sort_values(by = 'CumlRnk', ascending=False)
df_tmp[cols].head()

Empty DataFrame
Columns: [Symbol, Today P/L%, Current P/L%, FTT%, OTT%, FTT Amt, Current P/L, Current, FTT, Dev%_PE, RSI_14, Conviction, Spread%, CumlRnk, RRR Ind, CurrAlloc%, Gained%, Criteria, Strategy, Category]
Index: []

In [13]:
# OX40N stocks to exit
df_tmp = df_portfolio_features[(df_portfolio_features['Symbol'].isin(list_ox40n))].sort_values(by = 'Current P/L%', ascending=False)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
25,FINCABLES,2.16,28.95,61.24,107.91,116592.0,42741.0,190385.0,1641.55,16.18,47.0,M-SC,26.75,220.0,0.37,1.28,43.23,OX40N,ATH,CABLES
72,SIS,1.10,-2.62,24.53,21.26,26522.0,-2912.0,108120.0,528.00,2579.27,73.0,H-SC,18.93,168.0,-0.11,0.73,60.76,OX40N,NTT,MISC
16,CERA,-0.76,-27.63,71.20,23.89,90633.0,-48609.0,127294.0,9475.00,-30.07,48.0,H-SC,6.70,153.0,-0.54,0.86,22.33,OX40N,NTT,CERAMICS
50,KANSAINER,-0.56,-28.70,59.14,13.47,113717.0,-77382.0,192285.0,340.00,-38.75,53.0,H-SC,10.10,162.0,-0.68,1.30,34.31,XY24,NTT,PAINTS
83,TTKPRESTIG,0.06,-29.21,41.39,0.09,29529.0,-29434.0,71343.0,770.00,65.64,59.0,M-SC,14.18,250.0,-1.00,0.48,27.04,OX40N,NTT,DURABLES

In [14]:
# top 5 to book for rotation
df_tmp = df_portfolio_features[(df_portfolio_features['Current P/L%'] > 20) ].sort_values(by = 'CumlRnk', ascending=False)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
25,FINCABLES,2.16,28.95,61.24,107.91,116592.0,42741.0,190385.0,1641.55,16.18,47.0,M-SC,26.75,220.0,0.37,1.28,43.23,OX40N,ATH,CABLES
68,SATIN,2.84,34.06,13.26,51.83,49114.0,94111.0,370395.0,274.00,19.58,76.0,H-SC,40.78,159.0,1.92,2.50,80.44,XY24,NTT,FINANCE

In [15]:
# top 5 to monitor for exit
df_tmp = df_portfolio_features[~df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])]
df_tmp = df_tmp[(df_tmp['Current P/L%'] > 0) ].sort_values(by = 'Dev%_PE', ascending=False)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
74,STARHEALTH,-0.72,1.83,44.61,47.26,127710.0,5157.0,286280.0,761.00,60.64,58.0,H-SC,9.93,173.0,0.04,1.93,25.69,XY24,NTT,INSURANCE
68,SATIN,2.84,34.06,13.26,51.83,49114.0,94111.0,370395.0,274.00,19.58,76.0,H-SC,40.78,159.0,1.92,2.50,80.44,XY24,NTT,FINANCE
25,FINCABLES,2.16,28.95,61.24,107.91,116592.0,42741.0,190385.0,1641.55,16.18,47.0,M-SC,26.75,220.0,0.37,1.28,43.23,OX40N,ATH,CABLES
91,ZYDUSLIFE,0.74,14.37,18.58,35.63,44536.0,30123.0,239697.0,1286.17,-0.45,70.0,H-MC,8.69,120.0,0.68,1.62,26.03,AR,ATH,PHARMA
73,SONACOMS,-0.38,4.00,33.75,39.09,35505.0,4042.0,105201.0,804.02,-17.63,55.0,M-MC,18.87,193.0,0.11,0.71,48.82,AR,ATH,AUTO

In [16]:
# top 5 to book for rotation from weak conviction
df_tmp = df_portfolio_features[~df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])]
df_tmp = df_tmp[~df_tmp['Criteria'].isin(['XY25','XY24','X40', 'X40N'])].sort_values(by = 'RRR Ind', ascending=False)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
91,ZYDUSLIFE,0.74,14.37,18.58,35.63,44536.0,30123.0,239697.0,1286.17,-0.45,70.0,H-MC,8.69,120.0,0.68,1.62,26.03,AR,ATH,PHARMA
25,FINCABLES,2.16,28.95,61.24,107.91,116592.0,42741.0,190385.0,1641.55,16.18,47.0,M-SC,26.75,220.0,0.37,1.28,43.23,OX40N,ATH,CABLES
73,SONACOMS,-0.38,4.00,33.75,39.09,35505.0,4042.0,105201.0,804.02,-17.63,55.0,M-MC,18.87,193.0,0.11,0.71,48.82,AR,ATH,AUTO
75,SURYODAY,1.01,-2.38,26.03,23.03,45505.0,-4253.0,174818.0,216.00,90.79,66.0,H-SC,19.34,166.0,-0.09,1.18,47.19,XR,NTT,BANKS
72,SIS,1.10,-2.62,24.53,21.26,26522.0,-2912.0,108120.0,528.00,2579.27,73.0,H-SC,18.93,168.0,-0.11,0.73,60.76,OX40N,NTT,MISC

In [17]:
# top 5 to accumulate based on lowest RSI_14
df_tmp = df_portfolio_features[df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])].sort_values(by = 'RSI_14', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
27,GLAXO,-0.66,-13.02,56.01,35.69,97081.0,-25956.0,173328.0,3380.16,-33.67,28.0,X-MC,7.60,56.0,-0.27,1.17,0.00,X40,ATH,PHARMA
40,ICICIPRULI,0.04,-21.05,65.58,30.73,102000.0,-41470.0,155535.0,790.00,-42.23,29.0,X-MC,13.52,78.0,-0.41,1.05,0.04,X40,ATH,INSURANCE
36,HINDUNILVR,-0.54,-19.11,40.52,13.67,84257.0,-49123.0,207940.0,2922.00,-39.91,31.0,X-LC,6.88,9.0,-0.58,1.40,1.33,XY25,NTT,FMCG
10,BATAINDIA,-1.24,-57.58,218.76,35.20,119393.0,-74093.0,54577.0,2096.00,-28.38,32.0,X-SC,25.22,91.0,-0.62,0.37,8.24,X40,NTT,FOOTWEAR
35,HDFCLIFE,-0.11,-6.16,41.93,33.18,58941.0,-9231.0,140569.0,814.30,-26.76,33.0,X-LC,15.13,31.0,-0.16,0.95,1.35,X40,ATH,INSURANCE

In [18]:
# top 5 to accumulate based on Spread and CumlRnk
df_tmp = df_portfolio_features[df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])]
df_tmp = df_tmp[(df_tmp['CumlRnk'] < 100)].sort_values(by = 'Spread%', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
57,PAGEIND,3.38,1.29,31.88,33.59,86664.0,3466.0,271845.0,51217.29,-27.40,62.0,X-MC,3.12,55.0,0.04,1.83,29.10,X40,ATH,APPARELS
23,DMART,-0.70,-0.50,30.25,29.60,75128.0,-1242.0,248358.0,5391.45,-16.12,43.0,X-LC,3.67,14.0,-0.02,1.67,13.52,X40N,ATH,FMCG
49,JSWINFRA,0.92,-7.13,25.37,16.43,52253.0,-15810.0,205964.0,342.00,-20.31,50.0,X-MC,3.91,61.0,-0.30,1.39,16.43,X40N,NTT,REALTY
59,PIDILITIND,0.13,4.25,13.54,18.37,19919.0,6000.0,147110.0,1670.26,-26.97,57.0,X-LC,4.42,5.0,0.30,0.99,15.51,X40,ATH,CHEMICALS
19,COLPAL,-0.70,-23.89,83.77,39.86,167909.0,-62925.0,200440.0,3683.41,-7.87,39.0,X-MC,4.52,62.0,-0.37,1.35,13.38,XY25,ATH,FMCG

In [19]:
# top 5 to accumulate based on lowest Gained%
df_tmp = df_portfolio_features[df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])].sort_values(by = 'Gained%', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
27,GLAXO,-0.66,-13.02,56.01,35.69,97081.0,-25956.0,173328.0,3380.16,-33.67,28.0,X-MC,7.60,56.0,-0.27,1.17,0.00,X40,ATH,PHARMA
65,RELIANCE,-0.72,-16.31,49.73,25.30,83634.0,-32786.0,168177.0,1952.00,-18.49,35.0,X-LC,5.59,21.0,-0.39,1.13,0.00,XY25,BTT,REFINERIES
40,ICICIPRULI,0.04,-21.05,65.58,30.73,102000.0,-41470.0,155535.0,790.00,-42.23,29.0,X-MC,13.52,78.0,-0.41,1.05,0.04,X40,ATH,INSURANCE
79,TCS,-0.03,-34.21,89.82,24.88,273750.0,-158497.0,304776.0,4253.91,-44.28,42.0,X-LC,18.19,2.0,-0.58,2.05,1.13,X40,ATH,IT
47,ITC,1.19,-26.17,61.26,19.06,153854.0,-89017.0,251149.0,452.00,-59.56,35.0,X-LC,14.52,1.0,-0.58,1.69,1.19,X40,NTT,FMCG

In [20]:
# top 5 to accumulate based on lowest CurrAlloc%
df_tmp = df_portfolio_features[df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])].sort_values(by = 'CurrAlloc%', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
10,BATAINDIA,-1.24,-57.58,218.76,35.20,119393.0,-74093.0,54577.0,2096.00,-28.38,32.0,X-SC,25.22,91.0,-0.62,0.37,8.24,X40,NTT,FOOTWEAR
64,RELAXO,-0.12,-56.33,248.75,52.31,157693.0,-81766.0,63394.0,1176.00,-53.54,67.0,X-SC,22.60,92.0,-0.52,0.43,41.74,X40N,NTT,FOOTWEAR
60,QUESS,1.86,-11.80,97.17,73.90,91522.0,-12605.0,94188.0,424.00,-52.62,59.0,X-SC,7.22,80.0,-0.14,0.63,28.40,XY24,NTT,MISC
28,GODREJCP,0.90,-10.92,47.58,31.47,62990.0,-16226.0,132388.0,1469.04,-6.33,39.0,X-LC,9.95,32.0,-0.26,0.89,1.58,X40N,ATH,FMCG
53,M&M,0.17,-2.13,26.07,23.38,35383.0,-2957.0,135724.0,3802.40,-17.22,42.0,X-LC,9.32,25.0,-0.08,0.91,2.90,X40N,ATH,AUTO

In [21]:
# top 5 to accumulate based on CumlRnk
df_tmp = df_portfolio_features.sort_values(by = 'CumlRnk', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
47,ITC,1.19,-26.17,61.26,19.06,153854.0,-89017.0,251149.0,452.00,-59.56,35.0,X-LC,14.52,1.0,-0.58,1.69,1.19,X40,NTT,FMCG
79,TCS,-0.03,-34.21,89.82,24.88,273750.0,-158497.0,304776.0,4253.91,-44.28,42.0,X-LC,18.19,2.0,-0.58,2.05,1.13,X40,ATH,IT
45,INFY,-1.74,-18.22,64.16,34.24,164171.0,-57011.0,255877.0,1972.00,-35.78,51.0,X-LC,17.82,3.0,-0.35,1.72,9.71,X40,NTT,IT
81,TMPV,0.39,-9.02,50.11,36.58,162235.0,-32084.0,323757.0,600.00,-81.44,68.0,X-LC,18.40,4.0,-0.20,2.18,34.94,XY24,NTT,AUTO
59,PIDILITIND,0.13,4.25,13.54,18.37,19919.0,6000.0,147110.0,1670.26,-26.97,57.0,X-LC,4.42,5.0,0.30,0.99,15.51,X40,ATH,CHEMICALS

In [22]:
# top 5 for average up
df_tmp = df_portfolio_features[(df_portfolio_features['Dev%_200'] > 5)].sort_values(by = 'CurrAlloc%', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
44,INDUSINDBK,0.36,-33.32,99.29,32.89,51116.0,-25724.0,51482.0,1800.00,-342.30,50.0,L-MC,7.83,258.0,-0.50,0.35,26.72,XR,NTT,BANKS
3,ALKYLAMINE,-1.96,-23.30,152.46,93.63,118056.0,-23529.0,77434.0,4546.37,-17.90,60.0,H-SC,9.72,142.0,-0.20,0.52,46.22,SR,ATH,CHEMICALS
18,COFFEEDAY,2.12,-31.60,97.78,35.27,75940.0,-35885.0,77664.0,80.00,-47.69,84.0,L-SC,21.15,266.0,-0.47,0.52,91.52,XR,NTT,HOTELS
73,SONACOMS,-0.38,4.00,33.75,39.09,35505.0,4042.0,105201.0,804.02,-17.63,55.0,M-MC,18.87,193.0,0.11,0.71,48.82,AR,ATH,AUTO
72,SIS,1.10,-2.62,24.53,21.26,26522.0,-2912.0,108120.0,528.00,2579.27,73.0,H-SC,18.93,168.0,-0.11,0.73,60.76,OX40N,NTT,MISC

In [23]:
# top 5 RSP
df_tmp = df_portfolio_features.sort_values(by = 'RSP', ascending=False)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
18,COFFEEDAY,2.12,-31.60,97.78,35.27,75940.0,-35885.0,77664.0,80.00,-47.69,84.0,L-SC,21.15,266.0,-0.47,0.52,91.52,XR,NTT,HOTELS
68,SATIN,2.84,34.06,13.26,51.83,49114.0,94111.0,370395.0,274.00,19.58,76.0,H-SC,40.78,159.0,1.92,2.50,80.44,XY24,NTT,FINANCE
91,ZYDUSLIFE,0.74,14.37,18.58,35.63,44536.0,30123.0,239697.0,1286.17,-0.45,70.0,H-MC,8.69,120.0,0.68,1.62,26.03,AR,ATH,PHARMA
69,SFL,3.97,-38.69,106.53,26.63,171271.0,-101445.0,160773.0,1287.00,21.78,62.0,M-SC,8.42,242.0,-0.59,1.08,34.00,XY24,NTT,MISC
81,TMPV,0.39,-9.02,50.11,36.58,162235.0,-32084.0,323757.0,600.00,-81.44,68.0,X-LC,18.40,4.0,-0.20,2.18,34.94,XY24,NTT,AUTO

In [24]:
# Top N allocation
df_tmp = df_portfolio_features.sort_values(by = 'CurrAlloc%', ascending=False)
top_n_values = [10, 25, 50]

sum_df = pd.DataFrame({
    'Top_N': top_n_values,
    'Sum_Alloc%': [df_tmp['CurrAlloc%'].head(n).sum() for n in top_n_values]
})

sum_df

   Top_N  Sum_Alloc%
0     10       19.85
1     25       42.81
2     50       72.65

In [25]:
# market-cap-wise allocation
df_tmp = df_portfolio_features[cols]
df_tmp.groupby(df_tmp['Conviction'].str[-2:])['CurrAlloc%'].sum().sort_values(ascending=False)

Conviction
SC    43.18
LC    31.44
MC    25.38
Name: CurrAlloc%, dtype: float64

In [26]:
# criteria-wise allocation
df_portfolio_features.groupby('Criteria')['CurrAlloc%'].sum().sort_values(ascending=False)

Criteria
XY24     27.86
X40      24.94
X40N     16.94
XR        9.17
OX40N     6.93
AR        6.86
XY25      6.42
SR        0.88
Name: CurrAlloc%, dtype: float64

In [27]:
# conviction-wise allocation
df_portfolio_features.groupby('Conviction')['CurrAlloc%'].sum().sort_values(ascending=False)

Conviction
X-LC    29.24
H-SC    22.83
X-MC    20.30
M-SC     9.90
X-SC     9.74
H-MC     2.78
M-MC     1.95
H-LC     1.24
M-LC     0.96
L-SC     0.71
L-MC     0.35
Name: CurrAlloc%, dtype: float64

In [28]:
# sector-wise stats
df_tmp = df_portfolio_features.groupby('Category')[['CurrAlloc%', 'Current', 'Current P/L', 'FTT Amt']].sum().sort_values(by=['Current', 'Current P/L'], ascending=False)
df_tmp['Current P/L%'] = round(df_tmp['Current P/L'] * 100 / df_tmp['Current'], 2)
df_tmp['FTT%'] = round(df_tmp['FTT Amt'] * 100 / df_tmp['Current'], 2)
cols = ['CurrAlloc%', 'Current P/L%', 'FTT%']
df_tmp[cols].sort_values(by=['CurrAlloc%'], ascending=False)

               CurrAlloc%  Current P/L%    FTT%
Category
FMCG                14.80        -20.40   62.64
FINANCE             10.89        -14.13   63.76
IT                  10.37        -46.39  119.58
MISC                 6.96        -29.61   85.91
AUTO                 6.92         -6.63   46.60
BANKS                5.76         -6.26   55.39
PAINTS               5.51        -20.61   41.55
INSURANCE            5.17         -8.09   44.76
PHARMA               5.00          0.07   31.12
ELECTRICAL           4.05        -17.49   58.95
CHEMICALS            2.18        -24.98   99.46
HEALTHCARE           2.07        -16.42   46.80
APPARELS             1.83          1.27   31.88
AC                   1.83        -17.85   49.81
FOOTWEAR             1.76        -69.28  137.15
TRAVEL               1.60        -88.86  183.42
DURABLES             1.59        -63.71  103.53
BREWERIES            1.45         -8.93   31.55
REALTY               1.39         -7.68   25.37
ENGINEERING          1.33        -22.94   79.17
CERAMICS             1.33        -56.08  103.50
CABLES               1.28         22.45   61.24
REFINERIES           1.13        -19.49   49.73
CEMENT               1.09        -65.41  189.16
JEWELLERY            1.07       -101.60  171.65
ENTERTAINMENT        0.72        -82.06  190.65
HOTELS               0.52        -46.21   97.78
TEXTILES             0.40        -53.52   97.29

In [29]:
# money to be made criteria-wise
df_portfolio_features.groupby('Criteria')['FTT Amt'].agg(['sum', 'count']).sort_values(by='sum', ascending=False)

                sum  count
Criteria
XY24      3462417.0     21
X40       1982815.0     19
XR        1319765.0     13
X40N      1209469.0     13
AR        1166138.0      9
OX40N      765078.0     10
XY25       482161.0      5
SR         288627.0      2

In [30]:
# money to be made conviction-wise
df_portfolio_features.groupby('Conviction')['FTT Amt'].agg(['sum', 'count']).sort_values(by='sum', ascending=False)

                  sum  count
Conviction
H-SC        3398730.0     24
X-LC        1947345.0     21
X-MC        1705782.0     15
M-SC        1448984.0     14
X-SC        1357002.0      9
H-MC         286267.0      2
L-SC         185672.0      2
M-LC         149897.0      1
M-MC          96436.0      2
L-MC          51116.0      1
H-LC          49239.0      1

In [31]:
# money to be made criteria and conviction-wise
df_portfolio_features.groupby(['Conviction', 'Criteria'])['FTT Amt'].agg(['sum', 'count']).sort_values(by='sum', ascending=False)

                           sum  count
Conviction Criteria
X-LC       X40       1052270.0     10
H-SC       XY24      1024229.0      6
           AR         959546.0      5
M-SC       XY24       846345.0      6
H-SC       XR         803402.0      7
X-SC       XY24       799400.0      4
X-MC       X40        712987.0      7
           X40N       500718.0      4
X-LC       X40N       368707.0      6
X-SC       X40N       340044.0      3
M-SC       OX40N      332420.0      5
H-SC       OX40N      322926.0      4
X-LC       XY24       311974.0      2
H-SC       SR         288627.0      2
X-MC       XY25       253339.0      2
H-MC       XY24       241731.0      1
X-MC       XY24       238738.0      2
X-SC       X40        217558.0      2
M-SC       XR         192907.0      2
X-LC       XY25       167891.0      2
M-LC       XR         149897.0      1
L-SC       OX40N      109732.0      1
M-SC       AR          77312.0      1
L-SC       XR          75940.0      1
M-MC       XY25        60931.0      1
L-MC       XR          51116.0      1
H-LC       AR          49239.0      1
X-LC       XR          46503.0      1
H-MC       AR          44536.0      1
M-MC       AR          35505.0      1

In [32]:
# notebook execution time

end_time = time.time()
execution_time = round(end_time - start_time, 0)
print(f"Notebook execution time: {execution_time} seconds")

Notebook execution time: 35.0 seconds