<a href="https://colab.research.google.com/github/ankit-rathi/Quantvesting_v2/blob/main/myStocks_Portfolio_Analysis.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
'''
!pip install pandas==2.2.2 -qq
!pip install pyxirr -qq
!pip install ta -qq
!pip install yfinance==0.2.59 -qq
'''

'\n!pip install pandas==2.2.2 -qq\n!pip install pyxirr -qq\n!pip install ta -qq\n!pip install yfinance==0.2.59 -qq\n'

In [2]:
# import libraries

import numpy as np
import pandas as pd
import datetime
import warnings
warnings.filterwarnings('ignore')
import yfinance as yfin
import ta
import matplotlib.pyplot as plt
import requests

In [3]:
# notebook start time
import time
import datetime
import pytz

start_time = time.time()

# function to print date timestamp
def print_date_time():
  tz_NY = pytz.timezone('Asia/Kolkata')
  datetime_NY = datetime.datetime.now(tz_NY)
  print("Run date time (IST):", datetime_NY.strftime("%Y-%m-%d %H:%M:%S"))

In [4]:
# function to get booked and reserved amount
def get_amt():
  # fetch the JSON data from the URL
  url = "https://raw.githubusercontent.com/ankit-rathi/Tradevesting_v1/main/data/myPortfolioAmts.json"
  response = requests.get(url)
  pf_amts = response.json()  # parse the JSON data

  # extract values from the JSON
  py_booked_amt_dm = pf_amts["py_booked_amt_dm"]
  py_booked_amt_sv = pf_amts["py_booked_amt_sv"]
  cy_booked_amt_dm = pf_amts["cy_booked_amt_dm"]
  cy_booked_amt_sv = pf_amts["cy_booked_amt_sv"]
  reserve_amt_dm = pf_amts["reserve_amt_dm"]
  reserve_amt_sv = pf_amts["reserve_amt_sv"]

  # perform calculations
  py_booked_amt = py_booked_amt_dm + py_booked_amt_sv
  cy_booked_amt = cy_booked_amt_dm + cy_booked_amt_sv
  reserve_amt = reserve_amt_dm + reserve_amt_sv
  total_booked_amt = py_booked_amt + cy_booked_amt

  return total_booked_amt, reserve_amt, cy_booked_amt, py_booked_amt

gen_output = 0

In [5]:
# function to format the amount
def format_amt(number):
    abs_number = abs(number)

    if abs_number >= 1_00_00_000:  # Crores
        formatted_amt = f"{number / 1_00_00_000:.2f} C"
    elif abs_number >= 1_00_000:  # Lakhs
        formatted_amt = f"{number / 1_00_000:.2f} L"
    elif abs_number >= 1_000:  # Thousands
        formatted_amt = f"{number / 1_000:.2f} K"
    else:
        formatted_amt = f"{number:.2f}"

    return formatted_amt

# function to set start and end date
def get_start_end_date():
  start_date = (datetime.date.today() + datetime.timedelta(days=-365)).strftime('%Y-%m-%d')
  end_date = (datetime.date.today() + datetime.timedelta(days=1)).strftime('%Y-%m-%d')
  return start_date, end_date

# function to fetch my portfolio csv
def get_mypfs_df():
  mypfs_df = pd.read_csv('https://raw.githubusercontent.com/ankit-rathi/Tradevesting_v1/main/data/myPortfolioStocks.csv')
  return mypfs_df

# function to fetch my prospects csv
def get_mypps_df():
  mypps_df = pd.read_csv('https://raw.githubusercontent.com/ankit-rathi/Tradevesting_v1/main/data/myProspectsScrips.csv')
  return mypps_df

# function to fetch screener data
def get_myscreen_df():
  myscreen_df = pd.read_csv('https://raw.githubusercontent.com/ankit-rathi/Tradevesting_v1/main/data/myScreenerDB.csv')
  return myscreen_df

# function to fetch momentum data
def get_myinvmt_df():
  myinvmt_df = pd.read_csv('https://raw.githubusercontent.com/ankit-rathi/Tradevesting_v1/main/data/myInvestments.csv')
  return myinvmt_df

# function to get the stock ids
def get_stock_ids(df_pf):
  stock_n100 = df_pf['Symbol'].unique()

  exclude = ['CADILAHC','MMTC', 'MASFIN']

  stock_ids = df_pf[~df_pf['Symbol'].isin(exclude) ]['Symbol'].unique()

  #mypf = mypf[mypf.Forecast.notnull()]
  #stock_ids = mypf['Symbol'].unique()

  #stock_ids.sort()
  return stock_ids

# get features from screener data
def get_screener_features():
  myscreen_df = get_myscreen_df()
  cols = ['Symbol', 'EPS', 'MedPE', 'ROCE%', 'ROE%', 'CapType']
  return myscreen_df[cols]

# get relative strength
def get_relative_strength(stock_list):

    # Dictionary to store stock tickers and their corresponding percentage price change
    stock_changes = {}

    # Loop through each stock and fetch its price data
    for stock in stock_list:
        try:
            # Download the stock data for the given date range
            stock_data = yfin.Ticker(stock + '.NS').history(period='1mo', interval='1d')[map(str.title, ['open', 'close', 'low', 'high', 'volume'])]

            # Calculate the percentage change for the stock
            if len(stock_data) > 0:
                start_price = stock_data['Close'].iloc[0]
                end_price = stock_data['Close'].iloc[-1]
                percent_change = round(((end_price - start_price) / start_price) * 100, 2)
                stock_changes[stock] = percent_change
            else:
                stock_changes[stock] = np.nan  # If no data is available, set to NaN

        except Exception as e:
            print(f"Error fetching data for {stock}: {e}")
            stock_changes[stock] = np.nan

    # Create a DataFrame with stock tickers and their percentage changes
    df = pd.DataFrame(list(stock_changes.items()), columns=['Symbol', 'Percent_Change'])

    # Drop any stocks with missing data (NaN values)
    df = df.dropna()

    # Calculate the percentile rank based on percentage change
    df['RSP'] = round(df['Percent_Change'].rank(pct=True) * 100, 2)
    cols = ['Symbol', 'RSP']
    df = df[cols]
    # Sort by percentile rank (optional)
    df = df.sort_values(by='RSP', ascending=False).reset_index(drop=True)

    return df

In [6]:
# function to get stock technicals
def stock_prec_dev(stock_symbol):
    #stock_symbol = 'ULTRACEMCO.NS'
    short_window = 20
    mid_window = 50
    long_window = 200
    moving_avg = 'SMA'

    start = datetime.datetime(*map(int, start_date.split('-')))
    end = datetime.datetime(*map(int, end_date.split('-')))

    stock_df = yfin.Ticker(stock_symbol + '.NS').history(period='max', interval='1d')[map(str.title, ['open', 'close', 'low', 'high', 'volume'])]

    stock_df['Max'] = round(max(stock_df['Close']),2)
    stock_df = stock_df[(stock_df.index <= end_date) & (stock_df.index >= start_date)]
    stock_df['200_SMA'] = round(stock_df['Close'].rolling(window = 200, min_periods = 1).mean(),0)
    stock_df['Dev%_200'] = round((stock_df['Close'] - stock_df['200_SMA'])*100/stock_df['200_SMA'],2)
    stock_df.dropna(axis = 0, inplace = True) # remove any null rows

    stock_df['20_SMA'] = stock_df['Close'].rolling(window=20).mean()
    stock_df['50_SMA'] = stock_df['Close'].rolling(window=50).mean()
    stock_df['Symbol'] = stock_symbol

    stock_df['Close'] = round(stock_df['Close'],2)
    stock_df['Min'] = round(min(stock_df['Close']),2)
    stock_df['RSI_14'] = ta.momentum.RSIIndicator(close=stock_df['Close'], window=14).rsi()
    stock_df['RSI_14'] = round(stock_df['RSI_14'],0)
    stock_df['Prev_Close'] = stock_df['Close'].shift(1)
    stock_df.drop(['Open', 'Low', 'High', 'Volume'], axis=1, inplace=True)
    stock_df = stock_df.tail(1)

    max_SMA = max(stock_df['20_SMA'].item(), stock_df['50_SMA'].item(), stock_df['200_SMA'].item())
    min_SMA = min(stock_df['20_SMA'].item(), stock_df['50_SMA'].item(), stock_df['200_SMA'].item())
    ABS_Spread = max_SMA - min_SMA
    stock_df['Spread%'] = round((ABS_Spread / stock_df['200_SMA'].item()) * 100,2)

    return stock_df

# function to compute stock attributes
def get_common_features(stock_ids, df_mypf):

  df_prec_dev = pd.DataFrame()
  df_tmp = get_screener_features()
  df_rs = get_relative_strength(stock_ids)

  for stock_id in stock_ids:
      tmp = stock_prec_dev(stock_id)
      tmp = tmp.reset_index()
      df_prec_dev = pd.concat([df_prec_dev, tmp], ignore_index = True)
  df_prec_dev = pd.merge(df_prec_dev, df_mypf, on= 'Symbol')
  df_prec_dev = pd.merge(df_prec_dev, df_tmp, on= 'Symbol', how='left')
  df_prec_dev = pd.merge(df_prec_dev, df_rs, on= 'Symbol', how='left')
  #print(df_prec_dev.columns)
  df_prec_dev['Curr_PE'] = round(df_prec_dev['Close']/df_prec_dev['EPS'],1)
  df_prec_dev['Dev%_PE'] = round((df_prec_dev['Curr_PE'] - df_prec_dev['MedPE'])*100/df_prec_dev['MedPE'],2)
  df_prec_dev['Conviction'] = df_prec_dev['Conviction'] + '-' + df_prec_dev['CapType']
  return df_prec_dev

# function to arrange stock features
def arrange_features(df_stocks, common_cols, diff_cols):
  df_stocks_common = df_stocks[common_cols].drop_duplicates()
  df_stocks_diff = df_stocks[diff_cols]
  df_stocks_diff['Investment'] = df_stocks_diff['AvgCost'] * df_stocks_diff['Shares']
  df_stocks_diff = df_stocks_diff.groupby(['Symbol'])[['Shares', 'Investment']].aggregate(['sum']).reset_index()
  df_stocks_diff.columns = ['Symbol', 'Shares', 'Investment']
  df_stocks_diff['AvgCost'] = round(df_stocks_diff['Investment']/df_stocks_diff['Shares'],2)
  df_stocks = pd.merge(df_stocks_diff, df_stocks_common, on='Symbol')
  return df_stocks

# plot fact distribution across dimension
def plot_pie_chart(df, dimension, fact):
  # grouping the data by category and calculating the sum of fact for each type
  grouped_data = df.groupby(dimension)[fact].sum()

  # sorting the grouped data in descending order
  grouped_data = grouped_data.sort_values(ascending=False)

  # creating a pie chart
  grouped_data.plot.pie(autopct='%1.1f%%', startangle=90, figsize=(6, 6))

  # adding a title and displaying the plot
  plt.title(f'{dimension} {fact} Distribution')
  plt.ylabel('')  # To hide the y-label
  plt.show()

In [7]:
# function to get portfolio features

def get_portfolio_features(df_common_features):

  print_date_time()
  print('-------------------')

  #df_common_features["Target"] = df_common_features["Target"].fillna(df_common_features["Max"])
  df_common_features['NTT'] = np.where(df_common_features['Strategy']== 'NTT', df_common_features["Target"], df_common_features['Max'])
  df_common_features['LTT'] = np.where(df_common_features['Strategy']== 'BTT', df_common_features["Target"], df_common_features['Max'])
  df_common_features['BOL'] = df_common_features['Min']

  tmp_df = df_common_features[df_common_features['Symbol'].isin(mypf_df[mypf_df['InPortfolio'] != 'NA'].Symbol.values)]
  print('qualified stocks: '+str(len(tmp_df['Symbol'].unique())))
  tmp_df1 = tmp_df[tmp_df['LatestQtr'] == 1]
  print('with latest results: '+str(len(tmp_df1['Symbol'].unique())))
  tmp_df1 = tmp_df1[tmp_df1['StarStock'] == 1]
  print('still star stocks: '+str(len(tmp_df1['Symbol'].unique())))
  tmp_df['Investment'] = tmp_df['AvgCost'] * tmp_df['Shares']
  tmp_df['Current'] = round(tmp_df['Close'] * tmp_df['Shares'],0)
  tmp_df['Previous'] = tmp_df['Prev_Close'] * tmp_df['Shares']
  tmp_df['EstimatedST'] = tmp_df['NTT'] * tmp_df['Shares']
  tmp_df['EstimatedLT'] = tmp_df['LTT'] * tmp_df['Shares']
  tmp_df['Current P/L'] = round((tmp_df['Current'] - tmp_df['Investment']),0)
  tmp_df['Today P/L%'] = round((tmp_df['Current'] - tmp_df['Previous'])*100/tmp_df['Previous'],2)
  tmp_df['Current P/L%'] = round((tmp_df['Current'] - tmp_df['Investment'])*100/tmp_df['Investment'],2)
  tmp_df['EstimatedST P/L%'] = round((tmp_df['EstimatedST'] - tmp_df['Investment'])*100/tmp_df['Investment'],2)
  tmp_df['EstimatedLT P/L%'] = round((tmp_df['EstimatedLT'] - tmp_df['Investment'])*100/tmp_df['Investment'],2)
  tmp_df['NTT%'] = round((tmp_df['NTT'] - tmp_df['Close'])*100/tmp_df['Close'],2)
  tmp_df['LTT%'] = round((tmp_df['LTT'] - tmp_df['Close'])*100/tmp_df['Close'],2)
  tmp_df['Gained%'] = round((tmp_df['Close'] - tmp_df['BOL'])*100/tmp_df['BOL'],2)
  investment = round(sum(tmp_df['AvgCost']*tmp_df['Shares']),0)
  current = round(sum(tmp_df['Close']*tmp_df['Shares']),0)
  tmp_df['InitAlloc%'] = round(tmp_df['Investment']*100/investment,2)
  tmp_df['CurrAlloc%'] = round(tmp_df['Current']*100/current,2)
  tmp_df['FTT'] = tmp_df['LTT']
  tmp_df.loc[tmp_df['Strategy'] == 'NTT', 'FTT'] = tmp_df['NTT']
  tmp_df['FTT%'] = tmp_df['LTT%']
  tmp_df.loc[tmp_df['Strategy'] == 'NTT', 'FTT%'] = tmp_df['NTT%']
  tmp_df['FTT Amt'] = round(tmp_df['FTT%'] * tmp_df['Current']/100,0)
  tmp_df['OTT%'] = round((tmp_df['FTT'] - tmp_df['AvgCost'])*100/tmp_df['AvgCost'],2)
  tmp_df['RRR Ind'] = round(tmp_df['Current P/L']/tmp_df['FTT Amt'],2)
  tmp_df['Risk Ind'] = round(tmp_df['Current P/L%']*tmp_df['CurrAlloc%'],0)

  return tmp_df

# function to print portfolio features
def print_portfolio_stats(df_portfolio_features, myinvmt_df):
  from pyxirr import xirr

  total_booked_amt, reserve_amt, cy_booked_amt, py_booked_amt = get_amt()

  dates = myinvmt_df['Date'].values
  dates = np.append(dates, datetime.date.today().strftime('%d-%b-%y'))
  investment = myinvmt_df['Investment'].values
  dates= pd.to_datetime(dates)

  current = round(sum(df_portfolio_features['Close']*df_portfolio_features['Shares']),0) + reserve_amt
  investment_xirr = np.append(investment, current)
  cagr = round(xirr(pd.DataFrame({"dates": dates, "amounts": investment_xirr}))*100,2)

  investment = -sum(investment)
  invested = round(sum(df_portfolio_features['AvgCost']*df_portfolio_features['Shares']),0) + reserve_amt
  previous = round(sum(df_portfolio_features['Prev_Close']*df_portfolio_features['Shares']),0) + reserve_amt
  cy_invested = investment + py_booked_amt

  today_pnl_amount = current-previous
  today_pnl_percentage = round((current-previous)*100/previous,2)

  curr_pnl_amount = current-invested
  curr_pnl_percentage = round((curr_pnl_amount)*100/(cy_invested),2)

  cy_pnl_amount = cy_booked_amt + curr_pnl_amount
  cy_pnl_percentage = round((cy_pnl_amount)*100/cy_invested,2)

  overall_pnl_amount = total_booked_amt + curr_pnl_amount
  overall_pnl_percentage = round((overall_pnl_amount)*100/investment,2)

  estimate_st = round(sum(df_portfolio_features['FTT']*df_portfolio_features['Shares']),0)  + reserve_amt
  est_st_pnl_amount = estimate_st-current
  est_st_pnl_percentage = round((est_st_pnl_amount)*100/current,2)

  estimate_lt = round(sum(df_portfolio_features['LTT']*df_portfolio_features['Shares']),0)  + reserve_amt
  est_lt_pnl_amount = estimate_lt-current
  est_lt_pnl_percentage = round((est_lt_pnl_amount)*100/current,2)

  total_profit = round(sum(df_portfolio_features[df_portfolio_features['Current P/L%'] > 0]['Current']) - sum(df_portfolio_features[df_portfolio_features['Current P/L%'] > 0]['Investment']),0)
  total_loss = round(sum(df_portfolio_features[df_portfolio_features['Current P/L%'] < 0]['Current']) - sum(df_portfolio_features[df_portfolio_features['Current P/L%'] < 0]['Investment']),0)

  cy_booked_percentage = round((cy_booked_amt)*100/current,2)
  py_booked_percentage = round((py_booked_amt)*100/investment,2)
  total_booked_percentage = round((total_booked_amt)*100/investment,2)

  print('-------------------')
  print('Initial Investment: ', format_amt(investment))
  print('CY Investment: ', format_amt(cy_invested))
  print('Reserve: ', format_amt(reserve_amt))
  print('Current: ',  format_amt(current))
  print('-------------------')
  print('Today PnL: '+ '{} ({}%)'.format(format_amt(today_pnl_amount), today_pnl_percentage))
  print('Current PnL: '+ '{} ({}%)'.format(format_amt(curr_pnl_amount), curr_pnl_percentage))
  print('CY Booked + Current PnL: '+ '{} ({}%)'.format(format_amt(cy_pnl_amount), cy_pnl_percentage))
  print('-------------------')
  print('Total profit: ', format_amt(total_profit))
  print('Total loss: ', format_amt(total_loss))
  print('-------------------')
  print('Total Booked + Current PnL: '+ '{} ({}%)'.format(format_amt(overall_pnl_amount), overall_pnl_percentage))
  print('Total Booked PnL: '+ '{} ({}%)'.format(format_amt(total_booked_amt), total_booked_percentage))
  print('Curr Year Booked PnL: '+ '{} ({}%)'.format(format_amt(cy_booked_amt), cy_booked_percentage))
  print('Prev Year Booked PnL: '+ '{} ({}%)'.format(format_amt(py_booked_amt), py_booked_percentage))
  print('===================')
  print('Est FTT: ',  format_amt(estimate_st))
  print('Est FTT PnL: '+ '{} ({}%)'.format(format_amt(est_st_pnl_amount), est_st_pnl_percentage))

  print('===================')
  print('Deployed: ', format_amt(investment))

  print('Current: ', format_amt(current))

  print('CAGR/XIRR %: '+'{}%'.format(cagr))

In [8]:
# get start and end date
start_date, end_date = get_start_end_date()

# get portfolio and prospects data
mypfs_df = get_mypfs_df()
mypps_df = get_mypps_df()
myinvmt_df = get_myinvmt_df()

# merge above datasets
mypf_df = pd.merge(mypfs_df, mypps_df, on="Symbol")

# seggregate dm and sv portfolio
dm_pf = mypf_df[mypf_df['InPortfolio'] == 'DM']
sv_pf = mypf_df[mypf_df['InPortfolio'] == 'SV']

# build portfolio stock dataframe
dm_stocks = get_stock_ids(dm_pf)
sv_stocks = get_stock_ids(sv_pf)
df_stocks = pd.concat([dm_pf,sv_pf], ignore_index = True)

# arrange common and diff stock features
common_cols = ['Symbol', 'Target', 'Criteria', 'Strategy', 'CumlRnk', 'LatestQtr', 'StarStock', 'Conviction', 'Category', 'InFolio', 'XIRR', 'MBQ']
diff_cols = ['Symbol', 'AvgCost', 'Shares']
df_stocks = arrange_features(df_stocks, common_cols, diff_cols)

# get common features
stock_ids = df_stocks['Symbol'].values
df_common_features = get_common_features(stock_ids, df_stocks)

df_common_features.reset_index(drop=True, inplace=True)
df_common_features.drop(['Date'], axis=1, inplace=True)
# get and print portfolio features
df_portfolio_features = get_portfolio_features(df_common_features)

print_portfolio_stats(df_portfolio_features, myinvmt_df)

df = df_portfolio_features
#plot_pie_chart(df, 'CapType', 'Current')
list_ox40n = list(df[df['MBQ'].str.contains('OX40N', na=False)]['Symbol'].values)

Run date time (IST): 2026-08-18 15:21:39
-------------------
qualified stocks: 87
with latest results: 30
still star stocks: 19
-------------------
Initial Investment:  1.46 C
CY Investment:  1.89 C
Reserve:  3.69 L
Current:  1.58 C
-------------------
Today PnL: -1.04 L (-0.66%)
Current PnL: -34.96 L (-18.5%)
CY Booked + Current PnL: -29.90 L (-15.82%)
-------------------
Total profit:  3.37 L
Total loss:  -38.32 L
-------------------
Total Booked + Current PnL: 12.97 L (8.88%)
Total Booked PnL: 47.93 L (32.82%)
Curr Year Booked PnL: 5.06 L (3.2%)
Prev Year Booked PnL: 42.87 L (29.35%)
===================
Est FTT:  2.67 C
Est FTT PnL: 1.09 C (69.07%)
===================
Deployed:  1.46 C
Current:  1.58 C
CAGR/XIRR %: 3.56%

In [9]:
# top 5 near their targets
cols = ['Symbol', 'Today P/L%', 'Current P/L%', 'FTT%', 'OTT%', 'FTT Amt', 'Current P/L', 'Current', 'FTT', 'Dev%_PE', 'RSI_14','Conviction', 'Spread%',  'CumlRnk', 'RRR Ind', 'CurrAlloc%', 'Gained%', 'Criteria', 'Strategy', 'Category']
df_tmp = df_portfolio_features[~df_portfolio_features['Symbol'].isin(['ENRIN','BLUSPRING','DIGITIDE'])]
df_tmp = df_tmp.sort_values(by = 'FTT Amt', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
66,SIEMENS,0.43,6.40,4.17,10.83,8257.0,11905.0,198000.0,4125.00,-13.70,64.0,H-LC,13.66,51.0,1.44,1.28,39.70,AR,NTT,ELECTRICAL
78,UNITDSPR,-1.46,11.84,7.98,20.77,20897.0,27726.0,261870.0,1644.00,-4.62,60.0,X-MC,10.92,64.0,1.33,1.70,25.88,X40N,NTT,BREWERIES
77,TTKPRESTIG,0.19,-22.88,29.79,0.09,23152.0,-23061.0,77716.0,770.00,-6.23,41.0,M-SC,10.21,250.0,-1.00,0.50,39.88,OX40N,NTT,DURABLES
52,M&M,0.65,7.76,10.27,18.82,26635.0,18669.0,259350.0,3762.88,-6.96,58.0,X-LC,4.78,25.0,0.70,1.68,17.65,X40N,ATH,AUTO
54,MASFIN,-0.75,-7.23,31.04,21.57,28215.0,-7080.0,90900.0,397.04,-28.13,43.0,H-SC,1.15,167.0,-0.25,0.59,8.35,XR,ATH,FINANCE

In [10]:
# top 5 today
df_tmp = df_portfolio_features.sort_values(by = 'Today P/L%', ascending=False)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
27,GLAXO,6.74,15.82,17.16,35.69,39607.0,31524.0,230808.0,3380.16,-13.09,82.0,X-MC,8.89,56.0,0.80,1.50,37.18,X40,ATH,PHARMA
74,TITAGARH,2.26,-20.96,84.40,45.74,161547.0,-50771.0,191406.0,1548.00,NaN,49.0,NaN,7.65,175.0,-0.31,1.24,46.04,XY24,NTT,ENGINEERING
12,BOSCH-HCIL,1.84,-24.13,31.79,-0.01,30827.0,-30835.0,96970.0,2282.00,757.93,77.0,M-SC,6.86,231.0,-1.00,0.63,65.06,OX40N,BTT,AC
0,5PAISA,1.76,-26.22,53.03,12.90,85484.0,-57296.0,161200.0,593.00,3.45,60.0,H-SC,11.06,170.0,-0.67,1.04,55.56,OX40N,NTT,FINANCE
58,RAJOOENG,1.65,-50.24,180.59,39.61,92101.0,-51500.0,51000.0,143.10,NaN,45.0,NaN,15.77,136.0,-0.56,0.33,9.25,AR,ATH,MISC

In [11]:
# bottom 5 today
df_tmp = df_portfolio_features.sort_values(by = 'Today P/L%', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
19,COLPAL,-3.11,-27.74,93.56,39.86,178045.0,-73065.0,190300.0,3683.41,-12.49,29.0,X-MC,1.40,62.0,-0.41,1.23,7.64,XY25,ATH,FMCG
72,TATAELXSI,-2.53,-47.18,149.96,32.03,104425.0,-62200.0,69635.0,9161.00,-39.97,46.0,H-SC,18.03,158.0,-0.60,0.45,8.19,OX40N,NTT,IT
29,GREENPANEL,-2.52,-55.93,224.82,43.14,181376.0,-102402.0,80676.0,537.00,NaN,28.0,NaN,11.56,225.0,-0.56,0.52,0.00,XY24,NTT,MISC
4,ASIANPAINT,-2.51,-5.71,30.93,23.45,82660.0,-16189.0,267250.0,3430.49,-16.82,36.0,X-LC,5.25,30.0,-0.20,1.73,24.59,X40,ATH,PAINTS
15,CAMS,-2.33,-0.66,25.30,24.48,63302.0,-1650.0,250206.0,950.00,-5.26,42.0,X-SC,5.57,89.0,-0.03,1.62,22.83,X40N,NTT,MISC

In [12]:
# top 5 to exit based on CumlRnk
df_tmp = df_portfolio_features[~df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])]
df_tmp = df_tmp[(df_tmp['Current P/L%'] > -1) & (df_tmp['Current P/L%'] < 1)].sort_values(by = 'CumlRnk', ascending=False)
df_tmp[cols].head()

Empty DataFrame
Columns: [Symbol, Today P/L%, Current P/L%, FTT%, OTT%, FTT Amt, Current P/L, Current, FTT, Dev%_PE, RSI_14, Conviction, Spread%, CumlRnk, RRR Ind, CurrAlloc%, Gained%, Criteria, Strategy, Category]
Index: []

In [13]:
# OX40N stocks to exit
df_tmp = df_portfolio_features[(df_portfolio_features['Symbol'].isin(list_ox40n))].sort_values(by = 'Current P/L%', ascending=False)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
25,FINCABLES,0.77,68.58,23.33,107.91,58068.0,101253.0,248897.0,1641.55,22.65,77.0,M-SC,18.65,220.0,1.74,1.61,87.25,OX40N,ATH,CABLES
67,SIS,-0.53,-4.86,27.46,21.26,29007.0,-5398.0,105634.0,528.00,102.74,38.0,H-SC,21.56,168.0,-0.19,0.68,57.06,OX40N,NTT,MISC
43,INDIGOPNTS,-1.30,-18.60,22.87,0.02,32496.0,-32467.0,142092.0,1408.00,-22.31,62.0,M-SC,7.02,222.0,-1.00,0.92,61.21,OX40N,NTT,PAINTS
77,TTKPRESTIG,0.19,-22.88,29.79,0.09,23152.0,-23061.0,77716.0,770.00,-6.23,41.0,M-SC,10.21,250.0,-1.00,0.50,39.88,OX40N,NTT,DURABLES
12,BOSCH-HCIL,1.84,-24.13,31.79,-0.01,30827.0,-30835.0,96970.0,2282.00,757.93,77.0,M-SC,6.86,231.0,-1.00,0.63,65.06,OX40N,BTT,AC

In [14]:
# top 5 to book for rotation
df_tmp = df_portfolio_features[(df_portfolio_features['Current P/L%'] > 20) ].sort_values(by = 'CumlRnk', ascending=False)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
25,FINCABLES,0.77,68.58,23.33,107.91,58068.0,101253.0,248897.0,1641.55,22.65,77.0,M-SC,18.65,220.0,1.74,1.61,87.25,OX40N,ATH,CABLES

In [15]:
# top 5 to monitor for exit
df_tmp = df_portfolio_features[~df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])]
df_tmp = df_tmp[(df_tmp['Current P/L%'] > 0) ].sort_values(by = 'Dev%_PE', ascending=False)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
25,FINCABLES,0.77,68.58,23.33,107.91,58068.0,101253.0,248897.0,1641.55,22.65,77.0,M-SC,18.65,220.0,1.74,1.61,87.25,OX40N,ATH,CABLES
68,STARHEALTH,-0.11,12.93,30.40,47.26,96513.0,36355.0,317478.0,761.00,-0.37,50.0,H-SC,16.23,173.0,0.38,2.06,37.27,XY24,NTT,INSURANCE

In [16]:
# top 5 to book for rotation from weak conviction
df_tmp = df_portfolio_features[~df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])]
df_tmp = df_tmp[~df_tmp['Criteria'].isin(['XY25','XY24','X40', 'X40N'])].sort_values(by = 'RRR Ind', ascending=False)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
25,FINCABLES,0.77,68.58,23.33,107.91,58068.0,101253.0,248897.0,1641.55,22.65,77.0,M-SC,18.65,220.0,1.74,1.61,87.25,OX40N,ATH,CABLES
3,ALKYLAMINE,-1.22,-19.22,138.35,92.54,112835.0,-19405.0,81558.0,4520.85,NaN,54.0,NaN,14.18,142.0,-0.17,0.53,54.87,SR,ATH,CHEMICALS
67,SIS,-0.53,-4.86,27.46,21.26,29007.0,-5398.0,105634.0,528.00,102.74,38.0,H-SC,21.56,168.0,-0.19,0.68,57.06,OX40N,NTT,MISC
42,INDIAMART,-1.01,-24.70,166.84,100.92,154939.0,-30469.0,92867.0,4675.60,NaN,37.0,NaN,13.63,140.0,-0.20,0.60,0.53,AR,ATH,MISC
71,TANLA,0.52,-34.85,233.45,117.25,411827.0,-94352.0,176409.0,1922.32,NaN,47.0,NaN,15.61,147.0,-0.23,1.14,54.45,AR,ATH,IT

In [17]:
# top 5 to accumulate based on lowest RSI_14
df_tmp = df_portfolio_features[df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])].sort_values(by = 'RSI_14', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
19,COLPAL,-3.11,-27.74,93.56,39.86,178045.0,-73065.0,190300.0,3683.41,-12.49,29.0,X-MC,1.40,62.0,-0.41,1.23,7.64,XY25,ATH,FMCG
56,PGHH,-0.57,-37.67,111.80,32.01,148783.0,-80440.0,133080.0,17616.87,-54.25,31.0,X-SC,19.64,57.0,-0.54,0.86,0.00,X40,ATH,FMCG
47,ITC,-1.04,-25.46,67.28,24.70,199242.0,-101139.0,296139.0,452.00,-30.35,32.0,X-LC,10.46,1.0,-0.51,1.92,0.00,X40,NTT,FMCG
28,GODREJCP,0.43,-15.22,56.76,32.90,120084.0,-37973.0,211564.0,1460.97,-16.89,32.0,X-MC,6.17,32.0,-0.32,1.37,2.98,X40N,ATH,FMCG
55,PAGEIND,-2.25,-4.75,40.24,33.59,102870.0,-12739.0,255640.0,51217.29,-29.22,32.0,X-MC,8.81,55.0,-0.12,1.66,21.40,X40,ATH,APPARELS

In [18]:
# top 5 to accumulate based on Spread and CumlRnk
df_tmp = df_portfolio_features[df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])]
df_tmp = df_tmp[(df_tmp['CumlRnk'] < 100)].sort_values(by = 'Spread%', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
19,COLPAL,-3.11,-27.74,93.56,39.86,178045.0,-73065.0,190300.0,3683.41,-12.49,29.0,X-MC,1.40,62.0,-0.41,1.23,7.64,XY25,ATH,FMCG
23,DMART,-0.23,-2.84,35.26,31.42,106815.0,-8854.0,302936.0,5391.45,-18.52,47.0,X-LC,2.37,14.0,-0.08,1.96,9.32,X40N,ATH,FMCG
50,KOTAKBANK,-1.26,1.91,16.69,18.92,40771.0,4580.0,244282.0,452.46,-13.75,47.0,X-LC,2.37,12.0,0.11,1.58,9.91,X40,ATH,BANKS
26,GILLETTE,-0.50,-11.00,45.76,29.72,103399.0,-27936.0,225960.0,10978.86,-35.84,37.0,X-SC,3.47,83.0,-0.27,1.46,3.84,X40,ATH,FMCG
1,ABBOTINDIA,-1.32,-10.93,29.53,15.37,47041.0,-19555.0,159300.0,34390.26,-27.58,38.0,X-MC,4.06,58.0,-0.42,1.03,7.91,X40,ATH,PHARMA

In [19]:
# top 5 to accumulate based on lowest Gained%
df_tmp = df_portfolio_features[df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])].sort_values(by = 'Gained%', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
20,DABUR,-0.97,-21.24,82.45,43.70,161092.0,-52686.0,195382.0,735.00,-32.11,35.0,X-MC,9.94,70.0,-0.33,1.27,0.00,XY24,BTT,FMCG
47,ITC,-1.04,-25.46,67.28,24.70,199242.0,-101139.0,296139.0,452.00,-30.35,32.0,X-LC,10.46,1.0,-0.51,1.92,0.00,X40,NTT,FMCG
56,PGHH,-0.57,-37.67,111.80,32.01,148783.0,-80440.0,133080.0,17616.87,-54.25,31.0,X-SC,19.64,57.0,-0.54,0.86,0.00,X40,ATH,FMCG
35,HDFCLIFE,-0.87,-7.69,50.75,39.15,117460.0,-19289.0,231448.0,811.41,-32.11,41.0,X-LC,16.49,31.0,-0.16,1.50,0.45,X40,ATH,INSURANCE
34,HDFCBANK,-0.79,-11.67,48.36,31.05,125216.0,-34196.0,258924.0,1073.00,-28.50,33.0,X-LC,12.73,26.0,-0.27,1.68,0.50,X40,BTT,BANKS

In [20]:
# top 5 to accumulate based on lowest CurrAlloc%
df_tmp = df_portfolio_features[df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])].sort_values(by = 'CurrAlloc%', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
56,PGHH,-0.57,-37.67,111.80,32.01,148783.0,-80440.0,133080.0,17616.87,-54.25,31.0,X-SC,19.64,57.0,-0.54,0.86,0.00,X40,ATH,FMCG
2,ACC,-0.90,-41.60,199.36,74.81,312150.0,-111552.0,156576.0,3906.00,-42.24,36.0,X-SC,11.36,85.0,-0.36,1.01,4.60,XY24,BTT,CEMENT
1,ABBOTINDIA,-1.32,-10.93,29.53,15.37,47041.0,-19555.0,159300.0,34390.26,-27.58,38.0,X-MC,4.06,58.0,-0.42,1.03,7.91,X40,ATH,PHARMA
40,ICICIPRULI,-1.22,-17.13,57.20,30.28,93385.0,-33744.0,163261.0,787.27,-46.81,46.0,X-MC,12.47,78.0,-0.36,1.06,8.77,X40,ATH,INSURANCE
39,ICICIGI,0.12,-13.75,37.85,18.89,65325.0,-27520.0,172589.0,2244.41,-14.07,42.0,X-MC,10.31,66.0,-0.42,1.12,2.82,X40,ATH,INSURANCE

In [21]:
# top 5 to accumulate based on CumlRnk
df_tmp = df_portfolio_features.sort_values(by = 'CumlRnk', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
47,ITC,-1.04,-25.46,67.28,24.70,199242.0,-101139.0,296139.0,452.00,-30.35,32.0,X-LC,10.46,1.0,-0.51,1.92,0.00,X40,NTT,FMCG
73,TCS,-1.26,-32.95,85.23,24.20,264745.0,-152649.0,310624.0,4230.71,-44.31,46.0,X-LC,14.32,2.0,-0.58,2.01,15.83,X40,ATH,IT
45,INFY,-2.29,-20.71,77.05,40.38,229993.0,-77972.0,298498.0,1972.00,-41.63,45.0,X-LC,15.93,3.0,-0.34,1.93,13.04,X40,NTT,IT
75,TMPV,-2.24,-23.20,85.87,42.75,274416.0,-96535.0,319572.0,600.00,-84.91,36.0,X-LC,4.44,4.0,-0.35,2.07,9.89,XY24,NTT,AUTO
33,HCLTECH,-2.26,-13.38,43.12,23.97,115590.0,-41421.0,268065.0,1853.42,-15.52,49.0,X-LC,11.45,8.0,-0.36,1.74,26.50,X40,ATH,IT

In [22]:
# top 5 for average up
df_tmp = df_portfolio_features[(df_portfolio_features['Dev%_200'] > 5)].sort_values(by = 'CurrAlloc%', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
44,INDUSINDBK,0.17,-25.26,77.81,32.89,44897.0,-19506.0,57701.0,1800.00,325.21,53.0,L-MC,13.39,258.0,-0.43,0.37,42.26,XR,NTT,BANKS
60,RELAXO,-1.76,-50.23,206.01,52.31,148838.0,-72912.0,72248.0,1176.00,NaN,41.0,NaN,12.26,92.0,-0.49,0.47,61.54,X40N,NTT,FOOTWEAR
3,ALKYLAMINE,-1.22,-19.22,138.35,92.54,112835.0,-19405.0,81558.0,4520.85,NaN,54.0,NaN,14.18,142.0,-0.17,0.53,54.87,SR,ATH,CHEMICALS
12,BOSCH-HCIL,1.84,-24.13,31.79,-0.01,30827.0,-30835.0,96970.0,2282.00,757.93,77.0,M-SC,6.86,231.0,-1.00,0.63,65.06,OX40N,BTT,AC
81,VALIANTORG,0.68,-35.49,169.97,74.15,179380.0,-58069.0,105536.0,838.00,NaN,59.0,NaN,7.08,145.0,-0.32,0.68,57.05,XR,NTT,CHEMICALS

In [23]:
# top 5 RSP
df_tmp = df_portfolio_features.sort_values(by = 'RSP', ascending=False)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
25,FINCABLES,0.77,68.58,23.33,107.91,58068.0,101253.0,248897.0,1641.55,22.65,77.0,M-SC,18.65,220.0,1.74,1.61,87.25,OX40N,ATH,CABLES
12,BOSCH-HCIL,1.84,-24.13,31.79,-0.01,30827.0,-30835.0,96970.0,2282.00,757.93,77.0,M-SC,6.86,231.0,-1.00,0.63,65.06,OX40N,BTT,AC
81,VALIANTORG,0.68,-35.49,169.97,74.15,179380.0,-58069.0,105536.0,838.00,NaN,59.0,NaN,7.08,145.0,-0.32,0.68,57.05,XR,NTT,CHEMICALS
27,GLAXO,6.74,15.82,17.16,35.69,39607.0,31524.0,230808.0,3380.16,-13.09,82.0,X-MC,8.89,56.0,0.80,1.50,37.18,X40,ATH,PHARMA
38,HYUNDAI,-0.21,13.04,27.33,43.94,77649.0,32783.0,284115.0,2782.73,17.21,63.0,X-LC,4.97,29.0,0.42,1.84,30.45,X40N,ATH,AUTO

In [24]:
# Top N allocation
df_tmp = df_portfolio_features.sort_values(by = 'CurrAlloc%', ascending=False)
top_n_values = [10, 25, 50]

sum_df = pd.DataFrame({
    'Top_N': top_n_values,
    'Sum_Alloc%': [df_tmp['CurrAlloc%'].head(n).sum() for n in top_n_values]
})

sum_df

   Top_N  Sum_Alloc%
0     10       19.72
1     25       45.05
2     50       77.61

In [25]:
# market-cap-wise allocation
df_tmp = df_portfolio_features[cols]
df_tmp.groupby(df_tmp['Conviction'].str[-2:])['CurrAlloc%'].sum().sort_values(ascending=False)

Conviction
LC    38.00
MC    22.28
SC    21.59
Name: CurrAlloc%, dtype: float64

In [26]:
# criteria-wise allocation
df_portfolio_features.groupby('Criteria')['CurrAlloc%'].sum().sort_values(ascending=False)

Criteria
X40      26.62
XY24     23.99
X40N     18.63
XR        9.10
OX40N     7.35
XY25      7.26
AR        6.14
SR        0.86
Name: CurrAlloc%, dtype: float64

In [27]:
# conviction-wise allocation
df_portfolio_features.groupby('Conviction')['CurrAlloc%'].sum().sort_values(ascending=False)

Conviction
X-LC    34.31
X-MC    19.66
H-SC     8.48
X-SC     7.64
M-SC     5.47
H-LC     2.88
M-MC     1.21
H-MC     1.04
M-LC     0.81
L-MC     0.37
Name: CurrAlloc%, dtype: float64

In [28]:
# sector-wise stats
df_tmp = df_portfolio_features.groupby('Category')[['CurrAlloc%', 'Current', 'Current P/L', 'FTT Amt']].sum().sort_values(by=['Current', 'Current P/L'], ascending=False)
df_tmp['Current P/L%'] = round(df_tmp['Current P/L'] * 100 / df_tmp['Current'], 2)
df_tmp['FTT%'] = round(df_tmp['FTT Amt'] * 100 / df_tmp['Current'], 2)
cols = ['CurrAlloc%', 'Current P/L%', 'FTT%']
df_tmp[cols].sort_values(by=['CurrAlloc%'], ascending=False)

               CurrAlloc%  Current P/L%    FTT%
Category
FMCG                15.45        -25.03   69.99
IT                  11.09        -39.24  108.30
FINANCE             10.73        -16.47   66.64
AUTO                 8.27         -5.85   43.76
BANKS                6.12        -13.03   61.78
MISC                 5.96        -34.02   87.92
PHARMA               5.84          7.91   18.20
INSURANCE            5.74         -5.00   42.12
PAINTS               5.48        -16.34   36.18
ELECTRICAL           4.22         -8.47   42.44
AC                   1.85        -12.21   42.64
REFINERIES           1.75        -10.59   47.73
BREWERIES            1.70         10.59    7.98
FOOTWEAR             1.67        -71.26  139.92
APPARELS             1.66         -4.98   40.24
CABLES               1.61         40.68   23.33
DURABLES             1.48        -68.83  109.90
TRAVEL               1.43       -102.67  204.15
CERAMICS             1.34        -48.05   93.03
ENGINEERING          1.24        -26.53   84.40
CHEMICALS            1.21        -41.41  156.19
CEMENT               1.01        -71.24  199.36
JEWELLERY            0.96       -116.74  192.04
ENTERTAINMENT        0.69        -80.54  188.22
HEALTHCARE           0.69        -70.21  112.93
TEXTILES             0.39        -52.76   96.32
HOTELS               0.37        -98.79  168.91

In [29]:
# money to be made criteria-wise
df_portfolio_features.groupby('Criteria')['FTT Amt'].agg(['sum', 'count']).sort_values(by='sum', ascending=False)

                sum  count
Criteria
XY24      3625532.0     19
X40       2115126.0     18
XR        1392143.0     13
X40N      1205801.0     12
AR        1056203.0      8
OX40N      654251.0     10
XY25       580262.0      5
SR         283783.0      2

In [30]:
# money to be made conviction-wise
df_portfolio_features.groupby('Conviction')['FTT Amt'].agg(['sum', 'count']).sort_values(by='sum', ascending=False)

                  sum  count
Conviction
X-LC        2429596.0     19
X-MC        1472076.0     14
X-SC        1099491.0      6
H-SC         841013.0      8
M-SC         319428.0      6
H-MC         253096.0      1
M-LC         167635.0      1
M-MC          58786.0      1
H-LC          45555.0      2
L-MC          44897.0      1

In [31]:
# money to be made criteria and conviction-wise
df_portfolio_features.groupby(['Conviction', 'Criteria'])['FTT Amt'].agg(['sum', 'count']).sort_values(by='sum', ascending=False)

                           sum  count
Conviction Criteria
X-LC       X40       1244103.0      9
X-SC       XY24       674772.0      2
H-SC       XY24       528729.0      3
X-MC       X40        507304.0      6
           X40N       468432.0      4
X-LC       XY24       455843.0      2
           X40N       415994.0      5
X-MC       XY25       268640.0      2
H-MC       XY24       253096.0      1
X-LC       XY25       252836.0      2
X-SC       X40        252182.0      2
X-MC       XY24       227700.0      2
H-SC       OX40N      218916.0      3
X-SC       X40N       172537.0      2
M-LC       XR         167635.0      1
M-SC       OX40N      144543.0      4
           XY24       116715.0      1
H-SC       XR          93368.0      2
X-LC       XR          60820.0      1
M-MC       XY25        58786.0      1
M-SC       XR          58170.0      1
H-LC       AR          45555.0      2
L-MC       XR          44897.0      1

In [32]:
# notebook execution time

end_time = time.time()
execution_time = round(end_time - start_time, 0)
print(f"Notebook execution time: {execution_time} seconds")

Notebook execution time: 30.0 seconds