<a href="https://colab.research.google.com/github/ankit-rathi/Quantvesting_v2/blob/main/myStocks_Portfolio_Analysis.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
'''
!pip install pandas==2.2.2 -qq
!pip install pyxirr -qq
!pip install ta -qq
!pip install yfinance==0.2.59 -qq
'''

'\n!pip install pandas==2.2.2 -qq\n!pip install pyxirr -qq\n!pip install ta -qq\n!pip install yfinance==0.2.59 -qq\n'

In [2]:
# import libraries

import numpy as np
import pandas as pd
import datetime
import warnings
warnings.filterwarnings('ignore')
import yfinance as yfin
import ta
import matplotlib.pyplot as plt
import requests

In [3]:
# notebook start time
import time
import datetime
import pytz

start_time = time.time()

# function to print date timestamp
def print_date_time():
  tz_NY = pytz.timezone('Asia/Kolkata')
  datetime_NY = datetime.datetime.now(tz_NY)
  print("Run date time (IST):", datetime_NY.strftime("%Y-%m-%d %H:%M:%S"))

In [4]:
# function to get booked and reserved amount
def get_amt():
  # fetch the JSON data from the URL
  url = "https://raw.githubusercontent.com/ankit-rathi/Tradevesting_v1/main/data/myPortfolioAmts.json"
  response = requests.get(url)
  pf_amts = response.json()  # parse the JSON data

  # extract values from the JSON
  py_booked_amt_dm = pf_amts["py_booked_amt_dm"]
  py_booked_amt_sv = pf_amts["py_booked_amt_sv"]
  cy_booked_amt_dm = pf_amts["cy_booked_amt_dm"]
  cy_booked_amt_sv = pf_amts["cy_booked_amt_sv"]
  reserve_amt_dm = pf_amts["reserve_amt_dm"]
  reserve_amt_sv = pf_amts["reserve_amt_sv"]

  # perform calculations
  py_booked_amt = py_booked_amt_dm + py_booked_amt_sv
  cy_booked_amt = cy_booked_amt_dm + cy_booked_amt_sv
  reserve_amt = reserve_amt_dm + reserve_amt_sv
  total_booked_amt = py_booked_amt + cy_booked_amt

  return total_booked_amt, reserve_amt, cy_booked_amt, py_booked_amt

gen_output = 0

In [5]:
# function to format the amount
def format_amt(number):
    abs_number = abs(number)

    if abs_number >= 1_00_00_000:  # Crores
        formatted_amt = f"{number / 1_00_00_000:.2f} C"
    elif abs_number >= 1_00_000:  # Lakhs
        formatted_amt = f"{number / 1_00_000:.2f} L"
    elif abs_number >= 1_000:  # Thousands
        formatted_amt = f"{number / 1_000:.2f} K"
    else:
        formatted_amt = f"{number:.2f}"

    return formatted_amt

# function to set start and end date
def get_start_end_date():
  start_date = (datetime.date.today() + datetime.timedelta(days=-365)).strftime('%Y-%m-%d')
  end_date = (datetime.date.today() + datetime.timedelta(days=1)).strftime('%Y-%m-%d')
  return start_date, end_date

# function to fetch my portfolio csv
def get_mypfs_df():
  mypfs_df = pd.read_csv('https://raw.githubusercontent.com/ankit-rathi/Tradevesting_v1/main/data/myPortfolioStocks.csv')
  return mypfs_df

# function to fetch my prospects csv
def get_mypps_df():
  mypps_df = pd.read_csv('https://raw.githubusercontent.com/ankit-rathi/Tradevesting_v1/main/data/myProspectsScrips.csv')
  return mypps_df

# function to fetch screener data
def get_myscreen_df():
  myscreen_df = pd.read_csv('https://raw.githubusercontent.com/ankit-rathi/Tradevesting_v1/main/data/myScreenerDB.csv')
  return myscreen_df

# function to fetch momentum data
def get_myinvmt_df():
  myinvmt_df = pd.read_csv('https://raw.githubusercontent.com/ankit-rathi/Tradevesting_v1/main/data/myInvestments.csv')
  return myinvmt_df

# function to get the stock ids
def get_stock_ids(df_pf):
  stock_n100 = df_pf['Symbol'].unique()

  exclude = ['CADILAHC','MMTC', 'MASFIN']

  stock_ids = df_pf[~df_pf['Symbol'].isin(exclude) ]['Symbol'].unique()

  #mypf = mypf[mypf.Forecast.notnull()]
  #stock_ids = mypf['Symbol'].unique()

  #stock_ids.sort()
  return stock_ids

# get features from screener data
def get_screener_features():
  myscreen_df = get_myscreen_df()
  cols = ['Symbol', 'EPS', 'MedPE', 'ROCE%', 'ROE%', 'CapType']
  return myscreen_df[cols]

# get relative strength
def get_relative_strength(stock_list):

    # Dictionary to store stock tickers and their corresponding percentage price change
    stock_changes = {}

    # Loop through each stock and fetch its price data
    for stock in stock_list:
        try:
            # Download the stock data for the given date range
            stock_data = yfin.Ticker(stock + '.NS').history(period='1mo', interval='1d')[map(str.title, ['open', 'close', 'low', 'high', 'volume'])]

            # Calculate the percentage change for the stock
            if len(stock_data) > 0:
                start_price = stock_data['Close'].iloc[0]
                end_price = stock_data['Close'].iloc[-1]
                percent_change = round(((end_price - start_price) / start_price) * 100, 2)
                stock_changes[stock] = percent_change
            else:
                stock_changes[stock] = np.nan  # If no data is available, set to NaN

        except Exception as e:
            print(f"Error fetching data for {stock}: {e}")
            stock_changes[stock] = np.nan

    # Create a DataFrame with stock tickers and their percentage changes
    df = pd.DataFrame(list(stock_changes.items()), columns=['Symbol', 'Percent_Change'])

    # Drop any stocks with missing data (NaN values)
    df = df.dropna()

    # Calculate the percentile rank based on percentage change
    df['RSP'] = round(df['Percent_Change'].rank(pct=True) * 100, 2)
    cols = ['Symbol', 'RSP']
    df = df[cols]
    # Sort by percentile rank (optional)
    df = df.sort_values(by='RSP', ascending=False).reset_index(drop=True)

    return df

In [6]:
# function to get stock technicals
def stock_prec_dev(stock_symbol):
    #stock_symbol = 'ULTRACEMCO.NS'
    short_window = 20
    mid_window = 50
    long_window = 200
    moving_avg = 'SMA'

    start = datetime.datetime(*map(int, start_date.split('-')))
    end = datetime.datetime(*map(int, end_date.split('-')))

    stock_df = yfin.Ticker(stock_symbol + '.NS').history(period='max', interval='1d')[map(str.title, ['open', 'close', 'low', 'high', 'volume'])]

    stock_df['Max'] = round(max(stock_df['Close']),2)
    stock_df = stock_df[(stock_df.index <= end_date) & (stock_df.index >= start_date)]
    stock_df['200_SMA'] = round(stock_df['Close'].rolling(window = 200, min_periods = 1).mean(),0)
    stock_df['Dev%_200'] = round((stock_df['Close'] - stock_df['200_SMA'])*100/stock_df['200_SMA'],2)
    stock_df.dropna(axis = 0, inplace = True) # remove any null rows

    stock_df['20_SMA'] = stock_df['Close'].rolling(window=20).mean()
    stock_df['50_SMA'] = stock_df['Close'].rolling(window=50).mean()
    stock_df['Symbol'] = stock_symbol

    stock_df['Close'] = round(stock_df['Close'],2)
    stock_df['Min'] = round(min(stock_df['Close']),2)
    stock_df['RSI_14'] = ta.momentum.RSIIndicator(close=stock_df['Close'], window=14).rsi()
    stock_df['RSI_14'] = round(stock_df['RSI_14'],0)
    stock_df['Prev_Close'] = stock_df['Close'].shift(1)
    stock_df.drop(['Open', 'Low', 'High', 'Volume'], axis=1, inplace=True)
    stock_df = stock_df.tail(1)

    max_SMA = max(stock_df['20_SMA'].item(), stock_df['50_SMA'].item(), stock_df['200_SMA'].item())
    min_SMA = min(stock_df['20_SMA'].item(), stock_df['50_SMA'].item(), stock_df['200_SMA'].item())
    ABS_Spread = max_SMA - min_SMA
    stock_df['Spread%'] = round((ABS_Spread / stock_df['200_SMA'].item()) * 100,2)

    return stock_df

# function to compute stock attributes
def get_common_features(stock_ids, df_mypf):

  df_prec_dev = pd.DataFrame()
  df_tmp = get_screener_features()
  df_rs = get_relative_strength(stock_ids)

  for stock_id in stock_ids:
      tmp = stock_prec_dev(stock_id)
      tmp = tmp.reset_index()
      df_prec_dev = pd.concat([df_prec_dev, tmp], ignore_index = True)
  df_prec_dev = pd.merge(df_prec_dev, df_mypf, on= 'Symbol')
  df_prec_dev = pd.merge(df_prec_dev, df_tmp, on= 'Symbol', how='left')
  df_prec_dev = pd.merge(df_prec_dev, df_rs, on= 'Symbol', how='left')
  #print(df_prec_dev.columns)
  df_prec_dev['Curr_PE'] = round(df_prec_dev['Close']/df_prec_dev['EPS'],1)
  df_prec_dev['Dev%_PE'] = round((df_prec_dev['Curr_PE'] - df_prec_dev['MedPE'])*100/df_prec_dev['MedPE'],2)
  df_prec_dev['Conviction'] = df_prec_dev['Conviction'] + '-' + df_prec_dev['CapType']
  return df_prec_dev

# function to arrange stock features
def arrange_features(df_stocks, common_cols, diff_cols):
  df_stocks_common = df_stocks[common_cols].drop_duplicates()
  df_stocks_diff = df_stocks[diff_cols]
  df_stocks_diff['Investment'] = df_stocks_diff['AvgCost'] * df_stocks_diff['Shares']
  df_stocks_diff = df_stocks_diff.groupby(['Symbol'])[['Shares', 'Investment']].aggregate(['sum']).reset_index()
  df_stocks_diff.columns = ['Symbol', 'Shares', 'Investment']
  df_stocks_diff['AvgCost'] = round(df_stocks_diff['Investment']/df_stocks_diff['Shares'],2)
  df_stocks = pd.merge(df_stocks_diff, df_stocks_common, on='Symbol')
  return df_stocks

# plot fact distribution across dimension
def plot_pie_chart(df, dimension, fact):
  # grouping the data by category and calculating the sum of fact for each type
  grouped_data = df.groupby(dimension)[fact].sum()

  # sorting the grouped data in descending order
  grouped_data = grouped_data.sort_values(ascending=False)

  # creating a pie chart
  grouped_data.plot.pie(autopct='%1.1f%%', startangle=90, figsize=(6, 6))

  # adding a title and displaying the plot
  plt.title(f'{dimension} {fact} Distribution')
  plt.ylabel('')  # To hide the y-label
  plt.show()

In [7]:
# function to get portfolio features

def get_portfolio_features(df_common_features):

  print_date_time()
  print('-------------------')

  #df_common_features["Target"] = df_common_features["Target"].fillna(df_common_features["Max"])
  df_common_features['NTT'] = np.where(df_common_features['Strategy']== 'NTT', df_common_features["Target"], df_common_features['Max'])
  df_common_features['LTT'] = np.where(df_common_features['Strategy']== 'BTT', df_common_features["Target"], df_common_features['Max'])
  df_common_features['BOL'] = df_common_features['Min']

  tmp_df = df_common_features[df_common_features['Symbol'].isin(mypf_df[mypf_df['InPortfolio'] != 'NA'].Symbol.values)]
  print('qualified stocks: '+str(len(tmp_df['Symbol'].unique())))
  tmp_df1 = tmp_df[tmp_df['LatestQtr'] == 1]
  print('with latest results: '+str(len(tmp_df1['Symbol'].unique())))
  tmp_df1 = tmp_df1[tmp_df1['StarStock'] == 1]
  print('still star stocks: '+str(len(tmp_df1['Symbol'].unique())))
  tmp_df['Investment'] = tmp_df['AvgCost'] * tmp_df['Shares']
  tmp_df['Current'] = round(tmp_df['Close'] * tmp_df['Shares'],0)
  tmp_df['Previous'] = tmp_df['Prev_Close'] * tmp_df['Shares']
  tmp_df['EstimatedST'] = tmp_df['NTT'] * tmp_df['Shares']
  tmp_df['EstimatedLT'] = tmp_df['LTT'] * tmp_df['Shares']
  tmp_df['Current P/L'] = round((tmp_df['Current'] - tmp_df['Investment']),0)
  tmp_df['Today P/L%'] = round((tmp_df['Current'] - tmp_df['Previous'])*100/tmp_df['Previous'],2)
  tmp_df['Current P/L%'] = round((tmp_df['Current'] - tmp_df['Investment'])*100/tmp_df['Investment'],2)
  tmp_df['EstimatedST P/L%'] = round((tmp_df['EstimatedST'] - tmp_df['Investment'])*100/tmp_df['Investment'],2)
  tmp_df['EstimatedLT P/L%'] = round((tmp_df['EstimatedLT'] - tmp_df['Investment'])*100/tmp_df['Investment'],2)
  tmp_df['NTT%'] = round((tmp_df['NTT'] - tmp_df['Close'])*100/tmp_df['Close'],2)
  tmp_df['LTT%'] = round((tmp_df['LTT'] - tmp_df['Close'])*100/tmp_df['Close'],2)
  tmp_df['Gained%'] = round((tmp_df['Close'] - tmp_df['BOL'])*100/tmp_df['BOL'],2)
  investment = round(sum(tmp_df['AvgCost']*tmp_df['Shares']),0)
  current = round(sum(tmp_df['Close']*tmp_df['Shares']),0)
  tmp_df['InitAlloc%'] = round(tmp_df['Investment']*100/investment,2)
  tmp_df['CurrAlloc%'] = round(tmp_df['Current']*100/current,2)
  tmp_df['FTT'] = tmp_df['LTT']
  tmp_df.loc[tmp_df['Strategy'] == 'NTT', 'FTT'] = tmp_df['NTT']
  tmp_df['FTT%'] = tmp_df['LTT%']
  tmp_df.loc[tmp_df['Strategy'] == 'NTT', 'FTT%'] = tmp_df['NTT%']
  tmp_df['FTT Amt'] = round(tmp_df['FTT%'] * tmp_df['Current']/100,0)
  tmp_df['OTT%'] = round((tmp_df['FTT'] - tmp_df['AvgCost'])*100/tmp_df['AvgCost'],2)
  tmp_df['RRR Ind'] = round(tmp_df['Current P/L']/tmp_df['FTT Amt'],2)
  tmp_df['Risk Ind'] = round(tmp_df['Current P/L%']*tmp_df['CurrAlloc%'],0)

  return tmp_df

# function to print portfolio features
def print_portfolio_stats(df_portfolio_features, myinvmt_df):
  from pyxirr import xirr

  total_booked_amt, reserve_amt, cy_booked_amt, py_booked_amt = get_amt()

  dates = myinvmt_df['Date'].values
  dates = np.append(dates, datetime.date.today().strftime('%d-%b-%y'))
  investment = myinvmt_df['Investment'].values
  dates= pd.to_datetime(dates)

  current = round(sum(df_portfolio_features['Close']*df_portfolio_features['Shares']),0) + reserve_amt
  investment_xirr = np.append(investment, current)
  cagr = round(xirr(pd.DataFrame({"dates": dates, "amounts": investment_xirr}))*100,2)

  investment = -sum(investment)
  invested = round(sum(df_portfolio_features['AvgCost']*df_portfolio_features['Shares']),0) + reserve_amt
  previous = round(sum(df_portfolio_features['Prev_Close']*df_portfolio_features['Shares']),0) + reserve_amt
  cy_invested = investment + py_booked_amt

  today_pnl_amount = current-previous
  today_pnl_percentage = round((current-previous)*100/previous,2)

  curr_pnl_amount = current-invested
  curr_pnl_percentage = round((curr_pnl_amount)*100/(cy_invested),2)

  cy_pnl_amount = cy_booked_amt + curr_pnl_amount
  cy_pnl_percentage = round((cy_pnl_amount)*100/cy_invested,2)

  overall_pnl_amount = total_booked_amt + curr_pnl_amount
  overall_pnl_percentage = round((overall_pnl_amount)*100/investment,2)

  estimate_st = round(sum(df_portfolio_features['FTT']*df_portfolio_features['Shares']),0)  + reserve_amt
  est_st_pnl_amount = estimate_st-current
  est_st_pnl_percentage = round((est_st_pnl_amount)*100/current,2)

  estimate_lt = round(sum(df_portfolio_features['LTT']*df_portfolio_features['Shares']),0)  + reserve_amt
  est_lt_pnl_amount = estimate_lt-current
  est_lt_pnl_percentage = round((est_lt_pnl_amount)*100/current,2)

  total_profit = round(sum(df_portfolio_features[df_portfolio_features['Current P/L%'] > 0]['Current']) - sum(df_portfolio_features[df_portfolio_features['Current P/L%'] > 0]['Investment']),0)
  total_loss = round(sum(df_portfolio_features[df_portfolio_features['Current P/L%'] < 0]['Current']) - sum(df_portfolio_features[df_portfolio_features['Current P/L%'] < 0]['Investment']),0)

  cy_booked_percentage = round((cy_booked_amt)*100/current,2)
  py_booked_percentage = round((py_booked_amt)*100/investment,2)
  total_booked_percentage = round((total_booked_amt)*100/investment,2)

  print('-------------------')
  print('Initial Investment: ', format_amt(investment))
  print('CY Investment: ', format_amt(cy_invested))
  print('Reserve: ', format_amt(reserve_amt))
  print('Current: ',  format_amt(current))
  print('-------------------')
  print('Today PnL: '+ '{} ({}%)'.format(format_amt(today_pnl_amount), today_pnl_percentage))
  print('Current PnL: '+ '{} ({}%)'.format(format_amt(curr_pnl_amount), curr_pnl_percentage))
  print('CY Booked + Current PnL: '+ '{} ({}%)'.format(format_amt(cy_pnl_amount), cy_pnl_percentage))
  print('-------------------')
  print('Total profit: ', format_amt(total_profit))
  print('Total loss: ', format_amt(total_loss))
  print('-------------------')
  print('Total Booked + Current PnL: '+ '{} ({}%)'.format(format_amt(overall_pnl_amount), overall_pnl_percentage))
  print('Total Booked PnL: '+ '{} ({}%)'.format(format_amt(total_booked_amt), total_booked_percentage))
  print('Curr Year Booked PnL: '+ '{} ({}%)'.format(format_amt(cy_booked_amt), cy_booked_percentage))
  print('Prev Year Booked PnL: '+ '{} ({}%)'.format(format_amt(py_booked_amt), py_booked_percentage))
  print('===================')
  print('Est FTT: ',  format_amt(estimate_st))
  print('Est FTT PnL: '+ '{} ({}%)'.format(format_amt(est_st_pnl_amount), est_st_pnl_percentage))

  print('===================')
  print('Deployed: ', format_amt(investment))

  print('Current: ', format_amt(current))

  print('CAGR/XIRR %: '+'{}%'.format(cagr))

In [8]:
# get start and end date
start_date, end_date = get_start_end_date()

# get portfolio and prospects data
mypfs_df = get_mypfs_df()
mypps_df = get_mypps_df()
myinvmt_df = get_myinvmt_df()

# merge above datasets
mypf_df = pd.merge(mypfs_df, mypps_df, on="Symbol")

# seggregate dm and sv portfolio
dm_pf = mypf_df[mypf_df['InPortfolio'] == 'DM']
sv_pf = mypf_df[mypf_df['InPortfolio'] == 'SV']

# build portfolio stock dataframe
dm_stocks = get_stock_ids(dm_pf)
sv_stocks = get_stock_ids(sv_pf)
df_stocks = pd.concat([dm_pf,sv_pf], ignore_index = True)

# arrange common and diff stock features
common_cols = ['Symbol', 'Target', 'Criteria', 'Strategy', 'CumlRnk', 'LatestQtr', 'StarStock', 'Conviction', 'Category', 'InFolio', 'XIRR', 'MBQ']
diff_cols = ['Symbol', 'AvgCost', 'Shares']
df_stocks = arrange_features(df_stocks, common_cols, diff_cols)

# get common features
stock_ids = df_stocks['Symbol'].values
df_common_features = get_common_features(stock_ids, df_stocks)

df_common_features.reset_index(drop=True, inplace=True)
df_common_features.drop(['Date'], axis=1, inplace=True)
# get and print portfolio features
df_portfolio_features = get_portfolio_features(df_common_features)

print_portfolio_stats(df_portfolio_features, myinvmt_df)

df = df_portfolio_features
#plot_pie_chart(df, 'CapType', 'Current')
list_ox40n = list(df[df['MBQ'].str.contains('OX40N', na=False)]['Symbol'].values)

Run date time (IST): 2026-03-13 10:49:54
-------------------
qualified stocks: 86
with latest results: 26
still star stocks: 15

-------------------
Initial Investment:  1.36 C
CY Investment:  1.62 C
Reserve:  66.25 K
Current:  1.34 C
-------------------
Today PnL: -1.71 L (-1.26%)
Current PnL: -42.93 L (-26.42%)
CY Booked + Current PnL: -27.25 L (-16.77%)
-------------------
Total profit:  99.35 K
Total loss:  -43.93 L
-------------------
Total Booked + Current PnL: -27.34 K (-0.2%)
Total Booked PnL: 42.66 L (31.48%)
Curr Year Booked PnL: 15.68 L (11.7%)
Prev Year Booked PnL: 26.98 L (19.91%)
===================
Est FTT:  2.47 C
Est FTT PnL: 1.13 C (84.55%)
===================
Deployed:  1.36 C
Current:  1.34 C
CAGR/XIRR %: -0.56%

In [9]:
# top 5 near their targets
cols = ['Symbol', 'Today P/L%', 'Current P/L%', 'FTT%', 'OTT%', 'FTT Amt', 'Current P/L', 'Current', 'FTT', 'Dev%_PE', 'RSI_14','Conviction', 'Spread%',  'CumlRnk', 'RRR Ind', 'CurrAlloc%', 'Gained%', 'Criteria', 'Strategy', 'Category']
df_tmp = df_portfolio_features[~df_portfolio_features['Symbol'].isin(['ENRIN','BLUSPRING','DIGITIDE'])]
df_tmp = df_tmp.sort_values(by = 'FTT Amt', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
19,COALINDIA,-0.88,14.58,2.70,17.67,4655.0,21942.0,172402.0,478.51,37.73,67.0,L-LC,12.88,185.0,4.71,1.29,33.88,XY25,ATH,MINING
77,TTKPRESTIG,0.94,-24.12,31.91,0.09,24402.0,-24306.0,76471.0,770.00,77.59,61.0,M-SC,15.05,250.0,-1.00,0.57,29.21,OX40N,NTT,DURABLES
50,MASFIN,-1.05,-7.88,31.97,21.57,28855.0,-7725.0,90255.0,397.04,-20.51,37.0,H-SC,3.60,167.0,-0.27,0.68,25.21,XR,ATH,FINANCE
37,ICICIGI,-0.45,-2.16,21.98,19.34,43033.0,-4327.0,195782.0,2252.93,-17.63,40.0,X-MC,1.89,66.0,-0.10,1.47,10.79,X40,ATH,INSURANCE
78,UNITDSPR,-0.53,-0.37,21.21,20.77,49480.0,-860.0,233284.0,1644.00,-11.71,46.0,X-MC,1.27,64.0,-0.02,1.75,6.32,X40N,NTT,BREWERIES

In [10]:
# top 5 today
df_tmp = df_portfolio_features.sort_values(by = 'Today P/L%', ascending=False)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
1,ABB,2.05,17.59,23.79,45.57,73186.0,46013.0,307632.0,7934.0,-24.43,69.0,H-MC,10.55,125.0,0.63,2.31,36.61,AR,NTT,ELECTRICAL
35,HINDUNILVR,1.63,-15.51,34.54,13.67,75014.0,-39883.0,217180.0,2922.0,-37.23,33.0,X-LC,5.65,9.0,-0.53,1.63,1.87,XY25,NTT,FMCG
77,TTKPRESTIG,0.94,-24.12,31.91,0.09,24402.0,-24306.0,76471.0,770.0,77.59,61.0,M-SC,15.05,250.0,-1.00,0.57,29.21,OX40N,NTT,DURABLES
20,COFFEEDAY,0.94,-56.56,211.41,35.27,104278.0,-64224.0,49325.0,80.0,-65.79,27.0,L-SC,19.76,266.0,-0.62,0.37,10.12,XR,NTT,HOTELS
69,SURYODAY,0.93,-27.38,69.41,23.03,90268.0,-49021.0,130050.0,216.0,42.54,47.0,H-SC,7.69,166.0,-0.54,0.98,29.04,XR,NTT,BANKS

In [11]:
# bottom 5 today
df_tmp = df_portfolio_features.sort_values(by = 'Today P/L%', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
55,RAJESHEXPO,-3.81,-78.83,372.63,0.07,108227.0,-108133.0,29044.0,518.00,964.39,21.0,L-SC,22.54,268.0,-1.00,0.22,0.38,OX40N,NTT,JEWELLERY
7,ATULAUTO,-3.72,-29.46,106.36,45.57,147904.0,-58072.0,139060.0,844.00,2997.30,35.0,M-SC,4.05,248.0,-0.39,1.04,5.24,XY24,NTT,AUTO
82,VOLTAS,-3.68,9.21,32.95,45.20,68997.0,17658.0,209400.0,1856.00,25.07,40.0,X-MC,8.76,79.0,0.26,1.57,16.63,XY25,NTT,AC
75,TMPV,-3.59,-28.77,91.75,36.58,232539.0,-102392.0,253449.0,600.00,-84.72,29.0,X-LC,2.05,4.0,-0.44,1.90,0.00,XY24,NTT,AUTO
27,FINCABLES,-3.52,9.30,90.21,107.91,145582.0,13737.0,161381.0,1641.55,-1.57,51.0,M-SC,7.73,220.0,0.09,1.21,21.41,OX40N,ATH,CABLES

In [12]:
# top 5 to exit based on CumlRnk
df_tmp = df_portfolio_features[~df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])]
df_tmp = df_tmp[(df_tmp['Current P/L%'] > -1) & (df_tmp['Current P/L%'] < 1)].sort_values(by = 'CumlRnk', ascending=False)
df_tmp[cols].head()

Empty DataFrame
Columns: [Symbol, Today P/L%, Current P/L%, FTT%, OTT%, FTT Amt, Current P/L, Current, FTT, Dev%_PE, RSI_14, Conviction, Spread%, CumlRnk, RRR Ind, CurrAlloc%, Gained%, Criteria, Strategy, Category]
Index: []

In [13]:
# OX40N stocks to exit
df_tmp = df_portfolio_features[(df_portfolio_features['Symbol'].isin(list_ox40n))].sort_values(by = 'Current P/L%', ascending=False)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
27,FINCABLES,-3.52,9.30,90.21,107.91,145582.0,13737.0,161381.0,1641.55,-1.57,51.0,M-SC,7.73,220.0,0.09,1.21,21.41,OX40N,ATH,CABLES
77,TTKPRESTIG,0.94,-24.12,31.91,0.09,24402.0,-24306.0,76471.0,770.00,77.59,61.0,M-SC,15.05,250.0,-1.00,0.57,29.21,OX40N,NTT,DURABLES
66,SIS,-2.19,-35.30,87.43,21.26,62804.0,-39198.0,71834.0,528.00,1679.79,32.0,H-SC,11.48,168.0,-0.62,0.54,0.00,OX40N,NTT,MISC
48,KANSAINER,0.35,-37.02,80.16,13.47,136150.0,-99819.0,169848.0,340.00,-45.81,31.0,H-SC,17.02,162.0,-0.73,1.27,1.83,XY24,NTT,PAINTS
70,SYMPHONY,-1.03,-38.22,61.81,-0.03,65352.0,-65411.0,105730.0,1306.00,-50.45,44.0,M-SC,14.21,205.0,-1.00,0.79,6.92,OX40N,NTT,DURABLES

In [14]:
# top 5 to book for rotation
df_tmp = df_portfolio_features[(df_portfolio_features['Current P/L%'] > 20) ].sort_values(by = 'CumlRnk', ascending=False)
df_tmp[cols].head()

Empty DataFrame
Columns: [Symbol, Today P/L%, Current P/L%, FTT%, OTT%, FTT Amt, Current P/L, Current, FTT, Dev%_PE, RSI_14, Conviction, Spread%, CumlRnk, RRR Ind, CurrAlloc%, Gained%, Criteria, Strategy, Category]
Index: []

In [15]:
# top 5 to monitor for exit
df_tmp = df_portfolio_features[~df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])]
df_tmp = df_tmp[(df_tmp['Current P/L%'] > 0) ].sort_values(by = 'Dev%_PE', ascending=False)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
19,COALINDIA,-0.88,14.58,2.70,17.67,4655.0,21942.0,172402.0,478.51,37.73,67.0,L-LC,12.88,185.0,4.71,1.29,33.88,XY25,ATH,MINING
27,FINCABLES,-3.52,9.30,90.21,107.91,145582.0,13737.0,161381.0,1641.55,-1.57,51.0,M-SC,7.73,220.0,0.09,1.21,21.41,OX40N,ATH,CABLES
1,ABB,2.05,17.59,23.79,45.57,73186.0,46013.0,307632.0,7934.00,-24.43,69.0,H-MC,10.55,125.0,0.63,2.31,36.61,AR,NTT,ELECTRICAL

In [16]:
# top 5 to book for rotation from weak conviction
df_tmp = df_portfolio_features[~df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])]
df_tmp = df_tmp[~df_tmp['Criteria'].isin(['XY25','XY24','X40', 'X40N'])].sort_values(by = 'RRR Ind', ascending=False)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
1,ABB,2.05,17.59,23.79,45.57,73186.0,46013.0,307632.0,7934.00,-24.43,69.0,H-MC,10.55,125.0,0.63,2.31,36.61,AR,NTT,ELECTRICAL
27,FINCABLES,-3.52,9.30,90.21,107.91,145582.0,13737.0,161381.0,1641.55,-1.57,51.0,M-SC,7.73,220.0,0.09,1.21,21.41,OX40N,ATH,CABLES
40,INDIAMART,0.36,-9.42,128.23,106.72,143250.0,-11623.0,111713.0,4810.62,-59.18,42.0,H-SC,9.61,140.0,-0.08,0.84,11.75,AR,ATH,MISC
85,ZYDUSLIFE,-1.12,-4.39,41.86,35.63,83875.0,-9204.0,200370.0,1286.17,-16.67,49.0,H-MC,5.03,120.0,-0.11,1.50,11.55,AR,ATH,PHARMA
84,WIPRO,-0.73,-17.54,108.91,72.27,152172.0,-29725.0,139723.0,420.00,-25.49,34.0,M-LC,15.07,98.0,-0.20,1.05,2.89,XR,NTT,IT

In [17]:
# top 5 to accumulate based on lowest RSI_14
df_tmp = df_portfolio_features[df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])].sort_values(by = 'RSI_14', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
58,RELAXO,-1.26,-61.30,293.51,52.31,164906.0,-88976.0,56184.0,1176.00,-58.76,17.0,X-SC,20.16,92.0,-0.54,0.42,0.00,X40N,NTT,FOOTWEAR
3,ACC,-1.47,-36.79,176.57,74.81,299244.0,-98652.0,169476.0,3906.00,-55.22,19.0,X-SC,13.43,85.0,-0.33,1.27,0.00,XY24,BTT,CEMENT
12,BATAINDIA,-1.98,-54.86,199.51,35.20,115881.0,-70587.0,58083.0,2096.00,-23.90,19.0,X-SC,26.89,91.0,-0.61,0.44,0.00,X40,NTT,FOOTWEAR
8,AWL,-0.23,-39.48,175.96,67.02,379449.0,-140664.0,215645.0,485.00,-67.43,20.0,X-SC,23.70,81.0,-0.37,1.62,0.09,XY24,NTT,FMCG
73,TCS,-0.33,-28.54,77.11,26.57,255294.0,-132195.0,331078.0,4311.59,-39.36,20.0,X-LC,14.82,2.0,-0.52,2.48,0.00,X40,ATH,IT

In [18]:
# top 5 to accumulate based on Spread and CumlRnk
df_tmp = df_portfolio_features[df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])]
df_tmp = df_tmp[(df_tmp['CumlRnk'] < 100)].sort_values(by = 'Spread%', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
78,UNITDSPR,-0.53,-0.37,21.21,20.77,49480.0,-860.0,233284.0,1644.00,-11.71,46.0,X-MC,1.27,64.0,-0.02,1.75,6.32,X40N,NTT,BREWERIES
37,ICICIGI,-0.45,-2.16,21.98,19.34,43033.0,-4327.0,195782.0,2252.93,-17.63,40.0,X-MC,1.89,66.0,-0.10,1.47,10.79,X40,ATH,INSURANCE
22,DABUR,0.08,-10.12,59.89,43.70,133527.0,-25114.0,222954.0,735.00,-18.36,31.0,X-MC,1.94,70.0,-0.19,1.67,3.40,XY24,BTT,FMCG
75,TMPV,-3.59,-28.77,91.75,36.58,232539.0,-102392.0,253449.0,600.00,-84.72,29.0,X-LC,2.05,4.0,-0.44,1.90,0.00,XY24,NTT,AUTO
59,RELIANCE,0.20,-10.45,39.93,25.30,71856.0,-21008.0,179955.0,1952.00,-12.73,46.0,X-LC,2.92,21.0,-0.29,1.35,20.15,XY25,BTT,REFINERIES

In [19]:
# top 5 to accumulate based on lowest Gained%
df_tmp = df_portfolio_features[df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])].sort_values(by = 'Gained%', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
3,ACC,-1.47,-36.79,176.57,74.81,299244.0,-98652.0,169476.0,3906.00,-55.22,19.0,X-SC,13.43,85.0,-0.33,1.27,0.0,XY24,BTT,CEMENT
12,BATAINDIA,-1.98,-54.86,199.51,35.20,115881.0,-70587.0,58083.0,2096.00,-23.90,19.0,X-SC,26.89,91.0,-0.61,0.44,0.0,X40,NTT,FOOTWEAR
10,BAJAJHLDNG,-0.91,-13.27,48.98,29.22,80768.0,-25225.0,164900.0,14451.52,-19.77,23.0,X-LC,12.73,28.0,-0.31,1.24,0.0,X40,ATH,FINANCE
9,BAJAJHFL,-1.11,-26.08,119.34,62.13,240860.0,-71219.0,201827.0,181.50,-39.10,29.0,X-MC,18.65,60.0,-0.30,1.51,0.0,X40N,ATH,FINANCE
21,COLPAL,-0.24,-25.16,89.07,41.51,175566.0,-66255.0,197110.0,3726.84,-9.44,31.0,X-MC,4.13,62.0,-0.38,1.48,0.0,XY25,ATH,FMCG

In [20]:
# top 5 to accumulate based on lowest CurrAlloc%
df_tmp = df_portfolio_features[df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])].sort_values(by = 'CurrAlloc%', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
58,RELAXO,-1.26,-61.30,293.51,52.31,164906.0,-88976.0,56184.0,1176.00,-58.76,17.0,X-SC,20.16,92.0,-0.54,0.42,0.00,X40N,NTT,FOOTWEAR
12,BATAINDIA,-1.98,-54.86,199.51,35.20,115881.0,-70587.0,58083.0,2096.00,-23.90,19.0,X-SC,26.89,91.0,-0.61,0.44,0.00,X40,NTT,FOOTWEAR
54,QUESS,-1.95,-23.50,127.31,73.90,104012.0,-25093.0,81700.0,424.00,-58.68,38.0,X-SC,18.43,80.0,-0.24,0.61,0.78,XY24,NTT,MISC
36,HONAUT,-0.74,-21.29,92.25,51.31,140012.0,-41063.0,151775.0,58357.33,-34.59,40.0,X-SC,13.91,90.0,-0.29,1.14,2.21,X40N,ATH,ELECTRICAL
2,ABBOTINDIA,-0.88,-11.27,33.06,18.07,52466.0,-20155.0,158700.0,35195.00,-24.45,43.0,X-MC,11.09,58.0,-0.38,1.19,0.61,X40,ATH,PHARMA

In [21]:
# top 5 to accumulate based on CumlRnk
df_tmp = df_portfolio_features.sort_values(by = 'CumlRnk', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
45,ITC,-0.03,-19.93,48.68,19.06,132597.0,-67782.0,272384.0,452.00,-55.92,33.0,X-LC,17.23,1.0,-0.51,2.04,0.00,X40,NTT,FMCG
73,TCS,-0.33,-28.54,77.11,26.57,255294.0,-132195.0,331078.0,4311.59,-39.36,20.0,X-LC,14.82,2.0,-0.52,2.48,0.00,X40,ATH,IT
43,INFY,0.05,-13.79,55.72,34.24,150301.0,-43145.0,269743.0,1972.00,-32.15,25.0,X-LC,13.09,3.0,-0.29,2.02,0.05,X40,NTT,IT
75,TMPV,-3.59,-28.77,91.75,36.58,232539.0,-102392.0,253449.0,600.00,-84.72,29.0,X-LC,2.05,4.0,-0.44,1.90,0.00,XY24,NTT,AUTO
34,HCLTECH,-0.35,-12.18,41.00,23.83,87112.0,-29456.0,212468.0,1908.19,-7.78,29.0,X-LC,9.88,8.0,-0.34,1.59,1.94,X40,ATH,IT

In [22]:
# top 5 for average up
df_tmp = df_portfolio_features[(df_portfolio_features['Dev%_200'] > 5)].sort_values(by = 'CurrAlloc%', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
67,SONACOMS,-1.76,-13.28,60.39,39.09,52979.0,-13431.0,87728.0,804.02,-31.27,44.0,M-MC,9.51,193.0,-0.25,0.66,24.11,AR,ATH,AUTO
19,COALINDIA,-0.88,14.58,2.70,17.67,4655.0,21942.0,172402.0,478.51,37.73,67.0,L-LC,12.88,185.0,4.71,1.29,33.88,XY25,ATH,MINING
11,BANDHANBNK,-2.39,-16.41,130.20,92.42,303155.0,-45721.0,232838.0,400.00,99.71,51.0,H-SC,9.66,174.0,-0.15,1.75,28.26,XY24,NTT,BANKS
1,ABB,2.05,17.59,23.79,45.57,73186.0,46013.0,307632.0,7934.00,-24.43,69.0,H-MC,10.55,125.0,0.63,2.31,36.61,AR,NTT,ELECTRICAL

In [23]:
# top 5 RSP
df_tmp = df_portfolio_features.sort_values(by = 'RSP', ascending=False)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
19,COALINDIA,-0.88,14.58,2.70,17.67,4655.0,21942.0,172402.0,478.51,37.73,67.0,L-LC,12.88,185.0,4.71,1.29,33.88,XY25,ATH,MINING
1,ABB,2.05,17.59,23.79,45.57,73186.0,46013.0,307632.0,7934.00,-24.43,69.0,H-MC,10.55,125.0,0.63,2.31,36.61,AR,NTT,ELECTRICAL
26,EASEMYTRIP,-1.24,-60.54,269.23,45.70,187842.0,-107045.0,69770.0,26.40,-27.55,41.0,M-SC,18.24,204.0,-0.57,0.52,14.95,XY24,NTT,TRAVEL
31,HAPPSTMNDS,-2.33,-50.13,270.64,84.85,172993.0,-64245.0,63920.0,1480.71,-40.67,57.0,H-SC,28.04,152.0,-0.37,0.48,18.37,AR,ATH,IT
27,FINCABLES,-3.52,9.30,90.21,107.91,145582.0,13737.0,161381.0,1641.55,-1.57,51.0,M-SC,7.73,220.0,0.09,1.21,21.41,OX40N,ATH,CABLES

In [24]:
# Top N allocation
df_tmp = df_portfolio_features.sort_values(by = 'CurrAlloc%', ascending=False)
top_n_values = [10, 25, 50]

sum_df = pd.DataFrame({
    'Top_N': top_n_values,
    'Sum_Alloc%': [df_tmp['CurrAlloc%'].head(n).sum() for n in top_n_values]
})

sum_df

   Top_N  Sum_Alloc%
0     10       20.40
1     25       45.26
2     50       77.80

In [25]:
# market-cap-wise allocation
df_tmp = df_portfolio_features[cols]
df_tmp.groupby(df_tmp['Conviction'].str[-2:])['CurrAlloc%'].sum().sort_values(ascending=False)

Conviction
SC    44.63
MC    30.37
LC    25.02
Name: CurrAlloc%, dtype: float64

In [26]:
# criteria-wise allocation
df_portfolio_features.groupby('Criteria')['CurrAlloc%'].sum().sort_values(ascending=False)

Criteria
XY24     27.18
X40      23.75
X40N     15.11
AR        9.31
XY25      8.70
XR        8.26
OX40N     6.95
SR        0.76
Name: CurrAlloc%, dtype: float64

In [27]:
# conviction-wise allocation
df_portfolio_features.groupby('Conviction')['CurrAlloc%'].sum().sort_values(ascending=False)

Conviction
X-MC    22.88
H-SC    21.72
X-LC    21.45
X-SC    12.09
M-SC    10.23
H-MC     5.10
M-MC     2.04
L-LC     1.29
H-LC     1.23
M-LC     1.05
L-SC     0.59
L-MC     0.35
Name: CurrAlloc%, dtype: float64

In [28]:
# sector-wise stats
df_tmp = df_portfolio_features.groupby('Category')[['CurrAlloc%', 'Current', 'Current P/L', 'FTT Amt']].sum().sort_values(by=['Current', 'Current P/L'], ascending=False)
df_tmp['Current P/L%'] = round(df_tmp['Current P/L'] * 100 / df_tmp['Current'], 2)
df_tmp['FTT%'] = round(df_tmp['FTT Amt'] * 100 / df_tmp['Current'], 2)
cols = ['CurrAlloc%', 'Current P/L%', 'FTT%']
df_tmp[cols].sort_values(by=['CurrAlloc%'], ascending=False)

               CurrAlloc%  Current P/L%    FTT%
Category
FMCG                15.22        -23.10   66.80
FINANCE             12.84        -25.54   76.70
IT                  11.75        -43.70  116.82
MISC                 7.01        -43.56  105.92
ELECTRICAL           6.74         -7.90   49.21
PAINTS               5.17        -42.95   67.77
INSURANCE            4.76         -6.89   43.47
PHARMA               4.15         -6.16   39.57
AUTO                 3.60        -36.21   90.25
BANKS                3.08        -30.71  109.91
AC                   2.11        -13.49   44.26
HEALTHCARE           1.98        -35.55   70.92
DURABLES             1.94        -49.17   85.46
FOOTWEAR             1.86        -78.02  149.40
TRAVEL               1.81        -85.01  177.65
BREWERIES            1.75         -0.37   21.21
APPARELS             1.60        -25.99   68.97
REALTY               1.45        -15.01   33.91
CERAMICS             1.35        -70.60  122.43
REFINERIES           1.35        -11.67   39.93
MINING               1.29         12.73    2.70
CEMENT               1.27        -58.21  176.57
CABLES               1.21          8.51   90.21
JEWELLERY            1.12       -115.10  189.83
ENGINEERING          1.10        -64.93  140.37
CHEMICALS            0.94       -112.06  285.07
ENTERTAINMENT        0.77        -88.62  201.11
TEXTILES             0.43        -62.32  108.60
HOTELS               0.37       -130.21  211.41

In [29]:
# money to be made criteria-wise
df_portfolio_features.groupby('Criteria')['FTT Amt'].agg(['sum', 'count']).sort_values(by='sum', ascending=False)

                sum  count
Criteria
XY24      3972453.0     21
X40       1706788.0     15
XR        1392797.0     12
AR        1331428.0     10
X40N      1286175.0     10
OX40N      864786.0     10
XY25       456815.0      6
SR         317844.0      2

In [30]:
# money to be made conviction-wise
df_portfolio_features.groupby('Conviction')['FTT Amt'].agg(['sum', 'count']).sort_values(by='sum', ascending=False)

                  sum  count
Conviction
H-SC        3898333.0     24
X-MC        1685169.0     15
X-LC        1614528.0     12
X-SC        1570254.0     10
M-SC        1552810.0     14
H-MC         398741.0      3
L-SC         212505.0      2
M-LC         152172.0      1
M-MC         113706.0      2
H-LC          69916.0      1
L-MC          56297.0      1
L-LC           4655.0      1

In [31]:
# money to be made criteria and conviction-wise
df_portfolio_features.groupby(['Conviction', 'Criteria'])['FTT Amt'].agg(['sum', 'count']).sort_values(by='sum', ascending=False)

                           sum  count
Conviction Criteria
H-SC       XY24      1329851.0      6
           AR         973950.0      5
M-SC       XY24       915367.0      6
H-SC       XR         886525.0      7
X-SC       XY24       844396.0      4
X-LC       X40        834025.0      6
X-MC       X40        663469.0      7
X-SC       X40N       516564.0      4
X-MC       X40N       515976.0      4
H-SC       OX40N      390163.0      4
X-LC       XY24       379998.0      2
M-SC       OX40N      366396.0      5
H-SC       SR         317844.0      2
X-MC       XY24       261161.0      2
X-LC       X40N       253635.0      2
X-MC       XY25       244563.0      2
H-MC       XY24       241680.0      1
X-SC       X40        209294.0      2
M-SC       XR         193525.0      2
H-MC       AR         157061.0      2
M-LC       XR         152172.0      1
X-LC       XY25       146870.0      2
L-SC       OX40N      108227.0      1
           XR         104278.0      1
M-SC       AR          77522.0      1
H-LC       AR          69916.0      1
M-MC       XY25        60727.0      1
L-MC       XR          56297.0      1
M-MC       AR          52979.0      1
L-LC       XY25         4655.0      1

In [32]:
# notebook execution time

end_time = time.time()
execution_time = round(end_time - start_time, 0)
print(f"Notebook execution time: {execution_time} seconds")

Notebook execution time: 28.0 seconds