<a href="https://colab.research.google.com/github/ankit-rathi/Quantvesting_v2/blob/main/myStocks_Portfolio_Analysis.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
'''
!pip install pandas==2.2.2 -qq
!pip install pyxirr -qq
!pip install ta -qq
!pip install yfinance==0.2.59 -qq
'''

'\n!pip install pandas==2.2.2 -qq\n!pip install pyxirr -qq\n!pip install ta -qq\n!pip install yfinance==0.2.59 -qq\n'

In [2]:
# import libraries

import numpy as np
import pandas as pd
import datetime
import warnings
warnings.filterwarnings('ignore')
import yfinance as yfin
import ta
import matplotlib.pyplot as plt
import requests

In [3]:
# notebook start time
import time
import datetime
import pytz

start_time = time.time()

# function to print date timestamp
def print_date_time():
  tz_NY = pytz.timezone('Asia/Kolkata')
  datetime_NY = datetime.datetime.now(tz_NY)
  print("Run date time (IST):", datetime_NY.strftime("%Y-%m-%d %H:%M:%S"))

In [4]:
# function to get booked and reserved amount
def get_amt():
  # fetch the JSON data from the URL
  url = "https://raw.githubusercontent.com/ankit-rathi/Tradevesting_v1/main/data/myPortfolioAmts.json"
  response = requests.get(url)
  pf_amts = response.json()  # parse the JSON data

  # extract values from the JSON
  py_booked_amt_dm = pf_amts["py_booked_amt_dm"]
  py_booked_amt_sv = pf_amts["py_booked_amt_sv"]
  cy_booked_amt_dm = pf_amts["cy_booked_amt_dm"]
  cy_booked_amt_sv = pf_amts["cy_booked_amt_sv"]
  reserve_amt_dm = pf_amts["reserve_amt_dm"]
  reserve_amt_sv = pf_amts["reserve_amt_sv"]

  # perform calculations
  py_booked_amt = py_booked_amt_dm + py_booked_amt_sv
  cy_booked_amt = cy_booked_amt_dm + cy_booked_amt_sv
  reserve_amt = reserve_amt_dm + reserve_amt_sv
  total_booked_amt = py_booked_amt + cy_booked_amt

  return total_booked_amt, reserve_amt, cy_booked_amt, py_booked_amt

gen_output = 0

In [5]:
# function to format the amount
def format_amt(number):
    abs_number = abs(number)

    if abs_number >= 1_00_00_000:  # Crores
        formatted_amt = f"{number / 1_00_00_000:.2f} C"
    elif abs_number >= 1_00_000:  # Lakhs
        formatted_amt = f"{number / 1_00_000:.2f} L"
    elif abs_number >= 1_000:  # Thousands
        formatted_amt = f"{number / 1_000:.2f} K"
    else:
        formatted_amt = f"{number:.2f}"

    return formatted_amt

# function to set start and end date
def get_start_end_date():
  start_date = (datetime.date.today() + datetime.timedelta(days=-365)).strftime('%Y-%m-%d')
  end_date = (datetime.date.today() + datetime.timedelta(days=1)).strftime('%Y-%m-%d')
  return start_date, end_date

# function to fetch my portfolio csv
def get_mypfs_df():
  mypfs_df = pd.read_csv('https://raw.githubusercontent.com/ankit-rathi/Tradevesting_v1/main/data/myPortfolioStocks.csv')
  return mypfs_df

# function to fetch my prospects csv
def get_mypps_df():
  mypps_df = pd.read_csv('https://raw.githubusercontent.com/ankit-rathi/Tradevesting_v1/main/data/myProspectsScrips.csv')
  return mypps_df

# function to fetch screener data
def get_myscreen_df():
  myscreen_df = pd.read_csv('https://raw.githubusercontent.com/ankit-rathi/Tradevesting_v1/main/data/myScreenerDB.csv')
  return myscreen_df

# function to fetch momentum data
def get_myinvmt_df():
  myinvmt_df = pd.read_csv('https://raw.githubusercontent.com/ankit-rathi/Tradevesting_v1/main/data/myInvestments.csv')
  return myinvmt_df

# function to get the stock ids
def get_stock_ids(df_pf):
  stock_n100 = df_pf['Symbol'].unique()

  exclude = ['CADILAHC','MMTC', 'MASFIN']

  stock_ids = df_pf[~df_pf['Symbol'].isin(exclude) ]['Symbol'].unique()

  #mypf = mypf[mypf.Forecast.notnull()]
  #stock_ids = mypf['Symbol'].unique()

  #stock_ids.sort()
  return stock_ids

# get features from screener data
def get_screener_features():
  myscreen_df = get_myscreen_df()
  cols = ['Symbol', 'EPS', 'MedPE', 'ROCE%', 'ROE%', 'CapType']
  return myscreen_df[cols]

# get relative strength
def get_relative_strength(stock_list):

    # Dictionary to store stock tickers and their corresponding percentage price change
    stock_changes = {}

    # Loop through each stock and fetch its price data
    for stock in stock_list:
        try:
            # Download the stock data for the given date range
            stock_data = yfin.Ticker(stock + '.NS').history(period='1mo', interval='1d')[map(str.title, ['open', 'close', 'low', 'high', 'volume'])]

            # Calculate the percentage change for the stock
            if len(stock_data) > 0:
                start_price = stock_data['Close'].iloc[0]
                end_price = stock_data['Close'].iloc[-1]
                percent_change = round(((end_price - start_price) / start_price) * 100, 2)
                stock_changes[stock] = percent_change
            else:
                stock_changes[stock] = np.nan  # If no data is available, set to NaN

        except Exception as e:
            print(f"Error fetching data for {stock}: {e}")
            stock_changes[stock] = np.nan

    # Create a DataFrame with stock tickers and their percentage changes
    df = pd.DataFrame(list(stock_changes.items()), columns=['Symbol', 'Percent_Change'])

    # Drop any stocks with missing data (NaN values)
    df = df.dropna()

    # Calculate the percentile rank based on percentage change
    df['RSP'] = round(df['Percent_Change'].rank(pct=True) * 100, 2)
    cols = ['Symbol', 'RSP']
    df = df[cols]
    # Sort by percentile rank (optional)
    df = df.sort_values(by='RSP', ascending=False).reset_index(drop=True)

    return df

In [6]:
# function to get stock technicals
def stock_prec_dev(stock_symbol):
    #stock_symbol = 'ULTRACEMCO.NS'
    short_window = 20
    mid_window = 50
    long_window = 200
    moving_avg = 'SMA'

    start = datetime.datetime(*map(int, start_date.split('-')))
    end = datetime.datetime(*map(int, end_date.split('-')))

    stock_df = yfin.Ticker(stock_symbol + '.NS').history(period='max', interval='1d')[map(str.title, ['open', 'close', 'low', 'high', 'volume'])]

    stock_df['Max'] = round(max(stock_df['Close']),2)
    stock_df = stock_df[(stock_df.index <= end_date) & (stock_df.index >= start_date)]
    stock_df['200_SMA'] = round(stock_df['Close'].rolling(window = 200, min_periods = 1).mean(),0)
    stock_df['Dev%_200'] = round((stock_df['Close'] - stock_df['200_SMA'])*100/stock_df['200_SMA'],2)
    stock_df.dropna(axis = 0, inplace = True) # remove any null rows

    stock_df['20_SMA'] = stock_df['Close'].rolling(window=20).mean()
    stock_df['50_SMA'] = stock_df['Close'].rolling(window=50).mean()
    stock_df['Symbol'] = stock_symbol

    stock_df['Close'] = round(stock_df['Close'],2)
    stock_df['Min'] = round(min(stock_df['Close']),2)
    stock_df['RSI_14'] = ta.momentum.RSIIndicator(close=stock_df['Close'], window=14).rsi()
    stock_df['RSI_14'] = round(stock_df['RSI_14'],0)
    stock_df['Prev_Close'] = stock_df['Close'].shift(1)
    stock_df.drop(['Open', 'Low', 'High', 'Volume'], axis=1, inplace=True)
    stock_df = stock_df.tail(1)

    max_SMA = max(stock_df['20_SMA'].item(), stock_df['50_SMA'].item(), stock_df['200_SMA'].item())
    min_SMA = min(stock_df['20_SMA'].item(), stock_df['50_SMA'].item(), stock_df['200_SMA'].item())
    ABS_Spread = max_SMA - min_SMA
    stock_df['Spread%'] = round((ABS_Spread / stock_df['200_SMA'].item()) * 100,2)

    return stock_df

# function to compute stock attributes
def get_common_features(stock_ids, df_mypf):

  df_prec_dev = pd.DataFrame()
  df_tmp = get_screener_features()
  df_rs = get_relative_strength(stock_ids)

  for stock_id in stock_ids:
      tmp = stock_prec_dev(stock_id)
      tmp = tmp.reset_index()
      df_prec_dev = pd.concat([df_prec_dev, tmp], ignore_index = True)
  df_prec_dev = pd.merge(df_prec_dev, df_mypf, on= 'Symbol')
  df_prec_dev = pd.merge(df_prec_dev, df_tmp, on= 'Symbol', how='left')
  df_prec_dev = pd.merge(df_prec_dev, df_rs, on= 'Symbol', how='left')
  #print(df_prec_dev.columns)
  df_prec_dev['Curr_PE'] = round(df_prec_dev['Close']/df_prec_dev['EPS'],1)
  df_prec_dev['Dev%_PE'] = round((df_prec_dev['Curr_PE'] - df_prec_dev['MedPE'])*100/df_prec_dev['MedPE'],2)
  df_prec_dev['Conviction'] = df_prec_dev['Conviction'] + '-' + df_prec_dev['CapType']
  return df_prec_dev

# function to arrange stock features
def arrange_features(df_stocks, common_cols, diff_cols):
  df_stocks_common = df_stocks[common_cols].drop_duplicates()
  df_stocks_diff = df_stocks[diff_cols]
  df_stocks_diff['Investment'] = df_stocks_diff['AvgCost'] * df_stocks_diff['Shares']
  df_stocks_diff = df_stocks_diff.groupby(['Symbol'])[['Shares', 'Investment']].aggregate(['sum']).reset_index()
  df_stocks_diff.columns = ['Symbol', 'Shares', 'Investment']
  df_stocks_diff['AvgCost'] = round(df_stocks_diff['Investment']/df_stocks_diff['Shares'],2)
  df_stocks = pd.merge(df_stocks_diff, df_stocks_common, on='Symbol')
  return df_stocks

# plot fact distribution across dimension
def plot_pie_chart(df, dimension, fact):
  # grouping the data by category and calculating the sum of fact for each type
  grouped_data = df.groupby(dimension)[fact].sum()

  # sorting the grouped data in descending order
  grouped_data = grouped_data.sort_values(ascending=False)

  # creating a pie chart
  grouped_data.plot.pie(autopct='%1.1f%%', startangle=90, figsize=(6, 6))

  # adding a title and displaying the plot
  plt.title(f'{dimension} {fact} Distribution')
  plt.ylabel('')  # To hide the y-label
  plt.show()

In [7]:
# function to get portfolio features

def get_portfolio_features(df_common_features):

  print_date_time()
  print('-------------------')

  #df_common_features["Target"] = df_common_features["Target"].fillna(df_common_features["Max"])
  df_common_features['NTT'] = np.where(df_common_features['Strategy']== 'NTT', df_common_features["Target"], df_common_features['Max'])
  df_common_features['LTT'] = np.where(df_common_features['Strategy']== 'BTT', df_common_features["Target"], df_common_features['Max'])
  df_common_features['BOL'] = df_common_features['Min']

  tmp_df = df_common_features[df_common_features['Symbol'].isin(mypf_df[mypf_df['InPortfolio'] != 'NA'].Symbol.values)]
  print('qualified stocks: '+str(len(tmp_df['Symbol'].unique())))
  tmp_df1 = tmp_df[tmp_df['LatestQtr'] == 1]
  print('with latest results: '+str(len(tmp_df1['Symbol'].unique())))
  tmp_df1 = tmp_df1[tmp_df1['StarStock'] == 1]
  print('still star stocks: '+str(len(tmp_df1['Symbol'].unique())))
  tmp_df['Investment'] = tmp_df['AvgCost'] * tmp_df['Shares']
  tmp_df['Current'] = round(tmp_df['Close'] * tmp_df['Shares'],0)
  tmp_df['Previous'] = tmp_df['Prev_Close'] * tmp_df['Shares']
  tmp_df['EstimatedST'] = tmp_df['NTT'] * tmp_df['Shares']
  tmp_df['EstimatedLT'] = tmp_df['LTT'] * tmp_df['Shares']
  tmp_df['Current P/L'] = round((tmp_df['Current'] - tmp_df['Investment']),0)
  tmp_df['Today P/L%'] = round((tmp_df['Current'] - tmp_df['Previous'])*100/tmp_df['Previous'],2)
  tmp_df['Current P/L%'] = round((tmp_df['Current'] - tmp_df['Investment'])*100/tmp_df['Investment'],2)
  tmp_df['EstimatedST P/L%'] = round((tmp_df['EstimatedST'] - tmp_df['Investment'])*100/tmp_df['Investment'],2)
  tmp_df['EstimatedLT P/L%'] = round((tmp_df['EstimatedLT'] - tmp_df['Investment'])*100/tmp_df['Investment'],2)
  tmp_df['NTT%'] = round((tmp_df['NTT'] - tmp_df['Close'])*100/tmp_df['Close'],2)
  tmp_df['LTT%'] = round((tmp_df['LTT'] - tmp_df['Close'])*100/tmp_df['Close'],2)
  tmp_df['Gained%'] = round((tmp_df['Close'] - tmp_df['BOL'])*100/tmp_df['BOL'],2)
  investment = round(sum(tmp_df['AvgCost']*tmp_df['Shares']),0)
  current = round(sum(tmp_df['Close']*tmp_df['Shares']),0)
  tmp_df['InitAlloc%'] = round(tmp_df['Investment']*100/investment,2)
  tmp_df['CurrAlloc%'] = round(tmp_df['Current']*100/current,2)
  tmp_df['FTT'] = tmp_df['LTT']
  tmp_df.loc[tmp_df['Strategy'] == 'NTT', 'FTT'] = tmp_df['NTT']
  tmp_df['FTT%'] = tmp_df['LTT%']
  tmp_df.loc[tmp_df['Strategy'] == 'NTT', 'FTT%'] = tmp_df['NTT%']
  tmp_df['FTT Amt'] = round(tmp_df['FTT%'] * tmp_df['Current']/100,0)
  tmp_df['OTT%'] = round((tmp_df['FTT'] - tmp_df['AvgCost'])*100/tmp_df['AvgCost'],2)
  tmp_df['RRR Ind'] = round(tmp_df['Current P/L']/tmp_df['FTT Amt'],2)
  tmp_df['Risk Ind'] = round(tmp_df['Current P/L%']*tmp_df['CurrAlloc%'],0)

  return tmp_df

# function to print portfolio features
def print_portfolio_stats(df_portfolio_features, myinvmt_df):
  from pyxirr import xirr

  total_booked_amt, reserve_amt, cy_booked_amt, py_booked_amt = get_amt()

  dates = myinvmt_df['Date'].values
  dates = np.append(dates, datetime.date.today().strftime('%d-%b-%y'))
  investment = myinvmt_df['Investment'].values
  dates= pd.to_datetime(dates)

  current = round(sum(df_portfolio_features['Close']*df_portfolio_features['Shares']),0) + reserve_amt
  investment_xirr = np.append(investment, current)
  cagr = round(xirr(pd.DataFrame({"dates": dates, "amounts": investment_xirr}))*100,2)

  investment = -sum(investment)
  invested = round(sum(df_portfolio_features['AvgCost']*df_portfolio_features['Shares']),0) + reserve_amt
  previous = round(sum(df_portfolio_features['Prev_Close']*df_portfolio_features['Shares']),0) + reserve_amt
  cy_invested = investment + py_booked_amt

  today_pnl_amount = current-previous
  today_pnl_percentage = round((current-previous)*100/previous,2)

  curr_pnl_amount = current-invested
  curr_pnl_percentage = round((curr_pnl_amount)*100/(cy_invested),2)

  cy_pnl_amount = cy_booked_amt + curr_pnl_amount
  cy_pnl_percentage = round((cy_pnl_amount)*100/cy_invested,2)

  overall_pnl_amount = total_booked_amt + curr_pnl_amount
  overall_pnl_percentage = round((overall_pnl_amount)*100/investment,2)

  estimate_st = round(sum(df_portfolio_features['FTT']*df_portfolio_features['Shares']),0)  + reserve_amt
  est_st_pnl_amount = estimate_st-current
  est_st_pnl_percentage = round((est_st_pnl_amount)*100/current,2)

  estimate_lt = round(sum(df_portfolio_features['LTT']*df_portfolio_features['Shares']),0)  + reserve_amt
  est_lt_pnl_amount = estimate_lt-current
  est_lt_pnl_percentage = round((est_lt_pnl_amount)*100/current,2)

  total_profit = round(sum(df_portfolio_features[df_portfolio_features['Current P/L%'] > 0]['Current']) - sum(df_portfolio_features[df_portfolio_features['Current P/L%'] > 0]['Investment']),0)
  total_loss = round(sum(df_portfolio_features[df_portfolio_features['Current P/L%'] < 0]['Current']) - sum(df_portfolio_features[df_portfolio_features['Current P/L%'] < 0]['Investment']),0)

  cy_booked_percentage = round((cy_booked_amt)*100/current,2)
  py_booked_percentage = round((py_booked_amt)*100/investment,2)
  total_booked_percentage = round((total_booked_amt)*100/investment,2)

  print('-------------------')
  print('Initial Investment: ', format_amt(investment))
  print('CY Investment: ', format_amt(cy_invested))
  print('Reserve: ', format_amt(reserve_amt))
  print('Current: ',  format_amt(current))
  print('-------------------')
  print('Today PnL: '+ '{} ({}%)'.format(format_amt(today_pnl_amount), today_pnl_percentage))
  print('Current PnL: '+ '{} ({}%)'.format(format_amt(curr_pnl_amount), curr_pnl_percentage))
  print('CY Booked + Current PnL: '+ '{} ({}%)'.format(format_amt(cy_pnl_amount), cy_pnl_percentage))
  print('-------------------')
  print('Total profit: ', format_amt(total_profit))
  print('Total loss: ', format_amt(total_loss))
  print('-------------------')
  print('Total Booked + Current PnL: '+ '{} ({}%)'.format(format_amt(overall_pnl_amount), overall_pnl_percentage))
  print('Total Booked PnL: '+ '{} ({}%)'.format(format_amt(total_booked_amt), total_booked_percentage))
  print('Curr Year Booked PnL: '+ '{} ({}%)'.format(format_amt(cy_booked_amt), cy_booked_percentage))
  print('Prev Year Booked PnL: '+ '{} ({}%)'.format(format_amt(py_booked_amt), py_booked_percentage))
  print('===================')
  print('Est FTT: ',  format_amt(estimate_st))
  print('Est FTT PnL: '+ '{} ({}%)'.format(format_amt(est_st_pnl_amount), est_st_pnl_percentage))

  print('===================')
  print('Deployed: ', format_amt(investment))

  print('Current: ', format_amt(current))

  print('CAGR/XIRR %: '+'{}%'.format(cagr))

In [8]:
# get start and end date
start_date, end_date = get_start_end_date()

# get portfolio and prospects data
mypfs_df = get_mypfs_df()
mypps_df = get_mypps_df()
myinvmt_df = get_myinvmt_df()

# merge above datasets
mypf_df = pd.merge(mypfs_df, mypps_df, on="Symbol")

# seggregate dm and sv portfolio
dm_pf = mypf_df[mypf_df['InPortfolio'] == 'DM']
sv_pf = mypf_df[mypf_df['InPortfolio'] == 'SV']

# build portfolio stock dataframe
dm_stocks = get_stock_ids(dm_pf)
sv_stocks = get_stock_ids(sv_pf)
df_stocks = pd.concat([dm_pf,sv_pf], ignore_index = True)

# arrange common and diff stock features
common_cols = ['Symbol', 'Target', 'Criteria', 'Strategy', 'CumlRnk', 'LatestQtr', 'StarStock', 'Conviction', 'Category', 'InFolio', 'XIRR', 'MBQ']
diff_cols = ['Symbol', 'AvgCost', 'Shares']
df_stocks = arrange_features(df_stocks, common_cols, diff_cols)

# get common features
stock_ids = df_stocks['Symbol'].values
df_common_features = get_common_features(stock_ids, df_stocks)

df_common_features.reset_index(drop=True, inplace=True)
df_common_features.drop(['Date'], axis=1, inplace=True)
# get and print portfolio features
df_portfolio_features = get_portfolio_features(df_common_features)

print_portfolio_stats(df_portfolio_features, myinvmt_df)

df = df_portfolio_features
#plot_pie_chart(df, 'CapType', 'Current')
list_ox40n = list(df[df['MBQ'].str.contains('OX40N', na=False)]['Symbol'].values)

Run date time (IST): 2026-04-29 13:08:41
-------------------
qualified stocks: 92
with latest results: 31
still star stocks: 20
-------------------
Initial Investment:  1.40 C
CY Investment:  1.82 C
Reserve:  1.49 K
Current:  1.50 C
-------------------
Today PnL: 1.54 L (1.04%)
Current PnL: -32.87 L (-18.02%)
CY Booked + Current PnL: -30.79 L (-16.88%)
-------------------
Total profit:  1.65 L
Total loss:  -34.51 L
-------------------
Total Booked + Current PnL: 12.08 L (8.66%)
Total Booked PnL: 44.95 L (32.22%)
Curr Year Booked PnL: 2.08 L (1.38%)
Prev Year Booked PnL: 42.87 L (30.73%)
===================
Est FTT:  2.56 C
Est FTT PnL: 1.05 C (69.99%)
===================
Deployed:  1.40 C
Current:  1.50 C
CAGR/XIRR %: 3.73%

In [9]:
# top 5 near their targets
cols = ['Symbol', 'Today P/L%', 'Current P/L%', 'FTT%', 'OTT%', 'FTT Amt', 'Current P/L', 'Current', 'FTT', 'Dev%_PE', 'RSI_14','Conviction', 'Spread%',  'CumlRnk', 'RRR Ind', 'CurrAlloc%', 'Gained%', 'Criteria', 'Strategy', 'Category']
df_tmp = df_portfolio_features[~df_portfolio_features['Symbol'].isin(['ENRIN','BLUSPRING','DIGITIDE'])]
df_tmp = df_tmp.sort_values(by = 'FTT Amt', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
55,MASFIN,2.17,-0.32,21.96,21.57,21447.0,-315.0,97665.0,397.04,-14.18,61.0,H-SC,0.81,167.0,-0.01,0.65,26.21,XR,ATH,FINANCE
51,KOTAKBANK,1.83,2.83,17.77,21.11,25303.0,3922.0,142394.0,453.24,-11.57,55.0,X-LC,9.32,12.0,0.16,0.95,8.90,X40,ATH,BANKS
59,PIDILITIND,0.52,-0.79,19.31,18.37,27032.0,-1120.0,139990.0,1670.26,-30.55,55.0,X-LC,7.58,5.0,-0.04,0.93,9.92,X40,ATH,CHEMICALS
53,M&M,3.12,3.33,19.41,23.38,27813.0,4613.0,143294.0,3802.40,-12.35,52.0,X-LC,8.87,25.0,0.17,0.95,10.32,X40N,ATH,AUTO
83,TTKPRESTIG,0.40,-32.93,49.22,0.09,33271.0,-33181.0,67596.0,770.00,56.88,59.0,M-SC,19.30,250.0,-1.00,0.45,20.36,OX40N,NTT,DURABLES

In [10]:
# top 5 today
df_tmp = df_portfolio_features.sort_values(by = 'Today P/L%', ascending=False)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
9,BANDHANBNK,13.64,-2.34,97.02,92.42,263940.0,-6512.0,272047.0,400.0,133.48,75.0,H-SC,4.60,174.0,-0.02,1.81,49.86,XY24,NTT,BANKS
29,GREENPANEL,9.07,-39.66,137.21,43.14,151580.0,-72605.0,110473.0,537.0,147.42,66.0,M-SC,19.10,225.0,-0.48,0.74,32.70,XY24,NTT,MISC
54,MARUTI,4.64,0.39,28.18,28.68,41816.0,573.0,148390.0,17292.0,-17.49,53.0,X-LC,11.10,33.0,0.01,0.99,15.16,XR,ATH,AUTO
47,ITC,4.06,-16.55,42.68,19.06,121148.0,-56313.0,283853.0,452.0,-54.31,63.0,X-LC,17.51,1.0,-0.46,1.89,10.11,X40,NTT,FMCG
44,INDUSINDBK,3.95,-32.04,95.54,32.89,50131.0,-24736.0,52471.0,1800.0,-347.20,64.0,L-MC,3.94,258.0,-0.49,0.35,29.15,XR,NTT,BANKS

In [11]:
# bottom 5 today
df_tmp = df_portfolio_features.sort_values(by = 'Today P/L%', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
62,RAJOOENG,-14.07,-40.56,134.86,39.61,82170.0,-41570.0,60930.0,143.10,-59.87,46.0,H-SC,23.69,136.0,-0.51,0.41,30.53,AR,ATH,MISC
63,RECLTD,-3.07,-1.39,22.44,20.74,44956.0,-2832.0,200338.0,446.00,9.37,55.0,M-MC,3.38,191.0,-0.06,1.33,19.39,XY25,NTT,FINANCE
49,JSWINFRA,-2.79,-5.71,23.47,16.43,49080.0,-12654.0,209120.0,342.00,-19.19,58.0,X-MC,8.59,61.0,-0.26,1.39,18.21,X40N,NTT,REALTY
6,AWL,-1.91,-30.78,141.29,67.02,348459.0,-109682.0,246627.0,485.00,-62.73,62.0,X-SC,20.85,81.0,-0.31,1.64,16.66,XY24,NTT,FMCG
77,TANLA,-1.74,-37.86,253.57,119.69,426604.0,-102522.0,168239.0,1943.92,-37.17,66.0,H-SC,19.30,147.0,-0.24,1.12,45.66,AR,ATH,IT

In [12]:
# top 5 to exit based on CumlRnk
df_tmp = df_portfolio_features[~df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])]
df_tmp = df_tmp[(df_tmp['Current P/L%'] > -1) & (df_tmp['Current P/L%'] < 1)].sort_values(by = 'CumlRnk', ascending=False)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
55,MASFIN,2.17,-0.32,21.96,21.57,21447.0,-315.0,97665.0,397.04,-14.18,61.0,H-SC,0.81,167.0,-0.01,0.65,26.21,XR,ATH,FINANCE

In [13]:
# OX40N stocks to exit
df_tmp = df_portfolio_features[(df_portfolio_features['Symbol'].isin(list_ox40n))].sort_values(by = 'Current P/L%', ascending=False)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
25,FINCABLES,0.16,27.42,63.18,107.91,118855.0,40478.0,188122.0,1641.55,14.66,73.0,M-SC,9.05,220.0,0.34,1.25,41.53,OX40N,ATH,CABLES
72,SIS,2.65,-16.08,44.50,21.26,41464.0,-17855.0,93177.0,528.00,2208.81,80.0,H-SC,8.19,168.0,-0.43,0.62,38.54,OX40N,NTT,MISC
16,CERA,2.70,-29.80,76.47,23.89,94432.0,-52414.0,123489.0,9475.00,-32.22,62.0,H-SC,12.45,153.0,-0.56,0.82,18.67,OX40N,NTT,CERAMICS
83,TTKPRESTIG,0.40,-32.93,49.22,0.09,33271.0,-33181.0,67596.0,770.00,56.88,59.0,M-SC,19.30,250.0,-1.00,0.45,20.36,OX40N,NTT,DURABLES
76,SYMPHONY,0.18,-33.00,49.21,-0.03,56423.0,-56483.0,114658.0,1306.00,-46.27,68.0,M-SC,13.29,205.0,-1.00,0.76,27.16,OX40N,NTT,DURABLES

In [14]:
# top 5 to book for rotation
df_tmp = df_portfolio_features[(df_portfolio_features['Current P/L%'] > 20) ].sort_values(by = 'CumlRnk', ascending=False)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
25,FINCABLES,0.16,27.42,63.18,107.91,118855.0,40478.0,188122.0,1641.55,14.66,73.0,M-SC,9.05,220.0,0.34,1.25,41.53,OX40N,ATH,CABLES

In [15]:
# top 5 to monitor for exit
df_tmp = df_portfolio_features[~df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])]
df_tmp = df_tmp[(df_tmp['Current P/L%'] > 0) ].sort_values(by = 'Dev%_PE', ascending=False)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
74,STARHEALTH,3.60,3.70,42.00,47.26,122443.0,10407.0,291530.0,761.00,63.65,77.0,H-SC,6.03,173.0,0.08,1.94,50.98,XY24,NTT,INSURANCE
25,FINCABLES,0.16,27.42,63.18,107.91,118855.0,40478.0,188122.0,1641.55,14.66,73.0,M-SC,9.05,220.0,0.34,1.25,41.53,OX40N,ATH,CABLES
73,SONACOMS,1.54,5.18,32.24,39.09,34303.0,5241.0,106400.0,804.02,-16.69,67.0,M-MC,15.37,193.0,0.15,0.71,50.52,AR,ATH,AUTO

In [16]:
# top 5 to book for rotation from weak conviction
df_tmp = df_portfolio_features[~df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])]
df_tmp = df_tmp[~df_tmp['Criteria'].isin(['XY25','XY24','X40', 'X40N'])].sort_values(by = 'RRR Ind', ascending=False)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
25,FINCABLES,0.16,27.42,63.18,107.91,118855.0,40478.0,188122.0,1641.55,14.66,73.0,M-SC,9.05,220.0,0.34,1.25,41.53,OX40N,ATH,CABLES
73,SONACOMS,1.54,5.18,32.24,39.09,34303.0,5241.0,106400.0,804.02,-16.69,67.0,M-MC,15.37,193.0,0.15,0.71,50.52,AR,ATH,AUTO
55,MASFIN,2.17,-0.32,21.96,21.57,21447.0,-315.0,97665.0,397.04,-14.18,61.0,H-SC,0.81,167.0,-0.01,0.65,26.21,XR,ATH,FINANCE
42,INDIAMART,0.48,-8.06,124.84,106.72,141567.0,-9937.0,113399.0,4810.62,-58.59,54.0,H-SC,9.54,140.0,-0.07,0.75,8.95,AR,ATH,MISC
91,ZYDUSLIFE,0.66,-3.27,40.21,35.63,81515.0,-6851.0,202723.0,1286.17,-15.77,51.0,H-MC,3.87,120.0,-0.08,1.35,6.59,AR,ATH,PHARMA

In [17]:
# top 5 to accumulate based on lowest RSI_14
df_tmp = df_portfolio_features[df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])].sort_values(by = 'RSI_14', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
33,HCLTECH,0.68,-21.86,55.50,21.51,104919.0,-52880.0,189044.0,1872.35,-18.11,31.0,X-LC,8.64,8.0,-0.50,1.26,0.68,X40,ATH,IT
45,INFY,2.09,-19.93,67.66,34.24,169509.0,-62357.0,250531.0,1972.00,-36.87,35.0,X-LC,13.43,3.0,-0.37,1.67,2.09,X40,NTT,IT
40,ICICIPRULI,1.70,-12.40,49.23,30.73,84963.0,-24421.0,172584.0,790.00,-35.93,41.0,X-MC,13.16,78.0,-0.29,1.15,5.16,X40,ATH,INSURANCE
27,GLAXO,-1.58,-4.78,46.12,39.15,87521.0,-9516.0,189768.0,3466.20,-27.20,44.0,X-MC,8.63,56.0,-0.11,1.26,4.98,X40,ATH,PHARMA
39,ICICIGI,0.21,-5.95,26.89,19.34,50608.0,-11906.0,188203.0,2252.93,-20.81,44.0,X-MC,6.24,66.0,-0.24,1.25,5.12,X40,ATH,INSURANCE

In [18]:
# top 5 to accumulate based on Spread and CumlRnk
df_tmp = df_portfolio_features[df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])]
df_tmp = df_tmp[(df_tmp['CumlRnk'] < 100)].sort_values(by = 'Spread%', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
88,VOLTAS,-0.77,17.31,23.77,45.20,53465.0,33183.0,224925.0,1856.0,34.28,62.0,X-MC,3.51,79.0,0.62,1.50,25.28,XY25,NTT,AC
84,UNITDSPR,-0.18,0.78,19.83,20.77,46792.0,1823.0,235967.0,1644.0,-10.63,59.0,X-MC,4.11,64.0,0.04,1.57,12.56,X40N,NTT,BREWERIES
81,TMPV,2.11,-18.46,67.50,36.58,195846.0,-65699.0,290142.0,600.0,-82.53,59.0,X-LC,5.72,4.0,-0.34,1.93,20.93,XY24,NTT,AUTO
87,VBL,1.84,6.68,27.02,35.50,91038.0,21086.0,336928.0,670.8,-5.84,77.0,X-LC,5.77,13.0,0.23,2.24,38.35,X40N,ATH,FMCG
65,RELIANCE,2.03,-9.03,37.75,25.30,69009.0,-18157.0,182806.0,1952.0,-11.57,60.0,X-LC,5.96,21.0,-0.26,1.22,8.62,XY25,BTT,REFINERIES

In [19]:
# top 5 to accumulate based on lowest Gained%
df_tmp = df_portfolio_features[df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])].sort_values(by = 'Gained%', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
33,HCLTECH,0.68,-21.86,55.50,21.51,104919.0,-52880.0,189044.0,1872.35,-18.11,31.0,X-LC,8.64,8.0,-0.50,1.26,0.68,X40,ATH,IT
1,ABBOTINDIA,0.85,-14.25,37.70,18.07,57817.0,-25495.0,153360.0,35195.00,-27.11,45.0,X-MC,11.96,58.0,-0.44,1.02,1.51,X40,ATH,PHARMA
45,INFY,2.09,-19.93,67.66,34.24,169509.0,-62357.0,250531.0,1972.00,-36.87,35.0,X-LC,13.43,3.0,-0.37,1.67,2.09,X40,NTT,IT
27,GLAXO,-1.58,-4.78,46.12,39.15,87521.0,-9516.0,189768.0,3466.20,-27.20,44.0,X-MC,8.63,56.0,-0.11,1.26,4.98,X40,ATH,PHARMA
39,ICICIGI,0.21,-5.95,26.89,19.34,50608.0,-11906.0,188203.0,2252.93,-20.81,44.0,X-MC,6.24,66.0,-0.24,1.25,5.12,X40,ATH,INSURANCE

In [20]:
# top 5 to accumulate based on lowest CurrAlloc%
df_tmp = df_portfolio_features[df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])].sort_values(by = 'CurrAlloc%', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
64,RELAXO,0.22,-60.50,285.57,52.31,163746.0,-87820.0,57340.0,1176.00,-57.99,54.0,X-SC,27.73,92.0,-0.54,0.38,28.21,X40N,NTT,FOOTWEAR
10,BATAINDIA,0.61,-52.92,187.16,35.20,113385.0,-68088.0,60582.0,2096.00,-20.58,51.0,X-SC,27.55,91.0,-0.60,0.40,20.15,X40,NTT,FOOTWEAR
60,QUESS,2.13,-16.29,107.74,73.90,96315.0,-17397.0,89396.0,424.00,-54.82,63.0,X-SC,15.37,80.0,-0.18,0.59,20.26,XY24,NTT,MISC
59,PIDILITIND,0.52,-0.79,19.31,18.37,27032.0,-1120.0,139990.0,1670.26,-30.55,55.0,X-LC,7.58,5.0,-0.04,0.93,9.92,X40,ATH,CHEMICALS
51,KOTAKBANK,1.83,2.83,17.77,21.11,25303.0,3922.0,142394.0,453.24,-11.57,55.0,X-LC,9.32,12.0,0.16,0.95,8.90,X40,ATH,BANKS

In [21]:
# top 5 to accumulate based on CumlRnk
df_tmp = df_portfolio_features.sort_values(by = 'CumlRnk', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
47,ITC,4.06,-16.55,42.68,19.06,121148.0,-56313.0,283853.0,452.00,-54.31,63.0,X-LC,17.51,1.0,-0.46,1.89,10.11,X40,NTT,FMCG
79,TCS,1.65,-27.05,73.50,26.57,248411.0,-125299.0,337974.0,4311.59,-38.38,47.0,X-LC,14.45,2.0,-0.50,2.25,5.48,X40,ATH,IT
45,INFY,2.09,-19.93,67.66,34.24,169509.0,-62357.0,250531.0,1972.00,-36.87,35.0,X-LC,13.43,3.0,-0.37,1.67,2.09,X40,NTT,IT
81,TMPV,2.11,-18.46,67.50,36.58,195846.0,-65699.0,290142.0,600.00,-82.53,59.0,X-LC,5.72,4.0,-0.34,1.93,20.93,XY24,NTT,AUTO
59,PIDILITIND,0.52,-0.79,19.31,18.37,27032.0,-1120.0,139990.0,1670.26,-30.55,55.0,X-LC,7.58,5.0,-0.04,0.93,9.92,X40,ATH,CHEMICALS

In [22]:
# top 5 for average up
df_tmp = df_portfolio_features[(df_portfolio_features['Dev%_200'] > 5)].sort_values(by = 'CurrAlloc%', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
44,INDUSINDBK,3.95,-32.04,95.54,32.89,50131.0,-24736.0,52471.0,1800.00,-347.20,64.0,L-MC,3.94,258.0,-0.49,0.35,29.15,XR,NTT,BANKS
72,SIS,2.65,-16.08,44.50,21.26,41464.0,-17855.0,93177.0,528.00,2208.81,80.0,H-SC,8.19,168.0,-0.43,0.62,38.54,OX40N,NTT,MISC
73,SONACOMS,1.54,5.18,32.24,39.09,34303.0,5241.0,106400.0,804.02,-16.69,67.0,M-MC,15.37,193.0,0.15,0.71,50.52,AR,ATH,AUTO
75,SURYODAY,2.33,-12.55,40.70,23.03,63732.0,-22481.0,156590.0,216.00,71.05,69.0,H-SC,5.41,166.0,-0.35,1.04,33.54,XR,NTT,BANKS
5,ATULAUTO,1.08,-15.31,71.88,45.57,120009.0,-30175.0,166957.0,844.00,3618.92,62.0,M-SC,1.08,248.0,-0.25,1.11,28.48,XY24,NTT,AUTO

In [23]:
# top 5 RSP
df_tmp = df_portfolio_features.sort_values(by = 'RSP', ascending=False)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
61,RAJESHEXPO,-0.49,-75.57,309.65,0.07,103761.0,-103668.0,33509.0,518.00,1128.54,59.0,L-SC,34.03,268.0,-1.00,0.22,57.32,OX40N,NTT,JEWELLERY
77,TANLA,-1.74,-37.86,253.57,119.69,426604.0,-102522.0,168239.0,1943.92,-37.17,66.0,H-SC,19.30,147.0,-0.24,1.12,45.66,AR,ATH,IT
9,BANDHANBNK,13.64,-2.34,97.02,92.42,263940.0,-6512.0,272047.0,400.00,133.48,75.0,H-SC,4.60,174.0,-0.02,1.81,49.86,XY24,NTT,BANKS
80,TITAGARH,1.40,-24.96,94.22,45.74,171223.0,-60450.0,181727.0,1548.00,0.02,70.0,H-SC,14.90,175.0,-0.35,1.21,38.65,XY24,NTT,ENGINEERING
87,VBL,1.84,6.68,27.02,35.50,91038.0,21086.0,336928.0,670.80,-5.84,77.0,X-LC,5.77,13.0,0.23,2.24,38.35,X40N,ATH,FMCG

In [24]:
# Top N allocation
df_tmp = df_portfolio_features.sort_values(by = 'CurrAlloc%', ascending=False)
top_n_values = [10, 25, 50]

sum_df = pd.DataFrame({
    'Top_N': top_n_values,
    'Sum_Alloc%': [df_tmp['CurrAlloc%'].head(n).sum() for n in top_n_values]
})

sum_df

   Top_N  Sum_Alloc%
0     10       19.19
1     25       42.77
2     50       72.70

In [25]:
# market-cap-wise allocation
df_tmp = df_portfolio_features[cols]
df_tmp.groupby(df_tmp['Conviction'].str[-2:])['CurrAlloc%'].sum().sort_values(ascending=False)

Conviction
SC    42.09
LC    31.95
MC    25.95
Name: CurrAlloc%, dtype: float64

In [26]:
# criteria-wise allocation
df_portfolio_features.groupby('Criteria')['CurrAlloc%'].sum().sort_values(ascending=False)

Criteria
XY24     26.86
X40      25.56
X40N     17.08
XR        9.01
XY25      7.05
OX40N     6.85
AR        6.78
SR        0.80
Name: CurrAlloc%, dtype: float64

In [27]:
# conviction-wise allocation
df_portfolio_features.groupby('Conviction')['CurrAlloc%'].sum().sort_values(ascending=False)

Conviction
X-LC    29.75
H-SC    21.84
X-MC    21.01
M-SC    10.02
X-SC     9.67
H-MC     2.55
M-MC     2.04
H-LC     1.27
M-LC     0.93
L-SC     0.56
L-MC     0.35
Name: CurrAlloc%, dtype: float64

In [28]:
# sector-wise stats
df_tmp = df_portfolio_features.groupby('Category')[['CurrAlloc%', 'Current', 'Current P/L', 'FTT Amt']].sum().sort_values(by=['Current', 'Current P/L'], ascending=False)
df_tmp['Current P/L%'] = round(df_tmp['Current P/L'] * 100 / df_tmp['Current'], 2)
df_tmp['FTT%'] = round(df_tmp['FTT Amt'] * 100 / df_tmp['Current'], 2)
cols = ['CurrAlloc%', 'Current P/L%', 'FTT%']
df_tmp[cols].sort_values(by=['CurrAlloc%'], ascending=False)

               CurrAlloc%  Current P/L%    FTT%
Category
FMCG                15.79        -11.52   50.88
FINANCE             10.70        -14.61   64.45
IT                  10.60        -41.63  113.35
MISC                 6.82        -30.75   87.54
AUTO                 6.69         -8.93   49.77
BANKS                5.62         -7.54   57.27
INSURANCE            5.32         -3.52   38.75
PAINTS               5.05        -29.79   52.33
PHARMA               4.72         -4.49   38.07
ELECTRICAL           4.09        -14.99   55.93
AC                   2.03         -4.84   33.27
CHEMICALS            1.99        -35.10  115.61
HEALTHCARE           1.91        -24.54   57.04
DURABLES             1.82        -41.42   75.83
FOOTWEAR             1.74        -68.22  135.67
APPARELS             1.73         -3.15   38.33
TRAVEL               1.71        -74.08  161.25
BREWERIES            1.57          0.77   19.83
REALTY               1.39         -6.05   23.47
CERAMICS             1.29        -58.10  106.13
CABLES               1.25         21.52   63.18
REFINERIES           1.22         -9.93   37.75
ENGINEERING          1.21        -33.26   94.22
CEMENT               1.16        -54.03  169.27
JEWELLERY            1.05       -101.23  171.14
ENTERTAINMENT        0.75        -72.33  175.11
TEXTILES             0.43        -42.56   83.21
HOTELS               0.34       -121.33  199.40

In [29]:
# money to be made criteria-wise
df_portfolio_features.groupby('Criteria')['FTT Amt'].agg(['sum', 'count']).sort_values(by='sum', ascending=False)

                sum  count
Criteria
XY24      3558678.0     21
X40       1861083.0     19
XR        1326489.0     13
AR        1172693.0      9
X40N      1159822.0     13
OX40N      761136.0     10
XY25       381433.0      5
SR         298858.0      2

In [30]:
# money to be made conviction-wise
df_portfolio_features.groupby('Conviction')['FTT Amt'].agg(['sum', 'count']).sort_values(by='sum', ascending=False)

                  sum  count
Conviction
H-SC        3508841.0     24
X-LC        1829513.0     21
X-MC        1577270.0     15
M-SC        1410931.0     14
X-SC        1348451.0      9
H-MC         315436.0      2
L-SC         206057.0      2
M-LC         151509.0      1
M-MC          79259.0      2
L-MC          50131.0      1
H-LC          42794.0      1

In [31]:
# money to be made criteria and conviction-wise
df_portfolio_features.groupby(['Conviction', 'Criteria'])['FTT Amt'].agg(['sum', 'count']).sort_values(by='sum', ascending=False)

                           sum  count
Conviction Criteria
H-SC       XY24      1126576.0      6
X-LC       X40        997368.0     10
H-SC       AR         939280.0      5
M-SC       XY24       842145.0      6
H-SC       XR         809235.0      7
X-SC       XY24       790313.0      4
X-MC       X40        664539.0      7
           X40N       463500.0      4
X-SC       X40N       358962.0      3
X-LC       X40N       337360.0      6
H-SC       OX40N      334892.0      4
X-LC       XY24       326514.0      2
M-SC       OX40N      322483.0      5
H-SC       SR         298858.0      2
X-MC       XY24       239209.0      2
H-MC       XY24       233921.0      1
X-MC       XY25       210022.0      2
X-SC       X40        199176.0      2
M-SC       XR         171502.0      2
M-LC       XR         151509.0      1
X-LC       XY25       126455.0      2
L-SC       OX40N      103761.0      1
           XR         102296.0      1
H-MC       AR          81515.0      1
M-SC       AR          74801.0      1
L-MC       XR          50131.0      1
M-MC       XY25        44956.0      1
H-LC       AR          42794.0      1
X-LC       XR          41816.0      1
M-MC       AR          34303.0      1

In [32]:
# notebook execution time

end_time = time.time()
execution_time = round(end_time - start_time, 0)
print(f"Notebook execution time: {execution_time} seconds")

Notebook execution time: 27.0 seconds