<a href="https://colab.research.google.com/github/ankit-rathi/Quantvesting_v2/blob/main/myStocks_Portfolio_Analysis.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
'''
!pip install pandas==2.2.2 -qq
!pip install pyxirr -qq
!pip install ta -qq
!pip install yfinance==0.2.59 -qq
'''

'\n!pip install pandas==2.2.2 -qq\n!pip install pyxirr -qq\n!pip install ta -qq\n!pip install yfinance==0.2.59 -qq\n'

In [2]:
# import libraries

import numpy as np
import pandas as pd
import datetime
import warnings
warnings.filterwarnings('ignore')
import yfinance as yfin
import ta
import matplotlib.pyplot as plt
import requests

In [3]:
# notebook start time
import time
import datetime
import pytz

start_time = time.time()

# function to print date timestamp
def print_date_time():
  tz_NY = pytz.timezone('Asia/Kolkata')
  datetime_NY = datetime.datetime.now(tz_NY)
  print("Run date time (IST):", datetime_NY.strftime("%Y-%m-%d %H:%M:%S"))

In [4]:
# function to get booked and reserved amount
def get_amt():
  # fetch the JSON data from the URL
  url = "https://raw.githubusercontent.com/ankit-rathi/Tradevesting_v1/main/data/myPortfolioAmts.json"
  response = requests.get(url)
  pf_amts = response.json()  # parse the JSON data

  # extract values from the JSON
  py_booked_amt_dm = pf_amts["py_booked_amt_dm"]
  py_booked_amt_sv = pf_amts["py_booked_amt_sv"]
  cy_booked_amt_dm = pf_amts["cy_booked_amt_dm"]
  cy_booked_amt_sv = pf_amts["cy_booked_amt_sv"]
  reserve_amt_dm = pf_amts["reserve_amt_dm"]
  reserve_amt_sv = pf_amts["reserve_amt_sv"]

  # perform calculations
  py_booked_amt = py_booked_amt_dm + py_booked_amt_sv
  cy_booked_amt = cy_booked_amt_dm + cy_booked_amt_sv
  reserve_amt = reserve_amt_dm + reserve_amt_sv
  total_booked_amt = py_booked_amt + cy_booked_amt

  return total_booked_amt, reserve_amt, cy_booked_amt, py_booked_amt

gen_output = 0

In [5]:
# function to format the amount
def format_amt(number):
    abs_number = abs(number)

    if abs_number >= 1_00_00_000:  # Crores
        formatted_amt = f"{number / 1_00_00_000:.2f} C"
    elif abs_number >= 1_00_000:  # Lakhs
        formatted_amt = f"{number / 1_00_000:.2f} L"
    elif abs_number >= 1_000:  # Thousands
        formatted_amt = f"{number / 1_000:.2f} K"
    else:
        formatted_amt = f"{number:.2f}"

    return formatted_amt

# function to set start and end date
def get_start_end_date():
  start_date = (datetime.date.today() + datetime.timedelta(days=-365)).strftime('%Y-%m-%d')
  end_date = (datetime.date.today() + datetime.timedelta(days=1)).strftime('%Y-%m-%d')
  return start_date, end_date

# function to fetch my portfolio csv
def get_mypfs_df():
  mypfs_df = pd.read_csv('https://raw.githubusercontent.com/ankit-rathi/Tradevesting_v1/main/data/myPortfolioStocks.csv')
  return mypfs_df

# function to fetch my prospects csv
def get_mypps_df():
  mypps_df = pd.read_csv('https://raw.githubusercontent.com/ankit-rathi/Tradevesting_v1/main/data/myProspectsScrips.csv')
  return mypps_df

# function to fetch screener data
def get_myscreen_df():
  myscreen_df = pd.read_csv('https://raw.githubusercontent.com/ankit-rathi/Tradevesting_v1/main/data/myScreenerDB.csv')
  return myscreen_df

# function to fetch momentum data
def get_myinvmt_df():
  myinvmt_df = pd.read_csv('https://raw.githubusercontent.com/ankit-rathi/Tradevesting_v1/main/data/myInvestments.csv')
  return myinvmt_df

# function to get the stock ids
def get_stock_ids(df_pf):
  stock_n100 = df_pf['Symbol'].unique()

  exclude = ['CADILAHC','MMTC', 'MASFIN']

  stock_ids = df_pf[~df_pf['Symbol'].isin(exclude) ]['Symbol'].unique()

  #mypf = mypf[mypf.Forecast.notnull()]
  #stock_ids = mypf['Symbol'].unique()

  #stock_ids.sort()
  return stock_ids

# get features from screener data
def get_screener_features():
  myscreen_df = get_myscreen_df()
  cols = ['Symbol', 'EPS', 'MedPE', 'ROCE%', 'ROE%', 'CapType']
  return myscreen_df[cols]

# get relative strength
def get_relative_strength(stock_list):

    # Dictionary to store stock tickers and their corresponding percentage price change
    stock_changes = {}

    # Loop through each stock and fetch its price data
    for stock in stock_list:
        try:
            # Download the stock data for the given date range
            stock_data = yfin.Ticker(stock + '.NS').history(period='1mo', interval='1d')[map(str.title, ['open', 'close', 'low', 'high', 'volume'])]

            # Calculate the percentage change for the stock
            if len(stock_data) > 0:
                start_price = stock_data['Close'].iloc[0]
                end_price = stock_data['Close'].iloc[-1]
                percent_change = round(((end_price - start_price) / start_price) * 100, 2)
                stock_changes[stock] = percent_change
            else:
                stock_changes[stock] = np.nan  # If no data is available, set to NaN

        except Exception as e:
            print(f"Error fetching data for {stock}: {e}")
            stock_changes[stock] = np.nan

    # Create a DataFrame with stock tickers and their percentage changes
    df = pd.DataFrame(list(stock_changes.items()), columns=['Symbol', 'Percent_Change'])

    # Drop any stocks with missing data (NaN values)
    df = df.dropna()

    # Calculate the percentile rank based on percentage change
    df['RSP'] = round(df['Percent_Change'].rank(pct=True) * 100, 2)
    cols = ['Symbol', 'RSP']
    df = df[cols]
    # Sort by percentile rank (optional)
    df = df.sort_values(by='RSP', ascending=False).reset_index(drop=True)

    return df

In [6]:
# function to get stock technicals
def stock_prec_dev(stock_symbol):
    #stock_symbol = 'ULTRACEMCO.NS'
    short_window = 20
    mid_window = 50
    long_window = 200
    moving_avg = 'SMA'

    start = datetime.datetime(*map(int, start_date.split('-')))
    end = datetime.datetime(*map(int, end_date.split('-')))

    stock_df = yfin.Ticker(stock_symbol + '.NS').history(period='max', interval='1d')[map(str.title, ['open', 'close', 'low', 'high', 'volume'])]

    stock_df['Max'] = round(max(stock_df['Close']),2)
    stock_df = stock_df[(stock_df.index <= end_date) & (stock_df.index >= start_date)]
    stock_df['200_SMA'] = round(stock_df['Close'].rolling(window = 200, min_periods = 1).mean(),0)
    stock_df['Dev%_200'] = round((stock_df['Close'] - stock_df['200_SMA'])*100/stock_df['200_SMA'],2)
    stock_df.dropna(axis = 0, inplace = True) # remove any null rows

    stock_df['20_SMA'] = stock_df['Close'].rolling(window=20).mean()
    stock_df['50_SMA'] = stock_df['Close'].rolling(window=50).mean()
    stock_df['Symbol'] = stock_symbol

    stock_df['Close'] = round(stock_df['Close'],2)
    stock_df['Min'] = round(min(stock_df['Close']),2)
    stock_df['RSI_14'] = ta.momentum.RSIIndicator(close=stock_df['Close'], window=14).rsi()
    stock_df['RSI_14'] = round(stock_df['RSI_14'],0)
    stock_df['Prev_Close'] = stock_df['Close'].shift(1)
    stock_df.drop(['Open', 'Low', 'High', 'Volume'], axis=1, inplace=True)
    stock_df = stock_df.tail(1)

    max_SMA = max(stock_df['20_SMA'].item(), stock_df['50_SMA'].item(), stock_df['200_SMA'].item())
    min_SMA = min(stock_df['20_SMA'].item(), stock_df['50_SMA'].item(), stock_df['200_SMA'].item())
    ABS_Spread = max_SMA - min_SMA
    stock_df['Spread%'] = round((ABS_Spread / stock_df['200_SMA'].item()) * 100,2)

    return stock_df

# function to compute stock attributes
def get_common_features(stock_ids, df_mypf):

  df_prec_dev = pd.DataFrame()
  df_tmp = get_screener_features()
  df_rs = get_relative_strength(stock_ids)

  for stock_id in stock_ids:
      tmp = stock_prec_dev(stock_id)
      tmp = tmp.reset_index()
      df_prec_dev = pd.concat([df_prec_dev, tmp], ignore_index = True)
  df_prec_dev = pd.merge(df_prec_dev, df_mypf, on= 'Symbol')
  df_prec_dev = pd.merge(df_prec_dev, df_tmp, on= 'Symbol', how='left')
  df_prec_dev = pd.merge(df_prec_dev, df_rs, on= 'Symbol', how='left')
  #print(df_prec_dev.columns)
  df_prec_dev['Curr_PE'] = round(df_prec_dev['Close']/df_prec_dev['EPS'],1)
  df_prec_dev['Dev%_PE'] = round((df_prec_dev['Curr_PE'] - df_prec_dev['MedPE'])*100/df_prec_dev['MedPE'],2)
  df_prec_dev['Conviction'] = df_prec_dev['Conviction'] + '-' + df_prec_dev['CapType']
  return df_prec_dev

# function to arrange stock features
def arrange_features(df_stocks, common_cols, diff_cols):
  df_stocks_common = df_stocks[common_cols].drop_duplicates()
  df_stocks_diff = df_stocks[diff_cols]
  df_stocks_diff['Investment'] = df_stocks_diff['AvgCost'] * df_stocks_diff['Shares']
  df_stocks_diff = df_stocks_diff.groupby(['Symbol'])[['Shares', 'Investment']].aggregate(['sum']).reset_index()
  df_stocks_diff.columns = ['Symbol', 'Shares', 'Investment']
  df_stocks_diff['AvgCost'] = round(df_stocks_diff['Investment']/df_stocks_diff['Shares'],2)
  df_stocks = pd.merge(df_stocks_diff, df_stocks_common, on='Symbol')
  return df_stocks

# plot fact distribution across dimension
def plot_pie_chart(df, dimension, fact):
  # grouping the data by category and calculating the sum of fact for each type
  grouped_data = df.groupby(dimension)[fact].sum()

  # sorting the grouped data in descending order
  grouped_data = grouped_data.sort_values(ascending=False)

  # creating a pie chart
  grouped_data.plot.pie(autopct='%1.1f%%', startangle=90, figsize=(6, 6))

  # adding a title and displaying the plot
  plt.title(f'{dimension} {fact} Distribution')
  plt.ylabel('')  # To hide the y-label
  plt.show()

In [7]:
# function to get portfolio features

def get_portfolio_features(df_common_features):

  print_date_time()
  print('-------------------')

  #df_common_features["Target"] = df_common_features["Target"].fillna(df_common_features["Max"])
  df_common_features['NTT'] = np.where(df_common_features['Strategy']== 'NTT', df_common_features["Target"], df_common_features['Max'])
  df_common_features['LTT'] = np.where(df_common_features['Strategy']== 'BTT', df_common_features["Target"], df_common_features['Max'])
  df_common_features['BOL'] = df_common_features['Min']

  tmp_df = df_common_features[df_common_features['Symbol'].isin(mypf_df[mypf_df['InPortfolio'] != 'NA'].Symbol.values)]
  print('qualified stocks: '+str(len(tmp_df['Symbol'].unique())))
  tmp_df1 = tmp_df[tmp_df['LatestQtr'] == 1]
  print('with latest results: '+str(len(tmp_df1['Symbol'].unique())))
  tmp_df1 = tmp_df1[tmp_df1['StarStock'] == 1]
  print('still star stocks: '+str(len(tmp_df1['Symbol'].unique())))
  tmp_df['Investment'] = tmp_df['AvgCost'] * tmp_df['Shares']
  tmp_df['Current'] = round(tmp_df['Close'] * tmp_df['Shares'],0)
  tmp_df['Previous'] = tmp_df['Prev_Close'] * tmp_df['Shares']
  tmp_df['EstimatedST'] = tmp_df['NTT'] * tmp_df['Shares']
  tmp_df['EstimatedLT'] = tmp_df['LTT'] * tmp_df['Shares']
  tmp_df['Current P/L'] = round((tmp_df['Current'] - tmp_df['Investment']),0)
  tmp_df['Today P/L%'] = round((tmp_df['Current'] - tmp_df['Previous'])*100/tmp_df['Previous'],2)
  tmp_df['Current P/L%'] = round((tmp_df['Current'] - tmp_df['Investment'])*100/tmp_df['Investment'],2)
  tmp_df['EstimatedST P/L%'] = round((tmp_df['EstimatedST'] - tmp_df['Investment'])*100/tmp_df['Investment'],2)
  tmp_df['EstimatedLT P/L%'] = round((tmp_df['EstimatedLT'] - tmp_df['Investment'])*100/tmp_df['Investment'],2)
  tmp_df['NTT%'] = round((tmp_df['NTT'] - tmp_df['Close'])*100/tmp_df['Close'],2)
  tmp_df['LTT%'] = round((tmp_df['LTT'] - tmp_df['Close'])*100/tmp_df['Close'],2)
  tmp_df['Gained%'] = round((tmp_df['Close'] - tmp_df['BOL'])*100/tmp_df['BOL'],2)
  investment = round(sum(tmp_df['AvgCost']*tmp_df['Shares']),0)
  current = round(sum(tmp_df['Close']*tmp_df['Shares']),0)
  tmp_df['InitAlloc%'] = round(tmp_df['Investment']*100/investment,2)
  tmp_df['CurrAlloc%'] = round(tmp_df['Current']*100/current,2)
  tmp_df['FTT'] = tmp_df['LTT']
  tmp_df.loc[tmp_df['Strategy'] == 'NTT', 'FTT'] = tmp_df['NTT']
  tmp_df['FTT%'] = tmp_df['LTT%']
  tmp_df.loc[tmp_df['Strategy'] == 'NTT', 'FTT%'] = tmp_df['NTT%']
  tmp_df['FTT Amt'] = round(tmp_df['FTT%'] * tmp_df['Current']/100,0)
  tmp_df['OTT%'] = round((tmp_df['FTT'] - tmp_df['AvgCost'])*100/tmp_df['AvgCost'],2)
  tmp_df['RRR Ind'] = round(tmp_df['Current P/L']/tmp_df['FTT Amt'],2)
  tmp_df['Risk Ind'] = round(tmp_df['Current P/L%']*tmp_df['CurrAlloc%'],0)

  return tmp_df

# function to print portfolio features
def print_portfolio_stats(df_portfolio_features, myinvmt_df):
  from pyxirr import xirr

  total_booked_amt, reserve_amt, cy_booked_amt, py_booked_amt = get_amt()

  dates = myinvmt_df['Date'].values
  dates = np.append(dates, datetime.date.today().strftime('%d-%b-%y'))
  investment = myinvmt_df['Investment'].values
  dates= pd.to_datetime(dates)

  current = round(sum(df_portfolio_features['Close']*df_portfolio_features['Shares']),0) + reserve_amt
  investment_xirr = np.append(investment, current)
  cagr = round(xirr(pd.DataFrame({"dates": dates, "amounts": investment_xirr}))*100,2)

  investment = -sum(investment)
  invested = round(sum(df_portfolio_features['AvgCost']*df_portfolio_features['Shares']),0) + reserve_amt
  previous = round(sum(df_portfolio_features['Prev_Close']*df_portfolio_features['Shares']),0) + reserve_amt
  cy_invested = investment + py_booked_amt

  today_pnl_amount = current-previous
  today_pnl_percentage = round((current-previous)*100/previous,2)

  curr_pnl_amount = current-invested
  curr_pnl_percentage = round((curr_pnl_amount)*100/(cy_invested),2)

  cy_pnl_amount = cy_booked_amt + curr_pnl_amount
  cy_pnl_percentage = round((cy_pnl_amount)*100/cy_invested,2)

  overall_pnl_amount = total_booked_amt + curr_pnl_amount
  overall_pnl_percentage = round((overall_pnl_amount)*100/investment,2)

  estimate_st = round(sum(df_portfolio_features['FTT']*df_portfolio_features['Shares']),0)  + reserve_amt
  est_st_pnl_amount = estimate_st-current
  est_st_pnl_percentage = round((est_st_pnl_amount)*100/current,2)

  estimate_lt = round(sum(df_portfolio_features['LTT']*df_portfolio_features['Shares']),0)  + reserve_amt
  est_lt_pnl_amount = estimate_lt-current
  est_lt_pnl_percentage = round((est_lt_pnl_amount)*100/current,2)

  total_profit = round(sum(df_portfolio_features[df_portfolio_features['Current P/L%'] > 0]['Current']) - sum(df_portfolio_features[df_portfolio_features['Current P/L%'] > 0]['Investment']),0)
  total_loss = round(sum(df_portfolio_features[df_portfolio_features['Current P/L%'] < 0]['Current']) - sum(df_portfolio_features[df_portfolio_features['Current P/L%'] < 0]['Investment']),0)

  cy_booked_percentage = round((cy_booked_amt)*100/current,2)
  py_booked_percentage = round((py_booked_amt)*100/investment,2)
  total_booked_percentage = round((total_booked_amt)*100/investment,2)

  print('-------------------')
  print('Initial Investment: ', format_amt(investment))
  print('CY Investment: ', format_amt(cy_invested))
  print('Reserve: ', format_amt(reserve_amt))
  print('Current: ',  format_amt(current))
  print('-------------------')
  print('Today PnL: '+ '{} ({}%)'.format(format_amt(today_pnl_amount), today_pnl_percentage))
  print('Current PnL: '+ '{} ({}%)'.format(format_amt(curr_pnl_amount), curr_pnl_percentage))
  print('CY Booked + Current PnL: '+ '{} ({}%)'.format(format_amt(cy_pnl_amount), cy_pnl_percentage))
  print('-------------------')
  print('Total profit: ', format_amt(total_profit))
  print('Total loss: ', format_amt(total_loss))
  print('-------------------')
  print('Total Booked + Current PnL: '+ '{} ({}%)'.format(format_amt(overall_pnl_amount), overall_pnl_percentage))
  print('Total Booked PnL: '+ '{} ({}%)'.format(format_amt(total_booked_amt), total_booked_percentage))
  print('Curr Year Booked PnL: '+ '{} ({}%)'.format(format_amt(cy_booked_amt), cy_booked_percentage))
  print('Prev Year Booked PnL: '+ '{} ({}%)'.format(format_amt(py_booked_amt), py_booked_percentage))
  print('===================')
  print('Est FTT: ',  format_amt(estimate_st))
  print('Est FTT PnL: '+ '{} ({}%)'.format(format_amt(est_st_pnl_amount), est_st_pnl_percentage))

  print('===================')
  print('Deployed: ', format_amt(investment))

  print('Current: ', format_amt(current))

  print('CAGR/XIRR %: '+'{}%'.format(cagr))

In [8]:
# get start and end date
start_date, end_date = get_start_end_date()

# get portfolio and prospects data
mypfs_df = get_mypfs_df()
mypps_df = get_mypps_df()
myinvmt_df = get_myinvmt_df()

# merge above datasets
mypf_df = pd.merge(mypfs_df, mypps_df, on="Symbol")

# seggregate dm and sv portfolio
dm_pf = mypf_df[mypf_df['InPortfolio'] == 'DM']
sv_pf = mypf_df[mypf_df['InPortfolio'] == 'SV']

# build portfolio stock dataframe
dm_stocks = get_stock_ids(dm_pf)
sv_stocks = get_stock_ids(sv_pf)
df_stocks = pd.concat([dm_pf,sv_pf], ignore_index = True)

# arrange common and diff stock features
common_cols = ['Symbol', 'Target', 'Criteria', 'Strategy', 'CumlRnk', 'LatestQtr', 'StarStock', 'Conviction', 'Category', 'InFolio', 'XIRR', 'MBQ']
diff_cols = ['Symbol', 'AvgCost', 'Shares']
df_stocks = arrange_features(df_stocks, common_cols, diff_cols)

# get common features
stock_ids = df_stocks['Symbol'].values
df_common_features = get_common_features(stock_ids, df_stocks)

df_common_features.reset_index(drop=True, inplace=True)
df_common_features.drop(['Date'], axis=1, inplace=True)
# get and print portfolio features
df_portfolio_features = get_portfolio_features(df_common_features)

print_portfolio_stats(df_portfolio_features, myinvmt_df)

df = df_portfolio_features
#plot_pie_chart(df, 'CapType', 'Current')
list_ox40n = list(df[df['MBQ'].str.contains('OX40N', na=False)]['Symbol'].values)

Run date time (IST): 2026-03-12 13:06:14
-------------------
qualified stocks: 86
with latest results: 26
still star stocks: 15
-------------------
Initial Investment:  1.36 C
CY Investment:  1.62 C
Reserve:  66.25 K
Current:  1.36 C
-------------------
Today PnL: -85.42 K (-0.63%)
Current PnL: -41.11 L (-25.3%)
CY Booked + Current PnL: -25.43 L (-15.65%)
-------------------
Total profit:  1.08 L
Total loss:  -42.20 L
-------------------
Total Booked + Current PnL: 1.55 L (1.14%)
Total Booked PnL: 42.66 L (31.48%)
Curr Year Booked PnL: 15.68 L (11.55%)
Prev Year Booked PnL: 26.98 L (19.91%)
===================
Est FTT:  2.47 C
Est FTT PnL: 1.11 C (82.08%)
===================
Deployed:  1.36 C
Current:  1.36 C
CAGR/XIRR %: 0.11%

In [9]:
# top 5 near their targets
cols = ['Symbol', 'Today P/L%', 'Current P/L%', 'FTT%', 'OTT%', 'FTT Amt', 'Current P/L', 'Current', 'FTT', 'Dev%_PE', 'RSI_14','Conviction', 'Spread%',  'CumlRnk', 'RRR Ind', 'CurrAlloc%', 'Gained%', 'Criteria', 'Strategy', 'Category']
df_tmp = df_portfolio_features[~df_portfolio_features['Symbol'].isin(['ENRIN','BLUSPRING','DIGITIDE'])]
df_tmp = df_tmp.sort_values(by = 'FTT Amt', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
19,COALINDIA,3.69,13.92,3.29,17.67,5639.0,20942.0,171402.0,478.51,37.73,68.0,L-LC,12.11,185.0,3.71,1.27,33.11,XY25,ATH,MINING
77,TTKPRESTIG,6.17,-26.10,35.44,0.09,26394.0,-26303.0,74474.0,770.00,72.89,59.0,M-SC,15.32,250.0,-1.00,0.55,25.83,OX40N,NTT,DURABLES
50,MASFIN,0.59,-6.55,30.09,21.57,27550.0,-6420.0,91560.0,397.04,-19.60,40.0,H-SC,4.18,167.0,-0.23,0.68,27.02,XR,ATH,FINANCE
37,ICICIGI,-1.73,-2.39,22.26,19.34,43480.0,-4783.0,195326.0,2252.93,-17.87,39.0,X-MC,1.79,66.0,-0.11,1.45,11.40,X40,ATH,INSURANCE
78,UNITDSPR,-1.74,-0.24,21.06,20.77,49191.0,-568.0,233576.0,1644.00,-11.56,47.0,X-MC,1.39,64.0,-0.01,1.73,6.45,X40N,NTT,BREWERIES

In [10]:
# top 5 today
df_tmp = df_portfolio_features.sort_values(by = 'Today P/L%', ascending=False)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
77,TTKPRESTIG,6.17,-26.10,35.44,0.09,26394.0,-26303.0,74474.0,770.00,72.89,59.0,M-SC,15.32,250.0,-1.00,0.55,25.83,OX40N,NTT,DURABLES
19,COALINDIA,3.69,13.92,3.29,17.67,5639.0,20942.0,171402.0,478.51,37.73,68.0,L-LC,12.11,185.0,3.71,1.27,33.11,XY25,ATH,MINING
57,RECLTD,3.29,-6.88,29.65,20.74,56098.0,-13970.0,189200.0,446.00,3.52,48.0,M-MC,5.06,191.0,-0.25,1.40,6.04,XY25,NTT,FINANCE
30,GREENPANEL,2.63,-46.69,168.50,43.14,164456.0,-85478.0,97600.0,537.00,118.35,38.0,M-SC,19.99,225.0,-0.52,0.72,2.63,XY24,NTT,MISC
60,REPCOHOME,2.32,-19.65,136.24,89.82,313631.0,-56300.0,230205.0,880.00,-59.76,43.0,H-SC,3.64,161.0,-0.18,1.70,22.38,XY24,NTT,FINANCE

In [11]:
# bottom 5 today
df_tmp = df_portfolio_features.sort_values(by = 'Today P/L%', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
81,VBL,-4.71,-16.99,63.44,35.67,166331.0,-53656.0,262186.0,671.64,-26.66,29.0,X-LC,5.10,13.0,-0.32,1.94,0.00,X40N,ATH,FMCG
42,INDUSINDBK,-4.64,-38.24,115.18,32.89,54918.0,-29526.0,47680.0,1800.00,-324.09,31.0,L-MC,10.62,258.0,-0.54,0.35,31.31,XR,NTT,BANKS
55,RAJESHEXPO,-4.38,-78.84,372.84,0.07,108239.0,-108146.0,29031.0,518.00,964.39,22.0,L-SC,21.04,268.0,-1.00,0.21,0.33,OX40N,NTT,JEWELLERY
21,COLPAL,-3.61,-24.77,88.09,41.51,174542.0,-65225.0,198140.0,3726.84,-8.99,32.0,X-MC,4.12,62.0,-0.37,1.47,0.00,XY25,ATH,FMCG
22,DABUR,-3.17,-10.67,60.87,43.70,134885.0,-26472.0,221596.0,735.00,-18.91,30.0,X-MC,1.54,70.0,-0.20,1.64,2.77,XY24,BTT,FMCG

In [12]:
# top 5 to exit based on CumlRnk
df_tmp = df_portfolio_features[~df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])]
df_tmp = df_tmp[(df_tmp['Current P/L%'] > -1) & (df_tmp['Current P/L%'] < 1)].sort_values(by = 'CumlRnk', ascending=False)
df_tmp[cols].head()

Empty DataFrame
Columns: [Symbol, Today P/L%, Current P/L%, FTT%, OTT%, FTT Amt, Current P/L, Current, FTT, Dev%_PE, RSI_14, Conviction, Spread%, CumlRnk, RRR Ind, CurrAlloc%, Gained%, Criteria, Strategy, Category]
Index: []

In [13]:
# OX40N stocks to exit
df_tmp = df_portfolio_features[(df_portfolio_features['Symbol'].isin(list_ox40n))].sort_values(by = 'Current P/L%', ascending=False)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
27,FINCABLES,0.53,13.05,83.91,107.91,140059.0,19272.0,166916.0,1641.55,1.47,56.0,M-SC,7.74,220.0,0.14,1.24,25.58,OX40N,ATH,CABLES
77,TTKPRESTIG,6.17,-26.10,35.44,0.09,26394.0,-26303.0,74474.0,770.00,72.89,59.0,M-SC,15.32,250.0,-1.00,0.55,25.83,OX40N,NTT,DURABLES
66,SIS,-1.46,-34.03,83.81,21.26,61390.0,-37783.0,73249.0,528.00,1715.03,35.0,H-SC,10.62,168.0,-0.62,0.54,0.98,OX40N,NTT,MISC
70,SYMPHONY,0.90,-36.58,57.63,-0.03,62548.0,-62607.0,108534.0,1306.00,-49.12,49.0,M-SC,13.66,205.0,-1.00,0.80,9.76,OX40N,NTT,DURABLES
48,KANSAINER,0.88,-37.04,80.22,13.47,136209.0,-99873.0,169794.0,340.00,-45.81,30.0,H-SC,16.71,162.0,-0.73,1.26,1.80,XY24,NTT,PAINTS

In [14]:
# top 5 to book for rotation
df_tmp = df_portfolio_features[(df_portfolio_features['Current P/L%'] > 20) ].sort_values(by = 'CumlRnk', ascending=False)
df_tmp[cols].head()

Empty DataFrame
Columns: [Symbol, Today P/L%, Current P/L%, FTT%, OTT%, FTT Amt, Current P/L, Current, FTT, Dev%_PE, RSI_14, Conviction, Spread%, CumlRnk, RRR Ind, CurrAlloc%, Gained%, Criteria, Strategy, Category]
Index: []

In [15]:
# top 5 to monitor for exit
df_tmp = df_portfolio_features[~df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])]
df_tmp = df_tmp[(df_tmp['Current P/L%'] > 0) ].sort_values(by = 'Dev%_PE', ascending=False)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
19,COALINDIA,3.69,13.92,3.29,17.67,5639.0,20942.0,171402.0,478.51,37.73,68.0,L-LC,12.11,185.0,3.71,1.27,33.11,XY25,ATH,MINING
27,FINCABLES,0.53,13.05,83.91,107.91,140059.0,19272.0,166916.0,1641.55,1.47,56.0,M-SC,7.74,220.0,0.14,1.24,25.58,OX40N,ATH,CABLES
1,ABB,0.76,16.10,25.38,45.57,77090.0,42125.0,303744.0,7934.00,-25.41,67.0,H-MC,10.50,125.0,0.55,2.25,34.88,AR,NTT,ELECTRICAL

In [16]:
# top 5 to book for rotation from weak conviction
df_tmp = df_portfolio_features[~df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])]
df_tmp = df_tmp[~df_tmp['Criteria'].isin(['XY25','XY24','X40', 'X40N'])].sort_values(by = 'RRR Ind', ascending=False)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
1,ABB,0.76,16.10,25.38,45.57,77090.0,42125.0,303744.0,7934.00,-25.41,67.0,H-MC,10.50,125.0,0.55,2.25,34.88,AR,NTT,ELECTRICAL
27,FINCABLES,0.53,13.05,83.91,107.91,140059.0,19272.0,166916.0,1641.55,1.47,56.0,M-SC,7.74,220.0,0.14,1.24,25.58,OX40N,ATH,CABLES
40,INDIAMART,-1.34,-9.68,128.87,106.72,143562.0,-11935.0,111401.0,4810.62,-59.18,41.0,H-SC,9.46,140.0,-0.08,0.82,11.44,AR,ATH,MISC
85,ZYDUSLIFE,-0.28,-3.07,39.92,35.63,81095.0,-6431.0,203143.0,1286.17,-15.77,54.0,H-MC,5.01,120.0,-0.08,1.50,13.09,AR,ATH,PHARMA
84,WIPRO,-0.11,-17.15,107.92,72.27,151509.0,-29058.0,140390.0,420.00,-25.02,34.0,M-LC,15.06,98.0,-0.19,1.04,3.38,XR,NTT,IT

In [17]:
# top 5 to accumulate based on lowest RSI_14
df_tmp = df_portfolio_features[df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])].sort_values(by = 'RSI_14', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
58,RELAXO,-0.30,-60.66,287.16,52.31,163983.0,-88055.0,57105.0,1176.00,-58.09,19.0,X-SC,19.53,92.0,-0.54,0.42,0.00,X40N,NTT,FOOTWEAR
3,ACC,-1.39,-35.73,171.99,74.81,296394.0,-95796.0,172332.0,3906.00,-54.32,21.0,X-SC,12.80,85.0,-0.32,1.28,0.00,XY24,BTT,CEMENT
8,AWL,-1.00,-38.84,173.07,67.02,377166.0,-138382.0,217927.0,485.00,-67.02,21.0,X-SC,23.36,81.0,-0.37,1.61,1.14,XY24,NTT,FMCG
73,TCS,-0.77,-28.20,76.28,26.57,253739.0,-130631.0,332642.0,4311.59,-39.36,21.0,X-LC,14.44,2.0,-0.51,2.46,0.00,X40,ATH,IT
53,PGHH,-1.37,-19.90,64.80,32.01,110834.0,-42480.0,171040.0,17616.87,-45.79,24.0,X-MC,11.61,57.0,-0.38,1.27,0.81,X40,ATH,FMCG

In [18]:
# top 5 to accumulate based on Spread and CumlRnk
df_tmp = df_portfolio_features[df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])]
df_tmp = df_tmp[(df_tmp['CumlRnk'] < 100)].sort_values(by = 'Spread%', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
78,UNITDSPR,-1.74,-0.24,21.06,20.77,49191.0,-568.0,233576.0,1644.00,-11.56,47.0,X-MC,1.39,64.0,-0.01,1.73,6.45,X40N,NTT,BREWERIES
22,DABUR,-3.17,-10.67,60.87,43.70,134885.0,-26472.0,221596.0,735.00,-18.91,30.0,X-MC,1.54,70.0,-0.20,1.64,2.77,XY24,BTT,FMCG
75,TMPV,-2.52,-25.59,83.54,36.58,221205.0,-91052.0,264789.0,600.00,-84.72,33.0,X-LC,1.78,4.0,-0.41,1.96,0.00,XY24,NTT,AUTO
37,ICICIGI,-1.73,-2.39,22.26,19.34,43480.0,-4783.0,195326.0,2252.93,-17.87,39.0,X-MC,1.79,66.0,-0.11,1.45,11.40,X40,ATH,INSURANCE
59,RELIANCE,0.73,-10.11,39.39,25.30,71159.0,-20311.0,180652.0,1952.00,-12.34,47.0,X-LC,2.71,21.0,-0.29,1.34,20.61,XY25,BTT,REFINERIES

In [19]:
# top 5 to accumulate based on lowest Gained%
df_tmp = df_portfolio_features[df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])].sort_values(by = 'Gained%', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
3,ACC,-1.39,-35.73,171.99,74.81,296394.0,-95796.0,172332.0,3906.00,-54.32,21.0,X-SC,12.80,85.0,-0.32,1.28,0.0,XY24,BTT,CEMENT
10,BAJAJHLDNG,-2.26,-11.06,45.29,29.22,76585.0,-21026.0,169099.0,14451.52,-17.81,27.0,X-LC,12.27,28.0,-0.27,1.25,0.0,X40,ATH,FINANCE
21,COLPAL,-3.61,-24.77,88.09,41.51,174542.0,-65225.0,198140.0,3726.84,-8.99,32.0,X-MC,4.12,62.0,-0.37,1.47,0.0,XY25,ATH,FMCG
13,BERGEPAINT,-2.22,-22.40,61.48,25.32,122974.0,-57727.0,200022.0,680.00,-26.59,24.0,X-MC,15.69,68.0,-0.47,1.48,0.0,XY24,NTT,PAINTS
52,PAGEIND,-2.66,-19.78,67.19,34.11,144650.0,-53094.0,215285.0,51418.64,-42.47,32.0,X-MC,20.22,55.0,-0.37,1.59,0.0,X40,ATH,APPARELS

In [20]:
# top 5 to accumulate based on lowest CurrAlloc%
df_tmp = df_portfolio_features[df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])].sort_values(by = 'CurrAlloc%', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
58,RELAXO,-0.30,-60.66,287.16,52.31,163983.0,-88055.0,57105.0,1176.00,-58.09,19.0,X-SC,19.53,92.0,-0.54,0.42,0.00,X40N,NTT,FOOTWEAR
12,BATAINDIA,0.64,-53.34,189.78,35.20,113933.0,-68636.0,60034.0,2096.00,-21.30,24.0,X-SC,26.19,91.0,-0.60,0.44,0.89,X40,NTT,FOOTWEAR
54,QUESS,-0.24,-20.97,120.05,73.90,101315.0,-22399.0,84394.0,424.00,-57.58,43.0,X-SC,18.30,80.0,-0.22,0.62,4.11,XY24,NTT,MISC
36,HONAUT,-0.57,-20.98,91.49,51.31,139408.0,-40463.0,152375.0,58357.33,-34.34,41.0,X-SC,13.80,90.0,-0.29,1.13,2.61,X40N,ATH,ELECTRICAL
2,ABBOTINDIA,-1.53,-10.15,31.40,18.07,50463.0,-18145.0,160710.0,35195.00,-23.63,47.0,X-MC,11.09,58.0,-0.36,1.19,1.88,X40,ATH,PHARMA

In [21]:
# top 5 to accumulate based on CumlRnk
df_tmp = df_portfolio_features.sort_values(by = 'CumlRnk', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
45,ITC,-0.95,-19.39,47.69,19.06,130776.0,-65945.0,274221.0,452.00,-55.92,35.0,X-LC,17.03,1.0,-0.50,2.03,0.02,X40,NTT,FMCG
73,TCS,-0.77,-28.20,76.28,26.57,253739.0,-130631.0,332642.0,4311.59,-39.36,21.0,X-LC,14.44,2.0,-0.51,2.46,0.00,X40,ATH,IT
43,INFY,-0.49,-13.54,55.28,34.24,149538.0,-42378.0,270510.0,1972.00,-31.79,25.0,X-LC,12.73,3.0,-0.28,2.00,0.00,X40,NTT,IT
75,TMPV,-2.52,-25.59,83.54,36.58,221205.0,-91052.0,264789.0,600.00,-84.72,33.0,X-LC,1.78,4.0,-0.41,1.96,0.00,XY24,NTT,AUTO
34,HCLTECH,0.30,-12.10,40.89,23.83,86949.0,-29283.0,212641.0,1908.19,-7.78,29.0,X-LC,9.81,8.0,-0.34,1.57,2.02,X40,ATH,IT

In [22]:
# top 5 for average up
df_tmp = df_portfolio_features[(df_portfolio_features['Dev%_200'] > 5)].sort_values(by = 'CurrAlloc%', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
67,SONACOMS,-1.23,-11.77,57.65,39.09,51453.0,-11909.0,89250.0,804.02,-30.06,48.0,M-MC,9.83,193.0,-0.23,0.66,26.26,AR,ATH,AUTO
27,FINCABLES,0.53,13.05,83.91,107.91,140059.0,19272.0,166916.0,1641.55,1.47,56.0,M-SC,7.74,220.0,0.14,1.24,25.58,OX40N,ATH,CABLES
19,COALINDIA,3.69,13.92,3.29,17.67,5639.0,20942.0,171402.0,478.51,37.73,68.0,L-LC,12.11,185.0,3.71,1.27,33.11,XY25,ATH,MINING
11,BANDHANBNK,-2.39,-14.33,124.59,92.42,297339.0,-39905.0,238654.0,400.00,104.74,56.0,H-SC,9.87,174.0,-0.13,1.77,31.47,XY24,NTT,BANKS
1,ABB,0.76,16.10,25.38,45.57,77090.0,42125.0,303744.0,7934.00,-25.41,67.0,H-MC,10.50,125.0,0.55,2.25,34.88,AR,NTT,ELECTRICAL

In [23]:
# top 5 RSP
df_tmp = df_portfolio_features.sort_values(by = 'RSP', ascending=False)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
19,COALINDIA,3.69,13.92,3.29,17.67,5639.0,20942.0,171402.0,478.51,37.73,68.0,L-LC,12.11,185.0,3.71,1.27,33.11,XY25,ATH,MINING
1,ABB,0.76,16.10,25.38,45.57,77090.0,42125.0,303744.0,7934.00,-25.41,67.0,H-MC,10.50,125.0,0.55,2.25,34.88,AR,NTT,ELECTRICAL
27,FINCABLES,0.53,13.05,83.91,107.91,140059.0,19272.0,166916.0,1641.55,1.47,56.0,M-SC,7.74,220.0,0.14,1.24,25.58,OX40N,ATH,CABLES
26,EASEMYTRIP,-1.36,-59.99,264.14,45.70,186868.0,-106069.0,70746.0,26.40,-26.57,42.0,M-SC,18.20,204.0,-0.57,0.52,16.56,XY24,NTT,TRAVEL
31,HAPPSTMNDS,-1.83,-49.55,266.38,84.85,172252.0,-63501.0,64664.0,1480.71,-39.93,59.0,H-SC,28.40,152.0,-0.37,0.48,19.75,AR,ATH,IT

In [24]:
# Top N allocation
df_tmp = df_portfolio_features.sort_values(by = 'CurrAlloc%', ascending=False)
top_n_values = [10, 25, 50]

sum_df = pd.DataFrame({
    'Top_N': top_n_values,
    'Sum_Alloc%': [df_tmp['CurrAlloc%'].head(n).sum() for n in top_n_values]
})

sum_df

   Top_N  Sum_Alloc%
0     10       20.33
1     25       45.12
2     50       77.72

In [25]:
# market-cap-wise allocation
df_tmp = df_portfolio_features[cols]
df_tmp.groupby(df_tmp['Conviction'].str[-2:])['CurrAlloc%'].sum().sort_values(ascending=False)

Conviction
SC    44.78
MC    30.36
LC    24.86
Name: CurrAlloc%, dtype: float64

In [26]:
# criteria-wise allocation
df_portfolio_features.groupby('Criteria')['CurrAlloc%'].sum().sort_values(ascending=False)

Criteria
XY24     27.30
X40      23.71
X40N     15.03
AR        9.24
XY25      8.68
XR        8.27
OX40N     6.99
SR        0.78
Name: CurrAlloc%, dtype: float64

In [27]:
# conviction-wise allocation
df_portfolio_features.groupby('Conviction')['CurrAlloc%'].sum().sort_values(ascending=False)

Conviction
X-MC    22.90
H-SC    21.79
X-LC    21.33
X-SC    12.10
M-SC    10.31
H-MC     5.05
M-MC     2.06
L-LC     1.27
H-LC     1.22
M-LC     1.04
L-SC     0.58
L-MC     0.35
Name: CurrAlloc%, dtype: float64

In [28]:
# sector-wise stats
df_tmp = df_portfolio_features.groupby('Category')[['CurrAlloc%', 'Current', 'Current P/L', 'FTT Amt']].sum().sort_values(by=['Current', 'Current P/L'], ascending=False)
df_tmp['Current P/L%'] = round(df_tmp['Current P/L'] * 100 / df_tmp['Current'], 2)
df_tmp['FTT%'] = round(df_tmp['FTT Amt'] * 100 / df_tmp['Current'], 2)
cols = ['CurrAlloc%', 'Current P/L%', 'FTT%']
df_tmp[cols].sort_values(by=['CurrAlloc%'], ascending=False)

               CurrAlloc%  Current P/L%    FTT%
Category
FMCG                15.08        -22.60   66.13
FINANCE             12.88        -23.38   73.66
IT                  11.70        -42.38  114.84
MISC                 7.02        -41.39  102.81
ELECTRICAL           6.70         -7.03   48.01
PAINTS               5.17        -41.20   65.73
INSURANCE            4.72         -6.43   42.85
PHARMA               4.18         -4.08   36.83
AUTO                 3.68        -31.39   83.52
BANKS                3.10        -27.67  105.03
AC                   2.15        -10.11   39.96
HEALTHCARE           1.99        -32.81   67.47
DURABLES             1.94        -46.91   82.65
FOOTWEAR             1.86        -74.58  144.57
TRAVEL               1.82        -81.98  173.10
BREWERIES            1.73         -0.24   21.06
APPARELS             1.59        -24.66   67.19
REALTY               1.45        -12.89   31.44
CERAMICS             1.36        -67.30  118.13
REFINERIES           1.34        -11.24   39.39
CEMENT               1.28        -55.59  171.99
MINING               1.27         12.22    3.29
CABLES               1.24         11.55   83.91
JEWELLERY            1.11       -112.64  186.52
ENGINEERING          1.11        -61.60  135.51
CHEMICALS            0.96       -103.27  269.11
ENTERTAINMENT        0.77        -85.72  196.48
TEXTILES             0.43        -60.51  106.27
HOTELS               0.37       -125.64  205.23

In [29]:
# money to be made criteria-wise
df_portfolio_features.groupby('Criteria')['FTT Amt'].agg(['sum', 'count']).sort_values(by='sum', ascending=False)

                sum  count
Criteria
XY24      3907113.0     21
X40       1668376.0     15
XR        1373791.0     12
AR        1321975.0     10
X40N      1268396.0     10
OX40N      847612.0     10
XY25       445563.0      6
SR         314250.0      2

In [30]:
# money to be made conviction-wise
df_portfolio_features.groupby('Conviction')['FTT Amt'].agg(['sum', 'count']).sort_values(by='sum', ascending=False)

                  sum  count
Conviction
H-SC        3849283.0     24
X-MC        1640192.0     15
X-LC        1591758.0     12
X-SC        1546484.0     10
M-SC        1523119.0     14
H-MC         396812.0      3
L-SC         211517.0      2
M-LC         151509.0      1
M-MC         107551.0      2
H-LC          68294.0      1
L-MC          54918.0      1
L-LC           5639.0      1

In [31]:
# money to be made criteria and conviction-wise
df_portfolio_features.groupby(['Conviction', 'Criteria'])['FTT Amt'].agg(['sum', 'count']).sort_values(by='sum', ascending=False)

                           sum  count
Conviction Criteria
H-SC       XY24      1309059.0      6
           AR         967404.0      5
M-SC       XY24       901591.0      6
H-SC       XR         874390.0      7
X-SC       XY24       833283.0      4
X-LC       X40        824806.0      6
X-MC       X40        639585.0      7
X-SC       X40N       509216.0      4
X-MC       X40N       506141.0      4
H-SC       OX40N      384180.0      4
X-LC       XY24       366694.0      2
M-SC       OX40N      355193.0      5
H-SC       SR         314250.0      2
X-MC       XY24       257859.0      2
X-LC       X40N       253039.0      2
H-MC       XY24       238627.0      1
X-MC       XY25       236607.0      2
X-SC       X40        203985.0      2
M-SC       XR         189696.0      2
H-MC       AR         158185.0      2
M-LC       XR         151509.0      1
X-LC       XY25       147219.0      2
L-SC       OX40N      108239.0      1
           XR         103278.0      1
M-SC       AR          76639.0      1
H-LC       AR          68294.0      1
M-MC       XY25        56098.0      1
L-MC       XR          54918.0      1
M-MC       AR          51453.0      1
L-LC       XY25         5639.0      1

In [32]:
# notebook execution time

end_time = time.time()
execution_time = round(end_time - start_time, 0)
print(f"Notebook execution time: {execution_time} seconds")

Notebook execution time: 23.0 seconds