<a href="https://colab.research.google.com/github/ankit-rathi/Quantvesting_v2/blob/main/myStocks_Portfolio_Analysis.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
'''
!pip install pandas==2.2.2 -qq
!pip install pyxirr -qq
!pip install ta -qq
!pip install yfinance==0.2.59 -qq
'''

'\n!pip install pandas==2.2.2 -qq\n!pip install pyxirr -qq\n!pip install ta -qq\n!pip install yfinance==0.2.59 -qq\n'

In [2]:
# import libraries

import numpy as np
import pandas as pd
import datetime
import warnings
warnings.filterwarnings('ignore')
import yfinance as yfin
import ta
import matplotlib.pyplot as plt
import requests

In [3]:
# notebook start time
import time
import datetime
import pytz

start_time = time.time()

# function to print date timestamp
def print_date_time():
  tz_NY = pytz.timezone('Asia/Kolkata')
  datetime_NY = datetime.datetime.now(tz_NY)
  print("Run date time (IST):", datetime_NY.strftime("%Y-%m-%d %H:%M:%S"))

In [4]:
# function to get booked and reserved amount
def get_amt():
  # fetch the JSON data from the URL
  url = "https://raw.githubusercontent.com/ankit-rathi/Tradevesting_v1/main/data/myPortfolioAmts.json"
  response = requests.get(url)
  pf_amts = response.json()  # parse the JSON data

  # extract values from the JSON
  py_booked_amt_dm = pf_amts["py_booked_amt_dm"]
  py_booked_amt_sv = pf_amts["py_booked_amt_sv"]
  cy_booked_amt_dm = pf_amts["cy_booked_amt_dm"]
  cy_booked_amt_sv = pf_amts["cy_booked_amt_sv"]
  reserve_amt_dm = pf_amts["reserve_amt_dm"]
  reserve_amt_sv = pf_amts["reserve_amt_sv"]

  # perform calculations
  py_booked_amt = py_booked_amt_dm + py_booked_amt_sv
  cy_booked_amt = cy_booked_amt_dm + cy_booked_amt_sv
  reserve_amt = reserve_amt_dm + reserve_amt_sv
  total_booked_amt = py_booked_amt + cy_booked_amt

  return total_booked_amt, reserve_amt, cy_booked_amt, py_booked_amt

gen_output = 0

In [5]:
# function to format the amount
def format_amt(number):
    abs_number = abs(number)

    if abs_number >= 1_00_00_000:  # Crores
        formatted_amt = f"{number / 1_00_00_000:.2f} C"
    elif abs_number >= 1_00_000:  # Lakhs
        formatted_amt = f"{number / 1_00_000:.2f} L"
    elif abs_number >= 1_000:  # Thousands
        formatted_amt = f"{number / 1_000:.2f} K"
    else:
        formatted_amt = f"{number:.2f}"

    return formatted_amt

# function to set start and end date
def get_start_end_date():
  start_date = (datetime.date.today() + datetime.timedelta(days=-365)).strftime('%Y-%m-%d')
  end_date = (datetime.date.today() + datetime.timedelta(days=1)).strftime('%Y-%m-%d')
  return start_date, end_date

# function to fetch my portfolio csv
def get_mypfs_df():
  mypfs_df = pd.read_csv('https://raw.githubusercontent.com/ankit-rathi/Tradevesting_v1/main/data/myPortfolioStocks.csv')
  return mypfs_df

# function to fetch my prospects csv
def get_mypps_df():
  mypps_df = pd.read_csv('https://raw.githubusercontent.com/ankit-rathi/Tradevesting_v1/main/data/myProspectsScrips.csv')
  return mypps_df

# function to fetch screener data
def get_myscreen_df():
  myscreen_df = pd.read_csv('https://raw.githubusercontent.com/ankit-rathi/Tradevesting_v1/main/data/myScreenerDB.csv')
  return myscreen_df

# function to fetch momentum data
def get_myinvmt_df():
  myinvmt_df = pd.read_csv('https://raw.githubusercontent.com/ankit-rathi/Tradevesting_v1/main/data/myInvestments.csv')
  return myinvmt_df

# function to get the stock ids
def get_stock_ids(df_pf):
  stock_n100 = df_pf['Symbol'].unique()

  exclude = ['CADILAHC','MMTC', 'MASFIN']

  stock_ids = df_pf[~df_pf['Symbol'].isin(exclude) ]['Symbol'].unique()

  #mypf = mypf[mypf.Forecast.notnull()]
  #stock_ids = mypf['Symbol'].unique()

  #stock_ids.sort()
  return stock_ids

# get features from screener data
def get_screener_features():
  myscreen_df = get_myscreen_df()
  cols = ['Symbol', 'EPS', 'MedPE', 'ROCE%', 'ROE%', 'CapType']
  return myscreen_df[cols]

# get relative strength
def get_relative_strength(stock_list):

    # Dictionary to store stock tickers and their corresponding percentage price change
    stock_changes = {}

    # Loop through each stock and fetch its price data
    for stock in stock_list:
        try:
            # Download the stock data for the given date range
            stock_data = yfin.Ticker(stock + '.NS').history(period='1mo', interval='1d')[map(str.title, ['open', 'close', 'low', 'high', 'volume'])]

            # Calculate the percentage change for the stock
            if len(stock_data) > 0:
                start_price = stock_data['Close'].iloc[0]
                end_price = stock_data['Close'].iloc[-1]
                percent_change = round(((end_price - start_price) / start_price) * 100, 2)
                stock_changes[stock] = percent_change
            else:
                stock_changes[stock] = np.nan  # If no data is available, set to NaN

        except Exception as e:
            print(f"Error fetching data for {stock}: {e}")
            stock_changes[stock] = np.nan

    # Create a DataFrame with stock tickers and their percentage changes
    df = pd.DataFrame(list(stock_changes.items()), columns=['Symbol', 'Percent_Change'])

    # Drop any stocks with missing data (NaN values)
    df = df.dropna()

    # Calculate the percentile rank based on percentage change
    df['RSP'] = round(df['Percent_Change'].rank(pct=True) * 100, 2)
    cols = ['Symbol', 'RSP']
    df = df[cols]
    # Sort by percentile rank (optional)
    df = df.sort_values(by='RSP', ascending=False).reset_index(drop=True)

    return df

In [6]:
# function to get stock technicals
def stock_prec_dev(stock_symbol):
    #stock_symbol = 'ULTRACEMCO.NS'
    short_window = 20
    mid_window = 50
    long_window = 200
    moving_avg = 'SMA'

    start = datetime.datetime(*map(int, start_date.split('-')))
    end = datetime.datetime(*map(int, end_date.split('-')))

    stock_df = yfin.Ticker(stock_symbol + '.NS').history(period='max', interval='1d')[map(str.title, ['open', 'close', 'low', 'high', 'volume'])]

    stock_df['Max'] = round(max(stock_df['Close']),2)
    stock_df = stock_df[(stock_df.index <= end_date) & (stock_df.index >= start_date)]
    stock_df['200_SMA'] = round(stock_df['Close'].rolling(window = 200, min_periods = 1).mean(),0)
    stock_df['Dev%_200'] = round((stock_df['Close'] - stock_df['200_SMA'])*100/stock_df['200_SMA'],2)
    stock_df.dropna(axis = 0, inplace = True) # remove any null rows

    stock_df['20_SMA'] = stock_df['Close'].rolling(window=20).mean()
    stock_df['50_SMA'] = stock_df['Close'].rolling(window=50).mean()
    stock_df['Symbol'] = stock_symbol

    stock_df['Close'] = round(stock_df['Close'],2)
    stock_df['Min'] = round(min(stock_df['Close']),2)
    stock_df['RSI_14'] = ta.momentum.RSIIndicator(close=stock_df['Close'], window=14).rsi()
    stock_df['RSI_14'] = round(stock_df['RSI_14'],0)
    stock_df['Prev_Close'] = stock_df['Close'].shift(1)
    stock_df.drop(['Open', 'Low', 'High', 'Volume'], axis=1, inplace=True)
    stock_df = stock_df.tail(1)

    max_SMA = max(stock_df['20_SMA'].item(), stock_df['50_SMA'].item(), stock_df['200_SMA'].item())
    min_SMA = min(stock_df['20_SMA'].item(), stock_df['50_SMA'].item(), stock_df['200_SMA'].item())
    ABS_Spread = max_SMA - min_SMA
    stock_df['Spread%'] = round((ABS_Spread / stock_df['200_SMA'].item()) * 100,2)

    return stock_df

# function to compute stock attributes
def get_common_features(stock_ids, df_mypf):

  df_prec_dev = pd.DataFrame()
  df_tmp = get_screener_features()
  df_rs = get_relative_strength(stock_ids)

  for stock_id in stock_ids:
      tmp = stock_prec_dev(stock_id)
      tmp = tmp.reset_index()
      df_prec_dev = pd.concat([df_prec_dev, tmp], ignore_index = True)
  df_prec_dev = pd.merge(df_prec_dev, df_mypf, on= 'Symbol')
  df_prec_dev = pd.merge(df_prec_dev, df_tmp, on= 'Symbol', how='left')
  df_prec_dev = pd.merge(df_prec_dev, df_rs, on= 'Symbol', how='left')
  #print(df_prec_dev.columns)
  df_prec_dev['Curr_PE'] = round(df_prec_dev['Close']/df_prec_dev['EPS'],1)
  df_prec_dev['Dev%_PE'] = round((df_prec_dev['Curr_PE'] - df_prec_dev['MedPE'])*100/df_prec_dev['MedPE'],2)
  df_prec_dev['Conviction'] = df_prec_dev['Conviction'] + '-' + df_prec_dev['CapType']
  return df_prec_dev

# function to arrange stock features
def arrange_features(df_stocks, common_cols, diff_cols):
  df_stocks_common = df_stocks[common_cols].drop_duplicates()
  df_stocks_diff = df_stocks[diff_cols]
  df_stocks_diff['Investment'] = df_stocks_diff['AvgCost'] * df_stocks_diff['Shares']
  df_stocks_diff = df_stocks_diff.groupby(['Symbol'])[['Shares', 'Investment']].aggregate(['sum']).reset_index()
  df_stocks_diff.columns = ['Symbol', 'Shares', 'Investment']
  df_stocks_diff['AvgCost'] = round(df_stocks_diff['Investment']/df_stocks_diff['Shares'],2)
  df_stocks = pd.merge(df_stocks_diff, df_stocks_common, on='Symbol')
  return df_stocks

# plot fact distribution across dimension
def plot_pie_chart(df, dimension, fact):
  # grouping the data by category and calculating the sum of fact for each type
  grouped_data = df.groupby(dimension)[fact].sum()

  # sorting the grouped data in descending order
  grouped_data = grouped_data.sort_values(ascending=False)

  # creating a pie chart
  grouped_data.plot.pie(autopct='%1.1f%%', startangle=90, figsize=(6, 6))

  # adding a title and displaying the plot
  plt.title(f'{dimension} {fact} Distribution')
  plt.ylabel('')  # To hide the y-label
  plt.show()

In [7]:
# function to get portfolio features

def get_portfolio_features(df_common_features):

  print_date_time()
  print('-------------------')

  #df_common_features["Target"] = df_common_features["Target"].fillna(df_common_features["Max"])
  df_common_features['NTT'] = np.where(df_common_features['Strategy']== 'NTT', df_common_features["Target"], df_common_features['Max'])
  df_common_features['LTT'] = np.where(df_common_features['Strategy']== 'BTT', df_common_features["Target"], df_common_features['Max'])
  df_common_features['BOL'] = df_common_features['Min']

  tmp_df = df_common_features[df_common_features['Symbol'].isin(mypf_df[mypf_df['InPortfolio'] != 'NA'].Symbol.values)]
  print('qualified stocks: '+str(len(tmp_df['Symbol'].unique())))
  tmp_df1 = tmp_df[tmp_df['LatestQtr'] == 1]
  print('with latest results: '+str(len(tmp_df1['Symbol'].unique())))
  tmp_df1 = tmp_df1[tmp_df1['StarStock'] == 1]
  print('still star stocks: '+str(len(tmp_df1['Symbol'].unique())))
  tmp_df['Investment'] = tmp_df['AvgCost'] * tmp_df['Shares']
  tmp_df['Current'] = round(tmp_df['Close'] * tmp_df['Shares'],0)
  tmp_df['Previous'] = tmp_df['Prev_Close'] * tmp_df['Shares']
  tmp_df['EstimatedST'] = tmp_df['NTT'] * tmp_df['Shares']
  tmp_df['EstimatedLT'] = tmp_df['LTT'] * tmp_df['Shares']
  tmp_df['Current P/L'] = round((tmp_df['Current'] - tmp_df['Investment']),0)
  tmp_df['Today P/L%'] = round((tmp_df['Current'] - tmp_df['Previous'])*100/tmp_df['Previous'],2)
  tmp_df['Current P/L%'] = round((tmp_df['Current'] - tmp_df['Investment'])*100/tmp_df['Investment'],2)
  tmp_df['EstimatedST P/L%'] = round((tmp_df['EstimatedST'] - tmp_df['Investment'])*100/tmp_df['Investment'],2)
  tmp_df['EstimatedLT P/L%'] = round((tmp_df['EstimatedLT'] - tmp_df['Investment'])*100/tmp_df['Investment'],2)
  tmp_df['NTT%'] = round((tmp_df['NTT'] - tmp_df['Close'])*100/tmp_df['Close'],2)
  tmp_df['LTT%'] = round((tmp_df['LTT'] - tmp_df['Close'])*100/tmp_df['Close'],2)
  tmp_df['Gained%'] = round((tmp_df['Close'] - tmp_df['BOL'])*100/tmp_df['BOL'],2)
  investment = round(sum(tmp_df['AvgCost']*tmp_df['Shares']),0)
  current = round(sum(tmp_df['Close']*tmp_df['Shares']),0)
  tmp_df['InitAlloc%'] = round(tmp_df['Investment']*100/investment,2)
  tmp_df['CurrAlloc%'] = round(tmp_df['Current']*100/current,2)
  tmp_df['FTT'] = tmp_df['LTT']
  tmp_df.loc[tmp_df['Strategy'] == 'NTT', 'FTT'] = tmp_df['NTT']
  tmp_df['FTT%'] = tmp_df['LTT%']
  tmp_df.loc[tmp_df['Strategy'] == 'NTT', 'FTT%'] = tmp_df['NTT%']
  tmp_df['FTT Amt'] = round(tmp_df['FTT%'] * tmp_df['Current']/100,0)
  tmp_df['OTT%'] = round((tmp_df['FTT'] - tmp_df['AvgCost'])*100/tmp_df['AvgCost'],2)
  tmp_df['RRR Ind'] = round(tmp_df['Current P/L']/tmp_df['FTT Amt'],2)
  tmp_df['Risk Ind'] = round(tmp_df['Current P/L%']*tmp_df['CurrAlloc%'],0)

  return tmp_df

# function to print portfolio features
def print_portfolio_stats(df_portfolio_features, myinvmt_df):
  from pyxirr import xirr

  total_booked_amt, reserve_amt, cy_booked_amt, py_booked_amt = get_amt()

  dates = myinvmt_df['Date'].values
  dates = np.append(dates, datetime.date.today().strftime('%d-%b-%y'))
  investment = myinvmt_df['Investment'].values
  dates= pd.to_datetime(dates)

  current = round(sum(df_portfolio_features['Close']*df_portfolio_features['Shares']),0) + reserve_amt
  investment_xirr = np.append(investment, current)
  cagr = round(xirr(pd.DataFrame({"dates": dates, "amounts": investment_xirr}))*100,2)

  investment = -sum(investment)
  invested = round(sum(df_portfolio_features['AvgCost']*df_portfolio_features['Shares']),0) + reserve_amt
  previous = round(sum(df_portfolio_features['Prev_Close']*df_portfolio_features['Shares']),0) + reserve_amt
  cy_invested = investment + py_booked_amt

  today_pnl_amount = current-previous
  today_pnl_percentage = round((current-previous)*100/previous,2)

  curr_pnl_amount = current-invested
  curr_pnl_percentage = round((curr_pnl_amount)*100/(cy_invested),2)

  cy_pnl_amount = cy_booked_amt + curr_pnl_amount
  cy_pnl_percentage = round((cy_pnl_amount)*100/cy_invested,2)

  overall_pnl_amount = total_booked_amt + curr_pnl_amount
  overall_pnl_percentage = round((overall_pnl_amount)*100/investment,2)

  estimate_st = round(sum(df_portfolio_features['FTT']*df_portfolio_features['Shares']),0)  + reserve_amt
  est_st_pnl_amount = estimate_st-current
  est_st_pnl_percentage = round((est_st_pnl_amount)*100/current,2)

  estimate_lt = round(sum(df_portfolio_features['LTT']*df_portfolio_features['Shares']),0)  + reserve_amt
  est_lt_pnl_amount = estimate_lt-current
  est_lt_pnl_percentage = round((est_lt_pnl_amount)*100/current,2)

  total_profit = round(sum(df_portfolio_features[df_portfolio_features['Current P/L%'] > 0]['Current']) - sum(df_portfolio_features[df_portfolio_features['Current P/L%'] > 0]['Investment']),0)
  total_loss = round(sum(df_portfolio_features[df_portfolio_features['Current P/L%'] < 0]['Current']) - sum(df_portfolio_features[df_portfolio_features['Current P/L%'] < 0]['Investment']),0)

  cy_booked_percentage = round((cy_booked_amt)*100/current,2)
  py_booked_percentage = round((py_booked_amt)*100/investment,2)
  total_booked_percentage = round((total_booked_amt)*100/investment,2)

  print('-------------------')
  print('Initial Investment: ', format_amt(investment))
  print('CY Investment: ', format_amt(cy_invested))
  print('Reserve: ', format_amt(reserve_amt))
  print('Current: ',  format_amt(current))
  print('-------------------')
  print('Today PnL: '+ '{} ({}%)'.format(format_amt(today_pnl_amount), today_pnl_percentage))
  print('Current PnL: '+ '{} ({}%)'.format(format_amt(curr_pnl_amount), curr_pnl_percentage))
  print('CY Booked + Current PnL: '+ '{} ({}%)'.format(format_amt(cy_pnl_amount), cy_pnl_percentage))
  print('-------------------')
  print('Total profit: ', format_amt(total_profit))
  print('Total loss: ', format_amt(total_loss))
  print('-------------------')
  print('Total Booked + Current PnL: '+ '{} ({}%)'.format(format_amt(overall_pnl_amount), overall_pnl_percentage))
  print('Total Booked PnL: '+ '{} ({}%)'.format(format_amt(total_booked_amt), total_booked_percentage))
  print('Curr Year Booked PnL: '+ '{} ({}%)'.format(format_amt(cy_booked_amt), cy_booked_percentage))
  print('Prev Year Booked PnL: '+ '{} ({}%)'.format(format_amt(py_booked_amt), py_booked_percentage))
  print('===================')
  print('Est FTT: ',  format_amt(estimate_st))
  print('Est FTT PnL: '+ '{} ({}%)'.format(format_amt(est_st_pnl_amount), est_st_pnl_percentage))

  print('===================')
  print('Deployed: ', format_amt(investment))

  print('Current: ', format_amt(current))

  print('CAGR/XIRR %: '+'{}%'.format(cagr))

In [8]:
# get start and end date
start_date, end_date = get_start_end_date()

# get portfolio and prospects data
mypfs_df = get_mypfs_df()
mypps_df = get_mypps_df()
myinvmt_df = get_myinvmt_df()

# merge above datasets
mypf_df = pd.merge(mypfs_df, mypps_df, on="Symbol")

# seggregate dm and sv portfolio
dm_pf = mypf_df[mypf_df['InPortfolio'] == 'DM']
sv_pf = mypf_df[mypf_df['InPortfolio'] == 'SV']

# build portfolio stock dataframe
dm_stocks = get_stock_ids(dm_pf)
sv_stocks = get_stock_ids(sv_pf)
df_stocks = pd.concat([dm_pf,sv_pf], ignore_index = True)

# arrange common and diff stock features
common_cols = ['Symbol', 'Target', 'Criteria', 'Strategy', 'CumlRnk', 'LatestQtr', 'StarStock', 'Conviction', 'Category', 'InFolio', 'XIRR', 'MBQ']
diff_cols = ['Symbol', 'AvgCost', 'Shares']
df_stocks = arrange_features(df_stocks, common_cols, diff_cols)

# get common features
stock_ids = df_stocks['Symbol'].values
df_common_features = get_common_features(stock_ids, df_stocks)

df_common_features.reset_index(drop=True, inplace=True)
df_common_features.drop(['Date'], axis=1, inplace=True)
# get and print portfolio features
df_portfolio_features = get_portfolio_features(df_common_features)

print_portfolio_stats(df_portfolio_features, myinvmt_df)

df = df_portfolio_features
#plot_pie_chart(df, 'CapType', 'Current')
list_ox40n = list(df[df['MBQ'].str.contains('OX40N', na=False)]['Symbol'].values)

Run date time (IST): 2026-03-25 12:15:10
-------------------
qualified stocks: 86
with latest results: 26
still star stocks: 16
-------------------
Initial Investment:  1.36 C
CY Investment:  1.62 C
Reserve:  1.61 K
Current:  1.32 C
-------------------
Today PnL: 3.27 L (2.53%)
Current PnL: -44.77 L (-27.55%)
CY Booked + Current PnL: -28.88 L (-17.78%)
-------------------
Total profit:  58.43 K
Total loss:  -45.36 L
-------------------
Total Booked + Current PnL: -1.90 L (-1.4%)
Total Booked PnL: 42.87 L (31.64%)
Curr Year Booked PnL: 15.89 L (12.01%)
Prev Year Booked PnL: 26.98 L (19.91%)
===================
Est FTT:  2.48 C
Est FTT PnL: 1.16 C (87.29%)
===================
Deployed:  1.36 C
Current:  1.32 C
CAGR/XIRR %: -1.16%

In [9]:
# top 5 near their targets
cols = ['Symbol', 'Today P/L%', 'Current P/L%', 'FTT%', 'OTT%', 'FTT Amt', 'Current P/L', 'Current', 'FTT', 'Dev%_PE', 'RSI_14','Conviction', 'Spread%',  'CumlRnk', 'RRR Ind', 'CurrAlloc%', 'Gained%', 'Criteria', 'Strategy', 'Category']
df_tmp = df_portfolio_features[~df_portfolio_features['Symbol'].isin(['ENRIN','BLUSPRING','DIGITIDE'])]
df_tmp = df_tmp.sort_values(by = 'FTT Amt', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
50,MASFIN,1.46,-7.46,31.36,21.57,28436.0,-7305.0,90675.0,397.04,-20.05,46.0,H-SC,2.86,167.0,-0.26,0.69,23.68,XR,ATH,FINANCE
77,TTKPRESTIG,1.01,-42.41,73.81,0.09,42834.0,-42744.0,58033.0,770.00,34.69,35.0,M-SC,19.98,250.0,-1.00,0.44,1.01,OX40N,NTT,DURABLES
2,ABBOTINDIA,0.39,-9.74,30.81,18.07,49737.0,-17425.0,161430.0,35195.00,-23.22,51.0,X-MC,10.44,58.0,-0.35,1.22,5.57,X40,ATH,PHARMA
67,SONACOMS,4.42,-10.64,55.65,39.09,50305.0,-10763.0,90396.0,804.02,-29.25,53.0,M-MC,7.32,193.0,-0.21,0.68,27.88,AR,ATH,AUTO
37,ICICIGI,2.29,-6.25,27.30,19.34,51215.0,-12510.0,187599.0,2252.93,-21.06,37.0,X-MC,4.03,66.0,-0.24,1.42,3.70,X40,ATH,INSURANCE

In [10]:
# top 5 today
df_tmp = df_portfolio_features.sort_values(by = 'Today P/L%', ascending=False)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
56,RAJOOENG,7.14,-46.87,162.76,39.61,88639.0,-48040.0,54460.0,143.1,-64.09,39.0,H-SC,32.21,136.0,-0.54,0.41,7.14,AR,ATH,MISC
25,EASEMYTRIP,6.48,-61.04,273.94,45.70,188720.0,-107924.0,68891.0,26.4,-28.52,46.0,M-SC,8.92,204.0,-0.57,0.52,13.50,XY24,NTT,TRAVEL
51,MEDANTA,6.13,-11.59,43.78,27.12,68322.0,-20459.0,156058.0,1486.0,-14.24,42.0,X-SC,12.71,87.0,-0.30,1.18,6.59,XY24,NTT,HEALTHCARE
16,CAMPUS,5.67,-20.62,67.91,33.28,90438.0,-34601.0,133174.0,393.0,-36.03,43.0,M-SC,10.95,218.0,-0.38,1.01,6.80,XY24,NTT,FOOTWEAR
41,INDIGOPNTS,5.56,-45.27,82.74,0.02,79051.0,-79017.0,95542.0,1408.0,45.65,32.0,M-SC,25.09,222.0,-1.00,0.72,8.07,OX40N,NTT,PAINTS

In [11]:
# bottom 5 today
df_tmp = df_portfolio_features.sort_values(by = 'Today P/L%', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
4,ALKYLAMINE,-1.64,-40.74,226.72,93.63,135656.0,-41129.0,59834.0,4546.37,-36.55,50.0,H-SC,25.92,142.0,-0.30,0.45,12.27,SR,ATH,CHEMICALS
78,UNITDSPR,-1.25,-3.67,25.36,20.77,57202.0,-8583.0,225561.0,1644.00,-14.48,45.0,X-MC,1.95,64.0,-0.15,1.70,2.84,X40N,NTT,BREWERIES
76,TRIDENT,-0.75,-32.48,90.33,28.51,56269.0,-29962.0,62293.0,48.00,-13.20,54.0,M-SC,14.11,223.0,-0.53,0.47,14.32,XR,NTT,TEXTILES
66,SIS,-0.52,-35.79,88.84,21.26,63341.0,-39734.0,71298.0,528.00,1666.84,42.0,H-SC,14.42,168.0,-0.63,0.54,6.01,OX40N,NTT,MISC
49,LAOPALA,0.32,-45.53,155.35,39.09,110939.0,-59693.0,71412.0,464.00,55.93,38.0,H-SC,15.69,154.0,-0.54,0.54,2.58,AR,NTT,CERAMICS

In [12]:
# top 5 to exit based on CumlRnk
df_tmp = df_portfolio_features[~df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])]
df_tmp = df_tmp[(df_tmp['Current P/L%'] > -1) & (df_tmp['Current P/L%'] < 1)].sort_values(by = 'CumlRnk', ascending=False)
df_tmp[cols].head()

Empty DataFrame
Columns: [Symbol, Today P/L%, Current P/L%, FTT%, OTT%, FTT Amt, Current P/L, Current, FTT, Dev%_PE, RSI_14, Conviction, Spread%, CumlRnk, RRR Ind, CurrAlloc%, Gained%, Criteria, Strategy, Category]
Index: []

In [13]:
# OX40N stocks to exit
df_tmp = df_portfolio_features[(df_portfolio_features['Symbol'].isin(list_ox40n))].sort_values(by = 'Current P/L%', ascending=False)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
26,FINCABLES,2.51,5.85,96.43,107.91,150697.0,8632.0,156276.0,1641.55,-4.62,48.0,M-SC,8.14,220.0,0.06,1.18,17.57,OX40N,ATH,CABLES
66,SIS,-0.52,-35.79,88.84,21.26,63341.0,-39734.0,71298.0,528.00,1666.84,42.0,H-SC,14.42,168.0,-0.63,0.54,6.01,OX40N,NTT,MISC
18,CERA,1.36,-37.70,98.85,23.89,108330.0,-66313.0,109590.0,9475.00,-39.86,48.0,H-SC,19.03,153.0,-0.61,0.83,5.32,OX40N,NTT,CERAMICS
72,TATAELXSI,1.56,-38.82,115.80,32.03,93403.0,-51176.0,80659.0,9161.00,-23.56,41.0,H-SC,21.02,158.0,-0.55,0.61,5.10,OX40N,NTT,IT
77,TTKPRESTIG,1.01,-42.41,73.81,0.09,42834.0,-42744.0,58033.0,770.00,34.69,35.0,M-SC,19.98,250.0,-1.00,0.44,1.01,OX40N,NTT,DURABLES

In [14]:
# top 5 to book for rotation
df_tmp = df_portfolio_features[(df_portfolio_features['Current P/L%'] > 20) ].sort_values(by = 'CumlRnk', ascending=False)
df_tmp[cols].head()

Empty DataFrame
Columns: [Symbol, Today P/L%, Current P/L%, FTT%, OTT%, FTT Amt, Current P/L, Current, FTT, Dev%_PE, RSI_14, Conviction, Spread%, CumlRnk, RRR Ind, CurrAlloc%, Gained%, Criteria, Strategy, Category]
Index: []

In [15]:
# top 5 to monitor for exit
df_tmp = df_portfolio_features[~df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])]
df_tmp = df_tmp[(df_tmp['Current P/L%'] > 0) ].sort_values(by = 'Dev%_PE', ascending=False)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
26,FINCABLES,2.51,5.85,96.43,107.91,150697.0,8632.0,156276.0,1641.55,-4.62,48.0,M-SC,8.14,220.0,0.06,1.18,17.57,OX40N,ATH,CABLES
1,ABB,1.27,14.49,27.15,45.57,81320.0,37901.0,299520.0,7934.00,-26.39,56.0,H-MC,13.44,125.0,0.47,2.26,33.01,AR,NTT,ELECTRICAL

In [16]:
# top 5 to book for rotation from weak conviction
df_tmp = df_portfolio_features[~df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])]
df_tmp = df_tmp[~df_tmp['Criteria'].isin(['XY25','XY24','X40', 'X40N'])].sort_values(by = 'RRR Ind', ascending=False)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
1,ABB,1.27,14.49,27.15,45.57,81320.0,37901.0,299520.0,7934.00,-26.39,56.0,H-MC,13.44,125.0,0.47,2.26,33.01,AR,NTT,ELECTRICAL
26,FINCABLES,2.51,5.85,96.43,107.91,150697.0,8632.0,156276.0,1641.55,-4.62,48.0,M-SC,8.14,220.0,0.06,1.18,17.57,OX40N,ATH,CABLES
40,INDIAMART,3.50,-12.65,136.67,106.72,147232.0,-15608.0,107728.0,4810.62,-60.55,41.0,H-SC,11.95,140.0,-0.11,0.81,7.76,AR,ATH,MISC
85,ZYDUSLIFE,2.47,-4.22,41.60,35.63,83505.0,-8840.0,200734.0,1286.17,-16.67,52.0,H-MC,5.38,120.0,-0.11,1.52,11.75,AR,ATH,PHARMA
67,SONACOMS,4.42,-10.64,55.65,39.09,50305.0,-10763.0,90396.0,804.02,-29.25,53.0,M-MC,7.32,193.0,-0.21,0.68,27.88,AR,ATH,AUTO

In [17]:
# top 5 to accumulate based on lowest RSI_14
df_tmp = df_portfolio_features[df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])].sort_values(by = 'RSI_14', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
53,PGHH,1.42,-27.83,82.92,32.01,127776.0,-59424.0,154096.0,17616.87,-51.15,20.0,X-MC,16.46,57.0,-0.47,1.16,1.85,X40,ATH,FMCG
58,RELAXO,4.26,-65.10,336.36,52.31,170420.0,-94494.0,50666.0,1176.00,-62.83,29.0,X-SC,27.40,92.0,-0.55,0.38,5.75,X40N,NTT,FOOTWEAR
38,ICICIPRULI,2.34,-8.97,43.61,30.73,78207.0,-17672.0,179333.0,790.00,-33.41,30.0,X-MC,4.90,78.0,-0.23,1.36,3.55,X40,ATH,INSURANCE
12,BATAINDIA,3.08,-57.44,217.70,35.20,119210.0,-73911.0,54759.0,2096.00,-28.23,31.0,X-SC,31.75,91.0,-0.62,0.41,5.43,X40,NTT,FOOTWEAR
73,TCS,0.58,-29.17,78.71,26.57,258259.0,-135159.0,328114.0,4311.58,-40.02,32.0,X-LC,17.53,2.0,-0.52,2.48,2.40,X40,ATH,IT

In [18]:
# top 5 to accumulate based on Spread and CumlRnk
df_tmp = df_portfolio_features[df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])]
df_tmp = df_tmp[(df_tmp['CumlRnk'] < 100)].sort_values(by = 'Spread%', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
78,UNITDSPR,-1.25,-3.67,25.36,20.77,57202.0,-8583.0,225561.0,1644.00,-14.48,45.0,X-MC,1.95,64.0,-0.15,1.70,2.84,X40N,NTT,BREWERIES
65,SIEMENS,3.36,-16.64,50.56,25.51,78436.0,-30960.0,155135.0,4671.50,30.24,46.0,H-LC,2.34,51.0,-0.39,1.17,14.24,AR,ATH,ELECTRICAL
59,RELIANCE,0.91,-8.55,37.01,25.30,68019.0,-17177.0,183786.0,1952.00,-10.80,54.0,X-LC,3.47,21.0,-0.25,1.39,22.71,XY25,BTT,REFINERIES
82,VOLTAS,4.26,6.21,36.71,45.20,74756.0,11898.0,203640.0,1856.00,21.54,43.0,X-MC,3.54,79.0,0.16,1.54,13.42,XY25,NTT,AC
37,ICICIGI,2.29,-6.25,27.30,19.34,51215.0,-12510.0,187599.0,2252.93,-21.06,37.0,X-MC,4.03,66.0,-0.24,1.42,3.70,X40,ATH,INSURANCE

In [19]:
# top 5 to accumulate based on lowest Gained%
df_tmp = df_portfolio_features[df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])].sort_values(by = 'Gained%', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
53,PGHH,1.42,-27.83,82.92,32.01,127776.0,-59424.0,154096.0,17616.87,-51.15,20.0,X-MC,16.46,57.0,-0.47,1.16,1.85,X40,ATH,FMCG
9,BAJAJHFL,1.57,-28.55,126.90,62.13,247577.0,-77950.0,195096.0,181.50,-41.28,33.0,X-MC,20.77,60.0,-0.31,1.47,1.89,X40N,ATH,FINANCE
73,TCS,0.58,-29.17,78.71,26.57,258259.0,-135159.0,328114.0,4311.58,-40.02,32.0,X-LC,17.53,2.0,-0.52,2.48,2.40,X40,ATH,IT
45,ITC,2.20,-21.60,51.86,19.06,138308.0,-73472.0,266694.0,452.00,-57.14,39.0,X-LC,18.78,1.0,-0.53,2.02,2.48,X40,NTT,FMCG
78,UNITDSPR,-1.25,-3.67,25.36,20.77,57202.0,-8583.0,225561.0,1644.00,-14.48,45.0,X-MC,1.95,64.0,-0.15,1.70,2.84,X40N,NTT,BREWERIES

In [20]:
# top 5 to accumulate based on lowest CurrAlloc%
df_tmp = df_portfolio_features[df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])].sort_values(by = 'CurrAlloc%', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
58,RELAXO,4.26,-65.10,336.36,52.31,170420.0,-94494.0,50666.0,1176.00,-62.83,29.0,X-SC,27.40,92.0,-0.55,0.38,5.75,X40N,NTT,FOOTWEAR
12,BATAINDIA,3.08,-57.44,217.70,35.20,119210.0,-73911.0,54759.0,2096.00,-28.23,31.0,X-SC,31.75,91.0,-0.62,0.41,5.43,X40,NTT,FOOTWEAR
54,QUESS,1.45,-27.00,138.20,73.90,107746.0,-28829.0,77964.0,424.00,-60.88,41.0,X-SC,21.59,80.0,-0.27,0.59,4.79,XY24,NTT,MISC
36,HONAUT,2.01,-26.89,106.98,51.31,150815.0,-51863.0,140975.0,58357.33,-39.27,34.0,X-SC,16.19,90.0,-0.34,1.07,3.60,X40N,ATH,ELECTRICAL
53,PGHH,1.42,-27.83,82.92,32.01,127776.0,-59424.0,154096.0,17616.87,-51.15,20.0,X-MC,16.46,57.0,-0.47,1.16,1.85,X40,ATH,FMCG

In [21]:
# top 5 to accumulate based on CumlRnk
df_tmp = df_portfolio_features.sort_values(by = 'CumlRnk', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
45,ITC,2.20,-21.60,51.86,19.06,138308.0,-73472.0,266694.0,452.00,-57.14,39.0,X-LC,18.78,1.0,-0.53,2.02,2.48,X40,NTT,FMCG
73,TCS,0.58,-29.17,78.71,26.57,258259.0,-135159.0,328114.0,4311.58,-40.02,32.0,X-LC,17.53,2.0,-0.52,2.48,2.40,X40,ATH,IT
43,INFY,1.71,-12.98,54.27,34.24,147765.0,-40610.0,272278.0,1972.00,-31.42,42.0,X-LC,15.19,3.0,-0.27,2.06,4.71,X40,NTT,IT
75,TMPV,2.81,-27.17,87.53,36.58,226843.0,-96681.0,259160.0,600.00,-84.72,41.0,X-LC,7.49,4.0,-0.43,1.96,4.82,XY24,NTT,AUTO
33,HCLTECH,2.00,-9.10,36.23,23.83,79673.0,-22014.0,219910.0,1908.19,-4.47,51.0,X-LC,11.59,8.0,-0.28,1.66,6.78,X40,ATH,IT

In [22]:
# top 5 for average up
df_tmp = df_portfolio_features[(df_portfolio_features['Dev%_200'] > 5)].sort_values(by = 'CurrAlloc%', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
67,SONACOMS,4.42,-10.64,55.65,39.09,50305.0,-10763.0,90396.0,804.02,-29.25,53.0,M-MC,7.32,193.0,-0.21,0.68,27.88,AR,ATH,AUTO
1,ABB,1.27,14.49,27.15,45.57,81320.0,37901.0,299520.0,7934.00,-26.39,56.0,H-MC,13.44,125.0,0.47,2.26,33.01,AR,NTT,ELECTRICAL

In [23]:
# top 5 RSP
df_tmp = df_portfolio_features.sort_values(by = 'RSP', ascending=False)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
30,HAPPSTMNDS,1.33,-49.48,265.88,84.85,172163.0,-63413.0,64752.0,1480.71,-39.93,56.0,H-SC,26.08,152.0,-0.37,0.49,19.91,AR,ATH,IT
69,SURYODAY,4.89,-25.00,64.05,23.03,86021.0,-44768.0,134303.0,216.00,46.93,54.0,H-SC,5.78,166.0,-0.52,1.01,31.26,XR,NTT,BANKS
52,PAGEIND,3.87,-12.85,53.88,34.11,126028.0,-34474.0,233905.0,51418.65,-37.45,59.0,X-MC,20.99,55.0,-0.27,1.77,10.65,X40,ATH,APPARELS
59,RELIANCE,0.91,-8.55,37.01,25.30,68019.0,-17177.0,183786.0,1952.00,-10.80,54.0,X-LC,3.47,21.0,-0.25,1.39,22.71,XY25,BTT,REFINERIES
2,ABBOTINDIA,0.39,-9.74,30.81,18.07,49737.0,-17425.0,161430.0,35195.00,-23.22,51.0,X-MC,10.44,58.0,-0.35,1.22,5.57,X40,ATH,PHARMA

In [24]:
# Top N allocation
df_tmp = df_portfolio_features.sort_values(by = 'CurrAlloc%', ascending=False)
top_n_values = [10, 25, 50]

sum_df = pd.DataFrame({
    'Top_N': top_n_values,
    'Sum_Alloc%': [df_tmp['CurrAlloc%'].head(n).sum() for n in top_n_values]
})

sum_df

   Top_N  Sum_Alloc%
0     10       20.74
1     25       45.96
2     50       78.22

In [25]:
# market-cap-wise allocation
df_tmp = df_portfolio_features[cols]
df_tmp.groupby(df_tmp['Conviction'].str[-2:])['CurrAlloc%'].sum().sort_values(ascending=False)

Conviction
SC    44.36
MC    30.11
LC    25.58
Name: CurrAlloc%, dtype: float64

In [26]:
# criteria-wise allocation
df_portfolio_features.groupby('Criteria')['CurrAlloc%'].sum().sort_values(ascending=False)

Criteria
XY24     27.12
X40      25.46
X40N     15.21
AR        9.17
XR        8.29
XY25      7.36
OX40N     6.63
SR        0.81
Name: CurrAlloc%, dtype: float64

In [27]:
# conviction-wise allocation
df_portfolio_features.groupby('Conviction')['CurrAlloc%'].sum().sort_values(ascending=False)

Conviction
X-LC    23.41
X-MC    22.63
H-SC    21.54
X-SC    12.30
M-SC     9.99
H-MC     5.08
M-MC     2.04
H-LC     1.17
M-LC     1.00
L-SC     0.53
L-MC     0.36
Name: CurrAlloc%, dtype: float64

In [28]:
# sector-wise stats
df_tmp = df_portfolio_features.groupby('Category')[['CurrAlloc%', 'Current', 'Current P/L', 'FTT Amt']].sum().sort_values(by=['Current', 'Current P/L'], ascending=False)
df_tmp['Current P/L%'] = round(df_tmp['Current P/L'] * 100 / df_tmp['Current'], 2)
df_tmp['FTT%'] = round(df_tmp['FTT Amt'] * 100 / df_tmp['Current'], 2)
cols = ['CurrAlloc%', 'Current P/L%', 'FTT%']
df_tmp[cols].sort_values(by=['CurrAlloc%'], ascending=False)

               CurrAlloc%  Current P/L%    FTT%
Category
FMCG                15.11        -24.89   69.24
FINANCE             13.08        -24.21   74.83
IT                  11.81        -44.29  117.72
MISC                 6.92        -46.53  110.19
ELECTRICAL           6.54        -11.97   54.84
PAINTS               5.17        -44.02   69.03
INSURANCE            4.68         -9.60   47.11
BANKS                4.62        -25.90   89.81
PHARMA               4.15         -6.98   40.65
AUTO                 3.73        -32.39   84.92
AC                   2.06        -17.30   49.10
HEALTHCARE           1.91        -41.84   78.86
TRAVEL               1.82        -86.02  179.17
FOOTWEAR             1.80        -85.08  159.29
APPARELS             1.77        -14.74   53.88
DURABLES             1.74        -68.61  109.63
BREWERIES            1.70         -3.81   25.36
REALTY               1.47        -13.88   32.58
REFINERIES           1.39         -9.35   37.01
CERAMICS             1.37        -69.62  121.14
CEMENT               1.25        -62.50  184.07
CABLES               1.18          5.52   96.43
ENGINEERING          1.10        -67.05  143.45
CHEMICALS            1.07        -87.34  240.17
JEWELLERY            1.03       -135.42  217.22
ENTERTAINMENT        0.76        -92.05  206.59
TEXTILES             0.47        -48.10   90.33
HOTELS               0.35       -147.45  234.73

In [29]:
# money to be made criteria-wise
df_portfolio_features.groupby('Criteria')['FTT Amt'].agg(['sum', 'count']).sort_values(by='sum', ascending=False)

                sum  count
Criteria
XY24      4012084.0     21
X40       1805266.0     16
XR        1396503.0     12
AR        1357571.0     10
X40N      1286757.0     10
OX40N      916206.0     10
XY25       466593.0      5
SR         312079.0      2

In [30]:
# money to be made conviction-wise
df_portfolio_features.groupby('Conviction')['FTT Amt'].agg(['sum', 'count']).sort_values(by='sum', ascending=False)

                  sum  count
Conviction
H-SC        3945935.0     24
X-MC        1737752.0     15
X-LC        1679791.0     13
M-SC        1598057.0     14
X-SC        1554641.0     10
H-MC         406950.0      3
L-SC         221382.0      2
M-LC         159574.0      1
M-MC         115090.0      2
H-LC          78436.0      1
L-MC          55451.0      1

In [31]:
# money to be made criteria and conviction-wise
df_portfolio_features.groupby(['Conviction', 'Criteria'])['FTT Amt'].agg(['sum', 'count']).sort_values(by='sum', ascending=False)

                           sum  count
Conviction Criteria
H-SC       XY24      1367991.0      6
           AR         986036.0      5
M-SC       XY24       923615.0      6
X-LC       X40        904682.0      7
H-SC       XR         882659.0      7
X-SC       XY24       842169.0      4
X-MC       X40        686851.0      7
           X40N       529474.0      4
X-SC       X40N       498739.0      4
M-SC       OX40N      405367.0      5
H-SC       OX40N      397170.0      4
X-LC       XY24       371422.0      2
H-SC       SR         312079.0      2
X-MC       XY24       264762.0      2
X-LC       X40N       258544.0      2
X-MC       XY25       256665.0      2
H-MC       XY24       242125.0      1
X-SC       X40        213733.0      2
M-SC       XR         191106.0      2
H-MC       AR         164825.0      2
M-LC       XR         159574.0      1
X-LC       XY25       145143.0      2
L-SC       OX40N      113669.0      1
           XR         107713.0      1
H-LC       AR          78436.0      1
M-SC       AR          77969.0      1
M-MC       XY25        64785.0      1
L-MC       XR          55451.0      1
M-MC       AR          50305.0      1

In [32]:
# notebook execution time

end_time = time.time()
execution_time = round(end_time - start_time, 0)
print(f"Notebook execution time: {execution_time} seconds")

Notebook execution time: 56.0 seconds