<a href="https://colab.research.google.com/github/ankit-rathi/Quantvesting_v2/blob/main/myStocks_Portfolio_Analysis.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
'''
!pip install pandas==2.2.2 -qq
!pip install pyxirr -qq
!pip install ta -qq
!pip install yfinance==0.2.59 -qq
'''

'\n!pip install pandas==2.2.2 -qq\n!pip install pyxirr -qq\n!pip install ta -qq\n!pip install yfinance==0.2.59 -qq\n'

In [2]:
# import libraries

import numpy as np
import pandas as pd
import datetime
import warnings
warnings.filterwarnings('ignore')
import yfinance as yfin
import ta
import matplotlib.pyplot as plt
import requests

In [3]:
# notebook start time
import time
import datetime
import pytz

start_time = time.time()

# function to print date timestamp
def print_date_time():
  tz_NY = pytz.timezone('Asia/Kolkata')
  datetime_NY = datetime.datetime.now(tz_NY)
  print("Run date time (IST):", datetime_NY.strftime("%Y-%m-%d %H:%M:%S"))

In [4]:
# function to get booked and reserved amount
def get_amt():
  # fetch the JSON data from the URL
  url = "https://raw.githubusercontent.com/ankit-rathi/Tradevesting_v1/main/data/myPortfolioAmts.json"
  response = requests.get(url)
  pf_amts = response.json()  # parse the JSON data

  # extract values from the JSON
  py_booked_amt_dm = pf_amts["py_booked_amt_dm"]
  py_booked_amt_sv = pf_amts["py_booked_amt_sv"]
  cy_booked_amt_dm = pf_amts["cy_booked_amt_dm"]
  cy_booked_amt_sv = pf_amts["cy_booked_amt_sv"]
  reserve_amt_dm = pf_amts["reserve_amt_dm"]
  reserve_amt_sv = pf_amts["reserve_amt_sv"]

  # perform calculations
  py_booked_amt = py_booked_amt_dm + py_booked_amt_sv
  cy_booked_amt = cy_booked_amt_dm + cy_booked_amt_sv
  reserve_amt = reserve_amt_dm + reserve_amt_sv
  total_booked_amt = py_booked_amt + cy_booked_amt

  return total_booked_amt, reserve_amt, cy_booked_amt, py_booked_amt

gen_output = 0

In [5]:
# function to format the amount
def format_amt(number):
    abs_number = abs(number)

    if abs_number >= 1_00_00_000:  # Crores
        formatted_amt = f"{number / 1_00_00_000:.2f} C"
    elif abs_number >= 1_00_000:  # Lakhs
        formatted_amt = f"{number / 1_00_000:.2f} L"
    elif abs_number >= 1_000:  # Thousands
        formatted_amt = f"{number / 1_000:.2f} K"
    else:
        formatted_amt = f"{number:.2f}"

    return formatted_amt

# function to set start and end date
def get_start_end_date():
  start_date = (datetime.date.today() + datetime.timedelta(days=-365)).strftime('%Y-%m-%d')
  end_date = (datetime.date.today() + datetime.timedelta(days=1)).strftime('%Y-%m-%d')
  return start_date, end_date

# function to fetch my portfolio csv
def get_mypfs_df():
  mypfs_df = pd.read_csv('https://raw.githubusercontent.com/ankit-rathi/Tradevesting_v1/main/data/myPortfolioStocks.csv')
  return mypfs_df

# function to fetch my prospects csv
def get_mypps_df():
  mypps_df = pd.read_csv('https://raw.githubusercontent.com/ankit-rathi/Tradevesting_v1/main/data/myProspectsScrips.csv')
  return mypps_df

# function to fetch screener data
def get_myscreen_df():
  myscreen_df = pd.read_csv('https://raw.githubusercontent.com/ankit-rathi/Tradevesting_v1/main/data/myScreenerDB.csv')
  return myscreen_df

# function to fetch momentum data
def get_myinvmt_df():
  myinvmt_df = pd.read_csv('https://raw.githubusercontent.com/ankit-rathi/Tradevesting_v1/main/data/myInvestments.csv')
  return myinvmt_df

# function to get the stock ids
def get_stock_ids(df_pf):
  stock_n100 = df_pf['Symbol'].unique()

  exclude = ['CADILAHC','MMTC', 'MASFIN']

  stock_ids = df_pf[~df_pf['Symbol'].isin(exclude) ]['Symbol'].unique()

  #mypf = mypf[mypf.Forecast.notnull()]
  #stock_ids = mypf['Symbol'].unique()

  #stock_ids.sort()
  return stock_ids

# get features from screener data
def get_screener_features():
  myscreen_df = get_myscreen_df()
  cols = ['Symbol', 'EPS', 'MedPE', 'ROCE%', 'ROE%', 'CapType']
  return myscreen_df[cols]

# get relative strength
def get_relative_strength(stock_list):

    # Dictionary to store stock tickers and their corresponding percentage price change
    stock_changes = {}

    # Loop through each stock and fetch its price data
    for stock in stock_list:
        try:
            # Download the stock data for the given date range
            stock_data = yfin.Ticker(stock + '.NS').history(period='1mo', interval='1d')[map(str.title, ['open', 'close', 'low', 'high', 'volume'])]

            # Calculate the percentage change for the stock
            if len(stock_data) > 0:
                start_price = stock_data['Close'].iloc[0]
                end_price = stock_data['Close'].iloc[-1]
                percent_change = round(((end_price - start_price) / start_price) * 100, 2)
                stock_changes[stock] = percent_change
            else:
                stock_changes[stock] = np.nan  # If no data is available, set to NaN

        except Exception as e:
            print(f"Error fetching data for {stock}: {e}")
            stock_changes[stock] = np.nan

    # Create a DataFrame with stock tickers and their percentage changes
    df = pd.DataFrame(list(stock_changes.items()), columns=['Symbol', 'Percent_Change'])

    # Drop any stocks with missing data (NaN values)
    df = df.dropna()

    # Calculate the percentile rank based on percentage change
    df['RSP'] = round(df['Percent_Change'].rank(pct=True) * 100, 2)
    cols = ['Symbol', 'RSP']
    df = df[cols]
    # Sort by percentile rank (optional)
    df = df.sort_values(by='RSP', ascending=False).reset_index(drop=True)

    return df

In [6]:
# function to get stock technicals
def stock_prec_dev(stock_symbol):
    #stock_symbol = 'ULTRACEMCO.NS'
    short_window = 20
    mid_window = 50
    long_window = 200
    moving_avg = 'SMA'

    start = datetime.datetime(*map(int, start_date.split('-')))
    end = datetime.datetime(*map(int, end_date.split('-')))

    stock_df = yfin.Ticker(stock_symbol + '.NS').history(period='max', interval='1d')[map(str.title, ['open', 'close', 'low', 'high', 'volume'])]

    stock_df['Max'] = round(max(stock_df['Close']),2)
    stock_df = stock_df[(stock_df.index <= end_date) & (stock_df.index >= start_date)]
    stock_df['200_SMA'] = round(stock_df['Close'].rolling(window = 200, min_periods = 1).mean(),0)
    stock_df['Dev%_200'] = round((stock_df['Close'] - stock_df['200_SMA'])*100/stock_df['200_SMA'],2)
    stock_df.dropna(axis = 0, inplace = True) # remove any null rows

    stock_df['20_SMA'] = stock_df['Close'].rolling(window=20).mean()
    stock_df['50_SMA'] = stock_df['Close'].rolling(window=50).mean()
    stock_df['Symbol'] = stock_symbol

    stock_df['Close'] = round(stock_df['Close'],2)
    stock_df['Min'] = round(min(stock_df['Close']),2)
    stock_df['RSI_14'] = ta.momentum.RSIIndicator(close=stock_df['Close'], window=14).rsi()
    stock_df['RSI_14'] = round(stock_df['RSI_14'],0)
    stock_df['Prev_Close'] = stock_df['Close'].shift(1)
    stock_df.drop(['Open', 'Low', 'High', 'Volume'], axis=1, inplace=True)
    stock_df = stock_df.tail(1)

    max_SMA = max(stock_df['20_SMA'].item(), stock_df['50_SMA'].item(), stock_df['200_SMA'].item())
    min_SMA = min(stock_df['20_SMA'].item(), stock_df['50_SMA'].item(), stock_df['200_SMA'].item())
    ABS_Spread = max_SMA - min_SMA
    stock_df['Spread%'] = round((ABS_Spread / stock_df['200_SMA'].item()) * 100,2)

    return stock_df

# function to compute stock attributes
def get_common_features(stock_ids, df_mypf):

  df_prec_dev = pd.DataFrame()
  df_tmp = get_screener_features()
  df_rs = get_relative_strength(stock_ids)

  for stock_id in stock_ids:
      tmp = stock_prec_dev(stock_id)
      tmp = tmp.reset_index()
      df_prec_dev = pd.concat([df_prec_dev, tmp], ignore_index = True)
  df_prec_dev = pd.merge(df_prec_dev, df_mypf, on= 'Symbol')
  df_prec_dev = pd.merge(df_prec_dev, df_tmp, on= 'Symbol', how='left')
  df_prec_dev = pd.merge(df_prec_dev, df_rs, on= 'Symbol', how='left')
  #print(df_prec_dev.columns)
  df_prec_dev['Curr_PE'] = round(df_prec_dev['Close']/df_prec_dev['EPS'],1)
  df_prec_dev['Dev%_PE'] = round((df_prec_dev['Curr_PE'] - df_prec_dev['MedPE'])*100/df_prec_dev['MedPE'],2)
  df_prec_dev['Conviction'] = df_prec_dev['Conviction'] + '-' + df_prec_dev['CapType']
  return df_prec_dev

# function to arrange stock features
def arrange_features(df_stocks, common_cols, diff_cols):
  df_stocks_common = df_stocks[common_cols].drop_duplicates()
  df_stocks_diff = df_stocks[diff_cols]
  df_stocks_diff['Investment'] = df_stocks_diff['AvgCost'] * df_stocks_diff['Shares']
  df_stocks_diff = df_stocks_diff.groupby(['Symbol'])[['Shares', 'Investment']].aggregate(['sum']).reset_index()
  df_stocks_diff.columns = ['Symbol', 'Shares', 'Investment']
  df_stocks_diff['AvgCost'] = round(df_stocks_diff['Investment']/df_stocks_diff['Shares'],2)
  df_stocks = pd.merge(df_stocks_diff, df_stocks_common, on='Symbol')
  return df_stocks

# plot fact distribution across dimension
def plot_pie_chart(df, dimension, fact):
  # grouping the data by category and calculating the sum of fact for each type
  grouped_data = df.groupby(dimension)[fact].sum()

  # sorting the grouped data in descending order
  grouped_data = grouped_data.sort_values(ascending=False)

  # creating a pie chart
  grouped_data.plot.pie(autopct='%1.1f%%', startangle=90, figsize=(6, 6))

  # adding a title and displaying the plot
  plt.title(f'{dimension} {fact} Distribution')
  plt.ylabel('')  # To hide the y-label
  plt.show()

In [7]:
# function to get portfolio features

def get_portfolio_features(df_common_features):

  print_date_time()
  print('-------------------')

  #df_common_features["Target"] = df_common_features["Target"].fillna(df_common_features["Max"])
  df_common_features['NTT'] = np.where(df_common_features['Strategy']== 'NTT', df_common_features["Target"], df_common_features['Max'])
  df_common_features['LTT'] = np.where(df_common_features['Strategy']== 'BTT', df_common_features["Target"], df_common_features['Max'])
  df_common_features['BOL'] = df_common_features['Min']

  tmp_df = df_common_features[df_common_features['Symbol'].isin(mypf_df[mypf_df['InPortfolio'] != 'NA'].Symbol.values)]
  print('qualified stocks: '+str(len(tmp_df['Symbol'].unique())))
  tmp_df1 = tmp_df[tmp_df['LatestQtr'] == 1]
  print('with latest results: '+str(len(tmp_df1['Symbol'].unique())))
  tmp_df1 = tmp_df1[tmp_df1['StarStock'] == 1]
  print('still star stocks: '+str(len(tmp_df1['Symbol'].unique())))
  tmp_df['Investment'] = tmp_df['AvgCost'] * tmp_df['Shares']
  tmp_df['Current'] = round(tmp_df['Close'] * tmp_df['Shares'],0)
  tmp_df['Previous'] = tmp_df['Prev_Close'] * tmp_df['Shares']
  tmp_df['EstimatedST'] = tmp_df['NTT'] * tmp_df['Shares']
  tmp_df['EstimatedLT'] = tmp_df['LTT'] * tmp_df['Shares']
  tmp_df['Current P/L'] = round((tmp_df['Current'] - tmp_df['Investment']),0)
  tmp_df['Today P/L%'] = round((tmp_df['Current'] - tmp_df['Previous'])*100/tmp_df['Previous'],2)
  tmp_df['Current P/L%'] = round((tmp_df['Current'] - tmp_df['Investment'])*100/tmp_df['Investment'],2)
  tmp_df['EstimatedST P/L%'] = round((tmp_df['EstimatedST'] - tmp_df['Investment'])*100/tmp_df['Investment'],2)
  tmp_df['EstimatedLT P/L%'] = round((tmp_df['EstimatedLT'] - tmp_df['Investment'])*100/tmp_df['Investment'],2)
  tmp_df['NTT%'] = round((tmp_df['NTT'] - tmp_df['Close'])*100/tmp_df['Close'],2)
  tmp_df['LTT%'] = round((tmp_df['LTT'] - tmp_df['Close'])*100/tmp_df['Close'],2)
  tmp_df['Gained%'] = round((tmp_df['Close'] - tmp_df['BOL'])*100/tmp_df['BOL'],2)
  investment = round(sum(tmp_df['AvgCost']*tmp_df['Shares']),0)
  current = round(sum(tmp_df['Close']*tmp_df['Shares']),0)
  tmp_df['InitAlloc%'] = round(tmp_df['Investment']*100/investment,2)
  tmp_df['CurrAlloc%'] = round(tmp_df['Current']*100/current,2)
  tmp_df['FTT'] = tmp_df['LTT']
  tmp_df.loc[tmp_df['Strategy'] == 'NTT', 'FTT'] = tmp_df['NTT']
  tmp_df['FTT%'] = tmp_df['LTT%']
  tmp_df.loc[tmp_df['Strategy'] == 'NTT', 'FTT%'] = tmp_df['NTT%']
  tmp_df['FTT Amt'] = round(tmp_df['FTT%'] * tmp_df['Current']/100,0)
  tmp_df['OTT%'] = round((tmp_df['FTT'] - tmp_df['AvgCost'])*100/tmp_df['AvgCost'],2)
  tmp_df['RRR Ind'] = round(tmp_df['Current P/L']/tmp_df['FTT Amt'],2)
  tmp_df['Risk Ind'] = round(tmp_df['Current P/L%']*tmp_df['CurrAlloc%'],0)

  return tmp_df

# function to print portfolio features
def print_portfolio_stats(df_portfolio_features, myinvmt_df):
  from pyxirr import xirr

  total_booked_amt, reserve_amt, cy_booked_amt, py_booked_amt = get_amt()

  dates = myinvmt_df['Date'].values
  dates = np.append(dates, datetime.date.today().strftime('%d-%b-%y'))
  investment = myinvmt_df['Investment'].values
  dates= pd.to_datetime(dates)

  current = round(sum(df_portfolio_features['Close']*df_portfolio_features['Shares']),0) + reserve_amt
  investment_xirr = np.append(investment, current)
  cagr = round(xirr(pd.DataFrame({"dates": dates, "amounts": investment_xirr}))*100,2)

  investment = -sum(investment)
  invested = round(sum(df_portfolio_features['AvgCost']*df_portfolio_features['Shares']),0) + reserve_amt
  previous = round(sum(df_portfolio_features['Prev_Close']*df_portfolio_features['Shares']),0) + reserve_amt
  cy_invested = investment + py_booked_amt

  today_pnl_amount = current-previous
  today_pnl_percentage = round((current-previous)*100/previous,2)

  curr_pnl_amount = current-invested
  curr_pnl_percentage = round((curr_pnl_amount)*100/(cy_invested),2)

  cy_pnl_amount = cy_booked_amt + curr_pnl_amount
  cy_pnl_percentage = round((cy_pnl_amount)*100/cy_invested,2)

  overall_pnl_amount = total_booked_amt + curr_pnl_amount
  overall_pnl_percentage = round((overall_pnl_amount)*100/investment,2)

  estimate_st = round(sum(df_portfolio_features['FTT']*df_portfolio_features['Shares']),0)  + reserve_amt
  est_st_pnl_amount = estimate_st-current
  est_st_pnl_percentage = round((est_st_pnl_amount)*100/current,2)

  estimate_lt = round(sum(df_portfolio_features['LTT']*df_portfolio_features['Shares']),0)  + reserve_amt
  est_lt_pnl_amount = estimate_lt-current
  est_lt_pnl_percentage = round((est_lt_pnl_amount)*100/current,2)

  total_profit = round(sum(df_portfolio_features[df_portfolio_features['Current P/L%'] > 0]['Current']) - sum(df_portfolio_features[df_portfolio_features['Current P/L%'] > 0]['Investment']),0)
  total_loss = round(sum(df_portfolio_features[df_portfolio_features['Current P/L%'] < 0]['Current']) - sum(df_portfolio_features[df_portfolio_features['Current P/L%'] < 0]['Investment']),0)

  cy_booked_percentage = round((cy_booked_amt)*100/current,2)
  py_booked_percentage = round((py_booked_amt)*100/investment,2)
  total_booked_percentage = round((total_booked_amt)*100/investment,2)

  print('-------------------')
  print('Initial Investment: ', format_amt(investment))
  print('CY Investment: ', format_amt(cy_invested))
  print('Reserve: ', format_amt(reserve_amt))
  print('Current: ',  format_amt(current))
  print('-------------------')
  print('Today PnL: '+ '{} ({}%)'.format(format_amt(today_pnl_amount), today_pnl_percentage))
  print('Current PnL: '+ '{} ({}%)'.format(format_amt(curr_pnl_amount), curr_pnl_percentage))
  print('CY Booked + Current PnL: '+ '{} ({}%)'.format(format_amt(cy_pnl_amount), cy_pnl_percentage))
  print('-------------------')
  print('Total profit: ', format_amt(total_profit))
  print('Total loss: ', format_amt(total_loss))
  print('-------------------')
  print('Total Booked + Current PnL: '+ '{} ({}%)'.format(format_amt(overall_pnl_amount), overall_pnl_percentage))
  print('Total Booked PnL: '+ '{} ({}%)'.format(format_amt(total_booked_amt), total_booked_percentage))
  print('Curr Year Booked PnL: '+ '{} ({}%)'.format(format_amt(cy_booked_amt), cy_booked_percentage))
  print('Prev Year Booked PnL: '+ '{} ({}%)'.format(format_amt(py_booked_amt), py_booked_percentage))
  print('===================')
  print('Est FTT: ',  format_amt(estimate_st))
  print('Est FTT PnL: '+ '{} ({}%)'.format(format_amt(est_st_pnl_amount), est_st_pnl_percentage))

  print('===================')
  print('Deployed: ', format_amt(investment))

  print('Current: ', format_amt(current))

  print('CAGR/XIRR %: '+'{}%'.format(cagr))

In [8]:
# get start and end date
start_date, end_date = get_start_end_date()

# get portfolio and prospects data
mypfs_df = get_mypfs_df()
mypps_df = get_mypps_df()
myinvmt_df = get_myinvmt_df()

# merge above datasets
mypf_df = pd.merge(mypfs_df, mypps_df, on="Symbol")

# seggregate dm and sv portfolio
dm_pf = mypf_df[mypf_df['InPortfolio'] == 'DM']
sv_pf = mypf_df[mypf_df['InPortfolio'] == 'SV']

# build portfolio stock dataframe
dm_stocks = get_stock_ids(dm_pf)
sv_stocks = get_stock_ids(sv_pf)
df_stocks = pd.concat([dm_pf,sv_pf], ignore_index = True)

# arrange common and diff stock features
common_cols = ['Symbol', 'Target', 'Criteria', 'Strategy', 'CumlRnk', 'LatestQtr', 'StarStock', 'Conviction', 'Category', 'InFolio', 'XIRR', 'MBQ']
diff_cols = ['Symbol', 'AvgCost', 'Shares']
df_stocks = arrange_features(df_stocks, common_cols, diff_cols)

# get common features
stock_ids = df_stocks['Symbol'].values
df_common_features = get_common_features(stock_ids, df_stocks)

df_common_features.reset_index(drop=True, inplace=True)
df_common_features.drop(['Date'], axis=1, inplace=True)
# get and print portfolio features
df_portfolio_features = get_portfolio_features(df_common_features)

print_portfolio_stats(df_portfolio_features, myinvmt_df)

df = df_portfolio_features
#plot_pie_chart(df, 'CapType', 'Current')
list_ox40n = list(df[df['MBQ'].str.contains('OX40N', na=False)]['Symbol'].values)

Run date time (IST): 2026-03-20 11:01:55
-------------------
qualified stocks: 86
with latest results: 26
still star stocks: 16
-------------------
Initial Investment:  1.36 C
CY Investment:  1.62 C
Reserve:  1.61 K
Current:  1.32 C
-------------------
Today PnL: 1.50 L (1.15%)
Current PnL: -44.64 L (-27.47%)
CY Booked + Current PnL: -28.75 L (-17.7%)
-------------------
Total profit:  70.47 K
Total loss:  -45.35 L
-------------------
Total Booked + Current PnL: -1.77 L (-1.31%)
Total Booked PnL: 42.87 L (31.64%)
Curr Year Booked PnL: 15.89 L (11.99%)
Prev Year Booked PnL: 26.98 L (19.91%)
===================
Est FTT:  2.48 C
Est FTT PnL: 1.15 C (87.11%)
===================
Deployed:  1.36 C
Current:  1.32 C
CAGR/XIRR %: -1.12%

In [9]:
# top 5 near their targets
cols = ['Symbol', 'Today P/L%', 'Current P/L%', 'FTT%', 'OTT%', 'FTT Amt', 'Current P/L', 'Current', 'FTT', 'Dev%_PE', 'RSI_14','Conviction', 'Spread%',  'CumlRnk', 'RRR Ind', 'CurrAlloc%', 'Gained%', 'Criteria', 'Strategy', 'Category']
df_tmp = df_portfolio_features[~df_portfolio_features['Symbol'].isin(['ENRIN','BLUSPRING','DIGITIDE'])]
df_tmp = df_tmp.sort_values(by = 'FTT Amt', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
50,MASFIN,1.42,-9.05,33.66,21.57,29996.0,-8865.0,89115.0,397.04,-21.41,39.0,H-SC,1.63,167.0,-0.30,0.67,21.55,XR,ATH,FINANCE
77,TTKPRESTIG,-1.73,-38.12,61.75,0.09,38509.0,-38414.0,62363.0,770.00,44.72,40.0,M-SC,18.00,250.0,-1.00,0.47,5.37,OX40N,NTT,DURABLES
37,ICICIGI,0.91,-4.21,24.58,19.34,47117.0,-8419.0,191690.0,2252.93,-19.34,37.0,X-MC,2.70,66.0,-0.18,1.45,5.97,X40,ATH,INSURANCE
2,ABBOTINDIA,-0.04,-11.08,32.79,18.07,52146.0,-19825.0,159030.0,35195.00,-24.24,44.0,X-MC,10.69,58.0,-0.38,1.20,0.82,X40,ATH,PHARMA
67,SONACOMS,1.32,-12.58,59.12,39.09,52279.0,-12731.0,88428.0,804.02,-30.73,48.0,M-MC,8.15,193.0,-0.24,0.67,25.10,AR,ATH,AUTO

In [10]:
# top 5 today
df_tmp = df_portfolio_features.sort_values(by = 'Today P/L%', ascending=False)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
30,HAPPSTMNDS,4.84,-51.36,280.01,84.85,174569.0,-65821.0,62344.0,1480.71,-42.16,53.0,H-SC,27.46,152.0,-0.38,0.47,15.45,AR,ATH,IT
72,TATAELXSI,4.79,-39.00,116.43,32.03,93636.0,-51412.0,80423.0,9161.00,-23.72,38.0,H-SC,20.12,158.0,-0.55,0.61,4.79,OX40N,NTT,IT
8,AWL,4.52,-36.55,163.23,67.02,369022.0,-130234.0,226075.0,485.00,-65.82,45.0,X-SC,25.73,81.0,-0.35,1.71,6.94,XY24,NTT,FMCG
59,RELIANCE,3.13,-8.33,36.69,25.30,67592.0,-16738.0,184225.0,1952.00,-10.80,54.0,X-LC,3.38,21.0,-0.25,1.39,23.00,XY25,BTT,REFINERIES
65,SIEMENS,3.02,-14.78,47.28,25.51,74984.0,-27500.0,158595.0,4671.50,33.15,48.0,H-LC,3.55,51.0,-0.37,1.20,16.79,AR,ATH,ELECTRICAL

In [11]:
# bottom 5 today
df_tmp = df_portfolio_features.sort_values(by = 'Today P/L%', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
70,SYMPHONY,-4.10,-40.08,66.84,-0.03,68542.0,-68594.0,102547.0,1306.0,-51.97,41.0,M-SC,14.94,205.0,-1.00,0.77,3.70,OX40N,NTT,DURABLES
42,INDUSINDBK,-3.07,-39.73,120.51,32.89,56072.0,-30678.0,46529.0,1800.0,-319.19,33.0,L-MC,8.84,258.0,-0.55,0.35,28.14,XR,NTT,BANKS
34,HDFCBANK,-1.98,-6.40,37.14,28.37,81654.0,-15031.0,219854.0,1073.0,-20.53,24.0,X-LC,10.76,26.0,-0.18,1.66,0.00,X40,BTT,BANKS
77,TTKPRESTIG,-1.73,-38.12,61.75,0.09,38509.0,-38414.0,62363.0,770.0,44.72,40.0,M-SC,18.00,250.0,-1.00,0.47,5.37,OX40N,NTT,DURABLES
55,RAJESHEXPO,-1.57,-81.22,432.92,0.07,111512.0,-111419.0,25758.0,518.0,844.44,18.0,L-SC,30.90,268.0,-1.00,0.19,0.00,OX40N,NTT,JEWELLERY

In [12]:
# top 5 to exit based on CumlRnk
df_tmp = df_portfolio_features[~df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])]
df_tmp = df_tmp[(df_tmp['Current P/L%'] > -1) & (df_tmp['Current P/L%'] < 1)].sort_values(by = 'CumlRnk', ascending=False)
df_tmp[cols].head()

Empty DataFrame
Columns: [Symbol, Today P/L%, Current P/L%, FTT%, OTT%, FTT Amt, Current P/L, Current, FTT, Dev%_PE, RSI_14, Conviction, Spread%, CumlRnk, RRR Ind, CurrAlloc%, Gained%, Criteria, Strategy, Category]
Index: []

In [13]:
# OX40N stocks to exit
df_tmp = df_portfolio_features[(df_portfolio_features['Symbol'].isin(list_ox40n))].sort_values(by = 'Current P/L%', ascending=False)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
26,FINCABLES,2.60,10.43,88.27,107.91,143920.0,15401.0,163045.0,1641.55,-0.56,52.0,M-SC,8.29,220.0,0.11,1.23,22.66,OX40N,ATH,CABLES
66,SIS,-0.74,-36.61,91.30,21.26,64257.0,-40652.0,70380.0,528.00,1644.04,33.0,H-SC,13.66,168.0,-0.63,0.53,1.43,OX40N,NTT,MISC
18,CERA,0.24,-37.63,98.64,23.89,108218.0,-66193.0,109710.0,9475.00,-39.86,47.0,H-SC,18.44,153.0,-0.61,0.83,5.43,OX40N,NTT,CERAMICS
77,TTKPRESTIG,-1.73,-38.12,61.75,0.09,38509.0,-38414.0,62363.0,770.00,44.72,40.0,M-SC,18.00,250.0,-1.00,0.47,5.37,OX40N,NTT,DURABLES
72,TATAELXSI,4.79,-39.00,116.43,32.03,93636.0,-51412.0,80423.0,9161.00,-23.72,38.0,H-SC,20.12,158.0,-0.55,0.61,4.79,OX40N,NTT,IT

In [14]:
# top 5 to book for rotation
df_tmp = df_portfolio_features[(df_portfolio_features['Current P/L%'] > 20) ].sort_values(by = 'CumlRnk', ascending=False)
df_tmp[cols].head()

Empty DataFrame
Columns: [Symbol, Today P/L%, Current P/L%, FTT%, OTT%, FTT Amt, Current P/L, Current, FTT, Dev%_PE, RSI_14, Conviction, Spread%, CumlRnk, RRR Ind, CurrAlloc%, Gained%, Criteria, Strategy, Category]
Index: []

In [15]:
# top 5 to monitor for exit
df_tmp = df_portfolio_features[~df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])]
df_tmp = df_tmp[(df_tmp['Current P/L%'] > 0) ].sort_values(by = 'Dev%_PE', ascending=False)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
26,FINCABLES,2.60,10.43,88.27,107.91,143920.0,15401.0,163045.0,1641.55,-0.56,52.0,M-SC,8.29,220.0,0.11,1.23,22.66,OX40N,ATH,CABLES
1,ABB,1.75,16.01,25.48,45.57,77333.0,41885.0,303504.0,7934.00,-25.41,61.0,H-MC,13.04,125.0,0.54,2.29,34.78,AR,NTT,ELECTRICAL

In [16]:
# top 5 to book for rotation from weak conviction
df_tmp = df_portfolio_features[~df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])]
df_tmp = df_tmp[~df_tmp['Criteria'].isin(['XY25','XY24','X40', 'X40N'])].sort_values(by = 'RRR Ind', ascending=False)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
1,ABB,1.75,16.01,25.48,45.57,77333.0,41885.0,303504.0,7934.00,-25.41,61.0,H-MC,13.04,125.0,0.54,2.29,34.78,AR,NTT,ELECTRICAL
26,FINCABLES,2.60,10.43,88.27,107.91,143920.0,15401.0,163045.0,1641.55,-0.56,52.0,M-SC,8.29,220.0,0.11,1.23,22.66,OX40N,ATH,CABLES
40,INDIAMART,-0.39,-13.15,138.03,106.72,147848.0,-16223.0,107113.0,4810.62,-60.74,35.0,H-SC,10.76,140.0,-0.11,0.81,7.15,AR,ATH,MISC
85,ZYDUSLIFE,1.53,-6.20,44.59,35.63,87660.0,-12983.0,196591.0,1286.17,-18.47,45.0,H-MC,5.29,120.0,-0.15,1.48,9.44,AR,ATH,PHARMA
84,WIPRO,0.93,-22.00,120.87,72.27,159743.0,-37287.0,132161.0,420.00,-29.71,30.0,M-LC,17.02,98.0,-0.23,1.00,0.93,XR,NTT,IT

In [17]:
# top 5 to accumulate based on lowest RSI_14
df_tmp = df_portfolio_features[df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])].sort_values(by = 'RSI_14', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
53,PGHH,-0.55,-26.08,78.60,32.01,124050.0,-55696.0,157824.0,17616.87,-49.95,15.0,X-MC,14.44,57.0,-0.45,1.19,0.00,X40,ATH,FMCG
12,BATAINDIA,1.56,-57.55,218.52,35.20,119351.0,-74052.0,54618.0,2096.00,-28.38,19.0,X-SC,29.92,91.0,-0.62,0.41,1.56,X40,NTT,FOOTWEAR
38,ICICIPRULI,-0.44,-7.26,40.96,30.73,74837.0,-14298.0,182707.0,790.00,-32.15,23.0,X-MC,3.37,78.0,-0.19,1.38,4.52,X40,ATH,INSURANCE
58,RELAXO,1.47,-64.16,325.01,52.31,169070.0,-93140.0,52020.0,1176.00,-61.86,23.0,X-SC,24.49,92.0,-0.55,0.39,1.47,X40N,NTT,FOOTWEAR
34,HDFCBANK,-1.98,-6.40,37.14,28.37,81654.0,-15031.0,219854.0,1073.00,-20.53,24.0,X-LC,10.76,26.0,-0.18,1.66,0.00,X40,BTT,BANKS

In [18]:
# top 5 to accumulate based on Spread and CumlRnk
df_tmp = df_portfolio_features[df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])]
df_tmp = df_tmp[(df_tmp['CumlRnk'] < 100)].sort_values(by = 'Spread%', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
78,UNITDSPR,1.32,-4.07,25.89,20.77,58153.0,-9529.0,224615.0,1644.00,-14.95,42.0,X-MC,1.11,64.0,-0.16,1.70,2.36,X40N,NTT,BREWERIES
37,ICICIGI,0.91,-4.21,24.58,19.34,47117.0,-8419.0,191690.0,2252.93,-19.34,37.0,X-MC,2.70,66.0,-0.18,1.45,5.97,X40,ATH,INSURANCE
38,ICICIPRULI,-0.44,-7.26,40.96,30.73,74837.0,-14298.0,182707.0,790.00,-32.15,23.0,X-MC,3.37,78.0,-0.19,1.38,4.52,X40,ATH,INSURANCE
59,RELIANCE,3.13,-8.33,36.69,25.30,67592.0,-16738.0,184225.0,1952.00,-10.80,54.0,X-LC,3.38,21.0,-0.25,1.39,23.00,XY25,BTT,REFINERIES
65,SIEMENS,3.02,-14.78,47.28,25.51,74984.0,-27500.0,158595.0,4671.50,33.15,48.0,H-LC,3.55,51.0,-0.37,1.20,16.79,AR,ATH,ELECTRICAL

In [19]:
# top 5 to accumulate based on lowest Gained%
df_tmp = df_portfolio_features[df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])].sort_values(by = 'Gained%', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
51,MEDANTA,-0.54,-13.68,47.26,27.12,72012.0,-24143.0,152374.0,1486.00,-16.30,29.0,X-SC,11.01,87.0,-0.34,1.15,0.00,XY24,NTT,HEALTHCARE
53,PGHH,-0.55,-26.08,78.60,32.01,124050.0,-55696.0,157824.0,17616.87,-49.95,15.0,X-MC,14.44,57.0,-0.45,1.19,0.00,X40,ATH,FMCG
34,HDFCBANK,-1.98,-6.40,37.14,28.37,81654.0,-15031.0,219854.0,1073.00,-20.53,24.0,X-LC,10.76,26.0,-0.18,1.66,0.00,X40,BTT,BANKS
21,DABUR,0.41,-15.55,70.16,43.70,146982.0,-38572.0,209496.0,735.00,-23.35,25.0,X-MC,4.53,70.0,-0.26,1.58,0.41,XY24,BTT,FMCG
35,HINDUNILVR,0.67,-18.65,39.73,13.67,83083.0,-47943.0,209120.0,2922.00,-39.55,28.0,X-LC,7.35,9.0,-0.58,1.58,0.67,XY25,NTT,FMCG

In [20]:
# top 5 to accumulate based on lowest CurrAlloc%
df_tmp = df_portfolio_features[df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])].sort_values(by = 'CurrAlloc%', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
58,RELAXO,1.47,-64.16,325.01,52.31,169070.0,-93140.0,52020.0,1176.00,-61.86,23.0,X-SC,24.49,92.0,-0.55,0.39,1.47,X40N,NTT,FOOTWEAR
12,BATAINDIA,1.56,-57.55,218.52,35.20,119351.0,-74052.0,54618.0,2096.00,-28.38,19.0,X-SC,29.92,91.0,-0.62,0.41,1.56,X40,NTT,FOOTWEAR
54,QUESS,1.00,-25.91,134.71,73.90,106589.0,-27668.0,79125.0,424.00,-60.33,39.0,X-SC,20.46,80.0,-0.26,0.60,3.12,XY24,NTT,MISC
36,HONAUT,1.74,-24.94,101.58,51.31,147037.0,-48088.0,144750.0,58357.33,-37.55,34.0,X-SC,14.96,90.0,-0.33,1.09,1.74,X40N,ATH,ELECTRICAL
51,MEDANTA,-0.54,-13.68,47.26,27.12,72012.0,-24143.0,152374.0,1486.00,-16.30,29.0,X-SC,11.01,87.0,-0.34,1.15,0.00,XY24,NTT,HEALTHCARE

In [21]:
# top 5 to accumulate based on CumlRnk
df_tmp = df_portfolio_features.sort_values(by = 'CumlRnk', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
45,ITC,2.89,-19.24,47.42,19.06,130269.0,-65452.0,274714.0,452.00,-55.52,44.0,X-LC,17.85,1.0,-0.50,2.07,2.89,X40,NTT,FMCG
73,TCS,1.06,-30.10,81.08,26.57,262550.0,-139457.0,323816.0,4311.59,-40.68,27.0,X-LC,16.68,2.0,-0.53,2.44,1.06,X40,ATH,IT
43,INFY,2.40,-14.90,57.75,34.24,153772.0,-46617.0,266271.0,1972.00,-32.87,35.0,X-LC,14.84,3.0,-0.30,2.01,2.40,X40,NTT,IT
75,TMPV,1.70,-28.40,90.75,36.58,231218.0,-101055.0,254786.0,600.00,-84.72,35.0,X-LC,5.02,4.0,-0.44,1.92,1.70,XY24,NTT,AUTO
33,HCLTECH,2.90,-12.40,41.36,23.83,87656.0,-29990.0,211934.0,1908.19,-7.78,40.0,X-LC,11.48,8.0,-0.34,1.60,2.90,X40,ATH,IT

In [22]:
# top 5 for average up
df_tmp = df_portfolio_features[(df_portfolio_features['Dev%_200'] > 5)].sort_values(by = 'CurrAlloc%', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
67,SONACOMS,1.32,-12.58,59.12,39.09,52279.0,-12731.0,88428.0,804.02,-30.73,48.0,M-MC,8.15,193.0,-0.24,0.67,25.10,AR,ATH,AUTO
1,ABB,1.75,16.01,25.48,45.57,77333.0,41885.0,303504.0,7934.00,-25.41,61.0,H-MC,13.04,125.0,0.54,2.29,34.78,AR,NTT,ELECTRICAL

In [23]:
# top 5 RSP
df_tmp = df_portfolio_features.sort_values(by = 'RSP', ascending=False)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
26,FINCABLES,2.60,10.43,88.27,107.91,143920.0,15401.0,163045.0,1641.55,-0.56,52.0,M-SC,8.29,220.0,0.11,1.23,22.66,OX40N,ATH,CABLES
80,VALIANTORG,0.61,-45.76,221.07,74.15,196178.0,-74865.0,88740.0,838.00,-259.70,64.0,H-SC,28.68,145.0,-0.38,0.67,32.06,XR,NTT,CHEMICALS
1,ABB,1.75,16.01,25.48,45.57,77333.0,41885.0,303504.0,7934.00,-25.41,61.0,H-MC,13.04,125.0,0.54,2.29,34.78,AR,NTT,ELECTRICAL
69,SURYODAY,0.02,-27.39,69.44,23.03,90293.0,-49041.0,130030.0,216.00,42.54,48.0,H-SC,6.56,166.0,-0.54,0.98,27.09,XR,NTT,BANKS
30,HAPPSTMNDS,4.84,-51.36,280.01,84.85,174569.0,-65821.0,62344.0,1480.71,-42.16,53.0,H-SC,27.46,152.0,-0.38,0.47,15.45,AR,ATH,IT

In [24]:
# Top N allocation
df_tmp = df_portfolio_features.sort_values(by = 'CurrAlloc%', ascending=False)
top_n_values = [10, 25, 50]

sum_df = pd.DataFrame({
    'Top_N': top_n_values,
    'Sum_Alloc%': [df_tmp['CurrAlloc%'].head(n).sum() for n in top_n_values]
})

sum_df

   Top_N  Sum_Alloc%
0     10       20.69
1     25       45.63
2     50       77.99

In [25]:
# market-cap-wise allocation
df_tmp = df_portfolio_features[cols]
df_tmp.groupby(df_tmp['Conviction'].str[-2:])['CurrAlloc%'].sum().sort_values(ascending=False)

Conviction
SC    44.52
MC    30.11
LC    25.33
Name: CurrAlloc%, dtype: float64

In [26]:
# criteria-wise allocation
df_portfolio_features.groupby('Criteria')['CurrAlloc%'].sum().sort_values(ascending=False)

Criteria
XY24     26.97
X40      25.40
X40N     15.17
AR        9.19
XR        8.31
XY25      7.34
OX40N     6.79
SR        0.79
Name: CurrAlloc%, dtype: float64

In [27]:
# conviction-wise allocation
df_portfolio_features.groupby('Conviction')['CurrAlloc%'].sum().sort_values(ascending=False)

Conviction
X-LC    23.13
X-MC    22.64
H-SC    21.62
X-SC    12.26
M-SC    10.10
H-MC     5.07
M-MC     2.05
H-LC     1.20
M-LC     1.00
L-SC     0.54
L-MC     0.35
Name: CurrAlloc%, dtype: float64

In [28]:
# sector-wise stats
df_tmp = df_portfolio_features.groupby('Category')[['CurrAlloc%', 'Current', 'Current P/L', 'FTT Amt']].sum().sort_values(by=['Current', 'Current P/L'], ascending=False)
df_tmp['Current P/L%'] = round(df_tmp['Current P/L'] * 100 / df_tmp['Current'], 2)
df_tmp['FTT%'] = round(df_tmp['FTT Amt'] * 100 / df_tmp['Current'], 2)
cols = ['CurrAlloc%', 'Current P/L%', 'FTT%']
df_tmp[cols].sort_values(by=['CurrAlloc%'], ascending=False)

               CurrAlloc%  Current P/L%    FTT%
Category
FMCG                15.10        -24.84   69.17
FINANCE             13.14        -23.40   73.69
IT                  11.69        -45.53  119.60
MISC                 6.94        -45.73  109.04
ELECTRICAL           6.64        -10.03   52.16
PAINTS               5.06        -47.04   72.58
INSURANCE            4.72         -8.56   45.70
BANKS                4.61        -25.98   89.93
PHARMA               4.13         -7.22   40.97
AUTO                 3.67        -34.55   87.93
AC                   2.10        -14.89   46.05
HEALTHCARE           1.89        -42.88   80.17
DURABLES             1.81        -60.75   99.86
TRAVEL               1.81        -87.30  181.09
FOOTWEAR             1.77        -87.60  162.81
BREWERIES            1.70         -4.24   25.89
APPARELS             1.68        -20.62   61.77
REALTY               1.45        -15.17   34.09
REFINERIES           1.39         -9.09   36.69
CERAMICS             1.38        -67.87  118.87
CEMENT               1.24        -63.14  185.19
CABLES               1.23          9.45   88.27
ENGINEERING          1.09        -67.14  143.59
CHEMICALS            1.09        -83.08  232.45
JEWELLERY            1.06       -126.23  204.82
ENTERTAINMENT        0.77        -89.90  203.16
TEXTILES             0.45        -54.72   98.84
HOTELS               0.35       -145.29  231.81

In [29]:
# money to be made criteria-wise
df_portfolio_features.groupby('Criteria')['FTT Amt'].agg(['sum', 'count']).sort_values(by='sum', ascending=False)

                sum  count
Criteria
XY24      4025434.0     21
X40       1808231.0     16
XR        1389382.0     12
AR        1353902.0     10
X40N      1289152.0     10
OX40N      890366.0     10
XY25       468531.0      5
SR         315061.0      2

In [30]:
# money to be made conviction-wise
df_portfolio_features.groupby('Conviction')['FTT Amt'].agg(['sum', 'count']).sort_values(by='sum', ascending=False)

                  sum  count
Conviction
H-SC        3927363.0     24
X-MC        1733926.0     15
X-LC        1710847.0     13
M-SC        1579120.0     14
X-SC        1557543.0     10
H-MC         406902.0      3
L-SC         218819.0      2
M-LC         159743.0      1
M-MC         114740.0      2
H-LC          74984.0      1
L-MC          56072.0      1

In [31]:
# money to be made criteria and conviction-wise
df_portfolio_features.groupby(['Conviction', 'Criteria'])['FTT Amt'].agg(['sum', 'count']).sort_values(by='sum', ascending=False)

                           sum  count
Conviction Criteria
H-SC       XY24      1361613.0      6
           AR         983615.0      5
X-LC       X40        923149.0      7
M-SC       XY24       923049.0      6
H-SC       XR         874141.0      7
X-SC       XY24       851986.0      4
X-MC       X40        680126.0      7
           X40N       525612.0      4
X-SC       X40N       500601.0      4
H-SC       OX40N      392933.0      4
M-SC       OX40N      385921.0      5
X-LC       XY24       374084.0      2
H-SC       SR         315061.0      2
X-MC       XY24       272793.0      2
X-LC       X40N       262939.0      2
X-MC       XY25       255395.0      2
H-MC       XY24       241909.0      1
X-SC       X40        204956.0      2
M-SC       XR         192119.0      2
H-MC       AR         164993.0      2
M-LC       XR         159743.0      1
X-LC       XY25       150675.0      2
L-SC       OX40N      111512.0      1
           XR         107307.0      1
M-SC       AR          78031.0      1
H-LC       AR          74984.0      1
M-MC       XY25        62461.0      1
L-MC       XR          56072.0      1
M-MC       AR          52279.0      1

In [32]:
# notebook execution time

end_time = time.time()
execution_time = round(end_time - start_time, 0)
print(f"Notebook execution time: {execution_time} seconds")

Notebook execution time: 29.0 seconds