<a href="https://colab.research.google.com/github/ankit-rathi/Quantvesting_v2/blob/main/myStocks_Portfolio_Analysis.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
'''
!pip install pandas==2.2.2 -qq
!pip install pyxirr -qq
!pip install ta -qq
!pip install yfinance==0.2.59 -qq
'''

'\n!pip install pandas==2.2.2 -qq\n!pip install pyxirr -qq\n!pip install ta -qq\n!pip install yfinance==0.2.59 -qq\n'

In [2]:
# import libraries

import numpy as np
import pandas as pd
import datetime
import warnings
warnings.filterwarnings('ignore')
import yfinance as yfin
import ta
import matplotlib.pyplot as plt
import requests

In [3]:
# notebook start time
import time
import datetime
import pytz

start_time = time.time()

# function to print date timestamp
def print_date_time():
  tz_NY = pytz.timezone('Asia/Kolkata')
  datetime_NY = datetime.datetime.now(tz_NY)
  print("Run date time (IST):", datetime_NY.strftime("%Y-%m-%d %H:%M:%S"))

In [4]:
# function to get booked and reserved amount
def get_amt():
  # fetch the JSON data from the URL
  url = "https://raw.githubusercontent.com/ankit-rathi/Tradevesting_v1/main/data/myPortfolioAmts.json"
  response = requests.get(url)
  pf_amts = response.json()  # parse the JSON data

  # extract values from the JSON
  py_booked_amt_dm = pf_amts["py_booked_amt_dm"]
  py_booked_amt_sv = pf_amts["py_booked_amt_sv"]
  cy_booked_amt_dm = pf_amts["cy_booked_amt_dm"]
  cy_booked_amt_sv = pf_amts["cy_booked_amt_sv"]
  reserve_amt_dm = pf_amts["reserve_amt_dm"]
  reserve_amt_sv = pf_amts["reserve_amt_sv"]

  # perform calculations
  py_booked_amt = py_booked_amt_dm + py_booked_amt_sv
  cy_booked_amt = cy_booked_amt_dm + cy_booked_amt_sv
  reserve_amt = reserve_amt_dm + reserve_amt_sv
  total_booked_amt = py_booked_amt + cy_booked_amt

  return total_booked_amt, reserve_amt, cy_booked_amt, py_booked_amt

gen_output = 0

In [5]:
# function to format the amount
def format_amt(number):
    abs_number = abs(number)

    if abs_number >= 1_00_00_000:  # Crores
        formatted_amt = f"{number / 1_00_00_000:.2f} C"
    elif abs_number >= 1_00_000:  # Lakhs
        formatted_amt = f"{number / 1_00_000:.2f} L"
    elif abs_number >= 1_000:  # Thousands
        formatted_amt = f"{number / 1_000:.2f} K"
    else:
        formatted_amt = f"{number:.2f}"

    return formatted_amt

# function to set start and end date
def get_start_end_date():
  start_date = (datetime.date.today() + datetime.timedelta(days=-365)).strftime('%Y-%m-%d')
  end_date = (datetime.date.today() + datetime.timedelta(days=1)).strftime('%Y-%m-%d')
  return start_date, end_date

# function to fetch my portfolio csv
def get_mypfs_df():
  mypfs_df = pd.read_csv('https://raw.githubusercontent.com/ankit-rathi/Tradevesting_v1/main/data/myPortfolioStocks.csv')
  return mypfs_df

# function to fetch my prospects csv
def get_mypps_df():
  mypps_df = pd.read_csv('https://raw.githubusercontent.com/ankit-rathi/Tradevesting_v1/main/data/myProspectsScrips.csv')
  return mypps_df

# function to fetch screener data
def get_myscreen_df():
  myscreen_df = pd.read_csv('https://raw.githubusercontent.com/ankit-rathi/Tradevesting_v1/main/data/myScreenerDB.csv')
  return myscreen_df

# function to fetch momentum data
def get_myinvmt_df():
  myinvmt_df = pd.read_csv('https://raw.githubusercontent.com/ankit-rathi/Tradevesting_v1/main/data/myInvestments.csv')
  return myinvmt_df

# function to get the stock ids
def get_stock_ids(df_pf):
  stock_n100 = df_pf['Symbol'].unique()

  exclude = ['CADILAHC','MMTC', 'MASFIN']

  stock_ids = df_pf[~df_pf['Symbol'].isin(exclude) ]['Symbol'].unique()

  #mypf = mypf[mypf.Forecast.notnull()]
  #stock_ids = mypf['Symbol'].unique()

  #stock_ids.sort()
  return stock_ids

# get features from screener data
def get_screener_features():
  myscreen_df = get_myscreen_df()
  cols = ['Symbol', 'EPS', 'MedPE', 'ROCE%', 'ROE%', 'CapType']
  return myscreen_df[cols]

# get relative strength
def get_relative_strength(stock_list):

    # Dictionary to store stock tickers and their corresponding percentage price change
    stock_changes = {}

    # Loop through each stock and fetch its price data
    for stock in stock_list:
        try:
            # Download the stock data for the given date range
            stock_data = yfin.Ticker(stock + '.NS').history(period='1mo', interval='1d')[map(str.title, ['open', 'close', 'low', 'high', 'volume'])]

            # Calculate the percentage change for the stock
            if len(stock_data) > 0:
                start_price = stock_data['Close'].iloc[0]
                end_price = stock_data['Close'].iloc[-1]
                percent_change = round(((end_price - start_price) / start_price) * 100, 2)
                stock_changes[stock] = percent_change
            else:
                stock_changes[stock] = np.nan  # If no data is available, set to NaN

        except Exception as e:
            print(f"Error fetching data for {stock}: {e}")
            stock_changes[stock] = np.nan

    # Create a DataFrame with stock tickers and their percentage changes
    df = pd.DataFrame(list(stock_changes.items()), columns=['Symbol', 'Percent_Change'])

    # Drop any stocks with missing data (NaN values)
    df = df.dropna()

    # Calculate the percentile rank based on percentage change
    df['RSP'] = round(df['Percent_Change'].rank(pct=True) * 100, 2)
    cols = ['Symbol', 'RSP']
    df = df[cols]
    # Sort by percentile rank (optional)
    df = df.sort_values(by='RSP', ascending=False).reset_index(drop=True)

    return df

In [6]:
# function to get stock technicals
def stock_prec_dev(stock_symbol):
    #stock_symbol = 'ULTRACEMCO.NS'
    short_window = 20
    mid_window = 50
    long_window = 200
    moving_avg = 'SMA'

    start = datetime.datetime(*map(int, start_date.split('-')))
    end = datetime.datetime(*map(int, end_date.split('-')))

    stock_df = yfin.Ticker(stock_symbol + '.NS').history(period='max', interval='1d')[map(str.title, ['open', 'close', 'low', 'high', 'volume'])]

    stock_df['Max'] = round(max(stock_df['Close']),2)
    stock_df = stock_df[(stock_df.index <= end_date) & (stock_df.index >= start_date)]
    stock_df['200_SMA'] = round(stock_df['Close'].rolling(window = 200, min_periods = 1).mean(),0)
    stock_df['Dev%_200'] = round((stock_df['Close'] - stock_df['200_SMA'])*100/stock_df['200_SMA'],2)
    stock_df.dropna(axis = 0, inplace = True) # remove any null rows

    stock_df['20_SMA'] = stock_df['Close'].rolling(window=20).mean()
    stock_df['50_SMA'] = stock_df['Close'].rolling(window=50).mean()
    stock_df['Symbol'] = stock_symbol

    stock_df['Close'] = round(stock_df['Close'],2)
    stock_df['Min'] = round(min(stock_df['Close']),2)
    stock_df['RSI_14'] = ta.momentum.RSIIndicator(close=stock_df['Close'], window=14).rsi()
    stock_df['RSI_14'] = round(stock_df['RSI_14'],0)
    stock_df['Prev_Close'] = stock_df['Close'].shift(1)
    stock_df.drop(['Open', 'Low', 'High', 'Volume'], axis=1, inplace=True)
    stock_df = stock_df.tail(1)

    max_SMA = max(stock_df['20_SMA'].item(), stock_df['50_SMA'].item(), stock_df['200_SMA'].item())
    min_SMA = min(stock_df['20_SMA'].item(), stock_df['50_SMA'].item(), stock_df['200_SMA'].item())
    ABS_Spread = max_SMA - min_SMA
    stock_df['Spread%'] = round((ABS_Spread / stock_df['200_SMA'].item()) * 100,2)

    return stock_df

# function to compute stock attributes
def get_common_features(stock_ids, df_mypf):

  df_prec_dev = pd.DataFrame()
  df_tmp = get_screener_features()
  df_rs = get_relative_strength(stock_ids)

  for stock_id in stock_ids:
      tmp = stock_prec_dev(stock_id)
      tmp = tmp.reset_index()
      df_prec_dev = pd.concat([df_prec_dev, tmp], ignore_index = True)
  df_prec_dev = pd.merge(df_prec_dev, df_mypf, on= 'Symbol')
  df_prec_dev = pd.merge(df_prec_dev, df_tmp, on= 'Symbol', how='left')
  df_prec_dev = pd.merge(df_prec_dev, df_rs, on= 'Symbol', how='left')
  #print(df_prec_dev.columns)
  df_prec_dev['Curr_PE'] = round(df_prec_dev['Close']/df_prec_dev['EPS'],1)
  df_prec_dev['Dev%_PE'] = round((df_prec_dev['Curr_PE'] - df_prec_dev['MedPE'])*100/df_prec_dev['MedPE'],2)
  df_prec_dev['Conviction'] = df_prec_dev['Conviction'] + '-' + df_prec_dev['CapType']
  return df_prec_dev

# function to arrange stock features
def arrange_features(df_stocks, common_cols, diff_cols):
  df_stocks_common = df_stocks[common_cols].drop_duplicates()
  df_stocks_diff = df_stocks[diff_cols]
  df_stocks_diff['Investment'] = df_stocks_diff['AvgCost'] * df_stocks_diff['Shares']
  df_stocks_diff = df_stocks_diff.groupby(['Symbol'])[['Shares', 'Investment']].aggregate(['sum']).reset_index()
  df_stocks_diff.columns = ['Symbol', 'Shares', 'Investment']
  df_stocks_diff['AvgCost'] = round(df_stocks_diff['Investment']/df_stocks_diff['Shares'],2)
  df_stocks = pd.merge(df_stocks_diff, df_stocks_common, on='Symbol')
  return df_stocks

# plot fact distribution across dimension
def plot_pie_chart(df, dimension, fact):
  # grouping the data by category and calculating the sum of fact for each type
  grouped_data = df.groupby(dimension)[fact].sum()

  # sorting the grouped data in descending order
  grouped_data = grouped_data.sort_values(ascending=False)

  # creating a pie chart
  grouped_data.plot.pie(autopct='%1.1f%%', startangle=90, figsize=(6, 6))

  # adding a title and displaying the plot
  plt.title(f'{dimension} {fact} Distribution')
  plt.ylabel('')  # To hide the y-label
  plt.show()

In [7]:
# function to get portfolio features

def get_portfolio_features(df_common_features):

  print_date_time()
  print('-------------------')

  #df_common_features["Target"] = df_common_features["Target"].fillna(df_common_features["Max"])
  df_common_features['NTT'] = np.where(df_common_features['Strategy']== 'NTT', df_common_features["Target"], df_common_features['Max'])
  df_common_features['LTT'] = np.where(df_common_features['Strategy']== 'BTT', df_common_features["Target"], df_common_features['Max'])
  df_common_features['BOL'] = df_common_features['Min']

  tmp_df = df_common_features[df_common_features['Symbol'].isin(mypf_df[mypf_df['InPortfolio'] != 'NA'].Symbol.values)]
  print('qualified stocks: '+str(len(tmp_df['Symbol'].unique())))
  tmp_df1 = tmp_df[tmp_df['LatestQtr'] == 1]
  print('with latest results: '+str(len(tmp_df1['Symbol'].unique())))
  tmp_df1 = tmp_df1[tmp_df1['StarStock'] == 1]
  print('still star stocks: '+str(len(tmp_df1['Symbol'].unique())))
  tmp_df['Investment'] = tmp_df['AvgCost'] * tmp_df['Shares']
  tmp_df['Current'] = round(tmp_df['Close'] * tmp_df['Shares'],0)
  tmp_df['Previous'] = tmp_df['Prev_Close'] * tmp_df['Shares']
  tmp_df['EstimatedST'] = tmp_df['NTT'] * tmp_df['Shares']
  tmp_df['EstimatedLT'] = tmp_df['LTT'] * tmp_df['Shares']
  tmp_df['Current P/L'] = round((tmp_df['Current'] - tmp_df['Investment']),0)
  tmp_df['Today P/L%'] = round((tmp_df['Current'] - tmp_df['Previous'])*100/tmp_df['Previous'],2)
  tmp_df['Current P/L%'] = round((tmp_df['Current'] - tmp_df['Investment'])*100/tmp_df['Investment'],2)
  tmp_df['EstimatedST P/L%'] = round((tmp_df['EstimatedST'] - tmp_df['Investment'])*100/tmp_df['Investment'],2)
  tmp_df['EstimatedLT P/L%'] = round((tmp_df['EstimatedLT'] - tmp_df['Investment'])*100/tmp_df['Investment'],2)
  tmp_df['NTT%'] = round((tmp_df['NTT'] - tmp_df['Close'])*100/tmp_df['Close'],2)
  tmp_df['LTT%'] = round((tmp_df['LTT'] - tmp_df['Close'])*100/tmp_df['Close'],2)
  tmp_df['Gained%'] = round((tmp_df['Close'] - tmp_df['BOL'])*100/tmp_df['BOL'],2)
  investment = round(sum(tmp_df['AvgCost']*tmp_df['Shares']),0)
  current = round(sum(tmp_df['Close']*tmp_df['Shares']),0)
  tmp_df['InitAlloc%'] = round(tmp_df['Investment']*100/investment,2)
  tmp_df['CurrAlloc%'] = round(tmp_df['Current']*100/current,2)
  tmp_df['FTT'] = tmp_df['LTT']
  tmp_df.loc[tmp_df['Strategy'] == 'NTT', 'FTT'] = tmp_df['NTT']
  tmp_df['FTT%'] = tmp_df['LTT%']
  tmp_df.loc[tmp_df['Strategy'] == 'NTT', 'FTT%'] = tmp_df['NTT%']
  tmp_df['FTT Amt'] = round(tmp_df['FTT%'] * tmp_df['Current']/100,0)
  tmp_df['OTT%'] = round((tmp_df['FTT'] - tmp_df['AvgCost'])*100/tmp_df['AvgCost'],2)
  tmp_df['RRR Ind'] = round(tmp_df['Current P/L']/tmp_df['FTT Amt'],2)
  tmp_df['Risk Ind'] = round(tmp_df['Current P/L%']*tmp_df['CurrAlloc%'],0)

  return tmp_df

# function to print portfolio features
def print_portfolio_stats(df_portfolio_features, myinvmt_df):
  from pyxirr import xirr

  total_booked_amt, reserve_amt, cy_booked_amt, py_booked_amt = get_amt()

  dates = myinvmt_df['Date'].values
  dates = np.append(dates, datetime.date.today().strftime('%d-%b-%y'))
  investment = myinvmt_df['Investment'].values
  dates= pd.to_datetime(dates)

  current = round(sum(df_portfolio_features['Close']*df_portfolio_features['Shares']),0) + reserve_amt
  investment_xirr = np.append(investment, current)
  cagr = round(xirr(pd.DataFrame({"dates": dates, "amounts": investment_xirr}))*100,2)

  investment = -sum(investment)
  invested = round(sum(df_portfolio_features['AvgCost']*df_portfolio_features['Shares']),0) + reserve_amt
  previous = round(sum(df_portfolio_features['Prev_Close']*df_portfolio_features['Shares']),0) + reserve_amt
  cy_invested = investment + py_booked_amt

  today_pnl_amount = current-previous
  today_pnl_percentage = round((current-previous)*100/previous,2)

  curr_pnl_amount = current-invested
  curr_pnl_percentage = round((curr_pnl_amount)*100/(cy_invested),2)

  cy_pnl_amount = cy_booked_amt + curr_pnl_amount
  cy_pnl_percentage = round((cy_pnl_amount)*100/cy_invested,2)

  overall_pnl_amount = total_booked_amt + curr_pnl_amount
  overall_pnl_percentage = round((overall_pnl_amount)*100/investment,2)

  estimate_st = round(sum(df_portfolio_features['FTT']*df_portfolio_features['Shares']),0)  + reserve_amt
  est_st_pnl_amount = estimate_st-current
  est_st_pnl_percentage = round((est_st_pnl_amount)*100/current,2)

  estimate_lt = round(sum(df_portfolio_features['LTT']*df_portfolio_features['Shares']),0)  + reserve_amt
  est_lt_pnl_amount = estimate_lt-current
  est_lt_pnl_percentage = round((est_lt_pnl_amount)*100/current,2)

  total_profit = round(sum(df_portfolio_features[df_portfolio_features['Current P/L%'] > 0]['Current']) - sum(df_portfolio_features[df_portfolio_features['Current P/L%'] > 0]['Investment']),0)
  total_loss = round(sum(df_portfolio_features[df_portfolio_features['Current P/L%'] < 0]['Current']) - sum(df_portfolio_features[df_portfolio_features['Current P/L%'] < 0]['Investment']),0)

  cy_booked_percentage = round((cy_booked_amt)*100/current,2)
  py_booked_percentage = round((py_booked_amt)*100/investment,2)
  total_booked_percentage = round((total_booked_amt)*100/investment,2)

  print('-------------------')
  print('Initial Investment: ', format_amt(investment))
  print('CY Investment: ', format_amt(cy_invested))
  print('Reserve: ', format_amt(reserve_amt))
  print('Current: ',  format_amt(current))
  print('-------------------')
  print('Today PnL: '+ '{} ({}%)'.format(format_amt(today_pnl_amount), today_pnl_percentage))
  print('Current PnL: '+ '{} ({}%)'.format(format_amt(curr_pnl_amount), curr_pnl_percentage))
  print('CY Booked + Current PnL: '+ '{} ({}%)'.format(format_amt(cy_pnl_amount), cy_pnl_percentage))
  print('-------------------')
  print('Total profit: ', format_amt(total_profit))
  print('Total loss: ', format_amt(total_loss))
  print('-------------------')
  print('Total Booked + Current PnL: '+ '{} ({}%)'.format(format_amt(overall_pnl_amount), overall_pnl_percentage))
  print('Total Booked PnL: '+ '{} ({}%)'.format(format_amt(total_booked_amt), total_booked_percentage))
  print('Curr Year Booked PnL: '+ '{} ({}%)'.format(format_amt(cy_booked_amt), cy_booked_percentage))
  print('Prev Year Booked PnL: '+ '{} ({}%)'.format(format_amt(py_booked_amt), py_booked_percentage))
  print('===================')
  print('Est FTT: ',  format_amt(estimate_st))
  print('Est FTT PnL: '+ '{} ({}%)'.format(format_amt(est_st_pnl_amount), est_st_pnl_percentage))

  print('===================')
  print('Deployed: ', format_amt(investment))

  print('Current: ', format_amt(current))

  print('CAGR/XIRR %: '+'{}%'.format(cagr))

In [8]:
# get start and end date
start_date, end_date = get_start_end_date()

# get portfolio and prospects data
mypfs_df = get_mypfs_df()
mypps_df = get_mypps_df()
myinvmt_df = get_myinvmt_df()

# merge above datasets
mypf_df = pd.merge(mypfs_df, mypps_df, on="Symbol")

# seggregate dm and sv portfolio
dm_pf = mypf_df[mypf_df['InPortfolio'] == 'DM']
sv_pf = mypf_df[mypf_df['InPortfolio'] == 'SV']

# build portfolio stock dataframe
dm_stocks = get_stock_ids(dm_pf)
sv_stocks = get_stock_ids(sv_pf)
df_stocks = pd.concat([dm_pf,sv_pf], ignore_index = True)

# arrange common and diff stock features
common_cols = ['Symbol', 'Target', 'Criteria', 'Strategy', 'CumlRnk', 'LatestQtr', 'StarStock', 'Conviction', 'Category', 'InFolio', 'XIRR', 'MBQ']
diff_cols = ['Symbol', 'AvgCost', 'Shares']
df_stocks = arrange_features(df_stocks, common_cols, diff_cols)

# get common features
stock_ids = df_stocks['Symbol'].values
df_common_features = get_common_features(stock_ids, df_stocks)

df_common_features.reset_index(drop=True, inplace=True)
df_common_features.drop(['Date'], axis=1, inplace=True)
# get and print portfolio features
df_portfolio_features = get_portfolio_features(df_common_features)

print_portfolio_stats(df_portfolio_features, myinvmt_df)

df = df_portfolio_features
#plot_pie_chart(df, 'CapType', 'Current')
list_ox40n = list(df[df['MBQ'].str.contains('OX40N', na=False)]['Symbol'].values)

Run date time (IST): 2026-03-19 11:13:17
-------------------
qualified stocks: 86
with latest results: 26
still star stocks: 16
-------------------
Initial Investment:  1.36 C
CY Investment:  1.62 C
Reserve:  1.61 K
Current:  1.32 C
-------------------
Today PnL: -2.33 L (-1.73%)
Current PnL: -44.96 L (-27.67%)
CY Booked + Current PnL: -29.07 L (-17.89%)
-------------------
Total profit:  62.52 K
Total loss:  -45.58 L
-------------------
Total Booked + Current PnL: -2.09 L (-1.54%)
Total Booked PnL: 42.87 L (31.64%)
Curr Year Booked PnL: 15.89 L (12.02%)
Prev Year Booked PnL: 26.98 L (19.91%)
===================
Est FTT:  2.48 C
Est FTT PnL: 1.16 C (87.55%)
===================
Deployed:  1.36 C
Current:  1.32 C
CAGR/XIRR %: -1.24%

In [9]:
# top 5 near their targets
cols = ['Symbol', 'Today P/L%', 'Current P/L%', 'FTT%', 'OTT%', 'FTT Amt', 'Current P/L', 'Current', 'FTT', 'Dev%_PE', 'RSI_14','Conviction', 'Spread%',  'CumlRnk', 'RRR Ind', 'CurrAlloc%', 'Gained%', 'Criteria', 'Strategy', 'Category']
df_tmp = df_portfolio_features[~df_portfolio_features['Symbol'].isin(['ENRIN','BLUSPRING','DIGITIDE'])]
df_tmp = df_tmp.sort_values(by = 'FTT Amt', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
50,MASFIN,-1.10,-9.08,33.71,21.57,30031.0,-8895.0,89085.0,397.04,-21.41,38.0,H-SC,1.90,167.0,-0.30,0.67,22.15,XR,ATH,FINANCE
77,TTKPRESTIG,2.57,-36.30,57.14,0.09,36678.0,-36587.0,64190.0,770.00,48.99,43.0,M-SC,17.47,250.0,-1.00,0.49,8.46,OX40N,NTT,DURABLES
37,ICICIGI,-1.25,-4.21,24.58,19.34,47117.0,-8419.0,191690.0,2252.93,-19.34,35.0,X-MC,2.52,66.0,-0.18,1.45,5.97,X40,ATH,INSURANCE
67,SONACOMS,-1.82,-13.07,60.00,39.09,52763.0,-13221.0,87938.0,804.02,-31.14,47.0,M-MC,8.43,193.0,-0.25,0.67,24.40,AR,ATH,AUTO
2,ABBOTINDIA,-0.06,-11.57,33.52,18.07,53015.0,-20695.0,158160.0,35195.00,-24.65,42.0,X-MC,10.80,58.0,-0.39,1.20,0.27,X40,ATH,PHARMA

In [10]:
# top 5 today
df_tmp = df_portfolio_features.sort_values(by = 'Today P/L%', ascending=False)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
80,VALIANTORG,11.84,-44.88,215.94,74.15,194739.0,-73423.0,90182.0,838.0,-262.20,65.0,H-SC,29.10,145.0,-0.38,0.68,34.20,XR,NTT,CHEMICALS
77,TTKPRESTIG,2.57,-36.30,57.14,0.09,36678.0,-36587.0,64190.0,770.0,48.99,43.0,M-SC,17.47,250.0,-1.00,0.49,8.46,OX40N,NTT,DURABLES
72,TATAELXSI,2.53,-39.36,117.74,32.03,94123.0,-51894.0,79941.0,9161.0,-24.23,31.0,H-SC,19.12,158.0,-0.55,0.60,2.53,OX40N,NTT,IT
69,SURYODAY,2.12,-26.06,66.40,23.03,87918.0,-46665.0,132406.0,216.0,44.74,51.0,H-SC,6.59,166.0,-0.53,1.00,29.41,XR,NTT,BANKS
49,LAOPALA,0.95,-43.66,146.87,39.09,108484.0,-57241.0,73864.0,464.0,61.79,41.0,H-SC,13.83,154.0,-0.53,0.56,0.95,AR,NTT,CERAMICS

In [11]:
# bottom 5 today
df_tmp = df_portfolio_features.sort_values(by = 'Today P/L%', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
34,HDFCBANK,-4.57,-3.75,33.37,28.37,75443.0,-8806.0,226079.0,1073.00,-18.07,28.0,X-LC,10.13,26.0,-0.12,1.71,0.00,X40,BTT,BANKS
82,VOLTAS,-4.33,6.47,36.37,45.20,74249.0,12408.0,204150.0,1856.00,21.95,36.0,X-MC,6.72,79.0,0.17,1.54,13.71,XY25,NTT,AC
76,TRIDENT,-3.76,-37.03,104.08,28.51,60464.0,-34160.0,58094.0,48.00,-18.99,44.0,M-SC,13.43,223.0,-0.56,0.44,6.62,XR,NTT,TEXTILES
23,DIXON,-3.66,-24.84,83.50,37.92,163679.0,-64775.0,196023.0,18931.72,-68.06,45.0,X-MC,27.36,54.0,-0.40,1.48,5.23,X40N,ATH,IT
38,ICICIPRULI,-3.64,-6.13,39.27,30.73,72620.0,-12081.0,184924.0,790.00,-31.35,25.0,X-MC,3.04,78.0,-0.17,1.40,5.79,X40,ATH,INSURANCE

In [12]:
# top 5 to exit based on CumlRnk
df_tmp = df_portfolio_features[~df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])]
df_tmp = df_tmp[(df_tmp['Current P/L%'] > -1) & (df_tmp['Current P/L%'] < 1)].sort_values(by = 'CumlRnk', ascending=False)
df_tmp[cols].head()

Empty DataFrame
Columns: [Symbol, Today P/L%, Current P/L%, FTT%, OTT%, FTT Amt, Current P/L, Current, FTT, Dev%_PE, RSI_14, Conviction, Spread%, CumlRnk, RRR Ind, CurrAlloc%, Gained%, Criteria, Strategy, Category]
Index: []

In [13]:
# OX40N stocks to exit
df_tmp = df_portfolio_features[(df_portfolio_features['Symbol'].isin(list_ox40n))].sort_values(by = 'Current P/L%', ascending=False)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
26,FINCABLES,-3.30,7.41,93.57,107.91,148388.0,10941.0,158585.0,1641.55,-3.60,49.0,M-SC,8.07,220.0,0.07,1.20,19.31,OX40N,ATH,CABLES
77,TTKPRESTIG,2.57,-36.30,57.14,0.09,36678.0,-36587.0,64190.0,770.00,48.99,43.0,M-SC,17.47,250.0,-1.00,0.49,8.46,OX40N,NTT,DURABLES
66,SIS,-1.09,-36.50,90.96,21.26,64134.0,-40524.0,70508.0,528.00,1647.15,34.0,H-SC,13.55,168.0,-0.63,0.53,1.62,OX40N,NTT,MISC
18,CERA,-2.79,-36.68,95.64,23.89,106532.0,-64514.0,111389.0,9475.00,-38.90,50.0,H-SC,18.18,153.0,-0.61,0.84,7.04,OX40N,NTT,CERAMICS
70,SYMPHONY,-2.02,-38.78,63.29,-0.03,66311.0,-66367.0,104774.0,1306.00,-50.83,45.0,M-SC,14.85,205.0,-1.00,0.79,5.95,OX40N,NTT,DURABLES

In [14]:
# top 5 to book for rotation
df_tmp = df_portfolio_features[(df_portfolio_features['Current P/L%'] > 20) ].sort_values(by = 'CumlRnk', ascending=False)
df_tmp[cols].head()

Empty DataFrame
Columns: [Symbol, Today P/L%, Current P/L%, FTT%, OTT%, FTT Amt, Current P/L, Current, FTT, Dev%_PE, RSI_14, Conviction, Spread%, CumlRnk, RRR Ind, CurrAlloc%, Gained%, Criteria, Strategy, Category]
Index: []

In [15]:
# top 5 to monitor for exit
df_tmp = df_portfolio_features[~df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])]
df_tmp = df_tmp[(df_tmp['Current P/L%'] > 0) ].sort_values(by = 'Dev%_PE', ascending=False)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
26,FINCABLES,-3.30,7.41,93.57,107.91,148388.0,10941.0,158585.0,1641.55,-3.6,49.0,M-SC,8.07,220.0,0.07,1.20,19.31,OX40N,ATH,CABLES
1,ABB,-1.12,14.97,26.61,45.57,80041.0,39173.0,300792.0,7934.00,-26.1,60.0,H-MC,12.58,125.0,0.49,2.28,33.57,AR,NTT,ELECTRICAL

In [16]:
# top 5 to book for rotation from weak conviction
df_tmp = df_portfolio_features[~df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])]
df_tmp = df_tmp[~df_tmp['Criteria'].isin(['XY25','XY24','X40', 'X40N'])].sort_values(by = 'RRR Ind', ascending=False)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
1,ABB,-1.12,14.97,26.61,45.57,80041.0,39173.0,300792.0,7934.00,-26.10,60.0,H-MC,12.58,125.0,0.49,2.28,33.57,AR,NTT,ELECTRICAL
26,FINCABLES,-3.30,7.41,93.57,107.91,148388.0,10941.0,158585.0,1641.55,-3.60,49.0,M-SC,8.07,220.0,0.07,1.20,19.31,OX40N,ATH,CABLES
40,INDIAMART,-2.34,-11.95,134.78,106.72,146367.0,-14739.0,108597.0,4810.62,-60.35,37.0,H-SC,10.50,140.0,-0.10,0.82,8.63,AR,ATH,MISC
85,ZYDUSLIFE,-1.76,-6.81,45.54,35.63,88944.0,-14265.0,195309.0,1286.17,-18.92,42.0,H-MC,5.30,120.0,-0.16,1.48,8.73,AR,ATH,PHARMA
84,WIPRO,-2.28,-22.13,121.22,72.27,159953.0,-37495.0,131953.0,420.00,-29.71,28.0,M-LC,16.55,98.0,-0.23,1.00,0.00,XR,NTT,IT

In [17]:
# top 5 to accumulate based on lowest RSI_14
df_tmp = df_portfolio_features[df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])].sort_values(by = 'RSI_14', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
12,BATAINDIA,-2.47,-57.65,219.27,35.20,119480.0,-74180.0,54490.0,2096.00,-28.52,15.0,X-SC,29.29,91.0,-0.62,0.41,0.00,X40,NTT,FOOTWEAR
53,PGHH,-0.99,-25.67,77.59,32.01,123151.0,-54800.0,158720.0,17616.87,-49.68,15.0,X-MC,13.90,57.0,-0.44,1.20,0.00,X40,ATH,FMCG
58,RELAXO,-3.36,-64.25,326.09,52.31,169202.0,-93272.0,51888.0,1176.00,-61.96,20.0,X-SC,23.58,92.0,-0.55,0.39,0.16,X40N,NTT,FOOTWEAR
3,ACC,-2.58,-38.73,185.32,74.81,304444.0,-103848.0,164280.0,3906.00,-56.56,23.0,X-SC,15.84,85.0,-0.34,1.24,0.00,XY24,BTT,CEMENT
73,TCS,-2.45,-30.11,81.09,26.57,262571.0,-139471.0,323802.0,4311.59,-40.68,24.0,X-LC,16.29,2.0,-0.53,2.45,0.00,X40,ATH,IT

In [18]:
# top 5 to accumulate based on Spread and CumlRnk
df_tmp = df_portfolio_features[df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])]
df_tmp = df_tmp[(df_tmp['CumlRnk'] < 100)].sort_values(by = 'Spread%', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
78,UNITDSPR,-1.99,-4.94,27.05,20.77,60205.0,-11576.0,222568.0,1644.00,-15.72,39.0,X-MC,1.00,64.0,-0.19,1.68,1.43,X40N,NTT,BREWERIES
37,ICICIGI,-1.25,-4.21,24.58,19.34,47117.0,-8419.0,191690.0,2252.93,-19.34,35.0,X-MC,2.52,66.0,-0.18,1.45,5.97,X40,ATH,INSURANCE
38,ICICIPRULI,-3.64,-6.13,39.27,30.73,72620.0,-12081.0,184924.0,790.00,-31.35,25.0,X-MC,3.04,78.0,-0.17,1.40,5.79,X40,ATH,INSURANCE
59,RELIANCE,-0.01,-9.62,38.64,25.30,70183.0,-19331.0,181632.0,1952.00,-11.96,50.0,X-LC,3.36,21.0,-0.28,1.37,21.27,XY25,BTT,REFINERIES
65,SIEMENS,-2.22,-15.38,48.33,25.51,76105.0,-28625.0,157470.0,4671.50,32.32,46.0,H-LC,3.54,51.0,-0.38,1.19,15.96,AR,ATH,ELECTRICAL

In [19]:
# top 5 to accumulate based on lowest Gained%
df_tmp = df_portfolio_features[df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])].sort_values(by = 'Gained%', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
3,ACC,-2.58,-38.73,185.32,74.81,304444.0,-103848.0,164280.0,3906.00,-56.56,23.0,X-SC,15.84,85.0,-0.34,1.24,0.0,XY24,BTT,CEMENT
6,ASIANPAINT,-2.95,-20.99,57.61,24.52,129007.0,-59508.0,223931.0,3460.25,-20.26,33.0,X-LC,8.42,30.0,-0.46,1.69,0.0,X40,ATH,PAINTS
12,BATAINDIA,-2.47,-57.65,219.27,35.20,119480.0,-74180.0,54490.0,2096.00,-28.52,15.0,X-SC,29.29,91.0,-0.62,0.41,0.0,X40,NTT,FOOTWEAR
21,DABUR,-3.04,-14.35,67.77,43.70,143996.0,-35590.0,212478.0,735.00,-22.24,26.0,X-MC,3.95,70.0,-0.25,1.61,0.0,XY24,BTT,FMCG
20,COLPAL,-1.26,-27.21,94.40,41.51,180974.0,-71655.0,191710.0,3726.84,-11.90,29.0,X-MC,4.33,62.0,-0.40,1.45,0.0,XY25,ATH,FMCG

In [20]:
# top 5 to accumulate based on lowest CurrAlloc%
df_tmp = df_portfolio_features[df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])].sort_values(by = 'CurrAlloc%', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
58,RELAXO,-3.36,-64.25,326.09,52.31,169202.0,-93272.0,51888.0,1176.00,-61.96,20.0,X-SC,23.58,92.0,-0.55,0.39,0.16,X40N,NTT,FOOTWEAR
12,BATAINDIA,-2.47,-57.65,219.27,35.20,119480.0,-74180.0,54490.0,2096.00,-28.52,15.0,X-SC,29.29,91.0,-0.62,0.41,0.00,X40,NTT,FOOTWEAR
54,QUESS,-1.07,-25.89,134.66,73.90,106573.0,-27651.0,79142.0,424.00,-60.33,38.0,X-SC,20.23,80.0,-0.26,0.60,3.14,XY24,NTT,MISC
36,HONAUT,-1.54,-25.34,102.66,51.31,147805.0,-48863.0,143975.0,58357.33,-37.92,29.0,X-SC,14.74,90.0,-0.33,1.09,0.00,X40N,ATH,ELECTRICAL
51,MEDANTA,-1.40,-11.94,44.36,27.12,68953.0,-21078.0,155439.0,1486.00,-14.71,32.0,X-SC,10.50,87.0,-0.31,1.18,0.00,XY24,NTT,HEALTHCARE

In [21]:
# top 5 to accumulate based on CumlRnk
df_tmp = df_portfolio_features.sort_values(by = 'CumlRnk', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
45,ITC,-1.09,-20.78,50.29,19.06,135517.0,-70694.0,269472.0,452.00,-56.73,35.0,X-LC,17.56,1.0,-0.52,2.04,0.00,X40,NTT,FMCG
73,TCS,-2.45,-30.11,81.09,26.57,262571.0,-139471.0,323802.0,4311.59,-40.68,24.0,X-LC,16.29,2.0,-0.53,2.45,0.00,X40,ATH,IT
43,INFY,-2.86,-16.21,60.22,34.24,157873.0,-50728.0,262160.0,1972.00,-33.96,28.0,X-LC,14.52,3.0,-0.32,1.98,0.00,X40,NTT,IT
75,TMPV,-3.40,-28.59,91.27,36.58,231914.0,-101744.0,254097.0,600.00,-84.72,33.0,X-LC,4.38,4.0,-0.44,1.92,0.00,XY24,NTT,AUTO
33,HCLTECH,-2.25,-13.90,43.83,23.83,91294.0,-33632.0,208292.0,1908.19,-9.43,33.0,X-LC,11.22,8.0,-0.37,1.58,0.42,X40,ATH,IT

In [22]:
# top 5 for average up
df_tmp = df_portfolio_features[(df_portfolio_features['Dev%_200'] > 5)].sort_values(by = 'CurrAlloc%', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
67,SONACOMS,-1.82,-13.07,60.00,39.09,52763.0,-13221.0,87938.0,804.02,-31.14,47.0,M-MC,8.43,193.0,-0.25,0.67,24.40,AR,ATH,AUTO
1,ABB,-1.12,14.97,26.61,45.57,80041.0,39173.0,300792.0,7934.00,-26.10,60.0,H-MC,12.58,125.0,0.49,2.28,33.57,AR,NTT,ELECTRICAL

In [23]:
# top 5 RSP
df_tmp = df_portfolio_features.sort_values(by = 'RSP', ascending=False)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
1,ABB,-1.12,14.97,26.61,45.57,80041.0,39173.0,300792.0,7934.00,-26.10,60.0,H-MC,12.58,125.0,0.49,2.28,33.57,AR,NTT,ELECTRICAL
80,VALIANTORG,11.84,-44.88,215.94,74.15,194739.0,-73423.0,90182.0,838.00,-262.20,65.0,H-SC,29.10,145.0,-0.38,0.68,34.20,XR,NTT,CHEMICALS
26,FINCABLES,-3.30,7.41,93.57,107.91,148388.0,10941.0,158585.0,1641.55,-3.60,49.0,M-SC,8.07,220.0,0.07,1.20,19.31,OX40N,ATH,CABLES
69,SURYODAY,2.12,-26.06,66.40,23.03,87918.0,-46665.0,132406.0,216.00,44.74,51.0,H-SC,6.59,166.0,-0.53,1.00,29.41,XR,NTT,BANKS
65,SIEMENS,-2.22,-15.38,48.33,25.51,76105.0,-28625.0,157470.0,4671.50,32.32,46.0,H-LC,3.54,51.0,-0.38,1.19,15.96,AR,ATH,ELECTRICAL

In [24]:
# Top N allocation
df_tmp = df_portfolio_features.sort_values(by = 'CurrAlloc%', ascending=False)
top_n_values = [10, 25, 50]

sum_df = pd.DataFrame({
    'Top_N': top_n_values,
    'Sum_Alloc%': [df_tmp['CurrAlloc%'].head(n).sum() for n in top_n_values]
})

sum_df

   Top_N  Sum_Alloc%
0     10       20.62
1     25       45.47
2     50       77.86

In [25]:
# market-cap-wise allocation
df_tmp = df_portfolio_features[cols]
df_tmp.groupby(df_tmp['Conviction'].str[-2:])['CurrAlloc%'].sum().sort_values(ascending=False)

Conviction
SC    44.48
MC    30.14
LC    25.31
Name: CurrAlloc%, dtype: float64

In [26]:
# criteria-wise allocation
df_portfolio_features.groupby('Criteria')['CurrAlloc%'].sum().sort_values(ascending=False)

Criteria
XY24     26.98
X40      25.33
X40N     15.15
AR        9.18
XR        8.33
XY25      7.36
OX40N     6.82
SR        0.78
Name: CurrAlloc%, dtype: float64

In [27]:
# conviction-wise allocation
df_portfolio_features.groupby('Conviction')['CurrAlloc%'].sum().sort_values(ascending=False)

Conviction
X-LC    23.12
X-MC    22.64
H-SC    21.66
X-SC    12.16
M-SC    10.10
H-MC     5.07
M-MC     2.08
H-LC     1.19
M-LC     1.00
L-SC     0.56
L-MC     0.35
Name: CurrAlloc%, dtype: float64

In [28]:
# sector-wise stats
df_tmp = df_portfolio_features.groupby('Category')[['CurrAlloc%', 'Current', 'Current P/L', 'FTT Amt']].sum().sort_values(by=['Current', 'Current P/L'], ascending=False)
df_tmp['Current P/L%'] = round(df_tmp['Current P/L'] * 100 / df_tmp['Current'], 2)
df_tmp['FTT%'] = round(df_tmp['FTT Amt'] * 100 / df_tmp['Current'], 2)
cols = ['CurrAlloc%', 'Current P/L%', 'FTT%']
df_tmp[cols].sort_values(by=['CurrAlloc%'], ascending=False)

               CurrAlloc%  Current P/L%    FTT%
Category
FMCG                15.06        -25.53   70.10
FINANCE             13.15        -23.57   73.92
IT                  11.58        -47.10  121.96
MISC                 6.96        -45.83  109.17
ELECTRICAL           6.63        -10.63   52.99
PAINTS               5.03        -47.82   73.49
INSURANCE            4.75         -8.14   45.14
BANKS                4.67        -24.46   87.63
PHARMA               4.14         -7.53   41.38
AUTO                 3.67        -35.01   88.58
AC                   2.09        -15.52   46.84
HEALTHCARE           1.92        -41.04   77.85
DURABLES             1.85        -58.11   96.57
TRAVEL               1.82        -85.33  178.13
FOOTWEAR             1.77        -88.24  163.72
BREWERIES            1.68         -5.20   27.05
APPARELS             1.65        -22.75   64.62
REALTY               1.46        -14.74   33.59
CERAMICS             1.40        -65.72  116.07
REFINERIES           1.37        -10.64   38.64
CEMENT               1.24        -63.21  185.32
CABLES               1.20          6.90   93.57
CHEMICALS            1.10        -80.79  228.29
ENGINEERING          1.09        -67.50  144.11
JEWELLERY            1.08       -123.47  201.11
ENTERTAINMENT        0.77        -89.78  202.96
TEXTILES             0.44        -58.80  104.08
HOTELS               0.36       -140.41  225.20

In [29]:
# money to be made criteria-wise
df_portfolio_features.groupby('Criteria')['FTT Amt'].agg(['sum', 'count']).sort_values(by='sum', ascending=False)

                sum  count
Criteria
XY24      4030327.0     21
X40       1825213.0     16
XR        1388760.0     12
AR        1360213.0     10
X40N      1296645.0     10
OX40N      888947.0     10
XY25       466534.0      5
SR         315030.0      2

In [30]:
# money to be made conviction-wise
df_portfolio_features.groupby('Conviction')['FTT Amt'].agg(['sum', 'count']).sort_values(by='sum', ascending=False)

                  sum  count
Conviction
H-SC        3925961.0     24
X-MC        1739242.0     15
X-LC        1719012.0     13
M-SC        1582901.0     14
X-SC        1574911.0     10
H-MC         408940.0      3
L-SC         216970.0      2
M-LC         159953.0      1
M-MC         111892.0      2
H-LC          76105.0      1
L-MC          55782.0      1

In [31]:
# money to be made criteria and conviction-wise
df_portfolio_features.groupby(['Conviction', 'Criteria'])['FTT Amt'].agg(['sum', 'count']).sort_values(by='sum', ascending=False)

                           sum  count
Conviction Criteria
H-SC       XY24      1363384.0      6
           AR         984457.0      5
X-LC       X40        932086.0      7
M-SC       XY24       923086.0      6
H-SC       XR         872976.0      7
X-SC       XY24       857455.0      4
X-MC       X40        681318.0      7
           X40N       531616.0      4
X-SC       X40N       505647.0      4
H-SC       OX40N      390114.0      4
M-SC       OX40N      388229.0      5
X-LC       XY24       375362.0      2
H-SC       SR         315030.0      2
X-MC       XY24       271085.0      2
X-LC       X40N       259382.0      2
X-MC       XY25       255223.0      2
H-MC       XY24       239955.0      1
X-SC       X40        211809.0      2
M-SC       XR         193683.0      2
H-MC       AR         168985.0      2
M-LC       XR         159953.0      1
X-LC       XY25       152182.0      2
L-SC       OX40N      110604.0      1
           XR         106366.0      1
M-SC       AR          77903.0      1
H-LC       AR          76105.0      1
M-MC       XY25        59129.0      1
L-MC       XR          55782.0      1
M-MC       AR          52763.0      1

In [32]:
# notebook execution time

end_time = time.time()
execution_time = round(end_time - start_time, 0)
print(f"Notebook execution time: {execution_time} seconds")

Notebook execution time: 50.0 seconds