<a href="https://colab.research.google.com/github/ankit-rathi/Quantvesting_v2/blob/main/myStocks_Portfolio_Analysis.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
'''
!pip install pandas==2.2.2 -qq
!pip install pyxirr -qq
!pip install ta -qq
!pip install yfinance==0.2.59 -qq
'''

'\n!pip install pandas==2.2.2 -qq\n!pip install pyxirr -qq\n!pip install ta -qq\n!pip install yfinance==0.2.59 -qq\n'

In [2]:
# import libraries

import numpy as np
import pandas as pd
import datetime
import warnings
warnings.filterwarnings('ignore')
import yfinance as yfin
import ta
import matplotlib.pyplot as plt
import requests

In [3]:
# notebook start time
import time
import datetime
import pytz

start_time = time.time()

# function to print date timestamp
def print_date_time():
  tz_NY = pytz.timezone('Asia/Kolkata')
  datetime_NY = datetime.datetime.now(tz_NY)
  print("Run date time (IST):", datetime_NY.strftime("%Y-%m-%d %H:%M:%S"))

In [4]:
# function to get booked and reserved amount
def get_amt():
  # fetch the JSON data from the URL
  url = "https://raw.githubusercontent.com/ankit-rathi/Tradevesting_v1/main/data/myPortfolioAmts.json"
  response = requests.get(url)
  pf_amts = response.json()  # parse the JSON data

  # extract values from the JSON
  py_booked_amt_dm = pf_amts["py_booked_amt_dm"]
  py_booked_amt_sv = pf_amts["py_booked_amt_sv"]
  cy_booked_amt_dm = pf_amts["cy_booked_amt_dm"]
  cy_booked_amt_sv = pf_amts["cy_booked_amt_sv"]
  reserve_amt_dm = pf_amts["reserve_amt_dm"]
  reserve_amt_sv = pf_amts["reserve_amt_sv"]

  # perform calculations
  py_booked_amt = py_booked_amt_dm + py_booked_amt_sv
  cy_booked_amt = cy_booked_amt_dm + cy_booked_amt_sv
  reserve_amt = reserve_amt_dm + reserve_amt_sv
  total_booked_amt = py_booked_amt + cy_booked_amt

  return total_booked_amt, reserve_amt, cy_booked_amt, py_booked_amt

gen_output = 0

In [5]:
# function to format the amount
def format_amt(number):
    abs_number = abs(number)

    if abs_number >= 1_00_00_000:  # Crores
        formatted_amt = f"{number / 1_00_00_000:.2f} C"
    elif abs_number >= 1_00_000:  # Lakhs
        formatted_amt = f"{number / 1_00_000:.2f} L"
    elif abs_number >= 1_000:  # Thousands
        formatted_amt = f"{number / 1_000:.2f} K"
    else:
        formatted_amt = f"{number:.2f}"

    return formatted_amt

# function to set start and end date
def get_start_end_date():
  start_date = (datetime.date.today() + datetime.timedelta(days=-365)).strftime('%Y-%m-%d')
  end_date = (datetime.date.today() + datetime.timedelta(days=1)).strftime('%Y-%m-%d')
  return start_date, end_date

# function to fetch my portfolio csv
def get_mypfs_df():
  mypfs_df = pd.read_csv('https://raw.githubusercontent.com/ankit-rathi/Tradevesting_v1/main/data/myPortfolioStocks.csv')
  return mypfs_df

# function to fetch my prospects csv
def get_mypps_df():
  mypps_df = pd.read_csv('https://raw.githubusercontent.com/ankit-rathi/Tradevesting_v1/main/data/myProspectsScrips.csv')
  return mypps_df

# function to fetch screener data
def get_myscreen_df():
  myscreen_df = pd.read_csv('https://raw.githubusercontent.com/ankit-rathi/Tradevesting_v1/main/data/myScreenerDB.csv')
  return myscreen_df

# function to fetch momentum data
def get_myinvmt_df():
  myinvmt_df = pd.read_csv('https://raw.githubusercontent.com/ankit-rathi/Tradevesting_v1/main/data/myInvestments.csv')
  return myinvmt_df

# function to get the stock ids
def get_stock_ids(df_pf):
  stock_n100 = df_pf['Symbol'].unique()

  exclude = ['CADILAHC','MMTC', 'MASFIN']

  stock_ids = df_pf[~df_pf['Symbol'].isin(exclude) ]['Symbol'].unique()

  #mypf = mypf[mypf.Forecast.notnull()]
  #stock_ids = mypf['Symbol'].unique()

  #stock_ids.sort()
  return stock_ids

# get features from screener data
def get_screener_features():
  myscreen_df = get_myscreen_df()
  cols = ['Symbol', 'EPS', 'MedPE', 'ROCE%', 'ROE%', 'CapType']
  return myscreen_df[cols]

# get relative strength
def get_relative_strength(stock_list):

    # Dictionary to store stock tickers and their corresponding percentage price change
    stock_changes = {}

    # Loop through each stock and fetch its price data
    for stock in stock_list:
        try:
            # Download the stock data for the given date range
            stock_data = yfin.Ticker(stock + '.NS').history(period='1mo', interval='1d')[map(str.title, ['open', 'close', 'low', 'high', 'volume'])]

            # Calculate the percentage change for the stock
            if len(stock_data) > 0:
                start_price = stock_data['Close'].iloc[0]
                end_price = stock_data['Close'].iloc[-1]
                percent_change = round(((end_price - start_price) / start_price) * 100, 2)
                stock_changes[stock] = percent_change
            else:
                stock_changes[stock] = np.nan  # If no data is available, set to NaN

        except Exception as e:
            print(f"Error fetching data for {stock}: {e}")
            stock_changes[stock] = np.nan

    # Create a DataFrame with stock tickers and their percentage changes
    df = pd.DataFrame(list(stock_changes.items()), columns=['Symbol', 'Percent_Change'])

    # Drop any stocks with missing data (NaN values)
    df = df.dropna()

    # Calculate the percentile rank based on percentage change
    df['RSP'] = round(df['Percent_Change'].rank(pct=True) * 100, 2)
    cols = ['Symbol', 'RSP']
    df = df[cols]
    # Sort by percentile rank (optional)
    df = df.sort_values(by='RSP', ascending=False).reset_index(drop=True)

    return df

In [6]:
# function to get stock technicals
def stock_prec_dev(stock_symbol):
    #stock_symbol = 'ULTRACEMCO.NS'
    short_window = 20
    mid_window = 50
    long_window = 200
    moving_avg = 'SMA'

    start = datetime.datetime(*map(int, start_date.split('-')))
    end = datetime.datetime(*map(int, end_date.split('-')))

    stock_df = yfin.Ticker(stock_symbol + '.NS').history(period='max', interval='1d')[map(str.title, ['open', 'close', 'low', 'high', 'volume'])]

    stock_df['Max'] = round(max(stock_df['Close']),2)
    stock_df = stock_df[(stock_df.index <= end_date) & (stock_df.index >= start_date)]
    stock_df['200_SMA'] = round(stock_df['Close'].rolling(window = 200, min_periods = 1).mean(),0)
    stock_df['Dev%_200'] = round((stock_df['Close'] - stock_df['200_SMA'])*100/stock_df['200_SMA'],2)
    stock_df.dropna(axis = 0, inplace = True) # remove any null rows

    stock_df['20_SMA'] = stock_df['Close'].rolling(window=20).mean()
    stock_df['50_SMA'] = stock_df['Close'].rolling(window=50).mean()
    stock_df['Symbol'] = stock_symbol

    stock_df['Close'] = round(stock_df['Close'],2)
    stock_df['Min'] = round(min(stock_df['Close']),2)
    stock_df['RSI_14'] = ta.momentum.RSIIndicator(close=stock_df['Close'], window=14).rsi()
    stock_df['RSI_14'] = round(stock_df['RSI_14'],0)
    stock_df['Prev_Close'] = stock_df['Close'].shift(1)
    stock_df.drop(['Open', 'Low', 'High', 'Volume'], axis=1, inplace=True)
    stock_df = stock_df.tail(1)

    max_SMA = max(stock_df['20_SMA'].item(), stock_df['50_SMA'].item(), stock_df['200_SMA'].item())
    min_SMA = min(stock_df['20_SMA'].item(), stock_df['50_SMA'].item(), stock_df['200_SMA'].item())
    ABS_Spread = max_SMA - min_SMA
    stock_df['Spread%'] = round((ABS_Spread / stock_df['200_SMA'].item()) * 100,2)

    return stock_df

# function to compute stock attributes
def get_common_features(stock_ids, df_mypf):

  df_prec_dev = pd.DataFrame()
  df_tmp = get_screener_features()
  df_rs = get_relative_strength(stock_ids)

  for stock_id in stock_ids:
      tmp = stock_prec_dev(stock_id)
      tmp = tmp.reset_index()
      df_prec_dev = pd.concat([df_prec_dev, tmp], ignore_index = True)
  df_prec_dev = pd.merge(df_prec_dev, df_mypf, on= 'Symbol')
  df_prec_dev = pd.merge(df_prec_dev, df_tmp, on= 'Symbol', how='left')
  df_prec_dev = pd.merge(df_prec_dev, df_rs, on= 'Symbol', how='left')
  #print(df_prec_dev.columns)
  df_prec_dev['Curr_PE'] = round(df_prec_dev['Close']/df_prec_dev['EPS'],1)
  df_prec_dev['Dev%_PE'] = round((df_prec_dev['Curr_PE'] - df_prec_dev['MedPE'])*100/df_prec_dev['MedPE'],2)
  df_prec_dev['Conviction'] = df_prec_dev['Conviction'] + '-' + df_prec_dev['CapType']
  return df_prec_dev

# function to arrange stock features
def arrange_features(df_stocks, common_cols, diff_cols):
  df_stocks_common = df_stocks[common_cols].drop_duplicates()
  df_stocks_diff = df_stocks[diff_cols]
  df_stocks_diff['Investment'] = df_stocks_diff['AvgCost'] * df_stocks_diff['Shares']
  df_stocks_diff = df_stocks_diff.groupby(['Symbol'])[['Shares', 'Investment']].aggregate(['sum']).reset_index()
  df_stocks_diff.columns = ['Symbol', 'Shares', 'Investment']
  df_stocks_diff['AvgCost'] = round(df_stocks_diff['Investment']/df_stocks_diff['Shares'],2)
  df_stocks = pd.merge(df_stocks_diff, df_stocks_common, on='Symbol')
  return df_stocks

# plot fact distribution across dimension
def plot_pie_chart(df, dimension, fact):
  # grouping the data by category and calculating the sum of fact for each type
  grouped_data = df.groupby(dimension)[fact].sum()

  # sorting the grouped data in descending order
  grouped_data = grouped_data.sort_values(ascending=False)

  # creating a pie chart
  grouped_data.plot.pie(autopct='%1.1f%%', startangle=90, figsize=(6, 6))

  # adding a title and displaying the plot
  plt.title(f'{dimension} {fact} Distribution')
  plt.ylabel('')  # To hide the y-label
  plt.show()

In [7]:
# function to get portfolio features

def get_portfolio_features(df_common_features):

  print_date_time()
  print('-------------------')

  #df_common_features["Target"] = df_common_features["Target"].fillna(df_common_features["Max"])
  df_common_features['NTT'] = np.where(df_common_features['Strategy']== 'NTT', df_common_features["Target"], df_common_features['Max'])
  df_common_features['LTT'] = np.where(df_common_features['Strategy']== 'BTT', df_common_features["Target"], df_common_features['Max'])
  df_common_features['BOL'] = df_common_features['Min']

  tmp_df = df_common_features[df_common_features['Symbol'].isin(mypf_df[mypf_df['InPortfolio'] != 'NA'].Symbol.values)]
  print('qualified stocks: '+str(len(tmp_df['Symbol'].unique())))
  tmp_df1 = tmp_df[tmp_df['LatestQtr'] == 1]
  print('with latest results: '+str(len(tmp_df1['Symbol'].unique())))
  tmp_df1 = tmp_df1[tmp_df1['StarStock'] == 1]
  print('still star stocks: '+str(len(tmp_df1['Symbol'].unique())))
  tmp_df['Investment'] = tmp_df['AvgCost'] * tmp_df['Shares']
  tmp_df['Current'] = round(tmp_df['Close'] * tmp_df['Shares'],0)
  tmp_df['Previous'] = tmp_df['Prev_Close'] * tmp_df['Shares']
  tmp_df['EstimatedST'] = tmp_df['NTT'] * tmp_df['Shares']
  tmp_df['EstimatedLT'] = tmp_df['LTT'] * tmp_df['Shares']
  tmp_df['Current P/L'] = round((tmp_df['Current'] - tmp_df['Investment']),0)
  tmp_df['Today P/L%'] = round((tmp_df['Current'] - tmp_df['Previous'])*100/tmp_df['Previous'],2)
  tmp_df['Current P/L%'] = round((tmp_df['Current'] - tmp_df['Investment'])*100/tmp_df['Investment'],2)
  tmp_df['EstimatedST P/L%'] = round((tmp_df['EstimatedST'] - tmp_df['Investment'])*100/tmp_df['Investment'],2)
  tmp_df['EstimatedLT P/L%'] = round((tmp_df['EstimatedLT'] - tmp_df['Investment'])*100/tmp_df['Investment'],2)
  tmp_df['NTT%'] = round((tmp_df['NTT'] - tmp_df['Close'])*100/tmp_df['Close'],2)
  tmp_df['LTT%'] = round((tmp_df['LTT'] - tmp_df['Close'])*100/tmp_df['Close'],2)
  tmp_df['Gained%'] = round((tmp_df['Close'] - tmp_df['BOL'])*100/tmp_df['BOL'],2)
  investment = round(sum(tmp_df['AvgCost']*tmp_df['Shares']),0)
  current = round(sum(tmp_df['Close']*tmp_df['Shares']),0)
  tmp_df['InitAlloc%'] = round(tmp_df['Investment']*100/investment,2)
  tmp_df['CurrAlloc%'] = round(tmp_df['Current']*100/current,2)
  tmp_df['FTT'] = tmp_df['LTT']
  tmp_df.loc[tmp_df['Strategy'] == 'NTT', 'FTT'] = tmp_df['NTT']
  tmp_df['FTT%'] = tmp_df['LTT%']
  tmp_df.loc[tmp_df['Strategy'] == 'NTT', 'FTT%'] = tmp_df['NTT%']
  tmp_df['FTT Amt'] = round(tmp_df['FTT%'] * tmp_df['Current']/100,0)
  tmp_df['OTT%'] = round((tmp_df['FTT'] - tmp_df['AvgCost'])*100/tmp_df['AvgCost'],2)
  tmp_df['RRR Ind'] = round(tmp_df['Current P/L']/tmp_df['FTT Amt'],2)
  tmp_df['Risk Ind'] = round(tmp_df['Current P/L%']*tmp_df['CurrAlloc%'],0)

  return tmp_df

# function to print portfolio features
def print_portfolio_stats(df_portfolio_features, myinvmt_df):
  from pyxirr import xirr

  total_booked_amt, reserve_amt, cy_booked_amt, py_booked_amt = get_amt()

  dates = myinvmt_df['Date'].values
  dates = np.append(dates, datetime.date.today().strftime('%d-%b-%y'))
  investment = myinvmt_df['Investment'].values
  dates= pd.to_datetime(dates)

  current = round(sum(df_portfolio_features['Close']*df_portfolio_features['Shares']),0) + reserve_amt
  investment_xirr = np.append(investment, current)
  cagr = round(xirr(pd.DataFrame({"dates": dates, "amounts": investment_xirr}))*100,2)

  investment = -sum(investment)
  invested = round(sum(df_portfolio_features['AvgCost']*df_portfolio_features['Shares']),0) + reserve_amt
  previous = round(sum(df_portfolio_features['Prev_Close']*df_portfolio_features['Shares']),0) + reserve_amt
  cy_invested = investment + py_booked_amt

  today_pnl_amount = current-previous
  today_pnl_percentage = round((current-previous)*100/previous,2)

  curr_pnl_amount = current-invested
  curr_pnl_percentage = round((curr_pnl_amount)*100/(cy_invested),2)

  cy_pnl_amount = cy_booked_amt + curr_pnl_amount
  cy_pnl_percentage = round((cy_pnl_amount)*100/cy_invested,2)

  overall_pnl_amount = total_booked_amt + curr_pnl_amount
  overall_pnl_percentage = round((overall_pnl_amount)*100/investment,2)

  estimate_st = round(sum(df_portfolio_features['FTT']*df_portfolio_features['Shares']),0)  + reserve_amt
  est_st_pnl_amount = estimate_st-current
  est_st_pnl_percentage = round((est_st_pnl_amount)*100/current,2)

  estimate_lt = round(sum(df_portfolio_features['LTT']*df_portfolio_features['Shares']),0)  + reserve_amt
  est_lt_pnl_amount = estimate_lt-current
  est_lt_pnl_percentage = round((est_lt_pnl_amount)*100/current,2)

  total_profit = round(sum(df_portfolio_features[df_portfolio_features['Current P/L%'] > 0]['Current']) - sum(df_portfolio_features[df_portfolio_features['Current P/L%'] > 0]['Investment']),0)
  total_loss = round(sum(df_portfolio_features[df_portfolio_features['Current P/L%'] < 0]['Current']) - sum(df_portfolio_features[df_portfolio_features['Current P/L%'] < 0]['Investment']),0)

  cy_booked_percentage = round((cy_booked_amt)*100/current,2)
  py_booked_percentage = round((py_booked_amt)*100/investment,2)
  total_booked_percentage = round((total_booked_amt)*100/investment,2)

  print('-------------------')
  print('Initial Investment: ', format_amt(investment))
  print('CY Investment: ', format_amt(cy_invested))
  print('Reserve: ', format_amt(reserve_amt))
  print('Current: ',  format_amt(current))
  print('-------------------')
  print('Today PnL: '+ '{} ({}%)'.format(format_amt(today_pnl_amount), today_pnl_percentage))
  print('Current PnL: '+ '{} ({}%)'.format(format_amt(curr_pnl_amount), curr_pnl_percentage))
  print('CY Booked + Current PnL: '+ '{} ({}%)'.format(format_amt(cy_pnl_amount), cy_pnl_percentage))
  print('-------------------')
  print('Total profit: ', format_amt(total_profit))
  print('Total loss: ', format_amt(total_loss))
  print('-------------------')
  print('Total Booked + Current PnL: '+ '{} ({}%)'.format(format_amt(overall_pnl_amount), overall_pnl_percentage))
  print('Total Booked PnL: '+ '{} ({}%)'.format(format_amt(total_booked_amt), total_booked_percentage))
  print('Curr Year Booked PnL: '+ '{} ({}%)'.format(format_amt(cy_booked_amt), cy_booked_percentage))
  print('Prev Year Booked PnL: '+ '{} ({}%)'.format(format_amt(py_booked_amt), py_booked_percentage))
  print('===================')
  print('Est FTT: ',  format_amt(estimate_st))
  print('Est FTT PnL: '+ '{} ({}%)'.format(format_amt(est_st_pnl_amount), est_st_pnl_percentage))

  print('===================')
  print('Deployed: ', format_amt(investment))

  print('Current: ', format_amt(current))

  print('CAGR/XIRR %: '+'{}%'.format(cagr))

In [8]:
# get start and end date
start_date, end_date = get_start_end_date()

# get portfolio and prospects data
mypfs_df = get_mypfs_df()
mypps_df = get_mypps_df()
myinvmt_df = get_myinvmt_df()

# merge above datasets
mypf_df = pd.merge(mypfs_df, mypps_df, on="Symbol")

# seggregate dm and sv portfolio
dm_pf = mypf_df[mypf_df['InPortfolio'] == 'DM']
sv_pf = mypf_df[mypf_df['InPortfolio'] == 'SV']

# build portfolio stock dataframe
dm_stocks = get_stock_ids(dm_pf)
sv_stocks = get_stock_ids(sv_pf)
df_stocks = pd.concat([dm_pf,sv_pf], ignore_index = True)

# arrange common and diff stock features
common_cols = ['Symbol', 'Target', 'Criteria', 'Strategy', 'CumlRnk', 'LatestQtr', 'StarStock', 'Conviction', 'Category', 'InFolio', 'XIRR', 'MBQ']
diff_cols = ['Symbol', 'AvgCost', 'Shares']
df_stocks = arrange_features(df_stocks, common_cols, diff_cols)

# get common features
stock_ids = df_stocks['Symbol'].values
df_common_features = get_common_features(stock_ids, df_stocks)

df_common_features.reset_index(drop=True, inplace=True)
df_common_features.drop(['Date'], axis=1, inplace=True)
# get and print portfolio features
df_portfolio_features = get_portfolio_features(df_common_features)

print_portfolio_stats(df_portfolio_features, myinvmt_df)

df = df_portfolio_features
#plot_pie_chart(df, 'CapType', 'Current')
list_ox40n = list(df[df['MBQ'].str.contains('OX40N', na=False)]['Symbol'].values)

Run date time (IST): 2026-03-16 13:19:24
-------------------
qualified stocks: 86
with latest results: 26
still star stocks: 15
-------------------
Initial Investment:  1.36 C
CY Investment:  1.62 C
Reserve:  66.25 K
Current:  1.31 C
-------------------
Today PnL: -2.40 L (-1.8%)
Current PnL: -46.17 L (-28.41%)
CY Booked + Current PnL: -30.49 L (-18.76%)
-------------------
Total profit:  79.12 K
Total loss:  -46.96 L
-------------------
Total Booked + Current PnL: -3.51 L (-2.59%)
Total Booked PnL: 42.66 L (31.48%)
Curr Year Booked PnL: 15.68 L (11.99%)
Prev Year Booked PnL: 26.98 L (19.91%)
===================
Est FTT:  2.47 C
Est FTT PnL: 1.17 C (89.11%)
===================
Deployed:  1.36 C
Current:  1.31 C
CAGR/XIRR %: -1.77%

In [9]:
# top 5 near their targets
cols = ['Symbol', 'Today P/L%', 'Current P/L%', 'FTT%', 'OTT%', 'FTT Amt', 'Current P/L', 'Current', 'FTT', 'Dev%_PE', 'RSI_14','Conviction', 'Spread%',  'CumlRnk', 'RRR Ind', 'CurrAlloc%', 'Gained%', 'Criteria', 'Strategy', 'Category']
df_tmp = df_portfolio_features[~df_portfolio_features['Symbol'].isin(['ENRIN','BLUSPRING','DIGITIDE'])]
df_tmp = df_tmp.sort_values(by = 'FTT Amt', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
19,COALINDIA,-2.00,12.54,4.56,17.67,7721.0,18870.0,169330.0,478.51,34.86,61.0,L-LC,13.30,185.0,2.44,1.30,31.50,XY25,ATH,MINING
50,MASFIN,-1.19,-8.76,33.23,21.57,29708.0,-8580.0,89400.0,397.04,-21.41,36.0,H-SC,3.00,167.0,-0.29,0.69,23.98,XR,ATH,FINANCE
77,TTKPRESTIG,-6.88,-34.39,52.57,0.09,34757.0,-34661.0,66116.0,770.00,53.47,44.0,M-SC,15.87,250.0,-1.00,0.51,11.71,OX40N,NTT,DURABLES
37,ICICIGI,-0.76,-3.43,23.58,19.34,45568.0,-6860.0,193249.0,2252.93,-18.85,36.0,X-MC,2.04,66.0,-0.15,1.49,6.83,X40,ATH,INSURANCE
2,ABBOTINDIA,-0.63,-10.13,31.37,18.07,50424.0,-18115.0,160740.0,35195.00,-23.42,47.0,X-MC,10.91,58.0,-0.36,1.24,1.90,X40,ATH,PHARMA

In [10]:
# top 5 today
df_tmp = df_portfolio_features.sort_values(by = 'Today P/L%', ascending=False)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
45,ITC,0.90,-19.89,48.61,19.06,132471.0,-67648.0,272518.0,452.00,-55.92,36.0,X-LC,17.18,1.0,-0.51,2.09,0.90,X40,NTT,FMCG
62,SATIN,0.81,-19.54,88.71,51.83,197203.0,-53983.0,222301.0,274.00,-27.73,39.0,H-SC,0.85,159.0,-0.27,1.71,8.29,XY24,NTT,FINANCE
81,VBL,0.55,-18.49,66.45,35.67,171064.0,-58409.0,257433.0,671.64,-28.10,28.0,X-LC,5.96,13.0,-0.34,1.98,0.55,X40N,ATH,FMCG
22,DABUR,0.50,-10.90,61.27,43.70,135431.0,-27029.0,221039.0,735.00,-19.10,30.0,X-MC,2.36,70.0,-0.20,1.70,2.51,XY24,BTT,FMCG
8,AWL,0.34,-40.26,179.57,67.02,382233.0,-143449.0,212860.0,485.00,-67.83,19.0,X-SC,24.33,81.0,-0.38,1.64,0.34,XY24,NTT,FMCG

In [11]:
# bottom 5 today
df_tmp = df_portfolio_features.sort_values(by = 'Today P/L%', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
11,BANDHANBNK,-8.67,-22.89,149.55,92.42,321217.0,-63770.0,214789.0,400.00,83.91,40.0,H-SC,9.34,174.0,-0.20,1.65,18.32,XY24,NTT,BANKS
77,TTKPRESTIG,-6.88,-34.39,52.57,0.09,34757.0,-34661.0,66116.0,770.00,53.47,44.0,M-SC,15.87,250.0,-1.00,0.51,11.71,OX40N,NTT,DURABLES
31,HAPPSTMNDS,-5.52,-53.62,298.52,84.85,177464.0,-68717.0,59448.0,1480.71,-44.76,46.0,H-SC,27.82,152.0,-0.39,0.46,10.09,AR,ATH,IT
69,SURYODAY,-5.24,-28.77,72.72,23.03,92762.0,-51510.0,127561.0,216.00,38.16,45.0,H-SC,7.70,166.0,-0.56,0.98,26.57,XR,NTT,BANKS
55,RAJESHEXPO,-4.93,-79.79,395.08,0.07,109544.0,-109450.0,27727.0,518.00,916.41,20.0,L-SC,24.53,268.0,-1.00,0.21,0.00,OX40N,NTT,JEWELLERY

In [12]:
# top 5 to exit based on CumlRnk
df_tmp = df_portfolio_features[~df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])]
df_tmp = df_tmp[(df_tmp['Current P/L%'] > -1) & (df_tmp['Current P/L%'] < 1)].sort_values(by = 'CumlRnk', ascending=False)
df_tmp[cols].head()

Empty DataFrame
Columns: [Symbol, Today P/L%, Current P/L%, FTT%, OTT%, FTT Amt, Current P/L, Current, FTT, Dev%_PE, RSI_14, Conviction, Spread%, CumlRnk, RRR Ind, CurrAlloc%, Gained%, Criteria, Strategy, Category]
Index: []

In [13]:
# OX40N stocks to exit
df_tmp = df_portfolio_features[(df_portfolio_features['Symbol'].isin(list_ox40n))].sort_values(by = 'Current P/L%', ascending=False)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
27,FINCABLES,-2.04,6.20,95.77,107.91,150167.0,9156.0,156800.0,1641.55,-4.62,47.0,M-SC,7.76,220.0,0.06,1.21,17.97,OX40N,ATH,CABLES
77,TTKPRESTIG,-6.88,-34.39,52.57,0.09,34757.0,-34661.0,66116.0,770.00,53.47,44.0,M-SC,15.87,250.0,-1.00,0.51,11.71,OX40N,NTT,DURABLES
66,SIS,-0.75,-36.31,90.41,21.26,63931.0,-40320.0,70712.0,528.00,1652.33,30.0,H-SC,12.25,168.0,-0.63,0.54,0.00,OX40N,NTT,MISC
70,SYMPHONY,-1.62,-39.82,66.13,-0.03,68105.0,-68155.0,102986.0,1306.00,-51.78,39.0,M-SC,14.47,205.0,-1.00,0.79,4.15,OX40N,NTT,DURABLES
72,TATAELXSI,-2.79,-40.39,121.47,32.03,95466.0,-53243.0,78592.0,9161.00,-25.40,24.0,H-SC,18.21,158.0,-0.56,0.60,0.00,OX40N,NTT,IT

In [14]:
# top 5 to book for rotation
df_tmp = df_portfolio_features[(df_portfolio_features['Current P/L%'] > 20) ].sort_values(by = 'CumlRnk', ascending=False)
df_tmp[cols].head()

Empty DataFrame
Columns: [Symbol, Today P/L%, Current P/L%, FTT%, OTT%, FTT Amt, Current P/L, Current, FTT, Dev%_PE, RSI_14, Conviction, Spread%, CumlRnk, RRR Ind, CurrAlloc%, Gained%, Criteria, Strategy, Category]
Index: []

In [15]:
# top 5 to monitor for exit
df_tmp = df_portfolio_features[~df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])]
df_tmp = df_tmp[(df_tmp['Current P/L%'] > 0) ].sort_values(by = 'Dev%_PE', ascending=False)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
19,COALINDIA,-2.00,12.54,4.56,17.67,7721.0,18870.0,169330.0,478.51,34.86,61.0,L-LC,13.30,185.0,2.44,1.30,31.50,XY25,ATH,MINING
27,FINCABLES,-2.04,6.20,95.77,107.91,150167.0,9156.0,156800.0,1641.55,-4.62,47.0,M-SC,7.76,220.0,0.06,1.21,17.97,OX40N,ATH,CABLES
1,ABB,-3.25,13.47,28.29,45.57,83981.0,35237.0,296856.0,7934.00,-27.08,58.0,H-MC,11.44,125.0,0.42,2.28,31.82,AR,NTT,ELECTRICAL

In [16]:
# top 5 to book for rotation from weak conviction
df_tmp = df_portfolio_features[~df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])]
df_tmp = df_tmp[~df_tmp['Criteria'].isin(['XY25','XY24','X40', 'X40N'])].sort_values(by = 'RRR Ind', ascending=False)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
1,ABB,-3.25,13.47,28.29,45.57,83981.0,35237.0,296856.0,7934.00,-27.08,58.0,H-MC,11.44,125.0,0.42,2.28,31.82,AR,NTT,ELECTRICAL
27,FINCABLES,-2.04,6.20,95.77,107.91,150167.0,9156.0,156800.0,1641.55,-4.62,47.0,M-SC,7.76,220.0,0.06,1.21,17.97,OX40N,ATH,CABLES
40,INDIAMART,-0.09,-9.76,129.08,106.72,143666.0,-12036.0,111300.0,4810.62,-59.38,41.0,H-SC,9.80,140.0,-0.08,0.86,11.34,AR,ATH,MISC
85,ZYDUSLIFE,-3.03,-7.37,46.41,35.63,90099.0,-15437.0,194137.0,1286.17,-19.37,40.0,H-MC,5.11,120.0,-0.17,1.49,8.08,AR,ATH,PHARMA
84,WIPRO,-2.03,-20.61,116.99,72.27,157380.0,-34924.0,134524.0,420.00,-28.30,27.0,M-LC,15.57,98.0,-0.22,1.03,0.00,XR,NTT,IT

In [17]:
# top 5 to accumulate based on lowest RSI_14
df_tmp = df_portfolio_features[df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])].sort_values(by = 'RSI_14', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
58,RELAXO,-4.16,-63.42,316.36,52.31,167990.0,-92059.0,53101.0,1176.00,-61.09,14.0,X-SC,20.93,92.0,-0.55,0.41,0.0,X40N,NTT,FOOTWEAR
3,ACC,-0.39,-38.64,184.90,74.81,304197.0,-103608.0,164520.0,3906.00,-56.56,16.0,X-SC,14.13,85.0,-0.34,1.26,0.0,XY24,BTT,CEMENT
12,BATAINDIA,-3.50,-56.46,210.54,35.20,117947.0,-72649.0,56021.0,2096.00,-26.50,16.0,X-SC,27.52,91.0,-0.62,0.43,0.0,X40,NTT,FOOTWEAR
13,BERGEPAINT,-3.49,-27.47,72.79,25.32,136071.0,-70813.0,186936.0,680.00,-31.47,17.0,X-MC,16.65,68.0,-0.52,1.44,0.0,XY24,NTT,PAINTS
53,PGHH,-3.48,-23.90,73.46,32.01,119370.0,-51024.0,162496.0,17616.87,-48.47,17.0,X-MC,12.38,57.0,-0.43,1.25,0.0,X40,ATH,FMCG

In [18]:
# top 5 to accumulate based on Spread and CumlRnk
df_tmp = df_portfolio_features[df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])]
df_tmp = df_tmp[(df_tmp['CumlRnk'] < 100)].sort_values(by = 'Spread%', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
78,UNITDSPR,-0.09,-3.53,25.19,20.77,56897.0,-8274.0,225870.0,1644.00,-14.48,40.0,X-MC,1.04,64.0,-0.15,1.74,2.94,X40N,NTT,BREWERIES
37,ICICIGI,-0.76,-3.43,23.58,19.34,45568.0,-6860.0,193249.0,2252.93,-18.85,36.0,X-MC,2.04,66.0,-0.15,1.49,6.83,X40,ATH,INSURANCE
75,TMPV,-0.59,-28.92,92.15,36.58,233068.0,-102919.0,252922.0,600.00,-84.72,29.0,X-LC,2.16,4.0,-0.44,1.94,0.00,XY24,NTT,AUTO
22,DABUR,0.50,-10.90,61.27,43.70,135431.0,-27029.0,221039.0,735.00,-19.10,30.0,X-MC,2.36,70.0,-0.20,1.70,2.51,XY24,BTT,FMCG
38,ICICIPRULI,-0.61,-3.99,36.16,30.73,68395.0,-7860.0,189145.0,790.00,-29.74,24.0,X-MC,2.82,78.0,-0.11,1.45,8.21,X40,ATH,INSURANCE

In [19]:
# top 5 to accumulate based on lowest Gained%
df_tmp = df_portfolio_features[df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])].sort_values(by = 'Gained%', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
3,ACC,-0.39,-38.64,184.90,74.81,304197.0,-103608.0,164520.0,3906.00,-56.56,16.0,X-SC,14.13,85.0,-0.34,1.26,0.0,XY24,BTT,CEMENT
6,ASIANPAINT,-0.16,-21.07,57.77,24.52,129235.0,-59733.0,223706.0,3460.25,-20.40,27.0,X-LC,7.33,30.0,-0.46,1.72,0.0,X40,ATH,PAINTS
10,BAJAJHLDNG,-0.94,-15.80,53.46,29.22,85584.0,-30036.0,160089.0,14451.52,-22.37,20.0,X-LC,13.25,28.0,-0.35,1.23,0.0,X40,ATH,FINANCE
9,BAJAJHFL,-2.33,-28.33,126.20,62.13,246980.0,-77341.0,195705.0,181.50,-41.06,23.0,X-MC,19.10,60.0,-0.31,1.50,0.0,X40N,ATH,FINANCE
12,BATAINDIA,-3.50,-56.46,210.54,35.20,117947.0,-72649.0,56021.0,2096.00,-26.50,16.0,X-SC,27.52,91.0,-0.62,0.43,0.0,X40,NTT,FOOTWEAR

In [20]:
# top 5 to accumulate based on lowest CurrAlloc%
df_tmp = df_portfolio_features[df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])].sort_values(by = 'CurrAlloc%', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
58,RELAXO,-4.16,-63.42,316.36,52.31,167990.0,-92059.0,53101.0,1176.00,-61.09,14.0,X-SC,20.93,92.0,-0.55,0.41,0.00,X40N,NTT,FOOTWEAR
12,BATAINDIA,-3.50,-56.46,210.54,35.20,117947.0,-72649.0,56021.0,2096.00,-26.50,16.0,X-SC,27.52,91.0,-0.62,0.43,0.00,X40,NTT,FOOTWEAR
54,QUESS,-3.96,-28.42,142.95,73.90,109271.0,-30353.0,76440.0,424.00,-61.43,29.0,X-SC,18.82,80.0,-0.28,0.59,0.00,XY24,NTT,MISC
36,HONAUT,-2.86,-24.31,99.92,51.31,145833.0,-46888.0,145950.0,58357.33,-37.05,31.0,X-SC,14.15,90.0,-0.32,1.12,0.00,X40N,ATH,ELECTRICAL
65,SIEMENS,-2.89,-16.31,49.98,25.51,77839.0,-30355.0,155740.0,4671.50,30.86,44.0,H-LC,3.74,51.0,-0.39,1.20,14.69,AR,ATH,ELECTRICAL

In [21]:
# top 5 to accumulate based on CumlRnk
df_tmp = df_portfolio_features.sort_values(by = 'CumlRnk', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
45,ITC,0.90,-19.89,48.61,19.06,132471.0,-67648.0,272518.0,452.00,-55.92,36.0,X-LC,17.18,1.0,-0.51,2.09,0.9,X40,NTT,FMCG
73,TCS,-1.35,-30.19,81.32,26.57,262984.0,-139879.0,323394.0,4311.59,-41.00,18.0,X-LC,15.24,2.0,-0.53,2.49,0.0,X40,ATH,IT
43,INFY,-1.22,-16.06,59.92,34.24,157380.0,-50238.0,262650.0,1972.00,-33.96,22.0,X-LC,13.48,3.0,-0.32,2.02,0.0,X40,NTT,IT
75,TMPV,-0.59,-28.92,92.15,36.58,233068.0,-102919.0,252922.0,600.00,-84.72,29.0,X-LC,2.16,4.0,-0.44,1.94,0.0,XY24,NTT,AUTO
34,HCLTECH,-1.33,-15.13,45.91,23.83,94265.0,-36599.0,205325.0,1908.19,-10.67,24.0,X-LC,10.20,8.0,-0.39,1.58,0.0,X40,ATH,IT

In [22]:
# top 5 for average up
df_tmp = df_portfolio_features[(df_portfolio_features['Dev%_200'] > 5)].sort_values(by = 'CurrAlloc%', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
19,COALINDIA,-2.00,12.54,4.56,17.67,7721.0,18870.0,169330.0,478.51,34.86,61.0,L-LC,13.30,185.0,2.44,1.30,31.50,XY25,ATH,MINING
1,ABB,-3.25,13.47,28.29,45.57,83981.0,35237.0,296856.0,7934.00,-27.08,58.0,H-MC,11.44,125.0,0.42,2.28,31.82,AR,NTT,ELECTRICAL

In [23]:
# top 5 RSP
df_tmp = df_portfolio_features.sort_values(by = 'RSP', ascending=False)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
19,COALINDIA,-2.00,12.54,4.56,17.67,7721.0,18870.0,169330.0,478.51,34.86,61.0,L-LC,13.30,185.0,2.44,1.30,31.50,XY25,ATH,MINING
1,ABB,-3.25,13.47,28.29,45.57,83981.0,35237.0,296856.0,7934.00,-27.08,58.0,H-MC,11.44,125.0,0.42,2.28,31.82,AR,NTT,ELECTRICAL
27,FINCABLES,-2.04,6.20,95.77,107.91,150167.0,9156.0,156800.0,1641.55,-4.62,47.0,M-SC,7.76,220.0,0.06,1.21,17.97,OX40N,ATH,CABLES
2,ABBOTINDIA,-0.63,-10.13,31.37,18.07,50424.0,-18115.0,160740.0,35195.00,-23.42,47.0,X-MC,10.91,58.0,-0.36,1.24,1.90,X40,ATH,PHARMA
69,SURYODAY,-5.24,-28.77,72.72,23.03,92762.0,-51510.0,127561.0,216.00,38.16,45.0,H-SC,7.70,166.0,-0.56,0.98,26.57,XR,NTT,BANKS

In [24]:
# Top N allocation
df_tmp = df_portfolio_features.sort_values(by = 'CurrAlloc%', ascending=False)
top_n_values = [10, 25, 50]

sum_df = pd.DataFrame({
    'Top_N': top_n_values,
    'Sum_Alloc%': [df_tmp['CurrAlloc%'].head(n).sum() for n in top_n_values]
})

sum_df

   Top_N  Sum_Alloc%
0     10       20.61
1     25       45.51
2     50       78.00

In [25]:
# market-cap-wise allocation
df_tmp = df_portfolio_features[cols]
df_tmp.groupby(df_tmp['Conviction'].str[-2:])['CurrAlloc%'].sum().sort_values(ascending=False)

Conviction
SC    44.45
MC    30.46
LC    25.10
Name: CurrAlloc%, dtype: float64

In [26]:
# criteria-wise allocation
df_portfolio_features.groupby('Criteria')['CurrAlloc%'].sum().sort_values(ascending=False)

Criteria
XY24     27.17
X40      23.95
X40N     15.03
AR        9.21
XY25      8.82
XR        8.20
OX40N     6.86
SR        0.77
Name: CurrAlloc%, dtype: float64

In [27]:
# conviction-wise allocation
df_portfolio_features.groupby('Conviction')['CurrAlloc%'].sum().sort_values(ascending=False)

Conviction
X-MC    22.97
H-SC    21.64
X-LC    21.57
X-SC    12.11
M-SC    10.13
H-MC     5.08
M-MC     2.05
L-LC     1.30
H-LC     1.20
M-LC     1.03
L-SC     0.57
L-MC     0.36
Name: CurrAlloc%, dtype: float64

In [28]:
# sector-wise stats
df_tmp = df_portfolio_features.groupby('Category')[['CurrAlloc%', 'Current', 'Current P/L', 'FTT Amt']].sum().sort_values(by=['Current', 'Current P/L'], ascending=False)
df_tmp['Current P/L%'] = round(df_tmp['Current P/L'] * 100 / df_tmp['Current'], 2)
df_tmp['FTT%'] = round(df_tmp['FTT Amt'] * 100 / df_tmp['Current'], 2)
cols = ['CurrAlloc%', 'Current P/L%', 'FTT%']
df_tmp[cols].sort_values(by=['CurrAlloc%'], ascending=False)

               CurrAlloc%  Current P/L%    FTT%
Category
FMCG                15.36        -25.06   69.46
FINANCE             12.95        -27.53   79.51
IT                  11.63        -48.83  124.57
MISC                 6.95        -48.17  112.54
ELECTRICAL           6.66        -11.71   54.48
PAINTS               5.12        -48.18   73.91
INSURANCE            4.84         -7.69   44.54
PHARMA               4.20         -7.54   41.39
AUTO                 3.64        -37.76   92.42
BANKS                2.99        -37.53  120.87
AC                   2.15        -14.26   45.24
HEALTHCARE           1.96        -40.10   76.66
DURABLES             1.88        -58.37   96.90
FOOTWEAR             1.84        -84.29  158.19
TRAVEL               1.82        -89.36  184.17
BREWERIES            1.74         -3.66   25.19
APPARELS             1.61        -28.21   71.94
REALTY               1.45        -17.76   37.10
REFINERIES           1.37        -12.90   41.47
CERAMICS             1.37        -73.40  126.07
MINING               1.30         11.14    4.56
CEMENT               1.26        -62.98  184.90
CABLES               1.21          5.84   95.77
JEWELLERY            1.12       -119.80  196.17
ENGINEERING          1.09        -70.58  148.59
CHEMICALS            0.95       -113.92  288.44
ENTERTAINMENT        0.77        -93.79  209.37
TEXTILES             0.42        -66.89  114.48
HOTELS               0.36       -144.08  230.17

In [29]:
# money to be made criteria-wise
df_portfolio_features.groupby('Criteria')['FTT Amt'].agg(['sum', 'count']).sort_values(by='sum', ascending=False)

                sum  count
Criteria
XY24      4061937.0     21
X40       1757748.0     15
XR        1424573.0     12
AR        1373513.0     10
X40N      1346160.0     10
OX40N      898570.0     10
XY25       470474.0      6
SR         319306.0      2

In [30]:
# money to be made conviction-wise
df_portfolio_features.groupby('Conviction')['FTT Amt'].agg(['sum', 'count']).sort_values(by='sum', ascending=False)

                  sum  count
Conviction
H-SC        3978069.0     24
X-MC        1747103.0     15
X-LC        1668389.0     12
X-SC        1608274.0     10
M-SC        1598845.0     14
H-MC         417400.0      3
L-SC         216624.0      2
M-LC         157380.0      1
M-MC         118572.0      2
H-LC          77839.0      1
L-MC          56065.0      1
L-LC           7721.0      1

In [31]:
# money to be made criteria and conviction-wise
df_portfolio_features.groupby(['Conviction', 'Criteria'])['FTT Amt'].agg(['sum', 'count']).sort_values(by='sum', ascending=False)

                           sum  count
Conviction Criteria
H-SC       XY24      1363788.0      6
           AR         987724.0      5
M-SC       XY24       934749.0      6
H-SC       XR         907015.0      7
X-LC       X40        861919.0      6
X-SC       XY24       861566.0      4
X-MC       X40        684770.0      7
           X40N       540898.0      4
X-SC       X40N       535649.0      4
H-SC       OX40N      400236.0      4
M-SC       OX40N      388790.0      5
X-LC       XY24       387012.0      2
H-SC       SR         319306.0      2
X-MC       XY24       271502.0      2
X-LC       X40N       269613.0      2
X-MC       XY25       249933.0      2
H-MC       XY24       243320.0      1
X-SC       X40        211059.0      2
M-SC       XR         197033.0      2
H-MC       AR         174080.0      2
M-LC       XR         157380.0      1
X-LC       XY25       149845.0      2
L-SC       OX40N      109544.0      1
           XR         107080.0      1
M-SC       AR          78273.0      1
H-LC       AR          77839.0      1
M-MC       XY25        62975.0      1
L-MC       XR          56065.0      1
M-MC       AR          55597.0      1
L-LC       XY25         7721.0      1

In [32]:
# notebook execution time

end_time = time.time()
execution_time = round(end_time - start_time, 0)
print(f"Notebook execution time: {execution_time} seconds")

Notebook execution time: 28.0 seconds