<a href="https://colab.research.google.com/github/ankit-rathi/Quantvesting_v2/blob/main/myStocks_Portfolio_Analysis.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
'''
!pip install pandas==2.2.2 -qq
!pip install pyxirr -qq
!pip install ta -qq
!pip install yfinance==0.2.59 -qq
'''

'\n!pip install pandas==2.2.2 -qq\n!pip install pyxirr -qq\n!pip install ta -qq\n!pip install yfinance==0.2.59 -qq\n'

In [2]:
# import libraries

import numpy as np
import pandas as pd
import datetime
import warnings
warnings.filterwarnings('ignore')
import yfinance as yfin
import ta
import matplotlib.pyplot as plt
import requests

In [3]:
# notebook start time
import time
import datetime
import pytz

start_time = time.time()

# function to print date timestamp
def print_date_time():
  tz_NY = pytz.timezone('Asia/Kolkata')
  datetime_NY = datetime.datetime.now(tz_NY)
  print("Run date time (IST):", datetime_NY.strftime("%Y-%m-%d %H:%M:%S"))

In [4]:
# function to get booked and reserved amount
def get_amt():
  # fetch the JSON data from the URL
  url = "https://raw.githubusercontent.com/ankit-rathi/Tradevesting_v1/main/data/myPortfolioAmts.json"
  response = requests.get(url)
  pf_amts = response.json()  # parse the JSON data

  # extract values from the JSON
  py_booked_amt_dm = pf_amts["py_booked_amt_dm"]
  py_booked_amt_sv = pf_amts["py_booked_amt_sv"]
  cy_booked_amt_dm = pf_amts["cy_booked_amt_dm"]
  cy_booked_amt_sv = pf_amts["cy_booked_amt_sv"]
  reserve_amt_dm = pf_amts["reserve_amt_dm"]
  reserve_amt_sv = pf_amts["reserve_amt_sv"]

  # perform calculations
  py_booked_amt = py_booked_amt_dm + py_booked_amt_sv
  cy_booked_amt = cy_booked_amt_dm + cy_booked_amt_sv
  reserve_amt = reserve_amt_dm + reserve_amt_sv
  total_booked_amt = py_booked_amt + cy_booked_amt

  return total_booked_amt, reserve_amt, cy_booked_amt, py_booked_amt

gen_output = 0

In [5]:
# function to format the amount
def format_amt(number):
    abs_number = abs(number)

    if abs_number >= 1_00_00_000:  # Crores
        formatted_amt = f"{number / 1_00_00_000:.2f} C"
    elif abs_number >= 1_00_000:  # Lakhs
        formatted_amt = f"{number / 1_00_000:.2f} L"
    elif abs_number >= 1_000:  # Thousands
        formatted_amt = f"{number / 1_000:.2f} K"
    else:
        formatted_amt = f"{number:.2f}"

    return formatted_amt

# function to set start and end date
def get_start_end_date():
  start_date = (datetime.date.today() + datetime.timedelta(days=-365)).strftime('%Y-%m-%d')
  end_date = (datetime.date.today() + datetime.timedelta(days=1)).strftime('%Y-%m-%d')
  return start_date, end_date

# function to fetch my portfolio csv
def get_mypfs_df():
  mypfs_df = pd.read_csv('https://raw.githubusercontent.com/ankit-rathi/Tradevesting_v1/main/data/myPortfolioStocks.csv')
  return mypfs_df

# function to fetch my prospects csv
def get_mypps_df():
  mypps_df = pd.read_csv('https://raw.githubusercontent.com/ankit-rathi/Tradevesting_v1/main/data/myProspectsScrips.csv')
  return mypps_df

# function to fetch screener data
def get_myscreen_df():
  myscreen_df = pd.read_csv('https://raw.githubusercontent.com/ankit-rathi/Tradevesting_v1/main/data/myScreenerDB.csv')
  return myscreen_df

# function to fetch momentum data
def get_myinvmt_df():
  myinvmt_df = pd.read_csv('https://raw.githubusercontent.com/ankit-rathi/Tradevesting_v1/main/data/myInvestments.csv')
  return myinvmt_df

# function to get the stock ids
def get_stock_ids(df_pf):
  stock_n100 = df_pf['Symbol'].unique()

  exclude = ['CADILAHC','MMTC', 'MASFIN']

  stock_ids = df_pf[~df_pf['Symbol'].isin(exclude) ]['Symbol'].unique()

  #mypf = mypf[mypf.Forecast.notnull()]
  #stock_ids = mypf['Symbol'].unique()

  #stock_ids.sort()
  return stock_ids

# get features from screener data
def get_screener_features():
  myscreen_df = get_myscreen_df()
  cols = ['Symbol', 'EPS', 'MedPE', 'ROCE%', 'ROE%', 'CapType']
  return myscreen_df[cols]

# get relative strength
def get_relative_strength(stock_list):

    # Dictionary to store stock tickers and their corresponding percentage price change
    stock_changes = {}

    # Loop through each stock and fetch its price data
    for stock in stock_list:
        try:
            # Download the stock data for the given date range
            stock_data = yfin.Ticker(stock + '.NS').history(period='1mo', interval='1d')[map(str.title, ['open', 'close', 'low', 'high', 'volume'])]

            # Calculate the percentage change for the stock
            if len(stock_data) > 0:
                start_price = stock_data['Close'].iloc[0]
                end_price = stock_data['Close'].iloc[-1]
                percent_change = round(((end_price - start_price) / start_price) * 100, 2)
                stock_changes[stock] = percent_change
            else:
                stock_changes[stock] = np.nan  # If no data is available, set to NaN

        except Exception as e:
            print(f"Error fetching data for {stock}: {e}")
            stock_changes[stock] = np.nan

    # Create a DataFrame with stock tickers and their percentage changes
    df = pd.DataFrame(list(stock_changes.items()), columns=['Symbol', 'Percent_Change'])

    # Drop any stocks with missing data (NaN values)
    df = df.dropna()

    # Calculate the percentile rank based on percentage change
    df['RSP'] = round(df['Percent_Change'].rank(pct=True) * 100, 2)
    cols = ['Symbol', 'RSP']
    df = df[cols]
    # Sort by percentile rank (optional)
    df = df.sort_values(by='RSP', ascending=False).reset_index(drop=True)

    return df

In [6]:
# function to get stock technicals
def stock_prec_dev(stock_symbol):
    #stock_symbol = 'ULTRACEMCO.NS'
    short_window = 20
    mid_window = 50
    long_window = 200
    moving_avg = 'SMA'

    start = datetime.datetime(*map(int, start_date.split('-')))
    end = datetime.datetime(*map(int, end_date.split('-')))

    stock_df = yfin.Ticker(stock_symbol + '.NS').history(period='max', interval='1d')[map(str.title, ['open', 'close', 'low', 'high', 'volume'])]

    stock_df['Max'] = round(max(stock_df['Close']),2)
    stock_df = stock_df[(stock_df.index <= end_date) & (stock_df.index >= start_date)]
    stock_df['200_SMA'] = round(stock_df['Close'].rolling(window = 200, min_periods = 1).mean(),0)
    stock_df['Dev%_200'] = round((stock_df['Close'] - stock_df['200_SMA'])*100/stock_df['200_SMA'],2)
    stock_df.dropna(axis = 0, inplace = True) # remove any null rows

    stock_df['20_SMA'] = stock_df['Close'].rolling(window=20).mean()
    stock_df['50_SMA'] = stock_df['Close'].rolling(window=50).mean()
    stock_df['Symbol'] = stock_symbol

    stock_df['Close'] = round(stock_df['Close'],2)
    stock_df['Min'] = round(min(stock_df['Close']),2)
    stock_df['RSI_14'] = ta.momentum.RSIIndicator(close=stock_df['Close'], window=14).rsi()
    stock_df['RSI_14'] = round(stock_df['RSI_14'],0)
    stock_df['Prev_Close'] = stock_df['Close'].shift(1)
    stock_df.drop(['Open', 'Low', 'High', 'Volume'], axis=1, inplace=True)
    stock_df = stock_df.tail(1)

    max_SMA = max(stock_df['20_SMA'].item(), stock_df['50_SMA'].item(), stock_df['200_SMA'].item())
    min_SMA = min(stock_df['20_SMA'].item(), stock_df['50_SMA'].item(), stock_df['200_SMA'].item())
    ABS_Spread = max_SMA - min_SMA
    stock_df['Spread%'] = round((ABS_Spread / stock_df['200_SMA'].item()) * 100,2)

    return stock_df

# function to compute stock attributes
def get_common_features(stock_ids, df_mypf):

  df_prec_dev = pd.DataFrame()
  df_tmp = get_screener_features()
  df_rs = get_relative_strength(stock_ids)

  for stock_id in stock_ids:
      tmp = stock_prec_dev(stock_id)
      tmp = tmp.reset_index()
      df_prec_dev = pd.concat([df_prec_dev, tmp], ignore_index = True)
  df_prec_dev = pd.merge(df_prec_dev, df_mypf, on= 'Symbol')
  df_prec_dev = pd.merge(df_prec_dev, df_tmp, on= 'Symbol', how='left')
  df_prec_dev = pd.merge(df_prec_dev, df_rs, on= 'Symbol', how='left')
  #print(df_prec_dev.columns)
  df_prec_dev['Curr_PE'] = round(df_prec_dev['Close']/df_prec_dev['EPS'],1)
  df_prec_dev['Dev%_PE'] = round((df_prec_dev['Curr_PE'] - df_prec_dev['MedPE'])*100/df_prec_dev['MedPE'],2)
  df_prec_dev['Conviction'] = df_prec_dev['Conviction'] + '-' + df_prec_dev['CapType']
  return df_prec_dev

# function to arrange stock features
def arrange_features(df_stocks, common_cols, diff_cols):
  df_stocks_common = df_stocks[common_cols].drop_duplicates()
  df_stocks_diff = df_stocks[diff_cols]
  df_stocks_diff['Investment'] = df_stocks_diff['AvgCost'] * df_stocks_diff['Shares']
  df_stocks_diff = df_stocks_diff.groupby(['Symbol'])[['Shares', 'Investment']].aggregate(['sum']).reset_index()
  df_stocks_diff.columns = ['Symbol', 'Shares', 'Investment']
  df_stocks_diff['AvgCost'] = round(df_stocks_diff['Investment']/df_stocks_diff['Shares'],2)
  df_stocks = pd.merge(df_stocks_diff, df_stocks_common, on='Symbol')
  return df_stocks

# plot fact distribution across dimension
def plot_pie_chart(df, dimension, fact):
  # grouping the data by category and calculating the sum of fact for each type
  grouped_data = df.groupby(dimension)[fact].sum()

  # sorting the grouped data in descending order
  grouped_data = grouped_data.sort_values(ascending=False)

  # creating a pie chart
  grouped_data.plot.pie(autopct='%1.1f%%', startangle=90, figsize=(6, 6))

  # adding a title and displaying the plot
  plt.title(f'{dimension} {fact} Distribution')
  plt.ylabel('')  # To hide the y-label
  plt.show()

In [7]:
# function to get portfolio features

def get_portfolio_features(df_common_features):

  print_date_time()
  print('-------------------')

  #df_common_features["Target"] = df_common_features["Target"].fillna(df_common_features["Max"])
  df_common_features['NTT'] = np.where(df_common_features['Strategy']== 'NTT', df_common_features["Target"], df_common_features['Max'])
  df_common_features['LTT'] = np.where(df_common_features['Strategy']== 'BTT', df_common_features["Target"], df_common_features['Max'])
  df_common_features['BOL'] = df_common_features['Min']

  tmp_df = df_common_features[df_common_features['Symbol'].isin(mypf_df[mypf_df['InPortfolio'] != 'NA'].Symbol.values)]
  print('qualified stocks: '+str(len(tmp_df['Symbol'].unique())))
  tmp_df1 = tmp_df[tmp_df['LatestQtr'] == 1]
  print('with latest results: '+str(len(tmp_df1['Symbol'].unique())))
  tmp_df1 = tmp_df1[tmp_df1['StarStock'] == 1]
  print('still star stocks: '+str(len(tmp_df1['Symbol'].unique())))
  tmp_df['Investment'] = tmp_df['AvgCost'] * tmp_df['Shares']
  tmp_df['Current'] = round(tmp_df['Close'] * tmp_df['Shares'],0)
  tmp_df['Previous'] = tmp_df['Prev_Close'] * tmp_df['Shares']
  tmp_df['EstimatedST'] = tmp_df['NTT'] * tmp_df['Shares']
  tmp_df['EstimatedLT'] = tmp_df['LTT'] * tmp_df['Shares']
  tmp_df['Current P/L'] = round((tmp_df['Current'] - tmp_df['Investment']),0)
  tmp_df['Today P/L%'] = round((tmp_df['Current'] - tmp_df['Previous'])*100/tmp_df['Previous'],2)
  tmp_df['Current P/L%'] = round((tmp_df['Current'] - tmp_df['Investment'])*100/tmp_df['Investment'],2)
  tmp_df['EstimatedST P/L%'] = round((tmp_df['EstimatedST'] - tmp_df['Investment'])*100/tmp_df['Investment'],2)
  tmp_df['EstimatedLT P/L%'] = round((tmp_df['EstimatedLT'] - tmp_df['Investment'])*100/tmp_df['Investment'],2)
  tmp_df['NTT%'] = round((tmp_df['NTT'] - tmp_df['Close'])*100/tmp_df['Close'],2)
  tmp_df['LTT%'] = round((tmp_df['LTT'] - tmp_df['Close'])*100/tmp_df['Close'],2)
  tmp_df['Gained%'] = round((tmp_df['Close'] - tmp_df['BOL'])*100/tmp_df['BOL'],2)
  investment = round(sum(tmp_df['AvgCost']*tmp_df['Shares']),0)
  current = round(sum(tmp_df['Close']*tmp_df['Shares']),0)
  tmp_df['InitAlloc%'] = round(tmp_df['Investment']*100/investment,2)
  tmp_df['CurrAlloc%'] = round(tmp_df['Current']*100/current,2)
  tmp_df['FTT'] = tmp_df['LTT']
  tmp_df.loc[tmp_df['Strategy'] == 'NTT', 'FTT'] = tmp_df['NTT']
  tmp_df['FTT%'] = tmp_df['LTT%']
  tmp_df.loc[tmp_df['Strategy'] == 'NTT', 'FTT%'] = tmp_df['NTT%']
  tmp_df['FTT Amt'] = round(tmp_df['FTT%'] * tmp_df['Current']/100,0)
  tmp_df['OTT%'] = round((tmp_df['FTT'] - tmp_df['AvgCost'])*100/tmp_df['AvgCost'],2)
  tmp_df['RRR Ind'] = round(tmp_df['Current P/L']/tmp_df['FTT Amt'],2)
  tmp_df['Risk Ind'] = round(tmp_df['Current P/L%']*tmp_df['CurrAlloc%'],0)

  return tmp_df

# function to print portfolio features
def print_portfolio_stats(df_portfolio_features, myinvmt_df):
  from pyxirr import xirr

  total_booked_amt, reserve_amt, cy_booked_amt, py_booked_amt = get_amt()

  dates = myinvmt_df['Date'].values
  dates = np.append(dates, datetime.date.today().strftime('%d-%b-%y'))
  investment = myinvmt_df['Investment'].values
  dates= pd.to_datetime(dates)

  current = round(sum(df_portfolio_features['Close']*df_portfolio_features['Shares']),0) + reserve_amt
  investment_xirr = np.append(investment, current)
  cagr = round(xirr(pd.DataFrame({"dates": dates, "amounts": investment_xirr}))*100,2)

  investment = -sum(investment)
  invested = round(sum(df_portfolio_features['AvgCost']*df_portfolio_features['Shares']),0) + reserve_amt
  previous = round(sum(df_portfolio_features['Prev_Close']*df_portfolio_features['Shares']),0) + reserve_amt
  cy_invested = investment + py_booked_amt

  today_pnl_amount = current-previous
  today_pnl_percentage = round((current-previous)*100/previous,2)

  curr_pnl_amount = current-invested
  curr_pnl_percentage = round((curr_pnl_amount)*100/(cy_invested),2)

  cy_pnl_amount = cy_booked_amt + curr_pnl_amount
  cy_pnl_percentage = round((cy_pnl_amount)*100/cy_invested,2)

  overall_pnl_amount = total_booked_amt + curr_pnl_amount
  overall_pnl_percentage = round((overall_pnl_amount)*100/investment,2)

  estimate_st = round(sum(df_portfolio_features['FTT']*df_portfolio_features['Shares']),0)  + reserve_amt
  est_st_pnl_amount = estimate_st-current
  est_st_pnl_percentage = round((est_st_pnl_amount)*100/current,2)

  estimate_lt = round(sum(df_portfolio_features['LTT']*df_portfolio_features['Shares']),0)  + reserve_amt
  est_lt_pnl_amount = estimate_lt-current
  est_lt_pnl_percentage = round((est_lt_pnl_amount)*100/current,2)

  total_profit = round(sum(df_portfolio_features[df_portfolio_features['Current P/L%'] > 0]['Current']) - sum(df_portfolio_features[df_portfolio_features['Current P/L%'] > 0]['Investment']),0)
  total_loss = round(sum(df_portfolio_features[df_portfolio_features['Current P/L%'] < 0]['Current']) - sum(df_portfolio_features[df_portfolio_features['Current P/L%'] < 0]['Investment']),0)

  cy_booked_percentage = round((cy_booked_amt)*100/current,2)
  py_booked_percentage = round((py_booked_amt)*100/investment,2)
  total_booked_percentage = round((total_booked_amt)*100/investment,2)

  print('-------------------')
  print('Initial Investment: ', format_amt(investment))
  print('CY Investment: ', format_amt(cy_invested))
  print('Reserve: ', format_amt(reserve_amt))
  print('Current: ',  format_amt(current))
  print('-------------------')
  print('Today PnL: '+ '{} ({}%)'.format(format_amt(today_pnl_amount), today_pnl_percentage))
  print('Current PnL: '+ '{} ({}%)'.format(format_amt(curr_pnl_amount), curr_pnl_percentage))
  print('CY Booked + Current PnL: '+ '{} ({}%)'.format(format_amt(cy_pnl_amount), cy_pnl_percentage))
  print('-------------------')
  print('Total profit: ', format_amt(total_profit))
  print('Total loss: ', format_amt(total_loss))
  print('-------------------')
  print('Total Booked + Current PnL: '+ '{} ({}%)'.format(format_amt(overall_pnl_amount), overall_pnl_percentage))
  print('Total Booked PnL: '+ '{} ({}%)'.format(format_amt(total_booked_amt), total_booked_percentage))
  print('Curr Year Booked PnL: '+ '{} ({}%)'.format(format_amt(cy_booked_amt), cy_booked_percentage))
  print('Prev Year Booked PnL: '+ '{} ({}%)'.format(format_amt(py_booked_amt), py_booked_percentage))
  print('===================')
  print('Est FTT: ',  format_amt(estimate_st))
  print('Est FTT PnL: '+ '{} ({}%)'.format(format_amt(est_st_pnl_amount), est_st_pnl_percentage))

  print('===================')
  print('Deployed: ', format_amt(investment))

  print('Current: ', format_amt(current))

  print('CAGR/XIRR %: '+'{}%'.format(cagr))

In [8]:
# get start and end date
start_date, end_date = get_start_end_date()

# get portfolio and prospects data
mypfs_df = get_mypfs_df()
mypps_df = get_mypps_df()
myinvmt_df = get_myinvmt_df()

# merge above datasets
mypf_df = pd.merge(mypfs_df, mypps_df, on="Symbol")

# seggregate dm and sv portfolio
dm_pf = mypf_df[mypf_df['InPortfolio'] == 'DM']
sv_pf = mypf_df[mypf_df['InPortfolio'] == 'SV']

# build portfolio stock dataframe
dm_stocks = get_stock_ids(dm_pf)
sv_stocks = get_stock_ids(sv_pf)
df_stocks = pd.concat([dm_pf,sv_pf], ignore_index = True)

# arrange common and diff stock features
common_cols = ['Symbol', 'Target', 'Criteria', 'Strategy', 'CumlRnk', 'LatestQtr', 'StarStock', 'Conviction', 'Category', 'InFolio', 'XIRR', 'MBQ']
diff_cols = ['Symbol', 'AvgCost', 'Shares']
df_stocks = arrange_features(df_stocks, common_cols, diff_cols)

# get common features
stock_ids = df_stocks['Symbol'].values
df_common_features = get_common_features(stock_ids, df_stocks)

df_common_features.reset_index(drop=True, inplace=True)
df_common_features.drop(['Date'], axis=1, inplace=True)
# get and print portfolio features
df_portfolio_features = get_portfolio_features(df_common_features)

print_portfolio_stats(df_portfolio_features, myinvmt_df)

df = df_portfolio_features
#plot_pie_chart(df, 'CapType', 'Current')
list_ox40n = list(df[df['MBQ'].str.contains('OX40N', na=False)]['Symbol'].values)

Run date time (IST): 2026-03-18 11:16:31
-------------------
qualified stocks: 86
with latest results: 26
still star stocks: 16
-------------------
Initial Investment:  1.36 C
CY Investment:  1.62 C
Reserve:  1.61 K
Current:  1.34 C
-------------------
Today PnL: 2.46 L (1.86%)
Current PnL: -42.76 L (-26.32%)
CY Booked + Current PnL: -26.87 L (-16.54%)
-------------------
Total profit:  83.81 K
Total loss:  -43.60 L
-------------------
Total Booked + Current PnL: 11.15 K (0.08%)
Total Booked PnL: 42.87 L (31.64%)
Curr Year Booked PnL: 15.89 L (11.83%)
Prev Year Booked PnL: 26.98 L (19.91%)
===================
Est FTT:  2.48 C
Est FTT PnL: 1.14 C (84.48%)
===================
Deployed:  1.36 C
Current:  1.34 C
CAGR/XIRR %: -0.42%

In [9]:
# top 5 near their targets
cols = ['Symbol', 'Today P/L%', 'Current P/L%', 'FTT%', 'OTT%', 'FTT Amt', 'Current P/L', 'Current', 'FTT', 'Dev%_PE', 'RSI_14','Conviction', 'Spread%',  'CumlRnk', 'RRR Ind', 'CurrAlloc%', 'Gained%', 'Criteria', 'Strategy', 'Category']
df_tmp = df_portfolio_features[~df_portfolio_features['Symbol'].isin(['ENRIN','BLUSPRING','DIGITIDE'])]
df_tmp = df_tmp.sort_values(by = 'FTT Amt', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
50,MASFIN,2.19,-7.81,31.86,21.57,28779.0,-7650.0,90330.0,397.04,-20.51,41.0,H-SC,2.16,167.0,-0.27,0.67,25.27,XR,ATH,FINANCE
77,TTKPRESTIG,-0.68,-37.36,59.80,0.09,37747.0,-37655.0,63122.0,770.00,46.42,41.0,M-SC,16.91,250.0,-1.00,0.47,6.65,OX40N,NTT,DURABLES
37,ICICIGI,-1.84,-4.55,25.02,19.34,47791.0,-9097.0,191012.0,2252.93,-19.59,34.0,X-MC,2.34,66.0,-0.19,1.42,5.59,X40,ATH,INSURANCE
67,SONACOMS,3.62,-9.99,54.53,39.09,49651.0,-10107.0,91052.0,804.02,-28.71,54.0,M-MC,8.83,193.0,-0.20,0.68,28.81,AR,ATH,AUTO
2,ABBOTINDIA,0.19,-11.10,32.81,18.07,52168.0,-19855.0,159000.0,35195.00,-24.45,44.0,X-MC,10.82,58.0,-0.38,1.18,0.80,X40,ATH,PHARMA

In [10]:
# top 5 today
df_tmp = df_portfolio_features.sort_values(by = 'Today P/L%', ascending=False)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
80,VALIANTORG,20.00,-50.71,253.35,74.15,204286.0,-82971.0,80634.0,838.00,-245.35,55.0,H-SC,29.62,145.0,-0.41,0.60,20.00,XR,NTT,CHEMICALS
61,ROUTE,12.57,-61.94,341.81,68.16,173113.0,-82420.0,50646.0,2215.45,-69.24,48.0,H-SC,35.61,141.0,-0.48,0.38,12.57,SR,ATH,IT
18,CERA,7.23,-35.48,92.03,23.89,104442.0,-62416.0,113487.0,9475.00,-37.71,54.0,H-SC,18.00,153.0,-0.60,0.84,9.06,OX40N,NTT,CERAMICS
54,QUESS,5.53,-24.12,129.19,73.90,104683.0,-25763.0,81030.0,424.00,-59.23,42.0,X-SC,19.61,80.0,-0.25,0.60,5.60,XY24,NTT,MISC
4,ALKYLAMINE,5.06,-42.77,238.35,93.63,137716.0,-43184.0,57779.0,4546.37,-38.72,39.0,H-SC,23.96,142.0,-0.31,0.43,6.69,SR,ATH,CHEMICALS

In [11]:
# bottom 5 today
df_tmp = df_portfolio_features.sort_values(by = 'Today P/L%', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
37,ICICIGI,-1.84,-4.55,25.02,19.34,47791.0,-9097.0,191012.0,2252.93,-19.59,34.0,X-MC,2.34,66.0,-0.19,1.42,5.59,X40,ATH,INSURANCE
34,HDFCBANK,-0.85,0.27,28.02,28.37,65993.0,635.0,235520.0,1073.00,-14.61,35.0,X-LC,9.53,26.0,0.01,1.75,2.59,X40,BTT,BANKS
77,TTKPRESTIG,-0.68,-37.36,59.80,0.09,37747.0,-37655.0,63122.0,770.00,46.42,41.0,M-SC,16.91,250.0,-1.00,0.47,6.65,OX40N,NTT,DURABLES
71,TANLA,-0.58,-53.88,376.39,119.69,469972.0,-145898.0,124863.0,1943.92,-53.59,32.0,H-SC,24.43,147.0,-0.31,0.93,0.00,AR,ATH,IT
55,RAJESHEXPO,-0.54,-80.20,405.37,0.07,110107.0,-110015.0,27162.0,518.00,894.95,19.0,L-SC,27.68,268.0,-1.00,0.20,0.00,OX40N,NTT,JEWELLERY

In [12]:
# top 5 to exit based on CumlRnk
df_tmp = df_portfolio_features[~df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])]
df_tmp = df_tmp[(df_tmp['Current P/L%'] > -1) & (df_tmp['Current P/L%'] < 1)].sort_values(by = 'CumlRnk', ascending=False)
df_tmp[cols].head()

Empty DataFrame
Columns: [Symbol, Today P/L%, Current P/L%, FTT%, OTT%, FTT Amt, Current P/L, Current, FTT, Dev%_PE, RSI_14, Conviction, Spread%, CumlRnk, RRR Ind, CurrAlloc%, Gained%, Criteria, Strategy, Category]
Index: []

In [13]:
# OX40N stocks to exit
df_tmp = df_portfolio_features[(df_portfolio_features['Symbol'].isin(list_ox40n))].sort_values(by = 'Current P/L%', ascending=False)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
26,FINCABLES,1.50,10.23,88.62,107.91,144226.0,15102.0,162746.0,1641.55,-1.07,52.0,M-SC,8.03,220.0,0.10,1.21,22.44,OX40N,ATH,CABLES
18,CERA,7.23,-35.48,92.03,23.89,104442.0,-62416.0,113487.0,9475.00,-37.71,54.0,H-SC,18.00,153.0,-0.60,0.84,9.06,OX40N,NTT,CERAMICS
66,SIS,2.48,-35.96,89.35,21.26,63534.0,-39925.0,71107.0,528.00,1662.18,34.0,H-SC,13.05,168.0,-0.63,0.53,2.48,OX40N,NTT,MISC
70,SYMPHONY,4.66,-37.14,59.04,-0.03,63513.0,-63564.0,107577.0,1306.00,-49.50,49.0,M-SC,14.73,205.0,-1.00,0.80,8.79,OX40N,NTT,DURABLES
77,TTKPRESTIG,-0.68,-37.36,59.80,0.09,37747.0,-37655.0,63122.0,770.00,46.42,41.0,M-SC,16.91,250.0,-1.00,0.47,6.65,OX40N,NTT,DURABLES

In [14]:
# top 5 to book for rotation
df_tmp = df_portfolio_features[(df_portfolio_features['Current P/L%'] > 20) ].sort_values(by = 'CumlRnk', ascending=False)
df_tmp[cols].head()

Empty DataFrame
Columns: [Symbol, Today P/L%, Current P/L%, FTT%, OTT%, FTT Amt, Current P/L, Current, FTT, Dev%_PE, RSI_14, Conviction, Spread%, CumlRnk, RRR Ind, CurrAlloc%, Gained%, Criteria, Strategy, Category]
Index: []

In [15]:
# top 5 to monitor for exit
df_tmp = df_portfolio_features[~df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])]
df_tmp = df_tmp[(df_tmp['Current P/L%'] > 0) ].sort_values(by = 'Dev%_PE', ascending=False)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
26,FINCABLES,1.50,10.23,88.62,107.91,144226.0,15102.0,162746.0,1641.55,-1.07,52.0,M-SC,8.03,220.0,0.10,1.21,22.44,OX40N,ATH,CABLES
1,ABB,1.53,17.55,23.83,45.57,73286.0,45917.0,307536.0,7934.00,-24.43,65.0,H-MC,12.31,125.0,0.63,2.29,36.57,AR,NTT,ELECTRICAL

In [16]:
# top 5 to book for rotation from weak conviction
df_tmp = df_portfolio_features[~df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])]
df_tmp = df_tmp[~df_tmp['Criteria'].isin(['XY25','XY24','X40', 'X40N'])].sort_values(by = 'RRR Ind', ascending=False)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
1,ABB,1.53,17.55,23.83,45.57,73286.0,45917.0,307536.0,7934.00,-24.43,65.0,H-MC,12.31,125.0,0.63,2.29,36.57,AR,NTT,ELECTRICAL
26,FINCABLES,1.50,10.23,88.62,107.91,144226.0,15102.0,162746.0,1641.55,-1.07,52.0,M-SC,8.03,220.0,0.10,1.21,22.44,OX40N,ATH,CABLES
40,INDIAMART,0.98,-10.36,130.61,106.72,144400.0,-12778.0,110558.0,4810.62,-59.57,41.0,H-SC,10.29,140.0,-0.09,0.82,10.60,AR,ATH,MISC
85,ZYDUSLIFE,1.56,-4.70,42.32,35.63,84521.0,-9856.0,199718.0,1286.17,-17.12,49.0,H-MC,5.19,120.0,-0.12,1.49,11.18,AR,ATH,PHARMA
67,SONACOMS,3.62,-9.99,54.53,39.09,49651.0,-10107.0,91052.0,804.02,-28.71,54.0,M-MC,8.83,193.0,-0.20,0.68,28.81,AR,ATH,AUTO

In [17]:
# top 5 to accumulate based on lowest RSI_14
df_tmp = df_portfolio_features[df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])].sort_values(by = 'RSI_14', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
58,RELAXO,0.80,-64.03,323.40,52.31,168870.0,-92943.0,52217.0,1176.00,-61.67,15.0,X-SC,22.71,92.0,-0.55,0.39,0.80,X40N,NTT,FOOTWEAR
53,PGHH,0.06,-25.02,76.06,32.01,121769.0,-53424.0,160096.0,17616.87,-49.28,16.0,X-MC,13.36,57.0,-0.44,1.19,0.06,X40,ATH,FMCG
12,BATAINDIA,0.77,-56.37,209.85,35.20,117820.0,-72525.0,56145.0,2096.00,-26.35,18.0,X-SC,28.61,91.0,-0.62,0.42,0.77,X40,NTT,FOOTWEAR
3,ACC,0.86,-38.01,182.02,74.81,302517.0,-101928.0,166200.0,3906.00,-56.11,20.0,X-SC,14.67,85.0,-0.34,1.24,0.86,XY24,BTT,CEMENT
8,AWL,0.77,-39.27,175.01,67.02,378711.0,-139915.0,216394.0,485.00,-67.29,28.0,X-SC,25.20,81.0,-0.37,1.61,2.36,XY24,NTT,FMCG

In [18]:
# top 5 to accumulate based on Spread and CumlRnk
df_tmp = df_portfolio_features[df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])]
df_tmp = df_tmp[(df_tmp['CumlRnk'] < 100)].sort_values(by = 'Spread%', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
78,UNITDSPR,0.86,-3.58,25.25,20.77,57006.0,-8377.0,225767.0,1644.00,-14.48,41.0,X-MC,0.97,64.0,-0.15,1.68,2.89,X40N,NTT,BREWERIES
37,ICICIGI,-1.84,-4.55,25.02,19.34,47791.0,-9097.0,191012.0,2252.93,-19.59,34.0,X-MC,2.34,66.0,-0.19,1.42,5.59,X40,ATH,INSURANCE
38,ICICIPRULI,-0.08,-2.04,33.45,30.73,64556.0,-4013.0,192992.0,790.00,-28.37,32.0,X-MC,2.76,78.0,-0.06,1.44,10.41,X40,ATH,INSURANCE
21,DABUR,0.42,-11.14,61.72,43.70,136051.0,-27636.0,220432.0,735.00,-19.28,32.0,X-MC,3.21,70.0,-0.20,1.64,2.23,XY24,BTT,FMCG
59,RELIANCE,0.92,-9.46,38.39,25.30,69852.0,-19009.0,181954.0,1952.00,-11.96,50.0,X-LC,3.24,21.0,-0.27,1.35,21.48,XY25,BTT,REFINERIES

In [19]:
# top 5 to accumulate based on lowest Gained%
df_tmp = df_portfolio_features[df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])].sort_values(by = 'Gained%', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
53,PGHH,0.06,-25.02,76.06,32.01,121769.0,-53424.0,160096.0,17616.87,-49.28,16.0,X-MC,13.36,57.0,-0.44,1.19,0.06,X40,ATH,FMCG
20,COLPAL,0.48,-26.26,91.90,41.51,178479.0,-69155.0,194210.0,3726.84,-10.78,31.0,X-MC,4.21,62.0,-0.39,1.45,0.48,XY25,ATH,FMCG
36,HONAUT,0.74,-23.61,98.09,51.31,144487.0,-45538.0,147300.0,58357.33,-36.44,35.0,X-SC,14.46,90.0,-0.32,1.10,0.74,X40N,ATH,ELECTRICAL
12,BATAINDIA,0.77,-56.37,209.85,35.20,117820.0,-72525.0,56145.0,2096.00,-26.35,18.0,X-SC,28.61,91.0,-0.62,0.42,0.77,X40,NTT,FOOTWEAR
2,ABBOTINDIA,0.19,-11.10,32.81,18.07,52168.0,-19855.0,159000.0,35195.00,-24.45,44.0,X-MC,10.82,58.0,-0.38,1.18,0.80,X40,ATH,PHARMA

In [20]:
# top 5 to accumulate based on lowest CurrAlloc%
df_tmp = df_portfolio_features[df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])].sort_values(by = 'CurrAlloc%', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
58,RELAXO,0.80,-64.03,323.40,52.31,168870.0,-92943.0,52217.0,1176.00,-61.67,15.0,X-SC,22.71,92.0,-0.55,0.39,0.80,X40N,NTT,FOOTWEAR
12,BATAINDIA,0.77,-56.37,209.85,35.20,117820.0,-72525.0,56145.0,2096.00,-26.35,18.0,X-SC,28.61,91.0,-0.62,0.42,0.77,X40,NTT,FOOTWEAR
54,QUESS,5.53,-24.12,129.19,73.90,104683.0,-25763.0,81030.0,424.00,-59.23,42.0,X-SC,19.61,80.0,-0.25,0.60,5.60,XY24,NTT,MISC
36,HONAUT,0.74,-23.61,98.09,51.31,144487.0,-45538.0,147300.0,58357.33,-36.44,35.0,X-SC,14.46,90.0,-0.32,1.10,0.74,X40N,ATH,ELECTRICAL
51,MEDANTA,1.55,-9.92,41.12,27.12,65382.0,-17514.0,159003.0,1486.00,-12.65,37.0,X-SC,9.95,87.0,-0.27,1.18,2.23,XY24,NTT,HEALTHCARE

In [21]:
# top 5 to accumulate based on CumlRnk
df_tmp = df_portfolio_features.sort_values(by = 'CumlRnk', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
45,ITC,0.51,-19.29,47.52,19.06,130459.0,-65632.0,274534.0,452.00,-55.52,40.0,X-LC,17.33,1.0,-0.50,2.04,1.64,X40,NTT,FMCG
73,TCS,3.50,-27.33,74.17,26.57,249707.0,-126605.0,336668.0,4311.58,-38.38,33.0,X-LC,15.85,2.0,-0.51,2.51,3.50,X40,ATH,IT
43,INFY,4.00,-12.71,53.80,34.24,146933.0,-39779.0,273109.0,1972.00,-31.42,37.0,X-LC,14.05,3.0,-0.27,2.03,4.00,X40,NTT,IT
75,TMPV,2.85,-25.27,82.76,36.58,220078.0,-89918.0,265923.0,600.00,-84.72,39.0,X-LC,3.39,4.0,-0.41,1.98,4.52,XY24,NTT,AUTO
33,HCLTECH,3.97,-10.86,38.93,23.83,83949.0,-26284.0,215640.0,1908.19,-6.53,41.0,X-LC,10.77,8.0,-0.31,1.61,3.97,X40,ATH,IT

In [22]:
# top 5 for average up
df_tmp = df_portfolio_features[(df_portfolio_features['Dev%_200'] > 5)].sort_values(by = 'CurrAlloc%', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
67,SONACOMS,3.62,-9.99,54.53,39.09,49651.0,-10107.0,91052.0,804.02,-28.71,54.0,M-MC,8.83,193.0,-0.20,0.68,28.81,AR,ATH,AUTO
1,ABB,1.53,17.55,23.83,45.57,73286.0,45917.0,307536.0,7934.00,-24.43,65.0,H-MC,12.31,125.0,0.63,2.29,36.57,AR,NTT,ELECTRICAL

In [23]:
# top 5 RSP
df_tmp = df_portfolio_features.sort_values(by = 'RSP', ascending=False)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
1,ABB,1.53,17.55,23.83,45.57,73286.0,45917.0,307536.0,7934.00,-24.43,65.0,H-MC,12.31,125.0,0.63,2.29,36.57,AR,NTT,ELECTRICAL
26,FINCABLES,1.50,10.23,88.62,107.91,144226.0,15102.0,162746.0,1641.55,-1.07,52.0,M-SC,8.03,220.0,0.10,1.21,22.44,OX40N,ATH,CABLES
69,SURYODAY,-0.30,-27.85,70.54,23.03,91133.0,-49878.0,129193.0,216.00,40.35,47.0,H-SC,6.82,166.0,-0.55,0.96,28.19,XR,NTT,BANKS
65,SIEMENS,1.08,-13.82,45.63,25.51,73184.0,-25710.0,160385.0,4671.50,34.61,49.0,H-LC,3.63,51.0,-0.35,1.19,18.11,AR,ATH,ELECTRICAL
47,JSWINFRA,2.75,-11.52,31.59,16.43,61987.0,-25550.0,196224.0,342.00,-24.13,51.0,X-MC,11.42,61.0,-0.41,1.46,5.35,X40N,NTT,REALTY

In [24]:
# Top N allocation
df_tmp = df_portfolio_features.sort_values(by = 'CurrAlloc%', ascending=False)
top_n_values = [10, 25, 50]

sum_df = pd.DataFrame({
    'Top_N': top_n_values,
    'Sum_Alloc%': [df_tmp['CurrAlloc%'].head(n).sum() for n in top_n_values]
})

sum_df

   Top_N  Sum_Alloc%
0     10       20.71
1     25       45.63
2     50       78.01

In [25]:
# market-cap-wise allocation
df_tmp = df_portfolio_features[cols]
df_tmp.groupby(df_tmp['Conviction'].str[-2:])['CurrAlloc%'].sum().sort_values(ascending=False)

Conviction
SC    44.25
MC    30.18
LC    25.54
Name: CurrAlloc%, dtype: float64

In [26]:
# criteria-wise allocation
df_portfolio_features.groupby('Criteria')['CurrAlloc%'].sum().sort_values(ascending=False)

Criteria
XY24     27.00
X40      25.53
X40N     15.00
AR        9.17
XR        8.22
XY25      7.41
OX40N     6.83
SR        0.81
Name: CurrAlloc%, dtype: float64

In [27]:
# conviction-wise allocation
df_portfolio_features.groupby('Conviction')['CurrAlloc%'].sum().sort_values(ascending=False)

Conviction
X-LC    23.33
X-MC    22.66
H-SC    21.58
X-SC    12.05
M-SC    10.06
H-MC     5.07
M-MC     2.10
H-LC     1.19
M-LC     1.02
L-SC     0.56
L-MC     0.35
Name: CurrAlloc%, dtype: float64

In [28]:
# sector-wise stats
df_tmp = df_portfolio_features.groupby('Category')[['CurrAlloc%', 'Current', 'Current P/L', 'FTT Amt']].sum().sort_values(by=['Current', 'Current P/L'], ascending=False)
df_tmp['Current P/L%'] = round(df_tmp['Current P/L'] * 100 / df_tmp['Current'], 2)
df_tmp['FTT%'] = round(df_tmp['FTT Amt'] * 100 / df_tmp['Current'], 2)
cols = ['CurrAlloc%', 'Current P/L%', 'FTT%']
df_tmp[cols].sort_values(by=['CurrAlloc%'], ascending=False)

               CurrAlloc%  Current P/L%    FTT%
Category
FMCG                15.05        -23.53   67.39
FINANCE             13.05        -22.55   72.49
IT                  11.71        -43.40  116.38
MISC                 6.92        -44.11  106.70
ELECTRICAL           6.66         -8.27   49.73
PAINTS               5.07        -44.47   69.56
INSURANCE            4.75         -6.35   42.74
BANKS                4.67        -22.54   84.74
PHARMA               4.14         -5.64   38.90
AUTO                 3.74        -30.21   81.87
AC                   2.12        -11.83   42.14
HEALTHCARE           1.92        -38.29   74.38
DURABLES             1.84        -56.19   94.19
TRAVEL               1.80        -84.29  176.56
FOOTWEAR             1.79        -83.74  157.41
BREWERIES            1.68         -3.71   25.25
APPARELS             1.63        -22.43   64.20
REALTY               1.46        -13.02   31.59
CERAMICS             1.40        -63.06  112.61
REFINERIES           1.35        -10.45   38.39
CEMENT               1.24        -61.33  182.02
CABLES               1.21          9.28   88.62
ENGINEERING          1.10        -64.23  139.35
JEWELLERY            1.09       -117.08  192.50
CHEMICALS            1.03        -91.14  247.09
ENTERTAINMENT        0.77        -87.71  199.66
TEXTILES             0.42        -63.60  110.25
HOTELS               0.36       -133.20  215.46

In [29]:
# money to be made criteria-wise
df_portfolio_features.groupby('Criteria')['FTT Amt'].agg(['sum', 'count']).sort_values(by='sum', ascending=False)

                sum  count
Criteria
XY24      3967015.0     21
X40       1743656.0     16
XR        1385298.0     12
AR        1339883.0     10
X40N      1286518.0     10
OX40N      873682.0     10
XY25       444845.0      5
SR         310829.0      2

In [30]:
# money to be made conviction-wise
df_portfolio_features.groupby('Conviction')['FTT Amt'].agg(['sum', 'count']).sort_values(by='sum', ascending=False)

                  sum  count
Conviction
H-SC        3891599.0     24
X-MC        1689005.0     15
X-LC        1642219.0     13
M-SC        1564683.0     14
X-SC        1563222.0     10
H-MC         397562.0      3
L-SC         215017.0      2
M-LC         154994.0      1
M-MC         104425.0      2
H-LC          73184.0      1
L-MC          55816.0      1

In [31]:
# money to be made criteria and conviction-wise
df_portfolio_features.groupby(['Conviction', 'Criteria'])['FTT Amt'].agg(['sum', 'count']).sort_values(by='sum', ascending=False)

                           sum  count
Conviction Criteria
H-SC       XY24      1340705.0      6
           AR         981737.0      5
M-SC       XY24       912354.0      6
X-LC       X40        879373.0      7
H-SC       XR         875458.0      7
X-SC       XY24       851293.0      4
X-MC       X40        660601.0      7
           X40N       524182.0      4
X-SC       X40N       508247.0      4
H-SC       OX40N      382870.0      4
M-SC       OX40N      380705.0      5
X-LC       XY24       361656.0      2
H-SC       SR         310829.0      2
X-MC       XY24       261252.0      2
X-LC       X40N       254089.0      2
X-MC       XY25       242970.0      2
H-MC       XY24       239755.0      1
X-SC       X40        203682.0      2
M-SC       XR         194120.0      2
H-MC       AR         157807.0      2
M-LC       XR         154994.0      1
X-LC       XY25       147101.0      2
L-SC       OX40N      110107.0      1
           XR         104910.0      1
M-SC       AR          77504.0      1
H-LC       AR          73184.0      1
L-MC       XR          55816.0      1
M-MC       XY25        54774.0      1
           AR          49651.0      1

In [32]:
# notebook execution time

end_time = time.time()
execution_time = round(end_time - start_time, 0)
print(f"Notebook execution time: {execution_time} seconds")

Notebook execution time: 31.0 seconds