<a href="https://colab.research.google.com/github/ankit-rathi/Quantvesting_v2/blob/main/myStocks_Portfolio_Analysis.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
'''
!pip install pandas==2.2.2 -qq
!pip install pyxirr -qq
!pip install ta -qq
!pip install yfinance==0.2.59 -qq
'''

'\n!pip install pandas==2.2.2 -qq\n!pip install pyxirr -qq\n!pip install ta -qq\n!pip install yfinance==0.2.59 -qq\n'

In [2]:
# import libraries

import numpy as np
import pandas as pd
import datetime
import warnings
warnings.filterwarnings('ignore')
import yfinance as yfin
import ta
import matplotlib.pyplot as plt
import requests

In [3]:
# notebook start time
import time
import datetime
import pytz

start_time = time.time()

# function to print date timestamp
def print_date_time():
  tz_NY = pytz.timezone('Asia/Kolkata')
  datetime_NY = datetime.datetime.now(tz_NY)
  print("Run date time (IST):", datetime_NY.strftime("%Y-%m-%d %H:%M:%S"))

In [4]:
# function to get booked and reserved amount
def get_amt():
  # fetch the JSON data from the URL
  url = "https://raw.githubusercontent.com/ankit-rathi/Tradevesting_v1/main/data/myPortfolioAmts.json"
  response = requests.get(url)
  pf_amts = response.json()  # parse the JSON data

  # extract values from the JSON
  py_booked_amt_dm = pf_amts["py_booked_amt_dm"]
  py_booked_amt_sv = pf_amts["py_booked_amt_sv"]
  cy_booked_amt_dm = pf_amts["cy_booked_amt_dm"]
  cy_booked_amt_sv = pf_amts["cy_booked_amt_sv"]
  reserve_amt_dm = pf_amts["reserve_amt_dm"]
  reserve_amt_sv = pf_amts["reserve_amt_sv"]

  # perform calculations
  py_booked_amt = py_booked_amt_dm + py_booked_amt_sv
  cy_booked_amt = cy_booked_amt_dm + cy_booked_amt_sv
  reserve_amt = reserve_amt_dm + reserve_amt_sv
  total_booked_amt = py_booked_amt + cy_booked_amt

  return total_booked_amt, reserve_amt, cy_booked_amt, py_booked_amt

gen_output = 0

In [5]:
# function to format the amount
def format_amt(number):
    abs_number = abs(number)

    if abs_number >= 1_00_00_000:  # Crores
        formatted_amt = f"{number / 1_00_00_000:.2f} C"
    elif abs_number >= 1_00_000:  # Lakhs
        formatted_amt = f"{number / 1_00_000:.2f} L"
    elif abs_number >= 1_000:  # Thousands
        formatted_amt = f"{number / 1_000:.2f} K"
    else:
        formatted_amt = f"{number:.2f}"

    return formatted_amt

# function to set start and end date
def get_start_end_date():
  start_date = (datetime.date.today() + datetime.timedelta(days=-365)).strftime('%Y-%m-%d')
  end_date = (datetime.date.today() + datetime.timedelta(days=1)).strftime('%Y-%m-%d')
  return start_date, end_date

# function to fetch my portfolio csv
def get_mypfs_df():
  mypfs_df = pd.read_csv('https://raw.githubusercontent.com/ankit-rathi/Tradevesting_v1/main/data/myPortfolioStocks.csv')
  return mypfs_df

# function to fetch my prospects csv
def get_mypps_df():
  mypps_df = pd.read_csv('https://raw.githubusercontent.com/ankit-rathi/Tradevesting_v1/main/data/myProspectsScrips.csv')
  return mypps_df

# function to fetch screener data
def get_myscreen_df():
  myscreen_df = pd.read_csv('https://raw.githubusercontent.com/ankit-rathi/Tradevesting_v1/main/data/myScreenerDB.csv')
  return myscreen_df

# function to fetch momentum data
def get_myinvmt_df():
  myinvmt_df = pd.read_csv('https://raw.githubusercontent.com/ankit-rathi/Tradevesting_v1/main/data/myInvestments.csv')
  return myinvmt_df

# function to get the stock ids
def get_stock_ids(df_pf):
  stock_n100 = df_pf['Symbol'].unique()

  exclude = ['CADILAHC','MMTC', 'MASFIN']

  stock_ids = df_pf[~df_pf['Symbol'].isin(exclude) ]['Symbol'].unique()

  #mypf = mypf[mypf.Forecast.notnull()]
  #stock_ids = mypf['Symbol'].unique()

  #stock_ids.sort()
  return stock_ids

# get features from screener data
def get_screener_features():
  myscreen_df = get_myscreen_df()
  cols = ['Symbol', 'EPS', 'MedPE', 'ROCE%', 'ROE%', 'CapType']
  return myscreen_df[cols]

# get relative strength
def get_relative_strength(stock_list):

    # Dictionary to store stock tickers and their corresponding percentage price change
    stock_changes = {}

    # Loop through each stock and fetch its price data
    for stock in stock_list:
        try:
            # Download the stock data for the given date range
            stock_data = yfin.Ticker(stock + '.NS').history(period='1mo', interval='1d')[map(str.title, ['open', 'close', 'low', 'high', 'volume'])]

            # Calculate the percentage change for the stock
            if len(stock_data) > 0:
                start_price = stock_data['Close'].iloc[0]
                end_price = stock_data['Close'].iloc[-1]
                percent_change = round(((end_price - start_price) / start_price) * 100, 2)
                stock_changes[stock] = percent_change
            else:
                stock_changes[stock] = np.nan  # If no data is available, set to NaN

        except Exception as e:
            print(f"Error fetching data for {stock}: {e}")
            stock_changes[stock] = np.nan

    # Create a DataFrame with stock tickers and their percentage changes
    df = pd.DataFrame(list(stock_changes.items()), columns=['Symbol', 'Percent_Change'])

    # Drop any stocks with missing data (NaN values)
    df = df.dropna()

    # Calculate the percentile rank based on percentage change
    df['RSP'] = round(df['Percent_Change'].rank(pct=True) * 100, 2)
    cols = ['Symbol', 'RSP']
    df = df[cols]
    # Sort by percentile rank (optional)
    df = df.sort_values(by='RSP', ascending=False).reset_index(drop=True)

    return df

In [6]:
# function to get stock technicals
def stock_prec_dev(stock_symbol):
    #stock_symbol = 'ULTRACEMCO.NS'
    short_window = 20
    mid_window = 50
    long_window = 200
    moving_avg = 'SMA'

    start = datetime.datetime(*map(int, start_date.split('-')))
    end = datetime.datetime(*map(int, end_date.split('-')))

    stock_df = yfin.Ticker(stock_symbol + '.NS').history(period='max', interval='1d')[map(str.title, ['open', 'close', 'low', 'high', 'volume'])]

    stock_df['Max'] = round(max(stock_df['Close']),2)
    stock_df = stock_df[(stock_df.index <= end_date) & (stock_df.index >= start_date)]
    stock_df['200_SMA'] = round(stock_df['Close'].rolling(window = 200, min_periods = 1).mean(),0)
    stock_df['Dev%_200'] = round((stock_df['Close'] - stock_df['200_SMA'])*100/stock_df['200_SMA'],2)
    stock_df.dropna(axis = 0, inplace = True) # remove any null rows

    stock_df['20_SMA'] = stock_df['Close'].rolling(window=20).mean()
    stock_df['50_SMA'] = stock_df['Close'].rolling(window=50).mean()
    stock_df['Symbol'] = stock_symbol

    stock_df['Close'] = round(stock_df['Close'],2)
    stock_df['Min'] = round(min(stock_df['Close']),2)
    stock_df['RSI_14'] = ta.momentum.RSIIndicator(close=stock_df['Close'], window=14).rsi()
    stock_df['RSI_14'] = round(stock_df['RSI_14'],0)
    stock_df['Prev_Close'] = stock_df['Close'].shift(1)
    stock_df.drop(['Open', 'Low', 'High', 'Volume'], axis=1, inplace=True)
    stock_df = stock_df.tail(1)

    max_SMA = max(stock_df['20_SMA'].item(), stock_df['50_SMA'].item(), stock_df['200_SMA'].item())
    min_SMA = min(stock_df['20_SMA'].item(), stock_df['50_SMA'].item(), stock_df['200_SMA'].item())
    ABS_Spread = max_SMA - min_SMA
    stock_df['Spread%'] = round((ABS_Spread / stock_df['200_SMA'].item()) * 100,2)

    return stock_df

# function to compute stock attributes
def get_common_features(stock_ids, df_mypf):

  df_prec_dev = pd.DataFrame()
  df_tmp = get_screener_features()
  df_rs = get_relative_strength(stock_ids)

  for stock_id in stock_ids:
      tmp = stock_prec_dev(stock_id)
      tmp = tmp.reset_index()
      df_prec_dev = pd.concat([df_prec_dev, tmp], ignore_index = True)
  df_prec_dev = pd.merge(df_prec_dev, df_mypf, on= 'Symbol')
  df_prec_dev = pd.merge(df_prec_dev, df_tmp, on= 'Symbol', how='left')
  df_prec_dev = pd.merge(df_prec_dev, df_rs, on= 'Symbol', how='left')
  #print(df_prec_dev.columns)
  df_prec_dev['Curr_PE'] = round(df_prec_dev['Close']/df_prec_dev['EPS'],1)
  df_prec_dev['Dev%_PE'] = round((df_prec_dev['Curr_PE'] - df_prec_dev['MedPE'])*100/df_prec_dev['MedPE'],2)
  df_prec_dev['Conviction'] = df_prec_dev['Conviction'] + '-' + df_prec_dev['CapType']
  return df_prec_dev

# function to arrange stock features
def arrange_features(df_stocks, common_cols, diff_cols):
  df_stocks_common = df_stocks[common_cols].drop_duplicates()
  df_stocks_diff = df_stocks[diff_cols]
  df_stocks_diff['Investment'] = df_stocks_diff['AvgCost'] * df_stocks_diff['Shares']
  df_stocks_diff = df_stocks_diff.groupby(['Symbol'])[['Shares', 'Investment']].aggregate(['sum']).reset_index()
  df_stocks_diff.columns = ['Symbol', 'Shares', 'Investment']
  df_stocks_diff['AvgCost'] = round(df_stocks_diff['Investment']/df_stocks_diff['Shares'],2)
  df_stocks = pd.merge(df_stocks_diff, df_stocks_common, on='Symbol')
  return df_stocks

# plot fact distribution across dimension
def plot_pie_chart(df, dimension, fact):
  # grouping the data by category and calculating the sum of fact for each type
  grouped_data = df.groupby(dimension)[fact].sum()

  # sorting the grouped data in descending order
  grouped_data = grouped_data.sort_values(ascending=False)

  # creating a pie chart
  grouped_data.plot.pie(autopct='%1.1f%%', startangle=90, figsize=(6, 6))

  # adding a title and displaying the plot
  plt.title(f'{dimension} {fact} Distribution')
  plt.ylabel('')  # To hide the y-label
  plt.show()

In [7]:
# function to get portfolio features

def get_portfolio_features(df_common_features):

  print_date_time()
  print('-------------------')

  #df_common_features["Target"] = df_common_features["Target"].fillna(df_common_features["Max"])
  df_common_features['NTT'] = np.where(df_common_features['Strategy']== 'NTT', df_common_features["Target"], df_common_features['Max'])
  df_common_features['LTT'] = np.where(df_common_features['Strategy']== 'BTT', df_common_features["Target"], df_common_features['Max'])
  df_common_features['BOL'] = df_common_features['Min']

  tmp_df = df_common_features[df_common_features['Symbol'].isin(mypf_df[mypf_df['InPortfolio'] != 'NA'].Symbol.values)]
  print('qualified stocks: '+str(len(tmp_df['Symbol'].unique())))
  tmp_df1 = tmp_df[tmp_df['LatestQtr'] == 1]
  print('with latest results: '+str(len(tmp_df1['Symbol'].unique())))
  tmp_df1 = tmp_df1[tmp_df1['StarStock'] == 1]
  print('still star stocks: '+str(len(tmp_df1['Symbol'].unique())))
  tmp_df['Investment'] = tmp_df['AvgCost'] * tmp_df['Shares']
  tmp_df['Current'] = round(tmp_df['Close'] * tmp_df['Shares'],0)
  tmp_df['Previous'] = tmp_df['Prev_Close'] * tmp_df['Shares']
  tmp_df['EstimatedST'] = tmp_df['NTT'] * tmp_df['Shares']
  tmp_df['EstimatedLT'] = tmp_df['LTT'] * tmp_df['Shares']
  tmp_df['Current P/L'] = round((tmp_df['Current'] - tmp_df['Investment']),0)
  tmp_df['Today P/L%'] = round((tmp_df['Current'] - tmp_df['Previous'])*100/tmp_df['Previous'],2)
  tmp_df['Current P/L%'] = round((tmp_df['Current'] - tmp_df['Investment'])*100/tmp_df['Investment'],2)
  tmp_df['EstimatedST P/L%'] = round((tmp_df['EstimatedST'] - tmp_df['Investment'])*100/tmp_df['Investment'],2)
  tmp_df['EstimatedLT P/L%'] = round((tmp_df['EstimatedLT'] - tmp_df['Investment'])*100/tmp_df['Investment'],2)
  tmp_df['NTT%'] = round((tmp_df['NTT'] - tmp_df['Close'])*100/tmp_df['Close'],2)
  tmp_df['LTT%'] = round((tmp_df['LTT'] - tmp_df['Close'])*100/tmp_df['Close'],2)
  tmp_df['Gained%'] = round((tmp_df['Close'] - tmp_df['BOL'])*100/tmp_df['BOL'],2)
  investment = round(sum(tmp_df['AvgCost']*tmp_df['Shares']),0)
  current = round(sum(tmp_df['Close']*tmp_df['Shares']),0)
  tmp_df['InitAlloc%'] = round(tmp_df['Investment']*100/investment,2)
  tmp_df['CurrAlloc%'] = round(tmp_df['Current']*100/current,2)
  tmp_df['FTT'] = tmp_df['LTT']
  tmp_df.loc[tmp_df['Strategy'] == 'NTT', 'FTT'] = tmp_df['NTT']
  tmp_df['FTT%'] = tmp_df['LTT%']
  tmp_df.loc[tmp_df['Strategy'] == 'NTT', 'FTT%'] = tmp_df['NTT%']
  tmp_df['FTT Amt'] = round(tmp_df['FTT%'] * tmp_df['Current']/100,0)
  tmp_df['OTT%'] = round((tmp_df['FTT'] - tmp_df['AvgCost'])*100/tmp_df['AvgCost'],2)
  tmp_df['RRR Ind'] = round(tmp_df['Current P/L']/tmp_df['FTT Amt'],2)
  tmp_df['Risk Ind'] = round(tmp_df['Current P/L%']*tmp_df['CurrAlloc%'],0)

  return tmp_df

# function to print portfolio features
def print_portfolio_stats(df_portfolio_features, myinvmt_df):
  from pyxirr import xirr

  total_booked_amt, reserve_amt, cy_booked_amt, py_booked_amt = get_amt()

  dates = myinvmt_df['Date'].values
  dates = np.append(dates, datetime.date.today().strftime('%d-%b-%y'))
  investment = myinvmt_df['Investment'].values
  dates= pd.to_datetime(dates)

  current = round(sum(df_portfolio_features['Close']*df_portfolio_features['Shares']),0) + reserve_amt
  investment_xirr = np.append(investment, current)
  cagr = round(xirr(pd.DataFrame({"dates": dates, "amounts": investment_xirr}))*100,2)

  investment = -sum(investment)
  invested = round(sum(df_portfolio_features['AvgCost']*df_portfolio_features['Shares']),0) + reserve_amt
  previous = round(sum(df_portfolio_features['Prev_Close']*df_portfolio_features['Shares']),0) + reserve_amt
  cy_invested = investment + py_booked_amt

  today_pnl_amount = current-previous
  today_pnl_percentage = round((current-previous)*100/previous,2)

  curr_pnl_amount = current-invested
  curr_pnl_percentage = round((curr_pnl_amount)*100/(cy_invested),2)

  cy_pnl_amount = cy_booked_amt + curr_pnl_amount
  cy_pnl_percentage = round((cy_pnl_amount)*100/cy_invested,2)

  overall_pnl_amount = total_booked_amt + curr_pnl_amount
  overall_pnl_percentage = round((overall_pnl_amount)*100/investment,2)

  estimate_st = round(sum(df_portfolio_features['FTT']*df_portfolio_features['Shares']),0)  + reserve_amt
  est_st_pnl_amount = estimate_st-current
  est_st_pnl_percentage = round((est_st_pnl_amount)*100/current,2)

  estimate_lt = round(sum(df_portfolio_features['LTT']*df_portfolio_features['Shares']),0)  + reserve_amt
  est_lt_pnl_amount = estimate_lt-current
  est_lt_pnl_percentage = round((est_lt_pnl_amount)*100/current,2)

  total_profit = round(sum(df_portfolio_features[df_portfolio_features['Current P/L%'] > 0]['Current']) - sum(df_portfolio_features[df_portfolio_features['Current P/L%'] > 0]['Investment']),0)
  total_loss = round(sum(df_portfolio_features[df_portfolio_features['Current P/L%'] < 0]['Current']) - sum(df_portfolio_features[df_portfolio_features['Current P/L%'] < 0]['Investment']),0)

  cy_booked_percentage = round((cy_booked_amt)*100/current,2)
  py_booked_percentage = round((py_booked_amt)*100/investment,2)
  total_booked_percentage = round((total_booked_amt)*100/investment,2)

  print('-------------------')
  print('Initial Investment: ', format_amt(investment))
  print('CY Investment: ', format_amt(cy_invested))
  print('Reserve: ', format_amt(reserve_amt))
  print('Current: ',  format_amt(current))
  print('-------------------')
  print('Today PnL: '+ '{} ({}%)'.format(format_amt(today_pnl_amount), today_pnl_percentage))
  print('Current PnL: '+ '{} ({}%)'.format(format_amt(curr_pnl_amount), curr_pnl_percentage))
  print('CY Booked + Current PnL: '+ '{} ({}%)'.format(format_amt(cy_pnl_amount), cy_pnl_percentage))
  print('-------------------')
  print('Total profit: ', format_amt(total_profit))
  print('Total loss: ', format_amt(total_loss))
  print('-------------------')
  print('Total Booked + Current PnL: '+ '{} ({}%)'.format(format_amt(overall_pnl_amount), overall_pnl_percentage))
  print('Total Booked PnL: '+ '{} ({}%)'.format(format_amt(total_booked_amt), total_booked_percentage))
  print('Curr Year Booked PnL: '+ '{} ({}%)'.format(format_amt(cy_booked_amt), cy_booked_percentage))
  print('Prev Year Booked PnL: '+ '{} ({}%)'.format(format_amt(py_booked_amt), py_booked_percentage))
  print('===================')
  print('Est FTT: ',  format_amt(estimate_st))
  print('Est FTT PnL: '+ '{} ({}%)'.format(format_amt(est_st_pnl_amount), est_st_pnl_percentage))

  print('===================')
  print('Deployed: ', format_amt(investment))

  print('Current: ', format_amt(current))

  print('CAGR/XIRR %: '+'{}%'.format(cagr))

In [8]:
# get start and end date
start_date, end_date = get_start_end_date()

# get portfolio and prospects data
mypfs_df = get_mypfs_df()
mypps_df = get_mypps_df()
myinvmt_df = get_myinvmt_df()

# merge above datasets
mypf_df = pd.merge(mypfs_df, mypps_df, on="Symbol")

# seggregate dm and sv portfolio
dm_pf = mypf_df[mypf_df['InPortfolio'] == 'DM']
sv_pf = mypf_df[mypf_df['InPortfolio'] == 'SV']

# build portfolio stock dataframe
dm_stocks = get_stock_ids(dm_pf)
sv_stocks = get_stock_ids(sv_pf)
df_stocks = pd.concat([dm_pf,sv_pf], ignore_index = True)

# arrange common and diff stock features
common_cols = ['Symbol', 'Target', 'Criteria', 'Strategy', 'CumlRnk', 'LatestQtr', 'StarStock', 'Conviction', 'Category', 'InFolio', 'XIRR', 'MBQ']
diff_cols = ['Symbol', 'AvgCost', 'Shares']
df_stocks = arrange_features(df_stocks, common_cols, diff_cols)

# get common features
stock_ids = df_stocks['Symbol'].values
df_common_features = get_common_features(stock_ids, df_stocks)

df_common_features.reset_index(drop=True, inplace=True)
df_common_features.drop(['Date'], axis=1, inplace=True)
# get and print portfolio features
df_portfolio_features = get_portfolio_features(df_common_features)

print_portfolio_stats(df_portfolio_features, myinvmt_df)

df = df_portfolio_features
#plot_pie_chart(df, 'CapType', 'Current')
list_ox40n = list(df[df['MBQ'].str.contains('OX40N', na=False)]['Symbol'].values)

Run date time (IST): 2026-04-16 13:57:33
-------------------
qualified stocks: 86
with latest results: 26
still star stocks: 16
-------------------
Initial Investment:  1.36 C
CY Investment:  1.62 C
Reserve:  1.61 K
Current:  1.42 C
-------------------
Today PnL: 69.96 K (0.5%)
Current PnL: -35.31 L (-21.73%)
CY Booked + Current PnL: -19.42 L (-11.95%)
-------------------
Total profit:  1.80 L
Total loss:  -37.11 L
-------------------
Total Booked + Current PnL: 7.56 L (5.58%)
Total Booked PnL: 42.87 L (31.64%)
Curr Year Booked PnL: 15.89 L (11.2%)
Prev Year Booked PnL: 26.98 L (19.91%)
===================
Est FTT:  2.48 C
Est FTT PnL: 1.06 C (74.79%)
===================
Deployed:  1.36 C
Current:  1.42 C
CAGR/XIRR %: 2.2%

In [9]:
# top 5 near their targets
cols = ['Symbol', 'Today P/L%', 'Current P/L%', 'FTT%', 'OTT%', 'FTT Amt', 'Current P/L', 'Current', 'FTT', 'Dev%_PE', 'RSI_14','Conviction', 'Spread%',  'CumlRnk', 'RRR Ind', 'CurrAlloc%', 'Gained%', 'Criteria', 'Strategy', 'Category']
df_tmp = df_portfolio_features[~df_portfolio_features['Symbol'].isin(['ENRIN','BLUSPRING','DIGITIDE'])]
df_tmp = df_tmp.sort_values(by = 'FTT Amt', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
5,ANGELONE,-2.47,19.02,4.34,24.18,15754.0,58000.0,363000.0,303.00,-82.85,70.0,X-SC,1.20,97.0,3.68,2.56,38.87,X40N,NTT,FINANCE
50,MASFIN,1.35,-2.65,24.87,21.57,23722.0,-2595.0,95385.0,397.04,-15.99,58.0,H-SC,4.24,167.0,-0.11,0.67,23.26,XR,ATH,FINANCE
77,TTKPRESTIG,-0.27,-37.68,60.60,0.09,38062.0,-37969.0,62808.0,770.00,45.78,49.0,M-SC,23.38,250.0,-1.00,0.44,11.84,OX40N,NTT,DURABLES
67,SONACOMS,-0.46,0.86,37.91,39.09,38678.0,866.0,102025.0,804.02,-20.06,68.0,M-MC,9.00,193.0,0.02,0.72,44.33,AR,ATH,AUTO
37,ICICIGI,1.44,-0.17,19.54,19.34,39037.0,-331.0,199778.0,2252.93,-15.91,64.0,X-MC,7.47,66.0,-0.01,1.41,11.58,X40,ATH,INSURANCE

In [10]:
# top 5 today
df_tmp = df_portfolio_features.sort_values(by = 'Today P/L%', ascending=False)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
80,VALIANTORG,8.90,-39.66,188.60,74.15,186197.0,-64879.0,98726.0,838.0,-277.79,67.0,H-SC,19.88,145.0,-0.35,0.70,46.92,XR,NTT,CHEMICALS
55,RAJESHEXPO,5.00,-75.46,307.71,0.07,103600.0,-103509.0,33668.0,518.0,1133.59,64.0,L-SC,43.08,268.0,-1.00,0.24,58.06,OX40N,NTT,JEWELLERY
60,REPCOHOME,4.53,-12.91,117.96,89.82,294331.0,-36987.0,249518.0,880.0,-56.78,62.0,H-SC,6.46,161.0,-0.13,1.76,19.95,XY24,NTT,FINANCE
29,GREENPANEL,4.15,-41.37,144.16,43.14,154728.0,-75747.0,107331.0,537.0,140.31,68.0,M-SC,23.98,225.0,-0.49,0.76,28.93,XY24,NTT,MISC
57,RECLTD,3.79,-0.92,21.86,20.74,44004.0,-1870.0,201300.0,446.0,9.37,65.0,M-MC,6.63,191.0,-0.04,1.42,19.96,XY25,NTT,FINANCE

In [11]:
# bottom 5 today
df_tmp = df_portfolio_features.sort_values(by = 'Today P/L%', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
14,BOSCH-HCIL,-5.47,-43.70,77.59,-0.01,55834.0,-55845.0,71960.0,2282.00,14617.39,51.0,M-SC,9.16,231.0,-1.00,0.51,22.49,OX40N,BTT,AC
5,ANGELONE,-2.47,19.02,4.34,24.18,15754.0,58000.0,363000.0,303.00,-82.85,70.0,X-SC,1.20,97.0,3.68,2.56,38.87,X40N,NTT,FINANCE
22,DEN,-1.52,-45.82,162.24,42.07,74241.0,-38704.0,45760.0,75.00,63.21,61.0,M-SC,18.12,235.0,-0.52,0.32,24.46,AR,NTT,ENTERTAINMENT
24,DMART,-1.42,6.00,22.27,29.60,58921.0,14976.0,264576.0,5391.45,-10.59,64.0,X-LC,3.67,14.0,0.25,1.87,20.93,X40N,ATH,FMCG
31,HATHWAY,-1.39,-37.14,175.68,73.29,120060.0,-40380.0,68340.0,31.40,693.48,64.0,H-SC,22.10,171.0,-0.34,0.48,28.41,XR,NTT,ENTERTAINMENT

In [12]:
# top 5 to exit based on CumlRnk
df_tmp = df_portfolio_features[~df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])]
df_tmp = df_tmp[(df_tmp['Current P/L%'] > -1) & (df_tmp['Current P/L%'] < 1)].sort_values(by = 'CumlRnk', ascending=False)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
67,SONACOMS,-0.46,0.86,37.91,39.09,38678.0,866.0,102025.0,804.02,-20.06,68.0,M-MC,9.00,193.0,0.02,0.72,44.33,AR,ATH,AUTO
57,RECLTD,3.79,-0.92,21.86,20.74,44004.0,-1870.0,201300.0,446.00,9.37,65.0,M-MC,6.63,191.0,-0.04,1.42,19.96,XY25,NTT,FINANCE

In [13]:
# OX40N stocks to exit
df_tmp = df_portfolio_features[(df_portfolio_features['Symbol'].isin(list_ox40n))].sort_values(by = 'Current P/L%', ascending=False)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
26,FINCABLES,3.25,15.55,79.93,107.91,136368.0,22965.0,170609.0,1641.55,4.01,63.0,M-SC,1.85,220.0,0.17,1.20,28.36,OX40N,ATH,CABLES
66,SIS,1.56,-25.76,63.34,21.26,52211.0,-28603.0,82429.0,528.00,1942.49,69.0,H-SC,12.74,168.0,-0.55,0.58,22.56,OX40N,NTT,MISC
18,CERA,-0.75,-31.23,80.15,23.89,96954.0,-54937.0,120966.0,9475.00,-33.65,66.0,H-SC,15.38,153.0,-0.57,0.85,16.25,OX40N,NTT,CERAMICS
48,KANSAINER,2.33,-32.96,69.26,13.47,125210.0,-88884.0,180783.0,340.00,-42.48,63.0,H-SC,22.34,162.0,-0.71,1.27,26.28,XY24,NTT,PAINTS
72,TATAELXSI,0.76,-34.06,100.23,32.03,87129.0,-44906.0,86929.0,9161.00,-17.51,59.0,H-SC,19.88,158.0,-0.52,0.61,15.05,OX40N,NTT,IT

In [14]:
# top 5 to book for rotation
df_tmp = df_portfolio_features[(df_portfolio_features['Current P/L%'] > 20) ].sort_values(by = 'CumlRnk', ascending=False)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
1,ABB,-1.1,24.72,16.72,45.57,54554.0,64661.0,326280.0,7934.0,-19.82,67.0,H-MC,16.34,125.0,1.19,2.3,44.89,AR,NTT,ELECTRICAL

In [15]:
# top 5 to monitor for exit
df_tmp = df_portfolio_features[~df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])]
df_tmp = df_tmp[(df_tmp['Current P/L%'] > 0) ].sort_values(by = 'Dev%_PE', ascending=False)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
26,FINCABLES,3.25,15.55,79.93,107.91,136368.0,22965.0,170609.0,1641.55,4.01,63.0,M-SC,1.85,220.0,0.17,1.20,28.36,OX40N,ATH,CABLES
1,ABB,-1.10,24.72,16.72,45.57,54554.0,64661.0,326280.0,7934.00,-19.82,67.0,H-MC,16.34,125.0,1.19,2.30,44.89,AR,NTT,ELECTRICAL
67,SONACOMS,-0.46,0.86,37.91,39.09,38678.0,866.0,102025.0,804.02,-20.06,68.0,M-MC,9.00,193.0,0.02,0.72,44.33,AR,ATH,AUTO

In [16]:
# top 5 to book for rotation from weak conviction
df_tmp = df_portfolio_features[~df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])]
df_tmp = df_tmp[~df_tmp['Criteria'].isin(['XY25','XY24','X40', 'X40N'])].sort_values(by = 'RRR Ind', ascending=False)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
1,ABB,-1.10,24.72,16.72,45.57,54554.0,64661.0,326280.0,7934.00,-19.82,67.0,H-MC,16.34,125.0,1.19,2.30,44.89,AR,NTT,ELECTRICAL
26,FINCABLES,3.25,15.55,79.93,107.91,136368.0,22965.0,170609.0,1641.55,4.01,63.0,M-SC,1.85,220.0,0.17,1.20,28.36,OX40N,ATH,CABLES
67,SONACOMS,-0.46,0.86,37.91,39.09,38678.0,866.0,102025.0,804.02,-20.06,68.0,M-MC,9.00,193.0,0.02,0.72,44.33,AR,ATH,AUTO
85,ZYDUSLIFE,0.13,-1.16,37.22,35.63,77099.0,-2431.0,207143.0,1286.17,-13.96,63.0,H-MC,5.74,120.0,-0.03,1.46,15.32,AR,ATH,PHARMA
40,INDIAMART,1.82,-7.24,122.86,106.72,140559.0,-8930.0,114406.0,4810.62,-58.20,60.0,H-SC,12.71,140.0,-0.06,0.81,9.91,AR,ATH,MISC

In [17]:
# top 5 to accumulate based on lowest RSI_14
df_tmp = df_portfolio_features[df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])].sort_values(by = 'RSI_14', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
78,UNITDSPR,-1.15,-9.06,32.79,20.77,69822.0,-21208.0,212936.0,1644.00,-19.41,42.0,X-MC,6.39,64.0,-0.30,1.50,1.58,X40N,NTT,BREWERIES
21,DABUR,-1.04,-16.17,71.43,43.70,148534.0,-40124.0,207944.0,735.00,-23.90,43.0,X-MC,14.54,70.0,-0.27,1.47,4.46,XY24,BTT,FMCG
53,PGHH,-0.52,-26.20,78.88,32.01,124296.0,-55944.0,157576.0,17616.87,-50.08,43.0,X-MC,21.63,57.0,-0.45,1.11,7.78,X40,ATH,FMCG
2,ABBOTINDIA,-0.48,-13.28,36.15,18.07,56069.0,-23755.0,155100.0,35195.00,-26.29,44.0,X-MC,11.67,58.0,-0.42,1.09,1.43,X40,ATH,PHARMA
59,RELIANCE,-0.57,-14.21,46.06,25.30,79406.0,-28567.0,172396.0,1952.00,-16.57,44.0,X-LC,5.35,21.0,-0.36,1.22,8.27,XY25,BTT,REFINERIES

In [18]:
# top 5 to accumulate based on Spread and CumlRnk
df_tmp = df_portfolio_features[df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])]
df_tmp = df_tmp[(df_tmp['CumlRnk'] < 100)].sort_values(by = 'Spread%', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
5,ANGELONE,-2.47,19.02,4.34,24.18,15754.0,58000.0,363000.0,303.00,-82.85,70.0,X-SC,1.20,97.0,3.68,2.56,38.87,X40N,NTT,FINANCE
65,SIEMENS,-0.34,-4.24,31.07,25.51,55367.0,-7895.0,178200.0,4671.50,49.61,68.0,H-LC,1.52,51.0,-0.14,1.26,26.83,AR,ATH,ELECTRICAL
24,DMART,-1.42,6.00,22.27,29.60,58921.0,14976.0,264576.0,5391.45,-10.59,64.0,X-LC,3.67,14.0,0.25,1.87,20.93,X40N,ATH,FMCG
59,RELIANCE,-0.57,-14.21,46.06,25.30,79406.0,-28567.0,172396.0,1952.00,-16.57,44.0,X-LC,5.35,21.0,-0.36,1.22,8.27,XY25,BTT,REFINERIES
78,UNITDSPR,-1.15,-9.06,32.79,20.77,69822.0,-21208.0,212936.0,1644.00,-19.41,42.0,X-MC,6.39,64.0,-0.30,1.50,1.58,X40N,NTT,BREWERIES

In [19]:
# top 5 to accumulate based on lowest Gained%
df_tmp = df_portfolio_features[df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])].sort_values(by = 'Gained%', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
2,ABBOTINDIA,-0.48,-13.28,36.15,18.07,56069.0,-23755.0,155100.0,35195.0,-26.29,44.0,X-MC,11.67,58.0,-0.42,1.09,1.43,X40,ATH,PHARMA
78,UNITDSPR,-1.15,-9.06,32.79,20.77,69822.0,-21208.0,212936.0,1644.0,-19.41,42.0,X-MC,6.39,64.0,-0.30,1.50,1.58,X40N,NTT,BREWERIES
35,HINDUNILVR,-1.03,-16.93,36.84,13.67,78664.0,-43533.0,213530.0,2922.0,-38.30,47.0,X-LC,11.91,9.0,-0.55,1.51,4.05,XY25,NTT,FMCG
21,DABUR,-1.04,-16.17,71.43,43.70,148534.0,-40124.0,207944.0,735.0,-23.90,43.0,X-MC,14.54,70.0,-0.27,1.47,4.46,XY24,BTT,FMCG
45,ITC,0.58,-19.98,48.78,19.06,132782.0,-67961.0,272205.0,452.0,-55.92,51.0,X-LC,19.37,1.0,-0.51,1.92,5.60,X40,NTT,FMCG

In [20]:
# top 5 to accumulate based on lowest CurrAlloc%
df_tmp = df_portfolio_features[df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])].sort_values(by = 'CurrAlloc%', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
58,RELAXO,-0.09,-60.53,285.84,52.31,163789.0,-87859.0,57301.0,1176.00,-57.99,56.0,X-SC,32.91,92.0,-0.54,0.40,28.12,X40N,NTT,FOOTWEAR
12,BATAINDIA,0.08,-52.20,182.84,35.20,112459.0,-67163.0,61507.0,2096.00,-19.42,59.0,X-SC,33.32,91.0,-0.60,0.43,21.98,X40,NTT,FOOTWEAR
54,QUESS,0.05,-19.91,117.14,73.90,100187.0,-21265.0,85528.0,424.00,-57.02,60.0,X-SC,20.89,80.0,-0.21,0.60,15.05,XY24,NTT,MISC
2,ABBOTINDIA,-0.48,-13.28,36.15,18.07,56069.0,-23755.0,155100.0,35195.00,-26.29,44.0,X-MC,11.67,58.0,-0.42,1.09,1.43,X40,ATH,PHARMA
53,PGHH,-0.52,-26.20,78.88,32.01,124296.0,-55944.0,157576.0,17616.87,-50.08,43.0,X-MC,21.63,57.0,-0.45,1.11,7.78,X40,ATH,FMCG

In [21]:
# top 5 to accumulate based on CumlRnk
df_tmp = df_portfolio_features.sort_values(by = 'CumlRnk', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
45,ITC,0.58,-19.98,48.78,19.06,132782.0,-67961.0,272205.0,452.00,-55.92,51.0,X-LC,19.37,1.0,-0.51,1.92,5.60,X40,NTT,FMCG
73,TCS,0.65,-24.51,67.67,26.57,236649.0,-113563.0,349710.0,4311.59,-36.09,55.0,X-LC,17.33,2.0,-0.48,2.47,9.14,X40,ATH,IT
43,INFY,0.59,-10.62,50.19,34.24,140366.0,-33219.0,279669.0,1972.00,-29.61,51.0,X-LC,13.70,3.0,-0.24,1.97,7.55,X40,NTT,IT
75,TMPV,-0.50,-18.94,68.49,36.58,197553.0,-67400.0,288441.0,600.00,-83.62,62.0,X-LC,11.25,4.0,-0.34,2.03,20.22,XY24,NTT,AUTO
33,HCLTECH,-0.32,-6.11,31.90,23.83,72455.0,-14792.0,227132.0,1908.19,-1.57,57.0,X-LC,8.57,8.0,-0.20,1.60,10.28,X40,ATH,IT

In [22]:
# top 5 for average up
df_tmp = df_portfolio_features[(df_portfolio_features['Dev%_200'] > 5)].sort_values(by = 'CurrAlloc%', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
67,SONACOMS,-0.46,0.86,37.91,39.09,38678.0,866.0,102025.0,804.02,-20.06,68.0,M-MC,9.00,193.0,0.02,0.72,44.33,AR,ATH,AUTO
69,SURYODAY,3.27,-18.08,50.19,23.03,73627.0,-32375.0,146696.0,216.00,60.09,64.0,H-SC,4.06,166.0,-0.44,1.03,25.10,XR,NTT,BANKS
26,FINCABLES,3.25,15.55,79.93,107.91,136368.0,22965.0,170609.0,1641.55,4.01,63.0,M-SC,1.85,220.0,0.17,1.20,28.36,OX40N,ATH,CABLES
65,SIEMENS,-0.34,-4.24,31.07,25.51,55367.0,-7895.0,178200.0,4671.50,49.61,68.0,H-LC,1.52,51.0,-0.14,1.26,26.83,AR,ATH,ELECTRICAL
11,BANDHANBNK,0.13,-16.30,129.89,92.42,302852.0,-45399.0,233160.0,400.00,99.71,60.0,H-SC,4.99,174.0,-0.15,1.64,28.44,XY24,NTT,BANKS

In [23]:
# top 5 RSP
df_tmp = df_portfolio_features.sort_values(by = 'RSP', ascending=False)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
80,VALIANTORG,8.90,-39.66,188.60,74.15,186197.0,-64879.0,98726.0,838.00,-277.79,67.0,H-SC,19.88,145.0,-0.35,0.70,46.92,XR,NTT,CHEMICALS
5,ANGELONE,-2.47,19.02,4.34,24.18,15754.0,58000.0,363000.0,303.00,-82.85,70.0,X-SC,1.20,97.0,3.68,2.56,38.87,X40N,NTT,FINANCE
52,PAGEIND,0.40,-4.34,40.20,34.11,103203.0,-11654.0,256725.0,51418.64,-31.42,73.0,X-MC,15.75,55.0,-0.11,1.81,21.44,X40,ATH,APPARELS
55,RAJESHEXPO,5.00,-75.46,307.71,0.07,103600.0,-103509.0,33668.0,518.00,1133.59,64.0,L-SC,43.08,268.0,-1.00,0.24,58.06,OX40N,NTT,JEWELLERY
67,SONACOMS,-0.46,0.86,37.91,39.09,38678.0,866.0,102025.0,804.02,-20.06,68.0,M-MC,9.00,193.0,0.02,0.72,44.33,AR,ATH,AUTO

In [24]:
# Top N allocation
df_tmp = df_portfolio_features.sort_values(by = 'CurrAlloc%', ascending=False)
top_n_values = [10, 25, 50]

sum_df = pd.DataFrame({
    'Top_N': top_n_values,
    'Sum_Alloc%': [df_tmp['CurrAlloc%'].head(n).sum() for n in top_n_values]
})

sum_df

   Top_N  Sum_Alloc%
0     10       20.97
1     25       45.60
2     50       77.57

In [25]:
# market-cap-wise allocation
df_tmp = df_portfolio_features[cols]
df_tmp.groupby(df_tmp['Conviction'].str[-2:])['CurrAlloc%'].sum().sort_values(ascending=False)

Conviction
SC    45.42
MC    29.39
LC    25.15
Name: CurrAlloc%, dtype: float64

In [26]:
# criteria-wise allocation
df_portfolio_features.groupby('Criteria')['CurrAlloc%'].sum().sort_values(ascending=False)

Criteria
XY24     27.28
X40      24.59
X40N     15.66
AR        9.30
XR        8.48
XY25      7.03
OX40N     6.83
SR        0.79
Name: CurrAlloc%, dtype: float64

In [27]:
# conviction-wise allocation
df_portfolio_features.groupby('Conviction')['CurrAlloc%'].sum().sort_values(ascending=False)

Conviction
X-LC    22.86
H-SC    22.22
X-MC    21.88
X-SC    12.42
M-SC    10.16
H-MC     5.03
M-MC     2.14
H-LC     1.26
M-LC     1.03
L-SC     0.62
L-MC     0.34
Name: CurrAlloc%, dtype: float64

In [28]:
# sector-wise stats
df_tmp = df_portfolio_features.groupby('Category')[['CurrAlloc%', 'Current', 'Current P/L', 'FTT Amt']].sum().sort_values(by=['Current', 'Current P/L'], ascending=False)
df_tmp['Current P/L%'] = round(df_tmp['Current P/L'] * 100 / df_tmp['Current'], 2)
df_tmp['FTT%'] = round(df_tmp['FTT Amt'] * 100 / df_tmp['Current'], 2)
cols = ['CurrAlloc%', 'Current P/L%', 'FTT%']
df_tmp[cols].sort_values(by=['CurrAlloc%'], ascending=False)

               CurrAlloc%  Current P/L%    FTT%
Category
FMCG                14.55        -21.12   64.10
FINANCE             13.50        -12.18   57.90
IT                  11.71        -35.48  104.43
MISC                 7.18        -31.56   88.71
ELECTRICAL           6.58         -3.87   43.64
PAINTS               5.33        -30.25   52.88
BANKS                4.60        -17.81   77.62
INSURANCE            4.60         -4.20   39.86
PHARMA               3.91         -5.89   39.22
AUTO                 3.87        -19.07   66.31
AC                   1.99        -13.16   43.85
HEALTHCARE           1.94        -29.80   63.67
FOOTWEAR             1.84        -68.98  136.73
TRAVEL               1.82        -73.35  160.15
APPARELS             1.81         -4.54   40.20
DURABLES             1.74        -56.92   95.09
BREWERIES            1.50         -9.96   32.79
REALTY               1.44         -8.57   26.41
CERAMICS             1.35        -60.21  108.88
CEMENT               1.22        -55.49  171.82
REFINERIES           1.22        -16.57   46.06
CABLES               1.20         13.46   79.93
ENGINEERING          1.18        -44.38  110.41
CHEMICALS            1.13        -65.41  200.36
JEWELLERY            1.12       -102.10  172.32
ENTERTAINMENT        0.80        -69.31  170.29
TEXTILES             0.45        -44.54   85.76
HOTELS               0.38       -112.35  187.25

In [29]:
# money to be made criteria-wise
df_portfolio_features.groupby('Criteria')['FTT Amt'].agg(['sum', 'count']).sort_values(by='sum', ascending=False)

                sum  count
Criteria
XY24      3726289.0     21
X40       1687657.0     16
XR        1288830.0     12
AR        1251691.0     10
X40N      1077915.0     10
OX40N      822696.0     10
XY25       444647.0      5
SR         306720.0      2

In [30]:
# money to be made conviction-wise
df_portfolio_features.groupby('Conviction')['FTT Amt'].agg(['sum', 'count']).sort_values(by='sum', ascending=False)

                  sum  count
Conviction
H-SC        3637749.0     24
X-MC        1630468.0     15
X-LC        1535203.0     13
M-SC        1477233.0     14
X-SC        1418727.0     10
H-MC         365364.0      3
L-SC         203726.0      2
M-LC         145781.0      1
M-MC          82682.0      2
H-LC          55367.0      1
L-MC          54145.0      1

In [31]:
# money to be made criteria and conviction-wise
df_portfolio_features.groupby(['Conviction', 'Criteria'])['FTT Amt'].agg(['sum', 'count']).sort_values(by='sum', ascending=False)

                           sum  count
Conviction Criteria
H-SC       XY24      1223835.0      6
           AR         951752.0      5
M-SC       XY24       850560.0      6
X-LC       X40        836386.0      7
X-SC       XY24       827800.0      4
H-SC       XR         802755.0      7
X-MC       X40        645059.0      7
           X40N       495729.0      4
X-SC       X40N       384715.0      4
M-SC       OX40N      366409.0      5
H-SC       OX40N      352687.0      4
X-LC       XY24       343276.0      2
H-SC       SR         306720.0      2
X-MC       XY24       247107.0      2
           XY25       242573.0      2
H-MC       XY24       233711.0      1
X-SC       X40        206212.0      2
X-LC       X40N       197471.0      2
M-SC       XR         186023.0      2
X-LC       XY25       158070.0      2
M-LC       XR         145781.0      1
H-MC       AR         131653.0      2
L-SC       OX40N      103600.0      1
           XR         100126.0      1
M-SC       AR          74241.0      1
H-LC       AR          55367.0      1
L-MC       XR          54145.0      1
M-MC       XY25        44004.0      1
           AR          38678.0      1

In [32]:
# notebook execution time

end_time = time.time()
execution_time = round(end_time - start_time, 0)
print(f"Notebook execution time: {execution_time} seconds")

Notebook execution time: 27.0 seconds