<a href="https://colab.research.google.com/github/ankit-rathi/Quantvesting_v2/blob/main/myStocks_Portfolio_Analysis.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
'''
!pip install pandas==2.2.2 -qq
!pip install pyxirr -qq
!pip install ta -qq
!pip install yfinance==0.2.59 -qq
'''

'\n!pip install pandas==2.2.2 -qq\n!pip install pyxirr -qq\n!pip install ta -qq\n!pip install yfinance==0.2.59 -qq\n'

In [2]:
# import libraries

import numpy as np
import pandas as pd
import datetime
import warnings
warnings.filterwarnings('ignore')
import yfinance as yfin
import ta
import matplotlib.pyplot as plt
import requests

In [3]:
# notebook start time
import time
import datetime
import pytz

start_time = time.time()

# function to print date timestamp
def print_date_time():
  tz_NY = pytz.timezone('Asia/Kolkata')
  datetime_NY = datetime.datetime.now(tz_NY)
  print("Run date time (IST):", datetime_NY.strftime("%Y-%m-%d %H:%M:%S"))

In [4]:
# function to get booked and reserved amount
def get_amt():
  # fetch the JSON data from the URL
  url = "https://raw.githubusercontent.com/ankit-rathi/Tradevesting_v1/main/data/myPortfolioAmts.json"
  response = requests.get(url)
  pf_amts = response.json()  # parse the JSON data

  # extract values from the JSON
  py_booked_amt_dm = pf_amts["py_booked_amt_dm"]
  py_booked_amt_sv = pf_amts["py_booked_amt_sv"]
  cy_booked_amt_dm = pf_amts["cy_booked_amt_dm"]
  cy_booked_amt_sv = pf_amts["cy_booked_amt_sv"]
  reserve_amt_dm = pf_amts["reserve_amt_dm"]
  reserve_amt_sv = pf_amts["reserve_amt_sv"]

  # perform calculations
  py_booked_amt = py_booked_amt_dm + py_booked_amt_sv
  cy_booked_amt = cy_booked_amt_dm + cy_booked_amt_sv
  reserve_amt = reserve_amt_dm + reserve_amt_sv
  total_booked_amt = py_booked_amt + cy_booked_amt

  return total_booked_amt, reserve_amt, cy_booked_amt, py_booked_amt

gen_output = 0

In [5]:
# function to format the amount
def format_amt(number):
    abs_number = abs(number)

    if abs_number >= 1_00_00_000:  # Crores
        formatted_amt = f"{number / 1_00_00_000:.2f} C"
    elif abs_number >= 1_00_000:  # Lakhs
        formatted_amt = f"{number / 1_00_000:.2f} L"
    elif abs_number >= 1_000:  # Thousands
        formatted_amt = f"{number / 1_000:.2f} K"
    else:
        formatted_amt = f"{number:.2f}"

    return formatted_amt

# function to set start and end date
def get_start_end_date():
  start_date = (datetime.date.today() + datetime.timedelta(days=-365)).strftime('%Y-%m-%d')
  end_date = (datetime.date.today() + datetime.timedelta(days=1)).strftime('%Y-%m-%d')
  return start_date, end_date

# function to fetch my portfolio csv
def get_mypfs_df():
  mypfs_df = pd.read_csv('https://raw.githubusercontent.com/ankit-rathi/Tradevesting_v1/main/data/myPortfolioStocks.csv')
  return mypfs_df

# function to fetch my prospects csv
def get_mypps_df():
  mypps_df = pd.read_csv('https://raw.githubusercontent.com/ankit-rathi/Tradevesting_v1/main/data/myProspectsScrips.csv')
  return mypps_df

# function to fetch screener data
def get_myscreen_df():
  myscreen_df = pd.read_csv('https://raw.githubusercontent.com/ankit-rathi/Tradevesting_v1/main/data/myScreenerDB.csv')
  return myscreen_df

# function to fetch momentum data
def get_myinvmt_df():
  myinvmt_df = pd.read_csv('https://raw.githubusercontent.com/ankit-rathi/Tradevesting_v1/main/data/myInvestments.csv')
  return myinvmt_df

# function to get the stock ids
def get_stock_ids(df_pf):
  stock_n100 = df_pf['Symbol'].unique()

  exclude = ['CADILAHC','MMTC', 'MASFIN']

  stock_ids = df_pf[~df_pf['Symbol'].isin(exclude) ]['Symbol'].unique()

  #mypf = mypf[mypf.Forecast.notnull()]
  #stock_ids = mypf['Symbol'].unique()

  #stock_ids.sort()
  return stock_ids

# get features from screener data
def get_screener_features():
  myscreen_df = get_myscreen_df()
  cols = ['Symbol', 'EPS', 'MedPE', 'ROCE%', 'ROE%', 'CapType']
  return myscreen_df[cols]

# get relative strength
def get_relative_strength(stock_list):

    # Dictionary to store stock tickers and their corresponding percentage price change
    stock_changes = {}

    # Loop through each stock and fetch its price data
    for stock in stock_list:
        try:
            # Download the stock data for the given date range
            stock_data = yfin.Ticker(stock + '.NS').history(period='1mo', interval='1d')[map(str.title, ['open', 'close', 'low', 'high', 'volume'])]

            # Calculate the percentage change for the stock
            if len(stock_data) > 0:
                start_price = stock_data['Close'].iloc[0]
                end_price = stock_data['Close'].iloc[-1]
                percent_change = round(((end_price - start_price) / start_price) * 100, 2)
                stock_changes[stock] = percent_change
            else:
                stock_changes[stock] = np.nan  # If no data is available, set to NaN

        except Exception as e:
            print(f"Error fetching data for {stock}: {e}")
            stock_changes[stock] = np.nan

    # Create a DataFrame with stock tickers and their percentage changes
    df = pd.DataFrame(list(stock_changes.items()), columns=['Symbol', 'Percent_Change'])

    # Drop any stocks with missing data (NaN values)
    df = df.dropna()

    # Calculate the percentile rank based on percentage change
    df['RSP'] = round(df['Percent_Change'].rank(pct=True) * 100, 2)
    cols = ['Symbol', 'RSP']
    df = df[cols]
    # Sort by percentile rank (optional)
    df = df.sort_values(by='RSP', ascending=False).reset_index(drop=True)

    return df

In [6]:
# function to get stock technicals
def stock_prec_dev(stock_symbol):
    #stock_symbol = 'ULTRACEMCO.NS'
    short_window = 20
    mid_window = 50
    long_window = 200
    moving_avg = 'SMA'

    start = datetime.datetime(*map(int, start_date.split('-')))
    end = datetime.datetime(*map(int, end_date.split('-')))

    stock_df = yfin.Ticker(stock_symbol + '.NS').history(period='max', interval='1d')[map(str.title, ['open', 'close', 'low', 'high', 'volume'])]

    stock_df['Max'] = round(max(stock_df['Close']),2)
    stock_df = stock_df[(stock_df.index <= end_date) & (stock_df.index >= start_date)]
    stock_df['200_SMA'] = round(stock_df['Close'].rolling(window = 200, min_periods = 1).mean(),0)
    stock_df['Dev%_200'] = round((stock_df['Close'] - stock_df['200_SMA'])*100/stock_df['200_SMA'],2)
    stock_df.dropna(axis = 0, inplace = True) # remove any null rows

    stock_df['20_SMA'] = stock_df['Close'].rolling(window=20).mean()
    stock_df['50_SMA'] = stock_df['Close'].rolling(window=50).mean()
    stock_df['Symbol'] = stock_symbol

    stock_df['Close'] = round(stock_df['Close'],2)
    stock_df['Min'] = round(min(stock_df['Close']),2)
    stock_df['RSI_14'] = ta.momentum.RSIIndicator(close=stock_df['Close'], window=14).rsi()
    stock_df['RSI_14'] = round(stock_df['RSI_14'],0)
    stock_df['Prev_Close'] = stock_df['Close'].shift(1)
    stock_df.drop(['Open', 'Low', 'High', 'Volume'], axis=1, inplace=True)
    stock_df = stock_df.tail(1)

    max_SMA = max(stock_df['20_SMA'].item(), stock_df['50_SMA'].item(), stock_df['200_SMA'].item())
    min_SMA = min(stock_df['20_SMA'].item(), stock_df['50_SMA'].item(), stock_df['200_SMA'].item())
    ABS_Spread = max_SMA - min_SMA
    stock_df['Spread%'] = round((ABS_Spread / stock_df['200_SMA'].item()) * 100,2)

    return stock_df

# function to compute stock attributes
def get_common_features(stock_ids, df_mypf):

  df_prec_dev = pd.DataFrame()
  df_tmp = get_screener_features()
  df_rs = get_relative_strength(stock_ids)

  for stock_id in stock_ids:
      tmp = stock_prec_dev(stock_id)
      tmp = tmp.reset_index()
      df_prec_dev = pd.concat([df_prec_dev, tmp], ignore_index = True)
  df_prec_dev = pd.merge(df_prec_dev, df_mypf, on= 'Symbol')
  df_prec_dev = pd.merge(df_prec_dev, df_tmp, on= 'Symbol', how='left')
  df_prec_dev = pd.merge(df_prec_dev, df_rs, on= 'Symbol', how='left')
  #print(df_prec_dev.columns)
  df_prec_dev['Curr_PE'] = round(df_prec_dev['Close']/df_prec_dev['EPS'],1)
  df_prec_dev['Dev%_PE'] = round((df_prec_dev['Curr_PE'] - df_prec_dev['MedPE'])*100/df_prec_dev['MedPE'],2)
  df_prec_dev['Conviction'] = df_prec_dev['Conviction'] + '-' + df_prec_dev['CapType']
  return df_prec_dev

# function to arrange stock features
def arrange_features(df_stocks, common_cols, diff_cols):
  df_stocks_common = df_stocks[common_cols].drop_duplicates()
  df_stocks_diff = df_stocks[diff_cols]
  df_stocks_diff['Investment'] = df_stocks_diff['AvgCost'] * df_stocks_diff['Shares']
  df_stocks_diff = df_stocks_diff.groupby(['Symbol'])[['Shares', 'Investment']].aggregate(['sum']).reset_index()
  df_stocks_diff.columns = ['Symbol', 'Shares', 'Investment']
  df_stocks_diff['AvgCost'] = round(df_stocks_diff['Investment']/df_stocks_diff['Shares'],2)
  df_stocks = pd.merge(df_stocks_diff, df_stocks_common, on='Symbol')
  return df_stocks

# plot fact distribution across dimension
def plot_pie_chart(df, dimension, fact):
  # grouping the data by category and calculating the sum of fact for each type
  grouped_data = df.groupby(dimension)[fact].sum()

  # sorting the grouped data in descending order
  grouped_data = grouped_data.sort_values(ascending=False)

  # creating a pie chart
  grouped_data.plot.pie(autopct='%1.1f%%', startangle=90, figsize=(6, 6))

  # adding a title and displaying the plot
  plt.title(f'{dimension} {fact} Distribution')
  plt.ylabel('')  # To hide the y-label
  plt.show()

In [7]:
# function to get portfolio features

def get_portfolio_features(df_common_features):

  print_date_time()
  print('-------------------')

  #df_common_features["Target"] = df_common_features["Target"].fillna(df_common_features["Max"])
  df_common_features['NTT'] = np.where(df_common_features['Strategy']== 'NTT', df_common_features["Target"], df_common_features['Max'])
  df_common_features['LTT'] = np.where(df_common_features['Strategy']== 'BTT', df_common_features["Target"], df_common_features['Max'])
  df_common_features['BOL'] = df_common_features['Min']

  tmp_df = df_common_features[df_common_features['Symbol'].isin(mypf_df[mypf_df['InPortfolio'] != 'NA'].Symbol.values)]
  print('qualified stocks: '+str(len(tmp_df['Symbol'].unique())))
  tmp_df1 = tmp_df[tmp_df['LatestQtr'] == 1]
  print('with latest results: '+str(len(tmp_df1['Symbol'].unique())))
  tmp_df1 = tmp_df1[tmp_df1['StarStock'] == 1]
  print('still star stocks: '+str(len(tmp_df1['Symbol'].unique())))
  tmp_df['Investment'] = tmp_df['AvgCost'] * tmp_df['Shares']
  tmp_df['Current'] = round(tmp_df['Close'] * tmp_df['Shares'],0)
  tmp_df['Previous'] = tmp_df['Prev_Close'] * tmp_df['Shares']
  tmp_df['EstimatedST'] = tmp_df['NTT'] * tmp_df['Shares']
  tmp_df['EstimatedLT'] = tmp_df['LTT'] * tmp_df['Shares']
  tmp_df['Current P/L'] = round((tmp_df['Current'] - tmp_df['Investment']),0)
  tmp_df['Today P/L%'] = round((tmp_df['Current'] - tmp_df['Previous'])*100/tmp_df['Previous'],2)
  tmp_df['Current P/L%'] = round((tmp_df['Current'] - tmp_df['Investment'])*100/tmp_df['Investment'],2)
  tmp_df['EstimatedST P/L%'] = round((tmp_df['EstimatedST'] - tmp_df['Investment'])*100/tmp_df['Investment'],2)
  tmp_df['EstimatedLT P/L%'] = round((tmp_df['EstimatedLT'] - tmp_df['Investment'])*100/tmp_df['Investment'],2)
  tmp_df['NTT%'] = round((tmp_df['NTT'] - tmp_df['Close'])*100/tmp_df['Close'],2)
  tmp_df['LTT%'] = round((tmp_df['LTT'] - tmp_df['Close'])*100/tmp_df['Close'],2)
  tmp_df['Gained%'] = round((tmp_df['Close'] - tmp_df['BOL'])*100/tmp_df['BOL'],2)
  investment = round(sum(tmp_df['AvgCost']*tmp_df['Shares']),0)
  current = round(sum(tmp_df['Close']*tmp_df['Shares']),0)
  tmp_df['InitAlloc%'] = round(tmp_df['Investment']*100/investment,2)
  tmp_df['CurrAlloc%'] = round(tmp_df['Current']*100/current,2)
  tmp_df['FTT'] = tmp_df['LTT']
  tmp_df.loc[tmp_df['Strategy'] == 'NTT', 'FTT'] = tmp_df['NTT']
  tmp_df['FTT%'] = tmp_df['LTT%']
  tmp_df.loc[tmp_df['Strategy'] == 'NTT', 'FTT%'] = tmp_df['NTT%']
  tmp_df['FTT Amt'] = round(tmp_df['FTT%'] * tmp_df['Current']/100,0)
  tmp_df['OTT%'] = round((tmp_df['FTT'] - tmp_df['AvgCost'])*100/tmp_df['AvgCost'],2)
  tmp_df['RRR Ind'] = round(tmp_df['Current P/L']/tmp_df['FTT Amt'],2)
  tmp_df['Risk Ind'] = round(tmp_df['Current P/L%']*tmp_df['CurrAlloc%'],0)

  return tmp_df

# function to print portfolio features
def print_portfolio_stats(df_portfolio_features, myinvmt_df):
  from pyxirr import xirr

  total_booked_amt, reserve_amt, cy_booked_amt, py_booked_amt = get_amt()

  dates = myinvmt_df['Date'].values
  dates = np.append(dates, datetime.date.today().strftime('%d-%b-%y'))
  investment = myinvmt_df['Investment'].values
  dates= pd.to_datetime(dates)

  current = round(sum(df_portfolio_features['Close']*df_portfolio_features['Shares']),0) + reserve_amt
  investment_xirr = np.append(investment, current)
  cagr = round(xirr(pd.DataFrame({"dates": dates, "amounts": investment_xirr}))*100,2)

  investment = -sum(investment)
  invested = round(sum(df_portfolio_features['AvgCost']*df_portfolio_features['Shares']),0) + reserve_amt
  previous = round(sum(df_portfolio_features['Prev_Close']*df_portfolio_features['Shares']),0) + reserve_amt
  cy_invested = investment + py_booked_amt

  today_pnl_amount = current-previous
  today_pnl_percentage = round((current-previous)*100/previous,2)

  curr_pnl_amount = current-invested
  curr_pnl_percentage = round((curr_pnl_amount)*100/(cy_invested),2)

  cy_pnl_amount = cy_booked_amt + curr_pnl_amount
  cy_pnl_percentage = round((cy_pnl_amount)*100/cy_invested,2)

  overall_pnl_amount = total_booked_amt + curr_pnl_amount
  overall_pnl_percentage = round((overall_pnl_amount)*100/investment,2)

  estimate_st = round(sum(df_portfolio_features['FTT']*df_portfolio_features['Shares']),0)  + reserve_amt
  est_st_pnl_amount = estimate_st-current
  est_st_pnl_percentage = round((est_st_pnl_amount)*100/current,2)

  estimate_lt = round(sum(df_portfolio_features['LTT']*df_portfolio_features['Shares']),0)  + reserve_amt
  est_lt_pnl_amount = estimate_lt-current
  est_lt_pnl_percentage = round((est_lt_pnl_amount)*100/current,2)

  total_profit = round(sum(df_portfolio_features[df_portfolio_features['Current P/L%'] > 0]['Current']) - sum(df_portfolio_features[df_portfolio_features['Current P/L%'] > 0]['Investment']),0)
  total_loss = round(sum(df_portfolio_features[df_portfolio_features['Current P/L%'] < 0]['Current']) - sum(df_portfolio_features[df_portfolio_features['Current P/L%'] < 0]['Investment']),0)

  cy_booked_percentage = round((cy_booked_amt)*100/current,2)
  py_booked_percentage = round((py_booked_amt)*100/investment,2)
  total_booked_percentage = round((total_booked_amt)*100/investment,2)

  print('-------------------')
  print('Initial Investment: ', format_amt(investment))
  print('CY Investment: ', format_amt(cy_invested))
  print('Reserve: ', format_amt(reserve_amt))
  print('Current: ',  format_amt(current))
  print('-------------------')
  print('Today PnL: '+ '{} ({}%)'.format(format_amt(today_pnl_amount), today_pnl_percentage))
  print('Current PnL: '+ '{} ({}%)'.format(format_amt(curr_pnl_amount), curr_pnl_percentage))
  print('CY Booked + Current PnL: '+ '{} ({}%)'.format(format_amt(cy_pnl_amount), cy_pnl_percentage))
  print('-------------------')
  print('Total profit: ', format_amt(total_profit))
  print('Total loss: ', format_amt(total_loss))
  print('-------------------')
  print('Total Booked + Current PnL: '+ '{} ({}%)'.format(format_amt(overall_pnl_amount), overall_pnl_percentage))
  print('Total Booked PnL: '+ '{} ({}%)'.format(format_amt(total_booked_amt), total_booked_percentage))
  print('Curr Year Booked PnL: '+ '{} ({}%)'.format(format_amt(cy_booked_amt), cy_booked_percentage))
  print('Prev Year Booked PnL: '+ '{} ({}%)'.format(format_amt(py_booked_amt), py_booked_percentage))
  print('===================')
  print('Est FTT: ',  format_amt(estimate_st))
  print('Est FTT PnL: '+ '{} ({}%)'.format(format_amt(est_st_pnl_amount), est_st_pnl_percentage))

  print('===================')
  print('Deployed: ', format_amt(investment))

  print('Current: ', format_amt(current))

  print('CAGR/XIRR %: '+'{}%'.format(cagr))

In [8]:
# get start and end date
start_date, end_date = get_start_end_date()

# get portfolio and prospects data
mypfs_df = get_mypfs_df()
mypps_df = get_mypps_df()
myinvmt_df = get_myinvmt_df()

# merge above datasets
mypf_df = pd.merge(mypfs_df, mypps_df, on="Symbol")

# seggregate dm and sv portfolio
dm_pf = mypf_df[mypf_df['InPortfolio'] == 'DM']
sv_pf = mypf_df[mypf_df['InPortfolio'] == 'SV']

# build portfolio stock dataframe
dm_stocks = get_stock_ids(dm_pf)
sv_stocks = get_stock_ids(sv_pf)
df_stocks = pd.concat([dm_pf,sv_pf], ignore_index = True)

# arrange common and diff stock features
common_cols = ['Symbol', 'Target', 'Criteria', 'Strategy', 'CumlRnk', 'LatestQtr', 'StarStock', 'Conviction', 'Category', 'InFolio', 'XIRR', 'MBQ']
diff_cols = ['Symbol', 'AvgCost', 'Shares']
df_stocks = arrange_features(df_stocks, common_cols, diff_cols)

# get common features
stock_ids = df_stocks['Symbol'].values
df_common_features = get_common_features(stock_ids, df_stocks)

df_common_features.reset_index(drop=True, inplace=True)
df_common_features.drop(['Date'], axis=1, inplace=True)
# get and print portfolio features
df_portfolio_features = get_portfolio_features(df_common_features)

print_portfolio_stats(df_portfolio_features, myinvmt_df)

df = df_portfolio_features
#plot_pie_chart(df, 'CapType', 'Current')
list_ox40n = list(df[df['MBQ'].str.contains('OX40N', na=False)]['Symbol'].values)

Run date time (IST): 2026-08-05 13:20:04
-------------------
qualified stocks: 88
with latest results: 30
still star stocks: 19
-------------------
Initial Investment:  1.46 C
CY Investment:  1.89 C
Reserve:  2.24 L
Current:  1.62 C
-------------------
Today PnL: 431.00 (0.0%)
Current PnL: -29.62 L (-15.68%)
CY Booked + Current PnL: -25.40 L (-13.45%)
-------------------
Total profit:  3.91 L
Total loss:  -33.53 L
-------------------
Total Booked + Current PnL: 17.47 L (11.96%)
Total Booked PnL: 47.09 L (32.24%)
Curr Year Booked PnL: 4.22 L (2.6%)
Prev Year Booked PnL: 42.87 L (29.35%)
===================
Est FTT:  2.67 C
Est FTT PnL: 1.04 C (64.16%)
===================
Deployed:  1.46 C
Current:  1.62 C
CAGR/XIRR %: 4.93%

In [9]:
# top 5 near their targets
cols = ['Symbol', 'Today P/L%', 'Current P/L%', 'FTT%', 'OTT%', 'FTT Amt', 'Current P/L', 'Current', 'FTT', 'Dev%_PE', 'RSI_14','Conviction', 'Spread%',  'CumlRnk', 'RRR Ind', 'CurrAlloc%', 'Gained%', 'Criteria', 'Strategy', 'Category']
df_tmp = df_portfolio_features[~df_portfolio_features['Symbol'].isin(['ENRIN','BLUSPRING','DIGITIDE'])]
df_tmp = df_tmp.sort_values(by = 'FTT Amt', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
55,MEDANTA,-1.75,20.62,5.39,27.12,11476.0,36393.0,212910.0,1486.00,16.84,60.0,X-SC,14.57,87.0,3.17,1.33,46.71,XY24,NTT,HEALTHCARE
80,UNITDSPR,0.48,12.56,7.29,20.77,19213.0,29412.0,263556.0,1644.00,-0.15,73.0,X-MC,6.74,64.0,1.53,1.64,26.69,X40N,NTT,BREWERIES
79,TTKPRESTIG,-1.34,-19.10,23.72,0.09,19338.0,-19249.0,81528.0,770.00,89.33,47.0,M-SC,13.70,250.0,-1.00,0.51,46.74,OX40N,NTT,DURABLES
52,M&M,1.17,9.68,8.34,18.82,22015.0,23290.0,263971.0,3762.88,-4.35,71.0,X-LC,6.21,25.0,1.06,1.65,19.74,X40N,ATH,AUTO
69,SIS,1.35,-1.05,22.55,21.26,24775.0,-1165.0,109867.0,528.00,2622.28,51.0,H-SC,23.22,168.0,-0.05,0.69,63.36,OX40N,NTT,MISC

In [10]:
# top 5 today
df_tmp = df_portfolio_features.sort_values(by = 'Today P/L%', ascending=False)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
51,LAOPALA,6.43,-40.08,132.14,39.09,103800.0,-52552.0,78553.0,464.00,72.04,71.0,H-SC,6.39,154.0,-0.51,0.49,21.88,AR,NTT,CERAMICS
18,COFFEEDAY,6.12,-42.53,135.36,35.27,88337.0,-48288.0,65261.0,80.00,-55.73,66.0,L-SC,5.49,266.0,-0.55,0.41,60.94,XR,NTT,HOTELS
49,KANSAINER,5.64,-29.87,61.80,13.47,116880.0,-80541.0,189126.0,340.00,-39.78,57.0,H-SC,5.90,162.0,-0.69,1.18,33.68,XY24,NTT,PAINTS
5,ATULAUTO,4.65,0.68,44.58,45.57,88480.0,1343.0,198475.0,844.00,4321.62,78.0,M-SC,7.72,248.0,0.02,1.24,52.73,XY24,NTT,AUTO
30,HAPPSTMNDS,4.48,-49.38,261.66,83.08,169765.0,-63285.0,64880.0,1466.54,-39.74,67.0,H-SC,10.92,152.0,-0.37,0.40,21.52,AR,ATH,IT

In [11]:
# bottom 5 today
df_tmp = df_portfolio_features.sort_values(by = 'Today P/L%', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
81,VAIBHAVGBL,-6.29,-23.16,109.24,60.77,153412.0,-42339.0,140436.0,521.00,61.98,47.0,H-SC,11.67,160.0,-0.28,0.88,42.88,XR,NTT,JEWELLERY
54,MASFIN,-3.13,-5.79,29.03,21.57,26798.0,-5670.0,92310.0,397.04,-18.70,43.0,H-SC,1.42,167.0,-0.21,0.58,10.03,XR,ATH,FINANCE
19,COLPAL,-2.68,-23.25,82.22,39.86,166200.0,-61225.0,202140.0,3683.41,-7.20,43.0,X-MC,1.69,62.0,-0.37,1.26,14.34,XY25,ATH,FMCG
72,SYMPHONY,-2.57,-49.86,99.39,-0.03,85282.0,-85336.0,85805.0,1306.00,-59.75,35.0,M-SC,14.04,205.0,-1.00,0.54,0.00,OX40N,NTT,DURABLES
60,RAJOOENG,-2.38,-50.05,179.49,39.61,91899.0,-51300.0,51200.0,143.10,-66.21,43.0,H-SC,17.61,136.0,-0.56,0.32,9.68,AR,ATH,MISC

In [12]:
# top 5 to exit based on CumlRnk
df_tmp = df_portfolio_features[~df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])]
df_tmp = df_tmp[(df_tmp['Current P/L%'] > -1) & (df_tmp['Current P/L%'] < 1)].sort_values(by = 'CumlRnk', ascending=False)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
5,ATULAUTO,4.65,0.68,44.58,45.57,88480.0,1343.0,198475.0,844.0,4321.62,78.0,M-SC,7.72,248.0,0.02,1.24,52.73,XY24,NTT,AUTO

In [13]:
# OX40N stocks to exit
df_tmp = df_portfolio_features[(df_portfolio_features['Symbol'].isin(list_ox40n))].sort_values(by = 'Current P/L%', ascending=False)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
25,FINCABLES,1.28,27.42,63.18,107.91,118855.0,40478.0,188122.0,1641.55,14.66,46.0,M-SC,18.08,220.0,0.34,1.17,41.53,OX40N,ATH,CABLES
69,SIS,1.35,-1.05,22.55,21.26,24775.0,-1165.0,109867.0,528.00,2622.28,51.0,H-SC,23.22,168.0,-0.05,0.69,63.36,OX40N,NTT,MISC
16,CERA,-0.29,-17.85,50.80,23.89,73411.0,-31394.0,144509.0,9475.00,-20.76,56.0,H-SC,13.02,153.0,-0.43,0.90,40.48,OX40N,NTT,CERAMICS
79,TTKPRESTIG,-1.34,-19.10,23.72,0.09,19338.0,-19249.0,81528.0,770.00,89.33,47.0,M-SC,13.70,250.0,-1.00,0.51,46.74,OX40N,NTT,DURABLES
43,INDIGOPNTS,0.17,-22.50,29.06,0.02,39314.0,-39275.0,135284.0,1408.00,106.47,57.0,M-SC,4.37,222.0,-1.00,0.84,53.49,OX40N,NTT,PAINTS

In [14]:
# top 5 to book for rotation
df_tmp = df_portfolio_features[(df_portfolio_features['Current P/L%'] > 20) ].sort_values(by = 'CumlRnk', ascending=False)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
25,FINCABLES,1.28,27.42,63.18,107.91,118855.0,40478.0,188122.0,1641.55,14.66,46.0,M-SC,18.08,220.0,0.34,1.17,41.53,OX40N,ATH,CABLES
55,MEDANTA,-1.75,20.62,5.39,27.12,11476.0,36393.0,212910.0,1486.00,16.84,60.0,X-SC,14.57,87.0,3.17,1.33,46.71,XY24,NTT,HEALTHCARE
58,QUESS,-1.33,30.73,33.02,73.90,46100.0,32819.0,139612.0,424.00,-29.48,62.0,X-SC,38.58,80.0,0.71,0.87,90.32,XY24,NTT,MISC

In [15]:
# top 5 to monitor for exit
df_tmp = df_portfolio_features[~df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])]
df_tmp = df_tmp[(df_tmp['Current P/L%'] > 0) ].sort_values(by = 'Dev%_PE', ascending=False)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
5,ATULAUTO,4.65,0.68,44.58,45.57,88480.0,1343.0,198475.0,844.00,4321.62,78.0,M-SC,7.72,248.0,0.02,1.24,52.73,XY24,NTT,AUTO
70,STARHEALTH,-0.65,13.93,29.26,47.26,93714.0,39157.0,320280.0,761.00,79.88,52.0,H-SC,18.44,173.0,0.42,2.00,38.48,XY24,NTT,INSURANCE
25,FINCABLES,1.28,27.42,63.18,107.91,118855.0,40478.0,188122.0,1641.55,14.66,46.0,M-SC,18.08,220.0,0.34,1.17,41.53,OX40N,ATH,CABLES
87,ZYDUSLIFE,-1.54,17.33,15.50,35.51,38112.0,36311.0,245885.0,1285.01,2.25,48.0,H-MC,16.11,120.0,0.95,1.53,29.40,AR,ATH,PHARMA

In [16]:
# top 5 to book for rotation from weak conviction
df_tmp = df_portfolio_features[~df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])]
df_tmp = df_tmp[~df_tmp['Criteria'].isin(['XY25','XY24','X40', 'X40N'])].sort_values(by = 'RRR Ind', ascending=False)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
87,ZYDUSLIFE,-1.54,17.33,15.50,35.51,38112.0,36311.0,245885.0,1285.01,2.25,48.0,H-MC,16.11,120.0,0.95,1.53,29.40,AR,ATH,PHARMA
25,FINCABLES,1.28,27.42,63.18,107.91,118855.0,40478.0,188122.0,1641.55,14.66,46.0,M-SC,18.08,220.0,0.34,1.17,41.53,OX40N,ATH,CABLES
69,SIS,1.35,-1.05,22.55,21.26,24775.0,-1165.0,109867.0,528.00,2622.28,51.0,H-SC,23.22,168.0,-0.05,0.69,63.36,OX40N,NTT,MISC
3,ALKYLAMINE,1.09,-17.29,132.78,92.54,110885.0,-17453.0,83510.0,4520.85,-11.41,64.0,H-SC,13.53,142.0,-0.16,0.52,58.58,SR,ATH,CHEMICALS
42,INDIAMART,-1.70,-24.02,164.44,100.92,154095.0,-29627.0,93709.0,4675.60,-65.82,37.0,H-SC,11.16,140.0,-0.19,0.58,1.44,AR,ATH,MISC

In [17]:
# top 5 to accumulate based on lowest RSI_14
df_tmp = df_portfolio_features[df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])].sort_values(by = 'RSI_14', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
34,HDFCBANK,-1.04,-10.32,46.13,31.05,121266.0,-30241.0,262879.0,1073.00,-25.47,36.0,X-LC,9.97,26.0,-0.25,1.64,2.04,X40,BTT,BANKS
57,PGHH,-1.32,-36.04,106.41,32.01,145313.0,-76960.0,136560.0,17616.87,-56.79,36.0,X-MC,19.23,57.0,-0.53,0.85,0.68,X40,ATH,FMCG
83,VBL,0.26,-10.81,52.09,35.66,163472.0,-38017.0,313827.0,669.42,-21.54,36.0,X-LC,7.70,13.0,-0.23,1.96,15.54,X40N,ATH,FMCG
20,DABUR,0.56,-19.46,78.42,43.70,156680.0,-48272.0,199796.0,735.00,-26.86,39.0,X-MC,8.92,70.0,-0.31,1.25,1.67,XY24,BTT,FMCG
35,HDFCLIFE,1.34,-6.85,49.39,39.15,115352.0,-17183.0,233554.0,811.41,-30.68,41.0,X-LC,15.96,31.0,-0.15,1.46,1.34,X40,ATH,INSURANCE

In [18]:
# top 5 to accumulate based on Spread and CumlRnk
df_tmp = df_portfolio_features[df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])]
df_tmp = df_tmp[(df_tmp['CumlRnk'] < 100)].sort_values(by = 'Spread%', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
19,COLPAL,-2.68,-23.25,82.22,39.86,166200.0,-61225.0,202140.0,3683.41,-7.20,43.0,X-MC,1.69,62.0,-0.37,1.26,14.34,XY25,ATH,FMCG
11,BERGEPAINT,1.05,-1.34,27.02,25.32,68709.0,-3458.0,254291.0,680.00,-6.74,66.0,X-MC,2.01,68.0,-0.05,1.59,33.35,XY24,NTT,PAINTS
8,BAJAJHLDNG,-1.13,3.03,24.47,28.24,64543.0,7759.0,263764.0,14274.15,-5.41,69.0,X-LC,2.05,28.0,0.12,1.65,32.75,X40,ATH,FINANCE
23,DMART,-0.80,-2.72,35.09,31.42,106431.0,-8482.0,303308.0,5391.45,-19.07,47.0,X-LC,2.97,14.0,-0.08,1.89,9.45,X40N,ATH,FMCG
17,CIPLA,-0.42,10.91,13.37,25.73,35765.0,26303.0,267499.0,1648.14,-9.03,55.0,X-LC,3.23,18.0,0.74,1.67,23.07,X40N,ATH,PHARMA

In [19]:
# top 5 to accumulate based on lowest Gained%
df_tmp = df_portfolio_features[df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])].sort_values(by = 'Gained%', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
57,PGHH,-1.32,-36.04,106.41,32.01,145313.0,-76960.0,136560.0,17616.87,-56.79,36.0,X-MC,19.23,57.0,-0.53,0.85,0.68,X40,ATH,FMCG
35,HDFCLIFE,1.34,-6.85,49.39,39.15,115352.0,-17183.0,233554.0,811.41,-30.68,41.0,X-LC,15.96,31.0,-0.15,1.46,1.34,X40,ATH,INSURANCE
20,DABUR,0.56,-19.46,78.42,43.70,156680.0,-48272.0,199796.0,735.00,-26.86,39.0,X-MC,8.92,70.0,-0.31,1.25,1.67,XY24,BTT,FMCG
34,HDFCBANK,-1.04,-10.32,46.13,31.05,121266.0,-30241.0,262879.0,1073.00,-25.47,36.0,X-LC,9.97,26.0,-0.25,1.64,2.04,X40,BTT,BANKS
63,RELIANCE,-0.43,-12.04,51.87,33.59,136004.0,-35876.0,262201.0,1952.00,-19.65,46.0,X-LC,7.76,21.0,-0.26,1.64,2.11,XY25,BTT,REFINERIES

In [20]:
# top 5 to accumulate based on lowest CurrAlloc%
df_tmp = df_portfolio_features[df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])].sort_values(by = 'CurrAlloc%', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
10,BATAINDIA,3.09,-52.82,186.55,35.20,113255.0,-67960.0,60710.0,2096.00,-20.43,67.0,X-SC,15.10,91.0,-0.60,0.38,21.97,X40,NTT,FOOTWEAR
62,RELAXO,1.37,-46.34,183.85,52.31,143197.0,-67272.0,77888.0,1176.00,-42.89,57.0,X-SC,10.23,92.0,-0.47,0.49,74.15,X40N,NTT,FOOTWEAR
57,PGHH,-1.32,-36.04,106.41,32.01,145313.0,-76960.0,136560.0,17616.87,-56.79,36.0,X-MC,19.23,57.0,-0.53,0.85,0.68,X40,ATH,FMCG
58,QUESS,-1.33,30.73,33.02,73.90,46100.0,32819.0,139612.0,424.00,-29.48,62.0,X-SC,38.58,80.0,0.71,0.87,90.32,XY24,NTT,MISC
1,ABBOTINDIA,-0.54,-6.92,23.95,15.37,39870.0,-12385.0,166470.0,34390.26,-20.76,62.0,X-MC,4.12,58.0,-0.31,1.04,12.77,X40,ATH,PHARMA

In [21]:
# top 5 to accumulate based on CumlRnk
df_tmp = df_portfolio_features.sort_values(by = 'CumlRnk', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
47,ITC,-1.19,-21.22,58.29,24.70,182426.0,-84315.0,312963.0,452.00,-58.75,51.0,X-LC,12.00,1.0,-0.46,1.95,3.63,X40,NTT,FMCG
75,TCS,-1.59,-28.93,74.75,24.20,246119.0,-134017.0,329256.0,4230.71,-39.69,63.0,X-LC,16.06,2.0,-0.54,2.05,22.78,X40,ATH,IT
45,INFY,0.01,-16.88,68.89,40.38,215569.0,-63553.0,312917.0,1972.00,-37.59,62.0,X-LC,16.69,3.0,-0.29,1.95,18.50,X40,NTT,IT
77,TMPV,0.09,-17.00,71.99,42.75,248626.0,-70745.0,345362.0,600.00,-83.62,58.0,X-LC,5.98,4.0,-0.28,2.16,18.75,XY24,NTT,AUTO
33,HCLTECH,-1.69,-9.92,37.62,23.97,104880.0,-30698.0,278788.0,1853.42,-8.19,69.0,X-LC,14.18,8.0,-0.29,1.74,31.56,X40,ATH,IT

In [22]:
# top 5 for average up
df_tmp = df_portfolio_features[(df_portfolio_features['Dev%_200'] > 5)].sort_values(by = 'CurrAlloc%', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
44,INDUSINDBK,-0.26,-24.24,75.40,32.89,44104.0,-18714.0,58493.0,1800.00,-375.21,58.0,L-MC,14.29,258.0,-0.42,0.37,44.21,XR,NTT,BANKS
18,COFFEEDAY,6.12,-42.53,135.36,35.27,88337.0,-48288.0,65261.0,80.00,-55.73,66.0,L-SC,5.49,266.0,-0.55,0.41,60.94,XR,NTT,HOTELS
62,RELAXO,1.37,-46.34,183.85,52.31,143197.0,-67272.0,77888.0,1176.00,-42.89,57.0,X-SC,10.23,92.0,-0.47,0.49,74.15,X40N,NTT,FOOTWEAR
79,TTKPRESTIG,-1.34,-19.10,23.72,0.09,19338.0,-19249.0,81528.0,770.00,89.33,47.0,M-SC,13.70,250.0,-1.00,0.51,46.74,OX40N,NTT,DURABLES
3,ALKYLAMINE,1.09,-17.29,132.78,92.54,110885.0,-17453.0,83510.0,4520.85,-11.41,64.0,H-SC,13.53,142.0,-0.16,0.52,58.58,SR,ATH,CHEMICALS

In [23]:
# top 5 RSP
df_tmp = df_portfolio_features.sort_values(by = 'RSP', ascending=False)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
33,HCLTECH,-1.69,-9.92,37.62,23.97,104880.0,-30698.0,278788.0,1853.42,-8.19,69.0,X-LC,14.18,8.0,-0.29,1.74,31.56,X40,ATH,IT
75,TCS,-1.59,-28.93,74.75,24.20,246119.0,-134017.0,329256.0,4230.71,-39.69,63.0,X-LC,16.06,2.0,-0.54,2.05,22.78,X40,ATH,IT
30,HAPPSTMNDS,4.48,-49.38,261.66,83.08,169765.0,-63285.0,64880.0,1466.54,-39.74,67.0,H-SC,10.92,152.0,-0.37,0.40,21.52,AR,ATH,IT
13,BSOFT,0.37,-41.19,152.65,48.59,126275.0,-57931.0,82722.0,819.60,-24.62,65.0,H-SC,18.29,172.0,-0.46,0.52,20.94,XR,ATH,IT
5,ATULAUTO,4.65,0.68,44.58,45.57,88480.0,1343.0,198475.0,844.00,4321.62,78.0,M-SC,7.72,248.0,0.02,1.24,52.73,XY24,NTT,AUTO

In [24]:
# Top N allocation
df_tmp = df_portfolio_features.sort_values(by = 'CurrAlloc%', ascending=False)
top_n_values = [10, 25, 50]

sum_df = pd.DataFrame({
    'Top_N': top_n_values,
    'Sum_Alloc%': [df_tmp['CurrAlloc%'].head(n).sum() for n in top_n_values]
})

sum_df

   Top_N  Sum_Alloc%
0     10       19.67
1     25       44.61
2     50       76.83

In [25]:
# market-cap-wise allocation
df_tmp = df_portfolio_features[cols]
df_tmp.groupby(df_tmp['Conviction'].str[-2:])['CurrAlloc%'].sum().sort_values(ascending=False)

Conviction
SC    39.46
LC    37.59
MC    22.97
Name: CurrAlloc%, dtype: float64

In [26]:
# criteria-wise allocation
df_portfolio_features.groupby('Criteria')['CurrAlloc%'].sum().sort_values(ascending=False)

Criteria
X40      26.36
XY24     25.23
X40N     18.48
XR        9.19
XY25      7.19
OX40N     6.70
AR        6.01
SR        0.86
Name: CurrAlloc%, dtype: float64

In [27]:
# conviction-wise allocation
df_portfolio_features.groupby('Conviction')['CurrAlloc%'].sum().sort_values(ascending=False)

Conviction
X-LC    35.54
H-SC    19.29
X-MC    18.78
X-SC     9.89
M-SC     9.73
H-MC     2.57
M-MC     1.25
H-LC     1.24
M-LC     0.81
L-SC     0.55
L-MC     0.37
Name: CurrAlloc%, dtype: float64

In [28]:
# sector-wise stats
df_tmp = df_portfolio_features.groupby('Category')[['CurrAlloc%', 'Current', 'Current P/L', 'FTT Amt']].sum().sort_values(by=['Current', 'Current P/L'], ascending=False)
df_tmp['Current P/L%'] = round(df_tmp['Current P/L'] * 100 / df_tmp['Current'], 2)
df_tmp['FTT%'] = round(df_tmp['FTT Amt'] * 100 / df_tmp['Current'], 2)
cols = ['CurrAlloc%', 'Current P/L%', 'FTT%']
df_tmp[cols].sort_values(by=['CurrAlloc%'], ascending=False)

               CurrAlloc%  Current P/L%    FTT%
Category
FMCG                15.39        -20.80   64.31
IT                  11.13        -33.49   99.74
FINANCE              9.34        -14.07   62.01
AUTO                 8.43         -0.27   36.41
MISC                 7.09        -17.86   68.44
BANKS                6.07         -9.88   57.27
INSURANCE            5.62         -3.25   39.76
PHARMA               5.54          6.63   19.85
PAINTS               5.37        -14.55   34.09
ELECTRICAL           4.12         -7.03   44.51
HEALTHCARE           2.04         -9.52   38.10
AC                   1.75        -14.08   45.01
APPARELS             1.75          4.13   28.08
FOOTWEAR             1.67        -65.82  132.31
BREWERIES            1.64         11.16    7.29
REFINERIES           1.64        -13.68   51.87
DURABLES             1.53        -58.70   97.30
TRAVEL               1.44        -93.98  191.12
CERAMICS             1.39        -37.63   79.44
ENGINEERING          1.22        -24.36   81.24
CABLES               1.17         21.52   63.18
CHEMICALS            1.13        -46.29  165.03
CEMENT               1.05        -59.78  179.32
JEWELLERY            1.02        -96.58  164.88
ENTERTAINMENT        0.68        -76.69  182.08
HOTELS               0.41        -73.99  135.36
TEXTILES             0.39        -49.46   92.08

In [29]:
# money to be made criteria-wise
df_portfolio_features.groupby('Criteria')['FTT Amt'].agg(['sum', 'count']).sort_values(by='sum', ascending=False)

                sum  count
Criteria
XY24      3361861.0     20
X40       2002537.0     18
XR        1331824.0     13
X40N      1119800.0     12
AR        1065869.0      8
OX40N      717027.0     10
XY25       546844.0      5
SR         279280.0      2

In [30]:
# money to be made conviction-wise
df_portfolio_features.groupby('Conviction')['FTT Amt'].agg(['sum', 'count']).sort_values(by='sum', ascending=False)

                  sum  count
Conviction
H-SC        3260825.0     23
X-LC        2368848.0     20
X-MC        1446198.0     14
M-SC        1358429.0     14
X-SC        1217660.0      9
H-MC         285226.0      2
L-SC         203280.0      2
M-LC         162204.0      1
M-MC          44580.0      1
L-MC          44104.0      1
H-LC          33688.0      1

In [31]:
# money to be made criteria and conviction-wise
df_portfolio_features.groupby(['Conviction', 'Criteria'])['FTT Amt'].agg(['sum', 'count']).sort_values(by='sum', ascending=False)

                           sum  count
Conviction Criteria
X-LC       X40       1154067.0      9
H-SC       XY24       977564.0      5
           AR         917942.0      5
           XR         791033.0      7
M-SC       XY24       785896.0      6
X-SC       XY24       716342.0      4
X-MC       X40        635692.0      7
X-LC       X40N       494131.0      6
           XY24       409556.0      2
X-MC       X40N       337129.0      3
M-SC       OX40N      307078.0      5
H-SC       OX40N      295006.0      4
X-SC       X40N       288540.0      3
H-SC       SR         279280.0      2
X-LC       XY25       254276.0      2
X-MC       XY25       247988.0      2
H-MC       XY24       247114.0      1
X-MC       XY24       225389.0      2
X-SC       X40        212778.0      2
M-SC       XR         189328.0      2
M-LC       XR         162204.0      1
L-SC       OX40N      114943.0      1
           XR          88337.0      1
M-SC       AR          76127.0      1
X-LC       XR          56818.0      1
M-MC       XY25        44580.0      1
L-MC       XR          44104.0      1
H-MC       AR          38112.0      1
H-LC       AR          33688.0      1

In [32]:
# notebook execution time

end_time = time.time()
execution_time = round(end_time - start_time, 0)
print(f"Notebook execution time: {execution_time} seconds")

Notebook execution time: 26.0 seconds