<a href="https://colab.research.google.com/github/ankit-rathi/Quantvesting_v2/blob/main/myStocks_Portfolio_Analysis.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
'''
!pip install pandas==2.2.2 -qq
!pip install pyxirr -qq
!pip install ta -qq
!pip install yfinance==0.2.59 -qq
'''

'\n!pip install pandas==2.2.2 -qq\n!pip install pyxirr -qq\n!pip install ta -qq\n!pip install yfinance==0.2.59 -qq\n'

In [2]:
# import libraries

import numpy as np
import pandas as pd
import datetime
import warnings
warnings.filterwarnings('ignore')
import yfinance as yfin
import ta
import matplotlib.pyplot as plt
import requests

In [3]:
# notebook start time
import time
import datetime
import pytz

start_time = time.time()

# function to print date timestamp
def print_date_time():
  tz_NY = pytz.timezone('Asia/Kolkata')
  datetime_NY = datetime.datetime.now(tz_NY)
  print("Run date time (IST):", datetime_NY.strftime("%Y-%m-%d %H:%M:%S"))

In [4]:
# function to get booked and reserved amount
def get_amt():
  # fetch the JSON data from the URL
  url = "https://raw.githubusercontent.com/ankit-rathi/Tradevesting_v1/main/data/myPortfolioAmts.json"
  response = requests.get(url)
  pf_amts = response.json()  # parse the JSON data

  # extract values from the JSON
  py_booked_amt_dm = pf_amts["py_booked_amt_dm"]
  py_booked_amt_sv = pf_amts["py_booked_amt_sv"]
  cy_booked_amt_dm = pf_amts["cy_booked_amt_dm"]
  cy_booked_amt_sv = pf_amts["cy_booked_amt_sv"]
  reserve_amt_dm = pf_amts["reserve_amt_dm"]
  reserve_amt_sv = pf_amts["reserve_amt_sv"]

  # perform calculations
  py_booked_amt = py_booked_amt_dm + py_booked_amt_sv
  cy_booked_amt = cy_booked_amt_dm + cy_booked_amt_sv
  reserve_amt = reserve_amt_dm + reserve_amt_sv
  total_booked_amt = py_booked_amt + cy_booked_amt

  return total_booked_amt, reserve_amt, cy_booked_amt, py_booked_amt

gen_output = 0

In [5]:
# function to format the amount
def format_amt(number):
    abs_number = abs(number)

    if abs_number >= 1_00_00_000:  # Crores
        formatted_amt = f"{number / 1_00_00_000:.2f} C"
    elif abs_number >= 1_00_000:  # Lakhs
        formatted_amt = f"{number / 1_00_000:.2f} L"
    elif abs_number >= 1_000:  # Thousands
        formatted_amt = f"{number / 1_000:.2f} K"
    else:
        formatted_amt = f"{number:.2f}"

    return formatted_amt

# function to set start and end date
def get_start_end_date():
  start_date = (datetime.date.today() + datetime.timedelta(days=-365)).strftime('%Y-%m-%d')
  end_date = (datetime.date.today() + datetime.timedelta(days=1)).strftime('%Y-%m-%d')
  return start_date, end_date

# function to fetch my portfolio csv
def get_mypfs_df():
  mypfs_df = pd.read_csv('https://raw.githubusercontent.com/ankit-rathi/Tradevesting_v1/main/data/myPortfolioStocks.csv')
  return mypfs_df

# function to fetch my prospects csv
def get_mypps_df():
  mypps_df = pd.read_csv('https://raw.githubusercontent.com/ankit-rathi/Tradevesting_v1/main/data/myProspectsScrips.csv')
  return mypps_df

# function to fetch screener data
def get_myscreen_df():
  myscreen_df = pd.read_csv('https://raw.githubusercontent.com/ankit-rathi/Tradevesting_v1/main/data/myScreenerDB.csv')
  return myscreen_df

# function to fetch momentum data
def get_myinvmt_df():
  myinvmt_df = pd.read_csv('https://raw.githubusercontent.com/ankit-rathi/Tradevesting_v1/main/data/myInvestments.csv')
  return myinvmt_df

# function to get the stock ids
def get_stock_ids(df_pf):
  stock_n100 = df_pf['Symbol'].unique()

  exclude = ['CADILAHC','MMTC', 'MASFIN']

  stock_ids = df_pf[~df_pf['Symbol'].isin(exclude) ]['Symbol'].unique()

  #mypf = mypf[mypf.Forecast.notnull()]
  #stock_ids = mypf['Symbol'].unique()

  #stock_ids.sort()
  return stock_ids

# get features from screener data
def get_screener_features():
  myscreen_df = get_myscreen_df()
  cols = ['Symbol', 'EPS', 'MedPE', 'ROCE%', 'ROE%', 'CapType']
  return myscreen_df[cols]

# get relative strength
def get_relative_strength(stock_list):

    # Dictionary to store stock tickers and their corresponding percentage price change
    stock_changes = {}

    # Loop through each stock and fetch its price data
    for stock in stock_list:
        try:
            # Download the stock data for the given date range
            stock_data = yfin.Ticker(stock + '.NS').history(period='1mo', interval='1d')[map(str.title, ['open', 'close', 'low', 'high', 'volume'])]

            # Calculate the percentage change for the stock
            if len(stock_data) > 0:
                start_price = stock_data['Close'].iloc[0]
                end_price = stock_data['Close'].iloc[-1]
                percent_change = round(((end_price - start_price) / start_price) * 100, 2)
                stock_changes[stock] = percent_change
            else:
                stock_changes[stock] = np.nan  # If no data is available, set to NaN

        except Exception as e:
            print(f"Error fetching data for {stock}: {e}")
            stock_changes[stock] = np.nan

    # Create a DataFrame with stock tickers and their percentage changes
    df = pd.DataFrame(list(stock_changes.items()), columns=['Symbol', 'Percent_Change'])

    # Drop any stocks with missing data (NaN values)
    df = df.dropna()

    # Calculate the percentile rank based on percentage change
    df['RSP'] = round(df['Percent_Change'].rank(pct=True) * 100, 2)
    cols = ['Symbol', 'RSP']
    df = df[cols]
    # Sort by percentile rank (optional)
    df = df.sort_values(by='RSP', ascending=False).reset_index(drop=True)

    return df

In [6]:
# function to get stock technicals
def stock_prec_dev(stock_symbol):
    #stock_symbol = 'ULTRACEMCO.NS'
    short_window = 20
    mid_window = 50
    long_window = 200
    moving_avg = 'SMA'

    start = datetime.datetime(*map(int, start_date.split('-')))
    end = datetime.datetime(*map(int, end_date.split('-')))

    stock_df = yfin.Ticker(stock_symbol + '.NS').history(period='max', interval='1d')[map(str.title, ['open', 'close', 'low', 'high', 'volume'])]

    stock_df['Max'] = round(max(stock_df['Close']),2)
    stock_df = stock_df[(stock_df.index <= end_date) & (stock_df.index >= start_date)]
    stock_df['200_SMA'] = round(stock_df['Close'].rolling(window = 200, min_periods = 1).mean(),0)
    stock_df['Dev%_200'] = round((stock_df['Close'] - stock_df['200_SMA'])*100/stock_df['200_SMA'],2)
    stock_df.dropna(axis = 0, inplace = True) # remove any null rows

    stock_df['20_SMA'] = stock_df['Close'].rolling(window=20).mean()
    stock_df['50_SMA'] = stock_df['Close'].rolling(window=50).mean()
    stock_df['Symbol'] = stock_symbol

    stock_df['Close'] = round(stock_df['Close'],2)
    stock_df['Min'] = round(min(stock_df['Close']),2)
    stock_df['RSI_14'] = ta.momentum.RSIIndicator(close=stock_df['Close'], window=14).rsi()
    stock_df['RSI_14'] = round(stock_df['RSI_14'],0)
    stock_df['Prev_Close'] = stock_df['Close'].shift(1)
    stock_df.drop(['Open', 'Low', 'High', 'Volume'], axis=1, inplace=True)
    stock_df = stock_df.tail(1)

    max_SMA = max(stock_df['20_SMA'].item(), stock_df['50_SMA'].item(), stock_df['200_SMA'].item())
    min_SMA = min(stock_df['20_SMA'].item(), stock_df['50_SMA'].item(), stock_df['200_SMA'].item())
    ABS_Spread = max_SMA - min_SMA
    stock_df['Spread%'] = round((ABS_Spread / stock_df['200_SMA'].item()) * 100,2)

    return stock_df

# function to compute stock attributes
def get_common_features(stock_ids, df_mypf):

  df_prec_dev = pd.DataFrame()
  df_tmp = get_screener_features()
  df_rs = get_relative_strength(stock_ids)

  for stock_id in stock_ids:
      tmp = stock_prec_dev(stock_id)
      tmp = tmp.reset_index()
      df_prec_dev = pd.concat([df_prec_dev, tmp], ignore_index = True)
  df_prec_dev = pd.merge(df_prec_dev, df_mypf, on= 'Symbol')
  df_prec_dev = pd.merge(df_prec_dev, df_tmp, on= 'Symbol', how='left')
  df_prec_dev = pd.merge(df_prec_dev, df_rs, on= 'Symbol', how='left')
  #print(df_prec_dev.columns)
  df_prec_dev['Curr_PE'] = round(df_prec_dev['Close']/df_prec_dev['EPS'],1)
  df_prec_dev['Dev%_PE'] = round((df_prec_dev['Curr_PE'] - df_prec_dev['MedPE'])*100/df_prec_dev['MedPE'],2)
  df_prec_dev['Conviction'] = df_prec_dev['Conviction'] + '-' + df_prec_dev['CapType']
  return df_prec_dev

# function to arrange stock features
def arrange_features(df_stocks, common_cols, diff_cols):
  df_stocks_common = df_stocks[common_cols].drop_duplicates()
  df_stocks_diff = df_stocks[diff_cols]
  df_stocks_diff['Investment'] = df_stocks_diff['AvgCost'] * df_stocks_diff['Shares']
  df_stocks_diff = df_stocks_diff.groupby(['Symbol'])[['Shares', 'Investment']].aggregate(['sum']).reset_index()
  df_stocks_diff.columns = ['Symbol', 'Shares', 'Investment']
  df_stocks_diff['AvgCost'] = round(df_stocks_diff['Investment']/df_stocks_diff['Shares'],2)
  df_stocks = pd.merge(df_stocks_diff, df_stocks_common, on='Symbol')
  return df_stocks

# plot fact distribution across dimension
def plot_pie_chart(df, dimension, fact):
  # grouping the data by category and calculating the sum of fact for each type
  grouped_data = df.groupby(dimension)[fact].sum()

  # sorting the grouped data in descending order
  grouped_data = grouped_data.sort_values(ascending=False)

  # creating a pie chart
  grouped_data.plot.pie(autopct='%1.1f%%', startangle=90, figsize=(6, 6))

  # adding a title and displaying the plot
  plt.title(f'{dimension} {fact} Distribution')
  plt.ylabel('')  # To hide the y-label
  plt.show()

In [7]:
# function to get portfolio features

def get_portfolio_features(df_common_features):

  print_date_time()
  print('-------------------')

  #df_common_features["Target"] = df_common_features["Target"].fillna(df_common_features["Max"])
  df_common_features['NTT'] = np.where(df_common_features['Strategy']== 'NTT', df_common_features["Target"], df_common_features['Max'])
  df_common_features['LTT'] = np.where(df_common_features['Strategy']== 'BTT', df_common_features["Target"], df_common_features['Max'])
  df_common_features['BOL'] = df_common_features['Min']

  tmp_df = df_common_features[df_common_features['Symbol'].isin(mypf_df[mypf_df['InPortfolio'] != 'NA'].Symbol.values)]
  print('qualified stocks: '+str(len(tmp_df['Symbol'].unique())))
  tmp_df1 = tmp_df[tmp_df['LatestQtr'] == 1]
  print('with latest results: '+str(len(tmp_df1['Symbol'].unique())))
  tmp_df1 = tmp_df1[tmp_df1['StarStock'] == 1]
  print('still star stocks: '+str(len(tmp_df1['Symbol'].unique())))
  tmp_df['Investment'] = tmp_df['AvgCost'] * tmp_df['Shares']
  tmp_df['Current'] = round(tmp_df['Close'] * tmp_df['Shares'],0)
  tmp_df['Previous'] = tmp_df['Prev_Close'] * tmp_df['Shares']
  tmp_df['EstimatedST'] = tmp_df['NTT'] * tmp_df['Shares']
  tmp_df['EstimatedLT'] = tmp_df['LTT'] * tmp_df['Shares']
  tmp_df['Current P/L'] = round((tmp_df['Current'] - tmp_df['Investment']),0)
  tmp_df['Today P/L%'] = round((tmp_df['Current'] - tmp_df['Previous'])*100/tmp_df['Previous'],2)
  tmp_df['Current P/L%'] = round((tmp_df['Current'] - tmp_df['Investment'])*100/tmp_df['Investment'],2)
  tmp_df['EstimatedST P/L%'] = round((tmp_df['EstimatedST'] - tmp_df['Investment'])*100/tmp_df['Investment'],2)
  tmp_df['EstimatedLT P/L%'] = round((tmp_df['EstimatedLT'] - tmp_df['Investment'])*100/tmp_df['Investment'],2)
  tmp_df['NTT%'] = round((tmp_df['NTT'] - tmp_df['Close'])*100/tmp_df['Close'],2)
  tmp_df['LTT%'] = round((tmp_df['LTT'] - tmp_df['Close'])*100/tmp_df['Close'],2)
  tmp_df['Gained%'] = round((tmp_df['Close'] - tmp_df['BOL'])*100/tmp_df['BOL'],2)
  investment = round(sum(tmp_df['AvgCost']*tmp_df['Shares']),0)
  current = round(sum(tmp_df['Close']*tmp_df['Shares']),0)
  tmp_df['InitAlloc%'] = round(tmp_df['Investment']*100/investment,2)
  tmp_df['CurrAlloc%'] = round(tmp_df['Current']*100/current,2)
  tmp_df['FTT'] = tmp_df['LTT']
  tmp_df.loc[tmp_df['Strategy'] == 'NTT', 'FTT'] = tmp_df['NTT']
  tmp_df['FTT%'] = tmp_df['LTT%']
  tmp_df.loc[tmp_df['Strategy'] == 'NTT', 'FTT%'] = tmp_df['NTT%']
  tmp_df['FTT Amt'] = round(tmp_df['FTT%'] * tmp_df['Current']/100,0)
  tmp_df['OTT%'] = round((tmp_df['FTT'] - tmp_df['AvgCost'])*100/tmp_df['AvgCost'],2)
  tmp_df['RRR Ind'] = round(tmp_df['Current P/L']/tmp_df['FTT Amt'],2)
  tmp_df['Risk Ind'] = round(tmp_df['Current P/L%']*tmp_df['CurrAlloc%'],0)

  return tmp_df

# function to print portfolio features
def print_portfolio_stats(df_portfolio_features, myinvmt_df):
  from pyxirr import xirr

  total_booked_amt, reserve_amt, cy_booked_amt, py_booked_amt = get_amt()

  dates = myinvmt_df['Date'].values
  dates = np.append(dates, datetime.date.today().strftime('%d-%b-%y'))
  investment = myinvmt_df['Investment'].values
  dates= pd.to_datetime(dates)

  current = round(sum(df_portfolio_features['Close']*df_portfolio_features['Shares']),0) + reserve_amt
  investment_xirr = np.append(investment, current)
  cagr = round(xirr(pd.DataFrame({"dates": dates, "amounts": investment_xirr}))*100,2)

  investment = -sum(investment)
  invested = round(sum(df_portfolio_features['AvgCost']*df_portfolio_features['Shares']),0) + reserve_amt
  previous = round(sum(df_portfolio_features['Prev_Close']*df_portfolio_features['Shares']),0) + reserve_amt
  cy_invested = investment + py_booked_amt

  today_pnl_amount = current-previous
  today_pnl_percentage = round((current-previous)*100/previous,2)

  curr_pnl_amount = current-invested
  curr_pnl_percentage = round((curr_pnl_amount)*100/(cy_invested),2)

  cy_pnl_amount = cy_booked_amt + curr_pnl_amount
  cy_pnl_percentage = round((cy_pnl_amount)*100/cy_invested,2)

  overall_pnl_amount = total_booked_amt + curr_pnl_amount
  overall_pnl_percentage = round((overall_pnl_amount)*100/investment,2)

  estimate_st = round(sum(df_portfolio_features['FTT']*df_portfolio_features['Shares']),0)  + reserve_amt
  est_st_pnl_amount = estimate_st-current
  est_st_pnl_percentage = round((est_st_pnl_amount)*100/current,2)

  estimate_lt = round(sum(df_portfolio_features['LTT']*df_portfolio_features['Shares']),0)  + reserve_amt
  est_lt_pnl_amount = estimate_lt-current
  est_lt_pnl_percentage = round((est_lt_pnl_amount)*100/current,2)

  total_profit = round(sum(df_portfolio_features[df_portfolio_features['Current P/L%'] > 0]['Current']) - sum(df_portfolio_features[df_portfolio_features['Current P/L%'] > 0]['Investment']),0)
  total_loss = round(sum(df_portfolio_features[df_portfolio_features['Current P/L%'] < 0]['Current']) - sum(df_portfolio_features[df_portfolio_features['Current P/L%'] < 0]['Investment']),0)

  cy_booked_percentage = round((cy_booked_amt)*100/current,2)
  py_booked_percentage = round((py_booked_amt)*100/investment,2)
  total_booked_percentage = round((total_booked_amt)*100/investment,2)

  print('-------------------')
  print('Initial Investment: ', format_amt(investment))
  print('CY Investment: ', format_amt(cy_invested))
  print('Reserve: ', format_amt(reserve_amt))
  print('Current: ',  format_amt(current))
  print('-------------------')
  print('Today PnL: '+ '{} ({}%)'.format(format_amt(today_pnl_amount), today_pnl_percentage))
  print('Current PnL: '+ '{} ({}%)'.format(format_amt(curr_pnl_amount), curr_pnl_percentage))
  print('CY Booked + Current PnL: '+ '{} ({}%)'.format(format_amt(cy_pnl_amount), cy_pnl_percentage))
  print('-------------------')
  print('Total profit: ', format_amt(total_profit))
  print('Total loss: ', format_amt(total_loss))
  print('-------------------')
  print('Total Booked + Current PnL: '+ '{} ({}%)'.format(format_amt(overall_pnl_amount), overall_pnl_percentage))
  print('Total Booked PnL: '+ '{} ({}%)'.format(format_amt(total_booked_amt), total_booked_percentage))
  print('Curr Year Booked PnL: '+ '{} ({}%)'.format(format_amt(cy_booked_amt), cy_booked_percentage))
  print('Prev Year Booked PnL: '+ '{} ({}%)'.format(format_amt(py_booked_amt), py_booked_percentage))
  print('===================')
  print('Est FTT: ',  format_amt(estimate_st))
  print('Est FTT PnL: '+ '{} ({}%)'.format(format_amt(est_st_pnl_amount), est_st_pnl_percentage))

  print('===================')
  print('Deployed: ', format_amt(investment))

  print('Current: ', format_amt(current))

  print('CAGR/XIRR %: '+'{}%'.format(cagr))

In [8]:
# get start and end date
start_date, end_date = get_start_end_date()

# get portfolio and prospects data
mypfs_df = get_mypfs_df()
mypps_df = get_mypps_df()
myinvmt_df = get_myinvmt_df()

# merge above datasets
mypf_df = pd.merge(mypfs_df, mypps_df, on="Symbol")

# seggregate dm and sv portfolio
dm_pf = mypf_df[mypf_df['InPortfolio'] == 'DM']
sv_pf = mypf_df[mypf_df['InPortfolio'] == 'SV']

# build portfolio stock dataframe
dm_stocks = get_stock_ids(dm_pf)
sv_stocks = get_stock_ids(sv_pf)
df_stocks = pd.concat([dm_pf,sv_pf], ignore_index = True)

# arrange common and diff stock features
common_cols = ['Symbol', 'Target', 'Criteria', 'Strategy', 'CumlRnk', 'LatestQtr', 'StarStock', 'Conviction', 'Category', 'InFolio', 'XIRR', 'MBQ']
diff_cols = ['Symbol', 'AvgCost', 'Shares']
df_stocks = arrange_features(df_stocks, common_cols, diff_cols)

# get common features
stock_ids = df_stocks['Symbol'].values
df_common_features = get_common_features(stock_ids, df_stocks)

df_common_features.reset_index(drop=True, inplace=True)
df_common_features.drop(['Date'], axis=1, inplace=True)
# get and print portfolio features
df_portfolio_features = get_portfolio_features(df_common_features)

print_portfolio_stats(df_portfolio_features, myinvmt_df)

df = df_portfolio_features
#plot_pie_chart(df, 'CapType', 'Current')
list_ox40n = list(df[df['MBQ'].str.contains('OX40N', na=False)]['Symbol'].values)

Run date time (IST): 2026-08-14 16:12:32
-------------------
qualified stocks: 88
with latest results: 30
still star stocks: 19
-------------------
Initial Investment:  1.46 C
CY Investment:  1.89 C
Reserve:  2.21 L
Current:  1.60 C
-------------------
Today PnL: -1.01 L (-0.63%)
Current PnL: -32.86 L (-17.39%)
CY Booked + Current PnL: -28.21 L (-14.93%)
-------------------
Total profit:  3.74 L
Total loss:  -36.60 L
-------------------
Total Booked + Current PnL: 14.66 L (10.04%)
Total Booked PnL: 47.52 L (32.53%)
Curr Year Booked PnL: 4.65 L (2.91%)
Prev Year Booked PnL: 42.87 L (29.35%)
===================
Est FTT:  2.68 C
Est FTT PnL: 1.08 C (67.7%)
===================
Deployed:  1.46 C
Current:  1.60 C
CAGR/XIRR %: 4.07%

In [9]:
# top 5 near their targets
cols = ['Symbol', 'Today P/L%', 'Current P/L%', 'FTT%', 'OTT%', 'FTT Amt', 'Current P/L', 'Current', 'FTT', 'Dev%_PE', 'RSI_14','Conviction', 'Spread%',  'CumlRnk', 'RRR Ind', 'CurrAlloc%', 'Gained%', 'Criteria', 'Strategy', 'Category']
df_tmp = df_portfolio_features[~df_portfolio_features['Symbol'].isin(['ENRIN','BLUSPRING','DIGITIDE'])]
df_tmp = df_tmp.sort_values(by = 'FTT Amt', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
79,UNITDSPR,1.39,12.83,7.03,20.77,18573.0,30048.0,264192.0,1644.00,0.00,66.0,X-MC,9.53,64.0,1.62,1.68,27.00,X40N,NTT,BREWERIES
78,TTKPRESTIG,-0.84,-22.54,29.22,0.09,22810.0,-22714.0,78063.0,770.00,81.22,42.0,M-SC,11.09,250.0,-1.00,0.50,40.50,OX40N,NTT,DURABLES
68,SIS,-1.18,-1.32,22.89,21.26,25079.0,-1471.0,109561.0,528.00,2615.03,48.0,H-SC,22.11,168.0,-0.06,0.70,62.90,OX40N,NTT,MISC
52,M&M,0.00,8.26,9.76,18.82,25430.0,19870.0,260551.0,3762.88,-5.74,60.0,X-LC,4.67,25.0,0.78,1.65,18.19,X40N,ATH,AUTO
54,MASFIN,-0.71,-7.69,31.69,21.57,28664.0,-7530.0,90450.0,397.04,-20.51,41.0,H-SC,0.77,167.0,-0.26,0.57,7.81,XR,ATH,FINANCE

In [10]:
# top 5 today
df_tmp = df_portfolio_features.sort_values(by = 'Today P/L%', ascending=False)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
30,HAPPSTMNDS,6.43,-47.54,249.01,83.08,167414.0,-60933.0,67232.0,1466.54,-37.70,68.0,H-SC,9.22,152.0,-0.36,0.43,25.93,AR,ATH,IT
10,BATAINDIA,3.85,-51.25,177.36,35.20,111246.0,-65947.0,62723.0,2096.00,-17.83,68.0,X-SC,12.38,91.0,-0.59,0.40,26.02,X40,NTT,FOOTWEAR
24,EASEMYTRIP,3.39,-64.68,312.50,45.70,195159.0,-114364.0,62451.0,26.40,-35.08,38.0,M-SC,6.78,204.0,-0.59,0.40,9.40,XY24,NTT,TRAVEL
84,VOLTAS,2.40,3.30,40.55,45.20,80319.0,6333.0,198075.0,1856.00,18.29,54.0,X-MC,3.66,79.0,0.08,1.26,8.56,XY25,NTT,AC
32,HAVELLS,2.20,-16.89,58.14,31.42,158478.0,-55411.0,272580.0,2052.62,-21.80,67.0,X-MC,7.62,63.0,-0.35,1.73,14.97,X40,ATH,ELECTRICAL

In [11]:
# bottom 5 today
df_tmp = df_portfolio_features.sort_values(by = 'Today P/L%', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
61,RELAXO,-5.53,-48.68,196.78,52.31,146591.0,-70665.0,74495.0,1176.0,-45.41,46.0,X-SC,13.44,92.0,-0.48,0.47,66.56,X40N,NTT,FOOTWEAR
82,VALIANTORG,-4.99,-32.56,158.24,74.15,174586.0,-53275.0,110330.0,838.0,-298.38,67.0,H-SC,5.61,145.0,-0.31,0.70,64.19,XR,NTT,CHEMICALS
76,TMPV,-4.32,-20.42,79.37,42.75,262838.0,-84952.0,331155.0,600.0,-84.72,43.0,X-LC,4.47,4.0,-0.32,2.10,13.87,XY24,NTT,AUTO
60,RECLTD,-2.88,-9.31,33.13,20.74,61042.0,-18920.0,184250.0,446.0,-0.39,34.0,M-MC,3.23,191.0,-0.31,1.17,11.56,XY25,NTT,FINANCE
70,SURYODAY,-2.77,-13.39,42.05,23.03,65220.0,-23970.0,155101.0,216.0,68.86,32.0,H-SC,16.17,166.0,-0.37,0.98,31.65,XR,NTT,BANKS

In [12]:
# top 5 to exit based on CumlRnk
df_tmp = df_portfolio_features[~df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])]
df_tmp = df_tmp[(df_tmp['Current P/L%'] > -1) & (df_tmp['Current P/L%'] < 1)].sort_values(by = 'CumlRnk', ascending=False)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
80,UTIAMC,-0.05,0.06,51.06,51.15,113594.0,142.0,222472.0,1371.68,-19.39,48.0,M-SC,7.6,229.0,0.0,1.41,4.21,XY24,ATH,FINANCE

In [13]:
# OX40N stocks to exit
df_tmp = df_portfolio_features[(df_portfolio_features['Symbol'].isin(list_ox40n))].sort_values(by = 'Current P/L%', ascending=False)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
25,FINCABLES,-0.20,57.92,31.66,107.91,73819.0,85517.0,233161.0,1641.55,42.06,72.0,M-SC,18.27,220.0,1.16,1.48,75.42,OX40N,ATH,CABLES
68,SIS,-1.18,-1.32,22.89,21.26,25079.0,-1471.0,109561.0,528.00,2615.03,48.0,H-SC,22.11,168.0,-0.06,0.70,62.90,OX40N,NTT,MISC
43,INDIGOPNTS,1.62,-18.40,22.57,0.02,32148.0,-32120.0,142439.0,1408.00,117.08,66.0,M-SC,6.26,222.0,-1.00,0.90,61.61,OX40N,NTT,PAINTS
78,TTKPRESTIG,-0.84,-22.54,29.22,0.09,22810.0,-22714.0,78063.0,770.00,81.22,42.0,M-SC,11.09,250.0,-1.00,0.50,40.50,OX40N,NTT,DURABLES
16,CERA,-0.90,-23.22,61.36,23.89,82870.0,-40847.0,135056.0,9475.00,-26.01,38.0,H-SC,12.57,153.0,-0.49,0.86,31.29,OX40N,NTT,CERAMICS

In [14]:
# top 5 to book for rotation
df_tmp = df_portfolio_features[(df_portfolio_features['Current P/L%'] > 20) ].sort_values(by = 'CumlRnk', ascending=False)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
25,FINCABLES,-0.20,57.92,31.66,107.91,73819.0,85517.0,233161.0,1641.55,42.06,72.0,M-SC,18.27,220.0,1.16,1.48,75.42,OX40N,ATH,CABLES
57,QUESS,1.38,38.54,25.52,73.90,37758.0,41163.0,147956.0,424.00,-25.62,70.0,X-SC,42.11,80.0,1.09,0.94,103.64,XY24,NTT,MISC

In [15]:
# top 5 to monitor for exit
df_tmp = df_portfolio_features[~df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])]
df_tmp = df_tmp[(df_tmp['Current P/L%'] > 0) ].sort_values(by = 'Dev%_PE', ascending=False)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
69,STARHEALTH,0.09,13.23,30.05,47.26,95656.0,37199.0,318322.0,761.00,78.72,51.0,H-SC,16.49,173.0,0.39,2.02,37.63,XY24,NTT,INSURANCE
25,FINCABLES,-0.20,57.92,31.66,107.91,73819.0,85517.0,233161.0,1641.55,42.06,72.0,M-SC,18.27,220.0,1.16,1.48,75.42,OX40N,ATH,CABLES
87,ZYDUSLIFE,-2.75,19.71,13.20,35.51,33116.0,41305.0,250879.0,1285.01,4.05,51.0,H-MC,15.85,120.0,1.25,1.59,32.03,AR,ATH,PHARMA
80,UTIAMC,-0.05,0.06,51.06,51.15,113594.0,142.0,222472.0,1371.68,-19.39,48.0,M-SC,7.60,229.0,0.00,1.41,4.21,XY24,ATH,FINANCE

In [16]:
# top 5 to book for rotation from weak conviction
df_tmp = df_portfolio_features[~df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])]
df_tmp = df_tmp[~df_tmp['Criteria'].isin(['XY25','XY24','X40', 'X40N'])].sort_values(by = 'RRR Ind', ascending=False)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
87,ZYDUSLIFE,-2.75,19.71,13.20,35.51,33116.0,41305.0,250879.0,1285.01,4.05,51.0,H-MC,15.85,120.0,1.25,1.59,32.03,AR,ATH,PHARMA
25,FINCABLES,-0.20,57.92,31.66,107.91,73819.0,85517.0,233161.0,1641.55,42.06,72.0,M-SC,18.27,220.0,1.16,1.48,75.42,OX40N,ATH,CABLES
68,SIS,-1.18,-1.32,22.89,21.26,25079.0,-1471.0,109561.0,528.00,2615.03,48.0,H-SC,22.11,168.0,-0.06,0.70,62.90,OX40N,NTT,MISC
3,ALKYLAMINE,-0.32,-18.36,135.84,92.54,111969.0,-18536.0,82427.0,4520.85,-12.57,56.0,H-SC,13.85,142.0,-0.17,0.52,56.52,SR,ATH,CHEMICALS
42,INDIAMART,-0.76,-23.08,161.22,100.92,152941.0,-28471.0,94865.0,4675.60,-65.23,43.0,H-SC,13.12,140.0,-0.19,0.60,2.69,AR,ATH,MISC

In [17]:
# top 5 to accumulate based on lowest RSI_14
df_tmp = df_portfolio_features[df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])].sort_values(by = 'RSI_14', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
28,GODREJCP,-0.28,-15.01,56.37,32.90,119553.0,-37451.0,212086.0,1460.97,-12.03,31.0,X-LC,5.21,32.0,-0.31,1.35,3.24,X40N,ATH,FMCG
55,PAGEIND,0.63,-4.15,39.37,33.59,101279.0,-11129.0,257250.0,51217.29,-31.29,31.0,X-MC,8.78,55.0,-0.11,1.63,22.17,X40,ATH,APPARELS
56,PGHH,-0.71,-36.86,109.07,32.01,147053.0,-78696.0,134824.0,17616.87,-57.33,34.0,X-MC,19.19,57.0,-0.54,0.86,0.00,X40,ATH,FMCG
34,HDFCBANK,0.28,-11.21,47.59,31.05,123861.0,-32854.0,260266.0,1073.00,-25.96,34.0,X-LC,12.48,26.0,-0.27,1.65,1.02,X40,BTT,BANKS
20,DABUR,-1.16,-20.77,81.37,43.70,159929.0,-51522.0,196546.0,735.00,-28.15,35.0,X-MC,9.61,70.0,-0.32,1.25,0.01,XY24,BTT,FMCG

In [18]:
# top 5 to accumulate based on Spread and CumlRnk
df_tmp = df_portfolio_features[df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])]
df_tmp = df_tmp[(df_tmp['CumlRnk'] < 100)].sort_values(by = 'Spread%', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
19,COLPAL,-0.73,-24.78,85.94,39.86,170247.0,-65265.0,198100.0,3683.41,-8.99,39.0,X-MC,1.46,62.0,-0.38,1.26,12.06,XY25,ATH,FMCG
23,DMART,-0.25,-1.04,32.79,31.42,101177.0,-3230.0,308560.0,5391.45,-17.73,53.0,X-LC,2.50,14.0,-0.03,1.96,11.35,X40N,ATH,FMCG
50,KOTAKBANK,-0.32,2.80,15.67,18.92,38615.0,6722.0,246424.0,452.46,-10.27,51.0,X-LC,2.77,12.0,0.17,1.56,10.87,X40,ATH,BANKS
26,GILLETTE,0.06,-10.20,44.46,29.72,101369.0,-25896.0,228000.0,10978.86,-31.02,41.0,X-SC,3.24,83.0,-0.26,1.45,4.78,X40,ATH,FMCG
84,VOLTAS,2.40,3.30,40.55,45.20,80319.0,6333.0,198075.0,1856.00,18.29,54.0,X-MC,3.66,79.0,0.08,1.26,8.56,XY25,NTT,AC

In [19]:
# top 5 to accumulate based on lowest Gained%
df_tmp = df_portfolio_features[df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])].sort_values(by = 'Gained%', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
35,HDFCLIFE,-0.41,-8.10,51.42,39.15,118480.0,-20321.0,230416.0,811.41,-31.58,38.0,X-LC,16.41,31.0,-0.17,1.46,0.00,X40,ATH,INSURANCE
56,PGHH,-0.71,-36.86,109.07,32.01,147053.0,-78696.0,134824.0,17616.87,-57.33,34.0,X-MC,19.19,57.0,-0.54,0.86,0.00,X40,ATH,FMCG
20,DABUR,-1.16,-20.77,81.37,43.70,159929.0,-51522.0,196546.0,735.00,-28.15,35.0,X-MC,9.61,70.0,-0.32,1.25,0.01,XY24,BTT,FMCG
47,ITC,-0.11,-23.25,62.47,24.70,190475.0,-92371.0,304907.0,452.00,-59.97,41.0,X-LC,10.70,1.0,-0.48,1.94,0.96,X40,NTT,FMCG
34,HDFCBANK,0.28,-11.21,47.59,31.05,123861.0,-32854.0,260266.0,1073.00,-25.96,34.0,X-LC,12.48,26.0,-0.27,1.65,1.02,X40,BTT,BANKS

In [20]:
# top 5 to accumulate based on lowest CurrAlloc%
df_tmp = df_portfolio_features[df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])].sort_values(by = 'CurrAlloc%', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
10,BATAINDIA,3.85,-51.25,177.36,35.20,111246.0,-65947.0,62723.0,2096.00,-17.83,68.0,X-SC,12.38,91.0,-0.59,0.40,26.02,X40,NTT,FOOTWEAR
61,RELAXO,-5.53,-48.68,196.78,52.31,146591.0,-70665.0,74495.0,1176.00,-45.41,46.0,X-SC,13.44,92.0,-0.48,0.47,66.56,X40N,NTT,FOOTWEAR
56,PGHH,-0.71,-36.86,109.07,32.01,147053.0,-78696.0,134824.0,17616.87,-57.33,34.0,X-MC,19.19,57.0,-0.54,0.86,0.00,X40,ATH,FMCG
57,QUESS,1.38,38.54,25.52,73.90,37758.0,41163.0,147956.0,424.00,-25.62,70.0,X-SC,42.11,80.0,1.09,0.94,103.64,XY24,NTT,MISC
2,ACC,-0.25,-40.86,195.60,74.81,310159.0,-109560.0,158568.0,3906.00,-57.90,40.0,X-SC,11.74,85.0,-0.35,1.01,5.93,XY24,BTT,CEMENT

In [21]:
# top 5 to accumulate based on CumlRnk
df_tmp = df_portfolio_features.sort_values(by = 'CumlRnk', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
47,ITC,-0.11,-23.25,62.47,24.70,190475.0,-92371.0,304907.0,452.00,-59.97,41.0,X-LC,10.70,1.0,-0.48,1.94,0.96,X40,NTT,FMCG
74,TCS,-0.59,-30.69,79.19,24.20,254276.0,-142177.0,321096.0,4230.71,-41.33,53.0,X-LC,14.79,2.0,-0.56,2.04,19.74,X40,ATH,IT
45,INFY,-0.49,-16.77,68.66,40.38,215143.0,-63124.0,313346.0,1972.00,-37.23,59.0,X-LC,16.02,3.0,-0.29,1.99,18.66,X40,NTT,IT
76,TMPV,-4.32,-20.42,79.37,42.75,262838.0,-84952.0,331155.0,600.00,-84.72,43.0,X-LC,4.47,4.0,-0.32,2.10,13.87,XY24,NTT,AUTO
33,HCLTECH,-0.73,-9.04,36.28,23.97,102135.0,-27966.0,281520.0,1853.42,-7.36,67.0,X-LC,12.08,8.0,-0.27,1.79,32.84,X40,ATH,IT

In [22]:
# top 5 for average up
df_tmp = df_portfolio_features[(df_portfolio_features['Dev%_200'] > 5)].sort_values(by = 'CurrAlloc%', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
44,INDUSINDBK,-0.38,-24.64,76.33,32.89,44413.0,-19020.0,58186.0,1800.00,-373.81,55.0,L-MC,13.62,258.0,-0.43,0.37,43.45,XR,NTT,BANKS
61,RELAXO,-5.53,-48.68,196.78,52.31,146591.0,-70665.0,74495.0,1176.00,-45.41,46.0,X-SC,13.44,92.0,-0.48,0.47,66.56,X40N,NTT,FOOTWEAR
3,ALKYLAMINE,-0.32,-18.36,135.84,92.54,111969.0,-18536.0,82427.0,4520.85,-12.57,56.0,H-SC,13.85,142.0,-0.17,0.52,56.52,SR,ATH,CHEMICALS
12,BOSCH-HCIL,-1.83,-27.52,37.95,-0.01,35155.0,-35170.0,92635.0,2282.00,18856.52,72.0,M-SC,4.98,231.0,-1.00,0.59,57.68,OX40N,BTT,AC
82,VALIANTORG,-4.99,-32.56,158.24,74.15,174586.0,-53275.0,110330.0,838.00,-298.38,67.0,H-SC,5.61,145.0,-0.31,0.70,64.19,XR,NTT,CHEMICALS

In [23]:
# top 5 RSP
df_tmp = df_portfolio_features.sort_values(by = 'RSP', ascending=False)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
12,BOSCH-HCIL,-1.83,-27.52,37.95,-0.01,35155.0,-35170.0,92635.0,2282.00,18856.52,72.0,M-SC,4.98,231.0,-1.00,0.59,57.68,OX40N,BTT,AC
25,FINCABLES,-0.20,57.92,31.66,107.91,73819.0,85517.0,233161.0,1641.55,42.06,72.0,M-SC,18.27,220.0,1.16,1.48,75.42,OX40N,ATH,CABLES
82,VALIANTORG,-4.99,-32.56,158.24,74.15,174586.0,-53275.0,110330.0,838.00,-298.38,67.0,H-SC,5.61,145.0,-0.31,0.70,64.19,XR,NTT,CHEMICALS
33,HCLTECH,-0.73,-9.04,36.28,23.97,102135.0,-27966.0,281520.0,1853.42,-7.36,67.0,X-LC,12.08,8.0,-0.27,1.79,32.84,X40,ATH,IT
57,QUESS,1.38,38.54,25.52,73.90,37758.0,41163.0,147956.0,424.00,-25.62,70.0,X-SC,42.11,80.0,1.09,0.94,103.64,XY24,NTT,MISC

In [24]:
# Top N allocation
df_tmp = df_portfolio_features.sort_values(by = 'CurrAlloc%', ascending=False)
top_n_values = [10, 25, 50]

sum_df = pd.DataFrame({
    'Top_N': top_n_values,
    'Sum_Alloc%': [df_tmp['CurrAlloc%'].head(n).sum() for n in top_n_values]
})

sum_df

   Top_N  Sum_Alloc%
0     10       19.73
1     25       44.79
2     50       76.89

In [25]:
# market-cap-wise allocation
df_tmp = df_portfolio_features[cols]
df_tmp.groupby(df_tmp['Conviction'].str[-2:])['CurrAlloc%'].sum().sort_values(ascending=False)

Conviction
SC    39.35
LC    37.63
MC    23.03
Name: CurrAlloc%, dtype: float64

In [26]:
# criteria-wise allocation
df_portfolio_features.groupby('Criteria')['CurrAlloc%'].sum().sort_values(ascending=False)

Criteria
X40      26.48
XY24     24.82
X40N     18.38
XR        9.01
XY25      7.24
OX40N     7.16
AR        6.08
SR        0.84
Name: CurrAlloc%, dtype: float64

In [27]:
# conviction-wise allocation
df_portfolio_features.groupby('Conviction')['CurrAlloc%'].sum().sort_values(ascending=False)

Conviction
X-LC    35.57
H-SC    19.17
X-MC    18.87
M-SC    11.14
X-SC     8.55
H-MC     2.62
H-LC     1.25
M-MC     1.17
M-LC     0.81
L-SC     0.49
L-MC     0.37
Name: CurrAlloc%, dtype: float64

In [28]:
# sector-wise stats
df_tmp = df_portfolio_features.groupby('Category')[['CurrAlloc%', 'Current', 'Current P/L', 'FTT Amt']].sum().sort_values(by=['Current', 'Current P/L'], ascending=False)
df_tmp['Current P/L%'] = round(df_tmp['Current P/L'] * 100 / df_tmp['Current'], 2)
df_tmp['FTT%'] = round(df_tmp['FTT Amt'] * 100 / df_tmp['Current'], 2)
cols = ['CurrAlloc%', 'Current P/L%', 'FTT%']
df_tmp[cols].sort_values(by=['CurrAlloc%'], ascending=False)

               CurrAlloc%  Current P/L%    FTT%
Category
FMCG                15.39        -23.24   67.55
IT                  11.18        -35.46  102.69
FINANCE             10.59        -15.65   65.47
AUTO                 8.22         -4.46   41.87
MISC                 6.93        -23.01   75.79
BANKS                6.05        -11.93   60.20
PHARMA               5.68          7.40   18.86
INSURANCE            5.63         -4.67   41.68
PAINTS               5.46        -14.50   34.03
ELECTRICAL           4.16         -7.83   45.58
AC                   1.85         -9.92   39.72
REFINERIES           1.70        -11.54   49.01
BREWERIES            1.68         11.37    7.03
FOOTWEAR             1.66        -68.88  136.60
APPARELS             1.63         -4.33   39.37
CABLES               1.48         36.68   31.66
DURABLES             1.48        -67.33  108.04
TRAVEL               1.43        -99.13  198.84
CERAMICS             1.34        -45.70   89.97
CHEMICALS            1.22        -37.25  148.66
ENGINEERING          1.20        -27.77   86.20
CEMENT               1.01        -69.09  195.60
JEWELLERY            0.96       -112.75  186.66
ENTERTAINMENT        0.68        -79.51  186.58
HEALTHCARE           0.67        -70.94  113.85
TEXTILES             0.38        -53.45   97.21
HOTELS               0.35       -105.21  177.59

In [29]:
# money to be made criteria-wise
df_portfolio_features.groupby('Criteria')['FTT Amt'].agg(['sum', 'count']).sort_values(by='sum', ascending=False)

                sum  count
Criteria
XY24      3605181.0     20
X40       2056737.0     18
XR        1377144.0     13
X40N      1185934.0     12
AR        1073842.0      8
OX40N      666618.0     10
XY25       560871.0      5
SR         283073.0      2

In [30]:
# money to be made conviction-wise
df_portfolio_features.groupby('Conviction')['FTT Amt'].agg(['sum', 'count']).sort_values(by='sum', ascending=False)

                  sum  count
Conviction
H-SC        3331161.0     23
X-LC        2457086.0     20
M-SC        1501120.0     15
X-MC        1483260.0     14
X-SC        1233320.0      8
H-MC         284632.0      2
L-SC         213907.0      2
M-LC         164019.0      1
M-MC          61042.0      1
L-MC          44413.0      1
H-LC          35440.0      1

In [31]:
# money to be made criteria and conviction-wise
df_portfolio_features.groupby(['Conviction', 'Criteria'])['FTT Amt'].agg(['sum', 'count']).sort_values(by='sum', ascending=False)

                           sum  count
Conviction Criteria
X-LC       X40       1182245.0      9
H-SC       XY24      1005755.0      5
M-SC       XY24       975884.0      7
H-SC       AR         929301.0      5
           XR         815677.0      7
X-SC       XY24       707222.0      3
X-MC       X40        661877.0      7
X-LC       X40N       525646.0      6
           XY24       440792.0      2
X-MC       X40N       346805.0      3
X-SC       X40N       313483.0      3
H-SC       OX40N      297355.0      4
           SR         283073.0      2
M-SC       OX40N      253624.0      5
H-MC       XY24       251516.0      1
X-MC       XY25       250566.0      2
X-LC       XY25       249263.0      2
X-MC       XY24       224012.0      2
X-SC       X40        212615.0      2
M-SC       XR         195627.0      2
M-LC       XR         164019.0      1
L-SC       OX40N      115639.0      1
           XR          98268.0      1
M-SC       AR          75985.0      1
M-MC       XY25        61042.0      1
X-LC       XR          59140.0      1
L-MC       XR          44413.0      1
H-LC       AR          35440.0      1
H-MC       AR          33116.0      1

In [32]:
# notebook execution time

end_time = time.time()
execution_time = round(end_time - start_time, 0)
print(f"Notebook execution time: {execution_time} seconds")

Notebook execution time: 29.0 seconds