<a href="https://colab.research.google.com/github/ankit-rathi/Quantvesting_v2/blob/main/myStocks_Portfolio_Analysis.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
'''
!pip install pandas==2.2.2 -qq
!pip install pyxirr -qq
!pip install ta -qq
!pip install yfinance==0.2.59 -qq
'''

'\n!pip install pandas==2.2.2 -qq\n!pip install pyxirr -qq\n!pip install ta -qq\n!pip install yfinance==0.2.59 -qq\n'

In [2]:
# import libraries

import numpy as np
import pandas as pd
import datetime
import warnings
warnings.filterwarnings('ignore')
import yfinance as yfin
import ta
import matplotlib.pyplot as plt
import requests

In [3]:
# notebook start time
import time
import datetime
import pytz

start_time = time.time()

# function to print date timestamp
def print_date_time():
  tz_NY = pytz.timezone('Asia/Kolkata')
  datetime_NY = datetime.datetime.now(tz_NY)
  print("Run date time (IST):", datetime_NY.strftime("%Y-%m-%d %H:%M:%S"))

In [4]:
# function to get booked and reserved amount
def get_amt():
  # fetch the JSON data from the URL
  url = "https://raw.githubusercontent.com/ankit-rathi/Tradevesting_v1/main/data/myPortfolioAmts.json"
  response = requests.get(url)
  pf_amts = response.json()  # parse the JSON data

  # extract values from the JSON
  py_booked_amt_dm = pf_amts["py_booked_amt_dm"]
  py_booked_amt_sv = pf_amts["py_booked_amt_sv"]
  cy_booked_amt_dm = pf_amts["cy_booked_amt_dm"]
  cy_booked_amt_sv = pf_amts["cy_booked_amt_sv"]
  reserve_amt_dm = pf_amts["reserve_amt_dm"]
  reserve_amt_sv = pf_amts["reserve_amt_sv"]

  # perform calculations
  py_booked_amt = py_booked_amt_dm + py_booked_amt_sv
  cy_booked_amt = cy_booked_amt_dm + cy_booked_amt_sv
  reserve_amt = reserve_amt_dm + reserve_amt_sv
  total_booked_amt = py_booked_amt + cy_booked_amt

  return total_booked_amt, reserve_amt, cy_booked_amt, py_booked_amt

gen_output = 0

In [5]:
# function to format the amount
def format_amt(number):
    abs_number = abs(number)

    if abs_number >= 1_00_00_000:  # Crores
        formatted_amt = f"{number / 1_00_00_000:.2f} C"
    elif abs_number >= 1_00_000:  # Lakhs
        formatted_amt = f"{number / 1_00_000:.2f} L"
    elif abs_number >= 1_000:  # Thousands
        formatted_amt = f"{number / 1_000:.2f} K"
    else:
        formatted_amt = f"{number:.2f}"

    return formatted_amt

# function to set start and end date
def get_start_end_date():
  start_date = (datetime.date.today() + datetime.timedelta(days=-365)).strftime('%Y-%m-%d')
  end_date = (datetime.date.today() + datetime.timedelta(days=1)).strftime('%Y-%m-%d')
  return start_date, end_date

# function to fetch my portfolio csv
def get_mypfs_df():
  mypfs_df = pd.read_csv('https://raw.githubusercontent.com/ankit-rathi/Tradevesting_v1/main/data/myPortfolioStocks.csv')
  return mypfs_df

# function to fetch my prospects csv
def get_mypps_df():
  mypps_df = pd.read_csv('https://raw.githubusercontent.com/ankit-rathi/Tradevesting_v1/main/data/myProspectsScrips.csv')
  return mypps_df

# function to fetch screener data
def get_myscreen_df():
  myscreen_df = pd.read_csv('https://raw.githubusercontent.com/ankit-rathi/Tradevesting_v1/main/data/myScreenerDB.csv')
  return myscreen_df

# function to fetch momentum data
def get_myinvmt_df():
  myinvmt_df = pd.read_csv('https://raw.githubusercontent.com/ankit-rathi/Tradevesting_v1/main/data/myInvestments.csv')
  return myinvmt_df

# function to get the stock ids
def get_stock_ids(df_pf):
  stock_n100 = df_pf['Symbol'].unique()

  exclude = ['CADILAHC','MMTC', 'MASFIN']

  stock_ids = df_pf[~df_pf['Symbol'].isin(exclude) ]['Symbol'].unique()

  #mypf = mypf[mypf.Forecast.notnull()]
  #stock_ids = mypf['Symbol'].unique()

  #stock_ids.sort()
  return stock_ids

# get features from screener data
def get_screener_features():
  myscreen_df = get_myscreen_df()
  cols = ['Symbol', 'EPS', 'MedPE', 'ROCE%', 'ROE%', 'CapType']
  return myscreen_df[cols]

# get relative strength
def get_relative_strength(stock_list):

    # Dictionary to store stock tickers and their corresponding percentage price change
    stock_changes = {}

    # Loop through each stock and fetch its price data
    for stock in stock_list:
        try:
            # Download the stock data for the given date range
            stock_data = yfin.Ticker(stock + '.NS').history(period='1mo', interval='1d')[map(str.title, ['open', 'close', 'low', 'high', 'volume'])]

            # Calculate the percentage change for the stock
            if len(stock_data) > 0:
                start_price = stock_data['Close'].iloc[0]
                end_price = stock_data['Close'].iloc[-1]
                percent_change = round(((end_price - start_price) / start_price) * 100, 2)
                stock_changes[stock] = percent_change
            else:
                stock_changes[stock] = np.nan  # If no data is available, set to NaN

        except Exception as e:
            print(f"Error fetching data for {stock}: {e}")
            stock_changes[stock] = np.nan

    # Create a DataFrame with stock tickers and their percentage changes
    df = pd.DataFrame(list(stock_changes.items()), columns=['Symbol', 'Percent_Change'])

    # Drop any stocks with missing data (NaN values)
    df = df.dropna()

    # Calculate the percentile rank based on percentage change
    df['RSP'] = round(df['Percent_Change'].rank(pct=True) * 100, 2)
    cols = ['Symbol', 'RSP']
    df = df[cols]
    # Sort by percentile rank (optional)
    df = df.sort_values(by='RSP', ascending=False).reset_index(drop=True)

    return df

In [6]:
# function to get stock technicals
def stock_prec_dev(stock_symbol):
    #stock_symbol = 'ULTRACEMCO.NS'
    short_window = 20
    mid_window = 50
    long_window = 200
    moving_avg = 'SMA'

    start = datetime.datetime(*map(int, start_date.split('-')))
    end = datetime.datetime(*map(int, end_date.split('-')))

    stock_df = yfin.Ticker(stock_symbol + '.NS').history(period='max', interval='1d')[map(str.title, ['open', 'close', 'low', 'high', 'volume'])]

    stock_df['Max'] = round(max(stock_df['Close']),2)
    stock_df = stock_df[(stock_df.index <= end_date) & (stock_df.index >= start_date)]
    stock_df['200_SMA'] = round(stock_df['Close'].rolling(window = 200, min_periods = 1).mean(),0)
    stock_df['Dev%_200'] = round((stock_df['Close'] - stock_df['200_SMA'])*100/stock_df['200_SMA'],2)
    stock_df.dropna(axis = 0, inplace = True) # remove any null rows

    stock_df['20_SMA'] = stock_df['Close'].rolling(window=20).mean()
    stock_df['50_SMA'] = stock_df['Close'].rolling(window=50).mean()
    stock_df['Symbol'] = stock_symbol

    stock_df['Close'] = round(stock_df['Close'],2)
    stock_df['Min'] = round(min(stock_df['Close']),2)
    stock_df['RSI_14'] = ta.momentum.RSIIndicator(close=stock_df['Close'], window=14).rsi()
    stock_df['RSI_14'] = round(stock_df['RSI_14'],0)
    stock_df['Prev_Close'] = stock_df['Close'].shift(1)
    stock_df.drop(['Open', 'Low', 'High', 'Volume'], axis=1, inplace=True)
    stock_df = stock_df.tail(1)

    max_SMA = max(stock_df['20_SMA'].item(), stock_df['50_SMA'].item(), stock_df['200_SMA'].item())
    min_SMA = min(stock_df['20_SMA'].item(), stock_df['50_SMA'].item(), stock_df['200_SMA'].item())
    ABS_Spread = max_SMA - min_SMA
    stock_df['Spread%'] = round((ABS_Spread / stock_df['200_SMA'].item()) * 100,2)

    return stock_df

# function to compute stock attributes
def get_common_features(stock_ids, df_mypf):

  df_prec_dev = pd.DataFrame()
  df_tmp = get_screener_features()
  df_rs = get_relative_strength(stock_ids)

  for stock_id in stock_ids:
      tmp = stock_prec_dev(stock_id)
      tmp = tmp.reset_index()
      df_prec_dev = pd.concat([df_prec_dev, tmp], ignore_index = True)
  df_prec_dev = pd.merge(df_prec_dev, df_mypf, on= 'Symbol')
  df_prec_dev = pd.merge(df_prec_dev, df_tmp, on= 'Symbol', how='left')
  df_prec_dev = pd.merge(df_prec_dev, df_rs, on= 'Symbol', how='left')
  #print(df_prec_dev.columns)
  df_prec_dev['Curr_PE'] = round(df_prec_dev['Close']/df_prec_dev['EPS'],1)
  df_prec_dev['Dev%_PE'] = round((df_prec_dev['Curr_PE'] - df_prec_dev['MedPE'])*100/df_prec_dev['MedPE'],2)
  df_prec_dev['Conviction'] = df_prec_dev['Conviction'] + '-' + df_prec_dev['CapType']
  return df_prec_dev

# function to arrange stock features
def arrange_features(df_stocks, common_cols, diff_cols):
  df_stocks_common = df_stocks[common_cols].drop_duplicates()
  df_stocks_diff = df_stocks[diff_cols]
  df_stocks_diff['Investment'] = df_stocks_diff['AvgCost'] * df_stocks_diff['Shares']
  df_stocks_diff = df_stocks_diff.groupby(['Symbol'])[['Shares', 'Investment']].aggregate(['sum']).reset_index()
  df_stocks_diff.columns = ['Symbol', 'Shares', 'Investment']
  df_stocks_diff['AvgCost'] = round(df_stocks_diff['Investment']/df_stocks_diff['Shares'],2)
  df_stocks = pd.merge(df_stocks_diff, df_stocks_common, on='Symbol')
  return df_stocks

# plot fact distribution across dimension
def plot_pie_chart(df, dimension, fact):
  # grouping the data by category and calculating the sum of fact for each type
  grouped_data = df.groupby(dimension)[fact].sum()

  # sorting the grouped data in descending order
  grouped_data = grouped_data.sort_values(ascending=False)

  # creating a pie chart
  grouped_data.plot.pie(autopct='%1.1f%%', startangle=90, figsize=(6, 6))

  # adding a title and displaying the plot
  plt.title(f'{dimension} {fact} Distribution')
  plt.ylabel('')  # To hide the y-label
  plt.show()

In [7]:
# function to get portfolio features

def get_portfolio_features(df_common_features):

  print_date_time()
  print('-------------------')

  #df_common_features["Target"] = df_common_features["Target"].fillna(df_common_features["Max"])
  df_common_features['NTT'] = np.where(df_common_features['Strategy']== 'NTT', df_common_features["Target"], df_common_features['Max'])
  df_common_features['LTT'] = np.where(df_common_features['Strategy']== 'BTT', df_common_features["Target"], df_common_features['Max'])
  df_common_features['BOL'] = df_common_features['Min']

  tmp_df = df_common_features[df_common_features['Symbol'].isin(mypf_df[mypf_df['InPortfolio'] != 'NA'].Symbol.values)]
  print('qualified stocks: '+str(len(tmp_df['Symbol'].unique())))
  tmp_df1 = tmp_df[tmp_df['LatestQtr'] == 1]
  print('with latest results: '+str(len(tmp_df1['Symbol'].unique())))
  tmp_df1 = tmp_df1[tmp_df1['StarStock'] == 1]
  print('still star stocks: '+str(len(tmp_df1['Symbol'].unique())))
  tmp_df['Investment'] = tmp_df['AvgCost'] * tmp_df['Shares']
  tmp_df['Current'] = round(tmp_df['Close'] * tmp_df['Shares'],0)
  tmp_df['Previous'] = tmp_df['Prev_Close'] * tmp_df['Shares']
  tmp_df['EstimatedST'] = tmp_df['NTT'] * tmp_df['Shares']
  tmp_df['EstimatedLT'] = tmp_df['LTT'] * tmp_df['Shares']
  tmp_df['Current P/L'] = round((tmp_df['Current'] - tmp_df['Investment']),0)
  tmp_df['Today P/L%'] = round((tmp_df['Current'] - tmp_df['Previous'])*100/tmp_df['Previous'],2)
  tmp_df['Current P/L%'] = round((tmp_df['Current'] - tmp_df['Investment'])*100/tmp_df['Investment'],2)
  tmp_df['EstimatedST P/L%'] = round((tmp_df['EstimatedST'] - tmp_df['Investment'])*100/tmp_df['Investment'],2)
  tmp_df['EstimatedLT P/L%'] = round((tmp_df['EstimatedLT'] - tmp_df['Investment'])*100/tmp_df['Investment'],2)
  tmp_df['NTT%'] = round((tmp_df['NTT'] - tmp_df['Close'])*100/tmp_df['Close'],2)
  tmp_df['LTT%'] = round((tmp_df['LTT'] - tmp_df['Close'])*100/tmp_df['Close'],2)
  tmp_df['Gained%'] = round((tmp_df['Close'] - tmp_df['BOL'])*100/tmp_df['BOL'],2)
  investment = round(sum(tmp_df['AvgCost']*tmp_df['Shares']),0)
  current = round(sum(tmp_df['Close']*tmp_df['Shares']),0)
  tmp_df['InitAlloc%'] = round(tmp_df['Investment']*100/investment,2)
  tmp_df['CurrAlloc%'] = round(tmp_df['Current']*100/current,2)
  tmp_df['FTT'] = tmp_df['LTT']
  tmp_df.loc[tmp_df['Strategy'] == 'NTT', 'FTT'] = tmp_df['NTT']
  tmp_df['FTT%'] = tmp_df['LTT%']
  tmp_df.loc[tmp_df['Strategy'] == 'NTT', 'FTT%'] = tmp_df['NTT%']
  tmp_df['FTT Amt'] = round(tmp_df['FTT%'] * tmp_df['Current']/100,0)
  tmp_df['OTT%'] = round((tmp_df['FTT'] - tmp_df['AvgCost'])*100/tmp_df['AvgCost'],2)
  tmp_df['RRR Ind'] = round(tmp_df['Current P/L']/tmp_df['FTT Amt'],2)
  tmp_df['Risk Ind'] = round(tmp_df['Current P/L%']*tmp_df['CurrAlloc%'],0)

  return tmp_df

# function to print portfolio features
def print_portfolio_stats(df_portfolio_features, myinvmt_df):
  from pyxirr import xirr

  total_booked_amt, reserve_amt, cy_booked_amt, py_booked_amt = get_amt()

  dates = myinvmt_df['Date'].values
  dates = np.append(dates, datetime.date.today().strftime('%d-%b-%y'))
  investment = myinvmt_df['Investment'].values
  dates= pd.to_datetime(dates)

  current = round(sum(df_portfolio_features['Close']*df_portfolio_features['Shares']),0) + reserve_amt
  investment_xirr = np.append(investment, current)
  cagr = round(xirr(pd.DataFrame({"dates": dates, "amounts": investment_xirr}))*100,2)

  investment = -sum(investment)
  invested = round(sum(df_portfolio_features['AvgCost']*df_portfolio_features['Shares']),0) + reserve_amt
  previous = round(sum(df_portfolio_features['Prev_Close']*df_portfolio_features['Shares']),0) + reserve_amt
  cy_invested = investment + py_booked_amt

  today_pnl_amount = current-previous
  today_pnl_percentage = round((current-previous)*100/previous,2)

  curr_pnl_amount = current-invested
  curr_pnl_percentage = round((curr_pnl_amount)*100/(cy_invested),2)

  cy_pnl_amount = cy_booked_amt + curr_pnl_amount
  cy_pnl_percentage = round((cy_pnl_amount)*100/cy_invested,2)

  overall_pnl_amount = total_booked_amt + curr_pnl_amount
  overall_pnl_percentage = round((overall_pnl_amount)*100/investment,2)

  estimate_st = round(sum(df_portfolio_features['FTT']*df_portfolio_features['Shares']),0)  + reserve_amt
  est_st_pnl_amount = estimate_st-current
  est_st_pnl_percentage = round((est_st_pnl_amount)*100/current,2)

  estimate_lt = round(sum(df_portfolio_features['LTT']*df_portfolio_features['Shares']),0)  + reserve_amt
  est_lt_pnl_amount = estimate_lt-current
  est_lt_pnl_percentage = round((est_lt_pnl_amount)*100/current,2)

  total_profit = round(sum(df_portfolio_features[df_portfolio_features['Current P/L%'] > 0]['Current']) - sum(df_portfolio_features[df_portfolio_features['Current P/L%'] > 0]['Investment']),0)
  total_loss = round(sum(df_portfolio_features[df_portfolio_features['Current P/L%'] < 0]['Current']) - sum(df_portfolio_features[df_portfolio_features['Current P/L%'] < 0]['Investment']),0)

  cy_booked_percentage = round((cy_booked_amt)*100/current,2)
  py_booked_percentage = round((py_booked_amt)*100/investment,2)
  total_booked_percentage = round((total_booked_amt)*100/investment,2)

  print('-------------------')
  print('Initial Investment: ', format_amt(investment))
  print('CY Investment: ', format_amt(cy_invested))
  print('Reserve: ', format_amt(reserve_amt))
  print('Current: ',  format_amt(current))
  print('-------------------')
  print('Today PnL: '+ '{} ({}%)'.format(format_amt(today_pnl_amount), today_pnl_percentage))
  print('Current PnL: '+ '{} ({}%)'.format(format_amt(curr_pnl_amount), curr_pnl_percentage))
  print('CY Booked + Current PnL: '+ '{} ({}%)'.format(format_amt(cy_pnl_amount), cy_pnl_percentage))
  print('-------------------')
  print('Total profit: ', format_amt(total_profit))
  print('Total loss: ', format_amt(total_loss))
  print('-------------------')
  print('Total Booked + Current PnL: '+ '{} ({}%)'.format(format_amt(overall_pnl_amount), overall_pnl_percentage))
  print('Total Booked PnL: '+ '{} ({}%)'.format(format_amt(total_booked_amt), total_booked_percentage))
  print('Curr Year Booked PnL: '+ '{} ({}%)'.format(format_amt(cy_booked_amt), cy_booked_percentage))
  print('Prev Year Booked PnL: '+ '{} ({}%)'.format(format_amt(py_booked_amt), py_booked_percentage))
  print('===================')
  print('Est FTT: ',  format_amt(estimate_st))
  print('Est FTT PnL: '+ '{} ({}%)'.format(format_amt(est_st_pnl_amount), est_st_pnl_percentage))

  print('===================')
  print('Deployed: ', format_amt(investment))

  print('Current: ', format_amt(current))

  print('CAGR/XIRR %: '+'{}%'.format(cagr))

In [8]:
# get start and end date
start_date, end_date = get_start_end_date()

# get portfolio and prospects data
mypfs_df = get_mypfs_df()
mypps_df = get_mypps_df()
myinvmt_df = get_myinvmt_df()

# merge above datasets
mypf_df = pd.merge(mypfs_df, mypps_df, on="Symbol")

# seggregate dm and sv portfolio
dm_pf = mypf_df[mypf_df['InPortfolio'] == 'DM']
sv_pf = mypf_df[mypf_df['InPortfolio'] == 'SV']

# build portfolio stock dataframe
dm_stocks = get_stock_ids(dm_pf)
sv_stocks = get_stock_ids(sv_pf)
df_stocks = pd.concat([dm_pf,sv_pf], ignore_index = True)

# arrange common and diff stock features
common_cols = ['Symbol', 'Target', 'Criteria', 'Strategy', 'CumlRnk', 'LatestQtr', 'StarStock', 'Conviction', 'Category', 'InFolio', 'XIRR', 'MBQ']
diff_cols = ['Symbol', 'AvgCost', 'Shares']
df_stocks = arrange_features(df_stocks, common_cols, diff_cols)

# get common features
stock_ids = df_stocks['Symbol'].values
df_common_features = get_common_features(stock_ids, df_stocks)

df_common_features.reset_index(drop=True, inplace=True)
df_common_features.drop(['Date'], axis=1, inplace=True)
# get and print portfolio features
df_portfolio_features = get_portfolio_features(df_common_features)

print_portfolio_stats(df_portfolio_features, myinvmt_df)

df = df_portfolio_features
#plot_pie_chart(df, 'CapType', 'Current')
list_ox40n = list(df[df['MBQ'].str.contains('OX40N', na=False)]['Symbol'].values)

Run date time (IST): 2026-06-18 16:38:34
-------------------
qualified stocks: 92
with latest results: 31
still star stocks: 20
-------------------
Initial Investment:  1.40 C
CY Investment:  1.82 C
Reserve:  1.49 K
Current:  1.53 C
-------------------
Today PnL: 1.01 L (0.66%)
Current PnL: -30.44 L (-16.69%)
CY Booked + Current PnL: -28.36 L (-15.55%)
-------------------
Total profit:  3.76 L
Total loss:  -34.20 L
-------------------
Total Booked + Current PnL: 14.51 L (10.4%)
Total Booked PnL: 44.95 L (32.22%)
Curr Year Booked PnL: 2.08 L (1.36%)
Prev Year Booked PnL: 42.87 L (30.73%)
===================
Est FTT:  2.55 C
Est FTT PnL: 1.02 C (67.06%)
===================
Deployed:  1.40 C
Current:  1.53 C
CAGR/XIRR %: 4.25%

In [9]:
# top 5 near their targets
cols = ['Symbol', 'Today P/L%', 'Current P/L%', 'FTT%', 'OTT%', 'FTT Amt', 'Current P/L', 'Current', 'FTT', 'Dev%_PE', 'RSI_14','Conviction', 'Spread%',  'CumlRnk', 'RRR Ind', 'CurrAlloc%', 'Gained%', 'Criteria', 'Strategy', 'Category']
df_tmp = df_portfolio_features[~df_portfolio_features['Symbol'].isin(['ENRIN','BLUSPRING','DIGITIDE'])]
df_tmp = df_tmp.sort_values(by = 'FTT Amt', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
59,PIDILITIND,0.18,12.05,5.64,18.37,8917.0,17000.0,158110.0,1670.26,-21.49,75.0,X-LC,3.78,5.0,1.91,1.04,24.14,X40,ATH,CHEMICALS
51,KOTAKBANK,-0.38,7.67,12.48,21.11,18607.0,10620.0,149092.0,453.24,-7.67,64.0,X-LC,5.63,12.0,0.57,0.98,14.02,X40,ATH,BANKS
55,MASFIN,2.48,-2.01,24.06,21.57,23101.0,-1965.0,96015.0,397.04,-15.54,58.0,H-SC,3.38,167.0,-0.09,0.63,14.45,XR,ATH,FINANCE
49,JSWINFRA,3.20,4.84,11.06,16.43,25715.0,10728.0,232502.0,342.00,-10.21,70.0,X-MC,1.85,61.0,0.42,1.52,31.82,X40N,NTT,REALTY
72,SIS,-0.52,-2.58,24.47,21.26,26469.0,-2861.0,108171.0,528.00,2580.31,61.0,H-SC,22.74,168.0,-0.11,0.71,60.83,OX40N,NTT,MISC

In [10]:
# top 5 today
df_tmp = df_portfolio_features.sort_values(by = 'Today P/L%', ascending=False)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
10,BATAINDIA,16.42,-49.05,165.35,35.20,108407.0,-63108.0,65562.0,2096.0,-14.08,77.0,X-SC,24.42,91.0,-0.58,0.43,30.02,X40,NTT,FOOTWEAR
12,BOSCH-HCIL,10.00,-38.35,62.19,-0.01,49001.0,-49013.0,78792.0,2282.0,16030.43,56.0,M-SC,8.19,231.0,-1.00,0.52,34.11,OX40N,BTT,AC
21,DEN,8.15,-40.69,139.54,42.07,69904.0,-34368.0,50096.0,75.0,78.76,72.0,M-SC,7.93,235.0,-0.49,0.33,36.25,AR,NTT,ENTERTAINMENT
74,STARHEALTH,5.99,9.46,34.54,47.26,106284.0,26591.0,307714.0,761.0,72.69,74.0,H-SC,10.38,173.0,0.25,2.01,35.10,XY24,NTT,INSURANCE
61,RAJESHEXPO,5.00,-82.06,457.77,0.07,112662.0,-112566.0,24611.0,518.0,801.52,43.0,L-SC,35.40,268.0,-1.00,0.16,21.54,OX40N,NTT,JEWELLERY

In [11]:
# bottom 5 today
df_tmp = df_portfolio_features.sort_values(by = 'Today P/L%', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
24,EASEMYTRIP,-3.62,-55.91,230.41,45.70,179641.0,-98849.0,77966.0,26.40,-19.04,53.0,M-SC,4.21,204.0,-0.55,0.51,36.58,XY24,NTT,TRAVEL
45,INFY,-2.61,-23.24,74.90,34.24,179878.0,-72730.0,240158.0,1972.00,-39.77,44.0,X-LC,16.55,3.0,-0.40,1.57,5.20,X40,NTT,IT
87,VBL,-2.30,7.37,26.08,35.37,88445.0,23287.0,339129.0,670.16,-5.20,55.0,X-LC,12.78,13.0,0.26,2.22,39.38,X40N,ATH,FMCG
68,SATIN,-1.77,28.24,18.39,51.83,65159.0,78035.0,354319.0,274.00,14.32,57.0,H-SC,40.24,159.0,1.20,2.32,72.61,XY24,NTT,FINANCE
30,HAPPSTMNDS,-1.39,-56.20,322.04,84.85,180780.0,-72029.0,56136.0,1480.71,-47.93,40.0,H-SC,17.43,152.0,-0.40,0.37,3.96,AR,ATH,IT

In [12]:
# top 5 to exit based on CumlRnk
df_tmp = df_portfolio_features[~df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])]
df_tmp = df_tmp[(df_tmp['Current P/L%'] > -1) & (df_tmp['Current P/L%'] < 1)].sort_values(by = 'CumlRnk', ascending=False)
df_tmp[cols].head()

Empty DataFrame
Columns: [Symbol, Today P/L%, Current P/L%, FTT%, OTT%, FTT Amt, Current P/L, Current, FTT, Dev%_PE, RSI_14, Conviction, Spread%, CumlRnk, RRR Ind, CurrAlloc%, Gained%, Criteria, Strategy, Category]
Index: []

In [13]:
# OX40N stocks to exit
df_tmp = df_portfolio_features[(df_portfolio_features['Symbol'].isin(list_ox40n))].sort_values(by = 'Current P/L%', ascending=False)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
25,FINCABLES,3.45,46.74,41.68,107.91,90303.0,69014.0,216658.0,1641.55,31.91,64.0,M-SC,24.06,220.0,0.76,1.42,63.00,OX40N,ATH,CABLES
72,SIS,-0.52,-2.58,24.47,21.26,26469.0,-2861.0,108171.0,528.00,2580.31,61.0,H-SC,22.74,168.0,-0.11,0.71,60.83,OX40N,NTT,MISC
16,CERA,0.06,-19.46,53.81,23.89,76238.0,-34223.0,141680.0,9475.00,-22.20,66.0,H-SC,5.42,153.0,-0.45,0.93,36.15,OX40N,NTT,CERAMICS
43,INDIGOPNTS,0.57,-27.02,37.06,0.02,47209.0,-47174.0,127385.0,1408.00,94.20,63.0,M-SC,9.78,222.0,-1.00,0.83,44.53,OX40N,NTT,PAINTS
50,KANSAINER,-0.78,-30.09,62.32,13.47,117482.0,-81153.0,188514.0,340.00,-39.99,44.0,H-SC,5.92,162.0,-0.69,1.23,31.68,XY24,NTT,PAINTS

In [14]:
# top 5 to book for rotation
df_tmp = df_portfolio_features[(df_portfolio_features['Current P/L%'] > 20) ].sort_values(by = 'CumlRnk', ascending=False)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
25,FINCABLES,3.45,46.74,41.68,107.91,90303.0,69014.0,216658.0,1641.55,31.91,64.0,M-SC,24.06,220.0,0.76,1.42,63.00,OX40N,ATH,CABLES
68,SATIN,-1.77,28.24,18.39,51.83,65159.0,78035.0,354319.0,274.00,14.32,57.0,H-SC,40.24,159.0,1.20,2.32,72.61,XY24,NTT,FINANCE

In [15]:
# top 5 to monitor for exit
df_tmp = df_portfolio_features[~df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])]
df_tmp = df_tmp[(df_tmp['Current P/L%'] > 0) ].sort_values(by = 'Dev%_PE', ascending=False)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
9,BANDHANBNK,0.24,3.08,86.67,92.42,248860.0,8576.0,287135.0,400.00,146.41,62.0,H-SC,23.00,174.0,0.03,1.88,58.18,XY24,NTT,BANKS
74,STARHEALTH,5.99,9.46,34.54,47.26,106284.0,26591.0,307714.0,761.00,72.69,74.0,H-SC,10.38,173.0,0.25,2.01,35.10,XY24,NTT,INSURANCE
25,FINCABLES,3.45,46.74,41.68,107.91,90303.0,69014.0,216658.0,1641.55,31.91,64.0,M-SC,24.06,220.0,0.76,1.42,63.00,OX40N,ATH,CABLES
68,SATIN,-1.77,28.24,18.39,51.83,65159.0,78035.0,354319.0,274.00,14.32,57.0,H-SC,40.24,159.0,1.20,2.32,72.61,XY24,NTT,FINANCE
91,ZYDUSLIFE,1.22,13.30,19.71,35.63,46800.0,27868.0,237442.0,1286.17,-1.35,57.0,H-MC,13.55,120.0,0.60,1.55,24.84,AR,ATH,PHARMA

In [16]:
# top 5 to book for rotation from weak conviction
df_tmp = df_portfolio_features[~df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])]
df_tmp = df_tmp[~df_tmp['Criteria'].isin(['XY25','XY24','X40', 'X40N'])].sort_values(by = 'RRR Ind', ascending=False)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
25,FINCABLES,3.45,46.74,41.68,107.91,90303.0,69014.0,216658.0,1641.55,31.91,64.0,M-SC,24.06,220.0,0.76,1.42,63.00,OX40N,ATH,CABLES
91,ZYDUSLIFE,1.22,13.30,19.71,35.63,46800.0,27868.0,237442.0,1286.17,-1.35,57.0,H-MC,13.55,120.0,0.60,1.55,24.84,AR,ATH,PHARMA
73,SONACOMS,0.63,4.67,32.88,39.09,34815.0,4725.0,105884.0,804.02,-17.09,56.0,M-MC,18.53,193.0,0.14,0.69,49.79,AR,ATH,AUTO
75,SURYODAY,1.69,-1.21,24.55,23.03,43429.0,-2172.0,176899.0,216.00,92.98,59.0,H-SC,18.37,166.0,-0.05,1.16,48.94,XR,NTT,BANKS
42,INDIAMART,2.28,-8.14,125.04,106.72,141668.0,-10038.0,113298.0,4810.62,-58.59,69.0,H-SC,9.33,140.0,-0.07,0.74,9.68,AR,ATH,MISC

In [17]:
# top 5 to accumulate based on lowest RSI_14
df_tmp = df_portfolio_features[df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])].sort_values(by = 'RSI_14', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
58,PGHH,0.11,-32.52,95.63,32.01,137784.0,-69440.0,144080.0,17616.87,-54.37,33.0,X-MC,19.69,57.0,-0.50,0.94,0.14,X40,ATH,FMCG
20,DABUR,-0.07,-16.18,71.45,43.70,148559.0,-40148.0,207920.0,735.00,-23.90,44.0,X-MC,11.28,70.0,-0.27,1.36,4.45,XY24,BTT,FMCG
79,TCS,-0.89,-35.32,93.07,24.88,278883.0,-163624.0,299649.0,4253.91,-45.26,44.0,X-LC,18.97,2.0,-0.59,1.96,3.17,X40,ATH,IT
45,INFY,-2.61,-23.24,74.90,34.24,179878.0,-72730.0,240158.0,1972.00,-39.77,44.0,X-LC,16.55,3.0,-0.40,1.57,5.20,X40,NTT,IT
81,TMPV,1.02,-16.99,64.54,36.58,190629.0,-60475.0,295366.0,600.00,-82.53,44.0,X-LC,11.84,4.0,-0.32,1.93,23.11,XY24,NTT,AUTO

In [18]:
# top 5 to accumulate based on Spread and CumlRnk
df_tmp = df_portfolio_features[df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])]
df_tmp = df_tmp[(df_tmp['CumlRnk'] < 100)].sort_values(by = 'Spread%', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
49,JSWINFRA,3.20,4.84,11.06,16.43,25715.0,10728.0,232502.0,342.00,-10.21,70.0,X-MC,1.85,61.0,0.42,1.52,31.82,X40N,NTT,REALTY
11,BERGEPAINT,-1.30,-6.93,34.64,25.32,83101.0,-17850.0,239899.0,680.00,-11.94,51.0,X-MC,2.99,68.0,-0.21,1.57,24.86,XY24,NTT,PAINTS
57,PAGEIND,2.24,4.80,27.47,33.59,77262.0,12881.0,281260.0,51217.29,-24.88,66.0,X-MC,3.37,55.0,0.17,1.84,33.57,X40,ATH,APPARELS
19,COLPAL,-0.34,-23.02,81.69,39.86,165610.0,-60635.0,202730.0,3683.41,-6.75,46.0,X-MC,3.41,62.0,-0.37,1.33,14.68,XY25,ATH,FMCG
56,MEDANTA,0.30,7.63,18.11,27.12,34407.0,13471.0,189988.0,1486.00,4.31,61.0,X-SC,3.62,87.0,0.39,1.24,30.91,XY24,NTT,HEALTHCARE

In [19]:
# top 5 to accumulate based on lowest Gained%
df_tmp = df_portfolio_features[df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])].sort_values(by = 'Gained%', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
58,PGHH,0.11,-32.52,95.63,32.01,137784.0,-69440.0,144080.0,17616.87,-54.37,33.0,X-MC,19.69,57.0,-0.50,0.94,0.14,X40,ATH,FMCG
28,GODREJCP,-1.06,-9.68,45.56,31.47,61152.0,-14390.0,134224.0,1469.04,-4.99,45.0,X-LC,9.48,32.0,-0.24,0.88,2.99,X40N,ATH,FMCG
79,TCS,-0.89,-35.32,93.07,24.88,278883.0,-163624.0,299649.0,4253.91,-45.26,44.0,X-LC,18.97,2.0,-0.59,1.96,3.17,X40,ATH,IT
1,ABBOTINDIA,0.73,-12.29,34.61,18.07,54293.0,-21985.0,156870.0,35195.00,-25.27,45.0,X-MC,5.80,58.0,-0.40,1.03,3.83,X40,ATH,PHARMA
20,DABUR,-0.07,-16.18,71.45,43.70,148559.0,-40148.0,207920.0,735.00,-23.90,44.0,X-MC,11.28,70.0,-0.27,1.36,4.45,XY24,BTT,FMCG

In [20]:
# top 5 to accumulate based on lowest CurrAlloc%
df_tmp = df_portfolio_features[df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])].sort_values(by = 'CurrAlloc%', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
10,BATAINDIA,16.42,-49.05,165.35,35.20,108407.0,-63108.0,65562.0,2096.00,-14.08,77.0,X-SC,24.42,91.0,-0.58,0.43,30.02,X40,NTT,FOOTWEAR
64,RELAXO,0.99,-52.36,219.70,52.31,151936.0,-76004.0,69156.0,1176.00,-49.28,70.0,X-SC,16.91,92.0,-0.50,0.45,54.62,X40N,NTT,FOOTWEAR
60,QUESS,0.27,2.51,69.64,73.90,76238.0,2681.0,109474.0,424.00,-44.90,78.0,X-SC,7.02,80.0,0.04,0.72,49.24,XY24,NTT,MISC
28,GODREJCP,-1.06,-9.68,45.56,31.47,61152.0,-14390.0,134224.0,1469.04,-4.99,45.0,X-LC,9.48,32.0,-0.24,0.88,2.99,X40N,ATH,FMCG
53,M&M,0.11,1.77,21.23,23.38,29964.0,2461.0,141142.0,3802.40,-13.74,56.0,X-LC,10.42,25.0,0.08,0.92,7.01,X40N,ATH,AUTO

In [21]:
# top 5 to accumulate based on CumlRnk
df_tmp = df_portfolio_features.sort_values(by = 'CumlRnk', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
47,ITC,0.14,-23.31,55.25,19.06,144131.0,-79296.0,260870.0,452.00,-57.95,53.0,X-LC,15.28,1.0,-0.55,1.71,5.11,X40,NTT,FMCG
79,TCS,-0.89,-35.32,93.07,24.88,278883.0,-163624.0,299649.0,4253.91,-45.26,44.0,X-LC,18.97,2.0,-0.59,1.96,3.17,X40,ATH,IT
45,INFY,-2.61,-23.24,74.90,34.24,179878.0,-72730.0,240158.0,1972.00,-39.77,44.0,X-LC,16.55,3.0,-0.40,1.57,5.20,X40,NTT,IT
81,TMPV,1.02,-16.99,64.54,36.58,190629.0,-60475.0,295366.0,600.00,-82.53,44.0,X-LC,11.84,4.0,-0.32,1.93,23.11,XY24,NTT,AUTO
59,PIDILITIND,0.18,12.05,5.64,18.37,8917.0,17000.0,158110.0,1670.26,-21.49,75.0,X-LC,3.78,5.0,1.91,1.04,24.14,X40,ATH,CHEMICALS

In [22]:
# top 5 for average up
df_tmp = df_portfolio_features[(df_portfolio_features['Dev%_200'] > 5)].sort_values(by = 'CurrAlloc%', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
44,INDUSINDBK,0.27,-30.69,91.74,32.89,49089.0,-23698.0,53509.0,1800.00,-352.10,59.0,L-MC,7.59,258.0,-0.48,0.35,31.71,XR,NTT,BANKS
3,ALKYLAMINE,-1.39,-23.71,153.82,93.63,118475.0,-23941.0,77022.0,4546.37,-18.23,55.0,H-SC,7.05,142.0,-0.20,0.50,45.44,SR,ATH,CHEMICALS
86,VALIANTORG,-0.06,-35.43,169.71,74.15,179278.0,-57967.0,105638.0,838.00,-290.27,61.0,H-SC,3.11,145.0,-0.32,0.69,57.21,XR,NTT,CHEMICALS
73,SONACOMS,0.63,4.67,32.88,39.09,34815.0,4725.0,105884.0,804.02,-17.09,56.0,M-MC,18.53,193.0,0.14,0.69,49.79,AR,ATH,AUTO
72,SIS,-0.52,-2.58,24.47,21.26,26469.0,-2861.0,108171.0,528.00,2580.31,61.0,H-SC,22.74,168.0,-0.11,0.71,60.83,OX40N,NTT,MISC

In [23]:
# top 5 RSP
df_tmp = df_portfolio_features.sort_values(by = 'RSP', ascending=False)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
18,COFFEEDAY,1.20,-41.55,131.41,35.27,87222.0,-47175.0,66374.0,80.00,-55.73,58.0,L-SC,14.33,266.0,-0.54,0.43,63.68,XR,NTT,HOTELS
37,HONAUT,2.17,-3.62,57.00,51.31,105934.0,-6988.0,185850.0,58357.33,-19.81,67.0,X-SC,9.00,90.0,-0.07,1.22,41.20,X40N,ATH,ELECTRICAL
64,RELAXO,0.99,-52.36,219.70,52.31,151936.0,-76004.0,69156.0,1176.00,-49.28,70.0,X-SC,16.91,92.0,-0.50,0.45,54.62,X40N,NTT,FOOTWEAR
60,QUESS,0.27,2.51,69.64,73.90,76238.0,2681.0,109474.0,424.00,-44.90,78.0,X-SC,7.02,80.0,0.04,0.72,49.24,XY24,NTT,MISC
80,TITAGARH,1.33,-12.20,65.99,45.74,140317.0,-29544.0,212633.0,1548.00,17.03,71.0,H-SC,6.03,175.0,-0.21,1.39,62.23,XY24,NTT,ENGINEERING

In [24]:
# Top N allocation
df_tmp = df_portfolio_features.sort_values(by = 'CurrAlloc%', ascending=False)
top_n_values = [10, 25, 50]

sum_df = pd.DataFrame({
    'Top_N': top_n_values,
    'Sum_Alloc%': [df_tmp['CurrAlloc%'].head(n).sum() for n in top_n_values]
})

sum_df

   Top_N  Sum_Alloc%
0     10       19.51
1     25       42.74
2     50       72.70

In [25]:
# market-cap-wise allocation
df_tmp = df_portfolio_features[cols]
df_tmp.groupby(df_tmp['Conviction'].str[-2:])['CurrAlloc%'].sum().sort_values(ascending=False)

Conviction
SC    43.49
LC    30.88
MC    25.61
Name: CurrAlloc%, dtype: float64

In [26]:
# criteria-wise allocation
df_portfolio_features.groupby('Criteria')['CurrAlloc%'].sum().sort_values(ascending=False)

Criteria
XY24     27.57
X40      24.90
X40N     17.33
XR        9.00
OX40N     7.01
AR        6.79
XY25      6.52
SR        0.86
Name: CurrAlloc%, dtype: float64

In [27]:
# conviction-wise allocation
df_portfolio_features.groupby('Conviction')['CurrAlloc%'].sum().sort_values(ascending=False)

Conviction
X-LC    28.82
H-SC    22.80
X-MC    20.61
M-SC    10.08
X-SC    10.02
H-MC     2.67
M-MC     1.98
H-LC     1.23
M-LC     0.83
L-SC     0.59
L-MC     0.35
Name: CurrAlloc%, dtype: float64

In [28]:
# sector-wise stats
df_tmp = df_portfolio_features.groupby('Category')[['CurrAlloc%', 'Current', 'Current P/L', 'FTT Amt']].sum().sort_values(by=['Current', 'Current P/L'], ascending=False)
df_tmp['Current P/L%'] = round(df_tmp['Current P/L'] * 100 / df_tmp['Current'], 2)
df_tmp['FTT%'] = round(df_tmp['FTT Amt'] * 100 / df_tmp['Current'], 2)
cols = ['CurrAlloc%', 'Current P/L%', 'FTT%']
df_tmp[cols].sort_values(by=['CurrAlloc%'], ascending=False)

               CurrAlloc%  Current P/L%    FTT%
Category
FMCG                14.67        -18.12   59.55
FINANCE             10.84        -11.31   59.72
IT                   9.96        -47.98  121.97
MISC                 7.23        -21.66   74.51
AUTO                 6.61         -8.16   48.72
BANKS                5.84         -1.91   49.03
PAINTS               5.47        -17.76   38.21
INSURANCE            5.35         -1.26   35.51
PHARMA               4.87          0.38   30.46
ELECTRICAL           4.09        -13.29   53.27
CHEMICALS            2.23        -19.05   89.99
HEALTHCARE           2.01        -16.08   46.37
AC                   1.85        -13.14   43.82
APPARELS             1.84          4.58   27.47
FOOTWEAR             1.78        -62.62  127.82
TRAVEL               1.63        -79.80  169.83
DURABLES             1.54        -64.99  105.13
REALTY               1.52          4.61   11.06
BREWERIES            1.52         -0.81   21.75
CABLES               1.42         31.85   41.68
CERAMICS             1.40        -44.15   87.94
ENGINEERING          1.39        -13.89   65.99
REFINERIES           1.12        -17.30   46.98
JEWELLERY            1.09        -92.41  159.26
CEMENT               1.07        -64.43  187.44
ENTERTAINMENT        0.79        -61.40  157.65
HOTELS               0.43        -71.07  131.41
TEXTILES             0.42        -43.82   84.83

In [29]:
# money to be made criteria-wise
df_portfolio_features.groupby('Criteria')['FTT Amt'].agg(['sum', 'count']).sort_values(by='sum', ascending=False)

                sum  count
Criteria
XY24      3384881.0     21
X40       1880399.0     19
XR        1307436.0     13
AR        1147057.0      9
X40N      1074296.0     13
OX40N      721494.0     10
XY25       439222.0      5
SR         287876.0      2

In [30]:
# money to be made conviction-wise
df_portfolio_features.groupby('Conviction')['FTT Amt'].agg(['sum', 'count']).sort_values(by='sum', ascending=False)

                  sum  count
Conviction
H-SC        3303350.0     24
X-LC        1883753.0     21
X-MC        1568669.0     15
M-SC        1379906.0     14
X-SC        1274404.0      9
H-MC         289678.0      2
L-SC         199884.0      2
M-LC         164828.0      1
M-MC          82834.0      2
L-MC          49089.0      1
H-LC          46266.0      1

In [31]:
# money to be made criteria and conviction-wise
df_portfolio_features.groupby(['Conviction', 'Criteria'])['FTT Amt'].agg(['sum', 'count']).sort_values(by='sum', ascending=False)

                           sum  count
Conviction Criteria
X-LC       X40       1009707.0     10
H-SC       XY24       980294.0      6
           AR         949272.0      5
M-SC       XY24       822668.0      6
H-SC       XR         775448.0      7
X-SC       XY24       775285.0      4
X-MC       X40        668111.0      7
           X40N       428532.0      4
X-LC       X40N       349226.0      6
           XY24       332096.0      2
H-SC       OX40N      310460.0      4
M-SC       OX40N      298372.0      5
X-SC       X40N       296538.0      3
H-SC       SR         287876.0      2
H-MC       XY24       242878.0      1
X-MC       XY25       240366.0      2
           XY24       231660.0      2
X-SC       X40        202581.0      2
M-SC       XR         188962.0      2
M-LC       XR         164828.0      1
X-LC       XY25       150837.0      2
L-SC       OX40N      112662.0      1
           XR          87222.0      1
M-SC       AR          69904.0      1
L-MC       XR          49089.0      1
M-MC       XY25        48019.0      1
H-MC       AR          46800.0      1
H-LC       AR          46266.0      1
X-LC       XR          41887.0      1
M-MC       AR          34815.0      1

In [32]:
# notebook execution time

end_time = time.time()
execution_time = round(end_time - start_time, 0)
print(f"Notebook execution time: {execution_time} seconds")

Notebook execution time: 27.0 seconds