<a href="https://colab.research.google.com/github/ankit-rathi/Quantvesting_v2/blob/main/myStocks_Portfolio_Analysis.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
'''
!pip install pandas==2.2.2 -qq
!pip install pyxirr -qq
!pip install ta -qq
!pip install yfinance==0.2.59 -qq
'''

'\n!pip install pandas==2.2.2 -qq\n!pip install pyxirr -qq\n!pip install ta -qq\n!pip install yfinance==0.2.59 -qq\n'

In [2]:
# import libraries

import numpy as np
import pandas as pd
import datetime
import warnings
warnings.filterwarnings('ignore')
import yfinance as yfin
import ta
import matplotlib.pyplot as plt
import requests

In [3]:
# notebook start time
import time
import datetime
import pytz

start_time = time.time()

# function to print date timestamp
def print_date_time():
  tz_NY = pytz.timezone('Asia/Kolkata')
  datetime_NY = datetime.datetime.now(tz_NY)
  print("Run date time (IST):", datetime_NY.strftime("%Y-%m-%d %H:%M:%S"))

In [4]:
# function to get booked and reserved amount
def get_amt():
  # fetch the JSON data from the URL
  url = "https://raw.githubusercontent.com/ankit-rathi/Tradevesting_v1/main/data/myPortfolioAmts.json"
  response = requests.get(url)
  pf_amts = response.json()  # parse the JSON data

  # extract values from the JSON
  py_booked_amt_dm = pf_amts["py_booked_amt_dm"]
  py_booked_amt_sv = pf_amts["py_booked_amt_sv"]
  cy_booked_amt_dm = pf_amts["cy_booked_amt_dm"]
  cy_booked_amt_sv = pf_amts["cy_booked_amt_sv"]
  reserve_amt_dm = pf_amts["reserve_amt_dm"]
  reserve_amt_sv = pf_amts["reserve_amt_sv"]

  # perform calculations
  py_booked_amt = py_booked_amt_dm + py_booked_amt_sv
  cy_booked_amt = cy_booked_amt_dm + cy_booked_amt_sv
  reserve_amt = reserve_amt_dm + reserve_amt_sv
  total_booked_amt = py_booked_amt + cy_booked_amt

  return total_booked_amt, reserve_amt, cy_booked_amt, py_booked_amt

gen_output = 0

In [5]:
# function to format the amount
def format_amt(number):
    abs_number = abs(number)

    if abs_number >= 1_00_00_000:  # Crores
        formatted_amt = f"{number / 1_00_00_000:.2f} C"
    elif abs_number >= 1_00_000:  # Lakhs
        formatted_amt = f"{number / 1_00_000:.2f} L"
    elif abs_number >= 1_000:  # Thousands
        formatted_amt = f"{number / 1_000:.2f} K"
    else:
        formatted_amt = f"{number:.2f}"

    return formatted_amt

# function to set start and end date
def get_start_end_date():
  start_date = (datetime.date.today() + datetime.timedelta(days=-365)).strftime('%Y-%m-%d')
  end_date = (datetime.date.today() + datetime.timedelta(days=1)).strftime('%Y-%m-%d')
  return start_date, end_date

# function to fetch my portfolio csv
def get_mypfs_df():
  mypfs_df = pd.read_csv('https://raw.githubusercontent.com/ankit-rathi/Tradevesting_v1/main/data/myPortfolioStocks.csv')
  return mypfs_df

# function to fetch my prospects csv
def get_mypps_df():
  mypps_df = pd.read_csv('https://raw.githubusercontent.com/ankit-rathi/Tradevesting_v1/main/data/myProspectsScrips.csv')
  return mypps_df

# function to fetch screener data
def get_myscreen_df():
  myscreen_df = pd.read_csv('https://raw.githubusercontent.com/ankit-rathi/Tradevesting_v1/main/data/myScreenerDB.csv')
  return myscreen_df

# function to fetch momentum data
def get_myinvmt_df():
  myinvmt_df = pd.read_csv('https://raw.githubusercontent.com/ankit-rathi/Tradevesting_v1/main/data/myInvestments.csv')
  return myinvmt_df

# function to get the stock ids
def get_stock_ids(df_pf):
  stock_n100 = df_pf['Symbol'].unique()

  exclude = ['CADILAHC','MMTC', 'MASFIN']

  stock_ids = df_pf[~df_pf['Symbol'].isin(exclude) ]['Symbol'].unique()

  #mypf = mypf[mypf.Forecast.notnull()]
  #stock_ids = mypf['Symbol'].unique()

  #stock_ids.sort()
  return stock_ids

# get features from screener data
def get_screener_features():
  myscreen_df = get_myscreen_df()
  cols = ['Symbol', 'EPS', 'MedPE', 'ROCE%', 'ROE%', 'CapType']
  return myscreen_df[cols]

# get relative strength
def get_relative_strength(stock_list):

    # Dictionary to store stock tickers and their corresponding percentage price change
    stock_changes = {}

    # Loop through each stock and fetch its price data
    for stock in stock_list:
        try:
            # Download the stock data for the given date range
            stock_data = yfin.Ticker(stock + '.NS').history(period='1mo', interval='1d')[map(str.title, ['open', 'close', 'low', 'high', 'volume'])]

            # Calculate the percentage change for the stock
            if len(stock_data) > 0:
                start_price = stock_data['Close'].iloc[0]
                end_price = stock_data['Close'].iloc[-1]
                percent_change = round(((end_price - start_price) / start_price) * 100, 2)
                stock_changes[stock] = percent_change
            else:
                stock_changes[stock] = np.nan  # If no data is available, set to NaN

        except Exception as e:
            print(f"Error fetching data for {stock}: {e}")
            stock_changes[stock] = np.nan

    # Create a DataFrame with stock tickers and their percentage changes
    df = pd.DataFrame(list(stock_changes.items()), columns=['Symbol', 'Percent_Change'])

    # Drop any stocks with missing data (NaN values)
    df = df.dropna()

    # Calculate the percentile rank based on percentage change
    df['RSP'] = round(df['Percent_Change'].rank(pct=True) * 100, 2)
    cols = ['Symbol', 'RSP']
    df = df[cols]
    # Sort by percentile rank (optional)
    df = df.sort_values(by='RSP', ascending=False).reset_index(drop=True)

    return df

In [6]:
# function to get stock technicals
def stock_prec_dev(stock_symbol):
    #stock_symbol = 'ULTRACEMCO.NS'
    short_window = 20
    mid_window = 50
    long_window = 200
    moving_avg = 'SMA'

    start = datetime.datetime(*map(int, start_date.split('-')))
    end = datetime.datetime(*map(int, end_date.split('-')))

    stock_df = yfin.Ticker(stock_symbol + '.NS').history(period='max', interval='1d')[map(str.title, ['open', 'close', 'low', 'high', 'volume'])]

    stock_df['Max'] = round(max(stock_df['Close']),2)
    stock_df = stock_df[(stock_df.index <= end_date) & (stock_df.index >= start_date)]
    stock_df['200_SMA'] = round(stock_df['Close'].rolling(window = 200, min_periods = 1).mean(),0)
    stock_df['Dev%_200'] = round((stock_df['Close'] - stock_df['200_SMA'])*100/stock_df['200_SMA'],2)
    stock_df.dropna(axis = 0, inplace = True) # remove any null rows

    stock_df['20_SMA'] = stock_df['Close'].rolling(window=20).mean()
    stock_df['50_SMA'] = stock_df['Close'].rolling(window=50).mean()
    stock_df['Symbol'] = stock_symbol

    stock_df['Close'] = round(stock_df['Close'],2)
    stock_df['Min'] = round(min(stock_df['Close']),2)
    stock_df['RSI_14'] = ta.momentum.RSIIndicator(close=stock_df['Close'], window=14).rsi()
    stock_df['RSI_14'] = round(stock_df['RSI_14'],0)
    stock_df['Prev_Close'] = stock_df['Close'].shift(1)
    stock_df.drop(['Open', 'Low', 'High', 'Volume'], axis=1, inplace=True)
    stock_df = stock_df.tail(1)

    max_SMA = max(stock_df['20_SMA'].item(), stock_df['50_SMA'].item(), stock_df['200_SMA'].item())
    min_SMA = min(stock_df['20_SMA'].item(), stock_df['50_SMA'].item(), stock_df['200_SMA'].item())
    ABS_Spread = max_SMA - min_SMA
    stock_df['Spread%'] = round((ABS_Spread / stock_df['200_SMA'].item()) * 100,2)

    return stock_df

# function to compute stock attributes
def get_common_features(stock_ids, df_mypf):

  df_prec_dev = pd.DataFrame()
  df_tmp = get_screener_features()
  df_rs = get_relative_strength(stock_ids)

  for stock_id in stock_ids:
      tmp = stock_prec_dev(stock_id)
      tmp = tmp.reset_index()
      df_prec_dev = pd.concat([df_prec_dev, tmp], ignore_index = True)
  df_prec_dev = pd.merge(df_prec_dev, df_mypf, on= 'Symbol')
  df_prec_dev = pd.merge(df_prec_dev, df_tmp, on= 'Symbol', how='left')
  df_prec_dev = pd.merge(df_prec_dev, df_rs, on= 'Symbol', how='left')
  #print(df_prec_dev.columns)
  df_prec_dev['Curr_PE'] = round(df_prec_dev['Close']/df_prec_dev['EPS'],1)
  df_prec_dev['Dev%_PE'] = round((df_prec_dev['Curr_PE'] - df_prec_dev['MedPE'])*100/df_prec_dev['MedPE'],2)
  df_prec_dev['Conviction'] = df_prec_dev['Conviction'] + '-' + df_prec_dev['CapType']
  return df_prec_dev

# function to arrange stock features
def arrange_features(df_stocks, common_cols, diff_cols):
  df_stocks_common = df_stocks[common_cols].drop_duplicates()
  df_stocks_diff = df_stocks[diff_cols]
  df_stocks_diff['Investment'] = df_stocks_diff['AvgCost'] * df_stocks_diff['Shares']
  df_stocks_diff = df_stocks_diff.groupby(['Symbol'])[['Shares', 'Investment']].aggregate(['sum']).reset_index()
  df_stocks_diff.columns = ['Symbol', 'Shares', 'Investment']
  df_stocks_diff['AvgCost'] = round(df_stocks_diff['Investment']/df_stocks_diff['Shares'],2)
  df_stocks = pd.merge(df_stocks_diff, df_stocks_common, on='Symbol')
  return df_stocks

# plot fact distribution across dimension
def plot_pie_chart(df, dimension, fact):
  # grouping the data by category and calculating the sum of fact for each type
  grouped_data = df.groupby(dimension)[fact].sum()

  # sorting the grouped data in descending order
  grouped_data = grouped_data.sort_values(ascending=False)

  # creating a pie chart
  grouped_data.plot.pie(autopct='%1.1f%%', startangle=90, figsize=(6, 6))

  # adding a title and displaying the plot
  plt.title(f'{dimension} {fact} Distribution')
  plt.ylabel('')  # To hide the y-label
  plt.show()

In [7]:
# function to get portfolio features

def get_portfolio_features(df_common_features):

  print_date_time()
  print('-------------------')

  #df_common_features["Target"] = df_common_features["Target"].fillna(df_common_features["Max"])
  df_common_features['NTT'] = np.where(df_common_features['Strategy']== 'NTT', df_common_features["Target"], df_common_features['Max'])
  df_common_features['LTT'] = np.where(df_common_features['Strategy']== 'BTT', df_common_features["Target"], df_common_features['Max'])
  df_common_features['BOL'] = df_common_features['Min']

  tmp_df = df_common_features[df_common_features['Symbol'].isin(mypf_df[mypf_df['InPortfolio'] != 'NA'].Symbol.values)]
  print('qualified stocks: '+str(len(tmp_df['Symbol'].unique())))
  tmp_df1 = tmp_df[tmp_df['LatestQtr'] == 1]
  print('with latest results: '+str(len(tmp_df1['Symbol'].unique())))
  tmp_df1 = tmp_df1[tmp_df1['StarStock'] == 1]
  print('still star stocks: '+str(len(tmp_df1['Symbol'].unique())))
  tmp_df['Investment'] = tmp_df['AvgCost'] * tmp_df['Shares']
  tmp_df['Current'] = round(tmp_df['Close'] * tmp_df['Shares'],0)
  tmp_df['Previous'] = tmp_df['Prev_Close'] * tmp_df['Shares']
  tmp_df['EstimatedST'] = tmp_df['NTT'] * tmp_df['Shares']
  tmp_df['EstimatedLT'] = tmp_df['LTT'] * tmp_df['Shares']
  tmp_df['Current P/L'] = round((tmp_df['Current'] - tmp_df['Investment']),0)
  tmp_df['Today P/L%'] = round((tmp_df['Current'] - tmp_df['Previous'])*100/tmp_df['Previous'],2)
  tmp_df['Current P/L%'] = round((tmp_df['Current'] - tmp_df['Investment'])*100/tmp_df['Investment'],2)
  tmp_df['EstimatedST P/L%'] = round((tmp_df['EstimatedST'] - tmp_df['Investment'])*100/tmp_df['Investment'],2)
  tmp_df['EstimatedLT P/L%'] = round((tmp_df['EstimatedLT'] - tmp_df['Investment'])*100/tmp_df['Investment'],2)
  tmp_df['NTT%'] = round((tmp_df['NTT'] - tmp_df['Close'])*100/tmp_df['Close'],2)
  tmp_df['LTT%'] = round((tmp_df['LTT'] - tmp_df['Close'])*100/tmp_df['Close'],2)
  tmp_df['Gained%'] = round((tmp_df['Close'] - tmp_df['BOL'])*100/tmp_df['BOL'],2)
  investment = round(sum(tmp_df['AvgCost']*tmp_df['Shares']),0)
  current = round(sum(tmp_df['Close']*tmp_df['Shares']),0)
  tmp_df['InitAlloc%'] = round(tmp_df['Investment']*100/investment,2)
  tmp_df['CurrAlloc%'] = round(tmp_df['Current']*100/current,2)
  tmp_df['FTT'] = tmp_df['LTT']
  tmp_df.loc[tmp_df['Strategy'] == 'NTT', 'FTT'] = tmp_df['NTT']
  tmp_df['FTT%'] = tmp_df['LTT%']
  tmp_df.loc[tmp_df['Strategy'] == 'NTT', 'FTT%'] = tmp_df['NTT%']
  tmp_df['FTT Amt'] = round(tmp_df['FTT%'] * tmp_df['Current']/100,0)
  tmp_df['OTT%'] = round((tmp_df['FTT'] - tmp_df['AvgCost'])*100/tmp_df['AvgCost'],2)
  tmp_df['RRR Ind'] = round(tmp_df['Current P/L']/tmp_df['FTT Amt'],2)
  tmp_df['Risk Ind'] = round(tmp_df['Current P/L%']*tmp_df['CurrAlloc%'],0)

  return tmp_df

# function to print portfolio features
def print_portfolio_stats(df_portfolio_features, myinvmt_df):
  from pyxirr import xirr

  total_booked_amt, reserve_amt, cy_booked_amt, py_booked_amt = get_amt()

  dates = myinvmt_df['Date'].values
  dates = np.append(dates, datetime.date.today().strftime('%d-%b-%y'))
  investment = myinvmt_df['Investment'].values
  dates= pd.to_datetime(dates)

  current = round(sum(df_portfolio_features['Close']*df_portfolio_features['Shares']),0) + reserve_amt
  investment_xirr = np.append(investment, current)
  cagr = round(xirr(pd.DataFrame({"dates": dates, "amounts": investment_xirr}))*100,2)

  investment = -sum(investment)
  invested = round(sum(df_portfolio_features['AvgCost']*df_portfolio_features['Shares']),0) + reserve_amt
  previous = round(sum(df_portfolio_features['Prev_Close']*df_portfolio_features['Shares']),0) + reserve_amt
  cy_invested = investment + py_booked_amt

  today_pnl_amount = current-previous
  today_pnl_percentage = round((current-previous)*100/previous,2)

  curr_pnl_amount = current-invested
  curr_pnl_percentage = round((curr_pnl_amount)*100/(cy_invested),2)

  cy_pnl_amount = cy_booked_amt + curr_pnl_amount
  cy_pnl_percentage = round((cy_pnl_amount)*100/cy_invested,2)

  overall_pnl_amount = total_booked_amt + curr_pnl_amount
  overall_pnl_percentage = round((overall_pnl_amount)*100/investment,2)

  estimate_st = round(sum(df_portfolio_features['FTT']*df_portfolio_features['Shares']),0)  + reserve_amt
  est_st_pnl_amount = estimate_st-current
  est_st_pnl_percentage = round((est_st_pnl_amount)*100/current,2)

  estimate_lt = round(sum(df_portfolio_features['LTT']*df_portfolio_features['Shares']),0)  + reserve_amt
  est_lt_pnl_amount = estimate_lt-current
  est_lt_pnl_percentage = round((est_lt_pnl_amount)*100/current,2)

  total_profit = round(sum(df_portfolio_features[df_portfolio_features['Current P/L%'] > 0]['Current']) - sum(df_portfolio_features[df_portfolio_features['Current P/L%'] > 0]['Investment']),0)
  total_loss = round(sum(df_portfolio_features[df_portfolio_features['Current P/L%'] < 0]['Current']) - sum(df_portfolio_features[df_portfolio_features['Current P/L%'] < 0]['Investment']),0)

  cy_booked_percentage = round((cy_booked_amt)*100/current,2)
  py_booked_percentage = round((py_booked_amt)*100/investment,2)
  total_booked_percentage = round((total_booked_amt)*100/investment,2)

  print('-------------------')
  print('Initial Investment: ', format_amt(investment))
  print('CY Investment: ', format_amt(cy_invested))
  print('Reserve: ', format_amt(reserve_amt))
  print('Current: ',  format_amt(current))
  print('-------------------')
  print('Today PnL: '+ '{} ({}%)'.format(format_amt(today_pnl_amount), today_pnl_percentage))
  print('Current PnL: '+ '{} ({}%)'.format(format_amt(curr_pnl_amount), curr_pnl_percentage))
  print('CY Booked + Current PnL: '+ '{} ({}%)'.format(format_amt(cy_pnl_amount), cy_pnl_percentage))
  print('-------------------')
  print('Total profit: ', format_amt(total_profit))
  print('Total loss: ', format_amt(total_loss))
  print('-------------------')
  print('Total Booked + Current PnL: '+ '{} ({}%)'.format(format_amt(overall_pnl_amount), overall_pnl_percentage))
  print('Total Booked PnL: '+ '{} ({}%)'.format(format_amt(total_booked_amt), total_booked_percentage))
  print('Curr Year Booked PnL: '+ '{} ({}%)'.format(format_amt(cy_booked_amt), cy_booked_percentage))
  print('Prev Year Booked PnL: '+ '{} ({}%)'.format(format_amt(py_booked_amt), py_booked_percentage))
  print('===================')
  print('Est FTT: ',  format_amt(estimate_st))
  print('Est FTT PnL: '+ '{} ({}%)'.format(format_amt(est_st_pnl_amount), est_st_pnl_percentage))

  print('===================')
  print('Deployed: ', format_amt(investment))

  print('Current: ', format_amt(current))

  print('CAGR/XIRR %: '+'{}%'.format(cagr))

In [8]:
# get start and end date
start_date, end_date = get_start_end_date()

# get portfolio and prospects data
mypfs_df = get_mypfs_df()
mypps_df = get_mypps_df()
myinvmt_df = get_myinvmt_df()

# merge above datasets
mypf_df = pd.merge(mypfs_df, mypps_df, on="Symbol")

# seggregate dm and sv portfolio
dm_pf = mypf_df[mypf_df['InPortfolio'] == 'DM']
sv_pf = mypf_df[mypf_df['InPortfolio'] == 'SV']

# build portfolio stock dataframe
dm_stocks = get_stock_ids(dm_pf)
sv_stocks = get_stock_ids(sv_pf)
df_stocks = pd.concat([dm_pf,sv_pf], ignore_index = True)

# arrange common and diff stock features
common_cols = ['Symbol', 'Target', 'Criteria', 'Strategy', 'CumlRnk', 'LatestQtr', 'StarStock', 'Conviction', 'Category', 'InFolio', 'XIRR', 'MBQ']
diff_cols = ['Symbol', 'AvgCost', 'Shares']
df_stocks = arrange_features(df_stocks, common_cols, diff_cols)

# get common features
stock_ids = df_stocks['Symbol'].values
df_common_features = get_common_features(stock_ids, df_stocks)

df_common_features.reset_index(drop=True, inplace=True)
df_common_features.drop(['Date'], axis=1, inplace=True)
# get and print portfolio features
df_portfolio_features = get_portfolio_features(df_common_features)

print_portfolio_stats(df_portfolio_features, myinvmt_df)

df = df_portfolio_features
#plot_pie_chart(df, 'CapType', 'Current')
list_ox40n = list(df[df['MBQ'].str.contains('OX40N', na=False)]['Symbol'].values)

Run date time (IST): 2026-04-24 16:15:20
-------------------
qualified stocks: 92
with latest results: 31
still star stocks: 20
-------------------
Initial Investment:  1.40 C
CY Investment:  1.82 C
Reserve:  1.49 K
Current:  1.47 C
-------------------
Today PnL: -2.02 L (-1.36%)
Current PnL: -36.47 L (-20.0%)
CY Booked + Current PnL: -34.39 L (-18.86%)
-------------------
Total profit:  98.68 K
Total loss:  -37.46 L
-------------------
Total Booked + Current PnL: 8.48 L (6.08%)
Total Booked PnL: 44.95 L (32.22%)
Curr Year Booked PnL: 2.08 L (1.42%)
Prev Year Booked PnL: 42.87 L (30.73%)
===================
Est FTT:  2.56 C
Est FTT PnL: 1.09 C (74.17%)
===================
Deployed:  1.40 C
Current:  1.47 C
CAGR/XIRR %: 2.52%

In [9]:
# top 5 near their targets
cols = ['Symbol', 'Today P/L%', 'Current P/L%', 'FTT%', 'OTT%', 'FTT Amt', 'Current P/L', 'Current', 'FTT', 'Dev%_PE', 'RSI_14','Conviction', 'Spread%',  'CumlRnk', 'RRR Ind', 'CurrAlloc%', 'Gained%', 'Criteria', 'Strategy', 'Category']
df_tmp = df_portfolio_features[~df_portfolio_features['Symbol'].isin(['ENRIN','BLUSPRING','DIGITIDE'])]
df_tmp = df_tmp.sort_values(by = 'FTT Amt', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
55,MASFIN,0.17,-1.91,23.94,21.57,23008.0,-1875.0,96105.0,397.04,-15.54,58.0,H-SC,2.20,167.0,-0.08,0.66,24.19,XR,ATH,FINANCE
59,PIDILITIND,-0.56,-1.19,19.79,18.37,27593.0,-1680.0,139430.0,1670.26,-30.78,54.0,X-LC,8.33,5.0,-0.06,0.95,9.48,X40,ATH,CHEMICALS
51,KOTAKBANK,0.12,-0.91,22.22,21.11,30489.0,-1258.0,137214.0,453.24,-15.04,45.0,X-LC,9.75,12.0,-0.04,0.94,4.94,X40,ATH,BANKS
83,TTKPRESTIG,0.04,-32.37,48.01,0.09,32720.0,-32624.0,68153.0,770.00,58.16,62.0,M-SC,21.53,250.0,-1.00,0.46,21.36,OX40N,NTT,DURABLES
53,M&M,-0.31,-1.41,25.14,23.38,34373.0,-1953.0,136728.0,3802.40,-16.52,42.0,X-LC,9.13,25.0,-0.06,0.93,6.93,X40N,ATH,AUTO

In [10]:
# top 5 today
df_tmp = df_portfolio_features.sort_values(by = 'Today P/L%', ascending=False)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
5,ATULAUTO,5.30,-14.00,69.26,45.57,117424.0,-27591.0,169541.0,844.0,3672.97,66.0,M-SC,3.65,248.0,-0.23,1.16,30.47,XY24,NTT,AUTO
80,TITAGARH,2.00,-28.76,104.59,45.74,180434.0,-69661.0,172516.0,1548.0,-5.12,66.0,H-SC,16.14,175.0,-0.39,1.18,31.63,XY24,NTT,ENGINEERING
72,SIS,1.85,-22.90,57.28,21.26,49034.0,-25428.0,85604.0,528.0,2021.24,70.0,H-SC,8.33,168.0,-0.52,0.58,27.28,OX40N,NTT,MISC
49,JSWINFRA,1.72,-5.01,22.57,16.43,47548.0,-11106.0,210668.0,342.0,-18.52,62.0,X-MC,9.28,61.0,-0.23,1.44,19.09,X40N,NTT,REALTY
87,VBL,1.28,-0.93,36.77,35.50,115056.0,-2935.0,312907.0,670.8,-12.57,69.0,X-LC,6.92,13.0,-0.03,2.13,28.48,X40N,ATH,FMCG

In [11]:
# bottom 5 today
df_tmp = df_portfolio_features.sort_values(by = 'Today P/L%', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
45,INFY,-6.93,-21.40,70.80,34.24,174118.0,-66958.0,245930.0,1972.00,-38.32,27.0,X-LC,12.73,3.0,-0.38,1.68,0.00,X40,NTT,IT
69,SFL,-5.51,-48.52,145.96,26.63,197043.0,-127220.0,134998.0,1287.00,2.26,48.0,M-SC,15.57,242.0,-0.65,0.92,12.51,XY24,NTT,MISC
79,TCS,-4.95,-29.64,79.88,26.57,260391.0,-137295.0,325978.0,4311.59,-40.35,38.0,X-LC,15.19,2.0,-0.53,2.22,1.74,X40,ATH,IT
28,GODREJCP,-4.64,-2.46,35.46,32.12,51402.0,-3657.0,144957.0,1476.34,2.55,51.0,X-LC,9.01,32.0,-0.07,0.99,10.67,X40N,ATH,FMCG
13,BSOFT,-4.25,-33.16,125.61,50.79,118081.0,-46647.0,94006.0,831.70,-14.19,47.0,H-SC,5.79,172.0,-0.40,0.64,10.86,XR,ATH,IT

In [12]:
# top 5 to exit based on CumlRnk
df_tmp = df_portfolio_features[~df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])]
df_tmp = df_tmp[(df_tmp['Current P/L%'] > -1) & (df_tmp['Current P/L%'] < 1)].sort_values(by = 'CumlRnk', ascending=False)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
74,STARHEALTH,-0.73,-0.8,48.44,47.26,135090.0,-2241.0,278882.0,761.0,56.47,70.0,H-SC,4.13,173.0,-0.02,1.9,44.43,XY24,NTT,INSURANCE

In [13]:
# OX40N stocks to exit
df_tmp = df_portfolio_features[(df_portfolio_features['Symbol'].isin(list_ox40n))].sort_values(by = 'Current P/L%', ascending=False)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
25,FINCABLES,0.44,23.20,68.76,107.91,125071.0,34251.0,181895.0,1641.55,10.60,69.0,M-SC,5.76,220.0,0.27,1.24,36.85,OX40N,ATH,CABLES
72,SIS,1.85,-22.90,57.28,21.26,49034.0,-25428.0,85604.0,528.00,2021.24,70.0,H-SC,8.33,168.0,-0.52,0.58,27.28,OX40N,NTT,MISC
16,CERA,-2.59,-30.33,77.82,23.89,95369.0,-53352.0,122551.0,9475.00,-32.70,62.0,H-SC,12.81,153.0,-0.56,0.84,17.77,OX40N,NTT,CERAMICS
83,TTKPRESTIG,0.04,-32.37,48.01,0.09,32720.0,-32624.0,68153.0,770.00,58.16,62.0,M-SC,21.53,250.0,-1.00,0.46,21.36,OX40N,NTT,DURABLES
50,KANSAINER,-1.78,-34.20,72.46,13.47,128569.0,-92232.0,177435.0,340.00,-43.52,56.0,H-SC,17.75,162.0,-0.72,1.21,23.94,XY24,NTT,PAINTS

In [14]:
# top 5 to book for rotation
df_tmp = df_portfolio_features[(df_portfolio_features['Current P/L%'] > 20) ].sort_values(by = 'CumlRnk', ascending=False)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
25,FINCABLES,0.44,23.2,68.76,107.91,125071.0,34251.0,181895.0,1641.55,10.6,69.0,M-SC,5.76,220.0,0.27,1.24,36.85,OX40N,ATH,CABLES

In [15]:
# top 5 to monitor for exit
df_tmp = df_portfolio_features[~df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])]
df_tmp = df_tmp[(df_tmp['Current P/L%'] > 0) ].sort_values(by = 'Dev%_PE', ascending=False)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
63,RECLTD,-0.65,1.25,19.25,20.74,39597.0,2530.0,205700.0,446.00,11.33,63.0,M-MC,3.70,191.0,0.06,1.40,22.58,XY25,NTT,FINANCE
25,FINCABLES,0.44,23.20,68.76,107.91,125071.0,34251.0,181895.0,1641.55,10.60,69.0,M-SC,5.76,220.0,0.27,1.24,36.85,OX40N,ATH,CABLES

In [16]:
# top 5 to book for rotation from weak conviction
df_tmp = df_portfolio_features[~df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])]
df_tmp = df_tmp[~df_tmp['Criteria'].isin(['XY25','XY24','X40', 'X40N'])].sort_values(by = 'RRR Ind', ascending=False)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
25,FINCABLES,0.44,23.20,68.76,107.91,125071.0,34251.0,181895.0,1641.55,10.60,69.0,M-SC,5.76,220.0,0.27,1.24,36.85,OX40N,ATH,CABLES
73,SONACOMS,-1.69,-2.28,42.34,39.09,41853.0,-2310.0,98849.0,804.02,-22.63,57.0,M-MC,12.72,193.0,-0.06,0.67,39.84,AR,ATH,AUTO
91,ZYDUSLIFE,-2.00,-2.20,38.69,35.63,79297.0,-4619.0,204955.0,1286.17,-14.86,55.0,H-MC,4.10,120.0,-0.06,1.40,9.12,AR,ATH,PHARMA
42,INDIAMART,-2.42,-9.45,128.31,106.72,143291.0,-11660.0,111676.0,4810.62,-59.18,49.0,H-SC,10.75,140.0,-0.08,0.76,7.29,AR,ATH,MISC
55,MASFIN,0.17,-1.91,23.94,21.57,23008.0,-1875.0,96105.0,397.04,-15.54,58.0,H-SC,2.20,167.0,-0.08,0.66,24.19,XR,ATH,FINANCE

In [17]:
# top 5 to accumulate based on lowest RSI_14
df_tmp = df_portfolio_features[df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])].sort_values(by = 'RSI_14', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
45,INFY,-6.93,-21.40,70.80,34.24,174118.0,-66958.0,245930.0,1972.00,-38.32,27.0,X-LC,12.73,3.0,-0.38,1.68,0.00,X40,NTT,IT
33,HCLTECH,-4.02,-21.92,55.61,21.51,105048.0,-53022.0,188902.0,1872.35,-18.11,27.0,X-LC,7.67,8.0,-0.50,1.29,0.00,X40,ATH,IT
40,ICICIPRULI,-3.94,-14.91,53.64,30.73,89916.0,-29376.0,167629.0,790.00,-37.77,32.0,X-MC,13.13,78.0,-0.33,1.14,2.15,X40,ATH,INSURANCE
1,ABBOTINDIA,-0.91,-15.53,39.77,18.07,60085.0,-27775.0,151080.0,35195.00,-28.13,36.0,X-MC,11.85,58.0,-0.46,1.03,0.00,X40,ATH,PHARMA
79,TCS,-4.95,-29.64,79.88,26.57,260391.0,-137295.0,325978.0,4311.59,-40.35,38.0,X-LC,15.19,2.0,-0.53,2.22,1.74,X40,ATH,IT

In [18]:
# top 5 to accumulate based on Spread and CumlRnk
df_tmp = df_portfolio_features[df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])]
df_tmp = df_tmp[(df_tmp['CumlRnk'] < 100)].sort_values(by = 'Spread%', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
84,UNITDSPR,0.69,2.25,18.11,20.77,43357.0,5263.0,239407.0,1644.00,-9.24,64.0,X-MC,5.02,64.0,0.12,1.63,14.20,X40N,NTT,BREWERIES
88,VOLTAS,1.28,14.53,26.78,45.20,58809.0,27858.0,219600.0,1856.00,31.17,60.0,X-MC,5.37,79.0,0.47,1.50,22.31,XY25,NTT,AC
71,SIEMENS,-1.44,2.34,22.65,25.51,43136.0,4350.0,190445.0,4671.50,60.03,72.0,H-LC,5.98,51.0,0.10,1.30,34.42,AR,ATH,ELECTRICAL
65,RELIANCE,-1.16,-14.77,47.01,25.30,80522.0,-29677.0,171286.0,1952.00,-16.96,43.0,X-LC,6.08,21.0,-0.37,1.17,2.51,XY25,BTT,REFINERIES
39,ICICIGI,-2.09,-6.13,27.13,19.34,50962.0,-12266.0,187843.0,2252.93,-21.06,43.0,X-MC,6.62,66.0,-0.24,1.28,4.91,X40,ATH,INSURANCE

In [19]:
# top 5 to accumulate based on lowest Gained%
df_tmp = df_portfolio_features[df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])].sort_values(by = 'Gained%', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
1,ABBOTINDIA,-0.91,-15.53,39.77,18.07,60085.0,-27775.0,151080.0,35195.00,-28.13,36.0,X-MC,11.85,58.0,-0.46,1.03,0.00,X40,ATH,PHARMA
33,HCLTECH,-4.02,-21.92,55.61,21.51,105048.0,-53022.0,188902.0,1872.35,-18.11,27.0,X-LC,7.67,8.0,-0.50,1.29,0.00,X40,ATH,IT
45,INFY,-6.93,-21.40,70.80,34.24,174118.0,-66958.0,245930.0,1972.00,-38.32,27.0,X-LC,12.73,3.0,-0.38,1.68,0.00,X40,NTT,IT
79,TCS,-4.95,-29.64,79.88,26.57,260391.0,-137295.0,325978.0,4311.59,-40.35,38.0,X-LC,15.19,2.0,-0.53,2.22,1.74,X40,ATH,IT
40,ICICIPRULI,-3.94,-14.91,53.64,30.73,89916.0,-29376.0,167629.0,790.00,-37.77,32.0,X-MC,13.13,78.0,-0.33,1.14,2.15,X40,ATH,INSURANCE

In [20]:
# top 5 to accumulate based on lowest CurrAlloc%
df_tmp = df_portfolio_features[df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])].sort_values(by = 'CurrAlloc%', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
64,RELAXO,-2.70,-60.99,290.45,52.31,164464.0,-88536.0,56624.0,1176.00,-58.47,52.0,X-SC,29.86,92.0,-0.54,0.39,26.60,X40N,NTT,FOOTWEAR
10,BATAINDIA,-2.34,-52.43,184.24,35.20,112762.0,-67466.0,61204.0,2096.00,-19.71,53.0,X-SC,29.41,91.0,-0.60,0.42,21.38,X40,NTT,FOOTWEAR
60,QUESS,-1.32,-22.02,122.99,73.90,102427.0,-23512.0,83281.0,424.00,-58.13,51.0,X-SC,17.43,80.0,-0.23,0.57,12.03,XY24,NTT,MISC
53,M&M,-0.31,-1.41,25.14,23.38,34373.0,-1953.0,136728.0,3802.40,-16.52,42.0,X-LC,9.13,25.0,-0.06,0.93,6.93,X40N,ATH,AUTO
51,KOTAKBANK,0.12,-0.91,22.22,21.11,30489.0,-1258.0,137214.0,453.24,-15.04,45.0,X-LC,9.75,12.0,-0.04,0.94,4.94,X40,ATH,BANKS

In [21]:
# top 5 to accumulate based on CumlRnk
df_tmp = df_portfolio_features.sort_values(by = 'CumlRnk', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
47,ITC,-1.21,-20.56,49.87,19.06,134766.0,-69932.0,270234.0,452.00,-56.33,47.0,X-LC,18.33,1.0,-0.52,1.84,4.83,X40,NTT,FMCG
79,TCS,-4.95,-29.64,79.88,26.57,260391.0,-137295.0,325978.0,4311.59,-40.35,38.0,X-LC,15.19,2.0,-0.53,2.22,1.74,X40,ATH,IT
45,INFY,-6.93,-21.40,70.80,34.24,174118.0,-66958.0,245930.0,1972.00,-38.32,27.0,X-LC,12.73,3.0,-0.38,1.68,0.00,X40,NTT,IT
81,TMPV,-0.41,-20.22,71.18,36.58,202084.0,-71936.0,283905.0,600.00,-83.62,56.0,X-LC,7.80,4.0,-0.36,1.94,18.33,XY24,NTT,AUTO
59,PIDILITIND,-0.56,-1.19,19.79,18.37,27593.0,-1680.0,139430.0,1670.26,-30.78,54.0,X-LC,8.33,5.0,-0.06,0.95,9.48,X40,ATH,CHEMICALS

In [22]:
# top 5 for average up
df_tmp = df_portfolio_features[(df_portfolio_features['Dev%_200'] > 5)].sort_values(by = 'CurrAlloc%', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
73,SONACOMS,-1.69,-2.28,42.34,39.09,41853.0,-2310.0,98849.0,804.02,-22.63,57.0,M-MC,12.72,193.0,-0.06,0.67,39.84,AR,ATH,AUTO
75,SURYODAY,-0.24,-17.29,48.76,23.03,72216.0,-30967.0,148104.0,216.00,62.28,62.0,H-SC,3.53,166.0,-0.43,1.01,26.30,XR,NTT,BANKS
5,ATULAUTO,5.30,-14.00,69.26,45.57,117424.0,-27591.0,169541.0,844.00,3672.97,66.0,M-SC,3.65,248.0,-0.23,1.16,30.47,XY24,NTT,AUTO
25,FINCABLES,0.44,23.20,68.76,107.91,125071.0,34251.0,181895.0,1641.55,10.60,69.0,M-SC,5.76,220.0,0.27,1.24,36.85,OX40N,ATH,CABLES
71,SIEMENS,-1.44,2.34,22.65,25.51,43136.0,4350.0,190445.0,4671.50,60.03,72.0,H-LC,5.98,51.0,0.10,1.30,34.42,AR,ATH,ELECTRICAL

In [23]:
# top 5 RSP
df_tmp = df_portfolio_features.sort_values(by = 'RSP', ascending=False)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
61,RAJESHEXPO,-1.46,-75.50,308.49,0.07,103668.0,-103572.0,33605.0,518.0,1131.06,60.0,L-SC,38.03,268.0,-1.00,0.23,57.76,OX40N,NTT,JEWELLERY
62,RAJOOENG,-1.36,-30.66,101.35,39.61,72029.0,-31430.0,71070.0,143.1,-53.15,67.0,H-SC,25.23,136.0,-0.44,0.48,52.25,AR,ATH,MISC
71,SIEMENS,-1.44,2.34,22.65,25.51,43136.0,4350.0,190445.0,4671.5,60.03,72.0,H-LC,5.98,51.0,0.10,1.30,34.42,AR,ATH,ELECTRICAL
87,VBL,1.28,-0.93,36.77,35.50,115056.0,-2935.0,312907.0,670.8,-12.57,69.0,X-LC,6.92,13.0,-0.03,2.13,28.48,X40N,ATH,FMCG
80,TITAGARH,2.00,-28.76,104.59,45.74,180434.0,-69661.0,172516.0,1548.0,-5.12,66.0,H-SC,16.14,175.0,-0.39,1.18,31.63,XY24,NTT,ENGINEERING

In [24]:
# Top N allocation
df_tmp = df_portfolio_features.sort_values(by = 'CurrAlloc%', ascending=False)
top_n_values = [10, 25, 50]

sum_df = pd.DataFrame({
    'Top_N': top_n_values,
    'Sum_Alloc%': [df_tmp['CurrAlloc%'].head(n).sum() for n in top_n_values]
})

sum_df

   Top_N  Sum_Alloc%
0     10       18.90
1     25       42.75
2     50       72.87

In [25]:
# market-cap-wise allocation
df_tmp = df_portfolio_features[cols]
df_tmp.groupby(df_tmp['Conviction'].str[-2:])['CurrAlloc%'].sum().sort_values(ascending=False)

Conviction
SC    41.75
LC    31.86
MC    26.41
Name: CurrAlloc%, dtype: float64

In [26]:
# criteria-wise allocation
df_portfolio_features.groupby('Criteria')['CurrAlloc%'].sum().sort_values(ascending=False)

Criteria
XY24     26.63
X40      25.89
X40N     17.09
XR        8.95
XY25      7.14
AR        6.78
OX40N     6.77
SR        0.77
Name: CurrAlloc%, dtype: float64

In [27]:
# conviction-wise allocation
df_portfolio_features.groupby('Conviction')['CurrAlloc%'].sum().sort_values(ascending=False)

Conviction
X-LC    29.62
H-SC    21.44
X-MC    21.41
M-SC     9.96
X-SC     9.77
H-MC     2.60
M-MC     2.07
H-LC     1.30
M-LC     0.94
L-SC     0.58
L-MC     0.33
Name: CurrAlloc%, dtype: float64

In [28]:
# sector-wise stats
df_tmp = df_portfolio_features.groupby('Category')[['CurrAlloc%', 'Current', 'Current P/L', 'FTT Amt']].sum().sort_values(by=['Current', 'Current P/L'], ascending=False)
df_tmp['Current P/L%'] = round(df_tmp['Current P/L'] * 100 / df_tmp['Current'], 2)
df_tmp['FTT%'] = round(df_tmp['FTT Amt'] * 100 / df_tmp['Current'], 2)
cols = ['CurrAlloc%', 'Current P/L%', 'FTT%']
df_tmp[cols].sort_values(by=['CurrAlloc%'], ascending=False)

               CurrAlloc%  Current P/L%    FTT%
Category
FMCG                15.77        -14.38   54.76
FINANCE             10.79        -16.54   67.23
IT                  10.45        -46.74  121.05
MISC                 6.85        -33.17   91.01
AUTO                 6.68        -11.86   53.79
BANKS                5.38        -15.22   68.49
INSURANCE            5.30         -6.37   42.57
PAINTS               5.16        -30.30   52.93
PHARMA               4.87         -3.71   37.04
ELECTRICAL           4.14        -16.39   57.82
AC                   2.02         -7.91   37.17
CHEMICALS            1.97        -40.17  123.70
HEALTHCARE           1.88        -30.17   64.13
APPARELS             1.80         -1.79   36.52
DURABLES             1.77        -48.80   85.00
FOOTWEAR             1.76        -72.12  141.14
TRAVEL               1.71        -78.37  167.68
BREWERIES            1.63          2.20   18.11
REALTY               1.44         -5.27   22.57
CERAMICS             1.31        -60.19  108.85
CABLES               1.24         18.83   68.76
ENGINEERING          1.18        -40.38  104.59
REFINERIES           1.17        -17.33   47.01
CEMENT               1.16        -58.17  176.49
JEWELLERY            1.06       -106.58  178.35
ENTERTAINMENT        0.75        -74.69  178.88
TEXTILES             0.43        -46.76   88.61
HOTELS               0.35       -124.36  203.49

In [29]:
# money to be made criteria-wise
df_portfolio_features.groupby('Criteria')['FTT Amt'].agg(['sum', 'count']).sort_values(by='sum', ascending=False)

                sum  count
Criteria
XY24      3694388.0     21
X40       1905727.0     19
XR        1370689.0     13
X40N      1219137.0     13
AR        1193709.0      9
OX40N      797690.0     10
XY25       393943.0      5
SR         305548.0      2

In [30]:
# money to be made conviction-wise
df_portfolio_features.groupby('Conviction')['FTT Amt'].agg(['sum', 'count']).sort_values(by='sum', ascending=False)

                  sum  count
Conviction
H-SC        3646109.0     24
X-LC        1955620.0     21
X-MC        1593101.0     15
M-SC        1457925.0     14
X-SC        1372666.0      9
H-MC         316561.0      2
L-SC         206656.0      2
M-LC         153339.0      1
M-MC          81450.0      2
L-MC          54268.0      1
H-LC          43136.0      1

In [31]:
# money to be made criteria and conviction-wise
df_portfolio_features.groupby(['Conviction', 'Criteria'])['FTT Amt'].agg(['sum', 'count']).sort_values(by='sum', ascending=False)

                           sum  count
Conviction Criteria
H-SC       XY24      1200129.0      6
X-LC       X40       1039492.0     10
H-SC       AR         953888.0      5
M-SC       XY24       861508.0      6
H-SC       XR         836494.0      7
X-SC       XY24       811527.0      4
X-MC       X40        666964.0      7
           X40N       469758.0      4
X-LC       X40N       387511.0      6
X-SC       X40N       361868.0      3
H-SC       OX40N      350050.0      4
M-SC       OX40N      343972.0      5
X-LC       XY24       341942.0      2
H-SC       SR         305548.0      2
X-MC       XY24       242018.0      2
H-MC       XY24       237264.0      1
X-MC       XY25       214361.0      2
X-SC       X40        199271.0      2
M-SC       XR         176910.0      2
M-LC       XR         153339.0      1
X-LC       XY25       139985.0      2
L-SC       OX40N      103668.0      1
           XR         102988.0      1
H-MC       AR          79297.0      1
M-SC       AR          75535.0      1
L-MC       XR          54268.0      1
X-LC       XR          46690.0      1
H-LC       AR          43136.0      1
M-MC       AR          41853.0      1
           XY25        39597.0      1

In [32]:
# notebook execution time

end_time = time.time()
execution_time = round(end_time - start_time, 0)
print(f"Notebook execution time: {execution_time} seconds")

Notebook execution time: 26.0 seconds