<a href="https://colab.research.google.com/github/ankit-rathi/Quantvesting_v2/blob/main/myStocks_Portfolio_Analysis.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
'''
!pip install pandas==2.2.2 -qq
!pip install pyxirr -qq
!pip install ta -qq
!pip install yfinance==0.2.59 -qq
'''

'\n!pip install pandas==2.2.2 -qq\n!pip install pyxirr -qq\n!pip install ta -qq\n!pip install yfinance==0.2.59 -qq\n'

In [2]:
# import libraries

import numpy as np
import pandas as pd
import datetime
import warnings
warnings.filterwarnings('ignore')
import yfinance as yfin
import ta
import matplotlib.pyplot as plt
import requests

In [3]:
# notebook start time
import time
import datetime
import pytz

start_time = time.time()

# function to print date timestamp
def print_date_time():
  tz_NY = pytz.timezone('Asia/Kolkata')
  datetime_NY = datetime.datetime.now(tz_NY)
  print("Run date time (IST):", datetime_NY.strftime("%Y-%m-%d %H:%M:%S"))

In [4]:
# function to get booked and reserved amount
def get_amt():
  # fetch the JSON data from the URL
  url = "https://raw.githubusercontent.com/ankit-rathi/Tradevesting_v1/main/data/myPortfolioAmts.json"
  response = requests.get(url)
  pf_amts = response.json()  # parse the JSON data

  # extract values from the JSON
  py_booked_amt_dm = pf_amts["py_booked_amt_dm"]
  py_booked_amt_sv = pf_amts["py_booked_amt_sv"]
  cy_booked_amt_dm = pf_amts["cy_booked_amt_dm"]
  cy_booked_amt_sv = pf_amts["cy_booked_amt_sv"]
  reserve_amt_dm = pf_amts["reserve_amt_dm"]
  reserve_amt_sv = pf_amts["reserve_amt_sv"]

  # perform calculations
  py_booked_amt = py_booked_amt_dm + py_booked_amt_sv
  cy_booked_amt = cy_booked_amt_dm + cy_booked_amt_sv
  reserve_amt = reserve_amt_dm + reserve_amt_sv
  total_booked_amt = py_booked_amt + cy_booked_amt

  return total_booked_amt, reserve_amt, cy_booked_amt, py_booked_amt

gen_output = 0

In [5]:
# function to format the amount
def format_amt(number):
    abs_number = abs(number)

    if abs_number >= 1_00_00_000:  # Crores
        formatted_amt = f"{number / 1_00_00_000:.2f} C"
    elif abs_number >= 1_00_000:  # Lakhs
        formatted_amt = f"{number / 1_00_000:.2f} L"
    elif abs_number >= 1_000:  # Thousands
        formatted_amt = f"{number / 1_000:.2f} K"
    else:
        formatted_amt = f"{number:.2f}"

    return formatted_amt

# function to set start and end date
def get_start_end_date():
  start_date = (datetime.date.today() + datetime.timedelta(days=-365)).strftime('%Y-%m-%d')
  end_date = (datetime.date.today() + datetime.timedelta(days=1)).strftime('%Y-%m-%d')
  return start_date, end_date

# function to fetch my portfolio csv
def get_mypfs_df():
  mypfs_df = pd.read_csv('https://raw.githubusercontent.com/ankit-rathi/Tradevesting_v1/main/data/myPortfolioStocks.csv')
  return mypfs_df

# function to fetch my prospects csv
def get_mypps_df():
  mypps_df = pd.read_csv('https://raw.githubusercontent.com/ankit-rathi/Tradevesting_v1/main/data/myProspectsScrips.csv')
  return mypps_df

# function to fetch screener data
def get_myscreen_df():
  myscreen_df = pd.read_csv('https://raw.githubusercontent.com/ankit-rathi/Tradevesting_v1/main/data/myScreenerDB.csv')
  return myscreen_df

# function to fetch momentum data
def get_myinvmt_df():
  myinvmt_df = pd.read_csv('https://raw.githubusercontent.com/ankit-rathi/Tradevesting_v1/main/data/myInvestments.csv')
  return myinvmt_df

# function to get the stock ids
def get_stock_ids(df_pf):
  stock_n100 = df_pf['Symbol'].unique()

  exclude = ['CADILAHC','MMTC', 'MASFIN']

  stock_ids = df_pf[~df_pf['Symbol'].isin(exclude) ]['Symbol'].unique()

  #mypf = mypf[mypf.Forecast.notnull()]
  #stock_ids = mypf['Symbol'].unique()

  #stock_ids.sort()
  return stock_ids

# get features from screener data
def get_screener_features():
  myscreen_df = get_myscreen_df()
  cols = ['Symbol', 'EPS', 'MedPE', 'ROCE%', 'ROE%', 'CapType']
  return myscreen_df[cols]

# get relative strength
def get_relative_strength(stock_list):

    # Dictionary to store stock tickers and their corresponding percentage price change
    stock_changes = {}

    # Loop through each stock and fetch its price data
    for stock in stock_list:
        try:
            # Download the stock data for the given date range
            stock_data = yfin.Ticker(stock + '.NS').history(period='1mo', interval='1d')[map(str.title, ['open', 'close', 'low', 'high', 'volume'])]

            # Calculate the percentage change for the stock
            if len(stock_data) > 0:
                start_price = stock_data['Close'].iloc[0]
                end_price = stock_data['Close'].iloc[-1]
                percent_change = round(((end_price - start_price) / start_price) * 100, 2)
                stock_changes[stock] = percent_change
            else:
                stock_changes[stock] = np.nan  # If no data is available, set to NaN

        except Exception as e:
            print(f"Error fetching data for {stock}: {e}")
            stock_changes[stock] = np.nan

    # Create a DataFrame with stock tickers and their percentage changes
    df = pd.DataFrame(list(stock_changes.items()), columns=['Symbol', 'Percent_Change'])

    # Drop any stocks with missing data (NaN values)
    df = df.dropna()

    # Calculate the percentile rank based on percentage change
    df['RSP'] = round(df['Percent_Change'].rank(pct=True) * 100, 2)
    cols = ['Symbol', 'RSP']
    df = df[cols]
    # Sort by percentile rank (optional)
    df = df.sort_values(by='RSP', ascending=False).reset_index(drop=True)

    return df

In [6]:
# function to get stock technicals
def stock_prec_dev(stock_symbol):
    #stock_symbol = 'ULTRACEMCO.NS'
    short_window = 20
    mid_window = 50
    long_window = 200
    moving_avg = 'SMA'

    start = datetime.datetime(*map(int, start_date.split('-')))
    end = datetime.datetime(*map(int, end_date.split('-')))

    stock_df = yfin.Ticker(stock_symbol + '.NS').history(period='max', interval='1d')[map(str.title, ['open', 'close', 'low', 'high', 'volume'])]

    stock_df['Max'] = round(max(stock_df['Close']),2)
    stock_df = stock_df[(stock_df.index <= end_date) & (stock_df.index >= start_date)]
    stock_df['200_SMA'] = round(stock_df['Close'].rolling(window = 200, min_periods = 1).mean(),0)
    stock_df['Dev%_200'] = round((stock_df['Close'] - stock_df['200_SMA'])*100/stock_df['200_SMA'],2)
    stock_df.dropna(axis = 0, inplace = True) # remove any null rows

    stock_df['20_SMA'] = stock_df['Close'].rolling(window=20).mean()
    stock_df['50_SMA'] = stock_df['Close'].rolling(window=50).mean()
    stock_df['Symbol'] = stock_symbol

    stock_df['Close'] = round(stock_df['Close'],2)
    stock_df['Min'] = round(min(stock_df['Close']),2)
    stock_df['RSI_14'] = ta.momentum.RSIIndicator(close=stock_df['Close'], window=14).rsi()
    stock_df['RSI_14'] = round(stock_df['RSI_14'],0)
    stock_df['Prev_Close'] = stock_df['Close'].shift(1)
    stock_df.drop(['Open', 'Low', 'High', 'Volume'], axis=1, inplace=True)
    stock_df = stock_df.tail(1)

    max_SMA = max(stock_df['20_SMA'].item(), stock_df['50_SMA'].item(), stock_df['200_SMA'].item())
    min_SMA = min(stock_df['20_SMA'].item(), stock_df['50_SMA'].item(), stock_df['200_SMA'].item())
    ABS_Spread = max_SMA - min_SMA
    stock_df['Spread%'] = round((ABS_Spread / stock_df['200_SMA'].item()) * 100,2)

    return stock_df

# function to compute stock attributes
def get_common_features(stock_ids, df_mypf):

  df_prec_dev = pd.DataFrame()
  df_tmp = get_screener_features()
  df_rs = get_relative_strength(stock_ids)

  for stock_id in stock_ids:
      tmp = stock_prec_dev(stock_id)
      tmp = tmp.reset_index()
      df_prec_dev = pd.concat([df_prec_dev, tmp], ignore_index = True)
  df_prec_dev = pd.merge(df_prec_dev, df_mypf, on= 'Symbol')
  df_prec_dev = pd.merge(df_prec_dev, df_tmp, on= 'Symbol', how='left')
  df_prec_dev = pd.merge(df_prec_dev, df_rs, on= 'Symbol', how='left')
  #print(df_prec_dev.columns)
  df_prec_dev['Curr_PE'] = round(df_prec_dev['Close']/df_prec_dev['EPS'],1)
  df_prec_dev['Dev%_PE'] = round((df_prec_dev['Curr_PE'] - df_prec_dev['MedPE'])*100/df_prec_dev['MedPE'],2)
  df_prec_dev['Conviction'] = df_prec_dev['Conviction'] + '-' + df_prec_dev['CapType']
  return df_prec_dev

# function to arrange stock features
def arrange_features(df_stocks, common_cols, diff_cols):
  df_stocks_common = df_stocks[common_cols].drop_duplicates()
  df_stocks_diff = df_stocks[diff_cols]
  df_stocks_diff['Investment'] = df_stocks_diff['AvgCost'] * df_stocks_diff['Shares']
  df_stocks_diff = df_stocks_diff.groupby(['Symbol'])[['Shares', 'Investment']].aggregate(['sum']).reset_index()
  df_stocks_diff.columns = ['Symbol', 'Shares', 'Investment']
  df_stocks_diff['AvgCost'] = round(df_stocks_diff['Investment']/df_stocks_diff['Shares'],2)
  df_stocks = pd.merge(df_stocks_diff, df_stocks_common, on='Symbol')
  return df_stocks

# plot fact distribution across dimension
def plot_pie_chart(df, dimension, fact):
  # grouping the data by category and calculating the sum of fact for each type
  grouped_data = df.groupby(dimension)[fact].sum()

  # sorting the grouped data in descending order
  grouped_data = grouped_data.sort_values(ascending=False)

  # creating a pie chart
  grouped_data.plot.pie(autopct='%1.1f%%', startangle=90, figsize=(6, 6))

  # adding a title and displaying the plot
  plt.title(f'{dimension} {fact} Distribution')
  plt.ylabel('')  # To hide the y-label
  plt.show()

In [7]:
# function to get portfolio features

def get_portfolio_features(df_common_features):

  print_date_time()
  print('-------------------')

  #df_common_features["Target"] = df_common_features["Target"].fillna(df_common_features["Max"])
  df_common_features['NTT'] = np.where(df_common_features['Strategy']== 'NTT', df_common_features["Target"], df_common_features['Max'])
  df_common_features['LTT'] = np.where(df_common_features['Strategy']== 'BTT', df_common_features["Target"], df_common_features['Max'])
  df_common_features['BOL'] = df_common_features['Min']

  tmp_df = df_common_features[df_common_features['Symbol'].isin(mypf_df[mypf_df['InPortfolio'] != 'NA'].Symbol.values)]
  print('qualified stocks: '+str(len(tmp_df['Symbol'].unique())))
  tmp_df1 = tmp_df[tmp_df['LatestQtr'] == 1]
  print('with latest results: '+str(len(tmp_df1['Symbol'].unique())))
  tmp_df1 = tmp_df1[tmp_df1['StarStock'] == 1]
  print('still star stocks: '+str(len(tmp_df1['Symbol'].unique())))
  tmp_df['Investment'] = tmp_df['AvgCost'] * tmp_df['Shares']
  tmp_df['Current'] = round(tmp_df['Close'] * tmp_df['Shares'],0)
  tmp_df['Previous'] = tmp_df['Prev_Close'] * tmp_df['Shares']
  tmp_df['EstimatedST'] = tmp_df['NTT'] * tmp_df['Shares']
  tmp_df['EstimatedLT'] = tmp_df['LTT'] * tmp_df['Shares']
  tmp_df['Current P/L'] = round((tmp_df['Current'] - tmp_df['Investment']),0)
  tmp_df['Today P/L%'] = round((tmp_df['Current'] - tmp_df['Previous'])*100/tmp_df['Previous'],2)
  tmp_df['Current P/L%'] = round((tmp_df['Current'] - tmp_df['Investment'])*100/tmp_df['Investment'],2)
  tmp_df['EstimatedST P/L%'] = round((tmp_df['EstimatedST'] - tmp_df['Investment'])*100/tmp_df['Investment'],2)
  tmp_df['EstimatedLT P/L%'] = round((tmp_df['EstimatedLT'] - tmp_df['Investment'])*100/tmp_df['Investment'],2)
  tmp_df['NTT%'] = round((tmp_df['NTT'] - tmp_df['Close'])*100/tmp_df['Close'],2)
  tmp_df['LTT%'] = round((tmp_df['LTT'] - tmp_df['Close'])*100/tmp_df['Close'],2)
  tmp_df['Gained%'] = round((tmp_df['Close'] - tmp_df['BOL'])*100/tmp_df['BOL'],2)
  investment = round(sum(tmp_df['AvgCost']*tmp_df['Shares']),0)
  current = round(sum(tmp_df['Close']*tmp_df['Shares']),0)
  tmp_df['InitAlloc%'] = round(tmp_df['Investment']*100/investment,2)
  tmp_df['CurrAlloc%'] = round(tmp_df['Current']*100/current,2)
  tmp_df['FTT'] = tmp_df['LTT']
  tmp_df.loc[tmp_df['Strategy'] == 'NTT', 'FTT'] = tmp_df['NTT']
  tmp_df['FTT%'] = tmp_df['LTT%']
  tmp_df.loc[tmp_df['Strategy'] == 'NTT', 'FTT%'] = tmp_df['NTT%']
  tmp_df['FTT Amt'] = round(tmp_df['FTT%'] * tmp_df['Current']/100,0)
  tmp_df['OTT%'] = round((tmp_df['FTT'] - tmp_df['AvgCost'])*100/tmp_df['AvgCost'],2)
  tmp_df['RRR Ind'] = round(tmp_df['Current P/L']/tmp_df['FTT Amt'],2)
  tmp_df['Risk Ind'] = round(tmp_df['Current P/L%']*tmp_df['CurrAlloc%'],0)

  return tmp_df

# function to print portfolio features
def print_portfolio_stats(df_portfolio_features, myinvmt_df):
  from pyxirr import xirr

  total_booked_amt, reserve_amt, cy_booked_amt, py_booked_amt = get_amt()

  dates = myinvmt_df['Date'].values
  dates = np.append(dates, datetime.date.today().strftime('%d-%b-%y'))
  investment = myinvmt_df['Investment'].values
  dates= pd.to_datetime(dates)

  current = round(sum(df_portfolio_features['Close']*df_portfolio_features['Shares']),0) + reserve_amt
  investment_xirr = np.append(investment, current)
  cagr = round(xirr(pd.DataFrame({"dates": dates, "amounts": investment_xirr}))*100,2)

  investment = -sum(investment)
  invested = round(sum(df_portfolio_features['AvgCost']*df_portfolio_features['Shares']),0) + reserve_amt
  previous = round(sum(df_portfolio_features['Prev_Close']*df_portfolio_features['Shares']),0) + reserve_amt
  cy_invested = investment + py_booked_amt

  today_pnl_amount = current-previous
  today_pnl_percentage = round((current-previous)*100/previous,2)

  curr_pnl_amount = current-invested
  curr_pnl_percentage = round((curr_pnl_amount)*100/(cy_invested),2)

  cy_pnl_amount = cy_booked_amt + curr_pnl_amount
  cy_pnl_percentage = round((cy_pnl_amount)*100/cy_invested,2)

  overall_pnl_amount = total_booked_amt + curr_pnl_amount
  overall_pnl_percentage = round((overall_pnl_amount)*100/investment,2)

  estimate_st = round(sum(df_portfolio_features['FTT']*df_portfolio_features['Shares']),0)  + reserve_amt
  est_st_pnl_amount = estimate_st-current
  est_st_pnl_percentage = round((est_st_pnl_amount)*100/current,2)

  estimate_lt = round(sum(df_portfolio_features['LTT']*df_portfolio_features['Shares']),0)  + reserve_amt
  est_lt_pnl_amount = estimate_lt-current
  est_lt_pnl_percentage = round((est_lt_pnl_amount)*100/current,2)

  total_profit = round(sum(df_portfolio_features[df_portfolio_features['Current P/L%'] > 0]['Current']) - sum(df_portfolio_features[df_portfolio_features['Current P/L%'] > 0]['Investment']),0)
  total_loss = round(sum(df_portfolio_features[df_portfolio_features['Current P/L%'] < 0]['Current']) - sum(df_portfolio_features[df_portfolio_features['Current P/L%'] < 0]['Investment']),0)

  cy_booked_percentage = round((cy_booked_amt)*100/current,2)
  py_booked_percentage = round((py_booked_amt)*100/investment,2)
  total_booked_percentage = round((total_booked_amt)*100/investment,2)

  print('-------------------')
  print('Initial Investment: ', format_amt(investment))
  print('CY Investment: ', format_amt(cy_invested))
  print('Reserve: ', format_amt(reserve_amt))
  print('Current: ',  format_amt(current))
  print('-------------------')
  print('Today PnL: '+ '{} ({}%)'.format(format_amt(today_pnl_amount), today_pnl_percentage))
  print('Current PnL: '+ '{} ({}%)'.format(format_amt(curr_pnl_amount), curr_pnl_percentage))
  print('CY Booked + Current PnL: '+ '{} ({}%)'.format(format_amt(cy_pnl_amount), cy_pnl_percentage))
  print('-------------------')
  print('Total profit: ', format_amt(total_profit))
  print('Total loss: ', format_amt(total_loss))
  print('-------------------')
  print('Total Booked + Current PnL: '+ '{} ({}%)'.format(format_amt(overall_pnl_amount), overall_pnl_percentage))
  print('Total Booked PnL: '+ '{} ({}%)'.format(format_amt(total_booked_amt), total_booked_percentage))
  print('Curr Year Booked PnL: '+ '{} ({}%)'.format(format_amt(cy_booked_amt), cy_booked_percentage))
  print('Prev Year Booked PnL: '+ '{} ({}%)'.format(format_amt(py_booked_amt), py_booked_percentage))
  print('===================')
  print('Est FTT: ',  format_amt(estimate_st))
  print('Est FTT PnL: '+ '{} ({}%)'.format(format_amt(est_st_pnl_amount), est_st_pnl_percentage))

  print('===================')
  print('Deployed: ', format_amt(investment))

  print('Current: ', format_amt(current))

  print('CAGR/XIRR %: '+'{}%'.format(cagr))

In [8]:
# get start and end date
start_date, end_date = get_start_end_date()

# get portfolio and prospects data
mypfs_df = get_mypfs_df()
mypps_df = get_mypps_df()
myinvmt_df = get_myinvmt_df()

# merge above datasets
mypf_df = pd.merge(mypfs_df, mypps_df, on="Symbol")

# seggregate dm and sv portfolio
dm_pf = mypf_df[mypf_df['InPortfolio'] == 'DM']
sv_pf = mypf_df[mypf_df['InPortfolio'] == 'SV']

# build portfolio stock dataframe
dm_stocks = get_stock_ids(dm_pf)
sv_stocks = get_stock_ids(sv_pf)
df_stocks = pd.concat([dm_pf,sv_pf], ignore_index = True)

# arrange common and diff stock features
common_cols = ['Symbol', 'Target', 'Criteria', 'Strategy', 'CumlRnk', 'LatestQtr', 'StarStock', 'Conviction', 'Category', 'InFolio', 'XIRR', 'MBQ']
diff_cols = ['Symbol', 'AvgCost', 'Shares']
df_stocks = arrange_features(df_stocks, common_cols, diff_cols)

# get common features
stock_ids = df_stocks['Symbol'].values
df_common_features = get_common_features(stock_ids, df_stocks)

df_common_features.reset_index(drop=True, inplace=True)
df_common_features.drop(['Date'], axis=1, inplace=True)
# get and print portfolio features
df_portfolio_features = get_portfolio_features(df_common_features)

print_portfolio_stats(df_portfolio_features, myinvmt_df)

df = df_portfolio_features
#plot_pie_chart(df, 'CapType', 'Current')
list_ox40n = list(df[df['MBQ'].str.contains('OX40N', na=False)]['Symbol'].values)

Run date time (IST): 2026-06-11 16:52:18
-------------------
qualified stocks: 92
with latest results: 31
still star stocks: 20

-------------------
Initial Investment:  1.40 C
CY Investment:  1.82 C
Reserve:  1.49 K
Current:  1.45 C
-------------------
Today PnL: -1.63 L (-1.11%)
Current PnL: -37.68 L (-20.66%)
CY Booked + Current PnL: -35.60 L (-19.52%)
-------------------
Total profit:  2.04 L
Total loss:  -39.72 L
-------------------
Total Booked + Current PnL: 7.27 L (5.21%)
Total Booked PnL: 44.95 L (32.22%)
Curr Year Booked PnL: 2.08 L (1.43%)
Prev Year Booked PnL: 42.87 L (30.73%)
===================
Est FTT:  2.55 C
Est FTT PnL: 1.10 C (75.38%)
===================
Deployed:  1.40 C
Current:  1.45 C
CAGR/XIRR %: 1.98%

In [9]:
# top 5 near their targets
cols = ['Symbol', 'Today P/L%', 'Current P/L%', 'FTT%', 'OTT%', 'FTT Amt', 'Current P/L', 'Current', 'FTT', 'Dev%_PE', 'RSI_14','Conviction', 'Spread%',  'CumlRnk', 'RRR Ind', 'CurrAlloc%', 'Gained%', 'Criteria', 'Strategy', 'Category']
df_tmp = df_portfolio_features[~df_portfolio_features['Symbol'].isin(['ENRIN','BLUSPRING','DIGITIDE'])]
df_tmp = df_tmp.sort_values(by = 'FTT Amt', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
59,PIDILITIND,-0.51,6.22,11.44,18.37,17146.0,8770.0,149880.0,1670.26,-25.63,62.0,X-LC,3.75,5.0,0.51,1.03,17.68,X40,ATH,CHEMICALS
51,KOTAKBANK,1.35,5.10,15.23,21.11,22166.0,7068.0,145540.0,453.24,-9.84,61.0,X-LC,6.65,12.0,0.32,1.00,11.30,X40,ATH,BANKS
72,SIS,3.18,-1.55,23.18,21.26,25337.0,-1726.0,109306.0,528.00,2608.29,67.0,H-SC,20.92,168.0,-0.07,0.75,62.52,OX40N,NTT,MISC
83,TTKPRESTIG,-2.32,-30.84,44.72,0.09,31169.0,-31078.0,69699.0,770.00,61.79,51.0,M-SC,12.29,250.0,-1.00,0.48,24.11,OX40N,NTT,DURABLES
55,MASFIN,-1.95,-10.84,36.35,21.57,31755.0,-10620.0,87360.0,397.04,-23.22,34.0,H-SC,2.97,167.0,-0.33,0.60,4.13,XR,ATH,FINANCE

In [10]:
# top 5 today
df_tmp = df_portfolio_features.sort_values(by = 'Today P/L%', ascending=False)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
18,COFFEEDAY,4.62,-41.39,130.81,35.27,87050.0,-47002.0,66547.0,80.00,-55.73,59.0,L-SC,17.33,266.0,-0.54,0.46,64.11,XR,NTT,HOTELS
72,SIS,3.18,-1.55,23.18,21.26,25337.0,-1726.0,109306.0,528.00,2608.29,67.0,H-SC,20.92,168.0,-0.07,0.75,62.52,OX40N,NTT,MISC
38,HYUNDAI,2.60,3.14,44.80,49.35,71271.0,4847.0,159088.0,2809.30,-16.97,60.0,X-LC,16.28,29.0,0.07,1.09,14.70,X40N,ATH,AUTO
25,FINCABLES,1.85,28.29,62.06,107.91,117549.0,41768.0,189412.0,1641.55,15.17,47.0,M-SC,23.75,220.0,0.36,1.30,42.50,OX40N,ATH,CABLES
46,IRCTC,1.70,-37.21,143.55,52.93,243837.0,-100646.0,169862.0,1269.00,-53.48,46.0,H-MC,16.31,119.0,-0.41,1.17,5.37,XY24,BTT,TRAVEL

In [11]:
# bottom 5 today
df_tmp = df_portfolio_features.sort_values(by = 'Today P/L%', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
68,SATIN,-6.05,21.74,24.72,51.83,83144.0,60061.0,336345.0,274.00,9.07,50.0,H-SC,41.25,159.0,0.72,2.31,63.85,XY24,NTT,FINANCE
24,EASEMYTRIP,-5.78,-54.14,217.69,45.70,176523.0,-95726.0,81089.0,26.40,-15.88,59.0,M-SC,4.97,204.0,-0.54,0.56,42.05,XY24,NTT,TRAVEL
61,RAJESHEXPO,-5.00,-84.46,544.04,0.07,115957.0,-115863.0,21314.0,518.00,681.57,24.0,L-SC,32.47,268.0,-1.00,0.15,0.06,OX40N,NTT,JEWELLERY
63,RECLTD,-3.43,-8.81,32.40,20.74,60027.0,-17902.0,185268.0,446.00,-0.39,46.0,M-MC,4.02,191.0,-0.30,1.27,10.41,XY25,NTT,FINANCE
27,GLAXO,-3.30,-15.57,60.72,35.69,102165.0,-31028.0,168256.0,3380.16,-35.51,26.0,X-MC,9.25,56.0,-0.30,1.16,0.00,X40,ATH,PHARMA

In [12]:
# top 5 to exit based on CumlRnk
df_tmp = df_portfolio_features[~df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])]
df_tmp = df_tmp[(df_tmp['Current P/L%'] > -1) & (df_tmp['Current P/L%'] < 1)].sort_values(by = 'CumlRnk', ascending=False)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
74,STARHEALTH,-0.85,0.62,46.36,47.26,131131.0,1730.0,282853.0,761.0,58.79,51.0,H-SC,9.98,173.0,0.01,1.94,24.18,XY24,NTT,INSURANCE

In [13]:
# OX40N stocks to exit
df_tmp = df_portfolio_features[(df_portfolio_features['Symbol'].isin(list_ox40n))].sort_values(by = 'Current P/L%', ascending=False)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
25,FINCABLES,1.85,28.29,62.06,107.91,117549.0,41768.0,189412.0,1641.55,15.17,47.0,M-SC,23.75,220.0,0.36,1.30,42.50,OX40N,ATH,CABLES
72,SIS,3.18,-1.55,23.18,21.26,25337.0,-1726.0,109306.0,528.00,2608.29,67.0,H-SC,20.92,168.0,-0.07,0.75,62.52,OX40N,NTT,MISC
16,CERA,-0.26,-23.45,61.84,23.89,83270.0,-41249.0,134654.0,9475.00,-26.25,61.0,H-SC,4.05,153.0,-0.50,0.93,29.40,OX40N,NTT,CERAMICS
50,KANSAINER,0.76,-27.90,57.38,13.47,111567.0,-75231.0,194436.0,340.00,-38.12,57.0,H-SC,7.62,162.0,-0.67,1.34,35.81,XY24,NTT,PAINTS
83,TTKPRESTIG,-2.32,-30.84,44.72,0.09,31169.0,-31078.0,69699.0,770.00,61.79,51.0,M-SC,12.29,250.0,-1.00,0.48,24.11,OX40N,NTT,DURABLES

In [14]:
# top 5 to book for rotation
df_tmp = df_portfolio_features[(df_portfolio_features['Current P/L%'] > 20) ].sort_values(by = 'CumlRnk', ascending=False)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
25,FINCABLES,1.85,28.29,62.06,107.91,117549.0,41768.0,189412.0,1641.55,15.17,47.0,M-SC,23.75,220.0,0.36,1.30,42.50,OX40N,ATH,CABLES
68,SATIN,-6.05,21.74,24.72,51.83,83144.0,60061.0,336345.0,274.00,9.07,50.0,H-SC,41.25,159.0,0.72,2.31,63.85,XY24,NTT,FINANCE

In [15]:
# top 5 to monitor for exit
df_tmp = df_portfolio_features[~df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])]
df_tmp = df_tmp[(df_tmp['Current P/L%'] > 0) ].sort_values(by = 'Dev%_PE', ascending=False)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
74,STARHEALTH,-0.85,0.62,46.36,47.26,131131.0,1730.0,282853.0,761.00,58.79,51.0,H-SC,9.98,173.0,0.01,1.94,24.18,XY24,NTT,INSURANCE
25,FINCABLES,1.85,28.29,62.06,107.91,117549.0,41768.0,189412.0,1641.55,15.17,47.0,M-SC,23.75,220.0,0.36,1.30,42.50,OX40N,ATH,CABLES
68,SATIN,-6.05,21.74,24.72,51.83,83144.0,60061.0,336345.0,274.00,9.07,50.0,H-SC,41.25,159.0,0.72,2.31,63.85,XY24,NTT,FINANCE
91,ZYDUSLIFE,0.69,16.62,16.30,35.63,39838.0,34830.0,244404.0,1286.17,1.35,72.0,H-MC,12.17,120.0,0.87,1.68,28.50,AR,ATH,PHARMA
73,SONACOMS,-0.70,1.22,37.42,39.09,38315.0,1233.0,102392.0,804.02,-19.79,47.0,M-MC,18.47,193.0,0.03,0.70,44.85,AR,ATH,AUTO

In [16]:
# top 5 to book for rotation from weak conviction
df_tmp = df_portfolio_features[~df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])]
df_tmp = df_tmp[~df_tmp['Criteria'].isin(['XY25','XY24','X40', 'X40N'])].sort_values(by = 'RRR Ind', ascending=False)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
91,ZYDUSLIFE,0.69,16.62,16.30,35.63,39838.0,34830.0,244404.0,1286.17,1.35,72.0,H-MC,12.17,120.0,0.87,1.68,28.50,AR,ATH,PHARMA
25,FINCABLES,1.85,28.29,62.06,107.91,117549.0,41768.0,189412.0,1641.55,15.17,47.0,M-SC,23.75,220.0,0.36,1.30,42.50,OX40N,ATH,CABLES
73,SONACOMS,-0.70,1.22,37.42,39.09,38315.0,1233.0,102392.0,804.02,-19.79,47.0,M-MC,18.47,193.0,0.03,0.70,44.85,AR,ATH,AUTO
72,SIS,3.18,-1.55,23.18,21.26,25337.0,-1726.0,109306.0,528.00,2608.29,67.0,H-SC,20.92,168.0,-0.07,0.75,62.52,OX40N,NTT,MISC
42,INDIAMART,-2.08,-15.42,144.42,106.72,150652.0,-19021.0,104315.0,4810.62,-61.91,37.0,H-SC,10.92,140.0,-0.13,0.72,0.99,AR,ATH,MISC

In [17]:
# top 5 to accumulate based on lowest RSI_14
df_tmp = df_portfolio_features[df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])].sort_values(by = 'RSI_14', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
35,HDFCLIFE,-0.78,-10.82,49.34,33.18,65911.0,-16214.0,133586.0,814.30,-30.35,24.0,X-LC,15.91,31.0,-0.25,0.92,0.00,X40,ATH,INSURANCE
27,GLAXO,-3.30,-15.57,60.72,35.69,102165.0,-31028.0,168256.0,3380.16,-35.51,26.0,X-MC,9.25,56.0,-0.30,1.16,0.00,X40,ATH,PHARMA
40,ICICIPRULI,-1.16,-23.81,71.00,30.28,106564.0,-46915.0,150090.0,787.27,-44.30,27.0,X-MC,16.22,78.0,-0.44,1.03,0.00,X40,ATH,INSURANCE
58,PGHH,-0.07,-32.38,95.21,32.01,137476.0,-69128.0,144392.0,17616.87,-54.24,31.0,X-MC,18.97,57.0,-0.50,0.99,0.00,X40,ATH,FMCG
65,RELIANCE,0.33,-18.93,54.55,25.30,88877.0,-38036.0,162927.0,1952.00,-21.18,31.0,X-LC,7.23,21.0,-0.43,1.12,0.33,XY25,BTT,REFINERIES

In [18]:
# top 5 to accumulate based on Spread and CumlRnk
df_tmp = df_portfolio_features[df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])]
df_tmp = df_tmp[(df_tmp['CumlRnk'] < 100)].sort_values(by = 'Spread%', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
49,JSWINFRA,-1.13,-6.23,24.16,16.43,50244.0,-13809.0,207965.0,342.00,-19.64,51.0,X-MC,2.90,61.0,-0.27,1.43,17.56,X40N,NTT,REALTY
57,PAGEIND,-0.57,-1.56,35.71,33.59,94339.0,-4199.0,264180.0,51217.29,-29.41,51.0,X-MC,3.00,55.0,-0.04,1.82,25.46,X40,ATH,APPARELS
15,CAMS,-2.49,-5.31,31.46,24.48,75024.0,-13382.0,238474.0,950.00,-9.17,37.0,X-SC,3.23,89.0,-0.18,1.64,16.10,X40N,NTT,MISC
19,COLPAL,-1.35,-22.97,81.57,39.86,165473.0,-60505.0,202860.0,3683.41,-6.75,46.0,X-MC,3.48,62.0,-0.37,1.39,14.75,XY25,ATH,FMCG
59,PIDILITIND,-0.51,6.22,11.44,18.37,17146.0,8770.0,149880.0,1670.26,-25.63,62.0,X-LC,3.75,5.0,0.51,1.03,17.68,X40,ATH,CHEMICALS

In [19]:
# top 5 to accumulate based on lowest Gained%
df_tmp = df_portfolio_features[df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])].sort_values(by = 'Gained%', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
27,GLAXO,-3.30,-15.57,60.72,35.69,102165.0,-31028.0,168256.0,3380.16,-35.51,26.0,X-MC,9.25,56.0,-0.30,1.16,0.0,X40,ATH,PHARMA
35,HDFCLIFE,-0.78,-10.82,49.34,33.18,65911.0,-16214.0,133586.0,814.30,-30.35,24.0,X-LC,15.91,31.0,-0.25,0.92,0.0,X40,ATH,INSURANCE
33,HCLTECH,-1.93,-27.95,68.65,21.51,119658.0,-67623.0,174301.0,1872.35,-24.32,33.0,X-LC,18.48,8.0,-0.57,1.20,0.0,X40,ATH,IT
32,HAVELLS,-2.29,-27.71,81.81,31.42,193963.0,-90901.0,237090.0,2052.62,-31.93,35.0,X-MC,14.29,63.0,-0.47,1.63,0.0,X40,ATH,ELECTRICAL
40,ICICIPRULI,-1.16,-23.81,71.00,30.28,106564.0,-46915.0,150090.0,787.27,-44.30,27.0,X-MC,16.22,78.0,-0.44,1.03,0.0,X40,ATH,INSURANCE

In [20]:
# top 5 to accumulate based on lowest CurrAlloc%
df_tmp = df_portfolio_features[df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])].sort_values(by = 'CurrAlloc%', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
10,BATAINDIA,-0.93,-57.56,218.61,35.20,119365.0,-74068.0,54602.0,2096.00,-28.38,36.0,X-SC,25.56,91.0,-0.62,0.38,8.29,X40,NTT,FOOTWEAR
64,RELAXO,-2.29,-56.39,249.27,52.31,157788.0,-81860.0,63300.0,1176.00,-53.54,59.0,X-SC,20.00,92.0,-0.52,0.44,41.53,X40N,NTT,FOOTWEAR
60,QUESS,1.68,-0.70,75.12,73.90,79664.0,-744.0,106049.0,424.00,-46.56,75.0,X-SC,4.93,80.0,-0.01,0.73,44.57,XY24,NTT,MISC
28,GODREJCP,-1.82,-9.71,45.61,31.47,61201.0,-14430.0,134184.0,1469.04,-4.99,45.0,X-LC,9.96,32.0,-0.24,0.92,2.96,X40N,ATH,FMCG
35,HDFCLIFE,-0.78,-10.82,49.34,33.18,65911.0,-16214.0,133586.0,814.30,-30.35,24.0,X-LC,15.91,31.0,-0.25,0.92,0.00,X40,ATH,INSURANCE

In [21]:
# top 5 to accumulate based on CumlRnk
df_tmp = df_portfolio_features.sort_values(by = 'CumlRnk', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
47,ITC,-0.44,-25.62,60.06,19.06,151970.0,-87136.0,253030.0,452.00,-59.16,40.0,X-LC,14.93,1.0,-0.57,1.74,1.95,X40,NTT,FMCG
79,TCS,-0.85,-37.31,99.19,24.88,288089.0,-172831.0,290442.0,4253.91,-46.90,35.0,X-LC,18.79,2.0,-0.60,2.00,0.00,X40,ATH,IT
45,INFY,-2.68,-24.12,76.92,34.24,182616.0,-75478.0,237410.0,1972.00,-40.13,40.0,X-LC,16.92,3.0,-0.41,1.63,3.99,X40,NTT,IT
81,TMPV,-1.34,-14.43,59.62,36.58,181530.0,-51362.0,304479.0,600.00,-82.53,50.0,X-LC,15.17,4.0,-0.28,2.09,26.91,XY24,NTT,AUTO
59,PIDILITIND,-0.51,6.22,11.44,18.37,17146.0,8770.0,149880.0,1670.26,-25.63,62.0,X-LC,3.75,5.0,0.51,1.03,17.68,X40,ATH,CHEMICALS

In [22]:
# top 5 for average up
df_tmp = df_portfolio_features[(df_portfolio_features['Dev%_200'] > 5)].sort_values(by = 'CurrAlloc%', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
3,ALKYLAMINE,0.67,-22.96,151.33,93.63,117709.0,-23180.0,77783.0,4546.37,-17.57,58.0,H-SC,8.88,142.0,-0.20,0.53,46.87,SR,ATH,CHEMICALS
73,SONACOMS,-0.70,1.22,37.42,39.09,38315.0,1233.0,102392.0,804.02,-19.79,47.0,M-MC,18.47,193.0,0.03,0.70,44.85,AR,ATH,AUTO
60,QUESS,1.68,-0.70,75.12,73.90,79664.0,-744.0,106049.0,424.00,-46.56,75.0,X-SC,4.93,80.0,-0.01,0.73,44.57,XY24,NTT,MISC
72,SIS,3.18,-1.55,23.18,21.26,25337.0,-1726.0,109306.0,528.00,2608.29,67.0,H-SC,20.92,168.0,-0.07,0.75,62.52,OX40N,NTT,MISC
16,CERA,-0.26,-23.45,61.84,23.89,83270.0,-41249.0,134654.0,9475.00,-26.25,61.0,H-SC,4.05,153.0,-0.50,0.93,29.40,OX40N,NTT,CERAMICS

In [23]:
# top 5 RSP
df_tmp = df_portfolio_features.sort_values(by = 'RSP', ascending=False)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
18,COFFEEDAY,4.62,-41.39,130.81,35.27,87050.0,-47002.0,66547.0,80.00,-55.73,59.0,L-SC,17.33,266.0,-0.54,0.46,64.11,XR,NTT,HOTELS
37,HONAUT,-2.49,-8.65,65.65,51.31,115642.0,-16688.0,176150.0,58357.33,-24.00,60.0,X-SC,7.27,90.0,-0.14,1.21,33.83,X40N,ATH,ELECTRICAL
69,SFL,-2.33,-33.06,89.17,26.63,156520.0,-86688.0,175530.0,1287.00,33.01,69.0,M-SC,9.35,242.0,-0.55,1.21,46.30,XY24,NTT,MISC
91,ZYDUSLIFE,0.69,16.62,16.30,35.63,39838.0,34830.0,244404.0,1286.17,1.35,72.0,H-MC,12.17,120.0,0.87,1.68,28.50,AR,ATH,PHARMA
72,SIS,3.18,-1.55,23.18,21.26,25337.0,-1726.0,109306.0,528.00,2608.29,67.0,H-SC,20.92,168.0,-0.07,0.75,62.52,OX40N,NTT,MISC

In [24]:
# Top N allocation
df_tmp = df_portfolio_features.sort_values(by = 'CurrAlloc%', ascending=False)
top_n_values = [10, 25, 50]

sum_df = pd.DataFrame({
    'Top_N': top_n_values,
    'Sum_Alloc%': [df_tmp['CurrAlloc%'].head(n).sum() for n in top_n_values]
})

sum_df

   Top_N  Sum_Alloc%
0     10       19.54
1     25       42.75
2     50       72.76

In [25]:
# market-cap-wise allocation
df_tmp = df_portfolio_features[cols]
df_tmp.groupby(df_tmp['Conviction'].str[-2:])['CurrAlloc%'].sum().sort_values(ascending=False)

Conviction
SC    43.00
LC    31.32
MC    25.72
Name: CurrAlloc%, dtype: float64

In [26]:
# criteria-wise allocation
df_portfolio_features.groupby('Criteria')['CurrAlloc%'].sum().sort_values(ascending=False)

Criteria
XY24     27.91
X40      24.91
X40N     17.13
XR        8.85
OX40N     6.92
AR        6.87
XY25      6.57
SR        0.88
Name: CurrAlloc%, dtype: float64

In [27]:
# conviction-wise allocation
df_portfolio_features.groupby('Conviction')['CurrAlloc%'].sum().sort_values(ascending=False)

Conviction
X-LC    29.26
H-SC    22.49
X-MC    20.55
M-SC    10.00
X-SC     9.90
H-MC     2.85
M-MC     1.97
H-LC     1.21
M-LC     0.85
L-SC     0.61
L-MC     0.35
Name: CurrAlloc%, dtype: float64

In [28]:
# sector-wise stats
df_tmp = df_portfolio_features.groupby('Category')[['CurrAlloc%', 'Current', 'Current P/L', 'FTT Amt']].sum().sort_values(by=['Current', 'Current P/L'], ascending=False)
df_tmp['Current P/L%'] = round(df_tmp['Current P/L'] * 100 / df_tmp['Current'], 2)
df_tmp['FTT%'] = round(df_tmp['FTT Amt'] * 100 / df_tmp['Current'], 2)
cols = ['CurrAlloc%', 'Current P/L%', 'FTT%']
df_tmp[cols].sort_values(by=['CurrAlloc%'], ascending=False)

               CurrAlloc%  Current P/L%    FTT%
Category
FMCG                14.98        -21.32   63.87
FINANCE             10.71        -18.31   69.76
IT                  10.01        -54.64  131.96
MISC                 7.15        -29.06   85.13
AUTO                 6.82        -10.16   51.46
BANKS                5.74         -8.97   59.36
PAINTS               5.72        -18.56   39.15
INSURANCE            5.14        -10.69   48.13
PHARMA               5.09         -0.04   31.01
ELECTRICAL           4.05        -19.95   62.29
CHEMICALS            2.18        -27.55  103.56
HEALTHCARE           2.06        -19.38   50.53
AC                   1.83        -20.30   52.93
APPARELS             1.82         -1.59   35.71
TRAVEL               1.73        -78.25  167.51
FOOTWEAR             1.73        -76.77  147.64
DURABLES             1.57        -70.27  111.69
BREWERIES            1.49         -8.23   30.70
REALTY               1.43         -6.64   24.16
CERAMICS             1.40        -50.96   96.83
CABLES               1.30         22.05   62.06
ENGINEERING          1.29        -29.11   88.16
REFINERIES           1.12        -23.35   54.55
CEMENT               1.08        -71.39  199.61
JEWELLERY            1.02       -117.04  192.46
ENTERTAINMENT        0.72        -85.12  195.52
HOTELS               0.46        -70.63  130.81
TEXTILES             0.40        -58.46  103.65

In [29]:
# money to be made criteria-wise
df_portfolio_features.groupby('Criteria')['FTT Amt'].agg(['sum', 'count']).sort_values(by='sum', ascending=False)

                sum  count
Criteria
XY24      3539699.0     21
X40       2060667.0     19
XR        1395796.0     13
X40N      1230930.0     13
AR        1184256.0      9
OX40N      786290.0     10
XY25       479399.0      5
SR         290009.0      2

In [30]:
# money to be made conviction-wise
df_portfolio_features.groupby('Conviction')['FTT Amt'].agg(['sum', 'count']).sort_values(by='sum', ascending=False)

                  sum  count
Conviction
H-SC        3514775.0     24
X-LC        2029964.0     21
X-MC        1729739.0     15
M-SC        1464056.0     14
X-SC        1365453.0      9
H-MC         283675.0      2
L-SC         203007.0      2
M-LC         168624.0      1
M-MC          98342.0      2
H-LC          57479.0      1
L-MC          51932.0      1

In [31]:
# money to be made criteria and conviction-wise
df_portfolio_features.groupby(['Conviction', 'Criteria'])['FTT Amt'].agg(['sum', 'count']).sort_values(by='sum', ascending=False)

                           sum  count
Conviction Criteria
X-LC       X40       1096301.0     10
H-SC       XY24      1083295.0      6
           AR         970881.0      5
M-SC       XY24       844514.0      6
H-SC       XR         843657.0      7
X-SC       XY24       798319.0      4
X-MC       X40        745686.0      7
           X40N       500950.0      4
X-LC       X40N       381526.0      6
X-SC       X40N       348454.0      3
M-SC       OX40N      343400.0      5
X-LC       XY24       338916.0      2
H-SC       OX40N      326933.0      4
           SR         290009.0      2
X-MC       XY25       252285.0      2
H-MC       XY24       243837.0      1
X-MC       XY24       230818.0      2
X-SC       X40        218680.0      2
M-SC       XR         198399.0      2
M-LC       XR         168624.0      1
X-LC       XY25       167087.0      2
L-SC       OX40N      115957.0      1
           XR          87050.0      1
M-SC       AR          77743.0      1
M-MC       XY25        60027.0      1
H-LC       AR          57479.0      1
L-MC       XR          51932.0      1
X-LC       XR          46134.0      1
H-MC       AR          39838.0      1
M-MC       AR          38315.0      1

In [32]:
# notebook execution time

end_time = time.time()
execution_time = round(end_time - start_time, 0)
print(f"Notebook execution time: {execution_time} seconds")

Notebook execution time: 30.0 seconds