<a href="https://colab.research.google.com/github/ankit-rathi/Quantvesting_v2/blob/main/myStocks_Portfolio_Analysis.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
'''
!pip install pandas==2.2.2 -qq
!pip install pyxirr -qq
!pip install ta -qq
!pip install yfinance==0.2.59 -qq
'''

'\n!pip install pandas==2.2.2 -qq\n!pip install pyxirr -qq\n!pip install ta -qq\n!pip install yfinance==0.2.59 -qq\n'

In [2]:
# import libraries

import numpy as np
import pandas as pd
import datetime
import warnings
warnings.filterwarnings('ignore')
import yfinance as yfin
import ta
import matplotlib.pyplot as plt
import requests

In [3]:
# notebook start time
import time
import datetime
import pytz

start_time = time.time()

# function to print date timestamp
def print_date_time():
  tz_NY = pytz.timezone('Asia/Kolkata')
  datetime_NY = datetime.datetime.now(tz_NY)
  print("Run date time (IST):", datetime_NY.strftime("%Y-%m-%d %H:%M:%S"))

In [4]:
# function to get booked and reserved amount
def get_amt():
  # fetch the JSON data from the URL
  url = "https://raw.githubusercontent.com/ankit-rathi/Tradevesting_v1/main/data/myPortfolioAmts.json"
  response = requests.get(url)
  pf_amts = response.json()  # parse the JSON data

  # extract values from the JSON
  py_booked_amt_dm = pf_amts["py_booked_amt_dm"]
  py_booked_amt_sv = pf_amts["py_booked_amt_sv"]
  cy_booked_amt_dm = pf_amts["cy_booked_amt_dm"]
  cy_booked_amt_sv = pf_amts["cy_booked_amt_sv"]
  reserve_amt_dm = pf_amts["reserve_amt_dm"]
  reserve_amt_sv = pf_amts["reserve_amt_sv"]

  # perform calculations
  py_booked_amt = py_booked_amt_dm + py_booked_amt_sv
  cy_booked_amt = cy_booked_amt_dm + cy_booked_amt_sv
  reserve_amt = reserve_amt_dm + reserve_amt_sv
  total_booked_amt = py_booked_amt + cy_booked_amt

  return total_booked_amt, reserve_amt, cy_booked_amt, py_booked_amt

gen_output = 0

In [5]:
# function to format the amount
def format_amt(number):
    abs_number = abs(number)

    if abs_number >= 1_00_00_000:  # Crores
        formatted_amt = f"{number / 1_00_00_000:.2f} C"
    elif abs_number >= 1_00_000:  # Lakhs
        formatted_amt = f"{number / 1_00_000:.2f} L"
    elif abs_number >= 1_000:  # Thousands
        formatted_amt = f"{number / 1_000:.2f} K"
    else:
        formatted_amt = f"{number:.2f}"

    return formatted_amt

# function to set start and end date
def get_start_end_date():
  start_date = (datetime.date.today() + datetime.timedelta(days=-365)).strftime('%Y-%m-%d')
  end_date = (datetime.date.today() + datetime.timedelta(days=1)).strftime('%Y-%m-%d')
  return start_date, end_date

# function to fetch my portfolio csv
def get_mypfs_df():
  mypfs_df = pd.read_csv('https://raw.githubusercontent.com/ankit-rathi/Tradevesting_v1/main/data/myPortfolioStocks.csv')
  return mypfs_df

# function to fetch my prospects csv
def get_mypps_df():
  mypps_df = pd.read_csv('https://raw.githubusercontent.com/ankit-rathi/Tradevesting_v1/main/data/myProspectsScrips.csv')
  return mypps_df

# function to fetch screener data
def get_myscreen_df():
  myscreen_df = pd.read_csv('https://raw.githubusercontent.com/ankit-rathi/Tradevesting_v1/main/data/myScreenerDB.csv')
  return myscreen_df

# function to fetch momentum data
def get_myinvmt_df():
  myinvmt_df = pd.read_csv('https://raw.githubusercontent.com/ankit-rathi/Tradevesting_v1/main/data/myInvestments.csv')
  return myinvmt_df

# function to get the stock ids
def get_stock_ids(df_pf):
  stock_n100 = df_pf['Symbol'].unique()

  exclude = ['CADILAHC','MMTC', 'MASFIN']

  stock_ids = df_pf[~df_pf['Symbol'].isin(exclude) ]['Symbol'].unique()

  #mypf = mypf[mypf.Forecast.notnull()]
  #stock_ids = mypf['Symbol'].unique()

  #stock_ids.sort()
  return stock_ids

# get features from screener data
def get_screener_features():
  myscreen_df = get_myscreen_df()
  cols = ['Symbol', 'EPS', 'MedPE', 'ROCE%', 'ROE%', 'CapType']
  return myscreen_df[cols]

# get relative strength
def get_relative_strength(stock_list):

    # Dictionary to store stock tickers and their corresponding percentage price change
    stock_changes = {}

    # Loop through each stock and fetch its price data
    for stock in stock_list:
        try:
            # Download the stock data for the given date range
            stock_data = yfin.Ticker(stock + '.NS').history(period='1mo', interval='1d')[map(str.title, ['open', 'close', 'low', 'high', 'volume'])]

            # Calculate the percentage change for the stock
            if len(stock_data) > 0:
                start_price = stock_data['Close'].iloc[0]
                end_price = stock_data['Close'].iloc[-1]
                percent_change = round(((end_price - start_price) / start_price) * 100, 2)
                stock_changes[stock] = percent_change
            else:
                stock_changes[stock] = np.nan  # If no data is available, set to NaN

        except Exception as e:
            print(f"Error fetching data for {stock}: {e}")
            stock_changes[stock] = np.nan

    # Create a DataFrame with stock tickers and their percentage changes
    df = pd.DataFrame(list(stock_changes.items()), columns=['Symbol', 'Percent_Change'])

    # Drop any stocks with missing data (NaN values)
    df = df.dropna()

    # Calculate the percentile rank based on percentage change
    df['RSP'] = round(df['Percent_Change'].rank(pct=True) * 100, 2)
    cols = ['Symbol', 'RSP']
    df = df[cols]
    # Sort by percentile rank (optional)
    df = df.sort_values(by='RSP', ascending=False).reset_index(drop=True)

    return df

In [6]:
# function to get stock technicals
def stock_prec_dev(stock_symbol):
    #stock_symbol = 'ULTRACEMCO.NS'
    short_window = 20
    mid_window = 50
    long_window = 200
    moving_avg = 'SMA'

    start = datetime.datetime(*map(int, start_date.split('-')))
    end = datetime.datetime(*map(int, end_date.split('-')))

    stock_df = yfin.Ticker(stock_symbol + '.NS').history(period='max', interval='1d')[map(str.title, ['open', 'close', 'low', 'high', 'volume'])]

    stock_df['Max'] = round(max(stock_df['Close']),2)
    stock_df = stock_df[(stock_df.index <= end_date) & (stock_df.index >= start_date)]
    stock_df['200_SMA'] = round(stock_df['Close'].rolling(window = 200, min_periods = 1).mean(),0)
    stock_df['Dev%_200'] = round((stock_df['Close'] - stock_df['200_SMA'])*100/stock_df['200_SMA'],2)
    stock_df.dropna(axis = 0, inplace = True) # remove any null rows

    stock_df['20_SMA'] = stock_df['Close'].rolling(window=20).mean()
    stock_df['50_SMA'] = stock_df['Close'].rolling(window=50).mean()
    stock_df['Symbol'] = stock_symbol

    stock_df['Close'] = round(stock_df['Close'],2)
    stock_df['Min'] = round(min(stock_df['Close']),2)
    stock_df['RSI_14'] = ta.momentum.RSIIndicator(close=stock_df['Close'], window=14).rsi()
    stock_df['RSI_14'] = round(stock_df['RSI_14'],0)
    stock_df['Prev_Close'] = stock_df['Close'].shift(1)
    stock_df.drop(['Open', 'Low', 'High', 'Volume'], axis=1, inplace=True)
    stock_df = stock_df.tail(1)

    max_SMA = max(stock_df['20_SMA'].item(), stock_df['50_SMA'].item(), stock_df['200_SMA'].item())
    min_SMA = min(stock_df['20_SMA'].item(), stock_df['50_SMA'].item(), stock_df['200_SMA'].item())
    ABS_Spread = max_SMA - min_SMA
    stock_df['Spread%'] = round((ABS_Spread / stock_df['200_SMA'].item()) * 100,2)

    return stock_df

# function to compute stock attributes
def get_common_features(stock_ids, df_mypf):

  df_prec_dev = pd.DataFrame()
  df_tmp = get_screener_features()
  df_rs = get_relative_strength(stock_ids)

  for stock_id in stock_ids:
      tmp = stock_prec_dev(stock_id)
      tmp = tmp.reset_index()
      df_prec_dev = pd.concat([df_prec_dev, tmp], ignore_index = True)
  df_prec_dev = pd.merge(df_prec_dev, df_mypf, on= 'Symbol')
  df_prec_dev = pd.merge(df_prec_dev, df_tmp, on= 'Symbol', how='left')
  df_prec_dev = pd.merge(df_prec_dev, df_rs, on= 'Symbol', how='left')
  #print(df_prec_dev.columns)
  df_prec_dev['Curr_PE'] = round(df_prec_dev['Close']/df_prec_dev['EPS'],1)
  df_prec_dev['Dev%_PE'] = round((df_prec_dev['Curr_PE'] - df_prec_dev['MedPE'])*100/df_prec_dev['MedPE'],2)
  df_prec_dev['Conviction'] = df_prec_dev['Conviction'] + '-' + df_prec_dev['CapType']
  return df_prec_dev

# function to arrange stock features
def arrange_features(df_stocks, common_cols, diff_cols):
  df_stocks_common = df_stocks[common_cols].drop_duplicates()
  df_stocks_diff = df_stocks[diff_cols]
  df_stocks_diff['Investment'] = df_stocks_diff['AvgCost'] * df_stocks_diff['Shares']
  df_stocks_diff = df_stocks_diff.groupby(['Symbol'])[['Shares', 'Investment']].aggregate(['sum']).reset_index()
  df_stocks_diff.columns = ['Symbol', 'Shares', 'Investment']
  df_stocks_diff['AvgCost'] = round(df_stocks_diff['Investment']/df_stocks_diff['Shares'],2)
  df_stocks = pd.merge(df_stocks_diff, df_stocks_common, on='Symbol')
  return df_stocks

# plot fact distribution across dimension
def plot_pie_chart(df, dimension, fact):
  # grouping the data by category and calculating the sum of fact for each type
  grouped_data = df.groupby(dimension)[fact].sum()

  # sorting the grouped data in descending order
  grouped_data = grouped_data.sort_values(ascending=False)

  # creating a pie chart
  grouped_data.plot.pie(autopct='%1.1f%%', startangle=90, figsize=(6, 6))

  # adding a title and displaying the plot
  plt.title(f'{dimension} {fact} Distribution')
  plt.ylabel('')  # To hide the y-label
  plt.show()

In [7]:
# function to get portfolio features

def get_portfolio_features(df_common_features):

  print_date_time()
  print('-------------------')

  #df_common_features["Target"] = df_common_features["Target"].fillna(df_common_features["Max"])
  df_common_features['NTT'] = np.where(df_common_features['Strategy']== 'NTT', df_common_features["Target"], df_common_features['Max'])
  df_common_features['LTT'] = np.where(df_common_features['Strategy']== 'BTT', df_common_features["Target"], df_common_features['Max'])
  df_common_features['BOL'] = df_common_features['Min']

  tmp_df = df_common_features[df_common_features['Symbol'].isin(mypf_df[mypf_df['InPortfolio'] != 'NA'].Symbol.values)]
  print('qualified stocks: '+str(len(tmp_df['Symbol'].unique())))
  tmp_df1 = tmp_df[tmp_df['LatestQtr'] == 1]
  print('with latest results: '+str(len(tmp_df1['Symbol'].unique())))
  tmp_df1 = tmp_df1[tmp_df1['StarStock'] == 1]
  print('still star stocks: '+str(len(tmp_df1['Symbol'].unique())))
  tmp_df['Investment'] = tmp_df['AvgCost'] * tmp_df['Shares']
  tmp_df['Current'] = round(tmp_df['Close'] * tmp_df['Shares'],0)
  tmp_df['Previous'] = tmp_df['Prev_Close'] * tmp_df['Shares']
  tmp_df['EstimatedST'] = tmp_df['NTT'] * tmp_df['Shares']
  tmp_df['EstimatedLT'] = tmp_df['LTT'] * tmp_df['Shares']
  tmp_df['Current P/L'] = round((tmp_df['Current'] - tmp_df['Investment']),0)
  tmp_df['Today P/L%'] = round((tmp_df['Current'] - tmp_df['Previous'])*100/tmp_df['Previous'],2)
  tmp_df['Current P/L%'] = round((tmp_df['Current'] - tmp_df['Investment'])*100/tmp_df['Investment'],2)
  tmp_df['EstimatedST P/L%'] = round((tmp_df['EstimatedST'] - tmp_df['Investment'])*100/tmp_df['Investment'],2)
  tmp_df['EstimatedLT P/L%'] = round((tmp_df['EstimatedLT'] - tmp_df['Investment'])*100/tmp_df['Investment'],2)
  tmp_df['NTT%'] = round((tmp_df['NTT'] - tmp_df['Close'])*100/tmp_df['Close'],2)
  tmp_df['LTT%'] = round((tmp_df['LTT'] - tmp_df['Close'])*100/tmp_df['Close'],2)
  tmp_df['Gained%'] = round((tmp_df['Close'] - tmp_df['BOL'])*100/tmp_df['BOL'],2)
  investment = round(sum(tmp_df['AvgCost']*tmp_df['Shares']),0)
  current = round(sum(tmp_df['Close']*tmp_df['Shares']),0)
  tmp_df['InitAlloc%'] = round(tmp_df['Investment']*100/investment,2)
  tmp_df['CurrAlloc%'] = round(tmp_df['Current']*100/current,2)
  tmp_df['FTT'] = tmp_df['LTT']
  tmp_df.loc[tmp_df['Strategy'] == 'NTT', 'FTT'] = tmp_df['NTT']
  tmp_df['FTT%'] = tmp_df['LTT%']
  tmp_df.loc[tmp_df['Strategy'] == 'NTT', 'FTT%'] = tmp_df['NTT%']
  tmp_df['FTT Amt'] = round(tmp_df['FTT%'] * tmp_df['Current']/100,0)
  tmp_df['OTT%'] = round((tmp_df['FTT'] - tmp_df['AvgCost'])*100/tmp_df['AvgCost'],2)
  tmp_df['RRR Ind'] = round(tmp_df['Current P/L']/tmp_df['FTT Amt'],2)
  tmp_df['Risk Ind'] = round(tmp_df['Current P/L%']*tmp_df['CurrAlloc%'],0)

  return tmp_df

# function to print portfolio features
def print_portfolio_stats(df_portfolio_features, myinvmt_df):
  from pyxirr import xirr

  total_booked_amt, reserve_amt, cy_booked_amt, py_booked_amt = get_amt()

  dates = myinvmt_df['Date'].values
  dates = np.append(dates, datetime.date.today().strftime('%d-%b-%y'))
  investment = myinvmt_df['Investment'].values
  dates= pd.to_datetime(dates)

  current = round(sum(df_portfolio_features['Close']*df_portfolio_features['Shares']),0) + reserve_amt
  investment_xirr = np.append(investment, current)
  cagr = round(xirr(pd.DataFrame({"dates": dates, "amounts": investment_xirr}))*100,2)

  investment = -sum(investment)
  invested = round(sum(df_portfolio_features['AvgCost']*df_portfolio_features['Shares']),0) + reserve_amt
  previous = round(sum(df_portfolio_features['Prev_Close']*df_portfolio_features['Shares']),0) + reserve_amt
  cy_invested = investment + py_booked_amt

  today_pnl_amount = current-previous
  today_pnl_percentage = round((current-previous)*100/previous,2)

  curr_pnl_amount = current-invested
  curr_pnl_percentage = round((curr_pnl_amount)*100/(cy_invested),2)

  cy_pnl_amount = cy_booked_amt + curr_pnl_amount
  cy_pnl_percentage = round((cy_pnl_amount)*100/cy_invested,2)

  overall_pnl_amount = total_booked_amt + curr_pnl_amount
  overall_pnl_percentage = round((overall_pnl_amount)*100/investment,2)

  estimate_st = round(sum(df_portfolio_features['FTT']*df_portfolio_features['Shares']),0)  + reserve_amt
  est_st_pnl_amount = estimate_st-current
  est_st_pnl_percentage = round((est_st_pnl_amount)*100/current,2)

  estimate_lt = round(sum(df_portfolio_features['LTT']*df_portfolio_features['Shares']),0)  + reserve_amt
  est_lt_pnl_amount = estimate_lt-current
  est_lt_pnl_percentage = round((est_lt_pnl_amount)*100/current,2)

  total_profit = round(sum(df_portfolio_features[df_portfolio_features['Current P/L%'] > 0]['Current']) - sum(df_portfolio_features[df_portfolio_features['Current P/L%'] > 0]['Investment']),0)
  total_loss = round(sum(df_portfolio_features[df_portfolio_features['Current P/L%'] < 0]['Current']) - sum(df_portfolio_features[df_portfolio_features['Current P/L%'] < 0]['Investment']),0)

  cy_booked_percentage = round((cy_booked_amt)*100/current,2)
  py_booked_percentage = round((py_booked_amt)*100/investment,2)
  total_booked_percentage = round((total_booked_amt)*100/investment,2)

  print('-------------------')
  print('Initial Investment: ', format_amt(investment))
  print('CY Investment: ', format_amt(cy_invested))
  print('Reserve: ', format_amt(reserve_amt))
  print('Current: ',  format_amt(current))
  print('-------------------')
  print('Today PnL: '+ '{} ({}%)'.format(format_amt(today_pnl_amount), today_pnl_percentage))
  print('Current PnL: '+ '{} ({}%)'.format(format_amt(curr_pnl_amount), curr_pnl_percentage))
  print('CY Booked + Current PnL: '+ '{} ({}%)'.format(format_amt(cy_pnl_amount), cy_pnl_percentage))
  print('-------------------')
  print('Total profit: ', format_amt(total_profit))
  print('Total loss: ', format_amt(total_loss))
  print('-------------------')
  print('Total Booked + Current PnL: '+ '{} ({}%)'.format(format_amt(overall_pnl_amount), overall_pnl_percentage))
  print('Total Booked PnL: '+ '{} ({}%)'.format(format_amt(total_booked_amt), total_booked_percentage))
  print('Curr Year Booked PnL: '+ '{} ({}%)'.format(format_amt(cy_booked_amt), cy_booked_percentage))
  print('Prev Year Booked PnL: '+ '{} ({}%)'.format(format_amt(py_booked_amt), py_booked_percentage))
  print('===================')
  print('Est FTT: ',  format_amt(estimate_st))
  print('Est FTT PnL: '+ '{} ({}%)'.format(format_amt(est_st_pnl_amount), est_st_pnl_percentage))

  print('===================')
  print('Deployed: ', format_amt(investment))

  print('Current: ', format_amt(current))

  print('CAGR/XIRR %: '+'{}%'.format(cagr))

In [8]:
# get start and end date
start_date, end_date = get_start_end_date()

# get portfolio and prospects data
mypfs_df = get_mypfs_df()
mypps_df = get_mypps_df()
myinvmt_df = get_myinvmt_df()

# merge above datasets
mypf_df = pd.merge(mypfs_df, mypps_df, on="Symbol")

# seggregate dm and sv portfolio
dm_pf = mypf_df[mypf_df['InPortfolio'] == 'DM']
sv_pf = mypf_df[mypf_df['InPortfolio'] == 'SV']

# build portfolio stock dataframe
dm_stocks = get_stock_ids(dm_pf)
sv_stocks = get_stock_ids(sv_pf)
df_stocks = pd.concat([dm_pf,sv_pf], ignore_index = True)

# arrange common and diff stock features
common_cols = ['Symbol', 'Target', 'Criteria', 'Strategy', 'CumlRnk', 'LatestQtr', 'StarStock', 'Conviction', 'Category', 'InFolio', 'XIRR', 'MBQ']
diff_cols = ['Symbol', 'AvgCost', 'Shares']
df_stocks = arrange_features(df_stocks, common_cols, diff_cols)

# get common features
stock_ids = df_stocks['Symbol'].values
df_common_features = get_common_features(stock_ids, df_stocks)

df_common_features.reset_index(drop=True, inplace=True)
df_common_features.drop(['Date'], axis=1, inplace=True)
# get and print portfolio features
df_portfolio_features = get_portfolio_features(df_common_features)

print_portfolio_stats(df_portfolio_features, myinvmt_df)

df = df_portfolio_features
#plot_pie_chart(df, 'CapType', 'Current')
list_ox40n = list(df[df['MBQ'].str.contains('OX40N', na=False)]['Symbol'].values)

Run date time (IST): 2026-08-17 11:30:12
-------------------
qualified stocks: 88
with latest results: 30
still star stocks: 19
-------------------
Initial Investment:  1.46 C
CY Investment:  1.89 C
Reserve:  2.21 L
Current:  1.59 C
-------------------
Today PnL: -84.31 K (-0.53%)
Current PnL: -33.72 L (-17.85%)
CY Booked + Current PnL: -29.07 L (-15.39%)
-------------------
Total profit:  3.79 L
Total loss:  -37.51 L
-------------------
Total Booked + Current PnL: 13.80 L (9.45%)
Total Booked PnL: 47.52 L (32.53%)
Curr Year Booked PnL: 4.65 L (2.93%)
Prev Year Booked PnL: 42.87 L (29.35%)
===================
Est FTT:  2.68 C
Est FTT PnL: 1.09 C (68.61%)
===================
Deployed:  1.46 C
Current:  1.59 C
CAGR/XIRR %: 3.81%

In [9]:
# top 5 near their targets
cols = ['Symbol', 'Today P/L%', 'Current P/L%', 'FTT%', 'OTT%', 'FTT Amt', 'Current P/L', 'Current', 'FTT', 'Dev%_PE', 'RSI_14','Conviction', 'Spread%',  'CumlRnk', 'RRR Ind', 'CurrAlloc%', 'Gained%', 'Criteria', 'Strategy', 'Category']
df_tmp = df_portfolio_features[~df_portfolio_features['Symbol'].isin(['ENRIN','BLUSPRING','DIGITIDE'])]
df_tmp = df_tmp.sort_values(by = 'FTT Amt', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
79,UNITDSPR,-0.18,12.63,7.23,20.77,19066.0,29566.0,263710.0,1644.00,-0.15,66.0,X-MC,10.03,64.0,1.55,1.68,26.76,X40N,NTT,BREWERIES
78,TTKPRESTIG,-0.68,-23.07,30.10,0.09,23337.0,-23245.0,77532.0,770.00,79.94,41.0,M-SC,10.50,250.0,-1.00,0.50,39.55,OX40N,NTT,DURABLES
68,SIS,-1.08,-2.39,24.24,21.26,26270.0,-2657.0,108375.0,528.00,2585.49,44.0,H-SC,21.65,168.0,-0.10,0.69,61.14,OX40N,NTT,MISC
52,M&M,-0.82,7.37,10.67,18.82,27572.0,17727.0,258408.0,3762.88,-6.43,57.0,X-LC,4.75,25.0,0.64,1.65,17.22,X40N,ATH,AUTO
54,MASFIN,0.40,-7.32,31.17,21.57,28305.0,-7170.0,90810.0,397.04,-20.05,42.0,H-SC,0.95,167.0,-0.25,0.58,8.24,XR,ATH,FINANCE

In [10]:
# top 5 today
df_tmp = df_portfolio_features.sort_values(by = 'Today P/L%', ascending=False)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
25,FINCABLES,5.55,66.68,24.74,107.91,60883.0,98448.0,246092.0,1641.55,50.18,76.0,M-SC,18.57,220.0,1.62,1.57,85.14,OX40N,ATH,CABLES
18,COFFEEDAY,4.06,-49.29,166.76,35.27,96022.0,-55968.0,57581.0,80.00,-61.77,43.0,L-SC,3.95,266.0,-0.58,0.37,42.00,XR,NTT,HOTELS
58,RAJESHEXPO,2.80,-83.79,517.40,0.07,115039.0,-114943.0,22234.0,518.00,714.39,43.0,L-SC,36.49,268.0,-1.00,0.14,9.80,OX40N,NTT,JEWELLERY
5,ATULAUTO,1.76,-13.19,67.69,45.57,115832.0,-26010.0,171122.0,844.00,3710.81,48.0,M-SC,10.54,248.0,-0.22,1.09,31.68,XY24,NTT,AUTO
43,INDIGOPNTS,1.54,-17.14,20.71,0.02,29954.0,-29925.0,144634.0,1408.00,120.42,69.0,M-SC,6.75,222.0,-1.00,0.92,64.10,OX40N,NTT,PAINTS

In [11]:
# bottom 5 today
df_tmp = df_portfolio_features.sort_values(by = 'Today P/L%', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
82,VALIANTORG,-4.99,-35.93,171.81,74.15,180095.0,-58783.0,104822.0,838.00,-288.40,58.0,H-SC,6.29,145.0,-0.33,0.67,55.99,XR,NTT,CHEMICALS
24,EASEMYTRIP,-4.69,-66.34,332.79,45.70,198090.0,-117291.0,59524.0,26.40,-38.24,31.0,M-SC,7.10,204.0,-0.59,0.38,4.27,XY24,NTT,TRAVEL
84,VOLTAS,-3.60,-0.42,45.81,45.20,87467.0,-807.0,190935.0,1856.00,13.96,43.0,X-MC,3.88,79.0,-0.01,1.22,4.65,XY25,NTT,AC
29,GREENPANEL,-3.23,-54.98,217.92,43.14,179627.0,-100650.0,82428.0,537.00,84.75,30.0,M-SC,10.94,225.0,-0.56,0.53,0.00,XY24,NTT,MISC
30,HAPPSTMNDS,-2.87,-49.05,259.31,83.08,169340.0,-62861.0,65304.0,1466.54,-39.37,60.0,H-SC,8.98,152.0,-0.37,0.42,22.32,AR,ATH,IT

In [12]:
# top 5 to exit based on CumlRnk
df_tmp = df_portfolio_features[~df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])]
df_tmp = df_tmp[(df_tmp['Current P/L%'] > -1) & (df_tmp['Current P/L%'] < 1)].sort_values(by = 'CumlRnk', ascending=False)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
80,UTIAMC,-0.34,-0.27,51.57,51.15,114344.0,-605.0,221725.0,1371.68,-19.83,46.0,M-SC,7.69,229.0,-0.01,1.42,3.86,XY24,ATH,FINANCE

In [13]:
# OX40N stocks to exit
df_tmp = df_portfolio_features[(df_portfolio_features['Symbol'].isin(list_ox40n))].sort_values(by = 'Current P/L%', ascending=False)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
25,FINCABLES,5.55,66.68,24.74,107.91,60883.0,98448.0,246092.0,1641.55,50.18,76.0,M-SC,18.57,220.0,1.62,1.57,85.14,OX40N,ATH,CABLES
68,SIS,-1.08,-2.39,24.24,21.26,26270.0,-2657.0,108375.0,528.00,2585.49,44.0,H-SC,21.65,168.0,-0.10,0.69,61.14,OX40N,NTT,MISC
43,INDIGOPNTS,1.54,-17.14,20.71,0.02,29954.0,-29925.0,144634.0,1408.00,120.42,69.0,M-SC,6.75,222.0,-1.00,0.92,64.10,OX40N,NTT,PAINTS
78,TTKPRESTIG,-0.68,-23.07,30.10,0.09,23337.0,-23245.0,77532.0,770.00,79.94,41.0,M-SC,10.50,250.0,-1.00,0.50,39.55,OX40N,NTT,DURABLES
16,CERA,-1.54,-24.41,63.88,23.89,84944.0,-42929.0,132974.0,9475.00,-26.97,35.0,H-SC,12.71,153.0,-0.51,0.85,29.26,OX40N,NTT,CERAMICS

In [14]:
# top 5 to book for rotation
df_tmp = df_portfolio_features[(df_portfolio_features['Current P/L%'] > 20) ].sort_values(by = 'CumlRnk', ascending=False)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
25,FINCABLES,5.55,66.68,24.74,107.91,60883.0,98448.0,246092.0,1641.55,50.18,76.0,M-SC,18.57,220.0,1.62,1.57,85.14,OX40N,ATH,CABLES
87,ZYDUSLIFE,1.35,21.32,11.69,35.51,29723.0,44686.0,254260.0,1285.01,5.41,54.0,H-MC,15.77,120.0,1.50,1.62,33.81,AR,ATH,PHARMA
57,QUESS,0.64,39.43,24.72,73.90,36808.0,42105.0,148898.0,424.00,-25.07,71.0,X-SC,43.20,80.0,1.14,0.95,104.94,XY24,NTT,MISC

In [15]:
# top 5 to monitor for exit
df_tmp = df_portfolio_features[~df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])]
df_tmp = df_tmp[(df_tmp['Current P/L%'] > 0) ].sort_values(by = 'Dev%_PE', ascending=False)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
69,STARHEALTH,-0.16,13.05,30.26,47.26,96168.0,36682.0,317805.0,761.00,78.49,51.0,H-SC,16.28,173.0,0.38,2.03,37.41,XY24,NTT,INSURANCE
25,FINCABLES,5.55,66.68,24.74,107.91,60883.0,98448.0,246092.0,1641.55,50.18,76.0,M-SC,18.57,220.0,1.62,1.57,85.14,OX40N,ATH,CABLES
87,ZYDUSLIFE,1.35,21.32,11.69,35.51,29723.0,44686.0,254260.0,1285.01,5.41,54.0,H-MC,15.77,120.0,1.50,1.62,33.81,AR,ATH,PHARMA

In [16]:
# top 5 to book for rotation from weak conviction
df_tmp = df_portfolio_features[~df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])]
df_tmp = df_tmp[~df_tmp['Criteria'].isin(['XY25','XY24','X40', 'X40N'])].sort_values(by = 'RRR Ind', ascending=False)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
25,FINCABLES,5.55,66.68,24.74,107.91,60883.0,98448.0,246092.0,1641.55,50.18,76.0,M-SC,18.57,220.0,1.62,1.57,85.14,OX40N,ATH,CABLES
87,ZYDUSLIFE,1.35,21.32,11.69,35.51,29723.0,44686.0,254260.0,1285.01,5.41,54.0,H-MC,15.77,120.0,1.50,1.62,33.81,AR,ATH,PHARMA
68,SIS,-1.08,-2.39,24.24,21.26,26270.0,-2657.0,108375.0,528.00,2585.49,44.0,H-SC,21.65,168.0,-0.10,0.69,61.14,OX40N,NTT,MISC
3,ALKYLAMINE,0.34,-18.08,135.03,92.54,111683.0,-18253.0,82710.0,4520.85,-12.24,57.0,H-SC,14.15,142.0,-0.16,0.53,57.06,SR,ATH,CHEMICALS
42,INDIAMART,-1.07,-23.91,164.05,100.92,153956.0,-29489.0,93847.0,4675.60,-65.62,40.0,H-SC,13.38,140.0,-0.19,0.60,1.59,AR,ATH,MISC

In [17]:
# top 5 to accumulate based on lowest RSI_14
df_tmp = df_portfolio_features[df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])].sort_values(by = 'RSI_14', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
28,GODREJCP,-0.81,-15.70,57.65,32.90,121273.0,-39176.0,210361.0,1460.97,-12.70,30.0,X-LC,5.72,32.0,-0.32,1.34,2.40,X40N,ATH,FMCG
34,HDFCBANK,-0.27,-11.45,47.99,31.05,124567.0,-33552.0,259568.0,1073.00,-26.46,33.0,X-LC,12.58,26.0,-0.27,1.66,0.75,X40,BTT,BANKS
56,PGHH,-0.45,-37.14,110.00,32.01,147646.0,-79296.0,134224.0,17616.87,-57.46,33.0,X-MC,19.17,57.0,-0.54,0.86,0.00,X40,ATH,FMCG
55,PAGEIND,0.80,-3.38,38.26,33.59,99214.0,-9064.0,259315.0,51217.29,-30.66,34.0,X-MC,8.77,55.0,-0.09,1.66,23.15,X40,ATH,APPARELS
20,DABUR,0.06,-20.72,81.26,43.70,159812.0,-51400.0,196668.0,735.00,-27.96,36.0,X-MC,9.84,70.0,-0.32,1.26,0.08,XY24,BTT,FMCG

In [18]:
# top 5 to accumulate based on Spread and CumlRnk
df_tmp = df_portfolio_features[df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])]
df_tmp = df_tmp[(df_tmp['CumlRnk'] < 100)].sort_values(by = 'Spread%', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
19,COLPAL,-0.69,-25.30,87.22,39.86,171597.0,-66625.0,196740.0,3683.41,-9.66,37.0,X-MC,1.45,62.0,-0.39,1.26,11.29,XY25,ATH,FMCG
23,DMART,-1.09,-2.12,34.26,31.42,104559.0,-6597.0,305193.0,5391.45,-18.62,49.0,X-LC,2.36,14.0,-0.06,1.95,10.13,X40N,ATH,FMCG
50,KOTAKBANK,0.22,3.03,15.42,18.92,38081.0,7258.0,246960.0,452.46,-10.27,52.0,X-LC,2.75,12.0,0.19,1.58,11.11,X40,ATH,BANKS
26,GILLETTE,-0.28,-10.45,44.86,29.72,101998.0,-26526.0,227370.0,10978.86,-31.19,40.0,X-SC,3.32,83.0,-0.26,1.45,4.49,X40,ATH,FMCG
84,VOLTAS,-3.60,-0.42,45.81,45.20,87467.0,-807.0,190935.0,1856.00,13.96,43.0,X-MC,3.88,79.0,-0.01,1.22,4.65,XY25,NTT,AC

In [19]:
# top 5 to accumulate based on lowest Gained%
df_tmp = df_portfolio_features[df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])].sort_values(by = 'Gained%', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
47,ITC,-1.53,-24.42,64.99,24.70,195132.0,-97029.0,300249.0,452.00,-60.37,36.0,X-LC,10.56,1.0,-0.50,1.92,0.00,X40,NTT,FMCG
56,PGHH,-0.45,-37.14,110.00,32.01,147646.0,-79296.0,134224.0,17616.87,-57.46,33.0,X-MC,19.17,57.0,-0.54,0.86,0.00,X40,ATH,FMCG
20,DABUR,0.06,-20.72,81.26,43.70,159812.0,-51400.0,196668.0,735.00,-27.96,36.0,X-MC,9.84,70.0,-0.32,1.26,0.08,XY24,BTT,FMCG
34,HDFCBANK,-0.27,-11.45,47.99,31.05,124567.0,-33552.0,259568.0,1073.00,-26.46,33.0,X-LC,12.58,26.0,-0.27,1.66,0.75,X40,BTT,BANKS
35,HDFCLIFE,1.41,-6.81,49.32,39.15,115242.0,-17075.0,233662.0,811.41,-30.57,45.0,X-LC,16.44,31.0,-0.15,1.49,1.41,X40,ATH,INSURANCE

In [20]:
# top 5 to accumulate based on lowest CurrAlloc%
df_tmp = df_portfolio_features[df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])].sort_values(by = 'CurrAlloc%', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
10,BATAINDIA,-0.91,-51.69,179.90,35.20,111817.0,-66515.0,62155.0,2096.00,-18.56,65.0,X-SC,12.02,91.0,-0.59,0.40,24.87,X40,NTT,FOOTWEAR
61,RELAXO,-1.53,-49.46,201.38,52.31,147728.0,-71802.0,73358.0,1176.00,-46.18,44.0,X-SC,13.07,92.0,-0.49,0.47,64.02,X40N,NTT,FOOTWEAR
56,PGHH,-0.45,-37.14,110.00,32.01,147646.0,-79296.0,134224.0,17616.87,-57.46,33.0,X-MC,19.17,57.0,-0.54,0.86,0.00,X40,ATH,FMCG
57,QUESS,0.64,39.43,24.72,73.90,36808.0,42105.0,148898.0,424.00,-25.07,71.0,X-SC,43.20,80.0,1.14,0.95,104.94,XY24,NTT,MISC
2,ACC,-1.37,-41.67,199.70,74.81,312323.0,-111732.0,156396.0,3906.00,-58.80,37.0,X-SC,11.59,85.0,-0.36,1.00,4.48,XY24,BTT,CEMENT

In [21]:
# top 5 to accumulate based on CumlRnk
df_tmp = df_portfolio_features.sort_values(by = 'CumlRnk', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
47,ITC,-1.53,-24.42,64.99,24.70,195132.0,-97029.0,300249.0,452.00,-60.37,36.0,X-LC,10.56,1.0,-0.50,1.92,0.00,X40,NTT,FMCG
74,TCS,-1.92,-32.02,82.70,24.20,260440.0,-148351.0,314922.0,4230.71,-42.31,49.0,X-LC,14.56,2.0,-0.57,2.01,17.44,X40,ATH,IT
45,INFY,-2.53,-18.87,73.04,40.38,223074.0,-71057.0,305413.0,1972.00,-39.04,51.0,X-LC,15.93,3.0,-0.32,1.95,15.66,X40,NTT,IT
76,TMPV,-1.24,-21.40,81.63,42.75,266968.0,-89061.0,327046.0,600.00,-84.72,41.0,X-LC,4.55,4.0,-0.33,2.09,12.46,XY24,NTT,AUTO
33,HCLTECH,-2.12,-10.97,39.24,23.97,108121.0,-33948.0,275538.0,1853.42,-9.43,58.0,X-LC,11.74,8.0,-0.31,1.76,30.02,X40,ATH,IT

In [22]:
# top 5 for average up
df_tmp = df_portfolio_features[(df_portfolio_features['Dev%_200'] > 5)].sort_values(by = 'CurrAlloc%', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
44,INDUSINDBK,-1.56,-25.81,79.12,32.89,45319.0,-19928.0,57279.0,1800.00,-369.61,49.0,L-MC,13.37,258.0,-0.44,0.37,41.22,XR,NTT,BANKS
61,RELAXO,-1.53,-49.46,201.38,52.31,147728.0,-71802.0,73358.0,1176.00,-46.18,44.0,X-SC,13.07,92.0,-0.49,0.47,64.02,X40N,NTT,FOOTWEAR
3,ALKYLAMINE,0.34,-18.08,135.03,92.54,111683.0,-18253.0,82710.0,4520.85,-12.24,57.0,H-SC,14.15,142.0,-0.16,0.53,57.06,SR,ATH,CHEMICALS
12,BOSCH-HCIL,-0.99,-28.23,39.32,-0.01,36065.0,-36083.0,91722.0,2282.00,18660.87,69.0,M-SC,5.71,231.0,-1.00,0.59,56.12,OX40N,BTT,AC
82,VALIANTORG,-4.99,-35.93,171.81,74.15,180095.0,-58783.0,104822.0,838.00,-288.40,58.0,H-SC,6.29,145.0,-0.33,0.67,55.99,XR,NTT,CHEMICALS

In [23]:
# top 5 RSP
df_tmp = df_portfolio_features.sort_values(by = 'RSP', ascending=False)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
25,FINCABLES,5.55,66.68,24.74,107.91,60883.0,98448.0,246092.0,1641.55,50.18,76.0,M-SC,18.57,220.0,1.62,1.57,85.14,OX40N,ATH,CABLES
12,BOSCH-HCIL,-0.99,-28.23,39.32,-0.01,36065.0,-36083.0,91722.0,2282.00,18660.87,69.0,M-SC,5.71,231.0,-1.00,0.59,56.12,OX40N,BTT,AC
57,QUESS,0.64,39.43,24.72,73.90,36808.0,42105.0,148898.0,424.00,-25.07,71.0,X-SC,43.20,80.0,1.14,0.95,104.94,XY24,NTT,MISC
82,VALIANTORG,-4.99,-35.93,171.81,74.15,180095.0,-58783.0,104822.0,838.00,-288.40,58.0,H-SC,6.29,145.0,-0.33,0.67,55.99,XR,NTT,CHEMICALS
11,BERGEPAINT,1.05,1.51,23.46,25.32,61378.0,3881.0,261630.0,680.00,-4.06,62.0,X-MC,4.62,68.0,0.06,1.67,37.20,XY24,NTT,PAINTS

In [24]:
# Top N allocation
df_tmp = df_portfolio_features.sort_values(by = 'CurrAlloc%', ascending=False)
top_n_values = [10, 25, 50]

sum_df = pd.DataFrame({
    'Top_N': top_n_values,
    'Sum_Alloc%': [df_tmp['CurrAlloc%'].head(n).sum() for n in top_n_values]
})

sum_df

   Top_N  Sum_Alloc%
0     10       19.62
1     25       44.78
2     50       76.96

In [25]:
# market-cap-wise allocation
df_tmp = df_portfolio_features[cols]
df_tmp.groupby(df_tmp['Conviction'].str[-2:])['CurrAlloc%'].sum().sort_values(ascending=False)

Conviction
SC    39.36
LC    37.54
MC    23.14
Name: CurrAlloc%, dtype: float64

In [26]:
# criteria-wise allocation
df_portfolio_features.groupby('Criteria')['CurrAlloc%'].sum().sort_values(ascending=False)

Criteria
X40      26.47
XY24     24.82
X40N     18.37
XR        9.00
OX40N     7.24
XY25      7.19
AR        6.09
SR        0.86
Name: CurrAlloc%, dtype: float64

In [27]:
# conviction-wise allocation
df_portfolio_features.groupby('Conviction')['CurrAlloc%'].sum().sort_values(ascending=False)

Conviction
X-LC    35.47
H-SC    19.07
X-MC    18.93
M-SC    11.24
X-SC     8.54
H-MC     2.66
H-LC     1.26
M-MC     1.18
M-LC     0.81
L-SC     0.51
L-MC     0.37
Name: CurrAlloc%, dtype: float64

In [28]:
# sector-wise stats
df_tmp = df_portfolio_features.groupby('Category')[['CurrAlloc%', 'Current', 'Current P/L', 'FTT Amt']].sum().sort_values(by=['Current', 'Current P/L'], ascending=False)
df_tmp['Current P/L%'] = round(df_tmp['Current P/L'] * 100 / df_tmp['Current'], 2)
df_tmp['FTT%'] = round(df_tmp['FTT Amt'] * 100 / df_tmp['Current'], 2)
cols = ['CurrAlloc%', 'Current P/L%', 'FTT%']
df_tmp[cols].sort_values(by=['CurrAlloc%'], ascending=False)

               CurrAlloc%  Current P/L%    FTT%
Category
FMCG                15.37        -23.96   68.53
IT                  11.06        -37.69  106.03
FINANCE             10.59        -16.45   66.61
AUTO                 8.23         -4.89   42.46
MISC                 6.90        -24.18   77.47
BANKS                6.07        -12.58   61.13
PHARMA               5.70          7.25   19.05
INSURANCE            5.67         -4.52   41.47
PAINTS               5.53        -13.70   33.10
ELECTRICAL           4.17         -8.48   46.46
AC                   1.81        -13.05   43.70
REFINERIES           1.69        -12.39   50.14
BREWERIES            1.68         11.21    7.23
FOOTWEAR             1.66        -70.53  138.91
APPARELS             1.66         -3.50   38.26
CABLES               1.57         40.00   24.74
DURABLES             1.48        -68.16  109.07
TRAVEL               1.42       -101.54  202.45
CERAMICS             1.33        -47.42   92.20
CHEMICALS            1.20        -41.08  155.59
ENGINEERING          1.19        -30.27   89.85
CEMENT               1.00        -71.44  199.70
JEWELLERY            0.95       -113.53  187.72
ENTERTAINMENT        0.68        -79.43  186.44
HEALTHCARE           0.68        -70.40  113.17
TEXTILES             0.38        -53.07   96.72
HOTELS               0.37        -97.20  166.76

In [29]:
# money to be made criteria-wise
df_portfolio_features.groupby('Criteria')['FTT Amt'].agg(['sum', 'count']).sort_values(by='sum', ascending=False)

                sum  count
Criteria
XY24      3630762.0     20
X40       2081496.0     18
XR        1387606.0     13
X40N      1205343.0     12
AR        1077549.0      8
OX40N      657537.0     10
XY25       573027.0      5
SR         282458.0      2

In [30]:
# money to be made conviction-wise
df_portfolio_features.groupby('Conviction')['FTT Amt'].agg(['sum', 'count']).sort_values(by='sum', ascending=False)

                  sum  count
Conviction
H-SC        3364312.0     23
X-LC        2503487.0     20
M-SC        1495878.0     15
X-MC        1491135.0     14
X-SC        1241706.0      8
H-MC         280986.0      2
L-SC         211061.0      2
M-LC         165645.0      1
M-MC          60476.0      1
L-MC          45319.0      1
H-LC          35773.0      1

In [31]:
# money to be made criteria and conviction-wise
df_portfolio_features.groupby(['Conviction', 'Criteria'])['FTT Amt'].agg(['sum', 'count']).sort_values(by='sum', ascending=False)

                           sum  count
Conviction Criteria
X-LC       X40       1204820.0      9
H-SC       XY24      1016830.0      5
M-SC       XY24       984226.0      7
H-SC       AR         936419.0      5
           XR         826301.0      7
X-SC       XY24       709092.0      3
X-MC       X40        662861.0      7
X-LC       X40N       538524.0      6
           XY24       448161.0      2
X-MC       X40N       348020.0      3
X-SC       X40N       318799.0      3
H-SC       OX40N      302304.0      4
           SR         282458.0      2
X-MC       XY25       259064.0      2
X-LC       XY25       253487.0      2
H-MC       XY24       251263.0      1
M-SC       OX40N      240194.0      5
X-MC       XY24       221190.0      2
X-SC       X40        213815.0      2
M-SC       XR         195824.0      2
M-LC       XR         165645.0      1
L-SC       OX40N      115039.0      1
           XR          96022.0      1
M-SC       AR          75634.0      1
M-MC       XY25        60476.0      1
X-LC       XR          58495.0      1
L-MC       XR          45319.0      1
H-LC       AR          35773.0      1
H-MC       AR          29723.0      1

In [32]:
# notebook execution time

end_time = time.time()
execution_time = round(end_time - start_time, 0)
print(f"Notebook execution time: {execution_time} seconds")

Notebook execution time: 32.0 seconds