<a href="https://colab.research.google.com/github/ankit-rathi/Quantvesting_v2/blob/main/myStocks_Portfolio_Analysis.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
'''
!pip install pandas==2.2.2 -qq
!pip install pyxirr -qq
!pip install ta -qq
!pip install yfinance==0.2.59 -qq
'''

'\n!pip install pandas==2.2.2 -qq\n!pip install pyxirr -qq\n!pip install ta -qq\n!pip install yfinance==0.2.59 -qq\n'

In [2]:
# import libraries

import numpy as np
import pandas as pd
import datetime
import warnings
warnings.filterwarnings('ignore')
import yfinance as yfin
import ta
import matplotlib.pyplot as plt
import requests

In [3]:
# notebook start time
import time
import datetime
import pytz

start_time = time.time()

# function to print date timestamp
def print_date_time():
  tz_NY = pytz.timezone('Asia/Kolkata')
  datetime_NY = datetime.datetime.now(tz_NY)
  print("Run date time (IST):", datetime_NY.strftime("%Y-%m-%d %H:%M:%S"))

In [4]:
# function to get booked and reserved amount
def get_amt():
  # fetch the JSON data from the URL
  url = "https://raw.githubusercontent.com/ankit-rathi/Tradevesting_v1/main/data/myPortfolioAmts.json"
  response = requests.get(url)
  pf_amts = response.json()  # parse the JSON data

  # extract values from the JSON
  py_booked_amt_dm = pf_amts["py_booked_amt_dm"]
  py_booked_amt_sv = pf_amts["py_booked_amt_sv"]
  cy_booked_amt_dm = pf_amts["cy_booked_amt_dm"]
  cy_booked_amt_sv = pf_amts["cy_booked_amt_sv"]
  reserve_amt_dm = pf_amts["reserve_amt_dm"]
  reserve_amt_sv = pf_amts["reserve_amt_sv"]

  # perform calculations
  py_booked_amt = py_booked_amt_dm + py_booked_amt_sv
  cy_booked_amt = cy_booked_amt_dm + cy_booked_amt_sv
  reserve_amt = reserve_amt_dm + reserve_amt_sv
  total_booked_amt = py_booked_amt + cy_booked_amt

  return total_booked_amt, reserve_amt, cy_booked_amt, py_booked_amt

gen_output = 0

In [5]:
# function to format the amount
def format_amt(number):
    abs_number = abs(number)

    if abs_number >= 1_00_00_000:  # Crores
        formatted_amt = f"{number / 1_00_00_000:.2f} C"
    elif abs_number >= 1_00_000:  # Lakhs
        formatted_amt = f"{number / 1_00_000:.2f} L"
    elif abs_number >= 1_000:  # Thousands
        formatted_amt = f"{number / 1_000:.2f} K"
    else:
        formatted_amt = f"{number:.2f}"

    return formatted_amt

# function to set start and end date
def get_start_end_date():
  start_date = (datetime.date.today() + datetime.timedelta(days=-365)).strftime('%Y-%m-%d')
  end_date = (datetime.date.today() + datetime.timedelta(days=1)).strftime('%Y-%m-%d')
  return start_date, end_date

# function to fetch my portfolio csv
def get_mypfs_df():
  mypfs_df = pd.read_csv('https://raw.githubusercontent.com/ankit-rathi/Tradevesting_v1/main/data/myPortfolioStocks.csv')
  return mypfs_df

# function to fetch my prospects csv
def get_mypps_df():
  mypps_df = pd.read_csv('https://raw.githubusercontent.com/ankit-rathi/Tradevesting_v1/main/data/myProspectsScrips.csv')
  return mypps_df

# function to fetch screener data
def get_myscreen_df():
  myscreen_df = pd.read_csv('https://raw.githubusercontent.com/ankit-rathi/Tradevesting_v1/main/data/myScreenerDB.csv')
  return myscreen_df

# function to fetch momentum data
def get_myinvmt_df():
  myinvmt_df = pd.read_csv('https://raw.githubusercontent.com/ankit-rathi/Tradevesting_v1/main/data/myInvestments.csv')
  return myinvmt_df

# function to get the stock ids
def get_stock_ids(df_pf):
  stock_n100 = df_pf['Symbol'].unique()

  exclude = ['CADILAHC','MMTC', 'MASFIN']

  stock_ids = df_pf[~df_pf['Symbol'].isin(exclude) ]['Symbol'].unique()

  #mypf = mypf[mypf.Forecast.notnull()]
  #stock_ids = mypf['Symbol'].unique()

  #stock_ids.sort()
  return stock_ids

# get features from screener data
def get_screener_features():
  myscreen_df = get_myscreen_df()
  cols = ['Symbol', 'EPS', 'MedPE', 'ROCE%', 'ROE%', 'CapType']
  return myscreen_df[cols]

# get relative strength
def get_relative_strength(stock_list):

    # Dictionary to store stock tickers and their corresponding percentage price change
    stock_changes = {}

    # Loop through each stock and fetch its price data
    for stock in stock_list:
        try:
            # Download the stock data for the given date range
            stock_data = yfin.Ticker(stock + '.NS').history(period='1mo', interval='1d')[map(str.title, ['open', 'close', 'low', 'high', 'volume'])]

            # Calculate the percentage change for the stock
            if len(stock_data) > 0:
                start_price = stock_data['Close'].iloc[0]
                end_price = stock_data['Close'].iloc[-1]
                percent_change = round(((end_price - start_price) / start_price) * 100, 2)
                stock_changes[stock] = percent_change
            else:
                stock_changes[stock] = np.nan  # If no data is available, set to NaN

        except Exception as e:
            print(f"Error fetching data for {stock}: {e}")
            stock_changes[stock] = np.nan

    # Create a DataFrame with stock tickers and their percentage changes
    df = pd.DataFrame(list(stock_changes.items()), columns=['Symbol', 'Percent_Change'])

    # Drop any stocks with missing data (NaN values)
    df = df.dropna()

    # Calculate the percentile rank based on percentage change
    df['RSP'] = round(df['Percent_Change'].rank(pct=True) * 100, 2)
    cols = ['Symbol', 'RSP']
    df = df[cols]
    # Sort by percentile rank (optional)
    df = df.sort_values(by='RSP', ascending=False).reset_index(drop=True)

    return df

In [6]:
# function to get stock technicals
def stock_prec_dev(stock_symbol):
    #stock_symbol = 'ULTRACEMCO.NS'
    short_window = 20
    mid_window = 50
    long_window = 200
    moving_avg = 'SMA'

    start = datetime.datetime(*map(int, start_date.split('-')))
    end = datetime.datetime(*map(int, end_date.split('-')))

    stock_df = yfin.Ticker(stock_symbol + '.NS').history(period='max', interval='1d')[map(str.title, ['open', 'close', 'low', 'high', 'volume'])]

    stock_df['Max'] = round(max(stock_df['Close']),2)
    stock_df = stock_df[(stock_df.index <= end_date) & (stock_df.index >= start_date)]
    stock_df['200_SMA'] = round(stock_df['Close'].rolling(window = 200, min_periods = 1).mean(),0)
    stock_df['Dev%_200'] = round((stock_df['Close'] - stock_df['200_SMA'])*100/stock_df['200_SMA'],2)
    stock_df.dropna(axis = 0, inplace = True) # remove any null rows

    stock_df['20_SMA'] = stock_df['Close'].rolling(window=20).mean()
    stock_df['50_SMA'] = stock_df['Close'].rolling(window=50).mean()
    stock_df['Symbol'] = stock_symbol

    stock_df['Close'] = round(stock_df['Close'],2)
    stock_df['Min'] = round(min(stock_df['Close']),2)
    stock_df['RSI_14'] = ta.momentum.RSIIndicator(close=stock_df['Close'], window=14).rsi()
    stock_df['RSI_14'] = round(stock_df['RSI_14'],0)
    stock_df['Prev_Close'] = stock_df['Close'].shift(1)
    stock_df.drop(['Open', 'Low', 'High', 'Volume'], axis=1, inplace=True)
    stock_df = stock_df.tail(1)

    max_SMA = max(stock_df['20_SMA'].item(), stock_df['50_SMA'].item(), stock_df['200_SMA'].item())
    min_SMA = min(stock_df['20_SMA'].item(), stock_df['50_SMA'].item(), stock_df['200_SMA'].item())
    ABS_Spread = max_SMA - min_SMA
    stock_df['Spread%'] = round((ABS_Spread / stock_df['200_SMA'].item()) * 100,2)

    return stock_df

# function to compute stock attributes
def get_common_features(stock_ids, df_mypf):

  df_prec_dev = pd.DataFrame()
  df_tmp = get_screener_features()
  df_rs = get_relative_strength(stock_ids)

  for stock_id in stock_ids:
      tmp = stock_prec_dev(stock_id)
      tmp = tmp.reset_index()
      df_prec_dev = pd.concat([df_prec_dev, tmp], ignore_index = True)
  df_prec_dev = pd.merge(df_prec_dev, df_mypf, on= 'Symbol')
  df_prec_dev = pd.merge(df_prec_dev, df_tmp, on= 'Symbol', how='left')
  df_prec_dev = pd.merge(df_prec_dev, df_rs, on= 'Symbol', how='left')
  #print(df_prec_dev.columns)
  df_prec_dev['Curr_PE'] = round(df_prec_dev['Close']/df_prec_dev['EPS'],1)
  df_prec_dev['Dev%_PE'] = round((df_prec_dev['Curr_PE'] - df_prec_dev['MedPE'])*100/df_prec_dev['MedPE'],2)
  df_prec_dev['Conviction'] = df_prec_dev['Conviction'] + '-' + df_prec_dev['CapType']
  return df_prec_dev

# function to arrange stock features
def arrange_features(df_stocks, common_cols, diff_cols):
  df_stocks_common = df_stocks[common_cols].drop_duplicates()
  df_stocks_diff = df_stocks[diff_cols]
  df_stocks_diff['Investment'] = df_stocks_diff['AvgCost'] * df_stocks_diff['Shares']
  df_stocks_diff = df_stocks_diff.groupby(['Symbol'])[['Shares', 'Investment']].aggregate(['sum']).reset_index()
  df_stocks_diff.columns = ['Symbol', 'Shares', 'Investment']
  df_stocks_diff['AvgCost'] = round(df_stocks_diff['Investment']/df_stocks_diff['Shares'],2)
  df_stocks = pd.merge(df_stocks_diff, df_stocks_common, on='Symbol')
  return df_stocks

# plot fact distribution across dimension
def plot_pie_chart(df, dimension, fact):
  # grouping the data by category and calculating the sum of fact for each type
  grouped_data = df.groupby(dimension)[fact].sum()

  # sorting the grouped data in descending order
  grouped_data = grouped_data.sort_values(ascending=False)

  # creating a pie chart
  grouped_data.plot.pie(autopct='%1.1f%%', startangle=90, figsize=(6, 6))

  # adding a title and displaying the plot
  plt.title(f'{dimension} {fact} Distribution')
  plt.ylabel('')  # To hide the y-label
  plt.show()

In [7]:
# function to get portfolio features

def get_portfolio_features(df_common_features):

  print_date_time()
  print('-------------------')

  #df_common_features["Target"] = df_common_features["Target"].fillna(df_common_features["Max"])
  df_common_features['NTT'] = np.where(df_common_features['Strategy']== 'NTT', df_common_features["Target"], df_common_features['Max'])
  df_common_features['LTT'] = np.where(df_common_features['Strategy']== 'BTT', df_common_features["Target"], df_common_features['Max'])
  df_common_features['BOL'] = df_common_features['Min']

  tmp_df = df_common_features[df_common_features['Symbol'].isin(mypf_df[mypf_df['InPortfolio'] != 'NA'].Symbol.values)]
  print('qualified stocks: '+str(len(tmp_df['Symbol'].unique())))
  tmp_df1 = tmp_df[tmp_df['LatestQtr'] == 1]
  print('with latest results: '+str(len(tmp_df1['Symbol'].unique())))
  tmp_df1 = tmp_df1[tmp_df1['StarStock'] == 1]
  print('still star stocks: '+str(len(tmp_df1['Symbol'].unique())))
  tmp_df['Investment'] = tmp_df['AvgCost'] * tmp_df['Shares']
  tmp_df['Current'] = round(tmp_df['Close'] * tmp_df['Shares'],0)
  tmp_df['Previous'] = tmp_df['Prev_Close'] * tmp_df['Shares']
  tmp_df['EstimatedST'] = tmp_df['NTT'] * tmp_df['Shares']
  tmp_df['EstimatedLT'] = tmp_df['LTT'] * tmp_df['Shares']
  tmp_df['Current P/L'] = round((tmp_df['Current'] - tmp_df['Investment']),0)
  tmp_df['Today P/L%'] = round((tmp_df['Current'] - tmp_df['Previous'])*100/tmp_df['Previous'],2)
  tmp_df['Current P/L%'] = round((tmp_df['Current'] - tmp_df['Investment'])*100/tmp_df['Investment'],2)
  tmp_df['EstimatedST P/L%'] = round((tmp_df['EstimatedST'] - tmp_df['Investment'])*100/tmp_df['Investment'],2)
  tmp_df['EstimatedLT P/L%'] = round((tmp_df['EstimatedLT'] - tmp_df['Investment'])*100/tmp_df['Investment'],2)
  tmp_df['NTT%'] = round((tmp_df['NTT'] - tmp_df['Close'])*100/tmp_df['Close'],2)
  tmp_df['LTT%'] = round((tmp_df['LTT'] - tmp_df['Close'])*100/tmp_df['Close'],2)
  tmp_df['Gained%'] = round((tmp_df['Close'] - tmp_df['BOL'])*100/tmp_df['BOL'],2)
  investment = round(sum(tmp_df['AvgCost']*tmp_df['Shares']),0)
  current = round(sum(tmp_df['Close']*tmp_df['Shares']),0)
  tmp_df['InitAlloc%'] = round(tmp_df['Investment']*100/investment,2)
  tmp_df['CurrAlloc%'] = round(tmp_df['Current']*100/current,2)
  tmp_df['FTT'] = tmp_df['LTT']
  tmp_df.loc[tmp_df['Strategy'] == 'NTT', 'FTT'] = tmp_df['NTT']
  tmp_df['FTT%'] = tmp_df['LTT%']
  tmp_df.loc[tmp_df['Strategy'] == 'NTT', 'FTT%'] = tmp_df['NTT%']
  tmp_df['FTT Amt'] = round(tmp_df['FTT%'] * tmp_df['Current']/100,0)
  tmp_df['OTT%'] = round((tmp_df['FTT'] - tmp_df['AvgCost'])*100/tmp_df['AvgCost'],2)
  tmp_df['RRR Ind'] = round(tmp_df['Current P/L']/tmp_df['FTT Amt'],2)
  tmp_df['Risk Ind'] = round(tmp_df['Current P/L%']*tmp_df['CurrAlloc%'],0)

  return tmp_df

# function to print portfolio features
def print_portfolio_stats(df_portfolio_features, myinvmt_df):
  from pyxirr import xirr

  total_booked_amt, reserve_amt, cy_booked_amt, py_booked_amt = get_amt()

  dates = myinvmt_df['Date'].values
  dates = np.append(dates, datetime.date.today().strftime('%d-%b-%y'))
  investment = myinvmt_df['Investment'].values
  dates= pd.to_datetime(dates)

  current = round(sum(df_portfolio_features['Close']*df_portfolio_features['Shares']),0) + reserve_amt
  investment_xirr = np.append(investment, current)
  cagr = round(xirr(pd.DataFrame({"dates": dates, "amounts": investment_xirr}))*100,2)

  investment = -sum(investment)
  invested = round(sum(df_portfolio_features['AvgCost']*df_portfolio_features['Shares']),0) + reserve_amt
  previous = round(sum(df_portfolio_features['Prev_Close']*df_portfolio_features['Shares']),0) + reserve_amt
  cy_invested = investment + py_booked_amt

  today_pnl_amount = current-previous
  today_pnl_percentage = round((current-previous)*100/previous,2)

  curr_pnl_amount = current-invested
  curr_pnl_percentage = round((curr_pnl_amount)*100/(cy_invested),2)

  cy_pnl_amount = cy_booked_amt + curr_pnl_amount
  cy_pnl_percentage = round((cy_pnl_amount)*100/cy_invested,2)

  overall_pnl_amount = total_booked_amt + curr_pnl_amount
  overall_pnl_percentage = round((overall_pnl_amount)*100/investment,2)

  estimate_st = round(sum(df_portfolio_features['FTT']*df_portfolio_features['Shares']),0)  + reserve_amt
  est_st_pnl_amount = estimate_st-current
  est_st_pnl_percentage = round((est_st_pnl_amount)*100/current,2)

  estimate_lt = round(sum(df_portfolio_features['LTT']*df_portfolio_features['Shares']),0)  + reserve_amt
  est_lt_pnl_amount = estimate_lt-current
  est_lt_pnl_percentage = round((est_lt_pnl_amount)*100/current,2)

  total_profit = round(sum(df_portfolio_features[df_portfolio_features['Current P/L%'] > 0]['Current']) - sum(df_portfolio_features[df_portfolio_features['Current P/L%'] > 0]['Investment']),0)
  total_loss = round(sum(df_portfolio_features[df_portfolio_features['Current P/L%'] < 0]['Current']) - sum(df_portfolio_features[df_portfolio_features['Current P/L%'] < 0]['Investment']),0)

  cy_booked_percentage = round((cy_booked_amt)*100/current,2)
  py_booked_percentage = round((py_booked_amt)*100/investment,2)
  total_booked_percentage = round((total_booked_amt)*100/investment,2)

  print('-------------------')
  print('Initial Investment: ', format_amt(investment))
  print('CY Investment: ', format_amt(cy_invested))
  print('Reserve: ', format_amt(reserve_amt))
  print('Current: ',  format_amt(current))
  print('-------------------')
  print('Today PnL: '+ '{} ({}%)'.format(format_amt(today_pnl_amount), today_pnl_percentage))
  print('Current PnL: '+ '{} ({}%)'.format(format_amt(curr_pnl_amount), curr_pnl_percentage))
  print('CY Booked + Current PnL: '+ '{} ({}%)'.format(format_amt(cy_pnl_amount), cy_pnl_percentage))
  print('-------------------')
  print('Total profit: ', format_amt(total_profit))
  print('Total loss: ', format_amt(total_loss))
  print('-------------------')
  print('Total Booked + Current PnL: '+ '{} ({}%)'.format(format_amt(overall_pnl_amount), overall_pnl_percentage))
  print('Total Booked PnL: '+ '{} ({}%)'.format(format_amt(total_booked_amt), total_booked_percentage))
  print('Curr Year Booked PnL: '+ '{} ({}%)'.format(format_amt(cy_booked_amt), cy_booked_percentage))
  print('Prev Year Booked PnL: '+ '{} ({}%)'.format(format_amt(py_booked_amt), py_booked_percentage))
  print('===================')
  print('Est FTT: ',  format_amt(estimate_st))
  print('Est FTT PnL: '+ '{} ({}%)'.format(format_amt(est_st_pnl_amount), est_st_pnl_percentage))

  print('===================')
  print('Deployed: ', format_amt(investment))

  print('Current: ', format_amt(current))

  print('CAGR/XIRR %: '+'{}%'.format(cagr))

In [8]:
# get start and end date
start_date, end_date = get_start_end_date()

# get portfolio and prospects data
mypfs_df = get_mypfs_df()
mypps_df = get_mypps_df()
myinvmt_df = get_myinvmt_df()

# merge above datasets
mypf_df = pd.merge(mypfs_df, mypps_df, on="Symbol")

# seggregate dm and sv portfolio
dm_pf = mypf_df[mypf_df['InPortfolio'] == 'DM']
sv_pf = mypf_df[mypf_df['InPortfolio'] == 'SV']

# build portfolio stock dataframe
dm_stocks = get_stock_ids(dm_pf)
sv_stocks = get_stock_ids(sv_pf)
df_stocks = pd.concat([dm_pf,sv_pf], ignore_index = True)

# arrange common and diff stock features
common_cols = ['Symbol', 'Target', 'Criteria', 'Strategy', 'CumlRnk', 'LatestQtr', 'StarStock', 'Conviction', 'Category', 'InFolio', 'XIRR', 'MBQ']
diff_cols = ['Symbol', 'AvgCost', 'Shares']
df_stocks = arrange_features(df_stocks, common_cols, diff_cols)

# get common features
stock_ids = df_stocks['Symbol'].values
df_common_features = get_common_features(stock_ids, df_stocks)

df_common_features.reset_index(drop=True, inplace=True)
df_common_features.drop(['Date'], axis=1, inplace=True)
# get and print portfolio features
df_portfolio_features = get_portfolio_features(df_common_features)

print_portfolio_stats(df_portfolio_features, myinvmt_df)

df = df_portfolio_features
#plot_pie_chart(df, 'CapType', 'Current')
list_ox40n = list(df[df['MBQ'].str.contains('OX40N', na=False)]['Symbol'].values)

Run date time (IST): 2026-04-13 10:28:07
-------------------
qualified stocks: 86
with latest results: 26
still star stocks: 16
-------------------
Initial Investment:  1.36 C
CY Investment:  1.62 C
Reserve:  1.61 K
Current:  1.37 C
-------------------
Today PnL: -90.50 K (-0.65%)
Current PnL: -39.75 L (-24.47%)
CY Booked + Current PnL: -23.86 L (-14.69%)
-------------------
Total profit:  1.41 L
Total loss:  -41.16 L
-------------------
Total Booked + Current PnL: 3.12 L (2.3%)
Total Booked PnL: 42.87 L (31.64%)
Curr Year Booked PnL: 15.89 L (11.57%)
Prev Year Booked PnL: 26.98 L (19.91%)
===================
Est FTT:  2.48 C
Est FTT PnL: 1.11 C (80.44%)
===================
Deployed:  1.36 C
Current:  1.37 C
CAGR/XIRR %: 0.66%

In [9]:
# top 5 near their targets
cols = ['Symbol', 'Today P/L%', 'Current P/L%', 'FTT%', 'OTT%', 'FTT Amt', 'Current P/L', 'Current', 'FTT', 'Dev%_PE', 'RSI_14','Conviction', 'Spread%',  'CumlRnk', 'RRR Ind', 'CurrAlloc%', 'Gained%', 'Criteria', 'Strategy', 'Category']
df_tmp = df_portfolio_features[~df_portfolio_features['Symbol'].isin(['ENRIN','BLUSPRING','DIGITIDE'])]
df_tmp = df_tmp.sort_values(by = 'FTT Amt', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
50,MASFIN,-0.15,-5.70,28.91,21.57,26713.0,-5580.0,92400.0,397.04,-18.70,52.0,H-SC,4.67,167.0,-0.21,0.67,19.40,XR,ATH,FINANCE
5,ANGELONE,-0.77,14.27,8.67,24.18,30217.0,43525.0,348525.0,303.00,-83.35,70.0,X-SC,3.93,97.0,1.44,2.54,33.34,X40N,NTT,FINANCE
77,TTKPRESTIG,-0.26,-38.12,61.75,0.09,38509.0,-38414.0,62363.0,770.00,44.72,48.0,M-SC,22.28,250.0,-1.00,0.45,11.05,OX40N,NTT,DURABLES
67,SONACOMS,0.36,-3.77,44.54,39.09,43357.0,-3815.0,97344.0,804.02,-23.71,64.0,M-MC,8.40,193.0,-0.09,0.71,37.71,AR,ATH,AUTO
37,ICICIGI,-0.69,-6.05,27.03,19.34,50817.0,-12107.0,188002.0,2252.93,-21.06,47.0,X-MC,7.67,66.0,-0.24,1.37,5.00,X40,ATH,INSURANCE

In [10]:
# top 5 today
df_tmp = df_portfolio_features.sort_values(by = 'Today P/L%', ascending=False)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
7,ATULAUTO,16.58,-12.43,66.22,45.57,114319.0,-24497.0,172635.0,844.0,3743.24,69.0,M-SC,8.45,248.0,-0.21,1.26,32.85,XY24,NTT,AUTO
55,RAJESHEXPO,4.99,-77.74,349.50,0.07,106734.0,-106638.0,30539.0,518.0,1018.69,56.0,L-SC,44.10,268.0,-1.00,0.22,43.37,OX40N,NTT,JEWELLERY
12,BATAINDIA,1.75,-53.04,187.91,35.20,113543.0,-68246.0,60424.0,2096.0,-20.72,56.0,X-SC,33.95,91.0,-0.60,0.44,19.84,X40,NTT,FOOTWEAR
58,RELAXO,1.68,-61.79,298.64,52.31,165626.0,-89700.0,55460.0,1176.0,-59.35,52.0,X-SC,33.23,92.0,-0.54,0.40,24.00,X40N,NTT,FOOTWEAR
82,VOLTAS,1.21,4.16,39.39,45.20,78672.0,7983.0,199725.0,1856.0,19.24,48.0,X-MC,6.53,79.0,0.10,1.45,11.24,XY25,NTT,AC

In [11]:
# bottom 5 today
df_tmp = df_portfolio_features.sort_values(by = 'Today P/L%', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
71,TANLA,-3.23,-48.00,322.50,119.69,454051.0,-129970.0,140791.0,1943.92,-47.43,57.0,H-SC,25.53,147.0,-0.29,1.03,21.90,AR,ATH,IT
25,EASEMYTRIP,-2.87,-57.06,239.33,45.70,181692.0,-100898.0,75917.0,26.40,-21.23,59.0,M-SC,13.44,204.0,-0.56,0.55,32.99,XY24,NTT,TRAVEL
74,TITAGARH,-2.33,-34.69,123.15,45.74,194779.0,-84013.0,158164.0,1548.00,-12.96,56.0,H-SC,22.18,175.0,-0.43,1.15,20.67,XY24,NTT,ENGINEERING
34,HDFCBANK,-2.32,-5.31,35.57,28.37,79112.0,-12473.0,222412.0,1073.00,-19.55,46.0,X-LC,17.08,26.0,-0.16,1.62,8.19,X40,BTT,BANKS
46,JIOFIN,-2.22,-21.09,62.74,28.43,147704.0,-62905.0,235422.0,387.00,-22.30,48.0,X-LC,19.32,34.0,-0.43,1.71,6.11,XY24,BTT,FINANCE

In [12]:
# top 5 to exit based on CumlRnk
df_tmp = df_portfolio_features[~df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])]
df_tmp = df_tmp[(df_tmp['Current P/L%'] > -1) & (df_tmp['Current P/L%'] < 1)].sort_values(by = 'CumlRnk', ascending=False)
df_tmp[cols].head()

Empty DataFrame
Columns: [Symbol, Today P/L%, Current P/L%, FTT%, OTT%, FTT Amt, Current P/L, Current, FTT, Dev%_PE, RSI_14, Conviction, Spread%, CumlRnk, RRR Ind, CurrAlloc%, Gained%, Criteria, Strategy, Category]
Index: []

In [13]:
# OX40N stocks to exit
df_tmp = df_portfolio_features[(df_portfolio_features['Symbol'].isin(list_ox40n))].sort_values(by = 'Current P/L%', ascending=False)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
26,FINCABLES,-1.01,6.29,95.61,107.91,150041.0,9286.0,156930.0,1641.55,-4.62,51.0,M-SC,1.53,220.0,0.06,1.14,18.06,OX40N,ATH,CABLES
66,SIS,0.41,-30.18,73.68,21.26,57117.0,-33512.0,77520.0,528.00,1820.73,59.0,H-SC,13.87,168.0,-0.59,0.56,15.26,OX40N,NTT,MISC
18,CERA,-1.20,-33.32,85.78,23.89,100620.0,-58603.0,117300.0,9475.00,-35.56,61.0,H-SC,16.85,153.0,-0.58,0.85,12.72,OX40N,NTT,CERAMICS
48,KANSAINER,-0.62,-36.47,78.63,13.47,134698.0,-98361.0,171306.0,340.00,-45.39,56.0,H-SC,22.90,162.0,-0.73,1.25,19.66,XY24,NTT,PAINTS
72,TATAELXSI,-1.17,-36.69,108.53,32.03,90589.0,-48366.0,83469.0,9161.00,-20.87,51.0,H-SC,20.65,158.0,-0.53,0.61,10.47,OX40N,NTT,IT

In [14]:
# top 5 to book for rotation
df_tmp = df_portfolio_features[(df_portfolio_features['Current P/L%'] > 20) ].sort_values(by = 'CumlRnk', ascending=False)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
1,ABB,0.12,26.01,15.52,45.57,51164.0,68045.0,329664.0,7934.0,-19.03,71.0,H-MC,15.77,125.0,1.33,2.4,46.39,AR,NTT,ELECTRICAL

In [15]:
# top 5 to monitor for exit
df_tmp = df_portfolio_features[~df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])]
df_tmp = df_tmp[(df_tmp['Current P/L%'] > 0) ].sort_values(by = 'Dev%_PE', ascending=False)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
26,FINCABLES,-1.01,6.29,95.61,107.91,150041.0,9286.0,156930.0,1641.55,-4.62,51.0,M-SC,1.53,220.0,0.06,1.14,18.06,OX40N,ATH,CABLES
1,ABB,0.12,26.01,15.52,45.57,51164.0,68045.0,329664.0,7934.00,-19.03,71.0,H-MC,15.77,125.0,1.33,2.40,46.39,AR,NTT,ELECTRICAL

In [16]:
# top 5 to book for rotation from weak conviction
df_tmp = df_portfolio_features[~df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])]
df_tmp = df_tmp[~df_tmp['Criteria'].isin(['XY25','XY24','X40', 'X40N'])].sort_values(by = 'RRR Ind', ascending=False)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
1,ABB,0.12,26.01,15.52,45.57,51164.0,68045.0,329664.0,7934.00,-19.03,71.0,H-MC,15.77,125.0,1.33,2.40,46.39,AR,NTT,ELECTRICAL
26,FINCABLES,-1.01,6.29,95.61,107.91,150041.0,9286.0,156930.0,1641.55,-4.62,51.0,M-SC,1.53,220.0,0.06,1.14,18.06,OX40N,ATH,CABLES
40,INDIAMART,0.17,-9.61,128.70,106.72,143482.0,-11850.0,111486.0,4810.62,-59.18,53.0,H-SC,13.03,140.0,-0.08,0.81,7.11,AR,ATH,MISC
85,ZYDUSLIFE,-0.05,-3.52,40.57,35.63,82034.0,-7370.0,202204.0,1286.17,-16.22,57.0,H-MC,6.05,120.0,-0.09,1.47,12.57,AR,ATH,PHARMA
67,SONACOMS,0.36,-3.77,44.54,39.09,43357.0,-3815.0,97344.0,804.02,-23.71,64.0,M-MC,8.40,193.0,-0.09,0.71,37.71,AR,ATH,AUTO

In [17]:
# top 5 to accumulate based on lowest RSI_14
df_tmp = df_portfolio_features[df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])].sort_values(by = 'RSI_14', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
53,PGHH,-0.68,-27.16,81.22,32.01,126326.0,-57984.0,155536.0,17616.87,-50.75,39.0,X-MC,21.22,57.0,-0.46,1.13,6.38,X40,ATH,FMCG
21,DABUR,-1.71,-16.27,71.63,43.70,148776.0,-40367.0,207701.0,735.00,-24.09,41.0,X-MC,14.00,70.0,-0.27,1.51,4.34,XY24,BTT,FMCG
59,RELIANCE,-1.87,-14.95,47.32,25.30,80882.0,-30038.0,170925.0,1952.00,-17.34,41.0,X-LC,5.06,21.0,-0.37,1.24,7.34,XY25,BTT,REFINERIES
2,ABBOTINDIA,-0.21,-13.70,36.81,18.07,56816.0,-24505.0,154350.0,35195.00,-26.49,42.0,X-MC,11.51,58.0,-0.43,1.12,0.94,X40,ATH,PHARMA
78,UNITDSPR,-1.73,-8.45,31.91,20.77,68404.0,-19780.0,214364.0,1644.00,-18.80,42.0,X-MC,5.78,64.0,-0.29,1.56,2.26,X40N,NTT,BREWERIES

In [18]:
# top 5 to accumulate based on Spread and CumlRnk
df_tmp = df_portfolio_features[df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])]
df_tmp = df_tmp[(df_tmp['CumlRnk'] < 100)].sort_values(by = 'Spread%', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
65,SIEMENS,-1.27,-10.12,39.64,25.51,66306.0,-18825.0,167270.0,4671.50,40.45,60.0,H-LC,1.43,51.0,-0.28,1.22,19.05,AR,ATH,ELECTRICAL
5,ANGELONE,-0.77,14.27,8.67,24.18,30217.0,43525.0,348525.0,303.00,-83.35,70.0,X-SC,3.93,97.0,1.44,2.54,33.34,X40N,NTT,FINANCE
24,DMART,-1.02,4.70,23.78,29.60,62144.0,11730.0,261330.0,5391.45,-11.75,64.0,X-LC,4.39,14.0,0.19,1.90,19.45,X40N,ATH,FMCG
59,RELIANCE,-1.87,-14.95,47.32,25.30,80882.0,-30038.0,170925.0,1952.00,-17.34,41.0,X-LC,5.06,21.0,-0.37,1.24,7.34,XY25,BTT,REFINERIES
78,UNITDSPR,-1.73,-8.45,31.91,20.77,68404.0,-19780.0,214364.0,1644.00,-18.80,42.0,X-MC,5.78,64.0,-0.29,1.56,2.26,X40N,NTT,BREWERIES

In [19]:
# top 5 to accumulate based on lowest Gained%
df_tmp = df_portfolio_features[df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])].sort_values(by = 'Gained%', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
2,ABBOTINDIA,-0.21,-13.70,36.81,18.07,56816.0,-24505.0,154350.0,35195.0,-26.49,42.0,X-MC,11.51,58.0,-0.43,1.12,0.94,X40,ATH,PHARMA
78,UNITDSPR,-1.73,-8.45,31.91,20.77,68404.0,-19780.0,214364.0,1644.0,-18.80,42.0,X-MC,5.78,64.0,-0.29,1.56,2.26,X40N,NTT,BREWERIES
35,HINDUNILVR,-1.25,-17.21,37.29,13.67,79364.0,-44233.0,212830.0,2922.0,-38.48,46.0,X-LC,11.94,9.0,-0.56,1.55,3.71,XY25,NTT,FMCG
45,ITC,-1.45,-21.02,50.74,19.06,136321.0,-71500.0,268666.0,452.0,-56.73,46.0,X-LC,19.57,1.0,-0.52,1.96,4.22,X40,NTT,FMCG
21,DABUR,-1.71,-16.27,71.63,43.70,148776.0,-40367.0,207701.0,735.0,-24.09,41.0,X-MC,14.00,70.0,-0.27,1.51,4.34,XY24,BTT,FMCG

In [20]:
# top 5 to accumulate based on lowest CurrAlloc%
df_tmp = df_portfolio_features[df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])].sort_values(by = 'CurrAlloc%', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
58,RELAXO,1.68,-61.79,298.64,52.31,165626.0,-89700.0,55460.0,1176.00,-59.35,52.0,X-SC,33.23,92.0,-0.54,0.40,24.00,X40N,NTT,FOOTWEAR
12,BATAINDIA,1.75,-53.04,187.91,35.20,113543.0,-68246.0,60424.0,2096.00,-20.72,56.0,X-SC,33.95,91.0,-0.60,0.44,19.84,X40,NTT,FOOTWEAR
54,QUESS,-0.12,-20.86,119.73,73.90,101191.0,-22277.0,84516.0,424.00,-57.58,58.0,X-SC,21.58,80.0,-0.22,0.62,13.69,XY24,NTT,MISC
36,HONAUT,0.49,-25.52,103.16,51.31,148164.0,-49213.0,143625.0,58357.33,-38.04,50.0,X-SC,19.29,90.0,-0.33,1.05,9.12,X40N,ATH,ELECTRICAL
2,ABBOTINDIA,-0.21,-13.70,36.81,18.07,56816.0,-24505.0,154350.0,35195.00,-26.49,42.0,X-MC,11.51,58.0,-0.43,1.12,0.94,X40,ATH,PHARMA

In [21]:
# top 5 to accumulate based on CumlRnk
df_tmp = df_portfolio_features.sort_values(by = 'CumlRnk', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
45,ITC,-1.45,-21.02,50.74,19.06,136321.0,-71500.0,268666.0,452.00,-56.73,46.0,X-LC,19.57,1.0,-0.52,1.96,4.22,X40,NTT,FMCG
73,TCS,-1.48,-26.99,73.37,26.57,248151.0,-125055.0,338218.0,4311.58,-38.05,47.0,X-LC,17.99,2.0,-0.50,2.46,5.56,X40,ATH,IT
43,INFY,-1.33,-13.18,54.63,34.24,148396.0,-41249.0,271639.0,1972.00,-31.79,43.0,X-LC,14.23,3.0,-0.28,1.98,4.46,X40,NTT,IT
75,TMPV,-0.32,-22.26,75.70,36.58,209398.0,-79226.0,276615.0,600.00,-83.62,57.0,X-LC,12.35,4.0,-0.38,2.01,15.29,XY24,NTT,AUTO
33,HCLTECH,-1.32,-7.07,33.25,23.83,74754.0,-17100.0,224824.0,1908.19,-2.40,55.0,X-LC,9.38,8.0,-0.23,1.64,9.16,X40,ATH,IT

In [22]:
# top 5 for average up
df_tmp = df_portfolio_features[(df_portfolio_features['Dev%_200'] > 5)].sort_values(by = 'CurrAlloc%', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
67,SONACOMS,0.36,-3.77,44.54,39.09,43357.0,-3815.0,97344.0,804.02,-23.71,64.0,M-MC,8.40,193.0,-0.09,0.71,37.71,AR,ATH,AUTO
65,SIEMENS,-1.27,-10.12,39.64,25.51,66306.0,-18825.0,167270.0,4671.50,40.45,60.0,H-LC,1.43,51.0,-0.28,1.22,19.05,AR,ATH,ELECTRICAL
7,ATULAUTO,16.58,-12.43,66.22,45.57,114319.0,-24497.0,172635.0,844.00,3743.24,69.0,M-SC,8.45,248.0,-0.21,1.26,32.85,XY24,NTT,AUTO
62,SATIN,0.77,-10.92,70.45,51.83,173383.0,-30176.0,246108.0,274.00,-19.84,67.0,H-SC,2.81,159.0,-0.17,1.79,19.89,XY24,NTT,FINANCE
24,DMART,-1.02,4.70,23.78,29.60,62144.0,11730.0,261330.0,5391.45,-11.75,64.0,X-LC,4.39,14.0,0.19,1.90,19.45,X40N,ATH,FMCG

In [23]:
# top 5 RSP
df_tmp = df_portfolio_features.sort_values(by = 'RSP', ascending=False)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
5,ANGELONE,-0.77,14.27,8.67,24.18,30217.0,43525.0,348525.0,303.00,-83.35,70.0,X-SC,3.93,97.0,1.44,2.54,33.34,X40N,NTT,FINANCE
7,ATULAUTO,16.58,-12.43,66.22,45.57,114319.0,-24497.0,172635.0,844.00,3743.24,69.0,M-SC,8.45,248.0,-0.21,1.26,32.85,XY24,NTT,AUTO
80,VALIANTORG,-1.89,-46.49,225.46,74.15,197374.0,-76062.0,87543.0,838.00,-257.21,57.0,H-SC,21.91,145.0,-0.39,0.64,30.28,XR,NTT,CHEMICALS
52,PAGEIND,0.22,-5.75,42.30,34.11,106996.0,-15434.0,252945.0,51418.64,-32.42,72.0,X-MC,16.56,55.0,-0.14,1.84,19.65,X40,ATH,APPARELS
31,HATHWAY,-0.44,-37.58,177.63,73.29,120540.0,-40860.0,67860.0,31.40,689.86,65.0,H-SC,23.26,171.0,-0.34,0.49,27.51,XR,NTT,ENTERTAINMENT

In [24]:
# Top N allocation
df_tmp = df_portfolio_features.sort_values(by = 'CurrAlloc%', ascending=False)
top_n_values = [10, 25, 50]

sum_df = pd.DataFrame({
    'Top_N': top_n_values,
    'Sum_Alloc%': [df_tmp['CurrAlloc%'].head(n).sum() for n in top_n_values]
})

sum_df

   Top_N  Sum_Alloc%
0     10       21.04
1     25       45.86
2     50       77.80

In [25]:
# market-cap-wise allocation
df_tmp = df_portfolio_features[cols]
df_tmp.groupby(df_tmp['Conviction'].str[-2:])['CurrAlloc%'].sum().sort_values(ascending=False)

Conviction
SC    45.14
MC    29.56
LC    25.29
Name: CurrAlloc%, dtype: float64

In [26]:
# criteria-wise allocation
df_portfolio_features.groupby('Criteria')['CurrAlloc%'].sum().sort_values(ascending=False)

Criteria
XY24     27.31
X40      24.86
X40N     15.56
AR        9.37
XR        8.35
XY25      7.01
OX40N     6.74
SR        0.79
Name: CurrAlloc%, dtype: float64

In [27]:
# conviction-wise allocation
df_portfolio_features.groupby('Conviction')['CurrAlloc%'].sum().sort_values(ascending=False)

Conviction
X-LC    23.05
X-MC    21.99
H-SC    21.94
X-SC    12.41
M-SC    10.20
H-MC     5.14
M-MC     2.09
H-LC     1.22
M-LC     1.02
L-SC     0.59
L-MC     0.34
Name: CurrAlloc%, dtype: float64

In [28]:
# sector-wise stats
df_tmp = df_portfolio_features.groupby('Category')[['CurrAlloc%', 'Current', 'Current P/L', 'FTT Amt']].sum().sort_values(by=['Current', 'Current P/L'], ascending=False)
df_tmp['Current P/L%'] = round(df_tmp['Current P/L'] * 100 / df_tmp['Current'], 2)
df_tmp['FTT%'] = round(df_tmp['FTT Amt'] * 100 / df_tmp['Current'], 2)
cols = ['CurrAlloc%', 'Current P/L%', 'FTT%']
df_tmp[cols].sort_values(by=['CurrAlloc%'], ascending=False)

               CurrAlloc%  Current P/L%    FTT%
Category
FMCG                14.72        -23.47   67.28
FINANCE             13.46        -16.30   63.69
IT                  11.66        -40.77  112.40
MISC                 7.15        -36.62   95.96
ELECTRICAL           6.61         -6.72   47.59
PAINTS               5.28        -36.01   59.63
BANKS                4.57        -22.69   84.97
INSURANCE            4.52         -9.46   46.92
PHARMA               4.00         -6.92   40.57
AUTO                 3.98        -19.67   67.16
AC                   1.99        -16.65   48.27
HEALTHCARE           1.93        -34.54   69.65
APPARELS             1.84         -6.10   42.30
TRAVEL               1.82        -78.23  167.47
FOOTWEAR             1.82        -76.26  146.94
DURABLES             1.72        -63.59  103.39
BREWERIES            1.56         -9.23   31.91
REALTY               1.45        -11.35   29.65
CERAMICS             1.34        -65.99  116.42
REFINERIES           1.24        -17.57   47.32
CEMENT               1.22        -59.86  179.46
ENGINEERING          1.15        -53.12  123.15
CABLES               1.14          5.92   95.61
JEWELLERY            1.10       -112.08  185.77
CHEMICALS            1.07        -80.05  226.93
ENTERTAINMENT        0.83        -68.46  168.93
TEXTILES             0.45        -48.57   90.93
HOTELS               0.37       -126.42  206.28

In [29]:
# money to be made criteria-wise
df_portfolio_features.groupby('Criteria')['FTT Amt'].agg(['sum', 'count']).sort_values(by='sum', ascending=False)

                sum  count
Criteria
XY24      3845855.0     21
X40       1760872.0     16
XR        1344378.0     12
AR        1285204.0     10
X40N      1162349.0     10
OX40N      864110.0     10
XY25       476905.0      5
SR         310801.0      2

In [30]:
# money to be made conviction-wise
df_portfolio_features.groupby('Conviction')['FTT Amt'].agg(['sum', 'count']).sort_values(by='sum', ascending=False)

                  sum  count
Conviction
H-SC        3780282.0     24
X-MC        1712077.0     15
X-LC        1609562.0     13
M-SC        1514859.0     14
X-SC        1477915.0     10
H-MC         371825.0      3
L-SC         210183.0      2
M-LC         151541.0      1
M-MC          99732.0      2
H-LC          66306.0      1
L-MC          56192.0      1

In [31]:
# money to be made criteria and conviction-wise
df_portfolio_features.groupby(['Conviction', 'Criteria'])['FTT Amt'].agg(['sum', 'count']).sort_values(by='sum', ascending=False)

                           sum  count
Conviction Criteria
H-SC       XY24      1288037.0      6
           AR         969160.0      5
X-LC       X40        876830.0      7
M-SC       XY24       863388.0      6
H-SC       XR         843473.0      7
X-SC       XY24       840647.0      4
X-MC       X40        670834.0      7
           X40N       522905.0      4
X-SC       X40N       424060.0      4
M-SC       OX40N      388565.0      5
H-SC       OX40N      368811.0      4
X-LC       XY24       357102.0      2
H-SC       SR         310801.0      2
X-MC       XY25       260284.0      2
           XY24       258054.0      2
H-MC       XY24       238627.0      1
X-LC       X40N       215384.0      2
X-SC       X40        213208.0      2
M-SC       XR         189723.0      2
X-LC       XY25       160246.0      2
M-LC       XR         151541.0      1
H-MC       AR         133198.0      2
L-SC       OX40N      106734.0      1
           XR         103449.0      1
M-SC       AR          73183.0      1
H-LC       AR          66306.0      1
M-MC       XY25        56375.0      1
L-MC       XR          56192.0      1
M-MC       AR          43357.0      1

In [32]:
# notebook execution time

end_time = time.time()
execution_time = round(end_time - start_time, 0)
print(f"Notebook execution time: {execution_time} seconds")

Notebook execution time: 24.0 seconds