<a href="https://colab.research.google.com/github/ankit-rathi/Quantvesting_v2/blob/main/myStocks_Portfolio_Analysis.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
'''
!pip install pandas==2.2.2 -qq
!pip install pyxirr -qq
!pip install ta -qq
!pip install yfinance==0.2.59 -qq
'''

'\n!pip install pandas==2.2.2 -qq\n!pip install pyxirr -qq\n!pip install ta -qq\n!pip install yfinance==0.2.59 -qq\n'

In [2]:
# import libraries

import numpy as np
import pandas as pd
import datetime
import warnings
warnings.filterwarnings('ignore')
import yfinance as yfin
import ta
import matplotlib.pyplot as plt
import requests

In [3]:
# notebook start time
import time
import datetime
import pytz

start_time = time.time()

# function to print date timestamp
def print_date_time():
  tz_NY = pytz.timezone('Asia/Kolkata')
  datetime_NY = datetime.datetime.now(tz_NY)
  print("Run date time (IST):", datetime_NY.strftime("%Y-%m-%d %H:%M:%S"))

In [4]:
# function to get booked and reserved amount
def get_amt():
  # fetch the JSON data from the URL
  url = "https://raw.githubusercontent.com/ankit-rathi/Tradevesting_v1/main/data/myPortfolioAmts.json"
  response = requests.get(url)
  pf_amts = response.json()  # parse the JSON data

  # extract values from the JSON
  py_booked_amt_dm = pf_amts["py_booked_amt_dm"]
  py_booked_amt_sv = pf_amts["py_booked_amt_sv"]
  cy_booked_amt_dm = pf_amts["cy_booked_amt_dm"]
  cy_booked_amt_sv = pf_amts["cy_booked_amt_sv"]
  reserve_amt_dm = pf_amts["reserve_amt_dm"]
  reserve_amt_sv = pf_amts["reserve_amt_sv"]

  # perform calculations
  py_booked_amt = py_booked_amt_dm + py_booked_amt_sv
  cy_booked_amt = cy_booked_amt_dm + cy_booked_amt_sv
  reserve_amt = reserve_amt_dm + reserve_amt_sv
  total_booked_amt = py_booked_amt + cy_booked_amt

  return total_booked_amt, reserve_amt, cy_booked_amt, py_booked_amt

gen_output = 0

In [5]:
# function to format the amount
def format_amt(number):
    abs_number = abs(number)

    if abs_number >= 1_00_00_000:  # Crores
        formatted_amt = f"{number / 1_00_00_000:.2f} C"
    elif abs_number >= 1_00_000:  # Lakhs
        formatted_amt = f"{number / 1_00_000:.2f} L"
    elif abs_number >= 1_000:  # Thousands
        formatted_amt = f"{number / 1_000:.2f} K"
    else:
        formatted_amt = f"{number:.2f}"

    return formatted_amt

# function to set start and end date
def get_start_end_date():
  start_date = (datetime.date.today() + datetime.timedelta(days=-365)).strftime('%Y-%m-%d')
  end_date = (datetime.date.today() + datetime.timedelta(days=1)).strftime('%Y-%m-%d')
  return start_date, end_date

# function to fetch my portfolio csv
def get_mypfs_df():
  mypfs_df = pd.read_csv('https://raw.githubusercontent.com/ankit-rathi/Tradevesting_v1/main/data/myPortfolioStocks.csv')
  return mypfs_df

# function to fetch my prospects csv
def get_mypps_df():
  mypps_df = pd.read_csv('https://raw.githubusercontent.com/ankit-rathi/Tradevesting_v1/main/data/myProspectsScrips.csv')
  return mypps_df

# function to fetch screener data
def get_myscreen_df():
  myscreen_df = pd.read_csv('https://raw.githubusercontent.com/ankit-rathi/Tradevesting_v1/main/data/myScreenerDB.csv')
  return myscreen_df

# function to fetch momentum data
def get_myinvmt_df():
  myinvmt_df = pd.read_csv('https://raw.githubusercontent.com/ankit-rathi/Tradevesting_v1/main/data/myInvestments.csv')
  return myinvmt_df

# function to get the stock ids
def get_stock_ids(df_pf):
  stock_n100 = df_pf['Symbol'].unique()

  exclude = ['CADILAHC','MMTC', 'MASFIN']

  stock_ids = df_pf[~df_pf['Symbol'].isin(exclude) ]['Symbol'].unique()

  #mypf = mypf[mypf.Forecast.notnull()]
  #stock_ids = mypf['Symbol'].unique()

  #stock_ids.sort()
  return stock_ids

# get features from screener data
def get_screener_features():
  myscreen_df = get_myscreen_df()
  cols = ['Symbol', 'EPS', 'MedPE', 'ROCE%', 'ROE%', 'CapType']
  return myscreen_df[cols]

# get relative strength
def get_relative_strength(stock_list):

    # Dictionary to store stock tickers and their corresponding percentage price change
    stock_changes = {}

    # Loop through each stock and fetch its price data
    for stock in stock_list:
        try:
            # Download the stock data for the given date range
            stock_data = yfin.Ticker(stock + '.NS').history(period='1mo', interval='1d')[map(str.title, ['open', 'close', 'low', 'high', 'volume'])]

            # Calculate the percentage change for the stock
            if len(stock_data) > 0:
                start_price = stock_data['Close'].iloc[0]
                end_price = stock_data['Close'].iloc[-1]
                percent_change = round(((end_price - start_price) / start_price) * 100, 2)
                stock_changes[stock] = percent_change
            else:
                stock_changes[stock] = np.nan  # If no data is available, set to NaN

        except Exception as e:
            print(f"Error fetching data for {stock}: {e}")
            stock_changes[stock] = np.nan

    # Create a DataFrame with stock tickers and their percentage changes
    df = pd.DataFrame(list(stock_changes.items()), columns=['Symbol', 'Percent_Change'])

    # Drop any stocks with missing data (NaN values)
    df = df.dropna()

    # Calculate the percentile rank based on percentage change
    df['RSP'] = round(df['Percent_Change'].rank(pct=True) * 100, 2)
    cols = ['Symbol', 'RSP']
    df = df[cols]
    # Sort by percentile rank (optional)
    df = df.sort_values(by='RSP', ascending=False).reset_index(drop=True)

    return df

In [6]:
# function to get stock technicals
def stock_prec_dev(stock_symbol):
    #stock_symbol = 'ULTRACEMCO.NS'
    short_window = 20
    mid_window = 50
    long_window = 200
    moving_avg = 'SMA'

    start = datetime.datetime(*map(int, start_date.split('-')))
    end = datetime.datetime(*map(int, end_date.split('-')))

    stock_df = yfin.Ticker(stock_symbol + '.NS').history(period='max', interval='1d')[map(str.title, ['open', 'close', 'low', 'high', 'volume'])]

    stock_df['Max'] = round(max(stock_df['Close']),2)
    stock_df = stock_df[(stock_df.index <= end_date) & (stock_df.index >= start_date)]
    stock_df['200_SMA'] = round(stock_df['Close'].rolling(window = 200, min_periods = 1).mean(),0)
    stock_df['Dev%_200'] = round((stock_df['Close'] - stock_df['200_SMA'])*100/stock_df['200_SMA'],2)
    stock_df.dropna(axis = 0, inplace = True) # remove any null rows

    stock_df['20_SMA'] = stock_df['Close'].rolling(window=20).mean()
    stock_df['50_SMA'] = stock_df['Close'].rolling(window=50).mean()
    stock_df['Symbol'] = stock_symbol

    stock_df['Close'] = round(stock_df['Close'],2)
    stock_df['Min'] = round(min(stock_df['Close']),2)
    stock_df['RSI_14'] = ta.momentum.RSIIndicator(close=stock_df['Close'], window=14).rsi()
    stock_df['RSI_14'] = round(stock_df['RSI_14'],0)
    stock_df['Prev_Close'] = stock_df['Close'].shift(1)
    stock_df.drop(['Open', 'Low', 'High', 'Volume'], axis=1, inplace=True)
    stock_df = stock_df.tail(1)

    max_SMA = max(stock_df['20_SMA'].item(), stock_df['50_SMA'].item(), stock_df['200_SMA'].item())
    min_SMA = min(stock_df['20_SMA'].item(), stock_df['50_SMA'].item(), stock_df['200_SMA'].item())
    ABS_Spread = max_SMA - min_SMA
    stock_df['Spread%'] = round((ABS_Spread / stock_df['200_SMA'].item()) * 100,2)

    return stock_df

# function to compute stock attributes
def get_common_features(stock_ids, df_mypf):

  df_prec_dev = pd.DataFrame()
  df_tmp = get_screener_features()
  df_rs = get_relative_strength(stock_ids)

  for stock_id in stock_ids:
      tmp = stock_prec_dev(stock_id)
      tmp = tmp.reset_index()
      df_prec_dev = pd.concat([df_prec_dev, tmp], ignore_index = True)
  df_prec_dev = pd.merge(df_prec_dev, df_mypf, on= 'Symbol')
  df_prec_dev = pd.merge(df_prec_dev, df_tmp, on= 'Symbol', how='left')
  df_prec_dev = pd.merge(df_prec_dev, df_rs, on= 'Symbol', how='left')
  #print(df_prec_dev.columns)
  df_prec_dev['Curr_PE'] = round(df_prec_dev['Close']/df_prec_dev['EPS'],1)
  df_prec_dev['Dev%_PE'] = round((df_prec_dev['Curr_PE'] - df_prec_dev['MedPE'])*100/df_prec_dev['MedPE'],2)
  df_prec_dev['Conviction'] = df_prec_dev['Conviction'] + '-' + df_prec_dev['CapType']
  return df_prec_dev

# function to arrange stock features
def arrange_features(df_stocks, common_cols, diff_cols):
  df_stocks_common = df_stocks[common_cols].drop_duplicates()
  df_stocks_diff = df_stocks[diff_cols]
  df_stocks_diff['Investment'] = df_stocks_diff['AvgCost'] * df_stocks_diff['Shares']
  df_stocks_diff = df_stocks_diff.groupby(['Symbol'])[['Shares', 'Investment']].aggregate(['sum']).reset_index()
  df_stocks_diff.columns = ['Symbol', 'Shares', 'Investment']
  df_stocks_diff['AvgCost'] = round(df_stocks_diff['Investment']/df_stocks_diff['Shares'],2)
  df_stocks = pd.merge(df_stocks_diff, df_stocks_common, on='Symbol')
  return df_stocks

# plot fact distribution across dimension
def plot_pie_chart(df, dimension, fact):
  # grouping the data by category and calculating the sum of fact for each type
  grouped_data = df.groupby(dimension)[fact].sum()

  # sorting the grouped data in descending order
  grouped_data = grouped_data.sort_values(ascending=False)

  # creating a pie chart
  grouped_data.plot.pie(autopct='%1.1f%%', startangle=90, figsize=(6, 6))

  # adding a title and displaying the plot
  plt.title(f'{dimension} {fact} Distribution')
  plt.ylabel('')  # To hide the y-label
  plt.show()

In [7]:
# function to get portfolio features

def get_portfolio_features(df_common_features):

  print_date_time()
  print('-------------------')

  #df_common_features["Target"] = df_common_features["Target"].fillna(df_common_features["Max"])
  df_common_features['NTT'] = np.where(df_common_features['Strategy']== 'NTT', df_common_features["Target"], df_common_features['Max'])
  df_common_features['LTT'] = np.where(df_common_features['Strategy']== 'BTT', df_common_features["Target"], df_common_features['Max'])
  df_common_features['BOL'] = df_common_features['Min']

  tmp_df = df_common_features[df_common_features['Symbol'].isin(mypf_df[mypf_df['InPortfolio'] != 'NA'].Symbol.values)]
  print('qualified stocks: '+str(len(tmp_df['Symbol'].unique())))
  tmp_df1 = tmp_df[tmp_df['LatestQtr'] == 1]
  print('with latest results: '+str(len(tmp_df1['Symbol'].unique())))
  tmp_df1 = tmp_df1[tmp_df1['StarStock'] == 1]
  print('still star stocks: '+str(len(tmp_df1['Symbol'].unique())))
  tmp_df['Investment'] = tmp_df['AvgCost'] * tmp_df['Shares']
  tmp_df['Current'] = round(tmp_df['Close'] * tmp_df['Shares'],0)
  tmp_df['Previous'] = tmp_df['Prev_Close'] * tmp_df['Shares']
  tmp_df['EstimatedST'] = tmp_df['NTT'] * tmp_df['Shares']
  tmp_df['EstimatedLT'] = tmp_df['LTT'] * tmp_df['Shares']
  tmp_df['Current P/L'] = round((tmp_df['Current'] - tmp_df['Investment']),0)
  tmp_df['Today P/L%'] = round((tmp_df['Current'] - tmp_df['Previous'])*100/tmp_df['Previous'],2)
  tmp_df['Current P/L%'] = round((tmp_df['Current'] - tmp_df['Investment'])*100/tmp_df['Investment'],2)
  tmp_df['EstimatedST P/L%'] = round((tmp_df['EstimatedST'] - tmp_df['Investment'])*100/tmp_df['Investment'],2)
  tmp_df['EstimatedLT P/L%'] = round((tmp_df['EstimatedLT'] - tmp_df['Investment'])*100/tmp_df['Investment'],2)
  tmp_df['NTT%'] = round((tmp_df['NTT'] - tmp_df['Close'])*100/tmp_df['Close'],2)
  tmp_df['LTT%'] = round((tmp_df['LTT'] - tmp_df['Close'])*100/tmp_df['Close'],2)
  tmp_df['Gained%'] = round((tmp_df['Close'] - tmp_df['BOL'])*100/tmp_df['BOL'],2)
  investment = round(sum(tmp_df['AvgCost']*tmp_df['Shares']),0)
  current = round(sum(tmp_df['Close']*tmp_df['Shares']),0)
  tmp_df['InitAlloc%'] = round(tmp_df['Investment']*100/investment,2)
  tmp_df['CurrAlloc%'] = round(tmp_df['Current']*100/current,2)
  tmp_df['FTT'] = tmp_df['LTT']
  tmp_df.loc[tmp_df['Strategy'] == 'NTT', 'FTT'] = tmp_df['NTT']
  tmp_df['FTT%'] = tmp_df['LTT%']
  tmp_df.loc[tmp_df['Strategy'] == 'NTT', 'FTT%'] = tmp_df['NTT%']
  tmp_df['FTT Amt'] = round(tmp_df['FTT%'] * tmp_df['Current']/100,0)
  tmp_df['OTT%'] = round((tmp_df['FTT'] - tmp_df['AvgCost'])*100/tmp_df['AvgCost'],2)
  tmp_df['RRR Ind'] = round(tmp_df['Current P/L']/tmp_df['FTT Amt'],2)
  tmp_df['Risk Ind'] = round(tmp_df['Current P/L%']*tmp_df['CurrAlloc%'],0)

  return tmp_df

# function to print portfolio features
def print_portfolio_stats(df_portfolio_features, myinvmt_df):
  from pyxirr import xirr

  total_booked_amt, reserve_amt, cy_booked_amt, py_booked_amt = get_amt()

  dates = myinvmt_df['Date'].values
  dates = np.append(dates, datetime.date.today().strftime('%d-%b-%y'))
  investment = myinvmt_df['Investment'].values
  dates= pd.to_datetime(dates)

  current = round(sum(df_portfolio_features['Close']*df_portfolio_features['Shares']),0) + reserve_amt
  investment_xirr = np.append(investment, current)
  cagr = round(xirr(pd.DataFrame({"dates": dates, "amounts": investment_xirr}))*100,2)

  investment = -sum(investment)
  invested = round(sum(df_portfolio_features['AvgCost']*df_portfolio_features['Shares']),0) + reserve_amt
  previous = round(sum(df_portfolio_features['Prev_Close']*df_portfolio_features['Shares']),0) + reserve_amt
  cy_invested = investment + py_booked_amt

  today_pnl_amount = current-previous
  today_pnl_percentage = round((current-previous)*100/previous,2)

  curr_pnl_amount = current-invested
  curr_pnl_percentage = round((curr_pnl_amount)*100/(cy_invested),2)

  cy_pnl_amount = cy_booked_amt + curr_pnl_amount
  cy_pnl_percentage = round((cy_pnl_amount)*100/cy_invested,2)

  overall_pnl_amount = total_booked_amt + curr_pnl_amount
  overall_pnl_percentage = round((overall_pnl_amount)*100/investment,2)

  estimate_st = round(sum(df_portfolio_features['FTT']*df_portfolio_features['Shares']),0)  + reserve_amt
  est_st_pnl_amount = estimate_st-current
  est_st_pnl_percentage = round((est_st_pnl_amount)*100/current,2)

  estimate_lt = round(sum(df_portfolio_features['LTT']*df_portfolio_features['Shares']),0)  + reserve_amt
  est_lt_pnl_amount = estimate_lt-current
  est_lt_pnl_percentage = round((est_lt_pnl_amount)*100/current,2)

  total_profit = round(sum(df_portfolio_features[df_portfolio_features['Current P/L%'] > 0]['Current']) - sum(df_portfolio_features[df_portfolio_features['Current P/L%'] > 0]['Investment']),0)
  total_loss = round(sum(df_portfolio_features[df_portfolio_features['Current P/L%'] < 0]['Current']) - sum(df_portfolio_features[df_portfolio_features['Current P/L%'] < 0]['Investment']),0)

  cy_booked_percentage = round((cy_booked_amt)*100/current,2)
  py_booked_percentage = round((py_booked_amt)*100/investment,2)
  total_booked_percentage = round((total_booked_amt)*100/investment,2)

  print('-------------------')
  print('Initial Investment: ', format_amt(investment))
  print('CY Investment: ', format_amt(cy_invested))
  print('Reserve: ', format_amt(reserve_amt))
  print('Current: ',  format_amt(current))
  print('-------------------')
  print('Today PnL: '+ '{} ({}%)'.format(format_amt(today_pnl_amount), today_pnl_percentage))
  print('Current PnL: '+ '{} ({}%)'.format(format_amt(curr_pnl_amount), curr_pnl_percentage))
  print('CY Booked + Current PnL: '+ '{} ({}%)'.format(format_amt(cy_pnl_amount), cy_pnl_percentage))
  print('-------------------')
  print('Total profit: ', format_amt(total_profit))
  print('Total loss: ', format_amt(total_loss))
  print('-------------------')
  print('Total Booked + Current PnL: '+ '{} ({}%)'.format(format_amt(overall_pnl_amount), overall_pnl_percentage))
  print('Total Booked PnL: '+ '{} ({}%)'.format(format_amt(total_booked_amt), total_booked_percentage))
  print('Curr Year Booked PnL: '+ '{} ({}%)'.format(format_amt(cy_booked_amt), cy_booked_percentage))
  print('Prev Year Booked PnL: '+ '{} ({}%)'.format(format_amt(py_booked_amt), py_booked_percentage))
  print('===================')
  print('Est FTT: ',  format_amt(estimate_st))
  print('Est FTT PnL: '+ '{} ({}%)'.format(format_amt(est_st_pnl_amount), est_st_pnl_percentage))

  print('===================')
  print('Deployed: ', format_amt(investment))

  print('Current: ', format_amt(current))

  print('CAGR/XIRR %: '+'{}%'.format(cagr))

In [8]:
# get start and end date
start_date, end_date = get_start_end_date()

# get portfolio and prospects data
mypfs_df = get_mypfs_df()
mypps_df = get_mypps_df()
myinvmt_df = get_myinvmt_df()

# merge above datasets
mypf_df = pd.merge(mypfs_df, mypps_df, on="Symbol")

# seggregate dm and sv portfolio
dm_pf = mypf_df[mypf_df['InPortfolio'] == 'DM']
sv_pf = mypf_df[mypf_df['InPortfolio'] == 'SV']

# build portfolio stock dataframe
dm_stocks = get_stock_ids(dm_pf)
sv_stocks = get_stock_ids(sv_pf)
df_stocks = pd.concat([dm_pf,sv_pf], ignore_index = True)

# arrange common and diff stock features
common_cols = ['Symbol', 'Target', 'Criteria', 'Strategy', 'CumlRnk', 'LatestQtr', 'StarStock', 'Conviction', 'Category', 'InFolio', 'XIRR', 'MBQ']
diff_cols = ['Symbol', 'AvgCost', 'Shares']
df_stocks = arrange_features(df_stocks, common_cols, diff_cols)

# get common features
stock_ids = df_stocks['Symbol'].values
df_common_features = get_common_features(stock_ids, df_stocks)

df_common_features.reset_index(drop=True, inplace=True)
df_common_features.drop(['Date'], axis=1, inplace=True)
# get and print portfolio features
df_portfolio_features = get_portfolio_features(df_common_features)

print_portfolio_stats(df_portfolio_features, myinvmt_df)

df = df_portfolio_features
#plot_pie_chart(df, 'CapType', 'Current')
list_ox40n = list(df[df['MBQ'].str.contains('OX40N', na=False)]['Symbol'].values)

Run date time (IST): 2026-08-13 12:54:03
-------------------
qualified stocks: 88
with latest results: 30
still star stocks: 19
-------------------
Initial Investment:  1.46 C
CY Investment:  1.89 C
Reserve:  2.21 L
Current:  1.61 C
-------------------
Today PnL: -30.28 K (-0.19%)
Current PnL: -31.87 L (-16.87%)
CY Booked + Current PnL: -27.22 L (-14.41%)
-------------------
Total profit:  3.77 L
Total loss:  -35.63 L
-------------------
Total Booked + Current PnL: 15.65 L (10.72%)
Total Booked PnL: 47.52 L (32.53%)
Curr Year Booked PnL: 4.65 L (2.89%)
Prev Year Booked PnL: 42.87 L (29.35%)
===================
Est FTT:  2.68 C
Est FTT PnL: 1.07 C (66.66%)
===================
Deployed:  1.46 C
Current:  1.61 C
CAGR/XIRR %: 4.36%

In [9]:
# top 5 near their targets
cols = ['Symbol', 'Today P/L%', 'Current P/L%', 'FTT%', 'OTT%', 'FTT Amt', 'Current P/L', 'Current', 'FTT', 'Dev%_PE', 'RSI_14','Conviction', 'Spread%',  'CumlRnk', 'RRR Ind', 'CurrAlloc%', 'Gained%', 'Criteria', 'Strategy', 'Category']
df_tmp = df_portfolio_features[~df_portfolio_features['Symbol'].isin(['ENRIN','BLUSPRING','DIGITIDE'])]
df_tmp = df_tmp.sort_values(by = 'FTT Amt', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
79,UNITDSPR,-1.28,12.31,7.53,20.77,19802.0,28827.0,262971.0,1644.00,-0.46,67.0,X-MC,8.51,64.0,1.46,1.66,26.41,X40N,NTT,BREWERIES
78,TTKPRESTIG,1.36,-22.27,28.76,0.09,22530.0,-22439.0,78338.0,770.00,81.86,41.0,M-SC,12.21,250.0,-1.00,0.49,41.00,OX40N,NTT,DURABLES
68,SIS,-0.81,-0.33,21.66,21.26,23971.0,-362.0,110670.0,528.00,2642.49,53.0,H-SC,22.57,168.0,-0.02,0.70,64.55,OX40N,NTT,MISC
52,M&M,0.61,8.14,9.88,18.82,25714.0,19581.0,260262.0,3762.88,-5.74,60.0,X-LC,4.55,25.0,0.76,1.64,18.06,X40N,ATH,AUTO
87,ZYDUSLIFE,-3.24,22.95,10.22,35.51,26333.0,48090.0,257664.0,1285.01,7.21,58.0,H-MC,16.21,120.0,1.83,1.63,35.60,AR,ATH,PHARMA

In [10]:
# top 5 today
df_tmp = df_portfolio_features.sort_values(by = 'Today P/L%', ascending=False)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
82,VALIANTORG,10.23,-29.02,145.35,74.15,168791.0,-47478.0,116127.0,838.00,-308.98,79.0,H-SC,4.24,145.0,-0.28,0.73,72.81,XR,NTT,CHEMICALS
21,DEN,3.37,-47.15,168.82,42.07,75361.0,-39824.0,44640.0,75.00,58.03,51.0,M-SC,5.75,235.0,-0.53,0.28,21.41,AR,NTT,ENTERTAINMENT
28,GODREJCP,2.76,-15.40,57.09,32.90,120523.0,-38427.0,211110.0,1460.97,-12.53,30.0,X-LC,5.08,32.0,-0.32,1.33,2.76,X40N,ATH,FMCG
65,SFL,2.61,-31.42,84.65,26.63,152223.0,-82392.0,179826.0,1287.00,36.12,40.0,M-SC,21.73,242.0,-0.54,1.13,50.08,XY24,NTT,MISC
5,ATULAUTO,2.40,-12.74,66.81,45.57,114929.0,-25109.0,172023.0,844.00,3732.43,49.0,M-SC,10.00,248.0,-0.22,1.09,32.38,XY24,NTT,AUTO

In [11]:
# bottom 5 today
df_tmp = df_portfolio_features.sort_values(by = 'Today P/L%', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
72,TANLA,-4.39,-33.37,226.04,117.25,407817.0,-90343.0,180418.0,1922.32,-32.65,51.0,H-SC,15.29,147.0,-0.22,1.14,57.96,AR,ATH,IT
24,EASEMYTRIP,-4.17,-65.78,325.81,45.70,197115.0,-116315.0,60500.0,26.40,-37.27,28.0,M-SC,6.68,204.0,-0.59,0.38,5.98,XY24,NTT,TRAVEL
18,COFFEEDAY,-3.38,-50.24,171.83,35.27,97094.0,-57043.0,56506.0,80.00,-61.77,37.0,L-SC,4.72,266.0,-0.59,0.36,39.35,XR,NTT,HOTELS
87,ZYDUSLIFE,-3.24,22.95,10.22,35.51,26333.0,48090.0,257664.0,1285.01,7.21,58.0,H-MC,16.21,120.0,1.83,1.63,35.60,AR,ATH,PHARMA
25,FINCABLES,-2.58,57.95,31.63,107.91,73761.0,85554.0,233198.0,1641.55,42.06,72.0,M-SC,17.95,220.0,1.16,1.47,75.44,OX40N,ATH,CABLES

In [12]:
# top 5 to exit based on CumlRnk
df_tmp = df_portfolio_features[~df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])]
df_tmp = df_tmp[(df_tmp['Current P/L%'] > -1) & (df_tmp['Current P/L%'] < 1)].sort_values(by = 'CumlRnk', ascending=False)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
80,UTIAMC,-0.88,0.17,50.90,51.15,113357.0,375.0,222705.0,1371.68,-19.39,48.0,M-SC,7.63,229.0,0.00,1.41,4.32,XY24,ATH,FINANCE
68,SIS,-0.81,-0.33,21.66,21.26,23971.0,-362.0,110670.0,528.00,2642.49,53.0,H-SC,22.57,168.0,-0.02,0.70,64.55,OX40N,NTT,MISC

In [13]:
# OX40N stocks to exit
df_tmp = df_portfolio_features[(df_portfolio_features['Symbol'].isin(list_ox40n))].sort_values(by = 'Current P/L%', ascending=False)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
25,FINCABLES,-2.58,57.95,31.63,107.91,73761.0,85554.0,233198.0,1641.55,42.06,72.0,M-SC,17.95,220.0,1.16,1.47,75.44,OX40N,ATH,CABLES
68,SIS,-0.81,-0.33,21.66,21.26,23971.0,-362.0,110670.0,528.00,2642.49,53.0,H-SC,22.57,168.0,-0.02,0.70,64.55,OX40N,NTT,MISC
43,INDIGOPNTS,1.40,-19.17,23.75,0.02,33508.0,-33472.0,141087.0,1408.00,115.40,62.0,M-SC,6.12,222.0,-1.00,0.89,60.07,OX40N,NTT,PAINTS
78,TTKPRESTIG,1.36,-22.27,28.76,0.09,22530.0,-22439.0,78338.0,770.00,81.86,41.0,M-SC,12.21,250.0,-1.00,0.49,41.00,OX40N,NTT,DURABLES
16,CERA,-1.04,-22.57,60.00,23.89,81724.0,-39697.0,136206.0,9475.00,-25.30,39.0,H-SC,12.36,153.0,-0.49,0.86,32.40,OX40N,NTT,CERAMICS

In [14]:
# top 5 to book for rotation
df_tmp = df_portfolio_features[(df_portfolio_features['Current P/L%'] > 20) ].sort_values(by = 'CumlRnk', ascending=False)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
25,FINCABLES,-2.58,57.95,31.63,107.91,73761.0,85554.0,233198.0,1641.55,42.06,72.0,M-SC,17.95,220.0,1.16,1.47,75.44,OX40N,ATH,CABLES
87,ZYDUSLIFE,-3.24,22.95,10.22,35.51,26333.0,48090.0,257664.0,1285.01,7.21,58.0,H-MC,16.21,120.0,1.83,1.63,35.60,AR,ATH,PHARMA
57,QUESS,-0.16,36.84,27.08,73.90,39574.0,39346.0,146139.0,424.00,-26.17,68.0,X-SC,41.64,80.0,0.99,0.92,101.14,XY24,NTT,MISC

In [15]:
# top 5 to monitor for exit
df_tmp = df_portfolio_features[~df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])]
df_tmp = df_tmp[(df_tmp['Current P/L%'] > 0) ].sort_values(by = 'Dev%_PE', ascending=False)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
69,STARHEALTH,-0.93,12.09,31.38,47.26,98882.0,33989.0,315112.0,761.00,76.87,48.0,H-SC,16.84,173.0,0.34,1.99,36.25,XY24,NTT,INSURANCE
25,FINCABLES,-2.58,57.95,31.63,107.91,73761.0,85554.0,233198.0,1641.55,42.06,72.0,M-SC,17.95,220.0,1.16,1.47,75.44,OX40N,ATH,CABLES
87,ZYDUSLIFE,-3.24,22.95,10.22,35.51,26333.0,48090.0,257664.0,1285.01,7.21,58.0,H-MC,16.21,120.0,1.83,1.63,35.60,AR,ATH,PHARMA
80,UTIAMC,-0.88,0.17,50.90,51.15,113357.0,375.0,222705.0,1371.68,-19.39,48.0,M-SC,7.63,229.0,0.00,1.41,4.32,XY24,ATH,FINANCE

In [16]:
# top 5 to book for rotation from weak conviction
df_tmp = df_portfolio_features[~df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])]
df_tmp = df_tmp[~df_tmp['Criteria'].isin(['XY25','XY24','X40', 'X40N'])].sort_values(by = 'RRR Ind', ascending=False)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
87,ZYDUSLIFE,-3.24,22.95,10.22,35.51,26333.0,48090.0,257664.0,1285.01,7.21,58.0,H-MC,16.21,120.0,1.83,1.63,35.60,AR,ATH,PHARMA
25,FINCABLES,-2.58,57.95,31.63,107.91,73761.0,85554.0,233198.0,1641.55,42.06,72.0,M-SC,17.95,220.0,1.16,1.47,75.44,OX40N,ATH,CABLES
68,SIS,-0.81,-0.33,21.66,21.26,23971.0,-362.0,110670.0,528.00,2642.49,53.0,H-SC,22.57,168.0,-0.02,0.70,64.55,OX40N,NTT,MISC
3,ALKYLAMINE,-1.40,-18.22,135.45,92.54,111833.0,-18399.0,82564.0,4520.85,-12.41,58.0,H-SC,13.90,142.0,-0.16,0.52,56.78,SR,ATH,CHEMICALS
42,INDIAMART,0.57,-22.89,160.57,100.92,152707.0,-28233.0,95103.0,4675.60,-65.23,43.0,H-SC,12.60,140.0,-0.18,0.60,2.95,AR,ATH,MISC

In [17]:
# top 5 to accumulate based on lowest RSI_14
df_tmp = df_portfolio_features[df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])].sort_values(by = 'RSI_14', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
28,GODREJCP,2.76,-15.40,57.09,32.90,120523.0,-38427.0,211110.0,1460.97,-12.53,30.0,X-LC,5.08,32.0,-0.32,1.33,2.76,X40N,ATH,FMCG
34,HDFCBANK,-0.26,-11.20,47.57,31.05,123826.0,-32818.0,260302.0,1073.00,-25.96,33.0,X-LC,11.80,26.0,-0.27,1.64,1.04,X40,BTT,BANKS
55,PAGEIND,-1.36,-1.47,35.59,33.59,94109.0,-3954.0,264425.0,51217.29,-29.41,33.0,X-MC,8.98,55.0,-0.04,1.67,25.57,X40,ATH,APPARELS
56,PGHH,0.36,-36.41,107.61,32.01,146100.0,-77752.0,135768.0,17616.87,-57.06,36.0,X-MC,19.16,57.0,-0.53,0.86,0.36,X40,ATH,FMCG
83,VBL,0.10,-11.35,53.03,35.66,165402.0,-39942.0,311902.0,669.42,-22.02,37.0,X-LC,7.45,13.0,-0.24,1.97,14.83,X40N,ATH,FMCG

In [18]:
# top 5 to accumulate based on Spread and CumlRnk
df_tmp = df_portfolio_features[df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])]
df_tmp = df_tmp[(df_tmp['CumlRnk'] < 100)].sort_values(by = 'Spread%', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
19,COLPAL,-1.15,-24.74,85.84,39.86,170135.0,-65165.0,198200.0,3683.41,-8.99,39.0,X-MC,1.64,62.0,-0.38,1.25,12.11,XY25,ATH,FMCG
23,DMART,0.01,-1.15,32.94,31.42,101524.0,-3580.0,308210.0,5391.45,-17.82,54.0,X-LC,2.78,14.0,-0.04,1.95,11.22,X40N,ATH,FMCG
50,KOTAKBANK,0.42,3.07,15.38,18.92,37997.0,7352.0,247054.0,452.46,-10.27,52.0,X-LC,3.00,12.0,0.19,1.56,11.16,X40,ATH,BANKS
8,BAJAJHLDNG,-0.44,3.31,24.13,28.24,63818.0,8472.0,264477.0,14274.15,-4.76,65.0,X-LC,3.17,28.0,0.13,1.67,33.11,X40,ATH,FINANCE
26,GILLETTE,0.38,-9.99,44.12,29.72,100832.0,-25356.0,228540.0,10978.86,-30.84,43.0,X-SC,3.19,83.0,-0.25,1.44,5.03,X40,ATH,FMCG

In [19]:
# top 5 to accumulate based on lowest Gained%
df_tmp = df_portfolio_features[df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])].sort_values(by = 'Gained%', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
56,PGHH,0.36,-36.41,107.61,32.01,146100.0,-77752.0,135768.0,17616.87,-57.06,36.0,X-MC,19.16,57.0,-0.53,0.86,0.36,X40,ATH,FMCG
35,HDFCLIFE,0.33,-7.61,50.61,39.15,117244.0,-19075.0,231662.0,811.41,-31.24,40.0,X-LC,16.32,31.0,-0.16,1.46,0.52,X40,ATH,INSURANCE
47,ITC,0.49,-23.44,62.88,24.70,191243.0,-93138.0,304140.0,452.00,-59.97,40.0,X-LC,10.98,1.0,-0.49,1.92,0.71,X40,NTT,FMCG
34,HDFCBANK,-0.26,-11.20,47.57,31.05,123826.0,-32818.0,260302.0,1073.00,-25.96,33.0,X-LC,11.80,26.0,-0.27,1.64,1.04,X40,BTT,BANKS
20,DABUR,-0.26,-19.80,79.18,43.70,157526.0,-49121.0,198947.0,735.00,-27.23,40.0,X-MC,9.43,70.0,-0.31,1.26,1.24,XY24,BTT,FMCG

In [20]:
# top 5 to accumulate based on lowest CurrAlloc%
df_tmp = df_portfolio_features[df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])].sort_values(by = 'CurrAlloc%', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
10,BATAINDIA,1.40,-53.22,189.04,35.20,113778.0,-68483.0,60187.0,2096.00,-21.16,60.0,X-SC,13.17,91.0,-0.60,0.38,20.92,X40,NTT,FOOTWEAR
61,RELAXO,0.31,-45.83,181.14,52.31,142448.0,-66520.0,78640.0,1176.00,-42.31,57.0,X-SC,13.53,92.0,-0.47,0.50,75.83,X40N,NTT,FOOTWEAR
56,PGHH,0.36,-36.41,107.61,32.01,146100.0,-77752.0,135768.0,17616.87,-57.06,36.0,X-MC,19.16,57.0,-0.53,0.86,0.36,X40,ATH,FMCG
57,QUESS,-0.16,36.84,27.08,73.90,39574.0,39346.0,146139.0,424.00,-26.17,68.0,X-SC,41.64,80.0,0.99,0.92,101.14,XY24,NTT,MISC
2,ACC,-1.07,-40.68,194.70,74.81,309666.0,-109080.0,159048.0,3906.00,-57.90,42.0,X-SC,12.12,85.0,-0.35,1.00,6.25,XY24,BTT,CEMENT

In [21]:
# top 5 to accumulate based on CumlRnk
df_tmp = df_portfolio_features.sort_values(by = 'CumlRnk', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
47,ITC,0.49,-23.44,62.88,24.70,191243.0,-93138.0,304140.0,452.00,-59.97,40.0,X-LC,10.98,1.0,-0.49,1.92,0.71,X40,NTT,FMCG
74,TCS,0.59,-30.61,78.99,24.20,253913.0,-141823.0,321450.0,4230.71,-41.33,54.0,X-LC,15.03,2.0,-0.56,2.03,19.87,X40,ATH,IT
45,INFY,-0.64,-16.81,68.75,40.38,215315.0,-63285.0,313185.0,1972.00,-37.23,59.0,X-LC,16.09,3.0,-0.29,1.98,18.60,X40,NTT,IT
76,TMPV,1.85,-16.88,71.75,42.75,248152.0,-70251.0,345856.0,600.00,-83.62,56.0,X-LC,4.67,4.0,-0.28,2.18,18.92,XY24,NTT,AUTO
33,HCLTECH,0.25,-8.45,35.40,23.97,100303.0,-26144.0,283342.0,1853.42,-6.53,70.0,X-LC,12.93,8.0,-0.26,1.79,33.70,X40,ATH,IT

In [22]:
# top 5 for average up
df_tmp = df_portfolio_features[(df_portfolio_features['Dev%_200'] > 5)].sort_values(by = 'CurrAlloc%', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
44,INDUSINDBK,0.26,-24.69,76.45,32.89,44453.0,-19060.0,58146.0,1800.00,-373.81,55.0,L-MC,13.54,258.0,-0.43,0.37,43.35,XR,NTT,BANKS
61,RELAXO,0.31,-45.83,181.14,52.31,142448.0,-66520.0,78640.0,1176.00,-42.31,57.0,X-SC,13.53,92.0,-0.47,0.50,75.83,X40N,NTT,FOOTWEAR
3,ALKYLAMINE,-1.40,-18.22,135.45,92.54,111833.0,-18399.0,82564.0,4520.85,-12.41,58.0,H-SC,13.90,142.0,-0.16,0.52,56.78,SR,ATH,CHEMICALS
12,BOSCH-HCIL,-1.28,-25.87,34.88,-0.01,33047.0,-33059.0,94746.0,2282.00,19291.30,79.0,M-SC,4.44,231.0,-1.00,0.60,61.27,OX40N,BTT,AC
68,SIS,-0.81,-0.33,21.66,21.26,23971.0,-362.0,110670.0,528.00,2642.49,53.0,H-SC,22.57,168.0,-0.02,0.70,64.55,OX40N,NTT,MISC

In [23]:
# top 5 RSP
df_tmp = df_portfolio_features.sort_values(by = 'RSP', ascending=False)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
12,BOSCH-HCIL,-1.28,-25.87,34.88,-0.01,33047.0,-33059.0,94746.0,2282.00,19291.30,79.0,M-SC,4.44,231.0,-1.00,0.60,61.27,OX40N,BTT,AC
82,VALIANTORG,10.23,-29.02,145.35,74.15,168791.0,-47478.0,116127.0,838.00,-308.98,79.0,H-SC,4.24,145.0,-0.28,0.73,72.81,XR,NTT,CHEMICALS
25,FINCABLES,-2.58,57.95,31.63,107.91,73761.0,85554.0,233198.0,1641.55,42.06,72.0,M-SC,17.95,220.0,1.16,1.47,75.44,OX40N,ATH,CABLES
67,SIEMENS,-1.17,6.72,17.03,24.90,33822.0,12510.0,198605.0,4648.66,66.91,66.0,H-LC,12.68,51.0,0.37,1.25,40.13,AR,ATH,ELECTRICAL
11,BERGEPAINT,-0.88,2.25,22.56,25.32,59458.0,5805.0,263554.0,680.00,-3.28,65.0,X-MC,3.81,68.0,0.10,1.66,38.20,XY24,NTT,PAINTS

In [24]:
# Top N allocation
df_tmp = df_portfolio_features.sort_values(by = 'CurrAlloc%', ascending=False)
top_n_values = [10, 25, 50]

sum_df = pd.DataFrame({
    'Top_N': top_n_values,
    'Sum_Alloc%': [df_tmp['CurrAlloc%'].head(n).sum() for n in top_n_values]
})

sum_df

   Top_N  Sum_Alloc%
0     10       19.76
1     25       44.81
2     50       76.83

In [25]:
# market-cap-wise allocation
df_tmp = df_portfolio_features[cols]
df_tmp.groupby(df_tmp['Conviction'].str[-2:])['CurrAlloc%'].sum().sort_values(ascending=False)

Conviction
SC    39.41
LC    37.64
MC    22.97
Name: CurrAlloc%, dtype: float64

In [26]:
# criteria-wise allocation
df_portfolio_features.groupby('Criteria')['CurrAlloc%'].sum().sort_values(ascending=False)

Criteria
X40      26.35
XY24     24.96
X40N     18.31
XR        9.12
XY25      7.19
OX40N     7.14
AR        6.10
SR        0.85
Name: CurrAlloc%, dtype: float64

In [27]:
# conviction-wise allocation
df_portfolio_features.groupby('Conviction')['CurrAlloc%'].sum().sort_values(ascending=False)

Conviction
X-LC    35.59
H-SC    19.29
X-MC    18.72
M-SC    11.11
X-SC     8.51
H-MC     2.68
H-LC     1.25
M-MC     1.20
M-LC     0.80
L-SC     0.50
L-MC     0.37
Name: CurrAlloc%, dtype: float64

In [28]:
# sector-wise stats
df_tmp = df_portfolio_features.groupby('Category')[['CurrAlloc%', 'Current', 'Current P/L', 'FTT Amt']].sum().sort_values(by=['Current', 'Current P/L'], ascending=False)
df_tmp['Current P/L%'] = round(df_tmp['Current P/L'] * 100 / df_tmp['Current'], 2)
df_tmp['FTT%'] = round(df_tmp['FTT Amt'] * 100 / df_tmp['Current'], 2)
cols = ['CurrAlloc%', 'Current P/L%', 'FTT%']
df_tmp[cols].sort_values(by=['CurrAlloc%'], ascending=False)

               CurrAlloc%  Current P/L%    FTT%
Category
FMCG                15.31        -23.03   67.26
IT                  11.10        -35.67  103.01
FINANCE             10.67        -14.28   63.51
AUTO                 8.31         -2.67   39.43
MISC                 6.88        -22.77   75.45
BANKS                6.08        -10.92   58.75
PHARMA               5.69          8.08   18.00
INSURANCE            5.58         -5.01   42.14
PAINTS               5.51        -12.95   32.21
ELECTRICAL           4.10         -8.65   46.69
AC                   1.81        -11.33   41.52
REFINERIES           1.69        -11.23   48.60
APPARELS             1.67         -1.50   35.59
FOOTWEAR             1.67        -67.42  134.55
BREWERIES            1.66         10.96    7.53
DURABLES             1.47        -65.06  105.22
CABLES               1.47         36.69   31.63
TRAVEL               1.43        -97.71  196.70
CERAMICS             1.34        -44.29   88.13
CHEMICALS            1.25        -33.16  141.24
ENGINEERING          1.23        -24.23   81.05
CEMENT               1.00        -68.58  194.70
JEWELLERY            0.98       -107.80  180.00
ENTERTAINMENT        0.69        -76.81  182.26
HEALTHCARE           0.68        -67.21  109.19
TEXTILES             0.39        -51.03   94.10
HOTELS               0.36       -100.95  171.83

In [29]:
# money to be made criteria-wise
df_portfolio_features.groupby('Criteria')['FTT Amt'].agg(['sum', 'count']).sort_values(by='sum', ascending=False)

                sum  count
Criteria
XY24      3559736.0     20
X40       2051264.0     18
XR        1354125.0     13
X40N      1177201.0     12
AR        1065743.0      8
OX40N      660321.0     10
XY25       559724.0      5
SR         282081.0      2

In [30]:
# money to be made conviction-wise
df_portfolio_features.groupby('Conviction')['FTT Amt'].agg(['sum', 'count']).sort_values(by='sum', ascending=False)

                  sum  count
Conviction
H-SC        3298451.0     23
X-LC        2418894.0     20
M-SC        1491769.0     15
X-MC        1486978.0     14
X-SC        1228545.0      8
H-MC         274269.0      2
L-SC         212792.0      2
M-LC         164663.0      1
M-MC          55559.0      1
L-MC          44453.0      1
H-LC          33822.0      1

In [31]:
# money to be made criteria and conviction-wise
df_portfolio_features.groupby(['Conviction', 'Criteria'])['FTT Amt'].agg(['sum', 'count']).sort_values(by='sum', ascending=False)

                           sum  count
Conviction Criteria
X-LC       X40       1173796.0      9
H-SC       XY24       995775.0      5
M-SC       XY24       972105.0      7
H-SC       AR         930227.0      5
           XR         796671.0      7
X-SC       XY24       708617.0      3
X-MC       X40        662858.0      7
X-LC       X40N       521006.0      6
           XY24       418319.0      2
X-MC       X40N       350877.0      3
X-SC       X40N       305318.0      3
H-SC       OX40N      293697.0      4
           SR         282081.0      2
X-MC       XY25       256259.0      2
M-SC       OX40N      250926.0      5
H-MC       XY24       247936.0      1
X-LC       XY25       247906.0      2
X-MC       XY24       216984.0      2
X-SC       X40        214610.0      2
M-SC       XR         193377.0      2
M-LC       XR         164663.0      1
L-SC       OX40N      115698.0      1
           XR          97094.0      1
M-SC       AR          75361.0      1
X-LC       XR          57867.0      1
M-MC       XY25        55559.0      1
L-MC       XR          44453.0      1
H-LC       AR          33822.0      1
H-MC       AR          26333.0      1

In [32]:
# notebook execution time

end_time = time.time()
execution_time = round(end_time - start_time, 0)
print(f"Notebook execution time: {execution_time} seconds")

Notebook execution time: 26.0 seconds