<a href="https://colab.research.google.com/github/ankit-rathi/Quantvesting_v2/blob/main/myStocks_Portfolio_Analysis.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
'''
!pip install pandas==2.2.2 -qq
!pip install pyxirr -qq
!pip install ta -qq
!pip install yfinance==0.2.59 -qq
'''

'\n!pip install pandas==2.2.2 -qq\n!pip install pyxirr -qq\n!pip install ta -qq\n!pip install yfinance==0.2.59 -qq\n'

In [2]:
# import libraries

import numpy as np
import pandas as pd
import datetime
import warnings
warnings.filterwarnings('ignore')
import yfinance as yfin
import ta
import matplotlib.pyplot as plt
import requests

In [3]:
# notebook start time
import time
import datetime
import pytz

start_time = time.time()

# function to print date timestamp
def print_date_time():
  tz_NY = pytz.timezone('Asia/Kolkata')
  datetime_NY = datetime.datetime.now(tz_NY)
  print("Run date time (IST):", datetime_NY.strftime("%Y-%m-%d %H:%M:%S"))

In [4]:
# function to get booked and reserved amount
def get_amt():
  # fetch the JSON data from the URL
  url = "https://raw.githubusercontent.com/ankit-rathi/Tradevesting_v1/main/data/myPortfolioAmts.json"
  response = requests.get(url)
  pf_amts = response.json()  # parse the JSON data

  # extract values from the JSON
  py_booked_amt_dm = pf_amts["py_booked_amt_dm"]
  py_booked_amt_sv = pf_amts["py_booked_amt_sv"]
  cy_booked_amt_dm = pf_amts["cy_booked_amt_dm"]
  cy_booked_amt_sv = pf_amts["cy_booked_amt_sv"]
  reserve_amt_dm = pf_amts["reserve_amt_dm"]
  reserve_amt_sv = pf_amts["reserve_amt_sv"]

  # perform calculations
  py_booked_amt = py_booked_amt_dm + py_booked_amt_sv
  cy_booked_amt = cy_booked_amt_dm + cy_booked_amt_sv
  reserve_amt = reserve_amt_dm + reserve_amt_sv
  total_booked_amt = py_booked_amt + cy_booked_amt

  return total_booked_amt, reserve_amt, cy_booked_amt, py_booked_amt

gen_output = 0

In [5]:
# function to format the amount
def format_amt(number):
    abs_number = abs(number)

    if abs_number >= 1_00_00_000:  # Crores
        formatted_amt = f"{number / 1_00_00_000:.2f} C"
    elif abs_number >= 1_00_000:  # Lakhs
        formatted_amt = f"{number / 1_00_000:.2f} L"
    elif abs_number >= 1_000:  # Thousands
        formatted_amt = f"{number / 1_000:.2f} K"
    else:
        formatted_amt = f"{number:.2f}"

    return formatted_amt

# function to set start and end date
def get_start_end_date():
  start_date = (datetime.date.today() + datetime.timedelta(days=-365)).strftime('%Y-%m-%d')
  end_date = (datetime.date.today() + datetime.timedelta(days=1)).strftime('%Y-%m-%d')
  return start_date, end_date

# function to fetch my portfolio csv
def get_mypfs_df():
  mypfs_df = pd.read_csv('https://raw.githubusercontent.com/ankit-rathi/Tradevesting_v1/main/data/myPortfolioStocks.csv')
  return mypfs_df

# function to fetch my prospects csv
def get_mypps_df():
  mypps_df = pd.read_csv('https://raw.githubusercontent.com/ankit-rathi/Tradevesting_v1/main/data/myProspectsScrips.csv')
  return mypps_df

# function to fetch screener data
def get_myscreen_df():
  myscreen_df = pd.read_csv('https://raw.githubusercontent.com/ankit-rathi/Tradevesting_v1/main/data/myScreenerDB.csv')
  return myscreen_df

# function to fetch momentum data
def get_myinvmt_df():
  myinvmt_df = pd.read_csv('https://raw.githubusercontent.com/ankit-rathi/Tradevesting_v1/main/data/myInvestments.csv')
  return myinvmt_df

# function to get the stock ids
def get_stock_ids(df_pf):
  stock_n100 = df_pf['Symbol'].unique()

  exclude = ['CADILAHC','MMTC', 'MASFIN']

  stock_ids = df_pf[~df_pf['Symbol'].isin(exclude) ]['Symbol'].unique()

  #mypf = mypf[mypf.Forecast.notnull()]
  #stock_ids = mypf['Symbol'].unique()

  #stock_ids.sort()
  return stock_ids

# get features from screener data
def get_screener_features():
  myscreen_df = get_myscreen_df()
  cols = ['Symbol', 'EPS', 'MedPE', 'ROCE%', 'ROE%', 'CapType']
  return myscreen_df[cols]

# get relative strength
def get_relative_strength(stock_list):

    # Dictionary to store stock tickers and their corresponding percentage price change
    stock_changes = {}

    # Loop through each stock and fetch its price data
    for stock in stock_list:
        try:
            # Download the stock data for the given date range
            stock_data = yfin.Ticker(stock + '.NS').history(period='1mo', interval='1d')[map(str.title, ['open', 'close', 'low', 'high', 'volume'])]

            # Calculate the percentage change for the stock
            if len(stock_data) > 0:
                start_price = stock_data['Close'].iloc[0]
                end_price = stock_data['Close'].iloc[-1]
                percent_change = round(((end_price - start_price) / start_price) * 100, 2)
                stock_changes[stock] = percent_change
            else:
                stock_changes[stock] = np.nan  # If no data is available, set to NaN

        except Exception as e:
            print(f"Error fetching data for {stock}: {e}")
            stock_changes[stock] = np.nan

    # Create a DataFrame with stock tickers and their percentage changes
    df = pd.DataFrame(list(stock_changes.items()), columns=['Symbol', 'Percent_Change'])

    # Drop any stocks with missing data (NaN values)
    df = df.dropna()

    # Calculate the percentile rank based on percentage change
    df['RSP'] = round(df['Percent_Change'].rank(pct=True) * 100, 2)
    cols = ['Symbol', 'RSP']
    df = df[cols]
    # Sort by percentile rank (optional)
    df = df.sort_values(by='RSP', ascending=False).reset_index(drop=True)

    return df

In [6]:
# function to get stock technicals
def stock_prec_dev(stock_symbol):
    #stock_symbol = 'ULTRACEMCO.NS'
    short_window = 20
    mid_window = 50
    long_window = 200
    moving_avg = 'SMA'

    start = datetime.datetime(*map(int, start_date.split('-')))
    end = datetime.datetime(*map(int, end_date.split('-')))

    stock_df = yfin.Ticker(stock_symbol + '.NS').history(period='max', interval='1d')[map(str.title, ['open', 'close', 'low', 'high', 'volume'])]

    stock_df['Max'] = round(max(stock_df['Close']),2)
    stock_df = stock_df[(stock_df.index <= end_date) & (stock_df.index >= start_date)]
    stock_df['200_SMA'] = round(stock_df['Close'].rolling(window = 200, min_periods = 1).mean(),0)
    stock_df['Dev%_200'] = round((stock_df['Close'] - stock_df['200_SMA'])*100/stock_df['200_SMA'],2)
    stock_df.dropna(axis = 0, inplace = True) # remove any null rows

    stock_df['20_SMA'] = stock_df['Close'].rolling(window=20).mean()
    stock_df['50_SMA'] = stock_df['Close'].rolling(window=50).mean()
    stock_df['Symbol'] = stock_symbol

    stock_df['Close'] = round(stock_df['Close'],2)
    stock_df['Min'] = round(min(stock_df['Close']),2)
    stock_df['RSI_14'] = ta.momentum.RSIIndicator(close=stock_df['Close'], window=14).rsi()
    stock_df['RSI_14'] = round(stock_df['RSI_14'],0)
    stock_df['Prev_Close'] = stock_df['Close'].shift(1)
    stock_df.drop(['Open', 'Low', 'High', 'Volume'], axis=1, inplace=True)
    stock_df = stock_df.tail(1)

    max_SMA = max(stock_df['20_SMA'].item(), stock_df['50_SMA'].item(), stock_df['200_SMA'].item())
    min_SMA = min(stock_df['20_SMA'].item(), stock_df['50_SMA'].item(), stock_df['200_SMA'].item())
    ABS_Spread = max_SMA - min_SMA
    stock_df['Spread%'] = round((ABS_Spread / stock_df['200_SMA'].item()) * 100,2)

    return stock_df

# function to compute stock attributes
def get_common_features(stock_ids, df_mypf):

  df_prec_dev = pd.DataFrame()
  df_tmp = get_screener_features()
  df_rs = get_relative_strength(stock_ids)

  for stock_id in stock_ids:
      tmp = stock_prec_dev(stock_id)
      tmp = tmp.reset_index()
      df_prec_dev = pd.concat([df_prec_dev, tmp], ignore_index = True)
  df_prec_dev = pd.merge(df_prec_dev, df_mypf, on= 'Symbol')
  df_prec_dev = pd.merge(df_prec_dev, df_tmp, on= 'Symbol', how='left')
  df_prec_dev = pd.merge(df_prec_dev, df_rs, on= 'Symbol', how='left')
  #print(df_prec_dev.columns)
  df_prec_dev['Curr_PE'] = round(df_prec_dev['Close']/df_prec_dev['EPS'],1)
  df_prec_dev['Dev%_PE'] = round((df_prec_dev['Curr_PE'] - df_prec_dev['MedPE'])*100/df_prec_dev['MedPE'],2)
  df_prec_dev['Conviction'] = df_prec_dev['Conviction'] + '-' + df_prec_dev['CapType']
  return df_prec_dev

# function to arrange stock features
def arrange_features(df_stocks, common_cols, diff_cols):
  df_stocks_common = df_stocks[common_cols].drop_duplicates()
  df_stocks_diff = df_stocks[diff_cols]
  df_stocks_diff['Investment'] = df_stocks_diff['AvgCost'] * df_stocks_diff['Shares']
  df_stocks_diff = df_stocks_diff.groupby(['Symbol'])[['Shares', 'Investment']].aggregate(['sum']).reset_index()
  df_stocks_diff.columns = ['Symbol', 'Shares', 'Investment']
  df_stocks_diff['AvgCost'] = round(df_stocks_diff['Investment']/df_stocks_diff['Shares'],2)
  df_stocks = pd.merge(df_stocks_diff, df_stocks_common, on='Symbol')
  return df_stocks

# plot fact distribution across dimension
def plot_pie_chart(df, dimension, fact):
  # grouping the data by category and calculating the sum of fact for each type
  grouped_data = df.groupby(dimension)[fact].sum()

  # sorting the grouped data in descending order
  grouped_data = grouped_data.sort_values(ascending=False)

  # creating a pie chart
  grouped_data.plot.pie(autopct='%1.1f%%', startangle=90, figsize=(6, 6))

  # adding a title and displaying the plot
  plt.title(f'{dimension} {fact} Distribution')
  plt.ylabel('')  # To hide the y-label
  plt.show()

In [7]:
# function to get portfolio features

def get_portfolio_features(df_common_features):

  print_date_time()
  print('-------------------')

  #df_common_features["Target"] = df_common_features["Target"].fillna(df_common_features["Max"])
  df_common_features['NTT'] = np.where(df_common_features['Strategy']== 'NTT', df_common_features["Target"], df_common_features['Max'])
  df_common_features['LTT'] = np.where(df_common_features['Strategy']== 'BTT', df_common_features["Target"], df_common_features['Max'])
  df_common_features['BOL'] = df_common_features['Min']

  tmp_df = df_common_features[df_common_features['Symbol'].isin(mypf_df[mypf_df['InPortfolio'] != 'NA'].Symbol.values)]
  print('qualified stocks: '+str(len(tmp_df['Symbol'].unique())))
  tmp_df1 = tmp_df[tmp_df['LatestQtr'] == 1]
  print('with latest results: '+str(len(tmp_df1['Symbol'].unique())))
  tmp_df1 = tmp_df1[tmp_df1['StarStock'] == 1]
  print('still star stocks: '+str(len(tmp_df1['Symbol'].unique())))
  tmp_df['Investment'] = tmp_df['AvgCost'] * tmp_df['Shares']
  tmp_df['Current'] = round(tmp_df['Close'] * tmp_df['Shares'],0)
  tmp_df['Previous'] = tmp_df['Prev_Close'] * tmp_df['Shares']
  tmp_df['EstimatedST'] = tmp_df['NTT'] * tmp_df['Shares']
  tmp_df['EstimatedLT'] = tmp_df['LTT'] * tmp_df['Shares']
  tmp_df['Current P/L'] = round((tmp_df['Current'] - tmp_df['Investment']),0)
  tmp_df['Today P/L%'] = round((tmp_df['Current'] - tmp_df['Previous'])*100/tmp_df['Previous'],2)
  tmp_df['Current P/L%'] = round((tmp_df['Current'] - tmp_df['Investment'])*100/tmp_df['Investment'],2)
  tmp_df['EstimatedST P/L%'] = round((tmp_df['EstimatedST'] - tmp_df['Investment'])*100/tmp_df['Investment'],2)
  tmp_df['EstimatedLT P/L%'] = round((tmp_df['EstimatedLT'] - tmp_df['Investment'])*100/tmp_df['Investment'],2)
  tmp_df['NTT%'] = round((tmp_df['NTT'] - tmp_df['Close'])*100/tmp_df['Close'],2)
  tmp_df['LTT%'] = round((tmp_df['LTT'] - tmp_df['Close'])*100/tmp_df['Close'],2)
  tmp_df['Gained%'] = round((tmp_df['Close'] - tmp_df['BOL'])*100/tmp_df['BOL'],2)
  investment = round(sum(tmp_df['AvgCost']*tmp_df['Shares']),0)
  current = round(sum(tmp_df['Close']*tmp_df['Shares']),0)
  tmp_df['InitAlloc%'] = round(tmp_df['Investment']*100/investment,2)
  tmp_df['CurrAlloc%'] = round(tmp_df['Current']*100/current,2)
  tmp_df['FTT'] = tmp_df['LTT']
  tmp_df.loc[tmp_df['Strategy'] == 'NTT', 'FTT'] = tmp_df['NTT']
  tmp_df['FTT%'] = tmp_df['LTT%']
  tmp_df.loc[tmp_df['Strategy'] == 'NTT', 'FTT%'] = tmp_df['NTT%']
  tmp_df['FTT Amt'] = round(tmp_df['FTT%'] * tmp_df['Current']/100,0)
  tmp_df['OTT%'] = round((tmp_df['FTT'] - tmp_df['AvgCost'])*100/tmp_df['AvgCost'],2)
  tmp_df['RRR Ind'] = round(tmp_df['Current P/L']/tmp_df['FTT Amt'],2)
  tmp_df['Risk Ind'] = round(tmp_df['Current P/L%']*tmp_df['CurrAlloc%'],0)

  return tmp_df

# function to print portfolio features
def print_portfolio_stats(df_portfolio_features, myinvmt_df):
  from pyxirr import xirr

  total_booked_amt, reserve_amt, cy_booked_amt, py_booked_amt = get_amt()

  dates = myinvmt_df['Date'].values
  dates = np.append(dates, datetime.date.today().strftime('%d-%b-%y'))
  investment = myinvmt_df['Investment'].values
  dates= pd.to_datetime(dates)

  current = round(sum(df_portfolio_features['Close']*df_portfolio_features['Shares']),0) + reserve_amt
  investment_xirr = np.append(investment, current)
  cagr = round(xirr(pd.DataFrame({"dates": dates, "amounts": investment_xirr}))*100,2)

  investment = -sum(investment)
  invested = round(sum(df_portfolio_features['AvgCost']*df_portfolio_features['Shares']),0) + reserve_amt
  previous = round(sum(df_portfolio_features['Prev_Close']*df_portfolio_features['Shares']),0) + reserve_amt
  cy_invested = investment + py_booked_amt

  today_pnl_amount = current-previous
  today_pnl_percentage = round((current-previous)*100/previous,2)

  curr_pnl_amount = current-invested
  curr_pnl_percentage = round((curr_pnl_amount)*100/(cy_invested),2)

  cy_pnl_amount = cy_booked_amt + curr_pnl_amount
  cy_pnl_percentage = round((cy_pnl_amount)*100/cy_invested,2)

  overall_pnl_amount = total_booked_amt + curr_pnl_amount
  overall_pnl_percentage = round((overall_pnl_amount)*100/investment,2)

  estimate_st = round(sum(df_portfolio_features['FTT']*df_portfolio_features['Shares']),0)  + reserve_amt
  est_st_pnl_amount = estimate_st-current
  est_st_pnl_percentage = round((est_st_pnl_amount)*100/current,2)

  estimate_lt = round(sum(df_portfolio_features['LTT']*df_portfolio_features['Shares']),0)  + reserve_amt
  est_lt_pnl_amount = estimate_lt-current
  est_lt_pnl_percentage = round((est_lt_pnl_amount)*100/current,2)

  total_profit = round(sum(df_portfolio_features[df_portfolio_features['Current P/L%'] > 0]['Current']) - sum(df_portfolio_features[df_portfolio_features['Current P/L%'] > 0]['Investment']),0)
  total_loss = round(sum(df_portfolio_features[df_portfolio_features['Current P/L%'] < 0]['Current']) - sum(df_portfolio_features[df_portfolio_features['Current P/L%'] < 0]['Investment']),0)

  cy_booked_percentage = round((cy_booked_amt)*100/current,2)
  py_booked_percentage = round((py_booked_amt)*100/investment,2)
  total_booked_percentage = round((total_booked_amt)*100/investment,2)

  print('-------------------')
  print('Initial Investment: ', format_amt(investment))
  print('CY Investment: ', format_amt(cy_invested))
  print('Reserve: ', format_amt(reserve_amt))
  print('Current: ',  format_amt(current))
  print('-------------------')
  print('Today PnL: '+ '{} ({}%)'.format(format_amt(today_pnl_amount), today_pnl_percentage))
  print('Current PnL: '+ '{} ({}%)'.format(format_amt(curr_pnl_amount), curr_pnl_percentage))
  print('CY Booked + Current PnL: '+ '{} ({}%)'.format(format_amt(cy_pnl_amount), cy_pnl_percentage))
  print('-------------------')
  print('Total profit: ', format_amt(total_profit))
  print('Total loss: ', format_amt(total_loss))
  print('-------------------')
  print('Total Booked + Current PnL: '+ '{} ({}%)'.format(format_amt(overall_pnl_amount), overall_pnl_percentage))
  print('Total Booked PnL: '+ '{} ({}%)'.format(format_amt(total_booked_amt), total_booked_percentage))
  print('Curr Year Booked PnL: '+ '{} ({}%)'.format(format_amt(cy_booked_amt), cy_booked_percentage))
  print('Prev Year Booked PnL: '+ '{} ({}%)'.format(format_amt(py_booked_amt), py_booked_percentage))
  print('===================')
  print('Est FTT: ',  format_amt(estimate_st))
  print('Est FTT PnL: '+ '{} ({}%)'.format(format_amt(est_st_pnl_amount), est_st_pnl_percentage))

  print('===================')
  print('Deployed: ', format_amt(investment))

  print('Current: ', format_amt(current))

  print('CAGR/XIRR %: '+'{}%'.format(cagr))

In [8]:
# get start and end date
start_date, end_date = get_start_end_date()

# get portfolio and prospects data
mypfs_df = get_mypfs_df()
mypps_df = get_mypps_df()
myinvmt_df = get_myinvmt_df()

# merge above datasets
mypf_df = pd.merge(mypfs_df, mypps_df, on="Symbol")

# seggregate dm and sv portfolio
dm_pf = mypf_df[mypf_df['InPortfolio'] == 'DM']
sv_pf = mypf_df[mypf_df['InPortfolio'] == 'SV']

# build portfolio stock dataframe
dm_stocks = get_stock_ids(dm_pf)
sv_stocks = get_stock_ids(sv_pf)
df_stocks = pd.concat([dm_pf,sv_pf], ignore_index = True)

# arrange common and diff stock features
common_cols = ['Symbol', 'Target', 'Criteria', 'Strategy', 'CumlRnk', 'LatestQtr', 'StarStock', 'Conviction', 'Category', 'InFolio', 'XIRR', 'MBQ']
diff_cols = ['Symbol', 'AvgCost', 'Shares']
df_stocks = arrange_features(df_stocks, common_cols, diff_cols)

# get common features
stock_ids = df_stocks['Symbol'].values
df_common_features = get_common_features(stock_ids, df_stocks)

df_common_features.reset_index(drop=True, inplace=True)
df_common_features.drop(['Date'], axis=1, inplace=True)
# get and print portfolio features
df_portfolio_features = get_portfolio_features(df_common_features)

print_portfolio_stats(df_portfolio_features, myinvmt_df)

df = df_portfolio_features
#plot_pie_chart(df, 'CapType', 'Current')
list_ox40n = list(df[df['MBQ'].str.contains('OX40N', na=False)]['Symbol'].values)

Run date time (IST): 2026-08-14 14:14:57
-------------------
qualified stocks: 88
with latest results: 30
still star stocks: 19

-------------------
Initial Investment:  1.46 C
CY Investment:  1.89 C
Reserve:  2.21 L
Current:  1.60 C
-------------------
Today PnL: -76.47 K (-0.48%)
Current PnL: -32.61 L (-17.26%)
CY Booked + Current PnL: -27.97 L (-14.8%)
-------------------
Total profit:  3.86 L
Total loss:  -36.48 L
-------------------
Total Booked + Current PnL: 14.90 L (10.2%)
Total Booked PnL: 47.52 L (32.53%)
Curr Year Booked PnL: 4.65 L (2.91%)
Prev Year Booked PnL: 42.87 L (29.35%)
===================
Est FTT:  2.68 C
Est FTT PnL: 1.08 C (67.44%)
===================
Deployed:  1.46 C
Current:  1.60 C
CAGR/XIRR %: 4.14%

In [9]:
# top 5 near their targets
cols = ['Symbol', 'Today P/L%', 'Current P/L%', 'FTT%', 'OTT%', 'FTT Amt', 'Current P/L', 'Current', 'FTT', 'Dev%_PE', 'RSI_14','Conviction', 'Spread%',  'CumlRnk', 'RRR Ind', 'CurrAlloc%', 'Gained%', 'Criteria', 'Strategy', 'Category']
df_tmp = df_portfolio_features[~df_portfolio_features['Symbol'].isin(['ENRIN','BLUSPRING','DIGITIDE'])]
df_tmp = df_tmp.sort_values(by = 'FTT Amt', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
79,UNITDSPR,1.61,13.08,6.79,20.77,17978.0,30633.0,264777.0,1644.00,0.31,67.0,X-MC,9.54,64.0,1.70,1.68,27.28,X40N,NTT,BREWERIES
78,TTKPRESTIG,-0.76,-22.47,29.11,0.09,22743.0,-22649.0,78128.0,770.00,81.43,42.0,M-SC,11.09,250.0,-1.00,0.50,40.62,OX40N,NTT,DURABLES
68,SIS,-0.23,-0.37,21.72,21.26,24026.0,-413.0,110619.0,528.00,2640.93,52.0,H-SC,22.17,168.0,-0.02,0.70,64.47,OX40N,NTT,MISC
52,M&M,-0.18,8.06,9.96,18.82,25903.0,19391.0,260072.0,3762.88,-5.74,59.0,X-LC,4.67,25.0,0.75,1.65,17.97,X40N,ATH,AUTO
54,MASFIN,-0.79,-7.76,31.80,21.57,28739.0,-7605.0,90375.0,397.04,-20.51,41.0,H-SC,0.77,167.0,-0.26,0.57,7.72,XR,ATH,FINANCE

In [10]:
# top 5 today
df_tmp = df_portfolio_features.sort_values(by = 'Today P/L%', ascending=False)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
30,HAPPSTMNDS,5.88,-47.82,250.85,83.08,167768.0,-61285.0,66880.0,1466.54,-37.88,67.0,H-SC,9.23,152.0,-0.37,0.42,25.27,AR,ATH,IT
10,BATAINDIA,3.62,-51.36,177.98,35.20,111383.0,-66088.0,62582.0,2096.00,-17.98,68.0,X-SC,12.39,91.0,-0.59,0.40,25.73,X40,NTT,FOOTWEAR
43,INDIGOPNTS,3.45,-16.93,20.40,0.02,29581.0,-29553.0,145006.0,1408.00,120.98,69.0,M-SC,6.36,222.0,-1.00,0.92,64.52,OX40N,NTT,PAINTS
24,EASEMYTRIP,3.39,-64.68,312.50,45.70,195159.0,-114364.0,62451.0,26.40,-35.08,38.0,M-SC,6.78,204.0,-0.59,0.40,9.40,XY24,NTT,TRAVEL
84,VOLTAS,2.91,3.81,39.86,45.20,79341.0,7308.0,199050.0,1856.00,18.83,55.0,X-MC,3.65,79.0,0.09,1.26,9.09,XY25,NTT,AC

In [11]:
# bottom 5 today
df_tmp = df_portfolio_features.sort_values(by = 'Today P/L%', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
82,VALIANTORG,-4.99,-32.56,158.24,74.15,174586.0,-53275.0,110330.0,838.0,-298.38,67.0,H-SC,5.61,145.0,-0.31,0.70,64.19,XR,NTT,CHEMICALS
76,TMPV,-4.81,-20.82,80.29,42.75,264533.0,-86635.0,329472.0,600.0,-84.72,42.0,X-LC,4.49,4.0,-0.33,2.09,13.29,XY24,NTT,AUTO
61,RELAXO,-4.67,-48.21,194.11,52.31,145916.0,-69988.0,75172.0,1176.0,-44.83,48.0,X-SC,13.49,92.0,-0.48,0.48,68.07,X40N,NTT,FOOTWEAR
60,RECLTD,-2.65,-9.10,32.82,20.74,60615.0,-18480.0,184690.0,446.0,-0.39,34.0,M-MC,3.24,191.0,-0.30,1.17,11.83,XY25,NTT,FINANCE
70,SURYODAY,-2.17,-12.85,41.18,23.03,64266.0,-23011.0,156060.0,216.0,71.05,33.0,H-SC,16.18,166.0,-0.36,0.99,32.47,XR,NTT,BANKS

In [12]:
# top 5 to exit based on CumlRnk
df_tmp = df_portfolio_features[~df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])]
df_tmp = df_tmp[(df_tmp['Current P/L%'] > -1) & (df_tmp['Current P/L%'] < 1)].sort_values(by = 'CumlRnk', ascending=False)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
80,UTIAMC,0.14,0.25,50.78,51.15,113183.0,559.0,222889.0,1371.68,-19.39,48.0,M-SC,7.60,229.0,0.00,1.41,4.40,XY24,ATH,FINANCE
68,SIS,-0.23,-0.37,21.72,21.26,24026.0,-413.0,110619.0,528.00,2640.93,52.0,H-SC,22.17,168.0,-0.02,0.70,64.47,OX40N,NTT,MISC

In [13]:
# OX40N stocks to exit
df_tmp = df_portfolio_features[(df_portfolio_features['Symbol'].isin(list_ox40n))].sort_values(by = 'Current P/L%', ascending=False)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
25,FINCABLES,0.67,59.29,30.53,107.91,71801.0,87537.0,235181.0,1641.55,43.07,73.0,M-SC,18.29,220.0,1.22,1.49,76.93,OX40N,ATH,CABLES
68,SIS,-0.23,-0.37,21.72,21.26,24026.0,-413.0,110619.0,528.00,2640.93,52.0,H-SC,22.17,168.0,-0.02,0.70,64.47,OX40N,NTT,MISC
43,INDIGOPNTS,3.45,-16.93,20.40,0.02,29581.0,-29553.0,145006.0,1408.00,120.98,69.0,M-SC,6.36,222.0,-1.00,0.92,64.52,OX40N,NTT,PAINTS
78,TTKPRESTIG,-0.76,-22.47,29.11,0.09,22743.0,-22649.0,78128.0,770.00,81.43,42.0,M-SC,11.09,250.0,-1.00,0.50,40.62,OX40N,NTT,DURABLES
16,CERA,0.01,-22.52,59.89,23.89,81629.0,-39605.0,136298.0,9475.00,-25.30,40.0,H-SC,12.59,153.0,-0.49,0.86,32.49,OX40N,NTT,CERAMICS

In [14]:
# top 5 to book for rotation
df_tmp = df_portfolio_features[(df_portfolio_features['Current P/L%'] > 20) ].sort_values(by = 'CumlRnk', ascending=False)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
25,FINCABLES,0.67,59.29,30.53,107.91,71801.0,87537.0,235181.0,1641.55,43.07,73.0,M-SC,18.29,220.0,1.22,1.49,76.93,OX40N,ATH,CABLES
87,ZYDUSLIFE,-2.14,20.46,12.49,35.51,31531.0,42874.0,252448.0,1285.01,4.95,52.0,H-MC,15.88,120.0,1.36,1.60,32.85,AR,ATH,PHARMA
57,QUESS,1.61,38.85,25.24,73.90,37427.0,41492.0,148285.0,424.00,-25.07,70.0,X-SC,42.13,80.0,1.11,0.94,104.09,XY24,NTT,MISC

In [15]:
# top 5 to monitor for exit
df_tmp = df_portfolio_features[~df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])]
df_tmp = df_tmp[(df_tmp['Current P/L%'] > 0) ].sort_values(by = 'Dev%_PE', ascending=False)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
69,STARHEALTH,0.66,13.87,29.32,47.26,93858.0,38994.0,320117.0,761.00,79.65,53.0,H-SC,16.52,173.0,0.42,2.03,38.41,XY24,NTT,INSURANCE
25,FINCABLES,0.67,59.29,30.53,107.91,71801.0,87537.0,235181.0,1641.55,43.07,73.0,M-SC,18.29,220.0,1.22,1.49,76.93,OX40N,ATH,CABLES
87,ZYDUSLIFE,-2.14,20.46,12.49,35.51,31531.0,42874.0,252448.0,1285.01,4.95,52.0,H-MC,15.88,120.0,1.36,1.60,32.85,AR,ATH,PHARMA
80,UTIAMC,0.14,0.25,50.78,51.15,113183.0,559.0,222889.0,1371.68,-19.39,48.0,M-SC,7.60,229.0,0.00,1.41,4.40,XY24,ATH,FINANCE

In [16]:
# top 5 to book for rotation from weak conviction
df_tmp = df_portfolio_features[~df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])]
df_tmp = df_tmp[~df_tmp['Criteria'].isin(['XY25','XY24','X40', 'X40N'])].sort_values(by = 'RRR Ind', ascending=False)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
87,ZYDUSLIFE,-2.14,20.46,12.49,35.51,31531.0,42874.0,252448.0,1285.01,4.95,52.0,H-MC,15.88,120.0,1.36,1.60,32.85,AR,ATH,PHARMA
25,FINCABLES,0.67,59.29,30.53,107.91,71801.0,87537.0,235181.0,1641.55,43.07,73.0,M-SC,18.29,220.0,1.22,1.49,76.93,OX40N,ATH,CABLES
68,SIS,-0.23,-0.37,21.72,21.26,24026.0,-413.0,110619.0,528.00,2640.93,52.0,H-SC,22.17,168.0,-0.02,0.70,64.47,OX40N,NTT,MISC
3,ALKYLAMINE,-0.35,-18.38,135.90,92.54,111988.0,-18558.0,82405.0,4520.85,-12.57,56.0,H-SC,13.85,142.0,-0.17,0.52,56.48,SR,ATH,CHEMICALS
42,INDIAMART,-1.03,-23.29,161.94,100.92,153203.0,-28731.0,94605.0,4675.60,-65.43,42.0,H-SC,13.13,140.0,-0.19,0.60,2.41,AR,ATH,MISC

In [17]:
# top 5 to accumulate based on lowest RSI_14
df_tmp = df_portfolio_features[df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])].sort_values(by = 'RSI_14', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
55,PAGEIND,0.55,-4.23,39.48,33.59,101479.0,-11339.0,257040.0,51217.29,-31.29,30.0,X-MC,8.79,55.0,-0.11,1.63,22.07,X40,ATH,APPARELS
28,GODREJCP,0.15,-14.64,55.70,32.90,118638.0,-36543.0,212994.0,1460.97,-11.70,32.0,X-LC,5.19,32.0,-0.31,1.35,3.68,X40N,ATH,FMCG
56,PGHH,-0.44,-36.68,108.48,32.01,146665.0,-78320.0,135200.0,17616.87,-57.19,35.0,X-MC,19.18,57.0,-0.53,0.86,0.05,X40,ATH,FMCG
34,HDFCBANK,0.40,-11.10,47.41,31.05,123545.0,-32532.0,260588.0,1073.00,-25.96,35.0,X-LC,12.47,26.0,-0.26,1.65,1.15,X40,BTT,BANKS
83,VBL,-1.59,-12.15,54.42,35.66,168205.0,-42758.0,309086.0,669.42,-22.66,36.0,X-LC,7.27,13.0,-0.25,1.96,13.80,X40N,ATH,FMCG

In [18]:
# top 5 to accumulate based on Spread and CumlRnk
df_tmp = df_portfolio_features[df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])]
df_tmp = df_tmp[(df_tmp['CumlRnk'] < 100)].sort_values(by = 'Spread%', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
19,COLPAL,-0.88,-24.90,86.22,39.86,170543.0,-65565.0,197800.0,3683.41,-9.21,38.0,X-MC,1.47,62.0,-0.38,1.25,11.89,XY25,ATH,FMCG
23,DMART,-0.27,-1.06,32.83,31.42,101275.0,-3306.0,308484.0,5391.45,-17.73,53.0,X-LC,2.50,14.0,-0.03,1.96,11.32,X40N,ATH,FMCG
50,KOTAKBANK,0.32,3.46,14.94,18.92,37051.0,8298.0,248000.0,452.46,-9.84,54.0,X-LC,2.74,12.0,0.22,1.57,11.58,X40,ATH,BANKS
26,GILLETTE,0.52,-9.79,43.80,29.72,100324.0,-24846.0,229050.0,10978.86,-30.67,44.0,X-SC,3.23,83.0,-0.25,1.45,5.26,X40,ATH,FMCG
84,VOLTAS,2.91,3.81,39.86,45.20,79341.0,7308.0,199050.0,1856.00,18.83,55.0,X-MC,3.65,79.0,0.09,1.26,9.09,XY25,NTT,AC

In [19]:
# top 5 to accumulate based on lowest Gained%
df_tmp = df_portfolio_features[df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])].sort_values(by = 'Gained%', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
56,PGHH,-0.44,-36.68,108.48,32.01,146665.0,-78320.0,135200.0,17616.87,-57.19,35.0,X-MC,19.18,57.0,-0.53,0.86,0.05,X40,ATH,FMCG
35,HDFCLIFE,0.06,-7.68,50.72,39.15,117412.0,-19247.0,231490.0,811.41,-31.24,40.0,X-LC,16.39,31.0,-0.16,1.47,0.45,X40,ATH,INSURANCE
47,ITC,-0.34,-23.43,62.85,24.70,191187.0,-93083.0,304195.0,452.00,-59.97,40.0,X-LC,10.71,1.0,-0.49,1.93,0.73,X40,NTT,FMCG
20,DABUR,-0.16,-19.97,79.55,43.70,157935.0,-49533.0,198535.0,735.00,-27.41,38.0,X-MC,9.56,70.0,-0.31,1.26,1.03,XY24,BTT,FMCG
34,HDFCBANK,0.40,-11.10,47.41,31.05,123545.0,-32532.0,260588.0,1073.00,-25.96,35.0,X-LC,12.47,26.0,-0.26,1.65,1.15,X40,BTT,BANKS

In [20]:
# top 5 to accumulate based on lowest CurrAlloc%
df_tmp = df_portfolio_features[df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])].sort_values(by = 'CurrAlloc%', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
10,BATAINDIA,3.62,-51.36,177.98,35.20,111383.0,-66088.0,62582.0,2096.00,-17.98,68.0,X-SC,12.39,91.0,-0.59,0.40,25.73,X40,NTT,FOOTWEAR
61,RELAXO,-4.67,-48.21,194.11,52.31,145916.0,-69988.0,75172.0,1176.00,-44.83,48.0,X-SC,13.49,92.0,-0.48,0.48,68.07,X40N,NTT,FOOTWEAR
56,PGHH,-0.44,-36.68,108.48,32.01,146665.0,-78320.0,135200.0,17616.87,-57.19,35.0,X-MC,19.18,57.0,-0.53,0.86,0.05,X40,ATH,FMCG
57,QUESS,1.61,38.85,25.24,73.90,37427.0,41492.0,148285.0,424.00,-25.07,70.0,X-SC,42.13,80.0,1.11,0.94,104.09,XY24,NTT,MISC
2,ACC,-0.28,-40.88,195.69,74.81,310208.0,-109608.0,158520.0,3906.00,-57.90,40.0,X-SC,11.74,85.0,-0.35,1.01,5.90,XY24,BTT,CEMENT

In [21]:
# top 5 to accumulate based on CumlRnk
df_tmp = df_portfolio_features.sort_values(by = 'CumlRnk', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
47,ITC,-0.34,-23.43,62.85,24.70,191187.0,-93083.0,304195.0,452.00,-59.97,40.0,X-LC,10.71,1.0,-0.49,1.93,0.73,X40,NTT,FMCG
74,TCS,-0.84,-30.87,79.65,24.20,255103.0,-142993.0,320280.0,4230.71,-41.33,53.0,X-LC,14.80,2.0,-0.56,2.03,19.43,X40,ATH,IT
45,INFY,-0.63,-16.88,68.89,40.38,215569.0,-63553.0,312917.0,1972.00,-37.59,58.0,X-LC,16.03,3.0,-0.29,1.98,18.50,X40,NTT,IT
76,TMPV,-4.81,-20.82,80.29,42.75,264533.0,-86635.0,329472.0,600.00,-84.72,42.0,X-LC,4.49,4.0,-0.33,2.09,13.29,XY24,NTT,AUTO
33,HCLTECH,-0.42,-8.75,35.85,23.97,101244.0,-27076.0,282410.0,1853.42,-6.95,69.0,X-LC,12.07,8.0,-0.27,1.79,33.26,X40,ATH,IT

In [22]:
# top 5 for average up
df_tmp = df_portfolio_features[(df_portfolio_features['Dev%_200'] > 5)].sort_values(by = 'CurrAlloc%', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
44,INDUSINDBK,-0.91,-25.03,77.27,32.89,44722.0,-19328.0,57878.0,1800.00,-372.41,53.0,L-MC,13.59,258.0,-0.43,0.37,42.69,XR,NTT,BANKS
61,RELAXO,-4.67,-48.21,194.11,52.31,145916.0,-69988.0,75172.0,1176.00,-44.83,48.0,X-SC,13.49,92.0,-0.48,0.48,68.07,X40N,NTT,FOOTWEAR
3,ALKYLAMINE,-0.35,-18.38,135.90,92.54,111988.0,-18558.0,82405.0,4520.85,-12.57,56.0,H-SC,13.85,142.0,-0.17,0.52,56.48,SR,ATH,CHEMICALS
12,BOSCH-HCIL,-0.94,-26.86,36.70,-0.01,34308.0,-34324.0,93481.0,2282.00,19030.43,75.0,M-SC,5.01,231.0,-1.00,0.59,59.12,OX40N,BTT,AC
82,VALIANTORG,-4.99,-32.56,158.24,74.15,174586.0,-53275.0,110330.0,838.00,-298.38,67.0,H-SC,5.61,145.0,-0.31,0.70,64.19,XR,NTT,CHEMICALS

In [23]:
# top 5 RSP
df_tmp = df_portfolio_features.sort_values(by = 'RSP', ascending=False)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
12,BOSCH-HCIL,-0.94,-26.86,36.70,-0.01,34308.0,-34324.0,93481.0,2282.00,19030.43,75.0,M-SC,5.01,231.0,-1.00,0.59,59.12,OX40N,BTT,AC
25,FINCABLES,0.67,59.29,30.53,107.91,71801.0,87537.0,235181.0,1641.55,43.07,73.0,M-SC,18.29,220.0,1.22,1.49,76.93,OX40N,ATH,CABLES
82,VALIANTORG,-4.99,-32.56,158.24,74.15,174586.0,-53275.0,110330.0,838.00,-298.38,67.0,H-SC,5.61,145.0,-0.31,0.70,64.19,XR,NTT,CHEMICALS
33,HCLTECH,-0.42,-8.75,35.85,23.97,101244.0,-27076.0,282410.0,1853.42,-6.95,69.0,X-LC,12.07,8.0,-0.27,1.79,33.26,X40,ATH,IT
57,QUESS,1.61,38.85,25.24,73.90,37427.0,41492.0,148285.0,424.00,-25.07,70.0,X-SC,42.13,80.0,1.11,0.94,104.09,XY24,NTT,MISC

In [24]:
# Top N allocation
df_tmp = df_portfolio_features.sort_values(by = 'CurrAlloc%', ascending=False)
top_n_values = [10, 25, 50]

sum_df = pd.DataFrame({
    'Top_N': top_n_values,
    'Sum_Alloc%': [df_tmp['CurrAlloc%'].head(n).sum() for n in top_n_values]
})

sum_df

   Top_N  Sum_Alloc%
0     10       19.69
1     25       44.76
2     50       76.83

In [25]:
# market-cap-wise allocation
df_tmp = df_portfolio_features[cols]
df_tmp.groupby(df_tmp['Conviction'].str[-2:])['CurrAlloc%'].sum().sort_values(ascending=False)

Conviction
SC    39.36
LC    37.58
MC    23.03
Name: CurrAlloc%, dtype: float64

In [26]:
# criteria-wise allocation
df_portfolio_features.groupby('Criteria')['CurrAlloc%'].sum().sort_values(ascending=False)

Criteria
X40      26.43
XY24     24.85
X40N     18.37
XR        9.00
XY25      7.21
OX40N     7.19
AR        6.08
SR        0.84
Name: CurrAlloc%, dtype: float64

In [27]:
# conviction-wise allocation
df_portfolio_features.groupby('Conviction')['CurrAlloc%'].sum().sort_values(ascending=False)

Conviction
X-LC    35.52
H-SC    19.17
X-MC    18.86
M-SC    11.16
X-SC     8.54
H-MC     2.63
H-LC     1.25
M-MC     1.17
M-LC     0.81
L-SC     0.49
L-MC     0.37
Name: CurrAlloc%, dtype: float64

In [28]:
# sector-wise stats
df_tmp = df_portfolio_features.groupby('Category')[['CurrAlloc%', 'Current', 'Current P/L', 'FTT Amt']].sum().sort_values(by=['Current', 'Current P/L'], ascending=False)
df_tmp['Current P/L%'] = round(df_tmp['Current P/L'] * 100 / df_tmp['Current'], 2)
df_tmp['FTT%'] = round(df_tmp['FTT Amt'] * 100 / df_tmp['Current'], 2)
cols = ['CurrAlloc%', 'Current P/L%', 'FTT%']
df_tmp[cols].sort_values(by=['CurrAlloc%'], ascending=False)

               CurrAlloc%  Current P/L%    FTT%
Category
FMCG                15.35        -23.22   67.52
IT                  11.14        -35.41  102.61
FINANCE             10.59        -15.38   65.08
AUTO                 8.22         -4.42   41.81
MISC                 6.91        -23.01   75.79
BANKS                6.06        -11.60   59.73
PHARMA               5.68          7.58   18.63
INSURANCE            5.64         -4.43   41.36
PAINTS               5.51        -13.60   32.98
ELECTRICAL           4.14         -7.95   45.74
AC                   1.85         -9.24   38.85
REFINERIES           1.69        -11.56   49.03
BREWERIES            1.68         11.57    6.79
FOOTWEAR             1.67        -68.31  135.80
APPARELS             1.63         -4.41   39.48
CABLES               1.49         37.22   30.53
DURABLES             1.47        -67.15  107.82
TRAVEL               1.43        -99.05  198.71
CERAMICS             1.34        -45.18   89.29
CHEMICALS            1.22        -37.27  148.69
ENGINEERING          1.20        -27.51   85.83
CEMENT               1.01        -69.14  195.69
JEWELLERY            0.96       -112.89  186.85
ENTERTAINMENT        0.69        -79.25  186.16
HEALTHCARE           0.67        -70.90  113.80
TEXTILES             0.38        -54.02   97.94
HOTELS               0.35       -105.35  177.78

In [29]:
# money to be made criteria-wise
df_portfolio_features.groupby('Criteria')['FTT Amt'].agg(['sum', 'count']).sort_values(by='sum', ascending=False)

                sum  count
Criteria
XY24      3595102.0     20
X40       2055763.0     18
XR        1376116.0     13
X40N      1183696.0     12
AR        1073199.0      8
OX40N      657010.0     10
XY25       561056.0      5
SR         282991.0      2

In [30]:
# money to be made conviction-wise
df_portfolio_features.groupby('Conviction')['FTT Amt'].agg(['sum', 'count']).sort_values(by='sum', ascending=False)

                  sum  count
Conviction
H-SC        3323558.0     23
X-LC        2455765.0     20
M-SC        1494358.0     15
X-MC        1478146.0     14
X-SC        1232154.0      8
H-MC         282940.0      2
L-SC         214072.0      2
M-LC         163699.0      1
M-MC          60615.0      1
L-MC          44722.0      1
H-LC          34904.0      1

In [31]:
# money to be made criteria and conviction-wise
df_portfolio_features.groupby(['Conviction', 'Criteria'])['FTT Amt'].agg(['sum', 'count']).sort_values(by='sum', ascending=False)

                           sum  count
Conviction Criteria
X-LC       X40       1180801.0      9
H-SC       XY24      1001594.0      5
M-SC       XY24       974429.0      7
H-SC       AR         930637.0      5
           XR         815132.0      7
X-SC       XY24       707444.0      3
X-MC       X40        663255.0      7
X-LC       X40N       525421.0      6
           XY24       440491.0      2
X-MC       X40N       345272.0      3
X-SC       X40N       313003.0      3
H-SC       OX40N      293204.0      4
           SR         282991.0      2
H-MC       XY24       251409.0      1
X-LC       XY25       250557.0      2
X-MC       XY25       249884.0      2
M-SC       OX40N      248039.0      5
X-MC       XY24       219735.0      2
X-SC       X40        211707.0      2
M-SC       XR         195763.0      2
M-LC       XR         163699.0      1
L-SC       OX40N      115767.0      1
           XR          98305.0      1
M-SC       AR          76127.0      1
M-MC       XY25        60615.0      1
X-LC       XR          58495.0      1
L-MC       XR          44722.0      1
H-LC       AR          34904.0      1
H-MC       AR          31531.0      1

In [32]:
# notebook execution time

end_time = time.time()
execution_time = round(end_time - start_time, 0)
print(f"Notebook execution time: {execution_time} seconds")

Notebook execution time: 24.0 seconds