<a href="https://colab.research.google.com/github/ankit-rathi/Quantvesting_v2/blob/main/myStocks_Portfolio_Analysis.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
'''
!pip install pandas==2.2.2 -qq
!pip install pyxirr -qq
!pip install ta -qq
!pip install yfinance==0.2.59 -qq
'''

'\n!pip install pandas==2.2.2 -qq\n!pip install pyxirr -qq\n!pip install ta -qq\n!pip install yfinance==0.2.59 -qq\n'

In [2]:
# import libraries

import numpy as np
import pandas as pd
import datetime
import warnings
warnings.filterwarnings('ignore')
import yfinance as yfin
import ta
import matplotlib.pyplot as plt
import requests

In [3]:
# notebook start time
import time
import datetime
import pytz

start_time = time.time()

# function to print date timestamp
def print_date_time():
  tz_NY = pytz.timezone('Asia/Kolkata')
  datetime_NY = datetime.datetime.now(tz_NY)
  print("Run date time (IST):", datetime_NY.strftime("%Y-%m-%d %H:%M:%S"))

In [4]:
# function to get booked and reserved amount
def get_amt():
  # fetch the JSON data from the URL
  url = "https://raw.githubusercontent.com/ankit-rathi/Tradevesting_v1/main/data/myPortfolioAmts.json"
  response = requests.get(url)
  pf_amts = response.json()  # parse the JSON data

  # extract values from the JSON
  py_booked_amt_dm = pf_amts["py_booked_amt_dm"]
  py_booked_amt_sv = pf_amts["py_booked_amt_sv"]
  cy_booked_amt_dm = pf_amts["cy_booked_amt_dm"]
  cy_booked_amt_sv = pf_amts["cy_booked_amt_sv"]
  reserve_amt_dm = pf_amts["reserve_amt_dm"]
  reserve_amt_sv = pf_amts["reserve_amt_sv"]

  # perform calculations
  py_booked_amt = py_booked_amt_dm + py_booked_amt_sv
  cy_booked_amt = cy_booked_amt_dm + cy_booked_amt_sv
  reserve_amt = reserve_amt_dm + reserve_amt_sv
  total_booked_amt = py_booked_amt + cy_booked_amt

  return total_booked_amt, reserve_amt, cy_booked_amt, py_booked_amt

gen_output = 0

In [5]:
# function to format the amount
def format_amt(number):
    abs_number = abs(number)

    if abs_number >= 1_00_00_000:  # Crores
        formatted_amt = f"{number / 1_00_00_000:.2f} C"
    elif abs_number >= 1_00_000:  # Lakhs
        formatted_amt = f"{number / 1_00_000:.2f} L"
    elif abs_number >= 1_000:  # Thousands
        formatted_amt = f"{number / 1_000:.2f} K"
    else:
        formatted_amt = f"{number:.2f}"

    return formatted_amt

# function to set start and end date
def get_start_end_date():
  start_date = (datetime.date.today() + datetime.timedelta(days=-365)).strftime('%Y-%m-%d')
  end_date = (datetime.date.today() + datetime.timedelta(days=1)).strftime('%Y-%m-%d')
  return start_date, end_date

# function to fetch my portfolio csv
def get_mypfs_df():
  mypfs_df = pd.read_csv('https://raw.githubusercontent.com/ankit-rathi/Tradevesting_v1/main/data/myPortfolioStocks.csv')
  return mypfs_df

# function to fetch my prospects csv
def get_mypps_df():
  mypps_df = pd.read_csv('https://raw.githubusercontent.com/ankit-rathi/Tradevesting_v1/main/data/myProspectsScrips.csv')
  return mypps_df

# function to fetch screener data
def get_myscreen_df():
  myscreen_df = pd.read_csv('https://raw.githubusercontent.com/ankit-rathi/Tradevesting_v1/main/data/myScreenerDB.csv')
  return myscreen_df

# function to fetch momentum data
def get_myinvmt_df():
  myinvmt_df = pd.read_csv('https://raw.githubusercontent.com/ankit-rathi/Tradevesting_v1/main/data/myInvestments.csv')
  return myinvmt_df

# function to get the stock ids
def get_stock_ids(df_pf):
  stock_n100 = df_pf['Symbol'].unique()

  exclude = ['CADILAHC','MMTC', 'MASFIN']

  stock_ids = df_pf[~df_pf['Symbol'].isin(exclude) ]['Symbol'].unique()

  #mypf = mypf[mypf.Forecast.notnull()]
  #stock_ids = mypf['Symbol'].unique()

  #stock_ids.sort()
  return stock_ids

# get features from screener data
def get_screener_features():
  myscreen_df = get_myscreen_df()
  cols = ['Symbol', 'EPS', 'MedPE', 'ROCE%', 'ROE%', 'CapType']
  return myscreen_df[cols]

# get relative strength
def get_relative_strength(stock_list):

    # Dictionary to store stock tickers and their corresponding percentage price change
    stock_changes = {}

    # Loop through each stock and fetch its price data
    for stock in stock_list:
        try:
            # Download the stock data for the given date range
            stock_data = yfin.Ticker(stock + '.NS').history(period='1mo', interval='1d')[map(str.title, ['open', 'close', 'low', 'high', 'volume'])]

            # Calculate the percentage change for the stock
            if len(stock_data) > 0:
                start_price = stock_data['Close'].iloc[0]
                end_price = stock_data['Close'].iloc[-1]
                percent_change = round(((end_price - start_price) / start_price) * 100, 2)
                stock_changes[stock] = percent_change
            else:
                stock_changes[stock] = np.nan  # If no data is available, set to NaN

        except Exception as e:
            print(f"Error fetching data for {stock}: {e}")
            stock_changes[stock] = np.nan

    # Create a DataFrame with stock tickers and their percentage changes
    df = pd.DataFrame(list(stock_changes.items()), columns=['Symbol', 'Percent_Change'])

    # Drop any stocks with missing data (NaN values)
    df = df.dropna()

    # Calculate the percentile rank based on percentage change
    df['RSP'] = round(df['Percent_Change'].rank(pct=True) * 100, 2)
    cols = ['Symbol', 'RSP']
    df = df[cols]
    # Sort by percentile rank (optional)
    df = df.sort_values(by='RSP', ascending=False).reset_index(drop=True)

    return df

In [6]:
# function to get stock technicals
def stock_prec_dev(stock_symbol):
    #stock_symbol = 'ULTRACEMCO.NS'
    short_window = 20
    mid_window = 50
    long_window = 200
    moving_avg = 'SMA'

    start = datetime.datetime(*map(int, start_date.split('-')))
    end = datetime.datetime(*map(int, end_date.split('-')))

    stock_df = yfin.Ticker(stock_symbol + '.NS').history(period='max', interval='1d')[map(str.title, ['open', 'close', 'low', 'high', 'volume'])]

    stock_df['Max'] = round(max(stock_df['Close']),2)
    stock_df = stock_df[(stock_df.index <= end_date) & (stock_df.index >= start_date)]
    stock_df['200_SMA'] = round(stock_df['Close'].rolling(window = 200, min_periods = 1).mean(),0)
    stock_df['Dev%_200'] = round((stock_df['Close'] - stock_df['200_SMA'])*100/stock_df['200_SMA'],2)
    stock_df.dropna(axis = 0, inplace = True) # remove any null rows

    stock_df['20_SMA'] = stock_df['Close'].rolling(window=20).mean()
    stock_df['50_SMA'] = stock_df['Close'].rolling(window=50).mean()
    stock_df['Symbol'] = stock_symbol

    stock_df['Close'] = round(stock_df['Close'],2)
    stock_df['Min'] = round(min(stock_df['Close']),2)
    stock_df['RSI_14'] = ta.momentum.RSIIndicator(close=stock_df['Close'], window=14).rsi()
    stock_df['RSI_14'] = round(stock_df['RSI_14'],0)
    stock_df['Prev_Close'] = stock_df['Close'].shift(1)
    stock_df.drop(['Open', 'Low', 'High', 'Volume'], axis=1, inplace=True)
    stock_df = stock_df.tail(1)

    max_SMA = max(stock_df['20_SMA'].item(), stock_df['50_SMA'].item(), stock_df['200_SMA'].item())
    min_SMA = min(stock_df['20_SMA'].item(), stock_df['50_SMA'].item(), stock_df['200_SMA'].item())
    ABS_Spread = max_SMA - min_SMA
    stock_df['Spread%'] = round((ABS_Spread / stock_df['200_SMA'].item()) * 100,2)

    return stock_df

# function to compute stock attributes
def get_common_features(stock_ids, df_mypf):

  df_prec_dev = pd.DataFrame()
  df_tmp = get_screener_features()
  df_rs = get_relative_strength(stock_ids)

  for stock_id in stock_ids:
      tmp = stock_prec_dev(stock_id)
      tmp = tmp.reset_index()
      df_prec_dev = pd.concat([df_prec_dev, tmp], ignore_index = True)
  df_prec_dev = pd.merge(df_prec_dev, df_mypf, on= 'Symbol')
  df_prec_dev = pd.merge(df_prec_dev, df_tmp, on= 'Symbol', how='left')
  df_prec_dev = pd.merge(df_prec_dev, df_rs, on= 'Symbol', how='left')
  #print(df_prec_dev.columns)
  df_prec_dev['Curr_PE'] = round(df_prec_dev['Close']/df_prec_dev['EPS'],1)
  df_prec_dev['Dev%_PE'] = round((df_prec_dev['Curr_PE'] - df_prec_dev['MedPE'])*100/df_prec_dev['MedPE'],2)
  df_prec_dev['Conviction'] = df_prec_dev['Conviction'] + '-' + df_prec_dev['CapType']
  return df_prec_dev

# function to arrange stock features
def arrange_features(df_stocks, common_cols, diff_cols):
  df_stocks_common = df_stocks[common_cols].drop_duplicates()
  df_stocks_diff = df_stocks[diff_cols]
  df_stocks_diff['Investment'] = df_stocks_diff['AvgCost'] * df_stocks_diff['Shares']
  df_stocks_diff = df_stocks_diff.groupby(['Symbol'])[['Shares', 'Investment']].aggregate(['sum']).reset_index()
  df_stocks_diff.columns = ['Symbol', 'Shares', 'Investment']
  df_stocks_diff['AvgCost'] = round(df_stocks_diff['Investment']/df_stocks_diff['Shares'],2)
  df_stocks = pd.merge(df_stocks_diff, df_stocks_common, on='Symbol')
  return df_stocks

# plot fact distribution across dimension
def plot_pie_chart(df, dimension, fact):
  # grouping the data by category and calculating the sum of fact for each type
  grouped_data = df.groupby(dimension)[fact].sum()

  # sorting the grouped data in descending order
  grouped_data = grouped_data.sort_values(ascending=False)

  # creating a pie chart
  grouped_data.plot.pie(autopct='%1.1f%%', startangle=90, figsize=(6, 6))

  # adding a title and displaying the plot
  plt.title(f'{dimension} {fact} Distribution')
  plt.ylabel('')  # To hide the y-label
  plt.show()

In [7]:
# function to get portfolio features

def get_portfolio_features(df_common_features):

  print_date_time()
  print('-------------------')

  #df_common_features["Target"] = df_common_features["Target"].fillna(df_common_features["Max"])
  df_common_features['NTT'] = np.where(df_common_features['Strategy']== 'NTT', df_common_features["Target"], df_common_features['Max'])
  df_common_features['LTT'] = np.where(df_common_features['Strategy']== 'BTT', df_common_features["Target"], df_common_features['Max'])
  df_common_features['BOL'] = df_common_features['Min']

  tmp_df = df_common_features[df_common_features['Symbol'].isin(mypf_df[mypf_df['InPortfolio'] != 'NA'].Symbol.values)]
  print('qualified stocks: '+str(len(tmp_df['Symbol'].unique())))
  tmp_df1 = tmp_df[tmp_df['LatestQtr'] == 1]
  print('with latest results: '+str(len(tmp_df1['Symbol'].unique())))
  tmp_df1 = tmp_df1[tmp_df1['StarStock'] == 1]
  print('still star stocks: '+str(len(tmp_df1['Symbol'].unique())))
  tmp_df['Investment'] = tmp_df['AvgCost'] * tmp_df['Shares']
  tmp_df['Current'] = round(tmp_df['Close'] * tmp_df['Shares'],0)
  tmp_df['Previous'] = tmp_df['Prev_Close'] * tmp_df['Shares']
  tmp_df['EstimatedST'] = tmp_df['NTT'] * tmp_df['Shares']
  tmp_df['EstimatedLT'] = tmp_df['LTT'] * tmp_df['Shares']
  tmp_df['Current P/L'] = round((tmp_df['Current'] - tmp_df['Investment']),0)
  tmp_df['Today P/L%'] = round((tmp_df['Current'] - tmp_df['Previous'])*100/tmp_df['Previous'],2)
  tmp_df['Current P/L%'] = round((tmp_df['Current'] - tmp_df['Investment'])*100/tmp_df['Investment'],2)
  tmp_df['EstimatedST P/L%'] = round((tmp_df['EstimatedST'] - tmp_df['Investment'])*100/tmp_df['Investment'],2)
  tmp_df['EstimatedLT P/L%'] = round((tmp_df['EstimatedLT'] - tmp_df['Investment'])*100/tmp_df['Investment'],2)
  tmp_df['NTT%'] = round((tmp_df['NTT'] - tmp_df['Close'])*100/tmp_df['Close'],2)
  tmp_df['LTT%'] = round((tmp_df['LTT'] - tmp_df['Close'])*100/tmp_df['Close'],2)
  tmp_df['Gained%'] = round((tmp_df['Close'] - tmp_df['BOL'])*100/tmp_df['BOL'],2)
  investment = round(sum(tmp_df['AvgCost']*tmp_df['Shares']),0)
  current = round(sum(tmp_df['Close']*tmp_df['Shares']),0)
  tmp_df['InitAlloc%'] = round(tmp_df['Investment']*100/investment,2)
  tmp_df['CurrAlloc%'] = round(tmp_df['Current']*100/current,2)
  tmp_df['FTT'] = tmp_df['LTT']
  tmp_df.loc[tmp_df['Strategy'] == 'NTT', 'FTT'] = tmp_df['NTT']
  tmp_df['FTT%'] = tmp_df['LTT%']
  tmp_df.loc[tmp_df['Strategy'] == 'NTT', 'FTT%'] = tmp_df['NTT%']
  tmp_df['FTT Amt'] = round(tmp_df['FTT%'] * tmp_df['Current']/100,0)
  tmp_df['OTT%'] = round((tmp_df['FTT'] - tmp_df['AvgCost'])*100/tmp_df['AvgCost'],2)
  tmp_df['RRR Ind'] = round(tmp_df['Current P/L']/tmp_df['FTT Amt'],2)
  tmp_df['Risk Ind'] = round(tmp_df['Current P/L%']*tmp_df['CurrAlloc%'],0)

  return tmp_df

# function to print portfolio features
def print_portfolio_stats(df_portfolio_features, myinvmt_df):
  from pyxirr import xirr

  total_booked_amt, reserve_amt, cy_booked_amt, py_booked_amt = get_amt()

  dates = myinvmt_df['Date'].values
  dates = np.append(dates, datetime.date.today().strftime('%d-%b-%y'))
  investment = myinvmt_df['Investment'].values
  dates= pd.to_datetime(dates)

  current = round(sum(df_portfolio_features['Close']*df_portfolio_features['Shares']),0) + reserve_amt
  investment_xirr = np.append(investment, current)
  cagr = round(xirr(pd.DataFrame({"dates": dates, "amounts": investment_xirr}))*100,2)

  investment = -sum(investment)
  invested = round(sum(df_portfolio_features['AvgCost']*df_portfolio_features['Shares']),0) + reserve_amt
  previous = round(sum(df_portfolio_features['Prev_Close']*df_portfolio_features['Shares']),0) + reserve_amt
  cy_invested = investment + py_booked_amt

  today_pnl_amount = current-previous
  today_pnl_percentage = round((current-previous)*100/previous,2)

  curr_pnl_amount = current-invested
  curr_pnl_percentage = round((curr_pnl_amount)*100/(cy_invested),2)

  cy_pnl_amount = cy_booked_amt + curr_pnl_amount
  cy_pnl_percentage = round((cy_pnl_amount)*100/cy_invested,2)

  overall_pnl_amount = total_booked_amt + curr_pnl_amount
  overall_pnl_percentage = round((overall_pnl_amount)*100/investment,2)

  estimate_st = round(sum(df_portfolio_features['FTT']*df_portfolio_features['Shares']),0)  + reserve_amt
  est_st_pnl_amount = estimate_st-current
  est_st_pnl_percentage = round((est_st_pnl_amount)*100/current,2)

  estimate_lt = round(sum(df_portfolio_features['LTT']*df_portfolio_features['Shares']),0)  + reserve_amt
  est_lt_pnl_amount = estimate_lt-current
  est_lt_pnl_percentage = round((est_lt_pnl_amount)*100/current,2)

  total_profit = round(sum(df_portfolio_features[df_portfolio_features['Current P/L%'] > 0]['Current']) - sum(df_portfolio_features[df_portfolio_features['Current P/L%'] > 0]['Investment']),0)
  total_loss = round(sum(df_portfolio_features[df_portfolio_features['Current P/L%'] < 0]['Current']) - sum(df_portfolio_features[df_portfolio_features['Current P/L%'] < 0]['Investment']),0)

  cy_booked_percentage = round((cy_booked_amt)*100/current,2)
  py_booked_percentage = round((py_booked_amt)*100/investment,2)
  total_booked_percentage = round((total_booked_amt)*100/investment,2)

  print('-------------------')
  print('Initial Investment: ', format_amt(investment))
  print('CY Investment: ', format_amt(cy_invested))
  print('Reserve: ', format_amt(reserve_amt))
  print('Current: ',  format_amt(current))
  print('-------------------')
  print('Today PnL: '+ '{} ({}%)'.format(format_amt(today_pnl_amount), today_pnl_percentage))
  print('Current PnL: '+ '{} ({}%)'.format(format_amt(curr_pnl_amount), curr_pnl_percentage))
  print('CY Booked + Current PnL: '+ '{} ({}%)'.format(format_amt(cy_pnl_amount), cy_pnl_percentage))
  print('-------------------')
  print('Total profit: ', format_amt(total_profit))
  print('Total loss: ', format_amt(total_loss))
  print('-------------------')
  print('Total Booked + Current PnL: '+ '{} ({}%)'.format(format_amt(overall_pnl_amount), overall_pnl_percentage))
  print('Total Booked PnL: '+ '{} ({}%)'.format(format_amt(total_booked_amt), total_booked_percentage))
  print('Curr Year Booked PnL: '+ '{} ({}%)'.format(format_amt(cy_booked_amt), cy_booked_percentage))
  print('Prev Year Booked PnL: '+ '{} ({}%)'.format(format_amt(py_booked_amt), py_booked_percentage))
  print('===================')
  print('Est FTT: ',  format_amt(estimate_st))
  print('Est FTT PnL: '+ '{} ({}%)'.format(format_amt(est_st_pnl_amount), est_st_pnl_percentage))

  print('===================')
  print('Deployed: ', format_amt(investment))

  print('Current: ', format_amt(current))

  print('CAGR/XIRR %: '+'{}%'.format(cagr))

In [8]:
# get start and end date
start_date, end_date = get_start_end_date()

# get portfolio and prospects data
mypfs_df = get_mypfs_df()
mypps_df = get_mypps_df()
myinvmt_df = get_myinvmt_df()

# merge above datasets
mypf_df = pd.merge(mypfs_df, mypps_df, on="Symbol")

# seggregate dm and sv portfolio
dm_pf = mypf_df[mypf_df['InPortfolio'] == 'DM']
sv_pf = mypf_df[mypf_df['InPortfolio'] == 'SV']

# build portfolio stock dataframe
dm_stocks = get_stock_ids(dm_pf)
sv_stocks = get_stock_ids(sv_pf)
df_stocks = pd.concat([dm_pf,sv_pf], ignore_index = True)

# arrange common and diff stock features
common_cols = ['Symbol', 'Target', 'Criteria', 'Strategy', 'CumlRnk', 'LatestQtr', 'StarStock', 'Conviction', 'Category', 'InFolio', 'XIRR', 'MBQ']
diff_cols = ['Symbol', 'AvgCost', 'Shares']
df_stocks = arrange_features(df_stocks, common_cols, diff_cols)

# get common features
stock_ids = df_stocks['Symbol'].values
df_common_features = get_common_features(stock_ids, df_stocks)

df_common_features.reset_index(drop=True, inplace=True)
df_common_features.drop(['Date'], axis=1, inplace=True)
# get and print portfolio features
df_portfolio_features = get_portfolio_features(df_common_features)

print_portfolio_stats(df_portfolio_features, myinvmt_df)

df = df_portfolio_features
#plot_pie_chart(df, 'CapType', 'Current')
list_ox40n = list(df[df['MBQ'].str.contains('OX40N', na=False)]['Symbol'].values)

Run date time (IST): 2026-08-19 14:25:08
-------------------
qualified stocks: 87
with latest results: 30
still star stocks: 19
-------------------
Initial Investment:  1.46 C
CY Investment:  1.89 C
Reserve:  3.69 L
Current:  1.58 C
-------------------
Today PnL: -45.06 K (-0.29%)
Current PnL: -35.42 L (-18.75%)
CY Booked + Current PnL: -30.36 L (-16.07%)
-------------------
Total profit:  3.39 L
Total loss:  -38.81 L
-------------------
Total Booked + Current PnL: 12.51 L (8.56%)
Total Booked PnL: 47.93 L (32.82%)
Curr Year Booked PnL: 5.06 L (3.21%)
Prev Year Booked PnL: 42.87 L (29.35%)
===================
Est FTT:  2.67 C
Est FTT PnL: 1.10 C (69.56%)
===================
Deployed:  1.46 C
Current:  1.58 C
CAGR/XIRR %: 3.42%

In [9]:
# top 5 near their targets
cols = ['Symbol', 'Today P/L%', 'Current P/L%', 'FTT%', 'OTT%', 'FTT Amt', 'Current P/L', 'Current', 'FTT', 'Dev%_PE', 'RSI_14','Conviction', 'Spread%',  'CumlRnk', 'RRR Ind', 'CurrAlloc%', 'Gained%', 'Criteria', 'Strategy', 'Category']
df_tmp = df_portfolio_features[~df_portfolio_features['Symbol'].isin(['ENRIN','BLUSPRING','DIGITIDE'])]
df_tmp = df_tmp.sort_values(by = 'FTT Amt', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
66,SIEMENS,-1.51,4.71,5.85,10.83,11399.0,8760.0,194855.0,4125.00,-15.10,57.0,H-LC,13.83,51.0,0.77,1.27,37.48,AR,NTT,ELECTRICAL
78,UNITDSPR,-0.30,11.39,8.42,20.77,21960.0,26660.0,260804.0,1644.00,-5.11,59.0,X-MC,10.86,64.0,1.21,1.70,25.37,X40N,NTT,BREWERIES
77,TTKPRESTIG,-1.40,-23.79,31.34,0.09,24069.0,-23978.0,76799.0,770.00,-7.35,40.0,M-SC,9.66,250.0,-1.00,0.50,38.23,OX40N,NTT,DURABLES
52,M&M,-0.13,7.90,10.12,18.82,26281.0,19011.0,259692.0,3762.88,-6.96,58.0,X-LC,4.86,25.0,0.72,1.69,17.80,X40N,ATH,AUTO
67,SIS,0.73,-4.32,26.74,21.26,28407.0,-4799.0,106233.0,528.00,104.27,40.0,H-SC,20.86,168.0,-0.17,0.69,57.95,OX40N,NTT,MISC

In [10]:
# top 5 today
df_tmp = df_portfolio_features.sort_values(by = 'Today P/L%', ascending=False)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
0,5PAISA,4.44,-22.79,46.22,12.90,77977.0,-49787.0,168709.0,593.00,8.23,66.0,H-SC,11.93,170.0,-0.64,1.10,62.81,OX40N,NTT,FINANCE
27,GLAXO,4.35,20.53,12.58,35.69,30217.0,40916.0,240200.0,3380.16,-9.68,86.0,X-MC,9.81,56.0,1.35,1.56,42.76,X40,ATH,PHARMA
3,ALKYLAMINE,3.40,-16.57,130.77,92.54,110157.0,-16726.0,84237.0,4520.85,NaN,60.0,NaN,14.39,142.0,-0.15,0.55,59.96,SR,ATH,CHEMICALS
62,REPCOHOME,2.14,-22.86,146.09,89.82,322855.0,-65508.0,220997.0,880.00,NaN,33.0,NaN,4.31,161.0,-0.20,1.44,6.24,XY24,NTT,FINANCE
65,SHALBY,2.03,-40.40,109.88,25.10,118636.0,-73174.0,107969.0,327.00,NaN,39.0,NaN,7.97,236.0,-0.62,0.70,22.87,XY24,NTT,HEALTHCARE

In [11]:
# bottom 5 today
df_tmp = df_portfolio_features.sort_values(by = 'Today P/L%', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
60,RELAXO,-2.81,-51.67,215.15,52.31,150932.0,-75008.0,70152.0,1176.00,NaN,38.0,NaN,11.96,92.0,-0.50,0.46,56.85,X40N,NTT,FOOTWEAR
83,VOLTAS,-2.64,-4.57,52.16,45.20,95437.0,-8772.0,182970.0,1856.00,31.44,35.0,X-MC,4.55,79.0,-0.09,1.19,0.28,XY25,NTT,AC
29,GREENPANEL,-2.58,-56.86,231.77,43.14,183070.0,-104090.0,78988.0,537.00,NaN,26.0,NaN,11.94,225.0,-0.57,0.51,0.00,XY24,NTT,MISC
25,FINCABLES,-2.40,64.33,26.52,107.91,64344.0,94979.0,242623.0,1641.55,19.75,71.0,M-SC,20.37,220.0,1.48,1.58,82.53,OX40N,ATH,CABLES
55,PAGEIND,-2.03,-7.43,43.52,32.85,108117.0,-19949.0,248430.0,50936.07,-31.21,29.0,X-MC,8.54,55.0,-0.18,1.61,18.63,X40,ATH,APPARELS

In [12]:
# top 5 to exit based on CumlRnk
df_tmp = df_portfolio_features[~df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])]
df_tmp = df_tmp[(df_tmp['Current P/L%'] > -1) & (df_tmp['Current P/L%'] < 1)].sort_values(by = 'CumlRnk', ascending=False)
df_tmp[cols].head()

Empty DataFrame
Columns: [Symbol, Today P/L%, Current P/L%, FTT%, OTT%, FTT Amt, Current P/L, Current, FTT, Dev%_PE, RSI_14, Conviction, Spread%, CumlRnk, RRR Ind, CurrAlloc%, Gained%, Criteria, Strategy, Category]
Index: []

In [13]:
# OX40N stocks to exit
df_tmp = df_portfolio_features[(df_portfolio_features['Symbol'].isin(list_ox40n))].sort_values(by = 'Current P/L%', ascending=False)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
25,FINCABLES,-2.40,64.33,26.52,107.91,64344.0,94979.0,242623.0,1641.55,19.75,71.0,M-SC,20.37,220.0,1.48,1.58,82.53,OX40N,ATH,CABLES
67,SIS,0.73,-4.32,26.74,21.26,28407.0,-4799.0,106233.0,528.00,104.27,40.0,H-SC,20.86,168.0,-0.17,0.69,57.95,OX40N,NTT,MISC
43,INDIGOPNTS,-0.59,-18.73,23.08,0.02,32740.0,-32703.0,141856.0,1408.00,-22.52,62.0,M-SC,7.30,222.0,-1.00,0.92,60.95,OX40N,NTT,PAINTS
0,5PAISA,4.44,-22.79,46.22,12.90,77977.0,-49787.0,168709.0,593.00,8.23,66.0,H-SC,11.93,170.0,-0.64,1.10,62.81,OX40N,NTT,FINANCE
77,TTKPRESTIG,-1.40,-23.79,31.34,0.09,24069.0,-23978.0,76799.0,770.00,-7.35,40.0,M-SC,9.66,250.0,-1.00,0.50,38.23,OX40N,NTT,DURABLES

In [14]:
# top 5 to book for rotation
df_tmp = df_portfolio_features[(df_portfolio_features['Current P/L%'] > 20) ].sort_values(by = 'CumlRnk', ascending=False)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
25,FINCABLES,-2.40,64.33,26.52,107.91,64344.0,94979.0,242623.0,1641.55,19.75,71.0,M-SC,20.37,220.0,1.48,1.58,82.53,OX40N,ATH,CABLES
27,GLAXO,4.35,20.53,12.58,35.69,30217.0,40916.0,240200.0,3380.16,-9.68,86.0,X-MC,9.81,56.0,1.35,1.56,42.76,X40,ATH,PHARMA

In [15]:
# top 5 to monitor for exit
df_tmp = df_portfolio_features[~df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])]
df_tmp = df_tmp[(df_tmp['Current P/L%'] > 0) ].sort_values(by = 'Dev%_PE', ascending=False)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
25,FINCABLES,-2.40,64.33,26.52,107.91,64344.0,94979.0,242623.0,1641.55,19.75,71.0,M-SC,20.37,220.0,1.48,1.58,82.53,OX40N,ATH,CABLES
68,STARHEALTH,0.33,13.37,29.90,47.26,95292.0,37579.0,318702.0,761.00,-0.12,52.0,H-SC,16.30,173.0,0.39,2.07,37.80,XY24,NTT,INSURANCE

In [16]:
# top 5 to book for rotation from weak conviction
df_tmp = df_portfolio_features[~df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])]
df_tmp = df_tmp[~df_tmp['Criteria'].isin(['XY25','XY24','X40', 'X40N'])].sort_values(by = 'RRR Ind', ascending=False)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
25,FINCABLES,-2.40,64.33,26.52,107.91,64344.0,94979.0,242623.0,1641.55,19.75,71.0,M-SC,20.37,220.0,1.48,1.58,82.53,OX40N,ATH,CABLES
3,ALKYLAMINE,3.40,-16.57,130.77,92.54,110157.0,-16726.0,84237.0,4520.85,NaN,60.0,NaN,14.39,142.0,-0.15,0.55,59.96,SR,ATH,CHEMICALS
67,SIS,0.73,-4.32,26.74,21.26,28407.0,-4799.0,106233.0,528.00,104.27,40.0,H-SC,20.86,168.0,-0.17,0.69,57.95,OX40N,NTT,MISC
42,INDIAMART,-1.11,-25.50,169.69,100.92,155921.0,-31450.0,91886.0,4675.60,NaN,34.0,NaN,13.91,140.0,-0.20,0.60,0.00,AR,ATH,MISC
71,TANLA,-0.40,-35.08,234.64,117.25,412455.0,-94979.0,175782.0,1922.32,NaN,47.0,NaN,15.30,147.0,-0.23,1.14,53.90,AR,ATH,IT

In [17]:
# top 5 to accumulate based on lowest RSI_14
df_tmp = df_portfolio_features[df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])].sort_values(by = 'RSI_14', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
19,COLPAL,-1.92,-29.13,97.35,39.86,181694.0,-76725.0,186640.0,3683.41,-14.08,27.0,X-MC,1.69,62.0,-0.42,1.21,5.57,XY25,ATH,FMCG
47,ITC,-1.46,-26.60,69.89,24.70,203793.0,-105687.0,291591.0,452.00,-31.57,28.0,X-LC,10.70,1.0,-0.52,1.90,0.00,X40,NTT,FMCG
56,PGHH,-0.83,-38.19,113.59,32.01,149902.0,-81552.0,131968.0,17616.87,-54.51,28.0,X-SC,19.67,57.0,-0.54,0.86,0.00,X40,ATH,FMCG
55,PAGEIND,-2.03,-7.43,43.52,32.85,108117.0,-19949.0,248430.0,50936.07,-31.21,29.0,X-MC,8.54,55.0,-0.18,1.61,18.63,X40,ATH,APPARELS
34,HDFCBANK,-0.51,-12.15,49.17,31.05,126617.0,-35611.0,257509.0,1073.00,-29.01,31.0,X-LC,12.88,26.0,-0.28,1.67,0.00,X40,BTT,BANKS

In [18]:
# top 5 to accumulate based on Spread and CumlRnk
df_tmp = df_portfolio_features[df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])]
df_tmp = df_tmp[(df_tmp['CumlRnk'] < 100)].sort_values(by = 'Spread%', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
19,COLPAL,-1.92,-29.13,97.35,39.86,181694.0,-76725.0,186640.0,3683.41,-14.08,27.0,X-MC,1.69,62.0,-0.42,1.21,5.57,XY25,ATH,FMCG
23,DMART,0.10,-2.87,35.30,31.42,106907.0,-8938.0,302852.0,5391.45,-18.52,47.0,X-LC,2.32,14.0,-0.08,1.97,9.29,X40N,ATH,FMCG
50,KOTAKBANK,0.89,2.79,15.69,18.92,38659.0,6691.0,246393.0,452.46,-12.85,51.0,X-LC,2.55,12.0,0.17,1.60,10.86,X40,ATH,BANKS
26,GILLETTE,-0.23,-11.38,46.38,29.72,104355.0,-28896.0,225000.0,10978.86,-36.01,36.0,X-SC,3.71,83.0,-0.28,1.46,3.40,X40,ATH,FMCG
1,ABBOTINDIA,-0.81,-11.55,30.44,15.37,48153.0,-20665.0,158190.0,34390.26,-27.99,37.0,X-MC,4.06,58.0,-0.43,1.03,7.16,X40,ATH,PHARMA

In [19]:
# top 5 to accumulate based on lowest Gained%
df_tmp = df_portfolio_features[df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])].sort_values(by = 'Gained%', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
20,DABUR,-1.10,-21.98,84.19,43.70,162940.0,-54529.0,193539.0,735.00,-32.67,32.0,X-MC,10.17,70.0,-0.33,1.26,0.0,XY24,BTT,FMCG
47,ITC,-1.46,-26.60,69.89,24.70,203793.0,-105687.0,291591.0,452.00,-31.57,28.0,X-LC,10.70,1.0,-0.52,1.90,0.0,X40,NTT,FMCG
36,HINDUNILVR,-1.20,-16.36,45.34,21.56,127618.0,-55047.0,281470.0,2922.00,-42.35,36.0,X-LC,6.50,9.0,-0.43,1.83,0.0,XY25,NTT,FMCG
34,HDFCBANK,-0.51,-12.15,49.17,31.05,126617.0,-35611.0,257509.0,1073.00,-29.01,31.0,X-LC,12.88,26.0,-0.28,1.67,0.0,X40,BTT,BANKS
56,PGHH,-0.83,-38.19,113.59,32.01,149902.0,-81552.0,131968.0,17616.87,-54.51,28.0,X-SC,19.67,57.0,-0.54,0.86,0.0,X40,ATH,FMCG

In [20]:
# top 5 to accumulate based on lowest CurrAlloc%
df_tmp = df_portfolio_features[df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])].sort_values(by = 'CurrAlloc%', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
56,PGHH,-0.83,-38.19,113.59,32.01,149902.0,-81552.0,131968.0,17616.87,-54.51,28.0,X-SC,19.67,57.0,-0.54,0.86,0.00,X40,ATH,FMCG
2,ACC,-1.16,-42.32,203.10,74.81,314082.0,-113484.0,154644.0,3906.00,-42.69,34.0,X-SC,11.71,85.0,-0.36,1.01,3.31,XY24,BTT,CEMENT
1,ABBOTINDIA,-0.81,-11.55,30.44,15.37,48153.0,-20665.0,158190.0,34390.26,-27.99,37.0,X-MC,4.06,58.0,-0.43,1.03,7.16,X40,ATH,PHARMA
40,ICICIPRULI,0.47,-17.17,57.28,30.28,93469.0,-33826.0,163179.0,787.27,-46.93,47.0,X-MC,12.47,78.0,-0.36,1.06,8.72,X40,ATH,INSURANCE
39,ICICIGI,-0.05,-14.03,38.29,18.89,65873.0,-28071.0,172038.0,2244.41,-14.33,40.0,X-MC,10.42,66.0,-0.43,1.12,2.49,X40,ATH,INSURANCE

In [21]:
# top 5 to accumulate based on CumlRnk
df_tmp = df_portfolio_features.sort_values(by = 'CumlRnk', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
47,ITC,-1.46,-26.60,69.89,24.70,203793.0,-105687.0,291591.0,452.00,-31.57,28.0,X-LC,10.70,1.0,-0.52,1.90,0.00,X40,NTT,FMCG
73,TCS,0.16,-32.96,85.26,24.20,264792.0,-152703.0,310570.0,4230.71,-44.31,47.0,X-LC,14.29,2.0,-0.58,2.02,15.81,X40,ATH,IT
45,INFY,0.12,-20.53,76.66,40.38,229342.0,-77302.0,299168.0,1972.00,-41.63,47.0,X-LC,15.91,3.0,-0.34,1.94,13.30,X40,NTT,IT
75,TMPV,-0.11,-23.28,86.08,42.75,274790.0,-96881.0,319226.0,600.00,-84.91,36.0,X-LC,4.52,4.0,-0.35,2.08,9.77,XY24,NTT,AUTO
33,HCLTECH,1.48,-11.90,40.71,23.97,111000.0,-36826.0,272660.0,1853.42,-14.26,54.0,X-LC,11.33,8.0,-0.33,1.77,28.66,X40,ATH,IT

In [22]:
# top 5 for average up
df_tmp = df_portfolio_features[(df_portfolio_features['Dev%_200'] > 5)].sort_values(by = 'CurrAlloc%', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
44,INDUSINDBK,-0.20,-25.21,77.69,32.89,44859.0,-19466.0,57741.0,1800.00,325.21,53.0,L-MC,13.15,258.0,-0.43,0.38,42.36,XR,NTT,BANKS
3,ALKYLAMINE,3.40,-16.57,130.77,92.54,110157.0,-16726.0,84237.0,4520.85,NaN,60.0,NaN,14.39,142.0,-0.15,0.55,59.96,SR,ATH,CHEMICALS
12,BOSCH-HCIL,0.26,-23.91,31.41,-0.01,30546.0,-30555.0,97250.0,2282.00,760.49,77.0,M-SC,7.50,231.0,-1.00,0.63,65.53,OX40N,BTT,AC
67,SIS,0.73,-4.32,26.74,21.26,28407.0,-4799.0,106233.0,528.00,104.27,40.0,H-SC,20.86,168.0,-0.17,0.69,57.95,OX40N,NTT,MISC
81,VALIANTORG,0.19,-35.58,170.32,74.15,179517.0,-58205.0,105400.0,838.00,NaN,58.0,NaN,7.87,145.0,-0.32,0.69,56.85,XR,NTT,CHEMICALS

In [23]:
# top 5 RSP
df_tmp = df_portfolio_features.sort_values(by = 'RSP', ascending=False)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
12,BOSCH-HCIL,0.26,-23.91,31.41,-0.01,30546.0,-30555.0,97250.0,2282.00,760.49,77.0,M-SC,7.50,231.0,-1.00,0.63,65.53,OX40N,BTT,AC
25,FINCABLES,-2.40,64.33,26.52,107.91,64344.0,94979.0,242623.0,1641.55,19.75,71.0,M-SC,20.37,220.0,1.48,1.58,82.53,OX40N,ATH,CABLES
27,GLAXO,4.35,20.53,12.58,35.69,30217.0,40916.0,240200.0,3380.16,-9.68,86.0,X-MC,9.81,56.0,1.35,1.56,42.76,X40,ATH,PHARMA
81,VALIANTORG,0.19,-35.58,170.32,74.15,179517.0,-58205.0,105400.0,838.00,NaN,58.0,NaN,7.87,145.0,-0.32,0.69,56.85,XR,NTT,CHEMICALS
38,HYUNDAI,-0.00,13.06,27.30,43.94,77578.0,32835.0,284167.0,2782.73,17.21,63.0,X-LC,5.30,29.0,0.42,1.85,30.47,X40N,ATH,AUTO

In [24]:
# Top N allocation
df_tmp = df_portfolio_features.sort_values(by = 'CurrAlloc%', ascending=False)
top_n_values = [10, 25, 50]

sum_df = pd.DataFrame({
    'Top_N': top_n_values,
    'Sum_Alloc%': [df_tmp['CurrAlloc%'].head(n).sum() for n in top_n_values]
})

sum_df

   Top_N  Sum_Alloc%
0     10       19.71
1     25       44.99
2     50       77.66

In [25]:
# market-cap-wise allocation
df_tmp = df_portfolio_features[cols]
df_tmp.groupby(df_tmp['Conviction'].str[-2:])['CurrAlloc%'].sum().sort_values(ascending=False)

Conviction
LC    37.99
MC    22.27
SC    21.64
Name: CurrAlloc%, dtype: float64

In [26]:
# criteria-wise allocation
df_portfolio_features.groupby('Criteria')['CurrAlloc%'].sum().sort_values(ascending=False)

Criteria
X40      26.66
XY24     24.06
X40N     18.67
XR        9.10
OX40N     7.38
XY25      7.17
AR        6.13
SR        0.88
Name: CurrAlloc%, dtype: float64

In [27]:
# conviction-wise allocation
df_portfolio_features.groupby('Conviction')['CurrAlloc%'].sum().sort_values(ascending=False)

Conviction
X-LC    34.32
X-MC    19.64
H-SC     8.56
X-SC     7.64
M-SC     5.44
H-LC     2.86
M-MC     1.21
H-MC     1.04
M-LC     0.81
L-MC     0.38
Name: CurrAlloc%, dtype: float64

In [28]:
# sector-wise stats
df_tmp = df_portfolio_features.groupby('Category')[['CurrAlloc%', 'Current', 'Current P/L', 'FTT Amt']].sum().sort_values(by=['Current', 'Current P/L'], ascending=False)
df_tmp['Current P/L%'] = round(df_tmp['Current P/L'] * 100 / df_tmp['Current'], 2)
df_tmp['FTT%'] = round(df_tmp['FTT Amt'] * 100 / df_tmp['Current'], 2)
cols = ['CurrAlloc%', 'Current P/L%', 'FTT%']
df_tmp[cols].sort_values(by=['CurrAlloc%'], ascending=False)

               CurrAlloc%  Current P/L%    FTT%
Category
FMCG                15.39        -26.02   71.33
IT                  11.17        -38.63  107.39
FINANCE             10.84        -15.85   65.75
AUTO                 8.30         -6.06   44.04
BANKS                6.13        -13.22   62.04
MISC                 5.97        -34.35   88.39
PHARMA               5.87          8.26   17.76
INSURANCE            5.75         -4.99   42.11
PAINTS               5.50        -16.53   36.41
ELECTRICAL           4.19         -9.81   44.19
AC                   1.82        -14.03   44.96
REFINERIES           1.73        -11.70   49.22
BREWERIES            1.70         10.22    8.42
FOOTWEAR             1.67        -73.11  142.53
APPARELS             1.61         -8.03   43.52
CABLES               1.58         39.15   26.52
DURABLES             1.46        -71.42  113.12
TRAVEL               1.43       -104.38  206.71
CERAMICS             1.34        -49.25   94.59
ENGINEERING          1.24        -27.24   85.43
CHEMICALS            1.24        -39.51  152.75
CEMENT               1.01        -73.38  203.10
JEWELLERY            0.95       -117.97  193.70
HEALTHCARE           0.70        -67.77  109.88
ENTERTAINMENT        0.70        -80.89  188.77
TEXTILES             0.39        -53.20   96.88
HOTELS               0.37       -101.78  172.94

In [29]:
# money to be made criteria-wise
df_portfolio_features.groupby('Criteria')['FTT Amt'].agg(['sum', 'count']).sort_values(by='sum', ascending=False)

                sum  count
Criteria
XY24      3631623.0     19
X40       2120034.0     18
XR        1398495.0     13
X40N      1210709.0     12
AR        1065007.0      8
OX40N      656511.0     10
XY25       594842.0      5
SR         280843.0      2

In [30]:
# money to be made conviction-wise
df_portfolio_features.groupby('Conviction')['FTT Amt'].agg(['sum', 'count']).sort_values(by='sum', ascending=False)

                  sum  count
Conviction
X-LC        2445635.0     19
X-MC        1480154.0     14
X-SC        1106049.0      6
H-SC         835422.0      8
M-SC         328048.0      6
H-MC         254353.0      1
M-LC         167387.0      1
M-MC          58748.0      1
H-LC          50801.0      2
L-MC          44859.0      1

In [31]:
# money to be made criteria and conviction-wise
df_portfolio_features.groupby(['Conviction', 'Criteria'])['FTT Amt'].agg(['sum', 'count']).sort_values(by='sum', ascending=False)

                           sum  count
Conviction Criteria
X-LC       X40       1242487.0      9
X-SC       XY24       677121.0      2
H-SC       XY24       529230.0      3
X-MC       X40        508813.0      6
           X40N       463850.0      4
X-LC       XY24       460608.0      2
           X40N       421256.0      5
X-MC       XY25       277131.0      2
X-LC       XY25       258963.0      2
H-MC       XY24       254353.0      1
X-SC       X40        254257.0      2
X-MC       XY24       230360.0      2
H-SC       OX40N      211162.0      3
X-SC       X40N       174671.0      2
M-LC       XR         167387.0      1
M-SC       OX40N      151699.0      4
           XY24       118009.0      1
H-SC       XR          95030.0      2
X-LC       XR          62321.0      1
M-MC       XY25        58748.0      1
M-SC       XR          58340.0      1
H-LC       AR          50801.0      2
L-MC       XR          44859.0      1

In [32]:
# notebook execution time

end_time = time.time()
execution_time = round(end_time - start_time, 0)
print(f"Notebook execution time: {execution_time} seconds")

Notebook execution time: 46.0 seconds