<a href="https://colab.research.google.com/github/ankit-rathi/Quantvesting_v2/blob/main/myStocks_Portfolio_Analysis.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
'''
!pip install pandas==2.2.2 -qq
!pip install pyxirr -qq
!pip install ta -qq
!pip install yfinance==0.2.59 -qq
'''

'\n!pip install pandas==2.2.2 -qq\n!pip install pyxirr -qq\n!pip install ta -qq\n!pip install yfinance==0.2.59 -qq\n'

In [2]:
# import libraries

import numpy as np
import pandas as pd
import datetime
import warnings
warnings.filterwarnings('ignore')
import yfinance as yfin
import ta
import matplotlib.pyplot as plt
import requests

In [3]:
# notebook start time
import time
import datetime
import pytz

start_time = time.time()

# function to print date timestamp
def print_date_time():
  tz_NY = pytz.timezone('Asia/Kolkata')
  datetime_NY = datetime.datetime.now(tz_NY)
  print("Run date time (IST):", datetime_NY.strftime("%Y-%m-%d %H:%M:%S"))

In [4]:
# function to get booked and reserved amount
def get_amt():
  # fetch the JSON data from the URL
  url = "https://raw.githubusercontent.com/ankit-rathi/Tradevesting_v1/main/data/myPortfolioAmts.json"
  response = requests.get(url)
  pf_amts = response.json()  # parse the JSON data

  # extract values from the JSON
  py_booked_amt_dm = pf_amts["py_booked_amt_dm"]
  py_booked_amt_sv = pf_amts["py_booked_amt_sv"]
  cy_booked_amt_dm = pf_amts["cy_booked_amt_dm"]
  cy_booked_amt_sv = pf_amts["cy_booked_amt_sv"]
  reserve_amt_dm = pf_amts["reserve_amt_dm"]
  reserve_amt_sv = pf_amts["reserve_amt_sv"]

  # perform calculations
  py_booked_amt = py_booked_amt_dm + py_booked_amt_sv
  cy_booked_amt = cy_booked_amt_dm + cy_booked_amt_sv
  reserve_amt = reserve_amt_dm + reserve_amt_sv
  total_booked_amt = py_booked_amt + cy_booked_amt

  return total_booked_amt, reserve_amt, cy_booked_amt, py_booked_amt

gen_output = 0

In [5]:
# function to format the amount
def format_amt(number):
    abs_number = abs(number)

    if abs_number >= 1_00_00_000:  # Crores
        formatted_amt = f"{number / 1_00_00_000:.2f} C"
    elif abs_number >= 1_00_000:  # Lakhs
        formatted_amt = f"{number / 1_00_000:.2f} L"
    elif abs_number >= 1_000:  # Thousands
        formatted_amt = f"{number / 1_000:.2f} K"
    else:
        formatted_amt = f"{number:.2f}"

    return formatted_amt

# function to set start and end date
def get_start_end_date():
  start_date = (datetime.date.today() + datetime.timedelta(days=-365)).strftime('%Y-%m-%d')
  end_date = (datetime.date.today() + datetime.timedelta(days=1)).strftime('%Y-%m-%d')
  return start_date, end_date

# function to fetch my portfolio csv
def get_mypfs_df():
  mypfs_df = pd.read_csv('https://raw.githubusercontent.com/ankit-rathi/Tradevesting_v1/main/data/myPortfolioStocks.csv')
  return mypfs_df

# function to fetch my prospects csv
def get_mypps_df():
  mypps_df = pd.read_csv('https://raw.githubusercontent.com/ankit-rathi/Tradevesting_v1/main/data/myProspectsScrips.csv')
  return mypps_df

# function to fetch screener data
def get_myscreen_df():
  myscreen_df = pd.read_csv('https://raw.githubusercontent.com/ankit-rathi/Tradevesting_v1/main/data/myScreenerDB.csv')
  return myscreen_df

# function to fetch momentum data
def get_myinvmt_df():
  myinvmt_df = pd.read_csv('https://raw.githubusercontent.com/ankit-rathi/Tradevesting_v1/main/data/myInvestments.csv')
  return myinvmt_df

# function to get the stock ids
def get_stock_ids(df_pf):
  stock_n100 = df_pf['Symbol'].unique()

  exclude = ['CADILAHC','MMTC', 'MASFIN']

  stock_ids = df_pf[~df_pf['Symbol'].isin(exclude) ]['Symbol'].unique()

  #mypf = mypf[mypf.Forecast.notnull()]
  #stock_ids = mypf['Symbol'].unique()

  #stock_ids.sort()
  return stock_ids

# get features from screener data
def get_screener_features():
  myscreen_df = get_myscreen_df()
  cols = ['Symbol', 'EPS', 'MedPE', 'ROCE%', 'ROE%', 'CapType']
  return myscreen_df[cols]

# get relative strength
def get_relative_strength(stock_list):

    # Dictionary to store stock tickers and their corresponding percentage price change
    stock_changes = {}

    # Loop through each stock and fetch its price data
    for stock in stock_list:
        try:
            # Download the stock data for the given date range
            stock_data = yfin.Ticker(stock + '.NS').history(period='1mo', interval='1d')[map(str.title, ['open', 'close', 'low', 'high', 'volume'])]

            # Calculate the percentage change for the stock
            if len(stock_data) > 0:
                start_price = stock_data['Close'].iloc[0]
                end_price = stock_data['Close'].iloc[-1]
                percent_change = round(((end_price - start_price) / start_price) * 100, 2)
                stock_changes[stock] = percent_change
            else:
                stock_changes[stock] = np.nan  # If no data is available, set to NaN

        except Exception as e:
            print(f"Error fetching data for {stock}: {e}")
            stock_changes[stock] = np.nan

    # Create a DataFrame with stock tickers and their percentage changes
    df = pd.DataFrame(list(stock_changes.items()), columns=['Symbol', 'Percent_Change'])

    # Drop any stocks with missing data (NaN values)
    df = df.dropna()

    # Calculate the percentile rank based on percentage change
    df['RSP'] = round(df['Percent_Change'].rank(pct=True) * 100, 2)
    cols = ['Symbol', 'RSP']
    df = df[cols]
    # Sort by percentile rank (optional)
    df = df.sort_values(by='RSP', ascending=False).reset_index(drop=True)

    return df

In [6]:
# function to get stock technicals
def stock_prec_dev(stock_symbol):
    #stock_symbol = 'ULTRACEMCO.NS'
    short_window = 20
    mid_window = 50
    long_window = 200
    moving_avg = 'SMA'

    start = datetime.datetime(*map(int, start_date.split('-')))
    end = datetime.datetime(*map(int, end_date.split('-')))

    stock_df = yfin.Ticker(stock_symbol + '.NS').history(period='max', interval='1d')[map(str.title, ['open', 'close', 'low', 'high', 'volume'])]

    stock_df['Max'] = round(max(stock_df['Close']),2)
    stock_df = stock_df[(stock_df.index <= end_date) & (stock_df.index >= start_date)]
    stock_df['200_SMA'] = round(stock_df['Close'].rolling(window = 200, min_periods = 1).mean(),0)
    stock_df['Dev%_200'] = round((stock_df['Close'] - stock_df['200_SMA'])*100/stock_df['200_SMA'],2)
    stock_df.dropna(axis = 0, inplace = True) # remove any null rows

    stock_df['20_SMA'] = stock_df['Close'].rolling(window=20).mean()
    stock_df['50_SMA'] = stock_df['Close'].rolling(window=50).mean()
    stock_df['Symbol'] = stock_symbol

    stock_df['Close'] = round(stock_df['Close'],2)
    stock_df['Min'] = round(min(stock_df['Close']),2)
    stock_df['RSI_14'] = ta.momentum.RSIIndicator(close=stock_df['Close'], window=14).rsi()
    stock_df['RSI_14'] = round(stock_df['RSI_14'],0)
    stock_df['Prev_Close'] = stock_df['Close'].shift(1)
    stock_df.drop(['Open', 'Low', 'High', 'Volume'], axis=1, inplace=True)
    stock_df = stock_df.tail(1)

    max_SMA = max(stock_df['20_SMA'].item(), stock_df['50_SMA'].item(), stock_df['200_SMA'].item())
    min_SMA = min(stock_df['20_SMA'].item(), stock_df['50_SMA'].item(), stock_df['200_SMA'].item())
    ABS_Spread = max_SMA - min_SMA
    stock_df['Spread%'] = round((ABS_Spread / stock_df['200_SMA'].item()) * 100,2)

    return stock_df

# function to compute stock attributes
def get_common_features(stock_ids, df_mypf):

  df_prec_dev = pd.DataFrame()
  df_tmp = get_screener_features()
  df_rs = get_relative_strength(stock_ids)

  for stock_id in stock_ids:
      tmp = stock_prec_dev(stock_id)
      tmp = tmp.reset_index()
      df_prec_dev = pd.concat([df_prec_dev, tmp], ignore_index = True)
  df_prec_dev = pd.merge(df_prec_dev, df_mypf, on= 'Symbol')
  df_prec_dev = pd.merge(df_prec_dev, df_tmp, on= 'Symbol', how='left')
  df_prec_dev = pd.merge(df_prec_dev, df_rs, on= 'Symbol', how='left')
  #print(df_prec_dev.columns)
  df_prec_dev['Curr_PE'] = round(df_prec_dev['Close']/df_prec_dev['EPS'],1)
  df_prec_dev['Dev%_PE'] = round((df_prec_dev['Curr_PE'] - df_prec_dev['MedPE'])*100/df_prec_dev['MedPE'],2)
  df_prec_dev['Conviction'] = df_prec_dev['Conviction'] + '-' + df_prec_dev['CapType']
  return df_prec_dev

# function to arrange stock features
def arrange_features(df_stocks, common_cols, diff_cols):
  df_stocks_common = df_stocks[common_cols].drop_duplicates()
  df_stocks_diff = df_stocks[diff_cols]
  df_stocks_diff['Investment'] = df_stocks_diff['AvgCost'] * df_stocks_diff['Shares']
  df_stocks_diff = df_stocks_diff.groupby(['Symbol'])[['Shares', 'Investment']].aggregate(['sum']).reset_index()
  df_stocks_diff.columns = ['Symbol', 'Shares', 'Investment']
  df_stocks_diff['AvgCost'] = round(df_stocks_diff['Investment']/df_stocks_diff['Shares'],2)
  df_stocks = pd.merge(df_stocks_diff, df_stocks_common, on='Symbol')
  return df_stocks

# plot fact distribution across dimension
def plot_pie_chart(df, dimension, fact):
  # grouping the data by category and calculating the sum of fact for each type
  grouped_data = df.groupby(dimension)[fact].sum()

  # sorting the grouped data in descending order
  grouped_data = grouped_data.sort_values(ascending=False)

  # creating a pie chart
  grouped_data.plot.pie(autopct='%1.1f%%', startangle=90, figsize=(6, 6))

  # adding a title and displaying the plot
  plt.title(f'{dimension} {fact} Distribution')
  plt.ylabel('')  # To hide the y-label
  plt.show()

In [7]:
# function to get portfolio features

def get_portfolio_features(df_common_features):

  print_date_time()
  print('-------------------')

  #df_common_features["Target"] = df_common_features["Target"].fillna(df_common_features["Max"])
  df_common_features['NTT'] = np.where(df_common_features['Strategy']== 'NTT', df_common_features["Target"], df_common_features['Max'])
  df_common_features['LTT'] = np.where(df_common_features['Strategy']== 'BTT', df_common_features["Target"], df_common_features['Max'])
  df_common_features['BOL'] = df_common_features['Min']

  tmp_df = df_common_features[df_common_features['Symbol'].isin(mypf_df[mypf_df['InPortfolio'] != 'NA'].Symbol.values)]
  print('qualified stocks: '+str(len(tmp_df['Symbol'].unique())))
  tmp_df1 = tmp_df[tmp_df['LatestQtr'] == 1]
  print('with latest results: '+str(len(tmp_df1['Symbol'].unique())))
  tmp_df1 = tmp_df1[tmp_df1['StarStock'] == 1]
  print('still star stocks: '+str(len(tmp_df1['Symbol'].unique())))
  tmp_df['Investment'] = tmp_df['AvgCost'] * tmp_df['Shares']
  tmp_df['Current'] = round(tmp_df['Close'] * tmp_df['Shares'],0)
  tmp_df['Previous'] = tmp_df['Prev_Close'] * tmp_df['Shares']
  tmp_df['EstimatedST'] = tmp_df['NTT'] * tmp_df['Shares']
  tmp_df['EstimatedLT'] = tmp_df['LTT'] * tmp_df['Shares']
  tmp_df['Current P/L'] = round((tmp_df['Current'] - tmp_df['Investment']),0)
  tmp_df['Today P/L%'] = round((tmp_df['Current'] - tmp_df['Previous'])*100/tmp_df['Previous'],2)
  tmp_df['Current P/L%'] = round((tmp_df['Current'] - tmp_df['Investment'])*100/tmp_df['Investment'],2)
  tmp_df['EstimatedST P/L%'] = round((tmp_df['EstimatedST'] - tmp_df['Investment'])*100/tmp_df['Investment'],2)
  tmp_df['EstimatedLT P/L%'] = round((tmp_df['EstimatedLT'] - tmp_df['Investment'])*100/tmp_df['Investment'],2)
  tmp_df['NTT%'] = round((tmp_df['NTT'] - tmp_df['Close'])*100/tmp_df['Close'],2)
  tmp_df['LTT%'] = round((tmp_df['LTT'] - tmp_df['Close'])*100/tmp_df['Close'],2)
  tmp_df['Gained%'] = round((tmp_df['Close'] - tmp_df['BOL'])*100/tmp_df['BOL'],2)
  investment = round(sum(tmp_df['AvgCost']*tmp_df['Shares']),0)
  current = round(sum(tmp_df['Close']*tmp_df['Shares']),0)
  tmp_df['InitAlloc%'] = round(tmp_df['Investment']*100/investment,2)
  tmp_df['CurrAlloc%'] = round(tmp_df['Current']*100/current,2)
  tmp_df['FTT'] = tmp_df['LTT']
  tmp_df.loc[tmp_df['Strategy'] == 'NTT', 'FTT'] = tmp_df['NTT']
  tmp_df['FTT%'] = tmp_df['LTT%']
  tmp_df.loc[tmp_df['Strategy'] == 'NTT', 'FTT%'] = tmp_df['NTT%']
  tmp_df['FTT Amt'] = round(tmp_df['FTT%'] * tmp_df['Current']/100,0)
  tmp_df['OTT%'] = round((tmp_df['FTT'] - tmp_df['AvgCost'])*100/tmp_df['AvgCost'],2)
  tmp_df['RRR Ind'] = round(tmp_df['Current P/L']/tmp_df['FTT Amt'],2)
  tmp_df['Risk Ind'] = round(tmp_df['Current P/L%']*tmp_df['CurrAlloc%'],0)

  return tmp_df

# function to print portfolio features
def print_portfolio_stats(df_portfolio_features, myinvmt_df):
  from pyxirr import xirr

  total_booked_amt, reserve_amt, cy_booked_amt, py_booked_amt = get_amt()

  dates = myinvmt_df['Date'].values
  dates = np.append(dates, datetime.date.today().strftime('%d-%b-%y'))
  investment = myinvmt_df['Investment'].values
  dates= pd.to_datetime(dates)

  current = round(sum(df_portfolio_features['Close']*df_portfolio_features['Shares']),0) + reserve_amt
  investment_xirr = np.append(investment, current)
  cagr = round(xirr(pd.DataFrame({"dates": dates, "amounts": investment_xirr}))*100,2)

  investment = -sum(investment)
  invested = round(sum(df_portfolio_features['AvgCost']*df_portfolio_features['Shares']),0) + reserve_amt
  previous = round(sum(df_portfolio_features['Prev_Close']*df_portfolio_features['Shares']),0) + reserve_amt
  cy_invested = investment + py_booked_amt

  today_pnl_amount = current-previous
  today_pnl_percentage = round((current-previous)*100/previous,2)

  curr_pnl_amount = current-invested
  curr_pnl_percentage = round((curr_pnl_amount)*100/(cy_invested),2)

  cy_pnl_amount = cy_booked_amt + curr_pnl_amount
  cy_pnl_percentage = round((cy_pnl_amount)*100/cy_invested,2)

  overall_pnl_amount = total_booked_amt + curr_pnl_amount
  overall_pnl_percentage = round((overall_pnl_amount)*100/investment,2)

  estimate_st = round(sum(df_portfolio_features['FTT']*df_portfolio_features['Shares']),0)  + reserve_amt
  est_st_pnl_amount = estimate_st-current
  est_st_pnl_percentage = round((est_st_pnl_amount)*100/current,2)

  estimate_lt = round(sum(df_portfolio_features['LTT']*df_portfolio_features['Shares']),0)  + reserve_amt
  est_lt_pnl_amount = estimate_lt-current
  est_lt_pnl_percentage = round((est_lt_pnl_amount)*100/current,2)

  total_profit = round(sum(df_portfolio_features[df_portfolio_features['Current P/L%'] > 0]['Current']) - sum(df_portfolio_features[df_portfolio_features['Current P/L%'] > 0]['Investment']),0)
  total_loss = round(sum(df_portfolio_features[df_portfolio_features['Current P/L%'] < 0]['Current']) - sum(df_portfolio_features[df_portfolio_features['Current P/L%'] < 0]['Investment']),0)

  cy_booked_percentage = round((cy_booked_amt)*100/current,2)
  py_booked_percentage = round((py_booked_amt)*100/investment,2)
  total_booked_percentage = round((total_booked_amt)*100/investment,2)

  print('-------------------')
  print('Initial Investment: ', format_amt(investment))
  print('CY Investment: ', format_amt(cy_invested))
  print('Reserve: ', format_amt(reserve_amt))
  print('Current: ',  format_amt(current))
  print('-------------------')
  print('Today PnL: '+ '{} ({}%)'.format(format_amt(today_pnl_amount), today_pnl_percentage))
  print('Current PnL: '+ '{} ({}%)'.format(format_amt(curr_pnl_amount), curr_pnl_percentage))
  print('CY Booked + Current PnL: '+ '{} ({}%)'.format(format_amt(cy_pnl_amount), cy_pnl_percentage))
  print('-------------------')
  print('Total profit: ', format_amt(total_profit))
  print('Total loss: ', format_amt(total_loss))
  print('-------------------')
  print('Total Booked + Current PnL: '+ '{} ({}%)'.format(format_amt(overall_pnl_amount), overall_pnl_percentage))
  print('Total Booked PnL: '+ '{} ({}%)'.format(format_amt(total_booked_amt), total_booked_percentage))
  print('Curr Year Booked PnL: '+ '{} ({}%)'.format(format_amt(cy_booked_amt), cy_booked_percentage))
  print('Prev Year Booked PnL: '+ '{} ({}%)'.format(format_amt(py_booked_amt), py_booked_percentage))
  print('===================')
  print('Est FTT: ',  format_amt(estimate_st))
  print('Est FTT PnL: '+ '{} ({}%)'.format(format_amt(est_st_pnl_amount), est_st_pnl_percentage))

  print('===================')
  print('Deployed: ', format_amt(investment))

  print('Current: ', format_amt(current))

  print('CAGR/XIRR %: '+'{}%'.format(cagr))

In [8]:
# get start and end date
start_date, end_date = get_start_end_date()

# get portfolio and prospects data
mypfs_df = get_mypfs_df()
mypps_df = get_mypps_df()
myinvmt_df = get_myinvmt_df()

# merge above datasets
mypf_df = pd.merge(mypfs_df, mypps_df, on="Symbol")

# seggregate dm and sv portfolio
dm_pf = mypf_df[mypf_df['InPortfolio'] == 'DM']
sv_pf = mypf_df[mypf_df['InPortfolio'] == 'SV']

# build portfolio stock dataframe
dm_stocks = get_stock_ids(dm_pf)
sv_stocks = get_stock_ids(sv_pf)
df_stocks = pd.concat([dm_pf,sv_pf], ignore_index = True)

# arrange common and diff stock features
common_cols = ['Symbol', 'Target', 'Criteria', 'Strategy', 'CumlRnk', 'LatestQtr', 'StarStock', 'Conviction', 'Category', 'InFolio', 'XIRR', 'MBQ']
diff_cols = ['Symbol', 'AvgCost', 'Shares']
df_stocks = arrange_features(df_stocks, common_cols, diff_cols)

# get common features
stock_ids = df_stocks['Symbol'].values
df_common_features = get_common_features(stock_ids, df_stocks)

df_common_features.reset_index(drop=True, inplace=True)
df_common_features.drop(['Date'], axis=1, inplace=True)
# get and print portfolio features
df_portfolio_features = get_portfolio_features(df_common_features)

print_portfolio_stats(df_portfolio_features, myinvmt_df)

df = df_portfolio_features
#plot_pie_chart(df, 'CapType', 'Current')
list_ox40n = list(df[df['MBQ'].str.contains('OX40N', na=False)]['Symbol'].values)

Run date time (IST): 2026-03-16 11:40:31
-------------------
qualified stocks: 86
with latest results: 26
still star stocks: 15
-------------------
Initial Investment:  1.36 C
CY Investment:  1.62 C
Reserve:  66.25 K
Current:  1.31 C
-------------------
Today PnL: -1.85 L (-1.39%)
Current PnL: -45.63 L (-28.08%)
CY Booked + Current PnL: -29.95 L (-18.43%)
-------------------
Total profit:  84.07 K
Total loss:  -46.47 L
-------------------
Total Booked + Current PnL: -2.97 L (-2.19%)
Total Booked PnL: 42.66 L (31.48%)
Curr Year Booked PnL: 15.68 L (11.94%)
Prev Year Booked PnL: 26.98 L (19.91%)
===================
Est FTT:  2.47 C
Est FTT PnL: 1.16 C (88.34%)
===================
Deployed:  1.36 C
Current:  1.31 C
CAGR/XIRR %: -1.57%

In [9]:
# top 5 near their targets
cols = ['Symbol', 'Today P/L%', 'Current P/L%', 'FTT%', 'OTT%', 'FTT Amt', 'Current P/L', 'Current', 'FTT', 'Dev%_PE', 'RSI_14','Conviction', 'Spread%',  'CumlRnk', 'RRR Ind', 'CurrAlloc%', 'Gained%', 'Criteria', 'Strategy', 'Category']
df_tmp = df_portfolio_features[~df_portfolio_features['Symbol'].isin(['ENRIN','BLUSPRING','DIGITIDE'])]
df_tmp = df_tmp.sort_values(by = 'FTT Amt', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
19,COALINDIA,-0.66,14.84,2.46,17.67,4251.0,22330.0,172790.0,478.51,37.73,68.0,L-LC,12.90,185.0,5.25,1.32,34.18,XY25,ATH,MINING
50,MASFIN,-0.75,-8.34,32.63,21.57,29303.0,-8175.0,89805.0,397.04,-20.96,37.0,H-SC,3.02,167.0,-0.28,0.69,24.54,XR,ATH,FINANCE
77,TTKPRESTIG,-6.54,-34.15,52.01,0.09,34513.0,-34419.0,66358.0,770.00,54.11,45.0,M-SC,15.85,250.0,-1.00,0.51,12.12,OX40N,NTT,DURABLES
37,ICICIGI,-0.67,-3.34,23.46,19.34,45378.0,-6680.0,193429.0,2252.93,-18.61,36.0,X-MC,2.04,66.0,-0.15,1.48,6.93,X40,ATH,INSURANCE
2,ABBOTINDIA,-0.30,-9.83,30.93,18.07,49884.0,-17575.0,161280.0,35195.00,-23.22,48.0,X-MC,10.90,58.0,-0.35,1.23,2.24,X40,ATH,PHARMA

In [10]:
# top 5 today
df_tmp = df_portfolio_features.sort_values(by = 'Today P/L%', ascending=False)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
62,SATIN,1.42,-19.05,87.57,51.83,195849.0,-52636.0,223648.0,274.00,-27.73,41.0,H-SC,0.86,159.0,-0.27,1.71,8.95,XY24,NTT,FINANCE
8,AWL,0.87,-39.94,178.10,67.02,381114.0,-142320.0,213989.0,485.00,-67.69,22.0,X-SC,24.31,81.0,-0.37,1.64,0.87,XY24,NTT,FMCG
45,ITC,0.71,-20.03,48.88,19.06,132966.0,-68140.0,272026.0,452.00,-55.92,35.0,X-LC,17.18,1.0,-0.51,2.08,0.71,X40,NTT,FMCG
81,VBL,0.69,-18.38,66.23,35.67,170730.0,-58058.0,257784.0,671.64,-27.94,29.0,X-LC,5.95,13.0,-0.34,1.97,0.69,X40N,ATH,FMCG
42,INDUSINDBK,0.55,-39.55,119.82,32.89,55925.0,-30532.0,46674.0,1800.00,-319.89,30.0,L-MC,9.40,258.0,-0.55,0.36,28.54,XR,NTT,BANKS

In [11]:
# bottom 5 today
df_tmp = df_portfolio_features.sort_values(by = 'Today P/L%', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
11,BANDHANBNK,-6.80,-21.32,144.54,92.42,316809.0,-59375.0,219184.0,400.00,88.22,42.0,H-SC,9.40,174.0,-0.19,1.68,20.74,XY24,NTT,BANKS
77,TTKPRESTIG,-6.54,-34.15,52.01,0.09,34513.0,-34419.0,66358.0,770.00,54.11,45.0,M-SC,15.85,250.0,-1.00,0.51,12.12,OX40N,NTT,DURABLES
31,HAPPSTMNDS,-5.85,-53.78,299.92,84.85,177673.0,-68925.0,59240.0,1480.71,-45.14,46.0,H-SC,27.83,152.0,-0.39,0.45,9.70,AR,ATH,IT
55,RAJESHEXPO,-4.92,-79.78,394.98,0.07,109536.0,-109445.0,27732.0,518.00,916.41,20.0,L-SC,24.53,268.0,-1.00,0.21,0.00,OX40N,NTT,JEWELLERY
15,BSOFT,-4.37,-37.56,141.49,50.79,124259.0,-52831.0,87822.0,831.70,-19.98,33.0,H-SC,7.49,172.0,-0.43,0.67,2.25,XR,ATH,IT

In [12]:
# top 5 to exit based on CumlRnk
df_tmp = df_portfolio_features[~df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])]
df_tmp = df_tmp[(df_tmp['Current P/L%'] > -1) & (df_tmp['Current P/L%'] < 1)].sort_values(by = 'CumlRnk', ascending=False)
df_tmp[cols].head()

Empty DataFrame
Columns: [Symbol, Today P/L%, Current P/L%, FTT%, OTT%, FTT Amt, Current P/L, Current, FTT, Dev%_PE, RSI_14, Conviction, Spread%, CumlRnk, RRR Ind, CurrAlloc%, Gained%, Criteria, Strategy, Category]
Index: []

In [13]:
# OX40N stocks to exit
df_tmp = df_portfolio_features[(df_portfolio_features['Symbol'].isin(list_ox40n))].sort_values(by = 'Current P/L%', ascending=False)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
27,FINCABLES,-1.21,7.11,94.12,107.91,148839.0,10493.0,158137.0,1641.55,-3.60,48.0,M-SC,7.78,220.0,0.07,1.21,18.97,OX40N,ATH,CABLES
77,TTKPRESTIG,-6.54,-34.15,52.01,0.09,34513.0,-34419.0,66358.0,770.00,54.11,45.0,M-SC,15.85,250.0,-1.00,0.51,12.12,OX40N,NTT,DURABLES
66,SIS,-0.54,-36.18,90.00,21.26,63778.0,-40168.0,70864.0,528.00,1655.96,30.0,H-SC,12.24,168.0,-0.63,0.54,0.00,OX40N,NTT,MISC
70,SYMPHONY,-0.67,-39.24,64.54,-0.03,67109.0,-67160.0,103981.0,1306.00,-51.21,41.0,M-SC,14.52,205.0,-1.00,0.80,5.15,OX40N,NTT,DURABLES
72,TATAELXSI,-1.73,-39.74,119.10,32.03,94617.0,-52392.0,79443.0,9161.00,-24.56,25.0,H-SC,18.18,158.0,-0.55,0.61,0.00,OX40N,NTT,IT

In [14]:
# top 5 to book for rotation
df_tmp = df_portfolio_features[(df_portfolio_features['Current P/L%'] > 20) ].sort_values(by = 'CumlRnk', ascending=False)
df_tmp[cols].head()

Empty DataFrame
Columns: [Symbol, Today P/L%, Current P/L%, FTT%, OTT%, FTT Amt, Current P/L, Current, FTT, Dev%_PE, RSI_14, Conviction, Spread%, CumlRnk, RRR Ind, CurrAlloc%, Gained%, Criteria, Strategy, Category]
Index: []

In [15]:
# top 5 to monitor for exit
df_tmp = df_portfolio_features[~df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])]
df_tmp = df_tmp[(df_tmp['Current P/L%'] > 0) ].sort_values(by = 'Dev%_PE', ascending=False)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
19,COALINDIA,-0.66,14.84,2.46,17.67,4251.0,22330.0,172790.0,478.51,37.73,68.0,L-LC,12.90,185.0,5.25,1.32,34.18,XY25,ATH,MINING
27,FINCABLES,-1.21,7.11,94.12,107.91,148839.0,10493.0,158137.0,1641.55,-3.60,48.0,M-SC,7.78,220.0,0.07,1.21,18.97,OX40N,ATH,CABLES
1,ABB,-2.98,13.79,27.93,45.57,83146.0,36077.0,297696.0,7934.00,-26.88,59.0,H-MC,11.44,125.0,0.43,2.28,32.20,AR,NTT,ELECTRICAL

In [16]:
# top 5 to book for rotation from weak conviction
df_tmp = df_portfolio_features[~df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])]
df_tmp = df_tmp[~df_tmp['Criteria'].isin(['XY25','XY24','X40', 'X40N'])].sort_values(by = 'RRR Ind', ascending=False)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
1,ABB,-2.98,13.79,27.93,45.57,83146.0,36077.0,297696.0,7934.00,-26.88,59.0,H-MC,11.44,125.0,0.43,2.28,32.20,AR,NTT,ELECTRICAL
27,FINCABLES,-1.21,7.11,94.12,107.91,148839.0,10493.0,158137.0,1641.55,-3.60,48.0,M-SC,7.78,220.0,0.07,1.21,18.97,OX40N,ATH,CABLES
40,INDIAMART,-0.09,-9.76,129.08,106.72,143666.0,-12036.0,111300.0,4810.62,-59.38,41.0,H-SC,9.80,140.0,-0.08,0.85,11.34,AR,ATH,MISC
85,ZYDUSLIFE,-2.15,-6.53,45.10,35.63,88348.0,-13680.0,195894.0,1286.17,-18.47,42.0,H-MC,5.09,120.0,-0.15,1.50,9.06,AR,ATH,PHARMA
84,WIPRO,-1.59,-20.25,116.00,72.27,156758.0,-34312.0,135136.0,420.00,-27.84,27.0,M-LC,15.55,98.0,-0.22,1.03,0.00,XR,NTT,IT

In [17]:
# top 5 to accumulate based on lowest RSI_14
df_tmp = df_portfolio_features[df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])].sort_values(by = 'RSI_14', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
58,RELAXO,-3.90,-63.32,315.25,52.31,167845.0,-91918.0,53242.0,1176.00,-60.99,14.0,X-SC,20.92,92.0,-0.55,0.41,0.00,X40N,NTT,FOOTWEAR
12,BATAINDIA,-3.52,-56.47,210.61,35.20,117958.0,-72662.0,56008.0,2096.00,-26.50,16.0,X-SC,27.52,91.0,-0.62,0.43,0.00,X40,NTT,FOOTWEAR
53,PGHH,-3.21,-23.69,72.99,32.01,118933.0,-50576.0,162944.0,17616.87,-48.34,17.0,X-MC,12.37,57.0,-0.43,1.25,0.00,X40,ATH,FMCG
3,ACC,0.04,-38.37,183.66,74.81,303480.0,-102888.0,165240.0,3906.00,-56.11,17.0,X-SC,14.11,85.0,-0.34,1.26,0.04,XY24,BTT,CEMENT
13,BERGEPAINT,-2.86,-26.99,71.65,25.32,134825.0,-69578.0,188171.0,680.00,-31.00,18.0,X-MC,16.63,68.0,-0.52,1.44,0.00,XY24,NTT,PAINTS

In [18]:
# top 5 to accumulate based on Spread and CumlRnk
df_tmp = df_portfolio_features[df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])]
df_tmp = df_tmp[(df_tmp['CumlRnk'] < 100)].sort_values(by = 'Spread%', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
78,UNITDSPR,-0.14,-3.58,25.26,20.77,57024.0,-8394.0,225750.0,1644.00,-14.48,40.0,X-MC,1.04,64.0,-0.15,1.73,2.88,X40N,NTT,BREWERIES
37,ICICIGI,-0.67,-3.34,23.46,19.34,45378.0,-6680.0,193429.0,2252.93,-18.61,36.0,X-MC,2.04,66.0,-0.15,1.48,6.93,X40,ATH,INSURANCE
75,TMPV,-0.43,-28.81,91.85,36.58,232682.0,-102513.0,253328.0,600.00,-84.72,29.0,X-LC,2.15,4.0,-0.44,1.94,0.00,XY24,NTT,AUTO
22,DABUR,0.39,-10.99,61.45,43.70,135679.0,-27272.0,220796.0,735.00,-19.28,30.0,X-MC,2.37,70.0,-0.20,1.69,2.40,XY24,BTT,FMCG
38,ICICIPRULI,-0.03,-3.44,35.38,30.73,67306.0,-6768.0,190237.0,790.00,-29.40,25.0,X-MC,2.83,78.0,-0.10,1.46,8.83,X40,ATH,INSURANCE

In [19]:
# top 5 to accumulate based on lowest Gained%
df_tmp = df_portfolio_features[df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])].sort_values(by = 'Gained%', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
10,BAJAJHLDNG,-0.53,-15.45,52.83,29.22,84925.0,-29373.0,160752.0,14451.52,-21.72,21.0,X-LC,13.24,28.0,-0.35,1.23,0.0,X40,ATH,FINANCE
12,BATAINDIA,-3.52,-56.47,210.61,35.20,117958.0,-72662.0,56008.0,2096.00,-26.50,16.0,X-SC,27.52,91.0,-0.62,0.43,0.0,X40,NTT,FOOTWEAR
9,BAJAJHFL,-1.97,-28.07,125.38,62.13,246263.0,-76633.0,196413.0,181.50,-40.84,24.0,X-MC,19.09,60.0,-0.31,1.50,0.0,X40N,ATH,FINANCE
13,BERGEPAINT,-2.86,-26.99,71.65,25.32,134825.0,-69578.0,188171.0,680.00,-31.00,18.0,X-MC,16.63,68.0,-0.52,1.44,0.0,XY24,NTT,PAINTS
21,COLPAL,-0.75,-26.24,91.85,41.51,178428.0,-69105.0,194260.0,3726.84,-10.78,30.0,X-MC,4.15,62.0,-0.39,1.49,0.0,XY25,ATH,FMCG

In [20]:
# top 5 to accumulate based on lowest CurrAlloc%
df_tmp = df_portfolio_features[df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])].sort_values(by = 'CurrAlloc%', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
58,RELAXO,-3.90,-63.32,315.25,52.31,167845.0,-91918.0,53242.0,1176.00,-60.99,14.0,X-SC,20.92,92.0,-0.55,0.41,0.00,X40N,NTT,FOOTWEAR
12,BATAINDIA,-3.52,-56.47,210.61,35.20,117958.0,-72662.0,56008.0,2096.00,-26.50,16.0,X-SC,27.52,91.0,-0.62,0.43,0.00,X40,NTT,FOOTWEAR
54,QUESS,-2.59,-27.40,139.53,73.90,108178.0,-29263.0,77530.0,424.00,-60.88,31.0,X-SC,18.77,80.0,-0.27,0.59,0.00,XY24,NTT,MISC
36,HONAUT,-2.16,-23.77,98.49,51.31,144780.0,-45838.0,147000.0,58357.33,-36.56,33.0,X-SC,14.12,90.0,-0.32,1.13,0.00,X40N,ATH,ELECTRICAL
65,SIEMENS,-2.21,-15.73,48.94,25.51,76753.0,-29265.0,156830.0,4671.50,31.69,45.0,H-LC,3.77,51.0,-0.38,1.20,15.49,AR,ATH,ELECTRICAL

In [21]:
# top 5 to accumulate based on CumlRnk
df_tmp = df_portfolio_features.sort_values(by = 'CumlRnk', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
45,ITC,0.71,-20.03,48.88,19.06,132966.0,-68140.0,272026.0,452.00,-55.92,35.0,X-LC,17.18,1.0,-0.51,2.08,0.71,X40,NTT,FMCG
73,TCS,-1.37,-30.21,81.36,26.57,263058.0,-139947.0,323326.0,4311.59,-41.00,18.0,X-LC,15.24,2.0,-0.53,2.48,0.00,X40,ATH,IT
43,INFY,-1.59,-16.37,60.52,34.24,158363.0,-51218.0,261670.0,1972.00,-34.33,21.0,X-LC,13.49,3.0,-0.32,2.00,0.00,X40,NTT,IT
75,TMPV,-0.43,-28.81,91.85,36.58,232682.0,-102513.0,253328.0,600.00,-84.72,29.0,X-LC,2.15,4.0,-0.44,1.94,0.00,XY24,NTT,AUTO
34,HCLTECH,-0.84,-14.71,45.19,23.83,93247.0,-35579.0,206345.0,1908.19,-10.26,25.0,X-LC,10.18,8.0,-0.38,1.58,0.00,X40,ATH,IT

In [22]:
# top 5 for average up
df_tmp = df_portfolio_features[(df_portfolio_features['Dev%_200'] > 5)].sort_values(by = 'CurrAlloc%', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
19,COALINDIA,-0.66,14.84,2.46,17.67,4251.0,22330.0,172790.0,478.51,37.73,68.0,L-LC,12.90,185.0,5.25,1.32,34.18,XY25,ATH,MINING
1,ABB,-2.98,13.79,27.93,45.57,83146.0,36077.0,297696.0,7934.00,-26.88,59.0,H-MC,11.44,125.0,0.43,2.28,32.20,AR,NTT,ELECTRICAL

In [23]:
# top 5 RSP
df_tmp = df_portfolio_features.sort_values(by = 'RSP', ascending=False)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
19,COALINDIA,-0.66,14.84,2.46,17.67,4251.0,22330.0,172790.0,478.51,37.73,68.0,L-LC,12.90,185.0,5.25,1.32,34.18,XY25,ATH,MINING
1,ABB,-2.98,13.79,27.93,45.57,83146.0,36077.0,297696.0,7934.00,-26.88,59.0,H-MC,11.44,125.0,0.43,2.28,32.20,AR,NTT,ELECTRICAL
27,FINCABLES,-1.21,7.11,94.12,107.91,148839.0,10493.0,158137.0,1641.55,-3.60,48.0,M-SC,7.78,220.0,0.07,1.21,18.97,OX40N,ATH,CABLES
69,SURYODAY,-3.61,-27.54,69.80,23.03,90568.0,-49317.0,129754.0,216.00,40.35,47.0,H-SC,7.62,166.0,-0.54,0.99,28.74,XR,NTT,BANKS
2,ABBOTINDIA,-0.30,-9.83,30.93,18.07,49884.0,-17575.0,161280.0,35195.00,-23.22,48.0,X-MC,10.90,58.0,-0.35,1.23,2.24,X40,ATH,PHARMA

In [24]:
# Top N allocation
df_tmp = df_portfolio_features.sort_values(by = 'CurrAlloc%', ascending=False)
top_n_values = [10, 25, 50]

sum_df = pd.DataFrame({
    'Top_N': top_n_values,
    'Sum_Alloc%': [df_tmp['CurrAlloc%'].head(n).sum() for n in top_n_values]
})

sum_df

   Top_N  Sum_Alloc%
0     10       20.57
1     25       45.43
2     50       77.95

In [25]:
# market-cap-wise allocation
df_tmp = df_portfolio_features[cols]
df_tmp.groupby(df_tmp['Conviction'].str[-2:])['CurrAlloc%'].sum().sort_values(ascending=False)

Conviction
SC    44.46
MC    30.44
LC    25.06
Name: CurrAlloc%, dtype: float64

In [26]:
# criteria-wise allocation
df_portfolio_features.groupby('Criteria')['CurrAlloc%'].sum().sort_values(ascending=False)

Criteria
XY24     27.18
X40      23.89
X40N     15.03
AR        9.19
XY25      8.81
XR        8.22
OX40N     6.88
SR        0.76
Name: CurrAlloc%, dtype: float64

In [27]:
# conviction-wise allocation
df_portfolio_features.groupby('Conviction')['CurrAlloc%'].sum().sort_values(ascending=False)

Conviction
X-MC    22.94
H-SC    21.63
X-LC    21.51
X-SC    12.11
M-SC    10.15
H-MC     5.09
M-MC     2.05
L-LC     1.32
H-LC     1.20
M-LC     1.03
L-SC     0.57
L-MC     0.36
Name: CurrAlloc%, dtype: float64

In [28]:
# sector-wise stats
df_tmp = df_portfolio_features.groupby('Category')[['CurrAlloc%', 'Current', 'Current P/L', 'FTT Amt']].sum().sort_values(by=['Current', 'Current P/L'], ascending=False)
df_tmp['Current P/L%'] = round(df_tmp['Current P/L'] * 100 / df_tmp['Current'], 2)
df_tmp['FTT%'] = round(df_tmp['FTT Amt'] * 100 / df_tmp['Current'], 2)
cols = ['CurrAlloc%', 'Current P/L%', 'FTT%']
df_tmp[cols].sort_values(by=['CurrAlloc%'], ascending=False)

               CurrAlloc%  Current P/L%    FTT%
Category
FMCG                15.32        -24.75   69.04
FINANCE             12.95        -27.02   78.78
IT                  11.60        -48.51  124.08
MISC                 6.97        -47.19  111.13
ELECTRICAL           6.69        -10.98   53.48
PAINTS               5.10        -47.75   73.40
INSURANCE            4.84         -7.27   43.98
PHARMA               4.20         -7.04   40.73
AUTO                 3.64        -37.50   92.06
BANKS                3.03        -35.19  117.11
AC                   2.12        -15.24   46.48
HEALTHCARE           1.96        -39.74   76.21
DURABLES             1.89        -57.25   95.51
FOOTWEAR             1.85        -83.19  156.65
TRAVEL               1.82        -87.92  182.01
BREWERIES            1.73         -3.72   25.26
APPARELS             1.60        -28.12   71.83
REALTY               1.46        -15.92   34.96
CERAMICS             1.36        -72.70  125.17
REFINERIES           1.36        -13.18   41.81
MINING               1.32         12.92    2.46
CEMENT               1.26        -62.27  183.66
CABLES               1.21          6.64   94.12
JEWELLERY            1.11       -119.75  196.10
ENGINEERING          1.08        -72.04  150.73
CHEMICALS            0.95       -112.23  285.38
ENTERTAINMENT        0.76        -94.02  209.74
TEXTILES             0.42        -66.74  114.29
HOTELS               0.36       -143.37  229.22

In [29]:
# money to be made criteria-wise
df_portfolio_features.groupby('Criteria')['FTT Amt'].agg(['sum', 'count']).sort_values(by='sum', ascending=False)

                sum  count
Criteria
XY24      4046299.0     21
X40       1751323.0     15
XR        1416894.0     12
AR        1369767.0     10
X40N      1335445.0     10
OX40N      893384.0     10
XY25       466518.0      6
SR         319245.0      2

In [30]:
# money to be made conviction-wise
df_portfolio_features.groupby('Conviction')['FTT Amt'].agg(['sum', 'count']).sort_values(by='sum', ascending=False)

                  sum  count
Conviction
H-SC        3964303.0     24
X-MC        1736238.0     15
X-LC        1663775.0     12
X-SC        1600090.0     10
M-SC        1592039.0     14
H-MC         413794.0      3
L-SC         216481.0      2
M-LC         156758.0      1
M-MC         118468.0      2
H-LC          76753.0      1
L-MC          55925.0      1
L-LC           4251.0      1

In [31]:
# money to be made criteria and conviction-wise
df_portfolio_features.groupby(['Conviction', 'Criteria'])['FTT Amt'].agg(['sum', 'count']).sort_values(by='sum', ascending=False)

                           sum  count
Conviction Criteria
H-SC       XY24      1359720.0      6
           AR         987700.0      5
M-SC       XY24       930290.0      6
H-SC       XR         900773.0      7
X-LC       X40        861500.0      6
X-SC       XY24       858234.0      4
X-MC       X40        679387.0      7
           X40N       536432.0      4
X-SC       X40N       531420.0      4
H-SC       OX40N      396865.0      4
M-SC       OX40N      386983.0      5
X-LC       XY24       385251.0      2
H-SC       SR         319245.0      2
X-MC       XY24       270504.0      2
X-LC       X40N       267593.0      2
X-MC       XY25       249915.0      2
H-MC       XY24       242300.0      1
X-SC       X40        210436.0      2
M-SC       XR         196493.0      2
H-MC       AR         171494.0      2
M-LC       XR         156758.0      1
X-LC       XY25       149431.0      2
L-SC       OX40N      109536.0      1
           XR         106945.0      1
M-SC       AR          78273.0      1
H-LC       AR          76753.0      1
M-MC       XY25        62921.0      1
L-MC       XR          55925.0      1
M-MC       AR          55547.0      1
L-LC       XY25         4251.0      1

In [32]:
# notebook execution time

end_time = time.time()
execution_time = round(end_time - start_time, 0)
print(f"Notebook execution time: {execution_time} seconds")

Notebook execution time: 30.0 seconds