<a href="https://colab.research.google.com/github/ankit-rathi/Quantvesting_v2/blob/main/myStocks_Portfolio_Analysis.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
'''
!pip install pandas==2.2.2 -qq
!pip install pyxirr -qq
!pip install ta -qq
!pip install yfinance==0.2.59 -qq
'''

'\n!pip install pandas==2.2.2 -qq\n!pip install pyxirr -qq\n!pip install ta -qq\n!pip install yfinance==0.2.59 -qq\n'

In [2]:
# import libraries

import numpy as np
import pandas as pd
import datetime
import warnings
warnings.filterwarnings('ignore')
import yfinance as yfin
import ta
import matplotlib.pyplot as plt
import requests

In [3]:
# notebook start time
import time
import datetime
import pytz

start_time = time.time()

# function to print date timestamp
def print_date_time():
  tz_NY = pytz.timezone('Asia/Kolkata')
  datetime_NY = datetime.datetime.now(tz_NY)
  print("Run date time (IST):", datetime_NY.strftime("%Y-%m-%d %H:%M:%S"))

In [4]:
# function to get booked and reserved amount
def get_amt():
  # fetch the JSON data from the URL
  url = "https://raw.githubusercontent.com/ankit-rathi/Tradevesting_v1/main/data/myPortfolioAmts.json"
  response = requests.get(url)
  pf_amts = response.json()  # parse the JSON data

  # extract values from the JSON
  py_booked_amt_dm = pf_amts["py_booked_amt_dm"]
  py_booked_amt_sv = pf_amts["py_booked_amt_sv"]
  cy_booked_amt_dm = pf_amts["cy_booked_amt_dm"]
  cy_booked_amt_sv = pf_amts["cy_booked_amt_sv"]
  reserve_amt_dm = pf_amts["reserve_amt_dm"]
  reserve_amt_sv = pf_amts["reserve_amt_sv"]

  # perform calculations
  py_booked_amt = py_booked_amt_dm + py_booked_amt_sv
  cy_booked_amt = cy_booked_amt_dm + cy_booked_amt_sv
  reserve_amt = reserve_amt_dm + reserve_amt_sv
  total_booked_amt = py_booked_amt + cy_booked_amt

  return total_booked_amt, reserve_amt, cy_booked_amt, py_booked_amt

gen_output = 0

In [5]:
# function to format the amount
def format_amt(number):
    abs_number = abs(number)

    if abs_number >= 1_00_00_000:  # Crores
        formatted_amt = f"{number / 1_00_00_000:.2f} C"
    elif abs_number >= 1_00_000:  # Lakhs
        formatted_amt = f"{number / 1_00_000:.2f} L"
    elif abs_number >= 1_000:  # Thousands
        formatted_amt = f"{number / 1_000:.2f} K"
    else:
        formatted_amt = f"{number:.2f}"

    return formatted_amt

# function to set start and end date
def get_start_end_date():
  start_date = (datetime.date.today() + datetime.timedelta(days=-365)).strftime('%Y-%m-%d')
  end_date = (datetime.date.today() + datetime.timedelta(days=1)).strftime('%Y-%m-%d')
  return start_date, end_date

# function to fetch my portfolio csv
def get_mypfs_df():
  mypfs_df = pd.read_csv('https://raw.githubusercontent.com/ankit-rathi/Tradevesting_v1/main/data/myPortfolioStocks.csv')
  return mypfs_df

# function to fetch my prospects csv
def get_mypps_df():
  mypps_df = pd.read_csv('https://raw.githubusercontent.com/ankit-rathi/Tradevesting_v1/main/data/myProspectsScrips.csv')
  return mypps_df

# function to fetch screener data
def get_myscreen_df():
  myscreen_df = pd.read_csv('https://raw.githubusercontent.com/ankit-rathi/Tradevesting_v1/main/data/myScreenerDB.csv')
  return myscreen_df

# function to fetch momentum data
def get_myinvmt_df():
  myinvmt_df = pd.read_csv('https://raw.githubusercontent.com/ankit-rathi/Tradevesting_v1/main/data/myInvestments.csv')
  return myinvmt_df

# function to get the stock ids
def get_stock_ids(df_pf):
  stock_n100 = df_pf['Symbol'].unique()

  exclude = ['CADILAHC','MMTC', 'MASFIN']

  stock_ids = df_pf[~df_pf['Symbol'].isin(exclude) ]['Symbol'].unique()

  #mypf = mypf[mypf.Forecast.notnull()]
  #stock_ids = mypf['Symbol'].unique()

  #stock_ids.sort()
  return stock_ids

# get features from screener data
def get_screener_features():
  myscreen_df = get_myscreen_df()
  cols = ['Symbol', 'EPS', 'MedPE', 'ROCE%', 'ROE%', 'CapType']
  return myscreen_df[cols]

# get relative strength
def get_relative_strength(stock_list):

    # Dictionary to store stock tickers and their corresponding percentage price change
    stock_changes = {}

    # Loop through each stock and fetch its price data
    for stock in stock_list:
        try:
            # Download the stock data for the given date range
            stock_data = yfin.Ticker(stock + '.NS').history(period='1mo', interval='1d')[map(str.title, ['open', 'close', 'low', 'high', 'volume'])]

            # Calculate the percentage change for the stock
            if len(stock_data) > 0:
                start_price = stock_data['Close'].iloc[0]
                end_price = stock_data['Close'].iloc[-1]
                percent_change = round(((end_price - start_price) / start_price) * 100, 2)
                stock_changes[stock] = percent_change
            else:
                stock_changes[stock] = np.nan  # If no data is available, set to NaN

        except Exception as e:
            print(f"Error fetching data for {stock}: {e}")
            stock_changes[stock] = np.nan

    # Create a DataFrame with stock tickers and their percentage changes
    df = pd.DataFrame(list(stock_changes.items()), columns=['Symbol', 'Percent_Change'])

    # Drop any stocks with missing data (NaN values)
    df = df.dropna()

    # Calculate the percentile rank based on percentage change
    df['RSP'] = round(df['Percent_Change'].rank(pct=True) * 100, 2)
    cols = ['Symbol', 'RSP']
    df = df[cols]
    # Sort by percentile rank (optional)
    df = df.sort_values(by='RSP', ascending=False).reset_index(drop=True)

    return df

In [6]:
# function to get stock technicals
def stock_prec_dev(stock_symbol):
    #stock_symbol = 'ULTRACEMCO.NS'
    short_window = 20
    mid_window = 50
    long_window = 200
    moving_avg = 'SMA'

    start = datetime.datetime(*map(int, start_date.split('-')))
    end = datetime.datetime(*map(int, end_date.split('-')))

    stock_df = yfin.Ticker(stock_symbol + '.NS').history(period='max', interval='1d')[map(str.title, ['open', 'close', 'low', 'high', 'volume'])]

    stock_df['Max'] = round(max(stock_df['Close']),2)
    stock_df = stock_df[(stock_df.index <= end_date) & (stock_df.index >= start_date)]
    stock_df['200_SMA'] = round(stock_df['Close'].rolling(window = 200, min_periods = 1).mean(),0)
    stock_df['Dev%_200'] = round((stock_df['Close'] - stock_df['200_SMA'])*100/stock_df['200_SMA'],2)
    stock_df.dropna(axis = 0, inplace = True) # remove any null rows

    stock_df['20_SMA'] = stock_df['Close'].rolling(window=20).mean()
    stock_df['50_SMA'] = stock_df['Close'].rolling(window=50).mean()
    stock_df['Symbol'] = stock_symbol

    stock_df['Close'] = round(stock_df['Close'],2)
    stock_df['Min'] = round(min(stock_df['Close']),2)
    stock_df['RSI_14'] = ta.momentum.RSIIndicator(close=stock_df['Close'], window=14).rsi()
    stock_df['RSI_14'] = round(stock_df['RSI_14'],0)
    stock_df['Prev_Close'] = stock_df['Close'].shift(1)
    stock_df.drop(['Open', 'Low', 'High', 'Volume'], axis=1, inplace=True)
    stock_df = stock_df.tail(1)

    max_SMA = max(stock_df['20_SMA'].item(), stock_df['50_SMA'].item(), stock_df['200_SMA'].item())
    min_SMA = min(stock_df['20_SMA'].item(), stock_df['50_SMA'].item(), stock_df['200_SMA'].item())
    ABS_Spread = max_SMA - min_SMA
    stock_df['Spread%'] = round((ABS_Spread / stock_df['200_SMA'].item()) * 100,2)

    return stock_df

# function to compute stock attributes
def get_common_features(stock_ids, df_mypf):

  df_prec_dev = pd.DataFrame()
  df_tmp = get_screener_features()
  df_rs = get_relative_strength(stock_ids)

  for stock_id in stock_ids:
      tmp = stock_prec_dev(stock_id)
      tmp = tmp.reset_index()
      df_prec_dev = pd.concat([df_prec_dev, tmp], ignore_index = True)
  df_prec_dev = pd.merge(df_prec_dev, df_mypf, on= 'Symbol')
  df_prec_dev = pd.merge(df_prec_dev, df_tmp, on= 'Symbol', how='left')
  df_prec_dev = pd.merge(df_prec_dev, df_rs, on= 'Symbol', how='left')
  #print(df_prec_dev.columns)
  df_prec_dev['Curr_PE'] = round(df_prec_dev['Close']/df_prec_dev['EPS'],1)
  df_prec_dev['Dev%_PE'] = round((df_prec_dev['Curr_PE'] - df_prec_dev['MedPE'])*100/df_prec_dev['MedPE'],2)
  df_prec_dev['Conviction'] = df_prec_dev['Conviction'] + '-' + df_prec_dev['CapType']
  return df_prec_dev

# function to arrange stock features
def arrange_features(df_stocks, common_cols, diff_cols):
  df_stocks_common = df_stocks[common_cols].drop_duplicates()
  df_stocks_diff = df_stocks[diff_cols]
  df_stocks_diff['Investment'] = df_stocks_diff['AvgCost'] * df_stocks_diff['Shares']
  df_stocks_diff = df_stocks_diff.groupby(['Symbol'])[['Shares', 'Investment']].aggregate(['sum']).reset_index()
  df_stocks_diff.columns = ['Symbol', 'Shares', 'Investment']
  df_stocks_diff['AvgCost'] = round(df_stocks_diff['Investment']/df_stocks_diff['Shares'],2)
  df_stocks = pd.merge(df_stocks_diff, df_stocks_common, on='Symbol')
  return df_stocks

# plot fact distribution across dimension
def plot_pie_chart(df, dimension, fact):
  # grouping the data by category and calculating the sum of fact for each type
  grouped_data = df.groupby(dimension)[fact].sum()

  # sorting the grouped data in descending order
  grouped_data = grouped_data.sort_values(ascending=False)

  # creating a pie chart
  grouped_data.plot.pie(autopct='%1.1f%%', startangle=90, figsize=(6, 6))

  # adding a title and displaying the plot
  plt.title(f'{dimension} {fact} Distribution')
  plt.ylabel('')  # To hide the y-label
  plt.show()

In [7]:
# function to get portfolio features

def get_portfolio_features(df_common_features):

  print_date_time()
  print('-------------------')

  #df_common_features["Target"] = df_common_features["Target"].fillna(df_common_features["Max"])
  df_common_features['NTT'] = np.where(df_common_features['Strategy']== 'NTT', df_common_features["Target"], df_common_features['Max'])
  df_common_features['LTT'] = np.where(df_common_features['Strategy']== 'BTT', df_common_features["Target"], df_common_features['Max'])
  df_common_features['BOL'] = df_common_features['Min']

  tmp_df = df_common_features[df_common_features['Symbol'].isin(mypf_df[mypf_df['InPortfolio'] != 'NA'].Symbol.values)]
  print('qualified stocks: '+str(len(tmp_df['Symbol'].unique())))
  tmp_df1 = tmp_df[tmp_df['LatestQtr'] == 1]
  print('with latest results: '+str(len(tmp_df1['Symbol'].unique())))
  tmp_df1 = tmp_df1[tmp_df1['StarStock'] == 1]
  print('still star stocks: '+str(len(tmp_df1['Symbol'].unique())))
  tmp_df['Investment'] = tmp_df['AvgCost'] * tmp_df['Shares']
  tmp_df['Current'] = round(tmp_df['Close'] * tmp_df['Shares'],0)
  tmp_df['Previous'] = tmp_df['Prev_Close'] * tmp_df['Shares']
  tmp_df['EstimatedST'] = tmp_df['NTT'] * tmp_df['Shares']
  tmp_df['EstimatedLT'] = tmp_df['LTT'] * tmp_df['Shares']
  tmp_df['Current P/L'] = round((tmp_df['Current'] - tmp_df['Investment']),0)
  tmp_df['Today P/L%'] = round((tmp_df['Current'] - tmp_df['Previous'])*100/tmp_df['Previous'],2)
  tmp_df['Current P/L%'] = round((tmp_df['Current'] - tmp_df['Investment'])*100/tmp_df['Investment'],2)
  tmp_df['EstimatedST P/L%'] = round((tmp_df['EstimatedST'] - tmp_df['Investment'])*100/tmp_df['Investment'],2)
  tmp_df['EstimatedLT P/L%'] = round((tmp_df['EstimatedLT'] - tmp_df['Investment'])*100/tmp_df['Investment'],2)
  tmp_df['NTT%'] = round((tmp_df['NTT'] - tmp_df['Close'])*100/tmp_df['Close'],2)
  tmp_df['LTT%'] = round((tmp_df['LTT'] - tmp_df['Close'])*100/tmp_df['Close'],2)
  tmp_df['Gained%'] = round((tmp_df['Close'] - tmp_df['BOL'])*100/tmp_df['BOL'],2)
  investment = round(sum(tmp_df['AvgCost']*tmp_df['Shares']),0)
  current = round(sum(tmp_df['Close']*tmp_df['Shares']),0)
  tmp_df['InitAlloc%'] = round(tmp_df['Investment']*100/investment,2)
  tmp_df['CurrAlloc%'] = round(tmp_df['Current']*100/current,2)
  tmp_df['FTT'] = tmp_df['LTT']
  tmp_df.loc[tmp_df['Strategy'] == 'NTT', 'FTT'] = tmp_df['NTT']
  tmp_df['FTT%'] = tmp_df['LTT%']
  tmp_df.loc[tmp_df['Strategy'] == 'NTT', 'FTT%'] = tmp_df['NTT%']
  tmp_df['FTT Amt'] = round(tmp_df['FTT%'] * tmp_df['Current']/100,0)
  tmp_df['OTT%'] = round((tmp_df['FTT'] - tmp_df['AvgCost'])*100/tmp_df['AvgCost'],2)
  tmp_df['RRR Ind'] = round(tmp_df['Current P/L']/tmp_df['FTT Amt'],2)
  tmp_df['Risk Ind'] = round(tmp_df['Current P/L%']*tmp_df['CurrAlloc%'],0)

  return tmp_df

# function to print portfolio features
def print_portfolio_stats(df_portfolio_features, myinvmt_df):
  from pyxirr import xirr

  total_booked_amt, reserve_amt, cy_booked_amt, py_booked_amt = get_amt()

  dates = myinvmt_df['Date'].values
  dates = np.append(dates, datetime.date.today().strftime('%d-%b-%y'))
  investment = myinvmt_df['Investment'].values
  dates= pd.to_datetime(dates)

  current = round(sum(df_portfolio_features['Close']*df_portfolio_features['Shares']),0) + reserve_amt
  investment_xirr = np.append(investment, current)
  cagr = round(xirr(pd.DataFrame({"dates": dates, "amounts": investment_xirr}))*100,2)

  investment = -sum(investment)
  invested = round(sum(df_portfolio_features['AvgCost']*df_portfolio_features['Shares']),0) + reserve_amt
  previous = round(sum(df_portfolio_features['Prev_Close']*df_portfolio_features['Shares']),0) + reserve_amt
  cy_invested = investment + py_booked_amt

  today_pnl_amount = current-previous
  today_pnl_percentage = round((current-previous)*100/previous,2)

  curr_pnl_amount = current-invested
  curr_pnl_percentage = round((curr_pnl_amount)*100/(cy_invested),2)

  cy_pnl_amount = cy_booked_amt + curr_pnl_amount
  cy_pnl_percentage = round((cy_pnl_amount)*100/cy_invested,2)

  overall_pnl_amount = total_booked_amt + curr_pnl_amount
  overall_pnl_percentage = round((overall_pnl_amount)*100/investment,2)

  estimate_st = round(sum(df_portfolio_features['FTT']*df_portfolio_features['Shares']),0)  + reserve_amt
  est_st_pnl_amount = estimate_st-current
  est_st_pnl_percentage = round((est_st_pnl_amount)*100/current,2)

  estimate_lt = round(sum(df_portfolio_features['LTT']*df_portfolio_features['Shares']),0)  + reserve_amt
  est_lt_pnl_amount = estimate_lt-current
  est_lt_pnl_percentage = round((est_lt_pnl_amount)*100/current,2)

  total_profit = round(sum(df_portfolio_features[df_portfolio_features['Current P/L%'] > 0]['Current']) - sum(df_portfolio_features[df_portfolio_features['Current P/L%'] > 0]['Investment']),0)
  total_loss = round(sum(df_portfolio_features[df_portfolio_features['Current P/L%'] < 0]['Current']) - sum(df_portfolio_features[df_portfolio_features['Current P/L%'] < 0]['Investment']),0)

  cy_booked_percentage = round((cy_booked_amt)*100/current,2)
  py_booked_percentage = round((py_booked_amt)*100/investment,2)
  total_booked_percentage = round((total_booked_amt)*100/investment,2)

  print('-------------------')
  print('Initial Investment: ', format_amt(investment))
  print('CY Investment: ', format_amt(cy_invested))
  print('Reserve: ', format_amt(reserve_amt))
  print('Current: ',  format_amt(current))
  print('-------------------')
  print('Today PnL: '+ '{} ({}%)'.format(format_amt(today_pnl_amount), today_pnl_percentage))
  print('Current PnL: '+ '{} ({}%)'.format(format_amt(curr_pnl_amount), curr_pnl_percentage))
  print('CY Booked + Current PnL: '+ '{} ({}%)'.format(format_amt(cy_pnl_amount), cy_pnl_percentage))
  print('-------------------')
  print('Total profit: ', format_amt(total_profit))
  print('Total loss: ', format_amt(total_loss))
  print('-------------------')
  print('Total Booked + Current PnL: '+ '{} ({}%)'.format(format_amt(overall_pnl_amount), overall_pnl_percentage))
  print('Total Booked PnL: '+ '{} ({}%)'.format(format_amt(total_booked_amt), total_booked_percentage))
  print('Curr Year Booked PnL: '+ '{} ({}%)'.format(format_amt(cy_booked_amt), cy_booked_percentage))
  print('Prev Year Booked PnL: '+ '{} ({}%)'.format(format_amt(py_booked_amt), py_booked_percentage))
  print('===================')
  print('Est FTT: ',  format_amt(estimate_st))
  print('Est FTT PnL: '+ '{} ({}%)'.format(format_amt(est_st_pnl_amount), est_st_pnl_percentage))

  print('===================')
  print('Deployed: ', format_amt(investment))

  print('Current: ', format_amt(current))

  print('CAGR/XIRR %: '+'{}%'.format(cagr))

In [8]:
# get start and end date
start_date, end_date = get_start_end_date()

# get portfolio and prospects data
mypfs_df = get_mypfs_df()
mypps_df = get_mypps_df()
myinvmt_df = get_myinvmt_df()

# merge above datasets
mypf_df = pd.merge(mypfs_df, mypps_df, on="Symbol")

# seggregate dm and sv portfolio
dm_pf = mypf_df[mypf_df['InPortfolio'] == 'DM']
sv_pf = mypf_df[mypf_df['InPortfolio'] == 'SV']

# build portfolio stock dataframe
dm_stocks = get_stock_ids(dm_pf)
sv_stocks = get_stock_ids(sv_pf)
df_stocks = pd.concat([dm_pf,sv_pf], ignore_index = True)

# arrange common and diff stock features
common_cols = ['Symbol', 'Target', 'Criteria', 'Strategy', 'CumlRnk', 'LatestQtr', 'StarStock', 'Conviction', 'Category', 'InFolio', 'XIRR', 'MBQ']
diff_cols = ['Symbol', 'AvgCost', 'Shares']
df_stocks = arrange_features(df_stocks, common_cols, diff_cols)

# get common features
stock_ids = df_stocks['Symbol'].values
df_common_features = get_common_features(stock_ids, df_stocks)

df_common_features.reset_index(drop=True, inplace=True)
df_common_features.drop(['Date'], axis=1, inplace=True)
# get and print portfolio features
df_portfolio_features = get_portfolio_features(df_common_features)

print_portfolio_stats(df_portfolio_features, myinvmt_df)

df = df_portfolio_features
#plot_pie_chart(df, 'CapType', 'Current')
list_ox40n = list(df[df['MBQ'].str.contains('OX40N', na=False)]['Symbol'].values)

Run date time (IST): 2026-03-06 10:46:00
-------------------
qualified stocks: 86
with latest results: 26
still star stocks: 15
-------------------
Initial Investment:  1.33 C
CY Investment:  1.60 C
Reserve:  2.44 L
Current:  1.36 C
-------------------
Today PnL: 20.09 K (0.15%)
Current PnL: -38.72 L (-24.2%)
CY Booked + Current PnL: -23.04 L (-14.4%)
-------------------
Total profit:  1.05 L
Total loss:  -39.77 L
-------------------
Total Booked + Current PnL: 3.94 L (2.96%)
Total Booked PnL: 42.66 L (32.07%)
Curr Year Booked PnL: 15.68 L (11.55%)
Prev Year Booked PnL: 26.98 L (20.29%)
===================
Est FTT:  2.41 C
Est FTT PnL: 1.05 C (77.61%)
===================
Deployed:  1.33 C
Current:  1.36 C
CAGR/XIRR %: 1.02%

In [9]:
# top 5 near their targets
cols = ['Symbol', 'Today P/L%', 'Current P/L%', 'FTT%', 'OTT%', 'FTT Amt', 'Current P/L', 'Current', 'FTT', 'Dev%_PE', 'RSI_14','Conviction', 'Spread%',  'CumlRnk', 'RRR Ind', 'CurrAlloc%', 'Gained%', 'Criteria', 'Strategy', 'Category']
df_tmp = df_portfolio_features[~df_portfolio_features['Symbol'].isin(['ENRIN','BLUSPRING','DIGITIDE'])]
df_tmp = df_tmp.sort_values(by = 'FTT Amt', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
19,COALINDIA,-1.32,9.05,7.91,17.67,12978.0,13616.0,164076.0,478.51,31.99,60.0,L-LC,11.20,185.0,1.05,1.23,27.42,XY25,ATH,MINING
50,MASFIN,-0.02,-7.23,31.04,21.57,28215.0,-7080.0,90900.0,397.04,-20.05,36.0,H-SC,6.21,167.0,-0.25,0.68,26.84,XR,ATH,FINANCE
77,TTKPRESTIG,-1.14,-38.04,61.54,0.09,38426.0,-38336.0,62441.0,770.00,44.93,20.0,M-SC,13.43,250.0,-1.00,0.47,0.00,OX40N,NTT,DURABLES
51,MEDANTA,0.21,-6.98,33.39,24.08,39428.0,-8866.0,118084.0,1486.00,-7.58,45.0,X-SC,8.17,87.0,-0.22,0.89,8.16,XY24,NTT,HEALTHCARE
37,ICICIGI,-0.43,-1.09,20.66,19.34,40891.0,-2186.0,197923.0,2252.93,-16.89,44.0,X-MC,1.48,66.0,-0.05,1.49,12.88,X40,ATH,INSURANCE

In [10]:
# top 5 today
df_tmp = df_portfolio_features.sort_values(by = 'Today P/L%', ascending=False)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
74,TITAGARH,4.65,-35.17,124.80,45.74,195937.0,-85176.0,157001.0,1548.00,-13.63,37.0,H-SC,13.88,175.0,-0.43,1.18,7.27,XY24,NTT,ENGINEERING
47,JSWINFRA,4.15,-7.30,25.60,16.43,52630.0,-16188.0,205586.0,342.00,-20.54,60.0,X-MC,11.05,61.0,-0.31,1.54,10.38,X40N,NTT,REALTY
27,FINCABLES,2.74,19.46,74.05,107.91,130601.0,28725.0,176369.0,1641.55,7.56,69.0,M-SC,6.44,220.0,0.22,1.32,32.69,OX40N,ATH,CABLES
56,RAJOOENG,2.26,-40.36,134.09,39.61,81969.0,-41370.0,61130.0,143.10,-59.68,43.0,H-SC,29.37,136.0,-0.50,0.46,4.51,AR,ATH,MISC
59,RELIANCE,2.17,-8.87,37.50,25.30,68673.0,-17835.0,183128.0,1952.00,-11.19,50.0,X-LC,2.03,21.0,-0.26,1.37,22.27,XY25,BTT,REFINERIES

In [11]:
# bottom 5 today
df_tmp = df_portfolio_features.sort_values(by = 'Today P/L%', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
55,RAJESHEXPO,-5.00,-77.04,335.81,0.07,105773.0,-105679.0,31498.0,518.00,1054.04,19.0,L-SC,13.73,268.0,-1.00,0.24,0.00,OX40N,NTT,JEWELLERY
64,SHALBY,-1.76,-43.51,121.44,25.10,124276.0,-78808.0,102335.0,327.00,652.79,34.0,M-SC,21.05,236.0,-0.63,0.77,0.54,XY24,NTT,HEALTHCARE
5,ANGELONE,-1.40,-9.21,36.78,24.18,101848.0,-28088.0,276912.0,303.00,-86.88,31.0,X-SC,2.76,97.0,-0.28,2.08,15.97,X40N,NTT,FINANCE
53,PGHH,-1.33,-17.80,60.59,32.01,106348.0,-38000.0,175520.0,17616.87,-44.44,18.0,X-MC,10.18,57.0,-0.36,1.32,0.00,X40,ATH,FMCG
75,TMPV,-1.32,-22.12,71.21,33.33,180678.0,-72074.0,253726.0,600.00,-83.62,38.0,X-LC,3.01,4.0,-0.40,1.90,3.73,XY24,NTT,AUTO

In [12]:
# top 5 to exit based on CumlRnk
df_tmp = df_portfolio_features[~df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])]
df_tmp = df_tmp[(df_tmp['Current P/L%'] > -1) & (df_tmp['Current P/L%'] < 1)].sort_values(by = 'CumlRnk', ascending=False)
df_tmp[cols].head()

Empty DataFrame
Columns: [Symbol, Today P/L%, Current P/L%, FTT%, OTT%, FTT Amt, Current P/L, Current, FTT, Dev%_PE, RSI_14, Conviction, Spread%, CumlRnk, RRR Ind, CurrAlloc%, Gained%, Criteria, Strategy, Category]
Index: []

In [13]:
# OX40N stocks to exit
df_tmp = df_portfolio_features[(df_portfolio_features['Symbol'].isin(list_ox40n))].sort_values(by = 'Current P/L%', ascending=False)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
27,FINCABLES,2.74,19.46,74.05,107.91,130601.0,28725.0,176369.0,1641.55,7.56,69.0,M-SC,6.44,220.0,0.22,1.32,32.69,OX40N,ATH,CABLES
66,SIS,2.08,-30.79,75.21,21.26,57794.0,-34188.0,76844.0,528.00,1804.15,41.0,H-SC,7.50,168.0,-0.59,0.58,5.94,OX40N,NTT,MISC
48,KANSAINER,-0.69,-35.91,77.05,13.47,133170.0,-96831.0,172836.0,340.00,-44.98,28.0,H-SC,14.92,162.0,-0.73,1.30,0.00,XY24,NTT,PAINTS
72,TATAELXSI,-0.35,-36.81,108.94,32.03,90755.0,-48528.0,83307.0,9161.00,-21.03,28.0,H-SC,14.44,158.0,-0.53,0.63,0.62,OX40N,NTT,IT
41,INDIGOPNTS,-1.24,-36.84,58.36,0.02,64341.0,-64311.0,110248.0,1408.00,67.97,20.0,M-SC,14.11,222.0,-1.00,0.83,0.00,OX40N,NTT,PAINTS

In [14]:
# top 5 to book for rotation
df_tmp = df_portfolio_features[(df_portfolio_features['Current P/L%'] > 20) ].sort_values(by = 'CumlRnk', ascending=False)
df_tmp[cols].head()

Empty DataFrame
Columns: [Symbol, Today P/L%, Current P/L%, FTT%, OTT%, FTT Amt, Current P/L, Current, FTT, Dev%_PE, RSI_14, Conviction, Spread%, CumlRnk, RRR Ind, CurrAlloc%, Gained%, Criteria, Strategy, Category]
Index: []

In [15]:
# top 5 to monitor for exit
df_tmp = df_portfolio_features[~df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])]
df_tmp = df_tmp[(df_tmp['Current P/L%'] > 0) ].sort_values(by = 'Dev%_PE', ascending=False)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
19,COALINDIA,-1.32,9.05,7.91,17.67,12978.0,13616.0,164076.0,478.51,31.99,60.0,L-LC,11.20,185.0,1.05,1.23,27.42,XY25,ATH,MINING
27,FINCABLES,2.74,19.46,74.05,107.91,130601.0,28725.0,176369.0,1641.55,7.56,69.0,M-SC,6.44,220.0,0.22,1.32,32.69,OX40N,ATH,CABLES
1,ABB,1.58,10.50,31.74,45.57,91754.0,27461.0,289080.0,7934.00,-28.94,60.0,H-MC,9.19,125.0,0.30,2.17,28.37,AR,NTT,ELECTRICAL

In [16]:
# top 5 to book for rotation from weak conviction
df_tmp = df_portfolio_features[~df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])]
df_tmp = df_tmp[~df_tmp['Criteria'].isin(['XY25','XY24','X40', 'X40N'])].sort_values(by = 'RRR Ind', ascending=False)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
1,ABB,1.58,10.50,31.74,45.57,91754.0,27461.0,289080.0,7934.00,-28.94,60.0,H-MC,9.19,125.0,0.30,2.17,28.37,AR,NTT,ELECTRICAL
27,FINCABLES,2.74,19.46,74.05,107.91,130601.0,28725.0,176369.0,1641.55,7.56,69.0,M-SC,6.44,220.0,0.22,1.32,32.69,OX40N,ATH,CABLES
40,INDIAMART,0.33,-10.48,130.91,106.72,144544.0,-12921.0,110415.0,4810.62,-59.57,34.0,H-SC,8.84,140.0,-0.09,0.83,10.45,AR,ATH,MISC
85,ZYDUSLIFE,-0.45,-3.99,41.26,35.63,83023.0,-8354.0,201220.0,1286.17,-16.22,51.0,H-MC,5.10,120.0,-0.10,1.51,12.02,AR,ATH,PHARMA
84,WIPRO,1.13,-18.83,112.23,72.27,154361.0,-31908.0,137540.0,420.00,-26.90,25.0,M-LC,12.55,98.0,-0.21,1.03,1.20,XR,NTT,IT

In [17]:
# top 5 to accumulate based on lowest RSI_14
df_tmp = df_portfolio_features[df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])].sort_values(by = 'RSI_14', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
8,AWL,0.53,-41.73,169.76,57.19,322609.0,-136089.0,190038.0,485.00,-66.62,16.0,X-SC,21.00,81.0,-0.42,1.43,0.53,XY24,NTT,FMCG
53,PGHH,-1.33,-17.80,60.59,32.01,106348.0,-38000.0,175520.0,17616.87,-44.44,18.0,X-MC,10.18,57.0,-0.36,1.32,0.00,X40,ATH,FMCG
13,BERGEPAINT,-0.87,-23.22,57.77,21.14,100840.0,-52784.0,174555.0,680.00,-24.86,23.0,X-MC,14.84,68.0,-0.52,1.31,0.00,XY24,NTT,PAINTS
3,ACC,-0.04,-36.00,156.47,64.15,238304.0,-85651.0,152300.0,3906.00,-51.63,23.0,X-SC,10.61,85.0,-0.36,1.14,0.00,XY24,BTT,CEMENT
12,BATAINDIA,0.24,-51.94,181.34,35.20,112132.0,-66835.0,61835.0,2096.00,-18.99,25.0,X-SC,23.71,91.0,-0.60,0.46,1.71,X40,NTT,FOOTWEAR

In [18]:
# top 5 to accumulate based on Spread and CumlRnk
df_tmp = df_portfolio_features[df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])]
df_tmp = df_tmp[(df_tmp['CumlRnk'] < 100)].sort_values(by = 'Spread%', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
22,DABUR,-1.11,-5.67,52.33,43.70,122458.0,-14056.0,234012.0,735.00,-14.48,33.0,X-MC,1.08,70.0,-0.11,1.76,8.53,XY24,BTT,FMCG
78,UNITDSPR,0.17,-2.45,23.80,20.77,54363.0,-5728.0,228416.0,1644.00,-13.41,38.0,X-MC,1.36,64.0,-0.11,1.71,4.10,X40N,NTT,BREWERIES
37,ICICIGI,-0.43,-1.09,20.66,19.34,40891.0,-2186.0,197923.0,2252.93,-16.89,44.0,X-MC,1.48,66.0,-0.05,1.49,12.88,X40,ATH,INSURANCE
59,RELIANCE,2.17,-8.87,37.50,25.30,68673.0,-17835.0,183128.0,1952.00,-11.19,50.0,X-LC,2.03,21.0,-0.26,1.37,22.27,XY25,BTT,REFINERIES
5,ANGELONE,-1.40,-9.21,36.78,24.18,101848.0,-28088.0,276912.0,303.00,-86.88,31.0,X-SC,2.76,97.0,-0.28,2.08,15.97,X40N,NTT,FINANCE

In [19]:
# top 5 to accumulate based on lowest Gained%
df_tmp = df_portfolio_features[df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])].sort_values(by = 'Gained%', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
3,ACC,-0.04,-36.00,156.47,64.15,238304.0,-85651.0,152300.0,3906.00,-51.63,23.0,X-SC,10.61,85.0,-0.36,1.14,0.00,XY24,BTT,CEMENT
13,BERGEPAINT,-0.87,-23.22,57.77,21.14,100840.0,-52784.0,174555.0,680.00,-24.86,23.0,X-MC,14.84,68.0,-0.52,1.31,0.00,XY24,NTT,PAINTS
53,PGHH,-1.33,-17.80,60.59,32.01,106348.0,-38000.0,175520.0,17616.87,-44.44,18.0,X-MC,10.18,57.0,-0.36,1.32,0.00,X40,ATH,FMCG
36,HONAUT,0.22,-26.30,94.46,43.32,113390.0,-42832.0,120040.0,58357.33,-35.33,32.0,X-SC,13.11,90.0,-0.38,0.90,0.22,X40N,ATH,ELECTRICAL
58,RELAXO,0.36,-58.03,262.85,52.31,160157.0,-84229.0,60931.0,1176.00,-55.28,26.0,X-SC,16.87,92.0,-0.53,0.46,0.36,X40N,NTT,FOOTWEAR

In [20]:
# top 5 to accumulate based on lowest CurrAlloc%
df_tmp = df_portfolio_features[df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])].sort_values(by = 'CurrAlloc%', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
54,QUESS,-0.61,-35.89,122.79,42.84,51176.0,-23328.0,41678.0,424.00,-58.13,36.0,X-SC,17.15,80.0,-0.46,0.31,1.04,XY24,NTT,MISC
12,BATAINDIA,0.24,-51.94,181.34,35.20,112132.0,-66835.0,61835.0,2096.00,-18.99,25.0,X-SC,23.71,91.0,-0.60,0.46,1.71,X40,NTT,FOOTWEAR
58,RELAXO,0.36,-58.03,262.85,52.31,160157.0,-84229.0,60931.0,1176.00,-55.28,26.0,X-SC,16.87,92.0,-0.53,0.46,0.36,X40N,NTT,FOOTWEAR
51,MEDANTA,0.21,-6.98,33.39,24.08,39428.0,-8866.0,118084.0,1486.00,-7.58,45.0,X-SC,8.17,87.0,-0.22,0.89,8.16,XY24,NTT,HEALTHCARE
36,HONAUT,0.22,-26.30,94.46,43.32,113390.0,-42832.0,120040.0,58357.33,-35.33,32.0,X-SC,13.11,90.0,-0.38,0.90,0.22,X40N,ATH,ELECTRICAL

In [21]:
# top 5 to accumulate based on CumlRnk
df_tmp = df_portfolio_features.sort_values(by = 'CumlRnk', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
45,ITC,-0.48,-18.35,45.81,19.06,127242.0,-62406.0,277760.0,452.00,-55.12,36.0,X-LC,16.70,1.0,-0.49,2.08,0.57,X40,NTT,FMCG
73,TCS,0.83,-25.47,65.81,23.58,212196.0,-110192.0,322437.0,4311.59,-35.43,31.0,X-LC,11.90,2.0,-0.52,2.42,1.03,X40,ATH,IT
43,INFY,1.06,-10.17,49.44,34.24,138963.0,-31813.0,281075.0,1972.00,-29.25,32.0,X-LC,10.56,3.0,-0.23,2.11,3.46,X40,NTT,IT
75,TMPV,-1.32,-22.12,71.21,33.33,180678.0,-72074.0,253726.0,600.00,-83.62,38.0,X-LC,3.01,4.0,-0.40,1.90,3.73,XY24,NTT,AUTO
34,HCLTECH,0.91,-11.33,39.65,23.83,85059.0,-27399.0,214525.0,1908.19,-6.95,30.0,X-LC,8.30,8.0,-0.32,1.61,2.92,X40,ATH,IT

In [22]:
# top 5 for average up
df_tmp = df_portfolio_features[(df_portfolio_features['Dev%_200'] > 5)].sort_values(by = 'CurrAlloc%', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
42,INDUSINDBK,0.13,-30.72,91.81,32.89,49111.0,-23714.0,53492.0,1800.00,-352.10,54.0,L-MC,12.15,258.0,-0.48,0.40,47.31,XR,NTT,BANKS
67,SONACOMS,0.63,-11.05,56.38,39.09,50728.0,-11183.0,89976.0,804.02,-29.52,49.0,M-MC,10.61,193.0,-0.22,0.68,27.29,AR,ATH,AUTO
19,COALINDIA,-1.32,9.05,7.91,17.67,12978.0,13616.0,164076.0,478.51,31.99,60.0,L-LC,11.20,185.0,1.05,1.23,27.42,XY25,ATH,MINING
27,FINCABLES,2.74,19.46,74.05,107.91,130601.0,28725.0,176369.0,1641.55,7.56,69.0,M-SC,6.44,220.0,0.22,1.32,32.69,OX40N,ATH,CABLES
82,VOLTAS,-0.57,15.54,25.67,45.20,56868.0,29793.0,221535.0,1856.00,32.25,49.0,X-MC,10.08,79.0,0.52,1.66,23.39,XY25,NTT,AC

In [23]:
# top 5 RSP
df_tmp = df_portfolio_features.sort_values(by = 'RSP', ascending=False)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
27,FINCABLES,2.74,19.46,74.05,107.91,130601.0,28725.0,176369.0,1641.55,7.56,69.0,M-SC,6.44,220.0,0.22,1.32,32.69,OX40N,ATH,CABLES
11,BANDHANBNK,-0.49,-11.43,117.25,92.42,289280.0,-31838.0,246721.0,400.00,111.93,68.0,H-SC,9.73,174.0,-0.11,1.85,35.91,XY24,NTT,BANKS
26,EASEMYTRIP,-0.13,-58.22,248.75,45.70,183747.0,-102947.0,73868.0,26.40,-23.41,46.0,M-SC,18.06,204.0,-0.56,0.55,21.70,XY24,NTT,TRAVEL
83,WHIRLPOOL,1.01,-26.43,147.28,81.92,124387.0,-30342.0,84456.0,2270.00,-56.86,56.0,M-SC,25.72,210.0,-0.24,0.63,18.64,XR,NTT,DURABLES
47,JSWINFRA,4.15,-7.30,25.60,16.43,52630.0,-16188.0,205586.0,342.00,-20.54,60.0,X-MC,11.05,61.0,-0.31,1.54,10.38,X40N,NTT,REALTY

In [24]:
# Top N allocation
df_tmp = df_portfolio_features.sort_values(by = 'CurrAlloc%', ascending=False)
top_n_values = [10, 25, 50]

sum_df = pd.DataFrame({
    'Top_N': top_n_values,
    'Sum_Alloc%': [df_tmp['CurrAlloc%'].head(n).sum() for n in top_n_values]
})

sum_df

   Top_N  Sum_Alloc%
0     10       20.79
1     25       45.58
2     50       77.72

In [25]:
# market-cap-wise allocation
df_tmp = df_portfolio_features[cols]
df_tmp.groupby(df_tmp['Conviction'].str[-2:])['CurrAlloc%'].sum().sort_values(ascending=False)

Conviction
SC    44.67
MC    30.36
LC    24.97
Name: CurrAlloc%, dtype: float64

In [26]:
# criteria-wise allocation
df_portfolio_features.groupby('Criteria')['CurrAlloc%'].sum().sort_values(ascending=False)

Criteria
XY24     26.55
X40      23.99
X40N     14.74
AR        9.21
XY25      9.00
XR        8.52
OX40N     7.17
SR        0.82
Name: CurrAlloc%, dtype: float64

In [27]:
# conviction-wise allocation
df_portfolio_features.groupby('Conviction')['CurrAlloc%'].sum().sort_values(ascending=False)

Conviction
X-MC    22.80
H-SC    22.35
X-LC    21.48
X-SC    11.10
M-SC    10.58
H-MC     5.06
M-MC     2.10
H-LC     1.23
L-LC     1.23
M-LC     1.03
L-SC     0.64
L-MC     0.40
Name: CurrAlloc%, dtype: float64

In [28]:
# sector-wise stats
df_tmp = df_portfolio_features.groupby('Category')[['CurrAlloc%', 'Current', 'Current P/L', 'FTT Amt']].sum().sort_values(by=['Current', 'Current P/L'], ascending=False)
df_tmp['Current P/L%'] = round(df_tmp['Current P/L'] * 100 / df_tmp['Current'], 2)
df_tmp['FTT%'] = round(df_tmp['FTT Amt'] * 100 / df_tmp['Current'], 2)
cols = ['CurrAlloc%', 'Current P/L%', 'FTT%']
df_tmp[cols].sort_values(by=['CurrAlloc%'], ascending=False)

               CurrAlloc%  Current P/L%    FTT%
Category
FMCG                15.64        -18.40   58.45
FINANCE             12.82        -22.21   70.30
IT                  11.55        -42.48  113.89
MISC                 6.78        -43.68  102.46
ELECTRICAL           6.45         -9.22   49.07
PAINTS               4.94        -40.32   61.17
INSURANCE            4.88         -4.44   40.17
PHARMA               4.23         -4.22   37.02
AUTO                 3.73        -25.70   73.63
BANKS                3.27        -22.56   96.83
AC                   2.23         -7.59   36.76
FOOTWEAR             1.93        -71.17  139.81
TRAVEL               1.93        -73.94  161.03
DURABLES             1.85        -56.58   94.67
BREWERIES            1.71         -2.51   23.80
HEALTHCARE           1.66        -39.78   74.27
REALTY               1.54         -7.87   25.60
APPARELS             1.42        -24.99   62.67
CERAMICS             1.39        -64.96  115.08
REFINERIES           1.37         -9.74   37.50
CABLES               1.32         16.29   74.05
MINING               1.23          8.30    7.91
ENGINEERING          1.18        -54.25  124.80
JEWELLERY            1.16       -107.25  179.25
CEMENT               1.14        -56.24  156.47
CHEMICALS            1.01        -96.56  256.92
ENTERTAINMENT        0.80        -83.25  192.54
TEXTILES             0.44        -55.62  100.00
HOTELS               0.40       -114.43  190.07

In [29]:
# money to be made criteria-wise
df_portfolio_features.groupby('Criteria')['FTT Amt'].agg(['sum', 'count']).sort_values(by='sum', ascending=False)

                sum  count
Criteria
XY24      3589366.0     21
X40       1523637.0     15
XR        1354667.0     12
AR        1345490.0     10
X40N      1155979.0     10
OX40N      838349.0     10
XY25       415642.0      6
SR         310145.0      2

In [30]:
# money to be made conviction-wise
df_portfolio_features.groupby('Conviction')['FTT Amt'].agg(['sum', 'count']).sort_values(by='sum', ascending=False)

                  sum  count
Conviction
H-SC        3814883.0     24
M-SC        1506800.0     14
X-MC        1474158.0     15
X-LC        1408940.0     12
X-SC        1324213.0     10
H-MC         405161.0      3
L-SC         206423.0      2
M-LC         154361.0      1
M-MC         106287.0      2
H-LC          69960.0      1
L-MC          49111.0      1
L-LC          12978.0      1

In [31]:
# money to be made criteria and conviction-wise
df_portfolio_features.groupby(['Conviction', 'Criteria'])['FTT Amt'].agg(['sum', 'count']).sort_values(by='sum', ascending=False)

                           sum  count
Conviction Criteria
H-SC       XY24      1288495.0      6
           AR         973466.0      5
M-SC       XY24       889897.0      6
H-SC       XR         866878.0      7
X-LC       X40        732568.0      6
X-SC       XY24       651517.0      4
X-MC       X40        593727.0      7
X-SC       X40N       475354.0      4
X-MC       X40N       447930.0      4
H-SC       OX40N      375899.0      4
M-SC       OX40N      356677.0      5
H-SC       SR         310145.0      2
X-LC       XY24       305775.0      2
           X40N       232695.0      2
H-MC       XY24       230384.0      1
X-MC       XY24       223298.0      2
           XY25       209203.0      2
X-SC       X40        197342.0      2
M-SC       XR         183667.0      2
H-MC       AR         174777.0      2
M-LC       XR         154361.0      1
X-LC       XY25       137902.0      2
L-SC       OX40N      105773.0      1
           XR         100650.0      1
M-SC       AR          76559.0      1
H-LC       AR          69960.0      1
M-MC       XY25        55559.0      1
           AR          50728.0      1
L-MC       XR          49111.0      1
L-LC       XY25        12978.0      1

In [32]:
# notebook execution time

end_time = time.time()
execution_time = round(end_time - start_time, 0)
print(f"Notebook execution time: {execution_time} seconds")

Notebook execution time: 28.0 seconds