<a href="https://colab.research.google.com/github/ankit-rathi/Quantvesting_v2/blob/main/myStocks_Portfolio_Analysis.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
'''
!pip install pandas==2.2.2 -qq
!pip install pyxirr -qq
!pip install ta -qq
!pip install yfinance==0.2.59 -qq
'''

'\n!pip install pandas==2.2.2 -qq\n!pip install pyxirr -qq\n!pip install ta -qq\n!pip install yfinance==0.2.59 -qq\n'

In [2]:
# import libraries

import numpy as np
import pandas as pd
import datetime
import warnings
warnings.filterwarnings('ignore')
import yfinance as yfin
import ta
import matplotlib.pyplot as plt
import requests

In [3]:
# notebook start time
import time
import datetime
import pytz

start_time = time.time()

# function to print date timestamp
def print_date_time():
  tz_NY = pytz.timezone('Asia/Kolkata')
  datetime_NY = datetime.datetime.now(tz_NY)
  print("Run date time (IST):", datetime_NY.strftime("%Y-%m-%d %H:%M:%S"))

In [4]:
# function to get booked and reserved amount
def get_amt():
  # fetch the JSON data from the URL
  url = "https://raw.githubusercontent.com/ankit-rathi/Tradevesting_v1/main/data/myPortfolioAmts.json"
  response = requests.get(url)
  pf_amts = response.json()  # parse the JSON data

  # extract values from the JSON
  py_booked_amt_dm = pf_amts["py_booked_amt_dm"]
  py_booked_amt_sv = pf_amts["py_booked_amt_sv"]
  cy_booked_amt_dm = pf_amts["cy_booked_amt_dm"]
  cy_booked_amt_sv = pf_amts["cy_booked_amt_sv"]
  reserve_amt_dm = pf_amts["reserve_amt_dm"]
  reserve_amt_sv = pf_amts["reserve_amt_sv"]

  # perform calculations
  py_booked_amt = py_booked_amt_dm + py_booked_amt_sv
  cy_booked_amt = cy_booked_amt_dm + cy_booked_amt_sv
  reserve_amt = reserve_amt_dm + reserve_amt_sv
  total_booked_amt = py_booked_amt + cy_booked_amt

  return total_booked_amt, reserve_amt, cy_booked_amt, py_booked_amt

gen_output = 0

In [5]:
# function to format the amount
def format_amt(number):
    abs_number = abs(number)

    if abs_number >= 1_00_00_000:  # Crores
        formatted_amt = f"{number / 1_00_00_000:.2f} C"
    elif abs_number >= 1_00_000:  # Lakhs
        formatted_amt = f"{number / 1_00_000:.2f} L"
    elif abs_number >= 1_000:  # Thousands
        formatted_amt = f"{number / 1_000:.2f} K"
    else:
        formatted_amt = f"{number:.2f}"

    return formatted_amt

# function to set start and end date
def get_start_end_date():
  start_date = (datetime.date.today() + datetime.timedelta(days=-365)).strftime('%Y-%m-%d')
  end_date = (datetime.date.today() + datetime.timedelta(days=1)).strftime('%Y-%m-%d')
  return start_date, end_date

# function to fetch my portfolio csv
def get_mypfs_df():
  mypfs_df = pd.read_csv('https://raw.githubusercontent.com/ankit-rathi/Tradevesting_v1/main/data/myPortfolioStocks.csv')
  return mypfs_df

# function to fetch my prospects csv
def get_mypps_df():
  mypps_df = pd.read_csv('https://raw.githubusercontent.com/ankit-rathi/Tradevesting_v1/main/data/myProspectsScrips.csv')
  return mypps_df

# function to fetch screener data
def get_myscreen_df():
  myscreen_df = pd.read_csv('https://raw.githubusercontent.com/ankit-rathi/Tradevesting_v1/main/data/myScreenerDB.csv')
  return myscreen_df

# function to fetch momentum data
def get_myinvmt_df():
  myinvmt_df = pd.read_csv('https://raw.githubusercontent.com/ankit-rathi/Tradevesting_v1/main/data/myInvestments.csv')
  return myinvmt_df

# function to get the stock ids
def get_stock_ids(df_pf):
  stock_n100 = df_pf['Symbol'].unique()

  exclude = ['CADILAHC','MMTC', 'MASFIN']

  stock_ids = df_pf[~df_pf['Symbol'].isin(exclude) ]['Symbol'].unique()

  #mypf = mypf[mypf.Forecast.notnull()]
  #stock_ids = mypf['Symbol'].unique()

  #stock_ids.sort()
  return stock_ids

# get features from screener data
def get_screener_features():
  myscreen_df = get_myscreen_df()
  cols = ['Symbol', 'EPS', 'MedPE', 'ROCE%', 'ROE%', 'CapType']
  return myscreen_df[cols]

# get relative strength
def get_relative_strength(stock_list):

    # Dictionary to store stock tickers and their corresponding percentage price change
    stock_changes = {}

    # Loop through each stock and fetch its price data
    for stock in stock_list:
        try:
            # Download the stock data for the given date range
            stock_data = yfin.Ticker(stock + '.NS').history(period='1mo', interval='1d')[map(str.title, ['open', 'close', 'low', 'high', 'volume'])]

            # Calculate the percentage change for the stock
            if len(stock_data) > 0:
                start_price = stock_data['Close'].iloc[0]
                end_price = stock_data['Close'].iloc[-1]
                percent_change = round(((end_price - start_price) / start_price) * 100, 2)
                stock_changes[stock] = percent_change
            else:
                stock_changes[stock] = np.nan  # If no data is available, set to NaN

        except Exception as e:
            print(f"Error fetching data for {stock}: {e}")
            stock_changes[stock] = np.nan

    # Create a DataFrame with stock tickers and their percentage changes
    df = pd.DataFrame(list(stock_changes.items()), columns=['Symbol', 'Percent_Change'])

    # Drop any stocks with missing data (NaN values)
    df = df.dropna()

    # Calculate the percentile rank based on percentage change
    df['RSP'] = round(df['Percent_Change'].rank(pct=True) * 100, 2)
    cols = ['Symbol', 'RSP']
    df = df[cols]
    # Sort by percentile rank (optional)
    df = df.sort_values(by='RSP', ascending=False).reset_index(drop=True)

    return df

In [6]:
# function to get stock technicals
def stock_prec_dev(stock_symbol):
    #stock_symbol = 'ULTRACEMCO.NS'
    short_window = 20
    mid_window = 50
    long_window = 200
    moving_avg = 'SMA'

    start = datetime.datetime(*map(int, start_date.split('-')))
    end = datetime.datetime(*map(int, end_date.split('-')))

    stock_df = yfin.Ticker(stock_symbol + '.NS').history(period='max', interval='1d')[map(str.title, ['open', 'close', 'low', 'high', 'volume'])]

    stock_df['Max'] = round(max(stock_df['Close']),2)
    stock_df = stock_df[(stock_df.index <= end_date) & (stock_df.index >= start_date)]
    stock_df['200_SMA'] = round(stock_df['Close'].rolling(window = 200, min_periods = 1).mean(),0)
    stock_df['Dev%_200'] = round((stock_df['Close'] - stock_df['200_SMA'])*100/stock_df['200_SMA'],2)
    stock_df.dropna(axis = 0, inplace = True) # remove any null rows

    stock_df['20_SMA'] = stock_df['Close'].rolling(window=20).mean()
    stock_df['50_SMA'] = stock_df['Close'].rolling(window=50).mean()
    stock_df['Symbol'] = stock_symbol

    stock_df['Close'] = round(stock_df['Close'],2)
    stock_df['Min'] = round(min(stock_df['Close']),2)
    stock_df['RSI_14'] = ta.momentum.RSIIndicator(close=stock_df['Close'], window=14).rsi()
    stock_df['RSI_14'] = round(stock_df['RSI_14'],0)
    stock_df['Prev_Close'] = stock_df['Close'].shift(1)
    stock_df.drop(['Open', 'Low', 'High', 'Volume'], axis=1, inplace=True)
    stock_df = stock_df.tail(1)

    max_SMA = max(stock_df['20_SMA'].item(), stock_df['50_SMA'].item(), stock_df['200_SMA'].item())
    min_SMA = min(stock_df['20_SMA'].item(), stock_df['50_SMA'].item(), stock_df['200_SMA'].item())
    ABS_Spread = max_SMA - min_SMA
    stock_df['Spread%'] = round((ABS_Spread / stock_df['200_SMA'].item()) * 100,2)

    return stock_df

# function to compute stock attributes
def get_common_features(stock_ids, df_mypf):

  df_prec_dev = pd.DataFrame()
  df_tmp = get_screener_features()
  df_rs = get_relative_strength(stock_ids)

  for stock_id in stock_ids:
      tmp = stock_prec_dev(stock_id)
      tmp = tmp.reset_index()
      df_prec_dev = pd.concat([df_prec_dev, tmp], ignore_index = True)
  df_prec_dev = pd.merge(df_prec_dev, df_mypf, on= 'Symbol')
  df_prec_dev = pd.merge(df_prec_dev, df_tmp, on= 'Symbol', how='left')
  df_prec_dev = pd.merge(df_prec_dev, df_rs, on= 'Symbol', how='left')
  #print(df_prec_dev.columns)
  df_prec_dev['Curr_PE'] = round(df_prec_dev['Close']/df_prec_dev['EPS'],1)
  df_prec_dev['Dev%_PE'] = round((df_prec_dev['Curr_PE'] - df_prec_dev['MedPE'])*100/df_prec_dev['MedPE'],2)
  df_prec_dev['Conviction'] = df_prec_dev['Conviction'] + '-' + df_prec_dev['CapType']
  return df_prec_dev

# function to arrange stock features
def arrange_features(df_stocks, common_cols, diff_cols):
  df_stocks_common = df_stocks[common_cols].drop_duplicates()
  df_stocks_diff = df_stocks[diff_cols]
  df_stocks_diff['Investment'] = df_stocks_diff['AvgCost'] * df_stocks_diff['Shares']
  df_stocks_diff = df_stocks_diff.groupby(['Symbol'])[['Shares', 'Investment']].aggregate(['sum']).reset_index()
  df_stocks_diff.columns = ['Symbol', 'Shares', 'Investment']
  df_stocks_diff['AvgCost'] = round(df_stocks_diff['Investment']/df_stocks_diff['Shares'],2)
  df_stocks = pd.merge(df_stocks_diff, df_stocks_common, on='Symbol')
  return df_stocks

# plot fact distribution across dimension
def plot_pie_chart(df, dimension, fact):
  # grouping the data by category and calculating the sum of fact for each type
  grouped_data = df.groupby(dimension)[fact].sum()

  # sorting the grouped data in descending order
  grouped_data = grouped_data.sort_values(ascending=False)

  # creating a pie chart
  grouped_data.plot.pie(autopct='%1.1f%%', startangle=90, figsize=(6, 6))

  # adding a title and displaying the plot
  plt.title(f'{dimension} {fact} Distribution')
  plt.ylabel('')  # To hide the y-label
  plt.show()

In [7]:
# function to get portfolio features

def get_portfolio_features(df_common_features):

  print_date_time()
  print('-------------------')

  #df_common_features["Target"] = df_common_features["Target"].fillna(df_common_features["Max"])
  df_common_features['NTT'] = np.where(df_common_features['Strategy']== 'NTT', df_common_features["Target"], df_common_features['Max'])
  df_common_features['LTT'] = np.where(df_common_features['Strategy']== 'BTT', df_common_features["Target"], df_common_features['Max'])
  df_common_features['BOL'] = df_common_features['Min']

  tmp_df = df_common_features[df_common_features['Symbol'].isin(mypf_df[mypf_df['InPortfolio'] != 'NA'].Symbol.values)]
  print('qualified stocks: '+str(len(tmp_df['Symbol'].unique())))
  tmp_df1 = tmp_df[tmp_df['LatestQtr'] == 1]
  print('with latest results: '+str(len(tmp_df1['Symbol'].unique())))
  tmp_df1 = tmp_df1[tmp_df1['StarStock'] == 1]
  print('still star stocks: '+str(len(tmp_df1['Symbol'].unique())))
  tmp_df['Investment'] = tmp_df['AvgCost'] * tmp_df['Shares']
  tmp_df['Current'] = round(tmp_df['Close'] * tmp_df['Shares'],0)
  tmp_df['Previous'] = tmp_df['Prev_Close'] * tmp_df['Shares']
  tmp_df['EstimatedST'] = tmp_df['NTT'] * tmp_df['Shares']
  tmp_df['EstimatedLT'] = tmp_df['LTT'] * tmp_df['Shares']
  tmp_df['Current P/L'] = round((tmp_df['Current'] - tmp_df['Investment']),0)
  tmp_df['Today P/L%'] = round((tmp_df['Current'] - tmp_df['Previous'])*100/tmp_df['Previous'],2)
  tmp_df['Current P/L%'] = round((tmp_df['Current'] - tmp_df['Investment'])*100/tmp_df['Investment'],2)
  tmp_df['EstimatedST P/L%'] = round((tmp_df['EstimatedST'] - tmp_df['Investment'])*100/tmp_df['Investment'],2)
  tmp_df['EstimatedLT P/L%'] = round((tmp_df['EstimatedLT'] - tmp_df['Investment'])*100/tmp_df['Investment'],2)
  tmp_df['NTT%'] = round((tmp_df['NTT'] - tmp_df['Close'])*100/tmp_df['Close'],2)
  tmp_df['LTT%'] = round((tmp_df['LTT'] - tmp_df['Close'])*100/tmp_df['Close'],2)
  tmp_df['Gained%'] = round((tmp_df['Close'] - tmp_df['BOL'])*100/tmp_df['BOL'],2)
  investment = round(sum(tmp_df['AvgCost']*tmp_df['Shares']),0)
  current = round(sum(tmp_df['Close']*tmp_df['Shares']),0)
  tmp_df['InitAlloc%'] = round(tmp_df['Investment']*100/investment,2)
  tmp_df['CurrAlloc%'] = round(tmp_df['Current']*100/current,2)
  tmp_df['FTT'] = tmp_df['LTT']
  tmp_df.loc[tmp_df['Strategy'] == 'NTT', 'FTT'] = tmp_df['NTT']
  tmp_df['FTT%'] = tmp_df['LTT%']
  tmp_df.loc[tmp_df['Strategy'] == 'NTT', 'FTT%'] = tmp_df['NTT%']
  tmp_df['FTT Amt'] = round(tmp_df['FTT%'] * tmp_df['Current']/100,0)
  tmp_df['OTT%'] = round((tmp_df['FTT'] - tmp_df['AvgCost'])*100/tmp_df['AvgCost'],2)
  tmp_df['RRR Ind'] = round(tmp_df['Current P/L']/tmp_df['FTT Amt'],2)
  tmp_df['Risk Ind'] = round(tmp_df['Current P/L%']*tmp_df['CurrAlloc%'],0)

  return tmp_df

# function to print portfolio features
def print_portfolio_stats(df_portfolio_features, myinvmt_df):
  from pyxirr import xirr

  total_booked_amt, reserve_amt, cy_booked_amt, py_booked_amt = get_amt()

  dates = myinvmt_df['Date'].values
  dates = np.append(dates, datetime.date.today().strftime('%d-%b-%y'))
  investment = myinvmt_df['Investment'].values
  dates= pd.to_datetime(dates)

  current = round(sum(df_portfolio_features['Close']*df_portfolio_features['Shares']),0) + reserve_amt
  investment_xirr = np.append(investment, current)
  cagr = round(xirr(pd.DataFrame({"dates": dates, "amounts": investment_xirr}))*100,2)

  investment = -sum(investment)
  invested = round(sum(df_portfolio_features['AvgCost']*df_portfolio_features['Shares']),0) + reserve_amt
  previous = round(sum(df_portfolio_features['Prev_Close']*df_portfolio_features['Shares']),0) + reserve_amt
  cy_invested = investment + py_booked_amt

  today_pnl_amount = current-previous
  today_pnl_percentage = round((current-previous)*100/previous,2)

  curr_pnl_amount = current-invested
  curr_pnl_percentage = round((curr_pnl_amount)*100/(cy_invested),2)

  cy_pnl_amount = cy_booked_amt + curr_pnl_amount
  cy_pnl_percentage = round((cy_pnl_amount)*100/cy_invested,2)

  overall_pnl_amount = total_booked_amt + curr_pnl_amount
  overall_pnl_percentage = round((overall_pnl_amount)*100/investment,2)

  estimate_st = round(sum(df_portfolio_features['FTT']*df_portfolio_features['Shares']),0)  + reserve_amt
  est_st_pnl_amount = estimate_st-current
  est_st_pnl_percentage = round((est_st_pnl_amount)*100/current,2)

  estimate_lt = round(sum(df_portfolio_features['LTT']*df_portfolio_features['Shares']),0)  + reserve_amt
  est_lt_pnl_amount = estimate_lt-current
  est_lt_pnl_percentage = round((est_lt_pnl_amount)*100/current,2)

  total_profit = round(sum(df_portfolio_features[df_portfolio_features['Current P/L%'] > 0]['Current']) - sum(df_portfolio_features[df_portfolio_features['Current P/L%'] > 0]['Investment']),0)
  total_loss = round(sum(df_portfolio_features[df_portfolio_features['Current P/L%'] < 0]['Current']) - sum(df_portfolio_features[df_portfolio_features['Current P/L%'] < 0]['Investment']),0)

  cy_booked_percentage = round((cy_booked_amt)*100/current,2)
  py_booked_percentage = round((py_booked_amt)*100/investment,2)
  total_booked_percentage = round((total_booked_amt)*100/investment,2)

  print('-------------------')
  print('Initial Investment: ', format_amt(investment))
  print('CY Investment: ', format_amt(cy_invested))
  print('Reserve: ', format_amt(reserve_amt))
  print('Current: ',  format_amt(current))
  print('-------------------')
  print('Today PnL: '+ '{} ({}%)'.format(format_amt(today_pnl_amount), today_pnl_percentage))
  print('Current PnL: '+ '{} ({}%)'.format(format_amt(curr_pnl_amount), curr_pnl_percentage))
  print('CY Booked + Current PnL: '+ '{} ({}%)'.format(format_amt(cy_pnl_amount), cy_pnl_percentage))
  print('-------------------')
  print('Total profit: ', format_amt(total_profit))
  print('Total loss: ', format_amt(total_loss))
  print('-------------------')
  print('Total Booked + Current PnL: '+ '{} ({}%)'.format(format_amt(overall_pnl_amount), overall_pnl_percentage))
  print('Total Booked PnL: '+ '{} ({}%)'.format(format_amt(total_booked_amt), total_booked_percentage))
  print('Curr Year Booked PnL: '+ '{} ({}%)'.format(format_amt(cy_booked_amt), cy_booked_percentage))
  print('Prev Year Booked PnL: '+ '{} ({}%)'.format(format_amt(py_booked_amt), py_booked_percentage))
  print('===================')
  print('Est FTT: ',  format_amt(estimate_st))
  print('Est FTT PnL: '+ '{} ({}%)'.format(format_amt(est_st_pnl_amount), est_st_pnl_percentage))

  print('===================')
  print('Deployed: ', format_amt(investment))

  print('Current: ', format_amt(current))

  print('CAGR/XIRR %: '+'{}%'.format(cagr))

In [8]:
# get start and end date
start_date, end_date = get_start_end_date()

# get portfolio and prospects data
mypfs_df = get_mypfs_df()
mypps_df = get_mypps_df()
myinvmt_df = get_myinvmt_df()

# merge above datasets
mypf_df = pd.merge(mypfs_df, mypps_df, on="Symbol")

# seggregate dm and sv portfolio
dm_pf = mypf_df[mypf_df['InPortfolio'] == 'DM']
sv_pf = mypf_df[mypf_df['InPortfolio'] == 'SV']

# build portfolio stock dataframe
dm_stocks = get_stock_ids(dm_pf)
sv_stocks = get_stock_ids(sv_pf)
df_stocks = pd.concat([dm_pf,sv_pf], ignore_index = True)

# arrange common and diff stock features
common_cols = ['Symbol', 'Target', 'Criteria', 'Strategy', 'CumlRnk', 'LatestQtr', 'StarStock', 'Conviction', 'Category', 'InFolio', 'XIRR', 'MBQ']
diff_cols = ['Symbol', 'AvgCost', 'Shares']
df_stocks = arrange_features(df_stocks, common_cols, diff_cols)

# get common features
stock_ids = df_stocks['Symbol'].values
df_common_features = get_common_features(stock_ids, df_stocks)

df_common_features.reset_index(drop=True, inplace=True)
df_common_features.drop(['Date'], axis=1, inplace=True)
# get and print portfolio features
df_portfolio_features = get_portfolio_features(df_common_features)

print_portfolio_stats(df_portfolio_features, myinvmt_df)

df = df_portfolio_features
#plot_pie_chart(df, 'CapType', 'Current')
list_ox40n = list(df[df['MBQ'].str.contains('OX40N', na=False)]['Symbol'].values)

Run date time (IST): 2026-03-12 13:55:27
-------------------
qualified stocks: 86
with latest results: 26
still star stocks: 15
-------------------
Initial Investment:  1.36 C
CY Investment:  1.62 C
Reserve:  66.25 K
Current:  1.36 C
-------------------
Today PnL: -24.21 K (-0.18%)
Current PnL: -40.50 L (-24.93%)
CY Booked + Current PnL: -24.82 L (-15.28%)
-------------------
Total profit:  1.20 L
Total loss:  -41.70 L
-------------------
Total Booked + Current PnL: 2.16 L (1.59%)
Total Booked PnL: 42.66 L (31.48%)
Curr Year Booked PnL: 15.68 L (11.49%)
Prev Year Booked PnL: 26.98 L (19.91%)
===================
Est FTT:  2.47 C
Est FTT PnL: 1.11 C (81.26%)
===================
Deployed:  1.36 C
Current:  1.36 C
CAGR/XIRR %: 0.34%

In [9]:
# top 5 near their targets
cols = ['Symbol', 'Today P/L%', 'Current P/L%', 'FTT%', 'OTT%', 'FTT Amt', 'Current P/L', 'Current', 'FTT', 'Dev%_PE', 'RSI_14','Conviction', 'Spread%',  'CumlRnk', 'RRR Ind', 'CurrAlloc%', 'Gained%', 'Criteria', 'Strategy', 'Category']
df_tmp = df_portfolio_features[~df_portfolio_features['Symbol'].isin(['ENRIN','BLUSPRING','DIGITIDE'])]
df_tmp = df_tmp.sort_values(by = 'FTT Amt', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
19,COALINDIA,5.72,16.14,1.31,17.67,2289.0,24290.0,174751.0,478.51,39.17,71.0,L-LC,12.23,185.0,10.61,1.29,35.71,XY25,ATH,MINING
77,TTKPRESTIG,7.86,-24.92,33.32,0.09,25210.0,-25118.0,75659.0,770.00,75.67,60.0,M-SC,15.25,250.0,-1.00,0.56,27.83,OX40N,NTT,DURABLES
50,MASFIN,0.59,-6.55,30.09,21.57,27550.0,-6420.0,91560.0,397.04,-19.60,40.0,H-SC,4.18,167.0,-0.23,0.67,27.02,XR,ATH,FINANCE
37,ICICIGI,-0.75,-0.67,20.14,19.34,40032.0,-1338.0,198771.0,2252.93,-16.40,45.0,X-MC,1.67,66.0,-0.03,1.46,13.37,X40,ATH,INSURANCE
78,UNITDSPR,-1.19,0.32,20.39,20.77,47893.0,739.0,234883.0,1644.00,-11.09,48.0,X-MC,1.41,64.0,0.02,1.73,7.04,X40N,NTT,BREWERIES

In [10]:
# top 5 today
df_tmp = df_portfolio_features.sort_values(by = 'Today P/L%', ascending=False)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
77,TTKPRESTIG,7.86,-24.92,33.32,0.09,25210.0,-25118.0,75659.0,770.00,75.67,60.0,M-SC,15.25,250.0,-1.00,0.56,27.83,OX40N,NTT,DURABLES
19,COALINDIA,5.72,16.14,1.31,17.67,2289.0,24290.0,174751.0,478.51,39.17,71.0,L-LC,12.23,185.0,10.61,1.29,35.71,XY25,ATH,MINING
57,RECLTD,4.20,-6.05,28.51,20.74,54419.0,-12292.0,190878.0,446.00,3.52,50.0,M-MC,5.02,191.0,-0.23,1.41,6.98,XY25,NTT,FINANCE
30,GREENPANEL,2.87,-46.56,167.87,43.14,164226.0,-85249.0,97829.0,537.00,118.99,39.0,M-SC,19.98,225.0,-0.52,0.72,2.87,XY24,NTT,MISC
60,REPCOHOME,2.58,-19.45,135.64,89.82,313046.0,-55713.0,230792.0,880.00,-59.76,44.0,H-SC,3.63,161.0,-0.18,1.70,22.70,XY24,NTT,FINANCE

In [11]:
# bottom 5 today
df_tmp = df_portfolio_features.sort_values(by = 'Today P/L%', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
81,VBL,-4.23,-16.57,62.62,35.67,165000.0,-52348.0,263494.0,671.64,-26.34,30.0,X-LC,5.07,13.0,-0.32,1.94,0.00,X40N,ATH,FMCG
21,COLPAL,-3.79,-24.91,88.44,41.51,174908.0,-65595.0,197770.0,3726.84,-9.21,32.0,X-MC,4.12,62.0,-0.38,1.46,0.00,XY25,ATH,FMCG
69,SURYODAY,-3.54,-26.35,67.05,23.03,88430.0,-47185.0,131886.0,216.00,44.74,49.0,H-SC,7.40,166.0,-0.53,0.97,30.86,XR,NTT,BANKS
55,RAJESHEXPO,-3.51,-78.64,368.57,0.07,107976.0,-107881.0,29296.0,518.00,973.23,22.0,L-SC,21.01,268.0,-1.00,0.22,1.25,OX40N,NTT,JEWELLERY
10,BAJAJHLDNG,-2.85,-11.60,46.17,29.22,77602.0,-22046.0,168079.0,14451.52,-18.46,26.0,X-LC,12.29,28.0,-0.28,1.24,0.00,X40,ATH,FINANCE

In [12]:
# top 5 to exit based on CumlRnk
df_tmp = df_portfolio_features[~df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])]
df_tmp = df_tmp[(df_tmp['Current P/L%'] > -1) & (df_tmp['Current P/L%'] < 1)].sort_values(by = 'CumlRnk', ascending=False)
df_tmp[cols].head()

Empty DataFrame
Columns: [Symbol, Today P/L%, Current P/L%, FTT%, OTT%, FTT Amt, Current P/L, Current, FTT, Dev%_PE, RSI_14, Conviction, Spread%, CumlRnk, RRR Ind, CurrAlloc%, Gained%, Criteria, Strategy, Category]
Index: []

In [13]:
# OX40N stocks to exit
df_tmp = df_portfolio_features[(df_portfolio_features['Symbol'].isin(list_ox40n))].sort_values(by = 'Current P/L%', ascending=False)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
27,FINCABLES,1.38,14.00,82.37,107.91,138644.0,20675.0,168319.0,1641.55,2.49,57.0,M-SC,7.76,220.0,0.15,1.24,26.63,OX40N,ATH,CABLES
77,TTKPRESTIG,7.86,-24.92,33.32,0.09,25210.0,-25118.0,75659.0,770.00,75.67,60.0,M-SC,15.25,250.0,-1.00,0.56,27.83,OX40N,NTT,DURABLES
66,SIS,0.46,-32.74,80.30,21.26,59966.0,-36355.0,74677.0,528.00,1750.26,38.0,H-SC,10.54,168.0,-0.61,0.55,2.95,OX40N,NTT,MISC
48,KANSAINER,1.11,-36.89,79.80,13.47,135812.0,-99477.0,170190.0,340.00,-45.81,31.0,H-SC,16.70,162.0,-0.73,1.25,2.03,XY24,NTT,PAINTS
72,TATAELXSI,0.43,-37.14,110.02,32.03,91180.0,-48959.0,82876.0,9161.00,-21.37,31.0,H-SC,17.24,158.0,-0.54,0.61,1.35,OX40N,NTT,IT

In [14]:
# top 5 to book for rotation
df_tmp = df_portfolio_features[(df_portfolio_features['Current P/L%'] > 20) ].sort_values(by = 'CumlRnk', ascending=False)
df_tmp[cols].head()

Empty DataFrame
Columns: [Symbol, Today P/L%, Current P/L%, FTT%, OTT%, FTT Amt, Current P/L, Current, FTT, Dev%_PE, RSI_14, Conviction, Spread%, CumlRnk, RRR Ind, CurrAlloc%, Gained%, Criteria, Strategy, Category]
Index: []

In [15]:
# top 5 to monitor for exit
df_tmp = df_portfolio_features[~df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])]
df_tmp = df_tmp[(df_tmp['Current P/L%'] > 0) ].sort_values(by = 'Dev%_PE', ascending=False)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
19,COALINDIA,5.72,16.14,1.31,17.67,2289.0,24290.0,174751.0,478.51,39.17,71.0,L-LC,12.23,185.0,10.61,1.29,35.71,XY25,ATH,MINING
27,FINCABLES,1.38,14.00,82.37,107.91,138644.0,20675.0,168319.0,1641.55,2.49,57.0,M-SC,7.76,220.0,0.15,1.24,26.63,OX40N,ATH,CABLES
1,ABB,1.27,16.69,24.75,45.57,75557.0,43661.0,305280.0,7934.00,-25.02,68.0,H-MC,10.53,125.0,0.58,2.25,35.56,AR,NTT,ELECTRICAL

In [16]:
# top 5 to book for rotation from weak conviction
df_tmp = df_portfolio_features[~df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])]
df_tmp = df_tmp[~df_tmp['Criteria'].isin(['XY25','XY24','X40', 'X40N'])].sort_values(by = 'RRR Ind', ascending=False)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
1,ABB,1.27,16.69,24.75,45.57,75557.0,43661.0,305280.0,7934.00,-25.02,68.0,H-MC,10.53,125.0,0.58,2.25,35.56,AR,NTT,ELECTRICAL
27,FINCABLES,1.38,14.00,82.37,107.91,138644.0,20675.0,168319.0,1641.55,2.49,57.0,M-SC,7.76,220.0,0.15,1.24,26.63,OX40N,ATH,CABLES
85,ZYDUSLIFE,-0.01,-2.81,39.55,35.63,80557.0,-5889.0,203685.0,1286.17,-15.32,55.0,H-MC,5.01,120.0,-0.07,1.50,13.39,AR,ATH,PHARMA
40,INDIAMART,-1.38,-9.71,128.96,106.72,143607.0,-11978.0,111358.0,4810.62,-59.18,41.0,H-SC,9.46,140.0,-0.08,0.82,11.40,AR,ATH,MISC
84,WIPRO,0.28,-16.82,107.10,72.27,150953.0,-28502.0,140946.0,420.00,-25.02,36.0,M-LC,15.04,98.0,-0.19,1.04,3.79,XR,NTT,IT

In [17]:
# top 5 to accumulate based on lowest RSI_14
df_tmp = df_portfolio_features[df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])].sort_values(by = 'RSI_14', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
58,RELAXO,0.26,-60.44,285.01,52.31,163667.0,-87735.0,57425.0,1176.00,-57.89,20.0,X-SC,19.51,92.0,-0.54,0.42,0.26,X40N,NTT,FOOTWEAR
3,ACC,-1.12,-35.55,171.23,74.81,295906.0,-95316.0,172812.0,3906.00,-54.32,21.0,X-SC,12.79,85.0,-0.32,1.27,0.00,XY24,BTT,CEMENT
8,AWL,-0.65,-38.62,172.12,67.02,376406.0,-137621.0,218688.0,485.00,-66.89,21.0,X-SC,23.35,81.0,-0.37,1.61,1.50,XY24,NTT,FMCG
73,TCS,-0.56,-28.05,75.91,26.57,253035.0,-129937.0,333336.0,4311.58,-39.04,21.0,X-LC,14.43,2.0,-0.51,2.46,0.00,X40,ATH,IT
53,PGHH,-1.37,-19.89,64.78,32.01,110810.0,-42464.0,171056.0,17616.87,-45.79,24.0,X-MC,11.61,57.0,-0.38,1.26,0.82,X40,ATH,FMCG

In [18]:
# top 5 to accumulate based on Spread and CumlRnk
df_tmp = df_portfolio_features[df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])]
df_tmp = df_tmp[(df_tmp['CumlRnk'] < 100)].sort_values(by = 'Spread%', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
78,UNITDSPR,-1.19,0.32,20.39,20.77,47893.0,739.0,234883.0,1644.00,-11.09,48.0,X-MC,1.41,64.0,0.02,1.73,7.04,X40N,NTT,BREWERIES
22,DABUR,-2.30,-9.87,59.44,43.70,132899.0,-24483.0,223585.0,735.00,-18.18,31.0,X-MC,1.51,70.0,-0.18,1.65,3.70,XY24,BTT,FMCG
37,ICICIGI,-0.75,-0.67,20.14,19.34,40032.0,-1338.0,198771.0,2252.93,-16.40,45.0,X-MC,1.67,66.0,-0.03,1.46,13.37,X40,ATH,INSURANCE
75,TMPV,-2.27,-25.39,83.07,36.58,220533.0,-90363.0,265478.0,600.00,-84.72,33.0,X-LC,1.77,4.0,-0.41,1.96,0.00,XY24,NTT,AUTO
59,RELIANCE,1.10,-9.78,38.88,25.30,70493.0,-19653.0,181310.0,1952.00,-11.96,48.0,X-LC,2.69,21.0,-0.28,1.34,21.05,XY25,BTT,REFINERIES

In [19]:
# top 5 to accumulate based on lowest Gained%
df_tmp = df_portfolio_features[df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])].sort_values(by = 'Gained%', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
3,ACC,-1.12,-35.55,171.23,74.81,295906.0,-95316.0,172812.0,3906.00,-54.32,21.0,X-SC,12.79,85.0,-0.32,1.27,0.0,XY24,BTT,CEMENT
10,BAJAJHLDNG,-2.85,-11.60,46.17,29.22,77602.0,-22046.0,168079.0,14451.52,-18.46,26.0,X-LC,12.29,28.0,-0.28,1.24,0.0,X40,ATH,FINANCE
21,COLPAL,-3.79,-24.91,88.44,41.51,174908.0,-65595.0,197770.0,3726.84,-9.21,32.0,X-MC,4.12,62.0,-0.38,1.46,0.0,XY25,ATH,FMCG
13,BERGEPAINT,-1.83,-22.09,60.85,25.32,122190.0,-56943.0,200806.0,680.00,-26.28,25.0,X-MC,15.67,68.0,-0.47,1.48,0.0,XY24,NTT,PAINTS
43,INFY,-0.46,-13.52,55.23,34.24,149450.0,-42293.0,270595.0,1972.00,-31.79,25.0,X-LC,12.73,3.0,-0.28,1.99,0.0,X40,NTT,IT

In [20]:
# top 5 to accumulate based on lowest CurrAlloc%
df_tmp = df_portfolio_features[df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])].sort_values(by = 'CurrAlloc%', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
58,RELAXO,0.26,-60.44,285.01,52.31,163667.0,-87735.0,57425.0,1176.00,-57.89,20.0,X-SC,19.51,92.0,-0.54,0.42,0.26,X40N,NTT,FOOTWEAR
12,BATAINDIA,1.34,-53.02,187.77,35.20,113513.0,-68217.0,60453.0,2096.00,-20.72,26.0,X-SC,26.17,91.0,-0.60,0.45,1.60,X40,NTT,FOOTWEAR
54,QUESS,-0.25,-20.99,120.09,73.90,101333.0,-22412.0,84381.0,424.00,-57.58,43.0,X-SC,18.30,80.0,-0.22,0.62,4.09,XY24,NTT,MISC
36,HONAUT,-0.18,-20.67,90.74,51.31,138810.0,-39863.0,152975.0,58357.33,-34.10,42.0,X-SC,13.78,90.0,-0.29,1.13,3.01,X40N,ATH,ELECTRICAL
2,ABBOTINDIA,-1.54,-10.16,31.42,18.07,50486.0,-18175.0,160680.0,35195.00,-23.63,47.0,X-MC,11.09,58.0,-0.36,1.18,1.86,X40,ATH,PHARMA

In [21]:
# top 5 to accumulate based on CumlRnk
df_tmp = df_portfolio_features.sort_values(by = 'CumlRnk', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
45,ITC,-0.61,-19.11,47.18,19.06,129821.0,-65004.0,275162.0,452.00,-55.52,36.0,X-LC,17.02,1.0,-0.50,2.03,0.36,X40,NTT,FMCG
73,TCS,-0.56,-28.05,75.91,26.57,253035.0,-129937.0,333336.0,4311.58,-39.04,21.0,X-LC,14.43,2.0,-0.51,2.46,0.00,X40,ATH,IT
43,INFY,-0.46,-13.52,55.23,34.24,149450.0,-42293.0,270595.0,1972.00,-31.79,25.0,X-LC,12.73,3.0,-0.28,1.99,0.00,X40,NTT,IT
75,TMPV,-2.27,-25.39,83.07,36.58,220533.0,-90363.0,265478.0,600.00,-84.72,33.0,X-LC,1.77,4.0,-0.41,1.96,0.00,XY24,NTT,AUTO
34,HCLTECH,0.44,-11.98,40.69,23.83,86645.0,-28985.0,212939.0,1908.19,-7.36,29.0,X-LC,9.80,8.0,-0.33,1.57,2.16,X40,ATH,IT

In [22]:
# top 5 for average up
df_tmp = df_portfolio_features[(df_portfolio_features['Dev%_200'] > 5)].sort_values(by = 'CurrAlloc%', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
42,INDUSINDBK,-2.40,-35.24,105.21,32.89,52603.0,-27208.0,49998.0,1800.00,-335.29,38.0,L-MC,11.28,258.0,-0.52,0.37,37.69,XR,NTT,BANKS
67,SONACOMS,-0.78,-11.37,56.94,39.09,51048.0,-11507.0,89652.0,804.02,-29.79,49.0,M-MC,9.86,193.0,-0.23,0.66,26.83,AR,ATH,AUTO
65,SIEMENS,1.99,-10.34,39.98,25.51,66711.0,-19235.0,166860.0,4671.50,40.24,58.0,H-LC,3.81,51.0,-0.29,1.23,22.88,AR,ATH,ELECTRICAL
27,FINCABLES,1.38,14.00,82.37,107.91,138644.0,20675.0,168319.0,1641.55,2.49,57.0,M-SC,7.76,220.0,0.15,1.24,26.63,OX40N,ATH,CABLES
19,COALINDIA,5.72,16.14,1.31,17.67,2289.0,24290.0,174751.0,478.51,39.17,71.0,L-LC,12.23,185.0,10.61,1.29,35.71,XY25,ATH,MINING

In [23]:
# top 5 RSP
df_tmp = df_portfolio_features.sort_values(by = 'RSP', ascending=False)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
19,COALINDIA,5.72,16.14,1.31,17.67,2289.0,24290.0,174751.0,478.51,39.17,71.0,L-LC,12.23,185.0,10.61,1.29,35.71,XY25,ATH,MINING
1,ABB,1.27,16.69,24.75,45.57,75557.0,43661.0,305280.0,7934.00,-25.02,68.0,H-MC,10.53,125.0,0.58,2.25,35.56,AR,NTT,ELECTRICAL
27,FINCABLES,1.38,14.00,82.37,107.91,138644.0,20675.0,168319.0,1641.55,2.49,57.0,M-SC,7.76,220.0,0.15,1.24,26.63,OX40N,ATH,CABLES
26,EASEMYTRIP,-0.54,-59.66,261.15,45.70,186281.0,-105484.0,71331.0,26.40,-25.84,43.0,M-SC,18.18,204.0,-0.57,0.53,17.52,XY24,NTT,TRAVEL
31,HAPPSTMNDS,-0.51,-48.87,261.50,84.85,171377.0,-62629.0,65536.0,1480.71,-39.19,62.0,H-SC,28.35,152.0,-0.37,0.48,21.36,AR,ATH,IT

In [24]:
# Top N allocation
df_tmp = df_portfolio_features.sort_values(by = 'CurrAlloc%', ascending=False)
top_n_values = [10, 25, 50]

sum_df = pd.DataFrame({
    'Top_N': top_n_values,
    'Sum_Alloc%': [df_tmp['CurrAlloc%'].head(n).sum() for n in top_n_values]
})

sum_df

   Top_N  Sum_Alloc%
0     10       20.35
1     25       45.12
2     50       77.71

In [25]:
# market-cap-wise allocation
df_tmp = df_portfolio_features[cols]
df_tmp.groupby(df_tmp['Conviction'].str[-2:])['CurrAlloc%'].sum().sort_values(ascending=False)

Conviction
SC    44.82
MC    30.41
LC    24.83
Name: CurrAlloc%, dtype: float64

In [26]:
# criteria-wise allocation
df_portfolio_features.groupby('Criteria')['CurrAlloc%'].sum().sort_values(ascending=False)

Criteria
XY24     27.33
X40      23.69
X40N     15.03
AR        9.24
XY25      8.68
XR        8.29
OX40N     7.02
SR        0.78
Name: CurrAlloc%, dtype: float64

In [27]:
# conviction-wise allocation
df_portfolio_features.groupby('Conviction')['CurrAlloc%'].sum().sort_values(ascending=False)

Conviction
X-MC    22.92
H-SC    21.79
X-LC    21.27
X-SC    12.09
M-SC    10.34
H-MC     5.05
M-MC     2.07
L-LC     1.29
H-LC     1.23
M-LC     1.04
L-SC     0.60
L-MC     0.37
Name: CurrAlloc%, dtype: float64

In [28]:
# sector-wise stats
df_tmp = df_portfolio_features.groupby('Category')[['CurrAlloc%', 'Current', 'Current P/L', 'FTT Amt']].sum().sort_values(by=['Current', 'Current P/L'], ascending=False)
df_tmp['Current P/L%'] = round(df_tmp['Current P/L'] * 100 / df_tmp['Current'], 2)
df_tmp['FTT%'] = round(df_tmp['FTT Amt'] * 100 / df_tmp['Current'], 2)
cols = ['CurrAlloc%', 'Current P/L%', 'FTT%']
df_tmp[cols].sort_values(by=['CurrAlloc%'], ascending=False)

               CurrAlloc%  Current P/L%    FTT%
Category
FMCG                15.02        -22.55   66.05
FINANCE             12.88        -23.00   73.12
IT                  11.70        -41.83  114.00
MISC                 7.02        -40.53  101.58
ELECTRICAL           6.72         -6.29   46.98
PAINTS               5.16        -40.75   65.20
INSURANCE            4.74         -5.40   41.48
PHARMA               4.16         -3.94   36.65
AUTO                 3.69        -30.76   82.64
BANKS                3.12        -26.37  102.94
AC                   2.17         -8.48   37.90
HEALTHCARE           1.98        -32.91   67.59
DURABLES             1.94        -46.90   82.64
FOOTWEAR             1.88        -73.56  143.15
TRAVEL               1.83        -80.80  171.32
BREWERIES            1.73          0.31   20.39
APPARELS             1.59        -24.34   66.75
REALTY               1.45        -12.31   30.76
CERAMICS             1.36        -66.62  117.24
REFINERIES           1.34        -10.84   38.88
MINING               1.29         13.90    1.31
CEMENT               1.27        -55.16  171.23
CABLES               1.24         12.28   82.37
JEWELLERY            1.12       -111.13  184.48
ENGINEERING          1.11        -60.72  134.23
CHEMICALS            0.97       -102.06  266.91
ENTERTAINMENT        0.77        -85.50  196.13
TEXTILES             0.43        -59.61  105.13
HOTELS               0.38       -123.00  201.66

In [29]:
# money to be made criteria-wise
df_portfolio_features.groupby('Criteria')['FTT Amt'].agg(['sum', 'count']).sort_values(by='sum', ascending=False)

                sum  count
Criteria
XY24      3888799.0     21
X40       1657964.0     15
XR        1367606.0     12
AR        1316583.0     10
X40N      1259221.0     10
OX40N      841367.0     10
XY25       440609.0      6
SR         313838.0      2

In [30]:
# money to be made conviction-wise
df_portfolio_features.groupby('Conviction')['FTT Amt'].agg(['sum', 'count']).sort_values(by='sum', ascending=False)

                  sum  count
Conviction
H-SC        3835957.0     24
X-MC        1621280.0     15
X-LC        1588627.0     12
X-SC        1541439.0     10
M-SC        1516293.0     14
H-MC         393711.0      3
L-SC         210657.0      2
M-LC         150953.0      1
M-MC         105467.0      2
H-LC          66711.0      1
L-MC          52603.0      1
L-LC           2289.0      1

In [31]:
# money to be made criteria and conviction-wise
df_portfolio_features.groupby(['Conviction', 'Criteria'])['FTT Amt'].agg(['sum', 'count']).sort_values(by='sum', ascending=False)

                           sum  count
Conviction Criteria
H-SC       XY24      1303684.0      6
           AR         966136.0      5
M-SC       XY24       897258.0      6
H-SC       XR         871898.0      7
X-SC       XY24       832076.0      4
X-LC       X40        822963.0      6
X-MC       X40        632044.0      7
X-SC       X40N       506406.0      4
X-MC       X40N       501090.0      4
H-SC       OX40N      380401.0      4
X-LC       XY24       363095.0      2
M-SC       OX40N      352990.0      5
H-SC       SR         313838.0      2
X-MC       XY24       255089.0      2
X-LC       X40N       251725.0      2
H-MC       XY24       237597.0      1
X-MC       XY25       233057.0      2
X-SC       X40        202957.0      2
M-SC       XR         189471.0      2
H-MC       AR         156114.0      2
M-LC       XR         150953.0      1
X-LC       XY25       150844.0      2
L-SC       OX40N      107976.0      1
           XR         102681.0      1
M-SC       AR          76574.0      1
H-LC       AR          66711.0      1
M-MC       XY25        54419.0      1
L-MC       XR          52603.0      1
M-MC       AR          51048.0      1
L-LC       XY25         2289.0      1

In [32]:
# notebook execution time

end_time = time.time()
execution_time = round(end_time - start_time, 0)
print(f"Notebook execution time: {execution_time} seconds")

Notebook execution time: 33.0 seconds