<a href="https://colab.research.google.com/github/ankit-rathi/Quantvesting_v2/blob/main/myStocks_Portfolio_Analysis.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
'''
!pip install pandas==2.2.2 -qq
!pip install pyxirr -qq
!pip install ta -qq
!pip install yfinance==0.2.59 -qq
'''

'\n!pip install pandas==2.2.2 -qq\n!pip install pyxirr -qq\n!pip install ta -qq\n!pip install yfinance==0.2.59 -qq\n'

In [2]:
# import libraries

import numpy as np
import pandas as pd
import datetime
import warnings
warnings.filterwarnings('ignore')
import yfinance as yfin
import ta
import matplotlib.pyplot as plt
import requests

In [3]:
# notebook start time
import time
import datetime
import pytz

start_time = time.time()

# function to print date timestamp
def print_date_time():
  tz_NY = pytz.timezone('Asia/Kolkata')
  datetime_NY = datetime.datetime.now(tz_NY)
  print("Run date time (IST):", datetime_NY.strftime("%Y-%m-%d %H:%M:%S"))

In [4]:
# function to get booked and reserved amount
def get_amt():
  # fetch the JSON data from the URL
  url = "https://raw.githubusercontent.com/ankit-rathi/Tradevesting_v1/main/data/myPortfolioAmts.json"
  response = requests.get(url)
  pf_amts = response.json()  # parse the JSON data

  # extract values from the JSON
  py_booked_amt_dm = pf_amts["py_booked_amt_dm"]
  py_booked_amt_sv = pf_amts["py_booked_amt_sv"]
  cy_booked_amt_dm = pf_amts["cy_booked_amt_dm"]
  cy_booked_amt_sv = pf_amts["cy_booked_amt_sv"]
  reserve_amt_dm = pf_amts["reserve_amt_dm"]
  reserve_amt_sv = pf_amts["reserve_amt_sv"]

  # perform calculations
  py_booked_amt = py_booked_amt_dm + py_booked_amt_sv
  cy_booked_amt = cy_booked_amt_dm + cy_booked_amt_sv
  reserve_amt = reserve_amt_dm + reserve_amt_sv
  total_booked_amt = py_booked_amt + cy_booked_amt

  return total_booked_amt, reserve_amt, cy_booked_amt, py_booked_amt

gen_output = 0

In [5]:
# function to format the amount
def format_amt(number):
    abs_number = abs(number)

    if abs_number >= 1_00_00_000:  # Crores
        formatted_amt = f"{number / 1_00_00_000:.2f} C"
    elif abs_number >= 1_00_000:  # Lakhs
        formatted_amt = f"{number / 1_00_000:.2f} L"
    elif abs_number >= 1_000:  # Thousands
        formatted_amt = f"{number / 1_000:.2f} K"
    else:
        formatted_amt = f"{number:.2f}"

    return formatted_amt

# function to set start and end date
def get_start_end_date():
  start_date = (datetime.date.today() + datetime.timedelta(days=-365)).strftime('%Y-%m-%d')
  end_date = (datetime.date.today() + datetime.timedelta(days=1)).strftime('%Y-%m-%d')
  return start_date, end_date

# function to fetch my portfolio csv
def get_mypfs_df():
  mypfs_df = pd.read_csv('https://raw.githubusercontent.com/ankit-rathi/Tradevesting_v1/main/data/myPortfolioStocks.csv')
  return mypfs_df

# function to fetch my prospects csv
def get_mypps_df():
  mypps_df = pd.read_csv('https://raw.githubusercontent.com/ankit-rathi/Tradevesting_v1/main/data/myProspectsScrips.csv')
  return mypps_df

# function to fetch screener data
def get_myscreen_df():
  myscreen_df = pd.read_csv('https://raw.githubusercontent.com/ankit-rathi/Tradevesting_v1/main/data/myScreenerDB.csv')
  return myscreen_df

# function to fetch momentum data
def get_myinvmt_df():
  myinvmt_df = pd.read_csv('https://raw.githubusercontent.com/ankit-rathi/Tradevesting_v1/main/data/myInvestments.csv')
  return myinvmt_df

# function to get the stock ids
def get_stock_ids(df_pf):
  stock_n100 = df_pf['Symbol'].unique()

  exclude = ['CADILAHC','MMTC', 'MASFIN']

  stock_ids = df_pf[~df_pf['Symbol'].isin(exclude) ]['Symbol'].unique()

  #mypf = mypf[mypf.Forecast.notnull()]
  #stock_ids = mypf['Symbol'].unique()

  #stock_ids.sort()
  return stock_ids

# get features from screener data
def get_screener_features():
  myscreen_df = get_myscreen_df()
  cols = ['Symbol', 'EPS', 'MedPE', 'ROCE%', 'ROE%', 'CapType']
  return myscreen_df[cols]

# get relative strength
def get_relative_strength(stock_list):

    # Dictionary to store stock tickers and their corresponding percentage price change
    stock_changes = {}

    # Loop through each stock and fetch its price data
    for stock in stock_list:
        try:
            # Download the stock data for the given date range
            stock_data = yfin.Ticker(stock + '.NS').history(period='1mo', interval='1d')[map(str.title, ['open', 'close', 'low', 'high', 'volume'])]

            # Calculate the percentage change for the stock
            if len(stock_data) > 0:
                start_price = stock_data['Close'].iloc[0]
                end_price = stock_data['Close'].iloc[-1]
                percent_change = round(((end_price - start_price) / start_price) * 100, 2)
                stock_changes[stock] = percent_change
            else:
                stock_changes[stock] = np.nan  # If no data is available, set to NaN

        except Exception as e:
            print(f"Error fetching data for {stock}: {e}")
            stock_changes[stock] = np.nan

    # Create a DataFrame with stock tickers and their percentage changes
    df = pd.DataFrame(list(stock_changes.items()), columns=['Symbol', 'Percent_Change'])

    # Drop any stocks with missing data (NaN values)
    df = df.dropna()

    # Calculate the percentile rank based on percentage change
    df['RSP'] = round(df['Percent_Change'].rank(pct=True) * 100, 2)
    cols = ['Symbol', 'RSP']
    df = df[cols]
    # Sort by percentile rank (optional)
    df = df.sort_values(by='RSP', ascending=False).reset_index(drop=True)

    return df

In [6]:
# function to get stock technicals
def stock_prec_dev(stock_symbol):
    #stock_symbol = 'ULTRACEMCO.NS'
    short_window = 20
    mid_window = 50
    long_window = 200
    moving_avg = 'SMA'

    start = datetime.datetime(*map(int, start_date.split('-')))
    end = datetime.datetime(*map(int, end_date.split('-')))

    stock_df = yfin.Ticker(stock_symbol + '.NS').history(period='max', interval='1d')[map(str.title, ['open', 'close', 'low', 'high', 'volume'])]

    stock_df['Max'] = round(max(stock_df['Close']),2)
    stock_df = stock_df[(stock_df.index <= end_date) & (stock_df.index >= start_date)]
    stock_df['200_SMA'] = round(stock_df['Close'].rolling(window = 200, min_periods = 1).mean(),0)
    stock_df['Dev%_200'] = round((stock_df['Close'] - stock_df['200_SMA'])*100/stock_df['200_SMA'],2)
    stock_df.dropna(axis = 0, inplace = True) # remove any null rows

    stock_df['20_SMA'] = stock_df['Close'].rolling(window=20).mean()
    stock_df['50_SMA'] = stock_df['Close'].rolling(window=50).mean()
    stock_df['Symbol'] = stock_symbol

    stock_df['Close'] = round(stock_df['Close'],2)
    stock_df['Min'] = round(min(stock_df['Close']),2)
    stock_df['RSI_14'] = ta.momentum.RSIIndicator(close=stock_df['Close'], window=14).rsi()
    stock_df['RSI_14'] = round(stock_df['RSI_14'],0)
    stock_df['Prev_Close'] = stock_df['Close'].shift(1)
    stock_df.drop(['Open', 'Low', 'High', 'Volume'], axis=1, inplace=True)
    stock_df = stock_df.tail(1)

    max_SMA = max(stock_df['20_SMA'].item(), stock_df['50_SMA'].item(), stock_df['200_SMA'].item())
    min_SMA = min(stock_df['20_SMA'].item(), stock_df['50_SMA'].item(), stock_df['200_SMA'].item())
    ABS_Spread = max_SMA - min_SMA
    stock_df['Spread%'] = round((ABS_Spread / stock_df['200_SMA'].item()) * 100,2)

    return stock_df

# function to compute stock attributes
def get_common_features(stock_ids, df_mypf):

  df_prec_dev = pd.DataFrame()
  df_tmp = get_screener_features()
  df_rs = get_relative_strength(stock_ids)

  for stock_id in stock_ids:
      tmp = stock_prec_dev(stock_id)
      tmp = tmp.reset_index()
      df_prec_dev = pd.concat([df_prec_dev, tmp], ignore_index = True)
  df_prec_dev = pd.merge(df_prec_dev, df_mypf, on= 'Symbol')
  df_prec_dev = pd.merge(df_prec_dev, df_tmp, on= 'Symbol', how='left')
  df_prec_dev = pd.merge(df_prec_dev, df_rs, on= 'Symbol', how='left')
  #print(df_prec_dev.columns)
  df_prec_dev['Curr_PE'] = round(df_prec_dev['Close']/df_prec_dev['EPS'],1)
  df_prec_dev['Dev%_PE'] = round((df_prec_dev['Curr_PE'] - df_prec_dev['MedPE'])*100/df_prec_dev['MedPE'],2)
  df_prec_dev['Conviction'] = df_prec_dev['Conviction'] + '-' + df_prec_dev['CapType']
  return df_prec_dev

# function to arrange stock features
def arrange_features(df_stocks, common_cols, diff_cols):
  df_stocks_common = df_stocks[common_cols].drop_duplicates()
  df_stocks_diff = df_stocks[diff_cols]
  df_stocks_diff['Investment'] = df_stocks_diff['AvgCost'] * df_stocks_diff['Shares']
  df_stocks_diff = df_stocks_diff.groupby(['Symbol'])[['Shares', 'Investment']].aggregate(['sum']).reset_index()
  df_stocks_diff.columns = ['Symbol', 'Shares', 'Investment']
  df_stocks_diff['AvgCost'] = round(df_stocks_diff['Investment']/df_stocks_diff['Shares'],2)
  df_stocks = pd.merge(df_stocks_diff, df_stocks_common, on='Symbol')
  return df_stocks

# plot fact distribution across dimension
def plot_pie_chart(df, dimension, fact):
  # grouping the data by category and calculating the sum of fact for each type
  grouped_data = df.groupby(dimension)[fact].sum()

  # sorting the grouped data in descending order
  grouped_data = grouped_data.sort_values(ascending=False)

  # creating a pie chart
  grouped_data.plot.pie(autopct='%1.1f%%', startangle=90, figsize=(6, 6))

  # adding a title and displaying the plot
  plt.title(f'{dimension} {fact} Distribution')
  plt.ylabel('')  # To hide the y-label
  plt.show()

In [7]:
# function to get portfolio features

def get_portfolio_features(df_common_features):

  print_date_time()
  print('-------------------')

  #df_common_features["Target"] = df_common_features["Target"].fillna(df_common_features["Max"])
  df_common_features['NTT'] = np.where(df_common_features['Strategy']== 'NTT', df_common_features["Target"], df_common_features['Max'])
  df_common_features['LTT'] = np.where(df_common_features['Strategy']== 'BTT', df_common_features["Target"], df_common_features['Max'])
  df_common_features['BOL'] = df_common_features['Min']

  tmp_df = df_common_features[df_common_features['Symbol'].isin(mypf_df[mypf_df['InPortfolio'] != 'NA'].Symbol.values)]
  print('qualified stocks: '+str(len(tmp_df['Symbol'].unique())))
  tmp_df1 = tmp_df[tmp_df['LatestQtr'] == 1]
  print('with latest results: '+str(len(tmp_df1['Symbol'].unique())))
  tmp_df1 = tmp_df1[tmp_df1['StarStock'] == 1]
  print('still star stocks: '+str(len(tmp_df1['Symbol'].unique())))
  tmp_df['Investment'] = tmp_df['AvgCost'] * tmp_df['Shares']
  tmp_df['Current'] = round(tmp_df['Close'] * tmp_df['Shares'],0)
  tmp_df['Previous'] = tmp_df['Prev_Close'] * tmp_df['Shares']
  tmp_df['EstimatedST'] = tmp_df['NTT'] * tmp_df['Shares']
  tmp_df['EstimatedLT'] = tmp_df['LTT'] * tmp_df['Shares']
  tmp_df['Current P/L'] = round((tmp_df['Current'] - tmp_df['Investment']),0)
  tmp_df['Today P/L%'] = round((tmp_df['Current'] - tmp_df['Previous'])*100/tmp_df['Previous'],2)
  tmp_df['Current P/L%'] = round((tmp_df['Current'] - tmp_df['Investment'])*100/tmp_df['Investment'],2)
  tmp_df['EstimatedST P/L%'] = round((tmp_df['EstimatedST'] - tmp_df['Investment'])*100/tmp_df['Investment'],2)
  tmp_df['EstimatedLT P/L%'] = round((tmp_df['EstimatedLT'] - tmp_df['Investment'])*100/tmp_df['Investment'],2)
  tmp_df['NTT%'] = round((tmp_df['NTT'] - tmp_df['Close'])*100/tmp_df['Close'],2)
  tmp_df['LTT%'] = round((tmp_df['LTT'] - tmp_df['Close'])*100/tmp_df['Close'],2)
  tmp_df['Gained%'] = round((tmp_df['Close'] - tmp_df['BOL'])*100/tmp_df['BOL'],2)
  investment = round(sum(tmp_df['AvgCost']*tmp_df['Shares']),0)
  current = round(sum(tmp_df['Close']*tmp_df['Shares']),0)
  tmp_df['InitAlloc%'] = round(tmp_df['Investment']*100/investment,2)
  tmp_df['CurrAlloc%'] = round(tmp_df['Current']*100/current,2)
  tmp_df['FTT'] = tmp_df['LTT']
  tmp_df.loc[tmp_df['Strategy'] == 'NTT', 'FTT'] = tmp_df['NTT']
  tmp_df['FTT%'] = tmp_df['LTT%']
  tmp_df.loc[tmp_df['Strategy'] == 'NTT', 'FTT%'] = tmp_df['NTT%']
  tmp_df['FTT Amt'] = round(tmp_df['FTT%'] * tmp_df['Current']/100,0)
  tmp_df['OTT%'] = round((tmp_df['FTT'] - tmp_df['AvgCost'])*100/tmp_df['AvgCost'],2)
  tmp_df['RRR Ind'] = round(tmp_df['Current P/L']/tmp_df['FTT Amt'],2)
  tmp_df['Risk Ind'] = round(tmp_df['Current P/L%']*tmp_df['CurrAlloc%'],0)

  return tmp_df

# function to print portfolio features
def print_portfolio_stats(df_portfolio_features, myinvmt_df):
  from pyxirr import xirr

  total_booked_amt, reserve_amt, cy_booked_amt, py_booked_amt = get_amt()

  dates = myinvmt_df['Date'].values
  dates = np.append(dates, datetime.date.today().strftime('%d-%b-%y'))
  investment = myinvmt_df['Investment'].values
  dates= pd.to_datetime(dates)

  current = round(sum(df_portfolio_features['Close']*df_portfolio_features['Shares']),0) + reserve_amt
  investment_xirr = np.append(investment, current)
  cagr = round(xirr(pd.DataFrame({"dates": dates, "amounts": investment_xirr}))*100,2)

  investment = -sum(investment)
  invested = round(sum(df_portfolio_features['AvgCost']*df_portfolio_features['Shares']),0) + reserve_amt
  previous = round(sum(df_portfolio_features['Prev_Close']*df_portfolio_features['Shares']),0) + reserve_amt
  cy_invested = investment + py_booked_amt

  today_pnl_amount = current-previous
  today_pnl_percentage = round((current-previous)*100/previous,2)

  curr_pnl_amount = current-invested
  curr_pnl_percentage = round((curr_pnl_amount)*100/(cy_invested),2)

  cy_pnl_amount = cy_booked_amt + curr_pnl_amount
  cy_pnl_percentage = round((cy_pnl_amount)*100/cy_invested,2)

  overall_pnl_amount = total_booked_amt + curr_pnl_amount
  overall_pnl_percentage = round((overall_pnl_amount)*100/investment,2)

  estimate_st = round(sum(df_portfolio_features['FTT']*df_portfolio_features['Shares']),0)  + reserve_amt
  est_st_pnl_amount = estimate_st-current
  est_st_pnl_percentage = round((est_st_pnl_amount)*100/current,2)

  estimate_lt = round(sum(df_portfolio_features['LTT']*df_portfolio_features['Shares']),0)  + reserve_amt
  est_lt_pnl_amount = estimate_lt-current
  est_lt_pnl_percentage = round((est_lt_pnl_amount)*100/current,2)

  total_profit = round(sum(df_portfolio_features[df_portfolio_features['Current P/L%'] > 0]['Current']) - sum(df_portfolio_features[df_portfolio_features['Current P/L%'] > 0]['Investment']),0)
  total_loss = round(sum(df_portfolio_features[df_portfolio_features['Current P/L%'] < 0]['Current']) - sum(df_portfolio_features[df_portfolio_features['Current P/L%'] < 0]['Investment']),0)

  cy_booked_percentage = round((cy_booked_amt)*100/current,2)
  py_booked_percentage = round((py_booked_amt)*100/investment,2)
  total_booked_percentage = round((total_booked_amt)*100/investment,2)

  print('-------------------')
  print('Initial Investment: ', format_amt(investment))
  print('CY Investment: ', format_amt(cy_invested))
  print('Reserve: ', format_amt(reserve_amt))
  print('Current: ',  format_amt(current))
  print('-------------------')
  print('Today PnL: '+ '{} ({}%)'.format(format_amt(today_pnl_amount), today_pnl_percentage))
  print('Current PnL: '+ '{} ({}%)'.format(format_amt(curr_pnl_amount), curr_pnl_percentage))
  print('CY Booked + Current PnL: '+ '{} ({}%)'.format(format_amt(cy_pnl_amount), cy_pnl_percentage))
  print('-------------------')
  print('Total profit: ', format_amt(total_profit))
  print('Total loss: ', format_amt(total_loss))
  print('-------------------')
  print('Total Booked + Current PnL: '+ '{} ({}%)'.format(format_amt(overall_pnl_amount), overall_pnl_percentage))
  print('Total Booked PnL: '+ '{} ({}%)'.format(format_amt(total_booked_amt), total_booked_percentage))
  print('Curr Year Booked PnL: '+ '{} ({}%)'.format(format_amt(cy_booked_amt), cy_booked_percentage))
  print('Prev Year Booked PnL: '+ '{} ({}%)'.format(format_amt(py_booked_amt), py_booked_percentage))
  print('===================')
  print('Est FTT: ',  format_amt(estimate_st))
  print('Est FTT PnL: '+ '{} ({}%)'.format(format_amt(est_st_pnl_amount), est_st_pnl_percentage))

  print('===================')
  print('Deployed: ', format_amt(investment))

  print('Current: ', format_amt(current))

  print('CAGR/XIRR %: '+'{}%'.format(cagr))

In [8]:
# get start and end date
start_date, end_date = get_start_end_date()

# get portfolio and prospects data
mypfs_df = get_mypfs_df()
mypps_df = get_mypps_df()
myinvmt_df = get_myinvmt_df()

# merge above datasets
mypf_df = pd.merge(mypfs_df, mypps_df, on="Symbol")

# seggregate dm and sv portfolio
dm_pf = mypf_df[mypf_df['InPortfolio'] == 'DM']
sv_pf = mypf_df[mypf_df['InPortfolio'] == 'SV']

# build portfolio stock dataframe
dm_stocks = get_stock_ids(dm_pf)
sv_stocks = get_stock_ids(sv_pf)
df_stocks = pd.concat([dm_pf,sv_pf], ignore_index = True)

# arrange common and diff stock features
common_cols = ['Symbol', 'Target', 'Criteria', 'Strategy', 'CumlRnk', 'LatestQtr', 'StarStock', 'Conviction', 'Category', 'InFolio', 'XIRR', 'MBQ']
diff_cols = ['Symbol', 'AvgCost', 'Shares']
df_stocks = arrange_features(df_stocks, common_cols, diff_cols)

# get common features
stock_ids = df_stocks['Symbol'].values
df_common_features = get_common_features(stock_ids, df_stocks)

df_common_features.reset_index(drop=True, inplace=True)
df_common_features.drop(['Date'], axis=1, inplace=True)
# get and print portfolio features
df_portfolio_features = get_portfolio_features(df_common_features)

print_portfolio_stats(df_portfolio_features, myinvmt_df)

df = df_portfolio_features
#plot_pie_chart(df, 'CapType', 'Current')
list_ox40n = list(df[df['MBQ'].str.contains('OX40N', na=False)]['Symbol'].values)

Run date time (IST): 2026-08-19 09:52:41
-------------------
qualified stocks: 87
with latest results: 30
still star stocks: 19
-------------------
Initial Investment:  1.46 C
CY Investment:  1.89 C
Reserve:  3.69 L
Current:  1.58 C
-------------------
Today PnL: -29.62 K (-0.19%)
Current PnL: -35.05 L (-18.55%)
CY Booked + Current PnL: -29.99 L (-15.88%)
-------------------
Total profit:  3.32 L
Total loss:  -38.37 L
-------------------
Total Booked + Current PnL: 12.88 L (8.82%)
Total Booked PnL: 47.93 L (32.82%)
Curr Year Booked PnL: 5.06 L (3.2%)
Prev Year Booked PnL: 42.87 L (29.35%)
===================
Est FTT:  2.67 C
Est FTT PnL: 1.09 C (69.17%)
===================
Deployed:  1.46 C
Current:  1.58 C
CAGR/XIRR %: 3.53%

In [9]:
# top 5 near their targets
cols = ['Symbol', 'Today P/L%', 'Current P/L%', 'FTT%', 'OTT%', 'FTT Amt', 'Current P/L', 'Current', 'FTT', 'Dev%_PE', 'RSI_14','Conviction', 'Spread%',  'CumlRnk', 'RRR Ind', 'CurrAlloc%', 'Gained%', 'Criteria', 'Strategy', 'Category']
df_tmp = df_portfolio_features[~df_portfolio_features['Symbol'].isin(['ENRIN','BLUSPRING','DIGITIDE'])]
df_tmp = df_tmp.sort_values(by = 'FTT Amt', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
66,SIEMENS,-1.26,4.98,5.57,10.83,10882.0,9265.0,195360.0,4125.00,-14.90,58.0,H-LC,13.93,51.0,0.85,1.27,37.84,AR,NTT,ELECTRICAL
78,UNITDSPR,0.51,12.29,7.55,20.77,19850.0,28775.0,262919.0,1644.00,-4.30,61.0,X-MC,11.29,64.0,1.45,1.71,26.38,X40N,NTT,BREWERIES
77,TTKPRESTIG,-0.88,-23.39,30.65,0.09,23663.0,-23572.0,77205.0,770.00,-6.68,40.0,M-SC,9.69,250.0,-1.00,0.50,38.96,OX40N,NTT,DURABLES
52,M&M,-0.68,7.31,10.73,18.82,27712.0,17590.0,258271.0,3762.88,-7.36,56.0,X-LC,4.84,25.0,0.63,1.67,17.16,X40N,ATH,AUTO
67,SIS,0.40,-3.98,26.29,21.26,28029.0,-4416.0,106616.0,528.00,104.78,40.0,H-SC,21.01,168.0,-0.16,0.69,58.52,OX40N,NTT,MISC

In [10]:
# top 5 today
df_tmp = df_portfolio_features.sort_values(by = 'Today P/L%', ascending=False)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
0,5PAISA,7.80,-21.84,44.46,12.90,75923.0,-47728.0,170768.0,593.00,9.49,68.0,H-SC,11.40,170.0,-0.63,1.11,64.79,OX40N,NTT,FINANCE
27,GLAXO,4.16,20.31,12.78,35.69,30641.0,40476.0,239760.0,3380.16,-9.87,84.0,X-MC,9.80,56.0,1.32,1.55,42.50,X40,ATH,PHARMA
74,TITAGARH,2.50,-20.78,83.97,45.74,161097.0,-50326.0,191851.0,1548.00,NaN,50.0,NaN,7.69,175.0,-0.31,1.24,46.38,XY24,NTT,ENGINEERING
62,REPCOHOME,1.27,-23.63,148.55,89.82,325032.0,-67702.0,218803.0,880.00,NaN,30.0,NaN,4.16,161.0,-0.21,1.42,5.18,XY24,NTT,FINANCE
12,BOSCH-HCIL,1.26,-24.55,32.53,-0.01,31367.0,-31379.0,96426.0,2282.00,753.16,76.0,M-SC,6.84,231.0,-1.00,0.63,64.13,OX40N,BTT,AC

In [11]:
# bottom 5 today
df_tmp = df_portfolio_features.sort_values(by = 'Today P/L%', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
25,FINCABLES,-4.09,61.49,28.75,107.91,68547.0,90781.0,238425.0,1641.55,17.82,68.0,M-SC,19.76,220.0,1.32,1.55,79.38,OX40N,ATH,CABLES
30,HAPPSTMNDS,-2.80,-49.04,259.27,83.08,169334.0,-62853.0,65312.0,1466.54,NaN,58.0,NaN,7.64,152.0,-0.37,0.42,22.33,AR,ATH,IT
11,BERGEPAINT,-2.19,-0.98,26.56,25.32,67786.0,-2532.0,255217.0,680.00,-13.92,55.0,X-MC,5.25,68.0,-0.04,1.66,33.83,XY24,NTT,PAINTS
40,ICICIPRULI,-2.17,-17.92,58.72,30.28,94948.0,-35309.0,161696.0,787.27,-47.40,43.0,X-MC,12.48,78.0,-0.37,1.05,7.73,X40,ATH,INSURANCE
10,BATAINDIA,-1.85,-53.90,193.29,35.20,114652.0,-69354.0,59316.0,2096.00,NaN,60.0,NaN,11.22,91.0,-0.60,0.38,23.26,X40,NTT,FOOTWEAR

In [12]:
# top 5 to exit based on CumlRnk
df_tmp = df_portfolio_features[~df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])]
df_tmp = df_tmp[(df_tmp['Current P/L%'] > -1) & (df_tmp['Current P/L%'] < 1)].sort_values(by = 'CumlRnk', ascending=False)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
79,UTIAMC,0.6,-0.82,52.41,51.15,115564.0,-1830.0,220500.0,1371.68,25.5,45.0,M-SC,7.52,229.0,-0.02,1.43,3.29,XY24,ATH,FINANCE

In [13]:
# OX40N stocks to exit
df_tmp = df_portfolio_features[(df_portfolio_features['Symbol'].isin(list_ox40n))].sort_values(by = 'Current P/L%', ascending=False)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
25,FINCABLES,-4.09,61.49,28.75,107.91,68547.0,90781.0,238425.0,1641.55,17.82,68.0,M-SC,19.76,220.0,1.32,1.55,79.38,OX40N,ATH,CABLES
67,SIS,0.40,-3.98,26.29,21.26,28029.0,-4416.0,106616.0,528.00,104.78,40.0,H-SC,21.01,168.0,-0.16,0.69,58.52,OX40N,NTT,MISC
43,INDIGOPNTS,-1.45,-18.72,23.06,0.02,32718.0,-32678.0,141881.0,1408.00,-22.52,62.0,M-SC,6.95,222.0,-1.00,0.92,60.97,OX40N,NTT,PAINTS
0,5PAISA,7.80,-21.84,44.46,12.90,75923.0,-47728.0,170768.0,593.00,9.49,68.0,H-SC,11.40,170.0,-0.63,1.11,64.79,OX40N,NTT,FINANCE
77,TTKPRESTIG,-0.88,-23.39,30.65,0.09,23663.0,-23572.0,77205.0,770.00,-6.68,40.0,M-SC,9.69,250.0,-1.00,0.50,38.96,OX40N,NTT,DURABLES

In [14]:
# top 5 to book for rotation
df_tmp = df_portfolio_features[(df_portfolio_features['Current P/L%'] > 20) ].sort_values(by = 'CumlRnk', ascending=False)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
25,FINCABLES,-4.09,61.49,28.75,107.91,68547.0,90781.0,238425.0,1641.55,17.82,68.0,M-SC,19.76,220.0,1.32,1.55,79.38,OX40N,ATH,CABLES
27,GLAXO,4.16,20.31,12.78,35.69,30641.0,40476.0,239760.0,3380.16,-9.87,84.0,X-MC,9.80,56.0,1.32,1.55,42.50,X40,ATH,PHARMA

In [15]:
# top 5 to monitor for exit
df_tmp = df_portfolio_features[~df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])]
df_tmp = df_tmp[(df_tmp['Current P/L%'] > 0) ].sort_values(by = 'Dev%_PE', ascending=False)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
25,FINCABLES,-4.09,61.49,28.75,107.91,68547.0,90781.0,238425.0,1641.55,17.82,68.0,M-SC,19.76,220.0,1.32,1.55,79.38,OX40N,ATH,CABLES
68,STARHEALTH,-0.27,12.75,30.61,47.26,97022.0,35839.0,316962.0,761.00,-0.61,50.0,H-SC,16.23,173.0,0.37,2.06,37.05,XY24,NTT,INSURANCE

In [16]:
# top 5 to book for rotation from weak conviction
df_tmp = df_portfolio_features[~df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])]
df_tmp = df_tmp[~df_tmp['Criteria'].isin(['XY25','XY24','X40', 'X40N'])].sort_values(by = 'RRR Ind', ascending=False)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
25,FINCABLES,-4.09,61.49,28.75,107.91,68547.0,90781.0,238425.0,1641.55,17.82,68.0,M-SC,19.76,220.0,1.32,1.55,79.38,OX40N,ATH,CABLES
67,SIS,0.40,-3.98,26.29,21.26,28029.0,-4416.0,106616.0,528.00,104.78,40.0,H-SC,21.01,168.0,-0.16,0.69,58.52,OX40N,NTT,MISC
3,ALKYLAMINE,-1.43,-19.39,138.87,92.54,113015.0,-19581.0,81382.0,4520.85,NaN,53.0,NaN,14.17,142.0,-0.17,0.53,54.54,SR,ATH,CHEMICALS
42,INDIAMART,-0.55,-25.08,168.17,100.92,155399.0,-30930.0,92406.0,4675.60,NaN,36.0,NaN,13.68,140.0,-0.20,0.60,0.03,AR,ATH,MISC
71,TANLA,1.25,-34.00,229.19,117.25,409537.0,-92072.0,178689.0,1922.32,NaN,50.0,NaN,15.40,147.0,-0.22,1.16,56.45,AR,ATH,IT

In [17]:
# top 5 to accumulate based on lowest RSI_14
df_tmp = df_portfolio_features[df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])].sort_values(by = 'RSI_14', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
19,COLPAL,-0.24,-27.91,94.02,39.86,178497.0,-73515.0,189850.0,3683.41,-12.72,29.0,X-MC,1.66,62.0,-0.41,1.23,7.39,XY25,ATH,FMCG
56,PGHH,-1.06,-37.98,112.85,32.01,149440.0,-81096.0,132424.0,17616.87,-54.38,29.0,X-SC,19.11,57.0,-0.54,0.86,0.00,X40,ATH,FMCG
55,PAGEIND,-1.09,-6.55,42.16,32.85,105741.0,-17569.0,250810.0,50936.07,-30.54,30.0,X-MC,8.77,55.0,-0.17,1.63,19.77,X40,ATH,APPARELS
34,HDFCBANK,-0.51,-12.15,49.17,31.05,126617.0,-35611.0,257509.0,1073.00,-29.01,31.0,X-LC,12.78,26.0,-0.28,1.67,0.00,X40,BTT,BANKS
47,ITC,0.07,-25.46,67.28,24.70,199242.0,-101139.0,296139.0,452.00,-30.35,32.0,X-LC,10.63,1.0,-0.51,1.92,0.07,X40,NTT,FMCG

In [18]:
# top 5 to accumulate based on Spread and CumlRnk
df_tmp = df_portfolio_features[df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])]
df_tmp = df_tmp[(df_tmp['CumlRnk'] < 100)].sort_values(by = 'Spread%', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
19,COLPAL,-0.24,-27.91,94.02,39.86,178497.0,-73515.0,189850.0,3683.41,-12.72,29.0,X-MC,1.66,62.0,-0.41,1.23,7.39,XY25,ATH,FMCG
50,KOTAKBANK,0.25,2.13,16.43,18.92,40224.0,5116.0,244818.0,452.46,-13.75,48.0,X-LC,2.28,12.0,0.13,1.59,10.15,X40,ATH,BANKS
23,DMART,-0.17,-2.78,35.18,31.42,106637.0,-8672.0,303118.0,5391.45,-18.52,47.0,X-LC,2.31,14.0,-0.08,1.97,9.38,X40N,ATH,FMCG
26,GILLETTE,-0.71,-11.20,46.08,29.72,103894.0,-28431.0,225465.0,10978.86,-35.84,36.0,X-SC,3.48,83.0,-0.27,1.46,3.61,X40,ATH,FMCG
1,ABBOTINDIA,-1.60,-11.19,29.90,15.37,47496.0,-20005.0,158850.0,34390.26,-27.79,37.0,X-MC,4.05,58.0,-0.42,1.03,7.60,X40,ATH,PHARMA

In [19]:
# top 5 to accumulate based on lowest Gained%
df_tmp = df_portfolio_features[df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])].sort_values(by = 'Gained%', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
20,DABUR,-0.28,-21.34,82.68,43.70,161342.0,-52928.0,195140.0,735.00,-32.11,35.0,X-MC,10.00,70.0,-0.33,1.27,0.00,XY24,BTT,FMCG
34,HDFCBANK,-0.51,-12.15,49.17,31.05,126617.0,-35611.0,257509.0,1073.00,-29.01,31.0,X-LC,12.78,26.0,-0.28,1.67,0.00,X40,BTT,BANKS
56,PGHH,-1.06,-37.98,112.85,32.01,149440.0,-81096.0,132424.0,17616.87,-54.38,29.0,X-SC,19.11,57.0,-0.54,0.86,0.00,X40,ATH,FMCG
47,ITC,0.07,-25.46,67.28,24.70,199242.0,-101139.0,296139.0,452.00,-30.35,32.0,X-LC,10.63,1.0,-0.51,1.92,0.07,X40,NTT,FMCG
35,HDFCLIFE,-0.35,-8.02,51.28,39.15,118267.0,-20107.0,230630.0,811.41,-32.34,40.0,X-LC,16.62,31.0,-0.17,1.50,0.09,X40,ATH,INSURANCE

In [20]:
# top 5 to accumulate based on lowest CurrAlloc%
df_tmp = df_portfolio_features[df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])].sort_values(by = 'CurrAlloc%', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
56,PGHH,-1.06,-37.98,112.85,32.01,149440.0,-81096.0,132424.0,17616.87,-54.38,29.0,X-SC,19.11,57.0,-0.54,0.86,0.00,X40,ATH,FMCG
2,ACC,-0.66,-42.03,201.58,74.81,313304.0,-112704.0,155424.0,3906.00,-42.69,34.0,X-SC,11.40,85.0,-0.36,1.01,3.83,XY24,BTT,CEMENT
1,ABBOTINDIA,-1.60,-11.19,29.90,15.37,47496.0,-20005.0,158850.0,34390.26,-27.79,37.0,X-MC,4.05,58.0,-0.42,1.03,7.60,X40,ATH,PHARMA
40,ICICIPRULI,-2.17,-17.92,58.72,30.28,94948.0,-35309.0,161696.0,787.27,-47.40,43.0,X-MC,12.48,78.0,-0.37,1.05,7.73,X40,ATH,INSURANCE
39,ICICIGI,-0.15,-13.98,38.21,18.89,65772.0,-27976.0,172133.0,2244.41,-14.33,41.0,X-MC,10.32,66.0,-0.43,1.12,2.55,X40,ATH,INSURANCE

In [21]:
# top 5 to accumulate based on CumlRnk
df_tmp = df_portfolio_features.sort_values(by = 'CumlRnk', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
47,ITC,0.07,-25.46,67.28,24.70,199242.0,-101139.0,296139.0,452.00,-30.35,32.0,X-LC,10.63,1.0,-0.51,1.92,0.07,X40,NTT,FMCG
73,TCS,-0.13,-33.15,85.79,24.20,265680.0,-153587.0,309686.0,4230.71,-44.65,46.0,X-LC,14.11,2.0,-0.58,2.01,15.48,X40,ATH,IT
45,INFY,0.88,-19.93,75.32,40.38,227049.0,-75024.0,301446.0,1972.00,-40.86,48.0,X-LC,15.90,3.0,-0.33,1.95,14.16,X40,NTT,IT
75,TMPV,-0.43,-23.53,86.68,42.75,275804.0,-97921.0,318186.0,600.00,-84.91,35.0,X-LC,4.53,4.0,-0.36,2.06,9.41,XY24,NTT,AUTO
33,HCLTECH,0.96,-12.35,41.44,23.97,112407.0,-38233.0,271253.0,1853.42,-14.68,53.0,X-LC,11.34,8.0,-0.34,1.76,28.00,X40,ATH,IT

In [22]:
# top 5 for average up
df_tmp = df_portfolio_features[(df_portfolio_features['Dev%_200'] > 5)].sort_values(by = 'CurrAlloc%', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
44,INDUSINDBK,-0.01,-25.40,78.13,32.89,45001.0,-19608.0,57598.0,1800.00,323.79,51.0,L-MC,12.74,258.0,-0.44,0.37,42.00,XR,NTT,BANKS
60,RELAXO,-0.29,-49.48,201.50,52.31,147758.0,-71831.0,73329.0,1176.00,NaN,43.0,NaN,12.34,92.0,-0.49,0.48,63.96,X40N,NTT,FOOTWEAR
3,ALKYLAMINE,-1.43,-19.39,138.87,92.54,113015.0,-19581.0,81382.0,4520.85,NaN,53.0,NaN,14.17,142.0,-0.17,0.53,54.54,SR,ATH,CHEMICALS
12,BOSCH-HCIL,1.26,-24.55,32.53,-0.01,31367.0,-31379.0,96426.0,2282.00,753.16,76.0,M-SC,6.84,231.0,-1.00,0.63,64.13,OX40N,BTT,AC
81,VALIANTORG,-1.57,-36.94,176.16,74.15,181750.0,-60432.0,103173.0,838.00,NaN,55.0,NaN,6.95,145.0,-0.33,0.67,53.54,XR,NTT,CHEMICALS

In [23]:
# top 5 RSP
df_tmp = df_portfolio_features.sort_values(by = 'RSP', ascending=False)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
12,BOSCH-HCIL,1.26,-24.55,32.53,-0.01,31367.0,-31379.0,96426.0,2282.00,753.16,76.0,M-SC,6.84,231.0,-1.00,0.63,64.13,OX40N,BTT,AC
25,FINCABLES,-4.09,61.49,28.75,107.91,68547.0,90781.0,238425.0,1641.55,17.82,68.0,M-SC,19.76,220.0,1.32,1.55,79.38,OX40N,ATH,CABLES
27,GLAXO,4.16,20.31,12.78,35.69,30641.0,40476.0,239760.0,3380.16,-9.87,84.0,X-MC,9.80,56.0,1.32,1.55,42.50,X40,ATH,PHARMA
81,VALIANTORG,-1.57,-36.94,176.16,74.15,181750.0,-60432.0,103173.0,838.00,NaN,55.0,NaN,6.95,145.0,-0.33,0.67,53.54,XR,NTT,CHEMICALS
38,HYUNDAI,-0.78,12.19,28.30,43.94,79794.0,30625.0,281957.0,2782.73,16.23,59.0,X-LC,5.27,29.0,0.38,1.83,29.46,X40N,ATH,AUTO

In [24]:
# Top N allocation
df_tmp = df_portfolio_features.sort_values(by = 'CurrAlloc%', ascending=False)
top_n_values = [10, 25, 50]

sum_df = pd.DataFrame({
    'Top_N': top_n_values,
    'Sum_Alloc%': [df_tmp['CurrAlloc%'].head(n).sum() for n in top_n_values]
})

sum_df

   Top_N  Sum_Alloc%
0     10       19.71
1     25       45.04
2     50       77.69

In [25]:
# market-cap-wise allocation
df_tmp = df_portfolio_features[cols]
df_tmp.groupby(df_tmp['Conviction'].str[-2:])['CurrAlloc%'].sum().sort_values(ascending=False)

Conviction
LC    38.01
MC    22.30
SC    21.62
Name: CurrAlloc%, dtype: float64

In [26]:
# criteria-wise allocation
df_portfolio_features.groupby('Criteria')['CurrAlloc%'].sum().sort_values(ascending=False)

Criteria
X40      26.67
XY24     24.03
X40N     18.66
XR        9.08
OX40N     7.38
XY25      7.22
AR        6.15
SR        0.86
Name: CurrAlloc%, dtype: float64

In [27]:
# conviction-wise allocation
df_portfolio_features.groupby('Conviction')['CurrAlloc%'].sum().sort_values(ascending=False)

Conviction
X-LC    34.32
X-MC    19.68
H-SC     8.55
X-SC     7.65
M-SC     5.42
H-LC     2.88
M-MC     1.21
H-MC     1.04
M-LC     0.81
L-MC     0.37
Name: CurrAlloc%, dtype: float64

In [28]:
# sector-wise stats
df_tmp = df_portfolio_features.groupby('Category')[['CurrAlloc%', 'Current', 'Current P/L', 'FTT Amt']].sum().sort_values(by=['Current', 'Current P/L'], ascending=False)
df_tmp['Current P/L%'] = round(df_tmp['Current P/L'] * 100 / df_tmp['Current'], 2)
df_tmp['FTT%'] = round(df_tmp['FTT Amt'] * 100 / df_tmp['Current'], 2)
cols = ['CurrAlloc%', 'Current P/L%', 'FTT%']
df_tmp[cols].sort_values(by=['CurrAlloc%'], ascending=False)

               CurrAlloc%  Current P/L%    FTT%
Category
FMCG                15.47        -25.06   70.02
IT                  11.15        -38.64  107.41
FINANCE             10.84        -15.57   65.35
AUTO                 8.25         -6.32   44.39
BANKS                6.11        -13.40   62.31
MISC                 5.98        -33.78   87.59
PHARMA               5.90          8.86   16.98
INSURANCE            5.73         -5.40   42.66
PAINTS               5.49        -16.60   36.49
ELECTRICAL           4.20         -9.07   43.22
AC                   1.83        -13.55   44.34
REFINERIES           1.74        -11.07   48.38
BREWERIES            1.71         10.94    7.55
FOOTWEAR             1.67        -71.81  140.70
APPARELS             1.63         -7.00   42.16
CABLES               1.55         38.08   28.75
DURABLES             1.47        -70.18  111.57
TRAVEL               1.43       -102.88  204.46
CERAMICS             1.35        -47.51   92.33
ENGINEERING          1.24        -26.23   83.97
CHEMICALS            1.20        -43.35  159.72
CEMENT               1.01        -72.51  201.58
JEWELLERY            0.96       -115.71  190.66
ENTERTAINMENT        0.69        -80.51  188.16
HEALTHCARE           0.69        -69.38  111.90
TEXTILES             0.39        -52.51   96.00
HOTELS               0.37       -100.20  170.82

In [29]:
# money to be made criteria-wise
df_portfolio_features.groupby('Criteria')['FTT Amt'].agg(['sum', 'count']).sort_values(by='sum', ascending=False)

                sum  count
Criteria
XY24      3625735.0     19
X40       2111208.0     18
XR        1395896.0     13
X40N      1205796.0     12
AR        1057574.0      8
OX40N      655495.0     10
XY25       585576.0      5
SR         283739.0      2

In [30]:
# money to be made conviction-wise
df_portfolio_features.groupby('Conviction')['FTT Amt'].agg(['sum', 'count']).sort_values(by='sum', ascending=False)

                  sum  count
Conviction
X-LC        2434605.0     19
X-MC        1470089.0     14
X-SC        1100619.0      6
H-SC         834752.0      8
M-SC         329929.0      6
H-MC         252726.0      1
M-LC         167209.0      1
M-MC          59101.0      1
H-LC          47127.0      2
L-MC          45001.0      1

In [31]:
# money to be made criteria and conviction-wise
df_portfolio_features.groupby(['Conviction', 'Criteria'])['FTT Amt'].agg(['sum', 'count']).sort_values(by='sum', ascending=False)

                           sum  count
Conviction Criteria
X-LC       X40       1239650.0      9
X-SC       XY24       674461.0      2
H-SC       XY24       532580.0      3
X-MC       X40        503572.0      6
           X40N       465488.0      4
X-LC       XY24       458610.0      2
           X40N       419726.0      5
X-MC       XY25       271901.0      2
X-LC       XY25       254574.0      2
X-SC       X40        253334.0      2
H-MC       XY24       252726.0      1
X-MC       XY24       229128.0      2
H-SC       OX40N      208664.0      3
X-SC       X40N       172824.0      2
M-LC       XR         167209.0      1
M-SC       OX40N      156295.0      4
           XY24       115564.0      1
H-SC       XR          93508.0      2
X-LC       XR          62045.0      1
M-MC       XY25        59101.0      1
M-SC       XR          58070.0      1
H-LC       AR          47127.0      2
L-MC       XR          45001.0      1

In [32]:
# notebook execution time

end_time = time.time()
execution_time = round(end_time - start_time, 0)
print(f"Notebook execution time: {execution_time} seconds")

Notebook execution time: 29.0 seconds