<a href="https://colab.research.google.com/github/ankit-rathi/Quantvesting_v2/blob/main/myStocks_Portfolio_Analysis.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
'''
!pip install pandas==2.2.2 -qq
!pip install pyxirr -qq
!pip install ta -qq
!pip install yfinance==0.2.59 -qq
'''

'\n!pip install pandas==2.2.2 -qq\n!pip install pyxirr -qq\n!pip install ta -qq\n!pip install yfinance==0.2.59 -qq\n'

In [2]:
# import libraries

import numpy as np
import pandas as pd
import datetime
import warnings
warnings.filterwarnings('ignore')
import yfinance as yfin
import ta
import matplotlib.pyplot as plt
import requests

In [3]:
# notebook start time
import time
import datetime
import pytz

start_time = time.time()

# function to print date timestamp
def print_date_time():
  tz_NY = pytz.timezone('Asia/Kolkata')
  datetime_NY = datetime.datetime.now(tz_NY)
  print("Run date time (IST):", datetime_NY.strftime("%Y-%m-%d %H:%M:%S"))

In [4]:
# function to get booked and reserved amount
def get_amt():
  # fetch the JSON data from the URL
  url = "https://raw.githubusercontent.com/ankit-rathi/Tradevesting_v1/main/data/myPortfolioAmts.json"
  response = requests.get(url)
  pf_amts = response.json()  # parse the JSON data

  # extract values from the JSON
  py_booked_amt_dm = pf_amts["py_booked_amt_dm"]
  py_booked_amt_sv = pf_amts["py_booked_amt_sv"]
  cy_booked_amt_dm = pf_amts["cy_booked_amt_dm"]
  cy_booked_amt_sv = pf_amts["cy_booked_amt_sv"]
  reserve_amt_dm = pf_amts["reserve_amt_dm"]
  reserve_amt_sv = pf_amts["reserve_amt_sv"]

  # perform calculations
  py_booked_amt = py_booked_amt_dm + py_booked_amt_sv
  cy_booked_amt = cy_booked_amt_dm + cy_booked_amt_sv
  reserve_amt = reserve_amt_dm + reserve_amt_sv
  total_booked_amt = py_booked_amt + cy_booked_amt

  return total_booked_amt, reserve_amt, cy_booked_amt, py_booked_amt

gen_output = 0

In [5]:
# function to format the amount
def format_amt(number):
    abs_number = abs(number)

    if abs_number >= 1_00_00_000:  # Crores
        formatted_amt = f"{number / 1_00_00_000:.2f} C"
    elif abs_number >= 1_00_000:  # Lakhs
        formatted_amt = f"{number / 1_00_000:.2f} L"
    elif abs_number >= 1_000:  # Thousands
        formatted_amt = f"{number / 1_000:.2f} K"
    else:
        formatted_amt = f"{number:.2f}"

    return formatted_amt

# function to set start and end date
def get_start_end_date():
  start_date = (datetime.date.today() + datetime.timedelta(days=-365)).strftime('%Y-%m-%d')
  end_date = (datetime.date.today() + datetime.timedelta(days=1)).strftime('%Y-%m-%d')
  return start_date, end_date

# function to fetch my portfolio csv
def get_mypfs_df():
  mypfs_df = pd.read_csv('https://raw.githubusercontent.com/ankit-rathi/Tradevesting_v1/main/data/myPortfolioStocks.csv')
  return mypfs_df

# function to fetch my prospects csv
def get_mypps_df():
  mypps_df = pd.read_csv('https://raw.githubusercontent.com/ankit-rathi/Tradevesting_v1/main/data/myProspectsScrips.csv')
  return mypps_df

# function to fetch screener data
def get_myscreen_df():
  myscreen_df = pd.read_csv('https://raw.githubusercontent.com/ankit-rathi/Tradevesting_v1/main/data/myScreenerDB.csv')
  return myscreen_df

# function to fetch momentum data
def get_myinvmt_df():
  myinvmt_df = pd.read_csv('https://raw.githubusercontent.com/ankit-rathi/Tradevesting_v1/main/data/myInvestments.csv')
  return myinvmt_df

# function to get the stock ids
def get_stock_ids(df_pf):
  stock_n100 = df_pf['Symbol'].unique()

  exclude = ['CADILAHC','MMTC', 'MASFIN']

  stock_ids = df_pf[~df_pf['Symbol'].isin(exclude) ]['Symbol'].unique()

  #mypf = mypf[mypf.Forecast.notnull()]
  #stock_ids = mypf['Symbol'].unique()

  #stock_ids.sort()
  return stock_ids

# get features from screener data
def get_screener_features():
  myscreen_df = get_myscreen_df()
  cols = ['Symbol', 'EPS', 'MedPE', 'ROCE%', 'ROE%', 'CapType']
  return myscreen_df[cols]

# get relative strength
def get_relative_strength(stock_list):

    # Dictionary to store stock tickers and their corresponding percentage price change
    stock_changes = {}

    # Loop through each stock and fetch its price data
    for stock in stock_list:
        try:
            # Download the stock data for the given date range
            stock_data = yfin.Ticker(stock + '.NS').history(period='1mo', interval='1d')[map(str.title, ['open', 'close', 'low', 'high', 'volume'])]

            # Calculate the percentage change for the stock
            if len(stock_data) > 0:
                start_price = stock_data['Close'].iloc[0]
                end_price = stock_data['Close'].iloc[-1]
                percent_change = round(((end_price - start_price) / start_price) * 100, 2)
                stock_changes[stock] = percent_change
            else:
                stock_changes[stock] = np.nan  # If no data is available, set to NaN

        except Exception as e:
            print(f"Error fetching data for {stock}: {e}")
            stock_changes[stock] = np.nan

    # Create a DataFrame with stock tickers and their percentage changes
    df = pd.DataFrame(list(stock_changes.items()), columns=['Symbol', 'Percent_Change'])

    # Drop any stocks with missing data (NaN values)
    df = df.dropna()

    # Calculate the percentile rank based on percentage change
    df['RSP'] = round(df['Percent_Change'].rank(pct=True) * 100, 2)
    cols = ['Symbol', 'RSP']
    df = df[cols]
    # Sort by percentile rank (optional)
    df = df.sort_values(by='RSP', ascending=False).reset_index(drop=True)

    return df

In [6]:
# function to get stock technicals
def stock_prec_dev(stock_symbol):
    #stock_symbol = 'ULTRACEMCO.NS'
    short_window = 20
    mid_window = 50
    long_window = 200
    moving_avg = 'SMA'

    start = datetime.datetime(*map(int, start_date.split('-')))
    end = datetime.datetime(*map(int, end_date.split('-')))

    stock_df = yfin.Ticker(stock_symbol + '.NS').history(period='max', interval='1d')[map(str.title, ['open', 'close', 'low', 'high', 'volume'])]

    stock_df['Max'] = round(max(stock_df['Close']),2)
    stock_df = stock_df[(stock_df.index <= end_date) & (stock_df.index >= start_date)]
    stock_df['200_SMA'] = round(stock_df['Close'].rolling(window = 200, min_periods = 1).mean(),0)
    stock_df['Dev%_200'] = round((stock_df['Close'] - stock_df['200_SMA'])*100/stock_df['200_SMA'],2)
    stock_df.dropna(axis = 0, inplace = True) # remove any null rows

    stock_df['20_SMA'] = stock_df['Close'].rolling(window=20).mean()
    stock_df['50_SMA'] = stock_df['Close'].rolling(window=50).mean()
    stock_df['Symbol'] = stock_symbol

    stock_df['Close'] = round(stock_df['Close'],2)
    stock_df['Min'] = round(min(stock_df['Close']),2)
    stock_df['RSI_14'] = ta.momentum.RSIIndicator(close=stock_df['Close'], window=14).rsi()
    stock_df['RSI_14'] = round(stock_df['RSI_14'],0)
    stock_df['Prev_Close'] = stock_df['Close'].shift(1)
    stock_df.drop(['Open', 'Low', 'High', 'Volume'], axis=1, inplace=True)
    stock_df = stock_df.tail(1)

    max_SMA = max(stock_df['20_SMA'].item(), stock_df['50_SMA'].item(), stock_df['200_SMA'].item())
    min_SMA = min(stock_df['20_SMA'].item(), stock_df['50_SMA'].item(), stock_df['200_SMA'].item())
    ABS_Spread = max_SMA - min_SMA
    stock_df['Spread%'] = round((ABS_Spread / stock_df['200_SMA'].item()) * 100,2)

    return stock_df

# function to compute stock attributes
def get_common_features(stock_ids, df_mypf):

  df_prec_dev = pd.DataFrame()
  df_tmp = get_screener_features()
  df_rs = get_relative_strength(stock_ids)

  for stock_id in stock_ids:
      tmp = stock_prec_dev(stock_id)
      tmp = tmp.reset_index()
      df_prec_dev = pd.concat([df_prec_dev, tmp], ignore_index = True)
  df_prec_dev = pd.merge(df_prec_dev, df_mypf, on= 'Symbol')
  df_prec_dev = pd.merge(df_prec_dev, df_tmp, on= 'Symbol', how='left')
  df_prec_dev = pd.merge(df_prec_dev, df_rs, on= 'Symbol', how='left')
  #print(df_prec_dev.columns)
  df_prec_dev['Curr_PE'] = round(df_prec_dev['Close']/df_prec_dev['EPS'],1)
  df_prec_dev['Dev%_PE'] = round((df_prec_dev['Curr_PE'] - df_prec_dev['MedPE'])*100/df_prec_dev['MedPE'],2)
  df_prec_dev['Conviction'] = df_prec_dev['Conviction'] + '-' + df_prec_dev['CapType']
  return df_prec_dev

# function to arrange stock features
def arrange_features(df_stocks, common_cols, diff_cols):
  df_stocks_common = df_stocks[common_cols].drop_duplicates()
  df_stocks_diff = df_stocks[diff_cols]
  df_stocks_diff['Investment'] = df_stocks_diff['AvgCost'] * df_stocks_diff['Shares']
  df_stocks_diff = df_stocks_diff.groupby(['Symbol'])[['Shares', 'Investment']].aggregate(['sum']).reset_index()
  df_stocks_diff.columns = ['Symbol', 'Shares', 'Investment']
  df_stocks_diff['AvgCost'] = round(df_stocks_diff['Investment']/df_stocks_diff['Shares'],2)
  df_stocks = pd.merge(df_stocks_diff, df_stocks_common, on='Symbol')
  return df_stocks

# plot fact distribution across dimension
def plot_pie_chart(df, dimension, fact):
  # grouping the data by category and calculating the sum of fact for each type
  grouped_data = df.groupby(dimension)[fact].sum()

  # sorting the grouped data in descending order
  grouped_data = grouped_data.sort_values(ascending=False)

  # creating a pie chart
  grouped_data.plot.pie(autopct='%1.1f%%', startangle=90, figsize=(6, 6))

  # adding a title and displaying the plot
  plt.title(f'{dimension} {fact} Distribution')
  plt.ylabel('')  # To hide the y-label
  plt.show()

In [7]:
# function to get portfolio features

def get_portfolio_features(df_common_features):

  print_date_time()
  print('-------------------')

  #df_common_features["Target"] = df_common_features["Target"].fillna(df_common_features["Max"])
  df_common_features['NTT'] = np.where(df_common_features['Strategy']== 'NTT', df_common_features["Target"], df_common_features['Max'])
  df_common_features['LTT'] = np.where(df_common_features['Strategy']== 'BTT', df_common_features["Target"], df_common_features['Max'])
  df_common_features['BOL'] = df_common_features['Min']

  tmp_df = df_common_features[df_common_features['Symbol'].isin(mypf_df[mypf_df['InPortfolio'] != 'NA'].Symbol.values)]
  print('qualified stocks: '+str(len(tmp_df['Symbol'].unique())))
  tmp_df1 = tmp_df[tmp_df['LatestQtr'] == 1]
  print('with latest results: '+str(len(tmp_df1['Symbol'].unique())))
  tmp_df1 = tmp_df1[tmp_df1['StarStock'] == 1]
  print('still star stocks: '+str(len(tmp_df1['Symbol'].unique())))
  tmp_df['Investment'] = tmp_df['AvgCost'] * tmp_df['Shares']
  tmp_df['Current'] = round(tmp_df['Close'] * tmp_df['Shares'],0)
  tmp_df['Previous'] = tmp_df['Prev_Close'] * tmp_df['Shares']
  tmp_df['EstimatedST'] = tmp_df['NTT'] * tmp_df['Shares']
  tmp_df['EstimatedLT'] = tmp_df['LTT'] * tmp_df['Shares']
  tmp_df['Current P/L'] = round((tmp_df['Current'] - tmp_df['Investment']),0)
  tmp_df['Today P/L%'] = round((tmp_df['Current'] - tmp_df['Previous'])*100/tmp_df['Previous'],2)
  tmp_df['Current P/L%'] = round((tmp_df['Current'] - tmp_df['Investment'])*100/tmp_df['Investment'],2)
  tmp_df['EstimatedST P/L%'] = round((tmp_df['EstimatedST'] - tmp_df['Investment'])*100/tmp_df['Investment'],2)
  tmp_df['EstimatedLT P/L%'] = round((tmp_df['EstimatedLT'] - tmp_df['Investment'])*100/tmp_df['Investment'],2)
  tmp_df['NTT%'] = round((tmp_df['NTT'] - tmp_df['Close'])*100/tmp_df['Close'],2)
  tmp_df['LTT%'] = round((tmp_df['LTT'] - tmp_df['Close'])*100/tmp_df['Close'],2)
  tmp_df['Gained%'] = round((tmp_df['Close'] - tmp_df['BOL'])*100/tmp_df['BOL'],2)
  investment = round(sum(tmp_df['AvgCost']*tmp_df['Shares']),0)
  current = round(sum(tmp_df['Close']*tmp_df['Shares']),0)
  tmp_df['InitAlloc%'] = round(tmp_df['Investment']*100/investment,2)
  tmp_df['CurrAlloc%'] = round(tmp_df['Current']*100/current,2)
  tmp_df['FTT'] = tmp_df['LTT']
  tmp_df.loc[tmp_df['Strategy'] == 'NTT', 'FTT'] = tmp_df['NTT']
  tmp_df['FTT%'] = tmp_df['LTT%']
  tmp_df.loc[tmp_df['Strategy'] == 'NTT', 'FTT%'] = tmp_df['NTT%']
  tmp_df['FTT Amt'] = round(tmp_df['FTT%'] * tmp_df['Current']/100,0)
  tmp_df['OTT%'] = round((tmp_df['FTT'] - tmp_df['AvgCost'])*100/tmp_df['AvgCost'],2)
  tmp_df['RRR Ind'] = round(tmp_df['Current P/L']/tmp_df['FTT Amt'],2)
  tmp_df['Risk Ind'] = round(tmp_df['Current P/L%']*tmp_df['CurrAlloc%'],0)

  return tmp_df

# function to print portfolio features
def print_portfolio_stats(df_portfolio_features, myinvmt_df):
  from pyxirr import xirr

  total_booked_amt, reserve_amt, cy_booked_amt, py_booked_amt = get_amt()

  dates = myinvmt_df['Date'].values
  dates = np.append(dates, datetime.date.today().strftime('%d-%b-%y'))
  investment = myinvmt_df['Investment'].values
  dates= pd.to_datetime(dates)

  current = round(sum(df_portfolio_features['Close']*df_portfolio_features['Shares']),0) + reserve_amt
  investment_xirr = np.append(investment, current)
  cagr = round(xirr(pd.DataFrame({"dates": dates, "amounts": investment_xirr}))*100,2)

  investment = -sum(investment)
  invested = round(sum(df_portfolio_features['AvgCost']*df_portfolio_features['Shares']),0) + reserve_amt
  previous = round(sum(df_portfolio_features['Prev_Close']*df_portfolio_features['Shares']),0) + reserve_amt
  cy_invested = investment + py_booked_amt

  today_pnl_amount = current-previous
  today_pnl_percentage = round((current-previous)*100/previous,2)

  curr_pnl_amount = current-invested
  curr_pnl_percentage = round((curr_pnl_amount)*100/(cy_invested),2)

  cy_pnl_amount = cy_booked_amt + curr_pnl_amount
  cy_pnl_percentage = round((cy_pnl_amount)*100/cy_invested,2)

  overall_pnl_amount = total_booked_amt + curr_pnl_amount
  overall_pnl_percentage = round((overall_pnl_amount)*100/investment,2)

  estimate_st = round(sum(df_portfolio_features['FTT']*df_portfolio_features['Shares']),0)  + reserve_amt
  est_st_pnl_amount = estimate_st-current
  est_st_pnl_percentage = round((est_st_pnl_amount)*100/current,2)

  estimate_lt = round(sum(df_portfolio_features['LTT']*df_portfolio_features['Shares']),0)  + reserve_amt
  est_lt_pnl_amount = estimate_lt-current
  est_lt_pnl_percentage = round((est_lt_pnl_amount)*100/current,2)

  total_profit = round(sum(df_portfolio_features[df_portfolio_features['Current P/L%'] > 0]['Current']) - sum(df_portfolio_features[df_portfolio_features['Current P/L%'] > 0]['Investment']),0)
  total_loss = round(sum(df_portfolio_features[df_portfolio_features['Current P/L%'] < 0]['Current']) - sum(df_portfolio_features[df_portfolio_features['Current P/L%'] < 0]['Investment']),0)

  cy_booked_percentage = round((cy_booked_amt)*100/current,2)
  py_booked_percentage = round((py_booked_amt)*100/investment,2)
  total_booked_percentage = round((total_booked_amt)*100/investment,2)

  print('-------------------')
  print('Initial Investment: ', format_amt(investment))
  print('CY Investment: ', format_amt(cy_invested))
  print('Reserve: ', format_amt(reserve_amt))
  print('Current: ',  format_amt(current))
  print('-------------------')
  print('Today PnL: '+ '{} ({}%)'.format(format_amt(today_pnl_amount), today_pnl_percentage))
  print('Current PnL: '+ '{} ({}%)'.format(format_amt(curr_pnl_amount), curr_pnl_percentage))
  print('CY Booked + Current PnL: '+ '{} ({}%)'.format(format_amt(cy_pnl_amount), cy_pnl_percentage))
  print('-------------------')
  print('Total profit: ', format_amt(total_profit))
  print('Total loss: ', format_amt(total_loss))
  print('-------------------')
  print('Total Booked + Current PnL: '+ '{} ({}%)'.format(format_amt(overall_pnl_amount), overall_pnl_percentage))
  print('Total Booked PnL: '+ '{} ({}%)'.format(format_amt(total_booked_amt), total_booked_percentage))
  print('Curr Year Booked PnL: '+ '{} ({}%)'.format(format_amt(cy_booked_amt), cy_booked_percentage))
  print('Prev Year Booked PnL: '+ '{} ({}%)'.format(format_amt(py_booked_amt), py_booked_percentage))
  print('===================')
  print('Est FTT: ',  format_amt(estimate_st))
  print('Est FTT PnL: '+ '{} ({}%)'.format(format_amt(est_st_pnl_amount), est_st_pnl_percentage))

  print('===================')
  print('Deployed: ', format_amt(investment))

  print('Current: ', format_amt(current))

  print('CAGR/XIRR %: '+'{}%'.format(cagr))

In [8]:
# get start and end date
start_date, end_date = get_start_end_date()

# get portfolio and prospects data
mypfs_df = get_mypfs_df()
mypps_df = get_mypps_df()
myinvmt_df = get_myinvmt_df()

# merge above datasets
mypf_df = pd.merge(mypfs_df, mypps_df, on="Symbol")

# seggregate dm and sv portfolio
dm_pf = mypf_df[mypf_df['InPortfolio'] == 'DM']
sv_pf = mypf_df[mypf_df['InPortfolio'] == 'SV']

# build portfolio stock dataframe
dm_stocks = get_stock_ids(dm_pf)
sv_stocks = get_stock_ids(sv_pf)
df_stocks = pd.concat([dm_pf,sv_pf], ignore_index = True)

# arrange common and diff stock features
common_cols = ['Symbol', 'Target', 'Criteria', 'Strategy', 'CumlRnk', 'LatestQtr', 'StarStock', 'Conviction', 'Category', 'InFolio', 'XIRR', 'MBQ']
diff_cols = ['Symbol', 'AvgCost', 'Shares']
df_stocks = arrange_features(df_stocks, common_cols, diff_cols)

# get common features
stock_ids = df_stocks['Symbol'].values
df_common_features = get_common_features(stock_ids, df_stocks)

df_common_features.reset_index(drop=True, inplace=True)
df_common_features.drop(['Date'], axis=1, inplace=True)
# get and print portfolio features
df_portfolio_features = get_portfolio_features(df_common_features)

print_portfolio_stats(df_portfolio_features, myinvmt_df)

df = df_portfolio_features
#plot_pie_chart(df, 'CapType', 'Current')
list_ox40n = list(df[df['MBQ'].str.contains('OX40N', na=False)]['Symbol'].values)

Run date time (IST): 2026-08-07 14:02:03
-------------------
qualified stocks: 88
with latest results: 30
still star stocks: 19
-------------------
Initial Investment:  1.46 C
CY Investment:  1.89 C
Reserve:  2.24 L
Current:  1.62 C
-------------------
Today PnL: -46.65 K (-0.29%)
Current PnL: -30.59 L (-16.19%)
CY Booked + Current PnL: -26.37 L (-13.96%)
-------------------
Total profit:  3.58 L
Total loss:  -34.17 L
-------------------
Total Booked + Current PnL: 16.50 L (11.29%)
Total Booked PnL: 47.09 L (32.24%)
Curr Year Booked PnL: 4.22 L (2.61%)
Prev Year Booked PnL: 42.87 L (29.35%)
===================
Est FTT:  2.67 C
Est FTT PnL: 1.05 C (65.13%)
===================
Deployed:  1.46 C
Current:  1.62 C
CAGR/XIRR %: 4.64%

In [9]:
# top 5 near their targets
cols = ['Symbol', 'Today P/L%', 'Current P/L%', 'FTT%', 'OTT%', 'FTT Amt', 'Current P/L', 'Current', 'FTT', 'Dev%_PE', 'RSI_14','Conviction', 'Spread%',  'CumlRnk', 'RRR Ind', 'CurrAlloc%', 'Gained%', 'Criteria', 'Strategy', 'Category']
df_tmp = df_portfolio_features[~df_portfolio_features['Symbol'].isin(['ENRIN','BLUSPRING','DIGITIDE'])]
df_tmp = df_tmp.sort_values(by = 'FTT Amt', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
55,MEDANTA,1.09,24.89,1.78,27.12,3924.0,43943.0,220460.0,1486.00,21.12,68.0,X-SC,15.39,87.0,11.20,1.38,51.91,XY24,NTT,HEALTHCARE
79,TTKPRESTIG,-0.72,-18.92,23.46,0.09,19168.0,-19072.0,81705.0,770.00,89.54,47.0,M-SC,13.78,250.0,-0.99,0.51,47.06,OX40N,NTT,DURABLES
52,M&M,2.69,10.44,7.59,18.82,20175.0,25129.0,265810.0,3762.88,-3.65,69.0,X-LC,5.72,25.0,1.25,1.67,20.58,X40N,ATH,AUTO
80,UNITDSPR,-0.23,11.40,8.41,20.77,21936.0,26694.0,260838.0,1644.00,-1.23,69.0,X-MC,7.12,64.0,1.22,1.64,25.38,X40N,NTT,BREWERIES
69,SIS,0.75,-0.37,21.72,21.26,24026.0,-413.0,110619.0,528.00,2640.93,54.0,H-SC,22.81,168.0,-0.02,0.69,64.47,OX40N,NTT,MISC

In [10]:
# top 5 today
df_tmp = df_portfolio_features.sort_values(by = 'Today P/L%', ascending=False)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
75,TCS,3.16,-28.13,72.82,24.20,242448.0,-130331.0,332942.0,4230.71,-39.04,63.0,X-LC,15.71,2.0,-0.54,2.09,24.16,X40,ATH,IT
82,VALIANTORG,2.98,-40.36,191.99,74.15,187344.0,-66025.0,97580.0,838.00,-275.30,59.0,H-SC,4.08,145.0,-0.35,0.61,45.21,XR,NTT,CHEMICALS
43,INDIGOPNTS,2.73,-20.40,25.65,0.02,35642.0,-35605.0,138954.0,1408.00,112.05,62.0,M-SC,4.65,222.0,-1.00,0.87,57.65,OX40N,NTT,PAINTS
52,M&M,2.69,10.44,7.59,18.82,20175.0,25129.0,265810.0,3762.88,-3.65,69.0,X-LC,5.72,25.0,1.25,1.67,20.58,X40N,ATH,AUTO
62,RELAXO,2.38,-44.82,176.02,52.31,140987.0,-65063.0,80097.0,1176.00,-41.24,61.0,X-SC,11.09,92.0,-0.46,0.50,79.09,X40N,NTT,FOOTWEAR

In [11]:
# bottom 5 today
df_tmp = df_portfolio_features.sort_values(by = 'Today P/L%', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
18,COFFEEDAY,-5.04,-45.21,146.91,35.27,91390.0,-51341.0,62208.0,80.00,-57.75,53.0,L-SC,5.65,266.0,-0.56,0.39,53.41,XR,NTT,HOTELS
16,CERA,-4.55,-21.07,56.96,23.89,79083.0,-37063.0,138840.0,9475.00,-23.87,44.0,H-SC,12.76,153.0,-0.47,0.87,34.96,OX40N,NTT,CERAMICS
28,GODREJCP,-3.33,-5.27,41.06,33.64,97065.0,-13139.0,236398.0,1469.04,-1.98,44.0,X-LC,5.19,32.0,-0.14,1.48,6.27,X40N,ATH,FMCG
29,GREENPANEL,-3.00,-48.45,177.65,43.14,167673.0,-88694.0,94384.0,537.00,111.24,49.0,M-SC,11.31,225.0,-0.53,0.59,13.67,XY24,NTT,MISC
66,SFL,-2.83,-33.35,90.01,26.63,157298.0,-87462.0,174756.0,1287.00,32.32,33.0,M-SC,24.58,242.0,-0.56,1.10,45.85,XY24,NTT,MISC

In [12]:
# top 5 to exit based on CumlRnk
df_tmp = df_portfolio_features[~df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])]
df_tmp = df_tmp[(df_tmp['Current P/L%'] > -1) & (df_tmp['Current P/L%'] < 1)].sort_values(by = 'CumlRnk', ascending=False)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
61,RECLTD,1.24,-0.92,21.86,20.74,44004.0,-1870.0,201300.0,446.0,9.37,57.0,M-MC,3.41,191.0,-0.04,1.26,21.34,XY25,NTT,FINANCE
69,SIS,0.75,-0.37,21.72,21.26,24026.0,-413.0,110619.0,528.0,2640.93,54.0,H-SC,22.81,168.0,-0.02,0.69,64.47,OX40N,NTT,MISC

In [13]:
# OX40N stocks to exit
df_tmp = df_portfolio_features[(df_portfolio_features['Symbol'].isin(list_ox40n))].sort_values(by = 'Current P/L%', ascending=False)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
25,FINCABLES,1.86,29.44,60.62,107.91,115853.0,43470.0,191114.0,1641.55,16.69,50.0,M-SC,17.60,220.0,0.38,1.20,43.78,OX40N,ATH,CABLES
69,SIS,0.75,-0.37,21.72,21.26,24026.0,-413.0,110619.0,528.00,2640.93,54.0,H-SC,22.81,168.0,-0.02,0.69,64.47,OX40N,NTT,MISC
79,TTKPRESTIG,-0.72,-18.92,23.46,0.09,19168.0,-19072.0,81705.0,770.00,89.54,47.0,M-SC,13.78,250.0,-0.99,0.51,47.06,OX40N,NTT,DURABLES
43,INDIGOPNTS,2.73,-20.40,25.65,0.02,35642.0,-35605.0,138954.0,1408.00,112.05,62.0,M-SC,4.65,222.0,-1.00,0.87,57.65,OX40N,NTT,PAINTS
16,CERA,-4.55,-21.07,56.96,23.89,79083.0,-37063.0,138840.0,9475.00,-23.87,44.0,H-SC,12.76,153.0,-0.47,0.87,34.96,OX40N,NTT,CERAMICS

In [14]:
# top 5 to book for rotation
df_tmp = df_portfolio_features[(df_portfolio_features['Current P/L%'] > 20) ].sort_values(by = 'CumlRnk', ascending=False)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
25,FINCABLES,1.86,29.44,60.62,107.91,115853.0,43470.0,191114.0,1641.55,16.69,50.0,M-SC,17.60,220.0,0.38,1.20,43.78,OX40N,ATH,CABLES
55,MEDANTA,1.09,24.89,1.78,27.12,3924.0,43943.0,220460.0,1486.00,21.12,68.0,X-SC,15.39,87.0,11.20,1.38,51.91,XY24,NTT,HEALTHCARE
58,QUESS,-0.64,27.25,36.66,73.90,49817.0,29097.0,135890.0,424.00,-31.68,59.0,X-SC,39.47,80.0,0.58,0.85,87.03,XY24,NTT,MISC

In [15]:
# top 5 to monitor for exit
df_tmp = df_portfolio_features[~df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])]
df_tmp = df_tmp[(df_tmp['Current P/L%'] > 0) ].sort_values(by = 'Dev%_PE', ascending=False)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
70,STARHEALTH,-0.64,10.30,33.51,47.26,103908.0,28957.0,310080.0,761.00,74.08,43.0,H-SC,17.61,173.0,0.28,1.95,34.07,XY24,NTT,INSURANCE
25,FINCABLES,1.86,29.44,60.62,107.91,115853.0,43470.0,191114.0,1641.55,16.69,50.0,M-SC,17.60,220.0,0.38,1.20,43.78,OX40N,ATH,CABLES
87,ZYDUSLIFE,0.24,17.13,15.69,35.51,38513.0,35891.0,245465.0,1285.01,1.80,47.0,H-MC,15.57,120.0,0.93,1.54,29.18,AR,ATH,PHARMA

In [16]:
# top 5 to book for rotation from weak conviction
df_tmp = df_portfolio_features[~df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])]
df_tmp = df_tmp[~df_tmp['Criteria'].isin(['XY25','XY24','X40', 'X40N'])].sort_values(by = 'RRR Ind', ascending=False)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
87,ZYDUSLIFE,0.24,17.13,15.69,35.51,38513.0,35891.0,245465.0,1285.01,1.80,47.0,H-MC,15.57,120.0,0.93,1.54,29.18,AR,ATH,PHARMA
25,FINCABLES,1.86,29.44,60.62,107.91,115853.0,43470.0,191114.0,1641.55,16.69,50.0,M-SC,17.60,220.0,0.38,1.20,43.78,OX40N,ATH,CABLES
69,SIS,0.75,-0.37,21.72,21.26,24026.0,-413.0,110619.0,528.00,2640.93,54.0,H-SC,22.81,168.0,-0.02,0.69,64.47,OX40N,NTT,MISC
3,ALKYLAMINE,-2.31,-19.29,138.57,92.54,112914.0,-19478.0,81485.0,4520.85,-13.57,57.0,H-SC,13.34,142.0,-0.17,0.51,54.73,SR,ATH,CHEMICALS
42,INDIAMART,-1.20,-24.61,166.51,100.92,154826.0,-30353.0,92983.0,4675.60,-66.02,35.0,H-SC,11.64,140.0,-0.20,0.58,0.65,AR,ATH,MISC

In [17]:
# top 5 to accumulate based on lowest RSI_14
df_tmp = df_portfolio_features[df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])].sort_values(by = 'RSI_14', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
34,HDFCBANK,-0.68,-10.93,47.13,31.05,123051.0,-32031.0,261089.0,1073.00,-25.96,34.0,X-LC,10.59,26.0,-0.26,1.64,1.34,X40,BTT,BANKS
57,PGHH,0.25,-36.27,107.14,32.01,145796.0,-77440.0,136080.0,17616.87,-56.92,36.0,X-MC,19.17,57.0,-0.53,0.85,0.33,X40,ATH,FMCG
83,VBL,-0.69,-10.64,51.81,35.66,162889.0,-37447.0,314397.0,669.42,-21.38,38.0,X-LC,7.75,13.0,-0.23,1.97,15.75,X40N,ATH,FMCG
20,DABUR,-0.45,-19.95,79.51,43.70,157893.0,-49485.0,198583.0,735.00,-27.41,38.0,X-MC,9.14,70.0,-0.31,1.25,1.05,XY24,BTT,FMCG
35,HDFCLIFE,-0.53,-7.46,50.37,39.15,116873.0,-18709.0,232028.0,811.41,-31.13,39.0,X-LC,15.97,31.0,-0.16,1.46,0.68,X40,ATH,INSURANCE

In [18]:
# top 5 to accumulate based on Spread and CumlRnk
df_tmp = df_portfolio_features[df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])]
df_tmp = df_tmp[(df_tmp['CumlRnk'] < 100)].sort_values(by = 'Spread%', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
19,COLPAL,-0.62,-23.46,82.73,39.86,166767.0,-61785.0,201580.0,3683.41,-7.42,43.0,X-MC,1.64,62.0,-0.37,1.27,14.02,XY25,ATH,FMCG
11,BERGEPAINT,-2.79,-2.33,28.30,25.32,71245.0,-5999.0,251750.0,680.00,-7.69,60.0,X-MC,2.08,68.0,-0.08,1.58,32.01,XY24,NTT,PAINTS
8,BAJAJHLDNG,-1.68,1.55,26.29,28.24,68346.0,3964.0,259969.0,14274.15,-6.72,63.0,X-LC,2.57,28.0,0.06,1.63,30.84,X40,ATH,FINANCE
23,DMART,-0.98,-5.12,38.51,31.42,113924.0,-15960.0,295830.0,5391.45,-21.12,40.0,X-LC,3.25,14.0,-0.14,1.86,6.75,X40N,ATH,FMCG
26,GILLETTE,-0.42,-9.47,43.29,29.72,99506.0,-24036.0,229860.0,10978.86,-30.50,44.0,X-SC,3.42,83.0,-0.24,1.44,5.63,X40,ATH,FMCG

In [19]:
# top 5 to accumulate based on lowest Gained%
df_tmp = df_portfolio_features[df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])].sort_values(by = 'Gained%', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
57,PGHH,0.25,-36.27,107.14,32.01,145796.0,-77440.0,136080.0,17616.87,-56.92,36.0,X-MC,19.17,57.0,-0.53,0.85,0.33,X40,ATH,FMCG
35,HDFCLIFE,-0.53,-7.46,50.37,39.15,116873.0,-18709.0,232028.0,811.41,-31.13,39.0,X-LC,15.97,31.0,-0.16,1.46,0.68,X40,ATH,INSURANCE
20,DABUR,-0.45,-19.95,79.51,43.70,157893.0,-49485.0,198583.0,735.00,-27.41,38.0,X-MC,9.14,70.0,-0.31,1.25,1.05,XY24,BTT,FMCG
34,HDFCBANK,-0.68,-10.93,47.13,31.05,123051.0,-32031.0,261089.0,1073.00,-25.96,34.0,X-LC,10.59,26.0,-0.26,1.64,1.34,X40,BTT,BANKS
47,ITC,-0.35,-21.40,58.65,24.70,183135.0,-85028.0,312250.0,452.00,-58.75,50.0,X-LC,11.32,1.0,-0.46,1.96,3.39,X40,NTT,FMCG

In [20]:
# top 5 to accumulate based on lowest CurrAlloc%
df_tmp = df_portfolio_features[df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])].sort_values(by = 'CurrAlloc%', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
10,BATAINDIA,-1.37,-53.55,191.09,35.20,114203.0,-68906.0,59764.0,2096.00,-21.59,61.0,X-SC,14.80,91.0,-0.60,0.38,20.07,X40,NTT,FOOTWEAR
62,RELAXO,2.38,-44.82,176.02,52.31,140987.0,-65063.0,80097.0,1176.00,-41.24,61.0,X-SC,11.09,92.0,-0.46,0.50,79.09,X40N,NTT,FOOTWEAR
58,QUESS,-0.64,27.25,36.66,73.90,49817.0,29097.0,135890.0,424.00,-31.68,59.0,X-SC,39.47,80.0,0.58,0.85,87.03,XY24,NTT,MISC
57,PGHH,0.25,-36.27,107.14,32.01,145796.0,-77440.0,136080.0,17616.87,-56.92,36.0,X-MC,19.17,57.0,-0.53,0.85,0.33,X40,ATH,FMCG
40,ICICIPRULI,-2.42,-16.59,56.19,30.28,92331.0,-32685.0,164320.0,787.27,-39.03,49.0,X-MC,13.71,78.0,-0.35,1.03,9.48,X40,ATH,INSURANCE

In [21]:
# top 5 to accumulate based on CumlRnk
df_tmp = df_portfolio_features.sort_values(by = 'CumlRnk', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
47,ITC,-0.35,-21.40,58.65,24.70,183135.0,-85028.0,312250.0,452.00,-58.75,50.0,X-LC,11.32,1.0,-0.46,1.96,3.39,X40,NTT,FMCG
75,TCS,3.16,-28.13,72.82,24.20,242448.0,-130331.0,332942.0,4230.71,-39.04,63.0,X-LC,15.71,2.0,-0.54,2.09,24.16,X40,ATH,IT
45,INFY,1.24,-16.04,67.20,40.38,212405.0,-60391.0,316079.0,1972.00,-36.87,63.0,X-LC,16.35,3.0,-0.28,1.98,19.70,X40,NTT,IT
77,TMPV,0.35,-17.55,73.14,42.75,250932.0,-73023.0,343084.0,600.00,-83.62,55.0,X-LC,5.39,4.0,-0.29,2.15,17.97,XY24,NTT,AUTO
33,HCLTECH,1.55,-9.32,36.71,23.97,103019.0,-28856.0,280630.0,1853.42,-7.78,69.0,X-LC,13.58,8.0,-0.28,1.76,32.42,X40,ATH,IT

In [22]:
# top 5 for average up
df_tmp = df_portfolio_features[(df_portfolio_features['Dev%_200'] > 5)].sort_values(by = 'CurrAlloc%', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
44,INDUSINDBK,-0.70,-25.50,78.38,32.89,45083.0,-19688.0,57519.0,1800.00,-371.01,52.0,L-MC,13.88,258.0,-0.44,0.36,41.81,XR,NTT,BANKS
62,RELAXO,2.38,-44.82,176.02,52.31,140987.0,-65063.0,80097.0,1176.00,-41.24,61.0,X-SC,11.09,92.0,-0.46,0.50,79.09,X40N,NTT,FOOTWEAR
3,ALKYLAMINE,-2.31,-19.29,138.57,92.54,112914.0,-19478.0,81485.0,4520.85,-13.57,57.0,H-SC,13.34,142.0,-0.17,0.51,54.73,SR,ATH,CHEMICALS
79,TTKPRESTIG,-0.72,-18.92,23.46,0.09,19168.0,-19072.0,81705.0,770.00,89.54,47.0,M-SC,13.78,250.0,-0.99,0.51,47.06,OX40N,NTT,DURABLES
12,BOSCH-HCIL,0.78,-27.35,37.64,-0.01,34948.0,-34957.0,92848.0,2282.00,18900.00,84.0,M-SC,3.88,231.0,-1.00,0.58,58.04,OX40N,BTT,AC

In [23]:
# top 5 RSP
df_tmp = df_portfolio_features.sort_values(by = 'RSP', ascending=False)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
12,BOSCH-HCIL,0.78,-27.35,37.64,-0.01,34948.0,-34957.0,92848.0,2282.00,18900.00,84.0,M-SC,3.88,231.0,-1.00,0.58,58.04,OX40N,BTT,AC
30,HAPPSTMNDS,0.46,-49.07,259.45,83.08,169369.0,-62885.0,65280.0,1466.54,-39.37,68.0,H-SC,10.38,152.0,-0.37,0.41,22.27,AR,ATH,IT
75,TCS,3.16,-28.13,72.82,24.20,242448.0,-130331.0,332942.0,4230.71,-39.04,63.0,X-LC,15.71,2.0,-0.54,2.09,24.16,X40,ATH,IT
33,HCLTECH,1.55,-9.32,36.71,23.97,103019.0,-28856.0,280630.0,1853.42,-7.78,69.0,X-LC,13.58,8.0,-0.28,1.76,32.42,X40,ATH,IT
5,ATULAUTO,-1.27,-1.07,47.14,45.57,91934.0,-2108.0,195024.0,844.00,4240.54,74.0,M-SC,8.57,248.0,-0.02,1.22,50.08,XY24,NTT,AUTO

In [24]:
# Top N allocation
df_tmp = df_portfolio_features.sort_values(by = 'CurrAlloc%', ascending=False)
top_n_values = [10, 25, 50]

sum_df = pd.DataFrame({
    'Top_N': top_n_values,
    'Sum_Alloc%': [df_tmp['CurrAlloc%'].head(n).sum() for n in top_n_values]
})

sum_df

   Top_N  Sum_Alloc%
0     10       19.69
1     25       44.63
2     50       76.83

In [25]:
# market-cap-wise allocation
df_tmp = df_portfolio_features[cols]
df_tmp.groupby(df_tmp['Conviction'].str[-2:])['CurrAlloc%'].sum().sort_values(ascending=False)

Conviction
SC    39.32
LC    37.69
MC    22.96
Name: CurrAlloc%, dtype: float64

In [26]:
# criteria-wise allocation
df_portfolio_features.groupby('Criteria')['CurrAlloc%'].sum().sort_values(ascending=False)

Criteria
X40      26.41
XY24     25.07
X40N     18.41
XR        9.10
XY25      7.28
OX40N     6.82
AR        6.03
SR        0.85
Name: CurrAlloc%, dtype: float64

In [27]:
# conviction-wise allocation
df_portfolio_features.groupby('Conviction')['CurrAlloc%'].sum().sort_values(ascending=False)

Conviction
X-LC    35.64
H-SC    19.23
X-MC    18.73
X-SC     9.91
M-SC     9.65
H-MC     2.61
M-MC     1.26
H-LC     1.23
M-LC     0.82
L-SC     0.53
L-MC     0.36
Name: CurrAlloc%, dtype: float64

In [28]:
# sector-wise stats
df_tmp = df_portfolio_features.groupby('Category')[['CurrAlloc%', 'Current', 'Current P/L', 'FTT Amt']].sum().sort_values(by=['Current', 'Current P/L'], ascending=False)
df_tmp['Current P/L%'] = round(df_tmp['Current P/L'] * 100 / df_tmp['Current'], 2)
df_tmp['FTT%'] = round(df_tmp['FTT Amt'] * 100 / df_tmp['Current'], 2)
cols = ['CurrAlloc%', 'Current P/L%', 'FTT%']
df_tmp[cols].sort_values(by=['CurrAlloc%'], ascending=False)

               CurrAlloc%  Current P/L%    FTT%
Category
FMCG                15.44        -21.22   64.87
IT                  11.23        -33.30   99.45
FINANCE              9.31        -14.98   63.31
AUTO                 8.43         -0.69   36.75
MISC                 6.84        -22.83   75.53
BANKS                6.07        -10.44   58.07
PHARMA               5.59          6.91   19.49
INSURANCE            5.53         -5.53   42.85
PAINTS               5.39        -14.81   34.39
ELECTRICAL           4.12         -7.67   45.37
HEALTHCARE           2.08         -7.90   36.06
AC                   1.79        -12.19   42.61
APPARELS             1.76          4.22   27.95
REFINERIES           1.70         -9.82   46.71
FOOTWEAR             1.68        -65.69  132.13
BREWERIES            1.64         10.23    8.41
DURABLES             1.52        -59.55   98.37
TRAVEL               1.47        -91.08  186.76
CERAMICS             1.34        -43.42   87.00
ENGINEERING          1.22        -24.98   82.14
CABLES               1.20         22.75   60.62
CHEMICALS            1.12        -47.75  167.68
CEMENT               1.03        -63.18  185.26
JEWELLERY            1.00       -101.79  171.91
ENTERTAINMENT        0.69        -76.95  182.48
TEXTILES             0.39        -47.51   89.57
HOTELS               0.39        -82.53  146.91

In [29]:
# money to be made criteria-wise
df_portfolio_features.groupby('Criteria')['FTT Amt'].agg(['sum', 'count']).sort_values(by='sum', ascending=False)

                sum  count
Criteria
XY24      3408096.0     20
X40       2018948.0     18
XR        1346707.0     13
X40N      1147250.0     12
AR        1072444.0      8
OX40N      704055.0     10
XY25       540042.0      5
SR         281466.0      2

In [30]:
# money to be made conviction-wise
df_portfolio_features.groupby('Conviction')['FTT Amt'].agg(['sum', 'count']).sort_values(by='sum', ascending=False)

                  sum  count
Conviction
H-SC        3288898.0     23
X-LC        2380448.0     20
X-MC        1472558.0     14
M-SC        1379534.0     14
X-SC        1221812.0      9
H-MC         282506.0      2
L-SC         206429.0      2
M-LC         161797.0      1
L-MC          45083.0      1
M-MC          44004.0      1
H-LC          35939.0      1

In [31]:
# money to be made criteria and conviction-wise
df_portfolio_features.groupby(['Conviction', 'Criteria'])['FTT Amt'].agg(['sum', 'count']).sort_values(by='sum', ascending=False)

                           sum  count
Conviction Criteria
X-LC       X40       1162503.0      9
H-SC       XY24       984428.0      5
           AR         922007.0      5
M-SC       XY24       822664.0      6
H-SC       XR         802922.0      7
X-SC       XY24       711108.0      4
X-MC       X40        642736.0      7
X-LC       X40N       502763.0      6
           XY24       416765.0      2
X-MC       X40N       347492.0      3
H-SC       OX40N      298075.0      4
X-SC       X40N       296995.0      3
M-SC       OX40N      290941.0      5
H-SC       SR         281466.0      2
X-MC       XY25       253192.0      2
H-MC       XY24       243993.0      1
X-LC       XY25       242846.0      2
X-MC       XY24       229138.0      2
X-SC       X40        213709.0      2
M-SC       XR         189944.0      2
M-LC       XR         161797.0      1
L-SC       OX40N      115039.0      1
           XR          91390.0      1
M-SC       AR          75985.0      1
X-LC       XR          55571.0      1
L-MC       XR          45083.0      1
M-MC       XY25        44004.0      1
H-MC       AR          38513.0      1
H-LC       AR          35939.0      1

In [32]:
# notebook execution time

end_time = time.time()
execution_time = round(end_time - start_time, 0)
print(f"Notebook execution time: {execution_time} seconds")

Notebook execution time: 26.0 seconds