<a href="https://colab.research.google.com/github/ankit-rathi/Quantvesting_v2/blob/main/myStocks_Portfolio_Analysis.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
'''
!pip install pandas==2.2.2 -qq
!pip install pyxirr -qq
!pip install ta -qq
!pip install yfinance==0.2.59 -qq
'''

'\n!pip install pandas==2.2.2 -qq\n!pip install pyxirr -qq\n!pip install ta -qq\n!pip install yfinance==0.2.59 -qq\n'

In [2]:
# import libraries

import numpy as np
import pandas as pd
import datetime
import warnings
warnings.filterwarnings('ignore')
import yfinance as yfin
import ta
import matplotlib.pyplot as plt
import requests

In [3]:
# notebook start time
import time
import datetime
import pytz

start_time = time.time()

# function to print date timestamp
def print_date_time():
  tz_NY = pytz.timezone('Asia/Kolkata')
  datetime_NY = datetime.datetime.now(tz_NY)
  print("Run date time (IST):", datetime_NY.strftime("%Y-%m-%d %H:%M:%S"))

In [4]:
# function to get booked and reserved amount
def get_amt():
  # fetch the JSON data from the URL
  url = "https://raw.githubusercontent.com/ankit-rathi/Tradevesting_v1/main/data/myPortfolioAmts.json"
  response = requests.get(url)
  pf_amts = response.json()  # parse the JSON data

  # extract values from the JSON
  py_booked_amt_dm = pf_amts["py_booked_amt_dm"]
  py_booked_amt_sv = pf_amts["py_booked_amt_sv"]
  cy_booked_amt_dm = pf_amts["cy_booked_amt_dm"]
  cy_booked_amt_sv = pf_amts["cy_booked_amt_sv"]
  reserve_amt_dm = pf_amts["reserve_amt_dm"]
  reserve_amt_sv = pf_amts["reserve_amt_sv"]

  # perform calculations
  py_booked_amt = py_booked_amt_dm + py_booked_amt_sv
  cy_booked_amt = cy_booked_amt_dm + cy_booked_amt_sv
  reserve_amt = reserve_amt_dm + reserve_amt_sv
  total_booked_amt = py_booked_amt + cy_booked_amt

  return total_booked_amt, reserve_amt, cy_booked_amt, py_booked_amt

gen_output = 0

In [5]:
# function to format the amount
def format_amt(number):
    abs_number = abs(number)

    if abs_number >= 1_00_00_000:  # Crores
        formatted_amt = f"{number / 1_00_00_000:.2f} C"
    elif abs_number >= 1_00_000:  # Lakhs
        formatted_amt = f"{number / 1_00_000:.2f} L"
    elif abs_number >= 1_000:  # Thousands
        formatted_amt = f"{number / 1_000:.2f} K"
    else:
        formatted_amt = f"{number:.2f}"

    return formatted_amt

# function to set start and end date
def get_start_end_date():
  start_date = (datetime.date.today() + datetime.timedelta(days=-365)).strftime('%Y-%m-%d')
  end_date = (datetime.date.today() + datetime.timedelta(days=1)).strftime('%Y-%m-%d')
  return start_date, end_date

# function to fetch my portfolio csv
def get_mypfs_df():
  mypfs_df = pd.read_csv('https://raw.githubusercontent.com/ankit-rathi/Tradevesting_v1/main/data/myPortfolioStocks.csv')
  return mypfs_df

# function to fetch my prospects csv
def get_mypps_df():
  mypps_df = pd.read_csv('https://raw.githubusercontent.com/ankit-rathi/Tradevesting_v1/main/data/myProspectsScrips.csv')
  return mypps_df

# function to fetch screener data
def get_myscreen_df():
  myscreen_df = pd.read_csv('https://raw.githubusercontent.com/ankit-rathi/Tradevesting_v1/main/data/myScreenerDB.csv')
  return myscreen_df

# function to fetch momentum data
def get_myinvmt_df():
  myinvmt_df = pd.read_csv('https://raw.githubusercontent.com/ankit-rathi/Tradevesting_v1/main/data/myInvestments.csv')
  return myinvmt_df

# function to get the stock ids
def get_stock_ids(df_pf):
  stock_n100 = df_pf['Symbol'].unique()

  exclude = ['CADILAHC','MMTC', 'MASFIN']

  stock_ids = df_pf[~df_pf['Symbol'].isin(exclude) ]['Symbol'].unique()

  #mypf = mypf[mypf.Forecast.notnull()]
  #stock_ids = mypf['Symbol'].unique()

  #stock_ids.sort()
  return stock_ids

# get features from screener data
def get_screener_features():
  myscreen_df = get_myscreen_df()
  cols = ['Symbol', 'EPS', 'MedPE', 'ROCE%', 'ROE%', 'CapType']
  return myscreen_df[cols]

# get relative strength
def get_relative_strength(stock_list):

    # Dictionary to store stock tickers and their corresponding percentage price change
    stock_changes = {}

    # Loop through each stock and fetch its price data
    for stock in stock_list:
        try:
            # Download the stock data for the given date range
            stock_data = yfin.Ticker(stock + '.NS').history(period='1mo', interval='1d')[map(str.title, ['open', 'close', 'low', 'high', 'volume'])]

            # Calculate the percentage change for the stock
            if len(stock_data) > 0:
                start_price = stock_data['Close'].iloc[0]
                end_price = stock_data['Close'].iloc[-1]
                percent_change = round(((end_price - start_price) / start_price) * 100, 2)
                stock_changes[stock] = percent_change
            else:
                stock_changes[stock] = np.nan  # If no data is available, set to NaN

        except Exception as e:
            print(f"Error fetching data for {stock}: {e}")
            stock_changes[stock] = np.nan

    # Create a DataFrame with stock tickers and their percentage changes
    df = pd.DataFrame(list(stock_changes.items()), columns=['Symbol', 'Percent_Change'])

    # Drop any stocks with missing data (NaN values)
    df = df.dropna()

    # Calculate the percentile rank based on percentage change
    df['RSP'] = round(df['Percent_Change'].rank(pct=True) * 100, 2)
    cols = ['Symbol', 'RSP']
    df = df[cols]
    # Sort by percentile rank (optional)
    df = df.sort_values(by='RSP', ascending=False).reset_index(drop=True)

    return df

In [6]:
# function to get stock technicals
def stock_prec_dev(stock_symbol):
    #stock_symbol = 'ULTRACEMCO.NS'
    short_window = 20
    mid_window = 50
    long_window = 200
    moving_avg = 'SMA'

    start = datetime.datetime(*map(int, start_date.split('-')))
    end = datetime.datetime(*map(int, end_date.split('-')))

    stock_df = yfin.Ticker(stock_symbol + '.NS').history(period='max', interval='1d')[map(str.title, ['open', 'close', 'low', 'high', 'volume'])]

    stock_df['Max'] = round(max(stock_df['Close']),2)
    stock_df = stock_df[(stock_df.index <= end_date) & (stock_df.index >= start_date)]
    stock_df['200_SMA'] = round(stock_df['Close'].rolling(window = 200, min_periods = 1).mean(),0)
    stock_df['Dev%_200'] = round((stock_df['Close'] - stock_df['200_SMA'])*100/stock_df['200_SMA'],2)
    stock_df.dropna(axis = 0, inplace = True) # remove any null rows

    stock_df['20_SMA'] = stock_df['Close'].rolling(window=20).mean()
    stock_df['50_SMA'] = stock_df['Close'].rolling(window=50).mean()
    stock_df['Symbol'] = stock_symbol

    stock_df['Close'] = round(stock_df['Close'],2)
    stock_df['Min'] = round(min(stock_df['Close']),2)
    stock_df['RSI_14'] = ta.momentum.RSIIndicator(close=stock_df['Close'], window=14).rsi()
    stock_df['RSI_14'] = round(stock_df['RSI_14'],0)
    stock_df['Prev_Close'] = stock_df['Close'].shift(1)
    stock_df.drop(['Open', 'Low', 'High', 'Volume'], axis=1, inplace=True)
    stock_df = stock_df.tail(1)

    max_SMA = max(stock_df['20_SMA'].item(), stock_df['50_SMA'].item(), stock_df['200_SMA'].item())
    min_SMA = min(stock_df['20_SMA'].item(), stock_df['50_SMA'].item(), stock_df['200_SMA'].item())
    ABS_Spread = max_SMA - min_SMA
    stock_df['Spread%'] = round((ABS_Spread / stock_df['200_SMA'].item()) * 100,2)

    return stock_df

# function to compute stock attributes
def get_common_features(stock_ids, df_mypf):

  df_prec_dev = pd.DataFrame()
  df_tmp = get_screener_features()
  df_rs = get_relative_strength(stock_ids)

  for stock_id in stock_ids:
      tmp = stock_prec_dev(stock_id)
      tmp = tmp.reset_index()
      df_prec_dev = pd.concat([df_prec_dev, tmp], ignore_index = True)
  df_prec_dev = pd.merge(df_prec_dev, df_mypf, on= 'Symbol')
  df_prec_dev = pd.merge(df_prec_dev, df_tmp, on= 'Symbol', how='left')
  df_prec_dev = pd.merge(df_prec_dev, df_rs, on= 'Symbol', how='left')
  #print(df_prec_dev.columns)
  df_prec_dev['Curr_PE'] = round(df_prec_dev['Close']/df_prec_dev['EPS'],1)
  df_prec_dev['Dev%_PE'] = round((df_prec_dev['Curr_PE'] - df_prec_dev['MedPE'])*100/df_prec_dev['MedPE'],2)
  df_prec_dev['Conviction'] = df_prec_dev['Conviction'] + '-' + df_prec_dev['CapType']
  return df_prec_dev

# function to arrange stock features
def arrange_features(df_stocks, common_cols, diff_cols):
  df_stocks_common = df_stocks[common_cols].drop_duplicates()
  df_stocks_diff = df_stocks[diff_cols]
  df_stocks_diff['Investment'] = df_stocks_diff['AvgCost'] * df_stocks_diff['Shares']
  df_stocks_diff = df_stocks_diff.groupby(['Symbol'])[['Shares', 'Investment']].aggregate(['sum']).reset_index()
  df_stocks_diff.columns = ['Symbol', 'Shares', 'Investment']
  df_stocks_diff['AvgCost'] = round(df_stocks_diff['Investment']/df_stocks_diff['Shares'],2)
  df_stocks = pd.merge(df_stocks_diff, df_stocks_common, on='Symbol')
  return df_stocks

# plot fact distribution across dimension
def plot_pie_chart(df, dimension, fact):
  # grouping the data by category and calculating the sum of fact for each type
  grouped_data = df.groupby(dimension)[fact].sum()

  # sorting the grouped data in descending order
  grouped_data = grouped_data.sort_values(ascending=False)

  # creating a pie chart
  grouped_data.plot.pie(autopct='%1.1f%%', startangle=90, figsize=(6, 6))

  # adding a title and displaying the plot
  plt.title(f'{dimension} {fact} Distribution')
  plt.ylabel('')  # To hide the y-label
  plt.show()

In [7]:
# function to get portfolio features

def get_portfolio_features(df_common_features):

  print_date_time()
  print('-------------------')

  #df_common_features["Target"] = df_common_features["Target"].fillna(df_common_features["Max"])
  df_common_features['NTT'] = np.where(df_common_features['Strategy']== 'NTT', df_common_features["Target"], df_common_features['Max'])
  df_common_features['LTT'] = np.where(df_common_features['Strategy']== 'BTT', df_common_features["Target"], df_common_features['Max'])
  df_common_features['BOL'] = df_common_features['Min']

  tmp_df = df_common_features[df_common_features['Symbol'].isin(mypf_df[mypf_df['InPortfolio'] != 'NA'].Symbol.values)]
  print('qualified stocks: '+str(len(tmp_df['Symbol'].unique())))
  tmp_df1 = tmp_df[tmp_df['LatestQtr'] == 1]
  print('with latest results: '+str(len(tmp_df1['Symbol'].unique())))
  tmp_df1 = tmp_df1[tmp_df1['StarStock'] == 1]
  print('still star stocks: '+str(len(tmp_df1['Symbol'].unique())))
  tmp_df['Investment'] = tmp_df['AvgCost'] * tmp_df['Shares']
  tmp_df['Current'] = round(tmp_df['Close'] * tmp_df['Shares'],0)
  tmp_df['Previous'] = tmp_df['Prev_Close'] * tmp_df['Shares']
  tmp_df['EstimatedST'] = tmp_df['NTT'] * tmp_df['Shares']
  tmp_df['EstimatedLT'] = tmp_df['LTT'] * tmp_df['Shares']
  tmp_df['Current P/L'] = round((tmp_df['Current'] - tmp_df['Investment']),0)
  tmp_df['Today P/L%'] = round((tmp_df['Current'] - tmp_df['Previous'])*100/tmp_df['Previous'],2)
  tmp_df['Current P/L%'] = round((tmp_df['Current'] - tmp_df['Investment'])*100/tmp_df['Investment'],2)
  tmp_df['EstimatedST P/L%'] = round((tmp_df['EstimatedST'] - tmp_df['Investment'])*100/tmp_df['Investment'],2)
  tmp_df['EstimatedLT P/L%'] = round((tmp_df['EstimatedLT'] - tmp_df['Investment'])*100/tmp_df['Investment'],2)
  tmp_df['NTT%'] = round((tmp_df['NTT'] - tmp_df['Close'])*100/tmp_df['Close'],2)
  tmp_df['LTT%'] = round((tmp_df['LTT'] - tmp_df['Close'])*100/tmp_df['Close'],2)
  tmp_df['Gained%'] = round((tmp_df['Close'] - tmp_df['BOL'])*100/tmp_df['BOL'],2)
  investment = round(sum(tmp_df['AvgCost']*tmp_df['Shares']),0)
  current = round(sum(tmp_df['Close']*tmp_df['Shares']),0)
  tmp_df['InitAlloc%'] = round(tmp_df['Investment']*100/investment,2)
  tmp_df['CurrAlloc%'] = round(tmp_df['Current']*100/current,2)
  tmp_df['FTT'] = tmp_df['LTT']
  tmp_df.loc[tmp_df['Strategy'] == 'NTT', 'FTT'] = tmp_df['NTT']
  tmp_df['FTT%'] = tmp_df['LTT%']
  tmp_df.loc[tmp_df['Strategy'] == 'NTT', 'FTT%'] = tmp_df['NTT%']
  tmp_df['FTT Amt'] = round(tmp_df['FTT%'] * tmp_df['Current']/100,0)
  tmp_df['OTT%'] = round((tmp_df['FTT'] - tmp_df['AvgCost'])*100/tmp_df['AvgCost'],2)
  tmp_df['RRR Ind'] = round(tmp_df['Current P/L']/tmp_df['FTT Amt'],2)
  tmp_df['Risk Ind'] = round(tmp_df['Current P/L%']*tmp_df['CurrAlloc%'],0)

  return tmp_df

# function to print portfolio features
def print_portfolio_stats(df_portfolio_features, myinvmt_df):
  from pyxirr import xirr

  total_booked_amt, reserve_amt, cy_booked_amt, py_booked_amt = get_amt()

  dates = myinvmt_df['Date'].values
  dates = np.append(dates, datetime.date.today().strftime('%d-%b-%y'))
  investment = myinvmt_df['Investment'].values
  dates= pd.to_datetime(dates)

  current = round(sum(df_portfolio_features['Close']*df_portfolio_features['Shares']),0) + reserve_amt
  investment_xirr = np.append(investment, current)
  cagr = round(xirr(pd.DataFrame({"dates": dates, "amounts": investment_xirr}))*100,2)

  investment = -sum(investment)
  invested = round(sum(df_portfolio_features['AvgCost']*df_portfolio_features['Shares']),0) + reserve_amt
  previous = round(sum(df_portfolio_features['Prev_Close']*df_portfolio_features['Shares']),0) + reserve_amt
  cy_invested = investment + py_booked_amt

  today_pnl_amount = current-previous
  today_pnl_percentage = round((current-previous)*100/previous,2)

  curr_pnl_amount = current-invested
  curr_pnl_percentage = round((curr_pnl_amount)*100/(cy_invested),2)

  cy_pnl_amount = cy_booked_amt + curr_pnl_amount
  cy_pnl_percentage = round((cy_pnl_amount)*100/cy_invested,2)

  overall_pnl_amount = total_booked_amt + curr_pnl_amount
  overall_pnl_percentage = round((overall_pnl_amount)*100/investment,2)

  estimate_st = round(sum(df_portfolio_features['FTT']*df_portfolio_features['Shares']),0)  + reserve_amt
  est_st_pnl_amount = estimate_st-current
  est_st_pnl_percentage = round((est_st_pnl_amount)*100/current,2)

  estimate_lt = round(sum(df_portfolio_features['LTT']*df_portfolio_features['Shares']),0)  + reserve_amt
  est_lt_pnl_amount = estimate_lt-current
  est_lt_pnl_percentage = round((est_lt_pnl_amount)*100/current,2)

  total_profit = round(sum(df_portfolio_features[df_portfolio_features['Current P/L%'] > 0]['Current']) - sum(df_portfolio_features[df_portfolio_features['Current P/L%'] > 0]['Investment']),0)
  total_loss = round(sum(df_portfolio_features[df_portfolio_features['Current P/L%'] < 0]['Current']) - sum(df_portfolio_features[df_portfolio_features['Current P/L%'] < 0]['Investment']),0)

  cy_booked_percentage = round((cy_booked_amt)*100/current,2)
  py_booked_percentage = round((py_booked_amt)*100/investment,2)
  total_booked_percentage = round((total_booked_amt)*100/investment,2)

  print('-------------------')
  print('Initial Investment: ', format_amt(investment))
  print('CY Investment: ', format_amt(cy_invested))
  print('Reserve: ', format_amt(reserve_amt))
  print('Current: ',  format_amt(current))
  print('-------------------')
  print('Today PnL: '+ '{} ({}%)'.format(format_amt(today_pnl_amount), today_pnl_percentage))
  print('Current PnL: '+ '{} ({}%)'.format(format_amt(curr_pnl_amount), curr_pnl_percentage))
  print('CY Booked + Current PnL: '+ '{} ({}%)'.format(format_amt(cy_pnl_amount), cy_pnl_percentage))
  print('-------------------')
  print('Total profit: ', format_amt(total_profit))
  print('Total loss: ', format_amt(total_loss))
  print('-------------------')
  print('Total Booked + Current PnL: '+ '{} ({}%)'.format(format_amt(overall_pnl_amount), overall_pnl_percentage))
  print('Total Booked PnL: '+ '{} ({}%)'.format(format_amt(total_booked_amt), total_booked_percentage))
  print('Curr Year Booked PnL: '+ '{} ({}%)'.format(format_amt(cy_booked_amt), cy_booked_percentage))
  print('Prev Year Booked PnL: '+ '{} ({}%)'.format(format_amt(py_booked_amt), py_booked_percentage))
  print('===================')
  print('Est FTT: ',  format_amt(estimate_st))
  print('Est FTT PnL: '+ '{} ({}%)'.format(format_amt(est_st_pnl_amount), est_st_pnl_percentage))

  print('===================')
  print('Deployed: ', format_amt(investment))

  print('Current: ', format_amt(current))

  print('CAGR/XIRR %: '+'{}%'.format(cagr))

In [8]:
# get start and end date
start_date, end_date = get_start_end_date()

# get portfolio and prospects data
mypfs_df = get_mypfs_df()
mypps_df = get_mypps_df()
myinvmt_df = get_myinvmt_df()

# merge above datasets
mypf_df = pd.merge(mypfs_df, mypps_df, on="Symbol")

# seggregate dm and sv portfolio
dm_pf = mypf_df[mypf_df['InPortfolio'] == 'DM']
sv_pf = mypf_df[mypf_df['InPortfolio'] == 'SV']

# build portfolio stock dataframe
dm_stocks = get_stock_ids(dm_pf)
sv_stocks = get_stock_ids(sv_pf)
df_stocks = pd.concat([dm_pf,sv_pf], ignore_index = True)

# arrange common and diff stock features
common_cols = ['Symbol', 'Target', 'Criteria', 'Strategy', 'CumlRnk', 'LatestQtr', 'StarStock', 'Conviction', 'Category', 'InFolio', 'XIRR', 'MBQ']
diff_cols = ['Symbol', 'AvgCost', 'Shares']
df_stocks = arrange_features(df_stocks, common_cols, diff_cols)

# get common features
stock_ids = df_stocks['Symbol'].values
df_common_features = get_common_features(stock_ids, df_stocks)

df_common_features.reset_index(drop=True, inplace=True)
df_common_features.drop(['Date'], axis=1, inplace=True)
# get and print portfolio features
df_portfolio_features = get_portfolio_features(df_common_features)

print_portfolio_stats(df_portfolio_features, myinvmt_df)

df = df_portfolio_features
#plot_pie_chart(df, 'CapType', 'Current')
list_ox40n = list(df[df['MBQ'].str.contains('OX40N', na=False)]['Symbol'].values)

Run date time (IST): 2026-03-10 11:33:13
-------------------
qualified stocks: 86
with latest results: 26
still star stocks: 15
-------------------
Initial Investment:  1.36 C
CY Investment:  1.62 C
Reserve:  66.25 K
Current:  1.37 C
-------------------
Today PnL: 1.54 L (1.14%)
Current PnL: -40.13 L (-24.7%)
CY Booked + Current PnL: -24.45 L (-15.05%)
-------------------
Total profit:  1.18 L
Total loss:  -41.31 L
-------------------
Total Booked + Current PnL: 2.53 L (1.87%)
Total Booked PnL: 42.66 L (31.48%)
Curr Year Booked PnL: 15.68 L (11.46%)
Prev Year Booked PnL: 26.98 L (19.91%)
===================
Est FTT:  2.47 C
Est FTT PnL: 1.10 C (80.77%)
===================
Deployed:  1.36 C
Current:  1.37 C
CAGR/XIRR %: 0.48%

In [9]:
# top 5 near their targets
cols = ['Symbol', 'Today P/L%', 'Current P/L%', 'FTT%', 'OTT%', 'FTT Amt', 'Current P/L', 'Current', 'FTT', 'Dev%_PE', 'RSI_14','Conviction', 'Spread%',  'CumlRnk', 'RRR Ind', 'CurrAlloc%', 'Gained%', 'Criteria', 'Strategy', 'Category']
df_tmp = df_portfolio_features[~df_portfolio_features['Symbol'].isin(['ENRIN','BLUSPRING','DIGITIDE'])]
df_tmp = df_tmp.sort_values(by = 'FTT Amt', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
19,COALINDIA,1.18,8.89,8.06,17.67,13205.0,13376.0,163836.0,478.51,30.56,59.0,L-LC,11.52,185.0,1.01,1.20,27.23,XY25,ATH,MINING
50,MASFIN,1.76,-6.14,29.52,21.57,27148.0,-6015.0,91965.0,397.04,-19.15,40.0,H-SC,5.05,167.0,-0.22,0.68,28.32,XR,ATH,FINANCE
37,ICICIGI,0.23,0.33,18.95,19.34,38045.0,655.0,200764.0,2252.93,-15.67,49.0,X-MC,1.59,66.0,0.02,1.47,14.50,X40,ATH,INSURANCE
77,TTKPRESTIG,3.29,-39.34,65.01,0.09,39741.0,-39646.0,61131.0,770.00,41.94,26.0,M-SC,15.04,250.0,-1.00,0.45,3.29,OX40N,NTT,DURABLES
78,UNITDSPR,2.79,2.37,17.97,20.77,43074.0,5555.0,239699.0,1644.00,-9.24,53.0,X-MC,1.51,64.0,0.13,1.76,9.24,X40N,NTT,BREWERIES

In [10]:
# top 5 today
df_tmp = df_portfolio_features.sort_values(by = 'Today P/L%', ascending=False)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
24,DIXON,6.02,-24.28,82.14,37.92,162215.0,-63312.0,197486.0,18931.72,-67.81,44.0,X-MC,25.55,54.0,-0.39,1.45,6.02,X40N,ATH,IT
15,BSOFT,4.14,-30.42,116.70,50.79,114213.0,-42784.0,97869.0,831.70,-10.71,45.0,H-SC,5.01,172.0,-0.37,0.72,13.95,XR,ATH,IT
77,TTKPRESTIG,3.29,-39.34,65.01,0.09,39741.0,-39646.0,61131.0,770.00,41.94,26.0,M-SC,15.04,250.0,-1.00,0.45,3.29,OX40N,NTT,DURABLES
1,ABB,3.16,13.23,28.56,45.57,84604.0,34613.0,296232.0,7934.00,-27.27,63.0,H-MC,9.67,125.0,0.41,2.18,31.55,AR,NTT,ELECTRICAL
67,SONACOMS,3.07,-10.73,55.80,39.09,50392.0,-10850.0,90309.0,804.02,-29.25,50.0,M-MC,10.33,193.0,-0.22,0.66,27.76,AR,ATH,AUTO

In [11]:
# bottom 5 today
df_tmp = df_portfolio_features.sort_values(by = 'Today P/L%', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
43,INFY,-1.43,-11.76,52.14,34.24,143954.0,-36797.0,276091.0,1972.00,-30.70,28.0,X-LC,11.45,3.0,-0.26,2.03,1.62,X40,NTT,IT
55,RAJESHEXPO,-1.28,-78.46,364.57,0.07,107723.0,-107629.0,29548.0,518.00,983.33,17.0,L-SC,16.78,268.0,-1.00,0.22,0.00,OX40N,NTT,JEWELLERY
16,CAMPUS,-0.92,-19.47,65.51,33.28,88510.0,-32666.0,135109.0,393.00,-35.18,31.0,M-SC,4.30,218.0,-0.37,0.99,4.72,XY24,NTT,FOOTWEAR
40,INDIAMART,-0.80,-6.92,122.09,106.72,140163.0,-8533.0,114803.0,4810.62,-58.01,49.0,H-SC,9.01,140.0,-0.06,0.84,14.84,AR,ATH,MISC
2,ABBOTINDIA,-0.77,-9.51,30.47,18.07,49316.0,-17005.0,161850.0,35195.00,-23.01,49.0,X-MC,11.12,58.0,-0.34,1.19,2.61,X40,ATH,PHARMA

In [12]:
# top 5 to exit based on CumlRnk
df_tmp = df_portfolio_features[~df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])]
df_tmp = df_tmp[(df_tmp['Current P/L%'] > -1) & (df_tmp['Current P/L%'] < 1)].sort_values(by = 'CumlRnk', ascending=False)
df_tmp[cols].head()

Empty DataFrame
Columns: [Symbol, Today P/L%, Current P/L%, FTT%, OTT%, FTT Amt, Current P/L, Current, FTT, Dev%_PE, RSI_14, Conviction, Spread%, CumlRnk, RRR Ind, CurrAlloc%, Gained%, Criteria, Strategy, Category]
Index: []

In [13]:
# OX40N stocks to exit
df_tmp = df_portfolio_features[(df_portfolio_features['Symbol'].isin(list_ox40n))].sort_values(by = 'Current P/L%', ascending=False)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
27,FINCABLES,0.78,22.86,69.23,107.91,125576.0,33746.0,181390.0,1641.55,10.60,71.0,M-SC,7.80,220.0,0.27,1.33,36.47,OX40N,ATH,CABLES
66,SIS,0.59,-33.89,83.43,21.26,61239.0,-37630.0,73402.0,528.00,1718.65,33.0,H-SC,9.22,168.0,-0.61,0.54,1.19,OX40N,NTT,MISC
72,TATAELXSI,0.21,-37.84,112.41,32.03,92114.0,-49890.0,81945.0,9161.00,-22.21,27.0,H-SC,15.83,158.0,-0.54,0.60,0.21,OX40N,NTT,IT
48,KANSAINER,0.31,-37.96,82.89,13.47,138683.0,-102357.0,167310.0,340.00,-46.64,24.0,H-SC,16.16,162.0,-0.74,1.23,0.31,XY24,NTT,PAINTS
77,TTKPRESTIG,3.29,-39.34,65.01,0.09,39741.0,-39646.0,61131.0,770.00,41.94,26.0,M-SC,15.04,250.0,-1.00,0.45,3.29,OX40N,NTT,DURABLES

In [14]:
# top 5 to book for rotation
df_tmp = df_portfolio_features[(df_portfolio_features['Current P/L%'] > 20) ].sort_values(by = 'CumlRnk', ascending=False)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
27,FINCABLES,0.78,22.86,69.23,107.91,125576.0,33746.0,181390.0,1641.55,10.6,71.0,M-SC,7.8,220.0,0.27,1.33,36.47,OX40N,ATH,CABLES

In [15]:
# top 5 to monitor for exit
df_tmp = df_portfolio_features[~df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])]
df_tmp = df_tmp[(df_tmp['Current P/L%'] > 0) ].sort_values(by = 'Dev%_PE', ascending=False)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
19,COALINDIA,1.18,8.89,8.06,17.67,13205.0,13376.0,163836.0,478.51,30.56,59.0,L-LC,11.52,185.0,1.01,1.20,27.23,XY25,ATH,MINING
27,FINCABLES,0.78,22.86,69.23,107.91,125576.0,33746.0,181390.0,1641.55,10.60,71.0,M-SC,7.80,220.0,0.27,1.33,36.47,OX40N,ATH,CABLES
1,ABB,3.16,13.23,28.56,45.57,84604.0,34613.0,296232.0,7934.00,-27.27,63.0,H-MC,9.67,125.0,0.41,2.18,31.55,AR,NTT,ELECTRICAL

In [16]:
# top 5 to book for rotation from weak conviction
df_tmp = df_portfolio_features[~df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])]
df_tmp = df_tmp[~df_tmp['Criteria'].isin(['XY25','XY24','X40', 'X40N'])].sort_values(by = 'RRR Ind', ascending=False)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
1,ABB,3.16,13.23,28.56,45.57,84604.0,34613.0,296232.0,7934.00,-27.27,63.0,H-MC,9.67,125.0,0.41,2.18,31.55,AR,NTT,ELECTRICAL
27,FINCABLES,0.78,22.86,69.23,107.91,125576.0,33746.0,181390.0,1641.55,10.60,71.0,M-SC,7.80,220.0,0.27,1.33,36.47,OX40N,ATH,CABLES
40,INDIAMART,-0.80,-6.92,122.09,106.72,140163.0,-8533.0,114803.0,4810.62,-58.01,49.0,H-SC,9.01,140.0,-0.06,0.84,14.84,AR,ATH,MISC
85,ZYDUSLIFE,0.75,-3.44,40.46,35.63,81879.0,-7204.0,202370.0,1286.17,-15.77,53.0,H-MC,5.10,120.0,-0.09,1.49,12.66,AR,ATH,PHARMA
84,WIPRO,0.06,-18.43,111.19,72.27,153681.0,-31233.0,138215.0,420.00,-26.43,28.0,M-LC,13.92,98.0,-0.20,1.02,1.78,XR,NTT,IT

In [17]:
# top 5 to accumulate based on lowest RSI_14
df_tmp = df_portfolio_features[df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])].sort_values(by = 'RSI_14', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
8,AWL,0.70,-39.11,174.27,67.02,378114.0,-139339.0,216970.0,485.00,-67.16,15.0,X-SC,22.46,81.0,-0.37,1.59,0.70,XY24,NTT,FMCG
53,PGHH,0.42,-20.20,65.43,32.01,111482.0,-43136.0,170384.0,17616.87,-46.05,16.0,X-MC,10.98,57.0,-0.39,1.25,0.42,X40,ATH,FMCG
12,BATAINDIA,-0.09,-53.76,192.37,35.20,114466.0,-69167.0,59503.0,2096.00,-22.02,20.0,X-SC,24.75,91.0,-0.60,0.44,0.00,X40,NTT,FOOTWEAR
46,JIOFIN,0.15,-22.81,66.38,28.43,152856.0,-68053.0,230274.0,387.00,-24.04,22.0,X-LC,14.47,34.0,-0.45,1.69,9.10,XY24,BTT,FINANCE
58,RELAXO,0.39,-59.57,276.68,52.31,162395.0,-86466.0,58694.0,1176.00,-56.93,22.0,X-SC,18.07,92.0,-0.53,0.43,0.39,X40N,NTT,FOOTWEAR

In [18]:
# top 5 to accumulate based on Spread and CumlRnk
df_tmp = df_portfolio_features[df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])]
df_tmp = df_tmp[(df_tmp['CumlRnk'] < 100)].sort_values(by = 'Spread%', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
22,DABUR,2.34,-6.62,53.89,43.70,124829.0,-16432.0,231636.0,735.00,-15.22,36.0,X-MC,0.92,70.0,-0.13,1.70,7.43,XY24,BTT,FMCG
78,UNITDSPR,2.79,2.37,17.97,20.77,43074.0,5555.0,239699.0,1644.00,-9.24,53.0,X-MC,1.51,64.0,0.13,1.76,9.24,X40N,NTT,BREWERIES
37,ICICIGI,0.23,0.33,18.95,19.34,38045.0,655.0,200764.0,2252.93,-15.67,49.0,X-MC,1.59,66.0,0.02,1.47,14.50,X40,ATH,INSURANCE
59,RELIANCE,-0.47,-9.02,37.73,25.30,68983.0,-18131.0,182832.0,1952.00,-11.57,50.0,X-LC,2.21,21.0,-0.26,1.34,22.07,XY25,BTT,REFINERIES
75,TMPV,2.73,-22.37,75.93,36.58,209757.0,-79591.0,276250.0,600.00,-83.62,37.0,X-LC,2.29,4.0,-0.38,2.03,2.73,XY24,NTT,AUTO

In [19]:
# top 5 to accumulate based on lowest Gained%
df_tmp = df_portfolio_features[df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])].sort_values(by = 'Gained%', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
10,BAJAJHLDNG,-0.60,-8.90,41.85,29.22,72483.0,-16929.0,173196.0,14451.52,-15.85,30.0,X-LC,11.96,28.0,-0.23,1.27,0.00,X40,ATH,FINANCE
12,BATAINDIA,-0.09,-53.76,192.37,35.20,114466.0,-69167.0,59503.0,2096.00,-22.02,20.0,X-SC,24.75,91.0,-0.60,0.44,0.00,X40,NTT,FOOTWEAR
73,TCS,-0.69,-26.32,71.78,26.57,245028.0,-121913.0,341360.0,4311.59,-37.73,24.0,X-LC,13.10,2.0,-0.50,2.51,0.00,X40,ATH,IT
45,ITC,0.02,-19.39,47.69,19.06,130776.0,-65945.0,274221.0,452.00,-55.92,33.0,X-LC,16.97,1.0,-0.50,2.01,0.02,X40,NTT,FMCG
58,RELAXO,0.39,-59.57,276.68,52.31,162395.0,-86466.0,58694.0,1176.00,-56.93,22.0,X-SC,18.07,92.0,-0.53,0.43,0.39,X40N,NTT,FOOTWEAR

In [20]:
# top 5 to accumulate based on lowest CurrAlloc%
df_tmp = df_portfolio_features[df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])].sort_values(by = 'CurrAlloc%', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
58,RELAXO,0.39,-59.57,276.68,52.31,162395.0,-86466.0,58694.0,1176.00,-56.93,22.0,X-SC,18.07,92.0,-0.53,0.43,0.39,X40N,NTT,FOOTWEAR
12,BATAINDIA,-0.09,-53.76,192.37,35.20,114466.0,-69167.0,59503.0,2096.00,-22.02,20.0,X-SC,24.75,91.0,-0.60,0.44,0.00,X40,NTT,FOOTWEAR
54,QUESS,1.75,-22.77,125.16,73.90,103232.0,-24313.0,82480.0,424.00,-58.68,37.0,X-SC,17.79,80.0,-0.24,0.61,1.75,XY24,NTT,MISC
36,HONAUT,2.15,-21.33,92.34,51.31,140080.0,-41138.0,151700.0,58357.33,-34.59,39.0,X-SC,13.55,90.0,-0.29,1.11,2.15,X40N,ATH,ELECTRICAL
2,ABBOTINDIA,-0.77,-9.51,30.47,18.07,49316.0,-17005.0,161850.0,35195.00,-23.01,49.0,X-MC,11.12,58.0,-0.34,1.19,2.61,X40,ATH,PHARMA

In [21]:
# top 5 to accumulate based on CumlRnk
df_tmp = df_portfolio_features.sort_values(by = 'CumlRnk', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
45,ITC,0.02,-19.39,47.69,19.06,130776.0,-65945.0,274221.0,452.00,-55.92,33.0,X-LC,16.97,1.0,-0.50,2.01,0.02,X40,NTT,FMCG
73,TCS,-0.69,-26.32,71.78,26.57,245028.0,-121913.0,341360.0,4311.59,-37.73,24.0,X-LC,13.10,2.0,-0.50,2.51,0.00,X40,ATH,IT
43,INFY,-1.43,-11.76,52.14,34.24,143954.0,-36797.0,276091.0,1972.00,-30.70,28.0,X-LC,11.45,3.0,-0.26,2.03,1.62,X40,NTT,IT
75,TMPV,2.73,-22.37,75.93,36.58,209757.0,-79591.0,276250.0,600.00,-83.62,37.0,X-LC,2.29,4.0,-0.38,2.03,2.73,XY24,NTT,AUTO
34,HCLTECH,-0.45,-12.23,41.09,23.83,87251.0,-29582.0,212342.0,1908.19,-7.78,27.0,X-LC,9.13,8.0,-0.34,1.56,1.88,X40,ATH,IT

In [22]:
# top 5 for average up
df_tmp = df_portfolio_features[(df_portfolio_features['Dev%_200'] > 5)].sort_values(by = 'CurrAlloc%', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
42,INDUSINDBK,1.87,-33.72,100.51,32.89,51430.0,-26038.0,51169.0,1800.00,-340.90,43.0,L-MC,11.58,258.0,-0.51,0.38,40.92,XR,NTT,BANKS
67,SONACOMS,3.07,-10.73,55.80,39.09,50392.0,-10850.0,90309.0,804.02,-29.25,50.0,M-MC,10.33,193.0,-0.22,0.66,27.76,AR,ATH,AUTO
19,COALINDIA,1.18,8.89,8.06,17.67,13205.0,13376.0,163836.0,478.51,30.56,59.0,L-LC,11.52,185.0,1.01,1.20,27.23,XY25,ATH,MINING
27,FINCABLES,0.78,22.86,69.23,107.91,125576.0,33746.0,181390.0,1641.55,10.60,71.0,M-SC,7.80,220.0,0.27,1.33,36.47,OX40N,ATH,CABLES
82,VOLTAS,1.30,13.84,27.54,45.20,60114.0,26538.0,218280.0,1856.00,30.35,47.0,X-MC,9.75,79.0,0.44,1.60,21.58,XY25,NTT,AC

In [23]:
# top 5 RSP
df_tmp = df_portfolio_features.sort_values(by = 'RSP', ascending=False)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
27,FINCABLES,0.78,22.86,69.23,107.91,125576.0,33746.0,181390.0,1641.55,10.60,71.0,M-SC,7.80,220.0,0.27,1.33,36.47,OX40N,ATH,CABLES
11,BANDHANBNK,2.89,-13.82,123.26,92.42,295915.0,-38485.0,240074.0,400.00,106.18,59.0,H-SC,9.93,174.0,-0.13,1.76,32.25,XY24,NTT,BANKS
26,EASEMYTRIP,2.08,-59.38,258.70,45.70,185796.0,-104996.0,71819.0,26.40,-25.36,44.0,M-SC,18.18,204.0,-0.57,0.53,18.33,XY24,NTT,TRAVEL
65,SIEMENS,1.94,-11.56,41.93,25.51,69006.0,-21520.0,164575.0,4671.50,38.15,55.0,H-LC,3.57,51.0,-0.31,1.21,21.20,AR,ATH,ELECTRICAL
1,ABB,3.16,13.23,28.56,45.57,84604.0,34613.0,296232.0,7934.00,-27.27,63.0,H-MC,9.67,125.0,0.41,2.18,31.55,AR,NTT,ELECTRICAL

In [24]:
# Top N allocation
df_tmp = df_portfolio_features.sort_values(by = 'CurrAlloc%', ascending=False)
top_n_values = [10, 25, 50]

sum_df = pd.DataFrame({
    'Top_N': top_n_values,
    'Sum_Alloc%': [df_tmp['CurrAlloc%'].head(n).sum() for n in top_n_values]
})

sum_df

   Top_N  Sum_Alloc%
0     10       20.60
1     25       45.44
2     50       77.99

In [25]:
# market-cap-wise allocation
df_tmp = df_portfolio_features[cols]
df_tmp.groupby(df_tmp['Conviction'].str[-2:])['CurrAlloc%'].sum().sort_values(ascending=False)

Conviction
SC    44.42
MC    30.55
LC    24.99
Name: CurrAlloc%, dtype: float64

In [26]:
# criteria-wise allocation
df_portfolio_features.groupby('Criteria')['CurrAlloc%'].sum().sort_values(ascending=False)

Criteria
XY24     27.21
X40      23.89
X40N     15.18
AR        9.07
XY25      8.70
XR        8.26
OX40N     6.88
SR        0.77
Name: CurrAlloc%, dtype: float64

In [27]:
# conviction-wise allocation
df_portfolio_features.groupby('Conviction')['CurrAlloc%'].sum().sort_values(ascending=False)

Conviction
X-MC    23.20
X-LC    21.56
H-SC    21.49
X-SC    12.16
M-SC    10.17
H-MC     4.97
M-MC     2.00
H-LC     1.21
L-LC     1.20
M-LC     1.02
L-SC     0.60
L-MC     0.38
Name: CurrAlloc%, dtype: float64

In [28]:
# sector-wise stats
df_tmp = df_portfolio_features.groupby('Category')[['CurrAlloc%', 'Current', 'Current P/L', 'FTT Amt']].sum().sort_values(by=['Current', 'Current P/L'], ascending=False)
df_tmp['Current P/L%'] = round(df_tmp['Current P/L'] * 100 / df_tmp['Current'], 2)
df_tmp['FTT%'] = round(df_tmp['FTT Amt'] * 100 / df_tmp['Current'], 2)
cols = ['CurrAlloc%', 'Current P/L%', 'FTT%']
df_tmp[cols].sort_values(by=['CurrAlloc%'], ascending=False)

               CurrAlloc%  Current P/L%    FTT%
Category
FMCG                15.38        -19.22   61.55
FINANCE             12.76        -23.70   74.11
IT                  11.63        -42.33  114.76
MISC                 6.91        -42.30  104.12
ELECTRICAL           6.62         -7.55   48.73
PAINTS               5.23        -38.48   62.53
INSURANCE            4.73         -5.19   41.18
PHARMA               4.17         -3.66   36.30
AUTO                 3.76        -27.75   78.44
BANKS                3.14        -25.22  101.10
AC                   2.14         -9.57   39.28
HEALTHCARE           1.97        -32.84   67.50
FOOTWEAR             1.86        -74.34  144.24
TRAVEL               1.83        -79.39  169.22
DURABLES             1.79        -58.43   96.98
BREWERIES            1.76          2.32   17.97
APPARELS             1.60        -23.00   64.96
REALTY               1.46        -11.58   29.91
REFINERIES           1.34         -9.92   37.73
CABLES               1.33         18.60   69.23
CERAMICS             1.32        -69.90  121.52
CEMENT               1.30        -51.75  165.28
MINING               1.20          8.16    8.06
ENGINEERING          1.10        -61.33  135.12
JEWELLERY            1.10       -113.76  188.02
CHEMICALS            0.96       -103.29  269.14
ENTERTAINMENT        0.77        -84.57  194.64
TEXTILES             0.42        -60.71  106.54
HOTELS               0.38       -122.25  200.64

In [29]:
# money to be made criteria-wise
df_portfolio_features.groupby('Criteria')['FTT Amt'].agg(['sum', 'count']).sort_values(by='sum', ascending=False)

                sum  count
Criteria
XY24      3890639.0     21
X40       1620250.0     15
XR        1368657.0     12
AR        1335091.0     10
X40N      1234206.0     10
OX40N      854497.0     10
XY25       430994.0      6
SR         314613.0      2

In [30]:
# money to be made conviction-wise
df_portfolio_features.groupby('Conviction')['FTT Amt'].agg(['sum', 'count']).sort_values(by='sum', ascending=False)

                  sum  count
Conviction
H-SC        3863867.0     24
X-MC        1574809.0     15
X-LC        1539745.0     12
M-SC        1531189.0     14
X-SC        1525958.0     10
H-MC         402647.0      3
L-SC         210232.0      2
M-LC         153681.0      1
M-MC         113178.0      2
H-LC          69006.0      1
L-MC          51430.0      1
L-LC          13205.0      1

In [31]:
# money to be made criteria and conviction-wise
df_portfolio_features.groupby(['Conviction', 'Criteria'])['FTT Amt'].agg(['sum', 'count']).sort_values(by='sum', ascending=False)

                           sum  count
Conviction Criteria
H-SC       XY24      1317147.0      6
           AR         973099.0      5
M-SC       XY24       906275.0      6
H-SC       XR         871818.0      7
X-SC       XY24       829659.0      4
X-LC       X40        800894.0      6
X-MC       X40        620880.0      7
           X40N       501928.0      4
X-SC       X40N       497823.0      4
H-SC       OX40N      387190.0      4
X-LC       XY24       362613.0      2
M-SC       OX40N      359584.0      5
H-SC       SR         314613.0      2
X-MC       XY24       238781.0      2
H-MC       XY24       236164.0      1
X-LC       X40N       234455.0      2
X-MC       XY25       213220.0      2
X-SC       X40        198476.0      2
M-SC       XR         189219.0      2
H-MC       AR         166483.0      2
M-LC       XR         153681.0      1
X-LC       XY25       141783.0      2
L-SC       OX40N      107723.0      1
           XR         102509.0      1
M-SC       AR          76111.0      1
H-LC       AR          69006.0      1
M-MC       XY25        62786.0      1
L-MC       XR          51430.0      1
M-MC       AR          50392.0      1
L-LC       XY25        13205.0      1

In [32]:
# notebook execution time

end_time = time.time()
execution_time = round(end_time - start_time, 0)
print(f"Notebook execution time: {execution_time} seconds")

Notebook execution time: 31.0 seconds