<a href="https://colab.research.google.com/github/ankit-rathi/Quantvesting_v2/blob/main/myStocks_Portfolio_Analysis.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
'''
!pip install pandas==2.2.2 -qq
!pip install pyxirr -qq
!pip install ta -qq
!pip install yfinance==0.2.59 -qq
'''

'\n!pip install pandas==2.2.2 -qq\n!pip install pyxirr -qq\n!pip install ta -qq\n!pip install yfinance==0.2.59 -qq\n'

In [2]:
# import libraries

import numpy as np
import pandas as pd
import datetime
import warnings
warnings.filterwarnings('ignore')
import yfinance as yfin
import ta
import matplotlib.pyplot as plt
import requests

In [3]:
# notebook start time
import time
import datetime
import pytz

start_time = time.time()

# function to print date timestamp
def print_date_time():
  tz_NY = pytz.timezone('Asia/Kolkata')
  datetime_NY = datetime.datetime.now(tz_NY)
  print("Run date time (IST):", datetime_NY.strftime("%Y-%m-%d %H:%M:%S"))

In [4]:
# function to get booked and reserved amount
def get_amt():
  # fetch the JSON data from the URL
  url = "https://raw.githubusercontent.com/ankit-rathi/Tradevesting_v1/main/data/myPortfolioAmts.json"
  response = requests.get(url)
  pf_amts = response.json()  # parse the JSON data

  # extract values from the JSON
  py_booked_amt_dm = pf_amts["py_booked_amt_dm"]
  py_booked_amt_sv = pf_amts["py_booked_amt_sv"]
  cy_booked_amt_dm = pf_amts["cy_booked_amt_dm"]
  cy_booked_amt_sv = pf_amts["cy_booked_amt_sv"]
  reserve_amt_dm = pf_amts["reserve_amt_dm"]
  reserve_amt_sv = pf_amts["reserve_amt_sv"]

  # perform calculations
  py_booked_amt = py_booked_amt_dm + py_booked_amt_sv
  cy_booked_amt = cy_booked_amt_dm + cy_booked_amt_sv
  reserve_amt = reserve_amt_dm + reserve_amt_sv
  total_booked_amt = py_booked_amt + cy_booked_amt

  return total_booked_amt, reserve_amt, cy_booked_amt, py_booked_amt

gen_output = 0

In [5]:
# function to format the amount
def format_amt(number):
    abs_number = abs(number)

    if abs_number >= 1_00_00_000:  # Crores
        formatted_amt = f"{number / 1_00_00_000:.2f} C"
    elif abs_number >= 1_00_000:  # Lakhs
        formatted_amt = f"{number / 1_00_000:.2f} L"
    elif abs_number >= 1_000:  # Thousands
        formatted_amt = f"{number / 1_000:.2f} K"
    else:
        formatted_amt = f"{number:.2f}"

    return formatted_amt

# function to set start and end date
def get_start_end_date():
  start_date = (datetime.date.today() + datetime.timedelta(days=-365)).strftime('%Y-%m-%d')
  end_date = (datetime.date.today() + datetime.timedelta(days=1)).strftime('%Y-%m-%d')
  return start_date, end_date

# function to fetch my portfolio csv
def get_mypfs_df():
  mypfs_df = pd.read_csv('https://raw.githubusercontent.com/ankit-rathi/Tradevesting_v1/main/data/myPortfolioStocks.csv')
  return mypfs_df

# function to fetch my prospects csv
def get_mypps_df():
  mypps_df = pd.read_csv('https://raw.githubusercontent.com/ankit-rathi/Tradevesting_v1/main/data/myProspectsScrips.csv')
  return mypps_df

# function to fetch screener data
def get_myscreen_df():
  myscreen_df = pd.read_csv('https://raw.githubusercontent.com/ankit-rathi/Tradevesting_v1/main/data/myScreenerDB.csv')
  return myscreen_df

# function to fetch momentum data
def get_myinvmt_df():
  myinvmt_df = pd.read_csv('https://raw.githubusercontent.com/ankit-rathi/Tradevesting_v1/main/data/myInvestments.csv')
  return myinvmt_df

# function to get the stock ids
def get_stock_ids(df_pf):
  stock_n100 = df_pf['Symbol'].unique()

  exclude = ['CADILAHC','MMTC', 'MASFIN']

  stock_ids = df_pf[~df_pf['Symbol'].isin(exclude) ]['Symbol'].unique()

  #mypf = mypf[mypf.Forecast.notnull()]
  #stock_ids = mypf['Symbol'].unique()

  #stock_ids.sort()
  return stock_ids

# get features from screener data
def get_screener_features():
  myscreen_df = get_myscreen_df()
  cols = ['Symbol', 'EPS', 'MedPE', 'ROCE%', 'ROE%', 'CapType']
  return myscreen_df[cols]

# get relative strength
def get_relative_strength(stock_list):

    # Dictionary to store stock tickers and their corresponding percentage price change
    stock_changes = {}

    # Loop through each stock and fetch its price data
    for stock in stock_list:
        try:
            # Download the stock data for the given date range
            stock_data = yfin.Ticker(stock + '.NS').history(period='1mo', interval='1d')[map(str.title, ['open', 'close', 'low', 'high', 'volume'])]

            # Calculate the percentage change for the stock
            if len(stock_data) > 0:
                start_price = stock_data['Close'].iloc[0]
                end_price = stock_data['Close'].iloc[-1]
                percent_change = round(((end_price - start_price) / start_price) * 100, 2)
                stock_changes[stock] = percent_change
            else:
                stock_changes[stock] = np.nan  # If no data is available, set to NaN

        except Exception as e:
            print(f"Error fetching data for {stock}: {e}")
            stock_changes[stock] = np.nan

    # Create a DataFrame with stock tickers and their percentage changes
    df = pd.DataFrame(list(stock_changes.items()), columns=['Symbol', 'Percent_Change'])

    # Drop any stocks with missing data (NaN values)
    df = df.dropna()

    # Calculate the percentile rank based on percentage change
    df['RSP'] = round(df['Percent_Change'].rank(pct=True) * 100, 2)
    cols = ['Symbol', 'RSP']
    df = df[cols]
    # Sort by percentile rank (optional)
    df = df.sort_values(by='RSP', ascending=False).reset_index(drop=True)

    return df

In [6]:
# function to get stock technicals
def stock_prec_dev(stock_symbol):
    #stock_symbol = 'ULTRACEMCO.NS'
    short_window = 20
    mid_window = 50
    long_window = 200
    moving_avg = 'SMA'

    start = datetime.datetime(*map(int, start_date.split('-')))
    end = datetime.datetime(*map(int, end_date.split('-')))

    stock_df = yfin.Ticker(stock_symbol + '.NS').history(period='max', interval='1d')[map(str.title, ['open', 'close', 'low', 'high', 'volume'])]

    stock_df['Max'] = round(max(stock_df['Close']),2)
    stock_df = stock_df[(stock_df.index <= end_date) & (stock_df.index >= start_date)]
    stock_df['200_SMA'] = round(stock_df['Close'].rolling(window = 200, min_periods = 1).mean(),0)
    stock_df['Dev%_200'] = round((stock_df['Close'] - stock_df['200_SMA'])*100/stock_df['200_SMA'],2)
    stock_df.dropna(axis = 0, inplace = True) # remove any null rows

    stock_df['20_SMA'] = stock_df['Close'].rolling(window=20).mean()
    stock_df['50_SMA'] = stock_df['Close'].rolling(window=50).mean()
    stock_df['Symbol'] = stock_symbol

    stock_df['Close'] = round(stock_df['Close'],2)
    stock_df['Min'] = round(min(stock_df['Close']),2)
    stock_df['RSI_14'] = ta.momentum.RSIIndicator(close=stock_df['Close'], window=14).rsi()
    stock_df['RSI_14'] = round(stock_df['RSI_14'],0)
    stock_df['Prev_Close'] = stock_df['Close'].shift(1)
    stock_df.drop(['Open', 'Low', 'High', 'Volume'], axis=1, inplace=True)
    stock_df = stock_df.tail(1)

    max_SMA = max(stock_df['20_SMA'].item(), stock_df['50_SMA'].item(), stock_df['200_SMA'].item())
    min_SMA = min(stock_df['20_SMA'].item(), stock_df['50_SMA'].item(), stock_df['200_SMA'].item())
    ABS_Spread = max_SMA - min_SMA
    stock_df['Spread%'] = round((ABS_Spread / stock_df['200_SMA'].item()) * 100,2)

    return stock_df

# function to compute stock attributes
def get_common_features(stock_ids, df_mypf):

  df_prec_dev = pd.DataFrame()
  df_tmp = get_screener_features()
  df_rs = get_relative_strength(stock_ids)

  for stock_id in stock_ids:
      tmp = stock_prec_dev(stock_id)
      tmp = tmp.reset_index()
      df_prec_dev = pd.concat([df_prec_dev, tmp], ignore_index = True)
  df_prec_dev = pd.merge(df_prec_dev, df_mypf, on= 'Symbol')
  df_prec_dev = pd.merge(df_prec_dev, df_tmp, on= 'Symbol', how='left')
  df_prec_dev = pd.merge(df_prec_dev, df_rs, on= 'Symbol', how='left')
  #print(df_prec_dev.columns)
  df_prec_dev['Curr_PE'] = round(df_prec_dev['Close']/df_prec_dev['EPS'],1)
  df_prec_dev['Dev%_PE'] = round((df_prec_dev['Curr_PE'] - df_prec_dev['MedPE'])*100/df_prec_dev['MedPE'],2)
  df_prec_dev['Conviction'] = df_prec_dev['Conviction'] + '-' + df_prec_dev['CapType']
  return df_prec_dev

# function to arrange stock features
def arrange_features(df_stocks, common_cols, diff_cols):
  df_stocks_common = df_stocks[common_cols].drop_duplicates()
  df_stocks_diff = df_stocks[diff_cols]
  df_stocks_diff['Investment'] = df_stocks_diff['AvgCost'] * df_stocks_diff['Shares']
  df_stocks_diff = df_stocks_diff.groupby(['Symbol'])[['Shares', 'Investment']].aggregate(['sum']).reset_index()
  df_stocks_diff.columns = ['Symbol', 'Shares', 'Investment']
  df_stocks_diff['AvgCost'] = round(df_stocks_diff['Investment']/df_stocks_diff['Shares'],2)
  df_stocks = pd.merge(df_stocks_diff, df_stocks_common, on='Symbol')
  return df_stocks

# plot fact distribution across dimension
def plot_pie_chart(df, dimension, fact):
  # grouping the data by category and calculating the sum of fact for each type
  grouped_data = df.groupby(dimension)[fact].sum()

  # sorting the grouped data in descending order
  grouped_data = grouped_data.sort_values(ascending=False)

  # creating a pie chart
  grouped_data.plot.pie(autopct='%1.1f%%', startangle=90, figsize=(6, 6))

  # adding a title and displaying the plot
  plt.title(f'{dimension} {fact} Distribution')
  plt.ylabel('')  # To hide the y-label
  plt.show()

In [7]:
# function to get portfolio features

def get_portfolio_features(df_common_features):

  print_date_time()
  print('-------------------')

  #df_common_features["Target"] = df_common_features["Target"].fillna(df_common_features["Max"])
  df_common_features['NTT'] = np.where(df_common_features['Strategy']== 'NTT', df_common_features["Target"], df_common_features['Max'])
  df_common_features['LTT'] = np.where(df_common_features['Strategy']== 'BTT', df_common_features["Target"], df_common_features['Max'])
  df_common_features['BOL'] = df_common_features['Min']

  tmp_df = df_common_features[df_common_features['Symbol'].isin(mypf_df[mypf_df['InPortfolio'] != 'NA'].Symbol.values)]
  print('qualified stocks: '+str(len(tmp_df['Symbol'].unique())))
  tmp_df1 = tmp_df[tmp_df['LatestQtr'] == 1]
  print('with latest results: '+str(len(tmp_df1['Symbol'].unique())))
  tmp_df1 = tmp_df1[tmp_df1['StarStock'] == 1]
  print('still star stocks: '+str(len(tmp_df1['Symbol'].unique())))
  tmp_df['Investment'] = tmp_df['AvgCost'] * tmp_df['Shares']
  tmp_df['Current'] = round(tmp_df['Close'] * tmp_df['Shares'],0)
  tmp_df['Previous'] = tmp_df['Prev_Close'] * tmp_df['Shares']
  tmp_df['EstimatedST'] = tmp_df['NTT'] * tmp_df['Shares']
  tmp_df['EstimatedLT'] = tmp_df['LTT'] * tmp_df['Shares']
  tmp_df['Current P/L'] = round((tmp_df['Current'] - tmp_df['Investment']),0)
  tmp_df['Today P/L%'] = round((tmp_df['Current'] - tmp_df['Previous'])*100/tmp_df['Previous'],2)
  tmp_df['Current P/L%'] = round((tmp_df['Current'] - tmp_df['Investment'])*100/tmp_df['Investment'],2)
  tmp_df['EstimatedST P/L%'] = round((tmp_df['EstimatedST'] - tmp_df['Investment'])*100/tmp_df['Investment'],2)
  tmp_df['EstimatedLT P/L%'] = round((tmp_df['EstimatedLT'] - tmp_df['Investment'])*100/tmp_df['Investment'],2)
  tmp_df['NTT%'] = round((tmp_df['NTT'] - tmp_df['Close'])*100/tmp_df['Close'],2)
  tmp_df['LTT%'] = round((tmp_df['LTT'] - tmp_df['Close'])*100/tmp_df['Close'],2)
  tmp_df['Gained%'] = round((tmp_df['Close'] - tmp_df['BOL'])*100/tmp_df['BOL'],2)
  investment = round(sum(tmp_df['AvgCost']*tmp_df['Shares']),0)
  current = round(sum(tmp_df['Close']*tmp_df['Shares']),0)
  tmp_df['InitAlloc%'] = round(tmp_df['Investment']*100/investment,2)
  tmp_df['CurrAlloc%'] = round(tmp_df['Current']*100/current,2)
  tmp_df['FTT'] = tmp_df['LTT']
  tmp_df.loc[tmp_df['Strategy'] == 'NTT', 'FTT'] = tmp_df['NTT']
  tmp_df['FTT%'] = tmp_df['LTT%']
  tmp_df.loc[tmp_df['Strategy'] == 'NTT', 'FTT%'] = tmp_df['NTT%']
  tmp_df['FTT Amt'] = round(tmp_df['FTT%'] * tmp_df['Current']/100,0)
  tmp_df['OTT%'] = round((tmp_df['FTT'] - tmp_df['AvgCost'])*100/tmp_df['AvgCost'],2)
  tmp_df['RRR Ind'] = round(tmp_df['Current P/L']/tmp_df['FTT Amt'],2)
  tmp_df['Risk Ind'] = round(tmp_df['Current P/L%']*tmp_df['CurrAlloc%'],0)

  return tmp_df

# function to print portfolio features
def print_portfolio_stats(df_portfolio_features, myinvmt_df):
  from pyxirr import xirr

  total_booked_amt, reserve_amt, cy_booked_amt, py_booked_amt = get_amt()

  dates = myinvmt_df['Date'].values
  dates = np.append(dates, datetime.date.today().strftime('%d-%b-%y'))
  investment = myinvmt_df['Investment'].values
  dates= pd.to_datetime(dates)

  current = round(sum(df_portfolio_features['Close']*df_portfolio_features['Shares']),0) + reserve_amt
  investment_xirr = np.append(investment, current)
  cagr = round(xirr(pd.DataFrame({"dates": dates, "amounts": investment_xirr}))*100,2)

  investment = -sum(investment)
  invested = round(sum(df_portfolio_features['AvgCost']*df_portfolio_features['Shares']),0) + reserve_amt
  previous = round(sum(df_portfolio_features['Prev_Close']*df_portfolio_features['Shares']),0) + reserve_amt
  cy_invested = investment + py_booked_amt

  today_pnl_amount = current-previous
  today_pnl_percentage = round((current-previous)*100/previous,2)

  curr_pnl_amount = current-invested
  curr_pnl_percentage = round((curr_pnl_amount)*100/(cy_invested),2)

  cy_pnl_amount = cy_booked_amt + curr_pnl_amount
  cy_pnl_percentage = round((cy_pnl_amount)*100/cy_invested,2)

  overall_pnl_amount = total_booked_amt + curr_pnl_amount
  overall_pnl_percentage = round((overall_pnl_amount)*100/investment,2)

  estimate_st = round(sum(df_portfolio_features['FTT']*df_portfolio_features['Shares']),0)  + reserve_amt
  est_st_pnl_amount = estimate_st-current
  est_st_pnl_percentage = round((est_st_pnl_amount)*100/current,2)

  estimate_lt = round(sum(df_portfolio_features['LTT']*df_portfolio_features['Shares']),0)  + reserve_amt
  est_lt_pnl_amount = estimate_lt-current
  est_lt_pnl_percentage = round((est_lt_pnl_amount)*100/current,2)

  total_profit = round(sum(df_portfolio_features[df_portfolio_features['Current P/L%'] > 0]['Current']) - sum(df_portfolio_features[df_portfolio_features['Current P/L%'] > 0]['Investment']),0)
  total_loss = round(sum(df_portfolio_features[df_portfolio_features['Current P/L%'] < 0]['Current']) - sum(df_portfolio_features[df_portfolio_features['Current P/L%'] < 0]['Investment']),0)

  cy_booked_percentage = round((cy_booked_amt)*100/current,2)
  py_booked_percentage = round((py_booked_amt)*100/investment,2)
  total_booked_percentage = round((total_booked_amt)*100/investment,2)

  print('-------------------')
  print('Initial Investment: ', format_amt(investment))
  print('CY Investment: ', format_amt(cy_invested))
  print('Reserve: ', format_amt(reserve_amt))
  print('Current: ',  format_amt(current))
  print('-------------------')
  print('Today PnL: '+ '{} ({}%)'.format(format_amt(today_pnl_amount), today_pnl_percentage))
  print('Current PnL: '+ '{} ({}%)'.format(format_amt(curr_pnl_amount), curr_pnl_percentage))
  print('CY Booked + Current PnL: '+ '{} ({}%)'.format(format_amt(cy_pnl_amount), cy_pnl_percentage))
  print('-------------------')
  print('Total profit: ', format_amt(total_profit))
  print('Total loss: ', format_amt(total_loss))
  print('-------------------')
  print('Total Booked + Current PnL: '+ '{} ({}%)'.format(format_amt(overall_pnl_amount), overall_pnl_percentage))
  print('Total Booked PnL: '+ '{} ({}%)'.format(format_amt(total_booked_amt), total_booked_percentage))
  print('Curr Year Booked PnL: '+ '{} ({}%)'.format(format_amt(cy_booked_amt), cy_booked_percentage))
  print('Prev Year Booked PnL: '+ '{} ({}%)'.format(format_amt(py_booked_amt), py_booked_percentage))
  print('===================')
  print('Est FTT: ',  format_amt(estimate_st))
  print('Est FTT PnL: '+ '{} ({}%)'.format(format_amt(est_st_pnl_amount), est_st_pnl_percentage))

  print('===================')
  print('Deployed: ', format_amt(investment))

  print('Current: ', format_amt(current))

  print('CAGR/XIRR %: '+'{}%'.format(cagr))

In [8]:
# get start and end date
start_date, end_date = get_start_end_date()

# get portfolio and prospects data
mypfs_df = get_mypfs_df()
mypps_df = get_mypps_df()
myinvmt_df = get_myinvmt_df()

# merge above datasets
mypf_df = pd.merge(mypfs_df, mypps_df, on="Symbol")

# seggregate dm and sv portfolio
dm_pf = mypf_df[mypf_df['InPortfolio'] == 'DM']
sv_pf = mypf_df[mypf_df['InPortfolio'] == 'SV']

# build portfolio stock dataframe
dm_stocks = get_stock_ids(dm_pf)
sv_stocks = get_stock_ids(sv_pf)
df_stocks = pd.concat([dm_pf,sv_pf], ignore_index = True)

# arrange common and diff stock features
common_cols = ['Symbol', 'Target', 'Criteria', 'Strategy', 'CumlRnk', 'LatestQtr', 'StarStock', 'Conviction', 'Category', 'InFolio', 'XIRR', 'MBQ']
diff_cols = ['Symbol', 'AvgCost', 'Shares']
df_stocks = arrange_features(df_stocks, common_cols, diff_cols)

# get common features
stock_ids = df_stocks['Symbol'].values
df_common_features = get_common_features(stock_ids, df_stocks)

df_common_features.reset_index(drop=True, inplace=True)
df_common_features.drop(['Date'], axis=1, inplace=True)
# get and print portfolio features
df_portfolio_features = get_portfolio_features(df_common_features)

print_portfolio_stats(df_portfolio_features, myinvmt_df)

df = df_portfolio_features
#plot_pie_chart(df, 'CapType', 'Current')
list_ox40n = list(df[df['MBQ'].str.contains('OX40N', na=False)]['Symbol'].values)

Run date time (IST): 2026-03-12 09:44:38
-------------------
qualified stocks: 86
with latest results: 26
still star stocks: 15
-------------------
Initial Investment:  1.36 C
CY Investment:  1.62 C
Reserve:  66.25 K
Current:  1.35 C
-------------------
Today PnL: -2.06 L (-1.51%)
Current PnL: -42.34 L (-26.06%)
CY Booked + Current PnL: -26.66 L (-16.41%)
-------------------
Total profit:  90.94 K
Total loss:  -43.25 L
-------------------
Total Booked + Current PnL: 31.64 K (0.23%)
Total Booked PnL: 42.66 L (31.48%)
Curr Year Booked PnL: 15.68 L (11.65%)
Prev Year Booked PnL: 26.98 L (19.91%)
===================
Est FTT:  2.47 C
Est FTT PnL: 1.13 C (83.74%)
===================
Deployed:  1.36 C
Current:  1.35 C
CAGR/XIRR %: -0.34%

In [9]:
# top 5 near their targets
cols = ['Symbol', 'Today P/L%', 'Current P/L%', 'FTT%', 'OTT%', 'FTT Amt', 'Current P/L', 'Current', 'FTT', 'Dev%_PE', 'RSI_14','Conviction', 'Spread%',  'CumlRnk', 'RRR Ind', 'CurrAlloc%', 'Gained%', 'Criteria', 'Strategy', 'Category']
df_tmp = df_portfolio_features[~df_portfolio_features['Symbol'].isin(['ENRIN','BLUSPRING','DIGITIDE'])]
df_tmp = df_tmp.sort_values(by = 'FTT Amt', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
19,COALINDIA,0.18,10.06,6.92,17.67,11459.0,15134.0,165594.0,478.51,31.99,61.0,L-LC,11.91,185.0,1.32,1.24,28.60,XY25,ATH,MINING
77,TTKPRESTIG,9.20,-23.99,31.69,0.09,24273.0,-24181.0,76596.0,770.00,77.80,61.0,M-SC,15.19,250.0,-1.00,0.57,29.42,OX40N,NTT,DURABLES
50,MASFIN,-1.14,-8.16,32.37,21.57,29128.0,-7995.0,89985.0,397.04,-20.96,37.0,H-SC,4.10,167.0,-0.27,0.67,24.83,XR,ATH,FINANCE
37,ICICIGI,-1.18,-1.84,21.58,19.34,42387.0,-3691.0,196418.0,2252.93,-17.38,41.0,X-MC,1.78,66.0,-0.09,1.47,12.02,X40,ATH,INSURANCE
2,ABBOTINDIA,-1.56,-10.18,31.45,18.07,50524.0,-18205.0,160650.0,35195.00,-23.63,47.0,X-MC,11.09,58.0,-0.36,1.20,1.84,X40,ATH,PHARMA

In [10]:
# top 5 today
df_tmp = df_portfolio_features.sort_values(by = 'Today P/L%', ascending=False)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
77,TTKPRESTIG,9.20,-23.99,31.69,0.09,24273.0,-24181.0,76596.0,770.00,77.80,61.0,M-SC,15.19,250.0,-1.00,0.57,29.42,OX40N,NTT,DURABLES
31,HAPPSTMNDS,1.26,-47.95,255.17,84.85,170209.0,-61461.0,66704.0,1480.71,-38.07,64.0,H-SC,28.28,152.0,-0.36,0.50,23.53,AR,ATH,IT
48,KANSAINER,0.67,-37.16,80.58,13.47,136544.0,-100215.0,169452.0,340.00,-46.01,30.0,H-SC,16.72,162.0,-0.73,1.27,1.59,XY24,NTT,PAINTS
27,FINCABLES,0.33,12.82,84.29,107.91,140402.0,18926.0,166570.0,1641.55,1.47,56.0,M-SC,7.73,220.0,0.13,1.24,25.32,OX40N,ATH,CABLES
19,COALINDIA,0.18,10.06,6.92,17.67,11459.0,15134.0,165594.0,478.51,31.99,61.0,L-LC,11.91,185.0,1.32,1.24,28.60,XY25,ATH,MINING

In [11]:
# bottom 5 today
df_tmp = df_portfolio_features.sort_values(by = 'Today P/L%', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
55,RAJESHEXPO,-4.99,-78.97,375.88,0.07,108423.0,-108332.0,28845.0,518.0,956.82,21.0,L-SC,21.06,268.0,-1.00,0.22,0.00,OX40N,NTT,JEWELLERY
42,INDUSINDBK,-4.52,-38.17,114.91,32.89,54858.0,-29466.0,47740.0,1800.0,-324.79,31.0,L-MC,10.62,258.0,-0.54,0.36,31.47,XR,NTT,BANKS
69,SURYODAY,-3.63,-26.42,67.22,23.03,88564.0,-47318.0,131753.0,216.0,42.54,49.0,H-SC,7.40,166.0,-0.53,0.98,30.73,XR,NTT,BANKS
7,ATULAUTO,-3.06,-27.90,101.89,45.57,144823.0,-54995.0,142137.0,844.0,3067.57,37.0,M-SC,4.99,248.0,-0.38,1.06,7.56,XY24,NTT,AUTO
75,TMPV,-2.94,-25.91,84.33,36.58,222340.0,-92186.0,263655.0,600.0,-84.72,32.0,X-LC,1.78,4.0,-0.41,1.97,0.00,XY24,NTT,AUTO

In [12]:
# top 5 to exit based on CumlRnk
df_tmp = df_portfolio_features[~df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])]
df_tmp = df_tmp[(df_tmp['Current P/L%'] > -1) & (df_tmp['Current P/L%'] < 1)].sort_values(by = 'CumlRnk', ascending=False)
df_tmp[cols].head()

Empty DataFrame
Columns: [Symbol, Today P/L%, Current P/L%, FTT%, OTT%, FTT Amt, Current P/L, Current, FTT, Dev%_PE, RSI_14, Conviction, Spread%, CumlRnk, RRR Ind, CurrAlloc%, Gained%, Criteria, Strategy, Category]
Index: []

In [13]:
# OX40N stocks to exit
df_tmp = df_portfolio_features[(df_portfolio_features['Symbol'].isin(list_ox40n))].sort_values(by = 'Current P/L%', ascending=False)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
27,FINCABLES,0.33,12.82,84.29,107.91,140402.0,18926.0,166570.0,1641.55,1.47,56.0,M-SC,7.73,220.0,0.13,1.24,25.32,OX40N,ATH,CABLES
77,TTKPRESTIG,9.20,-23.99,31.69,0.09,24273.0,-24181.0,76596.0,770.00,77.80,61.0,M-SC,15.19,250.0,-1.00,0.57,29.42,OX40N,NTT,DURABLES
66,SIS,-1.46,-34.03,83.81,21.26,61390.0,-37783.0,73249.0,528.00,1715.03,35.0,H-SC,10.62,168.0,-0.62,0.55,0.98,OX40N,NTT,MISC
48,KANSAINER,0.67,-37.16,80.58,13.47,136544.0,-100215.0,169452.0,340.00,-46.01,30.0,H-SC,16.72,162.0,-0.73,1.27,1.59,XY24,NTT,PAINTS
70,SYMPHONY,-1.18,-37.88,60.94,-0.03,64783.0,-64835.0,106306.0,1306.00,-50.07,45.0,M-SC,13.75,205.0,-1.00,0.79,7.50,OX40N,NTT,DURABLES

In [14]:
# top 5 to book for rotation
df_tmp = df_portfolio_features[(df_portfolio_features['Current P/L%'] > 20) ].sort_values(by = 'CumlRnk', ascending=False)
df_tmp[cols].head()

Empty DataFrame
Columns: [Symbol, Today P/L%, Current P/L%, FTT%, OTT%, FTT Amt, Current P/L, Current, FTT, Dev%_PE, RSI_14, Conviction, Spread%, CumlRnk, RRR Ind, CurrAlloc%, Gained%, Criteria, Strategy, Category]
Index: []

In [15]:
# top 5 to monitor for exit
df_tmp = df_portfolio_features[~df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])]
df_tmp = df_tmp[(df_tmp['Current P/L%'] > 0) ].sort_values(by = 'Dev%_PE', ascending=False)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
19,COALINDIA,0.18,10.06,6.92,17.67,11459.0,15134.0,165594.0,478.51,31.99,61.0,L-LC,11.91,185.0,1.32,1.24,28.60,XY25,ATH,MINING
27,FINCABLES,0.33,12.82,84.29,107.91,140402.0,18926.0,166570.0,1641.55,1.47,56.0,M-SC,7.73,220.0,0.13,1.24,25.32,OX40N,ATH,CABLES
1,ABB,-1.97,12.96,28.87,45.57,85314.0,33893.0,295512.0,7934.00,-27.37,60.0,H-MC,10.36,125.0,0.40,2.21,31.23,AR,NTT,ELECTRICAL

In [16]:
# top 5 to book for rotation from weak conviction
df_tmp = df_portfolio_features[~df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])]
df_tmp = df_tmp[~df_tmp['Criteria'].isin(['XY25','XY24','X40', 'X40N'])].sort_values(by = 'RRR Ind', ascending=False)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
1,ABB,-1.97,12.96,28.87,45.57,85314.0,33893.0,295512.0,7934.00,-27.37,60.0,H-MC,10.36,125.0,0.40,2.21,31.23,AR,NTT,ELECTRICAL
27,FINCABLES,0.33,12.82,84.29,107.91,140402.0,18926.0,166570.0,1641.55,1.47,56.0,M-SC,7.73,220.0,0.13,1.24,25.32,OX40N,ATH,CABLES
40,INDIAMART,-1.39,-9.72,128.99,106.72,143620.0,-11994.0,111342.0,4810.62,-59.38,41.0,H-SC,9.46,140.0,-0.08,0.83,11.38,AR,ATH,MISC
85,ZYDUSLIFE,-0.86,-3.63,40.74,35.63,82279.0,-7613.0,201961.0,1286.17,-16.22,51.0,H-MC,5.02,120.0,-0.09,1.51,12.43,AR,ATH,PHARMA
84,WIPRO,-0.27,-17.28,108.24,72.27,151725.0,-29273.0,140175.0,420.00,-25.49,34.0,M-LC,15.06,98.0,-0.19,1.05,3.22,XR,NTT,IT

In [17]:
# top 5 to accumulate based on lowest RSI_14
df_tmp = df_portfolio_features[df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])].sort_values(by = 'RSI_14', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
58,RELAXO,-1.53,-61.15,292.00,52.31,164688.0,-88760.0,56400.0,1176.00,-58.67,18.0,X-SC,19.58,92.0,-0.54,0.42,0.00,X40N,NTT,FOOTWEAR
12,BATAINDIA,-1.32,-54.25,195.54,35.20,115103.0,-69806.0,58864.0,2096.00,-22.89,20.0,X-SC,26.26,91.0,-0.61,0.44,0.00,X40,NTT,FOOTWEAR
8,AWL,-1.48,-39.14,174.41,67.02,378226.0,-139449.0,216860.0,485.00,-67.29,20.0,X-SC,23.38,81.0,-0.37,1.62,0.65,XY24,NTT,FMCG
3,ACC,-1.61,-35.87,172.58,74.81,296769.0,-96168.0,171960.0,3906.00,-54.32,21.0,X-SC,12.81,85.0,-0.32,1.28,0.00,XY24,BTT,CEMENT
73,TCS,-0.45,-27.97,75.71,26.57,252657.0,-129556.0,333717.0,4311.58,-39.04,21.0,X-LC,14.43,2.0,-0.51,2.49,0.00,X40,ATH,IT

In [18]:
# top 5 to accumulate based on Spread and CumlRnk
df_tmp = df_portfolio_features[df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])]
df_tmp = df_tmp[(df_tmp['CumlRnk'] < 100)].sort_values(by = 'Spread%', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
78,UNITDSPR,-2.76,-1.27,22.32,20.77,51597.0,-2976.0,231168.0,1644.00,-12.48,45.0,X-MC,1.36,64.0,-0.06,1.73,5.35,X40N,NTT,BREWERIES
22,DABUR,-2.03,-9.63,59.00,43.70,132273.0,-23877.0,224191.0,735.00,-17.99,31.0,X-MC,1.50,70.0,-0.18,1.67,3.98,XY24,BTT,FMCG
75,TMPV,-2.94,-25.91,84.33,36.58,222340.0,-92186.0,263655.0,600.00,-84.72,32.0,X-LC,1.78,4.0,-0.41,1.97,0.00,XY24,NTT,AUTO
37,ICICIGI,-1.18,-1.84,21.58,19.34,42387.0,-3691.0,196418.0,2252.93,-17.38,41.0,X-MC,1.78,66.0,-0.09,1.47,12.02,X40,ATH,INSURANCE
59,RELIANCE,0.14,-10.64,40.22,25.30,72227.0,-21382.0,179581.0,1952.00,-13.11,45.0,X-LC,2.74,21.0,-0.30,1.34,19.90,XY25,BTT,REFINERIES

In [19]:
# top 5 to accumulate based on lowest Gained%
df_tmp = df_portfolio_features[df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])].sort_values(by = 'Gained%', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
3,ACC,-1.61,-35.87,172.58,74.81,296769.0,-96168.0,171960.0,3906.00,-54.32,21.0,X-SC,12.81,85.0,-0.32,1.28,0.0,XY24,BTT,CEMENT
12,BATAINDIA,-1.32,-54.25,195.54,35.20,115103.0,-69806.0,58864.0,2096.00,-22.89,20.0,X-SC,26.26,91.0,-0.61,0.44,0.0,X40,NTT,FOOTWEAR
10,BAJAJHLDNG,-2.00,-10.83,44.91,29.22,76141.0,-20584.0,169541.0,14451.52,-17.81,27.0,X-LC,12.26,28.0,-0.27,1.27,0.0,X40,ATH,FINANCE
9,BAJAJHFL,-1.84,-26.57,120.80,62.13,242187.0,-72560.0,200486.0,181.50,-39.53,28.0,X-MC,19.12,60.0,-0.30,1.50,0.0,X40N,ATH,FINANCE
21,COLPAL,-2.42,-23.84,85.80,41.51,172098.0,-62785.0,200580.0,3726.84,-7.87,34.0,X-MC,4.14,62.0,-0.36,1.50,0.0,XY25,ATH,FMCG

In [20]:
# top 5 to accumulate based on lowest CurrAlloc%
df_tmp = df_portfolio_features[df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])].sort_values(by = 'CurrAlloc%', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
58,RELAXO,-1.53,-61.15,292.00,52.31,164688.0,-88760.0,56400.0,1176.00,-58.67,18.0,X-SC,19.58,92.0,-0.54,0.42,0.00,X40N,NTT,FOOTWEAR
12,BATAINDIA,-1.32,-54.25,195.54,35.20,115103.0,-69806.0,58864.0,2096.00,-22.89,20.0,X-SC,26.26,91.0,-0.61,0.44,0.00,X40,NTT,FOOTWEAR
54,QUESS,-2.75,-22.97,125.75,73.90,103448.0,-24528.0,82265.0,424.00,-58.68,39.0,X-SC,18.40,80.0,-0.24,0.61,1.48,XY24,NTT,MISC
36,HONAUT,-0.85,-21.20,92.03,51.31,139840.0,-40888.0,151950.0,58357.33,-34.47,41.0,X-SC,13.81,90.0,-0.29,1.13,2.32,X40N,ATH,ELECTRICAL
2,ABBOTINDIA,-1.56,-10.18,31.45,18.07,50524.0,-18205.0,160650.0,35195.00,-23.63,47.0,X-MC,11.09,58.0,-0.36,1.20,1.84,X40,ATH,PHARMA

In [21]:
# top 5 to accumulate based on CumlRnk
df_tmp = df_portfolio_features.sort_values(by = 'CumlRnk', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
45,ITC,-0.95,-19.39,47.69,19.06,130776.0,-65945.0,274221.0,452.00,-55.92,35.0,X-LC,17.03,1.0,-0.50,2.05,0.02,X40,NTT,FMCG
73,TCS,-0.45,-27.97,75.71,26.57,252657.0,-129556.0,333717.0,4311.58,-39.04,21.0,X-LC,14.43,2.0,-0.51,2.49,0.00,X40,ATH,IT
43,INFY,-0.72,-13.74,55.63,34.24,150141.0,-42996.0,269892.0,1972.00,-32.15,25.0,X-LC,12.74,3.0,-0.29,2.02,0.00,X40,NTT,IT
75,TMPV,-2.94,-25.91,84.33,36.58,222340.0,-92186.0,263655.0,600.00,-84.72,32.0,X-LC,1.78,4.0,-0.41,1.97,0.00,XY24,NTT,AUTO
34,HCLTECH,-0.53,-12.84,42.07,23.83,88712.0,-31057.0,210867.0,1908.19,-8.60,26.0,X-LC,9.83,8.0,-0.35,1.57,1.17,X40,ATH,IT

In [22]:
# top 5 for average up
df_tmp = df_portfolio_features[(df_portfolio_features['Dev%_200'] > 5)].sort_values(by = 'CurrAlloc%', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
67,SONACOMS,-2.10,-12.55,59.05,39.09,52237.0,-12697.0,88462.0,804.02,-30.73,46.0,M-MC,9.79,193.0,-0.24,0.66,25.15,AR,ATH,AUTO
27,FINCABLES,0.33,12.82,84.29,107.91,140402.0,18926.0,166570.0,1641.55,1.47,56.0,M-SC,7.73,220.0,0.13,1.24,25.32,OX40N,ATH,CABLES
19,COALINDIA,0.18,10.06,6.92,17.67,11459.0,15134.0,165594.0,478.51,31.99,61.0,L-LC,11.91,185.0,1.32,1.24,28.60,XY25,ATH,MINING
11,BANDHANBNK,-1.63,-13.66,122.85,92.42,295475.0,-38042.0,240517.0,400.00,106.18,58.0,H-SC,9.90,174.0,-0.13,1.80,32.49,XY24,NTT,BANKS
1,ABB,-1.97,12.96,28.87,45.57,85314.0,33893.0,295512.0,7934.00,-27.37,60.0,H-MC,10.36,125.0,0.40,2.21,31.23,AR,NTT,ELECTRICAL

In [23]:
# top 5 RSP
df_tmp = df_portfolio_features.sort_values(by = 'RSP', ascending=False)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
31,HAPPSTMNDS,1.26,-47.95,255.17,84.85,170209.0,-61461.0,66704.0,1480.71,-38.07,64.0,H-SC,28.28,152.0,-0.36,0.50,23.53,AR,ATH,IT
27,FINCABLES,0.33,12.82,84.29,107.91,140402.0,18926.0,166570.0,1641.55,1.47,56.0,M-SC,7.73,220.0,0.13,1.24,25.32,OX40N,ATH,CABLES
19,COALINDIA,0.18,10.06,6.92,17.67,11459.0,15134.0,165594.0,478.51,31.99,61.0,L-LC,11.91,185.0,1.32,1.24,28.60,XY25,ATH,MINING
26,EASEMYTRIP,-1.50,-60.04,264.64,45.70,186963.0,-106167.0,70648.0,26.40,-26.57,42.0,M-SC,18.20,204.0,-0.57,0.53,16.40,XY24,NTT,TRAVEL
1,ABB,-1.97,12.96,28.87,45.57,85314.0,33893.0,295512.0,7934.00,-27.37,60.0,H-MC,10.36,125.0,0.40,2.21,31.23,AR,NTT,ELECTRICAL

In [24]:
# Top N allocation
df_tmp = df_portfolio_features.sort_values(by = 'CurrAlloc%', ascending=False)
top_n_values = [10, 25, 50]

sum_df = pd.DataFrame({
    'Top_N': top_n_values,
    'Sum_Alloc%': [df_tmp['CurrAlloc%'].head(n).sum() for n in top_n_values]
})

sum_df

   Top_N  Sum_Alloc%
0     10       20.47
1     25       45.29
2     50       77.79

In [25]:
# market-cap-wise allocation
df_tmp = df_portfolio_features[cols]
df_tmp.groupby(df_tmp['Conviction'].str[-2:])['CurrAlloc%'].sum().sort_values(ascending=False)

Conviction
SC    44.74
MC    30.34
LC    24.98
Name: CurrAlloc%, dtype: float64

In [26]:
# criteria-wise allocation
df_portfolio_features.groupby('Criteria')['CurrAlloc%'].sum().sort_values(ascending=False)

Criteria
XY24     27.22
X40      23.85
X40N     15.09
AR        9.23
XY25      8.62
XR        8.27
OX40N     7.00
SR        0.78
Name: CurrAlloc%, dtype: float64

In [27]:
# conviction-wise allocation
df_portfolio_features.groupby('Conviction')['CurrAlloc%'].sum().sort_values(ascending=False)

Conviction
X-MC    22.98
H-SC    21.74
X-LC    21.47
X-SC    12.13
M-SC    10.28
H-MC     4.99
M-MC     2.01
L-LC     1.24
H-LC     1.22
M-LC     1.05
L-SC     0.59
L-MC     0.36
Name: CurrAlloc%, dtype: float64

In [28]:
# sector-wise stats
df_tmp = df_portfolio_features.groupby('Category')[['CurrAlloc%', 'Current', 'Current P/L', 'FTT Amt']].sum().sort_values(by=['Current', 'Current P/L'], ascending=False)
df_tmp['Current P/L%'] = round(df_tmp['Current P/L'] * 100 / df_tmp['Current'], 2)
df_tmp['FTT%'] = round(df_tmp['FTT Amt'] * 100 / df_tmp['Current'], 2)
cols = ['CurrAlloc%', 'Current P/L%', 'FTT%']
df_tmp[cols].sort_values(by=['CurrAlloc%'], ascending=False)

               CurrAlloc%  Current P/L%    FTT%
Category
FMCG                15.20        -22.70   66.26
FINANCE             12.81        -25.44   76.56
IT                  11.76        -43.10  115.93
MISC                 6.99        -43.22  105.44
ELECTRICAL           6.67         -8.43   49.95
PAINTS               5.22        -41.37   65.91
INSURANCE            4.70         -7.91   44.84
PHARMA               4.18         -5.06   38.13
AUTO                 3.69        -32.35   84.86
BANKS                3.14        -27.34  104.50
AC                   2.15        -11.01   41.10
HEALTHCARE           1.97        -35.50   70.86
DURABLES             1.96        -46.84   82.57
FOOTWEAR             1.85        -78.59  150.20
TRAVEL               1.80        -85.64  178.59
BREWERIES            1.73         -1.29   22.32
APPARELS             1.62        -23.40   65.49
REALTY               1.45        -14.34   33.13
REFINERIES           1.34        -11.91   40.22
CERAMICS             1.34        -71.33  123.37
CEMENT               1.28        -55.92  172.58
CABLES               1.24         11.36   84.29
MINING               1.24          9.14    6.92
JEWELLERY            1.11       -115.25  190.04
ENGINEERING          1.09        -65.81  141.65
CHEMICALS            0.97       -105.06  272.36
ENTERTAINMENT        0.77        -89.22  202.07
TEXTILES             0.42        -64.83  111.83
HOTELS               0.37       -129.23  210.08

In [29]:
# money to be made criteria-wise
df_portfolio_features.groupby('Criteria')['FTT Amt'].agg(['sum', 'count']).sort_values(by='sum', ascending=False)

                sum  count
Criteria
XY24      3954284.0     21
X40       1680864.0     15
XR        1384414.0     12
AR        1336515.0     10
X40N      1279630.0     10
OX40N      856016.0     10
XY25       462824.0      6
SR         315571.0      2

In [30]:
# money to be made conviction-wise
df_portfolio_features.groupby('Conviction')['FTT Amt'].agg(['sum', 'count']).sort_values(by='sum', ascending=False)

                  sum  count
Conviction
H-SC        3885193.0     24
X-MC        1657472.0     15
X-LC        1600689.0     12
X-SC        1556824.0     10
M-SC        1541826.0     14
H-MC         410962.0      3
L-SC         212488.0      2
M-LC         151725.0      1
M-MC         116662.0      2
H-LC          69960.0      1
L-MC          54858.0      1
L-LC          11459.0      1

In [31]:
# money to be made criteria and conviction-wise
df_portfolio_features.groupby(['Conviction', 'Criteria'])['FTT Amt'].agg(['sum', 'count']).sort_values(by='sum', ascending=False)

                           sum  count
Conviction Criteria
H-SC       XY24      1327452.0      6
           AR         969060.0      5
M-SC       XY24       915912.0      6
H-SC       XR         882787.0      7
X-SC       XY24       839686.0      4
X-LC       X40        825719.0      6
X-MC       X40        646424.0      7
           X40N       520533.0      4
X-SC       X40N       508417.0      4
H-SC       OX40N      390323.0      4
X-LC       XY24       373114.0      2
M-SC       OX40N      357270.0      5
H-SC       SR         315571.0      2
X-MC       XY24       254751.0      2
X-LC       X40N       250680.0      2
H-MC       XY24       243369.0      1
X-MC       XY25       235764.0      2
X-SC       X40        208721.0      2
M-SC       XR         190979.0      2
H-MC       AR         167593.0      2
M-LC       XR         151725.0      1
X-LC       XY25       151176.0      2
L-SC       OX40N      108423.0      1
           XR         104065.0      1
M-SC       AR          77665.0      1
H-LC       AR          69960.0      1
M-MC       XY25        64425.0      1
L-MC       XR          54858.0      1
M-MC       AR          52237.0      1
L-LC       XY25        11459.0      1

In [32]:
# notebook execution time

end_time = time.time()
execution_time = round(end_time - start_time, 0)
print(f"Notebook execution time: {execution_time} seconds")

Notebook execution time: 49.0 seconds