<a href="https://colab.research.google.com/github/ankit-rathi/Quantvesting_v2/blob/main/myStocks_Portfolio_Analysis.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
'''
!pip install pandas==2.2.2 -qq
!pip install pyxirr -qq
!pip install ta -qq
!pip install yfinance==0.2.59 -qq
'''

'\n!pip install pandas==2.2.2 -qq\n!pip install pyxirr -qq\n!pip install ta -qq\n!pip install yfinance==0.2.59 -qq\n'

In [2]:
# import libraries

import numpy as np
import pandas as pd
import datetime
import warnings
warnings.filterwarnings('ignore')
import yfinance as yfin
import ta
import matplotlib.pyplot as plt
import requests

In [3]:
# notebook start time
import time
import datetime
import pytz

start_time = time.time()

# function to print date timestamp
def print_date_time():
  tz_NY = pytz.timezone('Asia/Kolkata')
  datetime_NY = datetime.datetime.now(tz_NY)
  print("Run date time (IST):", datetime_NY.strftime("%Y-%m-%d %H:%M:%S"))

In [4]:
# function to get booked and reserved amount
def get_amt():
  # fetch the JSON data from the URL
  url = "https://raw.githubusercontent.com/ankit-rathi/Tradevesting_v1/main/data/myPortfolioAmts.json"
  response = requests.get(url)
  pf_amts = response.json()  # parse the JSON data

  # extract values from the JSON
  py_booked_amt_dm = pf_amts["py_booked_amt_dm"]
  py_booked_amt_sv = pf_amts["py_booked_amt_sv"]
  cy_booked_amt_dm = pf_amts["cy_booked_amt_dm"]
  cy_booked_amt_sv = pf_amts["cy_booked_amt_sv"]
  reserve_amt_dm = pf_amts["reserve_amt_dm"]
  reserve_amt_sv = pf_amts["reserve_amt_sv"]

  # perform calculations
  py_booked_amt = py_booked_amt_dm + py_booked_amt_sv
  cy_booked_amt = cy_booked_amt_dm + cy_booked_amt_sv
  reserve_amt = reserve_amt_dm + reserve_amt_sv
  total_booked_amt = py_booked_amt + cy_booked_amt

  return total_booked_amt, reserve_amt, cy_booked_amt, py_booked_amt

gen_output = 0

In [5]:
# function to format the amount
def format_amt(number):
    abs_number = abs(number)

    if abs_number >= 1_00_00_000:  # Crores
        formatted_amt = f"{number / 1_00_00_000:.2f} C"
    elif abs_number >= 1_00_000:  # Lakhs
        formatted_amt = f"{number / 1_00_000:.2f} L"
    elif abs_number >= 1_000:  # Thousands
        formatted_amt = f"{number / 1_000:.2f} K"
    else:
        formatted_amt = f"{number:.2f}"

    return formatted_amt

# function to set start and end date
def get_start_end_date():
  start_date = (datetime.date.today() + datetime.timedelta(days=-365)).strftime('%Y-%m-%d')
  end_date = (datetime.date.today() + datetime.timedelta(days=1)).strftime('%Y-%m-%d')
  return start_date, end_date

# function to fetch my portfolio csv
def get_mypfs_df():
  mypfs_df = pd.read_csv('https://raw.githubusercontent.com/ankit-rathi/Tradevesting_v1/main/data/myPortfolioStocks.csv')
  return mypfs_df

# function to fetch my prospects csv
def get_mypps_df():
  mypps_df = pd.read_csv('https://raw.githubusercontent.com/ankit-rathi/Tradevesting_v1/main/data/myProspectsScrips.csv')
  return mypps_df

# function to fetch screener data
def get_myscreen_df():
  myscreen_df = pd.read_csv('https://raw.githubusercontent.com/ankit-rathi/Tradevesting_v1/main/data/myScreenerDB.csv')
  return myscreen_df

# function to fetch momentum data
def get_myinvmt_df():
  myinvmt_df = pd.read_csv('https://raw.githubusercontent.com/ankit-rathi/Tradevesting_v1/main/data/myInvestments.csv')
  return myinvmt_df

# function to get the stock ids
def get_stock_ids(df_pf):
  stock_n100 = df_pf['Symbol'].unique()

  exclude = ['CADILAHC','MMTC', 'MASFIN']

  stock_ids = df_pf[~df_pf['Symbol'].isin(exclude) ]['Symbol'].unique()

  #mypf = mypf[mypf.Forecast.notnull()]
  #stock_ids = mypf['Symbol'].unique()

  #stock_ids.sort()
  return stock_ids

# get features from screener data
def get_screener_features():
  myscreen_df = get_myscreen_df()
  cols = ['Symbol', 'EPS', 'MedPE', 'ROCE%', 'ROE%', 'CapType']
  return myscreen_df[cols]

# get relative strength
def get_relative_strength(stock_list):

    # Dictionary to store stock tickers and their corresponding percentage price change
    stock_changes = {}

    # Loop through each stock and fetch its price data
    for stock in stock_list:
        try:
            # Download the stock data for the given date range
            stock_data = yfin.Ticker(stock + '.NS').history(period='1mo', interval='1d')[map(str.title, ['open', 'close', 'low', 'high', 'volume'])]

            # Calculate the percentage change for the stock
            if len(stock_data) > 0:
                start_price = stock_data['Close'].iloc[0]
                end_price = stock_data['Close'].iloc[-1]
                percent_change = round(((end_price - start_price) / start_price) * 100, 2)
                stock_changes[stock] = percent_change
            else:
                stock_changes[stock] = np.nan  # If no data is available, set to NaN

        except Exception as e:
            print(f"Error fetching data for {stock}: {e}")
            stock_changes[stock] = np.nan

    # Create a DataFrame with stock tickers and their percentage changes
    df = pd.DataFrame(list(stock_changes.items()), columns=['Symbol', 'Percent_Change'])

    # Drop any stocks with missing data (NaN values)
    df = df.dropna()

    # Calculate the percentile rank based on percentage change
    df['RSP'] = round(df['Percent_Change'].rank(pct=True) * 100, 2)
    cols = ['Symbol', 'RSP']
    df = df[cols]
    # Sort by percentile rank (optional)
    df = df.sort_values(by='RSP', ascending=False).reset_index(drop=True)

    return df

In [6]:
# function to get stock technicals
def stock_prec_dev(stock_symbol):
    #stock_symbol = 'ULTRACEMCO.NS'
    short_window = 20
    mid_window = 50
    long_window = 200
    moving_avg = 'SMA'

    start = datetime.datetime(*map(int, start_date.split('-')))
    end = datetime.datetime(*map(int, end_date.split('-')))

    stock_df = yfin.Ticker(stock_symbol + '.NS').history(period='max', interval='1d')[map(str.title, ['open', 'close', 'low', 'high', 'volume'])]

    stock_df['Max'] = round(max(stock_df['Close']),2)
    stock_df = stock_df[(stock_df.index <= end_date) & (stock_df.index >= start_date)]
    stock_df['200_SMA'] = round(stock_df['Close'].rolling(window = 200, min_periods = 1).mean(),0)
    stock_df['Dev%_200'] = round((stock_df['Close'] - stock_df['200_SMA'])*100/stock_df['200_SMA'],2)
    stock_df.dropna(axis = 0, inplace = True) # remove any null rows

    stock_df['20_SMA'] = stock_df['Close'].rolling(window=20).mean()
    stock_df['50_SMA'] = stock_df['Close'].rolling(window=50).mean()
    stock_df['Symbol'] = stock_symbol

    stock_df['Close'] = round(stock_df['Close'],2)
    stock_df['Min'] = round(min(stock_df['Close']),2)
    stock_df['RSI_14'] = ta.momentum.RSIIndicator(close=stock_df['Close'], window=14).rsi()
    stock_df['RSI_14'] = round(stock_df['RSI_14'],0)
    stock_df['Prev_Close'] = stock_df['Close'].shift(1)
    stock_df.drop(['Open', 'Low', 'High', 'Volume'], axis=1, inplace=True)
    stock_df = stock_df.tail(1)

    max_SMA = max(stock_df['20_SMA'].item(), stock_df['50_SMA'].item(), stock_df['200_SMA'].item())
    min_SMA = min(stock_df['20_SMA'].item(), stock_df['50_SMA'].item(), stock_df['200_SMA'].item())
    ABS_Spread = max_SMA - min_SMA
    stock_df['Spread%'] = round((ABS_Spread / stock_df['200_SMA'].item()) * 100,2)

    return stock_df

# function to compute stock attributes
def get_common_features(stock_ids, df_mypf):

  df_prec_dev = pd.DataFrame()
  df_tmp = get_screener_features()
  df_rs = get_relative_strength(stock_ids)

  for stock_id in stock_ids:
      tmp = stock_prec_dev(stock_id)
      tmp = tmp.reset_index()
      df_prec_dev = pd.concat([df_prec_dev, tmp], ignore_index = True)
  df_prec_dev = pd.merge(df_prec_dev, df_mypf, on= 'Symbol')
  df_prec_dev = pd.merge(df_prec_dev, df_tmp, on= 'Symbol', how='left')
  df_prec_dev = pd.merge(df_prec_dev, df_rs, on= 'Symbol', how='left')
  #print(df_prec_dev.columns)
  df_prec_dev['Curr_PE'] = round(df_prec_dev['Close']/df_prec_dev['EPS'],1)
  df_prec_dev['Dev%_PE'] = round((df_prec_dev['Curr_PE'] - df_prec_dev['MedPE'])*100/df_prec_dev['MedPE'],2)
  df_prec_dev['Conviction'] = df_prec_dev['Conviction'] + '-' + df_prec_dev['CapType']
  return df_prec_dev

# function to arrange stock features
def arrange_features(df_stocks, common_cols, diff_cols):
  df_stocks_common = df_stocks[common_cols].drop_duplicates()
  df_stocks_diff = df_stocks[diff_cols]
  df_stocks_diff['Investment'] = df_stocks_diff['AvgCost'] * df_stocks_diff['Shares']
  df_stocks_diff = df_stocks_diff.groupby(['Symbol'])[['Shares', 'Investment']].aggregate(['sum']).reset_index()
  df_stocks_diff.columns = ['Symbol', 'Shares', 'Investment']
  df_stocks_diff['AvgCost'] = round(df_stocks_diff['Investment']/df_stocks_diff['Shares'],2)
  df_stocks = pd.merge(df_stocks_diff, df_stocks_common, on='Symbol')
  return df_stocks

# plot fact distribution across dimension
def plot_pie_chart(df, dimension, fact):
  # grouping the data by category and calculating the sum of fact for each type
  grouped_data = df.groupby(dimension)[fact].sum()

  # sorting the grouped data in descending order
  grouped_data = grouped_data.sort_values(ascending=False)

  # creating a pie chart
  grouped_data.plot.pie(autopct='%1.1f%%', startangle=90, figsize=(6, 6))

  # adding a title and displaying the plot
  plt.title(f'{dimension} {fact} Distribution')
  plt.ylabel('')  # To hide the y-label
  plt.show()

In [7]:
# function to get portfolio features

def get_portfolio_features(df_common_features):

  print_date_time()
  print('-------------------')

  #df_common_features["Target"] = df_common_features["Target"].fillna(df_common_features["Max"])
  df_common_features['NTT'] = np.where(df_common_features['Strategy']== 'NTT', df_common_features["Target"], df_common_features['Max'])
  df_common_features['LTT'] = np.where(df_common_features['Strategy']== 'BTT', df_common_features["Target"], df_common_features['Max'])
  df_common_features['BOL'] = df_common_features['Min']

  tmp_df = df_common_features[df_common_features['Symbol'].isin(mypf_df[mypf_df['InPortfolio'] != 'NA'].Symbol.values)]
  print('qualified stocks: '+str(len(tmp_df['Symbol'].unique())))
  tmp_df1 = tmp_df[tmp_df['LatestQtr'] == 1]
  print('with latest results: '+str(len(tmp_df1['Symbol'].unique())))
  tmp_df1 = tmp_df1[tmp_df1['StarStock'] == 1]
  print('still star stocks: '+str(len(tmp_df1['Symbol'].unique())))
  tmp_df['Investment'] = tmp_df['AvgCost'] * tmp_df['Shares']
  tmp_df['Current'] = round(tmp_df['Close'] * tmp_df['Shares'],0)
  tmp_df['Previous'] = tmp_df['Prev_Close'] * tmp_df['Shares']
  tmp_df['EstimatedST'] = tmp_df['NTT'] * tmp_df['Shares']
  tmp_df['EstimatedLT'] = tmp_df['LTT'] * tmp_df['Shares']
  tmp_df['Current P/L'] = round((tmp_df['Current'] - tmp_df['Investment']),0)
  tmp_df['Today P/L%'] = round((tmp_df['Current'] - tmp_df['Previous'])*100/tmp_df['Previous'],2)
  tmp_df['Current P/L%'] = round((tmp_df['Current'] - tmp_df['Investment'])*100/tmp_df['Investment'],2)
  tmp_df['EstimatedST P/L%'] = round((tmp_df['EstimatedST'] - tmp_df['Investment'])*100/tmp_df['Investment'],2)
  tmp_df['EstimatedLT P/L%'] = round((tmp_df['EstimatedLT'] - tmp_df['Investment'])*100/tmp_df['Investment'],2)
  tmp_df['NTT%'] = round((tmp_df['NTT'] - tmp_df['Close'])*100/tmp_df['Close'],2)
  tmp_df['LTT%'] = round((tmp_df['LTT'] - tmp_df['Close'])*100/tmp_df['Close'],2)
  tmp_df['Gained%'] = round((tmp_df['Close'] - tmp_df['BOL'])*100/tmp_df['BOL'],2)
  investment = round(sum(tmp_df['AvgCost']*tmp_df['Shares']),0)
  current = round(sum(tmp_df['Close']*tmp_df['Shares']),0)
  tmp_df['InitAlloc%'] = round(tmp_df['Investment']*100/investment,2)
  tmp_df['CurrAlloc%'] = round(tmp_df['Current']*100/current,2)
  tmp_df['FTT'] = tmp_df['LTT']
  tmp_df.loc[tmp_df['Strategy'] == 'NTT', 'FTT'] = tmp_df['NTT']
  tmp_df['FTT%'] = tmp_df['LTT%']
  tmp_df.loc[tmp_df['Strategy'] == 'NTT', 'FTT%'] = tmp_df['NTT%']
  tmp_df['FTT Amt'] = round(tmp_df['FTT%'] * tmp_df['Current']/100,0)
  tmp_df['OTT%'] = round((tmp_df['FTT'] - tmp_df['AvgCost'])*100/tmp_df['AvgCost'],2)
  tmp_df['RRR Ind'] = round(tmp_df['Current P/L']/tmp_df['FTT Amt'],2)
  tmp_df['Risk Ind'] = round(tmp_df['Current P/L%']*tmp_df['CurrAlloc%'],0)

  return tmp_df

# function to print portfolio features
def print_portfolio_stats(df_portfolio_features, myinvmt_df):
  from pyxirr import xirr

  total_booked_amt, reserve_amt, cy_booked_amt, py_booked_amt = get_amt()

  dates = myinvmt_df['Date'].values
  dates = np.append(dates, datetime.date.today().strftime('%d-%b-%y'))
  investment = myinvmt_df['Investment'].values
  dates= pd.to_datetime(dates)

  current = round(sum(df_portfolio_features['Close']*df_portfolio_features['Shares']),0) + reserve_amt
  investment_xirr = np.append(investment, current)
  cagr = round(xirr(pd.DataFrame({"dates": dates, "amounts": investment_xirr}))*100,2)

  investment = -sum(investment)
  invested = round(sum(df_portfolio_features['AvgCost']*df_portfolio_features['Shares']),0) + reserve_amt
  previous = round(sum(df_portfolio_features['Prev_Close']*df_portfolio_features['Shares']),0) + reserve_amt
  cy_invested = investment + py_booked_amt

  today_pnl_amount = current-previous
  today_pnl_percentage = round((current-previous)*100/previous,2)

  curr_pnl_amount = current-invested
  curr_pnl_percentage = round((curr_pnl_amount)*100/(cy_invested),2)

  cy_pnl_amount = cy_booked_amt + curr_pnl_amount
  cy_pnl_percentage = round((cy_pnl_amount)*100/cy_invested,2)

  overall_pnl_amount = total_booked_amt + curr_pnl_amount
  overall_pnl_percentage = round((overall_pnl_amount)*100/investment,2)

  estimate_st = round(sum(df_portfolio_features['FTT']*df_portfolio_features['Shares']),0)  + reserve_amt
  est_st_pnl_amount = estimate_st-current
  est_st_pnl_percentage = round((est_st_pnl_amount)*100/current,2)

  estimate_lt = round(sum(df_portfolio_features['LTT']*df_portfolio_features['Shares']),0)  + reserve_amt
  est_lt_pnl_amount = estimate_lt-current
  est_lt_pnl_percentage = round((est_lt_pnl_amount)*100/current,2)

  total_profit = round(sum(df_portfolio_features[df_portfolio_features['Current P/L%'] > 0]['Current']) - sum(df_portfolio_features[df_portfolio_features['Current P/L%'] > 0]['Investment']),0)
  total_loss = round(sum(df_portfolio_features[df_portfolio_features['Current P/L%'] < 0]['Current']) - sum(df_portfolio_features[df_portfolio_features['Current P/L%'] < 0]['Investment']),0)

  cy_booked_percentage = round((cy_booked_amt)*100/current,2)
  py_booked_percentage = round((py_booked_amt)*100/investment,2)
  total_booked_percentage = round((total_booked_amt)*100/investment,2)

  print('-------------------')
  print('Initial Investment: ', format_amt(investment))
  print('CY Investment: ', format_amt(cy_invested))
  print('Reserve: ', format_amt(reserve_amt))
  print('Current: ',  format_amt(current))
  print('-------------------')
  print('Today PnL: '+ '{} ({}%)'.format(format_amt(today_pnl_amount), today_pnl_percentage))
  print('Current PnL: '+ '{} ({}%)'.format(format_amt(curr_pnl_amount), curr_pnl_percentage))
  print('CY Booked + Current PnL: '+ '{} ({}%)'.format(format_amt(cy_pnl_amount), cy_pnl_percentage))
  print('-------------------')
  print('Total profit: ', format_amt(total_profit))
  print('Total loss: ', format_amt(total_loss))
  print('-------------------')
  print('Total Booked + Current PnL: '+ '{} ({}%)'.format(format_amt(overall_pnl_amount), overall_pnl_percentage))
  print('Total Booked PnL: '+ '{} ({}%)'.format(format_amt(total_booked_amt), total_booked_percentage))
  print('Curr Year Booked PnL: '+ '{} ({}%)'.format(format_amt(cy_booked_amt), cy_booked_percentage))
  print('Prev Year Booked PnL: '+ '{} ({}%)'.format(format_amt(py_booked_amt), py_booked_percentage))
  print('===================')
  print('Est FTT: ',  format_amt(estimate_st))
  print('Est FTT PnL: '+ '{} ({}%)'.format(format_amt(est_st_pnl_amount), est_st_pnl_percentage))

  print('===================')
  print('Deployed: ', format_amt(investment))

  print('Current: ', format_amt(current))

  print('CAGR/XIRR %: '+'{}%'.format(cagr))

In [8]:
# get start and end date
start_date, end_date = get_start_end_date()

# get portfolio and prospects data
mypfs_df = get_mypfs_df()
mypps_df = get_mypps_df()
myinvmt_df = get_myinvmt_df()

# merge above datasets
mypf_df = pd.merge(mypfs_df, mypps_df, on="Symbol")

# seggregate dm and sv portfolio
dm_pf = mypf_df[mypf_df['InPortfolio'] == 'DM']
sv_pf = mypf_df[mypf_df['InPortfolio'] == 'SV']

# build portfolio stock dataframe
dm_stocks = get_stock_ids(dm_pf)
sv_stocks = get_stock_ids(sv_pf)
df_stocks = pd.concat([dm_pf,sv_pf], ignore_index = True)

# arrange common and diff stock features
common_cols = ['Symbol', 'Target', 'Criteria', 'Strategy', 'CumlRnk', 'LatestQtr', 'StarStock', 'Conviction', 'Category', 'InFolio', 'XIRR', 'MBQ']
diff_cols = ['Symbol', 'AvgCost', 'Shares']
df_stocks = arrange_features(df_stocks, common_cols, diff_cols)

# get common features
stock_ids = df_stocks['Symbol'].values
df_common_features = get_common_features(stock_ids, df_stocks)

df_common_features.reset_index(drop=True, inplace=True)
df_common_features.drop(['Date'], axis=1, inplace=True)
# get and print portfolio features
df_portfolio_features = get_portfolio_features(df_common_features)

print_portfolio_stats(df_portfolio_features, myinvmt_df)

df = df_portfolio_features
#plot_pie_chart(df, 'CapType', 'Current')
list_ox40n = list(df[df['MBQ'].str.contains('OX40N', na=False)]['Symbol'].values)

Run date time (IST): 2026-04-08 11:41:40
-------------------
qualified stocks: 86
with latest results: 26
still star stocks: 16
-------------------
Initial Investment:  1.36 C
CY Investment:  1.62 C
Reserve:  1.61 K
Current:  1.36 C
-------------------
Today PnL: 4.61 L (3.5%)
Current PnL: -40.89 L (-25.17%)
CY Booked + Current PnL: -25.00 L (-15.39%)
-------------------
Total profit:  94.83 K
Total loss:  -41.84 L
-------------------
Total Booked + Current PnL: 1.98 L (1.46%)
Total Booked PnL: 42.87 L (31.64%)
Curr Year Booked PnL: 15.89 L (11.66%)
Prev Year Booked PnL: 26.98 L (19.91%)
===================
Est FTT:  2.48 C
Est FTT PnL: 1.12 C (81.95%)
===================
Deployed:  1.36 C
Current:  1.36 C
CAGR/XIRR %: 0.26%

In [9]:
# top 5 near their targets
cols = ['Symbol', 'Today P/L%', 'Current P/L%', 'FTT%', 'OTT%', 'FTT Amt', 'Current P/L', 'Current', 'FTT', 'Dev%_PE', 'RSI_14','Conviction', 'Spread%',  'CumlRnk', 'RRR Ind', 'CurrAlloc%', 'Gained%', 'Criteria', 'Strategy', 'Category']
df_tmp = df_portfolio_features[~df_portfolio_features['Symbol'].isin(['ENRIN','BLUSPRING','DIGITIDE'])]
df_tmp = df_tmp.sort_values(by = 'FTT Amt', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
50,MASFIN,5.08,-3.70,26.24,21.57,24757.0,-3630.0,94350.0,397.04,-16.89,56.0,H-SC,4.82,167.0,-0.15,0.69,24.14,XR,ATH,FINANCE
77,TTKPRESTIG,3.08,-36.94,58.73,0.09,37322.0,-37229.0,63548.0,770.00,47.49,50.0,M-SC,22.11,250.0,-1.00,0.47,13.16,OX40N,NTT,DURABLES
67,SONACOMS,3.76,-7.53,50.42,39.09,47162.0,-7621.0,93538.0,804.02,-26.68,60.0,M-MC,7.69,193.0,-0.16,0.69,32.32,AR,ATH,AUTO
37,ICICIGI,2.70,-6.07,27.05,19.34,50843.0,-12150.0,187959.0,2252.93,-21.06,46.0,X-MC,6.86,66.0,-0.24,1.38,4.98,X40,ATH,INSURANCE
42,INDUSINDBK,6.47,-38.31,115.41,32.89,54969.0,-29578.0,47629.0,1800.00,-324.09,50.0,L-MC,7.67,258.0,-0.54,0.35,23.14,XR,NTT,BANKS

In [10]:
# top 5 today
df_tmp = df_portfolio_features.sort_values(by = 'Today P/L%', ascending=False)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
25,EASEMYTRIP,16.22,-56.90,238.03,45.70,181403.0,-100605.0,76210.0,26.4,-20.98,61.0,M-SC,14.64,204.0,-0.55,0.56,33.50,XY24,NTT,TRAVEL
14,BOSCH-HCIL,9.99,-44.05,78.73,-0.01,56293.0,-56304.0,71501.0,2282.0,14530.43,53.0,M-SC,9.53,231.0,-1.00,0.52,21.70,OX40N,BTT,AC
19,COFFEEDAY,8.72,-56.80,213.11,35.27,104543.0,-64493.0,49056.0,80.0,-67.81,50.0,L-SC,32.96,266.0,-0.62,0.36,20.98,XR,NTT,HOTELS
11,BANDHANBNK,8.48,-22.18,147.25,92.42,319216.0,-61774.0,216785.0,400.0,86.06,52.0,H-SC,2.43,174.0,-0.19,1.59,19.42,XY24,NTT,BANKS
75,TMPV,8.08,-24.05,79.83,36.58,215745.0,-85585.0,270256.0,600.0,-84.72,54.0,X-LC,12.43,4.0,-0.40,1.98,12.64,XY24,NTT,AUTO

In [11]:
# bottom 5 today
df_tmp = df_portfolio_features.sort_values(by = 'Today P/L%', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
24,DMART,-1.34,5.92,22.36,29.60,59112.0,14766.0,264366.0,5391.45,-10.68,68.0,X-LC,5.35,14.0,0.25,1.94,20.84,X40N,ATH,FMCG
84,WIPRO,-0.59,-16.53,106.37,72.27,150456.0,-28002.0,141446.0,420.00,-24.55,55.0,M-LC,17.76,98.0,-0.19,1.04,8.52,XR,NTT,IT
43,INFY,-0.20,-9.00,47.53,34.24,135326.0,-28171.0,284717.0,1972.00,-28.52,56.0,X-LC,14.53,3.0,-0.21,2.09,9.49,X40,NTT,IT
33,HCLTECH,0.44,-6.03,31.78,23.83,72247.0,-14588.0,227336.0,1908.19,-1.16,60.0,X-LC,10.57,8.0,-0.20,1.67,10.38,X40,ATH,IT
8,AWL,0.59,-37.98,169.28,67.02,374100.0,-135314.0,220995.0,485.00,-66.62,46.0,X-SC,25.67,81.0,-0.36,1.62,4.53,XY24,NTT,FMCG

In [12]:
# top 5 to exit based on CumlRnk
df_tmp = df_portfolio_features[~df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])]
df_tmp = df_tmp[(df_tmp['Current P/L%'] > -1) & (df_tmp['Current P/L%'] < 1)].sort_values(by = 'CumlRnk', ascending=False)
df_tmp[cols].head()

Empty DataFrame
Columns: [Symbol, Today P/L%, Current P/L%, FTT%, OTT%, FTT Amt, Current P/L, Current, FTT, Dev%_PE, RSI_14, Conviction, Spread%, CumlRnk, RRR Ind, CurrAlloc%, Gained%, Criteria, Strategy, Category]
Index: []

In [13]:
# OX40N stocks to exit
df_tmp = df_portfolio_features[(df_portfolio_features['Symbol'].isin(list_ox40n))].sort_values(by = 'Current P/L%', ascending=False)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
26,FINCABLES,4.38,7.15,94.04,107.91,148773.0,10558.0,158202.0,1641.55,-3.60,52.0,M-SC,3.12,220.0,0.07,1.16,19.02,OX40N,ATH,CABLES
66,SIS,1.49,-32.82,80.51,21.26,60051.0,-36444.0,74588.0,528.00,1748.19,52.0,H-SC,14.75,168.0,-0.61,0.55,10.90,OX40N,NTT,MISC
18,CERA,5.79,-33.48,86.24,23.89,100911.0,-58891.0,117012.0,9475.00,-35.80,62.0,H-SC,18.53,153.0,-0.58,0.86,12.45,OX40N,NTT,CERAMICS
72,TATAELXSI,1.60,-36.19,106.91,32.03,89935.0,-47713.0,84122.0,9161.00,-20.19,53.0,H-SC,21.34,158.0,-0.53,0.62,11.34,OX40N,NTT,IT
77,TTKPRESTIG,3.08,-36.94,58.73,0.09,37322.0,-37229.0,63548.0,770.00,47.49,50.0,M-SC,22.11,250.0,-1.00,0.47,13.16,OX40N,NTT,DURABLES

In [14]:
# top 5 to book for rotation
df_tmp = df_portfolio_features[(df_portfolio_features['Current P/L%'] > 20) ].sort_values(by = 'CumlRnk', ascending=False)
df_tmp[cols].head()

Empty DataFrame
Columns: [Symbol, Today P/L%, Current P/L%, FTT%, OTT%, FTT Amt, Current P/L, Current, FTT, Dev%_PE, RSI_14, Conviction, Spread%, CumlRnk, RRR Ind, CurrAlloc%, Gained%, Criteria, Strategy, Category]
Index: []

In [15]:
# top 5 to monitor for exit
df_tmp = df_portfolio_features[~df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])]
df_tmp = df_tmp[(df_tmp['Current P/L%'] > 0) ].sort_values(by = 'Dev%_PE', ascending=False)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
26,FINCABLES,4.38,7.15,94.04,107.91,148773.0,10558.0,158202.0,1641.55,-3.60,52.0,M-SC,3.12,220.0,0.07,1.16,19.02,OX40N,ATH,CABLES
1,ABB,3.83,19.42,21.89,45.57,68391.0,50813.0,312432.0,7934.00,-23.25,63.0,H-MC,14.29,125.0,0.74,2.29,38.74,AR,NTT,ELECTRICAL

In [16]:
# top 5 to book for rotation from weak conviction
df_tmp = df_portfolio_features[~df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])]
df_tmp = df_tmp[~df_tmp['Criteria'].isin(['XY25','XY24','X40', 'X40N'])].sort_values(by = 'RRR Ind', ascending=False)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
1,ABB,3.83,19.42,21.89,45.57,68391.0,50813.0,312432.0,7934.00,-23.25,63.0,H-MC,14.29,125.0,0.74,2.29,38.74,AR,NTT,ELECTRICAL
26,FINCABLES,4.38,7.15,94.04,107.91,148773.0,10558.0,158202.0,1641.55,-3.60,52.0,M-SC,3.12,220.0,0.07,1.16,19.02,OX40N,ATH,CABLES
40,INDIAMART,2.27,-9.75,129.06,106.72,143658.0,-12025.0,111311.0,4810.62,-59.38,53.0,H-SC,12.83,140.0,-0.08,0.82,7.98,AR,ATH,MISC
85,ZYDUSLIFE,1.48,-6.52,45.09,35.63,88334.0,-13669.0,195905.0,1286.17,-18.47,49.0,H-MC,5.96,120.0,-0.15,1.44,9.06,AR,ATH,PHARMA
50,MASFIN,5.08,-3.70,26.24,21.57,24757.0,-3630.0,94350.0,397.04,-16.89,56.0,H-SC,4.82,167.0,-0.15,0.69,24.14,XR,ATH,FINANCE

In [17]:
# top 5 to accumulate based on lowest RSI_14
df_tmp = df_portfolio_features[df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])].sort_values(by = 'RSI_14', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
21,DABUR,2.74,-16.79,72.70,43.70,150064.0,-41652.0,206416.0,735.00,-24.46,38.0,X-MC,12.93,70.0,-0.28,1.52,3.69,XY24,BTT,FMCG
53,PGHH,0.81,-26.66,80.00,32.01,125274.0,-56928.0,156592.0,17616.87,-50.35,39.0,X-MC,20.24,57.0,-0.45,1.15,7.10,X40,ATH,FMCG
38,ICICIPRULI,4.46,-10.69,46.38,30.73,81602.0,-21063.0,175942.0,790.00,-34.67,40.0,X-MC,10.82,78.0,-0.26,1.29,7.21,X40,ATH,INSURANCE
82,VOLTAS,4.36,-0.38,45.75,45.20,87387.0,-732.0,191010.0,1856.00,14.09,41.0,X-MC,4.99,79.0,-0.01,1.40,6.39,XY25,NTT,AC
20,COLPAL,2.21,-28.19,97.05,41.51,183551.0,-74235.0,189130.0,3726.84,-13.02,42.0,X-MC,12.19,62.0,-0.40,1.39,5.74,XY25,ATH,FMCG

In [18]:
# top 5 to accumulate based on Spread and CumlRnk
df_tmp = df_portfolio_features[df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])]
df_tmp = df_tmp[(df_tmp['CumlRnk'] < 100)].sort_values(by = 'Spread%', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
65,SIEMENS,3.25,-14.68,47.11,25.51,74799.0,-27320.0,158775.0,4671.50,33.36,53.0,H-LC,0.99,51.0,-0.37,1.17,16.92,AR,ATH,ELECTRICAL
59,RELIANCE,3.04,-13.71,45.21,25.30,78401.0,-27548.0,173415.0,1952.00,-15.80,43.0,X-LC,4.45,21.0,-0.35,1.27,14.17,XY25,BTT,REFINERIES
78,UNITDSPR,2.10,-7.14,30.05,20.77,65336.0,-16719.0,217425.0,1644.00,-17.57,44.0,X-MC,4.53,64.0,-0.26,1.60,3.72,X40N,NTT,BREWERIES
82,VOLTAS,4.36,-0.38,45.75,45.20,87387.0,-732.0,191010.0,1856.00,14.09,41.0,X-MC,4.99,79.0,-0.01,1.40,6.39,XY25,NTT,AC
24,DMART,-1.34,5.92,22.36,29.60,59112.0,14766.0,264366.0,5391.45,-10.68,68.0,X-LC,5.35,14.0,0.25,1.94,20.84,X40N,ATH,FMCG

In [19]:
# top 5 to accumulate based on lowest Gained%
df_tmp = df_portfolio_features[df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])].sort_values(by = 'Gained%', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
2,ABBOTINDIA,0.95,-13.08,35.84,18.07,55717.0,-23395.0,155460.0,35195.00,-26.09,44.0,X-MC,11.08,58.0,-0.42,1.14,1.67,X40,ATH,PHARMA
21,DABUR,2.74,-16.79,72.70,43.70,150064.0,-41652.0,206416.0,735.00,-24.46,38.0,X-MC,12.93,70.0,-0.28,1.52,3.69,XY24,BTT,FMCG
78,UNITDSPR,2.10,-7.14,30.05,20.77,65336.0,-16719.0,217425.0,1644.00,-17.57,44.0,X-MC,4.53,64.0,-0.26,1.60,3.72,X40N,NTT,BREWERIES
8,AWL,0.59,-37.98,169.28,67.02,374100.0,-135314.0,220995.0,485.00,-66.62,46.0,X-SC,25.67,81.0,-0.36,1.62,4.53,XY24,NTT,FMCG
37,ICICIGI,2.70,-6.07,27.05,19.34,50843.0,-12150.0,187959.0,2252.93,-21.06,46.0,X-MC,6.86,66.0,-0.24,1.38,4.98,X40,ATH,INSURANCE

In [20]:
# top 5 to accumulate based on lowest CurrAlloc%
df_tmp = df_portfolio_features[df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])].sort_values(by = 'CurrAlloc%', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
58,RELAXO,3.54,-63.81,320.89,52.31,168560.0,-92631.0,52529.0,1176.00,-61.48,45.0,X-SC,32.70,92.0,-0.55,0.39,17.45,X40N,NTT,FOOTWEAR
12,BATAINDIA,4.71,-54.78,199.00,35.20,115784.0,-70487.0,58183.0,2096.00,-23.75,50.0,X-SC,34.37,91.0,-0.61,0.43,15.39,X40,NTT,FOOTWEAR
54,QUESS,3.73,-22.41,124.14,73.90,102857.0,-23937.0,82856.0,424.00,-58.13,55.0,X-SC,22.41,80.0,-0.23,0.61,11.46,XY24,NTT,MISC
36,HONAUT,2.48,-27.69,109.24,51.31,152335.0,-53388.0,139450.0,58357.33,-39.89,43.0,X-SC,18.66,90.0,-0.35,1.02,5.94,X40N,ATH,ELECTRICAL
2,ABBOTINDIA,0.95,-13.08,35.84,18.07,55717.0,-23395.0,155460.0,35195.00,-26.09,44.0,X-MC,11.08,58.0,-0.42,1.14,1.67,X40,ATH,PHARMA

In [21]:
# top 5 to accumulate based on CumlRnk
df_tmp = df_portfolio_features.sort_values(by = 'CumlRnk', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
45,ITC,1.81,-19.97,48.76,19.06,132749.0,-67916.0,272250.0,452.00,-55.92,51.0,X-LC,19.76,1.0,-0.51,2.00,5.61,X40,NTT,FMCG
73,TCS,0.98,-24.71,68.11,26.57,237567.0,-114474.0,348799.0,4311.58,-36.41,56.0,X-LC,18.47,2.0,-0.48,2.56,8.86,X40,ATH,IT
43,INFY,-0.20,-9.00,47.53,34.24,135326.0,-28171.0,284717.0,1972.00,-28.52,56.0,X-LC,14.53,3.0,-0.21,2.09,9.49,X40,NTT,IT
75,TMPV,8.08,-24.05,79.83,36.58,215745.0,-85585.0,270256.0,600.00,-84.72,54.0,X-LC,12.43,4.0,-0.40,1.98,12.64,XY24,NTT,AUTO
33,HCLTECH,0.44,-6.03,31.78,23.83,72247.0,-14588.0,227336.0,1908.19,-1.16,60.0,X-LC,10.57,8.0,-0.20,1.67,10.38,X40,ATH,IT

In [22]:
# top 5 for average up
df_tmp = df_portfolio_features[(df_portfolio_features['Dev%_200'] > 5)].sort_values(by = 'CurrAlloc%', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
67,SONACOMS,3.76,-7.53,50.42,39.09,47162.0,-7621.0,93538.0,804.02,-26.68,60.0,M-MC,7.69,193.0,-0.16,0.69,32.32,AR,ATH,AUTO
24,DMART,-1.34,5.92,22.36,29.60,59112.0,14766.0,264366.0,5391.45,-10.68,68.0,X-LC,5.35,14.0,0.25,1.94,20.84,X40N,ATH,FMCG
1,ABB,3.83,19.42,21.89,45.57,68391.0,50813.0,312432.0,7934.00,-23.25,63.0,H-MC,14.29,125.0,0.74,2.29,38.74,AR,NTT,ELECTRICAL

In [23]:
# top 5 RSP
df_tmp = df_portfolio_features.sort_values(by = 'RSP', ascending=False)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
80,VALIANTORG,1.51,-44.82,215.60,74.15,194644.0,-73325.0,90280.0,838.00,-262.20,61.0,H-SC,25.02,145.0,-0.38,0.66,34.35,XR,NTT,CHEMICALS
5,ANGELONE,5.22,6.13,17.01,24.18,55059.0,18688.0,323688.0,303.00,-84.36,64.0,X-SC,7.79,97.0,0.34,2.38,23.83,X40N,NTT,FINANCE
52,PAGEIND,1.30,-7.42,44.86,34.11,111461.0,-19914.0,248465.0,51418.64,-33.55,69.0,X-MC,18.57,55.0,-0.18,1.82,17.53,X40,ATH,APPARELS
30,HAPPSTMNDS,1.38,-52.19,286.61,84.85,175635.0,-66885.0,61280.0,1480.71,-43.09,49.0,H-SC,23.19,152.0,-0.38,0.45,13.48,AR,ATH,IT
18,CERA,5.79,-33.48,86.24,23.89,100911.0,-58891.0,117012.0,9475.00,-35.80,62.0,H-SC,18.53,153.0,-0.58,0.86,12.45,OX40N,NTT,CERAMICS

In [24]:
# Top N allocation
df_tmp = df_portfolio_features.sort_values(by = 'CurrAlloc%', ascending=False)
top_n_values = [10, 25, 50]

sum_df = pd.DataFrame({
    'Top_N': top_n_values,
    'Sum_Alloc%': [df_tmp['CurrAlloc%'].head(n).sum() for n in top_n_values]
})

sum_df

   Top_N  Sum_Alloc%
0     10       21.02
1     25       46.01
2     50       77.77

In [25]:
# market-cap-wise allocation
df_tmp = df_portfolio_features[cols]
df_tmp.groupby(df_tmp['Conviction'].str[-2:])['CurrAlloc%'].sum().sort_values(ascending=False)

Conviction
SC    45.03
MC    29.36
LC    25.65
Name: CurrAlloc%, dtype: float64

In [26]:
# criteria-wise allocation
df_portfolio_features.groupby('Criteria')['CurrAlloc%'].sum().sort_values(ascending=False)

Criteria
XY24     27.31
X40      25.16
X40N     15.38
AR        9.15
XR        8.45
XY25      7.03
OX40N     6.76
SR        0.80
Name: CurrAlloc%, dtype: float64

In [27]:
# conviction-wise allocation
df_portfolio_features.groupby('Conviction')['CurrAlloc%'].sum().sort_values(ascending=False)

Conviction
X-LC    23.44
H-SC    22.08
X-MC    21.93
X-SC    12.28
M-SC    10.11
H-MC     5.01
M-MC     2.07
H-LC     1.17
M-LC     1.04
L-SC     0.56
L-MC     0.35
Name: CurrAlloc%, dtype: float64

In [28]:
# sector-wise stats
df_tmp = df_portfolio_features.groupby('Category')[['CurrAlloc%', 'Current', 'Current P/L', 'FTT Amt']].sum().sort_values(by=['Current', 'Current P/L'], ascending=False)
df_tmp['Current P/L%'] = round(df_tmp['Current P/L'] * 100 / df_tmp['Current'], 2)
df_tmp['FTT%'] = round(df_tmp['FTT Amt'] * 100 / df_tmp['Current'], 2)
cols = ['CurrAlloc%', 'Current P/L%', 'FTT%']
df_tmp[cols].sort_values(by=['CurrAlloc%'], ascending=False)

               CurrAlloc%  Current P/L%    FTT%
Category
FMCG                14.87        -23.37   67.14
FINANCE             13.39        -17.91   65.97
IT                  12.00        -37.97  108.18
MISC                 7.14        -37.86   97.75
ELECTRICAL           6.42        -10.78   53.19
PAINTS               5.21        -39.06   63.21
BANKS                4.63        -22.11   84.10
INSURANCE            4.55         -9.47   46.92
PHARMA               3.97         -8.60   42.78
AUTO                 3.76        -27.79   78.49
HEALTHCARE           1.95        -34.91   70.12
AC                   1.92        -21.73   54.73
TRAVEL               1.84        -78.48  167.84
FOOTWEAR             1.84        -76.89  147.81
APPARELS             1.82         -8.01   44.86
DURABLES             1.76        -61.96  101.36
BREWERIES            1.60         -7.69   30.05
REALTY               1.39        -16.95   36.17
CERAMICS             1.37        -64.38  114.32
REFINERIES           1.27        -15.89   45.21
CEMENT               1.25        -57.43  175.21
ENGINEERING          1.20        -48.28  116.10
CABLES               1.16          6.67   94.04
CHEMICALS            1.10        -76.84  221.11
JEWELLERY            1.05       -123.66  201.37
ENTERTAINMENT        0.77        -83.43  192.82
TEXTILES             0.45        -48.98   91.46
HOTELS               0.36       -131.47  213.11

In [29]:
# money to be made criteria-wise
df_portfolio_features.groupby('Criteria')['FTT Amt'].agg(['sum', 'count']).sort_values(by='sum', ascending=False)

                sum  count
Criteria
XY24      3879997.0     21
X40       1747965.0     16
XR        1338825.0     12
AR        1326371.0     10
X40N      1205206.0     10
OX40N      871898.0     10
XY25       483018.0      5
SR         311147.0      2

In [30]:
# money to be made conviction-wise
df_portfolio_features.groupby('Conviction')['FTT Amt'].agg(['sum', 'count']).sort_values(by='sum', ascending=False)

                  sum  count
Conviction
H-SC        3787039.0     24
X-MC        1746955.0     15
X-LC        1582402.0     13
M-SC        1540798.0     14
X-SC        1510787.0     10
H-MC         395985.0      3
L-SC         215154.0      2
M-LC         150456.0      1
M-MC         105083.0      2
H-LC          74799.0      1
L-MC          54969.0      1

In [31]:
# money to be made criteria and conviction-wise
df_portfolio_features.groupby(['Conviction', 'Criteria'])['FTT Amt'].agg(['sum', 'count']).sort_values(by='sum', ascending=False)

                           sum  count
Conviction Criteria
H-SC       XY24      1292150.0      6
           AR         970007.0      5
M-SC       XY24       886711.0      6
X-LC       X40        851915.0      7
H-SC       XR         840721.0      7
X-SC       XY24       840605.0      4
X-MC       X40        681940.0      7
           X40N       529533.0      4
X-SC       X40N       456072.0      4
M-SC       OX40N      388273.0      5
H-SC       OX40N      373014.0      4
X-LC       XY24       356727.0      2
H-SC       SR         311147.0      2
X-MC       XY25       270938.0      2
           XY24       264544.0      2
H-MC       XY24       239260.0      1
X-LC       X40N       219601.0      2
X-SC       X40        214110.0      2
M-SC       XR         188136.0      2
H-MC       AR         156725.0      2
X-LC       XY25       154159.0      2
M-LC       XR         150456.0      1
L-SC       OX40N      110611.0      1
           XR         104543.0      1
M-SC       AR          77678.0      1
H-LC       AR          74799.0      1
M-MC       XY25        57921.0      1
L-MC       XR          54969.0      1
M-MC       AR          47162.0      1

In [32]:
# notebook execution time

end_time = time.time()
execution_time = round(end_time - start_time, 0)
print(f"Notebook execution time: {execution_time} seconds")

Notebook execution time: 34.0 seconds