<a href="https://colab.research.google.com/github/ankit-rathi/Quantvesting_v2/blob/main/myStocks_Portfolio_Analysis.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
'''
!pip install pandas==2.2.2 -qq
!pip install pyxirr -qq
!pip install ta -qq
!pip install yfinance==0.2.59 -qq
'''

'\n!pip install pandas==2.2.2 -qq\n!pip install pyxirr -qq\n!pip install ta -qq\n!pip install yfinance==0.2.59 -qq\n'

In [2]:
# import libraries

import numpy as np
import pandas as pd
import datetime
import warnings
warnings.filterwarnings('ignore')
import yfinance as yfin
import ta
import matplotlib.pyplot as plt
import requests

In [3]:
# notebook start time
import time
import datetime
import pytz

start_time = time.time()

# function to print date timestamp
def print_date_time():
  tz_NY = pytz.timezone('Asia/Kolkata')
  datetime_NY = datetime.datetime.now(tz_NY)
  print("Run date time (IST):", datetime_NY.strftime("%Y-%m-%d %H:%M:%S"))

In [4]:
# function to get booked and reserved amount
def get_amt():
  # fetch the JSON data from the URL
  url = "https://raw.githubusercontent.com/ankit-rathi/Tradevesting_v1/main/data/myPortfolioAmts.json"
  response = requests.get(url)
  pf_amts = response.json()  # parse the JSON data

  # extract values from the JSON
  py_booked_amt_dm = pf_amts["py_booked_amt_dm"]
  py_booked_amt_sv = pf_amts["py_booked_amt_sv"]
  cy_booked_amt_dm = pf_amts["cy_booked_amt_dm"]
  cy_booked_amt_sv = pf_amts["cy_booked_amt_sv"]
  reserve_amt_dm = pf_amts["reserve_amt_dm"]
  reserve_amt_sv = pf_amts["reserve_amt_sv"]

  # perform calculations
  py_booked_amt = py_booked_amt_dm + py_booked_amt_sv
  cy_booked_amt = cy_booked_amt_dm + cy_booked_amt_sv
  reserve_amt = reserve_amt_dm + reserve_amt_sv
  total_booked_amt = py_booked_amt + cy_booked_amt

  return total_booked_amt, reserve_amt, cy_booked_amt, py_booked_amt

gen_output = 0

In [5]:
# function to format the amount
def format_amt(number):
    abs_number = abs(number)

    if abs_number >= 1_00_00_000:  # Crores
        formatted_amt = f"{number / 1_00_00_000:.2f} C"
    elif abs_number >= 1_00_000:  # Lakhs
        formatted_amt = f"{number / 1_00_000:.2f} L"
    elif abs_number >= 1_000:  # Thousands
        formatted_amt = f"{number / 1_000:.2f} K"
    else:
        formatted_amt = f"{number:.2f}"

    return formatted_amt

# function to set start and end date
def get_start_end_date():
  start_date = (datetime.date.today() + datetime.timedelta(days=-365)).strftime('%Y-%m-%d')
  end_date = (datetime.date.today() + datetime.timedelta(days=1)).strftime('%Y-%m-%d')
  return start_date, end_date

# function to fetch my portfolio csv
def get_mypfs_df():
  mypfs_df = pd.read_csv('https://raw.githubusercontent.com/ankit-rathi/Tradevesting_v1/main/data/myPortfolioStocks.csv')
  return mypfs_df

# function to fetch my prospects csv
def get_mypps_df():
  mypps_df = pd.read_csv('https://raw.githubusercontent.com/ankit-rathi/Tradevesting_v1/main/data/myProspectsScrips.csv')
  return mypps_df

# function to fetch screener data
def get_myscreen_df():
  myscreen_df = pd.read_csv('https://raw.githubusercontent.com/ankit-rathi/Tradevesting_v1/main/data/myScreenerDB.csv')
  return myscreen_df

# function to fetch momentum data
def get_myinvmt_df():
  myinvmt_df = pd.read_csv('https://raw.githubusercontent.com/ankit-rathi/Tradevesting_v1/main/data/myInvestments.csv')
  return myinvmt_df

# function to get the stock ids
def get_stock_ids(df_pf):
  stock_n100 = df_pf['Symbol'].unique()

  exclude = ['CADILAHC','MMTC', 'MASFIN']

  stock_ids = df_pf[~df_pf['Symbol'].isin(exclude) ]['Symbol'].unique()

  #mypf = mypf[mypf.Forecast.notnull()]
  #stock_ids = mypf['Symbol'].unique()

  #stock_ids.sort()
  return stock_ids

# get features from screener data
def get_screener_features():
  myscreen_df = get_myscreen_df()
  cols = ['Symbol', 'EPS', 'MedPE', 'ROCE%', 'ROE%', 'CapType']
  return myscreen_df[cols]

# get relative strength
def get_relative_strength(stock_list):

    # Dictionary to store stock tickers and their corresponding percentage price change
    stock_changes = {}

    # Loop through each stock and fetch its price data
    for stock in stock_list:
        try:
            # Download the stock data for the given date range
            stock_data = yfin.Ticker(stock + '.NS').history(period='1mo', interval='1d')[map(str.title, ['open', 'close', 'low', 'high', 'volume'])]

            # Calculate the percentage change for the stock
            if len(stock_data) > 0:
                start_price = stock_data['Close'].iloc[0]
                end_price = stock_data['Close'].iloc[-1]
                percent_change = round(((end_price - start_price) / start_price) * 100, 2)
                stock_changes[stock] = percent_change
            else:
                stock_changes[stock] = np.nan  # If no data is available, set to NaN

        except Exception as e:
            print(f"Error fetching data for {stock}: {e}")
            stock_changes[stock] = np.nan

    # Create a DataFrame with stock tickers and their percentage changes
    df = pd.DataFrame(list(stock_changes.items()), columns=['Symbol', 'Percent_Change'])

    # Drop any stocks with missing data (NaN values)
    df = df.dropna()

    # Calculate the percentile rank based on percentage change
    df['RSP'] = round(df['Percent_Change'].rank(pct=True) * 100, 2)
    cols = ['Symbol', 'RSP']
    df = df[cols]
    # Sort by percentile rank (optional)
    df = df.sort_values(by='RSP', ascending=False).reset_index(drop=True)

    return df

In [6]:
# function to get stock technicals
def stock_prec_dev(stock_symbol):
    #stock_symbol = 'ULTRACEMCO.NS'
    short_window = 20
    mid_window = 50
    long_window = 200
    moving_avg = 'SMA'

    start = datetime.datetime(*map(int, start_date.split('-')))
    end = datetime.datetime(*map(int, end_date.split('-')))

    stock_df = yfin.Ticker(stock_symbol + '.NS').history(period='max', interval='1d')[map(str.title, ['open', 'close', 'low', 'high', 'volume'])]

    stock_df['Max'] = round(max(stock_df['Close']),2)
    stock_df = stock_df[(stock_df.index <= end_date) & (stock_df.index >= start_date)]
    stock_df['200_SMA'] = round(stock_df['Close'].rolling(window = 200, min_periods = 1).mean(),0)
    stock_df['Dev%_200'] = round((stock_df['Close'] - stock_df['200_SMA'])*100/stock_df['200_SMA'],2)
    stock_df.dropna(axis = 0, inplace = True) # remove any null rows

    stock_df['20_SMA'] = stock_df['Close'].rolling(window=20).mean()
    stock_df['50_SMA'] = stock_df['Close'].rolling(window=50).mean()
    stock_df['Symbol'] = stock_symbol

    stock_df['Close'] = round(stock_df['Close'],2)
    stock_df['Min'] = round(min(stock_df['Close']),2)
    stock_df['RSI_14'] = ta.momentum.RSIIndicator(close=stock_df['Close'], window=14).rsi()
    stock_df['RSI_14'] = round(stock_df['RSI_14'],0)
    stock_df['Prev_Close'] = stock_df['Close'].shift(1)
    stock_df.drop(['Open', 'Low', 'High', 'Volume'], axis=1, inplace=True)
    stock_df = stock_df.tail(1)

    max_SMA = max(stock_df['20_SMA'].item(), stock_df['50_SMA'].item(), stock_df['200_SMA'].item())
    min_SMA = min(stock_df['20_SMA'].item(), stock_df['50_SMA'].item(), stock_df['200_SMA'].item())
    ABS_Spread = max_SMA - min_SMA
    stock_df['Spread%'] = round((ABS_Spread / stock_df['200_SMA'].item()) * 100,2)

    return stock_df

# function to compute stock attributes
def get_common_features(stock_ids, df_mypf):

  df_prec_dev = pd.DataFrame()
  df_tmp = get_screener_features()
  df_rs = get_relative_strength(stock_ids)

  for stock_id in stock_ids:
      tmp = stock_prec_dev(stock_id)
      tmp = tmp.reset_index()
      df_prec_dev = pd.concat([df_prec_dev, tmp], ignore_index = True)
  df_prec_dev = pd.merge(df_prec_dev, df_mypf, on= 'Symbol')
  df_prec_dev = pd.merge(df_prec_dev, df_tmp, on= 'Symbol', how='left')
  df_prec_dev = pd.merge(df_prec_dev, df_rs, on= 'Symbol', how='left')
  #print(df_prec_dev.columns)
  df_prec_dev['Curr_PE'] = round(df_prec_dev['Close']/df_prec_dev['EPS'],1)
  df_prec_dev['Dev%_PE'] = round((df_prec_dev['Curr_PE'] - df_prec_dev['MedPE'])*100/df_prec_dev['MedPE'],2)
  df_prec_dev['Conviction'] = df_prec_dev['Conviction'] + '-' + df_prec_dev['CapType']
  return df_prec_dev

# function to arrange stock features
def arrange_features(df_stocks, common_cols, diff_cols):
  df_stocks_common = df_stocks[common_cols].drop_duplicates()
  df_stocks_diff = df_stocks[diff_cols]
  df_stocks_diff['Investment'] = df_stocks_diff['AvgCost'] * df_stocks_diff['Shares']
  df_stocks_diff = df_stocks_diff.groupby(['Symbol'])[['Shares', 'Investment']].aggregate(['sum']).reset_index()
  df_stocks_diff.columns = ['Symbol', 'Shares', 'Investment']
  df_stocks_diff['AvgCost'] = round(df_stocks_diff['Investment']/df_stocks_diff['Shares'],2)
  df_stocks = pd.merge(df_stocks_diff, df_stocks_common, on='Symbol')
  return df_stocks

# plot fact distribution across dimension
def plot_pie_chart(df, dimension, fact):
  # grouping the data by category and calculating the sum of fact for each type
  grouped_data = df.groupby(dimension)[fact].sum()

  # sorting the grouped data in descending order
  grouped_data = grouped_data.sort_values(ascending=False)

  # creating a pie chart
  grouped_data.plot.pie(autopct='%1.1f%%', startangle=90, figsize=(6, 6))

  # adding a title and displaying the plot
  plt.title(f'{dimension} {fact} Distribution')
  plt.ylabel('')  # To hide the y-label
  plt.show()

In [7]:
# function to get portfolio features

def get_portfolio_features(df_common_features):

  print_date_time()
  print('-------------------')

  #df_common_features["Target"] = df_common_features["Target"].fillna(df_common_features["Max"])
  df_common_features['NTT'] = np.where(df_common_features['Strategy']== 'NTT', df_common_features["Target"], df_common_features['Max'])
  df_common_features['LTT'] = np.where(df_common_features['Strategy']== 'BTT', df_common_features["Target"], df_common_features['Max'])
  df_common_features['BOL'] = df_common_features['Min']

  tmp_df = df_common_features[df_common_features['Symbol'].isin(mypf_df[mypf_df['InPortfolio'] != 'NA'].Symbol.values)]
  print('qualified stocks: '+str(len(tmp_df['Symbol'].unique())))
  tmp_df1 = tmp_df[tmp_df['LatestQtr'] == 1]
  print('with latest results: '+str(len(tmp_df1['Symbol'].unique())))
  tmp_df1 = tmp_df1[tmp_df1['StarStock'] == 1]
  print('still star stocks: '+str(len(tmp_df1['Symbol'].unique())))
  tmp_df['Investment'] = tmp_df['AvgCost'] * tmp_df['Shares']
  tmp_df['Current'] = round(tmp_df['Close'] * tmp_df['Shares'],0)
  tmp_df['Previous'] = tmp_df['Prev_Close'] * tmp_df['Shares']
  tmp_df['EstimatedST'] = tmp_df['NTT'] * tmp_df['Shares']
  tmp_df['EstimatedLT'] = tmp_df['LTT'] * tmp_df['Shares']
  tmp_df['Current P/L'] = round((tmp_df['Current'] - tmp_df['Investment']),0)
  tmp_df['Today P/L%'] = round((tmp_df['Current'] - tmp_df['Previous'])*100/tmp_df['Previous'],2)
  tmp_df['Current P/L%'] = round((tmp_df['Current'] - tmp_df['Investment'])*100/tmp_df['Investment'],2)
  tmp_df['EstimatedST P/L%'] = round((tmp_df['EstimatedST'] - tmp_df['Investment'])*100/tmp_df['Investment'],2)
  tmp_df['EstimatedLT P/L%'] = round((tmp_df['EstimatedLT'] - tmp_df['Investment'])*100/tmp_df['Investment'],2)
  tmp_df['NTT%'] = round((tmp_df['NTT'] - tmp_df['Close'])*100/tmp_df['Close'],2)
  tmp_df['LTT%'] = round((tmp_df['LTT'] - tmp_df['Close'])*100/tmp_df['Close'],2)
  tmp_df['Gained%'] = round((tmp_df['Close'] - tmp_df['BOL'])*100/tmp_df['BOL'],2)
  investment = round(sum(tmp_df['AvgCost']*tmp_df['Shares']),0)
  current = round(sum(tmp_df['Close']*tmp_df['Shares']),0)
  tmp_df['InitAlloc%'] = round(tmp_df['Investment']*100/investment,2)
  tmp_df['CurrAlloc%'] = round(tmp_df['Current']*100/current,2)
  tmp_df['FTT'] = tmp_df['LTT']
  tmp_df.loc[tmp_df['Strategy'] == 'NTT', 'FTT'] = tmp_df['NTT']
  tmp_df['FTT%'] = tmp_df['LTT%']
  tmp_df.loc[tmp_df['Strategy'] == 'NTT', 'FTT%'] = tmp_df['NTT%']
  tmp_df['FTT Amt'] = round(tmp_df['FTT%'] * tmp_df['Current']/100,0)
  tmp_df['OTT%'] = round((tmp_df['FTT'] - tmp_df['AvgCost'])*100/tmp_df['AvgCost'],2)
  tmp_df['RRR Ind'] = round(tmp_df['Current P/L']/tmp_df['FTT Amt'],2)
  tmp_df['Risk Ind'] = round(tmp_df['Current P/L%']*tmp_df['CurrAlloc%'],0)

  return tmp_df

# function to print portfolio features
def print_portfolio_stats(df_portfolio_features, myinvmt_df):
  from pyxirr import xirr

  total_booked_amt, reserve_amt, cy_booked_amt, py_booked_amt = get_amt()

  dates = myinvmt_df['Date'].values
  dates = np.append(dates, datetime.date.today().strftime('%d-%b-%y'))
  investment = myinvmt_df['Investment'].values
  dates= pd.to_datetime(dates)

  current = round(sum(df_portfolio_features['Close']*df_portfolio_features['Shares']),0) + reserve_amt
  investment_xirr = np.append(investment, current)
  cagr = round(xirr(pd.DataFrame({"dates": dates, "amounts": investment_xirr}))*100,2)

  investment = -sum(investment)
  invested = round(sum(df_portfolio_features['AvgCost']*df_portfolio_features['Shares']),0) + reserve_amt
  previous = round(sum(df_portfolio_features['Prev_Close']*df_portfolio_features['Shares']),0) + reserve_amt
  cy_invested = investment + py_booked_amt

  today_pnl_amount = current-previous
  today_pnl_percentage = round((current-previous)*100/previous,2)

  curr_pnl_amount = current-invested
  curr_pnl_percentage = round((curr_pnl_amount)*100/(cy_invested),2)

  cy_pnl_amount = cy_booked_amt + curr_pnl_amount
  cy_pnl_percentage = round((cy_pnl_amount)*100/cy_invested,2)

  overall_pnl_amount = total_booked_amt + curr_pnl_amount
  overall_pnl_percentage = round((overall_pnl_amount)*100/investment,2)

  estimate_st = round(sum(df_portfolio_features['FTT']*df_portfolio_features['Shares']),0)  + reserve_amt
  est_st_pnl_amount = estimate_st-current
  est_st_pnl_percentage = round((est_st_pnl_amount)*100/current,2)

  estimate_lt = round(sum(df_portfolio_features['LTT']*df_portfolio_features['Shares']),0)  + reserve_amt
  est_lt_pnl_amount = estimate_lt-current
  est_lt_pnl_percentage = round((est_lt_pnl_amount)*100/current,2)

  total_profit = round(sum(df_portfolio_features[df_portfolio_features['Current P/L%'] > 0]['Current']) - sum(df_portfolio_features[df_portfolio_features['Current P/L%'] > 0]['Investment']),0)
  total_loss = round(sum(df_portfolio_features[df_portfolio_features['Current P/L%'] < 0]['Current']) - sum(df_portfolio_features[df_portfolio_features['Current P/L%'] < 0]['Investment']),0)

  cy_booked_percentage = round((cy_booked_amt)*100/current,2)
  py_booked_percentage = round((py_booked_amt)*100/investment,2)
  total_booked_percentage = round((total_booked_amt)*100/investment,2)

  print('-------------------')
  print('Initial Investment: ', format_amt(investment))
  print('CY Investment: ', format_amt(cy_invested))
  print('Reserve: ', format_amt(reserve_amt))
  print('Current: ',  format_amt(current))
  print('-------------------')
  print('Today PnL: '+ '{} ({}%)'.format(format_amt(today_pnl_amount), today_pnl_percentage))
  print('Current PnL: '+ '{} ({}%)'.format(format_amt(curr_pnl_amount), curr_pnl_percentage))
  print('CY Booked + Current PnL: '+ '{} ({}%)'.format(format_amt(cy_pnl_amount), cy_pnl_percentage))
  print('-------------------')
  print('Total profit: ', format_amt(total_profit))
  print('Total loss: ', format_amt(total_loss))
  print('-------------------')
  print('Total Booked + Current PnL: '+ '{} ({}%)'.format(format_amt(overall_pnl_amount), overall_pnl_percentage))
  print('Total Booked PnL: '+ '{} ({}%)'.format(format_amt(total_booked_amt), total_booked_percentage))
  print('Curr Year Booked PnL: '+ '{} ({}%)'.format(format_amt(cy_booked_amt), cy_booked_percentage))
  print('Prev Year Booked PnL: '+ '{} ({}%)'.format(format_amt(py_booked_amt), py_booked_percentage))
  print('===================')
  print('Est FTT: ',  format_amt(estimate_st))
  print('Est FTT PnL: '+ '{} ({}%)'.format(format_amt(est_st_pnl_amount), est_st_pnl_percentage))

  print('===================')
  print('Deployed: ', format_amt(investment))

  print('Current: ', format_amt(current))

  print('CAGR/XIRR %: '+'{}%'.format(cagr))

In [8]:
# get start and end date
start_date, end_date = get_start_end_date()

# get portfolio and prospects data
mypfs_df = get_mypfs_df()
mypps_df = get_mypps_df()
myinvmt_df = get_myinvmt_df()

# merge above datasets
mypf_df = pd.merge(mypfs_df, mypps_df, on="Symbol")

# seggregate dm and sv portfolio
dm_pf = mypf_df[mypf_df['InPortfolio'] == 'DM']
sv_pf = mypf_df[mypf_df['InPortfolio'] == 'SV']

# build portfolio stock dataframe
dm_stocks = get_stock_ids(dm_pf)
sv_stocks = get_stock_ids(sv_pf)
df_stocks = pd.concat([dm_pf,sv_pf], ignore_index = True)

# arrange common and diff stock features
common_cols = ['Symbol', 'Target', 'Criteria', 'Strategy', 'CumlRnk', 'LatestQtr', 'StarStock', 'Conviction', 'Category', 'InFolio', 'XIRR', 'MBQ']
diff_cols = ['Symbol', 'AvgCost', 'Shares']
df_stocks = arrange_features(df_stocks, common_cols, diff_cols)

# get common features
stock_ids = df_stocks['Symbol'].values
df_common_features = get_common_features(stock_ids, df_stocks)

df_common_features.reset_index(drop=True, inplace=True)
df_common_features.drop(['Date'], axis=1, inplace=True)
# get and print portfolio features
df_portfolio_features = get_portfolio_features(df_common_features)

print_portfolio_stats(df_portfolio_features, myinvmt_df)

df = df_portfolio_features
#plot_pie_chart(df, 'CapType', 'Current')
list_ox40n = list(df[df['MBQ'].str.contains('OX40N', na=False)]['Symbol'].values)

Run date time (IST): 2026-03-24 12:15:20
-------------------
qualified stocks: 86
with latest results: 26
still star stocks: 16
-------------------
Initial Investment:  1.36 C
CY Investment:  1.62 C
Reserve:  1.61 K
Current:  1.28 C
-------------------
Today PnL: 1.31 L (1.03%)
Current PnL: -48.98 L (-30.14%)
CY Booked + Current PnL: -33.09 L (-20.36%)
-------------------
Total profit:  39.55 K
Total loss:  -49.37 L
-------------------
Total Booked + Current PnL: -6.11 L (-4.51%)
Total Booked PnL: 42.87 L (31.64%)
Curr Year Booked PnL: 15.89 L (12.4%)
Prev Year Booked PnL: 26.98 L (19.91%)
===================
Est FTT:  2.48 C
Est FTT PnL: 1.20 C (93.44%)
===================
Deployed:  1.36 C
Current:  1.28 C
CAGR/XIRR %: -2.73%

In [9]:
# top 5 near their targets
cols = ['Symbol', 'Today P/L%', 'Current P/L%', 'FTT%', 'OTT%', 'FTT Amt', 'Current P/L', 'Current', 'FTT', 'Dev%_PE', 'RSI_14','Conviction', 'Spread%',  'CumlRnk', 'RRR Ind', 'CurrAlloc%', 'Gained%', 'Criteria', 'Strategy', 'Category']
df_tmp = df_portfolio_features[~df_portfolio_features['Symbol'].isin(['ENRIN','BLUSPRING','DIGITIDE'])]
df_tmp = df_tmp.sort_values(by = 'FTT Amt', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
50,MASFIN,-0.51,-10.66,36.07,21.57,31576.0,-10440.0,87540.0,397.04,-22.76,38.0,H-SC,2.41,167.0,-0.33,0.68,19.40,XR,ATH,FINANCE
77,TTKPRESTIG,-4.00,-43.04,75.72,0.09,43466.0,-43373.0,57404.0,770.00,33.19,34.0,M-SC,19.19,250.0,-1.00,0.45,0.00,OX40N,NTT,DURABLES
2,ABBOTINDIA,2.71,-12.19,34.46,18.07,54119.0,-21805.0,157050.0,35195.00,-25.27,44.0,X-MC,10.69,58.0,-0.40,1.23,2.71,X40,ATH,PHARMA
67,SONACOMS,0.75,-15.47,64.56,39.09,55202.0,-15654.0,85505.0,804.02,-33.03,43.0,M-MC,7.40,193.0,-0.28,0.67,20.96,AR,ATH,AUTO
37,ICICIGI,0.52,-8.30,30.14,19.34,55306.0,-16612.0,183497.0,2252.93,-22.78,27.0,X-MC,3.73,66.0,-0.30,1.43,1.44,X40,ATH,INSURANCE

In [10]:
# top 5 today
df_tmp = df_portfolio_features.sort_values(by = 'Today P/L%', ascending=False)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
4,ALKYLAMINE,7.01,-43.51,242.79,93.63,138466.0,-43932.0,57031.0,4546.37,-39.55,43.0,H-SC,25.96,142.0,-0.32,0.45,7.01,SR,ATH,CHEMICALS
41,INDIGOPNTS,4.21,-47.22,89.50,0.02,82458.0,-82427.0,92132.0,1408.00,40.62,23.0,M-SC,24.37,222.0,-1.00,0.72,4.21,OX40N,NTT,PAINTS
78,UNITDSPR,3.68,-2.88,24.35,20.77,55372.0,-6743.0,227401.0,1644.00,-13.87,46.0,X-MC,1.64,64.0,-0.12,1.77,3.68,X40N,NTT,BREWERIES
47,JSWINFRA,3.56,-14.92,36.85,16.43,69526.0,-33100.0,188674.0,342.00,-27.05,45.0,X-MC,11.60,61.0,-0.48,1.47,3.56,X40N,NTT,REALTY
66,SIS,3.22,-37.47,93.94,21.26,65217.0,-41608.0,69424.0,528.00,1620.21,36.0,H-SC,14.34,168.0,-0.64,0.54,3.22,OX40N,NTT,MISC

In [11]:
# bottom 5 today
df_tmp = df_portfolio_features.sort_values(by = 'Today P/L%', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
80,VALIANTORG,-5.59,-52.62,267.58,74.15,207409.0,-86092.0,77513.0,838.0,-239.74,48.0,H-SC,28.37,145.0,-0.42,0.60,15.35,XR,NTT,CHEMICALS
25,EASEMYTRIP,-5.55,-64.29,308.04,45.70,194478.0,-113681.0,63134.0,26.4,-34.35,34.0,M-SC,8.79,204.0,-0.58,0.49,4.02,XY24,NTT,TRAVEL
55,RAJESHEXPO,-4.99,-83.61,510.49,0.07,114784.0,-114692.0,22485.0,518.0,724.49,14.0,L-SC,34.55,268.0,-1.00,0.18,0.00,OX40N,NTT,JEWELLERY
77,TTKPRESTIG,-4.00,-43.04,75.72,0.09,43466.0,-43373.0,57404.0,770.0,33.19,34.0,M-SC,19.19,250.0,-1.00,0.45,0.00,OX40N,NTT,DURABLES
69,SURYODAY,-3.28,-30.93,78.13,23.03,96635.0,-55386.0,123685.0,216.0,33.77,41.0,H-SC,6.49,166.0,-0.57,0.97,20.89,XR,NTT,BANKS

In [12]:
# top 5 to exit based on CumlRnk
df_tmp = df_portfolio_features[~df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])]
df_tmp = df_tmp[(df_tmp['Current P/L%'] > -1) & (df_tmp['Current P/L%'] < 1)].sort_values(by = 'CumlRnk', ascending=False)
df_tmp[cols].head()

Empty DataFrame
Columns: [Symbol, Today P/L%, Current P/L%, FTT%, OTT%, FTT Amt, Current P/L, Current, FTT, Dev%_PE, RSI_14, Conviction, Spread%, CumlRnk, RRR Ind, CurrAlloc%, Gained%, Criteria, Strategy, Category]
Index: []

In [13]:
# OX40N stocks to exit
df_tmp = df_portfolio_features[(df_portfolio_features['Symbol'].isin(list_ox40n))].sort_values(by = 'Current P/L%', ascending=False)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
26,FINCABLES,2.27,4.74,98.51,107.91,152336.0,6996.0,154640.0,1641.55,-5.63,46.0,M-SC,8.22,220.0,0.05,1.21,16.34,OX40N,ATH,CABLES
66,SIS,3.22,-37.47,93.94,21.26,65217.0,-41608.0,69424.0,528.00,1620.21,36.0,H-SC,14.34,168.0,-0.64,0.54,3.22,OX40N,NTT,MISC
18,CERA,1.36,-39.26,103.98,23.89,111087.0,-69068.0,106835.0,9475.00,-41.29,43.0,H-SC,19.01,153.0,-0.62,0.83,2.67,OX40N,NTT,CERAMICS
72,TATAELXSI,1.34,-39.67,118.85,32.03,94526.0,-52301.0,79534.0,9161.00,-24.56,38.0,H-SC,20.94,158.0,-0.55,0.62,3.63,OX40N,NTT,IT
77,TTKPRESTIG,-4.00,-43.04,75.72,0.09,43466.0,-43373.0,57404.0,770.00,33.19,34.0,M-SC,19.19,250.0,-1.00,0.45,0.00,OX40N,NTT,DURABLES

In [14]:
# top 5 to book for rotation
df_tmp = df_portfolio_features[(df_portfolio_features['Current P/L%'] > 20) ].sort_values(by = 'CumlRnk', ascending=False)
df_tmp[cols].head()

Empty DataFrame
Columns: [Symbol, Today P/L%, Current P/L%, FTT%, OTT%, FTT Amt, Current P/L, Current, FTT, Dev%_PE, RSI_14, Conviction, Spread%, CumlRnk, RRR Ind, CurrAlloc%, Gained%, Criteria, Strategy, Category]
Index: []

In [15]:
# top 5 to monitor for exit
df_tmp = df_portfolio_features[~df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])]
df_tmp = df_tmp[(df_tmp['Current P/L%'] > 0) ].sort_values(by = 'Dev%_PE', ascending=False)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
26,FINCABLES,2.27,4.74,98.51,107.91,152336.0,6996.0,154640.0,1641.55,-5.63,46.0,M-SC,8.22,220.0,0.05,1.21,16.34,OX40N,ATH,CABLES
1,ABB,1.44,12.44,29.46,45.57,86662.0,32549.0,294168.0,7934.00,-27.77,53.0,H-MC,13.26,125.0,0.38,2.30,30.63,AR,NTT,ELECTRICAL

In [16]:
# top 5 to book for rotation from weak conviction
df_tmp = df_portfolio_features[~df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])]
df_tmp = df_tmp[~df_tmp['Criteria'].isin(['XY25','XY24','X40', 'X40N'])].sort_values(by = 'RRR Ind', ascending=False)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
1,ABB,1.44,12.44,29.46,45.57,86662.0,32549.0,294168.0,7934.00,-27.77,53.0,H-MC,13.26,125.0,0.38,2.30,30.63,AR,NTT,ELECTRICAL
26,FINCABLES,2.27,4.74,98.51,107.91,152336.0,6996.0,154640.0,1641.55,-5.63,46.0,M-SC,8.22,220.0,0.05,1.21,16.34,OX40N,ATH,CABLES
40,INDIAMART,0.03,-15.30,144.06,106.72,150497.0,-18868.0,104468.0,4810.62,-61.72,31.0,H-SC,11.63,140.0,-0.13,0.82,4.50,AR,ATH,MISC
85,ZYDUSLIFE,1.85,-7.57,46.74,35.63,90538.0,-15868.0,193706.0,1286.17,-19.37,43.0,H-MC,5.43,120.0,-0.18,1.51,7.84,AR,ATH,PHARMA
84,WIPRO,1.27,-22.10,121.13,72.27,159893.0,-37447.0,132001.0,420.00,-29.71,33.0,M-LC,17.81,98.0,-0.23,1.03,1.27,XR,NTT,IT

In [17]:
# top 5 to accumulate based on lowest RSI_14
df_tmp = df_portfolio_features[df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])].sort_values(by = 'RSI_14', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
53,PGHH,0.47,-28.81,85.44,32.01,129869.0,-61520.0,152000.0,17616.87,-51.83,14.0,X-MC,15.84,57.0,-0.47,1.19,0.47,X40,ATH,FMCG
38,ICICIPRULI,-0.07,-12.15,48.80,30.73,84460.0,-23932.0,173073.0,790.00,-35.70,18.0,X-MC,4.46,78.0,-0.28,1.35,0.00,X40,ATH,INSURANCE
12,BATAINDIA,0.38,-59.48,233.68,35.20,121831.0,-76534.0,52136.0,2096.00,-31.70,19.0,X-SC,31.27,91.0,-0.63,0.41,0.38,X40,NTT,FOOTWEAR
58,RELAXO,1.43,-66.52,354.93,52.31,172489.0,-96562.0,48598.0,1176.00,-64.38,20.0,X-SC,26.57,92.0,-0.56,0.38,1.43,X40N,NTT,FOOTWEAR
21,DABUR,0.60,-17.91,75.06,43.70,152842.0,-44441.0,203627.0,735.00,-25.56,23.0,X-MC,6.40,70.0,-0.29,1.59,0.60,XY24,BTT,FMCG

In [18]:
# top 5 to accumulate based on Spread and CumlRnk
df_tmp = df_portfolio_features[df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])]
df_tmp = df_tmp[(df_tmp['CumlRnk'] < 100)].sort_values(by = 'Spread%', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
78,UNITDSPR,3.68,-2.88,24.35,20.77,55372.0,-6743.0,227401.0,1644.00,-13.87,46.0,X-MC,1.64,64.0,-0.12,1.77,3.68,X40N,NTT,BREWERIES
65,SIEMENS,1.03,-18.89,54.74,25.51,82630.0,-35145.0,150950.0,4671.50,26.69,41.0,H-LC,2.80,51.0,-0.43,1.18,11.16,AR,ATH,ELECTRICAL
59,RELIANCE,0.25,-9.41,38.31,25.30,69746.0,-18905.0,182058.0,1952.00,-11.57,51.0,X-LC,3.45,21.0,-0.27,1.42,21.55,XY25,BTT,REFINERIES
37,ICICIGI,0.52,-8.30,30.14,19.34,55306.0,-16612.0,183497.0,2252.93,-22.78,27.0,X-MC,3.73,66.0,-0.30,1.43,1.44,X40,ATH,INSURANCE
82,VOLTAS,2.08,-0.08,45.32,45.20,86824.0,-162.0,191580.0,1856.00,14.36,31.0,X-MC,3.90,79.0,-0.00,1.50,6.71,XY25,NTT,AC

In [19]:
# top 5 to accumulate based on lowest Gained%
df_tmp = df_portfolio_features[df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])].sort_values(by = 'Gained%', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
9,BAJAJHFL,-0.92,-30.51,133.32,62.13,252948.0,-83316.0,189730.0,181.50,-42.81,24.0,X-MC,20.47,60.0,-0.33,1.48,0.00,X40N,ATH,FINANCE
38,ICICIPRULI,-0.07,-12.15,48.80,30.73,84460.0,-23932.0,173073.0,790.00,-35.70,18.0,X-MC,4.46,78.0,-0.28,1.35,0.00,X40,ATH,INSURANCE
45,ITC,-3.17,-23.50,55.62,19.06,144747.0,-79923.0,260243.0,452.00,-57.95,29.0,X-LC,18.20,1.0,-0.55,2.03,0.00,X40,NTT,FMCG
3,ACC,0.04,-40.46,193.62,74.81,309087.0,-108492.0,159636.0,3906.00,-57.90,24.0,X-SC,17.78,85.0,-0.35,1.25,0.04,XY24,BTT,CEMENT
32,HAVELLS,0.07,-21.13,67.45,32.08,174492.0,-69292.0,258699.0,2062.85,-25.80,32.0,X-MC,8.61,63.0,-0.40,2.02,0.07,X40,ATH,ELECTRICAL

In [20]:
# top 5 to accumulate based on lowest CurrAlloc%
df_tmp = df_portfolio_features[df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])].sort_values(by = 'CurrAlloc%', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
58,RELAXO,1.43,-66.52,354.93,52.31,172489.0,-96562.0,48598.0,1176.00,-64.38,20.0,X-SC,26.57,92.0,-0.56,0.38,1.43,X40N,NTT,FOOTWEAR
12,BATAINDIA,0.38,-59.48,233.68,35.20,121831.0,-76534.0,52136.0,2096.00,-31.70,19.0,X-SC,31.27,91.0,-0.63,0.41,0.38,X40,NTT,FOOTWEAR
54,QUESS,2.40,-28.66,143.76,73.90,109525.0,-30607.0,76186.0,424.00,-61.43,36.0,X-SC,21.49,80.0,-0.28,0.59,2.40,XY24,NTT,MISC
36,HONAUT,1.23,-28.57,111.82,51.31,154032.0,-55088.0,137750.0,58357.33,-40.63,26.0,X-SC,15.85,90.0,-0.36,1.08,1.23,X40N,ATH,ELECTRICAL
51,MEDANTA,1.45,-15.85,51.06,27.12,75844.0,-27978.0,148539.0,1486.00,-18.52,28.0,X-SC,12.27,87.0,-0.37,1.16,1.45,XY24,NTT,HEALTHCARE

In [21]:
# top 5 to accumulate based on CumlRnk
df_tmp = df_portfolio_features.sort_values(by = 'CumlRnk', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
45,ITC,-3.17,-23.50,55.62,19.06,144747.0,-79923.0,260243.0,452.00,-57.95,29.0,X-LC,18.20,1.0,-0.55,2.03,0.00,X40,NTT,FMCG
73,TCS,1.72,-28.81,77.80,26.57,256574.0,-133487.0,329786.0,4311.59,-39.69,34.0,X-LC,17.33,2.0,-0.52,2.57,2.92,X40,ATH,IT
43,INFY,0.07,-14.44,56.91,34.24,152347.0,-45190.0,267698.0,1972.00,-32.51,37.0,X-LC,15.08,3.0,-0.30,2.09,2.95,X40,NTT,IT
75,TMPV,0.97,-29.84,94.68,36.58,236361.0,-106199.0,249642.0,600.00,-85.81,34.0,X-LC,6.74,4.0,-0.45,1.95,0.97,XY24,NTT,AUTO
33,HCLTECH,2.20,-9.89,37.43,23.83,81595.0,-23930.0,217994.0,1908.19,-5.29,48.0,X-LC,11.79,8.0,-0.29,1.70,5.85,X40,ATH,IT

In [22]:
# top 5 for average up
df_tmp = df_portfolio_features[(df_portfolio_features['Dev%_200'] > 5)].sort_values(by = 'CurrAlloc%', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
1,ABB,1.44,12.44,29.46,45.57,86662.0,32549.0,294168.0,7934.0,-27.77,53.0,H-MC,13.26,125.0,0.38,2.3,30.63,AR,NTT,ELECTRICAL

In [23]:
# top 5 RSP
df_tmp = df_portfolio_features.sort_values(by = 'RSP', ascending=False)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
30,HAPPSTMNDS,-0.33,-51.14,278.36,84.85,174298.0,-65549.0,62616.0,1480.71,-41.98,52.0,H-SC,26.57,152.0,-0.38,0.49,15.96,AR,ATH,IT
69,SURYODAY,-3.28,-30.93,78.13,23.03,96635.0,-55386.0,123685.0,216.00,33.77,41.0,H-SC,6.49,166.0,-0.57,0.97,20.89,XR,NTT,BANKS
33,HCLTECH,2.20,-9.89,37.43,23.83,81595.0,-23930.0,217994.0,1908.19,-5.29,48.0,X-LC,11.79,8.0,-0.29,1.70,5.85,X40,ATH,IT
26,FINCABLES,2.27,4.74,98.51,107.91,152336.0,6996.0,154640.0,1641.55,-5.63,46.0,M-SC,8.22,220.0,0.05,1.21,16.34,OX40N,ATH,CABLES
1,ABB,1.44,12.44,29.46,45.57,86662.0,32549.0,294168.0,7934.00,-27.77,53.0,H-MC,13.26,125.0,0.38,2.30,30.63,AR,NTT,ELECTRICAL

In [24]:
# Top N allocation
df_tmp = df_portfolio_features.sort_values(by = 'CurrAlloc%', ascending=False)
top_n_values = [10, 25, 50]

sum_df = pd.DataFrame({
    'Top_N': top_n_values,
    'Sum_Alloc%': [df_tmp['CurrAlloc%'].head(n).sum() for n in top_n_values]
})

sum_df

   Top_N  Sum_Alloc%
0     10       20.82
1     25       45.94
2     50       78.27

In [25]:
# market-cap-wise allocation
df_tmp = df_portfolio_features[cols]
df_tmp.groupby(df_tmp['Conviction'].str[-2:])['CurrAlloc%'].sum().sort_values(ascending=False)

Conviction
SC    44.13
MC    30.20
LC    25.71
Name: CurrAlloc%, dtype: float64

In [26]:
# criteria-wise allocation
df_portfolio_features.groupby('Criteria')['CurrAlloc%'].sum().sort_values(ascending=False)

Criteria
XY24     26.82
X40      25.68
X40N     15.18
AR        9.21
XR        8.24
XY25      7.37
OX40N     6.73
SR        0.81
Name: CurrAlloc%, dtype: float64

In [27]:
# conviction-wise allocation
df_portfolio_features.groupby('Conviction')['CurrAlloc%'].sum().sort_values(ascending=False)

Conviction
X-LC    23.50
X-MC    22.70
H-SC    21.46
X-SC    12.20
M-SC     9.95
H-MC     5.11
M-MC     2.04
H-LC     1.18
M-LC     1.03
L-SC     0.52
L-MC     0.35
Name: CurrAlloc%, dtype: float64

In [28]:
# sector-wise stats
df_tmp = df_portfolio_features.groupby('Category')[['CurrAlloc%', 'Current', 'Current P/L', 'FTT Amt']].sum().sort_values(by=['Current', 'Current P/L'], ascending=False)
df_tmp['Current P/L%'] = round(df_tmp['Current P/L'] * 100 / df_tmp['Current'], 2)
df_tmp['FTT%'] = round(df_tmp['FTT Amt'] * 100 / df_tmp['Current'], 2)
cols = ['CurrAlloc%', 'Current P/L%', 'FTT%']
df_tmp[cols].sort_values(by=['CurrAlloc%'], ascending=False)

               CurrAlloc%  Current P/L%    FTT%
Category
FMCG                15.09        -29.15   75.01
FINANCE             13.00        -29.05   81.64
IT                  12.01        -46.32  120.77
MISC                 6.89        -51.81  117.76
ELECTRICAL           6.58        -15.09   59.15
PAINTS               5.13        -50.08   76.14
INSURANCE            4.69        -12.84   51.45
BANKS                4.52        -33.17  100.77
PHARMA               4.19         -9.60   44.10
AUTO                 3.69        -38.63   93.63
AC                   2.04        -22.69   55.96
HEALTHCARE           1.88        -48.42   87.15
TRAVEL               1.79        -95.06  192.73
FOOTWEAR             1.78        -94.30  172.21
BREWERIES            1.77         -2.97   24.35
DURABLES             1.76        -71.68  113.45
APPARELS             1.75        -19.83   60.71
REALTY               1.47        -17.54   36.85
REFINERIES           1.42        -10.38   38.31
CERAMICS             1.38        -73.28  125.93
CEMENT               1.25        -67.96  193.62
CABLES               1.21          4.52   98.51
ENGINEERING          1.09        -73.21  152.43
CHEMICALS            1.05        -96.64  257.07
JEWELLERY            1.05       -139.03  222.08
ENTERTAINMENT        0.75       -102.23  222.84
TEXTILES             0.47        -52.01   95.36
HOTELS               0.34       -157.69  248.58

In [29]:
# money to be made criteria-wise
df_portfolio_features.groupby('Criteria')['FTT Amt'].agg(['sum', 'count']).sort_values(by='sum', ascending=False)

                sum  count
Criteria
XY24      4160923.0     21
X40       1885629.0     16
XR        1434763.0     12
AR        1393593.0     10
X40N      1354968.0     10
OX40N      931049.0     10
XY25       496512.0      5
SR         316370.0      2

In [30]:
# money to be made conviction-wise
df_portfolio_features.groupby('Conviction')['FTT Amt'].agg(['sum', 'count']).sort_values(by='sum', ascending=False)

                  sum  count
Conviction
H-SC        4043996.0     24
X-MC        1826456.0     15
X-LC        1764500.0     13
M-SC        1643161.0     14
X-SC        1620370.0     10
H-MC         424698.0      3
L-SC         224318.0      2
M-LC         159893.0      1
M-MC         125462.0      2
H-LC          82630.0      1
L-MC          58323.0      1

In [31]:
# money to be made criteria and conviction-wise
df_portfolio_features.groupby(['Conviction', 'Criteria'])['FTT Amt'].agg(['sum', 'count']).sort_values(by='sum', ascending=False)

                           sum  count
Conviction Criteria
H-SC       XY24      1413425.0      6
           AR         998049.0      5
M-SC       XY24       955523.0      6
X-LC       X40        941661.0      7
H-SC       XR         912451.0      7
X-SC       XY24       873057.0      4
X-MC       X40        726032.0      7
           X40N       546783.0      4
X-SC       X40N       529377.0      4
M-SC       OX40N      412564.0      5
H-SC       OX40N      403701.0      4
X-LC       XY24       391039.0      2
H-SC       SR         316370.0      2
X-MC       XY24       280381.0      2
X-LC       X40N       278808.0      2
X-MC       XY25       273260.0      2
H-MC       XY24       247498.0      1
X-SC       X40        217936.0      2
M-SC       XR         194562.0      2
H-MC       AR         177200.0      2
M-LC       XR         159893.0      1
X-LC       XY25       152992.0      2
L-SC       OX40N      114784.0      1
           XR         109534.0      1
H-LC       AR          82630.0      1
M-SC       AR          80512.0      1
M-MC       XY25        70260.0      1
L-MC       XR          58323.0      1
M-MC       AR          55202.0      1

In [32]:
# notebook execution time

end_time = time.time()
execution_time = round(end_time - start_time, 0)
print(f"Notebook execution time: {execution_time} seconds")

Notebook execution time: 46.0 seconds