<a href="https://colab.research.google.com/github/ankit-rathi/Quantvesting_v2/blob/main/myStocks_Portfolio_Analysis.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
'''
!pip install pandas==2.2.2 -qq
!pip install pyxirr -qq
!pip install ta -qq
!pip install yfinance==0.2.59 -qq
'''

'\n!pip install pandas==2.2.2 -qq\n!pip install pyxirr -qq\n!pip install ta -qq\n!pip install yfinance==0.2.59 -qq\n'

In [2]:
# import libraries

import numpy as np
import pandas as pd
import datetime
import warnings
warnings.filterwarnings('ignore')
import yfinance as yfin
import ta
import matplotlib.pyplot as plt
import requests

In [3]:
# notebook start time
import time
import datetime
import pytz

start_time = time.time()

# function to print date timestamp
def print_date_time():
  tz_NY = pytz.timezone('Asia/Kolkata')
  datetime_NY = datetime.datetime.now(tz_NY)
  print("Run date time (IST):", datetime_NY.strftime("%Y-%m-%d %H:%M:%S"))

In [4]:
# function to get booked and reserved amount
def get_amt():
  # fetch the JSON data from the URL
  url = "https://raw.githubusercontent.com/ankit-rathi/Tradevesting_v1/main/data/myPortfolioAmts.json"
  response = requests.get(url)
  pf_amts = response.json()  # parse the JSON data

  # extract values from the JSON
  py_booked_amt_dm = pf_amts["py_booked_amt_dm"]
  py_booked_amt_sv = pf_amts["py_booked_amt_sv"]
  cy_booked_amt_dm = pf_amts["cy_booked_amt_dm"]
  cy_booked_amt_sv = pf_amts["cy_booked_amt_sv"]
  reserve_amt_dm = pf_amts["reserve_amt_dm"]
  reserve_amt_sv = pf_amts["reserve_amt_sv"]

  # perform calculations
  py_booked_amt = py_booked_amt_dm + py_booked_amt_sv
  cy_booked_amt = cy_booked_amt_dm + cy_booked_amt_sv
  reserve_amt = reserve_amt_dm + reserve_amt_sv
  total_booked_amt = py_booked_amt + cy_booked_amt

  return total_booked_amt, reserve_amt, cy_booked_amt, py_booked_amt

gen_output = 0

In [5]:
# function to format the amount
def format_amt(number):
    abs_number = abs(number)

    if abs_number >= 1_00_00_000:  # Crores
        formatted_amt = f"{number / 1_00_00_000:.2f} C"
    elif abs_number >= 1_00_000:  # Lakhs
        formatted_amt = f"{number / 1_00_000:.2f} L"
    elif abs_number >= 1_000:  # Thousands
        formatted_amt = f"{number / 1_000:.2f} K"
    else:
        formatted_amt = f"{number:.2f}"

    return formatted_amt

# function to set start and end date
def get_start_end_date():
  start_date = (datetime.date.today() + datetime.timedelta(days=-365)).strftime('%Y-%m-%d')
  end_date = (datetime.date.today() + datetime.timedelta(days=1)).strftime('%Y-%m-%d')
  return start_date, end_date

# function to fetch my portfolio csv
def get_mypfs_df():
  mypfs_df = pd.read_csv('https://raw.githubusercontent.com/ankit-rathi/Tradevesting_v1/main/data/myPortfolioStocks.csv')
  return mypfs_df

# function to fetch my prospects csv
def get_mypps_df():
  mypps_df = pd.read_csv('https://raw.githubusercontent.com/ankit-rathi/Tradevesting_v1/main/data/myProspectsScrips.csv')
  return mypps_df

# function to fetch screener data
def get_myscreen_df():
  myscreen_df = pd.read_csv('https://raw.githubusercontent.com/ankit-rathi/Tradevesting_v1/main/data/myScreenerDB.csv')
  return myscreen_df

# function to fetch momentum data
def get_myinvmt_df():
  myinvmt_df = pd.read_csv('https://raw.githubusercontent.com/ankit-rathi/Tradevesting_v1/main/data/myInvestments.csv')
  return myinvmt_df

# function to get the stock ids
def get_stock_ids(df_pf):
  stock_n100 = df_pf['Symbol'].unique()

  exclude = ['CADILAHC','MMTC', 'MASFIN']

  stock_ids = df_pf[~df_pf['Symbol'].isin(exclude) ]['Symbol'].unique()

  #mypf = mypf[mypf.Forecast.notnull()]
  #stock_ids = mypf['Symbol'].unique()

  #stock_ids.sort()
  return stock_ids

# get features from screener data
def get_screener_features():
  myscreen_df = get_myscreen_df()
  cols = ['Symbol', 'EPS', 'MedPE', 'ROCE%', 'ROE%', 'CapType']
  return myscreen_df[cols]

# get relative strength
def get_relative_strength(stock_list):

    # Dictionary to store stock tickers and their corresponding percentage price change
    stock_changes = {}

    # Loop through each stock and fetch its price data
    for stock in stock_list:
        try:
            # Download the stock data for the given date range
            stock_data = yfin.Ticker(stock + '.NS').history(period='1mo', interval='1d')[map(str.title, ['open', 'close', 'low', 'high', 'volume'])]

            # Calculate the percentage change for the stock
            if len(stock_data) > 0:
                start_price = stock_data['Close'].iloc[0]
                end_price = stock_data['Close'].iloc[-1]
                percent_change = round(((end_price - start_price) / start_price) * 100, 2)
                stock_changes[stock] = percent_change
            else:
                stock_changes[stock] = np.nan  # If no data is available, set to NaN

        except Exception as e:
            print(f"Error fetching data for {stock}: {e}")
            stock_changes[stock] = np.nan

    # Create a DataFrame with stock tickers and their percentage changes
    df = pd.DataFrame(list(stock_changes.items()), columns=['Symbol', 'Percent_Change'])

    # Drop any stocks with missing data (NaN values)
    df = df.dropna()

    # Calculate the percentile rank based on percentage change
    df['RSP'] = round(df['Percent_Change'].rank(pct=True) * 100, 2)
    cols = ['Symbol', 'RSP']
    df = df[cols]
    # Sort by percentile rank (optional)
    df = df.sort_values(by='RSP', ascending=False).reset_index(drop=True)

    return df

In [6]:
# function to get stock technicals
def stock_prec_dev(stock_symbol):
    #stock_symbol = 'ULTRACEMCO.NS'
    short_window = 20
    mid_window = 50
    long_window = 200
    moving_avg = 'SMA'

    start = datetime.datetime(*map(int, start_date.split('-')))
    end = datetime.datetime(*map(int, end_date.split('-')))

    stock_df = yfin.Ticker(stock_symbol + '.NS').history(period='max', interval='1d')[map(str.title, ['open', 'close', 'low', 'high', 'volume'])]

    stock_df['Max'] = round(max(stock_df['Close']),2)
    stock_df = stock_df[(stock_df.index <= end_date) & (stock_df.index >= start_date)]
    stock_df['200_SMA'] = round(stock_df['Close'].rolling(window = 200, min_periods = 1).mean(),0)
    stock_df['Dev%_200'] = round((stock_df['Close'] - stock_df['200_SMA'])*100/stock_df['200_SMA'],2)
    stock_df.dropna(axis = 0, inplace = True) # remove any null rows

    stock_df['20_SMA'] = stock_df['Close'].rolling(window=20).mean()
    stock_df['50_SMA'] = stock_df['Close'].rolling(window=50).mean()
    stock_df['Symbol'] = stock_symbol

    stock_df['Close'] = round(stock_df['Close'],2)
    stock_df['Min'] = round(min(stock_df['Close']),2)
    stock_df['RSI_14'] = ta.momentum.RSIIndicator(close=stock_df['Close'], window=14).rsi()
    stock_df['RSI_14'] = round(stock_df['RSI_14'],0)
    stock_df['Prev_Close'] = stock_df['Close'].shift(1)
    stock_df.drop(['Open', 'Low', 'High', 'Volume'], axis=1, inplace=True)
    stock_df = stock_df.tail(1)

    max_SMA = max(stock_df['20_SMA'].item(), stock_df['50_SMA'].item(), stock_df['200_SMA'].item())
    min_SMA = min(stock_df['20_SMA'].item(), stock_df['50_SMA'].item(), stock_df['200_SMA'].item())
    ABS_Spread = max_SMA - min_SMA
    stock_df['Spread%'] = round((ABS_Spread / stock_df['200_SMA'].item()) * 100,2)

    return stock_df

# function to compute stock attributes
def get_common_features(stock_ids, df_mypf):

  df_prec_dev = pd.DataFrame()
  df_tmp = get_screener_features()
  df_rs = get_relative_strength(stock_ids)

  for stock_id in stock_ids:
      tmp = stock_prec_dev(stock_id)
      tmp = tmp.reset_index()
      df_prec_dev = pd.concat([df_prec_dev, tmp], ignore_index = True)
  df_prec_dev = pd.merge(df_prec_dev, df_mypf, on= 'Symbol')
  df_prec_dev = pd.merge(df_prec_dev, df_tmp, on= 'Symbol', how='left')
  df_prec_dev = pd.merge(df_prec_dev, df_rs, on= 'Symbol', how='left')
  #print(df_prec_dev.columns)
  df_prec_dev['Curr_PE'] = round(df_prec_dev['Close']/df_prec_dev['EPS'],1)
  df_prec_dev['Dev%_PE'] = round((df_prec_dev['Curr_PE'] - df_prec_dev['MedPE'])*100/df_prec_dev['MedPE'],2)
  df_prec_dev['Conviction'] = df_prec_dev['Conviction'] + '-' + df_prec_dev['CapType']
  return df_prec_dev

# function to arrange stock features
def arrange_features(df_stocks, common_cols, diff_cols):
  df_stocks_common = df_stocks[common_cols].drop_duplicates()
  df_stocks_diff = df_stocks[diff_cols]
  df_stocks_diff['Investment'] = df_stocks_diff['AvgCost'] * df_stocks_diff['Shares']
  df_stocks_diff = df_stocks_diff.groupby(['Symbol'])[['Shares', 'Investment']].aggregate(['sum']).reset_index()
  df_stocks_diff.columns = ['Symbol', 'Shares', 'Investment']
  df_stocks_diff['AvgCost'] = round(df_stocks_diff['Investment']/df_stocks_diff['Shares'],2)
  df_stocks = pd.merge(df_stocks_diff, df_stocks_common, on='Symbol')
  return df_stocks

# plot fact distribution across dimension
def plot_pie_chart(df, dimension, fact):
  # grouping the data by category and calculating the sum of fact for each type
  grouped_data = df.groupby(dimension)[fact].sum()

  # sorting the grouped data in descending order
  grouped_data = grouped_data.sort_values(ascending=False)

  # creating a pie chart
  grouped_data.plot.pie(autopct='%1.1f%%', startangle=90, figsize=(6, 6))

  # adding a title and displaying the plot
  plt.title(f'{dimension} {fact} Distribution')
  plt.ylabel('')  # To hide the y-label
  plt.show()

In [7]:
# function to get portfolio features

def get_portfolio_features(df_common_features):

  print_date_time()
  print('-------------------')

  #df_common_features["Target"] = df_common_features["Target"].fillna(df_common_features["Max"])
  df_common_features['NTT'] = np.where(df_common_features['Strategy']== 'NTT', df_common_features["Target"], df_common_features['Max'])
  df_common_features['LTT'] = np.where(df_common_features['Strategy']== 'BTT', df_common_features["Target"], df_common_features['Max'])
  df_common_features['BOL'] = df_common_features['Min']

  tmp_df = df_common_features[df_common_features['Symbol'].isin(mypf_df[mypf_df['InPortfolio'] != 'NA'].Symbol.values)]
  print('qualified stocks: '+str(len(tmp_df['Symbol'].unique())))
  tmp_df1 = tmp_df[tmp_df['LatestQtr'] == 1]
  print('with latest results: '+str(len(tmp_df1['Symbol'].unique())))
  tmp_df1 = tmp_df1[tmp_df1['StarStock'] == 1]
  print('still star stocks: '+str(len(tmp_df1['Symbol'].unique())))
  tmp_df['Investment'] = tmp_df['AvgCost'] * tmp_df['Shares']
  tmp_df['Current'] = round(tmp_df['Close'] * tmp_df['Shares'],0)
  tmp_df['Previous'] = tmp_df['Prev_Close'] * tmp_df['Shares']
  tmp_df['EstimatedST'] = tmp_df['NTT'] * tmp_df['Shares']
  tmp_df['EstimatedLT'] = tmp_df['LTT'] * tmp_df['Shares']
  tmp_df['Current P/L'] = round((tmp_df['Current'] - tmp_df['Investment']),0)
  tmp_df['Today P/L%'] = round((tmp_df['Current'] - tmp_df['Previous'])*100/tmp_df['Previous'],2)
  tmp_df['Current P/L%'] = round((tmp_df['Current'] - tmp_df['Investment'])*100/tmp_df['Investment'],2)
  tmp_df['EstimatedST P/L%'] = round((tmp_df['EstimatedST'] - tmp_df['Investment'])*100/tmp_df['Investment'],2)
  tmp_df['EstimatedLT P/L%'] = round((tmp_df['EstimatedLT'] - tmp_df['Investment'])*100/tmp_df['Investment'],2)
  tmp_df['NTT%'] = round((tmp_df['NTT'] - tmp_df['Close'])*100/tmp_df['Close'],2)
  tmp_df['LTT%'] = round((tmp_df['LTT'] - tmp_df['Close'])*100/tmp_df['Close'],2)
  tmp_df['Gained%'] = round((tmp_df['Close'] - tmp_df['BOL'])*100/tmp_df['BOL'],2)
  investment = round(sum(tmp_df['AvgCost']*tmp_df['Shares']),0)
  current = round(sum(tmp_df['Close']*tmp_df['Shares']),0)
  tmp_df['InitAlloc%'] = round(tmp_df['Investment']*100/investment,2)
  tmp_df['CurrAlloc%'] = round(tmp_df['Current']*100/current,2)
  tmp_df['FTT'] = tmp_df['LTT']
  tmp_df.loc[tmp_df['Strategy'] == 'NTT', 'FTT'] = tmp_df['NTT']
  tmp_df['FTT%'] = tmp_df['LTT%']
  tmp_df.loc[tmp_df['Strategy'] == 'NTT', 'FTT%'] = tmp_df['NTT%']
  tmp_df['FTT Amt'] = round(tmp_df['FTT%'] * tmp_df['Current']/100,0)
  tmp_df['OTT%'] = round((tmp_df['FTT'] - tmp_df['AvgCost'])*100/tmp_df['AvgCost'],2)
  tmp_df['RRR Ind'] = round(tmp_df['Current P/L']/tmp_df['FTT Amt'],2)
  tmp_df['Risk Ind'] = round(tmp_df['Current P/L%']*tmp_df['CurrAlloc%'],0)

  return tmp_df

# function to print portfolio features
def print_portfolio_stats(df_portfolio_features, myinvmt_df):
  from pyxirr import xirr

  total_booked_amt, reserve_amt, cy_booked_amt, py_booked_amt = get_amt()

  dates = myinvmt_df['Date'].values
  dates = np.append(dates, datetime.date.today().strftime('%d-%b-%y'))
  investment = myinvmt_df['Investment'].values
  dates= pd.to_datetime(dates)

  current = round(sum(df_portfolio_features['Close']*df_portfolio_features['Shares']),0) + reserve_amt
  investment_xirr = np.append(investment, current)
  cagr = round(xirr(pd.DataFrame({"dates": dates, "amounts": investment_xirr}))*100,2)

  investment = -sum(investment)
  invested = round(sum(df_portfolio_features['AvgCost']*df_portfolio_features['Shares']),0) + reserve_amt
  previous = round(sum(df_portfolio_features['Prev_Close']*df_portfolio_features['Shares']),0) + reserve_amt
  cy_invested = investment + py_booked_amt

  today_pnl_amount = current-previous
  today_pnl_percentage = round((current-previous)*100/previous,2)

  curr_pnl_amount = current-invested
  curr_pnl_percentage = round((curr_pnl_amount)*100/(cy_invested),2)

  cy_pnl_amount = cy_booked_amt + curr_pnl_amount
  cy_pnl_percentage = round((cy_pnl_amount)*100/cy_invested,2)

  overall_pnl_amount = total_booked_amt + curr_pnl_amount
  overall_pnl_percentage = round((overall_pnl_amount)*100/investment,2)

  estimate_st = round(sum(df_portfolio_features['FTT']*df_portfolio_features['Shares']),0)  + reserve_amt
  est_st_pnl_amount = estimate_st-current
  est_st_pnl_percentage = round((est_st_pnl_amount)*100/current,2)

  estimate_lt = round(sum(df_portfolio_features['LTT']*df_portfolio_features['Shares']),0)  + reserve_amt
  est_lt_pnl_amount = estimate_lt-current
  est_lt_pnl_percentage = round((est_lt_pnl_amount)*100/current,2)

  total_profit = round(sum(df_portfolio_features[df_portfolio_features['Current P/L%'] > 0]['Current']) - sum(df_portfolio_features[df_portfolio_features['Current P/L%'] > 0]['Investment']),0)
  total_loss = round(sum(df_portfolio_features[df_portfolio_features['Current P/L%'] < 0]['Current']) - sum(df_portfolio_features[df_portfolio_features['Current P/L%'] < 0]['Investment']),0)

  cy_booked_percentage = round((cy_booked_amt)*100/current,2)
  py_booked_percentage = round((py_booked_amt)*100/investment,2)
  total_booked_percentage = round((total_booked_amt)*100/investment,2)

  print('-------------------')
  print('Initial Investment: ', format_amt(investment))
  print('CY Investment: ', format_amt(cy_invested))
  print('Reserve: ', format_amt(reserve_amt))
  print('Current: ',  format_amt(current))
  print('-------------------')
  print('Today PnL: '+ '{} ({}%)'.format(format_amt(today_pnl_amount), today_pnl_percentage))
  print('Current PnL: '+ '{} ({}%)'.format(format_amt(curr_pnl_amount), curr_pnl_percentage))
  print('CY Booked + Current PnL: '+ '{} ({}%)'.format(format_amt(cy_pnl_amount), cy_pnl_percentage))
  print('-------------------')
  print('Total profit: ', format_amt(total_profit))
  print('Total loss: ', format_amt(total_loss))
  print('-------------------')
  print('Total Booked + Current PnL: '+ '{} ({}%)'.format(format_amt(overall_pnl_amount), overall_pnl_percentage))
  print('Total Booked PnL: '+ '{} ({}%)'.format(format_amt(total_booked_amt), total_booked_percentage))
  print('Curr Year Booked PnL: '+ '{} ({}%)'.format(format_amt(cy_booked_amt), cy_booked_percentage))
  print('Prev Year Booked PnL: '+ '{} ({}%)'.format(format_amt(py_booked_amt), py_booked_percentage))
  print('===================')
  print('Est FTT: ',  format_amt(estimate_st))
  print('Est FTT PnL: '+ '{} ({}%)'.format(format_amt(est_st_pnl_amount), est_st_pnl_percentage))

  print('===================')
  print('Deployed: ', format_amt(investment))

  print('Current: ', format_amt(current))

  print('CAGR/XIRR %: '+'{}%'.format(cagr))

In [8]:
# get start and end date
start_date, end_date = get_start_end_date()

# get portfolio and prospects data
mypfs_df = get_mypfs_df()
mypps_df = get_mypps_df()
myinvmt_df = get_myinvmt_df()

# merge above datasets
mypf_df = pd.merge(mypfs_df, mypps_df, on="Symbol")

# seggregate dm and sv portfolio
dm_pf = mypf_df[mypf_df['InPortfolio'] == 'DM']
sv_pf = mypf_df[mypf_df['InPortfolio'] == 'SV']

# build portfolio stock dataframe
dm_stocks = get_stock_ids(dm_pf)
sv_stocks = get_stock_ids(sv_pf)
df_stocks = pd.concat([dm_pf,sv_pf], ignore_index = True)

# arrange common and diff stock features
common_cols = ['Symbol', 'Target', 'Criteria', 'Strategy', 'CumlRnk', 'LatestQtr', 'StarStock', 'Conviction', 'Category', 'InFolio', 'XIRR', 'MBQ']
diff_cols = ['Symbol', 'AvgCost', 'Shares']
df_stocks = arrange_features(df_stocks, common_cols, diff_cols)

# get common features
stock_ids = df_stocks['Symbol'].values
df_common_features = get_common_features(stock_ids, df_stocks)

df_common_features.reset_index(drop=True, inplace=True)
df_common_features.drop(['Date'], axis=1, inplace=True)
# get and print portfolio features
df_portfolio_features = get_portfolio_features(df_common_features)

print_portfolio_stats(df_portfolio_features, myinvmt_df)

df = df_portfolio_features
#plot_pie_chart(df, 'CapType', 'Current')
list_ox40n = list(df[df['MBQ'].str.contains('OX40N', na=False)]['Symbol'].values)

Run date time (IST): 2026-08-10 13:55:35
-------------------
qualified stocks: 88
with latest results: 30
still star stocks: 19
-------------------
Initial Investment:  1.46 C
CY Investment:  1.89 C
Reserve:  2.24 L
Current:  1.62 C
-------------------
Today PnL: 10.42 K (0.06%)
Current PnL: -30.41 L (-16.09%)
CY Booked + Current PnL: -26.19 L (-13.86%)
-------------------
Total profit:  3.89 L
Total loss:  -34.30 L
-------------------
Total Booked + Current PnL: 16.68 L (11.42%)
Total Booked PnL: 47.09 L (32.24%)
Curr Year Booked PnL: 4.22 L (2.61%)
Prev Year Booked PnL: 42.87 L (29.35%)
===================
Est FTT:  2.67 C
Est FTT PnL: 1.05 C (64.94%)
===================
Deployed:  1.46 C
Current:  1.62 C
CAGR/XIRR %: 4.68%

In [9]:
# top 5 near their targets
cols = ['Symbol', 'Today P/L%', 'Current P/L%', 'FTT%', 'OTT%', 'FTT Amt', 'Current P/L', 'Current', 'FTT', 'Dev%_PE', 'RSI_14','Conviction', 'Spread%',  'CumlRnk', 'RRR Ind', 'CurrAlloc%', 'Gained%', 'Criteria', 'Strategy', 'Category']
df_tmp = df_portfolio_features[~df_portfolio_features['Symbol'].isin(['ENRIN','BLUSPRING','DIGITIDE'])]
df_tmp = df_tmp.sort_values(by = 'FTT Amt', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
55,MEDANTA,1.77,26.72,0.31,27.12,693.0,47174.0,223691.0,1486.00,22.86,71.0,X-SC,15.69,87.0,68.07,1.40,54.14,XY24,NTT,HEALTHCARE
52,M&M,0.47,11.10,6.95,18.82,18584.0,26710.0,267391.0,3762.88,-3.30,70.0,X-LC,5.36,25.0,1.44,1.68,21.29,X40N,ATH,AUTO
80,UNITDSPR,1.10,12.32,7.52,20.77,19777.0,28844.0,262988.0,1644.00,-0.31,72.0,X-MC,7.59,64.0,1.46,1.65,26.42,X40N,NTT,BREWERIES
79,TTKPRESTIG,-1.45,-21.10,26.85,0.09,21350.0,-21260.0,79517.0,770.00,84.63,43.0,M-SC,13.37,250.0,-1.00,0.50,43.12,OX40N,NTT,DURABLES
69,SIS,-1.83,-1.93,23.65,21.26,25751.0,-2147.0,108885.0,528.00,2597.93,46.0,H-SC,22.90,168.0,-0.08,0.68,61.90,OX40N,NTT,MISC

In [10]:
# top 5 today
df_tmp = df_portfolio_features.sort_values(by = 'Today P/L%', ascending=False)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
0,5PAISA,3.88,-27.31,55.32,12.90,87864.0,-59667.0,158829.0,593.00,134.38,60.0,H-SC,11.63,170.0,-0.68,1.00,53.27,OX40N,NTT,FINANCE
58,QUESS,3.50,32.04,31.70,73.90,44701.0,34221.0,141014.0,424.00,-28.93,64.0,X-SC,39.47,80.0,0.77,0.88,94.09,XY24,NTT,MISC
25,FINCABLES,3.32,34.09,55.05,107.91,108986.0,50333.0,197977.0,1641.55,20.75,56.0,M-SC,17.41,220.0,0.46,1.24,48.94,OX40N,ATH,CABLES
82,VALIANTORG,2.98,-38.26,182.06,74.15,183906.0,-62591.0,101014.0,838.00,-281.53,64.0,H-SC,4.32,145.0,-0.34,0.63,50.32,XR,NTT,CHEMICALS
73,TANLA,2.77,-28.74,204.86,117.25,395273.0,-77813.0,192948.0,1922.32,-28.13,65.0,H-SC,14.21,147.0,-0.20,1.21,68.93,AR,ATH,IT

In [11]:
# bottom 5 today
df_tmp = df_portfolio_features.sort_values(by = 'Today P/L%', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
5,ATULAUTO,-9.72,-10.18,62.06,45.57,109891.0,-20060.0,177072.0,844.0,3840.54,52.0,M-SC,9.69,248.0,-0.18,1.11,36.26,XY24,NTT,AUTO
61,RECLTD,-5.82,-6.43,29.03,20.74,55188.0,-13062.0,190108.0,446.0,3.52,39.0,M-MC,3.40,191.0,-0.24,1.19,14.59,XY25,NTT,FINANCE
18,COFFEEDAY,-4.11,-47.46,157.48,35.27,93943.0,-53895.0,59654.0,80.0,-59.76,45.0,L-SC,4.97,266.0,-0.57,0.37,47.11,XR,NTT,HOTELS
59,RAJESHEXPO,-1.89,-84.16,531.71,0.07,115541.0,-115447.0,21730.0,518.0,696.72,35.0,L-SC,36.34,268.0,-1.00,0.14,7.32,OX40N,NTT,JEWELLERY
9,BANDHANBNK,-1.85,-16.89,131.52,92.42,304485.0,-47047.0,231512.0,400.0,98.28,38.0,H-SC,13.92,174.0,-0.15,1.45,27.53,XY24,NTT,BANKS

In [12]:
# top 5 to exit based on CumlRnk
df_tmp = df_portfolio_features[~df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])]
df_tmp = df_tmp[(df_tmp['Current P/L%'] > -1) & (df_tmp['Current P/L%'] < 1)].sort_values(by = 'CumlRnk', ascending=False)
df_tmp[cols].head()

Empty DataFrame
Columns: [Symbol, Today P/L%, Current P/L%, FTT%, OTT%, FTT Amt, Current P/L, Current, FTT, Dev%_PE, RSI_14, Conviction, Spread%, CumlRnk, RRR Ind, CurrAlloc%, Gained%, Criteria, Strategy, Category]
Index: []

In [13]:
# OX40N stocks to exit
df_tmp = df_portfolio_features[(df_portfolio_features['Symbol'].isin(list_ox40n))].sort_values(by = 'Current P/L%', ascending=False)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
25,FINCABLES,3.32,34.09,55.05,107.91,108986.0,50333.0,197977.0,1641.55,20.75,56.0,M-SC,17.41,220.0,0.46,1.24,48.94,OX40N,ATH,CABLES
69,SIS,-1.83,-1.93,23.65,21.26,25751.0,-2147.0,108885.0,528.00,2597.93,46.0,H-SC,22.90,168.0,-0.08,0.68,61.90,OX40N,NTT,MISC
43,INDIGOPNTS,2.01,-18.81,23.18,0.02,32853.0,-32827.0,141732.0,1408.00,115.96,67.0,M-SC,5.07,222.0,-1.00,0.89,60.80,OX40N,NTT,PAINTS
16,CERA,-0.03,-20.76,56.35,23.89,78541.0,-36523.0,139380.0,9475.00,-23.63,45.0,H-SC,12.72,153.0,-0.47,0.87,35.49,OX40N,NTT,CERAMICS
79,TTKPRESTIG,-1.45,-21.10,26.85,0.09,21350.0,-21260.0,79517.0,770.00,84.63,43.0,M-SC,13.37,250.0,-1.00,0.50,43.12,OX40N,NTT,DURABLES

In [14]:
# top 5 to book for rotation
df_tmp = df_portfolio_features[(df_portfolio_features['Current P/L%'] > 20) ].sort_values(by = 'CumlRnk', ascending=False)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
25,FINCABLES,3.32,34.09,55.05,107.91,108986.0,50333.0,197977.0,1641.55,20.75,56.0,M-SC,17.41,220.0,0.46,1.24,48.94,OX40N,ATH,CABLES
55,MEDANTA,1.77,26.72,0.31,27.12,693.0,47174.0,223691.0,1486.00,22.86,71.0,X-SC,15.69,87.0,68.07,1.40,54.14,XY24,NTT,HEALTHCARE
58,QUESS,3.50,32.04,31.70,73.90,44701.0,34221.0,141014.0,424.00,-28.93,64.0,X-SC,39.47,80.0,0.77,0.88,94.09,XY24,NTT,MISC

In [15]:
# top 5 to monitor for exit
df_tmp = df_portfolio_features[~df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])]
df_tmp = df_tmp[(df_tmp['Current P/L%'] > 0) ].sort_values(by = 'Dev%_PE', ascending=False)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
70,STARHEALTH,-0.04,10.22,33.60,47.26,104114.0,28739.0,309862.0,761.00,73.85,43.0,H-SC,17.31,173.0,0.28,1.94,33.98,XY24,NTT,INSURANCE
25,FINCABLES,3.32,34.09,55.05,107.91,108986.0,50333.0,197977.0,1641.55,20.75,56.0,M-SC,17.41,220.0,0.46,1.24,48.94,OX40N,ATH,CABLES
87,ZYDUSLIFE,0.49,18.07,14.76,35.51,36524.0,37880.0,247454.0,1285.01,2.70,51.0,H-MC,15.56,120.0,1.04,1.55,30.22,AR,ATH,PHARMA

In [16]:
# top 5 to book for rotation from weak conviction
df_tmp = df_portfolio_features[~df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])]
df_tmp = df_tmp[~df_tmp['Criteria'].isin(['XY25','XY24','X40', 'X40N'])].sort_values(by = 'RRR Ind', ascending=False)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
87,ZYDUSLIFE,0.49,18.07,14.76,35.51,36524.0,37880.0,247454.0,1285.01,2.70,51.0,H-MC,15.56,120.0,1.04,1.55,30.22,AR,ATH,PHARMA
25,FINCABLES,3.32,34.09,55.05,107.91,108986.0,50333.0,197977.0,1641.55,20.75,56.0,M-SC,17.41,220.0,0.46,1.24,48.94,OX40N,ATH,CABLES
69,SIS,-1.83,-1.93,23.65,21.26,25751.0,-2147.0,108885.0,528.00,2597.93,46.0,H-SC,22.90,168.0,-0.08,0.68,61.90,OX40N,NTT,MISC
3,ALKYLAMINE,1.56,-18.08,135.03,92.54,111683.0,-18253.0,82710.0,4520.85,-12.24,59.0,H-SC,13.59,142.0,-0.16,0.52,57.06,SR,ATH,CHEMICALS
42,INDIAMART,2.39,-22.78,160.19,100.92,152567.0,-28095.0,95241.0,4675.60,-65.23,44.0,H-SC,12.19,140.0,-0.18,0.60,3.10,AR,ATH,MISC

In [17]:
# top 5 to accumulate based on lowest RSI_14
df_tmp = df_portfolio_features[df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])].sort_values(by = 'RSI_14', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
34,HDFCBANK,0.34,-10.41,46.28,31.05,121528.0,-30527.0,262593.0,1073.00,-25.47,36.0,X-LC,10.97,26.0,-0.25,1.65,1.92,X40,BTT,BANKS
57,PGHH,0.05,-36.29,107.22,32.01,145845.0,-77496.0,136024.0,17616.87,-56.92,36.0,X-MC,19.22,57.0,-0.53,0.85,0.29,X40,ATH,FMCG
84,VOLTAS,-1.17,-0.65,46.14,45.20,87897.0,-1242.0,190500.0,1856.00,13.69,39.0,X-MC,4.07,79.0,-0.01,1.19,4.41,XY25,NTT,AC
35,HDFCLIFE,-0.13,-7.51,50.46,39.15,117016.0,-18838.0,231899.0,811.41,-31.13,39.0,X-LC,16.10,31.0,-0.16,1.45,0.63,X40,ATH,INSURANCE
20,DABUR,0.61,-19.35,78.18,43.70,156408.0,-48006.0,200062.0,735.00,-26.86,40.0,X-MC,9.23,70.0,-0.31,1.25,1.80,XY24,BTT,FMCG

In [18]:
# top 5 to accumulate based on Spread and CumlRnk
df_tmp = df_portfolio_features[df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])]
df_tmp = df_tmp[(df_tmp['CumlRnk'] < 100)].sort_values(by = 'Spread%', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
19,COLPAL,-0.90,-23.62,83.10,39.86,167172.0,-62195.0,201170.0,3683.41,-7.64,43.0,X-MC,1.64,62.0,-0.37,1.26,13.79,XY25,ATH,FMCG
11,BERGEPAINT,2.05,-0.22,25.59,25.32,65815.0,-560.0,257189.0,680.00,-5.64,64.0,X-MC,2.14,68.0,-0.01,1.61,34.87,XY24,NTT,PAINTS
8,BAJAJHLDNG,1.97,3.18,24.29,28.24,64163.0,8150.0,264155.0,14274.15,-5.41,66.0,X-LC,2.73,28.0,0.13,1.66,32.95,X40,ATH,FINANCE
23,DMART,2.76,-2.31,34.53,31.42,105173.0,-7205.0,304585.0,5391.45,-18.80,50.0,X-LC,3.18,14.0,-0.07,1.91,9.91,X40N,ATH,FMCG
26,GILLETTE,-0.42,-9.60,43.50,29.72,99846.0,-24366.0,229530.0,10978.86,-30.50,44.0,X-SC,3.37,83.0,-0.24,1.44,5.48,X40,ATH,FMCG

In [19]:
# top 5 to accumulate based on lowest Gained%
df_tmp = df_portfolio_features[df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])].sort_values(by = 'Gained%', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
57,PGHH,0.05,-36.29,107.22,32.01,145845.0,-77496.0,136024.0,17616.87,-56.92,36.0,X-MC,19.22,57.0,-0.53,0.85,0.29,X40,ATH,FMCG
35,HDFCLIFE,-0.13,-7.51,50.46,39.15,117016.0,-18838.0,231899.0,811.41,-31.13,39.0,X-LC,16.10,31.0,-0.16,1.45,0.63,X40,ATH,INSURANCE
20,DABUR,0.61,-19.35,78.18,43.70,156408.0,-48006.0,200062.0,735.00,-26.86,40.0,X-MC,9.23,70.0,-0.31,1.25,1.80,XY24,BTT,FMCG
34,HDFCBANK,0.34,-10.41,46.28,31.05,121528.0,-30527.0,262593.0,1073.00,-25.47,36.0,X-LC,10.97,26.0,-0.25,1.65,1.92,X40,BTT,BANKS
47,ITC,-1.12,-21.95,59.77,24.70,185322.0,-87220.0,310058.0,452.00,-59.16,46.0,X-LC,11.25,1.0,-0.47,1.94,2.67,X40,NTT,FMCG

In [20]:
# top 5 to accumulate based on lowest CurrAlloc%
df_tmp = df_portfolio_features[df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])].sort_values(by = 'CurrAlloc%', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
10,BATAINDIA,-0.73,-53.86,193.06,35.20,114604.0,-69308.0,59362.0,2096.00,-22.17,58.0,X-SC,14.05,91.0,-0.60,0.37,19.26,X40,NTT,FOOTWEAR
62,RELAXO,0.93,-44.65,175.15,52.31,140735.0,-64809.0,80351.0,1176.00,-41.05,61.0,X-SC,11.80,92.0,-0.46,0.50,79.66,X40N,NTT,FOOTWEAR
57,PGHH,0.05,-36.29,107.22,32.01,145845.0,-77496.0,136024.0,17616.87,-56.92,36.0,X-MC,19.22,57.0,-0.53,0.85,0.29,X40,ATH,FMCG
58,QUESS,3.50,32.04,31.70,73.90,44701.0,34221.0,141014.0,424.00,-28.93,64.0,X-SC,39.47,80.0,0.77,0.88,94.09,XY24,NTT,MISC
40,ICICIPRULI,-0.59,-17.58,58.05,30.28,94262.0,-34624.0,162381.0,787.27,-39.71,45.0,X-MC,13.51,78.0,-0.37,1.02,8.19,X40,ATH,INSURANCE

In [21]:
# top 5 to accumulate based on CumlRnk
df_tmp = df_portfolio_features.sort_values(by = 'CumlRnk', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
47,ITC,-1.12,-21.95,59.77,24.70,185322.0,-87220.0,310058.0,452.00,-59.16,46.0,X-LC,11.25,1.0,-0.47,1.94,2.67,X40,NTT,FMCG
75,TCS,-0.44,-28.31,73.25,24.20,243272.0,-131161.0,332112.0,4230.71,-39.36,62.0,X-LC,15.48,2.0,-0.54,2.08,23.85,X40,ATH,IT
45,INFY,0.91,-15.59,66.30,40.38,210697.0,-58676.0,317794.0,1972.00,-36.50,64.0,X-LC,16.28,3.0,-0.28,1.99,20.35,X40,NTT,IT
77,TMPV,0.25,-17.24,72.49,42.75,249635.0,-71735.0,344372.0,600.00,-83.62,56.0,X-LC,5.30,4.0,-0.29,2.16,18.41,XY24,NTT,AUTO
33,HCLTECH,0.20,-9.08,36.35,23.97,102280.0,-28111.0,281375.0,1853.42,-7.36,69.0,X-LC,13.32,8.0,-0.27,1.76,32.78,X40,ATH,IT

In [22]:
# top 5 for average up
df_tmp = df_portfolio_features[(df_portfolio_features['Dev%_200'] > 5)].sort_values(by = 'CurrAlloc%', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
44,INDUSINDBK,-0.13,-24.64,76.35,32.89,44420.0,-19026.0,58180.0,1800.00,-373.81,56.0,L-MC,14.00,258.0,-0.43,0.36,43.44,XR,NTT,BANKS
62,RELAXO,0.93,-44.65,175.15,52.31,140735.0,-64809.0,80351.0,1176.00,-41.05,61.0,X-SC,11.80,92.0,-0.46,0.50,79.66,X40N,NTT,FOOTWEAR
79,TTKPRESTIG,-1.45,-21.10,26.85,0.09,21350.0,-21260.0,79517.0,770.00,84.63,43.0,M-SC,13.37,250.0,-1.00,0.50,43.12,OX40N,NTT,DURABLES
3,ALKYLAMINE,1.56,-18.08,135.03,92.54,111683.0,-18253.0,82710.0,4520.85,-12.24,59.0,H-SC,13.59,142.0,-0.16,0.52,57.06,SR,ATH,CHEMICALS
12,BOSCH-HCIL,1.58,-25.12,33.53,-0.01,32090.0,-32101.0,95704.0,2282.00,19486.96,86.0,M-SC,3.53,231.0,-1.00,0.60,62.90,OX40N,BTT,AC

In [23]:
# top 5 RSP
df_tmp = df_portfolio_features.sort_values(by = 'RSP', ascending=False)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
12,BOSCH-HCIL,1.58,-25.12,33.53,-0.01,32090.0,-32101.0,95704.0,2282.00,19486.96,86.0,M-SC,3.53,231.0,-1.00,0.60,62.90,OX40N,BTT,AC
75,TCS,-0.44,-28.31,73.25,24.20,243272.0,-131161.0,332112.0,4230.71,-39.36,62.0,X-LC,15.48,2.0,-0.54,2.08,23.85,X40,ATH,IT
33,HCLTECH,0.20,-9.08,36.35,23.97,102280.0,-28111.0,281375.0,1853.42,-7.36,69.0,X-LC,13.32,8.0,-0.27,1.76,32.78,X40,ATH,IT
73,TANLA,2.77,-28.74,204.86,117.25,395273.0,-77813.0,192948.0,1922.32,-28.13,65.0,H-SC,14.21,147.0,-0.20,1.21,68.93,AR,ATH,IT
38,HYUNDAI,1.40,15.42,24.71,43.94,71679.0,38750.0,290082.0,2782.73,-4.38,75.0,X-LC,4.58,29.0,0.54,1.82,33.19,X40N,ATH,AUTO

In [24]:
# Top N allocation
df_tmp = df_portfolio_features.sort_values(by = 'CurrAlloc%', ascending=False)
top_n_values = [10, 25, 50]

sum_df = pd.DataFrame({
    'Top_N': top_n_values,
    'Sum_Alloc%': [df_tmp['CurrAlloc%'].head(n).sum() for n in top_n_values]
})

sum_df

   Top_N  Sum_Alloc%
0     10       19.74
1     25       44.80
2     50       76.79

In [25]:
# market-cap-wise allocation
df_tmp = df_portfolio_features[cols]
df_tmp.groupby(df_tmp['Conviction'].str[-2:])['CurrAlloc%'].sum().sort_values(ascending=False)

Conviction
SC    39.29
LC    37.83
MC    22.84
Name: CurrAlloc%, dtype: float64

In [26]:
# criteria-wise allocation
df_portfolio_features.groupby('Criteria')['CurrAlloc%'].sum().sort_values(ascending=False)

Criteria
X40      26.38
XY24     24.95
X40N     18.54
XR        9.07
XY25      7.18
OX40N     6.91
AR        6.07
SR        0.86
Name: CurrAlloc%, dtype: float64

In [27]:
# conviction-wise allocation
df_portfolio_features.groupby('Conviction')['CurrAlloc%'].sum().sort_values(ascending=False)

Conviction
X-LC    35.78
H-SC    19.26
X-MC    18.67
X-SC     9.95
M-SC     9.57
H-MC     2.62
H-LC     1.24
M-MC     1.19
M-LC     0.81
L-SC     0.51
L-MC     0.36
Name: CurrAlloc%, dtype: float64

In [28]:
# sector-wise stats
df_tmp = df_portfolio_features.groupby('Category')[['CurrAlloc%', 'Current', 'Current P/L', 'FTT Amt']].sum().sort_values(by=['Current', 'Current P/L'], ascending=False)
df_tmp['Current P/L%'] = round(df_tmp['Current P/L'] * 100 / df_tmp['Current'], 2)
df_tmp['FTT%'] = round(df_tmp['FTT Amt'] * 100 / df_tmp['Current'], 2)
cols = ['CurrAlloc%', 'Current P/L%', 'FTT%']
df_tmp[cols].sort_values(by=['CurrAlloc%'], ascending=False)

               CurrAlloc%  Current P/L%    FTT%
Category
FMCG                15.46        -20.88   64.42
IT                  11.26        -32.79   98.70
FINANCE              9.27        -15.63   64.23
AUTO                 8.36         -1.48   37.82
MISC                 6.87        -22.29   74.76
BANKS                6.05        -10.69   58.42
PHARMA               5.60          7.15   19.18
INSURANCE            5.50         -5.72   43.10
PAINTS               5.49        -12.55   31.74
ELECTRICAL           4.12         -7.68   45.38
HEALTHCARE           2.11         -6.09   33.77
AC                   1.79        -11.65   41.92
APPARELS             1.72          2.32   30.49
REFINERIES           1.70        -10.23   47.27
FOOTWEAR             1.66        -65.72  132.16
BREWERIES            1.65         10.97    7.52
DURABLES             1.49        -62.10  101.53
TRAVEL               1.48        -89.96  185.07
CERAMICS             1.34        -42.72   86.08
CABLES               1.24         25.42   55.05
ENGINEERING          1.20        -26.48   84.33
CHEMICALS            1.15        -44.00  160.89
CEMENT               1.02        -64.40  187.40
JEWELLERY            0.99       -104.04  174.93
ENTERTAINMENT        0.68        -78.36  184.73
TEXTILES             0.39        -49.46   92.08
HOTELS               0.37        -90.35  157.48

In [29]:
# money to be made criteria-wise
df_portfolio_features.groupby('Criteria')['FTT Amt'].agg(['sum', 'count']).sort_values(by='sum', ascending=False)

                sum  count
Criteria
XY24      3418131.0     20
X40       2016657.0     18
XR        1350587.0     13
X40N      1125893.0     12
AR        1064066.0      8
OX40N      690589.0     10
XY25       554220.0      5
SR         280028.0      2

In [30]:
# money to be made conviction-wise
df_portfolio_features.groupby('Conviction')['FTT Amt'].agg(['sum', 'count']).sort_values(by='sum', ascending=False)

                  sum  count
Conviction
H-SC        3282144.0     23
X-LC        2354953.0     20
X-MC        1473705.0     14
M-SC        1389138.0     14
X-SC        1214036.0      9
H-MC         279323.0      2
L-SC         209484.0      2
M-LC         162811.0      1
M-MC          55188.0      1
L-MC          44420.0      1
H-LC          34969.0      1

In [31]:
# money to be made criteria and conviction-wise
df_portfolio_features.groupby(['Conviction', 'Criteria'])['FTT Amt'].agg(['sum', 'count']).sort_values(by='sum', ascending=False)

                           sum  count
Conviction Criteria
X-LC       X40       1150575.0      9
H-SC       XY24       988759.0      5
           AR         916204.0      5
M-SC       XY24       839782.0      6
H-SC       XR         803555.0      7
X-SC       XY24       705159.0      4
X-MC       X40        651632.0      7
X-LC       X40N       486685.0      6
           XY24       419409.0      2
X-MC       X40N       344781.0      3
X-SC       X40N       294427.0      3
H-SC       OX40N      293598.0      4
M-SC       OX40N      281450.0      5
H-SC       SR         280028.0      2
X-MC       XY25       255069.0      2
X-LC       XY25       243963.0      2
H-MC       XY24       242799.0      1
X-MC       XY24       222223.0      2
X-SC       X40        214450.0      2
M-SC       XR         191537.0      2
M-LC       XR         162811.0      1
L-SC       OX40N      115541.0      1
           XR          93943.0      1
M-SC       AR          76369.0      1
M-MC       XY25        55188.0      1
X-LC       XR          54321.0      1
L-MC       XR          44420.0      1
H-MC       AR          36524.0      1
H-LC       AR          34969.0      1

In [32]:
# notebook execution time

end_time = time.time()
execution_time = round(end_time - start_time, 0)
print(f"Notebook execution time: {execution_time} seconds")

Notebook execution time: 24.0 seconds