<a href="https://colab.research.google.com/github/ankit-rathi/Quantvesting_v2/blob/main/myStocks_Portfolio_Analysis.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
'''
!pip install pandas==2.2.2 -qq
!pip install pyxirr -qq
!pip install ta -qq
!pip install yfinance==0.2.59 -qq
'''

'\n!pip install pandas==2.2.2 -qq\n!pip install pyxirr -qq\n!pip install ta -qq\n!pip install yfinance==0.2.59 -qq\n'

In [2]:
# import libraries

import numpy as np
import pandas as pd
import datetime
import warnings
warnings.filterwarnings('ignore')
import yfinance as yfin
import ta
import matplotlib.pyplot as plt
import requests

In [3]:
# notebook start time
import time
import datetime
import pytz

start_time = time.time()

# function to print date timestamp
def print_date_time():
  tz_NY = pytz.timezone('Asia/Kolkata')
  datetime_NY = datetime.datetime.now(tz_NY)
  print("Run date time (IST):", datetime_NY.strftime("%Y-%m-%d %H:%M:%S"))

In [4]:
# function to get booked and reserved amount
def get_amt():
  # fetch the JSON data from the URL
  url = "https://raw.githubusercontent.com/ankit-rathi/Tradevesting_v1/main/data/myPortfolioAmts.json"
  response = requests.get(url)
  pf_amts = response.json()  # parse the JSON data

  # extract values from the JSON
  py_booked_amt_dm = pf_amts["py_booked_amt_dm"]
  py_booked_amt_sv = pf_amts["py_booked_amt_sv"]
  cy_booked_amt_dm = pf_amts["cy_booked_amt_dm"]
  cy_booked_amt_sv = pf_amts["cy_booked_amt_sv"]
  reserve_amt_dm = pf_amts["reserve_amt_dm"]
  reserve_amt_sv = pf_amts["reserve_amt_sv"]

  # perform calculations
  py_booked_amt = py_booked_amt_dm + py_booked_amt_sv
  cy_booked_amt = cy_booked_amt_dm + cy_booked_amt_sv
  reserve_amt = reserve_amt_dm + reserve_amt_sv
  total_booked_amt = py_booked_amt + cy_booked_amt

  return total_booked_amt, reserve_amt, cy_booked_amt, py_booked_amt

gen_output = 0

In [5]:
# function to format the amount
def format_amt(number):
    abs_number = abs(number)

    if abs_number >= 1_00_00_000:  # Crores
        formatted_amt = f"{number / 1_00_00_000:.2f} C"
    elif abs_number >= 1_00_000:  # Lakhs
        formatted_amt = f"{number / 1_00_000:.2f} L"
    elif abs_number >= 1_000:  # Thousands
        formatted_amt = f"{number / 1_000:.2f} K"
    else:
        formatted_amt = f"{number:.2f}"

    return formatted_amt

# function to set start and end date
def get_start_end_date():
  start_date = (datetime.date.today() + datetime.timedelta(days=-365)).strftime('%Y-%m-%d')
  end_date = (datetime.date.today() + datetime.timedelta(days=1)).strftime('%Y-%m-%d')
  return start_date, end_date

# function to fetch my portfolio csv
def get_mypfs_df():
  mypfs_df = pd.read_csv('https://raw.githubusercontent.com/ankit-rathi/Tradevesting_v1/main/data/myPortfolioStocks.csv')
  return mypfs_df

# function to fetch my prospects csv
def get_mypps_df():
  mypps_df = pd.read_csv('https://raw.githubusercontent.com/ankit-rathi/Tradevesting_v1/main/data/myProspectsScrips.csv')
  return mypps_df

# function to fetch screener data
def get_myscreen_df():
  myscreen_df = pd.read_csv('https://raw.githubusercontent.com/ankit-rathi/Tradevesting_v1/main/data/myScreenerDB.csv')
  return myscreen_df

# function to fetch momentum data
def get_myinvmt_df():
  myinvmt_df = pd.read_csv('https://raw.githubusercontent.com/ankit-rathi/Tradevesting_v1/main/data/myInvestments.csv')
  return myinvmt_df

# function to get the stock ids
def get_stock_ids(df_pf):
  stock_n100 = df_pf['Symbol'].unique()

  exclude = ['CADILAHC','MMTC', 'MASFIN']

  stock_ids = df_pf[~df_pf['Symbol'].isin(exclude) ]['Symbol'].unique()

  #mypf = mypf[mypf.Forecast.notnull()]
  #stock_ids = mypf['Symbol'].unique()

  #stock_ids.sort()
  return stock_ids

# get features from screener data
def get_screener_features():
  myscreen_df = get_myscreen_df()
  cols = ['Symbol', 'EPS', 'MedPE', 'ROCE%', 'ROE%', 'CapType']
  return myscreen_df[cols]

# get relative strength
def get_relative_strength(stock_list):

    # Dictionary to store stock tickers and their corresponding percentage price change
    stock_changes = {}

    # Loop through each stock and fetch its price data
    for stock in stock_list:
        try:
            # Download the stock data for the given date range
            stock_data = yfin.Ticker(stock + '.NS').history(period='1mo', interval='1d')[map(str.title, ['open', 'close', 'low', 'high', 'volume'])]

            # Calculate the percentage change for the stock
            if len(stock_data) > 0:
                start_price = stock_data['Close'].iloc[0]
                end_price = stock_data['Close'].iloc[-1]
                percent_change = round(((end_price - start_price) / start_price) * 100, 2)
                stock_changes[stock] = percent_change
            else:
                stock_changes[stock] = np.nan  # If no data is available, set to NaN

        except Exception as e:
            print(f"Error fetching data for {stock}: {e}")
            stock_changes[stock] = np.nan

    # Create a DataFrame with stock tickers and their percentage changes
    df = pd.DataFrame(list(stock_changes.items()), columns=['Symbol', 'Percent_Change'])

    # Drop any stocks with missing data (NaN values)
    df = df.dropna()

    # Calculate the percentile rank based on percentage change
    df['RSP'] = round(df['Percent_Change'].rank(pct=True) * 100, 2)
    cols = ['Symbol', 'RSP']
    df = df[cols]
    # Sort by percentile rank (optional)
    df = df.sort_values(by='RSP', ascending=False).reset_index(drop=True)

    return df

In [6]:
# function to get stock technicals
def stock_prec_dev(stock_symbol):
    #stock_symbol = 'ULTRACEMCO.NS'
    short_window = 20
    mid_window = 50
    long_window = 200
    moving_avg = 'SMA'

    start = datetime.datetime(*map(int, start_date.split('-')))
    end = datetime.datetime(*map(int, end_date.split('-')))

    stock_df = yfin.Ticker(stock_symbol + '.NS').history(period='max', interval='1d')[map(str.title, ['open', 'close', 'low', 'high', 'volume'])]

    stock_df['Max'] = round(max(stock_df['Close']),2)
    stock_df = stock_df[(stock_df.index <= end_date) & (stock_df.index >= start_date)]
    stock_df['200_SMA'] = round(stock_df['Close'].rolling(window = 200, min_periods = 1).mean(),0)
    stock_df['Dev%_200'] = round((stock_df['Close'] - stock_df['200_SMA'])*100/stock_df['200_SMA'],2)
    stock_df.dropna(axis = 0, inplace = True) # remove any null rows

    stock_df['20_SMA'] = stock_df['Close'].rolling(window=20).mean()
    stock_df['50_SMA'] = stock_df['Close'].rolling(window=50).mean()
    stock_df['Symbol'] = stock_symbol

    stock_df['Close'] = round(stock_df['Close'],2)
    stock_df['Min'] = round(min(stock_df['Close']),2)
    stock_df['RSI_14'] = ta.momentum.RSIIndicator(close=stock_df['Close'], window=14).rsi()
    stock_df['RSI_14'] = round(stock_df['RSI_14'],0)
    stock_df['Prev_Close'] = stock_df['Close'].shift(1)
    stock_df.drop(['Open', 'Low', 'High', 'Volume'], axis=1, inplace=True)
    stock_df = stock_df.tail(1)

    max_SMA = max(stock_df['20_SMA'].item(), stock_df['50_SMA'].item(), stock_df['200_SMA'].item())
    min_SMA = min(stock_df['20_SMA'].item(), stock_df['50_SMA'].item(), stock_df['200_SMA'].item())
    ABS_Spread = max_SMA - min_SMA
    stock_df['Spread%'] = round((ABS_Spread / stock_df['200_SMA'].item()) * 100,2)

    return stock_df

# function to compute stock attributes
def get_common_features(stock_ids, df_mypf):

  df_prec_dev = pd.DataFrame()
  df_tmp = get_screener_features()
  df_rs = get_relative_strength(stock_ids)

  for stock_id in stock_ids:
      tmp = stock_prec_dev(stock_id)
      tmp = tmp.reset_index()
      df_prec_dev = pd.concat([df_prec_dev, tmp], ignore_index = True)
  df_prec_dev = pd.merge(df_prec_dev, df_mypf, on= 'Symbol')
  df_prec_dev = pd.merge(df_prec_dev, df_tmp, on= 'Symbol', how='left')
  df_prec_dev = pd.merge(df_prec_dev, df_rs, on= 'Symbol', how='left')
  #print(df_prec_dev.columns)
  df_prec_dev['Curr_PE'] = round(df_prec_dev['Close']/df_prec_dev['EPS'],1)
  df_prec_dev['Dev%_PE'] = round((df_prec_dev['Curr_PE'] - df_prec_dev['MedPE'])*100/df_prec_dev['MedPE'],2)
  df_prec_dev['Conviction'] = df_prec_dev['Conviction'] + '-' + df_prec_dev['CapType']
  return df_prec_dev

# function to arrange stock features
def arrange_features(df_stocks, common_cols, diff_cols):
  df_stocks_common = df_stocks[common_cols].drop_duplicates()
  df_stocks_diff = df_stocks[diff_cols]
  df_stocks_diff['Investment'] = df_stocks_diff['AvgCost'] * df_stocks_diff['Shares']
  df_stocks_diff = df_stocks_diff.groupby(['Symbol'])[['Shares', 'Investment']].aggregate(['sum']).reset_index()
  df_stocks_diff.columns = ['Symbol', 'Shares', 'Investment']
  df_stocks_diff['AvgCost'] = round(df_stocks_diff['Investment']/df_stocks_diff['Shares'],2)
  df_stocks = pd.merge(df_stocks_diff, df_stocks_common, on='Symbol')
  return df_stocks

# plot fact distribution across dimension
def plot_pie_chart(df, dimension, fact):
  # grouping the data by category and calculating the sum of fact for each type
  grouped_data = df.groupby(dimension)[fact].sum()

  # sorting the grouped data in descending order
  grouped_data = grouped_data.sort_values(ascending=False)

  # creating a pie chart
  grouped_data.plot.pie(autopct='%1.1f%%', startangle=90, figsize=(6, 6))

  # adding a title and displaying the plot
  plt.title(f'{dimension} {fact} Distribution')
  plt.ylabel('')  # To hide the y-label
  plt.show()

In [7]:
# function to get portfolio features

def get_portfolio_features(df_common_features):

  print_date_time()
  print('-------------------')

  #df_common_features["Target"] = df_common_features["Target"].fillna(df_common_features["Max"])
  df_common_features['NTT'] = np.where(df_common_features['Strategy']== 'NTT', df_common_features["Target"], df_common_features['Max'])
  df_common_features['LTT'] = np.where(df_common_features['Strategy']== 'BTT', df_common_features["Target"], df_common_features['Max'])
  df_common_features['BOL'] = df_common_features['Min']

  tmp_df = df_common_features[df_common_features['Symbol'].isin(mypf_df[mypf_df['InPortfolio'] != 'NA'].Symbol.values)]
  print('qualified stocks: '+str(len(tmp_df['Symbol'].unique())))
  tmp_df1 = tmp_df[tmp_df['LatestQtr'] == 1]
  print('with latest results: '+str(len(tmp_df1['Symbol'].unique())))
  tmp_df1 = tmp_df1[tmp_df1['StarStock'] == 1]
  print('still star stocks: '+str(len(tmp_df1['Symbol'].unique())))
  tmp_df['Investment'] = tmp_df['AvgCost'] * tmp_df['Shares']
  tmp_df['Current'] = round(tmp_df['Close'] * tmp_df['Shares'],0)
  tmp_df['Previous'] = tmp_df['Prev_Close'] * tmp_df['Shares']
  tmp_df['EstimatedST'] = tmp_df['NTT'] * tmp_df['Shares']
  tmp_df['EstimatedLT'] = tmp_df['LTT'] * tmp_df['Shares']
  tmp_df['Current P/L'] = round((tmp_df['Current'] - tmp_df['Investment']),0)
  tmp_df['Today P/L%'] = round((tmp_df['Current'] - tmp_df['Previous'])*100/tmp_df['Previous'],2)
  tmp_df['Current P/L%'] = round((tmp_df['Current'] - tmp_df['Investment'])*100/tmp_df['Investment'],2)
  tmp_df['EstimatedST P/L%'] = round((tmp_df['EstimatedST'] - tmp_df['Investment'])*100/tmp_df['Investment'],2)
  tmp_df['EstimatedLT P/L%'] = round((tmp_df['EstimatedLT'] - tmp_df['Investment'])*100/tmp_df['Investment'],2)
  tmp_df['NTT%'] = round((tmp_df['NTT'] - tmp_df['Close'])*100/tmp_df['Close'],2)
  tmp_df['LTT%'] = round((tmp_df['LTT'] - tmp_df['Close'])*100/tmp_df['Close'],2)
  tmp_df['Gained%'] = round((tmp_df['Close'] - tmp_df['BOL'])*100/tmp_df['BOL'],2)
  investment = round(sum(tmp_df['AvgCost']*tmp_df['Shares']),0)
  current = round(sum(tmp_df['Close']*tmp_df['Shares']),0)
  tmp_df['InitAlloc%'] = round(tmp_df['Investment']*100/investment,2)
  tmp_df['CurrAlloc%'] = round(tmp_df['Current']*100/current,2)
  tmp_df['FTT'] = tmp_df['LTT']
  tmp_df.loc[tmp_df['Strategy'] == 'NTT', 'FTT'] = tmp_df['NTT']
  tmp_df['FTT%'] = tmp_df['LTT%']
  tmp_df.loc[tmp_df['Strategy'] == 'NTT', 'FTT%'] = tmp_df['NTT%']
  tmp_df['FTT Amt'] = round(tmp_df['FTT%'] * tmp_df['Current']/100,0)
  tmp_df['OTT%'] = round((tmp_df['FTT'] - tmp_df['AvgCost'])*100/tmp_df['AvgCost'],2)
  tmp_df['RRR Ind'] = round(tmp_df['Current P/L']/tmp_df['FTT Amt'],2)
  tmp_df['Risk Ind'] = round(tmp_df['Current P/L%']*tmp_df['CurrAlloc%'],0)

  return tmp_df

# function to print portfolio features
def print_portfolio_stats(df_portfolio_features, myinvmt_df):
  from pyxirr import xirr

  total_booked_amt, reserve_amt, cy_booked_amt, py_booked_amt = get_amt()

  dates = myinvmt_df['Date'].values
  dates = np.append(dates, datetime.date.today().strftime('%d-%b-%y'))
  investment = myinvmt_df['Investment'].values
  dates= pd.to_datetime(dates)

  current = round(sum(df_portfolio_features['Close']*df_portfolio_features['Shares']),0) + reserve_amt
  investment_xirr = np.append(investment, current)
  cagr = round(xirr(pd.DataFrame({"dates": dates, "amounts": investment_xirr}))*100,2)

  investment = -sum(investment)
  invested = round(sum(df_portfolio_features['AvgCost']*df_portfolio_features['Shares']),0) + reserve_amt
  previous = round(sum(df_portfolio_features['Prev_Close']*df_portfolio_features['Shares']),0) + reserve_amt
  cy_invested = investment + py_booked_amt

  today_pnl_amount = current-previous
  today_pnl_percentage = round((current-previous)*100/previous,2)

  curr_pnl_amount = current-invested
  curr_pnl_percentage = round((curr_pnl_amount)*100/(cy_invested),2)

  cy_pnl_amount = cy_booked_amt + curr_pnl_amount
  cy_pnl_percentage = round((cy_pnl_amount)*100/cy_invested,2)

  overall_pnl_amount = total_booked_amt + curr_pnl_amount
  overall_pnl_percentage = round((overall_pnl_amount)*100/investment,2)

  estimate_st = round(sum(df_portfolio_features['FTT']*df_portfolio_features['Shares']),0)  + reserve_amt
  est_st_pnl_amount = estimate_st-current
  est_st_pnl_percentage = round((est_st_pnl_amount)*100/current,2)

  estimate_lt = round(sum(df_portfolio_features['LTT']*df_portfolio_features['Shares']),0)  + reserve_amt
  est_lt_pnl_amount = estimate_lt-current
  est_lt_pnl_percentage = round((est_lt_pnl_amount)*100/current,2)

  total_profit = round(sum(df_portfolio_features[df_portfolio_features['Current P/L%'] > 0]['Current']) - sum(df_portfolio_features[df_portfolio_features['Current P/L%'] > 0]['Investment']),0)
  total_loss = round(sum(df_portfolio_features[df_portfolio_features['Current P/L%'] < 0]['Current']) - sum(df_portfolio_features[df_portfolio_features['Current P/L%'] < 0]['Investment']),0)

  cy_booked_percentage = round((cy_booked_amt)*100/current,2)
  py_booked_percentage = round((py_booked_amt)*100/investment,2)
  total_booked_percentage = round((total_booked_amt)*100/investment,2)

  print('-------------------')
  print('Initial Investment: ', format_amt(investment))
  print('CY Investment: ', format_amt(cy_invested))
  print('Reserve: ', format_amt(reserve_amt))
  print('Current: ',  format_amt(current))
  print('-------------------')
  print('Today PnL: '+ '{} ({}%)'.format(format_amt(today_pnl_amount), today_pnl_percentage))
  print('Current PnL: '+ '{} ({}%)'.format(format_amt(curr_pnl_amount), curr_pnl_percentage))
  print('CY Booked + Current PnL: '+ '{} ({}%)'.format(format_amt(cy_pnl_amount), cy_pnl_percentage))
  print('-------------------')
  print('Total profit: ', format_amt(total_profit))
  print('Total loss: ', format_amt(total_loss))
  print('-------------------')
  print('Total Booked + Current PnL: '+ '{} ({}%)'.format(format_amt(overall_pnl_amount), overall_pnl_percentage))
  print('Total Booked PnL: '+ '{} ({}%)'.format(format_amt(total_booked_amt), total_booked_percentage))
  print('Curr Year Booked PnL: '+ '{} ({}%)'.format(format_amt(cy_booked_amt), cy_booked_percentage))
  print('Prev Year Booked PnL: '+ '{} ({}%)'.format(format_amt(py_booked_amt), py_booked_percentage))
  print('===================')
  print('Est FTT: ',  format_amt(estimate_st))
  print('Est FTT PnL: '+ '{} ({}%)'.format(format_amt(est_st_pnl_amount), est_st_pnl_percentage))

  print('===================')
  print('Deployed: ', format_amt(investment))

  print('Current: ', format_amt(current))

  print('CAGR/XIRR %: '+'{}%'.format(cagr))

In [8]:
# get start and end date
start_date, end_date = get_start_end_date()

# get portfolio and prospects data
mypfs_df = get_mypfs_df()
mypps_df = get_mypps_df()
myinvmt_df = get_myinvmt_df()

# merge above datasets
mypf_df = pd.merge(mypfs_df, mypps_df, on="Symbol")

# seggregate dm and sv portfolio
dm_pf = mypf_df[mypf_df['InPortfolio'] == 'DM']
sv_pf = mypf_df[mypf_df['InPortfolio'] == 'SV']

# build portfolio stock dataframe
dm_stocks = get_stock_ids(dm_pf)
sv_stocks = get_stock_ids(sv_pf)
df_stocks = pd.concat([dm_pf,sv_pf], ignore_index = True)

# arrange common and diff stock features
common_cols = ['Symbol', 'Target', 'Criteria', 'Strategy', 'CumlRnk', 'LatestQtr', 'StarStock', 'Conviction', 'Category', 'InFolio', 'XIRR', 'MBQ']
diff_cols = ['Symbol', 'AvgCost', 'Shares']
df_stocks = arrange_features(df_stocks, common_cols, diff_cols)

# get common features
stock_ids = df_stocks['Symbol'].values
df_common_features = get_common_features(stock_ids, df_stocks)

df_common_features.reset_index(drop=True, inplace=True)
df_common_features.drop(['Date'], axis=1, inplace=True)
# get and print portfolio features
df_portfolio_features = get_portfolio_features(df_common_features)

print_portfolio_stats(df_portfolio_features, myinvmt_df)

df = df_portfolio_features
#plot_pie_chart(df, 'CapType', 'Current')
list_ox40n = list(df[df['MBQ'].str.contains('OX40N', na=False)]['Symbol'].values)

Run date time (IST): 2026-04-02 14:05:10
-------------------
qualified stocks: 86
with latest results: 26
still star stocks: 16
-------------------
Initial Investment:  1.36 C
CY Investment:  1.62 C
Reserve:  1.61 K
Current:  1.29 C
-------------------
Today PnL: -13.81 K (-0.11%)
Current PnL: -48.39 L (-29.78%)
CY Booked + Current PnL: -32.50 L (-20.0%)
-------------------
Total profit:  46.00 K
Total loss:  -48.85 L
-------------------
Total Booked + Current PnL: -5.52 L (-4.07%)
Total Booked PnL: 42.87 L (31.64%)
Curr Year Booked PnL: 15.89 L (12.34%)
Prev Year Booked PnL: 26.98 L (19.91%)
===================
Est FTT:  2.48 C
Est FTT PnL: 1.19 C (92.55%)
===================
Deployed:  1.36 C
Current:  1.29 C
CAGR/XIRR %: -2.48%

In [9]:
# top 5 near their targets
cols = ['Symbol', 'Today P/L%', 'Current P/L%', 'FTT%', 'OTT%', 'FTT Amt', 'Current P/L', 'Current', 'FTT', 'Dev%_PE', 'RSI_14','Conviction', 'Spread%',  'CumlRnk', 'RRR Ind', 'CurrAlloc%', 'Gained%', 'Criteria', 'Strategy', 'Category']
df_tmp = df_portfolio_features[~df_portfolio_features['Symbol'].isin(['ENRIN','BLUSPRING','DIGITIDE'])]
df_tmp = df_tmp.sort_values(by = 'FTT Amt', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
50,MASFIN,1.01,-9.31,34.04,21.57,30248.0,-9120.0,88860.0,397.04,-21.86,46.0,H-SC,4.88,167.0,-0.30,0.69,21.20,XR,ATH,FINANCE
77,TTKPRESTIG,-1.07,-42.75,74.82,0.09,43170.0,-43078.0,57699.0,770.00,33.83,37.0,M-SC,22.16,250.0,-1.00,0.45,2.74,OX40N,NTT,DURABLES
2,ABBOTINDIA,-0.66,-11.72,33.75,18.07,53288.0,-20965.0,157890.0,35195.00,-24.86,47.0,X-MC,10.43,58.0,-0.39,1.23,3.26,X40,ATH,PHARMA
67,SONACOMS,-0.28,-14.22,62.15,39.09,53930.0,-14385.0,86774.0,804.02,-32.08,47.0,M-MC,6.74,193.0,-0.27,0.67,22.76,AR,ATH,AUTO
42,INDUSINDBK,-1.67,-42.97,133.01,32.89,58567.0,-33174.0,44032.0,1800.00,-307.28,37.0,L-MC,6.68,258.0,-0.57,0.34,14.29,XR,NTT,BANKS

In [10]:
# top 5 today
df_tmp = df_portfolio_features.sort_values(by = 'Today P/L%', ascending=False)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
0,5PAISA,5.07,-45.94,108.86,12.90,128576.0,-100385.0,118111.0,593.00,74.28,45.0,H-SC,16.51,170.0,-0.78,0.92,13.98,OX40N,NTT,FINANCE
55,RAJESHEXPO,4.99,-83.11,492.61,0.07,114108.0,-114013.0,23164.0,518.00,748.48,27.0,L-SC,42.39,268.0,-1.00,0.18,8.75,OX40N,NTT,JEWELLERY
15,BSOFT,4.38,-33.84,127.89,50.79,119017.0,-47591.0,93062.0,831.70,-14.96,49.0,H-SC,8.40,172.0,-0.40,0.72,9.74,XR,ATH,IT
52,PAGEIND,3.54,-11.91,52.24,34.11,123508.0,-31954.0,236425.0,51418.64,-36.82,61.0,X-MC,20.33,55.0,-0.26,1.84,11.84,X40,ATH,APPARELS
12,BATAINDIA,3.16,-58.21,223.51,35.20,120195.0,-74894.0,53776.0,2096.00,-29.53,37.0,X-SC,34.04,91.0,-0.62,0.42,6.65,X40,NTT,FOOTWEAR

In [11]:
# bottom 5 today
df_tmp = df_portfolio_features.sort_values(by = 'Today P/L%', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
19,COFFEEDAY,-3.52,-61.11,247.83,35.27,109442.0,-69389.0,44160.0,80.00,-69.82,38.0,L-SC,31.37,266.0,-0.63,0.34,8.90,XR,NTT,HOTELS
23,DIXON,-3.45,-27.88,91.23,37.92,171604.0,-72698.0,188100.0,18931.72,-69.35,44.0,X-MC,27.83,54.0,-0.42,1.46,2.35,X40N,ATH,IT
47,JSWINFRA,-3.41,-18.47,42.80,16.43,77392.0,-40952.0,180822.0,342.00,-30.19,41.0,X-MC,11.93,61.0,-0.53,1.40,0.00,X40N,NTT,REALTY
6,ASIANPAINT,-3.20,-22.47,60.61,24.52,133196.0,-63680.0,219759.0,3460.25,-21.86,40.0,X-LC,11.60,30.0,-0.48,1.71,1.57,X40,ATH,PAINTS
38,ICICIPRULI,-2.77,-17.40,58.27,30.73,94819.0,-34282.0,162723.0,790.00,-39.60,19.0,X-MC,8.75,78.0,-0.36,1.26,0.00,X40,ATH,INSURANCE

In [12]:
# top 5 to exit based on CumlRnk
df_tmp = df_portfolio_features[~df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])]
df_tmp = df_tmp[(df_tmp['Current P/L%'] > -1) & (df_tmp['Current P/L%'] < 1)].sort_values(by = 'CumlRnk', ascending=False)
df_tmp[cols].head()

Empty DataFrame
Columns: [Symbol, Today P/L%, Current P/L%, FTT%, OTT%, FTT Amt, Current P/L, Current, FTT, Dev%_PE, RSI_14, Conviction, Spread%, CumlRnk, RRR Ind, CurrAlloc%, Gained%, Criteria, Strategy, Category]
Index: []

In [13]:
# OX40N stocks to exit
df_tmp = df_portfolio_features[(df_portfolio_features['Symbol'].isin(list_ox40n))].sort_values(by = 'Current P/L%', ascending=False)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
26,FINCABLES,0.68,1.85,104.13,107.91,156587.0,2732.0,150376.0,1641.55,-8.17,45.0,M-SC,5.67,220.0,0.02,1.17,13.13,OX40N,ATH,CABLES
66,SIS,0.21,-33.86,83.33,21.26,61198.0,-37592.0,73440.0,528.00,1719.69,48.0,H-SC,14.72,168.0,-0.61,0.57,9.19,OX40N,NTT,MISC
18,CERA,-0.44,-39.24,103.89,23.89,111039.0,-69022.0,106881.0,9475.00,-41.29,45.0,H-SC,19.32,153.0,-0.62,0.83,2.71,OX40N,NTT,CERAMICS
72,TATAELXSI,2.06,-39.30,117.50,32.03,94033.0,-51807.0,80028.0,9161.00,-24.06,44.0,H-SC,21.79,158.0,-0.55,0.62,5.92,OX40N,NTT,IT
48,KANSAINER,1.07,-40.78,91.61,13.47,146298.0,-109971.0,159696.0,340.00,-49.13,45.0,H-SC,23.12,162.0,-0.75,1.24,11.55,XY24,NTT,PAINTS

In [14]:
# top 5 to book for rotation
df_tmp = df_portfolio_features[(df_portfolio_features['Current P/L%'] > 20) ].sort_values(by = 'CumlRnk', ascending=False)
df_tmp[cols].head()

Empty DataFrame
Columns: [Symbol, Today P/L%, Current P/L%, FTT%, OTT%, FTT Amt, Current P/L, Current, FTT, Dev%_PE, RSI_14, Conviction, Spread%, CumlRnk, RRR Ind, CurrAlloc%, Gained%, Criteria, Strategy, Category]
Index: []

In [15]:
# top 5 to monitor for exit
df_tmp = df_portfolio_features[~df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])]
df_tmp = df_tmp[(df_tmp['Current P/L%'] > 0) ].sort_values(by = 'Dev%_PE', ascending=False)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
26,FINCABLES,0.68,1.85,104.13,107.91,156587.0,2732.0,150376.0,1641.55,-8.17,45.0,M-SC,5.67,220.0,0.02,1.17,13.13,OX40N,ATH,CABLES
1,ABB,0.92,12.26,29.67,45.57,87137.0,32069.0,293688.0,7934.00,-27.86,52.0,H-MC,13.32,125.0,0.37,2.28,30.42,AR,NTT,ELECTRICAL

In [16]:
# top 5 to book for rotation from weak conviction
df_tmp = df_portfolio_features[~df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])]
df_tmp = df_tmp[~df_tmp['Criteria'].isin(['XY25','XY24','X40', 'X40N'])].sort_values(by = 'RRR Ind', ascending=False)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
1,ABB,0.92,12.26,29.67,45.57,87137.0,32069.0,293688.0,7934.00,-27.86,52.0,H-MC,13.32,125.0,0.37,2.28,30.42,AR,NTT,ELECTRICAL
26,FINCABLES,0.68,1.85,104.13,107.91,156587.0,2732.0,150376.0,1641.55,-8.17,45.0,M-SC,5.67,220.0,0.02,1.17,13.13,OX40N,ATH,CABLES
40,INDIAMART,-0.98,-13.24,138.28,106.72,147962.0,-16334.0,107002.0,4810.62,-60.94,43.0,H-SC,12.94,140.0,-0.11,0.83,7.04,AR,ATH,MISC
85,ZYDUSLIFE,-0.43,-9.36,49.64,35.63,94291.0,-19624.0,189950.0,1286.17,-21.17,40.0,H-MC,5.67,120.0,-0.21,1.48,5.75,AR,ATH,PHARMA
84,WIPRO,1.57,-20.36,116.29,72.27,156939.0,-34493.0,134955.0,420.00,-28.30,44.0,M-LC,18.17,98.0,-0.22,1.05,3.54,XR,NTT,IT

In [17]:
# top 5 to accumulate based on lowest RSI_14
df_tmp = df_portfolio_features[df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])].sort_values(by = 'RSI_14', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
38,ICICIPRULI,-2.77,-17.40,58.27,30.73,94819.0,-34282.0,162723.0,790.00,-39.60,19.0,X-MC,8.75,78.0,-0.36,1.26,0.00,X40,ATH,INSURANCE
37,ICICIGI,-1.75,-11.79,35.29,19.34,62295.0,-23587.0,176522.0,2252.93,-25.72,26.0,X-MC,6.03,66.0,-0.38,1.37,0.00,X40,ATH,INSURANCE
21,DABUR,-0.75,-19.48,78.46,43.70,156721.0,-48321.0,199747.0,735.00,-26.86,28.0,X-MC,10.99,70.0,-0.31,1.55,0.34,XY24,BTT,FMCG
32,HAVELLS,-1.26,-25.03,76.16,32.08,187285.0,-82081.0,245910.0,2062.85,-29.51,29.0,X-MC,11.33,63.0,-0.44,1.91,0.00,X40,ATH,ELECTRICAL
34,HDFCBANK,0.01,-11.19,44.54,28.37,92910.0,-26285.0,208600.0,1073.00,-24.48,30.0,X-LC,15.54,26.0,-0.28,1.62,1.48,X40,BTT,BANKS

In [18]:
# top 5 to accumulate based on Spread and CumlRnk
df_tmp = df_portfolio_features[df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])]
df_tmp = df_tmp[(df_tmp['CumlRnk'] < 100)].sort_values(by = 'Spread%', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
65,SIEMENS,-0.39,-19.25,55.44,25.51,83307.0,-35830.0,150265.0,4671.50,26.28,43.0,H-LC,0.37,51.0,-0.43,1.17,10.66,AR,ATH,ELECTRICAL
82,VOLTAS,-1.62,-3.82,50.97,45.20,93994.0,-7332.0,184410.0,1856.00,10.16,33.0,X-MC,3.01,79.0,-0.08,1.43,2.71,XY25,NTT,AC
78,UNITDSPR,-2.33,-10.37,34.73,20.77,72889.0,-24270.0,209874.0,1644.00,-20.49,37.0,X-MC,3.74,64.0,-0.33,1.63,0.11,X40N,NTT,BREWERIES
59,RELIANCE,-1.58,-13.50,44.86,25.30,77979.0,-27135.0,173828.0,1952.00,-15.80,40.0,X-LC,3.89,21.0,-0.35,1.35,16.06,XY25,BTT,REFINERIES
37,ICICIGI,-1.75,-11.79,35.29,19.34,62295.0,-23587.0,176522.0,2252.93,-25.72,26.0,X-MC,6.03,66.0,-0.38,1.37,0.00,X40,ATH,INSURANCE

In [19]:
# top 5 to accumulate based on lowest Gained%
df_tmp = df_portfolio_features[df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])].sort_values(by = 'Gained%', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
47,JSWINFRA,-3.41,-18.47,42.80,16.43,77392.0,-40952.0,180822.0,342.00,-30.19,41.0,X-MC,11.93,61.0,-0.53,1.40,0.00,X40N,NTT,REALTY
38,ICICIPRULI,-2.77,-17.40,58.27,30.73,94819.0,-34282.0,162723.0,790.00,-39.60,19.0,X-MC,8.75,78.0,-0.36,1.26,0.00,X40,ATH,INSURANCE
37,ICICIGI,-1.75,-11.79,35.29,19.34,62295.0,-23587.0,176522.0,2252.93,-25.72,26.0,X-MC,6.03,66.0,-0.38,1.37,0.00,X40,ATH,INSURANCE
32,HAVELLS,-1.26,-25.03,76.16,32.08,187285.0,-82081.0,245910.0,2062.85,-29.51,29.0,X-MC,11.33,63.0,-0.44,1.91,0.00,X40,ATH,ELECTRICAL
78,UNITDSPR,-2.33,-10.37,34.73,20.77,72889.0,-24270.0,209874.0,1644.00,-20.49,37.0,X-MC,3.74,64.0,-0.33,1.63,0.11,X40N,NTT,BREWERIES

In [20]:
# top 5 to accumulate based on lowest CurrAlloc%
df_tmp = df_portfolio_features[df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])].sort_values(by = 'CurrAlloc%', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
58,RELAXO,2.07,-65.57,342.40,52.31,171111.0,-95186.0,49974.0,1176.00,-63.31,37.0,X-SC,31.41,92.0,-0.56,0.39,11.74,X40N,NTT,FOOTWEAR
12,BATAINDIA,3.16,-58.21,223.51,35.20,120195.0,-74894.0,53776.0,2096.00,-29.53,37.0,X-SC,34.04,91.0,-0.62,0.42,6.65,X40,NTT,FOOTWEAR
54,QUESS,0.61,-27.25,139.05,73.90,108025.0,-29105.0,77688.0,424.00,-60.88,43.0,X-SC,22.35,80.0,-0.27,0.60,4.51,XY24,NTT,MISC
36,HONAUT,-1.98,-30.64,118.16,51.31,158039.0,-59088.0,133750.0,58357.33,-42.35,32.0,X-SC,17.98,90.0,-0.37,1.04,1.61,X40N,ATH,ELECTRICAL
51,MEDANTA,0.06,-15.33,50.14,27.12,74935.0,-27065.0,149452.0,1486.00,-17.88,37.0,X-SC,15.14,87.0,-0.36,1.16,2.98,XY24,NTT,HEALTHCARE

In [21]:
# top 5 to accumulate based on CumlRnk
df_tmp = df_portfolio_features.sort_values(by = 'CumlRnk', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
45,ITC,0.21,-23.01,54.64,19.06,143103.0,-78265.0,261901.0,452.00,-57.95,37.0,X-LC,19.71,1.0,-0.55,2.03,1.60,X40,NTT,FMCG
73,TCS,1.57,-28.19,76.27,26.57,253717.0,-130617.0,332656.0,4311.59,-39.36,42.0,X-LC,18.58,2.0,-0.51,2.58,3.82,X40,ATH,IT
43,INFY,0.72,-12.53,53.47,34.24,146339.0,-39204.0,273684.0,1972.00,-31.06,46.0,X-LC,15.02,3.0,-0.27,2.13,5.25,X40,NTT,IT
75,TMPV,-0.38,-31.30,98.81,36.58,241549.0,-111383.0,244458.0,600.00,-85.81,36.0,X-LC,11.21,4.0,-0.46,1.90,1.89,XY24,NTT,AUTO
33,HCLTECH,3.05,-9.42,36.72,23.83,80463.0,-22799.0,219125.0,1908.19,-4.88,51.0,X-LC,11.48,8.0,-0.28,1.70,6.40,X40,ATH,IT

In [22]:
# top 5 for average up
df_tmp = df_portfolio_features[(df_portfolio_features['Dev%_200'] > 5)].sort_values(by = 'CurrAlloc%', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
24,DMART,1.77,4.49,24.04,29.60,62697.0,11202.0,260802.0,5391.45,-11.93,73.0,X-LC,6.33,14.0,0.18,2.03,19.21,X40N,ATH,FMCG
1,ABB,0.92,12.26,29.67,45.57,87137.0,32069.0,293688.0,7934.00,-27.86,52.0,H-MC,13.32,125.0,0.37,2.28,30.42,AR,NTT,ELECTRICAL

In [23]:
# top 5 RSP
df_tmp = df_portfolio_features.sort_values(by = 'RSP', ascending=False)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
24,DMART,1.77,4.49,24.04,29.60,62697.0,11202.0,260802.0,5391.45,-11.93,73.0,X-LC,6.33,14.0,0.18,2.03,19.21,X40N,ATH,FMCG
30,HAPPSTMNDS,0.48,-50.73,275.20,84.85,173772.0,-65021.0,63144.0,1480.71,-41.42,53.0,H-SC,24.34,152.0,-0.37,0.49,16.93,AR,ATH,IT
52,PAGEIND,3.54,-11.91,52.24,34.11,123508.0,-31954.0,236425.0,51418.64,-36.82,61.0,X-MC,20.33,55.0,-0.26,1.84,11.84,X40,ATH,APPARELS
5,ANGELONE,-0.04,-1.43,25.99,24.18,78132.0,-4375.0,300625.0,303.00,-85.87,55.0,X-SC,9.60,97.0,-0.06,2.34,15.71,X40N,NTT,FINANCE
80,VALIANTORG,-0.07,-52.08,263.43,74.15,206521.0,-85208.0,78397.0,838.00,-240.99,50.0,H-SC,27.65,145.0,-0.41,0.61,16.67,XR,NTT,CHEMICALS

In [24]:
# Top N allocation
df_tmp = df_portfolio_features.sort_values(by = 'CurrAlloc%', ascending=False)
top_n_values = [10, 25, 50]

sum_df = pd.DataFrame({
    'Top_N': top_n_values,
    'Sum_Alloc%': [df_tmp['CurrAlloc%'].head(n).sum() for n in top_n_values]
})

sum_df

   Top_N  Sum_Alloc%
0     10       21.18
1     25       46.25
2     50       78.08

In [25]:
# market-cap-wise allocation
df_tmp = df_portfolio_features[cols]
df_tmp.groupby(df_tmp['Conviction'].str[-2:])['CurrAlloc%'].sum().sort_values(ascending=False)

Conviction
SC    44.60
MC    29.58
LC    25.80
Name: CurrAlloc%, dtype: float64

In [26]:
# criteria-wise allocation
df_portfolio_features.groupby('Criteria')['CurrAlloc%'].sum().sort_values(ascending=False)

Criteria
XY24     27.03
X40      25.36
X40N     15.43
AR        9.18
XR        8.31
XY25      7.17
OX40N     6.70
SR        0.80
Name: CurrAlloc%, dtype: float64

In [27]:
# conviction-wise allocation
df_portfolio_features.groupby('Conviction')['CurrAlloc%'].sum().sort_values(ascending=False)

Conviction
X-LC    23.58
X-MC    22.14
H-SC    21.84
X-SC    12.32
M-SC     9.92
H-MC     5.05
M-MC     2.05
H-LC     1.17
M-LC     1.05
L-SC     0.52
L-MC     0.34
Name: CurrAlloc%, dtype: float64

In [28]:
# sector-wise stats
df_tmp = df_portfolio_features.groupby('Category')[['CurrAlloc%', 'Current', 'Current P/L', 'FTT Amt']].sum().sort_values(by=['Current', 'Current P/L'], ascending=False)
df_tmp['Current P/L%'] = round(df_tmp['Current P/L'] * 100 / df_tmp['Current'], 2)
df_tmp['FTT%'] = round(df_tmp['FTT Amt'] * 100 / df_tmp['Current'], 2)
cols = ['CurrAlloc%', 'Current P/L%', 'FTT%']
df_tmp[cols].sort_values(by=['CurrAlloc%'], ascending=False)

               CurrAlloc%  Current P/L%    FTT%
Category
FMCG                15.29        -26.88   71.93
FINANCE             13.21        -26.38   77.88
IT                  12.11        -44.44  117.95
MISC                 7.02        -48.26  112.67
ELECTRICAL           6.40        -17.60   62.62
PAINTS               5.23        -46.42   71.85
INSURANCE            4.61        -14.21   53.29
BANKS                4.47        -33.66  101.50
PHARMA               4.15        -10.31   45.03
AUTO                 3.65        -39.04   94.21
AC                   1.92        -29.09   64.09
HEALTHCARE           1.90        -45.91   83.98
APPARELS             1.84        -13.52   52.24
FOOTWEAR             1.81        -89.67  165.73
TRAVEL               1.78        -95.63  193.58
DURABLES             1.76        -70.59  112.09
BREWERIES            1.63        -11.56   34.73
REALTY               1.40        -22.65   42.80
CERAMICS             1.37        -73.86  126.67
REFINERIES           1.35        -15.61   44.86
CEMENT               1.23        -70.05  197.26
CABLES               1.17          1.82  104.13
ENGINEERING          1.08        -74.07  153.69
CHEMICALS            1.05        -96.19  256.25
JEWELLERY            0.99       -150.93  238.12
ENTERTAINMENT        0.76        -96.56  213.79
TEXTILES             0.46        -56.87  101.60
HOTELS               0.34       -157.13  247.83

In [29]:
# money to be made criteria-wise
df_portfolio_features.groupby('Criteria')['FTT Amt'].agg(['sum', 'count']).sort_values(by='sum', ascending=False)

                sum  count
Criteria
XY24      4116687.0     21
X40       1910127.0     16
XR        1420529.0     12
AR        1389552.0     10
X40N      1314784.0     10
OX40N      929539.0     10
XY25       516639.0      5
SR         316941.0      2

In [30]:
# money to be made conviction-wise
df_portfolio_features.groupby('Conviction')['FTT Amt'].agg(['sum', 'count']).sort_values(by='sum', ascending=False)

                  sum  count
Conviction
H-SC        3979927.0     24
X-MC        1882602.0     15
X-LC        1740677.0     13
M-SC        1640122.0     14
X-SC        1598095.0     10
H-MC         429601.0      3
L-SC         223550.0      2
M-LC         156939.0      1
M-MC         121411.0      2
H-LC          83307.0      1
L-MC          58567.0      1

In [31]:
# money to be made criteria and conviction-wise
df_portfolio_features.groupby(['Conviction', 'Criteria'])['FTT Amt'].agg(['sum', 'count']).sort_values(by='sum', ascending=False)

                           sum  count
Conviction Criteria
H-SC       XY24      1375765.0      6
           AR         990729.0      5
M-SC       XY24       945444.0      6
X-LC       X40        943552.0      7
H-SC       XR         901646.0      7
X-SC       XY24       866815.0      4
X-MC       X40        740997.0      7
           X40N       575655.0      4
X-SC       X40N       505702.0      4
M-SC       OX40N      420585.0      5
X-LC       XY24       399120.0      2
H-SC       OX40N      394846.0      4
           SR         316941.0      2
X-MC       XY25       284580.0      2
           XY24       281370.0      2
H-MC       XY24       248173.0      1
X-LC       X40N       233427.0      2
X-SC       X40        225578.0      2
M-SC       XR         193935.0      2
H-MC       AR         181428.0      2
X-LC       XY25       164578.0      2
M-LC       XR         156939.0      1
L-SC       OX40N      114108.0      1
           XR         109442.0      1
H-LC       AR          83307.0      1
M-SC       AR          80158.0      1
M-MC       XY25        67481.0      1
L-MC       XR          58567.0      1
M-MC       AR          53930.0      1

In [32]:
# notebook execution time

end_time = time.time()
execution_time = round(end_time - start_time, 0)
print(f"Notebook execution time: {execution_time} seconds")

Notebook execution time: 33.0 seconds