<a href="https://colab.research.google.com/github/ankit-rathi/Quantvesting_v2/blob/main/myStocks_Portfolio_Analysis.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
'''
!pip install pandas==2.2.2 -qq
!pip install pyxirr -qq
!pip install ta -qq
!pip install yfinance==0.2.59 -qq
'''

'\n!pip install pandas==2.2.2 -qq\n!pip install pyxirr -qq\n!pip install ta -qq\n!pip install yfinance==0.2.59 -qq\n'

In [2]:
# import libraries

import numpy as np
import pandas as pd
import datetime
import warnings
warnings.filterwarnings('ignore')
import yfinance as yfin
import ta
import matplotlib.pyplot as plt
import requests

In [3]:
# notebook start time
import time
import datetime
import pytz

start_time = time.time()

# function to print date timestamp
def print_date_time():
  tz_NY = pytz.timezone('Asia/Kolkata')
  datetime_NY = datetime.datetime.now(tz_NY)
  print("Run date time (IST):", datetime_NY.strftime("%Y-%m-%d %H:%M:%S"))

In [4]:
# function to get booked and reserved amount
def get_amt():
  # fetch the JSON data from the URL
  url = "https://raw.githubusercontent.com/ankit-rathi/Tradevesting_v1/main/data/myPortfolioAmts.json"
  response = requests.get(url)
  pf_amts = response.json()  # parse the JSON data

  # extract values from the JSON
  py_booked_amt_dm = pf_amts["py_booked_amt_dm"]
  py_booked_amt_sv = pf_amts["py_booked_amt_sv"]
  cy_booked_amt_dm = pf_amts["cy_booked_amt_dm"]
  cy_booked_amt_sv = pf_amts["cy_booked_amt_sv"]
  reserve_amt_dm = pf_amts["reserve_amt_dm"]
  reserve_amt_sv = pf_amts["reserve_amt_sv"]

  # perform calculations
  py_booked_amt = py_booked_amt_dm + py_booked_amt_sv
  cy_booked_amt = cy_booked_amt_dm + cy_booked_amt_sv
  reserve_amt = reserve_amt_dm + reserve_amt_sv
  total_booked_amt = py_booked_amt + cy_booked_amt

  return total_booked_amt, reserve_amt, cy_booked_amt, py_booked_amt

gen_output = 0

In [5]:
# function to format the amount
def format_amt(number):
    abs_number = abs(number)

    if abs_number >= 1_00_00_000:  # Crores
        formatted_amt = f"{number / 1_00_00_000:.2f} C"
    elif abs_number >= 1_00_000:  # Lakhs
        formatted_amt = f"{number / 1_00_000:.2f} L"
    elif abs_number >= 1_000:  # Thousands
        formatted_amt = f"{number / 1_000:.2f} K"
    else:
        formatted_amt = f"{number:.2f}"

    return formatted_amt

# function to set start and end date
def get_start_end_date():
  start_date = (datetime.date.today() + datetime.timedelta(days=-365)).strftime('%Y-%m-%d')
  end_date = (datetime.date.today() + datetime.timedelta(days=1)).strftime('%Y-%m-%d')
  return start_date, end_date

# function to fetch my portfolio csv
def get_mypfs_df():
  mypfs_df = pd.read_csv('https://raw.githubusercontent.com/ankit-rathi/Tradevesting_v1/main/data/myPortfolioStocks.csv')
  return mypfs_df

# function to fetch my prospects csv
def get_mypps_df():
  mypps_df = pd.read_csv('https://raw.githubusercontent.com/ankit-rathi/Tradevesting_v1/main/data/myProspectsScrips.csv')
  return mypps_df

# function to fetch screener data
def get_myscreen_df():
  myscreen_df = pd.read_csv('https://raw.githubusercontent.com/ankit-rathi/Tradevesting_v1/main/data/myScreenerDB.csv')
  return myscreen_df

# function to fetch momentum data
def get_myinvmt_df():
  myinvmt_df = pd.read_csv('https://raw.githubusercontent.com/ankit-rathi/Tradevesting_v1/main/data/myInvestments.csv')
  return myinvmt_df

# function to get the stock ids
def get_stock_ids(df_pf):
  stock_n100 = df_pf['Symbol'].unique()

  exclude = ['CADILAHC','MMTC', 'MASFIN']

  stock_ids = df_pf[~df_pf['Symbol'].isin(exclude) ]['Symbol'].unique()

  #mypf = mypf[mypf.Forecast.notnull()]
  #stock_ids = mypf['Symbol'].unique()

  #stock_ids.sort()
  return stock_ids

# get features from screener data
def get_screener_features():
  myscreen_df = get_myscreen_df()
  cols = ['Symbol', 'EPS', 'MedPE', 'ROCE%', 'ROE%', 'CapType']
  return myscreen_df[cols]

# get relative strength
def get_relative_strength(stock_list):

    # Dictionary to store stock tickers and their corresponding percentage price change
    stock_changes = {}

    # Loop through each stock and fetch its price data
    for stock in stock_list:
        try:
            # Download the stock data for the given date range
            stock_data = yfin.Ticker(stock + '.NS').history(period='1mo', interval='1d')[map(str.title, ['open', 'close', 'low', 'high', 'volume'])]

            # Calculate the percentage change for the stock
            if len(stock_data) > 0:
                start_price = stock_data['Close'].iloc[0]
                end_price = stock_data['Close'].iloc[-1]
                percent_change = round(((end_price - start_price) / start_price) * 100, 2)
                stock_changes[stock] = percent_change
            else:
                stock_changes[stock] = np.nan  # If no data is available, set to NaN

        except Exception as e:
            print(f"Error fetching data for {stock}: {e}")
            stock_changes[stock] = np.nan

    # Create a DataFrame with stock tickers and their percentage changes
    df = pd.DataFrame(list(stock_changes.items()), columns=['Symbol', 'Percent_Change'])

    # Drop any stocks with missing data (NaN values)
    df = df.dropna()

    # Calculate the percentile rank based on percentage change
    df['RSP'] = round(df['Percent_Change'].rank(pct=True) * 100, 2)
    cols = ['Symbol', 'RSP']
    df = df[cols]
    # Sort by percentile rank (optional)
    df = df.sort_values(by='RSP', ascending=False).reset_index(drop=True)

    return df

In [6]:
# function to get stock technicals
def stock_prec_dev(stock_symbol):
    #stock_symbol = 'ULTRACEMCO.NS'
    short_window = 20
    mid_window = 50
    long_window = 200
    moving_avg = 'SMA'

    start = datetime.datetime(*map(int, start_date.split('-')))
    end = datetime.datetime(*map(int, end_date.split('-')))

    stock_df = yfin.Ticker(stock_symbol + '.NS').history(period='max', interval='1d')[map(str.title, ['open', 'close', 'low', 'high', 'volume'])]

    stock_df['Max'] = round(max(stock_df['Close']),2)
    stock_df = stock_df[(stock_df.index <= end_date) & (stock_df.index >= start_date)]
    stock_df['200_SMA'] = round(stock_df['Close'].rolling(window = 200, min_periods = 1).mean(),0)
    stock_df['Dev%_200'] = round((stock_df['Close'] - stock_df['200_SMA'])*100/stock_df['200_SMA'],2)
    stock_df.dropna(axis = 0, inplace = True) # remove any null rows

    stock_df['20_SMA'] = stock_df['Close'].rolling(window=20).mean()
    stock_df['50_SMA'] = stock_df['Close'].rolling(window=50).mean()
    stock_df['Symbol'] = stock_symbol

    stock_df['Close'] = round(stock_df['Close'],2)
    stock_df['Min'] = round(min(stock_df['Close']),2)
    stock_df['RSI_14'] = ta.momentum.RSIIndicator(close=stock_df['Close'], window=14).rsi()
    stock_df['RSI_14'] = round(stock_df['RSI_14'],0)
    stock_df['Prev_Close'] = stock_df['Close'].shift(1)
    stock_df.drop(['Open', 'Low', 'High', 'Volume'], axis=1, inplace=True)
    stock_df = stock_df.tail(1)

    max_SMA = max(stock_df['20_SMA'].item(), stock_df['50_SMA'].item(), stock_df['200_SMA'].item())
    min_SMA = min(stock_df['20_SMA'].item(), stock_df['50_SMA'].item(), stock_df['200_SMA'].item())
    ABS_Spread = max_SMA - min_SMA
    stock_df['Spread%'] = round((ABS_Spread / stock_df['200_SMA'].item()) * 100,2)

    return stock_df

# function to compute stock attributes
def get_common_features(stock_ids, df_mypf):

  df_prec_dev = pd.DataFrame()
  df_tmp = get_screener_features()
  df_rs = get_relative_strength(stock_ids)

  for stock_id in stock_ids:
      tmp = stock_prec_dev(stock_id)
      tmp = tmp.reset_index()
      df_prec_dev = pd.concat([df_prec_dev, tmp], ignore_index = True)
  df_prec_dev = pd.merge(df_prec_dev, df_mypf, on= 'Symbol')
  df_prec_dev = pd.merge(df_prec_dev, df_tmp, on= 'Symbol', how='left')
  df_prec_dev = pd.merge(df_prec_dev, df_rs, on= 'Symbol', how='left')
  #print(df_prec_dev.columns)
  df_prec_dev['Curr_PE'] = round(df_prec_dev['Close']/df_prec_dev['EPS'],1)
  df_prec_dev['Dev%_PE'] = round((df_prec_dev['Curr_PE'] - df_prec_dev['MedPE'])*100/df_prec_dev['MedPE'],2)
  df_prec_dev['Conviction'] = df_prec_dev['Conviction'] + '-' + df_prec_dev['CapType']
  return df_prec_dev

# function to arrange stock features
def arrange_features(df_stocks, common_cols, diff_cols):
  df_stocks_common = df_stocks[common_cols].drop_duplicates()
  df_stocks_diff = df_stocks[diff_cols]
  df_stocks_diff['Investment'] = df_stocks_diff['AvgCost'] * df_stocks_diff['Shares']
  df_stocks_diff = df_stocks_diff.groupby(['Symbol'])[['Shares', 'Investment']].aggregate(['sum']).reset_index()
  df_stocks_diff.columns = ['Symbol', 'Shares', 'Investment']
  df_stocks_diff['AvgCost'] = round(df_stocks_diff['Investment']/df_stocks_diff['Shares'],2)
  df_stocks = pd.merge(df_stocks_diff, df_stocks_common, on='Symbol')
  return df_stocks

# plot fact distribution across dimension
def plot_pie_chart(df, dimension, fact):
  # grouping the data by category and calculating the sum of fact for each type
  grouped_data = df.groupby(dimension)[fact].sum()

  # sorting the grouped data in descending order
  grouped_data = grouped_data.sort_values(ascending=False)

  # creating a pie chart
  grouped_data.plot.pie(autopct='%1.1f%%', startangle=90, figsize=(6, 6))

  # adding a title and displaying the plot
  plt.title(f'{dimension} {fact} Distribution')
  plt.ylabel('')  # To hide the y-label
  plt.show()

In [7]:
# function to get portfolio features

def get_portfolio_features(df_common_features):

  print_date_time()
  print('-------------------')

  #df_common_features["Target"] = df_common_features["Target"].fillna(df_common_features["Max"])
  df_common_features['NTT'] = np.where(df_common_features['Strategy']== 'NTT', df_common_features["Target"], df_common_features['Max'])
  df_common_features['LTT'] = np.where(df_common_features['Strategy']== 'BTT', df_common_features["Target"], df_common_features['Max'])
  df_common_features['BOL'] = df_common_features['Min']

  tmp_df = df_common_features[df_common_features['Symbol'].isin(mypf_df[mypf_df['InPortfolio'] != 'NA'].Symbol.values)]
  print('qualified stocks: '+str(len(tmp_df['Symbol'].unique())))
  tmp_df1 = tmp_df[tmp_df['LatestQtr'] == 1]
  print('with latest results: '+str(len(tmp_df1['Symbol'].unique())))
  tmp_df1 = tmp_df1[tmp_df1['StarStock'] == 1]
  print('still star stocks: '+str(len(tmp_df1['Symbol'].unique())))
  tmp_df['Investment'] = tmp_df['AvgCost'] * tmp_df['Shares']
  tmp_df['Current'] = round(tmp_df['Close'] * tmp_df['Shares'],0)
  tmp_df['Previous'] = tmp_df['Prev_Close'] * tmp_df['Shares']
  tmp_df['EstimatedST'] = tmp_df['NTT'] * tmp_df['Shares']
  tmp_df['EstimatedLT'] = tmp_df['LTT'] * tmp_df['Shares']
  tmp_df['Current P/L'] = round((tmp_df['Current'] - tmp_df['Investment']),0)
  tmp_df['Today P/L%'] = round((tmp_df['Current'] - tmp_df['Previous'])*100/tmp_df['Previous'],2)
  tmp_df['Current P/L%'] = round((tmp_df['Current'] - tmp_df['Investment'])*100/tmp_df['Investment'],2)
  tmp_df['EstimatedST P/L%'] = round((tmp_df['EstimatedST'] - tmp_df['Investment'])*100/tmp_df['Investment'],2)
  tmp_df['EstimatedLT P/L%'] = round((tmp_df['EstimatedLT'] - tmp_df['Investment'])*100/tmp_df['Investment'],2)
  tmp_df['NTT%'] = round((tmp_df['NTT'] - tmp_df['Close'])*100/tmp_df['Close'],2)
  tmp_df['LTT%'] = round((tmp_df['LTT'] - tmp_df['Close'])*100/tmp_df['Close'],2)
  tmp_df['Gained%'] = round((tmp_df['Close'] - tmp_df['BOL'])*100/tmp_df['BOL'],2)
  investment = round(sum(tmp_df['AvgCost']*tmp_df['Shares']),0)
  current = round(sum(tmp_df['Close']*tmp_df['Shares']),0)
  tmp_df['InitAlloc%'] = round(tmp_df['Investment']*100/investment,2)
  tmp_df['CurrAlloc%'] = round(tmp_df['Current']*100/current,2)
  tmp_df['FTT'] = tmp_df['LTT']
  tmp_df.loc[tmp_df['Strategy'] == 'NTT', 'FTT'] = tmp_df['NTT']
  tmp_df['FTT%'] = tmp_df['LTT%']
  tmp_df.loc[tmp_df['Strategy'] == 'NTT', 'FTT%'] = tmp_df['NTT%']
  tmp_df['FTT Amt'] = round(tmp_df['FTT%'] * tmp_df['Current']/100,0)
  tmp_df['OTT%'] = round((tmp_df['FTT'] - tmp_df['AvgCost'])*100/tmp_df['AvgCost'],2)
  tmp_df['RRR Ind'] = round(tmp_df['Current P/L']/tmp_df['FTT Amt'],2)
  tmp_df['Risk Ind'] = round(tmp_df['Current P/L%']*tmp_df['CurrAlloc%'],0)

  return tmp_df

# function to print portfolio features
def print_portfolio_stats(df_portfolio_features, myinvmt_df):
  from pyxirr import xirr

  total_booked_amt, reserve_amt, cy_booked_amt, py_booked_amt = get_amt()

  dates = myinvmt_df['Date'].values
  dates = np.append(dates, datetime.date.today().strftime('%d-%b-%y'))
  investment = myinvmt_df['Investment'].values
  dates= pd.to_datetime(dates)

  current = round(sum(df_portfolio_features['Close']*df_portfolio_features['Shares']),0) + reserve_amt
  investment_xirr = np.append(investment, current)
  cagr = round(xirr(pd.DataFrame({"dates": dates, "amounts": investment_xirr}))*100,2)

  investment = -sum(investment)
  invested = round(sum(df_portfolio_features['AvgCost']*df_portfolio_features['Shares']),0) + reserve_amt
  previous = round(sum(df_portfolio_features['Prev_Close']*df_portfolio_features['Shares']),0) + reserve_amt
  cy_invested = investment + py_booked_amt

  today_pnl_amount = current-previous
  today_pnl_percentage = round((current-previous)*100/previous,2)

  curr_pnl_amount = current-invested
  curr_pnl_percentage = round((curr_pnl_amount)*100/(cy_invested),2)

  cy_pnl_amount = cy_booked_amt + curr_pnl_amount
  cy_pnl_percentage = round((cy_pnl_amount)*100/cy_invested,2)

  overall_pnl_amount = total_booked_amt + curr_pnl_amount
  overall_pnl_percentage = round((overall_pnl_amount)*100/investment,2)

  estimate_st = round(sum(df_portfolio_features['FTT']*df_portfolio_features['Shares']),0)  + reserve_amt
  est_st_pnl_amount = estimate_st-current
  est_st_pnl_percentage = round((est_st_pnl_amount)*100/current,2)

  estimate_lt = round(sum(df_portfolio_features['LTT']*df_portfolio_features['Shares']),0)  + reserve_amt
  est_lt_pnl_amount = estimate_lt-current
  est_lt_pnl_percentage = round((est_lt_pnl_amount)*100/current,2)

  total_profit = round(sum(df_portfolio_features[df_portfolio_features['Current P/L%'] > 0]['Current']) - sum(df_portfolio_features[df_portfolio_features['Current P/L%'] > 0]['Investment']),0)
  total_loss = round(sum(df_portfolio_features[df_portfolio_features['Current P/L%'] < 0]['Current']) - sum(df_portfolio_features[df_portfolio_features['Current P/L%'] < 0]['Investment']),0)

  cy_booked_percentage = round((cy_booked_amt)*100/current,2)
  py_booked_percentage = round((py_booked_amt)*100/investment,2)
  total_booked_percentage = round((total_booked_amt)*100/investment,2)

  print('-------------------')
  print('Initial Investment: ', format_amt(investment))
  print('CY Investment: ', format_amt(cy_invested))
  print('Reserve: ', format_amt(reserve_amt))
  print('Current: ',  format_amt(current))
  print('-------------------')
  print('Today PnL: '+ '{} ({}%)'.format(format_amt(today_pnl_amount), today_pnl_percentage))
  print('Current PnL: '+ '{} ({}%)'.format(format_amt(curr_pnl_amount), curr_pnl_percentage))
  print('CY Booked + Current PnL: '+ '{} ({}%)'.format(format_amt(cy_pnl_amount), cy_pnl_percentage))
  print('-------------------')
  print('Total profit: ', format_amt(total_profit))
  print('Total loss: ', format_amt(total_loss))
  print('-------------------')
  print('Total Booked + Current PnL: '+ '{} ({}%)'.format(format_amt(overall_pnl_amount), overall_pnl_percentage))
  print('Total Booked PnL: '+ '{} ({}%)'.format(format_amt(total_booked_amt), total_booked_percentage))
  print('Curr Year Booked PnL: '+ '{} ({}%)'.format(format_amt(cy_booked_amt), cy_booked_percentage))
  print('Prev Year Booked PnL: '+ '{} ({}%)'.format(format_amt(py_booked_amt), py_booked_percentage))
  print('===================')
  print('Est FTT: ',  format_amt(estimate_st))
  print('Est FTT PnL: '+ '{} ({}%)'.format(format_amt(est_st_pnl_amount), est_st_pnl_percentage))

  print('===================')
  print('Deployed: ', format_amt(investment))

  print('Current: ', format_amt(current))

  print('CAGR/XIRR %: '+'{}%'.format(cagr))

In [8]:
# get start and end date
start_date, end_date = get_start_end_date()

# get portfolio and prospects data
mypfs_df = get_mypfs_df()
mypps_df = get_mypps_df()
myinvmt_df = get_myinvmt_df()

# merge above datasets
mypf_df = pd.merge(mypfs_df, mypps_df, on="Symbol")

# seggregate dm and sv portfolio
dm_pf = mypf_df[mypf_df['InPortfolio'] == 'DM']
sv_pf = mypf_df[mypf_df['InPortfolio'] == 'SV']

# build portfolio stock dataframe
dm_stocks = get_stock_ids(dm_pf)
sv_stocks = get_stock_ids(sv_pf)
df_stocks = pd.concat([dm_pf,sv_pf], ignore_index = True)

# arrange common and diff stock features
common_cols = ['Symbol', 'Target', 'Criteria', 'Strategy', 'CumlRnk', 'LatestQtr', 'StarStock', 'Conviction', 'Category', 'InFolio', 'XIRR', 'MBQ']
diff_cols = ['Symbol', 'AvgCost', 'Shares']
df_stocks = arrange_features(df_stocks, common_cols, diff_cols)

# get common features
stock_ids = df_stocks['Symbol'].values
df_common_features = get_common_features(stock_ids, df_stocks)

df_common_features.reset_index(drop=True, inplace=True)
df_common_features.drop(['Date'], axis=1, inplace=True)
# get and print portfolio features
df_portfolio_features = get_portfolio_features(df_common_features)

print_portfolio_stats(df_portfolio_features, myinvmt_df)

df = df_portfolio_features
#plot_pie_chart(df, 'CapType', 'Current')
list_ox40n = list(df[df['MBQ'].str.contains('OX40N', na=False)]['Symbol'].values)

Run date time (IST): 2026-05-22 11:36:13
-------------------
qualified stocks: 92
with latest results: 31
still star stocks: 20

-------------------
Initial Investment:  1.40 C
CY Investment:  1.82 C
Reserve:  1.49 K
Current:  1.49 C
-------------------
Today PnL: 82.95 K (0.56%)
Current PnL: -34.12 L (-18.71%)
CY Booked + Current PnL: -32.04 L (-17.57%)
-------------------
Total profit:  1.96 L
Total loss:  -36.07 L
-------------------
Total Booked + Current PnL: 10.83 L (7.76%)
Total Booked PnL: 44.95 L (32.22%)
Curr Year Booked PnL: 2.08 L (1.4%)
Prev Year Booked PnL: 42.87 L (30.73%)
===================
Est FTT:  2.55 C
Est FTT PnL: 1.06 C (71.35%)
===================
Deployed:  1.40 C
Current:  1.49 C
CAGR/XIRR %: 3.21%

In [9]:
# top 5 near their targets
cols = ['Symbol', 'Today P/L%', 'Current P/L%', 'FTT%', 'OTT%', 'FTT Amt', 'Current P/L', 'Current', 'FTT', 'Dev%_PE', 'RSI_14','Conviction', 'Spread%',  'CumlRnk', 'RRR Ind', 'CurrAlloc%', 'Gained%', 'Criteria', 'Strategy', 'Category']
df_tmp = df_portfolio_features[~df_portfolio_features['Symbol'].isin(['ENRIN','BLUSPRING','DIGITIDE'])]
df_tmp = df_tmp.sort_values(by = 'FTT Amt', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
59,PIDILITIND,-0.29,4.07,13.74,18.37,20177.0,5740.0,146850.0,1670.26,-27.09,60.0,X-LC,5.49,5.0,0.28,0.99,15.30,X40,ATH,CHEMICALS
51,KOTAKBANK,0.51,2.28,18.40,21.11,26061.0,3164.0,141636.0,453.24,-12.44,52.0,X-LC,7.84,12.0,0.12,0.95,8.32,X40,ATH,BANKS
83,TTKPRESTIG,2.86,-27.56,38.18,0.09,27871.0,-27777.0,73000.0,770.00,69.48,65.0,M-SC,15.72,250.0,-1.00,0.49,29.99,OX40N,NTT,DURABLES
55,MASFIN,-0.64,-6.90,30.58,21.57,27894.0,-6765.0,91215.0,397.04,-19.60,34.0,H-SC,4.95,167.0,-0.24,0.61,8.73,XR,ATH,FINANCE
53,M&M,0.29,0.85,22.34,23.38,31245.0,1179.0,139860.0,3802.40,-14.43,46.0,X-LC,8.86,25.0,0.04,0.94,6.04,X40N,ATH,AUTO

In [10]:
# top 5 today
df_tmp = df_portfolio_features.sort_values(by = 'Today P/L%', ascending=False)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
69,SFL,8.12,-36.66,99.91,26.63,165951.0,-96118.0,166100.0,1287.00,25.76,70.0,M-SC,11.61,242.0,-0.58,1.11,38.44,XY24,NTT,MISC
22,DIXON,4.33,-14.43,61.19,37.92,136549.0,-37643.0,223155.0,18931.72,-63.60,61.0,X-MC,19.95,54.0,-0.28,1.50,21.42,X40N,ATH,IT
29,GREENPANEL,4.33,-49.82,185.26,43.14,170191.0,-91212.0,91866.0,537.00,106.07,36.0,M-SC,16.27,225.0,-0.54,0.62,10.35,XY24,NTT,MISC
49,JSWINFRA,3.80,-6.19,24.12,16.43,50179.0,-13734.0,208040.0,342.00,-19.64,55.0,X-MC,5.94,61.0,-0.27,1.40,17.60,X40N,NTT,REALTY
13,BSOFT,3.52,-39.69,150.02,50.79,127256.0,-55827.0,84826.0,831.70,-22.69,42.0,H-SC,9.90,172.0,-0.44,0.57,7.45,XR,ATH,IT

In [11]:
# bottom 5 today
df_tmp = df_portfolio_features.sort_values(by = 'Today P/L%', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
68,SATIN,-3.25,16.67,30.14,51.83,97157.0,46068.0,322352.0,274.0,5.12,62.0,H-SC,32.15,159.0,0.47,2.16,57.03,XY24,NTT,FINANCE
89,WHIRLPOOL,-2.90,-31.72,166.43,81.92,130454.0,-36414.0,78384.0,2270.0,-59.97,40.0,M-SC,15.99,210.0,-0.28,0.53,10.11,XR,NTT,DURABLES
66,REPCOHOME,-2.43,-17.01,128.72,89.82,306065.0,-48729.0,237776.0,880.0,-58.27,44.0,H-SC,3.53,161.0,-0.16,1.60,14.30,XY24,NTT,FINANCE
47,ITC,-1.51,-20.08,48.98,19.06,133150.0,-68320.0,271846.0,452.0,-56.33,44.0,X-LC,14.88,1.0,-0.51,1.82,5.46,X40,NTT,FMCG
15,CAMS,-1.28,-0.52,25.12,24.48,62939.0,-1304.0,250552.0,950.0,-4.67,48.0,X-SC,7.74,89.0,-0.02,1.68,21.98,X40N,NTT,MISC

In [12]:
# top 5 to exit based on CumlRnk
df_tmp = df_portfolio_features[~df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])]
df_tmp = df_tmp[(df_tmp['Current P/L%'] > -1) & (df_tmp['Current P/L%'] < 1)].sort_values(by = 'CumlRnk', ascending=False)
df_tmp[cols].head()

Empty DataFrame
Columns: [Symbol, Today P/L%, Current P/L%, FTT%, OTT%, FTT Amt, Current P/L, Current, FTT, Dev%_PE, RSI_14, Conviction, Spread%, CumlRnk, RRR Ind, CurrAlloc%, Gained%, Criteria, Strategy, Category]
Index: []

In [13]:
# OX40N stocks to exit
df_tmp = df_portfolio_features[(df_portfolio_features['Symbol'].isin(list_ox40n))].sort_values(by = 'Current P/L%', ascending=False)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
25,FINCABLES,-0.32,31.70,57.87,107.91,112524.0,46799.0,194443.0,1641.55,18.72,55.0,M-SC,25.60,220.0,0.42,1.30,46.29,OX40N,ATH,CABLES
72,SIS,0.31,-9.74,34.35,21.26,34424.0,-10817.0,100215.0,528.00,2383.42,63.0,H-SC,15.56,168.0,-0.31,0.67,49.00,OX40N,NTT,MISC
16,CERA,0.32,-24.08,63.18,23.89,84377.0,-42353.0,133550.0,9475.00,-26.73,61.0,H-SC,7.09,153.0,-0.50,0.90,28.34,OX40N,NTT,CERAMICS
50,KANSAINER,1.95,-25.83,52.99,13.47,105984.0,-69660.0,200007.0,340.00,-36.25,65.0,H-SC,13.38,162.0,-0.66,1.34,39.71,XY24,NTT,PAINTS
83,TTKPRESTIG,2.86,-27.56,38.18,0.09,27871.0,-27777.0,73000.0,770.00,69.48,65.0,M-SC,15.72,250.0,-1.00,0.49,29.99,OX40N,NTT,DURABLES

In [14]:
# top 5 to book for rotation
df_tmp = df_portfolio_features[(df_portfolio_features['Current P/L%'] > 20) ].sort_values(by = 'CumlRnk', ascending=False)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
25,FINCABLES,-0.32,31.7,57.87,107.91,112524.0,46799.0,194443.0,1641.55,18.72,55.0,M-SC,25.6,220.0,0.42,1.3,46.29,OX40N,ATH,CABLES

In [15]:
# top 5 to monitor for exit
df_tmp = df_portfolio_features[~df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])]
df_tmp = df_tmp[(df_tmp['Current P/L%'] > 0) ].sort_values(by = 'Dev%_PE', ascending=False)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
74,STARHEALTH,0.49,2.42,43.79,47.26,126077.0,6789.0,287912.0,761.00,61.57,65.0,H-SC,10.33,173.0,0.05,1.93,26.40,XY24,NTT,INSURANCE
25,FINCABLES,-0.32,31.70,57.87,107.91,112524.0,46799.0,194443.0,1641.55,18.72,55.0,M-SC,25.60,220.0,0.42,1.30,46.29,OX40N,ATH,CABLES
68,SATIN,-3.25,16.67,30.14,51.83,97157.0,46068.0,322352.0,274.00,5.12,62.0,H-SC,32.15,159.0,0.47,2.16,57.03,XY24,NTT,FINANCE
91,ZYDUSLIFE,0.32,9.65,23.69,35.63,54439.0,20222.0,229796.0,1286.17,-4.50,70.0,H-MC,3.37,120.0,0.37,1.54,20.82,AR,ATH,PHARMA
73,SONACOMS,2.17,3.28,34.68,39.09,36232.0,3316.0,104475.0,804.02,-18.17,58.0,M-MC,19.34,193.0,0.09,0.70,47.79,AR,ATH,AUTO

In [16]:
# top 5 to book for rotation from weak conviction
df_tmp = df_portfolio_features[~df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])]
df_tmp = df_tmp[~df_tmp['Criteria'].isin(['XY25','XY24','X40', 'X40N'])].sort_values(by = 'RRR Ind', ascending=False)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
25,FINCABLES,-0.32,31.70,57.87,107.91,112524.0,46799.0,194443.0,1641.55,18.72,55.0,M-SC,25.60,220.0,0.42,1.30,46.29,OX40N,ATH,CABLES
91,ZYDUSLIFE,0.32,9.65,23.69,35.63,54439.0,20222.0,229796.0,1286.17,-4.50,70.0,H-MC,3.37,120.0,0.37,1.54,20.82,AR,ATH,PHARMA
73,SONACOMS,2.17,3.28,34.68,39.09,36232.0,3316.0,104475.0,804.02,-18.17,58.0,M-MC,19.34,193.0,0.09,0.70,47.79,AR,ATH,AUTO
42,INDIAMART,0.40,-12.41,136.00,106.72,146928.0,-15301.0,108035.0,4810.62,-60.55,48.0,H-SC,10.32,140.0,-0.10,0.72,4.59,AR,ATH,MISC
90,WIPRO,2.49,-16.04,105.17,72.27,149629.0,-27175.0,142273.0,420.00,-24.09,61.0,M-LC,13.87,98.0,-0.18,0.95,9.16,XR,NTT,IT

In [17]:
# top 5 to accumulate based on lowest RSI_14
df_tmp = df_portfolio_features[df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])].sort_values(by = 'RSI_14', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
23,DMART,-0.06,-0.61,30.39,29.60,75394.0,-1512.0,248088.0,5391.45,-16.21,35.0,X-LC,5.25,14.0,-0.02,1.66,13.40,X40N,ATH,FMCG
58,PGHH,-0.62,-28.06,83.51,32.01,128271.0,-59920.0,153600.0,17616.87,-51.29,37.0,X-MC,17.51,57.0,-0.47,1.03,5.06,X40,ATH,FMCG
26,GILLETTE,0.16,-9.41,43.20,29.72,99364.0,-23886.0,230010.0,10978.86,-30.33,39.0,X-SC,8.68,83.0,-0.24,1.54,5.70,X40,ATH,FMCG
33,HCLTECH,0.42,-23.87,59.61,21.51,109788.0,-57747.0,184177.0,1872.35,-20.18,40.0,X-LC,18.49,8.0,-0.53,1.24,4.37,X40,ATH,IT
79,TCS,-0.00,-31.68,85.27,26.57,269879.0,-146774.0,316499.0,4311.59,-42.31,40.0,X-LC,17.09,2.0,-0.54,2.12,3.62,X40,ATH,IT

In [18]:
# top 5 to accumulate based on Spread and CumlRnk
df_tmp = df_portfolio_features[df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])]
df_tmp = df_tmp[(df_tmp['CumlRnk'] < 100)].sort_values(by = 'Spread%', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
88,VOLTAS,-0.36,-0.73,46.27,45.20,88068.0,-1407.0,190335.0,1856.00,13.69,41.0,X-MC,2.62,79.0,-0.02,1.28,3.99,XY25,NTT,AC
84,UNITDSPR,0.03,-6.49,29.14,20.77,63804.0,-15188.0,218956.0,1644.00,-17.10,44.0,X-MC,3.43,64.0,-0.24,1.47,4.45,X40N,NTT,BREWERIES
65,RELIANCE,0.42,-13.00,44.03,25.30,76979.0,-26129.0,174834.0,1952.00,-15.42,46.0,X-LC,3.80,21.0,-0.34,1.17,3.89,XY25,BTT,REFINERIES
39,ICICIGI,2.21,-2.49,22.39,19.34,43688.0,-4984.0,195125.0,2252.93,-17.87,55.0,X-MC,4.95,66.0,-0.11,1.31,8.98,X40,ATH,INSURANCE
23,DMART,-0.06,-0.61,30.39,29.60,75394.0,-1512.0,248088.0,5391.45,-16.21,35.0,X-LC,5.25,14.0,-0.02,1.66,13.40,X40N,ATH,FMCG

In [19]:
# top 5 to accumulate based on lowest Gained%
df_tmp = df_portfolio_features[df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])].sort_values(by = 'Gained%', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
32,HAVELLS,0.11,-22.85,70.34,31.42,177995.0,-74941.0,253050.0,2052.62,-27.37,43.0,X-MC,12.35,63.0,-0.42,1.70,2.58,X40,ATH,ELECTRICAL
40,ICICIPRULI,1.58,-14.26,52.47,30.73,88631.0,-28088.0,168917.0,790.00,-37.31,42.0,X-MC,12.15,78.0,-0.32,1.13,2.93,X40,ATH,INSURANCE
27,GLAXO,0.82,-6.07,48.14,39.15,90110.0,-12100.0,187184.0,3466.20,-28.31,42.0,X-MC,6.32,56.0,-0.13,1.26,3.55,X40,ATH,PHARMA
79,TCS,-0.00,-31.68,85.27,26.57,269879.0,-146774.0,316499.0,4311.59,-42.31,40.0,X-LC,17.09,2.0,-0.54,2.12,3.62,X40,ATH,IT
28,GODREJCP,-0.17,-9.11,44.65,31.47,60311.0,-13539.0,135075.0,1469.04,-4.32,41.0,X-LC,8.44,32.0,-0.22,0.91,3.64,X40N,ATH,FMCG

In [20]:
# top 5 to accumulate based on lowest CurrAlloc%
df_tmp = df_portfolio_features[df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])].sort_values(by = 'CurrAlloc%', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
64,RELAXO,0.24,-61.86,299.32,52.31,165722.0,-89794.0,55366.0,1176.00,-59.35,48.0,X-SC,25.03,92.0,-0.54,0.37,23.79,X40N,NTT,FOOTWEAR
10,BATAINDIA,0.61,-55.30,202.45,35.20,116447.0,-71151.0,57519.0,2096.00,-24.62,42.0,X-SC,25.77,91.0,-0.61,0.39,14.07,X40,NTT,FOOTWEAR
60,QUESS,0.61,-16.89,109.23,73.90,96954.0,-18032.0,88761.0,424.00,-55.37,50.0,X-SC,10.59,80.0,-0.19,0.60,21.00,XY24,NTT,MISC
28,GODREJCP,-0.17,-9.11,44.65,31.47,60311.0,-13539.0,135075.0,1469.04,-4.32,41.0,X-LC,8.44,32.0,-0.22,0.91,3.64,X40N,ATH,FMCG
53,M&M,0.29,0.85,22.34,23.38,31245.0,1179.0,139860.0,3802.40,-14.43,46.0,X-LC,8.86,25.0,0.04,0.94,6.04,X40N,ATH,AUTO

In [21]:
# top 5 to accumulate based on CumlRnk
df_tmp = df_portfolio_features.sort_values(by = 'CumlRnk', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
47,ITC,-1.51,-20.08,48.98,19.06,133150.0,-68320.0,271846.0,452.00,-56.33,44.0,X-LC,14.88,1.0,-0.51,1.82,5.46,X40,NTT,FMCG
79,TCS,-0.00,-31.68,85.27,26.57,269879.0,-146774.0,316499.0,4311.59,-42.31,40.0,X-LC,17.09,2.0,-0.54,2.12,3.62,X40,ATH,IT
45,INFY,0.24,-19.40,66.55,34.24,167834.0,-60696.0,252192.0,1972.00,-36.50,48.0,X-LC,19.06,3.0,-0.36,1.69,8.13,X40,NTT,IT
81,TMPV,0.32,-17.48,65.52,36.58,192383.0,-62216.0,293625.0,600.00,-82.53,59.0,X-LC,6.04,4.0,-0.32,1.97,22.38,XY24,NTT,AUTO
59,PIDILITIND,-0.29,4.07,13.74,18.37,20177.0,5740.0,146850.0,1670.26,-27.09,60.0,X-LC,5.49,5.0,0.28,0.99,15.30,X40,ATH,CHEMICALS

In [22]:
# top 5 for average up
df_tmp = df_portfolio_features[(df_portfolio_features['Dev%_200'] > 5)].sort_values(by = 'CurrAlloc%', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
44,INDUSINDBK,1.25,-32.73,97.54,32.89,50660.0,-25268.0,51938.0,1800.00,-344.40,56.0,L-MC,8.58,258.0,-0.50,0.35,27.84,XR,NTT,BANKS
72,SIS,0.31,-9.74,34.35,21.26,34424.0,-10817.0,100215.0,528.00,2383.42,63.0,H-SC,15.56,168.0,-0.31,0.67,49.00,OX40N,NTT,MISC
73,SONACOMS,2.17,3.28,34.68,39.09,36232.0,3316.0,104475.0,804.02,-18.17,58.0,M-MC,19.34,193.0,0.09,0.70,47.79,AR,ATH,AUTO
75,SURYODAY,0.79,-8.33,34.21,23.03,56159.0,-14912.0,164159.0,216.00,79.82,55.0,H-SC,17.34,166.0,-0.27,1.10,38.22,XR,NTT,BANKS
69,SFL,8.12,-36.66,99.91,26.63,165951.0,-96118.0,166100.0,1287.00,25.76,70.0,M-SC,11.61,242.0,-0.58,1.11,38.44,XY24,NTT,MISC

In [23]:
# top 5 RSP
df_tmp = df_portfolio_features.sort_values(by = 'RSP', ascending=False)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
68,SATIN,-3.25,16.67,30.14,51.83,97157.0,46068.0,322352.0,274.00,5.12,62.0,H-SC,32.15,159.0,0.47,2.16,57.03,XY24,NTT,FINANCE
72,SIS,0.31,-9.74,34.35,21.26,34424.0,-10817.0,100215.0,528.00,2383.42,63.0,H-SC,15.56,168.0,-0.31,0.67,49.00,OX40N,NTT,MISC
3,ALKYLAMINE,-0.80,-26.38,163.02,93.63,121166.0,-26637.0,74326.0,4546.37,-21.23,60.0,H-SC,13.43,142.0,-0.22,0.50,40.35,SR,ATH,CHEMICALS
69,SFL,8.12,-36.66,99.91,26.63,165951.0,-96118.0,166100.0,1287.00,25.76,70.0,M-SC,11.61,242.0,-0.58,1.11,38.44,XY24,NTT,MISC
17,CIPLA,-0.33,13.13,19.06,34.69,33024.0,20104.0,173265.0,1663.60,-12.55,61.0,X-LC,10.09,18.0,0.61,1.16,17.18,X40N,ATH,PHARMA

In [24]:
# Top N allocation
df_tmp = df_portfolio_features.sort_values(by = 'CurrAlloc%', ascending=False)
top_n_values = [10, 25, 50]

sum_df = pd.DataFrame({
    'Top_N': top_n_values,
    'Sum_Alloc%': [df_tmp['CurrAlloc%'].head(n).sum() for n in top_n_values]
})

sum_df

   Top_N  Sum_Alloc%
0     10       19.34
1     25       42.68
2     50       72.90

In [25]:
# market-cap-wise allocation
df_tmp = df_portfolio_features[cols]
df_tmp.groupby(df_tmp['Conviction'].str[-2:])['CurrAlloc%'].sum().sort_values(ascending=False)

Conviction
SC    42.48
LC    31.61
MC    25.90
Name: CurrAlloc%, dtype: float64

In [26]:
# criteria-wise allocation
df_portfolio_features.groupby('Criteria')['CurrAlloc%'].sum().sort_values(ascending=False)

Criteria
XY24     27.37
X40      25.58
X40N     16.91
XR        8.90
OX40N     6.95
AR        6.81
XY25      6.62
SR        0.85
Name: CurrAlloc%, dtype: float64

In [27]:
# conviction-wise allocation
df_portfolio_features.groupby('Conviction')['CurrAlloc%'].sum().sort_values(ascending=False)

Conviction
X-LC    29.38
H-SC    22.17
X-MC    20.90
M-SC    10.05
X-SC     9.76
H-MC     2.71
M-MC     1.94
H-LC     1.28
M-LC     0.95
L-SC     0.50
L-MC     0.35
Name: CurrAlloc%, dtype: float64

In [28]:
# sector-wise stats
df_tmp = df_portfolio_features.groupby('Category')[['CurrAlloc%', 'Current', 'Current P/L', 'FTT Amt']].sum().sort_values(by=['Current', 'Current P/L'], ascending=False)
df_tmp['Current P/L%'] = round(df_tmp['Current P/L'] * 100 / df_tmp['Current'], 2)
df_tmp['FTT%'] = round(df_tmp['FTT Amt'] * 100 / df_tmp['Current'], 2)
cols = ['CurrAlloc%', 'Current P/L%', 'FTT%']
df_tmp[cols].sort_values(by=['CurrAlloc%'], ascending=False)

               CurrAlloc%  Current P/L%    FTT%
Category
FMCG                15.24        -16.47   57.51
FINANCE             10.63        -16.27   66.85
IT                  10.42        -44.99  117.99
MISC                 6.94        -29.60   85.90
AUTO                 6.68         -9.87   51.06
PAINTS               5.59        -18.26   38.79
BANKS                5.58         -9.31   59.85
INSURANCE            5.38         -3.10   38.19
PHARMA               5.07          1.94   29.57
ELECTRICAL           4.18        -13.53   53.60
CHEMICALS            2.16        -26.57  102.00
HEALTHCARE           2.05        -17.20   47.78
APPARELS             1.83          1.76   31.76
AC                   1.80        -19.57   52.00
TRAVEL               1.70        -76.90  165.48
FOOTWEAR             1.66        -78.85  150.57
DURABLES             1.65        -57.82   96.22
BREWERIES            1.47         -6.94   29.14
REALTY               1.40         -6.60   24.12
CERAMICS             1.35        -52.93   99.39
CABLES               1.30         24.07   57.87
REFINERIES           1.17        -14.95   44.03
ENGINEERING          1.17        -39.07  102.68
CEMENT               1.10        -63.80  186.34
JEWELLERY            1.06       -101.75  171.85
ENTERTAINMENT        0.70        -84.81  195.03
TEXTILES             0.40        -53.70   97.53
HOTELS               0.31       -142.08  227.47

In [29]:
# money to be made criteria-wise
df_portfolio_features.groupby('Criteria')['FTT Amt'].agg(['sum', 'count']).sort_values(by='sum', ascending=False)

                sum  count
Criteria
XY24      3519131.0     21
X40       1887967.0     19
XR        1354607.0     13
X40N      1202798.0     13
AR        1167223.0      9
OX40N      755629.0     10
XY25       454414.0      5
SR         293314.0      2

In [30]:
# money to be made conviction-wise
df_portfolio_features.groupby('Conviction')['FTT Amt'].agg(['sum', 'count']).sort_values(by='sum', ascending=False)

                  sum  count
Conviction
H-SC        3482195.0     24
X-LC        1916439.0     21
X-MC        1617766.0     15
M-SC        1419838.0     14
X-SC        1349715.0      9
H-MC         294024.0      2
L-SC         215347.0      2
M-LC         149629.0      1
M-MC          96287.0      2
L-MC          50660.0      1
H-LC          43183.0      1

In [31]:
# money to be made criteria and conviction-wise
df_portfolio_features.groupby(['Conviction', 'Criteria'])['FTT Amt'].agg(['sum', 'count']).sort_values(by='sum', ascending=False)

                           sum  count
Conviction Criteria
H-SC       XY24      1092923.0      6
X-LC       X40       1010830.0     10
H-SC       AR         957000.0      5
M-SC       XY24       834700.0      6
H-SC       XR         811756.0      7
X-SC       XY24       792652.0      4
X-MC       X40        661326.0      7
           X40N       490407.0      4
X-LC       X40N       371139.0      6
X-SC       X40N       341252.0      3
X-LC       XY24       338299.0      2
H-SC       OX40N      327202.0      4
M-SC       OX40N      319777.0      5
H-SC       SR         293314.0      2
X-MC       XY25       245061.0      2
H-MC       XY24       239585.0      1
X-MC       XY24       220972.0      2
X-SC       X40        215811.0      2
M-SC       XR         188992.0      2
M-LC       XR         149629.0      1
X-LC       XY25       149298.0      2
L-SC       OX40N      108650.0      1
           XR         106697.0      1
M-SC       AR          76369.0      1
M-MC       XY25        60055.0      1
H-MC       AR          54439.0      1
L-MC       XR          50660.0      1
X-LC       XR          46873.0      1
H-LC       AR          43183.0      1
M-MC       AR          36232.0      1

In [32]:
# notebook execution time

end_time = time.time()
execution_time = round(end_time - start_time, 0)
print(f"Notebook execution time: {execution_time} seconds")

Notebook execution time: 37.0 seconds