<a href="https://colab.research.google.com/github/ankit-rathi/Quantvesting_v2/blob/main/myStocks_Portfolio_Analysis.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
'''
!pip install pandas==2.2.2 -qq
!pip install pyxirr -qq
!pip install ta -qq
!pip install yfinance==0.2.59 -qq
'''

'\n!pip install pandas==2.2.2 -qq\n!pip install pyxirr -qq\n!pip install ta -qq\n!pip install yfinance==0.2.59 -qq\n'

In [2]:
# import libraries

import numpy as np
import pandas as pd
import datetime
import warnings
warnings.filterwarnings('ignore')
import yfinance as yfin
import ta
import matplotlib.pyplot as plt
import requests

In [3]:
# notebook start time
import time
import datetime
import pytz

start_time = time.time()

# function to print date timestamp
def print_date_time():
  tz_NY = pytz.timezone('Asia/Kolkata')
  datetime_NY = datetime.datetime.now(tz_NY)
  print("Run date time (IST):", datetime_NY.strftime("%Y-%m-%d %H:%M:%S"))

In [4]:
# function to get booked and reserved amount
def get_amt():
  # fetch the JSON data from the URL
  url = "https://raw.githubusercontent.com/ankit-rathi/Tradevesting_v1/main/data/myPortfolioAmts.json"
  response = requests.get(url)
  pf_amts = response.json()  # parse the JSON data

  # extract values from the JSON
  py_booked_amt_dm = pf_amts["py_booked_amt_dm"]
  py_booked_amt_sv = pf_amts["py_booked_amt_sv"]
  cy_booked_amt_dm = pf_amts["cy_booked_amt_dm"]
  cy_booked_amt_sv = pf_amts["cy_booked_amt_sv"]
  reserve_amt_dm = pf_amts["reserve_amt_dm"]
  reserve_amt_sv = pf_amts["reserve_amt_sv"]

  # perform calculations
  py_booked_amt = py_booked_amt_dm + py_booked_amt_sv
  cy_booked_amt = cy_booked_amt_dm + cy_booked_amt_sv
  reserve_amt = reserve_amt_dm + reserve_amt_sv
  total_booked_amt = py_booked_amt + cy_booked_amt

  return total_booked_amt, reserve_amt, cy_booked_amt, py_booked_amt

gen_output = 0

In [5]:
# function to format the amount
def format_amt(number):
    abs_number = abs(number)

    if abs_number >= 1_00_00_000:  # Crores
        formatted_amt = f"{number / 1_00_00_000:.2f} C"
    elif abs_number >= 1_00_000:  # Lakhs
        formatted_amt = f"{number / 1_00_000:.2f} L"
    elif abs_number >= 1_000:  # Thousands
        formatted_amt = f"{number / 1_000:.2f} K"
    else:
        formatted_amt = f"{number:.2f}"

    return formatted_amt

# function to set start and end date
def get_start_end_date():
  start_date = (datetime.date.today() + datetime.timedelta(days=-365)).strftime('%Y-%m-%d')
  end_date = (datetime.date.today() + datetime.timedelta(days=1)).strftime('%Y-%m-%d')
  return start_date, end_date

# function to fetch my portfolio csv
def get_mypfs_df():
  mypfs_df = pd.read_csv('https://raw.githubusercontent.com/ankit-rathi/Tradevesting_v1/main/data/myPortfolioStocks.csv')
  return mypfs_df

# function to fetch my prospects csv
def get_mypps_df():
  mypps_df = pd.read_csv('https://raw.githubusercontent.com/ankit-rathi/Tradevesting_v1/main/data/myProspectsScrips.csv')
  return mypps_df

# function to fetch screener data
def get_myscreen_df():
  myscreen_df = pd.read_csv('https://raw.githubusercontent.com/ankit-rathi/Tradevesting_v1/main/data/myScreenerDB.csv')
  return myscreen_df

# function to fetch momentum data
def get_myinvmt_df():
  myinvmt_df = pd.read_csv('https://raw.githubusercontent.com/ankit-rathi/Tradevesting_v1/main/data/myInvestments.csv')
  return myinvmt_df

# function to get the stock ids
def get_stock_ids(df_pf):
  stock_n100 = df_pf['Symbol'].unique()

  exclude = ['CADILAHC','MMTC', 'MASFIN']

  stock_ids = df_pf[~df_pf['Symbol'].isin(exclude) ]['Symbol'].unique()

  #mypf = mypf[mypf.Forecast.notnull()]
  #stock_ids = mypf['Symbol'].unique()

  #stock_ids.sort()
  return stock_ids

# get features from screener data
def get_screener_features():
  myscreen_df = get_myscreen_df()
  cols = ['Symbol', 'EPS', 'MedPE', 'ROCE%', 'ROE%', 'CapType']
  return myscreen_df[cols]

# get relative strength
def get_relative_strength(stock_list):

    # Dictionary to store stock tickers and their corresponding percentage price change
    stock_changes = {}

    # Loop through each stock and fetch its price data
    for stock in stock_list:
        try:
            # Download the stock data for the given date range
            stock_data = yfin.Ticker(stock + '.NS').history(period='1mo', interval='1d')[map(str.title, ['open', 'close', 'low', 'high', 'volume'])]

            # Calculate the percentage change for the stock
            if len(stock_data) > 0:
                start_price = stock_data['Close'].iloc[0]
                end_price = stock_data['Close'].iloc[-1]
                percent_change = round(((end_price - start_price) / start_price) * 100, 2)
                stock_changes[stock] = percent_change
            else:
                stock_changes[stock] = np.nan  # If no data is available, set to NaN

        except Exception as e:
            print(f"Error fetching data for {stock}: {e}")
            stock_changes[stock] = np.nan

    # Create a DataFrame with stock tickers and their percentage changes
    df = pd.DataFrame(list(stock_changes.items()), columns=['Symbol', 'Percent_Change'])

    # Drop any stocks with missing data (NaN values)
    df = df.dropna()

    # Calculate the percentile rank based on percentage change
    df['RSP'] = round(df['Percent_Change'].rank(pct=True) * 100, 2)
    cols = ['Symbol', 'RSP']
    df = df[cols]
    # Sort by percentile rank (optional)
    df = df.sort_values(by='RSP', ascending=False).reset_index(drop=True)

    return df

In [6]:
# function to get stock technicals
def stock_prec_dev(stock_symbol):
    #stock_symbol = 'ULTRACEMCO.NS'
    short_window = 20
    mid_window = 50
    long_window = 200
    moving_avg = 'SMA'

    start = datetime.datetime(*map(int, start_date.split('-')))
    end = datetime.datetime(*map(int, end_date.split('-')))

    stock_df = yfin.Ticker(stock_symbol + '.NS').history(period='max', interval='1d')[map(str.title, ['open', 'close', 'low', 'high', 'volume'])]

    stock_df['Max'] = round(max(stock_df['Close']),2)
    stock_df = stock_df[(stock_df.index <= end_date) & (stock_df.index >= start_date)]
    stock_df['200_SMA'] = round(stock_df['Close'].rolling(window = 200, min_periods = 1).mean(),0)
    stock_df['Dev%_200'] = round((stock_df['Close'] - stock_df['200_SMA'])*100/stock_df['200_SMA'],2)
    stock_df.dropna(axis = 0, inplace = True) # remove any null rows

    stock_df['20_SMA'] = stock_df['Close'].rolling(window=20).mean()
    stock_df['50_SMA'] = stock_df['Close'].rolling(window=50).mean()
    stock_df['Symbol'] = stock_symbol

    stock_df['Close'] = round(stock_df['Close'],2)
    stock_df['Min'] = round(min(stock_df['Close']),2)
    stock_df['RSI_14'] = ta.momentum.RSIIndicator(close=stock_df['Close'], window=14).rsi()
    stock_df['RSI_14'] = round(stock_df['RSI_14'],0)
    stock_df['Prev_Close'] = stock_df['Close'].shift(1)
    stock_df.drop(['Open', 'Low', 'High', 'Volume'], axis=1, inplace=True)
    stock_df = stock_df.tail(1)

    max_SMA = max(stock_df['20_SMA'].item(), stock_df['50_SMA'].item(), stock_df['200_SMA'].item())
    min_SMA = min(stock_df['20_SMA'].item(), stock_df['50_SMA'].item(), stock_df['200_SMA'].item())
    ABS_Spread = max_SMA - min_SMA
    stock_df['Spread%'] = round((ABS_Spread / stock_df['200_SMA'].item()) * 100,2)

    return stock_df

# function to compute stock attributes
def get_common_features(stock_ids, df_mypf):

  df_prec_dev = pd.DataFrame()
  df_tmp = get_screener_features()
  df_rs = get_relative_strength(stock_ids)

  for stock_id in stock_ids:
      tmp = stock_prec_dev(stock_id)
      tmp = tmp.reset_index()
      df_prec_dev = pd.concat([df_prec_dev, tmp], ignore_index = True)
  df_prec_dev = pd.merge(df_prec_dev, df_mypf, on= 'Symbol')
  df_prec_dev = pd.merge(df_prec_dev, df_tmp, on= 'Symbol', how='left')
  df_prec_dev = pd.merge(df_prec_dev, df_rs, on= 'Symbol', how='left')
  #print(df_prec_dev.columns)
  df_prec_dev['Curr_PE'] = round(df_prec_dev['Close']/df_prec_dev['EPS'],1)
  df_prec_dev['Dev%_PE'] = round((df_prec_dev['Curr_PE'] - df_prec_dev['MedPE'])*100/df_prec_dev['MedPE'],2)
  df_prec_dev['Conviction'] = df_prec_dev['Conviction'] + '-' + df_prec_dev['CapType']
  return df_prec_dev

# function to arrange stock features
def arrange_features(df_stocks, common_cols, diff_cols):
  df_stocks_common = df_stocks[common_cols].drop_duplicates()
  df_stocks_diff = df_stocks[diff_cols]
  df_stocks_diff['Investment'] = df_stocks_diff['AvgCost'] * df_stocks_diff['Shares']
  df_stocks_diff = df_stocks_diff.groupby(['Symbol'])[['Shares', 'Investment']].aggregate(['sum']).reset_index()
  df_stocks_diff.columns = ['Symbol', 'Shares', 'Investment']
  df_stocks_diff['AvgCost'] = round(df_stocks_diff['Investment']/df_stocks_diff['Shares'],2)
  df_stocks = pd.merge(df_stocks_diff, df_stocks_common, on='Symbol')
  return df_stocks

# plot fact distribution across dimension
def plot_pie_chart(df, dimension, fact):
  # grouping the data by category and calculating the sum of fact for each type
  grouped_data = df.groupby(dimension)[fact].sum()

  # sorting the grouped data in descending order
  grouped_data = grouped_data.sort_values(ascending=False)

  # creating a pie chart
  grouped_data.plot.pie(autopct='%1.1f%%', startangle=90, figsize=(6, 6))

  # adding a title and displaying the plot
  plt.title(f'{dimension} {fact} Distribution')
  plt.ylabel('')  # To hide the y-label
  plt.show()

In [7]:
# function to get portfolio features

def get_portfolio_features(df_common_features):

  print_date_time()
  print('-------------------')

  #df_common_features["Target"] = df_common_features["Target"].fillna(df_common_features["Max"])
  df_common_features['NTT'] = np.where(df_common_features['Strategy']== 'NTT', df_common_features["Target"], df_common_features['Max'])
  df_common_features['LTT'] = np.where(df_common_features['Strategy']== 'BTT', df_common_features["Target"], df_common_features['Max'])
  df_common_features['BOL'] = df_common_features['Min']

  tmp_df = df_common_features[df_common_features['Symbol'].isin(mypf_df[mypf_df['InPortfolio'] != 'NA'].Symbol.values)]
  print('qualified stocks: '+str(len(tmp_df['Symbol'].unique())))
  tmp_df1 = tmp_df[tmp_df['LatestQtr'] == 1]
  print('with latest results: '+str(len(tmp_df1['Symbol'].unique())))
  tmp_df1 = tmp_df1[tmp_df1['StarStock'] == 1]
  print('still star stocks: '+str(len(tmp_df1['Symbol'].unique())))
  tmp_df['Investment'] = tmp_df['AvgCost'] * tmp_df['Shares']
  tmp_df['Current'] = round(tmp_df['Close'] * tmp_df['Shares'],0)
  tmp_df['Previous'] = tmp_df['Prev_Close'] * tmp_df['Shares']
  tmp_df['EstimatedST'] = tmp_df['NTT'] * tmp_df['Shares']
  tmp_df['EstimatedLT'] = tmp_df['LTT'] * tmp_df['Shares']
  tmp_df['Current P/L'] = round((tmp_df['Current'] - tmp_df['Investment']),0)
  tmp_df['Today P/L%'] = round((tmp_df['Current'] - tmp_df['Previous'])*100/tmp_df['Previous'],2)
  tmp_df['Current P/L%'] = round((tmp_df['Current'] - tmp_df['Investment'])*100/tmp_df['Investment'],2)
  tmp_df['EstimatedST P/L%'] = round((tmp_df['EstimatedST'] - tmp_df['Investment'])*100/tmp_df['Investment'],2)
  tmp_df['EstimatedLT P/L%'] = round((tmp_df['EstimatedLT'] - tmp_df['Investment'])*100/tmp_df['Investment'],2)
  tmp_df['NTT%'] = round((tmp_df['NTT'] - tmp_df['Close'])*100/tmp_df['Close'],2)
  tmp_df['LTT%'] = round((tmp_df['LTT'] - tmp_df['Close'])*100/tmp_df['Close'],2)
  tmp_df['Gained%'] = round((tmp_df['Close'] - tmp_df['BOL'])*100/tmp_df['BOL'],2)
  investment = round(sum(tmp_df['AvgCost']*tmp_df['Shares']),0)
  current = round(sum(tmp_df['Close']*tmp_df['Shares']),0)
  tmp_df['InitAlloc%'] = round(tmp_df['Investment']*100/investment,2)
  tmp_df['CurrAlloc%'] = round(tmp_df['Current']*100/current,2)
  tmp_df['FTT'] = tmp_df['LTT']
  tmp_df.loc[tmp_df['Strategy'] == 'NTT', 'FTT'] = tmp_df['NTT']
  tmp_df['FTT%'] = tmp_df['LTT%']
  tmp_df.loc[tmp_df['Strategy'] == 'NTT', 'FTT%'] = tmp_df['NTT%']
  tmp_df['FTT Amt'] = round(tmp_df['FTT%'] * tmp_df['Current']/100,0)
  tmp_df['OTT%'] = round((tmp_df['FTT'] - tmp_df['AvgCost'])*100/tmp_df['AvgCost'],2)
  tmp_df['RRR Ind'] = round(tmp_df['Current P/L']/tmp_df['FTT Amt'],2)
  tmp_df['Risk Ind'] = round(tmp_df['Current P/L%']*tmp_df['CurrAlloc%'],0)

  return tmp_df

# function to print portfolio features
def print_portfolio_stats(df_portfolio_features, myinvmt_df):
  from pyxirr import xirr

  total_booked_amt, reserve_amt, cy_booked_amt, py_booked_amt = get_amt()

  dates = myinvmt_df['Date'].values
  dates = np.append(dates, datetime.date.today().strftime('%d-%b-%y'))
  investment = myinvmt_df['Investment'].values
  dates= pd.to_datetime(dates)

  current = round(sum(df_portfolio_features['Close']*df_portfolio_features['Shares']),0) + reserve_amt
  investment_xirr = np.append(investment, current)
  cagr = round(xirr(pd.DataFrame({"dates": dates, "amounts": investment_xirr}))*100,2)

  investment = -sum(investment)
  invested = round(sum(df_portfolio_features['AvgCost']*df_portfolio_features['Shares']),0) + reserve_amt
  previous = round(sum(df_portfolio_features['Prev_Close']*df_portfolio_features['Shares']),0) + reserve_amt
  cy_invested = investment + py_booked_amt

  today_pnl_amount = current-previous
  today_pnl_percentage = round((current-previous)*100/previous,2)

  curr_pnl_amount = current-invested
  curr_pnl_percentage = round((curr_pnl_amount)*100/(cy_invested),2)

  cy_pnl_amount = cy_booked_amt + curr_pnl_amount
  cy_pnl_percentage = round((cy_pnl_amount)*100/cy_invested,2)

  overall_pnl_amount = total_booked_amt + curr_pnl_amount
  overall_pnl_percentage = round((overall_pnl_amount)*100/investment,2)

  estimate_st = round(sum(df_portfolio_features['FTT']*df_portfolio_features['Shares']),0)  + reserve_amt
  est_st_pnl_amount = estimate_st-current
  est_st_pnl_percentage = round((est_st_pnl_amount)*100/current,2)

  estimate_lt = round(sum(df_portfolio_features['LTT']*df_portfolio_features['Shares']),0)  + reserve_amt
  est_lt_pnl_amount = estimate_lt-current
  est_lt_pnl_percentage = round((est_lt_pnl_amount)*100/current,2)

  total_profit = round(sum(df_portfolio_features[df_portfolio_features['Current P/L%'] > 0]['Current']) - sum(df_portfolio_features[df_portfolio_features['Current P/L%'] > 0]['Investment']),0)
  total_loss = round(sum(df_portfolio_features[df_portfolio_features['Current P/L%'] < 0]['Current']) - sum(df_portfolio_features[df_portfolio_features['Current P/L%'] < 0]['Investment']),0)

  cy_booked_percentage = round((cy_booked_amt)*100/current,2)
  py_booked_percentage = round((py_booked_amt)*100/investment,2)
  total_booked_percentage = round((total_booked_amt)*100/investment,2)

  print('-------------------')
  print('Initial Investment: ', format_amt(investment))
  print('CY Investment: ', format_amt(cy_invested))
  print('Reserve: ', format_amt(reserve_amt))
  print('Current: ',  format_amt(current))
  print('-------------------')
  print('Today PnL: '+ '{} ({}%)'.format(format_amt(today_pnl_amount), today_pnl_percentage))
  print('Current PnL: '+ '{} ({}%)'.format(format_amt(curr_pnl_amount), curr_pnl_percentage))
  print('CY Booked + Current PnL: '+ '{} ({}%)'.format(format_amt(cy_pnl_amount), cy_pnl_percentage))
  print('-------------------')
  print('Total profit: ', format_amt(total_profit))
  print('Total loss: ', format_amt(total_loss))
  print('-------------------')
  print('Total Booked + Current PnL: '+ '{} ({}%)'.format(format_amt(overall_pnl_amount), overall_pnl_percentage))
  print('Total Booked PnL: '+ '{} ({}%)'.format(format_amt(total_booked_amt), total_booked_percentage))
  print('Curr Year Booked PnL: '+ '{} ({}%)'.format(format_amt(cy_booked_amt), cy_booked_percentage))
  print('Prev Year Booked PnL: '+ '{} ({}%)'.format(format_amt(py_booked_amt), py_booked_percentage))
  print('===================')
  print('Est FTT: ',  format_amt(estimate_st))
  print('Est FTT PnL: '+ '{} ({}%)'.format(format_amt(est_st_pnl_amount), est_st_pnl_percentage))

  print('===================')
  print('Deployed: ', format_amt(investment))

  print('Current: ', format_amt(current))

  print('CAGR/XIRR %: '+'{}%'.format(cagr))

In [8]:
# get start and end date
start_date, end_date = get_start_end_date()

# get portfolio and prospects data
mypfs_df = get_mypfs_df()
mypps_df = get_mypps_df()
myinvmt_df = get_myinvmt_df()

# merge above datasets
mypf_df = pd.merge(mypfs_df, mypps_df, on="Symbol")

# seggregate dm and sv portfolio
dm_pf = mypf_df[mypf_df['InPortfolio'] == 'DM']
sv_pf = mypf_df[mypf_df['InPortfolio'] == 'SV']

# build portfolio stock dataframe
dm_stocks = get_stock_ids(dm_pf)
sv_stocks = get_stock_ids(sv_pf)
df_stocks = pd.concat([dm_pf,sv_pf], ignore_index = True)

# arrange common and diff stock features
common_cols = ['Symbol', 'Target', 'Criteria', 'Strategy', 'CumlRnk', 'LatestQtr', 'StarStock', 'Conviction', 'Category', 'InFolio', 'XIRR', 'MBQ']
diff_cols = ['Symbol', 'AvgCost', 'Shares']
df_stocks = arrange_features(df_stocks, common_cols, diff_cols)

# get common features
stock_ids = df_stocks['Symbol'].values
df_common_features = get_common_features(stock_ids, df_stocks)

df_common_features.reset_index(drop=True, inplace=True)
df_common_features.drop(['Date'], axis=1, inplace=True)
# get and print portfolio features
df_portfolio_features = get_portfolio_features(df_common_features)

print_portfolio_stats(df_portfolio_features, myinvmt_df)

df = df_portfolio_features
#plot_pie_chart(df, 'CapType', 'Current')
list_ox40n = list(df[df['MBQ'].str.contains('OX40N', na=False)]['Symbol'].values)

Run date time (IST): 2026-07-23 13:27:35
-------------------
qualified stocks: 92
with latest results: 31
still star stocks: 20
-------------------
Initial Investment:  1.40 C
CY Investment:  1.82 C
Reserve:  1.49 K
Current:  1.51 C
-------------------
Today PnL: -1.29 L (-0.85%)
Current PnL: -32.50 L (-17.82%)
CY Booked + Current PnL: -30.42 L (-16.68%)
-------------------
Total profit:  4.17 L
Total loss:  -36.68 L
-------------------
Total Booked + Current PnL: 12.45 L (8.92%)
Total Booked PnL: 44.95 L (32.22%)
Curr Year Booked PnL: 2.08 L (1.38%)
Prev Year Booked PnL: 42.87 L (30.73%)
===================
Est FTT:  2.55 C
Est FTT PnL: 1.04 C (69.15%)
===================
Deployed:  1.40 C
Current:  1.51 C
CAGR/XIRR %: 3.45%

In [9]:
# top 5 near their targets
cols = ['Symbol', 'Today P/L%', 'Current P/L%', 'FTT%', 'OTT%', 'FTT Amt', 'Current P/L', 'Current', 'FTT', 'Dev%_PE', 'RSI_14','Conviction', 'Spread%',  'CumlRnk', 'RRR Ind', 'CurrAlloc%', 'Gained%', 'Criteria', 'Strategy', 'Category']
df_tmp = df_portfolio_features[~df_portfolio_features['Symbol'].isin(['ENRIN','BLUSPRING','DIGITIDE'])]
df_tmp = df_tmp.sort_values(by = 'FTT Amt', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
59,PIDILITIND,-1.89,11.04,5.83,17.52,9135.0,15580.0,156690.0,1658.32,-22.28,52.0,X-LC,8.10,5.0,1.71,1.04,23.92,X40,ATH,CHEMICALS
49,JSWINFRA,-5.67,10.64,5.23,16.43,12833.0,23601.0,245375.0,342.00,-5.05,50.0,X-MC,18.94,61.0,1.84,1.63,39.12,X40N,NTT,REALTY
73,SONACOMS,-0.21,25.41,10.59,38.69,13435.0,25707.0,126866.0,801.69,-0.62,79.0,M-MC,25.57,193.0,1.91,0.84,79.99,AR,ATH,AUTO
56,MEDANTA,3.10,18.41,7.35,27.12,15363.0,32497.0,209014.0,1486.00,14.77,67.0,X-SC,11.32,87.0,2.12,1.39,44.02,XY24,NTT,HEALTHCARE
83,TTKPRESTIG,-1.68,-16.14,19.35,0.09,16354.0,-16262.0,84515.0,770.00,96.16,59.0,M-SC,10.20,250.0,-0.99,0.56,50.49,OX40N,NTT,DURABLES

In [10]:
# top 5 today
df_tmp = df_portfolio_features.sort_values(by = 'Today P/L%', ascending=False)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
67,ROUTE,11.71,-51.17,244.33,68.16,158773.0,-68083.0,64983.0,2215.45,-60.53,75.0,H-SC,9.08,141.0,-0.43,0.43,54.81,SR,ATH,IT
77,TANLA,8.25,-31.29,216.20,117.25,402203.0,-84728.0,186033.0,1922.32,-30.60,67.0,H-SC,5.45,147.0,-0.21,1.23,62.88,AR,ATH,IT
89,WHIRLPOOL,3.50,-37.17,189.56,81.92,136716.0,-42675.0,72123.0,2270.00,-63.21,47.0,M-SC,15.53,210.0,-0.31,0.48,3.51,XR,NTT,DURABLES
62,RAJOOENG,3.15,-46.05,158.77,39.61,87800.0,-47200.0,55300.0,143.10,-63.52,64.0,H-SC,20.52,136.0,-0.54,0.37,18.47,AR,ATH,MISC
56,MEDANTA,3.10,18.41,7.35,27.12,15363.0,32497.0,209014.0,1486.00,14.77,67.0,X-SC,11.32,87.0,2.12,1.39,44.02,XY24,NTT,HEALTHCARE

In [11]:
# bottom 5 today
df_tmp = df_portfolio_features.sort_values(by = 'Today P/L%', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
44,INDUSINDBK,-6.23,-25.98,79.52,32.89,45446.0,-20056.0,57151.0,1800.00,-368.91,53.0,L-MC,13.22,258.0,-0.44,0.38,40.90,XR,NTT,BANKS
49,JSWINFRA,-5.67,10.64,5.23,16.43,12833.0,23601.0,245375.0,342.00,-5.05,50.0,X-MC,18.94,61.0,1.84,1.63,39.12,X40N,NTT,REALTY
17,CIPLA,-4.39,10.88,20.34,33.43,34543.0,16669.0,169830.0,1648.14,-14.32,37.0,X-LC,3.01,18.0,0.48,1.13,15.94,X40N,ATH,PHARMA
50,KANSAINER,-3.86,-35.11,74.87,13.47,131013.0,-94680.0,174987.0,340.00,-44.14,35.0,H-SC,4.83,162.0,-0.72,1.16,23.68,XY24,NTT,PAINTS
88,VOLTAS,-3.81,2.28,41.96,45.20,82288.0,4368.0,196110.0,1856.00,17.07,48.0,X-MC,5.31,79.0,0.05,1.30,7.48,XY25,NTT,AC

In [12]:
# top 5 to exit based on CumlRnk
df_tmp = df_portfolio_features[~df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])]
df_tmp = df_tmp[(df_tmp['Current P/L%'] > -1) & (df_tmp['Current P/L%'] < 1)].sort_values(by = 'CumlRnk', ascending=False)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
72,SIS,-0.69,0.68,20.44,21.26,22850.0,760.0,111792.0,528.0,2669.95,58.0,H-SC,24.6,168.0,0.03,0.74,66.22,OX40N,NTT,MISC

In [13]:
# OX40N stocks to exit
df_tmp = df_portfolio_features[(df_portfolio_features['Symbol'].isin(list_ox40n))].sort_values(by = 'Current P/L%', ascending=False)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
25,FINCABLES,-3.00,24.69,66.74,107.91,122870.0,36458.0,184102.0,1641.55,12.13,36.0,M-SC,20.79,220.0,0.30,1.22,38.51,OX40N,ATH,CABLES
72,SIS,-0.69,0.68,20.44,21.26,22850.0,760.0,111792.0,528.00,2669.95,58.0,H-SC,24.60,168.0,0.03,0.74,66.22,OX40N,NTT,MISC
83,TTKPRESTIG,-1.68,-16.14,19.35,0.09,16354.0,-16262.0,84515.0,770.00,96.16,59.0,M-SC,10.20,250.0,-0.99,0.56,50.49,OX40N,NTT,DURABLES
16,CERA,-2.00,-20.15,55.16,23.89,77472.0,-35453.0,140450.0,9475.00,-22.91,48.0,H-SC,14.91,153.0,-0.46,0.93,36.53,OX40N,NTT,CERAMICS
43,INDIGOPNTS,-2.93,-25.70,34.62,0.02,44899.0,-44867.0,129692.0,1408.00,97.54,51.0,M-SC,3.66,222.0,-1.00,0.86,47.14,OX40N,NTT,PAINTS

In [14]:
# top 5 to book for rotation
df_tmp = df_portfolio_features[(df_portfolio_features['Current P/L%'] > 20) ].sort_values(by = 'CumlRnk', ascending=False)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
25,FINCABLES,-3.00,24.69,66.74,107.91,122870.0,36458.0,184102.0,1641.55,12.13,36.0,M-SC,20.79,220.0,0.30,1.22,38.51,OX40N,ATH,CABLES
73,SONACOMS,-0.21,25.41,10.59,38.69,13435.0,25707.0,126866.0,801.69,-0.62,79.0,M-MC,25.57,193.0,1.91,0.84,79.99,AR,ATH,AUTO
68,SATIN,-1.08,41.68,7.17,51.83,28067.0,115162.0,391446.0,274.00,27.46,55.0,H-SC,44.94,159.0,4.10,2.60,90.69,XY24,NTT,FINANCE
60,QUESS,-1.45,21.11,43.58,73.90,56367.0,22548.0,129341.0,424.00,-34.99,66.0,X-SC,32.32,80.0,0.40,0.86,76.32,XY24,NTT,MISC

In [15]:
# top 5 to monitor for exit
df_tmp = df_portfolio_features[~df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])]
df_tmp = df_tmp[(df_tmp['Current P/L%'] > 0) ].sort_values(by = 'Dev%_PE', ascending=False)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
72,SIS,-0.69,0.68,20.44,21.26,22850.0,760.0,111792.0,528.00,2669.95,58.0,H-SC,24.60,168.0,0.03,0.74,66.22,OX40N,NTT,MISC
75,SURYODAY,-1.98,6.31,15.73,23.03,29946.0,11302.0,190373.0,216.00,108.33,59.0,H-SC,22.55,166.0,0.38,1.26,61.59,XR,NTT,BANKS
74,STARHEALTH,-1.97,11.66,31.88,47.26,100076.0,32792.0,313915.0,761.00,76.17,50.0,H-SC,18.90,173.0,0.33,2.08,36.23,XY24,NTT,INSURANCE
68,SATIN,-1.08,41.68,7.17,51.83,28067.0,115162.0,391446.0,274.00,27.46,55.0,H-SC,44.94,159.0,4.10,2.60,90.69,XY24,NTT,FINANCE
25,FINCABLES,-3.00,24.69,66.74,107.91,122870.0,36458.0,184102.0,1641.55,12.13,36.0,M-SC,20.79,220.0,0.30,1.22,38.51,OX40N,ATH,CABLES

In [16]:
# top 5 to book for rotation from weak conviction
df_tmp = df_portfolio_features[~df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])]
df_tmp = df_tmp[~df_tmp['Criteria'].isin(['XY25','XY24','X40', 'X40N'])].sort_values(by = 'RRR Ind', ascending=False)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
73,SONACOMS,-0.21,25.41,10.59,38.69,13435.0,25707.0,126866.0,801.69,-0.62,79.0,M-MC,25.57,193.0,1.91,0.84,79.99,AR,ATH,AUTO
91,ZYDUSLIFE,-1.11,17.45,15.48,35.63,38104.0,36576.0,246150.0,1286.17,2.25,47.0,H-MC,17.23,120.0,0.96,1.63,29.42,AR,ATH,PHARMA
75,SURYODAY,-1.98,6.31,15.73,23.03,29946.0,11302.0,190373.0,216.00,108.33,59.0,H-SC,22.55,166.0,0.38,1.26,61.59,XR,NTT,BANKS
25,FINCABLES,-3.00,24.69,66.74,107.91,122870.0,36458.0,184102.0,1641.55,12.13,36.0,M-SC,20.79,220.0,0.30,1.22,38.51,OX40N,ATH,CABLES
72,SIS,-0.69,0.68,20.44,21.26,22850.0,760.0,111792.0,528.00,2669.95,58.0,H-SC,24.60,168.0,0.03,0.74,66.22,OX40N,NTT,MISC

In [17]:
# top 5 to accumulate based on lowest RSI_14
df_tmp = df_portfolio_features[df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])].sort_values(by = 'RSI_14', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
39,ICICIGI,-1.15,-14.97,39.81,18.89,67741.0,-29947.0,170162.0,2244.41,-28.41,31.0,X-MC,6.21,66.0,-0.44,1.13,0.00,X40,ATH,INSURANCE
87,VBL,0.01,-7.42,46.23,35.37,135174.0,-23447.0,292395.0,670.16,-18.33,31.0,X-LC,7.19,13.0,-0.17,1.94,20.18,X40N,ATH,FMCG
81,TMPV,-0.59,-25.85,84.19,36.58,222142.0,-91983.0,263858.0,600.00,-84.72,34.0,X-LC,7.65,4.0,-0.41,1.75,10.89,XY24,NTT,AUTO
34,HDFCBANK,-1.20,-10.98,44.19,28.37,92404.0,-25779.0,209106.0,1073.00,-24.48,34.0,X-LC,10.79,26.0,-0.28,1.39,3.40,X40,BTT,BANKS
17,CIPLA,-4.39,10.88,20.34,33.43,34543.0,16669.0,169830.0,1648.14,-14.32,37.0,X-LC,3.01,18.0,0.48,1.13,15.94,X40N,ATH,PHARMA

In [18]:
# top 5 to accumulate based on Spread and CumlRnk
df_tmp = df_portfolio_features[df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])]
df_tmp = df_tmp[(df_tmp['CumlRnk'] < 100)].sort_values(by = 'Spread%', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
11,BERGEPAINT,-2.54,-9.04,37.78,25.32,88570.0,-23313.0,234436.0,680.00,-13.99,44.0,X-MC,1.75,68.0,-0.26,1.56,22.01,XY24,NTT,PAINTS
23,DMART,1.52,-2.98,33.58,29.60,81317.0,-7440.0,242160.0,5391.45,-18.18,46.0,X-LC,1.94,14.0,-0.09,1.61,10.69,X40N,ATH,FMCG
19,COLPAL,-0.29,-20.76,76.51,39.86,159661.0,-54685.0,208680.0,3683.41,-4.06,56.0,X-MC,1.97,62.0,-0.34,1.39,18.04,XY25,ATH,FMCG
1,ABBOTINDIA,-0.17,-3.55,22.42,18.07,38675.0,-6355.0,172500.0,35195.00,-17.90,75.0,X-MC,2.70,58.0,-0.16,1.14,14.18,X40,ATH,PHARMA
17,CIPLA,-4.39,10.88,20.34,33.43,34543.0,16669.0,169830.0,1648.14,-14.32,37.0,X-LC,3.01,18.0,0.48,1.13,15.94,X40N,ATH,PHARMA

In [19]:
# top 5 to accumulate based on lowest Gained%
df_tmp = df_portfolio_features[df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])].sort_values(by = 'Gained%', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
39,ICICIGI,-1.15,-14.97,39.81,18.89,67741.0,-29947.0,170162.0,2244.41,-28.41,31.0,X-MC,6.21,66.0,-0.44,1.13,0.00,X40,ATH,INSURANCE
65,RELIANCE,-1.15,-18.23,53.24,25.30,87484.0,-36643.0,164320.0,1952.00,-20.42,41.0,X-LC,7.53,21.0,-0.42,1.09,1.19,XY25,BTT,REFINERIES
35,HDFCLIFE,-0.51,-10.00,47.45,32.71,63974.0,-14976.0,134824.0,811.41,-29.79,39.0,X-LC,15.63,31.0,-0.23,0.89,1.29,X40,ATH,INSURANCE
47,ITC,-0.20,-26.18,61.28,19.06,153877.0,-89062.0,251104.0,452.00,-59.56,42.0,X-LC,12.68,1.0,-0.58,1.67,1.71,X40,NTT,FMCG
58,PGHH,0.00,-32.56,95.75,32.01,137872.0,-69528.0,143992.0,17616.87,-54.37,51.0,X-MC,19.95,57.0,-0.50,0.96,3.20,X40,ATH,FMCG

In [20]:
# top 5 to accumulate based on lowest CurrAlloc%
df_tmp = df_portfolio_features[df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])].sort_values(by = 'CurrAlloc%', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
10,BATAINDIA,-3.20,-56.64,211.84,35.20,118181.0,-72882.0,55788.0,2096.00,-26.79,43.0,X-SC,17.61,91.0,-0.62,0.37,10.64,X40,NTT,FOOTWEAR
64,RELAXO,-1.86,-48.97,198.44,52.31,147006.0,-71079.0,74081.0,1176.00,-45.70,52.0,X-SC,11.52,92.0,-0.48,0.49,65.64,X40N,NTT,FOOTWEAR
60,QUESS,-1.45,21.11,43.58,73.90,56367.0,22548.0,129341.0,424.00,-34.99,66.0,X-SC,32.32,80.0,0.40,0.86,76.32,XY24,NTT,MISC
35,HDFCLIFE,-0.51,-10.00,47.45,32.71,63974.0,-14976.0,134824.0,811.41,-29.79,39.0,X-LC,15.63,31.0,-0.23,0.89,1.29,X40,ATH,INSURANCE
28,GODREJCP,1.34,-4.39,37.51,31.47,53296.0,-6530.0,142084.0,1469.04,0.54,54.0,X-LC,6.29,32.0,-0.12,0.94,9.02,X40N,ATH,FMCG

In [21]:
# top 5 to accumulate based on CumlRnk
df_tmp = df_portfolio_features.sort_values(by = 'CumlRnk', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
47,ITC,-0.20,-26.18,61.28,19.06,153877.0,-89062.0,251104.0,452.00,-59.56,42.0,X-LC,12.68,1.0,-0.58,1.67,1.71,X40,NTT,FMCG
79,TCS,0.89,-34.60,89.90,24.20,272392.0,-160279.0,302994.0,4230.71,-44.61,58.0,X-LC,19.48,2.0,-0.59,2.01,12.99,X40,ATH,IT
45,INFY,-0.87,-29.00,89.09,34.24,197903.0,-90750.0,222138.0,1972.00,-44.12,42.0,X-LC,20.75,3.0,-0.46,1.47,5.85,X40,NTT,IT
81,TMPV,-0.59,-25.85,84.19,36.58,222142.0,-91983.0,263858.0,600.00,-84.72,34.0,X-LC,7.65,4.0,-0.41,1.75,10.89,XY24,NTT,AUTO
59,PIDILITIND,-1.89,11.04,5.83,17.52,9135.0,15580.0,156690.0,1658.32,-22.28,52.0,X-LC,8.10,5.0,1.71,1.04,23.92,X40,ATH,CHEMICALS

In [22]:
# top 5 for average up
df_tmp = df_portfolio_features[(df_portfolio_features['Dev%_200'] > 5)].sort_values(by = 'CurrAlloc%', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
44,INDUSINDBK,-6.23,-25.98,79.52,32.89,45446.0,-20056.0,57151.0,1800.00,-368.91,53.0,L-MC,13.22,258.0,-0.44,0.38,40.90,XR,NTT,BANKS
67,ROUTE,11.71,-51.17,244.33,68.16,158773.0,-68083.0,64983.0,2215.45,-60.53,75.0,H-SC,9.08,141.0,-0.43,0.43,54.81,SR,ATH,IT
64,RELAXO,-1.86,-48.97,198.44,52.31,147006.0,-71079.0,74081.0,1176.00,-45.70,52.0,X-SC,11.52,92.0,-0.48,0.49,65.64,X40N,NTT,FOOTWEAR
3,ALKYLAMINE,-1.14,-22.66,148.95,92.54,116312.0,-22875.0,78088.0,4520.85,-17.24,49.0,H-SC,11.92,142.0,-0.20,0.52,48.28,SR,ATH,CHEMICALS
83,TTKPRESTIG,-1.68,-16.14,19.35,0.09,16354.0,-16262.0,84515.0,770.00,96.16,59.0,M-SC,10.20,250.0,-0.99,0.56,50.49,OX40N,NTT,DURABLES

In [23]:
# top 5 RSP
df_tmp = df_portfolio_features.sort_values(by = 'RSP', ascending=False)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
67,ROUTE,11.71,-51.17,244.33,68.16,158773.0,-68083.0,64983.0,2215.45,-60.53,75.0,H-SC,9.08,141.0,-0.43,0.43,54.81,SR,ATH,IT
73,SONACOMS,-0.21,25.41,10.59,38.69,13435.0,25707.0,126866.0,801.69,-0.62,79.0,M-MC,25.57,193.0,1.91,0.84,79.99,AR,ATH,AUTO
60,QUESS,-1.45,21.11,43.58,73.90,56367.0,22548.0,129341.0,424.00,-34.99,66.0,X-SC,32.32,80.0,0.40,0.86,76.32,XY24,NTT,MISC
77,TANLA,8.25,-31.29,216.20,117.25,402203.0,-84728.0,186033.0,1922.32,-30.60,67.0,H-SC,5.45,147.0,-0.21,1.23,62.88,AR,ATH,IT
83,TTKPRESTIG,-1.68,-16.14,19.35,0.09,16354.0,-16262.0,84515.0,770.00,96.16,59.0,M-SC,10.20,250.0,-0.99,0.56,50.49,OX40N,NTT,DURABLES

In [24]:
# Top N allocation
df_tmp = df_portfolio_features.sort_values(by = 'CurrAlloc%', ascending=False)
top_n_values = [10, 25, 50]

sum_df = pd.DataFrame({
    'Top_N': top_n_values,
    'Sum_Alloc%': [df_tmp['CurrAlloc%'].head(n).sum() for n in top_n_values]
})

sum_df

   Top_N  Sum_Alloc%
0     10       19.16
1     25       42.24
2     50       72.57

In [25]:
# market-cap-wise allocation
df_tmp = df_portfolio_features[cols]
df_tmp.groupby(df_tmp['Conviction'].str[-2:])['CurrAlloc%'].sum().sort_values(ascending=False)

Conviction
SC    43.42
LC    30.15
MC    26.41
Name: CurrAlloc%, dtype: float64

In [26]:
# criteria-wise allocation
df_portfolio_features.groupby('Criteria')['CurrAlloc%'].sum().sort_values(ascending=False)

Criteria
XY24     27.29
X40      24.86
X40N     17.41
XR        8.87
AR        7.09
OX40N     6.99
XY25      6.52
SR        0.95
Name: CurrAlloc%, dtype: float64

In [27]:
# conviction-wise allocation
df_portfolio_features.groupby('Conviction')['CurrAlloc%'].sum().sort_values(ascending=False)

Conviction
X-LC    28.14
H-SC    22.77
X-MC    21.18
X-SC    10.18
M-SC     9.92
H-MC     2.70
M-MC     2.15
H-LC     1.21
M-LC     0.80
L-SC     0.55
L-MC     0.38
Name: CurrAlloc%, dtype: float64

In [28]:
# sector-wise stats
df_tmp = df_portfolio_features.groupby('Category')[['CurrAlloc%', 'Current', 'Current P/L', 'FTT Amt']].sum().sort_values(by=['Current', 'Current P/L'], ascending=False)
df_tmp['Current P/L%'] = round(df_tmp['Current P/L'] * 100 / df_tmp['Current'], 2)
df_tmp['FTT%'] = round(df_tmp['FTT Amt'] * 100 / df_tmp['Current'], 2)
cols = ['CurrAlloc%', 'Current P/L%', 'FTT%']
df_tmp[cols].sort_values(by=['CurrAlloc%'], ascending=False)

               CurrAlloc%  Current P/L%    FTT%
Category
FMCG                14.39        -22.21   65.07
FINANCE             11.23         -9.05   56.31
IT                  10.26        -45.44  117.41
MISC                 7.29        -22.20   74.63
AUTO                 6.68         -8.63   49.14
BANKS                5.46        -10.38   61.39
PAINTS               5.39        -21.44   42.15
PHARMA               5.25          6.38   22.61
INSURANCE            5.18         -5.88   41.60
ELECTRICAL           4.16        -12.90   52.61
CHEMICALS            2.15        -25.13   99.00
HEALTHCARE           2.14        -10.91   39.85
APPARELS             1.87          4.70   27.31
AC                   1.79        -18.44   50.56
FOOTWEAR             1.69        -73.08  142.49
DURABLES             1.63        -57.25   95.51
REALTY               1.63          9.62    5.23
BREWERIES            1.61          3.35   16.72
TRAVEL               1.51        -96.04  194.20
CERAMICS             1.42        -43.24   86.75
ENGINEERING          1.24        -29.99   89.45
CABLES               1.22         19.80   66.74
JEWELLERY            1.12        -90.19  156.26
REFINERIES           1.09        -22.30   53.24
CEMENT               1.06        -67.12  192.15
ENTERTAINMENT        0.72        -79.77  186.98
TEXTILES             0.41        -48.10   90.33
HOTELS               0.39        -92.76  160.76

In [29]:
# money to be made criteria-wise
df_portfolio_features.groupby('Criteria')['FTT Amt'].agg(['sum', 'count']).sort_values(by='sum', ascending=False)

                sum  count
Criteria
XY24      3486462.0     21
X40       1923934.0     19
XR        1339788.0     13
AR        1104439.0      9
X40N      1096564.0     13
OX40N      737528.0     10
XY25       454641.0      5
SR         275085.0      2

In [30]:
# money to be made conviction-wise
df_portfolio_features.groupby('Conviction')['FTT Amt'].agg(['sum', 'count']).sort_values(by='sum', ascending=False)

                  sum  count
Conviction
H-SC        3340833.0     24
X-LC        2029316.0     21
X-MC        1528357.0     15
M-SC        1422436.0     14
X-SC        1270007.0      9
H-MC         290467.0      2
L-SC         208118.0      2
M-LC         170666.0      1
M-MC          62087.0      2
H-LC          50708.0      1
L-MC          45446.0      1

In [31]:
# money to be made criteria and conviction-wise
df_portfolio_features.groupby(['Conviction', 'Criteria'])['FTT Amt'].agg(['sum', 'count']).sort_values(by='sum', ascending=False)

                           sum  count
Conviction Criteria
X-LC       X40       1051561.0     10
H-SC       XY24      1042332.0      6
           AR         925455.0      5
M-SC       XY24       832680.0      6
H-SC       XR         793888.0      7
X-SC       XY24       744672.0      4
X-MC       X40        659148.0      7
X-LC       X40N       397499.0      6
X-MC       X40N       386955.0      4
X-LC       XY24       374110.0      2
M-SC       OX40N      320034.0      5
X-SC       X40N       312110.0      3
H-SC       OX40N      304073.0      4
           SR         275085.0      2
H-MC       XY24       252363.0      1
X-MC       XY25       241949.0      2
           XY24       240305.0      2
X-SC       X40        213225.0      2
M-SC       XR         192985.0      2
M-LC       XR         170666.0      1
X-LC       XY25       164040.0      2
L-SC       OX40N      113421.0      1
           XR          94697.0      1
M-SC       AR          76737.0      1
H-LC       AR          50708.0      1
M-MC       XY25        48652.0      1
L-MC       XR          45446.0      1
X-LC       XR          42106.0      1
H-MC       AR          38104.0      1
M-MC       AR          13435.0      1

In [32]:
# notebook execution time

end_time = time.time()
execution_time = round(end_time - start_time, 0)
print(f"Notebook execution time: {execution_time} seconds")

Notebook execution time: 42.0 seconds