<a href="https://colab.research.google.com/github/ankit-rathi/Quantvesting_v2/blob/main/myStocks_Portfolio_Analysis.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
'''
!pip install pandas==2.2.2 -qq
!pip install pyxirr -qq
!pip install ta -qq
!pip install yfinance==0.2.59 -qq
'''

'\n!pip install pandas==2.2.2 -qq\n!pip install pyxirr -qq\n!pip install ta -qq\n!pip install yfinance==0.2.59 -qq\n'

In [2]:
# import libraries

import numpy as np
import pandas as pd
import datetime
import warnings
warnings.filterwarnings('ignore')
import yfinance as yfin
import ta
import matplotlib.pyplot as plt
import requests

In [3]:
# notebook start time
import time
import datetime
import pytz

start_time = time.time()

# function to print date timestamp
def print_date_time():
  tz_NY = pytz.timezone('Asia/Kolkata')
  datetime_NY = datetime.datetime.now(tz_NY)
  print("Run date time (IST):", datetime_NY.strftime("%Y-%m-%d %H:%M:%S"))

In [4]:
# function to get booked and reserved amount
def get_amt():
  # fetch the JSON data from the URL
  url = "https://raw.githubusercontent.com/ankit-rathi/Tradevesting_v1/main/data/myPortfolioAmts.json"
  response = requests.get(url)
  pf_amts = response.json()  # parse the JSON data

  # extract values from the JSON
  py_booked_amt_dm = pf_amts["py_booked_amt_dm"]
  py_booked_amt_sv = pf_amts["py_booked_amt_sv"]
  cy_booked_amt_dm = pf_amts["cy_booked_amt_dm"]
  cy_booked_amt_sv = pf_amts["cy_booked_amt_sv"]
  reserve_amt_dm = pf_amts["reserve_amt_dm"]
  reserve_amt_sv = pf_amts["reserve_amt_sv"]

  # perform calculations
  py_booked_amt = py_booked_amt_dm + py_booked_amt_sv
  cy_booked_amt = cy_booked_amt_dm + cy_booked_amt_sv
  reserve_amt = reserve_amt_dm + reserve_amt_sv
  total_booked_amt = py_booked_amt + cy_booked_amt

  return total_booked_amt, reserve_amt, cy_booked_amt, py_booked_amt

gen_output = 0

In [5]:
# function to format the amount
def format_amt(number):
    abs_number = abs(number)

    if abs_number >= 1_00_00_000:  # Crores
        formatted_amt = f"{number / 1_00_00_000:.2f} C"
    elif abs_number >= 1_00_000:  # Lakhs
        formatted_amt = f"{number / 1_00_000:.2f} L"
    elif abs_number >= 1_000:  # Thousands
        formatted_amt = f"{number / 1_000:.2f} K"
    else:
        formatted_amt = f"{number:.2f}"

    return formatted_amt

# function to set start and end date
def get_start_end_date():
  start_date = (datetime.date.today() + datetime.timedelta(days=-365)).strftime('%Y-%m-%d')
  end_date = (datetime.date.today() + datetime.timedelta(days=1)).strftime('%Y-%m-%d')
  return start_date, end_date

# function to fetch my portfolio csv
def get_mypfs_df():
  mypfs_df = pd.read_csv('https://raw.githubusercontent.com/ankit-rathi/Tradevesting_v1/main/data/myPortfolioStocks.csv')
  return mypfs_df

# function to fetch my prospects csv
def get_mypps_df():
  mypps_df = pd.read_csv('https://raw.githubusercontent.com/ankit-rathi/Tradevesting_v1/main/data/myProspectsScrips.csv')
  return mypps_df

# function to fetch screener data
def get_myscreen_df():
  myscreen_df = pd.read_csv('https://raw.githubusercontent.com/ankit-rathi/Tradevesting_v1/main/data/myScreenerDB.csv')
  return myscreen_df

# function to fetch momentum data
def get_myinvmt_df():
  myinvmt_df = pd.read_csv('https://raw.githubusercontent.com/ankit-rathi/Tradevesting_v1/main/data/myInvestments.csv')
  return myinvmt_df

# function to get the stock ids
def get_stock_ids(df_pf):
  stock_n100 = df_pf['Symbol'].unique()

  exclude = ['CADILAHC','MMTC', 'MASFIN']

  stock_ids = df_pf[~df_pf['Symbol'].isin(exclude) ]['Symbol'].unique()

  #mypf = mypf[mypf.Forecast.notnull()]
  #stock_ids = mypf['Symbol'].unique()

  #stock_ids.sort()
  return stock_ids

# get features from screener data
def get_screener_features():
  myscreen_df = get_myscreen_df()
  cols = ['Symbol', 'EPS', 'MedPE', 'ROCE%', 'ROE%', 'CapType']
  return myscreen_df[cols]

# get relative strength
def get_relative_strength(stock_list):

    # Dictionary to store stock tickers and their corresponding percentage price change
    stock_changes = {}

    # Loop through each stock and fetch its price data
    for stock in stock_list:
        try:
            # Download the stock data for the given date range
            stock_data = yfin.Ticker(stock + '.NS').history(period='1mo', interval='1d')[map(str.title, ['open', 'close', 'low', 'high', 'volume'])]

            # Calculate the percentage change for the stock
            if len(stock_data) > 0:
                start_price = stock_data['Close'].iloc[0]
                end_price = stock_data['Close'].iloc[-1]
                percent_change = round(((end_price - start_price) / start_price) * 100, 2)
                stock_changes[stock] = percent_change
            else:
                stock_changes[stock] = np.nan  # If no data is available, set to NaN

        except Exception as e:
            print(f"Error fetching data for {stock}: {e}")
            stock_changes[stock] = np.nan

    # Create a DataFrame with stock tickers and their percentage changes
    df = pd.DataFrame(list(stock_changes.items()), columns=['Symbol', 'Percent_Change'])

    # Drop any stocks with missing data (NaN values)
    df = df.dropna()

    # Calculate the percentile rank based on percentage change
    df['RSP'] = round(df['Percent_Change'].rank(pct=True) * 100, 2)
    cols = ['Symbol', 'RSP']
    df = df[cols]
    # Sort by percentile rank (optional)
    df = df.sort_values(by='RSP', ascending=False).reset_index(drop=True)

    return df

In [6]:
# function to get stock technicals
def stock_prec_dev(stock_symbol):
    #stock_symbol = 'ULTRACEMCO.NS'
    short_window = 20
    mid_window = 50
    long_window = 200
    moving_avg = 'SMA'

    start = datetime.datetime(*map(int, start_date.split('-')))
    end = datetime.datetime(*map(int, end_date.split('-')))

    stock_df = yfin.Ticker(stock_symbol + '.NS').history(period='max', interval='1d')[map(str.title, ['open', 'close', 'low', 'high', 'volume'])]

    stock_df['Max'] = round(max(stock_df['Close']),2)
    stock_df = stock_df[(stock_df.index <= end_date) & (stock_df.index >= start_date)]
    stock_df['200_SMA'] = round(stock_df['Close'].rolling(window = 200, min_periods = 1).mean(),0)
    stock_df['Dev%_200'] = round((stock_df['Close'] - stock_df['200_SMA'])*100/stock_df['200_SMA'],2)
    stock_df.dropna(axis = 0, inplace = True) # remove any null rows

    stock_df['20_SMA'] = stock_df['Close'].rolling(window=20).mean()
    stock_df['50_SMA'] = stock_df['Close'].rolling(window=50).mean()
    stock_df['Symbol'] = stock_symbol

    stock_df['Close'] = round(stock_df['Close'],2)
    stock_df['Min'] = round(min(stock_df['Close']),2)
    stock_df['RSI_14'] = ta.momentum.RSIIndicator(close=stock_df['Close'], window=14).rsi()
    stock_df['RSI_14'] = round(stock_df['RSI_14'],0)
    stock_df['Prev_Close'] = stock_df['Close'].shift(1)
    stock_df.drop(['Open', 'Low', 'High', 'Volume'], axis=1, inplace=True)
    stock_df = stock_df.tail(1)

    max_SMA = max(stock_df['20_SMA'].item(), stock_df['50_SMA'].item(), stock_df['200_SMA'].item())
    min_SMA = min(stock_df['20_SMA'].item(), stock_df['50_SMA'].item(), stock_df['200_SMA'].item())
    ABS_Spread = max_SMA - min_SMA
    stock_df['Spread%'] = round((ABS_Spread / stock_df['200_SMA'].item()) * 100,2)

    return stock_df

# function to compute stock attributes
def get_common_features(stock_ids, df_mypf):

  df_prec_dev = pd.DataFrame()
  df_tmp = get_screener_features()
  df_rs = get_relative_strength(stock_ids)

  for stock_id in stock_ids:
      tmp = stock_prec_dev(stock_id)
      tmp = tmp.reset_index()
      df_prec_dev = pd.concat([df_prec_dev, tmp], ignore_index = True)
  df_prec_dev = pd.merge(df_prec_dev, df_mypf, on= 'Symbol')
  df_prec_dev = pd.merge(df_prec_dev, df_tmp, on= 'Symbol', how='left')
  df_prec_dev = pd.merge(df_prec_dev, df_rs, on= 'Symbol', how='left')
  #print(df_prec_dev.columns)
  df_prec_dev['Curr_PE'] = round(df_prec_dev['Close']/df_prec_dev['EPS'],1)
  df_prec_dev['Dev%_PE'] = round((df_prec_dev['Curr_PE'] - df_prec_dev['MedPE'])*100/df_prec_dev['MedPE'],2)
  df_prec_dev['Conviction'] = df_prec_dev['Conviction'] + '-' + df_prec_dev['CapType']
  return df_prec_dev

# function to arrange stock features
def arrange_features(df_stocks, common_cols, diff_cols):
  df_stocks_common = df_stocks[common_cols].drop_duplicates()
  df_stocks_diff = df_stocks[diff_cols]
  df_stocks_diff['Investment'] = df_stocks_diff['AvgCost'] * df_stocks_diff['Shares']
  df_stocks_diff = df_stocks_diff.groupby(['Symbol'])[['Shares', 'Investment']].aggregate(['sum']).reset_index()
  df_stocks_diff.columns = ['Symbol', 'Shares', 'Investment']
  df_stocks_diff['AvgCost'] = round(df_stocks_diff['Investment']/df_stocks_diff['Shares'],2)
  df_stocks = pd.merge(df_stocks_diff, df_stocks_common, on='Symbol')
  return df_stocks

# plot fact distribution across dimension
def plot_pie_chart(df, dimension, fact):
  # grouping the data by category and calculating the sum of fact for each type
  grouped_data = df.groupby(dimension)[fact].sum()

  # sorting the grouped data in descending order
  grouped_data = grouped_data.sort_values(ascending=False)

  # creating a pie chart
  grouped_data.plot.pie(autopct='%1.1f%%', startangle=90, figsize=(6, 6))

  # adding a title and displaying the plot
  plt.title(f'{dimension} {fact} Distribution')
  plt.ylabel('')  # To hide the y-label
  plt.show()

In [7]:
# function to get portfolio features

def get_portfolio_features(df_common_features):

  print_date_time()
  print('-------------------')

  #df_common_features["Target"] = df_common_features["Target"].fillna(df_common_features["Max"])
  df_common_features['NTT'] = np.where(df_common_features['Strategy']== 'NTT', df_common_features["Target"], df_common_features['Max'])
  df_common_features['LTT'] = np.where(df_common_features['Strategy']== 'BTT', df_common_features["Target"], df_common_features['Max'])
  df_common_features['BOL'] = df_common_features['Min']

  tmp_df = df_common_features[df_common_features['Symbol'].isin(mypf_df[mypf_df['InPortfolio'] != 'NA'].Symbol.values)]
  print('qualified stocks: '+str(len(tmp_df['Symbol'].unique())))
  tmp_df1 = tmp_df[tmp_df['LatestQtr'] == 1]
  print('with latest results: '+str(len(tmp_df1['Symbol'].unique())))
  tmp_df1 = tmp_df1[tmp_df1['StarStock'] == 1]
  print('still star stocks: '+str(len(tmp_df1['Symbol'].unique())))
  tmp_df['Investment'] = tmp_df['AvgCost'] * tmp_df['Shares']
  tmp_df['Current'] = round(tmp_df['Close'] * tmp_df['Shares'],0)
  tmp_df['Previous'] = tmp_df['Prev_Close'] * tmp_df['Shares']
  tmp_df['EstimatedST'] = tmp_df['NTT'] * tmp_df['Shares']
  tmp_df['EstimatedLT'] = tmp_df['LTT'] * tmp_df['Shares']
  tmp_df['Current P/L'] = round((tmp_df['Current'] - tmp_df['Investment']),0)
  tmp_df['Today P/L%'] = round((tmp_df['Current'] - tmp_df['Previous'])*100/tmp_df['Previous'],2)
  tmp_df['Current P/L%'] = round((tmp_df['Current'] - tmp_df['Investment'])*100/tmp_df['Investment'],2)
  tmp_df['EstimatedST P/L%'] = round((tmp_df['EstimatedST'] - tmp_df['Investment'])*100/tmp_df['Investment'],2)
  tmp_df['EstimatedLT P/L%'] = round((tmp_df['EstimatedLT'] - tmp_df['Investment'])*100/tmp_df['Investment'],2)
  tmp_df['NTT%'] = round((tmp_df['NTT'] - tmp_df['Close'])*100/tmp_df['Close'],2)
  tmp_df['LTT%'] = round((tmp_df['LTT'] - tmp_df['Close'])*100/tmp_df['Close'],2)
  tmp_df['Gained%'] = round((tmp_df['Close'] - tmp_df['BOL'])*100/tmp_df['BOL'],2)
  investment = round(sum(tmp_df['AvgCost']*tmp_df['Shares']),0)
  current = round(sum(tmp_df['Close']*tmp_df['Shares']),0)
  tmp_df['InitAlloc%'] = round(tmp_df['Investment']*100/investment,2)
  tmp_df['CurrAlloc%'] = round(tmp_df['Current']*100/current,2)
  tmp_df['FTT'] = tmp_df['LTT']
  tmp_df.loc[tmp_df['Strategy'] == 'NTT', 'FTT'] = tmp_df['NTT']
  tmp_df['FTT%'] = tmp_df['LTT%']
  tmp_df.loc[tmp_df['Strategy'] == 'NTT', 'FTT%'] = tmp_df['NTT%']
  tmp_df['FTT Amt'] = round(tmp_df['FTT%'] * tmp_df['Current']/100,0)
  tmp_df['OTT%'] = round((tmp_df['FTT'] - tmp_df['AvgCost'])*100/tmp_df['AvgCost'],2)
  tmp_df['RRR Ind'] = round(tmp_df['Current P/L']/tmp_df['FTT Amt'],2)
  tmp_df['Risk Ind'] = round(tmp_df['Current P/L%']*tmp_df['CurrAlloc%'],0)

  return tmp_df

# function to print portfolio features
def print_portfolio_stats(df_portfolio_features, myinvmt_df):
  from pyxirr import xirr

  total_booked_amt, reserve_amt, cy_booked_amt, py_booked_amt = get_amt()

  dates = myinvmt_df['Date'].values
  dates = np.append(dates, datetime.date.today().strftime('%d-%b-%y'))
  investment = myinvmt_df['Investment'].values
  dates= pd.to_datetime(dates)

  current = round(sum(df_portfolio_features['Close']*df_portfolio_features['Shares']),0) + reserve_amt
  investment_xirr = np.append(investment, current)
  cagr = round(xirr(pd.DataFrame({"dates": dates, "amounts": investment_xirr}))*100,2)

  investment = -sum(investment)
  invested = round(sum(df_portfolio_features['AvgCost']*df_portfolio_features['Shares']),0) + reserve_amt
  previous = round(sum(df_portfolio_features['Prev_Close']*df_portfolio_features['Shares']),0) + reserve_amt
  cy_invested = investment + py_booked_amt

  today_pnl_amount = current-previous
  today_pnl_percentage = round((current-previous)*100/previous,2)

  curr_pnl_amount = current-invested
  curr_pnl_percentage = round((curr_pnl_amount)*100/(cy_invested),2)

  cy_pnl_amount = cy_booked_amt + curr_pnl_amount
  cy_pnl_percentage = round((cy_pnl_amount)*100/cy_invested,2)

  overall_pnl_amount = total_booked_amt + curr_pnl_amount
  overall_pnl_percentage = round((overall_pnl_amount)*100/investment,2)

  estimate_st = round(sum(df_portfolio_features['FTT']*df_portfolio_features['Shares']),0)  + reserve_amt
  est_st_pnl_amount = estimate_st-current
  est_st_pnl_percentage = round((est_st_pnl_amount)*100/current,2)

  estimate_lt = round(sum(df_portfolio_features['LTT']*df_portfolio_features['Shares']),0)  + reserve_amt
  est_lt_pnl_amount = estimate_lt-current
  est_lt_pnl_percentage = round((est_lt_pnl_amount)*100/current,2)

  total_profit = round(sum(df_portfolio_features[df_portfolio_features['Current P/L%'] > 0]['Current']) - sum(df_portfolio_features[df_portfolio_features['Current P/L%'] > 0]['Investment']),0)
  total_loss = round(sum(df_portfolio_features[df_portfolio_features['Current P/L%'] < 0]['Current']) - sum(df_portfolio_features[df_portfolio_features['Current P/L%'] < 0]['Investment']),0)

  cy_booked_percentage = round((cy_booked_amt)*100/current,2)
  py_booked_percentage = round((py_booked_amt)*100/investment,2)
  total_booked_percentage = round((total_booked_amt)*100/investment,2)

  print('-------------------')
  print('Initial Investment: ', format_amt(investment))
  print('CY Investment: ', format_amt(cy_invested))
  print('Reserve: ', format_amt(reserve_amt))
  print('Current: ',  format_amt(current))
  print('-------------------')
  print('Today PnL: '+ '{} ({}%)'.format(format_amt(today_pnl_amount), today_pnl_percentage))
  print('Current PnL: '+ '{} ({}%)'.format(format_amt(curr_pnl_amount), curr_pnl_percentage))
  print('CY Booked + Current PnL: '+ '{} ({}%)'.format(format_amt(cy_pnl_amount), cy_pnl_percentage))
  print('-------------------')
  print('Total profit: ', format_amt(total_profit))
  print('Total loss: ', format_amt(total_loss))
  print('-------------------')
  print('Total Booked + Current PnL: '+ '{} ({}%)'.format(format_amt(overall_pnl_amount), overall_pnl_percentage))
  print('Total Booked PnL: '+ '{} ({}%)'.format(format_amt(total_booked_amt), total_booked_percentage))
  print('Curr Year Booked PnL: '+ '{} ({}%)'.format(format_amt(cy_booked_amt), cy_booked_percentage))
  print('Prev Year Booked PnL: '+ '{} ({}%)'.format(format_amt(py_booked_amt), py_booked_percentage))
  print('===================')
  print('Est FTT: ',  format_amt(estimate_st))
  print('Est FTT PnL: '+ '{} ({}%)'.format(format_amt(est_st_pnl_amount), est_st_pnl_percentage))

  print('===================')
  print('Deployed: ', format_amt(investment))

  print('Current: ', format_amt(current))

  print('CAGR/XIRR %: '+'{}%'.format(cagr))

In [8]:
# get start and end date
start_date, end_date = get_start_end_date()

# get portfolio and prospects data
mypfs_df = get_mypfs_df()
mypps_df = get_mypps_df()
myinvmt_df = get_myinvmt_df()

# merge above datasets
mypf_df = pd.merge(mypfs_df, mypps_df, on="Symbol")

# seggregate dm and sv portfolio
dm_pf = mypf_df[mypf_df['InPortfolio'] == 'DM']
sv_pf = mypf_df[mypf_df['InPortfolio'] == 'SV']

# build portfolio stock dataframe
dm_stocks = get_stock_ids(dm_pf)
sv_stocks = get_stock_ids(sv_pf)
df_stocks = pd.concat([dm_pf,sv_pf], ignore_index = True)

# arrange common and diff stock features
common_cols = ['Symbol', 'Target', 'Criteria', 'Strategy', 'CumlRnk', 'LatestQtr', 'StarStock', 'Conviction', 'Category', 'InFolio', 'XIRR', 'MBQ']
diff_cols = ['Symbol', 'AvgCost', 'Shares']
df_stocks = arrange_features(df_stocks, common_cols, diff_cols)

# get common features
stock_ids = df_stocks['Symbol'].values
df_common_features = get_common_features(stock_ids, df_stocks)

df_common_features.reset_index(drop=True, inplace=True)
df_common_features.drop(['Date'], axis=1, inplace=True)
# get and print portfolio features
df_portfolio_features = get_portfolio_features(df_common_features)

print_portfolio_stats(df_portfolio_features, myinvmt_df)

df = df_portfolio_features
#plot_pie_chart(df, 'CapType', 'Current')
list_ox40n = list(df[df['MBQ'].str.contains('OX40N', na=False)]['Symbol'].values)

Run date time (IST): 2026-04-30 13:22:22
-------------------
qualified stocks: 92
with latest results: 31
still star stocks: 20
-------------------
Initial Investment:  1.40 C
CY Investment:  1.82 C
Reserve:  1.49 K
Current:  1.48 C
-------------------
Today PnL: -1.81 L (-1.21%)
Current PnL: -35.66 L (-19.55%)
CY Booked + Current PnL: -33.58 L (-18.41%)
-------------------
Total profit:  1.23 L
Total loss:  -36.89 L
-------------------
Total Booked + Current PnL: 9.29 L (6.66%)
Total Booked PnL: 44.95 L (32.22%)
Curr Year Booked PnL: 2.08 L (1.41%)
Prev Year Booked PnL: 42.87 L (30.73%)
===================
Est FTT:  2.55 C
Est FTT PnL: 1.08 C (73.16%)
===================
Deployed:  1.40 C
Current:  1.48 C
CAGR/XIRR %: 2.78%

In [9]:
# top 5 near their targets
cols = ['Symbol', 'Today P/L%', 'Current P/L%', 'FTT%', 'OTT%', 'FTT Amt', 'Current P/L', 'Current', 'FTT', 'Dev%_PE', 'RSI_14','Conviction', 'Spread%',  'CumlRnk', 'RRR Ind', 'CurrAlloc%', 'Gained%', 'Criteria', 'Strategy', 'Category']
df_tmp = df_portfolio_features[~df_portfolio_features['Symbol'].isin(['ENRIN','BLUSPRING','DIGITIDE'])]
df_tmp = df_tmp.sort_values(by = 'FTT Amt', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
55,MASFIN,5.19,4.96,15.82,21.57,16269.0,4860.0,102840.0,397.04,-9.67,70.0,H-SC,0.64,167.0,0.30,0.70,32.89,XR,ATH,FINANCE
51,KOTAKBANK,-0.17,1.90,18.85,21.11,26597.0,2628.0,141100.0,453.24,-12.44,53.0,X-LC,8.80,12.0,0.10,0.96,7.91,X40,ATH,BANKS
59,PIDILITIND,-1.50,-3.04,22.08,18.37,30210.0,-4290.0,136820.0,1670.26,-32.12,49.0,X-LC,7.27,5.0,-0.14,0.93,7.43,X40,ATH,CHEMICALS
53,M&M,-2.28,-0.04,23.43,23.38,32479.0,-59.0,138622.0,3802.40,-15.13,45.0,X-LC,8.71,25.0,-0.00,0.94,6.45,X40N,ATH,AUTO
83,TTKPRESTIG,-2.68,-34.68,53.23,0.09,35040.0,-34949.0,65828.0,770.00,52.83,52.0,M-SC,18.68,250.0,-1.00,0.45,17.21,OX40N,NTT,DURABLES

In [10]:
# top 5 today
df_tmp = df_portfolio_features.sort_values(by = 'Today P/L%', ascending=False)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
55,MASFIN,5.19,4.96,15.82,21.57,16269.0,4860.0,102840.0,397.04,-9.67,70.0,H-SC,0.64,167.0,0.30,0.70,32.89,XR,ATH,FINANCE
29,GREENPANEL,2.04,-39.59,136.93,43.14,151451.0,-72473.0,110605.0,537.00,148.06,67.0,M-SC,18.78,225.0,-0.48,0.75,32.86,XY24,NTT,MISC
45,INFY,1.46,-19.36,66.48,34.24,167728.0,-60590.0,252298.0,1972.00,-36.50,36.0,X-LC,13.57,3.0,-0.36,1.71,2.81,X40,NTT,IT
11,BERGEPAINT,1.08,-13.61,45.05,25.32,100317.0,-35069.0,222680.0,680.00,-18.24,58.0,X-MC,13.73,68.0,-0.35,1.51,15.90,XY24,NTT,PAINTS
71,SIEMENS,0.93,2.42,22.55,25.51,42979.0,4500.0,190595.0,4671.50,60.03,68.0,H-LC,10.65,51.0,0.10,1.29,34.29,AR,ATH,ELECTRICAL

In [11]:
# bottom 5 today
df_tmp = df_portfolio_features.sort_values(by = 'Today P/L%', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
81,TMPV,-3.87,-22.82,76.97,36.58,211383.0,-81211.0,274630.0,600.0,-83.62,47.0,X-LC,5.20,4.0,-0.38,1.86,14.47,XY24,NTT,AUTO
88,VOLTAS,-3.40,11.45,30.28,45.20,64705.0,21948.0,213690.0,1856.0,27.64,51.0,X-MC,2.86,79.0,0.34,1.45,19.02,XY25,NTT,AC
68,SATIN,-3.29,-2.76,56.14,51.83,150826.0,-7624.0,268660.0,274.0,-13.27,63.0,H-SC,8.78,159.0,-0.05,1.82,30.88,XY24,NTT,FINANCE
20,DABUR,-3.04,-13.55,66.23,43.70,142026.0,-33625.0,214443.0,735.0,-21.50,47.0,X-MC,12.36,70.0,-0.24,1.45,7.72,XY24,BTT,FMCG
36,HINDUNILVR,-2.92,-12.59,30.05,13.67,67519.0,-32373.0,224690.0,2922.0,-35.09,52.0,X-LC,7.75,9.0,-0.48,1.52,9.49,XY25,NTT,FMCG

In [12]:
# top 5 to exit based on CumlRnk
df_tmp = df_portfolio_features[~df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])]
df_tmp = df_tmp[(df_tmp['Current P/L%'] > -1) & (df_tmp['Current P/L%'] < 1)].sort_values(by = 'CumlRnk', ascending=False)
df_tmp[cols].head()

Empty DataFrame
Columns: [Symbol, Today P/L%, Current P/L%, FTT%, OTT%, FTT Amt, Current P/L, Current, FTT, Dev%_PE, RSI_14, Conviction, Spread%, CumlRnk, RRR Ind, CurrAlloc%, Gained%, Criteria, Strategy, Category]
Index: []

In [13]:
# OX40N stocks to exit
df_tmp = df_portfolio_features[(df_portfolio_features['Symbol'].isin(list_ox40n))].sort_values(by = 'Current P/L%', ascending=False)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
25,FINCABLES,-1.44,25.24,66.01,107.91,122062.0,37271.0,184915.0,1641.55,12.63,68.0,M-SC,10.32,220.0,0.31,1.25,39.12,OX40N,ATH,CABLES
72,SIS,-1.32,-16.86,45.86,21.26,42333.0,-18722.0,92310.0,528.00,2187.56,75.0,H-SC,8.05,168.0,-0.44,0.63,37.25,OX40N,NTT,MISC
16,CERA,-0.99,-31.16,79.97,23.89,96834.0,-54815.0,121088.0,9475.00,-33.65,57.0,H-SC,12.32,153.0,-0.57,0.82,16.36,OX40N,NTT,CERAMICS
50,KANSAINER,-0.06,-34.05,72.06,13.47,128152.0,-91827.0,177840.0,340.00,-43.31,55.0,H-SC,16.50,162.0,-0.72,1.21,24.22,XY24,NTT,PAINTS
83,TTKPRESTIG,-2.68,-34.68,53.23,0.09,35040.0,-34949.0,65828.0,770.00,52.83,52.0,M-SC,18.68,250.0,-1.00,0.45,17.21,OX40N,NTT,DURABLES

In [14]:
# top 5 to book for rotation
df_tmp = df_portfolio_features[(df_portfolio_features['Current P/L%'] > 20) ].sort_values(by = 'CumlRnk', ascending=False)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
25,FINCABLES,-1.44,25.24,66.01,107.91,122062.0,37271.0,184915.0,1641.55,12.63,68.0,M-SC,10.32,220.0,0.31,1.25,39.12,OX40N,ATH,CABLES

In [15]:
# top 5 to monitor for exit
df_tmp = df_portfolio_features[~df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])]
df_tmp = df_tmp[(df_tmp['Current P/L%'] > 0) ].sort_values(by = 'Dev%_PE', ascending=False)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
74,STARHEALTH,-1.54,1.60,44.94,47.26,128361.0,4504.0,285627.0,761.00,60.41,70.0,H-SC,6.51,173.0,0.04,1.94,47.92,XY24,NTT,INSURANCE
25,FINCABLES,-1.44,25.24,66.01,107.91,122062.0,37271.0,184915.0,1641.55,12.63,68.0,M-SC,10.32,220.0,0.31,1.25,39.12,OX40N,ATH,CABLES
55,MASFIN,5.19,4.96,15.82,21.57,16269.0,4860.0,102840.0,397.04,-9.67,70.0,H-SC,0.64,167.0,0.30,0.70,32.89,XR,ATH,FINANCE
73,SONACOMS,-0.25,3.49,34.41,39.09,36022.0,3526.0,104685.0,804.02,-18.04,64.0,M-MC,16.25,193.0,0.10,0.71,48.09,AR,ATH,AUTO

In [16]:
# top 5 to book for rotation from weak conviction
df_tmp = df_portfolio_features[~df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])]
df_tmp = df_tmp[~df_tmp['Criteria'].isin(['XY25','XY24','X40', 'X40N'])].sort_values(by = 'RRR Ind', ascending=False)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
25,FINCABLES,-1.44,25.24,66.01,107.91,122062.0,37271.0,184915.0,1641.55,12.63,68.0,M-SC,10.32,220.0,0.31,1.25,39.12,OX40N,ATH,CABLES
55,MASFIN,5.19,4.96,15.82,21.57,16269.0,4860.0,102840.0,397.04,-9.67,70.0,H-SC,0.64,167.0,0.30,0.70,32.89,XR,ATH,FINANCE
73,SONACOMS,-0.25,3.49,34.41,39.09,36022.0,3526.0,104685.0,804.02,-18.04,64.0,M-MC,16.25,193.0,0.10,0.71,48.09,AR,ATH,AUTO
42,INDIAMART,-0.24,-8.66,126.32,106.72,142308.0,-10679.0,112657.0,4810.62,-58.79,52.0,H-SC,9.27,140.0,-0.08,0.76,8.23,AR,ATH,MISC
91,ZYDUSLIFE,-1.43,-5.32,43.25,35.63,85819.0,-11149.0,198425.0,1286.17,-17.57,45.0,H-MC,3.83,120.0,-0.13,1.35,4.33,AR,ATH,PHARMA

In [17]:
# top 5 to accumulate based on lowest RSI_14
df_tmp = df_portfolio_features[df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])].sort_values(by = 'RSI_14', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
33,HCLTECH,0.48,-21.74,55.25,21.51,104611.0,-52582.0,189342.0,1872.35,-17.70,31.0,X-LC,8.90,8.0,-0.50,1.28,0.84,X40,ATH,IT
40,ICICIPRULI,-1.81,-14.80,53.44,30.73,89694.0,-29164.0,167841.0,790.00,-37.65,35.0,X-MC,13.02,78.0,-0.33,1.14,2.27,X40,ATH,INSURANCE
45,INFY,1.46,-19.36,66.48,34.24,167728.0,-60590.0,252298.0,1972.00,-36.50,36.0,X-LC,13.57,3.0,-0.36,1.71,2.81,X40,NTT,IT
35,HDFCLIFE,-1.92,-4.65,39.67,33.18,56663.0,-6965.0,142835.0,814.30,-25.53,39.0,X-LC,17.71,31.0,-0.12,0.97,2.99,X40,ATH,INSURANCE
39,ICICIGI,-1.36,-7.49,29.00,19.34,53687.0,-14980.0,185129.0,2252.93,-22.28,39.0,X-MC,6.11,66.0,-0.28,1.26,3.40,X40,ATH,INSURANCE

In [18]:
# top 5 to accumulate based on Spread and CumlRnk
df_tmp = df_portfolio_features[df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])]
df_tmp = df_tmp[(df_tmp['CumlRnk'] < 100)].sort_values(by = 'Spread%', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
88,VOLTAS,-3.40,11.45,30.28,45.20,64705.0,21948.0,213690.0,1856.00,27.64,51.0,X-MC,2.86,79.0,0.34,1.45,19.02,XY25,NTT,AC
84,UNITDSPR,-2.74,-2.59,23.98,20.77,54692.0,-6072.0,228072.0,1644.00,-13.56,50.0,X-MC,3.75,64.0,-0.11,1.55,8.80,X40N,NTT,BREWERIES
81,TMPV,-3.87,-22.82,76.97,36.58,211383.0,-81211.0,274630.0,600.00,-83.62,47.0,X-LC,5.20,4.0,-0.38,1.86,14.47,XY24,NTT,AUTO
87,VBL,-2.10,3.34,30.99,35.37,101152.0,10559.0,326401.0,670.16,-8.73,69.0,X-LC,5.44,13.0,0.10,2.21,34.15,X40N,ATH,FMCG
65,RELIANCE,-0.34,-8.81,37.41,25.30,68556.0,-17706.0,183257.0,1952.00,-11.19,60.0,X-LC,5.60,21.0,-0.26,1.24,8.89,XY25,BTT,REFINERIES

In [19]:
# top 5 to accumulate based on lowest Gained%
df_tmp = df_portfolio_features[df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])].sort_values(by = 'Gained%', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
1,ABBOTINDIA,-0.43,-14.91,38.75,18.07,58974.0,-26665.0,152190.0,35195.00,-27.52,41.0,X-MC,11.94,58.0,-0.45,1.03,0.73,X40,ATH,PHARMA
33,HCLTECH,0.48,-21.74,55.25,21.51,104611.0,-52582.0,189342.0,1872.35,-17.70,31.0,X-LC,8.90,8.0,-0.50,1.28,0.84,X40,ATH,IT
40,ICICIPRULI,-1.81,-14.80,53.44,30.73,89694.0,-29164.0,167841.0,790.00,-37.65,35.0,X-MC,13.02,78.0,-0.33,1.14,2.27,X40,ATH,INSURANCE
45,INFY,1.46,-19.36,66.48,34.24,167728.0,-60590.0,252298.0,1972.00,-36.50,36.0,X-LC,13.57,3.0,-0.36,1.71,2.81,X40,NTT,IT
35,HDFCLIFE,-1.92,-4.65,39.67,33.18,56663.0,-6965.0,142835.0,814.30,-25.53,39.0,X-LC,17.71,31.0,-0.12,0.97,2.99,X40,ATH,INSURANCE

In [20]:
# top 5 to accumulate based on lowest CurrAlloc%
df_tmp = df_portfolio_features[df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])].sort_values(by = 'CurrAlloc%', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
64,RELAXO,-1.68,-61.27,293.27,52.31,164871.0,-88942.0,56218.0,1176.00,-58.76,50.0,X-SC,26.80,92.0,-0.54,0.38,25.70,X40N,NTT,FOOTWEAR
10,BATAINDIA,-0.54,-53.51,190.85,35.20,114155.0,-68856.0,59814.0,2096.00,-21.59,48.0,X-SC,26.86,91.0,-0.60,0.41,18.63,X40,NTT,FOOTWEAR
60,QUESS,-0.49,-17.15,109.90,73.90,97235.0,-18317.0,88476.0,424.00,-55.37,61.0,X-SC,15.36,80.0,-0.19,0.60,19.02,XY24,NTT,MISC
59,PIDILITIND,-1.50,-3.04,22.08,18.37,30210.0,-4290.0,136820.0,1670.26,-32.12,49.0,X-LC,7.27,5.0,-0.14,0.93,7.43,X40,ATH,CHEMICALS
53,M&M,-2.28,-0.04,23.43,23.38,32479.0,-59.0,138622.0,3802.40,-15.13,45.0,X-LC,8.71,25.0,-0.00,0.94,6.45,X40N,ATH,AUTO

In [21]:
# top 5 to accumulate based on CumlRnk
df_tmp = df_portfolio_features.sort_values(by = 'CumlRnk', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
47,ITC,-0.36,-17.00,43.45,19.06,122672.0,-57836.0,282330.0,452.00,-54.31,61.0,X-LC,16.92,1.0,-0.47,1.91,9.52,X40,NTT,FMCG
79,TCS,-0.14,-27.45,74.47,26.57,250281.0,-127190.0,336083.0,4311.59,-38.71,46.0,X-LC,14.16,2.0,-0.51,2.28,4.89,X40,ATH,IT
45,INFY,1.46,-19.36,66.48,34.24,167728.0,-60590.0,252298.0,1972.00,-36.50,36.0,X-LC,13.57,3.0,-0.36,1.71,2.81,X40,NTT,IT
81,TMPV,-3.87,-22.82,76.97,36.58,211383.0,-81211.0,274630.0,600.00,-83.62,47.0,X-LC,5.20,4.0,-0.38,1.86,14.47,XY24,NTT,AUTO
59,PIDILITIND,-1.50,-3.04,22.08,18.37,30210.0,-4290.0,136820.0,1670.26,-32.12,49.0,X-LC,7.27,5.0,-0.14,0.93,7.43,X40,ATH,CHEMICALS

In [22]:
# top 5 for average up
df_tmp = df_portfolio_features[(df_portfolio_features['Dev%_200'] > 5)].sort_values(by = 'CurrAlloc%', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
44,INDUSINDBK,-0.12,-32.62,97.23,32.89,50580.0,-25186.0,52021.0,1800.00,-345.10,63.0,L-MC,3.90,258.0,-0.50,0.35,28.05,XR,NTT,BANKS
72,SIS,-1.32,-16.86,45.86,21.26,42333.0,-18722.0,92310.0,528.00,2187.56,75.0,H-SC,8.05,168.0,-0.44,0.63,37.25,OX40N,NTT,MISC
55,MASFIN,5.19,4.96,15.82,21.57,16269.0,4860.0,102840.0,397.04,-9.67,70.0,H-SC,0.64,167.0,0.30,0.70,32.89,XR,ATH,FINANCE
73,SONACOMS,-0.25,3.49,34.41,39.09,36022.0,3526.0,104685.0,804.02,-18.04,64.0,M-MC,16.25,193.0,0.10,0.71,48.09,AR,ATH,AUTO
75,SURYODAY,0.87,-12.32,40.32,23.03,63306.0,-22062.0,157009.0,216.00,71.05,70.0,H-SC,6.37,166.0,-0.35,1.06,33.90,XR,NTT,BANKS

In [23]:
# top 5 RSP
df_tmp = df_portfolio_features.sort_values(by = 'RSP', ascending=False)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
61,RAJESHEXPO,-2.32,-76.43,324.59,0.07,104940.0,-104847.0,32330.0,518.00,1084.34,54.0,L-SC,32.85,268.0,-1.00,0.22,51.78,OX40N,NTT,JEWELLERY
77,TANLA,-2.22,-40.99,268.19,117.25,428468.0,-110998.0,159763.0,1922.32,-40.45,60.0,H-SC,19.06,147.0,-0.26,1.08,39.88,AR,ATH,IT
9,BANDHANBNK,-0.69,-5.27,103.12,92.42,272119.0,-14673.0,263886.0,400.00,126.29,71.0,H-SC,5.43,174.0,-0.05,1.79,45.37,XY24,NTT,BANKS
86,VALIANTORG,-0.47,-42.73,204.09,74.15,191226.0,-69908.0,93697.0,838.00,-268.43,58.0,H-SC,17.08,145.0,-0.37,0.64,39.44,XR,NTT,CHEMICALS
0,5PAISA,-1.55,-36.31,77.28,12.90,107537.0,-79344.0,139152.0,593.00,105.53,60.0,H-SC,9.05,170.0,-0.74,0.94,34.28,OX40N,NTT,FINANCE

In [24]:
# Top N allocation
df_tmp = df_portfolio_features.sort_values(by = 'CurrAlloc%', ascending=False)
top_n_values = [10, 25, 50]

sum_df = pd.DataFrame({
    'Top_N': top_n_values,
    'Sum_Alloc%': [df_tmp['CurrAlloc%'].head(n).sum() for n in top_n_values]
})

sum_df

   Top_N  Sum_Alloc%
0     10       19.17
1     25       42.65
2     50       72.62

In [25]:
# market-cap-wise allocation
df_tmp = df_portfolio_features[cols]
df_tmp.groupby(df_tmp['Conviction'].str[-2:])['CurrAlloc%'].sum().sort_values(ascending=False)

Conviction
SC    42.16
LC    31.94
MC    25.88
Name: CurrAlloc%, dtype: float64

In [26]:
# criteria-wise allocation
df_portfolio_features.groupby('Criteria')['CurrAlloc%'].sum().sort_values(ascending=False)

Criteria
XY24     26.83
X40      25.72
X40N     16.96
XR        9.13
XY25      6.95
OX40N     6.83
AR        6.76
SR        0.80
Name: CurrAlloc%, dtype: float64

In [27]:
# conviction-wise allocation
df_portfolio_features.groupby('Conviction')['CurrAlloc%'].sum().sort_values(ascending=False)

Conviction
X-LC    29.70
H-SC    21.94
X-MC    20.95
M-SC    10.01
X-SC     9.65
H-MC     2.55
M-MC     2.03
H-LC     1.29
M-LC     0.95
L-SC     0.56
L-MC     0.35
Name: CurrAlloc%, dtype: float64

In [28]:
# sector-wise stats
df_tmp = df_portfolio_features.groupby('Category')[['CurrAlloc%', 'Current', 'Current P/L', 'FTT Amt']].sum().sort_values(by=['Current', 'Current P/L'], ascending=False)
df_tmp['Current P/L%'] = round(df_tmp['Current P/L'] * 100 / df_tmp['Current'], 2)
df_tmp['FTT%'] = round(df_tmp['FTT Amt'] * 100 / df_tmp['Current'], 2)
cols = ['CurrAlloc%', 'Current P/L%', 'FTT%']
df_tmp[cols].sort_values(by=['CurrAlloc%'], ascending=False)

               CurrAlloc%  Current P/L%    FTT%
Category
FMCG                15.68        -14.32   54.65
FINANCE             10.75        -16.15   66.67
IT                  10.66        -43.05  115.08
MISC                 6.82        -33.11   90.94
AUTO                 6.60        -12.42   54.57
BANKS                5.64         -9.17   59.65
INSURANCE            5.31         -5.96   42.03
PAINTS               5.12        -30.70   53.39
PHARMA               4.76         -5.77   39.77
ELECTRICAL           4.11        -16.43   57.88
CHEMICALS            2.01        -37.11  118.82
AC                   1.98         -9.40   39.06
HEALTHCARE           1.90        -27.55   60.84
DURABLES             1.80        -45.76   81.22
FOOTWEAR             1.75        -71.52  140.30
APPARELS             1.74         -4.53   40.18
TRAVEL               1.72        -76.97  165.58
BREWERIES            1.55         -2.66   23.98
REALTY               1.39         -8.54   26.37
CERAMICS             1.30        -60.55  109.32
CABLES               1.25         20.16   66.01
REFINERIES           1.24         -9.66   37.41
ENGINEERING          1.18        -38.58  101.96
CEMENT               1.15        -58.02  176.24
JEWELLERY            1.05       -106.42  178.14
ENTERTAINMENT        0.75        -75.65  180.42
TEXTILES             0.43        -44.04   85.11
HOTELS               0.34       -124.27  203.38

In [29]:
# money to be made criteria-wise
df_portfolio_features.groupby('Criteria')['FTT Amt'].agg(['sum', 'count']).sort_values(by='sum', ascending=False)

                sum  count
Criteria
XY24      3639138.0     21
X40       1911141.0     19
XR        1334976.0     13
X40N      1223536.0     13
AR        1185869.0      9
OX40N      783376.0     10
XY25       413921.0      5
SR         300483.0      2

In [30]:
# money to be made conviction-wise
df_portfolio_features.groupby('Conviction')['FTT Amt'].agg(['sum', 'count']).sort_values(by='sum', ascending=False)

                  sum  count
Conviction
H-SC        3548418.0     24
X-LC        1917944.0     21
X-MC        1644194.0     15
M-SC        1439652.0     14
X-SC        1379984.0      9
H-MC         323057.0      2
L-SC         207911.0      2
M-LC         151777.0      1
M-MC          85944.0      2
L-MC          50580.0      1
H-LC          42979.0      1

In [31]:
# money to be made criteria and conviction-wise
df_portfolio_features.groupby(['Conviction', 'Criteria'])['FTT Amt'].agg(['sum', 'count']).sort_values(by='sum', ascending=False)

                           sum  count
Conviction Criteria
H-SC       XY24      1150488.0      6
X-LC       X40       1019700.0     10
H-SC       AR         945209.0      5
M-SC       XY24       853860.0      6
H-SC       XR         810268.0      7
X-SC       XY24       804229.0      4
X-MC       X40        687166.0      7
           X40N       486761.0      4
X-SC       X40N       371480.0      3
X-LC       X40N       365295.0      6
           XY24       350980.0      2
H-SC       OX40N      341970.0      4
M-SC       OX40N      336466.0      5
H-SC       SR         300483.0      2
X-MC       XY24       242343.0      2
H-MC       XY24       237238.0      1
X-MC       XY25       227924.0      2
X-SC       X40        204275.0      2
M-SC       XR         173486.0      2
M-LC       XR         151777.0      1
X-LC       XY25       136075.0      2
L-SC       OX40N      104940.0      1
           XR         102971.0      1
H-MC       AR          85819.0      1
M-SC       AR          75840.0      1
L-MC       XR          50580.0      1
M-MC       XY25        49922.0      1
X-LC       XR          45894.0      1
H-LC       AR          42979.0      1
M-MC       AR          36022.0      1

In [32]:
# notebook execution time

end_time = time.time()
execution_time = round(end_time - start_time, 0)
print(f"Notebook execution time: {execution_time} seconds")

Notebook execution time: 26.0 seconds