<a href="https://colab.research.google.com/github/ankit-rathi/Quantvesting_v2/blob/main/myStocks_Portfolio_Analysis.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
'''
!pip install pandas==2.2.2 -qq
!pip install pyxirr -qq
!pip install ta -qq
!pip install yfinance==0.2.59 -qq
'''

'\n!pip install pandas==2.2.2 -qq\n!pip install pyxirr -qq\n!pip install ta -qq\n!pip install yfinance==0.2.59 -qq\n'

In [2]:
# import libraries

import numpy as np
import pandas as pd
import datetime
import warnings
warnings.filterwarnings('ignore')
import yfinance as yfin
import ta
import matplotlib.pyplot as plt
import requests

In [3]:
# notebook start time
import time
import datetime
import pytz

start_time = time.time()

# function to print date timestamp
def print_date_time():
  tz_NY = pytz.timezone('Asia/Kolkata')
  datetime_NY = datetime.datetime.now(tz_NY)
  print("Run date time (IST):", datetime_NY.strftime("%Y-%m-%d %H:%M:%S"))

In [4]:
# function to get booked and reserved amount
def get_amt():
  # fetch the JSON data from the URL
  url = "https://raw.githubusercontent.com/ankit-rathi/Tradevesting_v1/main/data/myPortfolioAmts.json"
  response = requests.get(url)
  pf_amts = response.json()  # parse the JSON data

  # extract values from the JSON
  py_booked_amt_dm = pf_amts["py_booked_amt_dm"]
  py_booked_amt_sv = pf_amts["py_booked_amt_sv"]
  cy_booked_amt_dm = pf_amts["cy_booked_amt_dm"]
  cy_booked_amt_sv = pf_amts["cy_booked_amt_sv"]
  reserve_amt_dm = pf_amts["reserve_amt_dm"]
  reserve_amt_sv = pf_amts["reserve_amt_sv"]

  # perform calculations
  py_booked_amt = py_booked_amt_dm + py_booked_amt_sv
  cy_booked_amt = cy_booked_amt_dm + cy_booked_amt_sv
  reserve_amt = reserve_amt_dm + reserve_amt_sv
  total_booked_amt = py_booked_amt + cy_booked_amt

  return total_booked_amt, reserve_amt, cy_booked_amt, py_booked_amt

gen_output = 0

In [5]:
# function to format the amount
def format_amt(number):
    abs_number = abs(number)

    if abs_number >= 1_00_00_000:  # Crores
        formatted_amt = f"{number / 1_00_00_000:.2f} C"
    elif abs_number >= 1_00_000:  # Lakhs
        formatted_amt = f"{number / 1_00_000:.2f} L"
    elif abs_number >= 1_000:  # Thousands
        formatted_amt = f"{number / 1_000:.2f} K"
    else:
        formatted_amt = f"{number:.2f}"

    return formatted_amt

# function to set start and end date
def get_start_end_date():
  start_date = (datetime.date.today() + datetime.timedelta(days=-365)).strftime('%Y-%m-%d')
  end_date = (datetime.date.today() + datetime.timedelta(days=1)).strftime('%Y-%m-%d')
  return start_date, end_date

# function to fetch my portfolio csv
def get_mypfs_df():
  mypfs_df = pd.read_csv('https://raw.githubusercontent.com/ankit-rathi/Tradevesting_v1/main/data/myPortfolioStocks.csv')
  return mypfs_df

# function to fetch my prospects csv
def get_mypps_df():
  mypps_df = pd.read_csv('https://raw.githubusercontent.com/ankit-rathi/Tradevesting_v1/main/data/myProspectsScrips.csv')
  return mypps_df

# function to fetch screener data
def get_myscreen_df():
  myscreen_df = pd.read_csv('https://raw.githubusercontent.com/ankit-rathi/Tradevesting_v1/main/data/myScreenerDB.csv')
  return myscreen_df

# function to fetch momentum data
def get_myinvmt_df():
  myinvmt_df = pd.read_csv('https://raw.githubusercontent.com/ankit-rathi/Tradevesting_v1/main/data/myInvestments.csv')
  return myinvmt_df

# function to get the stock ids
def get_stock_ids(df_pf):
  stock_n100 = df_pf['Symbol'].unique()

  exclude = ['CADILAHC','MMTC', 'MASFIN']

  stock_ids = df_pf[~df_pf['Symbol'].isin(exclude) ]['Symbol'].unique()

  #mypf = mypf[mypf.Forecast.notnull()]
  #stock_ids = mypf['Symbol'].unique()

  #stock_ids.sort()
  return stock_ids

# get features from screener data
def get_screener_features():
  myscreen_df = get_myscreen_df()
  cols = ['Symbol', 'EPS', 'MedPE', 'ROCE%', 'ROE%', 'CapType']
  return myscreen_df[cols]

# get relative strength
def get_relative_strength(stock_list):

    # Dictionary to store stock tickers and their corresponding percentage price change
    stock_changes = {}

    # Loop through each stock and fetch its price data
    for stock in stock_list:
        try:
            # Download the stock data for the given date range
            stock_data = yfin.Ticker(stock + '.NS').history(period='1mo', interval='1d')[map(str.title, ['open', 'close', 'low', 'high', 'volume'])]

            # Calculate the percentage change for the stock
            if len(stock_data) > 0:
                start_price = stock_data['Close'].iloc[0]
                end_price = stock_data['Close'].iloc[-1]
                percent_change = round(((end_price - start_price) / start_price) * 100, 2)
                stock_changes[stock] = percent_change
            else:
                stock_changes[stock] = np.nan  # If no data is available, set to NaN

        except Exception as e:
            print(f"Error fetching data for {stock}: {e}")
            stock_changes[stock] = np.nan

    # Create a DataFrame with stock tickers and their percentage changes
    df = pd.DataFrame(list(stock_changes.items()), columns=['Symbol', 'Percent_Change'])

    # Drop any stocks with missing data (NaN values)
    df = df.dropna()

    # Calculate the percentile rank based on percentage change
    df['RSP'] = round(df['Percent_Change'].rank(pct=True) * 100, 2)
    cols = ['Symbol', 'RSP']
    df = df[cols]
    # Sort by percentile rank (optional)
    df = df.sort_values(by='RSP', ascending=False).reset_index(drop=True)

    return df

In [6]:
# function to get stock technicals
def stock_prec_dev(stock_symbol):
    #stock_symbol = 'ULTRACEMCO.NS'
    short_window = 20
    mid_window = 50
    long_window = 200
    moving_avg = 'SMA'

    start = datetime.datetime(*map(int, start_date.split('-')))
    end = datetime.datetime(*map(int, end_date.split('-')))

    stock_df = yfin.Ticker(stock_symbol + '.NS').history(period='max', interval='1d')[map(str.title, ['open', 'close', 'low', 'high', 'volume'])]

    stock_df['Max'] = round(max(stock_df['Close']),2)
    stock_df = stock_df[(stock_df.index <= end_date) & (stock_df.index >= start_date)]
    stock_df['200_SMA'] = round(stock_df['Close'].rolling(window = 200, min_periods = 1).mean(),0)
    stock_df['Dev%_200'] = round((stock_df['Close'] - stock_df['200_SMA'])*100/stock_df['200_SMA'],2)
    stock_df.dropna(axis = 0, inplace = True) # remove any null rows

    stock_df['20_SMA'] = stock_df['Close'].rolling(window=20).mean()
    stock_df['50_SMA'] = stock_df['Close'].rolling(window=50).mean()
    stock_df['Symbol'] = stock_symbol

    stock_df['Close'] = round(stock_df['Close'],2)
    stock_df['Min'] = round(min(stock_df['Close']),2)
    stock_df['RSI_14'] = ta.momentum.RSIIndicator(close=stock_df['Close'], window=14).rsi()
    stock_df['RSI_14'] = round(stock_df['RSI_14'],0)
    stock_df['Prev_Close'] = stock_df['Close'].shift(1)
    stock_df.drop(['Open', 'Low', 'High', 'Volume'], axis=1, inplace=True)
    stock_df = stock_df.tail(1)

    max_SMA = max(stock_df['20_SMA'].item(), stock_df['50_SMA'].item(), stock_df['200_SMA'].item())
    min_SMA = min(stock_df['20_SMA'].item(), stock_df['50_SMA'].item(), stock_df['200_SMA'].item())
    ABS_Spread = max_SMA - min_SMA
    stock_df['Spread%'] = round((ABS_Spread / stock_df['200_SMA'].item()) * 100,2)

    return stock_df

# function to compute stock attributes
def get_common_features(stock_ids, df_mypf):

  df_prec_dev = pd.DataFrame()
  df_tmp = get_screener_features()
  df_rs = get_relative_strength(stock_ids)

  for stock_id in stock_ids:
      tmp = stock_prec_dev(stock_id)
      tmp = tmp.reset_index()
      df_prec_dev = pd.concat([df_prec_dev, tmp], ignore_index = True)
  df_prec_dev = pd.merge(df_prec_dev, df_mypf, on= 'Symbol')
  df_prec_dev = pd.merge(df_prec_dev, df_tmp, on= 'Symbol', how='left')
  df_prec_dev = pd.merge(df_prec_dev, df_rs, on= 'Symbol', how='left')
  #print(df_prec_dev.columns)
  df_prec_dev['Curr_PE'] = round(df_prec_dev['Close']/df_prec_dev['EPS'],1)
  df_prec_dev['Dev%_PE'] = round((df_prec_dev['Curr_PE'] - df_prec_dev['MedPE'])*100/df_prec_dev['MedPE'],2)
  df_prec_dev['Conviction'] = df_prec_dev['Conviction'] + '-' + df_prec_dev['CapType']
  return df_prec_dev

# function to arrange stock features
def arrange_features(df_stocks, common_cols, diff_cols):
  df_stocks_common = df_stocks[common_cols].drop_duplicates()
  df_stocks_diff = df_stocks[diff_cols]
  df_stocks_diff['Investment'] = df_stocks_diff['AvgCost'] * df_stocks_diff['Shares']
  df_stocks_diff = df_stocks_diff.groupby(['Symbol'])[['Shares', 'Investment']].aggregate(['sum']).reset_index()
  df_stocks_diff.columns = ['Symbol', 'Shares', 'Investment']
  df_stocks_diff['AvgCost'] = round(df_stocks_diff['Investment']/df_stocks_diff['Shares'],2)
  df_stocks = pd.merge(df_stocks_diff, df_stocks_common, on='Symbol')
  return df_stocks

# plot fact distribution across dimension
def plot_pie_chart(df, dimension, fact):
  # grouping the data by category and calculating the sum of fact for each type
  grouped_data = df.groupby(dimension)[fact].sum()

  # sorting the grouped data in descending order
  grouped_data = grouped_data.sort_values(ascending=False)

  # creating a pie chart
  grouped_data.plot.pie(autopct='%1.1f%%', startangle=90, figsize=(6, 6))

  # adding a title and displaying the plot
  plt.title(f'{dimension} {fact} Distribution')
  plt.ylabel('')  # To hide the y-label
  plt.show()

In [7]:
# function to get portfolio features

def get_portfolio_features(df_common_features):

  print_date_time()
  print('-------------------')

  #df_common_features["Target"] = df_common_features["Target"].fillna(df_common_features["Max"])
  df_common_features['NTT'] = np.where(df_common_features['Strategy']== 'NTT', df_common_features["Target"], df_common_features['Max'])
  df_common_features['LTT'] = np.where(df_common_features['Strategy']== 'BTT', df_common_features["Target"], df_common_features['Max'])
  df_common_features['BOL'] = df_common_features['Min']

  tmp_df = df_common_features[df_common_features['Symbol'].isin(mypf_df[mypf_df['InPortfolio'] != 'NA'].Symbol.values)]
  print('qualified stocks: '+str(len(tmp_df['Symbol'].unique())))
  tmp_df1 = tmp_df[tmp_df['LatestQtr'] == 1]
  print('with latest results: '+str(len(tmp_df1['Symbol'].unique())))
  tmp_df1 = tmp_df1[tmp_df1['StarStock'] == 1]
  print('still star stocks: '+str(len(tmp_df1['Symbol'].unique())))
  tmp_df['Investment'] = tmp_df['AvgCost'] * tmp_df['Shares']
  tmp_df['Current'] = round(tmp_df['Close'] * tmp_df['Shares'],0)
  tmp_df['Previous'] = tmp_df['Prev_Close'] * tmp_df['Shares']
  tmp_df['EstimatedST'] = tmp_df['NTT'] * tmp_df['Shares']
  tmp_df['EstimatedLT'] = tmp_df['LTT'] * tmp_df['Shares']
  tmp_df['Current P/L'] = round((tmp_df['Current'] - tmp_df['Investment']),0)
  tmp_df['Today P/L%'] = round((tmp_df['Current'] - tmp_df['Previous'])*100/tmp_df['Previous'],2)
  tmp_df['Current P/L%'] = round((tmp_df['Current'] - tmp_df['Investment'])*100/tmp_df['Investment'],2)
  tmp_df['EstimatedST P/L%'] = round((tmp_df['EstimatedST'] - tmp_df['Investment'])*100/tmp_df['Investment'],2)
  tmp_df['EstimatedLT P/L%'] = round((tmp_df['EstimatedLT'] - tmp_df['Investment'])*100/tmp_df['Investment'],2)
  tmp_df['NTT%'] = round((tmp_df['NTT'] - tmp_df['Close'])*100/tmp_df['Close'],2)
  tmp_df['LTT%'] = round((tmp_df['LTT'] - tmp_df['Close'])*100/tmp_df['Close'],2)
  tmp_df['Gained%'] = round((tmp_df['Close'] - tmp_df['BOL'])*100/tmp_df['BOL'],2)
  investment = round(sum(tmp_df['AvgCost']*tmp_df['Shares']),0)
  current = round(sum(tmp_df['Close']*tmp_df['Shares']),0)
  tmp_df['InitAlloc%'] = round(tmp_df['Investment']*100/investment,2)
  tmp_df['CurrAlloc%'] = round(tmp_df['Current']*100/current,2)
  tmp_df['FTT'] = tmp_df['LTT']
  tmp_df.loc[tmp_df['Strategy'] == 'NTT', 'FTT'] = tmp_df['NTT']
  tmp_df['FTT%'] = tmp_df['LTT%']
  tmp_df.loc[tmp_df['Strategy'] == 'NTT', 'FTT%'] = tmp_df['NTT%']
  tmp_df['FTT Amt'] = round(tmp_df['FTT%'] * tmp_df['Current']/100,0)
  tmp_df['OTT%'] = round((tmp_df['FTT'] - tmp_df['AvgCost'])*100/tmp_df['AvgCost'],2)
  tmp_df['RRR Ind'] = round(tmp_df['Current P/L']/tmp_df['FTT Amt'],2)
  tmp_df['Risk Ind'] = round(tmp_df['Current P/L%']*tmp_df['CurrAlloc%'],0)

  return tmp_df

# function to print portfolio features
def print_portfolio_stats(df_portfolio_features, myinvmt_df):
  from pyxirr import xirr

  total_booked_amt, reserve_amt, cy_booked_amt, py_booked_amt = get_amt()

  dates = myinvmt_df['Date'].values
  dates = np.append(dates, datetime.date.today().strftime('%d-%b-%y'))
  investment = myinvmt_df['Investment'].values
  dates= pd.to_datetime(dates)

  current = round(sum(df_portfolio_features['Close']*df_portfolio_features['Shares']),0) + reserve_amt
  investment_xirr = np.append(investment, current)
  cagr = round(xirr(pd.DataFrame({"dates": dates, "amounts": investment_xirr}))*100,2)

  investment = -sum(investment)
  invested = round(sum(df_portfolio_features['AvgCost']*df_portfolio_features['Shares']),0) + reserve_amt
  previous = round(sum(df_portfolio_features['Prev_Close']*df_portfolio_features['Shares']),0) + reserve_amt
  cy_invested = investment + py_booked_amt

  today_pnl_amount = current-previous
  today_pnl_percentage = round((current-previous)*100/previous,2)

  curr_pnl_amount = current-invested
  curr_pnl_percentage = round((curr_pnl_amount)*100/(cy_invested),2)

  cy_pnl_amount = cy_booked_amt + curr_pnl_amount
  cy_pnl_percentage = round((cy_pnl_amount)*100/cy_invested,2)

  overall_pnl_amount = total_booked_amt + curr_pnl_amount
  overall_pnl_percentage = round((overall_pnl_amount)*100/investment,2)

  estimate_st = round(sum(df_portfolio_features['FTT']*df_portfolio_features['Shares']),0)  + reserve_amt
  est_st_pnl_amount = estimate_st-current
  est_st_pnl_percentage = round((est_st_pnl_amount)*100/current,2)

  estimate_lt = round(sum(df_portfolio_features['LTT']*df_portfolio_features['Shares']),0)  + reserve_amt
  est_lt_pnl_amount = estimate_lt-current
  est_lt_pnl_percentage = round((est_lt_pnl_amount)*100/current,2)

  total_profit = round(sum(df_portfolio_features[df_portfolio_features['Current P/L%'] > 0]['Current']) - sum(df_portfolio_features[df_portfolio_features['Current P/L%'] > 0]['Investment']),0)
  total_loss = round(sum(df_portfolio_features[df_portfolio_features['Current P/L%'] < 0]['Current']) - sum(df_portfolio_features[df_portfolio_features['Current P/L%'] < 0]['Investment']),0)

  cy_booked_percentage = round((cy_booked_amt)*100/current,2)
  py_booked_percentage = round((py_booked_amt)*100/investment,2)
  total_booked_percentage = round((total_booked_amt)*100/investment,2)

  print('-------------------')
  print('Initial Investment: ', format_amt(investment))
  print('CY Investment: ', format_amt(cy_invested))
  print('Reserve: ', format_amt(reserve_amt))
  print('Current: ',  format_amt(current))
  print('-------------------')
  print('Today PnL: '+ '{} ({}%)'.format(format_amt(today_pnl_amount), today_pnl_percentage))
  print('Current PnL: '+ '{} ({}%)'.format(format_amt(curr_pnl_amount), curr_pnl_percentage))
  print('CY Booked + Current PnL: '+ '{} ({}%)'.format(format_amt(cy_pnl_amount), cy_pnl_percentage))
  print('-------------------')
  print('Total profit: ', format_amt(total_profit))
  print('Total loss: ', format_amt(total_loss))
  print('-------------------')
  print('Total Booked + Current PnL: '+ '{} ({}%)'.format(format_amt(overall_pnl_amount), overall_pnl_percentage))
  print('Total Booked PnL: '+ '{} ({}%)'.format(format_amt(total_booked_amt), total_booked_percentage))
  print('Curr Year Booked PnL: '+ '{} ({}%)'.format(format_amt(cy_booked_amt), cy_booked_percentage))
  print('Prev Year Booked PnL: '+ '{} ({}%)'.format(format_amt(py_booked_amt), py_booked_percentage))
  print('===================')
  print('Est FTT: ',  format_amt(estimate_st))
  print('Est FTT PnL: '+ '{} ({}%)'.format(format_amt(est_st_pnl_amount), est_st_pnl_percentage))

  print('===================')
  print('Deployed: ', format_amt(investment))

  print('Current: ', format_amt(current))

  print('CAGR/XIRR %: '+'{}%'.format(cagr))

In [8]:
# get start and end date
start_date, end_date = get_start_end_date()

# get portfolio and prospects data
mypfs_df = get_mypfs_df()
mypps_df = get_mypps_df()
myinvmt_df = get_myinvmt_df()

# merge above datasets
mypf_df = pd.merge(mypfs_df, mypps_df, on="Symbol")

# seggregate dm and sv portfolio
dm_pf = mypf_df[mypf_df['InPortfolio'] == 'DM']
sv_pf = mypf_df[mypf_df['InPortfolio'] == 'SV']

# build portfolio stock dataframe
dm_stocks = get_stock_ids(dm_pf)
sv_stocks = get_stock_ids(sv_pf)
df_stocks = pd.concat([dm_pf,sv_pf], ignore_index = True)

# arrange common and diff stock features
common_cols = ['Symbol', 'Target', 'Criteria', 'Strategy', 'CumlRnk', 'LatestQtr', 'StarStock', 'Conviction', 'Category', 'InFolio', 'XIRR', 'MBQ']
diff_cols = ['Symbol', 'AvgCost', 'Shares']
df_stocks = arrange_features(df_stocks, common_cols, diff_cols)

# get common features
stock_ids = df_stocks['Symbol'].values
df_common_features = get_common_features(stock_ids, df_stocks)

df_common_features.reset_index(drop=True, inplace=True)
df_common_features.drop(['Date'], axis=1, inplace=True)
# get and print portfolio features
df_portfolio_features = get_portfolio_features(df_common_features)

print_portfolio_stats(df_portfolio_features, myinvmt_df)

df = df_portfolio_features
#plot_pie_chart(df, 'CapType', 'Current')
list_ox40n = list(df[df['MBQ'].str.contains('OX40N', na=False)]['Symbol'].values)

Run date time (IST): 2026-07-06 16:43:16
-------------------
qualified stocks: 92
with latest results: 31
still star stocks: 20
-------------------
Initial Investment:  1.40 C
CY Investment:  1.82 C
Reserve:  1.49 K
Current:  1.54 C
-------------------
Today PnL: 28.81 K (0.19%)
Current PnL: -29.51 L (-16.18%)
CY Booked + Current PnL: -27.43 L (-15.04%)
-------------------
Total profit:  4.76 L
Total loss:  -34.27 L
-------------------
Total Booked + Current PnL: 15.44 L (11.07%)
Total Booked PnL: 44.95 L (32.22%)
Curr Year Booked PnL: 2.08 L (1.35%)
Prev Year Booked PnL: 42.87 L (30.73%)
===================
Est FTT:  2.55 C
Est FTT PnL: 1.01 C (65.94%)
===================
Deployed:  1.40 C
Current:  1.54 C
CAGR/XIRR %: 4.44%

In [9]:
# top 5 near their targets
cols = ['Symbol', 'Today P/L%', 'Current P/L%', 'FTT%', 'OTT%', 'FTT Amt', 'Current P/L', 'Current', 'FTT', 'Dev%_PE', 'RSI_14','Conviction', 'Spread%',  'CumlRnk', 'RRR Ind', 'CurrAlloc%', 'Gained%', 'Criteria', 'Strategy', 'Category']
df_tmp = df_portfolio_features[~df_portfolio_features['Symbol'].isin(['ENRIN','BLUSPRING','DIGITIDE'])]
df_tmp = df_tmp.sort_values(by = 'FTT Amt', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
59,PIDILITIND,1.18,14.58,3.30,18.37,5336.0,20580.0,161690.0,1670.26,-19.70,71.0,X-LC,7.35,5.0,3.86,1.05,26.96,X40,ATH,CHEMICALS
49,JSWINFRA,-0.63,10.30,5.56,16.43,13601.0,22846.0,244620.0,342.00,-5.50,63.0,X-MC,11.06,61.0,1.68,1.59,38.69,X40N,NTT,REALTY
83,TTKPRESTIG,0.36,-18.56,22.91,0.09,18803.0,-18705.0,82072.0,770.00,90.39,69.0,M-SC,5.67,250.0,-0.99,0.53,46.14,OX40N,NTT,DURABLES
56,MEDANTA,0.03,15.58,9.98,27.12,20361.0,27499.0,204016.0,1486.00,12.08,74.0,X-SC,7.42,87.0,1.35,1.33,40.58,XY24,NTT,HEALTHCARE
17,CIPLA,0.97,19.20,11.94,33.43,21798.0,29404.0,182565.0,1648.14,-7.62,71.0,X-LC,2.20,18.0,1.35,1.19,24.63,X40N,ATH,PHARMA

In [10]:
# top 5 today
df_tmp = df_portfolio_features.sort_values(by = 'Today P/L%', ascending=False)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
22,DIXON,6.81,-3.08,42.30,37.92,106924.0,-8022.0,252776.0,18931.72,-58.81,71.0,X-MC,8.34,54.0,-0.08,1.65,37.54,X40N,ATH,IT
1,ABBOTINDIA,3.73,-9.89,31.03,18.07,50008.0,-17695.0,161160.0,35195.00,-23.42,62.0,X-MC,6.28,58.0,-0.35,1.05,6.67,X40,ATH,PHARMA
44,INDUSINDBK,3.64,-25.45,78.25,32.89,45040.0,-19648.0,57559.0,1800.00,-371.01,72.0,L-MC,7.88,258.0,-0.44,0.37,41.91,XR,NTT,BANKS
34,HDFCBANK,3.60,-0.72,29.30,28.37,68324.0,-1697.0,233188.0,1073.00,-15.60,75.0,X-LC,12.82,26.0,-0.02,1.52,15.31,X40,BTT,BANKS
9,BANDHANBNK,3.38,-0.24,92.87,92.42,258089.0,-656.0,277903.0,400.00,138.51,54.0,H-SC,21.30,174.0,-0.00,1.81,53.09,XY24,NTT,BANKS

In [11]:
# bottom 5 today
df_tmp = df_portfolio_features.sort_values(by = 'Today P/L%', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
87,VBL,-4.06,-0.04,35.43,35.37,111857.0,-128.0,315714.0,670.16,-11.77,38.0,X-LC,9.65,13.0,-0.00,2.05,29.76,X40N,ATH,FMCG
51,KOTAKBANK,-3.89,1.88,18.87,21.11,26622.0,2608.0,141081.0,453.24,-12.44,39.0,X-LC,4.29,12.0,0.10,0.92,7.89,X40,ATH,BANKS
62,RAJOOENG,-3.74,-50.53,182.19,39.61,92389.0,-51790.0,50710.0,143.10,-66.59,33.0,H-SC,19.39,136.0,-0.56,0.33,8.63,AR,ATH,MISC
37,HONAUT,-2.53,-0.14,51.52,51.31,99215.0,-263.0,192575.0,58357.33,-16.97,61.0,X-SC,12.59,90.0,-0.00,1.25,46.31,X40N,ATH,ELECTRICAL
8,BAJAJHLDNG,-2.35,-3.26,31.94,27.63,58745.0,-6202.0,183923.0,14274.15,-10.63,60.0,X-LC,5.22,28.0,-0.11,1.20,25.24,X40,ATH,FINANCE

In [12]:
# top 5 to exit based on CumlRnk
df_tmp = df_portfolio_features[~df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])]
df_tmp = df_tmp[(df_tmp['Current P/L%'] > -1) & (df_tmp['Current P/L%'] < 1)].sort_values(by = 'CumlRnk', ascending=False)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
9,BANDHANBNK,3.38,-0.24,92.87,92.42,258089.0,-656.0,277903.0,400.0,138.51,54.0,H-SC,21.3,174.0,-0.0,1.81,53.09,XY24,NTT,BANKS

In [13]:
# OX40N stocks to exit
df_tmp = df_portfolio_features[(df_portfolio_features['Symbol'].isin(list_ox40n))].sort_values(by = 'Current P/L%', ascending=False)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
25,FINCABLES,-1.19,37.68,51.02,107.91,103708.0,55625.0,203269.0,1641.55,23.80,48.0,M-SC,26.83,220.0,0.54,1.32,52.93,OX40N,ATH,CABLES
72,SIS,0.08,-2.14,23.91,21.26,25980.0,-2376.0,108656.0,528.00,2592.23,55.0,H-SC,25.22,168.0,-0.09,0.71,61.55,OX40N,NTT,MISC
16,CERA,1.72,-14.08,44.19,23.89,66786.0,-24770.0,151133.0,9475.00,-17.18,68.0,H-SC,14.15,153.0,-0.37,0.98,45.24,OX40N,NTT,CERAMICS
83,TTKPRESTIG,0.36,-18.56,22.91,0.09,18803.0,-18705.0,82072.0,770.00,90.39,69.0,M-SC,5.67,250.0,-0.99,0.53,46.14,OX40N,NTT,DURABLES
43,INDIGOPNTS,1.21,-23.37,30.52,0.02,40827.0,-40788.0,133771.0,1408.00,104.24,67.0,M-SC,4.88,222.0,-1.00,0.87,51.77,OX40N,NTT,PAINTS

In [14]:
# top 5 to book for rotation
df_tmp = df_portfolio_features[(df_portfolio_features['Current P/L%'] > 20) ].sort_values(by = 'CumlRnk', ascending=False)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
25,FINCABLES,-1.19,37.68,51.02,107.91,103708.0,55625.0,203269.0,1641.55,23.80,48.0,M-SC,26.83,220.0,0.54,1.32,52.93,OX40N,ATH,CABLES
68,SATIN,0.97,42.56,6.50,51.83,25602.0,117596.0,393880.0,274.00,27.46,67.0,H-SC,40.92,159.0,4.59,2.56,91.88,XY24,NTT,FINANCE
91,ZYDUSLIFE,0.64,21.05,12.05,35.63,30569.0,44112.0,253686.0,1286.17,5.41,68.0,H-MC,14.68,120.0,1.44,1.65,33.38,AR,ATH,PHARMA
60,QUESS,0.93,20.40,44.44,73.90,57139.0,21782.0,128575.0,424.00,-34.99,86.0,X-SC,20.57,80.0,0.38,0.84,75.27,XY24,NTT,MISC

In [15]:
# top 5 to monitor for exit
df_tmp = df_portfolio_features[~df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])]
df_tmp = df_tmp[(df_tmp['Current P/L%'] > 0) ].sort_values(by = 'Dev%_PE', ascending=False)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
75,SURYODAY,-0.28,3.46,18.92,23.03,35054.0,6202.0,185273.0,216.00,101.75,65.0,H-SC,20.12,166.0,0.18,1.21,55.99,XR,NTT,BANKS
74,STARHEALTH,0.18,12.50,30.90,47.26,97722.0,35131.0,316254.0,761.00,77.56,67.0,H-SC,15.43,173.0,0.36,2.06,37.76,XY24,NTT,INSURANCE
68,SATIN,0.97,42.56,6.50,51.83,25602.0,117596.0,393880.0,274.00,27.46,67.0,H-SC,40.92,159.0,4.59,2.56,91.88,XY24,NTT,FINANCE
25,FINCABLES,-1.19,37.68,51.02,107.91,103708.0,55625.0,203269.0,1641.55,23.80,48.0,M-SC,26.83,220.0,0.54,1.32,52.93,OX40N,ATH,CABLES
91,ZYDUSLIFE,0.64,21.05,12.05,35.63,30569.0,44112.0,253686.0,1286.17,5.41,68.0,H-MC,14.68,120.0,1.44,1.65,33.38,AR,ATH,PHARMA

In [16]:
# top 5 to book for rotation from weak conviction
df_tmp = df_portfolio_features[~df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])]
df_tmp = df_tmp[~df_tmp['Criteria'].isin(['XY25','XY24','X40', 'X40N'])].sort_values(by = 'RRR Ind', ascending=False)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
91,ZYDUSLIFE,0.64,21.05,12.05,35.63,30569.0,44112.0,253686.0,1286.17,5.41,68.0,H-MC,14.68,120.0,1.44,1.65,33.38,AR,ATH,PHARMA
73,SONACOMS,1.12,15.47,20.10,38.69,23479.0,15653.0,116812.0,801.69,-8.45,77.0,M-MC,19.05,193.0,0.67,0.76,65.73,AR,ATH,AUTO
25,FINCABLES,-1.19,37.68,51.02,107.91,103708.0,55625.0,203269.0,1641.55,23.80,48.0,M-SC,26.83,220.0,0.54,1.32,52.93,OX40N,ATH,CABLES
75,SURYODAY,-0.28,3.46,18.92,23.03,35054.0,6202.0,185273.0,216.00,101.75,65.0,H-SC,20.12,166.0,0.18,1.21,55.99,XR,NTT,BANKS
72,SIS,0.08,-2.14,23.91,21.26,25980.0,-2376.0,108656.0,528.00,2592.23,55.0,H-SC,25.22,168.0,-0.09,0.71,61.55,OX40N,NTT,MISC

In [17]:
# top 5 to accumulate based on lowest RSI_14
df_tmp = df_portfolio_features[df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])].sort_values(by = 'RSI_14', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
35,HDFCLIFE,-0.62,-7.72,43.82,32.71,60572.0,-11571.0,138229.0,811.41,-28.00,38.0,X-LC,15.90,31.0,-0.19,0.90,3.84,X40,ATH,INSURANCE
87,VBL,-4.06,-0.04,35.43,35.37,111857.0,-128.0,315714.0,670.16,-11.77,38.0,X-LC,9.65,13.0,-0.00,2.05,29.76,X40N,ATH,FMCG
51,KOTAKBANK,-3.89,1.88,18.87,21.11,26622.0,2608.0,141081.0,453.24,-12.44,39.0,X-LC,4.29,12.0,0.10,0.92,7.89,X40,ATH,BANKS
23,DMART,1.76,-2.29,32.64,29.60,79603.0,-5718.0,243882.0,5391.45,-17.64,41.0,X-LC,3.62,14.0,-0.07,1.59,11.47,X40N,ATH,FMCG
79,TCS,-1.71,-39.60,106.74,24.88,298695.0,-183439.0,279834.0,4253.91,-48.87,41.0,X-LC,21.67,2.0,-0.61,1.82,3.78,X40,ATH,IT

In [18]:
# top 5 to accumulate based on Spread and CumlRnk
df_tmp = df_portfolio_features[df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])]
df_tmp = df_tmp[(df_tmp['CumlRnk'] < 100)].sort_values(by = 'Spread%', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
17,CIPLA,0.97,19.20,11.94,33.43,21798.0,29404.0,182565.0,1648.14,-7.62,71.0,X-LC,2.20,18.0,1.35,1.19,24.63,X40N,ATH,PHARMA
84,UNITDSPR,2.44,4.85,15.18,20.77,37266.0,11352.0,245496.0,1644.00,-6.93,70.0,X-MC,3.16,64.0,0.30,1.60,17.11,X40N,NTT,BREWERIES
19,COLPAL,1.59,-21.04,77.12,39.86,160379.0,-55405.0,207960.0,3683.41,-4.51,58.0,X-MC,3.17,62.0,-0.35,1.35,17.63,XY25,ATH,FMCG
11,BERGEPAINT,0.46,-3.83,30.31,25.32,75132.0,-9870.0,247879.0,680.00,-9.11,52.0,X-MC,3.51,68.0,-0.13,1.61,29.01,XY24,NTT,PAINTS
23,DMART,1.76,-2.29,32.64,29.60,79603.0,-5718.0,243882.0,5391.45,-17.64,41.0,X-LC,3.62,14.0,-0.07,1.59,11.47,X40N,ATH,FMCG

In [19]:
# top 5 to accumulate based on lowest Gained%
df_tmp = df_portfolio_features[df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])].sort_values(by = 'Gained%', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
58,PGHH,0.67,-32.84,96.57,32.01,138474.0,-70128.0,143392.0,17616.87,-54.64,42.0,X-MC,21.00,57.0,-0.51,0.93,1.69,X40,ATH,FMCG
79,TCS,-1.71,-39.60,106.74,24.88,298695.0,-183439.0,279834.0,4253.91,-48.87,41.0,X-LC,21.67,2.0,-0.61,1.82,3.78,X40,ATH,IT
35,HDFCLIFE,-0.62,-7.72,43.82,32.71,60572.0,-11571.0,138229.0,811.41,-28.00,38.0,X-LC,15.90,31.0,-0.19,0.90,3.84,X40,ATH,INSURANCE
47,ITC,-0.59,-24.07,56.81,19.06,146724.0,-81894.0,258272.0,452.00,-58.35,47.0,X-LC,13.06,1.0,-0.56,1.68,4.06,X40,NTT,FMCG
32,HAVELLS,0.03,-24.35,73.73,31.42,182935.0,-79876.0,248115.0,2052.62,-28.80,50.0,X-MC,12.66,63.0,-0.44,1.61,4.65,X40,ATH,ELECTRICAL

In [20]:
# top 5 to accumulate based on lowest CurrAlloc%
df_tmp = df_portfolio_features[df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])].sort_values(by = 'CurrAlloc%', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
10,BATAINDIA,-1.08,-55.55,204.16,35.20,116769.0,-71475.0,57195.0,2096.00,-25.05,47.0,X-SC,19.93,91.0,-0.61,0.37,13.43,X40,NTT,FOOTWEAR
64,RELAXO,0.91,-48.10,193.45,52.31,145747.0,-69819.0,75341.0,1176.00,-44.73,65.0,X-SC,11.21,92.0,-0.48,0.49,68.45,X40N,NTT,FOOTWEAR
60,QUESS,0.93,20.40,44.44,73.90,57139.0,21782.0,128575.0,424.00,-34.99,86.0,X-SC,20.57,80.0,0.38,0.84,75.27,XY24,NTT,MISC
35,HDFCLIFE,-0.62,-7.72,43.82,32.71,60572.0,-11571.0,138229.0,811.41,-28.00,38.0,X-LC,15.90,31.0,-0.19,0.90,3.84,X40,ATH,INSURANCE
51,KOTAKBANK,-3.89,1.88,18.87,21.11,26622.0,2608.0,141081.0,453.24,-12.44,39.0,X-LC,4.29,12.0,0.10,0.92,7.89,X40,ATH,BANKS

In [21]:
# top 5 to accumulate based on CumlRnk
df_tmp = df_portfolio_features.sort_values(by = 'CumlRnk', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
47,ITC,-0.59,-24.07,56.81,19.06,146724.0,-81894.0,258272.0,452.00,-58.35,47.0,X-LC,13.06,1.0,-0.56,1.68,4.06,X40,NTT,FMCG
79,TCS,-1.71,-39.60,106.74,24.88,298695.0,-183439.0,279834.0,4253.91,-48.87,41.0,X-LC,21.67,2.0,-0.61,1.82,3.78,X40,ATH,IT
45,INFY,-0.48,-29.05,89.22,34.24,198059.0,-90899.0,221989.0,1972.00,-44.12,42.0,X-LC,20.72,3.0,-0.46,1.44,5.77,X40,NTT,IT
81,TMPV,0.86,-21.00,72.89,36.58,204901.0,-74731.0,281110.0,600.00,-83.62,41.0,X-LC,7.19,4.0,-0.36,1.83,18.14,XY24,NTT,AUTO
59,PIDILITIND,1.18,14.58,3.30,18.37,5336.0,20580.0,161690.0,1670.26,-19.70,71.0,X-LC,7.35,5.0,3.86,1.05,26.96,X40,ATH,CHEMICALS

In [22]:
# top 5 for average up
df_tmp = df_portfolio_features[(df_portfolio_features['Dev%_200'] > 5)].sort_values(by = 'CurrAlloc%', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
44,INDUSINDBK,3.64,-25.45,78.25,32.89,45040.0,-19648.0,57559.0,1800.00,-371.01,72.0,L-MC,7.88,258.0,-0.44,0.37,41.91,XR,NTT,BANKS
64,RELAXO,0.91,-48.10,193.45,52.31,145747.0,-69819.0,75341.0,1176.00,-44.73,65.0,X-SC,11.21,92.0,-0.48,0.49,68.45,X40N,NTT,FOOTWEAR
3,ALKYLAMINE,-1.54,-23.39,151.33,92.54,117051.0,-23615.0,77348.0,4520.85,-17.90,54.0,H-SC,8.97,142.0,-0.20,0.50,46.88,SR,ATH,CHEMICALS
83,TTKPRESTIG,0.36,-18.56,22.91,0.09,18803.0,-18705.0,82072.0,770.00,90.39,69.0,M-SC,5.67,250.0,-0.99,0.53,46.14,OX40N,NTT,DURABLES
72,SIS,0.08,-2.14,23.91,21.26,25980.0,-2376.0,108656.0,528.00,2592.23,55.0,H-SC,25.22,168.0,-0.09,0.71,61.55,OX40N,NTT,MISC

In [23]:
# top 5 RSP
df_tmp = df_portfolio_features.sort_values(by = 'RSP', ascending=False)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
64,RELAXO,0.91,-48.10,193.45,52.31,145747.0,-69819.0,75341.0,1176.0,-44.73,65.0,X-SC,11.21,92.0,-0.48,0.49,68.45,X40N,NTT,FOOTWEAR
60,QUESS,0.93,20.40,44.44,73.90,57139.0,21782.0,128575.0,424.0,-34.99,86.0,X-SC,20.57,80.0,0.38,0.84,75.27,XY24,NTT,MISC
0,5PAISA,-1.81,-27.53,55.79,12.90,88343.0,-60146.0,158350.0,593.0,133.17,74.0,H-SC,3.95,170.0,-0.68,1.03,52.81,OX40N,NTT,FINANCE
49,JSWINFRA,-0.63,10.30,5.56,16.43,13601.0,22846.0,244620.0,342.0,-5.50,63.0,X-MC,11.06,61.0,1.68,1.59,38.69,X40N,NTT,REALTY
83,TTKPRESTIG,0.36,-18.56,22.91,0.09,18803.0,-18705.0,82072.0,770.0,90.39,69.0,M-SC,5.67,250.0,-0.99,0.53,46.14,OX40N,NTT,DURABLES

In [24]:
# Top N allocation
df_tmp = df_portfolio_features.sort_values(by = 'CurrAlloc%', ascending=False)
top_n_values = [10, 25, 50]

sum_df = pd.DataFrame({
    'Top_N': top_n_values,
    'Sum_Alloc%': [df_tmp['CurrAlloc%'].head(n).sum() for n in top_n_values]
})

sum_df

   Top_N  Sum_Alloc%
0     10       19.31
1     25       42.70
2     50       72.80

In [25]:
# market-cap-wise allocation
df_tmp = df_portfolio_features[cols]
df_tmp.groupby(df_tmp['Conviction'].str[-2:])['CurrAlloc%'].sum().sort_values(ascending=False)

Conviction
SC    43.63
LC    30.21
MC    26.11
Name: CurrAlloc%, dtype: float64

In [26]:
# criteria-wise allocation
df_portfolio_features.groupby('Criteria')['CurrAlloc%'].sum().sort_values(ascending=False)

Criteria
XY24     28.00
X40      24.45
X40N     17.49
XR        8.80
OX40N     7.15
AR        6.75
XY25      6.45
SR        0.86
Name: CurrAlloc%, dtype: float64

In [27]:
# conviction-wise allocation
df_portfolio_features.groupby('Conviction')['CurrAlloc%'].sum().sort_values(ascending=False)

Conviction
X-LC    28.26
H-SC    22.89
X-MC    20.94
X-SC    10.10
M-SC    10.06
H-MC     2.73
M-MC     2.07
H-LC     1.16
M-LC     0.79
L-SC     0.58
L-MC     0.37
Name: CurrAlloc%, dtype: float64

In [28]:
# sector-wise stats
df_tmp = df_portfolio_features.groupby('Category')[['CurrAlloc%', 'Current', 'Current P/L', 'FTT Amt']].sum().sort_values(by=['Current', 'Current P/L'], ascending=False)
df_tmp['Current P/L%'] = round(df_tmp['Current P/L'] * 100 / df_tmp['Current'], 2)
df_tmp['FTT%'] = round(df_tmp['FTT Amt'] * 100 / df_tmp['Current'], 2)
cols = ['CurrAlloc%', 'Current P/L%', 'FTT%']
df_tmp[cols].sort_values(by=['CurrAlloc%'], ascending=False)

               CurrAlloc%  Current P/L%    FTT%
Category
FMCG                14.44        -19.15   60.94
FINANCE             11.42         -5.16   50.73
IT                   9.58        -52.98  129.46
MISC                 7.17        -21.62   73.81
AUTO                 6.74         -5.64   45.03
BANKS                5.83         -1.47   48.39
PAINTS               5.55        -15.49   35.19
INSURANCE            5.22         -3.26   38.09
PHARMA               5.14          6.17   22.87
ELECTRICAL           4.02        -14.15   54.44
CHEMICALS            2.16        -21.67   93.85
HEALTHCARE           2.10        -11.13   40.13
APPARELS             1.94          9.81   20.48
AC                   1.74        -19.07   51.36
FOOTWEAR             1.72        -66.52  133.28
DURABLES             1.61        -55.83   93.74
BREWERIES            1.60          4.62   15.18
REALTY               1.59          9.34    5.56
TRAVEL               1.53        -90.74  186.25
CERAMICS             1.44        -38.01   79.94
CABLES               1.32         27.37   51.02
ENGINEERING          1.29        -22.33   78.28
REFINERIES           1.11        -17.90   47.73
CEMENT               1.09        -59.93  179.58
JEWELLERY            1.03       -102.42  172.75
ENTERTAINMENT        0.74        -69.91  171.24
TEXTILES             0.42        -42.28   82.86
HOTELS               0.41        -81.97  146.15

In [29]:
# money to be made criteria-wise
df_portfolio_features.groupby('Criteria')['FTT Amt'].agg(['sum', 'count']).sort_values(by='sum', ascending=False)

                sum  count
Criteria
XY24      3295910.0     21
X40       1918577.0     19
XR        1328954.0     13
AR        1136276.0      9
X40N      1032431.0     13
OX40N      691208.0     10
XY25       444156.0      5
SR         285314.0      2

In [30]:
# money to be made conviction-wise
df_portfolio_features.groupby('Conviction')['FTT Amt'].agg(['sum', 'count']).sort_values(by='sum', ascending=False)

                  sum  count
Conviction
H-SC        3258962.0     24
X-LC        1936409.0     21
X-MC        1498036.0     15
M-SC        1368745.0     14
X-SC        1250705.0      9
H-MC         278351.0      2
L-SC         202648.0      2
M-LC         170752.0      1
M-MC          68175.0      2
H-LC          55003.0      1
L-MC          45040.0      1

In [31]:
# money to be made criteria and conviction-wise
df_portfolio_features.groupby(['Conviction', 'Criteria'])['FTT Amt'].agg(['sum', 'count']).sort_values(by='sum', ascending=False)

                           sum  count
Conviction Criteria
X-LC       X40       1047865.0     10
H-SC       AR         954025.0      5
           XY24       932094.0      6
M-SC       XY24       812551.0      6
H-SC       XR         801872.0      7
X-SC       XY24       739583.0      4
X-MC       X40        657758.0      7
           X40N       380709.0      4
X-LC       X40N       353554.0      6
           XY24       350431.0      2
X-SC       X40N       298168.0      3
M-SC       OX40N      294101.0      5
H-SC       OX40N      285657.0      4
           SR         285314.0      2
H-MC       XY24       247782.0      1
X-MC       XY25       246100.0      2
           XY24       213469.0      2
X-SC       X40        212954.0      2
M-SC       XR         188893.0      2
M-LC       XR         170752.0      1
X-LC       XY25       153360.0      2
L-SC       OX40N      111450.0      1
           XR          91198.0      1
M-SC       AR          73200.0      1
H-LC       AR          55003.0      1
L-MC       XR          45040.0      1
M-MC       XY25        44696.0      1
X-LC       XR          31199.0      1
H-MC       AR          30569.0      1
M-MC       AR          23479.0      1

In [32]:
# notebook execution time

end_time = time.time()
execution_time = round(end_time - start_time, 0)
print(f"Notebook execution time: {execution_time} seconds")

Notebook execution time: 31.0 seconds