<a href="https://colab.research.google.com/github/ankit-rathi/Quantvesting_v2/blob/main/myStocks_Portfolio_Analysis.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
'''
!pip install pandas==2.2.2 -qq
!pip install pyxirr -qq
!pip install ta -qq
!pip install yfinance==0.2.59 -qq
'''

'\n!pip install pandas==2.2.2 -qq\n!pip install pyxirr -qq\n!pip install ta -qq\n!pip install yfinance==0.2.59 -qq\n'

In [2]:
# import libraries

import numpy as np
import pandas as pd
import datetime
import warnings
warnings.filterwarnings('ignore')
import yfinance as yfin
import ta
import matplotlib.pyplot as plt
import requests

In [3]:
# notebook start time
import time
import datetime
import pytz

start_time = time.time()

# function to print date timestamp
def print_date_time():
  tz_NY = pytz.timezone('Asia/Kolkata')
  datetime_NY = datetime.datetime.now(tz_NY)
  print("Run date time (IST):", datetime_NY.strftime("%Y-%m-%d %H:%M:%S"))

In [4]:
# function to get booked and reserved amount
def get_amt():
  # fetch the JSON data from the URL
  url = "https://raw.githubusercontent.com/ankit-rathi/Tradevesting_v1/main/data/myPortfolioAmts.json"
  response = requests.get(url)
  pf_amts = response.json()  # parse the JSON data

  # extract values from the JSON
  py_booked_amt_dm = pf_amts["py_booked_amt_dm"]
  py_booked_amt_sv = pf_amts["py_booked_amt_sv"]
  cy_booked_amt_dm = pf_amts["cy_booked_amt_dm"]
  cy_booked_amt_sv = pf_amts["cy_booked_amt_sv"]
  reserve_amt_dm = pf_amts["reserve_amt_dm"]
  reserve_amt_sv = pf_amts["reserve_amt_sv"]

  # perform calculations
  py_booked_amt = py_booked_amt_dm + py_booked_amt_sv
  cy_booked_amt = cy_booked_amt_dm + cy_booked_amt_sv
  reserve_amt = reserve_amt_dm + reserve_amt_sv
  total_booked_amt = py_booked_amt + cy_booked_amt

  return total_booked_amt, reserve_amt, cy_booked_amt, py_booked_amt

gen_output = 0

In [5]:
# function to format the amount
def format_amt(number):
    abs_number = abs(number)

    if abs_number >= 1_00_00_000:  # Crores
        formatted_amt = f"{number / 1_00_00_000:.2f} C"
    elif abs_number >= 1_00_000:  # Lakhs
        formatted_amt = f"{number / 1_00_000:.2f} L"
    elif abs_number >= 1_000:  # Thousands
        formatted_amt = f"{number / 1_000:.2f} K"
    else:
        formatted_amt = f"{number:.2f}"

    return formatted_amt

# function to set start and end date
def get_start_end_date():
  start_date = (datetime.date.today() + datetime.timedelta(days=-365)).strftime('%Y-%m-%d')
  end_date = (datetime.date.today() + datetime.timedelta(days=1)).strftime('%Y-%m-%d')
  return start_date, end_date

# function to fetch my portfolio csv
def get_mypfs_df():
  mypfs_df = pd.read_csv('https://raw.githubusercontent.com/ankit-rathi/Tradevesting_v1/main/data/myPortfolioStocks.csv')
  return mypfs_df

# function to fetch my prospects csv
def get_mypps_df():
  mypps_df = pd.read_csv('https://raw.githubusercontent.com/ankit-rathi/Tradevesting_v1/main/data/myProspectsScrips.csv')
  return mypps_df

# function to fetch screener data
def get_myscreen_df():
  myscreen_df = pd.read_csv('https://raw.githubusercontent.com/ankit-rathi/Tradevesting_v1/main/data/myScreenerDB.csv')
  return myscreen_df

# function to fetch momentum data
def get_myinvmt_df():
  myinvmt_df = pd.read_csv('https://raw.githubusercontent.com/ankit-rathi/Tradevesting_v1/main/data/myInvestments.csv')
  return myinvmt_df

# function to get the stock ids
def get_stock_ids(df_pf):
  stock_n100 = df_pf['Symbol'].unique()

  exclude = ['CADILAHC','MMTC', 'MASFIN']

  stock_ids = df_pf[~df_pf['Symbol'].isin(exclude) ]['Symbol'].unique()

  #mypf = mypf[mypf.Forecast.notnull()]
  #stock_ids = mypf['Symbol'].unique()

  #stock_ids.sort()
  return stock_ids

# get features from screener data
def get_screener_features():
  myscreen_df = get_myscreen_df()
  cols = ['Symbol', 'EPS', 'MedPE', 'ROCE%', 'ROE%', 'CapType']
  return myscreen_df[cols]

# get relative strength
def get_relative_strength(stock_list):

    # Dictionary to store stock tickers and their corresponding percentage price change
    stock_changes = {}

    # Loop through each stock and fetch its price data
    for stock in stock_list:
        try:
            # Download the stock data for the given date range
            stock_data = yfin.Ticker(stock + '.NS').history(period='1mo', interval='1d')[map(str.title, ['open', 'close', 'low', 'high', 'volume'])]

            # Calculate the percentage change for the stock
            if len(stock_data) > 0:
                start_price = stock_data['Close'].iloc[0]
                end_price = stock_data['Close'].iloc[-1]
                percent_change = round(((end_price - start_price) / start_price) * 100, 2)
                stock_changes[stock] = percent_change
            else:
                stock_changes[stock] = np.nan  # If no data is available, set to NaN

        except Exception as e:
            print(f"Error fetching data for {stock}: {e}")
            stock_changes[stock] = np.nan

    # Create a DataFrame with stock tickers and their percentage changes
    df = pd.DataFrame(list(stock_changes.items()), columns=['Symbol', 'Percent_Change'])

    # Drop any stocks with missing data (NaN values)
    df = df.dropna()

    # Calculate the percentile rank based on percentage change
    df['RSP'] = round(df['Percent_Change'].rank(pct=True) * 100, 2)
    cols = ['Symbol', 'RSP']
    df = df[cols]
    # Sort by percentile rank (optional)
    df = df.sort_values(by='RSP', ascending=False).reset_index(drop=True)

    return df

In [6]:
# function to get stock technicals
def stock_prec_dev(stock_symbol):
    #stock_symbol = 'ULTRACEMCO.NS'
    short_window = 20
    mid_window = 50
    long_window = 200
    moving_avg = 'SMA'

    start = datetime.datetime(*map(int, start_date.split('-')))
    end = datetime.datetime(*map(int, end_date.split('-')))

    stock_df = yfin.Ticker(stock_symbol + '.NS').history(period='max', interval='1d')[map(str.title, ['open', 'close', 'low', 'high', 'volume'])]

    stock_df['Max'] = round(max(stock_df['Close']),2)
    stock_df = stock_df[(stock_df.index <= end_date) & (stock_df.index >= start_date)]
    stock_df['200_SMA'] = round(stock_df['Close'].rolling(window = 200, min_periods = 1).mean(),0)
    stock_df['Dev%_200'] = round((stock_df['Close'] - stock_df['200_SMA'])*100/stock_df['200_SMA'],2)
    stock_df.dropna(axis = 0, inplace = True) # remove any null rows

    stock_df['20_SMA'] = stock_df['Close'].rolling(window=20).mean()
    stock_df['50_SMA'] = stock_df['Close'].rolling(window=50).mean()
    stock_df['Symbol'] = stock_symbol

    stock_df['Close'] = round(stock_df['Close'],2)
    stock_df['Min'] = round(min(stock_df['Close']),2)
    stock_df['RSI_14'] = ta.momentum.RSIIndicator(close=stock_df['Close'], window=14).rsi()
    stock_df['RSI_14'] = round(stock_df['RSI_14'],0)
    stock_df['Prev_Close'] = stock_df['Close'].shift(1)
    stock_df.drop(['Open', 'Low', 'High', 'Volume'], axis=1, inplace=True)
    stock_df = stock_df.tail(1)

    max_SMA = max(stock_df['20_SMA'].item(), stock_df['50_SMA'].item(), stock_df['200_SMA'].item())
    min_SMA = min(stock_df['20_SMA'].item(), stock_df['50_SMA'].item(), stock_df['200_SMA'].item())
    ABS_Spread = max_SMA - min_SMA
    stock_df['Spread%'] = round((ABS_Spread / stock_df['200_SMA'].item()) * 100,2)

    return stock_df

# function to compute stock attributes
def get_common_features(stock_ids, df_mypf):

  df_prec_dev = pd.DataFrame()
  df_tmp = get_screener_features()
  df_rs = get_relative_strength(stock_ids)

  for stock_id in stock_ids:
      tmp = stock_prec_dev(stock_id)
      tmp = tmp.reset_index()
      df_prec_dev = pd.concat([df_prec_dev, tmp], ignore_index = True)
  df_prec_dev = pd.merge(df_prec_dev, df_mypf, on= 'Symbol')
  df_prec_dev = pd.merge(df_prec_dev, df_tmp, on= 'Symbol', how='left')
  df_prec_dev = pd.merge(df_prec_dev, df_rs, on= 'Symbol', how='left')
  #print(df_prec_dev.columns)
  df_prec_dev['Curr_PE'] = round(df_prec_dev['Close']/df_prec_dev['EPS'],1)
  df_prec_dev['Dev%_PE'] = round((df_prec_dev['Curr_PE'] - df_prec_dev['MedPE'])*100/df_prec_dev['MedPE'],2)
  df_prec_dev['Conviction'] = df_prec_dev['Conviction'] + '-' + df_prec_dev['CapType']
  return df_prec_dev

# function to arrange stock features
def arrange_features(df_stocks, common_cols, diff_cols):
  df_stocks_common = df_stocks[common_cols].drop_duplicates()
  df_stocks_diff = df_stocks[diff_cols]
  df_stocks_diff['Investment'] = df_stocks_diff['AvgCost'] * df_stocks_diff['Shares']
  df_stocks_diff = df_stocks_diff.groupby(['Symbol'])[['Shares', 'Investment']].aggregate(['sum']).reset_index()
  df_stocks_diff.columns = ['Symbol', 'Shares', 'Investment']
  df_stocks_diff['AvgCost'] = round(df_stocks_diff['Investment']/df_stocks_diff['Shares'],2)
  df_stocks = pd.merge(df_stocks_diff, df_stocks_common, on='Symbol')
  return df_stocks

# plot fact distribution across dimension
def plot_pie_chart(df, dimension, fact):
  # grouping the data by category and calculating the sum of fact for each type
  grouped_data = df.groupby(dimension)[fact].sum()

  # sorting the grouped data in descending order
  grouped_data = grouped_data.sort_values(ascending=False)

  # creating a pie chart
  grouped_data.plot.pie(autopct='%1.1f%%', startangle=90, figsize=(6, 6))

  # adding a title and displaying the plot
  plt.title(f'{dimension} {fact} Distribution')
  plt.ylabel('')  # To hide the y-label
  plt.show()

In [7]:
# function to get portfolio features

def get_portfolio_features(df_common_features):

  print_date_time()
  print('-------------------')

  #df_common_features["Target"] = df_common_features["Target"].fillna(df_common_features["Max"])
  df_common_features['NTT'] = np.where(df_common_features['Strategy']== 'NTT', df_common_features["Target"], df_common_features['Max'])
  df_common_features['LTT'] = np.where(df_common_features['Strategy']== 'BTT', df_common_features["Target"], df_common_features['Max'])
  df_common_features['BOL'] = df_common_features['Min']

  tmp_df = df_common_features[df_common_features['Symbol'].isin(mypf_df[mypf_df['InPortfolio'] != 'NA'].Symbol.values)]
  print('qualified stocks: '+str(len(tmp_df['Symbol'].unique())))
  tmp_df1 = tmp_df[tmp_df['LatestQtr'] == 1]
  print('with latest results: '+str(len(tmp_df1['Symbol'].unique())))
  tmp_df1 = tmp_df1[tmp_df1['StarStock'] == 1]
  print('still star stocks: '+str(len(tmp_df1['Symbol'].unique())))
  tmp_df['Investment'] = tmp_df['AvgCost'] * tmp_df['Shares']
  tmp_df['Current'] = round(tmp_df['Close'] * tmp_df['Shares'],0)
  tmp_df['Previous'] = tmp_df['Prev_Close'] * tmp_df['Shares']
  tmp_df['EstimatedST'] = tmp_df['NTT'] * tmp_df['Shares']
  tmp_df['EstimatedLT'] = tmp_df['LTT'] * tmp_df['Shares']
  tmp_df['Current P/L'] = round((tmp_df['Current'] - tmp_df['Investment']),0)
  tmp_df['Today P/L%'] = round((tmp_df['Current'] - tmp_df['Previous'])*100/tmp_df['Previous'],2)
  tmp_df['Current P/L%'] = round((tmp_df['Current'] - tmp_df['Investment'])*100/tmp_df['Investment'],2)
  tmp_df['EstimatedST P/L%'] = round((tmp_df['EstimatedST'] - tmp_df['Investment'])*100/tmp_df['Investment'],2)
  tmp_df['EstimatedLT P/L%'] = round((tmp_df['EstimatedLT'] - tmp_df['Investment'])*100/tmp_df['Investment'],2)
  tmp_df['NTT%'] = round((tmp_df['NTT'] - tmp_df['Close'])*100/tmp_df['Close'],2)
  tmp_df['LTT%'] = round((tmp_df['LTT'] - tmp_df['Close'])*100/tmp_df['Close'],2)
  tmp_df['Gained%'] = round((tmp_df['Close'] - tmp_df['BOL'])*100/tmp_df['BOL'],2)
  investment = round(sum(tmp_df['AvgCost']*tmp_df['Shares']),0)
  current = round(sum(tmp_df['Close']*tmp_df['Shares']),0)
  tmp_df['InitAlloc%'] = round(tmp_df['Investment']*100/investment,2)
  tmp_df['CurrAlloc%'] = round(tmp_df['Current']*100/current,2)
  tmp_df['FTT'] = tmp_df['LTT']
  tmp_df.loc[tmp_df['Strategy'] == 'NTT', 'FTT'] = tmp_df['NTT']
  tmp_df['FTT%'] = tmp_df['LTT%']
  tmp_df.loc[tmp_df['Strategy'] == 'NTT', 'FTT%'] = tmp_df['NTT%']
  tmp_df['FTT Amt'] = round(tmp_df['FTT%'] * tmp_df['Current']/100,0)
  tmp_df['OTT%'] = round((tmp_df['FTT'] - tmp_df['AvgCost'])*100/tmp_df['AvgCost'],2)
  tmp_df['RRR Ind'] = round(tmp_df['Current P/L']/tmp_df['FTT Amt'],2)
  tmp_df['Risk Ind'] = round(tmp_df['Current P/L%']*tmp_df['CurrAlloc%'],0)

  return tmp_df

# function to print portfolio features
def print_portfolio_stats(df_portfolio_features, myinvmt_df):
  from pyxirr import xirr

  total_booked_amt, reserve_amt, cy_booked_amt, py_booked_amt = get_amt()

  dates = myinvmt_df['Date'].values
  dates = np.append(dates, datetime.date.today().strftime('%d-%b-%y'))
  investment = myinvmt_df['Investment'].values
  dates= pd.to_datetime(dates)

  current = round(sum(df_portfolio_features['Close']*df_portfolio_features['Shares']),0) + reserve_amt
  investment_xirr = np.append(investment, current)
  cagr = round(xirr(pd.DataFrame({"dates": dates, "amounts": investment_xirr}))*100,2)

  investment = -sum(investment)
  invested = round(sum(df_portfolio_features['AvgCost']*df_portfolio_features['Shares']),0) + reserve_amt
  previous = round(sum(df_portfolio_features['Prev_Close']*df_portfolio_features['Shares']),0) + reserve_amt
  cy_invested = investment + py_booked_amt

  today_pnl_amount = current-previous
  today_pnl_percentage = round((current-previous)*100/previous,2)

  curr_pnl_amount = current-invested
  curr_pnl_percentage = round((curr_pnl_amount)*100/(cy_invested),2)

  cy_pnl_amount = cy_booked_amt + curr_pnl_amount
  cy_pnl_percentage = round((cy_pnl_amount)*100/cy_invested,2)

  overall_pnl_amount = total_booked_amt + curr_pnl_amount
  overall_pnl_percentage = round((overall_pnl_amount)*100/investment,2)

  estimate_st = round(sum(df_portfolio_features['FTT']*df_portfolio_features['Shares']),0)  + reserve_amt
  est_st_pnl_amount = estimate_st-current
  est_st_pnl_percentage = round((est_st_pnl_amount)*100/current,2)

  estimate_lt = round(sum(df_portfolio_features['LTT']*df_portfolio_features['Shares']),0)  + reserve_amt
  est_lt_pnl_amount = estimate_lt-current
  est_lt_pnl_percentage = round((est_lt_pnl_amount)*100/current,2)

  total_profit = round(sum(df_portfolio_features[df_portfolio_features['Current P/L%'] > 0]['Current']) - sum(df_portfolio_features[df_portfolio_features['Current P/L%'] > 0]['Investment']),0)
  total_loss = round(sum(df_portfolio_features[df_portfolio_features['Current P/L%'] < 0]['Current']) - sum(df_portfolio_features[df_portfolio_features['Current P/L%'] < 0]['Investment']),0)

  cy_booked_percentage = round((cy_booked_amt)*100/current,2)
  py_booked_percentage = round((py_booked_amt)*100/investment,2)
  total_booked_percentage = round((total_booked_amt)*100/investment,2)

  print('-------------------')
  print('Initial Investment: ', format_amt(investment))
  print('CY Investment: ', format_amt(cy_invested))
  print('Reserve: ', format_amt(reserve_amt))
  print('Current: ',  format_amt(current))
  print('-------------------')
  print('Today PnL: '+ '{} ({}%)'.format(format_amt(today_pnl_amount), today_pnl_percentage))
  print('Current PnL: '+ '{} ({}%)'.format(format_amt(curr_pnl_amount), curr_pnl_percentage))
  print('CY Booked + Current PnL: '+ '{} ({}%)'.format(format_amt(cy_pnl_amount), cy_pnl_percentage))
  print('-------------------')
  print('Total profit: ', format_amt(total_profit))
  print('Total loss: ', format_amt(total_loss))
  print('-------------------')
  print('Total Booked + Current PnL: '+ '{} ({}%)'.format(format_amt(overall_pnl_amount), overall_pnl_percentage))
  print('Total Booked PnL: '+ '{} ({}%)'.format(format_amt(total_booked_amt), total_booked_percentage))
  print('Curr Year Booked PnL: '+ '{} ({}%)'.format(format_amt(cy_booked_amt), cy_booked_percentage))
  print('Prev Year Booked PnL: '+ '{} ({}%)'.format(format_amt(py_booked_amt), py_booked_percentage))
  print('===================')
  print('Est FTT: ',  format_amt(estimate_st))
  print('Est FTT PnL: '+ '{} ({}%)'.format(format_amt(est_st_pnl_amount), est_st_pnl_percentage))

  print('===================')
  print('Deployed: ', format_amt(investment))

  print('Current: ', format_amt(current))

  print('CAGR/XIRR %: '+'{}%'.format(cagr))

In [8]:
# get start and end date
start_date, end_date = get_start_end_date()

# get portfolio and prospects data
mypfs_df = get_mypfs_df()
mypps_df = get_mypps_df()
myinvmt_df = get_myinvmt_df()

# merge above datasets
mypf_df = pd.merge(mypfs_df, mypps_df, on="Symbol")

# seggregate dm and sv portfolio
dm_pf = mypf_df[mypf_df['InPortfolio'] == 'DM']
sv_pf = mypf_df[mypf_df['InPortfolio'] == 'SV']

# build portfolio stock dataframe
dm_stocks = get_stock_ids(dm_pf)
sv_stocks = get_stock_ids(sv_pf)
df_stocks = pd.concat([dm_pf,sv_pf], ignore_index = True)

# arrange common and diff stock features
common_cols = ['Symbol', 'Target', 'Criteria', 'Strategy', 'CumlRnk', 'LatestQtr', 'StarStock', 'Conviction', 'Category', 'InFolio', 'XIRR', 'MBQ']
diff_cols = ['Symbol', 'AvgCost', 'Shares']
df_stocks = arrange_features(df_stocks, common_cols, diff_cols)

# get common features
stock_ids = df_stocks['Symbol'].values
df_common_features = get_common_features(stock_ids, df_stocks)

df_common_features.reset_index(drop=True, inplace=True)
df_common_features.drop(['Date'], axis=1, inplace=True)
# get and print portfolio features
df_portfolio_features = get_portfolio_features(df_common_features)

print_portfolio_stats(df_portfolio_features, myinvmt_df)

df = df_portfolio_features
#plot_pie_chart(df, 'CapType', 'Current')
list_ox40n = list(df[df['MBQ'].str.contains('OX40N', na=False)]['Symbol'].values)

Run date time (IST): 2026-03-13 09:43:11
-------------------
qualified stocks: 86
with latest results: 26
still star stocks: 15

-------------------
Initial Investment:  1.36 C
CY Investment:  1.62 C
Reserve:  66.25 K
Current:  1.35 C
-------------------
Today PnL: -93.48 K (-0.69%)
Current PnL: -42.09 L (-25.9%)
CY Booked + Current PnL: -26.41 L (-16.25%)
-------------------
Total profit:  1.09 L
Total loss:  -43.18 L
-------------------
Total Booked + Current PnL: 57.23 K (0.42%)
Total Booked PnL: 42.66 L (31.48%)
Curr Year Booked PnL: 15.68 L (11.63%)
Prev Year Booked PnL: 26.98 L (19.91%)
===================
Est FTT:  2.47 C
Est FTT PnL: 1.12 C (83.39%)
===================
Deployed:  1.36 C
Current:  1.35 C
CAGR/XIRR %: -0.25%

In [9]:
# top 5 near their targets
cols = ['Symbol', 'Today P/L%', 'Current P/L%', 'FTT%', 'OTT%', 'FTT Amt', 'Current P/L', 'Current', 'FTT', 'Dev%_PE', 'RSI_14','Conviction', 'Spread%',  'CumlRnk', 'RRR Ind', 'CurrAlloc%', 'Gained%', 'Criteria', 'Strategy', 'Category']
df_tmp = df_portfolio_features[~df_portfolio_features['Symbol'].isin(['ENRIN','BLUSPRING','DIGITIDE'])]
df_tmp = df_tmp.sort_values(by = 'FTT Amt', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
19,COALINDIA,0.10,15.71,1.69,17.67,2942.0,23644.0,174104.0,478.51,39.17,70.0,L-LC,12.65,185.0,8.04,1.30,35.20,XY25,ATH,MINING
77,TTKPRESTIG,1.44,-23.74,31.25,0.09,24016.0,-23926.0,76851.0,770.00,78.44,62.0,M-SC,15.17,250.0,-1.00,0.57,29.85,OX40N,NTT,DURABLES
50,MASFIN,-0.77,-7.62,31.60,21.57,28601.0,-7470.0,90510.0,397.04,-20.51,38.0,H-SC,3.61,167.0,-0.26,0.67,25.56,XR,ATH,FINANCE
37,ICICIGI,-0.43,-2.15,21.96,19.34,43001.0,-4295.0,195814.0,2252.93,-17.63,40.0,X-MC,1.89,66.0,-0.10,1.46,10.81,X40,ATH,INSURANCE
78,UNITDSPR,-0.19,-0.03,20.80,20.77,48688.0,-69.0,234075.0,1644.00,-11.40,47.0,X-MC,1.28,64.0,-0.00,1.74,6.68,X40N,NTT,BREWERIES

In [10]:
# top 5 today
df_tmp = df_portfolio_features.sort_values(by = 'Today P/L%', ascending=False)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
25,DMART,1.64,-3.40,34.17,29.60,82387.0,-8490.0,241110.0,5391.45,-18.53,64.0,X-LC,7.27,14.0,-0.10,1.80,10.21,X40N,ATH,FMCG
77,TTKPRESTIG,1.44,-23.74,31.25,0.09,24016.0,-23926.0,76851.0,770.00,78.44,62.0,M-SC,15.17,250.0,-1.00,0.57,29.85,OX40N,NTT,DURABLES
1,ABB,1.38,19.21,22.11,45.57,68957.0,50261.0,311880.0,7934.00,-23.35,71.0,H-MC,11.17,125.0,0.73,2.32,38.50,AR,NTT,ELECTRICAL
35,HINDUNILVR,1.36,-15.74,34.91,13.67,75612.0,-40473.0,216590.0,2922.00,-37.41,32.0,X-LC,5.66,9.0,-0.54,1.61,1.59,XY25,NTT,FMCG
81,VBL,1.13,-16.03,61.57,35.67,163294.0,-50625.0,265217.0,671.64,-25.86,33.0,X-LC,5.52,13.0,-0.31,1.98,1.13,X40N,ATH,FMCG

In [11]:
# bottom 5 today
df_tmp = df_portfolio_features.sort_values(by = 'Today P/L%', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
55,RAJESHEXPO,-3.14,-78.68,369.37,0.07,108022.0,-107932.0,29245.0,518.00,971.97,22.0,L-SC,22.52,268.0,-1.00,0.22,1.07,OX40N,NTT,JEWELLERY
82,VOLTAS,-3.08,9.90,32.12,45.20,67683.0,18978.0,210720.0,1856.00,25.75,41.0,X-MC,8.80,79.0,0.28,1.57,17.37,XY25,NTT,AC
83,WHIRLPOOL,-2.58,-32.79,170.67,81.92,131682.0,-37642.0,77156.0,2270.00,-60.62,39.0,M-SC,25.51,210.0,-0.29,0.58,8.38,XR,NTT,DURABLES
33,HAVELLS,-2.51,-15.49,56.28,32.08,156008.0,-50791.0,277200.0,2062.85,-20.52,39.0,X-MC,6.07,63.0,-0.33,2.07,3.62,X40,ATH,ELECTRICAL
31,HAPPSTMNDS,-2.26,-50.09,270.36,84.85,172944.0,-64197.0,63968.0,1480.71,-40.67,57.0,H-SC,28.03,152.0,-0.37,0.48,18.46,AR,ATH,IT

In [12]:
# top 5 to exit based on CumlRnk
df_tmp = df_portfolio_features[~df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])]
df_tmp = df_tmp[(df_tmp['Current P/L%'] > -1) & (df_tmp['Current P/L%'] < 1)].sort_values(by = 'CumlRnk', ascending=False)
df_tmp[cols].head()

Empty DataFrame
Columns: [Symbol, Today P/L%, Current P/L%, FTT%, OTT%, FTT Amt, Current P/L, Current, FTT, Dev%_PE, RSI_14, Conviction, Spread%, CumlRnk, RRR Ind, CurrAlloc%, Gained%, Criteria, Strategy, Category]
Index: []

In [13]:
# OX40N stocks to exit
df_tmp = df_portfolio_features[(df_portfolio_features['Symbol'].isin(list_ox40n))].sort_values(by = 'Current P/L%', ascending=False)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
27,FINCABLES,-1.86,11.18,87.01,107.91,142826.0,16505.0,164149.0,1641.55,-0.05,53.0,M-SC,7.79,220.0,0.12,1.22,23.49,OX40N,ATH,CABLES
77,TTKPRESTIG,1.44,-23.74,31.25,0.09,24016.0,-23926.0,76851.0,770.00,78.44,62.0,M-SC,15.17,250.0,-1.00,0.57,29.85,OX40N,NTT,DURABLES
66,SIS,-2.03,-35.20,87.13,21.26,62688.0,-39084.0,71948.0,528.00,1682.90,32.0,H-SC,11.47,168.0,-0.62,0.54,0.00,OX40N,NTT,MISC
48,KANSAINER,0.35,-37.02,80.17,13.47,136160.0,-99828.0,169839.0,340.00,-45.81,31.0,H-SC,17.02,162.0,-0.73,1.27,1.82,XY24,NTT,PAINTS
70,SYMPHONY,-0.78,-38.07,61.41,-0.03,65090.0,-65149.0,105992.0,1306.00,-50.26,44.0,M-SC,14.20,205.0,-1.00,0.79,7.19,OX40N,NTT,DURABLES

In [14]:
# top 5 to book for rotation
df_tmp = df_portfolio_features[(df_portfolio_features['Current P/L%'] > 20) ].sort_values(by = 'CumlRnk', ascending=False)
df_tmp[cols].head()

Empty DataFrame
Columns: [Symbol, Today P/L%, Current P/L%, FTT%, OTT%, FTT Amt, Current P/L, Current, FTT, Dev%_PE, RSI_14, Conviction, Spread%, CumlRnk, RRR Ind, CurrAlloc%, Gained%, Criteria, Strategy, Category]
Index: []

In [15]:
# top 5 to monitor for exit
df_tmp = df_portfolio_features[~df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])]
df_tmp = df_tmp[(df_tmp['Current P/L%'] > 0) ].sort_values(by = 'Dev%_PE', ascending=False)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
19,COALINDIA,0.10,15.71,1.69,17.67,2942.0,23644.0,174104.0,478.51,39.17,70.0,L-LC,12.65,185.0,8.04,1.30,35.20,XY25,ATH,MINING
27,FINCABLES,-1.86,11.18,87.01,107.91,142826.0,16505.0,164149.0,1641.55,-0.05,53.0,M-SC,7.79,220.0,0.12,1.22,23.49,OX40N,ATH,CABLES
1,ABB,1.38,19.21,22.11,45.57,68957.0,50261.0,311880.0,7934.00,-23.35,71.0,H-MC,11.17,125.0,0.73,2.32,38.50,AR,NTT,ELECTRICAL

In [16]:
# top 5 to book for rotation from weak conviction
df_tmp = df_portfolio_features[~df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])]
df_tmp = df_tmp[~df_tmp['Criteria'].isin(['XY25','XY24','X40', 'X40N'])].sort_values(by = 'RRR Ind', ascending=False)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
1,ABB,1.38,19.21,22.11,45.57,68957.0,50261.0,311880.0,7934.00,-23.35,71.0,H-MC,11.17,125.0,0.73,2.32,38.50,AR,NTT,ELECTRICAL
27,FINCABLES,-1.86,11.18,87.01,107.91,142826.0,16505.0,164149.0,1641.55,-0.05,53.0,M-SC,7.79,220.0,0.12,1.22,23.49,OX40N,ATH,CABLES
40,INDIAMART,1.08,-8.77,126.60,106.72,142449.0,-10817.0,112519.0,4810.62,-58.79,44.0,H-SC,9.58,140.0,-0.08,0.84,12.56,AR,ATH,MISC
85,ZYDUSLIFE,-0.43,-3.72,40.87,35.63,82465.0,-7801.0,201773.0,1286.17,-16.22,51.0,H-MC,5.02,120.0,-0.09,1.50,12.33,AR,ATH,PHARMA
84,WIPRO,-0.37,-17.24,108.16,72.27,151673.0,-29218.0,140230.0,420.00,-25.49,34.0,M-LC,15.05,98.0,-0.19,1.05,3.26,XR,NTT,IT

In [17]:
# top 5 to accumulate based on lowest RSI_14
df_tmp = df_portfolio_features[df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])].sort_values(by = 'RSI_14', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
58,RELAXO,-0.97,-61.19,292.39,52.31,164744.0,-88816.0,56344.0,1176.00,-58.67,18.0,X-SC,20.15,92.0,-0.54,0.42,0.0,X40N,NTT,FOOTWEAR
3,ACC,-1.30,-36.68,176.08,74.81,298942.0,-98352.0,169776.0,3906.00,-55.22,19.0,X-SC,13.43,85.0,-0.33,1.27,0.0,XY24,BTT,CEMENT
12,BATAINDIA,-0.90,-54.36,196.25,35.20,115242.0,-69948.0,58722.0,2096.00,-23.03,20.0,X-SC,26.86,91.0,-0.61,0.44,0.0,X40,NTT,FOOTWEAR
73,TCS,-0.67,-28.78,77.72,26.57,256426.0,-133337.0,329936.0,4311.59,-39.69,20.0,X-LC,14.84,2.0,-0.52,2.46,0.0,X40,ATH,IT
53,PGHH,-2.03,-20.56,66.18,32.01,112252.0,-43904.0,169616.0,17616.87,-46.32,23.0,X-MC,11.87,57.0,-0.39,1.26,0.0,X40,ATH,FMCG

In [18]:
# top 5 to accumulate based on Spread and CumlRnk
df_tmp = df_portfolio_features[df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])]
df_tmp = df_tmp[(df_tmp['CumlRnk'] < 100)].sort_values(by = 'Spread%', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
78,UNITDSPR,-0.19,-0.03,20.80,20.77,48688.0,-69.0,234075.0,1644.00,-11.40,47.0,X-MC,1.28,64.0,-0.00,1.74,6.68,X40N,NTT,BREWERIES
37,ICICIGI,-0.43,-2.15,21.96,19.34,43001.0,-4295.0,195814.0,2252.93,-17.63,40.0,X-MC,1.89,66.0,-0.10,1.46,10.81,X40,ATH,INSURANCE
22,DABUR,-0.16,-10.34,60.27,43.70,134053.0,-25647.0,222421.0,735.00,-18.54,30.0,X-MC,1.95,70.0,-0.19,1.66,3.16,XY24,BTT,FMCG
75,TMPV,-2.05,-27.64,88.74,36.58,228505.0,-98342.0,257499.0,600.00,-84.72,30.0,X-LC,2.03,4.0,-0.43,1.92,0.00,XY24,NTT,AUTO
59,RELIANCE,0.17,-10.48,39.97,25.30,71907.0,-21060.0,179903.0,1952.00,-12.73,46.0,X-LC,2.93,21.0,-0.29,1.34,20.11,XY25,BTT,REFINERIES

In [19]:
# top 5 to accumulate based on lowest Gained%
df_tmp = df_portfolio_features[df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])].sort_values(by = 'Gained%', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
3,ACC,-1.30,-36.68,176.08,74.81,298942.0,-98352.0,169776.0,3906.00,-55.22,19.0,X-SC,13.43,85.0,-0.33,1.27,0.0,XY24,BTT,CEMENT
12,BATAINDIA,-0.90,-54.36,196.25,35.20,115242.0,-69948.0,58722.0,2096.00,-23.03,20.0,X-SC,26.86,91.0,-0.61,0.44,0.0,X40,NTT,FOOTWEAR
10,BAJAJHLDNG,-0.38,-12.80,48.19,29.22,79891.0,-24341.0,165784.0,14451.52,-19.11,24.0,X-LC,12.71,28.0,-0.30,1.24,0.0,X40,ATH,FINANCE
13,BERGEPAINT,-1.56,-23.32,63.42,25.32,125348.0,-60101.0,197648.0,680.00,-27.54,23.0,X-MC,15.93,68.0,-0.48,1.47,0.0,XY24,NTT,PAINTS
52,PAGEIND,-1.15,-20.44,68.56,34.11,146400.0,-54844.0,213535.0,51418.64,-42.97,31.0,X-MC,20.46,55.0,-0.37,1.59,0.0,X40,ATH,APPARELS

In [20]:
# top 5 to accumulate based on lowest CurrAlloc%
df_tmp = df_portfolio_features[df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])].sort_values(by = 'CurrAlloc%', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
58,RELAXO,-0.97,-61.19,292.39,52.31,164744.0,-88816.0,56344.0,1176.00,-58.67,18.0,X-SC,20.15,92.0,-0.54,0.42,0.00,X40N,NTT,FOOTWEAR
12,BATAINDIA,-0.90,-54.36,196.25,35.20,115242.0,-69948.0,58722.0,2096.00,-23.03,20.0,X-SC,26.86,91.0,-0.61,0.44,0.00,X40,NTT,FOOTWEAR
54,QUESS,-0.91,-22.69,124.93,73.90,103146.0,-24230.0,82563.0,424.00,-58.68,39.0,X-SC,18.39,80.0,-0.23,0.62,1.85,XY24,NTT,MISC
36,HONAUT,-0.80,-21.35,92.38,51.31,140117.0,-41163.0,151675.0,58357.33,-34.59,40.0,X-SC,13.92,90.0,-0.29,1.13,2.14,X40N,ATH,ELECTRICAL
2,ABBOTINDIA,-0.51,-10.93,32.56,18.07,51868.0,-19555.0,159300.0,35195.00,-24.24,44.0,X-MC,11.08,58.0,-0.38,1.19,0.99,X40,ATH,PHARMA

In [21]:
# top 5 to accumulate based on CumlRnk
df_tmp = df_portfolio_features.sort_values(by = 'CumlRnk', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
45,ITC,0.21,-19.73,48.32,19.06,131941.0,-67110.0,273056.0,452.00,-55.92,35.0,X-LC,17.22,1.0,-0.51,2.04,0.21,X40,NTT,FMCG
73,TCS,-0.67,-28.78,77.72,26.57,256426.0,-133337.0,329936.0,4311.59,-39.69,20.0,X-LC,14.84,2.0,-0.52,2.46,0.00,X40,ATH,IT
43,INFY,-1.00,-14.69,57.37,34.24,153126.0,-45978.0,266910.0,1972.00,-32.87,24.0,X-LC,13.13,3.0,-0.30,1.99,0.00,X40,NTT,IT
75,TMPV,-2.05,-27.64,88.74,36.58,228505.0,-98342.0,257499.0,600.00,-84.72,30.0,X-LC,2.03,4.0,-0.43,1.92,0.00,XY24,NTT,AUTO
34,HCLTECH,-0.97,-12.72,41.88,23.83,88429.0,-30775.0,211149.0,1908.19,-8.19,28.0,X-LC,9.89,8.0,-0.35,1.57,1.30,X40,ATH,IT

In [22]:
# top 5 for average up
df_tmp = df_portfolio_features[(df_portfolio_features['Dev%_200'] > 5)].sort_values(by = 'CurrAlloc%', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
67,SONACOMS,-1.05,-12.65,59.23,39.09,52339.0,-12793.0,88366.0,804.02,-30.73,45.0,M-MC,9.55,193.0,-0.24,0.66,25.01,AR,ATH,AUTO
27,FINCABLES,-1.86,11.18,87.01,107.91,142826.0,16505.0,164149.0,1641.55,-0.05,53.0,M-SC,7.79,220.0,0.12,1.22,23.49,OX40N,ATH,CABLES
19,COALINDIA,0.10,15.71,1.69,17.67,2942.0,23644.0,174104.0,478.51,39.17,70.0,L-LC,12.65,185.0,8.04,1.30,35.20,XY25,ATH,MINING
11,BANDHANBNK,-0.52,-14.82,125.89,92.42,298721.0,-41272.0,237287.0,400.00,103.30,55.0,H-SC,9.72,174.0,-0.14,1.77,30.72,XY24,NTT,BANKS
1,ABB,1.38,19.21,22.11,45.57,68957.0,50261.0,311880.0,7934.00,-23.35,71.0,H-MC,11.17,125.0,0.73,2.32,38.50,AR,NTT,ELECTRICAL

In [23]:
# top 5 RSP
df_tmp = df_portfolio_features.sort_values(by = 'RSP', ascending=False)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
19,COALINDIA,0.10,15.71,1.69,17.67,2942.0,23644.0,174104.0,478.51,39.17,70.0,L-LC,12.65,185.0,8.04,1.30,35.20,XY25,ATH,MINING
1,ABB,1.38,19.21,22.11,45.57,68957.0,50261.0,311880.0,7934.00,-23.35,71.0,H-MC,11.17,125.0,0.73,2.32,38.50,AR,NTT,ELECTRICAL
26,EASEMYTRIP,-0.55,-60.26,266.67,45.70,187357.0,-106557.0,70258.0,26.40,-27.06,41.0,M-SC,18.23,204.0,-0.57,0.52,15.76,XY24,NTT,TRAVEL
27,FINCABLES,-1.86,11.18,87.01,107.91,142826.0,16505.0,164149.0,1641.55,-0.05,53.0,M-SC,7.79,220.0,0.12,1.22,23.49,OX40N,ATH,CABLES
31,HAPPSTMNDS,-2.26,-50.09,270.36,84.85,172944.0,-64197.0,63968.0,1480.71,-40.67,57.0,H-SC,28.03,152.0,-0.37,0.48,18.46,AR,ATH,IT

In [24]:
# Top N allocation
df_tmp = df_portfolio_features.sort_values(by = 'CurrAlloc%', ascending=False)
top_n_values = [10, 25, 50]

sum_df = pd.DataFrame({
    'Top_N': top_n_values,
    'Sum_Alloc%': [df_tmp['CurrAlloc%'].head(n).sum() for n in top_n_values]
})

sum_df

   Top_N  Sum_Alloc%
0     10       20.39
1     25       45.21
2     50       77.82

In [25]:
# market-cap-wise allocation
df_tmp = df_portfolio_features[cols]
df_tmp.groupby(df_tmp['Conviction'].str[-2:])['CurrAlloc%'].sum().sort_values(ascending=False)

Conviction
SC    44.66
MC    30.40
LC    24.98
Name: CurrAlloc%, dtype: float64

In [26]:
# criteria-wise allocation
df_portfolio_features.groupby('Criteria')['CurrAlloc%'].sum().sort_values(ascending=False)

Criteria
XY24     27.27
X40      23.66
X40N     15.13
AR        9.33
XY25      8.69
XR        8.24
OX40N     6.96
SR        0.76
Name: CurrAlloc%, dtype: float64

In [27]:
# conviction-wise allocation
df_portfolio_features.groupby('Conviction')['CurrAlloc%'].sum().sort_values(ascending=False)

Conviction
X-MC    22.88
H-SC    21.72
X-LC    21.39
X-SC    12.06
M-SC    10.29
H-MC     5.11
M-MC     2.06
L-LC     1.30
H-LC     1.24
M-LC     1.05
L-SC     0.59
L-MC     0.35
Name: CurrAlloc%, dtype: float64

In [28]:
# sector-wise stats
df_tmp = df_portfolio_features.groupby('Category')[['CurrAlloc%', 'Current', 'Current P/L', 'FTT Amt']].sum().sort_values(by=['Current', 'Current P/L'], ascending=False)
df_tmp['Current P/L%'] = round(df_tmp['Current P/L'] * 100 / df_tmp['Current'], 2)
df_tmp['FTT%'] = round(df_tmp['FTT Amt'] * 100 / df_tmp['Current'], 2)
cols = ['CurrAlloc%', 'Current P/L%', 'FTT%']
df_tmp[cols].sort_values(by=['CurrAlloc%'], ascending=False)

               CurrAlloc%  Current P/L%    FTT%
Category
FMCG                15.22        -22.32   65.75
FINANCE             12.81        -24.99   75.92
IT                  11.69        -43.71  116.84
MISC                 7.05        -41.88  103.52
ELECTRICAL           6.76         -6.79   47.67
PAINTS               5.16        -42.33   67.05
INSURANCE            4.75         -6.50   42.94
PHARMA               4.16         -5.26   38.39
AUTO                 3.64        -34.19   87.43
BANKS                3.09        -29.36  107.75
AC                   2.12        -12.49   43.00
HEALTHCARE           1.98        -34.98   70.21
DURABLES             1.94        -48.74   84.92
FOOTWEAR             1.86        -76.84  147.75
TRAVEL               1.81        -83.76  175.77
BREWERIES            1.74         -0.03   20.80
APPARELS             1.59        -25.68   68.56
REALTY               1.47        -12.57   31.06
CERAMICS             1.35        -69.61  121.13
REFINERIES           1.34        -11.71   39.97
MINING               1.30         13.58    1.69
CEMENT               1.27        -57.93  176.08
CABLES               1.22         10.05   87.01
JEWELLERY            1.11       -115.46  190.32
ENGINEERING          1.10        -63.58  138.39
CHEMICALS            0.94       -109.57  280.54
ENTERTAINMENT        0.77        -87.46  199.27
TEXTILES             0.43        -61.48  107.52
HOTELS               0.37       -130.39  211.65

In [29]:
# money to be made criteria-wise
df_portfolio_features.groupby('Criteria')['FTT Amt'].agg(['sum', 'count']).sort_values(by='sum', ascending=False)

                sum  count
Criteria
XY24      3940610.0     21
X40       1699882.0     15
XR        1388789.0     12
AR        1319653.0     10
X40N      1269656.0     10
OX40N      858058.0     10
XY25       451108.0      6
SR         316845.0      2

In [30]:
# money to be made conviction-wise
df_portfolio_features.groupby('Conviction')['FTT Amt'].agg(['sum', 'count']).sort_values(by='sum', ascending=False)

                  sum  count
Conviction
H-SC        3880854.0     24
X-MC        1663162.0     15
X-LC        1605575.0     12
X-SC        1564973.0     10
M-SC        1537498.0     14
H-MC         391939.0      3
L-SC         212336.0      2
M-LC         151673.0      1
M-MC         110231.0      2
H-LC          67329.0      1
L-MC          56089.0      1
L-LC           2942.0      1

In [31]:
# money to be made criteria and conviction-wise
df_portfolio_features.groupby(['Conviction', 'Criteria'])['FTT Amt'].agg(['sum', 'count']).sort_values(by='sum', ascending=False)

                           sum  count
Conviction Criteria
H-SC       XY24      1320189.0      6
           AR         971556.0      5
M-SC       XY24       906006.0      6
H-SC       XR         883604.0      7
X-SC       XY24       839628.0      4
X-LC       X40        837506.0      6
X-MC       X40        655679.0      7
X-SC       X40N       518648.0      4
X-MC       X40N       505327.0      4
H-SC       OX40N      388660.0      4
X-LC       XY24       374869.0      2
M-SC       OX40N      361376.0      5
H-SC       SR         316845.0      2
X-MC       XY24       259401.0      2
X-LC       X40N       245681.0      2
X-MC       XY25       242755.0      2
H-MC       XY24       240517.0      1
X-SC       X40        206697.0      2
M-SC       XR         193109.0      2
M-LC       XR         151673.0      1
H-MC       AR         151422.0      2
X-LC       XY25       147519.0      2
L-SC       OX40N      108022.0      1
           XR         104314.0      1
M-SC       AR          77007.0      1
H-LC       AR          67329.0      1
M-MC       XY25        57892.0      1
L-MC       XR          56089.0      1
M-MC       AR          52339.0      1
L-LC       XY25         2942.0      1

In [32]:
# notebook execution time

end_time = time.time()
execution_time = round(end_time - start_time, 0)
print(f"Notebook execution time: {execution_time} seconds")

Notebook execution time: 37.0 seconds