<a href="https://colab.research.google.com/github/ankit-rathi/Quantvesting_v2/blob/main/myStocks_Portfolio_Analysis.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
'''
!pip install pandas==2.2.2 -qq
!pip install pyxirr -qq
!pip install ta -qq
!pip install yfinance==0.2.59 -qq
'''

'\n!pip install pandas==2.2.2 -qq\n!pip install pyxirr -qq\n!pip install ta -qq\n!pip install yfinance==0.2.59 -qq\n'

In [2]:
# import libraries

import numpy as np
import pandas as pd
import datetime
import warnings
warnings.filterwarnings('ignore')
import yfinance as yfin
import ta
import matplotlib.pyplot as plt
import requests

In [3]:
# notebook start time
import time
import datetime
import pytz

start_time = time.time()

# function to print date timestamp
def print_date_time():
  tz_NY = pytz.timezone('Asia/Kolkata')
  datetime_NY = datetime.datetime.now(tz_NY)
  print("Run date time (IST):", datetime_NY.strftime("%Y-%m-%d %H:%M:%S"))

In [4]:
# function to get booked and reserved amount
def get_amt():
  # fetch the JSON data from the URL
  url = "https://raw.githubusercontent.com/ankit-rathi/Tradevesting_v1/main/data/myPortfolioAmts.json"
  response = requests.get(url)
  pf_amts = response.json()  # parse the JSON data

  # extract values from the JSON
  py_booked_amt_dm = pf_amts["py_booked_amt_dm"]
  py_booked_amt_sv = pf_amts["py_booked_amt_sv"]
  cy_booked_amt_dm = pf_amts["cy_booked_amt_dm"]
  cy_booked_amt_sv = pf_amts["cy_booked_amt_sv"]
  reserve_amt_dm = pf_amts["reserve_amt_dm"]
  reserve_amt_sv = pf_amts["reserve_amt_sv"]

  # perform calculations
  py_booked_amt = py_booked_amt_dm + py_booked_amt_sv
  cy_booked_amt = cy_booked_amt_dm + cy_booked_amt_sv
  reserve_amt = reserve_amt_dm + reserve_amt_sv
  total_booked_amt = py_booked_amt + cy_booked_amt

  return total_booked_amt, reserve_amt, cy_booked_amt, py_booked_amt

gen_output = 0

In [5]:
# function to format the amount
def format_amt(number):
    abs_number = abs(number)

    if abs_number >= 1_00_00_000:  # Crores
        formatted_amt = f"{number / 1_00_00_000:.2f} C"
    elif abs_number >= 1_00_000:  # Lakhs
        formatted_amt = f"{number / 1_00_000:.2f} L"
    elif abs_number >= 1_000:  # Thousands
        formatted_amt = f"{number / 1_000:.2f} K"
    else:
        formatted_amt = f"{number:.2f}"

    return formatted_amt

# function to set start and end date
def get_start_end_date():
  start_date = (datetime.date.today() + datetime.timedelta(days=-365)).strftime('%Y-%m-%d')
  end_date = (datetime.date.today() + datetime.timedelta(days=1)).strftime('%Y-%m-%d')
  return start_date, end_date

# function to fetch my portfolio csv
def get_mypfs_df():
  mypfs_df = pd.read_csv('https://raw.githubusercontent.com/ankit-rathi/Tradevesting_v1/main/data/myPortfolioStocks.csv')
  return mypfs_df

# function to fetch my prospects csv
def get_mypps_df():
  mypps_df = pd.read_csv('https://raw.githubusercontent.com/ankit-rathi/Tradevesting_v1/main/data/myProspectsScrips.csv')
  return mypps_df

# function to fetch screener data
def get_myscreen_df():
  myscreen_df = pd.read_csv('https://raw.githubusercontent.com/ankit-rathi/Tradevesting_v1/main/data/myScreenerDB.csv')
  return myscreen_df

# function to fetch momentum data
def get_myinvmt_df():
  myinvmt_df = pd.read_csv('https://raw.githubusercontent.com/ankit-rathi/Tradevesting_v1/main/data/myInvestments.csv')
  return myinvmt_df

# function to get the stock ids
def get_stock_ids(df_pf):
  stock_n100 = df_pf['Symbol'].unique()

  exclude = ['CADILAHC','MMTC', 'MASFIN']

  stock_ids = df_pf[~df_pf['Symbol'].isin(exclude) ]['Symbol'].unique()

  #mypf = mypf[mypf.Forecast.notnull()]
  #stock_ids = mypf['Symbol'].unique()

  #stock_ids.sort()
  return stock_ids

# get features from screener data
def get_screener_features():
  myscreen_df = get_myscreen_df()
  cols = ['Symbol', 'EPS', 'MedPE', 'ROCE%', 'ROE%', 'CapType']
  return myscreen_df[cols]

# get relative strength
def get_relative_strength(stock_list):

    # Dictionary to store stock tickers and their corresponding percentage price change
    stock_changes = {}

    # Loop through each stock and fetch its price data
    for stock in stock_list:
        try:
            # Download the stock data for the given date range
            stock_data = yfin.Ticker(stock + '.NS').history(period='1mo', interval='1d')[map(str.title, ['open', 'close', 'low', 'high', 'volume'])]

            # Calculate the percentage change for the stock
            if len(stock_data) > 0:
                start_price = stock_data['Close'].iloc[0]
                end_price = stock_data['Close'].iloc[-1]
                percent_change = round(((end_price - start_price) / start_price) * 100, 2)
                stock_changes[stock] = percent_change
            else:
                stock_changes[stock] = np.nan  # If no data is available, set to NaN

        except Exception as e:
            print(f"Error fetching data for {stock}: {e}")
            stock_changes[stock] = np.nan

    # Create a DataFrame with stock tickers and their percentage changes
    df = pd.DataFrame(list(stock_changes.items()), columns=['Symbol', 'Percent_Change'])

    # Drop any stocks with missing data (NaN values)
    df = df.dropna()

    # Calculate the percentile rank based on percentage change
    df['RSP'] = round(df['Percent_Change'].rank(pct=True) * 100, 2)
    cols = ['Symbol', 'RSP']
    df = df[cols]
    # Sort by percentile rank (optional)
    df = df.sort_values(by='RSP', ascending=False).reset_index(drop=True)

    return df

In [6]:
# function to get stock technicals
def stock_prec_dev(stock_symbol):
    #stock_symbol = 'ULTRACEMCO.NS'
    short_window = 20
    mid_window = 50
    long_window = 200
    moving_avg = 'SMA'

    start = datetime.datetime(*map(int, start_date.split('-')))
    end = datetime.datetime(*map(int, end_date.split('-')))

    stock_df = yfin.Ticker(stock_symbol + '.NS').history(period='max', interval='1d')[map(str.title, ['open', 'close', 'low', 'high', 'volume'])]

    stock_df['Max'] = round(max(stock_df['Close']),2)
    stock_df = stock_df[(stock_df.index <= end_date) & (stock_df.index >= start_date)]
    stock_df['200_SMA'] = round(stock_df['Close'].rolling(window = 200, min_periods = 1).mean(),0)
    stock_df['Dev%_200'] = round((stock_df['Close'] - stock_df['200_SMA'])*100/stock_df['200_SMA'],2)
    stock_df.dropna(axis = 0, inplace = True) # remove any null rows

    stock_df['20_SMA'] = stock_df['Close'].rolling(window=20).mean()
    stock_df['50_SMA'] = stock_df['Close'].rolling(window=50).mean()
    stock_df['Symbol'] = stock_symbol

    stock_df['Close'] = round(stock_df['Close'],2)
    stock_df['Min'] = round(min(stock_df['Close']),2)
    stock_df['RSI_14'] = ta.momentum.RSIIndicator(close=stock_df['Close'], window=14).rsi()
    stock_df['RSI_14'] = round(stock_df['RSI_14'],0)
    stock_df['Prev_Close'] = stock_df['Close'].shift(1)
    stock_df.drop(['Open', 'Low', 'High', 'Volume'], axis=1, inplace=True)
    stock_df = stock_df.tail(1)

    max_SMA = max(stock_df['20_SMA'].item(), stock_df['50_SMA'].item(), stock_df['200_SMA'].item())
    min_SMA = min(stock_df['20_SMA'].item(), stock_df['50_SMA'].item(), stock_df['200_SMA'].item())
    ABS_Spread = max_SMA - min_SMA
    stock_df['Spread%'] = round((ABS_Spread / stock_df['200_SMA'].item()) * 100,2)

    return stock_df

# function to compute stock attributes
def get_common_features(stock_ids, df_mypf):

  df_prec_dev = pd.DataFrame()
  df_tmp = get_screener_features()
  df_rs = get_relative_strength(stock_ids)

  for stock_id in stock_ids:
      tmp = stock_prec_dev(stock_id)
      tmp = tmp.reset_index()
      df_prec_dev = pd.concat([df_prec_dev, tmp], ignore_index = True)
  df_prec_dev = pd.merge(df_prec_dev, df_mypf, on= 'Symbol')
  df_prec_dev = pd.merge(df_prec_dev, df_tmp, on= 'Symbol', how='left')
  df_prec_dev = pd.merge(df_prec_dev, df_rs, on= 'Symbol', how='left')
  #print(df_prec_dev.columns)
  df_prec_dev['Curr_PE'] = round(df_prec_dev['Close']/df_prec_dev['EPS'],1)
  df_prec_dev['Dev%_PE'] = round((df_prec_dev['Curr_PE'] - df_prec_dev['MedPE'])*100/df_prec_dev['MedPE'],2)
  df_prec_dev['Conviction'] = df_prec_dev['Conviction'] + '-' + df_prec_dev['CapType']
  return df_prec_dev

# function to arrange stock features
def arrange_features(df_stocks, common_cols, diff_cols):
  df_stocks_common = df_stocks[common_cols].drop_duplicates()
  df_stocks_diff = df_stocks[diff_cols]
  df_stocks_diff['Investment'] = df_stocks_diff['AvgCost'] * df_stocks_diff['Shares']
  df_stocks_diff = df_stocks_diff.groupby(['Symbol'])[['Shares', 'Investment']].aggregate(['sum']).reset_index()
  df_stocks_diff.columns = ['Symbol', 'Shares', 'Investment']
  df_stocks_diff['AvgCost'] = round(df_stocks_diff['Investment']/df_stocks_diff['Shares'],2)
  df_stocks = pd.merge(df_stocks_diff, df_stocks_common, on='Symbol')
  return df_stocks

# plot fact distribution across dimension
def plot_pie_chart(df, dimension, fact):
  # grouping the data by category and calculating the sum of fact for each type
  grouped_data = df.groupby(dimension)[fact].sum()

  # sorting the grouped data in descending order
  grouped_data = grouped_data.sort_values(ascending=False)

  # creating a pie chart
  grouped_data.plot.pie(autopct='%1.1f%%', startangle=90, figsize=(6, 6))

  # adding a title and displaying the plot
  plt.title(f'{dimension} {fact} Distribution')
  plt.ylabel('')  # To hide the y-label
  plt.show()

In [7]:
# function to get portfolio features

def get_portfolio_features(df_common_features):

  print_date_time()
  print('-------------------')

  #df_common_features["Target"] = df_common_features["Target"].fillna(df_common_features["Max"])
  df_common_features['NTT'] = np.where(df_common_features['Strategy']== 'NTT', df_common_features["Target"], df_common_features['Max'])
  df_common_features['LTT'] = np.where(df_common_features['Strategy']== 'BTT', df_common_features["Target"], df_common_features['Max'])
  df_common_features['BOL'] = df_common_features['Min']

  tmp_df = df_common_features[df_common_features['Symbol'].isin(mypf_df[mypf_df['InPortfolio'] != 'NA'].Symbol.values)]
  print('qualified stocks: '+str(len(tmp_df['Symbol'].unique())))
  tmp_df1 = tmp_df[tmp_df['LatestQtr'] == 1]
  print('with latest results: '+str(len(tmp_df1['Symbol'].unique())))
  tmp_df1 = tmp_df1[tmp_df1['StarStock'] == 1]
  print('still star stocks: '+str(len(tmp_df1['Symbol'].unique())))
  tmp_df['Investment'] = tmp_df['AvgCost'] * tmp_df['Shares']
  tmp_df['Current'] = round(tmp_df['Close'] * tmp_df['Shares'],0)
  tmp_df['Previous'] = tmp_df['Prev_Close'] * tmp_df['Shares']
  tmp_df['EstimatedST'] = tmp_df['NTT'] * tmp_df['Shares']
  tmp_df['EstimatedLT'] = tmp_df['LTT'] * tmp_df['Shares']
  tmp_df['Current P/L'] = round((tmp_df['Current'] - tmp_df['Investment']),0)
  tmp_df['Today P/L%'] = round((tmp_df['Current'] - tmp_df['Previous'])*100/tmp_df['Previous'],2)
  tmp_df['Current P/L%'] = round((tmp_df['Current'] - tmp_df['Investment'])*100/tmp_df['Investment'],2)
  tmp_df['EstimatedST P/L%'] = round((tmp_df['EstimatedST'] - tmp_df['Investment'])*100/tmp_df['Investment'],2)
  tmp_df['EstimatedLT P/L%'] = round((tmp_df['EstimatedLT'] - tmp_df['Investment'])*100/tmp_df['Investment'],2)
  tmp_df['NTT%'] = round((tmp_df['NTT'] - tmp_df['Close'])*100/tmp_df['Close'],2)
  tmp_df['LTT%'] = round((tmp_df['LTT'] - tmp_df['Close'])*100/tmp_df['Close'],2)
  tmp_df['Gained%'] = round((tmp_df['Close'] - tmp_df['BOL'])*100/tmp_df['BOL'],2)
  investment = round(sum(tmp_df['AvgCost']*tmp_df['Shares']),0)
  current = round(sum(tmp_df['Close']*tmp_df['Shares']),0)
  tmp_df['InitAlloc%'] = round(tmp_df['Investment']*100/investment,2)
  tmp_df['CurrAlloc%'] = round(tmp_df['Current']*100/current,2)
  tmp_df['FTT'] = tmp_df['LTT']
  tmp_df.loc[tmp_df['Strategy'] == 'NTT', 'FTT'] = tmp_df['NTT']
  tmp_df['FTT%'] = tmp_df['LTT%']
  tmp_df.loc[tmp_df['Strategy'] == 'NTT', 'FTT%'] = tmp_df['NTT%']
  tmp_df['FTT Amt'] = round(tmp_df['FTT%'] * tmp_df['Current']/100,0)
  tmp_df['OTT%'] = round((tmp_df['FTT'] - tmp_df['AvgCost'])*100/tmp_df['AvgCost'],2)
  tmp_df['RRR Ind'] = round(tmp_df['Current P/L']/tmp_df['FTT Amt'],2)
  tmp_df['Risk Ind'] = round(tmp_df['Current P/L%']*tmp_df['CurrAlloc%'],0)

  return tmp_df

# function to print portfolio features
def print_portfolio_stats(df_portfolio_features, myinvmt_df):
  from pyxirr import xirr

  total_booked_amt, reserve_amt, cy_booked_amt, py_booked_amt = get_amt()

  dates = myinvmt_df['Date'].values
  dates = np.append(dates, datetime.date.today().strftime('%d-%b-%y'))
  investment = myinvmt_df['Investment'].values
  dates= pd.to_datetime(dates)

  current = round(sum(df_portfolio_features['Close']*df_portfolio_features['Shares']),0) + reserve_amt
  investment_xirr = np.append(investment, current)
  cagr = round(xirr(pd.DataFrame({"dates": dates, "amounts": investment_xirr}))*100,2)

  investment = -sum(investment)
  invested = round(sum(df_portfolio_features['AvgCost']*df_portfolio_features['Shares']),0) + reserve_amt
  previous = round(sum(df_portfolio_features['Prev_Close']*df_portfolio_features['Shares']),0) + reserve_amt
  cy_invested = investment + py_booked_amt

  today_pnl_amount = current-previous
  today_pnl_percentage = round((current-previous)*100/previous,2)

  curr_pnl_amount = current-invested
  curr_pnl_percentage = round((curr_pnl_amount)*100/(cy_invested),2)

  cy_pnl_amount = cy_booked_amt + curr_pnl_amount
  cy_pnl_percentage = round((cy_pnl_amount)*100/cy_invested,2)

  overall_pnl_amount = total_booked_amt + curr_pnl_amount
  overall_pnl_percentage = round((overall_pnl_amount)*100/investment,2)

  estimate_st = round(sum(df_portfolio_features['FTT']*df_portfolio_features['Shares']),0)  + reserve_amt
  est_st_pnl_amount = estimate_st-current
  est_st_pnl_percentage = round((est_st_pnl_amount)*100/current,2)

  estimate_lt = round(sum(df_portfolio_features['LTT']*df_portfolio_features['Shares']),0)  + reserve_amt
  est_lt_pnl_amount = estimate_lt-current
  est_lt_pnl_percentage = round((est_lt_pnl_amount)*100/current,2)

  total_profit = round(sum(df_portfolio_features[df_portfolio_features['Current P/L%'] > 0]['Current']) - sum(df_portfolio_features[df_portfolio_features['Current P/L%'] > 0]['Investment']),0)
  total_loss = round(sum(df_portfolio_features[df_portfolio_features['Current P/L%'] < 0]['Current']) - sum(df_portfolio_features[df_portfolio_features['Current P/L%'] < 0]['Investment']),0)

  cy_booked_percentage = round((cy_booked_amt)*100/current,2)
  py_booked_percentage = round((py_booked_amt)*100/investment,2)
  total_booked_percentage = round((total_booked_amt)*100/investment,2)

  print('-------------------')
  print('Initial Investment: ', format_amt(investment))
  print('CY Investment: ', format_amt(cy_invested))
  print('Reserve: ', format_amt(reserve_amt))
  print('Current: ',  format_amt(current))
  print('-------------------')
  print('Today PnL: '+ '{} ({}%)'.format(format_amt(today_pnl_amount), today_pnl_percentage))
  print('Current PnL: '+ '{} ({}%)'.format(format_amt(curr_pnl_amount), curr_pnl_percentage))
  print('CY Booked + Current PnL: '+ '{} ({}%)'.format(format_amt(cy_pnl_amount), cy_pnl_percentage))
  print('-------------------')
  print('Total profit: ', format_amt(total_profit))
  print('Total loss: ', format_amt(total_loss))
  print('-------------------')
  print('Total Booked + Current PnL: '+ '{} ({}%)'.format(format_amt(overall_pnl_amount), overall_pnl_percentage))
  print('Total Booked PnL: '+ '{} ({}%)'.format(format_amt(total_booked_amt), total_booked_percentage))
  print('Curr Year Booked PnL: '+ '{} ({}%)'.format(format_amt(cy_booked_amt), cy_booked_percentage))
  print('Prev Year Booked PnL: '+ '{} ({}%)'.format(format_amt(py_booked_amt), py_booked_percentage))
  print('===================')
  print('Est FTT: ',  format_amt(estimate_st))
  print('Est FTT PnL: '+ '{} ({}%)'.format(format_amt(est_st_pnl_amount), est_st_pnl_percentage))

  print('===================')
  print('Deployed: ', format_amt(investment))

  print('Current: ', format_amt(current))

  print('CAGR/XIRR %: '+'{}%'.format(cagr))

In [8]:
# get start and end date
start_date, end_date = get_start_end_date()

# get portfolio and prospects data
mypfs_df = get_mypfs_df()
mypps_df = get_mypps_df()
myinvmt_df = get_myinvmt_df()

# merge above datasets
mypf_df = pd.merge(mypfs_df, mypps_df, on="Symbol")

# seggregate dm and sv portfolio
dm_pf = mypf_df[mypf_df['InPortfolio'] == 'DM']
sv_pf = mypf_df[mypf_df['InPortfolio'] == 'SV']

# build portfolio stock dataframe
dm_stocks = get_stock_ids(dm_pf)
sv_stocks = get_stock_ids(sv_pf)
df_stocks = pd.concat([dm_pf,sv_pf], ignore_index = True)

# arrange common and diff stock features
common_cols = ['Symbol', 'Target', 'Criteria', 'Strategy', 'CumlRnk', 'LatestQtr', 'StarStock', 'Conviction', 'Category', 'InFolio', 'XIRR', 'MBQ']
diff_cols = ['Symbol', 'AvgCost', 'Shares']
df_stocks = arrange_features(df_stocks, common_cols, diff_cols)

# get common features
stock_ids = df_stocks['Symbol'].values
df_common_features = get_common_features(stock_ids, df_stocks)

df_common_features.reset_index(drop=True, inplace=True)
df_common_features.drop(['Date'], axis=1, inplace=True)
# get and print portfolio features
df_portfolio_features = get_portfolio_features(df_common_features)

print_portfolio_stats(df_portfolio_features, myinvmt_df)

df = df_portfolio_features
#plot_pie_chart(df, 'CapType', 'Current')
list_ox40n = list(df[df['MBQ'].str.contains('OX40N', na=False)]['Symbol'].values)

Run date time (IST): 2026-03-19 13:07:30
-------------------
qualified stocks: 86
with latest results: 26
still star stocks: 16
-------------------
Initial Investment:  1.36 C
CY Investment:  1.62 C
Reserve:  1.61 K
Current:  1.32 C
-------------------
Today PnL: -2.56 L (-1.9%)
Current PnL: -45.17 L (-27.8%)
CY Booked + Current PnL: -29.28 L (-18.02%)
-------------------
Total profit:  62.39 K
Total loss:  -45.79 L
-------------------
Total Booked + Current PnL: -2.30 L (-1.7%)
Total Booked PnL: 42.87 L (31.64%)
Curr Year Booked PnL: 15.89 L (12.04%)
Prev Year Booked PnL: 26.98 L (19.91%)
===================
Est FTT:  2.48 C
Est FTT PnL: 1.16 C (87.85%)
===================
Deployed:  1.36 C
Current:  1.32 C
CAGR/XIRR %: -1.31%

In [9]:
# top 5 near their targets
cols = ['Symbol', 'Today P/L%', 'Current P/L%', 'FTT%', 'OTT%', 'FTT Amt', 'Current P/L', 'Current', 'FTT', 'Dev%_PE', 'RSI_14','Conviction', 'Spread%',  'CumlRnk', 'RRR Ind', 'CurrAlloc%', 'Gained%', 'Criteria', 'Strategy', 'Category']
df_tmp = df_portfolio_features[~df_portfolio_features['Symbol'].isin(['ENRIN','BLUSPRING','DIGITIDE'])]
df_tmp = df_tmp.sort_values(by = 'FTT Amt', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
50,MASFIN,-2.41,-10.29,35.51,21.57,31213.0,-10080.0,87900.0,397.04,-22.76,36.0,H-SC,1.87,167.0,-0.32,0.67,20.53,XR,ATH,FINANCE
77,TTKPRESTIG,2.22,-36.53,57.69,0.09,36903.0,-36810.0,63967.0,770.00,48.56,43.0,M-SC,17.49,250.0,-1.00,0.48,8.08,OX40N,NTT,DURABLES
37,ICICIGI,-1.42,-4.38,24.80,19.34,47455.0,-8758.0,191351.0,2252.93,-19.59,34.0,X-MC,2.52,66.0,-0.18,1.45,5.78,X40,ATH,INSURANCE
67,SONACOMS,-1.64,-12.91,59.72,39.09,52610.0,-13064.0,88095.0,804.02,-31.00,47.0,M-MC,8.44,193.0,-0.25,0.67,24.63,AR,ATH,AUTO
2,ABBOTINDIA,-0.80,-12.22,34.51,18.07,54177.0,-21865.0,156990.0,35195.00,-25.27,40.0,X-MC,10.83,58.0,-0.40,1.19,0.00,X40,ATH,PHARMA

In [10]:
# top 5 today
df_tmp = df_portfolio_features.sort_values(by = 'Today P/L%', ascending=False)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
80,VALIANTORG,12.89,-44.36,213.00,74.15,193890.0,-72577.0,91028.0,838.0,-263.44,66.0,H-SC,29.06,145.0,-0.37,0.69,35.46,XR,NTT,CHEMICALS
77,TTKPRESTIG,2.22,-36.53,57.69,0.09,36903.0,-36810.0,63967.0,770.0,48.56,43.0,M-SC,17.49,250.0,-1.00,0.48,8.08,OX40N,NTT,DURABLES
69,SURYODAY,1.59,-26.44,67.26,23.03,88597.0,-47348.0,131723.0,216.0,42.54,50.0,H-SC,6.62,166.0,-0.53,1.00,28.74,XR,NTT,BANKS
15,BSOFT,0.99,-33.28,126.01,50.79,118248.0,-46813.0,93840.0,831.7,-14.57,43.0,H-SC,7.26,172.0,-0.40,0.71,9.26,XR,ATH,IT
14,BOSCH-HCIL,0.77,-43.30,76.35,-0.01,55326.0,-55341.0,72464.0,2282.0,14726.09,42.0,M-SC,3.60,231.0,-1.00,0.55,2.93,OX40N,BTT,AC

In [11]:
# bottom 5 today
df_tmp = df_portfolio_features.sort_values(by = 'Today P/L%', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
19,COFFEEDAY,-4.60,-58.94,229.49,35.27,106984.0,-66931.0,46618.0,80.0,-67.81,26.0,L-SC,24.61,266.0,-0.63,0.35,0.00,XR,NTT,HOTELS
82,VOLTAS,-4.22,6.59,36.22,45.20,74025.0,12633.0,204375.0,1856.0,22.09,36.0,X-MC,6.72,79.0,0.17,1.55,13.83,XY25,NTT,AC
76,TRIDENT,-4.05,-37.21,104.69,28.51,60639.0,-34332.0,57922.0,48.0,-19.26,43.0,M-SC,13.44,223.0,-0.57,0.44,6.30,XR,NTT,TEXTILES
75,TMPV,-4.02,-29.05,92.49,36.58,233516.0,-103364.0,252477.0,600.0,-85.81,32.0,X-LC,4.41,4.0,-0.44,1.91,0.00,XY24,NTT,AUTO
79,VAIBHAVGBL,-3.92,-36.53,153.28,60.77,177828.0,-66760.0,116015.0,521.0,33.88,39.0,H-SC,5.19,160.0,-0.38,0.88,5.18,XR,NTT,JEWELLERY

In [12]:
# top 5 to exit based on CumlRnk
df_tmp = df_portfolio_features[~df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])]
df_tmp = df_tmp[(df_tmp['Current P/L%'] > -1) & (df_tmp['Current P/L%'] < 1)].sort_values(by = 'CumlRnk', ascending=False)
df_tmp[cols].head()

Empty DataFrame
Columns: [Symbol, Today P/L%, Current P/L%, FTT%, OTT%, FTT Amt, Current P/L, Current, FTT, Dev%_PE, RSI_14, Conviction, Spread%, CumlRnk, RRR Ind, CurrAlloc%, Gained%, Criteria, Strategy, Category]
Index: []

In [13]:
# OX40N stocks to exit
df_tmp = df_portfolio_features[(df_portfolio_features['Symbol'].isin(list_ox40n))].sort_values(by = 'Current P/L%', ascending=False)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
26,FINCABLES,-2.75,8.01,92.49,107.91,147498.0,11830.0,159474.0,1641.55,-2.59,49.0,M-SC,8.08,220.0,0.08,1.21,19.98,OX40N,ATH,CABLES
77,TTKPRESTIG,2.22,-36.53,57.69,0.09,36903.0,-36810.0,63967.0,770.00,48.56,43.0,M-SC,17.49,250.0,-1.00,0.48,8.08,OX40N,NTT,DURABLES
66,SIS,-1.25,-36.60,91.27,21.26,64248.0,-40639.0,70393.0,528.00,1644.04,33.0,H-SC,13.56,168.0,-0.63,0.53,1.45,OX40N,NTT,MISC
18,CERA,-2.85,-36.71,95.76,23.89,106605.0,-64578.0,111325.0,9475.00,-38.90,50.0,H-SC,18.18,153.0,-0.61,0.84,6.98,OX40N,NTT,CERAMICS
70,SYMPHONY,-3.13,-39.48,65.17,-0.03,67504.0,-67559.0,103582.0,1306.00,-51.40,43.0,M-SC,14.89,205.0,-1.00,0.79,4.75,OX40N,NTT,DURABLES

In [14]:
# top 5 to book for rotation
df_tmp = df_portfolio_features[(df_portfolio_features['Current P/L%'] > 20) ].sort_values(by = 'CumlRnk', ascending=False)
df_tmp[cols].head()

Empty DataFrame
Columns: [Symbol, Today P/L%, Current P/L%, FTT%, OTT%, FTT Amt, Current P/L, Current, FTT, Dev%_PE, RSI_14, Conviction, Spread%, CumlRnk, RRR Ind, CurrAlloc%, Gained%, Criteria, Strategy, Category]
Index: []

In [15]:
# top 5 to monitor for exit
df_tmp = df_portfolio_features[~df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])]
df_tmp = df_tmp[(df_tmp['Current P/L%'] > 0) ].sort_values(by = 'Dev%_PE', ascending=False)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
26,FINCABLES,-2.75,8.01,92.49,107.91,147498.0,11830.0,159474.0,1641.55,-2.59,49.0,M-SC,8.08,220.0,0.08,1.21,19.98,OX40N,ATH,CABLES
1,ABB,-1.53,14.50,27.14,45.57,81296.0,37925.0,299544.0,7934.00,-26.39,59.0,H-MC,12.55,125.0,0.47,2.27,33.02,AR,NTT,ELECTRICAL

In [16]:
# top 5 to book for rotation from weak conviction
df_tmp = df_portfolio_features[~df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])]
df_tmp = df_tmp[~df_tmp['Criteria'].isin(['XY25','XY24','X40', 'X40N'])].sort_values(by = 'RRR Ind', ascending=False)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
1,ABB,-1.53,14.50,27.14,45.57,81296.0,37925.0,299544.0,7934.00,-26.39,59.0,H-MC,12.55,125.0,0.47,2.27,33.02,AR,NTT,ELECTRICAL
26,FINCABLES,-2.75,8.01,92.49,107.91,147498.0,11830.0,159474.0,1641.55,-2.59,49.0,M-SC,8.08,220.0,0.08,1.21,19.98,OX40N,ATH,CABLES
40,INDIAMART,-3.22,-12.75,136.92,106.72,147348.0,-15720.0,107616.0,4810.62,-60.74,35.0,H-SC,10.54,140.0,-0.11,0.82,7.65,AR,ATH,MISC
85,ZYDUSLIFE,-1.86,-6.90,45.68,35.63,89126.0,-14464.0,195110.0,1286.17,-18.92,42.0,H-MC,5.30,120.0,-0.16,1.48,8.62,AR,ATH,PHARMA
84,WIPRO,-2.70,-22.46,122.16,72.27,160506.0,-38058.0,131390.0,420.00,-30.18,27.0,M-LC,16.57,98.0,-0.24,1.00,0.00,XR,NTT,IT

In [17]:
# top 5 to accumulate based on lowest RSI_14
df_tmp = df_portfolio_features[df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])].sort_values(by = 'RSI_14', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
12,BATAINDIA,-2.27,-57.57,218.64,35.20,119371.0,-74073.0,54597.0,2096.00,-28.38,15.0,X-SC,29.28,91.0,-0.62,0.41,0.00,X40,NTT,FOOTWEAR
53,PGHH,-0.87,-25.58,77.37,32.01,122950.0,-54608.0,158912.0,17616.87,-49.68,16.0,X-MC,13.90,57.0,-0.44,1.20,0.00,X40,ATH,FMCG
58,RELAXO,-3.01,-64.13,324.55,52.31,169013.0,-93084.0,52076.0,1176.00,-61.77,21.0,X-SC,23.57,92.0,-0.55,0.39,0.53,X40N,NTT,FOOTWEAR
3,ACC,-3.23,-39.14,187.25,74.81,305547.0,-104952.0,163176.0,3906.00,-57.01,22.0,X-SC,15.87,85.0,-0.34,1.24,0.00,XY24,BTT,CEMENT
73,TCS,-2.81,-30.36,81.75,26.57,263752.0,-140640.0,322633.0,4311.59,-41.00,23.0,X-LC,16.30,2.0,-0.53,2.45,0.00,X40,ATH,IT

In [18]:
# top 5 to accumulate based on Spread and CumlRnk
df_tmp = df_portfolio_features[df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])]
df_tmp = df_tmp[(df_tmp['CumlRnk'] < 100)].sort_values(by = 'Spread%', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
78,UNITDSPR,-1.81,-4.77,26.81,20.77,59781.0,-11163.0,222981.0,1644.00,-15.56,40.0,X-MC,0.99,64.0,-0.19,1.69,1.62,X40N,NTT,BREWERIES
37,ICICIGI,-1.42,-4.38,24.80,19.34,47455.0,-8758.0,191351.0,2252.93,-19.59,34.0,X-MC,2.52,66.0,-0.18,1.45,5.78,X40,ATH,INSURANCE
38,ICICIPRULI,-3.54,-6.03,39.12,30.73,72419.0,-11886.0,185119.0,790.00,-31.23,25.0,X-MC,3.04,78.0,-0.16,1.40,5.90,X40,ATH,INSURANCE
59,RELIANCE,-0.65,-10.20,39.53,25.30,71340.0,-20492.0,180471.0,1952.00,-12.34,47.0,X-LC,3.32,21.0,-0.29,1.37,20.49,XY25,BTT,REFINERIES
65,SIEMENS,-3.41,-16.41,50.15,25.51,78013.0,-30535.0,155560.0,4671.50,30.65,44.0,H-LC,3.50,51.0,-0.39,1.18,14.56,AR,ATH,ELECTRICAL

In [19]:
# top 5 to accumulate based on lowest Gained%
df_tmp = df_portfolio_features[df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])].sort_values(by = 'Gained%', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
2,ABBOTINDIA,-0.80,-12.22,34.51,18.07,54177.0,-21865.0,156990.0,35195.00,-25.27,40.0,X-MC,10.83,58.0,-0.40,1.19,0.0,X40,ATH,PHARMA
3,ACC,-3.23,-39.14,187.25,74.81,305547.0,-104952.0,163176.0,3906.00,-57.01,22.0,X-SC,15.87,85.0,-0.34,1.24,0.0,XY24,BTT,CEMENT
12,BATAINDIA,-2.27,-57.57,218.64,35.20,119371.0,-74073.0,54597.0,2096.00,-28.38,15.0,X-SC,29.28,91.0,-0.62,0.41,0.0,X40,NTT,FOOTWEAR
21,DABUR,-3.36,-14.63,68.33,43.70,144706.0,-36293.0,211775.0,735.00,-22.61,26.0,X-MC,3.97,70.0,-0.25,1.61,0.0,XY24,BTT,FMCG
20,COLPAL,-1.58,-27.44,95.03,41.51,181593.0,-72275.0,191090.0,3726.84,-12.13,28.0,X-MC,4.34,62.0,-0.40,1.45,0.0,XY25,ATH,FMCG

In [20]:
# top 5 to accumulate based on lowest CurrAlloc%
df_tmp = df_portfolio_features[df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])].sort_values(by = 'CurrAlloc%', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
58,RELAXO,-3.01,-64.13,324.55,52.31,169013.0,-93084.0,52076.0,1176.00,-61.77,21.0,X-SC,23.57,92.0,-0.55,0.39,0.53,X40N,NTT,FOOTWEAR
12,BATAINDIA,-2.27,-57.57,218.64,35.20,119371.0,-74073.0,54597.0,2096.00,-28.38,15.0,X-SC,29.28,91.0,-0.62,0.41,0.00,X40,NTT,FOOTWEAR
54,QUESS,-1.55,-26.25,135.79,73.90,106950.0,-28032.0,78761.0,424.00,-60.33,37.0,X-SC,20.25,80.0,-0.26,0.60,2.64,XY24,NTT,MISC
36,HONAUT,-1.33,-25.18,102.24,51.31,147507.0,-48563.0,144275.0,58357.33,-37.79,29.0,X-SC,14.73,90.0,-0.33,1.09,0.00,X40N,ATH,ELECTRICAL
51,MEDANTA,-1.58,-12.10,44.62,27.12,69229.0,-21365.0,155152.0,1486.00,-14.87,31.0,X-SC,10.50,87.0,-0.31,1.18,0.00,XY24,NTT,HEALTHCARE

In [21]:
# top 5 to accumulate based on CumlRnk
df_tmp = df_portfolio_features.sort_values(by = 'CumlRnk', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
45,ITC,-1.43,-21.06,50.82,19.06,136467.0,-71635.0,268531.0,452.00,-56.73,34.0,X-LC,17.57,1.0,-0.52,2.04,0.00,X40,NTT,FMCG
73,TCS,-2.81,-30.36,81.75,26.57,263752.0,-140640.0,322633.0,4311.59,-41.00,23.0,X-LC,16.30,2.0,-0.53,2.45,0.00,X40,ATH,IT
43,INFY,-2.90,-16.24,60.27,34.24,157953.0,-50813.0,262075.0,1972.00,-33.96,28.0,X-LC,14.52,3.0,-0.32,1.99,0.00,X40,NTT,IT
75,TMPV,-4.02,-29.05,92.49,36.58,233516.0,-103364.0,252477.0,600.00,-85.81,32.0,X-LC,4.41,4.0,-0.44,1.91,0.00,XY24,NTT,AUTO
33,HCLTECH,-2.39,-14.03,44.04,23.83,91601.0,-33930.0,207994.0,1908.19,-9.84,32.0,X-LC,11.23,8.0,-0.37,1.58,0.28,X40,ATH,IT

In [22]:
# top 5 for average up
df_tmp = df_portfolio_features[(df_portfolio_features['Dev%_200'] > 5)].sort_values(by = 'CurrAlloc%', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
67,SONACOMS,-1.64,-12.91,59.72,39.09,52610.0,-13064.0,88095.0,804.02,-31.00,47.0,M-MC,8.44,193.0,-0.25,0.67,24.63,AR,ATH,AUTO
1,ABB,-1.53,14.50,27.14,45.57,81296.0,37925.0,299544.0,7934.00,-26.39,59.0,H-MC,12.55,125.0,0.47,2.27,33.02,AR,NTT,ELECTRICAL

In [23]:
# top 5 RSP
df_tmp = df_portfolio_features.sort_values(by = 'RSP', ascending=False)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
80,VALIANTORG,12.89,-44.36,213.00,74.15,193890.0,-72577.0,91028.0,838.00,-263.44,66.0,H-SC,29.06,145.0,-0.37,0.69,35.46,XR,NTT,CHEMICALS
1,ABB,-1.53,14.50,27.14,45.57,81296.0,37925.0,299544.0,7934.00,-26.39,59.0,H-MC,12.55,125.0,0.47,2.27,33.02,AR,NTT,ELECTRICAL
26,FINCABLES,-2.75,8.01,92.49,107.91,147498.0,11830.0,159474.0,1641.55,-2.59,49.0,M-SC,8.08,220.0,0.08,1.21,19.98,OX40N,ATH,CABLES
69,SURYODAY,1.59,-26.44,67.26,23.03,88597.0,-47348.0,131723.0,216.00,42.54,50.0,H-SC,6.62,166.0,-0.53,1.00,28.74,XR,NTT,BANKS
47,JSWINFRA,-1.85,-13.12,34.01,16.43,65529.0,-29098.0,192676.0,342.00,-25.48,47.0,X-MC,11.48,61.0,-0.44,1.46,3.45,X40N,NTT,REALTY

In [24]:
# Top N allocation
df_tmp = df_portfolio_features.sort_values(by = 'CurrAlloc%', ascending=False)
top_n_values = [10, 25, 50]

sum_df = pd.DataFrame({
    'Top_N': top_n_values,
    'Sum_Alloc%': [df_tmp['CurrAlloc%'].head(n).sum() for n in top_n_values]
})

sum_df

   Top_N  Sum_Alloc%
0     10       20.62
1     25       45.54
2     50       77.92

In [25]:
# market-cap-wise allocation
df_tmp = df_portfolio_features[cols]
df_tmp.groupby(df_tmp['Conviction'].str[-2:])['CurrAlloc%'].sum().sort_values(ascending=False)

Conviction
SC    44.53
MC    30.16
LC    25.33
Name: CurrAlloc%, dtype: float64

In [26]:
# criteria-wise allocation
df_portfolio_features.groupby('Criteria')['CurrAlloc%'].sum().sort_values(ascending=False)

Criteria
XY24     26.95
X40      25.39
X40N     15.18
AR        9.17
XR        8.35
XY25      7.36
OX40N     6.82
SR        0.80
Name: CurrAlloc%, dtype: float64

In [27]:
# conviction-wise allocation
df_portfolio_features.groupby('Conviction')['CurrAlloc%'].sum().sort_values(ascending=False)

Conviction
X-LC    23.15
X-MC    22.67
H-SC    21.70
X-SC    12.19
M-SC    10.09
H-MC     5.06
M-MC     2.07
H-LC     1.18
M-LC     1.00
L-SC     0.55
L-MC     0.36
Name: CurrAlloc%, dtype: float64

In [28]:
# sector-wise stats
df_tmp = df_portfolio_features.groupby('Category')[['CurrAlloc%', 'Current', 'Current P/L', 'FTT Amt']].sum().sort_values(by=['Current', 'Current P/L'], ascending=False)
df_tmp['Current P/L%'] = round(df_tmp['Current P/L'] * 100 / df_tmp['Current'], 2)
df_tmp['FTT%'] = round(df_tmp['FTT Amt'] * 100 / df_tmp['Current'], 2)
cols = ['CurrAlloc%', 'Current P/L%', 'FTT%']
df_tmp[cols].sort_values(by=['CurrAlloc%'], ascending=False)

               CurrAlloc%  Current P/L%    FTT%
Category
FMCG                15.06        -25.81   70.48
FINANCE             13.18        -23.65   74.04
IT                  11.62        -47.36  122.35
MISC                 6.94        -46.31  109.86
ELECTRICAL           6.61        -11.02   53.53
PAINTS               5.05        -47.90   73.58
INSURANCE            4.74         -8.28   45.33
BANKS                4.70        -24.15   87.17
PHARMA               4.13         -7.82   41.76
AUTO                 3.66        -35.27   88.94
AC                   2.10        -15.43   46.72
HEALTHCARE           1.92        -41.37   78.26
DURABLES             1.84        -58.92   97.59
TRAVEL               1.82        -85.82  178.86
FOOTWEAR             1.77        -87.91  163.25
BREWERIES            1.69         -5.01   26.81
APPARELS             1.66        -22.28   63.99
REALTY               1.46        -15.10   34.01
CERAMICS             1.40        -66.24  116.75
REFINERIES           1.37        -11.35   39.53
CEMENT               1.24        -64.32  187.25
CABLES               1.21          7.42   92.49
CHEMICALS            1.12        -79.84  226.57
ENGINEERING          1.09        -68.19  145.11
JEWELLERY            1.08       -124.36  202.31
ENTERTAINMENT        0.77        -90.07  203.42
TEXTILES             0.44        -59.27  104.69
HOTELS               0.35       -143.57  229.49

In [29]:
# money to be made criteria-wise
df_portfolio_features.groupby('Criteria')['FTT Amt'].agg(['sum', 'count']).sort_values(by='sum', ascending=False)

                sum  count
Criteria
XY24      4041053.0     21
X40       1824412.0     16
XR        1390006.0     12
AR        1365230.0     10
X40N      1296498.0     10
OX40N      891165.0     10
XY25       469384.0      5
SR         314809.0      2

In [30]:
# money to be made conviction-wise
df_portfolio_features.groupby('Conviction')['FTT Amt'].agg(['sum', 'count']).sort_values(by='sum', ascending=False)

                  sum  count
Conviction
H-SC        3933323.0     24
X-MC        1741732.0     15
X-LC        1723854.0     13
M-SC        1583872.0     14
X-SC        1574091.0     10
H-MC         411005.0      3
L-SC         217661.0      2
M-LC         160506.0      1
M-MC         112946.0      2
H-LC          78013.0      1
L-MC          55554.0      1

In [31]:
# money to be made criteria and conviction-wise
df_portfolio_features.groupby(['Conviction', 'Criteria'])['FTT Amt'].agg(['sum', 'count']).sort_values(by='sum', ascending=False)

                           sum  count
Conviction Criteria
H-SC       XY24      1366661.0      6
           AR         986187.0      5
X-LC       X40        931183.0      7
M-SC       XY24       924090.0      6
H-SC       XR         873267.0      7
X-SC       XY24       859684.0      4
X-MC       X40        681941.0      7
           X40N       531786.0      4
X-SC       X40N       503119.0      4
H-SC       OX40N      392399.0      4
M-SC       OX40N      388089.0      5
X-LC       XY24       377648.0      2
H-SC       SR         314809.0      2
X-MC       XY24       272387.0      2
X-LC       X40N       261593.0      2
X-MC       XY25       255618.0      2
H-MC       XY24       240583.0      1
X-SC       X40        211288.0      2
M-SC       XR         193695.0      2
H-MC       AR         170422.0      2
M-LC       XR         160506.0      1
X-LC       XY25       153430.0      2
L-SC       OX40N      110677.0      1
           XR         106984.0      1
H-LC       AR          78013.0      1
M-SC       AR          77998.0      1
M-MC       XY25        60336.0      1
L-MC       XR          55554.0      1
M-MC       AR          52610.0      1

In [32]:
# notebook execution time

end_time = time.time()
execution_time = round(end_time - start_time, 0)
print(f"Notebook execution time: {execution_time} seconds")

Notebook execution time: 29.0 seconds