<a href="https://colab.research.google.com/github/ankit-rathi/Quantvesting_v2/blob/main/myStocks_Portfolio_Analysis.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
'''
!pip install pandas==2.2.2 -qq
!pip install pyxirr -qq
!pip install ta -qq
!pip install yfinance==0.2.59 -qq
'''

'\n!pip install pandas==2.2.2 -qq\n!pip install pyxirr -qq\n!pip install ta -qq\n!pip install yfinance==0.2.59 -qq\n'

In [2]:
# import libraries

import numpy as np
import pandas as pd
import datetime
import warnings
warnings.filterwarnings('ignore')
import yfinance as yfin
import ta
import matplotlib.pyplot as plt
import requests

In [3]:
# notebook start time
import time
import datetime
import pytz

start_time = time.time()

# function to print date timestamp
def print_date_time():
  tz_NY = pytz.timezone('Asia/Kolkata')
  datetime_NY = datetime.datetime.now(tz_NY)
  print("Run date time (IST):", datetime_NY.strftime("%Y-%m-%d %H:%M:%S"))

In [4]:
# function to get booked and reserved amount
def get_amt():
  # fetch the JSON data from the URL
  url = "https://raw.githubusercontent.com/ankit-rathi/Tradevesting_v1/main/data/myPortfolioAmts.json"
  response = requests.get(url)
  pf_amts = response.json()  # parse the JSON data

  # extract values from the JSON
  py_booked_amt_dm = pf_amts["py_booked_amt_dm"]
  py_booked_amt_sv = pf_amts["py_booked_amt_sv"]
  cy_booked_amt_dm = pf_amts["cy_booked_amt_dm"]
  cy_booked_amt_sv = pf_amts["cy_booked_amt_sv"]
  reserve_amt_dm = pf_amts["reserve_amt_dm"]
  reserve_amt_sv = pf_amts["reserve_amt_sv"]

  # perform calculations
  py_booked_amt = py_booked_amt_dm + py_booked_amt_sv
  cy_booked_amt = cy_booked_amt_dm + cy_booked_amt_sv
  reserve_amt = reserve_amt_dm + reserve_amt_sv
  total_booked_amt = py_booked_amt + cy_booked_amt

  return total_booked_amt, reserve_amt, cy_booked_amt, py_booked_amt

gen_output = 0

In [5]:
# function to format the amount
def format_amt(number):
    abs_number = abs(number)

    if abs_number >= 1_00_00_000:  # Crores
        formatted_amt = f"{number / 1_00_00_000:.2f} C"
    elif abs_number >= 1_00_000:  # Lakhs
        formatted_amt = f"{number / 1_00_000:.2f} L"
    elif abs_number >= 1_000:  # Thousands
        formatted_amt = f"{number / 1_000:.2f} K"
    else:
        formatted_amt = f"{number:.2f}"

    return formatted_amt

# function to set start and end date
def get_start_end_date():
  start_date = (datetime.date.today() + datetime.timedelta(days=-365)).strftime('%Y-%m-%d')
  end_date = (datetime.date.today() + datetime.timedelta(days=1)).strftime('%Y-%m-%d')
  return start_date, end_date

# function to fetch my portfolio csv
def get_mypfs_df():
  mypfs_df = pd.read_csv('https://raw.githubusercontent.com/ankit-rathi/Tradevesting_v1/main/data/myPortfolioStocks.csv')
  return mypfs_df

# function to fetch my prospects csv
def get_mypps_df():
  mypps_df = pd.read_csv('https://raw.githubusercontent.com/ankit-rathi/Tradevesting_v1/main/data/myProspectsScrips.csv')
  return mypps_df

# function to fetch screener data
def get_myscreen_df():
  myscreen_df = pd.read_csv('https://raw.githubusercontent.com/ankit-rathi/Tradevesting_v1/main/data/myScreenerDB.csv')
  return myscreen_df

# function to fetch momentum data
def get_myinvmt_df():
  myinvmt_df = pd.read_csv('https://raw.githubusercontent.com/ankit-rathi/Tradevesting_v1/main/data/myInvestments.csv')
  return myinvmt_df

# function to get the stock ids
def get_stock_ids(df_pf):
  stock_n100 = df_pf['Symbol'].unique()

  exclude = ['CADILAHC','MMTC', 'MASFIN']

  stock_ids = df_pf[~df_pf['Symbol'].isin(exclude) ]['Symbol'].unique()

  #mypf = mypf[mypf.Forecast.notnull()]
  #stock_ids = mypf['Symbol'].unique()

  #stock_ids.sort()
  return stock_ids

# get features from screener data
def get_screener_features():
  myscreen_df = get_myscreen_df()
  cols = ['Symbol', 'EPS', 'MedPE', 'ROCE%', 'ROE%', 'CapType']
  return myscreen_df[cols]

# get relative strength
def get_relative_strength(stock_list):

    # Dictionary to store stock tickers and their corresponding percentage price change
    stock_changes = {}

    # Loop through each stock and fetch its price data
    for stock in stock_list:
        try:
            # Download the stock data for the given date range
            stock_data = yfin.Ticker(stock + '.NS').history(period='1mo', interval='1d')[map(str.title, ['open', 'close', 'low', 'high', 'volume'])]

            # Calculate the percentage change for the stock
            if len(stock_data) > 0:
                start_price = stock_data['Close'].iloc[0]
                end_price = stock_data['Close'].iloc[-1]
                percent_change = round(((end_price - start_price) / start_price) * 100, 2)
                stock_changes[stock] = percent_change
            else:
                stock_changes[stock] = np.nan  # If no data is available, set to NaN

        except Exception as e:
            print(f"Error fetching data for {stock}: {e}")
            stock_changes[stock] = np.nan

    # Create a DataFrame with stock tickers and their percentage changes
    df = pd.DataFrame(list(stock_changes.items()), columns=['Symbol', 'Percent_Change'])

    # Drop any stocks with missing data (NaN values)
    df = df.dropna()

    # Calculate the percentile rank based on percentage change
    df['RSP'] = round(df['Percent_Change'].rank(pct=True) * 100, 2)
    cols = ['Symbol', 'RSP']
    df = df[cols]
    # Sort by percentile rank (optional)
    df = df.sort_values(by='RSP', ascending=False).reset_index(drop=True)

    return df

In [6]:
# function to get stock technicals
def stock_prec_dev(stock_symbol):
    #stock_symbol = 'ULTRACEMCO.NS'
    short_window = 20
    mid_window = 50
    long_window = 200
    moving_avg = 'SMA'

    start = datetime.datetime(*map(int, start_date.split('-')))
    end = datetime.datetime(*map(int, end_date.split('-')))

    stock_df = yfin.Ticker(stock_symbol + '.NS').history(period='max', interval='1d')[map(str.title, ['open', 'close', 'low', 'high', 'volume'])]

    stock_df['Max'] = round(max(stock_df['Close']),2)
    stock_df = stock_df[(stock_df.index <= end_date) & (stock_df.index >= start_date)]
    stock_df['200_SMA'] = round(stock_df['Close'].rolling(window = 200, min_periods = 1).mean(),0)
    stock_df['Dev%_200'] = round((stock_df['Close'] - stock_df['200_SMA'])*100/stock_df['200_SMA'],2)
    stock_df.dropna(axis = 0, inplace = True) # remove any null rows

    stock_df['20_SMA'] = stock_df['Close'].rolling(window=20).mean()
    stock_df['50_SMA'] = stock_df['Close'].rolling(window=50).mean()
    stock_df['Symbol'] = stock_symbol

    stock_df['Close'] = round(stock_df['Close'],2)
    stock_df['Min'] = round(min(stock_df['Close']),2)
    stock_df['RSI_14'] = ta.momentum.RSIIndicator(close=stock_df['Close'], window=14).rsi()
    stock_df['RSI_14'] = round(stock_df['RSI_14'],0)
    stock_df['Prev_Close'] = stock_df['Close'].shift(1)
    stock_df.drop(['Open', 'Low', 'High', 'Volume'], axis=1, inplace=True)
    stock_df = stock_df.tail(1)

    max_SMA = max(stock_df['20_SMA'].item(), stock_df['50_SMA'].item(), stock_df['200_SMA'].item())
    min_SMA = min(stock_df['20_SMA'].item(), stock_df['50_SMA'].item(), stock_df['200_SMA'].item())
    ABS_Spread = max_SMA - min_SMA
    stock_df['Spread%'] = round((ABS_Spread / stock_df['200_SMA'].item()) * 100,2)

    return stock_df

# function to compute stock attributes
def get_common_features(stock_ids, df_mypf):

  df_prec_dev = pd.DataFrame()
  df_tmp = get_screener_features()
  df_rs = get_relative_strength(stock_ids)

  for stock_id in stock_ids:
      tmp = stock_prec_dev(stock_id)
      tmp = tmp.reset_index()
      df_prec_dev = pd.concat([df_prec_dev, tmp], ignore_index = True)
  df_prec_dev = pd.merge(df_prec_dev, df_mypf, on= 'Symbol')
  df_prec_dev = pd.merge(df_prec_dev, df_tmp, on= 'Symbol', how='left')
  df_prec_dev = pd.merge(df_prec_dev, df_rs, on= 'Symbol', how='left')
  #print(df_prec_dev.columns)
  df_prec_dev['Curr_PE'] = round(df_prec_dev['Close']/df_prec_dev['EPS'],1)
  df_prec_dev['Dev%_PE'] = round((df_prec_dev['Curr_PE'] - df_prec_dev['MedPE'])*100/df_prec_dev['MedPE'],2)
  df_prec_dev['Conviction'] = df_prec_dev['Conviction'] + '-' + df_prec_dev['CapType']
  return df_prec_dev

# function to arrange stock features
def arrange_features(df_stocks, common_cols, diff_cols):
  df_stocks_common = df_stocks[common_cols].drop_duplicates()
  df_stocks_diff = df_stocks[diff_cols]
  df_stocks_diff['Investment'] = df_stocks_diff['AvgCost'] * df_stocks_diff['Shares']
  df_stocks_diff = df_stocks_diff.groupby(['Symbol'])[['Shares', 'Investment']].aggregate(['sum']).reset_index()
  df_stocks_diff.columns = ['Symbol', 'Shares', 'Investment']
  df_stocks_diff['AvgCost'] = round(df_stocks_diff['Investment']/df_stocks_diff['Shares'],2)
  df_stocks = pd.merge(df_stocks_diff, df_stocks_common, on='Symbol')
  return df_stocks

# plot fact distribution across dimension
def plot_pie_chart(df, dimension, fact):
  # grouping the data by category and calculating the sum of fact for each type
  grouped_data = df.groupby(dimension)[fact].sum()

  # sorting the grouped data in descending order
  grouped_data = grouped_data.sort_values(ascending=False)

  # creating a pie chart
  grouped_data.plot.pie(autopct='%1.1f%%', startangle=90, figsize=(6, 6))

  # adding a title and displaying the plot
  plt.title(f'{dimension} {fact} Distribution')
  plt.ylabel('')  # To hide the y-label
  plt.show()

In [7]:
# function to get portfolio features

def get_portfolio_features(df_common_features):

  print_date_time()
  print('-------------------')

  #df_common_features["Target"] = df_common_features["Target"].fillna(df_common_features["Max"])
  df_common_features['NTT'] = np.where(df_common_features['Strategy']== 'NTT', df_common_features["Target"], df_common_features['Max'])
  df_common_features['LTT'] = np.where(df_common_features['Strategy']== 'BTT', df_common_features["Target"], df_common_features['Max'])
  df_common_features['BOL'] = df_common_features['Min']

  tmp_df = df_common_features[df_common_features['Symbol'].isin(mypf_df[mypf_df['InPortfolio'] != 'NA'].Symbol.values)]
  print('qualified stocks: '+str(len(tmp_df['Symbol'].unique())))
  tmp_df1 = tmp_df[tmp_df['LatestQtr'] == 1]
  print('with latest results: '+str(len(tmp_df1['Symbol'].unique())))
  tmp_df1 = tmp_df1[tmp_df1['StarStock'] == 1]
  print('still star stocks: '+str(len(tmp_df1['Symbol'].unique())))
  tmp_df['Investment'] = tmp_df['AvgCost'] * tmp_df['Shares']
  tmp_df['Current'] = round(tmp_df['Close'] * tmp_df['Shares'],0)
  tmp_df['Previous'] = tmp_df['Prev_Close'] * tmp_df['Shares']
  tmp_df['EstimatedST'] = tmp_df['NTT'] * tmp_df['Shares']
  tmp_df['EstimatedLT'] = tmp_df['LTT'] * tmp_df['Shares']
  tmp_df['Current P/L'] = round((tmp_df['Current'] - tmp_df['Investment']),0)
  tmp_df['Today P/L%'] = round((tmp_df['Current'] - tmp_df['Previous'])*100/tmp_df['Previous'],2)
  tmp_df['Current P/L%'] = round((tmp_df['Current'] - tmp_df['Investment'])*100/tmp_df['Investment'],2)
  tmp_df['EstimatedST P/L%'] = round((tmp_df['EstimatedST'] - tmp_df['Investment'])*100/tmp_df['Investment'],2)
  tmp_df['EstimatedLT P/L%'] = round((tmp_df['EstimatedLT'] - tmp_df['Investment'])*100/tmp_df['Investment'],2)
  tmp_df['NTT%'] = round((tmp_df['NTT'] - tmp_df['Close'])*100/tmp_df['Close'],2)
  tmp_df['LTT%'] = round((tmp_df['LTT'] - tmp_df['Close'])*100/tmp_df['Close'],2)
  tmp_df['Gained%'] = round((tmp_df['Close'] - tmp_df['BOL'])*100/tmp_df['BOL'],2)
  investment = round(sum(tmp_df['AvgCost']*tmp_df['Shares']),0)
  current = round(sum(tmp_df['Close']*tmp_df['Shares']),0)
  tmp_df['InitAlloc%'] = round(tmp_df['Investment']*100/investment,2)
  tmp_df['CurrAlloc%'] = round(tmp_df['Current']*100/current,2)
  tmp_df['FTT'] = tmp_df['LTT']
  tmp_df.loc[tmp_df['Strategy'] == 'NTT', 'FTT'] = tmp_df['NTT']
  tmp_df['FTT%'] = tmp_df['LTT%']
  tmp_df.loc[tmp_df['Strategy'] == 'NTT', 'FTT%'] = tmp_df['NTT%']
  tmp_df['FTT Amt'] = round(tmp_df['FTT%'] * tmp_df['Current']/100,0)
  tmp_df['OTT%'] = round((tmp_df['FTT'] - tmp_df['AvgCost'])*100/tmp_df['AvgCost'],2)
  tmp_df['RRR Ind'] = round(tmp_df['Current P/L']/tmp_df['FTT Amt'],2)
  tmp_df['Risk Ind'] = round(tmp_df['Current P/L%']*tmp_df['CurrAlloc%'],0)

  return tmp_df

# function to print portfolio features
def print_portfolio_stats(df_portfolio_features, myinvmt_df):
  from pyxirr import xirr

  total_booked_amt, reserve_amt, cy_booked_amt, py_booked_amt = get_amt()

  dates = myinvmt_df['Date'].values
  dates = np.append(dates, datetime.date.today().strftime('%d-%b-%y'))
  investment = myinvmt_df['Investment'].values
  dates= pd.to_datetime(dates)

  current = round(sum(df_portfolio_features['Close']*df_portfolio_features['Shares']),0) + reserve_amt
  investment_xirr = np.append(investment, current)
  cagr = round(xirr(pd.DataFrame({"dates": dates, "amounts": investment_xirr}))*100,2)

  investment = -sum(investment)
  invested = round(sum(df_portfolio_features['AvgCost']*df_portfolio_features['Shares']),0) + reserve_amt
  previous = round(sum(df_portfolio_features['Prev_Close']*df_portfolio_features['Shares']),0) + reserve_amt
  cy_invested = investment + py_booked_amt

  today_pnl_amount = current-previous
  today_pnl_percentage = round((current-previous)*100/previous,2)

  curr_pnl_amount = current-invested
  curr_pnl_percentage = round((curr_pnl_amount)*100/(cy_invested),2)

  cy_pnl_amount = cy_booked_amt + curr_pnl_amount
  cy_pnl_percentage = round((cy_pnl_amount)*100/cy_invested,2)

  overall_pnl_amount = total_booked_amt + curr_pnl_amount
  overall_pnl_percentage = round((overall_pnl_amount)*100/investment,2)

  estimate_st = round(sum(df_portfolio_features['FTT']*df_portfolio_features['Shares']),0)  + reserve_amt
  est_st_pnl_amount = estimate_st-current
  est_st_pnl_percentage = round((est_st_pnl_amount)*100/current,2)

  estimate_lt = round(sum(df_portfolio_features['LTT']*df_portfolio_features['Shares']),0)  + reserve_amt
  est_lt_pnl_amount = estimate_lt-current
  est_lt_pnl_percentage = round((est_lt_pnl_amount)*100/current,2)

  total_profit = round(sum(df_portfolio_features[df_portfolio_features['Current P/L%'] > 0]['Current']) - sum(df_portfolio_features[df_portfolio_features['Current P/L%'] > 0]['Investment']),0)
  total_loss = round(sum(df_portfolio_features[df_portfolio_features['Current P/L%'] < 0]['Current']) - sum(df_portfolio_features[df_portfolio_features['Current P/L%'] < 0]['Investment']),0)

  cy_booked_percentage = round((cy_booked_amt)*100/current,2)
  py_booked_percentage = round((py_booked_amt)*100/investment,2)
  total_booked_percentage = round((total_booked_amt)*100/investment,2)

  print('-------------------')
  print('Initial Investment: ', format_amt(investment))
  print('CY Investment: ', format_amt(cy_invested))
  print('Reserve: ', format_amt(reserve_amt))
  print('Current: ',  format_amt(current))
  print('-------------------')
  print('Today PnL: '+ '{} ({}%)'.format(format_amt(today_pnl_amount), today_pnl_percentage))
  print('Current PnL: '+ '{} ({}%)'.format(format_amt(curr_pnl_amount), curr_pnl_percentage))
  print('CY Booked + Current PnL: '+ '{} ({}%)'.format(format_amt(cy_pnl_amount), cy_pnl_percentage))
  print('-------------------')
  print('Total profit: ', format_amt(total_profit))
  print('Total loss: ', format_amt(total_loss))
  print('-------------------')
  print('Total Booked + Current PnL: '+ '{} ({}%)'.format(format_amt(overall_pnl_amount), overall_pnl_percentage))
  print('Total Booked PnL: '+ '{} ({}%)'.format(format_amt(total_booked_amt), total_booked_percentage))
  print('Curr Year Booked PnL: '+ '{} ({}%)'.format(format_amt(cy_booked_amt), cy_booked_percentage))
  print('Prev Year Booked PnL: '+ '{} ({}%)'.format(format_amt(py_booked_amt), py_booked_percentage))
  print('===================')
  print('Est FTT: ',  format_amt(estimate_st))
  print('Est FTT PnL: '+ '{} ({}%)'.format(format_amt(est_st_pnl_amount), est_st_pnl_percentage))

  print('===================')
  print('Deployed: ', format_amt(investment))

  print('Current: ', format_amt(current))

  print('CAGR/XIRR %: '+'{}%'.format(cagr))

In [8]:
# get start and end date
start_date, end_date = get_start_end_date()

# get portfolio and prospects data
mypfs_df = get_mypfs_df()
mypps_df = get_mypps_df()
myinvmt_df = get_myinvmt_df()

# merge above datasets
mypf_df = pd.merge(mypfs_df, mypps_df, on="Symbol")

# seggregate dm and sv portfolio
dm_pf = mypf_df[mypf_df['InPortfolio'] == 'DM']
sv_pf = mypf_df[mypf_df['InPortfolio'] == 'SV']

# build portfolio stock dataframe
dm_stocks = get_stock_ids(dm_pf)
sv_stocks = get_stock_ids(sv_pf)
df_stocks = pd.concat([dm_pf,sv_pf], ignore_index = True)

# arrange common and diff stock features
common_cols = ['Symbol', 'Target', 'Criteria', 'Strategy', 'CumlRnk', 'LatestQtr', 'StarStock', 'Conviction', 'Category', 'InFolio', 'XIRR', 'MBQ']
diff_cols = ['Symbol', 'AvgCost', 'Shares']
df_stocks = arrange_features(df_stocks, common_cols, diff_cols)

# get common features
stock_ids = df_stocks['Symbol'].values
df_common_features = get_common_features(stock_ids, df_stocks)

df_common_features.reset_index(drop=True, inplace=True)
df_common_features.drop(['Date'], axis=1, inplace=True)
# get and print portfolio features
df_portfolio_features = get_portfolio_features(df_common_features)

print_portfolio_stats(df_portfolio_features, myinvmt_df)

df = df_portfolio_features
#plot_pie_chart(df, 'CapType', 'Current')
list_ox40n = list(df[df['MBQ'].str.contains('OX40N', na=False)]['Symbol'].values)

Run date time (IST): 2026-08-10 09:22:53
-------------------
qualified stocks: 88
with latest results: 30
still star stocks: 19
-------------------
Initial Investment:  1.46 C
CY Investment:  1.89 C
Reserve:  2.24 L
Current:  1.61 C
-------------------
Today PnL: -13.65 K (-0.08%)
Current PnL: -30.65 L (-16.22%)
CY Booked + Current PnL: -26.43 L (-13.99%)
-------------------
Total profit:  3.76 L
Total loss:  -34.41 L
-------------------
Total Booked + Current PnL: 16.44 L (11.26%)
Total Booked PnL: 47.09 L (32.24%)
Curr Year Booked PnL: 4.22 L (2.61%)
Prev Year Booked PnL: 42.87 L (29.35%)
===================
Est FTT:  2.67 C
Est FTT PnL: 1.05 C (65.18%)
===================
Deployed:  1.46 C
Current:  1.61 C
CAGR/XIRR %: 4.61%

In [9]:
# top 5 near their targets
cols = ['Symbol', 'Today P/L%', 'Current P/L%', 'FTT%', 'OTT%', 'FTT Amt', 'Current P/L', 'Current', 'FTT', 'Dev%_PE', 'RSI_14','Conviction', 'Spread%',  'CumlRnk', 'RRR Ind', 'CurrAlloc%', 'Gained%', 'Criteria', 'Strategy', 'Category']
df_tmp = df_portfolio_features[~df_portfolio_features['Symbol'].isin(['ENRIN','BLUSPRING','DIGITIDE'])]
df_tmp = df_tmp.sort_values(by = 'FTT Amt', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
55,MEDANTA,1.93,26.92,0.16,27.12,358.0,47522.0,224039.0,1486.00,23.02,70.0,X-SC,15.93,87.0,132.74,1.41,54.38,XY24,NTT,HEALTHCARE
52,M&M,0.77,11.44,6.63,18.82,17782.0,27523.0,268204.0,3762.88,-2.96,71.0,X-LC,5.36,25.0,1.55,1.68,21.66,X40N,ATH,AUTO
80,UNITDSPR,0.79,11.98,7.85,20.77,20582.0,28053.0,262197.0,1644.00,-0.62,69.0,X-MC,8.02,64.0,1.36,1.65,26.04,X40N,NTT,BREWERIES
79,TTKPRESTIG,-0.54,-20.37,25.69,0.09,20616.0,-20526.0,80251.0,770.00,86.34,44.0,M-SC,13.42,250.0,-1.00,0.50,44.44,OX40N,NTT,DURABLES
69,SIS,-1.06,-1.16,22.69,21.26,24900.0,-1293.0,109739.0,528.00,2619.17,50.0,H-SC,22.43,168.0,-0.05,0.69,63.17,OX40N,NTT,MISC

In [10]:
# top 5 today
df_tmp = df_portfolio_features.sort_values(by = 'Today P/L%', ascending=False)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
43,INDIGOPNTS,2.19,-18.66,22.97,0.02,32613.0,-32579.0,141980.0,1408.0,116.52,65.0,M-SC,5.38,222.0,-1.00,0.89,61.09,OX40N,NTT,PAINTS
55,MEDANTA,1.93,26.92,0.16,27.12,358.0,47522.0,224039.0,1486.0,23.02,70.0,X-SC,15.93,87.0,132.74,1.41,54.38,XY24,NTT,HEALTHCARE
42,INDIAMART,1.71,-23.29,161.94,100.92,153203.0,-28731.0,94605.0,4675.6,-65.43,42.0,H-SC,12.22,140.0,-0.19,0.59,2.41,AR,ATH,MISC
0,5PAISA,1.55,-28.94,58.87,12.90,91409.0,-63224.0,155272.0,593.0,128.37,57.0,H-SC,11.16,170.0,-0.69,0.98,49.84,OX40N,NTT,FINANCE
82,VALIANTORG,1.54,-39.12,186.06,74.15,185321.0,-64002.0,99603.0,838.0,-279.04,63.0,H-SC,4.11,145.0,-0.35,0.63,48.22,XR,NTT,CHEMICALS

In [11]:
# bottom 5 today
df_tmp = df_portfolio_features.sort_values(by = 'Today P/L%', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
5,ATULAUTO,-7.47,-7.93,58.11,45.57,105465.0,-15640.0,181492.0,844.0,3943.24,56.0,M-SC,9.83,248.0,-0.15,1.14,39.67,XY24,NTT,AUTO
18,COFFEEDAY,-5.00,-47.95,159.91,35.27,94504.0,-54451.0,59098.0,80.0,-59.76,43.0,L-SC,5.00,266.0,-0.58,0.37,45.74,XR,NTT,HOTELS
61,RECLTD,-2.18,-2.82,24.23,20.74,47842.0,-5720.0,197450.0,446.0,7.42,49.0,M-MC,3.59,191.0,-0.12,1.24,19.02,XY25,NTT,FINANCE
66,SFL,-1.97,-34.66,93.81,26.63,160720.0,-90893.0,171325.0,1287.0,29.73,31.0,M-SC,23.41,242.0,-0.57,1.08,42.98,XY24,NTT,MISC
81,VAIBHAVGBL,-1.26,-25.97,117.17,60.77,158536.0,-47471.0,135304.0,521.0,55.92,41.0,H-SC,11.26,160.0,-0.30,0.85,37.66,XR,NTT,JEWELLERY

In [12]:
# top 5 to exit based on CumlRnk
df_tmp = df_portfolio_features[~df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])]
df_tmp = df_tmp[(df_tmp['Current P/L%'] > -1) & (df_tmp['Current P/L%'] < 1)].sort_values(by = 'CumlRnk', ascending=False)
df_tmp[cols].head()

Empty DataFrame
Columns: [Symbol, Today P/L%, Current P/L%, FTT%, OTT%, FTT Amt, Current P/L, Current, FTT, Dev%_PE, RSI_14, Conviction, Spread%, CumlRnk, RRR Ind, CurrAlloc%, Gained%, Criteria, Strategy, Category]
Index: []

In [13]:
# OX40N stocks to exit
df_tmp = df_portfolio_features[(df_portfolio_features['Symbol'].isin(list_ox40n))].sort_values(by = 'Current P/L%', ascending=False)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
25,FINCABLES,0.32,30.20,59.69,107.91,114740.0,44583.0,192227.0,1641.55,17.20,51.0,M-SC,17.20,220.0,0.39,1.21,44.62,OX40N,ATH,CABLES
69,SIS,-1.06,-1.16,22.69,21.26,24900.0,-1293.0,109739.0,528.00,2619.17,50.0,H-SC,22.43,168.0,-0.05,0.69,63.17,OX40N,NTT,MISC
43,INDIGOPNTS,2.19,-18.66,22.97,0.02,32613.0,-32579.0,141980.0,1408.00,116.52,65.0,M-SC,5.38,222.0,-1.00,0.89,61.09,OX40N,NTT,PAINTS
79,TTKPRESTIG,-0.54,-20.37,25.69,0.09,20616.0,-20526.0,80251.0,770.00,86.34,44.0,M-SC,13.42,250.0,-1.00,0.50,44.44,OX40N,NTT,DURABLES
16,CERA,-0.68,-21.27,57.37,23.89,79448.0,-37420.0,138483.0,9475.00,-24.11,43.0,H-SC,12.65,153.0,-0.47,0.87,34.62,OX40N,NTT,CERAMICS

In [14]:
# top 5 to book for rotation
df_tmp = df_portfolio_features[(df_portfolio_features['Current P/L%'] > 20) ].sort_values(by = 'CumlRnk', ascending=False)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
25,FINCABLES,0.32,30.20,59.69,107.91,114740.0,44583.0,192227.0,1641.55,17.20,51.0,M-SC,17.20,220.0,0.39,1.21,44.62,OX40N,ATH,CABLES
55,MEDANTA,1.93,26.92,0.16,27.12,358.0,47522.0,224039.0,1486.00,23.02,70.0,X-SC,15.93,87.0,132.74,1.41,54.38,XY24,NTT,HEALTHCARE
58,QUESS,0.79,28.58,35.25,73.90,48403.0,30520.0,137313.0,424.00,-30.58,60.0,X-SC,39.27,80.0,0.63,0.86,88.99,XY24,NTT,MISC

In [15]:
# top 5 to monitor for exit
df_tmp = df_portfolio_features[~df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])]
df_tmp = df_tmp[(df_tmp['Current P/L%'] > 0) ].sort_values(by = 'Dev%_PE', ascending=False)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
70,STARHEALTH,-0.70,9.50,34.49,47.26,106168.0,26699.0,307822.0,761.00,72.93,41.0,H-SC,17.27,173.0,0.25,1.93,33.09,XY24,NTT,INSURANCE
25,FINCABLES,0.32,30.20,59.69,107.91,114740.0,44583.0,192227.0,1641.55,17.20,51.0,M-SC,17.20,220.0,0.39,1.21,44.62,OX40N,ATH,CABLES
87,ZYDUSLIFE,0.62,18.22,14.62,35.51,36223.0,38189.0,247763.0,1285.01,2.70,51.0,H-MC,15.43,120.0,1.05,1.56,30.39,AR,ATH,PHARMA

In [16]:
# top 5 to book for rotation from weak conviction
df_tmp = df_portfolio_features[~df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])]
df_tmp = df_tmp[~df_tmp['Criteria'].isin(['XY25','XY24','X40', 'X40N'])].sort_values(by = 'RRR Ind', ascending=False)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
87,ZYDUSLIFE,0.62,18.22,14.62,35.51,36223.0,38189.0,247763.0,1285.01,2.70,51.0,H-MC,15.43,120.0,1.05,1.56,30.39,AR,ATH,PHARMA
25,FINCABLES,0.32,30.20,59.69,107.91,114740.0,44583.0,192227.0,1641.55,17.20,51.0,M-SC,17.20,220.0,0.39,1.21,44.62,OX40N,ATH,CABLES
69,SIS,-1.06,-1.16,22.69,21.26,24900.0,-1293.0,109739.0,528.00,2619.17,50.0,H-SC,22.43,168.0,-0.05,0.69,63.17,OX40N,NTT,MISC
3,ALKYLAMINE,-0.73,-19.93,140.47,92.54,113556.0,-20123.0,80840.0,4520.85,-14.24,55.0,H-SC,13.16,142.0,-0.18,0.51,53.51,SR,ATH,CHEMICALS
42,INDIAMART,1.71,-23.29,161.94,100.92,153203.0,-28731.0,94605.0,4675.60,-65.43,42.0,H-SC,12.22,140.0,-0.19,0.59,2.41,AR,ATH,MISC

In [17]:
# top 5 to accumulate based on lowest RSI_14
df_tmp = df_portfolio_features[df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])].sort_values(by = 'RSI_14', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
34,HDFCBANK,0.08,-10.65,46.66,31.05,122209.0,-31207.0,261913.0,1073.00,-25.47,35.0,X-LC,10.98,26.0,-0.26,1.64,1.66,X40,BTT,BANKS
57,PGHH,-0.01,-36.34,107.35,32.01,145927.0,-77584.0,135936.0,17616.87,-56.92,35.0,X-MC,19.18,57.0,-0.53,0.85,0.22,X40,ATH,FMCG
35,HDFCLIFE,-0.77,-8.10,51.42,39.15,118480.0,-20321.0,230416.0,811.41,-31.58,38.0,X-LC,16.13,31.0,-0.17,1.45,0.00,X40,ATH,INSURANCE
23,DMART,0.05,-4.89,38.17,31.42,113194.0,-15238.0,296552.0,5391.45,-20.94,41.0,X-LC,3.27,14.0,-0.13,1.86,7.01,X40N,ATH,FMCG
83,VBL,0.89,-9.63,50.11,35.66,159331.0,-33882.0,317962.0,669.42,-20.42,41.0,X-LC,7.65,13.0,-0.21,2.00,17.07,X40N,ATH,FMCG

In [18]:
# top 5 to accumulate based on Spread and CumlRnk
df_tmp = df_portfolio_features[df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])]
df_tmp = df_tmp[(df_tmp['CumlRnk'] < 100)].sort_values(by = 'Spread%', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
19,COLPAL,-0.16,-23.05,81.74,39.86,165662.0,-60695.0,202670.0,3683.41,-6.97,45.0,X-MC,1.54,62.0,-0.37,1.27,14.64,XY25,ATH,FMCG
11,BERGEPAINT,1.50,-0.76,26.28,25.32,67221.0,-1961.0,255788.0,680.00,-6.11,63.0,X-MC,2.36,68.0,-0.03,1.61,34.13,XY24,NTT,PAINTS
8,BAJAJHLDNG,0.51,1.71,26.09,28.24,67934.0,4378.0,260383.0,14274.15,-6.72,62.0,X-LC,2.73,28.0,0.06,1.64,31.05,X40,ATH,FINANCE
23,DMART,0.05,-4.89,38.17,31.42,113194.0,-15238.0,296552.0,5391.45,-20.94,41.0,X-LC,3.27,14.0,-0.13,1.86,7.01,X40N,ATH,FMCG
26,GILLETTE,0.21,-9.02,42.58,29.72,98360.0,-22896.0,231000.0,10978.86,-30.15,46.0,X-SC,3.36,83.0,-0.23,1.45,6.16,X40,ATH,FMCG

In [19]:
# top 5 to accumulate based on lowest Gained%
df_tmp = df_portfolio_features[df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])].sort_values(by = 'Gained%', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
35,HDFCLIFE,-0.77,-8.10,51.42,39.15,118480.0,-20321.0,230416.0,811.41,-31.58,38.0,X-LC,16.13,31.0,-0.17,1.45,0.00,X40,ATH,INSURANCE
57,PGHH,-0.01,-36.34,107.35,32.01,145927.0,-77584.0,135936.0,17616.87,-56.92,35.0,X-MC,19.18,57.0,-0.53,0.85,0.22,X40,ATH,FMCG
34,HDFCBANK,0.08,-10.65,46.66,31.05,122209.0,-31207.0,261913.0,1073.00,-25.47,35.0,X-LC,10.98,26.0,-0.26,1.64,1.66,X40,BTT,BANKS
20,DABUR,0.50,-19.44,78.38,43.70,156638.0,-48224.0,199844.0,735.00,-26.86,41.0,X-MC,9.17,70.0,-0.31,1.26,1.69,XY24,BTT,FMCG
39,ICICIGI,-0.74,-13.83,37.96,18.89,65459.0,-27668.0,172441.0,2244.41,-27.43,42.0,X-MC,10.11,66.0,-0.42,1.08,2.73,X40,ATH,INSURANCE

In [20]:
# top 5 to accumulate based on lowest CurrAlloc%
df_tmp = df_portfolio_features[df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])].sort_values(by = 'CurrAlloc%', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
10,BATAINDIA,0.62,-53.23,189.10,35.20,113791.0,-68495.0,60175.0,2096.00,-21.16,63.0,X-SC,14.03,91.0,-0.60,0.38,20.90,X40,NTT,FOOTWEAR
62,RELAXO,-0.35,-45.35,178.71,52.31,141765.0,-65833.0,79327.0,1176.00,-41.83,59.0,X-SC,11.80,92.0,-0.46,0.50,77.36,X40N,NTT,FOOTWEAR
57,PGHH,-0.01,-36.34,107.35,32.01,145927.0,-77584.0,135936.0,17616.87,-56.92,35.0,X-MC,19.18,57.0,-0.53,0.85,0.22,X40,ATH,FMCG
58,QUESS,0.79,28.58,35.25,73.90,48403.0,30520.0,137313.0,424.00,-30.58,60.0,X-SC,39.27,80.0,0.63,0.86,88.99,XY24,NTT,MISC
40,ICICIPRULI,-0.76,-17.72,58.32,30.28,94539.0,-34901.0,162104.0,787.27,-39.83,45.0,X-MC,13.51,78.0,-0.37,1.02,8.00,X40,ATH,INSURANCE

In [21]:
# top 5 to accumulate based on CumlRnk
df_tmp = df_portfolio_features.sort_values(by = 'CumlRnk', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
47,ITC,-0.30,-21.31,58.46,24.70,182766.0,-84644.0,312634.0,452.00,-58.75,50.0,X-LC,11.21,1.0,-0.46,1.96,3.52,X40,NTT,FMCG
75,TCS,-0.07,-28.05,72.61,24.20,242035.0,-129937.0,333336.0,4230.71,-39.04,63.0,X-LC,15.48,2.0,-0.54,2.09,24.30,X40,ATH,IT
45,INFY,0.17,-16.21,67.53,40.38,213032.0,-61007.0,315463.0,1972.00,-36.87,63.0,X-LC,16.30,3.0,-0.29,1.98,19.47,X40,NTT,IT
77,TMPV,0.50,-17.03,72.04,42.75,248727.0,-70845.0,345262.0,600.00,-83.62,57.0,X-LC,5.29,4.0,-0.28,2.17,18.72,XY24,NTT,AUTO
33,HCLTECH,-0.07,-9.32,36.71,23.97,103019.0,-28856.0,280630.0,1853.42,-7.78,68.0,X-LC,13.32,8.0,-0.28,1.76,32.42,X40,ATH,IT

In [22]:
# top 5 for average up
df_tmp = df_portfolio_features[(df_portfolio_features['Dev%_200'] > 5)].sort_values(by = 'CurrAlloc%', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
44,INDUSINDBK,-0.35,-24.81,76.75,32.89,44553.0,-19158.0,58049.0,1800.00,-373.11,55.0,L-MC,13.86,258.0,-0.43,0.36,43.11,XR,NTT,BANKS
62,RELAXO,-0.35,-45.35,178.71,52.31,141765.0,-65833.0,79327.0,1176.00,-41.83,59.0,X-SC,11.80,92.0,-0.46,0.50,77.36,X40N,NTT,FOOTWEAR
79,TTKPRESTIG,-0.54,-20.37,25.69,0.09,20616.0,-20526.0,80251.0,770.00,86.34,44.0,M-SC,13.42,250.0,-1.00,0.50,44.44,OX40N,NTT,DURABLES
3,ALKYLAMINE,-0.73,-19.93,140.47,92.54,113556.0,-20123.0,80840.0,4520.85,-14.24,55.0,H-SC,13.16,142.0,-0.18,0.51,53.51,SR,ATH,CHEMICALS
12,BOSCH-HCIL,-0.73,-26.82,36.64,-0.01,34268.0,-34279.0,93526.0,2282.00,19030.43,83.0,M-SC,3.46,231.0,-1.00,0.59,59.19,OX40N,BTT,AC

In [23]:
# top 5 RSP
df_tmp = df_portfolio_features.sort_values(by = 'RSP', ascending=False)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
12,BOSCH-HCIL,-0.73,-26.82,36.64,-0.01,34268.0,-34279.0,93526.0,2282.00,19030.43,83.0,M-SC,3.46,231.0,-1.00,0.59,59.19,OX40N,BTT,AC
75,TCS,-0.07,-28.05,72.61,24.20,242035.0,-129937.0,333336.0,4230.71,-39.04,63.0,X-LC,15.48,2.0,-0.54,2.09,24.30,X40,ATH,IT
33,HCLTECH,-0.07,-9.32,36.71,23.97,103019.0,-28856.0,280630.0,1853.42,-7.78,68.0,X-LC,13.32,8.0,-0.28,1.76,32.42,X40,ATH,IT
38,HYUNDAI,1.10,15.07,25.08,43.94,72534.0,37879.0,289211.0,2782.73,-4.68,75.0,X-LC,4.58,29.0,0.52,1.82,32.79,X40N,ATH,AUTO
68,SIEMENS,-0.34,5.51,18.38,24.90,36087.0,10245.0,196340.0,4648.66,64.83,68.0,H-LC,11.26,51.0,0.28,1.23,38.53,AR,ATH,ELECTRICAL

In [24]:
# Top N allocation
df_tmp = df_portfolio_features.sort_values(by = 'CurrAlloc%', ascending=False)
top_n_values = [10, 25, 50]

sum_df = pd.DataFrame({
    'Top_N': top_n_values,
    'Sum_Alloc%': [df_tmp['CurrAlloc%'].head(n).sum() for n in top_n_values]
})

sum_df

   Top_N  Sum_Alloc%
0     10       19.73
1     25       44.77
2     50       76.86

In [25]:
# market-cap-wise allocation
df_tmp = df_portfolio_features[cols]
df_tmp.groupby(df_tmp['Conviction'].str[-2:])['CurrAlloc%'].sum().sort_values(ascending=False)

Conviction
SC    39.22
LC    37.81
MC    22.97
Name: CurrAlloc%, dtype: float64

In [26]:
# criteria-wise allocation
df_portfolio_features.groupby('Criteria')['CurrAlloc%'].sum().sort_values(ascending=False)

Criteria
X40      26.39
XY24     25.00
X40N     18.53
XR        9.09
XY25      7.27
OX40N     6.86
AR        6.02
SR        0.84
Name: CurrAlloc%, dtype: float64

In [27]:
# conviction-wise allocation
df_portfolio_features.groupby('Conviction')['CurrAlloc%'].sum().sort_values(ascending=False)

Conviction
X-LC    35.76
H-SC    19.18
X-MC    18.75
X-SC     9.96
M-SC     9.57
H-MC     2.62
M-MC     1.24
H-LC     1.23
M-LC     0.82
L-SC     0.51
L-MC     0.36
Name: CurrAlloc%, dtype: float64

In [28]:
# sector-wise stats
df_tmp = df_portfolio_features.groupby('Category')[['CurrAlloc%', 'Current', 'Current P/L', 'FTT Amt']].sum().sort_values(by=['Current', 'Current P/L'], ascending=False)
df_tmp['Current P/L%'] = round(df_tmp['Current P/L'] * 100 / df_tmp['Current'], 2)
df_tmp['FTT%'] = round(df_tmp['FTT Amt'] * 100 / df_tmp['Current'], 2)
cols = ['CurrAlloc%', 'Current P/L%', 'FTT%']
df_tmp[cols].sort_values(by=['CurrAlloc%'], ascending=False)

               CurrAlloc%  Current P/L%    FTT%
Category
FMCG                15.50        -20.75   64.23
IT                  11.22        -33.35   99.54
FINANCE              9.30        -15.53   64.08
AUTO                 8.40         -1.11   37.32
MISC                 6.84        -23.04   75.83
BANKS                6.06        -10.41   58.03
PHARMA               5.63          7.49   18.75
INSURANCE            5.48         -6.44   44.07
PAINTS               5.46        -13.39   32.73
ELECTRICAL           4.11         -7.90   45.67
HEALTHCARE           2.11         -6.44   34.22
AC                   1.81        -11.34   41.53
APPARELS             1.74          3.08   29.47
REFINERIES           1.70        -10.11   47.10
FOOTWEAR             1.68        -65.90  132.42
BREWERIES            1.65         10.70    7.85
DURABLES             1.51        -61.12  100.31
TRAVEL               1.46        -92.34  188.64
CERAMICS             1.34        -43.58   87.20
CABLES               1.21         23.19   59.69
ENGINEERING          1.20        -26.46   84.30
CHEMICALS            1.14        -46.62  165.64
CEMENT               1.02        -64.29  187.21
JEWELLERY            0.99       -103.47  174.16
ENTERTAINMENT        0.68        -78.33  184.68
TEXTILES             0.39        -49.64   92.31
HOTELS               0.37        -92.14  159.91

In [29]:
# money to be made criteria-wise
df_portfolio_features.groupby('Criteria')['FTT Amt'].agg(['sum', 'count']).sort_values(by='sum', ascending=False)

                sum  count
Criteria
XY24      3421220.0     20
X40       2021138.0     18
XR        1351875.0     13
X40N      1132095.0     12
AR        1071942.0      8
OX40N      701008.0     10
XY25       542084.0      5
SR         282849.0      2

In [30]:
# money to be made conviction-wise
df_portfolio_features.groupby('Conviction')['FTT Amt'].agg(['sum', 'count']).sort_values(by='sum', ascending=False)

                  sum  count
Conviction
H-SC        3298591.0     23
X-LC        2362853.0     20
X-MC        1470295.0     14
M-SC        1394840.0     14
X-SC        1216115.0      9
H-MC         281450.0      2
L-SC         209831.0      2
M-LC         161754.0      1
M-MC          47842.0      1
L-MC          44553.0      1
H-LC          36087.0      1

In [31]:
# money to be made criteria and conviction-wise
df_portfolio_features.groupby(['Conviction', 'Criteria'])['FTT Amt'].agg(['sum', 'count']).sort_values(by='sum', ascending=False)

                           sum  count
Conviction Criteria
X-LC       X40       1158829.0      9
H-SC       XY24       989910.0      5
           AR         923104.0      5
M-SC       XY24       839013.0      6
H-SC       XR         805046.0      7
X-SC       XY24       706796.0      4
X-MC       X40        650158.0      7
X-LC       X40N       489244.0      6
           XY24       416415.0      2
X-MC       X40N       345683.0      3
H-SC       OX40N      297682.0      4
X-SC       X40N       297168.0      3
M-SC       OX40N      287999.0      5
H-SC       SR         282849.0      2
X-MC       XY25       250595.0      2
H-MC       XY24       245227.0      1
X-LC       XY25       243647.0      2
X-MC       XY24       223859.0      2
X-SC       X40        212151.0      2
M-SC       XR         191300.0      2
M-LC       XR         161754.0      1
L-SC       OX40N      115327.0      1
           XR          94504.0      1
M-SC       AR          76528.0      1
X-LC       XR          54718.0      1
M-MC       XY25        47842.0      1
L-MC       XR          44553.0      1
H-MC       AR          36223.0      1
H-LC       AR          36087.0      1

In [32]:
# notebook execution time

end_time = time.time()
execution_time = round(end_time - start_time, 0)
print(f"Notebook execution time: {execution_time} seconds")

Notebook execution time: 26.0 seconds