<a href="https://colab.research.google.com/github/ankit-rathi/Quantvesting_v2/blob/main/myStocks_Portfolio_Analysis.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
'''
!pip install pandas==2.2.2 -qq
!pip install pyxirr -qq
!pip install ta -qq
!pip install yfinance==0.2.59 -qq
'''

'\n!pip install pandas==2.2.2 -qq\n!pip install pyxirr -qq\n!pip install ta -qq\n!pip install yfinance==0.2.59 -qq\n'

In [2]:
# import libraries

import numpy as np
import pandas as pd
import datetime
import warnings
warnings.filterwarnings('ignore')
import yfinance as yfin
import ta
import matplotlib.pyplot as plt
import requests

In [3]:
# notebook start time
import time
import datetime
import pytz

start_time = time.time()

# function to print date timestamp
def print_date_time():
  tz_NY = pytz.timezone('Asia/Kolkata')
  datetime_NY = datetime.datetime.now(tz_NY)
  print("Run date time (IST):", datetime_NY.strftime("%Y-%m-%d %H:%M:%S"))

In [4]:
# function to get booked and reserved amount
def get_amt():
  # fetch the JSON data from the URL
  url = "https://raw.githubusercontent.com/ankit-rathi/Tradevesting_v1/main/data/myPortfolioAmts.json"
  response = requests.get(url)
  pf_amts = response.json()  # parse the JSON data

  # extract values from the JSON
  py_booked_amt_dm = pf_amts["py_booked_amt_dm"]
  py_booked_amt_sv = pf_amts["py_booked_amt_sv"]
  cy_booked_amt_dm = pf_amts["cy_booked_amt_dm"]
  cy_booked_amt_sv = pf_amts["cy_booked_amt_sv"]
  reserve_amt_dm = pf_amts["reserve_amt_dm"]
  reserve_amt_sv = pf_amts["reserve_amt_sv"]

  # perform calculations
  py_booked_amt = py_booked_amt_dm + py_booked_amt_sv
  cy_booked_amt = cy_booked_amt_dm + cy_booked_amt_sv
  reserve_amt = reserve_amt_dm + reserve_amt_sv
  total_booked_amt = py_booked_amt + cy_booked_amt

  return total_booked_amt, reserve_amt, cy_booked_amt, py_booked_amt

gen_output = 0

In [5]:
# function to format the amount
def format_amt(number):
    abs_number = abs(number)

    if abs_number >= 1_00_00_000:  # Crores
        formatted_amt = f"{number / 1_00_00_000:.2f} C"
    elif abs_number >= 1_00_000:  # Lakhs
        formatted_amt = f"{number / 1_00_000:.2f} L"
    elif abs_number >= 1_000:  # Thousands
        formatted_amt = f"{number / 1_000:.2f} K"
    else:
        formatted_amt = f"{number:.2f}"

    return formatted_amt

# function to set start and end date
def get_start_end_date():
  start_date = (datetime.date.today() + datetime.timedelta(days=-365)).strftime('%Y-%m-%d')
  end_date = (datetime.date.today() + datetime.timedelta(days=1)).strftime('%Y-%m-%d')
  return start_date, end_date

# function to fetch my portfolio csv
def get_mypfs_df():
  mypfs_df = pd.read_csv('https://raw.githubusercontent.com/ankit-rathi/Tradevesting_v1/main/data/myPortfolioStocks.csv')
  return mypfs_df

# function to fetch my prospects csv
def get_mypps_df():
  mypps_df = pd.read_csv('https://raw.githubusercontent.com/ankit-rathi/Tradevesting_v1/main/data/myProspectsScrips.csv')
  return mypps_df

# function to fetch screener data
def get_myscreen_df():
  myscreen_df = pd.read_csv('https://raw.githubusercontent.com/ankit-rathi/Tradevesting_v1/main/data/myScreenerDB.csv')
  return myscreen_df

# function to fetch momentum data
def get_myinvmt_df():
  myinvmt_df = pd.read_csv('https://raw.githubusercontent.com/ankit-rathi/Tradevesting_v1/main/data/myInvestments.csv')
  return myinvmt_df

# function to get the stock ids
def get_stock_ids(df_pf):
  stock_n100 = df_pf['Symbol'].unique()

  exclude = ['CADILAHC','MMTC', 'MASFIN']

  stock_ids = df_pf[~df_pf['Symbol'].isin(exclude) ]['Symbol'].unique()

  #mypf = mypf[mypf.Forecast.notnull()]
  #stock_ids = mypf['Symbol'].unique()

  #stock_ids.sort()
  return stock_ids

# get features from screener data
def get_screener_features():
  myscreen_df = get_myscreen_df()
  cols = ['Symbol', 'EPS', 'MedPE', 'ROCE%', 'ROE%', 'CapType']
  return myscreen_df[cols]

# get relative strength
def get_relative_strength(stock_list):

    # Dictionary to store stock tickers and their corresponding percentage price change
    stock_changes = {}

    # Loop through each stock and fetch its price data
    for stock in stock_list:
        try:
            # Download the stock data for the given date range
            stock_data = yfin.Ticker(stock + '.NS').history(period='1mo', interval='1d')[map(str.title, ['open', 'close', 'low', 'high', 'volume'])]

            # Calculate the percentage change for the stock
            if len(stock_data) > 0:
                start_price = stock_data['Close'].iloc[0]
                end_price = stock_data['Close'].iloc[-1]
                percent_change = round(((end_price - start_price) / start_price) * 100, 2)
                stock_changes[stock] = percent_change
            else:
                stock_changes[stock] = np.nan  # If no data is available, set to NaN

        except Exception as e:
            print(f"Error fetching data for {stock}: {e}")
            stock_changes[stock] = np.nan

    # Create a DataFrame with stock tickers and their percentage changes
    df = pd.DataFrame(list(stock_changes.items()), columns=['Symbol', 'Percent_Change'])

    # Drop any stocks with missing data (NaN values)
    df = df.dropna()

    # Calculate the percentile rank based on percentage change
    df['RSP'] = round(df['Percent_Change'].rank(pct=True) * 100, 2)
    cols = ['Symbol', 'RSP']
    df = df[cols]
    # Sort by percentile rank (optional)
    df = df.sort_values(by='RSP', ascending=False).reset_index(drop=True)

    return df

In [6]:
# function to get stock technicals
def stock_prec_dev(stock_symbol):
    #stock_symbol = 'ULTRACEMCO.NS'
    short_window = 20
    mid_window = 50
    long_window = 200
    moving_avg = 'SMA'

    start = datetime.datetime(*map(int, start_date.split('-')))
    end = datetime.datetime(*map(int, end_date.split('-')))

    stock_df = yfin.Ticker(stock_symbol + '.NS').history(period='max', interval='1d')[map(str.title, ['open', 'close', 'low', 'high', 'volume'])]

    stock_df['Max'] = round(max(stock_df['Close']),2)
    stock_df = stock_df[(stock_df.index <= end_date) & (stock_df.index >= start_date)]
    stock_df['200_SMA'] = round(stock_df['Close'].rolling(window = 200, min_periods = 1).mean(),0)
    stock_df['Dev%_200'] = round((stock_df['Close'] - stock_df['200_SMA'])*100/stock_df['200_SMA'],2)
    stock_df.dropna(axis = 0, inplace = True) # remove any null rows

    stock_df['20_SMA'] = stock_df['Close'].rolling(window=20).mean()
    stock_df['50_SMA'] = stock_df['Close'].rolling(window=50).mean()
    stock_df['Symbol'] = stock_symbol

    stock_df['Close'] = round(stock_df['Close'],2)
    stock_df['Min'] = round(min(stock_df['Close']),2)
    stock_df['RSI_14'] = ta.momentum.RSIIndicator(close=stock_df['Close'], window=14).rsi()
    stock_df['RSI_14'] = round(stock_df['RSI_14'],0)
    stock_df['Prev_Close'] = stock_df['Close'].shift(1)
    stock_df.drop(['Open', 'Low', 'High', 'Volume'], axis=1, inplace=True)
    stock_df = stock_df.tail(1)

    max_SMA = max(stock_df['20_SMA'].item(), stock_df['50_SMA'].item(), stock_df['200_SMA'].item())
    min_SMA = min(stock_df['20_SMA'].item(), stock_df['50_SMA'].item(), stock_df['200_SMA'].item())
    ABS_Spread = max_SMA - min_SMA
    stock_df['Spread%'] = round((ABS_Spread / stock_df['200_SMA'].item()) * 100,2)

    return stock_df

# function to compute stock attributes
def get_common_features(stock_ids, df_mypf):

  df_prec_dev = pd.DataFrame()
  df_tmp = get_screener_features()
  df_rs = get_relative_strength(stock_ids)

  for stock_id in stock_ids:
      tmp = stock_prec_dev(stock_id)
      tmp = tmp.reset_index()
      df_prec_dev = pd.concat([df_prec_dev, tmp], ignore_index = True)
  df_prec_dev = pd.merge(df_prec_dev, df_mypf, on= 'Symbol')
  df_prec_dev = pd.merge(df_prec_dev, df_tmp, on= 'Symbol', how='left')
  df_prec_dev = pd.merge(df_prec_dev, df_rs, on= 'Symbol', how='left')
  #print(df_prec_dev.columns)
  df_prec_dev['Curr_PE'] = round(df_prec_dev['Close']/df_prec_dev['EPS'],1)
  df_prec_dev['Dev%_PE'] = round((df_prec_dev['Curr_PE'] - df_prec_dev['MedPE'])*100/df_prec_dev['MedPE'],2)
  df_prec_dev['Conviction'] = df_prec_dev['Conviction'] + '-' + df_prec_dev['CapType']
  return df_prec_dev

# function to arrange stock features
def arrange_features(df_stocks, common_cols, diff_cols):
  df_stocks_common = df_stocks[common_cols].drop_duplicates()
  df_stocks_diff = df_stocks[diff_cols]
  df_stocks_diff['Investment'] = df_stocks_diff['AvgCost'] * df_stocks_diff['Shares']
  df_stocks_diff = df_stocks_diff.groupby(['Symbol'])[['Shares', 'Investment']].aggregate(['sum']).reset_index()
  df_stocks_diff.columns = ['Symbol', 'Shares', 'Investment']
  df_stocks_diff['AvgCost'] = round(df_stocks_diff['Investment']/df_stocks_diff['Shares'],2)
  df_stocks = pd.merge(df_stocks_diff, df_stocks_common, on='Symbol')
  return df_stocks

# plot fact distribution across dimension
def plot_pie_chart(df, dimension, fact):
  # grouping the data by category and calculating the sum of fact for each type
  grouped_data = df.groupby(dimension)[fact].sum()

  # sorting the grouped data in descending order
  grouped_data = grouped_data.sort_values(ascending=False)

  # creating a pie chart
  grouped_data.plot.pie(autopct='%1.1f%%', startangle=90, figsize=(6, 6))

  # adding a title and displaying the plot
  plt.title(f'{dimension} {fact} Distribution')
  plt.ylabel('')  # To hide the y-label
  plt.show()

In [7]:
# function to get portfolio features

def get_portfolio_features(df_common_features):

  print_date_time()
  print('-------------------')

  #df_common_features["Target"] = df_common_features["Target"].fillna(df_common_features["Max"])
  df_common_features['NTT'] = np.where(df_common_features['Strategy']== 'NTT', df_common_features["Target"], df_common_features['Max'])
  df_common_features['LTT'] = np.where(df_common_features['Strategy']== 'BTT', df_common_features["Target"], df_common_features['Max'])
  df_common_features['BOL'] = df_common_features['Min']

  tmp_df = df_common_features[df_common_features['Symbol'].isin(mypf_df[mypf_df['InPortfolio'] != 'NA'].Symbol.values)]
  print('qualified stocks: '+str(len(tmp_df['Symbol'].unique())))
  tmp_df1 = tmp_df[tmp_df['LatestQtr'] == 1]
  print('with latest results: '+str(len(tmp_df1['Symbol'].unique())))
  tmp_df1 = tmp_df1[tmp_df1['StarStock'] == 1]
  print('still star stocks: '+str(len(tmp_df1['Symbol'].unique())))
  tmp_df['Investment'] = tmp_df['AvgCost'] * tmp_df['Shares']
  tmp_df['Current'] = round(tmp_df['Close'] * tmp_df['Shares'],0)
  tmp_df['Previous'] = tmp_df['Prev_Close'] * tmp_df['Shares']
  tmp_df['EstimatedST'] = tmp_df['NTT'] * tmp_df['Shares']
  tmp_df['EstimatedLT'] = tmp_df['LTT'] * tmp_df['Shares']
  tmp_df['Current P/L'] = round((tmp_df['Current'] - tmp_df['Investment']),0)
  tmp_df['Today P/L%'] = round((tmp_df['Current'] - tmp_df['Previous'])*100/tmp_df['Previous'],2)
  tmp_df['Current P/L%'] = round((tmp_df['Current'] - tmp_df['Investment'])*100/tmp_df['Investment'],2)
  tmp_df['EstimatedST P/L%'] = round((tmp_df['EstimatedST'] - tmp_df['Investment'])*100/tmp_df['Investment'],2)
  tmp_df['EstimatedLT P/L%'] = round((tmp_df['EstimatedLT'] - tmp_df['Investment'])*100/tmp_df['Investment'],2)
  tmp_df['NTT%'] = round((tmp_df['NTT'] - tmp_df['Close'])*100/tmp_df['Close'],2)
  tmp_df['LTT%'] = round((tmp_df['LTT'] - tmp_df['Close'])*100/tmp_df['Close'],2)
  tmp_df['Gained%'] = round((tmp_df['Close'] - tmp_df['BOL'])*100/tmp_df['BOL'],2)
  investment = round(sum(tmp_df['AvgCost']*tmp_df['Shares']),0)
  current = round(sum(tmp_df['Close']*tmp_df['Shares']),0)
  tmp_df['InitAlloc%'] = round(tmp_df['Investment']*100/investment,2)
  tmp_df['CurrAlloc%'] = round(tmp_df['Current']*100/current,2)
  tmp_df['FTT'] = tmp_df['LTT']
  tmp_df.loc[tmp_df['Strategy'] == 'NTT', 'FTT'] = tmp_df['NTT']
  tmp_df['FTT%'] = tmp_df['LTT%']
  tmp_df.loc[tmp_df['Strategy'] == 'NTT', 'FTT%'] = tmp_df['NTT%']
  tmp_df['FTT Amt'] = round(tmp_df['FTT%'] * tmp_df['Current']/100,0)
  tmp_df['OTT%'] = round((tmp_df['FTT'] - tmp_df['AvgCost'])*100/tmp_df['AvgCost'],2)
  tmp_df['RRR Ind'] = round(tmp_df['Current P/L']/tmp_df['FTT Amt'],2)
  tmp_df['Risk Ind'] = round(tmp_df['Current P/L%']*tmp_df['CurrAlloc%'],0)

  return tmp_df

# function to print portfolio features
def print_portfolio_stats(df_portfolio_features, myinvmt_df):
  from pyxirr import xirr

  total_booked_amt, reserve_amt, cy_booked_amt, py_booked_amt = get_amt()

  dates = myinvmt_df['Date'].values
  dates = np.append(dates, datetime.date.today().strftime('%d-%b-%y'))
  investment = myinvmt_df['Investment'].values
  dates= pd.to_datetime(dates)

  current = round(sum(df_portfolio_features['Close']*df_portfolio_features['Shares']),0) + reserve_amt
  investment_xirr = np.append(investment, current)
  cagr = round(xirr(pd.DataFrame({"dates": dates, "amounts": investment_xirr}))*100,2)

  investment = -sum(investment)
  invested = round(sum(df_portfolio_features['AvgCost']*df_portfolio_features['Shares']),0) + reserve_amt
  previous = round(sum(df_portfolio_features['Prev_Close']*df_portfolio_features['Shares']),0) + reserve_amt
  cy_invested = investment + py_booked_amt

  today_pnl_amount = current-previous
  today_pnl_percentage = round((current-previous)*100/previous,2)

  curr_pnl_amount = current-invested
  curr_pnl_percentage = round((curr_pnl_amount)*100/(cy_invested),2)

  cy_pnl_amount = cy_booked_amt + curr_pnl_amount
  cy_pnl_percentage = round((cy_pnl_amount)*100/cy_invested,2)

  overall_pnl_amount = total_booked_amt + curr_pnl_amount
  overall_pnl_percentage = round((overall_pnl_amount)*100/investment,2)

  estimate_st = round(sum(df_portfolio_features['FTT']*df_portfolio_features['Shares']),0)  + reserve_amt
  est_st_pnl_amount = estimate_st-current
  est_st_pnl_percentage = round((est_st_pnl_amount)*100/current,2)

  estimate_lt = round(sum(df_portfolio_features['LTT']*df_portfolio_features['Shares']),0)  + reserve_amt
  est_lt_pnl_amount = estimate_lt-current
  est_lt_pnl_percentage = round((est_lt_pnl_amount)*100/current,2)

  total_profit = round(sum(df_portfolio_features[df_portfolio_features['Current P/L%'] > 0]['Current']) - sum(df_portfolio_features[df_portfolio_features['Current P/L%'] > 0]['Investment']),0)
  total_loss = round(sum(df_portfolio_features[df_portfolio_features['Current P/L%'] < 0]['Current']) - sum(df_portfolio_features[df_portfolio_features['Current P/L%'] < 0]['Investment']),0)

  cy_booked_percentage = round((cy_booked_amt)*100/current,2)
  py_booked_percentage = round((py_booked_amt)*100/investment,2)
  total_booked_percentage = round((total_booked_amt)*100/investment,2)

  print('-------------------')
  print('Initial Investment: ', format_amt(investment))
  print('CY Investment: ', format_amt(cy_invested))
  print('Reserve: ', format_amt(reserve_amt))
  print('Current: ',  format_amt(current))
  print('-------------------')
  print('Today PnL: '+ '{} ({}%)'.format(format_amt(today_pnl_amount), today_pnl_percentage))
  print('Current PnL: '+ '{} ({}%)'.format(format_amt(curr_pnl_amount), curr_pnl_percentage))
  print('CY Booked + Current PnL: '+ '{} ({}%)'.format(format_amt(cy_pnl_amount), cy_pnl_percentage))
  print('-------------------')
  print('Total profit: ', format_amt(total_profit))
  print('Total loss: ', format_amt(total_loss))
  print('-------------------')
  print('Total Booked + Current PnL: '+ '{} ({}%)'.format(format_amt(overall_pnl_amount), overall_pnl_percentage))
  print('Total Booked PnL: '+ '{} ({}%)'.format(format_amt(total_booked_amt), total_booked_percentage))
  print('Curr Year Booked PnL: '+ '{} ({}%)'.format(format_amt(cy_booked_amt), cy_booked_percentage))
  print('Prev Year Booked PnL: '+ '{} ({}%)'.format(format_amt(py_booked_amt), py_booked_percentage))
  print('===================')
  print('Est FTT: ',  format_amt(estimate_st))
  print('Est FTT PnL: '+ '{} ({}%)'.format(format_amt(est_st_pnl_amount), est_st_pnl_percentage))

  print('===================')
  print('Deployed: ', format_amt(investment))

  print('Current: ', format_amt(current))

  print('CAGR/XIRR %: '+'{}%'.format(cagr))

In [8]:
# get start and end date
start_date, end_date = get_start_end_date()

# get portfolio and prospects data
mypfs_df = get_mypfs_df()
mypps_df = get_mypps_df()
myinvmt_df = get_myinvmt_df()

# merge above datasets
mypf_df = pd.merge(mypfs_df, mypps_df, on="Symbol")

# seggregate dm and sv portfolio
dm_pf = mypf_df[mypf_df['InPortfolio'] == 'DM']
sv_pf = mypf_df[mypf_df['InPortfolio'] == 'SV']

# build portfolio stock dataframe
dm_stocks = get_stock_ids(dm_pf)
sv_stocks = get_stock_ids(sv_pf)
df_stocks = pd.concat([dm_pf,sv_pf], ignore_index = True)

# arrange common and diff stock features
common_cols = ['Symbol', 'Target', 'Criteria', 'Strategy', 'CumlRnk', 'LatestQtr', 'StarStock', 'Conviction', 'Category', 'InFolio', 'XIRR', 'MBQ']
diff_cols = ['Symbol', 'AvgCost', 'Shares']
df_stocks = arrange_features(df_stocks, common_cols, diff_cols)

# get common features
stock_ids = df_stocks['Symbol'].values
df_common_features = get_common_features(stock_ids, df_stocks)

df_common_features.reset_index(drop=True, inplace=True)
df_common_features.drop(['Date'], axis=1, inplace=True)
# get and print portfolio features
df_portfolio_features = get_portfolio_features(df_common_features)

print_portfolio_stats(df_portfolio_features, myinvmt_df)

df = df_portfolio_features
#plot_pie_chart(df, 'CapType', 'Current')
list_ox40n = list(df[df['MBQ'].str.contains('OX40N', na=False)]['Symbol'].values)

Run date time (IST): 2026-06-18 12:21:32
-------------------
qualified stocks: 92
with latest results: 31
still star stocks: 20
-------------------
Initial Investment:  1.40 C
CY Investment:  1.82 C
Reserve:  1.49 K
Current:  1.52 C
-------------------
Today PnL: 61.72 K (0.41%)
Current PnL: -30.82 L (-16.9%)
CY Booked + Current PnL: -28.74 L (-15.76%)
-------------------
Total profit:  3.69 L
Total loss:  -34.52 L
-------------------
Total Booked + Current PnL: 14.13 L (10.13%)
Total Booked PnL: 44.95 L (32.22%)
Curr Year Booked PnL: 2.08 L (1.37%)
Prev Year Booked PnL: 42.87 L (30.73%)
===================
Est FTT:  2.55 C
Est FTT PnL: 1.03 C (67.49%)
===================
Deployed:  1.40 C
Current:  1.52 C
CAGR/XIRR %: 4.13%

In [9]:
# top 5 near their targets
cols = ['Symbol', 'Today P/L%', 'Current P/L%', 'FTT%', 'OTT%', 'FTT Amt', 'Current P/L', 'Current', 'FTT', 'Dev%_PE', 'RSI_14','Conviction', 'Spread%',  'CumlRnk', 'RRR Ind', 'CurrAlloc%', 'Gained%', 'Criteria', 'Strategy', 'Category']
df_tmp = df_portfolio_features[~df_portfolio_features['Symbol'].isin(['ENRIN','BLUSPRING','DIGITIDE'])]
df_tmp = df_tmp.sort_values(by = 'FTT Amt', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
59,PIDILITIND,-0.23,11.59,6.08,18.37,9574.0,16350.0,157460.0,1670.26,-21.83,73.0,X-LC,3.76,5.0,1.71,1.03,23.63,X40,ATH,CHEMICALS
51,KOTAKBANK,-0.54,7.49,12.66,21.11,18845.0,10378.0,148851.0,453.24,-7.67,63.0,X-LC,5.63,12.0,0.55,0.98,13.84,X40,ATH,BANKS
55,MASFIN,1.30,-3.14,25.51,21.57,24210.0,-3075.0,94905.0,397.04,-16.44,55.0,H-SC,3.42,167.0,-0.13,0.62,13.12,XR,ATH,FINANCE
72,SIS,-0.09,-2.16,23.94,21.26,26006.0,-2402.0,108630.0,528.00,2591.71,62.0,H-SC,22.77,168.0,-0.09,0.71,61.52,OX40N,NTT,MISC
49,JSWINFRA,2.41,4.04,11.91,16.43,27480.0,8954.0,230728.0,342.00,-10.89,69.0,X-MC,1.82,61.0,0.33,1.51,30.82,X40N,NTT,REALTY

In [10]:
# top 5 today
df_tmp = df_portfolio_features.sort_values(by = 'Today P/L%', ascending=False)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
12,BOSCH-HCIL,7.24,-39.90,66.36,-0.01,50974.0,-50990.0,76815.0,2282.0,15617.39,51.0,M-SC,8.25,231.0,-1.00,0.50,30.75,OX40N,BTT,AC
74,STARHEALTH,6.87,10.37,33.43,47.26,103723.0,29147.0,310270.0,761.0,74.08,75.0,H-SC,10.43,173.0,0.28,2.04,36.22,XY24,NTT,INSURANCE
21,DEN,6.80,-41.43,142.56,42.07,70527.0,-34992.0,49472.0,75.0,76.17,71.0,M-SC,8.00,235.0,-0.50,0.32,34.55,AR,NTT,ENTERTAINMENT
61,RAJESHEXPO,5.00,-82.06,457.77,0.07,112662.0,-112566.0,24611.0,518.0,801.52,43.0,L-SC,35.40,268.0,-1.00,0.16,21.54,OX40N,NTT,JEWELLERY
84,UNITDSPR,3.59,-0.46,21.33,20.77,49712.0,-1084.0,233060.0,1644.0,-11.71,68.0,X-MC,5.14,64.0,-0.02,1.53,11.17,X40N,NTT,BREWERIES

In [11]:
# bottom 5 today
df_tmp = df_portfolio_features.sort_values(by = 'Today P/L%', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
68,SATIN,-2.88,26.79,19.75,51.83,69186.0,74024.0,350308.0,274.00,13.01,55.0,H-SC,40.16,159.0,1.07,2.30,70.65,XY24,NTT,FINANCE
45,INFY,-2.22,-22.94,74.20,34.24,178908.0,-71772.0,241116.0,1972.00,-39.40,45.0,X-LC,16.53,3.0,-0.40,1.58,5.62,X40,NTT,IT
24,EASEMYTRIP,-1.69,-55.02,223.93,45.70,178087.0,-97287.0,79528.0,26.40,-17.34,56.0,M-SC,4.11,204.0,-0.55,0.52,39.32,XY24,NTT,TRAVEL
83,TTKPRESTIG,-1.51,-30.27,43.55,0.09,30602.0,-30509.0,70268.0,770.00,63.07,52.0,M-SC,10.47,250.0,-1.00,0.46,25.12,OX40N,NTT,DURABLES
79,TCS,-1.49,-35.71,94.25,24.88,280701.0,-165447.0,297826.0,4253.91,-45.59,43.0,X-LC,18.99,2.0,-0.59,1.96,2.54,X40,ATH,IT

In [12]:
# top 5 to exit based on CumlRnk
df_tmp = df_portfolio_features[~df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])]
df_tmp = df_tmp[(df_tmp['Current P/L%'] > -1) & (df_tmp['Current P/L%'] < 1)].sort_values(by = 'CumlRnk', ascending=False)
df_tmp[cols].head()

Empty DataFrame
Columns: [Symbol, Today P/L%, Current P/L%, FTT%, OTT%, FTT Amt, Current P/L, Current, FTT, Dev%_PE, RSI_14, Conviction, Spread%, CumlRnk, RRR Ind, CurrAlloc%, Gained%, Criteria, Strategy, Category]
Index: []

In [13]:
# OX40N stocks to exit
df_tmp = df_portfolio_features[(df_portfolio_features['Symbol'].isin(list_ox40n))].sort_values(by = 'Current P/L%', ascending=False)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
25,FINCABLES,2.81,45.84,42.56,107.91,91644.0,67686.0,215330.0,1641.55,31.41,63.0,M-SC,24.02,220.0,0.74,1.41,62.00,OX40N,ATH,CABLES
72,SIS,-0.09,-2.16,23.94,21.26,26006.0,-2402.0,108630.0,528.00,2591.71,62.0,H-SC,22.77,168.0,-0.09,0.71,61.52,OX40N,NTT,MISC
16,CERA,0.45,-19.14,53.22,23.89,75696.0,-33671.0,142232.0,9475.00,-21.96,67.0,H-SC,5.44,153.0,-0.44,0.93,36.68,OX40N,NTT,CERAMICS
43,INDIGOPNTS,0.89,-26.79,36.63,0.02,46809.0,-46771.0,127788.0,1408.00,94.75,64.0,M-SC,9.78,222.0,-1.00,0.84,44.98,OX40N,NTT,PAINTS
50,KANSAINER,-0.93,-30.20,62.56,13.47,117760.0,-81432.0,188235.0,340.00,-39.99,43.0,H-SC,5.92,162.0,-0.69,1.24,31.48,XY24,NTT,PAINTS

In [14]:
# top 5 to book for rotation
df_tmp = df_portfolio_features[(df_portfolio_features['Current P/L%'] > 20) ].sort_values(by = 'CumlRnk', ascending=False)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
25,FINCABLES,2.81,45.84,42.56,107.91,91644.0,67686.0,215330.0,1641.55,31.41,63.0,M-SC,24.02,220.0,0.74,1.41,62.00,OX40N,ATH,CABLES
68,SATIN,-2.88,26.79,19.75,51.83,69186.0,74024.0,350308.0,274.00,13.01,55.0,H-SC,40.16,159.0,1.07,2.30,70.65,XY24,NTT,FINANCE

In [15]:
# top 5 to monitor for exit
df_tmp = df_portfolio_features[~df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])]
df_tmp = df_tmp[(df_tmp['Current P/L%'] > 0) ].sort_values(by = 'Dev%_PE', ascending=False)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
9,BANDHANBNK,0.38,3.22,86.42,92.42,248478.0,8965.0,287524.0,400.00,146.41,62.0,H-SC,23.01,174.0,0.04,1.89,58.39,XY24,NTT,BANKS
74,STARHEALTH,6.87,10.37,33.43,47.26,103723.0,29147.0,310270.0,761.00,74.08,75.0,H-SC,10.43,173.0,0.28,2.04,36.22,XY24,NTT,INSURANCE
25,FINCABLES,2.81,45.84,42.56,107.91,91644.0,67686.0,215330.0,1641.55,31.41,63.0,M-SC,24.02,220.0,0.74,1.41,62.00,OX40N,ATH,CABLES
68,SATIN,-2.88,26.79,19.75,51.83,69186.0,74024.0,350308.0,274.00,13.01,55.0,H-SC,40.16,159.0,1.07,2.30,70.65,XY24,NTT,FINANCE
91,ZYDUSLIFE,0.65,12.65,20.39,35.63,48140.0,26520.0,236094.0,1286.17,-1.80,55.0,H-MC,13.51,120.0,0.55,1.55,24.13,AR,ATH,PHARMA

In [16]:
# top 5 to book for rotation from weak conviction
df_tmp = df_portfolio_features[~df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])]
df_tmp = df_tmp[~df_tmp['Criteria'].isin(['XY25','XY24','X40', 'X40N'])].sort_values(by = 'RRR Ind', ascending=False)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
25,FINCABLES,2.81,45.84,42.56,107.91,91644.0,67686.0,215330.0,1641.55,31.41,63.0,M-SC,24.02,220.0,0.74,1.41,62.00,OX40N,ATH,CABLES
91,ZYDUSLIFE,0.65,12.65,20.39,35.63,48140.0,26520.0,236094.0,1286.17,-1.80,55.0,H-MC,13.51,120.0,0.55,1.55,24.13,AR,ATH,PHARMA
73,SONACOMS,0.13,4.15,33.55,39.09,35348.0,4200.0,105359.0,804.02,-17.50,55.0,M-MC,18.50,193.0,0.12,0.69,49.04,AR,ATH,AUTO
42,INDIAMART,0.48,-9.76,129.08,106.72,143666.0,-12036.0,111300.0,4810.62,-59.38,64.0,H-SC,9.38,140.0,-0.08,0.73,7.75,AR,ATH,MISC
72,SIS,-0.09,-2.16,23.94,21.26,26006.0,-2402.0,108630.0,528.00,2591.71,62.0,H-SC,22.77,168.0,-0.09,0.71,61.52,OX40N,NTT,MISC

In [17]:
# top 5 to accumulate based on lowest RSI_14
df_tmp = df_portfolio_features[df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])].sort_values(by = 'RSI_14', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
58,PGHH,-0.06,-32.63,95.95,32.01,138022.0,-69672.0,143848.0,17616.87,-54.37,33.0,X-MC,19.69,57.0,-0.50,0.94,0.00,X40,ATH,FMCG
81,TMPV,0.14,-17.72,66.00,36.58,193231.0,-63067.0,292774.0,600.00,-82.53,42.0,X-LC,11.86,4.0,-0.33,1.92,22.03,XY24,NTT,AUTO
79,TCS,-1.49,-35.71,94.25,24.88,280701.0,-165447.0,297826.0,4253.91,-45.59,43.0,X-LC,18.99,2.0,-0.59,1.96,2.54,X40,ATH,IT
1,ABBOTINDIA,0.56,-12.44,34.85,18.07,54575.0,-22255.0,156600.0,35195.00,-25.47,44.0,X-MC,5.81,58.0,-0.41,1.03,3.65,X40,ATH,PHARMA
45,INFY,-2.22,-22.94,74.20,34.24,178908.0,-71772.0,241116.0,1972.00,-39.40,45.0,X-LC,16.53,3.0,-0.40,1.58,5.62,X40,NTT,IT

In [18]:
# top 5 to accumulate based on Spread and CumlRnk
df_tmp = df_portfolio_features[df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])]
df_tmp = df_tmp[(df_tmp['CumlRnk'] < 100)].sort_values(by = 'Spread%', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
49,JSWINFRA,2.41,4.04,11.91,16.43,27480.0,8954.0,230728.0,342.00,-10.89,69.0,X-MC,1.82,61.0,0.33,1.51,30.82,X40N,NTT,REALTY
11,BERGEPAINT,-0.89,-6.54,34.08,25.32,82097.0,-16853.0,240896.0,680.00,-11.63,52.0,X-MC,3.00,68.0,-0.21,1.58,25.38,XY24,NTT,PAINTS
57,PAGEIND,0.89,3.42,29.17,33.59,80961.0,9171.0,277550.0,51217.29,-25.89,63.0,X-MC,3.31,55.0,0.11,1.82,31.81,X40,ATH,APPARELS
19,COLPAL,-0.22,-22.93,81.47,39.86,165368.0,-60385.0,202980.0,3683.41,-6.75,46.0,X-MC,3.40,62.0,-0.37,1.33,14.82,XY25,ATH,FMCG
15,CAMS,1.73,7.61,15.68,24.48,42495.0,19156.0,271012.0,950.00,3.22,65.0,X-SC,3.56,89.0,0.45,1.78,31.94,X40N,NTT,MISC

In [19]:
# top 5 to accumulate based on lowest Gained%
df_tmp = df_portfolio_features[df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])].sort_values(by = 'Gained%', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
58,PGHH,-0.06,-32.63,95.95,32.01,138022.0,-69672.0,143848.0,17616.87,-54.37,33.0,X-MC,19.69,57.0,-0.50,0.94,0.00,X40,ATH,FMCG
79,TCS,-1.49,-35.71,94.25,24.88,280701.0,-165447.0,297826.0,4253.91,-45.59,43.0,X-LC,18.99,2.0,-0.59,1.96,2.54,X40,ATH,IT
28,GODREJCP,-0.58,-9.24,44.86,31.47,60505.0,-13739.0,134875.0,1469.04,-4.49,46.0,X-LC,9.46,32.0,-0.23,0.89,3.49,X40N,ATH,FMCG
1,ABBOTINDIA,0.56,-12.44,34.85,18.07,54575.0,-22255.0,156600.0,35195.00,-25.47,44.0,X-MC,5.81,58.0,-0.41,1.03,3.65,X40,ATH,PHARMA
33,HCLTECH,-0.74,-24.84,61.66,21.51,112121.0,-60087.0,181837.0,1872.35,-21.01,47.0,X-LC,18.37,8.0,-0.54,1.19,4.38,X40,ATH,IT

In [20]:
# top 5 to accumulate based on lowest CurrAlloc%
df_tmp = df_portfolio_features[df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])].sort_values(by = 'CurrAlloc%', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
10,BATAINDIA,0.04,-56.22,208.80,35.20,117630.0,-72334.0,56336.0,2096.00,-26.21,48.0,X-SC,25.03,91.0,-0.61,0.37,11.73,X40,NTT,FOOTWEAR
64,RELAXO,-0.70,-53.16,225.13,52.31,153088.0,-77160.0,68000.0,1176.00,-50.15,67.0,X-SC,16.95,92.0,-0.50,0.45,52.04,X40N,NTT,FOOTWEAR
60,QUESS,0.29,2.53,69.60,73.90,76212.0,2707.0,109500.0,424.00,-44.90,78.0,X-SC,7.02,80.0,0.04,0.72,49.27,XY24,NTT,MISC
28,GODREJCP,-0.58,-9.24,44.86,31.47,60505.0,-13739.0,134875.0,1469.04,-4.49,46.0,X-LC,9.46,32.0,-0.23,0.89,3.49,X40N,ATH,FMCG
53,M&M,0.47,2.14,20.80,23.38,29462.0,2961.0,141642.0,3802.40,-13.39,57.0,X-LC,10.43,25.0,0.10,0.93,7.39,X40N,ATH,AUTO

In [21]:
# top 5 to accumulate based on CumlRnk
df_tmp = df_portfolio_features.sort_values(by = 'CumlRnk', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
47,ITC,-0.41,-23.73,56.10,19.06,145544.0,-80729.0,259437.0,452.00,-58.35,51.0,X-LC,15.30,1.0,-0.55,1.70,4.53,X40,NTT,FMCG
79,TCS,-1.49,-35.71,94.25,24.88,280701.0,-165447.0,297826.0,4253.91,-45.59,43.0,X-LC,18.99,2.0,-0.59,1.96,2.54,X40,ATH,IT
45,INFY,-2.22,-22.94,74.20,34.24,178908.0,-71772.0,241116.0,1972.00,-39.40,45.0,X-LC,16.53,3.0,-0.40,1.58,5.62,X40,NTT,IT
81,TMPV,0.14,-17.72,66.00,36.58,193231.0,-63067.0,292774.0,600.00,-82.53,42.0,X-LC,11.86,4.0,-0.33,1.92,22.03,XY24,NTT,AUTO
59,PIDILITIND,-0.23,11.59,6.08,18.37,9574.0,16350.0,157460.0,1670.26,-21.83,73.0,X-LC,3.76,5.0,1.71,1.03,23.63,X40,ATH,CHEMICALS

In [22]:
# top 5 for average up
df_tmp = df_portfolio_features[(df_portfolio_features['Dev%_200'] > 5)].sort_values(by = 'CurrAlloc%', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
44,INDUSINDBK,-0.30,-31.09,92.84,32.89,49395.0,-24002.0,53204.0,1800.00,-350.70,57.0,L-MC,7.56,258.0,-0.49,0.35,30.96,XR,NTT,BANKS
3,ALKYLAMINE,-0.51,-23.04,151.58,93.63,117785.0,-23258.0,77705.0,4546.37,-17.57,57.0,H-SC,7.07,142.0,-0.20,0.51,46.73,SR,ATH,CHEMICALS
73,SONACOMS,0.13,4.15,33.55,39.09,35348.0,4200.0,105359.0,804.02,-17.50,55.0,M-MC,18.50,193.0,0.12,0.69,49.04,AR,ATH,AUTO
86,VALIANTORG,0.32,-35.18,168.68,74.15,178878.0,-57559.0,106046.0,838.00,-290.89,61.0,H-SC,3.13,145.0,-0.32,0.70,57.81,XR,NTT,CHEMICALS
72,SIS,-0.09,-2.16,23.94,21.26,26006.0,-2402.0,108630.0,528.00,2591.71,62.0,H-SC,22.77,168.0,-0.09,0.71,61.52,OX40N,NTT,MISC

In [23]:
# top 5 RSP
df_tmp = df_portfolio_features.sort_values(by = 'RSP', ascending=False)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
18,COFFEEDAY,0.85,-41.75,132.22,35.27,87456.0,-47405.0,66144.0,80.00,-55.73,57.0,L-SC,14.34,266.0,-0.54,0.43,63.12,XR,NTT,HOTELS
37,HONAUT,0.66,-5.05,59.36,51.31,108688.0,-9738.0,183100.0,58357.33,-21.04,65.0,X-SC,8.95,90.0,-0.09,1.20,39.11,X40N,ATH,ELECTRICAL
64,RELAXO,-0.70,-53.16,225.13,52.31,153088.0,-77160.0,68000.0,1176.00,-50.15,67.0,X-SC,16.95,92.0,-0.50,0.45,52.04,X40N,NTT,FOOTWEAR
80,TITAGARH,2.66,-11.04,63.83,45.74,137513.0,-26740.0,215437.0,1548.00,18.59,72.0,H-SC,6.08,175.0,-0.19,1.41,64.37,XY24,NTT,ENGINEERING
60,QUESS,0.29,2.53,69.60,73.90,76212.0,2707.0,109500.0,424.00,-44.90,78.0,X-SC,7.02,80.0,0.04,0.72,49.27,XY24,NTT,MISC

In [24]:
# Top N allocation
df_tmp = df_portfolio_features.sort_values(by = 'CurrAlloc%', ascending=False)
top_n_values = [10, 25, 50]

sum_df = pd.DataFrame({
    'Top_N': top_n_values,
    'Sum_Alloc%': [df_tmp['CurrAlloc%'].head(n).sum() for n in top_n_values]
})

sum_df

   Top_N  Sum_Alloc%
0     10       19.52
1     25       42.78
2     50       72.75

In [25]:
# market-cap-wise allocation
df_tmp = df_portfolio_features[cols]
df_tmp.groupby(df_tmp['Conviction'].str[-2:])['CurrAlloc%'].sum().sort_values(ascending=False)

Conviction
SC    43.44
LC    30.93
MC    25.59
Name: CurrAlloc%, dtype: float64

In [26]:
# criteria-wise allocation
df_portfolio_features.groupby('Criteria')['CurrAlloc%'].sum().sort_values(ascending=False)

Criteria
XY24     27.67
X40      24.77
X40N     17.39
XR        8.98
OX40N     7.00
AR        6.76
XY25      6.52
SR        0.87
Name: CurrAlloc%, dtype: float64

In [27]:
# conviction-wise allocation
df_portfolio_features.groupby('Conviction')['CurrAlloc%'].sum().sort_values(ascending=False)

Conviction
X-LC    28.88
H-SC    22.85
X-MC    20.59
M-SC    10.05
X-SC     9.95
H-MC     2.67
M-MC     1.98
H-LC     1.22
M-LC     0.83
L-SC     0.59
L-MC     0.35
Name: CurrAlloc%, dtype: float64

In [28]:
# sector-wise stats
df_tmp = df_portfolio_features.groupby('Category')[['CurrAlloc%', 'Current', 'Current P/L', 'FTT Amt']].sum().sort_values(by=['Current', 'Current P/L'], ascending=False)
df_tmp['Current P/L%'] = round(df_tmp['Current P/L'] * 100 / df_tmp['Current'], 2)
df_tmp['FTT%'] = round(df_tmp['FTT Amt'] * 100 / df_tmp['Current'], 2)
cols = ['CurrAlloc%', 'Current P/L%', 'FTT%']
df_tmp[cols].sort_values(by=['CurrAlloc%'], ascending=False)

               CurrAlloc%  Current P/L%    FTT%
Category
FMCG                14.75        -17.67   58.95
FINANCE             10.80        -12.00   60.72
IT                   9.99        -47.93  121.90
MISC                 7.21        -22.15   75.21
AUTO                 6.63         -8.43   49.08
BANKS                5.83         -2.45   49.82
PAINTS               5.50        -17.74   38.19
INSURANCE            5.37         -1.18   35.39
PHARMA               4.85         -0.31   31.35
ELECTRICAL           4.06        -14.17   54.46
CHEMICALS            2.24        -18.89   89.75
HEALTHCARE           2.04        -15.10   45.13
AC                   1.83        -14.31   45.31
APPARELS             1.82          3.30   29.17
FOOTWEAR             1.71        -70.14  138.36
TRAVEL               1.64        -78.95  168.55
DURABLES             1.53        -65.90  106.26
BREWERIES            1.53         -0.47   21.33
REALTY               1.51          3.88   11.91
ENGINEERING          1.41        -12.41   63.83
CABLES               1.41         31.43   42.56
CERAMICS             1.39        -44.10   87.89
REFINERIES           1.12        -17.57   47.32
JEWELLERY            1.10        -90.34  156.48
CEMENT               1.07        -65.14  188.69
ENTERTAINMENT        0.78        -62.32  159.13
HOTELS               0.43        -71.67  132.22
TEXTILES             0.41        -47.51   89.57

In [29]:
# money to be made criteria-wise
df_portfolio_features.groupby('Criteria')['FTT Amt'].agg(['sum', 'count']).sort_values(by='sum', ascending=False)

                sum  count
Criteria
XY24      3383497.0     21
X40       1906539.0     19
XR        1313419.0     13
AR        1152976.0      9
X40N      1072887.0     13
OX40N      722153.0     10
XY25       442609.0      5
SR         287464.0      2

In [30]:
# money to be made conviction-wise
df_portfolio_features.groupby('Conviction')['FTT Amt'].agg(['sum', 'count']).sort_values(by='sum', ascending=False)

                  sum  count
Conviction
H-SC        3305464.0     24
X-LC        1886997.0     21
X-MC        1576107.0     15
M-SC        1385117.0     14
X-SC        1289635.0      9
H-MC         291388.0      2
L-SC         200118.0      2
M-LC         164831.0      1
M-MC          84692.0      2
L-MC          49395.0      1
H-LC          47800.0      1

In [31]:
# money to be made criteria and conviction-wise
df_portfolio_features.groupby(['Conviction', 'Criteria'])['FTT Amt'].agg(['sum', 'count']).sort_values(by='sum', ascending=False)

                           sum  count
Conviction Criteria
X-LC       X40       1017272.0     10
H-SC       XY24       980739.0      6
           AR         951161.0      5
M-SC       XY24       821454.0      6
H-SC       XR         777624.0      7
X-SC       XY24       773531.0      4
X-MC       X40        677434.0      7
           X40N       428301.0      4
X-LC       X40N       340315.0      6
           XY24       335198.0      2
H-SC       OX40N      308476.0      4
X-SC       X40N       304271.0      3
M-SC       OX40N      301015.0      5
H-SC       SR         287464.0      2
H-MC       XY24       243248.0      1
X-MC       XY25       241045.0      2
           XY24       229327.0      2
X-SC       X40        211833.0      2
M-SC       XR         192121.0      2
M-LC       XR         164831.0      1
X-LC       XY25       152220.0      2
L-SC       OX40N      112662.0      1
           XR          87456.0      1
M-SC       AR          70527.0      1
L-MC       XR          49395.0      1
M-MC       XY25        49344.0      1
H-MC       AR          48140.0      1
H-LC       AR          47800.0      1
X-LC       XR          41992.0      1
M-MC       AR          35348.0      1

In [32]:
# notebook execution time

end_time = time.time()
execution_time = round(end_time - start_time, 0)
print(f"Notebook execution time: {execution_time} seconds")

Notebook execution time: 33.0 seconds