<a href="https://colab.research.google.com/github/ankit-rathi/Quantvesting_v2/blob/main/myStocks_Portfolio_Analysis.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
'''
!pip install pandas==2.2.2 -qq
!pip install pyxirr -qq
!pip install ta -qq
!pip install yfinance==0.2.59 -qq
'''

'\n!pip install pandas==2.2.2 -qq\n!pip install pyxirr -qq\n!pip install ta -qq\n!pip install yfinance==0.2.59 -qq\n'

In [2]:
# import libraries

import numpy as np
import pandas as pd
import datetime
import warnings
warnings.filterwarnings('ignore')
import yfinance as yfin
import ta
import matplotlib.pyplot as plt
import requests

In [3]:
# notebook start time
import time
import datetime
import pytz

start_time = time.time()

# function to print date timestamp
def print_date_time():
  tz_NY = pytz.timezone('Asia/Kolkata')
  datetime_NY = datetime.datetime.now(tz_NY)
  print("Run date time (IST):", datetime_NY.strftime("%Y-%m-%d %H:%M:%S"))

In [4]:
# function to get booked and reserved amount
def get_amt():
  # fetch the JSON data from the URL
  url = "https://raw.githubusercontent.com/ankit-rathi/Tradevesting_v1/main/data/myPortfolioAmts.json"
  response = requests.get(url)
  pf_amts = response.json()  # parse the JSON data

  # extract values from the JSON
  py_booked_amt_dm = pf_amts["py_booked_amt_dm"]
  py_booked_amt_sv = pf_amts["py_booked_amt_sv"]
  cy_booked_amt_dm = pf_amts["cy_booked_amt_dm"]
  cy_booked_amt_sv = pf_amts["cy_booked_amt_sv"]
  reserve_amt_dm = pf_amts["reserve_amt_dm"]
  reserve_amt_sv = pf_amts["reserve_amt_sv"]

  # perform calculations
  py_booked_amt = py_booked_amt_dm + py_booked_amt_sv
  cy_booked_amt = cy_booked_amt_dm + cy_booked_amt_sv
  reserve_amt = reserve_amt_dm + reserve_amt_sv
  total_booked_amt = py_booked_amt + cy_booked_amt

  return total_booked_amt, reserve_amt, cy_booked_amt, py_booked_amt

gen_output = 0

In [5]:
# function to format the amount
def format_amt(number):
    abs_number = abs(number)

    if abs_number >= 1_00_00_000:  # Crores
        formatted_amt = f"{number / 1_00_00_000:.2f} C"
    elif abs_number >= 1_00_000:  # Lakhs
        formatted_amt = f"{number / 1_00_000:.2f} L"
    elif abs_number >= 1_000:  # Thousands
        formatted_amt = f"{number / 1_000:.2f} K"
    else:
        formatted_amt = f"{number:.2f}"

    return formatted_amt

# function to set start and end date
def get_start_end_date():
  start_date = (datetime.date.today() + datetime.timedelta(days=-365)).strftime('%Y-%m-%d')
  end_date = (datetime.date.today() + datetime.timedelta(days=1)).strftime('%Y-%m-%d')
  return start_date, end_date

# function to fetch my portfolio csv
def get_mypfs_df():
  mypfs_df = pd.read_csv('https://raw.githubusercontent.com/ankit-rathi/Tradevesting_v1/main/data/myPortfolioStocks.csv')
  return mypfs_df

# function to fetch my prospects csv
def get_mypps_df():
  mypps_df = pd.read_csv('https://raw.githubusercontent.com/ankit-rathi/Tradevesting_v1/main/data/myProspectsScrips.csv')
  return mypps_df

# function to fetch screener data
def get_myscreen_df():
  myscreen_df = pd.read_csv('https://raw.githubusercontent.com/ankit-rathi/Tradevesting_v1/main/data/myScreenerDB.csv')
  return myscreen_df

# function to fetch momentum data
def get_myinvmt_df():
  myinvmt_df = pd.read_csv('https://raw.githubusercontent.com/ankit-rathi/Tradevesting_v1/main/data/myInvestments.csv')
  return myinvmt_df

# function to get the stock ids
def get_stock_ids(df_pf):
  stock_n100 = df_pf['Symbol'].unique()

  exclude = ['CADILAHC','MMTC', 'MASFIN']

  stock_ids = df_pf[~df_pf['Symbol'].isin(exclude) ]['Symbol'].unique()

  #mypf = mypf[mypf.Forecast.notnull()]
  #stock_ids = mypf['Symbol'].unique()

  #stock_ids.sort()
  return stock_ids

# get features from screener data
def get_screener_features():
  myscreen_df = get_myscreen_df()
  cols = ['Symbol', 'EPS', 'MedPE', 'ROCE%', 'ROE%', 'CapType']
  return myscreen_df[cols]

# get relative strength
def get_relative_strength(stock_list):

    # Dictionary to store stock tickers and their corresponding percentage price change
    stock_changes = {}

    # Loop through each stock and fetch its price data
    for stock in stock_list:
        try:
            # Download the stock data for the given date range
            stock_data = yfin.Ticker(stock + '.NS').history(period='1mo', interval='1d')[map(str.title, ['open', 'close', 'low', 'high', 'volume'])]

            # Calculate the percentage change for the stock
            if len(stock_data) > 0:
                start_price = stock_data['Close'].iloc[0]
                end_price = stock_data['Close'].iloc[-1]
                percent_change = round(((end_price - start_price) / start_price) * 100, 2)
                stock_changes[stock] = percent_change
            else:
                stock_changes[stock] = np.nan  # If no data is available, set to NaN

        except Exception as e:
            print(f"Error fetching data for {stock}: {e}")
            stock_changes[stock] = np.nan

    # Create a DataFrame with stock tickers and their percentage changes
    df = pd.DataFrame(list(stock_changes.items()), columns=['Symbol', 'Percent_Change'])

    # Drop any stocks with missing data (NaN values)
    df = df.dropna()

    # Calculate the percentile rank based on percentage change
    df['RSP'] = round(df['Percent_Change'].rank(pct=True) * 100, 2)
    cols = ['Symbol', 'RSP']
    df = df[cols]
    # Sort by percentile rank (optional)
    df = df.sort_values(by='RSP', ascending=False).reset_index(drop=True)

    return df

In [6]:
# function to get stock technicals
def stock_prec_dev(stock_symbol):
    #stock_symbol = 'ULTRACEMCO.NS'
    short_window = 20
    mid_window = 50
    long_window = 200
    moving_avg = 'SMA'

    start = datetime.datetime(*map(int, start_date.split('-')))
    end = datetime.datetime(*map(int, end_date.split('-')))

    stock_df = yfin.Ticker(stock_symbol + '.NS').history(period='max', interval='1d')[map(str.title, ['open', 'close', 'low', 'high', 'volume'])]

    stock_df['Max'] = round(max(stock_df['Close']),2)
    stock_df = stock_df[(stock_df.index <= end_date) & (stock_df.index >= start_date)]
    stock_df['200_SMA'] = round(stock_df['Close'].rolling(window = 200, min_periods = 1).mean(),0)
    stock_df['Dev%_200'] = round((stock_df['Close'] - stock_df['200_SMA'])*100/stock_df['200_SMA'],2)
    stock_df.dropna(axis = 0, inplace = True) # remove any null rows

    stock_df['20_SMA'] = stock_df['Close'].rolling(window=20).mean()
    stock_df['50_SMA'] = stock_df['Close'].rolling(window=50).mean()
    stock_df['Symbol'] = stock_symbol

    stock_df['Close'] = round(stock_df['Close'],2)
    stock_df['Min'] = round(min(stock_df['Close']),2)
    stock_df['RSI_14'] = ta.momentum.RSIIndicator(close=stock_df['Close'], window=14).rsi()
    stock_df['RSI_14'] = round(stock_df['RSI_14'],0)
    stock_df['Prev_Close'] = stock_df['Close'].shift(1)
    stock_df.drop(['Open', 'Low', 'High', 'Volume'], axis=1, inplace=True)
    stock_df = stock_df.tail(1)

    max_SMA = max(stock_df['20_SMA'].item(), stock_df['50_SMA'].item(), stock_df['200_SMA'].item())
    min_SMA = min(stock_df['20_SMA'].item(), stock_df['50_SMA'].item(), stock_df['200_SMA'].item())
    ABS_Spread = max_SMA - min_SMA
    stock_df['Spread%'] = round((ABS_Spread / stock_df['200_SMA'].item()) * 100,2)

    return stock_df

# function to compute stock attributes
def get_common_features(stock_ids, df_mypf):

  df_prec_dev = pd.DataFrame()
  df_tmp = get_screener_features()
  df_rs = get_relative_strength(stock_ids)

  for stock_id in stock_ids:
      tmp = stock_prec_dev(stock_id)
      tmp = tmp.reset_index()
      df_prec_dev = pd.concat([df_prec_dev, tmp], ignore_index = True)
  df_prec_dev = pd.merge(df_prec_dev, df_mypf, on= 'Symbol')
  df_prec_dev = pd.merge(df_prec_dev, df_tmp, on= 'Symbol', how='left')
  df_prec_dev = pd.merge(df_prec_dev, df_rs, on= 'Symbol', how='left')
  #print(df_prec_dev.columns)
  df_prec_dev['Curr_PE'] = round(df_prec_dev['Close']/df_prec_dev['EPS'],1)
  df_prec_dev['Dev%_PE'] = round((df_prec_dev['Curr_PE'] - df_prec_dev['MedPE'])*100/df_prec_dev['MedPE'],2)
  df_prec_dev['Conviction'] = df_prec_dev['Conviction'] + '-' + df_prec_dev['CapType']
  return df_prec_dev

# function to arrange stock features
def arrange_features(df_stocks, common_cols, diff_cols):
  df_stocks_common = df_stocks[common_cols].drop_duplicates()
  df_stocks_diff = df_stocks[diff_cols]
  df_stocks_diff['Investment'] = df_stocks_diff['AvgCost'] * df_stocks_diff['Shares']
  df_stocks_diff = df_stocks_diff.groupby(['Symbol'])[['Shares', 'Investment']].aggregate(['sum']).reset_index()
  df_stocks_diff.columns = ['Symbol', 'Shares', 'Investment']
  df_stocks_diff['AvgCost'] = round(df_stocks_diff['Investment']/df_stocks_diff['Shares'],2)
  df_stocks = pd.merge(df_stocks_diff, df_stocks_common, on='Symbol')
  return df_stocks

# plot fact distribution across dimension
def plot_pie_chart(df, dimension, fact):
  # grouping the data by category and calculating the sum of fact for each type
  grouped_data = df.groupby(dimension)[fact].sum()

  # sorting the grouped data in descending order
  grouped_data = grouped_data.sort_values(ascending=False)

  # creating a pie chart
  grouped_data.plot.pie(autopct='%1.1f%%', startangle=90, figsize=(6, 6))

  # adding a title and displaying the plot
  plt.title(f'{dimension} {fact} Distribution')
  plt.ylabel('')  # To hide the y-label
  plt.show()

In [7]:
# function to get portfolio features

def get_portfolio_features(df_common_features):

  print_date_time()
  print('-------------------')

  #df_common_features["Target"] = df_common_features["Target"].fillna(df_common_features["Max"])
  df_common_features['NTT'] = np.where(df_common_features['Strategy']== 'NTT', df_common_features["Target"], df_common_features['Max'])
  df_common_features['LTT'] = np.where(df_common_features['Strategy']== 'BTT', df_common_features["Target"], df_common_features['Max'])
  df_common_features['BOL'] = df_common_features['Min']

  tmp_df = df_common_features[df_common_features['Symbol'].isin(mypf_df[mypf_df['InPortfolio'] != 'NA'].Symbol.values)]
  print('qualified stocks: '+str(len(tmp_df['Symbol'].unique())))
  tmp_df1 = tmp_df[tmp_df['LatestQtr'] == 1]
  print('with latest results: '+str(len(tmp_df1['Symbol'].unique())))
  tmp_df1 = tmp_df1[tmp_df1['StarStock'] == 1]
  print('still star stocks: '+str(len(tmp_df1['Symbol'].unique())))
  tmp_df['Investment'] = tmp_df['AvgCost'] * tmp_df['Shares']
  tmp_df['Current'] = round(tmp_df['Close'] * tmp_df['Shares'],0)
  tmp_df['Previous'] = tmp_df['Prev_Close'] * tmp_df['Shares']
  tmp_df['EstimatedST'] = tmp_df['NTT'] * tmp_df['Shares']
  tmp_df['EstimatedLT'] = tmp_df['LTT'] * tmp_df['Shares']
  tmp_df['Current P/L'] = round((tmp_df['Current'] - tmp_df['Investment']),0)
  tmp_df['Today P/L%'] = round((tmp_df['Current'] - tmp_df['Previous'])*100/tmp_df['Previous'],2)
  tmp_df['Current P/L%'] = round((tmp_df['Current'] - tmp_df['Investment'])*100/tmp_df['Investment'],2)
  tmp_df['EstimatedST P/L%'] = round((tmp_df['EstimatedST'] - tmp_df['Investment'])*100/tmp_df['Investment'],2)
  tmp_df['EstimatedLT P/L%'] = round((tmp_df['EstimatedLT'] - tmp_df['Investment'])*100/tmp_df['Investment'],2)
  tmp_df['NTT%'] = round((tmp_df['NTT'] - tmp_df['Close'])*100/tmp_df['Close'],2)
  tmp_df['LTT%'] = round((tmp_df['LTT'] - tmp_df['Close'])*100/tmp_df['Close'],2)
  tmp_df['Gained%'] = round((tmp_df['Close'] - tmp_df['BOL'])*100/tmp_df['BOL'],2)
  investment = round(sum(tmp_df['AvgCost']*tmp_df['Shares']),0)
  current = round(sum(tmp_df['Close']*tmp_df['Shares']),0)
  tmp_df['InitAlloc%'] = round(tmp_df['Investment']*100/investment,2)
  tmp_df['CurrAlloc%'] = round(tmp_df['Current']*100/current,2)
  tmp_df['FTT'] = tmp_df['LTT']
  tmp_df.loc[tmp_df['Strategy'] == 'NTT', 'FTT'] = tmp_df['NTT']
  tmp_df['FTT%'] = tmp_df['LTT%']
  tmp_df.loc[tmp_df['Strategy'] == 'NTT', 'FTT%'] = tmp_df['NTT%']
  tmp_df['FTT Amt'] = round(tmp_df['FTT%'] * tmp_df['Current']/100,0)
  tmp_df['OTT%'] = round((tmp_df['FTT'] - tmp_df['AvgCost'])*100/tmp_df['AvgCost'],2)
  tmp_df['RRR Ind'] = round(tmp_df['Current P/L']/tmp_df['FTT Amt'],2)
  tmp_df['Risk Ind'] = round(tmp_df['Current P/L%']*tmp_df['CurrAlloc%'],0)

  return tmp_df

# function to print portfolio features
def print_portfolio_stats(df_portfolio_features, myinvmt_df):
  from pyxirr import xirr

  total_booked_amt, reserve_amt, cy_booked_amt, py_booked_amt = get_amt()

  dates = myinvmt_df['Date'].values
  dates = np.append(dates, datetime.date.today().strftime('%d-%b-%y'))
  investment = myinvmt_df['Investment'].values
  dates= pd.to_datetime(dates)

  current = round(sum(df_portfolio_features['Close']*df_portfolio_features['Shares']),0) + reserve_amt
  investment_xirr = np.append(investment, current)
  cagr = round(xirr(pd.DataFrame({"dates": dates, "amounts": investment_xirr}))*100,2)

  investment = -sum(investment)
  invested = round(sum(df_portfolio_features['AvgCost']*df_portfolio_features['Shares']),0) + reserve_amt
  previous = round(sum(df_portfolio_features['Prev_Close']*df_portfolio_features['Shares']),0) + reserve_amt
  cy_invested = investment + py_booked_amt

  today_pnl_amount = current-previous
  today_pnl_percentage = round((current-previous)*100/previous,2)

  curr_pnl_amount = current-invested
  curr_pnl_percentage = round((curr_pnl_amount)*100/(cy_invested),2)

  cy_pnl_amount = cy_booked_amt + curr_pnl_amount
  cy_pnl_percentage = round((cy_pnl_amount)*100/cy_invested,2)

  overall_pnl_amount = total_booked_amt + curr_pnl_amount
  overall_pnl_percentage = round((overall_pnl_amount)*100/investment,2)

  estimate_st = round(sum(df_portfolio_features['FTT']*df_portfolio_features['Shares']),0)  + reserve_amt
  est_st_pnl_amount = estimate_st-current
  est_st_pnl_percentage = round((est_st_pnl_amount)*100/current,2)

  estimate_lt = round(sum(df_portfolio_features['LTT']*df_portfolio_features['Shares']),0)  + reserve_amt
  est_lt_pnl_amount = estimate_lt-current
  est_lt_pnl_percentage = round((est_lt_pnl_amount)*100/current,2)

  total_profit = round(sum(df_portfolio_features[df_portfolio_features['Current P/L%'] > 0]['Current']) - sum(df_portfolio_features[df_portfolio_features['Current P/L%'] > 0]['Investment']),0)
  total_loss = round(sum(df_portfolio_features[df_portfolio_features['Current P/L%'] < 0]['Current']) - sum(df_portfolio_features[df_portfolio_features['Current P/L%'] < 0]['Investment']),0)

  cy_booked_percentage = round((cy_booked_amt)*100/current,2)
  py_booked_percentage = round((py_booked_amt)*100/investment,2)
  total_booked_percentage = round((total_booked_amt)*100/investment,2)

  print('-------------------')
  print('Initial Investment: ', format_amt(investment))
  print('CY Investment: ', format_amt(cy_invested))
  print('Reserve: ', format_amt(reserve_amt))
  print('Current: ',  format_amt(current))
  print('-------------------')
  print('Today PnL: '+ '{} ({}%)'.format(format_amt(today_pnl_amount), today_pnl_percentage))
  print('Current PnL: '+ '{} ({}%)'.format(format_amt(curr_pnl_amount), curr_pnl_percentage))
  print('CY Booked + Current PnL: '+ '{} ({}%)'.format(format_amt(cy_pnl_amount), cy_pnl_percentage))
  print('-------------------')
  print('Total profit: ', format_amt(total_profit))
  print('Total loss: ', format_amt(total_loss))
  print('-------------------')
  print('Total Booked + Current PnL: '+ '{} ({}%)'.format(format_amt(overall_pnl_amount), overall_pnl_percentage))
  print('Total Booked PnL: '+ '{} ({}%)'.format(format_amt(total_booked_amt), total_booked_percentage))
  print('Curr Year Booked PnL: '+ '{} ({}%)'.format(format_amt(cy_booked_amt), cy_booked_percentage))
  print('Prev Year Booked PnL: '+ '{} ({}%)'.format(format_amt(py_booked_amt), py_booked_percentage))
  print('===================')
  print('Est FTT: ',  format_amt(estimate_st))
  print('Est FTT PnL: '+ '{} ({}%)'.format(format_amt(est_st_pnl_amount), est_st_pnl_percentage))

  print('===================')
  print('Deployed: ', format_amt(investment))

  print('Current: ', format_amt(current))

  print('CAGR/XIRR %: '+'{}%'.format(cagr))

In [8]:
# get start and end date
start_date, end_date = get_start_end_date()

# get portfolio and prospects data
mypfs_df = get_mypfs_df()
mypps_df = get_mypps_df()
myinvmt_df = get_myinvmt_df()

# merge above datasets
mypf_df = pd.merge(mypfs_df, mypps_df, on="Symbol")

# seggregate dm and sv portfolio
dm_pf = mypf_df[mypf_df['InPortfolio'] == 'DM']
sv_pf = mypf_df[mypf_df['InPortfolio'] == 'SV']

# build portfolio stock dataframe
dm_stocks = get_stock_ids(dm_pf)
sv_stocks = get_stock_ids(sv_pf)
df_stocks = pd.concat([dm_pf,sv_pf], ignore_index = True)

# arrange common and diff stock features
common_cols = ['Symbol', 'Target', 'Criteria', 'Strategy', 'CumlRnk', 'LatestQtr', 'StarStock', 'Conviction', 'Category', 'InFolio', 'XIRR', 'MBQ']
diff_cols = ['Symbol', 'AvgCost', 'Shares']
df_stocks = arrange_features(df_stocks, common_cols, diff_cols)

# get common features
stock_ids = df_stocks['Symbol'].values
df_common_features = get_common_features(stock_ids, df_stocks)

df_common_features.reset_index(drop=True, inplace=True)
df_common_features.drop(['Date'], axis=1, inplace=True)
# get and print portfolio features
df_portfolio_features = get_portfolio_features(df_common_features)

print_portfolio_stats(df_portfolio_features, myinvmt_df)

df = df_portfolio_features
#plot_pie_chart(df, 'CapType', 'Current')
list_ox40n = list(df[df['MBQ'].str.contains('OX40N', na=False)]['Symbol'].values)

Run date time (IST): 2026-07-07 15:31:06
-------------------
qualified stocks: 92
with latest results: 31
still star stocks: 20
-------------------
Initial Investment:  1.40 C
CY Investment:  1.82 C
Reserve:  1.49 K
Current:  1.53 C
-------------------
Today PnL: -33.73 K (-0.22%)
Current PnL: -29.86 L (-16.37%)
CY Booked + Current PnL: -27.78 L (-15.23%)
-------------------
Total profit:  4.63 L
Total loss:  -34.49 L
-------------------
Total Booked + Current PnL: 15.09 L (10.81%)
Total Booked PnL: 44.95 L (32.22%)
Curr Year Booked PnL: 2.08 L (1.36%)
Prev Year Booked PnL: 42.87 L (30.73%)
===================
Est FTT:  2.55 C
Est FTT PnL: 1.02 C (66.32%)
===================
Deployed:  1.40 C
Current:  1.53 C
CAGR/XIRR %: 4.32%

In [9]:
# top 5 near their targets
cols = ['Symbol', 'Today P/L%', 'Current P/L%', 'FTT%', 'OTT%', 'FTT Amt', 'Current P/L', 'Current', 'FTT', 'Dev%_PE', 'RSI_14','Conviction', 'Spread%',  'CumlRnk', 'RRR Ind', 'CurrAlloc%', 'Gained%', 'Criteria', 'Strategy', 'Category']
df_tmp = df_portfolio_features[~df_portfolio_features['Symbol'].isin(['ENRIN','BLUSPRING','DIGITIDE'])]
df_tmp = df_tmp.sort_values(by = 'FTT Amt', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
59,PIDILITIND,0.12,14.72,3.18,18.37,5148.0,20770.0,161880.0,1670.26,-19.59,72.0,X-LC,7.82,5.0,4.03,1.06,27.10,X40,ATH,CHEMICALS
49,JSWINFRA,-0.31,9.96,5.88,16.43,14339.0,22091.0,243865.0,342.00,-5.72,62.0,X-MC,11.79,61.0,1.54,1.59,38.26,X40N,NTT,REALTY
83,TTKPRESTIG,1.36,-17.46,21.26,0.09,17685.0,-17592.0,83185.0,770.00,93.17,71.0,M-SC,5.26,250.0,-0.99,0.54,48.12,OX40N,NTT,DURABLES
68,SATIN,1.72,45.01,4.70,51.83,18830.0,124363.0,400647.0,274.00,30.09,69.0,H-SC,41.50,159.0,6.60,2.61,95.17,XY24,NTT,FINANCE
55,MASFIN,0.88,-1.41,23.30,21.57,22508.0,-1380.0,96600.0,397.04,-15.09,59.0,H-SC,1.62,167.0,-0.06,0.63,15.14,XR,ATH,FINANCE

In [10]:
# top 5 today
df_tmp = df_portfolio_features.sort_values(by = 'Today P/L%', ascending=False)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
29,GREENPANEL,4.05,-47.66,173.46,43.14,166225.0,-87249.0,95829.0,537.00,114.47,54.0,M-SC,16.35,225.0,-0.52,0.63,15.11,XY24,NTT,MISC
32,HAVELLS,3.68,-21.57,67.56,31.42,173798.0,-70741.0,257250.0,2052.62,-26.23,62.0,X-MC,12.25,63.0,-0.41,1.68,8.50,X40,ATH,ELECTRICAL
33,HCLTECH,3.16,-24.07,60.03,21.51,110269.0,-58234.0,183690.0,1872.35,-20.18,57.0,X-LC,20.14,8.0,-0.53,1.20,13.13,X40,ATH,IT
45,INFY,2.85,-27.03,83.97,34.24,191716.0,-84573.0,228315.0,1972.00,-42.67,48.0,X-LC,20.91,3.0,-0.44,1.49,8.79,X40,NTT,IT
70,SHALBY,2.32,-33.44,87.96,25.10,106045.0,-60582.0,120561.0,327.00,786.76,56.0,M-SC,9.67,236.0,-0.57,0.79,37.20,XY24,NTT,HEALTHCARE

In [11]:
# bottom 5 today
df_tmp = df_portfolio_features.sort_values(by = 'Today P/L%', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
0,5PAISA,-3.45,-30.03,61.36,12.90,93807.0,-65616.0,152880.0,593.00,124.76,63.0,H-SC,4.81,170.0,-0.70,1.00,47.53,OX40N,NTT,FINANCE
25,FINCABLES,-3.13,33.37,55.89,107.91,110054.0,49267.0,196911.0,1641.55,19.74,43.0,M-SC,26.81,220.0,0.45,1.28,48.14,OX40N,ATH,CABLES
63,RECLTD,-2.54,-3.76,25.46,20.74,49781.0,-7645.0,195525.0,446.00,5.47,48.0,M-MC,2.66,191.0,-0.15,1.28,16.52,XY25,NTT,FINANCE
6,AWL,-2.51,-35.96,160.78,67.02,366895.0,-128112.0,228197.0,485.00,-65.55,47.0,X-SC,14.32,81.0,-0.35,1.49,8.51,XY24,NTT,FMCG
64,RELAXO,-2.31,-49.30,200.38,52.31,147484.0,-71558.0,73602.0,1176.00,-45.99,60.0,X-SC,11.39,92.0,-0.49,0.48,64.56,X40N,NTT,FOOTWEAR

In [12]:
# top 5 to exit based on CumlRnk
df_tmp = df_portfolio_features[~df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])]
df_tmp = df_tmp[(df_tmp['Current P/L%'] > -1) & (df_tmp['Current P/L%'] < 1)].sort_values(by = 'CumlRnk', ascending=False)
df_tmp[cols].head()

Empty DataFrame
Columns: [Symbol, Today P/L%, Current P/L%, FTT%, OTT%, FTT Amt, Current P/L, Current, FTT, Dev%_PE, RSI_14, Conviction, Spread%, CumlRnk, RRR Ind, CurrAlloc%, Gained%, Criteria, Strategy, Category]
Index: []

In [13]:
# OX40N stocks to exit
df_tmp = df_portfolio_features[(df_portfolio_features['Symbol'].isin(list_ox40n))].sort_values(by = 'Current P/L%', ascending=False)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
25,FINCABLES,-3.13,33.37,55.89,107.91,110054.0,49267.0,196911.0,1641.55,19.74,43.0,M-SC,26.81,220.0,0.45,1.28,48.14,OX40N,ATH,CABLES
72,SIS,0.92,-1.24,22.79,21.26,24989.0,-1382.0,109650.0,528.00,2617.10,57.0,H-SC,24.98,168.0,-0.06,0.72,63.03,OX40N,NTT,MISC
16,CERA,-2.02,-16.78,48.86,23.89,71529.0,-29508.0,146395.0,9475.00,-19.81,61.0,H-SC,14.70,153.0,-0.41,0.95,42.31,OX40N,NTT,CERAMICS
83,TTKPRESTIG,1.36,-17.46,21.26,0.09,17685.0,-17592.0,83185.0,770.00,93.17,71.0,M-SC,5.26,250.0,-0.99,0.54,48.12,OX40N,NTT,DURABLES
43,INDIGOPNTS,1.41,-22.29,28.70,0.02,38933.0,-38903.0,135656.0,1408.00,107.03,70.0,M-SC,4.43,222.0,-1.00,0.88,53.91,OX40N,NTT,PAINTS

In [14]:
# top 5 to book for rotation
df_tmp = df_portfolio_features[(df_portfolio_features['Current P/L%'] > 20) ].sort_values(by = 'CumlRnk', ascending=False)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
25,FINCABLES,-3.13,33.37,55.89,107.91,110054.0,49267.0,196911.0,1641.55,19.74,43.0,M-SC,26.81,220.0,0.45,1.28,48.14,OX40N,ATH,CABLES
68,SATIN,1.72,45.01,4.70,51.83,18830.0,124363.0,400647.0,274.00,30.09,69.0,H-SC,41.50,159.0,6.60,2.61,95.17,XY24,NTT,FINANCE
91,ZYDUSLIFE,0.40,21.53,11.60,35.63,29545.0,45128.0,254702.0,1286.17,5.86,69.0,H-MC,14.93,120.0,1.53,1.66,33.92,AR,ATH,PHARMA
60,QUESS,1.65,22.39,42.09,73.90,55011.0,23906.0,130699.0,424.00,-34.44,87.0,X-SC,22.01,80.0,0.43,0.85,78.17,XY24,NTT,MISC

In [15]:
# top 5 to monitor for exit
df_tmp = df_portfolio_features[~df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])]
df_tmp = df_tmp[(df_tmp['Current P/L%'] > 0) ].sort_values(by = 'Dev%_PE', ascending=False)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
75,SURYODAY,-2.01,1.38,21.36,23.03,38777.0,2469.0,181540.0,216.00,97.37,58.0,H-SC,20.23,166.0,0.06,1.18,52.85,XR,NTT,BANKS
74,STARHEALTH,1.41,14.08,29.08,47.26,93264.0,39592.0,320715.0,761.00,80.11,70.0,H-SC,15.89,173.0,0.42,2.09,39.70,XY24,NTT,INSURANCE
68,SATIN,1.72,45.01,4.70,51.83,18830.0,124363.0,400647.0,274.00,30.09,69.0,H-SC,41.50,159.0,6.60,2.61,95.17,XY24,NTT,FINANCE
25,FINCABLES,-3.13,33.37,55.89,107.91,110054.0,49267.0,196911.0,1641.55,19.74,43.0,M-SC,26.81,220.0,0.45,1.28,48.14,OX40N,ATH,CABLES
91,ZYDUSLIFE,0.40,21.53,11.60,35.63,29545.0,45128.0,254702.0,1286.17,5.86,69.0,H-MC,14.93,120.0,1.53,1.66,33.92,AR,ATH,PHARMA

In [16]:
# top 5 to book for rotation from weak conviction
df_tmp = df_portfolio_features[~df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])]
df_tmp = df_tmp[~df_tmp['Criteria'].isin(['XY25','XY24','X40', 'X40N'])].sort_values(by = 'RRR Ind', ascending=False)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
91,ZYDUSLIFE,0.40,21.53,11.60,35.63,29545.0,45128.0,254702.0,1286.17,5.86,69.0,H-MC,14.93,120.0,1.53,1.66,33.92,AR,ATH,PHARMA
73,SONACOMS,0.22,15.73,19.84,38.69,23226.0,15907.0,117066.0,801.69,-8.32,77.0,M-MC,19.49,193.0,0.68,0.76,66.09,AR,ATH,AUTO
25,FINCABLES,-3.13,33.37,55.89,107.91,110054.0,49267.0,196911.0,1641.55,19.74,43.0,M-SC,26.81,220.0,0.45,1.28,48.14,OX40N,ATH,CABLES
75,SURYODAY,-2.01,1.38,21.36,23.03,38777.0,2469.0,181540.0,216.00,97.37,58.0,H-SC,20.23,166.0,0.06,1.18,52.85,XR,NTT,BANKS
72,SIS,0.92,-1.24,22.79,21.26,24989.0,-1382.0,109650.0,528.00,2617.10,57.0,H-SC,24.98,168.0,-0.06,0.72,63.03,OX40N,NTT,MISC

In [17]:
# top 5 to accumulate based on lowest RSI_14
df_tmp = df_portfolio_features[df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])].sort_values(by = 'RSI_14', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
87,VBL,-2.19,-2.23,38.46,35.37,118761.0,-7050.0,308792.0,670.16,-13.69,34.0,X-LC,9.39,13.0,-0.06,2.01,26.91,X40N,ATH,FMCG
81,TMPV,-1.47,-22.16,75.46,36.58,209009.0,-78861.0,276980.0,600.00,-83.62,38.0,X-LC,7.26,4.0,-0.38,1.81,16.40,XY24,NTT,AUTO
51,KOTAKBANK,0.22,2.11,18.60,21.11,26300.0,2924.0,141396.0,453.24,-12.44,40.0,X-LC,4.27,12.0,0.11,0.92,8.14,X40,ATH,BANKS
71,SIEMENS,-2.13,-6.08,33.64,25.51,58798.0,-11310.0,174785.0,4671.50,46.70,40.0,H-LC,11.07,51.0,-0.19,1.14,22.72,AR,ATH,ELECTRICAL
23,DMART,0.13,-2.16,32.47,29.60,79292.0,-5400.0,244200.0,5391.45,-17.46,41.0,X-LC,3.46,14.0,-0.07,1.59,11.62,X40N,ATH,FMCG

In [18]:
# top 5 to accumulate based on Spread and CumlRnk
df_tmp = df_portfolio_features[df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])]
df_tmp = df_tmp[(df_tmp['CumlRnk'] < 100)].sort_values(by = 'Spread%', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
17,CIPLA,-1.43,17.49,13.57,33.43,24419.0,26788.0,179949.0,1648.14,-9.03,61.0,X-LC,2.24,18.0,1.10,1.17,22.85,X40N,ATH,PHARMA
19,COLPAL,-0.15,-21.16,77.39,39.86,160693.0,-55725.0,207640.0,3683.41,-4.51,57.0,X-MC,3.00,62.0,-0.35,1.35,17.45,XY25,ATH,FMCG
84,UNITDSPR,0.86,5.75,14.20,20.77,35161.0,13467.0,247611.0,1644.00,-6.16,72.0,X-MC,3.06,64.0,0.38,1.62,18.12,X40N,NTT,BREWERIES
23,DMART,0.13,-2.16,32.47,29.60,79292.0,-5400.0,244200.0,5391.45,-17.46,41.0,X-LC,3.46,14.0,-0.07,1.59,11.62,X40N,ATH,FMCG
11,BERGEPAINT,-2.29,-6.03,33.36,25.32,80799.0,-15547.0,242202.0,680.00,-11.15,47.0,X-MC,3.59,68.0,-0.19,1.58,26.06,XY24,NTT,PAINTS

In [19]:
# top 5 to accumulate based on lowest Gained%
df_tmp = df_portfolio_features[df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])].sort_values(by = 'Gained%', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
58,PGHH,0.69,-32.38,95.22,32.01,137482.0,-69136.0,144384.0,17616.87,-54.24,45.0,X-MC,20.87,57.0,-0.50,0.94,2.39,X40,ATH,FMCG
65,RELIANCE,-1.23,-16.23,49.58,25.30,83465.0,-32618.0,168345.0,1952.00,-18.49,47.0,X-LC,7.42,21.0,-0.39,1.10,3.67,XY25,BTT,REFINERIES
47,ITC,-0.09,-24.14,56.94,19.06,146933.0,-82118.0,258048.0,452.00,-58.35,47.0,X-LC,12.68,1.0,-0.56,1.68,3.97,X40,NTT,FMCG
35,HDFCLIFE,1.52,-6.33,41.67,32.71,58473.0,-9476.0,140324.0,811.41,-26.88,45.0,X-LC,15.67,31.0,-0.16,0.92,5.42,X40,ATH,INSURANCE
79,TCS,1.86,-38.47,102.96,24.88,293479.0,-178231.0,285042.0,4253.91,-47.89,45.0,X-LC,21.62,2.0,-0.61,1.86,5.71,X40,ATH,IT

In [20]:
# top 5 to accumulate based on lowest CurrAlloc%
df_tmp = df_portfolio_features[df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])].sort_values(by = 'CurrAlloc%', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
10,BATAINDIA,-0.74,-55.88,206.43,35.20,117194.0,-71898.0,56772.0,2096.00,-25.63,46.0,X-SC,19.75,91.0,-0.61,0.37,12.59,X40,NTT,FOOTWEAR
64,RELAXO,-2.31,-49.30,200.38,52.31,147484.0,-71558.0,73602.0,1176.00,-45.99,60.0,X-SC,11.39,92.0,-0.49,0.48,64.56,X40N,NTT,FOOTWEAR
60,QUESS,1.65,22.39,42.09,73.90,55011.0,23906.0,130699.0,424.00,-34.44,87.0,X-SC,22.01,80.0,0.43,0.85,78.17,XY24,NTT,MISC
35,HDFCLIFE,1.52,-6.33,41.67,32.71,58473.0,-9476.0,140324.0,811.41,-26.88,45.0,X-LC,15.67,31.0,-0.16,0.92,5.42,X40,ATH,INSURANCE
51,KOTAKBANK,0.22,2.11,18.60,21.11,26300.0,2924.0,141396.0,453.24,-12.44,40.0,X-LC,4.27,12.0,0.11,0.92,8.14,X40,ATH,BANKS

In [21]:
# top 5 to accumulate based on CumlRnk
df_tmp = df_portfolio_features.sort_values(by = 'CumlRnk', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
47,ITC,-0.09,-24.14,56.94,19.06,146933.0,-82118.0,258048.0,452.00,-58.35,47.0,X-LC,12.68,1.0,-0.56,1.68,3.97,X40,NTT,FMCG
79,TCS,1.86,-38.47,102.96,24.88,293479.0,-178231.0,285042.0,4253.91,-47.89,45.0,X-LC,21.62,2.0,-0.61,1.86,5.71,X40,ATH,IT
45,INFY,2.85,-27.03,83.97,34.24,191716.0,-84573.0,228315.0,1972.00,-42.67,48.0,X-LC,20.91,3.0,-0.44,1.49,8.79,X40,NTT,IT
81,TMPV,-1.47,-22.16,75.46,36.58,209009.0,-78861.0,276980.0,600.00,-83.62,38.0,X-LC,7.26,4.0,-0.38,1.81,16.40,XY24,NTT,AUTO
59,PIDILITIND,0.12,14.72,3.18,18.37,5148.0,20770.0,161880.0,1670.26,-19.59,72.0,X-LC,7.82,5.0,4.03,1.06,27.10,X40,ATH,CHEMICALS

In [22]:
# top 5 for average up
df_tmp = df_portfolio_features[(df_portfolio_features['Dev%_200'] > 5)].sort_values(by = 'CurrAlloc%', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
44,INDUSINDBK,1.12,-24.61,76.28,32.89,44397.0,-19004.0,58203.0,1800.00,-373.81,73.0,L-MC,8.34,258.0,-0.43,0.38,43.49,XR,NTT,BANKS
64,RELAXO,-2.31,-49.30,200.38,52.31,147484.0,-71558.0,73602.0,1176.00,-45.99,60.0,X-SC,11.39,92.0,-0.49,0.48,64.56,X40N,NTT,FOOTWEAR
3,ALKYLAMINE,0.18,-23.25,150.88,92.54,116911.0,-23477.0,77486.0,4520.85,-17.74,54.0,H-SC,8.98,142.0,-0.20,0.51,47.14,SR,ATH,CHEMICALS
83,TTKPRESTIG,1.36,-17.46,21.26,0.09,17685.0,-17592.0,83185.0,770.00,93.17,71.0,M-SC,5.26,250.0,-0.99,0.54,48.12,OX40N,NTT,DURABLES
72,SIS,0.92,-1.24,22.79,21.26,24989.0,-1382.0,109650.0,528.00,2617.10,57.0,H-SC,24.98,168.0,-0.06,0.72,63.03,OX40N,NTT,MISC

In [23]:
# top 5 RSP
df_tmp = df_portfolio_features.sort_values(by = 'RSP', ascending=False)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
60,QUESS,1.65,22.39,42.09,73.90,55011.0,23906.0,130699.0,424.0,-34.44,87.0,X-SC,22.01,80.0,0.43,0.85,78.17,XY24,NTT,MISC
64,RELAXO,-2.31,-49.30,200.38,52.31,147484.0,-71558.0,73602.0,1176.0,-45.99,60.0,X-SC,11.39,92.0,-0.49,0.48,64.56,X40N,NTT,FOOTWEAR
83,TTKPRESTIG,1.36,-17.46,21.26,0.09,17685.0,-17592.0,83185.0,770.0,93.17,71.0,M-SC,5.26,250.0,-0.99,0.54,48.12,OX40N,NTT,DURABLES
49,JSWINFRA,-0.31,9.96,5.88,16.43,14339.0,22091.0,243865.0,342.0,-5.72,62.0,X-MC,11.79,61.0,1.54,1.59,38.26,X40N,NTT,REALTY
66,REPCOHOME,0.61,-7.46,105.13,89.82,278723.0,-21383.0,265122.0,880.0,-53.80,68.0,H-SC,2.22,161.0,-0.08,1.73,27.45,XY24,NTT,FINANCE

In [24]:
# Top N allocation
df_tmp = df_portfolio_features.sort_values(by = 'CurrAlloc%', ascending=False)
top_n_values = [10, 25, 50]

sum_df = pd.DataFrame({
    'Top_N': top_n_values,
    'Sum_Alloc%': [df_tmp['CurrAlloc%'].head(n).sum() for n in top_n_values]
})

sum_df

   Top_N  Sum_Alloc%
0     10       19.30
1     25       42.82
2     50       72.73

In [25]:
# market-cap-wise allocation
df_tmp = df_portfolio_features[cols]
df_tmp.groupby(df_tmp['Conviction'].str[-2:])['CurrAlloc%'].sum().sort_values(ascending=False)

Conviction
SC    43.61
LC    30.25
MC    26.16
Name: CurrAlloc%, dtype: float64

In [26]:
# criteria-wise allocation
df_portfolio_features.groupby('Criteria')['CurrAlloc%'].sum().sort_values(ascending=False)

Criteria
XY24     28.01
X40      24.69
X40N     17.37
XR        8.79
OX40N     7.09
AR        6.76
XY25      6.43
SR        0.88
Name: CurrAlloc%, dtype: float64

In [27]:
# conviction-wise allocation
df_portfolio_features.groupby('Conviction')['CurrAlloc%'].sum().sort_values(ascending=False)

Conviction
X-LC    28.33
H-SC    22.90
X-MC    21.01
M-SC    10.10
X-SC    10.03
H-MC     2.73
M-MC     2.04
H-LC     1.14
M-LC     0.78
L-SC     0.58
L-MC     0.38
Name: CurrAlloc%, dtype: float64

In [28]:
# sector-wise stats
df_tmp = df_portfolio_features.groupby('Category')[['CurrAlloc%', 'Current', 'Current P/L', 'FTT Amt']].sum().sort_values(by=['Current', 'Current P/L'], ascending=False)
df_tmp['Current P/L%'] = round(df_tmp['Current P/L'] * 100 / df_tmp['Current'], 2)
df_tmp['FTT%'] = round(df_tmp['FTT Amt'] * 100 / df_tmp['Current'], 2)
cols = ['CurrAlloc%', 'Current P/L%', 'FTT%']
df_tmp[cols].sort_values(by=['CurrAlloc%'], ascending=False)

               CurrAlloc%  Current P/L%    FTT%
Category
FMCG                14.43        -19.57   61.51
FINANCE             11.42         -5.43   51.11
IT                   9.72        -51.15  126.73
MISC                 7.20        -21.42   73.52
AUTO                 6.70         -6.57   46.30
BANKS                5.79         -2.22   49.48
PAINTS               5.50        -16.94   36.89
INSURANCE            5.30         -2.06   36.49
PHARMA               5.14          5.91   23.21
ELECTRICAL           4.07        -13.42   53.45
CHEMICALS            2.18        -21.63   93.78
HEALTHCARE           2.09        -11.59   40.72
APPARELS             1.90          7.83   23.13
AC                   1.75        -19.19   51.51
FOOTWEAR             1.72        -67.63  134.85
DURABLES             1.62        -55.79   93.69
BREWERIES            1.62          5.44   14.20
REALTY               1.59          9.06    5.88
TRAVEL               1.53        -91.57  187.50
CERAMICS             1.41        -41.26   84.18
CABLES               1.28         25.02   55.89
ENGINEERING          1.27        -24.45   81.37
REFINERIES           1.10        -19.38   49.58
CEMENT               1.08        -61.57  182.45
JEWELLERY            1.04       -100.90  170.70
ENTERTAINMENT        0.74        -70.97  172.94
TEXTILES             0.42        -43.88   84.90
HOTELS               0.41        -81.13  145.02

In [29]:
# money to be made criteria-wise
df_portfolio_features.groupby('Criteria')['FTT Amt'].agg(['sum', 'count']).sort_values(by='sum', ascending=False)

                sum  count
Criteria
XY24      3306036.0     21
X40       1895758.0     19
XR        1332108.0     13
AR        1137340.0      9
X40N      1056548.0     13
OX40N      704574.0     10
XY25       451173.0      5
SR         284616.0      2

In [30]:
# money to be made conviction-wise
df_portfolio_features.groupby('Conviction')['FTT Amt'].agg(['sum', 'count']).sort_values(by='sum', ascending=False)

                  sum  count
Conviction
H-SC        3265435.0     24
X-LC        1937343.0     21
X-MC        1499700.0     15
M-SC        1370786.0     14
X-SC        1264843.0      9
H-MC         279709.0      2
L-SC         202475.0      2
M-LC         171660.0      1
M-MC          73007.0      2
H-LC          58798.0      1
L-MC          44397.0      1

In [31]:
# money to be made criteria and conviction-wise
df_portfolio_features.groupby(['Conviction', 'Criteria'])['FTT Amt'].agg(['sum', 'count']).sort_values(by='sum', ascending=False)

                           sum  count
Conviction Criteria
X-LC       X40       1033332.0     10
H-SC       AR         951802.0      5
           XY24       930021.0      6
M-SC       XY24       808074.0      6
H-SC       XR         805064.0      7
X-SC       XY24       749131.0      4
X-MC       X40        651737.0      7
           X40N       384848.0      4
X-LC       X40N       366677.0      6
           XY24       351571.0      2
X-SC       X40N       305023.0      3
M-SC       OX40N      299077.0      5
H-SC       OX40N      293932.0      4
           SR         284616.0      2
H-MC       XY24       250164.0      1
X-MC       XY25       246040.0      2
           XY24       217075.0      2
X-SC       X40        210689.0      2
M-SC       XR         189666.0      2
M-LC       XR         171660.0      1
X-LC       XY25       155352.0      2
L-SC       OX40N      111565.0      1
           XR          90910.0      1
M-SC       AR          73969.0      1
H-LC       AR          58798.0      1
M-MC       XY25        49781.0      1
L-MC       XR          44397.0      1
X-LC       XR          30411.0      1
H-MC       AR          29545.0      1
M-MC       AR          23226.0      1

In [32]:
# notebook execution time

end_time = time.time()
execution_time = round(end_time - start_time, 0)
print(f"Notebook execution time: {execution_time} seconds")

Notebook execution time: 28.0 seconds