<a href="https://colab.research.google.com/github/ankit-rathi/Quantvesting_v2/blob/main/myStocks_Portfolio_Analysis.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
'''
!pip install pandas==2.2.2 -qq
!pip install pyxirr -qq
!pip install ta -qq
!pip install yfinance==0.2.59 -qq
'''

'\n!pip install pandas==2.2.2 -qq\n!pip install pyxirr -qq\n!pip install ta -qq\n!pip install yfinance==0.2.59 -qq\n'

In [2]:
# import libraries

import numpy as np
import pandas as pd
import datetime
import warnings
warnings.filterwarnings('ignore')
import yfinance as yfin
import ta
import matplotlib.pyplot as plt
import requests

In [3]:
# notebook start time
import time
import datetime
import pytz

start_time = time.time()

# function to print date timestamp
def print_date_time():
  tz_NY = pytz.timezone('Asia/Kolkata')
  datetime_NY = datetime.datetime.now(tz_NY)
  print("Run date time (IST):", datetime_NY.strftime("%Y-%m-%d %H:%M:%S"))

In [4]:
# function to get booked and reserved amount
def get_amt():
  # fetch the JSON data from the URL
  url = "https://raw.githubusercontent.com/ankit-rathi/Tradevesting_v1/main/data/myPortfolioAmts.json"
  response = requests.get(url)
  pf_amts = response.json()  # parse the JSON data

  # extract values from the JSON
  py_booked_amt_dm = pf_amts["py_booked_amt_dm"]
  py_booked_amt_sv = pf_amts["py_booked_amt_sv"]
  cy_booked_amt_dm = pf_amts["cy_booked_amt_dm"]
  cy_booked_amt_sv = pf_amts["cy_booked_amt_sv"]
  reserve_amt_dm = pf_amts["reserve_amt_dm"]
  reserve_amt_sv = pf_amts["reserve_amt_sv"]

  # perform calculations
  py_booked_amt = py_booked_amt_dm + py_booked_amt_sv
  cy_booked_amt = cy_booked_amt_dm + cy_booked_amt_sv
  reserve_amt = reserve_amt_dm + reserve_amt_sv
  total_booked_amt = py_booked_amt + cy_booked_amt

  return total_booked_amt, reserve_amt, cy_booked_amt, py_booked_amt

gen_output = 0

In [5]:
# function to format the amount
def format_amt(number):
    abs_number = abs(number)

    if abs_number >= 1_00_00_000:  # Crores
        formatted_amt = f"{number / 1_00_00_000:.2f} C"
    elif abs_number >= 1_00_000:  # Lakhs
        formatted_amt = f"{number / 1_00_000:.2f} L"
    elif abs_number >= 1_000:  # Thousands
        formatted_amt = f"{number / 1_000:.2f} K"
    else:
        formatted_amt = f"{number:.2f}"

    return formatted_amt

# function to set start and end date
def get_start_end_date():
  start_date = (datetime.date.today() + datetime.timedelta(days=-365)).strftime('%Y-%m-%d')
  end_date = (datetime.date.today() + datetime.timedelta(days=1)).strftime('%Y-%m-%d')
  return start_date, end_date

# function to fetch my portfolio csv
def get_mypfs_df():
  mypfs_df = pd.read_csv('https://raw.githubusercontent.com/ankit-rathi/Tradevesting_v1/main/data/myPortfolioStocks.csv')
  return mypfs_df

# function to fetch my prospects csv
def get_mypps_df():
  mypps_df = pd.read_csv('https://raw.githubusercontent.com/ankit-rathi/Tradevesting_v1/main/data/myProspectsScrips.csv')
  return mypps_df

# function to fetch screener data
def get_myscreen_df():
  myscreen_df = pd.read_csv('https://raw.githubusercontent.com/ankit-rathi/Tradevesting_v1/main/data/myScreenerDB.csv')
  return myscreen_df

# function to fetch momentum data
def get_myinvmt_df():
  myinvmt_df = pd.read_csv('https://raw.githubusercontent.com/ankit-rathi/Tradevesting_v1/main/data/myInvestments.csv')
  return myinvmt_df

# function to get the stock ids
def get_stock_ids(df_pf):
  stock_n100 = df_pf['Symbol'].unique()

  exclude = ['CADILAHC','MMTC', 'MASFIN']

  stock_ids = df_pf[~df_pf['Symbol'].isin(exclude) ]['Symbol'].unique()

  #mypf = mypf[mypf.Forecast.notnull()]
  #stock_ids = mypf['Symbol'].unique()

  #stock_ids.sort()
  return stock_ids

# get features from screener data
def get_screener_features():
  myscreen_df = get_myscreen_df()
  cols = ['Symbol', 'EPS', 'MedPE', 'ROCE%', 'ROE%', 'CapType']
  return myscreen_df[cols]

# get relative strength
def get_relative_strength(stock_list):

    # Dictionary to store stock tickers and their corresponding percentage price change
    stock_changes = {}

    # Loop through each stock and fetch its price data
    for stock in stock_list:
        try:
            # Download the stock data for the given date range
            stock_data = yfin.Ticker(stock + '.NS').history(period='1mo', interval='1d')[map(str.title, ['open', 'close', 'low', 'high', 'volume'])]

            # Calculate the percentage change for the stock
            if len(stock_data) > 0:
                start_price = stock_data['Close'].iloc[0]
                end_price = stock_data['Close'].iloc[-1]
                percent_change = round(((end_price - start_price) / start_price) * 100, 2)
                stock_changes[stock] = percent_change
            else:
                stock_changes[stock] = np.nan  # If no data is available, set to NaN

        except Exception as e:
            print(f"Error fetching data for {stock}: {e}")
            stock_changes[stock] = np.nan

    # Create a DataFrame with stock tickers and their percentage changes
    df = pd.DataFrame(list(stock_changes.items()), columns=['Symbol', 'Percent_Change'])

    # Drop any stocks with missing data (NaN values)
    df = df.dropna()

    # Calculate the percentile rank based on percentage change
    df['RSP'] = round(df['Percent_Change'].rank(pct=True) * 100, 2)
    cols = ['Symbol', 'RSP']
    df = df[cols]
    # Sort by percentile rank (optional)
    df = df.sort_values(by='RSP', ascending=False).reset_index(drop=True)

    return df

In [6]:
# function to get stock technicals
def stock_prec_dev(stock_symbol):
    #stock_symbol = 'ULTRACEMCO.NS'
    short_window = 20
    mid_window = 50
    long_window = 200
    moving_avg = 'SMA'

    start = datetime.datetime(*map(int, start_date.split('-')))
    end = datetime.datetime(*map(int, end_date.split('-')))

    stock_df = yfin.Ticker(stock_symbol + '.NS').history(period='max', interval='1d')[map(str.title, ['open', 'close', 'low', 'high', 'volume'])]

    stock_df['Max'] = round(max(stock_df['Close']),2)
    stock_df = stock_df[(stock_df.index <= end_date) & (stock_df.index >= start_date)]
    stock_df['200_SMA'] = round(stock_df['Close'].rolling(window = 200, min_periods = 1).mean(),0)
    stock_df['Dev%_200'] = round((stock_df['Close'] - stock_df['200_SMA'])*100/stock_df['200_SMA'],2)
    stock_df.dropna(axis = 0, inplace = True) # remove any null rows

    stock_df['20_SMA'] = stock_df['Close'].rolling(window=20).mean()
    stock_df['50_SMA'] = stock_df['Close'].rolling(window=50).mean()
    stock_df['Symbol'] = stock_symbol

    stock_df['Close'] = round(stock_df['Close'],2)
    stock_df['Min'] = round(min(stock_df['Close']),2)
    stock_df['RSI_14'] = ta.momentum.RSIIndicator(close=stock_df['Close'], window=14).rsi()
    stock_df['RSI_14'] = round(stock_df['RSI_14'],0)
    stock_df['Prev_Close'] = stock_df['Close'].shift(1)
    stock_df.drop(['Open', 'Low', 'High', 'Volume'], axis=1, inplace=True)
    stock_df = stock_df.tail(1)

    max_SMA = max(stock_df['20_SMA'].item(), stock_df['50_SMA'].item(), stock_df['200_SMA'].item())
    min_SMA = min(stock_df['20_SMA'].item(), stock_df['50_SMA'].item(), stock_df['200_SMA'].item())
    ABS_Spread = max_SMA - min_SMA
    stock_df['Spread%'] = round((ABS_Spread / stock_df['200_SMA'].item()) * 100,2)

    return stock_df

# function to compute stock attributes
def get_common_features(stock_ids, df_mypf):

  df_prec_dev = pd.DataFrame()
  df_tmp = get_screener_features()
  df_rs = get_relative_strength(stock_ids)

  for stock_id in stock_ids:
      tmp = stock_prec_dev(stock_id)
      tmp = tmp.reset_index()
      df_prec_dev = pd.concat([df_prec_dev, tmp], ignore_index = True)
  df_prec_dev = pd.merge(df_prec_dev, df_mypf, on= 'Symbol')
  df_prec_dev = pd.merge(df_prec_dev, df_tmp, on= 'Symbol', how='left')
  df_prec_dev = pd.merge(df_prec_dev, df_rs, on= 'Symbol', how='left')
  #print(df_prec_dev.columns)
  df_prec_dev['Curr_PE'] = round(df_prec_dev['Close']/df_prec_dev['EPS'],1)
  df_prec_dev['Dev%_PE'] = round((df_prec_dev['Curr_PE'] - df_prec_dev['MedPE'])*100/df_prec_dev['MedPE'],2)
  df_prec_dev['Conviction'] = df_prec_dev['Conviction'] + '-' + df_prec_dev['CapType']
  return df_prec_dev

# function to arrange stock features
def arrange_features(df_stocks, common_cols, diff_cols):
  df_stocks_common = df_stocks[common_cols].drop_duplicates()
  df_stocks_diff = df_stocks[diff_cols]
  df_stocks_diff['Investment'] = df_stocks_diff['AvgCost'] * df_stocks_diff['Shares']
  df_stocks_diff = df_stocks_diff.groupby(['Symbol'])[['Shares', 'Investment']].aggregate(['sum']).reset_index()
  df_stocks_diff.columns = ['Symbol', 'Shares', 'Investment']
  df_stocks_diff['AvgCost'] = round(df_stocks_diff['Investment']/df_stocks_diff['Shares'],2)
  df_stocks = pd.merge(df_stocks_diff, df_stocks_common, on='Symbol')
  return df_stocks

# plot fact distribution across dimension
def plot_pie_chart(df, dimension, fact):
  # grouping the data by category and calculating the sum of fact for each type
  grouped_data = df.groupby(dimension)[fact].sum()

  # sorting the grouped data in descending order
  grouped_data = grouped_data.sort_values(ascending=False)

  # creating a pie chart
  grouped_data.plot.pie(autopct='%1.1f%%', startangle=90, figsize=(6, 6))

  # adding a title and displaying the plot
  plt.title(f'{dimension} {fact} Distribution')
  plt.ylabel('')  # To hide the y-label
  plt.show()

In [7]:
# function to get portfolio features

def get_portfolio_features(df_common_features):

  print_date_time()
  print('-------------------')

  #df_common_features["Target"] = df_common_features["Target"].fillna(df_common_features["Max"])
  df_common_features['NTT'] = np.where(df_common_features['Strategy']== 'NTT', df_common_features["Target"], df_common_features['Max'])
  df_common_features['LTT'] = np.where(df_common_features['Strategy']== 'BTT', df_common_features["Target"], df_common_features['Max'])
  df_common_features['BOL'] = df_common_features['Min']

  tmp_df = df_common_features[df_common_features['Symbol'].isin(mypf_df[mypf_df['InPortfolio'] != 'NA'].Symbol.values)]
  print('qualified stocks: '+str(len(tmp_df['Symbol'].unique())))
  tmp_df1 = tmp_df[tmp_df['LatestQtr'] == 1]
  print('with latest results: '+str(len(tmp_df1['Symbol'].unique())))
  tmp_df1 = tmp_df1[tmp_df1['StarStock'] == 1]
  print('still star stocks: '+str(len(tmp_df1['Symbol'].unique())))
  tmp_df['Investment'] = tmp_df['AvgCost'] * tmp_df['Shares']
  tmp_df['Current'] = round(tmp_df['Close'] * tmp_df['Shares'],0)
  tmp_df['Previous'] = tmp_df['Prev_Close'] * tmp_df['Shares']
  tmp_df['EstimatedST'] = tmp_df['NTT'] * tmp_df['Shares']
  tmp_df['EstimatedLT'] = tmp_df['LTT'] * tmp_df['Shares']
  tmp_df['Current P/L'] = round((tmp_df['Current'] - tmp_df['Investment']),0)
  tmp_df['Today P/L%'] = round((tmp_df['Current'] - tmp_df['Previous'])*100/tmp_df['Previous'],2)
  tmp_df['Current P/L%'] = round((tmp_df['Current'] - tmp_df['Investment'])*100/tmp_df['Investment'],2)
  tmp_df['EstimatedST P/L%'] = round((tmp_df['EstimatedST'] - tmp_df['Investment'])*100/tmp_df['Investment'],2)
  tmp_df['EstimatedLT P/L%'] = round((tmp_df['EstimatedLT'] - tmp_df['Investment'])*100/tmp_df['Investment'],2)
  tmp_df['NTT%'] = round((tmp_df['NTT'] - tmp_df['Close'])*100/tmp_df['Close'],2)
  tmp_df['LTT%'] = round((tmp_df['LTT'] - tmp_df['Close'])*100/tmp_df['Close'],2)
  tmp_df['Gained%'] = round((tmp_df['Close'] - tmp_df['BOL'])*100/tmp_df['BOL'],2)
  investment = round(sum(tmp_df['AvgCost']*tmp_df['Shares']),0)
  current = round(sum(tmp_df['Close']*tmp_df['Shares']),0)
  tmp_df['InitAlloc%'] = round(tmp_df['Investment']*100/investment,2)
  tmp_df['CurrAlloc%'] = round(tmp_df['Current']*100/current,2)
  tmp_df['FTT'] = tmp_df['LTT']
  tmp_df.loc[tmp_df['Strategy'] == 'NTT', 'FTT'] = tmp_df['NTT']
  tmp_df['FTT%'] = tmp_df['LTT%']
  tmp_df.loc[tmp_df['Strategy'] == 'NTT', 'FTT%'] = tmp_df['NTT%']
  tmp_df['FTT Amt'] = round(tmp_df['FTT%'] * tmp_df['Current']/100,0)
  tmp_df['OTT%'] = round((tmp_df['FTT'] - tmp_df['AvgCost'])*100/tmp_df['AvgCost'],2)
  tmp_df['RRR Ind'] = round(tmp_df['Current P/L']/tmp_df['FTT Amt'],2)
  tmp_df['Risk Ind'] = round(tmp_df['Current P/L%']*tmp_df['CurrAlloc%'],0)

  return tmp_df

# function to print portfolio features
def print_portfolio_stats(df_portfolio_features, myinvmt_df):
  from pyxirr import xirr

  total_booked_amt, reserve_amt, cy_booked_amt, py_booked_amt = get_amt()

  dates = myinvmt_df['Date'].values
  dates = np.append(dates, datetime.date.today().strftime('%d-%b-%y'))
  investment = myinvmt_df['Investment'].values
  dates= pd.to_datetime(dates)

  current = round(sum(df_portfolio_features['Close']*df_portfolio_features['Shares']),0) + reserve_amt
  investment_xirr = np.append(investment, current)
  cagr = round(xirr(pd.DataFrame({"dates": dates, "amounts": investment_xirr}))*100,2)

  investment = -sum(investment)
  invested = round(sum(df_portfolio_features['AvgCost']*df_portfolio_features['Shares']),0) + reserve_amt
  previous = round(sum(df_portfolio_features['Prev_Close']*df_portfolio_features['Shares']),0) + reserve_amt
  cy_invested = investment + py_booked_amt

  today_pnl_amount = current-previous
  today_pnl_percentage = round((current-previous)*100/previous,2)

  curr_pnl_amount = current-invested
  curr_pnl_percentage = round((curr_pnl_amount)*100/(cy_invested),2)

  cy_pnl_amount = cy_booked_amt + curr_pnl_amount
  cy_pnl_percentage = round((cy_pnl_amount)*100/cy_invested,2)

  overall_pnl_amount = total_booked_amt + curr_pnl_amount
  overall_pnl_percentage = round((overall_pnl_amount)*100/investment,2)

  estimate_st = round(sum(df_portfolio_features['FTT']*df_portfolio_features['Shares']),0)  + reserve_amt
  est_st_pnl_amount = estimate_st-current
  est_st_pnl_percentage = round((est_st_pnl_amount)*100/current,2)

  estimate_lt = round(sum(df_portfolio_features['LTT']*df_portfolio_features['Shares']),0)  + reserve_amt
  est_lt_pnl_amount = estimate_lt-current
  est_lt_pnl_percentage = round((est_lt_pnl_amount)*100/current,2)

  total_profit = round(sum(df_portfolio_features[df_portfolio_features['Current P/L%'] > 0]['Current']) - sum(df_portfolio_features[df_portfolio_features['Current P/L%'] > 0]['Investment']),0)
  total_loss = round(sum(df_portfolio_features[df_portfolio_features['Current P/L%'] < 0]['Current']) - sum(df_portfolio_features[df_portfolio_features['Current P/L%'] < 0]['Investment']),0)

  cy_booked_percentage = round((cy_booked_amt)*100/current,2)
  py_booked_percentage = round((py_booked_amt)*100/investment,2)
  total_booked_percentage = round((total_booked_amt)*100/investment,2)

  print('-------------------')
  print('Initial Investment: ', format_amt(investment))
  print('CY Investment: ', format_amt(cy_invested))
  print('Reserve: ', format_amt(reserve_amt))
  print('Current: ',  format_amt(current))
  print('-------------------')
  print('Today PnL: '+ '{} ({}%)'.format(format_amt(today_pnl_amount), today_pnl_percentage))
  print('Current PnL: '+ '{} ({}%)'.format(format_amt(curr_pnl_amount), curr_pnl_percentage))
  print('CY Booked + Current PnL: '+ '{} ({}%)'.format(format_amt(cy_pnl_amount), cy_pnl_percentage))
  print('-------------------')
  print('Total profit: ', format_amt(total_profit))
  print('Total loss: ', format_amt(total_loss))
  print('-------------------')
  print('Total Booked + Current PnL: '+ '{} ({}%)'.format(format_amt(overall_pnl_amount), overall_pnl_percentage))
  print('Total Booked PnL: '+ '{} ({}%)'.format(format_amt(total_booked_amt), total_booked_percentage))
  print('Curr Year Booked PnL: '+ '{} ({}%)'.format(format_amt(cy_booked_amt), cy_booked_percentage))
  print('Prev Year Booked PnL: '+ '{} ({}%)'.format(format_amt(py_booked_amt), py_booked_percentage))
  print('===================')
  print('Est FTT: ',  format_amt(estimate_st))
  print('Est FTT PnL: '+ '{} ({}%)'.format(format_amt(est_st_pnl_amount), est_st_pnl_percentage))

  print('===================')
  print('Deployed: ', format_amt(investment))

  print('Current: ', format_amt(current))

  print('CAGR/XIRR %: '+'{}%'.format(cagr))

In [8]:
# get start and end date
start_date, end_date = get_start_end_date()

# get portfolio and prospects data
mypfs_df = get_mypfs_df()
mypps_df = get_mypps_df()
myinvmt_df = get_myinvmt_df()

# merge above datasets
mypf_df = pd.merge(mypfs_df, mypps_df, on="Symbol")

# seggregate dm and sv portfolio
dm_pf = mypf_df[mypf_df['InPortfolio'] == 'DM']
sv_pf = mypf_df[mypf_df['InPortfolio'] == 'SV']

# build portfolio stock dataframe
dm_stocks = get_stock_ids(dm_pf)
sv_stocks = get_stock_ids(sv_pf)
df_stocks = pd.concat([dm_pf,sv_pf], ignore_index = True)

# arrange common and diff stock features
common_cols = ['Symbol', 'Target', 'Criteria', 'Strategy', 'CumlRnk', 'LatestQtr', 'StarStock', 'Conviction', 'Category', 'InFolio', 'XIRR', 'MBQ']
diff_cols = ['Symbol', 'AvgCost', 'Shares']
df_stocks = arrange_features(df_stocks, common_cols, diff_cols)

# get common features
stock_ids = df_stocks['Symbol'].values
df_common_features = get_common_features(stock_ids, df_stocks)

df_common_features.reset_index(drop=True, inplace=True)
df_common_features.drop(['Date'], axis=1, inplace=True)
# get and print portfolio features
df_portfolio_features = get_portfolio_features(df_common_features)

print_portfolio_stats(df_portfolio_features, myinvmt_df)

df = df_portfolio_features
#plot_pie_chart(df, 'CapType', 'Current')
list_ox40n = list(df[df['MBQ'].str.contains('OX40N', na=False)]['Symbol'].values)

Run date time (IST): 2026-06-01 12:25:24
-------------------
qualified stocks: 92
with latest results: 31
still star stocks: 20
-------------------
Initial Investment:  1.40 C
CY Investment:  1.82 C
Reserve:  1.49 K
Current:  1.49 C
-------------------
Today PnL: -26.13 K (-0.18%)
Current PnL: -34.20 L (-18.75%)
CY Booked + Current PnL: -32.12 L (-17.61%)
-------------------
Total profit:  2.25 L
Total loss:  -36.45 L
-------------------
Total Booked + Current PnL: 10.75 L (7.71%)
Total Booked PnL: 44.95 L (32.22%)
Curr Year Booked PnL: 2.08 L (1.4%)
Prev Year Booked PnL: 42.87 L (30.73%)
===================
Est FTT:  2.55 C
Est FTT PnL: 1.06 C (71.35%)
===================
Deployed:  1.40 C
Current:  1.49 C
CAGR/XIRR %: 3.14%

In [9]:
# top 5 near their targets
cols = ['Symbol', 'Today P/L%', 'Current P/L%', 'FTT%', 'OTT%', 'FTT Amt', 'Current P/L', 'Current', 'FTT', 'Dev%_PE', 'RSI_14','Conviction', 'Spread%',  'CumlRnk', 'RRR Ind', 'CurrAlloc%', 'Gained%', 'Criteria', 'Strategy', 'Category']
df_tmp = df_portfolio_features[~df_portfolio_features['Symbol'].isin(['ENRIN','BLUSPRING','DIGITIDE'])]
df_tmp = df_tmp.sort_values(by = 'FTT Amt', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
59,PIDILITIND,-1.38,3.63,14.22,18.37,20794.0,5120.0,146230.0,1670.26,-27.42,56.0,X-LC,4.84,5.0,0.25,0.98,14.82,X40,ATH,CHEMICALS
55,MASFIN,-0.44,-5.82,29.08,21.57,26835.0,-5700.0,92280.0,397.04,-18.70,41.0,H-SC,3.37,167.0,-0.21,0.62,9.99,XR,ATH,FINANCE
51,KOTAKBANK,-1.25,1.38,19.46,21.11,27318.0,1906.0,140378.0,453.24,-12.87,47.0,X-LC,7.30,12.0,0.07,0.94,7.36,X40,ATH,BANKS
72,SIS,1.49,-6.11,29.16,21.26,30398.0,-6788.0,104244.0,528.00,2482.90,68.0,H-SC,18.42,168.0,-0.22,0.70,55.00,OX40N,NTT,MISC
83,TTKPRESTIG,-0.49,-30.22,43.43,0.09,30543.0,-30450.0,70327.0,770.00,63.29,56.0,M-SC,15.32,250.0,-1.00,0.47,25.23,OX40N,NTT,DURABLES

In [10]:
# top 5 today
df_tmp = df_portfolio_features.sort_values(by = 'Today P/L%', ascending=False)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
18,COFFEEDAY,9.98,-35.32,109.15,35.27,80160.0,-40109.0,73440.0,80.0,-49.70,87.0,L-SC,24.21,266.0,-0.50,0.49,81.11,XR,NTT,HOTELS
68,SATIN,4.67,26.34,20.18,51.83,70442.0,72784.0,349068.0,274.0,13.01,69.0,H-SC,37.80,159.0,1.03,2.34,70.05,XY24,NTT,FINANCE
45,INFY,4.63,-17.32,62.36,34.24,161332.0,-54178.0,258710.0,1972.0,-35.05,57.0,X-LC,18.61,3.0,-0.34,1.74,10.92,X40,NTT,IT
13,BSOFT,4.27,-39.63,149.76,50.79,127169.0,-55738.0,84915.0,831.7,-22.69,46.0,H-SC,12.80,172.0,-0.44,0.57,7.56,XR,ATH,IT
85,VAIBHAVGBL,3.86,-28.63,125.27,60.77,163405.0,-52333.0,130442.0,521.0,50.41,58.0,H-SC,5.65,160.0,-0.32,0.88,31.89,XR,NTT,JEWELLERY

In [11]:
# bottom 5 today
df_tmp = df_portfolio_features.sort_values(by = 'Today P/L%', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
25,FINCABLES,-7.72,32.81,56.55,107.91,110888.0,48444.0,196088.0,1641.55,19.23,51.0,M-SC,27.77,220.0,0.44,1.32,47.52,OX40N,ATH,CABLES
61,RAJESHEXPO,-5.00,-78.28,360.77,0.07,107477.0,-107386.0,29791.0,518.00,992.17,47.0,L-SC,31.55,268.0,-1.00,0.20,39.86,OX40N,NTT,JEWELLERY
52,LAOPALA,-4.41,-48.61,170.66,39.09,114977.0,-63733.0,67372.0,464.00,47.14,44.0,H-SC,15.78,154.0,-0.55,0.45,4.53,AR,NTT,CERAMICS
20,DABUR,-2.93,-15.85,70.77,43.70,147728.0,-39324.0,208744.0,735.00,-23.72,35.0,X-MC,9.80,70.0,-0.27,1.40,4.86,XY24,BTT,FMCG
86,VALIANTORG,-2.78,-39.95,190.02,74.15,186681.0,-65362.0,98243.0,838.00,-276.54,52.0,H-SC,8.28,145.0,-0.35,0.66,46.20,XR,NTT,CHEMICALS

In [12]:
# top 5 to exit based on CumlRnk
df_tmp = df_portfolio_features[~df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])]
df_tmp = df_tmp[(df_tmp['Current P/L%'] > -1) & (df_tmp['Current P/L%'] < 1)].sort_values(by = 'CumlRnk', ascending=False)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
9,BANDHANBNK,-0.31,-0.11,92.62,92.42,257728.0,-295.0,278264.0,400.0,138.51,67.0,H-SC,21.19,174.0,-0.0,1.87,53.29,XY24,NTT,BANKS

In [13]:
# OX40N stocks to exit
df_tmp = df_portfolio_features[(df_portfolio_features['Symbol'].isin(list_ox40n))].sort_values(by = 'Current P/L%', ascending=False)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
25,FINCABLES,-7.72,32.81,56.55,107.91,110888.0,48444.0,196088.0,1641.55,19.23,51.0,M-SC,27.77,220.0,0.44,1.32,47.52,OX40N,ATH,CABLES
72,SIS,1.49,-6.11,29.16,21.26,30398.0,-6788.0,104244.0,528.00,2482.90,68.0,H-SC,18.42,168.0,-0.22,0.70,55.00,OX40N,NTT,MISC
16,CERA,0.11,-27.16,70.09,23.89,89801.0,-47781.0,128122.0,9475.00,-29.83,50.0,H-SC,7.02,153.0,-0.53,0.86,23.12,OX40N,NTT,CERAMICS
43,INDIGOPNTS,3.45,-27.18,37.36,0.02,47487.0,-47453.0,127106.0,1408.00,93.64,68.0,M-SC,16.80,222.0,-1.00,0.85,44.21,OX40N,NTT,PAINTS
50,KANSAINER,-0.11,-27.30,56.09,13.47,109958.0,-73629.0,196038.0,340.00,-37.50,61.0,H-SC,11.58,162.0,-0.67,1.32,36.93,XY24,NTT,PAINTS

In [14]:
# top 5 to book for rotation
df_tmp = df_portfolio_features[(df_portfolio_features['Current P/L%'] > 20) ].sort_values(by = 'CumlRnk', ascending=False)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
25,FINCABLES,-7.72,32.81,56.55,107.91,110888.0,48444.0,196088.0,1641.55,19.23,51.0,M-SC,27.77,220.0,0.44,1.32,47.52,OX40N,ATH,CABLES
68,SATIN,4.67,26.34,20.18,51.83,70442.0,72784.0,349068.0,274.00,13.01,69.0,H-SC,37.80,159.0,1.03,2.34,70.05,XY24,NTT,FINANCE

In [15]:
# top 5 to monitor for exit
df_tmp = df_portfolio_features[~df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])]
df_tmp = df_tmp[(df_tmp['Current P/L%'] > 0) ].sort_values(by = 'Dev%_PE', ascending=False)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
74,STARHEALTH,-0.32,1.83,44.61,47.26,127710.0,5157.0,286280.0,761.00,60.64,61.0,H-SC,9.68,173.0,0.04,1.92,25.69,XY24,NTT,INSURANCE
25,FINCABLES,-7.72,32.81,56.55,107.91,110888.0,48444.0,196088.0,1641.55,19.23,51.0,M-SC,27.77,220.0,0.44,1.32,47.52,OX40N,ATH,CABLES
68,SATIN,4.67,26.34,20.18,51.83,70442.0,72784.0,349068.0,274.00,13.01,69.0,H-SC,37.80,159.0,1.03,2.34,70.05,XY24,NTT,FINANCE
91,ZYDUSLIFE,2.30,16.26,16.66,35.63,40592.0,34078.0,243652.0,1286.17,1.35,76.0,H-MC,6.14,120.0,0.84,1.64,28.11,AR,ATH,PHARMA
73,SONACOMS,-0.50,4.56,33.03,39.09,34936.0,4611.0,105770.0,804.02,-17.09,58.0,M-MC,18.86,193.0,0.13,0.71,49.63,AR,ATH,AUTO

In [16]:
# top 5 to book for rotation from weak conviction
df_tmp = df_portfolio_features[~df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])]
df_tmp = df_tmp[~df_tmp['Criteria'].isin(['XY25','XY24','X40', 'X40N'])].sort_values(by = 'RRR Ind', ascending=False)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
91,ZYDUSLIFE,2.30,16.26,16.66,35.63,40592.0,34078.0,243652.0,1286.17,1.35,76.0,H-MC,6.14,120.0,0.84,1.64,28.11,AR,ATH,PHARMA
25,FINCABLES,-7.72,32.81,56.55,107.91,110888.0,48444.0,196088.0,1641.55,19.23,51.0,M-SC,27.77,220.0,0.44,1.32,47.52,OX40N,ATH,CABLES
73,SONACOMS,-0.50,4.56,33.03,39.09,34936.0,4611.0,105770.0,804.02,-17.09,58.0,M-MC,18.86,193.0,0.13,0.71,49.63,AR,ATH,AUTO
42,INDIAMART,-1.43,-14.62,142.13,106.72,149663.0,-18036.0,105300.0,4810.62,-61.52,39.0,H-SC,10.97,140.0,-0.12,0.71,1.94,AR,ATH,MISC
75,SURYODAY,2.15,-4.82,29.26,23.03,49871.0,-8629.0,170442.0,216.00,86.40,61.0,H-SC,18.94,166.0,-0.17,1.14,43.51,XR,NTT,BANKS

In [17]:
# top 5 to accumulate based on lowest RSI_14
df_tmp = df_portfolio_features[df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])].sort_values(by = 'RSI_14', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
27,GLAXO,-0.90,-12.08,58.26,39.15,102081.0,-24068.0,175216.0,3466.20,-32.93,27.0,X-MC,6.89,56.0,-0.24,1.18,0.00,X40,ATH,PHARMA
47,ITC,-0.94,-25.14,59.04,19.06,150341.0,-85523.0,254643.0,452.00,-58.75,32.0,X-LC,14.52,1.0,-0.57,1.71,1.47,X40,NTT,FMCG
36,HINDUNILVR,-1.77,-17.71,38.13,13.67,80660.0,-45523.0,211540.0,2922.00,-38.84,33.0,X-LC,7.06,9.0,-0.56,1.42,3.08,XY25,NTT,FMCG
10,BATAINDIA,0.04,-56.83,213.21,35.20,118425.0,-73126.0,55544.0,2096.00,-27.22,34.0,X-SC,24.88,91.0,-0.62,0.37,10.16,X40,NTT,FOOTWEAR
32,HAVELLS,-1.35,-25.67,76.81,31.42,187254.0,-84202.0,243789.0,2052.62,-30.08,34.0,X-MC,12.92,63.0,-0.45,1.64,0.00,X40,ATH,ELECTRICAL

In [18]:
# top 5 to accumulate based on Spread and CumlRnk
df_tmp = df_portfolio_features[df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])]
df_tmp = df_tmp[(df_tmp['CumlRnk'] < 100)].sort_values(by = 'Spread%', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
23,DMART,0.43,-2.12,32.41,29.60,79180.0,-5292.0,244308.0,5391.45,-17.46,34.0,X-LC,3.19,14.0,-0.07,1.64,11.67,X40N,ATH,FMCG
65,RELIANCE,0.13,-15.08,47.55,25.30,81146.0,-30309.0,170654.0,1952.00,-17.34,39.0,X-LC,4.16,21.0,-0.37,1.15,1.40,XY25,BTT,REFINERIES
49,JSWINFRA,-0.74,-6.98,25.16,16.43,51906.0,-15470.0,206304.0,342.00,-20.31,51.0,X-MC,4.65,61.0,-0.30,1.38,16.62,X40N,NTT,REALTY
84,UNITDSPR,-0.63,-7.29,30.27,20.77,65705.0,-17080.0,217064.0,1644.00,-17.72,41.0,X-MC,4.66,64.0,-0.26,1.46,3.54,X40N,NTT,BREWERIES
59,PIDILITIND,-1.38,3.63,14.22,18.37,20794.0,5120.0,146230.0,1670.26,-27.42,56.0,X-LC,4.84,5.0,0.25,0.98,14.82,X40,ATH,CHEMICALS

In [19]:
# top 5 to accumulate based on lowest Gained%
df_tmp = df_portfolio_features[df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])].sort_values(by = 'Gained%', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
27,GLAXO,-0.90,-12.08,58.26,39.15,102081.0,-24068.0,175216.0,3466.20,-32.93,27.0,X-MC,6.89,56.0,-0.24,1.18,0.00,X40,ATH,PHARMA
32,HAVELLS,-1.35,-25.67,76.81,31.42,187254.0,-84202.0,243789.0,2052.62,-30.08,34.0,X-MC,12.92,63.0,-0.45,1.64,0.00,X40,ATH,ELECTRICAL
40,ICICIPRULI,-1.52,-17.87,59.18,30.73,95750.0,-35211.0,161794.0,790.00,-39.94,34.0,X-MC,11.97,78.0,-0.37,1.09,0.00,X40,ATH,INSURANCE
65,RELIANCE,0.13,-15.08,47.55,25.30,81146.0,-30309.0,170654.0,1952.00,-17.34,39.0,X-LC,4.16,21.0,-0.37,1.15,1.40,XY25,BTT,REFINERIES
47,ITC,-0.94,-25.14,59.04,19.06,150341.0,-85523.0,254643.0,452.00,-58.75,32.0,X-LC,14.52,1.0,-0.57,1.71,1.47,X40,NTT,FMCG

In [20]:
# top 5 to accumulate based on lowest CurrAlloc%
df_tmp = df_portfolio_features[df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])].sort_values(by = 'CurrAlloc%', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
10,BATAINDIA,0.04,-56.83,213.21,35.20,118425.0,-73126.0,55544.0,2096.00,-27.22,34.0,X-SC,24.88,91.0,-0.62,0.37,10.16,X40,NTT,FOOTWEAR
64,RELAXO,-2.78,-56.52,250.31,52.31,157976.0,-82048.0,63112.0,1176.00,-53.73,69.0,X-SC,23.84,92.0,-0.52,0.42,41.11,X40N,NTT,FOOTWEAR
60,QUESS,-2.43,-16.33,107.84,73.90,96357.0,-17441.0,89352.0,424.00,-54.82,50.0,X-SC,9.06,80.0,-0.18,0.60,21.81,XY24,NTT,MISC
53,M&M,-1.73,-2.88,27.04,23.38,36419.0,-3996.0,134685.0,3802.40,-17.57,38.0,X-LC,8.81,25.0,-0.11,0.90,2.11,X40N,ATH,AUTO
28,GODREJCP,-1.25,-9.04,44.53,31.47,60196.0,-13433.0,135181.0,1469.04,-4.32,43.0,X-LC,9.02,32.0,-0.22,0.91,3.72,X40N,ATH,FMCG

In [21]:
# top 5 to accumulate based on CumlRnk
df_tmp = df_portfolio_features.sort_values(by = 'CumlRnk', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
47,ITC,-0.94,-25.14,59.04,19.06,150341.0,-85523.0,254643.0,452.00,-58.75,32.0,X-LC,14.52,1.0,-0.57,1.71,1.47,X40,NTT,FMCG
79,TCS,3.24,-31.54,82.41,24.88,261365.0,-146121.0,317152.0,4253.91,-41.99,50.0,X-LC,17.96,2.0,-0.56,2.13,5.24,X40,ATH,IT
45,INFY,4.63,-17.32,62.36,34.24,161332.0,-54178.0,258710.0,1972.00,-35.05,57.0,X-LC,18.61,3.0,-0.34,1.74,10.92,X40,NTT,IT
81,TMPV,-1.22,-11.43,54.20,36.58,170823.0,-40670.0,315171.0,600.00,-81.44,65.0,X-LC,20.25,4.0,-0.24,2.12,31.36,XY24,NTT,AUTO
59,PIDILITIND,-1.38,3.63,14.22,18.37,20794.0,5120.0,146230.0,1670.26,-27.42,56.0,X-LC,4.84,5.0,0.25,0.98,14.82,X40,ATH,CHEMICALS

In [22]:
# top 5 for average up
df_tmp = df_portfolio_features[(df_portfolio_features['Dev%_200'] > 5)].sort_values(by = 'CurrAlloc%', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
44,INDUSINDBK,-0.39,-32.76,97.64,32.89,50688.0,-25294.0,51913.0,1800.00,-344.40,53.0,L-MC,8.67,258.0,-0.50,0.35,27.78,XR,NTT,BANKS
18,COFFEEDAY,9.98,-35.32,109.15,35.27,80160.0,-40109.0,73440.0,80.00,-49.70,87.0,L-SC,24.21,266.0,-0.50,0.49,81.11,XR,NTT,HOTELS
72,SIS,1.49,-6.11,29.16,21.26,30398.0,-6788.0,104244.0,528.00,2482.90,68.0,H-SC,18.42,168.0,-0.22,0.70,55.00,OX40N,NTT,MISC
73,SONACOMS,-0.50,4.56,33.03,39.09,34936.0,4611.0,105770.0,804.02,-17.09,58.0,M-MC,18.86,193.0,0.13,0.71,49.63,AR,ATH,AUTO
75,SURYODAY,2.15,-4.82,29.26,23.03,49871.0,-8629.0,170442.0,216.00,86.40,61.0,H-SC,18.94,166.0,-0.17,1.14,43.51,XR,NTT,BANKS

In [23]:
# top 5 RSP
df_tmp = df_portfolio_features.sort_values(by = 'RSP', ascending=False)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
18,COFFEEDAY,9.98,-35.32,109.15,35.27,80160.0,-40109.0,73440.0,80.00,-49.70,87.0,L-SC,24.21,266.0,-0.50,0.49,81.11,XR,NTT,HOTELS
68,SATIN,4.67,26.34,20.18,51.83,70442.0,72784.0,349068.0,274.00,13.01,69.0,H-SC,37.80,159.0,1.03,2.34,70.05,XY24,NTT,FINANCE
91,ZYDUSLIFE,2.30,16.26,16.66,35.63,40592.0,34078.0,243652.0,1286.17,1.35,76.0,H-MC,6.14,120.0,0.84,1.64,28.11,AR,ATH,PHARMA
69,SFL,1.68,-39.47,109.22,26.63,173342.0,-103509.0,158709.0,1287.00,20.23,60.0,M-SC,9.41,242.0,-0.60,1.07,32.28,XY24,NTT,MISC
43,INDIGOPNTS,3.45,-27.18,37.36,0.02,47487.0,-47453.0,127106.0,1408.00,93.64,68.0,M-SC,16.80,222.0,-1.00,0.85,44.21,OX40N,NTT,PAINTS

In [24]:
# Top N allocation
df_tmp = df_portfolio_features.sort_values(by = 'CurrAlloc%', ascending=False)
top_n_values = [10, 25, 50]

sum_df = pd.DataFrame({
    'Top_N': top_n_values,
    'Sum_Alloc%': [df_tmp['CurrAlloc%'].head(n).sum() for n in top_n_values]
})

sum_df

   Top_N  Sum_Alloc%
0     10       19.70
1     25       42.82
2     50       72.75

In [25]:
# market-cap-wise allocation
df_tmp = df_portfolio_features[cols]
df_tmp.groupby(df_tmp['Conviction'].str[-2:])['CurrAlloc%'].sum().sort_values(ascending=False)

Conviction
SC    43.07
LC    31.58
MC    25.41
Name: CurrAlloc%, dtype: float64

In [26]:
# criteria-wise allocation
df_portfolio_features.groupby('Criteria')['CurrAlloc%'].sum().sort_values(ascending=False)

Criteria
XY24     27.59
X40      25.16
X40N     16.96
XR        9.16
OX40N     7.02
AR        6.94
XY25      6.41
SR        0.82
Name: CurrAlloc%, dtype: float64

In [27]:
# conviction-wise allocation
df_portfolio_features.groupby('Conviction')['CurrAlloc%'].sum().sort_values(ascending=False)

Conviction
X-LC    29.35
H-SC    22.61
X-MC    20.35
M-SC     9.97
X-SC     9.80
H-MC     2.76
M-MC     1.95
H-LC     1.26
M-LC     0.97
L-SC     0.69
L-MC     0.35
Name: CurrAlloc%, dtype: float64

In [28]:
# sector-wise stats
df_tmp = df_portfolio_features.groupby('Category')[['CurrAlloc%', 'Current', 'Current P/L', 'FTT Amt']].sum().sort_values(by=['Current', 'Current P/L'], ascending=False)
df_tmp['Current P/L%'] = round(df_tmp['Current P/L'] * 100 / df_tmp['Current'], 2)
df_tmp['FTT%'] = round(df_tmp['FTT Amt'] * 100 / df_tmp['Current'], 2)
cols = ['CurrAlloc%', 'Current P/L%', 'FTT%']
df_tmp[cols].sort_values(by=['CurrAlloc%'], ascending=False)

               CurrAlloc%  Current P/L%    FTT%
Category
FMCG                14.88        -19.45   61.36
FINANCE             10.83        -14.28   63.98
IT                  10.58        -43.17  114.75
MISC                 6.93        -30.19   86.74
AUTO                 6.84         -7.48   47.77
BANKS                5.71         -6.78   56.15
PAINTS               5.64        -17.28   37.65
INSURANCE            5.23         -6.18   42.32
PHARMA               5.06          1.53   30.12
ELECTRICAL           4.09        -15.95   56.87
CHEMICALS            2.11        -29.12  106.06
HEALTHCARE           2.01        -19.87   51.15
AC                   1.78        -20.82   53.59
APPARELS             1.77         -1.81   36.00
FOOTWEAR             1.75        -68.69  136.33
DURABLES             1.59        -63.18  102.88
TRAVEL               1.58        -89.91  185.00
BREWERIES            1.46         -7.87   30.27
REALTY               1.38         -7.50   25.16
CABLES               1.32         24.71   56.55
CERAMICS             1.31        -57.04  104.75
ENGINEERING          1.24        -31.49   91.63
REFINERIES           1.15        -17.76   47.55
CEMENT               1.12        -61.40  182.14
JEWELLERY            1.08        -99.68  169.06
ENTERTAINMENT        0.72        -80.63  188.36
HOTELS               0.49        -54.61  109.15
TEXTILES             0.41        -51.52   94.73

In [29]:
# money to be made criteria-wise
df_portfolio_features.groupby('Criteria')['FTT Amt'].agg(['sum', 'count']).sort_values(by='sum', ascending=False)

                sum  count
Criteria
XY24      3491485.0     21
X40       1943886.0     19
XR        1318677.0     13
X40N      1197201.0     13
AR        1150701.0      9
OX40N      746359.0     10
XY25       483105.0      5
SR         297909.0      2

In [30]:
# money to be made conviction-wise
df_portfolio_features.groupby('Conviction')['FTT Amt'].agg(['sum', 'count']).sort_values(by='sum', ascending=False)

                  sum  count
Conviction
H-SC        3420615.0     24
X-LC        1919407.0     21
X-MC        1696103.0     15
M-SC        1434456.0     14
X-SC        1344279.0      9
H-MC         286944.0      2
L-SC         187637.0      2
M-LC         148080.0      1
M-MC          95923.0      2
L-MC          50688.0      1
H-LC          45191.0      1

In [31]:
# money to be made criteria and conviction-wise
df_portfolio_features.groupby(['Conviction', 'Criteria'])['FTT Amt'].agg(['sum', 'count']).sort_values(by='sum', ascending=False)

                           sum  count
Conviction Criteria
H-SC       XY24      1046174.0      6
X-LC       X40       1018173.0     10
H-SC       AR         953152.0      5
M-SC       XY24       848726.0      6
X-SC       XY24       803440.0      4
H-SC       XR         802955.0      7
X-MC       X40        714977.0      7
           X40N       494026.0      4
X-LC       X40N       373072.0      6
X-SC       X40N       330103.0      3
H-SC       OX40N      320425.0      4
X-LC       XY24       320005.0      2
M-SC       OX40N      318457.0      5
H-SC       SR         297909.0      2
X-MC       XY25       260312.0      2
H-MC       XY24       246352.0      1
X-MC       XY24       226788.0      2
X-SC       X40        210736.0      2
M-SC       XR         190443.0      2
X-LC       XY25       161806.0      2
M-LC       XR         148080.0      1
L-SC       OX40N      107477.0      1
           XR          80160.0      1
M-SC       AR          76830.0      1
M-MC       XY25        60987.0      1
L-MC       XR          50688.0      1
X-LC       XR          46351.0      1
H-LC       AR          45191.0      1
H-MC       AR          40592.0      1
M-MC       AR          34936.0      1

In [32]:
# notebook execution time

end_time = time.time()
execution_time = round(end_time - start_time, 0)
print(f"Notebook execution time: {execution_time} seconds")

Notebook execution time: 25.0 seconds