<a href="https://colab.research.google.com/github/ankit-rathi/Quantvesting_v2/blob/main/myStocks_Portfolio_Analysis.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
'''
!pip install pandas==2.2.2 -qq
!pip install pyxirr -qq
!pip install ta -qq
!pip install yfinance==0.2.59 -qq
'''

'\n!pip install pandas==2.2.2 -qq\n!pip install pyxirr -qq\n!pip install ta -qq\n!pip install yfinance==0.2.59 -qq\n'

In [2]:
# import libraries

import numpy as np
import pandas as pd
import datetime
import warnings
warnings.filterwarnings('ignore')
import yfinance as yfin
import ta
import matplotlib.pyplot as plt
import requests

In [3]:
# notebook start time
import time
import datetime
import pytz

start_time = time.time()

# function to print date timestamp
def print_date_time():
  tz_NY = pytz.timezone('Asia/Kolkata')
  datetime_NY = datetime.datetime.now(tz_NY)
  print("Run date time (IST):", datetime_NY.strftime("%Y-%m-%d %H:%M:%S"))

In [4]:
# function to get booked and reserved amount
def get_amt():
  # fetch the JSON data from the URL
  url = "https://raw.githubusercontent.com/ankit-rathi/Tradevesting_v1/main/data/myPortfolioAmts.json"
  response = requests.get(url)
  pf_amts = response.json()  # parse the JSON data

  # extract values from the JSON
  py_booked_amt_dm = pf_amts["py_booked_amt_dm"]
  py_booked_amt_sv = pf_amts["py_booked_amt_sv"]
  cy_booked_amt_dm = pf_amts["cy_booked_amt_dm"]
  cy_booked_amt_sv = pf_amts["cy_booked_amt_sv"]
  reserve_amt_dm = pf_amts["reserve_amt_dm"]
  reserve_amt_sv = pf_amts["reserve_amt_sv"]

  # perform calculations
  py_booked_amt = py_booked_amt_dm + py_booked_amt_sv
  cy_booked_amt = cy_booked_amt_dm + cy_booked_amt_sv
  reserve_amt = reserve_amt_dm + reserve_amt_sv
  total_booked_amt = py_booked_amt + cy_booked_amt

  return total_booked_amt, reserve_amt, cy_booked_amt, py_booked_amt

gen_output = 0

In [5]:
# function to format the amount
def format_amt(number):
    abs_number = abs(number)

    if abs_number >= 1_00_00_000:  # Crores
        formatted_amt = f"{number / 1_00_00_000:.2f} C"
    elif abs_number >= 1_00_000:  # Lakhs
        formatted_amt = f"{number / 1_00_000:.2f} L"
    elif abs_number >= 1_000:  # Thousands
        formatted_amt = f"{number / 1_000:.2f} K"
    else:
        formatted_amt = f"{number:.2f}"

    return formatted_amt

# function to set start and end date
def get_start_end_date():
  start_date = (datetime.date.today() + datetime.timedelta(days=-365)).strftime('%Y-%m-%d')
  end_date = (datetime.date.today() + datetime.timedelta(days=1)).strftime('%Y-%m-%d')
  return start_date, end_date

# function to fetch my portfolio csv
def get_mypfs_df():
  mypfs_df = pd.read_csv('https://raw.githubusercontent.com/ankit-rathi/Tradevesting_v1/main/data/myPortfolioStocks.csv')
  return mypfs_df

# function to fetch my prospects csv
def get_mypps_df():
  mypps_df = pd.read_csv('https://raw.githubusercontent.com/ankit-rathi/Tradevesting_v1/main/data/myProspectsScrips.csv')
  return mypps_df

# function to fetch screener data
def get_myscreen_df():
  myscreen_df = pd.read_csv('https://raw.githubusercontent.com/ankit-rathi/Tradevesting_v1/main/data/myScreenerDB.csv')
  return myscreen_df

# function to fetch momentum data
def get_myinvmt_df():
  myinvmt_df = pd.read_csv('https://raw.githubusercontent.com/ankit-rathi/Tradevesting_v1/main/data/myInvestments.csv')
  return myinvmt_df

# function to get the stock ids
def get_stock_ids(df_pf):
  stock_n100 = df_pf['Symbol'].unique()

  exclude = ['CADILAHC','MMTC', 'MASFIN']

  stock_ids = df_pf[~df_pf['Symbol'].isin(exclude) ]['Symbol'].unique()

  #mypf = mypf[mypf.Forecast.notnull()]
  #stock_ids = mypf['Symbol'].unique()

  #stock_ids.sort()
  return stock_ids

# get features from screener data
def get_screener_features():
  myscreen_df = get_myscreen_df()
  cols = ['Symbol', 'EPS', 'MedPE', 'ROCE%', 'ROE%', 'CapType']
  return myscreen_df[cols]

# get relative strength
def get_relative_strength(stock_list):

    # Dictionary to store stock tickers and their corresponding percentage price change
    stock_changes = {}

    # Loop through each stock and fetch its price data
    for stock in stock_list:
        try:
            # Download the stock data for the given date range
            stock_data = yfin.Ticker(stock + '.NS').history(period='1mo', interval='1d')[map(str.title, ['open', 'close', 'low', 'high', 'volume'])]

            # Calculate the percentage change for the stock
            if len(stock_data) > 0:
                start_price = stock_data['Close'].iloc[0]
                end_price = stock_data['Close'].iloc[-1]
                percent_change = round(((end_price - start_price) / start_price) * 100, 2)
                stock_changes[stock] = percent_change
            else:
                stock_changes[stock] = np.nan  # If no data is available, set to NaN

        except Exception as e:
            print(f"Error fetching data for {stock}: {e}")
            stock_changes[stock] = np.nan

    # Create a DataFrame with stock tickers and their percentage changes
    df = pd.DataFrame(list(stock_changes.items()), columns=['Symbol', 'Percent_Change'])

    # Drop any stocks with missing data (NaN values)
    df = df.dropna()

    # Calculate the percentile rank based on percentage change
    df['RSP'] = round(df['Percent_Change'].rank(pct=True) * 100, 2)
    cols = ['Symbol', 'RSP']
    df = df[cols]
    # Sort by percentile rank (optional)
    df = df.sort_values(by='RSP', ascending=False).reset_index(drop=True)

    return df

In [6]:
# function to get stock technicals
def stock_prec_dev(stock_symbol):
    #stock_symbol = 'ULTRACEMCO.NS'
    short_window = 20
    mid_window = 50
    long_window = 200
    moving_avg = 'SMA'

    start = datetime.datetime(*map(int, start_date.split('-')))
    end = datetime.datetime(*map(int, end_date.split('-')))

    stock_df = yfin.Ticker(stock_symbol + '.NS').history(period='max', interval='1d')[map(str.title, ['open', 'close', 'low', 'high', 'volume'])]

    stock_df['Max'] = round(max(stock_df['Close']),2)
    stock_df = stock_df[(stock_df.index <= end_date) & (stock_df.index >= start_date)]
    stock_df['200_SMA'] = round(stock_df['Close'].rolling(window = 200, min_periods = 1).mean(),0)
    stock_df['Dev%_200'] = round((stock_df['Close'] - stock_df['200_SMA'])*100/stock_df['200_SMA'],2)
    stock_df.dropna(axis = 0, inplace = True) # remove any null rows

    stock_df['20_SMA'] = stock_df['Close'].rolling(window=20).mean()
    stock_df['50_SMA'] = stock_df['Close'].rolling(window=50).mean()
    stock_df['Symbol'] = stock_symbol

    stock_df['Close'] = round(stock_df['Close'],2)
    stock_df['Min'] = round(min(stock_df['Close']),2)
    stock_df['RSI_14'] = ta.momentum.RSIIndicator(close=stock_df['Close'], window=14).rsi()
    stock_df['RSI_14'] = round(stock_df['RSI_14'],0)
    stock_df['Prev_Close'] = stock_df['Close'].shift(1)
    stock_df.drop(['Open', 'Low', 'High', 'Volume'], axis=1, inplace=True)
    stock_df = stock_df.tail(1)

    max_SMA = max(stock_df['20_SMA'].item(), stock_df['50_SMA'].item(), stock_df['200_SMA'].item())
    min_SMA = min(stock_df['20_SMA'].item(), stock_df['50_SMA'].item(), stock_df['200_SMA'].item())
    ABS_Spread = max_SMA - min_SMA
    stock_df['Spread%'] = round((ABS_Spread / stock_df['200_SMA'].item()) * 100,2)

    return stock_df

# function to compute stock attributes
def get_common_features(stock_ids, df_mypf):

  df_prec_dev = pd.DataFrame()
  df_tmp = get_screener_features()
  df_rs = get_relative_strength(stock_ids)

  for stock_id in stock_ids:
      tmp = stock_prec_dev(stock_id)
      tmp = tmp.reset_index()
      df_prec_dev = pd.concat([df_prec_dev, tmp], ignore_index = True)
  df_prec_dev = pd.merge(df_prec_dev, df_mypf, on= 'Symbol')
  df_prec_dev = pd.merge(df_prec_dev, df_tmp, on= 'Symbol', how='left')
  df_prec_dev = pd.merge(df_prec_dev, df_rs, on= 'Symbol', how='left')
  #print(df_prec_dev.columns)
  df_prec_dev['Curr_PE'] = round(df_prec_dev['Close']/df_prec_dev['EPS'],1)
  df_prec_dev['Dev%_PE'] = round((df_prec_dev['Curr_PE'] - df_prec_dev['MedPE'])*100/df_prec_dev['MedPE'],2)
  df_prec_dev['Conviction'] = df_prec_dev['Conviction'] + '-' + df_prec_dev['CapType']
  return df_prec_dev

# function to arrange stock features
def arrange_features(df_stocks, common_cols, diff_cols):
  df_stocks_common = df_stocks[common_cols].drop_duplicates()
  df_stocks_diff = df_stocks[diff_cols]
  df_stocks_diff['Investment'] = df_stocks_diff['AvgCost'] * df_stocks_diff['Shares']
  df_stocks_diff = df_stocks_diff.groupby(['Symbol'])[['Shares', 'Investment']].aggregate(['sum']).reset_index()
  df_stocks_diff.columns = ['Symbol', 'Shares', 'Investment']
  df_stocks_diff['AvgCost'] = round(df_stocks_diff['Investment']/df_stocks_diff['Shares'],2)
  df_stocks = pd.merge(df_stocks_diff, df_stocks_common, on='Symbol')
  return df_stocks

# plot fact distribution across dimension
def plot_pie_chart(df, dimension, fact):
  # grouping the data by category and calculating the sum of fact for each type
  grouped_data = df.groupby(dimension)[fact].sum()

  # sorting the grouped data in descending order
  grouped_data = grouped_data.sort_values(ascending=False)

  # creating a pie chart
  grouped_data.plot.pie(autopct='%1.1f%%', startangle=90, figsize=(6, 6))

  # adding a title and displaying the plot
  plt.title(f'{dimension} {fact} Distribution')
  plt.ylabel('')  # To hide the y-label
  plt.show()

In [7]:
# function to get portfolio features

def get_portfolio_features(df_common_features):

  print_date_time()
  print('-------------------')

  #df_common_features["Target"] = df_common_features["Target"].fillna(df_common_features["Max"])
  df_common_features['NTT'] = np.where(df_common_features['Strategy']== 'NTT', df_common_features["Target"], df_common_features['Max'])
  df_common_features['LTT'] = np.where(df_common_features['Strategy']== 'BTT', df_common_features["Target"], df_common_features['Max'])
  df_common_features['BOL'] = df_common_features['Min']

  tmp_df = df_common_features[df_common_features['Symbol'].isin(mypf_df[mypf_df['InPortfolio'] != 'NA'].Symbol.values)]
  print('qualified stocks: '+str(len(tmp_df['Symbol'].unique())))
  tmp_df1 = tmp_df[tmp_df['LatestQtr'] == 1]
  print('with latest results: '+str(len(tmp_df1['Symbol'].unique())))
  tmp_df1 = tmp_df1[tmp_df1['StarStock'] == 1]
  print('still star stocks: '+str(len(tmp_df1['Symbol'].unique())))
  tmp_df['Investment'] = tmp_df['AvgCost'] * tmp_df['Shares']
  tmp_df['Current'] = round(tmp_df['Close'] * tmp_df['Shares'],0)
  tmp_df['Previous'] = tmp_df['Prev_Close'] * tmp_df['Shares']
  tmp_df['EstimatedST'] = tmp_df['NTT'] * tmp_df['Shares']
  tmp_df['EstimatedLT'] = tmp_df['LTT'] * tmp_df['Shares']
  tmp_df['Current P/L'] = round((tmp_df['Current'] - tmp_df['Investment']),0)
  tmp_df['Today P/L%'] = round((tmp_df['Current'] - tmp_df['Previous'])*100/tmp_df['Previous'],2)
  tmp_df['Current P/L%'] = round((tmp_df['Current'] - tmp_df['Investment'])*100/tmp_df['Investment'],2)
  tmp_df['EstimatedST P/L%'] = round((tmp_df['EstimatedST'] - tmp_df['Investment'])*100/tmp_df['Investment'],2)
  tmp_df['EstimatedLT P/L%'] = round((tmp_df['EstimatedLT'] - tmp_df['Investment'])*100/tmp_df['Investment'],2)
  tmp_df['NTT%'] = round((tmp_df['NTT'] - tmp_df['Close'])*100/tmp_df['Close'],2)
  tmp_df['LTT%'] = round((tmp_df['LTT'] - tmp_df['Close'])*100/tmp_df['Close'],2)
  tmp_df['Gained%'] = round((tmp_df['Close'] - tmp_df['BOL'])*100/tmp_df['BOL'],2)
  investment = round(sum(tmp_df['AvgCost']*tmp_df['Shares']),0)
  current = round(sum(tmp_df['Close']*tmp_df['Shares']),0)
  tmp_df['InitAlloc%'] = round(tmp_df['Investment']*100/investment,2)
  tmp_df['CurrAlloc%'] = round(tmp_df['Current']*100/current,2)
  tmp_df['FTT'] = tmp_df['LTT']
  tmp_df.loc[tmp_df['Strategy'] == 'NTT', 'FTT'] = tmp_df['NTT']
  tmp_df['FTT%'] = tmp_df['LTT%']
  tmp_df.loc[tmp_df['Strategy'] == 'NTT', 'FTT%'] = tmp_df['NTT%']
  tmp_df['FTT Amt'] = round(tmp_df['FTT%'] * tmp_df['Current']/100,0)
  tmp_df['OTT%'] = round((tmp_df['FTT'] - tmp_df['AvgCost'])*100/tmp_df['AvgCost'],2)
  tmp_df['RRR Ind'] = round(tmp_df['Current P/L']/tmp_df['FTT Amt'],2)
  tmp_df['Risk Ind'] = round(tmp_df['Current P/L%']*tmp_df['CurrAlloc%'],0)

  return tmp_df

# function to print portfolio features
def print_portfolio_stats(df_portfolio_features, myinvmt_df):
  from pyxirr import xirr

  total_booked_amt, reserve_amt, cy_booked_amt, py_booked_amt = get_amt()

  dates = myinvmt_df['Date'].values
  dates = np.append(dates, datetime.date.today().strftime('%d-%b-%y'))
  investment = myinvmt_df['Investment'].values
  dates= pd.to_datetime(dates)

  current = round(sum(df_portfolio_features['Close']*df_portfolio_features['Shares']),0) + reserve_amt
  investment_xirr = np.append(investment, current)
  cagr = round(xirr(pd.DataFrame({"dates": dates, "amounts": investment_xirr}))*100,2)

  investment = -sum(investment)
  invested = round(sum(df_portfolio_features['AvgCost']*df_portfolio_features['Shares']),0) + reserve_amt
  previous = round(sum(df_portfolio_features['Prev_Close']*df_portfolio_features['Shares']),0) + reserve_amt
  cy_invested = investment + py_booked_amt

  today_pnl_amount = current-previous
  today_pnl_percentage = round((current-previous)*100/previous,2)

  curr_pnl_amount = current-invested
  curr_pnl_percentage = round((curr_pnl_amount)*100/(cy_invested),2)

  cy_pnl_amount = cy_booked_amt + curr_pnl_amount
  cy_pnl_percentage = round((cy_pnl_amount)*100/cy_invested,2)

  overall_pnl_amount = total_booked_amt + curr_pnl_amount
  overall_pnl_percentage = round((overall_pnl_amount)*100/investment,2)

  estimate_st = round(sum(df_portfolio_features['FTT']*df_portfolio_features['Shares']),0)  + reserve_amt
  est_st_pnl_amount = estimate_st-current
  est_st_pnl_percentage = round((est_st_pnl_amount)*100/current,2)

  estimate_lt = round(sum(df_portfolio_features['LTT']*df_portfolio_features['Shares']),0)  + reserve_amt
  est_lt_pnl_amount = estimate_lt-current
  est_lt_pnl_percentage = round((est_lt_pnl_amount)*100/current,2)

  total_profit = round(sum(df_portfolio_features[df_portfolio_features['Current P/L%'] > 0]['Current']) - sum(df_portfolio_features[df_portfolio_features['Current P/L%'] > 0]['Investment']),0)
  total_loss = round(sum(df_portfolio_features[df_portfolio_features['Current P/L%'] < 0]['Current']) - sum(df_portfolio_features[df_portfolio_features['Current P/L%'] < 0]['Investment']),0)

  cy_booked_percentage = round((cy_booked_amt)*100/current,2)
  py_booked_percentage = round((py_booked_amt)*100/investment,2)
  total_booked_percentage = round((total_booked_amt)*100/investment,2)

  print('-------------------')
  print('Initial Investment: ', format_amt(investment))
  print('CY Investment: ', format_amt(cy_invested))
  print('Reserve: ', format_amt(reserve_amt))
  print('Current: ',  format_amt(current))
  print('-------------------')
  print('Today PnL: '+ '{} ({}%)'.format(format_amt(today_pnl_amount), today_pnl_percentage))
  print('Current PnL: '+ '{} ({}%)'.format(format_amt(curr_pnl_amount), curr_pnl_percentage))
  print('CY Booked + Current PnL: '+ '{} ({}%)'.format(format_amt(cy_pnl_amount), cy_pnl_percentage))
  print('-------------------')
  print('Total profit: ', format_amt(total_profit))
  print('Total loss: ', format_amt(total_loss))
  print('-------------------')
  print('Total Booked + Current PnL: '+ '{} ({}%)'.format(format_amt(overall_pnl_amount), overall_pnl_percentage))
  print('Total Booked PnL: '+ '{} ({}%)'.format(format_amt(total_booked_amt), total_booked_percentage))
  print('Curr Year Booked PnL: '+ '{} ({}%)'.format(format_amt(cy_booked_amt), cy_booked_percentage))
  print('Prev Year Booked PnL: '+ '{} ({}%)'.format(format_amt(py_booked_amt), py_booked_percentage))
  print('===================')
  print('Est FTT: ',  format_amt(estimate_st))
  print('Est FTT PnL: '+ '{} ({}%)'.format(format_amt(est_st_pnl_amount), est_st_pnl_percentage))

  print('===================')
  print('Deployed: ', format_amt(investment))

  print('Current: ', format_amt(current))

  print('CAGR/XIRR %: '+'{}%'.format(cagr))

In [8]:
# get start and end date
start_date, end_date = get_start_end_date()

# get portfolio and prospects data
mypfs_df = get_mypfs_df()
mypps_df = get_mypps_df()
myinvmt_df = get_myinvmt_df()

# merge above datasets
mypf_df = pd.merge(mypfs_df, mypps_df, on="Symbol")

# seggregate dm and sv portfolio
dm_pf = mypf_df[mypf_df['InPortfolio'] == 'DM']
sv_pf = mypf_df[mypf_df['InPortfolio'] == 'SV']

# build portfolio stock dataframe
dm_stocks = get_stock_ids(dm_pf)
sv_stocks = get_stock_ids(sv_pf)
df_stocks = pd.concat([dm_pf,sv_pf], ignore_index = True)

# arrange common and diff stock features
common_cols = ['Symbol', 'Target', 'Criteria', 'Strategy', 'CumlRnk', 'LatestQtr', 'StarStock', 'Conviction', 'Category', 'InFolio', 'XIRR', 'MBQ']
diff_cols = ['Symbol', 'AvgCost', 'Shares']
df_stocks = arrange_features(df_stocks, common_cols, diff_cols)

# get common features
stock_ids = df_stocks['Symbol'].values
df_common_features = get_common_features(stock_ids, df_stocks)

df_common_features.reset_index(drop=True, inplace=True)
df_common_features.drop(['Date'], axis=1, inplace=True)
# get and print portfolio features
df_portfolio_features = get_portfolio_features(df_common_features)

print_portfolio_stats(df_portfolio_features, myinvmt_df)

df = df_portfolio_features
#plot_pie_chart(df, 'CapType', 'Current')
list_ox40n = list(df[df['MBQ'].str.contains('OX40N', na=False)]['Symbol'].values)

Run date time (IST): 2026-07-08 15:46:00
-------------------
qualified stocks: 92
with latest results: 31
still star stocks: 20

-------------------
Initial Investment:  1.40 C
CY Investment:  1.82 C
Reserve:  1.49 K
Current:  1.50 C
-------------------
Today PnL: -3.38 L (-2.21%)
Current PnL: -33.29 L (-18.25%)
CY Booked + Current PnL: -31.21 L (-17.11%)
-------------------
Total profit:  3.81 L
Total loss:  -37.10 L
-------------------
Total Booked + Current PnL: 11.66 L (8.36%)
Total Booked PnL: 44.95 L (32.22%)
Curr Year Booked PnL: 2.08 L (1.39%)
Prev Year Booked PnL: 42.87 L (30.73%)
===================
Est FTT:  2.55 C
Est FTT PnL: 1.05 C (70.13%)
===================
Deployed:  1.40 C
Current:  1.50 C
CAGR/XIRR %: 3.27%

In [9]:
# top 5 near their targets
cols = ['Symbol', 'Today P/L%', 'Current P/L%', 'FTT%', 'OTT%', 'FTT Amt', 'Current P/L', 'Current', 'FTT', 'Dev%_PE', 'RSI_14','Conviction', 'Spread%',  'CumlRnk', 'RRR Ind', 'CurrAlloc%', 'Gained%', 'Criteria', 'Strategy', 'Category']
df_tmp = df_portfolio_features[~df_portfolio_features['Symbol'].isin(['ENRIN','BLUSPRING','DIGITIDE'])]
df_tmp = df_tmp.sort_values(by = 'FTT Amt', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
59,PIDILITIND,-3.20,11.29,6.36,18.37,9988.0,15930.0,157040.0,1670.26,-22.05,53.0,X-LC,7.97,5.0,1.59,1.05,23.30,X40,ATH,CHEMICALS
83,TTKPRESTIG,-3.82,-20.44,25.81,0.09,20694.0,-20598.0,80179.0,770.00,86.13,61.0,M-SC,5.12,250.0,-1.00,0.53,42.77,OX40N,NTT,DURABLES
49,JSWINFRA,-2.54,6.98,8.83,16.43,20950.0,15485.0,237259.0,342.00,-8.19,55.0,X-MC,12.44,61.0,0.74,1.58,34.52,X40N,NTT,REALTY
73,SONACOMS,-1.36,14.53,21.09,38.69,24435.0,14700.0,115859.0,801.69,-9.26,71.0,M-MC,19.99,193.0,0.60,0.77,64.37,AR,ATH,AUTO
55,MASFIN,-3.07,-3.92,26.53,21.57,24975.0,-3840.0,94140.0,397.04,-17.34,50.0,H-SC,1.26,167.0,-0.15,0.63,12.21,XR,ATH,FINANCE

In [10]:
# top 5 today
df_tmp = df_portfolio_features.sort_values(by = 'Today P/L%', ascending=False)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
3,ALKYLAMINE,3.23,-21.06,143.90,92.54,114695.0,-21258.0,79705.0,4520.85,-15.40,59.0,H-SC,9.23,142.0,-0.19,0.53,51.35,SR,ATH,CHEMICALS
85,VAIBHAVGBL,2.43,-25.09,114.61,60.77,156926.0,-45853.0,136922.0,521.00,58.13,61.0,H-SC,3.82,160.0,-0.29,0.91,39.31,XR,NTT,JEWELLERY
39,ICICIGI,0.55,-4.43,24.40,18.89,46664.0,-8864.0,191245.0,2244.41,-19.59,53.0,X-MC,4.41,66.0,-0.19,1.28,7.22,X40,ATH,INSURANCE
72,SIS,0.49,-1.23,22.78,21.26,24981.0,-1369.0,109663.0,528.00,2617.62,57.0,H-SC,25.17,168.0,-0.05,0.73,63.05,OX40N,NTT,MISC
12,BOSCH-HCIL,0.43,-41.31,70.37,-0.01,52782.0,-52799.0,75006.0,2282.00,15247.83,45.0,M-SC,7.42,231.0,-1.00,0.50,27.67,OX40N,BTT,AC

In [11]:
# bottom 5 today
df_tmp = df_portfolio_features.sort_values(by = 'Today P/L%', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
68,SATIN,-5.48,37.90,10.11,51.83,38518.0,104705.0,380989.0,274.0,23.52,57.0,H-SC,41.16,159.0,2.72,2.54,85.60,XY24,NTT,FINANCE
48,JIOFIN,-5.38,-23.68,68.27,28.43,155444.0,-70637.0,227690.0,387.0,-24.86,39.0,X-LC,11.13,34.0,-0.45,1.52,2.63,XY24,BTT,FINANCE
41,IEX,-4.61,-20.73,87.48,48.63,138665.0,-41443.0,158511.0,219.0,-47.38,31.0,H-SC,4.46,137.0,-0.30,1.06,3.41,XR,NTT,MISC
9,BANDHANBNK,-4.42,-5.70,104.04,92.42,273307.0,-15865.0,262694.0,400.0,125.57,42.0,H-SC,21.14,174.0,-0.06,1.75,44.71,XY24,NTT,BANKS
61,RAJESHEXPO,-4.42,-82.00,455.79,0.07,112571.0,-112479.0,24698.0,518.0,805.30,46.0,L-SC,37.42,268.0,-1.00,0.16,21.97,OX40N,NTT,JEWELLERY

In [12]:
# top 5 to exit based on CumlRnk
df_tmp = df_portfolio_features[~df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])]
df_tmp = df_tmp[(df_tmp['Current P/L%'] > -1) & (df_tmp['Current P/L%'] < 1)].sort_values(by = 'CumlRnk', ascending=False)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
75,SURYODAY,-0.63,0.05,22.97,23.03,41154.0,92.0,179163.0,216.0,95.18,54.0,H-SC,20.38,166.0,0.0,1.2,50.85,XR,NTT,BANKS

In [13]:
# OX40N stocks to exit
df_tmp = df_portfolio_features[(df_portfolio_features['Symbol'].isin(list_ox40n))].sort_values(by = 'Current P/L%', ascending=False)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
25,FINCABLES,-1.82,30.32,59.54,107.91,114557.0,44760.0,192404.0,1641.55,17.20,40.0,M-SC,26.83,220.0,0.39,1.28,44.75,OX40N,ATH,CABLES
72,SIS,0.49,-1.23,22.78,21.26,24981.0,-1369.0,109663.0,528.00,2617.62,57.0,H-SC,25.17,168.0,-0.05,0.73,63.05,OX40N,NTT,MISC
16,CERA,-0.85,-17.32,49.84,23.89,72487.0,-30463.0,145440.0,9475.00,-20.29,58.0,H-SC,15.17,153.0,-0.42,0.97,41.38,OX40N,NTT,CERAMICS
83,TTKPRESTIG,-3.82,-20.44,25.81,0.09,20694.0,-20598.0,80179.0,770.00,86.13,61.0,M-SC,5.12,250.0,-1.00,0.53,42.77,OX40N,NTT,DURABLES
43,INDIGOPNTS,-4.04,-25.39,34.06,0.02,44359.0,-44322.0,130237.0,1408.00,98.66,57.0,M-SC,4.14,222.0,-1.00,0.87,47.76,OX40N,NTT,PAINTS

In [14]:
# top 5 to book for rotation
df_tmp = df_portfolio_features[(df_portfolio_features['Current P/L%'] > 20) ].sort_values(by = 'CumlRnk', ascending=False)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
25,FINCABLES,-1.82,30.32,59.54,107.91,114557.0,44760.0,192404.0,1641.55,17.20,40.0,M-SC,26.83,220.0,0.39,1.28,44.75,OX40N,ATH,CABLES
68,SATIN,-5.48,37.90,10.11,51.83,38518.0,104705.0,380989.0,274.00,23.52,57.0,H-SC,41.16,159.0,2.72,2.54,85.60,XY24,NTT,FINANCE
91,ZYDUSLIFE,-0.43,21.06,12.04,35.63,30546.0,44134.0,253708.0,1286.17,5.41,67.0,H-MC,15.07,120.0,1.44,1.69,33.40,AR,ATH,PHARMA

In [15]:
# top 5 to monitor for exit
df_tmp = df_portfolio_features[~df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])]
df_tmp = df_tmp[(df_tmp['Current P/L%'] > 0) ].sort_values(by = 'Dev%_PE', ascending=False)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
75,SURYODAY,-0.63,0.05,22.97,23.03,41154.0,92.0,179163.0,216.00,95.18,54.0,H-SC,20.38,166.0,0.00,1.20,50.85,XR,NTT,BANKS
74,STARHEALTH,-0.94,13.05,30.26,47.26,96168.0,36682.0,317805.0,761.00,78.49,65.0,H-SC,16.51,173.0,0.38,2.12,38.37,XY24,NTT,INSURANCE
68,SATIN,-5.48,37.90,10.11,51.83,38518.0,104705.0,380989.0,274.00,23.52,57.0,H-SC,41.16,159.0,2.72,2.54,85.60,XY24,NTT,FINANCE
25,FINCABLES,-1.82,30.32,59.54,107.91,114557.0,44760.0,192404.0,1641.55,17.20,40.0,M-SC,26.83,220.0,0.39,1.28,44.75,OX40N,ATH,CABLES
91,ZYDUSLIFE,-0.43,21.06,12.04,35.63,30546.0,44134.0,253708.0,1286.17,5.41,67.0,H-MC,15.07,120.0,1.44,1.69,33.40,AR,ATH,PHARMA

In [16]:
# top 5 to book for rotation from weak conviction
df_tmp = df_portfolio_features[~df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])]
df_tmp = df_tmp[~df_tmp['Criteria'].isin(['XY25','XY24','X40', 'X40N'])].sort_values(by = 'RRR Ind', ascending=False)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
91,ZYDUSLIFE,-0.43,21.06,12.04,35.63,30546.0,44134.0,253708.0,1286.17,5.41,67.0,H-MC,15.07,120.0,1.44,1.69,33.40,AR,ATH,PHARMA
73,SONACOMS,-1.36,14.53,21.09,38.69,24435.0,14700.0,115859.0,801.69,-9.26,71.0,M-MC,19.99,193.0,0.60,0.77,64.37,AR,ATH,AUTO
25,FINCABLES,-1.82,30.32,59.54,107.91,114557.0,44760.0,192404.0,1641.55,17.20,40.0,M-SC,26.83,220.0,0.39,1.28,44.75,OX40N,ATH,CABLES
75,SURYODAY,-0.63,0.05,22.97,23.03,41154.0,92.0,179163.0,216.00,95.18,54.0,H-SC,20.38,166.0,0.00,1.20,50.85,XR,NTT,BANKS
72,SIS,0.49,-1.23,22.78,21.26,24981.0,-1369.0,109663.0,528.00,2617.62,57.0,H-SC,25.17,168.0,-0.05,0.73,63.05,OX40N,NTT,MISC

In [17]:
# top 5 to accumulate based on lowest RSI_14
df_tmp = df_portfolio_features[df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])].sort_values(by = 'RSI_14', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
87,VBL,-2.00,-4.14,41.22,35.37,124799.0,-13079.0,302763.0,670.16,-15.45,31.0,X-LC,9.19,13.0,-0.10,2.02,24.44,X40N,ATH,FMCG
51,KOTAKBANK,-3.04,-1.11,22.46,21.11,30756.0,-1536.0,136937.0,453.24,-15.04,33.0,X-LC,4.33,12.0,-0.05,0.91,4.73,X40,ATH,BANKS
81,TMPV,-2.99,-24.42,80.70,36.58,217051.0,-86881.0,268960.0,600.00,-84.72,33.0,X-LC,7.37,4.0,-0.40,1.79,13.03,XY24,NTT,AUTO
47,ITC,-2.81,-26.08,61.05,19.06,153518.0,-88704.0,251462.0,452.00,-59.56,35.0,X-LC,12.71,1.0,-0.58,1.68,1.32,X40,NTT,FMCG
35,HDFCLIFE,-2.93,-9.12,46.02,32.71,62654.0,-13654.0,136146.0,811.41,-29.00,37.0,X-LC,15.49,31.0,-0.22,0.91,2.28,X40,ATH,INSURANCE

In [18]:
# top 5 to accumulate based on Spread and CumlRnk
df_tmp = df_portfolio_features[df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])]
df_tmp = df_tmp[(df_tmp['CumlRnk'] < 100)].sort_values(by = 'Spread%', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
17,CIPLA,-1.38,15.92,15.11,33.43,26827.0,24382.0,177543.0,1648.14,-10.44,55.0,X-LC,2.26,18.0,0.91,1.18,21.20,X40N,ATH,PHARMA
19,COLPAL,-2.75,-23.30,82.34,39.86,166335.0,-61355.0,202010.0,3683.41,-7.20,47.0,X-MC,2.99,62.0,-0.37,1.35,14.27,XY25,ATH,FMCG
84,UNITDSPR,-1.37,3.49,16.70,20.77,40466.0,8170.0,242314.0,1644.00,-8.17,66.0,X-MC,3.07,64.0,0.20,1.62,16.48,X40N,NTT,BREWERIES
23,DMART,-0.79,-2.92,33.50,29.60,81176.0,-7284.0,242316.0,5391.45,-18.18,39.0,X-LC,3.27,14.0,-0.09,1.62,10.76,X40N,ATH,FMCG
11,BERGEPAINT,-2.08,-8.21,36.52,25.32,86406.0,-21151.0,236598.0,680.00,-13.20,42.0,X-MC,3.40,68.0,-0.24,1.58,23.14,XY24,NTT,PAINTS

In [19]:
# top 5 to accumulate based on lowest Gained%
df_tmp = df_portfolio_features[df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])].sort_values(by = 'Gained%', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
58,PGHH,-1.12,-33.31,97.95,32.01,139473.0,-71128.0,142392.0,17616.87,-54.91,41.0,X-MC,20.79,57.0,-0.51,0.95,0.98,X40,ATH,FMCG
47,ITC,-2.81,-26.08,61.05,19.06,153518.0,-88704.0,251462.0,452.00,-59.56,35.0,X-LC,12.71,1.0,-0.58,1.68,1.32,X40,NTT,FMCG
65,RELIANCE,-2.48,-18.10,52.99,25.30,87217.0,-36372.0,164591.0,1952.00,-20.42,39.0,X-LC,7.29,21.0,-0.42,1.10,1.36,XY25,BTT,REFINERIES
35,HDFCLIFE,-2.93,-9.12,46.02,32.71,62654.0,-13654.0,136146.0,811.41,-29.00,37.0,X-LC,15.49,31.0,-0.22,0.91,2.28,X40,ATH,INSURANCE
48,JIOFIN,-5.38,-23.68,68.27,28.43,155444.0,-70637.0,227690.0,387.00,-24.86,39.0,X-LC,11.13,34.0,-0.45,1.52,2.63,XY24,BTT,FINANCE

In [20]:
# top 5 to accumulate based on lowest CurrAlloc%
df_tmp = df_portfolio_features[df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])].sort_values(by = 'CurrAlloc%', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
10,BATAINDIA,-2.38,-56.85,213.30,35.20,118439.0,-73143.0,55527.0,2096.00,-27.22,41.0,X-SC,19.60,91.0,-0.62,0.37,10.12,X40,NTT,FOOTWEAR
64,RELAXO,-1.95,-50.16,205.61,52.31,148742.0,-72818.0,72342.0,1176.00,-46.96,56.0,X-SC,11.50,92.0,-0.49,0.48,61.75,X40N,NTT,FOOTWEAR
60,QUESS,-2.92,19.15,45.96,73.90,58479.0,20446.0,127239.0,424.00,-36.09,76.0,X-SC,23.27,80.0,0.35,0.85,73.45,XY24,NTT,MISC
35,HDFCLIFE,-2.93,-9.12,46.02,32.71,62654.0,-13654.0,136146.0,811.41,-29.00,37.0,X-LC,15.49,31.0,-0.22,0.91,2.28,X40,ATH,INSURANCE
51,KOTAKBANK,-3.04,-1.11,22.46,21.11,30756.0,-1536.0,136937.0,453.24,-15.04,33.0,X-LC,4.33,12.0,-0.05,0.91,4.73,X40,ATH,BANKS

In [21]:
# top 5 to accumulate based on CumlRnk
df_tmp = df_portfolio_features.sort_values(by = 'CumlRnk', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
47,ITC,-2.81,-26.08,61.05,19.06,153518.0,-88704.0,251462.0,452.00,-59.56,35.0,X-LC,12.71,1.0,-0.58,1.68,1.32,X40,NTT,FMCG
79,TCS,-1.84,-39.60,106.75,24.88,298708.0,-183453.0,279820.0,4253.91,-48.87,42.0,X-LC,21.66,2.0,-0.61,1.87,3.78,X40,ATH,IT
45,INFY,-0.23,-27.21,84.42,34.24,192276.0,-85127.0,227761.0,1972.00,-42.67,48.0,X-LC,21.07,3.0,-0.44,1.52,8.53,X40,NTT,IT
81,TMPV,-2.99,-24.42,80.70,36.58,217051.0,-86881.0,268960.0,600.00,-84.72,33.0,X-LC,7.37,4.0,-0.40,1.79,13.03,XY24,NTT,AUTO
59,PIDILITIND,-3.20,11.29,6.36,18.37,9988.0,15930.0,157040.0,1670.26,-22.05,53.0,X-LC,7.97,5.0,1.59,1.05,23.30,X40,ATH,CHEMICALS

In [22]:
# top 5 for average up
df_tmp = df_portfolio_features[(df_portfolio_features['Dev%_200'] > 5)].sort_values(by = 'CurrAlloc%', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
44,INDUSINDBK,-2.70,-26.57,80.97,32.89,45906.0,-20512.0,56695.0,1800.00,-366.81,64.0,L-MC,8.87,258.0,-0.45,0.38,39.78,XR,NTT,BANKS
3,ALKYLAMINE,3.23,-21.06,143.90,92.54,114695.0,-21258.0,79705.0,4520.85,-15.40,59.0,H-SC,9.23,142.0,-0.19,0.53,51.35,SR,ATH,CHEMICALS
83,TTKPRESTIG,-3.82,-20.44,25.81,0.09,20694.0,-20598.0,80179.0,770.00,86.13,61.0,M-SC,5.12,250.0,-1.00,0.53,42.77,OX40N,NTT,DURABLES
72,SIS,0.49,-1.23,22.78,21.26,24981.0,-1369.0,109663.0,528.00,2617.62,57.0,H-SC,25.17,168.0,-0.05,0.73,63.05,OX40N,NTT,MISC
73,SONACOMS,-1.36,14.53,21.09,38.69,24435.0,14700.0,115859.0,801.69,-9.26,71.0,M-MC,19.99,193.0,0.60,0.77,64.37,AR,ATH,AUTO

In [23]:
# top 5 RSP
df_tmp = df_portfolio_features.sort_values(by = 'RSP', ascending=False)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
60,QUESS,-2.92,19.15,45.96,73.90,58479.0,20446.0,127239.0,424.0,-36.09,76.0,X-SC,23.27,80.0,0.35,0.85,73.45,XY24,NTT,MISC
64,RELAXO,-1.95,-50.16,205.61,52.31,148742.0,-72818.0,72342.0,1176.0,-46.96,56.0,X-SC,11.50,92.0,-0.49,0.48,61.75,X40N,NTT,FOOTWEAR
0,5PAISA,0.04,-30.24,61.84,12.90,94258.0,-66074.0,152422.0,593.0,124.76,62.0,H-SC,5.77,170.0,-0.70,1.02,47.09,OX40N,NTT,FINANCE
83,TTKPRESTIG,-3.82,-20.44,25.81,0.09,20694.0,-20598.0,80179.0,770.0,86.13,61.0,M-SC,5.12,250.0,-1.00,0.53,42.77,OX40N,NTT,DURABLES
49,JSWINFRA,-2.54,6.98,8.83,16.43,20950.0,15485.0,237259.0,342.0,-8.19,55.0,X-MC,12.44,61.0,0.74,1.58,34.52,X40N,NTT,REALTY

In [24]:
# Top N allocation
df_tmp = df_portfolio_features.sort_values(by = 'CurrAlloc%', ascending=False)
top_n_values = [10, 25, 50]

sum_df = pd.DataFrame({
    'Top_N': top_n_values,
    'Sum_Alloc%': [df_tmp['CurrAlloc%'].head(n).sum() for n in top_n_values]
})

sum_df

   Top_N  Sum_Alloc%
0     10       19.21
1     25       42.69
2     50       72.61

In [25]:
# market-cap-wise allocation
df_tmp = df_portfolio_features[cols]
df_tmp.groupby(df_tmp['Conviction'].str[-2:])['CurrAlloc%'].sum().sort_values(ascending=False)

Conviction
SC    43.50
LC    30.20
MC    26.26
Name: CurrAlloc%, dtype: float64

In [26]:
# criteria-wise allocation
df_portfolio_features.groupby('Criteria')['CurrAlloc%'].sum().sort_values(ascending=False)

Criteria
XY24     27.72
X40      24.78
X40N     17.39
XR        8.82
OX40N     7.13
AR        6.82
XY25      6.41
SR        0.89
Name: CurrAlloc%, dtype: float64

In [27]:
# conviction-wise allocation
df_portfolio_features.groupby('Conviction')['CurrAlloc%'].sum().sort_values(ascending=False)

Conviction
X-LC    28.25
H-SC    22.86
X-MC    21.06
M-SC    10.04
X-SC    10.03
H-MC     2.77
M-MC     2.05
H-LC     1.15
M-LC     0.80
L-SC     0.57
L-MC     0.38
Name: CurrAlloc%, dtype: float64

In [28]:
# sector-wise stats
df_tmp = df_portfolio_features.groupby('Category')[['CurrAlloc%', 'Current', 'Current P/L', 'FTT Amt']].sum().sort_values(by=['Current', 'Current P/L'], ascending=False)
df_tmp['Current P/L%'] = round(df_tmp['Current P/L'] * 100 / df_tmp['Current'], 2)
df_tmp['FTT%'] = round(df_tmp['FTT Amt'] * 100 / df_tmp['Current'], 2)
cols = ['CurrAlloc%', 'Current P/L%', 'FTT%']
df_tmp[cols].sort_values(by=['CurrAlloc%'], ascending=False)

               CurrAlloc%  Current P/L%    FTT%
Category
FMCG                14.44        -22.34   65.26
FINANCE             11.24         -9.53   56.99
IT                   9.76        -54.12  131.17
MISC                 7.17        -24.51   77.93
AUTO                 6.64         -9.89   50.88
BANKS                5.76         -5.21   53.86
PAINTS               5.49        -19.82   40.26
INSURANCE            5.35         -3.29   38.12
PHARMA               5.21          5.21   24.13
ELECTRICAL           4.11        -14.73   55.22
CHEMICALS            2.21        -22.77   95.61
HEALTHCARE           2.09        -14.03   43.79
APPARELS             1.93          7.43   23.67
AC                   1.75        -21.48   54.41
FOOTWEAR             1.72        -70.72  139.17
DURABLES             1.62        -59.24   97.97
BREWERIES            1.62          3.37   16.70
REALTY               1.58          6.53    8.83
TRAVEL               1.53        -95.04  192.69
CERAMICS             1.43        -42.90   86.31
CABLES               1.28         23.26   59.54
ENGINEERING          1.24        -30.00   89.46
REFINERIES           1.10        -22.10   52.99
JEWELLERY            1.07        -97.97  166.75
CEMENT               1.07        -67.36  192.56
ENTERTAINMENT        0.73        -76.39  181.58
TEXTILES             0.41        -48.57   90.93
HOTELS               0.41        -85.80  151.34

In [29]:
# money to be made criteria-wise
df_portfolio_features.groupby('Criteria')['FTT Amt'].agg(['sum', 'count']).sort_values(by='sum', ascending=False)

                sum  count
Criteria
XY24      3441731.0     21
X40       1960891.0     19
XR        1359823.0     13
AR        1153194.0      9
X40N      1112760.0     13
OX40N      722080.0     10
XY25       476020.0      5
SR         284569.0      2

In [30]:
# money to be made conviction-wise
df_portfolio_features.groupby('Conviction')['FTT Amt'].agg(['sum', 'count']).sort_values(by='sum', ascending=False)

                  sum  count
Conviction
H-SC        3352334.0     24
X-LC        2043916.0     21
X-MC        1559750.0     15
M-SC        1411600.0     14
X-SC        1299714.0      9
H-MC         281723.0      2
L-SC         205061.0      2
M-LC         171861.0      1
M-MC          77931.0      2
H-LC          61272.0      1
L-MC          45906.0      1

In [31]:
# money to be made criteria and conviction-wise
df_portfolio_features.groupby(['Conviction', 'Criteria'])['FTT Amt'].agg(['sum', 'count']).sort_values(by='sum', ascending=False)

                           sum  count
Conviction Criteria
X-LC       X40       1080754.0     10
H-SC       XY24       989818.0      6
           AR         961726.0      5
M-SC       XY24       830285.0      6
H-SC       XR         819288.0      7
X-SC       XY24       766792.0      4
X-MC       X40        663583.0      7
           X40N       408315.0      4
X-LC       X40N       388077.0      6
           XY24       372495.0      2
X-SC       X40N       316368.0      3
M-SC       OX40N      312576.0      5
H-SC       OX40N      296933.0      4
           SR         284569.0      2
X-MC       XY25       256688.0      2
H-MC       XY24       251177.0      1
X-MC       XY24       231164.0      2
X-SC       X40        216554.0      2
M-SC       XR         193524.0      2
M-LC       XR         171861.0      1
X-LC       XY25       165836.0      2
L-SC       OX40N      112571.0      1
           XR          92490.0      1
M-SC       AR          75215.0      1
H-LC       AR          61272.0      1
M-MC       XY25        53496.0      1
L-MC       XR          45906.0      1
X-LC       XR          36754.0      1
H-MC       AR          30546.0      1
M-MC       AR          24435.0      1

In [32]:
# notebook execution time

end_time = time.time()
execution_time = round(end_time - start_time, 0)
print(f"Notebook execution time: {execution_time} seconds")

Notebook execution time: 38.0 seconds