<a href="https://colab.research.google.com/github/ankit-rathi/Quantvesting_v2/blob/main/myStocks_Portfolio_Analysis.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
'''
!pip install pandas==2.2.2 -qq
!pip install pyxirr -qq
!pip install ta -qq
!pip install yfinance==0.2.59 -qq
'''

'\n!pip install pandas==2.2.2 -qq\n!pip install pyxirr -qq\n!pip install ta -qq\n!pip install yfinance==0.2.59 -qq\n'

In [2]:
# import libraries

import numpy as np
import pandas as pd
import datetime
import warnings
warnings.filterwarnings('ignore')
import yfinance as yfin
import ta
import matplotlib.pyplot as plt
import requests

In [3]:
# notebook start time
import time
import datetime
import pytz

start_time = time.time()

# function to print date timestamp
def print_date_time():
  tz_NY = pytz.timezone('Asia/Kolkata')
  datetime_NY = datetime.datetime.now(tz_NY)
  print("Run date time (IST):", datetime_NY.strftime("%Y-%m-%d %H:%M:%S"))

In [4]:
# function to get booked and reserved amount
def get_amt():
  # fetch the JSON data from the URL
  url = "https://raw.githubusercontent.com/ankit-rathi/Tradevesting_v1/main/data/myPortfolioAmts.json"
  response = requests.get(url)
  pf_amts = response.json()  # parse the JSON data

  # extract values from the JSON
  py_booked_amt_dm = pf_amts["py_booked_amt_dm"]
  py_booked_amt_sv = pf_amts["py_booked_amt_sv"]
  cy_booked_amt_dm = pf_amts["cy_booked_amt_dm"]
  cy_booked_amt_sv = pf_amts["cy_booked_amt_sv"]
  reserve_amt_dm = pf_amts["reserve_amt_dm"]
  reserve_amt_sv = pf_amts["reserve_amt_sv"]

  # perform calculations
  py_booked_amt = py_booked_amt_dm + py_booked_amt_sv
  cy_booked_amt = cy_booked_amt_dm + cy_booked_amt_sv
  reserve_amt = reserve_amt_dm + reserve_amt_sv
  total_booked_amt = py_booked_amt + cy_booked_amt

  return total_booked_amt, reserve_amt, cy_booked_amt, py_booked_amt

gen_output = 0

In [5]:
# function to format the amount
def format_amt(number):
    abs_number = abs(number)

    if abs_number >= 1_00_00_000:  # Crores
        formatted_amt = f"{number / 1_00_00_000:.2f} C"
    elif abs_number >= 1_00_000:  # Lakhs
        formatted_amt = f"{number / 1_00_000:.2f} L"
    elif abs_number >= 1_000:  # Thousands
        formatted_amt = f"{number / 1_000:.2f} K"
    else:
        formatted_amt = f"{number:.2f}"

    return formatted_amt

# function to set start and end date
def get_start_end_date():
  start_date = (datetime.date.today() + datetime.timedelta(days=-365)).strftime('%Y-%m-%d')
  end_date = (datetime.date.today() + datetime.timedelta(days=1)).strftime('%Y-%m-%d')
  return start_date, end_date

# function to fetch my portfolio csv
def get_mypfs_df():
  mypfs_df = pd.read_csv('https://raw.githubusercontent.com/ankit-rathi/Tradevesting_v1/main/data/myPortfolioStocks.csv')
  return mypfs_df

# function to fetch my prospects csv
def get_mypps_df():
  mypps_df = pd.read_csv('https://raw.githubusercontent.com/ankit-rathi/Tradevesting_v1/main/data/myProspectsScrips.csv')
  return mypps_df

# function to fetch screener data
def get_myscreen_df():
  myscreen_df = pd.read_csv('https://raw.githubusercontent.com/ankit-rathi/Tradevesting_v1/main/data/myScreenerDB.csv')
  return myscreen_df

# function to fetch momentum data
def get_myinvmt_df():
  myinvmt_df = pd.read_csv('https://raw.githubusercontent.com/ankit-rathi/Tradevesting_v1/main/data/myInvestments.csv')
  return myinvmt_df

# function to get the stock ids
def get_stock_ids(df_pf):
  stock_n100 = df_pf['Symbol'].unique()

  exclude = ['CADILAHC','MMTC', 'MASFIN']

  stock_ids = df_pf[~df_pf['Symbol'].isin(exclude) ]['Symbol'].unique()

  #mypf = mypf[mypf.Forecast.notnull()]
  #stock_ids = mypf['Symbol'].unique()

  #stock_ids.sort()
  return stock_ids

# get features from screener data
def get_screener_features():
  myscreen_df = get_myscreen_df()
  cols = ['Symbol', 'EPS', 'MedPE', 'ROCE%', 'ROE%', 'CapType']
  return myscreen_df[cols]

# get relative strength
def get_relative_strength(stock_list):

    # Dictionary to store stock tickers and their corresponding percentage price change
    stock_changes = {}

    # Loop through each stock and fetch its price data
    for stock in stock_list:
        try:
            # Download the stock data for the given date range
            stock_data = yfin.Ticker(stock + '.NS').history(period='1mo', interval='1d')[map(str.title, ['open', 'close', 'low', 'high', 'volume'])]

            # Calculate the percentage change for the stock
            if len(stock_data) > 0:
                start_price = stock_data['Close'].iloc[0]
                end_price = stock_data['Close'].iloc[-1]
                percent_change = round(((end_price - start_price) / start_price) * 100, 2)
                stock_changes[stock] = percent_change
            else:
                stock_changes[stock] = np.nan  # If no data is available, set to NaN

        except Exception as e:
            print(f"Error fetching data for {stock}: {e}")
            stock_changes[stock] = np.nan

    # Create a DataFrame with stock tickers and their percentage changes
    df = pd.DataFrame(list(stock_changes.items()), columns=['Symbol', 'Percent_Change'])

    # Drop any stocks with missing data (NaN values)
    df = df.dropna()

    # Calculate the percentile rank based on percentage change
    df['RSP'] = round(df['Percent_Change'].rank(pct=True) * 100, 2)
    cols = ['Symbol', 'RSP']
    df = df[cols]
    # Sort by percentile rank (optional)
    df = df.sort_values(by='RSP', ascending=False).reset_index(drop=True)

    return df

In [6]:
# function to get stock technicals
def stock_prec_dev(stock_symbol):
    #stock_symbol = 'ULTRACEMCO.NS'
    short_window = 20
    mid_window = 50
    long_window = 200
    moving_avg = 'SMA'

    start = datetime.datetime(*map(int, start_date.split('-')))
    end = datetime.datetime(*map(int, end_date.split('-')))

    stock_df = yfin.Ticker(stock_symbol + '.NS').history(period='max', interval='1d')[map(str.title, ['open', 'close', 'low', 'high', 'volume'])]

    stock_df['Max'] = round(max(stock_df['Close']),2)
    stock_df = stock_df[(stock_df.index <= end_date) & (stock_df.index >= start_date)]
    stock_df['200_SMA'] = round(stock_df['Close'].rolling(window = 200, min_periods = 1).mean(),0)
    stock_df['Dev%_200'] = round((stock_df['Close'] - stock_df['200_SMA'])*100/stock_df['200_SMA'],2)
    stock_df.dropna(axis = 0, inplace = True) # remove any null rows

    stock_df['20_SMA'] = stock_df['Close'].rolling(window=20).mean()
    stock_df['50_SMA'] = stock_df['Close'].rolling(window=50).mean()
    stock_df['Symbol'] = stock_symbol

    stock_df['Close'] = round(stock_df['Close'],2)
    stock_df['Min'] = round(min(stock_df['Close']),2)
    stock_df['RSI_14'] = ta.momentum.RSIIndicator(close=stock_df['Close'], window=14).rsi()
    stock_df['RSI_14'] = round(stock_df['RSI_14'],0)
    stock_df['Prev_Close'] = stock_df['Close'].shift(1)
    stock_df.drop(['Open', 'Low', 'High', 'Volume'], axis=1, inplace=True)
    stock_df = stock_df.tail(1)

    max_SMA = max(stock_df['20_SMA'].item(), stock_df['50_SMA'].item(), stock_df['200_SMA'].item())
    min_SMA = min(stock_df['20_SMA'].item(), stock_df['50_SMA'].item(), stock_df['200_SMA'].item())
    ABS_Spread = max_SMA - min_SMA
    stock_df['Spread%'] = round((ABS_Spread / stock_df['200_SMA'].item()) * 100,2)

    return stock_df

# function to compute stock attributes
def get_common_features(stock_ids, df_mypf):

  df_prec_dev = pd.DataFrame()
  df_tmp = get_screener_features()
  df_rs = get_relative_strength(stock_ids)

  for stock_id in stock_ids:
      tmp = stock_prec_dev(stock_id)
      tmp = tmp.reset_index()
      df_prec_dev = pd.concat([df_prec_dev, tmp], ignore_index = True)
  df_prec_dev = pd.merge(df_prec_dev, df_mypf, on= 'Symbol')
  df_prec_dev = pd.merge(df_prec_dev, df_tmp, on= 'Symbol', how='left')
  df_prec_dev = pd.merge(df_prec_dev, df_rs, on= 'Symbol', how='left')
  #print(df_prec_dev.columns)
  df_prec_dev['Curr_PE'] = round(df_prec_dev['Close']/df_prec_dev['EPS'],1)
  df_prec_dev['Dev%_PE'] = round((df_prec_dev['Curr_PE'] - df_prec_dev['MedPE'])*100/df_prec_dev['MedPE'],2)
  df_prec_dev['Conviction'] = df_prec_dev['Conviction'] + '-' + df_prec_dev['CapType']
  return df_prec_dev

# function to arrange stock features
def arrange_features(df_stocks, common_cols, diff_cols):
  df_stocks_common = df_stocks[common_cols].drop_duplicates()
  df_stocks_diff = df_stocks[diff_cols]
  df_stocks_diff['Investment'] = df_stocks_diff['AvgCost'] * df_stocks_diff['Shares']
  df_stocks_diff = df_stocks_diff.groupby(['Symbol'])[['Shares', 'Investment']].aggregate(['sum']).reset_index()
  df_stocks_diff.columns = ['Symbol', 'Shares', 'Investment']
  df_stocks_diff['AvgCost'] = round(df_stocks_diff['Investment']/df_stocks_diff['Shares'],2)
  df_stocks = pd.merge(df_stocks_diff, df_stocks_common, on='Symbol')
  return df_stocks

# plot fact distribution across dimension
def plot_pie_chart(df, dimension, fact):
  # grouping the data by category and calculating the sum of fact for each type
  grouped_data = df.groupby(dimension)[fact].sum()

  # sorting the grouped data in descending order
  grouped_data = grouped_data.sort_values(ascending=False)

  # creating a pie chart
  grouped_data.plot.pie(autopct='%1.1f%%', startangle=90, figsize=(6, 6))

  # adding a title and displaying the plot
  plt.title(f'{dimension} {fact} Distribution')
  plt.ylabel('')  # To hide the y-label
  plt.show()

In [7]:
# function to get portfolio features

def get_portfolio_features(df_common_features):

  print_date_time()
  print('-------------------')

  #df_common_features["Target"] = df_common_features["Target"].fillna(df_common_features["Max"])
  df_common_features['NTT'] = np.where(df_common_features['Strategy']== 'NTT', df_common_features["Target"], df_common_features['Max'])
  df_common_features['LTT'] = np.where(df_common_features['Strategy']== 'BTT', df_common_features["Target"], df_common_features['Max'])
  df_common_features['BOL'] = df_common_features['Min']

  tmp_df = df_common_features[df_common_features['Symbol'].isin(mypf_df[mypf_df['InPortfolio'] != 'NA'].Symbol.values)]
  print('qualified stocks: '+str(len(tmp_df['Symbol'].unique())))
  tmp_df1 = tmp_df[tmp_df['LatestQtr'] == 1]
  print('with latest results: '+str(len(tmp_df1['Symbol'].unique())))
  tmp_df1 = tmp_df1[tmp_df1['StarStock'] == 1]
  print('still star stocks: '+str(len(tmp_df1['Symbol'].unique())))
  tmp_df['Investment'] = tmp_df['AvgCost'] * tmp_df['Shares']
  tmp_df['Current'] = round(tmp_df['Close'] * tmp_df['Shares'],0)
  tmp_df['Previous'] = tmp_df['Prev_Close'] * tmp_df['Shares']
  tmp_df['EstimatedST'] = tmp_df['NTT'] * tmp_df['Shares']
  tmp_df['EstimatedLT'] = tmp_df['LTT'] * tmp_df['Shares']
  tmp_df['Current P/L'] = round((tmp_df['Current'] - tmp_df['Investment']),0)
  tmp_df['Today P/L%'] = round((tmp_df['Current'] - tmp_df['Previous'])*100/tmp_df['Previous'],2)
  tmp_df['Current P/L%'] = round((tmp_df['Current'] - tmp_df['Investment'])*100/tmp_df['Investment'],2)
  tmp_df['EstimatedST P/L%'] = round((tmp_df['EstimatedST'] - tmp_df['Investment'])*100/tmp_df['Investment'],2)
  tmp_df['EstimatedLT P/L%'] = round((tmp_df['EstimatedLT'] - tmp_df['Investment'])*100/tmp_df['Investment'],2)
  tmp_df['NTT%'] = round((tmp_df['NTT'] - tmp_df['Close'])*100/tmp_df['Close'],2)
  tmp_df['LTT%'] = round((tmp_df['LTT'] - tmp_df['Close'])*100/tmp_df['Close'],2)
  tmp_df['Gained%'] = round((tmp_df['Close'] - tmp_df['BOL'])*100/tmp_df['BOL'],2)
  investment = round(sum(tmp_df['AvgCost']*tmp_df['Shares']),0)
  current = round(sum(tmp_df['Close']*tmp_df['Shares']),0)
  tmp_df['InitAlloc%'] = round(tmp_df['Investment']*100/investment,2)
  tmp_df['CurrAlloc%'] = round(tmp_df['Current']*100/current,2)
  tmp_df['FTT'] = tmp_df['LTT']
  tmp_df.loc[tmp_df['Strategy'] == 'NTT', 'FTT'] = tmp_df['NTT']
  tmp_df['FTT%'] = tmp_df['LTT%']
  tmp_df.loc[tmp_df['Strategy'] == 'NTT', 'FTT%'] = tmp_df['NTT%']
  tmp_df['FTT Amt'] = round(tmp_df['FTT%'] * tmp_df['Current']/100,0)
  tmp_df['OTT%'] = round((tmp_df['FTT'] - tmp_df['AvgCost'])*100/tmp_df['AvgCost'],2)
  tmp_df['RRR Ind'] = round(tmp_df['Current P/L']/tmp_df['FTT Amt'],2)
  tmp_df['Risk Ind'] = round(tmp_df['Current P/L%']*tmp_df['CurrAlloc%'],0)

  return tmp_df

# function to print portfolio features
def print_portfolio_stats(df_portfolio_features, myinvmt_df):
  from pyxirr import xirr

  total_booked_amt, reserve_amt, cy_booked_amt, py_booked_amt = get_amt()

  dates = myinvmt_df['Date'].values
  dates = np.append(dates, datetime.date.today().strftime('%d-%b-%y'))
  investment = myinvmt_df['Investment'].values
  dates= pd.to_datetime(dates)

  current = round(sum(df_portfolio_features['Close']*df_portfolio_features['Shares']),0) + reserve_amt
  investment_xirr = np.append(investment, current)
  cagr = round(xirr(pd.DataFrame({"dates": dates, "amounts": investment_xirr}))*100,2)

  investment = -sum(investment)
  invested = round(sum(df_portfolio_features['AvgCost']*df_portfolio_features['Shares']),0) + reserve_amt
  previous = round(sum(df_portfolio_features['Prev_Close']*df_portfolio_features['Shares']),0) + reserve_amt
  cy_invested = investment + py_booked_amt

  today_pnl_amount = current-previous
  today_pnl_percentage = round((current-previous)*100/previous,2)

  curr_pnl_amount = current-invested
  curr_pnl_percentage = round((curr_pnl_amount)*100/(cy_invested),2)

  cy_pnl_amount = cy_booked_amt + curr_pnl_amount
  cy_pnl_percentage = round((cy_pnl_amount)*100/cy_invested,2)

  overall_pnl_amount = total_booked_amt + curr_pnl_amount
  overall_pnl_percentage = round((overall_pnl_amount)*100/investment,2)

  estimate_st = round(sum(df_portfolio_features['FTT']*df_portfolio_features['Shares']),0)  + reserve_amt
  est_st_pnl_amount = estimate_st-current
  est_st_pnl_percentage = round((est_st_pnl_amount)*100/current,2)

  estimate_lt = round(sum(df_portfolio_features['LTT']*df_portfolio_features['Shares']),0)  + reserve_amt
  est_lt_pnl_amount = estimate_lt-current
  est_lt_pnl_percentage = round((est_lt_pnl_amount)*100/current,2)

  total_profit = round(sum(df_portfolio_features[df_portfolio_features['Current P/L%'] > 0]['Current']) - sum(df_portfolio_features[df_portfolio_features['Current P/L%'] > 0]['Investment']),0)
  total_loss = round(sum(df_portfolio_features[df_portfolio_features['Current P/L%'] < 0]['Current']) - sum(df_portfolio_features[df_portfolio_features['Current P/L%'] < 0]['Investment']),0)

  cy_booked_percentage = round((cy_booked_amt)*100/current,2)
  py_booked_percentage = round((py_booked_amt)*100/investment,2)
  total_booked_percentage = round((total_booked_amt)*100/investment,2)

  print('-------------------')
  print('Initial Investment: ', format_amt(investment))
  print('CY Investment: ', format_amt(cy_invested))
  print('Reserve: ', format_amt(reserve_amt))
  print('Current: ',  format_amt(current))
  print('-------------------')
  print('Today PnL: '+ '{} ({}%)'.format(format_amt(today_pnl_amount), today_pnl_percentage))
  print('Current PnL: '+ '{} ({}%)'.format(format_amt(curr_pnl_amount), curr_pnl_percentage))
  print('CY Booked + Current PnL: '+ '{} ({}%)'.format(format_amt(cy_pnl_amount), cy_pnl_percentage))
  print('-------------------')
  print('Total profit: ', format_amt(total_profit))
  print('Total loss: ', format_amt(total_loss))
  print('-------------------')
  print('Total Booked + Current PnL: '+ '{} ({}%)'.format(format_amt(overall_pnl_amount), overall_pnl_percentage))
  print('Total Booked PnL: '+ '{} ({}%)'.format(format_amt(total_booked_amt), total_booked_percentage))
  print('Curr Year Booked PnL: '+ '{} ({}%)'.format(format_amt(cy_booked_amt), cy_booked_percentage))
  print('Prev Year Booked PnL: '+ '{} ({}%)'.format(format_amt(py_booked_amt), py_booked_percentage))
  print('===================')
  print('Est FTT: ',  format_amt(estimate_st))
  print('Est FTT PnL: '+ '{} ({}%)'.format(format_amt(est_st_pnl_amount), est_st_pnl_percentage))

  print('===================')
  print('Deployed: ', format_amt(investment))

  print('Current: ', format_amt(current))

  print('CAGR/XIRR %: '+'{}%'.format(cagr))

In [8]:
# get start and end date
start_date, end_date = get_start_end_date()

# get portfolio and prospects data
mypfs_df = get_mypfs_df()
mypps_df = get_mypps_df()
myinvmt_df = get_myinvmt_df()

# merge above datasets
mypf_df = pd.merge(mypfs_df, mypps_df, on="Symbol")

# seggregate dm and sv portfolio
dm_pf = mypf_df[mypf_df['InPortfolio'] == 'DM']
sv_pf = mypf_df[mypf_df['InPortfolio'] == 'SV']

# build portfolio stock dataframe
dm_stocks = get_stock_ids(dm_pf)
sv_stocks = get_stock_ids(sv_pf)
df_stocks = pd.concat([dm_pf,sv_pf], ignore_index = True)

# arrange common and diff stock features
common_cols = ['Symbol', 'Target', 'Criteria', 'Strategy', 'CumlRnk', 'LatestQtr', 'StarStock', 'Conviction', 'Category', 'InFolio', 'XIRR', 'MBQ']
diff_cols = ['Symbol', 'AvgCost', 'Shares']
df_stocks = arrange_features(df_stocks, common_cols, diff_cols)

# get common features
stock_ids = df_stocks['Symbol'].values
df_common_features = get_common_features(stock_ids, df_stocks)

df_common_features.reset_index(drop=True, inplace=True)
df_common_features.drop(['Date'], axis=1, inplace=True)
# get and print portfolio features
df_portfolio_features = get_portfolio_features(df_common_features)

print_portfolio_stats(df_portfolio_features, myinvmt_df)

df = df_portfolio_features
#plot_pie_chart(df, 'CapType', 'Current')
list_ox40n = list(df[df['MBQ'].str.contains('OX40N', na=False)]['Symbol'].values)

Run date time (IST): 2026-06-15 19:00:47
-------------------
qualified stocks: 92
with latest results: 31
still star stocks: 20
-------------------
Initial Investment:  1.40 C
CY Investment:  1.82 C
Reserve:  1.49 K
Current:  1.50 C
-------------------
Today PnL: 1.89 L (1.28%)
Current PnL: -32.94 L (-18.06%)
CY Booked + Current PnL: -30.86 L (-16.92%)
-------------------
Total profit:  2.92 L
Total loss:  -35.86 L
-------------------
Total Booked + Current PnL: 12.01 L (8.61%)
Total Booked PnL: 44.95 L (32.22%)
Curr Year Booked PnL: 2.08 L (1.38%)
Prev Year Booked PnL: 42.87 L (30.73%)
===================
Est FTT:  2.55 C
Est FTT PnL: 1.05 C (69.85%)
===================
Deployed:  1.40 C
Current:  1.50 C
CAGR/XIRR %: 3.48%

In [9]:
# top 5 near their targets
cols = ['Symbol', 'Today P/L%', 'Current P/L%', 'FTT%', 'OTT%', 'FTT Amt', 'Current P/L', 'Current', 'FTT', 'Dev%_PE', 'RSI_14','Conviction', 'Spread%',  'CumlRnk', 'RRR Ind', 'CurrAlloc%', 'Gained%', 'Criteria', 'Strategy', 'Category']
df_tmp = df_portfolio_features[~df_portfolio_features['Symbol'].isin(['ENRIN','BLUSPRING','DIGITIDE'])]
df_tmp = df_tmp.sort_values(by = 'FTT Amt', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
59,PIDILITIND,2.31,11.33,6.32,18.37,9929.0,15990.0,157100.0,1670.26,-22.05,73.0,X-LC,3.67,5.0,1.61,1.05,23.35,X40,ATH,CHEMICALS
51,KOTAKBANK,0.61,8.42,11.70,21.11,17565.0,11656.0,150128.0,453.24,-6.81,69.0,X-LC,6.18,12.0,0.66,1.00,14.81,X40,ATH,BANKS
72,SIS,1.57,-1.76,23.44,21.26,25567.0,-1956.0,109076.0,528.00,2602.59,64.0,H-SC,21.87,168.0,-0.08,0.73,62.18,OX40N,NTT,MISC
55,MASFIN,3.56,-4.75,27.62,21.57,25778.0,-4650.0,93330.0,397.04,-17.80,51.0,H-SC,3.45,167.0,-0.18,0.62,11.25,XR,ATH,FINANCE
53,M&M,3.00,1.70,21.32,23.38,30071.0,2363.0,141044.0,3802.40,-13.74,56.0,X-LC,10.66,25.0,0.08,0.94,6.93,X40N,ATH,AUTO

In [10]:
# top 5 today
df_tmp = df_portfolio_features.sort_values(by = 'Today P/L%', ascending=False)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
21,DEN,8.35,-44.21,154.67,42.07,72881.0,-37344.0,47120.0,75.0,68.39,66.0,M-SC,9.36,235.0,-0.51,0.31,28.15,AR,NTT,ENTERTAINMENT
85,VAIBHAVGBL,5.10,-25.26,115.09,60.77,157227.0,-46163.0,136612.0,521.0,57.58,63.0,H-SC,3.00,160.0,-0.29,0.91,38.13,XR,NTT,JEWELLERY
61,RAJESHEXPO,5.00,-84.50,545.64,0.07,116009.0,-115916.0,21261.0,518.0,679.04,28.0,L-SC,33.92,268.0,-1.00,0.14,5.00,OX40N,NTT,JEWELLERY
31,HATHWAY,4.96,-38.13,180.11,73.29,121142.0,-41460.0,67260.0,31.4,682.61,59.0,H-SC,11.50,171.0,-0.34,0.45,26.38,XR,NTT,ENTERTAINMENT
35,HDFCLIFE,4.65,-4.94,40.11,33.18,57114.0,-7406.0,142394.0,814.3,-25.76,48.0,X-LC,16.22,31.0,-0.13,0.95,6.59,X40,ATH,INSURANCE

In [11]:
# bottom 5 today
df_tmp = df_portfolio_features.sort_values(by = 'Today P/L%', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
91,ZYDUSLIFE,-1.50,14.74,18.20,35.63,43766.0,30896.0,240470.0,1286.17,0.00,63.0,H-MC,13.04,120.0,0.71,1.60,26.44,AR,ATH,PHARMA
56,MEDANTA,-1.23,4.36,21.81,27.12,40175.0,7688.0,184205.0,1486.00,1.14,53.0,X-SC,4.63,87.0,0.19,1.23,26.93,XY24,NTT,HEALTHCARE
19,COLPAL,-1.02,-21.87,79.01,39.86,162579.0,-57595.0,205770.0,3683.41,-5.40,51.0,X-MC,2.89,62.0,-0.35,1.37,16.39,XY25,ATH,FMCG
3,ALKYLAMINE,-0.93,-22.71,150.52,93.63,117460.0,-22927.0,78036.0,4546.37,-17.24,58.0,H-SC,8.32,142.0,-0.20,0.52,47.35,SR,ATH,CHEMICALS
37,HONAUT,-0.71,-6.90,62.53,51.31,112257.0,-13313.0,179525.0,58357.33,-22.64,63.0,X-SC,8.32,90.0,-0.12,1.20,36.39,X40N,ATH,ELECTRICAL

In [12]:
# top 5 to exit based on CumlRnk
df_tmp = df_portfolio_features[~df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])]
df_tmp = df_tmp[(df_tmp['Current P/L%'] > -1) & (df_tmp['Current P/L%'] < 1)].sort_values(by = 'CumlRnk', ascending=False)
df_tmp[cols].head()

Empty DataFrame
Columns: [Symbol, Today P/L%, Current P/L%, FTT%, OTT%, FTT Amt, Current P/L, Current, FTT, Dev%_PE, RSI_14, Conviction, Spread%, CumlRnk, RRR Ind, CurrAlloc%, Gained%, Criteria, Strategy, Category]
Index: []

In [13]:
# OX40N stocks to exit
df_tmp = df_portfolio_features[(df_portfolio_features['Symbol'].isin(list_ox40n))].sort_values(by = 'Current P/L%', ascending=False)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
25,FINCABLES,0.80,32.24,57.22,107.91,111720.0,47603.0,195247.0,1641.55,18.72,51.0,M-SC,23.50,220.0,0.43,1.30,46.89,OX40N,ATH,CABLES
72,SIS,1.57,-1.76,23.44,21.26,25567.0,-1956.0,109076.0,528.00,2602.59,64.0,H-SC,21.87,168.0,-0.08,0.73,62.18,OX40N,NTT,MISC
16,CERA,1.87,-18.16,51.38,23.89,73965.0,-31946.0,143957.0,9475.00,-21.00,72.0,H-SC,4.26,153.0,-0.43,0.96,38.34,OX40N,NTT,CERAMICS
50,KANSAINER,-0.02,-27.76,57.08,13.47,111195.0,-74862.0,194805.0,340.00,-37.92,58.0,H-SC,6.81,162.0,-0.67,1.30,36.07,XY24,NTT,PAINTS
43,INDIGOPNTS,1.01,-28.59,40.06,0.02,49938.0,-49902.0,124657.0,1408.00,90.29,60.0,M-SC,11.29,222.0,-1.00,0.83,41.43,OX40N,NTT,PAINTS

In [14]:
# top 5 to book for rotation
df_tmp = df_portfolio_features[(df_portfolio_features['Current P/L%'] > 20) ].sort_values(by = 'CumlRnk', ascending=False)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
25,FINCABLES,0.80,32.24,57.22,107.91,111720.0,47603.0,195247.0,1641.55,18.72,51.0,M-SC,23.50,220.0,0.43,1.30,46.89,OX40N,ATH,CABLES
68,SATIN,2.56,28.62,18.05,51.83,64142.0,79076.0,355360.0,274.00,15.64,58.0,H-SC,40.86,159.0,1.23,2.37,73.11,XY24,NTT,FINANCE

In [15]:
# top 5 to monitor for exit
df_tmp = df_portfolio_features[~df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])]
df_tmp = df_tmp[(df_tmp['Current P/L%'] > 0) ].sort_values(by = 'Dev%_PE', ascending=False)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
9,BANDHANBNK,3.07,1.44,89.68,92.42,253417.0,4020.0,282579.0,400.00,142.10,61.0,H-SC,20.89,174.0,0.02,1.88,55.67,XY24,NTT,BANKS
74,STARHEALTH,1.74,2.30,43.95,47.26,126394.0,6463.0,287586.0,761.00,61.57,58.0,H-SC,10.24,173.0,0.05,1.91,26.26,XY24,NTT,INSURANCE
25,FINCABLES,0.80,32.24,57.22,107.91,111720.0,47603.0,195247.0,1641.55,18.72,51.0,M-SC,23.50,220.0,0.43,1.30,46.89,OX40N,ATH,CABLES
68,SATIN,2.56,28.62,18.05,51.83,64142.0,79076.0,355360.0,274.00,15.64,58.0,H-SC,40.86,159.0,1.23,2.37,73.11,XY24,NTT,FINANCE
91,ZYDUSLIFE,-1.50,14.74,18.20,35.63,43766.0,30896.0,240470.0,1286.17,0.00,63.0,H-MC,13.04,120.0,0.71,1.60,26.44,AR,ATH,PHARMA

In [16]:
# top 5 to book for rotation from weak conviction
df_tmp = df_portfolio_features[~df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])]
df_tmp = df_tmp[~df_tmp['Criteria'].isin(['XY25','XY24','X40', 'X40N'])].sort_values(by = 'RRR Ind', ascending=False)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
91,ZYDUSLIFE,-1.50,14.74,18.20,35.63,43766.0,30896.0,240470.0,1286.17,0.00,63.0,H-MC,13.04,120.0,0.71,1.60,26.44,AR,ATH,PHARMA
25,FINCABLES,0.80,32.24,57.22,107.91,111720.0,47603.0,195247.0,1641.55,18.72,51.0,M-SC,23.50,220.0,0.43,1.30,46.89,OX40N,ATH,CABLES
73,SONACOMS,0.56,3.17,34.82,39.09,36339.0,3202.0,104361.0,804.02,-18.31,52.0,M-MC,18.48,193.0,0.09,0.69,47.63,AR,ATH,AUTO
75,SURYODAY,1.32,-2.09,25.66,23.03,44989.0,-3743.0,175328.0,216.00,90.79,59.0,H-SC,17.99,166.0,-0.08,1.17,47.62,XR,NTT,BANKS
72,SIS,1.57,-1.76,23.44,21.26,25567.0,-1956.0,109076.0,528.00,2602.59,64.0,H-SC,21.87,168.0,-0.08,0.73,62.18,OX40N,NTT,MISC

In [17]:
# top 5 to accumulate based on lowest RSI_14
df_tmp = df_portfolio_features[df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])].sort_values(by = 'RSI_14', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
27,GLAXO,0.05,-14.79,59.25,35.69,100606.0,-29484.0,169800.0,3380.16,-34.96,31.0,X-MC,9.98,56.0,-0.29,1.13,0.92,X40,ATH,PHARMA
58,PGHH,-0.02,-32.62,95.92,32.01,138002.0,-69648.0,143872.0,17616.87,-54.37,31.0,X-MC,19.27,57.0,-0.50,0.96,0.00,X40,ATH,FMCG
33,HCLTECH,0.87,-27.36,67.28,21.51,118231.0,-66194.0,175730.0,1872.35,-23.49,36.0,X-LC,18.48,8.0,-0.56,1.17,0.87,X40,ATH,IT
79,TCS,0.03,-36.53,96.76,24.88,284505.0,-169241.0,294032.0,4253.91,-46.25,39.0,X-LC,18.84,2.0,-0.59,1.96,1.24,X40,ATH,IT
40,ICICIPRULI,3.84,-19.55,61.94,30.28,98166.0,-38520.0,158485.0,787.27,-41.20,44.0,X-MC,16.72,78.0,-0.39,1.06,5.59,X40,ATH,INSURANCE

In [18]:
# top 5 to accumulate based on Spread and CumlRnk
df_tmp = df_portfolio_features[df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])]
df_tmp = df_tmp[(df_tmp['CumlRnk'] < 100)].sort_values(by = 'Spread%', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
49,JSWINFRA,1.19,0.24,16.15,16.43,35903.0,536.0,222310.0,342.00,-14.03,63.0,X-MC,1.86,61.0,0.01,1.48,25.67,X40N,NTT,REALTY
57,PAGEIND,1.48,2.23,30.67,33.59,84148.0,5986.0,274365.0,51217.29,-26.64,60.0,X-MC,2.78,55.0,0.07,1.83,30.29,X40,ATH,APPARELS
19,COLPAL,-1.02,-21.87,79.01,39.86,162579.0,-57595.0,205770.0,3683.41,-5.40,51.0,X-MC,2.89,62.0,-0.35,1.37,16.39,XY25,ATH,FMCG
15,CAMS,2.61,1.85,22.21,24.48,56974.0,4670.0,256526.0,950.00,-2.41,55.0,X-SC,3.08,89.0,0.08,1.71,24.89,X40N,NTT,MISC
59,PIDILITIND,2.31,11.33,6.32,18.37,9929.0,15990.0,157100.0,1670.26,-22.05,73.0,X-LC,3.67,5.0,1.61,1.05,23.35,X40,ATH,CHEMICALS

In [19]:
# top 5 to accumulate based on lowest Gained%
df_tmp = df_portfolio_features[df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])].sort_values(by = 'Gained%', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
58,PGHH,-0.02,-32.62,95.92,32.01,138002.0,-69648.0,143872.0,17616.87,-54.37,31.0,X-MC,19.27,57.0,-0.50,0.96,0.00,X40,ATH,FMCG
33,HCLTECH,0.87,-27.36,67.28,21.51,118231.0,-66194.0,175730.0,1872.35,-23.49,36.0,X-LC,18.48,8.0,-0.56,1.17,0.87,X40,ATH,IT
27,GLAXO,0.05,-14.79,59.25,35.69,100606.0,-29484.0,169800.0,3380.16,-34.96,31.0,X-MC,9.98,56.0,-0.29,1.13,0.92,X40,ATH,PHARMA
79,TCS,0.03,-36.53,96.76,24.88,284505.0,-169241.0,294032.0,4253.91,-46.25,39.0,X-LC,18.84,2.0,-0.59,1.96,1.24,X40,ATH,IT
39,ICICIGI,2.26,-8.14,29.43,18.89,54097.0,-16294.0,183815.0,2244.41,-22.78,44.0,X-MC,5.27,66.0,-0.30,1.22,3.05,X40,ATH,INSURANCE

In [20]:
# top 5 to accumulate based on lowest CurrAlloc%
df_tmp = df_portfolio_features[df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])].sort_values(by = 'CurrAlloc%', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
10,BATAINDIA,1.67,-56.12,208.10,35.20,117504.0,-72205.0,56465.0,2096.00,-25.92,49.0,X-SC,25.36,91.0,-0.61,0.38,11.98,X40,NTT,FOOTWEAR
64,RELAXO,-0.34,-55.77,244.36,52.31,156884.0,-80958.0,64202.0,1176.00,-52.96,61.0,X-SC,18.80,92.0,-0.52,0.43,43.55,X40N,NTT,FOOTWEAR
60,QUESS,0.63,0.71,72.67,73.90,78157.0,758.0,107551.0,424.00,-46.01,77.0,X-SC,5.67,80.0,0.01,0.72,46.61,XY24,NTT,MISC
28,GODREJCP,0.34,-7.21,41.69,31.47,57488.0,-10720.0,137894.0,1469.04,-2.48,53.0,X-LC,9.73,32.0,-0.19,0.92,5.80,X40N,ATH,FMCG
53,M&M,3.00,1.70,21.32,23.38,30071.0,2363.0,141044.0,3802.40,-13.74,56.0,X-LC,10.66,25.0,0.08,0.94,6.93,X40N,ATH,AUTO

In [21]:
# top 5 to accumulate based on CumlRnk
df_tmp = df_portfolio_features.sort_values(by = 'CumlRnk', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
47,ITC,0.98,-24.17,57.00,19.06,147036.0,-82208.0,257958.0,452.00,-58.35,49.0,X-LC,15.12,1.0,-0.56,1.72,3.94,X40,NTT,FMCG
79,TCS,0.03,-36.53,96.76,24.88,284505.0,-169241.0,294032.0,4253.91,-46.25,39.0,X-LC,18.84,2.0,-0.59,1.96,1.24,X40,ATH,IT
45,INFY,1.66,-22.74,73.76,34.24,178303.0,-71154.0,241734.0,1972.00,-39.04,45.0,X-LC,16.60,3.0,-0.40,1.61,5.89,X40,NTT,IT
81,TMPV,1.64,-9.77,51.36,36.58,164909.0,-34757.0,321084.0,600.00,-81.44,61.0,X-LC,13.70,4.0,-0.21,2.14,33.83,XY24,NTT,AUTO
59,PIDILITIND,2.31,11.33,6.32,18.37,9929.0,15990.0,157100.0,1670.26,-22.05,73.0,X-LC,3.67,5.0,1.61,1.05,23.35,X40,ATH,CHEMICALS

In [22]:
# top 5 for average up
df_tmp = df_portfolio_features[(df_portfolio_features['Dev%_200'] > 5)].sort_values(by = 'CurrAlloc%', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
44,INDUSINDBK,1.73,-31.10,92.88,32.89,49405.0,-24014.0,53192.0,1800.00,-350.70,58.0,L-MC,7.33,258.0,-0.49,0.35,30.93,XR,NTT,BANKS
3,ALKYLAMINE,-0.93,-22.71,150.52,93.63,117460.0,-22927.0,78036.0,4546.37,-17.24,58.0,H-SC,8.32,142.0,-0.20,0.52,47.35,SR,ATH,CHEMICALS
73,SONACOMS,0.56,3.17,34.82,39.09,36339.0,3202.0,104361.0,804.02,-18.31,52.0,M-MC,18.48,193.0,0.09,0.69,47.63,AR,ATH,AUTO
60,QUESS,0.63,0.71,72.67,73.90,78157.0,758.0,107551.0,424.00,-46.01,77.0,X-SC,5.67,80.0,0.01,0.72,46.61,XY24,NTT,MISC
72,SIS,1.57,-1.76,23.44,21.26,25567.0,-1956.0,109076.0,528.00,2602.59,64.0,H-SC,21.87,168.0,-0.08,0.73,62.18,OX40N,NTT,MISC

In [23]:
# top 5 RSP
df_tmp = df_portfolio_features.sort_values(by = 'RSP', ascending=False)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
18,COFFEEDAY,-0.56,-42.95,137.11,35.27,88821.0,-48768.0,64781.0,80.00,-55.73,56.0,L-SC,16.05,266.0,-0.55,0.43,59.75,XR,NTT,HOTELS
37,HONAUT,-0.71,-6.90,62.53,51.31,112257.0,-13313.0,179525.0,58357.33,-22.64,63.0,X-SC,8.32,90.0,-0.12,1.20,36.39,X40N,ATH,ELECTRICAL
60,QUESS,0.63,0.71,72.67,73.90,78157.0,758.0,107551.0,424.00,-46.01,77.0,X-SC,5.67,80.0,0.01,0.72,46.61,XY24,NTT,MISC
64,RELAXO,-0.34,-55.77,244.36,52.31,156884.0,-80958.0,64202.0,1176.00,-52.96,61.0,X-SC,18.80,92.0,-0.52,0.43,43.55,X40N,NTT,FOOTWEAR
69,SFL,0.86,-30.18,81.37,26.63,148970.0,-79141.0,183077.0,1287.00,38.71,73.0,M-SC,9.67,242.0,-0.53,1.22,52.59,XY24,NTT,MISC

In [24]:
# Top N allocation
df_tmp = df_portfolio_features.sort_values(by = 'CurrAlloc%', ascending=False)
top_n_values = [10, 25, 50]

sum_df = pd.DataFrame({
    'Top_N': top_n_values,
    'Sum_Alloc%': [df_tmp['CurrAlloc%'].head(n).sum() for n in top_n_values]
})

sum_df

   Top_N  Sum_Alloc%
0     10       19.68
1     25       42.85
2     50       72.68

In [25]:
# market-cap-wise allocation
df_tmp = df_portfolio_features[cols]
df_tmp.groupby(df_tmp['Conviction'].str[-2:])['CurrAlloc%'].sum().sort_values(ascending=False)

Conviction
SC    43.21
LC    31.31
MC    25.52
Name: CurrAlloc%, dtype: float64

In [26]:
# criteria-wise allocation
df_portfolio_features.groupby('Criteria')['CurrAlloc%'].sum().sort_values(ascending=False)

Criteria
XY24     27.97
X40      24.74
X40N     17.25
XR        8.97
OX40N     6.91
AR        6.79
XY25      6.54
SR        0.87
Name: CurrAlloc%, dtype: float64

In [27]:
# conviction-wise allocation
df_portfolio_features.groupby('Conviction')['CurrAlloc%'].sum().sort_values(ascending=False)

Conviction
X-LC    29.27
H-SC    22.77
X-MC    20.47
M-SC    10.02
X-SC     9.85
H-MC     2.72
M-MC     1.98
H-LC     1.20
M-LC     0.84
L-SC     0.57
L-MC     0.35
Name: CurrAlloc%, dtype: float64

In [28]:
# sector-wise stats
df_tmp = df_portfolio_features.groupby('Category')[['CurrAlloc%', 'Current', 'Current P/L', 'FTT Amt']].sum().sort_values(by=['Current', 'Current P/L'], ascending=False)
df_tmp['Current P/L%'] = round(df_tmp['Current P/L'] * 100 / df_tmp['Current'], 2)
df_tmp['FTT%'] = round(df_tmp['FTT Amt'] * 100 / df_tmp['Current'], 2)
cols = ['CurrAlloc%', 'Current P/L%', 'FTT%']
df_tmp[cols].sort_values(by=['CurrAlloc%'], ascending=False)

               CurrAlloc%  Current P/L%    FTT%
Category
FMCG                14.84        -18.86   60.55
FINANCE             10.92        -12.49   61.42
IT                   9.93        -50.82  126.23
MISC                 7.21        -24.01   77.88
AUTO                 6.94         -4.98   44.34
BANKS                5.85         -3.24   50.98
PAINTS               5.63        -16.54   36.77
INSURANCE            5.14         -7.22   43.48
PHARMA               4.92         -0.24   31.27
ELECTRICAL           4.04        -16.74   57.94
CHEMICALS            2.21        -22.44   95.41
HEALTHCARE           2.02        -18.26   49.11
APPARELS             1.83          2.18   30.67
AC                   1.82        -16.48   48.07
FOOTWEAR             1.71        -72.56  141.74
TRAVEL               1.66        -78.55  167.95
DURABLES             1.55        -67.33  108.04
REALTY               1.48          0.24   16.15
BREWERIES            1.46         -7.06   29.30
CERAMICS             1.43        -43.23   86.74
ENGINEERING          1.31        -23.47   79.94
CABLES               1.30         24.38   57.22
REFINERIES           1.12        -19.19   49.35
CEMENT               1.08        -64.73  187.97
JEWELLERY            1.05       -102.66  173.07
ENTERTAINMENT        0.76        -68.90  169.63
HOTELS               0.43        -75.28  137.11
TEXTILES             0.40        -51.77   95.04

In [29]:
# money to be made criteria-wise
df_portfolio_features.groupby('Criteria')['FTT Amt'].agg(['sum', 'count']).sort_values(by='sum', ascending=False)

                sum  count
Criteria
XY24      3396968.0     21
X40       1969084.0     19
XR        1333690.0     13
AR        1162109.0      9
X40N      1134576.0     13
OX40N      755183.0     10
XY25       453600.0      5
SR         288043.0      2

In [30]:
# money to be made conviction-wise
df_portfolio_features.groupby('Conviction')['FTT Amt'].agg(['sum', 'count']).sort_values(by='sum', ascending=False)

                  sum  count
Conviction
H-SC        3366356.0     24
X-LC        1893644.0     21
X-MC        1644405.0     15
M-SC        1412424.0     14
X-SC        1326134.0      9
H-MC         288601.0      2
L-SC         204830.0      2
M-LC         165843.0      1
M-MC          88124.0      2
H-LC          53487.0      1
L-MC          49405.0      1

In [31]:
# money to be made criteria and conviction-wise
df_portfolio_features.groupby(['Conviction', 'Criteria'])['FTT Amt'].agg(['sum', 'count']).sort_values(by='sum', ascending=False)

                           sum  count
Conviction Criteria
X-LC       X40       1040113.0     10
H-SC       XY24      1013783.0      6
           AR         955636.0      5
M-SC       XY24       818001.0      6
H-SC       XR         797701.0      7
X-SC       XY24       784818.0      4
X-MC       X40        713770.0      7
           X40N       463987.0      4
X-LC       X40N       344474.0      6
M-SC       OX40N      327981.0      5
X-SC       X40N       326115.0      3
H-SC       OX40N      311193.0      4
X-LC       XY24       310907.0      2
H-SC       SR         288043.0      2
H-MC       XY24       244835.0      1
X-MC       XY25       242024.0      2
           XY24       224624.0      2
X-SC       X40        215201.0      2
M-SC       XR         193561.0      2
M-LC       XR         165843.0      1
X-LC       XY25       159791.0      2
L-SC       OX40N      116009.0      1
           XR          88821.0      1
M-SC       AR          72881.0      1
H-LC       AR          53487.0      1
M-MC       XY25        51785.0      1
L-MC       XR          49405.0      1
H-MC       AR          43766.0      1
X-LC       XR          38359.0      1
M-MC       AR          36339.0      1

In [32]:
# notebook execution time

end_time = time.time()
execution_time = round(end_time - start_time, 0)
print(f"Notebook execution time: {execution_time} seconds")

Notebook execution time: 58.0 seconds