<a href="https://colab.research.google.com/github/ankit-rathi/Quantvesting_v2/blob/main/myStocks_Portfolio_Analysis.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
'''
!pip install pandas==2.2.2 -qq
!pip install pyxirr -qq
!pip install ta -qq
!pip install yfinance==0.2.59 -qq
'''

'\n!pip install pandas==2.2.2 -qq\n!pip install pyxirr -qq\n!pip install ta -qq\n!pip install yfinance==0.2.59 -qq\n'

In [2]:
# import libraries

import numpy as np
import pandas as pd
import datetime
import warnings
warnings.filterwarnings('ignore')
import yfinance as yfin
import ta
import matplotlib.pyplot as plt
import requests

In [3]:
# notebook start time
import time
import datetime
import pytz

start_time = time.time()

# function to print date timestamp
def print_date_time():
  tz_NY = pytz.timezone('Asia/Kolkata')
  datetime_NY = datetime.datetime.now(tz_NY)
  print("Run date time (IST):", datetime_NY.strftime("%Y-%m-%d %H:%M:%S"))

In [4]:
# function to get booked and reserved amount
def get_amt():
  # fetch the JSON data from the URL
  url = "https://raw.githubusercontent.com/ankit-rathi/Tradevesting_v1/main/data/myPortfolioAmts.json"
  response = requests.get(url)
  pf_amts = response.json()  # parse the JSON data

  # extract values from the JSON
  py_booked_amt_dm = pf_amts["py_booked_amt_dm"]
  py_booked_amt_sv = pf_amts["py_booked_amt_sv"]
  cy_booked_amt_dm = pf_amts["cy_booked_amt_dm"]
  cy_booked_amt_sv = pf_amts["cy_booked_amt_sv"]
  reserve_amt_dm = pf_amts["reserve_amt_dm"]
  reserve_amt_sv = pf_amts["reserve_amt_sv"]

  # perform calculations
  py_booked_amt = py_booked_amt_dm + py_booked_amt_sv
  cy_booked_amt = cy_booked_amt_dm + cy_booked_amt_sv
  reserve_amt = reserve_amt_dm + reserve_amt_sv
  total_booked_amt = py_booked_amt + cy_booked_amt

  return total_booked_amt, reserve_amt, cy_booked_amt, py_booked_amt

gen_output = 0

In [5]:
# function to format the amount
def format_amt(number):
    abs_number = abs(number)

    if abs_number >= 1_00_00_000:  # Crores
        formatted_amt = f"{number / 1_00_00_000:.2f} C"
    elif abs_number >= 1_00_000:  # Lakhs
        formatted_amt = f"{number / 1_00_000:.2f} L"
    elif abs_number >= 1_000:  # Thousands
        formatted_amt = f"{number / 1_000:.2f} K"
    else:
        formatted_amt = f"{number:.2f}"

    return formatted_amt

# function to set start and end date
def get_start_end_date():
  start_date = (datetime.date.today() + datetime.timedelta(days=-365)).strftime('%Y-%m-%d')
  end_date = (datetime.date.today() + datetime.timedelta(days=1)).strftime('%Y-%m-%d')
  return start_date, end_date

# function to fetch my portfolio csv
def get_mypfs_df():
  mypfs_df = pd.read_csv('https://raw.githubusercontent.com/ankit-rathi/Tradevesting_v1/main/data/myPortfolioStocks.csv')
  return mypfs_df

# function to fetch my prospects csv
def get_mypps_df():
  mypps_df = pd.read_csv('https://raw.githubusercontent.com/ankit-rathi/Tradevesting_v1/main/data/myProspectsScrips.csv')
  return mypps_df

# function to fetch screener data
def get_myscreen_df():
  myscreen_df = pd.read_csv('https://raw.githubusercontent.com/ankit-rathi/Tradevesting_v1/main/data/myScreenerDB.csv')
  return myscreen_df

# function to fetch momentum data
def get_myinvmt_df():
  myinvmt_df = pd.read_csv('https://raw.githubusercontent.com/ankit-rathi/Tradevesting_v1/main/data/myInvestments.csv')
  return myinvmt_df

# function to get the stock ids
def get_stock_ids(df_pf):
  stock_n100 = df_pf['Symbol'].unique()

  exclude = ['CADILAHC','MMTC', 'MASFIN']

  stock_ids = df_pf[~df_pf['Symbol'].isin(exclude) ]['Symbol'].unique()

  #mypf = mypf[mypf.Forecast.notnull()]
  #stock_ids = mypf['Symbol'].unique()

  #stock_ids.sort()
  return stock_ids

# get features from screener data
def get_screener_features():
  myscreen_df = get_myscreen_df()
  cols = ['Symbol', 'EPS', 'MedPE', 'ROCE%', 'ROE%', 'CapType']
  return myscreen_df[cols]

# get relative strength
def get_relative_strength(stock_list):

    # Dictionary to store stock tickers and their corresponding percentage price change
    stock_changes = {}

    # Loop through each stock and fetch its price data
    for stock in stock_list:
        try:
            # Download the stock data for the given date range
            stock_data = yfin.Ticker(stock + '.NS').history(period='1mo', interval='1d')[map(str.title, ['open', 'close', 'low', 'high', 'volume'])]

            # Calculate the percentage change for the stock
            if len(stock_data) > 0:
                start_price = stock_data['Close'].iloc[0]
                end_price = stock_data['Close'].iloc[-1]
                percent_change = round(((end_price - start_price) / start_price) * 100, 2)
                stock_changes[stock] = percent_change
            else:
                stock_changes[stock] = np.nan  # If no data is available, set to NaN

        except Exception as e:
            print(f"Error fetching data for {stock}: {e}")
            stock_changes[stock] = np.nan

    # Create a DataFrame with stock tickers and their percentage changes
    df = pd.DataFrame(list(stock_changes.items()), columns=['Symbol', 'Percent_Change'])

    # Drop any stocks with missing data (NaN values)
    df = df.dropna()

    # Calculate the percentile rank based on percentage change
    df['RSP'] = round(df['Percent_Change'].rank(pct=True) * 100, 2)
    cols = ['Symbol', 'RSP']
    df = df[cols]
    # Sort by percentile rank (optional)
    df = df.sort_values(by='RSP', ascending=False).reset_index(drop=True)

    return df

In [6]:
# function to get stock technicals
def stock_prec_dev(stock_symbol):
    #stock_symbol = 'ULTRACEMCO.NS'
    short_window = 20
    mid_window = 50
    long_window = 200
    moving_avg = 'SMA'

    start = datetime.datetime(*map(int, start_date.split('-')))
    end = datetime.datetime(*map(int, end_date.split('-')))

    stock_df = yfin.Ticker(stock_symbol + '.NS').history(period='max', interval='1d')[map(str.title, ['open', 'close', 'low', 'high', 'volume'])]

    stock_df['Max'] = round(max(stock_df['Close']),2)
    stock_df = stock_df[(stock_df.index <= end_date) & (stock_df.index >= start_date)]
    stock_df['200_SMA'] = round(stock_df['Close'].rolling(window = 200, min_periods = 1).mean(),0)
    stock_df['Dev%_200'] = round((stock_df['Close'] - stock_df['200_SMA'])*100/stock_df['200_SMA'],2)
    stock_df.dropna(axis = 0, inplace = True) # remove any null rows

    stock_df['20_SMA'] = stock_df['Close'].rolling(window=20).mean()
    stock_df['50_SMA'] = stock_df['Close'].rolling(window=50).mean()
    stock_df['Symbol'] = stock_symbol

    stock_df['Close'] = round(stock_df['Close'],2)
    stock_df['Min'] = round(min(stock_df['Close']),2)
    stock_df['RSI_14'] = ta.momentum.RSIIndicator(close=stock_df['Close'], window=14).rsi()
    stock_df['RSI_14'] = round(stock_df['RSI_14'],0)
    stock_df['Prev_Close'] = stock_df['Close'].shift(1)
    stock_df.drop(['Open', 'Low', 'High', 'Volume'], axis=1, inplace=True)
    stock_df = stock_df.tail(1)

    max_SMA = max(stock_df['20_SMA'].item(), stock_df['50_SMA'].item(), stock_df['200_SMA'].item())
    min_SMA = min(stock_df['20_SMA'].item(), stock_df['50_SMA'].item(), stock_df['200_SMA'].item())
    ABS_Spread = max_SMA - min_SMA
    stock_df['Spread%'] = round((ABS_Spread / stock_df['200_SMA'].item()) * 100,2)

    return stock_df

# function to compute stock attributes
def get_common_features(stock_ids, df_mypf):

  df_prec_dev = pd.DataFrame()
  df_tmp = get_screener_features()
  df_rs = get_relative_strength(stock_ids)

  for stock_id in stock_ids:
      tmp = stock_prec_dev(stock_id)
      tmp = tmp.reset_index()
      df_prec_dev = pd.concat([df_prec_dev, tmp], ignore_index = True)
  df_prec_dev = pd.merge(df_prec_dev, df_mypf, on= 'Symbol')
  df_prec_dev = pd.merge(df_prec_dev, df_tmp, on= 'Symbol', how='left')
  df_prec_dev = pd.merge(df_prec_dev, df_rs, on= 'Symbol', how='left')
  #print(df_prec_dev.columns)
  df_prec_dev['Curr_PE'] = round(df_prec_dev['Close']/df_prec_dev['EPS'],1)
  df_prec_dev['Dev%_PE'] = round((df_prec_dev['Curr_PE'] - df_prec_dev['MedPE'])*100/df_prec_dev['MedPE'],2)
  df_prec_dev['Conviction'] = df_prec_dev['Conviction'] + '-' + df_prec_dev['CapType']
  return df_prec_dev

# function to arrange stock features
def arrange_features(df_stocks, common_cols, diff_cols):
  df_stocks_common = df_stocks[common_cols].drop_duplicates()
  df_stocks_diff = df_stocks[diff_cols]
  df_stocks_diff['Investment'] = df_stocks_diff['AvgCost'] * df_stocks_diff['Shares']
  df_stocks_diff = df_stocks_diff.groupby(['Symbol'])[['Shares', 'Investment']].aggregate(['sum']).reset_index()
  df_stocks_diff.columns = ['Symbol', 'Shares', 'Investment']
  df_stocks_diff['AvgCost'] = round(df_stocks_diff['Investment']/df_stocks_diff['Shares'],2)
  df_stocks = pd.merge(df_stocks_diff, df_stocks_common, on='Symbol')
  return df_stocks

# plot fact distribution across dimension
def plot_pie_chart(df, dimension, fact):
  # grouping the data by category and calculating the sum of fact for each type
  grouped_data = df.groupby(dimension)[fact].sum()

  # sorting the grouped data in descending order
  grouped_data = grouped_data.sort_values(ascending=False)

  # creating a pie chart
  grouped_data.plot.pie(autopct='%1.1f%%', startangle=90, figsize=(6, 6))

  # adding a title and displaying the plot
  plt.title(f'{dimension} {fact} Distribution')
  plt.ylabel('')  # To hide the y-label
  plt.show()

In [7]:
# function to get portfolio features

def get_portfolio_features(df_common_features):

  print_date_time()
  print('-------------------')

  #df_common_features["Target"] = df_common_features["Target"].fillna(df_common_features["Max"])
  df_common_features['NTT'] = np.where(df_common_features['Strategy']== 'NTT', df_common_features["Target"], df_common_features['Max'])
  df_common_features['LTT'] = np.where(df_common_features['Strategy']== 'BTT', df_common_features["Target"], df_common_features['Max'])
  df_common_features['BOL'] = df_common_features['Min']

  tmp_df = df_common_features[df_common_features['Symbol'].isin(mypf_df[mypf_df['InPortfolio'] != 'NA'].Symbol.values)]
  print('qualified stocks: '+str(len(tmp_df['Symbol'].unique())))
  tmp_df1 = tmp_df[tmp_df['LatestQtr'] == 1]
  print('with latest results: '+str(len(tmp_df1['Symbol'].unique())))
  tmp_df1 = tmp_df1[tmp_df1['StarStock'] == 1]
  print('still star stocks: '+str(len(tmp_df1['Symbol'].unique())))
  tmp_df['Investment'] = tmp_df['AvgCost'] * tmp_df['Shares']
  tmp_df['Current'] = round(tmp_df['Close'] * tmp_df['Shares'],0)
  tmp_df['Previous'] = tmp_df['Prev_Close'] * tmp_df['Shares']
  tmp_df['EstimatedST'] = tmp_df['NTT'] * tmp_df['Shares']
  tmp_df['EstimatedLT'] = tmp_df['LTT'] * tmp_df['Shares']
  tmp_df['Current P/L'] = round((tmp_df['Current'] - tmp_df['Investment']),0)
  tmp_df['Today P/L%'] = round((tmp_df['Current'] - tmp_df['Previous'])*100/tmp_df['Previous'],2)
  tmp_df['Current P/L%'] = round((tmp_df['Current'] - tmp_df['Investment'])*100/tmp_df['Investment'],2)
  tmp_df['EstimatedST P/L%'] = round((tmp_df['EstimatedST'] - tmp_df['Investment'])*100/tmp_df['Investment'],2)
  tmp_df['EstimatedLT P/L%'] = round((tmp_df['EstimatedLT'] - tmp_df['Investment'])*100/tmp_df['Investment'],2)
  tmp_df['NTT%'] = round((tmp_df['NTT'] - tmp_df['Close'])*100/tmp_df['Close'],2)
  tmp_df['LTT%'] = round((tmp_df['LTT'] - tmp_df['Close'])*100/tmp_df['Close'],2)
  tmp_df['Gained%'] = round((tmp_df['Close'] - tmp_df['BOL'])*100/tmp_df['BOL'],2)
  investment = round(sum(tmp_df['AvgCost']*tmp_df['Shares']),0)
  current = round(sum(tmp_df['Close']*tmp_df['Shares']),0)
  tmp_df['InitAlloc%'] = round(tmp_df['Investment']*100/investment,2)
  tmp_df['CurrAlloc%'] = round(tmp_df['Current']*100/current,2)
  tmp_df['FTT'] = tmp_df['LTT']
  tmp_df.loc[tmp_df['Strategy'] == 'NTT', 'FTT'] = tmp_df['NTT']
  tmp_df['FTT%'] = tmp_df['LTT%']
  tmp_df.loc[tmp_df['Strategy'] == 'NTT', 'FTT%'] = tmp_df['NTT%']
  tmp_df['FTT Amt'] = round(tmp_df['FTT%'] * tmp_df['Current']/100,0)
  tmp_df['OTT%'] = round((tmp_df['FTT'] - tmp_df['AvgCost'])*100/tmp_df['AvgCost'],2)
  tmp_df['RRR Ind'] = round(tmp_df['Current P/L']/tmp_df['FTT Amt'],2)
  tmp_df['Risk Ind'] = round(tmp_df['Current P/L%']*tmp_df['CurrAlloc%'],0)

  return tmp_df

# function to print portfolio features
def print_portfolio_stats(df_portfolio_features, myinvmt_df):
  from pyxirr import xirr

  total_booked_amt, reserve_amt, cy_booked_amt, py_booked_amt = get_amt()

  dates = myinvmt_df['Date'].values
  dates = np.append(dates, datetime.date.today().strftime('%d-%b-%y'))
  investment = myinvmt_df['Investment'].values
  dates= pd.to_datetime(dates)

  current = round(sum(df_portfolio_features['Close']*df_portfolio_features['Shares']),0) + reserve_amt
  investment_xirr = np.append(investment, current)
  cagr = round(xirr(pd.DataFrame({"dates": dates, "amounts": investment_xirr}))*100,2)

  investment = -sum(investment)
  invested = round(sum(df_portfolio_features['AvgCost']*df_portfolio_features['Shares']),0) + reserve_amt
  previous = round(sum(df_portfolio_features['Prev_Close']*df_portfolio_features['Shares']),0) + reserve_amt
  cy_invested = investment + py_booked_amt

  today_pnl_amount = current-previous
  today_pnl_percentage = round((current-previous)*100/previous,2)

  curr_pnl_amount = current-invested
  curr_pnl_percentage = round((curr_pnl_amount)*100/(cy_invested),2)

  cy_pnl_amount = cy_booked_amt + curr_pnl_amount
  cy_pnl_percentage = round((cy_pnl_amount)*100/cy_invested,2)

  overall_pnl_amount = total_booked_amt + curr_pnl_amount
  overall_pnl_percentage = round((overall_pnl_amount)*100/investment,2)

  estimate_st = round(sum(df_portfolio_features['FTT']*df_portfolio_features['Shares']),0)  + reserve_amt
  est_st_pnl_amount = estimate_st-current
  est_st_pnl_percentage = round((est_st_pnl_amount)*100/current,2)

  estimate_lt = round(sum(df_portfolio_features['LTT']*df_portfolio_features['Shares']),0)  + reserve_amt
  est_lt_pnl_amount = estimate_lt-current
  est_lt_pnl_percentage = round((est_lt_pnl_amount)*100/current,2)

  total_profit = round(sum(df_portfolio_features[df_portfolio_features['Current P/L%'] > 0]['Current']) - sum(df_portfolio_features[df_portfolio_features['Current P/L%'] > 0]['Investment']),0)
  total_loss = round(sum(df_portfolio_features[df_portfolio_features['Current P/L%'] < 0]['Current']) - sum(df_portfolio_features[df_portfolio_features['Current P/L%'] < 0]['Investment']),0)

  cy_booked_percentage = round((cy_booked_amt)*100/current,2)
  py_booked_percentage = round((py_booked_amt)*100/investment,2)
  total_booked_percentage = round((total_booked_amt)*100/investment,2)

  print('-------------------')
  print('Initial Investment: ', format_amt(investment))
  print('CY Investment: ', format_amt(cy_invested))
  print('Reserve: ', format_amt(reserve_amt))
  print('Current: ',  format_amt(current))
  print('-------------------')
  print('Today PnL: '+ '{} ({}%)'.format(format_amt(today_pnl_amount), today_pnl_percentage))
  print('Current PnL: '+ '{} ({}%)'.format(format_amt(curr_pnl_amount), curr_pnl_percentage))
  print('CY Booked + Current PnL: '+ '{} ({}%)'.format(format_amt(cy_pnl_amount), cy_pnl_percentage))
  print('-------------------')
  print('Total profit: ', format_amt(total_profit))
  print('Total loss: ', format_amt(total_loss))
  print('-------------------')
  print('Total Booked + Current PnL: '+ '{} ({}%)'.format(format_amt(overall_pnl_amount), overall_pnl_percentage))
  print('Total Booked PnL: '+ '{} ({}%)'.format(format_amt(total_booked_amt), total_booked_percentage))
  print('Curr Year Booked PnL: '+ '{} ({}%)'.format(format_amt(cy_booked_amt), cy_booked_percentage))
  print('Prev Year Booked PnL: '+ '{} ({}%)'.format(format_amt(py_booked_amt), py_booked_percentage))
  print('===================')
  print('Est FTT: ',  format_amt(estimate_st))
  print('Est FTT PnL: '+ '{} ({}%)'.format(format_amt(est_st_pnl_amount), est_st_pnl_percentage))

  print('===================')
  print('Deployed: ', format_amt(investment))

  print('Current: ', format_amt(current))

  print('CAGR/XIRR %: '+'{}%'.format(cagr))

In [8]:
# get start and end date
start_date, end_date = get_start_end_date()

# get portfolio and prospects data
mypfs_df = get_mypfs_df()
mypps_df = get_mypps_df()
myinvmt_df = get_myinvmt_df()

# merge above datasets
mypf_df = pd.merge(mypfs_df, mypps_df, on="Symbol")

# seggregate dm and sv portfolio
dm_pf = mypf_df[mypf_df['InPortfolio'] == 'DM']
sv_pf = mypf_df[mypf_df['InPortfolio'] == 'SV']

# build portfolio stock dataframe
dm_stocks = get_stock_ids(dm_pf)
sv_stocks = get_stock_ids(sv_pf)
df_stocks = pd.concat([dm_pf,sv_pf], ignore_index = True)

# arrange common and diff stock features
common_cols = ['Symbol', 'Target', 'Criteria', 'Strategy', 'CumlRnk', 'LatestQtr', 'StarStock', 'Conviction', 'Category', 'InFolio', 'XIRR', 'MBQ']
diff_cols = ['Symbol', 'AvgCost', 'Shares']
df_stocks = arrange_features(df_stocks, common_cols, diff_cols)

# get common features
stock_ids = df_stocks['Symbol'].values
df_common_features = get_common_features(stock_ids, df_stocks)

df_common_features.reset_index(drop=True, inplace=True)
df_common_features.drop(['Date'], axis=1, inplace=True)
# get and print portfolio features
df_portfolio_features = get_portfolio_features(df_common_features)

print_portfolio_stats(df_portfolio_features, myinvmt_df)

df = df_portfolio_features
#plot_pie_chart(df, 'CapType', 'Current')
list_ox40n = list(df[df['MBQ'].str.contains('OX40N', na=False)]['Symbol'].values)

Run date time (IST): 2026-03-17 09:49:50
-------------------
qualified stocks: 86
with latest results: 26
still star stocks: 16
-------------------
Initial Investment:  1.36 C
CY Investment:  1.62 C
Reserve:  1.61 K
Current:  1.32 C
-------------------
Today PnL: -1.14 L (-0.86%)
Current PnL: -45.27 L (-27.86%)
CY Booked + Current PnL: -29.38 L (-18.08%)
-------------------
Total profit:  67.56 K
Total loss:  -45.95 L
-------------------
Total Booked + Current PnL: -2.40 L (-1.77%)
Total Booked PnL: 42.87 L (31.64%)
Curr Year Booked PnL: 15.89 L (12.05%)
Prev Year Booked PnL: 26.98 L (19.91%)
===================
Est FTT:  2.48 C
Est FTT PnL: 1.16 C (88.0%)
===================
Deployed:  1.36 C
Current:  1.32 C
CAGR/XIRR %: -1.36%

In [9]:
# top 5 near their targets
cols = ['Symbol', 'Today P/L%', 'Current P/L%', 'FTT%', 'OTT%', 'FTT Amt', 'Current P/L', 'Current', 'FTT', 'Dev%_PE', 'RSI_14','Conviction', 'Spread%',  'CumlRnk', 'RRR Ind', 'CurrAlloc%', 'Gained%', 'Criteria', 'Strategy', 'Category']
df_tmp = df_portfolio_features[~df_portfolio_features['Symbol'].isin(['ENRIN','BLUSPRING','DIGITIDE'])]
df_tmp = df_tmp.sort_values(by = 'FTT Amt', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
50,MASFIN,-4.05,-11.39,37.19,21.57,32288.0,-11160.0,86820.0,397.04,-23.67,32.0,H-SC,2.86,167.0,-0.35,0.66,20.40,XR,ATH,FINANCE
77,TTKPRESTIG,-9.87,-36.50,57.63,0.09,36880.0,-36783.0,63994.0,770.00,48.56,42.0,M-SC,16.00,250.0,-1.00,0.49,8.12,OX40N,NTT,DURABLES
37,ICICIGI,0.25,-2.44,22.33,19.34,43593.0,-4889.0,195220.0,2252.93,-17.87,39.0,X-MC,2.02,66.0,-0.11,1.48,7.92,X40,ATH,INSURANCE
2,ABBOTINDIA,-0.87,-10.35,31.69,18.07,50815.0,-18505.0,160350.0,35195.00,-23.63,46.0,X-MC,10.92,58.0,-0.36,1.22,1.65,X40,ATH,PHARMA
67,SONACOMS,1.85,-14.36,62.41,39.09,54068.0,-14525.0,86634.0,804.02,-32.08,43.0,M-MC,9.23,193.0,-0.27,0.66,22.56,AR,ATH,AUTO

In [10]:
# top 5 today
df_tmp = df_portfolio_features.sort_values(by = 'Today P/L%', ascending=False)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
34,HDFCBANK,3.07,0.74,27.43,28.37,64904.0,1731.0,236616.0,1073.00,-14.61,35.0,X-LC,8.84,26.0,0.03,1.79,3.07,X40,BTT,BANKS
47,JSWINFRA,2.18,-12.90,33.67,16.43,65039.0,-28607.0,193167.0,342.00,-25.25,47.0,X-MC,11.36,61.0,-0.44,1.47,3.71,X40N,NTT,REALTY
13,BERGEPAINT,2.12,-23.25,63.28,25.32,125177.0,-59935.0,197814.0,680.00,-27.38,28.0,X-MC,16.44,68.0,-0.48,1.50,2.12,XY24,NTT,PAINTS
6,ASIANPAINT,1.99,-19.37,54.43,24.52,124395.0,-54898.0,228541.0,3460.25,-18.66,35.0,X-LC,7.24,30.0,-0.44,1.73,2.04,X40,ATH,PAINTS
67,SONACOMS,1.85,-14.36,62.41,39.09,54068.0,-14525.0,86634.0,804.02,-32.08,43.0,M-MC,9.23,193.0,-0.27,0.66,22.56,AR,ATH,AUTO

In [11]:
# bottom 5 today
df_tmp = df_portfolio_features.sort_values(by = 'Today P/L%', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
77,TTKPRESTIG,-9.87,-36.50,57.63,0.09,36880.0,-36783.0,63994.0,770.00,48.56,42.0,M-SC,16.00,250.0,-1.00,0.49,8.12,OX40N,NTT,DURABLES
11,BANDHANBNK,-9.20,-23.34,151.00,92.42,322448.0,-65017.0,213542.0,400.00,83.19,39.0,H-SC,9.32,174.0,-0.20,1.62,17.63,XY24,NTT,BANKS
55,RAJESHEXPO,-8.23,-80.49,412.87,0.07,110505.0,-110412.0,26765.0,518.00,881.06,19.0,L-SC,24.63,268.0,-1.00,0.20,0.00,OX40N,NTT,JEWELLERY
69,SURYODAY,-5.59,-29.03,73.35,23.03,93222.0,-51979.0,127092.0,216.00,38.16,45.0,H-SC,7.72,166.0,-0.56,0.96,26.10,XR,NTT,BANKS
53,PGHH,-4.63,-24.80,75.55,32.01,121303.0,-52960.0,160560.0,17616.87,-49.14,16.0,X-MC,12.42,57.0,-0.44,1.22,0.00,X40,ATH,FMCG

In [12]:
# top 5 to exit based on CumlRnk
df_tmp = df_portfolio_features[~df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])]
df_tmp = df_tmp[(df_tmp['Current P/L%'] > -1) & (df_tmp['Current P/L%'] < 1)].sort_values(by = 'CumlRnk', ascending=False)
df_tmp[cols].head()

Empty DataFrame
Columns: [Symbol, Today P/L%, Current P/L%, FTT%, OTT%, FTT Amt, Current P/L, Current, FTT, Dev%_PE, RSI_14, Conviction, Spread%, CumlRnk, RRR Ind, CurrAlloc%, Gained%, Criteria, Strategy, Category]
Index: []

In [13]:
# OX40N stocks to exit
df_tmp = df_portfolio_features[(df_portfolio_features['Symbol'].isin(list_ox40n))].sort_values(by = 'Current P/L%', ascending=False)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
26,FINCABLES,-0.98,7.35,93.67,107.91,148468.0,10857.0,158501.0,1641.55,-3.60,49.0,M-SC,7.79,220.0,0.07,1.20,19.25,OX40N,ATH,CABLES
66,SIS,-0.52,-36.17,89.96,21.26,63761.0,-40155.0,70877.0,528.00,1656.48,30.0,H-SC,12.24,168.0,-0.63,0.54,0.00,OX40N,NTT,MISC
77,TTKPRESTIG,-9.87,-36.50,57.63,0.09,36880.0,-36783.0,63994.0,770.00,48.56,42.0,M-SC,16.00,250.0,-1.00,0.49,8.12,OX40N,NTT,DURABLES
72,TATAELXSI,-2.52,-40.22,120.86,32.03,95250.0,-53025.0,78810.0,9161.00,-25.24,24.0,H-SC,18.20,158.0,-0.56,0.60,0.00,OX40N,NTT,IT
70,SYMPHONY,-2.35,-40.27,67.36,-0.03,68859.0,-68915.0,102226.0,1306.00,-51.97,38.0,M-SC,14.50,205.0,-1.00,0.78,3.38,OX40N,NTT,DURABLES

In [14]:
# top 5 to book for rotation
df_tmp = df_portfolio_features[(df_portfolio_features['Current P/L%'] > 20) ].sort_values(by = 'CumlRnk', ascending=False)
df_tmp[cols].head()

Empty DataFrame
Columns: [Symbol, Today P/L%, Current P/L%, FTT%, OTT%, FTT Amt, Current P/L, Current, FTT, Dev%_PE, RSI_14, Conviction, Spread%, CumlRnk, RRR Ind, CurrAlloc%, Gained%, Criteria, Strategy, Category]
Index: []

In [15]:
# top 5 to monitor for exit
df_tmp = df_portfolio_features[~df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])]
df_tmp = df_tmp[(df_tmp['Current P/L%'] > 0) ].sort_values(by = 'Dev%_PE', ascending=False)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
26,FINCABLES,-0.98,7.35,93.67,107.91,148468.0,10857.0,158501.0,1641.55,-3.60,49.0,M-SC,7.79,220.0,0.07,1.20,19.25,OX40N,ATH,CABLES
1,ABB,-2.99,13.78,27.94,45.57,83170.0,36053.0,297672.0,7934.00,-26.88,59.0,H-MC,11.44,125.0,0.43,2.26,32.19,AR,NTT,ELECTRICAL

In [16]:
# top 5 to book for rotation from weak conviction
df_tmp = df_portfolio_features[~df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])]
df_tmp = df_tmp[~df_tmp['Criteria'].isin(['XY25','XY24','X40', 'X40N'])].sort_values(by = 'RRR Ind', ascending=False)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
1,ABB,-2.99,13.78,27.94,45.57,83170.0,36053.0,297672.0,7934.00,-26.88,59.0,H-MC,11.44,125.0,0.43,2.26,32.19,AR,NTT,ELECTRICAL
26,FINCABLES,-0.98,7.35,93.67,107.91,148468.0,10857.0,158501.0,1641.55,-3.60,49.0,M-SC,7.79,220.0,0.07,1.20,19.25,OX40N,ATH,CABLES
40,INDIAMART,-0.09,-9.76,129.08,106.72,143666.0,-12036.0,111300.0,4810.62,-59.38,41.0,H-SC,9.80,140.0,-0.08,0.84,11.34,AR,ATH,MISC
85,ZYDUSLIFE,-1.19,-5.60,43.68,35.63,86411.0,-11746.0,197828.0,1286.17,-18.02,45.0,H-MC,5.08,120.0,-0.14,1.50,10.13,AR,ATH,PHARMA
84,WIPRO,-3.61,-21.89,120.54,72.27,159542.0,-37092.0,132356.0,420.00,-29.71,25.0,M-LC,15.63,98.0,-0.23,1.00,0.00,XR,NTT,IT

In [17]:
# top 5 to accumulate based on lowest RSI_14
df_tmp = df_portfolio_features[df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])].sort_values(by = 'RSI_14', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
58,RELAXO,-3.97,-63.35,315.55,52.31,167885.0,-91956.0,53204.0,1176.00,-60.99,14.0,X-SC,20.92,92.0,-0.55,0.40,0.00,X40N,NTT,FOOTWEAR
12,BATAINDIA,-4.20,-56.78,212.84,35.20,118360.0,-73060.0,55610.0,2096.00,-27.08,15.0,X-SC,27.55,91.0,-0.62,0.42,0.00,X40,NTT,FOOTWEAR
53,PGHH,-4.63,-24.80,75.55,32.01,121303.0,-52960.0,160560.0,17616.87,-49.14,16.0,X-MC,12.42,57.0,-0.44,1.22,0.00,X40,ATH,FMCG
73,TCS,-1.69,-30.43,81.94,26.57,264087.0,-140980.0,322293.0,4311.59,-41.00,17.0,X-LC,15.25,2.0,-0.53,2.44,0.00,X40,ATH,IT
3,ACC,0.28,-38.23,182.98,74.81,303081.0,-102492.0,165636.0,3906.00,-56.11,18.0,X-SC,14.10,85.0,-0.34,1.26,0.28,XY24,BTT,CEMENT

In [18]:
# top 5 to accumulate based on Spread and CumlRnk
df_tmp = df_portfolio_features[df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])]
df_tmp = df_tmp[(df_tmp['CumlRnk'] < 100)].sort_values(by = 'Spread%', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
78,UNITDSPR,-0.31,-3.53,25.18,20.77,56879.0,-8256.0,225888.0,1644.00,-14.48,41.0,X-MC,0.93,64.0,-0.15,1.71,2.94,X40N,NTT,BREWERIES
37,ICICIGI,0.25,-2.44,22.33,19.34,43593.0,-4889.0,195220.0,2252.93,-17.87,39.0,X-MC,2.02,66.0,-0.11,1.48,7.92,X40,ATH,INSURANCE
21,DABUR,0.54,-10.86,61.20,43.70,135335.0,-26932.0,221136.0,735.00,-19.10,30.0,X-MC,2.36,70.0,-0.20,1.68,2.56,XY24,BTT,FMCG
38,ICICIPRULI,1.04,-2.39,33.93,30.73,65244.0,-4714.0,192291.0,790.00,-28.60,30.0,X-MC,2.85,78.0,-0.07,1.46,10.01,X40,ATH,INSURANCE
75,TMPV,0.57,-28.02,89.75,36.58,229869.0,-99719.0,256122.0,600.00,-84.72,31.0,X-LC,2.96,4.0,-0.43,1.94,0.67,XY24,NTT,AUTO

In [19]:
# top 5 to accumulate based on lowest Gained%
df_tmp = df_portfolio_features[df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])].sort_values(by = 'Gained%', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
12,BATAINDIA,-4.20,-56.78,212.84,35.20,118360.0,-73060.0,55610.0,2096.00,-27.08,15.0,X-SC,27.55,91.0,-0.62,0.42,0.0,X40,NTT,FOOTWEAR
9,BAJAJHFL,-0.86,-27.25,122.86,62.13,244039.0,-74414.0,198632.0,181.50,-40.19,26.0,X-MC,19.04,60.0,-0.30,1.51,0.0,X40N,ATH,FINANCE
20,COLPAL,-1.12,-26.52,92.58,41.51,179161.0,-69845.0,193520.0,3726.84,-11.01,29.0,X-MC,4.16,62.0,-0.39,1.47,0.0,XY25,ATH,FMCG
58,RELAXO,-3.97,-63.35,315.55,52.31,167885.0,-91956.0,53204.0,1176.00,-60.99,14.0,X-SC,20.92,92.0,-0.55,0.40,0.0,X40N,NTT,FOOTWEAR
54,QUESS,-3.95,-28.41,142.91,73.90,109259.0,-30340.0,76453.0,424.00,-61.43,29.0,X-SC,18.82,80.0,-0.28,0.58,0.0,XY24,NTT,MISC

In [20]:
# top 5 to accumulate based on lowest CurrAlloc%
df_tmp = df_portfolio_features[df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])].sort_values(by = 'CurrAlloc%', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
58,RELAXO,-3.97,-63.35,315.55,52.31,167885.0,-91956.0,53204.0,1176.00,-60.99,14.0,X-SC,20.92,92.0,-0.55,0.40,0.00,X40N,NTT,FOOTWEAR
12,BATAINDIA,-4.20,-56.78,212.84,35.20,118360.0,-73060.0,55610.0,2096.00,-27.08,15.0,X-SC,27.55,91.0,-0.62,0.42,0.00,X40,NTT,FOOTWEAR
54,QUESS,-3.95,-28.41,142.91,73.90,109259.0,-30340.0,76453.0,424.00,-61.43,29.0,X-SC,18.82,80.0,-0.28,0.58,0.00,XY24,NTT,MISC
36,HONAUT,-1.38,-23.16,96.92,51.31,143611.0,-44663.0,148175.0,58357.33,-36.07,34.0,X-SC,14.09,90.0,-0.31,1.12,0.00,X40N,ATH,ELECTRICAL
51,MEDANTA,-3.37,-11.38,43.44,27.12,67956.0,-20081.0,156436.0,1486.00,-14.08,31.0,X-SC,9.20,87.0,-0.30,1.19,0.58,XY24,NTT,HEALTHCARE

In [21]:
# top 5 to accumulate based on CumlRnk
df_tmp = df_portfolio_features.sort_values(by = 'CumlRnk', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
45,ITC,1.77,-19.19,47.33,19.06,130107.0,-65273.0,274893.0,452.00,-55.52,39.0,X-LC,17.14,1.0,-0.50,2.09,1.77,X40,NTT,FMCG
73,TCS,-1.69,-30.43,81.94,26.57,264087.0,-140980.0,322293.0,4311.59,-41.00,17.0,X-LC,15.25,2.0,-0.53,2.44,0.00,X40,ATH,IT
43,INFY,-1.82,-16.57,60.90,34.24,158981.0,-51835.0,261053.0,1972.00,-34.33,21.0,X-LC,13.50,3.0,-0.33,1.98,0.00,X40,NTT,IT
75,TMPV,0.57,-28.02,89.75,36.58,229869.0,-99719.0,256122.0,600.00,-84.72,31.0,X-LC,2.96,4.0,-0.43,1.94,0.67,XY24,NTT,AUTO
33,HCLTECH,-1.29,-15.10,45.85,23.83,94177.0,-36521.0,205403.0,1908.19,-10.67,24.0,X-LC,10.20,8.0,-0.39,1.56,0.00,X40,ATH,IT

In [22]:
# top 5 for average up
df_tmp = df_portfolio_features[(df_portfolio_features['Dev%_200'] > 5)].sort_values(by = 'CurrAlloc%', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
1,ABB,-2.99,13.78,27.94,45.57,83170.0,36053.0,297672.0,7934.0,-26.88,59.0,H-MC,11.44,125.0,0.43,2.26,32.19,AR,NTT,ELECTRICAL

In [23]:
# top 5 RSP
df_tmp = df_portfolio_features.sort_values(by = 'RSP', ascending=False)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
1,ABB,-2.99,13.78,27.94,45.57,83170.0,36053.0,297672.0,7934.00,-26.88,59.0,H-MC,11.44,125.0,0.43,2.26,32.19,AR,NTT,ELECTRICAL
26,FINCABLES,-0.98,7.35,93.67,107.91,148468.0,10857.0,158501.0,1641.55,-3.60,49.0,M-SC,7.79,220.0,0.07,1.20,19.25,OX40N,ATH,CABLES
2,ABBOTINDIA,-0.87,-10.35,31.69,18.07,50815.0,-18505.0,160350.0,35195.00,-23.63,46.0,X-MC,10.92,58.0,-0.36,1.22,1.65,X40,ATH,PHARMA
69,SURYODAY,-5.59,-29.03,73.35,23.03,93222.0,-51979.0,127092.0,216.00,38.16,45.0,H-SC,7.72,166.0,-0.56,0.96,26.10,XR,NTT,BANKS
85,ZYDUSLIFE,-1.19,-5.60,43.68,35.63,86411.0,-11746.0,197828.0,1286.17,-18.02,45.0,H-MC,5.08,120.0,-0.14,1.50,10.13,AR,ATH,PHARMA

In [24]:
# Top N allocation
df_tmp = df_portfolio_features.sort_values(by = 'CurrAlloc%', ascending=False)
top_n_values = [10, 25, 50]

sum_df = pd.DataFrame({
    'Top_N': top_n_values,
    'Sum_Alloc%': [df_tmp['CurrAlloc%'].head(n).sum() for n in top_n_values]
})

sum_df

   Top_N  Sum_Alloc%
0     10       20.53
1     25       45.58
2     50       78.20

In [25]:
# market-cap-wise allocation
df_tmp = df_portfolio_features[cols]
df_tmp.groupby(df_tmp['Conviction'].str[-2:])['CurrAlloc%'].sum().sort_values(ascending=False)

Conviction
SC    44.13
MC    30.43
LC    25.43
Name: CurrAlloc%, dtype: float64

In [26]:
# criteria-wise allocation
df_portfolio_features.groupby('Criteria')['CurrAlloc%'].sum().sort_values(ascending=False)

Criteria
XY24     27.07
X40      25.59
X40N     15.07
AR        9.17
XR        8.11
XY25      7.46
OX40N     6.77
SR        0.75
Name: CurrAlloc%, dtype: float64

In [27]:
# conviction-wise allocation
df_portfolio_features.groupby('Conviction')['CurrAlloc%'].sum().sort_values(ascending=False)

Conviction
X-LC    23.24
X-MC    22.97
H-SC    21.44
X-SC    12.07
M-SC    10.06
H-MC     5.06
M-MC     2.05
H-LC     1.19
M-LC     1.00
L-SC     0.56
L-MC     0.35
Name: CurrAlloc%, dtype: float64

In [28]:
# sector-wise stats
df_tmp = df_portfolio_features.groupby('Category')[['CurrAlloc%', 'Current', 'Current P/L', 'FTT Amt']].sum().sort_values(by=['Current', 'Current P/L'], ascending=False)
df_tmp['Current P/L%'] = round(df_tmp['Current P/L'] * 100 / df_tmp['Current'], 2)
df_tmp['FTT%'] = round(df_tmp['FTT Amt'] * 100 / df_tmp['Current'], 2)
cols = ['CurrAlloc%', 'Current P/L%', 'FTT%']
df_tmp[cols].sort_values(by=['CurrAlloc%'], ascending=False)

               CurrAlloc%  Current P/L%    FTT%
Category
FMCG                15.25        -24.30   68.43
FINANCE             12.93        -26.02   77.37
IT                  11.52        -48.26  123.71
MISC                 6.93        -46.62  110.31
ELECTRICAL           6.64        -10.66   53.03
PAINTS               5.15        -44.95   70.12
INSURANCE            4.84         -6.35   42.75
BANKS                4.72        -23.42   86.06
PHARMA               4.18         -6.63   40.19
AUTO                 3.65        -35.78   89.65
AC                   2.14        -13.27   43.98
HEALTHCARE           1.93        -41.03   77.84
DURABLES             1.84        -60.08   99.03
FOOTWEAR             1.83        -82.68  155.94
TRAVEL               1.81        -87.65  181.60
BREWERIES            1.71         -3.65   25.18
APPARELS             1.62        -25.95   68.92
REALTY               1.47        -14.81   33.67
CERAMICS             1.35        -72.14  124.44
REFINERIES           1.35        -12.83   41.38
CEMENT               1.26        -61.88  182.98
CABLES               1.20          6.85   93.67
JEWELLERY            1.11       -118.87  194.91
ENGINEERING          1.09        -69.30  146.73
CHEMICALS            0.93       -114.62  289.71
ENTERTAINMENT        0.76        -92.68  207.60
TEXTILES             0.42        -67.19  114.86
HOTELS               0.36       -139.53  224.02

In [29]:
# money to be made criteria-wise
df_portfolio_features.groupby('Criteria')['FTT Amt'].agg(['sum', 'count']).sort_values(by='sum', ascending=False)

                sum  count
Criteria
XY24      4030710.0     21
X40       1800782.0     16
XR        1419857.0     12
AR        1363231.0     10
X40N      1312222.0     10
OX40N      898876.0     10
XY25       457683.0      5
SR         319589.0      2

In [30]:
# money to be made conviction-wise
df_portfolio_features.groupby('Conviction')['FTT Amt'].agg(['sum', 'count']).sort_values(by='sum', ascending=False)

                  sum  count
Conviction
H-SC        3963889.0     24
X-LC        1709872.0     13
X-MC        1708149.0     15
M-SC        1592619.0     14
X-SC        1590553.0     10
H-MC         412118.0      3
L-SC         216702.0      2
M-LC         159542.0      1
M-MC         116691.0      2
H-LC          76636.0      1
L-MC          56179.0      1

In [31]:
# money to be made criteria and conviction-wise
df_portfolio_features.groupby(['Conviction', 'Criteria'])['FTT Amt'].agg(['sum', 'count']).sort_values(by='sum', ascending=False)

                           sum  count
Conviction Criteria
H-SC       XY24      1361235.0      6
           AR         984704.0      5
M-SC       XY24       926428.0      6
X-LC       X40        918869.0      7
H-SC       XR         901071.0      7
X-SC       XY24       860785.0      4
X-MC       X40        672860.0      7
           X40N       527868.0      4
X-SC       X40N       520715.0      4
H-SC       OX40N      397290.0      4
M-SC       OX40N      391081.0      5
X-LC       XY24       379213.0      2
H-SC       SR         319589.0      2
X-LC       X40N       263639.0      2
X-MC       XY24       260512.0      2
           XY25       246909.0      2
H-MC       XY24       242537.0      1
X-SC       X40        209053.0      2
M-SC       XR         196868.0      2
H-MC       AR         169581.0      2
M-LC       XR         159542.0      1
X-LC       XY25       148151.0      2
L-SC       OX40N      110505.0      1
           XR         106197.0      1
M-SC       AR          78242.0      1
H-LC       AR          76636.0      1
M-MC       XY25        62623.0      1
L-MC       XR          56179.0      1
M-MC       AR          54068.0      1

In [32]:
# notebook execution time

end_time = time.time()
execution_time = round(end_time - start_time, 0)
print(f"Notebook execution time: {execution_time} seconds")

Notebook execution time: 37.0 seconds