<a href="https://colab.research.google.com/github/ankit-rathi/Quantvesting_v2/blob/main/myStocks_Portfolio_Analysis.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
'''
!pip install pandas==2.2.2 -qq
!pip install pyxirr -qq
!pip install ta -qq
!pip install yfinance==0.2.59 -qq
'''

'\n!pip install pandas==2.2.2 -qq\n!pip install pyxirr -qq\n!pip install ta -qq\n!pip install yfinance==0.2.59 -qq\n'

In [2]:
# import libraries

import numpy as np
import pandas as pd
import datetime
import warnings
warnings.filterwarnings('ignore')
import yfinance as yfin
import ta
import matplotlib.pyplot as plt
import requests

In [3]:
# notebook start time
import time
import datetime
import pytz

start_time = time.time()

# function to print date timestamp
def print_date_time():
  tz_NY = pytz.timezone('Asia/Kolkata')
  datetime_NY = datetime.datetime.now(tz_NY)
  print("Run date time (IST):", datetime_NY.strftime("%Y-%m-%d %H:%M:%S"))

In [4]:
# function to get booked and reserved amount
def get_amt():
  # fetch the JSON data from the URL
  url = "https://raw.githubusercontent.com/ankit-rathi/Tradevesting_v1/main/data/myPortfolioAmts.json"
  response = requests.get(url)
  pf_amts = response.json()  # parse the JSON data

  # extract values from the JSON
  py_booked_amt_dm = pf_amts["py_booked_amt_dm"]
  py_booked_amt_sv = pf_amts["py_booked_amt_sv"]
  cy_booked_amt_dm = pf_amts["cy_booked_amt_dm"]
  cy_booked_amt_sv = pf_amts["cy_booked_amt_sv"]
  reserve_amt_dm = pf_amts["reserve_amt_dm"]
  reserve_amt_sv = pf_amts["reserve_amt_sv"]

  # perform calculations
  py_booked_amt = py_booked_amt_dm + py_booked_amt_sv
  cy_booked_amt = cy_booked_amt_dm + cy_booked_amt_sv
  reserve_amt = reserve_amt_dm + reserve_amt_sv
  total_booked_amt = py_booked_amt + cy_booked_amt

  return total_booked_amt, reserve_amt, cy_booked_amt, py_booked_amt

gen_output = 0

In [5]:
# function to format the amount
def format_amt(number):
    abs_number = abs(number)

    if abs_number >= 1_00_00_000:  # Crores
        formatted_amt = f"{number / 1_00_00_000:.2f} C"
    elif abs_number >= 1_00_000:  # Lakhs
        formatted_amt = f"{number / 1_00_000:.2f} L"
    elif abs_number >= 1_000:  # Thousands
        formatted_amt = f"{number / 1_000:.2f} K"
    else:
        formatted_amt = f"{number:.2f}"

    return formatted_amt

# function to set start and end date
def get_start_end_date():
  start_date = (datetime.date.today() + datetime.timedelta(days=-365)).strftime('%Y-%m-%d')
  end_date = (datetime.date.today() + datetime.timedelta(days=1)).strftime('%Y-%m-%d')
  return start_date, end_date

# function to fetch my portfolio csv
def get_mypfs_df():
  mypfs_df = pd.read_csv('https://raw.githubusercontent.com/ankit-rathi/Tradevesting_v1/main/data/myPortfolioStocks.csv')
  return mypfs_df

# function to fetch my prospects csv
def get_mypps_df():
  mypps_df = pd.read_csv('https://raw.githubusercontent.com/ankit-rathi/Tradevesting_v1/main/data/myProspectsScrips.csv')
  return mypps_df

# function to fetch screener data
def get_myscreen_df():
  myscreen_df = pd.read_csv('https://raw.githubusercontent.com/ankit-rathi/Tradevesting_v1/main/data/myScreenerDB.csv')
  return myscreen_df

# function to fetch momentum data
def get_myinvmt_df():
  myinvmt_df = pd.read_csv('https://raw.githubusercontent.com/ankit-rathi/Tradevesting_v1/main/data/myInvestments.csv')
  return myinvmt_df

# function to get the stock ids
def get_stock_ids(df_pf):
  stock_n100 = df_pf['Symbol'].unique()

  exclude = ['CADILAHC','MMTC', 'MASFIN']

  stock_ids = df_pf[~df_pf['Symbol'].isin(exclude) ]['Symbol'].unique()

  #mypf = mypf[mypf.Forecast.notnull()]
  #stock_ids = mypf['Symbol'].unique()

  #stock_ids.sort()
  return stock_ids

# get features from screener data
def get_screener_features():
  myscreen_df = get_myscreen_df()
  cols = ['Symbol', 'EPS', 'MedPE', 'ROCE%', 'ROE%', 'CapType']
  return myscreen_df[cols]

# get relative strength
def get_relative_strength(stock_list):

    # Dictionary to store stock tickers and their corresponding percentage price change
    stock_changes = {}

    # Loop through each stock and fetch its price data
    for stock in stock_list:
        try:
            # Download the stock data for the given date range
            stock_data = yfin.Ticker(stock + '.NS').history(period='1mo', interval='1d')[map(str.title, ['open', 'close', 'low', 'high', 'volume'])]

            # Calculate the percentage change for the stock
            if len(stock_data) > 0:
                start_price = stock_data['Close'].iloc[0]
                end_price = stock_data['Close'].iloc[-1]
                percent_change = round(((end_price - start_price) / start_price) * 100, 2)
                stock_changes[stock] = percent_change
            else:
                stock_changes[stock] = np.nan  # If no data is available, set to NaN

        except Exception as e:
            print(f"Error fetching data for {stock}: {e}")
            stock_changes[stock] = np.nan

    # Create a DataFrame with stock tickers and their percentage changes
    df = pd.DataFrame(list(stock_changes.items()), columns=['Symbol', 'Percent_Change'])

    # Drop any stocks with missing data (NaN values)
    df = df.dropna()

    # Calculate the percentile rank based on percentage change
    df['RSP'] = round(df['Percent_Change'].rank(pct=True) * 100, 2)
    cols = ['Symbol', 'RSP']
    df = df[cols]
    # Sort by percentile rank (optional)
    df = df.sort_values(by='RSP', ascending=False).reset_index(drop=True)

    return df

In [6]:
# function to get stock technicals
def stock_prec_dev(stock_symbol):
    #stock_symbol = 'ULTRACEMCO.NS'
    short_window = 20
    mid_window = 50
    long_window = 200
    moving_avg = 'SMA'

    start = datetime.datetime(*map(int, start_date.split('-')))
    end = datetime.datetime(*map(int, end_date.split('-')))

    stock_df = yfin.Ticker(stock_symbol + '.NS').history(period='max', interval='1d')[map(str.title, ['open', 'close', 'low', 'high', 'volume'])]

    stock_df['Max'] = round(max(stock_df['Close']),2)
    stock_df = stock_df[(stock_df.index <= end_date) & (stock_df.index >= start_date)]
    stock_df['200_SMA'] = round(stock_df['Close'].rolling(window = 200, min_periods = 1).mean(),0)
    stock_df['Dev%_200'] = round((stock_df['Close'] - stock_df['200_SMA'])*100/stock_df['200_SMA'],2)
    stock_df.dropna(axis = 0, inplace = True) # remove any null rows

    stock_df['20_SMA'] = stock_df['Close'].rolling(window=20).mean()
    stock_df['50_SMA'] = stock_df['Close'].rolling(window=50).mean()
    stock_df['Symbol'] = stock_symbol

    stock_df['Close'] = round(stock_df['Close'],2)
    stock_df['Min'] = round(min(stock_df['Close']),2)
    stock_df['RSI_14'] = ta.momentum.RSIIndicator(close=stock_df['Close'], window=14).rsi()
    stock_df['RSI_14'] = round(stock_df['RSI_14'],0)
    stock_df['Prev_Close'] = stock_df['Close'].shift(1)
    stock_df.drop(['Open', 'Low', 'High', 'Volume'], axis=1, inplace=True)
    stock_df = stock_df.tail(1)

    max_SMA = max(stock_df['20_SMA'].item(), stock_df['50_SMA'].item(), stock_df['200_SMA'].item())
    min_SMA = min(stock_df['20_SMA'].item(), stock_df['50_SMA'].item(), stock_df['200_SMA'].item())
    ABS_Spread = max_SMA - min_SMA
    stock_df['Spread%'] = round((ABS_Spread / stock_df['200_SMA'].item()) * 100,2)

    return stock_df

# function to compute stock attributes
def get_common_features(stock_ids, df_mypf):

  df_prec_dev = pd.DataFrame()
  df_tmp = get_screener_features()
  df_rs = get_relative_strength(stock_ids)

  for stock_id in stock_ids:
      tmp = stock_prec_dev(stock_id)
      tmp = tmp.reset_index()
      df_prec_dev = pd.concat([df_prec_dev, tmp], ignore_index = True)
  df_prec_dev = pd.merge(df_prec_dev, df_mypf, on= 'Symbol')
  df_prec_dev = pd.merge(df_prec_dev, df_tmp, on= 'Symbol', how='left')
  df_prec_dev = pd.merge(df_prec_dev, df_rs, on= 'Symbol', how='left')
  #print(df_prec_dev.columns)
  df_prec_dev['Curr_PE'] = round(df_prec_dev['Close']/df_prec_dev['EPS'],1)
  df_prec_dev['Dev%_PE'] = round((df_prec_dev['Curr_PE'] - df_prec_dev['MedPE'])*100/df_prec_dev['MedPE'],2)
  df_prec_dev['Conviction'] = df_prec_dev['Conviction'] + '-' + df_prec_dev['CapType']
  return df_prec_dev

# function to arrange stock features
def arrange_features(df_stocks, common_cols, diff_cols):
  df_stocks_common = df_stocks[common_cols].drop_duplicates()
  df_stocks_diff = df_stocks[diff_cols]
  df_stocks_diff['Investment'] = df_stocks_diff['AvgCost'] * df_stocks_diff['Shares']
  df_stocks_diff = df_stocks_diff.groupby(['Symbol'])[['Shares', 'Investment']].aggregate(['sum']).reset_index()
  df_stocks_diff.columns = ['Symbol', 'Shares', 'Investment']
  df_stocks_diff['AvgCost'] = round(df_stocks_diff['Investment']/df_stocks_diff['Shares'],2)
  df_stocks = pd.merge(df_stocks_diff, df_stocks_common, on='Symbol')
  return df_stocks

# plot fact distribution across dimension
def plot_pie_chart(df, dimension, fact):
  # grouping the data by category and calculating the sum of fact for each type
  grouped_data = df.groupby(dimension)[fact].sum()

  # sorting the grouped data in descending order
  grouped_data = grouped_data.sort_values(ascending=False)

  # creating a pie chart
  grouped_data.plot.pie(autopct='%1.1f%%', startangle=90, figsize=(6, 6))

  # adding a title and displaying the plot
  plt.title(f'{dimension} {fact} Distribution')
  plt.ylabel('')  # To hide the y-label
  plt.show()

In [7]:
# function to get portfolio features

def get_portfolio_features(df_common_features):

  print_date_time()
  print('-------------------')

  #df_common_features["Target"] = df_common_features["Target"].fillna(df_common_features["Max"])
  df_common_features['NTT'] = np.where(df_common_features['Strategy']== 'NTT', df_common_features["Target"], df_common_features['Max'])
  df_common_features['LTT'] = np.where(df_common_features['Strategy']== 'BTT', df_common_features["Target"], df_common_features['Max'])
  df_common_features['BOL'] = df_common_features['Min']

  tmp_df = df_common_features[df_common_features['Symbol'].isin(mypf_df[mypf_df['InPortfolio'] != 'NA'].Symbol.values)]
  print('qualified stocks: '+str(len(tmp_df['Symbol'].unique())))
  tmp_df1 = tmp_df[tmp_df['LatestQtr'] == 1]
  print('with latest results: '+str(len(tmp_df1['Symbol'].unique())))
  tmp_df1 = tmp_df1[tmp_df1['StarStock'] == 1]
  print('still star stocks: '+str(len(tmp_df1['Symbol'].unique())))
  tmp_df['Investment'] = tmp_df['AvgCost'] * tmp_df['Shares']
  tmp_df['Current'] = round(tmp_df['Close'] * tmp_df['Shares'],0)
  tmp_df['Previous'] = tmp_df['Prev_Close'] * tmp_df['Shares']
  tmp_df['EstimatedST'] = tmp_df['NTT'] * tmp_df['Shares']
  tmp_df['EstimatedLT'] = tmp_df['LTT'] * tmp_df['Shares']
  tmp_df['Current P/L'] = round((tmp_df['Current'] - tmp_df['Investment']),0)
  tmp_df['Today P/L%'] = round((tmp_df['Current'] - tmp_df['Previous'])*100/tmp_df['Previous'],2)
  tmp_df['Current P/L%'] = round((tmp_df['Current'] - tmp_df['Investment'])*100/tmp_df['Investment'],2)
  tmp_df['EstimatedST P/L%'] = round((tmp_df['EstimatedST'] - tmp_df['Investment'])*100/tmp_df['Investment'],2)
  tmp_df['EstimatedLT P/L%'] = round((tmp_df['EstimatedLT'] - tmp_df['Investment'])*100/tmp_df['Investment'],2)
  tmp_df['NTT%'] = round((tmp_df['NTT'] - tmp_df['Close'])*100/tmp_df['Close'],2)
  tmp_df['LTT%'] = round((tmp_df['LTT'] - tmp_df['Close'])*100/tmp_df['Close'],2)
  tmp_df['Gained%'] = round((tmp_df['Close'] - tmp_df['BOL'])*100/tmp_df['BOL'],2)
  investment = round(sum(tmp_df['AvgCost']*tmp_df['Shares']),0)
  current = round(sum(tmp_df['Close']*tmp_df['Shares']),0)
  tmp_df['InitAlloc%'] = round(tmp_df['Investment']*100/investment,2)
  tmp_df['CurrAlloc%'] = round(tmp_df['Current']*100/current,2)
  tmp_df['FTT'] = tmp_df['LTT']
  tmp_df.loc[tmp_df['Strategy'] == 'NTT', 'FTT'] = tmp_df['NTT']
  tmp_df['FTT%'] = tmp_df['LTT%']
  tmp_df.loc[tmp_df['Strategy'] == 'NTT', 'FTT%'] = tmp_df['NTT%']
  tmp_df['FTT Amt'] = round(tmp_df['FTT%'] * tmp_df['Current']/100,0)
  tmp_df['OTT%'] = round((tmp_df['FTT'] - tmp_df['AvgCost'])*100/tmp_df['AvgCost'],2)
  tmp_df['RRR Ind'] = round(tmp_df['Current P/L']/tmp_df['FTT Amt'],2)
  tmp_df['Risk Ind'] = round(tmp_df['Current P/L%']*tmp_df['CurrAlloc%'],0)

  return tmp_df

# function to print portfolio features
def print_portfolio_stats(df_portfolio_features, myinvmt_df):
  from pyxirr import xirr

  total_booked_amt, reserve_amt, cy_booked_amt, py_booked_amt = get_amt()

  dates = myinvmt_df['Date'].values
  dates = np.append(dates, datetime.date.today().strftime('%d-%b-%y'))
  investment = myinvmt_df['Investment'].values
  dates= pd.to_datetime(dates)

  current = round(sum(df_portfolio_features['Close']*df_portfolio_features['Shares']),0) + reserve_amt
  investment_xirr = np.append(investment, current)
  cagr = round(xirr(pd.DataFrame({"dates": dates, "amounts": investment_xirr}))*100,2)

  investment = -sum(investment)
  invested = round(sum(df_portfolio_features['AvgCost']*df_portfolio_features['Shares']),0) + reserve_amt
  previous = round(sum(df_portfolio_features['Prev_Close']*df_portfolio_features['Shares']),0) + reserve_amt
  cy_invested = investment + py_booked_amt

  today_pnl_amount = current-previous
  today_pnl_percentage = round((current-previous)*100/previous,2)

  curr_pnl_amount = current-invested
  curr_pnl_percentage = round((curr_pnl_amount)*100/(cy_invested),2)

  cy_pnl_amount = cy_booked_amt + curr_pnl_amount
  cy_pnl_percentage = round((cy_pnl_amount)*100/cy_invested,2)

  overall_pnl_amount = total_booked_amt + curr_pnl_amount
  overall_pnl_percentage = round((overall_pnl_amount)*100/investment,2)

  estimate_st = round(sum(df_portfolio_features['FTT']*df_portfolio_features['Shares']),0)  + reserve_amt
  est_st_pnl_amount = estimate_st-current
  est_st_pnl_percentage = round((est_st_pnl_amount)*100/current,2)

  estimate_lt = round(sum(df_portfolio_features['LTT']*df_portfolio_features['Shares']),0)  + reserve_amt
  est_lt_pnl_amount = estimate_lt-current
  est_lt_pnl_percentage = round((est_lt_pnl_amount)*100/current,2)

  total_profit = round(sum(df_portfolio_features[df_portfolio_features['Current P/L%'] > 0]['Current']) - sum(df_portfolio_features[df_portfolio_features['Current P/L%'] > 0]['Investment']),0)
  total_loss = round(sum(df_portfolio_features[df_portfolio_features['Current P/L%'] < 0]['Current']) - sum(df_portfolio_features[df_portfolio_features['Current P/L%'] < 0]['Investment']),0)

  cy_booked_percentage = round((cy_booked_amt)*100/current,2)
  py_booked_percentage = round((py_booked_amt)*100/investment,2)
  total_booked_percentage = round((total_booked_amt)*100/investment,2)

  print('-------------------')
  print('Initial Investment: ', format_amt(investment))
  print('CY Investment: ', format_amt(cy_invested))
  print('Reserve: ', format_amt(reserve_amt))
  print('Current: ',  format_amt(current))
  print('-------------------')
  print('Today PnL: '+ '{} ({}%)'.format(format_amt(today_pnl_amount), today_pnl_percentage))
  print('Current PnL: '+ '{} ({}%)'.format(format_amt(curr_pnl_amount), curr_pnl_percentage))
  print('CY Booked + Current PnL: '+ '{} ({}%)'.format(format_amt(cy_pnl_amount), cy_pnl_percentage))
  print('-------------------')
  print('Total profit: ', format_amt(total_profit))
  print('Total loss: ', format_amt(total_loss))
  print('-------------------')
  print('Total Booked + Current PnL: '+ '{} ({}%)'.format(format_amt(overall_pnl_amount), overall_pnl_percentage))
  print('Total Booked PnL: '+ '{} ({}%)'.format(format_amt(total_booked_amt), total_booked_percentage))
  print('Curr Year Booked PnL: '+ '{} ({}%)'.format(format_amt(cy_booked_amt), cy_booked_percentage))
  print('Prev Year Booked PnL: '+ '{} ({}%)'.format(format_amt(py_booked_amt), py_booked_percentage))
  print('===================')
  print('Est FTT: ',  format_amt(estimate_st))
  print('Est FTT PnL: '+ '{} ({}%)'.format(format_amt(est_st_pnl_amount), est_st_pnl_percentage))

  print('===================')
  print('Deployed: ', format_amt(investment))

  print('Current: ', format_amt(current))

  print('CAGR/XIRR %: '+'{}%'.format(cagr))

In [8]:
# get start and end date
start_date, end_date = get_start_end_date()

# get portfolio and prospects data
mypfs_df = get_mypfs_df()
mypps_df = get_mypps_df()
myinvmt_df = get_myinvmt_df()

# merge above datasets
mypf_df = pd.merge(mypfs_df, mypps_df, on="Symbol")

# seggregate dm and sv portfolio
dm_pf = mypf_df[mypf_df['InPortfolio'] == 'DM']
sv_pf = mypf_df[mypf_df['InPortfolio'] == 'SV']

# build portfolio stock dataframe
dm_stocks = get_stock_ids(dm_pf)
sv_stocks = get_stock_ids(sv_pf)
df_stocks = pd.concat([dm_pf,sv_pf], ignore_index = True)

# arrange common and diff stock features
common_cols = ['Symbol', 'Target', 'Criteria', 'Strategy', 'CumlRnk', 'LatestQtr', 'StarStock', 'Conviction', 'Category', 'InFolio', 'XIRR', 'MBQ']
diff_cols = ['Symbol', 'AvgCost', 'Shares']
df_stocks = arrange_features(df_stocks, common_cols, diff_cols)

# get common features
stock_ids = df_stocks['Symbol'].values
df_common_features = get_common_features(stock_ids, df_stocks)

df_common_features.reset_index(drop=True, inplace=True)
df_common_features.drop(['Date'], axis=1, inplace=True)
# get and print portfolio features
df_portfolio_features = get_portfolio_features(df_common_features)

print_portfolio_stats(df_portfolio_features, myinvmt_df)

df = df_portfolio_features
#plot_pie_chart(df, 'CapType', 'Current')
list_ox40n = list(df[df['MBQ'].str.contains('OX40N', na=False)]['Symbol'].values)

Run date time (IST): 2026-03-02 12:08:21
-------------------
qualified stocks: 86
with latest results: 26
still star stocks: 15
-------------------
Initial Investment:  1.33 C
CY Investment:  1.60 C
Reserve:  2.44 L
Current:  1.34 C
-------------------
Today PnL: -2.92 L (-2.13%)
Current PnL: -40.34 L (-25.21%)
CY Booked + Current PnL: -24.66 L (-15.41%)
-------------------
Total profit:  1.17 L
Total loss:  -41.51 L
-------------------
Total Booked + Current PnL: 2.32 L (1.75%)
Total Booked PnL: 42.66 L (32.07%)
Curr Year Booked PnL: 15.68 L (11.69%)
Prev Year Booked PnL: 26.98 L (20.29%)
===================
Est FTT:  2.41 C
Est FTT PnL: 1.07 C (79.76%)
===================
Deployed:  1.33 C
Current:  1.34 C
CAGR/XIRR %: 0.41%

In [9]:
# top 5 near their targets
cols = ['Symbol', 'Today P/L%', 'Current P/L%', 'FTT%', 'OTT%', 'FTT Amt', 'Current P/L', 'Current', 'FTT', 'Dev%_PE', 'RSI_14','Conviction', 'Spread%',  'CumlRnk', 'RRR Ind', 'CurrAlloc%', 'Gained%', 'Criteria', 'Strategy', 'Category']
df_tmp = df_portfolio_features[~df_portfolio_features['Symbol'].isin(['ENRIN','BLUSPRING','DIGITIDE'])]
df_tmp = df_tmp.sort_values(by = 'FTT Amt', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
19,COALINDIA,-1.93,3.86,13.30,17.67,20784.0,5810.0,156270.0,478.51,24.82,50.0,L-LC,10.81,185.0,0.28,1.19,25.45,XY25,ATH,MINING
50,MASFIN,-3.13,-3.80,26.37,21.57,24856.0,-3720.0,94260.0,397.04,-16.89,41.0,H-SC,6.67,167.0,-0.15,0.72,37.55,XR,ATH,FINANCE
77,TTKPRESTIG,-2.50,-33.75,51.08,0.09,34103.0,-34013.0,66764.0,770.00,54.96,27.0,M-SC,11.99,250.0,-1.00,0.51,0.00,OX40N,NTT,DURABLES
37,ICICIGI,-0.05,0.68,18.54,19.34,37351.0,1355.0,201464.0,2252.93,-15.42,48.0,X-MC,1.20,66.0,0.04,1.53,16.72,X40,ATH,INSURANCE
51,MEDANTA,-0.77,-5.65,31.50,24.08,37731.0,-7170.0,119780.0,1486.00,-6.31,48.0,X-SC,7.96,87.0,-0.19,0.91,9.71,XY24,NTT,HEALTHCARE

In [10]:
# top 5 today
df_tmp = df_portfolio_features.sort_values(by = 'Today P/L%', ascending=False)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
27,FINCABLES,2.33,18.42,75.57,107.91,132130.0,27201.0,174845.0,1641.55,6.54,77.0,M-SC,6.70,220.0,0.21,1.33,31.54,OX40N,ATH,CABLES
63,SFL,0.46,-45.88,134.00,26.63,190146.0,-120318.0,141900.0,1287.00,7.45,43.0,M-SC,12.20,242.0,-0.63,1.08,8.92,XY24,NTT,MISC
2,ABBOTINDIA,0.34,-10.70,32.21,18.07,51446.0,-19135.0,159720.0,35195.00,-24.04,44.0,X-MC,11.52,58.0,-0.37,1.21,1.26,X40,ATH,PHARMA
38,ICICIPRULI,0.30,8.63,20.34,30.73,43528.0,16998.0,214003.0,790.00,-20.57,52.0,X-MC,4.18,78.0,0.39,1.63,22.50,X40,ATH,INSURANCE
37,ICICIGI,-0.05,0.68,18.54,19.34,37351.0,1355.0,201464.0,2252.93,-15.42,48.0,X-MC,1.20,66.0,0.04,1.53,16.72,X40,ATH,INSURANCE

In [11]:
# bottom 5 today
df_tmp = df_portfolio_features.sort_values(by = 'Today P/L%', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
26,EASEMYTRIP,-7.42,-55.96,230.83,45.70,179745.0,-98946.0,77869.0,26.4,-19.28,51.0,M-SC,18.11,204.0,-0.55,0.59,28.30,XY24,NTT,TRAVEL
69,SURYODAY,-6.38,-29.57,74.69,23.03,94201.0,-52948.0,126123.0,216.0,38.16,44.0,H-SC,5.88,166.0,-0.56,0.96,25.14,XR,NTT,BANKS
8,AWL,-4.80,-41.65,169.41,57.19,322355.0,-135846.0,190281.0,485.0,-66.62,13.0,X-SC,19.48,81.0,-0.42,1.45,0.00,XY24,NTT,FMCG
76,TRIDENT,-4.69,-34.73,96.88,28.51,58340.0,-32036.0,60219.0,48.0,-15.95,36.0,M-SC,9.02,223.0,-0.55,0.46,3.04,XR,NTT,TEXTILES
55,RAJESHEXPO,-4.60,-73.50,277.55,0.07,100912.0,-100819.0,36358.0,518.0,1232.07,26.0,L-SC,10.14,268.0,-1.00,0.28,0.00,OX40N,NTT,JEWELLERY

In [12]:
# top 5 to exit based on CumlRnk
df_tmp = df_portfolio_features[~df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])]
df_tmp = df_tmp[(df_tmp['Current P/L%'] > -1) & (df_tmp['Current P/L%'] < 1)].sort_values(by = 'CumlRnk', ascending=False)
df_tmp[cols].head()

Empty DataFrame
Columns: [Symbol, Today P/L%, Current P/L%, FTT%, OTT%, FTT Amt, Current P/L, Current, FTT, Dev%_PE, RSI_14, Conviction, Spread%, CumlRnk, RRR Ind, CurrAlloc%, Gained%, Criteria, Strategy, Category]
Index: []

In [13]:
# OX40N stocks to exit
df_tmp = df_portfolio_features[(df_portfolio_features['Symbol'].isin(list_ox40n))].sort_values(by = 'Current P/L%', ascending=False)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
27,FINCABLES,2.33,18.42,75.57,107.91,132130.0,27201.0,174845.0,1641.55,6.54,77.0,M-SC,6.70,220.0,0.21,1.33,31.54,OX40N,ATH,CABLES
66,SIS,-0.52,-30.25,73.86,21.26,57200.0,-33588.0,77444.0,528.00,1819.17,40.0,H-SC,5.94,168.0,-0.59,0.59,6.76,OX40N,NTT,MISC
77,TTKPRESTIG,-2.50,-33.75,51.08,0.09,34103.0,-34013.0,66764.0,770.00,54.96,27.0,M-SC,11.99,250.0,-1.00,0.51,0.00,OX40N,NTT,DURABLES
48,KANSAINER,-3.55,-34.49,73.21,13.47,129334.0,-93006.0,176661.0,340.00,-43.73,31.0,H-SC,13.43,162.0,-0.72,1.34,0.00,XY24,NTT,PAINTS
41,INDIGOPNTS,-2.91,-35.39,54.81,0.02,61814.0,-61781.0,112778.0,1408.00,71.88,22.0,M-SC,12.66,222.0,-1.00,0.86,0.00,OX40N,NTT,PAINTS

In [14]:
# top 5 to book for rotation
df_tmp = df_portfolio_features[(df_portfolio_features['Current P/L%'] > 20) ].sort_values(by = 'CumlRnk', ascending=False)
df_tmp[cols].head()

Empty DataFrame
Columns: [Symbol, Today P/L%, Current P/L%, FTT%, OTT%, FTT Amt, Current P/L, Current, FTT, Dev%_PE, RSI_14, Conviction, Spread%, CumlRnk, RRR Ind, CurrAlloc%, Gained%, Criteria, Strategy, Category]
Index: []

In [15]:
# top 5 to monitor for exit
df_tmp = df_portfolio_features[~df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])]
df_tmp = df_tmp[(df_tmp['Current P/L%'] > 0) ].sort_values(by = 'Dev%_PE', ascending=False)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
19,COALINDIA,-1.93,3.86,13.30,17.67,20784.0,5810.0,156270.0,478.51,24.82,50.0,L-LC,10.81,185.0,0.28,1.19,25.45,XY25,ATH,MINING
27,FINCABLES,2.33,18.42,75.57,107.91,132130.0,27201.0,174845.0,1641.55,6.54,77.0,M-SC,6.70,220.0,0.21,1.33,31.54,OX40N,ATH,CABLES
1,ABB,-2.03,9.17,33.34,45.57,95219.0,23981.0,285600.0,7934.00,-29.83,59.0,H-MC,8.93,125.0,0.25,2.17,26.83,AR,NTT,ELECTRICAL

In [16]:
# top 5 to book for rotation from weak conviction
df_tmp = df_portfolio_features[~df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])]
df_tmp = df_tmp[~df_tmp['Criteria'].isin(['XY25','XY24','X40', 'X40N'])].sort_values(by = 'RRR Ind', ascending=False)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
1,ABB,-2.03,9.17,33.34,45.57,95219.0,23981.0,285600.0,7934.00,-29.83,59.0,H-MC,8.93,125.0,0.25,2.17,26.83,AR,NTT,ELECTRICAL
27,FINCABLES,2.33,18.42,75.57,107.91,132130.0,27201.0,174845.0,1641.55,6.54,77.0,M-SC,6.70,220.0,0.21,1.33,31.54,OX40N,ATH,CABLES
40,INDIAMART,-1.32,-9.59,128.65,106.72,143454.0,-11829.0,111507.0,4810.62,-59.18,36.0,H-SC,8.20,140.0,-0.08,0.85,11.54,AR,ATH,MISC
85,ZYDUSLIFE,-1.70,-4.46,41.96,35.63,84015.0,-9348.0,200226.0,1286.17,-16.67,50.0,H-MC,4.91,120.0,-0.11,1.52,11.47,AR,ATH,PHARMA
50,MASFIN,-3.13,-3.80,26.37,21.57,24856.0,-3720.0,94260.0,397.04,-16.89,41.0,H-SC,6.67,167.0,-0.15,0.72,37.55,XR,ATH,FINANCE

In [17]:
# top 5 to accumulate based on lowest RSI_14
df_tmp = df_portfolio_features[df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])].sort_values(by = 'RSI_14', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
8,AWL,-4.80,-41.65,169.41,57.19,322355.0,-135846.0,190281.0,485.00,-66.62,13.0,X-SC,19.48,81.0,-0.42,1.45,0.00,XY24,NTT,FMCG
43,INFY,-1.74,-13.03,54.36,34.24,147918.0,-40780.0,272108.0,1972.00,-31.42,22.0,X-LC,9.40,3.0,-0.28,2.07,0.16,X40,NTT,IT
12,BATAINDIA,-3.38,-50.82,174.94,35.20,110693.0,-65395.0,63275.0,2096.00,-17.11,23.0,X-SC,22.65,91.0,-0.59,0.48,0.00,X40,NTT,FOOTWEAR
9,BAJAJHFL,-3.61,-28.13,116.33,55.47,203401.0,-68438.0,174848.0,181.50,-38.44,23.0,X-MC,17.47,60.0,-0.34,1.33,0.00,X40N,ATH,FINANCE
53,PGHH,-1.17,-15.94,57.04,32.01,102380.0,-34032.0,179488.0,17616.87,-43.10,23.0,X-MC,9.68,57.0,-0.33,1.36,0.00,X40,ATH,FMCG

In [18]:
# top 5 to accumulate based on Spread and CumlRnk
df_tmp = df_portfolio_features[df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])]
df_tmp = df_tmp[(df_tmp['CumlRnk'] < 100)].sort_values(by = 'Spread%', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
37,ICICIGI,-0.05,0.68,18.54,19.34,37351.0,1355.0,201464.0,2252.93,-15.42,48.0,X-MC,1.20,66.0,0.04,1.53,16.72,X40,ATH,INSURANCE
78,UNITDSPR,-0.77,0.65,19.98,20.77,47088.0,1530.0,235674.0,1644.00,-10.79,45.0,X-MC,1.43,64.0,0.03,1.79,7.81,X40N,NTT,BREWERIES
22,DABUR,-2.24,-0.90,45.00,43.70,110631.0,-2222.0,245846.0,735.00,-10.05,45.0,X-MC,1.55,70.0,-0.02,1.87,14.02,XY24,BTT,FMCG
59,RELIANCE,-2.37,-12.64,43.43,25.30,76244.0,-25407.0,175556.0,1952.00,-15.03,34.0,X-LC,2.16,21.0,-0.33,1.33,17.59,XY25,BTT,REFINERIES
5,ANGELONE,-3.88,-90.82,1253.17,24.20,351113.0,-277232.0,28018.0,3033.00,-86.88,30.0,X-SC,2.45,97.0,-0.79,0.21,17.34,X40N,NTT,FINANCE

In [19]:
# top 5 to accumulate based on lowest Gained%
df_tmp = df_portfolio_features[df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])].sort_values(by = 'Gained%', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
3,ACC,-2.15,-34.52,150.67,64.15,234774.0,-82131.0,155820.0,3906.00,-50.74,27.0,X-SC,9.62,85.0,-0.35,1.18,0.0,XY24,BTT,CEMENT
10,BAJAJHLDNG,-2.82,-6.12,37.65,29.22,67199.0,-11642.0,178483.0,14451.52,-13.24,36.0,X-LC,11.86,28.0,-0.17,1.36,0.0,X40,ATH,FINANCE
9,BAJAJHFL,-3.61,-28.13,116.33,55.47,203401.0,-68438.0,174848.0,181.50,-38.44,23.0,X-MC,17.47,60.0,-0.34,1.33,0.0,X40N,ATH,FINANCE
8,AWL,-4.80,-41.65,169.41,57.19,322355.0,-135846.0,190281.0,485.00,-66.62,13.0,X-SC,19.48,81.0,-0.42,1.45,0.0,XY24,NTT,FMCG
12,BATAINDIA,-3.38,-50.82,174.94,35.20,110693.0,-65395.0,63275.0,2096.00,-17.11,23.0,X-SC,22.65,91.0,-0.59,0.48,0.0,X40,NTT,FOOTWEAR

In [20]:
# top 5 to accumulate based on lowest CurrAlloc%
df_tmp = df_portfolio_features[df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])].sort_values(by = 'CurrAlloc%', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
5,ANGELONE,-3.88,-90.82,1253.17,24.20,351113.0,-277232.0,28018.0,3033.0,-86.88,30.0,X-SC,2.45,97.0,-0.79,0.21,17.34,X40N,NTT,FINANCE
54,QUESS,-1.80,-35.25,120.59,42.84,50761.0,-22912.0,42094.0,424.0,-57.58,36.0,X-SC,17.17,80.0,-0.45,0.32,1.25,XY24,NTT,MISC
58,RELAXO,-3.88,-56.67,251.46,52.31,158181.0,-82255.0,62905.0,1176.0,-53.83,28.0,X-SC,15.37,92.0,-0.52,0.48,0.00,X40N,NTT,FOOTWEAR
12,BATAINDIA,-3.38,-50.82,174.94,35.20,110693.0,-65395.0,63275.0,2096.0,-17.11,23.0,X-SC,22.65,91.0,-0.59,0.48,0.00,X40,NTT,FOOTWEAR
51,MEDANTA,-0.77,-5.65,31.50,24.08,37731.0,-7170.0,119780.0,1486.0,-6.31,48.0,X-SC,7.96,87.0,-0.19,0.91,9.71,XY24,NTT,HEALTHCARE

In [21]:
# top 5 to accumulate based on CumlRnk
df_tmp = df_portfolio_features.sort_values(by = 'CumlRnk', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
45,ITC,-0.30,-17.65,44.57,19.06,124856.0,-60032.0,280134.0,452.00,-54.71,38.0,X-LC,17.15,1.0,-0.48,2.13,1.43,X40,NTT,FMCG
73,TCS,-1.23,-25.34,65.51,23.58,211610.0,-109609.0,323020.0,4311.59,-35.10,29.0,X-LC,9.91,2.0,-0.52,2.45,1.22,X40,ATH,IT
43,INFY,-1.74,-13.03,54.36,34.24,147918.0,-40780.0,272108.0,1972.00,-31.42,22.0,X-LC,9.40,3.0,-0.28,2.07,0.16,X40,NTT,IT
75,TMPV,-2.85,-17.39,61.40,33.33,165256.0,-56653.0,269147.0,600.00,-82.53,49.0,X-LC,3.89,4.0,-0.34,2.04,10.03,XY24,NTT,AUTO
34,HCLTECH,-1.58,-11.28,39.58,23.83,84953.0,-27289.0,214635.0,1908.19,-6.95,28.0,X-LC,6.70,8.0,-0.32,1.63,2.98,X40,ATH,IT

In [22]:
# top 5 for average up
df_tmp = df_portfolio_features[(df_portfolio_features['Dev%_200'] > 5)].sort_values(by = 'CurrAlloc%', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
42,INDUSINDBK,-1.35,-30.32,90.72,32.89,48805.0,-23410.0,53797.0,1800.00,-353.50,57.0,L-MC,12.16,258.0,-0.48,0.41,48.15,XR,NTT,BANKS
67,SONACOMS,-4.01,-11.24,56.71,39.09,50917.0,-11375.0,89784.0,804.02,-29.65,47.0,M-MC,11.20,193.0,-0.22,0.68,27.01,AR,ATH,AUTO
19,COALINDIA,-1.93,3.86,13.30,17.67,20784.0,5810.0,156270.0,478.51,24.82,50.0,L-LC,10.81,185.0,0.28,1.19,25.45,XY25,ATH,MINING
65,SIEMENS,-2.25,-10.22,39.79,25.51,66483.0,-19010.0,167085.0,4671.50,40.24,60.0,H-LC,3.83,51.0,-0.29,1.27,23.04,AR,ATH,ELECTRICAL
27,FINCABLES,2.33,18.42,75.57,107.91,132130.0,27201.0,174845.0,1641.55,6.54,77.0,M-SC,6.70,220.0,0.21,1.33,31.54,OX40N,ATH,CABLES

In [23]:
# top 5 RSP
df_tmp = df_portfolio_features.sort_values(by = 'RSP', ascending=False)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
27,FINCABLES,2.33,18.42,75.57,107.91,132130.0,27201.0,174845.0,1641.55,6.54,77.0,M-SC,6.70,220.0,0.21,1.33,31.54,OX40N,ATH,CABLES
26,EASEMYTRIP,-7.42,-55.96,230.83,45.70,179745.0,-98946.0,77869.0,26.40,-19.28,51.0,M-SC,18.11,204.0,-0.55,0.59,28.30,XY24,NTT,TRAVEL
11,BANDHANBNK,-1.75,-13.99,123.71,92.42,296399.0,-38967.0,239592.0,400.00,105.46,66.0,H-SC,8.61,174.0,-0.13,1.82,31.98,XY24,NTT,BANKS
83,WHIRLPOOL,-2.19,-27.74,151.76,81.92,125888.0,-31846.0,82952.0,2270.00,-57.64,53.0,M-SC,25.95,210.0,-0.25,0.63,16.52,XR,NTT,DURABLES
82,VOLTAS,-3.16,18.28,22.76,45.20,51616.0,35043.0,226785.0,1856.00,35.37,55.0,X-MC,9.68,79.0,0.68,1.72,26.32,XY25,NTT,AC

In [24]:
# Top N allocation
df_tmp = df_portfolio_features.sort_values(by = 'CurrAlloc%', ascending=False)
top_n_values = [10, 25, 50]

sum_df = pd.DataFrame({
    'Top_N': top_n_values,
    'Sum_Alloc%': [df_tmp['CurrAlloc%'].head(n).sum() for n in top_n_values]
})

sum_df

   Top_N  Sum_Alloc%
0     10       20.82
1     25       45.98
2     50       78.05

In [25]:
# market-cap-wise allocation
df_tmp = df_portfolio_features[cols]
df_tmp.groupby(df_tmp['Conviction'].str[-2:])['CurrAlloc%'].sum().sort_values(ascending=False)

Conviction
SC    43.78
MC    30.93
LC    25.33
Name: CurrAlloc%, dtype: float64

In [26]:
# criteria-wise allocation
df_portfolio_features.groupby('Criteria')['CurrAlloc%'].sum().sort_values(ascending=False)

Criteria
XY24     27.46
X40      24.39
X40N     12.94
AR        9.31
XY25      9.11
XR        8.62
OX40N     7.37
SR        0.84
Name: CurrAlloc%, dtype: float64

In [27]:
# conviction-wise allocation
df_portfolio_features.groupby('Conviction')['CurrAlloc%'].sum().sort_values(ascending=False)

Conviction
X-MC    23.32
H-SC    22.62
X-LC    21.82
M-SC    11.01
X-SC     9.45
H-MC     5.10
M-MC     2.10
H-LC     1.27
L-LC     1.19
M-LC     1.05
L-SC     0.70
L-MC     0.41
Name: CurrAlloc%, dtype: float64

In [28]:
# sector-wise stats
df_tmp = df_portfolio_features.groupby('Category')[['CurrAlloc%', 'Current', 'Current P/L', 'FTT Amt']].sum().sort_values(by=['Current', 'Current P/L'], ascending=False)
df_tmp['Current P/L%'] = round(df_tmp['Current P/L'] * 100 / df_tmp['Current'], 2)
df_tmp['FTT%'] = round(df_tmp['FTT Amt'] * 100 / df_tmp['Current'], 2)
cols = ['CurrAlloc%', 'Current P/L%', 'FTT%']
df_tmp[cols].sort_values(by=['CurrAlloc%'], ascending=False)

               CurrAlloc%  Current P/L%    FTT%
Category
FMCG                16.02        -17.07   56.66
IT                  11.63        -43.15  114.88
FINANCE             11.15        -42.34   98.35
MISC                 6.92        -42.76  101.16
ELECTRICAL           6.52         -9.44   49.37
PAINTS               5.13        -36.86   57.20
INSURANCE            5.07         -1.63   36.41
PHARMA               4.28         -4.18   36.98
AUTO                 3.96        -19.56   65.15
BANKS                3.19        -27.49  104.74
AC                   2.30         -5.47   34.06
FOOTWEAR             2.04        -64.17  129.99
TRAVEL               2.00        -70.01  155.14
DURABLES             1.92        -52.97   90.18
BREWERIES            1.79          0.65   19.98
HEALTHCARE           1.70        -37.91   71.94
REALTY               1.45        -16.26   35.37
CERAMICS             1.42        -63.68  113.41
APPARELS             1.42        -27.22   65.57
REFINERIES           1.33        -14.47   43.43
CABLES               1.33         15.56   75.57
JEWELLERY            1.22       -100.13  169.66
MINING               1.19          3.72   13.30
CEMENT               1.18        -52.71  150.67
ENGINEERING          1.16        -58.06  130.36
CHEMICALS            1.04        -93.80  251.92
ENTERTAINMENT        0.80        -84.40  194.38
TEXTILES             0.46        -53.20   96.88
HOTELS               0.42       -103.65  175.48

In [29]:
# money to be made criteria-wise
df_portfolio_features.groupby('Criteria')['FTT Amt'].agg(['sum', 'count']).sort_values(by='sum', ascending=False)

                sum  count
Criteria
XY24      3511986.0     21
X40       1512169.0     15
X40N      1417543.0     10
XR        1358290.0     12
AR        1345155.0     10
OX40N      822343.0     10
XY25       419064.0      6
SR         308709.0      2

In [30]:
# money to be made conviction-wise
df_portfolio_features.groupby('Conviction')['FTT Amt'].agg(['sum', 'count']).sort_values(by='sum', ascending=False)

                  sum  count
Conviction
H-SC        3813628.0     24
X-SC        1560818.0     10
M-SC        1470133.0     14
X-MC        1444717.0     15
X-LC        1399433.0     12
H-MC         407684.0      3
L-SC         198754.0      2
M-LC         154202.0      1
M-MC         109818.0      2
H-LC          66483.0      1
L-MC          48805.0      1
L-LC          20784.0      1

In [31]:
# money to be made criteria and conviction-wise
df_portfolio_features.groupby(['Conviction', 'Criteria'])['FTT Amt'].agg(['sum', 'count']).sort_values(by='sum', ascending=False)

                           sum  count
Conviction Criteria
H-SC       XY24      1286124.0      6
           AR         971784.0      5
           XR         873213.0      7
M-SC       XY24       861535.0      6
X-LC       X40        737538.0      6
X-SC       X40N       720698.0      4
           XY24       645621.0      4
X-MC       X40        580132.0      7
           X40N       458082.0      4
H-SC       OX40N      373798.0      4
M-SC       OX40N      347633.0      5
H-SC       SR         308709.0      2
X-LC       XY24       285913.0      2
           X40N       238763.0      2
H-MC       XY24       228450.0      1
X-MC       XY24       204343.0      2
           XY25       202160.0      2
X-SC       X40        194499.0      2
M-SC       XR         184228.0      2
H-MC       AR         179234.0      2
M-LC       XR         154202.0      1
X-LC       XY25       137219.0      2
L-SC       OX40N      100912.0      1
           XR          97842.0      1
M-SC       AR          76737.0      1
H-LC       AR          66483.0      1
M-MC       XY25        58901.0      1
           AR          50917.0      1
L-MC       XR          48805.0      1
L-LC       XY25        20784.0      1

In [32]:
# notebook execution time

end_time = time.time()
execution_time = round(end_time - start_time, 0)
print(f"Notebook execution time: {execution_time} seconds")

Notebook execution time: 25.0 seconds