<a href="https://colab.research.google.com/github/ankit-rathi/Quantvesting_v2/blob/main/myStocks_Portfolio_Analysis.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
'''
!pip install pandas==2.2.2 -qq
!pip install pyxirr -qq
!pip install ta -qq
!pip install yfinance==0.2.59 -qq
'''

'\n!pip install pandas==2.2.2 -qq\n!pip install pyxirr -qq\n!pip install ta -qq\n!pip install yfinance==0.2.59 -qq\n'

In [2]:
# import libraries

import numpy as np
import pandas as pd
import datetime
import warnings
warnings.filterwarnings('ignore')
import yfinance as yfin
import ta
import matplotlib.pyplot as plt
import requests

In [3]:
# notebook start time
import time
import datetime
import pytz

start_time = time.time()

# function to print date timestamp
def print_date_time():
  tz_NY = pytz.timezone('Asia/Kolkata')
  datetime_NY = datetime.datetime.now(tz_NY)
  print("Run date time (IST):", datetime_NY.strftime("%Y-%m-%d %H:%M:%S"))

In [4]:
# function to get booked and reserved amount
def get_amt():
  # fetch the JSON data from the URL
  url = "https://raw.githubusercontent.com/ankit-rathi/Tradevesting_v1/main/data/myPortfolioAmts.json"
  response = requests.get(url)
  pf_amts = response.json()  # parse the JSON data

  # extract values from the JSON
  py_booked_amt_dm = pf_amts["py_booked_amt_dm"]
  py_booked_amt_sv = pf_amts["py_booked_amt_sv"]
  cy_booked_amt_dm = pf_amts["cy_booked_amt_dm"]
  cy_booked_amt_sv = pf_amts["cy_booked_amt_sv"]
  reserve_amt_dm = pf_amts["reserve_amt_dm"]
  reserve_amt_sv = pf_amts["reserve_amt_sv"]

  # perform calculations
  py_booked_amt = py_booked_amt_dm + py_booked_amt_sv
  cy_booked_amt = cy_booked_amt_dm + cy_booked_amt_sv
  reserve_amt = reserve_amt_dm + reserve_amt_sv
  total_booked_amt = py_booked_amt + cy_booked_amt

  return total_booked_amt, reserve_amt, cy_booked_amt, py_booked_amt

gen_output = 0

In [5]:
# function to format the amount
def format_amt(number):
    abs_number = abs(number)

    if abs_number >= 1_00_00_000:  # Crores
        formatted_amt = f"{number / 1_00_00_000:.2f} C"
    elif abs_number >= 1_00_000:  # Lakhs
        formatted_amt = f"{number / 1_00_000:.2f} L"
    elif abs_number >= 1_000:  # Thousands
        formatted_amt = f"{number / 1_000:.2f} K"
    else:
        formatted_amt = f"{number:.2f}"

    return formatted_amt

# function to set start and end date
def get_start_end_date():
  start_date = (datetime.date.today() + datetime.timedelta(days=-365)).strftime('%Y-%m-%d')
  end_date = (datetime.date.today() + datetime.timedelta(days=1)).strftime('%Y-%m-%d')
  return start_date, end_date

# function to fetch my portfolio csv
def get_mypfs_df():
  mypfs_df = pd.read_csv('https://raw.githubusercontent.com/ankit-rathi/Tradevesting_v1/main/data/myPortfolioStocks.csv')
  return mypfs_df

# function to fetch my prospects csv
def get_mypps_df():
  mypps_df = pd.read_csv('https://raw.githubusercontent.com/ankit-rathi/Tradevesting_v1/main/data/myProspectsScrips.csv')
  return mypps_df

# function to fetch screener data
def get_myscreen_df():
  myscreen_df = pd.read_csv('https://raw.githubusercontent.com/ankit-rathi/Tradevesting_v1/main/data/myScreenerDB.csv')
  return myscreen_df

# function to fetch momentum data
def get_myinvmt_df():
  myinvmt_df = pd.read_csv('https://raw.githubusercontent.com/ankit-rathi/Tradevesting_v1/main/data/myInvestments.csv')
  return myinvmt_df

# function to get the stock ids
def get_stock_ids(df_pf):
  stock_n100 = df_pf['Symbol'].unique()

  exclude = ['CADILAHC','MMTC', 'MASFIN']

  stock_ids = df_pf[~df_pf['Symbol'].isin(exclude) ]['Symbol'].unique()

  #mypf = mypf[mypf.Forecast.notnull()]
  #stock_ids = mypf['Symbol'].unique()

  #stock_ids.sort()
  return stock_ids

# get features from screener data
def get_screener_features():
  myscreen_df = get_myscreen_df()
  cols = ['Symbol', 'EPS', 'MedPE', 'ROCE%', 'ROE%', 'CapType']
  return myscreen_df[cols]

# get relative strength
def get_relative_strength(stock_list):

    # Dictionary to store stock tickers and their corresponding percentage price change
    stock_changes = {}

    # Loop through each stock and fetch its price data
    for stock in stock_list:
        try:
            # Download the stock data for the given date range
            stock_data = yfin.Ticker(stock + '.NS').history(period='1mo', interval='1d')[map(str.title, ['open', 'close', 'low', 'high', 'volume'])]

            # Calculate the percentage change for the stock
            if len(stock_data) > 0:
                start_price = stock_data['Close'].iloc[0]
                end_price = stock_data['Close'].iloc[-1]
                percent_change = round(((end_price - start_price) / start_price) * 100, 2)
                stock_changes[stock] = percent_change
            else:
                stock_changes[stock] = np.nan  # If no data is available, set to NaN

        except Exception as e:
            print(f"Error fetching data for {stock}: {e}")
            stock_changes[stock] = np.nan

    # Create a DataFrame with stock tickers and their percentage changes
    df = pd.DataFrame(list(stock_changes.items()), columns=['Symbol', 'Percent_Change'])

    # Drop any stocks with missing data (NaN values)
    df = df.dropna()

    # Calculate the percentile rank based on percentage change
    df['RSP'] = round(df['Percent_Change'].rank(pct=True) * 100, 2)
    cols = ['Symbol', 'RSP']
    df = df[cols]
    # Sort by percentile rank (optional)
    df = df.sort_values(by='RSP', ascending=False).reset_index(drop=True)

    return df

In [6]:
# function to get stock technicals
def stock_prec_dev(stock_symbol):
    #stock_symbol = 'ULTRACEMCO.NS'
    short_window = 20
    mid_window = 50
    long_window = 200
    moving_avg = 'SMA'

    start = datetime.datetime(*map(int, start_date.split('-')))
    end = datetime.datetime(*map(int, end_date.split('-')))

    stock_df = yfin.Ticker(stock_symbol + '.NS').history(period='max', interval='1d')[map(str.title, ['open', 'close', 'low', 'high', 'volume'])]

    stock_df['Max'] = round(max(stock_df['Close']),2)
    stock_df = stock_df[(stock_df.index <= end_date) & (stock_df.index >= start_date)]
    stock_df['200_SMA'] = round(stock_df['Close'].rolling(window = 200, min_periods = 1).mean(),0)
    stock_df['Dev%_200'] = round((stock_df['Close'] - stock_df['200_SMA'])*100/stock_df['200_SMA'],2)
    stock_df.dropna(axis = 0, inplace = True) # remove any null rows

    stock_df['20_SMA'] = stock_df['Close'].rolling(window=20).mean()
    stock_df['50_SMA'] = stock_df['Close'].rolling(window=50).mean()
    stock_df['Symbol'] = stock_symbol

    stock_df['Close'] = round(stock_df['Close'],2)
    stock_df['Min'] = round(min(stock_df['Close']),2)
    stock_df['RSI_14'] = ta.momentum.RSIIndicator(close=stock_df['Close'], window=14).rsi()
    stock_df['RSI_14'] = round(stock_df['RSI_14'],0)
    stock_df['Prev_Close'] = stock_df['Close'].shift(1)
    stock_df.drop(['Open', 'Low', 'High', 'Volume'], axis=1, inplace=True)
    stock_df = stock_df.tail(1)

    max_SMA = max(stock_df['20_SMA'].item(), stock_df['50_SMA'].item(), stock_df['200_SMA'].item())
    min_SMA = min(stock_df['20_SMA'].item(), stock_df['50_SMA'].item(), stock_df['200_SMA'].item())
    ABS_Spread = max_SMA - min_SMA
    stock_df['Spread%'] = round((ABS_Spread / stock_df['200_SMA'].item()) * 100,2)

    return stock_df

# function to compute stock attributes
def get_common_features(stock_ids, df_mypf):

  df_prec_dev = pd.DataFrame()
  df_tmp = get_screener_features()
  df_rs = get_relative_strength(stock_ids)

  for stock_id in stock_ids:
      tmp = stock_prec_dev(stock_id)
      tmp = tmp.reset_index()
      df_prec_dev = pd.concat([df_prec_dev, tmp], ignore_index = True)
  df_prec_dev = pd.merge(df_prec_dev, df_mypf, on= 'Symbol')
  df_prec_dev = pd.merge(df_prec_dev, df_tmp, on= 'Symbol', how='left')
  df_prec_dev = pd.merge(df_prec_dev, df_rs, on= 'Symbol', how='left')
  #print(df_prec_dev.columns)
  df_prec_dev['Curr_PE'] = round(df_prec_dev['Close']/df_prec_dev['EPS'],1)
  df_prec_dev['Dev%_PE'] = round((df_prec_dev['Curr_PE'] - df_prec_dev['MedPE'])*100/df_prec_dev['MedPE'],2)
  df_prec_dev['Conviction'] = df_prec_dev['Conviction'] + '-' + df_prec_dev['CapType']
  return df_prec_dev

# function to arrange stock features
def arrange_features(df_stocks, common_cols, diff_cols):
  df_stocks_common = df_stocks[common_cols].drop_duplicates()
  df_stocks_diff = df_stocks[diff_cols]
  df_stocks_diff['Investment'] = df_stocks_diff['AvgCost'] * df_stocks_diff['Shares']
  df_stocks_diff = df_stocks_diff.groupby(['Symbol'])[['Shares', 'Investment']].aggregate(['sum']).reset_index()
  df_stocks_diff.columns = ['Symbol', 'Shares', 'Investment']
  df_stocks_diff['AvgCost'] = round(df_stocks_diff['Investment']/df_stocks_diff['Shares'],2)
  df_stocks = pd.merge(df_stocks_diff, df_stocks_common, on='Symbol')
  return df_stocks

# plot fact distribution across dimension
def plot_pie_chart(df, dimension, fact):
  # grouping the data by category and calculating the sum of fact for each type
  grouped_data = df.groupby(dimension)[fact].sum()

  # sorting the grouped data in descending order
  grouped_data = grouped_data.sort_values(ascending=False)

  # creating a pie chart
  grouped_data.plot.pie(autopct='%1.1f%%', startangle=90, figsize=(6, 6))

  # adding a title and displaying the plot
  plt.title(f'{dimension} {fact} Distribution')
  plt.ylabel('')  # To hide the y-label
  plt.show()

In [7]:
# function to get portfolio features

def get_portfolio_features(df_common_features):

  print_date_time()
  print('-------------------')

  #df_common_features["Target"] = df_common_features["Target"].fillna(df_common_features["Max"])
  df_common_features['NTT'] = np.where(df_common_features['Strategy']== 'NTT', df_common_features["Target"], df_common_features['Max'])
  df_common_features['LTT'] = np.where(df_common_features['Strategy']== 'BTT', df_common_features["Target"], df_common_features['Max'])
  df_common_features['BOL'] = df_common_features['Min']

  tmp_df = df_common_features[df_common_features['Symbol'].isin(mypf_df[mypf_df['InPortfolio'] != 'NA'].Symbol.values)]
  print('qualified stocks: '+str(len(tmp_df['Symbol'].unique())))
  tmp_df1 = tmp_df[tmp_df['LatestQtr'] == 1]
  print('with latest results: '+str(len(tmp_df1['Symbol'].unique())))
  tmp_df1 = tmp_df1[tmp_df1['StarStock'] == 1]
  print('still star stocks: '+str(len(tmp_df1['Symbol'].unique())))
  tmp_df['Investment'] = tmp_df['AvgCost'] * tmp_df['Shares']
  tmp_df['Current'] = round(tmp_df['Close'] * tmp_df['Shares'],0)
  tmp_df['Previous'] = tmp_df['Prev_Close'] * tmp_df['Shares']
  tmp_df['EstimatedST'] = tmp_df['NTT'] * tmp_df['Shares']
  tmp_df['EstimatedLT'] = tmp_df['LTT'] * tmp_df['Shares']
  tmp_df['Current P/L'] = round((tmp_df['Current'] - tmp_df['Investment']),0)
  tmp_df['Today P/L%'] = round((tmp_df['Current'] - tmp_df['Previous'])*100/tmp_df['Previous'],2)
  tmp_df['Current P/L%'] = round((tmp_df['Current'] - tmp_df['Investment'])*100/tmp_df['Investment'],2)
  tmp_df['EstimatedST P/L%'] = round((tmp_df['EstimatedST'] - tmp_df['Investment'])*100/tmp_df['Investment'],2)
  tmp_df['EstimatedLT P/L%'] = round((tmp_df['EstimatedLT'] - tmp_df['Investment'])*100/tmp_df['Investment'],2)
  tmp_df['NTT%'] = round((tmp_df['NTT'] - tmp_df['Close'])*100/tmp_df['Close'],2)
  tmp_df['LTT%'] = round((tmp_df['LTT'] - tmp_df['Close'])*100/tmp_df['Close'],2)
  tmp_df['Gained%'] = round((tmp_df['Close'] - tmp_df['BOL'])*100/tmp_df['BOL'],2)
  investment = round(sum(tmp_df['AvgCost']*tmp_df['Shares']),0)
  current = round(sum(tmp_df['Close']*tmp_df['Shares']),0)
  tmp_df['InitAlloc%'] = round(tmp_df['Investment']*100/investment,2)
  tmp_df['CurrAlloc%'] = round(tmp_df['Current']*100/current,2)
  tmp_df['FTT'] = tmp_df['LTT']
  tmp_df.loc[tmp_df['Strategy'] == 'NTT', 'FTT'] = tmp_df['NTT']
  tmp_df['FTT%'] = tmp_df['LTT%']
  tmp_df.loc[tmp_df['Strategy'] == 'NTT', 'FTT%'] = tmp_df['NTT%']
  tmp_df['FTT Amt'] = round(tmp_df['FTT%'] * tmp_df['Current']/100,0)
  tmp_df['OTT%'] = round((tmp_df['FTT'] - tmp_df['AvgCost'])*100/tmp_df['AvgCost'],2)
  tmp_df['RRR Ind'] = round(tmp_df['Current P/L']/tmp_df['FTT Amt'],2)
  tmp_df['Risk Ind'] = round(tmp_df['Current P/L%']*tmp_df['CurrAlloc%'],0)

  return tmp_df

# function to print portfolio features
def print_portfolio_stats(df_portfolio_features, myinvmt_df):
  from pyxirr import xirr

  total_booked_amt, reserve_amt, cy_booked_amt, py_booked_amt = get_amt()

  dates = myinvmt_df['Date'].values
  dates = np.append(dates, datetime.date.today().strftime('%d-%b-%y'))
  investment = myinvmt_df['Investment'].values
  dates= pd.to_datetime(dates)

  current = round(sum(df_portfolio_features['Close']*df_portfolio_features['Shares']),0) + reserve_amt
  investment_xirr = np.append(investment, current)
  cagr = round(xirr(pd.DataFrame({"dates": dates, "amounts": investment_xirr}))*100,2)

  investment = -sum(investment)
  invested = round(sum(df_portfolio_features['AvgCost']*df_portfolio_features['Shares']),0) + reserve_amt
  previous = round(sum(df_portfolio_features['Prev_Close']*df_portfolio_features['Shares']),0) + reserve_amt
  cy_invested = investment + py_booked_amt

  today_pnl_amount = current-previous
  today_pnl_percentage = round((current-previous)*100/previous,2)

  curr_pnl_amount = current-invested
  curr_pnl_percentage = round((curr_pnl_amount)*100/(cy_invested),2)

  cy_pnl_amount = cy_booked_amt + curr_pnl_amount
  cy_pnl_percentage = round((cy_pnl_amount)*100/cy_invested,2)

  overall_pnl_amount = total_booked_amt + curr_pnl_amount
  overall_pnl_percentage = round((overall_pnl_amount)*100/investment,2)

  estimate_st = round(sum(df_portfolio_features['FTT']*df_portfolio_features['Shares']),0)  + reserve_amt
  est_st_pnl_amount = estimate_st-current
  est_st_pnl_percentage = round((est_st_pnl_amount)*100/current,2)

  estimate_lt = round(sum(df_portfolio_features['LTT']*df_portfolio_features['Shares']),0)  + reserve_amt
  est_lt_pnl_amount = estimate_lt-current
  est_lt_pnl_percentage = round((est_lt_pnl_amount)*100/current,2)

  total_profit = round(sum(df_portfolio_features[df_portfolio_features['Current P/L%'] > 0]['Current']) - sum(df_portfolio_features[df_portfolio_features['Current P/L%'] > 0]['Investment']),0)
  total_loss = round(sum(df_portfolio_features[df_portfolio_features['Current P/L%'] < 0]['Current']) - sum(df_portfolio_features[df_portfolio_features['Current P/L%'] < 0]['Investment']),0)

  cy_booked_percentage = round((cy_booked_amt)*100/current,2)
  py_booked_percentage = round((py_booked_amt)*100/investment,2)
  total_booked_percentage = round((total_booked_amt)*100/investment,2)

  print('-------------------')
  print('Initial Investment: ', format_amt(investment))
  print('CY Investment: ', format_amt(cy_invested))
  print('Reserve: ', format_amt(reserve_amt))
  print('Current: ',  format_amt(current))
  print('-------------------')
  print('Today PnL: '+ '{} ({}%)'.format(format_amt(today_pnl_amount), today_pnl_percentage))
  print('Current PnL: '+ '{} ({}%)'.format(format_amt(curr_pnl_amount), curr_pnl_percentage))
  print('CY Booked + Current PnL: '+ '{} ({}%)'.format(format_amt(cy_pnl_amount), cy_pnl_percentage))
  print('-------------------')
  print('Total profit: ', format_amt(total_profit))
  print('Total loss: ', format_amt(total_loss))
  print('-------------------')
  print('Total Booked + Current PnL: '+ '{} ({}%)'.format(format_amt(overall_pnl_amount), overall_pnl_percentage))
  print('Total Booked PnL: '+ '{} ({}%)'.format(format_amt(total_booked_amt), total_booked_percentage))
  print('Curr Year Booked PnL: '+ '{} ({}%)'.format(format_amt(cy_booked_amt), cy_booked_percentage))
  print('Prev Year Booked PnL: '+ '{} ({}%)'.format(format_amt(py_booked_amt), py_booked_percentage))
  print('===================')
  print('Est FTT: ',  format_amt(estimate_st))
  print('Est FTT PnL: '+ '{} ({}%)'.format(format_amt(est_st_pnl_amount), est_st_pnl_percentage))

  print('===================')
  print('Deployed: ', format_amt(investment))

  print('Current: ', format_amt(current))

  print('CAGR/XIRR %: '+'{}%'.format(cagr))

In [8]:
# get start and end date
start_date, end_date = get_start_end_date()

# get portfolio and prospects data
mypfs_df = get_mypfs_df()
mypps_df = get_mypps_df()
myinvmt_df = get_myinvmt_df()

# merge above datasets
mypf_df = pd.merge(mypfs_df, mypps_df, on="Symbol")

# seggregate dm and sv portfolio
dm_pf = mypf_df[mypf_df['InPortfolio'] == 'DM']
sv_pf = mypf_df[mypf_df['InPortfolio'] == 'SV']

# build portfolio stock dataframe
dm_stocks = get_stock_ids(dm_pf)
sv_stocks = get_stock_ids(sv_pf)
df_stocks = pd.concat([dm_pf,sv_pf], ignore_index = True)

# arrange common and diff stock features
common_cols = ['Symbol', 'Target', 'Criteria', 'Strategy', 'CumlRnk', 'LatestQtr', 'StarStock', 'Conviction', 'Category', 'InFolio', 'XIRR', 'MBQ']
diff_cols = ['Symbol', 'AvgCost', 'Shares']
df_stocks = arrange_features(df_stocks, common_cols, diff_cols)

# get common features
stock_ids = df_stocks['Symbol'].values
df_common_features = get_common_features(stock_ids, df_stocks)

df_common_features.reset_index(drop=True, inplace=True)
df_common_features.drop(['Date'], axis=1, inplace=True)
# get and print portfolio features
df_portfolio_features = get_portfolio_features(df_common_features)

print_portfolio_stats(df_portfolio_features, myinvmt_df)

df = df_portfolio_features
#plot_pie_chart(df, 'CapType', 'Current')
list_ox40n = list(df[df['MBQ'].str.contains('OX40N', na=False)]['Symbol'].values)

Run date time (IST): 2026-06-12 12:11:48
-------------------
qualified stocks: 92
with latest results: 31
still star stocks: 20

-------------------
Initial Investment:  1.40 C
CY Investment:  1.82 C
Reserve:  1.49 K
Current:  1.47 C
-------------------
Today PnL: 1.44 L (0.99%)
Current PnL: -36.25 L (-19.88%)
CY Booked + Current PnL: -34.17 L (-18.74%)
-------------------
Total profit:  2.26 L
Total loss:  -38.51 L
-------------------
Total Booked + Current PnL: 8.70 L (6.24%)
Total Booked PnL: 44.95 L (32.22%)
Curr Year Booked PnL: 2.08 L (1.42%)
Prev Year Booked PnL: 42.87 L (30.73%)
===================
Est FTT:  2.55 C
Est FTT PnL: 1.08 C (73.67%)
===================
Deployed:  1.40 C
Current:  1.47 C
CAGR/XIRR %: 2.44%

In [9]:
# top 5 near their targets
cols = ['Symbol', 'Today P/L%', 'Current P/L%', 'FTT%', 'OTT%', 'FTT Amt', 'Current P/L', 'Current', 'FTT', 'Dev%_PE', 'RSI_14','Conviction', 'Spread%',  'CumlRnk', 'RRR Ind', 'CurrAlloc%', 'Gained%', 'Criteria', 'Strategy', 'Category']
df_tmp = df_portfolio_features[~df_portfolio_features['Symbol'].isin(['ENRIN','BLUSPRING','DIGITIDE'])]
df_tmp = df_tmp.sort_values(by = 'FTT Amt', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
59,PIDILITIND,2.48,8.85,8.74,18.37,13425.0,12490.0,153600.0,1670.26,-23.73,69.0,X-LC,3.67,5.0,0.93,1.05,20.60,X40,ATH,CHEMICALS
51,KOTAKBANK,1.36,6.53,13.68,21.11,20181.0,9046.0,147519.0,453.24,-8.54,65.0,X-LC,6.44,12.0,0.45,1.00,12.82,X40,ATH,BANKS
72,SIS,-1.10,-2.63,24.54,21.26,26529.0,-2925.0,108107.0,528.00,2578.76,63.0,H-SC,21.42,168.0,-0.11,0.74,60.74,OX40N,NTT,MISC
83,TTKPRESTIG,0.29,-30.64,44.30,0.09,30967.0,-30875.0,69902.0,770.00,62.22,52.0,M-SC,11.83,250.0,-1.00,0.48,24.47,OX40N,NTT,DURABLES
55,MASFIN,0.34,-10.53,35.88,21.57,31452.0,-10320.0,87660.0,397.04,-22.76,35.0,H-SC,3.40,167.0,-0.33,0.60,4.49,XR,ATH,FINANCE

In [10]:
# top 5 today
df_tmp = df_portfolio_features.sort_values(by = 'Today P/L%', ascending=False)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
49,JSWINFRA,3.52,-2.92,19.94,16.43,42928.0,-6486.0,215288.0,342.0,-16.72,58.0,X-MC,2.64,61.0,-0.15,1.47,21.70,X40N,NTT,REALTY
80,TITAGARH,3.32,-19.98,82.12,45.74,159149.0,-48377.0,193800.0,1548.0,6.51,59.0,H-SC,4.54,175.0,-0.30,1.32,47.86,XY24,NTT,ENGINEERING
66,REPCOHOME,2.91,-18.13,131.85,89.82,309270.0,-51943.0,234562.0,880.0,-59.02,48.0,H-SC,2.69,161.0,-0.17,1.60,12.76,XY24,NTT,FINANCE
85,VAIBHAVGBL,2.88,-29.02,126.50,60.77,164110.0,-53044.0,129731.0,521.0,49.86,55.0,H-SC,3.50,160.0,-0.32,0.88,31.17,XR,NTT,JEWELLERY
38,HYUNDAI,2.84,6.07,40.80,49.35,66751.0,9365.0,163606.0,2809.3,-14.57,66.0,X-LC,15.95,29.0,0.14,1.11,17.96,X40N,ATH,AUTO

In [11]:
# bottom 5 today
df_tmp = df_portfolio_features.sort_values(by = 'Today P/L%', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
61,RAJESHEXPO,-5.00,-85.24,577.92,0.07,117023.0,-116928.0,20249.0,518.00,642.42,22.0,L-SC,33.53,268.0,-1.00,0.14,0.00,OX40N,NTT,JEWELLERY
39,ICICIGI,-1.99,-11.09,33.72,18.89,59991.0,-22199.0,177910.0,2244.41,-25.23,35.0,X-MC,5.13,66.0,-0.37,1.21,0.00,X40,ATH,INSURANCE
18,COFFEEDAY,-1.21,-42.10,133.64,35.27,87856.0,-47808.0,65741.0,80.00,-55.73,57.0,L-SC,16.72,266.0,-0.54,0.45,62.12,XR,NTT,HOTELS
72,SIS,-1.10,-2.63,24.54,21.26,26529.0,-2925.0,108107.0,528.00,2578.76,63.0,H-SC,21.42,168.0,-0.11,0.74,60.74,OX40N,NTT,MISC
50,KANSAINER,-0.80,-28.47,58.64,13.47,113110.0,-76779.0,192888.0,340.00,-38.54,54.0,H-SC,7.20,162.0,-0.68,1.31,34.73,XY24,NTT,PAINTS

In [12]:
# top 5 to exit based on CumlRnk
df_tmp = df_portfolio_features[~df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])]
df_tmp = df_tmp[(df_tmp['Current P/L%'] > -1) & (df_tmp['Current P/L%'] < 1)].sort_values(by = 'CumlRnk', ascending=False)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
74,STARHEALTH,0.01,0.63,46.35,47.26,131115.0,1757.0,282880.0,761.0,58.79,51.0,H-SC,9.94,173.0,0.01,1.93,24.19,XY24,NTT,INSURANCE

In [13]:
# OX40N stocks to exit
df_tmp = df_portfolio_features[(df_portfolio_features['Symbol'].isin(list_ox40n))].sort_values(by = 'Current P/L%', ascending=False)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
25,FINCABLES,1.25,29.90,60.06,107.91,115187.0,44143.0,191787.0,1641.55,16.69,49.0,M-SC,23.46,220.0,0.38,1.31,44.29,OX40N,ATH,CABLES
72,SIS,-1.10,-2.63,24.54,21.26,26529.0,-2925.0,108107.0,528.00,2578.76,63.0,H-SC,21.42,168.0,-0.11,0.74,60.74,OX40N,NTT,MISC
16,CERA,2.21,-21.76,58.34,23.89,80295.0,-38271.0,137632.0,9475.00,-24.58,65.0,H-SC,3.89,153.0,-0.48,0.94,32.26,OX40N,NTT,CERAMICS
50,KANSAINER,-0.80,-28.47,58.64,13.47,113110.0,-76779.0,192888.0,340.00,-38.54,54.0,H-SC,7.20,162.0,-0.68,1.31,34.73,XY24,NTT,PAINTS
83,TTKPRESTIG,0.29,-30.64,44.30,0.09,30967.0,-30875.0,69902.0,770.00,62.22,52.0,M-SC,11.83,250.0,-1.00,0.48,24.47,OX40N,NTT,DURABLES

In [14]:
# top 5 to book for rotation
df_tmp = df_portfolio_features[(df_portfolio_features['Current P/L%'] > 20) ].sort_values(by = 'CumlRnk', ascending=False)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
25,FINCABLES,1.25,29.90,60.06,107.91,115187.0,44143.0,191787.0,1641.55,16.69,49.0,M-SC,23.46,220.0,0.38,1.31,44.29,OX40N,ATH,CABLES
68,SATIN,1.51,23.57,22.87,51.83,78081.0,65129.0,341413.0,274.00,10.38,53.0,H-SC,40.36,159.0,0.83,2.32,66.32,XY24,NTT,FINANCE

In [15]:
# top 5 to monitor for exit
df_tmp = df_portfolio_features[~df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])]
df_tmp = df_tmp[(df_tmp['Current P/L%'] > 0) ].sort_values(by = 'Dev%_PE', ascending=False)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
74,STARHEALTH,0.01,0.63,46.35,47.26,131115.0,1757.0,282880.0,761.00,58.79,51.0,H-SC,9.94,173.0,0.01,1.93,24.19,XY24,NTT,INSURANCE
25,FINCABLES,1.25,29.90,60.06,107.91,115187.0,44143.0,191787.0,1641.55,16.69,49.0,M-SC,23.46,220.0,0.38,1.31,44.29,OX40N,ATH,CABLES
68,SATIN,1.51,23.57,22.87,51.83,78081.0,65129.0,341413.0,274.00,10.38,53.0,H-SC,40.36,159.0,0.83,2.32,66.32,XY24,NTT,FINANCE
91,ZYDUSLIFE,0.23,16.88,16.04,35.63,39291.0,35382.0,244956.0,1286.17,1.80,72.0,H-MC,12.56,120.0,0.90,1.67,28.79,AR,ATH,PHARMA
73,SONACOMS,0.44,1.67,36.81,39.09,37858.0,1689.0,102848.0,804.02,-19.39,48.0,M-MC,18.37,193.0,0.04,0.70,45.49,AR,ATH,AUTO

In [16]:
# top 5 to book for rotation from weak conviction
df_tmp = df_portfolio_features[~df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])]
df_tmp = df_tmp[~df_tmp['Criteria'].isin(['XY25','XY24','X40', 'X40N'])].sort_values(by = 'RRR Ind', ascending=False)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
91,ZYDUSLIFE,0.23,16.88,16.04,35.63,39291.0,35382.0,244956.0,1286.17,1.80,72.0,H-MC,12.56,120.0,0.90,1.67,28.79,AR,ATH,PHARMA
25,FINCABLES,1.25,29.90,60.06,107.91,115187.0,44143.0,191787.0,1641.55,16.69,49.0,M-SC,23.46,220.0,0.38,1.31,44.29,OX40N,ATH,CABLES
73,SONACOMS,0.44,1.67,36.81,39.09,37858.0,1689.0,102848.0,804.02,-19.39,48.0,M-MC,18.37,193.0,0.04,0.70,45.49,AR,ATH,AUTO
42,INDIAMART,2.17,-13.58,139.22,106.72,148385.0,-16753.0,106583.0,4810.62,-60.94,49.0,H-SC,10.64,140.0,-0.11,0.73,3.18,AR,ATH,MISC
72,SIS,-1.10,-2.63,24.54,21.26,26529.0,-2925.0,108107.0,528.00,2578.76,63.0,H-SC,21.42,168.0,-0.11,0.74,60.74,OX40N,NTT,MISC

In [17]:
# top 5 to accumulate based on lowest RSI_14
df_tmp = df_portfolio_features[df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])].sort_values(by = 'RSI_14', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
27,GLAXO,0.06,-15.52,60.62,35.69,102060.0,-30924.0,168360.0,3380.16,-35.51,26.0,X-MC,9.70,56.0,-0.30,1.15,0.06,X40,ATH,PHARMA
35,HDFCLIFE,0.50,-10.37,48.59,33.18,65237.0,-15540.0,134260.0,814.30,-30.01,27.0,X-LC,16.22,31.0,-0.24,0.91,0.50,X40,ATH,INSURANCE
40,ICICIPRULI,0.86,-23.16,69.54,30.28,105268.0,-45627.0,151378.0,787.27,-43.84,30.0,X-MC,16.66,78.0,-0.43,1.03,0.86,X40,ATH,INSURANCE
58,PGHH,-0.41,-32.65,96.02,32.01,138077.0,-69720.0,143800.0,17616.87,-54.51,30.0,X-MC,19.13,57.0,-0.50,0.98,0.00,X40,ATH,FMCG
65,RELIANCE,0.30,-18.68,54.09,25.30,88392.0,-37546.0,163417.0,1952.00,-20.80,32.0,X-LC,7.39,21.0,-0.42,1.11,0.64,XY25,BTT,REFINERIES

In [18]:
# top 5 to accumulate based on Spread and CumlRnk
df_tmp = df_portfolio_features[df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])]
df_tmp = df_tmp[(df_tmp['CumlRnk'] < 100)].sort_values(by = 'Spread%', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
49,JSWINFRA,3.52,-2.92,19.94,16.43,42928.0,-6486.0,215288.0,342.00,-16.72,58.0,X-MC,2.64,61.0,-0.15,1.47,21.70,X40N,NTT,REALTY
57,PAGEIND,1.89,0.30,33.19,33.59,89343.0,806.0,269185.0,51217.29,-28.02,56.0,X-MC,2.88,55.0,0.01,1.83,27.84,X40,ATH,APPARELS
15,CAMS,2.12,-3.30,28.73,24.48,69969.0,-8316.0,243540.0,950.00,-7.37,43.0,X-SC,3.06,89.0,-0.12,1.66,18.56,X40N,NTT,MISC
19,COLPAL,1.45,-21.86,78.98,39.86,162541.0,-57565.0,205800.0,3683.41,-5.40,51.0,X-MC,3.14,62.0,-0.35,1.40,16.41,XY25,ATH,FMCG
59,PIDILITIND,2.48,8.85,8.74,18.37,13425.0,12490.0,153600.0,1670.26,-23.73,69.0,X-LC,3.67,5.0,0.93,1.05,20.60,X40,ATH,CHEMICALS

In [19]:
# top 5 to accumulate based on lowest Gained%
df_tmp = df_portfolio_features[df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])].sort_values(by = 'Gained%', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
39,ICICIGI,-1.99,-11.09,33.72,18.89,59991.0,-22199.0,177910.0,2244.41,-25.23,35.0,X-MC,5.13,66.0,-0.37,1.21,0.00,X40,ATH,INSURANCE
33,HCLTECH,-0.20,-28.09,68.98,21.51,119995.0,-67968.0,173956.0,1872.35,-24.32,33.0,X-LC,18.45,8.0,-0.57,1.18,0.00,X40,ATH,IT
58,PGHH,-0.41,-32.65,96.02,32.01,138077.0,-69720.0,143800.0,17616.87,-54.51,30.0,X-MC,19.13,57.0,-0.50,0.98,0.00,X40,ATH,FMCG
27,GLAXO,0.06,-15.52,60.62,35.69,102060.0,-30924.0,168360.0,3380.16,-35.51,26.0,X-MC,9.70,56.0,-0.30,1.15,0.06,X40,ATH,PHARMA
35,HDFCLIFE,0.50,-10.37,48.59,33.18,65237.0,-15540.0,134260.0,814.30,-30.01,27.0,X-LC,16.22,31.0,-0.24,0.91,0.50,X40,ATH,INSURANCE

In [20]:
# top 5 to accumulate based on lowest CurrAlloc%
df_tmp = df_portfolio_features[df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])].sort_values(by = 'CurrAlloc%', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
10,BATAINDIA,0.76,-57.24,216.21,35.20,118952.0,-73653.0,55017.0,2096.0,-27.80,40.0,X-SC,25.57,91.0,-0.62,0.37,9.11,X40,NTT,FOOTWEAR
64,RELAXO,1.31,-55.82,244.77,52.31,156964.0,-81033.0,64127.0,1176.0,-52.96,61.0,X-SC,19.45,92.0,-0.52,0.44,43.38,X40N,NTT,FOOTWEAR
60,QUESS,0.30,-0.40,74.59,73.90,79340.0,-425.0,106368.0,424.0,-46.56,75.0,X-SC,5.22,80.0,-0.01,0.72,45.00,XY24,NTT,MISC
35,HDFCLIFE,0.50,-10.37,48.59,33.18,65237.0,-15540.0,134260.0,814.3,-30.01,27.0,X-LC,16.22,31.0,-0.24,0.91,0.50,X40,ATH,INSURANCE
53,M&M,-0.35,-2.96,27.15,23.38,36536.0,-4109.0,134572.0,3802.4,-17.91,43.0,X-LC,10.84,25.0,-0.11,0.92,2.03,X40N,ATH,AUTO

In [21]:
# top 5 to accumulate based on CumlRnk
df_tmp = df_portfolio_features.sort_values(by = 'CumlRnk', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
47,ITC,0.74,-25.06,58.88,19.06,150092.0,-85254.0,254912.0,452.00,-58.75,44.0,X-LC,15.17,1.0,-0.57,1.74,2.71,X40,NTT,FMCG
79,TCS,0.96,-36.70,97.29,24.88,285296.0,-170030.0,293243.0,4253.91,-46.57,38.0,X-LC,18.81,2.0,-0.60,2.00,0.96,X40,ATH,IT
45,INFY,0.35,-23.86,76.31,34.24,181801.0,-74648.0,238240.0,1972.00,-40.13,41.0,X-LC,16.72,3.0,-0.41,1.62,4.36,X40,NTT,IT
81,TMPV,1.13,-13.47,57.83,36.58,178071.0,-47919.0,307922.0,600.00,-82.53,53.0,X-LC,14.39,4.0,-0.27,2.10,28.34,XY24,NTT,AUTO
59,PIDILITIND,2.48,8.85,8.74,18.37,13425.0,12490.0,153600.0,1670.26,-23.73,69.0,X-LC,3.67,5.0,0.93,1.05,20.60,X40,ATH,CHEMICALS

In [22]:
# top 5 for average up
df_tmp = df_portfolio_features[(df_portfolio_features['Dev%_200'] > 5)].sort_values(by = 'CurrAlloc%', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
44,INDUSINDBK,0.69,-33.92,101.11,32.89,51584.0,-26188.0,51018.0,1800.00,-340.20,48.0,L-MC,7.08,258.0,-0.51,0.35,25.58,XR,NTT,BANKS
3,ALKYLAMINE,0.61,-22.49,149.80,93.63,117233.0,-22703.0,78260.0,4546.37,-17.07,59.0,H-SC,8.57,142.0,-0.19,0.53,47.78,SR,ATH,CHEMICALS
73,SONACOMS,0.44,1.67,36.81,39.09,37858.0,1689.0,102848.0,804.02,-19.39,48.0,M-MC,18.37,193.0,0.04,0.70,45.49,AR,ATH,AUTO
60,QUESS,0.30,-0.40,74.59,73.90,79340.0,-425.0,106368.0,424.00,-46.56,75.0,X-SC,5.22,80.0,-0.01,0.72,45.00,XY24,NTT,MISC
72,SIS,-1.10,-2.63,24.54,21.26,26529.0,-2925.0,108107.0,528.00,2578.76,63.0,H-SC,21.42,168.0,-0.11,0.74,60.74,OX40N,NTT,MISC

In [23]:
# top 5 RSP
df_tmp = df_portfolio_features.sort_values(by = 'RSP', ascending=False)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
18,COFFEEDAY,-1.21,-42.10,133.64,35.27,87856.0,-47808.0,65741.0,80.00,-55.73,57.0,L-SC,16.72,266.0,-0.54,0.45,62.12,XR,NTT,HOTELS
37,HONAUT,2.72,-6.16,61.25,51.31,110832.0,-11888.0,180950.0,58357.33,-22.03,65.0,X-SC,7.76,90.0,-0.11,1.23,37.47,X40N,ATH,ELECTRICAL
69,SFL,1.37,-32.14,86.62,26.63,154123.0,-84288.0,177930.0,1287.00,34.74,70.0,M-SC,9.38,242.0,-0.55,1.21,48.30,XY24,NTT,MISC
91,ZYDUSLIFE,0.23,16.88,16.04,35.63,39291.0,35382.0,244956.0,1286.17,1.80,72.0,H-MC,12.56,120.0,0.90,1.67,28.79,AR,ATH,PHARMA
64,RELAXO,1.31,-55.82,244.77,52.31,156964.0,-81033.0,64127.0,1176.00,-52.96,61.0,X-SC,19.45,92.0,-0.52,0.44,43.38,X40N,NTT,FOOTWEAR

In [24]:
# Top N allocation
df_tmp = df_portfolio_features.sort_values(by = 'CurrAlloc%', ascending=False)
top_n_values = [10, 25, 50]

sum_df = pd.DataFrame({
    'Top_N': top_n_values,
    'Sum_Alloc%': [df_tmp['CurrAlloc%'].head(n).sum() for n in top_n_values]
})

sum_df

   Top_N  Sum_Alloc%
0     10       19.53
1     25       42.79
2     50       72.81

In [25]:
# market-cap-wise allocation
df_tmp = df_portfolio_features[cols]
df_tmp.groupby(df_tmp['Conviction'].str[-2:])['CurrAlloc%'].sum().sort_values(ascending=False)

Conviction
SC    43.06
LC    31.31
MC    25.67
Name: CurrAlloc%, dtype: float64

In [26]:
# criteria-wise allocation
df_portfolio_features.groupby('Criteria')['CurrAlloc%'].sum().sort_values(ascending=False)

Criteria
XY24     27.92
X40      24.84
X40N     17.18
XR        8.84
OX40N     6.92
AR        6.87
XY25      6.58
SR        0.89
Name: CurrAlloc%, dtype: float64

In [27]:
# conviction-wise allocation
df_portfolio_features.groupby('Conviction')['CurrAlloc%'].sum().sort_values(ascending=False)

Conviction
X-LC    29.26
H-SC    22.56
X-MC    20.50
M-SC    10.01
X-SC     9.90
H-MC     2.83
M-MC     1.99
H-LC     1.21
M-LC     0.84
L-SC     0.59
L-MC     0.35
Name: CurrAlloc%, dtype: float64

In [28]:
# sector-wise stats
df_tmp = df_portfolio_features.groupby('Category')[['CurrAlloc%', 'Current', 'Current P/L', 'FTT Amt']].sum().sort_values(by=['Current', 'Current P/L'], ascending=False)
df_tmp['Current P/L%'] = round(df_tmp['Current P/L'] * 100 / df_tmp['Current'], 2)
df_tmp['FTT%'] = round(df_tmp['FTT Amt'] * 100 / df_tmp['Current'], 2)
cols = ['CurrAlloc%', 'Current P/L%', 'FTT%']
df_tmp[cols].sort_values(by=['CurrAlloc%'], ascending=False)

               CurrAlloc%  Current P/L%    FTT%
Category
FMCG                14.95        -20.64   62.95
FINANCE             10.79        -16.42   67.05
IT                   9.98        -53.63  130.44
MISC                 7.16        -27.56   82.97
AUTO                 6.85         -8.97   49.82
BANKS                5.75         -7.39   57.05
PAINTS               5.69        -17.75   38.20
INSURANCE            5.08        -10.93   48.45
PHARMA               5.07          0.34   30.52
ELECTRICAL           4.07        -18.11   59.79
CHEMICALS            2.20        -25.51  100.31
HEALTHCARE           2.06        -18.18   49.02
APPARELS             1.83          0.30   33.19
AC                   1.82        -19.47   51.87
FOOTWEAR             1.72        -74.92  145.06
TRAVEL               1.71        -77.97  167.09
DURABLES             1.55        -69.99  111.34
BREWERIES            1.48         -7.42   29.72
REALTY               1.47         -3.01   19.94
CERAMICS             1.41        -48.63   93.79
ENGINEERING          1.32        -24.96   82.12
CABLES               1.31         23.02   60.06
REFINERIES           1.11        -22.98   54.09
CEMENT               1.07        -70.25  197.62
JEWELLERY            1.02       -113.33  187.45
ENTERTAINMENT        0.72        -83.18  192.43
HOTELS               0.45        -72.72  133.64
TEXTILES             0.40        -56.60  101.26

In [29]:
# money to be made criteria-wise
df_portfolio_features.groupby('Criteria')['FTT Amt'].agg(['sum', 'count']).sort_values(by='sum', ascending=False)

                sum  count
Criteria
XY24      3496856.0     21
X40       2032112.0     19
XR        1382638.0     13
X40N      1201077.0     13
AR        1175575.0      9
OX40N      777451.0     10
XY25       469679.0      5
SR         288674.0      2

In [30]:
# money to be made conviction-wise
df_portfolio_features.groupby('Conviction')['FTT Amt'].agg(['sum', 'count']).sort_values(by='sum', ascending=False)

                  sum  count
Conviction
H-SC        3472641.0     24
X-LC        1990682.0     21
X-MC        1706175.0     15
M-SC        1448205.0     14
X-SC        1348922.0      9
H-MC         282933.0      2
L-SC         204879.0      2
M-LC         167838.0      1
M-MC          94362.0      2
H-LC          55841.0      1
L-MC          51584.0      1

In [31]:
# money to be made criteria and conviction-wise
df_portfolio_features.groupby(['Conviction', 'Criteria'])['FTT Amt'].agg(['sum', 'count']).sort_values(by='sum', ascending=False)

                           sum  count
Conviction Criteria
X-LC       X40       1074815.0     10
H-SC       XY24      1063795.0      6
           AR         964985.0      5
M-SC       XY24       835260.0      6
H-SC       XR         832404.0      7
X-SC       XY24       793651.0      4
X-MC       X40        739791.0      7
           X40N       489124.0      4
X-LC       X40N       374188.0      6
X-SC       X40N       337765.0      3
M-SC       OX40N      337645.0      5
X-LC       XY24       331605.0      2
H-SC       OX40N      322783.0      4
           SR         288674.0      2
X-MC       XY25       248357.0      2
H-MC       XY24       243642.0      1
X-MC       XY24       228903.0      2
X-SC       X40        217506.0      2
M-SC       XR         197700.0      2
M-LC       XR         167838.0      1
X-LC       XY25       164818.0      2
L-SC       OX40N      117023.0      1
           XR          87856.0      1
M-SC       AR          77600.0      1
M-MC       XY25        56504.0      1
H-LC       AR          55841.0      1
L-MC       XR          51584.0      1
X-LC       XR          45256.0      1
H-MC       AR          39291.0      1
M-MC       AR          37858.0      1

In [32]:
# notebook execution time

end_time = time.time()
execution_time = round(end_time - start_time, 0)
print(f"Notebook execution time: {execution_time} seconds")

Notebook execution time: 52.0 seconds