<a href="https://colab.research.google.com/github/ankit-rathi/Quantvesting_v2/blob/main/myStocks_Portfolio_Analysis.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
'''
!pip install pandas==2.2.2 -qq
!pip install pyxirr -qq
!pip install ta -qq
!pip install yfinance==0.2.59 -qq
'''

'\n!pip install pandas==2.2.2 -qq\n!pip install pyxirr -qq\n!pip install ta -qq\n!pip install yfinance==0.2.59 -qq\n'

In [2]:
# import libraries

import numpy as np
import pandas as pd
import datetime
import warnings
warnings.filterwarnings('ignore')
import yfinance as yfin
import ta
import matplotlib.pyplot as plt
import requests

In [3]:
# notebook start time
import time
import datetime
import pytz

start_time = time.time()

# function to print date timestamp
def print_date_time():
  tz_NY = pytz.timezone('Asia/Kolkata')
  datetime_NY = datetime.datetime.now(tz_NY)
  print("Run date time (IST):", datetime_NY.strftime("%Y-%m-%d %H:%M:%S"))

In [4]:
# function to get booked and reserved amount
def get_amt():
  # fetch the JSON data from the URL
  url = "https://raw.githubusercontent.com/ankit-rathi/Tradevesting_v1/main/data/myPortfolioAmts.json"
  response = requests.get(url)
  pf_amts = response.json()  # parse the JSON data

  # extract values from the JSON
  py_booked_amt_dm = pf_amts["py_booked_amt_dm"]
  py_booked_amt_sv = pf_amts["py_booked_amt_sv"]
  cy_booked_amt_dm = pf_amts["cy_booked_amt_dm"]
  cy_booked_amt_sv = pf_amts["cy_booked_amt_sv"]
  reserve_amt_dm = pf_amts["reserve_amt_dm"]
  reserve_amt_sv = pf_amts["reserve_amt_sv"]

  # perform calculations
  py_booked_amt = py_booked_amt_dm + py_booked_amt_sv
  cy_booked_amt = cy_booked_amt_dm + cy_booked_amt_sv
  reserve_amt = reserve_amt_dm + reserve_amt_sv
  total_booked_amt = py_booked_amt + cy_booked_amt

  return total_booked_amt, reserve_amt, cy_booked_amt, py_booked_amt

gen_output = 0

In [5]:
# function to format the amount
def format_amt(number):
    abs_number = abs(number)

    if abs_number >= 1_00_00_000:  # Crores
        formatted_amt = f"{number / 1_00_00_000:.2f} C"
    elif abs_number >= 1_00_000:  # Lakhs
        formatted_amt = f"{number / 1_00_000:.2f} L"
    elif abs_number >= 1_000:  # Thousands
        formatted_amt = f"{number / 1_000:.2f} K"
    else:
        formatted_amt = f"{number:.2f}"

    return formatted_amt

# function to set start and end date
def get_start_end_date():
  start_date = (datetime.date.today() + datetime.timedelta(days=-365)).strftime('%Y-%m-%d')
  end_date = (datetime.date.today() + datetime.timedelta(days=1)).strftime('%Y-%m-%d')
  return start_date, end_date

# function to fetch my portfolio csv
def get_mypfs_df():
  mypfs_df = pd.read_csv('https://raw.githubusercontent.com/ankit-rathi/Tradevesting_v1/main/data/myPortfolioStocks.csv')
  return mypfs_df

# function to fetch my prospects csv
def get_mypps_df():
  mypps_df = pd.read_csv('https://raw.githubusercontent.com/ankit-rathi/Tradevesting_v1/main/data/myProspectsScrips.csv')
  return mypps_df

# function to fetch screener data
def get_myscreen_df():
  myscreen_df = pd.read_csv('https://raw.githubusercontent.com/ankit-rathi/Tradevesting_v1/main/data/myScreenerDB.csv')
  return myscreen_df

# function to fetch momentum data
def get_myinvmt_df():
  myinvmt_df = pd.read_csv('https://raw.githubusercontent.com/ankit-rathi/Tradevesting_v1/main/data/myInvestments.csv')
  return myinvmt_df

# function to get the stock ids
def get_stock_ids(df_pf):
  stock_n100 = df_pf['Symbol'].unique()

  exclude = ['CADILAHC','MMTC', 'MASFIN']

  stock_ids = df_pf[~df_pf['Symbol'].isin(exclude) ]['Symbol'].unique()

  #mypf = mypf[mypf.Forecast.notnull()]
  #stock_ids = mypf['Symbol'].unique()

  #stock_ids.sort()
  return stock_ids

# get features from screener data
def get_screener_features():
  myscreen_df = get_myscreen_df()
  cols = ['Symbol', 'EPS', 'MedPE', 'ROCE%', 'ROE%', 'CapType']
  return myscreen_df[cols]

# get relative strength
def get_relative_strength(stock_list):

    # Dictionary to store stock tickers and their corresponding percentage price change
    stock_changes = {}

    # Loop through each stock and fetch its price data
    for stock in stock_list:
        try:
            # Download the stock data for the given date range
            stock_data = yfin.Ticker(stock + '.NS').history(period='1mo', interval='1d')[map(str.title, ['open', 'close', 'low', 'high', 'volume'])]

            # Calculate the percentage change for the stock
            if len(stock_data) > 0:
                start_price = stock_data['Close'].iloc[0]
                end_price = stock_data['Close'].iloc[-1]
                percent_change = round(((end_price - start_price) / start_price) * 100, 2)
                stock_changes[stock] = percent_change
            else:
                stock_changes[stock] = np.nan  # If no data is available, set to NaN

        except Exception as e:
            print(f"Error fetching data for {stock}: {e}")
            stock_changes[stock] = np.nan

    # Create a DataFrame with stock tickers and their percentage changes
    df = pd.DataFrame(list(stock_changes.items()), columns=['Symbol', 'Percent_Change'])

    # Drop any stocks with missing data (NaN values)
    df = df.dropna()

    # Calculate the percentile rank based on percentage change
    df['RSP'] = round(df['Percent_Change'].rank(pct=True) * 100, 2)
    cols = ['Symbol', 'RSP']
    df = df[cols]
    # Sort by percentile rank (optional)
    df = df.sort_values(by='RSP', ascending=False).reset_index(drop=True)

    return df

In [6]:
# function to get stock technicals
def stock_prec_dev(stock_symbol):
    #stock_symbol = 'ULTRACEMCO.NS'
    short_window = 20
    mid_window = 50
    long_window = 200
    moving_avg = 'SMA'

    start = datetime.datetime(*map(int, start_date.split('-')))
    end = datetime.datetime(*map(int, end_date.split('-')))

    stock_df = yfin.Ticker(stock_symbol + '.NS').history(period='max', interval='1d')[map(str.title, ['open', 'close', 'low', 'high', 'volume'])]

    stock_df['Max'] = round(max(stock_df['Close']),2)
    stock_df = stock_df[(stock_df.index <= end_date) & (stock_df.index >= start_date)]
    stock_df['200_SMA'] = round(stock_df['Close'].rolling(window = 200, min_periods = 1).mean(),0)
    stock_df['Dev%_200'] = round((stock_df['Close'] - stock_df['200_SMA'])*100/stock_df['200_SMA'],2)
    stock_df.dropna(axis = 0, inplace = True) # remove any null rows

    stock_df['20_SMA'] = stock_df['Close'].rolling(window=20).mean()
    stock_df['50_SMA'] = stock_df['Close'].rolling(window=50).mean()
    stock_df['Symbol'] = stock_symbol

    stock_df['Close'] = round(stock_df['Close'],2)
    stock_df['Min'] = round(min(stock_df['Close']),2)
    stock_df['RSI_14'] = ta.momentum.RSIIndicator(close=stock_df['Close'], window=14).rsi()
    stock_df['RSI_14'] = round(stock_df['RSI_14'],0)
    stock_df['Prev_Close'] = stock_df['Close'].shift(1)
    stock_df.drop(['Open', 'Low', 'High', 'Volume'], axis=1, inplace=True)
    stock_df = stock_df.tail(1)

    max_SMA = max(stock_df['20_SMA'].item(), stock_df['50_SMA'].item(), stock_df['200_SMA'].item())
    min_SMA = min(stock_df['20_SMA'].item(), stock_df['50_SMA'].item(), stock_df['200_SMA'].item())
    ABS_Spread = max_SMA - min_SMA
    stock_df['Spread%'] = round((ABS_Spread / stock_df['200_SMA'].item()) * 100,2)

    return stock_df

# function to compute stock attributes
def get_common_features(stock_ids, df_mypf):

  df_prec_dev = pd.DataFrame()
  df_tmp = get_screener_features()
  df_rs = get_relative_strength(stock_ids)

  for stock_id in stock_ids:
      tmp = stock_prec_dev(stock_id)
      tmp = tmp.reset_index()
      df_prec_dev = pd.concat([df_prec_dev, tmp], ignore_index = True)
  df_prec_dev = pd.merge(df_prec_dev, df_mypf, on= 'Symbol')
  df_prec_dev = pd.merge(df_prec_dev, df_tmp, on= 'Symbol', how='left')
  df_prec_dev = pd.merge(df_prec_dev, df_rs, on= 'Symbol', how='left')
  #print(df_prec_dev.columns)
  df_prec_dev['Curr_PE'] = round(df_prec_dev['Close']/df_prec_dev['EPS'],1)
  df_prec_dev['Dev%_PE'] = round((df_prec_dev['Curr_PE'] - df_prec_dev['MedPE'])*100/df_prec_dev['MedPE'],2)
  df_prec_dev['Conviction'] = df_prec_dev['Conviction'] + '-' + df_prec_dev['CapType']
  return df_prec_dev

# function to arrange stock features
def arrange_features(df_stocks, common_cols, diff_cols):
  df_stocks_common = df_stocks[common_cols].drop_duplicates()
  df_stocks_diff = df_stocks[diff_cols]
  df_stocks_diff['Investment'] = df_stocks_diff['AvgCost'] * df_stocks_diff['Shares']
  df_stocks_diff = df_stocks_diff.groupby(['Symbol'])[['Shares', 'Investment']].aggregate(['sum']).reset_index()
  df_stocks_diff.columns = ['Symbol', 'Shares', 'Investment']
  df_stocks_diff['AvgCost'] = round(df_stocks_diff['Investment']/df_stocks_diff['Shares'],2)
  df_stocks = pd.merge(df_stocks_diff, df_stocks_common, on='Symbol')
  return df_stocks

# plot fact distribution across dimension
def plot_pie_chart(df, dimension, fact):
  # grouping the data by category and calculating the sum of fact for each type
  grouped_data = df.groupby(dimension)[fact].sum()

  # sorting the grouped data in descending order
  grouped_data = grouped_data.sort_values(ascending=False)

  # creating a pie chart
  grouped_data.plot.pie(autopct='%1.1f%%', startangle=90, figsize=(6, 6))

  # adding a title and displaying the plot
  plt.title(f'{dimension} {fact} Distribution')
  plt.ylabel('')  # To hide the y-label
  plt.show()

In [7]:
# function to get portfolio features

def get_portfolio_features(df_common_features):

  print_date_time()
  print('-------------------')

  #df_common_features["Target"] = df_common_features["Target"].fillna(df_common_features["Max"])
  df_common_features['NTT'] = np.where(df_common_features['Strategy']== 'NTT', df_common_features["Target"], df_common_features['Max'])
  df_common_features['LTT'] = np.where(df_common_features['Strategy']== 'BTT', df_common_features["Target"], df_common_features['Max'])
  df_common_features['BOL'] = df_common_features['Min']

  tmp_df = df_common_features[df_common_features['Symbol'].isin(mypf_df[mypf_df['InPortfolio'] != 'NA'].Symbol.values)]
  print('qualified stocks: '+str(len(tmp_df['Symbol'].unique())))
  tmp_df1 = tmp_df[tmp_df['LatestQtr'] == 1]
  print('with latest results: '+str(len(tmp_df1['Symbol'].unique())))
  tmp_df1 = tmp_df1[tmp_df1['StarStock'] == 1]
  print('still star stocks: '+str(len(tmp_df1['Symbol'].unique())))
  tmp_df['Investment'] = tmp_df['AvgCost'] * tmp_df['Shares']
  tmp_df['Current'] = round(tmp_df['Close'] * tmp_df['Shares'],0)
  tmp_df['Previous'] = tmp_df['Prev_Close'] * tmp_df['Shares']
  tmp_df['EstimatedST'] = tmp_df['NTT'] * tmp_df['Shares']
  tmp_df['EstimatedLT'] = tmp_df['LTT'] * tmp_df['Shares']
  tmp_df['Current P/L'] = round((tmp_df['Current'] - tmp_df['Investment']),0)
  tmp_df['Today P/L%'] = round((tmp_df['Current'] - tmp_df['Previous'])*100/tmp_df['Previous'],2)
  tmp_df['Current P/L%'] = round((tmp_df['Current'] - tmp_df['Investment'])*100/tmp_df['Investment'],2)
  tmp_df['EstimatedST P/L%'] = round((tmp_df['EstimatedST'] - tmp_df['Investment'])*100/tmp_df['Investment'],2)
  tmp_df['EstimatedLT P/L%'] = round((tmp_df['EstimatedLT'] - tmp_df['Investment'])*100/tmp_df['Investment'],2)
  tmp_df['NTT%'] = round((tmp_df['NTT'] - tmp_df['Close'])*100/tmp_df['Close'],2)
  tmp_df['LTT%'] = round((tmp_df['LTT'] - tmp_df['Close'])*100/tmp_df['Close'],2)
  tmp_df['Gained%'] = round((tmp_df['Close'] - tmp_df['BOL'])*100/tmp_df['BOL'],2)
  investment = round(sum(tmp_df['AvgCost']*tmp_df['Shares']),0)
  current = round(sum(tmp_df['Close']*tmp_df['Shares']),0)
  tmp_df['InitAlloc%'] = round(tmp_df['Investment']*100/investment,2)
  tmp_df['CurrAlloc%'] = round(tmp_df['Current']*100/current,2)
  tmp_df['FTT'] = tmp_df['LTT']
  tmp_df.loc[tmp_df['Strategy'] == 'NTT', 'FTT'] = tmp_df['NTT']
  tmp_df['FTT%'] = tmp_df['LTT%']
  tmp_df.loc[tmp_df['Strategy'] == 'NTT', 'FTT%'] = tmp_df['NTT%']
  tmp_df['FTT Amt'] = round(tmp_df['FTT%'] * tmp_df['Current']/100,0)
  tmp_df['OTT%'] = round((tmp_df['FTT'] - tmp_df['AvgCost'])*100/tmp_df['AvgCost'],2)
  tmp_df['RRR Ind'] = round(tmp_df['Current P/L']/tmp_df['FTT Amt'],2)
  tmp_df['Risk Ind'] = round(tmp_df['Current P/L%']*tmp_df['CurrAlloc%'],0)

  return tmp_df

# function to print portfolio features
def print_portfolio_stats(df_portfolio_features, myinvmt_df):
  from pyxirr import xirr

  total_booked_amt, reserve_amt, cy_booked_amt, py_booked_amt = get_amt()

  dates = myinvmt_df['Date'].values
  dates = np.append(dates, datetime.date.today().strftime('%d-%b-%y'))
  investment = myinvmt_df['Investment'].values
  dates= pd.to_datetime(dates)

  current = round(sum(df_portfolio_features['Close']*df_portfolio_features['Shares']),0) + reserve_amt
  investment_xirr = np.append(investment, current)
  cagr = round(xirr(pd.DataFrame({"dates": dates, "amounts": investment_xirr}))*100,2)

  investment = -sum(investment)
  invested = round(sum(df_portfolio_features['AvgCost']*df_portfolio_features['Shares']),0) + reserve_amt
  previous = round(sum(df_portfolio_features['Prev_Close']*df_portfolio_features['Shares']),0) + reserve_amt
  cy_invested = investment + py_booked_amt

  today_pnl_amount = current-previous
  today_pnl_percentage = round((current-previous)*100/previous,2)

  curr_pnl_amount = current-invested
  curr_pnl_percentage = round((curr_pnl_amount)*100/(cy_invested),2)

  cy_pnl_amount = cy_booked_amt + curr_pnl_amount
  cy_pnl_percentage = round((cy_pnl_amount)*100/cy_invested,2)

  overall_pnl_amount = total_booked_amt + curr_pnl_amount
  overall_pnl_percentage = round((overall_pnl_amount)*100/investment,2)

  estimate_st = round(sum(df_portfolio_features['FTT']*df_portfolio_features['Shares']),0)  + reserve_amt
  est_st_pnl_amount = estimate_st-current
  est_st_pnl_percentage = round((est_st_pnl_amount)*100/current,2)

  estimate_lt = round(sum(df_portfolio_features['LTT']*df_portfolio_features['Shares']),0)  + reserve_amt
  est_lt_pnl_amount = estimate_lt-current
  est_lt_pnl_percentage = round((est_lt_pnl_amount)*100/current,2)

  total_profit = round(sum(df_portfolio_features[df_portfolio_features['Current P/L%'] > 0]['Current']) - sum(df_portfolio_features[df_portfolio_features['Current P/L%'] > 0]['Investment']),0)
  total_loss = round(sum(df_portfolio_features[df_portfolio_features['Current P/L%'] < 0]['Current']) - sum(df_portfolio_features[df_portfolio_features['Current P/L%'] < 0]['Investment']),0)

  cy_booked_percentage = round((cy_booked_amt)*100/current,2)
  py_booked_percentage = round((py_booked_amt)*100/investment,2)
  total_booked_percentage = round((total_booked_amt)*100/investment,2)

  print('-------------------')
  print('Initial Investment: ', format_amt(investment))
  print('CY Investment: ', format_amt(cy_invested))
  print('Reserve: ', format_amt(reserve_amt))
  print('Current: ',  format_amt(current))
  print('-------------------')
  print('Today PnL: '+ '{} ({}%)'.format(format_amt(today_pnl_amount), today_pnl_percentage))
  print('Current PnL: '+ '{} ({}%)'.format(format_amt(curr_pnl_amount), curr_pnl_percentage))
  print('CY Booked + Current PnL: '+ '{} ({}%)'.format(format_amt(cy_pnl_amount), cy_pnl_percentage))
  print('-------------------')
  print('Total profit: ', format_amt(total_profit))
  print('Total loss: ', format_amt(total_loss))
  print('-------------------')
  print('Total Booked + Current PnL: '+ '{} ({}%)'.format(format_amt(overall_pnl_amount), overall_pnl_percentage))
  print('Total Booked PnL: '+ '{} ({}%)'.format(format_amt(total_booked_amt), total_booked_percentage))
  print('Curr Year Booked PnL: '+ '{} ({}%)'.format(format_amt(cy_booked_amt), cy_booked_percentage))
  print('Prev Year Booked PnL: '+ '{} ({}%)'.format(format_amt(py_booked_amt), py_booked_percentage))
  print('===================')
  print('Est FTT: ',  format_amt(estimate_st))
  print('Est FTT PnL: '+ '{} ({}%)'.format(format_amt(est_st_pnl_amount), est_st_pnl_percentage))

  print('===================')
  print('Deployed: ', format_amt(investment))

  print('Current: ', format_amt(current))

  print('CAGR/XIRR %: '+'{}%'.format(cagr))

In [8]:
# get start and end date
start_date, end_date = get_start_end_date()

# get portfolio and prospects data
mypfs_df = get_mypfs_df()
mypps_df = get_mypps_df()
myinvmt_df = get_myinvmt_df()

# merge above datasets
mypf_df = pd.merge(mypfs_df, mypps_df, on="Symbol")

# seggregate dm and sv portfolio
dm_pf = mypf_df[mypf_df['InPortfolio'] == 'DM']
sv_pf = mypf_df[mypf_df['InPortfolio'] == 'SV']

# build portfolio stock dataframe
dm_stocks = get_stock_ids(dm_pf)
sv_stocks = get_stock_ids(sv_pf)
df_stocks = pd.concat([dm_pf,sv_pf], ignore_index = True)

# arrange common and diff stock features
common_cols = ['Symbol', 'Target', 'Criteria', 'Strategy', 'CumlRnk', 'LatestQtr', 'StarStock', 'Conviction', 'Category', 'InFolio', 'XIRR', 'MBQ']
diff_cols = ['Symbol', 'AvgCost', 'Shares']
df_stocks = arrange_features(df_stocks, common_cols, diff_cols)

# get common features
stock_ids = df_stocks['Symbol'].values
df_common_features = get_common_features(stock_ids, df_stocks)

df_common_features.reset_index(drop=True, inplace=True)
df_common_features.drop(['Date'], axis=1, inplace=True)
# get and print portfolio features
df_portfolio_features = get_portfolio_features(df_common_features)

print_portfolio_stats(df_portfolio_features, myinvmt_df)

df = df_portfolio_features
#plot_pie_chart(df, 'CapType', 'Current')
list_ox40n = list(df[df['MBQ'].str.contains('OX40N', na=False)]['Symbol'].values)

Run date time (IST): 2026-08-18 13:26:14
-------------------
qualified stocks: 87
with latest results: 30
still star stocks: 19

-------------------
Initial Investment:  1.46 C
CY Investment:  1.89 C
Reserve:  3.69 L
Current:  1.58 C
-------------------
Today PnL: -1.10 L (-0.69%)
Current PnL: -34.81 L (-18.43%)
CY Booked + Current PnL: -29.75 L (-15.75%)
-------------------
Total profit:  3.32 L
Total loss:  -38.14 L
-------------------
Total Booked + Current PnL: 13.12 L (8.98%)
Total Booked PnL: 47.93 L (32.82%)
Curr Year Booked PnL: 5.06 L (3.2%)
Prev Year Booked PnL: 42.87 L (29.35%)
===================
Est FTT:  2.67 C
Est FTT PnL: 1.09 C (68.92%)
===================
Deployed:  1.46 C
Current:  1.58 C
CAGR/XIRR %: 3.61%

In [9]:
# top 5 near their targets
cols = ['Symbol', 'Today P/L%', 'Current P/L%', 'FTT%', 'OTT%', 'FTT Amt', 'Current P/L', 'Current', 'FTT', 'Dev%_PE', 'RSI_14','Conviction', 'Spread%',  'CumlRnk', 'RRR Ind', 'CurrAlloc%', 'Gained%', 'Criteria', 'Strategy', 'Category']
df_tmp = df_portfolio_features[~df_portfolio_features['Symbol'].isin(['ENRIN','BLUSPRING','DIGITIDE'])]
df_tmp = df_tmp.sort_values(by = 'FTT Amt', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
66,SIEMENS,0.30,6.26,4.30,10.83,8503.0,11655.0,197750.0,4125.00,-13.90,63.0,H-LC,13.60,51.0,1.37,1.28,39.52,AR,NTT,ELECTRICAL
78,UNITDSPR,-0.67,12.74,7.12,20.77,18795.0,29824.0,263968.0,1644.00,-3.81,64.0,X-MC,10.50,64.0,1.59,1.71,26.89,X40N,NTT,BREWERIES
77,TTKPRESTIG,0.63,-22.55,29.23,0.09,22816.0,-22721.0,78056.0,770.00,-5.78,42.0,M-SC,10.23,250.0,-1.00,0.51,40.49,OX40N,NTT,DURABLES
52,M&M,1.02,8.15,9.86,18.82,25666.0,19627.0,260308.0,3762.88,-6.55,59.0,X-LC,4.80,25.0,0.76,1.69,18.08,X40N,ATH,AUTO
54,MASFIN,0.50,-7.23,31.04,21.57,28215.0,-7080.0,90900.0,397.04,-28.13,42.0,H-SC,0.94,167.0,-0.25,0.59,8.35,XR,ATH,FINANCE

In [10]:
# top 5 today
df_tmp = df_portfolio_features.sort_values(by = 'Today P/L%', ascending=False)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
12,BOSCH-HCIL,4.42,-24.32,32.11,-0.01,31060.0,-31076.0,96729.0,2282.00,755.80,76.0,M-SC,5.90,231.0,-1.00,0.63,64.65,OX40N,BTT,AC
18,COFFEEDAY,3.23,-49.70,168.91,35.27,96481.0,-56429.0,57120.0,80.00,NaN,41.0,NaN,3.94,266.0,-0.58,0.37,40.86,XR,NTT,HOTELS
0,5PAISA,1.75,-25.65,51.86,12.90,84246.0,-56048.0,162448.0,593.00,4.20,61.0,H-SC,11.49,170.0,-0.67,1.05,56.76,OX40N,NTT,FINANCE
38,HYUNDAI,1.12,14.54,25.66,43.94,73871.0,36553.0,287885.0,2782.73,18.51,66.0,X-LC,5.01,29.0,0.49,1.86,32.18,X40N,ATH,AUTO
82,VBL,1.04,-11.17,52.71,35.66,164742.0,-39300.0,312544.0,669.42,-27.33,40.0,X-LC,7.14,13.0,-0.24,2.02,15.07,X40N,ATH,FMCG

In [11]:
# bottom 5 today
df_tmp = df_portfolio_features.sort_values(by = 'Today P/L%', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
29,GREENPANEL,-4.89,-55.75,223.49,43.14,181045.0,-102070.0,81008.0,537.00,NaN,28.0,NaN,11.01,225.0,-0.56,0.52,0.00,XY24,NTT,MISC
33,HCLTECH,-4.41,-13.05,42.57,23.97,114556.0,-40386.0,269100.0,1853.42,-15.52,51.0,X-LC,11.78,8.0,-0.35,1.74,26.98,X40,ATH,IT
81,VALIANTORG,-3.54,-34.95,167.73,74.15,178498.0,-57185.0,106420.0,838.00,NaN,60.0,NaN,6.38,145.0,-0.32,0.69,58.37,XR,NTT,CHEMICALS
19,COLPAL,-3.22,-27.20,92.12,39.86,176612.0,-71645.0,191720.0,3683.41,-11.80,31.0,X-MC,1.50,62.0,-0.41,1.24,8.45,XY25,ATH,FMCG
72,TATAELXSI,-2.78,-47.14,149.77,32.03,104372.0,-62147.0,69688.0,9161.00,-39.97,46.0,H-SC,18.51,158.0,-0.60,0.45,8.27,OX40N,NTT,IT

In [12]:
# top 5 to exit based on CumlRnk
df_tmp = df_portfolio_features[~df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])]
df_tmp = df_tmp[(df_tmp['Current P/L%'] > -1) & (df_tmp['Current P/L%'] < 1)].sort_values(by = 'CumlRnk', ascending=False)
df_tmp[cols].head()

Empty DataFrame
Columns: [Symbol, Today P/L%, Current P/L%, FTT%, OTT%, FTT Amt, Current P/L, Current, FTT, Dev%_PE, RSI_14, Conviction, Spread%, CumlRnk, RRR Ind, CurrAlloc%, Gained%, Criteria, Strategy, Category]
Index: []

In [13]:
# OX40N stocks to exit
df_tmp = df_portfolio_features[(df_portfolio_features['Symbol'].isin(list_ox40n))].sort_values(by = 'Current P/L%', ascending=False)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
25,FINCABLES,-0.39,66.64,24.77,107.91,60941.0,98383.0,246027.0,1641.55,21.20,75.0,M-SC,18.84,220.0,1.61,1.59,85.09,OX40N,ATH,CABLES
67,SIS,-0.42,-4.76,27.32,21.26,28890.0,-5284.0,105748.0,528.00,103.25,37.0,H-SC,21.23,168.0,-0.18,0.68,57.23,OX40N,NTT,MISC
43,INDIGOPNTS,0.42,-18.06,22.06,0.02,31553.0,-31525.0,143034.0,1408.00,-21.90,67.0,M-SC,6.69,222.0,-1.00,0.93,62.28,OX40N,NTT,PAINTS
77,TTKPRESTIG,0.63,-22.55,29.23,0.09,22816.0,-22721.0,78056.0,770.00,-5.78,42.0,M-SC,10.23,250.0,-1.00,0.51,40.49,OX40N,NTT,DURABLES
12,BOSCH-HCIL,4.42,-24.32,32.11,-0.01,31060.0,-31076.0,96729.0,2282.00,755.80,76.0,M-SC,5.90,231.0,-1.00,0.63,64.65,OX40N,BTT,AC

In [14]:
# top 5 to book for rotation
df_tmp = df_portfolio_features[(df_portfolio_features['Current P/L%'] > 20) ].sort_values(by = 'CumlRnk', ascending=False)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
25,FINCABLES,-0.39,66.64,24.77,107.91,60941.0,98383.0,246027.0,1641.55,21.2,75.0,M-SC,18.84,220.0,1.61,1.59,85.09,OX40N,ATH,CABLES

In [15]:
# top 5 to monitor for exit
df_tmp = df_portfolio_features[~df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])]
df_tmp = df_tmp[(df_tmp['Current P/L%'] > 0) ].sort_values(by = 'Dev%_PE', ascending=False)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
25,FINCABLES,-0.39,66.64,24.77,107.91,60941.0,98383.0,246027.0,1641.55,21.20,75.0,M-SC,18.84,220.0,1.61,1.59,85.09,OX40N,ATH,CABLES
68,STARHEALTH,-0.03,13.19,30.10,47.26,95782.0,37090.0,318213.0,761.00,-0.12,51.0,H-SC,16.29,173.0,0.39,2.06,37.59,XY24,NTT,INSURANCE

In [16]:
# top 5 to book for rotation from weak conviction
df_tmp = df_portfolio_features[~df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])]
df_tmp = df_tmp[~df_tmp['Criteria'].isin(['XY25','XY24','X40', 'X40N'])].sort_values(by = 'RRR Ind', ascending=False)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
25,FINCABLES,-0.39,66.64,24.77,107.91,60941.0,98383.0,246027.0,1641.55,21.20,75.0,M-SC,18.84,220.0,1.61,1.59,85.09,OX40N,ATH,CABLES
3,ALKYLAMINE,-0.68,-18.91,137.45,92.54,112528.0,-19095.0,81868.0,4520.85,NaN,55.0,NaN,14.09,142.0,-0.17,0.53,55.46,SR,ATH,CHEMICALS
67,SIS,-0.42,-4.76,27.32,21.26,28890.0,-5284.0,105748.0,528.00,103.25,37.0,H-SC,21.23,168.0,-0.18,0.68,57.23,OX40N,NTT,MISC
42,INDIAMART,-2.69,-25.16,168.45,100.92,155496.0,-31026.0,92310.0,4675.60,NaN,36.0,NaN,13.45,140.0,-0.20,0.60,0.00,AR,ATH,MISC
71,TANLA,-1.74,-35.37,236.13,117.25,413230.0,-95760.0,175001.0,1922.32,NaN,46.0,NaN,15.13,147.0,-0.23,1.13,53.22,AR,ATH,IT

In [17]:
# top 5 to accumulate based on lowest RSI_14
df_tmp = df_portfolio_features[df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])].sort_values(by = 'RSI_14', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
28,GODREJCP,-0.45,-15.39,57.08,32.90,120515.0,-38404.0,211133.0,1460.97,-17.06,31.0,X-MC,5.71,32.0,-0.32,1.37,2.77,X40N,ATH,FMCG
19,COLPAL,-3.22,-27.20,92.12,39.86,176612.0,-71645.0,191720.0,3683.41,-11.80,31.0,X-MC,1.50,62.0,-0.41,1.24,8.45,XY25,ATH,FMCG
55,PAGEIND,-0.03,-4.17,39.40,33.59,101329.0,-11199.0,257180.0,51217.29,-28.69,31.0,X-MC,8.76,55.0,-0.11,1.67,22.13,X40,ATH,APPARELS
56,PGHH,-1.10,-37.55,111.40,32.01,148536.0,-80184.0,133336.0,17616.87,-54.11,31.0,X-SC,19.19,57.0,-0.54,0.86,0.00,X40,ATH,FMCG
47,ITC,-1.01,-25.43,67.22,24.70,199139.0,-101029.0,296249.0,452.00,-30.35,32.0,X-LC,10.46,1.0,-0.51,1.92,0.00,X40,NTT,FMCG

In [18]:
# top 5 to accumulate based on Spread and CumlRnk
df_tmp = df_portfolio_features[df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])]
df_tmp = df_tmp[(df_tmp['CumlRnk'] < 100)].sort_values(by = 'Spread%', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
19,COLPAL,-3.22,-27.20,92.12,39.86,176612.0,-71645.0,191720.0,3683.41,-11.80,31.0,X-MC,1.50,62.0,-0.41,1.24,8.45,XY25,ATH,FMCG
23,DMART,0.01,-2.61,34.94,31.42,106098.0,-8132.0,303658.0,5391.45,-18.33,48.0,X-LC,2.32,14.0,-0.08,1.97,9.58,X40N,ATH,FMCG
50,KOTAKBANK,-0.73,2.46,16.06,18.92,39444.0,5904.0,245606.0,452.46,-13.30,50.0,X-LC,2.40,12.0,0.15,1.59,10.50,X40,ATH,BANKS
26,GILLETTE,-0.61,-11.11,45.94,29.72,103682.0,-28206.0,225690.0,10978.86,-35.84,37.0,X-SC,3.48,83.0,-0.27,1.46,3.72,X40,ATH,FMCG
8,BAJAJHLDNG,-1.24,1.82,25.95,28.24,67641.0,4654.0,260659.0,14274.15,-8.09,58.0,X-LC,4.21,28.0,0.07,1.69,31.19,X40,ATH,FINANCE

In [19]:
# top 5 to accumulate based on lowest Gained%
df_tmp = df_portfolio_features[df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])].sort_values(by = 'Gained%', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
20,DABUR,-0.75,-21.06,82.04,43.70,160650.0,-52249.0,195819.0,735.00,-31.92,35.0,X-MC,9.88,70.0,-0.33,1.27,0.00,XY24,BTT,FMCG
47,ITC,-1.01,-25.43,67.22,24.70,199139.0,-101029.0,296249.0,452.00,-30.35,32.0,X-LC,10.46,1.0,-0.51,1.92,0.00,X40,NTT,FMCG
56,PGHH,-1.10,-37.55,111.40,32.01,148536.0,-80184.0,133336.0,17616.87,-54.11,31.0,X-SC,19.19,57.0,-0.54,0.86,0.00,X40,ATH,FMCG
34,HDFCBANK,-0.51,-11.42,47.95,31.05,124497.0,-33480.0,259640.0,1073.00,-28.50,34.0,X-LC,12.67,26.0,-0.27,1.68,0.78,X40,BTT,BANKS
35,HDFCLIFE,-0.43,-7.28,50.08,39.15,116426.0,-18257.0,232480.0,811.41,-31.77,43.0,X-LC,16.47,31.0,-0.16,1.51,0.90,X40,ATH,INSURANCE

In [20]:
# top 5 to accumulate based on lowest CurrAlloc%
df_tmp = df_portfolio_features[df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])].sort_values(by = 'CurrAlloc%', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
56,PGHH,-1.10,-37.55,111.40,32.01,148536.0,-80184.0,133336.0,17616.87,-54.11,31.0,X-SC,19.19,57.0,-0.54,0.86,0.00,X40,ATH,FMCG
2,ACC,-0.49,-41.37,198.15,74.81,311516.0,-110916.0,157212.0,3906.00,-41.79,38.0,X-SC,11.40,85.0,-0.36,1.02,5.03,XY24,BTT,CEMENT
1,ABBOTINDIA,-1.77,-10.83,29.38,15.37,46855.0,-19375.0,159480.0,34390.26,-27.37,39.0,X-MC,4.56,58.0,-0.41,1.03,8.03,X40,ATH,PHARMA
40,ICICIPRULI,-1.48,-17.00,56.95,30.28,93126.0,-33483.0,163522.0,787.27,-46.81,47.0,X-MC,12.73,78.0,-0.36,1.06,8.95,X40,ATH,INSURANCE
39,ICICIGI,-0.08,-13.92,38.12,18.89,65662.0,-27859.0,172250.0,2244.41,-14.33,41.0,X-MC,10.42,66.0,-0.42,1.12,2.62,X40,ATH,INSURANCE

In [21]:
# top 5 to accumulate based on CumlRnk
df_tmp = df_portfolio_features.sort_values(by = 'CumlRnk', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
47,ITC,-1.01,-25.43,67.22,24.70,199139.0,-101029.0,296249.0,452.00,-30.35,32.0,X-LC,10.46,1.0,-0.51,1.92,0.00,X40,NTT,FMCG
73,TCS,-1.05,-32.81,84.84,24.20,264098.0,-151983.0,311290.0,4230.71,-44.31,47.0,X-LC,14.31,2.0,-0.58,2.02,16.08,X40,ATH,IT
45,INFY,-2.01,-20.48,76.54,40.38,229127.0,-77114.0,299356.0,1972.00,-41.63,46.0,X-LC,15.92,3.0,-0.34,1.94,13.37,X40,NTT,IT
75,TMPV,-2.01,-23.02,85.44,42.75,273676.0,-95793.0,320314.0,600.00,-84.91,36.0,X-LC,4.43,4.0,-0.35,2.07,10.14,XY24,NTT,AUTO
33,HCLTECH,-4.41,-13.05,42.57,23.97,114556.0,-40386.0,269100.0,1853.42,-15.52,51.0,X-LC,11.78,8.0,-0.35,1.74,26.98,X40,ATH,IT

In [22]:
# top 5 for average up
df_tmp = df_portfolio_features[(df_portfolio_features['Dev%_200'] > 5)].sort_values(by = 'CurrAlloc%', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
44,INDUSINDBK,-0.80,-25.24,77.76,32.89,44882.0,-19488.0,57718.0,1800.00,325.21,52.0,L-MC,13.41,258.0,-0.43,0.37,42.30,XR,NTT,BANKS
60,RELAXO,-2.66,-50.05,204.90,52.31,148577.0,-72648.0,72512.0,1176.00,NaN,42.0,NaN,13.00,92.0,-0.49,0.47,62.13,X40N,NTT,FOOTWEAR
3,ALKYLAMINE,-0.68,-18.91,137.45,92.54,112528.0,-19095.0,81868.0,4520.85,NaN,55.0,NaN,14.09,142.0,-0.17,0.53,55.46,SR,ATH,CHEMICALS
12,BOSCH-HCIL,4.42,-24.32,32.11,-0.01,31060.0,-31076.0,96729.0,2282.00,755.80,76.0,M-SC,5.90,231.0,-1.00,0.63,64.65,OX40N,BTT,AC
67,SIS,-0.42,-4.76,27.32,21.26,28890.0,-5284.0,105748.0,528.00,103.25,37.0,H-SC,21.23,168.0,-0.18,0.68,57.23,OX40N,NTT,MISC

In [23]:
# top 5 RSP
df_tmp = df_portfolio_features.sort_values(by = 'RSP', ascending=False)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
25,FINCABLES,-0.39,66.64,24.77,107.91,60941.0,98383.0,246027.0,1641.55,21.20,75.0,M-SC,18.84,220.0,1.61,1.59,85.09,OX40N,ATH,CABLES
12,BOSCH-HCIL,4.42,-24.32,32.11,-0.01,31060.0,-31076.0,96729.0,2282.00,755.80,76.0,M-SC,5.90,231.0,-1.00,0.63,64.65,OX40N,BTT,AC
81,VALIANTORG,-3.54,-34.95,167.73,74.15,178498.0,-57185.0,106420.0,838.00,NaN,60.0,NaN,6.38,145.0,-0.32,0.69,58.37,XR,NTT,CHEMICALS
38,HYUNDAI,1.12,14.54,25.66,43.94,73871.0,36553.0,287885.0,2782.73,18.51,66.0,X-LC,5.01,29.0,0.49,1.86,32.18,X40N,ATH,AUTO
11,BERGEPAINT,-0.28,0.18,25.09,25.32,64785.0,461.0,258210.0,680.00,-12.92,59.0,X-MC,4.54,68.0,0.01,1.67,35.40,XY24,NTT,PAINTS

In [24]:
# Top N allocation
df_tmp = df_portfolio_features.sort_values(by = 'CurrAlloc%', ascending=False)
top_n_values = [10, 25, 50]

sum_df = pd.DataFrame({
    'Top_N': top_n_values,
    'Sum_Alloc%': [df_tmp['CurrAlloc%'].head(n).sum() for n in top_n_values]
})

sum_df

   Top_N  Sum_Alloc%
0     10       19.77
1     25       45.15
2     50       77.62

In [25]:
# market-cap-wise allocation
df_tmp = df_portfolio_features[cols]
df_tmp.groupby(df_tmp['Conviction'].str[-2:])['CurrAlloc%'].sum().sort_values(ascending=False)

Conviction
LC    38.11
MC    22.21
SC    21.64
Name: CurrAlloc%, dtype: float64

In [26]:
# criteria-wise allocation
df_portfolio_features.groupby('Criteria')['CurrAlloc%'].sum().sort_values(ascending=False)

Criteria
X40      26.60
XY24     24.00
X40N     18.67
XR        9.12
OX40N     7.35
XY25      7.27
AR        6.13
SR        0.86
Name: CurrAlloc%, dtype: float64

In [27]:
# conviction-wise allocation
df_portfolio_features.groupby('Conviction')['CurrAlloc%'].sum().sort_values(ascending=False)

Conviction
X-LC    34.41
X-MC    19.59
H-SC     8.50
X-SC     7.67
M-SC     5.47
H-LC     2.89
M-MC     1.21
H-MC     1.04
M-LC     0.81
L-MC     0.37
Name: CurrAlloc%, dtype: float64

In [28]:
# sector-wise stats
df_tmp = df_portfolio_features.groupby('Category')[['CurrAlloc%', 'Current', 'Current P/L', 'FTT Amt']].sum().sort_values(by=['Current', 'Current P/L'], ascending=False)
df_tmp['Current P/L%'] = round(df_tmp['Current P/L'] * 100 / df_tmp['Current'], 2)
df_tmp['FTT%'] = round(df_tmp['FTT Amt'] * 100 / df_tmp['Current'], 2)
cols = ['CurrAlloc%', 'Current P/L%', 'FTT%']
df_tmp[cols].sort_values(by=['CurrAlloc%'], ascending=False)

               CurrAlloc%  Current P/L%    FTT%
Category
FMCG                15.48        -24.73   69.57
IT                  11.09        -39.16  108.19
FINANCE             10.75        -16.18   66.23
AUTO                 8.31         -5.28   42.98
BANKS                6.13        -12.67   61.27
MISC                 5.95        -34.09   88.03
PHARMA               5.76          6.77   19.67
INSURANCE            5.75         -4.80   41.85
PAINTS               5.51        -15.88   35.64
ELECTRICAL           4.22         -8.44   42.40
AC                   1.85        -12.27   42.71
REFINERIES           1.75        -10.41   47.50
BREWERIES            1.71         11.30    7.12
FOOTWEAR             1.68        -70.91  139.44
APPARELS             1.67         -4.35   39.40
CABLES               1.59         39.99   24.77
DURABLES             1.49        -68.53  109.53
TRAVEL               1.43       -101.79  202.83
CERAMICS             1.33        -49.01   94.27
CHEMICALS            1.22        -40.51  154.56
ENGINEERING          1.21        -29.44   88.64
CEMENT               1.02        -70.55  198.15
JEWELLERY            0.96       -116.43  191.63
ENTERTAINMENT        0.69        -80.41  188.01
HEALTHCARE           0.69        -70.68  113.52
TEXTILES             0.39        -51.28   94.41
HOTELS               0.37        -98.79  168.91

In [29]:
# money to be made criteria-wise
df_portfolio_features.groupby('Criteria')['FTT Amt'].agg(['sum', 'count']).sort_values(by='sum', ascending=False)

                sum  count
Criteria
XY24      3619360.0     19
X40       2119209.0     18
XR        1388219.0     13
X40N      1198116.0     12
AR        1058044.0      8
OX40N      655796.0     10
XY25       577030.0      5
SR         283059.0      2

In [30]:
# money to be made conviction-wise
df_portfolio_features.groupby('Conviction')['FTT Amt'].agg(['sum', 'count']).sort_values(by='sum', ascending=False)

                  sum  count
Conviction
X-LC        2412577.0     19
X-MC        1479325.0     14
X-SC        1095249.0      6
H-SC         837727.0      8
M-SC         319954.0      6
H-MC         252318.0      1
M-LC         167341.0      1
M-MC          58364.0      1
L-MC          44882.0      1
H-LC          44532.0      2

In [31]:
# money to be made criteria and conviction-wise
df_portfolio_features.groupby(['Conviction', 'Criteria'])['FTT Amt'].agg(['sum', 'count']).sort_values(by='sum', ascending=False)

                           sum  count
Conviction Criteria
X-LC       X40       1237182.0      9
X-SC       XY24       671631.0      2
H-SC       XY24       526546.0      3
X-MC       X40        518474.0      6
           X40N       468297.0      4
X-LC       XY24       454602.0      2
           X40N       409842.0      5
X-MC       XY25       267119.0      2
H-MC       XY24       252318.0      1
X-SC       X40        252218.0      2
X-LC       XY25       251547.0      2
X-MC       XY24       225435.0      2
H-SC       OX40N      217508.0      3
X-SC       X40N       171400.0      2
M-LC       XR         167341.0      1
M-SC       OX40N      146370.0      4
           XY24       116009.0      1
H-SC       XR          93673.0      2
X-LC       XR          59404.0      1
M-MC       XY25        58364.0      1
M-SC       XR          57575.0      1
L-MC       XR          44882.0      1
H-LC       AR          44532.0      2

In [32]:
# notebook execution time

end_time = time.time()
execution_time = round(end_time - start_time, 0)
print(f"Notebook execution time: {execution_time} seconds")

Notebook execution time: 29.0 seconds