<a href="https://colab.research.google.com/github/ankit-rathi/Quantvesting_v2/blob/main/myStocks_Portfolio_Analysis.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
'''
!pip install pandas==2.2.2 -qq
!pip install pyxirr -qq
!pip install ta -qq
!pip install yfinance==0.2.59 -qq
'''

'\n!pip install pandas==2.2.2 -qq\n!pip install pyxirr -qq\n!pip install ta -qq\n!pip install yfinance==0.2.59 -qq\n'

In [2]:
# import libraries

import numpy as np
import pandas as pd
import datetime
import warnings
warnings.filterwarnings('ignore')
import yfinance as yfin
import ta
import matplotlib.pyplot as plt
import requests

In [3]:
# notebook start time
import time
import datetime
import pytz

start_time = time.time()

# function to print date timestamp
def print_date_time():
  tz_NY = pytz.timezone('Asia/Kolkata')
  datetime_NY = datetime.datetime.now(tz_NY)
  print("Run date time (IST):", datetime_NY.strftime("%Y-%m-%d %H:%M:%S"))

In [4]:
# function to get booked and reserved amount
def get_amt():
  # fetch the JSON data from the URL
  url = "https://raw.githubusercontent.com/ankit-rathi/Tradevesting_v1/main/data/myPortfolioAmts.json"
  response = requests.get(url)
  pf_amts = response.json()  # parse the JSON data

  # extract values from the JSON
  py_booked_amt_dm = pf_amts["py_booked_amt_dm"]
  py_booked_amt_sv = pf_amts["py_booked_amt_sv"]
  cy_booked_amt_dm = pf_amts["cy_booked_amt_dm"]
  cy_booked_amt_sv = pf_amts["cy_booked_amt_sv"]
  reserve_amt_dm = pf_amts["reserve_amt_dm"]
  reserve_amt_sv = pf_amts["reserve_amt_sv"]

  # perform calculations
  py_booked_amt = py_booked_amt_dm + py_booked_amt_sv
  cy_booked_amt = cy_booked_amt_dm + cy_booked_amt_sv
  reserve_amt = reserve_amt_dm + reserve_amt_sv
  total_booked_amt = py_booked_amt + cy_booked_amt

  return total_booked_amt, reserve_amt, cy_booked_amt, py_booked_amt

gen_output = 0

In [5]:
# function to format the amount
def format_amt(number):
    abs_number = abs(number)

    if abs_number >= 1_00_00_000:  # Crores
        formatted_amt = f"{number / 1_00_00_000:.2f} C"
    elif abs_number >= 1_00_000:  # Lakhs
        formatted_amt = f"{number / 1_00_000:.2f} L"
    elif abs_number >= 1_000:  # Thousands
        formatted_amt = f"{number / 1_000:.2f} K"
    else:
        formatted_amt = f"{number:.2f}"

    return formatted_amt

# function to set start and end date
def get_start_end_date():
  start_date = (datetime.date.today() + datetime.timedelta(days=-365)).strftime('%Y-%m-%d')
  end_date = (datetime.date.today() + datetime.timedelta(days=1)).strftime('%Y-%m-%d')
  return start_date, end_date

# function to fetch my portfolio csv
def get_mypfs_df():
  mypfs_df = pd.read_csv('https://raw.githubusercontent.com/ankit-rathi/Tradevesting_v1/main/data/myPortfolioStocks.csv')
  return mypfs_df

# function to fetch my prospects csv
def get_mypps_df():
  mypps_df = pd.read_csv('https://raw.githubusercontent.com/ankit-rathi/Tradevesting_v1/main/data/myProspectsScrips.csv')
  return mypps_df

# function to fetch screener data
def get_myscreen_df():
  myscreen_df = pd.read_csv('https://raw.githubusercontent.com/ankit-rathi/Tradevesting_v1/main/data/myScreenerDB.csv')
  return myscreen_df

# function to fetch momentum data
def get_myinvmt_df():
  myinvmt_df = pd.read_csv('https://raw.githubusercontent.com/ankit-rathi/Tradevesting_v1/main/data/myInvestments.csv')
  return myinvmt_df

# function to get the stock ids
def get_stock_ids(df_pf):
  stock_n100 = df_pf['Symbol'].unique()

  exclude = ['CADILAHC','MMTC', 'MASFIN']

  stock_ids = df_pf[~df_pf['Symbol'].isin(exclude) ]['Symbol'].unique()

  #mypf = mypf[mypf.Forecast.notnull()]
  #stock_ids = mypf['Symbol'].unique()

  #stock_ids.sort()
  return stock_ids

# get features from screener data
def get_screener_features():
  myscreen_df = get_myscreen_df()
  cols = ['Symbol', 'EPS', 'MedPE', 'ROCE%', 'ROE%', 'CapType']
  return myscreen_df[cols]

# get relative strength
def get_relative_strength(stock_list):

    # Dictionary to store stock tickers and their corresponding percentage price change
    stock_changes = {}

    # Loop through each stock and fetch its price data
    for stock in stock_list:
        try:
            # Download the stock data for the given date range
            stock_data = yfin.Ticker(stock + '.NS').history(period='1mo', interval='1d')[map(str.title, ['open', 'close', 'low', 'high', 'volume'])]

            # Calculate the percentage change for the stock
            if len(stock_data) > 0:
                start_price = stock_data['Close'].iloc[0]
                end_price = stock_data['Close'].iloc[-1]
                percent_change = round(((end_price - start_price) / start_price) * 100, 2)
                stock_changes[stock] = percent_change
            else:
                stock_changes[stock] = np.nan  # If no data is available, set to NaN

        except Exception as e:
            print(f"Error fetching data for {stock}: {e}")
            stock_changes[stock] = np.nan

    # Create a DataFrame with stock tickers and their percentage changes
    df = pd.DataFrame(list(stock_changes.items()), columns=['Symbol', 'Percent_Change'])

    # Drop any stocks with missing data (NaN values)
    df = df.dropna()

    # Calculate the percentile rank based on percentage change
    df['RSP'] = round(df['Percent_Change'].rank(pct=True) * 100, 2)
    cols = ['Symbol', 'RSP']
    df = df[cols]
    # Sort by percentile rank (optional)
    df = df.sort_values(by='RSP', ascending=False).reset_index(drop=True)

    return df

In [6]:
# function to get stock technicals
def stock_prec_dev(stock_symbol):
    #stock_symbol = 'ULTRACEMCO.NS'
    short_window = 20
    mid_window = 50
    long_window = 200
    moving_avg = 'SMA'

    start = datetime.datetime(*map(int, start_date.split('-')))
    end = datetime.datetime(*map(int, end_date.split('-')))

    stock_df = yfin.Ticker(stock_symbol + '.NS').history(period='max', interval='1d')[map(str.title, ['open', 'close', 'low', 'high', 'volume'])]

    stock_df['Max'] = round(max(stock_df['Close']),2)
    stock_df = stock_df[(stock_df.index <= end_date) & (stock_df.index >= start_date)]
    stock_df['200_SMA'] = round(stock_df['Close'].rolling(window = 200, min_periods = 1).mean(),0)
    stock_df['Dev%_200'] = round((stock_df['Close'] - stock_df['200_SMA'])*100/stock_df['200_SMA'],2)
    stock_df.dropna(axis = 0, inplace = True) # remove any null rows

    stock_df['20_SMA'] = stock_df['Close'].rolling(window=20).mean()
    stock_df['50_SMA'] = stock_df['Close'].rolling(window=50).mean()
    stock_df['Symbol'] = stock_symbol

    stock_df['Close'] = round(stock_df['Close'],2)
    stock_df['Min'] = round(min(stock_df['Close']),2)
    stock_df['RSI_14'] = ta.momentum.RSIIndicator(close=stock_df['Close'], window=14).rsi()
    stock_df['RSI_14'] = round(stock_df['RSI_14'],0)
    stock_df['Prev_Close'] = stock_df['Close'].shift(1)
    stock_df.drop(['Open', 'Low', 'High', 'Volume'], axis=1, inplace=True)
    stock_df = stock_df.tail(1)

    max_SMA = max(stock_df['20_SMA'].item(), stock_df['50_SMA'].item(), stock_df['200_SMA'].item())
    min_SMA = min(stock_df['20_SMA'].item(), stock_df['50_SMA'].item(), stock_df['200_SMA'].item())
    ABS_Spread = max_SMA - min_SMA
    stock_df['Spread%'] = round((ABS_Spread / stock_df['200_SMA'].item()) * 100,2)

    return stock_df

# function to compute stock attributes
def get_common_features(stock_ids, df_mypf):

  df_prec_dev = pd.DataFrame()
  df_tmp = get_screener_features()
  df_rs = get_relative_strength(stock_ids)

  for stock_id in stock_ids:
      tmp = stock_prec_dev(stock_id)
      tmp = tmp.reset_index()
      df_prec_dev = pd.concat([df_prec_dev, tmp], ignore_index = True)
  df_prec_dev = pd.merge(df_prec_dev, df_mypf, on= 'Symbol')
  df_prec_dev = pd.merge(df_prec_dev, df_tmp, on= 'Symbol', how='left')
  df_prec_dev = pd.merge(df_prec_dev, df_rs, on= 'Symbol', how='left')
  #print(df_prec_dev.columns)
  df_prec_dev['Curr_PE'] = round(df_prec_dev['Close']/df_prec_dev['EPS'],1)
  df_prec_dev['Dev%_PE'] = round((df_prec_dev['Curr_PE'] - df_prec_dev['MedPE'])*100/df_prec_dev['MedPE'],2)
  df_prec_dev['Conviction'] = df_prec_dev['Conviction'] + '-' + df_prec_dev['CapType']
  return df_prec_dev

# function to arrange stock features
def arrange_features(df_stocks, common_cols, diff_cols):
  df_stocks_common = df_stocks[common_cols].drop_duplicates()
  df_stocks_diff = df_stocks[diff_cols]
  df_stocks_diff['Investment'] = df_stocks_diff['AvgCost'] * df_stocks_diff['Shares']
  df_stocks_diff = df_stocks_diff.groupby(['Symbol'])[['Shares', 'Investment']].aggregate(['sum']).reset_index()
  df_stocks_diff.columns = ['Symbol', 'Shares', 'Investment']
  df_stocks_diff['AvgCost'] = round(df_stocks_diff['Investment']/df_stocks_diff['Shares'],2)
  df_stocks = pd.merge(df_stocks_diff, df_stocks_common, on='Symbol')
  return df_stocks

# plot fact distribution across dimension
def plot_pie_chart(df, dimension, fact):
  # grouping the data by category and calculating the sum of fact for each type
  grouped_data = df.groupby(dimension)[fact].sum()

  # sorting the grouped data in descending order
  grouped_data = grouped_data.sort_values(ascending=False)

  # creating a pie chart
  grouped_data.plot.pie(autopct='%1.1f%%', startangle=90, figsize=(6, 6))

  # adding a title and displaying the plot
  plt.title(f'{dimension} {fact} Distribution')
  plt.ylabel('')  # To hide the y-label
  plt.show()

In [7]:
# function to get portfolio features

def get_portfolio_features(df_common_features):

  print_date_time()
  print('-------------------')

  #df_common_features["Target"] = df_common_features["Target"].fillna(df_common_features["Max"])
  df_common_features['NTT'] = np.where(df_common_features['Strategy']== 'NTT', df_common_features["Target"], df_common_features['Max'])
  df_common_features['LTT'] = np.where(df_common_features['Strategy']== 'BTT', df_common_features["Target"], df_common_features['Max'])
  df_common_features['BOL'] = df_common_features['Min']

  tmp_df = df_common_features[df_common_features['Symbol'].isin(mypf_df[mypf_df['InPortfolio'] != 'NA'].Symbol.values)]
  print('qualified stocks: '+str(len(tmp_df['Symbol'].unique())))
  tmp_df1 = tmp_df[tmp_df['LatestQtr'] == 1]
  print('with latest results: '+str(len(tmp_df1['Symbol'].unique())))
  tmp_df1 = tmp_df1[tmp_df1['StarStock'] == 1]
  print('still star stocks: '+str(len(tmp_df1['Symbol'].unique())))
  tmp_df['Investment'] = tmp_df['AvgCost'] * tmp_df['Shares']
  tmp_df['Current'] = round(tmp_df['Close'] * tmp_df['Shares'],0)
  tmp_df['Previous'] = tmp_df['Prev_Close'] * tmp_df['Shares']
  tmp_df['EstimatedST'] = tmp_df['NTT'] * tmp_df['Shares']
  tmp_df['EstimatedLT'] = tmp_df['LTT'] * tmp_df['Shares']
  tmp_df['Current P/L'] = round((tmp_df['Current'] - tmp_df['Investment']),0)
  tmp_df['Today P/L%'] = round((tmp_df['Current'] - tmp_df['Previous'])*100/tmp_df['Previous'],2)
  tmp_df['Current P/L%'] = round((tmp_df['Current'] - tmp_df['Investment'])*100/tmp_df['Investment'],2)
  tmp_df['EstimatedST P/L%'] = round((tmp_df['EstimatedST'] - tmp_df['Investment'])*100/tmp_df['Investment'],2)
  tmp_df['EstimatedLT P/L%'] = round((tmp_df['EstimatedLT'] - tmp_df['Investment'])*100/tmp_df['Investment'],2)
  tmp_df['NTT%'] = round((tmp_df['NTT'] - tmp_df['Close'])*100/tmp_df['Close'],2)
  tmp_df['LTT%'] = round((tmp_df['LTT'] - tmp_df['Close'])*100/tmp_df['Close'],2)
  tmp_df['Gained%'] = round((tmp_df['Close'] - tmp_df['BOL'])*100/tmp_df['BOL'],2)
  investment = round(sum(tmp_df['AvgCost']*tmp_df['Shares']),0)
  current = round(sum(tmp_df['Close']*tmp_df['Shares']),0)
  tmp_df['InitAlloc%'] = round(tmp_df['Investment']*100/investment,2)
  tmp_df['CurrAlloc%'] = round(tmp_df['Current']*100/current,2)
  tmp_df['FTT'] = tmp_df['LTT']
  tmp_df.loc[tmp_df['Strategy'] == 'NTT', 'FTT'] = tmp_df['NTT']
  tmp_df['FTT%'] = tmp_df['LTT%']
  tmp_df.loc[tmp_df['Strategy'] == 'NTT', 'FTT%'] = tmp_df['NTT%']
  tmp_df['FTT Amt'] = round(tmp_df['FTT%'] * tmp_df['Current']/100,0)
  tmp_df['OTT%'] = round((tmp_df['FTT'] - tmp_df['AvgCost'])*100/tmp_df['AvgCost'],2)
  tmp_df['RRR Ind'] = round(tmp_df['Current P/L']/tmp_df['FTT Amt'],2)
  tmp_df['Risk Ind'] = round(tmp_df['Current P/L%']*tmp_df['CurrAlloc%'],0)

  return tmp_df

# function to print portfolio features
def print_portfolio_stats(df_portfolio_features, myinvmt_df):
  from pyxirr import xirr

  total_booked_amt, reserve_amt, cy_booked_amt, py_booked_amt = get_amt()

  dates = myinvmt_df['Date'].values
  dates = np.append(dates, datetime.date.today().strftime('%d-%b-%y'))
  investment = myinvmt_df['Investment'].values
  dates= pd.to_datetime(dates)

  current = round(sum(df_portfolio_features['Close']*df_portfolio_features['Shares']),0) + reserve_amt
  investment_xirr = np.append(investment, current)
  cagr = round(xirr(pd.DataFrame({"dates": dates, "amounts": investment_xirr}))*100,2)

  investment = -sum(investment)
  invested = round(sum(df_portfolio_features['AvgCost']*df_portfolio_features['Shares']),0) + reserve_amt
  previous = round(sum(df_portfolio_features['Prev_Close']*df_portfolio_features['Shares']),0) + reserve_amt
  cy_invested = investment + py_booked_amt

  today_pnl_amount = current-previous
  today_pnl_percentage = round((current-previous)*100/previous,2)

  curr_pnl_amount = current-invested
  curr_pnl_percentage = round((curr_pnl_amount)*100/(cy_invested),2)

  cy_pnl_amount = cy_booked_amt + curr_pnl_amount
  cy_pnl_percentage = round((cy_pnl_amount)*100/cy_invested,2)

  overall_pnl_amount = total_booked_amt + curr_pnl_amount
  overall_pnl_percentage = round((overall_pnl_amount)*100/investment,2)

  estimate_st = round(sum(df_portfolio_features['FTT']*df_portfolio_features['Shares']),0)  + reserve_amt
  est_st_pnl_amount = estimate_st-current
  est_st_pnl_percentage = round((est_st_pnl_amount)*100/current,2)

  estimate_lt = round(sum(df_portfolio_features['LTT']*df_portfolio_features['Shares']),0)  + reserve_amt
  est_lt_pnl_amount = estimate_lt-current
  est_lt_pnl_percentage = round((est_lt_pnl_amount)*100/current,2)

  total_profit = round(sum(df_portfolio_features[df_portfolio_features['Current P/L%'] > 0]['Current']) - sum(df_portfolio_features[df_portfolio_features['Current P/L%'] > 0]['Investment']),0)
  total_loss = round(sum(df_portfolio_features[df_portfolio_features['Current P/L%'] < 0]['Current']) - sum(df_portfolio_features[df_portfolio_features['Current P/L%'] < 0]['Investment']),0)

  cy_booked_percentage = round((cy_booked_amt)*100/current,2)
  py_booked_percentage = round((py_booked_amt)*100/investment,2)
  total_booked_percentage = round((total_booked_amt)*100/investment,2)

  print('-------------------')
  print('Initial Investment: ', format_amt(investment))
  print('CY Investment: ', format_amt(cy_invested))
  print('Reserve: ', format_amt(reserve_amt))
  print('Current: ',  format_amt(current))
  print('-------------------')
  print('Today PnL: '+ '{} ({}%)'.format(format_amt(today_pnl_amount), today_pnl_percentage))
  print('Current PnL: '+ '{} ({}%)'.format(format_amt(curr_pnl_amount), curr_pnl_percentage))
  print('CY Booked + Current PnL: '+ '{} ({}%)'.format(format_amt(cy_pnl_amount), cy_pnl_percentage))
  print('-------------------')
  print('Total profit: ', format_amt(total_profit))
  print('Total loss: ', format_amt(total_loss))
  print('-------------------')
  print('Total Booked + Current PnL: '+ '{} ({}%)'.format(format_amt(overall_pnl_amount), overall_pnl_percentage))
  print('Total Booked PnL: '+ '{} ({}%)'.format(format_amt(total_booked_amt), total_booked_percentage))
  print('Curr Year Booked PnL: '+ '{} ({}%)'.format(format_amt(cy_booked_amt), cy_booked_percentage))
  print('Prev Year Booked PnL: '+ '{} ({}%)'.format(format_amt(py_booked_amt), py_booked_percentage))
  print('===================')
  print('Est FTT: ',  format_amt(estimate_st))
  print('Est FTT PnL: '+ '{} ({}%)'.format(format_amt(est_st_pnl_amount), est_st_pnl_percentage))

  print('===================')
  print('Deployed: ', format_amt(investment))

  print('Current: ', format_amt(current))

  print('CAGR/XIRR %: '+'{}%'.format(cagr))

In [8]:
# get start and end date
start_date, end_date = get_start_end_date()

# get portfolio and prospects data
mypfs_df = get_mypfs_df()
mypps_df = get_mypps_df()
myinvmt_df = get_myinvmt_df()

# merge above datasets
mypf_df = pd.merge(mypfs_df, mypps_df, on="Symbol")

# seggregate dm and sv portfolio
dm_pf = mypf_df[mypf_df['InPortfolio'] == 'DM']
sv_pf = mypf_df[mypf_df['InPortfolio'] == 'SV']

# build portfolio stock dataframe
dm_stocks = get_stock_ids(dm_pf)
sv_stocks = get_stock_ids(sv_pf)
df_stocks = pd.concat([dm_pf,sv_pf], ignore_index = True)

# arrange common and diff stock features
common_cols = ['Symbol', 'Target', 'Criteria', 'Strategy', 'CumlRnk', 'LatestQtr', 'StarStock', 'Conviction', 'Category', 'InFolio', 'XIRR', 'MBQ']
diff_cols = ['Symbol', 'AvgCost', 'Shares']
df_stocks = arrange_features(df_stocks, common_cols, diff_cols)

# get common features
stock_ids = df_stocks['Symbol'].values
df_common_features = get_common_features(stock_ids, df_stocks)

df_common_features.reset_index(drop=True, inplace=True)
df_common_features.drop(['Date'], axis=1, inplace=True)
# get and print portfolio features
df_portfolio_features = get_portfolio_features(df_common_features)

print_portfolio_stats(df_portfolio_features, myinvmt_df)

df = df_portfolio_features
#plot_pie_chart(df, 'CapType', 'Current')
list_ox40n = list(df[df['MBQ'].str.contains('OX40N', na=False)]['Symbol'].values)

Run date time (IST): 2026-06-23 15:33:08
-------------------
qualified stocks: 92
with latest results: 31
still star stocks: 20

-------------------
Initial Investment:  1.40 C
CY Investment:  1.82 C
Reserve:  1.49 K
Current:  1.51 C
-------------------
Today PnL: -1.28 L (-0.84%)
Current PnL: -31.69 L (-17.38%)
CY Booked + Current PnL: -29.61 L (-16.24%)
-------------------
Total profit:  3.81 L
Total loss:  -35.51 L
-------------------
Total Booked + Current PnL: 13.26 L (9.5%)
Total Booked PnL: 44.95 L (32.22%)
Curr Year Booked PnL: 2.08 L (1.37%)
Prev Year Booked PnL: 42.87 L (30.73%)
===================
Est FTT:  2.55 C
Est FTT PnL: 1.04 C (68.38%)
===================
Deployed:  1.40 C
Current:  1.51 C
CAGR/XIRR %: 3.83%

In [9]:
# top 5 near their targets
cols = ['Symbol', 'Today P/L%', 'Current P/L%', 'FTT%', 'OTT%', 'FTT Amt', 'Current P/L', 'Current', 'FTT', 'Dev%_PE', 'RSI_14','Conviction', 'Spread%',  'CumlRnk', 'RRR Ind', 'CurrAlloc%', 'Gained%', 'Criteria', 'Strategy', 'Category']
df_tmp = df_portfolio_features[~df_portfolio_features['Symbol'].isin(['ENRIN','BLUSPRING','DIGITIDE'])]
df_tmp = df_tmp.sort_values(by = 'FTT Amt', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
59,PIDILITIND,-0.35,11.03,6.61,18.37,10356.0,15560.0,156670.0,1670.26,-22.28,69.0,X-LC,3.81,5.0,1.50,1.03,23.01,X40,ATH,CHEMICALS
51,KOTAKBANK,-0.12,7.32,12.84,21.11,19082.0,10138.0,148610.0,453.24,-8.11,61.0,X-LC,5.21,12.0,0.53,0.98,13.65,X40,ATH,BANKS
49,JSWINFRA,2.57,7.22,8.59,16.43,20426.0,16013.0,237787.0,342.00,-7.97,73.0,X-MC,2.76,61.0,0.78,1.57,34.82,X40N,NTT,REALTY
72,SIS,-0.89,-1.44,23.03,21.26,25202.0,-1599.0,109433.0,528.00,2611.92,62.0,H-SC,23.66,168.0,-0.06,0.72,62.71,OX40N,NTT,MISC
55,MASFIN,-2.17,-4.87,27.79,21.57,25903.0,-4770.0,93210.0,397.04,-17.80,49.0,H-SC,3.08,167.0,-0.18,0.62,11.10,XR,ATH,FINANCE

In [10]:
# top 5 today
df_tmp = df_portfolio_features.sort_values(by = 'Today P/L%', ascending=False)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
61,RAJESHEXPO,4.99,-79.23,381.91,0.07,108787.0,-108692.0,28485.0,518.00,944.19,57.0,L-SC,35.99,268.0,-1.00,0.19,40.68,OX40N,NTT,JEWELLERY
49,JSWINFRA,2.57,7.22,8.59,16.43,20426.0,16013.0,237787.0,342.00,-7.97,73.0,X-MC,2.76,61.0,0.78,1.57,34.82,X40N,NTT,REALTY
91,ZYDUSLIFE,2.46,17.28,15.64,35.63,38442.0,36222.0,245796.0,1286.17,2.25,66.0,H-MC,13.71,120.0,0.94,1.62,29.24,AR,ATH,PHARMA
64,RELAXO,2.29,-52.81,222.72,52.31,152579.0,-76653.0,68507.0,1176.00,-49.76,65.0,X-SC,15.49,92.0,-0.50,0.45,53.17,X40N,NTT,FOOTWEAR
60,QUESS,2.10,2.97,68.89,73.90,75751.0,3167.0,109960.0,424.00,-44.35,74.0,X-SC,9.80,80.0,0.04,0.73,49.90,XY24,NTT,MISC

In [11]:
# bottom 5 today
df_tmp = df_portfolio_features.sort_values(by = 'Today P/L%', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
21,DEN,-4.21,-40.16,137.42,42.07,69458.0,-33920.0,50544.0,75.00,78.76,66.0,M-SC,6.87,235.0,-0.49,0.33,37.47,AR,NTT,ENTERTAINMENT
31,HATHWAY,-3.77,-35.21,167.46,73.29,117959.0,-38280.0,70440.0,31.40,718.84,61.0,H-SC,9.05,171.0,-0.32,0.47,32.36,XR,NTT,ENTERTAINMENT
16,CERA,-3.48,-15.93,47.36,23.89,70041.0,-28013.0,147890.0,9475.00,-18.85,66.0,H-SC,7.50,153.0,-0.40,0.98,42.12,OX40N,NTT,CERAMICS
45,INFY,-3.39,-29.93,91.59,34.24,200803.0,-93647.0,219241.0,1972.00,-44.85,32.0,X-LC,17.24,3.0,-0.47,1.45,0.00,X40,NTT,IT
22,DIXON,-3.27,-13.07,58.66,37.92,132987.0,-34090.0,226708.0,18931.72,-63.03,53.0,X-MC,11.63,54.0,-0.26,1.50,23.35,X40N,ATH,IT

In [12]:
# top 5 to exit based on CumlRnk
df_tmp = df_portfolio_features[~df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])]
df_tmp = df_tmp[(df_tmp['Current P/L%'] > -1) & (df_tmp['Current P/L%'] < 1)].sort_values(by = 'CumlRnk', ascending=False)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
9,BANDHANBNK,-0.58,-0.37,93.12,92.42,258446.0,-1018.0,277541.0,400.0,137.79,54.0,H-SC,23.2,174.0,-0.0,1.83,52.89,XY24,NTT,BANKS

In [13]:
# OX40N stocks to exit
df_tmp = df_portfolio_features[(df_portfolio_features['Symbol'].isin(list_ox40n))].sort_values(by = 'Current P/L%', ascending=False)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
25,FINCABLES,-2.80,46.57,41.86,107.91,90583.0,68752.0,216396.0,1641.55,31.91,61.0,M-SC,25.23,220.0,0.76,1.43,62.80,OX40N,ATH,CABLES
72,SIS,-0.89,-1.44,23.03,21.26,25202.0,-1599.0,109433.0,528.00,2611.92,62.0,H-SC,23.66,168.0,-0.06,0.72,62.71,OX40N,NTT,MISC
16,CERA,-3.48,-15.93,47.36,23.89,70041.0,-28013.0,147890.0,9475.00,-18.85,66.0,H-SC,7.50,153.0,-0.40,0.98,42.12,OX40N,NTT,CERAMICS
69,SFL,-0.73,-27.55,74.79,26.63,142075.0,-72253.0,189965.0,1287.00,43.89,73.0,M-SC,10.87,242.0,-0.51,1.25,58.33,XY24,NTT,MISC
83,TTKPRESTIG,-1.52,-27.81,38.65,0.09,28118.0,-28026.0,72751.0,770.00,68.84,58.0,M-SC,9.33,250.0,-1.00,0.48,29.54,OX40N,NTT,DURABLES

In [14]:
# top 5 to book for rotation
df_tmp = df_portfolio_features[(df_portfolio_features['Current P/L%'] > 20) ].sort_values(by = 'CumlRnk', ascending=False)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
25,FINCABLES,-2.80,46.57,41.86,107.91,90583.0,68752.0,216396.0,1641.55,31.91,61.0,M-SC,25.23,220.0,0.76,1.43,62.80,OX40N,ATH,CABLES
68,SATIN,-1.49,28.89,17.80,51.83,63388.0,79827.0,356111.0,274.00,15.64,56.0,H-SC,41.05,159.0,1.26,2.35,73.48,XY24,NTT,FINANCE

In [15]:
# top 5 to monitor for exit
df_tmp = df_portfolio_features[~df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])]
df_tmp = df_tmp[(df_tmp['Current P/L%'] > 0) ].sort_values(by = 'Dev%_PE', ascending=False)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
74,STARHEALTH,0.29,12.93,30.40,47.26,96513.0,36355.0,317478.0,761.00,78.26,78.0,H-SC,11.73,173.0,0.38,2.10,39.38,XY24,NTT,INSURANCE
25,FINCABLES,-2.80,46.57,41.86,107.91,90583.0,68752.0,216396.0,1641.55,31.91,61.0,M-SC,25.23,220.0,0.76,1.43,62.80,OX40N,ATH,CABLES
68,SATIN,-1.49,28.89,17.80,51.83,63388.0,79827.0,356111.0,274.00,15.64,56.0,H-SC,41.05,159.0,1.26,2.35,73.48,XY24,NTT,FINANCE
91,ZYDUSLIFE,2.46,17.28,15.64,35.63,38442.0,36222.0,245796.0,1286.17,2.25,66.0,H-MC,13.71,120.0,0.94,1.62,29.24,AR,ATH,PHARMA
73,SONACOMS,-0.81,6.56,30.53,39.09,32909.0,6632.0,107791.0,804.02,-15.61,59.0,M-MC,18.36,193.0,0.20,0.71,52.49,AR,ATH,AUTO

In [16]:
# top 5 to book for rotation from weak conviction
df_tmp = df_portfolio_features[~df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])]
df_tmp = df_tmp[~df_tmp['Criteria'].isin(['XY25','XY24','X40', 'X40N'])].sort_values(by = 'RRR Ind', ascending=False)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
91,ZYDUSLIFE,2.46,17.28,15.64,35.63,38442.0,36222.0,245796.0,1286.17,2.25,66.0,H-MC,13.71,120.0,0.94,1.62,29.24,AR,ATH,PHARMA
25,FINCABLES,-2.80,46.57,41.86,107.91,90583.0,68752.0,216396.0,1641.55,31.91,61.0,M-SC,25.23,220.0,0.76,1.43,62.80,OX40N,ATH,CABLES
73,SONACOMS,-0.81,6.56,30.53,39.09,32909.0,6632.0,107791.0,804.02,-15.61,59.0,M-MC,18.36,193.0,0.20,0.71,52.49,AR,ATH,AUTO
72,SIS,-0.89,-1.44,23.03,21.26,25202.0,-1599.0,109433.0,528.00,2611.92,62.0,H-SC,23.66,168.0,-0.06,0.72,62.71,OX40N,NTT,MISC
75,SURYODAY,-1.92,-2.14,25.72,23.03,45073.0,-3825.0,175246.0,216.00,90.79,56.0,H-SC,18.93,166.0,-0.08,1.16,47.55,XR,NTT,BANKS

In [17]:
# top 5 to accumulate based on lowest RSI_14
df_tmp = df_portfolio_features[df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])].sort_values(by = 'RSI_14', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
45,INFY,-3.39,-29.93,91.59,34.24,200803.0,-93647.0,219241.0,1972.00,-44.85,32.0,X-LC,17.24,3.0,-0.47,1.45,0.00,X40,NTT,IT
79,TCS,-3.21,-39.54,106.54,24.88,298425.0,-183167.0,280106.0,4253.91,-48.87,32.0,X-LC,19.60,2.0,-0.61,1.85,0.00,X40,ATH,IT
33,HCLTECH,-1.86,-28.00,68.76,21.51,119774.0,-67732.0,174192.0,1872.35,-24.32,37.0,X-LC,18.49,8.0,-0.57,1.15,0.00,X40,ATH,IT
1,ABBOTINDIA,-1.90,-14.22,37.64,18.07,57747.0,-25435.0,153420.0,35195.00,-27.11,38.0,X-MC,5.72,58.0,-0.44,1.01,1.55,X40,ATH,PHARMA
20,DABUR,-0.58,-17.92,75.08,43.70,152865.0,-44465.0,203603.0,735.00,-25.56,39.0,X-MC,11.74,70.0,-0.29,1.34,2.28,XY24,BTT,FMCG

In [18]:
# top 5 to accumulate based on Spread and CumlRnk
df_tmp = df_portfolio_features[df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])]
df_tmp = df_tmp[(df_tmp['CumlRnk'] < 100)].sort_values(by = 'Spread%', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
49,JSWINFRA,2.57,7.22,8.59,16.43,20426.0,16013.0,237787.0,342.00,-7.97,73.0,X-MC,2.76,61.0,0.78,1.57,34.82,X40N,NTT,REALTY
11,BERGEPAINT,-0.69,0.67,24.49,25.32,63544.0,1720.0,259469.0,680.00,-4.85,65.0,X-MC,3.05,68.0,0.03,1.71,35.04,XY24,NTT,PAINTS
56,MEDANTA,1.14,11.45,14.06,27.12,27659.0,20206.0,196723.0,1486.00,7.96,69.0,X-SC,3.08,87.0,0.73,1.30,35.55,XY24,NTT,HEALTHCARE
59,PIDILITIND,-0.35,11.03,6.61,18.37,10356.0,15560.0,156670.0,1670.26,-22.28,69.0,X-LC,3.81,5.0,1.50,1.03,23.01,X40,ATH,CHEMICALS
19,COLPAL,-0.08,-24.80,85.98,39.86,170283.0,-65315.0,198050.0,3683.41,-8.99,40.0,X-MC,3.88,62.0,-0.38,1.31,12.03,XY25,ATH,FMCG

In [19]:
# top 5 to accumulate based on lowest Gained%
df_tmp = df_portfolio_features[df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])].sort_values(by = 'Gained%', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
45,INFY,-3.39,-29.93,91.59,34.24,200803.0,-93647.0,219241.0,1972.00,-44.85,32.0,X-LC,17.24,3.0,-0.47,1.45,0.00,X40,NTT,IT
33,HCLTECH,-1.86,-28.00,68.76,21.51,119774.0,-67732.0,174192.0,1872.35,-24.32,37.0,X-LC,18.49,8.0,-0.57,1.15,0.00,X40,ATH,IT
79,TCS,-3.21,-39.54,106.54,24.88,298425.0,-183167.0,280106.0,4253.91,-48.87,32.0,X-LC,19.60,2.0,-0.61,1.85,0.00,X40,ATH,IT
58,PGHH,-0.63,-31.82,93.61,32.01,136281.0,-67936.0,145584.0,17616.87,-53.84,40.0,X-MC,19.98,57.0,-0.50,0.96,1.19,X40,ATH,FMCG
1,ABBOTINDIA,-1.90,-14.22,37.64,18.07,57747.0,-25435.0,153420.0,35195.00,-27.11,38.0,X-MC,5.72,58.0,-0.44,1.01,1.55,X40,ATH,PHARMA

In [20]:
# top 5 to accumulate based on lowest CurrAlloc%
df_tmp = df_portfolio_features[df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])].sort_values(by = 'CurrAlloc%', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
10,BATAINDIA,0.37,-52.67,185.68,35.20,113074.0,-67773.0,60897.0,2096.00,-20.14,59.0,X-SC,23.27,91.0,-0.60,0.40,20.77,X40,NTT,FOOTWEAR
64,RELAXO,2.29,-52.81,222.72,52.31,152579.0,-76653.0,68507.0,1176.00,-49.76,65.0,X-SC,15.49,92.0,-0.50,0.45,53.17,X40N,NTT,FOOTWEAR
60,QUESS,2.10,2.97,68.89,73.90,75751.0,3167.0,109960.0,424.00,-44.35,74.0,X-SC,9.80,80.0,0.04,0.73,49.90,XY24,NTT,MISC
28,GODREJCP,0.12,-8.65,43.92,31.47,59623.0,-12861.0,135753.0,1469.04,-3.99,49.0,X-LC,9.33,32.0,-0.22,0.90,4.16,X40N,ATH,FMCG
53,M&M,-0.85,-1.44,25.19,23.38,34429.0,-2003.0,136678.0,3802.40,-16.52,46.0,X-LC,10.59,25.0,-0.06,0.90,3.62,X40N,ATH,AUTO

In [21]:
# top 5 to accumulate based on CumlRnk
df_tmp = df_portfolio_features.sort_values(by = 'CumlRnk', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
47,ITC,-0.43,-23.61,55.86,19.06,145147.0,-80326.0,259840.0,452.00,-57.95,51.0,X-LC,14.92,1.0,-0.55,1.72,4.69,X40,NTT,FMCG
79,TCS,-3.21,-39.54,106.54,24.88,298425.0,-183167.0,280106.0,4253.91,-48.87,32.0,X-LC,19.60,2.0,-0.61,1.85,0.00,X40,ATH,IT
45,INFY,-3.39,-29.93,91.59,34.24,200803.0,-93647.0,219241.0,1972.00,-44.85,32.0,X-LC,17.24,3.0,-0.47,1.45,0.00,X40,NTT,IT
81,TMPV,-1.92,-19.29,69.23,36.58,198819.0,-68655.0,287186.0,600.00,-83.62,41.0,X-LC,10.54,4.0,-0.35,1.90,20.69,XY24,NTT,AUTO
59,PIDILITIND,-0.35,11.03,6.61,18.37,10356.0,15560.0,156670.0,1670.26,-22.28,69.0,X-LC,3.81,5.0,1.50,1.03,23.01,X40,ATH,CHEMICALS

In [22]:
# top 5 for average up
df_tmp = df_portfolio_features[(df_portfolio_features['Dev%_200'] > 5)].sort_values(by = 'CurrAlloc%', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
21,DEN,-4.21,-40.16,137.42,42.07,69458.0,-33920.0,50544.0,75.00,78.76,66.0,M-SC,6.87,235.0,-0.49,0.33,37.47,AR,NTT,ENTERTAINMENT
44,INDUSINDBK,-1.69,-33.15,98.80,32.89,50992.0,-25596.0,51611.0,1800.00,-343.00,48.0,L-MC,7.37,258.0,-0.50,0.34,27.04,XR,NTT,BANKS
3,ALKYLAMINE,-1.67,-23.21,152.17,93.63,117970.0,-23438.0,77525.0,4546.37,-17.74,55.0,H-SC,6.91,142.0,-0.20,0.51,46.39,SR,ATH,CHEMICALS
73,SONACOMS,-0.81,6.56,30.53,39.09,32909.0,6632.0,107791.0,804.02,-15.61,59.0,M-MC,18.36,193.0,0.20,0.71,52.49,AR,ATH,AUTO
72,SIS,-0.89,-1.44,23.03,21.26,25202.0,-1599.0,109433.0,528.00,2611.92,62.0,H-SC,23.66,168.0,-0.06,0.72,62.71,OX40N,NTT,MISC

In [23]:
# top 5 RSP
df_tmp = df_portfolio_features.sort_values(by = 'RSP', ascending=False)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
18,COFFEEDAY,0.94,-41.93,132.96,35.27,87665.0,-47616.0,65933.0,80.0,-55.73,57.0,L-SC,16.07,266.0,-0.54,0.44,62.59,XR,NTT,HOTELS
64,RELAXO,2.29,-52.81,222.72,52.31,152579.0,-76653.0,68507.0,1176.0,-49.76,65.0,X-SC,15.49,92.0,-0.50,0.45,53.17,X40N,NTT,FOOTWEAR
60,QUESS,2.10,2.97,68.89,73.90,75751.0,3167.0,109960.0,424.0,-44.35,74.0,X-SC,9.80,80.0,0.04,0.73,49.90,XY24,NTT,MISC
69,SFL,-0.73,-27.55,74.79,26.63,142075.0,-72253.0,189965.0,1287.0,43.89,73.0,M-SC,10.87,242.0,-0.51,1.25,58.33,XY24,NTT,MISC
21,DEN,-4.21,-40.16,137.42,42.07,69458.0,-33920.0,50544.0,75.0,78.76,66.0,M-SC,6.87,235.0,-0.49,0.33,37.47,AR,NTT,ENTERTAINMENT

In [24]:
# Top N allocation
df_tmp = df_portfolio_features.sort_values(by = 'CurrAlloc%', ascending=False)
top_n_values = [10, 25, 50]

sum_df = pd.DataFrame({
    'Top_N': top_n_values,
    'Sum_Alloc%': [df_tmp['CurrAlloc%'].head(n).sum() for n in top_n_values]
})

sum_df

   Top_N  Sum_Alloc%
0     10       19.30
1     25       42.52
2     50       72.75

In [25]:
# market-cap-wise allocation
df_tmp = df_portfolio_features[cols]
df_tmp.groupby(df_tmp['Conviction'].str[-2:])['CurrAlloc%'].sum().sort_values(ascending=False)

Conviction
SC    43.73
LC    30.47
MC    25.84
Name: CurrAlloc%, dtype: float64

In [26]:
# criteria-wise allocation
df_portfolio_features.groupby('Criteria')['CurrAlloc%'].sum().sort_values(ascending=False)

Criteria
XY24     27.81
X40      24.60
X40N     17.38
XR        8.89
OX40N     7.17
AR        6.84
XY25      6.48
SR        0.87
Name: CurrAlloc%, dtype: float64

In [27]:
# conviction-wise allocation
df_portfolio_features.groupby('Conviction')['CurrAlloc%'].sum().sort_values(ascending=False)

Conviction
X-LC    28.45
H-SC    22.92
X-MC    20.74
M-SC    10.17
X-SC    10.01
H-MC     2.74
M-MC     2.02
H-LC     1.22
M-LC     0.80
L-SC     0.63
L-MC     0.34
Name: CurrAlloc%, dtype: float64

In [28]:
# sector-wise stats
df_tmp = df_portfolio_features.groupby('Category')[['CurrAlloc%', 'Current', 'Current P/L', 'FTT Amt']].sum().sort_values(by=['Current', 'Current P/L'], ascending=False)
df_tmp['Current P/L%'] = round(df_tmp['Current P/L'] * 100 / df_tmp['Current'], 2)
df_tmp['FTT%'] = round(df_tmp['FTT Amt'] * 100 / df_tmp['Current'], 2)
cols = ['CurrAlloc%', 'Current P/L%', 'FTT%']
df_tmp[cols].sort_values(by=['CurrAlloc%'], ascending=False)

               CurrAlloc%  Current P/L%    FTT%
Category
FMCG                14.57        -20.01   62.10
FINANCE             10.96        -11.06   59.36
IT                   9.55        -55.84  133.75
MISC                 7.27        -21.83   74.10
AUTO                 6.61         -9.48   50.52
BANKS                5.75         -4.31   52.54
PAINTS               5.61        -15.91   35.68
INSURANCE            5.42         -0.90   34.94
PHARMA               5.07          3.61   26.22
ELECTRICAL           4.11        -13.65   53.76
CHEMICALS            2.18        -22.31   95.20
HEALTHCARE           2.09        -13.13   42.65
APPARELS             1.85          4.09   28.12
AC                   1.81        -16.09   47.57
FOOTWEAR             1.73        -68.18  135.61
TRAVEL               1.63        -82.10  173.28
REALTY               1.57          6.73    8.59
DURABLES             1.57        -62.78  102.38
BREWERIES            1.52         -1.76   22.90
CERAMICS             1.46        -39.43   81.79
CABLES               1.43         31.77   41.86
ENGINEERING          1.37        -16.99   70.49
REFINERIES           1.12        -18.97   49.06
JEWELLERY            1.08        -95.54  163.48
CEMENT               1.05        -68.08  193.82
ENTERTAINMENT        0.80        -59.68  154.91
HOTELS               0.44        -72.22  132.96
TEXTILES             0.42        -45.44   86.92

In [29]:
# money to be made criteria-wise
df_portfolio_features.groupby('Criteria')['FTT Amt'].agg(['sum', 'count']).sort_values(by='sum', ascending=False)

                sum  count
Criteria
XY24      3386658.0     21
X40       1953898.0     19
XR        1337802.0     13
AR        1139742.0      9
X40N      1089425.0     13
OX40N      707193.0     10
XY25       454889.0      5
SR         287882.0      2

In [30]:
# money to be made conviction-wise
df_portfolio_features.groupby('Conviction')['FTT Amt'].agg(['sum', 'count']).sort_values(by='sum', ascending=False)

                  sum  count
Conviction
H-SC        3310242.0     24
X-LC        1976709.0     21
X-MC        1574531.0     15
M-SC        1378349.0     14
X-SC        1288052.0      9
H-MC         283087.0      2
L-SC         196452.0      2
M-LC         170628.0      1
M-MC          79167.0      2
L-MC          50992.0      1
H-LC          49280.0      1

In [31]:
# money to be made criteria and conviction-wise
df_portfolio_features.groupby(['Conviction', 'Criteria'])['FTT Amt'].agg(['sum', 'count']).sort_values(by='sum', ascending=False)

                           sum  count
Conviction Criteria
X-LC       X40       1073521.0     10
H-SC       XY24       977972.0      6
           AR         949653.0      5
M-SC       XY24       818961.0      6
H-SC       XR         796388.0      7
X-SC       XY24       782166.0      4
X-MC       X40        673503.0      7
           X40N       435050.0      4
X-LC       X40N       355363.0      6
           XY24       346505.0      2
M-SC       OX40N      300059.0      5
X-SC       X40N       299012.0      3
H-SC       OX40N      298347.0      4
           SR         287882.0      2
X-MC       XY25       249569.0      2
H-MC       XY24       244645.0      1
X-MC       XY24       216409.0      2
X-SC       X40        206874.0      2
M-SC       XR         189871.0      2
M-LC       XR         170628.0      1
X-LC       XY25       159062.0      2
L-SC       OX40N      108787.0      1
           XR          87665.0      1
M-SC       AR          69458.0      1
L-MC       XR          50992.0      1
H-LC       AR          49280.0      1
M-MC       XY25        46258.0      1
X-LC       XR          42258.0      1
H-MC       AR          38442.0      1
M-MC       AR          32909.0      1

In [32]:
# notebook execution time

end_time = time.time()
execution_time = round(end_time - start_time, 0)
print(f"Notebook execution time: {execution_time} seconds")

Notebook execution time: 30.0 seconds