<a href="https://colab.research.google.com/github/ankit-rathi/Quantvesting_v2/blob/main/myStocks_Portfolio_Analysis.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
'''
!pip install pandas==2.2.2 -qq
!pip install pyxirr -qq
!pip install ta -qq
!pip install yfinance==0.2.59 -qq
'''

'\n!pip install pandas==2.2.2 -qq\n!pip install pyxirr -qq\n!pip install ta -qq\n!pip install yfinance==0.2.59 -qq\n'

In [2]:
# import libraries

import numpy as np
import pandas as pd
import datetime
import warnings
warnings.filterwarnings('ignore')
import yfinance as yfin
import ta
import matplotlib.pyplot as plt
import requests

In [3]:
# notebook start time
import time
import datetime
import pytz

start_time = time.time()

# function to print date timestamp
def print_date_time():
  tz_NY = pytz.timezone('Asia/Kolkata')
  datetime_NY = datetime.datetime.now(tz_NY)
  print("Run date time (IST):", datetime_NY.strftime("%Y-%m-%d %H:%M:%S"))

In [4]:
# function to get booked and reserved amount
def get_amt():
  # fetch the JSON data from the URL
  url = "https://raw.githubusercontent.com/ankit-rathi/Tradevesting_v1/main/data/myPortfolioAmts.json"
  response = requests.get(url)
  pf_amts = response.json()  # parse the JSON data

  # extract values from the JSON
  py_booked_amt_dm = pf_amts["py_booked_amt_dm"]
  py_booked_amt_sv = pf_amts["py_booked_amt_sv"]
  cy_booked_amt_dm = pf_amts["cy_booked_amt_dm"]
  cy_booked_amt_sv = pf_amts["cy_booked_amt_sv"]
  reserve_amt_dm = pf_amts["reserve_amt_dm"]
  reserve_amt_sv = pf_amts["reserve_amt_sv"]

  # perform calculations
  py_booked_amt = py_booked_amt_dm + py_booked_amt_sv
  cy_booked_amt = cy_booked_amt_dm + cy_booked_amt_sv
  reserve_amt = reserve_amt_dm + reserve_amt_sv
  total_booked_amt = py_booked_amt + cy_booked_amt

  return total_booked_amt, reserve_amt, cy_booked_amt, py_booked_amt

gen_output = 0

In [5]:
# function to format the amount
def format_amt(number):
    abs_number = abs(number)

    if abs_number >= 1_00_00_000:  # Crores
        formatted_amt = f"{number / 1_00_00_000:.2f} C"
    elif abs_number >= 1_00_000:  # Lakhs
        formatted_amt = f"{number / 1_00_000:.2f} L"
    elif abs_number >= 1_000:  # Thousands
        formatted_amt = f"{number / 1_000:.2f} K"
    else:
        formatted_amt = f"{number:.2f}"

    return formatted_amt

# function to set start and end date
def get_start_end_date():
  start_date = (datetime.date.today() + datetime.timedelta(days=-365)).strftime('%Y-%m-%d')
  end_date = (datetime.date.today() + datetime.timedelta(days=1)).strftime('%Y-%m-%d')
  return start_date, end_date

# function to fetch my portfolio csv
def get_mypfs_df():
  mypfs_df = pd.read_csv('https://raw.githubusercontent.com/ankit-rathi/Tradevesting_v1/main/data/myPortfolioStocks.csv')
  return mypfs_df

# function to fetch my prospects csv
def get_mypps_df():
  mypps_df = pd.read_csv('https://raw.githubusercontent.com/ankit-rathi/Tradevesting_v1/main/data/myProspectsScrips.csv')
  return mypps_df

# function to fetch screener data
def get_myscreen_df():
  myscreen_df = pd.read_csv('https://raw.githubusercontent.com/ankit-rathi/Tradevesting_v1/main/data/myScreenerDB.csv')
  return myscreen_df

# function to fetch momentum data
def get_myinvmt_df():
  myinvmt_df = pd.read_csv('https://raw.githubusercontent.com/ankit-rathi/Tradevesting_v1/main/data/myInvestments.csv')
  return myinvmt_df

# function to get the stock ids
def get_stock_ids(df_pf):
  stock_n100 = df_pf['Symbol'].unique()

  exclude = ['CADILAHC','MMTC', 'MASFIN']

  stock_ids = df_pf[~df_pf['Symbol'].isin(exclude) ]['Symbol'].unique()

  #mypf = mypf[mypf.Forecast.notnull()]
  #stock_ids = mypf['Symbol'].unique()

  #stock_ids.sort()
  return stock_ids

# get features from screener data
def get_screener_features():
  myscreen_df = get_myscreen_df()
  cols = ['Symbol', 'EPS', 'MedPE', 'ROCE%', 'ROE%', 'CapType']
  return myscreen_df[cols]

# get relative strength
def get_relative_strength(stock_list):

    # Dictionary to store stock tickers and their corresponding percentage price change
    stock_changes = {}

    # Loop through each stock and fetch its price data
    for stock in stock_list:
        try:
            # Download the stock data for the given date range
            stock_data = yfin.Ticker(stock + '.NS').history(period='1mo', interval='1d')[map(str.title, ['open', 'close', 'low', 'high', 'volume'])]

            # Calculate the percentage change for the stock
            if len(stock_data) > 0:
                start_price = stock_data['Close'].iloc[0]
                end_price = stock_data['Close'].iloc[-1]
                percent_change = round(((end_price - start_price) / start_price) * 100, 2)
                stock_changes[stock] = percent_change
            else:
                stock_changes[stock] = np.nan  # If no data is available, set to NaN

        except Exception as e:
            print(f"Error fetching data for {stock}: {e}")
            stock_changes[stock] = np.nan

    # Create a DataFrame with stock tickers and their percentage changes
    df = pd.DataFrame(list(stock_changes.items()), columns=['Symbol', 'Percent_Change'])

    # Drop any stocks with missing data (NaN values)
    df = df.dropna()

    # Calculate the percentile rank based on percentage change
    df['RSP'] = round(df['Percent_Change'].rank(pct=True) * 100, 2)
    cols = ['Symbol', 'RSP']
    df = df[cols]
    # Sort by percentile rank (optional)
    df = df.sort_values(by='RSP', ascending=False).reset_index(drop=True)

    return df

In [6]:
# function to get stock technicals
def stock_prec_dev(stock_symbol):
    #stock_symbol = 'ULTRACEMCO.NS'
    short_window = 20
    mid_window = 50
    long_window = 200
    moving_avg = 'SMA'

    start = datetime.datetime(*map(int, start_date.split('-')))
    end = datetime.datetime(*map(int, end_date.split('-')))

    stock_df = yfin.Ticker(stock_symbol + '.NS').history(period='max', interval='1d')[map(str.title, ['open', 'close', 'low', 'high', 'volume'])]

    stock_df['Max'] = round(max(stock_df['Close']),2)
    stock_df = stock_df[(stock_df.index <= end_date) & (stock_df.index >= start_date)]
    stock_df['200_SMA'] = round(stock_df['Close'].rolling(window = 200, min_periods = 1).mean(),0)
    stock_df['Dev%_200'] = round((stock_df['Close'] - stock_df['200_SMA'])*100/stock_df['200_SMA'],2)
    stock_df.dropna(axis = 0, inplace = True) # remove any null rows

    stock_df['20_SMA'] = stock_df['Close'].rolling(window=20).mean()
    stock_df['50_SMA'] = stock_df['Close'].rolling(window=50).mean()
    stock_df['Symbol'] = stock_symbol

    stock_df['Close'] = round(stock_df['Close'],2)
    stock_df['Min'] = round(min(stock_df['Close']),2)
    stock_df['RSI_14'] = ta.momentum.RSIIndicator(close=stock_df['Close'], window=14).rsi()
    stock_df['RSI_14'] = round(stock_df['RSI_14'],0)
    stock_df['Prev_Close'] = stock_df['Close'].shift(1)
    stock_df.drop(['Open', 'Low', 'High', 'Volume'], axis=1, inplace=True)
    stock_df = stock_df.tail(1)

    max_SMA = max(stock_df['20_SMA'].item(), stock_df['50_SMA'].item(), stock_df['200_SMA'].item())
    min_SMA = min(stock_df['20_SMA'].item(), stock_df['50_SMA'].item(), stock_df['200_SMA'].item())
    ABS_Spread = max_SMA - min_SMA
    stock_df['Spread%'] = round((ABS_Spread / stock_df['200_SMA'].item()) * 100,2)

    return stock_df

# function to compute stock attributes
def get_common_features(stock_ids, df_mypf):

  df_prec_dev = pd.DataFrame()
  df_tmp = get_screener_features()
  df_rs = get_relative_strength(stock_ids)

  for stock_id in stock_ids:
      tmp = stock_prec_dev(stock_id)
      tmp = tmp.reset_index()
      df_prec_dev = pd.concat([df_prec_dev, tmp], ignore_index = True)
  df_prec_dev = pd.merge(df_prec_dev, df_mypf, on= 'Symbol')
  df_prec_dev = pd.merge(df_prec_dev, df_tmp, on= 'Symbol', how='left')
  df_prec_dev = pd.merge(df_prec_dev, df_rs, on= 'Symbol', how='left')
  #print(df_prec_dev.columns)
  df_prec_dev['Curr_PE'] = round(df_prec_dev['Close']/df_prec_dev['EPS'],1)
  df_prec_dev['Dev%_PE'] = round((df_prec_dev['Curr_PE'] - df_prec_dev['MedPE'])*100/df_prec_dev['MedPE'],2)
  df_prec_dev['Conviction'] = df_prec_dev['Conviction'] + '-' + df_prec_dev['CapType']
  return df_prec_dev

# function to arrange stock features
def arrange_features(df_stocks, common_cols, diff_cols):
  df_stocks_common = df_stocks[common_cols].drop_duplicates()
  df_stocks_diff = df_stocks[diff_cols]
  df_stocks_diff['Investment'] = df_stocks_diff['AvgCost'] * df_stocks_diff['Shares']
  df_stocks_diff = df_stocks_diff.groupby(['Symbol'])[['Shares', 'Investment']].aggregate(['sum']).reset_index()
  df_stocks_diff.columns = ['Symbol', 'Shares', 'Investment']
  df_stocks_diff['AvgCost'] = round(df_stocks_diff['Investment']/df_stocks_diff['Shares'],2)
  df_stocks = pd.merge(df_stocks_diff, df_stocks_common, on='Symbol')
  return df_stocks

# plot fact distribution across dimension
def plot_pie_chart(df, dimension, fact):
  # grouping the data by category and calculating the sum of fact for each type
  grouped_data = df.groupby(dimension)[fact].sum()

  # sorting the grouped data in descending order
  grouped_data = grouped_data.sort_values(ascending=False)

  # creating a pie chart
  grouped_data.plot.pie(autopct='%1.1f%%', startangle=90, figsize=(6, 6))

  # adding a title and displaying the plot
  plt.title(f'{dimension} {fact} Distribution')
  plt.ylabel('')  # To hide the y-label
  plt.show()

In [7]:
# function to get portfolio features

def get_portfolio_features(df_common_features):

  print_date_time()
  print('-------------------')

  #df_common_features["Target"] = df_common_features["Target"].fillna(df_common_features["Max"])
  df_common_features['NTT'] = np.where(df_common_features['Strategy']== 'NTT', df_common_features["Target"], df_common_features['Max'])
  df_common_features['LTT'] = np.where(df_common_features['Strategy']== 'BTT', df_common_features["Target"], df_common_features['Max'])
  df_common_features['BOL'] = df_common_features['Min']

  tmp_df = df_common_features[df_common_features['Symbol'].isin(mypf_df[mypf_df['InPortfolio'] != 'NA'].Symbol.values)]
  print('qualified stocks: '+str(len(tmp_df['Symbol'].unique())))
  tmp_df1 = tmp_df[tmp_df['LatestQtr'] == 1]
  print('with latest results: '+str(len(tmp_df1['Symbol'].unique())))
  tmp_df1 = tmp_df1[tmp_df1['StarStock'] == 1]
  print('still star stocks: '+str(len(tmp_df1['Symbol'].unique())))
  tmp_df['Investment'] = tmp_df['AvgCost'] * tmp_df['Shares']
  tmp_df['Current'] = round(tmp_df['Close'] * tmp_df['Shares'],0)
  tmp_df['Previous'] = tmp_df['Prev_Close'] * tmp_df['Shares']
  tmp_df['EstimatedST'] = tmp_df['NTT'] * tmp_df['Shares']
  tmp_df['EstimatedLT'] = tmp_df['LTT'] * tmp_df['Shares']
  tmp_df['Current P/L'] = round((tmp_df['Current'] - tmp_df['Investment']),0)
  tmp_df['Today P/L%'] = round((tmp_df['Current'] - tmp_df['Previous'])*100/tmp_df['Previous'],2)
  tmp_df['Current P/L%'] = round((tmp_df['Current'] - tmp_df['Investment'])*100/tmp_df['Investment'],2)
  tmp_df['EstimatedST P/L%'] = round((tmp_df['EstimatedST'] - tmp_df['Investment'])*100/tmp_df['Investment'],2)
  tmp_df['EstimatedLT P/L%'] = round((tmp_df['EstimatedLT'] - tmp_df['Investment'])*100/tmp_df['Investment'],2)
  tmp_df['NTT%'] = round((tmp_df['NTT'] - tmp_df['Close'])*100/tmp_df['Close'],2)
  tmp_df['LTT%'] = round((tmp_df['LTT'] - tmp_df['Close'])*100/tmp_df['Close'],2)
  tmp_df['Gained%'] = round((tmp_df['Close'] - tmp_df['BOL'])*100/tmp_df['BOL'],2)
  investment = round(sum(tmp_df['AvgCost']*tmp_df['Shares']),0)
  current = round(sum(tmp_df['Close']*tmp_df['Shares']),0)
  tmp_df['InitAlloc%'] = round(tmp_df['Investment']*100/investment,2)
  tmp_df['CurrAlloc%'] = round(tmp_df['Current']*100/current,2)
  tmp_df['FTT'] = tmp_df['LTT']
  tmp_df.loc[tmp_df['Strategy'] == 'NTT', 'FTT'] = tmp_df['NTT']
  tmp_df['FTT%'] = tmp_df['LTT%']
  tmp_df.loc[tmp_df['Strategy'] == 'NTT', 'FTT%'] = tmp_df['NTT%']
  tmp_df['FTT Amt'] = round(tmp_df['FTT%'] * tmp_df['Current']/100,0)
  tmp_df['OTT%'] = round((tmp_df['FTT'] - tmp_df['AvgCost'])*100/tmp_df['AvgCost'],2)
  tmp_df['RRR Ind'] = round(tmp_df['Current P/L']/tmp_df['FTT Amt'],2)
  tmp_df['Risk Ind'] = round(tmp_df['Current P/L%']*tmp_df['CurrAlloc%'],0)

  return tmp_df

# function to print portfolio features
def print_portfolio_stats(df_portfolio_features, myinvmt_df):
  from pyxirr import xirr

  total_booked_amt, reserve_amt, cy_booked_amt, py_booked_amt = get_amt()

  dates = myinvmt_df['Date'].values
  dates = np.append(dates, datetime.date.today().strftime('%d-%b-%y'))
  investment = myinvmt_df['Investment'].values
  dates= pd.to_datetime(dates)

  current = round(sum(df_portfolio_features['Close']*df_portfolio_features['Shares']),0) + reserve_amt
  investment_xirr = np.append(investment, current)
  cagr = round(xirr(pd.DataFrame({"dates": dates, "amounts": investment_xirr}))*100,2)

  investment = -sum(investment)
  invested = round(sum(df_portfolio_features['AvgCost']*df_portfolio_features['Shares']),0) + reserve_amt
  previous = round(sum(df_portfolio_features['Prev_Close']*df_portfolio_features['Shares']),0) + reserve_amt
  cy_invested = investment + py_booked_amt

  today_pnl_amount = current-previous
  today_pnl_percentage = round((current-previous)*100/previous,2)

  curr_pnl_amount = current-invested
  curr_pnl_percentage = round((curr_pnl_amount)*100/(cy_invested),2)

  cy_pnl_amount = cy_booked_amt + curr_pnl_amount
  cy_pnl_percentage = round((cy_pnl_amount)*100/cy_invested,2)

  overall_pnl_amount = total_booked_amt + curr_pnl_amount
  overall_pnl_percentage = round((overall_pnl_amount)*100/investment,2)

  estimate_st = round(sum(df_portfolio_features['FTT']*df_portfolio_features['Shares']),0)  + reserve_amt
  est_st_pnl_amount = estimate_st-current
  est_st_pnl_percentage = round((est_st_pnl_amount)*100/current,2)

  estimate_lt = round(sum(df_portfolio_features['LTT']*df_portfolio_features['Shares']),0)  + reserve_amt
  est_lt_pnl_amount = estimate_lt-current
  est_lt_pnl_percentage = round((est_lt_pnl_amount)*100/current,2)

  total_profit = round(sum(df_portfolio_features[df_portfolio_features['Current P/L%'] > 0]['Current']) - sum(df_portfolio_features[df_portfolio_features['Current P/L%'] > 0]['Investment']),0)
  total_loss = round(sum(df_portfolio_features[df_portfolio_features['Current P/L%'] < 0]['Current']) - sum(df_portfolio_features[df_portfolio_features['Current P/L%'] < 0]['Investment']),0)

  cy_booked_percentage = round((cy_booked_amt)*100/current,2)
  py_booked_percentage = round((py_booked_amt)*100/investment,2)
  total_booked_percentage = round((total_booked_amt)*100/investment,2)

  print('-------------------')
  print('Initial Investment: ', format_amt(investment))
  print('CY Investment: ', format_amt(cy_invested))
  print('Reserve: ', format_amt(reserve_amt))
  print('Current: ',  format_amt(current))
  print('-------------------')
  print('Today PnL: '+ '{} ({}%)'.format(format_amt(today_pnl_amount), today_pnl_percentage))
  print('Current PnL: '+ '{} ({}%)'.format(format_amt(curr_pnl_amount), curr_pnl_percentage))
  print('CY Booked + Current PnL: '+ '{} ({}%)'.format(format_amt(cy_pnl_amount), cy_pnl_percentage))
  print('-------------------')
  print('Total profit: ', format_amt(total_profit))
  print('Total loss: ', format_amt(total_loss))
  print('-------------------')
  print('Total Booked + Current PnL: '+ '{} ({}%)'.format(format_amt(overall_pnl_amount), overall_pnl_percentage))
  print('Total Booked PnL: '+ '{} ({}%)'.format(format_amt(total_booked_amt), total_booked_percentage))
  print('Curr Year Booked PnL: '+ '{} ({}%)'.format(format_amt(cy_booked_amt), cy_booked_percentage))
  print('Prev Year Booked PnL: '+ '{} ({}%)'.format(format_amt(py_booked_amt), py_booked_percentage))
  print('===================')
  print('Est FTT: ',  format_amt(estimate_st))
  print('Est FTT PnL: '+ '{} ({}%)'.format(format_amt(est_st_pnl_amount), est_st_pnl_percentage))

  print('===================')
  print('Deployed: ', format_amt(investment))

  print('Current: ', format_amt(current))

  print('CAGR/XIRR %: '+'{}%'.format(cagr))

In [8]:
# get start and end date
start_date, end_date = get_start_end_date()

# get portfolio and prospects data
mypfs_df = get_mypfs_df()
mypps_df = get_mypps_df()
myinvmt_df = get_myinvmt_df()

# merge above datasets
mypf_df = pd.merge(mypfs_df, mypps_df, on="Symbol")

# seggregate dm and sv portfolio
dm_pf = mypf_df[mypf_df['InPortfolio'] == 'DM']
sv_pf = mypf_df[mypf_df['InPortfolio'] == 'SV']

# build portfolio stock dataframe
dm_stocks = get_stock_ids(dm_pf)
sv_stocks = get_stock_ids(sv_pf)
df_stocks = pd.concat([dm_pf,sv_pf], ignore_index = True)

# arrange common and diff stock features
common_cols = ['Symbol', 'Target', 'Criteria', 'Strategy', 'CumlRnk', 'LatestQtr', 'StarStock', 'Conviction', 'Category', 'InFolio', 'XIRR', 'MBQ']
diff_cols = ['Symbol', 'AvgCost', 'Shares']
df_stocks = arrange_features(df_stocks, common_cols, diff_cols)

# get common features
stock_ids = df_stocks['Symbol'].values
df_common_features = get_common_features(stock_ids, df_stocks)

df_common_features.reset_index(drop=True, inplace=True)
df_common_features.drop(['Date'], axis=1, inplace=True)
# get and print portfolio features
df_portfolio_features = get_portfolio_features(df_common_features)

print_portfolio_stats(df_portfolio_features, myinvmt_df)

df = df_portfolio_features
#plot_pie_chart(df, 'CapType', 'Current')
list_ox40n = list(df[df['MBQ'].str.contains('OX40N', na=False)]['Symbol'].values)

Run date time (IST): 2026-08-06 10:46:12
-------------------
qualified stocks: 88
with latest results: 30
still star stocks: 19
-------------------
Initial Investment:  1.46 C
CY Investment:  1.89 C
Reserve:  2.24 L
Current:  1.63 C
-------------------
Today PnL: -46.56 K (-0.29%)
Current PnL: -29.58 L (-15.66%)
CY Booked + Current PnL: -25.36 L (-13.42%)
-------------------
Total profit:  3.96 L
Total loss:  -33.54 L
-------------------
Total Booked + Current PnL: 17.51 L (11.99%)
Total Booked PnL: 47.09 L (32.24%)
Curr Year Booked PnL: 4.22 L (2.6%)
Prev Year Booked PnL: 42.87 L (29.35%)
===================
Est FTT:  2.67 C
Est FTT PnL: 1.04 C (64.14%)
===================
Deployed:  1.46 C
Current:  1.63 C
CAGR/XIRR %: 4.94%

In [9]:
# top 5 near their targets
cols = ['Symbol', 'Today P/L%', 'Current P/L%', 'FTT%', 'OTT%', 'FTT Amt', 'Current P/L', 'Current', 'FTT', 'Dev%_PE', 'RSI_14','Conviction', 'Spread%',  'CumlRnk', 'RRR Ind', 'CurrAlloc%', 'Gained%', 'Criteria', 'Strategy', 'Category']
df_tmp = df_portfolio_features[~df_portfolio_features['Symbol'].isin(['ENRIN','BLUSPRING','DIGITIDE'])]
df_tmp = df_tmp.sort_values(by = 'FTT Amt', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
55,MEDANTA,-0.33,22.36,3.89,27.12,8402.0,39473.0,215990.0,1486.00,18.58,66.0,X-SC,14.66,87.0,4.70,1.35,48.83,XY24,NTT,HEALTHCARE
79,TTKPRESTIG,-2.07,-17.98,22.04,0.09,18217.0,-18123.0,82654.0,770.00,91.89,50.0,M-SC,13.30,250.0,-0.99,0.52,48.77,OX40N,NTT,DURABLES
80,UNITDSPR,0.13,11.80,8.02,20.77,20994.0,27623.0,261767.0,1644.00,-0.77,71.0,X-MC,7.14,64.0,1.32,1.63,25.83,X40N,NTT,BREWERIES
69,SIS,2.99,0.55,20.60,21.26,22998.0,607.0,111639.0,528.00,2666.32,57.0,H-SC,23.61,168.0,0.03,0.70,65.99,OX40N,NTT,MISC
52,M&M,0.41,8.71,9.30,18.82,24333.0,20964.0,261645.0,3762.88,-5.39,69.0,X-LC,6.47,25.0,0.86,1.63,18.69,X40N,ATH,AUTO

In [10]:
# top 5 today
df_tmp = df_portfolio_features.sort_values(by = 'Today P/L%', ascending=False)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
12,BOSCH-HCIL,13.51,-30.86,44.61,-0.01,39421.0,-39437.0,88368.0,2282.00,17986.96,79.0,M-SC,5.84,231.0,-1.00,0.55,50.41,OX40N,BTT,AC
3,ALKYLAMINE,5.90,-17.72,134.00,92.54,111322.0,-17887.0,83076.0,4520.85,-11.91,62.0,H-SC,13.16,142.0,-0.16,0.52,57.75,SR,ATH,CHEMICALS
18,COFFEEDAY,4.78,-43.25,138.38,35.27,89165.0,-49114.0,64435.0,80.00,-55.73,63.0,L-SC,4.99,266.0,-0.55,0.40,58.90,XR,NTT,HOTELS
11,BERGEPAINT,4.13,1.04,24.02,25.32,62558.0,2693.0,260442.0,680.00,-4.38,68.0,X-MC,2.01,68.0,0.04,1.62,35.55,XY24,NTT,PAINTS
51,LAOPALA,3.74,-41.59,138.14,39.09,105777.0,-54533.0,76572.0,464.00,67.64,67.0,H-SC,7.12,154.0,-0.52,0.48,18.80,AR,NTT,CERAMICS

In [11]:
# bottom 5 today
df_tmp = df_portfolio_features.sort_values(by = 'Today P/L%', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
66,SFL,-10.29,-30.21,81.43,26.63,149027.0,-79206.0,183012.0,1287.00,38.54,41.0,M-SC,25.41,242.0,-0.53,1.14,52.74,XY24,NTT,MISC
81,VAIBHAVGBL,-9.14,-24.28,112.31,60.77,155444.0,-44369.0,138406.0,521.00,59.78,44.0,H-SC,12.19,160.0,-0.29,0.86,40.82,XR,NTT,JEWELLERY
58,QUESS,-7.04,31.55,32.19,73.90,45223.0,33695.0,140488.0,424.00,-29.48,64.0,X-SC,38.51,80.0,0.75,0.88,91.52,XY24,NTT,MISC
72,SYMPHONY,-4.84,-50.27,101.02,-0.03,85979.0,-86030.0,85111.0,1306.00,-60.13,33.0,M-SC,14.22,205.0,-1.00,0.53,0.00,OX40N,NTT,DURABLES
33,HCLTECH,-2.96,-10.63,38.71,23.97,107069.0,-32893.0,276593.0,1853.42,-9.02,67.0,X-LC,14.70,8.0,-0.31,1.73,30.52,X40,ATH,IT

In [12]:
# top 5 to exit based on CumlRnk
df_tmp = df_portfolio_features[~df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])]
df_tmp = df_tmp[(df_tmp['Current P/L%'] > -1) & (df_tmp['Current P/L%'] < 1)].sort_values(by = 'CumlRnk', ascending=False)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
5,ATULAUTO,3.57,0.63,44.66,45.57,88593.0,1241.0,198373.0,844.0,4316.22,79.0,M-SC,7.20,248.0,0.01,1.24,52.66,XY24,NTT,AUTO
69,SIS,2.99,0.55,20.60,21.26,22998.0,607.0,111639.0,528.0,2666.32,57.0,H-SC,23.61,168.0,0.03,0.70,65.99,OX40N,NTT,MISC

In [13]:
# OX40N stocks to exit
df_tmp = df_portfolio_features[(df_portfolio_features['Symbol'].isin(list_ox40n))].sort_values(by = 'Current P/L%', ascending=False)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
25,FINCABLES,2.98,30.17,59.72,107.91,114775.0,44545.0,192189.0,1641.55,17.20,49.0,M-SC,19.45,220.0,0.39,1.20,44.59,OX40N,ATH,CABLES
69,SIS,2.99,0.55,20.60,21.26,22998.0,607.0,111639.0,528.00,2666.32,57.0,H-SC,23.61,168.0,0.03,0.70,65.99,OX40N,NTT,MISC
16,CERA,1.83,-16.38,48.15,23.89,70827.0,-28807.0,147096.0,9475.00,-19.33,60.0,H-SC,13.41,153.0,-0.41,0.92,42.99,OX40N,NTT,CERAMICS
79,TTKPRESTIG,-2.07,-17.98,22.04,0.09,18217.0,-18123.0,82654.0,770.00,91.89,50.0,M-SC,13.30,250.0,-0.99,0.52,48.77,OX40N,NTT,DURABLES
43,INDIGOPNTS,3.04,-20.40,25.66,0.02,35653.0,-35617.0,138942.0,1408.00,112.05,64.0,M-SC,4.24,222.0,-1.00,0.87,57.64,OX40N,NTT,PAINTS

In [14]:
# top 5 to book for rotation
df_tmp = df_portfolio_features[(df_portfolio_features['Current P/L%'] > 20) ].sort_values(by = 'CumlRnk', ascending=False)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
25,FINCABLES,2.98,30.17,59.72,107.91,114775.0,44545.0,192189.0,1641.55,17.20,49.0,M-SC,19.45,220.0,0.39,1.20,44.59,OX40N,ATH,CABLES
55,MEDANTA,-0.33,22.36,3.89,27.12,8402.0,39473.0,215990.0,1486.00,18.58,66.0,X-SC,14.66,87.0,4.70,1.35,48.83,XY24,NTT,HEALTHCARE
58,QUESS,-7.04,31.55,32.19,73.90,45223.0,33695.0,140488.0,424.00,-29.48,64.0,X-SC,38.51,80.0,0.75,0.88,91.52,XY24,NTT,MISC

In [15]:
# top 5 to monitor for exit
df_tmp = df_portfolio_features[~df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])]
df_tmp = df_tmp[(df_tmp['Current P/L%'] > 0) ].sort_values(by = 'Dev%_PE', ascending=False)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
5,ATULAUTO,3.57,0.63,44.66,45.57,88593.0,1241.0,198373.0,844.00,4316.22,79.0,M-SC,7.20,248.0,0.01,1.24,52.66,XY24,NTT,AUTO
69,SIS,2.99,0.55,20.60,21.26,22998.0,607.0,111639.0,528.00,2666.32,57.0,H-SC,23.61,168.0,0.03,0.70,65.99,OX40N,NTT,MISC
70,STARHEALTH,-2.24,12.10,31.37,47.26,98859.0,34016.0,315139.0,761.00,76.87,48.0,H-SC,18.67,173.0,0.34,1.97,36.26,XY24,NTT,INSURANCE
25,FINCABLES,2.98,30.17,59.72,107.91,114775.0,44545.0,192189.0,1641.55,17.20,49.0,M-SC,19.45,220.0,0.39,1.20,44.59,OX40N,ATH,CABLES
87,ZYDUSLIFE,-0.48,17.65,15.18,35.51,37429.0,36996.0,246570.0,1285.01,2.25,49.0,H-MC,15.93,120.0,0.99,1.54,29.76,AR,ATH,PHARMA

In [16]:
# top 5 to book for rotation from weak conviction
df_tmp = df_portfolio_features[~df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])]
df_tmp = df_tmp[~df_tmp['Criteria'].isin(['XY25','XY24','X40', 'X40N'])].sort_values(by = 'RRR Ind', ascending=False)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
87,ZYDUSLIFE,-0.48,17.65,15.18,35.51,37429.0,36996.0,246570.0,1285.01,2.25,49.0,H-MC,15.93,120.0,0.99,1.54,29.76,AR,ATH,PHARMA
25,FINCABLES,2.98,30.17,59.72,107.91,114775.0,44545.0,192189.0,1641.55,17.20,49.0,M-SC,19.45,220.0,0.39,1.20,44.59,OX40N,ATH,CABLES
69,SIS,2.99,0.55,20.60,21.26,22998.0,607.0,111639.0,528.00,2666.32,57.0,H-SC,23.61,168.0,0.03,0.70,65.99,OX40N,NTT,MISC
3,ALKYLAMINE,5.90,-17.72,134.00,92.54,111322.0,-17887.0,83076.0,4520.85,-11.91,62.0,H-SC,13.16,142.0,-0.16,0.52,57.75,SR,ATH,CHEMICALS
54,MASFIN,-2.25,-4.93,27.87,21.57,25961.0,-4830.0,93150.0,397.04,-18.25,45.0,H-SC,1.70,167.0,-0.19,0.58,11.03,XR,ATH,FINANCE

In [17]:
# top 5 to accumulate based on lowest RSI_14
df_tmp = df_portfolio_features[df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])].sort_values(by = 'RSI_14', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
34,HDFCBANK,-0.14,-10.35,46.19,31.05,121374.0,-30348.0,262772.0,1073.00,-25.47,35.0,X-LC,10.13,26.0,-0.25,1.64,1.99,X40,BTT,BANKS
57,PGHH,-1.79,-36.35,107.39,32.01,145956.0,-77608.0,135912.0,17616.87,-56.92,36.0,X-MC,19.58,57.0,-0.53,0.85,0.21,X40,ATH,FMCG
83,VBL,-0.58,-10.35,51.32,35.66,161879.0,-36413.0,315431.0,669.42,-21.06,36.0,X-LC,7.75,13.0,-0.22,1.97,16.13,X40N,ATH,FMCG
20,DABUR,-2.70,-19.00,77.41,43.70,155545.0,-47132.0,200936.0,735.00,-26.49,39.0,X-MC,8.70,70.0,-0.30,1.25,2.25,XY24,BTT,FMCG
35,HDFCLIFE,-0.79,-7.27,50.07,39.15,116413.0,-18236.0,232501.0,811.41,-30.91,40.0,X-LC,15.90,31.0,-0.16,1.45,0.89,X40,ATH,INSURANCE

In [18]:
# top 5 to accumulate based on Spread and CumlRnk
df_tmp = df_portfolio_features[df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])]
df_tmp = df_tmp[(df_tmp['CumlRnk'] < 100)].sort_values(by = 'Spread%', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
19,COLPAL,-2.02,-22.73,81.00,39.86,164835.0,-59865.0,203500.0,3683.41,-6.52,45.0,X-MC,1.74,62.0,-0.36,1.27,15.11,XY25,ATH,FMCG
11,BERGEPAINT,4.13,1.04,24.02,25.32,62558.0,2693.0,260442.0,680.00,-4.38,68.0,X-MC,2.01,68.0,0.04,1.62,35.55,XY24,NTT,PAINTS
8,BAJAJHLDNG,-0.56,3.62,23.76,28.24,63031.0,9277.0,265282.0,14274.15,-4.76,72.0,X-LC,2.14,28.0,0.15,1.66,33.52,X40,ATH,FINANCE
23,DMART,-1.35,-3.46,36.13,31.42,108753.0,-10784.0,301006.0,5391.45,-19.69,45.0,X-LC,2.88,14.0,-0.10,1.88,8.62,X40N,ATH,FMCG
17,CIPLA,0.55,13.09,11.17,25.73,30470.0,31584.0,272780.0,1648.14,-7.26,64.0,X-LC,3.16,18.0,1.04,1.70,25.50,X40N,ATH,PHARMA

In [19]:
# top 5 to accumulate based on lowest Gained%
df_tmp = df_portfolio_features[df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])].sort_values(by = 'Gained%', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
57,PGHH,-1.79,-36.35,107.39,32.01,145956.0,-77608.0,135912.0,17616.87,-56.92,36.0,X-MC,19.58,57.0,-0.53,0.85,0.21,X40,ATH,FMCG
35,HDFCLIFE,-0.79,-7.27,50.07,39.15,116413.0,-18236.0,232501.0,811.41,-30.91,40.0,X-LC,15.90,31.0,-0.16,1.45,0.89,X40,ATH,INSURANCE
34,HDFCBANK,-0.14,-10.35,46.19,31.05,121374.0,-30348.0,262772.0,1073.00,-25.47,35.0,X-LC,10.13,26.0,-0.25,1.64,1.99,X40,BTT,BANKS
20,DABUR,-2.70,-19.00,77.41,43.70,155545.0,-47132.0,200936.0,735.00,-26.49,39.0,X-MC,8.70,70.0,-0.30,1.25,2.25,XY24,BTT,FMCG
36,HINDUNILVR,-2.54,-13.31,40.22,21.56,117335.0,-44785.0,291732.0,2922.00,-39.91,44.0,X-LC,5.68,9.0,-0.38,1.82,3.02,XY25,NTT,FMCG

In [20]:
# top 5 to accumulate based on lowest CurrAlloc%
df_tmp = df_portfolio_features[df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])].sort_values(by = 'CurrAlloc%', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
10,BATAINDIA,3.29,-52.72,185.95,35.20,113130.0,-67831.0,60839.0,2096.00,-20.29,66.0,X-SC,15.57,91.0,-0.60,0.38,22.23,X40,NTT,FOOTWEAR
62,RELAXO,3.65,-45.14,177.62,52.31,141451.0,-65523.0,79637.0,1176.00,-41.63,60.0,X-SC,9.89,92.0,-0.46,0.50,78.06,X40N,NTT,FOOTWEAR
57,PGHH,-1.79,-36.35,107.39,32.01,145956.0,-77608.0,135912.0,17616.87,-56.92,36.0,X-MC,19.58,57.0,-0.53,0.85,0.21,X40,ATH,FMCG
58,QUESS,-7.04,31.55,32.19,73.90,45223.0,33695.0,140488.0,424.00,-29.48,64.0,X-SC,38.51,80.0,0.75,0.88,91.52,XY24,NTT,MISC
40,ICICIPRULI,-2.56,-15.77,54.67,30.28,90716.0,-31071.0,165934.0,787.27,-38.45,52.0,X-MC,13.72,78.0,-0.34,1.04,10.56,X40,ATH,INSURANCE

In [21]:
# top 5 to accumulate based on CumlRnk
df_tmp = df_portfolio_features.sort_values(by = 'CumlRnk', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
47,ITC,-0.94,-21.57,58.99,24.70,183809.0,-85685.0,311593.0,452.00,-58.75,50.0,X-LC,12.30,1.0,-0.47,1.94,3.18,X40,NTT,FMCG
75,TCS,-2.93,-29.51,76.19,24.20,248808.0,-136710.0,326563.0,4230.71,-40.35,62.0,X-LC,16.34,2.0,-0.55,2.04,21.78,X40,ATH,IT
45,INFY,-0.44,-16.80,68.72,40.38,215257.0,-63232.0,313238.0,1972.00,-37.23,62.0,X-LC,16.48,3.0,-0.29,1.95,18.62,X40,NTT,IT
77,TMPV,-0.63,-17.42,72.86,42.75,250368.0,-72478.0,343629.0,600.00,-83.62,55.0,X-LC,6.25,4.0,-0.29,2.14,18.16,XY24,NTT,AUTO
33,HCLTECH,-2.96,-10.63,38.71,23.97,107069.0,-32893.0,276593.0,1853.42,-9.02,67.0,X-LC,14.70,8.0,-0.31,1.73,30.52,X40,ATH,IT

In [22]:
# top 5 for average up
df_tmp = df_portfolio_features[(df_portfolio_features['Dev%_200'] > 5)].sort_values(by = 'CurrAlloc%', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
44,INDUSINDBK,1.08,-23.96,74.76,32.89,43892.0,-18496.0,58710.0,1800.00,-376.61,58.0,L-MC,14.12,258.0,-0.42,0.37,44.74,XR,NTT,BANKS
62,RELAXO,3.65,-45.14,177.62,52.31,141451.0,-65523.0,79637.0,1176.00,-41.63,60.0,X-SC,9.89,92.0,-0.46,0.50,78.06,X40N,NTT,FOOTWEAR
3,ALKYLAMINE,5.90,-17.72,134.00,92.54,111322.0,-17887.0,83076.0,4520.85,-11.91,62.0,H-SC,13.16,142.0,-0.16,0.52,57.75,SR,ATH,CHEMICALS
79,TTKPRESTIG,-2.07,-17.98,22.04,0.09,18217.0,-18123.0,82654.0,770.00,91.89,50.0,M-SC,13.30,250.0,-0.99,0.52,48.77,OX40N,NTT,DURABLES
12,BOSCH-HCIL,13.51,-30.86,44.61,-0.01,39421.0,-39437.0,88368.0,2282.00,17986.96,79.0,M-SC,5.84,231.0,-1.00,0.55,50.41,OX40N,BTT,AC

In [23]:
# top 5 RSP
df_tmp = df_portfolio_features.sort_values(by = 'RSP', ascending=False)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
33,HCLTECH,-2.96,-10.63,38.71,23.97,107069.0,-32893.0,276593.0,1853.42,-9.02,67.0,X-LC,14.70,8.0,-0.31,1.73,30.52,X40,ATH,IT
30,HAPPSTMNDS,0.84,-49.55,262.87,83.08,169982.0,-63501.0,64664.0,1466.54,-39.93,66.0,H-SC,10.80,152.0,-0.37,0.40,21.12,AR,ATH,IT
75,TCS,-2.93,-29.51,76.19,24.20,248808.0,-136710.0,326563.0,4230.71,-40.35,62.0,X-LC,16.34,2.0,-0.55,2.04,21.78,X40,ATH,IT
12,BOSCH-HCIL,13.51,-30.86,44.61,-0.01,39421.0,-39437.0,88368.0,2282.00,17986.96,79.0,M-SC,5.84,231.0,-1.00,0.55,50.41,OX40N,BTT,AC
13,BSOFT,-0.11,-41.78,155.21,48.59,127106.0,-58760.0,81893.0,819.60,-25.40,64.0,H-SC,19.09,172.0,-0.46,0.51,19.72,XR,ATH,IT

In [24]:
# Top N allocation
df_tmp = df_portfolio_features.sort_values(by = 'CurrAlloc%', ascending=False)
top_n_values = [10, 25, 50]

sum_df = pd.DataFrame({
    'Top_N': top_n_values,
    'Sum_Alloc%': [df_tmp['CurrAlloc%'].head(n).sum() for n in top_n_values]
})

sum_df

   Top_N  Sum_Alloc%
0     10       19.63
1     25       44.57
2     50       76.81

In [25]:
# market-cap-wise allocation
df_tmp = df_portfolio_features[cols]
df_tmp.groupby(df_tmp['Conviction'].str[-2:])['CurrAlloc%'].sum().sort_values(ascending=False)

Conviction
SC    39.44
LC    37.61
MC    22.96
Name: CurrAlloc%, dtype: float64

In [26]:
# criteria-wise allocation
df_portfolio_features.groupby('Criteria')['CurrAlloc%'].sum().sort_values(ascending=False)

Criteria
X40      26.30
XY24     25.19
X40N     18.48
XR        9.12
XY25      7.22
OX40N     6.82
AR        6.02
SR        0.86
Name: CurrAlloc%, dtype: float64

In [27]:
# conviction-wise allocation
df_portfolio_features.groupby('Conviction')['CurrAlloc%'].sum().sort_values(ascending=False)

Conviction
X-LC    35.55
H-SC    19.28
X-MC    18.76
X-SC     9.96
M-SC     9.66
H-MC     2.58
H-LC     1.25
M-MC     1.25
M-LC     0.81
L-SC     0.54
L-MC     0.37
Name: CurrAlloc%, dtype: float64

In [28]:
# sector-wise stats
df_tmp = df_portfolio_features.groupby('Category')[['CurrAlloc%', 'Current', 'Current P/L', 'FTT Amt']].sum().sort_values(by=['Current', 'Current P/L'], ascending=False)
df_tmp['Current P/L%'] = round(df_tmp['Current P/L'] * 100 / df_tmp['Current'], 2)
df_tmp['FTT%'] = round(df_tmp['FTT Amt'] * 100 / df_tmp['Current'], 2)
cols = ['CurrAlloc%', 'Current P/L%', 'FTT%']
df_tmp[cols].sort_values(by=['CurrAlloc%'], ascending=False)

               CurrAlloc%  Current P/L%    FTT%
Category
FMCG                15.46        -20.29   63.62
IT                  11.08        -34.26  100.90
FINANCE              9.39        -13.64   61.40
AUTO                 8.39         -0.59   37.11
MISC                 6.98        -19.82   71.23
BANKS                6.08         -9.65   56.94
PHARMA               5.57          7.11   19.23
INSURANCE            5.57         -4.14   40.97
PAINTS               5.42        -13.28   32.60
ELECTRICAL           4.13         -6.69   44.05
HEALTHCARE           2.04         -9.35   37.89
AC                   1.77        -12.30   42.76
APPARELS             1.75          4.14   28.06
FOOTWEAR             1.69        -63.17  128.60
REFINERIES           1.66        -12.35   50.08
BREWERIES            1.63         10.55    8.02
DURABLES             1.51        -60.15   99.11
TRAVEL               1.44        -92.89  189.48
CERAMICS             1.40        -37.26   78.96
ENGINEERING          1.22        -24.35   81.22
CABLES               1.20         23.18   59.72
CHEMICALS            1.13        -45.90  164.33
CEMENT               1.04        -61.00  181.45
JEWELLERY            1.00        -99.06  168.22
ENTERTAINMENT        0.68        -76.82  182.27
HOTELS               0.40        -76.22  138.38
TEXTILES             0.38        -49.88   92.62

In [29]:
# money to be made criteria-wise
df_portfolio_features.groupby('Criteria')['FTT Amt'].agg(['sum', 'count']).sort_values(by='sum', ascending=False)

                sum  count
Criteria
XY24      3364153.0     20
X40       2010031.0     18
XR        1337768.0     13
X40N      1122975.0     12
AR        1066566.0      8
OX40N      700380.0     10
XY25       542870.0      5
SR         279706.0      2

In [30]:
# money to be made conviction-wise
df_portfolio_features.groupby('Conviction')['FTT Amt'].agg(['sum', 'count']).sort_values(by='sum', ascending=False)

                  sum  count
Conviction
H-SC        3264041.0     23
X-LC        2368174.0     20
X-MC        1445602.0     14
M-SC        1367305.0     14
X-SC        1207783.0      9
H-MC         283726.0      2
L-SC         204106.0      2
M-LC         162549.0      1
M-MC          45593.0      1
L-MC          43892.0      1
H-LC          31678.0      1

In [31]:
# money to be made criteria and conviction-wise
df_portfolio_features.groupby(['Conviction', 'Criteria'])['FTT Amt'].agg(['sum', 'count']).sort_values(by='sum', ascending=False)

                           sum  count
Conviction Criteria
X-LC       X40       1158699.0      9
H-SC       XY24       978423.0      5
           AR         921316.0      5
M-SC       XY24       804975.0      6
H-SC       XR         793202.0      7
X-SC       XY24       707392.0      4
X-MC       X40        640081.0      7
X-LC       X40N       493486.0      6
           XY24       408963.0      2
X-MC       X40N       340349.0      3
M-SC       OX40N      294045.0      5
H-SC       OX40N      291394.0      4
X-SC       X40N       289140.0      3
H-SC       SR         279706.0      2
X-LC       XY25       250208.0      2
X-MC       XY25       247069.0      2
H-MC       XY24       246297.0      1
X-MC       XY24       218103.0      2
X-SC       X40        211251.0      2
M-SC       XR         192142.0      2
M-LC       XR         162549.0      1
L-SC       OX40N      114941.0      1
           XR          89165.0      1
M-SC       AR          76143.0      1
X-LC       XR          56818.0      1
M-MC       XY25        45593.0      1
L-MC       XR          43892.0      1
H-MC       AR          37429.0      1
H-LC       AR          31678.0      1

In [32]:
# notebook execution time

end_time = time.time()
execution_time = round(end_time - start_time, 0)
print(f"Notebook execution time: {execution_time} seconds")

Notebook execution time: 39.0 seconds