<a href="https://colab.research.google.com/github/ankit-rathi/Quantvesting_v2/blob/main/myStocks_Portfolio_Analysis.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
'''
!pip install pandas==2.2.2 -qq
!pip install pyxirr -qq
!pip install ta -qq
!pip install yfinance==0.2.59 -qq
'''

'\n!pip install pandas==2.2.2 -qq\n!pip install pyxirr -qq\n!pip install ta -qq\n!pip install yfinance==0.2.59 -qq\n'

In [2]:
# import libraries

import numpy as np
import pandas as pd
import datetime
import warnings
warnings.filterwarnings('ignore')
import yfinance as yfin
import ta
import matplotlib.pyplot as plt
import requests

In [3]:
# notebook start time
import time
import datetime
import pytz

start_time = time.time()

# function to print date timestamp
def print_date_time():
  tz_NY = pytz.timezone('Asia/Kolkata')
  datetime_NY = datetime.datetime.now(tz_NY)
  print("Run date time (IST):", datetime_NY.strftime("%Y-%m-%d %H:%M:%S"))

In [4]:
# function to get booked and reserved amount
def get_amt():
  # fetch the JSON data from the URL
  url = "https://raw.githubusercontent.com/ankit-rathi/Tradevesting_v1/main/data/myPortfolioAmts.json"
  response = requests.get(url)
  pf_amts = response.json()  # parse the JSON data

  # extract values from the JSON
  py_booked_amt_dm = pf_amts["py_booked_amt_dm"]
  py_booked_amt_sv = pf_amts["py_booked_amt_sv"]
  cy_booked_amt_dm = pf_amts["cy_booked_amt_dm"]
  cy_booked_amt_sv = pf_amts["cy_booked_amt_sv"]
  reserve_amt_dm = pf_amts["reserve_amt_dm"]
  reserve_amt_sv = pf_amts["reserve_amt_sv"]

  # perform calculations
  py_booked_amt = py_booked_amt_dm + py_booked_amt_sv
  cy_booked_amt = cy_booked_amt_dm + cy_booked_amt_sv
  reserve_amt = reserve_amt_dm + reserve_amt_sv
  total_booked_amt = py_booked_amt + cy_booked_amt

  return total_booked_amt, reserve_amt, cy_booked_amt, py_booked_amt

gen_output = 0

In [5]:
# function to format the amount
def format_amt(number):
    abs_number = abs(number)

    if abs_number >= 1_00_00_000:  # Crores
        formatted_amt = f"{number / 1_00_00_000:.2f} C"
    elif abs_number >= 1_00_000:  # Lakhs
        formatted_amt = f"{number / 1_00_000:.2f} L"
    elif abs_number >= 1_000:  # Thousands
        formatted_amt = f"{number / 1_000:.2f} K"
    else:
        formatted_amt = f"{number:.2f}"

    return formatted_amt

# function to set start and end date
def get_start_end_date():
  start_date = (datetime.date.today() + datetime.timedelta(days=-365)).strftime('%Y-%m-%d')
  end_date = (datetime.date.today() + datetime.timedelta(days=1)).strftime('%Y-%m-%d')
  return start_date, end_date

# function to fetch my portfolio csv
def get_mypfs_df():
  mypfs_df = pd.read_csv('https://raw.githubusercontent.com/ankit-rathi/Tradevesting_v1/main/data/myPortfolioStocks.csv')
  return mypfs_df

# function to fetch my prospects csv
def get_mypps_df():
  mypps_df = pd.read_csv('https://raw.githubusercontent.com/ankit-rathi/Tradevesting_v1/main/data/myProspectsScrips.csv')
  return mypps_df

# function to fetch screener data
def get_myscreen_df():
  myscreen_df = pd.read_csv('https://raw.githubusercontent.com/ankit-rathi/Tradevesting_v1/main/data/myScreenerDB.csv')
  return myscreen_df

# function to fetch momentum data
def get_myinvmt_df():
  myinvmt_df = pd.read_csv('https://raw.githubusercontent.com/ankit-rathi/Tradevesting_v1/main/data/myInvestments.csv')
  return myinvmt_df

# function to get the stock ids
def get_stock_ids(df_pf):
  stock_n100 = df_pf['Symbol'].unique()

  exclude = ['CADILAHC','MMTC', 'MASFIN']

  stock_ids = df_pf[~df_pf['Symbol'].isin(exclude) ]['Symbol'].unique()

  #mypf = mypf[mypf.Forecast.notnull()]
  #stock_ids = mypf['Symbol'].unique()

  #stock_ids.sort()
  return stock_ids

# get features from screener data
def get_screener_features():
  myscreen_df = get_myscreen_df()
  cols = ['Symbol', 'EPS', 'MedPE', 'ROCE%', 'ROE%', 'CapType']
  return myscreen_df[cols]

# get relative strength
def get_relative_strength(stock_list):

    # Dictionary to store stock tickers and their corresponding percentage price change
    stock_changes = {}

    # Loop through each stock and fetch its price data
    for stock in stock_list:
        try:
            # Download the stock data for the given date range
            stock_data = yfin.Ticker(stock + '.NS').history(period='1mo', interval='1d')[map(str.title, ['open', 'close', 'low', 'high', 'volume'])]

            # Calculate the percentage change for the stock
            if len(stock_data) > 0:
                start_price = stock_data['Close'].iloc[0]
                end_price = stock_data['Close'].iloc[-1]
                percent_change = round(((end_price - start_price) / start_price) * 100, 2)
                stock_changes[stock] = percent_change
            else:
                stock_changes[stock] = np.nan  # If no data is available, set to NaN

        except Exception as e:
            print(f"Error fetching data for {stock}: {e}")
            stock_changes[stock] = np.nan

    # Create a DataFrame with stock tickers and their percentage changes
    df = pd.DataFrame(list(stock_changes.items()), columns=['Symbol', 'Percent_Change'])

    # Drop any stocks with missing data (NaN values)
    df = df.dropna()

    # Calculate the percentile rank based on percentage change
    df['RSP'] = round(df['Percent_Change'].rank(pct=True) * 100, 2)
    cols = ['Symbol', 'RSP']
    df = df[cols]
    # Sort by percentile rank (optional)
    df = df.sort_values(by='RSP', ascending=False).reset_index(drop=True)

    return df

In [6]:
# function to get stock technicals
def stock_prec_dev(stock_symbol):
    #stock_symbol = 'ULTRACEMCO.NS'
    short_window = 20
    mid_window = 50
    long_window = 200
    moving_avg = 'SMA'

    start = datetime.datetime(*map(int, start_date.split('-')))
    end = datetime.datetime(*map(int, end_date.split('-')))

    stock_df = yfin.Ticker(stock_symbol + '.NS').history(period='max', interval='1d')[map(str.title, ['open', 'close', 'low', 'high', 'volume'])]

    stock_df['Max'] = round(max(stock_df['Close']),2)
    stock_df = stock_df[(stock_df.index <= end_date) & (stock_df.index >= start_date)]
    stock_df['200_SMA'] = round(stock_df['Close'].rolling(window = 200, min_periods = 1).mean(),0)
    stock_df['Dev%_200'] = round((stock_df['Close'] - stock_df['200_SMA'])*100/stock_df['200_SMA'],2)
    stock_df.dropna(axis = 0, inplace = True) # remove any null rows

    stock_df['20_SMA'] = stock_df['Close'].rolling(window=20).mean()
    stock_df['50_SMA'] = stock_df['Close'].rolling(window=50).mean()
    stock_df['Symbol'] = stock_symbol

    stock_df['Close'] = round(stock_df['Close'],2)
    stock_df['Min'] = round(min(stock_df['Close']),2)
    stock_df['RSI_14'] = ta.momentum.RSIIndicator(close=stock_df['Close'], window=14).rsi()
    stock_df['RSI_14'] = round(stock_df['RSI_14'],0)
    stock_df['Prev_Close'] = stock_df['Close'].shift(1)
    stock_df.drop(['Open', 'Low', 'High', 'Volume'], axis=1, inplace=True)
    stock_df = stock_df.tail(1)

    max_SMA = max(stock_df['20_SMA'].item(), stock_df['50_SMA'].item(), stock_df['200_SMA'].item())
    min_SMA = min(stock_df['20_SMA'].item(), stock_df['50_SMA'].item(), stock_df['200_SMA'].item())
    ABS_Spread = max_SMA - min_SMA
    stock_df['Spread%'] = round((ABS_Spread / stock_df['200_SMA'].item()) * 100,2)

    return stock_df

# function to compute stock attributes
def get_common_features(stock_ids, df_mypf):

  df_prec_dev = pd.DataFrame()
  df_tmp = get_screener_features()
  df_rs = get_relative_strength(stock_ids)

  for stock_id in stock_ids:
      tmp = stock_prec_dev(stock_id)
      tmp = tmp.reset_index()
      df_prec_dev = pd.concat([df_prec_dev, tmp], ignore_index = True)
  df_prec_dev = pd.merge(df_prec_dev, df_mypf, on= 'Symbol')
  df_prec_dev = pd.merge(df_prec_dev, df_tmp, on= 'Symbol', how='left')
  df_prec_dev = pd.merge(df_prec_dev, df_rs, on= 'Symbol', how='left')
  #print(df_prec_dev.columns)
  df_prec_dev['Curr_PE'] = round(df_prec_dev['Close']/df_prec_dev['EPS'],1)
  df_prec_dev['Dev%_PE'] = round((df_prec_dev['Curr_PE'] - df_prec_dev['MedPE'])*100/df_prec_dev['MedPE'],2)
  df_prec_dev['Conviction'] = df_prec_dev['Conviction'] + '-' + df_prec_dev['CapType']
  return df_prec_dev

# function to arrange stock features
def arrange_features(df_stocks, common_cols, diff_cols):
  df_stocks_common = df_stocks[common_cols].drop_duplicates()
  df_stocks_diff = df_stocks[diff_cols]
  df_stocks_diff['Investment'] = df_stocks_diff['AvgCost'] * df_stocks_diff['Shares']
  df_stocks_diff = df_stocks_diff.groupby(['Symbol'])[['Shares', 'Investment']].aggregate(['sum']).reset_index()
  df_stocks_diff.columns = ['Symbol', 'Shares', 'Investment']
  df_stocks_diff['AvgCost'] = round(df_stocks_diff['Investment']/df_stocks_diff['Shares'],2)
  df_stocks = pd.merge(df_stocks_diff, df_stocks_common, on='Symbol')
  return df_stocks

# plot fact distribution across dimension
def plot_pie_chart(df, dimension, fact):
  # grouping the data by category and calculating the sum of fact for each type
  grouped_data = df.groupby(dimension)[fact].sum()

  # sorting the grouped data in descending order
  grouped_data = grouped_data.sort_values(ascending=False)

  # creating a pie chart
  grouped_data.plot.pie(autopct='%1.1f%%', startangle=90, figsize=(6, 6))

  # adding a title and displaying the plot
  plt.title(f'{dimension} {fact} Distribution')
  plt.ylabel('')  # To hide the y-label
  plt.show()

In [7]:
# function to get portfolio features

def get_portfolio_features(df_common_features):

  print_date_time()
  print('-------------------')

  #df_common_features["Target"] = df_common_features["Target"].fillna(df_common_features["Max"])
  df_common_features['NTT'] = np.where(df_common_features['Strategy']== 'NTT', df_common_features["Target"], df_common_features['Max'])
  df_common_features['LTT'] = np.where(df_common_features['Strategy']== 'BTT', df_common_features["Target"], df_common_features['Max'])
  df_common_features['BOL'] = df_common_features['Min']

  tmp_df = df_common_features[df_common_features['Symbol'].isin(mypf_df[mypf_df['InPortfolio'] != 'NA'].Symbol.values)]
  print('qualified stocks: '+str(len(tmp_df['Symbol'].unique())))
  tmp_df1 = tmp_df[tmp_df['LatestQtr'] == 1]
  print('with latest results: '+str(len(tmp_df1['Symbol'].unique())))
  tmp_df1 = tmp_df1[tmp_df1['StarStock'] == 1]
  print('still star stocks: '+str(len(tmp_df1['Symbol'].unique())))
  tmp_df['Investment'] = tmp_df['AvgCost'] * tmp_df['Shares']
  tmp_df['Current'] = round(tmp_df['Close'] * tmp_df['Shares'],0)
  tmp_df['Previous'] = tmp_df['Prev_Close'] * tmp_df['Shares']
  tmp_df['EstimatedST'] = tmp_df['NTT'] * tmp_df['Shares']
  tmp_df['EstimatedLT'] = tmp_df['LTT'] * tmp_df['Shares']
  tmp_df['Current P/L'] = round((tmp_df['Current'] - tmp_df['Investment']),0)
  tmp_df['Today P/L%'] = round((tmp_df['Current'] - tmp_df['Previous'])*100/tmp_df['Previous'],2)
  tmp_df['Current P/L%'] = round((tmp_df['Current'] - tmp_df['Investment'])*100/tmp_df['Investment'],2)
  tmp_df['EstimatedST P/L%'] = round((tmp_df['EstimatedST'] - tmp_df['Investment'])*100/tmp_df['Investment'],2)
  tmp_df['EstimatedLT P/L%'] = round((tmp_df['EstimatedLT'] - tmp_df['Investment'])*100/tmp_df['Investment'],2)
  tmp_df['NTT%'] = round((tmp_df['NTT'] - tmp_df['Close'])*100/tmp_df['Close'],2)
  tmp_df['LTT%'] = round((tmp_df['LTT'] - tmp_df['Close'])*100/tmp_df['Close'],2)
  tmp_df['Gained%'] = round((tmp_df['Close'] - tmp_df['BOL'])*100/tmp_df['BOL'],2)
  investment = round(sum(tmp_df['AvgCost']*tmp_df['Shares']),0)
  current = round(sum(tmp_df['Close']*tmp_df['Shares']),0)
  tmp_df['InitAlloc%'] = round(tmp_df['Investment']*100/investment,2)
  tmp_df['CurrAlloc%'] = round(tmp_df['Current']*100/current,2)
  tmp_df['FTT'] = tmp_df['LTT']
  tmp_df.loc[tmp_df['Strategy'] == 'NTT', 'FTT'] = tmp_df['NTT']
  tmp_df['FTT%'] = tmp_df['LTT%']
  tmp_df.loc[tmp_df['Strategy'] == 'NTT', 'FTT%'] = tmp_df['NTT%']
  tmp_df['FTT Amt'] = round(tmp_df['FTT%'] * tmp_df['Current']/100,0)
  tmp_df['OTT%'] = round((tmp_df['FTT'] - tmp_df['AvgCost'])*100/tmp_df['AvgCost'],2)
  tmp_df['RRR Ind'] = round(tmp_df['Current P/L']/tmp_df['FTT Amt'],2)
  tmp_df['Risk Ind'] = round(tmp_df['Current P/L%']*tmp_df['CurrAlloc%'],0)

  return tmp_df

# function to print portfolio features
def print_portfolio_stats(df_portfolio_features, myinvmt_df):
  from pyxirr import xirr

  total_booked_amt, reserve_amt, cy_booked_amt, py_booked_amt = get_amt()

  dates = myinvmt_df['Date'].values
  dates = np.append(dates, datetime.date.today().strftime('%d-%b-%y'))
  investment = myinvmt_df['Investment'].values
  dates= pd.to_datetime(dates)

  current = round(sum(df_portfolio_features['Close']*df_portfolio_features['Shares']),0) + reserve_amt
  investment_xirr = np.append(investment, current)
  cagr = round(xirr(pd.DataFrame({"dates": dates, "amounts": investment_xirr}))*100,2)

  investment = -sum(investment)
  invested = round(sum(df_portfolio_features['AvgCost']*df_portfolio_features['Shares']),0) + reserve_amt
  previous = round(sum(df_portfolio_features['Prev_Close']*df_portfolio_features['Shares']),0) + reserve_amt
  cy_invested = investment + py_booked_amt

  today_pnl_amount = current-previous
  today_pnl_percentage = round((current-previous)*100/previous,2)

  curr_pnl_amount = current-invested
  curr_pnl_percentage = round((curr_pnl_amount)*100/(cy_invested),2)

  cy_pnl_amount = cy_booked_amt + curr_pnl_amount
  cy_pnl_percentage = round((cy_pnl_amount)*100/cy_invested,2)

  overall_pnl_amount = total_booked_amt + curr_pnl_amount
  overall_pnl_percentage = round((overall_pnl_amount)*100/investment,2)

  estimate_st = round(sum(df_portfolio_features['FTT']*df_portfolio_features['Shares']),0)  + reserve_amt
  est_st_pnl_amount = estimate_st-current
  est_st_pnl_percentage = round((est_st_pnl_amount)*100/current,2)

  estimate_lt = round(sum(df_portfolio_features['LTT']*df_portfolio_features['Shares']),0)  + reserve_amt
  est_lt_pnl_amount = estimate_lt-current
  est_lt_pnl_percentage = round((est_lt_pnl_amount)*100/current,2)

  total_profit = round(sum(df_portfolio_features[df_portfolio_features['Current P/L%'] > 0]['Current']) - sum(df_portfolio_features[df_portfolio_features['Current P/L%'] > 0]['Investment']),0)
  total_loss = round(sum(df_portfolio_features[df_portfolio_features['Current P/L%'] < 0]['Current']) - sum(df_portfolio_features[df_portfolio_features['Current P/L%'] < 0]['Investment']),0)

  cy_booked_percentage = round((cy_booked_amt)*100/current,2)
  py_booked_percentage = round((py_booked_amt)*100/investment,2)
  total_booked_percentage = round((total_booked_amt)*100/investment,2)

  print('-------------------')
  print('Initial Investment: ', format_amt(investment))
  print('CY Investment: ', format_amt(cy_invested))
  print('Reserve: ', format_amt(reserve_amt))
  print('Current: ',  format_amt(current))
  print('-------------------')
  print('Today PnL: '+ '{} ({}%)'.format(format_amt(today_pnl_amount), today_pnl_percentage))
  print('Current PnL: '+ '{} ({}%)'.format(format_amt(curr_pnl_amount), curr_pnl_percentage))
  print('CY Booked + Current PnL: '+ '{} ({}%)'.format(format_amt(cy_pnl_amount), cy_pnl_percentage))
  print('-------------------')
  print('Total profit: ', format_amt(total_profit))
  print('Total loss: ', format_amt(total_loss))
  print('-------------------')
  print('Total Booked + Current PnL: '+ '{} ({}%)'.format(format_amt(overall_pnl_amount), overall_pnl_percentage))
  print('Total Booked PnL: '+ '{} ({}%)'.format(format_amt(total_booked_amt), total_booked_percentage))
  print('Curr Year Booked PnL: '+ '{} ({}%)'.format(format_amt(cy_booked_amt), cy_booked_percentage))
  print('Prev Year Booked PnL: '+ '{} ({}%)'.format(format_amt(py_booked_amt), py_booked_percentage))
  print('===================')
  print('Est FTT: ',  format_amt(estimate_st))
  print('Est FTT PnL: '+ '{} ({}%)'.format(format_amt(est_st_pnl_amount), est_st_pnl_percentage))

  print('===================')
  print('Deployed: ', format_amt(investment))

  print('Current: ', format_amt(current))

  print('CAGR/XIRR %: '+'{}%'.format(cagr))

In [8]:
# get start and end date
start_date, end_date = get_start_end_date()

# get portfolio and prospects data
mypfs_df = get_mypfs_df()
mypps_df = get_mypps_df()
myinvmt_df = get_myinvmt_df()

# merge above datasets
mypf_df = pd.merge(mypfs_df, mypps_df, on="Symbol")

# seggregate dm and sv portfolio
dm_pf = mypf_df[mypf_df['InPortfolio'] == 'DM']
sv_pf = mypf_df[mypf_df['InPortfolio'] == 'SV']

# build portfolio stock dataframe
dm_stocks = get_stock_ids(dm_pf)
sv_stocks = get_stock_ids(sv_pf)
df_stocks = pd.concat([dm_pf,sv_pf], ignore_index = True)

# arrange common and diff stock features
common_cols = ['Symbol', 'Target', 'Criteria', 'Strategy', 'CumlRnk', 'LatestQtr', 'StarStock', 'Conviction', 'Category', 'InFolio', 'XIRR', 'MBQ']
diff_cols = ['Symbol', 'AvgCost', 'Shares']
df_stocks = arrange_features(df_stocks, common_cols, diff_cols)

# get common features
stock_ids = df_stocks['Symbol'].values
df_common_features = get_common_features(stock_ids, df_stocks)

df_common_features.reset_index(drop=True, inplace=True)
df_common_features.drop(['Date'], axis=1, inplace=True)
# get and print portfolio features
df_portfolio_features = get_portfolio_features(df_common_features)

print_portfolio_stats(df_portfolio_features, myinvmt_df)

df = df_portfolio_features
#plot_pie_chart(df, 'CapType', 'Current')
list_ox40n = list(df[df['MBQ'].str.contains('OX40N', na=False)]['Symbol'].values)

Run date time (IST): 2026-03-06 15:32:59
-------------------
qualified stocks: 86
with latest results: 26
still star stocks: 15
-------------------
Initial Investment:  1.33 C
CY Investment:  1.60 C
Reserve:  2.44 L
Current:  1.35 C
-------------------
Today PnL: -33.97 K (-0.25%)
Current PnL: -39.26 L (-24.54%)
CY Booked + Current PnL: -23.58 L (-14.74%)
-------------------
Total profit:  1.16 L
Total loss:  -40.42 L
-------------------
Total Booked + Current PnL: 3.40 L (2.56%)
Total Booked PnL: 42.66 L (32.07%)
Curr Year Booked PnL: 15.68 L (11.6%)
Prev Year Booked PnL: 26.98 L (20.29%)
===================
Est FTT:  2.41 C
Est FTT PnL: 1.06 C (78.32%)
===================
Deployed:  1.33 C
Current:  1.35 C
CAGR/XIRR %: 0.81%

In [9]:
# top 5 near their targets
cols = ['Symbol', 'Today P/L%', 'Current P/L%', 'FTT%', 'OTT%', 'FTT Amt', 'Current P/L', 'Current', 'FTT', 'Dev%_PE', 'RSI_14','Conviction', 'Spread%',  'CumlRnk', 'RRR Ind', 'CurrAlloc%', 'Gained%', 'Criteria', 'Strategy', 'Category']
df_tmp = df_portfolio_features[~df_portfolio_features['Symbol'].isin(['ENRIN','BLUSPRING','DIGITIDE'])]
df_tmp = df_tmp.sort_values(by = 'FTT Amt', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
19,COALINDIA,-1.99,8.31,8.64,17.67,14080.0,12506.0,162966.0,478.51,30.56,58.0,L-LC,11.17,185.0,0.89,1.23,26.56,XY25,ATH,MINING
50,MASFIN,-0.71,-7.87,31.95,21.57,28841.0,-7710.0,90270.0,397.04,-20.51,35.0,H-SC,6.17,167.0,-0.27,0.68,25.96,XR,ATH,FINANCE
77,TTKPRESTIG,-2.75,-39.05,64.21,0.09,39442.0,-39351.0,61426.0,770.00,42.58,19.0,M-SC,13.49,250.0,-1.00,0.46,0.00,OX40N,NTT,DURABLES
37,ICICIGI,0.27,-0.40,19.82,19.34,39504.0,-797.0,199312.0,2252.93,-16.16,46.0,X-MC,1.46,66.0,-0.02,1.50,13.67,X40,ATH,INSURANCE
51,MEDANTA,-0.14,-7.31,33.86,24.08,39843.0,-9279.0,117671.0,1486.00,-7.89,44.0,X-SC,8.17,87.0,-0.23,0.89,7.78,XY24,NTT,HEALTHCARE

In [10]:
# top 5 today
df_tmp = df_portfolio_features.sort_values(by = 'Today P/L%', ascending=False)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
27,FINCABLES,5.54,22.71,69.43,107.91,125790.0,33531.0,181175.0,1641.55,10.60,72.0,M-SC,6.53,220.0,0.27,1.36,36.30,OX40N,ATH,CABLES
78,UNITDSPR,4.83,2.09,18.29,20.77,43722.0,4902.0,239046.0,1644.00,-9.40,52.0,X-MC,1.50,64.0,0.11,1.80,8.94,X40N,NTT,BREWERIES
74,TITAGARH,3.39,-35.95,127.55,45.74,197840.0,-87069.0,155108.0,1548.00,-14.75,34.0,H-SC,13.93,175.0,-0.44,1.17,5.97,XY24,NTT,ENGINEERING
47,JSWINFRA,2.81,-8.49,27.23,16.43,55262.0,-18830.0,202944.0,342.00,-21.44,57.0,X-MC,11.11,61.0,-0.34,1.53,8.96,X40N,NTT,REALTY
56,RAJOOENG,2.64,-40.14,133.21,39.61,81738.0,-41140.0,61360.0,143.10,-59.49,44.0,H-SC,29.35,136.0,-0.50,0.46,4.91,AR,ATH,MISC

In [11]:
# bottom 5 today
df_tmp = df_portfolio_features.sort_values(by = 'Today P/L%', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
55,RAJESHEXPO,-4.97,-77.03,335.70,0.07,105766.0,-105671.0,31506.0,518.0,1055.30,19.0,L-SC,13.73,268.0,-1.00,0.24,0.00,OX40N,NTT,JEWELLERY
41,INDIGOPNTS,-2.98,-37.95,61.19,0.02,66277.0,-66245.0,108314.0,1408.0,65.18,18.0,M-SC,14.18,222.0,-1.00,0.82,0.00,OX40N,NTT,PAINTS
77,TTKPRESTIG,-2.75,-39.05,64.21,0.09,39442.0,-39351.0,61426.0,770.0,42.58,19.0,M-SC,13.49,250.0,-1.00,0.46,0.00,OX40N,NTT,DURABLES
69,SURYODAY,-2.31,-26.38,67.12,23.03,88488.0,-47236.0,131835.0,216.0,44.74,50.0,H-SC,6.96,166.0,-0.53,0.99,30.81,XR,NTT,BANKS
5,ANGELONE,-2.28,-10.02,38.00,24.18,104291.0,-30550.0,274450.0,303.0,-86.88,30.0,X-SC,2.78,97.0,-0.29,2.07,14.94,X40N,NTT,FINANCE

In [12]:
# top 5 to exit based on CumlRnk
df_tmp = df_portfolio_features[~df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])]
df_tmp = df_tmp[(df_tmp['Current P/L%'] > -1) & (df_tmp['Current P/L%'] < 1)].sort_values(by = 'CumlRnk', ascending=False)
df_tmp[cols].head()

Empty DataFrame
Columns: [Symbol, Today P/L%, Current P/L%, FTT%, OTT%, FTT Amt, Current P/L, Current, FTT, Dev%_PE, RSI_14, Conviction, Spread%, CumlRnk, RRR Ind, CurrAlloc%, Gained%, Criteria, Strategy, Category]
Index: []

In [13]:
# OX40N stocks to exit
df_tmp = df_portfolio_features[(df_portfolio_features['Symbol'].isin(list_ox40n))].sort_values(by = 'Current P/L%', ascending=False)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
27,FINCABLES,5.54,22.71,69.43,107.91,125790.0,33531.0,181175.0,1641.55,10.60,72.0,M-SC,6.53,220.0,0.27,1.36,36.30,OX40N,ATH,CABLES
66,SIS,0.91,-31.58,77.24,21.26,58675.0,-35068.0,75964.0,528.00,1782.38,38.0,H-SC,7.55,168.0,-0.60,0.57,4.72,OX40N,NTT,MISC
48,KANSAINER,-2.17,-36.86,79.71,13.47,135723.0,-99396.0,170271.0,340.00,-45.81,26.0,H-SC,14.98,162.0,-0.73,1.28,0.00,XY24,NTT,PAINTS
72,TATAELXSI,-1.59,-37.59,111.56,32.03,91785.0,-49561.0,82274.0,9161.00,-21.88,27.0,H-SC,14.49,158.0,-0.54,0.62,0.00,OX40N,NTT,IT
41,INDIGOPNTS,-2.98,-37.95,61.19,0.02,66277.0,-66245.0,108314.0,1408.00,65.18,18.0,M-SC,14.18,222.0,-1.00,0.82,0.00,OX40N,NTT,PAINTS

In [14]:
# top 5 to book for rotation
df_tmp = df_portfolio_features[(df_portfolio_features['Current P/L%'] > 20) ].sort_values(by = 'CumlRnk', ascending=False)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
27,FINCABLES,5.54,22.71,69.43,107.91,125790.0,33531.0,181175.0,1641.55,10.6,72.0,M-SC,6.53,220.0,0.27,1.36,36.3,OX40N,ATH,CABLES

In [15]:
# top 5 to monitor for exit
df_tmp = df_portfolio_features[~df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])]
df_tmp = df_tmp[(df_tmp['Current P/L%'] > 0) ].sort_values(by = 'Dev%_PE', ascending=False)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
19,COALINDIA,-1.99,8.31,8.64,17.67,14080.0,12506.0,162966.0,478.51,30.56,58.0,L-LC,11.17,185.0,0.89,1.23,26.56,XY25,ATH,MINING
27,FINCABLES,5.54,22.71,69.43,107.91,125790.0,33531.0,181175.0,1641.55,10.60,72.0,M-SC,6.53,220.0,0.27,1.36,36.30,OX40N,ATH,CABLES
1,ABB,2.24,11.22,30.88,45.57,89853.0,29357.0,290976.0,7934.00,-28.55,61.0,H-MC,9.23,125.0,0.33,2.19,29.21,AR,NTT,ELECTRICAL

In [16]:
# top 5 to book for rotation from weak conviction
df_tmp = df_portfolio_features[~df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])]
df_tmp = df_tmp[~df_tmp['Criteria'].isin(['XY25','XY24','X40', 'X40N'])].sort_values(by = 'RRR Ind', ascending=False)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
1,ABB,2.24,11.22,30.88,45.57,89853.0,29357.0,290976.0,7934.00,-28.55,61.0,H-MC,9.23,125.0,0.33,2.19,29.21,AR,NTT,ELECTRICAL
27,FINCABLES,5.54,22.71,69.43,107.91,125790.0,33531.0,181175.0,1641.55,10.60,72.0,M-SC,6.53,220.0,0.27,1.36,36.30,OX40N,ATH,CABLES
40,INDIAMART,2.13,-8.87,126.85,106.72,142569.0,-10944.0,112392.0,4810.62,-58.98,41.0,H-SC,8.76,140.0,-0.08,0.85,12.43,AR,ATH,MISC
85,ZYDUSLIFE,-0.17,-3.72,40.87,35.63,82469.0,-7790.0,201784.0,1286.17,-16.22,52.0,H-MC,5.09,120.0,-0.09,1.52,12.34,AR,ATH,PHARMA
67,SONACOMS,0.78,-10.92,56.14,39.09,50591.0,-11043.0,90116.0,804.02,-29.38,49.0,M-MC,10.61,193.0,-0.22,0.68,27.48,AR,ATH,AUTO

In [17]:
# top 5 to accumulate based on lowest RSI_14
df_tmp = df_portfolio_features[df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])].sort_values(by = 'RSI_14', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
8,AWL,-0.89,-42.56,173.64,57.19,325302.0,-138784.0,187343.0,485.00,-67.16,12.0,X-SC,21.05,81.0,-0.43,1.41,0.00,XY24,NTT,FMCG
53,PGHH,-2.10,-18.43,61.85,32.01,107718.0,-39360.0,174160.0,17616.87,-44.85,17.0,X-MC,10.20,57.0,-0.37,1.31,0.00,X40,ATH,FMCG
3,ACC,-1.47,-36.91,160.19,64.15,240477.0,-87831.0,150120.0,3906.00,-52.53,21.0,X-SC,10.67,85.0,-0.37,1.13,0.00,XY24,BTT,CEMENT
12,BATAINDIA,0.07,-52.02,181.82,35.20,112239.0,-66939.0,61731.0,2096.00,-19.13,24.0,X-SC,23.72,91.0,-0.60,0.47,1.54,X40,NTT,FOOTWEAR
58,RELAXO,-0.36,-58.32,265.44,52.31,160586.0,-84662.0,60498.0,1176.00,-55.67,24.0,X-SC,16.89,92.0,-0.53,0.46,0.00,X40N,NTT,FOOTWEAR

In [18]:
# top 5 to accumulate based on Spread and CumlRnk
df_tmp = df_portfolio_features[df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])]
df_tmp = df_tmp[(df_tmp['CumlRnk'] < 100)].sort_values(by = 'Spread%', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
22,DABUR,-1.91,-6.43,53.57,43.70,124347.0,-15947.0,232121.0,735.00,-15.04,31.0,X-MC,1.06,70.0,-0.13,1.75,7.65,XY24,BTT,FMCG
37,ICICIGI,0.27,-0.40,19.82,19.34,39504.0,-797.0,199312.0,2252.93,-16.16,46.0,X-MC,1.46,66.0,-0.02,1.50,13.67,X40,ATH,INSURANCE
78,UNITDSPR,4.83,2.09,18.29,20.77,43722.0,4902.0,239046.0,1644.00,-9.40,52.0,X-MC,1.50,64.0,0.11,1.80,8.94,X40N,NTT,BREWERIES
59,RELIANCE,1.11,-9.82,38.95,25.30,70585.0,-19744.0,181219.0,1952.00,-12.34,47.0,X-LC,2.06,21.0,-0.28,1.37,20.99,XY25,BTT,REFINERIES
5,ANGELONE,-2.28,-10.02,38.00,24.18,104291.0,-30550.0,274450.0,303.00,-86.88,30.0,X-SC,2.78,97.0,-0.29,2.07,14.94,X40N,NTT,FINANCE

In [19]:
# top 5 to accumulate based on lowest Gained%
df_tmp = df_portfolio_features[df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])].sort_values(by = 'Gained%', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
3,ACC,-1.47,-36.91,160.19,64.15,240477.0,-87831.0,150120.0,3906.00,-52.53,21.0,X-SC,10.67,85.0,-0.37,1.13,0.0,XY24,BTT,CEMENT
10,BAJAJHLDNG,-0.97,-5.58,36.85,29.22,66153.0,-10605.0,179520.0,14451.52,-12.59,37.0,X-LC,11.85,28.0,-0.16,1.35,0.0,X40,ATH,FINANCE
9,BAJAJHFL,-0.58,-27.93,115.71,55.47,202895.0,-67938.0,175348.0,181.50,-38.22,26.0,X-MC,17.63,60.0,-0.33,1.32,0.0,X40N,ATH,FINANCE
8,AWL,-0.89,-42.56,173.64,57.19,325302.0,-138784.0,187343.0,485.00,-67.16,12.0,X-SC,21.05,81.0,-0.43,1.41,0.0,XY24,NTT,FMCG
24,DIXON,-1.91,-30.47,88.77,31.26,142444.0,-70304.0,160464.0,18931.72,-68.95,35.0,X-MC,24.77,54.0,-0.49,1.21,0.0,X40N,ATH,IT

In [20]:
# top 5 to accumulate based on lowest CurrAlloc%
df_tmp = df_portfolio_features[df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])].sort_values(by = 'CurrAlloc%', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
54,QUESS,-0.89,-36.07,123.43,42.84,51298.0,-23446.0,41560.0,424.00,-58.13,36.0,X-SC,17.16,80.0,-0.46,0.31,0.75,XY24,NTT,MISC
58,RELAXO,-0.36,-58.32,265.44,52.31,160586.0,-84662.0,60498.0,1176.00,-55.67,24.0,X-SC,16.89,92.0,-0.53,0.46,0.00,X40N,NTT,FOOTWEAR
12,BATAINDIA,0.07,-52.02,181.82,35.20,112239.0,-66939.0,61731.0,2096.00,-19.13,24.0,X-SC,23.72,91.0,-0.60,0.47,1.54,X40,NTT,FOOTWEAR
51,MEDANTA,-0.14,-7.31,33.86,24.08,39843.0,-9279.0,117671.0,1486.00,-7.89,44.0,X-SC,8.17,87.0,-0.23,0.89,7.78,XY24,NTT,HEALTHCARE
36,HONAUT,0.07,-26.41,94.75,43.32,113567.0,-43012.0,119860.0,58357.33,-35.45,31.0,X-SC,13.11,90.0,-0.38,0.90,0.07,X40N,ATH,ELECTRICAL

In [21]:
# top 5 to accumulate based on CumlRnk
df_tmp = df_portfolio_features.sort_values(by = 'CumlRnk', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
45,ITC,-0.58,-18.42,45.95,19.06,127507.0,-62675.0,277491.0,452.00,-55.12,36.0,X-LC,16.71,1.0,-0.49,2.09,0.47,X40,NTT,FMCG
73,TCS,-0.82,-26.69,68.58,23.58,217496.0,-115487.0,317142.0,4311.59,-36.41,26.0,X-LC,11.97,2.0,-0.53,2.39,0.00,X40,ATH,IT
43,INFY,0.20,-10.93,50.72,34.24,141351.0,-34199.0,278689.0,1972.00,-29.97,29.0,X-LC,10.58,3.0,-0.24,2.10,2.58,X40,NTT,IT
75,TMPV,-1.24,-22.06,71.06,33.33,180452.0,-71857.0,253943.0,600.00,-83.62,38.0,X-LC,3.01,4.0,-0.40,1.91,3.82,XY24,NTT,AUTO
34,HCLTECH,0.19,-11.96,40.65,23.83,86585.0,-28922.0,213002.0,1908.19,-7.36,27.0,X-LC,8.32,8.0,-0.33,1.60,2.19,X40,ATH,IT

In [22]:
# top 5 for average up
df_tmp = df_portfolio_features[(df_portfolio_features['Dev%_200'] > 5)].sort_values(by = 'CurrAlloc%', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
42,INDUSINDBK,-2.07,-32.24,96.11,32.89,50282.0,-24890.0,52317.0,1800.00,-346.50,47.0,L-MC,12.03,258.0,-0.50,0.39,44.08,XR,NTT,BANKS
67,SONACOMS,0.78,-10.92,56.14,39.09,50591.0,-11043.0,90116.0,804.02,-29.38,49.0,M-MC,10.61,193.0,-0.22,0.68,27.48,AR,ATH,AUTO
19,COALINDIA,-1.99,8.31,8.64,17.67,14080.0,12506.0,162966.0,478.51,30.56,58.0,L-LC,11.17,185.0,0.89,1.23,26.56,XY25,ATH,MINING
27,FINCABLES,5.54,22.71,69.43,107.91,125790.0,33531.0,181175.0,1641.55,10.60,72.0,M-SC,6.53,220.0,0.27,1.36,36.30,OX40N,ATH,CABLES
82,VOLTAS,-0.46,15.66,25.54,45.20,56638.0,30018.0,221760.0,1856.00,32.38,50.0,X-MC,10.08,79.0,0.53,1.67,23.52,XY25,NTT,AC

In [23]:
# top 5 RSP
df_tmp = df_portfolio_features.sort_values(by = 'RSP', ascending=False)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
27,FINCABLES,5.54,22.71,69.43,107.91,125790.0,33531.0,181175.0,1641.55,10.60,72.0,M-SC,6.53,220.0,0.27,1.36,36.30,OX40N,ATH,CABLES
11,BANDHANBNK,-1.08,-11.95,118.54,92.42,290731.0,-33299.0,245260.0,400.00,110.49,66.0,H-SC,9.71,174.0,-0.11,1.85,35.11,XY24,NTT,BANKS
26,EASEMYTRIP,-1.19,-58.66,252.47,45.70,184523.0,-103728.0,73087.0,26.40,-24.14,45.0,M-SC,18.08,204.0,-0.56,0.55,20.42,XY24,NTT,TRAVEL
83,WHIRLPOOL,-1.35,-28.15,153.21,81.92,126365.0,-32320.0,82478.0,2270.00,-57.90,51.0,M-SC,25.76,210.0,-0.26,0.62,15.86,XR,NTT,DURABLES
1,ABB,2.24,11.22,30.88,45.57,89853.0,29357.0,290976.0,7934.00,-28.55,61.0,H-MC,9.23,125.0,0.33,2.19,29.21,AR,NTT,ELECTRICAL

In [24]:
# Top N allocation
df_tmp = df_portfolio_features.sort_values(by = 'CurrAlloc%', ascending=False)
top_n_values = [10, 25, 50]

sum_df = pd.DataFrame({
    'Top_N': top_n_values,
    'Sum_Alloc%': [df_tmp['CurrAlloc%'].head(n).sum() for n in top_n_values]
})

sum_df

   Top_N  Sum_Alloc%
0     10       20.76
1     25       45.66
2     50       77.81

In [25]:
# market-cap-wise allocation
df_tmp = df_portfolio_features[cols]
df_tmp.groupby(df_tmp['Conviction'].str[-2:])['CurrAlloc%'].sum().sort_values(ascending=False)

Conviction
SC    44.58
MC    30.47
LC    24.93
Name: CurrAlloc%, dtype: float64

In [26]:
# criteria-wise allocation
df_portfolio_features.groupby('Criteria')['CurrAlloc%'].sum().sort_values(ascending=False)

Criteria
XY24     26.54
X40      23.98
X40N     14.80
AR        9.28
XY25      9.02
XR        8.41
OX40N     7.14
SR        0.81
Name: CurrAlloc%, dtype: float64

In [27]:
# conviction-wise allocation
df_portfolio_features.groupby('Conviction')['CurrAlloc%'].sum().sort_values(ascending=False)

Conviction
X-MC    22.92
H-SC    22.26
X-LC    21.45
X-SC    11.08
M-SC    10.61
H-MC     5.07
M-MC     2.09
H-LC     1.23
L-LC     1.23
M-LC     1.02
L-SC     0.63
L-MC     0.39
Name: CurrAlloc%, dtype: float64

In [28]:
# sector-wise stats
df_tmp = df_portfolio_features.groupby('Category')[['CurrAlloc%', 'Current', 'Current P/L', 'FTT Amt']].sum().sort_values(by=['Current', 'Current P/L'], ascending=False)
df_tmp['Current P/L%'] = round(df_tmp['Current P/L'] * 100 / df_tmp['Current'], 2)
df_tmp['FTT%'] = round(df_tmp['FTT Amt'] * 100 / df_tmp['Current'], 2)
cols = ['CurrAlloc%', 'Current P/L%', 'FTT%']
df_tmp[cols].sort_values(by=['CurrAlloc%'], ascending=False)

               CurrAlloc%  Current P/L%    FTT%
Category
FMCG                15.63        -18.91   59.13
FINANCE             12.76        -23.36   71.90
IT                  11.45        -44.11  116.33
MISC                 6.80        -43.75  102.55
ELECTRICAL           6.45         -9.44   49.37
PAINTS               4.95        -40.43   61.29
INSURANCE            4.89         -4.49   40.24
PHARMA               4.28         -3.63   36.26
AUTO                 3.73        -25.97   74.00
BANKS                3.23        -24.55  100.02
AC                   2.23         -7.81   37.04
FOOTWEAR             1.98        -69.10  136.90
TRAVEL               1.91        -76.60  165.02
DURABLES             1.82        -59.28   98.03
BREWERIES            1.80          2.05   18.29
HEALTHCARE           1.67        -38.86   73.13
REALTY               1.53         -9.28   27.23
APPARELS             1.43        -25.05   62.74
CERAMICS             1.40        -64.69  114.72
REFINERIES           1.37        -10.90   38.95
CABLES               1.36         18.51   69.43
MINING               1.23          7.67    8.64
ENGINEERING          1.17        -56.13  127.55
JEWELLERY            1.16       -108.25  180.61
CEMENT               1.13        -58.51  160.19
CHEMICALS            1.00       -100.12  263.38
ENTERTAINMENT        0.79        -85.06  195.44
TEXTILES             0.44        -57.66  102.62
HOTELS               0.39       -118.15  195.09

In [29]:
# money to be made criteria-wise
df_portfolio_features.groupby('Criteria')['FTT Amt'].agg(['sum', 'count']).sort_values(by='sum', ascending=False)

                sum  count
Criteria
XY24      3604639.0     21
X40       1538215.0     15
XR        1372189.0     12
AR        1340086.0     10
X40N      1156005.0     10
OX40N      842730.0     10
XY25       421927.0      6
SR         311470.0      2

In [30]:
# money to be made conviction-wise
df_portfolio_features.groupby('Conviction')['FTT Amt'].agg(['sum', 'count']).sort_values(by='sum', ascending=False)

                  sum  count
Conviction
H-SC        3836779.0     24
M-SC        1508338.0     14
X-MC        1471118.0     15
X-LC        1424506.0     12
X-SC        1333447.0     10
H-MC         405806.0      3
L-SC         207312.0      2
M-LC         156092.0      1
M-MC         109367.0      2
H-LC          70134.0      1
L-MC          50282.0      1
L-LC          14080.0      1

In [31]:
# money to be made criteria and conviction-wise
df_portfolio_features.groupby(['Conviction', 'Criteria'])['FTT Amt'].agg(['sum', 'count']).sort_values(by='sum', ascending=False)

                           sum  count
Conviction Criteria
H-SC       XY24      1297066.0      6
           AR         970287.0      5
M-SC       XY24       888309.0      6
H-SC       XR         877857.0      7
X-LC       X40        743001.0      6
X-SC       XY24       656920.0      4
X-MC       X40        596504.0      7
X-SC       X40N       477817.0      4
X-MC       X40N       444323.0      4
H-SC       OX40N      380099.0      4
M-SC       OX40N      356865.0      5
H-SC       SR         311470.0      2
X-LC       XY24       307435.0      2
           X40N       233865.0      2
H-MC       XY24       233484.0      1
X-MC       XY24       221425.0      2
           XY25       208866.0      2
X-SC       X40        198710.0      2
M-SC       XR         186412.0      2
H-MC       AR         172322.0      2
M-LC       XR         156092.0      1
X-LC       XY25       140205.0      2
L-SC       OX40N      105766.0      1
           XR         101546.0      1
M-SC       AR          76752.0      1
H-LC       AR          70134.0      1
M-MC       XY25        58776.0      1
           AR          50591.0      1
L-MC       XR          50282.0      1
L-LC       XY25        14080.0      1

In [32]:
# notebook execution time

end_time = time.time()
execution_time = round(end_time - start_time, 0)
print(f"Notebook execution time: {execution_time} seconds")

Notebook execution time: 39.0 seconds