<a href="https://colab.research.google.com/github/ankit-rathi/Quantvesting_v2/blob/main/myStocks_Portfolio_Analysis.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
'''
!pip install pandas==2.2.2 -qq
!pip install pyxirr -qq
!pip install ta -qq
!pip install yfinance==0.2.59 -qq
'''

'\n!pip install pandas==2.2.2 -qq\n!pip install pyxirr -qq\n!pip install ta -qq\n!pip install yfinance==0.2.59 -qq\n'

In [2]:
# import libraries

import numpy as np
import pandas as pd
import datetime
import warnings
warnings.filterwarnings('ignore')
import yfinance as yfin
import ta
import matplotlib.pyplot as plt
import requests

In [3]:
# notebook start time
import time
import datetime
import pytz

start_time = time.time()

# function to print date timestamp
def print_date_time():
  tz_NY = pytz.timezone('Asia/Kolkata')
  datetime_NY = datetime.datetime.now(tz_NY)
  print("Run date time (IST):", datetime_NY.strftime("%Y-%m-%d %H:%M:%S"))

In [4]:
# function to get booked and reserved amount
def get_amt():
  # fetch the JSON data from the URL
  url = "https://raw.githubusercontent.com/ankit-rathi/Tradevesting_v1/main/data/myPortfolioAmts.json"
  response = requests.get(url)
  pf_amts = response.json()  # parse the JSON data

  # extract values from the JSON
  py_booked_amt_dm = pf_amts["py_booked_amt_dm"]
  py_booked_amt_sv = pf_amts["py_booked_amt_sv"]
  cy_booked_amt_dm = pf_amts["cy_booked_amt_dm"]
  cy_booked_amt_sv = pf_amts["cy_booked_amt_sv"]
  reserve_amt_dm = pf_amts["reserve_amt_dm"]
  reserve_amt_sv = pf_amts["reserve_amt_sv"]

  # perform calculations
  py_booked_amt = py_booked_amt_dm + py_booked_amt_sv
  cy_booked_amt = cy_booked_amt_dm + cy_booked_amt_sv
  reserve_amt = reserve_amt_dm + reserve_amt_sv
  total_booked_amt = py_booked_amt + cy_booked_amt

  return total_booked_amt, reserve_amt, cy_booked_amt, py_booked_amt

gen_output = 0

In [5]:
# function to format the amount
def format_amt(number):
    abs_number = abs(number)

    if abs_number >= 1_00_00_000:  # Crores
        formatted_amt = f"{number / 1_00_00_000:.2f} C"
    elif abs_number >= 1_00_000:  # Lakhs
        formatted_amt = f"{number / 1_00_000:.2f} L"
    elif abs_number >= 1_000:  # Thousands
        formatted_amt = f"{number / 1_000:.2f} K"
    else:
        formatted_amt = f"{number:.2f}"

    return formatted_amt

# function to set start and end date
def get_start_end_date():
  start_date = (datetime.date.today() + datetime.timedelta(days=-365)).strftime('%Y-%m-%d')
  end_date = (datetime.date.today() + datetime.timedelta(days=1)).strftime('%Y-%m-%d')
  return start_date, end_date

# function to fetch my portfolio csv
def get_mypfs_df():
  mypfs_df = pd.read_csv('https://raw.githubusercontent.com/ankit-rathi/Tradevesting_v1/main/data/myPortfolioStocks.csv')
  return mypfs_df

# function to fetch my prospects csv
def get_mypps_df():
  mypps_df = pd.read_csv('https://raw.githubusercontent.com/ankit-rathi/Tradevesting_v1/main/data/myProspectsScrips.csv')
  return mypps_df

# function to fetch screener data
def get_myscreen_df():
  myscreen_df = pd.read_csv('https://raw.githubusercontent.com/ankit-rathi/Tradevesting_v1/main/data/myScreenerDB.csv')
  return myscreen_df

# function to fetch momentum data
def get_myinvmt_df():
  myinvmt_df = pd.read_csv('https://raw.githubusercontent.com/ankit-rathi/Tradevesting_v1/main/data/myInvestments.csv')
  return myinvmt_df

# function to get the stock ids
def get_stock_ids(df_pf):
  stock_n100 = df_pf['Symbol'].unique()

  exclude = ['CADILAHC','MMTC', 'MASFIN']

  stock_ids = df_pf[~df_pf['Symbol'].isin(exclude) ]['Symbol'].unique()

  #mypf = mypf[mypf.Forecast.notnull()]
  #stock_ids = mypf['Symbol'].unique()

  #stock_ids.sort()
  return stock_ids

# get features from screener data
def get_screener_features():
  myscreen_df = get_myscreen_df()
  cols = ['Symbol', 'EPS', 'MedPE', 'ROCE%', 'ROE%', 'CapType']
  return myscreen_df[cols]

# get relative strength
def get_relative_strength(stock_list):

    # Dictionary to store stock tickers and their corresponding percentage price change
    stock_changes = {}

    # Loop through each stock and fetch its price data
    for stock in stock_list:
        try:
            # Download the stock data for the given date range
            stock_data = yfin.Ticker(stock + '.NS').history(period='1mo', interval='1d')[map(str.title, ['open', 'close', 'low', 'high', 'volume'])]

            # Calculate the percentage change for the stock
            if len(stock_data) > 0:
                start_price = stock_data['Close'].iloc[0]
                end_price = stock_data['Close'].iloc[-1]
                percent_change = round(((end_price - start_price) / start_price) * 100, 2)
                stock_changes[stock] = percent_change
            else:
                stock_changes[stock] = np.nan  # If no data is available, set to NaN

        except Exception as e:
            print(f"Error fetching data for {stock}: {e}")
            stock_changes[stock] = np.nan

    # Create a DataFrame with stock tickers and their percentage changes
    df = pd.DataFrame(list(stock_changes.items()), columns=['Symbol', 'Percent_Change'])

    # Drop any stocks with missing data (NaN values)
    df = df.dropna()

    # Calculate the percentile rank based on percentage change
    df['RSP'] = round(df['Percent_Change'].rank(pct=True) * 100, 2)
    cols = ['Symbol', 'RSP']
    df = df[cols]
    # Sort by percentile rank (optional)
    df = df.sort_values(by='RSP', ascending=False).reset_index(drop=True)

    return df

In [6]:
# function to get stock technicals
def stock_prec_dev(stock_symbol):
    #stock_symbol = 'ULTRACEMCO.NS'
    short_window = 20
    mid_window = 50
    long_window = 200
    moving_avg = 'SMA'

    start = datetime.datetime(*map(int, start_date.split('-')))
    end = datetime.datetime(*map(int, end_date.split('-')))

    stock_df = yfin.Ticker(stock_symbol + '.NS').history(period='max', interval='1d')[map(str.title, ['open', 'close', 'low', 'high', 'volume'])]

    stock_df['Max'] = round(max(stock_df['Close']),2)
    stock_df = stock_df[(stock_df.index <= end_date) & (stock_df.index >= start_date)]
    stock_df['200_SMA'] = round(stock_df['Close'].rolling(window = 200, min_periods = 1).mean(),0)
    stock_df['Dev%_200'] = round((stock_df['Close'] - stock_df['200_SMA'])*100/stock_df['200_SMA'],2)
    stock_df.dropna(axis = 0, inplace = True) # remove any null rows

    stock_df['20_SMA'] = stock_df['Close'].rolling(window=20).mean()
    stock_df['50_SMA'] = stock_df['Close'].rolling(window=50).mean()
    stock_df['Symbol'] = stock_symbol

    stock_df['Close'] = round(stock_df['Close'],2)
    stock_df['Min'] = round(min(stock_df['Close']),2)
    stock_df['RSI_14'] = ta.momentum.RSIIndicator(close=stock_df['Close'], window=14).rsi()
    stock_df['RSI_14'] = round(stock_df['RSI_14'],0)
    stock_df['Prev_Close'] = stock_df['Close'].shift(1)
    stock_df.drop(['Open', 'Low', 'High', 'Volume'], axis=1, inplace=True)
    stock_df = stock_df.tail(1)

    max_SMA = max(stock_df['20_SMA'].item(), stock_df['50_SMA'].item(), stock_df['200_SMA'].item())
    min_SMA = min(stock_df['20_SMA'].item(), stock_df['50_SMA'].item(), stock_df['200_SMA'].item())
    ABS_Spread = max_SMA - min_SMA
    stock_df['Spread%'] = round((ABS_Spread / stock_df['200_SMA'].item()) * 100,2)

    return stock_df

# function to compute stock attributes
def get_common_features(stock_ids, df_mypf):

  df_prec_dev = pd.DataFrame()
  df_tmp = get_screener_features()
  df_rs = get_relative_strength(stock_ids)

  for stock_id in stock_ids:
      tmp = stock_prec_dev(stock_id)
      tmp = tmp.reset_index()
      df_prec_dev = pd.concat([df_prec_dev, tmp], ignore_index = True)
  df_prec_dev = pd.merge(df_prec_dev, df_mypf, on= 'Symbol')
  df_prec_dev = pd.merge(df_prec_dev, df_tmp, on= 'Symbol', how='left')
  df_prec_dev = pd.merge(df_prec_dev, df_rs, on= 'Symbol', how='left')
  #print(df_prec_dev.columns)
  df_prec_dev['Curr_PE'] = round(df_prec_dev['Close']/df_prec_dev['EPS'],1)
  df_prec_dev['Dev%_PE'] = round((df_prec_dev['Curr_PE'] - df_prec_dev['MedPE'])*100/df_prec_dev['MedPE'],2)
  df_prec_dev['Conviction'] = df_prec_dev['Conviction'] + '-' + df_prec_dev['CapType']
  return df_prec_dev

# function to arrange stock features
def arrange_features(df_stocks, common_cols, diff_cols):
  df_stocks_common = df_stocks[common_cols].drop_duplicates()
  df_stocks_diff = df_stocks[diff_cols]
  df_stocks_diff['Investment'] = df_stocks_diff['AvgCost'] * df_stocks_diff['Shares']
  df_stocks_diff = df_stocks_diff.groupby(['Symbol'])[['Shares', 'Investment']].aggregate(['sum']).reset_index()
  df_stocks_diff.columns = ['Symbol', 'Shares', 'Investment']
  df_stocks_diff['AvgCost'] = round(df_stocks_diff['Investment']/df_stocks_diff['Shares'],2)
  df_stocks = pd.merge(df_stocks_diff, df_stocks_common, on='Symbol')
  return df_stocks

# plot fact distribution across dimension
def plot_pie_chart(df, dimension, fact):
  # grouping the data by category and calculating the sum of fact for each type
  grouped_data = df.groupby(dimension)[fact].sum()

  # sorting the grouped data in descending order
  grouped_data = grouped_data.sort_values(ascending=False)

  # creating a pie chart
  grouped_data.plot.pie(autopct='%1.1f%%', startangle=90, figsize=(6, 6))

  # adding a title and displaying the plot
  plt.title(f'{dimension} {fact} Distribution')
  plt.ylabel('')  # To hide the y-label
  plt.show()

In [7]:
# function to get portfolio features

def get_portfolio_features(df_common_features):

  print_date_time()
  print('-------------------')

  #df_common_features["Target"] = df_common_features["Target"].fillna(df_common_features["Max"])
  df_common_features['NTT'] = np.where(df_common_features['Strategy']== 'NTT', df_common_features["Target"], df_common_features['Max'])
  df_common_features['LTT'] = np.where(df_common_features['Strategy']== 'BTT', df_common_features["Target"], df_common_features['Max'])
  df_common_features['BOL'] = df_common_features['Min']

  tmp_df = df_common_features[df_common_features['Symbol'].isin(mypf_df[mypf_df['InPortfolio'] != 'NA'].Symbol.values)]
  print('qualified stocks: '+str(len(tmp_df['Symbol'].unique())))
  tmp_df1 = tmp_df[tmp_df['LatestQtr'] == 1]
  print('with latest results: '+str(len(tmp_df1['Symbol'].unique())))
  tmp_df1 = tmp_df1[tmp_df1['StarStock'] == 1]
  print('still star stocks: '+str(len(tmp_df1['Symbol'].unique())))
  tmp_df['Investment'] = tmp_df['AvgCost'] * tmp_df['Shares']
  tmp_df['Current'] = round(tmp_df['Close'] * tmp_df['Shares'],0)
  tmp_df['Previous'] = tmp_df['Prev_Close'] * tmp_df['Shares']
  tmp_df['EstimatedST'] = tmp_df['NTT'] * tmp_df['Shares']
  tmp_df['EstimatedLT'] = tmp_df['LTT'] * tmp_df['Shares']
  tmp_df['Current P/L'] = round((tmp_df['Current'] - tmp_df['Investment']),0)
  tmp_df['Today P/L%'] = round((tmp_df['Current'] - tmp_df['Previous'])*100/tmp_df['Previous'],2)
  tmp_df['Current P/L%'] = round((tmp_df['Current'] - tmp_df['Investment'])*100/tmp_df['Investment'],2)
  tmp_df['EstimatedST P/L%'] = round((tmp_df['EstimatedST'] - tmp_df['Investment'])*100/tmp_df['Investment'],2)
  tmp_df['EstimatedLT P/L%'] = round((tmp_df['EstimatedLT'] - tmp_df['Investment'])*100/tmp_df['Investment'],2)
  tmp_df['NTT%'] = round((tmp_df['NTT'] - tmp_df['Close'])*100/tmp_df['Close'],2)
  tmp_df['LTT%'] = round((tmp_df['LTT'] - tmp_df['Close'])*100/tmp_df['Close'],2)
  tmp_df['Gained%'] = round((tmp_df['Close'] - tmp_df['BOL'])*100/tmp_df['BOL'],2)
  investment = round(sum(tmp_df['AvgCost']*tmp_df['Shares']),0)
  current = round(sum(tmp_df['Close']*tmp_df['Shares']),0)
  tmp_df['InitAlloc%'] = round(tmp_df['Investment']*100/investment,2)
  tmp_df['CurrAlloc%'] = round(tmp_df['Current']*100/current,2)
  tmp_df['FTT'] = tmp_df['LTT']
  tmp_df.loc[tmp_df['Strategy'] == 'NTT', 'FTT'] = tmp_df['NTT']
  tmp_df['FTT%'] = tmp_df['LTT%']
  tmp_df.loc[tmp_df['Strategy'] == 'NTT', 'FTT%'] = tmp_df['NTT%']
  tmp_df['FTT Amt'] = round(tmp_df['FTT%'] * tmp_df['Current']/100,0)
  tmp_df['OTT%'] = round((tmp_df['FTT'] - tmp_df['AvgCost'])*100/tmp_df['AvgCost'],2)
  tmp_df['RRR Ind'] = round(tmp_df['Current P/L']/tmp_df['FTT Amt'],2)
  tmp_df['Risk Ind'] = round(tmp_df['Current P/L%']*tmp_df['CurrAlloc%'],0)

  return tmp_df

# function to print portfolio features
def print_portfolio_stats(df_portfolio_features, myinvmt_df):
  from pyxirr import xirr

  total_booked_amt, reserve_amt, cy_booked_amt, py_booked_amt = get_amt()

  dates = myinvmt_df['Date'].values
  dates = np.append(dates, datetime.date.today().strftime('%d-%b-%y'))
  investment = myinvmt_df['Investment'].values
  dates= pd.to_datetime(dates)

  current = round(sum(df_portfolio_features['Close']*df_portfolio_features['Shares']),0) + reserve_amt
  investment_xirr = np.append(investment, current)
  cagr = round(xirr(pd.DataFrame({"dates": dates, "amounts": investment_xirr}))*100,2)

  investment = -sum(investment)
  invested = round(sum(df_portfolio_features['AvgCost']*df_portfolio_features['Shares']),0) + reserve_amt
  previous = round(sum(df_portfolio_features['Prev_Close']*df_portfolio_features['Shares']),0) + reserve_amt
  cy_invested = investment + py_booked_amt

  today_pnl_amount = current-previous
  today_pnl_percentage = round((current-previous)*100/previous,2)

  curr_pnl_amount = current-invested
  curr_pnl_percentage = round((curr_pnl_amount)*100/(cy_invested),2)

  cy_pnl_amount = cy_booked_amt + curr_pnl_amount
  cy_pnl_percentage = round((cy_pnl_amount)*100/cy_invested,2)

  overall_pnl_amount = total_booked_amt + curr_pnl_amount
  overall_pnl_percentage = round((overall_pnl_amount)*100/investment,2)

  estimate_st = round(sum(df_portfolio_features['FTT']*df_portfolio_features['Shares']),0)  + reserve_amt
  est_st_pnl_amount = estimate_st-current
  est_st_pnl_percentage = round((est_st_pnl_amount)*100/current,2)

  estimate_lt = round(sum(df_portfolio_features['LTT']*df_portfolio_features['Shares']),0)  + reserve_amt
  est_lt_pnl_amount = estimate_lt-current
  est_lt_pnl_percentage = round((est_lt_pnl_amount)*100/current,2)

  total_profit = round(sum(df_portfolio_features[df_portfolio_features['Current P/L%'] > 0]['Current']) - sum(df_portfolio_features[df_portfolio_features['Current P/L%'] > 0]['Investment']),0)
  total_loss = round(sum(df_portfolio_features[df_portfolio_features['Current P/L%'] < 0]['Current']) - sum(df_portfolio_features[df_portfolio_features['Current P/L%'] < 0]['Investment']),0)

  cy_booked_percentage = round((cy_booked_amt)*100/current,2)
  py_booked_percentage = round((py_booked_amt)*100/investment,2)
  total_booked_percentage = round((total_booked_amt)*100/investment,2)

  print('-------------------')
  print('Initial Investment: ', format_amt(investment))
  print('CY Investment: ', format_amt(cy_invested))
  print('Reserve: ', format_amt(reserve_amt))
  print('Current: ',  format_amt(current))
  print('-------------------')
  print('Today PnL: '+ '{} ({}%)'.format(format_amt(today_pnl_amount), today_pnl_percentage))
  print('Current PnL: '+ '{} ({}%)'.format(format_amt(curr_pnl_amount), curr_pnl_percentage))
  print('CY Booked + Current PnL: '+ '{} ({}%)'.format(format_amt(cy_pnl_amount), cy_pnl_percentage))
  print('-------------------')
  print('Total profit: ', format_amt(total_profit))
  print('Total loss: ', format_amt(total_loss))
  print('-------------------')
  print('Total Booked + Current PnL: '+ '{} ({}%)'.format(format_amt(overall_pnl_amount), overall_pnl_percentage))
  print('Total Booked PnL: '+ '{} ({}%)'.format(format_amt(total_booked_amt), total_booked_percentage))
  print('Curr Year Booked PnL: '+ '{} ({}%)'.format(format_amt(cy_booked_amt), cy_booked_percentage))
  print('Prev Year Booked PnL: '+ '{} ({}%)'.format(format_amt(py_booked_amt), py_booked_percentage))
  print('===================')
  print('Est FTT: ',  format_amt(estimate_st))
  print('Est FTT PnL: '+ '{} ({}%)'.format(format_amt(est_st_pnl_amount), est_st_pnl_percentage))

  print('===================')
  print('Deployed: ', format_amt(investment))

  print('Current: ', format_amt(current))

  print('CAGR/XIRR %: '+'{}%'.format(cagr))

In [8]:
# get start and end date
start_date, end_date = get_start_end_date()

# get portfolio and prospects data
mypfs_df = get_mypfs_df()
mypps_df = get_mypps_df()
myinvmt_df = get_myinvmt_df()

# merge above datasets
mypf_df = pd.merge(mypfs_df, mypps_df, on="Symbol")

# seggregate dm and sv portfolio
dm_pf = mypf_df[mypf_df['InPortfolio'] == 'DM']
sv_pf = mypf_df[mypf_df['InPortfolio'] == 'SV']

# build portfolio stock dataframe
dm_stocks = get_stock_ids(dm_pf)
sv_stocks = get_stock_ids(sv_pf)
df_stocks = pd.concat([dm_pf,sv_pf], ignore_index = True)

# arrange common and diff stock features
common_cols = ['Symbol', 'Target', 'Criteria', 'Strategy', 'CumlRnk', 'LatestQtr', 'StarStock', 'Conviction', 'Category', 'InFolio', 'XIRR', 'MBQ']
diff_cols = ['Symbol', 'AvgCost', 'Shares']
df_stocks = arrange_features(df_stocks, common_cols, diff_cols)

# get common features
stock_ids = df_stocks['Symbol'].values
df_common_features = get_common_features(stock_ids, df_stocks)

df_common_features.reset_index(drop=True, inplace=True)
df_common_features.drop(['Date'], axis=1, inplace=True)
# get and print portfolio features
df_portfolio_features = get_portfolio_features(df_common_features)

print_portfolio_stats(df_portfolio_features, myinvmt_df)

df = df_portfolio_features
#plot_pie_chart(df, 'CapType', 'Current')
list_ox40n = list(df[df['MBQ'].str.contains('OX40N', na=False)]['Symbol'].values)

Run date time (IST): 2026-03-31 10:06:23
-------------------
qualified stocks: 86
with latest results: 26
still star stocks: 16
-------------------
Initial Investment:  1.36 C
CY Investment:  1.62 C
Reserve:  1.61 K
Current:  1.24 C
-------------------
Today PnL: -3.57 L (-2.79%)
Current PnL: -52.74 L (-32.46%)
CY Booked + Current PnL: -36.85 L (-22.68%)
-------------------
Total profit:  23.57 K
Total loss:  -52.97 L
-------------------
Total Booked + Current PnL: -9.87 L (-7.28%)
Total Booked PnL: 42.87 L (31.64%)
Curr Year Booked PnL: 15.89 L (12.77%)
Prev Year Booked PnL: 26.98 L (19.91%)
===================
Est FTT:  2.48 C
Est FTT PnL: 1.23 C (99.28%)
===================
Deployed:  1.36 C
Current:  1.24 C
CAGR/XIRR %: -4.13%

In [9]:
# top 5 near their targets
cols = ['Symbol', 'Today P/L%', 'Current P/L%', 'FTT%', 'OTT%', 'FTT Amt', 'Current P/L', 'Current', 'FTT', 'Dev%_PE', 'RSI_14','Conviction', 'Spread%',  'CumlRnk', 'RRR Ind', 'CurrAlloc%', 'Gained%', 'Criteria', 'Strategy', 'Category']
df_tmp = df_portfolio_features[~df_portfolio_features['Symbol'].isin(['ENRIN','BLUSPRING','DIGITIDE'])]
df_tmp = df_tmp.sort_values(by = 'FTT Amt', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
50,MASFIN,-4.30,-14.38,41.98,21.57,35219.0,-14085.0,83895.0,397.04,-26.38,34.0,H-SC,4.27,167.0,-0.40,0.67,14.43,XR,ATH,FINANCE
77,TTKPRESTIG,-2.58,-44.27,79.61,0.09,44709.0,-44617.0,56160.0,770.00,30.42,33.0,M-SC,21.28,250.0,-1.00,0.45,0.00,OX40N,NTT,DURABLES
2,ABBOTINDIA,-0.84,-13.06,35.81,18.07,55681.0,-23365.0,155490.0,35195.00,-26.09,42.0,X-MC,10.48,58.0,-0.42,1.25,1.69,X40,ATH,PHARMA
67,SONACOMS,-1.48,-16.70,66.98,39.09,56439.0,-16897.0,84262.0,804.02,-33.97,42.0,M-MC,6.42,193.0,-0.30,0.68,19.20,AR,ATH,AUTO
37,ICICIGI,-2.08,-9.39,31.70,19.34,57480.0,-18785.0,181324.0,2252.93,-23.76,30.0,X-MC,4.99,66.0,-0.33,1.46,0.23,X40,ATH,INSURANCE

In [10]:
# top 5 today
df_tmp = df_portfolio_features.sort_values(by = 'Today P/L%', ascending=False)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
53,PGHH,2.02,-30.14,88.96,32.01,132700.0,-64352.0,149168.0,17616.87,-52.76,23.0,X-MC,17.95,57.0,-0.48,1.20,2.02,X40,ATH,FMCG
24,DMART,1.37,-4.88,36.26,29.60,86084.0,-12192.0,237408.0,5391.45,-19.78,58.0,X-LC,6.78,14.0,-0.14,1.91,8.52,X40N,ATH,FMCG
28,GLAXO,1.04,-8.35,51.83,39.15,94662.0,-16644.0,182640.0,3466.20,-29.97,34.0,X-MC,10.43,56.0,-0.18,1.47,1.04,X40,ATH,PHARMA
40,INDIAMART,0.79,-14.65,142.20,106.72,149693.0,-18067.0,105269.0,4810.62,-61.52,37.0,H-SC,12.69,140.0,-0.12,0.85,5.30,AR,ATH,MISC
29,GREENPANEL,0.44,-54.33,213.41,43.14,178441.0,-99464.0,83614.0,537.00,87.34,27.0,M-SC,24.67,225.0,-0.56,0.67,0.44,XY24,NTT,MISC

In [11]:
# bottom 5 today
df_tmp = df_portfolio_features.sort_values(by = 'Today P/L%', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
56,RAJOOENG,-8.13,-54.46,206.56,39.61,96422.0,-55820.0,46680.0,143.10,-69.28,27.0,H-SC,33.11,136.0,-0.58,0.38,0.00,AR,ATH,MISC
30,HAPPSTMNDS,-7.17,-54.93,310.11,84.85,179144.0,-70397.0,57768.0,1480.71,-46.44,42.0,H-SC,25.43,152.0,-0.39,0.46,6.98,AR,ATH,IT
69,SURYODAY,-7.15,-32.34,81.85,23.03,99166.0,-57915.0,121156.0,216.00,31.58,39.0,H-SC,5.76,166.0,-0.58,0.97,13.74,XR,NTT,BANKS
19,COFFEEDAY,-6.13,-64.29,278.79,35.27,113049.0,-72999.0,40550.0,80.00,-71.83,24.0,L-SC,29.65,266.0,-0.65,0.33,0.00,XR,NTT,HOTELS
63,SFL,-5.82,-54.24,176.74,26.63,212058.0,-142235.0,119983.0,1287.00,-9.14,32.0,M-SC,18.34,242.0,-0.67,0.96,0.00,XY24,NTT,MISC

In [12]:
# top 5 to exit based on CumlRnk
df_tmp = df_portfolio_features[~df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])]
df_tmp = df_tmp[(df_tmp['Current P/L%'] > -1) & (df_tmp['Current P/L%'] < 1)].sort_values(by = 'CumlRnk', ascending=False)
df_tmp[cols].head()

Empty DataFrame
Columns: [Symbol, Today P/L%, Current P/L%, FTT%, OTT%, FTT Amt, Current P/L, Current, FTT, Dev%_PE, RSI_14, Conviction, Spread%, CumlRnk, RRR Ind, CurrAlloc%, Gained%, Criteria, Strategy, Category]
Index: []

In [13]:
# OX40N stocks to exit
df_tmp = df_portfolio_features[(df_portfolio_features['Symbol'].isin(list_ox40n))].sort_values(by = 'Current P/L%', ascending=False)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
26,FINCABLES,-3.74,-1.65,111.40,107.91,161759.0,-2438.0,145206.0,1641.55,-11.72,40.0,M-SC,7.33,220.0,-0.02,1.17,9.24,OX40N,ATH,CABLES
66,SIS,-2.89,-35.63,88.37,21.26,63163.0,-39556.0,71476.0,528.00,1670.98,43.0,H-SC,14.46,168.0,-0.63,0.57,6.27,OX40N,NTT,MISC
18,CERA,-1.68,-40.34,107.66,23.89,112981.0,-70961.0,104942.0,9475.00,-42.48,41.0,H-SC,19.33,153.0,-0.63,0.84,0.85,OX40N,NTT,CERAMICS
72,TATAELXSI,-4.43,-42.69,130.37,32.03,98501.0,-56280.0,75555.0,9161.00,-28.26,32.0,H-SC,21.56,158.0,-0.57,0.61,0.00,OX40N,NTT,IT
48,KANSAINER,-1.92,-44.19,103.32,13.47,155495.0,-119169.0,150498.0,340.00,-52.03,33.0,H-SC,22.44,162.0,-0.77,1.21,5.12,XY24,NTT,PAINTS

In [14]:
# top 5 to book for rotation
df_tmp = df_portfolio_features[(df_portfolio_features['Current P/L%'] > 20) ].sort_values(by = 'CumlRnk', ascending=False)
df_tmp[cols].head()

Empty DataFrame
Columns: [Symbol, Today P/L%, Current P/L%, FTT%, OTT%, FTT Amt, Current P/L, Current, FTT, Dev%_PE, RSI_14, Conviction, Spread%, CumlRnk, RRR Ind, CurrAlloc%, Gained%, Criteria, Strategy, Category]
Index: []

In [15]:
# top 5 to monitor for exit
df_tmp = df_portfolio_features[~df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])]
df_tmp = df_tmp[(df_tmp['Current P/L%'] > 0) ].sort_values(by = 'Dev%_PE', ascending=False)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
1,ABB,-2.68,9.01,33.54,45.57,95653.0,23573.0,285192.0,7934.0,-29.92,46.0,H-MC,13.2,125.0,0.25,2.29,26.64,AR,NTT,ELECTRICAL

In [16]:
# top 5 to book for rotation from weak conviction
df_tmp = df_portfolio_features[~df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])]
df_tmp = df_tmp[~df_tmp['Criteria'].isin(['XY25','XY24','X40', 'X40N'])].sort_values(by = 'RRR Ind', ascending=False)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
1,ABB,-2.68,9.01,33.54,45.57,95653.0,23573.0,285192.0,7934.00,-29.92,46.0,H-MC,13.20,125.0,0.25,2.29,26.64,AR,NTT,ELECTRICAL
26,FINCABLES,-3.74,-1.65,111.40,107.91,161759.0,-2438.0,145206.0,1641.55,-11.72,40.0,M-SC,7.33,220.0,-0.02,1.17,9.24,OX40N,ATH,CABLES
40,INDIAMART,0.79,-14.65,142.20,106.72,149693.0,-18067.0,105269.0,4810.62,-61.52,37.0,H-SC,12.69,140.0,-0.12,0.85,5.30,AR,ATH,MISC
85,ZYDUSLIFE,-2.84,-8.13,47.63,35.63,91704.0,-17039.0,192535.0,1286.17,-19.82,43.0,H-MC,5.32,120.0,-0.19,1.55,7.19,AR,ATH,PHARMA
84,WIPRO,-2.07,-23.04,123.83,72.27,161487.0,-39038.0,130410.0,420.00,-30.65,32.0,M-LC,18.22,98.0,-0.24,1.05,0.05,XR,NTT,IT

In [17]:
# top 5 to accumulate based on lowest RSI_14
df_tmp = df_portfolio_features[df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])].sort_values(by = 'RSI_14', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
9,BAJAJHFL,-3.64,-34.71,148.32,62.13,264406.0,-94779.0,178267.0,181.50,-46.30,18.0,X-MC,21.32,60.0,-0.36,1.43,0.00,X40N,ATH,FINANCE
38,ICICIPRULI,-3.93,-15.68,55.04,30.73,91429.0,-30892.0,166113.0,790.00,-38.34,19.0,X-MC,6.54,78.0,-0.34,1.34,0.00,X40,ATH,INSURANCE
58,RELAXO,-4.75,-69.19,394.33,52.31,176364.0,-100435.0,44725.0,1176.00,-67.19,20.0,X-SC,29.75,92.0,-0.57,0.36,0.00,X40N,NTT,FOOTWEAR
27,GILLETTE,-2.91,-14.29,51.36,29.72,111762.0,-36291.0,217605.0,10978.86,-34.13,23.0,X-SC,12.32,83.0,-0.32,1.75,0.00,X40,ATH,FMCG
53,PGHH,2.02,-30.14,88.96,32.01,132700.0,-64352.0,149168.0,17616.87,-52.76,23.0,X-MC,17.95,57.0,-0.48,1.20,2.02,X40,ATH,FMCG

In [18]:
# top 5 to accumulate based on Spread and CumlRnk
df_tmp = df_portfolio_features[df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])]
df_tmp = df_tmp[(df_tmp['CumlRnk'] < 100)].sort_values(by = 'Spread%', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
65,SIEMENS,-3.74,-21.14,59.17,25.51,86832.0,-39345.0,146750.0,4671.50,23.15,38.0,H-LC,1.19,51.0,-0.45,1.18,8.07,AR,ATH,ELECTRICAL
78,UNITDSPR,-2.79,-10.47,34.89,20.77,73141.0,-24510.0,209634.0,1644.00,-20.65,34.0,X-MC,2.93,64.0,-0.34,1.69,0.00,X40N,NTT,BREWERIES
82,VOLTAS,-3.77,-0.43,45.82,45.20,87480.0,-822.0,190920.0,1856.00,13.96,36.0,X-MC,3.11,79.0,-0.01,1.54,6.34,XY25,NTT,AC
59,RELIANCE,-0.31,-13.73,45.25,25.30,78447.0,-27600.0,173363.0,1952.00,-15.80,37.0,X-LC,3.83,21.0,-0.35,1.39,15.75,XY25,BTT,REFINERIES
37,ICICIGI,-2.08,-9.39,31.70,19.34,57480.0,-18785.0,181324.0,2252.93,-23.76,30.0,X-MC,4.99,66.0,-0.33,1.46,0.23,X40,ATH,INSURANCE

In [19]:
# top 5 to accumulate based on lowest Gained%
df_tmp = df_portfolio_features[df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])].sort_values(by = 'Gained%', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
3,ACC,-4.55,-43.85,211.33,74.81,318162.0,-117576.0,150552.0,3906.00,-60.14,24.0,X-SC,19.94,85.0,-0.37,1.21,0.0,XY24,BTT,CEMENT
12,BATAINDIA,-3.90,-60.81,245.02,35.20,123544.0,-78248.0,50422.0,2096.00,-33.86,24.0,X-SC,33.06,91.0,-0.63,0.41,0.0,X40,NTT,FOOTWEAR
10,BAJAJHLDNG,-4.42,-21.80,65.24,29.22,97000.0,-41443.0,148682.0,14451.52,-27.59,26.0,X-LC,18.59,28.0,-0.43,1.20,0.0,X40,ATH,FINANCE
9,BAJAJHFL,-3.64,-34.71,148.32,62.13,264406.0,-94779.0,178267.0,181.50,-46.30,18.0,X-MC,21.32,60.0,-0.36,1.43,0.0,X40N,ATH,FINANCE
23,DIXON,-3.45,-29.53,95.72,37.92,175921.0,-77011.0,183787.0,18931.72,-70.08,40.0,X-MC,27.88,54.0,-0.44,1.48,0.0,X40N,ATH,IT

In [20]:
# top 5 to accumulate based on lowest CurrAlloc%
df_tmp = df_portfolio_features[df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])].sort_values(by = 'CurrAlloc%', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
58,RELAXO,-4.75,-69.19,394.33,52.31,176364.0,-100435.0,44725.0,1176.00,-67.19,20.0,X-SC,29.75,92.0,-0.57,0.36,0.0,X40N,NTT,FOOTWEAR
12,BATAINDIA,-3.90,-60.81,245.02,35.20,123544.0,-78248.0,50422.0,2096.00,-33.86,24.0,X-SC,33.06,91.0,-0.63,0.41,0.0,X40,NTT,FOOTWEAR
54,QUESS,-2.48,-30.39,149.82,73.90,111372.0,-32456.0,74337.0,424.00,-62.53,34.0,X-SC,22.30,80.0,-0.29,0.60,0.0,XY24,NTT,MISC
36,HONAUT,-2.61,-31.74,121.68,51.31,160161.0,-61213.0,131625.0,58357.33,-43.21,25.0,X-SC,17.23,90.0,-0.38,1.06,0.0,X40N,ATH,ELECTRICAL
51,MEDANTA,-2.46,-17.78,54.61,27.12,79253.0,-31391.0,145126.0,1486.00,-20.26,30.0,X-SC,14.17,87.0,-0.40,1.17,0.0,XY24,NTT,HEALTHCARE

In [21]:
# top 5 to accumulate based on CumlRnk
df_tmp = df_portfolio_features.sort_values(by = 'CumlRnk', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
45,ITC,-2.38,-24.22,57.11,19.06,147218.0,-82387.0,257779.0,452.00,-58.35,31.0,X-LC,19.33,1.0,-0.56,2.07,0.00,X40,NTT,FMCG
73,TCS,-1.29,-30.75,82.78,26.57,265567.0,-142463.0,320810.0,4311.59,-41.33,28.0,X-LC,18.19,2.0,-0.54,2.58,0.12,X40,ATH,IT
43,INFY,-1.50,-14.86,57.68,34.24,153647.0,-46510.0,266378.0,1972.00,-32.87,37.0,X-LC,15.09,3.0,-0.30,2.14,2.44,X40,NTT,IT
75,TMPV,-2.31,-32.58,102.57,36.58,246088.0,-115919.0,239922.0,600.00,-85.81,32.0,X-LC,9.66,4.0,-0.47,1.93,0.00,XY24,NTT,AUTO
33,HCLTECH,-1.67,-12.94,42.23,23.83,88949.0,-31293.0,210631.0,1908.19,-8.60,40.0,X-LC,11.63,8.0,-0.35,1.69,2.27,X40,ATH,IT

In [22]:
# top 5 for average up
df_tmp = df_portfolio_features[(df_portfolio_features['Dev%_200'] > 5)].sort_values(by = 'CurrAlloc%', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
1,ABB,-2.68,9.01,33.54,45.57,95653.0,23573.0,285192.0,7934.0,-29.92,46.0,H-MC,13.2,125.0,0.25,2.29,26.64,AR,NTT,ELECTRICAL

In [23]:
# top 5 RSP
df_tmp = df_portfolio_features.sort_values(by = 'RSP', ascending=False)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
24,DMART,1.37,-4.88,36.26,29.60,86084.0,-12192.0,237408.0,5391.45,-19.78,58.0,X-LC,6.78,14.0,-0.14,1.91,8.52,X40N,ATH,FMCG
30,HAPPSTMNDS,-7.17,-54.93,310.11,84.85,179144.0,-70397.0,57768.0,1480.71,-46.44,42.0,H-SC,25.43,152.0,-0.39,0.46,6.98,AR,ATH,IT
52,PAGEIND,-0.09,-17.12,61.82,34.11,137503.0,-45954.0,222425.0,51418.65,-40.59,48.0,X-MC,20.98,55.0,-0.33,1.79,5.22,X40,ATH,APPARELS
5,ANGELONE,-3.29,-6.75,33.17,24.18,94339.0,-20588.0,284412.0,303.00,-86.38,47.0,X-SC,10.46,97.0,-0.22,2.29,9.47,X40N,NTT,FINANCE
1,ABB,-2.68,9.01,33.54,45.57,95653.0,23573.0,285192.0,7934.00,-29.92,46.0,H-MC,13.20,125.0,0.25,2.29,26.64,AR,NTT,ELECTRICAL

In [24]:
# Top N allocation
df_tmp = df_portfolio_features.sort_values(by = 'CurrAlloc%', ascending=False)
top_n_values = [10, 25, 50]

sum_df = pd.DataFrame({
    'Top_N': top_n_values,
    'Sum_Alloc%': [df_tmp['CurrAlloc%'].head(n).sum() for n in top_n_values]
})

sum_df

   Top_N  Sum_Alloc%
0     10       21.19
1     25       46.55
2     50       78.77

In [25]:
# market-cap-wise allocation
df_tmp = df_portfolio_features[cols]
df_tmp.groupby(df_tmp['Conviction'].str[-2:])['CurrAlloc%'].sum().sort_values(ascending=False)

Conviction
SC    43.79
MC    30.24
LC    25.97
Name: CurrAlloc%, dtype: float64

In [26]:
# criteria-wise allocation
df_portfolio_features.groupby('Criteria')['CurrAlloc%'].sum().sort_values(ascending=False)

Criteria
XY24     26.98
X40      25.79
X40N     15.31
AR        9.14
XR        8.10
XY25      7.37
OX40N     6.54
SR        0.77
Name: CurrAlloc%, dtype: float64

In [27]:
# conviction-wise allocation
df_portfolio_features.groupby('Conviction')['CurrAlloc%'].sum().sort_values(ascending=False)

Conviction
X-LC    23.74
X-MC    22.73
H-SC    21.34
X-SC    12.26
M-SC     9.69
H-MC     5.14
M-MC     2.03
H-LC     1.18
M-LC     1.05
L-SC     0.50
L-MC     0.34
Name: CurrAlloc%, dtype: float64

In [28]:
# sector-wise stats
df_tmp = df_portfolio_features.groupby('Category')[['CurrAlloc%', 'Current', 'Current P/L', 'FTT Amt']].sum().sort_values(by=['Current', 'Current P/L'], ascending=False)
df_tmp['Current P/L%'] = round(df_tmp['Current P/L'] * 100 / df_tmp['Current'], 2)
df_tmp['FTT%'] = round(df_tmp['FTT Amt'] * 100 / df_tmp['Current'], 2)
cols = ['CurrAlloc%', 'Current P/L%', 'FTT%']
df_tmp[cols].sort_values(by=['CurrAlloc%'], ascending=False)

               CurrAlloc%  Current P/L%    FTT%
Category
FMCG                15.34        -30.87   77.34
FINANCE             13.00        -32.79   86.90
IT                  11.96        -51.44  128.50
MISC                 6.94        -55.26  122.70
ELECTRICAL           6.54        -19.05   64.63
PAINTS               5.27        -50.62   76.77
INSURANCE            4.80        -13.74   52.66
BANKS                4.48        -37.69  107.58
PHARMA               4.27        -10.75   45.61
AUTO                 3.65        -44.04  101.19
AC                   2.01        -27.99   62.69
HEALTHCARE           1.88        -53.50   93.56
APPARELS             1.79        -20.66   61.82
FOOTWEAR             1.77       -101.03  181.64
TRAVEL               1.76       -104.92  207.52
DURABLES             1.75        -76.60  119.56
BREWERIES            1.69        -11.69   34.89
REALTY               1.46        -21.99   42.03
REFINERIES           1.39        -15.92   45.25
CERAMICS             1.36        -81.24  136.30
CEMENT               1.21        -78.10  211.33
CABLES               1.17         -1.68  111.40
ENGINEERING          1.05        -84.77  169.29
CHEMICALS            0.98       -117.46  294.87
JEWELLERY            0.97       -166.17  258.65
ENTERTAINMENT        0.73       -114.68  242.71
TEXTILES             0.45        -65.92  113.24
HOTELS               0.33       -180.02  278.79

In [29]:
# money to be made criteria-wise
df_portfolio_features.groupby('Criteria')['FTT Amt'].agg(['sum', 'count']).sort_values(by='sum', ascending=False)

                sum  count
Criteria
XY24      4239757.0     21
X40       1968339.0     16
XR        1482867.0     12
AR        1436358.0     10
X40N      1397272.0     10
OX40N      976565.0     10
XY25       523913.0      5
SR         324319.0      2

In [30]:
# money to be made conviction-wise
df_portfolio_features.groupby('Conviction')['FTT Amt'].agg(['sum', 'count']).sort_values(by='sum', ascending=False)

                  sum  count
Conviction
H-SC        4136645.0     24
X-MC        1909436.0     15
X-LC        1822434.0     13
M-SC        1711141.0     14
X-SC        1658914.0     10
H-MC         439839.0      3
L-SC         229020.0      2
M-LC         161487.0      1
M-MC         133931.0      2
H-LC          86832.0      1
L-MC          59711.0      1

In [31]:
# money to be made criteria and conviction-wise
df_portfolio_features.groupby(['Conviction', 'Criteria'])['FTT Amt'].agg(['sum', 'count']).sort_values(by='sum', ascending=False)

                           sum  count
Conviction Criteria
H-SC       XY24      1422644.0      6
           AR        1022498.0      5
M-SC       XY24       985879.0      6
X-LC       X40        980409.0      7
H-SC       XR         949473.0      7
X-SC       XY24       885749.0      4
X-MC       X40        752624.0      7
           X40N       589880.0      4
X-SC       X40N       537859.0      4
M-SC       OX40N      442883.0      5
H-SC       OX40N      417711.0      4
X-LC       XY24       407357.0      2
H-SC       SR         324319.0      2
X-MC       XY24       285646.0      2
           XY25       281286.0      2
X-LC       X40N       269533.0      2
H-MC       XY24       252482.0      1
X-SC       X40        235306.0      2
M-SC       XR         199147.0      2
H-MC       AR         187357.0      2
X-LC       XY25       165135.0      2
M-LC       XR         161487.0      1
L-SC       OX40N      115971.0      1
           XR         113049.0      1
H-LC       AR          86832.0      1
M-SC       AR          83232.0      1
M-MC       XY25        77492.0      1
L-MC       XR          59711.0      1
M-MC       AR          56439.0      1

In [32]:
# notebook execution time

end_time = time.time()
execution_time = round(end_time - start_time, 0)
print(f"Notebook execution time: {execution_time} seconds")

Notebook execution time: 24.0 seconds