<a href="https://colab.research.google.com/github/ankit-rathi/Quantvesting_v2/blob/main/myStocks_Portfolio_Analysis.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
'''
!pip install pandas==2.2.2 -qq
!pip install pyxirr -qq
!pip install ta -qq
!pip install yfinance==0.2.59 -qq
'''

'\n!pip install pandas==2.2.2 -qq\n!pip install pyxirr -qq\n!pip install ta -qq\n!pip install yfinance==0.2.59 -qq\n'

In [2]:
# import libraries

import numpy as np
import pandas as pd
import datetime
import warnings
warnings.filterwarnings('ignore')
import yfinance as yfin
import ta
import matplotlib.pyplot as plt
import requests

In [3]:
# notebook start time
import time
import datetime
import pytz

start_time = time.time()

# function to print date timestamp
def print_date_time():
  tz_NY = pytz.timezone('Asia/Kolkata')
  datetime_NY = datetime.datetime.now(tz_NY)
  print("Run date time (IST):", datetime_NY.strftime("%Y-%m-%d %H:%M:%S"))

In [4]:
# function to get booked and reserved amount
def get_amt():
  # fetch the JSON data from the URL
  url = "https://raw.githubusercontent.com/ankit-rathi/Tradevesting_v1/main/data/myPortfolioAmts.json"
  response = requests.get(url)
  pf_amts = response.json()  # parse the JSON data

  # extract values from the JSON
  py_booked_amt_dm = pf_amts["py_booked_amt_dm"]
  py_booked_amt_sv = pf_amts["py_booked_amt_sv"]
  cy_booked_amt_dm = pf_amts["cy_booked_amt_dm"]
  cy_booked_amt_sv = pf_amts["cy_booked_amt_sv"]
  reserve_amt_dm = pf_amts["reserve_amt_dm"]
  reserve_amt_sv = pf_amts["reserve_amt_sv"]

  # perform calculations
  py_booked_amt = py_booked_amt_dm + py_booked_amt_sv
  cy_booked_amt = cy_booked_amt_dm + cy_booked_amt_sv
  reserve_amt = reserve_amt_dm + reserve_amt_sv
  total_booked_amt = py_booked_amt + cy_booked_amt

  return total_booked_amt, reserve_amt, cy_booked_amt, py_booked_amt

gen_output = 0

In [5]:
# function to format the amount
def format_amt(number):
    abs_number = abs(number)

    if abs_number >= 1_00_00_000:  # Crores
        formatted_amt = f"{number / 1_00_00_000:.2f} C"
    elif abs_number >= 1_00_000:  # Lakhs
        formatted_amt = f"{number / 1_00_000:.2f} L"
    elif abs_number >= 1_000:  # Thousands
        formatted_amt = f"{number / 1_000:.2f} K"
    else:
        formatted_amt = f"{number:.2f}"

    return formatted_amt

# function to set start and end date
def get_start_end_date():
  start_date = (datetime.date.today() + datetime.timedelta(days=-365)).strftime('%Y-%m-%d')
  end_date = (datetime.date.today() + datetime.timedelta(days=1)).strftime('%Y-%m-%d')
  return start_date, end_date

# function to fetch my portfolio csv
def get_mypfs_df():
  mypfs_df = pd.read_csv('https://raw.githubusercontent.com/ankit-rathi/Tradevesting_v1/main/data/myPortfolioStocks.csv')
  return mypfs_df

# function to fetch my prospects csv
def get_mypps_df():
  mypps_df = pd.read_csv('https://raw.githubusercontent.com/ankit-rathi/Tradevesting_v1/main/data/myProspectsScrips.csv')
  return mypps_df

# function to fetch screener data
def get_myscreen_df():
  myscreen_df = pd.read_csv('https://raw.githubusercontent.com/ankit-rathi/Tradevesting_v1/main/data/myScreenerDB.csv')
  return myscreen_df

# function to fetch momentum data
def get_myinvmt_df():
  myinvmt_df = pd.read_csv('https://raw.githubusercontent.com/ankit-rathi/Tradevesting_v1/main/data/myInvestments.csv')
  return myinvmt_df

# function to get the stock ids
def get_stock_ids(df_pf):
  stock_n100 = df_pf['Symbol'].unique()

  exclude = ['CADILAHC','MMTC', 'MASFIN']

  stock_ids = df_pf[~df_pf['Symbol'].isin(exclude) ]['Symbol'].unique()

  #mypf = mypf[mypf.Forecast.notnull()]
  #stock_ids = mypf['Symbol'].unique()

  #stock_ids.sort()
  return stock_ids

# get features from screener data
def get_screener_features():
  myscreen_df = get_myscreen_df()
  cols = ['Symbol', 'EPS', 'MedPE', 'ROCE%', 'ROE%', 'CapType']
  return myscreen_df[cols]

# get relative strength
def get_relative_strength(stock_list):

    # Dictionary to store stock tickers and their corresponding percentage price change
    stock_changes = {}

    # Loop through each stock and fetch its price data
    for stock in stock_list:
        try:
            # Download the stock data for the given date range
            stock_data = yfin.Ticker(stock + '.NS').history(period='1mo', interval='1d')[map(str.title, ['open', 'close', 'low', 'high', 'volume'])]

            # Calculate the percentage change for the stock
            if len(stock_data) > 0:
                start_price = stock_data['Close'].iloc[0]
                end_price = stock_data['Close'].iloc[-1]
                percent_change = round(((end_price - start_price) / start_price) * 100, 2)
                stock_changes[stock] = percent_change
            else:
                stock_changes[stock] = np.nan  # If no data is available, set to NaN

        except Exception as e:
            print(f"Error fetching data for {stock}: {e}")
            stock_changes[stock] = np.nan

    # Create a DataFrame with stock tickers and their percentage changes
    df = pd.DataFrame(list(stock_changes.items()), columns=['Symbol', 'Percent_Change'])

    # Drop any stocks with missing data (NaN values)
    df = df.dropna()

    # Calculate the percentile rank based on percentage change
    df['RSP'] = round(df['Percent_Change'].rank(pct=True) * 100, 2)
    cols = ['Symbol', 'RSP']
    df = df[cols]
    # Sort by percentile rank (optional)
    df = df.sort_values(by='RSP', ascending=False).reset_index(drop=True)

    return df

In [6]:
# function to get stock technicals
def stock_prec_dev(stock_symbol):
    #stock_symbol = 'ULTRACEMCO.NS'
    short_window = 20
    mid_window = 50
    long_window = 200
    moving_avg = 'SMA'

    start = datetime.datetime(*map(int, start_date.split('-')))
    end = datetime.datetime(*map(int, end_date.split('-')))

    stock_df = yfin.Ticker(stock_symbol + '.NS').history(period='max', interval='1d')[map(str.title, ['open', 'close', 'low', 'high', 'volume'])]

    stock_df['Max'] = round(max(stock_df['Close']),2)
    stock_df = stock_df[(stock_df.index <= end_date) & (stock_df.index >= start_date)]
    stock_df['200_SMA'] = round(stock_df['Close'].rolling(window = 200, min_periods = 1).mean(),0)
    stock_df['Dev%_200'] = round((stock_df['Close'] - stock_df['200_SMA'])*100/stock_df['200_SMA'],2)
    stock_df.dropna(axis = 0, inplace = True) # remove any null rows

    stock_df['20_SMA'] = stock_df['Close'].rolling(window=20).mean()
    stock_df['50_SMA'] = stock_df['Close'].rolling(window=50).mean()
    stock_df['Symbol'] = stock_symbol

    stock_df['Close'] = round(stock_df['Close'],2)
    stock_df['Min'] = round(min(stock_df['Close']),2)
    stock_df['RSI_14'] = ta.momentum.RSIIndicator(close=stock_df['Close'], window=14).rsi()
    stock_df['RSI_14'] = round(stock_df['RSI_14'],0)
    stock_df['Prev_Close'] = stock_df['Close'].shift(1)
    stock_df.drop(['Open', 'Low', 'High', 'Volume'], axis=1, inplace=True)
    stock_df = stock_df.tail(1)

    max_SMA = max(stock_df['20_SMA'].item(), stock_df['50_SMA'].item(), stock_df['200_SMA'].item())
    min_SMA = min(stock_df['20_SMA'].item(), stock_df['50_SMA'].item(), stock_df['200_SMA'].item())
    ABS_Spread = max_SMA - min_SMA
    stock_df['Spread%'] = round((ABS_Spread / stock_df['200_SMA'].item()) * 100,2)

    return stock_df

# function to compute stock attributes
def get_common_features(stock_ids, df_mypf):

  df_prec_dev = pd.DataFrame()
  df_tmp = get_screener_features()
  df_rs = get_relative_strength(stock_ids)

  for stock_id in stock_ids:
      tmp = stock_prec_dev(stock_id)
      tmp = tmp.reset_index()
      df_prec_dev = pd.concat([df_prec_dev, tmp], ignore_index = True)
  df_prec_dev = pd.merge(df_prec_dev, df_mypf, on= 'Symbol')
  df_prec_dev = pd.merge(df_prec_dev, df_tmp, on= 'Symbol', how='left')
  df_prec_dev = pd.merge(df_prec_dev, df_rs, on= 'Symbol', how='left')
  #print(df_prec_dev.columns)
  df_prec_dev['Curr_PE'] = round(df_prec_dev['Close']/df_prec_dev['EPS'],1)
  df_prec_dev['Dev%_PE'] = round((df_prec_dev['Curr_PE'] - df_prec_dev['MedPE'])*100/df_prec_dev['MedPE'],2)
  df_prec_dev['Conviction'] = df_prec_dev['Conviction'] + '-' + df_prec_dev['CapType']
  return df_prec_dev

# function to arrange stock features
def arrange_features(df_stocks, common_cols, diff_cols):
  df_stocks_common = df_stocks[common_cols].drop_duplicates()
  df_stocks_diff = df_stocks[diff_cols]
  df_stocks_diff['Investment'] = df_stocks_diff['AvgCost'] * df_stocks_diff['Shares']
  df_stocks_diff = df_stocks_diff.groupby(['Symbol'])[['Shares', 'Investment']].aggregate(['sum']).reset_index()
  df_stocks_diff.columns = ['Symbol', 'Shares', 'Investment']
  df_stocks_diff['AvgCost'] = round(df_stocks_diff['Investment']/df_stocks_diff['Shares'],2)
  df_stocks = pd.merge(df_stocks_diff, df_stocks_common, on='Symbol')
  return df_stocks

# plot fact distribution across dimension
def plot_pie_chart(df, dimension, fact):
  # grouping the data by category and calculating the sum of fact for each type
  grouped_data = df.groupby(dimension)[fact].sum()

  # sorting the grouped data in descending order
  grouped_data = grouped_data.sort_values(ascending=False)

  # creating a pie chart
  grouped_data.plot.pie(autopct='%1.1f%%', startangle=90, figsize=(6, 6))

  # adding a title and displaying the plot
  plt.title(f'{dimension} {fact} Distribution')
  plt.ylabel('')  # To hide the y-label
  plt.show()

In [7]:
# function to get portfolio features

def get_portfolio_features(df_common_features):

  print_date_time()
  print('-------------------')

  #df_common_features["Target"] = df_common_features["Target"].fillna(df_common_features["Max"])
  df_common_features['NTT'] = np.where(df_common_features['Strategy']== 'NTT', df_common_features["Target"], df_common_features['Max'])
  df_common_features['LTT'] = np.where(df_common_features['Strategy']== 'BTT', df_common_features["Target"], df_common_features['Max'])
  df_common_features['BOL'] = df_common_features['Min']

  tmp_df = df_common_features[df_common_features['Symbol'].isin(mypf_df[mypf_df['InPortfolio'] != 'NA'].Symbol.values)]
  print('qualified stocks: '+str(len(tmp_df['Symbol'].unique())))
  tmp_df1 = tmp_df[tmp_df['LatestQtr'] == 1]
  print('with latest results: '+str(len(tmp_df1['Symbol'].unique())))
  tmp_df1 = tmp_df1[tmp_df1['StarStock'] == 1]
  print('still star stocks: '+str(len(tmp_df1['Symbol'].unique())))
  tmp_df['Investment'] = tmp_df['AvgCost'] * tmp_df['Shares']
  tmp_df['Current'] = round(tmp_df['Close'] * tmp_df['Shares'],0)
  tmp_df['Previous'] = tmp_df['Prev_Close'] * tmp_df['Shares']
  tmp_df['EstimatedST'] = tmp_df['NTT'] * tmp_df['Shares']
  tmp_df['EstimatedLT'] = tmp_df['LTT'] * tmp_df['Shares']
  tmp_df['Current P/L'] = round((tmp_df['Current'] - tmp_df['Investment']),0)
  tmp_df['Today P/L%'] = round((tmp_df['Current'] - tmp_df['Previous'])*100/tmp_df['Previous'],2)
  tmp_df['Current P/L%'] = round((tmp_df['Current'] - tmp_df['Investment'])*100/tmp_df['Investment'],2)
  tmp_df['EstimatedST P/L%'] = round((tmp_df['EstimatedST'] - tmp_df['Investment'])*100/tmp_df['Investment'],2)
  tmp_df['EstimatedLT P/L%'] = round((tmp_df['EstimatedLT'] - tmp_df['Investment'])*100/tmp_df['Investment'],2)
  tmp_df['NTT%'] = round((tmp_df['NTT'] - tmp_df['Close'])*100/tmp_df['Close'],2)
  tmp_df['LTT%'] = round((tmp_df['LTT'] - tmp_df['Close'])*100/tmp_df['Close'],2)
  tmp_df['Gained%'] = round((tmp_df['Close'] - tmp_df['BOL'])*100/tmp_df['BOL'],2)
  investment = round(sum(tmp_df['AvgCost']*tmp_df['Shares']),0)
  current = round(sum(tmp_df['Close']*tmp_df['Shares']),0)
  tmp_df['InitAlloc%'] = round(tmp_df['Investment']*100/investment,2)
  tmp_df['CurrAlloc%'] = round(tmp_df['Current']*100/current,2)
  tmp_df['FTT'] = tmp_df['LTT']
  tmp_df.loc[tmp_df['Strategy'] == 'NTT', 'FTT'] = tmp_df['NTT']
  tmp_df['FTT%'] = tmp_df['LTT%']
  tmp_df.loc[tmp_df['Strategy'] == 'NTT', 'FTT%'] = tmp_df['NTT%']
  tmp_df['FTT Amt'] = round(tmp_df['FTT%'] * tmp_df['Current']/100,0)
  tmp_df['OTT%'] = round((tmp_df['FTT'] - tmp_df['AvgCost'])*100/tmp_df['AvgCost'],2)
  tmp_df['RRR Ind'] = round(tmp_df['Current P/L']/tmp_df['FTT Amt'],2)
  tmp_df['Risk Ind'] = round(tmp_df['Current P/L%']*tmp_df['CurrAlloc%'],0)

  return tmp_df

# function to print portfolio features
def print_portfolio_stats(df_portfolio_features, myinvmt_df):
  from pyxirr import xirr

  total_booked_amt, reserve_amt, cy_booked_amt, py_booked_amt = get_amt()

  dates = myinvmt_df['Date'].values
  dates = np.append(dates, datetime.date.today().strftime('%d-%b-%y'))
  investment = myinvmt_df['Investment'].values
  dates= pd.to_datetime(dates)

  current = round(sum(df_portfolio_features['Close']*df_portfolio_features['Shares']),0) + reserve_amt
  investment_xirr = np.append(investment, current)
  cagr = round(xirr(pd.DataFrame({"dates": dates, "amounts": investment_xirr}))*100,2)

  investment = -sum(investment)
  invested = round(sum(df_portfolio_features['AvgCost']*df_portfolio_features['Shares']),0) + reserve_amt
  previous = round(sum(df_portfolio_features['Prev_Close']*df_portfolio_features['Shares']),0) + reserve_amt
  cy_invested = investment + py_booked_amt

  today_pnl_amount = current-previous
  today_pnl_percentage = round((current-previous)*100/previous,2)

  curr_pnl_amount = current-invested
  curr_pnl_percentage = round((curr_pnl_amount)*100/(cy_invested),2)

  cy_pnl_amount = cy_booked_amt + curr_pnl_amount
  cy_pnl_percentage = round((cy_pnl_amount)*100/cy_invested,2)

  overall_pnl_amount = total_booked_amt + curr_pnl_amount
  overall_pnl_percentage = round((overall_pnl_amount)*100/investment,2)

  estimate_st = round(sum(df_portfolio_features['FTT']*df_portfolio_features['Shares']),0)  + reserve_amt
  est_st_pnl_amount = estimate_st-current
  est_st_pnl_percentage = round((est_st_pnl_amount)*100/current,2)

  estimate_lt = round(sum(df_portfolio_features['LTT']*df_portfolio_features['Shares']),0)  + reserve_amt
  est_lt_pnl_amount = estimate_lt-current
  est_lt_pnl_percentage = round((est_lt_pnl_amount)*100/current,2)

  total_profit = round(sum(df_portfolio_features[df_portfolio_features['Current P/L%'] > 0]['Current']) - sum(df_portfolio_features[df_portfolio_features['Current P/L%'] > 0]['Investment']),0)
  total_loss = round(sum(df_portfolio_features[df_portfolio_features['Current P/L%'] < 0]['Current']) - sum(df_portfolio_features[df_portfolio_features['Current P/L%'] < 0]['Investment']),0)

  cy_booked_percentage = round((cy_booked_amt)*100/current,2)
  py_booked_percentage = round((py_booked_amt)*100/investment,2)
  total_booked_percentage = round((total_booked_amt)*100/investment,2)

  print('-------------------')
  print('Initial Investment: ', format_amt(investment))
  print('CY Investment: ', format_amt(cy_invested))
  print('Reserve: ', format_amt(reserve_amt))
  print('Current: ',  format_amt(current))
  print('-------------------')
  print('Today PnL: '+ '{} ({}%)'.format(format_amt(today_pnl_amount), today_pnl_percentage))
  print('Current PnL: '+ '{} ({}%)'.format(format_amt(curr_pnl_amount), curr_pnl_percentage))
  print('CY Booked + Current PnL: '+ '{} ({}%)'.format(format_amt(cy_pnl_amount), cy_pnl_percentage))
  print('-------------------')
  print('Total profit: ', format_amt(total_profit))
  print('Total loss: ', format_amt(total_loss))
  print('-------------------')
  print('Total Booked + Current PnL: '+ '{} ({}%)'.format(format_amt(overall_pnl_amount), overall_pnl_percentage))
  print('Total Booked PnL: '+ '{} ({}%)'.format(format_amt(total_booked_amt), total_booked_percentage))
  print('Curr Year Booked PnL: '+ '{} ({}%)'.format(format_amt(cy_booked_amt), cy_booked_percentage))
  print('Prev Year Booked PnL: '+ '{} ({}%)'.format(format_amt(py_booked_amt), py_booked_percentage))
  print('===================')
  print('Est FTT: ',  format_amt(estimate_st))
  print('Est FTT PnL: '+ '{} ({}%)'.format(format_amt(est_st_pnl_amount), est_st_pnl_percentage))

  print('===================')
  print('Deployed: ', format_amt(investment))

  print('Current: ', format_amt(current))

  print('CAGR/XIRR %: '+'{}%'.format(cagr))

In [8]:
# get start and end date
start_date, end_date = get_start_end_date()

# get portfolio and prospects data
mypfs_df = get_mypfs_df()
mypps_df = get_mypps_df()
myinvmt_df = get_myinvmt_df()

# merge above datasets
mypf_df = pd.merge(mypfs_df, mypps_df, on="Symbol")

# seggregate dm and sv portfolio
dm_pf = mypf_df[mypf_df['InPortfolio'] == 'DM']
sv_pf = mypf_df[mypf_df['InPortfolio'] == 'SV']

# build portfolio stock dataframe
dm_stocks = get_stock_ids(dm_pf)
sv_stocks = get_stock_ids(sv_pf)
df_stocks = pd.concat([dm_pf,sv_pf], ignore_index = True)

# arrange common and diff stock features
common_cols = ['Symbol', 'Target', 'Criteria', 'Strategy', 'CumlRnk', 'LatestQtr', 'StarStock', 'Conviction', 'Category', 'InFolio', 'XIRR', 'MBQ']
diff_cols = ['Symbol', 'AvgCost', 'Shares']
df_stocks = arrange_features(df_stocks, common_cols, diff_cols)

# get common features
stock_ids = df_stocks['Symbol'].values
df_common_features = get_common_features(stock_ids, df_stocks)

df_common_features.reset_index(drop=True, inplace=True)
df_common_features.drop(['Date'], axis=1, inplace=True)
# get and print portfolio features
df_portfolio_features = get_portfolio_features(df_common_features)

print_portfolio_stats(df_portfolio_features, myinvmt_df)

df = df_portfolio_features
#plot_pie_chart(df, 'CapType', 'Current')
list_ox40n = list(df[df['MBQ'].str.contains('OX40N', na=False)]['Symbol'].values)

Run date time (IST): 2026-08-21 08:31:25
-------------------
qualified stocks: 87
with latest results: 30
still star stocks: 19
-------------------
Initial Investment:  1.46 C
CY Investment:  1.89 C
Reserve:  3.69 L
Current:  1.58 C
-------------------
Today PnL: 67.61 K (0.43%)
Current PnL: -34.77 L (-18.4%)
CY Booked + Current PnL: -29.71 L (-15.72%)
-------------------
Total profit:  3.58 L
Total loss:  -38.34 L
-------------------
Total Booked + Current PnL: 13.16 L (9.01%)
Total Booked PnL: 47.93 L (32.82%)
Curr Year Booked PnL: 5.06 L (3.2%)
Prev Year Booked PnL: 42.87 L (29.35%)
===================
Est FTT:  2.67 C
Est FTT PnL: 1.09 C (68.86%)
===================
Deployed:  1.46 C
Current:  1.58 C
CAGR/XIRR %: 3.61%

In [9]:
# top 5 near their targets
cols = ['Symbol', 'Today P/L%', 'Current P/L%', 'FTT%', 'OTT%', 'FTT Amt', 'Current P/L', 'Current', 'FTT', 'Dev%_PE', 'RSI_14','Conviction', 'Spread%',  'CumlRnk', 'RRR Ind', 'CurrAlloc%', 'Gained%', 'Criteria', 'Strategy', 'Category']
df_tmp = df_portfolio_features[~df_portfolio_features['Symbol'].isin(['ENRIN','BLUSPRING','DIGITIDE'])]
df_tmp = df_tmp.sort_values(by = 'FTT Amt', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
66,SIEMENS,-0.48,4.25,6.31,10.83,12241.0,7905.0,194000.0,4125.00,-15.50,55.0,H-LC,14.06,51.0,0.65,1.26,36.88,AR,NTT,ELECTRICAL
78,UNITDSPR,0.20,11.95,7.87,20.77,20629.0,27984.0,262128.0,1644.00,-4.62,61.0,X-MC,10.89,64.0,1.36,1.70,26.00,X40N,NTT,BREWERIES
77,TTKPRESTIG,-1.60,-23.94,31.60,0.09,24221.0,-24129.0,76648.0,770.00,-7.35,39.0,M-SC,9.65,250.0,-1.00,0.50,37.96,OX40N,NTT,DURABLES
52,M&M,0.29,8.15,9.87,18.82,25690.0,19604.0,260285.0,3762.88,-6.55,59.0,X-LC,4.88,25.0,0.76,1.68,18.07,X40N,ATH,AUTO
27,GLAXO,5.39,21.73,11.47,35.69,27825.0,43308.0,242592.0,3380.16,-8.73,86.0,X-MC,9.83,56.0,1.56,1.57,44.18,X40,ATH,PHARMA

In [10]:
# top 5 today
df_tmp = df_portfolio_features.sort_values(by = 'Today P/L%', ascending=False)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
27,GLAXO,5.39,21.73,11.47,35.69,27825.0,43308.0,242592.0,3380.16,-8.73,86.0,X-MC,9.83,56.0,1.56,1.57,44.18,X40,ATH,PHARMA
0,5PAISA,4.46,-22.78,46.20,12.90,77953.0,-49766.0,168730.0,593.00,8.23,66.0,H-SC,11.93,170.0,-0.64,1.09,62.83,OX40N,NTT,FINANCE
3,ALKYLAMINE,3.25,-16.69,131.12,92.54,110288.0,-16851.0,84112.0,4520.85,NaN,60.0,NaN,14.38,142.0,-0.15,0.54,59.72,SR,ATH,CHEMICALS
62,REPCOHOME,3.07,-22.16,143.87,89.82,320837.0,-63500.0,223005.0,880.00,NaN,36.0,NaN,4.27,161.0,-0.20,1.44,7.20,XY24,NTT,FINANCE
84,WHIRLPOOL,2.96,-37.83,192.62,81.92,137471.0,-43429.0,71369.0,2270.00,NaN,44.0,NaN,11.12,210.0,-0.32,0.46,2.96,XR,NTT,DURABLES

In [11]:
# bottom 5 today
df_tmp = df_portfolio_features.sort_values(by = 'Today P/L%', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
29,GREENPANEL,-3.30,-57.18,234.25,43.14,183657.0,-104676.0,78402.0,537.00,NaN,25.0,NaN,11.97,225.0,-0.57,0.51,0.00,XY24,NTT,MISC
55,PAGEIND,-2.72,-8.09,44.54,32.85,109871.0,-21699.0,246680.0,50936.07,-31.61,28.0,X-MC,8.53,55.0,-0.20,1.60,17.79,X40,ATH,APPARELS
59,RECLTD,-2.64,-11.18,35.93,20.74,64837.0,-22715.0,180455.0,446.00,-2.70,32.0,M-MC,2.40,191.0,-0.35,1.17,9.26,XY25,NTT,FINANCE
30,HAPPSTMNDS,-2.27,-48.77,257.34,83.08,168980.0,-62501.0,65664.0,1466.54,NaN,59.0,NaN,8.49,152.0,-0.37,0.43,22.99,AR,ATH,IT
70,SYMPHONY,-2.21,-53.92,116.93,-0.03,92222.0,-92272.0,78869.0,1306.00,NaN,23.0,NaN,16.58,205.0,-1.00,0.51,0.00,OX40N,NTT,DURABLES

In [12]:
# top 5 to exit based on CumlRnk
df_tmp = df_portfolio_features[~df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])]
df_tmp = df_tmp[(df_tmp['Current P/L%'] > -1) & (df_tmp['Current P/L%'] < 1)].sort_values(by = 'CumlRnk', ascending=False)
df_tmp[cols].head()

Empty DataFrame
Columns: [Symbol, Today P/L%, Current P/L%, FTT%, OTT%, FTT Amt, Current P/L, Current, FTT, Dev%_PE, RSI_14, Conviction, Spread%, CumlRnk, RRR Ind, CurrAlloc%, Gained%, Criteria, Strategy, Category]
Index: []

In [13]:
# OX40N stocks to exit
df_tmp = df_portfolio_features[(df_portfolio_features['Symbol'].isin(list_ox40n))].sort_values(by = 'Current P/L%', ascending=False)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
25,FINCABLES,-1.71,63.54,27.13,107.91,65506.0,93810.0,241454.0,1641.55,19.27,69.0,M-SC,21.63,220.0,1.43,1.56,81.65,OX40N,ATH,CABLES
67,SIS,-0.31,-5.10,27.78,21.26,29271.0,-5666.0,105366.0,528.00,102.24,37.0,H-SC,20.73,168.0,-0.19,0.68,56.66,OX40N,NTT,MISC
43,INDIGOPNTS,-0.17,-18.39,22.56,0.02,32137.0,-32108.0,142451.0,1408.00,-22.11,64.0,M-SC,7.32,222.0,-1.00,0.92,61.62,OX40N,NTT,PAINTS
12,BOSCH-HCIL,0.53,-22.36,28.78,-0.01,28559.0,-28573.0,99232.0,2282.00,777.96,79.0,M-SC,8.78,231.0,-1.00,0.64,68.91,OX40N,BTT,AC
0,5PAISA,4.46,-22.78,46.20,12.90,77953.0,-49766.0,168730.0,593.00,8.23,66.0,H-SC,11.93,170.0,-0.64,1.09,62.83,OX40N,NTT,FINANCE

In [14]:
# top 5 to book for rotation
df_tmp = df_portfolio_features[(df_portfolio_features['Current P/L%'] > 20) ].sort_values(by = 'CumlRnk', ascending=False)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
25,FINCABLES,-1.71,63.54,27.13,107.91,65506.0,93810.0,241454.0,1641.55,19.27,69.0,M-SC,21.63,220.0,1.43,1.56,81.65,OX40N,ATH,CABLES
27,GLAXO,5.39,21.73,11.47,35.69,27825.0,43308.0,242592.0,3380.16,-8.73,86.0,X-MC,9.83,56.0,1.56,1.57,44.18,X40,ATH,PHARMA

In [15]:
# top 5 to monitor for exit
df_tmp = df_portfolio_features[~df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])]
df_tmp = df_tmp[(df_tmp['Current P/L%'] > 0) ].sort_values(by = 'Dev%_PE', ascending=False)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
25,FINCABLES,-1.71,63.54,27.13,107.91,65506.0,93810.0,241454.0,1641.55,19.27,69.0,M-SC,21.63,220.0,1.43,1.56,81.65,OX40N,ATH,CABLES
68,STARHEALTH,-0.19,12.78,30.58,47.26,96952.0,35920.0,317043.0,761.00,-0.61,50.0,H-SC,16.27,173.0,0.37,2.05,37.08,XY24,NTT,INSURANCE

In [16]:
# top 5 to book for rotation from weak conviction
df_tmp = df_portfolio_features[~df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])]
df_tmp = df_tmp[~df_tmp['Criteria'].isin(['XY25','XY24','X40', 'X40N'])].sort_values(by = 'RRR Ind', ascending=False)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
25,FINCABLES,-1.71,63.54,27.13,107.91,65506.0,93810.0,241454.0,1641.55,19.27,69.0,M-SC,21.63,220.0,1.43,1.56,81.65,OX40N,ATH,CABLES
3,ALKYLAMINE,3.25,-16.69,131.12,92.54,110288.0,-16851.0,84112.0,4520.85,NaN,60.0,NaN,14.38,142.0,-0.15,0.54,59.72,SR,ATH,CHEMICALS
67,SIS,-0.31,-5.10,27.78,21.26,29271.0,-5666.0,105366.0,528.00,102.24,37.0,H-SC,20.73,168.0,-0.19,0.68,56.66,OX40N,NTT,MISC
42,INDIAMART,-1.07,-25.47,169.60,100.92,155893.0,-31418.0,91918.0,4675.60,NaN,34.0,NaN,13.91,140.0,-0.20,0.59,0.00,AR,ATH,MISC
71,TANLA,0.28,-35.27,235.60,117.25,412953.0,-95484.0,175277.0,1922.32,NaN,46.0,NaN,15.58,147.0,-0.23,1.13,53.46,AR,ATH,IT

In [17]:
# top 5 to accumulate based on lowest RSI_14
df_tmp = df_portfolio_features[df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])].sort_values(by = 'RSI_14', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
55,PAGEIND,-2.72,-8.09,44.54,32.85,109871.0,-21699.0,246680.0,50936.07,-31.61,28.0,X-MC,8.53,55.0,-0.20,1.60,17.79,X40,ATH,APPARELS
56,PGHH,-0.94,-38.26,113.82,32.01,150042.0,-81696.0,131824.0,17616.87,-54.65,28.0,X-SC,19.68,57.0,-0.54,0.85,0.00,X40,ATH,FMCG
20,DABUR,0.06,-21.80,83.75,43.70,162475.0,-54068.0,194000.0,735.00,-32.48,33.0,X-MC,10.26,70.0,-0.33,1.26,0.06,XY24,BTT,FMCG
19,COLPAL,1.62,-27.48,92.85,39.86,177344.0,-72365.0,191000.0,3683.41,-12.26,34.0,X-MC,1.91,62.0,-0.41,1.24,8.04,XY25,ATH,FMCG
2,ACC,-1.16,-42.32,203.10,74.81,314082.0,-113484.0,154644.0,3906.00,-42.69,34.0,X-SC,11.71,85.0,-0.36,1.00,3.31,XY24,BTT,CEMENT

In [18]:
# top 5 to accumulate based on Spread and CumlRnk
df_tmp = df_portfolio_features[df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])]
df_tmp = df_tmp[(df_tmp['CumlRnk'] < 100)].sort_values(by = 'Spread%', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
19,COLPAL,1.62,-27.48,92.85,39.86,177344.0,-72365.0,191000.0,3683.41,-12.26,34.0,X-MC,1.91,62.0,-0.41,1.24,8.04,XY25,ATH,FMCG
50,KOTAKBANK,1.82,4.43,13.87,18.92,34721.0,10628.0,250330.0,452.46,-11.48,57.0,X-LC,2.17,12.0,0.31,1.62,12.63,X40,ATH,BANKS
23,DMART,-0.40,-3.35,35.98,31.42,108422.0,-10450.0,301340.0,5391.45,-18.91,45.0,X-LC,2.34,14.0,-0.10,1.95,8.74,X40N,ATH,FMCG
1,ABBOTINDIA,-1.08,-12.38,31.66,15.37,49618.0,-22135.0,156720.0,34390.26,-28.62,35.0,X-MC,3.62,58.0,-0.45,1.01,6.16,X40,ATH,PHARMA
26,GILLETTE,-0.17,-11.32,46.29,29.72,104222.0,-28746.0,225150.0,10978.86,-36.01,36.0,X-SC,3.71,83.0,-0.28,1.46,3.47,X40,ATH,FMCG

In [19]:
# top 5 to accumulate based on lowest Gained%
df_tmp = df_portfolio_features[df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])].sort_values(by = 'Gained%', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
36,HINDUNILVR,-0.70,-15.93,44.60,21.56,126173.0,-53619.0,282898.0,2922.00,-42.16,38.0,X-LC,6.48,9.0,-0.42,1.83,0.00,XY25,NTT,FMCG
56,PGHH,-0.94,-38.26,113.82,32.01,150042.0,-81696.0,131824.0,17616.87,-54.65,28.0,X-SC,19.68,57.0,-0.54,0.85,0.00,X40,ATH,FMCG
20,DABUR,0.06,-21.80,83.75,43.70,162475.0,-54068.0,194000.0,735.00,-32.48,33.0,X-MC,10.26,70.0,-0.33,1.26,0.06,XY24,BTT,FMCG
83,VOLTAS,-0.29,-4.60,52.19,45.20,95469.0,-8817.0,182925.0,1856.00,31.44,35.0,X-MC,4.80,79.0,-0.09,1.18,0.26,XY25,NTT,AC
34,HDFCBANK,0.70,-11.45,47.99,31.05,124567.0,-33552.0,259568.0,1073.00,-28.50,36.0,X-LC,12.91,26.0,-0.27,1.68,0.75,X40,BTT,BANKS

In [20]:
# top 5 to accumulate based on lowest CurrAlloc%
df_tmp = df_portfolio_features[df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])].sort_values(by = 'CurrAlloc%', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
56,PGHH,-0.94,-38.26,113.82,32.01,150042.0,-81696.0,131824.0,17616.87,-54.65,28.0,X-SC,19.68,57.0,-0.54,0.85,0.00,X40,ATH,FMCG
2,ACC,-1.16,-42.32,203.10,74.81,314082.0,-113484.0,154644.0,3906.00,-42.69,34.0,X-SC,11.71,85.0,-0.36,1.00,3.31,XY24,BTT,CEMENT
1,ABBOTINDIA,-1.08,-12.38,31.66,15.37,49618.0,-22135.0,156720.0,34390.26,-28.62,35.0,X-MC,3.62,58.0,-0.45,1.01,6.16,X40,ATH,PHARMA
40,ICICIPRULI,0.26,-17.34,57.61,30.28,93810.0,-34168.0,162837.0,787.27,-47.05,46.0,X-MC,12.48,78.0,-0.36,1.05,8.49,X40,ATH,INSURANCE
39,ICICIGI,-0.50,-14.41,38.91,18.89,66639.0,-28845.0,171264.0,2244.41,-14.84,39.0,X-MC,10.44,66.0,-0.43,1.11,2.03,X40,ATH,INSURANCE

In [21]:
# top 5 to accumulate based on CumlRnk
df_tmp = df_portfolio_features.sort_values(by = 'CumlRnk', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
47,ITC,1.72,-25.06,66.39,24.70,197662.0,-99550.0,297728.0,452.00,-30.35,38.0,X-LC,10.83,1.0,-0.50,1.93,1.72,X40,NTT,FMCG
73,TCS,0.39,-32.54,84.10,24.20,262836.0,-150745.0,312528.0,4230.71,-43.98,48.0,X-LC,14.04,2.0,-0.57,2.02,16.54,X40,ATH,IT
45,INFY,0.91,-19.56,74.51,40.38,225646.0,-73630.0,302840.0,1972.00,-40.86,50.0,X-LC,15.88,3.0,-0.33,1.96,14.69,X40,NTT,IT
75,TMPV,-0.33,-23.81,87.35,42.75,276941.0,-99059.0,317048.0,600.00,-84.91,35.0,X-LC,4.59,4.0,-0.36,2.05,9.02,XY24,NTT,AUTO
33,HCLTECH,2.06,-11.39,39.90,23.97,109419.0,-35252.0,274234.0,1853.42,-13.84,56.0,X-LC,11.31,8.0,-0.32,1.78,29.41,X40,ATH,IT

In [22]:
# top 5 for average up
df_tmp = df_portfolio_features[(df_portfolio_features['Dev%_200'] > 5)].sort_values(by = 'CurrAlloc%', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
44,INDUSINDBK,-0.86,-25.58,78.57,32.89,45143.0,-19750.0,57456.0,1800.00,323.08,51.0,L-MC,12.93,258.0,-0.44,0.37,41.65,XR,NTT,BANKS
3,ALKYLAMINE,3.25,-16.69,131.12,92.54,110288.0,-16851.0,84112.0,4520.85,NaN,60.0,NaN,14.38,142.0,-0.15,0.54,59.72,SR,ATH,CHEMICALS
12,BOSCH-HCIL,0.53,-22.36,28.78,-0.01,28559.0,-28573.0,99232.0,2282.00,777.96,79.0,M-SC,8.78,231.0,-1.00,0.64,68.91,OX40N,BTT,AC
67,SIS,-0.31,-5.10,27.78,21.26,29271.0,-5666.0,105366.0,528.00,102.24,37.0,H-SC,20.73,168.0,-0.19,0.68,56.66,OX40N,NTT,MISC
81,VALIANTORG,2.31,-34.22,164.73,74.15,177294.0,-55978.0,107627.0,838.00,NaN,61.0,NaN,7.99,145.0,-0.32,0.70,60.16,XR,NTT,CHEMICALS

In [23]:
# top 5 RSP
df_tmp = df_portfolio_features.sort_values(by = 'RSP', ascending=False)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
12,BOSCH-HCIL,0.53,-22.36,28.78,-0.01,28559.0,-28573.0,99232.0,2282.00,777.96,79.0,M-SC,8.78,231.0,-1.00,0.64,68.91,OX40N,BTT,AC
25,FINCABLES,-1.71,63.54,27.13,107.91,65506.0,93810.0,241454.0,1641.55,19.27,69.0,M-SC,21.63,220.0,1.43,1.56,81.65,OX40N,ATH,CABLES
52,M&M,0.29,8.15,9.87,18.82,25690.0,19604.0,260285.0,3762.88,-6.55,59.0,X-LC,4.88,25.0,0.76,1.68,18.07,X40N,ATH,AUTO
13,BSOFT,1.01,-43.98,165.24,48.59,130201.0,-61858.0,78795.0,819.60,NaN,52.0,NaN,16.61,172.0,-0.48,0.51,15.20,XR,ATH,IT
66,SIEMENS,-0.48,4.25,6.31,10.83,12241.0,7905.0,194000.0,4125.00,-15.50,55.0,H-LC,14.06,51.0,0.65,1.26,36.88,AR,NTT,ELECTRICAL

In [24]:
# Top N allocation
df_tmp = df_portfolio_features.sort_values(by = 'CurrAlloc%', ascending=False)
top_n_values = [10, 25, 50]

sum_df = pd.DataFrame({
    'Top_N': top_n_values,
    'Sum_Alloc%': [df_tmp['CurrAlloc%'].head(n).sum() for n in top_n_values]
})

sum_df

   Top_N  Sum_Alloc%
0     10       19.68
1     25       45.04
2     50       77.67

In [25]:
# market-cap-wise allocation
df_tmp = df_portfolio_features[cols]
df_tmp.groupby(df_tmp['Conviction'].str[-2:])['CurrAlloc%'].sum().sort_values(ascending=False)

Conviction
LC    38.03
MC    22.25
SC    21.56
Name: CurrAlloc%, dtype: float64

In [26]:
# criteria-wise allocation
df_portfolio_features.groupby('Criteria')['CurrAlloc%'].sum().sort_values(ascending=False)

Criteria
X40      26.71
XY24     24.00
X40N     18.71
XR        9.11
OX40N     7.36
XY25      7.15
AR        6.06
SR        0.87
Name: CurrAlloc%, dtype: float64

In [27]:
# conviction-wise allocation
df_portfolio_features.groupby('Conviction')['CurrAlloc%'].sum().sort_values(ascending=False)

Conviction
X-LC    34.38
X-MC    19.68
H-SC     8.53
X-SC     7.60
M-SC     5.43
H-LC     2.84
M-MC     1.17
H-MC     1.03
M-LC     0.81
L-MC     0.37
Name: CurrAlloc%, dtype: float64

In [28]:
# sector-wise stats
df_tmp = df_portfolio_features.groupby('Category')[['CurrAlloc%', 'Current', 'Current P/L', 'FTT Amt']].sum().sort_values(by=['Current', 'Current P/L'], ascending=False)
df_tmp['Current P/L%'] = round(df_tmp['Current P/L'] * 100 / df_tmp['Current'], 2)
df_tmp['FTT%'] = round(df_tmp['FTT Amt'] * 100 / df_tmp['Current'], 2)
cols = ['CurrAlloc%', 'Current P/L%', 'FTT%']
df_tmp[cols].sort_values(by=['CurrAlloc%'], ascending=False)

               CurrAlloc%  Current P/L%    FTT%
Category
FMCG                15.43        -25.15   70.14
IT                  11.25        -37.21  105.26
FINANCE             10.78        -15.77   65.64
AUTO                 8.25         -6.09   44.08
BANKS                6.18        -11.74   59.93
MISC                 5.92        -34.66   88.83
PHARMA               5.87          8.78   17.09
INSURANCE            5.72         -5.06   42.21
PAINTS               5.48        -16.40   36.25
ELECTRICAL           4.19         -9.44   43.70
AC                   1.82        -13.25   43.96
REFINERIES           1.73        -11.27   48.64
BREWERIES            1.70         10.68    7.87
FOOTWEAR             1.67        -71.73  140.59
APPARELS             1.60         -8.80   44.54
CABLES               1.56         38.85   27.13
DURABLES             1.47        -70.45  111.91
TRAVEL               1.42       -105.17  207.90
CERAMICS             1.33        -48.77   93.96
ENGINEERING          1.25        -25.07   82.27
CHEMICALS            1.24        -37.98  149.99
CEMENT               1.00        -73.38  203.10
JEWELLERY            0.97       -114.17  188.58
HEALTHCARE           0.70        -68.15  110.36
ENTERTAINMENT        0.69        -81.58  189.88
TEXTILES             0.39        -51.64   94.88
HOTELS               0.36       -101.50  172.57

In [29]:
# money to be made criteria-wise
df_portfolio_features.groupby('Criteria')['FTT Amt'].agg(['sum', 'count']).sort_values(by='sum', ascending=False)

                sum  count
Criteria
XY24      3621327.0     19
X40       2097635.0     18
XR        1386830.0     13
X40N      1189791.0     12
AR        1068304.0      8
OX40N      653386.0     10
XY25       594126.0      5
SR         280899.0      2

In [30]:
# money to be made conviction-wise
df_portfolio_features.groupby('Conviction')['FTT Amt'].agg(['sum', 'count']).sort_values(by='sum', ascending=False)

                  sum  count
Conviction
X-LC        2412188.0     19
X-MC        1462951.0     14
X-SC        1105601.0      6
H-SC         830608.0      8
M-SC         325559.0      6
H-MC         255282.0      1
M-LC         166100.0      1
M-MC          64837.0      1
H-LC          51434.0      2
L-MC          45143.0      1

In [31]:
# money to be made criteria and conviction-wise
df_portfolio_features.groupby(['Conviction', 'Criteria'])['FTT Amt'].agg(['sum', 'count']).sort_values(by='sum', ascending=False)

                           sum  count
Conviction Criteria
X-LC       X40       1218841.0      9
X-SC       XY24       677707.0      2
H-SC       XY24       524329.0      3
X-MC       X40        510428.0      6
X-LC       XY24       460645.0      2
X-MC       X40N       448786.0      4
X-LC       X40N       416621.0      5
X-MC       XY25       272813.0      2
X-LC       XY25       256476.0      2
H-MC       XY24       255282.0      1
X-SC       X40        254264.0      2
X-MC       XY24       230924.0      2
H-SC       OX40N      211743.0      3
X-SC       X40N       173630.0      2
M-LC       XR         166100.0      1
M-SC       OX40N      150423.0      4
           XY24       117415.0      1
H-SC       XR          94536.0      2
M-MC       XY25        64837.0      1
X-LC       XR          59605.0      1
M-SC       XR          57721.0      1
H-LC       AR          51434.0      2
L-MC       XR          45143.0      1

In [32]:
# notebook execution time

end_time = time.time()
execution_time = round(end_time - start_time, 0)
print(f"Notebook execution time: {execution_time} seconds")

Notebook execution time: 52.0 seconds