<a href="https://colab.research.google.com/github/ankit-rathi/Quantvesting_v2/blob/main/myStocks_Portfolio_Analysis.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
'''
!pip install pandas==2.2.2 -qq
!pip install pyxirr -qq
!pip install ta -qq
!pip install yfinance==0.2.59 -qq
'''

'\n!pip install pandas==2.2.2 -qq\n!pip install pyxirr -qq\n!pip install ta -qq\n!pip install yfinance==0.2.59 -qq\n'

In [2]:
# import libraries

import numpy as np
import pandas as pd
import datetime
import warnings
warnings.filterwarnings('ignore')
import yfinance as yfin
import ta
import matplotlib.pyplot as plt
import requests

In [3]:
# notebook start time
import time
import datetime
import pytz

start_time = time.time()

# function to print date timestamp
def print_date_time():
  tz_NY = pytz.timezone('Asia/Kolkata')
  datetime_NY = datetime.datetime.now(tz_NY)
  print("Run date time (IST):", datetime_NY.strftime("%Y-%m-%d %H:%M:%S"))

In [4]:
# function to get booked and reserved amount
def get_amt():
  # fetch the JSON data from the URL
  url = "https://raw.githubusercontent.com/ankit-rathi/Tradevesting_v1/main/data/myPortfolioAmts.json"
  response = requests.get(url)
  pf_amts = response.json()  # parse the JSON data

  # extract values from the JSON
  py_booked_amt_dm = pf_amts["py_booked_amt_dm"]
  py_booked_amt_sv = pf_amts["py_booked_amt_sv"]
  cy_booked_amt_dm = pf_amts["cy_booked_amt_dm"]
  cy_booked_amt_sv = pf_amts["cy_booked_amt_sv"]
  reserve_amt_dm = pf_amts["reserve_amt_dm"]
  reserve_amt_sv = pf_amts["reserve_amt_sv"]

  # perform calculations
  py_booked_amt = py_booked_amt_dm + py_booked_amt_sv
  cy_booked_amt = cy_booked_amt_dm + cy_booked_amt_sv
  reserve_amt = reserve_amt_dm + reserve_amt_sv
  total_booked_amt = py_booked_amt + cy_booked_amt

  return total_booked_amt, reserve_amt, cy_booked_amt, py_booked_amt

gen_output = 0

In [5]:
# function to format the amount
def format_amt(number):
    abs_number = abs(number)

    if abs_number >= 1_00_00_000:  # Crores
        formatted_amt = f"{number / 1_00_00_000:.2f} C"
    elif abs_number >= 1_00_000:  # Lakhs
        formatted_amt = f"{number / 1_00_000:.2f} L"
    elif abs_number >= 1_000:  # Thousands
        formatted_amt = f"{number / 1_000:.2f} K"
    else:
        formatted_amt = f"{number:.2f}"

    return formatted_amt

# function to set start and end date
def get_start_end_date():
  start_date = (datetime.date.today() + datetime.timedelta(days=-365)).strftime('%Y-%m-%d')
  end_date = (datetime.date.today() + datetime.timedelta(days=1)).strftime('%Y-%m-%d')
  return start_date, end_date

# function to fetch my portfolio csv
def get_mypfs_df():
  mypfs_df = pd.read_csv('https://raw.githubusercontent.com/ankit-rathi/Tradevesting_v1/main/data/myPortfolioStocks.csv')
  return mypfs_df

# function to fetch my prospects csv
def get_mypps_df():
  mypps_df = pd.read_csv('https://raw.githubusercontent.com/ankit-rathi/Tradevesting_v1/main/data/myProspectsScrips.csv')
  return mypps_df

# function to fetch screener data
def get_myscreen_df():
  myscreen_df = pd.read_csv('https://raw.githubusercontent.com/ankit-rathi/Tradevesting_v1/main/data/myScreenerDB.csv')
  return myscreen_df

# function to fetch momentum data
def get_myinvmt_df():
  myinvmt_df = pd.read_csv('https://raw.githubusercontent.com/ankit-rathi/Tradevesting_v1/main/data/myInvestments.csv')
  return myinvmt_df

# function to get the stock ids
def get_stock_ids(df_pf):
  stock_n100 = df_pf['Symbol'].unique()

  exclude = ['CADILAHC','MMTC', 'MASFIN']

  stock_ids = df_pf[~df_pf['Symbol'].isin(exclude) ]['Symbol'].unique()

  #mypf = mypf[mypf.Forecast.notnull()]
  #stock_ids = mypf['Symbol'].unique()

  #stock_ids.sort()
  return stock_ids

# get features from screener data
def get_screener_features():
  myscreen_df = get_myscreen_df()
  cols = ['Symbol', 'EPS', 'MedPE', 'ROCE%', 'ROE%', 'CapType']
  return myscreen_df[cols]

# get relative strength
def get_relative_strength(stock_list):

    # Dictionary to store stock tickers and their corresponding percentage price change
    stock_changes = {}

    # Loop through each stock and fetch its price data
    for stock in stock_list:
        try:
            # Download the stock data for the given date range
            stock_data = yfin.Ticker(stock + '.NS').history(period='1mo', interval='1d')[map(str.title, ['open', 'close', 'low', 'high', 'volume'])]

            # Calculate the percentage change for the stock
            if len(stock_data) > 0:
                start_price = stock_data['Close'].iloc[0]
                end_price = stock_data['Close'].iloc[-1]
                percent_change = round(((end_price - start_price) / start_price) * 100, 2)
                stock_changes[stock] = percent_change
            else:
                stock_changes[stock] = np.nan  # If no data is available, set to NaN

        except Exception as e:
            print(f"Error fetching data for {stock}: {e}")
            stock_changes[stock] = np.nan

    # Create a DataFrame with stock tickers and their percentage changes
    df = pd.DataFrame(list(stock_changes.items()), columns=['Symbol', 'Percent_Change'])

    # Drop any stocks with missing data (NaN values)
    df = df.dropna()

    # Calculate the percentile rank based on percentage change
    df['RSP'] = round(df['Percent_Change'].rank(pct=True) * 100, 2)
    cols = ['Symbol', 'RSP']
    df = df[cols]
    # Sort by percentile rank (optional)
    df = df.sort_values(by='RSP', ascending=False).reset_index(drop=True)

    return df

In [6]:
# function to get stock technicals
def stock_prec_dev(stock_symbol):
    #stock_symbol = 'ULTRACEMCO.NS'
    short_window = 20
    mid_window = 50
    long_window = 200
    moving_avg = 'SMA'

    start = datetime.datetime(*map(int, start_date.split('-')))
    end = datetime.datetime(*map(int, end_date.split('-')))

    stock_df = yfin.Ticker(stock_symbol + '.NS').history(period='max', interval='1d')[map(str.title, ['open', 'close', 'low', 'high', 'volume'])]

    stock_df['Max'] = round(max(stock_df['Close']),2)
    stock_df = stock_df[(stock_df.index <= end_date) & (stock_df.index >= start_date)]
    stock_df['200_SMA'] = round(stock_df['Close'].rolling(window = 200, min_periods = 1).mean(),0)
    stock_df['Dev%_200'] = round((stock_df['Close'] - stock_df['200_SMA'])*100/stock_df['200_SMA'],2)
    stock_df.dropna(axis = 0, inplace = True) # remove any null rows

    stock_df['20_SMA'] = stock_df['Close'].rolling(window=20).mean()
    stock_df['50_SMA'] = stock_df['Close'].rolling(window=50).mean()
    stock_df['Symbol'] = stock_symbol

    stock_df['Close'] = round(stock_df['Close'],2)
    stock_df['Min'] = round(min(stock_df['Close']),2)
    stock_df['RSI_14'] = ta.momentum.RSIIndicator(close=stock_df['Close'], window=14).rsi()
    stock_df['RSI_14'] = round(stock_df['RSI_14'],0)
    stock_df['Prev_Close'] = stock_df['Close'].shift(1)
    stock_df.drop(['Open', 'Low', 'High', 'Volume'], axis=1, inplace=True)
    stock_df = stock_df.tail(1)

    max_SMA = max(stock_df['20_SMA'].item(), stock_df['50_SMA'].item(), stock_df['200_SMA'].item())
    min_SMA = min(stock_df['20_SMA'].item(), stock_df['50_SMA'].item(), stock_df['200_SMA'].item())
    ABS_Spread = max_SMA - min_SMA
    stock_df['Spread%'] = round((ABS_Spread / stock_df['200_SMA'].item()) * 100,2)

    return stock_df

# function to compute stock attributes
def get_common_features(stock_ids, df_mypf):

  df_prec_dev = pd.DataFrame()
  df_tmp = get_screener_features()
  df_rs = get_relative_strength(stock_ids)

  for stock_id in stock_ids:
      tmp = stock_prec_dev(stock_id)
      tmp = tmp.reset_index()
      df_prec_dev = pd.concat([df_prec_dev, tmp], ignore_index = True)
  df_prec_dev = pd.merge(df_prec_dev, df_mypf, on= 'Symbol')
  df_prec_dev = pd.merge(df_prec_dev, df_tmp, on= 'Symbol', how='left')
  df_prec_dev = pd.merge(df_prec_dev, df_rs, on= 'Symbol', how='left')
  #print(df_prec_dev.columns)
  df_prec_dev['Curr_PE'] = round(df_prec_dev['Close']/df_prec_dev['EPS'],1)
  df_prec_dev['Dev%_PE'] = round((df_prec_dev['Curr_PE'] - df_prec_dev['MedPE'])*100/df_prec_dev['MedPE'],2)
  df_prec_dev['Conviction'] = df_prec_dev['Conviction'] + '-' + df_prec_dev['CapType']
  return df_prec_dev

# function to arrange stock features
def arrange_features(df_stocks, common_cols, diff_cols):
  df_stocks_common = df_stocks[common_cols].drop_duplicates()
  df_stocks_diff = df_stocks[diff_cols]
  df_stocks_diff['Investment'] = df_stocks_diff['AvgCost'] * df_stocks_diff['Shares']
  df_stocks_diff = df_stocks_diff.groupby(['Symbol'])[['Shares', 'Investment']].aggregate(['sum']).reset_index()
  df_stocks_diff.columns = ['Symbol', 'Shares', 'Investment']
  df_stocks_diff['AvgCost'] = round(df_stocks_diff['Investment']/df_stocks_diff['Shares'],2)
  df_stocks = pd.merge(df_stocks_diff, df_stocks_common, on='Symbol')
  return df_stocks

# plot fact distribution across dimension
def plot_pie_chart(df, dimension, fact):
  # grouping the data by category and calculating the sum of fact for each type
  grouped_data = df.groupby(dimension)[fact].sum()

  # sorting the grouped data in descending order
  grouped_data = grouped_data.sort_values(ascending=False)

  # creating a pie chart
  grouped_data.plot.pie(autopct='%1.1f%%', startangle=90, figsize=(6, 6))

  # adding a title and displaying the plot
  plt.title(f'{dimension} {fact} Distribution')
  plt.ylabel('')  # To hide the y-label
  plt.show()

In [7]:
# function to get portfolio features

def get_portfolio_features(df_common_features):

  print_date_time()
  print('-------------------')

  #df_common_features["Target"] = df_common_features["Target"].fillna(df_common_features["Max"])
  df_common_features['NTT'] = np.where(df_common_features['Strategy']== 'NTT', df_common_features["Target"], df_common_features['Max'])
  df_common_features['LTT'] = np.where(df_common_features['Strategy']== 'BTT', df_common_features["Target"], df_common_features['Max'])
  df_common_features['BOL'] = df_common_features['Min']

  tmp_df = df_common_features[df_common_features['Symbol'].isin(mypf_df[mypf_df['InPortfolio'] != 'NA'].Symbol.values)]
  print('qualified stocks: '+str(len(tmp_df['Symbol'].unique())))
  tmp_df1 = tmp_df[tmp_df['LatestQtr'] == 1]
  print('with latest results: '+str(len(tmp_df1['Symbol'].unique())))
  tmp_df1 = tmp_df1[tmp_df1['StarStock'] == 1]
  print('still star stocks: '+str(len(tmp_df1['Symbol'].unique())))
  tmp_df['Investment'] = tmp_df['AvgCost'] * tmp_df['Shares']
  tmp_df['Current'] = round(tmp_df['Close'] * tmp_df['Shares'],0)
  tmp_df['Previous'] = tmp_df['Prev_Close'] * tmp_df['Shares']
  tmp_df['EstimatedST'] = tmp_df['NTT'] * tmp_df['Shares']
  tmp_df['EstimatedLT'] = tmp_df['LTT'] * tmp_df['Shares']
  tmp_df['Current P/L'] = round((tmp_df['Current'] - tmp_df['Investment']),0)
  tmp_df['Today P/L%'] = round((tmp_df['Current'] - tmp_df['Previous'])*100/tmp_df['Previous'],2)
  tmp_df['Current P/L%'] = round((tmp_df['Current'] - tmp_df['Investment'])*100/tmp_df['Investment'],2)
  tmp_df['EstimatedST P/L%'] = round((tmp_df['EstimatedST'] - tmp_df['Investment'])*100/tmp_df['Investment'],2)
  tmp_df['EstimatedLT P/L%'] = round((tmp_df['EstimatedLT'] - tmp_df['Investment'])*100/tmp_df['Investment'],2)
  tmp_df['NTT%'] = round((tmp_df['NTT'] - tmp_df['Close'])*100/tmp_df['Close'],2)
  tmp_df['LTT%'] = round((tmp_df['LTT'] - tmp_df['Close'])*100/tmp_df['Close'],2)
  tmp_df['Gained%'] = round((tmp_df['Close'] - tmp_df['BOL'])*100/tmp_df['BOL'],2)
  investment = round(sum(tmp_df['AvgCost']*tmp_df['Shares']),0)
  current = round(sum(tmp_df['Close']*tmp_df['Shares']),0)
  tmp_df['InitAlloc%'] = round(tmp_df['Investment']*100/investment,2)
  tmp_df['CurrAlloc%'] = round(tmp_df['Current']*100/current,2)
  tmp_df['FTT'] = tmp_df['LTT']
  tmp_df.loc[tmp_df['Strategy'] == 'NTT', 'FTT'] = tmp_df['NTT']
  tmp_df['FTT%'] = tmp_df['LTT%']
  tmp_df.loc[tmp_df['Strategy'] == 'NTT', 'FTT%'] = tmp_df['NTT%']
  tmp_df['FTT Amt'] = round(tmp_df['FTT%'] * tmp_df['Current']/100,0)
  tmp_df['OTT%'] = round((tmp_df['FTT'] - tmp_df['AvgCost'])*100/tmp_df['AvgCost'],2)
  tmp_df['RRR Ind'] = round(tmp_df['Current P/L']/tmp_df['FTT Amt'],2)
  tmp_df['Risk Ind'] = round(tmp_df['Current P/L%']*tmp_df['CurrAlloc%'],0)

  return tmp_df

# function to print portfolio features
def print_portfolio_stats(df_portfolio_features, myinvmt_df):
  from pyxirr import xirr

  total_booked_amt, reserve_amt, cy_booked_amt, py_booked_amt = get_amt()

  dates = myinvmt_df['Date'].values
  dates = np.append(dates, datetime.date.today().strftime('%d-%b-%y'))
  investment = myinvmt_df['Investment'].values
  dates= pd.to_datetime(dates)

  current = round(sum(df_portfolio_features['Close']*df_portfolio_features['Shares']),0) + reserve_amt
  investment_xirr = np.append(investment, current)
  cagr = round(xirr(pd.DataFrame({"dates": dates, "amounts": investment_xirr}))*100,2)

  investment = -sum(investment)
  invested = round(sum(df_portfolio_features['AvgCost']*df_portfolio_features['Shares']),0) + reserve_amt
  previous = round(sum(df_portfolio_features['Prev_Close']*df_portfolio_features['Shares']),0) + reserve_amt
  cy_invested = investment + py_booked_amt

  today_pnl_amount = current-previous
  today_pnl_percentage = round((current-previous)*100/previous,2)

  curr_pnl_amount = current-invested
  curr_pnl_percentage = round((curr_pnl_amount)*100/(cy_invested),2)

  cy_pnl_amount = cy_booked_amt + curr_pnl_amount
  cy_pnl_percentage = round((cy_pnl_amount)*100/cy_invested,2)

  overall_pnl_amount = total_booked_amt + curr_pnl_amount
  overall_pnl_percentage = round((overall_pnl_amount)*100/investment,2)

  estimate_st = round(sum(df_portfolio_features['FTT']*df_portfolio_features['Shares']),0)  + reserve_amt
  est_st_pnl_amount = estimate_st-current
  est_st_pnl_percentage = round((est_st_pnl_amount)*100/current,2)

  estimate_lt = round(sum(df_portfolio_features['LTT']*df_portfolio_features['Shares']),0)  + reserve_amt
  est_lt_pnl_amount = estimate_lt-current
  est_lt_pnl_percentage = round((est_lt_pnl_amount)*100/current,2)

  total_profit = round(sum(df_portfolio_features[df_portfolio_features['Current P/L%'] > 0]['Current']) - sum(df_portfolio_features[df_portfolio_features['Current P/L%'] > 0]['Investment']),0)
  total_loss = round(sum(df_portfolio_features[df_portfolio_features['Current P/L%'] < 0]['Current']) - sum(df_portfolio_features[df_portfolio_features['Current P/L%'] < 0]['Investment']),0)

  cy_booked_percentage = round((cy_booked_amt)*100/current,2)
  py_booked_percentage = round((py_booked_amt)*100/investment,2)
  total_booked_percentage = round((total_booked_amt)*100/investment,2)

  print('-------------------')
  print('Initial Investment: ', format_amt(investment))
  print('CY Investment: ', format_amt(cy_invested))
  print('Reserve: ', format_amt(reserve_amt))
  print('Current: ',  format_amt(current))
  print('-------------------')
  print('Today PnL: '+ '{} ({}%)'.format(format_amt(today_pnl_amount), today_pnl_percentage))
  print('Current PnL: '+ '{} ({}%)'.format(format_amt(curr_pnl_amount), curr_pnl_percentage))
  print('CY Booked + Current PnL: '+ '{} ({}%)'.format(format_amt(cy_pnl_amount), cy_pnl_percentage))
  print('-------------------')
  print('Total profit: ', format_amt(total_profit))
  print('Total loss: ', format_amt(total_loss))
  print('-------------------')
  print('Total Booked + Current PnL: '+ '{} ({}%)'.format(format_amt(overall_pnl_amount), overall_pnl_percentage))
  print('Total Booked PnL: '+ '{} ({}%)'.format(format_amt(total_booked_amt), total_booked_percentage))
  print('Curr Year Booked PnL: '+ '{} ({}%)'.format(format_amt(cy_booked_amt), cy_booked_percentage))
  print('Prev Year Booked PnL: '+ '{} ({}%)'.format(format_amt(py_booked_amt), py_booked_percentage))
  print('===================')
  print('Est FTT: ',  format_amt(estimate_st))
  print('Est FTT PnL: '+ '{} ({}%)'.format(format_amt(est_st_pnl_amount), est_st_pnl_percentage))

  print('===================')
  print('Deployed: ', format_amt(investment))

  print('Current: ', format_amt(current))

  print('CAGR/XIRR %: '+'{}%'.format(cagr))

In [8]:
# get start and end date
start_date, end_date = get_start_end_date()

# get portfolio and prospects data
mypfs_df = get_mypfs_df()
mypps_df = get_mypps_df()
myinvmt_df = get_myinvmt_df()

# merge above datasets
mypf_df = pd.merge(mypfs_df, mypps_df, on="Symbol")

# seggregate dm and sv portfolio
dm_pf = mypf_df[mypf_df['InPortfolio'] == 'DM']
sv_pf = mypf_df[mypf_df['InPortfolio'] == 'SV']

# build portfolio stock dataframe
dm_stocks = get_stock_ids(dm_pf)
sv_stocks = get_stock_ids(sv_pf)
df_stocks = pd.concat([dm_pf,sv_pf], ignore_index = True)

# arrange common and diff stock features
common_cols = ['Symbol', 'Target', 'Criteria', 'Strategy', 'CumlRnk', 'LatestQtr', 'StarStock', 'Conviction', 'Category', 'InFolio', 'XIRR', 'MBQ']
diff_cols = ['Symbol', 'AvgCost', 'Shares']
df_stocks = arrange_features(df_stocks, common_cols, diff_cols)

# get common features
stock_ids = df_stocks['Symbol'].values
df_common_features = get_common_features(stock_ids, df_stocks)

df_common_features.reset_index(drop=True, inplace=True)
df_common_features.drop(['Date'], axis=1, inplace=True)
# get and print portfolio features
df_portfolio_features = get_portfolio_features(df_common_features)

print_portfolio_stats(df_portfolio_features, myinvmt_df)

df = df_portfolio_features
#plot_pie_chart(df, 'CapType', 'Current')
list_ox40n = list(df[df['MBQ'].str.contains('OX40N', na=False)]['Symbol'].values)

Run date time (IST): 2026-04-08 13:24:25
-------------------
qualified stocks: 86
with latest results: 26
still star stocks: 16

-------------------
Initial Investment:  1.36 C
CY Investment:  1.62 C
Reserve:  1.61 K
Current:  1.36 C
-------------------
Today PnL: 4.69 L (3.56%)
Current PnL: -40.81 L (-25.12%)
CY Booked + Current PnL: -24.92 L (-15.34%)
-------------------
Total profit:  1.02 L
Total loss:  -41.83 L
-------------------
Total Booked + Current PnL: 2.06 L (1.52%)
Total Booked PnL: 42.87 L (31.64%)
Curr Year Booked PnL: 15.89 L (11.66%)
Prev Year Booked PnL: 26.98 L (19.91%)
===================
Est FTT:  2.48 C
Est FTT PnL: 1.12 C (81.85%)
===================
Deployed:  1.36 C
Current:  1.36 C
CAGR/XIRR %: 0.29%

In [9]:
# top 5 near their targets
cols = ['Symbol', 'Today P/L%', 'Current P/L%', 'FTT%', 'OTT%', 'FTT Amt', 'Current P/L', 'Current', 'FTT', 'Dev%_PE', 'RSI_14','Conviction', 'Spread%',  'CumlRnk', 'RRR Ind', 'CurrAlloc%', 'Gained%', 'Criteria', 'Strategy', 'Category']
df_tmp = df_portfolio_features[~df_portfolio_features['Symbol'].isin(['ENRIN','BLUSPRING','DIGITIDE'])]
df_tmp = df_tmp.sort_values(by = 'FTT Amt', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
50,MASFIN,4.31,-4.41,27.17,21.57,25447.0,-4320.0,93660.0,397.04,-17.80,55.0,H-SC,4.84,167.0,-0.17,0.69,23.23,XR,ATH,FINANCE
77,TTKPRESTIG,3.02,-36.98,58.83,0.09,37362.0,-37268.0,63509.0,770.00,47.49,50.0,M-SC,22.12,250.0,-1.00,0.47,13.09,OX40N,NTT,DURABLES
67,SONACOMS,4.05,-7.27,50.00,39.09,46900.0,-7359.0,93800.0,804.02,-26.55,60.0,M-MC,7.69,193.0,-0.16,0.69,32.69,AR,ATH,AUTO
5,ANGELONE,7.42,8.35,14.61,24.18,48280.0,25462.0,330462.0,303.00,-84.36,66.0,X-SC,7.68,97.0,0.53,2.42,26.43,X40N,NTT,FINANCE
37,ICICIGI,1.91,-6.79,28.04,19.34,52300.0,-13591.0,186518.0,2252.93,-21.55,44.0,X-MC,6.89,66.0,-0.26,1.37,4.17,X40,ATH,INSURANCE

In [10]:
# top 5 today
df_tmp = df_portfolio_features.sort_values(by = 'Today P/L%', ascending=False)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
25,EASEMYTRIP,19.79,-55.57,227.95,45.70,179059.0,-98263.0,78552.0,26.4,-18.55,63.0,M-SC,14.49,204.0,-0.55,0.58,37.61,XY24,NTT,TRAVEL
14,BOSCH-HCIL,9.99,-44.05,78.73,-0.01,56293.0,-56304.0,71501.0,2282.0,14530.43,53.0,M-SC,9.53,231.0,-1.00,0.52,21.70,OX40N,BTT,AC
19,COFFEEDAY,9.32,-56.56,211.41,35.27,104278.0,-64224.0,49325.0,80.0,-65.79,51.0,L-SC,32.94,266.0,-0.62,0.36,21.64,XR,NTT,HOTELS
11,BANDHANBNK,8.37,-22.26,147.51,92.42,319443.0,-62002.0,216557.0,400.0,86.06,52.0,H-SC,2.43,174.0,-0.19,1.59,19.30,XY24,NTT,BANKS
75,TMPV,8.29,-23.90,79.48,36.58,215218.0,-85058.0,270783.0,600.0,-84.72,54.0,X-LC,12.42,4.0,-0.40,1.99,12.86,XY24,NTT,AUTO

In [11]:
# bottom 5 today
df_tmp = df_portfolio_features.sort_values(by = 'Today P/L%', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
24,DMART,-1.74,5.48,22.87,29.60,60214.0,13686.0,263286.0,5391.45,-11.04,67.0,X-LC,5.36,14.0,0.23,1.93,20.34,X40N,ATH,FMCG
84,WIPRO,-0.52,-16.47,106.23,72.27,150362.0,-27904.0,141544.0,420.00,-24.55,56.0,M-LC,17.76,98.0,-0.19,1.04,8.60,XR,NTT,IT
73,TCS,0.46,-25.10,68.98,26.57,239363.0,-116269.0,347004.0,4311.59,-36.74,54.0,X-LC,18.49,2.0,-0.49,2.55,8.30,X40,ATH,IT
8,AWL,0.51,-38.02,169.47,67.02,374249.0,-135474.0,220835.0,485.00,-66.62,46.0,X-SC,25.67,81.0,-0.36,1.62,4.46,XY24,NTT,FMCG
43,INFY,0.52,-8.35,46.48,34.24,133287.0,-26126.0,286762.0,1972.00,-27.79,58.0,X-LC,14.50,3.0,-0.20,2.10,10.28,X40,NTT,IT

In [12]:
# top 5 to exit based on CumlRnk
df_tmp = df_portfolio_features[~df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])]
df_tmp = df_tmp[(df_tmp['Current P/L%'] > -1) & (df_tmp['Current P/L%'] < 1)].sort_values(by = 'CumlRnk', ascending=False)
df_tmp[cols].head()

Empty DataFrame
Columns: [Symbol, Today P/L%, Current P/L%, FTT%, OTT%, FTT Amt, Current P/L, Current, FTT, Dev%_PE, RSI_14, Conviction, Spread%, CumlRnk, RRR Ind, CurrAlloc%, Gained%, Criteria, Strategy, Category]
Index: []

In [13]:
# OX40N stocks to exit
df_tmp = df_portfolio_features[(df_portfolio_features['Symbol'].isin(list_ox40n))].sort_values(by = 'Current P/L%', ascending=False)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
26,FINCABLES,4.13,6.90,94.50,107.91,149147.0,10184.0,157828.0,1641.55,-3.60,52.0,M-SC,3.11,220.0,0.07,1.16,18.74,OX40N,ATH,CABLES
66,SIS,2.10,-32.42,79.44,21.26,59607.0,-35998.0,75034.0,528.00,1759.07,53.0,H-SC,14.72,168.0,-0.60,0.55,11.56,OX40N,NTT,MISC
18,CERA,5.75,-33.50,86.30,23.89,100950.0,-58927.0,116976.0,9475.00,-35.80,62.0,H-SC,18.53,153.0,-0.58,0.86,12.41,OX40N,NTT,CERAMICS
72,TATAELXSI,1.57,-36.21,106.99,32.03,89970.0,-47743.0,84092.0,9161.00,-20.19,53.0,H-SC,21.34,158.0,-0.53,0.62,11.30,OX40N,NTT,IT
77,TTKPRESTIG,3.02,-36.98,58.83,0.09,37362.0,-37268.0,63509.0,770.00,47.49,50.0,M-SC,22.12,250.0,-1.00,0.47,13.09,OX40N,NTT,DURABLES

In [14]:
# top 5 to book for rotation
df_tmp = df_portfolio_features[(df_portfolio_features['Current P/L%'] > 20) ].sort_values(by = 'CumlRnk', ascending=False)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
1,ABB,4.39,20.07,21.23,45.57,66691.0,52517.0,314136.0,7934.0,-22.86,64.0,H-MC,14.33,125.0,0.79,2.3,39.5,AR,NTT,ELECTRICAL

In [15]:
# top 5 to monitor for exit
df_tmp = df_portfolio_features[~df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])]
df_tmp = df_tmp[(df_tmp['Current P/L%'] > 0) ].sort_values(by = 'Dev%_PE', ascending=False)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
26,FINCABLES,4.13,6.90,94.50,107.91,149147.0,10184.0,157828.0,1641.55,-3.60,52.0,M-SC,3.11,220.0,0.07,1.16,18.74,OX40N,ATH,CABLES
1,ABB,4.39,20.07,21.23,45.57,66691.0,52517.0,314136.0,7934.00,-22.86,64.0,H-MC,14.33,125.0,0.79,2.30,39.50,AR,NTT,ELECTRICAL

In [16]:
# top 5 to book for rotation from weak conviction
df_tmp = df_portfolio_features[~df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])]
df_tmp = df_tmp[~df_tmp['Criteria'].isin(['XY25','XY24','X40', 'X40N'])].sort_values(by = 'RRR Ind', ascending=False)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
1,ABB,4.39,20.07,21.23,45.57,66691.0,52517.0,314136.0,7934.00,-22.86,64.0,H-MC,14.33,125.0,0.79,2.30,39.50,AR,NTT,ELECTRICAL
26,FINCABLES,4.13,6.90,94.50,107.91,149147.0,10184.0,157828.0,1641.55,-3.60,52.0,M-SC,3.11,220.0,0.07,1.16,18.74,OX40N,ATH,CABLES
40,INDIAMART,2.44,-9.61,128.70,106.72,143482.0,-11850.0,111486.0,4810.62,-59.18,53.0,H-SC,12.83,140.0,-0.08,0.82,8.15,AR,ATH,MISC
85,ZYDUSLIFE,1.62,-6.40,44.90,35.63,88081.0,-13403.0,196171.0,1286.17,-18.47,49.0,H-MC,6.06,120.0,-0.15,1.44,9.21,AR,ATH,PHARMA
67,SONACOMS,4.05,-7.27,50.00,39.09,46900.0,-7359.0,93800.0,804.02,-26.55,60.0,M-MC,7.69,193.0,-0.16,0.69,32.69,AR,ATH,AUTO

In [17]:
# top 5 to accumulate based on lowest RSI_14
df_tmp = df_portfolio_features[df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])].sort_values(by = 'RSI_14', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
53,PGHH,0.73,-26.73,80.16,32.01,125415.0,-57064.0,156456.0,17616.87,-50.48,38.0,X-MC,20.24,57.0,-0.46,1.15,7.01,X40,ATH,FMCG
21,DABUR,3.62,-16.08,71.23,43.70,148291.0,-39882.0,208186.0,735.00,-23.90,40.0,X-MC,12.89,70.0,-0.27,1.53,4.58,XY24,BTT,FMCG
38,ICICIPRULI,4.80,-10.40,45.90,30.73,81019.0,-20492.0,176513.0,790.00,-34.44,40.0,X-MC,10.81,78.0,-0.25,1.30,7.56,X40,ATH,INSURANCE
82,VOLTAS,4.26,-0.48,45.89,45.20,87572.0,-912.0,190830.0,1856.00,13.96,41.0,X-MC,4.99,79.0,-0.01,1.40,6.29,XY25,NTT,AC
36,HONAUT,2.11,-27.94,109.99,51.31,152831.0,-53888.0,138950.0,58357.33,-40.13,42.0,X-SC,18.67,90.0,-0.35,1.02,5.57,X40N,ATH,ELECTRICAL

In [18]:
# top 5 to accumulate based on Spread and CumlRnk
df_tmp = df_portfolio_features[df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])]
df_tmp = df_tmp[(df_tmp['CumlRnk'] < 100)].sort_values(by = 'Spread%', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
65,SIEMENS,3.53,-14.45,46.71,25.51,74365.0,-26890.0,159205.0,4671.50,33.78,54.0,H-LC,0.98,51.0,-0.36,1.17,17.24,AR,ATH,ELECTRICAL
59,RELIANCE,3.12,-13.64,45.10,25.30,78268.0,-27419.0,173544.0,1952.00,-15.80,43.0,X-LC,4.45,21.0,-0.35,1.27,14.25,XY25,BTT,REFINERIES
78,UNITDSPR,1.52,-7.67,30.80,20.77,66586.0,-17957.0,216187.0,1644.00,-18.18,43.0,X-MC,4.56,64.0,-0.27,1.59,3.13,X40N,NTT,BREWERIES
82,VOLTAS,4.26,-0.48,45.89,45.20,87572.0,-912.0,190830.0,1856.00,13.96,41.0,X-MC,4.99,79.0,-0.01,1.40,6.29,XY25,NTT,AC
24,DMART,-1.74,5.48,22.87,29.60,60214.0,13686.0,263286.0,5391.45,-11.04,67.0,X-LC,5.36,14.0,0.23,1.93,20.34,X40N,ATH,FMCG

In [19]:
# top 5 to accumulate based on lowest Gained%
df_tmp = df_portfolio_features[df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])].sort_values(by = 'Gained%', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
2,ABBOTINDIA,0.72,-13.28,36.15,18.07,56069.0,-23755.0,155100.0,35195.00,-26.29,43.0,X-MC,11.09,58.0,-0.42,1.14,1.43,X40,ATH,PHARMA
78,UNITDSPR,1.52,-7.67,30.80,20.77,66586.0,-17957.0,216187.0,1644.00,-18.18,43.0,X-MC,4.56,64.0,-0.27,1.59,3.13,X40N,NTT,BREWERIES
37,ICICIGI,1.91,-6.79,28.04,19.34,52300.0,-13591.0,186518.0,2252.93,-21.55,44.0,X-MC,6.89,66.0,-0.26,1.37,4.17,X40,ATH,INSURANCE
8,AWL,0.51,-38.02,169.47,67.02,374249.0,-135474.0,220835.0,485.00,-66.62,46.0,X-SC,25.67,81.0,-0.36,1.62,4.46,XY24,NTT,FMCG
21,DABUR,3.62,-16.08,71.23,43.70,148291.0,-39882.0,208186.0,735.00,-23.90,40.0,X-MC,12.89,70.0,-0.27,1.53,4.58,XY24,BTT,FMCG

In [20]:
# top 5 to accumulate based on lowest CurrAlloc%
df_tmp = df_portfolio_features[df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])].sort_values(by = 'CurrAlloc%', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
58,RELAXO,4.23,-63.57,318.09,52.31,168209.0,-92279.0,52881.0,1176.00,-61.18,46.0,X-SC,32.84,92.0,-0.55,0.39,18.23,X40N,NTT,FOOTWEAR
12,BATAINDIA,4.49,-54.87,199.62,35.20,115905.0,-70607.0,58063.0,2096.00,-23.90,50.0,X-SC,34.38,91.0,-0.61,0.43,15.15,X40,NTT,FOOTWEAR
54,QUESS,3.81,-22.35,123.96,73.90,102790.0,-23871.0,82922.0,424.00,-58.13,55.0,X-SC,22.41,80.0,-0.23,0.61,11.55,XY24,NTT,MISC
36,HONAUT,2.11,-27.94,109.99,51.31,152831.0,-53888.0,138950.0,58357.33,-40.13,42.0,X-SC,18.67,90.0,-0.35,1.02,5.57,X40N,ATH,ELECTRICAL
2,ABBOTINDIA,0.72,-13.28,36.15,18.07,56069.0,-23755.0,155100.0,35195.00,-26.29,43.0,X-MC,11.09,58.0,-0.42,1.14,1.43,X40,ATH,PHARMA

In [21]:
# top 5 to accumulate based on CumlRnk
df_tmp = df_portfolio_features.sort_values(by = 'CumlRnk', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
45,ITC,1.76,-20.01,48.83,19.06,132874.0,-68051.0,272115.0,452.00,-55.92,51.0,X-LC,19.76,1.0,-0.51,2.00,5.56,X40,NTT,FMCG
73,TCS,0.46,-25.10,68.98,26.57,239363.0,-116269.0,347004.0,4311.59,-36.74,54.0,X-LC,18.49,2.0,-0.49,2.55,8.30,X40,ATH,IT
43,INFY,0.52,-8.35,46.48,34.24,133287.0,-26126.0,286762.0,1972.00,-27.79,58.0,X-LC,14.50,3.0,-0.20,2.10,10.28,X40,NTT,IT
75,TMPV,8.29,-23.90,79.48,36.58,215218.0,-85058.0,270783.0,600.00,-84.72,54.0,X-LC,12.42,4.0,-0.40,1.99,12.86,XY24,NTT,AUTO
33,HCLTECH,0.92,-5.58,31.16,23.83,71175.0,-13505.0,228419.0,1908.19,-0.74,61.0,X-LC,10.55,8.0,-0.19,1.68,10.91,X40,ATH,IT

In [22]:
# top 5 for average up
df_tmp = df_portfolio_features[(df_portfolio_features['Dev%_200'] > 5)].sort_values(by = 'CurrAlloc%', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
67,SONACOMS,4.05,-7.27,50.00,39.09,46900.0,-7359.0,93800.0,804.02,-26.55,60.0,M-MC,7.69,193.0,-0.16,0.69,32.69,AR,ATH,AUTO
24,DMART,-1.74,5.48,22.87,29.60,60214.0,13686.0,263286.0,5391.45,-11.04,67.0,X-LC,5.36,14.0,0.23,1.93,20.34,X40N,ATH,FMCG
1,ABB,4.39,20.07,21.23,45.57,66691.0,52517.0,314136.0,7934.00,-22.86,64.0,H-MC,14.33,125.0,0.79,2.30,39.50,AR,NTT,ELECTRICAL
5,ANGELONE,7.42,8.35,14.61,24.18,48280.0,25462.0,330462.0,303.00,-84.36,66.0,X-SC,7.68,97.0,0.53,2.42,26.43,X40N,NTT,FINANCE

In [23]:
# top 5 RSP
df_tmp = df_portfolio_features.sort_values(by = 'RSP', ascending=False)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
80,VALIANTORG,1.09,-45.05,216.91,74.15,195015.0,-73699.0,89906.0,838.00,-261.57,60.0,H-SC,25.04,145.0,-0.38,0.66,33.79,XR,NTT,CHEMICALS
5,ANGELONE,7.42,8.35,14.61,24.18,48280.0,25462.0,330462.0,303.00,-84.36,66.0,X-SC,7.68,97.0,0.53,2.42,26.43,X40N,NTT,FINANCE
52,PAGEIND,1.54,-7.20,44.52,34.11,110882.0,-19319.0,249060.0,51418.64,-33.43,69.0,X-MC,18.56,55.0,-0.17,1.83,17.81,X40,ATH,APPARELS
30,HAPPSTMNDS,1.39,-52.18,286.56,84.85,175627.0,-66877.0,61288.0,1480.71,-43.09,49.0,H-SC,23.19,152.0,-0.38,0.45,13.50,AR,ATH,IT
18,CERA,5.75,-33.50,86.30,23.89,100950.0,-58927.0,116976.0,9475.00,-35.80,62.0,H-SC,18.53,153.0,-0.58,0.86,12.41,OX40N,NTT,CERAMICS

In [24]:
# Top N allocation
df_tmp = df_portfolio_features.sort_values(by = 'CurrAlloc%', ascending=False)
top_n_values = [10, 25, 50]

sum_df = pd.DataFrame({
    'Top_N': top_n_values,
    'Sum_Alloc%': [df_tmp['CurrAlloc%'].head(n).sum() for n in top_n_values]
})

sum_df

   Top_N  Sum_Alloc%
0     10       21.07
1     25       46.00
2     50       77.76

In [25]:
# market-cap-wise allocation
df_tmp = df_portfolio_features[cols]
df_tmp.groupby(df_tmp['Conviction'].str[-2:])['CurrAlloc%'].sum().sort_values(ascending=False)

Conviction
SC    45.01
MC    29.37
LC    25.66
Name: CurrAlloc%, dtype: float64

In [26]:
# criteria-wise allocation
df_portfolio_features.groupby('Criteria')['CurrAlloc%'].sum().sort_values(ascending=False)

Criteria
XY24     27.27
X40      25.18
X40N     15.37
AR        9.17
XR        8.45
XY25      7.03
OX40N     6.77
SR        0.80
Name: CurrAlloc%, dtype: float64

In [27]:
# conviction-wise allocation
df_portfolio_features.groupby('Conviction')['CurrAlloc%'].sum().sort_values(ascending=False)

Conviction
X-LC    23.45
H-SC    22.05
X-MC    21.93
X-SC    12.29
M-SC    10.11
H-MC     5.02
M-MC     2.07
H-LC     1.17
M-LC     1.04
L-SC     0.56
L-MC     0.35
Name: CurrAlloc%, dtype: float64

In [28]:
# sector-wise stats
df_tmp = df_portfolio_features.groupby('Category')[['CurrAlloc%', 'Current', 'Current P/L', 'FTT Amt']].sum().sort_values(by=['Current', 'Current P/L'], ascending=False)
df_tmp['Current P/L%'] = round(df_tmp['Current P/L'] * 100 / df_tmp['Current'], 2)
df_tmp['FTT%'] = round(df_tmp['FTT Amt'] * 100 / df_tmp['Current'], 2)
cols = ['CurrAlloc%', 'Current P/L%', 'FTT%']
df_tmp[cols].sort_values(by=['CurrAlloc%'], ascending=False)

               CurrAlloc%  Current P/L%    FTT%
Category
FMCG                14.86        -23.34   67.11
FINANCE             13.39        -17.72   65.70
IT                  12.00        -37.92  108.12
MISC                 7.10        -38.43   98.56
ELECTRICAL           6.43        -10.44   52.73
PAINTS               5.21        -39.01   63.15
BANKS                4.63        -22.06   84.01
INSURANCE            4.55         -9.62   47.13
PHARMA               3.97         -8.59   42.78
AUTO                 3.77        -27.64   78.28
HEALTHCARE           1.95        -34.59   69.72
AC                   1.92        -21.81   54.84
TRAVEL               1.86        -76.71  165.19
FOOTWEAR             1.84        -76.70  147.56
APPARELS             1.83         -7.76   44.52
DURABLES             1.76        -61.40  100.67
BREWERIES            1.59         -8.31   30.80
REALTY               1.40        -16.30   35.40
CERAMICS             1.37        -64.98  115.10
REFINERIES           1.27        -15.80   45.10
CEMENT               1.25        -56.94  174.36
ENGINEERING          1.19        -48.70  116.72
CABLES               1.16          6.45   94.50
CHEMICALS            1.10        -77.22  221.80
JEWELLERY            1.06       -121.61  198.60
ENTERTAINMENT        0.77        -83.27  192.56
TEXTILES             0.45        -48.86   91.31
HOTELS               0.36       -130.21  211.41

In [29]:
# money to be made criteria-wise
df_portfolio_features.groupby('Criteria')['FTT Amt'].agg(['sum', 'count']).sort_values(by='sum', ascending=False)

                sum  count
Criteria
XY24      3881700.0     21
X40       1744572.0     16
XR        1338913.0     12
AR        1323121.0     10
X40N      1204493.0     10
OX40N      871259.0     10
XY25       481474.0      5
SR         310962.0      2

In [30]:
# money to be made conviction-wise
df_portfolio_features.groupby('Conviction')['FTT Amt'].agg(['sum', 'count']).sort_values(by='sum', ascending=False)

                  sum  count
Conviction
H-SC        3790970.0     24
X-MC        1746496.0     15
X-LC        1579786.0     13
M-SC        1540275.0     14
X-SC        1506161.0     10
H-MC         393872.0      3
L-SC         214789.0      2
M-LC         150362.0      1
M-MC         104228.0      2
H-LC          74365.0      1
L-MC          55190.0      1

In [31]:
# money to be made criteria and conviction-wise
df_portfolio_features.groupby(['Conviction', 'Criteria'])['FTT Amt'].agg(['sum', 'count']).sort_values(by='sum', ascending=False)

                           sum  count
Conviction Criteria
H-SC       XY24      1296964.0      6
           AR         969436.0      5
M-SC       XY24       886404.0      6
X-LC       X40        848194.0      7
H-SC       XR         841450.0      7
X-SC       XY24       839480.0      4
X-MC       X40        681576.0      7
           X40N       531595.0      4
X-SC       X40N       451879.0      4
M-SC       OX40N      388590.0      5
H-SC       OX40N      372158.0      4
X-LC       XY24       355688.0      2
H-SC       SR         310962.0      2
X-MC       XY25       269261.0      2
           XY24       264064.0      2
H-MC       XY24       239100.0      1
X-LC       X40N       221019.0      2
X-SC       X40        214802.0      2
M-SC       XR         187633.0      2
X-LC       XY25       154885.0      2
H-MC       AR         154772.0      2
M-LC       XR         150362.0      1
L-SC       OX40N      110511.0      1
           XR         104278.0      1
M-SC       AR          77648.0      1
H-LC       AR          74365.0      1
M-MC       XY25        57328.0      1
L-MC       XR          55190.0      1
M-MC       AR          46900.0      1

In [32]:
# notebook execution time

end_time = time.time()
execution_time = round(end_time - start_time, 0)
print(f"Notebook execution time: {execution_time} seconds")

Notebook execution time: 39.0 seconds