<a href="https://colab.research.google.com/github/ankit-rathi/Quantvesting_v2/blob/main/myStocks_Portfolio_Analysis.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
'''
!pip install pandas==2.2.2 -qq
!pip install pyxirr -qq
!pip install ta -qq
!pip install yfinance==0.2.59 -qq
'''

'\n!pip install pandas==2.2.2 -qq\n!pip install pyxirr -qq\n!pip install ta -qq\n!pip install yfinance==0.2.59 -qq\n'

In [2]:
# import libraries

import numpy as np
import pandas as pd
import datetime
import warnings
warnings.filterwarnings('ignore')
import yfinance as yfin
import ta
import matplotlib.pyplot as plt
import requests

In [3]:
# notebook start time
import time
import datetime
import pytz

start_time = time.time()

# function to print date timestamp
def print_date_time():
  tz_NY = pytz.timezone('Asia/Kolkata')
  datetime_NY = datetime.datetime.now(tz_NY)
  print("Run date time (IST):", datetime_NY.strftime("%Y-%m-%d %H:%M:%S"))

In [4]:
# function to get booked and reserved amount
def get_amt():
  # fetch the JSON data from the URL
  url = "https://raw.githubusercontent.com/ankit-rathi/Tradevesting_v1/main/data/myPortfolioAmts.json"
  response = requests.get(url)
  pf_amts = response.json()  # parse the JSON data

  # extract values from the JSON
  py_booked_amt_dm = pf_amts["py_booked_amt_dm"]
  py_booked_amt_sv = pf_amts["py_booked_amt_sv"]
  cy_booked_amt_dm = pf_amts["cy_booked_amt_dm"]
  cy_booked_amt_sv = pf_amts["cy_booked_amt_sv"]
  reserve_amt_dm = pf_amts["reserve_amt_dm"]
  reserve_amt_sv = pf_amts["reserve_amt_sv"]

  # perform calculations
  py_booked_amt = py_booked_amt_dm + py_booked_amt_sv
  cy_booked_amt = cy_booked_amt_dm + cy_booked_amt_sv
  reserve_amt = reserve_amt_dm + reserve_amt_sv
  total_booked_amt = py_booked_amt + cy_booked_amt

  return total_booked_amt, reserve_amt, cy_booked_amt, py_booked_amt

gen_output = 0

In [5]:
# function to format the amount
def format_amt(number):
    abs_number = abs(number)

    if abs_number >= 1_00_00_000:  # Crores
        formatted_amt = f"{number / 1_00_00_000:.2f} C"
    elif abs_number >= 1_00_000:  # Lakhs
        formatted_amt = f"{number / 1_00_000:.2f} L"
    elif abs_number >= 1_000:  # Thousands
        formatted_amt = f"{number / 1_000:.2f} K"
    else:
        formatted_amt = f"{number:.2f}"

    return formatted_amt

# function to set start and end date
def get_start_end_date():
  start_date = (datetime.date.today() + datetime.timedelta(days=-365)).strftime('%Y-%m-%d')
  end_date = (datetime.date.today() + datetime.timedelta(days=1)).strftime('%Y-%m-%d')
  return start_date, end_date

# function to fetch my portfolio csv
def get_mypfs_df():
  mypfs_df = pd.read_csv('https://raw.githubusercontent.com/ankit-rathi/Tradevesting_v1/main/data/myPortfolioStocks.csv')
  return mypfs_df

# function to fetch my prospects csv
def get_mypps_df():
  mypps_df = pd.read_csv('https://raw.githubusercontent.com/ankit-rathi/Tradevesting_v1/main/data/myProspectsScrips.csv')
  return mypps_df

# function to fetch screener data
def get_myscreen_df():
  myscreen_df = pd.read_csv('https://raw.githubusercontent.com/ankit-rathi/Tradevesting_v1/main/data/myScreenerDB.csv')
  return myscreen_df

# function to fetch momentum data
def get_myinvmt_df():
  myinvmt_df = pd.read_csv('https://raw.githubusercontent.com/ankit-rathi/Tradevesting_v1/main/data/myInvestments.csv')
  return myinvmt_df

# function to get the stock ids
def get_stock_ids(df_pf):
  stock_n100 = df_pf['Symbol'].unique()

  exclude = ['CADILAHC','MMTC', 'MASFIN']

  stock_ids = df_pf[~df_pf['Symbol'].isin(exclude) ]['Symbol'].unique()

  #mypf = mypf[mypf.Forecast.notnull()]
  #stock_ids = mypf['Symbol'].unique()

  #stock_ids.sort()
  return stock_ids

# get features from screener data
def get_screener_features():
  myscreen_df = get_myscreen_df()
  cols = ['Symbol', 'EPS', 'MedPE', 'ROCE%', 'ROE%', 'CapType']
  return myscreen_df[cols]

# get relative strength
def get_relative_strength(stock_list):

    # Dictionary to store stock tickers and their corresponding percentage price change
    stock_changes = {}

    # Loop through each stock and fetch its price data
    for stock in stock_list:
        try:
            # Download the stock data for the given date range
            stock_data = yfin.Ticker(stock + '.NS').history(period='1mo', interval='1d')[map(str.title, ['open', 'close', 'low', 'high', 'volume'])]

            # Calculate the percentage change for the stock
            if len(stock_data) > 0:
                start_price = stock_data['Close'].iloc[0]
                end_price = stock_data['Close'].iloc[-1]
                percent_change = round(((end_price - start_price) / start_price) * 100, 2)
                stock_changes[stock] = percent_change
            else:
                stock_changes[stock] = np.nan  # If no data is available, set to NaN

        except Exception as e:
            print(f"Error fetching data for {stock}: {e}")
            stock_changes[stock] = np.nan

    # Create a DataFrame with stock tickers and their percentage changes
    df = pd.DataFrame(list(stock_changes.items()), columns=['Symbol', 'Percent_Change'])

    # Drop any stocks with missing data (NaN values)
    df = df.dropna()

    # Calculate the percentile rank based on percentage change
    df['RSP'] = round(df['Percent_Change'].rank(pct=True) * 100, 2)
    cols = ['Symbol', 'RSP']
    df = df[cols]
    # Sort by percentile rank (optional)
    df = df.sort_values(by='RSP', ascending=False).reset_index(drop=True)

    return df

In [6]:
# function to get stock technicals
def stock_prec_dev(stock_symbol):
    #stock_symbol = 'ULTRACEMCO.NS'
    short_window = 20
    mid_window = 50
    long_window = 200
    moving_avg = 'SMA'

    start = datetime.datetime(*map(int, start_date.split('-')))
    end = datetime.datetime(*map(int, end_date.split('-')))

    stock_df = yfin.Ticker(stock_symbol + '.NS').history(period='max', interval='1d')[map(str.title, ['open', 'close', 'low', 'high', 'volume'])]

    stock_df['Max'] = round(max(stock_df['Close']),2)
    stock_df = stock_df[(stock_df.index <= end_date) & (stock_df.index >= start_date)]
    stock_df['200_SMA'] = round(stock_df['Close'].rolling(window = 200, min_periods = 1).mean(),0)
    stock_df['Dev%_200'] = round((stock_df['Close'] - stock_df['200_SMA'])*100/stock_df['200_SMA'],2)
    stock_df.dropna(axis = 0, inplace = True) # remove any null rows

    stock_df['20_SMA'] = stock_df['Close'].rolling(window=20).mean()
    stock_df['50_SMA'] = stock_df['Close'].rolling(window=50).mean()
    stock_df['Symbol'] = stock_symbol

    stock_df['Close'] = round(stock_df['Close'],2)
    stock_df['Min'] = round(min(stock_df['Close']),2)
    stock_df['RSI_14'] = ta.momentum.RSIIndicator(close=stock_df['Close'], window=14).rsi()
    stock_df['RSI_14'] = round(stock_df['RSI_14'],0)
    stock_df['Prev_Close'] = stock_df['Close'].shift(1)
    stock_df.drop(['Open', 'Low', 'High', 'Volume'], axis=1, inplace=True)
    stock_df = stock_df.tail(1)

    max_SMA = max(stock_df['20_SMA'].item(), stock_df['50_SMA'].item(), stock_df['200_SMA'].item())
    min_SMA = min(stock_df['20_SMA'].item(), stock_df['50_SMA'].item(), stock_df['200_SMA'].item())
    ABS_Spread = max_SMA - min_SMA
    stock_df['Spread%'] = round((ABS_Spread / stock_df['200_SMA'].item()) * 100,2)

    return stock_df

# function to compute stock attributes
def get_common_features(stock_ids, df_mypf):

  df_prec_dev = pd.DataFrame()
  df_tmp = get_screener_features()
  df_rs = get_relative_strength(stock_ids)

  for stock_id in stock_ids:
      tmp = stock_prec_dev(stock_id)
      tmp = tmp.reset_index()
      df_prec_dev = pd.concat([df_prec_dev, tmp], ignore_index = True)
  df_prec_dev = pd.merge(df_prec_dev, df_mypf, on= 'Symbol')
  df_prec_dev = pd.merge(df_prec_dev, df_tmp, on= 'Symbol', how='left')
  df_prec_dev = pd.merge(df_prec_dev, df_rs, on= 'Symbol', how='left')
  #print(df_prec_dev.columns)
  df_prec_dev['Curr_PE'] = round(df_prec_dev['Close']/df_prec_dev['EPS'],1)
  df_prec_dev['Dev%_PE'] = round((df_prec_dev['Curr_PE'] - df_prec_dev['MedPE'])*100/df_prec_dev['MedPE'],2)
  df_prec_dev['Conviction'] = df_prec_dev['Conviction'] + '-' + df_prec_dev['CapType']
  return df_prec_dev

# function to arrange stock features
def arrange_features(df_stocks, common_cols, diff_cols):
  df_stocks_common = df_stocks[common_cols].drop_duplicates()
  df_stocks_diff = df_stocks[diff_cols]
  df_stocks_diff['Investment'] = df_stocks_diff['AvgCost'] * df_stocks_diff['Shares']
  df_stocks_diff = df_stocks_diff.groupby(['Symbol'])[['Shares', 'Investment']].aggregate(['sum']).reset_index()
  df_stocks_diff.columns = ['Symbol', 'Shares', 'Investment']
  df_stocks_diff['AvgCost'] = round(df_stocks_diff['Investment']/df_stocks_diff['Shares'],2)
  df_stocks = pd.merge(df_stocks_diff, df_stocks_common, on='Symbol')
  return df_stocks

# plot fact distribution across dimension
def plot_pie_chart(df, dimension, fact):
  # grouping the data by category and calculating the sum of fact for each type
  grouped_data = df.groupby(dimension)[fact].sum()

  # sorting the grouped data in descending order
  grouped_data = grouped_data.sort_values(ascending=False)

  # creating a pie chart
  grouped_data.plot.pie(autopct='%1.1f%%', startangle=90, figsize=(6, 6))

  # adding a title and displaying the plot
  plt.title(f'{dimension} {fact} Distribution')
  plt.ylabel('')  # To hide the y-label
  plt.show()

In [7]:
# function to get portfolio features

def get_portfolio_features(df_common_features):

  print_date_time()
  print('-------------------')

  #df_common_features["Target"] = df_common_features["Target"].fillna(df_common_features["Max"])
  df_common_features['NTT'] = np.where(df_common_features['Strategy']== 'NTT', df_common_features["Target"], df_common_features['Max'])
  df_common_features['LTT'] = np.where(df_common_features['Strategy']== 'BTT', df_common_features["Target"], df_common_features['Max'])
  df_common_features['BOL'] = df_common_features['Min']

  tmp_df = df_common_features[df_common_features['Symbol'].isin(mypf_df[mypf_df['InPortfolio'] != 'NA'].Symbol.values)]
  print('qualified stocks: '+str(len(tmp_df['Symbol'].unique())))
  tmp_df1 = tmp_df[tmp_df['LatestQtr'] == 1]
  print('with latest results: '+str(len(tmp_df1['Symbol'].unique())))
  tmp_df1 = tmp_df1[tmp_df1['StarStock'] == 1]
  print('still star stocks: '+str(len(tmp_df1['Symbol'].unique())))
  tmp_df['Investment'] = tmp_df['AvgCost'] * tmp_df['Shares']
  tmp_df['Current'] = round(tmp_df['Close'] * tmp_df['Shares'],0)
  tmp_df['Previous'] = tmp_df['Prev_Close'] * tmp_df['Shares']
  tmp_df['EstimatedST'] = tmp_df['NTT'] * tmp_df['Shares']
  tmp_df['EstimatedLT'] = tmp_df['LTT'] * tmp_df['Shares']
  tmp_df['Current P/L'] = round((tmp_df['Current'] - tmp_df['Investment']),0)
  tmp_df['Today P/L%'] = round((tmp_df['Current'] - tmp_df['Previous'])*100/tmp_df['Previous'],2)
  tmp_df['Current P/L%'] = round((tmp_df['Current'] - tmp_df['Investment'])*100/tmp_df['Investment'],2)
  tmp_df['EstimatedST P/L%'] = round((tmp_df['EstimatedST'] - tmp_df['Investment'])*100/tmp_df['Investment'],2)
  tmp_df['EstimatedLT P/L%'] = round((tmp_df['EstimatedLT'] - tmp_df['Investment'])*100/tmp_df['Investment'],2)
  tmp_df['NTT%'] = round((tmp_df['NTT'] - tmp_df['Close'])*100/tmp_df['Close'],2)
  tmp_df['LTT%'] = round((tmp_df['LTT'] - tmp_df['Close'])*100/tmp_df['Close'],2)
  tmp_df['Gained%'] = round((tmp_df['Close'] - tmp_df['BOL'])*100/tmp_df['BOL'],2)
  investment = round(sum(tmp_df['AvgCost']*tmp_df['Shares']),0)
  current = round(sum(tmp_df['Close']*tmp_df['Shares']),0)
  tmp_df['InitAlloc%'] = round(tmp_df['Investment']*100/investment,2)
  tmp_df['CurrAlloc%'] = round(tmp_df['Current']*100/current,2)
  tmp_df['FTT'] = tmp_df['LTT']
  tmp_df.loc[tmp_df['Strategy'] == 'NTT', 'FTT'] = tmp_df['NTT']
  tmp_df['FTT%'] = tmp_df['LTT%']
  tmp_df.loc[tmp_df['Strategy'] == 'NTT', 'FTT%'] = tmp_df['NTT%']
  tmp_df['FTT Amt'] = round(tmp_df['FTT%'] * tmp_df['Current']/100,0)
  tmp_df['OTT%'] = round((tmp_df['FTT'] - tmp_df['AvgCost'])*100/tmp_df['AvgCost'],2)
  tmp_df['RRR Ind'] = round(tmp_df['Current P/L']/tmp_df['FTT Amt'],2)
  tmp_df['Risk Ind'] = round(tmp_df['Current P/L%']*tmp_df['CurrAlloc%'],0)

  return tmp_df

# function to print portfolio features
def print_portfolio_stats(df_portfolio_features, myinvmt_df):
  from pyxirr import xirr

  total_booked_amt, reserve_amt, cy_booked_amt, py_booked_amt = get_amt()

  dates = myinvmt_df['Date'].values
  dates = np.append(dates, datetime.date.today().strftime('%d-%b-%y'))
  investment = myinvmt_df['Investment'].values
  dates= pd.to_datetime(dates)

  current = round(sum(df_portfolio_features['Close']*df_portfolio_features['Shares']),0) + reserve_amt
  investment_xirr = np.append(investment, current)
  cagr = round(xirr(pd.DataFrame({"dates": dates, "amounts": investment_xirr}))*100,2)

  investment = -sum(investment)
  invested = round(sum(df_portfolio_features['AvgCost']*df_portfolio_features['Shares']),0) + reserve_amt
  previous = round(sum(df_portfolio_features['Prev_Close']*df_portfolio_features['Shares']),0) + reserve_amt
  cy_invested = investment + py_booked_amt

  today_pnl_amount = current-previous
  today_pnl_percentage = round((current-previous)*100/previous,2)

  curr_pnl_amount = current-invested
  curr_pnl_percentage = round((curr_pnl_amount)*100/(cy_invested),2)

  cy_pnl_amount = cy_booked_amt + curr_pnl_amount
  cy_pnl_percentage = round((cy_pnl_amount)*100/cy_invested,2)

  overall_pnl_amount = total_booked_amt + curr_pnl_amount
  overall_pnl_percentage = round((overall_pnl_amount)*100/investment,2)

  estimate_st = round(sum(df_portfolio_features['FTT']*df_portfolio_features['Shares']),0)  + reserve_amt
  est_st_pnl_amount = estimate_st-current
  est_st_pnl_percentage = round((est_st_pnl_amount)*100/current,2)

  estimate_lt = round(sum(df_portfolio_features['LTT']*df_portfolio_features['Shares']),0)  + reserve_amt
  est_lt_pnl_amount = estimate_lt-current
  est_lt_pnl_percentage = round((est_lt_pnl_amount)*100/current,2)

  total_profit = round(sum(df_portfolio_features[df_portfolio_features['Current P/L%'] > 0]['Current']) - sum(df_portfolio_features[df_portfolio_features['Current P/L%'] > 0]['Investment']),0)
  total_loss = round(sum(df_portfolio_features[df_portfolio_features['Current P/L%'] < 0]['Current']) - sum(df_portfolio_features[df_portfolio_features['Current P/L%'] < 0]['Investment']),0)

  cy_booked_percentage = round((cy_booked_amt)*100/current,2)
  py_booked_percentage = round((py_booked_amt)*100/investment,2)
  total_booked_percentage = round((total_booked_amt)*100/investment,2)

  print('-------------------')
  print('Initial Investment: ', format_amt(investment))
  print('CY Investment: ', format_amt(cy_invested))
  print('Reserve: ', format_amt(reserve_amt))
  print('Current: ',  format_amt(current))
  print('-------------------')
  print('Today PnL: '+ '{} ({}%)'.format(format_amt(today_pnl_amount), today_pnl_percentage))
  print('Current PnL: '+ '{} ({}%)'.format(format_amt(curr_pnl_amount), curr_pnl_percentage))
  print('CY Booked + Current PnL: '+ '{} ({}%)'.format(format_amt(cy_pnl_amount), cy_pnl_percentage))
  print('-------------------')
  print('Total profit: ', format_amt(total_profit))
  print('Total loss: ', format_amt(total_loss))
  print('-------------------')
  print('Total Booked + Current PnL: '+ '{} ({}%)'.format(format_amt(overall_pnl_amount), overall_pnl_percentage))
  print('Total Booked PnL: '+ '{} ({}%)'.format(format_amt(total_booked_amt), total_booked_percentage))
  print('Curr Year Booked PnL: '+ '{} ({}%)'.format(format_amt(cy_booked_amt), cy_booked_percentage))
  print('Prev Year Booked PnL: '+ '{} ({}%)'.format(format_amt(py_booked_amt), py_booked_percentage))
  print('===================')
  print('Est FTT: ',  format_amt(estimate_st))
  print('Est FTT PnL: '+ '{} ({}%)'.format(format_amt(est_st_pnl_amount), est_st_pnl_percentage))

  print('===================')
  print('Deployed: ', format_amt(investment))

  print('Current: ', format_amt(current))

  print('CAGR/XIRR %: '+'{}%'.format(cagr))

In [8]:
# get start and end date
start_date, end_date = get_start_end_date()

# get portfolio and prospects data
mypfs_df = get_mypfs_df()
mypps_df = get_mypps_df()
myinvmt_df = get_myinvmt_df()

# merge above datasets
mypf_df = pd.merge(mypfs_df, mypps_df, on="Symbol")

# seggregate dm and sv portfolio
dm_pf = mypf_df[mypf_df['InPortfolio'] == 'DM']
sv_pf = mypf_df[mypf_df['InPortfolio'] == 'SV']

# build portfolio stock dataframe
dm_stocks = get_stock_ids(dm_pf)
sv_stocks = get_stock_ids(sv_pf)
df_stocks = pd.concat([dm_pf,sv_pf], ignore_index = True)

# arrange common and diff stock features
common_cols = ['Symbol', 'Target', 'Criteria', 'Strategy', 'CumlRnk', 'LatestQtr', 'StarStock', 'Conviction', 'Category', 'InFolio', 'XIRR', 'MBQ']
diff_cols = ['Symbol', 'AvgCost', 'Shares']
df_stocks = arrange_features(df_stocks, common_cols, diff_cols)

# get common features
stock_ids = df_stocks['Symbol'].values
df_common_features = get_common_features(stock_ids, df_stocks)

df_common_features.reset_index(drop=True, inplace=True)
df_common_features.drop(['Date'], axis=1, inplace=True)
# get and print portfolio features
df_portfolio_features = get_portfolio_features(df_common_features)

print_portfolio_stats(df_portfolio_features, myinvmt_df)

df = df_portfolio_features
#plot_pie_chart(df, 'CapType', 'Current')
list_ox40n = list(df[df['MBQ'].str.contains('OX40N', na=False)]['Symbol'].values)

Run date time (IST): 2026-03-27 16:02:25
-------------------
qualified stocks: 86
with latest results: 26
still star stocks: 16
-------------------
Initial Investment:  1.36 C
CY Investment:  1.62 C
Reserve:  1.61 K
Current:  1.28 C
-------------------
Today PnL: -3.45 L (-2.62%)
Current PnL: -49.16 L (-30.26%)
CY Booked + Current PnL: -33.27 L (-20.48%)
-------------------
Total profit:  41.27 K
Total loss:  -49.57 L
-------------------
Total Booked + Current PnL: -6.29 L (-4.64%)
Total Booked PnL: 42.87 L (31.64%)
Curr Year Booked PnL: 15.89 L (12.42%)
Prev Year Booked PnL: 26.98 L (19.91%)
===================
Est FTT:  2.48 C
Est FTT PnL: 1.20 C (93.72%)
===================
Deployed:  1.36 C
Current:  1.28 C
CAGR/XIRR %: -2.79%

In [9]:
# top 5 near their targets
cols = ['Symbol', 'Today P/L%', 'Current P/L%', 'FTT%', 'OTT%', 'FTT Amt', 'Current P/L', 'Current', 'FTT', 'Dev%_PE', 'RSI_14','Conviction', 'Spread%',  'CumlRnk', 'RRR Ind', 'CurrAlloc%', 'Gained%', 'Criteria', 'Strategy', 'Category']
df_tmp = df_portfolio_features[~df_portfolio_features['Symbol'].isin(['ENRIN','BLUSPRING','DIGITIDE'])]
df_tmp = df_tmp.sort_values(by = 'FTT Amt', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
50,MASFIN,-3.16,-10.53,35.88,21.57,31452.0,-10320.0,87660.0,397.04,-22.76,40.0,H-SC,3.51,167.0,-0.33,0.69,19.56,XR,ATH,FINANCE
77,TTKPRESTIG,-0.04,-42.80,74.98,0.09,43224.0,-43130.0,57647.0,770.00,33.83,35.0,M-SC,20.61,250.0,-1.00,0.45,0.34,OX40N,NTT,DURABLES
37,ICICIGI,-1.32,-7.46,28.96,19.34,53629.0,-14927.0,185182.0,2252.93,-22.04,34.0,X-MC,4.48,66.0,-0.28,1.45,2.37,X40,ATH,INSURANCE
2,ABBOTINDIA,-1.02,-12.33,34.67,18.07,54366.0,-22045.0,156810.0,35195.00,-25.47,44.0,X-MC,10.49,58.0,-0.41,1.23,2.55,X40,ATH,PHARMA
67,SONACOMS,-4.44,-15.45,64.51,39.09,55176.0,-15628.0,85531.0,804.02,-33.03,44.0,M-MC,6.71,193.0,-0.28,0.67,21.00,AR,ATH,AUTO

In [10]:
# top 5 today
df_tmp = df_portfolio_features.sort_values(by = 'Today P/L%', ascending=False)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
8,AWL,1.39,-36.15,161.60,67.02,367617.0,-128823.0,227486.0,485.00,-65.68,49.0,X-SC,26.04,81.0,-0.35,1.78,7.60,XY24,NTT,FMCG
84,WIPRO,1.35,-21.41,119.21,72.27,158742.0,-36286.0,133162.0,420.00,-29.24,36.0,M-LC,17.94,98.0,-0.23,1.04,2.16,XR,NTT,IT
66,SIS,0.96,-33.71,82.92,21.26,61034.0,-37426.0,73606.0,528.00,1723.83,48.0,H-SC,14.39,168.0,-0.61,0.58,9.44,OX40N,NTT,MISC
73,TCS,0.52,-29.84,80.42,26.57,261375.0,-138260.0,325013.0,4311.59,-40.68,31.0,X-LC,17.85,2.0,-0.53,2.54,1.43,X40,ATH,IT
83,WHIRLPOOL,0.20,-35.18,180.65,81.92,134429.0,-40384.0,74414.0,2270.00,-62.04,41.0,M-SC,25.04,210.0,-0.30,0.58,4.53,XR,NTT,DURABLES

In [11]:
# bottom 5 today
df_tmp = df_portfolio_features.sort_values(by = 'Today P/L%', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
80,VALIANTORG,-9.28,-55.44,290.79,74.15,212015.0,-90695.0,72910.0,838.0,-231.00,43.0,H-SC,28.19,145.0,-0.43,0.57,8.5,XR,NTT,CHEMICALS
14,BOSCH-HCIL,-8.90,-51.85,107.68,-0.01,66259.0,-66272.0,61533.0,2282.0,12486.96,22.0,M-SC,6.00,231.0,-1.00,0.48,0.0,OX40N,BTT,AC
25,EASEMYTRIP,-7.19,-65.78,325.81,45.70,197115.0,-116315.0,60500.0,26.4,-37.27,32.0,M-SC,9.54,204.0,-0.59,0.47,0.0,XY24,NTT,TRAVEL
56,RAJOOENG,-6.62,-50.43,181.64,39.61,92291.0,-51690.0,50810.0,143.1,-66.40,33.0,H-SC,32.94,136.0,-0.56,0.40,0.0,AR,ATH,MISC
22,DEN,-6.49,-54.40,211.59,42.07,81488.0,-45952.0,38512.0,75.0,37.31,26.0,M-SC,19.71,235.0,-0.56,0.30,0.0,AR,NTT,ENTERTAINMENT

In [12]:
# top 5 to exit based on CumlRnk
df_tmp = df_portfolio_features[~df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])]
df_tmp = df_tmp[(df_tmp['Current P/L%'] > -1) & (df_tmp['Current P/L%'] < 1)].sort_values(by = 'CumlRnk', ascending=False)
df_tmp[cols].head()

Empty DataFrame
Columns: [Symbol, Today P/L%, Current P/L%, FTT%, OTT%, FTT Amt, Current P/L, Current, FTT, Dev%_PE, RSI_14, Conviction, Spread%, CumlRnk, RRR Ind, CurrAlloc%, Gained%, Criteria, Strategy, Category]
Index: []

In [13]:
# OX40N stocks to exit
df_tmp = df_portfolio_features[(df_portfolio_features['Symbol'].isin(list_ox40n))].sort_values(by = 'Current P/L%', ascending=False)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
26,FINCABLES,-3.06,2.17,103.50,107.91,156124.0,3200.0,150844.0,1641.55,-8.17,44.0,M-SC,7.90,220.0,0.02,1.18,13.48,OX40N,ATH,CABLES
66,SIS,0.96,-33.71,82.92,21.26,61034.0,-37426.0,73606.0,528.00,1723.83,48.0,H-SC,14.39,168.0,-0.61,0.58,9.44,OX40N,NTT,MISC
18,CERA,-1.86,-39.32,104.18,23.89,111193.0,-69171.0,106732.0,9475.00,-41.53,43.0,H-SC,19.17,153.0,-0.62,0.83,2.57,OX40N,NTT,CERAMICS
72,TATAELXSI,-1.25,-40.03,120.17,32.03,95000.0,-52780.0,79055.0,9161.00,-25.07,37.0,H-SC,21.26,158.0,-0.56,0.62,3.01,OX40N,NTT,IT
77,TTKPRESTIG,-0.04,-42.80,74.98,0.09,43224.0,-43130.0,57647.0,770.00,33.83,35.0,M-SC,20.61,250.0,-1.00,0.45,0.34,OX40N,NTT,DURABLES

In [14]:
# top 5 to book for rotation
df_tmp = df_portfolio_features[(df_portfolio_features['Current P/L%'] > 20) ].sort_values(by = 'CumlRnk', ascending=False)
df_tmp[cols].head()

Empty DataFrame
Columns: [Symbol, Today P/L%, Current P/L%, FTT%, OTT%, FTT Amt, Current P/L, Current, FTT, Dev%_PE, RSI_14, Conviction, Spread%, CumlRnk, RRR Ind, CurrAlloc%, Gained%, Criteria, Strategy, Category]
Index: []

In [15]:
# top 5 to monitor for exit
df_tmp = df_portfolio_features[~df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])]
df_tmp = df_tmp[(df_tmp['Current P/L%'] > 0) ].sort_values(by = 'Dev%_PE', ascending=False)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
26,FINCABLES,-3.06,2.17,103.50,107.91,156124.0,3200.0,150844.0,1641.55,-8.17,44.0,M-SC,7.90,220.0,0.02,1.18,13.48,OX40N,ATH,CABLES
1,ABB,-1.73,12.01,29.96,45.57,87795.0,31421.0,293040.0,7934.00,-28.06,52.0,H-MC,13.36,125.0,0.36,2.29,30.13,AR,NTT,ELECTRICAL

In [16]:
# top 5 to book for rotation from weak conviction
df_tmp = df_portfolio_features[~df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])]
df_tmp = df_tmp[~df_tmp['Criteria'].isin(['XY25','XY24','X40', 'X40N'])].sort_values(by = 'RRR Ind', ascending=False)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
1,ABB,-1.73,12.01,29.96,45.57,87795.0,31421.0,293040.0,7934.00,-28.06,52.0,H-MC,13.36,125.0,0.36,2.29,30.13,AR,NTT,ELECTRICAL
26,FINCABLES,-3.06,2.17,103.50,107.91,156124.0,3200.0,150844.0,1641.55,-8.17,44.0,M-SC,7.90,220.0,0.02,1.18,13.48,OX40N,ATH,CABLES
40,INDIAMART,-2.23,-15.31,144.11,106.72,150519.0,-18889.0,104447.0,4810.62,-61.72,35.0,H-SC,12.39,140.0,-0.13,0.82,4.48,AR,ATH,MISC
85,ZYDUSLIFE,-0.77,-5.44,43.43,35.63,86066.0,-11403.0,198171.0,1286.17,-17.57,49.0,H-MC,5.30,120.0,-0.13,1.55,10.32,AR,ATH,PHARMA
84,WIPRO,1.35,-21.41,119.21,72.27,158742.0,-36286.0,133162.0,420.00,-29.24,36.0,M-LC,17.94,98.0,-0.23,1.04,2.16,XR,NTT,IT

In [17]:
# top 5 to accumulate based on lowest RSI_14
df_tmp = df_portfolio_features[df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])].sort_values(by = 'RSI_14', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
53,PGHH,-5.34,-31.52,92.79,32.01,135666.0,-67312.0,146208.0,17616.87,-53.70,16.0,X-MC,17.23,57.0,-0.50,1.14,0.0,X40,ATH,FMCG
9,BAJAJHFL,-4.15,-32.25,139.29,62.13,257684.0,-88048.0,184998.0,181.50,-44.34,22.0,X-MC,20.62,60.0,-0.34,1.45,0.0,X40N,ATH,FINANCE
38,ICICIPRULI,-1.89,-12.23,48.94,30.73,84622.0,-24095.0,172910.0,790.00,-35.82,22.0,X-MC,5.57,78.0,-0.28,1.35,0.0,X40,ATH,INSURANCE
58,RELAXO,-6.02,-67.65,370.87,52.31,174135.0,-98207.0,46953.0,1176.00,-65.54,22.0,X-SC,28.52,92.0,-0.56,0.37,0.0,X40N,NTT,FOOTWEAR
27,GILLETTE,-2.75,-11.72,46.95,29.72,105229.0,-29766.0,224130.0,10978.86,-32.23,27.0,X-SC,11.83,83.0,-0.28,1.75,0.0,X40,ATH,FMCG

In [18]:
# top 5 to accumulate based on Spread and CumlRnk
df_tmp = df_portfolio_features[df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])]
df_tmp = df_tmp[(df_tmp['CumlRnk'] < 100)].sort_values(by = 'Spread%', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
65,SIEMENS,-1.69,-18.08,53.22,25.51,81131.0,-33650.0,152445.0,4671.50,27.94,43.0,H-LC,1.81,51.0,-0.41,1.19,12.26,AR,ATH,ELECTRICAL
78,UNITDSPR,-4.41,-7.90,31.12,20.77,67112.0,-18490.0,215654.0,1644.00,-18.34,38.0,X-MC,2.38,64.0,-0.28,1.69,0.00,X40N,NTT,BREWERIES
82,VOLTAS,-3.38,3.47,40.33,45.20,80011.0,6648.0,198390.0,1856.00,18.43,40.0,X-MC,3.36,79.0,0.08,1.55,10.50,XY25,NTT,AC
59,RELIANCE,-4.60,-13.46,44.80,25.30,77909.0,-27058.0,173905.0,1952.00,-15.80,38.0,X-LC,3.68,21.0,-0.35,1.36,16.11,XY25,BTT,REFINERIES
37,ICICIGI,-1.32,-7.46,28.96,19.34,53629.0,-14927.0,185182.0,2252.93,-22.04,34.0,X-MC,4.48,66.0,-0.28,1.45,2.37,X40,ATH,INSURANCE

In [19]:
# top 5 to accumulate based on lowest Gained%
df_tmp = df_portfolio_features[df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])].sort_values(by = 'Gained%', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
3,ACC,-3.91,-41.17,197.17,74.81,310992.0,-110400.0,157728.0,3906.00,-58.35,28.0,X-SC,19.11,85.0,-0.35,1.23,0.0,XY24,BTT,CEMENT
9,BAJAJHFL,-4.15,-32.25,139.29,62.13,257684.0,-88048.0,184998.0,181.50,-44.34,22.0,X-MC,20.62,60.0,-0.34,1.45,0.0,X40N,ATH,FINANCE
10,BAJAJHLDNG,-4.23,-18.19,57.94,29.22,90126.0,-34575.0,155550.0,14451.52,-24.33,31.0,X-LC,17.87,28.0,-0.38,1.22,0.0,X40,ATH,FINANCE
27,GILLETTE,-2.75,-11.72,46.95,29.72,105229.0,-29766.0,224130.0,10978.86,-32.23,27.0,X-SC,11.83,83.0,-0.28,1.75,0.0,X40,ATH,FMCG
28,GLAXO,-2.67,-9.30,53.41,39.15,96544.0,-18524.0,180760.0,3466.20,-30.71,31.0,X-MC,10.00,56.0,-0.19,1.41,0.0,X40,ATH,PHARMA

In [20]:
# top 5 to accumulate based on lowest CurrAlloc%
df_tmp = df_portfolio_features[df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])].sort_values(by = 'CurrAlloc%', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
58,RELAXO,-6.02,-67.65,370.87,52.31,174135.0,-98207.0,46953.0,1176.00,-65.54,22.0,X-SC,28.52,92.0,-0.56,0.37,0.00,X40N,NTT,FOOTWEAR
12,BATAINDIA,-4.23,-59.22,231.57,35.20,121500.0,-76202.0,52468.0,2096.00,-31.26,27.0,X-SC,32.35,91.0,-0.63,0.41,1.02,X40,NTT,FOOTWEAR
54,QUESS,-1.48,-28.62,143.64,73.90,109490.0,-30568.0,76225.0,424.00,-61.43,37.0,X-SC,21.77,80.0,-0.28,0.60,2.45,XY24,NTT,MISC
36,HONAUT,-4.17,-29.92,115.90,51.31,156639.0,-57688.0,135150.0,58357.33,-41.73,28.0,X-SC,16.68,90.0,-0.37,1.06,0.00,X40N,ATH,ELECTRICAL
53,PGHH,-5.34,-31.52,92.79,32.01,135666.0,-67312.0,146208.0,17616.87,-53.70,16.0,X-MC,17.23,57.0,-0.50,1.14,0.00,X40,ATH,FMCG

In [21]:
# top 5 to accumulate based on CumlRnk
df_tmp = df_portfolio_features.sort_values(by = 'CumlRnk', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
45,ITC,-0.34,-22.38,53.38,19.06,140950.0,-76115.0,264051.0,452.00,-57.54,36.0,X-LC,18.93,1.0,-0.54,2.06,1.46,X40,NTT,FMCG
73,TCS,0.52,-29.84,80.42,26.57,261375.0,-138260.0,325013.0,4311.59,-40.68,31.0,X-LC,17.85,2.0,-0.53,2.54,1.43,X40,ATH,IT
43,INFY,-0.73,-13.56,55.31,34.24,149584.0,-42442.0,270446.0,1972.00,-32.15,40.0,X-LC,15.08,3.0,-0.28,2.11,4.01,X40,NTT,IT
75,TMPV,-4.64,-30.98,97.89,36.58,240410.0,-110249.0,245592.0,600.00,-85.81,34.0,X-LC,8.35,4.0,-0.46,1.92,0.00,XY24,NTT,AUTO
33,HCLTECH,-1.22,-11.46,39.86,23.83,85385.0,-27713.0,214211.0,1908.19,-6.95,44.0,X-LC,11.64,8.0,-0.32,1.67,4.01,X40,ATH,IT

In [22]:
# top 5 for average up
df_tmp = df_portfolio_features[(df_portfolio_features['Dev%_200'] > 5)].sort_values(by = 'CurrAlloc%', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
1,ABB,-1.73,12.01,29.96,45.57,87795.0,31421.0,293040.0,7934.0,-28.06,52.0,H-MC,13.36,125.0,0.36,2.29,30.13,AR,NTT,ELECTRICAL

In [23]:
# top 5 RSP
df_tmp = df_portfolio_features.sort_values(by = 'RSP', ascending=False)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
30,HAPPSTMNDS,-2.30,-51.44,280.69,84.85,174679.0,-65933.0,62232.0,1480.71,-42.35,51.0,H-SC,25.56,152.0,-0.38,0.49,15.24,AR,ATH,IT
5,ANGELONE,-1.94,-3.58,28.79,24.18,84668.0,-10912.0,294088.0,303.00,-85.87,52.0,X-SC,10.12,97.0,-0.13,2.30,13.20,X40N,NTT,FINANCE
24,DMART,-0.19,-6.17,38.13,29.60,89297.0,-15408.0,234192.0,5391.45,-20.85,54.0,X-LC,6.87,14.0,-0.17,1.83,7.05,X40N,ATH,FMCG
1,ABB,-1.73,12.01,29.96,45.57,87795.0,31421.0,293040.0,7934.00,-28.06,52.0,H-MC,13.36,125.0,0.36,2.29,30.13,AR,NTT,ELECTRICAL
52,PAGEIND,-2.54,-17.04,61.67,34.11,137299.0,-45744.0,222635.0,51418.65,-40.46,48.0,X-MC,21.06,55.0,-0.33,1.74,5.31,X40,ATH,APPARELS

In [24]:
# Top N allocation
df_tmp = df_portfolio_features.sort_values(by = 'CurrAlloc%', ascending=False)
top_n_values = [10, 25, 50]

sum_df = pd.DataFrame({
    'Top_N': top_n_values,
    'Sum_Alloc%': [df_tmp['CurrAlloc%'].head(n).sum() for n in top_n_values]
})

sum_df

   Top_N  Sum_Alloc%
0     10       20.96
1     25       46.27
2     50       78.51

In [25]:
# market-cap-wise allocation
df_tmp = df_portfolio_features[cols]
df_tmp.groupby(df_tmp['Conviction'].str[-2:])['CurrAlloc%'].sum().sort_values(ascending=False)

Conviction
SC    44.19
MC    30.12
LC    25.72
Name: CurrAlloc%, dtype: float64

In [26]:
# criteria-wise allocation
df_portfolio_features.groupby('Criteria')['CurrAlloc%'].sum().sort_values(ascending=False)

Criteria
XY24     27.08
X40      25.52
X40N     15.24
AR        9.19
XR        8.24
XY25      7.37
OX40N     6.61
SR        0.78
Name: CurrAlloc%, dtype: float64

In [27]:
# conviction-wise allocation
df_portfolio_features.groupby('Conviction')['CurrAlloc%'].sum().sort_values(ascending=False)

Conviction
X-LC    23.49
X-MC    22.59
H-SC    21.59
X-SC    12.30
M-SC     9.78
H-MC     5.14
M-MC     2.04
H-LC     1.19
M-LC     1.04
L-SC     0.52
L-MC     0.35
Name: CurrAlloc%, dtype: float64

In [28]:
# sector-wise stats
df_tmp = df_portfolio_features.groupby('Category')[['CurrAlloc%', 'Current', 'Current P/L', 'FTT Amt']].sum().sort_values(by=['Current', 'Current P/L'], ascending=False)
df_tmp['Current P/L%'] = round(df_tmp['Current P/L'] * 100 / df_tmp['Current'], 2)
df_tmp['FTT%'] = round(df_tmp['FTT Amt'] * 100 / df_tmp['Current'], 2)
cols = ['CurrAlloc%', 'Current P/L%', 'FTT%']
df_tmp[cols].sort_values(by=['CurrAlloc%'], ascending=False)

               CurrAlloc%  Current P/L%    FTT%
Category
FMCG                15.18        -28.55   74.19
FINANCE             13.18        -27.65   79.68
IT                  11.93        -47.56  122.66
MISC                 6.95        -51.09  116.73
ELECTRICAL           6.56        -15.40   59.59
PAINTS               5.21        -47.92   73.61
INSURANCE            4.75        -11.74   49.97
BANKS                4.59        -30.97   97.45
PHARMA               4.19         -9.70   44.23
AUTO                 3.65        -39.96   95.49
AC                   2.03        -22.94   56.27
HEALTHCARE           1.87        -49.28   88.24
FOOTWEAR             1.78        -94.77  172.86
TRAVEL               1.77        -97.10  195.79
DURABLES             1.76        -71.43  113.14
APPARELS             1.74        -20.55   61.67
BREWERIES            1.69         -8.57   31.12
REALTY               1.47        -17.52   36.83
REFINERIES           1.36        -15.56   44.80
CERAMICS             1.36        -75.41  128.69
CEMENT               1.23        -69.99  197.17
CABLES               1.18          2.12  103.50
ENGINEERING          1.06        -78.34  159.91
CHEMICALS            1.00       -105.91  273.90
JEWELLERY            1.00       -152.25  239.89
ENTERTAINMENT        0.74       -104.84  227.00
TEXTILES             0.46        -57.06  101.85
HOTELS               0.34       -162.84  255.56

In [29]:
# money to be made criteria-wise
df_portfolio_features.groupby('Criteria')['FTT Amt'].agg(['sum', 'count']).sort_values(by='sum', ascending=False)

                sum  count
Criteria
XY24      4134394.0     21
X40       1907639.0     16
XR        1438364.0     12
AR        1396113.0     10
X40N      1351654.0     10
OX40N      947025.0     10
XY25       497788.0      5
SR         319175.0      2

In [30]:
# money to be made conviction-wise
df_portfolio_features.groupby('Conviction')['FTT Amt'].agg(['sum', 'count']).sort_values(by='sum', ascending=False)

                  sum  count
Conviction
H-SC        4033935.0     24
X-MC        1844304.0     15
X-LC        1769667.0     13
M-SC        1666268.0     14
X-SC        1609006.0     10
H-MC         421098.0      3
L-SC         225252.0      2
M-LC         158742.0      1
M-MC         125323.0      2
H-LC          81131.0      1
L-MC          57426.0      1

In [31]:
# money to be made criteria and conviction-wise
df_portfolio_features.groupby(['Conviction', 'Criteria'])['FTT Amt'].agg(['sum', 'count']).sort_values(by='sum', ascending=False)

                           sum  count
Conviction Criteria
H-SC       XY24      1387737.0      6
           AR        1004457.0      5
M-SC       XY24       963377.0      6
X-LC       X40        944231.0      7
H-SC       XR         917541.0      7
X-SC       XY24       863709.0      4
X-MC       X40        736679.0      7
           X40N       563644.0      4
X-SC       X40N       518568.0      4
M-SC       OX40N      427150.0      5
H-SC       OX40N      405025.0      4
X-LC       XY24       393325.0      2
H-SC       SR         319175.0      2
X-MC       XY24       279009.0      2
X-LC       X40N       269442.0      2
X-MC       XY25       264972.0      2
H-MC       XY24       247237.0      1
X-SC       X40        226729.0      2
M-SC       XR         194253.0      2
H-MC       AR         173861.0      2
X-LC       XY25       162669.0      2
M-LC       XR         158742.0      1
L-SC       OX40N      114850.0      1
           XR         110402.0      1
M-SC       AR          81488.0      1
H-LC       AR          81131.0      1
M-MC       XY25        70147.0      1
L-MC       XR          57426.0      1
M-MC       AR          55176.0      1

In [32]:
# notebook execution time

end_time = time.time()
execution_time = round(end_time - start_time, 0)
print(f"Notebook execution time: {execution_time} seconds")

Notebook execution time: 26.0 seconds