<a href="https://colab.research.google.com/github/ankit-rathi/Quantvesting_v2/blob/main/myStocks_Portfolio_Analysis.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
'''
!pip install pandas==2.2.2 -qq
!pip install pyxirr -qq
!pip install ta -qq
!pip install yfinance==0.2.59 -qq
'''

'\n!pip install pandas==2.2.2 -qq\n!pip install pyxirr -qq\n!pip install ta -qq\n!pip install yfinance==0.2.59 -qq\n'

In [2]:
# import libraries

import numpy as np
import pandas as pd
import datetime
import warnings
warnings.filterwarnings('ignore')
import yfinance as yfin
import ta
import matplotlib.pyplot as plt
import requests

In [3]:
# notebook start time
import time
import datetime
import pytz

start_time = time.time()

# function to print date timestamp
def print_date_time():
  tz_NY = pytz.timezone('Asia/Kolkata')
  datetime_NY = datetime.datetime.now(tz_NY)
  print("Run date time (IST):", datetime_NY.strftime("%Y-%m-%d %H:%M:%S"))

In [4]:
# function to get booked and reserved amount
def get_amt():
  # fetch the JSON data from the URL
  url = "https://raw.githubusercontent.com/ankit-rathi/Tradevesting_v1/main/data/myPortfolioAmts.json"
  response = requests.get(url)
  pf_amts = response.json()  # parse the JSON data

  # extract values from the JSON
  py_booked_amt_dm = pf_amts["py_booked_amt_dm"]
  py_booked_amt_sv = pf_amts["py_booked_amt_sv"]
  cy_booked_amt_dm = pf_amts["cy_booked_amt_dm"]
  cy_booked_amt_sv = pf_amts["cy_booked_amt_sv"]
  reserve_amt_dm = pf_amts["reserve_amt_dm"]
  reserve_amt_sv = pf_amts["reserve_amt_sv"]

  # perform calculations
  py_booked_amt = py_booked_amt_dm + py_booked_amt_sv
  cy_booked_amt = cy_booked_amt_dm + cy_booked_amt_sv
  reserve_amt = reserve_amt_dm + reserve_amt_sv
  total_booked_amt = py_booked_amt + cy_booked_amt

  return total_booked_amt, reserve_amt, cy_booked_amt, py_booked_amt

gen_output = 0

In [5]:
# function to format the amount
def format_amt(number):
    abs_number = abs(number)

    if abs_number >= 1_00_00_000:  # Crores
        formatted_amt = f"{number / 1_00_00_000:.2f} C"
    elif abs_number >= 1_00_000:  # Lakhs
        formatted_amt = f"{number / 1_00_000:.2f} L"
    elif abs_number >= 1_000:  # Thousands
        formatted_amt = f"{number / 1_000:.2f} K"
    else:
        formatted_amt = f"{number:.2f}"

    return formatted_amt

# function to set start and end date
def get_start_end_date():
  start_date = (datetime.date.today() + datetime.timedelta(days=-365)).strftime('%Y-%m-%d')
  end_date = (datetime.date.today() + datetime.timedelta(days=1)).strftime('%Y-%m-%d')
  return start_date, end_date

# function to fetch my portfolio csv
def get_mypfs_df():
  mypfs_df = pd.read_csv('https://raw.githubusercontent.com/ankit-rathi/Tradevesting_v1/main/data/myPortfolioStocks.csv')
  return mypfs_df

# function to fetch my prospects csv
def get_mypps_df():
  mypps_df = pd.read_csv('https://raw.githubusercontent.com/ankit-rathi/Tradevesting_v1/main/data/myProspectsScrips.csv')
  return mypps_df

# function to fetch screener data
def get_myscreen_df():
  myscreen_df = pd.read_csv('https://raw.githubusercontent.com/ankit-rathi/Tradevesting_v1/main/data/myScreenerDB.csv')
  return myscreen_df

# function to fetch momentum data
def get_myinvmt_df():
  myinvmt_df = pd.read_csv('https://raw.githubusercontent.com/ankit-rathi/Tradevesting_v1/main/data/myInvestments.csv')
  return myinvmt_df

# function to get the stock ids
def get_stock_ids(df_pf):
  stock_n100 = df_pf['Symbol'].unique()

  exclude = ['CADILAHC','MMTC', 'MASFIN']

  stock_ids = df_pf[~df_pf['Symbol'].isin(exclude) ]['Symbol'].unique()

  #mypf = mypf[mypf.Forecast.notnull()]
  #stock_ids = mypf['Symbol'].unique()

  #stock_ids.sort()
  return stock_ids

# get features from screener data
def get_screener_features():
  myscreen_df = get_myscreen_df()
  cols = ['Symbol', 'EPS', 'MedPE', 'ROCE%', 'ROE%', 'CapType']
  return myscreen_df[cols]

# get relative strength
def get_relative_strength(stock_list):

    # Dictionary to store stock tickers and their corresponding percentage price change
    stock_changes = {}

    # Loop through each stock and fetch its price data
    for stock in stock_list:
        try:
            # Download the stock data for the given date range
            stock_data = yfin.Ticker(stock + '.NS').history(period='1mo', interval='1d')[map(str.title, ['open', 'close', 'low', 'high', 'volume'])]

            # Calculate the percentage change for the stock
            if len(stock_data) > 0:
                start_price = stock_data['Close'].iloc[0]
                end_price = stock_data['Close'].iloc[-1]
                percent_change = round(((end_price - start_price) / start_price) * 100, 2)
                stock_changes[stock] = percent_change
            else:
                stock_changes[stock] = np.nan  # If no data is available, set to NaN

        except Exception as e:
            print(f"Error fetching data for {stock}: {e}")
            stock_changes[stock] = np.nan

    # Create a DataFrame with stock tickers and their percentage changes
    df = pd.DataFrame(list(stock_changes.items()), columns=['Symbol', 'Percent_Change'])

    # Drop any stocks with missing data (NaN values)
    df = df.dropna()

    # Calculate the percentile rank based on percentage change
    df['RSP'] = round(df['Percent_Change'].rank(pct=True) * 100, 2)
    cols = ['Symbol', 'RSP']
    df = df[cols]
    # Sort by percentile rank (optional)
    df = df.sort_values(by='RSP', ascending=False).reset_index(drop=True)

    return df

In [6]:
# function to get stock technicals
def stock_prec_dev(stock_symbol):
    #stock_symbol = 'ULTRACEMCO.NS'
    short_window = 20
    mid_window = 50
    long_window = 200
    moving_avg = 'SMA'

    start = datetime.datetime(*map(int, start_date.split('-')))
    end = datetime.datetime(*map(int, end_date.split('-')))

    stock_df = yfin.Ticker(stock_symbol + '.NS').history(period='max', interval='1d')[map(str.title, ['open', 'close', 'low', 'high', 'volume'])]

    stock_df['Max'] = round(max(stock_df['Close']),2)
    stock_df = stock_df[(stock_df.index <= end_date) & (stock_df.index >= start_date)]
    stock_df['200_SMA'] = round(stock_df['Close'].rolling(window = 200, min_periods = 1).mean(),0)
    stock_df['Dev%_200'] = round((stock_df['Close'] - stock_df['200_SMA'])*100/stock_df['200_SMA'],2)
    stock_df.dropna(axis = 0, inplace = True) # remove any null rows

    stock_df['20_SMA'] = stock_df['Close'].rolling(window=20).mean()
    stock_df['50_SMA'] = stock_df['Close'].rolling(window=50).mean()
    stock_df['Symbol'] = stock_symbol

    stock_df['Close'] = round(stock_df['Close'],2)
    stock_df['Min'] = round(min(stock_df['Close']),2)
    stock_df['RSI_14'] = ta.momentum.RSIIndicator(close=stock_df['Close'], window=14).rsi()
    stock_df['RSI_14'] = round(stock_df['RSI_14'],0)
    stock_df['Prev_Close'] = stock_df['Close'].shift(1)
    stock_df.drop(['Open', 'Low', 'High', 'Volume'], axis=1, inplace=True)
    stock_df = stock_df.tail(1)

    max_SMA = max(stock_df['20_SMA'].item(), stock_df['50_SMA'].item(), stock_df['200_SMA'].item())
    min_SMA = min(stock_df['20_SMA'].item(), stock_df['50_SMA'].item(), stock_df['200_SMA'].item())
    ABS_Spread = max_SMA - min_SMA
    stock_df['Spread%'] = round((ABS_Spread / stock_df['200_SMA'].item()) * 100,2)

    return stock_df

# function to compute stock attributes
def get_common_features(stock_ids, df_mypf):

  df_prec_dev = pd.DataFrame()
  df_tmp = get_screener_features()
  df_rs = get_relative_strength(stock_ids)

  for stock_id in stock_ids:
      tmp = stock_prec_dev(stock_id)
      tmp = tmp.reset_index()
      df_prec_dev = pd.concat([df_prec_dev, tmp], ignore_index = True)
  df_prec_dev = pd.merge(df_prec_dev, df_mypf, on= 'Symbol')
  df_prec_dev = pd.merge(df_prec_dev, df_tmp, on= 'Symbol', how='left')
  df_prec_dev = pd.merge(df_prec_dev, df_rs, on= 'Symbol', how='left')
  #print(df_prec_dev.columns)
  df_prec_dev['Curr_PE'] = round(df_prec_dev['Close']/df_prec_dev['EPS'],1)
  df_prec_dev['Dev%_PE'] = round((df_prec_dev['Curr_PE'] - df_prec_dev['MedPE'])*100/df_prec_dev['MedPE'],2)
  df_prec_dev['Conviction'] = df_prec_dev['Conviction'] + '-' + df_prec_dev['CapType']
  return df_prec_dev

# function to arrange stock features
def arrange_features(df_stocks, common_cols, diff_cols):
  df_stocks_common = df_stocks[common_cols].drop_duplicates()
  df_stocks_diff = df_stocks[diff_cols]
  df_stocks_diff['Investment'] = df_stocks_diff['AvgCost'] * df_stocks_diff['Shares']
  df_stocks_diff = df_stocks_diff.groupby(['Symbol'])[['Shares', 'Investment']].aggregate(['sum']).reset_index()
  df_stocks_diff.columns = ['Symbol', 'Shares', 'Investment']
  df_stocks_diff['AvgCost'] = round(df_stocks_diff['Investment']/df_stocks_diff['Shares'],2)
  df_stocks = pd.merge(df_stocks_diff, df_stocks_common, on='Symbol')
  return df_stocks

# plot fact distribution across dimension
def plot_pie_chart(df, dimension, fact):
  # grouping the data by category and calculating the sum of fact for each type
  grouped_data = df.groupby(dimension)[fact].sum()

  # sorting the grouped data in descending order
  grouped_data = grouped_data.sort_values(ascending=False)

  # creating a pie chart
  grouped_data.plot.pie(autopct='%1.1f%%', startangle=90, figsize=(6, 6))

  # adding a title and displaying the plot
  plt.title(f'{dimension} {fact} Distribution')
  plt.ylabel('')  # To hide the y-label
  plt.show()

In [7]:
# function to get portfolio features

def get_portfolio_features(df_common_features):

  print_date_time()
  print('-------------------')

  #df_common_features["Target"] = df_common_features["Target"].fillna(df_common_features["Max"])
  df_common_features['NTT'] = np.where(df_common_features['Strategy']== 'NTT', df_common_features["Target"], df_common_features['Max'])
  df_common_features['LTT'] = np.where(df_common_features['Strategy']== 'BTT', df_common_features["Target"], df_common_features['Max'])
  df_common_features['BOL'] = df_common_features['Min']

  tmp_df = df_common_features[df_common_features['Symbol'].isin(mypf_df[mypf_df['InPortfolio'] != 'NA'].Symbol.values)]
  print('qualified stocks: '+str(len(tmp_df['Symbol'].unique())))
  tmp_df1 = tmp_df[tmp_df['LatestQtr'] == 1]
  print('with latest results: '+str(len(tmp_df1['Symbol'].unique())))
  tmp_df1 = tmp_df1[tmp_df1['StarStock'] == 1]
  print('still star stocks: '+str(len(tmp_df1['Symbol'].unique())))
  tmp_df['Investment'] = tmp_df['AvgCost'] * tmp_df['Shares']
  tmp_df['Current'] = round(tmp_df['Close'] * tmp_df['Shares'],0)
  tmp_df['Previous'] = tmp_df['Prev_Close'] * tmp_df['Shares']
  tmp_df['EstimatedST'] = tmp_df['NTT'] * tmp_df['Shares']
  tmp_df['EstimatedLT'] = tmp_df['LTT'] * tmp_df['Shares']
  tmp_df['Current P/L'] = round((tmp_df['Current'] - tmp_df['Investment']),0)
  tmp_df['Today P/L%'] = round((tmp_df['Current'] - tmp_df['Previous'])*100/tmp_df['Previous'],2)
  tmp_df['Current P/L%'] = round((tmp_df['Current'] - tmp_df['Investment'])*100/tmp_df['Investment'],2)
  tmp_df['EstimatedST P/L%'] = round((tmp_df['EstimatedST'] - tmp_df['Investment'])*100/tmp_df['Investment'],2)
  tmp_df['EstimatedLT P/L%'] = round((tmp_df['EstimatedLT'] - tmp_df['Investment'])*100/tmp_df['Investment'],2)
  tmp_df['NTT%'] = round((tmp_df['NTT'] - tmp_df['Close'])*100/tmp_df['Close'],2)
  tmp_df['LTT%'] = round((tmp_df['LTT'] - tmp_df['Close'])*100/tmp_df['Close'],2)
  tmp_df['Gained%'] = round((tmp_df['Close'] - tmp_df['BOL'])*100/tmp_df['BOL'],2)
  investment = round(sum(tmp_df['AvgCost']*tmp_df['Shares']),0)
  current = round(sum(tmp_df['Close']*tmp_df['Shares']),0)
  tmp_df['InitAlloc%'] = round(tmp_df['Investment']*100/investment,2)
  tmp_df['CurrAlloc%'] = round(tmp_df['Current']*100/current,2)
  tmp_df['FTT'] = tmp_df['LTT']
  tmp_df.loc[tmp_df['Strategy'] == 'NTT', 'FTT'] = tmp_df['NTT']
  tmp_df['FTT%'] = tmp_df['LTT%']
  tmp_df.loc[tmp_df['Strategy'] == 'NTT', 'FTT%'] = tmp_df['NTT%']
  tmp_df['FTT Amt'] = round(tmp_df['FTT%'] * tmp_df['Current']/100,0)
  tmp_df['OTT%'] = round((tmp_df['FTT'] - tmp_df['AvgCost'])*100/tmp_df['AvgCost'],2)
  tmp_df['RRR Ind'] = round(tmp_df['Current P/L']/tmp_df['FTT Amt'],2)
  tmp_df['Risk Ind'] = round(tmp_df['Current P/L%']*tmp_df['CurrAlloc%'],0)

  return tmp_df

# function to print portfolio features
def print_portfolio_stats(df_portfolio_features, myinvmt_df):
  from pyxirr import xirr

  total_booked_amt, reserve_amt, cy_booked_amt, py_booked_amt = get_amt()

  dates = myinvmt_df['Date'].values
  dates = np.append(dates, datetime.date.today().strftime('%d-%b-%y'))
  investment = myinvmt_df['Investment'].values
  dates= pd.to_datetime(dates)

  current = round(sum(df_portfolio_features['Close']*df_portfolio_features['Shares']),0) + reserve_amt
  investment_xirr = np.append(investment, current)
  cagr = round(xirr(pd.DataFrame({"dates": dates, "amounts": investment_xirr}))*100,2)

  investment = -sum(investment)
  invested = round(sum(df_portfolio_features['AvgCost']*df_portfolio_features['Shares']),0) + reserve_amt
  previous = round(sum(df_portfolio_features['Prev_Close']*df_portfolio_features['Shares']),0) + reserve_amt
  cy_invested = investment + py_booked_amt

  today_pnl_amount = current-previous
  today_pnl_percentage = round((current-previous)*100/previous,2)

  curr_pnl_amount = current-invested
  curr_pnl_percentage = round((curr_pnl_amount)*100/(cy_invested),2)

  cy_pnl_amount = cy_booked_amt + curr_pnl_amount
  cy_pnl_percentage = round((cy_pnl_amount)*100/cy_invested,2)

  overall_pnl_amount = total_booked_amt + curr_pnl_amount
  overall_pnl_percentage = round((overall_pnl_amount)*100/investment,2)

  estimate_st = round(sum(df_portfolio_features['FTT']*df_portfolio_features['Shares']),0)  + reserve_amt
  est_st_pnl_amount = estimate_st-current
  est_st_pnl_percentage = round((est_st_pnl_amount)*100/current,2)

  estimate_lt = round(sum(df_portfolio_features['LTT']*df_portfolio_features['Shares']),0)  + reserve_amt
  est_lt_pnl_amount = estimate_lt-current
  est_lt_pnl_percentage = round((est_lt_pnl_amount)*100/current,2)

  total_profit = round(sum(df_portfolio_features[df_portfolio_features['Current P/L%'] > 0]['Current']) - sum(df_portfolio_features[df_portfolio_features['Current P/L%'] > 0]['Investment']),0)
  total_loss = round(sum(df_portfolio_features[df_portfolio_features['Current P/L%'] < 0]['Current']) - sum(df_portfolio_features[df_portfolio_features['Current P/L%'] < 0]['Investment']),0)

  cy_booked_percentage = round((cy_booked_amt)*100/current,2)
  py_booked_percentage = round((py_booked_amt)*100/investment,2)
  total_booked_percentage = round((total_booked_amt)*100/investment,2)

  print('-------------------')
  print('Initial Investment: ', format_amt(investment))
  print('CY Investment: ', format_amt(cy_invested))
  print('Reserve: ', format_amt(reserve_amt))
  print('Current: ',  format_amt(current))
  print('-------------------')
  print('Today PnL: '+ '{} ({}%)'.format(format_amt(today_pnl_amount), today_pnl_percentage))
  print('Current PnL: '+ '{} ({}%)'.format(format_amt(curr_pnl_amount), curr_pnl_percentage))
  print('CY Booked + Current PnL: '+ '{} ({}%)'.format(format_amt(cy_pnl_amount), cy_pnl_percentage))
  print('-------------------')
  print('Total profit: ', format_amt(total_profit))
  print('Total loss: ', format_amt(total_loss))
  print('-------------------')
  print('Total Booked + Current PnL: '+ '{} ({}%)'.format(format_amt(overall_pnl_amount), overall_pnl_percentage))
  print('Total Booked PnL: '+ '{} ({}%)'.format(format_amt(total_booked_amt), total_booked_percentage))
  print('Curr Year Booked PnL: '+ '{} ({}%)'.format(format_amt(cy_booked_amt), cy_booked_percentage))
  print('Prev Year Booked PnL: '+ '{} ({}%)'.format(format_amt(py_booked_amt), py_booked_percentage))
  print('===================')
  print('Est FTT: ',  format_amt(estimate_st))
  print('Est FTT PnL: '+ '{} ({}%)'.format(format_amt(est_st_pnl_amount), est_st_pnl_percentage))

  print('===================')
  print('Deployed: ', format_amt(investment))

  print('Current: ', format_amt(current))

  print('CAGR/XIRR %: '+'{}%'.format(cagr))

In [8]:
# get start and end date
start_date, end_date = get_start_end_date()

# get portfolio and prospects data
mypfs_df = get_mypfs_df()
mypps_df = get_mypps_df()
myinvmt_df = get_myinvmt_df()

# merge above datasets
mypf_df = pd.merge(mypfs_df, mypps_df, on="Symbol")

# seggregate dm and sv portfolio
dm_pf = mypf_df[mypf_df['InPortfolio'] == 'DM']
sv_pf = mypf_df[mypf_df['InPortfolio'] == 'SV']

# build portfolio stock dataframe
dm_stocks = get_stock_ids(dm_pf)
sv_stocks = get_stock_ids(sv_pf)
df_stocks = pd.concat([dm_pf,sv_pf], ignore_index = True)

# arrange common and diff stock features
common_cols = ['Symbol', 'Target', 'Criteria', 'Strategy', 'CumlRnk', 'LatestQtr', 'StarStock', 'Conviction', 'Category', 'InFolio', 'XIRR', 'MBQ']
diff_cols = ['Symbol', 'AvgCost', 'Shares']
df_stocks = arrange_features(df_stocks, common_cols, diff_cols)

# get common features
stock_ids = df_stocks['Symbol'].values
df_common_features = get_common_features(stock_ids, df_stocks)

df_common_features.reset_index(drop=True, inplace=True)
df_common_features.drop(['Date'], axis=1, inplace=True)
# get and print portfolio features
df_portfolio_features = get_portfolio_features(df_common_features)

print_portfolio_stats(df_portfolio_features, myinvmt_df)

df = df_portfolio_features
#plot_pie_chart(df, 'CapType', 'Current')
list_ox40n = list(df[df['MBQ'].str.contains('OX40N', na=False)]['Symbol'].values)

Run date time (IST): 2026-07-24 10:49:43
-------------------
qualified stocks: 92
with latest results: 31
still star stocks: 20
-------------------
Initial Investment:  1.40 C
CY Investment:  1.82 C
Reserve:  1.49 K
Current:  1.50 C
-------------------
Today PnL: -87.72 K (-0.58%)
Current PnL: -33.03 L (-18.11%)
CY Booked + Current PnL: -30.95 L (-16.97%)
-------------------
Total profit:  4.49 L
Total loss:  -37.52 L
-------------------
Total Booked + Current PnL: 11.92 L (8.54%)
Total Booked PnL: 44.95 L (32.22%)
Curr Year Booked PnL: 2.08 L (1.39%)
Prev Year Booked PnL: 42.87 L (30.73%)
===================
Est FTT:  2.55 C
Est FTT PnL: 1.05 C (69.74%)
===================
Deployed:  1.40 C
Current:  1.50 C
CAGR/XIRR %: 3.29%

In [9]:
# top 5 near their targets
cols = ['Symbol', 'Today P/L%', 'Current P/L%', 'FTT%', 'OTT%', 'FTT Amt', 'Current P/L', 'Current', 'FTT', 'Dev%_PE', 'RSI_14','Conviction', 'Spread%',  'CumlRnk', 'RRR Ind', 'CurrAlloc%', 'Gained%', 'Criteria', 'Strategy', 'Category']
df_tmp = df_portfolio_features[~df_portfolio_features['Symbol'].isin(['ENRIN','BLUSPRING','DIGITIDE'])]
df_tmp = df_tmp.sort_values(by = 'FTT Amt', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
68,SATIN,6.16,48.16,2.48,51.83,10152.0,133059.0,409343.0,274.00,32.72,60.0,H-SC,45.04,159.0,13.11,2.73,99.41,XY24,NTT,FINANCE
59,PIDILITIND,-1.09,9.64,7.19,17.52,11124.0,13600.0,154710.0,1658.32,-23.17,47.0,X-LC,7.95,5.0,1.22,1.03,22.35,X40,ATH,CHEMICALS
75,SURYODAY,12.59,16.26,5.83,23.03,12137.0,29111.0,208182.0,216.00,125.88,68.0,H-SC,23.51,166.0,2.40,1.39,76.71,XR,NTT,BANKS
73,SONACOMS,-0.07,25.59,10.43,38.69,13251.0,25891.0,127050.0,801.69,-0.49,79.0,M-MC,25.58,193.0,1.95,0.85,80.25,AR,ATH,AUTO
83,TTKPRESTIG,-2.82,-16.99,20.59,0.09,17224.0,-17127.0,83650.0,770.00,94.24,56.0,M-SC,10.58,250.0,-0.99,0.56,48.95,OX40N,NTT,DURABLES

In [10]:
# top 5 today
df_tmp = df_portfolio_features.sort_values(by = 'Today P/L%', ascending=False)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
75,SURYODAY,12.59,16.26,5.83,23.03,12137.0,29111.0,208182.0,216.00,125.88,68.0,H-SC,23.51,166.0,2.40,1.39,76.71,XR,NTT,BANKS
68,SATIN,6.16,48.16,2.48,51.83,10152.0,133059.0,409343.0,274.00,32.72,60.0,H-SC,45.04,159.0,13.11,2.73,99.41,XY24,NTT,FINANCE
84,UNITDSPR,5.14,8.46,11.35,20.77,28822.0,19797.0,253941.0,1644.00,-3.85,72.0,X-MC,4.59,64.0,0.69,1.69,22.07,X40N,NTT,BREWERIES
39,ICICIGI,4.72,-12.16,35.34,18.89,62121.0,-24329.0,175780.0,2244.41,-26.21,41.0,X-MC,6.63,66.0,-0.39,1.17,4.72,X40,ATH,INSURANCE
32,HAVELLS,1.18,-21.80,68.07,31.42,174581.0,-71518.0,256473.0,2052.62,-26.37,59.0,X-MC,10.44,63.0,-0.41,1.71,8.18,X40,ATH,ELECTRICAL

In [11]:
# bottom 5 today
df_tmp = df_portfolio_features.sort_values(by = 'Today P/L%', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
62,RAJOOENG,-4.62,-47.62,166.53,39.61,89410.0,-48810.0,53690.0,143.10,-64.48,54.0,H-SC,20.49,136.0,-0.55,0.36,15.02,AR,ATH,MISC
67,ROUTE,-4.29,-56.38,285.50,68.16,165718.0,-75021.0,58045.0,2215.45,-64.57,56.0,H-SC,8.46,141.0,-0.45,0.39,38.28,SR,ATH,IT
52,LAOPALA,-3.77,-45.26,154.09,39.09,110584.0,-59339.0,71766.0,464.00,56.66,50.0,H-SC,8.72,154.0,-0.54,0.48,11.35,AR,NTT,CERAMICS
25,FINCABLES,-3.73,23.74,68.02,107.91,124272.0,35055.0,182699.0,1641.55,11.11,35.0,M-SC,20.78,220.0,0.28,1.22,37.45,OX40N,ATH,CABLES
42,INDIAMART,-3.47,-24.50,166.13,100.92,154694.0,-30220.0,93116.0,4675.60,-66.02,29.0,H-SC,9.50,140.0,-0.20,0.62,0.00,AR,ATH,MISC

In [12]:
# top 5 to exit based on CumlRnk
df_tmp = df_portfolio_features[~df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])]
df_tmp = df_tmp[(df_tmp['Current P/L%'] > -1) & (df_tmp['Current P/L%'] < 1)].sort_values(by = 'CumlRnk', ascending=False)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
72,SIS,-0.25,0.13,21.1,21.26,23459.0,148.0,111180.0,528.0,2654.92,56.0,H-SC,24.59,168.0,0.01,0.74,65.31,OX40N,NTT,MISC

In [13]:
# OX40N stocks to exit
df_tmp = df_portfolio_features[(df_portfolio_features['Symbol'].isin(list_ox40n))].sort_values(by = 'Current P/L%', ascending=False)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
25,FINCABLES,-3.73,23.74,68.02,107.91,124272.0,35055.0,182699.0,1641.55,11.11,35.0,M-SC,20.78,220.0,0.28,1.22,37.45,OX40N,ATH,CABLES
72,SIS,-0.25,0.13,21.10,21.26,23459.0,148.0,111180.0,528.00,2654.92,56.0,H-SC,24.59,168.0,0.01,0.74,65.31,OX40N,NTT,MISC
83,TTKPRESTIG,-2.82,-16.99,20.59,0.09,17224.0,-17127.0,83650.0,770.00,94.24,56.0,M-SC,10.58,250.0,-0.99,0.56,48.95,OX40N,NTT,DURABLES
16,CERA,-1.56,-21.42,57.65,23.89,79690.0,-37673.0,138230.0,9475.00,-24.11,43.0,H-SC,14.68,153.0,-0.47,0.92,34.37,OX40N,NTT,CERAMICS
69,SFL,0.58,-26.21,71.60,26.63,138546.0,-68718.0,193500.0,1287.00,46.48,54.0,M-SC,24.63,242.0,-0.50,1.29,61.49,XY24,NTT,MISC

In [14]:
# top 5 to book for rotation
df_tmp = df_portfolio_features[(df_portfolio_features['Current P/L%'] > 20) ].sort_values(by = 'CumlRnk', ascending=False)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
25,FINCABLES,-3.73,23.74,68.02,107.91,124272.0,35055.0,182699.0,1641.55,11.11,35.0,M-SC,20.78,220.0,0.28,1.22,37.45,OX40N,ATH,CABLES
73,SONACOMS,-0.07,25.59,10.43,38.69,13251.0,25891.0,127050.0,801.69,-0.49,79.0,M-MC,25.58,193.0,1.95,0.85,80.25,AR,ATH,AUTO
68,SATIN,6.16,48.16,2.48,51.83,10152.0,133059.0,409343.0,274.00,32.72,60.0,H-SC,45.04,159.0,13.11,2.73,99.41,XY24,NTT,FINANCE
60,QUESS,-0.35,20.83,43.92,73.90,56672.0,22242.0,129035.0,424.00,-34.99,66.0,X-SC,33.33,80.0,0.39,0.86,75.90,XY24,NTT,MISC

In [15]:
# top 5 to monitor for exit
df_tmp = df_portfolio_features[~df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])]
df_tmp = df_tmp[(df_tmp['Current P/L%'] > 0) ].sort_values(by = 'Dev%_PE', ascending=False)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
72,SIS,-0.25,0.13,21.10,21.26,23459.0,148.0,111180.0,528.00,2654.92,56.0,H-SC,24.59,168.0,0.01,0.74,65.31,OX40N,NTT,MISC
75,SURYODAY,12.59,16.26,5.83,23.03,12137.0,29111.0,208182.0,216.00,125.88,68.0,H-SC,23.51,166.0,2.40,1.39,76.71,XR,NTT,BANKS
74,STARHEALTH,-0.29,11.90,31.60,47.26,99403.0,33445.0,314568.0,761.00,76.63,50.0,H-SC,18.94,173.0,0.34,2.10,36.51,XY24,NTT,INSURANCE
68,SATIN,6.16,48.16,2.48,51.83,10152.0,133059.0,409343.0,274.00,32.72,60.0,H-SC,45.04,159.0,13.11,2.73,99.41,XY24,NTT,FINANCE
25,FINCABLES,-3.73,23.74,68.02,107.91,124272.0,35055.0,182699.0,1641.55,11.11,35.0,M-SC,20.78,220.0,0.28,1.22,37.45,OX40N,ATH,CABLES

In [16]:
# top 5 to book for rotation from weak conviction
df_tmp = df_portfolio_features[~df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])]
df_tmp = df_tmp[~df_tmp['Criteria'].isin(['XY25','XY24','X40', 'X40N'])].sort_values(by = 'RRR Ind', ascending=False)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
75,SURYODAY,12.59,16.26,5.83,23.03,12137.0,29111.0,208182.0,216.00,125.88,68.0,H-SC,23.51,166.0,2.40,1.39,76.71,XR,NTT,BANKS
73,SONACOMS,-0.07,25.59,10.43,38.69,13251.0,25891.0,127050.0,801.69,-0.49,79.0,M-MC,25.58,193.0,1.95,0.85,80.25,AR,ATH,AUTO
91,ZYDUSLIFE,-1.30,17.22,15.70,35.63,38569.0,36090.0,245664.0,1286.17,1.80,47.0,H-MC,17.22,120.0,0.94,1.64,29.17,AR,ATH,PHARMA
25,FINCABLES,-3.73,23.74,68.02,107.91,124272.0,35055.0,182699.0,1641.55,11.11,35.0,M-SC,20.78,220.0,0.28,1.22,37.45,OX40N,ATH,CABLES
72,SIS,-0.25,0.13,21.10,21.26,23459.0,148.0,111180.0,528.00,2654.92,56.0,H-SC,24.59,168.0,0.01,0.74,65.31,OX40N,NTT,MISC

In [17]:
# top 5 to accumulate based on lowest RSI_14
df_tmp = df_portfolio_features[df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])].sort_values(by = 'RSI_14', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
87,VBL,-1.01,-8.21,47.48,35.37,137648.0,-25935.0,289907.0,670.16,-18.98,29.0,X-LC,6.99,13.0,-0.19,1.93,19.15,X40N,ATH,FMCG
81,TMPV,-1.42,-27.23,87.68,36.58,227053.0,-96884.0,258957.0,600.00,-84.72,31.0,X-LC,7.62,4.0,-0.43,1.72,8.83,XY24,NTT,AUTO
34,HDFCBANK,-0.70,-11.23,44.61,28.37,93013.0,-26383.0,208502.0,1073.00,-24.48,34.0,X-LC,10.61,26.0,-0.28,1.39,3.11,X40,BTT,BANKS
7,BAJAJHFL,-0.68,-24.76,115.48,62.13,237239.0,-67609.0,205437.0,181.50,-38.00,39.0,X-MC,6.66,60.0,-0.28,1.37,15.24,X40N,ATH,FINANCE
45,INFY,-2.39,-30.40,92.88,34.24,202266.0,-95117.0,217771.0,1972.00,-45.21,39.0,X-LC,20.68,3.0,-0.47,1.45,3.77,X40,NTT,IT

In [18]:
# top 5 to accumulate based on Spread and CumlRnk
df_tmp = df_portfolio_features[df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])]
df_tmp = df_tmp[(df_tmp['CumlRnk'] < 100)].sort_values(by = 'Spread%', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
11,BERGEPAINT,-0.61,-9.59,38.61,25.32,89975.0,-24714.0,233035.0,680.00,-14.46,42.0,X-MC,1.52,68.0,-0.27,1.55,21.29,XY24,NTT,PAINTS
19,COLPAL,-1.21,-20.97,76.96,39.86,160192.0,-55215.0,208150.0,3683.41,-4.28,55.0,X-MC,1.71,62.0,-0.34,1.39,17.74,XY25,ATH,FMCG
23,DMART,0.63,-3.23,33.93,29.60,81953.0,-8064.0,241536.0,5391.45,-18.44,45.0,X-LC,1.82,14.0,-0.10,1.61,10.40,X40N,ATH,FMCG
1,ABBOTINDIA,-3.29,-6.24,25.92,18.07,43468.0,-11155.0,167700.0,35195.00,-20.15,60.0,X-MC,2.63,58.0,-0.26,1.12,11.00,X40,ATH,PHARMA
17,CIPLA,0.30,14.92,16.12,33.43,28372.0,22845.0,176006.0,1648.14,-11.14,48.0,X-LC,3.10,18.0,0.81,1.17,20.15,X40N,ATH,PHARMA

In [19]:
# top 5 to accumulate based on lowest Gained%
df_tmp = df_portfolio_features[df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])].sort_values(by = 'Gained%', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
65,RELIANCE,0.05,-18.29,53.35,25.30,87603.0,-36759.0,164204.0,1952.00,-20.42,41.0,X-LC,7.70,21.0,-0.42,1.09,1.12,XY25,BTT,REFINERIES
35,HDFCLIFE,0.27,-9.65,46.87,32.71,63439.0,-14450.0,135350.0,811.41,-29.45,40.0,X-LC,15.74,31.0,-0.23,0.90,1.68,X40,ATH,INSURANCE
47,ITC,0.25,-25.72,60.28,19.06,152311.0,-87494.0,252672.0,452.00,-59.16,46.0,X-LC,12.52,1.0,-0.57,1.68,2.34,X40,NTT,FMCG
58,PGHH,-0.36,-32.81,96.46,32.01,138393.0,-70048.0,143472.0,17616.87,-54.51,50.0,X-MC,19.96,57.0,-0.51,0.96,2.83,X40,ATH,FMCG
34,HDFCBANK,-0.70,-11.23,44.61,28.37,93013.0,-26383.0,208502.0,1073.00,-24.48,34.0,X-LC,10.61,26.0,-0.28,1.39,3.11,X40,BTT,BANKS

In [20]:
# top 5 to accumulate based on lowest CurrAlloc%
df_tmp = df_portfolio_features[df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])].sort_values(by = 'CurrAlloc%', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
10,BATAINDIA,-2.95,-56.53,211.03,35.20,118038.0,-72736.0,55934.0,2096.00,-26.64,43.0,X-SC,17.60,91.0,-0.62,0.37,10.93,X40,NTT,FOOTWEAR
64,RELAXO,-3.05,-49.59,202.12,52.31,147909.0,-71981.0,73179.0,1176.00,-46.37,50.0,X-SC,11.48,92.0,-0.49,0.49,63.62,X40N,NTT,FOOTWEAR
60,QUESS,-0.35,20.83,43.92,73.90,56672.0,22242.0,129035.0,424.00,-34.99,66.0,X-SC,33.33,80.0,0.39,0.86,75.90,XY24,NTT,MISC
35,HDFCLIFE,0.27,-9.65,46.87,32.71,63439.0,-14450.0,135350.0,811.41,-29.45,40.0,X-LC,15.74,31.0,-0.23,0.90,1.68,X40,ATH,INSURANCE
51,KOTAKBANK,0.42,2.27,18.21,20.90,25789.0,3146.0,141618.0,452.46,-12.44,48.0,X-LC,4.56,12.0,0.12,0.94,8.49,X40,ATH,BANKS

In [21]:
# top 5 to accumulate based on CumlRnk
df_tmp = df_portfolio_features.sort_values(by = 'CumlRnk', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
47,ITC,0.25,-25.72,60.28,19.06,152311.0,-87494.0,252672.0,452.00,-59.16,46.0,X-LC,12.52,1.0,-0.57,1.68,2.34,X40,NTT,FMCG
79,TCS,-0.13,-34.24,88.87,24.20,270734.0,-158633.0,304640.0,4230.71,-44.28,59.0,X-LC,19.06,2.0,-0.59,2.03,13.60,X40,ATH,IT
45,INFY,-2.39,-30.40,92.88,34.24,202266.0,-95117.0,217771.0,1972.00,-45.21,39.0,X-LC,20.68,3.0,-0.47,1.45,3.77,X40,NTT,IT
81,TMPV,-1.42,-27.23,87.68,36.58,227053.0,-96884.0,258957.0,600.00,-84.72,31.0,X-LC,7.62,4.0,-0.43,1.72,8.83,XY24,NTT,AUTO
59,PIDILITIND,-1.09,9.64,7.19,17.52,11124.0,13600.0,154710.0,1658.32,-23.17,47.0,X-LC,7.95,5.0,1.22,1.03,22.35,X40,ATH,CHEMICALS

In [22]:
# top 5 for average up
df_tmp = df_portfolio_features[(df_portfolio_features['Dev%_200'] > 5)].sort_values(by = 'CurrAlloc%', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
44,INDUSINDBK,-1.02,-26.52,80.86,32.89,45871.0,-20478.0,56729.0,1800.00,-366.81,52.0,L-MC,13.41,258.0,-0.45,0.38,39.86,XR,NTT,BANKS
64,RELAXO,-3.05,-49.59,202.12,52.31,147909.0,-71981.0,73179.0,1176.00,-46.37,50.0,X-SC,11.48,92.0,-0.49,0.49,63.62,X40N,NTT,FOOTWEAR
3,ALKYLAMINE,-2.75,-24.48,154.95,92.54,118146.0,-24715.0,76248.0,4520.85,-19.07,45.0,H-SC,11.96,142.0,-0.21,0.51,44.79,SR,ATH,CHEMICALS
83,TTKPRESTIG,-2.82,-16.99,20.59,0.09,17224.0,-17127.0,83650.0,770.00,94.24,56.0,M-SC,10.58,250.0,-0.99,0.56,48.95,OX40N,NTT,DURABLES
72,SIS,-0.25,0.13,21.10,21.26,23459.0,148.0,111180.0,528.00,2654.92,56.0,H-SC,24.59,168.0,0.01,0.74,65.31,OX40N,NTT,MISC

In [23]:
# top 5 RSP
df_tmp = df_portfolio_features.sort_values(by = 'RSP', ascending=False)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
75,SURYODAY,12.59,16.26,5.83,23.03,12137.0,29111.0,208182.0,216.00,125.88,68.0,H-SC,23.51,166.0,2.40,1.39,76.71,XR,NTT,BANKS
60,QUESS,-0.35,20.83,43.92,73.90,56672.0,22242.0,129035.0,424.00,-34.99,66.0,X-SC,33.33,80.0,0.39,0.86,75.90,XY24,NTT,MISC
73,SONACOMS,-0.07,25.59,10.43,38.69,13251.0,25891.0,127050.0,801.69,-0.49,79.0,M-MC,25.58,193.0,1.95,0.85,80.25,AR,ATH,AUTO
77,TANLA,-3.28,-32.39,221.35,117.25,405179.0,-87712.0,183049.0,1922.32,-31.83,62.0,H-SC,6.30,147.0,-0.22,1.22,60.26,AR,ATH,IT
22,DIXON,-1.08,-0.34,38.40,37.92,99802.0,-897.0,259901.0,18931.72,-57.60,58.0,X-MC,7.74,54.0,-0.01,1.73,41.41,X40N,ATH,IT

In [24]:
# Top N allocation
df_tmp = df_portfolio_features.sort_values(by = 'CurrAlloc%', ascending=False)
top_n_values = [10, 25, 50]

sum_df = pd.DataFrame({
    'Top_N': top_n_values,
    'Sum_Alloc%': [df_tmp['CurrAlloc%'].head(n).sum() for n in top_n_values]
})

sum_df

   Top_N  Sum_Alloc%
0     10       19.30
1     25       42.35
2     50       72.77

In [25]:
# market-cap-wise allocation
df_tmp = df_portfolio_features[cols]
df_tmp.groupby(df_tmp['Conviction'].str[-2:])['CurrAlloc%'].sum().sort_values(ascending=False)

Conviction
SC    43.44
LC    30.13
MC    26.47
Name: CurrAlloc%, dtype: float64

In [26]:
# criteria-wise allocation
df_portfolio_features.groupby('Criteria')['CurrAlloc%'].sum().sort_values(ascending=False)

Criteria
XY24     27.28
X40      24.87
X40N     17.42
XR        8.99
AR        7.07
OX40N     6.98
XY25      6.53
SR        0.90
Name: CurrAlloc%, dtype: float64

In [27]:
# conviction-wise allocation
df_portfolio_features.groupby('Conviction')['CurrAlloc%'].sum().sort_values(ascending=False)

Conviction
X-LC    28.11
H-SC    22.88
X-MC    21.22
X-SC    10.13
M-SC     9.88
H-MC     2.71
M-MC     2.16
H-LC     1.22
M-LC     0.80
L-SC     0.55
L-MC     0.38
Name: CurrAlloc%, dtype: float64

In [28]:
# sector-wise stats
df_tmp = df_portfolio_features.groupby('Category')[['CurrAlloc%', 'Current', 'Current P/L', 'FTT Amt']].sum().sort_values(by=['Current', 'Current P/L'], ascending=False)
df_tmp['Current P/L%'] = round(df_tmp['Current P/L'] * 100 / df_tmp['Current'], 2)
df_tmp['FTT%'] = round(df_tmp['FTT Amt'] * 100 / df_tmp['Current'], 2)
cols = ['CurrAlloc%', 'Current P/L%', 'FTT%']
df_tmp[cols].sort_values(by=['CurrAlloc%'], ascending=False)

               CurrAlloc%  Current P/L%    FTT%
Category
FMCG                14.38        -22.66   65.69
FINANCE             11.37         -8.05   54.87
IT                  10.22        -46.87  119.55
MISC                 7.25        -23.12   75.94
AUTO                 6.60        -10.37   51.52
BANKS                5.56         -8.90   59.22
PAINTS               5.35        -22.67   43.59
INSURANCE            5.25         -5.02   40.44
PHARMA               5.24          5.83   23.32
ELECTRICAL           4.17        -12.93   52.66
CHEMICALS            2.14        -26.36  100.95
HEALTHCARE           2.13        -12.27   41.57
APPARELS             1.87          4.47   27.61
AC                   1.80        -18.49   50.62
BREWERIES            1.69          7.80   11.35
FOOTWEAR             1.69        -74.52  144.50
DURABLES             1.62        -60.01   98.93
REALTY               1.60          7.82    7.33
TRAVEL               1.51        -97.90  197.00
CERAMICS             1.40        -46.20   90.61
CABLES               1.22         19.19   68.02
ENGINEERING          1.21        -33.40   94.41
JEWELLERY            1.11        -91.72  158.33
REFINERIES           1.09        -22.39   53.35
CEMENT               1.06        -68.94  195.33
ENTERTAINMENT        0.71        -81.73  190.11
TEXTILES             0.41        -50.36   93.24
HOTELS               0.39        -96.35  165.60

In [29]:
# money to be made criteria-wise
df_portfolio_features.groupby('Criteria')['FTT Amt'].agg(['sum', 'count']).sort_values(by='sum', ascending=False)

                sum  count
Criteria
XY24      3504778.0     21
X40       1933095.0     19
XR        1329765.0     13
AR        1116146.0      9
X40N      1101957.0     13
OX40N      745432.0     10
XY25       456435.0      5
SR         283864.0      2

In [30]:
# money to be made conviction-wise
df_portfolio_features.groupby('Conviction')['FTT Amt'].agg(['sum', 'count']).sort_values(by='sum', ascending=False)

                  sum  count
Conviction
H-SC        3340426.0     24
X-LC        2047376.0     21
X-MC        1530745.0     15
M-SC        1439599.0     14
X-SC        1281642.0      9
H-MC         292194.0      2
L-SC         209126.0      2
M-LC         171329.0      1
M-MC          62343.0      2
H-LC          50821.0      1
L-MC          45871.0      1

In [31]:
# money to be made criteria and conviction-wise
df_portfolio_features.groupby(['Conviction', 'Criteria'])['FTT Amt'].agg(['sum', 'count']).sort_values(by='sum', ascending=False)

                           sum  count
Conviction Criteria
X-LC       X40       1056497.0     10
H-SC       XY24      1036596.0      6
           AR         936451.0      5
M-SC       XY24       841252.0      6
H-SC       XR         776612.0      7
X-SC       XY24       750919.0      4
X-MC       X40        663056.0      7
X-LC       X40N       401278.0      6
X-MC       X40N       383498.0      4
X-LC       XY24       380175.0      2
M-SC       OX40N      325169.0      5
X-SC       X40N       317181.0      3
H-SC       OX40N      306903.0      4
           SR         283864.0      2
H-MC       XY24       253625.0      1
X-MC       XY24       242211.0      2
           XY25       241980.0      2
X-SC       X40        213542.0      2
M-SC       XR         196124.0      2
M-LC       XR         171329.0      1
X-LC       XY25       165363.0      2
L-SC       OX40N      113360.0      1
           XR          95766.0      1
M-SC       AR          77054.0      1
H-LC       AR          50821.0      1
M-MC       XY25        49092.0      1
L-MC       XR          45871.0      1
X-LC       XR          44063.0      1
H-MC       AR          38569.0      1
M-MC       AR          13251.0      1

In [32]:
# notebook execution time

end_time = time.time()
execution_time = round(end_time - start_time, 0)
print(f"Notebook execution time: {execution_time} seconds")

Notebook execution time: 26.0 seconds