<a href="https://colab.research.google.com/github/ankit-rathi/Quantvesting_v2/blob/main/myStocks_Portfolio_Analysis.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
'''
!pip install pandas==2.2.2 -qq
!pip install pyxirr -qq
!pip install ta -qq
!pip install yfinance==0.2.59 -qq
'''

'\n!pip install pandas==2.2.2 -qq\n!pip install pyxirr -qq\n!pip install ta -qq\n!pip install yfinance==0.2.59 -qq\n'

In [2]:
# import libraries

import numpy as np
import pandas as pd
import datetime
import warnings
warnings.filterwarnings('ignore')
import yfinance as yfin
import ta
import matplotlib.pyplot as plt
import requests

In [3]:
# notebook start time
import time
import datetime
import pytz

start_time = time.time()

# function to print date timestamp
def print_date_time():
  tz_NY = pytz.timezone('Asia/Kolkata')
  datetime_NY = datetime.datetime.now(tz_NY)
  print("Run date time (IST):", datetime_NY.strftime("%Y-%m-%d %H:%M:%S"))

In [4]:
# function to get booked and reserved amount
def get_amt():
  # fetch the JSON data from the URL
  url = "https://raw.githubusercontent.com/ankit-rathi/Tradevesting_v1/main/data/myPortfolioAmts.json"
  response = requests.get(url)
  pf_amts = response.json()  # parse the JSON data

  # extract values from the JSON
  py_booked_amt_dm = pf_amts["py_booked_amt_dm"]
  py_booked_amt_sv = pf_amts["py_booked_amt_sv"]
  cy_booked_amt_dm = pf_amts["cy_booked_amt_dm"]
  cy_booked_amt_sv = pf_amts["cy_booked_amt_sv"]
  reserve_amt_dm = pf_amts["reserve_amt_dm"]
  reserve_amt_sv = pf_amts["reserve_amt_sv"]

  # perform calculations
  py_booked_amt = py_booked_amt_dm + py_booked_amt_sv
  cy_booked_amt = cy_booked_amt_dm + cy_booked_amt_sv
  reserve_amt = reserve_amt_dm + reserve_amt_sv
  total_booked_amt = py_booked_amt + cy_booked_amt

  return total_booked_amt, reserve_amt, cy_booked_amt, py_booked_amt

gen_output = 0

In [5]:
# function to format the amount
def format_amt(number):
    abs_number = abs(number)

    if abs_number >= 1_00_00_000:  # Crores
        formatted_amt = f"{number / 1_00_00_000:.2f} C"
    elif abs_number >= 1_00_000:  # Lakhs
        formatted_amt = f"{number / 1_00_000:.2f} L"
    elif abs_number >= 1_000:  # Thousands
        formatted_amt = f"{number / 1_000:.2f} K"
    else:
        formatted_amt = f"{number:.2f}"

    return formatted_amt

# function to set start and end date
def get_start_end_date():
  start_date = (datetime.date.today() + datetime.timedelta(days=-365)).strftime('%Y-%m-%d')
  end_date = (datetime.date.today() + datetime.timedelta(days=1)).strftime('%Y-%m-%d')
  return start_date, end_date

# function to fetch my portfolio csv
def get_mypfs_df():
  mypfs_df = pd.read_csv('https://raw.githubusercontent.com/ankit-rathi/Tradevesting_v1/main/data/myPortfolioStocks.csv')
  return mypfs_df

# function to fetch my prospects csv
def get_mypps_df():
  mypps_df = pd.read_csv('https://raw.githubusercontent.com/ankit-rathi/Tradevesting_v1/main/data/myProspectsScrips.csv')
  return mypps_df

# function to fetch screener data
def get_myscreen_df():
  myscreen_df = pd.read_csv('https://raw.githubusercontent.com/ankit-rathi/Tradevesting_v1/main/data/myScreenerDB.csv')
  return myscreen_df

# function to fetch momentum data
def get_myinvmt_df():
  myinvmt_df = pd.read_csv('https://raw.githubusercontent.com/ankit-rathi/Tradevesting_v1/main/data/myInvestments.csv')
  return myinvmt_df

# function to get the stock ids
def get_stock_ids(df_pf):
  stock_n100 = df_pf['Symbol'].unique()

  exclude = ['CADILAHC','MMTC', 'MASFIN']

  stock_ids = df_pf[~df_pf['Symbol'].isin(exclude) ]['Symbol'].unique()

  #mypf = mypf[mypf.Forecast.notnull()]
  #stock_ids = mypf['Symbol'].unique()

  #stock_ids.sort()
  return stock_ids

# get features from screener data
def get_screener_features():
  myscreen_df = get_myscreen_df()
  cols = ['Symbol', 'EPS', 'MedPE', 'ROCE%', 'ROE%', 'CapType']
  return myscreen_df[cols]

# get relative strength
def get_relative_strength(stock_list):

    # Dictionary to store stock tickers and their corresponding percentage price change
    stock_changes = {}

    # Loop through each stock and fetch its price data
    for stock in stock_list:
        try:
            # Download the stock data for the given date range
            stock_data = yfin.Ticker(stock + '.NS').history(period='1mo', interval='1d')[map(str.title, ['open', 'close', 'low', 'high', 'volume'])]

            # Calculate the percentage change for the stock
            if len(stock_data) > 0:
                start_price = stock_data['Close'].iloc[0]
                end_price = stock_data['Close'].iloc[-1]
                percent_change = round(((end_price - start_price) / start_price) * 100, 2)
                stock_changes[stock] = percent_change
            else:
                stock_changes[stock] = np.nan  # If no data is available, set to NaN

        except Exception as e:
            print(f"Error fetching data for {stock}: {e}")
            stock_changes[stock] = np.nan

    # Create a DataFrame with stock tickers and their percentage changes
    df = pd.DataFrame(list(stock_changes.items()), columns=['Symbol', 'Percent_Change'])

    # Drop any stocks with missing data (NaN values)
    df = df.dropna()

    # Calculate the percentile rank based on percentage change
    df['RSP'] = round(df['Percent_Change'].rank(pct=True) * 100, 2)
    cols = ['Symbol', 'RSP']
    df = df[cols]
    # Sort by percentile rank (optional)
    df = df.sort_values(by='RSP', ascending=False).reset_index(drop=True)

    return df

In [6]:
# function to get stock technicals
def stock_prec_dev(stock_symbol):
    #stock_symbol = 'ULTRACEMCO.NS'
    short_window = 20
    mid_window = 50
    long_window = 200
    moving_avg = 'SMA'

    start = datetime.datetime(*map(int, start_date.split('-')))
    end = datetime.datetime(*map(int, end_date.split('-')))

    stock_df = yfin.Ticker(stock_symbol + '.NS').history(period='max', interval='1d')[map(str.title, ['open', 'close', 'low', 'high', 'volume'])]

    stock_df['Max'] = round(max(stock_df['Close']),2)
    stock_df = stock_df[(stock_df.index <= end_date) & (stock_df.index >= start_date)]
    stock_df['200_SMA'] = round(stock_df['Close'].rolling(window = 200, min_periods = 1).mean(),0)
    stock_df['Dev%_200'] = round((stock_df['Close'] - stock_df['200_SMA'])*100/stock_df['200_SMA'],2)
    stock_df.dropna(axis = 0, inplace = True) # remove any null rows

    stock_df['20_SMA'] = stock_df['Close'].rolling(window=20).mean()
    stock_df['50_SMA'] = stock_df['Close'].rolling(window=50).mean()
    stock_df['Symbol'] = stock_symbol

    stock_df['Close'] = round(stock_df['Close'],2)
    stock_df['Min'] = round(min(stock_df['Close']),2)
    stock_df['RSI_14'] = ta.momentum.RSIIndicator(close=stock_df['Close'], window=14).rsi()
    stock_df['RSI_14'] = round(stock_df['RSI_14'],0)
    stock_df['Prev_Close'] = stock_df['Close'].shift(1)
    stock_df.drop(['Open', 'Low', 'High', 'Volume'], axis=1, inplace=True)
    stock_df = stock_df.tail(1)

    max_SMA = max(stock_df['20_SMA'].item(), stock_df['50_SMA'].item(), stock_df['200_SMA'].item())
    min_SMA = min(stock_df['20_SMA'].item(), stock_df['50_SMA'].item(), stock_df['200_SMA'].item())
    ABS_Spread = max_SMA - min_SMA
    stock_df['Spread%'] = round((ABS_Spread / stock_df['200_SMA'].item()) * 100,2)

    return stock_df

# function to compute stock attributes
def get_common_features(stock_ids, df_mypf):

  df_prec_dev = pd.DataFrame()
  df_tmp = get_screener_features()
  df_rs = get_relative_strength(stock_ids)

  for stock_id in stock_ids:
      tmp = stock_prec_dev(stock_id)
      tmp = tmp.reset_index()
      df_prec_dev = pd.concat([df_prec_dev, tmp], ignore_index = True)
  df_prec_dev = pd.merge(df_prec_dev, df_mypf, on= 'Symbol')
  df_prec_dev = pd.merge(df_prec_dev, df_tmp, on= 'Symbol', how='left')
  df_prec_dev = pd.merge(df_prec_dev, df_rs, on= 'Symbol', how='left')
  #print(df_prec_dev.columns)
  df_prec_dev['Curr_PE'] = round(df_prec_dev['Close']/df_prec_dev['EPS'],1)
  df_prec_dev['Dev%_PE'] = round((df_prec_dev['Curr_PE'] - df_prec_dev['MedPE'])*100/df_prec_dev['MedPE'],2)
  df_prec_dev['Conviction'] = df_prec_dev['Conviction'] + '-' + df_prec_dev['CapType']
  return df_prec_dev

# function to arrange stock features
def arrange_features(df_stocks, common_cols, diff_cols):
  df_stocks_common = df_stocks[common_cols].drop_duplicates()
  df_stocks_diff = df_stocks[diff_cols]
  df_stocks_diff['Investment'] = df_stocks_diff['AvgCost'] * df_stocks_diff['Shares']
  df_stocks_diff = df_stocks_diff.groupby(['Symbol'])[['Shares', 'Investment']].aggregate(['sum']).reset_index()
  df_stocks_diff.columns = ['Symbol', 'Shares', 'Investment']
  df_stocks_diff['AvgCost'] = round(df_stocks_diff['Investment']/df_stocks_diff['Shares'],2)
  df_stocks = pd.merge(df_stocks_diff, df_stocks_common, on='Symbol')
  return df_stocks

# plot fact distribution across dimension
def plot_pie_chart(df, dimension, fact):
  # grouping the data by category and calculating the sum of fact for each type
  grouped_data = df.groupby(dimension)[fact].sum()

  # sorting the grouped data in descending order
  grouped_data = grouped_data.sort_values(ascending=False)

  # creating a pie chart
  grouped_data.plot.pie(autopct='%1.1f%%', startangle=90, figsize=(6, 6))

  # adding a title and displaying the plot
  plt.title(f'{dimension} {fact} Distribution')
  plt.ylabel('')  # To hide the y-label
  plt.show()

In [7]:
# function to get portfolio features

def get_portfolio_features(df_common_features):

  print_date_time()
  print('-------------------')

  #df_common_features["Target"] = df_common_features["Target"].fillna(df_common_features["Max"])
  df_common_features['NTT'] = np.where(df_common_features['Strategy']== 'NTT', df_common_features["Target"], df_common_features['Max'])
  df_common_features['LTT'] = np.where(df_common_features['Strategy']== 'BTT', df_common_features["Target"], df_common_features['Max'])
  df_common_features['BOL'] = df_common_features['Min']

  tmp_df = df_common_features[df_common_features['Symbol'].isin(mypf_df[mypf_df['InPortfolio'] != 'NA'].Symbol.values)]
  print('qualified stocks: '+str(len(tmp_df['Symbol'].unique())))
  tmp_df1 = tmp_df[tmp_df['LatestQtr'] == 1]
  print('with latest results: '+str(len(tmp_df1['Symbol'].unique())))
  tmp_df1 = tmp_df1[tmp_df1['StarStock'] == 1]
  print('still star stocks: '+str(len(tmp_df1['Symbol'].unique())))
  tmp_df['Investment'] = tmp_df['AvgCost'] * tmp_df['Shares']
  tmp_df['Current'] = round(tmp_df['Close'] * tmp_df['Shares'],0)
  tmp_df['Previous'] = tmp_df['Prev_Close'] * tmp_df['Shares']
  tmp_df['EstimatedST'] = tmp_df['NTT'] * tmp_df['Shares']
  tmp_df['EstimatedLT'] = tmp_df['LTT'] * tmp_df['Shares']
  tmp_df['Current P/L'] = round((tmp_df['Current'] - tmp_df['Investment']),0)
  tmp_df['Today P/L%'] = round((tmp_df['Current'] - tmp_df['Previous'])*100/tmp_df['Previous'],2)
  tmp_df['Current P/L%'] = round((tmp_df['Current'] - tmp_df['Investment'])*100/tmp_df['Investment'],2)
  tmp_df['EstimatedST P/L%'] = round((tmp_df['EstimatedST'] - tmp_df['Investment'])*100/tmp_df['Investment'],2)
  tmp_df['EstimatedLT P/L%'] = round((tmp_df['EstimatedLT'] - tmp_df['Investment'])*100/tmp_df['Investment'],2)
  tmp_df['NTT%'] = round((tmp_df['NTT'] - tmp_df['Close'])*100/tmp_df['Close'],2)
  tmp_df['LTT%'] = round((tmp_df['LTT'] - tmp_df['Close'])*100/tmp_df['Close'],2)
  tmp_df['Gained%'] = round((tmp_df['Close'] - tmp_df['BOL'])*100/tmp_df['BOL'],2)
  investment = round(sum(tmp_df['AvgCost']*tmp_df['Shares']),0)
  current = round(sum(tmp_df['Close']*tmp_df['Shares']),0)
  tmp_df['InitAlloc%'] = round(tmp_df['Investment']*100/investment,2)
  tmp_df['CurrAlloc%'] = round(tmp_df['Current']*100/current,2)
  tmp_df['FTT'] = tmp_df['LTT']
  tmp_df.loc[tmp_df['Strategy'] == 'NTT', 'FTT'] = tmp_df['NTT']
  tmp_df['FTT%'] = tmp_df['LTT%']
  tmp_df.loc[tmp_df['Strategy'] == 'NTT', 'FTT%'] = tmp_df['NTT%']
  tmp_df['FTT Amt'] = round(tmp_df['FTT%'] * tmp_df['Current']/100,0)
  tmp_df['OTT%'] = round((tmp_df['FTT'] - tmp_df['AvgCost'])*100/tmp_df['AvgCost'],2)
  tmp_df['RRR Ind'] = round(tmp_df['Current P/L']/tmp_df['FTT Amt'],2)
  tmp_df['Risk Ind'] = round(tmp_df['Current P/L%']*tmp_df['CurrAlloc%'],0)

  return tmp_df

# function to print portfolio features
def print_portfolio_stats(df_portfolio_features, myinvmt_df):
  from pyxirr import xirr

  total_booked_amt, reserve_amt, cy_booked_amt, py_booked_amt = get_amt()

  dates = myinvmt_df['Date'].values
  dates = np.append(dates, datetime.date.today().strftime('%d-%b-%y'))
  investment = myinvmt_df['Investment'].values
  dates= pd.to_datetime(dates)

  current = round(sum(df_portfolio_features['Close']*df_portfolio_features['Shares']),0) + reserve_amt
  investment_xirr = np.append(investment, current)
  cagr = round(xirr(pd.DataFrame({"dates": dates, "amounts": investment_xirr}))*100,2)

  investment = -sum(investment)
  invested = round(sum(df_portfolio_features['AvgCost']*df_portfolio_features['Shares']),0) + reserve_amt
  previous = round(sum(df_portfolio_features['Prev_Close']*df_portfolio_features['Shares']),0) + reserve_amt
  cy_invested = investment + py_booked_amt

  today_pnl_amount = current-previous
  today_pnl_percentage = round((current-previous)*100/previous,2)

  curr_pnl_amount = current-invested
  curr_pnl_percentage = round((curr_pnl_amount)*100/(cy_invested),2)

  cy_pnl_amount = cy_booked_amt + curr_pnl_amount
  cy_pnl_percentage = round((cy_pnl_amount)*100/cy_invested,2)

  overall_pnl_amount = total_booked_amt + curr_pnl_amount
  overall_pnl_percentage = round((overall_pnl_amount)*100/investment,2)

  estimate_st = round(sum(df_portfolio_features['FTT']*df_portfolio_features['Shares']),0)  + reserve_amt
  est_st_pnl_amount = estimate_st-current
  est_st_pnl_percentage = round((est_st_pnl_amount)*100/current,2)

  estimate_lt = round(sum(df_portfolio_features['LTT']*df_portfolio_features['Shares']),0)  + reserve_amt
  est_lt_pnl_amount = estimate_lt-current
  est_lt_pnl_percentage = round((est_lt_pnl_amount)*100/current,2)

  total_profit = round(sum(df_portfolio_features[df_portfolio_features['Current P/L%'] > 0]['Current']) - sum(df_portfolio_features[df_portfolio_features['Current P/L%'] > 0]['Investment']),0)
  total_loss = round(sum(df_portfolio_features[df_portfolio_features['Current P/L%'] < 0]['Current']) - sum(df_portfolio_features[df_portfolio_features['Current P/L%'] < 0]['Investment']),0)

  cy_booked_percentage = round((cy_booked_amt)*100/current,2)
  py_booked_percentage = round((py_booked_amt)*100/investment,2)
  total_booked_percentage = round((total_booked_amt)*100/investment,2)

  print('-------------------')
  print('Initial Investment: ', format_amt(investment))
  print('CY Investment: ', format_amt(cy_invested))
  print('Reserve: ', format_amt(reserve_amt))
  print('Current: ',  format_amt(current))
  print('-------------------')
  print('Today PnL: '+ '{} ({}%)'.format(format_amt(today_pnl_amount), today_pnl_percentage))
  print('Current PnL: '+ '{} ({}%)'.format(format_amt(curr_pnl_amount), curr_pnl_percentage))
  print('CY Booked + Current PnL: '+ '{} ({}%)'.format(format_amt(cy_pnl_amount), cy_pnl_percentage))
  print('-------------------')
  print('Total profit: ', format_amt(total_profit))
  print('Total loss: ', format_amt(total_loss))
  print('-------------------')
  print('Total Booked + Current PnL: '+ '{} ({}%)'.format(format_amt(overall_pnl_amount), overall_pnl_percentage))
  print('Total Booked PnL: '+ '{} ({}%)'.format(format_amt(total_booked_amt), total_booked_percentage))
  print('Curr Year Booked PnL: '+ '{} ({}%)'.format(format_amt(cy_booked_amt), cy_booked_percentage))
  print('Prev Year Booked PnL: '+ '{} ({}%)'.format(format_amt(py_booked_amt), py_booked_percentage))
  print('===================')
  print('Est FTT: ',  format_amt(estimate_st))
  print('Est FTT PnL: '+ '{} ({}%)'.format(format_amt(est_st_pnl_amount), est_st_pnl_percentage))

  print('===================')
  print('Deployed: ', format_amt(investment))

  print('Current: ', format_amt(current))

  print('CAGR/XIRR %: '+'{}%'.format(cagr))

In [8]:
# get start and end date
start_date, end_date = get_start_end_date()

# get portfolio and prospects data
mypfs_df = get_mypfs_df()
mypps_df = get_mypps_df()
myinvmt_df = get_myinvmt_df()

# merge above datasets
mypf_df = pd.merge(mypfs_df, mypps_df, on="Symbol")

# seggregate dm and sv portfolio
dm_pf = mypf_df[mypf_df['InPortfolio'] == 'DM']
sv_pf = mypf_df[mypf_df['InPortfolio'] == 'SV']

# build portfolio stock dataframe
dm_stocks = get_stock_ids(dm_pf)
sv_stocks = get_stock_ids(sv_pf)
df_stocks = pd.concat([dm_pf,sv_pf], ignore_index = True)

# arrange common and diff stock features
common_cols = ['Symbol', 'Target', 'Criteria', 'Strategy', 'CumlRnk', 'LatestQtr', 'StarStock', 'Conviction', 'Category', 'InFolio', 'XIRR', 'MBQ']
diff_cols = ['Symbol', 'AvgCost', 'Shares']
df_stocks = arrange_features(df_stocks, common_cols, diff_cols)

# get common features
stock_ids = df_stocks['Symbol'].values
df_common_features = get_common_features(stock_ids, df_stocks)

df_common_features.reset_index(drop=True, inplace=True)
df_common_features.drop(['Date'], axis=1, inplace=True)
# get and print portfolio features
df_portfolio_features = get_portfolio_features(df_common_features)

print_portfolio_stats(df_portfolio_features, myinvmt_df)

df = df_portfolio_features
#plot_pie_chart(df, 'CapType', 'Current')
list_ox40n = list(df[df['MBQ'].str.contains('OX40N', na=False)]['Symbol'].values)

Run date time (IST): 2026-03-11 15:39:15
-------------------
qualified stocks: 86
with latest results: 26
still star stocks: 15
-------------------
Initial Investment:  1.36 C
CY Investment:  1.62 C
Reserve:  66.25 K
Current:  1.37 C
-------------------
Today PnL: -74.73 K (-0.54%)
Current PnL: -40.29 L (-24.79%)
CY Booked + Current PnL: -24.61 L (-15.14%)
-------------------
Total profit:  1.06 L
Total loss:  -41.34 L
-------------------
Total Booked + Current PnL: 2.37 L (1.75%)
Total Booked PnL: 42.66 L (31.48%)
Curr Year Booked PnL: 15.68 L (11.48%)
Prev Year Booked PnL: 26.98 L (19.91%)
===================
Est FTT:  2.47 C
Est FTT PnL: 1.11 C (80.98%)
===================
Deployed:  1.36 C
Current:  1.37 C
CAGR/XIRR %: 0.42%

In [9]:
# top 5 near their targets
cols = ['Symbol', 'Today P/L%', 'Current P/L%', 'FTT%', 'OTT%', 'FTT Amt', 'Current P/L', 'Current', 'FTT', 'Dev%_PE', 'RSI_14','Conviction', 'Spread%',  'CumlRnk', 'RRR Ind', 'CurrAlloc%', 'Gained%', 'Criteria', 'Strategy', 'Category']
df_tmp = df_portfolio_features[~df_portfolio_features['Symbol'].isin(['ENRIN','BLUSPRING','DIGITIDE'])]
df_tmp = df_tmp.sort_values(by = 'FTT Amt', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
19,COALINDIA,0.72,9.86,7.11,17.67,11753.0,14838.0,165298.0,478.51,31.99,61.0,L-LC,11.52,185.0,1.26,1.22,28.37,XY25,ATH,MINING
50,MASFIN,-1.92,-7.10,30.86,21.57,28089.0,-6960.0,91020.0,397.04,-20.05,39.0,H-SC,4.58,167.0,-0.25,0.67,27.00,XR,ATH,FINANCE
77,TTKPRESTIG,10.52,-30.40,43.80,0.09,30723.0,-30633.0,70144.0,770.00,62.86,51.0,M-SC,15.16,250.0,-1.00,0.52,18.51,OX40N,NTT,DURABLES
37,ICICIGI,-0.75,-0.67,20.14,19.34,40032.0,-1338.0,198771.0,2252.93,-16.40,45.0,X-MC,1.67,66.0,-0.03,1.46,13.37,X40,ATH,INSURANCE
78,UNITDSPR,-1.78,1.53,18.95,20.77,45048.0,3577.0,237721.0,1644.00,-10.02,50.0,X-MC,1.50,64.0,0.08,1.75,8.34,X40N,NTT,BREWERIES

In [10]:
# top 5 today
df_tmp = df_portfolio_features.sort_values(by = 'Today P/L%', ascending=False)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
77,TTKPRESTIG,10.52,-30.40,43.80,0.09,30723.0,-30633.0,70144.0,770.00,62.86,51.0,M-SC,15.16,250.0,-1.00,0.52,18.51,OX40N,NTT,DURABLES
55,RAJESHEXPO,4.93,-77.87,352.13,0.07,106910.0,-106816.0,30361.0,518.00,1012.37,23.0,L-SC,18.85,268.0,-1.00,0.22,4.93,OX40N,NTT,JEWELLERY
70,SYMPHONY,3.56,-37.14,59.05,-0.03,63521.0,-63570.0,107571.0,1306.00,-49.50,47.0,M-SC,13.24,205.0,-1.00,0.79,8.78,OX40N,NTT,DURABLES
31,HAPPSTMNDS,2.81,-48.60,259.66,84.85,171043.0,-62293.0,65872.0,1480.71,-38.81,63.0,H-SC,28.65,152.0,-0.36,0.48,21.99,AR,ATH,IT
54,QUESS,2.00,-20.79,119.53,73.90,101116.0,-22198.0,84595.0,424.00,-57.58,44.0,X-SC,17.93,80.0,-0.22,0.62,4.35,XY24,NTT,MISC

In [11]:
# bottom 5 today
df_tmp = df_portfolio_features.sort_values(by = 'Today P/L%', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
21,COLPAL,-6.49,-21.95,81.30,41.51,167120.0,-57805.0,205560.0,3726.84,-5.63,37.0,X-MC,4.18,62.0,-0.35,1.51,0.44,XY25,ATH,FMCG
27,FINCABLES,-4.43,12.45,84.89,107.91,140941.0,18384.0,166028.0,1641.55,0.96,55.0,M-SC,7.67,220.0,0.13,1.22,24.91,OX40N,ATH,CABLES
20,COFFEEDAY,-3.04,-56.26,209.24,35.27,103930.0,-63879.0,49670.0,80.00,-65.79,26.0,L-SC,18.07,266.0,-0.61,0.37,10.89,XR,NTT,HOTELS
5,ANGELONE,-3.01,-10.44,38.65,24.18,105577.0,-31838.0,273162.0,303.00,-86.88,33.0,X-SC,4.76,97.0,-0.30,2.01,14.40,X40N,NTT,FINANCE
75,TMPV,-2.85,-23.66,78.92,36.58,214374.0,-84207.0,271634.0,600.00,-83.62,36.0,X-LC,1.87,4.0,-0.39,2.00,1.01,XY24,NTT,AUTO

In [12]:
# top 5 to exit based on CumlRnk
df_tmp = df_portfolio_features[~df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])]
df_tmp = df_tmp[(df_tmp['Current P/L%'] > -1) & (df_tmp['Current P/L%'] < 1)].sort_values(by = 'CumlRnk', ascending=False)
df_tmp[cols].head()

Empty DataFrame
Columns: [Symbol, Today P/L%, Current P/L%, FTT%, OTT%, FTT Amt, Current P/L, Current, FTT, Dev%_PE, RSI_14, Conviction, Spread%, CumlRnk, RRR Ind, CurrAlloc%, Gained%, Criteria, Strategy, Category]
Index: []

In [13]:
# OX40N stocks to exit
df_tmp = df_portfolio_features[(df_portfolio_features['Symbol'].isin(list_ox40n))].sort_values(by = 'Current P/L%', ascending=False)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
27,FINCABLES,-4.43,12.45,84.89,107.91,140941.0,18384.0,166028.0,1641.55,0.96,55.0,M-SC,7.67,220.0,0.13,1.22,24.91,OX40N,ATH,CABLES
77,TTKPRESTIG,10.52,-30.40,43.80,0.09,30723.0,-30633.0,70144.0,770.00,62.86,51.0,M-SC,15.16,250.0,-1.00,0.52,18.51,OX40N,NTT,DURABLES
66,SIS,0.41,-33.05,81.13,21.26,60306.0,-36700.0,74332.0,528.00,1741.97,37.0,H-SC,10.02,168.0,-0.61,0.55,2.47,OX40N,NTT,MISC
70,SYMPHONY,3.56,-37.14,59.05,-0.03,63521.0,-63570.0,107571.0,1306.00,-49.50,47.0,M-SC,13.24,205.0,-1.00,0.79,8.78,OX40N,NTT,DURABLES
72,TATAELXSI,-0.30,-37.40,110.92,32.03,91537.0,-49310.0,82525.0,9161.00,-21.71,29.0,H-SC,16.58,158.0,-0.54,0.61,0.92,OX40N,NTT,IT

In [14]:
# top 5 to book for rotation
df_tmp = df_portfolio_features[(df_portfolio_features['Current P/L%'] > 20) ].sort_values(by = 'CumlRnk', ascending=False)
df_tmp[cols].head()

Empty DataFrame
Columns: [Symbol, Today P/L%, Current P/L%, FTT%, OTT%, FTT Amt, Current P/L, Current, FTT, Dev%_PE, RSI_14, Conviction, Spread%, CumlRnk, RRR Ind, CurrAlloc%, Gained%, Criteria, Strategy, Category]
Index: []

In [15]:
# top 5 to monitor for exit
df_tmp = df_portfolio_features[~df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])]
df_tmp = df_tmp[(df_tmp['Current P/L%'] > 0) ].sort_values(by = 'Dev%_PE', ascending=False)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
19,COALINDIA,0.72,9.86,7.11,17.67,11753.0,14838.0,165298.0,478.51,31.99,61.0,L-LC,11.52,185.0,1.26,1.22,28.37,XY25,ATH,MINING
27,FINCABLES,-4.43,12.45,84.89,107.91,140941.0,18384.0,166028.0,1641.55,0.96,55.0,M-SC,7.67,220.0,0.13,1.22,24.91,OX40N,ATH,CABLES
1,ABB,0.89,15.22,26.34,45.57,79399.0,39821.0,301440.0,7934.00,-26.00,66.0,H-MC,10.08,125.0,0.50,2.22,33.86,AR,NTT,ELECTRICAL

In [16]:
# top 5 to book for rotation from weak conviction
df_tmp = df_portfolio_features[~df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])]
df_tmp = df_tmp[~df_tmp['Criteria'].isin(['XY25','XY24','X40', 'X40N'])].sort_values(by = 'RRR Ind', ascending=False)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
1,ABB,0.89,15.22,26.34,45.57,79399.0,39821.0,301440.0,7934.00,-26.00,66.0,H-MC,10.08,125.0,0.50,2.22,33.86,AR,NTT,ELECTRICAL
27,FINCABLES,-4.43,12.45,84.89,107.91,140941.0,18384.0,166028.0,1641.55,0.96,55.0,M-SC,7.67,220.0,0.13,1.22,24.91,OX40N,ATH,CABLES
40,INDIAMART,-2.26,-8.45,125.81,106.72,142053.0,-10425.0,112911.0,4810.62,-58.79,44.0,H-SC,9.20,140.0,-0.07,0.83,12.95,AR,ATH,MISC
85,ZYDUSLIFE,-0.15,-2.80,39.54,35.63,80546.0,-5867.0,203707.0,1286.17,-15.32,55.0,H-MC,5.05,120.0,-0.07,1.50,13.41,AR,ATH,PHARMA
84,WIPRO,0.65,-17.05,107.68,72.27,151344.0,-28898.0,140550.0,420.00,-25.02,35.0,M-LC,14.48,98.0,-0.19,1.03,3.50,XR,NTT,IT

In [17]:
# top 5 to accumulate based on lowest RSI_14
df_tmp = df_portfolio_features[df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])].sort_values(by = 'RSI_14', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
58,RELAXO,-1.07,-60.54,286.02,52.31,163815.0,-87886.0,57274.0,1176.00,-57.99,19.0,X-SC,18.74,92.0,-0.54,0.42,0.00,X40N,NTT,FOOTWEAR
12,BATAINDIA,0.25,-53.64,191.64,35.20,114317.0,-69018.0,59652.0,2096.00,-21.73,21.0,X-SC,25.48,91.0,-0.60,0.44,0.25,X40,NTT,FOOTWEAR
73,TCS,-1.92,-27.64,74.92,26.57,251151.0,-128047.0,335226.0,4311.59,-38.71,21.0,X-LC,13.82,2.0,-0.51,2.47,0.00,X40,ATH,IT
8,AWL,0.22,-38.22,170.35,67.02,374981.0,-136185.0,220124.0,485.00,-66.76,22.0,X-SC,22.72,81.0,-0.36,1.62,2.16,XY24,NTT,FMCG
3,ACC,-1.19,-34.82,168.20,74.81,293960.0,-93360.0,174768.0,3906.00,-53.87,23.0,X-SC,12.22,85.0,-0.32,1.29,0.41,XY24,BTT,CEMENT

In [18]:
# top 5 to accumulate based on Spread and CumlRnk
df_tmp = df_portfolio_features[df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])]
df_tmp = df_tmp[(df_tmp['CumlRnk'] < 100)].sort_values(by = 'Spread%', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
22,DABUR,-1.88,-7.75,55.77,43.70,127628.0,-19221.0,228847.0,735.00,-16.33,34.0,X-MC,1.04,70.0,-0.15,1.68,6.14,XY24,BTT,FMCG
78,UNITDSPR,-1.78,1.53,18.95,20.77,45048.0,3577.0,237721.0,1644.00,-10.02,50.0,X-MC,1.50,64.0,0.08,1.75,8.34,X40N,NTT,BREWERIES
37,ICICIGI,-0.75,-0.67,20.14,19.34,40032.0,-1338.0,198771.0,2252.93,-16.40,45.0,X-MC,1.67,66.0,-0.03,1.46,13.37,X40,ATH,INSURANCE
75,TMPV,-2.85,-23.66,78.92,36.58,214374.0,-84207.0,271634.0,600.00,-83.62,36.0,X-LC,1.87,4.0,-0.39,2.00,1.01,XY24,NTT,AUTO
59,RELIANCE,-1.32,-10.76,40.41,25.30,72470.0,-21627.0,179336.0,1952.00,-13.11,45.0,X-LC,2.47,21.0,-0.30,1.32,19.74,XY25,BTT,REFINERIES

In [19]:
# top 5 to accumulate based on lowest Gained%
df_tmp = df_portfolio_features[df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])].sort_values(by = 'Gained%', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
10,BAJAJHLDNG,-1.09,-9.00,42.00,29.22,72664.0,-17116.0,173009.0,14451.52,-15.85,30.0,X-LC,11.99,28.0,-0.24,1.27,0.00,X40,ATH,FINANCE
13,BERGEPAINT,-1.39,-20.64,57.90,25.32,118440.0,-53190.0,204559.0,680.00,-25.02,28.0,X-MC,15.49,68.0,-0.45,1.50,0.00,XY24,NTT,PAINTS
58,RELAXO,-1.07,-60.54,286.02,52.31,163815.0,-87886.0,57274.0,1176.00,-57.99,19.0,X-SC,18.74,92.0,-0.54,0.42,0.00,X40N,NTT,FOOTWEAR
73,TCS,-1.92,-27.64,74.92,26.57,251151.0,-128047.0,335226.0,4311.59,-38.71,21.0,X-LC,13.82,2.0,-0.51,2.47,0.00,X40,ATH,IT
43,INFY,-1.49,-13.12,54.51,34.24,148187.0,-41036.0,271852.0,1972.00,-31.79,26.0,X-LC,12.13,3.0,-0.28,2.00,0.06,X40,NTT,IT

In [20]:
# top 5 to accumulate based on lowest CurrAlloc%
df_tmp = df_portfolio_features[df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])].sort_values(by = 'CurrAlloc%', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
58,RELAXO,-1.07,-60.54,286.02,52.31,163815.0,-87886.0,57274.0,1176.00,-57.99,19.0,X-SC,18.74,92.0,-0.54,0.42,0.00,X40N,NTT,FOOTWEAR
12,BATAINDIA,0.25,-53.64,191.64,35.20,114317.0,-69018.0,59652.0,2096.00,-21.73,21.0,X-SC,25.48,91.0,-0.60,0.44,0.25,X40,NTT,FOOTWEAR
54,QUESS,2.00,-20.79,119.53,73.90,101116.0,-22198.0,84595.0,424.00,-57.58,44.0,X-SC,17.93,80.0,-0.22,0.62,4.35,XY24,NTT,MISC
36,HONAUT,-0.37,-20.53,90.40,51.31,138538.0,-39588.0,153250.0,58357.33,-33.97,43.0,X-SC,13.64,90.0,-0.29,1.13,3.20,X40N,ATH,ELECTRICAL
2,ABBOTINDIA,1.45,-8.75,29.39,18.07,47964.0,-15655.0,163200.0,35195.00,-22.40,52.0,X-MC,11.12,58.0,-0.33,1.20,3.46,X40,ATH,PHARMA

In [21]:
# top 5 to accumulate based on CumlRnk
df_tmp = df_portfolio_features.sort_values(by = 'CumlRnk', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
45,ITC,-0.02,-18.61,46.28,19.06,128133.0,-63302.0,276864.0,452.00,-55.52,38.0,X-LC,17.09,1.0,-0.49,2.04,0.98,X40,NTT,FMCG
73,TCS,-1.92,-27.64,74.92,26.57,251151.0,-128047.0,335226.0,4311.59,-38.71,21.0,X-LC,13.82,2.0,-0.51,2.47,0.00,X40,ATH,IT
43,INFY,-1.49,-13.12,54.51,34.24,148187.0,-41036.0,271852.0,1972.00,-31.79,26.0,X-LC,12.13,3.0,-0.28,2.00,0.06,X40,NTT,IT
75,TMPV,-2.85,-23.66,78.92,36.58,214374.0,-84207.0,271634.0,600.00,-83.62,36.0,X-LC,1.87,4.0,-0.39,2.00,1.01,XY24,NTT,AUTO
34,HCLTECH,-0.82,-12.37,41.32,23.83,87597.0,-29927.0,211997.0,1908.19,-7.78,27.0,X-LC,9.49,8.0,-0.34,1.56,1.71,X40,ATH,IT

In [22]:
# top 5 for average up
df_tmp = df_portfolio_features[(df_portfolio_features['Dev%_200'] > 5)].sort_values(by = 'CurrAlloc%', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
42,INDUSINDBK,-2.40,-35.24,105.21,32.89,52603.0,-27208.0,49998.0,1800.00,-335.29,38.0,L-MC,11.28,258.0,-0.52,0.37,37.69,XR,NTT,BANKS
67,SONACOMS,0.90,-10.67,55.71,39.09,50340.0,-10798.0,90361.0,804.02,-29.25,50.0,M-MC,10.13,193.0,-0.21,0.66,27.83,AR,ATH,AUTO
27,FINCABLES,-4.43,12.45,84.89,107.91,140941.0,18384.0,166028.0,1641.55,0.96,55.0,M-SC,7.67,220.0,0.13,1.22,24.91,OX40N,ATH,CABLES
19,COALINDIA,0.72,9.86,7.11,17.67,11753.0,14838.0,165298.0,478.51,31.99,61.0,L-LC,11.52,185.0,1.26,1.22,28.37,XY25,ATH,MINING
82,VOLTAS,1.55,15.11,26.14,45.20,57694.0,28968.0,220710.0,1856.00,31.84,49.0,X-MC,9.64,79.0,0.50,1.62,22.93,XY25,NTT,AC

In [23]:
# top 5 RSP
df_tmp = df_portfolio_features.sort_values(by = 'RSP', ascending=False)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
27,FINCABLES,-4.43,12.45,84.89,107.91,140941.0,18384.0,166028.0,1641.55,0.96,55.0,M-SC,7.67,220.0,0.13,1.22,24.91,OX40N,ATH,CABLES
11,BANDHANBNK,0.12,-12.22,119.21,92.42,291480.0,-34049.0,244510.0,400.00,109.77,61.0,H-SC,10.03,174.0,-0.12,1.80,34.69,XY24,NTT,BANKS
1,ABB,0.89,15.22,26.34,45.57,79399.0,39821.0,301440.0,7934.00,-26.00,66.0,H-MC,10.08,125.0,0.50,2.22,33.86,AR,NTT,ELECTRICAL
19,COALINDIA,0.72,9.86,7.11,17.67,11753.0,14838.0,165298.0,478.51,31.99,61.0,L-LC,11.52,185.0,1.26,1.22,28.37,XY25,ATH,MINING
26,EASEMYTRIP,-0.00,-59.44,259.18,45.70,185886.0,-105094.0,71721.0,26.40,-25.60,44.0,M-SC,18.18,204.0,-0.57,0.53,18.17,XY24,NTT,TRAVEL

In [24]:
# Top N allocation
df_tmp = df_portfolio_features.sort_values(by = 'CurrAlloc%', ascending=False)
top_n_values = [10, 25, 50]

sum_df = pd.DataFrame({
    'Top_N': top_n_values,
    'Sum_Alloc%': [df_tmp['CurrAlloc%'].head(n).sum() for n in top_n_values]
})

sum_df

   Top_N  Sum_Alloc%
0     10       20.49
1     25       45.34
2     50       77.77

In [25]:
# market-cap-wise allocation
df_tmp = df_portfolio_features[cols]
df_tmp.groupby(df_tmp['Conviction'].str[-2:])['CurrAlloc%'].sum().sort_values(ascending=False)

Conviction
SC    44.72
MC    30.43
LC    24.87
Name: CurrAlloc%, dtype: float64

In [26]:
# criteria-wise allocation
df_portfolio_features.groupby('Criteria')['CurrAlloc%'].sum().sort_values(ascending=False)

Criteria
XY24     27.31
X40      23.78
X40N     15.13
AR        9.19
XY25      8.61
XR        8.30
OX40N     6.92
SR        0.78
Name: CurrAlloc%, dtype: float64

In [27]:
# conviction-wise allocation
df_portfolio_features.groupby('Conviction')['CurrAlloc%'].sum().sort_values(ascending=False)

Conviction
X-MC    23.05
H-SC    21.77
X-LC    21.42
X-SC    12.15
M-SC    10.21
H-MC     5.00
M-MC     2.01
L-LC     1.22
H-LC     1.20
M-LC     1.03
L-SC     0.59
L-MC     0.37
Name: CurrAlloc%, dtype: float64

In [28]:
# sector-wise stats
df_tmp = df_portfolio_features.groupby('Category')[['CurrAlloc%', 'Current', 'Current P/L', 'FTT Amt']].sum().sort_values(by=['Current', 'Current P/L'], ascending=False)
df_tmp['Current P/L%'] = round(df_tmp['Current P/L'] * 100 / df_tmp['Current'], 2)
df_tmp['FTT%'] = round(df_tmp['FTT Amt'] * 100 / df_tmp['Current'], 2)
cols = ['CurrAlloc%', 'Current P/L%', 'FTT%']
df_tmp[cols].sort_values(by=['CurrAlloc%'], ascending=False)

               CurrAlloc%  Current P/L%    FTT%
Category
FMCG                15.24        -20.54   63.34
FINANCE             12.81        -23.39   73.67
IT                  11.70        -41.67  113.76
MISC                 7.01        -40.78  101.93
ELECTRICAL           6.66         -7.01   47.99
PAINTS               5.16        -40.24   64.60
INSURANCE            4.71         -5.66   41.82
PHARMA               4.16         -3.88   36.57
AUTO                 3.74        -28.61   79.64
BANKS                3.18        -24.03   99.18
AC                   2.16         -8.52   37.95
HEALTHCARE           1.97        -33.40   68.21
DURABLES             1.91        -48.89   85.12
FOOTWEAR             1.86        -74.90  145.03
TRAVEL               1.81        -81.95  173.05
BREWERIES            1.75          1.50   18.95
APPARELS             1.63        -21.35   62.74
REALTY               1.44        -13.17   31.77
CERAMICS             1.35        -67.57  118.47
REFINERIES           1.32        -12.06   40.41
CEMENT               1.29        -53.42  168.20
CABLES               1.22         11.07   84.89
MINING               1.22          8.98    7.11
JEWELLERY            1.12       -110.04  183.01
ENGINEERING          1.10        -61.93  135.99
CHEMICALS            0.96       -103.33  269.22
ENTERTAINMENT        0.75        -87.21  198.86
TEXTILES             0.42        -61.69  107.79
HOTELS               0.37       -128.61  209.24

In [29]:
# money to be made criteria-wise
df_portfolio_features.groupby('Criteria')['FTT Amt'].agg(['sum', 'count']).sort_values(by='sum', ascending=False)

                sum  count
Criteria
XY24      3885285.0     21
X40       1639832.0     15
XR        1364613.0     12
AR        1320000.0     10
X40N      1242137.0     10
OX40N      851626.0     10
XY25       447213.0      6
SR         313783.0      2

In [30]:
# money to be made conviction-wise
df_portfolio_features.groupby('Conviction')['FTT Amt'].agg(['sum', 'count']).sort_values(by='sum', ascending=False)

                  sum  count
Conviction
H-SC        3835458.0     24
X-MC        1597079.0     15
X-LC        1562895.0     12
X-SC        1530758.0     10
M-SC        1529843.0     14
H-MC         399500.0      3
L-SC         210840.0      2
M-LC         151344.0      1
M-MC         112456.0      2
H-LC          69960.0      1
L-MC          52603.0      1
L-LC          11753.0      1

In [31]:
# money to be made criteria and conviction-wise
df_portfolio_features.groupby(['Conviction', 'Criteria'])['FTT Amt'].agg(['sum', 'count']).sort_values(by='sum', ascending=False)

                           sum  count
Conviction Criteria
H-SC       XY24      1307680.0      6
           AR         962589.0      5
M-SC       XY24       902631.0      6
H-SC       XR         868409.0      7
X-SC       XY24       828156.0      4
X-LC       X40        813015.0      6
X-MC       X40        622497.0      7
           X40N       503700.0      4
X-SC       X40N       498282.0      4
H-SC       OX40N      382997.0      4
M-SC       OX40N      361719.0      5
X-LC       XY24       361195.0      2
H-SC       SR         313783.0      2
X-MC       XY24       246068.0      2
X-LC       X40N       240155.0      2
H-MC       XY24       239555.0      1
X-MC       XY25       224814.0      2
X-SC       X40        204320.0      2
M-SC       XR         188327.0      2
H-MC       AR         159945.0      2
M-LC       XR         151344.0      1
X-LC       XY25       148530.0      2
L-SC       OX40N      106910.0      1
           XR         103930.0      1
M-SC       AR          77166.0      1
H-LC       AR          69960.0      1
M-MC       XY25        62116.0      1
L-MC       XR          52603.0      1
M-MC       AR          50340.0      1
L-LC       XY25        11753.0      1

In [32]:
# notebook execution time

end_time = time.time()
execution_time = round(end_time - start_time, 0)
print(f"Notebook execution time: {execution_time} seconds")

Notebook execution time: 31.0 seconds