<a href="https://colab.research.google.com/github/ankit-rathi/Quantvesting_v2/blob/main/myStocks_Portfolio_Analysis.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
'''
!pip install pandas==2.2.2 -qq
!pip install pyxirr -qq
!pip install ta -qq
!pip install yfinance==0.2.59 -qq
'''

'\n!pip install pandas==2.2.2 -qq\n!pip install pyxirr -qq\n!pip install ta -qq\n!pip install yfinance==0.2.59 -qq\n'

In [2]:
# import libraries

import numpy as np
import pandas as pd
import datetime
import warnings
warnings.filterwarnings('ignore')
import yfinance as yfin
import ta
import matplotlib.pyplot as plt
import requests

In [3]:
# notebook start time
import time
import datetime
import pytz

start_time = time.time()

# function to print date timestamp
def print_date_time():
  tz_NY = pytz.timezone('Asia/Kolkata')
  datetime_NY = datetime.datetime.now(tz_NY)
  print("Run date time (IST):", datetime_NY.strftime("%Y-%m-%d %H:%M:%S"))

In [4]:
# function to get booked and reserved amount
def get_amt():
  # fetch the JSON data from the URL
  url = "https://raw.githubusercontent.com/ankit-rathi/Tradevesting_v1/main/data/myPortfolioAmts.json"
  response = requests.get(url)
  pf_amts = response.json()  # parse the JSON data

  # extract values from the JSON
  py_booked_amt_dm = pf_amts["py_booked_amt_dm"]
  py_booked_amt_sv = pf_amts["py_booked_amt_sv"]
  cy_booked_amt_dm = pf_amts["cy_booked_amt_dm"]
  cy_booked_amt_sv = pf_amts["cy_booked_amt_sv"]
  reserve_amt_dm = pf_amts["reserve_amt_dm"]
  reserve_amt_sv = pf_amts["reserve_amt_sv"]

  # perform calculations
  py_booked_amt = py_booked_amt_dm + py_booked_amt_sv
  cy_booked_amt = cy_booked_amt_dm + cy_booked_amt_sv
  reserve_amt = reserve_amt_dm + reserve_amt_sv
  total_booked_amt = py_booked_amt + cy_booked_amt

  return total_booked_amt, reserve_amt, cy_booked_amt, py_booked_amt

gen_output = 0

In [5]:
# function to format the amount
def format_amt(number):
    abs_number = abs(number)

    if abs_number >= 1_00_00_000:  # Crores
        formatted_amt = f"{number / 1_00_00_000:.2f} C"
    elif abs_number >= 1_00_000:  # Lakhs
        formatted_amt = f"{number / 1_00_000:.2f} L"
    elif abs_number >= 1_000:  # Thousands
        formatted_amt = f"{number / 1_000:.2f} K"
    else:
        formatted_amt = f"{number:.2f}"

    return formatted_amt

# function to set start and end date
def get_start_end_date():
  start_date = (datetime.date.today() + datetime.timedelta(days=-365)).strftime('%Y-%m-%d')
  end_date = (datetime.date.today() + datetime.timedelta(days=1)).strftime('%Y-%m-%d')
  return start_date, end_date

# function to fetch my portfolio csv
def get_mypfs_df():
  mypfs_df = pd.read_csv('https://raw.githubusercontent.com/ankit-rathi/Tradevesting_v1/main/data/myPortfolioStocks.csv')
  return mypfs_df

# function to fetch my prospects csv
def get_mypps_df():
  mypps_df = pd.read_csv('https://raw.githubusercontent.com/ankit-rathi/Tradevesting_v1/main/data/myProspectsScrips.csv')
  return mypps_df

# function to fetch screener data
def get_myscreen_df():
  myscreen_df = pd.read_csv('https://raw.githubusercontent.com/ankit-rathi/Tradevesting_v1/main/data/myScreenerDB.csv')
  return myscreen_df

# function to fetch momentum data
def get_myinvmt_df():
  myinvmt_df = pd.read_csv('https://raw.githubusercontent.com/ankit-rathi/Tradevesting_v1/main/data/myInvestments.csv')
  return myinvmt_df

# function to get the stock ids
def get_stock_ids(df_pf):
  stock_n100 = df_pf['Symbol'].unique()

  exclude = ['CADILAHC','MMTC', 'MASFIN']

  stock_ids = df_pf[~df_pf['Symbol'].isin(exclude) ]['Symbol'].unique()

  #mypf = mypf[mypf.Forecast.notnull()]
  #stock_ids = mypf['Symbol'].unique()

  #stock_ids.sort()
  return stock_ids

# get features from screener data
def get_screener_features():
  myscreen_df = get_myscreen_df()
  cols = ['Symbol', 'EPS', 'MedPE', 'ROCE%', 'ROE%', 'CapType']
  return myscreen_df[cols]

# get relative strength
def get_relative_strength(stock_list):

    # Dictionary to store stock tickers and their corresponding percentage price change
    stock_changes = {}

    # Loop through each stock and fetch its price data
    for stock in stock_list:
        try:
            # Download the stock data for the given date range
            stock_data = yfin.Ticker(stock + '.NS').history(period='1mo', interval='1d')[map(str.title, ['open', 'close', 'low', 'high', 'volume'])]

            # Calculate the percentage change for the stock
            if len(stock_data) > 0:
                start_price = stock_data['Close'].iloc[0]
                end_price = stock_data['Close'].iloc[-1]
                percent_change = round(((end_price - start_price) / start_price) * 100, 2)
                stock_changes[stock] = percent_change
            else:
                stock_changes[stock] = np.nan  # If no data is available, set to NaN

        except Exception as e:
            print(f"Error fetching data for {stock}: {e}")
            stock_changes[stock] = np.nan

    # Create a DataFrame with stock tickers and their percentage changes
    df = pd.DataFrame(list(stock_changes.items()), columns=['Symbol', 'Percent_Change'])

    # Drop any stocks with missing data (NaN values)
    df = df.dropna()

    # Calculate the percentile rank based on percentage change
    df['RSP'] = round(df['Percent_Change'].rank(pct=True) * 100, 2)
    cols = ['Symbol', 'RSP']
    df = df[cols]
    # Sort by percentile rank (optional)
    df = df.sort_values(by='RSP', ascending=False).reset_index(drop=True)

    return df

In [6]:
# function to get stock technicals
def stock_prec_dev(stock_symbol):
    #stock_symbol = 'ULTRACEMCO.NS'
    short_window = 20
    mid_window = 50
    long_window = 200
    moving_avg = 'SMA'

    start = datetime.datetime(*map(int, start_date.split('-')))
    end = datetime.datetime(*map(int, end_date.split('-')))

    stock_df = yfin.Ticker(stock_symbol + '.NS').history(period='max', interval='1d')[map(str.title, ['open', 'close', 'low', 'high', 'volume'])]

    stock_df['Max'] = round(max(stock_df['Close']),2)
    stock_df = stock_df[(stock_df.index <= end_date) & (stock_df.index >= start_date)]
    stock_df['200_SMA'] = round(stock_df['Close'].rolling(window = 200, min_periods = 1).mean(),0)
    stock_df['Dev%_200'] = round((stock_df['Close'] - stock_df['200_SMA'])*100/stock_df['200_SMA'],2)
    stock_df.dropna(axis = 0, inplace = True) # remove any null rows

    stock_df['20_SMA'] = stock_df['Close'].rolling(window=20).mean()
    stock_df['50_SMA'] = stock_df['Close'].rolling(window=50).mean()
    stock_df['Symbol'] = stock_symbol

    stock_df['Close'] = round(stock_df['Close'],2)
    stock_df['Min'] = round(min(stock_df['Close']),2)
    stock_df['RSI_14'] = ta.momentum.RSIIndicator(close=stock_df['Close'], window=14).rsi()
    stock_df['RSI_14'] = round(stock_df['RSI_14'],0)
    stock_df['Prev_Close'] = stock_df['Close'].shift(1)
    stock_df.drop(['Open', 'Low', 'High', 'Volume'], axis=1, inplace=True)
    stock_df = stock_df.tail(1)

    max_SMA = max(stock_df['20_SMA'].item(), stock_df['50_SMA'].item(), stock_df['200_SMA'].item())
    min_SMA = min(stock_df['20_SMA'].item(), stock_df['50_SMA'].item(), stock_df['200_SMA'].item())
    ABS_Spread = max_SMA - min_SMA
    stock_df['Spread%'] = round((ABS_Spread / stock_df['200_SMA'].item()) * 100,2)

    return stock_df

# function to compute stock attributes
def get_common_features(stock_ids, df_mypf):

  df_prec_dev = pd.DataFrame()
  df_tmp = get_screener_features()
  df_rs = get_relative_strength(stock_ids)

  for stock_id in stock_ids:
      tmp = stock_prec_dev(stock_id)
      tmp = tmp.reset_index()
      df_prec_dev = pd.concat([df_prec_dev, tmp], ignore_index = True)
  df_prec_dev = pd.merge(df_prec_dev, df_mypf, on= 'Symbol')
  df_prec_dev = pd.merge(df_prec_dev, df_tmp, on= 'Symbol', how='left')
  df_prec_dev = pd.merge(df_prec_dev, df_rs, on= 'Symbol', how='left')
  #print(df_prec_dev.columns)
  df_prec_dev['Curr_PE'] = round(df_prec_dev['Close']/df_prec_dev['EPS'],1)
  df_prec_dev['Dev%_PE'] = round((df_prec_dev['Curr_PE'] - df_prec_dev['MedPE'])*100/df_prec_dev['MedPE'],2)
  df_prec_dev['Conviction'] = df_prec_dev['Conviction'] + '-' + df_prec_dev['CapType']
  return df_prec_dev

# function to arrange stock features
def arrange_features(df_stocks, common_cols, diff_cols):
  df_stocks_common = df_stocks[common_cols].drop_duplicates()
  df_stocks_diff = df_stocks[diff_cols]
  df_stocks_diff['Investment'] = df_stocks_diff['AvgCost'] * df_stocks_diff['Shares']
  df_stocks_diff = df_stocks_diff.groupby(['Symbol'])[['Shares', 'Investment']].aggregate(['sum']).reset_index()
  df_stocks_diff.columns = ['Symbol', 'Shares', 'Investment']
  df_stocks_diff['AvgCost'] = round(df_stocks_diff['Investment']/df_stocks_diff['Shares'],2)
  df_stocks = pd.merge(df_stocks_diff, df_stocks_common, on='Symbol')
  return df_stocks

# plot fact distribution across dimension
def plot_pie_chart(df, dimension, fact):
  # grouping the data by category and calculating the sum of fact for each type
  grouped_data = df.groupby(dimension)[fact].sum()

  # sorting the grouped data in descending order
  grouped_data = grouped_data.sort_values(ascending=False)

  # creating a pie chart
  grouped_data.plot.pie(autopct='%1.1f%%', startangle=90, figsize=(6, 6))

  # adding a title and displaying the plot
  plt.title(f'{dimension} {fact} Distribution')
  plt.ylabel('')  # To hide the y-label
  plt.show()

In [7]:
# function to get portfolio features

def get_portfolio_features(df_common_features):

  print_date_time()
  print('-------------------')

  #df_common_features["Target"] = df_common_features["Target"].fillna(df_common_features["Max"])
  df_common_features['NTT'] = np.where(df_common_features['Strategy']== 'NTT', df_common_features["Target"], df_common_features['Max'])
  df_common_features['LTT'] = np.where(df_common_features['Strategy']== 'BTT', df_common_features["Target"], df_common_features['Max'])
  df_common_features['BOL'] = df_common_features['Min']

  tmp_df = df_common_features[df_common_features['Symbol'].isin(mypf_df[mypf_df['InPortfolio'] != 'NA'].Symbol.values)]
  print('qualified stocks: '+str(len(tmp_df['Symbol'].unique())))
  tmp_df1 = tmp_df[tmp_df['LatestQtr'] == 1]
  print('with latest results: '+str(len(tmp_df1['Symbol'].unique())))
  tmp_df1 = tmp_df1[tmp_df1['StarStock'] == 1]
  print('still star stocks: '+str(len(tmp_df1['Symbol'].unique())))
  tmp_df['Investment'] = tmp_df['AvgCost'] * tmp_df['Shares']
  tmp_df['Current'] = round(tmp_df['Close'] * tmp_df['Shares'],0)
  tmp_df['Previous'] = tmp_df['Prev_Close'] * tmp_df['Shares']
  tmp_df['EstimatedST'] = tmp_df['NTT'] * tmp_df['Shares']
  tmp_df['EstimatedLT'] = tmp_df['LTT'] * tmp_df['Shares']
  tmp_df['Current P/L'] = round((tmp_df['Current'] - tmp_df['Investment']),0)
  tmp_df['Today P/L%'] = round((tmp_df['Current'] - tmp_df['Previous'])*100/tmp_df['Previous'],2)
  tmp_df['Current P/L%'] = round((tmp_df['Current'] - tmp_df['Investment'])*100/tmp_df['Investment'],2)
  tmp_df['EstimatedST P/L%'] = round((tmp_df['EstimatedST'] - tmp_df['Investment'])*100/tmp_df['Investment'],2)
  tmp_df['EstimatedLT P/L%'] = round((tmp_df['EstimatedLT'] - tmp_df['Investment'])*100/tmp_df['Investment'],2)
  tmp_df['NTT%'] = round((tmp_df['NTT'] - tmp_df['Close'])*100/tmp_df['Close'],2)
  tmp_df['LTT%'] = round((tmp_df['LTT'] - tmp_df['Close'])*100/tmp_df['Close'],2)
  tmp_df['Gained%'] = round((tmp_df['Close'] - tmp_df['BOL'])*100/tmp_df['BOL'],2)
  investment = round(sum(tmp_df['AvgCost']*tmp_df['Shares']),0)
  current = round(sum(tmp_df['Close']*tmp_df['Shares']),0)
  tmp_df['InitAlloc%'] = round(tmp_df['Investment']*100/investment,2)
  tmp_df['CurrAlloc%'] = round(tmp_df['Current']*100/current,2)
  tmp_df['FTT'] = tmp_df['LTT']
  tmp_df.loc[tmp_df['Strategy'] == 'NTT', 'FTT'] = tmp_df['NTT']
  tmp_df['FTT%'] = tmp_df['LTT%']
  tmp_df.loc[tmp_df['Strategy'] == 'NTT', 'FTT%'] = tmp_df['NTT%']
  tmp_df['FTT Amt'] = round(tmp_df['FTT%'] * tmp_df['Current']/100,0)
  tmp_df['OTT%'] = round((tmp_df['FTT'] - tmp_df['AvgCost'])*100/tmp_df['AvgCost'],2)
  tmp_df['RRR Ind'] = round(tmp_df['Current P/L']/tmp_df['FTT Amt'],2)
  tmp_df['Risk Ind'] = round(tmp_df['Current P/L%']*tmp_df['CurrAlloc%'],0)

  return tmp_df

# function to print portfolio features
def print_portfolio_stats(df_portfolio_features, myinvmt_df):
  from pyxirr import xirr

  total_booked_amt, reserve_amt, cy_booked_amt, py_booked_amt = get_amt()

  dates = myinvmt_df['Date'].values
  dates = np.append(dates, datetime.date.today().strftime('%d-%b-%y'))
  investment = myinvmt_df['Investment'].values
  dates= pd.to_datetime(dates)

  current = round(sum(df_portfolio_features['Close']*df_portfolio_features['Shares']),0) + reserve_amt
  investment_xirr = np.append(investment, current)
  cagr = round(xirr(pd.DataFrame({"dates": dates, "amounts": investment_xirr}))*100,2)

  investment = -sum(investment)
  invested = round(sum(df_portfolio_features['AvgCost']*df_portfolio_features['Shares']),0) + reserve_amt
  previous = round(sum(df_portfolio_features['Prev_Close']*df_portfolio_features['Shares']),0) + reserve_amt
  cy_invested = investment + py_booked_amt

  today_pnl_amount = current-previous
  today_pnl_percentage = round((current-previous)*100/previous,2)

  curr_pnl_amount = current-invested
  curr_pnl_percentage = round((curr_pnl_amount)*100/(cy_invested),2)

  cy_pnl_amount = cy_booked_amt + curr_pnl_amount
  cy_pnl_percentage = round((cy_pnl_amount)*100/cy_invested,2)

  overall_pnl_amount = total_booked_amt + curr_pnl_amount
  overall_pnl_percentage = round((overall_pnl_amount)*100/investment,2)

  estimate_st = round(sum(df_portfolio_features['FTT']*df_portfolio_features['Shares']),0)  + reserve_amt
  est_st_pnl_amount = estimate_st-current
  est_st_pnl_percentage = round((est_st_pnl_amount)*100/current,2)

  estimate_lt = round(sum(df_portfolio_features['LTT']*df_portfolio_features['Shares']),0)  + reserve_amt
  est_lt_pnl_amount = estimate_lt-current
  est_lt_pnl_percentage = round((est_lt_pnl_amount)*100/current,2)

  total_profit = round(sum(df_portfolio_features[df_portfolio_features['Current P/L%'] > 0]['Current']) - sum(df_portfolio_features[df_portfolio_features['Current P/L%'] > 0]['Investment']),0)
  total_loss = round(sum(df_portfolio_features[df_portfolio_features['Current P/L%'] < 0]['Current']) - sum(df_portfolio_features[df_portfolio_features['Current P/L%'] < 0]['Investment']),0)

  cy_booked_percentage = round((cy_booked_amt)*100/current,2)
  py_booked_percentage = round((py_booked_amt)*100/investment,2)
  total_booked_percentage = round((total_booked_amt)*100/investment,2)

  print('-------------------')
  print('Initial Investment: ', format_amt(investment))
  print('CY Investment: ', format_amt(cy_invested))
  print('Reserve: ', format_amt(reserve_amt))
  print('Current: ',  format_amt(current))
  print('-------------------')
  print('Today PnL: '+ '{} ({}%)'.format(format_amt(today_pnl_amount), today_pnl_percentage))
  print('Current PnL: '+ '{} ({}%)'.format(format_amt(curr_pnl_amount), curr_pnl_percentage))
  print('CY Booked + Current PnL: '+ '{} ({}%)'.format(format_amt(cy_pnl_amount), cy_pnl_percentage))
  print('-------------------')
  print('Total profit: ', format_amt(total_profit))
  print('Total loss: ', format_amt(total_loss))
  print('-------------------')
  print('Total Booked + Current PnL: '+ '{} ({}%)'.format(format_amt(overall_pnl_amount), overall_pnl_percentage))
  print('Total Booked PnL: '+ '{} ({}%)'.format(format_amt(total_booked_amt), total_booked_percentage))
  print('Curr Year Booked PnL: '+ '{} ({}%)'.format(format_amt(cy_booked_amt), cy_booked_percentage))
  print('Prev Year Booked PnL: '+ '{} ({}%)'.format(format_amt(py_booked_amt), py_booked_percentage))
  print('===================')
  print('Est FTT: ',  format_amt(estimate_st))
  print('Est FTT PnL: '+ '{} ({}%)'.format(format_amt(est_st_pnl_amount), est_st_pnl_percentage))

  print('===================')
  print('Deployed: ', format_amt(investment))

  print('Current: ', format_amt(current))

  print('CAGR/XIRR %: '+'{}%'.format(cagr))

In [8]:
# get start and end date
start_date, end_date = get_start_end_date()

# get portfolio and prospects data
mypfs_df = get_mypfs_df()
mypps_df = get_mypps_df()
myinvmt_df = get_myinvmt_df()

# merge above datasets
mypf_df = pd.merge(mypfs_df, mypps_df, on="Symbol")

# seggregate dm and sv portfolio
dm_pf = mypf_df[mypf_df['InPortfolio'] == 'DM']
sv_pf = mypf_df[mypf_df['InPortfolio'] == 'SV']

# build portfolio stock dataframe
dm_stocks = get_stock_ids(dm_pf)
sv_stocks = get_stock_ids(sv_pf)
df_stocks = pd.concat([dm_pf,sv_pf], ignore_index = True)

# arrange common and diff stock features
common_cols = ['Symbol', 'Target', 'Criteria', 'Strategy', 'CumlRnk', 'LatestQtr', 'StarStock', 'Conviction', 'Category', 'InFolio', 'XIRR', 'MBQ']
diff_cols = ['Symbol', 'AvgCost', 'Shares']
df_stocks = arrange_features(df_stocks, common_cols, diff_cols)

# get common features
stock_ids = df_stocks['Symbol'].values
df_common_features = get_common_features(stock_ids, df_stocks)

df_common_features.reset_index(drop=True, inplace=True)
df_common_features.drop(['Date'], axis=1, inplace=True)
# get and print portfolio features
df_portfolio_features = get_portfolio_features(df_common_features)

print_portfolio_stats(df_portfolio_features, myinvmt_df)

df = df_portfolio_features
#plot_pie_chart(df, 'CapType', 'Current')
list_ox40n = list(df[df['MBQ'].str.contains('OX40N', na=False)]['Symbol'].values)

Run date time (IST): 2026-04-23 14:30:22
-------------------
qualified stocks: 90
with latest results: 28
still star stocks: 17
-------------------
Initial Investment:  1.38 C
CY Investment:  1.80 C
Reserve:  1.84 K
Current:  1.47 C
-------------------
Today PnL: -77.09 K (-0.52%)
Current PnL: -33.24 L (-18.43%)
CY Booked + Current PnL: -32.28 L (-17.9%)
-------------------
Total profit:  2.13 L
Total loss:  -35.37 L
-------------------
Total Booked + Current PnL: 10.59 L (7.7%)
Total Booked PnL: 43.83 L (31.88%)
Curr Year Booked PnL: 96.00 K (0.65%)
Prev Year Booked PnL: 42.87 L (31.18%)
===================
Est FTT:  2.52 C
Est FTT PnL: 1.05 C (71.78%)
===================
Deployed:  1.38 C
Current:  1.47 C
CAGR/XIRR %: 3.17%

In [9]:
# top 5 near their targets
cols = ['Symbol', 'Today P/L%', 'Current P/L%', 'FTT%', 'OTT%', 'FTT Amt', 'Current P/L', 'Current', 'FTT', 'Dev%_PE', 'RSI_14','Conviction', 'Spread%',  'CumlRnk', 'RRR Ind', 'CurrAlloc%', 'Gained%', 'Criteria', 'Strategy', 'Category']
df_tmp = df_portfolio_features[~df_portfolio_features['Symbol'].isin(['ENRIN','BLUSPRING','DIGITIDE'])]
df_tmp = df_tmp.sort_values(by = 'FTT Amt', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
1,ABB,0.01,39.22,4.56,45.57,16609.0,102605.0,364224.0,7934.00,-10.49,82.0,H-MC,20.49,125.0,6.18,2.48,61.74,AR,NTT,ELECTRICAL
54,MASFIN,-1.25,-2.33,24.46,21.57,23408.0,-2280.0,95700.0,397.04,-15.99,57.0,H-SC,2.67,167.0,-0.10,0.65,23.67,XR,ATH,FINANCE
81,TTKPRESTIG,2.83,-32.41,48.08,0.09,32752.0,-32657.0,68120.0,770.00,58.16,62.0,M-SC,22.19,250.0,-1.00,0.46,21.30,OX40N,NTT,DURABLES
53,MARUTI,-1.45,-2.75,31.56,27.95,33186.0,-2968.0,105152.0,17292.00,-19.52,46.0,X-LC,11.95,33.0,-0.09,0.72,13.58,XR,ATH,AUTO
18,CIPLA,5.61,6.08,27.41,35.15,35431.0,7405.0,129264.0,1663.60,-18.19,64.0,X-LC,15.60,18.0,0.21,0.88,9.50,X40N,ATH,PHARMA

In [10]:
# top 5 today
df_tmp = df_portfolio_features.sort_values(by = 'Today P/L%', ascending=False)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
60,RAJOOENG,6.38,-29.71,98.61,39.61,71049.0,-30450.0,72050.0,143.1,-52.38,69.0,H-SC,26.45,136.0,-0.43,0.49,54.35,AR,ATH,MISC
18,CIPLA,5.61,6.08,27.41,35.15,35431.0,7405.0,129264.0,1663.6,-18.19,64.0,X-LC,15.60,18.0,0.21,0.88,9.50,X40N,ATH,PHARMA
59,RAJESHEXPO,4.99,-75.14,302.52,0.07,103168.0,-103074.0,34103.0,518.0,1150.00,62.0,L-SC,39.12,268.0,-1.00,0.23,60.10,OX40N,NTT,JEWELLERY
49,JIOFIN,4.17,-17.55,55.77,28.43,137175.0,-52361.0,245966.0,387.0,-18.83,56.0,X-LC,18.31,34.0,-0.38,1.68,10.87,XY24,BTT,FINANCE
81,TTKPRESTIG,2.83,-32.41,48.08,0.09,32752.0,-32657.0,68120.0,770.0,58.16,62.0,M-SC,22.19,250.0,-1.00,0.46,21.30,OX40N,NTT,DURABLES

In [11]:
# bottom 5 today
df_tmp = df_portfolio_features.sort_values(by = 'Today P/L%', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
33,HAVELLS,-6.49,-19.25,63.56,32.08,168340.0,-63139.0,264852.0,2062.85,-24.09,45.0,X-MC,12.45,63.0,-0.38,1.80,6.83,X40,ATH,ELECTRICAL
23,DIXON,-3.24,-20.58,73.66,37.92,152570.0,-53670.0,207128.0,18931.72,-66.27,53.0,X-MC,24.39,54.0,-0.35,1.41,12.70,X40N,ATH,IT
76,TATAELXSI,-2.71,-38.83,115.84,32.03,93416.0,-51193.0,80642.0,9161.00,-23.56,43.0,H-SC,17.69,158.0,-0.55,0.55,6.73,OX40N,NTT,IT
84,VALIANTORG,-2.70,-46.13,223.29,74.15,196788.0,-75474.0,88131.0,838.00,-258.45,53.0,H-SC,18.08,145.0,-0.38,0.60,31.15,XR,NTT,CHEMICALS
30,GREENPANEL,-2.42,-44.82,159.41,43.14,161038.0,-82057.0,101021.0,537.00,126.10,54.0,M-SC,21.89,225.0,-0.51,0.69,21.35,XY24,NTT,MISC

In [12]:
# top 5 to exit based on CumlRnk
df_tmp = df_portfolio_features[~df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])]
df_tmp = df_tmp[(df_tmp['Current P/L%'] > -1) & (df_tmp['Current P/L%'] < 1)].sort_values(by = 'CumlRnk', ascending=False)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
71,SONACOMS,-2.35,-0.60,39.93,39.09,40152.0,-604.0,100555.0,804.02,-21.28,60.0,M-MC,11.89,193.0,-0.02,0.68,42.25,AR,ATH,AUTO
72,STARHEALTH,1.58,0.02,47.24,47.26,132823.0,43.0,281166.0,761.00,57.86,73.0,H-SC,3.62,173.0,0.00,1.92,45.61,XY24,NTT,INSURANCE
89,ZYDUSLIFE,1.99,0.01,35.61,35.63,74637.0,22.0,209596.0,1286.17,-13.06,64.0,H-MC,4.34,120.0,0.00,1.43,11.59,AR,ATH,PHARMA

In [13]:
# OX40N stocks to exit
df_tmp = df_portfolio_features[(df_portfolio_features['Symbol'].isin(list_ox40n))].sort_values(by = 'Current P/L%', ascending=False)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
26,FINCABLES,-0.13,23.43,68.45,107.91,124738.0,34588.0,182232.0,1641.55,11.11,70.0,M-SC,4.80,220.0,0.28,1.24,37.10,OX40N,ATH,CABLES
70,SIS,-2.09,-24.12,59.81,21.26,50391.0,-26780.0,84252.0,528.00,1987.56,68.0,H-SC,8.38,168.0,-0.53,0.57,25.27,OX40N,NTT,MISC
17,CERA,-0.41,-28.53,73.33,23.89,92194.0,-50178.0,125725.0,9475.00,-31.03,70.0,H-SC,12.99,153.0,-0.54,0.86,20.82,OX40N,NTT,CERAMICS
81,TTKPRESTIG,2.83,-32.41,48.08,0.09,32752.0,-32657.0,68120.0,770.00,58.16,62.0,M-SC,22.19,250.0,-1.00,0.46,21.30,OX40N,NTT,DURABLES
51,KANSAINER,-1.76,-33.10,69.62,13.47,125598.0,-89262.0,180405.0,340.00,-42.48,59.0,H-SC,18.59,162.0,-0.71,1.23,26.01,XY24,NTT,PAINTS

In [14]:
# top 5 to book for rotation
df_tmp = df_portfolio_features[(df_portfolio_features['Current P/L%'] > 20) ].sort_values(by = 'CumlRnk', ascending=False)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
26,FINCABLES,-0.13,23.43,68.45,107.91,124738.0,34588.0,182232.0,1641.55,11.11,70.0,M-SC,4.80,220.0,0.28,1.24,37.10,OX40N,ATH,CABLES
1,ABB,0.01,39.22,4.56,45.57,16609.0,102605.0,364224.0,7934.00,-10.49,82.0,H-MC,20.49,125.0,6.18,2.48,61.74,AR,NTT,ELECTRICAL

In [15]:
# top 5 to monitor for exit
df_tmp = df_portfolio_features[~df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])]
df_tmp = df_tmp[(df_tmp['Current P/L%'] > 0) ].sort_values(by = 'Dev%_PE', ascending=False)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
72,STARHEALTH,1.58,0.02,47.24,47.26,132823.0,43.0,281166.0,761.00,57.86,73.0,H-SC,3.62,173.0,0.00,1.92,45.61,XY24,NTT,INSURANCE
61,RECLTD,-1.68,2.03,18.33,20.74,37997.0,4125.0,207295.0,446.00,13.28,66.0,M-MC,3.73,191.0,0.11,1.41,23.53,XY25,NTT,FINANCE
26,FINCABLES,-0.13,23.43,68.45,107.91,124738.0,34588.0,182232.0,1641.55,11.11,70.0,M-SC,4.80,220.0,0.28,1.24,37.10,OX40N,ATH,CABLES
1,ABB,0.01,39.22,4.56,45.57,16609.0,102605.0,364224.0,7934.00,-10.49,82.0,H-MC,20.49,125.0,6.18,2.48,61.74,AR,NTT,ELECTRICAL
89,ZYDUSLIFE,1.99,0.01,35.61,35.63,74637.0,22.0,209596.0,1286.17,-13.06,64.0,H-MC,4.34,120.0,0.00,1.43,11.59,AR,ATH,PHARMA

In [16]:
# top 5 to book for rotation from weak conviction
df_tmp = df_portfolio_features[~df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])]
df_tmp = df_tmp[~df_tmp['Criteria'].isin(['XY25','XY24','X40', 'X40N'])].sort_values(by = 'RRR Ind', ascending=False)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
1,ABB,0.01,39.22,4.56,45.57,16609.0,102605.0,364224.0,7934.00,-10.49,82.0,H-MC,20.49,125.0,6.18,2.48,61.74,AR,NTT,ELECTRICAL
26,FINCABLES,-0.13,23.43,68.45,107.91,124738.0,34588.0,182232.0,1641.55,11.11,70.0,M-SC,4.80,220.0,0.28,1.24,37.10,OX40N,ATH,CABLES
89,ZYDUSLIFE,1.99,0.01,35.61,35.63,74637.0,22.0,209596.0,1286.17,-13.06,64.0,H-MC,4.34,120.0,0.00,1.43,11.59,AR,ATH,PHARMA
71,SONACOMS,-2.35,-0.60,39.93,39.09,40152.0,-604.0,100555.0,804.02,-21.28,60.0,M-MC,11.89,193.0,-0.02,0.68,42.25,AR,ATH,AUTO
43,INDIAMART,-0.27,-7.07,122.46,106.72,140354.0,-8724.0,114612.0,4810.62,-58.01,59.0,H-SC,11.11,140.0,-0.06,0.78,10.11,AR,ATH,MISC

In [17]:
# top 5 to accumulate based on lowest RSI_14
df_tmp = df_portfolio_features[df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])].sort_values(by = 'RSI_14', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
34,HCLTECH,-0.68,-17.15,49.47,23.83,99151.0,-41498.0,200426.0,1908.19,-13.15,31.0,X-LC,7.34,8.0,-0.42,1.37,0.00,X40,ATH,IT
46,INFY,-1.85,-15.24,58.38,34.24,154827.0,-47682.0,265206.0,1972.00,-33.24,38.0,X-LC,12.49,3.0,-0.31,1.81,1.99,X40,NTT,IT
2,ABBOTINDIA,-0.10,-14.81,38.59,18.07,58800.0,-26485.0,152370.0,35195.00,-27.52,39.0,X-MC,11.95,58.0,-0.45,1.04,0.04,X40,ATH,PHARMA
41,ICICIPRULI,-0.60,-11.17,47.17,30.73,82546.0,-22008.0,174997.0,790.00,-35.01,40.0,X-MC,13.12,78.0,-0.27,1.19,6.63,X40,ATH,INSURANCE
36,HDFCLIFE,-0.48,-2.05,35.46,32.69,41568.0,-2448.0,117224.0,814.30,-23.29,42.0,X-LC,17.87,31.0,-0.06,0.80,6.19,X40,ATH,INSURANCE

In [18]:
# top 5 to accumulate based on Spread and CumlRnk
df_tmp = df_portfolio_features[df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])]
df_tmp = df_tmp[(df_tmp['CumlRnk'] < 100)].sort_values(by = 'Spread%', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
69,SIEMENS,0.55,3.86,20.85,25.51,40297.0,7175.0,193270.0,4671.50,62.33,76.0,H-LC,4.78,51.0,0.18,1.32,36.42,AR,ATH,ELECTRICAL
82,UNITDSPR,-0.52,1.78,18.66,20.77,44468.0,4162.0,238306.0,1644.00,-9.71,63.0,X-MC,5.43,64.0,0.09,1.62,13.68,X40N,NTT,BREWERIES
63,RELIANCE,-1.17,-13.59,45.01,25.30,78159.0,-27316.0,173647.0,1952.00,-15.80,46.0,X-LC,5.86,21.0,-0.35,1.18,3.96,XY25,BTT,REFINERIES
86,VOLTAS,-2.25,13.30,28.15,45.20,61154.0,25503.0,217245.0,1856.00,29.67,59.0,X-MC,6.09,79.0,0.42,1.48,21.00,XY25,NTT,AC
24,DMART,-1.50,8.79,19.13,29.60,51946.0,21942.0,271542.0,5391.45,-8.27,64.0,X-LC,6.36,14.0,0.42,1.85,24.12,X40N,ATH,FMCG

In [19]:
# top 5 to accumulate based on lowest Gained%
df_tmp = df_portfolio_features[df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])].sort_values(by = 'Gained%', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
34,HCLTECH,-0.68,-17.15,49.47,23.83,99151.0,-41498.0,200426.0,1908.19,-13.15,31.0,X-LC,7.34,8.0,-0.42,1.37,0.00,X40,ATH,IT
2,ABBOTINDIA,-0.10,-14.81,38.59,18.07,58800.0,-26485.0,152370.0,35195.00,-27.52,39.0,X-MC,11.95,58.0,-0.45,1.04,0.04,X40,ATH,PHARMA
46,INFY,-1.85,-15.24,58.38,34.24,154827.0,-47682.0,265206.0,1972.00,-33.24,38.0,X-LC,12.49,3.0,-0.31,1.81,1.99,X40,NTT,IT
63,RELIANCE,-1.17,-13.59,45.01,25.30,78159.0,-27316.0,173647.0,1952.00,-15.80,46.0,X-LC,5.86,21.0,-0.35,1.18,3.96,XY25,BTT,REFINERIES
48,ITC,-0.15,-19.65,48.17,19.06,131661.0,-66841.0,273325.0,452.00,-55.92,51.0,X-LC,18.70,1.0,-0.51,1.86,6.03,X40,NTT,FMCG

In [20]:
# top 5 to accumulate based on lowest CurrAlloc%
df_tmp = df_portfolio_features[df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])].sort_values(by = 'CurrAlloc%', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
62,RELAXO,-0.41,-59.79,278.80,52.31,162722.0,-86795.0,58365.0,1176.0,-57.22,58.0,X-SC,30.59,92.0,-0.53,0.40,30.50,X40N,NTT,FOOTWEAR
11,BATAINDIA,-1.76,-50.93,175.54,35.20,110832.0,-65532.0,63138.0,2096.0,-17.26,61.0,X-SC,30.09,91.0,-0.59,0.43,25.22,X40,NTT,FOOTWEAR
58,QUESS,-1.63,-20.21,117.94,73.90,100500.0,-21580.0,85213.0,424.0,-57.02,56.0,X-SC,18.20,80.0,-0.21,0.58,14.63,XY24,NTT,MISC
53,MARUTI,-1.45,-2.75,31.56,27.95,33186.0,-2968.0,105152.0,17292.0,-19.52,46.0,X-LC,11.95,33.0,-0.09,0.72,13.58,XR,ATH,AUTO
36,HDFCLIFE,-0.48,-2.05,35.46,32.69,41568.0,-2448.0,117224.0,814.3,-23.29,42.0,X-LC,17.87,31.0,-0.06,0.80,6.19,X40,ATH,INSURANCE

In [21]:
# top 5 to accumulate based on CumlRnk
df_tmp = df_portfolio_features.sort_values(by = 'CumlRnk', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
48,ITC,-0.15,-19.65,48.17,19.06,131661.0,-66841.0,273325.0,452.00,-55.92,51.0,X-LC,18.70,1.0,-0.51,1.86,6.03,X40,NTT,FMCG
77,TCS,-0.54,-25.88,70.77,26.57,243005.0,-119900.0,343373.0,4311.59,-37.40,49.0,X-LC,15.35,2.0,-0.49,2.34,7.16,X40,ATH,IT
46,INFY,-1.85,-15.24,58.38,34.24,154827.0,-47682.0,265206.0,1972.00,-33.24,38.0,X-LC,12.49,3.0,-0.31,1.81,1.99,X40,NTT,IT
79,TMPV,-2.17,-19.42,69.49,36.58,199256.0,-69101.0,286740.0,600.00,-83.62,58.0,X-LC,8.39,4.0,-0.35,1.95,19.51,XY24,NTT,AUTO
34,HCLTECH,-0.68,-17.15,49.47,23.83,99151.0,-41498.0,200426.0,1908.19,-13.15,31.0,X-LC,7.34,8.0,-0.42,1.37,0.00,X40,ATH,IT

In [22]:
# top 5 for average up
df_tmp = df_portfolio_features[(df_portfolio_features['Dev%_200'] > 5)].sort_values(by = 'CurrAlloc%', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
71,SONACOMS,-2.35,-0.60,39.93,39.09,40152.0,-604.0,100555.0,804.02,-21.28,60.0,M-MC,11.89,193.0,-0.02,0.68,42.25,AR,ATH,AUTO
73,SURYODAY,-2.00,-16.95,48.14,23.03,71597.0,-30345.0,148726.0,216.00,62.28,63.0,H-SC,3.28,166.0,-0.42,1.01,26.84,XR,NTT,BANKS
26,FINCABLES,-0.13,23.43,68.45,107.91,124738.0,34588.0,182232.0,1641.55,11.11,70.0,M-SC,4.80,220.0,0.28,1.24,37.10,OX40N,ATH,CABLES
69,SIEMENS,0.55,3.86,20.85,25.51,40297.0,7175.0,193270.0,4671.50,62.33,76.0,H-LC,4.78,51.0,0.18,1.32,36.42,AR,ATH,ELECTRICAL
61,RECLTD,-1.68,2.03,18.33,20.74,37997.0,4125.0,207295.0,446.00,13.28,66.0,M-MC,3.73,191.0,0.11,1.41,23.53,XY25,NTT,FINANCE

In [23]:
# top 5 RSP
df_tmp = df_portfolio_features.sort_values(by = 'RSP', ascending=False)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
59,RAJESHEXPO,4.99,-75.14,302.52,0.07,103168.0,-103074.0,34103.0,518.0,1150.00,62.0,L-SC,39.12,268.0,-1.00,0.23,60.10,OX40N,NTT,JEWELLERY
60,RAJOOENG,6.38,-29.71,98.61,39.61,71049.0,-30450.0,72050.0,143.1,-52.38,69.0,H-SC,26.45,136.0,-0.43,0.49,54.35,AR,ATH,MISC
69,SIEMENS,0.55,3.86,20.85,25.51,40297.0,7175.0,193270.0,4671.5,62.33,76.0,H-LC,4.78,51.0,0.18,1.32,36.42,AR,ATH,ELECTRICAL
85,VBL,-2.12,-2.14,38.47,35.50,118903.0,-6763.0,309079.0,670.8,-13.69,68.0,X-LC,7.89,13.0,-0.06,2.11,26.91,X40N,ATH,FMCG
64,REPCOHOME,0.33,-8.32,107.03,89.82,281147.0,-23824.0,262681.0,880.0,-54.55,70.0,H-SC,2.78,161.0,-0.08,1.79,26.28,XY24,NTT,FINANCE

In [24]:
# Top N allocation
df_tmp = df_portfolio_features.sort_values(by = 'CurrAlloc%', ascending=False)
top_n_values = [10, 25, 50]

sum_df = pd.DataFrame({
    'Top_N': top_n_values,
    'Sum_Alloc%': [df_tmp['CurrAlloc%'].head(n).sum() for n in top_n_values]
})

sum_df

   Top_N  Sum_Alloc%
0     10       19.92
1     25       44.25
2     50       75.08

In [25]:
# market-cap-wise allocation
df_tmp = df_portfolio_features[cols]
df_tmp.groupby(df_tmp['Conviction'].str[-2:])['CurrAlloc%'].sum().sort_values(ascending=False)

Conviction
SC    42.30
MC    29.10
LC    28.59
Name: CurrAlloc%, dtype: float64

In [26]:
# criteria-wise allocation
df_portfolio_features.groupby('Criteria')['CurrAlloc%'].sum().sort_values(ascending=False)

Criteria
XY24     26.85
X40      24.33
X40N     15.73
AR        9.43
XR        8.82
XY25      7.15
OX40N     6.87
SR        0.81
Name: CurrAlloc%, dtype: float64

In [27]:
# conviction-wise allocation
df_portfolio_features.groupby('Conviction')['CurrAlloc%'].sum().sort_values(ascending=False)

Conviction
X-LC    26.31
H-SC    21.82
X-MC    21.55
M-SC    10.04
X-SC     9.85
H-MC     5.13
M-MC     2.09
H-LC     1.32
M-LC     0.96
L-SC     0.59
L-MC     0.33
Name: CurrAlloc%, dtype: float64

In [28]:
# sector-wise stats
df_tmp = df_portfolio_features.groupby('Category')[['CurrAlloc%', 'Current', 'Current P/L', 'FTT Amt']].sum().sort_values(by=['Current', 'Current P/L'], ascending=False)
df_tmp['Current P/L%'] = round(df_tmp['Current P/L'] * 100 / df_tmp['Current'], 2)
df_tmp['FTT%'] = round(df_tmp['FTT Amt'] * 100 / df_tmp['Current'], 2)
cols = ['CurrAlloc%', 'Current P/L%', 'FTT%']
df_tmp[cols].sort_values(by=['CurrAlloc%'], ascending=False)

               CurrAlloc%  Current P/L%    FTT%
Category
FMCG                15.72        -13.78   53.99
FINANCE             10.96        -14.53   64.34
IT                  10.92        -40.67  112.26
MISC                 7.00        -30.41   87.06
ELECTRICAL           6.72          1.80   35.80
AUTO                 5.26        -14.39   59.50
PAINTS               5.24        -28.06   50.29
INSURANCE            5.22         -4.25   39.69
PHARMA               4.70         -2.96   36.02
BANKS                4.42        -18.47   78.60
AC                   2.01         -8.05   37.35
HEALTHCARE           1.89        -28.28   61.76
APPARELS             1.80         -1.36   35.94
FOOTWEAR             1.80        -67.33  134.42
DURABLES             1.77        -48.22   84.28
TRAVEL               1.74        -75.05  162.70
BREWERIES            1.62          1.75   18.66
REALTY               1.42         -6.75   24.29
CERAMICS             1.34        -56.58  104.15
CABLES               1.24         18.98   68.45
REFINERIES           1.18        -15.73   45.01
CEMENT               1.16        -56.91  174.30
ENGINEERING          1.15        -43.19  108.68
JEWELLERY            1.09       -100.19  169.75
CHEMICALS            1.05        -71.93  212.19
ENTERTAINMENT        0.77        -71.48  173.75
TEXTILES             0.44        -43.38   84.26
HOTELS               0.36       -117.67  194.44

In [29]:
# money to be made criteria-wise
df_portfolio_features.groupby('Criteria')['FTT Amt'].agg(['sum', 'count']).sort_values(by='sum', ascending=False)

                sum  count
Criteria
XY24      3655232.0     21
X40       1762278.0     17
XR        1335355.0     13
AR        1187164.0     10
X40N      1126036.0     12
OX40N      780712.0     10
XY25       390244.0      5
SR         301335.0      2

In [30]:
# money to be made conviction-wise
df_portfolio_features.groupby('Conviction')['FTT Amt'].agg(['sum', 'count']).sort_values(by='sum', ascending=False)

                  sum  count
Conviction
H-SC        3591393.0     24
X-LC        1725854.0     18
X-MC        1570055.0     15
M-SC        1441366.0     14
X-SC        1356886.0      9
H-MC         325211.0      3
L-SC         204600.0      2
M-LC         150853.0      1
M-MC          78149.0      2
L-MC          53692.0      1
H-LC          40297.0      1

In [31]:
# money to be made criteria and conviction-wise
df_portfolio_features.groupby(['Conviction', 'Criteria'])['FTT Amt'].agg(['sum', 'count']).sort_values(by='sum', ascending=False)

                           sum  count
Conviction Criteria
H-SC       XY24      1188804.0      6
           AR         940989.0      5
X-LC       X40        916424.0      8
M-SC       XY24       853415.0      6
H-SC       XR         820286.0      7
X-SC       XY24       807775.0      4
X-MC       X40        646228.0      7
           X40N       469344.0      4
X-SC       X40N       349485.0      3
H-SC       OX40N      339979.0      4
M-SC       OX40N      337565.0      5
X-LC       XY24       336431.0      2
           X40N       307207.0      5
H-SC       SR         301335.0      2
X-MC       XY24       234842.0      2
H-MC       XY24       233965.0      1
X-MC       XY25       219641.0      2
X-SC       X40        199626.0      2
M-SC       XR         175906.0      2
M-LC       XR         150853.0      1
X-LC       XY25       132606.0      2
L-SC       OX40N      103168.0      1
           XR         101432.0      1
H-MC       AR          91246.0      2
M-SC       AR          74480.0      1
L-MC       XR          53692.0      1
H-LC       AR          40297.0      1
M-MC       AR          40152.0      1
           XY25        37997.0      1
X-LC       XR          33186.0      1

In [32]:
# notebook execution time

end_time = time.time()
execution_time = round(end_time - start_time, 0)
print(f"Notebook execution time: {execution_time} seconds")

Notebook execution time: 37.0 seconds