<a href="https://colab.research.google.com/github/ankit-rathi/Quantvesting_v2/blob/main/myStocks_Portfolio_Analysis.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
'''
!pip install pandas==2.2.2 -qq
!pip install pyxirr -qq
!pip install ta -qq
!pip install yfinance==0.2.59 -qq
'''

'\n!pip install pandas==2.2.2 -qq\n!pip install pyxirr -qq\n!pip install ta -qq\n!pip install yfinance==0.2.59 -qq\n'

In [2]:
# import libraries

import numpy as np
import pandas as pd
import datetime
import warnings
warnings.filterwarnings('ignore')
import yfinance as yfin
import ta
import matplotlib.pyplot as plt
import requests

In [3]:
# notebook start time
import time
import datetime
import pytz

start_time = time.time()

# function to print date timestamp
def print_date_time():
  tz_NY = pytz.timezone('Asia/Kolkata')
  datetime_NY = datetime.datetime.now(tz_NY)
  print("Run date time (IST):", datetime_NY.strftime("%Y-%m-%d %H:%M:%S"))

In [4]:
# function to get booked and reserved amount
def get_amt():
  # fetch the JSON data from the URL
  url = "https://raw.githubusercontent.com/ankit-rathi/Tradevesting_v1/main/data/myPortfolioAmts.json"
  response = requests.get(url)
  pf_amts = response.json()  # parse the JSON data

  # extract values from the JSON
  py_booked_amt_dm = pf_amts["py_booked_amt_dm"]
  py_booked_amt_sv = pf_amts["py_booked_amt_sv"]
  cy_booked_amt_dm = pf_amts["cy_booked_amt_dm"]
  cy_booked_amt_sv = pf_amts["cy_booked_amt_sv"]
  reserve_amt_dm = pf_amts["reserve_amt_dm"]
  reserve_amt_sv = pf_amts["reserve_amt_sv"]

  # perform calculations
  py_booked_amt = py_booked_amt_dm + py_booked_amt_sv
  cy_booked_amt = cy_booked_amt_dm + cy_booked_amt_sv
  reserve_amt = reserve_amt_dm + reserve_amt_sv
  total_booked_amt = py_booked_amt + cy_booked_amt

  return total_booked_amt, reserve_amt, cy_booked_amt, py_booked_amt

gen_output = 0

In [5]:
# function to format the amount
def format_amt(number):
    abs_number = abs(number)

    if abs_number >= 1_00_00_000:  # Crores
        formatted_amt = f"{number / 1_00_00_000:.2f} C"
    elif abs_number >= 1_00_000:  # Lakhs
        formatted_amt = f"{number / 1_00_000:.2f} L"
    elif abs_number >= 1_000:  # Thousands
        formatted_amt = f"{number / 1_000:.2f} K"
    else:
        formatted_amt = f"{number:.2f}"

    return formatted_amt

# function to set start and end date
def get_start_end_date():
  start_date = (datetime.date.today() + datetime.timedelta(days=-365)).strftime('%Y-%m-%d')
  end_date = (datetime.date.today() + datetime.timedelta(days=1)).strftime('%Y-%m-%d')
  return start_date, end_date

# function to fetch my portfolio csv
def get_mypfs_df():
  mypfs_df = pd.read_csv('https://raw.githubusercontent.com/ankit-rathi/Tradevesting_v1/main/data/myPortfolioStocks.csv')
  return mypfs_df

# function to fetch my prospects csv
def get_mypps_df():
  mypps_df = pd.read_csv('https://raw.githubusercontent.com/ankit-rathi/Tradevesting_v1/main/data/myProspectsScrips.csv')
  return mypps_df

# function to fetch screener data
def get_myscreen_df():
  myscreen_df = pd.read_csv('https://raw.githubusercontent.com/ankit-rathi/Tradevesting_v1/main/data/myScreenerDB.csv')
  return myscreen_df

# function to fetch momentum data
def get_myinvmt_df():
  myinvmt_df = pd.read_csv('https://raw.githubusercontent.com/ankit-rathi/Tradevesting_v1/main/data/myInvestments.csv')
  return myinvmt_df

# function to get the stock ids
def get_stock_ids(df_pf):
  stock_n100 = df_pf['Symbol'].unique()

  exclude = ['CADILAHC','MMTC', 'MASFIN']

  stock_ids = df_pf[~df_pf['Symbol'].isin(exclude) ]['Symbol'].unique()

  #mypf = mypf[mypf.Forecast.notnull()]
  #stock_ids = mypf['Symbol'].unique()

  #stock_ids.sort()
  return stock_ids

# get features from screener data
def get_screener_features():
  myscreen_df = get_myscreen_df()
  cols = ['Symbol', 'EPS', 'MedPE', 'ROCE%', 'ROE%', 'CapType']
  return myscreen_df[cols]

# get relative strength
def get_relative_strength(stock_list):

    # Dictionary to store stock tickers and their corresponding percentage price change
    stock_changes = {}

    # Loop through each stock and fetch its price data
    for stock in stock_list:
        try:
            # Download the stock data for the given date range
            stock_data = yfin.Ticker(stock + '.NS').history(period='1mo', interval='1d')[map(str.title, ['open', 'close', 'low', 'high', 'volume'])]

            # Calculate the percentage change for the stock
            if len(stock_data) > 0:
                start_price = stock_data['Close'].iloc[0]
                end_price = stock_data['Close'].iloc[-1]
                percent_change = round(((end_price - start_price) / start_price) * 100, 2)
                stock_changes[stock] = percent_change
            else:
                stock_changes[stock] = np.nan  # If no data is available, set to NaN

        except Exception as e:
            print(f"Error fetching data for {stock}: {e}")
            stock_changes[stock] = np.nan

    # Create a DataFrame with stock tickers and their percentage changes
    df = pd.DataFrame(list(stock_changes.items()), columns=['Symbol', 'Percent_Change'])

    # Drop any stocks with missing data (NaN values)
    df = df.dropna()

    # Calculate the percentile rank based on percentage change
    df['RSP'] = round(df['Percent_Change'].rank(pct=True) * 100, 2)
    cols = ['Symbol', 'RSP']
    df = df[cols]
    # Sort by percentile rank (optional)
    df = df.sort_values(by='RSP', ascending=False).reset_index(drop=True)

    return df

In [6]:
# function to get stock technicals
def stock_prec_dev(stock_symbol):
    #stock_symbol = 'ULTRACEMCO.NS'
    short_window = 20
    mid_window = 50
    long_window = 200
    moving_avg = 'SMA'

    start = datetime.datetime(*map(int, start_date.split('-')))
    end = datetime.datetime(*map(int, end_date.split('-')))

    stock_df = yfin.Ticker(stock_symbol + '.NS').history(period='max', interval='1d')[map(str.title, ['open', 'close', 'low', 'high', 'volume'])]

    stock_df['Max'] = round(max(stock_df['Close']),2)
    stock_df = stock_df[(stock_df.index <= end_date) & (stock_df.index >= start_date)]
    stock_df['200_SMA'] = round(stock_df['Close'].rolling(window = 200, min_periods = 1).mean(),0)
    stock_df['Dev%_200'] = round((stock_df['Close'] - stock_df['200_SMA'])*100/stock_df['200_SMA'],2)
    stock_df.dropna(axis = 0, inplace = True) # remove any null rows

    stock_df['20_SMA'] = stock_df['Close'].rolling(window=20).mean()
    stock_df['50_SMA'] = stock_df['Close'].rolling(window=50).mean()
    stock_df['Symbol'] = stock_symbol

    stock_df['Close'] = round(stock_df['Close'],2)
    stock_df['Min'] = round(min(stock_df['Close']),2)
    stock_df['RSI_14'] = ta.momentum.RSIIndicator(close=stock_df['Close'], window=14).rsi()
    stock_df['RSI_14'] = round(stock_df['RSI_14'],0)
    stock_df['Prev_Close'] = stock_df['Close'].shift(1)
    stock_df.drop(['Open', 'Low', 'High', 'Volume'], axis=1, inplace=True)
    stock_df = stock_df.tail(1)

    max_SMA = max(stock_df['20_SMA'].item(), stock_df['50_SMA'].item(), stock_df['200_SMA'].item())
    min_SMA = min(stock_df['20_SMA'].item(), stock_df['50_SMA'].item(), stock_df['200_SMA'].item())
    ABS_Spread = max_SMA - min_SMA
    stock_df['Spread%'] = round((ABS_Spread / stock_df['200_SMA'].item()) * 100,2)

    return stock_df

# function to compute stock attributes
def get_common_features(stock_ids, df_mypf):

  df_prec_dev = pd.DataFrame()
  df_tmp = get_screener_features()
  df_rs = get_relative_strength(stock_ids)

  for stock_id in stock_ids:
      tmp = stock_prec_dev(stock_id)
      tmp = tmp.reset_index()
      df_prec_dev = pd.concat([df_prec_dev, tmp], ignore_index = True)
  df_prec_dev = pd.merge(df_prec_dev, df_mypf, on= 'Symbol')
  df_prec_dev = pd.merge(df_prec_dev, df_tmp, on= 'Symbol', how='left')
  df_prec_dev = pd.merge(df_prec_dev, df_rs, on= 'Symbol', how='left')
  #print(df_prec_dev.columns)
  df_prec_dev['Curr_PE'] = round(df_prec_dev['Close']/df_prec_dev['EPS'],1)
  df_prec_dev['Dev%_PE'] = round((df_prec_dev['Curr_PE'] - df_prec_dev['MedPE'])*100/df_prec_dev['MedPE'],2)
  df_prec_dev['Conviction'] = df_prec_dev['Conviction'] + '-' + df_prec_dev['CapType']
  return df_prec_dev

# function to arrange stock features
def arrange_features(df_stocks, common_cols, diff_cols):
  df_stocks_common = df_stocks[common_cols].drop_duplicates()
  df_stocks_diff = df_stocks[diff_cols]
  df_stocks_diff['Investment'] = df_stocks_diff['AvgCost'] * df_stocks_diff['Shares']
  df_stocks_diff = df_stocks_diff.groupby(['Symbol'])[['Shares', 'Investment']].aggregate(['sum']).reset_index()
  df_stocks_diff.columns = ['Symbol', 'Shares', 'Investment']
  df_stocks_diff['AvgCost'] = round(df_stocks_diff['Investment']/df_stocks_diff['Shares'],2)
  df_stocks = pd.merge(df_stocks_diff, df_stocks_common, on='Symbol')
  return df_stocks

# plot fact distribution across dimension
def plot_pie_chart(df, dimension, fact):
  # grouping the data by category and calculating the sum of fact for each type
  grouped_data = df.groupby(dimension)[fact].sum()

  # sorting the grouped data in descending order
  grouped_data = grouped_data.sort_values(ascending=False)

  # creating a pie chart
  grouped_data.plot.pie(autopct='%1.1f%%', startangle=90, figsize=(6, 6))

  # adding a title and displaying the plot
  plt.title(f'{dimension} {fact} Distribution')
  plt.ylabel('')  # To hide the y-label
  plt.show()

In [7]:
# function to get portfolio features

def get_portfolio_features(df_common_features):

  print_date_time()
  print('-------------------')

  #df_common_features["Target"] = df_common_features["Target"].fillna(df_common_features["Max"])
  df_common_features['NTT'] = np.where(df_common_features['Strategy']== 'NTT', df_common_features["Target"], df_common_features['Max'])
  df_common_features['LTT'] = np.where(df_common_features['Strategy']== 'BTT', df_common_features["Target"], df_common_features['Max'])
  df_common_features['BOL'] = df_common_features['Min']

  tmp_df = df_common_features[df_common_features['Symbol'].isin(mypf_df[mypf_df['InPortfolio'] != 'NA'].Symbol.values)]
  print('qualified stocks: '+str(len(tmp_df['Symbol'].unique())))
  tmp_df1 = tmp_df[tmp_df['LatestQtr'] == 1]
  print('with latest results: '+str(len(tmp_df1['Symbol'].unique())))
  tmp_df1 = tmp_df1[tmp_df1['StarStock'] == 1]
  print('still star stocks: '+str(len(tmp_df1['Symbol'].unique())))
  tmp_df['Investment'] = tmp_df['AvgCost'] * tmp_df['Shares']
  tmp_df['Current'] = round(tmp_df['Close'] * tmp_df['Shares'],0)
  tmp_df['Previous'] = tmp_df['Prev_Close'] * tmp_df['Shares']
  tmp_df['EstimatedST'] = tmp_df['NTT'] * tmp_df['Shares']
  tmp_df['EstimatedLT'] = tmp_df['LTT'] * tmp_df['Shares']
  tmp_df['Current P/L'] = round((tmp_df['Current'] - tmp_df['Investment']),0)
  tmp_df['Today P/L%'] = round((tmp_df['Current'] - tmp_df['Previous'])*100/tmp_df['Previous'],2)
  tmp_df['Current P/L%'] = round((tmp_df['Current'] - tmp_df['Investment'])*100/tmp_df['Investment'],2)
  tmp_df['EstimatedST P/L%'] = round((tmp_df['EstimatedST'] - tmp_df['Investment'])*100/tmp_df['Investment'],2)
  tmp_df['EstimatedLT P/L%'] = round((tmp_df['EstimatedLT'] - tmp_df['Investment'])*100/tmp_df['Investment'],2)
  tmp_df['NTT%'] = round((tmp_df['NTT'] - tmp_df['Close'])*100/tmp_df['Close'],2)
  tmp_df['LTT%'] = round((tmp_df['LTT'] - tmp_df['Close'])*100/tmp_df['Close'],2)
  tmp_df['Gained%'] = round((tmp_df['Close'] - tmp_df['BOL'])*100/tmp_df['BOL'],2)
  investment = round(sum(tmp_df['AvgCost']*tmp_df['Shares']),0)
  current = round(sum(tmp_df['Close']*tmp_df['Shares']),0)
  tmp_df['InitAlloc%'] = round(tmp_df['Investment']*100/investment,2)
  tmp_df['CurrAlloc%'] = round(tmp_df['Current']*100/current,2)
  tmp_df['FTT'] = tmp_df['LTT']
  tmp_df.loc[tmp_df['Strategy'] == 'NTT', 'FTT'] = tmp_df['NTT']
  tmp_df['FTT%'] = tmp_df['LTT%']
  tmp_df.loc[tmp_df['Strategy'] == 'NTT', 'FTT%'] = tmp_df['NTT%']
  tmp_df['FTT Amt'] = round(tmp_df['FTT%'] * tmp_df['Current']/100,0)
  tmp_df['OTT%'] = round((tmp_df['FTT'] - tmp_df['AvgCost'])*100/tmp_df['AvgCost'],2)
  tmp_df['RRR Ind'] = round(tmp_df['Current P/L']/tmp_df['FTT Amt'],2)
  tmp_df['Risk Ind'] = round(tmp_df['Current P/L%']*tmp_df['CurrAlloc%'],0)

  return tmp_df

# function to print portfolio features
def print_portfolio_stats(df_portfolio_features, myinvmt_df):
  from pyxirr import xirr

  total_booked_amt, reserve_amt, cy_booked_amt, py_booked_amt = get_amt()

  dates = myinvmt_df['Date'].values
  dates = np.append(dates, datetime.date.today().strftime('%d-%b-%y'))
  investment = myinvmt_df['Investment'].values
  dates= pd.to_datetime(dates)

  current = round(sum(df_portfolio_features['Close']*df_portfolio_features['Shares']),0) + reserve_amt
  investment_xirr = np.append(investment, current)
  cagr = round(xirr(pd.DataFrame({"dates": dates, "amounts": investment_xirr}))*100,2)

  investment = -sum(investment)
  invested = round(sum(df_portfolio_features['AvgCost']*df_portfolio_features['Shares']),0) + reserve_amt
  previous = round(sum(df_portfolio_features['Prev_Close']*df_portfolio_features['Shares']),0) + reserve_amt
  cy_invested = investment + py_booked_amt

  today_pnl_amount = current-previous
  today_pnl_percentage = round((current-previous)*100/previous,2)

  curr_pnl_amount = current-invested
  curr_pnl_percentage = round((curr_pnl_amount)*100/(cy_invested),2)

  cy_pnl_amount = cy_booked_amt + curr_pnl_amount
  cy_pnl_percentage = round((cy_pnl_amount)*100/cy_invested,2)

  overall_pnl_amount = total_booked_amt + curr_pnl_amount
  overall_pnl_percentage = round((overall_pnl_amount)*100/investment,2)

  estimate_st = round(sum(df_portfolio_features['FTT']*df_portfolio_features['Shares']),0)  + reserve_amt
  est_st_pnl_amount = estimate_st-current
  est_st_pnl_percentage = round((est_st_pnl_amount)*100/current,2)

  estimate_lt = round(sum(df_portfolio_features['LTT']*df_portfolio_features['Shares']),0)  + reserve_amt
  est_lt_pnl_amount = estimate_lt-current
  est_lt_pnl_percentage = round((est_lt_pnl_amount)*100/current,2)

  total_profit = round(sum(df_portfolio_features[df_portfolio_features['Current P/L%'] > 0]['Current']) - sum(df_portfolio_features[df_portfolio_features['Current P/L%'] > 0]['Investment']),0)
  total_loss = round(sum(df_portfolio_features[df_portfolio_features['Current P/L%'] < 0]['Current']) - sum(df_portfolio_features[df_portfolio_features['Current P/L%'] < 0]['Investment']),0)

  cy_booked_percentage = round((cy_booked_amt)*100/current,2)
  py_booked_percentage = round((py_booked_amt)*100/investment,2)
  total_booked_percentage = round((total_booked_amt)*100/investment,2)

  print('-------------------')
  print('Initial Investment: ', format_amt(investment))
  print('CY Investment: ', format_amt(cy_invested))
  print('Reserve: ', format_amt(reserve_amt))
  print('Current: ',  format_amt(current))
  print('-------------------')
  print('Today PnL: '+ '{} ({}%)'.format(format_amt(today_pnl_amount), today_pnl_percentage))
  print('Current PnL: '+ '{} ({}%)'.format(format_amt(curr_pnl_amount), curr_pnl_percentage))
  print('CY Booked + Current PnL: '+ '{} ({}%)'.format(format_amt(cy_pnl_amount), cy_pnl_percentage))
  print('-------------------')
  print('Total profit: ', format_amt(total_profit))
  print('Total loss: ', format_amt(total_loss))
  print('-------------------')
  print('Total Booked + Current PnL: '+ '{} ({}%)'.format(format_amt(overall_pnl_amount), overall_pnl_percentage))
  print('Total Booked PnL: '+ '{} ({}%)'.format(format_amt(total_booked_amt), total_booked_percentage))
  print('Curr Year Booked PnL: '+ '{} ({}%)'.format(format_amt(cy_booked_amt), cy_booked_percentage))
  print('Prev Year Booked PnL: '+ '{} ({}%)'.format(format_amt(py_booked_amt), py_booked_percentage))
  print('===================')
  print('Est FTT: ',  format_amt(estimate_st))
  print('Est FTT PnL: '+ '{} ({}%)'.format(format_amt(est_st_pnl_amount), est_st_pnl_percentage))

  print('===================')
  print('Deployed: ', format_amt(investment))

  print('Current: ', format_amt(current))

  print('CAGR/XIRR %: '+'{}%'.format(cagr))

In [8]:
# get start and end date
start_date, end_date = get_start_end_date()

# get portfolio and prospects data
mypfs_df = get_mypfs_df()
mypps_df = get_mypps_df()
myinvmt_df = get_myinvmt_df()

# merge above datasets
mypf_df = pd.merge(mypfs_df, mypps_df, on="Symbol")

# seggregate dm and sv portfolio
dm_pf = mypf_df[mypf_df['InPortfolio'] == 'DM']
sv_pf = mypf_df[mypf_df['InPortfolio'] == 'SV']

# build portfolio stock dataframe
dm_stocks = get_stock_ids(dm_pf)
sv_stocks = get_stock_ids(sv_pf)
df_stocks = pd.concat([dm_pf,sv_pf], ignore_index = True)

# arrange common and diff stock features
common_cols = ['Symbol', 'Target', 'Criteria', 'Strategy', 'CumlRnk', 'LatestQtr', 'StarStock', 'Conviction', 'Category', 'InFolio', 'XIRR', 'MBQ']
diff_cols = ['Symbol', 'AvgCost', 'Shares']
df_stocks = arrange_features(df_stocks, common_cols, diff_cols)

# get common features
stock_ids = df_stocks['Symbol'].values
df_common_features = get_common_features(stock_ids, df_stocks)

df_common_features.reset_index(drop=True, inplace=True)
df_common_features.drop(['Date'], axis=1, inplace=True)
# get and print portfolio features
df_portfolio_features = get_portfolio_features(df_common_features)

print_portfolio_stats(df_portfolio_features, myinvmt_df)

df = df_portfolio_features
#plot_pie_chart(df, 'CapType', 'Current')
list_ox40n = list(df[df['MBQ'].str.contains('OX40N', na=False)]['Symbol'].values)

Run date time (IST): 2026-06-29 17:28:36
-------------------
qualified stocks: 92
with latest results: 31
still star stocks: 20
-------------------
Initial Investment:  1.40 C
CY Investment:  1.82 C
Reserve:  1.49 K
Current:  1.51 C
-------------------
Today PnL: -90.13 K (-0.59%)
Current PnL: -32.42 L (-17.78%)
CY Booked + Current PnL: -30.34 L (-16.64%)
-------------------
Total profit:  3.84 L
Total loss:  -36.26 L
-------------------
Total Booked + Current PnL: 12.53 L (8.98%)
Total Booked PnL: 44.95 L (32.22%)
Curr Year Booked PnL: 2.08 L (1.38%)
Prev Year Booked PnL: 42.87 L (30.73%)
===================
Est FTT:  2.55 C
Est FTT PnL: 1.04 C (69.18%)
===================
Deployed:  1.40 C
Current:  1.51 C
CAGR/XIRR %: 3.58%

In [9]:
# top 5 near their targets
cols = ['Symbol', 'Today P/L%', 'Current P/L%', 'FTT%', 'OTT%', 'FTT Amt', 'Current P/L', 'Current', 'FTT', 'Dev%_PE', 'RSI_14','Conviction', 'Spread%',  'CumlRnk', 'RRR Ind', 'CurrAlloc%', 'Gained%', 'Criteria', 'Strategy', 'Category']
df_tmp = df_portfolio_features[~df_portfolio_features['Symbol'].isin(['ENRIN','BLUSPRING','DIGITIDE'])]
df_tmp = df_tmp.sort_values(by = 'FTT Amt', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
59,PIDILITIND,0.16,13.36,4.42,18.37,7070.0,18850.0,159960.0,1670.26,-20.60,74.0,X-LC,4.75,5.0,2.67,1.06,25.60,X40,ATH,CHEMICALS
49,JSWINFRA,-2.67,9.31,6.51,16.43,15782.0,20657.0,242431.0,342.00,-6.17,65.0,X-MC,5.60,61.0,1.31,1.61,37.45,X40N,NTT,REALTY
51,KOTAKBANK,-3.30,5.68,14.60,21.11,21365.0,7862.0,146335.0,453.24,-9.41,51.0,X-LC,4.89,12.0,0.37,0.97,11.91,X40,ATH,BANKS
83,TTKPRESTIG,4.42,-22.56,29.25,0.09,22828.0,-22734.0,78043.0,770.00,81.22,70.0,M-SC,8.23,250.0,-1.00,0.52,38.97,OX40N,NTT,DURABLES
72,SIS,0.10,0.10,21.14,21.26,23495.0,110.0,111142.0,528.00,2653.89,63.0,H-SC,25.07,168.0,0.00,0.74,65.25,OX40N,NTT,MISC

In [10]:
# top 5 today
df_tmp = df_portfolio_features.sort_values(by = 'Today P/L%', ascending=False)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
25,FINCABLES,5.62,49.35,39.21,107.91,86462.0,72866.0,220510.0,1641.55,34.45,62.0,M-SC,24.17,220.0,0.84,1.46,65.90,OX40N,ATH,CABLES
83,TTKPRESTIG,4.42,-22.56,29.25,0.09,22828.0,-22734.0,78043.0,770.00,81.22,70.0,M-SC,8.23,250.0,-1.00,0.52,38.97,OX40N,NTT,DURABLES
69,SFL,2.35,-26.93,73.30,26.63,140446.0,-70614.0,191604.0,1287.00,45.10,71.0,M-SC,13.73,242.0,-0.50,1.27,59.69,XY24,NTT,MISC
16,CERA,2.10,-15.49,46.59,23.89,69261.0,-27243.0,148660.0,9475.00,-18.38,65.0,H-SC,9.28,153.0,-0.39,0.99,42.86,OX40N,NTT,CERAMICS
68,SATIN,2.10,30.72,16.16,51.83,58362.0,84864.0,361148.0,274.00,16.95,57.0,H-SC,40.70,159.0,1.45,2.40,75.93,XY24,NTT,FINANCE

In [11]:
# bottom 5 today
df_tmp = df_portfolio_features.sort_values(by = 'Today P/L%', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
3,ALKYLAMINE,-6.23,-28.56,169.53,92.54,122272.0,-28839.0,72124.0,4520.85,-23.56,43.0,H-SC,7.91,142.0,-0.24,0.48,36.96,SR,ATH,CHEMICALS
21,DEN,-6.08,-44.42,155.62,42.07,73054.0,-37520.0,46944.0,75.00,65.80,51.0,M-SC,6.47,235.0,-0.51,0.31,27.68,AR,NTT,ENTERTAINMENT
31,HATHWAY,-5.03,-38.52,181.87,73.29,121562.0,-41880.0,66840.0,31.40,675.36,50.0,H-SC,9.04,171.0,-0.34,0.44,25.59,XR,NTT,ENTERTAINMENT
61,RAJESHEXPO,-5.00,-82.19,462.00,0.07,112844.0,-112752.0,24425.0,518.00,795.20,43.0,L-SC,37.50,268.0,-1.00,0.16,20.63,OX40N,NTT,JEWELLERY
38,HYUNDAI,-3.90,0.62,48.44,49.35,75175.0,952.0,155193.0,2809.30,-18.76,45.0,X-LC,13.18,29.0,0.01,1.03,11.90,X40N,ATH,AUTO

In [12]:
# top 5 to exit based on CumlRnk
df_tmp = df_portfolio_features[~df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])]
df_tmp = df_tmp[(df_tmp['Current P/L%'] > -1) & (df_tmp['Current P/L%'] < 1)].sort_values(by = 'CumlRnk', ascending=False)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
72,SIS,0.1,0.1,21.14,21.26,23495.0,110.0,111142.0,528.0,2653.89,63.0,H-SC,25.07,168.0,0.0,0.74,65.25,OX40N,NTT,MISC

In [13]:
# OX40N stocks to exit
df_tmp = df_portfolio_features[(df_portfolio_features['Symbol'].isin(list_ox40n))].sort_values(by = 'Current P/L%', ascending=False)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
25,FINCABLES,5.62,49.35,39.21,107.91,86462.0,72866.0,220510.0,1641.55,34.45,62.0,M-SC,24.17,220.0,0.84,1.46,65.90,OX40N,ATH,CABLES
72,SIS,0.10,0.10,21.14,21.26,23495.0,110.0,111142.0,528.00,2653.89,63.0,H-SC,25.07,168.0,0.00,0.74,65.25,OX40N,NTT,MISC
16,CERA,2.10,-15.49,46.59,23.89,69261.0,-27243.0,148660.0,9475.00,-18.38,65.0,H-SC,9.28,153.0,-0.39,0.99,42.86,OX40N,NTT,CERAMICS
83,TTKPRESTIG,4.42,-22.56,29.25,0.09,22828.0,-22734.0,78043.0,770.00,81.22,70.0,M-SC,8.23,250.0,-1.00,0.52,38.97,OX40N,NTT,DURABLES
69,SFL,2.35,-26.93,73.30,26.63,140446.0,-70614.0,191604.0,1287.00,45.10,71.0,M-SC,13.73,242.0,-0.50,1.27,59.69,XY24,NTT,MISC

In [14]:
# top 5 to book for rotation
df_tmp = df_portfolio_features[(df_portfolio_features['Current P/L%'] > 20) ].sort_values(by = 'CumlRnk', ascending=False)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
25,FINCABLES,5.62,49.35,39.21,107.91,86462.0,72866.0,220510.0,1641.55,34.45,62.0,M-SC,24.17,220.0,0.84,1.46,65.90,OX40N,ATH,CABLES
68,SATIN,2.10,30.72,16.16,51.83,58362.0,84864.0,361148.0,274.00,16.95,57.0,H-SC,40.70,159.0,1.45,2.40,75.93,XY24,NTT,FINANCE

In [15]:
# top 5 to monitor for exit
df_tmp = df_portfolio_features[~df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])]
df_tmp = df_tmp[(df_tmp['Current P/L%'] > 0) ].sort_values(by = 'Dev%_PE', ascending=False)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
72,SIS,0.10,0.10,21.14,21.26,23495.0,110.0,111142.0,528.00,2653.89,63.0,H-SC,25.07,168.0,0.00,0.74,65.25,OX40N,NTT,MISC
74,STARHEALTH,1.33,13.15,30.14,47.26,95877.0,36981.0,318104.0,761.00,78.49,74.0,H-SC,12.91,173.0,0.39,2.11,39.59,XY24,NTT,INSURANCE
25,FINCABLES,5.62,49.35,39.21,107.91,86462.0,72866.0,220510.0,1641.55,34.45,62.0,M-SC,24.17,220.0,0.84,1.46,65.90,OX40N,ATH,CABLES
68,SATIN,2.10,30.72,16.16,51.83,58362.0,84864.0,361148.0,274.00,16.95,57.0,H-SC,40.70,159.0,1.45,2.40,75.93,XY24,NTT,FINANCE
91,ZYDUSLIFE,1.81,18.24,14.70,35.63,36428.0,38233.0,247807.0,1286.17,2.70,66.0,H-MC,13.98,120.0,1.05,1.64,30.29,AR,ATH,PHARMA

In [16]:
# top 5 to book for rotation from weak conviction
df_tmp = df_portfolio_features[~df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])]
df_tmp = df_tmp[~df_tmp['Criteria'].isin(['XY25','XY24','X40', 'X40N'])].sort_values(by = 'RRR Ind', ascending=False)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
91,ZYDUSLIFE,1.81,18.24,14.70,35.63,36428.0,38233.0,247807.0,1286.17,2.70,66.0,H-MC,13.98,120.0,1.05,1.64,30.29,AR,ATH,PHARMA
25,FINCABLES,5.62,49.35,39.21,107.91,86462.0,72866.0,220510.0,1641.55,34.45,62.0,M-SC,24.17,220.0,0.84,1.46,65.90,OX40N,ATH,CABLES
73,SONACOMS,0.24,7.39,29.15,38.69,31666.0,7472.0,108631.0,801.69,-14.93,62.0,M-MC,17.98,193.0,0.24,0.72,54.12,AR,ATH,AUTO
72,SIS,0.10,0.10,21.14,21.26,23495.0,110.0,111142.0,528.00,2653.89,63.0,H-SC,25.07,168.0,0.00,0.74,65.25,OX40N,NTT,MISC
75,SURYODAY,0.91,-1.14,24.46,23.03,43299.0,-2050.0,177021.0,216.00,92.98,57.0,H-SC,19.76,166.0,-0.05,1.17,49.05,XR,NTT,BANKS

In [17]:
# top 5 to accumulate based on lowest RSI_14
df_tmp = df_portfolio_features[df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])].sort_values(by = 'RSI_14', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
58,PGHH,-2.30,-33.96,99.90,32.01,140867.0,-72512.0,141008.0,17616.87,-55.31,33.0,X-MC,20.85,57.0,-0.51,0.94,0.00,X40,ATH,FMCG
1,ABBOTINDIA,-1.13,-15.14,39.14,18.07,59403.0,-27085.0,151770.0,35195.00,-27.72,34.0,X-MC,6.44,58.0,-0.46,1.01,0.46,X40,ATH,PHARMA
45,INFY,-0.43,-29.43,90.22,34.24,199221.0,-92071.0,220817.0,1972.00,-44.48,36.0,X-LC,17.93,3.0,-0.46,1.46,0.72,X40,NTT,IT
33,HCLTECH,0.15,-28.46,69.84,21.51,120877.0,-68847.0,173077.0,1872.35,-24.73,37.0,X-LC,18.96,8.0,-0.57,1.15,0.15,X40,ATH,IT
26,GILLETTE,-2.05,-10.66,45.20,29.72,102527.0,-27066.0,226830.0,10978.86,-31.36,37.0,X-SC,6.66,83.0,-0.26,1.50,4.24,X40,ATH,FMCG

In [18]:
# top 5 to accumulate based on Spread and CumlRnk
df_tmp = df_portfolio_features[df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])]
df_tmp = df_tmp[(df_tmp['CumlRnk'] < 100)].sort_values(by = 'Spread%', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
11,BERGEPAINT,-3.78,-4.48,31.20,25.32,76812.0,-11557.0,246192.0,680.00,-9.74,51.0,X-MC,2.70,68.0,-0.15,1.63,28.13,XY24,NTT,PAINTS
17,CIPLA,0.97,17.72,13.34,33.43,24053.0,27147.0,180308.0,1648.14,-9.03,69.0,X-LC,3.38,18.0,1.13,1.20,23.09,X40N,ATH,PHARMA
84,UNITDSPR,-3.13,-1.45,22.55,20.77,52031.0,-3406.0,230738.0,1644.00,-12.63,57.0,X-MC,3.92,64.0,-0.07,1.53,10.07,X40N,NTT,BREWERIES
19,COLPAL,0.31,-24.09,84.24,39.86,168413.0,-63445.0,199920.0,3683.41,-8.09,45.0,X-MC,4.09,62.0,-0.38,1.33,13.09,XY25,ATH,FMCG
56,MEDANTA,-0.59,11.61,13.90,27.12,27384.0,20493.0,197010.0,1486.00,8.12,66.0,X-SC,4.19,87.0,0.75,1.31,35.75,XY24,NTT,HEALTHCARE

In [19]:
# top 5 to accumulate based on lowest Gained%
df_tmp = df_portfolio_features[df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])].sort_values(by = 'Gained%', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
58,PGHH,-2.30,-33.96,99.90,32.01,140867.0,-72512.0,141008.0,17616.87,-55.31,33.0,X-MC,20.85,57.0,-0.51,0.94,0.00,X40,ATH,FMCG
33,HCLTECH,0.15,-28.46,69.84,21.51,120877.0,-68847.0,173077.0,1872.35,-24.73,37.0,X-LC,18.96,8.0,-0.57,1.15,0.15,X40,ATH,IT
1,ABBOTINDIA,-1.13,-15.14,39.14,18.07,59403.0,-27085.0,151770.0,35195.00,-27.72,34.0,X-MC,6.44,58.0,-0.46,1.01,0.46,X40,ATH,PHARMA
45,INFY,-0.43,-29.43,90.22,34.24,199221.0,-92071.0,220817.0,1972.00,-44.48,36.0,X-LC,17.93,3.0,-0.46,1.46,0.72,X40,NTT,IT
79,TCS,0.15,-38.41,102.77,24.88,293217.0,-177959.0,285314.0,4253.91,-47.89,38.0,X-LC,20.18,2.0,-0.61,1.89,1.86,X40,ATH,IT

In [20]:
# top 5 to accumulate based on lowest CurrAlloc%
df_tmp = df_portfolio_features[df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])].sort_values(by = 'CurrAlloc%', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
10,BATAINDIA,-2.63,-55.08,201.02,35.20,116175.0,-70877.0,57793.0,2096.00,-24.19,49.0,X-SC,22.17,91.0,-0.61,0.38,14.62,X40,NTT,FOOTWEAR
64,RELAXO,1.04,-45.88,181.44,52.31,142532.0,-66604.0,78556.0,1176.00,-42.41,78.0,X-SC,13.44,92.0,-0.47,0.52,75.64,X40N,NTT,FOOTWEAR
60,QUESS,-1.26,1.69,71.01,73.90,77115.0,1805.0,108598.0,424.00,-45.45,68.0,X-SC,13.02,80.0,0.02,0.72,48.04,XY24,NTT,MISC
28,GODREJCP,-1.23,-8.55,43.76,31.47,59476.0,-12701.0,135913.0,1469.04,-3.82,49.0,X-LC,9.27,32.0,-0.21,0.90,4.28,X40N,ATH,FMCG
53,M&M,-2.80,0.36,22.94,23.38,31929.0,504.0,139185.0,3802.40,-14.78,51.0,X-LC,10.39,25.0,0.02,0.92,5.52,X40N,ATH,AUTO

In [21]:
# top 5 to accumulate based on CumlRnk
df_tmp = df_portfolio_features.sort_values(by = 'CumlRnk', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
47,ITC,0.24,-23.43,55.49,19.06,144533.0,-79699.0,260467.0,452.00,-57.95,52.0,X-LC,14.66,1.0,-0.55,1.73,4.95,X40,NTT,FMCG
79,TCS,0.15,-38.41,102.77,24.88,293217.0,-177959.0,285314.0,4253.91,-47.89,38.0,X-LC,20.18,2.0,-0.61,1.89,1.86,X40,ATH,IT
45,INFY,-0.43,-29.43,90.22,34.24,199221.0,-92071.0,220817.0,1972.00,-44.48,36.0,X-LC,17.93,3.0,-0.46,1.46,0.72,X40,NTT,IT
81,TMPV,-2.31,-21.46,73.89,36.58,206515.0,-76351.0,279490.0,600.00,-83.62,38.0,X-LC,9.51,4.0,-0.37,1.85,17.46,XY24,NTT,AUTO
59,PIDILITIND,0.16,13.36,4.42,18.37,7070.0,18850.0,159960.0,1670.26,-20.60,74.0,X-LC,4.75,5.0,2.67,1.06,25.60,X40,ATH,CHEMICALS

In [22]:
# top 5 for average up
df_tmp = df_portfolio_features[(df_portfolio_features['Dev%_200'] > 5)].sort_values(by = 'CurrAlloc%', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
44,INDUSINDBK,-0.39,-32.42,96.64,32.89,50425.0,-25028.0,52178.0,1800.00,-345.80,51.0,L-MC,6.86,258.0,-0.50,0.35,28.64,XR,NTT,BANKS
64,RELAXO,1.04,-45.88,181.44,52.31,142532.0,-66604.0,78556.0,1176.00,-42.41,78.0,X-SC,13.44,92.0,-0.47,0.52,75.64,X40N,NTT,FOOTWEAR
60,QUESS,-1.26,1.69,71.01,73.90,77115.0,1805.0,108598.0,424.00,-45.45,68.0,X-SC,13.02,80.0,0.02,0.72,48.04,XY24,NTT,MISC
73,SONACOMS,0.24,7.39,29.15,38.69,31666.0,7472.0,108631.0,801.69,-14.93,62.0,M-MC,17.98,193.0,0.24,0.72,54.12,AR,ATH,AUTO
72,SIS,0.10,0.10,21.14,21.26,23495.0,110.0,111142.0,528.00,2653.89,63.0,H-SC,25.07,168.0,0.00,0.74,65.25,OX40N,NTT,MISC

In [23]:
# top 5 RSP
df_tmp = df_portfolio_features.sort_values(by = 'RSP', ascending=False)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
69,SFL,2.35,-26.93,73.30,26.63,140446.0,-70614.0,191604.0,1287.0,45.10,71.0,M-SC,13.73,242.0,-0.50,1.27,59.69,XY24,NTT,MISC
64,RELAXO,1.04,-45.88,181.44,52.31,142532.0,-66604.0,78556.0,1176.0,-42.41,78.0,X-SC,13.44,92.0,-0.47,0.52,75.64,X40N,NTT,FOOTWEAR
60,QUESS,-1.26,1.69,71.01,73.90,77115.0,1805.0,108598.0,424.0,-45.45,68.0,X-SC,13.02,80.0,0.02,0.72,48.04,XY24,NTT,MISC
49,JSWINFRA,-2.67,9.31,6.51,16.43,15782.0,20657.0,242431.0,342.0,-6.17,65.0,X-MC,5.60,61.0,1.31,1.61,37.45,X40N,NTT,REALTY
16,CERA,2.10,-15.49,46.59,23.89,69261.0,-27243.0,148660.0,9475.0,-18.38,65.0,H-SC,9.28,153.0,-0.39,0.99,42.86,OX40N,NTT,CERAMICS

In [24]:
# Top N allocation
df_tmp = df_portfolio_features.sort_values(by = 'CurrAlloc%', ascending=False)
top_n_values = [10, 25, 50]

sum_df = pd.DataFrame({
    'Top_N': top_n_values,
    'Sum_Alloc%': [df_tmp['CurrAlloc%'].head(n).sum() for n in top_n_values]
})

sum_df

   Top_N  Sum_Alloc%
0     10       19.32
1     25       42.67
2     50       72.85

In [25]:
# market-cap-wise allocation
df_tmp = df_portfolio_features[cols]
df_tmp.groupby(df_tmp['Conviction'].str[-2:])['CurrAlloc%'].sum().sort_values(ascending=False)

Conviction
SC    43.70
LC    30.52
MC    25.77
Name: CurrAlloc%, dtype: float64

In [26]:
# criteria-wise allocation
df_portfolio_features.groupby('Criteria')['CurrAlloc%'].sum().sort_values(ascending=False)

Criteria
XY24     27.74
X40      24.56
X40N     17.48
XR        8.82
OX40N     7.28
AR        6.79
XY25      6.49
SR        0.83
Name: CurrAlloc%, dtype: float64

In [27]:
# conviction-wise allocation
df_portfolio_features.groupby('Conviction')['CurrAlloc%'].sum().sort_values(ascending=False)

Conviction
X-LC    28.52
H-SC    22.90
X-MC    20.64
M-SC    10.22
X-SC    10.00
H-MC     2.73
M-MC     2.05
H-LC     1.19
M-LC     0.81
L-SC     0.58
L-MC     0.35
Name: CurrAlloc%, dtype: float64

In [28]:
# sector-wise stats
df_tmp = df_portfolio_features.groupby('Category')[['CurrAlloc%', 'Current', 'Current P/L', 'FTT Amt']].sum().sort_values(by=['Current', 'Current P/L'], ascending=False)
df_tmp['Current P/L%'] = round(df_tmp['Current P/L'] * 100 / df_tmp['Current'], 2)
df_tmp['FTT%'] = round(df_tmp['FTT Amt'] * 100 / df_tmp['Current'], 2)
cols = ['CurrAlloc%', 'Current P/L%', 'FTT%']
df_tmp[cols].sort_values(by=['CurrAlloc%'], ascending=False)

               CurrAlloc%  Current P/L%    FTT%
Category
FMCG                14.55        -20.67   62.99
FINANCE             11.19         -9.28   56.81
IT                   9.60        -55.80  133.70
MISC                 7.23        -23.02   75.80
AUTO                 6.57        -10.43   51.79
BANKS                5.78         -4.25   52.46
PAINTS               5.49        -18.99   39.29
INSURANCE            5.36         -2.48   37.05
PHARMA               5.10          3.56   26.29
ELECTRICAL           4.09        -14.66   55.13
CHEMICALS            2.17        -24.09   97.70
HEALTHCARE           2.10        -13.21   42.76
APPARELS             1.88          5.11   26.76
AC                   1.79        -18.27   50.33
FOOTWEAR             1.78        -64.44  130.37
REALTY               1.61          8.52    6.51
DURABLES             1.61        -59.71   98.56
TRAVEL               1.54        -92.35  188.66
BREWERIES            1.53         -1.48   22.55
CABLES               1.46         33.04   39.21
CERAMICS             1.45        -40.74   83.50
ENGINEERING          1.33        -20.93   76.24
REFINERIES           1.11        -19.74   50.04
CEMENT               1.06        -67.57  192.94
JEWELLERY            1.02       -107.70  179.87
ENTERTAINMENT        0.75        -69.78  171.04
TEXTILES             0.42        -44.32   85.47
HOTELS               0.42        -80.25  143.83

In [29]:
# money to be made criteria-wise
df_portfolio_features.groupby('Criteria')['FTT Amt'].agg(['sum', 'count']).sort_values(by='sum', ascending=False)

                sum  count
Criteria
XY24      3414778.0     21
X40       1976301.0     19
XR        1352451.0     13
AR        1153609.0      9
X40N      1085333.0     13
OX40N      694599.0     10
XY25       458061.0      5
SR         293736.0      2

In [30]:
# money to be made conviction-wise
df_portfolio_features.groupby('Conviction')['FTT Amt'].agg(['sum', 'count']).sort_values(by='sum', ascending=False)

                  sum  count
Conviction
H-SC        3328832.0     24
X-LC        1981394.0     21
X-MC        1607051.0     15
M-SC        1375388.0     14
X-SC        1295359.0      9
H-MC         285866.0      2
L-SC         203450.0      2
M-LC         169938.0      1
M-MC          76246.0      2
H-LC          54919.0      1
L-MC          50425.0      1

In [31]:
# money to be made criteria and conviction-wise
df_portfolio_features.groupby(['Conviction', 'Criteria'])['FTT Amt'].agg(['sum', 'count']).sort_values(by='sum', ascending=False)

                           sum  count
Conviction Criteria
X-LC       X40       1063738.0     10
H-SC       XY24       976764.0      6
           AR         957542.0      5
M-SC       XY24       822568.0      6
H-SC       XR         808955.0      7
X-SC       XY24       784185.0      4
X-MC       X40        693861.0      7
           X40N       434227.0      4
X-LC       X40N       358634.0      6
           XY24       355299.0      2
H-SC       SR         293736.0      2
X-SC       X40N       292472.0      3
H-SC       OX40N      291835.0      4
M-SC       OX40N      289920.0      5
X-MC       XY25       252439.0      2
H-MC       XY24       249438.0      1
X-MC       XY24       226524.0      2
X-SC       X40        218702.0      2
M-SC       XR         189846.0      2
M-LC       XR         169938.0      1
X-LC       XY25       161042.0      2
L-SC       OX40N      112844.0      1
           XR          90606.0      1
M-SC       AR          73054.0      1
H-LC       AR          54919.0      1
L-MC       XR          50425.0      1
M-MC       XY25        44580.0      1
X-LC       XR          42681.0      1
H-MC       AR          36428.0      1
M-MC       AR          31666.0      1

In [32]:
# notebook execution time

end_time = time.time()
execution_time = round(end_time - start_time, 0)
print(f"Notebook execution time: {execution_time} seconds")

Notebook execution time: 28.0 seconds