<a href="https://colab.research.google.com/github/ankit-rathi/Quantvesting_v2/blob/main/myStocks_Portfolio_Analysis.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
'''
!pip install pandas==2.2.2 -qq
!pip install pyxirr -qq
!pip install ta -qq
!pip install yfinance==0.2.59 -qq
'''

'\n!pip install pandas==2.2.2 -qq\n!pip install pyxirr -qq\n!pip install ta -qq\n!pip install yfinance==0.2.59 -qq\n'

In [2]:
# import libraries

import numpy as np
import pandas as pd
import datetime
import warnings
warnings.filterwarnings('ignore')
import yfinance as yfin
import ta
import matplotlib.pyplot as plt
import requests

In [3]:
# notebook start time
import time
import datetime
import pytz

start_time = time.time()

# function to print date timestamp
def print_date_time():
  tz_NY = pytz.timezone('Asia/Kolkata')
  datetime_NY = datetime.datetime.now(tz_NY)
  print("Run date time (IST):", datetime_NY.strftime("%Y-%m-%d %H:%M:%S"))

In [4]:
# function to get booked and reserved amount
def get_amt():
  # fetch the JSON data from the URL
  url = "https://raw.githubusercontent.com/ankit-rathi/Tradevesting_v1/main/data/myPortfolioAmts.json"
  response = requests.get(url)
  pf_amts = response.json()  # parse the JSON data

  # extract values from the JSON
  py_booked_amt_dm = pf_amts["py_booked_amt_dm"]
  py_booked_amt_sv = pf_amts["py_booked_amt_sv"]
  cy_booked_amt_dm = pf_amts["cy_booked_amt_dm"]
  cy_booked_amt_sv = pf_amts["cy_booked_amt_sv"]
  reserve_amt_dm = pf_amts["reserve_amt_dm"]
  reserve_amt_sv = pf_amts["reserve_amt_sv"]

  # perform calculations
  py_booked_amt = py_booked_amt_dm + py_booked_amt_sv
  cy_booked_amt = cy_booked_amt_dm + cy_booked_amt_sv
  reserve_amt = reserve_amt_dm + reserve_amt_sv
  total_booked_amt = py_booked_amt + cy_booked_amt

  return total_booked_amt, reserve_amt, cy_booked_amt, py_booked_amt

gen_output = 0

In [5]:
# function to format the amount
def format_amt(number):
    abs_number = abs(number)

    if abs_number >= 1_00_00_000:  # Crores
        formatted_amt = f"{number / 1_00_00_000:.2f} C"
    elif abs_number >= 1_00_000:  # Lakhs
        formatted_amt = f"{number / 1_00_000:.2f} L"
    elif abs_number >= 1_000:  # Thousands
        formatted_amt = f"{number / 1_000:.2f} K"
    else:
        formatted_amt = f"{number:.2f}"

    return formatted_amt

# function to set start and end date
def get_start_end_date():
  start_date = (datetime.date.today() + datetime.timedelta(days=-365)).strftime('%Y-%m-%d')
  end_date = (datetime.date.today() + datetime.timedelta(days=1)).strftime('%Y-%m-%d')
  return start_date, end_date

# function to fetch my portfolio csv
def get_mypfs_df():
  mypfs_df = pd.read_csv('https://raw.githubusercontent.com/ankit-rathi/Tradevesting_v1/main/data/myPortfolioStocks.csv')
  return mypfs_df

# function to fetch my prospects csv
def get_mypps_df():
  mypps_df = pd.read_csv('https://raw.githubusercontent.com/ankit-rathi/Tradevesting_v1/main/data/myProspectsScrips.csv')
  return mypps_df

# function to fetch screener data
def get_myscreen_df():
  myscreen_df = pd.read_csv('https://raw.githubusercontent.com/ankit-rathi/Tradevesting_v1/main/data/myScreenerDB.csv')
  return myscreen_df

# function to fetch momentum data
def get_myinvmt_df():
  myinvmt_df = pd.read_csv('https://raw.githubusercontent.com/ankit-rathi/Tradevesting_v1/main/data/myInvestments.csv')
  return myinvmt_df

# function to get the stock ids
def get_stock_ids(df_pf):
  stock_n100 = df_pf['Symbol'].unique()

  exclude = ['CADILAHC','MMTC', 'MASFIN']

  stock_ids = df_pf[~df_pf['Symbol'].isin(exclude) ]['Symbol'].unique()

  #mypf = mypf[mypf.Forecast.notnull()]
  #stock_ids = mypf['Symbol'].unique()

  #stock_ids.sort()
  return stock_ids

# get features from screener data
def get_screener_features():
  myscreen_df = get_myscreen_df()
  cols = ['Symbol', 'EPS', 'MedPE', 'ROCE%', 'ROE%', 'CapType']
  return myscreen_df[cols]

# get relative strength
def get_relative_strength(stock_list):

    # Dictionary to store stock tickers and their corresponding percentage price change
    stock_changes = {}

    # Loop through each stock and fetch its price data
    for stock in stock_list:
        try:
            # Download the stock data for the given date range
            stock_data = yfin.Ticker(stock + '.NS').history(period='1mo', interval='1d')[map(str.title, ['open', 'close', 'low', 'high', 'volume'])]

            # Calculate the percentage change for the stock
            if len(stock_data) > 0:
                start_price = stock_data['Close'].iloc[0]
                end_price = stock_data['Close'].iloc[-1]
                percent_change = round(((end_price - start_price) / start_price) * 100, 2)
                stock_changes[stock] = percent_change
            else:
                stock_changes[stock] = np.nan  # If no data is available, set to NaN

        except Exception as e:
            print(f"Error fetching data for {stock}: {e}")
            stock_changes[stock] = np.nan

    # Create a DataFrame with stock tickers and their percentage changes
    df = pd.DataFrame(list(stock_changes.items()), columns=['Symbol', 'Percent_Change'])

    # Drop any stocks with missing data (NaN values)
    df = df.dropna()

    # Calculate the percentile rank based on percentage change
    df['RSP'] = round(df['Percent_Change'].rank(pct=True) * 100, 2)
    cols = ['Symbol', 'RSP']
    df = df[cols]
    # Sort by percentile rank (optional)
    df = df.sort_values(by='RSP', ascending=False).reset_index(drop=True)

    return df

In [6]:
# function to get stock technicals
def stock_prec_dev(stock_symbol):
    #stock_symbol = 'ULTRACEMCO.NS'
    short_window = 20
    mid_window = 50
    long_window = 200
    moving_avg = 'SMA'

    start = datetime.datetime(*map(int, start_date.split('-')))
    end = datetime.datetime(*map(int, end_date.split('-')))

    stock_df = yfin.Ticker(stock_symbol + '.NS').history(period='max', interval='1d')[map(str.title, ['open', 'close', 'low', 'high', 'volume'])]

    stock_df['Max'] = round(max(stock_df['Close']),2)
    stock_df = stock_df[(stock_df.index <= end_date) & (stock_df.index >= start_date)]
    stock_df['200_SMA'] = round(stock_df['Close'].rolling(window = 200, min_periods = 1).mean(),0)
    stock_df['Dev%_200'] = round((stock_df['Close'] - stock_df['200_SMA'])*100/stock_df['200_SMA'],2)
    stock_df.dropna(axis = 0, inplace = True) # remove any null rows

    stock_df['20_SMA'] = stock_df['Close'].rolling(window=20).mean()
    stock_df['50_SMA'] = stock_df['Close'].rolling(window=50).mean()
    stock_df['Symbol'] = stock_symbol

    stock_df['Close'] = round(stock_df['Close'],2)
    stock_df['Min'] = round(min(stock_df['Close']),2)
    stock_df['RSI_14'] = ta.momentum.RSIIndicator(close=stock_df['Close'], window=14).rsi()
    stock_df['RSI_14'] = round(stock_df['RSI_14'],0)
    stock_df['Prev_Close'] = stock_df['Close'].shift(1)
    stock_df.drop(['Open', 'Low', 'High', 'Volume'], axis=1, inplace=True)
    stock_df = stock_df.tail(1)

    max_SMA = max(stock_df['20_SMA'].item(), stock_df['50_SMA'].item(), stock_df['200_SMA'].item())
    min_SMA = min(stock_df['20_SMA'].item(), stock_df['50_SMA'].item(), stock_df['200_SMA'].item())
    ABS_Spread = max_SMA - min_SMA
    stock_df['Spread%'] = round((ABS_Spread / stock_df['200_SMA'].item()) * 100,2)

    return stock_df

# function to compute stock attributes
def get_common_features(stock_ids, df_mypf):

  df_prec_dev = pd.DataFrame()
  df_tmp = get_screener_features()
  df_rs = get_relative_strength(stock_ids)

  for stock_id in stock_ids:
      tmp = stock_prec_dev(stock_id)
      tmp = tmp.reset_index()
      df_prec_dev = pd.concat([df_prec_dev, tmp], ignore_index = True)
  df_prec_dev = pd.merge(df_prec_dev, df_mypf, on= 'Symbol')
  df_prec_dev = pd.merge(df_prec_dev, df_tmp, on= 'Symbol', how='left')
  df_prec_dev = pd.merge(df_prec_dev, df_rs, on= 'Symbol', how='left')
  #print(df_prec_dev.columns)
  df_prec_dev['Curr_PE'] = round(df_prec_dev['Close']/df_prec_dev['EPS'],1)
  df_prec_dev['Dev%_PE'] = round((df_prec_dev['Curr_PE'] - df_prec_dev['MedPE'])*100/df_prec_dev['MedPE'],2)
  df_prec_dev['Conviction'] = df_prec_dev['Conviction'] + '-' + df_prec_dev['CapType']
  return df_prec_dev

# function to arrange stock features
def arrange_features(df_stocks, common_cols, diff_cols):
  df_stocks_common = df_stocks[common_cols].drop_duplicates()
  df_stocks_diff = df_stocks[diff_cols]
  df_stocks_diff['Investment'] = df_stocks_diff['AvgCost'] * df_stocks_diff['Shares']
  df_stocks_diff = df_stocks_diff.groupby(['Symbol'])[['Shares', 'Investment']].aggregate(['sum']).reset_index()
  df_stocks_diff.columns = ['Symbol', 'Shares', 'Investment']
  df_stocks_diff['AvgCost'] = round(df_stocks_diff['Investment']/df_stocks_diff['Shares'],2)
  df_stocks = pd.merge(df_stocks_diff, df_stocks_common, on='Symbol')
  return df_stocks

# plot fact distribution across dimension
def plot_pie_chart(df, dimension, fact):
  # grouping the data by category and calculating the sum of fact for each type
  grouped_data = df.groupby(dimension)[fact].sum()

  # sorting the grouped data in descending order
  grouped_data = grouped_data.sort_values(ascending=False)

  # creating a pie chart
  grouped_data.plot.pie(autopct='%1.1f%%', startangle=90, figsize=(6, 6))

  # adding a title and displaying the plot
  plt.title(f'{dimension} {fact} Distribution')
  plt.ylabel('')  # To hide the y-label
  plt.show()

In [7]:
# function to get portfolio features

def get_portfolio_features(df_common_features):

  print_date_time()
  print('-------------------')

  #df_common_features["Target"] = df_common_features["Target"].fillna(df_common_features["Max"])
  df_common_features['NTT'] = np.where(df_common_features['Strategy']== 'NTT', df_common_features["Target"], df_common_features['Max'])
  df_common_features['LTT'] = np.where(df_common_features['Strategy']== 'BTT', df_common_features["Target"], df_common_features['Max'])
  df_common_features['BOL'] = df_common_features['Min']

  tmp_df = df_common_features[df_common_features['Symbol'].isin(mypf_df[mypf_df['InPortfolio'] != 'NA'].Symbol.values)]
  print('qualified stocks: '+str(len(tmp_df['Symbol'].unique())))
  tmp_df1 = tmp_df[tmp_df['LatestQtr'] == 1]
  print('with latest results: '+str(len(tmp_df1['Symbol'].unique())))
  tmp_df1 = tmp_df1[tmp_df1['StarStock'] == 1]
  print('still star stocks: '+str(len(tmp_df1['Symbol'].unique())))
  tmp_df['Investment'] = tmp_df['AvgCost'] * tmp_df['Shares']
  tmp_df['Current'] = round(tmp_df['Close'] * tmp_df['Shares'],0)
  tmp_df['Previous'] = tmp_df['Prev_Close'] * tmp_df['Shares']
  tmp_df['EstimatedST'] = tmp_df['NTT'] * tmp_df['Shares']
  tmp_df['EstimatedLT'] = tmp_df['LTT'] * tmp_df['Shares']
  tmp_df['Current P/L'] = round((tmp_df['Current'] - tmp_df['Investment']),0)
  tmp_df['Today P/L%'] = round((tmp_df['Current'] - tmp_df['Previous'])*100/tmp_df['Previous'],2)
  tmp_df['Current P/L%'] = round((tmp_df['Current'] - tmp_df['Investment'])*100/tmp_df['Investment'],2)
  tmp_df['EstimatedST P/L%'] = round((tmp_df['EstimatedST'] - tmp_df['Investment'])*100/tmp_df['Investment'],2)
  tmp_df['EstimatedLT P/L%'] = round((tmp_df['EstimatedLT'] - tmp_df['Investment'])*100/tmp_df['Investment'],2)
  tmp_df['NTT%'] = round((tmp_df['NTT'] - tmp_df['Close'])*100/tmp_df['Close'],2)
  tmp_df['LTT%'] = round((tmp_df['LTT'] - tmp_df['Close'])*100/tmp_df['Close'],2)
  tmp_df['Gained%'] = round((tmp_df['Close'] - tmp_df['BOL'])*100/tmp_df['BOL'],2)
  investment = round(sum(tmp_df['AvgCost']*tmp_df['Shares']),0)
  current = round(sum(tmp_df['Close']*tmp_df['Shares']),0)
  tmp_df['InitAlloc%'] = round(tmp_df['Investment']*100/investment,2)
  tmp_df['CurrAlloc%'] = round(tmp_df['Current']*100/current,2)
  tmp_df['FTT'] = tmp_df['LTT']
  tmp_df.loc[tmp_df['Strategy'] == 'NTT', 'FTT'] = tmp_df['NTT']
  tmp_df['FTT%'] = tmp_df['LTT%']
  tmp_df.loc[tmp_df['Strategy'] == 'NTT', 'FTT%'] = tmp_df['NTT%']
  tmp_df['FTT Amt'] = round(tmp_df['FTT%'] * tmp_df['Current']/100,0)
  tmp_df['OTT%'] = round((tmp_df['FTT'] - tmp_df['AvgCost'])*100/tmp_df['AvgCost'],2)
  tmp_df['RRR Ind'] = round(tmp_df['Current P/L']/tmp_df['FTT Amt'],2)
  tmp_df['Risk Ind'] = round(tmp_df['Current P/L%']*tmp_df['CurrAlloc%'],0)

  return tmp_df

# function to print portfolio features
def print_portfolio_stats(df_portfolio_features, myinvmt_df):
  from pyxirr import xirr

  total_booked_amt, reserve_amt, cy_booked_amt, py_booked_amt = get_amt()

  dates = myinvmt_df['Date'].values
  dates = np.append(dates, datetime.date.today().strftime('%d-%b-%y'))
  investment = myinvmt_df['Investment'].values
  dates= pd.to_datetime(dates)

  current = round(sum(df_portfolio_features['Close']*df_portfolio_features['Shares']),0) + reserve_amt
  investment_xirr = np.append(investment, current)
  cagr = round(xirr(pd.DataFrame({"dates": dates, "amounts": investment_xirr}))*100,2)

  investment = -sum(investment)
  invested = round(sum(df_portfolio_features['AvgCost']*df_portfolio_features['Shares']),0) + reserve_amt
  previous = round(sum(df_portfolio_features['Prev_Close']*df_portfolio_features['Shares']),0) + reserve_amt
  cy_invested = investment + py_booked_amt

  today_pnl_amount = current-previous
  today_pnl_percentage = round((current-previous)*100/previous,2)

  curr_pnl_amount = current-invested
  curr_pnl_percentage = round((curr_pnl_amount)*100/(cy_invested),2)

  cy_pnl_amount = cy_booked_amt + curr_pnl_amount
  cy_pnl_percentage = round((cy_pnl_amount)*100/cy_invested,2)

  overall_pnl_amount = total_booked_amt + curr_pnl_amount
  overall_pnl_percentage = round((overall_pnl_amount)*100/investment,2)

  estimate_st = round(sum(df_portfolio_features['FTT']*df_portfolio_features['Shares']),0)  + reserve_amt
  est_st_pnl_amount = estimate_st-current
  est_st_pnl_percentage = round((est_st_pnl_amount)*100/current,2)

  estimate_lt = round(sum(df_portfolio_features['LTT']*df_portfolio_features['Shares']),0)  + reserve_amt
  est_lt_pnl_amount = estimate_lt-current
  est_lt_pnl_percentage = round((est_lt_pnl_amount)*100/current,2)

  total_profit = round(sum(df_portfolio_features[df_portfolio_features['Current P/L%'] > 0]['Current']) - sum(df_portfolio_features[df_portfolio_features['Current P/L%'] > 0]['Investment']),0)
  total_loss = round(sum(df_portfolio_features[df_portfolio_features['Current P/L%'] < 0]['Current']) - sum(df_portfolio_features[df_portfolio_features['Current P/L%'] < 0]['Investment']),0)

  cy_booked_percentage = round((cy_booked_amt)*100/current,2)
  py_booked_percentage = round((py_booked_amt)*100/investment,2)
  total_booked_percentage = round((total_booked_amt)*100/investment,2)

  print('-------------------')
  print('Initial Investment: ', format_amt(investment))
  print('CY Investment: ', format_amt(cy_invested))
  print('Reserve: ', format_amt(reserve_amt))
  print('Current: ',  format_amt(current))
  print('-------------------')
  print('Today PnL: '+ '{} ({}%)'.format(format_amt(today_pnl_amount), today_pnl_percentage))
  print('Current PnL: '+ '{} ({}%)'.format(format_amt(curr_pnl_amount), curr_pnl_percentage))
  print('CY Booked + Current PnL: '+ '{} ({}%)'.format(format_amt(cy_pnl_amount), cy_pnl_percentage))
  print('-------------------')
  print('Total profit: ', format_amt(total_profit))
  print('Total loss: ', format_amt(total_loss))
  print('-------------------')
  print('Total Booked + Current PnL: '+ '{} ({}%)'.format(format_amt(overall_pnl_amount), overall_pnl_percentage))
  print('Total Booked PnL: '+ '{} ({}%)'.format(format_amt(total_booked_amt), total_booked_percentage))
  print('Curr Year Booked PnL: '+ '{} ({}%)'.format(format_amt(cy_booked_amt), cy_booked_percentage))
  print('Prev Year Booked PnL: '+ '{} ({}%)'.format(format_amt(py_booked_amt), py_booked_percentage))
  print('===================')
  print('Est FTT: ',  format_amt(estimate_st))
  print('Est FTT PnL: '+ '{} ({}%)'.format(format_amt(est_st_pnl_amount), est_st_pnl_percentage))

  print('===================')
  print('Deployed: ', format_amt(investment))

  print('Current: ', format_amt(current))

  print('CAGR/XIRR %: '+'{}%'.format(cagr))

In [8]:
# get start and end date
start_date, end_date = get_start_end_date()

# get portfolio and prospects data
mypfs_df = get_mypfs_df()
mypps_df = get_mypps_df()
myinvmt_df = get_myinvmt_df()

# merge above datasets
mypf_df = pd.merge(mypfs_df, mypps_df, on="Symbol")

# seggregate dm and sv portfolio
dm_pf = mypf_df[mypf_df['InPortfolio'] == 'DM']
sv_pf = mypf_df[mypf_df['InPortfolio'] == 'SV']

# build portfolio stock dataframe
dm_stocks = get_stock_ids(dm_pf)
sv_stocks = get_stock_ids(sv_pf)
df_stocks = pd.concat([dm_pf,sv_pf], ignore_index = True)

# arrange common and diff stock features
common_cols = ['Symbol', 'Target', 'Criteria', 'Strategy', 'CumlRnk', 'LatestQtr', 'StarStock', 'Conviction', 'Category', 'InFolio', 'XIRR', 'MBQ']
diff_cols = ['Symbol', 'AvgCost', 'Shares']
df_stocks = arrange_features(df_stocks, common_cols, diff_cols)

# get common features
stock_ids = df_stocks['Symbol'].values
df_common_features = get_common_features(stock_ids, df_stocks)

df_common_features.reset_index(drop=True, inplace=True)
df_common_features.drop(['Date'], axis=1, inplace=True)
# get and print portfolio features
df_portfolio_features = get_portfolio_features(df_common_features)

print_portfolio_stats(df_portfolio_features, myinvmt_df)

df = df_portfolio_features
#plot_pie_chart(df, 'CapType', 'Current')
list_ox40n = list(df[df['MBQ'].str.contains('OX40N', na=False)]['Symbol'].values)

Run date time (IST): 2026-08-25 15:21:28
-------------------
qualified stocks: 87
with latest results: 30
still star stocks: 19
-------------------
Initial Investment:  1.46 C
CY Investment:  1.89 C
Reserve:  3.69 L
Current:  1.57 C
-------------------
Today PnL: -41.64 K (-0.26%)
Current PnL: -35.57 L (-18.83%)
CY Booked + Current PnL: -30.51 L (-16.15%)
-------------------
Total profit:  3.65 L
Total loss:  -39.21 L
-------------------
Total Booked + Current PnL: 12.36 L (8.46%)
Total Booked PnL: 47.93 L (32.82%)
Curr Year Booked PnL: 5.06 L (3.22%)
Prev Year Booked PnL: 42.87 L (29.35%)
===================
Est FTT:  2.67 C
Est FTT PnL: 1.10 C (69.7%)
===================
Deployed:  1.46 C
Current:  1.57 C
CAGR/XIRR %: 3.36%

In [9]:
# top 5 near their targets
cols = ['Symbol', 'Today P/L%', 'Current P/L%', 'FTT%', 'OTT%', 'FTT Amt', 'Current P/L', 'Current', 'FTT', 'Dev%_PE', 'RSI_14','Conviction', 'Spread%',  'CumlRnk', 'RRR Ind', 'CurrAlloc%', 'Gained%', 'Criteria', 'Strategy', 'Category']
df_tmp = df_portfolio_features[~df_portfolio_features['Symbol'].isin(['ENRIN','BLUSPRING','DIGITIDE'])]
df_tmp = df_tmp.sort_values(by = 'FTT Amt', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
66,SIEMENS,-1.07,9.35,1.35,10.83,2747.0,17405.0,203500.0,4125.00,-11.49,66.0,H-LC,15.20,51.0,6.34,1.32,43.58,AR,NTT,ELECTRICAL
78,UNITDSPR,-0.77,13.42,6.48,20.77,17209.0,31424.0,265568.0,1644.00,-3.33,62.0,X-MC,12.12,64.0,1.83,1.73,27.66,X40N,NTT,BREWERIES
77,TTKPRESTIG,0.61,-22.62,29.36,0.09,22894.0,-22799.0,77978.0,770.00,-5.78,44.0,M-SC,8.58,250.0,-1.00,0.51,40.35,OX40N,NTT,DURABLES
52,M&M,0.76,8.63,9.39,18.82,24549.0,20759.0,261440.0,3762.88,-6.15,60.0,X-LC,5.15,25.0,0.85,1.70,18.59,X40N,ATH,AUTO
67,SIS,-0.84,-4.86,27.46,21.26,29007.0,-5398.0,105634.0,528.00,102.74,39.0,H-SC,20.04,168.0,-0.19,0.69,57.06,OX40N,NTT,MISC

In [10]:
# top 5 today
df_tmp = df_portfolio_features.sort_values(by = 'Today P/L%', ascending=False)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
18,COFFEEDAY,4.16,-48.78,164.11,35.27,95441.0,-55392.0,58157.0,80.00,NaN,47.0,NaN,3.25,266.0,-0.58,0.38,43.42,XR,NTT,HOTELS
6,AWL,3.47,-30.92,141.77,67.02,348947.0,-110173.0,246136.0,485.00,-48.98,65.0,X-SC,7.70,81.0,-0.32,1.60,17.04,XY24,NTT,FMCG
22,DIXON,2.40,8.69,26.90,37.92,76251.0,22663.0,283461.0,18931.72,-58.66,66.0,X-MC,16.98,54.0,0.30,1.84,54.23,X40N,ATH,IT
82,VBL,1.76,-11.74,53.70,35.66,166764.0,-41297.0,310547.0,669.42,-27.82,43.0,X-LC,6.77,13.0,-0.25,2.02,14.34,X40N,ATH,FMCG
27,GLAXO,1.41,19.35,13.70,35.69,32584.0,38556.0,237840.0,3380.16,-10.44,72.0,X-MC,12.85,56.0,1.18,1.55,41.36,X40,ATH,PHARMA

In [11]:
# bottom 5 today
df_tmp = df_portfolio_features.sort_values(by = 'Today P/L%', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
69,SURYODAY,-4.94,-13.99,43.05,23.03,66306.0,-25051.0,154020.0,216.0,-29.23,37.0,H-SC,14.83,166.0,-0.38,1.00,30.74,XR,NTT,BANKS
12,BOSCH-HCIL,-3.50,-27.05,37.06,-0.01,34555.0,-34565.0,93240.0,2282.0,724.95,61.0,M-SC,11.91,231.0,-1.00,0.61,58.71,OX40N,BTT,AC
70,SYMPHONY,-2.86,-54.46,119.50,-0.03,93144.0,-93196.0,77945.0,1306.0,NaN,27.0,NaN,17.21,205.0,-1.00,0.51,0.00,OX40N,NTT,DURABLES
29,GREENPANEL,-2.80,-58.29,243.20,43.14,185700.0,-106721.0,76357.0,537.0,NaN,23.0,NaN,13.61,225.0,-0.57,0.50,0.00,XY24,NTT,MISC
13,BSOFT,-2.78,-47.30,181.94,48.59,134868.0,-66525.0,74128.0,819.6,NaN,38.0,NaN,16.69,172.0,-0.49,0.48,8.37,XR,ATH,IT

In [12]:
# top 5 to exit based on CumlRnk
df_tmp = df_portfolio_features[~df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])]
df_tmp = df_tmp[(df_tmp['Current P/L%'] > -1) & (df_tmp['Current P/L%'] < 1)].sort_values(by = 'CumlRnk', ascending=False)
df_tmp[cols].head()

Empty DataFrame
Columns: [Symbol, Today P/L%, Current P/L%, FTT%, OTT%, FTT Amt, Current P/L, Current, FTT, Dev%_PE, RSI_14, Conviction, Spread%, CumlRnk, RRR Ind, CurrAlloc%, Gained%, Criteria, Strategy, Category]
Index: []

In [13]:
# OX40N stocks to exit
df_tmp = df_portfolio_features[(df_portfolio_features['Symbol'].isin(list_ox40n))].sort_values(by = 'Current P/L%', ascending=False)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
25,FINCABLES,-2.58,59.37,30.46,107.91,71673.0,87658.0,235302.0,1641.55,16.37,62.0,M-SC,24.90,220.0,1.22,1.53,77.03,OX40N,ATH,CABLES
67,SIS,-0.84,-4.86,27.46,21.26,29007.0,-5398.0,105634.0,528.00,102.74,39.0,H-SC,20.04,168.0,-0.19,0.69,57.06,OX40N,NTT,MISC
43,INDIGOPNTS,-1.53,-19.43,24.14,0.02,33951.0,-33918.0,140641.0,1408.00,-23.14,56.0,M-SC,8.33,222.0,-1.00,0.92,59.57,OX40N,NTT,PAINTS
77,TTKPRESTIG,0.61,-22.62,29.36,0.09,22894.0,-22799.0,77978.0,770.00,-5.78,44.0,M-SC,8.58,250.0,-1.00,0.51,40.35,OX40N,NTT,DURABLES
16,CERA,-1.16,-24.20,63.43,23.89,84579.0,-42561.0,133342.0,9475.00,NaN,40.0,NaN,12.91,153.0,-0.50,0.87,29.62,OX40N,NTT,CERAMICS

In [14]:
# top 5 to book for rotation
df_tmp = df_portfolio_features[(df_portfolio_features['Current P/L%'] > 20) ].sort_values(by = 'CumlRnk', ascending=False)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
25,FINCABLES,-2.58,59.37,30.46,107.91,71673.0,87658.0,235302.0,1641.55,16.37,62.0,M-SC,24.9,220.0,1.22,1.53,77.03,OX40N,ATH,CABLES

In [15]:
# top 5 to monitor for exit
df_tmp = df_portfolio_features[~df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])]
df_tmp = df_tmp[(df_tmp['Current P/L%'] > 0) ].sort_values(by = 'Dev%_PE', ascending=False)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
25,FINCABLES,-2.58,59.37,30.46,107.91,71673.0,87658.0,235302.0,1641.55,16.37,62.0,M-SC,24.90,220.0,1.22,1.53,77.03,OX40N,ATH,CABLES
68,STARHEALTH,0.95,13.01,30.31,47.26,96294.0,36573.0,317696.0,761.00,-0.37,51.0,H-SC,15.69,173.0,0.38,2.07,37.36,XY24,NTT,INSURANCE

In [16]:
# top 5 to book for rotation from weak conviction
df_tmp = df_portfolio_features[~df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])]
df_tmp = df_tmp[~df_tmp['Criteria'].isin(['XY25','XY24','X40', 'X40N'])].sort_values(by = 'RRR Ind', ascending=False)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
25,FINCABLES,-2.58,59.37,30.46,107.91,71673.0,87658.0,235302.0,1641.55,16.37,62.0,M-SC,24.90,220.0,1.22,1.53,77.03,OX40N,ATH,CABLES
3,ALKYLAMINE,0.84,-11.84,118.40,92.54,105388.0,-11953.0,89010.0,4520.85,NaN,68.0,NaN,16.27,142.0,-0.11,0.58,69.02,SR,ATH,CHEMICALS
67,SIS,-0.84,-4.86,27.46,21.26,29007.0,-5398.0,105634.0,528.00,102.74,39.0,H-SC,20.04,168.0,-0.19,0.69,57.06,OX40N,NTT,MISC
42,INDIAMART,0.18,-24.84,167.31,100.92,155100.0,-30634.0,92702.0,4675.60,NaN,39.0,NaN,13.31,140.0,-0.20,0.60,0.85,AR,ATH,MISC
71,TANLA,-1.63,-37.25,246.24,117.25,418340.0,-100870.0,169891.0,1922.32,NaN,40.0,NaN,14.58,147.0,-0.24,1.11,48.74,AR,ATH,IT

In [17]:
# top 5 to accumulate based on lowest RSI_14
df_tmp = df_portfolio_features[df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])].sort_values(by = 'RSI_14', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
56,PGHH,-0.41,-39.34,117.64,32.01,152358.0,-84008.0,129512.0,17616.87,-55.45,23.0,X-SC,20.06,57.0,-0.55,0.84,0.00,X40,ATH,FMCG
20,DABUR,-1.12,-22.97,86.55,43.70,165388.0,-56978.0,191090.0,735.00,-33.61,30.0,X-MC,10.78,70.0,-0.34,1.24,0.00,XY24,BTT,FMCG
55,PAGEIND,0.06,-7.41,43.48,32.85,108048.0,-19879.0,248500.0,50936.07,-31.21,30.0,X-MC,8.50,55.0,-0.18,1.62,18.66,X40,ATH,APPARELS
19,COLPAL,-1.03,-29.01,97.03,39.86,181398.0,-76415.0,186950.0,3683.41,-14.08,30.0,X-MC,2.87,62.0,-0.42,1.22,5.75,XY25,ATH,FMCG
75,TMPV,-0.27,-25.40,91.36,42.75,283594.0,-105693.0,310414.0,600.00,-84.91,31.0,X-LC,4.47,4.0,-0.37,2.02,6.74,XY24,NTT,AUTO

In [18]:
# top 5 to accumulate based on Spread and CumlRnk
df_tmp = df_portfolio_features[df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])]
df_tmp = df_tmp[(df_tmp['CumlRnk'] < 100)].sort_values(by = 'Spread%', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
50,KOTAKBANK,-0.46,5.38,12.85,18.92,32459.0,12896.0,252598.0,452.46,-11.03,60.0,X-LC,2.11,12.0,0.40,1.64,13.65,X40,ATH,BANKS
1,ABBOTINDIA,0.26,-11.13,29.82,15.37,47396.0,-19915.0,158940.0,34390.26,-27.58,41.0,X-MC,2.25,58.0,-0.42,1.03,7.66,X40,ATH,PHARMA
23,DMART,-0.86,-4.79,38.03,31.42,112897.0,-14926.0,296864.0,5391.45,-20.15,41.0,X-LC,2.31,14.0,-0.13,1.93,7.13,X40N,ATH,FMCG
19,COLPAL,-1.03,-29.01,97.03,39.86,181398.0,-76415.0,186950.0,3683.41,-14.08,30.0,X-MC,2.87,62.0,-0.42,1.22,5.75,XY25,ATH,FMCG
53,MARUTI,0.41,-0.83,25.69,24.64,62986.0,-2060.0,245178.0,17120.06,-6.59,45.0,X-LC,3.80,33.0,-0.03,1.60,11.80,XR,ATH,AUTO

In [19]:
# top 5 to accumulate based on lowest Gained%
df_tmp = df_portfolio_features[df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])].sort_values(by = 'Gained%', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
20,DABUR,-1.12,-22.97,86.55,43.70,165388.0,-56978.0,191090.0,735.00,-33.61,30.0,X-MC,10.78,70.0,-0.34,1.24,0.00,XY24,BTT,FMCG
56,PGHH,-0.41,-39.34,117.64,32.01,152358.0,-84008.0,129512.0,17616.87,-55.45,23.0,X-SC,20.06,57.0,-0.55,0.84,0.00,X40,ATH,FMCG
36,HINDUNILVR,-0.39,-15.88,44.51,21.56,125999.0,-53437.0,283080.0,2922.00,-41.98,39.0,X-LC,6.98,9.0,-0.42,1.84,0.35,XY25,NTT,FMCG
34,HDFCBANK,-0.69,-11.57,48.20,31.05,124931.0,-33928.0,259192.0,1073.00,-28.50,37.0,X-LC,12.61,26.0,-0.27,1.69,0.60,X40,BTT,BANKS
47,ITC,0.24,-25.42,67.19,24.70,199087.0,-100974.0,296304.0,452.00,-30.35,37.0,X-LC,10.69,1.0,-0.51,1.93,1.24,X40,NTT,FMCG

In [20]:
# top 5 to accumulate based on lowest CurrAlloc%
df_tmp = df_portfolio_features[df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])].sort_values(by = 'CurrAlloc%', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
56,PGHH,-0.41,-39.34,117.64,32.01,152358.0,-84008.0,129512.0,17616.87,-55.45,23.0,X-SC,20.06,57.0,-0.55,0.84,0.00,X40,ATH,FMCG
2,ACC,0.47,-41.51,198.85,74.81,311876.0,-111288.0,156840.0,3906.00,-41.79,41.0,X-SC,11.30,85.0,-0.36,1.02,4.78,XY24,BTT,CEMENT
1,ABBOTINDIA,0.26,-11.13,29.82,15.37,47396.0,-19915.0,158940.0,34390.26,-27.58,41.0,X-MC,2.25,58.0,-0.42,1.03,7.66,X40,ATH,PHARMA
40,ICICIPRULI,-0.64,-15.94,54.97,30.28,91035.0,-31397.0,165608.0,787.27,-46.10,52.0,X-MC,11.59,78.0,-0.34,1.08,10.34,X40,ATH,INSURANCE
39,ICICIGI,-0.80,-15.03,39.92,18.89,67878.0,-30074.0,170035.0,2244.41,-15.36,38.0,X-MC,10.16,66.0,-0.44,1.11,1.30,X40,ATH,INSURANCE

In [21]:
# top 5 to accumulate based on CumlRnk
df_tmp = df_portfolio_features.sort_values(by = 'CumlRnk', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
47,ITC,0.24,-25.42,67.19,24.70,199087.0,-100974.0,296304.0,452.00,-30.35,37.0,X-LC,10.69,1.0,-0.51,1.93,1.24,X40,NTT,FMCG
73,TCS,0.17,-32.83,84.91,24.20,264213.0,-152105.0,311168.0,4230.71,-44.31,47.0,X-LC,13.27,2.0,-0.58,2.02,16.04,X40,ATH,IT
45,INFY,0.07,-19.50,74.39,40.38,225442.0,-73416.0,303054.0,1972.00,-40.86,50.0,X-LC,15.45,3.0,-0.33,1.97,14.77,X40,NTT,IT
75,TMPV,-0.27,-25.40,91.36,42.75,283594.0,-105693.0,310414.0,600.00,-84.91,31.0,X-LC,4.47,4.0,-0.37,2.02,6.74,XY24,NTT,AUTO
33,HCLTECH,-0.96,-12.43,41.56,23.97,112638.0,-38461.0,271025.0,1853.42,-14.68,51.0,X-LC,9.71,8.0,-0.34,1.76,27.89,X40,ATH,IT

In [22]:
# top 5 for average up
df_tmp = df_portfolio_features[(df_portfolio_features['Dev%_200'] > 5)].sort_values(by = 'CurrAlloc%', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
44,INDUSINDBK,0.93,-25.06,77.34,32.89,44745.0,-19352.0,57855.0,1800.00,325.93,52.0,L-MC,11.96,258.0,-0.43,0.38,42.64,XR,NTT,BANKS
30,HAPPSTMNDS,0.29,-44.34,228.93,83.08,163310.0,-56829.0,71336.0,1466.54,NaN,71.0,NaN,6.77,152.0,-0.35,0.46,33.62,AR,ATH,IT
3,ALKYLAMINE,0.84,-11.84,118.40,92.54,105388.0,-11953.0,89010.0,4520.85,NaN,68.0,NaN,16.27,142.0,-0.11,0.58,69.02,SR,ATH,CHEMICALS
12,BOSCH-HCIL,-3.50,-27.05,37.06,-0.01,34555.0,-34565.0,93240.0,2282.00,724.95,61.0,M-SC,11.91,231.0,-1.00,0.61,58.71,OX40N,BTT,AC
81,VALIANTORG,-2.28,-38.53,183.30,74.15,184348.0,-63033.0,100572.0,838.00,NaN,50.0,NaN,10.24,145.0,-0.34,0.65,49.67,XR,NTT,CHEMICALS

In [23]:
# top 5 RSP
df_tmp = df_portfolio_features.sort_values(by = 'RSP', ascending=False)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
25,FINCABLES,-2.58,59.37,30.46,107.91,71673.0,87658.0,235302.0,1641.55,16.37,62.0,M-SC,24.90,220.0,1.22,1.53,77.03,OX40N,ATH,CABLES
12,BOSCH-HCIL,-3.50,-27.05,37.06,-0.01,34555.0,-34565.0,93240.0,2282.00,724.95,61.0,M-SC,11.91,231.0,-1.00,0.61,58.71,OX40N,BTT,AC
27,GLAXO,1.41,19.35,13.70,35.69,32584.0,38556.0,237840.0,3380.16,-10.44,72.0,X-MC,12.85,56.0,1.18,1.55,41.36,X40,ATH,PHARMA
30,HAPPSTMNDS,0.29,-44.34,228.93,83.08,163310.0,-56829.0,71336.0,1466.54,NaN,71.0,NaN,6.77,152.0,-0.35,0.46,33.62,AR,ATH,IT
3,ALKYLAMINE,0.84,-11.84,118.40,92.54,105388.0,-11953.0,89010.0,4520.85,NaN,68.0,NaN,16.27,142.0,-0.11,0.58,69.02,SR,ATH,CHEMICALS

In [24]:
# Top N allocation
df_tmp = df_portfolio_features.sort_values(by = 'CurrAlloc%', ascending=False)
top_n_values = [10, 25, 50]

sum_df = pd.DataFrame({
    'Top_N': top_n_values,
    'Sum_Alloc%': [df_tmp['CurrAlloc%'].head(n).sum() for n in top_n_values]
})

sum_df

   Top_N  Sum_Alloc%
0     10       19.73
1     25       45.10
2     50       77.70

In [25]:
# market-cap-wise allocation
df_tmp = df_portfolio_features[cols]
df_tmp.groupby(df_tmp['Conviction'].str[-2:])['CurrAlloc%'].sum().sort_values(ascending=False)

Conviction
LC    38.17
MC    22.21
SC    21.59
Name: CurrAlloc%, dtype: float64

In [26]:
# criteria-wise allocation
df_portfolio_features.groupby('Criteria')['CurrAlloc%'].sum().sort_values(ascending=False)

Criteria
X40      26.75
XY24     23.92
X40N     18.74
XR        9.05
OX40N     7.25
XY25      7.18
AR        6.14
SR        0.91
Name: CurrAlloc%, dtype: float64

In [27]:
# conviction-wise allocation
df_portfolio_features.groupby('Conviction')['CurrAlloc%'].sum().sort_values(ascending=False)

Conviction
X-LC    34.43
X-MC    19.64
H-SC     8.50
X-SC     7.71
M-SC     5.38
H-LC     2.93
M-MC     1.17
H-MC     1.02
M-LC     0.81
L-MC     0.38
Name: CurrAlloc%, dtype: float64

In [28]:
# sector-wise stats
df_tmp = df_portfolio_features.groupby('Category')[['CurrAlloc%', 'Current', 'Current P/L', 'FTT Amt']].sum().sort_values(by=['Current', 'Current P/L'], ascending=False)
df_tmp['Current P/L%'] = round(df_tmp['Current P/L'] * 100 / df_tmp['Current'], 2)
df_tmp['FTT%'] = round(df_tmp['FTT Amt'] * 100 / df_tmp['Current'], 2)
cols = ['CurrAlloc%', 'Current P/L%', 'FTT%']
df_tmp[cols].sort_values(by=['CurrAlloc%'], ascending=False)

               CurrAlloc%  Current P/L%    FTT%
Category
FMCG                15.45        -25.56   70.59
IT                  11.23        -37.86  106.23
FINANCE             10.66        -17.71   68.42
AUTO                 8.28         -6.35   44.44
BANKS                6.22        -11.64   59.79
MISC                 5.89        -36.29   91.12
PHARMA               5.88          8.44   17.53
INSURANCE            5.79         -4.48   41.43
PAINTS               5.42        -18.32   38.50
ELECTRICAL           4.24         -8.19   42.07
AC                   1.82        -14.21   45.17
REFINERIES           1.74        -11.31   48.70
BREWERIES            1.73         11.83    6.48
FOOTWEAR             1.66        -73.39  142.91
APPARELS             1.62         -8.00   43.48
CABLES               1.53         37.25   30.46
DURABLES             1.48        -70.74  112.28
TRAVEL               1.41       -105.96  209.08
CERAMICS             1.30        -53.41  100.02
ENGINEERING          1.23        -27.72   86.14
CHEMICALS            1.23        -39.55  152.83
CEMENT               1.02        -70.96  198.85
JEWELLERY            0.94       -120.51  197.13
ENTERTAINMENT        0.70        -78.01  184.18
HEALTHCARE           0.70        -68.64  110.97
TEXTILES             0.39        -53.14   96.80
HOTELS               0.38        -95.25  164.11

In [29]:
# money to be made criteria-wise
df_portfolio_features.groupby('Criteria')['FTT Amt'].agg(['sum', 'count']).sort_values(by='sum', ascending=False)

                sum  count
Criteria
XY24      3649284.0     19
X40       2108786.0     18
XR        1404633.0     13
X40N      1197400.0     12
AR        1059258.0      8
OX40N      679574.0     10
XY25       595549.0      5
SR         275450.0      2

In [30]:
# money to be made conviction-wise
df_portfolio_features.groupby('Conviction')['FTT Amt'].agg(['sum', 'count']).sort_values(by='sum', ascending=False)

                  sum  count
Conviction
X-LC        2432483.0     19
X-MC        1482394.0     14
X-SC        1090958.0      6
H-SC         843062.0      8
M-SC         339074.0      6
H-MC         256318.0      1
M-LC         167212.0      1
M-MC          65897.0      1
L-MC          44745.0      1
H-LC          38538.0      2

In [31]:
# money to be made criteria and conviction-wise
df_portfolio_features.groupby(['Conviction', 'Criteria'])['FTT Amt'].agg(['sum', 'count']).sort_values(by='sum', ascending=False)

                           sum  count
Conviction Criteria
X-LC       X40       1224594.0      9
X-SC       XY24       660823.0      2
H-SC       XY24       525484.0      3
X-MC       X40        511594.0      6
X-LC       XY24       469555.0      2
X-MC       X40N       451920.0      4
X-LC       X40N       418935.0      5
X-MC       XY25       273239.0      2
X-LC       XY25       256413.0      2
H-MC       XY24       256318.0      1
X-SC       X40        255407.0      2
X-MC       XY24       245641.0      2
H-SC       OX40N      222043.0      3
X-SC       X40N       174728.0      2
M-LC       XR         167212.0      1
M-SC       OX40N      163073.0      4
           XY24       117686.0      1
H-SC       XR          95535.0      2
M-MC       XY25        65897.0      1
X-LC       XR          62986.0      1
M-SC       XR          58315.0      1
L-MC       XR          44745.0      1
H-LC       AR          38538.0      2

In [32]:
# notebook execution time

end_time = time.time()
execution_time = round(end_time - start_time, 0)
print(f"Notebook execution time: {execution_time} seconds")

Notebook execution time: 28.0 seconds