<a href="https://colab.research.google.com/github/ankit-rathi/Quantvesting_v2/blob/main/myStocks_Portfolio_Analysis.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
'''
!pip install pandas==2.2.2 -qq
!pip install pyxirr -qq
!pip install ta -qq
!pip install yfinance==0.2.59 -qq
'''

'\n!pip install pandas==2.2.2 -qq\n!pip install pyxirr -qq\n!pip install ta -qq\n!pip install yfinance==0.2.59 -qq\n'

In [2]:
# import libraries

import numpy as np
import pandas as pd
import datetime
import warnings
warnings.filterwarnings('ignore')
import yfinance as yfin
import ta
import matplotlib.pyplot as plt
import requests

In [3]:
# notebook start time
import time
import datetime
import pytz

start_time = time.time()

# function to print date timestamp
def print_date_time():
  tz_NY = pytz.timezone('Asia/Kolkata')
  datetime_NY = datetime.datetime.now(tz_NY)
  print("Run date time (IST):", datetime_NY.strftime("%Y-%m-%d %H:%M:%S"))

In [4]:
# function to get booked and reserved amount
def get_amt():
  # fetch the JSON data from the URL
  url = "https://raw.githubusercontent.com/ankit-rathi/Tradevesting_v1/main/data/myPortfolioAmts.json"
  response = requests.get(url)
  pf_amts = response.json()  # parse the JSON data

  # extract values from the JSON
  py_booked_amt_dm = pf_amts["py_booked_amt_dm"]
  py_booked_amt_sv = pf_amts["py_booked_amt_sv"]
  cy_booked_amt_dm = pf_amts["cy_booked_amt_dm"]
  cy_booked_amt_sv = pf_amts["cy_booked_amt_sv"]
  reserve_amt_dm = pf_amts["reserve_amt_dm"]
  reserve_amt_sv = pf_amts["reserve_amt_sv"]

  # perform calculations
  py_booked_amt = py_booked_amt_dm + py_booked_amt_sv
  cy_booked_amt = cy_booked_amt_dm + cy_booked_amt_sv
  reserve_amt = reserve_amt_dm + reserve_amt_sv
  total_booked_amt = py_booked_amt + cy_booked_amt

  return total_booked_amt, reserve_amt, cy_booked_amt, py_booked_amt

gen_output = 0

In [5]:
# function to format the amount
def format_amt(number):
    abs_number = abs(number)

    if abs_number >= 1_00_00_000:  # Crores
        formatted_amt = f"{number / 1_00_00_000:.2f} C"
    elif abs_number >= 1_00_000:  # Lakhs
        formatted_amt = f"{number / 1_00_000:.2f} L"
    elif abs_number >= 1_000:  # Thousands
        formatted_amt = f"{number / 1_000:.2f} K"
    else:
        formatted_amt = f"{number:.2f}"

    return formatted_amt

# function to set start and end date
def get_start_end_date():
  start_date = (datetime.date.today() + datetime.timedelta(days=-365)).strftime('%Y-%m-%d')
  end_date = (datetime.date.today() + datetime.timedelta(days=1)).strftime('%Y-%m-%d')
  return start_date, end_date

# function to fetch my portfolio csv
def get_mypfs_df():
  mypfs_df = pd.read_csv('https://raw.githubusercontent.com/ankit-rathi/Tradevesting_v1/main/data/myPortfolioStocks.csv')
  return mypfs_df

# function to fetch my prospects csv
def get_mypps_df():
  mypps_df = pd.read_csv('https://raw.githubusercontent.com/ankit-rathi/Tradevesting_v1/main/data/myProspectsScrips.csv')
  return mypps_df

# function to fetch screener data
def get_myscreen_df():
  myscreen_df = pd.read_csv('https://raw.githubusercontent.com/ankit-rathi/Tradevesting_v1/main/data/myScreenerDB.csv')
  return myscreen_df

# function to fetch momentum data
def get_myinvmt_df():
  myinvmt_df = pd.read_csv('https://raw.githubusercontent.com/ankit-rathi/Tradevesting_v1/main/data/myInvestments.csv')
  return myinvmt_df

# function to get the stock ids
def get_stock_ids(df_pf):
  stock_n100 = df_pf['Symbol'].unique()

  exclude = ['CADILAHC','MMTC', 'MASFIN']

  stock_ids = df_pf[~df_pf['Symbol'].isin(exclude) ]['Symbol'].unique()

  #mypf = mypf[mypf.Forecast.notnull()]
  #stock_ids = mypf['Symbol'].unique()

  #stock_ids.sort()
  return stock_ids

# get features from screener data
def get_screener_features():
  myscreen_df = get_myscreen_df()
  cols = ['Symbol', 'EPS', 'MedPE', 'ROCE%', 'ROE%', 'CapType']
  return myscreen_df[cols]

# get relative strength
def get_relative_strength(stock_list):

    # Dictionary to store stock tickers and their corresponding percentage price change
    stock_changes = {}

    # Loop through each stock and fetch its price data
    for stock in stock_list:
        try:
            # Download the stock data for the given date range
            stock_data = yfin.Ticker(stock + '.NS').history(period='1mo', interval='1d')[map(str.title, ['open', 'close', 'low', 'high', 'volume'])]

            # Calculate the percentage change for the stock
            if len(stock_data) > 0:
                start_price = stock_data['Close'].iloc[0]
                end_price = stock_data['Close'].iloc[-1]
                percent_change = round(((end_price - start_price) / start_price) * 100, 2)
                stock_changes[stock] = percent_change
            else:
                stock_changes[stock] = np.nan  # If no data is available, set to NaN

        except Exception as e:
            print(f"Error fetching data for {stock}: {e}")
            stock_changes[stock] = np.nan

    # Create a DataFrame with stock tickers and their percentage changes
    df = pd.DataFrame(list(stock_changes.items()), columns=['Symbol', 'Percent_Change'])

    # Drop any stocks with missing data (NaN values)
    df = df.dropna()

    # Calculate the percentile rank based on percentage change
    df['RSP'] = round(df['Percent_Change'].rank(pct=True) * 100, 2)
    cols = ['Symbol', 'RSP']
    df = df[cols]
    # Sort by percentile rank (optional)
    df = df.sort_values(by='RSP', ascending=False).reset_index(drop=True)

    return df

In [6]:
# function to get stock technicals
def stock_prec_dev(stock_symbol):
    #stock_symbol = 'ULTRACEMCO.NS'
    short_window = 20
    mid_window = 50
    long_window = 200
    moving_avg = 'SMA'

    start = datetime.datetime(*map(int, start_date.split('-')))
    end = datetime.datetime(*map(int, end_date.split('-')))

    stock_df = yfin.Ticker(stock_symbol + '.NS').history(period='max', interval='1d')[map(str.title, ['open', 'close', 'low', 'high', 'volume'])]

    stock_df['Max'] = round(max(stock_df['Close']),2)
    stock_df = stock_df[(stock_df.index <= end_date) & (stock_df.index >= start_date)]
    stock_df['200_SMA'] = round(stock_df['Close'].rolling(window = 200, min_periods = 1).mean(),0)
    stock_df['Dev%_200'] = round((stock_df['Close'] - stock_df['200_SMA'])*100/stock_df['200_SMA'],2)
    stock_df.dropna(axis = 0, inplace = True) # remove any null rows

    stock_df['20_SMA'] = stock_df['Close'].rolling(window=20).mean()
    stock_df['50_SMA'] = stock_df['Close'].rolling(window=50).mean()
    stock_df['Symbol'] = stock_symbol

    stock_df['Close'] = round(stock_df['Close'],2)
    stock_df['Min'] = round(min(stock_df['Close']),2)
    stock_df['RSI_14'] = ta.momentum.RSIIndicator(close=stock_df['Close'], window=14).rsi()
    stock_df['RSI_14'] = round(stock_df['RSI_14'],0)
    stock_df['Prev_Close'] = stock_df['Close'].shift(1)
    stock_df.drop(['Open', 'Low', 'High', 'Volume'], axis=1, inplace=True)
    stock_df = stock_df.tail(1)

    max_SMA = max(stock_df['20_SMA'].item(), stock_df['50_SMA'].item(), stock_df['200_SMA'].item())
    min_SMA = min(stock_df['20_SMA'].item(), stock_df['50_SMA'].item(), stock_df['200_SMA'].item())
    ABS_Spread = max_SMA - min_SMA
    stock_df['Spread%'] = round((ABS_Spread / stock_df['200_SMA'].item()) * 100,2)

    return stock_df

# function to compute stock attributes
def get_common_features(stock_ids, df_mypf):

  df_prec_dev = pd.DataFrame()
  df_tmp = get_screener_features()
  df_rs = get_relative_strength(stock_ids)

  for stock_id in stock_ids:
      tmp = stock_prec_dev(stock_id)
      tmp = tmp.reset_index()
      df_prec_dev = pd.concat([df_prec_dev, tmp], ignore_index = True)
  df_prec_dev = pd.merge(df_prec_dev, df_mypf, on= 'Symbol')
  df_prec_dev = pd.merge(df_prec_dev, df_tmp, on= 'Symbol', how='left')
  df_prec_dev = pd.merge(df_prec_dev, df_rs, on= 'Symbol', how='left')
  #print(df_prec_dev.columns)
  df_prec_dev['Curr_PE'] = round(df_prec_dev['Close']/df_prec_dev['EPS'],1)
  df_prec_dev['Dev%_PE'] = round((df_prec_dev['Curr_PE'] - df_prec_dev['MedPE'])*100/df_prec_dev['MedPE'],2)
  df_prec_dev['Conviction'] = df_prec_dev['Conviction'] + '-' + df_prec_dev['CapType']
  return df_prec_dev

# function to arrange stock features
def arrange_features(df_stocks, common_cols, diff_cols):
  df_stocks_common = df_stocks[common_cols].drop_duplicates()
  df_stocks_diff = df_stocks[diff_cols]
  df_stocks_diff['Investment'] = df_stocks_diff['AvgCost'] * df_stocks_diff['Shares']
  df_stocks_diff = df_stocks_diff.groupby(['Symbol'])[['Shares', 'Investment']].aggregate(['sum']).reset_index()
  df_stocks_diff.columns = ['Symbol', 'Shares', 'Investment']
  df_stocks_diff['AvgCost'] = round(df_stocks_diff['Investment']/df_stocks_diff['Shares'],2)
  df_stocks = pd.merge(df_stocks_diff, df_stocks_common, on='Symbol')
  return df_stocks

# plot fact distribution across dimension
def plot_pie_chart(df, dimension, fact):
  # grouping the data by category and calculating the sum of fact for each type
  grouped_data = df.groupby(dimension)[fact].sum()

  # sorting the grouped data in descending order
  grouped_data = grouped_data.sort_values(ascending=False)

  # creating a pie chart
  grouped_data.plot.pie(autopct='%1.1f%%', startangle=90, figsize=(6, 6))

  # adding a title and displaying the plot
  plt.title(f'{dimension} {fact} Distribution')
  plt.ylabel('')  # To hide the y-label
  plt.show()

In [7]:
# function to get portfolio features

def get_portfolio_features(df_common_features):

  print_date_time()
  print('-------------------')

  #df_common_features["Target"] = df_common_features["Target"].fillna(df_common_features["Max"])
  df_common_features['NTT'] = np.where(df_common_features['Strategy']== 'NTT', df_common_features["Target"], df_common_features['Max'])
  df_common_features['LTT'] = np.where(df_common_features['Strategy']== 'BTT', df_common_features["Target"], df_common_features['Max'])
  df_common_features['BOL'] = df_common_features['Min']

  tmp_df = df_common_features[df_common_features['Symbol'].isin(mypf_df[mypf_df['InPortfolio'] != 'NA'].Symbol.values)]
  print('qualified stocks: '+str(len(tmp_df['Symbol'].unique())))
  tmp_df1 = tmp_df[tmp_df['LatestQtr'] == 1]
  print('with latest results: '+str(len(tmp_df1['Symbol'].unique())))
  tmp_df1 = tmp_df1[tmp_df1['StarStock'] == 1]
  print('still star stocks: '+str(len(tmp_df1['Symbol'].unique())))
  tmp_df['Investment'] = tmp_df['AvgCost'] * tmp_df['Shares']
  tmp_df['Current'] = round(tmp_df['Close'] * tmp_df['Shares'],0)
  tmp_df['Previous'] = tmp_df['Prev_Close'] * tmp_df['Shares']
  tmp_df['EstimatedST'] = tmp_df['NTT'] * tmp_df['Shares']
  tmp_df['EstimatedLT'] = tmp_df['LTT'] * tmp_df['Shares']
  tmp_df['Current P/L'] = round((tmp_df['Current'] - tmp_df['Investment']),0)
  tmp_df['Today P/L%'] = round((tmp_df['Current'] - tmp_df['Previous'])*100/tmp_df['Previous'],2)
  tmp_df['Current P/L%'] = round((tmp_df['Current'] - tmp_df['Investment'])*100/tmp_df['Investment'],2)
  tmp_df['EstimatedST P/L%'] = round((tmp_df['EstimatedST'] - tmp_df['Investment'])*100/tmp_df['Investment'],2)
  tmp_df['EstimatedLT P/L%'] = round((tmp_df['EstimatedLT'] - tmp_df['Investment'])*100/tmp_df['Investment'],2)
  tmp_df['NTT%'] = round((tmp_df['NTT'] - tmp_df['Close'])*100/tmp_df['Close'],2)
  tmp_df['LTT%'] = round((tmp_df['LTT'] - tmp_df['Close'])*100/tmp_df['Close'],2)
  tmp_df['Gained%'] = round((tmp_df['Close'] - tmp_df['BOL'])*100/tmp_df['BOL'],2)
  investment = round(sum(tmp_df['AvgCost']*tmp_df['Shares']),0)
  current = round(sum(tmp_df['Close']*tmp_df['Shares']),0)
  tmp_df['InitAlloc%'] = round(tmp_df['Investment']*100/investment,2)
  tmp_df['CurrAlloc%'] = round(tmp_df['Current']*100/current,2)
  tmp_df['FTT'] = tmp_df['LTT']
  tmp_df.loc[tmp_df['Strategy'] == 'NTT', 'FTT'] = tmp_df['NTT']
  tmp_df['FTT%'] = tmp_df['LTT%']
  tmp_df.loc[tmp_df['Strategy'] == 'NTT', 'FTT%'] = tmp_df['NTT%']
  tmp_df['FTT Amt'] = round(tmp_df['FTT%'] * tmp_df['Current']/100,0)
  tmp_df['OTT%'] = round((tmp_df['FTT'] - tmp_df['AvgCost'])*100/tmp_df['AvgCost'],2)
  tmp_df['RRR Ind'] = round(tmp_df['Current P/L']/tmp_df['FTT Amt'],2)
  tmp_df['Risk Ind'] = round(tmp_df['Current P/L%']*tmp_df['CurrAlloc%'],0)

  return tmp_df

# function to print portfolio features
def print_portfolio_stats(df_portfolio_features, myinvmt_df):
  from pyxirr import xirr

  total_booked_amt, reserve_amt, cy_booked_amt, py_booked_amt = get_amt()

  dates = myinvmt_df['Date'].values
  dates = np.append(dates, datetime.date.today().strftime('%d-%b-%y'))
  investment = myinvmt_df['Investment'].values
  dates= pd.to_datetime(dates)

  current = round(sum(df_portfolio_features['Close']*df_portfolio_features['Shares']),0) + reserve_amt
  investment_xirr = np.append(investment, current)
  cagr = round(xirr(pd.DataFrame({"dates": dates, "amounts": investment_xirr}))*100,2)

  investment = -sum(investment)
  invested = round(sum(df_portfolio_features['AvgCost']*df_portfolio_features['Shares']),0) + reserve_amt
  previous = round(sum(df_portfolio_features['Prev_Close']*df_portfolio_features['Shares']),0) + reserve_amt
  cy_invested = investment + py_booked_amt

  today_pnl_amount = current-previous
  today_pnl_percentage = round((current-previous)*100/previous,2)

  curr_pnl_amount = current-invested
  curr_pnl_percentage = round((curr_pnl_amount)*100/(cy_invested),2)

  cy_pnl_amount = cy_booked_amt + curr_pnl_amount
  cy_pnl_percentage = round((cy_pnl_amount)*100/cy_invested,2)

  overall_pnl_amount = total_booked_amt + curr_pnl_amount
  overall_pnl_percentage = round((overall_pnl_amount)*100/investment,2)

  estimate_st = round(sum(df_portfolio_features['FTT']*df_portfolio_features['Shares']),0)  + reserve_amt
  est_st_pnl_amount = estimate_st-current
  est_st_pnl_percentage = round((est_st_pnl_amount)*100/current,2)

  estimate_lt = round(sum(df_portfolio_features['LTT']*df_portfolio_features['Shares']),0)  + reserve_amt
  est_lt_pnl_amount = estimate_lt-current
  est_lt_pnl_percentage = round((est_lt_pnl_amount)*100/current,2)

  total_profit = round(sum(df_portfolio_features[df_portfolio_features['Current P/L%'] > 0]['Current']) - sum(df_portfolio_features[df_portfolio_features['Current P/L%'] > 0]['Investment']),0)
  total_loss = round(sum(df_portfolio_features[df_portfolio_features['Current P/L%'] < 0]['Current']) - sum(df_portfolio_features[df_portfolio_features['Current P/L%'] < 0]['Investment']),0)

  cy_booked_percentage = round((cy_booked_amt)*100/current,2)
  py_booked_percentage = round((py_booked_amt)*100/investment,2)
  total_booked_percentage = round((total_booked_amt)*100/investment,2)

  print('-------------------')
  print('Initial Investment: ', format_amt(investment))
  print('CY Investment: ', format_amt(cy_invested))
  print('Reserve: ', format_amt(reserve_amt))
  print('Current: ',  format_amt(current))
  print('-------------------')
  print('Today PnL: '+ '{} ({}%)'.format(format_amt(today_pnl_amount), today_pnl_percentage))
  print('Current PnL: '+ '{} ({}%)'.format(format_amt(curr_pnl_amount), curr_pnl_percentage))
  print('CY Booked + Current PnL: '+ '{} ({}%)'.format(format_amt(cy_pnl_amount), cy_pnl_percentage))
  print('-------------------')
  print('Total profit: ', format_amt(total_profit))
  print('Total loss: ', format_amt(total_loss))
  print('-------------------')
  print('Total Booked + Current PnL: '+ '{} ({}%)'.format(format_amt(overall_pnl_amount), overall_pnl_percentage))
  print('Total Booked PnL: '+ '{} ({}%)'.format(format_amt(total_booked_amt), total_booked_percentage))
  print('Curr Year Booked PnL: '+ '{} ({}%)'.format(format_amt(cy_booked_amt), cy_booked_percentage))
  print('Prev Year Booked PnL: '+ '{} ({}%)'.format(format_amt(py_booked_amt), py_booked_percentage))
  print('===================')
  print('Est FTT: ',  format_amt(estimate_st))
  print('Est FTT PnL: '+ '{} ({}%)'.format(format_amt(est_st_pnl_amount), est_st_pnl_percentage))

  print('===================')
  print('Deployed: ', format_amt(investment))

  print('Current: ', format_amt(current))

  print('CAGR/XIRR %: '+'{}%'.format(cagr))

In [8]:
# get start and end date
start_date, end_date = get_start_end_date()

# get portfolio and prospects data
mypfs_df = get_mypfs_df()
mypps_df = get_mypps_df()
myinvmt_df = get_myinvmt_df()

# merge above datasets
mypf_df = pd.merge(mypfs_df, mypps_df, on="Symbol")

# seggregate dm and sv portfolio
dm_pf = mypf_df[mypf_df['InPortfolio'] == 'DM']
sv_pf = mypf_df[mypf_df['InPortfolio'] == 'SV']

# build portfolio stock dataframe
dm_stocks = get_stock_ids(dm_pf)
sv_stocks = get_stock_ids(sv_pf)
df_stocks = pd.concat([dm_pf,sv_pf], ignore_index = True)

# arrange common and diff stock features
common_cols = ['Symbol', 'Target', 'Criteria', 'Strategy', 'CumlRnk', 'LatestQtr', 'StarStock', 'Conviction', 'Category', 'InFolio', 'XIRR', 'MBQ']
diff_cols = ['Symbol', 'AvgCost', 'Shares']
df_stocks = arrange_features(df_stocks, common_cols, diff_cols)

# get common features
stock_ids = df_stocks['Symbol'].values
df_common_features = get_common_features(stock_ids, df_stocks)

df_common_features.reset_index(drop=True, inplace=True)
df_common_features.drop(['Date'], axis=1, inplace=True)
# get and print portfolio features
df_portfolio_features = get_portfolio_features(df_common_features)

print_portfolio_stats(df_portfolio_features, myinvmt_df)

df = df_portfolio_features
#plot_pie_chart(df, 'CapType', 'Current')
list_ox40n = list(df[df['MBQ'].str.contains('OX40N', na=False)]['Symbol'].values)

Run date time (IST): 2026-06-25 11:36:15
-------------------
qualified stocks: 92
with latest results: 31
still star stocks: 20
-------------------
Initial Investment:  1.40 C
CY Investment:  1.82 C
Reserve:  1.49 K
Current:  1.52 C
-------------------
Today PnL: 48.97 K (0.32%)
Current PnL: -30.76 L (-16.87%)
CY Booked + Current PnL: -28.68 L (-15.73%)
-------------------
Total profit:  4.13 L
Total loss:  -34.89 L
-------------------
Total Booked + Current PnL: 14.19 L (10.17%)
Total Booked PnL: 44.95 L (32.22%)
Curr Year Booked PnL: 2.08 L (1.36%)
Prev Year Booked PnL: 42.87 L (30.73%)
===================
Est FTT:  2.55 C
Est FTT PnL: 1.03 C (67.34%)
===================
Deployed:  1.40 C
Current:  1.52 C
CAGR/XIRR %: 4.11%

In [9]:
# top 5 near their targets
cols = ['Symbol', 'Today P/L%', 'Current P/L%', 'FTT%', 'OTT%', 'FTT Amt', 'Current P/L', 'Current', 'FTT', 'Dev%_PE', 'RSI_14','Conviction', 'Spread%',  'CumlRnk', 'RRR Ind', 'CurrAlloc%', 'Gained%', 'Criteria', 'Strategy', 'Category']
df_tmp = df_portfolio_features[~df_portfolio_features['Symbol'].isin(['ENRIN','BLUSPRING','DIGITIDE'])]
df_tmp = df_tmp.sort_values(by = 'FTT Amt', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
59,PIDILITIND,2.51,14.70,3.19,18.37,5163.0,20750.0,161860.0,1670.26,-19.70,77.0,X-LC,4.42,5.0,4.02,1.06,27.09,X40,ATH,CHEMICALS
49,JSWINFRA,-2.57,12.24,3.73,16.43,9285.0,27150.0,248924.0,342.00,-3.70,72.0,X-MC,4.75,61.0,2.92,1.63,41.13,X40N,NTT,REALTY
51,KOTAKBANK,1.17,9.74,10.36,21.11,15743.0,13486.0,151959.0,453.24,-5.94,68.0,X-LC,4.94,12.0,0.86,1.00,16.21,X40,ATH,BANKS
72,SIS,-0.02,1.37,19.62,21.26,22084.0,1525.0,112557.0,528.00,2689.12,67.0,H-SC,25.04,168.0,0.07,0.74,67.36,OX40N,NTT,MISC
55,MASFIN,-0.25,-4.01,26.65,21.57,25064.0,-3930.0,94050.0,397.04,-17.34,51.0,H-SC,3.10,167.0,-0.16,0.62,12.10,XR,ATH,FINANCE

In [10]:
# top 5 today
df_tmp = df_portfolio_features.sort_values(by = 'Today P/L%', ascending=False)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
64,RELAXO,10.65,-47.13,188.06,52.31,144338.0,-68409.0,76751.0,1176.00,-43.66,77.0,X-SC,14.31,92.0,-0.47,0.50,71.61,X40N,NTT,FOOTWEAR
54,MARUTI,4.51,3.04,24.89,28.68,37909.0,4489.0,152306.0,17292.00,-15.17,62.0,X-LC,10.43,33.0,0.12,1.00,13.42,XR,ATH,AUTO
53,M&M,3.36,2.78,20.04,23.38,28565.0,3857.0,142538.0,3802.40,-13.04,58.0,X-LC,10.53,25.0,0.14,0.94,8.07,X40N,ATH,AUTO
71,SIEMENS,2.71,-1.72,27.71,25.51,50680.0,-3200.0,182895.0,4671.50,53.57,49.0,H-LC,12.71,51.0,-0.06,1.20,28.41,AR,ATH,ELECTRICAL
59,PIDILITIND,2.51,14.70,3.19,18.37,5163.0,20750.0,161860.0,1670.26,-19.70,77.0,X-LC,4.42,5.0,4.02,1.06,27.09,X40,ATH,CHEMICALS

In [11]:
# bottom 5 today
df_tmp = df_portfolio_features.sort_values(by = 'Today P/L%', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
9,BANDHANBNK,-6.59,-4.85,102.22,92.42,270936.0,-13507.0,265052.0,400.0,127.01,44.0,H-SC,23.14,174.0,-0.05,1.74,46.01,XY24,NTT,BANKS
61,RAJESHEXPO,-5.00,-81.26,433.91,0.07,111558.0,-111467.0,25710.0,518.0,841.92,47.0,L-SC,37.05,268.0,-1.00,0.17,26.97,OX40N,NTT,JEWELLERY
62,RAJOOENG,-2.66,-46.75,162.18,39.61,88518.0,-47920.0,54580.0,143.1,-63.90,45.0,H-SC,20.83,136.0,-0.54,0.36,16.92,AR,ATH,MISC
49,JSWINFRA,-2.57,12.24,3.73,16.43,9285.0,27150.0,248924.0,342.0,-3.70,72.0,X-MC,4.75,61.0,2.92,1.63,41.13,X40N,NTT,REALTY
52,LAOPALA,-2.13,-46.19,158.50,39.09,111812.0,-60561.0,70544.0,464.0,54.47,51.0,H-SC,12.49,154.0,-0.54,0.46,9.45,AR,NTT,CERAMICS

In [12]:
# top 5 to exit based on CumlRnk
df_tmp = df_portfolio_features[~df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])]
df_tmp = df_tmp[(df_tmp['Current P/L%'] > -1) & (df_tmp['Current P/L%'] < 1)].sort_values(by = 'CumlRnk', ascending=False)
df_tmp[cols].head()

Empty DataFrame
Columns: [Symbol, Today P/L%, Current P/L%, FTT%, OTT%, FTT Amt, Current P/L, Current, FTT, Dev%_PE, RSI_14, Conviction, Spread%, CumlRnk, RRR Ind, CurrAlloc%, Gained%, Criteria, Strategy, Category]
Index: []

In [13]:
# OX40N stocks to exit
df_tmp = df_portfolio_features[(df_portfolio_features['Symbol'].isin(list_ox40n))].sort_values(by = 'Current P/L%', ascending=False)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
25,FINCABLES,-0.89,42.68,45.72,107.91,96312.0,63012.0,210656.0,1641.55,28.36,56.0,M-SC,24.27,220.0,0.65,1.38,58.48,OX40N,ATH,CABLES
72,SIS,-0.02,1.37,19.62,21.26,22084.0,1525.0,112557.0,528.00,2689.12,67.0,H-SC,25.04,168.0,0.07,0.74,67.36,OX40N,NTT,MISC
16,CERA,0.32,-16.83,48.97,23.89,71639.0,-29611.0,146292.0,9475.00,-19.81,63.0,H-SC,8.51,153.0,-0.41,0.96,40.59,OX40N,NTT,CERAMICS
83,TTKPRESTIG,-0.09,-26.52,36.21,0.09,26815.0,-26723.0,74054.0,770.00,71.82,62.0,M-SC,8.60,250.0,-1.00,0.49,31.86,OX40N,NTT,DURABLES
43,INDIGOPNTS,-0.01,-27.00,37.01,0.02,47161.0,-47130.0,127429.0,1408.00,94.20,62.0,M-SC,7.61,222.0,-1.00,0.84,44.58,OX40N,NTT,PAINTS

In [14]:
# top 5 to book for rotation
df_tmp = df_portfolio_features[(df_portfolio_features['Current P/L%'] > 20) ].sort_values(by = 'CumlRnk', ascending=False)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
25,FINCABLES,-0.89,42.68,45.72,107.91,96312.0,63012.0,210656.0,1641.55,28.36,56.0,M-SC,24.27,220.0,0.65,1.38,58.48,OX40N,ATH,CABLES
68,SATIN,-2.02,29.93,16.86,51.83,60523.0,82690.0,358974.0,274.00,16.95,56.0,H-SC,41.11,159.0,1.37,2.36,74.87,XY24,NTT,FINANCE

In [15]:
# top 5 to monitor for exit
df_tmp = df_portfolio_features[~df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])]
df_tmp = df_tmp[(df_tmp['Current P/L%'] > 0) ].sort_values(by = 'Dev%_PE', ascending=False)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
72,SIS,-0.02,1.37,19.62,21.26,22084.0,1525.0,112557.0,528.00,2689.12,67.0,H-SC,25.04,168.0,0.07,0.74,67.36,OX40N,NTT,MISC
74,STARHEALTH,0.30,11.47,32.11,47.26,100623.0,32248.0,313371.0,761.00,75.94,71.0,H-SC,12.55,173.0,0.32,2.06,37.58,XY24,NTT,INSURANCE
25,FINCABLES,-0.89,42.68,45.72,107.91,96312.0,63012.0,210656.0,1641.55,28.36,56.0,M-SC,24.27,220.0,0.65,1.38,58.48,OX40N,ATH,CABLES
68,SATIN,-2.02,29.93,16.86,51.83,60523.0,82690.0,358974.0,274.00,16.95,56.0,H-SC,41.11,159.0,1.37,2.36,74.87,XY24,NTT,FINANCE
91,ZYDUSLIFE,0.50,16.50,16.42,35.63,40091.0,34587.0,244161.0,1286.17,1.35,62.0,H-MC,13.77,120.0,0.86,1.60,28.38,AR,ATH,PHARMA

In [16]:
# top 5 to book for rotation from weak conviction
df_tmp = df_portfolio_features[~df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])]
df_tmp = df_tmp[~df_tmp['Criteria'].isin(['XY25','XY24','X40', 'X40N'])].sort_values(by = 'RRR Ind', ascending=False)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
91,ZYDUSLIFE,0.50,16.50,16.42,35.63,40091.0,34587.0,244161.0,1286.17,1.35,62.0,H-MC,13.77,120.0,0.86,1.60,28.38,AR,ATH,PHARMA
25,FINCABLES,-0.89,42.68,45.72,107.91,96312.0,63012.0,210656.0,1641.55,28.36,56.0,M-SC,24.27,220.0,0.65,1.38,58.48,OX40N,ATH,CABLES
73,SONACOMS,1.18,8.40,27.94,38.69,30638.0,8496.0,109655.0,801.69,-14.12,65.0,M-MC,18.14,193.0,0.28,0.72,55.57,AR,ATH,AUTO
72,SIS,-0.02,1.37,19.62,21.26,22084.0,1525.0,112557.0,528.00,2689.12,67.0,H-SC,25.04,168.0,0.07,0.74,67.36,OX40N,NTT,MISC
75,SURYODAY,-0.44,-1.62,25.07,23.03,44164.0,-2907.0,176164.0,216.00,92.98,56.0,H-SC,19.43,166.0,-0.07,1.16,48.33,XR,NTT,BANKS

In [17]:
# top 5 to accumulate based on lowest RSI_14
df_tmp = df_portfolio_features[df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])].sort_values(by = 'RSI_14', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
45,INFY,-0.54,-28.46,87.65,34.24,196198.0,-89046.0,223842.0,1972.00,-43.76,37.0,X-LC,17.65,3.0,-0.45,1.47,2.10,X40,NTT,IT
1,ABBOTINDIA,-0.06,-14.19,37.59,18.07,57693.0,-25375.0,153480.0,35195.00,-26.90,38.0,X-MC,6.26,58.0,-0.44,1.01,1.59,X40,ATH,PHARMA
58,PGHH,0.43,-32.42,95.35,32.01,137579.0,-69232.0,144288.0,17616.87,-54.24,39.0,X-MC,20.65,57.0,-0.50,0.95,0.43,X40,ATH,FMCG
33,HCLTECH,0.57,-27.30,67.14,21.51,118080.0,-66053.0,175871.0,1872.35,-23.49,41.0,X-LC,18.66,8.0,-0.56,1.15,0.96,X40,ATH,IT
79,TCS,0.72,-37.64,100.26,24.88,289642.0,-174382.0,288891.0,4253.91,-47.23,41.0,X-LC,19.95,2.0,-0.60,1.90,3.14,X40,ATH,IT

In [18]:
# top 5 to accumulate based on Spread and CumlRnk
df_tmp = df_portfolio_features[df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])]
df_tmp = df_tmp[(df_tmp['CumlRnk'] < 100)].sort_values(by = 'Spread%', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
11,BERGEPAINT,2.13,-0.14,25.50,25.32,65632.0,-370.0,257379.0,680.00,-5.64,60.0,X-MC,2.74,68.0,-0.01,1.69,33.96,XY24,NTT,PAINTS
17,CIPLA,0.35,16.83,14.22,33.43,25444.0,25771.0,178932.0,1648.14,-9.73,67.0,X-LC,3.69,18.0,1.01,1.17,22.15,X40N,ATH,PHARMA
56,MEDANTA,-0.36,12.38,13.12,27.12,26026.0,21852.0,198369.0,1486.00,8.91,69.0,X-SC,3.71,87.0,0.84,1.30,36.69,XY24,NTT,HEALTHCARE
19,COLPAL,1.36,-24.36,84.91,39.86,169141.0,-64165.0,199200.0,3683.41,-8.54,43.0,X-MC,4.10,62.0,-0.38,1.31,12.68,XY25,ATH,FMCG
84,UNITDSPR,1.98,1.81,18.61,20.77,44365.0,4248.0,238392.0,1644.00,-9.71,68.0,X-MC,4.11,64.0,0.10,1.56,13.72,X40N,NTT,BREWERIES

In [19]:
# top 5 to accumulate based on lowest Gained%
df_tmp = df_portfolio_features[df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])].sort_values(by = 'Gained%', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
58,PGHH,0.43,-32.42,95.35,32.01,137579.0,-69232.0,144288.0,17616.87,-54.24,39.0,X-MC,20.65,57.0,-0.50,0.95,0.43,X40,ATH,FMCG
33,HCLTECH,0.57,-27.30,67.14,21.51,118080.0,-66053.0,175871.0,1872.35,-23.49,41.0,X-LC,18.66,8.0,-0.56,1.15,0.96,X40,ATH,IT
1,ABBOTINDIA,-0.06,-14.19,37.59,18.07,57693.0,-25375.0,153480.0,35195.00,-26.90,38.0,X-MC,6.26,58.0,-0.44,1.01,1.59,X40,ATH,PHARMA
45,INFY,-0.54,-28.46,87.65,34.24,196198.0,-89046.0,223842.0,1972.00,-43.76,37.0,X-LC,17.65,3.0,-0.45,1.47,2.10,X40,NTT,IT
79,TCS,0.72,-37.64,100.26,24.88,289642.0,-174382.0,288891.0,4253.91,-47.23,41.0,X-LC,19.95,2.0,-0.60,1.90,3.14,X40,ATH,IT

In [20]:
# top 5 to accumulate based on lowest CurrAlloc%
df_tmp = df_portfolio_features[df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])].sort_values(by = 'CurrAlloc%', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
10,BATAINDIA,1.02,-53.41,190.18,35.20,114015.0,-68719.0,59951.0,2096.00,-21.44,55.0,X-SC,22.55,91.0,-0.60,0.39,18.90,X40,NTT,FOOTWEAR
64,RELAXO,10.65,-47.13,188.06,52.31,144338.0,-68409.0,76751.0,1176.00,-43.66,77.0,X-SC,14.31,92.0,-0.47,0.50,71.61,X40N,NTT,FOOTWEAR
60,QUESS,-0.02,2.56,69.57,73.90,76194.0,2729.0,109522.0,424.00,-44.90,72.0,X-SC,11.55,80.0,0.04,0.72,49.30,XY24,NTT,MISC
28,GODREJCP,1.05,-7.71,42.46,31.47,58234.0,-11464.0,137150.0,1469.04,-2.98,53.0,X-LC,9.34,32.0,-0.20,0.90,5.23,X40N,ATH,FMCG
53,M&M,3.36,2.78,20.04,23.38,28565.0,3857.0,142538.0,3802.40,-13.04,58.0,X-LC,10.53,25.0,0.14,0.94,8.07,X40N,ATH,AUTO

In [21]:
# top 5 to accumulate based on CumlRnk
df_tmp = df_portfolio_features.sort_values(by = 'CumlRnk', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
47,ITC,0.52,-23.13,54.87,19.06,143484.0,-78668.0,261498.0,452.00,-57.95,54.0,X-LC,14.69,1.0,-0.55,1.72,5.36,X40,NTT,FMCG
79,TCS,0.72,-37.64,100.26,24.88,289642.0,-174382.0,288891.0,4253.91,-47.23,41.0,X-LC,19.95,2.0,-0.60,1.90,3.14,X40,ATH,IT
45,INFY,-0.54,-28.46,87.65,34.24,196198.0,-89046.0,223842.0,1972.00,-43.76,37.0,X-LC,17.65,3.0,-0.45,1.47,2.10,X40,NTT,IT
81,TMPV,1.32,-19.35,69.35,36.58,199023.0,-68858.0,286983.0,600.00,-83.62,42.0,X-LC,9.89,4.0,-0.35,1.88,20.61,XY24,NTT,AUTO
59,PIDILITIND,2.51,14.70,3.19,18.37,5163.0,20750.0,161860.0,1670.26,-19.70,77.0,X-LC,4.42,5.0,4.02,1.06,27.09,X40,ATH,CHEMICALS

In [22]:
# top 5 for average up
df_tmp = df_portfolio_features[(df_portfolio_features['Dev%_200'] > 5)].sort_values(by = 'CurrAlloc%', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
21,DEN,-2.03,-39.61,135.26,42.07,68993.0,-33456.0,51008.0,75.00,81.35,64.0,M-SC,6.45,235.0,-0.48,0.33,38.73,AR,NTT,ENTERTAINMENT
44,INDUSINDBK,0.19,-31.50,93.99,32.89,49711.0,-24316.0,52890.0,1800.00,-349.30,54.0,L-MC,7.02,258.0,-0.49,0.35,30.40,XR,NTT,BANKS
3,ALKYLAMINE,0.85,-23.91,153.06,92.54,117581.0,-24143.0,76820.0,4520.85,-18.57,54.0,H-SC,7.67,142.0,-0.21,0.50,45.87,SR,ATH,CHEMICALS
64,RELAXO,10.65,-47.13,188.06,52.31,144338.0,-68409.0,76751.0,1176.00,-43.66,77.0,X-SC,14.31,92.0,-0.47,0.50,71.61,X40N,NTT,FOOTWEAR
73,SONACOMS,1.18,8.40,27.94,38.69,30638.0,8496.0,109655.0,801.69,-14.12,65.0,M-MC,18.14,193.0,0.28,0.72,55.57,AR,ATH,AUTO

In [23]:
# top 5 RSP
df_tmp = df_portfolio_features.sort_values(by = 'RSP', ascending=False)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
64,RELAXO,10.65,-47.13,188.06,52.31,144338.0,-68409.0,76751.0,1176.0,-43.66,77.0,X-SC,14.31,92.0,-0.47,0.50,71.61,X40N,NTT,FOOTWEAR
18,COFFEEDAY,-0.26,-42.37,134.74,35.27,88166.0,-48115.0,65434.0,80.0,-55.73,55.0,L-SC,16.86,266.0,-0.55,0.43,61.36,XR,NTT,HOTELS
60,QUESS,-0.02,2.56,69.57,73.90,76194.0,2729.0,109522.0,424.0,-44.90,72.0,X-SC,11.55,80.0,0.04,0.72,49.30,XY24,NTT,MISC
49,JSWINFRA,-2.57,12.24,3.73,16.43,9285.0,27150.0,248924.0,342.0,-3.70,72.0,X-MC,4.75,61.0,2.92,1.63,41.13,X40N,NTT,REALTY
21,DEN,-2.03,-39.61,135.26,42.07,68993.0,-33456.0,51008.0,75.0,81.35,64.0,M-SC,6.45,235.0,-0.48,0.33,38.73,AR,NTT,ENTERTAINMENT

In [24]:
# Top N allocation
df_tmp = df_portfolio_features.sort_values(by = 'CurrAlloc%', ascending=False)
top_n_values = [10, 25, 50]

sum_df = pd.DataFrame({
    'Top_N': top_n_values,
    'Sum_Alloc%': [df_tmp['CurrAlloc%'].head(n).sum() for n in top_n_values]
})

sum_df

   Top_N  Sum_Alloc%
0     10       19.21
1     25       42.52
2     50       72.67

In [25]:
# market-cap-wise allocation
df_tmp = df_portfolio_features[cols]
df_tmp.groupby(df_tmp['Conviction'].str[-2:])['CurrAlloc%'].sum().sort_values(ascending=False)

Conviction
SC    43.42
LC    30.60
MC    25.94
Name: CurrAlloc%, dtype: float64

In [26]:
# criteria-wise allocation
df_portfolio_features.groupby('Criteria')['CurrAlloc%'].sum().sort_values(ascending=False)

Criteria
XY24     27.60
X40      24.69
X40N     17.55
XR        8.89
OX40N     7.13
AR        6.76
XY25      6.49
SR        0.85
Name: CurrAlloc%, dtype: float64

In [27]:
# conviction-wise allocation
df_portfolio_features.groupby('Conviction')['CurrAlloc%'].sum().sort_values(ascending=False)

Conviction
X-LC    28.60
H-SC    22.71
X-MC    20.85
M-SC    10.10
X-SC    10.01
H-MC     2.70
M-MC     2.04
H-LC     1.20
M-LC     0.80
L-SC     0.60
L-MC     0.35
Name: CurrAlloc%, dtype: float64

In [28]:
# sector-wise stats
df_tmp = df_portfolio_features.groupby('Category')[['CurrAlloc%', 'Current', 'Current P/L', 'FTT Amt']].sum().sort_values(by=['Current', 'Current P/L'], ascending=False)
df_tmp['Current P/L%'] = round(df_tmp['Current P/L'] * 100 / df_tmp['Current'], 2)
df_tmp['FTT%'] = round(df_tmp['FTT Amt'] * 100 / df_tmp['Current'], 2)
cols = ['CurrAlloc%', 'Current P/L%', 'FTT%']
df_tmp[cols].sort_values(by=['CurrAlloc%'], ascending=False)

               CurrAlloc%  Current P/L%    FTT%
Category
FMCG                14.51        -19.72   61.72
FINANCE             11.04         -9.61   57.28
IT                   9.63        -53.65  130.47
MISC                 7.25        -21.47   73.59
AUTO                 6.65         -8.04   48.50
BANKS                5.72         -4.32   52.55
PAINTS               5.59        -15.63   35.35
INSURANCE            5.34         -1.58   35.84
PHARMA               5.03          3.44   26.45
ELECTRICAL           4.12        -12.49   52.19
CHEMICALS            2.20        -20.52   92.02
HEALTHCARE           2.08        -12.87   42.33
APPARELS             1.88          6.48   24.94
AC                   1.80        -16.10   47.58
FOOTWEAR             1.77        -62.62  127.82
REALTY               1.63         10.91    3.73
TRAVEL               1.58        -85.79  178.82
BREWERIES            1.56          1.78   18.61
DURABLES             1.56        -62.40  101.91
CERAMICS             1.42        -41.59   84.60
CABLES               1.38         29.91   45.72
ENGINEERING          1.35        -17.62   71.42
REFINERIES           1.12        -17.81   47.62
CEMENT               1.06        -65.84  189.91
JEWELLERY            1.04       -102.04  172.24
ENTERTAINMENT        0.79        -59.30  154.32
TEXTILES             0.43        -40.31   80.32
HOTELS               0.43        -73.53  134.74

In [29]:
# money to be made criteria-wise
df_portfolio_features.groupby('Criteria')['FTT Amt'].agg(['sum', 'count']).sort_values(by='sum', ascending=False)

                sum  count
Criteria
XY24      3389331.0     21
X40       1913900.0     19
XR        1327970.0     13
AR        1144995.0      9
X40N      1046322.0     13
OX40N      705096.0     10
XY25       447468.0      5
SR         287759.0      2

In [30]:
# money to be made conviction-wise
df_portfolio_features.groupby('Conviction')['FTT Amt'].agg(['sum', 'count']).sort_values(by='sum', ascending=False)

                  sum  count
Conviction
H-SC        3316964.0     24
X-LC        1923941.0     21
X-MC        1537877.0     15
M-SC        1375193.0     14
X-SC        1277304.0      9
H-MC         286108.0      2
L-SC         199724.0      2
M-LC         170353.0      1
M-MC          74986.0      2
H-LC          50680.0      1
L-MC          49711.0      1

In [31]:
# money to be made criteria and conviction-wise
df_portfolio_features.groupby(['Conviction', 'Criteria'])['FTT Amt'].agg(['sum', 'count']).sort_values(by='sum', ascending=False)

                           sum  count
Conviction Criteria
X-LC       X40       1038220.0     10
H-SC       XY24       989104.0      6
           AR         954593.0      5
M-SC       XY24       816339.0      6
H-SC       XR         795158.0      7
X-SC       XY24       778902.0      4
X-MC       X40        665611.0      7
           X40N       408375.0      4
X-LC       X40N       349614.0      6
           XY24       344271.0      2
M-SC       OX40N      303188.0      5
H-SC       OX40N      290350.0      4
X-SC       X40N       288333.0      3
H-SC       SR         287759.0      2
X-MC       XY25       249193.0      2
H-MC       XY24       246017.0      1
X-MC       XY24       214698.0      2
X-SC       X40        210069.0      2
M-SC       XR         186673.0      2
M-LC       XR         170353.0      1
X-LC       XY25       153927.0      2
L-SC       OX40N      111558.0      1
           XR          88166.0      1
M-SC       AR          68993.0      1
H-LC       AR          50680.0      1
L-MC       XR          49711.0      1
M-MC       XY25        44348.0      1
H-MC       AR          40091.0      1
X-LC       XR          37909.0      1
M-MC       AR          30638.0      1

In [32]:
# notebook execution time

end_time = time.time()
execution_time = round(end_time - start_time, 0)
print(f"Notebook execution time: {execution_time} seconds")

Notebook execution time: 27.0 seconds