<a href="https://colab.research.google.com/github/ankit-rathi/Quantvesting_v2/blob/main/myStocks_Portfolio_Analysis.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
'''
!pip install pandas==2.2.2 -qq
!pip install pyxirr -qq
!pip install ta -qq
!pip install yfinance==0.2.59 -qq
'''

'\n!pip install pandas==2.2.2 -qq\n!pip install pyxirr -qq\n!pip install ta -qq\n!pip install yfinance==0.2.59 -qq\n'

In [2]:
# import libraries

import numpy as np
import pandas as pd
import datetime
import warnings
warnings.filterwarnings('ignore')
import yfinance as yfin
import ta
import matplotlib.pyplot as plt
import requests

In [3]:
# notebook start time
import time
import datetime
import pytz

start_time = time.time()

# function to print date timestamp
def print_date_time():
  tz_NY = pytz.timezone('Asia/Kolkata')
  datetime_NY = datetime.datetime.now(tz_NY)
  print("Run date time (IST):", datetime_NY.strftime("%Y-%m-%d %H:%M:%S"))

In [4]:
# function to get booked and reserved amount
def get_amt():
  # fetch the JSON data from the URL
  url = "https://raw.githubusercontent.com/ankit-rathi/Tradevesting_v1/main/data/myPortfolioAmts.json"
  response = requests.get(url)
  pf_amts = response.json()  # parse the JSON data

  # extract values from the JSON
  py_booked_amt_dm = pf_amts["py_booked_amt_dm"]
  py_booked_amt_sv = pf_amts["py_booked_amt_sv"]
  cy_booked_amt_dm = pf_amts["cy_booked_amt_dm"]
  cy_booked_amt_sv = pf_amts["cy_booked_amt_sv"]
  reserve_amt_dm = pf_amts["reserve_amt_dm"]
  reserve_amt_sv = pf_amts["reserve_amt_sv"]

  # perform calculations
  py_booked_amt = py_booked_amt_dm + py_booked_amt_sv
  cy_booked_amt = cy_booked_amt_dm + cy_booked_amt_sv
  reserve_amt = reserve_amt_dm + reserve_amt_sv
  total_booked_amt = py_booked_amt + cy_booked_amt

  return total_booked_amt, reserve_amt, cy_booked_amt, py_booked_amt

gen_output = 0

In [5]:
# function to format the amount
def format_amt(number):
    abs_number = abs(number)

    if abs_number >= 1_00_00_000:  # Crores
        formatted_amt = f"{number / 1_00_00_000:.2f} C"
    elif abs_number >= 1_00_000:  # Lakhs
        formatted_amt = f"{number / 1_00_000:.2f} L"
    elif abs_number >= 1_000:  # Thousands
        formatted_amt = f"{number / 1_000:.2f} K"
    else:
        formatted_amt = f"{number:.2f}"

    return formatted_amt

# function to set start and end date
def get_start_end_date():
  start_date = (datetime.date.today() + datetime.timedelta(days=-365)).strftime('%Y-%m-%d')
  end_date = (datetime.date.today() + datetime.timedelta(days=1)).strftime('%Y-%m-%d')
  return start_date, end_date

# function to fetch my portfolio csv
def get_mypfs_df():
  mypfs_df = pd.read_csv('https://raw.githubusercontent.com/ankit-rathi/Tradevesting_v1/main/data/myPortfolioStocks.csv')
  return mypfs_df

# function to fetch my prospects csv
def get_mypps_df():
  mypps_df = pd.read_csv('https://raw.githubusercontent.com/ankit-rathi/Tradevesting_v1/main/data/myProspectsScrips.csv')
  return mypps_df

# function to fetch screener data
def get_myscreen_df():
  myscreen_df = pd.read_csv('https://raw.githubusercontent.com/ankit-rathi/Tradevesting_v1/main/data/myScreenerDB.csv')
  return myscreen_df

# function to fetch momentum data
def get_myinvmt_df():
  myinvmt_df = pd.read_csv('https://raw.githubusercontent.com/ankit-rathi/Tradevesting_v1/main/data/myInvestments.csv')
  return myinvmt_df

# function to get the stock ids
def get_stock_ids(df_pf):
  stock_n100 = df_pf['Symbol'].unique()

  exclude = ['CADILAHC','MMTC', 'MASFIN']

  stock_ids = df_pf[~df_pf['Symbol'].isin(exclude) ]['Symbol'].unique()

  #mypf = mypf[mypf.Forecast.notnull()]
  #stock_ids = mypf['Symbol'].unique()

  #stock_ids.sort()
  return stock_ids

# get features from screener data
def get_screener_features():
  myscreen_df = get_myscreen_df()
  cols = ['Symbol', 'EPS', 'MedPE', 'ROCE%', 'ROE%', 'CapType']
  return myscreen_df[cols]

# get relative strength
def get_relative_strength(stock_list):

    # Dictionary to store stock tickers and their corresponding percentage price change
    stock_changes = {}

    # Loop through each stock and fetch its price data
    for stock in stock_list:
        try:
            # Download the stock data for the given date range
            stock_data = yfin.Ticker(stock + '.NS').history(period='1mo', interval='1d')[map(str.title, ['open', 'close', 'low', 'high', 'volume'])]

            # Calculate the percentage change for the stock
            if len(stock_data) > 0:
                start_price = stock_data['Close'].iloc[0]
                end_price = stock_data['Close'].iloc[-1]
                percent_change = round(((end_price - start_price) / start_price) * 100, 2)
                stock_changes[stock] = percent_change
            else:
                stock_changes[stock] = np.nan  # If no data is available, set to NaN

        except Exception as e:
            print(f"Error fetching data for {stock}: {e}")
            stock_changes[stock] = np.nan

    # Create a DataFrame with stock tickers and their percentage changes
    df = pd.DataFrame(list(stock_changes.items()), columns=['Symbol', 'Percent_Change'])

    # Drop any stocks with missing data (NaN values)
    df = df.dropna()

    # Calculate the percentile rank based on percentage change
    df['RSP'] = round(df['Percent_Change'].rank(pct=True) * 100, 2)
    cols = ['Symbol', 'RSP']
    df = df[cols]
    # Sort by percentile rank (optional)
    df = df.sort_values(by='RSP', ascending=False).reset_index(drop=True)

    return df

In [6]:
# function to get stock technicals
def stock_prec_dev(stock_symbol):
    #stock_symbol = 'ULTRACEMCO.NS'
    short_window = 20
    mid_window = 50
    long_window = 200
    moving_avg = 'SMA'

    start = datetime.datetime(*map(int, start_date.split('-')))
    end = datetime.datetime(*map(int, end_date.split('-')))

    stock_df = yfin.Ticker(stock_symbol + '.NS').history(period='max', interval='1d')[map(str.title, ['open', 'close', 'low', 'high', 'volume'])]

    stock_df['Max'] = round(max(stock_df['Close']),2)
    stock_df = stock_df[(stock_df.index <= end_date) & (stock_df.index >= start_date)]
    stock_df['200_SMA'] = round(stock_df['Close'].rolling(window = 200, min_periods = 1).mean(),0)
    stock_df['Dev%_200'] = round((stock_df['Close'] - stock_df['200_SMA'])*100/stock_df['200_SMA'],2)
    stock_df.dropna(axis = 0, inplace = True) # remove any null rows

    stock_df['20_SMA'] = stock_df['Close'].rolling(window=20).mean()
    stock_df['50_SMA'] = stock_df['Close'].rolling(window=50).mean()
    stock_df['Symbol'] = stock_symbol

    stock_df['Close'] = round(stock_df['Close'],2)
    stock_df['Min'] = round(min(stock_df['Close']),2)
    stock_df['RSI_14'] = ta.momentum.RSIIndicator(close=stock_df['Close'], window=14).rsi()
    stock_df['RSI_14'] = round(stock_df['RSI_14'],0)
    stock_df['Prev_Close'] = stock_df['Close'].shift(1)
    stock_df.drop(['Open', 'Low', 'High', 'Volume'], axis=1, inplace=True)
    stock_df = stock_df.tail(1)

    max_SMA = max(stock_df['20_SMA'].item(), stock_df['50_SMA'].item(), stock_df['200_SMA'].item())
    min_SMA = min(stock_df['20_SMA'].item(), stock_df['50_SMA'].item(), stock_df['200_SMA'].item())
    ABS_Spread = max_SMA - min_SMA
    stock_df['Spread%'] = round((ABS_Spread / stock_df['200_SMA'].item()) * 100,2)

    return stock_df

# function to compute stock attributes
def get_common_features(stock_ids, df_mypf):

  df_prec_dev = pd.DataFrame()
  df_tmp = get_screener_features()
  df_rs = get_relative_strength(stock_ids)

  for stock_id in stock_ids:
      tmp = stock_prec_dev(stock_id)
      tmp = tmp.reset_index()
      df_prec_dev = pd.concat([df_prec_dev, tmp], ignore_index = True)
  df_prec_dev = pd.merge(df_prec_dev, df_mypf, on= 'Symbol')
  df_prec_dev = pd.merge(df_prec_dev, df_tmp, on= 'Symbol', how='left')
  df_prec_dev = pd.merge(df_prec_dev, df_rs, on= 'Symbol', how='left')
  #print(df_prec_dev.columns)
  df_prec_dev['Curr_PE'] = round(df_prec_dev['Close']/df_prec_dev['EPS'],1)
  df_prec_dev['Dev%_PE'] = round((df_prec_dev['Curr_PE'] - df_prec_dev['MedPE'])*100/df_prec_dev['MedPE'],2)
  df_prec_dev['Conviction'] = df_prec_dev['Conviction'] + '-' + df_prec_dev['CapType']
  return df_prec_dev

# function to arrange stock features
def arrange_features(df_stocks, common_cols, diff_cols):
  df_stocks_common = df_stocks[common_cols].drop_duplicates()
  df_stocks_diff = df_stocks[diff_cols]
  df_stocks_diff['Investment'] = df_stocks_diff['AvgCost'] * df_stocks_diff['Shares']
  df_stocks_diff = df_stocks_diff.groupby(['Symbol'])[['Shares', 'Investment']].aggregate(['sum']).reset_index()
  df_stocks_diff.columns = ['Symbol', 'Shares', 'Investment']
  df_stocks_diff['AvgCost'] = round(df_stocks_diff['Investment']/df_stocks_diff['Shares'],2)
  df_stocks = pd.merge(df_stocks_diff, df_stocks_common, on='Symbol')
  return df_stocks

# plot fact distribution across dimension
def plot_pie_chart(df, dimension, fact):
  # grouping the data by category and calculating the sum of fact for each type
  grouped_data = df.groupby(dimension)[fact].sum()

  # sorting the grouped data in descending order
  grouped_data = grouped_data.sort_values(ascending=False)

  # creating a pie chart
  grouped_data.plot.pie(autopct='%1.1f%%', startangle=90, figsize=(6, 6))

  # adding a title and displaying the plot
  plt.title(f'{dimension} {fact} Distribution')
  plt.ylabel('')  # To hide the y-label
  plt.show()

In [7]:
# function to get portfolio features

def get_portfolio_features(df_common_features):

  print_date_time()
  print('-------------------')

  #df_common_features["Target"] = df_common_features["Target"].fillna(df_common_features["Max"])
  df_common_features['NTT'] = np.where(df_common_features['Strategy']== 'NTT', df_common_features["Target"], df_common_features['Max'])
  df_common_features['LTT'] = np.where(df_common_features['Strategy']== 'BTT', df_common_features["Target"], df_common_features['Max'])
  df_common_features['BOL'] = df_common_features['Min']

  tmp_df = df_common_features[df_common_features['Symbol'].isin(mypf_df[mypf_df['InPortfolio'] != 'NA'].Symbol.values)]
  print('qualified stocks: '+str(len(tmp_df['Symbol'].unique())))
  tmp_df1 = tmp_df[tmp_df['LatestQtr'] == 1]
  print('with latest results: '+str(len(tmp_df1['Symbol'].unique())))
  tmp_df1 = tmp_df1[tmp_df1['StarStock'] == 1]
  print('still star stocks: '+str(len(tmp_df1['Symbol'].unique())))
  tmp_df['Investment'] = tmp_df['AvgCost'] * tmp_df['Shares']
  tmp_df['Current'] = round(tmp_df['Close'] * tmp_df['Shares'],0)
  tmp_df['Previous'] = tmp_df['Prev_Close'] * tmp_df['Shares']
  tmp_df['EstimatedST'] = tmp_df['NTT'] * tmp_df['Shares']
  tmp_df['EstimatedLT'] = tmp_df['LTT'] * tmp_df['Shares']
  tmp_df['Current P/L'] = round((tmp_df['Current'] - tmp_df['Investment']),0)
  tmp_df['Today P/L%'] = round((tmp_df['Current'] - tmp_df['Previous'])*100/tmp_df['Previous'],2)
  tmp_df['Current P/L%'] = round((tmp_df['Current'] - tmp_df['Investment'])*100/tmp_df['Investment'],2)
  tmp_df['EstimatedST P/L%'] = round((tmp_df['EstimatedST'] - tmp_df['Investment'])*100/tmp_df['Investment'],2)
  tmp_df['EstimatedLT P/L%'] = round((tmp_df['EstimatedLT'] - tmp_df['Investment'])*100/tmp_df['Investment'],2)
  tmp_df['NTT%'] = round((tmp_df['NTT'] - tmp_df['Close'])*100/tmp_df['Close'],2)
  tmp_df['LTT%'] = round((tmp_df['LTT'] - tmp_df['Close'])*100/tmp_df['Close'],2)
  tmp_df['Gained%'] = round((tmp_df['Close'] - tmp_df['BOL'])*100/tmp_df['BOL'],2)
  investment = round(sum(tmp_df['AvgCost']*tmp_df['Shares']),0)
  current = round(sum(tmp_df['Close']*tmp_df['Shares']),0)
  tmp_df['InitAlloc%'] = round(tmp_df['Investment']*100/investment,2)
  tmp_df['CurrAlloc%'] = round(tmp_df['Current']*100/current,2)
  tmp_df['FTT'] = tmp_df['LTT']
  tmp_df.loc[tmp_df['Strategy'] == 'NTT', 'FTT'] = tmp_df['NTT']
  tmp_df['FTT%'] = tmp_df['LTT%']
  tmp_df.loc[tmp_df['Strategy'] == 'NTT', 'FTT%'] = tmp_df['NTT%']
  tmp_df['FTT Amt'] = round(tmp_df['FTT%'] * tmp_df['Current']/100,0)
  tmp_df['OTT%'] = round((tmp_df['FTT'] - tmp_df['AvgCost'])*100/tmp_df['AvgCost'],2)
  tmp_df['RRR Ind'] = round(tmp_df['Current P/L']/tmp_df['FTT Amt'],2)
  tmp_df['Risk Ind'] = round(tmp_df['Current P/L%']*tmp_df['CurrAlloc%'],0)

  return tmp_df

# function to print portfolio features
def print_portfolio_stats(df_portfolio_features, myinvmt_df):
  from pyxirr import xirr

  total_booked_amt, reserve_amt, cy_booked_amt, py_booked_amt = get_amt()

  dates = myinvmt_df['Date'].values
  dates = np.append(dates, datetime.date.today().strftime('%d-%b-%y'))
  investment = myinvmt_df['Investment'].values
  dates= pd.to_datetime(dates)

  current = round(sum(df_portfolio_features['Close']*df_portfolio_features['Shares']),0) + reserve_amt
  investment_xirr = np.append(investment, current)
  cagr = round(xirr(pd.DataFrame({"dates": dates, "amounts": investment_xirr}))*100,2)

  investment = -sum(investment)
  invested = round(sum(df_portfolio_features['AvgCost']*df_portfolio_features['Shares']),0) + reserve_amt
  previous = round(sum(df_portfolio_features['Prev_Close']*df_portfolio_features['Shares']),0) + reserve_amt
  cy_invested = investment + py_booked_amt

  today_pnl_amount = current-previous
  today_pnl_percentage = round((current-previous)*100/previous,2)

  curr_pnl_amount = current-invested
  curr_pnl_percentage = round((curr_pnl_amount)*100/(cy_invested),2)

  cy_pnl_amount = cy_booked_amt + curr_pnl_amount
  cy_pnl_percentage = round((cy_pnl_amount)*100/cy_invested,2)

  overall_pnl_amount = total_booked_amt + curr_pnl_amount
  overall_pnl_percentage = round((overall_pnl_amount)*100/investment,2)

  estimate_st = round(sum(df_portfolio_features['FTT']*df_portfolio_features['Shares']),0)  + reserve_amt
  est_st_pnl_amount = estimate_st-current
  est_st_pnl_percentage = round((est_st_pnl_amount)*100/current,2)

  estimate_lt = round(sum(df_portfolio_features['LTT']*df_portfolio_features['Shares']),0)  + reserve_amt
  est_lt_pnl_amount = estimate_lt-current
  est_lt_pnl_percentage = round((est_lt_pnl_amount)*100/current,2)

  total_profit = round(sum(df_portfolio_features[df_portfolio_features['Current P/L%'] > 0]['Current']) - sum(df_portfolio_features[df_portfolio_features['Current P/L%'] > 0]['Investment']),0)
  total_loss = round(sum(df_portfolio_features[df_portfolio_features['Current P/L%'] < 0]['Current']) - sum(df_portfolio_features[df_portfolio_features['Current P/L%'] < 0]['Investment']),0)

  cy_booked_percentage = round((cy_booked_amt)*100/current,2)
  py_booked_percentage = round((py_booked_amt)*100/investment,2)
  total_booked_percentage = round((total_booked_amt)*100/investment,2)

  print('-------------------')
  print('Initial Investment: ', format_amt(investment))
  print('CY Investment: ', format_amt(cy_invested))
  print('Reserve: ', format_amt(reserve_amt))
  print('Current: ',  format_amt(current))
  print('-------------------')
  print('Today PnL: '+ '{} ({}%)'.format(format_amt(today_pnl_amount), today_pnl_percentage))
  print('Current PnL: '+ '{} ({}%)'.format(format_amt(curr_pnl_amount), curr_pnl_percentage))
  print('CY Booked + Current PnL: '+ '{} ({}%)'.format(format_amt(cy_pnl_amount), cy_pnl_percentage))
  print('-------------------')
  print('Total profit: ', format_amt(total_profit))
  print('Total loss: ', format_amt(total_loss))
  print('-------------------')
  print('Total Booked + Current PnL: '+ '{} ({}%)'.format(format_amt(overall_pnl_amount), overall_pnl_percentage))
  print('Total Booked PnL: '+ '{} ({}%)'.format(format_amt(total_booked_amt), total_booked_percentage))
  print('Curr Year Booked PnL: '+ '{} ({}%)'.format(format_amt(cy_booked_amt), cy_booked_percentage))
  print('Prev Year Booked PnL: '+ '{} ({}%)'.format(format_amt(py_booked_amt), py_booked_percentage))
  print('===================')
  print('Est FTT: ',  format_amt(estimate_st))
  print('Est FTT PnL: '+ '{} ({}%)'.format(format_amt(est_st_pnl_amount), est_st_pnl_percentage))

  print('===================')
  print('Deployed: ', format_amt(investment))

  print('Current: ', format_amt(current))

  print('CAGR/XIRR %: '+'{}%'.format(cagr))

In [8]:
# get start and end date
start_date, end_date = get_start_end_date()

# get portfolio and prospects data
mypfs_df = get_mypfs_df()
mypps_df = get_mypps_df()
myinvmt_df = get_myinvmt_df()

# merge above datasets
mypf_df = pd.merge(mypfs_df, mypps_df, on="Symbol")

# seggregate dm and sv portfolio
dm_pf = mypf_df[mypf_df['InPortfolio'] == 'DM']
sv_pf = mypf_df[mypf_df['InPortfolio'] == 'SV']

# build portfolio stock dataframe
dm_stocks = get_stock_ids(dm_pf)
sv_stocks = get_stock_ids(sv_pf)
df_stocks = pd.concat([dm_pf,sv_pf], ignore_index = True)

# arrange common and diff stock features
common_cols = ['Symbol', 'Target', 'Criteria', 'Strategy', 'CumlRnk', 'LatestQtr', 'StarStock', 'Conviction', 'Category', 'InFolio', 'XIRR', 'MBQ']
diff_cols = ['Symbol', 'AvgCost', 'Shares']
df_stocks = arrange_features(df_stocks, common_cols, diff_cols)

# get common features
stock_ids = df_stocks['Symbol'].values
df_common_features = get_common_features(stock_ids, df_stocks)

df_common_features.reset_index(drop=True, inplace=True)
df_common_features.drop(['Date'], axis=1, inplace=True)
# get and print portfolio features
df_portfolio_features = get_portfolio_features(df_common_features)

print_portfolio_stats(df_portfolio_features, myinvmt_df)

df = df_portfolio_features
#plot_pie_chart(df, 'CapType', 'Current')
list_ox40n = list(df[df['MBQ'].str.contains('OX40N', na=False)]['Symbol'].values)

Run date time (IST): 2026-03-16 15:36:43
-------------------
qualified stocks: 86
with latest results: 26
still star stocks: 15
-------------------
Initial Investment:  1.36 C
CY Investment:  1.62 C
Reserve:  66.25 K
Current:  1.32 C
-------------------
Today PnL: -1.23 L (-0.93%)
Current PnL: -45.06 L (-27.73%)
CY Booked + Current PnL: -29.38 L (-18.08%)
-------------------
Total profit:  86.28 K
Total loss:  -45.93 L
-------------------
Total Booked + Current PnL: -2.40 L (-1.77%)
Total Booked PnL: 42.66 L (31.48%)
Curr Year Booked PnL: 15.68 L (11.89%)
Prev Year Booked PnL: 26.98 L (19.91%)
===================
Est FTT:  2.47 C
Est FTT PnL: 1.15 C (87.53%)
===================
Deployed:  1.36 C
Current:  1.32 C
CAGR/XIRR %: -1.36%

In [9]:
# top 5 near their targets
cols = ['Symbol', 'Today P/L%', 'Current P/L%', 'FTT%', 'OTT%', 'FTT Amt', 'Current P/L', 'Current', 'FTT', 'Dev%_PE', 'RSI_14','Conviction', 'Spread%',  'CumlRnk', 'RRR Ind', 'CurrAlloc%', 'Gained%', 'Criteria', 'Strategy', 'Category']
df_tmp = df_portfolio_features[~df_portfolio_features['Symbol'].isin(['ENRIN','BLUSPRING','DIGITIDE'])]
df_tmp = df_tmp.sort_values(by = 'FTT Amt', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
19,COALINDIA,-1.43,13.19,3.96,17.67,6744.0,19850.0,170311.0,478.51,36.30,63.0,L-LC,13.34,185.0,2.94,1.30,32.26,XY25,ATH,MINING
50,MASFIN,-2.39,-9.86,34.86,21.57,30788.0,-9660.0,88320.0,397.04,-22.31,34.0,H-SC,2.94,167.0,-0.31,0.67,22.48,XR,ATH,FINANCE
77,TTKPRESTIG,-9.23,-36.04,56.50,0.09,36415.0,-36325.0,64452.0,770.00,49.63,42.0,M-SC,15.97,250.0,-1.00,0.49,8.90,OX40N,NTT,DURABLES
37,ICICIGI,0.73,-1.98,21.75,19.34,42663.0,-3956.0,196153.0,2252.93,-17.63,42.0,X-MC,2.01,66.0,-0.09,1.50,8.43,X40,ATH,INSURANCE
2,ABBOTINDIA,-1.08,-10.53,31.96,18.07,51142.0,-18835.0,160020.0,35195.00,-23.83,46.0,X-MC,10.93,58.0,-0.37,1.22,1.45,X40,ATH,PHARMA

In [10]:
# top 5 today
df_tmp = df_portfolio_features.sort_values(by = 'Today P/L%', ascending=False)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
45,ITC,2.26,-18.81,46.63,19.06,128788.0,-63974.0,276192.0,452.00,-55.52,41.0,X-LC,17.12,1.0,-0.50,2.11,2.26,X40,NTT,FMCG
81,VBL,1.46,-17.76,64.96,35.67,168741.0,-56080.0,259762.0,671.64,-27.46,31.0,X-LC,5.92,13.0,-0.33,1.98,1.46,X40N,ATH,FMCG
10,BAJAJHLDNG,1.31,-13.88,50.05,29.22,81945.0,-26398.0,163727.0,14451.52,-20.42,26.0,X-LC,13.17,28.0,-0.32,1.25,1.31,X40,ATH,FINANCE
42,INDUSINDBK,1.31,-39.09,118.17,32.89,55573.0,-30178.0,47028.0,1800.00,-321.29,32.0,L-MC,9.41,258.0,-0.54,0.36,29.51,XR,NTT,BANKS
18,CERA,1.25,-40.10,106.84,23.89,112568.0,-70542.0,105361.0,9475.00,-42.24,33.0,H-SC,17.64,153.0,-0.63,0.80,1.25,OX40N,NTT,CERAMICS

In [11]:
# bottom 5 today
df_tmp = df_portfolio_features.sort_values(by = 'Today P/L%', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
77,TTKPRESTIG,-9.23,-36.04,56.50,0.09,36415.0,-36325.0,64452.0,770.00,49.63,42.0,M-SC,15.97,250.0,-1.00,0.49,8.90,OX40N,NTT,DURABLES
11,BANDHANBNK,-7.38,-21.81,146.09,92.42,318190.0,-60755.0,217804.0,400.00,86.78,41.0,H-SC,9.38,174.0,-0.19,1.66,19.98,XY24,NTT,BANKS
69,SURYODAY,-4.58,-28.26,71.51,23.03,91861.0,-50612.0,128459.0,216.00,40.35,46.0,H-SC,7.67,166.0,-0.55,0.98,27.46,XR,NTT,BANKS
55,RAJESHEXPO,-4.54,-79.70,393.05,0.07,109429.0,-109336.0,27841.0,518.00,920.20,20.0,L-SC,24.52,268.0,-1.00,0.21,0.00,OX40N,NTT,JEWELLERY
31,HAPPSTMNDS,-4.04,-52.89,292.40,84.85,176539.0,-67789.0,60376.0,1480.71,-44.02,48.0,H-SC,27.77,152.0,-0.38,0.46,11.81,AR,ATH,IT

In [12]:
# top 5 to exit based on CumlRnk
df_tmp = df_portfolio_features[~df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])]
df_tmp = df_tmp[(df_tmp['Current P/L%'] > -1) & (df_tmp['Current P/L%'] < 1)].sort_values(by = 'CumlRnk', ascending=False)
df_tmp[cols].head()

Empty DataFrame
Columns: [Symbol, Today P/L%, Current P/L%, FTT%, OTT%, FTT Amt, Current P/L, Current, FTT, Dev%_PE, RSI_14, Conviction, Spread%, CumlRnk, RRR Ind, CurrAlloc%, Gained%, Criteria, Strategy, Category]
Index: []

In [13]:
# OX40N stocks to exit
df_tmp = df_portfolio_features[(df_portfolio_features['Symbol'].isin(list_ox40n))].sort_values(by = 'Current P/L%', ascending=False)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
27,FINCABLES,-1.29,7.02,94.27,107.91,148961.0,10371.0,158015.0,1641.55,-3.60,48.0,M-SC,7.78,220.0,0.07,1.20,18.88,OX40N,ATH,CABLES
77,TTKPRESTIG,-9.23,-36.04,56.50,0.09,36415.0,-36325.0,64452.0,770.00,49.63,42.0,M-SC,15.97,250.0,-1.00,0.49,8.90,OX40N,NTT,DURABLES
66,SIS,-0.77,-36.33,90.44,21.26,63940.0,-40333.0,70699.0,528.00,1651.81,30.0,H-SC,12.25,168.0,-0.63,0.54,0.00,OX40N,NTT,MISC
72,TATAELXSI,-1.24,-39.44,118.00,32.03,94214.0,-51993.0,79842.0,9161.00,-24.23,25.0,H-SC,18.16,158.0,-0.55,0.61,0.00,OX40N,NTT,IT
70,SYMPHONY,-1.95,-40.02,66.68,-0.03,68444.0,-68496.0,102645.0,1306.00,-51.78,39.0,M-SC,14.48,205.0,-1.00,0.78,3.80,OX40N,NTT,DURABLES

In [14]:
# top 5 to book for rotation
df_tmp = df_portfolio_features[(df_portfolio_features['Current P/L%'] > 20) ].sort_values(by = 'CumlRnk', ascending=False)
df_tmp[cols].head()

Empty DataFrame
Columns: [Symbol, Today P/L%, Current P/L%, FTT%, OTT%, FTT Amt, Current P/L, Current, FTT, Dev%_PE, RSI_14, Conviction, Spread%, CumlRnk, RRR Ind, CurrAlloc%, Gained%, Criteria, Strategy, Category]
Index: []

In [15]:
# top 5 to monitor for exit
df_tmp = df_portfolio_features[~df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])]
df_tmp = df_tmp[(df_tmp['Current P/L%'] > 0) ].sort_values(by = 'Dev%_PE', ascending=False)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
19,COALINDIA,-1.43,13.19,3.96,17.67,6744.0,19850.0,170311.0,478.51,36.30,63.0,L-LC,13.34,185.0,2.94,1.30,32.26,XY25,ATH,MINING
27,FINCABLES,-1.29,7.02,94.27,107.91,148961.0,10371.0,158015.0,1641.55,-3.60,48.0,M-SC,7.78,220.0,0.07,1.20,18.88,OX40N,ATH,CABLES
1,ABB,-2.73,14.08,27.60,45.57,82376.0,36845.0,298464.0,7934.00,-26.69,60.0,H-MC,11.45,125.0,0.45,2.27,32.54,AR,NTT,ELECTRICAL

In [16]:
# top 5 to book for rotation from weak conviction
df_tmp = df_portfolio_features[~df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])]
df_tmp = df_tmp[~df_tmp['Criteria'].isin(['XY25','XY24','X40', 'X40N'])].sort_values(by = 'RRR Ind', ascending=False)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
1,ABB,-2.73,14.08,27.60,45.57,82376.0,36845.0,298464.0,7934.00,-26.69,60.0,H-MC,11.45,125.0,0.45,2.27,32.54,AR,NTT,ELECTRICAL
27,FINCABLES,-1.29,7.02,94.27,107.91,148961.0,10371.0,158015.0,1641.55,-3.60,48.0,M-SC,7.78,220.0,0.07,1.20,18.88,OX40N,ATH,CABLES
40,INDIAMART,0.29,-9.41,128.21,106.72,143241.0,-11612.0,111724.0,4810.62,-59.18,42.0,H-SC,9.78,140.0,-0.08,0.85,11.76,AR,ATH,MISC
85,ZYDUSLIFE,-2.10,-6.47,45.02,35.63,88241.0,-13569.0,196005.0,1286.17,-18.47,42.0,H-MC,5.09,120.0,-0.15,1.49,9.12,AR,ATH,PHARMA
84,WIPRO,-1.25,-19.97,115.26,72.27,156294.0,-33847.0,135601.0,420.00,-27.84,28.0,M-LC,15.54,98.0,-0.22,1.03,0.00,XR,NTT,IT

In [17]:
# top 5 to accumulate based on lowest RSI_14
df_tmp = df_portfolio_features[df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])].sort_values(by = 'RSI_14', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
58,RELAXO,-2.85,-62.92,310.76,52.31,167263.0,-91336.0,53824.0,1176.00,-60.51,15.0,X-SC,20.88,92.0,-0.55,0.41,0.0,X40N,NTT,FOOTWEAR
12,BATAINDIA,-3.07,-56.27,209.17,35.20,117700.0,-72400.0,56270.0,2096.00,-26.21,16.0,X-SC,27.51,91.0,-0.62,0.43,0.0,X40,NTT,FOOTWEAR
8,AWL,-0.34,-40.67,181.49,67.02,383692.0,-144897.0,211412.0,485.00,-68.10,17.0,X-SC,24.35,81.0,-0.38,1.61,0.0,XY24,NTT,FMCG
3,ACC,-0.23,-38.54,184.45,74.81,303944.0,-103344.0,164784.0,3906.00,-56.56,17.0,X-SC,14.12,85.0,-0.34,1.26,0.0,XY24,BTT,CEMENT
53,PGHH,-3.43,-23.86,73.38,32.01,119298.0,-50944.0,162576.0,17616.87,-48.47,17.0,X-MC,12.38,57.0,-0.43,1.24,0.0,X40,ATH,FMCG

In [18]:
# top 5 to accumulate based on Spread and CumlRnk
df_tmp = df_portfolio_features[df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])]
df_tmp = df_tmp[(df_tmp['CumlRnk'] < 100)].sort_values(by = 'Spread%', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
78,UNITDSPR,0.23,-3.22,24.79,20.77,56172.0,-7551.0,226593.0,1644.00,-14.18,41.0,X-MC,1.05,64.0,-0.13,1.73,3.27,X40N,NTT,BREWERIES
37,ICICIGI,0.73,-1.98,21.75,19.34,42663.0,-3956.0,196153.0,2252.93,-17.63,42.0,X-MC,2.01,66.0,-0.09,1.50,8.43,X40,ATH,INSURANCE
75,TMPV,0.10,-28.43,90.84,36.58,231337.0,-101177.0,254664.0,600.00,-84.72,29.0,X-LC,2.13,4.0,-0.44,1.94,0.10,XY24,NTT,AUTO
22,DABUR,1.18,-10.29,60.18,43.70,133926.0,-25526.0,222542.0,735.00,-18.54,32.0,X-MC,2.34,70.0,-0.19,1.70,3.21,XY24,BTT,FMCG
38,ICICIPRULI,0.03,-3.38,35.30,30.73,67194.0,-6654.0,190351.0,790.00,-29.28,25.0,X-MC,2.83,78.0,-0.10,1.45,8.90,X40,ATH,INSURANCE

In [19]:
# top 5 to accumulate based on lowest Gained%
df_tmp = df_portfolio_features[df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])].sort_values(by = 'Gained%', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
3,ACC,-0.23,-38.54,184.45,74.81,303944.0,-103344.0,164784.0,3906.00,-56.56,17.0,X-SC,14.12,85.0,-0.34,1.26,0.0,XY24,BTT,CEMENT
12,BATAINDIA,-3.07,-56.27,209.17,35.20,117700.0,-72400.0,56270.0,2096.00,-26.21,16.0,X-SC,27.51,91.0,-0.62,0.43,0.0,X40,NTT,FOOTWEAR
9,BAJAJHFL,-1.02,-27.37,123.22,62.13,244364.0,-74731.0,198315.0,181.50,-40.19,25.0,X-MC,19.05,60.0,-0.31,1.51,0.0,X40N,ATH,FINANCE
8,AWL,-0.34,-40.67,181.49,67.02,383692.0,-144897.0,211412.0,485.00,-68.10,17.0,X-SC,24.35,81.0,-0.38,1.61,0.0,XY24,NTT,FMCG
21,COLPAL,-0.82,-26.30,92.00,41.51,178581.0,-69255.0,194110.0,3726.84,-10.78,30.0,X-MC,4.15,62.0,-0.39,1.48,0.0,XY25,ATH,FMCG

In [20]:
# top 5 to accumulate based on lowest CurrAlloc%
df_tmp = df_portfolio_features[df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])].sort_values(by = 'CurrAlloc%', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
58,RELAXO,-2.85,-62.92,310.76,52.31,167263.0,-91336.0,53824.0,1176.00,-60.51,15.0,X-SC,20.88,92.0,-0.55,0.41,0.00,X40N,NTT,FOOTWEAR
12,BATAINDIA,-3.07,-56.27,209.17,35.20,117700.0,-72400.0,56270.0,2096.00,-26.21,16.0,X-SC,27.51,91.0,-0.62,0.43,0.00,X40,NTT,FOOTWEAR
54,QUESS,-3.59,-28.15,142.02,73.90,108976.0,-30060.0,76733.0,424.00,-61.43,30.0,X-SC,18.81,80.0,-0.28,0.58,0.00,XY24,NTT,MISC
36,HONAUT,-2.48,-24.02,99.14,51.31,145265.0,-46313.0,146525.0,58357.33,-36.81,32.0,X-SC,14.14,90.0,-0.32,1.12,0.00,X40N,ATH,ELECTRICAL
51,MEDANTA,-2.92,-10.97,42.77,27.12,67218.0,-19356.0,157161.0,1486.00,-13.76,32.0,X-SC,9.18,87.0,-0.29,1.20,1.05,XY24,NTT,HEALTHCARE

In [21]:
# top 5 to accumulate based on CumlRnk
df_tmp = df_portfolio_features.sort_values(by = 'CumlRnk', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
45,ITC,2.26,-18.81,46.63,19.06,128788.0,-63974.0,276192.0,452.00,-55.52,41.0,X-LC,17.12,1.0,-0.50,2.11,2.26,X40,NTT,FMCG
73,TCS,-0.05,-29.27,78.96,26.57,258713.0,-135622.0,327651.0,4311.59,-40.02,19.0,X-LC,15.19,2.0,-0.52,2.50,0.00,X40,ATH,IT
43,INFY,0.12,-14.92,57.79,34.24,153841.0,-46681.0,266207.0,1972.00,-32.87,24.0,X-LC,13.42,3.0,-0.30,2.03,0.12,X40,NTT,IT
75,TMPV,0.10,-28.43,90.84,36.58,231337.0,-101177.0,254664.0,600.00,-84.72,29.0,X-LC,2.13,4.0,-0.44,1.94,0.10,XY24,NTT,AUTO
34,HCLTECH,0.24,-13.78,43.62,23.83,90987.0,-33334.0,208590.0,1908.19,-9.43,27.0,X-LC,10.13,8.0,-0.37,1.59,0.24,X40,ATH,IT

In [22]:
# top 5 for average up
df_tmp = df_portfolio_features[(df_portfolio_features['Dev%_200'] > 5)].sort_values(by = 'CurrAlloc%', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
19,COALINDIA,-1.43,13.19,3.96,17.67,6744.0,19850.0,170311.0,478.51,36.30,63.0,L-LC,13.34,185.0,2.94,1.30,32.26,XY25,ATH,MINING
1,ABB,-2.73,14.08,27.60,45.57,82376.0,36845.0,298464.0,7934.00,-26.69,60.0,H-MC,11.45,125.0,0.45,2.27,32.54,AR,NTT,ELECTRICAL

In [23]:
# top 5 RSP
df_tmp = df_portfolio_features.sort_values(by = 'RSP', ascending=False)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
19,COALINDIA,-1.43,13.19,3.96,17.67,6744.0,19850.0,170311.0,478.51,36.30,63.0,L-LC,13.34,185.0,2.94,1.30,32.26,XY25,ATH,MINING
1,ABB,-2.73,14.08,27.60,45.57,82376.0,36845.0,298464.0,7934.00,-26.69,60.0,H-MC,11.45,125.0,0.45,2.27,32.54,AR,NTT,ELECTRICAL
27,FINCABLES,-1.29,7.02,94.27,107.91,148961.0,10371.0,158015.0,1641.55,-3.60,48.0,M-SC,7.78,220.0,0.07,1.20,18.88,OX40N,ATH,CABLES
69,SURYODAY,-4.58,-28.26,71.51,23.03,91861.0,-50612.0,128459.0,216.00,40.35,46.0,H-SC,7.67,166.0,-0.55,0.98,27.46,XR,NTT,BANKS
2,ABBOTINDIA,-1.08,-10.53,31.96,18.07,51142.0,-18835.0,160020.0,35195.00,-23.83,46.0,X-MC,10.93,58.0,-0.37,1.22,1.45,X40,ATH,PHARMA

In [24]:
# Top N allocation
df_tmp = df_portfolio_features.sort_values(by = 'CurrAlloc%', ascending=False)
top_n_values = [10, 25, 50]

sum_df = pd.DataFrame({
    'Top_N': top_n_values,
    'Sum_Alloc%': [df_tmp['CurrAlloc%'].head(n).sum() for n in top_n_values]
})

sum_df

   Top_N  Sum_Alloc%
0     10       20.69
1     25       45.59
2     50       78.05

In [25]:
# market-cap-wise allocation
df_tmp = df_portfolio_features[cols]
df_tmp.groupby(df_tmp['Conviction'].str[-2:])['CurrAlloc%'].sum().sort_values(ascending=False)

Conviction
SC    44.37
MC    30.46
LC    25.20
Name: CurrAlloc%, dtype: float64

In [26]:
# criteria-wise allocation
df_portfolio_features.groupby('Criteria')['CurrAlloc%'].sum().sort_values(ascending=False)

Criteria
XY24     27.12
X40      24.02
X40N     15.10
AR        9.20
XY25      8.81
XR        8.20
OX40N     6.82
SR        0.76
Name: CurrAlloc%, dtype: float64

In [27]:
# conviction-wise allocation
df_portfolio_features.groupby('Conviction')['CurrAlloc%'].sum().sort_values(ascending=False)

Conviction
X-MC    22.99
X-LC    21.67
H-SC    21.60
X-SC    12.10
M-SC    10.10
H-MC     5.07
M-MC     2.04
L-LC     1.30
H-LC     1.20
M-LC     1.03
L-SC     0.57
L-MC     0.36
Name: CurrAlloc%, dtype: float64

In [28]:
# sector-wise stats
df_tmp = df_portfolio_features.groupby('Category')[['CurrAlloc%', 'Current', 'Current P/L', 'FTT Amt']].sum().sort_values(by=['Current', 'Current P/L'], ascending=False)
df_tmp['Current P/L%'] = round(df_tmp['Current P/L'] * 100 / df_tmp['Current'], 2)
df_tmp['FTT%'] = round(df_tmp['FTT Amt'] * 100 / df_tmp['Current'], 2)
cols = ['CurrAlloc%', 'Current P/L%', 'FTT%']
df_tmp[cols].sort_values(by=['CurrAlloc%'], ascending=False)

               CurrAlloc%  Current P/L%    FTT%
Category
FMCG                15.35        -24.18   68.28
FINANCE             12.95        -26.40   77.91
IT                  11.70        -46.87  121.62
MISC                 6.99        -46.30  109.86
ELECTRICAL           6.67        -10.70   53.09
PAINTS               5.12        -46.64   72.11
INSURANCE            4.85         -6.75   43.28
PHARMA               4.18         -7.20   40.93
AUTO                 3.64        -36.80   91.08
BANKS                3.00        -35.99  118.39
AC                   2.15        -13.25   43.96
HEALTHCARE           1.94        -40.65   77.35
FOOTWEAR             1.85        -82.04  155.03
DURABLES             1.84        -59.49   98.29
TRAVEL               1.82        -87.28  181.05
BREWERIES            1.73         -3.33   24.79
APPARELS             1.61        -26.95   70.26
REALTY               1.44        -17.31   36.58
REFINERIES           1.37        -11.67   39.92
CERAMICS             1.36        -71.70  123.86
MINING               1.30         11.66    3.96
CEMENT               1.26        -62.71  184.45
CABLES               1.20          6.56   94.27
JEWELLERY            1.12       -118.22  194.04
ENGINEERING          1.09        -69.15  146.52
CHEMICALS            0.94       -114.25  289.04
ENTERTAINMENT        0.77        -92.32  207.02
TEXTILES             0.43        -65.34  112.48
HOTELS               0.36       -140.41  225.20

In [29]:
# money to be made criteria-wise
df_portfolio_features.groupby('Criteria')['FTT Amt'].agg(['sum', 'count']).sort_values(by='sum', ascending=False)

                sum  count
Criteria
XY24      4039880.0     21
X40       1724585.0     15
XR        1416753.0     12
AR        1363680.0     10
X40N      1320518.0     10
OX40N      896195.0     10
XY25       461700.0      6
SR         319016.0      2

In [30]:
# money to be made conviction-wise
df_portfolio_features.groupby('Conviction')['FTT Amt'].agg(['sum', 'count']).sort_values(by='sum', ascending=False)

                  sum  count
Conviction
H-SC        3961124.0     24
X-MC        1719858.0     15
X-LC        1633118.0     12
X-SC        1595709.0     10
M-SC        1591776.0     14
H-MC         412691.0      3
L-SC         215795.0      2
M-LC         156294.0      1
M-MC         117551.0      2
H-LC          76094.0      1
L-MC          55573.0      1
L-LC           6744.0      1

In [31]:
# money to be made criteria and conviction-wise
df_portfolio_features.groupby(['Conviction', 'Criteria'])['FTT Amt'].agg(['sum', 'count']).sort_values(by='sum', ascending=False)

                           sum  count
Conviction Criteria
H-SC       XY24      1360333.0      6
           AR         983766.0      5
M-SC       XY24       926386.0      6
H-SC       XR         902300.0      7
X-SC       XY24       863830.0      4
X-LC       X40        841017.0      6
X-MC       X40        674637.0      7
           X40N       534405.0      4
X-SC       X40N       522948.0      4
H-SC       OX40N      395709.0      4
M-SC       OX40N      391057.0      5
X-LC       XY24       382466.0      2
H-SC       SR         319016.0      2
X-MC       XY24       264791.0      2
X-LC       X40N       263165.0      2
X-MC       XY25       246025.0      2
H-MC       XY24       242074.0      1
X-SC       X40        208931.0      2
M-SC       XR         196220.0      2
H-MC       AR         170617.0      2
M-LC       XR         156294.0      1
X-LC       XY25       146470.0      2
L-SC       OX40N      109429.0      1
           XR         106366.0      1
M-SC       AR          78113.0      1
H-LC       AR          76094.0      1
M-MC       XY25        62461.0      1
L-MC       XR          55573.0      1
M-MC       AR          55090.0      1
L-LC       XY25         6744.0      1

In [32]:
# notebook execution time

end_time = time.time()
execution_time = round(end_time - start_time, 0)
print(f"Notebook execution time: {execution_time} seconds")

Notebook execution time: 35.0 seconds