<a href="https://colab.research.google.com/github/ankit-rathi/Quantvesting_v2/blob/main/myStocks_Portfolio_Analysis.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
'''
!pip install pandas==2.2.2 -qq
!pip install pyxirr -qq
!pip install ta -qq
!pip install yfinance==0.2.59 -qq
'''

'\n!pip install pandas==2.2.2 -qq\n!pip install pyxirr -qq\n!pip install ta -qq\n!pip install yfinance==0.2.59 -qq\n'

In [2]:
# import libraries

import numpy as np
import pandas as pd
import datetime
import warnings
warnings.filterwarnings('ignore')
import yfinance as yfin
import ta
import matplotlib.pyplot as plt
import requests

In [3]:
# notebook start time
import time
import datetime
import pytz

start_time = time.time()

# function to print date timestamp
def print_date_time():
  tz_NY = pytz.timezone('Asia/Kolkata')
  datetime_NY = datetime.datetime.now(tz_NY)
  print("Run date time (IST):", datetime_NY.strftime("%Y-%m-%d %H:%M:%S"))

In [4]:
# function to get booked and reserved amount
def get_amt():
  # fetch the JSON data from the URL
  url = "https://raw.githubusercontent.com/ankit-rathi/Tradevesting_v1/main/data/myPortfolioAmts.json"
  response = requests.get(url)
  pf_amts = response.json()  # parse the JSON data

  # extract values from the JSON
  py_booked_amt_dm = pf_amts["py_booked_amt_dm"]
  py_booked_amt_sv = pf_amts["py_booked_amt_sv"]
  cy_booked_amt_dm = pf_amts["cy_booked_amt_dm"]
  cy_booked_amt_sv = pf_amts["cy_booked_amt_sv"]
  reserve_amt_dm = pf_amts["reserve_amt_dm"]
  reserve_amt_sv = pf_amts["reserve_amt_sv"]

  # perform calculations
  py_booked_amt = py_booked_amt_dm + py_booked_amt_sv
  cy_booked_amt = cy_booked_amt_dm + cy_booked_amt_sv
  reserve_amt = reserve_amt_dm + reserve_amt_sv
  total_booked_amt = py_booked_amt + cy_booked_amt

  return total_booked_amt, reserve_amt, cy_booked_amt, py_booked_amt

gen_output = 0

In [5]:
# function to format the amount
def format_amt(number):
    abs_number = abs(number)

    if abs_number >= 1_00_00_000:  # Crores
        formatted_amt = f"{number / 1_00_00_000:.2f} C"
    elif abs_number >= 1_00_000:  # Lakhs
        formatted_amt = f"{number / 1_00_000:.2f} L"
    elif abs_number >= 1_000:  # Thousands
        formatted_amt = f"{number / 1_000:.2f} K"
    else:
        formatted_amt = f"{number:.2f}"

    return formatted_amt

# function to set start and end date
def get_start_end_date():
  start_date = (datetime.date.today() + datetime.timedelta(days=-365)).strftime('%Y-%m-%d')
  end_date = (datetime.date.today() + datetime.timedelta(days=1)).strftime('%Y-%m-%d')
  return start_date, end_date

# function to fetch my portfolio csv
def get_mypfs_df():
  mypfs_df = pd.read_csv('https://raw.githubusercontent.com/ankit-rathi/Tradevesting_v1/main/data/myPortfolioStocks.csv')
  return mypfs_df

# function to fetch my prospects csv
def get_mypps_df():
  mypps_df = pd.read_csv('https://raw.githubusercontent.com/ankit-rathi/Tradevesting_v1/main/data/myProspectsScrips.csv')
  return mypps_df

# function to fetch screener data
def get_myscreen_df():
  myscreen_df = pd.read_csv('https://raw.githubusercontent.com/ankit-rathi/Tradevesting_v1/main/data/myScreenerDB.csv')
  return myscreen_df

# function to fetch momentum data
def get_myinvmt_df():
  myinvmt_df = pd.read_csv('https://raw.githubusercontent.com/ankit-rathi/Tradevesting_v1/main/data/myInvestments.csv')
  return myinvmt_df

# function to get the stock ids
def get_stock_ids(df_pf):
  stock_n100 = df_pf['Symbol'].unique()

  exclude = ['CADILAHC','MMTC', 'MASFIN']

  stock_ids = df_pf[~df_pf['Symbol'].isin(exclude) ]['Symbol'].unique()

  #mypf = mypf[mypf.Forecast.notnull()]
  #stock_ids = mypf['Symbol'].unique()

  #stock_ids.sort()
  return stock_ids

# get features from screener data
def get_screener_features():
  myscreen_df = get_myscreen_df()
  cols = ['Symbol', 'EPS', 'MedPE', 'ROCE%', 'ROE%', 'CapType']
  return myscreen_df[cols]

# get relative strength
def get_relative_strength(stock_list):

    # Dictionary to store stock tickers and their corresponding percentage price change
    stock_changes = {}

    # Loop through each stock and fetch its price data
    for stock in stock_list:
        try:
            # Download the stock data for the given date range
            stock_data = yfin.Ticker(stock + '.NS').history(period='1mo', interval='1d')[map(str.title, ['open', 'close', 'low', 'high', 'volume'])]

            # Calculate the percentage change for the stock
            if len(stock_data) > 0:
                start_price = stock_data['Close'].iloc[0]
                end_price = stock_data['Close'].iloc[-1]
                percent_change = round(((end_price - start_price) / start_price) * 100, 2)
                stock_changes[stock] = percent_change
            else:
                stock_changes[stock] = np.nan  # If no data is available, set to NaN

        except Exception as e:
            print(f"Error fetching data for {stock}: {e}")
            stock_changes[stock] = np.nan

    # Create a DataFrame with stock tickers and their percentage changes
    df = pd.DataFrame(list(stock_changes.items()), columns=['Symbol', 'Percent_Change'])

    # Drop any stocks with missing data (NaN values)
    df = df.dropna()

    # Calculate the percentile rank based on percentage change
    df['RSP'] = round(df['Percent_Change'].rank(pct=True) * 100, 2)
    cols = ['Symbol', 'RSP']
    df = df[cols]
    # Sort by percentile rank (optional)
    df = df.sort_values(by='RSP', ascending=False).reset_index(drop=True)

    return df

In [6]:
# function to get stock technicals
def stock_prec_dev(stock_symbol):
    #stock_symbol = 'ULTRACEMCO.NS'
    short_window = 20
    mid_window = 50
    long_window = 200
    moving_avg = 'SMA'

    start = datetime.datetime(*map(int, start_date.split('-')))
    end = datetime.datetime(*map(int, end_date.split('-')))

    stock_df = yfin.Ticker(stock_symbol + '.NS').history(period='max', interval='1d')[map(str.title, ['open', 'close', 'low', 'high', 'volume'])]

    stock_df['Max'] = round(max(stock_df['Close']),2)
    stock_df = stock_df[(stock_df.index <= end_date) & (stock_df.index >= start_date)]
    stock_df['200_SMA'] = round(stock_df['Close'].rolling(window = 200, min_periods = 1).mean(),0)
    stock_df['Dev%_200'] = round((stock_df['Close'] - stock_df['200_SMA'])*100/stock_df['200_SMA'],2)
    stock_df.dropna(axis = 0, inplace = True) # remove any null rows

    stock_df['20_SMA'] = stock_df['Close'].rolling(window=20).mean()
    stock_df['50_SMA'] = stock_df['Close'].rolling(window=50).mean()
    stock_df['Symbol'] = stock_symbol

    stock_df['Close'] = round(stock_df['Close'],2)
    stock_df['Min'] = round(min(stock_df['Close']),2)
    stock_df['RSI_14'] = ta.momentum.RSIIndicator(close=stock_df['Close'], window=14).rsi()
    stock_df['RSI_14'] = round(stock_df['RSI_14'],0)
    stock_df['Prev_Close'] = stock_df['Close'].shift(1)
    stock_df.drop(['Open', 'Low', 'High', 'Volume'], axis=1, inplace=True)
    stock_df = stock_df.tail(1)

    max_SMA = max(stock_df['20_SMA'].item(), stock_df['50_SMA'].item(), stock_df['200_SMA'].item())
    min_SMA = min(stock_df['20_SMA'].item(), stock_df['50_SMA'].item(), stock_df['200_SMA'].item())
    ABS_Spread = max_SMA - min_SMA
    stock_df['Spread%'] = round((ABS_Spread / stock_df['200_SMA'].item()) * 100,2)

    return stock_df

# function to compute stock attributes
def get_common_features(stock_ids, df_mypf):

  df_prec_dev = pd.DataFrame()
  df_tmp = get_screener_features()
  df_rs = get_relative_strength(stock_ids)

  for stock_id in stock_ids:
      tmp = stock_prec_dev(stock_id)
      tmp = tmp.reset_index()
      df_prec_dev = pd.concat([df_prec_dev, tmp], ignore_index = True)
  df_prec_dev = pd.merge(df_prec_dev, df_mypf, on= 'Symbol')
  df_prec_dev = pd.merge(df_prec_dev, df_tmp, on= 'Symbol', how='left')
  df_prec_dev = pd.merge(df_prec_dev, df_rs, on= 'Symbol', how='left')
  #print(df_prec_dev.columns)
  df_prec_dev['Curr_PE'] = round(df_prec_dev['Close']/df_prec_dev['EPS'],1)
  df_prec_dev['Dev%_PE'] = round((df_prec_dev['Curr_PE'] - df_prec_dev['MedPE'])*100/df_prec_dev['MedPE'],2)
  df_prec_dev['Conviction'] = df_prec_dev['Conviction'] + '-' + df_prec_dev['CapType']
  return df_prec_dev

# function to arrange stock features
def arrange_features(df_stocks, common_cols, diff_cols):
  df_stocks_common = df_stocks[common_cols].drop_duplicates()
  df_stocks_diff = df_stocks[diff_cols]
  df_stocks_diff['Investment'] = df_stocks_diff['AvgCost'] * df_stocks_diff['Shares']
  df_stocks_diff = df_stocks_diff.groupby(['Symbol'])[['Shares', 'Investment']].aggregate(['sum']).reset_index()
  df_stocks_diff.columns = ['Symbol', 'Shares', 'Investment']
  df_stocks_diff['AvgCost'] = round(df_stocks_diff['Investment']/df_stocks_diff['Shares'],2)
  df_stocks = pd.merge(df_stocks_diff, df_stocks_common, on='Symbol')
  return df_stocks

# plot fact distribution across dimension
def plot_pie_chart(df, dimension, fact):
  # grouping the data by category and calculating the sum of fact for each type
  grouped_data = df.groupby(dimension)[fact].sum()

  # sorting the grouped data in descending order
  grouped_data = grouped_data.sort_values(ascending=False)

  # creating a pie chart
  grouped_data.plot.pie(autopct='%1.1f%%', startangle=90, figsize=(6, 6))

  # adding a title and displaying the plot
  plt.title(f'{dimension} {fact} Distribution')
  plt.ylabel('')  # To hide the y-label
  plt.show()

In [7]:
# function to get portfolio features

def get_portfolio_features(df_common_features):

  print_date_time()
  print('-------------------')

  #df_common_features["Target"] = df_common_features["Target"].fillna(df_common_features["Max"])
  df_common_features['NTT'] = np.where(df_common_features['Strategy']== 'NTT', df_common_features["Target"], df_common_features['Max'])
  df_common_features['LTT'] = np.where(df_common_features['Strategy']== 'BTT', df_common_features["Target"], df_common_features['Max'])
  df_common_features['BOL'] = df_common_features['Min']

  tmp_df = df_common_features[df_common_features['Symbol'].isin(mypf_df[mypf_df['InPortfolio'] != 'NA'].Symbol.values)]
  print('qualified stocks: '+str(len(tmp_df['Symbol'].unique())))
  tmp_df1 = tmp_df[tmp_df['LatestQtr'] == 1]
  print('with latest results: '+str(len(tmp_df1['Symbol'].unique())))
  tmp_df1 = tmp_df1[tmp_df1['StarStock'] == 1]
  print('still star stocks: '+str(len(tmp_df1['Symbol'].unique())))
  tmp_df['Investment'] = tmp_df['AvgCost'] * tmp_df['Shares']
  tmp_df['Current'] = round(tmp_df['Close'] * tmp_df['Shares'],0)
  tmp_df['Previous'] = tmp_df['Prev_Close'] * tmp_df['Shares']
  tmp_df['EstimatedST'] = tmp_df['NTT'] * tmp_df['Shares']
  tmp_df['EstimatedLT'] = tmp_df['LTT'] * tmp_df['Shares']
  tmp_df['Current P/L'] = round((tmp_df['Current'] - tmp_df['Investment']),0)
  tmp_df['Today P/L%'] = round((tmp_df['Current'] - tmp_df['Previous'])*100/tmp_df['Previous'],2)
  tmp_df['Current P/L%'] = round((tmp_df['Current'] - tmp_df['Investment'])*100/tmp_df['Investment'],2)
  tmp_df['EstimatedST P/L%'] = round((tmp_df['EstimatedST'] - tmp_df['Investment'])*100/tmp_df['Investment'],2)
  tmp_df['EstimatedLT P/L%'] = round((tmp_df['EstimatedLT'] - tmp_df['Investment'])*100/tmp_df['Investment'],2)
  tmp_df['NTT%'] = round((tmp_df['NTT'] - tmp_df['Close'])*100/tmp_df['Close'],2)
  tmp_df['LTT%'] = round((tmp_df['LTT'] - tmp_df['Close'])*100/tmp_df['Close'],2)
  tmp_df['Gained%'] = round((tmp_df['Close'] - tmp_df['BOL'])*100/tmp_df['BOL'],2)
  investment = round(sum(tmp_df['AvgCost']*tmp_df['Shares']),0)
  current = round(sum(tmp_df['Close']*tmp_df['Shares']),0)
  tmp_df['InitAlloc%'] = round(tmp_df['Investment']*100/investment,2)
  tmp_df['CurrAlloc%'] = round(tmp_df['Current']*100/current,2)
  tmp_df['FTT'] = tmp_df['LTT']
  tmp_df.loc[tmp_df['Strategy'] == 'NTT', 'FTT'] = tmp_df['NTT']
  tmp_df['FTT%'] = tmp_df['LTT%']
  tmp_df.loc[tmp_df['Strategy'] == 'NTT', 'FTT%'] = tmp_df['NTT%']
  tmp_df['FTT Amt'] = round(tmp_df['FTT%'] * tmp_df['Current']/100,0)
  tmp_df['OTT%'] = round((tmp_df['FTT'] - tmp_df['AvgCost'])*100/tmp_df['AvgCost'],2)
  tmp_df['RRR Ind'] = round(tmp_df['Current P/L']/tmp_df['FTT Amt'],2)
  tmp_df['Risk Ind'] = round(tmp_df['Current P/L%']*tmp_df['CurrAlloc%'],0)

  return tmp_df

# function to print portfolio features
def print_portfolio_stats(df_portfolio_features, myinvmt_df):
  from pyxirr import xirr

  total_booked_amt, reserve_amt, cy_booked_amt, py_booked_amt = get_amt()

  dates = myinvmt_df['Date'].values
  dates = np.append(dates, datetime.date.today().strftime('%d-%b-%y'))
  investment = myinvmt_df['Investment'].values
  dates= pd.to_datetime(dates)

  current = round(sum(df_portfolio_features['Close']*df_portfolio_features['Shares']),0) + reserve_amt
  investment_xirr = np.append(investment, current)
  cagr = round(xirr(pd.DataFrame({"dates": dates, "amounts": investment_xirr}))*100,2)

  investment = -sum(investment)
  invested = round(sum(df_portfolio_features['AvgCost']*df_portfolio_features['Shares']),0) + reserve_amt
  previous = round(sum(df_portfolio_features['Prev_Close']*df_portfolio_features['Shares']),0) + reserve_amt
  cy_invested = investment + py_booked_amt

  today_pnl_amount = current-previous
  today_pnl_percentage = round((current-previous)*100/previous,2)

  curr_pnl_amount = current-invested
  curr_pnl_percentage = round((curr_pnl_amount)*100/(cy_invested),2)

  cy_pnl_amount = cy_booked_amt + curr_pnl_amount
  cy_pnl_percentage = round((cy_pnl_amount)*100/cy_invested,2)

  overall_pnl_amount = total_booked_amt + curr_pnl_amount
  overall_pnl_percentage = round((overall_pnl_amount)*100/investment,2)

  estimate_st = round(sum(df_portfolio_features['FTT']*df_portfolio_features['Shares']),0)  + reserve_amt
  est_st_pnl_amount = estimate_st-current
  est_st_pnl_percentage = round((est_st_pnl_amount)*100/current,2)

  estimate_lt = round(sum(df_portfolio_features['LTT']*df_portfolio_features['Shares']),0)  + reserve_amt
  est_lt_pnl_amount = estimate_lt-current
  est_lt_pnl_percentage = round((est_lt_pnl_amount)*100/current,2)

  total_profit = round(sum(df_portfolio_features[df_portfolio_features['Current P/L%'] > 0]['Current']) - sum(df_portfolio_features[df_portfolio_features['Current P/L%'] > 0]['Investment']),0)
  total_loss = round(sum(df_portfolio_features[df_portfolio_features['Current P/L%'] < 0]['Current']) - sum(df_portfolio_features[df_portfolio_features['Current P/L%'] < 0]['Investment']),0)

  cy_booked_percentage = round((cy_booked_amt)*100/current,2)
  py_booked_percentage = round((py_booked_amt)*100/investment,2)
  total_booked_percentage = round((total_booked_amt)*100/investment,2)

  print('-------------------')
  print('Initial Investment: ', format_amt(investment))
  print('CY Investment: ', format_amt(cy_invested))
  print('Reserve: ', format_amt(reserve_amt))
  print('Current: ',  format_amt(current))
  print('-------------------')
  print('Today PnL: '+ '{} ({}%)'.format(format_amt(today_pnl_amount), today_pnl_percentage))
  print('Current PnL: '+ '{} ({}%)'.format(format_amt(curr_pnl_amount), curr_pnl_percentage))
  print('CY Booked + Current PnL: '+ '{} ({}%)'.format(format_amt(cy_pnl_amount), cy_pnl_percentage))
  print('-------------------')
  print('Total profit: ', format_amt(total_profit))
  print('Total loss: ', format_amt(total_loss))
  print('-------------------')
  print('Total Booked + Current PnL: '+ '{} ({}%)'.format(format_amt(overall_pnl_amount), overall_pnl_percentage))
  print('Total Booked PnL: '+ '{} ({}%)'.format(format_amt(total_booked_amt), total_booked_percentage))
  print('Curr Year Booked PnL: '+ '{} ({}%)'.format(format_amt(cy_booked_amt), cy_booked_percentage))
  print('Prev Year Booked PnL: '+ '{} ({}%)'.format(format_amt(py_booked_amt), py_booked_percentage))
  print('===================')
  print('Est FTT: ',  format_amt(estimate_st))
  print('Est FTT PnL: '+ '{} ({}%)'.format(format_amt(est_st_pnl_amount), est_st_pnl_percentage))

  print('===================')
  print('Deployed: ', format_amt(investment))

  print('Current: ', format_amt(current))

  print('CAGR/XIRR %: '+'{}%'.format(cagr))

In [8]:
# get start and end date
start_date, end_date = get_start_end_date()

# get portfolio and prospects data
mypfs_df = get_mypfs_df()
mypps_df = get_mypps_df()
myinvmt_df = get_myinvmt_df()

# merge above datasets
mypf_df = pd.merge(mypfs_df, mypps_df, on="Symbol")

# seggregate dm and sv portfolio
dm_pf = mypf_df[mypf_df['InPortfolio'] == 'DM']
sv_pf = mypf_df[mypf_df['InPortfolio'] == 'SV']

# build portfolio stock dataframe
dm_stocks = get_stock_ids(dm_pf)
sv_stocks = get_stock_ids(sv_pf)
df_stocks = pd.concat([dm_pf,sv_pf], ignore_index = True)

# arrange common and diff stock features
common_cols = ['Symbol', 'Target', 'Criteria', 'Strategy', 'CumlRnk', 'LatestQtr', 'StarStock', 'Conviction', 'Category', 'InFolio', 'XIRR', 'MBQ']
diff_cols = ['Symbol', 'AvgCost', 'Shares']
df_stocks = arrange_features(df_stocks, common_cols, diff_cols)

# get common features
stock_ids = df_stocks['Symbol'].values
df_common_features = get_common_features(stock_ids, df_stocks)

df_common_features.reset_index(drop=True, inplace=True)
df_common_features.drop(['Date'], axis=1, inplace=True)
# get and print portfolio features
df_portfolio_features = get_portfolio_features(df_common_features)

print_portfolio_stats(df_portfolio_features, myinvmt_df)

df = df_portfolio_features
#plot_pie_chart(df, 'CapType', 'Current')
list_ox40n = list(df[df['MBQ'].str.contains('OX40N', na=False)]['Symbol'].values)

Run date time (IST): 2026-06-03 17:26:09
-------------------
qualified stocks: 92
with latest results: 31
still star stocks: 20

-------------------
Initial Investment:  1.40 C
CY Investment:  1.82 C
Reserve:  1.49 K
Current:  1.48 C
-------------------
Today PnL: -1.06 L (-0.71%)
Current PnL: -35.17 L (-19.29%)
CY Booked + Current PnL: -33.09 L (-18.15%)
-------------------
Total profit:  2.18 L
Total loss:  -37.36 L
-------------------
Total Booked + Current PnL: 9.78 L (7.01%)
Total Booked PnL: 44.95 L (32.22%)
Curr Year Booked PnL: 2.08 L (1.41%)
Prev Year Booked PnL: 42.87 L (30.73%)
===================
Est FTT:  2.55 C
Est FTT PnL: 1.07 C (72.43%)
===================
Deployed:  1.40 C
Current:  1.48 C
CAGR/XIRR %: 2.81%

In [9]:
# top 5 near their targets
cols = ['Symbol', 'Today P/L%', 'Current P/L%', 'FTT%', 'OTT%', 'FTT Amt', 'Current P/L', 'Current', 'FTT', 'Dev%_PE', 'RSI_14','Conviction', 'Spread%',  'CumlRnk', 'RRR Ind', 'CurrAlloc%', 'Gained%', 'Criteria', 'Strategy', 'Category']
df_tmp = df_portfolio_features[~df_portfolio_features['Symbol'].isin(['ENRIN','BLUSPRING','DIGITIDE'])]
df_tmp = df_tmp.sort_values(by = 'FTT Amt', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
59,PIDILITIND,1.00,4.12,13.68,18.37,20099.0,5810.0,146920.0,1670.26,-27.09,57.0,X-LC,4.52,5.0,0.29,0.99,15.36,X40,ATH,CHEMICALS
51,KOTAKBANK,0.51,1.80,18.96,21.11,26728.0,2498.0,140970.0,453.24,-12.87,49.0,X-LC,7.23,12.0,0.09,0.95,7.81,X40,ATH,BANKS
55,MASFIN,-0.84,-6.06,29.41,21.57,27069.0,-5940.0,92040.0,397.04,-19.15,42.0,H-SC,2.09,167.0,-0.22,0.62,9.71,XR,ATH,FINANCE
72,SIS,1.67,-3.68,25.89,21.26,27689.0,-4085.0,106947.0,528.00,2550.26,71.0,H-SC,18.49,168.0,-0.15,0.72,59.01,OX40N,NTT,MISC
83,TTKPRESTIG,0.94,-29.25,41.48,0.09,29574.0,-29480.0,71297.0,770.00,65.42,59.0,M-SC,14.75,250.0,-1.00,0.48,26.95,OX40N,NTT,DURABLES

In [10]:
# top 5 today
df_tmp = df_portfolio_features.sort_values(by = 'Today P/L%', ascending=False)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
86,VALIANTORG,5.01,-37.54,178.82,74.15,182731.0,-61418.0,102187.0,838.00,-284.03,57.0,H-SC,7.26,145.0,-0.34,0.69,52.07,XR,NTT,CHEMICALS
3,ALKYLAMINE,3.27,-21.77,147.52,93.63,116514.0,-21981.0,78982.0,4546.37,-16.24,64.0,H-SC,10.12,142.0,-0.19,0.53,49.14,SR,ATH,CHEMICALS
64,RELAXO,2.85,-56.28,248.34,52.31,157619.0,-81691.0,63469.0,1176.00,-53.44,67.0,X-SC,23.14,92.0,-0.52,0.43,41.91,X40N,NTT,FOOTWEAR
23,DMART,2.75,0.20,29.34,29.60,73381.0,504.0,250104.0,5391.45,-15.50,45.0,X-LC,3.49,14.0,0.01,1.69,14.32,X40N,ATH,FMCG
61,RAJESHEXPO,2.42,-78.87,373.58,0.07,108286.0,-108191.0,28986.0,518.00,961.87,44.0,L-SC,30.71,268.0,-1.00,0.20,36.08,OX40N,NTT,JEWELLERY

In [11]:
# bottom 5 today
df_tmp = df_portfolio_features.sort_values(by = 'Today P/L%', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
79,TCS,-8.39,-34.19,89.76,24.88,273652.0,-158402.0,304871.0,4253.91,-44.28,42.0,X-LC,18.04,2.0,-0.58,2.06,1.16,X40,ATH,IT
33,HCLTECH,-5.19,-23.49,58.81,21.51,108859.0,-56821.0,185103.0,1872.35,-19.77,45.0,X-LC,18.55,8.0,-0.52,1.25,4.89,X40,ATH,IT
13,BSOFT,-4.97,-40.60,153.84,50.79,128535.0,-57102.0,83551.0,831.70,-23.85,45.0,H-SC,13.79,172.0,-0.44,0.56,5.83,XR,ATH,IT
78,TATAELXSI,-4.05,-37.35,110.74,32.03,91463.0,-49242.0,82593.0,9161.00,-21.71,54.0,H-SC,15.15,158.0,-0.54,0.56,9.31,OX40N,NTT,IT
45,INFY,-3.79,-16.77,61.30,34.24,159634.0,-52474.0,260414.0,1972.00,-34.33,55.0,X-LC,18.02,3.0,-0.33,1.76,11.65,X40,NTT,IT

In [12]:
# top 5 to exit based on CumlRnk
df_tmp = df_portfolio_features[~df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])]
df_tmp = df_tmp[(df_tmp['Current P/L%'] > -1) & (df_tmp['Current P/L%'] < 1)].sort_values(by = 'CumlRnk', ascending=False)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
9,BANDHANBNK,0.63,-0.13,92.66,92.42,257790.0,-348.0,278211.0,400.0,138.51,66.0,H-SC,21.13,174.0,-0.0,1.88,53.26,XY24,NTT,BANKS

In [13]:
# OX40N stocks to exit
df_tmp = df_portfolio_features[(df_portfolio_features['Symbol'].isin(list_ox40n))].sort_values(by = 'Current P/L%', ascending=False)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
25,FINCABLES,-0.55,26.23,64.72,107.91,120615.0,38720.0,186364.0,1641.55,13.65,45.0,M-SC,27.32,220.0,0.32,1.26,40.21,OX40N,ATH,CABLES
72,SIS,1.67,-3.68,25.89,21.26,27689.0,-4085.0,106947.0,528.00,2550.26,71.0,H-SC,18.49,168.0,-0.15,0.72,59.01,OX40N,NTT,MISC
16,CERA,-0.50,-27.08,69.89,23.89,89649.0,-47632.0,128271.0,9475.00,-29.59,50.0,H-SC,6.90,153.0,-0.53,0.87,23.27,OX40N,NTT,CERAMICS
50,KANSAINER,-0.07,-28.29,58.24,13.47,112621.0,-76293.0,193374.0,340.00,-38.33,56.0,H-SC,10.90,162.0,-0.68,1.31,35.07,XY24,NTT,PAINTS
83,TTKPRESTIG,0.94,-29.25,41.48,0.09,29574.0,-29480.0,71297.0,770.00,65.42,59.0,M-SC,14.75,250.0,-1.00,0.48,26.95,OX40N,NTT,DURABLES

In [14]:
# top 5 to book for rotation
df_tmp = df_portfolio_features[(df_portfolio_features['Current P/L%'] > 20) ].sort_values(by = 'CumlRnk', ascending=False)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
25,FINCABLES,-0.55,26.23,64.72,107.91,120615.0,38720.0,186364.0,1641.55,13.65,45.0,M-SC,27.32,220.0,0.32,1.26,40.21,OX40N,ATH,CABLES
68,SATIN,1.79,30.36,16.47,51.83,59320.0,83884.0,360168.0,274.00,16.95,73.0,H-SC,39.57,159.0,1.41,2.43,75.45,XY24,NTT,FINANCE

In [15]:
# top 5 to monitor for exit
df_tmp = df_portfolio_features[~df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])]
df_tmp = df_tmp[(df_tmp['Current P/L%'] > 0) ].sort_values(by = 'Dev%_PE', ascending=False)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
74,STARHEALTH,-0.68,2.57,43.57,47.26,125633.0,7224.0,288347.0,761.00,61.80,62.0,H-SC,9.84,173.0,0.06,1.95,26.59,XY24,NTT,INSURANCE
68,SATIN,1.79,30.36,16.47,51.83,59320.0,83884.0,360168.0,274.00,16.95,73.0,H-SC,39.57,159.0,1.41,2.43,75.45,XY24,NTT,FINANCE
25,FINCABLES,-0.55,26.23,64.72,107.91,120615.0,38720.0,186364.0,1641.55,13.65,45.0,M-SC,27.32,220.0,0.32,1.26,40.21,OX40N,ATH,CABLES
91,ZYDUSLIFE,-0.16,13.53,19.47,35.63,46325.0,28355.0,237929.0,1286.17,-1.35,69.0,H-MC,7.93,120.0,0.61,1.61,25.10,AR,ATH,PHARMA
73,SONACOMS,-1.29,4.39,33.24,39.09,35103.0,4445.0,105604.0,804.02,-17.23,56.0,M-MC,18.88,193.0,0.13,0.71,49.39,AR,ATH,AUTO

In [16]:
# top 5 to book for rotation from weak conviction
df_tmp = df_portfolio_features[~df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])]
df_tmp = df_tmp[~df_tmp['Criteria'].isin(['XY25','XY24','X40', 'X40N'])].sort_values(by = 'RRR Ind', ascending=False)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
91,ZYDUSLIFE,-0.16,13.53,19.47,35.63,46325.0,28355.0,237929.0,1286.17,-1.35,69.0,H-MC,7.93,120.0,0.61,1.61,25.10,AR,ATH,PHARMA
25,FINCABLES,-0.55,26.23,64.72,107.91,120615.0,38720.0,186364.0,1641.55,13.65,45.0,M-SC,27.32,220.0,0.32,1.26,40.21,OX40N,ATH,CABLES
73,SONACOMS,-1.29,4.39,33.24,39.09,35103.0,4445.0,105604.0,804.02,-17.23,56.0,M-MC,18.88,193.0,0.13,0.71,49.39,AR,ATH,AUTO
42,INDIAMART,0.44,-14.92,142.96,106.72,150022.0,-18396.0,104940.0,4810.62,-61.72,39.0,H-SC,11.13,140.0,-0.12,0.71,1.59,AR,ATH,MISC
75,SURYODAY,0.44,-3.36,27.31,23.03,47264.0,-6008.0,173063.0,216.00,88.60,64.0,H-SC,19.84,166.0,-0.13,1.17,45.71,XR,NTT,BANKS

In [17]:
# top 5 to accumulate based on lowest RSI_14
df_tmp = df_portfolio_features[df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])].sort_values(by = 'RSI_14', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
40,ICICIPRULI,-1.15,-21.08,65.65,30.73,102065.0,-41536.0,155469.0,790.00,-42.23,28.0,X-MC,12.95,78.0,-0.41,1.05,0.00,X40,ATH,INSURANCE
27,GLAXO,-0.36,-12.45,54.98,35.69,95929.0,-24804.0,174480.0,3380.16,-33.11,30.0,X-MC,7.17,56.0,-0.26,1.18,0.00,X40,ATH,PHARMA
47,ITC,-2.21,-27.04,63.18,19.06,156808.0,-91974.0,248192.0,452.00,-59.97,30.0,X-LC,14.49,1.0,-0.59,1.68,0.00,X40,NTT,FMCG
20,DABUR,-1.80,-18.31,75.90,43.70,153817.0,-45411.0,202657.0,735.00,-25.93,30.0,X-MC,9.80,70.0,-0.30,1.37,1.80,XY24,BTT,FMCG
36,HINDUNILVR,-0.15,-18.67,39.77,13.67,83143.0,-48003.0,209060.0,2922.00,-39.55,32.0,X-LC,6.91,9.0,-0.58,1.41,1.87,XY25,NTT,FMCG

In [18]:
# top 5 to accumulate based on Spread and CumlRnk
df_tmp = df_portfolio_features[df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])]
df_tmp = df_tmp[(df_tmp['CumlRnk'] < 100)].sort_values(by = 'Spread%', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
23,DMART,2.75,0.20,29.34,29.60,73381.0,504.0,250104.0,5391.45,-15.50,45.0,X-LC,3.49,14.0,0.01,1.69,14.32,X40N,ATH,FMCG
57,PAGEIND,0.54,-2.02,36.34,33.59,95558.0,-5424.0,262955.0,51217.29,-29.78,53.0,X-MC,3.60,55.0,-0.06,1.78,24.88,X40,ATH,APPARELS
49,JSWINFRA,-1.96,-7.98,26.53,16.43,54141.0,-17698.0,204076.0,342.00,-21.21,47.0,X-MC,4.41,61.0,-0.33,1.38,15.36,X40N,NTT,REALTY
59,PIDILITIND,1.00,4.12,13.68,18.37,20099.0,5810.0,146920.0,1670.26,-27.09,57.0,X-LC,4.52,5.0,0.29,0.99,15.36,X40,ATH,CHEMICALS
19,COLPAL,0.99,-23.35,82.47,39.86,166474.0,-61505.0,201860.0,3683.41,-7.20,41.0,X-MC,4.64,62.0,-0.37,1.36,14.18,XY25,ATH,FMCG

In [19]:
# top 5 to accumulate based on lowest Gained%
df_tmp = df_portfolio_features[df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])].sort_values(by = 'Gained%', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
27,GLAXO,-0.36,-12.45,54.98,35.69,95929.0,-24804.0,174480.0,3380.16,-33.11,30.0,X-MC,7.17,56.0,-0.26,1.18,0.00,X40,ATH,PHARMA
47,ITC,-2.21,-27.04,63.18,19.06,156808.0,-91974.0,248192.0,452.00,-59.97,30.0,X-LC,14.49,1.0,-0.59,1.68,0.00,X40,NTT,FMCG
40,ICICIPRULI,-1.15,-21.08,65.65,30.73,102065.0,-41536.0,155469.0,790.00,-42.23,28.0,X-MC,12.95,78.0,-0.41,1.05,0.00,X40,ATH,INSURANCE
65,RELIANCE,-0.11,-15.70,48.64,25.30,82398.0,-31560.0,169403.0,1952.00,-17.72,37.0,X-LC,5.13,21.0,-0.38,1.14,0.66,XY25,BTT,REFINERIES
28,GODREJCP,-1.26,-11.72,48.91,31.47,64172.0,-17410.0,131204.0,1469.04,-7.17,35.0,X-LC,9.79,32.0,-0.27,0.89,0.67,X40N,ATH,FMCG

In [20]:
# top 5 to accumulate based on lowest CurrAlloc%
df_tmp = df_portfolio_features[df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])].sort_values(by = 'CurrAlloc%', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
10,BATAINDIA,-0.67,-57.05,214.81,35.20,118706.0,-73409.0,55261.0,2096.00,-27.51,35.0,X-SC,25.08,91.0,-0.62,0.37,9.60,X40,NTT,FOOTWEAR
64,RELAXO,2.85,-56.28,248.34,52.31,157619.0,-81691.0,63469.0,1176.00,-53.44,67.0,X-SC,23.14,92.0,-0.52,0.43,41.91,X40N,NTT,FOOTWEAR
60,QUESS,-0.83,-13.41,100.83,73.90,93239.0,-14322.0,92471.0,424.00,-53.17,56.0,X-SC,7.94,80.0,-0.15,0.62,26.06,XY24,NTT,MISC
28,GODREJCP,-1.26,-11.72,48.91,31.47,64172.0,-17410.0,131204.0,1469.04,-7.17,35.0,X-LC,9.79,32.0,-0.27,0.89,0.67,X40N,ATH,FMCG
53,M&M,0.43,-2.29,26.28,23.38,35609.0,-3181.0,135500.0,3802.40,-17.22,41.0,X-LC,8.91,25.0,-0.09,0.92,2.73,X40N,ATH,AUTO

In [21]:
# top 5 to accumulate based on CumlRnk
df_tmp = df_portfolio_features.sort_values(by = 'CumlRnk', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
47,ITC,-2.21,-27.04,63.18,19.06,156808.0,-91974.0,248192.0,452.00,-59.97,30.0,X-LC,14.49,1.0,-0.59,1.68,0.00,X40,NTT,FMCG
79,TCS,-8.39,-34.19,89.76,24.88,273652.0,-158402.0,304871.0,4253.91,-44.28,42.0,X-LC,18.04,2.0,-0.58,2.06,1.16,X40,ATH,IT
45,INFY,-3.79,-16.77,61.30,34.24,159634.0,-52474.0,260414.0,1972.00,-34.33,55.0,X-LC,18.02,3.0,-0.33,1.76,11.65,X40,NTT,IT
81,TMPV,2.04,-9.37,50.70,36.58,163509.0,-33339.0,322502.0,600.00,-81.44,68.0,X-LC,18.99,4.0,-0.20,2.18,34.42,XY24,NTT,AUTO
59,PIDILITIND,1.00,4.12,13.68,18.37,20099.0,5810.0,146920.0,1670.26,-27.09,57.0,X-LC,4.52,5.0,0.29,0.99,15.36,X40,ATH,CHEMICALS

In [22]:
# top 5 for average up
df_tmp = df_portfolio_features[(df_portfolio_features['Dev%_200'] > 5)].sort_values(by = 'CurrAlloc%', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
44,INDUSINDBK,-1.38,-33.56,100.01,32.89,51302.0,-25910.0,51297.0,1800.00,-341.60,49.0,L-MC,8.22,258.0,-0.51,0.35,26.26,XR,NTT,BANKS
18,COFFEEDAY,-2.82,-33.02,101.97,35.27,77549.0,-37498.0,76051.0,80.00,-47.69,83.0,L-SC,22.13,266.0,-0.48,0.51,87.55,XR,NTT,HOTELS
3,ALKYLAMINE,3.27,-21.77,147.52,93.63,116514.0,-21981.0,78982.0,4546.37,-16.24,64.0,H-SC,10.12,142.0,-0.19,0.53,49.14,SR,ATH,CHEMICALS
86,VALIANTORG,5.01,-37.54,178.82,74.15,182731.0,-61418.0,102187.0,838.00,-284.03,57.0,H-SC,7.26,145.0,-0.34,0.69,52.07,XR,NTT,CHEMICALS
73,SONACOMS,-1.29,4.39,33.24,39.09,35103.0,4445.0,105604.0,804.02,-17.23,56.0,M-MC,18.88,193.0,0.13,0.71,49.39,AR,ATH,AUTO

In [23]:
# top 5 RSP
df_tmp = df_portfolio_features.sort_values(by = 'RSP', ascending=False)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
18,COFFEEDAY,-2.82,-33.02,101.97,35.27,77549.0,-37498.0,76051.0,80.00,-47.69,83.0,L-SC,22.13,266.0,-0.48,0.51,87.55,XR,NTT,HOTELS
68,SATIN,1.79,30.36,16.47,51.83,59320.0,83884.0,360168.0,274.00,16.95,73.0,H-SC,39.57,159.0,1.41,2.43,75.45,XY24,NTT,FINANCE
91,ZYDUSLIFE,-0.16,13.53,19.47,35.63,46325.0,28355.0,237929.0,1286.17,-1.35,69.0,H-MC,7.93,120.0,0.61,1.61,25.10,AR,ATH,PHARMA
3,ALKYLAMINE,3.27,-21.77,147.52,93.63,116514.0,-21981.0,78982.0,4546.37,-16.24,64.0,H-SC,10.12,142.0,-0.19,0.53,49.14,SR,ATH,CHEMICALS
81,TMPV,2.04,-9.37,50.70,36.58,163509.0,-33339.0,322502.0,600.00,-81.44,68.0,X-LC,18.99,4.0,-0.20,2.18,34.42,XY24,NTT,AUTO

In [24]:
# Top N allocation
df_tmp = df_portfolio_features.sort_values(by = 'CurrAlloc%', ascending=False)
top_n_values = [10, 25, 50]

sum_df = pd.DataFrame({
    'Top_N': top_n_values,
    'Sum_Alloc%': [df_tmp['CurrAlloc%'].head(n).sum() for n in top_n_values]
})

sum_df

   Top_N  Sum_Alloc%
0     10       19.87
1     25       42.83
2     50       72.55

In [25]:
# market-cap-wise allocation
df_tmp = df_portfolio_features[cols]
df_tmp.groupby(df_tmp['Conviction'].str[-2:])['CurrAlloc%'].sum().sort_values(ascending=False)

Conviction
SC    43.23
LC    31.54
MC    25.23
Name: CurrAlloc%, dtype: float64

In [26]:
# criteria-wise allocation
df_portfolio_features.groupby('Criteria')['CurrAlloc%'].sum().sort_values(ascending=False)

Criteria
XY24     27.79
X40      24.99
X40N     16.93
XR        9.18
OX40N     6.95
AR        6.90
XY25      6.37
SR        0.89
Name: CurrAlloc%, dtype: float64

In [27]:
# conviction-wise allocation
df_portfolio_features.groupby('Conviction')['CurrAlloc%'].sum().sort_values(ascending=False)

Conviction
X-LC    29.33
H-SC    22.89
X-MC    20.22
M-SC     9.89
X-SC     9.74
H-MC     2.74
M-MC     1.92
H-LC     1.25
M-LC     0.96
L-SC     0.71
L-MC     0.35
Name: CurrAlloc%, dtype: float64

In [28]:
# sector-wise stats
df_tmp = df_portfolio_features.groupby('Category')[['CurrAlloc%', 'Current', 'Current P/L', 'FTT Amt']].sum().sort_values(by=['Current', 'Current P/L'], ascending=False)
df_tmp['Current P/L%'] = round(df_tmp['Current P/L'] * 100 / df_tmp['Current'], 2)
df_tmp['FTT%'] = round(df_tmp['FTT Amt'] * 100 / df_tmp['Current'], 2)
cols = ['CurrAlloc%', 'Current P/L%', 'FTT%']
df_tmp[cols].sort_values(by=['CurrAlloc%'], ascending=False)

               CurrAlloc%  Current P/L%    FTT%
Category
FMCG                14.85        -20.45   62.70
FINANCE             10.83        -14.92   64.90
IT                  10.44        -45.73  118.60
AUTO                 6.89         -7.40   47.67
MISC                 6.89        -31.34   88.40
BANKS                5.78         -6.18   55.28
PAINTS               5.55        -20.15   41.01
INSURANCE            5.20         -7.67   44.19
PHARMA               5.01         -0.03   31.25
ELECTRICAL           4.06        -17.41   58.85
CHEMICALS            2.21        -23.65   97.33
HEALTHCARE           2.06        -17.84   48.59
FOOTWEAR             1.78        -67.75  135.01
AC                   1.78        -21.51   54.45
APPARELS             1.78         -2.06   36.34
DURABLES             1.60        -63.16  102.86
TRAVEL               1.58        -91.29  187.06
BREWERIES            1.47         -7.79   30.18
REALTY               1.38         -8.67   26.53
CERAMICS             1.34        -55.09  102.21
ENGINEERING          1.31        -24.47   81.40
CABLES               1.26         20.78   64.72
REFINERIES           1.14        -18.63   48.64
CEMENT               1.10        -65.40  189.14
JEWELLERY            1.08       -100.96  170.78
ENTERTAINMENT        0.72        -83.57  193.05
HOTELS               0.51        -49.31  101.97
TEXTILES             0.40        -54.66   98.76

In [29]:
# money to be made criteria-wise
df_portfolio_features.groupby('Criteria')['FTT Amt'].agg(['sum', 'count']).sort_values(by='sum', ascending=False)

                sum  count
Criteria
XY24      3486055.0     21
X40       1986275.0     19
XR        1322524.0     13
X40N      1219115.0     13
AR        1162474.0      9
OX40N      764436.0     10
XY25       491357.0      5
SR         286982.0      2

In [30]:
# money to be made conviction-wise
df_portfolio_features.groupby('Conviction')['FTT Amt'].agg(['sum', 'count']).sort_values(by='sum', ascending=False)

                  sum  count
Conviction
H-SC        3396295.0     24
X-LC        1947852.0     21
X-MC        1727230.0     15
M-SC        1455839.0     14
X-SC        1361928.0      9
H-MC         293492.0      2
L-SC         185835.0      2
M-LC         150049.0      1
M-MC         101301.0      2
L-MC          51302.0      1
H-LC          48095.0      1

In [31]:
# money to be made criteria and conviction-wise
df_portfolio_features.groupby(['Conviction', 'Criteria'])['FTT Amt'].agg(['sum', 'count']).sort_values(by='sum', ascending=False)

                           sum  count
Conviction Criteria
X-LC       X40       1048124.0     10
H-SC       XY24      1029481.0      6
           AR         955128.0      5
M-SC       XY24       849679.0      6
X-SC       XY24       804582.0      4
H-SC       XR         804440.0      7
X-MC       X40        721653.0      7
           X40N       504773.0      4
X-LC       X40N       373494.0      6
X-SC       X40N       340848.0      3
M-SC       OX40N      335886.0      5
H-SC       OX40N      320264.0      4
X-LC       XY24       313960.0      2
H-SC       SR         286982.0      2
X-MC       XY25       259618.0      2
H-MC       XY24       247167.0      1
X-MC       XY24       241186.0      2
X-SC       X40        216498.0      2
M-SC       XR         192451.0      2
X-LC       XY25       165541.0      2
M-LC       XR         150049.0      1
L-SC       OX40N      108286.0      1
M-SC       AR          77823.0      1
L-SC       XR          77549.0      1
M-MC       XY25        66198.0      1
L-MC       XR          51302.0      1
H-LC       AR          48095.0      1
X-LC       XR          46733.0      1
H-MC       AR          46325.0      1
M-MC       AR          35103.0      1

In [32]:
# notebook execution time

end_time = time.time()
execution_time = round(end_time - start_time, 0)
print(f"Notebook execution time: {execution_time} seconds")

Notebook execution time: 37.0 seconds