<a href="https://colab.research.google.com/github/ankit-rathi/Quantvesting_v2/blob/main/myStocks_Portfolio_Analysis.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
'''
!pip install pandas==2.2.2 -qq
!pip install pyxirr -qq
!pip install ta -qq
!pip install yfinance==0.2.59 -qq
'''

'\n!pip install pandas==2.2.2 -qq\n!pip install pyxirr -qq\n!pip install ta -qq\n!pip install yfinance==0.2.59 -qq\n'

In [2]:
# import libraries

import numpy as np
import pandas as pd
import datetime
import warnings
warnings.filterwarnings('ignore')
import yfinance as yfin
import ta
import matplotlib.pyplot as plt
import requests

In [3]:
# notebook start time
import time
import datetime
import pytz

start_time = time.time()

# function to print date timestamp
def print_date_time():
  tz_NY = pytz.timezone('Asia/Kolkata')
  datetime_NY = datetime.datetime.now(tz_NY)
  print("Run date time (IST):", datetime_NY.strftime("%Y-%m-%d %H:%M:%S"))

In [4]:
# function to get booked and reserved amount
def get_amt():
  # fetch the JSON data from the URL
  url = "https://raw.githubusercontent.com/ankit-rathi/Tradevesting_v1/main/data/myPortfolioAmts.json"
  response = requests.get(url)
  pf_amts = response.json()  # parse the JSON data

  # extract values from the JSON
  py_booked_amt_dm = pf_amts["py_booked_amt_dm"]
  py_booked_amt_sv = pf_amts["py_booked_amt_sv"]
  cy_booked_amt_dm = pf_amts["cy_booked_amt_dm"]
  cy_booked_amt_sv = pf_amts["cy_booked_amt_sv"]
  reserve_amt_dm = pf_amts["reserve_amt_dm"]
  reserve_amt_sv = pf_amts["reserve_amt_sv"]

  # perform calculations
  py_booked_amt = py_booked_amt_dm + py_booked_amt_sv
  cy_booked_amt = cy_booked_amt_dm + cy_booked_amt_sv
  reserve_amt = reserve_amt_dm + reserve_amt_sv
  total_booked_amt = py_booked_amt + cy_booked_amt

  return total_booked_amt, reserve_amt, cy_booked_amt, py_booked_amt

gen_output = 0

In [5]:
# function to format the amount
def format_amt(number):
    abs_number = abs(number)

    if abs_number >= 1_00_00_000:  # Crores
        formatted_amt = f"{number / 1_00_00_000:.2f} C"
    elif abs_number >= 1_00_000:  # Lakhs
        formatted_amt = f"{number / 1_00_000:.2f} L"
    elif abs_number >= 1_000:  # Thousands
        formatted_amt = f"{number / 1_000:.2f} K"
    else:
        formatted_amt = f"{number:.2f}"

    return formatted_amt

# function to set start and end date
def get_start_end_date():
  start_date = (datetime.date.today() + datetime.timedelta(days=-365)).strftime('%Y-%m-%d')
  end_date = (datetime.date.today() + datetime.timedelta(days=1)).strftime('%Y-%m-%d')
  return start_date, end_date

# function to fetch my portfolio csv
def get_mypfs_df():
  mypfs_df = pd.read_csv('https://raw.githubusercontent.com/ankit-rathi/Tradevesting_v1/main/data/myPortfolioStocks.csv')
  return mypfs_df

# function to fetch my prospects csv
def get_mypps_df():
  mypps_df = pd.read_csv('https://raw.githubusercontent.com/ankit-rathi/Tradevesting_v1/main/data/myProspectsScrips.csv')
  return mypps_df

# function to fetch screener data
def get_myscreen_df():
  myscreen_df = pd.read_csv('https://raw.githubusercontent.com/ankit-rathi/Tradevesting_v1/main/data/myScreenerDB.csv')
  return myscreen_df

# function to fetch momentum data
def get_myinvmt_df():
  myinvmt_df = pd.read_csv('https://raw.githubusercontent.com/ankit-rathi/Tradevesting_v1/main/data/myInvestments.csv')
  return myinvmt_df

# function to get the stock ids
def get_stock_ids(df_pf):
  stock_n100 = df_pf['Symbol'].unique()

  exclude = ['CADILAHC','MMTC', 'MASFIN']

  stock_ids = df_pf[~df_pf['Symbol'].isin(exclude) ]['Symbol'].unique()

  #mypf = mypf[mypf.Forecast.notnull()]
  #stock_ids = mypf['Symbol'].unique()

  #stock_ids.sort()
  return stock_ids

# get features from screener data
def get_screener_features():
  myscreen_df = get_myscreen_df()
  cols = ['Symbol', 'EPS', 'MedPE', 'ROCE%', 'ROE%', 'CapType']
  return myscreen_df[cols]

# get relative strength
def get_relative_strength(stock_list):

    # Dictionary to store stock tickers and their corresponding percentage price change
    stock_changes = {}

    # Loop through each stock and fetch its price data
    for stock in stock_list:
        try:
            # Download the stock data for the given date range
            stock_data = yfin.Ticker(stock + '.NS').history(period='1mo', interval='1d')[map(str.title, ['open', 'close', 'low', 'high', 'volume'])]

            # Calculate the percentage change for the stock
            if len(stock_data) > 0:
                start_price = stock_data['Close'].iloc[0]
                end_price = stock_data['Close'].iloc[-1]
                percent_change = round(((end_price - start_price) / start_price) * 100, 2)
                stock_changes[stock] = percent_change
            else:
                stock_changes[stock] = np.nan  # If no data is available, set to NaN

        except Exception as e:
            print(f"Error fetching data for {stock}: {e}")
            stock_changes[stock] = np.nan

    # Create a DataFrame with stock tickers and their percentage changes
    df = pd.DataFrame(list(stock_changes.items()), columns=['Symbol', 'Percent_Change'])

    # Drop any stocks with missing data (NaN values)
    df = df.dropna()

    # Calculate the percentile rank based on percentage change
    df['RSP'] = round(df['Percent_Change'].rank(pct=True) * 100, 2)
    cols = ['Symbol', 'RSP']
    df = df[cols]
    # Sort by percentile rank (optional)
    df = df.sort_values(by='RSP', ascending=False).reset_index(drop=True)

    return df

In [6]:
# function to get stock technicals
def stock_prec_dev(stock_symbol):
    #stock_symbol = 'ULTRACEMCO.NS'
    short_window = 20
    mid_window = 50
    long_window = 200
    moving_avg = 'SMA'

    start = datetime.datetime(*map(int, start_date.split('-')))
    end = datetime.datetime(*map(int, end_date.split('-')))

    stock_df = yfin.Ticker(stock_symbol + '.NS').history(period='max', interval='1d')[map(str.title, ['open', 'close', 'low', 'high', 'volume'])]

    stock_df['Max'] = round(max(stock_df['Close']),2)
    stock_df = stock_df[(stock_df.index <= end_date) & (stock_df.index >= start_date)]
    stock_df['200_SMA'] = round(stock_df['Close'].rolling(window = 200, min_periods = 1).mean(),0)
    stock_df['Dev%_200'] = round((stock_df['Close'] - stock_df['200_SMA'])*100/stock_df['200_SMA'],2)
    stock_df.dropna(axis = 0, inplace = True) # remove any null rows

    stock_df['20_SMA'] = stock_df['Close'].rolling(window=20).mean()
    stock_df['50_SMA'] = stock_df['Close'].rolling(window=50).mean()
    stock_df['Symbol'] = stock_symbol

    stock_df['Close'] = round(stock_df['Close'],2)
    stock_df['Min'] = round(min(stock_df['Close']),2)
    stock_df['RSI_14'] = ta.momentum.RSIIndicator(close=stock_df['Close'], window=14).rsi()
    stock_df['RSI_14'] = round(stock_df['RSI_14'],0)
    stock_df['Prev_Close'] = stock_df['Close'].shift(1)
    stock_df.drop(['Open', 'Low', 'High', 'Volume'], axis=1, inplace=True)
    stock_df = stock_df.tail(1)

    max_SMA = max(stock_df['20_SMA'].item(), stock_df['50_SMA'].item(), stock_df['200_SMA'].item())
    min_SMA = min(stock_df['20_SMA'].item(), stock_df['50_SMA'].item(), stock_df['200_SMA'].item())
    ABS_Spread = max_SMA - min_SMA
    stock_df['Spread%'] = round((ABS_Spread / stock_df['200_SMA'].item()) * 100,2)

    return stock_df

# function to compute stock attributes
def get_common_features(stock_ids, df_mypf):

  df_prec_dev = pd.DataFrame()
  df_tmp = get_screener_features()
  df_rs = get_relative_strength(stock_ids)

  for stock_id in stock_ids:
      tmp = stock_prec_dev(stock_id)
      tmp = tmp.reset_index()
      df_prec_dev = pd.concat([df_prec_dev, tmp], ignore_index = True)
  df_prec_dev = pd.merge(df_prec_dev, df_mypf, on= 'Symbol')
  df_prec_dev = pd.merge(df_prec_dev, df_tmp, on= 'Symbol', how='left')
  df_prec_dev = pd.merge(df_prec_dev, df_rs, on= 'Symbol', how='left')
  #print(df_prec_dev.columns)
  df_prec_dev['Curr_PE'] = round(df_prec_dev['Close']/df_prec_dev['EPS'],1)
  df_prec_dev['Dev%_PE'] = round((df_prec_dev['Curr_PE'] - df_prec_dev['MedPE'])*100/df_prec_dev['MedPE'],2)
  df_prec_dev['Conviction'] = df_prec_dev['Conviction'] + '-' + df_prec_dev['CapType']
  return df_prec_dev

# function to arrange stock features
def arrange_features(df_stocks, common_cols, diff_cols):
  df_stocks_common = df_stocks[common_cols].drop_duplicates()
  df_stocks_diff = df_stocks[diff_cols]
  df_stocks_diff['Investment'] = df_stocks_diff['AvgCost'] * df_stocks_diff['Shares']
  df_stocks_diff = df_stocks_diff.groupby(['Symbol'])[['Shares', 'Investment']].aggregate(['sum']).reset_index()
  df_stocks_diff.columns = ['Symbol', 'Shares', 'Investment']
  df_stocks_diff['AvgCost'] = round(df_stocks_diff['Investment']/df_stocks_diff['Shares'],2)
  df_stocks = pd.merge(df_stocks_diff, df_stocks_common, on='Symbol')
  return df_stocks

# plot fact distribution across dimension
def plot_pie_chart(df, dimension, fact):
  # grouping the data by category and calculating the sum of fact for each type
  grouped_data = df.groupby(dimension)[fact].sum()

  # sorting the grouped data in descending order
  grouped_data = grouped_data.sort_values(ascending=False)

  # creating a pie chart
  grouped_data.plot.pie(autopct='%1.1f%%', startangle=90, figsize=(6, 6))

  # adding a title and displaying the plot
  plt.title(f'{dimension} {fact} Distribution')
  plt.ylabel('')  # To hide the y-label
  plt.show()

In [7]:
# function to get portfolio features

def get_portfolio_features(df_common_features):

  print_date_time()
  print('-------------------')

  #df_common_features["Target"] = df_common_features["Target"].fillna(df_common_features["Max"])
  df_common_features['NTT'] = np.where(df_common_features['Strategy']== 'NTT', df_common_features["Target"], df_common_features['Max'])
  df_common_features['LTT'] = np.where(df_common_features['Strategy']== 'BTT', df_common_features["Target"], df_common_features['Max'])
  df_common_features['BOL'] = df_common_features['Min']

  tmp_df = df_common_features[df_common_features['Symbol'].isin(mypf_df[mypf_df['InPortfolio'] != 'NA'].Symbol.values)]
  print('qualified stocks: '+str(len(tmp_df['Symbol'].unique())))
  tmp_df1 = tmp_df[tmp_df['LatestQtr'] == 1]
  print('with latest results: '+str(len(tmp_df1['Symbol'].unique())))
  tmp_df1 = tmp_df1[tmp_df1['StarStock'] == 1]
  print('still star stocks: '+str(len(tmp_df1['Symbol'].unique())))
  tmp_df['Investment'] = tmp_df['AvgCost'] * tmp_df['Shares']
  tmp_df['Current'] = round(tmp_df['Close'] * tmp_df['Shares'],0)
  tmp_df['Previous'] = tmp_df['Prev_Close'] * tmp_df['Shares']
  tmp_df['EstimatedST'] = tmp_df['NTT'] * tmp_df['Shares']
  tmp_df['EstimatedLT'] = tmp_df['LTT'] * tmp_df['Shares']
  tmp_df['Current P/L'] = round((tmp_df['Current'] - tmp_df['Investment']),0)
  tmp_df['Today P/L%'] = round((tmp_df['Current'] - tmp_df['Previous'])*100/tmp_df['Previous'],2)
  tmp_df['Current P/L%'] = round((tmp_df['Current'] - tmp_df['Investment'])*100/tmp_df['Investment'],2)
  tmp_df['EstimatedST P/L%'] = round((tmp_df['EstimatedST'] - tmp_df['Investment'])*100/tmp_df['Investment'],2)
  tmp_df['EstimatedLT P/L%'] = round((tmp_df['EstimatedLT'] - tmp_df['Investment'])*100/tmp_df['Investment'],2)
  tmp_df['NTT%'] = round((tmp_df['NTT'] - tmp_df['Close'])*100/tmp_df['Close'],2)
  tmp_df['LTT%'] = round((tmp_df['LTT'] - tmp_df['Close'])*100/tmp_df['Close'],2)
  tmp_df['Gained%'] = round((tmp_df['Close'] - tmp_df['BOL'])*100/tmp_df['BOL'],2)
  investment = round(sum(tmp_df['AvgCost']*tmp_df['Shares']),0)
  current = round(sum(tmp_df['Close']*tmp_df['Shares']),0)
  tmp_df['InitAlloc%'] = round(tmp_df['Investment']*100/investment,2)
  tmp_df['CurrAlloc%'] = round(tmp_df['Current']*100/current,2)
  tmp_df['FTT'] = tmp_df['LTT']
  tmp_df.loc[tmp_df['Strategy'] == 'NTT', 'FTT'] = tmp_df['NTT']
  tmp_df['FTT%'] = tmp_df['LTT%']
  tmp_df.loc[tmp_df['Strategy'] == 'NTT', 'FTT%'] = tmp_df['NTT%']
  tmp_df['FTT Amt'] = round(tmp_df['FTT%'] * tmp_df['Current']/100,0)
  tmp_df['OTT%'] = round((tmp_df['FTT'] - tmp_df['AvgCost'])*100/tmp_df['AvgCost'],2)
  tmp_df['RRR Ind'] = round(tmp_df['Current P/L']/tmp_df['FTT Amt'],2)
  tmp_df['Risk Ind'] = round(tmp_df['Current P/L%']*tmp_df['CurrAlloc%'],0)

  return tmp_df

# function to print portfolio features
def print_portfolio_stats(df_portfolio_features, myinvmt_df):
  from pyxirr import xirr

  total_booked_amt, reserve_amt, cy_booked_amt, py_booked_amt = get_amt()

  dates = myinvmt_df['Date'].values
  dates = np.append(dates, datetime.date.today().strftime('%d-%b-%y'))
  investment = myinvmt_df['Investment'].values
  dates= pd.to_datetime(dates)

  current = round(sum(df_portfolio_features['Close']*df_portfolio_features['Shares']),0) + reserve_amt
  investment_xirr = np.append(investment, current)
  cagr = round(xirr(pd.DataFrame({"dates": dates, "amounts": investment_xirr}))*100,2)

  investment = -sum(investment)
  invested = round(sum(df_portfolio_features['AvgCost']*df_portfolio_features['Shares']),0) + reserve_amt
  previous = round(sum(df_portfolio_features['Prev_Close']*df_portfolio_features['Shares']),0) + reserve_amt
  cy_invested = investment + py_booked_amt

  today_pnl_amount = current-previous
  today_pnl_percentage = round((current-previous)*100/previous,2)

  curr_pnl_amount = current-invested
  curr_pnl_percentage = round((curr_pnl_amount)*100/(cy_invested),2)

  cy_pnl_amount = cy_booked_amt + curr_pnl_amount
  cy_pnl_percentage = round((cy_pnl_amount)*100/cy_invested,2)

  overall_pnl_amount = total_booked_amt + curr_pnl_amount
  overall_pnl_percentage = round((overall_pnl_amount)*100/investment,2)

  estimate_st = round(sum(df_portfolio_features['FTT']*df_portfolio_features['Shares']),0)  + reserve_amt
  est_st_pnl_amount = estimate_st-current
  est_st_pnl_percentage = round((est_st_pnl_amount)*100/current,2)

  estimate_lt = round(sum(df_portfolio_features['LTT']*df_portfolio_features['Shares']),0)  + reserve_amt
  est_lt_pnl_amount = estimate_lt-current
  est_lt_pnl_percentage = round((est_lt_pnl_amount)*100/current,2)

  total_profit = round(sum(df_portfolio_features[df_portfolio_features['Current P/L%'] > 0]['Current']) - sum(df_portfolio_features[df_portfolio_features['Current P/L%'] > 0]['Investment']),0)
  total_loss = round(sum(df_portfolio_features[df_portfolio_features['Current P/L%'] < 0]['Current']) - sum(df_portfolio_features[df_portfolio_features['Current P/L%'] < 0]['Investment']),0)

  cy_booked_percentage = round((cy_booked_amt)*100/current,2)
  py_booked_percentage = round((py_booked_amt)*100/investment,2)
  total_booked_percentage = round((total_booked_amt)*100/investment,2)

  print('-------------------')
  print('Initial Investment: ', format_amt(investment))
  print('CY Investment: ', format_amt(cy_invested))
  print('Reserve: ', format_amt(reserve_amt))
  print('Current: ',  format_amt(current))
  print('-------------------')
  print('Today PnL: '+ '{} ({}%)'.format(format_amt(today_pnl_amount), today_pnl_percentage))
  print('Current PnL: '+ '{} ({}%)'.format(format_amt(curr_pnl_amount), curr_pnl_percentage))
  print('CY Booked + Current PnL: '+ '{} ({}%)'.format(format_amt(cy_pnl_amount), cy_pnl_percentage))
  print('-------------------')
  print('Total profit: ', format_amt(total_profit))
  print('Total loss: ', format_amt(total_loss))
  print('-------------------')
  print('Total Booked + Current PnL: '+ '{} ({}%)'.format(format_amt(overall_pnl_amount), overall_pnl_percentage))
  print('Total Booked PnL: '+ '{} ({}%)'.format(format_amt(total_booked_amt), total_booked_percentage))
  print('Curr Year Booked PnL: '+ '{} ({}%)'.format(format_amt(cy_booked_amt), cy_booked_percentage))
  print('Prev Year Booked PnL: '+ '{} ({}%)'.format(format_amt(py_booked_amt), py_booked_percentage))
  print('===================')
  print('Est FTT: ',  format_amt(estimate_st))
  print('Est FTT PnL: '+ '{} ({}%)'.format(format_amt(est_st_pnl_amount), est_st_pnl_percentage))

  print('===================')
  print('Deployed: ', format_amt(investment))

  print('Current: ', format_amt(current))

  print('CAGR/XIRR %: '+'{}%'.format(cagr))

In [8]:
# get start and end date
start_date, end_date = get_start_end_date()

# get portfolio and prospects data
mypfs_df = get_mypfs_df()
mypps_df = get_mypps_df()
myinvmt_df = get_myinvmt_df()

# merge above datasets
mypf_df = pd.merge(mypfs_df, mypps_df, on="Symbol")

# seggregate dm and sv portfolio
dm_pf = mypf_df[mypf_df['InPortfolio'] == 'DM']
sv_pf = mypf_df[mypf_df['InPortfolio'] == 'SV']

# build portfolio stock dataframe
dm_stocks = get_stock_ids(dm_pf)
sv_stocks = get_stock_ids(sv_pf)
df_stocks = pd.concat([dm_pf,sv_pf], ignore_index = True)

# arrange common and diff stock features
common_cols = ['Symbol', 'Target', 'Criteria', 'Strategy', 'CumlRnk', 'LatestQtr', 'StarStock', 'Conviction', 'Category', 'InFolio', 'XIRR', 'MBQ']
diff_cols = ['Symbol', 'AvgCost', 'Shares']
df_stocks = arrange_features(df_stocks, common_cols, diff_cols)

# get common features
stock_ids = df_stocks['Symbol'].values
df_common_features = get_common_features(stock_ids, df_stocks)

df_common_features.reset_index(drop=True, inplace=True)
df_common_features.drop(['Date'], axis=1, inplace=True)
# get and print portfolio features
df_portfolio_features = get_portfolio_features(df_common_features)

print_portfolio_stats(df_portfolio_features, myinvmt_df)

df = df_portfolio_features
#plot_pie_chart(df, 'CapType', 'Current')
list_ox40n = list(df[df['MBQ'].str.contains('OX40N', na=False)]['Symbol'].values)

Run date time (IST): 2026-07-21 15:55:26
-------------------
qualified stocks: 92
with latest results: 31
still star stocks: 20
-------------------
Initial Investment:  1.40 C
CY Investment:  1.82 C
Reserve:  1.49 K
Current:  1.53 C
-------------------
Today PnL: -1.15 K (-0.01%)
Current PnL: -30.20 L (-16.56%)
CY Booked + Current PnL: -28.12 L (-15.42%)
-------------------
Total profit:  4.76 L
Total loss:  -34.96 L
-------------------
Total Booked + Current PnL: 14.75 L (10.57%)
Total Booked PnL: 44.95 L (32.22%)
Curr Year Booked PnL: 2.08 L (1.36%)
Prev Year Booked PnL: 42.87 L (30.73%)
===================
Est FTT:  2.55 C
Est FTT PnL: 1.02 C (66.61%)
===================
Deployed:  1.40 C
Current:  1.53 C
CAGR/XIRR %: 4.15%

In [9]:
# top 5 near their targets
cols = ['Symbol', 'Today P/L%', 'Current P/L%', 'FTT%', 'OTT%', 'FTT Amt', 'Current P/L', 'Current', 'FTT', 'Dev%_PE', 'RSI_14','Conviction', 'Spread%',  'CumlRnk', 'RRR Ind', 'CurrAlloc%', 'Gained%', 'Criteria', 'Strategy', 'Category']
df_tmp = df_portfolio_features[~df_portfolio_features['Symbol'].isin(['ENRIN','BLUSPRING','DIGITIDE'])]
df_tmp = df_tmp.sort_values(by = 'FTT Amt', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
49,JSWINFRA,-1.12,17.30,-0.74,16.43,-1925.0,38361.0,260135.0,342.00,0.56,63.0,X-MC,19.18,61.0,-19.93,1.70,47.49,X40N,NTT,REALTY
59,PIDILITIND,1.63,12.77,4.96,18.37,7893.0,18020.0,159130.0,1670.26,-21.05,57.0,X-LC,8.17,5.0,2.28,1.04,24.95,X40,ATH,CHEMICALS
73,SONACOMS,2.55,26.76,9.41,38.69,12067.0,27072.0,128231.0,801.69,0.46,84.0,M-MC,24.27,193.0,2.24,0.84,81.93,AR,ATH,AUTO
83,TTKPRESTIG,-1.40,-14.71,17.35,0.09,14913.0,-14821.0,85956.0,770.00,99.57,64.0,M-SC,9.91,250.0,-0.99,0.56,53.06,OX40N,NTT,DURABLES
56,MEDANTA,0.84,14.85,10.68,27.12,21652.0,26216.0,202733.0,1486.00,11.29,60.0,X-SC,11.14,87.0,1.21,1.33,39.69,XY24,NTT,HEALTHCARE

In [10]:
# top 5 today
df_tmp = df_portfolio_features.sort_values(by = 'Today P/L%', ascending=False)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
61,RAJESHEXPO,5.00,-82.27,464.33,0.07,112944.0,-112853.0,24324.0,518.0,791.41,48.0,L-SC,35.73,268.0,-1.00,0.16,20.13,OX40N,NTT,JEWELLERY
62,RAJOOENG,4.99,-47.70,166.93,39.61,89491.0,-48890.0,53610.0,143.1,-64.67,57.0,H-SC,20.46,136.0,-0.55,0.35,14.85,AR,ATH,MISC
75,SURYODAY,4.02,8.46,13.44,23.03,26103.0,15147.0,194218.0,216.0,112.72,64.0,H-SC,22.06,166.0,0.58,1.27,64.86,XR,NTT,BANKS
11,BERGEPAINT,3.20,-6.68,34.28,25.32,82457.0,-17209.0,240540.0,680.0,-11.78,50.0,X-MC,1.80,68.0,-0.21,1.57,25.19,XY24,NTT,PAINTS
44,INDUSINDBK,2.96,-21.49,69.26,32.89,41983.0,-16590.0,60617.0,1800.0,-385.01,73.0,L-MC,12.32,258.0,-0.40,0.40,49.44,XR,NTT,BANKS

In [11]:
# bottom 5 today
df_tmp = df_portfolio_features.sort_values(by = 'Today P/L%', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
64,RELAXO,-5.97,-46.78,186.17,52.31,143833.0,-67901.0,77259.0,1176.00,-43.37,57.0,X-SC,12.53,92.0,-0.47,0.51,72.74,X40N,NTT,FOOTWEAR
22,DIXON,-3.23,2.85,34.10,37.92,91471.0,7444.0,268242.0,18931.72,-56.30,65.0,X-MC,6.90,54.0,0.08,1.75,45.95,X40N,ATH,IT
80,TITAGARH,-2.72,-20.58,83.50,45.74,160605.0,-49836.0,192341.0,1548.00,5.84,45.0,H-SC,7.99,175.0,-0.31,1.26,46.75,XY24,NTT,ENGINEERING
78,TATAELXSI,-2.12,-50.11,164.65,32.03,108290.0,-66065.0,65770.0,9161.00,-37.67,32.0,H-SC,20.20,158.0,-0.61,0.43,0.00,OX40N,NTT,IT
34,HDFCBANK,-2.08,-8.91,40.92,28.37,87555.0,-20918.0,213967.0,1073.00,-22.51,38.0,X-LC,11.00,26.0,-0.24,1.40,5.81,X40,BTT,BANKS

In [12]:
# top 5 to exit based on CumlRnk
df_tmp = df_portfolio_features[~df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])]
df_tmp = df_tmp[(df_tmp['Current P/L%'] > -1) & (df_tmp['Current P/L%'] < 1)].sort_values(by = 'CumlRnk', ascending=False)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
9,BANDHANBNK,-1.19,0.46,91.54,92.42,256158.0,1273.0,279832.0,400.0,139.94,52.0,H-SC,20.24,174.0,0.0,1.83,54.15,XY24,NTT,BANKS

In [13]:
# OX40N stocks to exit
df_tmp = df_portfolio_features[(df_portfolio_features['Symbol'].isin(list_ox40n))].sort_values(by = 'Current P/L%', ascending=False)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
25,FINCABLES,-0.91,27.44,63.14,107.91,118804.0,40515.0,188159.0,1641.55,14.66,39.0,M-SC,21.88,220.0,0.34,1.23,41.56,OX40N,ATH,CABLES
72,SIS,1.24,1.39,19.61,21.26,22075.0,1538.0,112570.0,528.00,2689.64,61.0,H-SC,25.01,168.0,0.07,0.74,67.37,OX40N,NTT,MISC
83,TTKPRESTIG,-1.40,-14.71,17.35,0.09,14913.0,-14821.0,85956.0,770.00,99.57,64.0,M-SC,9.91,250.0,-0.99,0.56,53.06,OX40N,NTT,DURABLES
16,CERA,0.78,-18.53,52.06,23.89,74609.0,-32590.0,143313.0,9475.00,-21.48,54.0,H-SC,15.05,153.0,-0.44,0.94,39.31,OX40N,NTT,CERAMICS
43,INDIGOPNTS,-0.05,-23.46,30.67,0.02,40978.0,-40949.0,133610.0,1408.00,103.68,60.0,M-SC,3.69,222.0,-1.00,0.87,51.59,OX40N,NTT,PAINTS

In [14]:
# top 5 to book for rotation
df_tmp = df_portfolio_features[(df_portfolio_features['Current P/L%'] > 20) ].sort_values(by = 'CumlRnk', ascending=False)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
25,FINCABLES,-0.91,27.44,63.14,107.91,118804.0,40515.0,188159.0,1641.55,14.66,39.0,M-SC,21.88,220.0,0.34,1.23,41.56,OX40N,ATH,CABLES
73,SONACOMS,2.55,26.76,9.41,38.69,12067.0,27072.0,128231.0,801.69,0.46,84.0,M-MC,24.27,193.0,2.24,0.84,81.93,AR,ATH,AUTO
68,SATIN,0.93,43.22,6.01,51.83,23782.0,119418.0,395702.0,274.00,28.78,57.0,H-SC,44.48,159.0,5.02,2.59,92.77,XY24,NTT,FINANCE
91,ZYDUSLIFE,-0.51,20.54,12.52,35.63,31629.0,43051.0,252625.0,1286.17,4.95,58.0,H-MC,17.14,120.0,1.36,1.65,32.83,AR,ATH,PHARMA
60,QUESS,1.59,22.90,41.50,73.90,54468.0,24454.0,131247.0,424.00,-33.88,71.0,X-SC,31.88,80.0,0.45,0.86,78.92,XY24,NTT,MISC

In [15]:
# top 5 to monitor for exit
df_tmp = df_portfolio_features[~df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])]
df_tmp = df_tmp[(df_tmp['Current P/L%'] > 0) ].sort_values(by = 'Dev%_PE', ascending=False)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
72,SIS,1.24,1.39,19.61,21.26,22075.0,1538.0,112570.0,528.0,2689.64,61.0,H-SC,25.01,168.0,0.07,0.74,67.37,OX40N,NTT,MISC
9,BANDHANBNK,-1.19,0.46,91.54,92.42,256158.0,1273.0,279832.0,400.0,139.94,52.0,H-SC,20.24,174.0,0.00,1.83,54.15,XY24,NTT,BANKS
75,SURYODAY,4.02,8.46,13.44,23.03,26103.0,15147.0,194218.0,216.0,112.72,64.0,H-SC,22.06,166.0,0.58,1.27,64.86,XR,NTT,BANKS
74,STARHEALTH,1.28,13.91,29.28,47.26,93762.0,39103.0,320226.0,761.0,79.88,57.0,H-SC,19.11,173.0,0.42,2.09,38.96,XY24,NTT,INSURANCE
68,SATIN,0.93,43.22,6.01,51.83,23782.0,119418.0,395702.0,274.0,28.78,57.0,H-SC,44.48,159.0,5.02,2.59,92.77,XY24,NTT,FINANCE

In [16]:
# top 5 to book for rotation from weak conviction
df_tmp = df_portfolio_features[~df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])]
df_tmp = df_tmp[~df_tmp['Criteria'].isin(['XY25','XY24','X40', 'X40N'])].sort_values(by = 'RRR Ind', ascending=False)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
73,SONACOMS,2.55,26.76,9.41,38.69,12067.0,27072.0,128231.0,801.69,0.46,84.0,M-MC,24.27,193.0,2.24,0.84,81.93,AR,ATH,AUTO
91,ZYDUSLIFE,-0.51,20.54,12.52,35.63,31629.0,43051.0,252625.0,1286.17,4.95,58.0,H-MC,17.14,120.0,1.36,1.65,32.83,AR,ATH,PHARMA
75,SURYODAY,4.02,8.46,13.44,23.03,26103.0,15147.0,194218.0,216.00,112.72,64.0,H-SC,22.06,166.0,0.58,1.27,64.86,XR,NTT,BANKS
25,FINCABLES,-0.91,27.44,63.14,107.91,118804.0,40515.0,188159.0,1641.55,14.66,39.0,M-SC,21.88,220.0,0.34,1.23,41.56,OX40N,ATH,CABLES
72,SIS,1.24,1.39,19.61,21.26,22075.0,1538.0,112570.0,528.00,2689.64,61.0,H-SC,25.01,168.0,0.07,0.74,67.37,OX40N,NTT,MISC

In [17]:
# top 5 to accumulate based on lowest RSI_14
df_tmp = df_portfolio_features[df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])].sort_values(by = 'RSI_14', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
39,ICICIGI,0.15,-13.97,38.20,18.89,65759.0,-27965.0,172144.0,2244.41,-27.68,32.0,X-MC,5.73,66.0,-0.43,1.13,0.73,X40,ATH,INSURANCE
87,VBL,-0.97,-6.38,44.60,35.37,131874.0,-20161.0,295681.0,670.16,-17.37,33.0,X-LC,7.75,13.0,-0.15,1.93,21.53,X40N,ATH,FMCG
58,PGHH,0.54,-34.28,100.85,32.01,141529.0,-73184.0,140336.0,17616.87,-55.58,38.0,X-MC,20.30,57.0,-0.52,0.92,0.58,X40,ATH,FMCG
34,HDFCBANK,-2.08,-8.91,40.92,28.37,87555.0,-20918.0,213967.0,1073.00,-22.51,38.0,X-LC,11.00,26.0,-0.24,1.40,5.81,X40,BTT,BANKS
81,TMPV,-0.79,-24.02,79.75,36.58,215626.0,-85463.0,270378.0,600.00,-84.72,39.0,X-LC,7.97,4.0,-0.40,1.77,13.63,XY24,NTT,AUTO

In [18]:
# top 5 to accumulate based on Spread and CumlRnk
df_tmp = df_portfolio_features[df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])]
df_tmp = df_tmp[(df_tmp['CumlRnk'] < 100)].sort_values(by = 'Spread%', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
11,BERGEPAINT,3.20,-6.68,34.28,25.32,82457.0,-17209.0,240540.0,680.00,-11.78,50.0,X-MC,1.80,68.0,-0.21,1.57,25.19,XY24,NTT,PAINTS
23,DMART,0.00,-4.43,35.61,29.60,84943.0,-11064.0,238536.0,5391.45,-19.43,40.0,X-LC,2.04,14.0,-0.13,1.56,9.03,X40N,ATH,FMCG
19,COLPAL,-0.96,-20.53,76.00,39.86,159060.0,-54075.0,209290.0,3683.41,-3.83,58.0,X-MC,2.27,62.0,-0.34,1.37,18.39,XY25,ATH,FMCG
1,ABBOTINDIA,1.86,-3.39,22.20,18.07,38362.0,-6055.0,172800.0,35195.00,-17.69,76.0,X-MC,3.00,58.0,-0.16,1.13,14.38,X40,ATH,PHARMA
17,CIPLA,-0.63,15.98,15.05,33.43,26733.0,24469.0,177630.0,1648.14,-10.44,52.0,X-LC,3.18,18.0,0.92,1.16,21.26,X40N,ATH,PHARMA

In [19]:
# top 5 to accumulate based on lowest Gained%
df_tmp = df_portfolio_features[df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])].sort_values(by = 'Gained%', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
58,PGHH,0.54,-34.28,100.85,32.01,141529.0,-73184.0,140336.0,17616.87,-55.58,38.0,X-MC,20.30,57.0,-0.52,0.92,0.58,X40,ATH,FMCG
39,ICICIGI,0.15,-13.97,38.20,18.89,65759.0,-27965.0,172144.0,2244.41,-27.68,32.0,X-MC,5.73,66.0,-0.43,1.13,0.73,X40,ATH,INSURANCE
47,ITC,-0.60,-25.98,60.85,19.06,153206.0,-88390.0,251776.0,452.00,-59.56,43.0,X-LC,12.65,1.0,-0.58,1.65,1.98,X40,NTT,FMCG
35,HDFCLIFE,-0.65,-8.25,44.64,32.71,61355.0,-12355.0,137445.0,811.41,-28.33,44.0,X-LC,15.33,31.0,-0.20,0.90,3.26,X40,ATH,INSURANCE
65,RELIANCE,-1.47,-16.31,49.73,25.30,83634.0,-32786.0,168177.0,1952.00,-18.49,49.0,X-LC,7.35,21.0,-0.39,1.10,3.57,XY25,BTT,REFINERIES

In [20]:
# top 5 to accumulate based on lowest CurrAlloc%
df_tmp = df_portfolio_features[df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])].sort_values(by = 'CurrAlloc%', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
10,BATAINDIA,-0.23,-54.92,199.90,35.20,115960.0,-70661.0,58009.0,2096.00,-23.90,53.0,X-SC,18.04,91.0,-0.61,0.38,15.05,X40,NTT,FOOTWEAR
64,RELAXO,-5.97,-46.78,186.17,52.31,143833.0,-67901.0,77259.0,1176.00,-43.37,57.0,X-SC,12.53,92.0,-0.47,0.51,72.74,X40N,NTT,FOOTWEAR
60,QUESS,1.59,22.90,41.50,73.90,54468.0,24454.0,131247.0,424.00,-33.88,71.0,X-SC,31.88,80.0,0.45,0.86,78.92,XY24,NTT,MISC
35,HDFCLIFE,-0.65,-8.25,44.64,32.71,61355.0,-12355.0,137445.0,811.41,-28.33,44.0,X-LC,15.33,31.0,-0.20,0.90,3.26,X40,ATH,INSURANCE
28,GODREJCP,-1.00,-5.66,39.35,31.47,55172.0,-8405.0,140209.0,1469.04,-0.80,50.0,X-LC,6.35,32.0,-0.15,0.92,7.58,X40N,ATH,FMCG

In [21]:
# top 5 to accumulate based on CumlRnk
df_tmp = df_portfolio_features.sort_values(by = 'CumlRnk', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
47,ITC,-0.60,-25.98,60.85,19.06,153206.0,-88390.0,251776.0,452.00,-59.56,43.0,X-LC,12.65,1.0,-0.58,1.65,1.98,X40,NTT,FMCG
79,TCS,-1.33,-34.80,90.48,24.20,273313.0,-161203.0,302070.0,4230.71,-44.94,57.0,X-LC,20.14,2.0,-0.59,1.97,12.64,X40,ATH,IT
45,INFY,-1.25,-26.92,83.70,34.24,191385.0,-84232.0,228656.0,1972.00,-42.67,48.0,X-LC,20.92,3.0,-0.44,1.49,8.95,X40,NTT,IT
81,TMPV,-0.79,-24.02,79.75,36.58,215626.0,-85463.0,270378.0,600.00,-84.72,39.0,X-LC,7.97,4.0,-0.40,1.77,13.63,XY24,NTT,AUTO
59,PIDILITIND,1.63,12.77,4.96,18.37,7893.0,18020.0,159130.0,1670.26,-21.05,57.0,X-LC,8.17,5.0,2.28,1.04,24.95,X40,ATH,CHEMICALS

In [22]:
# top 5 for average up
df_tmp = df_portfolio_features[(df_portfolio_features['Dev%_200'] > 5)].sort_values(by = 'CurrAlloc%', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
44,INDUSINDBK,2.96,-21.49,69.26,32.89,41983.0,-16590.0,60617.0,1800.00,-385.01,73.0,L-MC,12.32,258.0,-0.40,0.40,49.44,XR,NTT,BANKS
64,RELAXO,-5.97,-46.78,186.17,52.31,143833.0,-67901.0,77259.0,1176.00,-43.37,57.0,X-SC,12.53,92.0,-0.47,0.51,72.74,X40N,NTT,FOOTWEAR
3,ALKYLAMINE,0.32,-21.77,146.11,92.54,115408.0,-21976.0,78987.0,4520.85,-16.24,52.0,H-SC,11.78,142.0,-0.19,0.52,49.99,SR,ATH,CHEMICALS
83,TTKPRESTIG,-1.40,-14.71,17.35,0.09,14913.0,-14821.0,85956.0,770.00,99.57,64.0,M-SC,9.91,250.0,-0.99,0.56,53.06,OX40N,NTT,DURABLES
72,SIS,1.24,1.39,19.61,21.26,22075.0,1538.0,112570.0,528.00,2689.64,61.0,H-SC,25.01,168.0,0.07,0.74,67.37,OX40N,NTT,MISC

In [23]:
# top 5 RSP
df_tmp = df_portfolio_features.sort_values(by = 'RSP', ascending=False)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
60,QUESS,1.59,22.90,41.50,73.90,54468.0,24454.0,131247.0,424.00,-33.88,71.0,X-SC,31.88,80.0,0.45,0.86,78.92,XY24,NTT,MISC
73,SONACOMS,2.55,26.76,9.41,38.69,12067.0,27072.0,128231.0,801.69,0.46,84.0,M-MC,24.27,193.0,2.24,0.84,81.93,AR,ATH,AUTO
83,TTKPRESTIG,-1.40,-14.71,17.35,0.09,14913.0,-14821.0,85956.0,770.00,99.57,64.0,M-SC,9.91,250.0,-0.99,0.56,53.06,OX40N,NTT,DURABLES
44,INDUSINDBK,2.96,-21.49,69.26,32.89,41983.0,-16590.0,60617.0,1800.00,-385.01,73.0,L-MC,12.32,258.0,-0.40,0.40,49.44,XR,NTT,BANKS
64,RELAXO,-5.97,-46.78,186.17,52.31,143833.0,-67901.0,77259.0,1176.00,-43.37,57.0,X-SC,12.53,92.0,-0.47,0.51,72.74,X40N,NTT,FOOTWEAR

In [24]:
# Top N allocation
df_tmp = df_portfolio_features.sort_values(by = 'CurrAlloc%', ascending=False)
top_n_values = [10, 25, 50]

sum_df = pd.DataFrame({
    'Top_N': top_n_values,
    'Sum_Alloc%': [df_tmp['CurrAlloc%'].head(n).sum() for n in top_n_values]
})

sum_df

   Top_N  Sum_Alloc%
0     10       19.26
1     25       42.52
2     50       72.67

In [25]:
# market-cap-wise allocation
df_tmp = df_portfolio_features[cols]
df_tmp.groupby(df_tmp['Conviction'].str[-2:])['CurrAlloc%'].sum().sort_values(ascending=False)

Conviction
SC    43.73
LC    29.97
MC    26.32
Name: CurrAlloc%, dtype: float64

In [26]:
# criteria-wise allocation
df_portfolio_features.groupby('Criteria')['CurrAlloc%'].sum().sort_values(ascending=False)

Criteria
XY24     27.72
X40      24.60
X40N     17.37
XR        8.89
OX40N     7.05
AR        6.99
XY25      6.50
SR        0.90
Name: CurrAlloc%, dtype: float64

In [27]:
# conviction-wise allocation
df_portfolio_features.groupby('Conviction')['CurrAlloc%'].sum().sort_values(ascending=False)

Conviction
X-LC    27.97
H-SC    23.09
X-MC    21.06
X-SC    10.20
M-SC     9.89
H-MC     2.72
M-MC     2.14
H-LC     1.20
M-LC     0.80
L-SC     0.55
L-MC     0.40
Name: CurrAlloc%, dtype: float64

In [28]:
# sector-wise stats
df_tmp = df_portfolio_features.groupby('Category')[['CurrAlloc%', 'Current', 'Current P/L', 'FTT Amt']].sum().sort_values(by=['Current', 'Current P/L'], ascending=False)
df_tmp['Current P/L%'] = round(df_tmp['Current P/L'] * 100 / df_tmp['Current'], 2)
df_tmp['FTT%'] = round(df_tmp['FTT Amt'] * 100 / df_tmp['Current'], 2)
cols = ['CurrAlloc%', 'Current P/L%', 'FTT%']
df_tmp[cols].sort_values(by=['CurrAlloc%'], ascending=False)

               CurrAlloc%  Current P/L%    FTT%
Category
FMCG                14.21        -21.85   64.59
FINANCE             11.25         -7.17   53.60
IT                  10.09        -45.82  117.98
MISC                 7.26        -20.82   72.66
AUTO                 6.66         -7.62   47.75
BANKS                5.83         -1.88   48.96
PAINTS               5.43        -18.61   38.84
PHARMA               5.25          7.80   20.73
INSURANCE            5.19         -4.42   39.64
ELECTRICAL           4.13        -11.86   51.21
CHEMICALS            2.15        -23.31   96.46
HEALTHCARE           2.08        -12.57   41.95
APPARELS             1.83          4.38   27.74
AC                   1.82        -14.54   45.60
FOOTWEAR             1.72        -68.39  135.90
REALTY               1.70         14.75   -0.74
DURABLES             1.62        -55.65   93.52
BREWERIES            1.56          2.12   18.21
TRAVEL               1.51        -94.68  192.15
CERAMICS             1.43        -40.91   83.72
ENGINEERING          1.26        -25.91   83.50
CABLES               1.23         21.53   63.14
JEWELLERY            1.11        -88.32  153.75
REFINERIES           1.10        -19.49   49.73
CEMENT               1.09        -61.00  181.45
ENTERTAINMENT        0.71        -76.30  181.45
TEXTILES             0.41        -48.81   91.24
HOTELS               0.39        -89.86  156.82

In [29]:
# money to be made criteria-wise
df_portfolio_features.groupby('Criteria')['FTT Amt'].agg(['sum', 'count']).sort_values(by='sum', ascending=False)

                sum  count
Criteria
XY24      3361638.0     21
X40       1906447.0     19
XR        1319289.0     13
AR        1103775.0      9
X40N      1061587.0     13
OX40N      714379.0     10
XY25       441334.0      5
SR         280998.0      2

In [30]:
# money to be made conviction-wise
df_portfolio_features.groupby('Conviction')['FTT Amt'].agg(['sum', 'count']).sort_values(by='sum', ascending=False)

                  sum  count
Conviction
H-SC        3242023.0     24
X-LC        1993144.0     21
X-MC        1493697.0     15
M-SC        1404913.0     14
X-SC        1245833.0      9
H-MC         282386.0      2
L-SC         206735.0      2
M-LC         170294.0      1
M-MC          58245.0      2
H-LC          50194.0      1
L-MC          41983.0      1

In [31]:
# money to be made criteria and conviction-wise
df_portfolio_features.groupby(['Conviction', 'Criteria'])['FTT Amt'].agg(['sum', 'count']).sort_values(by='sum', ascending=False)

                           sum  count
Conviction Criteria
X-LC       X40       1036057.0     10
H-SC       XY24       955059.0      6
           AR         933342.0      5
M-SC       XY24       826990.0      6
H-SC       XR         777976.0      7
X-SC       XY24       735442.0      4
X-MC       X40        662238.0      7
X-LC       X40N       393730.0      6
X-MC       X40N       365618.0      4
X-LC       XY24       361127.0      2
M-SC       OX40N      306787.0      5
X-SC       X40N       302239.0      3
H-SC       OX40N      294648.0      4
           SR         280998.0      2
H-MC       XY24       250757.0      1
X-MC       XY25       233578.0      2
           XY24       232263.0      2
X-SC       X40        208152.0      2
M-SC       XR         194593.0      2
M-LC       XR         170294.0      1
X-LC       XY25       161578.0      2
L-SC       OX40N      112944.0      1
           XR          93791.0      1
M-SC       AR          76543.0      1
H-LC       AR          50194.0      1
M-MC       XY25        46178.0      1
L-MC       XR          41983.0      1
X-LC       XR          40652.0      1
H-MC       AR          31629.0      1
M-MC       AR          12067.0      1

In [32]:
# notebook execution time

end_time = time.time()
execution_time = round(end_time - start_time, 0)
print(f"Notebook execution time: {execution_time} seconds")

Notebook execution time: 64.0 seconds