<a href="https://colab.research.google.com/github/ankit-rathi/Quantvesting_v2/blob/main/myStocks_Portfolio_Analysis.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
'''
!pip install pandas==2.2.2 -qq
!pip install pyxirr -qq
!pip install ta -qq
!pip install yfinance==0.2.59 -qq
'''

'\n!pip install pandas==2.2.2 -qq\n!pip install pyxirr -qq\n!pip install ta -qq\n!pip install yfinance==0.2.59 -qq\n'

In [2]:
# import libraries

import numpy as np
import pandas as pd
import datetime
import warnings
warnings.filterwarnings('ignore')
import yfinance as yfin
import ta
import matplotlib.pyplot as plt
import requests

In [3]:
# notebook start time
import time
import datetime
import pytz

start_time = time.time()

# function to print date timestamp
def print_date_time():
  tz_NY = pytz.timezone('Asia/Kolkata')
  datetime_NY = datetime.datetime.now(tz_NY)
  print("Run date time (IST):", datetime_NY.strftime("%Y-%m-%d %H:%M:%S"))

In [4]:
# function to get booked and reserved amount
def get_amt():
  # fetch the JSON data from the URL
  url = "https://raw.githubusercontent.com/ankit-rathi/Tradevesting_v1/main/data/myPortfolioAmts.json"
  response = requests.get(url)
  pf_amts = response.json()  # parse the JSON data

  # extract values from the JSON
  py_booked_amt_dm = pf_amts["py_booked_amt_dm"]
  py_booked_amt_sv = pf_amts["py_booked_amt_sv"]
  cy_booked_amt_dm = pf_amts["cy_booked_amt_dm"]
  cy_booked_amt_sv = pf_amts["cy_booked_amt_sv"]
  reserve_amt_dm = pf_amts["reserve_amt_dm"]
  reserve_amt_sv = pf_amts["reserve_amt_sv"]

  # perform calculations
  py_booked_amt = py_booked_amt_dm + py_booked_amt_sv
  cy_booked_amt = cy_booked_amt_dm + cy_booked_amt_sv
  reserve_amt = reserve_amt_dm + reserve_amt_sv
  total_booked_amt = py_booked_amt + cy_booked_amt

  return total_booked_amt, reserve_amt, cy_booked_amt, py_booked_amt

gen_output = 0

In [5]:
# function to format the amount
def format_amt(number):
    abs_number = abs(number)

    if abs_number >= 1_00_00_000:  # Crores
        formatted_amt = f"{number / 1_00_00_000:.2f} C"
    elif abs_number >= 1_00_000:  # Lakhs
        formatted_amt = f"{number / 1_00_000:.2f} L"
    elif abs_number >= 1_000:  # Thousands
        formatted_amt = f"{number / 1_000:.2f} K"
    else:
        formatted_amt = f"{number:.2f}"

    return formatted_amt

# function to set start and end date
def get_start_end_date():
  start_date = (datetime.date.today() + datetime.timedelta(days=-365)).strftime('%Y-%m-%d')
  end_date = (datetime.date.today() + datetime.timedelta(days=1)).strftime('%Y-%m-%d')
  return start_date, end_date

# function to fetch my portfolio csv
def get_mypfs_df():
  mypfs_df = pd.read_csv('https://raw.githubusercontent.com/ankit-rathi/Tradevesting_v1/main/data/myPortfolioStocks.csv')
  return mypfs_df

# function to fetch my prospects csv
def get_mypps_df():
  mypps_df = pd.read_csv('https://raw.githubusercontent.com/ankit-rathi/Tradevesting_v1/main/data/myProspectsScrips.csv')
  return mypps_df

# function to fetch screener data
def get_myscreen_df():
  myscreen_df = pd.read_csv('https://raw.githubusercontent.com/ankit-rathi/Tradevesting_v1/main/data/myScreenerDB.csv')
  return myscreen_df

# function to fetch momentum data
def get_myinvmt_df():
  myinvmt_df = pd.read_csv('https://raw.githubusercontent.com/ankit-rathi/Tradevesting_v1/main/data/myInvestments.csv')
  return myinvmt_df

# function to get the stock ids
def get_stock_ids(df_pf):
  stock_n100 = df_pf['Symbol'].unique()

  exclude = ['CADILAHC','MMTC', 'MASFIN']

  stock_ids = df_pf[~df_pf['Symbol'].isin(exclude) ]['Symbol'].unique()

  #mypf = mypf[mypf.Forecast.notnull()]
  #stock_ids = mypf['Symbol'].unique()

  #stock_ids.sort()
  return stock_ids

# get features from screener data
def get_screener_features():
  myscreen_df = get_myscreen_df()
  cols = ['Symbol', 'EPS', 'MedPE', 'ROCE%', 'ROE%', 'CapType']
  return myscreen_df[cols]

# get relative strength
def get_relative_strength(stock_list):

    # Dictionary to store stock tickers and their corresponding percentage price change
    stock_changes = {}

    # Loop through each stock and fetch its price data
    for stock in stock_list:
        try:
            # Download the stock data for the given date range
            stock_data = yfin.Ticker(stock + '.NS').history(period='1mo', interval='1d')[map(str.title, ['open', 'close', 'low', 'high', 'volume'])]

            # Calculate the percentage change for the stock
            if len(stock_data) > 0:
                start_price = stock_data['Close'].iloc[0]
                end_price = stock_data['Close'].iloc[-1]
                percent_change = round(((end_price - start_price) / start_price) * 100, 2)
                stock_changes[stock] = percent_change
            else:
                stock_changes[stock] = np.nan  # If no data is available, set to NaN

        except Exception as e:
            print(f"Error fetching data for {stock}: {e}")
            stock_changes[stock] = np.nan

    # Create a DataFrame with stock tickers and their percentage changes
    df = pd.DataFrame(list(stock_changes.items()), columns=['Symbol', 'Percent_Change'])

    # Drop any stocks with missing data (NaN values)
    df = df.dropna()

    # Calculate the percentile rank based on percentage change
    df['RSP'] = round(df['Percent_Change'].rank(pct=True) * 100, 2)
    cols = ['Symbol', 'RSP']
    df = df[cols]
    # Sort by percentile rank (optional)
    df = df.sort_values(by='RSP', ascending=False).reset_index(drop=True)

    return df

In [6]:
# function to get stock technicals
def stock_prec_dev(stock_symbol):
    #stock_symbol = 'ULTRACEMCO.NS'
    short_window = 20
    mid_window = 50
    long_window = 200
    moving_avg = 'SMA'

    start = datetime.datetime(*map(int, start_date.split('-')))
    end = datetime.datetime(*map(int, end_date.split('-')))

    stock_df = yfin.Ticker(stock_symbol + '.NS').history(period='max', interval='1d')[map(str.title, ['open', 'close', 'low', 'high', 'volume'])]

    stock_df['Max'] = round(max(stock_df['Close']),2)
    stock_df = stock_df[(stock_df.index <= end_date) & (stock_df.index >= start_date)]
    stock_df['200_SMA'] = round(stock_df['Close'].rolling(window = 200, min_periods = 1).mean(),0)
    stock_df['Dev%_200'] = round((stock_df['Close'] - stock_df['200_SMA'])*100/stock_df['200_SMA'],2)
    stock_df.dropna(axis = 0, inplace = True) # remove any null rows

    stock_df['20_SMA'] = stock_df['Close'].rolling(window=20).mean()
    stock_df['50_SMA'] = stock_df['Close'].rolling(window=50).mean()
    stock_df['Symbol'] = stock_symbol

    stock_df['Close'] = round(stock_df['Close'],2)
    stock_df['Min'] = round(min(stock_df['Close']),2)
    stock_df['RSI_14'] = ta.momentum.RSIIndicator(close=stock_df['Close'], window=14).rsi()
    stock_df['RSI_14'] = round(stock_df['RSI_14'],0)
    stock_df['Prev_Close'] = stock_df['Close'].shift(1)
    stock_df.drop(['Open', 'Low', 'High', 'Volume'], axis=1, inplace=True)
    stock_df = stock_df.tail(1)

    max_SMA = max(stock_df['20_SMA'].item(), stock_df['50_SMA'].item(), stock_df['200_SMA'].item())
    min_SMA = min(stock_df['20_SMA'].item(), stock_df['50_SMA'].item(), stock_df['200_SMA'].item())
    ABS_Spread = max_SMA - min_SMA
    stock_df['Spread%'] = round((ABS_Spread / stock_df['200_SMA'].item()) * 100,2)

    return stock_df

# function to compute stock attributes
def get_common_features(stock_ids, df_mypf):

  df_prec_dev = pd.DataFrame()
  df_tmp = get_screener_features()
  df_rs = get_relative_strength(stock_ids)

  for stock_id in stock_ids:
      tmp = stock_prec_dev(stock_id)
      tmp = tmp.reset_index()
      df_prec_dev = pd.concat([df_prec_dev, tmp], ignore_index = True)
  df_prec_dev = pd.merge(df_prec_dev, df_mypf, on= 'Symbol')
  df_prec_dev = pd.merge(df_prec_dev, df_tmp, on= 'Symbol', how='left')
  df_prec_dev = pd.merge(df_prec_dev, df_rs, on= 'Symbol', how='left')
  #print(df_prec_dev.columns)
  df_prec_dev['Curr_PE'] = round(df_prec_dev['Close']/df_prec_dev['EPS'],1)
  df_prec_dev['Dev%_PE'] = round((df_prec_dev['Curr_PE'] - df_prec_dev['MedPE'])*100/df_prec_dev['MedPE'],2)
  df_prec_dev['Conviction'] = df_prec_dev['Conviction'] + '-' + df_prec_dev['CapType']
  return df_prec_dev

# function to arrange stock features
def arrange_features(df_stocks, common_cols, diff_cols):
  df_stocks_common = df_stocks[common_cols].drop_duplicates()
  df_stocks_diff = df_stocks[diff_cols]
  df_stocks_diff['Investment'] = df_stocks_diff['AvgCost'] * df_stocks_diff['Shares']
  df_stocks_diff = df_stocks_diff.groupby(['Symbol'])[['Shares', 'Investment']].aggregate(['sum']).reset_index()
  df_stocks_diff.columns = ['Symbol', 'Shares', 'Investment']
  df_stocks_diff['AvgCost'] = round(df_stocks_diff['Investment']/df_stocks_diff['Shares'],2)
  df_stocks = pd.merge(df_stocks_diff, df_stocks_common, on='Symbol')
  return df_stocks

# plot fact distribution across dimension
def plot_pie_chart(df, dimension, fact):
  # grouping the data by category and calculating the sum of fact for each type
  grouped_data = df.groupby(dimension)[fact].sum()

  # sorting the grouped data in descending order
  grouped_data = grouped_data.sort_values(ascending=False)

  # creating a pie chart
  grouped_data.plot.pie(autopct='%1.1f%%', startangle=90, figsize=(6, 6))

  # adding a title and displaying the plot
  plt.title(f'{dimension} {fact} Distribution')
  plt.ylabel('')  # To hide the y-label
  plt.show()

In [7]:
# function to get portfolio features

def get_portfolio_features(df_common_features):

  print_date_time()
  print('-------------------')

  #df_common_features["Target"] = df_common_features["Target"].fillna(df_common_features["Max"])
  df_common_features['NTT'] = np.where(df_common_features['Strategy']== 'NTT', df_common_features["Target"], df_common_features['Max'])
  df_common_features['LTT'] = np.where(df_common_features['Strategy']== 'BTT', df_common_features["Target"], df_common_features['Max'])
  df_common_features['BOL'] = df_common_features['Min']

  tmp_df = df_common_features[df_common_features['Symbol'].isin(mypf_df[mypf_df['InPortfolio'] != 'NA'].Symbol.values)]
  print('qualified stocks: '+str(len(tmp_df['Symbol'].unique())))
  tmp_df1 = tmp_df[tmp_df['LatestQtr'] == 1]
  print('with latest results: '+str(len(tmp_df1['Symbol'].unique())))
  tmp_df1 = tmp_df1[tmp_df1['StarStock'] == 1]
  print('still star stocks: '+str(len(tmp_df1['Symbol'].unique())))
  tmp_df['Investment'] = tmp_df['AvgCost'] * tmp_df['Shares']
  tmp_df['Current'] = round(tmp_df['Close'] * tmp_df['Shares'],0)
  tmp_df['Previous'] = tmp_df['Prev_Close'] * tmp_df['Shares']
  tmp_df['EstimatedST'] = tmp_df['NTT'] * tmp_df['Shares']
  tmp_df['EstimatedLT'] = tmp_df['LTT'] * tmp_df['Shares']
  tmp_df['Current P/L'] = round((tmp_df['Current'] - tmp_df['Investment']),0)
  tmp_df['Today P/L%'] = round((tmp_df['Current'] - tmp_df['Previous'])*100/tmp_df['Previous'],2)
  tmp_df['Current P/L%'] = round((tmp_df['Current'] - tmp_df['Investment'])*100/tmp_df['Investment'],2)
  tmp_df['EstimatedST P/L%'] = round((tmp_df['EstimatedST'] - tmp_df['Investment'])*100/tmp_df['Investment'],2)
  tmp_df['EstimatedLT P/L%'] = round((tmp_df['EstimatedLT'] - tmp_df['Investment'])*100/tmp_df['Investment'],2)
  tmp_df['NTT%'] = round((tmp_df['NTT'] - tmp_df['Close'])*100/tmp_df['Close'],2)
  tmp_df['LTT%'] = round((tmp_df['LTT'] - tmp_df['Close'])*100/tmp_df['Close'],2)
  tmp_df['Gained%'] = round((tmp_df['Close'] - tmp_df['BOL'])*100/tmp_df['BOL'],2)
  investment = round(sum(tmp_df['AvgCost']*tmp_df['Shares']),0)
  current = round(sum(tmp_df['Close']*tmp_df['Shares']),0)
  tmp_df['InitAlloc%'] = round(tmp_df['Investment']*100/investment,2)
  tmp_df['CurrAlloc%'] = round(tmp_df['Current']*100/current,2)
  tmp_df['FTT'] = tmp_df['LTT']
  tmp_df.loc[tmp_df['Strategy'] == 'NTT', 'FTT'] = tmp_df['NTT']
  tmp_df['FTT%'] = tmp_df['LTT%']
  tmp_df.loc[tmp_df['Strategy'] == 'NTT', 'FTT%'] = tmp_df['NTT%']
  tmp_df['FTT Amt'] = round(tmp_df['FTT%'] * tmp_df['Current']/100,0)
  tmp_df['OTT%'] = round((tmp_df['FTT'] - tmp_df['AvgCost'])*100/tmp_df['AvgCost'],2)
  tmp_df['RRR Ind'] = round(tmp_df['Current P/L']/tmp_df['FTT Amt'],2)
  tmp_df['Risk Ind'] = round(tmp_df['Current P/L%']*tmp_df['CurrAlloc%'],0)

  return tmp_df

# function to print portfolio features
def print_portfolio_stats(df_portfolio_features, myinvmt_df):
  from pyxirr import xirr

  total_booked_amt, reserve_amt, cy_booked_amt, py_booked_amt = get_amt()

  dates = myinvmt_df['Date'].values
  dates = np.append(dates, datetime.date.today().strftime('%d-%b-%y'))
  investment = myinvmt_df['Investment'].values
  dates= pd.to_datetime(dates)

  current = round(sum(df_portfolio_features['Close']*df_portfolio_features['Shares']),0) + reserve_amt
  investment_xirr = np.append(investment, current)
  cagr = round(xirr(pd.DataFrame({"dates": dates, "amounts": investment_xirr}))*100,2)

  investment = -sum(investment)
  invested = round(sum(df_portfolio_features['AvgCost']*df_portfolio_features['Shares']),0) + reserve_amt
  previous = round(sum(df_portfolio_features['Prev_Close']*df_portfolio_features['Shares']),0) + reserve_amt
  cy_invested = investment + py_booked_amt

  today_pnl_amount = current-previous
  today_pnl_percentage = round((current-previous)*100/previous,2)

  curr_pnl_amount = current-invested
  curr_pnl_percentage = round((curr_pnl_amount)*100/(cy_invested),2)

  cy_pnl_amount = cy_booked_amt + curr_pnl_amount
  cy_pnl_percentage = round((cy_pnl_amount)*100/cy_invested,2)

  overall_pnl_amount = total_booked_amt + curr_pnl_amount
  overall_pnl_percentage = round((overall_pnl_amount)*100/investment,2)

  estimate_st = round(sum(df_portfolio_features['FTT']*df_portfolio_features['Shares']),0)  + reserve_amt
  est_st_pnl_amount = estimate_st-current
  est_st_pnl_percentage = round((est_st_pnl_amount)*100/current,2)

  estimate_lt = round(sum(df_portfolio_features['LTT']*df_portfolio_features['Shares']),0)  + reserve_amt
  est_lt_pnl_amount = estimate_lt-current
  est_lt_pnl_percentage = round((est_lt_pnl_amount)*100/current,2)

  total_profit = round(sum(df_portfolio_features[df_portfolio_features['Current P/L%'] > 0]['Current']) - sum(df_portfolio_features[df_portfolio_features['Current P/L%'] > 0]['Investment']),0)
  total_loss = round(sum(df_portfolio_features[df_portfolio_features['Current P/L%'] < 0]['Current']) - sum(df_portfolio_features[df_portfolio_features['Current P/L%'] < 0]['Investment']),0)

  cy_booked_percentage = round((cy_booked_amt)*100/current,2)
  py_booked_percentage = round((py_booked_amt)*100/investment,2)
  total_booked_percentage = round((total_booked_amt)*100/investment,2)

  print('-------------------')
  print('Initial Investment: ', format_amt(investment))
  print('CY Investment: ', format_amt(cy_invested))
  print('Reserve: ', format_amt(reserve_amt))
  print('Current: ',  format_amt(current))
  print('-------------------')
  print('Today PnL: '+ '{} ({}%)'.format(format_amt(today_pnl_amount), today_pnl_percentage))
  print('Current PnL: '+ '{} ({}%)'.format(format_amt(curr_pnl_amount), curr_pnl_percentage))
  print('CY Booked + Current PnL: '+ '{} ({}%)'.format(format_amt(cy_pnl_amount), cy_pnl_percentage))
  print('-------------------')
  print('Total profit: ', format_amt(total_profit))
  print('Total loss: ', format_amt(total_loss))
  print('-------------------')
  print('Total Booked + Current PnL: '+ '{} ({}%)'.format(format_amt(overall_pnl_amount), overall_pnl_percentage))
  print('Total Booked PnL: '+ '{} ({}%)'.format(format_amt(total_booked_amt), total_booked_percentage))
  print('Curr Year Booked PnL: '+ '{} ({}%)'.format(format_amt(cy_booked_amt), cy_booked_percentage))
  print('Prev Year Booked PnL: '+ '{} ({}%)'.format(format_amt(py_booked_amt), py_booked_percentage))
  print('===================')
  print('Est FTT: ',  format_amt(estimate_st))
  print('Est FTT PnL: '+ '{} ({}%)'.format(format_amt(est_st_pnl_amount), est_st_pnl_percentage))

  print('===================')
  print('Deployed: ', format_amt(investment))

  print('Current: ', format_amt(current))

  print('CAGR/XIRR %: '+'{}%'.format(cagr))

In [8]:
# get start and end date
start_date, end_date = get_start_end_date()

# get portfolio and prospects data
mypfs_df = get_mypfs_df()
mypps_df = get_mypps_df()
myinvmt_df = get_myinvmt_df()

# merge above datasets
mypf_df = pd.merge(mypfs_df, mypps_df, on="Symbol")

# seggregate dm and sv portfolio
dm_pf = mypf_df[mypf_df['InPortfolio'] == 'DM']
sv_pf = mypf_df[mypf_df['InPortfolio'] == 'SV']

# build portfolio stock dataframe
dm_stocks = get_stock_ids(dm_pf)
sv_stocks = get_stock_ids(sv_pf)
df_stocks = pd.concat([dm_pf,sv_pf], ignore_index = True)

# arrange common and diff stock features
common_cols = ['Symbol', 'Target', 'Criteria', 'Strategy', 'CumlRnk', 'LatestQtr', 'StarStock', 'Conviction', 'Category', 'InFolio', 'XIRR', 'MBQ']
diff_cols = ['Symbol', 'AvgCost', 'Shares']
df_stocks = arrange_features(df_stocks, common_cols, diff_cols)

# get common features
stock_ids = df_stocks['Symbol'].values
df_common_features = get_common_features(stock_ids, df_stocks)

df_common_features.reset_index(drop=True, inplace=True)
df_common_features.drop(['Date'], axis=1, inplace=True)
# get and print portfolio features
df_portfolio_features = get_portfolio_features(df_common_features)

print_portfolio_stats(df_portfolio_features, myinvmt_df)

df = df_portfolio_features
#plot_pie_chart(df, 'CapType', 'Current')
list_ox40n = list(df[df['MBQ'].str.contains('OX40N', na=False)]['Symbol'].values)

Run date time (IST): 2026-08-17 14:24:32
-------------------
qualified stocks: 88
with latest results: 30
still star stocks: 19
-------------------
Initial Investment:  1.46 C
CY Investment:  1.89 C
Reserve:  2.21 L
Current:  1.59 C
-------------------
Today PnL: -52.38 K (-0.33%)
Current PnL: -33.36 L (-17.66%)
CY Booked + Current PnL: -28.72 L (-15.2%)
-------------------
Total profit:  3.85 L
Total loss:  -37.21 L
-------------------
Total Booked + Current PnL: 14.15 L (9.69%)
Total Booked PnL: 47.52 L (32.53%)
Curr Year Booked PnL: 4.65 L (2.92%)
Prev Year Booked PnL: 42.87 L (29.35%)
===================
Est FTT:  2.68 C
Est FTT PnL: 1.09 C (68.23%)
===================
Deployed:  1.46 C
Current:  1.59 C
CAGR/XIRR %: 3.91%

In [9]:
# top 5 near their targets
cols = ['Symbol', 'Today P/L%', 'Current P/L%', 'FTT%', 'OTT%', 'FTT Amt', 'Current P/L', 'Current', 'FTT', 'Dev%_PE', 'RSI_14','Conviction', 'Spread%',  'CumlRnk', 'RRR Ind', 'CurrAlloc%', 'Gained%', 'Criteria', 'Strategy', 'Category']
df_tmp = df_portfolio_features[~df_portfolio_features['Symbol'].isin(['ENRIN','BLUSPRING','DIGITIDE'])]
df_tmp = df_tmp.sort_values(by = 'FTT Amt', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
79,UNITDSPR,0.52,13.42,6.48,20.77,17209.0,31424.0,265568.0,1644.00,0.62,68.0,X-MC,9.99,64.0,1.83,1.69,27.66,X40N,NTT,BREWERIES
78,TTKPRESTIG,-1.03,-23.34,30.56,0.09,23610.0,-23520.0,77257.0,770.00,79.30,41.0,M-SC,10.49,250.0,-1.00,0.49,39.05,OX40N,NTT,DURABLES
52,M&M,-0.52,7.69,10.34,18.82,26800.0,18509.0,259190.0,3762.88,-6.09,58.0,X-LC,4.76,25.0,0.69,1.65,17.57,X40N,ATH,AUTO
54,MASFIN,1.72,-6.09,29.46,21.57,27106.0,-5970.0,92010.0,397.04,-19.15,46.0,H-SC,0.95,167.0,-0.22,0.59,9.67,XR,ATH,FINANCE
68,SIS,-2.87,-4.16,26.53,21.26,28231.0,-4620.0,106412.0,528.00,2536.79,39.0,H-SC,21.85,168.0,-0.16,0.68,58.22,OX40N,NTT,MISC

In [10]:
# top 5 today
df_tmp = df_portfolio_features.sort_values(by = 'Today P/L%', ascending=False)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
25,FINCABLES,5.20,66.13,25.15,107.91,61690.0,97644.0,245288.0,1641.55,49.67,75.0,M-SC,18.93,220.0,1.58,1.56,84.54,OX40N,ATH,CABLES
18,COFFEEDAY,3.75,-49.44,167.56,35.27,96193.0,-56141.0,57408.0,80.00,-61.77,42.0,L-SC,4.00,266.0,-0.58,0.37,41.57,XR,NTT,HOTELS
12,BOSCH-HCIL,3.63,-24.89,33.12,-0.01,31794.0,-31810.0,95995.0,2282.00,19552.17,75.0,M-SC,5.76,231.0,-1.00,0.61,63.40,OX40N,BTT,AC
55,PAGEIND,1.80,-2.43,36.91,33.59,96656.0,-6509.0,261870.0,51217.29,-30.03,37.0,X-MC,8.67,55.0,-0.07,1.67,24.36,X40,ATH,APPARELS
54,MASFIN,1.72,-6.09,29.46,21.57,27106.0,-5970.0,92010.0,397.04,-19.15,46.0,H-SC,0.95,167.0,-0.22,0.59,9.67,XR,ATH,FINANCE

In [11]:
# bottom 5 today
df_tmp = df_portfolio_features.sort_values(by = 'Today P/L%', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
82,VALIANTORG,-4.99,-35.93,171.81,74.15,180095.0,-58783.0,104822.0,838.0,-288.40,58.0,H-SC,6.38,145.0,-0.33,0.67,55.99,XR,NTT,CHEMICALS
84,VOLTAS,-4.32,-1.16,46.91,45.20,88899.0,-2232.0,189510.0,1856.0,13.14,41.0,X-MC,3.99,79.0,-0.03,1.21,3.87,XY25,NTT,AC
24,EASEMYTRIP,-4.06,-66.11,329.97,45.70,197698.0,-116901.0,59914.0,26.4,-37.76,32.0,M-SC,7.07,204.0,-0.59,0.38,4.96,XY24,NTT,TRAVEL
29,GREENPANEL,-3.75,-55.22,219.64,43.14,180070.0,-101094.0,81984.0,537.0,83.46,29.0,M-SC,10.90,225.0,-0.56,0.52,0.00,XY24,NTT,MISC
65,SFL,-2.98,-33.18,89.52,26.63,156846.0,-87010.0,175208.0,1287.0,32.67,38.0,M-SC,20.13,242.0,-0.55,1.12,46.23,XY24,NTT,MISC

In [12]:
# top 5 to exit based on CumlRnk
df_tmp = df_portfolio_features[~df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])]
df_tmp = df_tmp[(df_tmp['Current P/L%'] > -1) & (df_tmp['Current P/L%'] < 1)].sort_values(by = 'CumlRnk', ascending=False)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
80,UTIAMC,-0.21,-0.15,51.38,51.15,114061.0,-336.0,221994.0,1371.68,-19.83,47.0,M-SC,7.73,229.0,-0.0,1.41,3.99,XY24,ATH,FINANCE

In [13]:
# OX40N stocks to exit
df_tmp = df_portfolio_features[(df_portfolio_features['Symbol'].isin(list_ox40n))].sort_values(by = 'Current P/L%', ascending=False)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
25,FINCABLES,5.20,66.13,25.15,107.91,61690.0,97644.0,245288.0,1641.55,49.67,75.0,M-SC,18.93,220.0,1.58,1.56,84.54,OX40N,ATH,CABLES
68,SIS,-2.87,-4.16,26.53,21.26,28231.0,-4620.0,106412.0,528.00,2536.79,39.0,H-SC,21.85,168.0,-0.16,0.68,58.22,OX40N,NTT,MISC
43,INDIGOPNTS,0.68,-17.85,21.75,0.02,31191.0,-31153.0,143406.0,1408.00,118.75,67.0,M-SC,6.64,222.0,-1.00,0.91,62.70,OX40N,NTT,PAINTS
78,TTKPRESTIG,-1.03,-23.34,30.56,0.09,23610.0,-23520.0,77257.0,770.00,79.30,41.0,M-SC,10.49,250.0,-1.00,0.49,39.05,OX40N,NTT,DURABLES
16,CERA,-2.24,-24.25,63.56,23.89,84687.0,-42664.0,133239.0,9475.00,-26.97,36.0,H-SC,12.56,153.0,-0.50,0.85,29.52,OX40N,NTT,CERAMICS

In [14]:
# top 5 to book for rotation
df_tmp = df_portfolio_features[(df_portfolio_features['Current P/L%'] > 20) ].sort_values(by = 'CumlRnk', ascending=False)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
25,FINCABLES,5.20,66.13,25.15,107.91,61690.0,97644.0,245288.0,1641.55,49.67,75.0,M-SC,18.93,220.0,1.58,1.56,84.54,OX40N,ATH,CABLES
57,QUESS,1.36,40.43,23.83,73.90,35738.0,43178.0,149971.0,424.00,-24.52,71.0,X-SC,43.25,80.0,1.21,0.96,106.41,XY24,NTT,MISC

In [15]:
# top 5 to monitor for exit
df_tmp = df_portfolio_features[~df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])]
df_tmp = df_tmp[(df_tmp['Current P/L%'] > 0) ].sort_values(by = 'Dev%_PE', ascending=False)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
69,STARHEALTH,-0.27,12.93,30.40,47.26,96513.0,36355.0,317478.0,761.00,78.26,50.0,H-SC,16.51,173.0,0.38,2.02,37.27,XY24,NTT,INSURANCE
25,FINCABLES,5.20,66.13,25.15,107.91,61690.0,97644.0,245288.0,1641.55,49.67,75.0,M-SC,18.93,220.0,1.58,1.56,84.54,OX40N,ATH,CABLES
87,ZYDUSLIFE,0.25,20.00,12.92,35.51,32494.0,41924.0,251498.0,1285.01,4.50,51.0,H-MC,15.91,120.0,1.29,1.60,32.35,AR,ATH,PHARMA

In [16]:
# top 5 to book for rotation from weak conviction
df_tmp = df_portfolio_features[~df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])]
df_tmp = df_tmp[~df_tmp['Criteria'].isin(['XY25','XY24','X40', 'X40N'])].sort_values(by = 'RRR Ind', ascending=False)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
25,FINCABLES,5.20,66.13,25.15,107.91,61690.0,97644.0,245288.0,1641.55,49.67,75.0,M-SC,18.93,220.0,1.58,1.56,84.54,OX40N,ATH,CABLES
87,ZYDUSLIFE,0.25,20.00,12.92,35.51,32494.0,41924.0,251498.0,1285.01,4.50,51.0,H-MC,15.91,120.0,1.29,1.60,32.35,AR,ATH,PHARMA
3,ALKYLAMINE,0.10,-18.01,134.85,92.54,111622.0,-18188.0,82775.0,4520.85,-12.24,57.0,H-SC,14.05,142.0,-0.16,0.53,57.18,SR,ATH,CHEMICALS
68,SIS,-2.87,-4.16,26.53,21.26,28231.0,-4620.0,106412.0,528.00,2536.79,39.0,H-SC,21.85,168.0,-0.16,0.68,58.22,OX40N,NTT,MISC
42,INDIAMART,-1.22,-24.02,164.44,100.92,154095.0,-29627.0,93709.0,4675.60,-65.82,39.0,H-SC,13.38,140.0,-0.19,0.60,1.44,AR,ATH,MISC

In [17]:
# top 5 to accumulate based on lowest RSI_14
df_tmp = df_portfolio_features[df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])].sort_values(by = 'RSI_14', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
28,GODREJCP,-0.11,-15.10,56.54,32.90,119785.0,-37678.0,211859.0,1460.97,-12.20,31.0,X-LC,5.69,32.0,-0.31,1.35,3.13,X40N,ATH,FMCG
56,PGHH,-0.61,-37.24,110.35,32.01,147869.0,-79520.0,134000.0,17616.87,-57.60,33.0,X-MC,19.61,57.0,-0.54,0.85,0.00,X40,ATH,FMCG
34,HDFCBANK,-0.01,-11.21,47.60,31.05,123878.0,-32872.0,260248.0,1073.00,-25.96,34.0,X-LC,12.63,26.0,-0.27,1.66,1.01,X40,BTT,BANKS
47,ITC,-1.82,-24.64,65.48,24.70,196029.0,-97906.0,299372.0,452.00,-60.37,35.0,X-LC,10.54,1.0,-0.50,1.91,0.00,X40,NTT,FMCG
37,HONAUT,-2.10,-5.56,59.76,50.88,108838.0,-10713.0,182125.0,58192.80,-21.53,37.0,X-SC,12.76,90.0,-0.10,1.16,38.76,X40N,ATH,ELECTRICAL

In [18]:
# top 5 to accumulate based on Spread and CumlRnk
df_tmp = df_portfolio_features[df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])]
df_tmp = df_tmp[(df_tmp['CumlRnk'] < 100)].sort_values(by = 'Spread%', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
19,COLPAL,-0.61,-25.24,87.07,39.86,171441.0,-66465.0,196900.0,3683.41,-9.44,37.0,X-MC,1.60,62.0,-0.39,1.25,11.38,XY25,ATH,FMCG
23,DMART,-1.11,-2.14,34.29,31.42,104630.0,-6658.0,305132.0,5391.45,-18.62,49.0,X-LC,2.47,14.0,-0.06,1.94,10.11,X40N,ATH,FMCG
50,KOTAKBANK,0.68,3.50,14.90,18.92,36966.0,8392.0,248094.0,452.46,-9.84,54.0,X-LC,2.62,12.0,0.23,1.58,11.62,X40,ATH,BANKS
26,GILLETTE,-0.39,-10.55,45.03,29.72,102263.0,-26796.0,227100.0,10978.86,-31.19,40.0,X-SC,3.38,83.0,-0.26,1.45,4.36,X40,ATH,FMCG
84,VOLTAS,-4.32,-1.16,46.91,45.20,88899.0,-2232.0,189510.0,1856.00,13.14,41.0,X-MC,3.99,79.0,-0.03,1.21,3.87,XY25,NTT,AC

In [19]:
# top 5 to accumulate based on lowest Gained%
df_tmp = df_portfolio_features[df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])].sort_values(by = 'Gained%', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
47,ITC,-1.82,-24.64,65.48,24.70,196029.0,-97906.0,299372.0,452.00,-60.37,35.0,X-LC,10.54,1.0,-0.50,1.91,0.00,X40,NTT,FMCG
56,PGHH,-0.61,-37.24,110.35,32.01,147869.0,-79520.0,134000.0,17616.87,-57.60,33.0,X-MC,19.61,57.0,-0.54,0.85,0.00,X40,ATH,FMCG
20,DABUR,0.30,-20.53,80.83,43.70,159339.0,-50940.0,197128.0,735.00,-27.96,37.0,X-MC,9.83,70.0,-0.32,1.26,0.31,XY24,BTT,FMCG
34,HDFCBANK,-0.01,-11.21,47.60,31.05,123878.0,-32872.0,260248.0,1073.00,-25.96,34.0,X-LC,12.63,26.0,-0.27,1.66,1.01,X40,BTT,BANKS
35,HDFCLIFE,1.13,-7.07,49.73,39.15,115879.0,-17720.0,233017.0,811.41,-30.80,43.0,X-LC,16.63,31.0,-0.15,1.48,1.13,X40,ATH,INSURANCE

In [20]:
# top 5 to accumulate based on lowest CurrAlloc%
df_tmp = df_portfolio_features[df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])].sort_values(by = 'CurrAlloc%', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
10,BATAINDIA,-0.01,-51.26,177.38,35.20,111251.0,-65951.0,62719.0,2096.00,-17.83,68.0,X-SC,12.32,91.0,-0.59,0.40,26.01,X40,NTT,FOOTWEAR
61,RELAXO,-1.25,-49.32,200.54,52.31,147525.0,-71596.0,73564.0,1176.00,-46.08,44.0,X-SC,13.30,92.0,-0.49,0.47,64.48,X40N,NTT,FOOTWEAR
56,PGHH,-0.61,-37.24,110.35,32.01,147869.0,-79520.0,134000.0,17616.87,-57.60,33.0,X-MC,19.61,57.0,-0.54,0.85,0.00,X40,ATH,FMCG
57,QUESS,1.36,40.43,23.83,73.90,35738.0,43178.0,149971.0,424.00,-24.52,71.0,X-SC,43.25,80.0,1.21,0.96,106.41,XY24,NTT,MISC
2,ACC,-0.56,-41.19,197.26,74.81,311040.0,-110448.0,157680.0,3906.00,-58.35,39.0,X-SC,11.77,85.0,-0.36,1.00,5.34,XY24,BTT,CEMENT

In [21]:
# top 5 to accumulate based on CumlRnk
df_tmp = df_portfolio_features.sort_values(by = 'CumlRnk', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
47,ITC,-1.82,-24.64,65.48,24.70,196029.0,-97906.0,299372.0,452.00,-60.37,35.0,X-LC,10.54,1.0,-0.50,1.91,0.00,X40,NTT,FMCG
74,TCS,-1.79,-31.93,82.46,24.20,260032.0,-147930.0,315343.0,4230.71,-42.31,49.0,X-LC,14.71,2.0,-0.57,2.01,17.59,X40,ATH,IT
45,INFY,-2.57,-18.50,72.26,40.38,221698.0,-69664.0,306806.0,1972.00,-38.68,52.0,X-LC,16.01,3.0,-0.31,1.95,16.19,X40,NTT,IT
76,TMPV,-0.93,-21.15,81.05,42.75,265914.0,-88021.0,328086.0,600.00,-84.72,41.0,X-LC,4.42,4.0,-0.33,2.09,12.81,XY24,NTT,AUTO
33,HCLTECH,-1.99,-10.84,39.04,23.97,107723.0,-33555.0,275931.0,1853.42,-9.02,59.0,X-LC,11.94,8.0,-0.31,1.76,30.21,X40,ATH,IT

In [22]:
# top 5 for average up
df_tmp = df_portfolio_features[(df_portfolio_features['Dev%_200'] > 5)].sort_values(by = 'CurrAlloc%', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
44,INDUSINDBK,-1.21,-25.26,77.81,32.89,44897.0,-19506.0,57701.0,1800.00,-371.71,53.0,L-MC,13.51,258.0,-0.43,0.37,42.26,XR,NTT,BANKS
61,RELAXO,-1.25,-49.32,200.54,52.31,147525.0,-71596.0,73564.0,1176.00,-46.08,44.0,X-SC,13.30,92.0,-0.49,0.47,64.48,X40N,NTT,FOOTWEAR
3,ALKYLAMINE,0.10,-18.01,134.85,92.54,111622.0,-18188.0,82775.0,4520.85,-12.24,57.0,H-SC,14.05,142.0,-0.16,0.53,57.18,SR,ATH,CHEMICALS
12,BOSCH-HCIL,3.63,-24.89,33.12,-0.01,31794.0,-31810.0,95995.0,2282.00,19552.17,75.0,M-SC,5.76,231.0,-1.00,0.61,63.40,OX40N,BTT,AC
82,VALIANTORG,-4.99,-35.93,171.81,74.15,180095.0,-58783.0,104822.0,838.00,-288.40,58.0,H-SC,6.38,145.0,-0.33,0.67,55.99,XR,NTT,CHEMICALS

In [23]:
# top 5 RSP
df_tmp = df_portfolio_features.sort_values(by = 'RSP', ascending=False)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
12,BOSCH-HCIL,3.63,-24.89,33.12,-0.01,31794.0,-31810.0,95995.0,2282.00,19552.17,75.0,M-SC,5.76,231.0,-1.00,0.61,63.40,OX40N,BTT,AC
25,FINCABLES,5.20,66.13,25.15,107.91,61690.0,97644.0,245288.0,1641.55,49.67,75.0,M-SC,18.93,220.0,1.58,1.56,84.54,OX40N,ATH,CABLES
57,QUESS,1.36,40.43,23.83,73.90,35738.0,43178.0,149971.0,424.00,-24.52,71.0,X-SC,43.25,80.0,1.21,0.96,106.41,XY24,NTT,MISC
82,VALIANTORG,-4.99,-35.93,171.81,74.15,180095.0,-58783.0,104822.0,838.00,-288.40,58.0,H-SC,6.38,145.0,-0.33,0.67,55.99,XR,NTT,CHEMICALS
11,BERGEPAINT,0.81,1.50,23.47,25.32,61399.0,3857.0,261606.0,680.00,-4.06,62.0,X-MC,4.14,68.0,0.06,1.67,37.18,XY24,NTT,PAINTS

In [24]:
# Top N allocation
df_tmp = df_portfolio_features.sort_values(by = 'CurrAlloc%', ascending=False)
top_n_values = [10, 25, 50]

sum_df = pd.DataFrame({
    'Top_N': top_n_values,
    'Sum_Alloc%': [df_tmp['CurrAlloc%'].head(n).sum() for n in top_n_values]
})

sum_df

   Top_N  Sum_Alloc%
0     10       19.60
1     25       44.81
2     50       76.93

In [25]:
# market-cap-wise allocation
df_tmp = df_portfolio_features[cols]
df_tmp.groupby(df_tmp['Conviction'].str[-2:])['CurrAlloc%'].sum().sort_values(ascending=False)

Conviction
SC    39.38
LC    37.54
MC    23.12
Name: CurrAlloc%, dtype: float64

In [26]:
# criteria-wise allocation
df_portfolio_features.groupby('Criteria')['CurrAlloc%'].sum().sort_values(ascending=False)

Criteria
X40      26.46
XY24     24.80
X40N     18.38
XR        9.03
OX40N     7.23
XY25      7.20
AR        6.08
SR        0.86
Name: CurrAlloc%, dtype: float64

In [27]:
# conviction-wise allocation
df_portfolio_features.groupby('Conviction')['CurrAlloc%'].sum().sort_values(ascending=False)

Conviction
X-LC    35.48
H-SC    19.10
X-MC    18.92
M-SC    11.19
X-SC     8.58
H-MC     2.64
H-LC     1.25
M-MC     1.19
M-LC     0.81
L-SC     0.51
L-MC     0.37
Name: CurrAlloc%, dtype: float64

In [28]:
# sector-wise stats
df_tmp = df_portfolio_features.groupby('Category')[['CurrAlloc%', 'Current', 'Current P/L', 'FTT Amt']].sum().sort_values(by=['Current', 'Current P/L'], ascending=False)
df_tmp['Current P/L%'] = round(df_tmp['Current P/L'] * 100 / df_tmp['Current'], 2)
df_tmp['FTT%'] = round(df_tmp['FTT Amt'] * 100 / df_tmp['Current'], 2)
cols = ['CurrAlloc%', 'Current P/L%', 'FTT%']
df_tmp[cols].sort_values(by=['CurrAlloc%'], ascending=False)

               CurrAlloc%  Current P/L%    FTT%
Category
FMCG                15.34        -23.82   68.34
IT                  11.08        -37.11  105.17
FINANCE             10.62        -15.95   65.90
AUTO                 8.22         -4.81   42.34
MISC                 6.91        -23.87   77.02
BANKS                6.08        -11.93   60.20
PHARMA               5.68          7.03   19.33
INSURANCE            5.65         -4.61   41.60
PAINTS               5.52        -13.88   33.30
ELECTRICAL           4.16         -8.27   46.17
AC                   1.82        -11.92   42.27
REFINERIES           1.71        -11.15   48.49
BREWERIES            1.69         11.83    6.48
APPARELS             1.67         -2.49   36.91
FOOTWEAR             1.66        -70.04  138.23
CABLES               1.56         39.81   25.15
DURABLES             1.47        -67.93  108.79
TRAVEL               1.42       -100.91  201.51
CERAMICS             1.33        -47.25   91.98
CHEMICALS            1.20        -41.03  155.50
ENGINEERING          1.19        -29.83   89.21
CEMENT               1.00        -70.05  197.26
JEWELLERY            0.95       -115.47  190.33
ENTERTAINMENT        0.68        -79.34  186.30
HEALTHCARE           0.68        -69.84  112.48
TEXTILES             0.38        -52.70   96.24
HOTELS               0.37        -97.79  167.56

In [29]:
# money to be made criteria-wise
df_portfolio_features.groupby('Criteria')['FTT Amt'].agg(['sum', 'count']).sort_values(by='sum', ascending=False)

                sum  count
Criteria
XY24      3624318.0     20
X40       2073724.0     18
XR        1380604.0     13
X40N      1194646.0     12
AR        1077928.0      8
OX40N      657240.0     10
XY25       568961.0      5
SR         282617.0      2

In [30]:
# money to be made conviction-wise
df_portfolio_features.groupby('Conviction')['FTT Amt'].agg(['sum', 'count']).sort_values(by='sum', ascending=False)

                  sum  count
Conviction
H-SC        3357404.0     23
X-LC        2489118.0     20
M-SC        1495435.0     15
X-MC        1485118.0     14
X-SC        1233381.0      8
H-MC         283454.0      2
L-SC         211590.0      2
M-LC         165306.0      1
M-MC          58662.0      1
L-MC          44897.0      1
H-LC          35673.0      1

In [31]:
# money to be made criteria and conviction-wise
df_portfolio_features.groupby(['Conviction', 'Criteria'])['FTT Amt'].agg(['sum', 'count']).sort_values(by='sum', ascending=False)

                           sum  count
Conviction Criteria
X-LC       X40       1201817.0      9
H-SC       XY24      1017012.0      5
M-SC       XY24       986340.0      7
H-SC       AR         934000.0      5
           XR         819975.0      7
X-SC       XY24       705400.0      3
X-MC       X40        658393.0      7
X-LC       X40N       534532.0      6
           XY24       443868.0      2
X-MC       X40N       345647.0      3
X-SC       X40N       314467.0      3
H-SC       OX40N      303800.0      4
           SR         282617.0      2
X-MC       XY25       260340.0      2
H-MC       XY24       250960.0      1
X-LC       XY25       249959.0      2
M-SC       OX40N      238043.0      5
X-MC       XY24       220738.0      2
X-SC       X40        213514.0      2
M-SC       XR         195291.0      2
M-LC       XR         165306.0      1
L-SC       OX40N      115397.0      1
           XR          96193.0      1
M-SC       AR          75761.0      1
X-LC       XR          58942.0      1
M-MC       XY25        58662.0      1
L-MC       XR          44897.0      1
H-LC       AR          35673.0      1
H-MC       AR          32494.0      1

In [32]:
# notebook execution time

end_time = time.time()
execution_time = round(end_time - start_time, 0)
print(f"Notebook execution time: {execution_time} seconds")

Notebook execution time: 43.0 seconds