<a href="https://colab.research.google.com/github/ankit-rathi/Quantvesting_v2/blob/main/myStocks_Portfolio_Analysis.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
'''
!pip install pandas==2.2.2 -qq
!pip install pyxirr -qq
!pip install ta -qq
!pip install yfinance==0.2.59 -qq
'''

'\n!pip install pandas==2.2.2 -qq\n!pip install pyxirr -qq\n!pip install ta -qq\n!pip install yfinance==0.2.59 -qq\n'

In [2]:
# import libraries

import numpy as np
import pandas as pd
import datetime
import warnings
warnings.filterwarnings('ignore')
import yfinance as yfin
import ta
import matplotlib.pyplot as plt
import requests

In [3]:
# notebook start time
import time
import datetime
import pytz

start_time = time.time()

# function to print date timestamp
def print_date_time():
  tz_NY = pytz.timezone('Asia/Kolkata')
  datetime_NY = datetime.datetime.now(tz_NY)
  print("Run date time (IST):", datetime_NY.strftime("%Y-%m-%d %H:%M:%S"))

In [4]:
# function to get booked and reserved amount
def get_amt():
  # fetch the JSON data from the URL
  url = "https://raw.githubusercontent.com/ankit-rathi/Tradevesting_v1/main/data/myPortfolioAmts.json"
  response = requests.get(url)
  pf_amts = response.json()  # parse the JSON data

  # extract values from the JSON
  py_booked_amt_dm = pf_amts["py_booked_amt_dm"]
  py_booked_amt_sv = pf_amts["py_booked_amt_sv"]
  cy_booked_amt_dm = pf_amts["cy_booked_amt_dm"]
  cy_booked_amt_sv = pf_amts["cy_booked_amt_sv"]
  reserve_amt_dm = pf_amts["reserve_amt_dm"]
  reserve_amt_sv = pf_amts["reserve_amt_sv"]

  # perform calculations
  py_booked_amt = py_booked_amt_dm + py_booked_amt_sv
  cy_booked_amt = cy_booked_amt_dm + cy_booked_amt_sv
  reserve_amt = reserve_amt_dm + reserve_amt_sv
  total_booked_amt = py_booked_amt + cy_booked_amt

  return total_booked_amt, reserve_amt, cy_booked_amt, py_booked_amt

gen_output = 0

In [5]:
# function to format the amount
def format_amt(number):
    abs_number = abs(number)

    if abs_number >= 1_00_00_000:  # Crores
        formatted_amt = f"{number / 1_00_00_000:.2f} C"
    elif abs_number >= 1_00_000:  # Lakhs
        formatted_amt = f"{number / 1_00_000:.2f} L"
    elif abs_number >= 1_000:  # Thousands
        formatted_amt = f"{number / 1_000:.2f} K"
    else:
        formatted_amt = f"{number:.2f}"

    return formatted_amt

# function to set start and end date
def get_start_end_date():
  start_date = (datetime.date.today() + datetime.timedelta(days=-365)).strftime('%Y-%m-%d')
  end_date = (datetime.date.today() + datetime.timedelta(days=1)).strftime('%Y-%m-%d')
  return start_date, end_date

# function to fetch my portfolio csv
def get_mypfs_df():
  mypfs_df = pd.read_csv('https://raw.githubusercontent.com/ankit-rathi/Tradevesting_v1/main/data/myPortfolioStocks.csv')
  return mypfs_df

# function to fetch my prospects csv
def get_mypps_df():
  mypps_df = pd.read_csv('https://raw.githubusercontent.com/ankit-rathi/Tradevesting_v1/main/data/myProspectsScrips.csv')
  return mypps_df

# function to fetch screener data
def get_myscreen_df():
  myscreen_df = pd.read_csv('https://raw.githubusercontent.com/ankit-rathi/Tradevesting_v1/main/data/myScreenerDB.csv')
  return myscreen_df

# function to fetch momentum data
def get_myinvmt_df():
  myinvmt_df = pd.read_csv('https://raw.githubusercontent.com/ankit-rathi/Tradevesting_v1/main/data/myInvestments.csv')
  return myinvmt_df

# function to get the stock ids
def get_stock_ids(df_pf):
  stock_n100 = df_pf['Symbol'].unique()

  exclude = ['CADILAHC','MMTC', 'MASFIN']

  stock_ids = df_pf[~df_pf['Symbol'].isin(exclude) ]['Symbol'].unique()

  #mypf = mypf[mypf.Forecast.notnull()]
  #stock_ids = mypf['Symbol'].unique()

  #stock_ids.sort()
  return stock_ids

# get features from screener data
def get_screener_features():
  myscreen_df = get_myscreen_df()
  cols = ['Symbol', 'EPS', 'MedPE', 'ROCE%', 'ROE%', 'CapType']
  return myscreen_df[cols]

# get relative strength
def get_relative_strength(stock_list):

    # Dictionary to store stock tickers and their corresponding percentage price change
    stock_changes = {}

    # Loop through each stock and fetch its price data
    for stock in stock_list:
        try:
            # Download the stock data for the given date range
            stock_data = yfin.Ticker(stock + '.NS').history(period='1mo', interval='1d')[map(str.title, ['open', 'close', 'low', 'high', 'volume'])]

            # Calculate the percentage change for the stock
            if len(stock_data) > 0:
                start_price = stock_data['Close'].iloc[0]
                end_price = stock_data['Close'].iloc[-1]
                percent_change = round(((end_price - start_price) / start_price) * 100, 2)
                stock_changes[stock] = percent_change
            else:
                stock_changes[stock] = np.nan  # If no data is available, set to NaN

        except Exception as e:
            print(f"Error fetching data for {stock}: {e}")
            stock_changes[stock] = np.nan

    # Create a DataFrame with stock tickers and their percentage changes
    df = pd.DataFrame(list(stock_changes.items()), columns=['Symbol', 'Percent_Change'])

    # Drop any stocks with missing data (NaN values)
    df = df.dropna()

    # Calculate the percentile rank based on percentage change
    df['RSP'] = round(df['Percent_Change'].rank(pct=True) * 100, 2)
    cols = ['Symbol', 'RSP']
    df = df[cols]
    # Sort by percentile rank (optional)
    df = df.sort_values(by='RSP', ascending=False).reset_index(drop=True)

    return df

In [6]:
# function to get stock technicals
def stock_prec_dev(stock_symbol):
    #stock_symbol = 'ULTRACEMCO.NS'
    short_window = 20
    mid_window = 50
    long_window = 200
    moving_avg = 'SMA'

    start = datetime.datetime(*map(int, start_date.split('-')))
    end = datetime.datetime(*map(int, end_date.split('-')))

    stock_df = yfin.Ticker(stock_symbol + '.NS').history(period='max', interval='1d')[map(str.title, ['open', 'close', 'low', 'high', 'volume'])]

    stock_df['Max'] = round(max(stock_df['Close']),2)
    stock_df = stock_df[(stock_df.index <= end_date) & (stock_df.index >= start_date)]
    stock_df['200_SMA'] = round(stock_df['Close'].rolling(window = 200, min_periods = 1).mean(),0)
    stock_df['Dev%_200'] = round((stock_df['Close'] - stock_df['200_SMA'])*100/stock_df['200_SMA'],2)
    stock_df.dropna(axis = 0, inplace = True) # remove any null rows

    stock_df['20_SMA'] = stock_df['Close'].rolling(window=20).mean()
    stock_df['50_SMA'] = stock_df['Close'].rolling(window=50).mean()
    stock_df['Symbol'] = stock_symbol

    stock_df['Close'] = round(stock_df['Close'],2)
    stock_df['Min'] = round(min(stock_df['Close']),2)
    stock_df['RSI_14'] = ta.momentum.RSIIndicator(close=stock_df['Close'], window=14).rsi()
    stock_df['RSI_14'] = round(stock_df['RSI_14'],0)
    stock_df['Prev_Close'] = stock_df['Close'].shift(1)
    stock_df.drop(['Open', 'Low', 'High', 'Volume'], axis=1, inplace=True)
    stock_df = stock_df.tail(1)

    max_SMA = max(stock_df['20_SMA'].item(), stock_df['50_SMA'].item(), stock_df['200_SMA'].item())
    min_SMA = min(stock_df['20_SMA'].item(), stock_df['50_SMA'].item(), stock_df['200_SMA'].item())
    ABS_Spread = max_SMA - min_SMA
    stock_df['Spread%'] = round((ABS_Spread / stock_df['200_SMA'].item()) * 100,2)

    return stock_df

# function to compute stock attributes
def get_common_features(stock_ids, df_mypf):

  df_prec_dev = pd.DataFrame()
  df_tmp = get_screener_features()
  df_rs = get_relative_strength(stock_ids)

  for stock_id in stock_ids:
      tmp = stock_prec_dev(stock_id)
      tmp = tmp.reset_index()
      df_prec_dev = pd.concat([df_prec_dev, tmp], ignore_index = True)
  df_prec_dev = pd.merge(df_prec_dev, df_mypf, on= 'Symbol')
  df_prec_dev = pd.merge(df_prec_dev, df_tmp, on= 'Symbol', how='left')
  df_prec_dev = pd.merge(df_prec_dev, df_rs, on= 'Symbol', how='left')
  #print(df_prec_dev.columns)
  df_prec_dev['Curr_PE'] = round(df_prec_dev['Close']/df_prec_dev['EPS'],1)
  df_prec_dev['Dev%_PE'] = round((df_prec_dev['Curr_PE'] - df_prec_dev['MedPE'])*100/df_prec_dev['MedPE'],2)
  df_prec_dev['Conviction'] = df_prec_dev['Conviction'] + '-' + df_prec_dev['CapType']
  return df_prec_dev

# function to arrange stock features
def arrange_features(df_stocks, common_cols, diff_cols):
  df_stocks_common = df_stocks[common_cols].drop_duplicates()
  df_stocks_diff = df_stocks[diff_cols]
  df_stocks_diff['Investment'] = df_stocks_diff['AvgCost'] * df_stocks_diff['Shares']
  df_stocks_diff = df_stocks_diff.groupby(['Symbol'])[['Shares', 'Investment']].aggregate(['sum']).reset_index()
  df_stocks_diff.columns = ['Symbol', 'Shares', 'Investment']
  df_stocks_diff['AvgCost'] = round(df_stocks_diff['Investment']/df_stocks_diff['Shares'],2)
  df_stocks = pd.merge(df_stocks_diff, df_stocks_common, on='Symbol')
  return df_stocks

# plot fact distribution across dimension
def plot_pie_chart(df, dimension, fact):
  # grouping the data by category and calculating the sum of fact for each type
  grouped_data = df.groupby(dimension)[fact].sum()

  # sorting the grouped data in descending order
  grouped_data = grouped_data.sort_values(ascending=False)

  # creating a pie chart
  grouped_data.plot.pie(autopct='%1.1f%%', startangle=90, figsize=(6, 6))

  # adding a title and displaying the plot
  plt.title(f'{dimension} {fact} Distribution')
  plt.ylabel('')  # To hide the y-label
  plt.show()

In [7]:
# function to get portfolio features

def get_portfolio_features(df_common_features):

  print_date_time()
  print('-------------------')

  #df_common_features["Target"] = df_common_features["Target"].fillna(df_common_features["Max"])
  df_common_features['NTT'] = np.where(df_common_features['Strategy']== 'NTT', df_common_features["Target"], df_common_features['Max'])
  df_common_features['LTT'] = np.where(df_common_features['Strategy']== 'BTT', df_common_features["Target"], df_common_features['Max'])
  df_common_features['BOL'] = df_common_features['Min']

  tmp_df = df_common_features[df_common_features['Symbol'].isin(mypf_df[mypf_df['InPortfolio'] != 'NA'].Symbol.values)]
  print('qualified stocks: '+str(len(tmp_df['Symbol'].unique())))
  tmp_df1 = tmp_df[tmp_df['LatestQtr'] == 1]
  print('with latest results: '+str(len(tmp_df1['Symbol'].unique())))
  tmp_df1 = tmp_df1[tmp_df1['StarStock'] == 1]
  print('still star stocks: '+str(len(tmp_df1['Symbol'].unique())))
  tmp_df['Investment'] = tmp_df['AvgCost'] * tmp_df['Shares']
  tmp_df['Current'] = round(tmp_df['Close'] * tmp_df['Shares'],0)
  tmp_df['Previous'] = tmp_df['Prev_Close'] * tmp_df['Shares']
  tmp_df['EstimatedST'] = tmp_df['NTT'] * tmp_df['Shares']
  tmp_df['EstimatedLT'] = tmp_df['LTT'] * tmp_df['Shares']
  tmp_df['Current P/L'] = round((tmp_df['Current'] - tmp_df['Investment']),0)
  tmp_df['Today P/L%'] = round((tmp_df['Current'] - tmp_df['Previous'])*100/tmp_df['Previous'],2)
  tmp_df['Current P/L%'] = round((tmp_df['Current'] - tmp_df['Investment'])*100/tmp_df['Investment'],2)
  tmp_df['EstimatedST P/L%'] = round((tmp_df['EstimatedST'] - tmp_df['Investment'])*100/tmp_df['Investment'],2)
  tmp_df['EstimatedLT P/L%'] = round((tmp_df['EstimatedLT'] - tmp_df['Investment'])*100/tmp_df['Investment'],2)
  tmp_df['NTT%'] = round((tmp_df['NTT'] - tmp_df['Close'])*100/tmp_df['Close'],2)
  tmp_df['LTT%'] = round((tmp_df['LTT'] - tmp_df['Close'])*100/tmp_df['Close'],2)
  tmp_df['Gained%'] = round((tmp_df['Close'] - tmp_df['BOL'])*100/tmp_df['BOL'],2)
  investment = round(sum(tmp_df['AvgCost']*tmp_df['Shares']),0)
  current = round(sum(tmp_df['Close']*tmp_df['Shares']),0)
  tmp_df['InitAlloc%'] = round(tmp_df['Investment']*100/investment,2)
  tmp_df['CurrAlloc%'] = round(tmp_df['Current']*100/current,2)
  tmp_df['FTT'] = tmp_df['LTT']
  tmp_df.loc[tmp_df['Strategy'] == 'NTT', 'FTT'] = tmp_df['NTT']
  tmp_df['FTT%'] = tmp_df['LTT%']
  tmp_df.loc[tmp_df['Strategy'] == 'NTT', 'FTT%'] = tmp_df['NTT%']
  tmp_df['FTT Amt'] = round(tmp_df['FTT%'] * tmp_df['Current']/100,0)
  tmp_df['OTT%'] = round((tmp_df['FTT'] - tmp_df['AvgCost'])*100/tmp_df['AvgCost'],2)
  tmp_df['RRR Ind'] = round(tmp_df['Current P/L']/tmp_df['FTT Amt'],2)
  tmp_df['Risk Ind'] = round(tmp_df['Current P/L%']*tmp_df['CurrAlloc%'],0)

  return tmp_df

# function to print portfolio features
def print_portfolio_stats(df_portfolio_features, myinvmt_df):
  from pyxirr import xirr

  total_booked_amt, reserve_amt, cy_booked_amt, py_booked_amt = get_amt()

  dates = myinvmt_df['Date'].values
  dates = np.append(dates, datetime.date.today().strftime('%d-%b-%y'))
  investment = myinvmt_df['Investment'].values
  dates= pd.to_datetime(dates)

  current = round(sum(df_portfolio_features['Close']*df_portfolio_features['Shares']),0) + reserve_amt
  investment_xirr = np.append(investment, current)
  cagr = round(xirr(pd.DataFrame({"dates": dates, "amounts": investment_xirr}))*100,2)

  investment = -sum(investment)
  invested = round(sum(df_portfolio_features['AvgCost']*df_portfolio_features['Shares']),0) + reserve_amt
  previous = round(sum(df_portfolio_features['Prev_Close']*df_portfolio_features['Shares']),0) + reserve_amt
  cy_invested = investment + py_booked_amt

  today_pnl_amount = current-previous
  today_pnl_percentage = round((current-previous)*100/previous,2)

  curr_pnl_amount = current-invested
  curr_pnl_percentage = round((curr_pnl_amount)*100/(cy_invested),2)

  cy_pnl_amount = cy_booked_amt + curr_pnl_amount
  cy_pnl_percentage = round((cy_pnl_amount)*100/cy_invested,2)

  overall_pnl_amount = total_booked_amt + curr_pnl_amount
  overall_pnl_percentage = round((overall_pnl_amount)*100/investment,2)

  estimate_st = round(sum(df_portfolio_features['FTT']*df_portfolio_features['Shares']),0)  + reserve_amt
  est_st_pnl_amount = estimate_st-current
  est_st_pnl_percentage = round((est_st_pnl_amount)*100/current,2)

  estimate_lt = round(sum(df_portfolio_features['LTT']*df_portfolio_features['Shares']),0)  + reserve_amt
  est_lt_pnl_amount = estimate_lt-current
  est_lt_pnl_percentage = round((est_lt_pnl_amount)*100/current,2)

  total_profit = round(sum(df_portfolio_features[df_portfolio_features['Current P/L%'] > 0]['Current']) - sum(df_portfolio_features[df_portfolio_features['Current P/L%'] > 0]['Investment']),0)
  total_loss = round(sum(df_portfolio_features[df_portfolio_features['Current P/L%'] < 0]['Current']) - sum(df_portfolio_features[df_portfolio_features['Current P/L%'] < 0]['Investment']),0)

  cy_booked_percentage = round((cy_booked_amt)*100/current,2)
  py_booked_percentage = round((py_booked_amt)*100/investment,2)
  total_booked_percentage = round((total_booked_amt)*100/investment,2)

  print('-------------------')
  print('Initial Investment: ', format_amt(investment))
  print('CY Investment: ', format_amt(cy_invested))
  print('Reserve: ', format_amt(reserve_amt))
  print('Current: ',  format_amt(current))
  print('-------------------')
  print('Today PnL: '+ '{} ({}%)'.format(format_amt(today_pnl_amount), today_pnl_percentage))
  print('Current PnL: '+ '{} ({}%)'.format(format_amt(curr_pnl_amount), curr_pnl_percentage))
  print('CY Booked + Current PnL: '+ '{} ({}%)'.format(format_amt(cy_pnl_amount), cy_pnl_percentage))
  print('-------------------')
  print('Total profit: ', format_amt(total_profit))
  print('Total loss: ', format_amt(total_loss))
  print('-------------------')
  print('Total Booked + Current PnL: '+ '{} ({}%)'.format(format_amt(overall_pnl_amount), overall_pnl_percentage))
  print('Total Booked PnL: '+ '{} ({}%)'.format(format_amt(total_booked_amt), total_booked_percentage))
  print('Curr Year Booked PnL: '+ '{} ({}%)'.format(format_amt(cy_booked_amt), cy_booked_percentage))
  print('Prev Year Booked PnL: '+ '{} ({}%)'.format(format_amt(py_booked_amt), py_booked_percentage))
  print('===================')
  print('Est FTT: ',  format_amt(estimate_st))
  print('Est FTT PnL: '+ '{} ({}%)'.format(format_amt(est_st_pnl_amount), est_st_pnl_percentage))

  print('===================')
  print('Deployed: ', format_amt(investment))

  print('Current: ', format_amt(current))

  print('CAGR/XIRR %: '+'{}%'.format(cagr))

In [8]:
# get start and end date
start_date, end_date = get_start_end_date()

# get portfolio and prospects data
mypfs_df = get_mypfs_df()
mypps_df = get_mypps_df()
myinvmt_df = get_myinvmt_df()

# merge above datasets
mypf_df = pd.merge(mypfs_df, mypps_df, on="Symbol")

# seggregate dm and sv portfolio
dm_pf = mypf_df[mypf_df['InPortfolio'] == 'DM']
sv_pf = mypf_df[mypf_df['InPortfolio'] == 'SV']

# build portfolio stock dataframe
dm_stocks = get_stock_ids(dm_pf)
sv_stocks = get_stock_ids(sv_pf)
df_stocks = pd.concat([dm_pf,sv_pf], ignore_index = True)

# arrange common and diff stock features
common_cols = ['Symbol', 'Target', 'Criteria', 'Strategy', 'CumlRnk', 'LatestQtr', 'StarStock', 'Conviction', 'Category', 'InFolio', 'XIRR', 'MBQ']
diff_cols = ['Symbol', 'AvgCost', 'Shares']
df_stocks = arrange_features(df_stocks, common_cols, diff_cols)

# get common features
stock_ids = df_stocks['Symbol'].values
df_common_features = get_common_features(stock_ids, df_stocks)

df_common_features.reset_index(drop=True, inplace=True)
df_common_features.drop(['Date'], axis=1, inplace=True)
# get and print portfolio features
df_portfolio_features = get_portfolio_features(df_common_features)

print_portfolio_stats(df_portfolio_features, myinvmt_df)

df = df_portfolio_features
#plot_pie_chart(df, 'CapType', 'Current')
list_ox40n = list(df[df['MBQ'].str.contains('OX40N', na=False)]['Symbol'].values)

Run date time (IST): 2026-05-29 11:43:25
-------------------
qualified stocks: 92
with latest results: 31
still star stocks: 20
-------------------
Initial Investment:  1.40 C
CY Investment:  1.82 C
Reserve:  1.49 K
Current:  1.51 C
-------------------
Today PnL: -98.00 (-0.0%)
Current PnL: -31.91 L (-17.5%)
CY Booked + Current PnL: -29.83 L (-16.36%)
-------------------
Total profit:  2.74 L
Total loss:  -34.65 L
-------------------
Total Booked + Current PnL: 13.04 L (9.34%)
Total Booked PnL: 44.95 L (32.22%)
Curr Year Booked PnL: 2.08 L (1.38%)
Prev Year Booked PnL: 42.87 L (30.73%)
===================
Est FTT:  2.55 C
Est FTT PnL: 1.04 C (68.79%)
===================
Deployed:  1.40 C
Current:  1.51 C
CAGR/XIRR %: 3.89%

In [9]:
# top 5 near their targets
cols = ['Symbol', 'Today P/L%', 'Current P/L%', 'FTT%', 'OTT%', 'FTT Amt', 'Current P/L', 'Current', 'FTT', 'Dev%_PE', 'RSI_14','Conviction', 'Spread%',  'CumlRnk', 'RRR Ind', 'CurrAlloc%', 'Gained%', 'Criteria', 'Strategy', 'Category']
df_tmp = df_portfolio_features[~df_portfolio_features['Symbol'].isin(['ENRIN','BLUSPRING','DIGITIDE'])]
df_tmp = df_tmp.sort_values(by = 'FTT Amt', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
59,PIDILITIND,-0.66,4.24,13.55,18.37,19932.0,5990.0,147100.0,1670.26,-26.97,59.0,X-LC,5.00,5.0,0.30,0.97,15.50,X40,ATH,CHEMICALS
51,KOTAKBANK,0.64,4.53,15.86,21.11,22956.0,6272.0,144744.0,453.24,-10.27,58.0,X-LC,7.39,12.0,0.27,0.96,10.70,X40,ATH,BANKS
55,MASFIN,0.60,-2.85,25.13,21.57,23921.0,-2790.0,95190.0,397.04,-16.44,49.0,H-SC,4.02,167.0,-0.12,0.63,13.46,XR,ATH,FINANCE
83,TTKPRESTIG,1.14,-30.17,43.34,0.09,30500.0,-30404.0,70373.0,770.00,63.29,57.0,M-SC,15.62,250.0,-1.00,0.47,25.31,OX40N,NTT,DURABLES
17,CIPLA,-0.35,14.42,17.71,34.69,31037.0,22088.0,175249.0,1663.60,-11.50,63.0,X-LC,9.46,18.0,0.71,1.16,18.53,X40N,ATH,PHARMA

In [10]:
# top 5 today
df_tmp = df_portfolio_features.sort_values(by = 'Today P/L%', ascending=False)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
18,COFFEEDAY,19.97,-41.19,130.02,35.27,86825.0,-46771.0,66778.0,80.0,-55.73,83.0,L-SC,25.01,266.0,-0.54,0.44,64.68,XR,NTT,HOTELS
64,RELAXO,16.84,-54.30,233.29,52.31,154755.0,-78824.0,66336.0,1176.0,-51.31,78.0,X-SC,24.30,92.0,-0.51,0.44,48.32,X40N,NTT,FOOTWEAR
45,INFY,3.90,-17.96,63.64,34.24,163355.0,-56202.0,256686.0,1972.0,-35.41,54.0,X-LC,18.71,3.0,-0.34,1.70,10.05,X40,NTT,IT
9,BANDHANBNK,2.16,1.15,90.22,92.42,254217.0,3216.0,281775.0,400.0,141.38,69.0,H-SC,21.77,174.0,0.01,1.86,55.22,XY24,NTT,BANKS
72,SIS,1.91,-7.57,31.20,21.26,32019.0,-8407.0,102625.0,528.0,2443.01,65.0,H-SC,17.61,168.0,-0.26,0.68,52.59,OX40N,NTT,MISC

In [11]:
# bottom 5 today
df_tmp = df_portfolio_features.sort_values(by = 'Today P/L%', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
58,PGHH,-3.91,-27.16,81.24,32.01,126344.0,-58000.0,155520.0,17616.87,-50.75,45.0,X-MC,17.71,57.0,-0.46,1.03,6.37,X40,ATH,FMCG
10,BATAINDIA,-3.30,-56.80,212.95,35.20,118377.0,-73081.0,55589.0,2096.00,-27.08,35.0,X-SC,25.18,91.0,-0.62,0.37,10.25,X40,NTT,FOOTWEAR
11,BERGEPAINT,-3.04,-5.84,33.09,25.32,80310.0,-15048.0,242701.0,680.00,-11.00,56.0,X-MC,8.20,68.0,-0.19,1.60,26.32,XY24,NTT,PAINTS
27,GLAXO,-2.63,-10.25,55.04,39.15,98442.0,-20428.0,178856.0,3466.20,-31.45,31.0,X-MC,6.66,56.0,-0.21,1.18,0.00,X40,ATH,PHARMA
25,FINCABLES,-2.14,45.91,42.50,107.91,91555.0,67780.0,215424.0,1641.55,31.41,67.0,M-SC,27.67,220.0,0.74,1.42,62.07,OX40N,ATH,CABLES

In [12]:
# top 5 to exit based on CumlRnk
df_tmp = df_portfolio_features[~df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])]
df_tmp = df_tmp[(df_tmp['Current P/L%'] > -1) & (df_tmp['Current P/L%'] < 1)].sort_values(by = 'CumlRnk', ascending=False)
df_tmp[cols].head()

Empty DataFrame
Columns: [Symbol, Today P/L%, Current P/L%, FTT%, OTT%, FTT Amt, Current P/L, Current, FTT, Dev%_PE, RSI_14, Conviction, Spread%, CumlRnk, RRR Ind, CurrAlloc%, Gained%, Criteria, Strategy, Category]
Index: []

In [13]:
# OX40N stocks to exit
df_tmp = df_portfolio_features[(df_portfolio_features['Symbol'].isin(list_ox40n))].sort_values(by = 'Current P/L%', ascending=False)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
25,FINCABLES,-2.14,45.91,42.50,107.91,91555.0,67780.0,215424.0,1641.55,31.41,67.0,M-SC,27.67,220.0,0.74,1.42,62.07,OX40N,ATH,CABLES
72,SIS,1.91,-7.57,31.20,21.26,32019.0,-8407.0,102625.0,528.00,2443.01,65.0,H-SC,17.61,168.0,-0.26,0.68,52.59,OX40N,NTT,MISC
16,CERA,-0.48,-24.56,64.23,23.89,85232.0,-43205.0,132698.0,9475.00,-27.21,59.0,H-SC,7.17,153.0,-0.51,0.88,27.52,OX40N,NTT,CERAMICS
50,KANSAINER,-0.07,-27.18,55.83,13.47,109629.0,-73305.0,196362.0,340.00,-37.50,62.0,H-SC,12.29,162.0,-0.67,1.30,37.16,XY24,NTT,PAINTS
43,INDIGOPNTS,-1.30,-29.94,42.76,0.02,52296.0,-52258.0,122301.0,1408.00,86.38,62.0,M-SC,17.40,222.0,-1.00,0.81,38.76,OX40N,NTT,PAINTS

In [14]:
# top 5 to book for rotation
df_tmp = df_portfolio_features[(df_portfolio_features['Current P/L%'] > 20) ].sort_values(by = 'CumlRnk', ascending=False)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
25,FINCABLES,-2.14,45.91,42.50,107.91,91555.0,67780.0,215424.0,1641.55,31.41,67.0,M-SC,27.67,220.0,0.74,1.42,62.07,OX40N,ATH,CABLES
68,SATIN,-0.26,22.61,23.83,51.83,80727.0,62480.0,338764.0,274.00,10.38,67.0,H-SC,36.25,159.0,0.77,2.24,65.03,XY24,NTT,FINANCE

In [15]:
# top 5 to monitor for exit
df_tmp = df_portfolio_features[~df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])]
df_tmp = df_tmp[(df_tmp['Current P/L%'] > 0) ].sort_values(by = 'Dev%_PE', ascending=False)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
9,BANDHANBNK,2.16,1.15,90.22,92.42,254217.0,3216.0,281775.0,400.00,141.38,69.0,H-SC,21.77,174.0,0.01,1.86,55.22,XY24,NTT,BANKS
74,STARHEALTH,-0.27,1.25,45.44,47.26,129344.0,3525.0,284648.0,761.00,59.71,60.0,H-SC,9.85,173.0,0.03,1.88,24.97,XY24,NTT,INSURANCE
25,FINCABLES,-2.14,45.91,42.50,107.91,91555.0,67780.0,215424.0,1641.55,31.41,67.0,M-SC,27.67,220.0,0.74,1.42,62.07,OX40N,ATH,CABLES
68,SATIN,-0.26,22.61,23.83,51.83,80727.0,62480.0,338764.0,274.00,10.38,67.0,H-SC,36.25,159.0,0.77,2.24,65.03,XY24,NTT,FINANCE
91,ZYDUSLIFE,1.25,15.93,16.99,35.63,41278.0,33382.0,242956.0,1286.17,0.90,77.0,H-MC,5.55,120.0,0.81,1.61,27.74,AR,ATH,PHARMA

In [16]:
# top 5 to book for rotation from weak conviction
df_tmp = df_portfolio_features[~df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])]
df_tmp = df_tmp[~df_tmp['Criteria'].isin(['XY25','XY24','X40', 'X40N'])].sort_values(by = 'RRR Ind', ascending=False)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
91,ZYDUSLIFE,1.25,15.93,16.99,35.63,41278.0,33382.0,242956.0,1286.17,0.90,77.0,H-MC,5.55,120.0,0.81,1.61,27.74,AR,ATH,PHARMA
25,FINCABLES,-2.14,45.91,42.50,107.91,91555.0,67780.0,215424.0,1641.55,31.41,67.0,M-SC,27.67,220.0,0.74,1.42,62.07,OX40N,ATH,CABLES
73,SONACOMS,-0.70,6.29,30.86,39.09,33181.0,6361.0,107520.0,804.02,-15.74,63.0,M-MC,18.76,193.0,0.19,0.71,52.10,AR,ATH,AUTO
42,INDIAMART,-0.50,-13.63,139.33,106.72,148428.0,-16806.0,106530.0,4810.62,-61.13,43.0,H-SC,10.80,140.0,-0.11,0.70,3.13,AR,ATH,MISC
55,MASFIN,0.60,-2.85,25.13,21.57,23921.0,-2790.0,95190.0,397.04,-16.44,49.0,H-SC,4.02,167.0,-0.12,0.63,13.46,XR,ATH,FINANCE

In [17]:
# top 5 to accumulate based on lowest RSI_14
df_tmp = df_portfolio_features[df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])].sort_values(by = 'RSI_14', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
27,GLAXO,-2.63,-10.25,55.04,39.15,98442.0,-20428.0,178856.0,3466.20,-31.45,31.0,X-MC,6.66,56.0,-0.21,1.18,0.00,X40,ATH,PHARMA
10,BATAINDIA,-3.30,-56.80,212.95,35.20,118377.0,-73081.0,55589.0,2096.00,-27.08,35.0,X-SC,25.18,91.0,-0.62,0.37,10.25,X40,NTT,FOOTWEAR
23,DMART,-0.11,-0.96,30.86,29.60,76286.0,-2400.0,247200.0,5391.45,-16.48,36.0,X-LC,3.13,14.0,-0.03,1.63,12.99,X40N,ATH,FMCG
47,ITC,-1.04,-23.90,56.46,19.06,146149.0,-81312.0,258854.0,452.00,-58.35,37.0,X-LC,14.63,1.0,-0.56,1.71,3.15,X40,NTT,FMCG
88,VOLTAS,-0.12,-1.41,47.27,45.20,89362.0,-2697.0,189045.0,1856.00,12.87,40.0,X-MC,5.57,79.0,-0.03,1.25,3.29,XY25,NTT,AC

In [18]:
# top 5 to accumulate based on Spread and CumlRnk
df_tmp = df_portfolio_features[df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])]
df_tmp = df_tmp[(df_tmp['CumlRnk'] < 100)].sort_values(by = 'Spread%', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
23,DMART,-0.11,-0.96,30.86,29.60,76286.0,-2400.0,247200.0,5391.45,-16.48,36.0,X-LC,3.13,14.0,-0.03,1.63,12.99,X40N,ATH,FMCG
65,RELIANCE,-0.85,-14.05,45.78,25.30,79076.0,-28232.0,172731.0,1952.00,-16.19,42.0,X-LC,3.96,21.0,-0.36,1.14,2.64,XY25,BTT,REFINERIES
84,UNITDSPR,-1.34,-5.60,27.94,20.77,61753.0,-13124.0,221020.0,1644.00,-16.33,47.0,X-MC,4.30,64.0,-0.21,1.46,5.43,X40N,NTT,BREWERIES
49,JSWINFRA,0.18,-4.66,22.12,16.43,46770.0,-10336.0,211438.0,342.00,-18.29,58.0,X-MC,4.97,61.0,-0.22,1.40,19.52,X40N,NTT,REALTY
39,ICICIGI,-0.67,-2.63,22.56,19.34,43958.0,-5260.0,194849.0,2252.93,-18.12,54.0,X-MC,4.97,66.0,-0.12,1.29,8.83,X40,ATH,INSURANCE

In [19]:
# top 5 to accumulate based on lowest Gained%
df_tmp = df_portfolio_features[df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])].sort_values(by = 'Gained%', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
27,GLAXO,-2.63,-10.25,55.04,39.15,98442.0,-20428.0,178856.0,3466.20,-31.45,31.0,X-MC,6.66,56.0,-0.21,1.18,0.00,X40,ATH,PHARMA
40,ICICIPRULI,-1.62,-14.87,53.56,30.73,89826.0,-29294.0,167711.0,790.00,-37.77,41.0,X-MC,11.77,78.0,-0.33,1.11,2.20,X40,ATH,INSURANCE
32,HAVELLS,-0.58,-22.91,70.48,31.42,178202.0,-75151.0,252840.0,2052.62,-27.51,44.0,X-MC,12.69,63.0,-0.42,1.67,2.49,X40,ATH,ELECTRICAL
65,RELIANCE,-0.85,-14.05,45.78,25.30,79076.0,-28232.0,172731.0,1952.00,-16.19,42.0,X-LC,3.96,21.0,-0.36,1.14,2.64,XY25,BTT,REFINERIES
47,ITC,-1.04,-23.90,56.46,19.06,146149.0,-81312.0,258854.0,452.00,-58.35,37.0,X-LC,14.63,1.0,-0.56,1.71,3.15,X40,NTT,FMCG

In [20]:
# top 5 to accumulate based on lowest CurrAlloc%
df_tmp = df_portfolio_features[df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])].sort_values(by = 'CurrAlloc%', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
10,BATAINDIA,-3.30,-56.80,212.95,35.20,118377.0,-73081.0,55589.0,2096.00,-27.08,35.0,X-SC,25.18,91.0,-0.62,0.37,10.25,X40,NTT,FOOTWEAR
64,RELAXO,16.84,-54.30,233.29,52.31,154755.0,-78824.0,66336.0,1176.00,-51.31,78.0,X-SC,24.30,92.0,-0.51,0.44,48.32,X40N,NTT,FOOTWEAR
60,QUESS,-1.06,-13.50,101.04,73.90,93335.0,-14419.0,92374.0,424.00,-53.72,57.0,X-SC,9.33,80.0,-0.15,0.61,25.93,XY24,NTT,MISC
28,GODREJCP,-0.60,-7.10,41.51,31.47,57312.0,-10547.0,138067.0,1469.04,-2.31,48.0,X-LC,8.87,32.0,-0.18,0.91,5.94,X40N,ATH,FMCG
53,M&M,-0.82,0.46,22.81,23.38,31780.0,643.0,139324.0,3802.40,-14.78,46.0,X-LC,8.80,25.0,0.02,0.92,5.63,X40N,ATH,AUTO

In [21]:
# top 5 to accumulate based on CumlRnk
df_tmp = df_portfolio_features.sort_values(by = 'CumlRnk', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
47,ITC,-1.04,-23.90,56.46,19.06,146149.0,-81312.0,258854.0,452.00,-58.35,37.0,X-LC,14.63,1.0,-0.56,1.71,3.15,X40,NTT,FMCG
79,TCS,0.95,-32.31,84.48,24.88,264931.0,-149671.0,313602.0,4253.91,-42.64,44.0,X-LC,17.69,2.0,-0.56,2.07,4.06,X40,ATH,IT
45,INFY,3.90,-17.96,63.64,34.24,163355.0,-56202.0,256686.0,1972.00,-35.41,54.0,X-LC,18.71,3.0,-0.34,1.70,10.05,X40,NTT,IT
81,TMPV,-0.19,-8.90,49.93,36.58,161854.0,-31679.0,324162.0,600.00,-81.44,75.0,X-LC,21.30,4.0,-0.20,2.14,35.11,XY24,NTT,AUTO
59,PIDILITIND,-0.66,4.24,13.55,18.37,19932.0,5990.0,147100.0,1670.26,-26.97,59.0,X-LC,5.00,5.0,0.30,0.97,15.50,X40,ATH,CHEMICALS

In [22]:
# top 5 for average up
df_tmp = df_portfolio_features[(df_portfolio_features['Dev%_200'] > 5)].sort_values(by = 'CurrAlloc%', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
44,INDUSINDBK,-0.98,-31.85,94.98,32.89,49978.0,-24586.0,52620.0,1800.00,-347.90,58.0,L-MC,8.77,258.0,-0.49,0.35,29.52,XR,NTT,BANKS
72,SIS,1.91,-7.57,31.20,21.26,32019.0,-8407.0,102625.0,528.00,2443.01,65.0,H-SC,17.61,168.0,-0.26,0.68,52.59,OX40N,NTT,MISC
86,VALIANTORG,1.41,-36.30,173.41,74.15,180711.0,-59395.0,104210.0,838.00,-287.15,61.0,H-SC,8.66,145.0,-0.33,0.69,55.08,XR,NTT,CHEMICALS
73,SONACOMS,-0.70,6.29,30.86,39.09,33181.0,6361.0,107520.0,804.02,-15.74,63.0,M-MC,18.76,193.0,0.19,0.71,52.10,AR,ATH,AUTO
75,SURYODAY,0.16,-5.41,30.07,23.03,50936.0,-9680.0,169391.0,216.00,84.21,61.0,H-SC,18.52,166.0,-0.19,1.12,42.62,XR,NTT,BANKS

In [23]:
# top 5 RSP
df_tmp = df_portfolio_features.sort_values(by = 'RSP', ascending=False)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
18,COFFEEDAY,19.97,-41.19,130.02,35.27,86825.0,-46771.0,66778.0,80.00,-55.73,83.0,L-SC,25.01,266.0,-0.54,0.44,64.68,XR,NTT,HOTELS
69,SFL,1.10,-37.72,103.33,26.63,168739.0,-98917.0,163301.0,1287.00,23.68,67.0,M-SC,10.02,242.0,-0.59,1.08,36.10,XY24,NTT,MISC
68,SATIN,-0.26,22.61,23.83,51.83,80727.0,62480.0,338764.0,274.00,10.38,67.0,H-SC,36.25,159.0,0.77,2.24,65.03,XY24,NTT,FINANCE
91,ZYDUSLIFE,1.25,15.93,16.99,35.63,41278.0,33382.0,242956.0,1286.17,0.90,77.0,H-MC,5.55,120.0,0.81,1.61,27.74,AR,ATH,PHARMA
64,RELAXO,16.84,-54.30,233.29,52.31,154755.0,-78824.0,66336.0,1176.00,-51.31,78.0,X-SC,24.30,92.0,-0.51,0.44,48.32,X40N,NTT,FOOTWEAR

In [24]:
# Top N allocation
df_tmp = df_portfolio_features.sort_values(by = 'CurrAlloc%', ascending=False)
top_n_values = [10, 25, 50]

sum_df = pd.DataFrame({
    'Top_N': top_n_values,
    'Sum_Alloc%': [df_tmp['CurrAlloc%'].head(n).sum() for n in top_n_values]
})

sum_df

   Top_N  Sum_Alloc%
0     10       19.53
1     25       42.71
2     50       72.78

In [25]:
# market-cap-wise allocation
df_tmp = df_portfolio_features[cols]
df_tmp.groupby(df_tmp['Conviction'].str[-2:])['CurrAlloc%'].sum().sort_values(ascending=False)

Conviction
SC    43.01
LC    31.46
MC    25.57
Name: CurrAlloc%, dtype: float64

In [26]:
# criteria-wise allocation
df_portfolio_features.groupby('Criteria')['CurrAlloc%'].sum().sort_values(ascending=False)

Criteria
XY24     27.54
X40      25.17
X40N     17.04
XR        9.04
OX40N     7.06
AR        6.92
XY25      6.45
SR        0.82
Name: CurrAlloc%, dtype: float64

In [27]:
# conviction-wise allocation
df_portfolio_features.groupby('Conviction')['CurrAlloc%'].sum().sort_values(ascending=False)

Conviction
X-LC    29.23
H-SC    22.41
X-MC    20.53
M-SC    10.05
X-SC     9.90
H-MC     2.74
M-MC     1.95
H-LC     1.29
M-LC     0.94
L-SC     0.65
L-MC     0.35
Name: CurrAlloc%, dtype: float64

In [28]:
# sector-wise stats
df_tmp = df_portfolio_features.groupby('Category')[['CurrAlloc%', 'Current', 'Current P/L', 'FTT Amt']].sum().sort_values(by=['Current', 'Current P/L'], ascending=False)
df_tmp['Current P/L%'] = round(df_tmp['Current P/L'] * 100 / df_tmp['Current'], 2)
df_tmp['FTT%'] = round(df_tmp['FTT Amt'] * 100 / df_tmp['Current'], 2)
cols = ['CurrAlloc%', 'Current P/L%', 'FTT%']
df_tmp[cols].sort_values(by=['CurrAlloc%'], ascending=False)

               CurrAlloc%  Current P/L%    FTT%
Category
FMCG                15.01        -16.56   57.64
FINANCE             10.73        -13.74   63.20
IT                  10.32        -44.17  116.25
MISC                 6.98        -27.09   82.29
AUTO                 6.85         -5.56   45.14
BANKS                5.70         -5.44   54.19
PAINTS               5.51        -18.24   38.78
INSURANCE            5.27         -3.93   39.31
PHARMA               5.04          2.79   28.45
ELECTRICAL           4.16        -12.53   52.24
CHEMICALS            2.14        -25.33  100.02
HEALTHCARE           2.00        -18.44   49.35
APPARELS             1.79          0.74   32.60
AC                   1.77        -19.54   51.96
FOOTWEAR             1.75        -67.16  134.19
TRAVEL               1.61        -84.35  176.66
DURABLES             1.59        -61.91  101.30
BREWERIES            1.46         -5.94   27.94
CABLES               1.42         31.46   42.50
REALTY               1.40         -4.89   22.12
CERAMICS             1.35        -50.49   96.22
ENGINEERING          1.28        -24.89   82.01
REFINERIES           1.14        -16.34   45.78
CEMENT               1.13        -57.52  175.36
JEWELLERY            1.06        -99.57  168.90
ENTERTAINMENT        0.74        -74.77  179.00
HOTELS               0.44        -70.04  130.02
TEXTILES             0.40        -51.83   95.12

In [29]:
# money to be made criteria-wise
df_portfolio_features.groupby('Criteria')['FTT Amt'].agg(['sum', 'count']).sort_values(by='sum', ascending=False)

                sum  count
Criteria
XY24      3431644.0     21
X40       1886120.0     19
XR        1315791.0     13
X40N      1147120.0     13
AR        1138229.0      9
OX40N      725740.0     10
XY25       466021.0      5
SR         294782.0      2

In [30]:
# money to be made conviction-wise
df_portfolio_features.groupby('Conviction')['FTT Amt'].agg(['sum', 'count']).sort_values(by='sum', ascending=False)

                  sum  count
Conviction
H-SC        3397011.0     24
X-LC        1867114.0     21
X-MC        1626345.0     15
M-SC        1400408.0     14
X-SC        1308193.0      9
H-MC         284438.0      2
L-SC         191765.0      2
M-LC         149532.0      1
M-MC          91555.0      2
L-MC          49978.0      1
H-LC          39108.0      1

In [31]:
# money to be made criteria and conviction-wise
df_portfolio_features.groupby(['Conviction', 'Criteria'])['FTT Amt'].agg(['sum', 'count']).sort_values(by='sum', ascending=False)

                           sum  count
Conviction Criteria
H-SC       XY24      1039856.0      6
X-LC       X40       1011977.0     10
H-SC       AR         949318.0      5
M-SC       XY24       831937.0      6
H-SC       XR         795373.0      7
X-SC       XY24       790445.0      4
X-MC       X40        670991.0      7
           X40N       480703.0      4
X-LC       X40N       351821.0      6
H-SC       OX40N      317682.0      4
X-SC       X40N       314596.0      3
X-LC       XY24       305651.0      2
M-SC       OX40N      303118.0      5
H-SC       SR         294782.0      2
X-MC       XY25       254056.0      2
H-MC       XY24       243160.0      1
X-MC       XY24       220595.0      2
X-SC       X40        203152.0      2
M-SC       XR         190009.0      2
X-LC       XY25       153591.0      2
M-LC       XR         149532.0      1
L-SC       OX40N      104940.0      1
           XR          86825.0      1
M-SC       AR          75344.0      1
M-MC       XY25        58374.0      1
L-MC       XR          49978.0      1
X-LC       XR          44074.0      1
H-MC       AR          41278.0      1
H-LC       AR          39108.0      1
M-MC       AR          33181.0      1

In [32]:
# notebook execution time

end_time = time.time()
execution_time = round(end_time - start_time, 0)
print(f"Notebook execution time: {execution_time} seconds")

Notebook execution time: 34.0 seconds