<a href="https://colab.research.google.com/github/ankit-rathi/Quantvesting_v2/blob/main/myStocks_Portfolio_Analysis.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
'''
!pip install pandas==2.2.2 -qq
!pip install pyxirr -qq
!pip install ta -qq
!pip install yfinance==0.2.59 -qq
'''

'\n!pip install pandas==2.2.2 -qq\n!pip install pyxirr -qq\n!pip install ta -qq\n!pip install yfinance==0.2.59 -qq\n'

In [2]:
# import libraries

import numpy as np
import pandas as pd
import datetime
import warnings
warnings.filterwarnings('ignore')
import yfinance as yfin
import ta
import matplotlib.pyplot as plt
import requests

In [3]:
# notebook start time
import time
import datetime
import pytz

start_time = time.time()

# function to print date timestamp
def print_date_time():
  tz_NY = pytz.timezone('Asia/Kolkata')
  datetime_NY = datetime.datetime.now(tz_NY)
  print("Run date time (IST):", datetime_NY.strftime("%Y-%m-%d %H:%M:%S"))

In [4]:
# function to get booked and reserved amount
def get_amt():
  # fetch the JSON data from the URL
  url = "https://raw.githubusercontent.com/ankit-rathi/Tradevesting_v1/main/data/myPortfolioAmts.json"
  response = requests.get(url)
  pf_amts = response.json()  # parse the JSON data

  # extract values from the JSON
  py_booked_amt_dm = pf_amts["py_booked_amt_dm"]
  py_booked_amt_sv = pf_amts["py_booked_amt_sv"]
  cy_booked_amt_dm = pf_amts["cy_booked_amt_dm"]
  cy_booked_amt_sv = pf_amts["cy_booked_amt_sv"]
  reserve_amt_dm = pf_amts["reserve_amt_dm"]
  reserve_amt_sv = pf_amts["reserve_amt_sv"]

  # perform calculations
  py_booked_amt = py_booked_amt_dm + py_booked_amt_sv
  cy_booked_amt = cy_booked_amt_dm + cy_booked_amt_sv
  reserve_amt = reserve_amt_dm + reserve_amt_sv
  total_booked_amt = py_booked_amt + cy_booked_amt

  return total_booked_amt, reserve_amt, cy_booked_amt, py_booked_amt

gen_output = 0

In [5]:
# function to format the amount
def format_amt(number):
    abs_number = abs(number)

    if abs_number >= 1_00_00_000:  # Crores
        formatted_amt = f"{number / 1_00_00_000:.2f} C"
    elif abs_number >= 1_00_000:  # Lakhs
        formatted_amt = f"{number / 1_00_000:.2f} L"
    elif abs_number >= 1_000:  # Thousands
        formatted_amt = f"{number / 1_000:.2f} K"
    else:
        formatted_amt = f"{number:.2f}"

    return formatted_amt

# function to set start and end date
def get_start_end_date():
  start_date = (datetime.date.today() + datetime.timedelta(days=-365)).strftime('%Y-%m-%d')
  end_date = (datetime.date.today() + datetime.timedelta(days=1)).strftime('%Y-%m-%d')
  return start_date, end_date

# function to fetch my portfolio csv
def get_mypfs_df():
  mypfs_df = pd.read_csv('https://raw.githubusercontent.com/ankit-rathi/Tradevesting_v1/main/data/myPortfolioStocks.csv')
  return mypfs_df

# function to fetch my prospects csv
def get_mypps_df():
  mypps_df = pd.read_csv('https://raw.githubusercontent.com/ankit-rathi/Tradevesting_v1/main/data/myProspectsScrips.csv')
  return mypps_df

# function to fetch screener data
def get_myscreen_df():
  myscreen_df = pd.read_csv('https://raw.githubusercontent.com/ankit-rathi/Tradevesting_v1/main/data/myScreenerDB.csv')
  return myscreen_df

# function to fetch momentum data
def get_myinvmt_df():
  myinvmt_df = pd.read_csv('https://raw.githubusercontent.com/ankit-rathi/Tradevesting_v1/main/data/myInvestments.csv')
  return myinvmt_df

# function to get the stock ids
def get_stock_ids(df_pf):
  stock_n100 = df_pf['Symbol'].unique()

  exclude = ['CADILAHC','MMTC', 'MASFIN']

  stock_ids = df_pf[~df_pf['Symbol'].isin(exclude) ]['Symbol'].unique()

  #mypf = mypf[mypf.Forecast.notnull()]
  #stock_ids = mypf['Symbol'].unique()

  #stock_ids.sort()
  return stock_ids

# get features from screener data
def get_screener_features():
  myscreen_df = get_myscreen_df()
  cols = ['Symbol', 'EPS', 'MedPE', 'ROCE%', 'ROE%', 'CapType']
  return myscreen_df[cols]

# get relative strength
def get_relative_strength(stock_list):

    # Dictionary to store stock tickers and their corresponding percentage price change
    stock_changes = {}

    # Loop through each stock and fetch its price data
    for stock in stock_list:
        try:
            # Download the stock data for the given date range
            stock_data = yfin.Ticker(stock + '.NS').history(period='1mo', interval='1d')[map(str.title, ['open', 'close', 'low', 'high', 'volume'])]

            # Calculate the percentage change for the stock
            if len(stock_data) > 0:
                start_price = stock_data['Close'].iloc[0]
                end_price = stock_data['Close'].iloc[-1]
                percent_change = round(((end_price - start_price) / start_price) * 100, 2)
                stock_changes[stock] = percent_change
            else:
                stock_changes[stock] = np.nan  # If no data is available, set to NaN

        except Exception as e:
            print(f"Error fetching data for {stock}: {e}")
            stock_changes[stock] = np.nan

    # Create a DataFrame with stock tickers and their percentage changes
    df = pd.DataFrame(list(stock_changes.items()), columns=['Symbol', 'Percent_Change'])

    # Drop any stocks with missing data (NaN values)
    df = df.dropna()

    # Calculate the percentile rank based on percentage change
    df['RSP'] = round(df['Percent_Change'].rank(pct=True) * 100, 2)
    cols = ['Symbol', 'RSP']
    df = df[cols]
    # Sort by percentile rank (optional)
    df = df.sort_values(by='RSP', ascending=False).reset_index(drop=True)

    return df

In [6]:
# function to get stock technicals
def stock_prec_dev(stock_symbol):
    #stock_symbol = 'ULTRACEMCO.NS'
    short_window = 20
    mid_window = 50
    long_window = 200
    moving_avg = 'SMA'

    start = datetime.datetime(*map(int, start_date.split('-')))
    end = datetime.datetime(*map(int, end_date.split('-')))

    stock_df = yfin.Ticker(stock_symbol + '.NS').history(period='max', interval='1d')[map(str.title, ['open', 'close', 'low', 'high', 'volume'])]

    stock_df['Max'] = round(max(stock_df['Close']),2)
    stock_df = stock_df[(stock_df.index <= end_date) & (stock_df.index >= start_date)]
    stock_df['200_SMA'] = round(stock_df['Close'].rolling(window = 200, min_periods = 1).mean(),0)
    stock_df['Dev%_200'] = round((stock_df['Close'] - stock_df['200_SMA'])*100/stock_df['200_SMA'],2)
    stock_df.dropna(axis = 0, inplace = True) # remove any null rows

    stock_df['20_SMA'] = stock_df['Close'].rolling(window=20).mean()
    stock_df['50_SMA'] = stock_df['Close'].rolling(window=50).mean()
    stock_df['Symbol'] = stock_symbol

    stock_df['Close'] = round(stock_df['Close'],2)
    stock_df['Min'] = round(min(stock_df['Close']),2)
    stock_df['RSI_14'] = ta.momentum.RSIIndicator(close=stock_df['Close'], window=14).rsi()
    stock_df['RSI_14'] = round(stock_df['RSI_14'],0)
    stock_df['Prev_Close'] = stock_df['Close'].shift(1)
    stock_df.drop(['Open', 'Low', 'High', 'Volume'], axis=1, inplace=True)
    stock_df = stock_df.tail(1)

    max_SMA = max(stock_df['20_SMA'].item(), stock_df['50_SMA'].item(), stock_df['200_SMA'].item())
    min_SMA = min(stock_df['20_SMA'].item(), stock_df['50_SMA'].item(), stock_df['200_SMA'].item())
    ABS_Spread = max_SMA - min_SMA
    stock_df['Spread%'] = round((ABS_Spread / stock_df['200_SMA'].item()) * 100,2)

    return stock_df

# function to compute stock attributes
def get_common_features(stock_ids, df_mypf):

  df_prec_dev = pd.DataFrame()
  df_tmp = get_screener_features()
  df_rs = get_relative_strength(stock_ids)

  for stock_id in stock_ids:
      tmp = stock_prec_dev(stock_id)
      tmp = tmp.reset_index()
      df_prec_dev = pd.concat([df_prec_dev, tmp], ignore_index = True)
  df_prec_dev = pd.merge(df_prec_dev, df_mypf, on= 'Symbol')
  df_prec_dev = pd.merge(df_prec_dev, df_tmp, on= 'Symbol', how='left')
  df_prec_dev = pd.merge(df_prec_dev, df_rs, on= 'Symbol', how='left')
  #print(df_prec_dev.columns)
  df_prec_dev['Curr_PE'] = round(df_prec_dev['Close']/df_prec_dev['EPS'],1)
  df_prec_dev['Dev%_PE'] = round((df_prec_dev['Curr_PE'] - df_prec_dev['MedPE'])*100/df_prec_dev['MedPE'],2)
  df_prec_dev['Conviction'] = df_prec_dev['Conviction'] + '-' + df_prec_dev['CapType']
  return df_prec_dev

# function to arrange stock features
def arrange_features(df_stocks, common_cols, diff_cols):
  df_stocks_common = df_stocks[common_cols].drop_duplicates()
  df_stocks_diff = df_stocks[diff_cols]
  df_stocks_diff['Investment'] = df_stocks_diff['AvgCost'] * df_stocks_diff['Shares']
  df_stocks_diff = df_stocks_diff.groupby(['Symbol'])[['Shares', 'Investment']].aggregate(['sum']).reset_index()
  df_stocks_diff.columns = ['Symbol', 'Shares', 'Investment']
  df_stocks_diff['AvgCost'] = round(df_stocks_diff['Investment']/df_stocks_diff['Shares'],2)
  df_stocks = pd.merge(df_stocks_diff, df_stocks_common, on='Symbol')
  return df_stocks

# plot fact distribution across dimension
def plot_pie_chart(df, dimension, fact):
  # grouping the data by category and calculating the sum of fact for each type
  grouped_data = df.groupby(dimension)[fact].sum()

  # sorting the grouped data in descending order
  grouped_data = grouped_data.sort_values(ascending=False)

  # creating a pie chart
  grouped_data.plot.pie(autopct='%1.1f%%', startangle=90, figsize=(6, 6))

  # adding a title and displaying the plot
  plt.title(f'{dimension} {fact} Distribution')
  plt.ylabel('')  # To hide the y-label
  plt.show()

In [7]:
# function to get portfolio features

def get_portfolio_features(df_common_features):

  print_date_time()
  print('-------------------')

  #df_common_features["Target"] = df_common_features["Target"].fillna(df_common_features["Max"])
  df_common_features['NTT'] = np.where(df_common_features['Strategy']== 'NTT', df_common_features["Target"], df_common_features['Max'])
  df_common_features['LTT'] = np.where(df_common_features['Strategy']== 'BTT', df_common_features["Target"], df_common_features['Max'])
  df_common_features['BOL'] = df_common_features['Min']

  tmp_df = df_common_features[df_common_features['Symbol'].isin(mypf_df[mypf_df['InPortfolio'] != 'NA'].Symbol.values)]
  print('qualified stocks: '+str(len(tmp_df['Symbol'].unique())))
  tmp_df1 = tmp_df[tmp_df['LatestQtr'] == 1]
  print('with latest results: '+str(len(tmp_df1['Symbol'].unique())))
  tmp_df1 = tmp_df1[tmp_df1['StarStock'] == 1]
  print('still star stocks: '+str(len(tmp_df1['Symbol'].unique())))
  tmp_df['Investment'] = tmp_df['AvgCost'] * tmp_df['Shares']
  tmp_df['Current'] = round(tmp_df['Close'] * tmp_df['Shares'],0)
  tmp_df['Previous'] = tmp_df['Prev_Close'] * tmp_df['Shares']
  tmp_df['EstimatedST'] = tmp_df['NTT'] * tmp_df['Shares']
  tmp_df['EstimatedLT'] = tmp_df['LTT'] * tmp_df['Shares']
  tmp_df['Current P/L'] = round((tmp_df['Current'] - tmp_df['Investment']),0)
  tmp_df['Today P/L%'] = round((tmp_df['Current'] - tmp_df['Previous'])*100/tmp_df['Previous'],2)
  tmp_df['Current P/L%'] = round((tmp_df['Current'] - tmp_df['Investment'])*100/tmp_df['Investment'],2)
  tmp_df['EstimatedST P/L%'] = round((tmp_df['EstimatedST'] - tmp_df['Investment'])*100/tmp_df['Investment'],2)
  tmp_df['EstimatedLT P/L%'] = round((tmp_df['EstimatedLT'] - tmp_df['Investment'])*100/tmp_df['Investment'],2)
  tmp_df['NTT%'] = round((tmp_df['NTT'] - tmp_df['Close'])*100/tmp_df['Close'],2)
  tmp_df['LTT%'] = round((tmp_df['LTT'] - tmp_df['Close'])*100/tmp_df['Close'],2)
  tmp_df['Gained%'] = round((tmp_df['Close'] - tmp_df['BOL'])*100/tmp_df['BOL'],2)
  investment = round(sum(tmp_df['AvgCost']*tmp_df['Shares']),0)
  current = round(sum(tmp_df['Close']*tmp_df['Shares']),0)
  tmp_df['InitAlloc%'] = round(tmp_df['Investment']*100/investment,2)
  tmp_df['CurrAlloc%'] = round(tmp_df['Current']*100/current,2)
  tmp_df['FTT'] = tmp_df['LTT']
  tmp_df.loc[tmp_df['Strategy'] == 'NTT', 'FTT'] = tmp_df['NTT']
  tmp_df['FTT%'] = tmp_df['LTT%']
  tmp_df.loc[tmp_df['Strategy'] == 'NTT', 'FTT%'] = tmp_df['NTT%']
  tmp_df['FTT Amt'] = round(tmp_df['FTT%'] * tmp_df['Current']/100,0)
  tmp_df['OTT%'] = round((tmp_df['FTT'] - tmp_df['AvgCost'])*100/tmp_df['AvgCost'],2)
  tmp_df['RRR Ind'] = round(tmp_df['Current P/L']/tmp_df['FTT Amt'],2)
  tmp_df['Risk Ind'] = round(tmp_df['Current P/L%']*tmp_df['CurrAlloc%'],0)

  return tmp_df

# function to print portfolio features
def print_portfolio_stats(df_portfolio_features, myinvmt_df):
  from pyxirr import xirr

  total_booked_amt, reserve_amt, cy_booked_amt, py_booked_amt = get_amt()

  dates = myinvmt_df['Date'].values
  dates = np.append(dates, datetime.date.today().strftime('%d-%b-%y'))
  investment = myinvmt_df['Investment'].values
  dates= pd.to_datetime(dates)

  current = round(sum(df_portfolio_features['Close']*df_portfolio_features['Shares']),0) + reserve_amt
  investment_xirr = np.append(investment, current)
  cagr = round(xirr(pd.DataFrame({"dates": dates, "amounts": investment_xirr}))*100,2)

  investment = -sum(investment)
  invested = round(sum(df_portfolio_features['AvgCost']*df_portfolio_features['Shares']),0) + reserve_amt
  previous = round(sum(df_portfolio_features['Prev_Close']*df_portfolio_features['Shares']),0) + reserve_amt
  cy_invested = investment + py_booked_amt

  today_pnl_amount = current-previous
  today_pnl_percentage = round((current-previous)*100/previous,2)

  curr_pnl_amount = current-invested
  curr_pnl_percentage = round((curr_pnl_amount)*100/(cy_invested),2)

  cy_pnl_amount = cy_booked_amt + curr_pnl_amount
  cy_pnl_percentage = round((cy_pnl_amount)*100/cy_invested,2)

  overall_pnl_amount = total_booked_amt + curr_pnl_amount
  overall_pnl_percentage = round((overall_pnl_amount)*100/investment,2)

  estimate_st = round(sum(df_portfolio_features['FTT']*df_portfolio_features['Shares']),0)  + reserve_amt
  est_st_pnl_amount = estimate_st-current
  est_st_pnl_percentage = round((est_st_pnl_amount)*100/current,2)

  estimate_lt = round(sum(df_portfolio_features['LTT']*df_portfolio_features['Shares']),0)  + reserve_amt
  est_lt_pnl_amount = estimate_lt-current
  est_lt_pnl_percentage = round((est_lt_pnl_amount)*100/current,2)

  total_profit = round(sum(df_portfolio_features[df_portfolio_features['Current P/L%'] > 0]['Current']) - sum(df_portfolio_features[df_portfolio_features['Current P/L%'] > 0]['Investment']),0)
  total_loss = round(sum(df_portfolio_features[df_portfolio_features['Current P/L%'] < 0]['Current']) - sum(df_portfolio_features[df_portfolio_features['Current P/L%'] < 0]['Investment']),0)

  cy_booked_percentage = round((cy_booked_amt)*100/current,2)
  py_booked_percentage = round((py_booked_amt)*100/investment,2)
  total_booked_percentage = round((total_booked_amt)*100/investment,2)

  print('-------------------')
  print('Initial Investment: ', format_amt(investment))
  print('CY Investment: ', format_amt(cy_invested))
  print('Reserve: ', format_amt(reserve_amt))
  print('Current: ',  format_amt(current))
  print('-------------------')
  print('Today PnL: '+ '{} ({}%)'.format(format_amt(today_pnl_amount), today_pnl_percentage))
  print('Current PnL: '+ '{} ({}%)'.format(format_amt(curr_pnl_amount), curr_pnl_percentage))
  print('CY Booked + Current PnL: '+ '{} ({}%)'.format(format_amt(cy_pnl_amount), cy_pnl_percentage))
  print('-------------------')
  print('Total profit: ', format_amt(total_profit))
  print('Total loss: ', format_amt(total_loss))
  print('-------------------')
  print('Total Booked + Current PnL: '+ '{} ({}%)'.format(format_amt(overall_pnl_amount), overall_pnl_percentage))
  print('Total Booked PnL: '+ '{} ({}%)'.format(format_amt(total_booked_amt), total_booked_percentage))
  print('Curr Year Booked PnL: '+ '{} ({}%)'.format(format_amt(cy_booked_amt), cy_booked_percentage))
  print('Prev Year Booked PnL: '+ '{} ({}%)'.format(format_amt(py_booked_amt), py_booked_percentage))
  print('===================')
  print('Est FTT: ',  format_amt(estimate_st))
  print('Est FTT PnL: '+ '{} ({}%)'.format(format_amt(est_st_pnl_amount), est_st_pnl_percentage))

  print('===================')
  print('Deployed: ', format_amt(investment))

  print('Current: ', format_amt(current))

  print('CAGR/XIRR %: '+'{}%'.format(cagr))

In [8]:
# get start and end date
start_date, end_date = get_start_end_date()

# get portfolio and prospects data
mypfs_df = get_mypfs_df()
mypps_df = get_mypps_df()
myinvmt_df = get_myinvmt_df()

# merge above datasets
mypf_df = pd.merge(mypfs_df, mypps_df, on="Symbol")

# seggregate dm and sv portfolio
dm_pf = mypf_df[mypf_df['InPortfolio'] == 'DM']
sv_pf = mypf_df[mypf_df['InPortfolio'] == 'SV']

# build portfolio stock dataframe
dm_stocks = get_stock_ids(dm_pf)
sv_stocks = get_stock_ids(sv_pf)
df_stocks = pd.concat([dm_pf,sv_pf], ignore_index = True)

# arrange common and diff stock features
common_cols = ['Symbol', 'Target', 'Criteria', 'Strategy', 'CumlRnk', 'LatestQtr', 'StarStock', 'Conviction', 'Category', 'InFolio', 'XIRR', 'MBQ']
diff_cols = ['Symbol', 'AvgCost', 'Shares']
df_stocks = arrange_features(df_stocks, common_cols, diff_cols)

# get common features
stock_ids = df_stocks['Symbol'].values
df_common_features = get_common_features(stock_ids, df_stocks)

df_common_features.reset_index(drop=True, inplace=True)
df_common_features.drop(['Date'], axis=1, inplace=True)
# get and print portfolio features
df_portfolio_features = get_portfolio_features(df_common_features)

print_portfolio_stats(df_portfolio_features, myinvmt_df)

df = df_portfolio_features
#plot_pie_chart(df, 'CapType', 'Current')
list_ox40n = list(df[df['MBQ'].str.contains('OX40N', na=False)]['Symbol'].values)

Run date time (IST): 2026-08-12 09:36:34
-------------------
qualified stocks: 88
with latest results: 30
still star stocks: 19
-------------------
Initial Investment:  1.46 C
CY Investment:  1.89 C
Reserve:  2.24 L
Current:  1.61 C
-------------------
Today PnL: -36.70 K (-0.23%)
Current PnL: -30.78 L (-16.29%)
CY Booked + Current PnL: -26.56 L (-14.06%)
-------------------
Total profit:  4.36 L
Total loss:  -35.14 L
-------------------
Total Booked + Current PnL: 16.31 L (11.17%)
Total Booked PnL: 47.09 L (32.24%)
Curr Year Booked PnL: 4.22 L (2.62%)
Prev Year Booked PnL: 42.87 L (29.35%)
===================
Est FTT:  2.67 C
Est FTT PnL: 1.05 C (65.32%)
===================
Deployed:  1.46 C
Current:  1.61 C
CAGR/XIRR %: 4.56%

In [9]:
# top 5 near their targets
cols = ['Symbol', 'Today P/L%', 'Current P/L%', 'FTT%', 'OTT%', 'FTT Amt', 'Current P/L', 'Current', 'FTT', 'Dev%_PE', 'RSI_14','Conviction', 'Spread%',  'CumlRnk', 'RRR Ind', 'CurrAlloc%', 'Gained%', 'Criteria', 'Strategy', 'Category']
df_tmp = df_portfolio_features[~df_portfolio_features['Symbol'].isin(['ENRIN','BLUSPRING','DIGITIDE'])]
df_tmp = df_tmp.sort_values(by = 'FTT Amt', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
55,MEDANTA,-2.61,22.98,3.37,27.12,7316.0,40561.0,217078.0,1486.00,19.21,60.0,X-SC,16.38,87.0,5.54,1.36,49.58,XY24,NTT,HEALTHCARE
80,UNITDSPR,-1.59,11.95,7.87,20.77,20629.0,27984.0,262128.0,1644.00,-0.77,64.0,X-MC,9.00,64.0,1.36,1.65,26.00,X40N,NTT,BREWERIES
69,SIS,3.01,1.10,19.95,21.26,22394.0,1219.0,112251.0,528.00,2681.35,58.0,H-SC,22.47,168.0,0.05,0.71,66.90,OX40N,NTT,MISC
79,TTKPRESTIG,-2.41,-23.18,30.29,0.09,23451.0,-23356.0,77421.0,770.00,79.72,39.0,M-SC,12.78,250.0,-1.00,0.49,39.35,OX40N,NTT,DURABLES
52,M&M,-0.21,9.03,8.98,18.82,23565.0,21732.0,262413.0,3762.88,-5.04,63.0,X-LC,4.73,25.0,0.92,1.65,19.04,X40N,ATH,AUTO

In [10]:
# top 5 today
df_tmp = df_portfolio_features.sort_values(by = 'Today P/L%', ascending=False)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
25,FINCABLES,11.17,70.07,22.25,107.91,55868.0,103450.0,251094.0,1641.55,53.22,80.0,M-SC,18.17,220.0,1.85,1.58,88.91,OX40N,ATH,CABLES
82,VALIANTORG,9.25,-32.40,157.61,74.15,174320.0,-53003.0,110602.0,838.00,-299.00,75.0,H-SC,4.44,145.0,-0.30,0.70,64.59,XR,NTT,CHEMICALS
66,SFL,4.89,-29.90,80.64,26.63,148226.0,-78406.0,183812.0,1287.00,39.23,44.0,M-SC,21.86,242.0,-0.53,1.16,53.41,XY24,NTT,MISC
10,BATAINDIA,4.84,-52.67,185.66,35.20,113069.0,-67769.0,60901.0,2096.00,-20.14,62.0,X-SC,13.23,91.0,-0.60,0.38,22.35,X40,NTT,FOOTWEAR
5,ATULAUTO,3.19,-12.06,65.54,45.57,113613.0,-23783.0,173349.0,844.00,3759.46,50.0,M-SC,10.04,248.0,-0.21,1.09,33.40,XY24,NTT,AUTO

In [11]:
# bottom 5 today
df_tmp = df_portfolio_features.sort_values(by = 'Today P/L%', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
28,GODREJCP,-9.41,-14.87,56.98,33.64,121041.0,-37110.0,212427.0,1469.04,-11.86,26.0,X-LC,5.16,32.0,-0.31,1.34,0.00,X40N,ATH,FMCG
55,MEDANTA,-2.61,22.98,3.37,27.12,7316.0,40561.0,217078.0,1486.00,19.21,60.0,X-SC,16.38,87.0,5.54,1.36,49.58,XY24,NTT,HEALTHCARE
64,REPCOHOME,-2.51,-19.91,137.01,89.82,314387.0,-57042.0,229463.0,880.00,-59.76,34.0,H-SC,1.61,161.0,-0.18,1.44,10.31,XY24,NTT,FINANCE
18,COFFEEDAY,-2.48,-48.77,164.03,35.27,95426.0,-55373.0,58176.0,80.00,-59.76,41.0,L-SC,4.55,266.0,-0.58,0.37,43.47,XR,NTT,HOTELS
79,TTKPRESTIG,-2.41,-23.18,30.29,0.09,23451.0,-23356.0,77421.0,770.00,79.72,39.0,M-SC,12.78,250.0,-1.00,0.49,39.35,OX40N,NTT,DURABLES

In [12]:
# top 5 to exit based on CumlRnk
df_tmp = df_portfolio_features[~df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])]
df_tmp = df_tmp[(df_tmp['Current P/L%'] > -1) & (df_tmp['Current P/L%'] < 1)].sort_values(by = 'CumlRnk', ascending=False)
df_tmp[cols].head()

Empty DataFrame
Columns: [Symbol, Today P/L%, Current P/L%, FTT%, OTT%, FTT Amt, Current P/L, Current, FTT, Dev%_PE, RSI_14, Conviction, Spread%, CumlRnk, RRR Ind, CurrAlloc%, Gained%, Criteria, Strategy, Category]
Index: []

In [13]:
# OX40N stocks to exit
df_tmp = df_portfolio_features[(df_portfolio_features['Symbol'].isin(list_ox40n))].sort_values(by = 'Current P/L%', ascending=False)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
25,FINCABLES,11.17,70.07,22.25,107.91,55868.0,103450.0,251094.0,1641.55,53.22,80.0,M-SC,18.17,220.0,1.85,1.58,88.91,OX40N,ATH,CABLES
69,SIS,3.01,1.10,19.95,21.26,22394.0,1219.0,112251.0,528.00,2681.35,58.0,H-SC,22.47,168.0,0.05,0.71,66.90,OX40N,NTT,MISC
43,INDIGOPNTS,-0.19,-19.09,23.62,0.02,33360.0,-33323.0,141236.0,1408.00,115.40,66.0,M-SC,5.36,222.0,-1.00,0.89,60.24,OX40N,NTT,PAINTS
16,CERA,-1.47,-22.27,59.39,23.89,81200.0,-39179.0,136724.0,9475.00,-25.06,40.0,H-SC,12.51,153.0,-0.48,0.86,32.91,OX40N,NTT,CERAMICS
79,TTKPRESTIG,-2.41,-23.18,30.29,0.09,23451.0,-23356.0,77421.0,770.00,79.72,39.0,M-SC,12.78,250.0,-1.00,0.49,39.35,OX40N,NTT,DURABLES

In [14]:
# top 5 to book for rotation
df_tmp = df_portfolio_features[(df_portfolio_features['Current P/L%'] > 20) ].sort_values(by = 'CumlRnk', ascending=False)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
25,FINCABLES,11.17,70.07,22.25,107.91,55868.0,103450.0,251094.0,1641.55,53.22,80.0,M-SC,18.17,220.0,1.85,1.58,88.91,OX40N,ATH,CABLES
87,ZYDUSLIFE,-2.33,22.67,10.46,35.51,26892.0,47515.0,257089.0,1285.01,6.76,59.0,H-MC,15.94,120.0,1.77,1.62,35.29,AR,ATH,PHARMA
55,MEDANTA,-2.61,22.98,3.37,27.12,7316.0,40561.0,217078.0,1486.00,19.21,60.0,X-SC,16.38,87.0,5.54,1.36,49.58,XY24,NTT,HEALTHCARE
58,QUESS,1.67,35.00,28.82,73.90,41549.0,37375.0,144168.0,424.00,-27.27,67.0,X-SC,40.41,80.0,0.90,0.91,98.43,XY24,NTT,MISC

In [15]:
# top 5 to monitor for exit
df_tmp = df_portfolio_features[~df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])]
df_tmp = df_tmp[(df_tmp['Current P/L%'] > 0) ].sort_values(by = 'Dev%_PE', ascending=False)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
69,SIS,3.01,1.10,19.95,21.26,22394.0,1219.0,112251.0,528.00,2681.35,58.0,H-SC,22.47,168.0,0.05,0.71,66.90,OX40N,NTT,MISC
70,STARHEALTH,-0.22,12.89,30.44,47.26,96607.0,36247.0,317370.0,761.00,78.26,50.0,H-SC,16.88,173.0,0.38,1.99,37.22,XY24,NTT,INSURANCE
25,FINCABLES,11.17,70.07,22.25,107.91,55868.0,103450.0,251094.0,1641.55,53.22,80.0,M-SC,18.17,220.0,1.85,1.58,88.91,OX40N,ATH,CABLES
87,ZYDUSLIFE,-2.33,22.67,10.46,35.51,26892.0,47515.0,257089.0,1285.01,6.76,59.0,H-MC,15.94,120.0,1.77,1.62,35.29,AR,ATH,PHARMA

In [16]:
# top 5 to book for rotation from weak conviction
df_tmp = df_portfolio_features[~df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])]
df_tmp = df_tmp[~df_tmp['Criteria'].isin(['XY25','XY24','X40', 'X40N'])].sort_values(by = 'RRR Ind', ascending=False)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
25,FINCABLES,11.17,70.07,22.25,107.91,55868.0,103450.0,251094.0,1641.55,53.22,80.0,M-SC,18.17,220.0,1.85,1.58,88.91,OX40N,ATH,CABLES
87,ZYDUSLIFE,-2.33,22.67,10.46,35.51,26892.0,47515.0,257089.0,1285.01,6.76,59.0,H-MC,15.94,120.0,1.77,1.62,35.29,AR,ATH,PHARMA
69,SIS,3.01,1.10,19.95,21.26,22394.0,1219.0,112251.0,528.00,2681.35,58.0,H-SC,22.47,168.0,0.05,0.71,66.90,OX40N,NTT,MISC
3,ALKYLAMINE,-0.78,-17.70,133.96,92.54,111306.0,-17874.0,83089.0,4520.85,-11.91,60.0,H-SC,13.54,142.0,-0.16,0.52,57.78,SR,ATH,CHEMICALS
42,INDIAMART,-0.47,-23.68,163.27,100.92,153683.0,-29208.0,94128.0,4675.60,-65.62,40.0,H-SC,12.65,140.0,-0.19,0.59,1.89,AR,ATH,MISC

In [17]:
# top 5 to accumulate based on lowest RSI_14
df_tmp = df_portfolio_features[df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])].sort_values(by = 'RSI_14', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
28,GODREJCP,-9.41,-14.87,56.98,33.64,121041.0,-37110.0,212427.0,1469.04,-11.86,26.0,X-LC,5.16,32.0,-0.31,1.34,0.00,X40N,ATH,FMCG
34,HDFCBANK,-0.30,-11.23,47.62,31.05,123913.0,-32908.0,260212.0,1073.00,-25.96,33.0,X-LC,11.40,26.0,-0.27,1.64,1.00,X40,BTT,BANKS
57,PGHH,-0.38,-36.68,108.50,32.01,146683.0,-78328.0,135192.0,17616.87,-57.19,34.0,X-MC,19.19,57.0,-0.53,0.85,0.00,X40,ATH,FMCG
56,PAGEIND,-1.28,-0.46,34.20,33.59,91367.0,-1224.0,267155.0,51217.29,-28.65,36.0,X-MC,8.90,55.0,-0.01,1.68,26.87,X40,ATH,APPARELS
83,VBL,0.06,-11.39,53.10,35.66,165544.0,-40085.0,311759.0,669.42,-22.02,37.0,X-LC,7.71,13.0,-0.24,1.96,14.78,X40N,ATH,FMCG

In [18]:
# top 5 to accumulate based on Spread and CumlRnk
df_tmp = df_portfolio_features[df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])]
df_tmp = df_tmp[(df_tmp['CumlRnk'] < 100)].sort_values(by = 'Spread%', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
19,COLPAL,-0.41,-24.07,84.19,39.86,168363.0,-63385.0,199980.0,3683.41,-8.09,41.0,X-MC,1.46,62.0,-0.38,1.26,13.12,XY25,ATH,FMCG
11,BERGEPAINT,0.83,0.73,24.41,25.32,63377.0,1886.0,259635.0,680.00,-4.69,66.0,X-MC,2.60,68.0,0.03,1.63,36.15,XY24,NTT,PAINTS
23,DMART,-0.40,-1.55,33.49,31.42,102797.0,-4841.0,306949.0,5391.45,-18.18,52.0,X-LC,2.79,14.0,-0.05,1.93,10.76,X40N,ATH,FMCG
50,KOTAKBANK,-0.88,2.52,16.00,18.92,39317.0,6030.0,245732.0,452.46,-10.71,50.0,X-LC,3.18,12.0,0.15,1.54,10.56,X40,ATH,BANKS
8,BAJAJHLDNG,-0.17,3.59,23.80,28.24,63115.0,9185.0,265190.0,14274.15,-4.76,66.0,X-LC,3.20,28.0,0.15,1.67,33.47,X40,ATH,FINANCE

In [19]:
# top 5 to accumulate based on lowest Gained%
df_tmp = df_portfolio_features[df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])].sort_values(by = 'Gained%', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
28,GODREJCP,-9.41,-14.87,56.98,33.64,121041.0,-37110.0,212427.0,1469.04,-11.86,26.0,X-LC,5.16,32.0,-0.31,1.34,0.00,X40N,ATH,FMCG
57,PGHH,-0.38,-36.68,108.50,32.01,146683.0,-78328.0,135192.0,17616.87,-57.19,34.0,X-MC,19.19,57.0,-0.53,0.85,0.00,X40,ATH,FMCG
35,HDFCLIFE,0.00,-8.08,51.38,39.15,118421.0,-20257.0,230480.0,811.41,-31.58,38.0,X-LC,16.44,31.0,-0.17,1.45,0.01,X40,ATH,INSURANCE
20,DABUR,-0.93,-20.08,79.79,43.70,158198.0,-49800.0,198268.0,735.00,-27.41,38.0,X-MC,9.46,70.0,-0.31,1.25,0.89,XY24,BTT,FMCG
34,HDFCBANK,-0.30,-11.23,47.62,31.05,123913.0,-32908.0,260212.0,1073.00,-25.96,33.0,X-LC,11.40,26.0,-0.27,1.64,1.00,X40,BTT,BANKS

In [20]:
# top 5 to accumulate based on lowest CurrAlloc%
df_tmp = df_portfolio_features[df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])].sort_values(by = 'CurrAlloc%', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
10,BATAINDIA,4.84,-52.67,185.66,35.20,113069.0,-67769.0,60901.0,2096.00,-20.14,62.0,X-SC,13.23,91.0,-0.60,0.38,22.35,X40,NTT,FOOTWEAR
62,RELAXO,1.14,-44.40,173.93,52.31,140375.0,-64452.0,80708.0,1176.00,-40.76,62.0,X-SC,12.38,92.0,-0.46,0.51,80.45,X40N,NTT,FOOTWEAR
57,PGHH,-0.38,-36.68,108.50,32.01,146683.0,-78328.0,135192.0,17616.87,-57.19,34.0,X-MC,19.19,57.0,-0.53,0.85,0.00,X40,ATH,FMCG
58,QUESS,1.67,35.00,28.82,73.90,41549.0,37375.0,144168.0,424.00,-27.27,67.0,X-SC,40.41,80.0,0.90,0.91,98.43,XY24,NTT,MISC
2,ACC,-1.41,-40.10,191.84,74.81,308110.0,-107520.0,160608.0,3906.00,-57.46,44.0,X-SC,12.26,85.0,-0.35,1.01,7.30,XY24,BTT,CEMENT

In [21]:
# top 5 to accumulate based on CumlRnk
df_tmp = df_portfolio_features.sort_values(by = 'CumlRnk', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
47,ITC,-0.16,-23.15,62.27,24.70,190105.0,-91987.0,305291.0,452.00,-59.56,40.0,X-LC,10.89,1.0,-0.48,1.92,1.09,X40,NTT,FMCG
75,TCS,-0.37,-28.47,73.62,24.20,243970.0,-131882.0,331391.0,4230.71,-39.36,61.0,X-LC,15.17,2.0,-0.54,2.08,23.58,X40,ATH,IT
45,INFY,-0.13,-15.35,65.84,40.38,209818.0,-57791.0,318679.0,1972.00,-36.14,64.0,X-LC,16.19,3.0,-0.28,2.00,20.68,X40,NTT,IT
77,TMPV,0.52,-16.87,71.72,42.75,248084.0,-70201.0,345906.0,600.00,-83.62,57.0,X-LC,4.88,4.0,-0.28,2.17,18.94,XY24,NTT,AUTO
33,HCLTECH,0.07,-8.61,35.64,23.97,100806.0,-26641.0,282845.0,1853.42,-6.95,70.0,X-LC,12.77,8.0,-0.26,1.78,33.47,X40,ATH,IT

In [22]:
# top 5 for average up
df_tmp = df_portfolio_features[(df_portfolio_features['Dev%_200'] > 5)].sort_values(by = 'CurrAlloc%', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
44,INDUSINDBK,0.64,-25.03,77.27,32.89,44722.0,-19328.0,57878.0,1800.00,-372.41,53.0,L-MC,13.62,258.0,-0.43,0.36,42.69,XR,NTT,BANKS
62,RELAXO,1.14,-44.40,173.93,52.31,140375.0,-64452.0,80708.0,1176.00,-40.76,62.0,X-SC,12.38,92.0,-0.46,0.51,80.45,X40N,NTT,FOOTWEAR
3,ALKYLAMINE,-0.78,-17.70,133.96,92.54,111306.0,-17874.0,83089.0,4520.85,-11.91,60.0,H-SC,13.54,142.0,-0.16,0.52,57.78,SR,ATH,CHEMICALS
12,BOSCH-HCIL,-0.99,-25.86,34.86,-0.01,33033.0,-33047.0,94758.0,2282.00,19291.30,82.0,M-SC,2.99,231.0,-1.00,0.60,61.29,OX40N,BTT,AC
82,VALIANTORG,9.25,-32.40,157.61,74.15,174320.0,-53003.0,110602.0,838.00,-299.00,75.0,H-SC,4.44,145.0,-0.30,0.70,64.59,XR,NTT,CHEMICALS

In [23]:
# top 5 RSP
df_tmp = df_portfolio_features.sort_values(by = 'RSP', ascending=False)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
25,FINCABLES,11.17,70.07,22.25,107.91,55868.0,103450.0,251094.0,1641.55,53.22,80.0,M-SC,18.17,220.0,1.85,1.58,88.91,OX40N,ATH,CABLES
12,BOSCH-HCIL,-0.99,-25.86,34.86,-0.01,33033.0,-33047.0,94758.0,2282.00,19291.30,82.0,M-SC,2.99,231.0,-1.00,0.60,61.29,OX40N,BTT,AC
82,VALIANTORG,9.25,-32.40,157.61,74.15,174320.0,-53003.0,110602.0,838.00,-299.00,75.0,H-SC,4.44,145.0,-0.30,0.70,64.59,XR,NTT,CHEMICALS
68,SIEMENS,0.68,8.50,15.12,24.90,30529.0,15815.0,201910.0,4648.66,69.62,73.0,H-LC,12.43,51.0,0.52,1.27,42.46,AR,ATH,ELECTRICAL
33,HCLTECH,0.07,-8.61,35.64,23.97,100806.0,-26641.0,282845.0,1853.42,-6.95,70.0,X-LC,12.77,8.0,-0.26,1.78,33.47,X40,ATH,IT

In [24]:
# Top N allocation
df_tmp = df_portfolio_features.sort_values(by = 'CurrAlloc%', ascending=False)
top_n_values = [10, 25, 50]

sum_df = pd.DataFrame({
    'Top_N': top_n_values,
    'Sum_Alloc%': [df_tmp['CurrAlloc%'].head(n).sum() for n in top_n_values]
})

sum_df

   Top_N  Sum_Alloc%
0     10       19.71
1     25       44.71
2     50       76.83

In [25]:
# market-cap-wise allocation
df_tmp = df_portfolio_features[cols]
df_tmp.groupby(df_tmp['Conviction'].str[-2:])['CurrAlloc%'].sum().sort_values(ascending=False)

Conviction
SC    39.59
LC    37.58
MC    22.85
Name: CurrAlloc%, dtype: float64

In [26]:
# criteria-wise allocation
df_portfolio_features.groupby('Criteria')['CurrAlloc%'].sum().sort_values(ascending=False)

Criteria
X40      26.34
XY24     24.92
X40N     18.31
XR        9.09
OX40N     7.27
XY25      7.14
AR        6.10
SR        0.85
Name: CurrAlloc%, dtype: float64

In [27]:
# conviction-wise allocation
df_portfolio_features.groupby('Conviction')['CurrAlloc%'].sum().sort_values(ascending=False)

Conviction
X-LC    35.51
H-SC    19.28
X-MC    18.63
X-SC     9.91
M-SC     9.89
H-MC     2.68
H-LC     1.27
M-MC     1.18
M-LC     0.80
L-SC     0.51
L-MC     0.36
Name: CurrAlloc%, dtype: float64

In [28]:
# sector-wise stats
df_tmp = df_portfolio_features.groupby('Category')[['CurrAlloc%', 'Current', 'Current P/L', 'FTT Amt']].sum().sort_values(by=['Current', 'Current P/L'], ascending=False)
df_tmp['Current P/L%'] = round(df_tmp['Current P/L'] * 100 / df_tmp['Current'], 2)
df_tmp['FTT%'] = round(df_tmp['FTT Amt'] * 100 / df_tmp['Current'], 2)
cols = ['CurrAlloc%', 'Current P/L%', 'FTT%']
df_tmp[cols].sort_values(by=['CurrAlloc%'], ascending=False)

               CurrAlloc%  Current P/L%    FTT%
Category
FMCG                15.25        -23.05   67.37
IT                  11.17        -33.81  100.23
FINANCE              9.22        -16.48   65.43
AUTO                 8.30         -2.36   39.01
MISC                 6.93        -21.56   73.72
BANKS                6.05        -10.98   58.85
PHARMA               5.67          8.08   17.99
INSURANCE            5.55         -5.23   42.44
PAINTS               5.49        -12.97   32.24
ELECTRICAL           4.14         -7.31   44.89
HEALTHCARE           2.06         -8.90   37.32
AC                   1.80        -11.63   41.90
REFINERIES           1.69        -11.00   48.28
APPARELS             1.68         -0.46   34.20
FOOTWEAR             1.67        -66.19  132.83
BREWERIES            1.65         10.68    7.87
CABLES               1.58         41.20   22.25
DURABLES             1.48        -64.56  104.59
TRAVEL               1.46        -92.31  188.61
CERAMICS             1.33        -45.31   89.46
CHEMICALS            1.22        -36.59  147.46
ENGINEERING          1.21        -26.05   83.71
CEMENT               1.01        -66.95  191.84
JEWELLERY            0.97       -107.92  180.16
ENTERTAINMENT        0.68        -79.45  186.46
TEXTILES             0.39        -50.49   93.39
HOTELS               0.37        -95.18  164.03

In [29]:
# money to be made criteria-wise
df_portfolio_features.groupby('Criteria')['FTT Amt'].agg(['sum', 'count']).sort_values(by='sum', ascending=False)

                sum  count
Criteria
XY24      3437067.0     20
X40       2036036.0     18
XR        1351906.0     13
X40N      1169669.0     12
AR        1060332.0      8
OX40N      638665.0     10
XY25       563757.0      5
SR         280233.0      2

In [30]:
# money to be made conviction-wise
df_portfolio_features.groupby('Conviction')['FTT Amt'].agg(['sum', 'count']).sort_values(by='sum', ascending=False)

                  sum  count
Conviction
H-SC        3283928.0     23
X-LC        2410203.0     20
X-MC        1490156.0     14
M-SC        1345793.0     14
X-SC        1226768.0      9
H-MC         272287.0      2
L-SC         211101.0      2
M-LC         163987.0      1
M-MC          58191.0      1
L-MC          44722.0      1
H-LC          30529.0      1

In [31]:
# money to be made criteria and conviction-wise
df_portfolio_features.groupby(['Conviction', 'Criteria'])['FTT Amt'].agg(['sum', 'count']).sort_values(by='sum', ascending=False)

                           sum  count
Conviction Criteria
X-LC       X40       1159940.0      9
H-SC       XY24       988536.0      5
           AR         926129.0      5
M-SC       XY24       843697.0      6
H-SC       XR         798248.0      7
X-SC       XY24       715320.0      4
X-MC       X40        662088.0      7
X-LC       X40N       521016.0      6
           XY24       422544.0      2
X-MC       X40N       351213.0      3
X-SC       X40N       297440.0      3
H-SC       OX40N      290782.0      4
           SR         280233.0      2
X-MC       XY25       255280.0      2
X-LC       XY25       250286.0      2
H-MC       XY24       245395.0      1
M-SC       OX40N      232208.0      5
X-MC       XY24       221575.0      2
X-SC       X40        214008.0      2
M-SC       XR         193106.0      2
M-LC       XR         163987.0      1
L-SC       OX40N      115675.0      1
           XR          95426.0      1
M-SC       AR          76782.0      1
M-MC       XY25        58191.0      1
X-LC       XR          56417.0      1
L-MC       XR          44722.0      1
H-LC       AR          30529.0      1
H-MC       AR          26892.0      1

In [32]:
# notebook execution time

end_time = time.time()
execution_time = round(end_time - start_time, 0)
print(f"Notebook execution time: {execution_time} seconds")

Notebook execution time: 33.0 seconds