<a href="https://colab.research.google.com/github/ankit-rathi/Quantvesting_v2/blob/main/myStocks_Portfolio_Analysis.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
'''
!pip install pandas==2.2.2 -qq
!pip install pyxirr -qq
!pip install ta -qq
!pip install yfinance==0.2.59 -qq
'''

'\n!pip install pandas==2.2.2 -qq\n!pip install pyxirr -qq\n!pip install ta -qq\n!pip install yfinance==0.2.59 -qq\n'

In [2]:
# import libraries

import numpy as np
import pandas as pd
import datetime
import warnings
warnings.filterwarnings('ignore')
import yfinance as yfin
import ta
import matplotlib.pyplot as plt
import requests

In [3]:
# notebook start time
import time
import datetime
import pytz

start_time = time.time()

# function to print date timestamp
def print_date_time():
  tz_NY = pytz.timezone('Asia/Kolkata')
  datetime_NY = datetime.datetime.now(tz_NY)
  print("Run date time (IST):", datetime_NY.strftime("%Y-%m-%d %H:%M:%S"))

In [4]:
# function to get booked and reserved amount
def get_amt():
  # fetch the JSON data from the URL
  url = "https://raw.githubusercontent.com/ankit-rathi/Tradevesting_v1/main/data/myPortfolioAmts.json"
  response = requests.get(url)
  pf_amts = response.json()  # parse the JSON data

  # extract values from the JSON
  py_booked_amt_dm = pf_amts["py_booked_amt_dm"]
  py_booked_amt_sv = pf_amts["py_booked_amt_sv"]
  cy_booked_amt_dm = pf_amts["cy_booked_amt_dm"]
  cy_booked_amt_sv = pf_amts["cy_booked_amt_sv"]
  reserve_amt_dm = pf_amts["reserve_amt_dm"]
  reserve_amt_sv = pf_amts["reserve_amt_sv"]

  # perform calculations
  py_booked_amt = py_booked_amt_dm + py_booked_amt_sv
  cy_booked_amt = cy_booked_amt_dm + cy_booked_amt_sv
  reserve_amt = reserve_amt_dm + reserve_amt_sv
  total_booked_amt = py_booked_amt + cy_booked_amt

  return total_booked_amt, reserve_amt, cy_booked_amt, py_booked_amt

gen_output = 0

In [5]:
# function to format the amount
def format_amt(number):
    abs_number = abs(number)

    if abs_number >= 1_00_00_000:  # Crores
        formatted_amt = f"{number / 1_00_00_000:.2f} C"
    elif abs_number >= 1_00_000:  # Lakhs
        formatted_amt = f"{number / 1_00_000:.2f} L"
    elif abs_number >= 1_000:  # Thousands
        formatted_amt = f"{number / 1_000:.2f} K"
    else:
        formatted_amt = f"{number:.2f}"

    return formatted_amt

# function to set start and end date
def get_start_end_date():
  start_date = (datetime.date.today() + datetime.timedelta(days=-365)).strftime('%Y-%m-%d')
  end_date = (datetime.date.today() + datetime.timedelta(days=1)).strftime('%Y-%m-%d')
  return start_date, end_date

# function to fetch my portfolio csv
def get_mypfs_df():
  mypfs_df = pd.read_csv('https://raw.githubusercontent.com/ankit-rathi/Tradevesting_v1/main/data/myPortfolioStocks.csv')
  return mypfs_df

# function to fetch my prospects csv
def get_mypps_df():
  mypps_df = pd.read_csv('https://raw.githubusercontent.com/ankit-rathi/Tradevesting_v1/main/data/myProspectsScrips.csv')
  return mypps_df

# function to fetch screener data
def get_myscreen_df():
  myscreen_df = pd.read_csv('https://raw.githubusercontent.com/ankit-rathi/Tradevesting_v1/main/data/myScreenerDB.csv')
  return myscreen_df

# function to fetch momentum data
def get_myinvmt_df():
  myinvmt_df = pd.read_csv('https://raw.githubusercontent.com/ankit-rathi/Tradevesting_v1/main/data/myInvestments.csv')
  return myinvmt_df

# function to get the stock ids
def get_stock_ids(df_pf):
  stock_n100 = df_pf['Symbol'].unique()

  exclude = ['CADILAHC','MMTC', 'MASFIN']

  stock_ids = df_pf[~df_pf['Symbol'].isin(exclude) ]['Symbol'].unique()

  #mypf = mypf[mypf.Forecast.notnull()]
  #stock_ids = mypf['Symbol'].unique()

  #stock_ids.sort()
  return stock_ids

# get features from screener data
def get_screener_features():
  myscreen_df = get_myscreen_df()
  cols = ['Symbol', 'EPS', 'MedPE', 'ROCE%', 'ROE%', 'CapType']
  return myscreen_df[cols]

# get relative strength
def get_relative_strength(stock_list):

    # Dictionary to store stock tickers and their corresponding percentage price change
    stock_changes = {}

    # Loop through each stock and fetch its price data
    for stock in stock_list:
        try:
            # Download the stock data for the given date range
            stock_data = yfin.Ticker(stock + '.NS').history(period='1mo', interval='1d')[map(str.title, ['open', 'close', 'low', 'high', 'volume'])]

            # Calculate the percentage change for the stock
            if len(stock_data) > 0:
                start_price = stock_data['Close'].iloc[0]
                end_price = stock_data['Close'].iloc[-1]
                percent_change = round(((end_price - start_price) / start_price) * 100, 2)
                stock_changes[stock] = percent_change
            else:
                stock_changes[stock] = np.nan  # If no data is available, set to NaN

        except Exception as e:
            print(f"Error fetching data for {stock}: {e}")
            stock_changes[stock] = np.nan

    # Create a DataFrame with stock tickers and their percentage changes
    df = pd.DataFrame(list(stock_changes.items()), columns=['Symbol', 'Percent_Change'])

    # Drop any stocks with missing data (NaN values)
    df = df.dropna()

    # Calculate the percentile rank based on percentage change
    df['RSP'] = round(df['Percent_Change'].rank(pct=True) * 100, 2)
    cols = ['Symbol', 'RSP']
    df = df[cols]
    # Sort by percentile rank (optional)
    df = df.sort_values(by='RSP', ascending=False).reset_index(drop=True)

    return df

In [6]:
# function to get stock technicals
def stock_prec_dev(stock_symbol):
    #stock_symbol = 'ULTRACEMCO.NS'
    short_window = 20
    mid_window = 50
    long_window = 200
    moving_avg = 'SMA'

    start = datetime.datetime(*map(int, start_date.split('-')))
    end = datetime.datetime(*map(int, end_date.split('-')))

    stock_df = yfin.Ticker(stock_symbol + '.NS').history(period='max', interval='1d')[map(str.title, ['open', 'close', 'low', 'high', 'volume'])]

    stock_df['Max'] = round(max(stock_df['Close']),2)
    stock_df = stock_df[(stock_df.index <= end_date) & (stock_df.index >= start_date)]
    stock_df['200_SMA'] = round(stock_df['Close'].rolling(window = 200, min_periods = 1).mean(),0)
    stock_df['Dev%_200'] = round((stock_df['Close'] - stock_df['200_SMA'])*100/stock_df['200_SMA'],2)
    stock_df.dropna(axis = 0, inplace = True) # remove any null rows

    stock_df['20_SMA'] = stock_df['Close'].rolling(window=20).mean()
    stock_df['50_SMA'] = stock_df['Close'].rolling(window=50).mean()
    stock_df['Symbol'] = stock_symbol

    stock_df['Close'] = round(stock_df['Close'],2)
    stock_df['Min'] = round(min(stock_df['Close']),2)
    stock_df['RSI_14'] = ta.momentum.RSIIndicator(close=stock_df['Close'], window=14).rsi()
    stock_df['RSI_14'] = round(stock_df['RSI_14'],0)
    stock_df['Prev_Close'] = stock_df['Close'].shift(1)
    stock_df.drop(['Open', 'Low', 'High', 'Volume'], axis=1, inplace=True)
    stock_df = stock_df.tail(1)

    max_SMA = max(stock_df['20_SMA'].item(), stock_df['50_SMA'].item(), stock_df['200_SMA'].item())
    min_SMA = min(stock_df['20_SMA'].item(), stock_df['50_SMA'].item(), stock_df['200_SMA'].item())
    ABS_Spread = max_SMA - min_SMA
    stock_df['Spread%'] = round((ABS_Spread / stock_df['200_SMA'].item()) * 100,2)

    return stock_df

# function to compute stock attributes
def get_common_features(stock_ids, df_mypf):

  df_prec_dev = pd.DataFrame()
  df_tmp = get_screener_features()
  df_rs = get_relative_strength(stock_ids)

  for stock_id in stock_ids:
      tmp = stock_prec_dev(stock_id)
      tmp = tmp.reset_index()
      df_prec_dev = pd.concat([df_prec_dev, tmp], ignore_index = True)
  df_prec_dev = pd.merge(df_prec_dev, df_mypf, on= 'Symbol')
  df_prec_dev = pd.merge(df_prec_dev, df_tmp, on= 'Symbol', how='left')
  df_prec_dev = pd.merge(df_prec_dev, df_rs, on= 'Symbol', how='left')
  #print(df_prec_dev.columns)
  df_prec_dev['Curr_PE'] = round(df_prec_dev['Close']/df_prec_dev['EPS'],1)
  df_prec_dev['Dev%_PE'] = round((df_prec_dev['Curr_PE'] - df_prec_dev['MedPE'])*100/df_prec_dev['MedPE'],2)
  df_prec_dev['Conviction'] = df_prec_dev['Conviction'] + '-' + df_prec_dev['CapType']
  return df_prec_dev

# function to arrange stock features
def arrange_features(df_stocks, common_cols, diff_cols):
  df_stocks_common = df_stocks[common_cols].drop_duplicates()
  df_stocks_diff = df_stocks[diff_cols]
  df_stocks_diff['Investment'] = df_stocks_diff['AvgCost'] * df_stocks_diff['Shares']
  df_stocks_diff = df_stocks_diff.groupby(['Symbol'])[['Shares', 'Investment']].aggregate(['sum']).reset_index()
  df_stocks_diff.columns = ['Symbol', 'Shares', 'Investment']
  df_stocks_diff['AvgCost'] = round(df_stocks_diff['Investment']/df_stocks_diff['Shares'],2)
  df_stocks = pd.merge(df_stocks_diff, df_stocks_common, on='Symbol')
  return df_stocks

# plot fact distribution across dimension
def plot_pie_chart(df, dimension, fact):
  # grouping the data by category and calculating the sum of fact for each type
  grouped_data = df.groupby(dimension)[fact].sum()

  # sorting the grouped data in descending order
  grouped_data = grouped_data.sort_values(ascending=False)

  # creating a pie chart
  grouped_data.plot.pie(autopct='%1.1f%%', startangle=90, figsize=(6, 6))

  # adding a title and displaying the plot
  plt.title(f'{dimension} {fact} Distribution')
  plt.ylabel('')  # To hide the y-label
  plt.show()

In [7]:
# function to get portfolio features

def get_portfolio_features(df_common_features):

  print_date_time()
  print('-------------------')

  #df_common_features["Target"] = df_common_features["Target"].fillna(df_common_features["Max"])
  df_common_features['NTT'] = np.where(df_common_features['Strategy']== 'NTT', df_common_features["Target"], df_common_features['Max'])
  df_common_features['LTT'] = np.where(df_common_features['Strategy']== 'BTT', df_common_features["Target"], df_common_features['Max'])
  df_common_features['BOL'] = df_common_features['Min']

  tmp_df = df_common_features[df_common_features['Symbol'].isin(mypf_df[mypf_df['InPortfolio'] != 'NA'].Symbol.values)]
  print('qualified stocks: '+str(len(tmp_df['Symbol'].unique())))
  tmp_df1 = tmp_df[tmp_df['LatestQtr'] == 1]
  print('with latest results: '+str(len(tmp_df1['Symbol'].unique())))
  tmp_df1 = tmp_df1[tmp_df1['StarStock'] == 1]
  print('still star stocks: '+str(len(tmp_df1['Symbol'].unique())))
  tmp_df['Investment'] = tmp_df['AvgCost'] * tmp_df['Shares']
  tmp_df['Current'] = round(tmp_df['Close'] * tmp_df['Shares'],0)
  tmp_df['Previous'] = tmp_df['Prev_Close'] * tmp_df['Shares']
  tmp_df['EstimatedST'] = tmp_df['NTT'] * tmp_df['Shares']
  tmp_df['EstimatedLT'] = tmp_df['LTT'] * tmp_df['Shares']
  tmp_df['Current P/L'] = round((tmp_df['Current'] - tmp_df['Investment']),0)
  tmp_df['Today P/L%'] = round((tmp_df['Current'] - tmp_df['Previous'])*100/tmp_df['Previous'],2)
  tmp_df['Current P/L%'] = round((tmp_df['Current'] - tmp_df['Investment'])*100/tmp_df['Investment'],2)
  tmp_df['EstimatedST P/L%'] = round((tmp_df['EstimatedST'] - tmp_df['Investment'])*100/tmp_df['Investment'],2)
  tmp_df['EstimatedLT P/L%'] = round((tmp_df['EstimatedLT'] - tmp_df['Investment'])*100/tmp_df['Investment'],2)
  tmp_df['NTT%'] = round((tmp_df['NTT'] - tmp_df['Close'])*100/tmp_df['Close'],2)
  tmp_df['LTT%'] = round((tmp_df['LTT'] - tmp_df['Close'])*100/tmp_df['Close'],2)
  tmp_df['Gained%'] = round((tmp_df['Close'] - tmp_df['BOL'])*100/tmp_df['BOL'],2)
  investment = round(sum(tmp_df['AvgCost']*tmp_df['Shares']),0)
  current = round(sum(tmp_df['Close']*tmp_df['Shares']),0)
  tmp_df['InitAlloc%'] = round(tmp_df['Investment']*100/investment,2)
  tmp_df['CurrAlloc%'] = round(tmp_df['Current']*100/current,2)
  tmp_df['FTT'] = tmp_df['LTT']
  tmp_df.loc[tmp_df['Strategy'] == 'NTT', 'FTT'] = tmp_df['NTT']
  tmp_df['FTT%'] = tmp_df['LTT%']
  tmp_df.loc[tmp_df['Strategy'] == 'NTT', 'FTT%'] = tmp_df['NTT%']
  tmp_df['FTT Amt'] = round(tmp_df['FTT%'] * tmp_df['Current']/100,0)
  tmp_df['OTT%'] = round((tmp_df['FTT'] - tmp_df['AvgCost'])*100/tmp_df['AvgCost'],2)
  tmp_df['RRR Ind'] = round(tmp_df['Current P/L']/tmp_df['FTT Amt'],2)
  tmp_df['Risk Ind'] = round(tmp_df['Current P/L%']*tmp_df['CurrAlloc%'],0)

  return tmp_df

# function to print portfolio features
def print_portfolio_stats(df_portfolio_features, myinvmt_df):
  from pyxirr import xirr

  total_booked_amt, reserve_amt, cy_booked_amt, py_booked_amt = get_amt()

  dates = myinvmt_df['Date'].values
  dates = np.append(dates, datetime.date.today().strftime('%d-%b-%y'))
  investment = myinvmt_df['Investment'].values
  dates= pd.to_datetime(dates)

  current = round(sum(df_portfolio_features['Close']*df_portfolio_features['Shares']),0) + reserve_amt
  investment_xirr = np.append(investment, current)
  cagr = round(xirr(pd.DataFrame({"dates": dates, "amounts": investment_xirr}))*100,2)

  investment = -sum(investment)
  invested = round(sum(df_portfolio_features['AvgCost']*df_portfolio_features['Shares']),0) + reserve_amt
  previous = round(sum(df_portfolio_features['Prev_Close']*df_portfolio_features['Shares']),0) + reserve_amt
  cy_invested = investment + py_booked_amt

  today_pnl_amount = current-previous
  today_pnl_percentage = round((current-previous)*100/previous,2)

  curr_pnl_amount = current-invested
  curr_pnl_percentage = round((curr_pnl_amount)*100/(cy_invested),2)

  cy_pnl_amount = cy_booked_amt + curr_pnl_amount
  cy_pnl_percentage = round((cy_pnl_amount)*100/cy_invested,2)

  overall_pnl_amount = total_booked_amt + curr_pnl_amount
  overall_pnl_percentage = round((overall_pnl_amount)*100/investment,2)

  estimate_st = round(sum(df_portfolio_features['FTT']*df_portfolio_features['Shares']),0)  + reserve_amt
  est_st_pnl_amount = estimate_st-current
  est_st_pnl_percentage = round((est_st_pnl_amount)*100/current,2)

  estimate_lt = round(sum(df_portfolio_features['LTT']*df_portfolio_features['Shares']),0)  + reserve_amt
  est_lt_pnl_amount = estimate_lt-current
  est_lt_pnl_percentage = round((est_lt_pnl_amount)*100/current,2)

  total_profit = round(sum(df_portfolio_features[df_portfolio_features['Current P/L%'] > 0]['Current']) - sum(df_portfolio_features[df_portfolio_features['Current P/L%'] > 0]['Investment']),0)
  total_loss = round(sum(df_portfolio_features[df_portfolio_features['Current P/L%'] < 0]['Current']) - sum(df_portfolio_features[df_portfolio_features['Current P/L%'] < 0]['Investment']),0)

  cy_booked_percentage = round((cy_booked_amt)*100/current,2)
  py_booked_percentage = round((py_booked_amt)*100/investment,2)
  total_booked_percentage = round((total_booked_amt)*100/investment,2)

  print('-------------------')
  print('Initial Investment: ', format_amt(investment))
  print('CY Investment: ', format_amt(cy_invested))
  print('Reserve: ', format_amt(reserve_amt))
  print('Current: ',  format_amt(current))
  print('-------------------')
  print('Today PnL: '+ '{} ({}%)'.format(format_amt(today_pnl_amount), today_pnl_percentage))
  print('Current PnL: '+ '{} ({}%)'.format(format_amt(curr_pnl_amount), curr_pnl_percentage))
  print('CY Booked + Current PnL: '+ '{} ({}%)'.format(format_amt(cy_pnl_amount), cy_pnl_percentage))
  print('-------------------')
  print('Total profit: ', format_amt(total_profit))
  print('Total loss: ', format_amt(total_loss))
  print('-------------------')
  print('Total Booked + Current PnL: '+ '{} ({}%)'.format(format_amt(overall_pnl_amount), overall_pnl_percentage))
  print('Total Booked PnL: '+ '{} ({}%)'.format(format_amt(total_booked_amt), total_booked_percentage))
  print('Curr Year Booked PnL: '+ '{} ({}%)'.format(format_amt(cy_booked_amt), cy_booked_percentage))
  print('Prev Year Booked PnL: '+ '{} ({}%)'.format(format_amt(py_booked_amt), py_booked_percentage))
  print('===================')
  print('Est FTT: ',  format_amt(estimate_st))
  print('Est FTT PnL: '+ '{} ({}%)'.format(format_amt(est_st_pnl_amount), est_st_pnl_percentage))

  print('===================')
  print('Deployed: ', format_amt(investment))

  print('Current: ', format_amt(current))

  print('CAGR/XIRR %: '+'{}%'.format(cagr))

In [8]:
# get start and end date
start_date, end_date = get_start_end_date()

# get portfolio and prospects data
mypfs_df = get_mypfs_df()
mypps_df = get_mypps_df()
myinvmt_df = get_myinvmt_df()

# merge above datasets
mypf_df = pd.merge(mypfs_df, mypps_df, on="Symbol")

# seggregate dm and sv portfolio
dm_pf = mypf_df[mypf_df['InPortfolio'] == 'DM']
sv_pf = mypf_df[mypf_df['InPortfolio'] == 'SV']

# build portfolio stock dataframe
dm_stocks = get_stock_ids(dm_pf)
sv_stocks = get_stock_ids(sv_pf)
df_stocks = pd.concat([dm_pf,sv_pf], ignore_index = True)

# arrange common and diff stock features
common_cols = ['Symbol', 'Target', 'Criteria', 'Strategy', 'CumlRnk', 'LatestQtr', 'StarStock', 'Conviction', 'Category', 'InFolio', 'XIRR', 'MBQ']
diff_cols = ['Symbol', 'AvgCost', 'Shares']
df_stocks = arrange_features(df_stocks, common_cols, diff_cols)

# get common features
stock_ids = df_stocks['Symbol'].values
df_common_features = get_common_features(stock_ids, df_stocks)

df_common_features.reset_index(drop=True, inplace=True)
df_common_features.drop(['Date'], axis=1, inplace=True)
# get and print portfolio features
df_portfolio_features = get_portfolio_features(df_common_features)

print_portfolio_stats(df_portfolio_features, myinvmt_df)

df = df_portfolio_features
#plot_pie_chart(df, 'CapType', 'Current')
list_ox40n = list(df[df['MBQ'].str.contains('OX40N', na=False)]['Symbol'].values)

Run date time (IST): 2026-03-04 15:34:49
-------------------
qualified stocks: 86
with latest results: 26
still star stocks: 15
-------------------
Initial Investment:  1.33 C
CY Investment:  1.60 C
Reserve:  2.44 L
Current:  1.34 C
-------------------
Today PnL: -2.56 L (-1.87%)
Current PnL: -40.14 L (-25.09%)
CY Booked + Current PnL: -24.46 L (-15.29%)
-------------------
Total profit:  78.54 K
Total loss:  -40.93 L
-------------------
Total Booked + Current PnL: 2.52 L (1.89%)
Total Booked PnL: 42.66 L (32.07%)
Curr Year Booked PnL: 15.68 L (11.68%)
Prev Year Booked PnL: 26.98 L (20.29%)
===================
Est FTT:  2.41 C
Est FTT PnL: 1.07 C (79.49%)
===================
Deployed:  1.33 C
Current:  1.34 C
CAGR/XIRR %: 0.49%

In [9]:
# top 5 near their targets
cols = ['Symbol', 'Today P/L%', 'Current P/L%', 'FTT%', 'OTT%', 'FTT Amt', 'Current P/L', 'Current', 'FTT', 'Dev%_PE', 'RSI_14','Conviction', 'Spread%',  'CumlRnk', 'RRR Ind', 'CurrAlloc%', 'Gained%', 'Criteria', 'Strategy', 'Category']
df_tmp = df_portfolio_features[~df_portfolio_features['Symbol'].isin(['ENRIN','BLUSPRING','DIGITIDE'])]
df_tmp = df_tmp.sort_values(by = 'FTT Amt', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
19,COALINDIA,2.09,7.01,9.96,17.67,16036.0,10546.0,161006.0,478.51,29.12,58.0,L-LC,11.01,185.0,0.66,1.22,28.00,XY25,ATH,MINING
50,MASFIN,-2.96,-6.31,29.75,21.57,27310.0,-6180.0,91800.0,397.04,-19.15,37.0,H-SC,6.51,167.0,-0.23,0.70,32.95,XR,ATH,FINANCE
77,TTKPRESTIG,-2.30,-36.36,57.27,0.09,36732.0,-36639.0,64138.0,770.00,48.77,23.0,M-SC,12.48,250.0,-1.00,0.49,0.00,OX40N,NTT,DURABLES
51,MEDANTA,-1.80,-7.34,33.91,24.08,39888.0,-9322.0,117628.0,1486.00,-8.05,44.0,X-SC,8.03,87.0,-0.23,0.89,7.74,XY24,NTT,HEALTHCARE
37,ICICIGI,-2.11,-1.71,21.42,19.34,42129.0,-3426.0,196683.0,2252.93,-17.38,41.0,X-MC,1.30,66.0,-0.08,1.49,13.95,X40,ATH,INSURANCE

In [10]:
# top 5 today
df_tmp = df_portfolio_features.sort_values(by = 'Today P/L%', ascending=False)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
69,SURYODAY,4.18,-25.74,65.68,23.03,87339.0,-46094.0,132977.0,216.00,44.74,52.0,H-SC,6.68,166.0,-0.53,1.01,31.94,XR,NTT,BANKS
2,ABBOTINDIA,3.81,-6.66,26.49,18.07,44225.0,-11905.0,166950.0,35195.00,-20.56,63.0,X-MC,11.31,58.0,-0.27,1.27,5.84,X40,ATH,PHARMA
19,COALINDIA,2.09,7.01,9.96,17.67,16036.0,10546.0,161006.0,478.51,29.12,58.0,L-LC,11.01,185.0,0.66,1.22,28.00,XY25,ATH,MINING
43,INFY,1.44,-11.00,50.83,34.24,141549.0,-34412.0,278476.0,1972.00,-29.97,28.0,X-LC,10.09,3.0,-0.24,2.11,2.50,X40,NTT,IT
53,PGHH,0.05,-15.88,56.93,32.01,102255.0,-33904.0,179616.0,17616.87,-43.10,24.0,X-MC,9.78,57.0,-0.33,1.36,0.05,X40,ATH,FMCG

In [11]:
# bottom 5 today
df_tmp = df_portfolio_features.sort_values(by = 'Today P/L%', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
27,FINCABLES,-6.03,12.64,84.58,107.91,140663.0,18664.0,166308.0,1641.55,1.47,63.0,M-SC,6.42,220.0,0.13,1.26,25.12,OX40N,ATH,CABLES
65,SIEMENS,-5.40,-15.07,47.79,25.51,75532.0,-28045.0,158050.0,4671.50,32.74,47.0,H-LC,3.69,51.0,-0.37,1.20,16.39,AR,ATH,ELECTRICAL
75,TMPV,-5.23,-21.96,70.84,33.33,180124.0,-71531.0,254269.0,600.00,-83.62,37.0,X-LC,3.57,4.0,-0.40,1.93,3.95,XY24,NTT,AUTO
55,RAJESHEXPO,-5.00,-74.56,293.35,0.07,102373.0,-102279.0,34898.0,518.00,1179.04,24.0,L-SC,11.12,268.0,-1.00,0.26,0.00,OX40N,NTT,JEWELLERY
7,ATULAUTO,-4.94,-21.71,85.94,45.57,132628.0,-42806.0,154326.0,844.00,3337.84,45.0,M-SC,7.20,248.0,-0.32,1.17,16.79,XY24,NTT,AUTO

In [12]:
# top 5 to exit based on CumlRnk
df_tmp = df_portfolio_features[~df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])]
df_tmp = df_tmp[(df_tmp['Current P/L%'] > -1) & (df_tmp['Current P/L%'] < 1)].sort_values(by = 'CumlRnk', ascending=False)
df_tmp[cols].head()

Empty DataFrame
Columns: [Symbol, Today P/L%, Current P/L%, FTT%, OTT%, FTT Amt, Current P/L, Current, FTT, Dev%_PE, RSI_14, Conviction, Spread%, CumlRnk, RRR Ind, CurrAlloc%, Gained%, Criteria, Strategy, Category]
Index: []

In [13]:
# OX40N stocks to exit
df_tmp = df_portfolio_features[(df_portfolio_features['Symbol'].isin(list_ox40n))].sort_values(by = 'Current P/L%', ascending=False)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
27,FINCABLES,-6.03,12.64,84.58,107.91,140663.0,18664.0,166308.0,1641.55,1.47,63.0,M-SC,6.42,220.0,0.13,1.26,25.12,OX40N,ATH,CABLES
66,SIS,-3.12,-32.19,78.83,21.26,59350.0,-35743.0,75289.0,528.00,1765.80,35.0,H-SC,6.51,168.0,-0.60,0.57,3.79,OX40N,NTT,MISC
48,KANSAINER,-0.70,-34.94,74.42,13.47,130560.0,-94230.0,175437.0,340.00,-44.14,30.0,H-SC,14.13,162.0,-0.72,1.33,0.00,XY24,NTT,PAINTS
41,INDIGOPNTS,-1.08,-35.48,55.01,0.02,61957.0,-61930.0,112629.0,1408.00,71.88,22.0,M-SC,13.17,222.0,-1.00,0.85,0.00,OX40N,NTT,PAINTS
77,TTKPRESTIG,-2.30,-36.36,57.27,0.09,36732.0,-36639.0,64138.0,770.00,48.77,23.0,M-SC,12.48,250.0,-1.00,0.49,0.00,OX40N,NTT,DURABLES

In [14]:
# top 5 to book for rotation
df_tmp = df_portfolio_features[(df_portfolio_features['Current P/L%'] > 20) ].sort_values(by = 'CumlRnk', ascending=False)
df_tmp[cols].head()

Empty DataFrame
Columns: [Symbol, Today P/L%, Current P/L%, FTT%, OTT%, FTT Amt, Current P/L, Current, FTT, Dev%_PE, RSI_14, Conviction, Spread%, CumlRnk, RRR Ind, CurrAlloc%, Gained%, Criteria, Strategy, Category]
Index: []

In [15]:
# top 5 to monitor for exit
df_tmp = df_portfolio_features[~df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])]
df_tmp = df_tmp[(df_tmp['Current P/L%'] > 0) ].sort_values(by = 'Dev%_PE', ascending=False)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
19,COALINDIA,2.09,7.01,9.96,17.67,16036.0,10546.0,161006.0,478.51,29.12,58.0,L-LC,11.01,185.0,0.66,1.22,28.00,XY25,ATH,MINING
27,FINCABLES,-6.03,12.64,84.58,107.91,140663.0,18664.0,166308.0,1641.55,1.47,63.0,M-SC,6.42,220.0,0.13,1.26,25.12,OX40N,ATH,CABLES
1,ABB,-2.55,6.97,36.08,45.57,100975.0,18245.0,279864.0,7934.00,-31.30,53.0,H-MC,8.86,125.0,0.18,2.12,24.28,AR,NTT,ELECTRICAL

In [16]:
# top 5 to book for rotation from weak conviction
df_tmp = df_portfolio_features[~df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])]
df_tmp = df_tmp[~df_tmp['Criteria'].isin(['XY25','XY24','X40', 'X40N'])].sort_values(by = 'RRR Ind', ascending=False)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
1,ABB,-2.55,6.97,36.08,45.57,100975.0,18245.0,279864.0,7934.00,-31.30,53.0,H-MC,8.86,125.0,0.18,2.12,24.28,AR,NTT,ELECTRICAL
27,FINCABLES,-6.03,12.64,84.58,107.91,140663.0,18664.0,166308.0,1641.55,1.47,63.0,M-SC,6.42,220.0,0.13,1.26,25.12,OX40N,ATH,CABLES
40,INDIAMART,-1.56,-10.58,131.18,106.72,144676.0,-13048.0,110288.0,4810.62,-59.77,33.0,H-SC,8.27,140.0,-0.09,0.84,10.33,AR,ATH,MISC
85,ZYDUSLIFE,-1.10,-5.42,43.40,35.63,86025.0,-11359.0,198215.0,1286.17,-17.57,47.0,H-MC,4.95,120.0,-0.13,1.50,10.35,AR,ATH,PHARMA
84,WIPRO,-1.52,-19.79,114.78,72.27,155994.0,-33541.0,135907.0,420.00,-27.84,20.0,M-LC,11.40,98.0,-0.22,1.03,0.00,XR,NTT,IT

In [17]:
# top 5 to accumulate based on lowest RSI_14
df_tmp = df_portfolio_features[df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])].sort_values(by = 'RSI_14', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
8,AWL,-0.33,-41.76,169.89,57.19,322694.0,-136184.0,189943.0,485.0,-66.62,13.0,X-SC,19.86,81.0,-0.42,1.44,0.00,XY24,NTT,FMCG
12,BATAINDIA,-4.81,-52.75,186.14,35.20,113169.0,-67872.0,60798.0,2096.0,-20.29,19.0,X-SC,23.03,91.0,-0.60,0.46,0.00,X40,NTT,FOOTWEAR
9,BAJAJHFL,-1.34,-27.93,115.71,55.47,202895.0,-67938.0,175348.0,181.5,-38.22,23.0,X-MC,17.73,60.0,-0.33,1.33,0.00,X40N,ATH,FINANCE
3,ACC,-1.51,-35.71,155.34,64.15,237624.0,-84981.0,152970.0,3906.0,-51.63,24.0,X-SC,9.92,85.0,-0.36,1.16,0.00,XY24,BTT,CEMENT
17,CAMS,-3.29,-17.47,50.82,24.48,105638.0,-43989.0,207867.0,950.0,-20.89,24.0,X-SC,6.49,89.0,-0.42,1.58,2.01,X40N,NTT,MISC

In [18]:
# top 5 to accumulate based on Spread and CumlRnk
df_tmp = df_portfolio_features[df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])]
df_tmp = df_tmp[(df_tmp['CumlRnk'] < 100)].sort_values(by = 'Spread%', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
37,ICICIGI,-2.11,-1.71,21.42,19.34,42129.0,-3426.0,196683.0,2252.93,-17.38,41.0,X-MC,1.30,66.0,-0.08,1.49,13.95,X40,ATH,INSURANCE
78,UNITDSPR,-3.64,-3.27,24.85,20.77,56283.0,-7654.0,226490.0,1644.00,-14.18,35.0,X-MC,1.35,64.0,-0.14,1.72,3.60,X40N,NTT,BREWERIES
22,DABUR,-3.98,-4.71,50.80,43.70,120086.0,-11679.0,236389.0,735.00,-13.56,35.0,X-MC,1.43,70.0,-0.10,1.79,9.63,XY24,BTT,FMCG
59,RELIANCE,-0.96,-13.66,45.13,25.30,78303.0,-27458.0,173505.0,1952.00,-15.80,32.0,X-LC,2.18,21.0,-0.35,1.32,16.22,XY25,BTT,REFINERIES
35,HINDUNILVR,-2.56,-12.03,29.22,13.67,66075.0,-30933.0,226130.0,2922.00,-34.74,38.0,X-LC,2.55,9.0,-0.47,1.71,6.75,XY25,NTT,FMCG

In [19]:
# top 5 to accumulate based on lowest Gained%
df_tmp = df_portfolio_features[df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])].sort_values(by = 'Gained%', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
3,ACC,-1.51,-35.71,155.34,64.15,237624.0,-84981.0,152970.0,3906.0,-51.63,24.0,X-SC,9.92,85.0,-0.36,1.16,0.0,XY24,BTT,CEMENT
12,BATAINDIA,-4.81,-52.75,186.14,35.20,113169.0,-67872.0,60798.0,2096.0,-20.29,19.0,X-SC,23.03,91.0,-0.60,0.46,0.0,X40,NTT,FOOTWEAR
9,BAJAJHFL,-1.34,-27.93,115.71,55.47,202895.0,-67938.0,175348.0,181.5,-38.22,23.0,X-MC,17.73,60.0,-0.33,1.33,0.0,X40N,ATH,FINANCE
8,AWL,-0.33,-41.76,169.89,57.19,322694.0,-136184.0,189943.0,485.0,-66.62,13.0,X-SC,19.86,81.0,-0.42,1.44,0.0,XY24,NTT,FMCG
13,BERGEPAINT,-1.93,-21.84,54.99,21.14,97714.0,-49645.0,177694.0,680.0,-23.60,26.0,X-MC,14.35,68.0,-0.51,1.35,0.0,XY24,NTT,PAINTS

In [20]:
# top 5 to accumulate based on lowest CurrAlloc%
df_tmp = df_portfolio_features[df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])].sort_values(by = 'CurrAlloc%', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
54,QUESS,-1.79,-36.54,125.10,42.84,51605.0,-23755.0,41251.0,424.00,-58.68,32.0,X-SC,16.96,80.0,-0.46,0.31,0.00,XY24,NTT,MISC
12,BATAINDIA,-4.81,-52.75,186.14,35.20,113169.0,-67872.0,60798.0,2096.00,-20.29,19.0,X-SC,23.03,91.0,-0.60,0.46,0.00,X40,NTT,FOOTWEAR
58,RELAXO,-1.14,-57.74,260.40,52.31,159740.0,-83816.0,61344.0,1176.00,-54.99,26.0,X-SC,15.87,92.0,-0.52,0.47,0.00,X40N,NTT,FOOTWEAR
51,MEDANTA,-1.80,-7.34,33.91,24.08,39888.0,-9322.0,117628.0,1486.00,-8.05,44.0,X-SC,8.03,87.0,-0.23,0.89,7.74,XY24,NTT,HEALTHCARE
36,HONAUT,-0.64,-26.02,93.72,43.32,112933.0,-42372.0,120500.0,58357.33,-35.08,32.0,X-SC,12.54,90.0,-0.38,0.91,0.00,X40N,ATH,ELECTRICAL

In [21]:
# top 5 to accumulate based on CumlRnk
df_tmp = df_portfolio_features.sort_values(by = 'CumlRnk', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
45,ITC,-0.94,-17.83,44.90,19.06,125499.0,-60659.0,279507.0,452.00,-55.12,38.0,X-LC,16.89,1.0,-0.48,2.12,1.20,X40,NTT,FMCG
73,TCS,-0.98,-25.83,66.61,23.58,213743.0,-111742.0,320887.0,4311.59,-35.76,28.0,X-LC,10.81,2.0,-0.52,2.43,0.55,X40,ATH,IT
43,INFY,1.44,-11.00,50.83,34.24,141549.0,-34412.0,278476.0,1972.00,-29.97,28.0,X-LC,10.09,3.0,-0.24,2.11,2.50,X40,NTT,IT
75,TMPV,-5.23,-21.96,70.84,33.33,180124.0,-71531.0,254269.0,600.00,-83.62,37.0,X-LC,3.57,4.0,-0.40,1.93,3.95,XY24,NTT,AUTO
34,HCLTECH,-0.51,-11.48,39.90,23.83,85445.0,-27776.0,214148.0,1908.19,-6.95,28.0,X-LC,7.42,8.0,-0.33,1.62,2.74,X40,ATH,IT

In [22]:
# top 5 for average up
df_tmp = df_portfolio_features[(df_portfolio_features['Dev%_200'] > 5)].sort_values(by = 'CurrAlloc%', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
42,INDUSINDBK,-1.59,-31.52,94.06,32.89,49730.0,-24336.0,52870.0,1800.00,-348.60,51.0,L-MC,12.18,258.0,-0.49,0.40,45.60,XR,NTT,BANKS
67,SONACOMS,-3.06,-13.26,60.36,39.09,52963.0,-13414.0,87745.0,804.02,-31.27,43.0,M-MC,10.94,193.0,-0.25,0.67,24.13,AR,ATH,AUTO
19,COALINDIA,2.09,7.01,9.96,17.67,16036.0,10546.0,161006.0,478.51,29.12,58.0,L-LC,11.01,185.0,0.66,1.22,28.00,XY25,ATH,MINING
27,FINCABLES,-6.03,12.64,84.58,107.91,140663.0,18664.0,166308.0,1641.55,1.47,63.0,M-SC,6.42,220.0,0.13,1.26,25.12,OX40N,ATH,CABLES
11,BANDHANBNK,-0.14,-14.66,125.47,92.42,298279.0,-40830.0,237729.0,400.00,104.02,63.0,H-SC,8.94,174.0,-0.14,1.80,30.96,XY24,NTT,BANKS

In [23]:
# top 5 RSP
df_tmp = df_portfolio_features.sort_values(by = 'RSP', ascending=False)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
27,FINCABLES,-6.03,12.64,84.58,107.91,140663.0,18664.0,166308.0,1641.55,1.47,63.0,M-SC,6.42,220.0,0.13,1.26,25.12,OX40N,ATH,CABLES
26,EASEMYTRIP,-3.25,-57.34,241.53,45.70,182184.0,-101386.0,75429.0,26.40,-21.71,48.0,M-SC,18.06,204.0,-0.56,0.57,24.28,XY24,NTT,TRAVEL
83,WHIRLPOOL,-1.58,-27.88,152.24,81.92,126047.0,-32003.0,82795.0,2270.00,-57.77,52.0,M-SC,25.85,210.0,-0.25,0.63,16.30,XR,NTT,DURABLES
11,BANDHANBNK,-0.14,-14.66,125.47,92.42,298279.0,-40830.0,237729.0,400.00,104.02,63.0,H-SC,8.94,174.0,-0.14,1.80,30.96,XY24,NTT,BANKS
7,ATULAUTO,-4.94,-21.71,85.94,45.57,132628.0,-42806.0,154326.0,844.00,3337.84,45.0,M-SC,7.20,248.0,-0.32,1.17,16.79,XY24,NTT,AUTO

In [24]:
# Top N allocation
df_tmp = df_portfolio_features.sort_values(by = 'CurrAlloc%', ascending=False)
top_n_values = [10, 25, 50]

sum_df = pd.DataFrame({
    'Top_N': top_n_values,
    'Sum_Alloc%': [df_tmp['CurrAlloc%'].head(n).sum() for n in top_n_values]
})

sum_df

   Top_N  Sum_Alloc%
0     10       20.71
1     25       45.53
2     50       77.56

In [25]:
# market-cap-wise allocation
df_tmp = df_portfolio_features[cols]
df_tmp.groupby(df_tmp['Conviction'].str[-2:])['CurrAlloc%'].sum().sort_values(ascending=False)

Conviction
SC    44.78
MC    30.25
LC    24.95
Name: CurrAlloc%, dtype: float64

In [26]:
# criteria-wise allocation
df_portfolio_features.groupby('Criteria')['CurrAlloc%'].sum().sort_values(ascending=False)

Criteria
XY24     26.74
X40      24.15
X40N     14.54
AR        9.10
XY25      8.92
XR        8.53
OX40N     7.18
SR        0.82
Name: CurrAlloc%, dtype: float64

In [27]:
# conviction-wise allocation
df_portfolio_features.groupby('Conviction')['CurrAlloc%'].sum().sort_values(ascending=False)

Conviction
X-MC    22.82
H-SC    22.28
X-LC    21.50
X-SC    11.14
M-SC    10.69
H-MC     4.99
M-MC     2.04
L-LC     1.22
H-LC     1.20
M-LC     1.03
L-SC     0.67
L-MC     0.40
Name: CurrAlloc%, dtype: float64

In [28]:
# sector-wise stats
df_tmp = df_portfolio_features.groupby('Category')[['CurrAlloc%', 'Current', 'Current P/L', 'FTT Amt']].sum().sort_values(by=['Current', 'Current P/L'], ascending=False)
df_tmp['Current P/L%'] = round(df_tmp['Current P/L'] * 100 / df_tmp['Current'], 2)
df_tmp['FTT%'] = round(df_tmp['FTT Amt'] * 100 / df_tmp['Current'], 2)
cols = ['CurrAlloc%', 'Current P/L%', 'FTT%']
df_tmp[cols].sort_values(by=['CurrAlloc%'], ascending=False)

               CurrAlloc%  Current P/L%    FTT%
Category
FMCG                15.69        -19.25   59.59
FINANCE             12.83        -23.39   71.94
IT                  11.57        -43.43  115.31
MISC                 6.75        -45.98  105.70
ELECTRICAL           6.33        -12.36   53.36
PAINTS               5.06        -38.46   59.03
INSURANCE            4.94         -4.21   39.87
PHARMA               4.28         -4.20   36.99
AUTO                 3.77        -25.74   73.68
BANKS                3.21        -26.27  102.78
AC                   2.21         -9.96   39.77
FOOTWEAR             1.99        -68.62  136.24
TRAVEL               1.94        -74.84  162.38
DURABLES             1.88        -56.42   94.47
BREWERIES            1.72         -3.38   24.85
HEALTHCARE           1.66        -40.42   75.07
REALTY               1.41        -19.07   38.63
CERAMICS             1.41        -65.01  115.14
APPARELS             1.41        -27.53   65.97
REFINERIES           1.32        -15.83   45.13
CABLES               1.26         11.22   84.58
MINING               1.22          6.55    9.96
JEWELLERY            1.18       -104.53  175.59
CEMENT               1.16        -55.55  155.34
ENGINEERING          1.11        -65.46  141.14
CHEMICALS            1.03        -95.03  254.13
ENTERTAINMENT        0.79        -85.73  196.49
TEXTILES             0.44        -58.40  103.56
HOTELS               0.41       -108.61  182.19

In [29]:
# money to be made criteria-wise
df_portfolio_features.groupby('Criteria')['FTT Amt'].agg(['sum', 'count']).sort_values(by='sum', ascending=False)

                sum  count
Criteria
XY24      3600482.0     21
X40       1536799.0     15
AR        1371289.0     10
XR        1365974.0     12
X40N      1203918.0     10
OX40N      844344.0     10
XY25       441803.0      6
SR         311032.0      2

In [30]:
# money to be made conviction-wise
df_portfolio_features.groupby('Conviction')['FTT Amt'].agg(['sum', 'count']).sort_values(by='sum', ascending=False)

                  sum  count
Conviction
H-SC        3853936.0     24
M-SC        1508118.0     14
X-MC        1506025.0     15
X-LC        1436227.0     12
X-SC        1334770.0     10
H-MC         420271.0      3
L-SC         201543.0      2
M-LC         155994.0      1
M-MC         117459.0      2
H-LC          75532.0      1
L-MC          49730.0      1
L-LC          16036.0      1

In [31]:
# money to be made criteria and conviction-wise
df_portfolio_features.groupby(['Conviction', 'Criteria'])['FTT Amt'].agg(['sum', 'count']).sort_values(by='sum', ascending=False)

                           sum  count
Conviction Criteria
H-SC       XY24      1310276.0      6
           AR         979091.0      5
M-SC       XY24       881901.0      6
H-SC       XR         874717.0      7
X-LC       X40        734246.0      6
X-SC       XY24       651811.0      4
X-MC       X40        599467.0      7
X-SC       X40N       479873.0      4
X-MC       X40N       471865.0      4
H-SC       OX40N      378820.0      4
M-SC       OX40N      363151.0      5
H-SC       SR         311032.0      2
X-LC       XY24       305423.0      2
           X40N       252180.0      2
H-MC       XY24       233271.0      1
X-MC       XY24       217800.0      2
           XY25       216893.0      2
X-SC       X40        203086.0      2
H-MC       AR         187000.0      2
M-SC       XR         186363.0      2
M-LC       XR         155994.0      1
X-LC       XY25       144378.0      2
L-SC       OX40N      102373.0      1
           XR          99170.0      1
M-SC       AR          76703.0      1
H-LC       AR          75532.0      1
M-MC       XY25        64496.0      1
           AR          52963.0      1
L-MC       XR          49730.0      1
L-LC       XY25        16036.0      1

In [32]:
# notebook execution time

end_time = time.time()
execution_time = round(end_time - start_time, 0)
print(f"Notebook execution time: {execution_time} seconds")

Notebook execution time: 32.0 seconds