<a href="https://colab.research.google.com/github/ankit-rathi/Quantvesting_v2/blob/main/myStocks_Portfolio_Analysis.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
'''
!pip install pandas==2.2.2 -qq
!pip install pyxirr -qq
!pip install ta -qq
!pip install yfinance==0.2.59 -qq
'''

'\n!pip install pandas==2.2.2 -qq\n!pip install pyxirr -qq\n!pip install ta -qq\n!pip install yfinance==0.2.59 -qq\n'

In [2]:
# import libraries

import numpy as np
import pandas as pd
import datetime
import warnings
warnings.filterwarnings('ignore')
import yfinance as yfin
import ta
import matplotlib.pyplot as plt
import requests

In [3]:
# notebook start time
import time
import datetime
import pytz

start_time = time.time()

# function to print date timestamp
def print_date_time():
  tz_NY = pytz.timezone('Asia/Kolkata')
  datetime_NY = datetime.datetime.now(tz_NY)
  print("Run date time (IST):", datetime_NY.strftime("%Y-%m-%d %H:%M:%S"))

In [4]:
# function to get booked and reserved amount
def get_amt():
  # fetch the JSON data from the URL
  url = "https://raw.githubusercontent.com/ankit-rathi/Tradevesting_v1/main/data/myPortfolioAmts.json"
  response = requests.get(url)
  pf_amts = response.json()  # parse the JSON data

  # extract values from the JSON
  py_booked_amt_dm = pf_amts["py_booked_amt_dm"]
  py_booked_amt_sv = pf_amts["py_booked_amt_sv"]
  cy_booked_amt_dm = pf_amts["cy_booked_amt_dm"]
  cy_booked_amt_sv = pf_amts["cy_booked_amt_sv"]
  reserve_amt_dm = pf_amts["reserve_amt_dm"]
  reserve_amt_sv = pf_amts["reserve_amt_sv"]

  # perform calculations
  py_booked_amt = py_booked_amt_dm + py_booked_amt_sv
  cy_booked_amt = cy_booked_amt_dm + cy_booked_amt_sv
  reserve_amt = reserve_amt_dm + reserve_amt_sv
  total_booked_amt = py_booked_amt + cy_booked_amt

  return total_booked_amt, reserve_amt, cy_booked_amt, py_booked_amt

gen_output = 0

In [5]:
# function to format the amount
def format_amt(number):
    abs_number = abs(number)

    if abs_number >= 1_00_00_000:  # Crores
        formatted_amt = f"{number / 1_00_00_000:.2f} C"
    elif abs_number >= 1_00_000:  # Lakhs
        formatted_amt = f"{number / 1_00_000:.2f} L"
    elif abs_number >= 1_000:  # Thousands
        formatted_amt = f"{number / 1_000:.2f} K"
    else:
        formatted_amt = f"{number:.2f}"

    return formatted_amt

# function to set start and end date
def get_start_end_date():
  start_date = (datetime.date.today() + datetime.timedelta(days=-365)).strftime('%Y-%m-%d')
  end_date = (datetime.date.today() + datetime.timedelta(days=1)).strftime('%Y-%m-%d')
  return start_date, end_date

# function to fetch my portfolio csv
def get_mypfs_df():
  mypfs_df = pd.read_csv('https://raw.githubusercontent.com/ankit-rathi/Tradevesting_v1/main/data/myPortfolioStocks.csv')
  return mypfs_df

# function to fetch my prospects csv
def get_mypps_df():
  mypps_df = pd.read_csv('https://raw.githubusercontent.com/ankit-rathi/Tradevesting_v1/main/data/myProspectsScrips.csv')
  return mypps_df

# function to fetch screener data
def get_myscreen_df():
  myscreen_df = pd.read_csv('https://raw.githubusercontent.com/ankit-rathi/Tradevesting_v1/main/data/myScreenerDB.csv')
  return myscreen_df

# function to fetch momentum data
def get_myinvmt_df():
  myinvmt_df = pd.read_csv('https://raw.githubusercontent.com/ankit-rathi/Tradevesting_v1/main/data/myInvestments.csv')
  return myinvmt_df

# function to get the stock ids
def get_stock_ids(df_pf):
  stock_n100 = df_pf['Symbol'].unique()

  exclude = ['CADILAHC','MMTC', 'MASFIN']

  stock_ids = df_pf[~df_pf['Symbol'].isin(exclude) ]['Symbol'].unique()

  #mypf = mypf[mypf.Forecast.notnull()]
  #stock_ids = mypf['Symbol'].unique()

  #stock_ids.sort()
  return stock_ids

# get features from screener data
def get_screener_features():
  myscreen_df = get_myscreen_df()
  cols = ['Symbol', 'EPS', 'MedPE', 'ROCE%', 'ROE%', 'CapType']
  return myscreen_df[cols]

# get relative strength
def get_relative_strength(stock_list):

    # Dictionary to store stock tickers and their corresponding percentage price change
    stock_changes = {}

    # Loop through each stock and fetch its price data
    for stock in stock_list:
        try:
            # Download the stock data for the given date range
            stock_data = yfin.Ticker(stock + '.NS').history(period='1mo', interval='1d')[map(str.title, ['open', 'close', 'low', 'high', 'volume'])]

            # Calculate the percentage change for the stock
            if len(stock_data) > 0:
                start_price = stock_data['Close'].iloc[0]
                end_price = stock_data['Close'].iloc[-1]
                percent_change = round(((end_price - start_price) / start_price) * 100, 2)
                stock_changes[stock] = percent_change
            else:
                stock_changes[stock] = np.nan  # If no data is available, set to NaN

        except Exception as e:
            print(f"Error fetching data for {stock}: {e}")
            stock_changes[stock] = np.nan

    # Create a DataFrame with stock tickers and their percentage changes
    df = pd.DataFrame(list(stock_changes.items()), columns=['Symbol', 'Percent_Change'])

    # Drop any stocks with missing data (NaN values)
    df = df.dropna()

    # Calculate the percentile rank based on percentage change
    df['RSP'] = round(df['Percent_Change'].rank(pct=True) * 100, 2)
    cols = ['Symbol', 'RSP']
    df = df[cols]
    # Sort by percentile rank (optional)
    df = df.sort_values(by='RSP', ascending=False).reset_index(drop=True)

    return df

In [6]:
# function to get stock technicals
def stock_prec_dev(stock_symbol):
    #stock_symbol = 'ULTRACEMCO.NS'
    short_window = 20
    mid_window = 50
    long_window = 200
    moving_avg = 'SMA'

    start = datetime.datetime(*map(int, start_date.split('-')))
    end = datetime.datetime(*map(int, end_date.split('-')))

    stock_df = yfin.Ticker(stock_symbol + '.NS').history(period='max', interval='1d')[map(str.title, ['open', 'close', 'low', 'high', 'volume'])]

    stock_df['Max'] = round(max(stock_df['Close']),2)
    stock_df = stock_df[(stock_df.index <= end_date) & (stock_df.index >= start_date)]
    stock_df['200_SMA'] = round(stock_df['Close'].rolling(window = 200, min_periods = 1).mean(),0)
    stock_df['Dev%_200'] = round((stock_df['Close'] - stock_df['200_SMA'])*100/stock_df['200_SMA'],2)
    stock_df.dropna(axis = 0, inplace = True) # remove any null rows

    stock_df['20_SMA'] = stock_df['Close'].rolling(window=20).mean()
    stock_df['50_SMA'] = stock_df['Close'].rolling(window=50).mean()
    stock_df['Symbol'] = stock_symbol

    stock_df['Close'] = round(stock_df['Close'],2)
    stock_df['Min'] = round(min(stock_df['Close']),2)
    stock_df['RSI_14'] = ta.momentum.RSIIndicator(close=stock_df['Close'], window=14).rsi()
    stock_df['RSI_14'] = round(stock_df['RSI_14'],0)
    stock_df['Prev_Close'] = stock_df['Close'].shift(1)
    stock_df.drop(['Open', 'Low', 'High', 'Volume'], axis=1, inplace=True)
    stock_df = stock_df.tail(1)

    max_SMA = max(stock_df['20_SMA'].item(), stock_df['50_SMA'].item(), stock_df['200_SMA'].item())
    min_SMA = min(stock_df['20_SMA'].item(), stock_df['50_SMA'].item(), stock_df['200_SMA'].item())
    ABS_Spread = max_SMA - min_SMA
    stock_df['Spread%'] = round((ABS_Spread / stock_df['200_SMA'].item()) * 100,2)

    return stock_df

# function to compute stock attributes
def get_common_features(stock_ids, df_mypf):

  df_prec_dev = pd.DataFrame()
  df_tmp = get_screener_features()
  df_rs = get_relative_strength(stock_ids)

  for stock_id in stock_ids:
      tmp = stock_prec_dev(stock_id)
      tmp = tmp.reset_index()
      df_prec_dev = pd.concat([df_prec_dev, tmp], ignore_index = True)
  df_prec_dev = pd.merge(df_prec_dev, df_mypf, on= 'Symbol')
  df_prec_dev = pd.merge(df_prec_dev, df_tmp, on= 'Symbol', how='left')
  df_prec_dev = pd.merge(df_prec_dev, df_rs, on= 'Symbol', how='left')
  #print(df_prec_dev.columns)
  df_prec_dev['Curr_PE'] = round(df_prec_dev['Close']/df_prec_dev['EPS'],1)
  df_prec_dev['Dev%_PE'] = round((df_prec_dev['Curr_PE'] - df_prec_dev['MedPE'])*100/df_prec_dev['MedPE'],2)
  df_prec_dev['Conviction'] = df_prec_dev['Conviction'] + '-' + df_prec_dev['CapType']
  return df_prec_dev

# function to arrange stock features
def arrange_features(df_stocks, common_cols, diff_cols):
  df_stocks_common = df_stocks[common_cols].drop_duplicates()
  df_stocks_diff = df_stocks[diff_cols]
  df_stocks_diff['Investment'] = df_stocks_diff['AvgCost'] * df_stocks_diff['Shares']
  df_stocks_diff = df_stocks_diff.groupby(['Symbol'])[['Shares', 'Investment']].aggregate(['sum']).reset_index()
  df_stocks_diff.columns = ['Symbol', 'Shares', 'Investment']
  df_stocks_diff['AvgCost'] = round(df_stocks_diff['Investment']/df_stocks_diff['Shares'],2)
  df_stocks = pd.merge(df_stocks_diff, df_stocks_common, on='Symbol')
  return df_stocks

# plot fact distribution across dimension
def plot_pie_chart(df, dimension, fact):
  # grouping the data by category and calculating the sum of fact for each type
  grouped_data = df.groupby(dimension)[fact].sum()

  # sorting the grouped data in descending order
  grouped_data = grouped_data.sort_values(ascending=False)

  # creating a pie chart
  grouped_data.plot.pie(autopct='%1.1f%%', startangle=90, figsize=(6, 6))

  # adding a title and displaying the plot
  plt.title(f'{dimension} {fact} Distribution')
  plt.ylabel('')  # To hide the y-label
  plt.show()

In [7]:
# function to get portfolio features

def get_portfolio_features(df_common_features):

  print_date_time()
  print('-------------------')

  #df_common_features["Target"] = df_common_features["Target"].fillna(df_common_features["Max"])
  df_common_features['NTT'] = np.where(df_common_features['Strategy']== 'NTT', df_common_features["Target"], df_common_features['Max'])
  df_common_features['LTT'] = np.where(df_common_features['Strategy']== 'BTT', df_common_features["Target"], df_common_features['Max'])
  df_common_features['BOL'] = df_common_features['Min']

  tmp_df = df_common_features[df_common_features['Symbol'].isin(mypf_df[mypf_df['InPortfolio'] != 'NA'].Symbol.values)]
  print('qualified stocks: '+str(len(tmp_df['Symbol'].unique())))
  tmp_df1 = tmp_df[tmp_df['LatestQtr'] == 1]
  print('with latest results: '+str(len(tmp_df1['Symbol'].unique())))
  tmp_df1 = tmp_df1[tmp_df1['StarStock'] == 1]
  print('still star stocks: '+str(len(tmp_df1['Symbol'].unique())))
  tmp_df['Investment'] = tmp_df['AvgCost'] * tmp_df['Shares']
  tmp_df['Current'] = round(tmp_df['Close'] * tmp_df['Shares'],0)
  tmp_df['Previous'] = tmp_df['Prev_Close'] * tmp_df['Shares']
  tmp_df['EstimatedST'] = tmp_df['NTT'] * tmp_df['Shares']
  tmp_df['EstimatedLT'] = tmp_df['LTT'] * tmp_df['Shares']
  tmp_df['Current P/L'] = round((tmp_df['Current'] - tmp_df['Investment']),0)
  tmp_df['Today P/L%'] = round((tmp_df['Current'] - tmp_df['Previous'])*100/tmp_df['Previous'],2)
  tmp_df['Current P/L%'] = round((tmp_df['Current'] - tmp_df['Investment'])*100/tmp_df['Investment'],2)
  tmp_df['EstimatedST P/L%'] = round((tmp_df['EstimatedST'] - tmp_df['Investment'])*100/tmp_df['Investment'],2)
  tmp_df['EstimatedLT P/L%'] = round((tmp_df['EstimatedLT'] - tmp_df['Investment'])*100/tmp_df['Investment'],2)
  tmp_df['NTT%'] = round((tmp_df['NTT'] - tmp_df['Close'])*100/tmp_df['Close'],2)
  tmp_df['LTT%'] = round((tmp_df['LTT'] - tmp_df['Close'])*100/tmp_df['Close'],2)
  tmp_df['Gained%'] = round((tmp_df['Close'] - tmp_df['BOL'])*100/tmp_df['BOL'],2)
  investment = round(sum(tmp_df['AvgCost']*tmp_df['Shares']),0)
  current = round(sum(tmp_df['Close']*tmp_df['Shares']),0)
  tmp_df['InitAlloc%'] = round(tmp_df['Investment']*100/investment,2)
  tmp_df['CurrAlloc%'] = round(tmp_df['Current']*100/current,2)
  tmp_df['FTT'] = tmp_df['LTT']
  tmp_df.loc[tmp_df['Strategy'] == 'NTT', 'FTT'] = tmp_df['NTT']
  tmp_df['FTT%'] = tmp_df['LTT%']
  tmp_df.loc[tmp_df['Strategy'] == 'NTT', 'FTT%'] = tmp_df['NTT%']
  tmp_df['FTT Amt'] = round(tmp_df['FTT%'] * tmp_df['Current']/100,0)
  tmp_df['OTT%'] = round((tmp_df['FTT'] - tmp_df['AvgCost'])*100/tmp_df['AvgCost'],2)
  tmp_df['RRR Ind'] = round(tmp_df['Current P/L']/tmp_df['FTT Amt'],2)
  tmp_df['Risk Ind'] = round(tmp_df['Current P/L%']*tmp_df['CurrAlloc%'],0)

  return tmp_df

# function to print portfolio features
def print_portfolio_stats(df_portfolio_features, myinvmt_df):
  from pyxirr import xirr

  total_booked_amt, reserve_amt, cy_booked_amt, py_booked_amt = get_amt()

  dates = myinvmt_df['Date'].values
  dates = np.append(dates, datetime.date.today().strftime('%d-%b-%y'))
  investment = myinvmt_df['Investment'].values
  dates= pd.to_datetime(dates)

  current = round(sum(df_portfolio_features['Close']*df_portfolio_features['Shares']),0) + reserve_amt
  investment_xirr = np.append(investment, current)
  cagr = round(xirr(pd.DataFrame({"dates": dates, "amounts": investment_xirr}))*100,2)

  investment = -sum(investment)
  invested = round(sum(df_portfolio_features['AvgCost']*df_portfolio_features['Shares']),0) + reserve_amt
  previous = round(sum(df_portfolio_features['Prev_Close']*df_portfolio_features['Shares']),0) + reserve_amt
  cy_invested = investment + py_booked_amt

  today_pnl_amount = current-previous
  today_pnl_percentage = round((current-previous)*100/previous,2)

  curr_pnl_amount = current-invested
  curr_pnl_percentage = round((curr_pnl_amount)*100/(cy_invested),2)

  cy_pnl_amount = cy_booked_amt + curr_pnl_amount
  cy_pnl_percentage = round((cy_pnl_amount)*100/cy_invested,2)

  overall_pnl_amount = total_booked_amt + curr_pnl_amount
  overall_pnl_percentage = round((overall_pnl_amount)*100/investment,2)

  estimate_st = round(sum(df_portfolio_features['FTT']*df_portfolio_features['Shares']),0)  + reserve_amt
  est_st_pnl_amount = estimate_st-current
  est_st_pnl_percentage = round((est_st_pnl_amount)*100/current,2)

  estimate_lt = round(sum(df_portfolio_features['LTT']*df_portfolio_features['Shares']),0)  + reserve_amt
  est_lt_pnl_amount = estimate_lt-current
  est_lt_pnl_percentage = round((est_lt_pnl_amount)*100/current,2)

  total_profit = round(sum(df_portfolio_features[df_portfolio_features['Current P/L%'] > 0]['Current']) - sum(df_portfolio_features[df_portfolio_features['Current P/L%'] > 0]['Investment']),0)
  total_loss = round(sum(df_portfolio_features[df_portfolio_features['Current P/L%'] < 0]['Current']) - sum(df_portfolio_features[df_portfolio_features['Current P/L%'] < 0]['Investment']),0)

  cy_booked_percentage = round((cy_booked_amt)*100/current,2)
  py_booked_percentage = round((py_booked_amt)*100/investment,2)
  total_booked_percentage = round((total_booked_amt)*100/investment,2)

  print('-------------------')
  print('Initial Investment: ', format_amt(investment))
  print('CY Investment: ', format_amt(cy_invested))
  print('Reserve: ', format_amt(reserve_amt))
  print('Current: ',  format_amt(current))
  print('-------------------')
  print('Today PnL: '+ '{} ({}%)'.format(format_amt(today_pnl_amount), today_pnl_percentage))
  print('Current PnL: '+ '{} ({}%)'.format(format_amt(curr_pnl_amount), curr_pnl_percentage))
  print('CY Booked + Current PnL: '+ '{} ({}%)'.format(format_amt(cy_pnl_amount), cy_pnl_percentage))
  print('-------------------')
  print('Total profit: ', format_amt(total_profit))
  print('Total loss: ', format_amt(total_loss))
  print('-------------------')
  print('Total Booked + Current PnL: '+ '{} ({}%)'.format(format_amt(overall_pnl_amount), overall_pnl_percentage))
  print('Total Booked PnL: '+ '{} ({}%)'.format(format_amt(total_booked_amt), total_booked_percentage))
  print('Curr Year Booked PnL: '+ '{} ({}%)'.format(format_amt(cy_booked_amt), cy_booked_percentage))
  print('Prev Year Booked PnL: '+ '{} ({}%)'.format(format_amt(py_booked_amt), py_booked_percentage))
  print('===================')
  print('Est FTT: ',  format_amt(estimate_st))
  print('Est FTT PnL: '+ '{} ({}%)'.format(format_amt(est_st_pnl_amount), est_st_pnl_percentage))

  print('===================')
  print('Deployed: ', format_amt(investment))

  print('Current: ', format_amt(current))

  print('CAGR/XIRR %: '+'{}%'.format(cagr))

In [8]:
# get start and end date
start_date, end_date = get_start_end_date()

# get portfolio and prospects data
mypfs_df = get_mypfs_df()
mypps_df = get_mypps_df()
myinvmt_df = get_myinvmt_df()

# merge above datasets
mypf_df = pd.merge(mypfs_df, mypps_df, on="Symbol")

# seggregate dm and sv portfolio
dm_pf = mypf_df[mypf_df['InPortfolio'] == 'DM']
sv_pf = mypf_df[mypf_df['InPortfolio'] == 'SV']

# build portfolio stock dataframe
dm_stocks = get_stock_ids(dm_pf)
sv_stocks = get_stock_ids(sv_pf)
df_stocks = pd.concat([dm_pf,sv_pf], ignore_index = True)

# arrange common and diff stock features
common_cols = ['Symbol', 'Target', 'Criteria', 'Strategy', 'CumlRnk', 'LatestQtr', 'StarStock', 'Conviction', 'Category', 'InFolio', 'XIRR', 'MBQ']
diff_cols = ['Symbol', 'AvgCost', 'Shares']
df_stocks = arrange_features(df_stocks, common_cols, diff_cols)

# get common features
stock_ids = df_stocks['Symbol'].values
df_common_features = get_common_features(stock_ids, df_stocks)

df_common_features.reset_index(drop=True, inplace=True)
df_common_features.drop(['Date'], axis=1, inplace=True)
# get and print portfolio features
df_portfolio_features = get_portfolio_features(df_common_features)

print_portfolio_stats(df_portfolio_features, myinvmt_df)

df = df_portfolio_features
#plot_pie_chart(df, 'CapType', 'Current')
list_ox40n = list(df[df['MBQ'].str.contains('OX40N', na=False)]['Symbol'].values)

Run date time (IST): 2026-05-04 15:55:39
-------------------
qualified stocks: 92
with latest results: 31
still star stocks: 20
-------------------
Initial Investment:  1.40 C
CY Investment:  1.82 C
Reserve:  1.49 K
Current:  1.49 C
-------------------
Today PnL: 1.26 L (0.85%)
Current PnL: -34.22 L (-18.76%)
CY Booked + Current PnL: -32.14 L (-17.62%)
-------------------
Total profit:  1.30 L
Total loss:  -35.52 L
-------------------
Total Booked + Current PnL: 10.73 L (7.69%)
Total Booked PnL: 44.95 L (32.22%)
Curr Year Booked PnL: 2.08 L (1.4%)
Prev Year Booked PnL: 42.87 L (30.73%)
===================
Est FTT:  2.55 C
Est FTT PnL: 1.06 C (71.49%)
===================
Deployed:  1.40 C
Current:  1.49 C
CAGR/XIRR %: 3.25%

In [9]:
# top 5 near their targets
cols = ['Symbol', 'Today P/L%', 'Current P/L%', 'FTT%', 'OTT%', 'FTT Amt', 'Current P/L', 'Current', 'FTT', 'Dev%_PE', 'RSI_14','Conviction', 'Spread%',  'CumlRnk', 'RRR Ind', 'CurrAlloc%', 'Gained%', 'Criteria', 'Strategy', 'Category']
df_tmp = df_portfolio_features[~df_portfolio_features['Symbol'].isin(['ENRIN','BLUSPRING','DIGITIDE'])]
df_tmp = df_tmp.sort_values(by = 'FTT Amt', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
55,MASFIN,2.07,6.23,14.44,21.57,15030.0,6105.0,104085.0,397.04,-8.31,72.0,H-SC,1.13,167.0,0.41,0.70,34.50,XR,ATH,FINANCE
51,KOTAKBANK,-3.04,-0.70,21.95,21.11,30183.0,-962.0,137510.0,453.24,-14.61,45.0,X-LC,8.58,12.0,-0.03,0.92,5.16,X40,ATH,BANKS
59,PIDILITIND,-0.81,-3.30,22.40,18.37,30567.0,-4650.0,136460.0,1670.26,-32.23,48.0,X-LC,6.99,5.0,-0.15,0.92,7.15,X40,ATH,CHEMICALS
83,TTKPRESTIG,6.23,-30.28,43.56,0.09,30606.0,-30515.0,70262.0,770.00,63.07,63.0,M-SC,17.77,250.0,-1.00,0.47,25.11,OX40N,NTT,DURABLES
53,M&M,0.29,0.80,22.40,23.38,31313.0,1111.0,139792.0,3802.40,-14.43,47.0,X-LC,8.57,25.0,0.04,0.94,5.98,X40N,ATH,AUTO

In [10]:
# top 5 today
df_tmp = df_portfolio_features.sort_values(by = 'Today P/L%', ascending=False)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
72,SIS,12.67,-8.02,31.84,21.26,32518.0,-8904.0,102128.0,528.0,2430.57,80.0,H-SC,7.65,168.0,-0.27,0.69,51.85,OX40N,NTT,MISC
60,QUESS,7.06,-13.20,100.35,73.90,93018.0,-14099.0,92694.0,424.0,-53.17,66.0,X-SC,14.96,80.0,-0.15,0.62,24.69,XY24,NTT,MISC
68,SATIN,7.03,4.48,45.32,51.83,130825.0,12386.0,288670.0,274.0,-6.70,72.0,H-SC,10.20,159.0,0.09,1.94,40.62,XY24,NTT,FINANCE
83,TTKPRESTIG,6.23,-30.28,43.56,0.09,30606.0,-30515.0,70262.0,770.0,63.07,63.0,M-SC,17.77,250.0,-1.00,0.47,25.11,OX40N,NTT,DURABLES
56,MEDANTA,4.86,0.21,26.85,27.12,47497.0,379.0,176896.0,1486.0,-2.82,64.0,X-SC,10.99,87.0,0.01,1.19,21.89,XY24,NTT,HEALTHCARE

In [11]:
# bottom 5 today
df_tmp = df_portfolio_features.sort_values(by = 'Today P/L%', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
73,SONACOMS,-5.24,-0.45,39.72,39.09,40000.0,-455.0,100704.0,804.02,-21.15,55.0,M-MC,16.91,193.0,-0.01,0.68,42.46,AR,ATH,AUTO
23,DMART,-4.57,5.20,23.19,29.60,60895.0,12990.0,262590.0,5391.45,-11.31,51.0,X-LC,9.07,14.0,0.21,1.76,20.03,X40N,ATH,FMCG
51,KOTAKBANK,-3.04,-0.70,21.95,21.11,30183.0,-962.0,137510.0,453.24,-14.61,45.0,X-LC,8.58,12.0,-0.03,0.92,5.16,X40,ATH,BANKS
76,SYMPHONY,-2.63,-36.88,58.39,-0.03,63071.0,-63125.0,108016.0,1306.00,-49.31,55.0,M-SC,11.79,205.0,-1.00,0.73,19.80,OX40N,NTT,DURABLES
86,VALIANTORG,-2.38,-44.70,214.92,74.15,194447.0,-73131.0,90474.0,838.00,-262.82,53.0,H-SC,17.11,145.0,-0.38,0.61,34.64,XR,NTT,CHEMICALS

In [12]:
# top 5 to exit based on CumlRnk
df_tmp = df_portfolio_features[~df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])]
df_tmp = df_tmp[(df_tmp['Current P/L%'] > -1) & (df_tmp['Current P/L%'] < 1)].sort_values(by = 'CumlRnk', ascending=False)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
73,SONACOMS,-5.24,-0.45,39.72,39.09,40000.0,-455.0,100704.0,804.02,-21.15,55.0,M-MC,16.91,193.0,-0.01,0.68,42.46,AR,ATH,AUTO
9,BANDHANBNK,3.52,-0.54,93.46,92.42,258938.0,-1501.0,277058.0,400.00,137.79,76.0,H-SC,7.34,174.0,-0.01,1.86,52.62,XY24,NTT,BANKS
74,STARHEALTH,-1.09,0.61,46.37,47.26,131146.0,1703.0,282826.0,761.00,58.79,66.0,H-SC,7.05,173.0,0.01,1.90,46.47,XY24,NTT,INSURANCE

In [13]:
# OX40N stocks to exit
df_tmp = df_portfolio_features[(df_portfolio_features['Symbol'].isin(list_ox40n))].sort_values(by = 'Current P/L%', ascending=False)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
25,FINCABLES,2.60,28.72,61.52,107.91,116918.0,42404.0,190048.0,1641.55,15.68,72.0,M-SC,11.65,220.0,0.36,1.28,42.98,OX40N,ATH,CABLES
72,SIS,12.67,-8.02,31.84,21.26,32518.0,-8904.0,102128.0,528.00,2430.57,80.0,H-SC,7.65,168.0,-0.27,0.69,51.85,OX40N,NTT,MISC
83,TTKPRESTIG,6.23,-30.28,43.56,0.09,30606.0,-30515.0,70262.0,770.00,63.07,63.0,M-SC,17.77,250.0,-1.00,0.47,25.11,OX40N,NTT,DURABLES
16,CERA,0.91,-30.69,78.76,23.89,96018.0,-53991.0,121912.0,9475.00,-33.17,58.0,H-SC,12.15,153.0,-0.56,0.82,17.16,OX40N,NTT,CERAMICS
50,KANSAINER,-0.25,-34.36,72.86,13.47,128978.0,-92646.0,177021.0,340.00,-43.52,54.0,H-SC,16.16,162.0,-0.72,1.19,23.65,XY24,NTT,PAINTS

In [14]:
# top 5 to book for rotation
df_tmp = df_portfolio_features[(df_portfolio_features['Current P/L%'] > 20) ].sort_values(by = 'CumlRnk', ascending=False)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
25,FINCABLES,2.6,28.72,61.52,107.91,116918.0,42404.0,190048.0,1641.55,15.68,72.0,M-SC,11.65,220.0,0.36,1.28,42.98,OX40N,ATH,CABLES

In [15]:
# top 5 to monitor for exit
df_tmp = df_portfolio_features[~df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])]
df_tmp = df_tmp[(df_tmp['Current P/L%'] > 0) ].sort_values(by = 'Dev%_PE', ascending=False)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
74,STARHEALTH,-1.09,0.61,46.37,47.26,131146.0,1703.0,282826.0,761.00,58.79,66.0,H-SC,7.05,173.0,0.01,1.90,46.47,XY24,NTT,INSURANCE
25,FINCABLES,2.60,28.72,61.52,107.91,116918.0,42404.0,190048.0,1641.55,15.68,72.0,M-SC,11.65,220.0,0.36,1.28,42.98,OX40N,ATH,CABLES
68,SATIN,7.03,4.48,45.32,51.83,130825.0,12386.0,288670.0,274.00,-6.70,72.0,H-SC,10.20,159.0,0.09,1.94,40.62,XY24,NTT,FINANCE
55,MASFIN,2.07,6.23,14.44,21.57,15030.0,6105.0,104085.0,397.04,-8.31,72.0,H-SC,1.13,167.0,0.41,0.70,34.50,XR,ATH,FINANCE

In [16]:
# top 5 to book for rotation from weak conviction
df_tmp = df_portfolio_features[~df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])]
df_tmp = df_tmp[~df_tmp['Criteria'].isin(['XY25','XY24','X40', 'X40N'])].sort_values(by = 'RRR Ind', ascending=False)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
55,MASFIN,2.07,6.23,14.44,21.57,15030.0,6105.0,104085.0,397.04,-8.31,72.0,H-SC,1.13,167.0,0.41,0.70,34.50,XR,ATH,FINANCE
25,FINCABLES,2.60,28.72,61.52,107.91,116918.0,42404.0,190048.0,1641.55,15.68,72.0,M-SC,11.65,220.0,0.36,1.28,42.98,OX40N,ATH,CABLES
73,SONACOMS,-5.24,-0.45,39.72,39.09,40000.0,-455.0,100704.0,804.02,-21.15,55.0,M-MC,16.91,193.0,-0.01,0.68,42.46,AR,ATH,AUTO
42,INDIAMART,-0.43,-10.00,129.68,106.72,143955.0,-12328.0,111008.0,4810.62,-59.38,46.0,H-SC,9.30,140.0,-0.09,0.75,6.65,AR,ATH,MISC
91,ZYDUSLIFE,1.17,-4.85,42.54,35.63,84833.0,-10155.0,199419.0,1286.17,-17.12,47.0,H-MC,3.85,120.0,-0.12,1.34,4.85,AR,ATH,PHARMA

In [17]:
# top 5 to accumulate based on lowest RSI_14
df_tmp = df_portfolio_features[df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])].sort_values(by = 'RSI_14', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
33,HCLTECH,0.12,-22.09,55.96,21.51,105472.0,-53446.0,188478.0,1872.35,-18.11,30.0,X-LC,9.24,8.0,-0.51,1.27,0.38,X40,ATH,IT
45,INFY,-1.13,-20.46,68.78,34.24,171172.0,-64019.0,248869.0,1972.00,-37.23,34.0,X-LC,13.83,3.0,-0.37,1.67,1.41,X40,NTT,IT
35,HDFCLIFE,0.25,-3.77,38.40,33.18,55352.0,-5654.0,144146.0,814.30,-24.86,41.0,X-LC,17.46,31.0,-0.10,0.97,3.93,X40,ATH,INSURANCE
39,ICICIGI,-0.36,-6.94,28.24,19.34,52589.0,-13888.0,186221.0,2252.93,-21.79,41.0,X-MC,5.86,66.0,-0.26,1.25,4.01,X40,ATH,INSURANCE
1,ABBOTINDIA,-0.08,-14.74,38.48,18.07,58678.0,-26365.0,152490.0,35195.00,-27.52,42.0,X-MC,11.99,58.0,-0.45,1.02,0.93,X40,ATH,PHARMA

In [18]:
# top 5 to accumulate based on Spread and CumlRnk
df_tmp = df_portfolio_features[df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])]
df_tmp = df_tmp[(df_tmp['CumlRnk'] < 100)].sort_values(by = 'Spread%', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
88,VOLTAS,1.66,13.76,27.63,45.20,60269.0,26388.0,218130.0,1856.00,30.22,55.0,X-MC,2.13,79.0,0.44,1.46,19.56,XY25,NTT,AC
84,UNITDSPR,-0.29,-2.91,24.39,20.77,55446.0,-6812.0,227332.0,1644.00,-13.87,49.0,X-MC,3.41,64.0,-0.12,1.53,8.44,X40N,NTT,BREWERIES
81,TMPV,0.44,-21.91,74.90,36.58,208125.0,-77971.0,277870.0,600.00,-83.62,50.0,X-LC,4.61,4.0,-0.37,1.87,15.82,XY24,NTT,AUTO
65,RELIANCE,2.26,-6.08,33.42,25.30,63077.0,-12223.0,188740.0,1952.00,-8.50,66.0,X-LC,5.23,21.0,-0.19,1.27,12.15,XY25,BTT,REFINERIES
87,VBL,-1.35,2.36,32.25,35.37,104266.0,7464.0,323306.0,670.16,-9.69,67.0,X-LC,5.38,13.0,0.07,2.17,32.88,X40N,ATH,FMCG

In [19]:
# top 5 to accumulate based on lowest Gained%
df_tmp = df_portfolio_features[df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])].sort_values(by = 'Gained%', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
33,HCLTECH,0.12,-22.09,55.96,21.51,105472.0,-53446.0,188478.0,1872.35,-18.11,30.0,X-LC,9.24,8.0,-0.51,1.27,0.38,X40,ATH,IT
1,ABBOTINDIA,-0.08,-14.74,38.48,18.07,58678.0,-26365.0,152490.0,35195.00,-27.52,42.0,X-MC,11.99,58.0,-0.45,1.02,0.93,X40,ATH,PHARMA
45,INFY,-1.13,-20.46,68.78,34.24,171172.0,-64019.0,248869.0,1972.00,-37.23,34.0,X-LC,13.83,3.0,-0.37,1.67,1.41,X40,NTT,IT
79,TCS,-1.72,-28.63,77.34,26.57,255730.0,-132616.0,330657.0,4311.59,-39.69,42.0,X-LC,13.97,2.0,-0.52,2.22,3.20,X40,ATH,IT
35,HDFCLIFE,0.25,-3.77,38.40,33.18,55352.0,-5654.0,144146.0,814.30,-24.86,41.0,X-LC,17.46,31.0,-0.10,0.97,3.93,X40,ATH,INSURANCE

In [20]:
# top 5 to accumulate based on lowest CurrAlloc%
df_tmp = df_portfolio_features[df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])].sort_values(by = 'CurrAlloc%', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
64,RELAXO,0.99,-61.01,290.63,52.31,164488.0,-88563.0,56597.0,1176.00,-58.47,51.0,X-SC,26.12,92.0,-0.54,0.38,26.54,X40N,NTT,FOOTWEAR
10,BATAINDIA,0.40,-53.47,190.57,35.20,114098.0,-68798.0,59872.0,2096.00,-21.44,49.0,X-SC,26.17,91.0,-0.60,0.40,18.74,X40,NTT,FOOTWEAR
60,QUESS,7.06,-13.20,100.35,73.90,93018.0,-14099.0,92694.0,424.00,-53.17,66.0,X-SC,14.96,80.0,-0.15,0.62,24.69,XY24,NTT,MISC
51,KOTAKBANK,-3.04,-0.70,21.95,21.11,30183.0,-962.0,137510.0,453.24,-14.61,45.0,X-LC,8.58,12.0,-0.03,0.92,5.16,X40,ATH,BANKS
59,PIDILITIND,-0.81,-3.30,22.40,18.37,30567.0,-4650.0,136460.0,1670.26,-32.23,48.0,X-LC,6.99,5.0,-0.15,0.92,7.15,X40,ATH,CHEMICALS

In [21]:
# top 5 to accumulate based on CumlRnk
df_tmp = df_portfolio_features.sort_values(by = 'CumlRnk', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
47,ITC,-1.21,-18.06,45.29,19.06,126244.0,-61420.0,278746.0,452.00,-55.12,56.0,X-LC,16.65,1.0,-0.49,1.87,8.13,X40,NTT,FMCG
79,TCS,-1.72,-28.63,77.34,26.57,255730.0,-132616.0,330657.0,4311.59,-39.69,42.0,X-LC,13.97,2.0,-0.52,2.22,3.20,X40,ATH,IT
45,INFY,-1.13,-20.46,68.78,34.24,171172.0,-64019.0,248869.0,1972.00,-37.23,34.0,X-LC,13.83,3.0,-0.37,1.67,1.41,X40,NTT,IT
81,TMPV,0.44,-21.91,74.90,36.58,208125.0,-77971.0,277870.0,600.00,-83.62,50.0,X-LC,4.61,4.0,-0.37,1.87,15.82,XY24,NTT,AUTO
59,PIDILITIND,-0.81,-3.30,22.40,18.37,30567.0,-4650.0,136460.0,1670.26,-32.23,48.0,X-LC,6.99,5.0,-0.15,0.92,7.15,X40,ATH,CHEMICALS

In [22]:
# top 5 for average up
df_tmp = df_portfolio_features[(df_portfolio_features['Dev%_200'] > 5)].sort_values(by = 'CurrAlloc%', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
44,INDUSINDBK,-0.24,-32.53,96.96,32.89,50508.0,-25114.0,52092.0,1800.00,-345.10,63.0,L-MC,3.88,258.0,-0.50,0.35,28.22,XR,NTT,BANKS
12,BOSCH-HCIL,2.98,-37.25,59.35,-0.01,47598.0,-47607.0,80198.0,2282.00,16313.04,61.0,M-SC,3.21,231.0,-1.00,0.54,36.51,OX40N,BTT,AC
73,SONACOMS,-5.24,-0.45,39.72,39.09,40000.0,-455.0,100704.0,804.02,-21.15,55.0,M-MC,16.91,193.0,-0.01,0.68,42.46,AR,ATH,AUTO
72,SIS,12.67,-8.02,31.84,21.26,32518.0,-8904.0,102128.0,528.00,2430.57,80.0,H-SC,7.65,168.0,-0.27,0.69,51.85,OX40N,NTT,MISC
55,MASFIN,2.07,6.23,14.44,21.57,15030.0,6105.0,104085.0,397.04,-8.31,72.0,H-SC,1.13,167.0,0.41,0.70,34.50,XR,ATH,FINANCE

In [23]:
# top 5 RSP
df_tmp = df_portfolio_features.sort_values(by = 'RSP', ascending=False)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
72,SIS,12.67,-8.02,31.84,21.26,32518.0,-8904.0,102128.0,528.0,2430.57,80.0,H-SC,7.65,168.0,-0.27,0.69,51.85,OX40N,NTT,MISC
9,BANDHANBNK,3.52,-0.54,93.46,92.42,258938.0,-1501.0,277058.0,400.0,137.79,76.0,H-SC,7.34,174.0,-0.01,1.86,52.62,XY24,NTT,BANKS
61,RAJESHEXPO,0.48,-76.86,332.50,0.07,105532.0,-105438.0,31739.0,518.0,1062.88,52.0,L-SC,31.46,268.0,-1.00,0.21,49.00,OX40N,NTT,JEWELLERY
68,SATIN,7.03,4.48,45.32,51.83,130825.0,12386.0,288670.0,274.0,-6.70,72.0,H-SC,10.20,159.0,0.09,1.94,40.62,XY24,NTT,FINANCE
29,GREENPANEL,1.61,-38.00,130.87,43.14,148549.0,-69569.0,113509.0,537.0,154.52,70.0,M-SC,18.66,225.0,-0.47,0.76,36.35,XY24,NTT,MISC

In [24]:
# Top N allocation
df_tmp = df_portfolio_features.sort_values(by = 'CurrAlloc%', ascending=False)
top_n_values = [10, 25, 50]

sum_df = pd.DataFrame({
    'Top_N': top_n_values,
    'Sum_Alloc%': [df_tmp['CurrAlloc%'].head(n).sum() for n in top_n_values]
})

sum_df

   Top_N  Sum_Alloc%
0     10       19.10
1     25       42.64
2     50       72.70

In [25]:
# market-cap-wise allocation
df_tmp = df_portfolio_features[cols]
df_tmp.groupby(df_tmp['Conviction'].str[-2:])['CurrAlloc%'].sum().sort_values(ascending=False)

Conviction
SC    42.45
LC    31.73
MC    25.88
Name: CurrAlloc%, dtype: float64

In [26]:
# criteria-wise allocation
df_portfolio_features.groupby('Criteria')['CurrAlloc%'].sum().sort_values(ascending=False)

Criteria
XY24     27.13
X40      25.49
X40N     16.81
XR        9.13
XY25      7.05
OX40N     6.92
AR        6.70
SR        0.83
Name: CurrAlloc%, dtype: float64

In [27]:
# conviction-wise allocation
df_portfolio_features.groupby('Conviction')['CurrAlloc%'].sum().sort_values(ascending=False)

Conviction
X-LC    29.50
H-SC    22.14
X-MC    20.98
M-SC    10.08
X-SC     9.69
H-MC     2.56
M-MC     1.99
H-LC     1.29
M-LC     0.94
L-SC     0.54
L-MC     0.35
Name: CurrAlloc%, dtype: float64

In [28]:
# sector-wise stats
df_tmp = df_portfolio_features.groupby('Category')[['CurrAlloc%', 'Current', 'Current P/L', 'FTT Amt']].sum().sort_values(by=['Current', 'Current P/L'], ascending=False)
df_tmp['Current P/L%'] = round(df_tmp['Current P/L'] * 100 / df_tmp['Current'], 2)
df_tmp['FTT%'] = round(df_tmp['FTT Amt'] * 100 / df_tmp['Current'], 2)
cols = ['CurrAlloc%', 'Current P/L%', 'FTT%']
df_tmp[cols].sort_values(by=['CurrAlloc%'], ascending=False)

               CurrAlloc%  Current P/L%    FTT%
Category
FMCG                15.62        -13.76   53.89
FINANCE             10.88        -13.84   63.35
IT                  10.57        -43.19  115.28
MISC                 6.88        -30.91   87.78
AUTO                 6.64        -10.83   52.39
BANKS                5.67         -7.52   57.23
INSURANCE            5.29         -5.11   40.88
PAINTS               5.08        -30.28   52.90
PHARMA               4.73         -5.02   38.78
ELECTRICAL           4.11        -15.60   56.74
AC                   2.00         -7.11   36.16
CHEMICALS            1.99        -37.58  119.57
HEALTHCARE           1.95        -23.34   55.53
DURABLES             1.81        -43.33   78.20
APPARELS             1.74         -3.75   39.14
TRAVEL               1.73        -73.84  160.89
FOOTWEAR             1.72        -71.95  140.90
BREWERIES            1.53         -3.00   24.39
REALTY               1.39         -7.15   24.75
CERAMICS             1.30        -59.31  107.72
CABLES               1.28         22.31   61.52
REFINERIES           1.27         -6.48   33.42
ENGINEERING          1.18        -38.04  101.18
CEMENT               1.13        -59.81  179.36
JEWELLERY            1.06       -102.63  173.03
ENTERTAINMENT        0.74        -76.71  182.10
TEXTILES             0.44        -42.18   82.72
HOTELS               0.33       -128.34  208.88

In [29]:
# money to be made criteria-wise
df_portfolio_features.groupby('Criteria')['FTT Amt'].agg(['sum', 'count']).sort_values(by='sum', ascending=False)

                sum  count
Criteria
XY24      3557636.0     21
X40       1906287.0     19
XR        1323892.0     13
X40N      1223019.0     13
AR        1188310.0      9
OX40N      762005.0     10
XY25       390877.0      5
SR         296290.0      2

In [30]:
# money to be made conviction-wise
df_portfolio_features.groupby('Conviction')['FTT Amt'].agg(['sum', 'count']).sort_values(by='sum', ascending=False)

                  sum  count
Conviction
H-SC        3494487.0     24
X-LC        1905979.0     21
X-MC        1608594.0     15
M-SC        1415498.0     14
X-SC        1361188.0      9
H-MC         317524.0      2
L-SC         209404.0      2
M-LC         152385.0      1
M-MC          90881.0      2
L-MC          50508.0      1
H-LC          41868.0      1

In [31]:
# money to be made criteria and conviction-wise
df_portfolio_features.groupby(['Conviction', 'Criteria'])['FTT Amt'].agg(['sum', 'count']).sort_values(by='sum', ascending=False)

                           sum  count
Conviction Criteria
H-SC       XY24      1117173.0      6
X-LC       X40       1029736.0     10
H-SC       AR         945769.0      5
M-SC       XY24       842139.0      6
H-SC       XR         805308.0      7
X-SC       XY24       784645.0      4
X-MC       X40        672658.0      7
           X40N       480333.0      4
X-SC       X40N       372650.0      3
X-LC       X40N       370036.0      6
           XY24       341038.0      2
H-SC       OX40N      329947.0      4
M-SC       OX40N      326526.0      5
H-SC       SR         296290.0      2
X-MC       XY24       239950.0      2
H-MC       XY24       232691.0      1
X-MC       XY25       215653.0      2
X-SC       X40        203893.0      2
M-SC       XR         170993.0      2
M-LC       XR         152385.0      1
X-LC       XY25       124343.0      2
L-SC       OX40N      105532.0      1
           XR         103872.0      1
H-MC       AR          84833.0      1
M-SC       AR          75840.0      1
M-MC       XY25        50881.0      1
L-MC       XR          50508.0      1
H-LC       AR          41868.0      1
X-LC       XR          40826.0      1
M-MC       AR          40000.0      1

In [32]:
# notebook execution time

end_time = time.time()
execution_time = round(end_time - start_time, 0)
print(f"Notebook execution time: {execution_time} seconds")

Notebook execution time: 28.0 seconds