<a href="https://colab.research.google.com/github/ankit-rathi/Quantvesting_v2/blob/main/myStocks_Portfolio_Analysis.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
'''
!pip install pandas==2.2.2 -qq
!pip install pyxirr -qq
!pip install ta -qq
!pip install yfinance==0.2.59 -qq
'''

'\n!pip install pandas==2.2.2 -qq\n!pip install pyxirr -qq\n!pip install ta -qq\n!pip install yfinance==0.2.59 -qq\n'

In [2]:
# import libraries

import numpy as np
import pandas as pd
import datetime
import warnings
warnings.filterwarnings('ignore')
import yfinance as yfin
import ta
import matplotlib.pyplot as plt
import requests

In [3]:
# notebook start time
import time
import datetime
import pytz

start_time = time.time()

# function to print date timestamp
def print_date_time():
  tz_NY = pytz.timezone('Asia/Kolkata')
  datetime_NY = datetime.datetime.now(tz_NY)
  print("Run date time (IST):", datetime_NY.strftime("%Y-%m-%d %H:%M:%S"))

In [4]:
# function to get booked and reserved amount
def get_amt():
  # fetch the JSON data from the URL
  url = "https://raw.githubusercontent.com/ankit-rathi/Tradevesting_v1/main/data/myPortfolioAmts.json"
  response = requests.get(url)
  pf_amts = response.json()  # parse the JSON data

  # extract values from the JSON
  py_booked_amt_dm = pf_amts["py_booked_amt_dm"]
  py_booked_amt_sv = pf_amts["py_booked_amt_sv"]
  cy_booked_amt_dm = pf_amts["cy_booked_amt_dm"]
  cy_booked_amt_sv = pf_amts["cy_booked_amt_sv"]
  reserve_amt_dm = pf_amts["reserve_amt_dm"]
  reserve_amt_sv = pf_amts["reserve_amt_sv"]

  # perform calculations
  py_booked_amt = py_booked_amt_dm + py_booked_amt_sv
  cy_booked_amt = cy_booked_amt_dm + cy_booked_amt_sv
  reserve_amt = reserve_amt_dm + reserve_amt_sv
  total_booked_amt = py_booked_amt + cy_booked_amt

  return total_booked_amt, reserve_amt, cy_booked_amt, py_booked_amt

gen_output = 0

In [5]:
# function to format the amount
def format_amt(number):
    abs_number = abs(number)

    if abs_number >= 1_00_00_000:  # Crores
        formatted_amt = f"{number / 1_00_00_000:.2f} C"
    elif abs_number >= 1_00_000:  # Lakhs
        formatted_amt = f"{number / 1_00_000:.2f} L"
    elif abs_number >= 1_000:  # Thousands
        formatted_amt = f"{number / 1_000:.2f} K"
    else:
        formatted_amt = f"{number:.2f}"

    return formatted_amt

# function to set start and end date
def get_start_end_date():
  start_date = (datetime.date.today() + datetime.timedelta(days=-365)).strftime('%Y-%m-%d')
  end_date = (datetime.date.today() + datetime.timedelta(days=1)).strftime('%Y-%m-%d')
  return start_date, end_date

# function to fetch my portfolio csv
def get_mypfs_df():
  mypfs_df = pd.read_csv('https://raw.githubusercontent.com/ankit-rathi/Tradevesting_v1/main/data/myPortfolioStocks.csv')
  return mypfs_df

# function to fetch my prospects csv
def get_mypps_df():
  mypps_df = pd.read_csv('https://raw.githubusercontent.com/ankit-rathi/Tradevesting_v1/main/data/myProspectsScrips.csv')
  return mypps_df

# function to fetch screener data
def get_myscreen_df():
  myscreen_df = pd.read_csv('https://raw.githubusercontent.com/ankit-rathi/Tradevesting_v1/main/data/myScreenerDB.csv')
  return myscreen_df

# function to fetch momentum data
def get_myinvmt_df():
  myinvmt_df = pd.read_csv('https://raw.githubusercontent.com/ankit-rathi/Tradevesting_v1/main/data/myInvestments.csv')
  return myinvmt_df

# function to get the stock ids
def get_stock_ids(df_pf):
  stock_n100 = df_pf['Symbol'].unique()

  exclude = ['CADILAHC','MMTC', 'MASFIN']

  stock_ids = df_pf[~df_pf['Symbol'].isin(exclude) ]['Symbol'].unique()

  #mypf = mypf[mypf.Forecast.notnull()]
  #stock_ids = mypf['Symbol'].unique()

  #stock_ids.sort()
  return stock_ids

# get features from screener data
def get_screener_features():
  myscreen_df = get_myscreen_df()
  cols = ['Symbol', 'EPS', 'MedPE', 'ROCE%', 'ROE%', 'CapType']
  return myscreen_df[cols]

# get relative strength
def get_relative_strength(stock_list):

    # Dictionary to store stock tickers and their corresponding percentage price change
    stock_changes = {}

    # Loop through each stock and fetch its price data
    for stock in stock_list:
        try:
            # Download the stock data for the given date range
            stock_data = yfin.Ticker(stock + '.NS').history(period='1mo', interval='1d')[map(str.title, ['open', 'close', 'low', 'high', 'volume'])]

            # Calculate the percentage change for the stock
            if len(stock_data) > 0:
                start_price = stock_data['Close'].iloc[0]
                end_price = stock_data['Close'].iloc[-1]
                percent_change = round(((end_price - start_price) / start_price) * 100, 2)
                stock_changes[stock] = percent_change
            else:
                stock_changes[stock] = np.nan  # If no data is available, set to NaN

        except Exception as e:
            print(f"Error fetching data for {stock}: {e}")
            stock_changes[stock] = np.nan

    # Create a DataFrame with stock tickers and their percentage changes
    df = pd.DataFrame(list(stock_changes.items()), columns=['Symbol', 'Percent_Change'])

    # Drop any stocks with missing data (NaN values)
    df = df.dropna()

    # Calculate the percentile rank based on percentage change
    df['RSP'] = round(df['Percent_Change'].rank(pct=True) * 100, 2)
    cols = ['Symbol', 'RSP']
    df = df[cols]
    # Sort by percentile rank (optional)
    df = df.sort_values(by='RSP', ascending=False).reset_index(drop=True)

    return df

In [6]:
# function to get stock technicals
def stock_prec_dev(stock_symbol):
    #stock_symbol = 'ULTRACEMCO.NS'
    short_window = 20
    mid_window = 50
    long_window = 200
    moving_avg = 'SMA'

    start = datetime.datetime(*map(int, start_date.split('-')))
    end = datetime.datetime(*map(int, end_date.split('-')))

    stock_df = yfin.Ticker(stock_symbol + '.NS').history(period='max', interval='1d')[map(str.title, ['open', 'close', 'low', 'high', 'volume'])]

    stock_df['Max'] = round(max(stock_df['Close']),2)
    stock_df = stock_df[(stock_df.index <= end_date) & (stock_df.index >= start_date)]
    stock_df['200_SMA'] = round(stock_df['Close'].rolling(window = 200, min_periods = 1).mean(),0)
    stock_df['Dev%_200'] = round((stock_df['Close'] - stock_df['200_SMA'])*100/stock_df['200_SMA'],2)
    stock_df.dropna(axis = 0, inplace = True) # remove any null rows

    stock_df['20_SMA'] = stock_df['Close'].rolling(window=20).mean()
    stock_df['50_SMA'] = stock_df['Close'].rolling(window=50).mean()
    stock_df['Symbol'] = stock_symbol

    stock_df['Close'] = round(stock_df['Close'],2)
    stock_df['Min'] = round(min(stock_df['Close']),2)
    stock_df['RSI_14'] = ta.momentum.RSIIndicator(close=stock_df['Close'], window=14).rsi()
    stock_df['RSI_14'] = round(stock_df['RSI_14'],0)
    stock_df['Prev_Close'] = stock_df['Close'].shift(1)
    stock_df.drop(['Open', 'Low', 'High', 'Volume'], axis=1, inplace=True)
    stock_df = stock_df.tail(1)

    max_SMA = max(stock_df['20_SMA'].item(), stock_df['50_SMA'].item(), stock_df['200_SMA'].item())
    min_SMA = min(stock_df['20_SMA'].item(), stock_df['50_SMA'].item(), stock_df['200_SMA'].item())
    ABS_Spread = max_SMA - min_SMA
    stock_df['Spread%'] = round((ABS_Spread / stock_df['200_SMA'].item()) * 100,2)

    return stock_df

# function to compute stock attributes
def get_common_features(stock_ids, df_mypf):

  df_prec_dev = pd.DataFrame()
  df_tmp = get_screener_features()
  df_rs = get_relative_strength(stock_ids)

  for stock_id in stock_ids:
      tmp = stock_prec_dev(stock_id)
      tmp = tmp.reset_index()
      df_prec_dev = pd.concat([df_prec_dev, tmp], ignore_index = True)
  df_prec_dev = pd.merge(df_prec_dev, df_mypf, on= 'Symbol')
  df_prec_dev = pd.merge(df_prec_dev, df_tmp, on= 'Symbol', how='left')
  df_prec_dev = pd.merge(df_prec_dev, df_rs, on= 'Symbol', how='left')
  #print(df_prec_dev.columns)
  df_prec_dev['Curr_PE'] = round(df_prec_dev['Close']/df_prec_dev['EPS'],1)
  df_prec_dev['Dev%_PE'] = round((df_prec_dev['Curr_PE'] - df_prec_dev['MedPE'])*100/df_prec_dev['MedPE'],2)
  df_prec_dev['Conviction'] = df_prec_dev['Conviction'] + '-' + df_prec_dev['CapType']
  return df_prec_dev

# function to arrange stock features
def arrange_features(df_stocks, common_cols, diff_cols):
  df_stocks_common = df_stocks[common_cols].drop_duplicates()
  df_stocks_diff = df_stocks[diff_cols]
  df_stocks_diff['Investment'] = df_stocks_diff['AvgCost'] * df_stocks_diff['Shares']
  df_stocks_diff = df_stocks_diff.groupby(['Symbol'])[['Shares', 'Investment']].aggregate(['sum']).reset_index()
  df_stocks_diff.columns = ['Symbol', 'Shares', 'Investment']
  df_stocks_diff['AvgCost'] = round(df_stocks_diff['Investment']/df_stocks_diff['Shares'],2)
  df_stocks = pd.merge(df_stocks_diff, df_stocks_common, on='Symbol')
  return df_stocks

# plot fact distribution across dimension
def plot_pie_chart(df, dimension, fact):
  # grouping the data by category and calculating the sum of fact for each type
  grouped_data = df.groupby(dimension)[fact].sum()

  # sorting the grouped data in descending order
  grouped_data = grouped_data.sort_values(ascending=False)

  # creating a pie chart
  grouped_data.plot.pie(autopct='%1.1f%%', startangle=90, figsize=(6, 6))

  # adding a title and displaying the plot
  plt.title(f'{dimension} {fact} Distribution')
  plt.ylabel('')  # To hide the y-label
  plt.show()

In [7]:
# function to get portfolio features

def get_portfolio_features(df_common_features):

  print_date_time()
  print('-------------------')

  #df_common_features["Target"] = df_common_features["Target"].fillna(df_common_features["Max"])
  df_common_features['NTT'] = np.where(df_common_features['Strategy']== 'NTT', df_common_features["Target"], df_common_features['Max'])
  df_common_features['LTT'] = np.where(df_common_features['Strategy']== 'BTT', df_common_features["Target"], df_common_features['Max'])
  df_common_features['BOL'] = df_common_features['Min']

  tmp_df = df_common_features[df_common_features['Symbol'].isin(mypf_df[mypf_df['InPortfolio'] != 'NA'].Symbol.values)]
  print('qualified stocks: '+str(len(tmp_df['Symbol'].unique())))
  tmp_df1 = tmp_df[tmp_df['LatestQtr'] == 1]
  print('with latest results: '+str(len(tmp_df1['Symbol'].unique())))
  tmp_df1 = tmp_df1[tmp_df1['StarStock'] == 1]
  print('still star stocks: '+str(len(tmp_df1['Symbol'].unique())))
  tmp_df['Investment'] = tmp_df['AvgCost'] * tmp_df['Shares']
  tmp_df['Current'] = round(tmp_df['Close'] * tmp_df['Shares'],0)
  tmp_df['Previous'] = tmp_df['Prev_Close'] * tmp_df['Shares']
  tmp_df['EstimatedST'] = tmp_df['NTT'] * tmp_df['Shares']
  tmp_df['EstimatedLT'] = tmp_df['LTT'] * tmp_df['Shares']
  tmp_df['Current P/L'] = round((tmp_df['Current'] - tmp_df['Investment']),0)
  tmp_df['Today P/L%'] = round((tmp_df['Current'] - tmp_df['Previous'])*100/tmp_df['Previous'],2)
  tmp_df['Current P/L%'] = round((tmp_df['Current'] - tmp_df['Investment'])*100/tmp_df['Investment'],2)
  tmp_df['EstimatedST P/L%'] = round((tmp_df['EstimatedST'] - tmp_df['Investment'])*100/tmp_df['Investment'],2)
  tmp_df['EstimatedLT P/L%'] = round((tmp_df['EstimatedLT'] - tmp_df['Investment'])*100/tmp_df['Investment'],2)
  tmp_df['NTT%'] = round((tmp_df['NTT'] - tmp_df['Close'])*100/tmp_df['Close'],2)
  tmp_df['LTT%'] = round((tmp_df['LTT'] - tmp_df['Close'])*100/tmp_df['Close'],2)
  tmp_df['Gained%'] = round((tmp_df['Close'] - tmp_df['BOL'])*100/tmp_df['BOL'],2)
  investment = round(sum(tmp_df['AvgCost']*tmp_df['Shares']),0)
  current = round(sum(tmp_df['Close']*tmp_df['Shares']),0)
  tmp_df['InitAlloc%'] = round(tmp_df['Investment']*100/investment,2)
  tmp_df['CurrAlloc%'] = round(tmp_df['Current']*100/current,2)
  tmp_df['FTT'] = tmp_df['LTT']
  tmp_df.loc[tmp_df['Strategy'] == 'NTT', 'FTT'] = tmp_df['NTT']
  tmp_df['FTT%'] = tmp_df['LTT%']
  tmp_df.loc[tmp_df['Strategy'] == 'NTT', 'FTT%'] = tmp_df['NTT%']
  tmp_df['FTT Amt'] = round(tmp_df['FTT%'] * tmp_df['Current']/100,0)
  tmp_df['OTT%'] = round((tmp_df['FTT'] - tmp_df['AvgCost'])*100/tmp_df['AvgCost'],2)
  tmp_df['RRR Ind'] = round(tmp_df['Current P/L']/tmp_df['FTT Amt'],2)
  tmp_df['Risk Ind'] = round(tmp_df['Current P/L%']*tmp_df['CurrAlloc%'],0)

  return tmp_df

# function to print portfolio features
def print_portfolio_stats(df_portfolio_features, myinvmt_df):
  from pyxirr import xirr

  total_booked_amt, reserve_amt, cy_booked_amt, py_booked_amt = get_amt()

  dates = myinvmt_df['Date'].values
  dates = np.append(dates, datetime.date.today().strftime('%d-%b-%y'))
  investment = myinvmt_df['Investment'].values
  dates= pd.to_datetime(dates)

  current = round(sum(df_portfolio_features['Close']*df_portfolio_features['Shares']),0) + reserve_amt
  investment_xirr = np.append(investment, current)
  cagr = round(xirr(pd.DataFrame({"dates": dates, "amounts": investment_xirr}))*100,2)

  investment = -sum(investment)
  invested = round(sum(df_portfolio_features['AvgCost']*df_portfolio_features['Shares']),0) + reserve_amt
  previous = round(sum(df_portfolio_features['Prev_Close']*df_portfolio_features['Shares']),0) + reserve_amt
  cy_invested = investment + py_booked_amt

  today_pnl_amount = current-previous
  today_pnl_percentage = round((current-previous)*100/previous,2)

  curr_pnl_amount = current-invested
  curr_pnl_percentage = round((curr_pnl_amount)*100/(cy_invested),2)

  cy_pnl_amount = cy_booked_amt + curr_pnl_amount
  cy_pnl_percentage = round((cy_pnl_amount)*100/cy_invested,2)

  overall_pnl_amount = total_booked_amt + curr_pnl_amount
  overall_pnl_percentage = round((overall_pnl_amount)*100/investment,2)

  estimate_st = round(sum(df_portfolio_features['FTT']*df_portfolio_features['Shares']),0)  + reserve_amt
  est_st_pnl_amount = estimate_st-current
  est_st_pnl_percentage = round((est_st_pnl_amount)*100/current,2)

  estimate_lt = round(sum(df_portfolio_features['LTT']*df_portfolio_features['Shares']),0)  + reserve_amt
  est_lt_pnl_amount = estimate_lt-current
  est_lt_pnl_percentage = round((est_lt_pnl_amount)*100/current,2)

  total_profit = round(sum(df_portfolio_features[df_portfolio_features['Current P/L%'] > 0]['Current']) - sum(df_portfolio_features[df_portfolio_features['Current P/L%'] > 0]['Investment']),0)
  total_loss = round(sum(df_portfolio_features[df_portfolio_features['Current P/L%'] < 0]['Current']) - sum(df_portfolio_features[df_portfolio_features['Current P/L%'] < 0]['Investment']),0)

  cy_booked_percentage = round((cy_booked_amt)*100/current,2)
  py_booked_percentage = round((py_booked_amt)*100/investment,2)
  total_booked_percentage = round((total_booked_amt)*100/investment,2)

  print('-------------------')
  print('Initial Investment: ', format_amt(investment))
  print('CY Investment: ', format_amt(cy_invested))
  print('Reserve: ', format_amt(reserve_amt))
  print('Current: ',  format_amt(current))
  print('-------------------')
  print('Today PnL: '+ '{} ({}%)'.format(format_amt(today_pnl_amount), today_pnl_percentage))
  print('Current PnL: '+ '{} ({}%)'.format(format_amt(curr_pnl_amount), curr_pnl_percentage))
  print('CY Booked + Current PnL: '+ '{} ({}%)'.format(format_amt(cy_pnl_amount), cy_pnl_percentage))
  print('-------------------')
  print('Total profit: ', format_amt(total_profit))
  print('Total loss: ', format_amt(total_loss))
  print('-------------------')
  print('Total Booked + Current PnL: '+ '{} ({}%)'.format(format_amt(overall_pnl_amount), overall_pnl_percentage))
  print('Total Booked PnL: '+ '{} ({}%)'.format(format_amt(total_booked_amt), total_booked_percentage))
  print('Curr Year Booked PnL: '+ '{} ({}%)'.format(format_amt(cy_booked_amt), cy_booked_percentage))
  print('Prev Year Booked PnL: '+ '{} ({}%)'.format(format_amt(py_booked_amt), py_booked_percentage))
  print('===================')
  print('Est FTT: ',  format_amt(estimate_st))
  print('Est FTT PnL: '+ '{} ({}%)'.format(format_amt(est_st_pnl_amount), est_st_pnl_percentage))

  print('===================')
  print('Deployed: ', format_amt(investment))

  print('Current: ', format_amt(current))

  print('CAGR/XIRR %: '+'{}%'.format(cagr))

In [8]:
# get start and end date
start_date, end_date = get_start_end_date()

# get portfolio and prospects data
mypfs_df = get_mypfs_df()
mypps_df = get_mypps_df()
myinvmt_df = get_myinvmt_df()

# merge above datasets
mypf_df = pd.merge(mypfs_df, mypps_df, on="Symbol")

# seggregate dm and sv portfolio
dm_pf = mypf_df[mypf_df['InPortfolio'] == 'DM']
sv_pf = mypf_df[mypf_df['InPortfolio'] == 'SV']

# build portfolio stock dataframe
dm_stocks = get_stock_ids(dm_pf)
sv_stocks = get_stock_ids(sv_pf)
df_stocks = pd.concat([dm_pf,sv_pf], ignore_index = True)

# arrange common and diff stock features
common_cols = ['Symbol', 'Target', 'Criteria', 'Strategy', 'CumlRnk', 'LatestQtr', 'StarStock', 'Conviction', 'Category', 'InFolio', 'XIRR', 'MBQ']
diff_cols = ['Symbol', 'AvgCost', 'Shares']
df_stocks = arrange_features(df_stocks, common_cols, diff_cols)

# get common features
stock_ids = df_stocks['Symbol'].values
df_common_features = get_common_features(stock_ids, df_stocks)

df_common_features.reset_index(drop=True, inplace=True)
df_common_features.drop(['Date'], axis=1, inplace=True)
# get and print portfolio features
df_portfolio_features = get_portfolio_features(df_common_features)

print_portfolio_stats(df_portfolio_features, myinvmt_df)

df = df_portfolio_features
#plot_pie_chart(df, 'CapType', 'Current')
list_ox40n = list(df[df['MBQ'].str.contains('OX40N', na=False)]['Symbol'].values)

Run date time (IST): 2026-08-04 16:06:53
-------------------
qualified stocks: 90
with latest results: 31
still star stocks: 20
-------------------
Initial Investment:  1.40 C
CY Investment:  1.82 C
Reserve:  6.53 L
Current:  1.55 C
-------------------
Today PnL: -2.79 K (-0.02%)
Current PnL: -29.45 L (-16.15%)
CY Booked + Current PnL: -25.81 L (-14.15%)
-------------------
Total profit:  4.34 L
Total loss:  -33.79 L
-------------------
Total Booked + Current PnL: 17.06 L (12.23%)
Total Booked PnL: 46.51 L (33.34%)
Curr Year Booked PnL: 3.64 L (2.34%)
Prev Year Booked PnL: 42.87 L (30.73%)
===================
Est FTT:  2.55 C
Est FTT PnL: 99.25 L (63.92%)
===================
Deployed:  1.40 C
Current:  1.55 C
CAGR/XIRR %: 4.74%

In [9]:
# top 5 near their targets
cols = ['Symbol', 'Today P/L%', 'Current P/L%', 'FTT%', 'OTT%', 'FTT Amt', 'Current P/L', 'Current', 'FTT', 'Dev%_PE', 'RSI_14','Conviction', 'Spread%',  'CumlRnk', 'RRR Ind', 'CurrAlloc%', 'Gained%', 'Criteria', 'Strategy', 'Category']
df_tmp = df_portfolio_features[~df_portfolio_features['Symbol'].isin(['ENRIN','BLUSPRING','DIGITIDE'])]
df_tmp = df_tmp.sort_values(by = 'FTT Amt', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
71,SONACOMS,0.25,36.15,1.87,38.69,2575.0,36566.0,137725.0,801.69,7.89,83.0,M-MC,30.42,193.0,14.20,0.93,95.40,AR,ATH,AUTO
58,PIDILITIND,-1.37,14.80,2.37,17.52,3839.0,20890.0,162000.0,1658.32,-19.59,58.0,X-LC,8.45,5.0,5.44,1.09,28.11,X40,ATH,CHEMICALS
55,MEDANTA,2.10,22.76,3.55,27.12,7693.0,40183.0,216700.0,1486.00,19.06,69.0,X-SC,13.63,87.0,5.22,1.46,49.32,XY24,NTT,HEALTHCARE
52,M&M,0.13,11.40,9.61,22.10,14846.0,15804.0,154485.0,3762.88,-5.74,69.0,X-LC,6.47,25.0,1.06,1.04,18.35,X40N,ATH,AUTO
81,TTKPRESTIG,-1.68,-18.00,22.07,0.09,18238.0,-18142.0,82635.0,770.00,91.89,50.0,M-SC,13.23,250.0,-0.99,0.56,48.73,OX40N,NTT,DURABLES

In [10]:
# top 5 today
df_tmp = df_portfolio_features.sort_values(by = 'Today P/L%', ascending=False)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
18,COFFEEDAY,10.23,-43.13,137.88,35.27,89029.0,-48979.0,64570.0,80.00,-55.73,63.0,L-SC,5.04,266.0,-0.55,0.43,59.23,XR,NTT,HOTELS
5,ATULAUTO,8.22,-3.79,51.31,45.57,97310.0,-7480.0,189652.0,844.00,4121.62,76.0,M-SC,6.00,248.0,-0.08,1.28,45.94,XY24,NTT,AUTO
3,ALKYLAMINE,7.59,-18.18,135.31,92.54,111782.0,-18351.0,82612.0,4520.85,-12.41,61.0,H-SC,13.10,142.0,-0.16,0.56,56.87,SR,ATH,CHEMICALS
84,VALIANTORG,3.84,-39.58,188.22,74.15,186065.0,-64750.0,98855.0,838.00,-277.79,66.0,H-SC,4.45,145.0,-0.35,0.66,47.11,XR,NTT,CHEMICALS
29,GREENPANEL,3.53,-46.73,168.73,43.14,164540.0,-85561.0,97517.0,537.00,118.35,59.0,M-SC,12.04,225.0,-0.52,0.66,17.44,XY24,NTT,MISC

In [11]:
# bottom 5 today
df_tmp = df_portfolio_features.sort_values(by = 'Today P/L%', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
20,DABUR,-3.79,-19.91,79.42,43.70,157792.0,-49388.0,198680.0,735.00,-27.23,37.0,X-MC,8.80,70.0,-0.31,1.34,1.10,XY24,BTT,FMCG
19,COLPAL,-3.23,-23.68,83.25,39.86,167332.0,-62365.0,201000.0,3683.41,-7.64,42.0,X-MC,1.71,62.0,-0.37,1.35,13.70,XY25,ATH,FMCG
35,HDFCLIFE,-3.10,-12.34,51.40,32.71,67492.0,-18492.0,131308.0,811.41,-31.58,36.0,X-LC,15.99,31.0,-0.27,0.88,0.00,X40,ATH,INSURANCE
59,QUESS,-2.86,32.50,31.25,73.90,44218.0,34703.0,141496.0,424.00,-28.93,72.0,X-SC,37.51,80.0,0.78,0.95,92.89,XY24,NTT,MISC
54,MASFIN,-2.83,-4.85,27.77,21.57,25889.0,-4755.0,93225.0,397.04,-17.80,45.0,H-SC,1.62,167.0,-0.18,0.63,11.12,XR,ATH,FINANCE

In [12]:
# top 5 to exit based on CumlRnk
df_tmp = df_portfolio_features[~df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])]
df_tmp = df_tmp[(df_tmp['Current P/L%'] > -1) & (df_tmp['Current P/L%'] < 1)].sort_values(by = 'CumlRnk', ascending=False)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
62,RECLTD,-0.03,-0.38,21.2,20.74,42909.0,-770.0,202400.0,446.0,9.37,61.0,M-MC,2.65,191.0,-0.02,1.36,22.0,XY25,NTT,FINANCE

In [13]:
# OX40N stocks to exit
df_tmp = df_portfolio_features[(df_portfolio_features['Symbol'].isin(list_ox40n))].sort_values(by = 'Current P/L%', ascending=False)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
25,FINCABLES,0.57,25.80,65.27,107.91,121231.0,38094.0,185738.0,1641.55,13.14,42.0,M-SC,18.93,220.0,0.31,1.25,39.74,OX40N,ATH,CABLES
70,SIS,1.81,-1.23,22.78,21.26,24981.0,-1369.0,109663.0,528.00,2617.62,50.0,H-SC,23.60,168.0,-0.05,0.74,63.05,OX40N,NTT,MISC
16,CERA,2.86,-17.61,50.37,23.89,72998.0,-30980.0,144923.0,9475.00,-20.53,57.0,H-SC,13.20,153.0,-0.42,0.97,40.88,OX40N,NTT,CERAMICS
81,TTKPRESTIG,-1.68,-18.00,22.07,0.09,18238.0,-18142.0,82635.0,770.00,91.89,50.0,M-SC,13.23,250.0,-0.99,0.56,48.73,OX40N,NTT,DURABLES
43,INDIGOPNTS,-2.03,-22.63,29.27,0.02,39532.0,-39498.0,135061.0,1408.00,105.92,57.0,M-SC,4.20,222.0,-1.00,0.91,53.24,OX40N,NTT,PAINTS

In [14]:
# top 5 to book for rotation
df_tmp = df_portfolio_features[(df_portfolio_features['Current P/L%'] > 20) ].sort_values(by = 'CumlRnk', ascending=False)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
25,FINCABLES,0.57,25.80,65.27,107.91,121231.0,38094.0,185738.0,1641.55,13.14,42.0,M-SC,18.93,220.0,0.31,1.25,39.74,OX40N,ATH,CABLES
71,SONACOMS,0.25,36.15,1.87,38.69,2575.0,36566.0,137725.0,801.69,7.89,83.0,M-MC,30.42,193.0,14.20,0.93,95.40,AR,ATH,AUTO
55,MEDANTA,2.10,22.76,3.55,27.12,7693.0,40183.0,216700.0,1486.00,19.06,69.0,X-SC,13.63,87.0,5.22,1.46,49.32,XY24,NTT,HEALTHCARE
59,QUESS,-2.86,32.50,31.25,73.90,44218.0,34703.0,141496.0,424.00,-28.93,72.0,X-SC,37.51,80.0,0.78,0.95,92.89,XY24,NTT,MISC

In [15]:
# top 5 to monitor for exit
df_tmp = df_portfolio_features[~df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])]
df_tmp = df_tmp[(df_tmp['Current P/L%'] > 0) ].sort_values(by = 'Dev%_PE', ascending=False)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
72,STARHEALTH,-2.21,13.73,29.49,47.26,94282.0,38586.0,319709.0,761.00,79.42,52.0,H-SC,18.64,173.0,0.41,2.15,38.23,XY24,NTT,INSURANCE
25,FINCABLES,0.57,25.80,65.27,107.91,121231.0,38094.0,185738.0,1641.55,13.14,42.0,M-SC,18.93,220.0,0.31,1.25,39.74,OX40N,ATH,CABLES
71,SONACOMS,0.25,36.15,1.87,38.69,2575.0,36566.0,137725.0,801.69,7.89,83.0,M-MC,30.42,193.0,14.20,0.93,95.40,AR,ATH,AUTO
89,ZYDUSLIFE,0.80,19.16,13.72,35.51,34263.0,40156.0,249730.0,1285.01,3.60,54.0,H-MC,16.40,120.0,1.17,1.68,31.42,AR,ATH,PHARMA

In [16]:
# top 5 to book for rotation from weak conviction
df_tmp = df_portfolio_features[~df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])]
df_tmp = df_tmp[~df_tmp['Criteria'].isin(['XY25','XY24','X40', 'X40N'])].sort_values(by = 'RRR Ind', ascending=False)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
71,SONACOMS,0.25,36.15,1.87,38.69,2575.0,36566.0,137725.0,801.69,7.89,83.0,M-MC,30.42,193.0,14.20,0.93,95.40,AR,ATH,AUTO
89,ZYDUSLIFE,0.80,19.16,13.72,35.51,34263.0,40156.0,249730.0,1285.01,3.60,54.0,H-MC,16.40,120.0,1.17,1.68,31.42,AR,ATH,PHARMA
25,FINCABLES,0.57,25.80,65.27,107.91,121231.0,38094.0,185738.0,1641.55,13.14,42.0,M-SC,18.93,220.0,0.31,1.25,39.74,OX40N,ATH,CABLES
70,SIS,1.81,-1.23,22.78,21.26,24981.0,-1369.0,109663.0,528.00,2617.62,50.0,H-SC,23.60,168.0,-0.05,0.74,63.05,OX40N,NTT,MISC
3,ALKYLAMINE,7.59,-18.18,135.31,92.54,111782.0,-18351.0,82612.0,4520.85,-12.41,61.0,H-SC,13.10,142.0,-0.16,0.56,56.87,SR,ATH,CHEMICALS

In [17]:
# top 5 to accumulate based on lowest RSI_14
df_tmp = df_portfolio_features[df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])].sort_values(by = 'RSI_14', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
85,VBL,-1.35,-11.32,52.49,35.22,147015.0,-35760.0,280082.0,669.42,-21.70,35.0,X-LC,7.74,13.0,-0.24,1.88,15.24,X40N,ATH,FMCG
35,HDFCLIFE,-3.10,-12.34,51.40,32.71,67492.0,-18492.0,131308.0,811.41,-31.58,36.0,X-LC,15.99,31.0,-0.27,0.88,0.00,X40,ATH,INSURANCE
20,DABUR,-3.79,-19.91,79.42,43.70,157792.0,-49388.0,198680.0,735.00,-27.23,37.0,X-MC,8.80,70.0,-0.31,1.34,1.10,XY24,BTT,FMCG
34,HDFCBANK,-1.46,-11.23,44.61,28.37,93013.0,-26383.0,208502.0,1073.00,-24.48,38.0,X-LC,10.05,26.0,-0.28,1.40,3.11,X40,BTT,BANKS
57,PGHH,-0.11,-35.26,103.91,32.01,143637.0,-75288.0,138232.0,17616.87,-56.25,40.0,X-MC,19.19,57.0,-0.52,0.93,1.92,X40,ATH,FMCG

In [18]:
# top 5 to accumulate based on Spread and CumlRnk
df_tmp = df_portfolio_features[df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])]
df_tmp = df_tmp[(df_tmp['CumlRnk'] < 100)].sort_values(by = 'Spread%', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
19,COLPAL,-3.23,-23.68,83.25,39.86,167332.0,-62365.0,201000.0,3683.41,-7.64,42.0,X-MC,1.71,62.0,-0.37,1.35,13.70,XY25,ATH,FMCG
11,BERGEPAINT,2.57,-1.63,27.39,25.32,69449.0,-4194.0,253555.0,680.00,-7.06,64.0,X-MC,1.87,68.0,-0.06,1.70,31.97,XY24,NTT,PAINTS
8,BAJAJHLDNG,-1.07,2.60,24.39,27.63,47579.0,4950.0,195075.0,14274.15,-5.41,69.0,X-LC,2.05,28.0,0.10,1.31,32.83,X40,ATH,FINANCE
23,DMART,0.20,-3.29,34.02,29.60,82117.0,-8220.0,241380.0,5391.45,-18.44,50.0,X-LC,2.98,14.0,-0.10,1.62,10.33,X40N,ATH,FMCG
17,CIPLA,-0.98,18.20,12.89,33.43,23336.0,27879.0,181040.0,1648.14,-8.67,57.0,X-LC,3.08,18.0,1.19,1.22,23.59,X40N,ATH,PHARMA

In [19]:
# top 5 to accumulate based on lowest Gained%
df_tmp = df_portfolio_features[df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])].sort_values(by = 'Gained%', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
35,HDFCLIFE,-3.10,-12.34,51.40,32.71,67492.0,-18492.0,131308.0,811.41,-31.58,36.0,X-LC,15.99,31.0,-0.27,0.88,0.00,X40,ATH,INSURANCE
20,DABUR,-3.79,-19.91,79.42,43.70,157792.0,-49388.0,198680.0,735.00,-27.23,37.0,X-MC,8.80,70.0,-0.31,1.34,1.10,XY24,BTT,FMCG
57,PGHH,-0.11,-35.26,103.91,32.01,143637.0,-75288.0,138232.0,17616.87,-56.25,40.0,X-MC,19.19,57.0,-0.52,0.93,1.92,X40,ATH,FMCG
64,RELIANCE,-2.13,-17.14,51.21,25.30,85278.0,-34437.0,166526.0,1952.00,-19.26,48.0,X-LC,7.86,21.0,-0.40,1.12,2.55,XY25,BTT,REFINERIES
34,HDFCBANK,-1.46,-11.23,44.61,28.37,93013.0,-26383.0,208502.0,1073.00,-24.48,38.0,X-LC,10.05,26.0,-0.28,1.40,3.11,X40,BTT,BANKS

In [20]:
# top 5 to accumulate based on lowest CurrAlloc%
df_tmp = df_portfolio_features[df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])].sort_values(by = 'CurrAlloc%', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
10,BATAINDIA,1.93,-54.23,195.40,35.20,115077.0,-69777.0,58893.0,2096.00,-22.74,60.0,X-SC,15.68,91.0,-0.61,0.40,18.32,X40,NTT,FOOTWEAR
63,RELAXO,0.66,-47.34,189.23,52.31,144649.0,-68719.0,76441.0,1176.00,-43.96,55.0,X-SC,9.90,92.0,-0.48,0.51,70.91,X40N,NTT,FOOTWEAR
35,HDFCLIFE,-3.10,-12.34,51.40,32.71,67492.0,-18492.0,131308.0,811.41,-31.58,36.0,X-LC,15.99,31.0,-0.27,0.88,0.00,X40,ATH,INSURANCE
57,PGHH,-0.11,-35.26,103.91,32.01,143637.0,-75288.0,138232.0,17616.87,-56.25,40.0,X-MC,19.19,57.0,-0.52,0.93,1.92,X40,ATH,FMCG
28,GODREJCP,-2.55,-5.30,38.82,31.47,54636.0,-7873.0,140741.0,1469.04,-0.47,49.0,X-LC,5.40,32.0,-0.14,0.95,7.99,X40N,ATH,FMCG

In [21]:
# top 5 to accumulate based on CumlRnk
df_tmp = df_portfolio_features.sort_values(by = 'CumlRnk', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
47,ITC,0.70,-23.88,56.40,19.06,146044.0,-81222.0,258944.0,452.00,-58.35,58.0,X-LC,12.08,1.0,-0.56,1.74,4.88,X40,NTT,FMCG
77,TCS,-0.55,-27.78,71.98,24.20,240816.0,-128713.0,334560.0,4230.71,-38.71,68.0,X-LC,16.27,2.0,-0.53,2.25,24.76,X40,ATH,IT
45,INFY,-1.06,-20.52,68.91,34.24,171364.0,-64210.0,248678.0,1972.00,-37.59,62.0,X-LC,17.18,3.0,-0.37,1.67,18.49,X40,NTT,IT
79,TMPV,-0.21,-20.66,72.14,36.58,203670.0,-73515.0,282326.0,600.00,-83.62,57.0,X-LC,6.22,4.0,-0.36,1.90,18.65,XY24,NTT,AUTO
58,PIDILITIND,-1.37,14.80,2.37,17.52,3839.0,20890.0,162000.0,1658.32,-19.59,58.0,X-LC,8.45,5.0,5.44,1.09,28.11,X40,ATH,CHEMICALS

In [22]:
# top 5 for average up
df_tmp = df_portfolio_features[(df_portfolio_features['Dev%_200'] > 5)].sort_values(by = 'CurrAlloc%', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
44,INDUSINDBK,-0.28,-24.25,75.44,32.89,44119.0,-18724.0,58482.0,1800.00,-375.21,58.0,L-MC,14.29,258.0,-0.42,0.39,44.18,XR,NTT,BANKS
18,COFFEEDAY,10.23,-43.13,137.88,35.27,89029.0,-48979.0,64570.0,80.00,-55.73,63.0,L-SC,5.04,266.0,-0.55,0.43,59.23,XR,NTT,HOTELS
63,RELAXO,0.66,-47.34,189.23,52.31,144649.0,-68719.0,76441.0,1176.00,-43.96,55.0,X-SC,9.90,92.0,-0.48,0.51,70.91,X40N,NTT,FOOTWEAR
3,ALKYLAMINE,7.59,-18.18,135.31,92.54,111782.0,-18351.0,82612.0,4520.85,-12.41,61.0,H-SC,13.10,142.0,-0.16,0.56,56.87,SR,ATH,CHEMICALS
81,TTKPRESTIG,-1.68,-18.00,22.07,0.09,18238.0,-18142.0,82635.0,770.00,91.89,50.0,M-SC,13.23,250.0,-0.99,0.56,48.73,OX40N,NTT,DURABLES

In [23]:
# top 5 RSP
df_tmp = df_portfolio_features.sort_values(by = 'RSP', ascending=False)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
33,HCLTECH,-0.52,-11.10,35.30,20.28,75921.0,-26850.0,215074.0,1853.42,-6.53,76.0,X-LC,14.52,8.0,-0.35,1.45,33.81,X40,ATH,IT
77,TCS,-0.55,-27.78,71.98,24.20,240816.0,-128713.0,334560.0,4230.71,-38.71,68.0,X-LC,16.27,2.0,-0.53,2.25,24.76,X40,ATH,IT
71,SONACOMS,0.25,36.15,1.87,38.69,2575.0,36566.0,137725.0,801.69,7.89,83.0,M-MC,30.42,193.0,14.20,0.93,95.40,AR,ATH,AUTO
13,BSOFT,0.53,-41.40,153.59,48.59,126583.0,-58237.0,82416.0,819.60,-25.01,65.0,H-SC,19.06,172.0,-0.46,0.55,20.49,XR,ATH,IT
83,VAIBHAVGBL,1.40,-16.65,92.89,60.77,141505.0,-30439.0,152336.0,521.00,75.76,64.0,H-SC,11.51,160.0,-0.22,1.02,54.99,XR,NTT,JEWELLERY

In [24]:
# Top N allocation
df_tmp = df_portfolio_features.sort_values(by = 'CurrAlloc%', ascending=False)
top_n_values = [10, 25, 50]

sum_df = pd.DataFrame({
    'Top_N': top_n_values,
    'Sum_Alloc%': [df_tmp['CurrAlloc%'].head(n).sum() for n in top_n_values]
})

sum_df

   Top_N  Sum_Alloc%
0     10       19.13
1     25       42.74
2     50       73.69

In [25]:
# market-cap-wise allocation
df_tmp = df_portfolio_features[cols]
df_tmp.groupby(df_tmp['Conviction'].str[-2:])['CurrAlloc%'].sum().sort_values(ascending=False)

Conviction
SC    42.26
LC    32.06
MC    25.66
Name: CurrAlloc%, dtype: float64

In [26]:
# criteria-wise allocation
df_portfolio_features.groupby('Criteria')['CurrAlloc%'].sum().sort_values(ascending=False)

Criteria
X40      26.10
XY24     26.05
X40N     16.50
XR        9.26
AR        7.40
OX40N     7.17
XY25      6.58
SR        0.92
Name: CurrAlloc%, dtype: float64

In [27]:
# conviction-wise allocation
df_portfolio_features.groupby('Conviction')['CurrAlloc%'].sum().sort_values(ascending=False)

Conviction
X-LC    29.85
H-SC    20.65
X-MC    20.18
X-SC    10.64
M-SC    10.39
H-MC     2.80
M-MC     2.29
H-LC     1.34
M-LC     0.87
L-SC     0.58
L-MC     0.39
Name: CurrAlloc%, dtype: float64

In [28]:
# sector-wise stats
df_tmp = df_portfolio_features.groupby('Category')[['CurrAlloc%', 'Current', 'Current P/L', 'FTT Amt']].sum().sort_values(by=['Current', 'Current P/L'], ascending=False)
df_tmp['Current P/L%'] = round(df_tmp['Current P/L'] * 100 / df_tmp['Current'], 2)
df_tmp['FTT%'] = round(df_tmp['FTT Amt'] * 100 / df_tmp['Current'], 2)
cols = ['CurrAlloc%', 'Current P/L%', 'FTT%']
df_tmp[cols].sort_values(by=['CurrAlloc%'], ascending=False)

               CurrAlloc%  Current P/L%    FTT%
Category
FMCG                14.34        -24.10   67.62
IT                  11.10        -36.51  103.97
FINANCE              9.06        -16.27   64.91
MISC                 7.64        -18.15   68.85
AUTO                 7.42          0.65   36.39
PAINTS               5.71        -15.84   35.59
BANKS                5.46        -11.72   63.35
PHARMA               5.44          8.48   19.23
INSURANCE            5.33         -4.45   39.68
ELECTRICAL           4.45         -6.64   43.97
CHEMICALS            2.31        -18.11   87.84
HEALTHCARE           2.23         -8.03   36.22
AC                   1.88        -14.22   45.19
APPARELS             1.87          3.55   28.85
FOOTWEAR             1.77        -68.13  135.55
BREWERIES            1.76         10.73    7.80
DURABLES             1.66        -57.08   95.29
TRAVEL               1.55        -93.94  191.05
CERAMICS             1.47        -39.73   82.18
ENGINEERING          1.30        -25.00   82.17
CABLES               1.25         20.51   65.27
JEWELLERY            1.17        -83.01  146.59
REFINERIES           1.12        -20.68   51.21
CEMENT               1.12        -61.36  182.08
ENTERTAINMENT        0.73        -76.60  181.92
HOTELS               0.43        -75.85  137.88
TEXTILES             0.41        -49.58   92.23

In [29]:
# money to be made criteria-wise
df_portfolio_features.groupby('Criteria')['FTT Amt'].agg(['sum', 'count']).sort_values(by='sum', ascending=False)

                sum  count
Criteria
XY24      3303266.0     20
X40       1781480.0     19
XR        1299247.0     13
AR        1071657.0      9
X40N      1005953.0     12
OX40N      725690.0     10
XY25       457323.0      5
SR         280127.0      2

In [30]:
# money to be made conviction-wise
df_portfolio_features.groupby('Conviction')['FTT Amt'].agg(['sum', 'count']).sort_values(by='sum', ascending=False)

                  sum  count
Conviction
H-SC        3278145.0     23
X-LC        1830009.0     21
X-MC        1452251.0     14
M-SC        1373151.0     14
X-SC        1221344.0      9
H-MC         281614.0      2
L-SC         203804.0      2
M-LC         162418.0      1
M-MC          45484.0      2
L-MC          44119.0      1
H-LC          32404.0      1

In [31]:
# money to be made criteria and conviction-wise
df_portfolio_features.groupby(['Conviction', 'Criteria'])['FTT Amt'].agg(['sum', 'count']).sort_values(by='sum', ascending=False)

                          sum  count
Conviction Criteria
H-SC       XY24      990940.0      5
X-LC       X40       933069.0     10
H-SC       AR        926288.0      5
M-SC       XY24      797582.0      6
H-SC       XR        779079.0      7
X-SC       XY24      715696.0      4
X-MC       X40       633828.0      7
X-LC       X40N      370282.0      6
X-MC       X40N      344606.0      3
X-LC       XY24      324456.0      2
M-SC       OX40N     309204.0      5
H-SC       OX40N     301711.0      4
X-SC       X40N      291065.0      3
H-SC       SR        280127.0      2
H-MC       XY24      247351.0      1
X-MC       XY25      246576.0      2
           XY24      227241.0      2
X-SC       X40       214583.0      2
M-SC       XR        190238.0      2
X-LC       XY25      167838.0      2
M-LC       XR        162418.0      1
L-SC       OX40N     114775.0      1
           XR         89029.0      1
M-SC       AR         76127.0      1
L-MC       XR         44119.0      1
M-MC       XY25       42909.0      1
X-LC       XR         34364.0      1
H-MC       AR         34263.0      1
H-LC       AR         32404.0      1
M-MC       AR          2575.0      1

In [32]:
# notebook execution time

end_time = time.time()
execution_time = round(end_time - start_time, 0)
print(f"Notebook execution time: {execution_time} seconds")

Notebook execution time: 27.0 seconds