<a href="https://colab.research.google.com/github/ankit-rathi/Quantvesting_v2/blob/main/myStocks_Portfolio_Analysis.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
'''
!pip install pandas==2.2.2 -qq
!pip install pyxirr -qq
!pip install ta -qq
!pip install yfinance==0.2.59 -qq
'''

'\n!pip install pandas==2.2.2 -qq\n!pip install pyxirr -qq\n!pip install ta -qq\n!pip install yfinance==0.2.59 -qq\n'

In [2]:
# import libraries

import numpy as np
import pandas as pd
import datetime
import warnings
warnings.filterwarnings('ignore')
import yfinance as yfin
import ta
import matplotlib.pyplot as plt
import requests

In [3]:
# notebook start time
import time
import datetime
import pytz

start_time = time.time()

# function to print date timestamp
def print_date_time():
  tz_NY = pytz.timezone('Asia/Kolkata')
  datetime_NY = datetime.datetime.now(tz_NY)
  print("Run date time (IST):", datetime_NY.strftime("%Y-%m-%d %H:%M:%S"))

In [4]:
# function to get booked and reserved amount
def get_amt():
  # fetch the JSON data from the URL
  url = "https://raw.githubusercontent.com/ankit-rathi/Tradevesting_v1/main/data/myPortfolioAmts.json"
  response = requests.get(url)
  pf_amts = response.json()  # parse the JSON data

  # extract values from the JSON
  py_booked_amt_dm = pf_amts["py_booked_amt_dm"]
  py_booked_amt_sv = pf_amts["py_booked_amt_sv"]
  cy_booked_amt_dm = pf_amts["cy_booked_amt_dm"]
  cy_booked_amt_sv = pf_amts["cy_booked_amt_sv"]
  reserve_amt_dm = pf_amts["reserve_amt_dm"]
  reserve_amt_sv = pf_amts["reserve_amt_sv"]

  # perform calculations
  py_booked_amt = py_booked_amt_dm + py_booked_amt_sv
  cy_booked_amt = cy_booked_amt_dm + cy_booked_amt_sv
  reserve_amt = reserve_amt_dm + reserve_amt_sv
  total_booked_amt = py_booked_amt + cy_booked_amt

  return total_booked_amt, reserve_amt, cy_booked_amt, py_booked_amt

gen_output = 0

In [5]:
# function to format the amount
def format_amt(number):
    abs_number = abs(number)

    if abs_number >= 1_00_00_000:  # Crores
        formatted_amt = f"{number / 1_00_00_000:.2f} C"
    elif abs_number >= 1_00_000:  # Lakhs
        formatted_amt = f"{number / 1_00_000:.2f} L"
    elif abs_number >= 1_000:  # Thousands
        formatted_amt = f"{number / 1_000:.2f} K"
    else:
        formatted_amt = f"{number:.2f}"

    return formatted_amt

# function to set start and end date
def get_start_end_date():
  start_date = (datetime.date.today() + datetime.timedelta(days=-365)).strftime('%Y-%m-%d')
  end_date = (datetime.date.today() + datetime.timedelta(days=1)).strftime('%Y-%m-%d')
  return start_date, end_date

# function to fetch my portfolio csv
def get_mypfs_df():
  mypfs_df = pd.read_csv('https://raw.githubusercontent.com/ankit-rathi/Tradevesting_v1/main/data/myPortfolioStocks.csv')
  return mypfs_df

# function to fetch my prospects csv
def get_mypps_df():
  mypps_df = pd.read_csv('https://raw.githubusercontent.com/ankit-rathi/Tradevesting_v1/main/data/myProspectsScrips.csv')
  return mypps_df

# function to fetch screener data
def get_myscreen_df():
  myscreen_df = pd.read_csv('https://raw.githubusercontent.com/ankit-rathi/Tradevesting_v1/main/data/myScreenerDB.csv')
  return myscreen_df

# function to fetch momentum data
def get_myinvmt_df():
  myinvmt_df = pd.read_csv('https://raw.githubusercontent.com/ankit-rathi/Tradevesting_v1/main/data/myInvestments.csv')
  return myinvmt_df

# function to get the stock ids
def get_stock_ids(df_pf):
  stock_n100 = df_pf['Symbol'].unique()

  exclude = ['CADILAHC','MMTC', 'MASFIN']

  stock_ids = df_pf[~df_pf['Symbol'].isin(exclude) ]['Symbol'].unique()

  #mypf = mypf[mypf.Forecast.notnull()]
  #stock_ids = mypf['Symbol'].unique()

  #stock_ids.sort()
  return stock_ids

# get features from screener data
def get_screener_features():
  myscreen_df = get_myscreen_df()
  cols = ['Symbol', 'EPS', 'MedPE', 'ROCE%', 'ROE%', 'CapType']
  return myscreen_df[cols]

# get relative strength
def get_relative_strength(stock_list):

    # Dictionary to store stock tickers and their corresponding percentage price change
    stock_changes = {}

    # Loop through each stock and fetch its price data
    for stock in stock_list:
        try:
            # Download the stock data for the given date range
            stock_data = yfin.Ticker(stock + '.NS').history(period='1mo', interval='1d')[map(str.title, ['open', 'close', 'low', 'high', 'volume'])]

            # Calculate the percentage change for the stock
            if len(stock_data) > 0:
                start_price = stock_data['Close'].iloc[0]
                end_price = stock_data['Close'].iloc[-1]
                percent_change = round(((end_price - start_price) / start_price) * 100, 2)
                stock_changes[stock] = percent_change
            else:
                stock_changes[stock] = np.nan  # If no data is available, set to NaN

        except Exception as e:
            print(f"Error fetching data for {stock}: {e}")
            stock_changes[stock] = np.nan

    # Create a DataFrame with stock tickers and their percentage changes
    df = pd.DataFrame(list(stock_changes.items()), columns=['Symbol', 'Percent_Change'])

    # Drop any stocks with missing data (NaN values)
    df = df.dropna()

    # Calculate the percentile rank based on percentage change
    df['RSP'] = round(df['Percent_Change'].rank(pct=True) * 100, 2)
    cols = ['Symbol', 'RSP']
    df = df[cols]
    # Sort by percentile rank (optional)
    df = df.sort_values(by='RSP', ascending=False).reset_index(drop=True)

    return df

In [6]:
# function to get stock technicals
def stock_prec_dev(stock_symbol):
    #stock_symbol = 'ULTRACEMCO.NS'
    short_window = 20
    mid_window = 50
    long_window = 200
    moving_avg = 'SMA'

    start = datetime.datetime(*map(int, start_date.split('-')))
    end = datetime.datetime(*map(int, end_date.split('-')))

    stock_df = yfin.Ticker(stock_symbol + '.NS').history(period='max', interval='1d')[map(str.title, ['open', 'close', 'low', 'high', 'volume'])]

    stock_df['Max'] = round(max(stock_df['Close']),2)
    stock_df = stock_df[(stock_df.index <= end_date) & (stock_df.index >= start_date)]
    stock_df['200_SMA'] = round(stock_df['Close'].rolling(window = 200, min_periods = 1).mean(),0)
    stock_df['Dev%_200'] = round((stock_df['Close'] - stock_df['200_SMA'])*100/stock_df['200_SMA'],2)
    stock_df.dropna(axis = 0, inplace = True) # remove any null rows

    stock_df['20_SMA'] = stock_df['Close'].rolling(window=20).mean()
    stock_df['50_SMA'] = stock_df['Close'].rolling(window=50).mean()
    stock_df['Symbol'] = stock_symbol

    stock_df['Close'] = round(stock_df['Close'],2)
    stock_df['Min'] = round(min(stock_df['Close']),2)
    stock_df['RSI_14'] = ta.momentum.RSIIndicator(close=stock_df['Close'], window=14).rsi()
    stock_df['RSI_14'] = round(stock_df['RSI_14'],0)
    stock_df['Prev_Close'] = stock_df['Close'].shift(1)
    stock_df.drop(['Open', 'Low', 'High', 'Volume'], axis=1, inplace=True)
    stock_df = stock_df.tail(1)

    max_SMA = max(stock_df['20_SMA'].item(), stock_df['50_SMA'].item(), stock_df['200_SMA'].item())
    min_SMA = min(stock_df['20_SMA'].item(), stock_df['50_SMA'].item(), stock_df['200_SMA'].item())
    ABS_Spread = max_SMA - min_SMA
    stock_df['Spread%'] = round((ABS_Spread / stock_df['200_SMA'].item()) * 100,2)

    return stock_df

# function to compute stock attributes
def get_common_features(stock_ids, df_mypf):

  df_prec_dev = pd.DataFrame()
  df_tmp = get_screener_features()
  df_rs = get_relative_strength(stock_ids)

  for stock_id in stock_ids:
      tmp = stock_prec_dev(stock_id)
      tmp = tmp.reset_index()
      df_prec_dev = pd.concat([df_prec_dev, tmp], ignore_index = True)
  df_prec_dev = pd.merge(df_prec_dev, df_mypf, on= 'Symbol')
  df_prec_dev = pd.merge(df_prec_dev, df_tmp, on= 'Symbol', how='left')
  df_prec_dev = pd.merge(df_prec_dev, df_rs, on= 'Symbol', how='left')
  #print(df_prec_dev.columns)
  df_prec_dev['Curr_PE'] = round(df_prec_dev['Close']/df_prec_dev['EPS'],1)
  df_prec_dev['Dev%_PE'] = round((df_prec_dev['Curr_PE'] - df_prec_dev['MedPE'])*100/df_prec_dev['MedPE'],2)
  df_prec_dev['Conviction'] = df_prec_dev['Conviction'] + '-' + df_prec_dev['CapType']
  return df_prec_dev

# function to arrange stock features
def arrange_features(df_stocks, common_cols, diff_cols):
  df_stocks_common = df_stocks[common_cols].drop_duplicates()
  df_stocks_diff = df_stocks[diff_cols]
  df_stocks_diff['Investment'] = df_stocks_diff['AvgCost'] * df_stocks_diff['Shares']
  df_stocks_diff = df_stocks_diff.groupby(['Symbol'])[['Shares', 'Investment']].aggregate(['sum']).reset_index()
  df_stocks_diff.columns = ['Symbol', 'Shares', 'Investment']
  df_stocks_diff['AvgCost'] = round(df_stocks_diff['Investment']/df_stocks_diff['Shares'],2)
  df_stocks = pd.merge(df_stocks_diff, df_stocks_common, on='Symbol')
  return df_stocks

# plot fact distribution across dimension
def plot_pie_chart(df, dimension, fact):
  # grouping the data by category and calculating the sum of fact for each type
  grouped_data = df.groupby(dimension)[fact].sum()

  # sorting the grouped data in descending order
  grouped_data = grouped_data.sort_values(ascending=False)

  # creating a pie chart
  grouped_data.plot.pie(autopct='%1.1f%%', startangle=90, figsize=(6, 6))

  # adding a title and displaying the plot
  plt.title(f'{dimension} {fact} Distribution')
  plt.ylabel('')  # To hide the y-label
  plt.show()

In [7]:
# function to get portfolio features

def get_portfolio_features(df_common_features):

  print_date_time()
  print('-------------------')

  #df_common_features["Target"] = df_common_features["Target"].fillna(df_common_features["Max"])
  df_common_features['NTT'] = np.where(df_common_features['Strategy']== 'NTT', df_common_features["Target"], df_common_features['Max'])
  df_common_features['LTT'] = np.where(df_common_features['Strategy']== 'BTT', df_common_features["Target"], df_common_features['Max'])
  df_common_features['BOL'] = df_common_features['Min']

  tmp_df = df_common_features[df_common_features['Symbol'].isin(mypf_df[mypf_df['InPortfolio'] != 'NA'].Symbol.values)]
  print('qualified stocks: '+str(len(tmp_df['Symbol'].unique())))
  tmp_df1 = tmp_df[tmp_df['LatestQtr'] == 1]
  print('with latest results: '+str(len(tmp_df1['Symbol'].unique())))
  tmp_df1 = tmp_df1[tmp_df1['StarStock'] == 1]
  print('still star stocks: '+str(len(tmp_df1['Symbol'].unique())))
  tmp_df['Investment'] = tmp_df['AvgCost'] * tmp_df['Shares']
  tmp_df['Current'] = round(tmp_df['Close'] * tmp_df['Shares'],0)
  tmp_df['Previous'] = tmp_df['Prev_Close'] * tmp_df['Shares']
  tmp_df['EstimatedST'] = tmp_df['NTT'] * tmp_df['Shares']
  tmp_df['EstimatedLT'] = tmp_df['LTT'] * tmp_df['Shares']
  tmp_df['Current P/L'] = round((tmp_df['Current'] - tmp_df['Investment']),0)
  tmp_df['Today P/L%'] = round((tmp_df['Current'] - tmp_df['Previous'])*100/tmp_df['Previous'],2)
  tmp_df['Current P/L%'] = round((tmp_df['Current'] - tmp_df['Investment'])*100/tmp_df['Investment'],2)
  tmp_df['EstimatedST P/L%'] = round((tmp_df['EstimatedST'] - tmp_df['Investment'])*100/tmp_df['Investment'],2)
  tmp_df['EstimatedLT P/L%'] = round((tmp_df['EstimatedLT'] - tmp_df['Investment'])*100/tmp_df['Investment'],2)
  tmp_df['NTT%'] = round((tmp_df['NTT'] - tmp_df['Close'])*100/tmp_df['Close'],2)
  tmp_df['LTT%'] = round((tmp_df['LTT'] - tmp_df['Close'])*100/tmp_df['Close'],2)
  tmp_df['Gained%'] = round((tmp_df['Close'] - tmp_df['BOL'])*100/tmp_df['BOL'],2)
  investment = round(sum(tmp_df['AvgCost']*tmp_df['Shares']),0)
  current = round(sum(tmp_df['Close']*tmp_df['Shares']),0)
  tmp_df['InitAlloc%'] = round(tmp_df['Investment']*100/investment,2)
  tmp_df['CurrAlloc%'] = round(tmp_df['Current']*100/current,2)
  tmp_df['FTT'] = tmp_df['LTT']
  tmp_df.loc[tmp_df['Strategy'] == 'NTT', 'FTT'] = tmp_df['NTT']
  tmp_df['FTT%'] = tmp_df['LTT%']
  tmp_df.loc[tmp_df['Strategy'] == 'NTT', 'FTT%'] = tmp_df['NTT%']
  tmp_df['FTT Amt'] = round(tmp_df['FTT%'] * tmp_df['Current']/100,0)
  tmp_df['OTT%'] = round((tmp_df['FTT'] - tmp_df['AvgCost'])*100/tmp_df['AvgCost'],2)
  tmp_df['RRR Ind'] = round(tmp_df['Current P/L']/tmp_df['FTT Amt'],2)
  tmp_df['Risk Ind'] = round(tmp_df['Current P/L%']*tmp_df['CurrAlloc%'],0)

  return tmp_df

# function to print portfolio features
def print_portfolio_stats(df_portfolio_features, myinvmt_df):
  from pyxirr import xirr

  total_booked_amt, reserve_amt, cy_booked_amt, py_booked_amt = get_amt()

  dates = myinvmt_df['Date'].values
  dates = np.append(dates, datetime.date.today().strftime('%d-%b-%y'))
  investment = myinvmt_df['Investment'].values
  dates= pd.to_datetime(dates)

  current = round(sum(df_portfolio_features['Close']*df_portfolio_features['Shares']),0) + reserve_amt
  investment_xirr = np.append(investment, current)
  cagr = round(xirr(pd.DataFrame({"dates": dates, "amounts": investment_xirr}))*100,2)

  investment = -sum(investment)
  invested = round(sum(df_portfolio_features['AvgCost']*df_portfolio_features['Shares']),0) + reserve_amt
  previous = round(sum(df_portfolio_features['Prev_Close']*df_portfolio_features['Shares']),0) + reserve_amt
  cy_invested = investment + py_booked_amt

  today_pnl_amount = current-previous
  today_pnl_percentage = round((current-previous)*100/previous,2)

  curr_pnl_amount = current-invested
  curr_pnl_percentage = round((curr_pnl_amount)*100/(cy_invested),2)

  cy_pnl_amount = cy_booked_amt + curr_pnl_amount
  cy_pnl_percentage = round((cy_pnl_amount)*100/cy_invested,2)

  overall_pnl_amount = total_booked_amt + curr_pnl_amount
  overall_pnl_percentage = round((overall_pnl_amount)*100/investment,2)

  estimate_st = round(sum(df_portfolio_features['FTT']*df_portfolio_features['Shares']),0)  + reserve_amt
  est_st_pnl_amount = estimate_st-current
  est_st_pnl_percentage = round((est_st_pnl_amount)*100/current,2)

  estimate_lt = round(sum(df_portfolio_features['LTT']*df_portfolio_features['Shares']),0)  + reserve_amt
  est_lt_pnl_amount = estimate_lt-current
  est_lt_pnl_percentage = round((est_lt_pnl_amount)*100/current,2)

  total_profit = round(sum(df_portfolio_features[df_portfolio_features['Current P/L%'] > 0]['Current']) - sum(df_portfolio_features[df_portfolio_features['Current P/L%'] > 0]['Investment']),0)
  total_loss = round(sum(df_portfolio_features[df_portfolio_features['Current P/L%'] < 0]['Current']) - sum(df_portfolio_features[df_portfolio_features['Current P/L%'] < 0]['Investment']),0)

  cy_booked_percentage = round((cy_booked_amt)*100/current,2)
  py_booked_percentage = round((py_booked_amt)*100/investment,2)
  total_booked_percentage = round((total_booked_amt)*100/investment,2)

  print('-------------------')
  print('Initial Investment: ', format_amt(investment))
  print('CY Investment: ', format_amt(cy_invested))
  print('Reserve: ', format_amt(reserve_amt))
  print('Current: ',  format_amt(current))
  print('-------------------')
  print('Today PnL: '+ '{} ({}%)'.format(format_amt(today_pnl_amount), today_pnl_percentage))
  print('Current PnL: '+ '{} ({}%)'.format(format_amt(curr_pnl_amount), curr_pnl_percentage))
  print('CY Booked + Current PnL: '+ '{} ({}%)'.format(format_amt(cy_pnl_amount), cy_pnl_percentage))
  print('-------------------')
  print('Total profit: ', format_amt(total_profit))
  print('Total loss: ', format_amt(total_loss))
  print('-------------------')
  print('Total Booked + Current PnL: '+ '{} ({}%)'.format(format_amt(overall_pnl_amount), overall_pnl_percentage))
  print('Total Booked PnL: '+ '{} ({}%)'.format(format_amt(total_booked_amt), total_booked_percentage))
  print('Curr Year Booked PnL: '+ '{} ({}%)'.format(format_amt(cy_booked_amt), cy_booked_percentage))
  print('Prev Year Booked PnL: '+ '{} ({}%)'.format(format_amt(py_booked_amt), py_booked_percentage))
  print('===================')
  print('Est FTT: ',  format_amt(estimate_st))
  print('Est FTT PnL: '+ '{} ({}%)'.format(format_amt(est_st_pnl_amount), est_st_pnl_percentage))

  print('===================')
  print('Deployed: ', format_amt(investment))

  print('Current: ', format_amt(current))

  print('CAGR/XIRR %: '+'{}%'.format(cagr))

In [8]:
# get start and end date
start_date, end_date = get_start_end_date()

# get portfolio and prospects data
mypfs_df = get_mypfs_df()
mypps_df = get_mypps_df()
myinvmt_df = get_myinvmt_df()

# merge above datasets
mypf_df = pd.merge(mypfs_df, mypps_df, on="Symbol")

# seggregate dm and sv portfolio
dm_pf = mypf_df[mypf_df['InPortfolio'] == 'DM']
sv_pf = mypf_df[mypf_df['InPortfolio'] == 'SV']

# build portfolio stock dataframe
dm_stocks = get_stock_ids(dm_pf)
sv_stocks = get_stock_ids(sv_pf)
df_stocks = pd.concat([dm_pf,sv_pf], ignore_index = True)

# arrange common and diff stock features
common_cols = ['Symbol', 'Target', 'Criteria', 'Strategy', 'CumlRnk', 'LatestQtr', 'StarStock', 'Conviction', 'Category', 'InFolio', 'XIRR', 'MBQ']
diff_cols = ['Symbol', 'AvgCost', 'Shares']
df_stocks = arrange_features(df_stocks, common_cols, diff_cols)

# get common features
stock_ids = df_stocks['Symbol'].values
df_common_features = get_common_features(stock_ids, df_stocks)

df_common_features.reset_index(drop=True, inplace=True)
df_common_features.drop(['Date'], axis=1, inplace=True)
# get and print portfolio features
df_portfolio_features = get_portfolio_features(df_common_features)

print_portfolio_stats(df_portfolio_features, myinvmt_df)

df = df_portfolio_features
#plot_pie_chart(df, 'CapType', 'Current')
list_ox40n = list(df[df['MBQ'].str.contains('OX40N', na=False)]['Symbol'].values)

Run date time (IST): 2026-05-27 11:50:20
-------------------
qualified stocks: 92
with latest results: 31
still star stocks: 20
-------------------
Initial Investment:  1.40 C
CY Investment:  1.82 C
Reserve:  1.49 K
Current:  1.51 C
-------------------
Today PnL: 84.67 K (0.56%)
Current PnL: -32.11 L (-17.6%)
CY Booked + Current PnL: -30.03 L (-16.46%)
-------------------
Total profit:  2.52 L
Total loss:  -34.63 L
-------------------
Total Booked + Current PnL: 12.84 L (9.21%)
Total Booked PnL: 44.95 L (32.22%)
Curr Year Booked PnL: 2.08 L (1.38%)
Prev Year Booked PnL: 42.87 L (30.73%)
===================
Est FTT:  2.55 C
Est FTT PnL: 1.04 C (69.01%)
===================
Deployed:  1.40 C
Current:  1.51 C
CAGR/XIRR %: 3.84%

In [9]:
# top 5 near their targets
cols = ['Symbol', 'Today P/L%', 'Current P/L%', 'FTT%', 'OTT%', 'FTT Amt', 'Current P/L', 'Current', 'FTT', 'Dev%_PE', 'RSI_14','Conviction', 'Spread%',  'CumlRnk', 'RRR Ind', 'CurrAlloc%', 'Gained%', 'Criteria', 'Strategy', 'Category']
df_tmp = df_portfolio_features[~df_portfolio_features['Symbol'].isin(['ENRIN','BLUSPRING','DIGITIDE'])]
df_tmp = df_tmp.sort_values(by = 'FTT Amt', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
59,PIDILITIND,-0.03,4.75,13.00,18.37,19215.0,6700.0,147810.0,1670.26,-26.64,62.0,X-LC,5.18,5.0,0.35,0.98,16.06,X40,ATH,CHEMICALS
51,KOTAKBANK,0.13,3.98,16.47,21.11,23714.0,5514.0,143986.0,453.24,-10.71,56.0,X-LC,7.50,12.0,0.23,0.95,10.12,X40,ATH,BANKS
55,MASFIN,1.24,-5.08,28.08,21.57,26114.0,-4980.0,93000.0,397.04,-18.25,41.0,H-SC,4.29,167.0,-0.19,0.62,10.85,XR,ATH,FINANCE
17,CIPLA,0.34,15.15,16.97,34.69,29929.0,23204.0,176365.0,1663.60,-10.79,66.0,X-LC,9.65,18.0,0.78,1.17,19.28,X40N,ATH,PHARMA
53,M&M,0.85,1.69,21.34,23.38,30094.0,2340.0,141021.0,3802.40,-13.74,49.0,X-LC,8.92,25.0,0.08,0.93,6.92,X40N,ATH,AUTO

In [10]:
# top 5 today
df_tmp = df_portfolio_features.sort_values(by = 'Today P/L%', ascending=False)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
18,COFFEEDAY,19.26,-48.50,162.64,35.27,95117.0,-55066.0,58483.0,80.00,-59.76,75.0,L-SC,25.52,266.0,-0.58,0.39,44.22,XR,NTT,HOTELS
83,TTKPRESTIG,4.77,-30.16,43.32,0.09,30489.0,-30397.0,70380.0,770.00,63.29,57.0,M-SC,15.58,250.0,-1.00,0.47,25.32,OX40N,NTT,DURABLES
60,QUESS,4.43,-12.35,98.41,73.90,92113.0,-13192.0,93601.0,424.00,-52.62,60.0,X-SC,9.62,80.0,-0.14,0.62,27.60,XY24,NTT,MISC
9,BANDHANBNK,3.63,-0.10,92.61,92.42,257713.0,-281.0,278278.0,400.00,138.51,67.0,H-SC,21.51,174.0,-0.00,1.84,53.30,XY24,NTT,BANKS
26,GILLETTE,3.23,-3.75,34.78,29.72,84990.0,-9531.0,244365.0,10978.86,-26.00,62.0,X-SC,8.32,83.0,-0.11,1.62,12.30,X40,ATH,FMCG

In [11]:
# bottom 5 today
df_tmp = df_portfolio_features.sort_values(by = 'Today P/L%', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
24,EASEMYTRIP,-7.00,-58.94,254.84,45.70,185014.0,-104215.0,72600.0,26.4,-24.63,42.0,M-SC,6.17,204.0,-0.56,0.48,27.18,XY24,NTT,TRAVEL
46,IRCTC,-2.46,-36.85,142.18,52.93,242878.0,-99684.0,170824.0,1269.0,-53.32,39.0,H-MC,15.63,119.0,-0.41,1.13,5.97,XY24,BTT,TRAVEL
34,HDFCBANK,-1.97,-8.65,40.53,28.37,86960.0,-20327.0,214558.0,1073.0,-22.51,45.0,X-LC,16.04,26.0,-0.23,1.42,4.37,X40,BTT,BANKS
70,SHALBY,-1.62,-34.53,91.09,25.10,108020.0,-62557.0,118586.0,327.0,772.41,61.0,M-SC,19.15,236.0,-0.58,0.79,34.95,XY24,NTT,HEALTHCARE
56,MEDANTA,-1.32,3.73,22.55,27.12,41290.0,6586.0,183103.0,1486.0,0.51,56.0,X-SC,8.02,87.0,0.16,1.21,26.17,XY24,NTT,HEALTHCARE

In [12]:
# top 5 to exit based on CumlRnk
df_tmp = df_portfolio_features[~df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])]
df_tmp = df_tmp[(df_tmp['Current P/L%'] > -1) & (df_tmp['Current P/L%'] < 1)].sort_values(by = 'CumlRnk', ascending=False)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
9,BANDHANBNK,3.63,-0.1,92.61,92.42,257713.0,-281.0,278278.0,400.0,138.51,67.0,H-SC,21.51,174.0,-0.0,1.84,53.3,XY24,NTT,BANKS

In [13]:
# OX40N stocks to exit
df_tmp = df_portfolio_features[(df_portfolio_features['Symbol'].isin(list_ox40n))].sort_values(by = 'Current P/L%', ascending=False)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
25,FINCABLES,2.67,41.24,47.20,107.91,98428.0,60889.0,208533.0,1641.55,26.84,66.0,M-SC,26.64,220.0,0.62,1.38,56.89,OX40N,ATH,CABLES
72,SIS,-0.35,-8.82,33.00,21.26,33408.0,-9797.0,101235.0,528.00,2408.29,64.0,H-SC,17.11,168.0,-0.29,0.67,50.52,OX40N,NTT,MISC
16,CERA,0.62,-24.44,63.97,23.89,85020.0,-42997.0,132906.0,9475.00,-27.21,60.0,H-SC,7.14,153.0,-0.51,0.88,27.72,OX40N,NTT,CERAMICS
50,KANSAINER,-0.15,-27.43,56.36,13.47,110294.0,-73971.0,195696.0,340.00,-37.71,61.0,H-SC,12.57,162.0,-0.67,1.30,36.69,XY24,NTT,PAINTS
43,INDIGOPNTS,1.17,-28.83,40.53,0.02,50355.0,-50317.0,124242.0,1408.00,89.73,66.0,M-SC,17.86,222.0,-1.00,0.82,40.96,OX40N,NTT,PAINTS

In [14]:
# top 5 to book for rotation
df_tmp = df_portfolio_features[(df_portfolio_features['Current P/L%'] > 20) ].sort_values(by = 'CumlRnk', ascending=False)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
25,FINCABLES,2.67,41.24,47.20,107.91,98428.0,60889.0,208533.0,1641.55,26.84,66.0,M-SC,26.64,220.0,0.62,1.38,56.89,OX40N,ATH,CABLES
68,SATIN,-0.53,22.86,23.58,51.83,80043.0,63169.0,339453.0,274.00,10.38,68.0,H-SC,35.67,159.0,0.79,2.25,65.36,XY24,NTT,FINANCE

In [15]:
# top 5 to monitor for exit
df_tmp = df_portfolio_features[~df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])]
df_tmp = df_tmp[(df_tmp['Current P/L%'] > 0) ].sort_values(by = 'Dev%_PE', ascending=False)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
74,STARHEALTH,1.77,3.21,42.68,47.26,123833.0,9019.0,290142.0,761.00,62.96,66.0,H-SC,9.97,173.0,0.07,1.92,27.38,XY24,NTT,INSURANCE
25,FINCABLES,2.67,41.24,47.20,107.91,98428.0,60889.0,208533.0,1641.55,26.84,66.0,M-SC,26.64,220.0,0.62,1.38,56.89,OX40N,ATH,CABLES
68,SATIN,-0.53,22.86,23.58,51.83,80043.0,63169.0,339453.0,274.00,10.38,68.0,H-SC,35.67,159.0,0.79,2.25,65.36,XY24,NTT,FINANCE
91,ZYDUSLIFE,0.74,14.63,18.32,35.63,44010.0,30653.0,240227.0,1286.17,-0.45,76.0,H-MC,4.88,120.0,0.70,1.59,26.31,AR,ATH,PHARMA
73,SONACOMS,0.40,5.61,31.71,39.09,33875.0,5670.0,106829.0,804.02,-16.28,63.0,M-MC,18.84,193.0,0.17,0.71,51.12,AR,ATH,AUTO

In [16]:
# top 5 to book for rotation from weak conviction
df_tmp = df_portfolio_features[~df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])]
df_tmp = df_tmp[~df_tmp['Criteria'].isin(['XY25','XY24','X40', 'X40N'])].sort_values(by = 'RRR Ind', ascending=False)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
91,ZYDUSLIFE,0.74,14.63,18.32,35.63,44010.0,30653.0,240227.0,1286.17,-0.45,76.0,H-MC,4.88,120.0,0.70,1.59,26.31,AR,ATH,PHARMA
25,FINCABLES,2.67,41.24,47.20,107.91,98428.0,60889.0,208533.0,1641.55,26.84,66.0,M-SC,26.64,220.0,0.62,1.38,56.89,OX40N,ATH,CABLES
73,SONACOMS,0.40,5.61,31.71,39.09,33875.0,5670.0,106829.0,804.02,-16.28,63.0,M-MC,18.84,193.0,0.17,0.71,51.12,AR,ATH,AUTO
42,INDIAMART,-1.02,-13.32,138.48,106.72,148052.0,-16424.0,106912.0,4810.62,-60.94,44.0,H-SC,10.68,140.0,-0.11,0.71,3.50,AR,ATH,MISC
55,MASFIN,1.24,-5.08,28.08,21.57,26114.0,-4980.0,93000.0,397.04,-18.25,41.0,H-SC,4.29,167.0,-0.19,0.62,10.85,XR,ATH,FINANCE

In [17]:
# top 5 to accumulate based on lowest RSI_14
df_tmp = df_portfolio_features[df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])].sort_values(by = 'RSI_14', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
23,DMART,-0.35,-1.70,31.85,29.60,78143.0,-4254.0,245346.0,5391.45,-17.11,33.0,X-LC,3.65,14.0,-0.05,1.62,12.14,X40N,ATH,FMCG
33,HCLTECH,0.25,-24.41,60.74,21.51,111078.0,-59050.0,182874.0,1872.35,-20.60,38.0,X-LC,18.81,8.0,-0.53,1.21,3.63,X40,ATH,IT
27,GLAXO,1.18,-7.30,50.10,39.15,92557.0,-14540.0,184744.0,3466.20,-29.23,39.0,X-MC,6.55,56.0,-0.16,1.22,2.20,X40,ATH,PHARMA
79,TCS,-0.07,-33.22,87.01,24.88,269173.0,-153914.0,309359.0,4253.91,-43.63,39.0,X-LC,17.55,2.0,-0.57,2.05,2.65,X40,ATH,IT
88,VOLTAS,-0.90,-1.43,47.30,45.20,89397.0,-2742.0,189000.0,1856.00,12.87,40.0,X-MC,5.03,79.0,-0.03,1.25,3.26,XY25,NTT,AC

In [18]:
# top 5 to accumulate based on Spread and CumlRnk
df_tmp = df_portfolio_features[df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])]
df_tmp = df_tmp[(df_tmp['CumlRnk'] < 100)].sort_values(by = 'Spread%', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
23,DMART,-0.35,-1.70,31.85,29.60,78143.0,-4254.0,245346.0,5391.45,-17.11,33.0,X-LC,3.65,14.0,-0.05,1.62,12.14,X40N,ATH,FMCG
65,RELIANCE,0.03,-12.91,43.88,25.30,76796.0,-25949.0,175014.0,1952.00,-15.03,46.0,X-LC,3.89,21.0,-0.34,1.16,3.99,XY25,BTT,REFINERIES
84,UNITDSPR,0.77,-4.26,26.14,20.77,58598.0,-9976.0,224168.0,1644.00,-15.10,51.0,X-MC,4.00,64.0,-0.17,1.48,6.93,X40N,NTT,BREWERIES
39,ICICIGI,0.45,-1.01,20.56,19.34,40726.0,-2027.0,198082.0,2252.93,-16.65,60.0,X-MC,4.95,66.0,-0.05,1.31,10.63,X40,ATH,INSURANCE
88,VOLTAS,-0.90,-1.43,47.30,45.20,89397.0,-2742.0,189000.0,1856.00,12.87,40.0,X-MC,5.03,79.0,-0.03,1.25,3.26,XY25,NTT,AC

In [19]:
# top 5 to accumulate based on lowest Gained%
df_tmp = df_portfolio_features[df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])].sort_values(by = 'Gained%', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
27,GLAXO,1.18,-7.30,50.10,39.15,92557.0,-14540.0,184744.0,3466.20,-29.23,39.0,X-MC,6.55,56.0,-0.16,1.22,2.20,X40,ATH,PHARMA
79,TCS,-0.07,-33.22,87.01,24.88,269173.0,-153914.0,309359.0,4253.91,-43.63,39.0,X-LC,17.55,2.0,-0.57,2.05,2.65,X40,ATH,IT
32,HAVELLS,0.59,-22.65,69.90,31.42,177337.0,-74290.0,253701.0,2052.62,-27.23,45.0,X-MC,12.65,63.0,-0.42,1.68,2.84,X40,ATH,ELECTRICAL
88,VOLTAS,-0.90,-1.43,47.30,45.20,89397.0,-2742.0,189000.0,1856.00,12.87,40.0,X-MC,5.03,79.0,-0.03,1.25,3.26,XY25,NTT,AC
40,ICICIPRULI,-0.33,-13.79,51.65,30.73,87717.0,-27175.0,169830.0,790.00,-36.96,44.0,X-MC,11.94,78.0,-0.31,1.12,3.49,X40,ATH,INSURANCE

In [20]:
# top 5 to accumulate based on lowest CurrAlloc%
df_tmp = df_portfolio_features[df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])].sort_values(by = 'CurrAlloc%', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
10,BATAINDIA,-0.58,-55.19,201.73,35.20,116309.0,-71014.0,57656.0,2096.00,-24.48,44.0,X-SC,25.35,91.0,-0.61,0.38,14.35,X40,NTT,FOOTWEAR
64,RELAXO,0.73,-60.67,287.22,52.31,163991.0,-88064.0,57096.0,1176.00,-58.09,56.0,X-SC,24.55,92.0,-0.54,0.38,27.66,X40N,NTT,FOOTWEAR
60,QUESS,4.43,-12.35,98.41,73.90,92113.0,-13192.0,93601.0,424.00,-52.62,60.0,X-SC,9.62,80.0,-0.14,0.62,27.60,XY24,NTT,MISC
28,GODREJCP,-0.47,-8.10,43.06,31.47,58810.0,-12036.0,136578.0,1469.04,-3.32,45.0,X-LC,8.92,32.0,-0.20,0.90,4.79,X40N,ATH,FMCG
53,M&M,0.85,1.69,21.34,23.38,30094.0,2340.0,141021.0,3802.40,-13.74,49.0,X-LC,8.92,25.0,0.08,0.93,6.92,X40N,ATH,AUTO

In [21]:
# top 5 to accumulate based on CumlRnk
df_tmp = df_portfolio_features.sort_values(by = 'CumlRnk', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
47,ITC,-0.19,-22.80,54.21,19.06,142365.0,-77548.0,262618.0,452.00,-57.54,42.0,X-LC,14.60,1.0,-0.54,1.74,4.65,X40,NTT,FMCG
79,TCS,-0.07,-33.22,87.01,24.88,269173.0,-153914.0,309359.0,4253.91,-43.63,39.0,X-LC,17.55,2.0,-0.57,2.05,2.65,X40,ATH,IT
45,INFY,-0.37,-20.80,69.50,34.24,172224.0,-65084.0,247804.0,1972.00,-37.59,44.0,X-LC,18.83,3.0,-0.38,1.64,6.25,X40,NTT,IT
81,TMPV,1.97,-10.50,52.59,36.58,167495.0,-37349.0,318492.0,600.00,-81.44,73.0,X-LC,5.52,4.0,-0.22,2.11,32.75,XY24,NTT,AUTO
59,PIDILITIND,-0.03,4.75,13.00,18.37,19215.0,6700.0,147810.0,1670.26,-26.64,62.0,X-LC,5.18,5.0,0.35,0.98,16.06,X40,ATH,CHEMICALS

In [22]:
# top 5 for average up
df_tmp = df_portfolio_features[(df_portfolio_features['Dev%_200'] > 5)].sort_values(by = 'CurrAlloc%', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
44,INDUSINDBK,0.02,-31.16,93.03,32.89,49447.0,-24054.0,53152.0,1800.00,-350.00,61.0,L-MC,8.86,258.0,-0.49,0.35,30.83,XR,NTT,BANKS
72,SIS,-0.35,-8.82,33.00,21.26,33408.0,-9797.0,101235.0,528.00,2408.29,64.0,H-SC,17.11,168.0,-0.29,0.67,50.52,OX40N,NTT,MISC
73,SONACOMS,0.40,5.61,31.71,39.09,33875.0,5670.0,106829.0,804.02,-16.28,63.0,M-MC,18.84,193.0,0.17,0.71,51.12,AR,ATH,AUTO
5,ATULAUTO,0.51,-16.20,73.70,45.57,121757.0,-31926.0,165206.0,844.00,3581.08,51.0,M-SC,6.85,248.0,-0.26,1.09,27.13,XY24,NTT,AUTO
75,SURYODAY,1.21,-6.86,32.09,23.03,53523.0,-12281.0,166790.0,216.00,82.02,58.0,H-SC,18.81,166.0,-0.23,1.10,40.43,XR,NTT,BANKS

In [23]:
# top 5 RSP
df_tmp = df_portfolio_features.sort_values(by = 'RSP', ascending=False)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
68,SATIN,-0.53,22.86,23.58,51.83,80043.0,63169.0,339453.0,274.00,10.38,68.0,H-SC,35.67,159.0,0.79,2.25,65.36,XY24,NTT,FINANCE
69,SFL,0.19,-38.22,104.97,26.63,170049.0,-100220.0,161998.0,1287.00,22.65,66.0,M-SC,10.55,242.0,-0.59,1.07,35.02,XY24,NTT,MISC
72,SIS,-0.35,-8.82,33.00,21.26,33408.0,-9797.0,101235.0,528.00,2408.29,64.0,H-SC,17.11,168.0,-0.29,0.67,50.52,OX40N,NTT,MISC
91,ZYDUSLIFE,0.74,14.63,18.32,35.63,44010.0,30653.0,240227.0,1286.17,-0.45,76.0,H-MC,4.88,120.0,0.70,1.59,26.31,AR,ATH,PHARMA
43,INDIGOPNTS,1.17,-28.83,40.53,0.02,50355.0,-50317.0,124242.0,1408.00,89.73,66.0,M-SC,17.86,222.0,-1.00,0.82,40.96,OX40N,NTT,PAINTS

In [24]:
# Top N allocation
df_tmp = df_portfolio_features.sort_values(by = 'CurrAlloc%', ascending=False)
top_n_values = [10, 25, 50]

sum_df = pd.DataFrame({
    'Top_N': top_n_values,
    'Sum_Alloc%': [df_tmp['CurrAlloc%'].head(n).sum() for n in top_n_values]
})

sum_df

   Top_N  Sum_Alloc%
0     10       19.47
1     25       42.72
2     50       72.80

In [25]:
# market-cap-wise allocation
df_tmp = df_portfolio_features[cols]
df_tmp.groupby(df_tmp['Conviction'].str[-2:])['CurrAlloc%'].sum().sort_values(ascending=False)

Conviction
SC    42.88
LC    31.36
MC    25.77
Name: CurrAlloc%, dtype: float64

In [26]:
# criteria-wise allocation
df_portfolio_features.groupby('Criteria')['CurrAlloc%'].sum().sort_values(ascending=False)

Criteria
XY24     27.64
X40      25.27
X40N     16.99
XR        8.91
OX40N     7.04
AR        6.85
XY25      6.47
SR        0.84
Name: CurrAlloc%, dtype: float64

In [27]:
# conviction-wise allocation
df_portfolio_features.groupby('Conviction')['CurrAlloc%'].sum().sort_values(ascending=False)

Conviction
X-LC    29.17
H-SC    22.39
X-MC    20.76
M-SC    10.04
X-SC     9.85
H-MC     2.72
M-MC     1.94
H-LC     1.25
M-LC     0.94
L-SC     0.60
L-MC     0.35
Name: CurrAlloc%, dtype: float64

In [28]:
# sector-wise stats
df_tmp = df_portfolio_features.groupby('Category')[['CurrAlloc%', 'Current', 'Current P/L', 'FTT Amt']].sum().sort_values(by=['Current', 'Current P/L'], ascending=False)
df_tmp['Current P/L%'] = round(df_tmp['Current P/L'] * 100 / df_tmp['Current'], 2)
df_tmp['FTT%'] = round(df_tmp['FTT Amt'] * 100 / df_tmp['Current'], 2)
cols = ['CurrAlloc%', 'Current P/L%', 'FTT%']
df_tmp[cols].sort_values(by=['CurrAlloc%'], ascending=False)

               CurrAlloc%  Current P/L%    FTT%
Category
FMCG                15.04        -16.50   57.56
FINANCE             10.81        -13.07   62.24
IT                  10.24        -45.75  118.62
MISC                 6.96        -27.55   82.96
AUTO                 6.83         -6.02   45.77
BANKS                5.66         -6.00   55.02
PAINTS               5.59        -16.76   37.03
INSURANCE            5.35         -2.40   37.25
PHARMA               5.07          3.36   27.70
ELECTRICAL           4.13        -13.40   53.42
CHEMICALS            2.13        -26.52  101.92
HEALTHCARE           2.00        -18.55   49.49
AC                   1.77        -19.43   51.81
APPARELS             1.77         -0.42   34.15
FOOTWEAR             1.71        -70.70  139.14
TRAVEL               1.61        -83.76  175.78
DURABLES             1.61        -59.98   98.90
BREWERIES            1.48         -4.45   26.14
REALTY               1.41         -4.35   21.49
CABLES               1.38         29.20   47.20
CERAMICS             1.34        -51.56   97.61
ENGINEERING          1.26        -27.20   85.38
REFINERIES           1.16        -14.83   43.88
CEMENT               1.13        -57.31  174.99
JEWELLERY            1.06        -99.03  168.18
ENTERTAINMENT        0.72        -77.23  182.94
TEXTILES             0.40        -51.09   94.17
HOTELS               0.39        -94.16  162.64

In [29]:
# money to be made criteria-wise
df_portfolio_features.groupby('Criteria')['FTT Amt'].agg(['sum', 'count']).sort_values(by='sum', ascending=False)

                sum  count
Criteria
XY24      3423081.0     21
X40       1873862.0     19
XR        1335696.0     13
X40N      1156533.0     13
AR        1149150.0      9
OX40N      729460.0     10
XY25       463127.0      5
SR         293599.0      2

In [30]:
# money to be made conviction-wise
df_portfolio_features.groupby('Conviction')['FTT Amt'].agg(['sum', 'count']).sort_values(by='sum', ascending=False)

                  sum  count
Conviction
H-SC        3407054.0     24
X-LC        1881881.0     21
X-MC        1593461.0     15
M-SC        1399823.0     14
X-SC        1316830.0      9
H-MC         286888.0      2
L-SC         200443.0      2
M-LC         150402.0      1
M-MC          93497.0      2
L-MC          49447.0      1
H-LC          44782.0      1

In [31]:
# money to be made criteria and conviction-wise
df_portfolio_features.groupby(['Conviction', 'Criteria'])['FTT Amt'].agg(['sum', 'count']).sort_values(by='sum', ascending=False)

                           sum  count
Conviction Criteria
H-SC       XY24      1037079.0      6
X-LC       X40       1018081.0     10
H-SC       AR         950802.0      5
M-SC       XY24       829574.0      6
H-SC       XR         807942.0      7
X-SC       XY24       788727.0      4
X-MC       X40        654482.0      7
           X40N       470347.0      4
X-LC       X40N       359382.0      6
X-SC       X40N       326804.0      3
H-SC       OX40N      317632.0      4
X-LC       XY24       310270.0      2
M-SC       OX40N      306502.0      5
H-SC       SR         293599.0      2
X-MC       XY25       254079.0      2
H-MC       XY24       242878.0      1
X-MC       XY24       214553.0      2
X-SC       X40        201299.0      2
M-SC       XR         188066.0      2
M-LC       XR         150402.0      1
X-LC       XY25       149426.0      2
L-SC       OX40N      105326.0      1
           XR          95117.0      1
M-SC       AR          75681.0      1
M-MC       XY25        59622.0      1
L-MC       XR          49447.0      1
H-LC       AR          44782.0      1
X-LC       XR          44722.0      1
H-MC       AR          44010.0      1
M-MC       AR          33875.0      1

In [32]:
# notebook execution time

end_time = time.time()
execution_time = round(end_time - start_time, 0)
print(f"Notebook execution time: {execution_time} seconds")

Notebook execution time: 25.0 seconds