<a href="https://colab.research.google.com/github/ankit-rathi/Quantvesting_v2/blob/main/myStocks_Portfolio_Analysis.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
'''
!pip install pandas==2.2.2 -qq
!pip install pyxirr -qq
!pip install ta -qq
!pip install yfinance==0.2.59 -qq
'''

'\n!pip install pandas==2.2.2 -qq\n!pip install pyxirr -qq\n!pip install ta -qq\n!pip install yfinance==0.2.59 -qq\n'

In [2]:
# import libraries

import numpy as np
import pandas as pd
import datetime
import warnings
warnings.filterwarnings('ignore')
import yfinance as yfin
import ta
import matplotlib.pyplot as plt
import requests

In [3]:
# notebook start time
import time
import datetime
import pytz

start_time = time.time()

# function to print date timestamp
def print_date_time():
  tz_NY = pytz.timezone('Asia/Kolkata')
  datetime_NY = datetime.datetime.now(tz_NY)
  print("Run date time (IST):", datetime_NY.strftime("%Y-%m-%d %H:%M:%S"))

In [4]:
# function to get booked and reserved amount
def get_amt():
  # fetch the JSON data from the URL
  url = "https://raw.githubusercontent.com/ankit-rathi/Tradevesting_v1/main/data/myPortfolioAmts.json"
  response = requests.get(url)
  pf_amts = response.json()  # parse the JSON data

  # extract values from the JSON
  py_booked_amt_dm = pf_amts["py_booked_amt_dm"]
  py_booked_amt_sv = pf_amts["py_booked_amt_sv"]
  cy_booked_amt_dm = pf_amts["cy_booked_amt_dm"]
  cy_booked_amt_sv = pf_amts["cy_booked_amt_sv"]
  reserve_amt_dm = pf_amts["reserve_amt_dm"]
  reserve_amt_sv = pf_amts["reserve_amt_sv"]

  # perform calculations
  py_booked_amt = py_booked_amt_dm + py_booked_amt_sv
  cy_booked_amt = cy_booked_amt_dm + cy_booked_amt_sv
  reserve_amt = reserve_amt_dm + reserve_amt_sv
  total_booked_amt = py_booked_amt + cy_booked_amt

  return total_booked_amt, reserve_amt, cy_booked_amt, py_booked_amt

gen_output = 0

In [5]:
# function to format the amount
def format_amt(number):
    abs_number = abs(number)

    if abs_number >= 1_00_00_000:  # Crores
        formatted_amt = f"{number / 1_00_00_000:.2f} C"
    elif abs_number >= 1_00_000:  # Lakhs
        formatted_amt = f"{number / 1_00_000:.2f} L"
    elif abs_number >= 1_000:  # Thousands
        formatted_amt = f"{number / 1_000:.2f} K"
    else:
        formatted_amt = f"{number:.2f}"

    return formatted_amt

# function to set start and end date
def get_start_end_date():
  start_date = (datetime.date.today() + datetime.timedelta(days=-365)).strftime('%Y-%m-%d')
  end_date = (datetime.date.today() + datetime.timedelta(days=1)).strftime('%Y-%m-%d')
  return start_date, end_date

# function to fetch my portfolio csv
def get_mypfs_df():
  mypfs_df = pd.read_csv('https://raw.githubusercontent.com/ankit-rathi/Tradevesting_v1/main/data/myPortfolioStocks.csv')
  return mypfs_df

# function to fetch my prospects csv
def get_mypps_df():
  mypps_df = pd.read_csv('https://raw.githubusercontent.com/ankit-rathi/Tradevesting_v1/main/data/myProspectsScrips.csv')
  return mypps_df

# function to fetch screener data
def get_myscreen_df():
  myscreen_df = pd.read_csv('https://raw.githubusercontent.com/ankit-rathi/Tradevesting_v1/main/data/myScreenerDB.csv')
  return myscreen_df

# function to fetch momentum data
def get_myinvmt_df():
  myinvmt_df = pd.read_csv('https://raw.githubusercontent.com/ankit-rathi/Tradevesting_v1/main/data/myInvestments.csv')
  return myinvmt_df

# function to get the stock ids
def get_stock_ids(df_pf):
  stock_n100 = df_pf['Symbol'].unique()

  exclude = ['CADILAHC','MMTC', 'MASFIN']

  stock_ids = df_pf[~df_pf['Symbol'].isin(exclude) ]['Symbol'].unique()

  #mypf = mypf[mypf.Forecast.notnull()]
  #stock_ids = mypf['Symbol'].unique()

  #stock_ids.sort()
  return stock_ids

# get features from screener data
def get_screener_features():
  myscreen_df = get_myscreen_df()
  cols = ['Symbol', 'EPS', 'MedPE', 'ROCE%', 'ROE%', 'CapType']
  return myscreen_df[cols]

# get relative strength
def get_relative_strength(stock_list):

    # Dictionary to store stock tickers and their corresponding percentage price change
    stock_changes = {}

    # Loop through each stock and fetch its price data
    for stock in stock_list:
        try:
            # Download the stock data for the given date range
            stock_data = yfin.Ticker(stock + '.NS').history(period='1mo', interval='1d')[map(str.title, ['open', 'close', 'low', 'high', 'volume'])]

            # Calculate the percentage change for the stock
            if len(stock_data) > 0:
                start_price = stock_data['Close'].iloc[0]
                end_price = stock_data['Close'].iloc[-1]
                percent_change = round(((end_price - start_price) / start_price) * 100, 2)
                stock_changes[stock] = percent_change
            else:
                stock_changes[stock] = np.nan  # If no data is available, set to NaN

        except Exception as e:
            print(f"Error fetching data for {stock}: {e}")
            stock_changes[stock] = np.nan

    # Create a DataFrame with stock tickers and their percentage changes
    df = pd.DataFrame(list(stock_changes.items()), columns=['Symbol', 'Percent_Change'])

    # Drop any stocks with missing data (NaN values)
    df = df.dropna()

    # Calculate the percentile rank based on percentage change
    df['RSP'] = round(df['Percent_Change'].rank(pct=True) * 100, 2)
    cols = ['Symbol', 'RSP']
    df = df[cols]
    # Sort by percentile rank (optional)
    df = df.sort_values(by='RSP', ascending=False).reset_index(drop=True)

    return df

In [6]:
# function to get stock technicals
def stock_prec_dev(stock_symbol):
    #stock_symbol = 'ULTRACEMCO.NS'
    short_window = 20
    mid_window = 50
    long_window = 200
    moving_avg = 'SMA'

    start = datetime.datetime(*map(int, start_date.split('-')))
    end = datetime.datetime(*map(int, end_date.split('-')))

    stock_df = yfin.Ticker(stock_symbol + '.NS').history(period='max', interval='1d')[map(str.title, ['open', 'close', 'low', 'high', 'volume'])]

    stock_df['Max'] = round(max(stock_df['Close']),2)
    stock_df = stock_df[(stock_df.index <= end_date) & (stock_df.index >= start_date)]
    stock_df['200_SMA'] = round(stock_df['Close'].rolling(window = 200, min_periods = 1).mean(),0)
    stock_df['Dev%_200'] = round((stock_df['Close'] - stock_df['200_SMA'])*100/stock_df['200_SMA'],2)
    stock_df.dropna(axis = 0, inplace = True) # remove any null rows

    stock_df['20_SMA'] = stock_df['Close'].rolling(window=20).mean()
    stock_df['50_SMA'] = stock_df['Close'].rolling(window=50).mean()
    stock_df['Symbol'] = stock_symbol

    stock_df['Close'] = round(stock_df['Close'],2)
    stock_df['Min'] = round(min(stock_df['Close']),2)
    stock_df['RSI_14'] = ta.momentum.RSIIndicator(close=stock_df['Close'], window=14).rsi()
    stock_df['RSI_14'] = round(stock_df['RSI_14'],0)
    stock_df['Prev_Close'] = stock_df['Close'].shift(1)
    stock_df.drop(['Open', 'Low', 'High', 'Volume'], axis=1, inplace=True)
    stock_df = stock_df.tail(1)

    max_SMA = max(stock_df['20_SMA'].item(), stock_df['50_SMA'].item(), stock_df['200_SMA'].item())
    min_SMA = min(stock_df['20_SMA'].item(), stock_df['50_SMA'].item(), stock_df['200_SMA'].item())
    ABS_Spread = max_SMA - min_SMA
    stock_df['Spread%'] = round((ABS_Spread / stock_df['200_SMA'].item()) * 100,2)

    return stock_df

# function to compute stock attributes
def get_common_features(stock_ids, df_mypf):

  df_prec_dev = pd.DataFrame()
  df_tmp = get_screener_features()
  df_rs = get_relative_strength(stock_ids)

  for stock_id in stock_ids:
      tmp = stock_prec_dev(stock_id)
      tmp = tmp.reset_index()
      df_prec_dev = pd.concat([df_prec_dev, tmp], ignore_index = True)
  df_prec_dev = pd.merge(df_prec_dev, df_mypf, on= 'Symbol')
  df_prec_dev = pd.merge(df_prec_dev, df_tmp, on= 'Symbol', how='left')
  df_prec_dev = pd.merge(df_prec_dev, df_rs, on= 'Symbol', how='left')
  #print(df_prec_dev.columns)
  df_prec_dev['Curr_PE'] = round(df_prec_dev['Close']/df_prec_dev['EPS'],1)
  df_prec_dev['Dev%_PE'] = round((df_prec_dev['Curr_PE'] - df_prec_dev['MedPE'])*100/df_prec_dev['MedPE'],2)
  df_prec_dev['Conviction'] = df_prec_dev['Conviction'] + '-' + df_prec_dev['CapType']
  return df_prec_dev

# function to arrange stock features
def arrange_features(df_stocks, common_cols, diff_cols):
  df_stocks_common = df_stocks[common_cols].drop_duplicates()
  df_stocks_diff = df_stocks[diff_cols]
  df_stocks_diff['Investment'] = df_stocks_diff['AvgCost'] * df_stocks_diff['Shares']
  df_stocks_diff = df_stocks_diff.groupby(['Symbol'])[['Shares', 'Investment']].aggregate(['sum']).reset_index()
  df_stocks_diff.columns = ['Symbol', 'Shares', 'Investment']
  df_stocks_diff['AvgCost'] = round(df_stocks_diff['Investment']/df_stocks_diff['Shares'],2)
  df_stocks = pd.merge(df_stocks_diff, df_stocks_common, on='Symbol')
  return df_stocks

# plot fact distribution across dimension
def plot_pie_chart(df, dimension, fact):
  # grouping the data by category and calculating the sum of fact for each type
  grouped_data = df.groupby(dimension)[fact].sum()

  # sorting the grouped data in descending order
  grouped_data = grouped_data.sort_values(ascending=False)

  # creating a pie chart
  grouped_data.plot.pie(autopct='%1.1f%%', startangle=90, figsize=(6, 6))

  # adding a title and displaying the plot
  plt.title(f'{dimension} {fact} Distribution')
  plt.ylabel('')  # To hide the y-label
  plt.show()

In [7]:
# function to get portfolio features

def get_portfolio_features(df_common_features):

  print_date_time()
  print('-------------------')

  #df_common_features["Target"] = df_common_features["Target"].fillna(df_common_features["Max"])
  df_common_features['NTT'] = np.where(df_common_features['Strategy']== 'NTT', df_common_features["Target"], df_common_features['Max'])
  df_common_features['LTT'] = np.where(df_common_features['Strategy']== 'BTT', df_common_features["Target"], df_common_features['Max'])
  df_common_features['BOL'] = df_common_features['Min']

  tmp_df = df_common_features[df_common_features['Symbol'].isin(mypf_df[mypf_df['InPortfolio'] != 'NA'].Symbol.values)]
  print('qualified stocks: '+str(len(tmp_df['Symbol'].unique())))
  tmp_df1 = tmp_df[tmp_df['LatestQtr'] == 1]
  print('with latest results: '+str(len(tmp_df1['Symbol'].unique())))
  tmp_df1 = tmp_df1[tmp_df1['StarStock'] == 1]
  print('still star stocks: '+str(len(tmp_df1['Symbol'].unique())))
  tmp_df['Investment'] = tmp_df['AvgCost'] * tmp_df['Shares']
  tmp_df['Current'] = round(tmp_df['Close'] * tmp_df['Shares'],0)
  tmp_df['Previous'] = tmp_df['Prev_Close'] * tmp_df['Shares']
  tmp_df['EstimatedST'] = tmp_df['NTT'] * tmp_df['Shares']
  tmp_df['EstimatedLT'] = tmp_df['LTT'] * tmp_df['Shares']
  tmp_df['Current P/L'] = round((tmp_df['Current'] - tmp_df['Investment']),0)
  tmp_df['Today P/L%'] = round((tmp_df['Current'] - tmp_df['Previous'])*100/tmp_df['Previous'],2)
  tmp_df['Current P/L%'] = round((tmp_df['Current'] - tmp_df['Investment'])*100/tmp_df['Investment'],2)
  tmp_df['EstimatedST P/L%'] = round((tmp_df['EstimatedST'] - tmp_df['Investment'])*100/tmp_df['Investment'],2)
  tmp_df['EstimatedLT P/L%'] = round((tmp_df['EstimatedLT'] - tmp_df['Investment'])*100/tmp_df['Investment'],2)
  tmp_df['NTT%'] = round((tmp_df['NTT'] - tmp_df['Close'])*100/tmp_df['Close'],2)
  tmp_df['LTT%'] = round((tmp_df['LTT'] - tmp_df['Close'])*100/tmp_df['Close'],2)
  tmp_df['Gained%'] = round((tmp_df['Close'] - tmp_df['BOL'])*100/tmp_df['BOL'],2)
  investment = round(sum(tmp_df['AvgCost']*tmp_df['Shares']),0)
  current = round(sum(tmp_df['Close']*tmp_df['Shares']),0)
  tmp_df['InitAlloc%'] = round(tmp_df['Investment']*100/investment,2)
  tmp_df['CurrAlloc%'] = round(tmp_df['Current']*100/current,2)
  tmp_df['FTT'] = tmp_df['LTT']
  tmp_df.loc[tmp_df['Strategy'] == 'NTT', 'FTT'] = tmp_df['NTT']
  tmp_df['FTT%'] = tmp_df['LTT%']
  tmp_df.loc[tmp_df['Strategy'] == 'NTT', 'FTT%'] = tmp_df['NTT%']
  tmp_df['FTT Amt'] = round(tmp_df['FTT%'] * tmp_df['Current']/100,0)
  tmp_df['OTT%'] = round((tmp_df['FTT'] - tmp_df['AvgCost'])*100/tmp_df['AvgCost'],2)
  tmp_df['RRR Ind'] = round(tmp_df['Current P/L']/tmp_df['FTT Amt'],2)
  tmp_df['Risk Ind'] = round(tmp_df['Current P/L%']*tmp_df['CurrAlloc%'],0)

  return tmp_df

# function to print portfolio features
def print_portfolio_stats(df_portfolio_features, myinvmt_df):
  from pyxirr import xirr

  total_booked_amt, reserve_amt, cy_booked_amt, py_booked_amt = get_amt()

  dates = myinvmt_df['Date'].values
  dates = np.append(dates, datetime.date.today().strftime('%d-%b-%y'))
  investment = myinvmt_df['Investment'].values
  dates= pd.to_datetime(dates)

  current = round(sum(df_portfolio_features['Close']*df_portfolio_features['Shares']),0) + reserve_amt
  investment_xirr = np.append(investment, current)
  cagr = round(xirr(pd.DataFrame({"dates": dates, "amounts": investment_xirr}))*100,2)

  investment = -sum(investment)
  invested = round(sum(df_portfolio_features['AvgCost']*df_portfolio_features['Shares']),0) + reserve_amt
  previous = round(sum(df_portfolio_features['Prev_Close']*df_portfolio_features['Shares']),0) + reserve_amt
  cy_invested = investment + py_booked_amt

  today_pnl_amount = current-previous
  today_pnl_percentage = round((current-previous)*100/previous,2)

  curr_pnl_amount = current-invested
  curr_pnl_percentage = round((curr_pnl_amount)*100/(cy_invested),2)

  cy_pnl_amount = cy_booked_amt + curr_pnl_amount
  cy_pnl_percentage = round((cy_pnl_amount)*100/cy_invested,2)

  overall_pnl_amount = total_booked_amt + curr_pnl_amount
  overall_pnl_percentage = round((overall_pnl_amount)*100/investment,2)

  estimate_st = round(sum(df_portfolio_features['FTT']*df_portfolio_features['Shares']),0)  + reserve_amt
  est_st_pnl_amount = estimate_st-current
  est_st_pnl_percentage = round((est_st_pnl_amount)*100/current,2)

  estimate_lt = round(sum(df_portfolio_features['LTT']*df_portfolio_features['Shares']),0)  + reserve_amt
  est_lt_pnl_amount = estimate_lt-current
  est_lt_pnl_percentage = round((est_lt_pnl_amount)*100/current,2)

  total_profit = round(sum(df_portfolio_features[df_portfolio_features['Current P/L%'] > 0]['Current']) - sum(df_portfolio_features[df_portfolio_features['Current P/L%'] > 0]['Investment']),0)
  total_loss = round(sum(df_portfolio_features[df_portfolio_features['Current P/L%'] < 0]['Current']) - sum(df_portfolio_features[df_portfolio_features['Current P/L%'] < 0]['Investment']),0)

  cy_booked_percentage = round((cy_booked_amt)*100/current,2)
  py_booked_percentage = round((py_booked_amt)*100/investment,2)
  total_booked_percentage = round((total_booked_amt)*100/investment,2)

  print('-------------------')
  print('Initial Investment: ', format_amt(investment))
  print('CY Investment: ', format_amt(cy_invested))
  print('Reserve: ', format_amt(reserve_amt))
  print('Current: ',  format_amt(current))
  print('-------------------')
  print('Today PnL: '+ '{} ({}%)'.format(format_amt(today_pnl_amount), today_pnl_percentage))
  print('Current PnL: '+ '{} ({}%)'.format(format_amt(curr_pnl_amount), curr_pnl_percentage))
  print('CY Booked + Current PnL: '+ '{} ({}%)'.format(format_amt(cy_pnl_amount), cy_pnl_percentage))
  print('-------------------')
  print('Total profit: ', format_amt(total_profit))
  print('Total loss: ', format_amt(total_loss))
  print('-------------------')
  print('Total Booked + Current PnL: '+ '{} ({}%)'.format(format_amt(overall_pnl_amount), overall_pnl_percentage))
  print('Total Booked PnL: '+ '{} ({}%)'.format(format_amt(total_booked_amt), total_booked_percentage))
  print('Curr Year Booked PnL: '+ '{} ({}%)'.format(format_amt(cy_booked_amt), cy_booked_percentage))
  print('Prev Year Booked PnL: '+ '{} ({}%)'.format(format_amt(py_booked_amt), py_booked_percentage))
  print('===================')
  print('Est FTT: ',  format_amt(estimate_st))
  print('Est FTT PnL: '+ '{} ({}%)'.format(format_amt(est_st_pnl_amount), est_st_pnl_percentage))

  print('===================')
  print('Deployed: ', format_amt(investment))

  print('Current: ', format_amt(current))

  print('CAGR/XIRR %: '+'{}%'.format(cagr))

In [8]:
# get start and end date
start_date, end_date = get_start_end_date()

# get portfolio and prospects data
mypfs_df = get_mypfs_df()
mypps_df = get_mypps_df()
myinvmt_df = get_myinvmt_df()

# merge above datasets
mypf_df = pd.merge(mypfs_df, mypps_df, on="Symbol")

# seggregate dm and sv portfolio
dm_pf = mypf_df[mypf_df['InPortfolio'] == 'DM']
sv_pf = mypf_df[mypf_df['InPortfolio'] == 'SV']

# build portfolio stock dataframe
dm_stocks = get_stock_ids(dm_pf)
sv_stocks = get_stock_ids(sv_pf)
df_stocks = pd.concat([dm_pf,sv_pf], ignore_index = True)

# arrange common and diff stock features
common_cols = ['Symbol', 'Target', 'Criteria', 'Strategy', 'CumlRnk', 'LatestQtr', 'StarStock', 'Conviction', 'Category', 'InFolio', 'XIRR', 'MBQ']
diff_cols = ['Symbol', 'AvgCost', 'Shares']
df_stocks = arrange_features(df_stocks, common_cols, diff_cols)

# get common features
stock_ids = df_stocks['Symbol'].values
df_common_features = get_common_features(stock_ids, df_stocks)

df_common_features.reset_index(drop=True, inplace=True)
df_common_features.drop(['Date'], axis=1, inplace=True)
# get and print portfolio features
df_portfolio_features = get_portfolio_features(df_common_features)

print_portfolio_stats(df_portfolio_features, myinvmt_df)

df = df_portfolio_features
#plot_pie_chart(df, 'CapType', 'Current')
list_ox40n = list(df[df['MBQ'].str.contains('OX40N', na=False)]['Symbol'].values)

Run date time (IST): 2026-03-20 12:06:29
-------------------
qualified stocks: 86
with latest results: 26
still star stocks: 16
-------------------
Initial Investment:  1.36 C
CY Investment:  1.62 C
Reserve:  1.61 K
Current:  1.32 C
-------------------
Today PnL: 1.29 L (0.98%)
Current PnL: -44.91 L (-27.64%)
CY Booked + Current PnL: -29.02 L (-17.86%)
-------------------
Total profit:  68.28 K
Total loss:  -45.60 L
-------------------
Total Booked + Current PnL: -2.04 L (-1.51%)
Total Booked PnL: 42.87 L (31.64%)
Curr Year Booked PnL: 15.89 L (12.02%)
Prev Year Booked PnL: 26.98 L (19.91%)
===================
Est FTT:  2.48 C
Est FTT PnL: 1.16 C (87.49%)
===================
Deployed:  1.36 C
Current:  1.32 C
CAGR/XIRR %: -1.22%

In [9]:
# top 5 near their targets
cols = ['Symbol', 'Today P/L%', 'Current P/L%', 'FTT%', 'OTT%', 'FTT Amt', 'Current P/L', 'Current', 'FTT', 'Dev%_PE', 'RSI_14','Conviction', 'Spread%',  'CumlRnk', 'RRR Ind', 'CurrAlloc%', 'Gained%', 'Criteria', 'Strategy', 'Category']
df_tmp = df_portfolio_features[~df_portfolio_features['Symbol'].isin(['ENRIN','BLUSPRING','DIGITIDE'])]
df_tmp = df_tmp.sort_values(by = 'FTT Amt', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
50,MASFIN,1.83,-8.68,33.12,21.57,29634.0,-8505.0,89475.0,397.04,-21.41,41.0,H-SC,1.64,167.0,-0.29,0.68,22.04,XR,ATH,FINANCE
77,TTKPRESTIG,-1.91,-38.23,62.04,0.09,38621.0,-38526.0,62251.0,770.00,44.50,40.0,M-SC,18.01,250.0,-1.00,0.47,5.18,OX40N,NTT,DURABLES
37,ICICIGI,0.89,-4.22,24.60,19.34,47148.0,-8450.0,191659.0,2252.93,-19.34,37.0,X-MC,2.70,66.0,-0.18,1.45,5.95,X40,ATH,INSURANCE
2,ABBOTINDIA,0.21,-10.87,32.46,18.07,51748.0,-19435.0,159420.0,35195.00,-24.24,45.0,X-MC,10.69,58.0,-0.38,1.21,1.07,X40,ATH,PHARMA
67,SONACOMS,1.62,-12.33,58.65,39.09,52017.0,-12469.0,88690.0,804.02,-30.46,49.0,M-MC,8.17,193.0,-0.24,0.67,25.47,AR,ATH,AUTO

In [10]:
# top 5 today
df_tmp = df_portfolio_features.sort_values(by = 'Today P/L%', ascending=False)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
30,HAPPSTMNDS,5.44,-51.08,277.88,84.85,174220.0,-65469.0,62696.0,1480.71,-41.79,54.0,H-SC,27.44,152.0,-0.38,0.47,16.10,AR,ATH,IT
8,AWL,5.16,-36.17,161.64,67.02,367649.0,-128860.0,227449.0,485.00,-65.68,47.0,X-SC,25.70,81.0,-0.35,1.72,7.59,XY24,NTT,FMCG
72,TATAELXSI,4.00,-39.46,118.07,32.03,94242.0,-52016.0,79819.0,9161.00,-24.23,36.0,H-SC,20.15,158.0,-0.55,0.60,4.00,OX40N,NTT,IT
52,PAGEIND,3.35,-15.83,59.34,34.11,134043.0,-42489.0,225890.0,51418.64,-39.71,52.0,X-MC,21.10,55.0,-0.32,1.71,6.85,X40,ATH,APPARELS
45,ITC,3.32,-18.90,46.80,19.06,129111.0,-64288.0,275878.0,452.00,-55.52,45.0,X-LC,17.83,1.0,-0.50,2.09,3.32,X40,NTT,FMCG

In [11]:
# bottom 5 today
df_tmp = df_portfolio_features.sort_values(by = 'Today P/L%', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
55,RAJESHEXPO,-2.57,-81.41,438.41,0.07,111777.0,-111681.0,25496.0,518.0,834.34,17.0,L-SC,30.93,268.0,-1.00,0.19,0.00,OX40N,NTT,JEWELLERY
34,HDFCBANK,-2.16,-6.57,37.40,28.37,82073.0,-15438.0,219447.0,1073.0,-20.53,24.0,X-LC,10.76,26.0,-0.19,1.66,0.00,X40,BTT,BANKS
77,TTKPRESTIG,-1.91,-38.23,62.04,0.09,38621.0,-38526.0,62251.0,770.0,44.50,40.0,M-SC,18.01,250.0,-1.00,0.47,5.18,OX40N,NTT,DURABLES
69,SURYODAY,-1.76,-28.68,72.51,23.03,92605.0,-51357.0,127714.0,216.0,38.16,45.0,H-SC,6.64,166.0,-0.55,0.97,24.82,XR,NTT,BANKS
80,VALIANTORG,-1.68,-47.00,228.56,74.15,198200.0,-76888.0,86717.0,838.0,-255.96,61.0,H-SC,28.77,145.0,-0.39,0.66,29.05,XR,NTT,CHEMICALS

In [12]:
# top 5 to exit based on CumlRnk
df_tmp = df_portfolio_features[~df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])]
df_tmp = df_tmp[(df_tmp['Current P/L%'] > -1) & (df_tmp['Current P/L%'] < 1)].sort_values(by = 'CumlRnk', ascending=False)
df_tmp[cols].head()

Empty DataFrame
Columns: [Symbol, Today P/L%, Current P/L%, FTT%, OTT%, FTT Amt, Current P/L, Current, FTT, Dev%_PE, RSI_14, Conviction, Spread%, CumlRnk, RRR Ind, CurrAlloc%, Gained%, Criteria, Strategy, Category]
Index: []

In [13]:
# OX40N stocks to exit
df_tmp = df_portfolio_features[(df_portfolio_features['Symbol'].isin(list_ox40n))].sort_values(by = 'Current P/L%', ascending=False)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
26,FINCABLES,2.50,10.32,88.46,107.91,144089.0,15242.0,162886.0,1641.55,-0.56,52.0,M-SC,8.29,220.0,0.11,1.23,22.55,OX40N,ATH,CABLES
66,SIS,-1.40,-37.04,92.60,21.26,64735.0,-41124.0,69908.0,528.00,1632.12,32.0,H-SC,13.68,168.0,-0.64,0.53,0.75,OX40N,NTT,MISC
18,CERA,-0.20,-37.91,99.52,23.89,108698.0,-66681.0,109222.0,9475.00,-40.10,46.0,H-SC,18.44,153.0,-0.61,0.83,4.96,OX40N,NTT,CERAMICS
77,TTKPRESTIG,-1.91,-38.23,62.04,0.09,38621.0,-38526.0,62251.0,770.00,44.50,40.0,M-SC,18.01,250.0,-1.00,0.47,5.18,OX40N,NTT,DURABLES
72,TATAELXSI,4.00,-39.46,118.07,32.03,94242.0,-52016.0,79819.0,9161.00,-24.23,36.0,H-SC,20.15,158.0,-0.55,0.60,4.00,OX40N,NTT,IT

In [14]:
# top 5 to book for rotation
df_tmp = df_portfolio_features[(df_portfolio_features['Current P/L%'] > 20) ].sort_values(by = 'CumlRnk', ascending=False)
df_tmp[cols].head()

Empty DataFrame
Columns: [Symbol, Today P/L%, Current P/L%, FTT%, OTT%, FTT Amt, Current P/L, Current, FTT, Dev%_PE, RSI_14, Conviction, Spread%, CumlRnk, RRR Ind, CurrAlloc%, Gained%, Criteria, Strategy, Category]
Index: []

In [15]:
# top 5 to monitor for exit
df_tmp = df_portfolio_features[~df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])]
df_tmp = df_tmp[(df_tmp['Current P/L%'] > 0) ].sort_values(by = 'Dev%_PE', ascending=False)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
26,FINCABLES,2.50,10.32,88.46,107.91,144089.0,15242.0,162886.0,1641.55,-0.56,52.0,M-SC,8.29,220.0,0.11,1.23,22.55,OX40N,ATH,CABLES
1,ABB,1.71,15.95,25.54,45.57,77478.0,41741.0,303360.0,7934.00,-25.51,61.0,H-MC,13.04,125.0,0.54,2.29,34.71,AR,NTT,ELECTRICAL

In [16]:
# top 5 to book for rotation from weak conviction
df_tmp = df_portfolio_features[~df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])]
df_tmp = df_tmp[~df_tmp['Criteria'].isin(['XY25','XY24','X40', 'X40N'])].sort_values(by = 'RRR Ind', ascending=False)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
1,ABB,1.71,15.95,25.54,45.57,77478.0,41741.0,303360.0,7934.00,-25.51,61.0,H-MC,13.04,125.0,0.54,2.29,34.71,AR,NTT,ELECTRICAL
26,FINCABLES,2.50,10.32,88.46,107.91,144089.0,15242.0,162886.0,1641.55,-0.56,52.0,M-SC,8.29,220.0,0.11,1.23,22.55,OX40N,ATH,CABLES
40,INDIAMART,-0.64,-13.37,138.62,106.72,148113.0,-16488.0,106848.0,4810.62,-60.94,34.0,H-SC,10.77,140.0,-0.11,0.81,6.88,AR,ATH,MISC
85,ZYDUSLIFE,1.48,-6.24,44.66,35.63,87753.0,-13083.0,196491.0,1286.17,-18.47,45.0,H-MC,5.29,120.0,-0.15,1.49,9.39,AR,ATH,PHARMA
84,WIPRO,0.73,-22.16,121.30,72.27,160000.0,-37544.0,131904.0,420.00,-29.71,29.0,M-LC,17.03,98.0,-0.23,1.00,0.73,XR,NTT,IT

In [17]:
# top 5 to accumulate based on lowest RSI_14
df_tmp = df_portfolio_features[df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])].sort_values(by = 'RSI_14', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
53,PGHH,-0.59,-26.11,78.67,32.01,124110.0,-55760.0,157760.0,17616.87,-50.08,15.0,X-MC,14.44,57.0,-0.45,1.19,0.00,X40,ATH,FMCG
12,BATAINDIA,1.77,-57.46,217.84,35.20,119233.0,-73936.0,54734.0,2096.00,-28.23,20.0,X-SC,29.92,91.0,-0.62,0.41,1.77,X40,NTT,FOOTWEAR
58,RELAXO,0.51,-64.50,329.04,52.31,169558.0,-93629.0,51531.0,1176.00,-62.25,21.0,X-SC,24.52,92.0,-0.55,0.39,0.51,X40N,NTT,FOOTWEAR
38,ICICIPRULI,-0.56,-7.37,41.13,30.73,75053.0,-14527.0,182478.0,790.00,-32.26,23.0,X-MC,3.37,78.0,-0.19,1.38,4.39,X40,ATH,INSURANCE
34,HDFCBANK,-2.16,-6.57,37.40,28.37,82073.0,-15438.0,219447.0,1073.00,-20.53,24.0,X-LC,10.76,26.0,-0.19,1.66,0.00,X40,BTT,BANKS

In [18]:
# top 5 to accumulate based on Spread and CumlRnk
df_tmp = df_portfolio_features[df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])]
df_tmp = df_tmp[(df_tmp['CumlRnk'] < 100)].sort_values(by = 'Spread%', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
78,UNITDSPR,1.91,-3.51,25.16,20.77,56842.0,-8222.0,225922.0,1644.00,-14.48,43.0,X-MC,1.08,64.0,-0.14,1.71,2.96,X40N,NTT,BREWERIES
37,ICICIGI,0.89,-4.22,24.60,19.34,47148.0,-8450.0,191659.0,2252.93,-19.34,37.0,X-MC,2.70,66.0,-0.18,1.45,5.95,X40,ATH,INSURANCE
38,ICICIPRULI,-0.56,-7.37,41.13,30.73,75053.0,-14527.0,182478.0,790.00,-32.26,23.0,X-MC,3.37,78.0,-0.19,1.38,4.39,X40,ATH,INSURANCE
59,RELIANCE,2.85,-8.58,37.06,25.30,68087.0,-17241.0,183722.0,1952.00,-10.80,53.0,X-LC,3.39,21.0,-0.25,1.39,22.66,XY25,BTT,REFINERIES
65,SIEMENS,2.16,-15.49,48.51,25.51,76294.0,-28820.0,157275.0,4671.50,32.11,46.0,H-LC,3.52,51.0,-0.38,1.19,15.82,AR,ATH,ELECTRICAL

In [19]:
# top 5 to accumulate based on lowest Gained%
df_tmp = df_portfolio_features[df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])].sort_values(by = 'Gained%', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
53,PGHH,-0.59,-26.11,78.67,32.01,124110.0,-55760.0,157760.0,17616.87,-50.08,15.0,X-MC,14.44,57.0,-0.45,1.19,0.00,X40,ATH,FMCG
34,HDFCBANK,-2.16,-6.57,37.40,28.37,82073.0,-15438.0,219447.0,1073.00,-20.53,24.0,X-LC,10.76,26.0,-0.19,1.66,0.00,X40,BTT,BANKS
51,MEDANTA,0.04,-13.17,46.40,27.12,71115.0,-23252.0,153265.0,1486.00,-15.82,30.0,X-SC,10.99,87.0,-0.33,1.16,0.04,XY24,NTT,HEALTHCARE
58,RELAXO,0.51,-64.50,329.04,52.31,169558.0,-93629.0,51531.0,1176.00,-62.25,21.0,X-SC,24.52,92.0,-0.55,0.39,0.51,X40N,NTT,FOOTWEAR
81,VBL,-0.26,-18.47,66.41,35.67,171004.0,-58345.0,257497.0,671.64,-28.10,33.0,X-LC,7.86,13.0,-0.34,1.95,0.57,X40N,ATH,FMCG

In [20]:
# top 5 to accumulate based on lowest CurrAlloc%
df_tmp = df_portfolio_features[df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])].sort_values(by = 'CurrAlloc%', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
58,RELAXO,0.51,-64.50,329.04,52.31,169558.0,-93629.0,51531.0,1176.00,-62.25,21.0,X-SC,24.52,92.0,-0.55,0.39,0.51,X40N,NTT,FOOTWEAR
12,BATAINDIA,1.77,-57.46,217.84,35.20,119233.0,-73936.0,54734.0,2096.00,-28.23,20.0,X-SC,29.92,91.0,-0.62,0.41,1.77,X40,NTT,FOOTWEAR
54,QUESS,0.25,-26.46,136.46,73.90,107173.0,-28255.0,78538.0,424.00,-60.33,37.0,X-SC,20.49,80.0,-0.26,0.59,2.35,XY24,NTT,MISC
36,HONAUT,1.42,-25.17,102.21,51.31,147489.0,-48538.0,144300.0,58357.33,-37.79,33.0,X-SC,14.98,90.0,-0.33,1.09,1.42,X40N,ATH,ELECTRICAL
51,MEDANTA,0.04,-13.17,46.40,27.12,71115.0,-23252.0,153265.0,1486.00,-15.82,30.0,X-SC,10.99,87.0,-0.33,1.16,0.04,XY24,NTT,HEALTHCARE

In [21]:
# top 5 to accumulate based on CumlRnk
df_tmp = df_portfolio_features.sort_values(by = 'CumlRnk', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
45,ITC,3.32,-18.90,46.80,19.06,129111.0,-64288.0,275878.0,452.00,-55.52,45.0,X-LC,17.83,1.0,-0.50,2.09,3.32,X40,NTT,FMCG
73,TCS,0.73,-30.33,81.68,26.57,263626.0,-140518.0,322755.0,4311.59,-41.00,25.0,X-LC,16.69,2.0,-0.53,2.44,0.73,X40,ATH,IT
43,INFY,1.54,-15.61,59.08,34.24,155992.0,-48853.0,264035.0,1972.00,-33.60,32.0,X-LC,14.87,3.0,-0.31,2.00,1.54,X40,NTT,IT
75,TMPV,1.55,-28.50,91.02,36.58,231574.0,-101420.0,254421.0,600.00,-84.72,34.0,X-LC,5.02,4.0,-0.44,1.92,1.55,XY24,NTT,AUTO
33,HCLTECH,2.44,-12.79,42.00,23.83,88610.0,-30947.0,210977.0,1908.19,-8.19,39.0,X-LC,11.50,8.0,-0.35,1.60,2.44,X40,ATH,IT

In [22]:
# top 5 for average up
df_tmp = df_portfolio_features[(df_portfolio_features['Dev%_200'] > 5)].sort_values(by = 'CurrAlloc%', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
67,SONACOMS,1.62,-12.33,58.65,39.09,52017.0,-12469.0,88690.0,804.02,-30.46,49.0,M-MC,8.17,193.0,-0.24,0.67,25.47,AR,ATH,AUTO
1,ABB,1.71,15.95,25.54,45.57,77478.0,41741.0,303360.0,7934.00,-25.51,61.0,H-MC,13.04,125.0,0.54,2.29,34.71,AR,NTT,ELECTRICAL

In [23]:
# top 5 RSP
df_tmp = df_portfolio_features.sort_values(by = 'RSP', ascending=False)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
26,FINCABLES,2.50,10.32,88.46,107.91,144089.0,15242.0,162886.0,1641.55,-0.56,52.0,M-SC,8.29,220.0,0.11,1.23,22.55,OX40N,ATH,CABLES
1,ABB,1.71,15.95,25.54,45.57,77478.0,41741.0,303360.0,7934.00,-25.51,61.0,H-MC,13.04,125.0,0.54,2.29,34.71,AR,NTT,ELECTRICAL
30,HAPPSTMNDS,5.44,-51.08,277.88,84.85,174220.0,-65469.0,62696.0,1480.71,-41.79,54.0,H-SC,27.44,152.0,-0.38,0.47,16.10,AR,ATH,IT
80,VALIANTORG,-1.68,-47.00,228.56,74.15,198200.0,-76888.0,86717.0,838.00,-255.96,61.0,H-SC,28.77,145.0,-0.39,0.66,29.05,XR,NTT,CHEMICALS
69,SURYODAY,-1.76,-28.68,72.51,23.03,92605.0,-51357.0,127714.0,216.00,38.16,45.0,H-SC,6.64,166.0,-0.55,0.97,24.82,XR,NTT,BANKS

In [24]:
# Top N allocation
df_tmp = df_portfolio_features.sort_values(by = 'CurrAlloc%', ascending=False)
top_n_values = [10, 25, 50]

sum_df = pd.DataFrame({
    'Top_N': top_n_values,
    'Sum_Alloc%': [df_tmp['CurrAlloc%'].head(n).sum() for n in top_n_values]
})

sum_df

   Top_N  Sum_Alloc%
0     10       20.68
1     25       45.63
2     50       78.03

In [25]:
# market-cap-wise allocation
df_tmp = df_portfolio_features[cols]
df_tmp.groupby(df_tmp['Conviction'].str[-2:])['CurrAlloc%'].sum().sort_values(ascending=False)

Conviction
SC    44.48
MC    30.22
LC    25.32
Name: CurrAlloc%, dtype: float64

In [26]:
# criteria-wise allocation
df_portfolio_features.groupby('Criteria')['CurrAlloc%'].sum().sort_values(ascending=False)

Criteria
XY24     26.96
X40      25.45
X40N     15.16
AR        9.20
XR        8.33
XY25      7.35
OX40N     6.78
SR        0.79
Name: CurrAlloc%, dtype: float64

In [27]:
# conviction-wise allocation
df_portfolio_features.groupby('Conviction')['CurrAlloc%'].sum().sort_values(ascending=False)

Conviction
X-LC    23.13
X-MC    22.73
H-SC    21.60
X-SC    12.25
M-SC    10.09
H-MC     5.08
M-MC     2.05
H-LC     1.19
M-LC     1.00
L-SC     0.54
L-MC     0.36
Name: CurrAlloc%, dtype: float64

In [28]:
# sector-wise stats
df_tmp = df_portfolio_features.groupby('Category')[['CurrAlloc%', 'Current', 'Current P/L', 'FTT Amt']].sum().sort_values(by=['Current', 'Current P/L'], ascending=False)
df_tmp['Current P/L%'] = round(df_tmp['Current P/L'] * 100 / df_tmp['Current'], 2)
df_tmp['FTT%'] = round(df_tmp['FTT Amt'] * 100 / df_tmp['Current'], 2)
cols = ['CurrAlloc%', 'Current P/L%', 'FTT%']
df_tmp[cols].sort_values(by=['CurrAlloc%'], ascending=False)

               CurrAlloc%  Current P/L%    FTT%
Category
FMCG                15.16        -24.69   68.96
FINANCE             13.14        -23.72   74.14
IT                  11.66        -46.27  120.71
MISC                 6.93        -46.18  109.68
ELECTRICAL           6.63        -10.41   52.68
PAINTS               5.06        -47.36   72.95
INSURANCE            4.71         -8.96   46.25
BANKS                4.59        -26.96   91.41
PHARMA               4.15         -7.29   41.06
AUTO                 3.67        -34.75   88.21
AC                   2.09        -15.73   47.11
HEALTHCARE           1.90        -42.51   79.69
TRAVEL               1.81        -86.97  180.59
DURABLES             1.81        -61.84  101.21
FOOTWEAR             1.77        -88.05  163.45
BREWERIES            1.71         -3.64   25.16
APPARELS             1.71        -18.81   59.34
REALTY               1.46        -14.90   33.78
REFINERIES           1.39         -9.38   37.06
CERAMICS             1.38        -68.36  119.51
CEMENT               1.24        -63.20  185.30
CABLES               1.23          9.36   88.46
ENGINEERING          1.09        -67.97  144.80
JEWELLERY            1.08       -124.49  202.48
CHEMICALS            1.08        -85.68  237.16
ENTERTAINMENT        0.77        -90.34  203.86
TEXTILES             0.45        -55.24   99.50
HOTELS               0.35       -148.38  235.99

In [29]:
# money to be made criteria-wise
df_portfolio_features.groupby('Criteria')['FTT Amt'].agg(['sum', 'count']).sort_values(by='sum', ascending=False)

                sum  count
Criteria
XY24      4031734.0     21
X40       1811147.0     16
XR        1392981.0     12
AR        1354928.0     10
X40N      1297015.0     10
OX40N      895214.0     10
XY25       468894.0      5
SR         315204.0      2

In [30]:
# money to be made conviction-wise
df_portfolio_features.groupby('Conviction')['FTT Amt'].agg(['sum', 'count']).sort_values(by='sum', ascending=False)

                  sum  count
Conviction
H-SC        3938670.0     24
X-MC        1731094.0     15
X-LC        1719476.0     13
M-SC        1584280.0     14
X-SC        1561138.0     10
H-MC         406807.0      3
L-SC         219660.0      2
M-LC         160000.0      1
M-MC         114351.0      2
H-LC          76294.0      1
L-MC          55347.0      1

In [31]:
# money to be made criteria and conviction-wise
df_portfolio_features.groupby(['Conviction', 'Criteria'])['FTT Amt'].agg(['sum', 'count']).sort_values(by='sum', ascending=False)

                           sum  count
Conviction Criteria
H-SC       XY24      1368929.0      6
           AR         983241.0      5
X-LC       X40        928234.0      7
M-SC       XY24       924243.0      6
H-SC       XR         877320.0      7
X-SC       XY24       850370.0      4
X-MC       X40        678418.0      7
           X40N       525026.0      4
X-SC       X40N       506273.0      4
H-SC       OX40N      393976.0      4
M-SC       OX40N      389461.0      5
X-LC       XY24       375064.0      2
H-SC       SR         315204.0      2
X-MC       XY24       271552.0      2
X-LC       X40N       265716.0      2
X-MC       XY25       256098.0      2
H-MC       XY24       241576.0      1
X-SC       X40        204495.0      2
M-SC       XR         192431.0      2
H-MC       AR         165231.0      2
M-LC       XR         160000.0      1
X-LC       XY25       150462.0      2
L-SC       OX40N      111777.0      1
           XR         107883.0      1
M-SC       AR          78145.0      1
H-LC       AR          76294.0      1
M-MC       XY25        62334.0      1
L-MC       XR          55347.0      1
M-MC       AR          52017.0      1

In [32]:
# notebook execution time

end_time = time.time()
execution_time = round(end_time - start_time, 0)
print(f"Notebook execution time: {execution_time} seconds")

Notebook execution time: 28.0 seconds