<a href="https://colab.research.google.com/github/ankit-rathi/Quantvesting_v2/blob/main/myStocks_Portfolio_Analysis.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
'''
!pip install pandas==2.2.2 -qq
!pip install pyxirr -qq
!pip install ta -qq
!pip install yfinance==0.2.59 -qq
'''

'\n!pip install pandas==2.2.2 -qq\n!pip install pyxirr -qq\n!pip install ta -qq\n!pip install yfinance==0.2.59 -qq\n'

In [2]:
# import libraries

import numpy as np
import pandas as pd
import datetime
import warnings
warnings.filterwarnings('ignore')
import yfinance as yfin
import ta
import matplotlib.pyplot as plt
import requests

In [3]:
# notebook start time
import time
import datetime
import pytz

start_time = time.time()

# function to print date timestamp
def print_date_time():
  tz_NY = pytz.timezone('Asia/Kolkata')
  datetime_NY = datetime.datetime.now(tz_NY)
  print("Run date time (IST):", datetime_NY.strftime("%Y-%m-%d %H:%M:%S"))

In [4]:
# function to get booked and reserved amount
def get_amt():
  # fetch the JSON data from the URL
  url = "https://raw.githubusercontent.com/ankit-rathi/Tradevesting_v1/main/data/myPortfolioAmts.json"
  response = requests.get(url)
  pf_amts = response.json()  # parse the JSON data

  # extract values from the JSON
  py_booked_amt_dm = pf_amts["py_booked_amt_dm"]
  py_booked_amt_sv = pf_amts["py_booked_amt_sv"]
  cy_booked_amt_dm = pf_amts["cy_booked_amt_dm"]
  cy_booked_amt_sv = pf_amts["cy_booked_amt_sv"]
  reserve_amt_dm = pf_amts["reserve_amt_dm"]
  reserve_amt_sv = pf_amts["reserve_amt_sv"]

  # perform calculations
  py_booked_amt = py_booked_amt_dm + py_booked_amt_sv
  cy_booked_amt = cy_booked_amt_dm + cy_booked_amt_sv
  reserve_amt = reserve_amt_dm + reserve_amt_sv
  total_booked_amt = py_booked_amt + cy_booked_amt

  return total_booked_amt, reserve_amt, cy_booked_amt, py_booked_amt

gen_output = 0

In [5]:
# function to format the amount
def format_amt(number):
    abs_number = abs(number)

    if abs_number >= 1_00_00_000:  # Crores
        formatted_amt = f"{number / 1_00_00_000:.2f} C"
    elif abs_number >= 1_00_000:  # Lakhs
        formatted_amt = f"{number / 1_00_000:.2f} L"
    elif abs_number >= 1_000:  # Thousands
        formatted_amt = f"{number / 1_000:.2f} K"
    else:
        formatted_amt = f"{number:.2f}"

    return formatted_amt

# function to set start and end date
def get_start_end_date():
  start_date = (datetime.date.today() + datetime.timedelta(days=-365)).strftime('%Y-%m-%d')
  end_date = (datetime.date.today() + datetime.timedelta(days=1)).strftime('%Y-%m-%d')
  return start_date, end_date

# function to fetch my portfolio csv
def get_mypfs_df():
  mypfs_df = pd.read_csv('https://raw.githubusercontent.com/ankit-rathi/Tradevesting_v1/main/data/myPortfolioStocks.csv')
  return mypfs_df

# function to fetch my prospects csv
def get_mypps_df():
  mypps_df = pd.read_csv('https://raw.githubusercontent.com/ankit-rathi/Tradevesting_v1/main/data/myProspectsScrips.csv')
  return mypps_df

# function to fetch screener data
def get_myscreen_df():
  myscreen_df = pd.read_csv('https://raw.githubusercontent.com/ankit-rathi/Tradevesting_v1/main/data/myScreenerDB.csv')
  return myscreen_df

# function to fetch momentum data
def get_myinvmt_df():
  myinvmt_df = pd.read_csv('https://raw.githubusercontent.com/ankit-rathi/Tradevesting_v1/main/data/myInvestments.csv')
  return myinvmt_df

# function to get the stock ids
def get_stock_ids(df_pf):
  stock_n100 = df_pf['Symbol'].unique()

  exclude = ['CADILAHC','MMTC', 'MASFIN']

  stock_ids = df_pf[~df_pf['Symbol'].isin(exclude) ]['Symbol'].unique()

  #mypf = mypf[mypf.Forecast.notnull()]
  #stock_ids = mypf['Symbol'].unique()

  #stock_ids.sort()
  return stock_ids

# get features from screener data
def get_screener_features():
  myscreen_df = get_myscreen_df()
  cols = ['Symbol', 'EPS', 'MedPE', 'ROCE%', 'ROE%', 'CapType']
  return myscreen_df[cols]

# get relative strength
def get_relative_strength(stock_list):

    # Dictionary to store stock tickers and their corresponding percentage price change
    stock_changes = {}

    # Loop through each stock and fetch its price data
    for stock in stock_list:
        try:
            # Download the stock data for the given date range
            stock_data = yfin.Ticker(stock + '.NS').history(period='1mo', interval='1d')[map(str.title, ['open', 'close', 'low', 'high', 'volume'])]

            # Calculate the percentage change for the stock
            if len(stock_data) > 0:
                start_price = stock_data['Close'].iloc[0]
                end_price = stock_data['Close'].iloc[-1]
                percent_change = round(((end_price - start_price) / start_price) * 100, 2)
                stock_changes[stock] = percent_change
            else:
                stock_changes[stock] = np.nan  # If no data is available, set to NaN

        except Exception as e:
            print(f"Error fetching data for {stock}: {e}")
            stock_changes[stock] = np.nan

    # Create a DataFrame with stock tickers and their percentage changes
    df = pd.DataFrame(list(stock_changes.items()), columns=['Symbol', 'Percent_Change'])

    # Drop any stocks with missing data (NaN values)
    df = df.dropna()

    # Calculate the percentile rank based on percentage change
    df['RSP'] = round(df['Percent_Change'].rank(pct=True) * 100, 2)
    cols = ['Symbol', 'RSP']
    df = df[cols]
    # Sort by percentile rank (optional)
    df = df.sort_values(by='RSP', ascending=False).reset_index(drop=True)

    return df

In [6]:
# function to get stock technicals
def stock_prec_dev(stock_symbol):
    #stock_symbol = 'ULTRACEMCO.NS'
    short_window = 20
    mid_window = 50
    long_window = 200
    moving_avg = 'SMA'

    start = datetime.datetime(*map(int, start_date.split('-')))
    end = datetime.datetime(*map(int, end_date.split('-')))

    stock_df = yfin.Ticker(stock_symbol + '.NS').history(period='max', interval='1d')[map(str.title, ['open', 'close', 'low', 'high', 'volume'])]

    stock_df['Max'] = round(max(stock_df['Close']),2)
    stock_df = stock_df[(stock_df.index <= end_date) & (stock_df.index >= start_date)]
    stock_df['200_SMA'] = round(stock_df['Close'].rolling(window = 200, min_periods = 1).mean(),0)
    stock_df['Dev%_200'] = round((stock_df['Close'] - stock_df['200_SMA'])*100/stock_df['200_SMA'],2)
    stock_df.dropna(axis = 0, inplace = True) # remove any null rows

    stock_df['20_SMA'] = stock_df['Close'].rolling(window=20).mean()
    stock_df['50_SMA'] = stock_df['Close'].rolling(window=50).mean()
    stock_df['Symbol'] = stock_symbol

    stock_df['Close'] = round(stock_df['Close'],2)
    stock_df['Min'] = round(min(stock_df['Close']),2)
    stock_df['RSI_14'] = ta.momentum.RSIIndicator(close=stock_df['Close'], window=14).rsi()
    stock_df['RSI_14'] = round(stock_df['RSI_14'],0)
    stock_df['Prev_Close'] = stock_df['Close'].shift(1)
    stock_df.drop(['Open', 'Low', 'High', 'Volume'], axis=1, inplace=True)
    stock_df = stock_df.tail(1)

    max_SMA = max(stock_df['20_SMA'].item(), stock_df['50_SMA'].item(), stock_df['200_SMA'].item())
    min_SMA = min(stock_df['20_SMA'].item(), stock_df['50_SMA'].item(), stock_df['200_SMA'].item())
    ABS_Spread = max_SMA - min_SMA
    stock_df['Spread%'] = round((ABS_Spread / stock_df['200_SMA'].item()) * 100,2)

    return stock_df

# function to compute stock attributes
def get_common_features(stock_ids, df_mypf):

  df_prec_dev = pd.DataFrame()
  df_tmp = get_screener_features()
  df_rs = get_relative_strength(stock_ids)

  for stock_id in stock_ids:
      tmp = stock_prec_dev(stock_id)
      tmp = tmp.reset_index()
      df_prec_dev = pd.concat([df_prec_dev, tmp], ignore_index = True)
  df_prec_dev = pd.merge(df_prec_dev, df_mypf, on= 'Symbol')
  df_prec_dev = pd.merge(df_prec_dev, df_tmp, on= 'Symbol', how='left')
  df_prec_dev = pd.merge(df_prec_dev, df_rs, on= 'Symbol', how='left')
  #print(df_prec_dev.columns)
  df_prec_dev['Curr_PE'] = round(df_prec_dev['Close']/df_prec_dev['EPS'],1)
  df_prec_dev['Dev%_PE'] = round((df_prec_dev['Curr_PE'] - df_prec_dev['MedPE'])*100/df_prec_dev['MedPE'],2)
  df_prec_dev['Conviction'] = df_prec_dev['Conviction'] + '-' + df_prec_dev['CapType']
  return df_prec_dev

# function to arrange stock features
def arrange_features(df_stocks, common_cols, diff_cols):
  df_stocks_common = df_stocks[common_cols].drop_duplicates()
  df_stocks_diff = df_stocks[diff_cols]
  df_stocks_diff['Investment'] = df_stocks_diff['AvgCost'] * df_stocks_diff['Shares']
  df_stocks_diff = df_stocks_diff.groupby(['Symbol'])[['Shares', 'Investment']].aggregate(['sum']).reset_index()
  df_stocks_diff.columns = ['Symbol', 'Shares', 'Investment']
  df_stocks_diff['AvgCost'] = round(df_stocks_diff['Investment']/df_stocks_diff['Shares'],2)
  df_stocks = pd.merge(df_stocks_diff, df_stocks_common, on='Symbol')
  return df_stocks

# plot fact distribution across dimension
def plot_pie_chart(df, dimension, fact):
  # grouping the data by category and calculating the sum of fact for each type
  grouped_data = df.groupby(dimension)[fact].sum()

  # sorting the grouped data in descending order
  grouped_data = grouped_data.sort_values(ascending=False)

  # creating a pie chart
  grouped_data.plot.pie(autopct='%1.1f%%', startangle=90, figsize=(6, 6))

  # adding a title and displaying the plot
  plt.title(f'{dimension} {fact} Distribution')
  plt.ylabel('')  # To hide the y-label
  plt.show()

In [7]:
# function to get portfolio features

def get_portfolio_features(df_common_features):

  print_date_time()
  print('-------------------')

  #df_common_features["Target"] = df_common_features["Target"].fillna(df_common_features["Max"])
  df_common_features['NTT'] = np.where(df_common_features['Strategy']== 'NTT', df_common_features["Target"], df_common_features['Max'])
  df_common_features['LTT'] = np.where(df_common_features['Strategy']== 'BTT', df_common_features["Target"], df_common_features['Max'])
  df_common_features['BOL'] = df_common_features['Min']

  tmp_df = df_common_features[df_common_features['Symbol'].isin(mypf_df[mypf_df['InPortfolio'] != 'NA'].Symbol.values)]
  print('qualified stocks: '+str(len(tmp_df['Symbol'].unique())))
  tmp_df1 = tmp_df[tmp_df['LatestQtr'] == 1]
  print('with latest results: '+str(len(tmp_df1['Symbol'].unique())))
  tmp_df1 = tmp_df1[tmp_df1['StarStock'] == 1]
  print('still star stocks: '+str(len(tmp_df1['Symbol'].unique())))
  tmp_df['Investment'] = tmp_df['AvgCost'] * tmp_df['Shares']
  tmp_df['Current'] = round(tmp_df['Close'] * tmp_df['Shares'],0)
  tmp_df['Previous'] = tmp_df['Prev_Close'] * tmp_df['Shares']
  tmp_df['EstimatedST'] = tmp_df['NTT'] * tmp_df['Shares']
  tmp_df['EstimatedLT'] = tmp_df['LTT'] * tmp_df['Shares']
  tmp_df['Current P/L'] = round((tmp_df['Current'] - tmp_df['Investment']),0)
  tmp_df['Today P/L%'] = round((tmp_df['Current'] - tmp_df['Previous'])*100/tmp_df['Previous'],2)
  tmp_df['Current P/L%'] = round((tmp_df['Current'] - tmp_df['Investment'])*100/tmp_df['Investment'],2)
  tmp_df['EstimatedST P/L%'] = round((tmp_df['EstimatedST'] - tmp_df['Investment'])*100/tmp_df['Investment'],2)
  tmp_df['EstimatedLT P/L%'] = round((tmp_df['EstimatedLT'] - tmp_df['Investment'])*100/tmp_df['Investment'],2)
  tmp_df['NTT%'] = round((tmp_df['NTT'] - tmp_df['Close'])*100/tmp_df['Close'],2)
  tmp_df['LTT%'] = round((tmp_df['LTT'] - tmp_df['Close'])*100/tmp_df['Close'],2)
  tmp_df['Gained%'] = round((tmp_df['Close'] - tmp_df['BOL'])*100/tmp_df['BOL'],2)
  investment = round(sum(tmp_df['AvgCost']*tmp_df['Shares']),0)
  current = round(sum(tmp_df['Close']*tmp_df['Shares']),0)
  tmp_df['InitAlloc%'] = round(tmp_df['Investment']*100/investment,2)
  tmp_df['CurrAlloc%'] = round(tmp_df['Current']*100/current,2)
  tmp_df['FTT'] = tmp_df['LTT']
  tmp_df.loc[tmp_df['Strategy'] == 'NTT', 'FTT'] = tmp_df['NTT']
  tmp_df['FTT%'] = tmp_df['LTT%']
  tmp_df.loc[tmp_df['Strategy'] == 'NTT', 'FTT%'] = tmp_df['NTT%']
  tmp_df['FTT Amt'] = round(tmp_df['FTT%'] * tmp_df['Current']/100,0)
  tmp_df['OTT%'] = round((tmp_df['FTT'] - tmp_df['AvgCost'])*100/tmp_df['AvgCost'],2)
  tmp_df['RRR Ind'] = round(tmp_df['Current P/L']/tmp_df['FTT Amt'],2)
  tmp_df['Risk Ind'] = round(tmp_df['Current P/L%']*tmp_df['CurrAlloc%'],0)

  return tmp_df

# function to print portfolio features
def print_portfolio_stats(df_portfolio_features, myinvmt_df):
  from pyxirr import xirr

  total_booked_amt, reserve_amt, cy_booked_amt, py_booked_amt = get_amt()

  dates = myinvmt_df['Date'].values
  dates = np.append(dates, datetime.date.today().strftime('%d-%b-%y'))
  investment = myinvmt_df['Investment'].values
  dates= pd.to_datetime(dates)

  current = round(sum(df_portfolio_features['Close']*df_portfolio_features['Shares']),0) + reserve_amt
  investment_xirr = np.append(investment, current)
  cagr = round(xirr(pd.DataFrame({"dates": dates, "amounts": investment_xirr}))*100,2)

  investment = -sum(investment)
  invested = round(sum(df_portfolio_features['AvgCost']*df_portfolio_features['Shares']),0) + reserve_amt
  previous = round(sum(df_portfolio_features['Prev_Close']*df_portfolio_features['Shares']),0) + reserve_amt
  cy_invested = investment + py_booked_amt

  today_pnl_amount = current-previous
  today_pnl_percentage = round((current-previous)*100/previous,2)

  curr_pnl_amount = current-invested
  curr_pnl_percentage = round((curr_pnl_amount)*100/(cy_invested),2)

  cy_pnl_amount = cy_booked_amt + curr_pnl_amount
  cy_pnl_percentage = round((cy_pnl_amount)*100/cy_invested,2)

  overall_pnl_amount = total_booked_amt + curr_pnl_amount
  overall_pnl_percentage = round((overall_pnl_amount)*100/investment,2)

  estimate_st = round(sum(df_portfolio_features['FTT']*df_portfolio_features['Shares']),0)  + reserve_amt
  est_st_pnl_amount = estimate_st-current
  est_st_pnl_percentage = round((est_st_pnl_amount)*100/current,2)

  estimate_lt = round(sum(df_portfolio_features['LTT']*df_portfolio_features['Shares']),0)  + reserve_amt
  est_lt_pnl_amount = estimate_lt-current
  est_lt_pnl_percentage = round((est_lt_pnl_amount)*100/current,2)

  total_profit = round(sum(df_portfolio_features[df_portfolio_features['Current P/L%'] > 0]['Current']) - sum(df_portfolio_features[df_portfolio_features['Current P/L%'] > 0]['Investment']),0)
  total_loss = round(sum(df_portfolio_features[df_portfolio_features['Current P/L%'] < 0]['Current']) - sum(df_portfolio_features[df_portfolio_features['Current P/L%'] < 0]['Investment']),0)

  cy_booked_percentage = round((cy_booked_amt)*100/current,2)
  py_booked_percentage = round((py_booked_amt)*100/investment,2)
  total_booked_percentage = round((total_booked_amt)*100/investment,2)

  print('-------------------')
  print('Initial Investment: ', format_amt(investment))
  print('CY Investment: ', format_amt(cy_invested))
  print('Reserve: ', format_amt(reserve_amt))
  print('Current: ',  format_amt(current))
  print('-------------------')
  print('Today PnL: '+ '{} ({}%)'.format(format_amt(today_pnl_amount), today_pnl_percentage))
  print('Current PnL: '+ '{} ({}%)'.format(format_amt(curr_pnl_amount), curr_pnl_percentage))
  print('CY Booked + Current PnL: '+ '{} ({}%)'.format(format_amt(cy_pnl_amount), cy_pnl_percentage))
  print('-------------------')
  print('Total profit: ', format_amt(total_profit))
  print('Total loss: ', format_amt(total_loss))
  print('-------------------')
  print('Total Booked + Current PnL: '+ '{} ({}%)'.format(format_amt(overall_pnl_amount), overall_pnl_percentage))
  print('Total Booked PnL: '+ '{} ({}%)'.format(format_amt(total_booked_amt), total_booked_percentage))
  print('Curr Year Booked PnL: '+ '{} ({}%)'.format(format_amt(cy_booked_amt), cy_booked_percentage))
  print('Prev Year Booked PnL: '+ '{} ({}%)'.format(format_amt(py_booked_amt), py_booked_percentage))
  print('===================')
  print('Est FTT: ',  format_amt(estimate_st))
  print('Est FTT PnL: '+ '{} ({}%)'.format(format_amt(est_st_pnl_amount), est_st_pnl_percentage))

  print('===================')
  print('Deployed: ', format_amt(investment))

  print('Current: ', format_amt(current))

  print('CAGR/XIRR %: '+'{}%'.format(cagr))

In [8]:
# get start and end date
start_date, end_date = get_start_end_date()

# get portfolio and prospects data
mypfs_df = get_mypfs_df()
mypps_df = get_mypps_df()
myinvmt_df = get_myinvmt_df()

# merge above datasets
mypf_df = pd.merge(mypfs_df, mypps_df, on="Symbol")

# seggregate dm and sv portfolio
dm_pf = mypf_df[mypf_df['InPortfolio'] == 'DM']
sv_pf = mypf_df[mypf_df['InPortfolio'] == 'SV']

# build portfolio stock dataframe
dm_stocks = get_stock_ids(dm_pf)
sv_stocks = get_stock_ids(sv_pf)
df_stocks = pd.concat([dm_pf,sv_pf], ignore_index = True)

# arrange common and diff stock features
common_cols = ['Symbol', 'Target', 'Criteria', 'Strategy', 'CumlRnk', 'LatestQtr', 'StarStock', 'Conviction', 'Category', 'InFolio', 'XIRR', 'MBQ']
diff_cols = ['Symbol', 'AvgCost', 'Shares']
df_stocks = arrange_features(df_stocks, common_cols, diff_cols)

# get common features
stock_ids = df_stocks['Symbol'].values
df_common_features = get_common_features(stock_ids, df_stocks)

df_common_features.reset_index(drop=True, inplace=True)
df_common_features.drop(['Date'], axis=1, inplace=True)
# get and print portfolio features
df_portfolio_features = get_portfolio_features(df_common_features)

print_portfolio_stats(df_portfolio_features, myinvmt_df)

df = df_portfolio_features
#plot_pie_chart(df, 'CapType', 'Current')
list_ox40n = list(df[df['MBQ'].str.contains('OX40N', na=False)]['Symbol'].values)

Run date time (IST): 2026-04-09 10:04:12
-------------------
qualified stocks: 86
with latest results: 26
still star stocks: 16
-------------------
Initial Investment:  1.36 C
CY Investment:  1.62 C
Reserve:  1.61 K
Current:  1.36 C
-------------------
Today PnL: -65.31 K (-0.48%)
Current PnL: -41.35 L (-25.45%)
CY Booked + Current PnL: -25.46 L (-15.67%)
-------------------
Total profit:  1.09 L
Total loss:  -42.44 L
-------------------
Total Booked + Current PnL: 1.52 L (1.12%)
Total Booked PnL: 42.87 L (31.64%)
Curr Year Booked PnL: 15.89 L (11.7%)
Prev Year Booked PnL: 26.98 L (19.91%)
===================
Est FTT:  2.48 C
Est FTT PnL: 1.12 C (82.57%)
===================
Deployed:  1.36 C
Current:  1.36 C
CAGR/XIRR %: 0.1%

In [9]:
# top 5 near their targets
cols = ['Symbol', 'Today P/L%', 'Current P/L%', 'FTT%', 'OTT%', 'FTT Amt', 'Current P/L', 'Current', 'FTT', 'Dev%_PE', 'RSI_14','Conviction', 'Spread%',  'CumlRnk', 'RRR Ind', 'CurrAlloc%', 'Gained%', 'Criteria', 'Strategy', 'Category']
df_tmp = df_portfolio_features[~df_portfolio_features['Symbol'].isin(['ENRIN','BLUSPRING','DIGITIDE'])]
df_tmp = df_tmp.sort_values(by = 'FTT Amt', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
50,MASFIN,-0.34,-4.93,27.87,21.57,25961.0,-4830.0,93150.0,397.04,-18.25,54.0,H-SC,4.73,167.0,-0.19,0.69,22.04,XR,ATH,FINANCE
77,TTKPRESTIG,-1.91,-38.62,63.07,0.09,39014.0,-38919.0,61858.0,770.00,43.65,47.0,M-SC,21.85,250.0,-1.00,0.46,10.15,OX40N,NTT,DURABLES
5,ANGELONE,1.37,11.18,11.69,24.18,39642.0,34112.0,339112.0,303.00,-83.85,69.0,X-SC,6.15,97.0,0.86,2.50,29.74,X40N,NTT,FINANCE
67,SONACOMS,-1.08,-8.67,52.29,39.09,48311.0,-8768.0,92391.0,804.02,-27.63,57.0,M-MC,7.94,193.0,-0.18,0.68,30.70,AR,ATH,AUTO
14,BOSCH-HCIL,3.62,-42.05,72.54,-0.01,53727.0,-53739.0,74066.0,2282.00,15052.17,58.0,M-SC,9.39,231.0,-1.00,0.55,26.07,OX40N,BTT,AC

In [10]:
# top 5 today
df_tmp = df_portfolio_features.sort_values(by = 'Today P/L%', ascending=False)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
14,BOSCH-HCIL,3.62,-42.05,72.54,-0.01,53727.0,-53739.0,74066.0,2282.00,15052.17,58.0,M-SC,9.39,231.0,-1.00,0.55,26.07,OX40N,BTT,AC
66,SIS,2.52,-30.83,75.30,21.26,57835.0,-34226.0,76806.0,528.00,1803.11,58.0,H-SC,14.50,168.0,-0.59,0.57,14.20,OX40N,NTT,MISC
36,HONAUT,2.39,-27.92,109.92,51.31,152789.0,-53838.0,139000.0,58357.33,-40.01,43.0,X-SC,18.91,90.0,-0.35,1.02,5.60,X40N,ATH,ELECTRICAL
22,DEN,2.01,-48.95,178.29,42.07,76879.0,-41344.0,43120.0,75.00,52.85,55.0,M-SC,21.94,235.0,-0.54,0.32,17.28,AR,NTT,ENTERTAINMENT
71,TANLA,1.86,-47.58,319.08,119.69,452896.0,-128823.0,141938.0,1943.92,-47.02,60.0,H-SC,26.39,147.0,-0.28,1.05,22.89,AR,ATH,IT

In [11]:
# bottom 5 today
df_tmp = df_portfolio_features.sort_values(by = 'Today P/L%', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
56,RAJOOENG,-2.78,-41.08,136.96,39.61,82710.0,-42110.0,60390.0,143.1,-60.06,55.0,H-SC,32.75,136.0,-0.51,0.44,29.37,AR,ATH,MISC
60,REPCOHOME,-2.52,-18.19,132.04,89.82,309470.0,-52129.0,234376.0,880.0,-59.02,54.0,H-SC,7.48,161.0,-0.17,1.73,12.67,XY24,NTT,FINANCE
55,RAJESHEXPO,-2.45,-80.97,425.89,0.07,111166.0,-111075.0,26102.0,518.0,857.07,41.0,L-SC,44.63,268.0,-1.00,0.19,22.54,OX40N,NTT,JEWELLERY
41,INDIGOPNTS,-2.28,-43.67,77.56,0.02,76262.0,-76233.0,98326.0,1408.0,50.11,46.0,M-SC,29.60,222.0,-1.00,0.72,11.56,OX40N,NTT,PAINTS
12,BATAINDIA,-2.24,-55.59,204.47,35.20,116828.0,-71533.0,57137.0,2096.0,-25.05,48.0,X-SC,34.37,91.0,-0.61,0.42,13.32,X40,NTT,FOOTWEAR

In [12]:
# top 5 to exit based on CumlRnk
df_tmp = df_portfolio_features[~df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])]
df_tmp = df_tmp[(df_tmp['Current P/L%'] > -1) & (df_tmp['Current P/L%'] < 1)].sort_values(by = 'CumlRnk', ascending=False)
df_tmp[cols].head()

Empty DataFrame
Columns: [Symbol, Today P/L%, Current P/L%, FTT%, OTT%, FTT Amt, Current P/L, Current, FTT, Dev%_PE, RSI_14, Conviction, Spread%, CumlRnk, RRR Ind, CurrAlloc%, Gained%, Criteria, Strategy, Category]
Index: []

In [13]:
# OX40N stocks to exit
df_tmp = df_portfolio_features[(df_portfolio_features['Symbol'].isin(list_ox40n))].sort_values(by = 'Current P/L%', ascending=False)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
26,FINCABLES,0.32,7.77,92.93,107.91,147860.0,11465.0,159109.0,1641.55,-3.09,53.0,M-SC,2.24,220.0,0.08,1.17,19.70,OX40N,ATH,CABLES
66,SIS,2.52,-30.83,75.30,21.26,57835.0,-34226.0,76806.0,528.00,1803.11,58.0,H-SC,14.50,168.0,-0.59,0.57,14.20,OX40N,NTT,MISC
18,CERA,-0.52,-34.27,88.48,23.89,102301.0,-60282.0,115621.0,9475.00,-36.52,60.0,H-SC,18.00,153.0,-0.59,0.85,11.11,OX40N,NTT,CERAMICS
72,TATAELXSI,-1.39,-36.98,109.51,32.03,90980.0,-48756.0,83079.0,9161.00,-21.20,50.0,H-SC,21.12,158.0,-0.54,0.61,9.96,OX40N,NTT,IT
48,KANSAINER,-1.47,-38.12,83.39,13.47,139145.0,-102807.0,166860.0,340.00,-46.84,52.0,H-SC,23.43,162.0,-0.74,1.23,16.55,XY24,NTT,PAINTS

In [14]:
# top 5 to book for rotation
df_tmp = df_portfolio_features[(df_portfolio_features['Current P/L%'] > 20) ].sort_values(by = 'CumlRnk', ascending=False)
df_tmp[cols].head()

Empty DataFrame
Columns: [Symbol, Today P/L%, Current P/L%, FTT%, OTT%, FTT Amt, Current P/L, Current, FTT, Dev%_PE, RSI_14, Conviction, Spread%, CumlRnk, RRR Ind, CurrAlloc%, Gained%, Criteria, Strategy, Category]
Index: []

In [15]:
# top 5 to monitor for exit
df_tmp = df_portfolio_features[~df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])]
df_tmp = df_tmp[(df_tmp['Current P/L%'] > 0) ].sort_values(by = 'Dev%_PE', ascending=False)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
26,FINCABLES,0.32,7.77,92.93,107.91,147860.0,11465.0,159109.0,1641.55,-3.09,53.0,M-SC,2.24,220.0,0.08,1.17,19.70,OX40N,ATH,CABLES
1,ABB,-1.04,19.20,22.12,45.57,68983.0,50237.0,311856.0,7934.00,-23.35,62.0,H-MC,14.75,125.0,0.73,2.30,38.48,AR,NTT,ELECTRICAL

In [16]:
# top 5 to book for rotation from weak conviction
df_tmp = df_portfolio_features[~df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])]
df_tmp = df_tmp[~df_tmp['Criteria'].isin(['XY25','XY24','X40', 'X40N'])].sort_values(by = 'RRR Ind', ascending=False)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
1,ABB,-1.04,19.20,22.12,45.57,68983.0,50237.0,311856.0,7934.00,-23.35,62.0,H-MC,14.75,125.0,0.73,2.30,38.48,AR,NTT,ELECTRICAL
26,FINCABLES,0.32,7.77,92.93,107.91,147860.0,11465.0,159109.0,1641.55,-3.09,53.0,M-SC,2.24,220.0,0.08,1.17,19.70,OX40N,ATH,CABLES
40,INDIAMART,0.62,-9.41,128.19,106.72,143233.0,-11601.0,111735.0,4810.62,-59.18,54.0,H-SC,12.93,140.0,-0.08,0.82,7.95,AR,ATH,MISC
85,ZYDUSLIFE,0.55,-5.46,43.47,35.63,86125.0,-11448.0,198126.0,1286.17,-17.57,52.0,H-MC,6.00,120.0,-0.13,1.46,10.30,AR,ATH,PHARMA
67,SONACOMS,-1.08,-8.67,52.29,39.09,48311.0,-8768.0,92391.0,804.02,-27.63,57.0,M-MC,7.94,193.0,-0.18,0.68,30.70,AR,ATH,AUTO

In [17]:
# top 5 to accumulate based on lowest RSI_14
df_tmp = df_portfolio_features[df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])].sort_values(by = 'RSI_14', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
53,PGHH,-0.39,-28.46,84.53,32.01,129121.0,-60768.0,152752.0,17616.87,-51.56,33.0,X-MC,20.62,57.0,-0.47,1.13,4.48,X40,ATH,FMCG
21,DABUR,-0.66,-17.02,73.17,43.70,150626.0,-42210.0,205858.0,735.00,-24.64,38.0,X-MC,13.16,70.0,-0.28,1.52,3.41,XY24,BTT,FMCG
82,VOLTAS,-1.53,-2.57,49.03,45.20,91593.0,-4932.0,186810.0,1856.00,11.52,38.0,X-MC,5.63,79.0,-0.05,1.38,4.05,XY25,NTT,AC
78,UNITDSPR,-1.03,-9.21,33.02,20.77,70192.0,-21569.0,212575.0,1644.00,-19.41,40.0,X-MC,4.96,64.0,-0.31,1.57,1.40,X40N,NTT,BREWERIES
37,ICICIGI,-0.30,-7.55,29.09,19.34,53814.0,-15118.0,184991.0,2252.93,-22.28,41.0,X-MC,7.25,66.0,-0.28,1.36,3.32,X40,ATH,INSURANCE

In [18]:
# top 5 to accumulate based on Spread and CumlRnk
df_tmp = df_portfolio_features[df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])]
df_tmp = df_tmp[(df_tmp['CumlRnk'] < 100)].sort_values(by = 'Spread%', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
65,SIEMENS,-0.88,-14.08,46.08,25.51,73677.0,-26205.0,159890.0,4671.50,34.19,54.0,H-LC,1.16,51.0,-0.36,1.18,17.75,AR,ATH,ELECTRICAL
59,RELIANCE,-0.80,-14.18,46.00,25.30,79338.0,-28490.0,172473.0,1952.00,-16.57,42.0,X-LC,4.68,21.0,-0.36,1.27,13.24,XY25,BTT,REFINERIES
78,UNITDSPR,-1.03,-9.21,33.02,20.77,70192.0,-21569.0,212575.0,1644.00,-19.41,40.0,X-MC,4.96,64.0,-0.31,1.57,1.40,X40N,NTT,BREWERIES
24,DMART,0.34,5.37,22.99,29.60,60466.0,13410.0,263010.0,5391.45,-11.13,66.0,X-LC,5.05,14.0,0.22,1.94,20.22,X40N,ATH,FMCG
82,VOLTAS,-1.53,-2.57,49.03,45.20,91593.0,-4932.0,186810.0,1856.00,11.52,38.0,X-MC,5.63,79.0,-0.05,1.38,4.05,XY25,NTT,AC

In [19]:
# top 5 to accumulate based on lowest Gained%
df_tmp = df_portfolio_features[df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])].sort_values(by = 'Gained%', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
78,UNITDSPR,-1.03,-9.21,33.02,20.77,70192.0,-21569.0,212575.0,1644.00,-19.41,40.0,X-MC,4.96,64.0,-0.31,1.57,1.40,X40N,NTT,BREWERIES
2,ABBOTINDIA,0.06,-13.23,36.07,18.07,55977.0,-23665.0,155190.0,35195.00,-26.09,44.0,X-MC,11.23,58.0,-0.42,1.14,1.49,X40,ATH,PHARMA
8,AWL,-0.55,-38.70,172.47,67.02,376685.0,-137903.0,218406.0,485.00,-67.02,44.0,X-SC,25.33,81.0,-0.37,1.61,3.31,XY24,NTT,FMCG
37,ICICIGI,-0.30,-7.55,29.09,19.34,53814.0,-15118.0,184991.0,2252.93,-22.28,41.0,X-MC,7.25,66.0,-0.28,1.36,3.32,X40,ATH,INSURANCE
21,DABUR,-0.66,-17.02,73.17,43.70,150626.0,-42210.0,205858.0,735.00,-24.64,38.0,X-MC,13.16,70.0,-0.28,1.52,3.41,XY24,BTT,FMCG

In [20]:
# top 5 to accumulate based on lowest CurrAlloc%
df_tmp = df_portfolio_features[df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])].sort_values(by = 'CurrAlloc%', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
58,RELAXO,-1.40,-64.23,325.76,52.31,169157.0,-93233.0,51927.0,1176.00,-61.96,43.0,X-SC,33.11,92.0,-0.55,0.38,16.10,X40N,NTT,FOOTWEAR
12,BATAINDIA,-2.24,-55.59,204.47,35.20,116828.0,-71533.0,57137.0,2096.00,-25.05,48.0,X-SC,34.37,91.0,-0.61,0.42,13.32,X40,NTT,FOOTWEAR
54,QUESS,-0.29,-22.77,125.16,73.90,103232.0,-24313.0,82480.0,424.00,-58.68,54.0,X-SC,22.02,80.0,-0.24,0.61,10.95,XY24,NTT,MISC
36,HONAUT,2.39,-27.92,109.92,51.31,152789.0,-53838.0,139000.0,58357.33,-40.01,43.0,X-SC,18.91,90.0,-0.35,1.02,5.60,X40N,ATH,ELECTRICAL
53,PGHH,-0.39,-28.46,84.53,32.01,129121.0,-60768.0,152752.0,17616.87,-51.56,33.0,X-MC,20.62,57.0,-0.47,1.13,4.48,X40,ATH,FMCG

In [21]:
# top 5 to accumulate based on CumlRnk
df_tmp = df_portfolio_features.sort_values(by = 'CumlRnk', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
45,ITC,0.12,-20.24,49.27,19.06,133674.0,-68857.0,271309.0,452.00,-56.33,50.0,X-LC,19.60,1.0,-0.52,2.00,5.25,X40,NTT,FMCG
73,TCS,0.23,-24.70,68.09,26.57,237525.0,-114433.0,348840.0,4311.59,-36.41,56.0,X-LC,18.30,2.0,-0.48,2.57,8.87,X40,ATH,IT
43,INFY,-2.09,-10.28,49.62,34.24,139300.0,-32154.0,280734.0,1972.00,-29.25,51.0,X-LC,14.43,3.0,-0.23,2.07,7.96,X40,NTT,IT
75,TMPV,0.15,-23.69,78.97,36.58,214445.0,-84289.0,271552.0,600.00,-83.62,54.0,X-LC,12.37,4.0,-0.39,2.00,13.18,XY24,NTT,AUTO
33,HCLTECH,-1.49,-6.60,32.59,23.83,73638.0,-15970.0,225954.0,1908.19,-1.99,57.0,X-LC,10.21,8.0,-0.22,1.66,9.71,X40,ATH,IT

In [22]:
# top 5 for average up
df_tmp = df_portfolio_features[(df_portfolio_features['Dev%_200'] > 5)].sort_values(by = 'CurrAlloc%', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
67,SONACOMS,-1.08,-8.67,52.29,39.09,48311.0,-8768.0,92391.0,804.02,-27.63,57.0,M-MC,7.94,193.0,-0.18,0.68,30.70,AR,ATH,AUTO
24,DMART,0.34,5.37,22.99,29.60,60466.0,13410.0,263010.0,5391.45,-11.13,66.0,X-LC,5.05,14.0,0.22,1.94,20.22,X40N,ATH,FMCG
1,ABB,-1.04,19.20,22.12,45.57,68983.0,50237.0,311856.0,7934.00,-23.35,62.0,H-MC,14.75,125.0,0.73,2.30,38.48,AR,NTT,ELECTRICAL
5,ANGELONE,1.37,11.18,11.69,24.18,39642.0,34112.0,339112.0,303.00,-83.85,69.0,X-SC,6.15,97.0,0.86,2.50,29.74,X40N,NTT,FINANCE

In [23]:
# top 5 RSP
df_tmp = df_portfolio_features.sort_values(by = 'RSP', ascending=False)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
80,VALIANTORG,0.29,-44.93,216.23,74.15,194823.0,-73505.0,90100.0,838.00,-262.20,61.0,H-SC,23.90,145.0,-0.38,0.66,34.08,XR,NTT,CHEMICALS
5,ANGELONE,1.37,11.18,11.69,24.18,39642.0,34112.0,339112.0,303.00,-83.85,69.0,X-SC,6.15,97.0,0.86,2.50,29.74,X40N,NTT,FINANCE
52,PAGEIND,0.52,-7.38,44.80,34.11,111359.0,-19809.0,248570.0,51418.64,-33.55,69.0,X-MC,17.94,55.0,-0.18,1.83,17.58,X40,ATH,APPARELS
30,HAPPSTMNDS,-1.18,-52.82,291.83,84.85,176452.0,-67701.0,60464.0,1480.71,-43.83,48.0,H-SC,23.02,152.0,-0.38,0.45,11.97,AR,ATH,IT
25,EASEMYTRIP,1.52,-55.79,229.59,45.70,179452.0,-98653.0,78162.0,26.40,-18.79,63.0,M-SC,14.09,204.0,-0.55,0.58,36.92,XY24,NTT,TRAVEL

In [24]:
# Top N allocation
df_tmp = df_portfolio_features.sort_values(by = 'CurrAlloc%', ascending=False)
top_n_values = [10, 25, 50]

sum_df = pd.DataFrame({
    'Top_N': top_n_values,
    'Sum_Alloc%': [df_tmp['CurrAlloc%'].head(n).sum() for n in top_n_values]
})

sum_df

   Top_N  Sum_Alloc%
0     10       21.14
1     25       46.09
2     50       77.87

In [25]:
# market-cap-wise allocation
df_tmp = df_portfolio_features[cols]
df_tmp.groupby(df_tmp['Conviction'].str[-2:])['CurrAlloc%'].sum().sort_values(ascending=False)

Conviction
SC    45.07
MC    29.34
LC    25.64
Name: CurrAlloc%, dtype: float64

In [26]:
# criteria-wise allocation
df_portfolio_features.groupby('Criteria')['CurrAlloc%'].sum().sort_values(ascending=False)

Criteria
XY24     27.26
X40      25.09
X40N     15.51
AR        9.20
XR        8.43
XY25      7.01
OX40N     6.76
SR        0.79
Name: CurrAlloc%, dtype: float64

In [27]:
# conviction-wise allocation
df_portfolio_features.groupby('Conviction')['CurrAlloc%'].sum().sort_values(ascending=False)

Conviction
X-LC    23.42
H-SC    22.09
X-MC    21.88
X-SC    12.36
M-SC    10.07
H-MC     5.04
M-MC     2.07
H-LC     1.18
M-LC     1.04
L-SC     0.55
L-MC     0.35
Name: CurrAlloc%, dtype: float64

In [28]:
# sector-wise stats
df_tmp = df_portfolio_features.groupby('Category')[['CurrAlloc%', 'Current', 'Current P/L', 'FTT Amt']].sum().sort_values(by=['Current', 'Current P/L'], ascending=False)
df_tmp['Current P/L%'] = round(df_tmp['Current P/L'] * 100 / df_tmp['Current'], 2)
df_tmp['FTT%'] = round(df_tmp['FTT Amt'] * 100 / df_tmp['Current'], 2)
cols = ['CurrAlloc%', 'Current P/L%', 'FTT%']
df_tmp[cols].sort_values(by=['CurrAlloc%'], ascending=False)

               CurrAlloc%  Current P/L%    FTT%
Category
FMCG                14.81        -24.40   68.54
FINANCE             13.48        -17.55   65.46
IT                  11.97        -38.76  109.37
MISC                 7.13        -38.67   98.91
ELECTRICAL           6.42        -11.07   53.60
PAINTS               5.18        -40.13   64.46
BANKS                4.68        -21.10   82.57
INSURANCE            4.55         -9.60   47.11
PHARMA               3.99         -8.45   42.59
AUTO                 3.76        -28.04   78.84
HEALTHCARE           1.95        -35.50   70.86
AC                   1.93        -22.49   55.70
TRAVEL               1.86        -77.63  166.58
APPARELS             1.83         -7.97   44.80
FOOTWEAR             1.80        -80.24  152.50
DURABLES             1.74        -64.16  104.10
BREWERIES            1.57        -10.15   33.02
REALTY               1.44        -13.64   32.31
CERAMICS             1.35        -66.81  117.49
REFINERIES           1.27        -16.52   46.00
CEMENT               1.23        -61.15  181.72
ENGINEERING          1.19        -49.97  118.57
CABLES               1.17          7.21   92.93
CHEMICALS            1.09        -77.87  222.98
JEWELLERY            1.05       -124.36  202.30
ENTERTAINMENT        0.80        -79.01  185.77
TEXTILES             0.45        -49.88   92.62
HOTELS               0.36       -132.20  214.10

In [29]:
# money to be made criteria-wise
df_portfolio_features.groupby('Criteria')['FTT Amt'].agg(['sum', 'count']).sort_values(by='sum', ascending=False)

                sum  count
Criteria
XY24      3900793.0     21
X40       1767095.0     16
XR        1346519.0     12
AR        1323194.0     10
X40N      1196101.0     10
OX40N      874682.0     10
XY25       489951.0      5
SR         312054.0      2

In [30]:
# money to be made conviction-wise
df_portfolio_features.groupby('Conviction')['FTT Amt'].agg(['sum', 'count']).sort_values(by='sum', ascending=False)

                  sum  count
Conviction
H-SC        3793382.0     24
X-MC        1764881.0     15
X-LC        1597033.0     13
M-SC        1552485.0     14
X-SC        1505736.0     10
H-MC         395141.0      3
L-SC         215865.0      2
M-LC         151213.0      1
M-MC         105395.0      2
H-LC          73677.0      1
L-MC          55581.0      1

In [31]:
# money to be made criteria and conviction-wise
df_portfolio_features.groupby(['Conviction', 'Criteria'])['FTT Amt'].agg(['sum', 'count']).sort_values(by='sum', ascending=False)

                           sum  count
Conviction Criteria
H-SC       XY24      1293657.0      6
           AR         969219.0      5
M-SC       XY24       895516.0      6
X-LC       X40        858440.0      7
X-SC       XY24       846568.0      4
H-SC       XR         845490.0      7
X-MC       X40        690304.0      7
           X40N       532632.0      4
X-SC       X40N       440817.0      4
M-SC       OX40N      390554.0      5
H-SC       OX40N      372962.0      4
X-LC       XY24       357875.0      2
H-SC       SR         312054.0      2
X-MC       XY25       274801.0      2
           XY24       267144.0      2
H-MC       XY24       240033.0      1
X-LC       X40N       222652.0      2
X-SC       X40        218351.0      2
M-SC       XR         189536.0      2
X-LC       XY25       158066.0      2
H-MC       AR         155108.0      2
M-LC       XR         151213.0      1
L-SC       OX40N      111166.0      1
           XR         104699.0      1
M-SC       AR          76879.0      1
H-LC       AR          73677.0      1
M-MC       XY25        57084.0      1
L-MC       XR          55581.0      1
M-MC       AR          48311.0      1

In [32]:
# notebook execution time

end_time = time.time()
execution_time = round(end_time - start_time, 0)
print(f"Notebook execution time: {execution_time} seconds")

Notebook execution time: 31.0 seconds