<a href="https://colab.research.google.com/github/ankit-rathi/Quantvesting_v2/blob/main/myStocks_Portfolio_Analysis.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
'''
!pip install pandas==2.2.2 -qq
!pip install pyxirr -qq
!pip install ta -qq
!pip install yfinance==0.2.59 -qq
'''

'\n!pip install pandas==2.2.2 -qq\n!pip install pyxirr -qq\n!pip install ta -qq\n!pip install yfinance==0.2.59 -qq\n'

In [2]:
# import libraries

import numpy as np
import pandas as pd
import datetime
import warnings
warnings.filterwarnings('ignore')
import yfinance as yfin
import ta
import matplotlib.pyplot as plt
import requests

In [3]:
# notebook start time
import time
import datetime
import pytz

start_time = time.time()

# function to print date timestamp
def print_date_time():
  tz_NY = pytz.timezone('Asia/Kolkata')
  datetime_NY = datetime.datetime.now(tz_NY)
  print("Run date time (IST):", datetime_NY.strftime("%Y-%m-%d %H:%M:%S"))

In [4]:
# function to get booked and reserved amount
def get_amt():
  # fetch the JSON data from the URL
  url = "https://raw.githubusercontent.com/ankit-rathi/Tradevesting_v1/main/data/myPortfolioAmts.json"
  response = requests.get(url)
  pf_amts = response.json()  # parse the JSON data

  # extract values from the JSON
  py_booked_amt_dm = pf_amts["py_booked_amt_dm"]
  py_booked_amt_sv = pf_amts["py_booked_amt_sv"]
  cy_booked_amt_dm = pf_amts["cy_booked_amt_dm"]
  cy_booked_amt_sv = pf_amts["cy_booked_amt_sv"]
  reserve_amt_dm = pf_amts["reserve_amt_dm"]
  reserve_amt_sv = pf_amts["reserve_amt_sv"]

  # perform calculations
  py_booked_amt = py_booked_amt_dm + py_booked_amt_sv
  cy_booked_amt = cy_booked_amt_dm + cy_booked_amt_sv
  reserve_amt = reserve_amt_dm + reserve_amt_sv
  total_booked_amt = py_booked_amt + cy_booked_amt

  return total_booked_amt, reserve_amt, cy_booked_amt, py_booked_amt

gen_output = 0

In [5]:
# function to format the amount
def format_amt(number):
    abs_number = abs(number)

    if abs_number >= 1_00_00_000:  # Crores
        formatted_amt = f"{number / 1_00_00_000:.2f} C"
    elif abs_number >= 1_00_000:  # Lakhs
        formatted_amt = f"{number / 1_00_000:.2f} L"
    elif abs_number >= 1_000:  # Thousands
        formatted_amt = f"{number / 1_000:.2f} K"
    else:
        formatted_amt = f"{number:.2f}"

    return formatted_amt

# function to set start and end date
def get_start_end_date():
  start_date = (datetime.date.today() + datetime.timedelta(days=-365)).strftime('%Y-%m-%d')
  end_date = (datetime.date.today() + datetime.timedelta(days=1)).strftime('%Y-%m-%d')
  return start_date, end_date

# function to fetch my portfolio csv
def get_mypfs_df():
  mypfs_df = pd.read_csv('https://raw.githubusercontent.com/ankit-rathi/Tradevesting_v1/main/data/myPortfolioStocks.csv')
  return mypfs_df

# function to fetch my prospects csv
def get_mypps_df():
  mypps_df = pd.read_csv('https://raw.githubusercontent.com/ankit-rathi/Tradevesting_v1/main/data/myProspectsScrips.csv')
  return mypps_df

# function to fetch screener data
def get_myscreen_df():
  myscreen_df = pd.read_csv('https://raw.githubusercontent.com/ankit-rathi/Tradevesting_v1/main/data/myScreenerDB.csv')
  return myscreen_df

# function to fetch momentum data
def get_myinvmt_df():
  myinvmt_df = pd.read_csv('https://raw.githubusercontent.com/ankit-rathi/Tradevesting_v1/main/data/myInvestments.csv')
  return myinvmt_df

# function to get the stock ids
def get_stock_ids(df_pf):
  stock_n100 = df_pf['Symbol'].unique()

  exclude = ['CADILAHC','MMTC', 'MASFIN']

  stock_ids = df_pf[~df_pf['Symbol'].isin(exclude) ]['Symbol'].unique()

  #mypf = mypf[mypf.Forecast.notnull()]
  #stock_ids = mypf['Symbol'].unique()

  #stock_ids.sort()
  return stock_ids

# get features from screener data
def get_screener_features():
  myscreen_df = get_myscreen_df()
  cols = ['Symbol', 'EPS', 'MedPE', 'ROCE%', 'ROE%', 'CapType']
  return myscreen_df[cols]

# get relative strength
def get_relative_strength(stock_list):

    # Dictionary to store stock tickers and their corresponding percentage price change
    stock_changes = {}

    # Loop through each stock and fetch its price data
    for stock in stock_list:
        try:
            # Download the stock data for the given date range
            stock_data = yfin.Ticker(stock + '.NS').history(period='1mo', interval='1d')[map(str.title, ['open', 'close', 'low', 'high', 'volume'])]

            # Calculate the percentage change for the stock
            if len(stock_data) > 0:
                start_price = stock_data['Close'].iloc[0]
                end_price = stock_data['Close'].iloc[-1]
                percent_change = round(((end_price - start_price) / start_price) * 100, 2)
                stock_changes[stock] = percent_change
            else:
                stock_changes[stock] = np.nan  # If no data is available, set to NaN

        except Exception as e:
            print(f"Error fetching data for {stock}: {e}")
            stock_changes[stock] = np.nan

    # Create a DataFrame with stock tickers and their percentage changes
    df = pd.DataFrame(list(stock_changes.items()), columns=['Symbol', 'Percent_Change'])

    # Drop any stocks with missing data (NaN values)
    df = df.dropna()

    # Calculate the percentile rank based on percentage change
    df['RSP'] = round(df['Percent_Change'].rank(pct=True) * 100, 2)
    cols = ['Symbol', 'RSP']
    df = df[cols]
    # Sort by percentile rank (optional)
    df = df.sort_values(by='RSP', ascending=False).reset_index(drop=True)

    return df

In [6]:
# function to get stock technicals
def stock_prec_dev(stock_symbol):
    #stock_symbol = 'ULTRACEMCO.NS'
    short_window = 20
    mid_window = 50
    long_window = 200
    moving_avg = 'SMA'

    start = datetime.datetime(*map(int, start_date.split('-')))
    end = datetime.datetime(*map(int, end_date.split('-')))

    stock_df = yfin.Ticker(stock_symbol + '.NS').history(period='max', interval='1d')[map(str.title, ['open', 'close', 'low', 'high', 'volume'])]

    stock_df['Max'] = round(max(stock_df['Close']),2)
    stock_df = stock_df[(stock_df.index <= end_date) & (stock_df.index >= start_date)]
    stock_df['200_SMA'] = round(stock_df['Close'].rolling(window = 200, min_periods = 1).mean(),0)
    stock_df['Dev%_200'] = round((stock_df['Close'] - stock_df['200_SMA'])*100/stock_df['200_SMA'],2)
    stock_df.dropna(axis = 0, inplace = True) # remove any null rows

    stock_df['20_SMA'] = stock_df['Close'].rolling(window=20).mean()
    stock_df['50_SMA'] = stock_df['Close'].rolling(window=50).mean()
    stock_df['Symbol'] = stock_symbol

    stock_df['Close'] = round(stock_df['Close'],2)
    stock_df['Min'] = round(min(stock_df['Close']),2)
    stock_df['RSI_14'] = ta.momentum.RSIIndicator(close=stock_df['Close'], window=14).rsi()
    stock_df['RSI_14'] = round(stock_df['RSI_14'],0)
    stock_df['Prev_Close'] = stock_df['Close'].shift(1)
    stock_df.drop(['Open', 'Low', 'High', 'Volume'], axis=1, inplace=True)
    stock_df = stock_df.tail(1)

    max_SMA = max(stock_df['20_SMA'].item(), stock_df['50_SMA'].item(), stock_df['200_SMA'].item())
    min_SMA = min(stock_df['20_SMA'].item(), stock_df['50_SMA'].item(), stock_df['200_SMA'].item())
    ABS_Spread = max_SMA - min_SMA
    stock_df['Spread%'] = round((ABS_Spread / stock_df['200_SMA'].item()) * 100,2)

    return stock_df

# function to compute stock attributes
def get_common_features(stock_ids, df_mypf):

  df_prec_dev = pd.DataFrame()
  df_tmp = get_screener_features()
  df_rs = get_relative_strength(stock_ids)

  for stock_id in stock_ids:
      tmp = stock_prec_dev(stock_id)
      tmp = tmp.reset_index()
      df_prec_dev = pd.concat([df_prec_dev, tmp], ignore_index = True)
  df_prec_dev = pd.merge(df_prec_dev, df_mypf, on= 'Symbol')
  df_prec_dev = pd.merge(df_prec_dev, df_tmp, on= 'Symbol', how='left')
  df_prec_dev = pd.merge(df_prec_dev, df_rs, on= 'Symbol', how='left')
  #print(df_prec_dev.columns)
  df_prec_dev['Curr_PE'] = round(df_prec_dev['Close']/df_prec_dev['EPS'],1)
  df_prec_dev['Dev%_PE'] = round((df_prec_dev['Curr_PE'] - df_prec_dev['MedPE'])*100/df_prec_dev['MedPE'],2)
  df_prec_dev['Conviction'] = df_prec_dev['Conviction'] + '-' + df_prec_dev['CapType']
  return df_prec_dev

# function to arrange stock features
def arrange_features(df_stocks, common_cols, diff_cols):
  df_stocks_common = df_stocks[common_cols].drop_duplicates()
  df_stocks_diff = df_stocks[diff_cols]
  df_stocks_diff['Investment'] = df_stocks_diff['AvgCost'] * df_stocks_diff['Shares']
  df_stocks_diff = df_stocks_diff.groupby(['Symbol'])[['Shares', 'Investment']].aggregate(['sum']).reset_index()
  df_stocks_diff.columns = ['Symbol', 'Shares', 'Investment']
  df_stocks_diff['AvgCost'] = round(df_stocks_diff['Investment']/df_stocks_diff['Shares'],2)
  df_stocks = pd.merge(df_stocks_diff, df_stocks_common, on='Symbol')
  return df_stocks

# plot fact distribution across dimension
def plot_pie_chart(df, dimension, fact):
  # grouping the data by category and calculating the sum of fact for each type
  grouped_data = df.groupby(dimension)[fact].sum()

  # sorting the grouped data in descending order
  grouped_data = grouped_data.sort_values(ascending=False)

  # creating a pie chart
  grouped_data.plot.pie(autopct='%1.1f%%', startangle=90, figsize=(6, 6))

  # adding a title and displaying the plot
  plt.title(f'{dimension} {fact} Distribution')
  plt.ylabel('')  # To hide the y-label
  plt.show()

In [7]:
# function to get portfolio features

def get_portfolio_features(df_common_features):

  print_date_time()
  print('-------------------')

  #df_common_features["Target"] = df_common_features["Target"].fillna(df_common_features["Max"])
  df_common_features['NTT'] = np.where(df_common_features['Strategy']== 'NTT', df_common_features["Target"], df_common_features['Max'])
  df_common_features['LTT'] = np.where(df_common_features['Strategy']== 'BTT', df_common_features["Target"], df_common_features['Max'])
  df_common_features['BOL'] = df_common_features['Min']

  tmp_df = df_common_features[df_common_features['Symbol'].isin(mypf_df[mypf_df['InPortfolio'] != 'NA'].Symbol.values)]
  print('qualified stocks: '+str(len(tmp_df['Symbol'].unique())))
  tmp_df1 = tmp_df[tmp_df['LatestQtr'] == 1]
  print('with latest results: '+str(len(tmp_df1['Symbol'].unique())))
  tmp_df1 = tmp_df1[tmp_df1['StarStock'] == 1]
  print('still star stocks: '+str(len(tmp_df1['Symbol'].unique())))
  tmp_df['Investment'] = tmp_df['AvgCost'] * tmp_df['Shares']
  tmp_df['Current'] = round(tmp_df['Close'] * tmp_df['Shares'],0)
  tmp_df['Previous'] = tmp_df['Prev_Close'] * tmp_df['Shares']
  tmp_df['EstimatedST'] = tmp_df['NTT'] * tmp_df['Shares']
  tmp_df['EstimatedLT'] = tmp_df['LTT'] * tmp_df['Shares']
  tmp_df['Current P/L'] = round((tmp_df['Current'] - tmp_df['Investment']),0)
  tmp_df['Today P/L%'] = round((tmp_df['Current'] - tmp_df['Previous'])*100/tmp_df['Previous'],2)
  tmp_df['Current P/L%'] = round((tmp_df['Current'] - tmp_df['Investment'])*100/tmp_df['Investment'],2)
  tmp_df['EstimatedST P/L%'] = round((tmp_df['EstimatedST'] - tmp_df['Investment'])*100/tmp_df['Investment'],2)
  tmp_df['EstimatedLT P/L%'] = round((tmp_df['EstimatedLT'] - tmp_df['Investment'])*100/tmp_df['Investment'],2)
  tmp_df['NTT%'] = round((tmp_df['NTT'] - tmp_df['Close'])*100/tmp_df['Close'],2)
  tmp_df['LTT%'] = round((tmp_df['LTT'] - tmp_df['Close'])*100/tmp_df['Close'],2)
  tmp_df['Gained%'] = round((tmp_df['Close'] - tmp_df['BOL'])*100/tmp_df['BOL'],2)
  investment = round(sum(tmp_df['AvgCost']*tmp_df['Shares']),0)
  current = round(sum(tmp_df['Close']*tmp_df['Shares']),0)
  tmp_df['InitAlloc%'] = round(tmp_df['Investment']*100/investment,2)
  tmp_df['CurrAlloc%'] = round(tmp_df['Current']*100/current,2)
  tmp_df['FTT'] = tmp_df['LTT']
  tmp_df.loc[tmp_df['Strategy'] == 'NTT', 'FTT'] = tmp_df['NTT']
  tmp_df['FTT%'] = tmp_df['LTT%']
  tmp_df.loc[tmp_df['Strategy'] == 'NTT', 'FTT%'] = tmp_df['NTT%']
  tmp_df['FTT Amt'] = round(tmp_df['FTT%'] * tmp_df['Current']/100,0)
  tmp_df['OTT%'] = round((tmp_df['FTT'] - tmp_df['AvgCost'])*100/tmp_df['AvgCost'],2)
  tmp_df['RRR Ind'] = round(tmp_df['Current P/L']/tmp_df['FTT Amt'],2)
  tmp_df['Risk Ind'] = round(tmp_df['Current P/L%']*tmp_df['CurrAlloc%'],0)

  return tmp_df

# function to print portfolio features
def print_portfolio_stats(df_portfolio_features, myinvmt_df):
  from pyxirr import xirr

  total_booked_amt, reserve_amt, cy_booked_amt, py_booked_amt = get_amt()

  dates = myinvmt_df['Date'].values
  dates = np.append(dates, datetime.date.today().strftime('%d-%b-%y'))
  investment = myinvmt_df['Investment'].values
  dates= pd.to_datetime(dates)

  current = round(sum(df_portfolio_features['Close']*df_portfolio_features['Shares']),0) + reserve_amt
  investment_xirr = np.append(investment, current)
  cagr = round(xirr(pd.DataFrame({"dates": dates, "amounts": investment_xirr}))*100,2)

  investment = -sum(investment)
  invested = round(sum(df_portfolio_features['AvgCost']*df_portfolio_features['Shares']),0) + reserve_amt
  previous = round(sum(df_portfolio_features['Prev_Close']*df_portfolio_features['Shares']),0) + reserve_amt
  cy_invested = investment + py_booked_amt

  today_pnl_amount = current-previous
  today_pnl_percentage = round((current-previous)*100/previous,2)

  curr_pnl_amount = current-invested
  curr_pnl_percentage = round((curr_pnl_amount)*100/(cy_invested),2)

  cy_pnl_amount = cy_booked_amt + curr_pnl_amount
  cy_pnl_percentage = round((cy_pnl_amount)*100/cy_invested,2)

  overall_pnl_amount = total_booked_amt + curr_pnl_amount
  overall_pnl_percentage = round((overall_pnl_amount)*100/investment,2)

  estimate_st = round(sum(df_portfolio_features['FTT']*df_portfolio_features['Shares']),0)  + reserve_amt
  est_st_pnl_amount = estimate_st-current
  est_st_pnl_percentage = round((est_st_pnl_amount)*100/current,2)

  estimate_lt = round(sum(df_portfolio_features['LTT']*df_portfolio_features['Shares']),0)  + reserve_amt
  est_lt_pnl_amount = estimate_lt-current
  est_lt_pnl_percentage = round((est_lt_pnl_amount)*100/current,2)

  total_profit = round(sum(df_portfolio_features[df_portfolio_features['Current P/L%'] > 0]['Current']) - sum(df_portfolio_features[df_portfolio_features['Current P/L%'] > 0]['Investment']),0)
  total_loss = round(sum(df_portfolio_features[df_portfolio_features['Current P/L%'] < 0]['Current']) - sum(df_portfolio_features[df_portfolio_features['Current P/L%'] < 0]['Investment']),0)

  cy_booked_percentage = round((cy_booked_amt)*100/current,2)
  py_booked_percentage = round((py_booked_amt)*100/investment,2)
  total_booked_percentage = round((total_booked_amt)*100/investment,2)

  print('-------------------')
  print('Initial Investment: ', format_amt(investment))
  print('CY Investment: ', format_amt(cy_invested))
  print('Reserve: ', format_amt(reserve_amt))
  print('Current: ',  format_amt(current))
  print('-------------------')
  print('Today PnL: '+ '{} ({}%)'.format(format_amt(today_pnl_amount), today_pnl_percentage))
  print('Current PnL: '+ '{} ({}%)'.format(format_amt(curr_pnl_amount), curr_pnl_percentage))
  print('CY Booked + Current PnL: '+ '{} ({}%)'.format(format_amt(cy_pnl_amount), cy_pnl_percentage))
  print('-------------------')
  print('Total profit: ', format_amt(total_profit))
  print('Total loss: ', format_amt(total_loss))
  print('-------------------')
  print('Total Booked + Current PnL: '+ '{} ({}%)'.format(format_amt(overall_pnl_amount), overall_pnl_percentage))
  print('Total Booked PnL: '+ '{} ({}%)'.format(format_amt(total_booked_amt), total_booked_percentage))
  print('Curr Year Booked PnL: '+ '{} ({}%)'.format(format_amt(cy_booked_amt), cy_booked_percentage))
  print('Prev Year Booked PnL: '+ '{} ({}%)'.format(format_amt(py_booked_amt), py_booked_percentage))
  print('===================')
  print('Est FTT: ',  format_amt(estimate_st))
  print('Est FTT PnL: '+ '{} ({}%)'.format(format_amt(est_st_pnl_amount), est_st_pnl_percentage))

  print('===================')
  print('Deployed: ', format_amt(investment))

  print('Current: ', format_amt(current))

  print('CAGR/XIRR %: '+'{}%'.format(cagr))

In [8]:
# get start and end date
start_date, end_date = get_start_end_date()

# get portfolio and prospects data
mypfs_df = get_mypfs_df()
mypps_df = get_mypps_df()
myinvmt_df = get_myinvmt_df()

# merge above datasets
mypf_df = pd.merge(mypfs_df, mypps_df, on="Symbol")

# seggregate dm and sv portfolio
dm_pf = mypf_df[mypf_df['InPortfolio'] == 'DM']
sv_pf = mypf_df[mypf_df['InPortfolio'] == 'SV']

# build portfolio stock dataframe
dm_stocks = get_stock_ids(dm_pf)
sv_stocks = get_stock_ids(sv_pf)
df_stocks = pd.concat([dm_pf,sv_pf], ignore_index = True)

# arrange common and diff stock features
common_cols = ['Symbol', 'Target', 'Criteria', 'Strategy', 'CumlRnk', 'LatestQtr', 'StarStock', 'Conviction', 'Category', 'InFolio', 'XIRR', 'MBQ']
diff_cols = ['Symbol', 'AvgCost', 'Shares']
df_stocks = arrange_features(df_stocks, common_cols, diff_cols)

# get common features
stock_ids = df_stocks['Symbol'].values
df_common_features = get_common_features(stock_ids, df_stocks)

df_common_features.reset_index(drop=True, inplace=True)
df_common_features.drop(['Date'], axis=1, inplace=True)
# get and print portfolio features
df_portfolio_features = get_portfolio_features(df_common_features)

print_portfolio_stats(df_portfolio_features, myinvmt_df)

df = df_portfolio_features
#plot_pie_chart(df, 'CapType', 'Current')
list_ox40n = list(df[df['MBQ'].str.contains('OX40N', na=False)]['Symbol'].values)

Run date time (IST): 2026-07-15 12:44:05
-------------------
qualified stocks: 92
with latest results: 31
still star stocks: 20
-------------------
Initial Investment:  1.40 C
CY Investment:  1.82 C
Reserve:  1.49 K
Current:  1.53 C
-------------------
Today PnL: 11.91 K (0.08%)
Current PnL: -30.24 L (-16.58%)
CY Booked + Current PnL: -28.16 L (-15.44%)
-------------------
Total profit:  4.80 L
Total loss:  -35.03 L
-------------------
Total Booked + Current PnL: 14.71 L (10.55%)
Total Booked PnL: 44.95 L (32.22%)
Curr Year Booked PnL: 2.08 L (1.36%)
Prev Year Booked PnL: 42.87 L (30.73%)
===================
Est FTT:  2.55 C
Est FTT PnL: 1.02 C (66.69%)
===================
Deployed:  1.40 C
Current:  1.53 C
CAGR/XIRR %: 4.17%

In [9]:
# top 5 near their targets
cols = ['Symbol', 'Today P/L%', 'Current P/L%', 'FTT%', 'OTT%', 'FTT Amt', 'Current P/L', 'Current', 'FTT', 'Dev%_PE', 'RSI_14','Conviction', 'Spread%',  'CumlRnk', 'RRR Ind', 'CurrAlloc%', 'Gained%', 'Criteria', 'Strategy', 'Category']
df_tmp = df_portfolio_features[~df_portfolio_features['Symbol'].isin(['ENRIN','BLUSPRING','DIGITIDE'])]
df_tmp = df_tmp.sort_values(by = 'FTT Amt', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
49,JSWINFRA,-2.75,14.97,1.27,16.43,3238.0,33190.0,254964.0,342.00,-1.46,62.0,X-MC,16.74,61.0,10.25,1.67,44.56,X40N,NTT,REALTY
59,PIDILITIND,0.11,12.15,5.55,18.37,8783.0,17140.0,158250.0,1670.26,-21.49,55.0,X-LC,8.50,5.0,1.95,1.03,24.25,X40,ATH,CHEMICALS
83,TTKPRESTIG,-0.11,-13.69,15.96,0.09,13883.0,-13793.0,86984.0,770.00,101.92,71.0,M-SC,7.78,250.0,-0.99,0.57,54.89,OX40N,NTT,DURABLES
55,MASFIN,-2.06,-0.87,22.64,21.57,21989.0,-855.0,97125.0,397.04,-14.63,56.0,H-SC,1.19,167.0,-0.04,0.64,15.77,XR,ATH,FINANCE
56,MEDANTA,1.44,14.62,10.90,27.12,22053.0,25808.0,202325.0,1486.00,11.13,61.0,X-SC,10.27,87.0,1.17,1.32,39.41,XY24,NTT,HEALTHCARE

In [10]:
# top 5 today
df_tmp = df_portfolio_features.sort_values(by = 'Today P/L%', ascending=False)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
0,5PAISA,5.81,-25.32,51.18,12.90,83513.0,-55320.0,163176.0,593.0,140.38,68.0,H-SC,9.61,170.0,-0.66,1.07,57.47,OX40N,NTT,FINANCE
9,BANDHANBNK,5.21,5.20,82.90,92.42,242945.0,14499.0,293058.0,400.0,151.44,61.0,H-SC,20.72,174.0,0.06,1.92,61.44,XY24,NTT,BANKS
80,TITAGARH,4.08,-16.78,75.12,45.74,151398.0,-40636.0,201541.0,1548.0,10.76,56.0,H-SC,9.75,175.0,-0.27,1.32,53.77,XY24,NTT,ENGINEERING
29,GREENPANEL,3.64,-45.84,164.27,43.14,162893.0,-83916.0,99162.0,537.0,122.22,61.0,M-SC,15.05,225.0,-0.52,0.65,19.12,XY24,NTT,MISC
38,HYUNDAI,3.23,7.54,38.87,49.35,64477.0,11637.0,165878.0,2809.3,-13.37,59.0,X-LC,9.87,29.0,0.18,1.08,19.60,X40N,ATH,AUTO

In [11]:
# bottom 5 today
df_tmp = df_portfolio_features.sort_values(by = 'Today P/L%', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
78,TATAELXSI,-8.04,-49.33,160.55,32.03,107254.0,-65031.0,66804.0,9161.0,-36.66,33.0,H-SC,18.03,158.0,-0.61,0.44,0.00,OX40N,NTT,IT
64,RELAXO,-4.58,-50.71,208.99,52.31,149539.0,-73607.0,71553.0,1176.0,-47.54,52.0,X-SC,12.19,92.0,-0.49,0.47,59.98,X40N,NTT,FOOTWEAR
21,DEN,-4.29,-45.07,158.62,42.07,73600.0,-38064.0,46400.0,75.0,65.80,48.0,M-SC,6.12,235.0,-0.52,0.30,26.20,AR,NTT,ENTERTAINMENT
61,RAJESHEXPO,-3.49,-82.91,485.58,0.07,113830.0,-113735.0,23442.0,518.0,758.59,41.0,L-SC,34.99,268.0,-1.00,0.15,15.77,OX40N,NTT,JEWELLERY
24,EASEMYTRIP,-3.27,-62.42,287.67,45.70,191162.0,-110363.0,66452.0,26.4,-30.95,40.0,M-SC,8.94,204.0,-0.58,0.43,16.41,XY24,NTT,TRAVEL

In [12]:
# top 5 to exit based on CumlRnk
df_tmp = df_portfolio_features[~df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])]
df_tmp = df_tmp[(df_tmp['Current P/L%'] > -1) & (df_tmp['Current P/L%'] < 1)].sort_values(by = 'CumlRnk', ascending=False)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
72,SIS,0.89,0.68,20.44,21.26,22850.0,760.0,111792.0,528.00,2669.95,61.0,H-SC,25.10,168.0,0.03,0.73,66.22,OX40N,NTT,MISC
55,MASFIN,-2.06,-0.87,22.64,21.57,21989.0,-855.0,97125.0,397.04,-14.63,56.0,H-SC,1.19,167.0,-0.04,0.64,15.77,XR,ATH,FINANCE

In [13]:
# OX40N stocks to exit
df_tmp = df_portfolio_features[(df_portfolio_features['Symbol'].isin(list_ox40n))].sort_values(by = 'Current P/L%', ascending=False)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
25,FINCABLES,0.43,31.36,58.28,107.91,113027.0,46294.0,193938.0,1641.55,18.21,43.0,M-SC,25.89,220.0,0.41,1.27,45.91,OX40N,ATH,CABLES
72,SIS,0.89,0.68,20.44,21.26,22850.0,760.0,111792.0,528.00,2669.95,61.0,H-SC,25.10,168.0,0.03,0.73,66.22,OX40N,NTT,MISC
83,TTKPRESTIG,-0.11,-13.69,15.96,0.09,13883.0,-13793.0,86984.0,770.00,101.92,71.0,M-SC,7.78,250.0,-0.99,0.57,54.89,OX40N,NTT,DURABLES
16,CERA,0.01,-19.61,54.12,23.89,76528.0,-34499.0,141404.0,9475.00,-22.43,49.0,H-SC,15.85,153.0,-0.45,0.92,37.46,OX40N,NTT,CERAMICS
69,SFL,-1.87,-22.09,62.53,26.63,127747.0,-57921.0,204297.0,1287.00,54.78,69.0,M-SC,22.93,242.0,-0.45,1.34,70.50,XY24,NTT,MISC

In [14]:
# top 5 to book for rotation
df_tmp = df_portfolio_features[(df_portfolio_features['Current P/L%'] > 20) ].sort_values(by = 'CumlRnk', ascending=False)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
25,FINCABLES,0.43,31.36,58.28,107.91,113027.0,46294.0,193938.0,1641.55,18.21,43.0,M-SC,25.89,220.0,0.41,1.27,45.91,OX40N,ATH,CABLES
68,SATIN,-3.05,43.55,5.77,51.83,22884.0,120322.0,396606.0,274.00,28.78,60.0,H-SC,43.25,159.0,5.26,2.59,93.21,XY24,NTT,FINANCE
91,ZYDUSLIFE,2.76,22.84,10.41,35.63,26800.0,47869.0,257443.0,1286.17,6.76,66.0,H-MC,16.39,120.0,1.79,1.68,35.36,AR,ATH,PHARMA
60,QUESS,-1.36,20.46,44.36,73.90,57065.0,21848.0,128641.0,424.00,-34.99,70.0,X-SC,27.21,80.0,0.38,0.84,75.36,XY24,NTT,MISC

In [15]:
# top 5 to monitor for exit
df_tmp = df_portfolio_features[~df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])]
df_tmp = df_tmp[(df_tmp['Current P/L%'] > 0) ].sort_values(by = 'Dev%_PE', ascending=False)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
72,SIS,0.89,0.68,20.44,21.26,22850.0,760.0,111792.0,528.0,2669.95,61.0,H-SC,25.10,168.0,0.03,0.73,66.22,OX40N,NTT,MISC
9,BANDHANBNK,5.21,5.20,82.90,92.42,242945.0,14499.0,293058.0,400.0,151.44,61.0,H-SC,20.72,174.0,0.06,1.92,61.44,XY24,NTT,BANKS
75,SURYODAY,1.27,8.03,13.89,23.03,26869.0,14372.0,193443.0,216.0,110.53,66.0,H-SC,21.44,166.0,0.53,1.26,62.87,XR,NTT,BANKS
74,STARHEALTH,-0.29,15.72,27.26,47.26,88680.0,44189.0,325312.0,761.0,82.66,68.0,H-SC,19.00,173.0,0.50,2.13,41.17,XY24,NTT,INSURANCE
68,SATIN,-3.05,43.55,5.77,51.83,22884.0,120322.0,396606.0,274.0,28.78,60.0,H-SC,43.25,159.0,5.26,2.59,93.21,XY24,NTT,FINANCE

In [16]:
# top 5 to book for rotation from weak conviction
df_tmp = df_portfolio_features[~df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])]
df_tmp = df_tmp[~df_tmp['Criteria'].isin(['XY25','XY24','X40', 'X40N'])].sort_values(by = 'RRR Ind', ascending=False)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
91,ZYDUSLIFE,2.76,22.84,10.41,35.63,26800.0,47869.0,257443.0,1286.17,6.76,66.0,H-MC,16.39,120.0,1.79,1.68,35.36,AR,ATH,PHARMA
73,SONACOMS,-0.59,15.37,20.21,38.69,23587.0,15549.0,116708.0,801.69,-8.59,69.0,M-MC,21.82,193.0,0.66,0.76,65.58,AR,ATH,AUTO
75,SURYODAY,1.27,8.03,13.89,23.03,26869.0,14372.0,193443.0,216.00,110.53,66.0,H-SC,21.44,166.0,0.53,1.26,62.87,XR,NTT,BANKS
25,FINCABLES,0.43,31.36,58.28,107.91,113027.0,46294.0,193938.0,1641.55,18.21,43.0,M-SC,25.89,220.0,0.41,1.27,45.91,OX40N,ATH,CABLES
72,SIS,0.89,0.68,20.44,21.26,22850.0,760.0,111792.0,528.00,2669.95,61.0,H-SC,25.10,168.0,0.03,0.73,66.22,OX40N,NTT,MISC

In [17]:
# top 5 to accumulate based on lowest RSI_14
df_tmp = df_portfolio_features[df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])].sort_values(by = 'RSI_14', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
87,VBL,-0.81,-5.78,43.67,35.37,129960.0,-18247.0,297595.0,670.16,-16.89,31.0,X-LC,8.38,13.0,-0.14,1.95,22.31,X40N,ATH,FMCG
47,ITC,0.45,-27.09,63.29,19.06,156967.0,-92153.0,248013.0,452.00,-59.97,33.0,X-LC,12.55,1.0,-0.59,1.62,0.45,X40,NTT,FMCG
23,DMART,0.00,-5.87,37.68,29.60,88533.0,-14640.0,234960.0,5391.45,-20.59,34.0,X-LC,2.64,14.0,-0.17,1.54,7.40,X40N,ATH,FMCG
81,TMPV,-0.10,-24.20,80.18,36.58,216270.0,-86111.0,269730.0,600.00,-84.72,37.0,X-LC,8.12,4.0,-0.40,1.76,13.36,XY24,NTT,AUTO
36,HINDUNILVR,-1.00,-18.35,39.21,13.67,82302.0,-47163.0,209900.0,2922.00,-39.37,39.0,X-LC,5.19,9.0,-0.57,1.37,3.32,XY25,NTT,FMCG

In [18]:
# top 5 to accumulate based on Spread and CumlRnk
df_tmp = df_portfolio_features[df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])]
df_tmp = df_tmp[(df_tmp['CumlRnk'] < 100)].sort_values(by = 'Spread%', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
17,CIPLA,1.28,16.98,14.07,33.43,25209.0,26007.0,179168.0,1648.14,-9.38,57.0,X-LC,2.33,18.0,1.03,1.17,22.31,X40N,ATH,PHARMA
23,DMART,0.00,-5.87,37.68,29.60,88533.0,-14640.0,234960.0,5391.45,-20.59,34.0,X-LC,2.64,14.0,-0.17,1.54,7.40,X40N,ATH,FMCG
11,BERGEPAINT,-0.30,-9.43,38.37,25.32,89571.0,-24310.0,233439.0,680.00,-14.30,39.0,X-MC,2.81,68.0,-0.27,1.53,21.50,XY24,NTT,PAINTS
19,COLPAL,-0.05,-23.77,83.47,39.86,167574.0,-62605.0,200760.0,3683.41,-7.87,45.0,X-MC,3.04,62.0,-0.37,1.31,13.56,XY25,ATH,FMCG
8,BAJAJHLDNG,0.23,-6.03,35.81,27.63,63982.0,-11455.0,178670.0,14274.15,-13.24,50.0,X-LC,3.98,28.0,-0.18,1.17,21.66,X40,ATH,FINANCE

In [19]:
# top 5 to accumulate based on lowest Gained%
df_tmp = df_portfolio_features[df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])].sort_values(by = 'Gained%', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
58,PGHH,-0.95,-33.90,99.70,32.01,140721.0,-72376.0,141144.0,17616.87,-55.31,39.0,X-MC,20.40,57.0,-0.51,0.92,0.10,X40,ATH,FMCG
47,ITC,0.45,-27.09,63.29,19.06,156967.0,-92153.0,248013.0,452.00,-59.97,33.0,X-LC,12.55,1.0,-0.59,1.62,0.45,X40,NTT,FMCG
65,RELIANCE,0.58,-16.52,50.10,25.30,84050.0,-33199.0,167764.0,1952.00,-18.88,48.0,X-LC,7.32,21.0,-0.39,1.10,3.31,XY25,BTT,REFINERIES
36,HINDUNILVR,-1.00,-18.35,39.21,13.67,82302.0,-47163.0,209900.0,2922.00,-39.37,39.0,X-LC,5.19,9.0,-0.57,1.37,3.32,XY25,NTT,FMCG
35,HDFCLIFE,-1.36,-7.50,43.46,32.71,60223.0,-11228.0,138572.0,811.41,-27.77,45.0,X-LC,14.92,31.0,-0.19,0.91,4.10,X40,ATH,INSURANCE

In [20]:
# top 5 to accumulate based on lowest CurrAlloc%
df_tmp = df_portfolio_features[df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])].sort_values(by = 'CurrAlloc%', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
10,BATAINDIA,-1.37,-55.74,205.49,35.20,117018.0,-71724.0,56946.0,2096.00,-25.34,48.0,X-SC,18.87,91.0,-0.61,0.37,12.94,X40,NTT,FOOTWEAR
64,RELAXO,-4.58,-50.71,208.99,52.31,149539.0,-73607.0,71553.0,1176.00,-47.54,52.0,X-SC,12.19,92.0,-0.49,0.47,59.98,X40N,NTT,FOOTWEAR
60,QUESS,-1.36,20.46,44.36,73.90,57065.0,21848.0,128641.0,424.00,-34.99,70.0,X-SC,27.21,80.0,0.38,0.84,75.36,XY24,NTT,MISC
35,HDFCLIFE,-1.36,-7.50,43.46,32.71,60223.0,-11228.0,138572.0,811.41,-27.77,45.0,X-LC,14.92,31.0,-0.19,0.91,4.10,X40,ATH,INSURANCE
53,M&M,0.22,0.59,21.38,22.10,29825.0,819.0,139500.0,3762.88,-14.78,50.0,X-LC,7.82,25.0,0.03,0.91,6.87,X40N,ATH,AUTO

In [21]:
# top 5 to accumulate based on CumlRnk
df_tmp = df_portfolio_features.sort_values(by = 'CumlRnk', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
47,ITC,0.45,-27.09,63.29,19.06,156967.0,-92153.0,248013.0,452.00,-59.97,33.0,X-LC,12.55,1.0,-0.59,1.62,0.45,X40,NTT,FMCG
79,TCS,0.14,-35.66,93.04,24.20,277313.0,-165215.0,298058.0,4230.71,-45.59,57.0,X-LC,21.36,2.0,-0.60,1.95,11.15,X40,ATH,IT
45,INFY,-1.13,-26.44,82.51,34.24,189893.0,-82742.0,230146.0,1972.00,-41.94,50.0,X-LC,21.56,3.0,-0.44,1.50,9.66,X40,NTT,IT
81,TMPV,-0.10,-24.20,80.18,36.58,216270.0,-86111.0,269730.0,600.00,-84.72,37.0,X-LC,8.12,4.0,-0.40,1.76,13.36,XY24,NTT,AUTO
59,PIDILITIND,0.11,12.15,5.55,18.37,8783.0,17140.0,158250.0,1670.26,-21.49,55.0,X-LC,8.50,5.0,1.95,1.03,24.25,X40,ATH,CHEMICALS

In [22]:
# top 5 for average up
df_tmp = df_portfolio_features[(df_portfolio_features['Dev%_200'] > 5)].sort_values(by = 'CurrAlloc%', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
44,INDUSINDBK,0.22,-25.05,77.31,32.89,44735.0,-19342.0,57864.0,1800.00,-372.41,67.0,L-MC,10.42,258.0,-0.43,0.38,42.66,XR,NTT,BANKS
3,ALKYLAMINE,-0.49,-19.33,138.67,92.54,112948.0,-19512.0,81451.0,4520.85,-13.57,59.0,H-SC,10.91,142.0,-0.17,0.53,54.67,SR,ATH,CHEMICALS
83,TTKPRESTIG,-0.11,-13.69,15.96,0.09,13883.0,-13793.0,86984.0,770.00,101.92,71.0,M-SC,7.78,250.0,-0.99,0.57,54.89,OX40N,NTT,DURABLES
72,SIS,0.89,0.68,20.44,21.26,22850.0,760.0,111792.0,528.00,2669.95,61.0,H-SC,25.10,168.0,0.03,0.73,66.22,OX40N,NTT,MISC
73,SONACOMS,-0.59,15.37,20.21,38.69,23587.0,15549.0,116708.0,801.69,-8.59,69.0,M-MC,21.82,193.0,0.66,0.76,65.58,AR,ATH,AUTO

In [23]:
# top 5 RSP
df_tmp = df_portfolio_features.sort_values(by = 'RSP', ascending=False)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
83,TTKPRESTIG,-0.11,-13.69,15.96,0.09,13883.0,-13793.0,86984.0,770.00,101.92,71.0,M-SC,7.78,250.0,-0.99,0.57,54.89,OX40N,NTT,DURABLES
0,5PAISA,5.81,-25.32,51.18,12.90,83513.0,-55320.0,163176.0,593.00,140.38,68.0,H-SC,9.61,170.0,-0.66,1.07,57.47,OX40N,NTT,FINANCE
60,QUESS,-1.36,20.46,44.36,73.90,57065.0,21848.0,128641.0,424.00,-34.99,70.0,X-SC,27.21,80.0,0.38,0.84,75.36,XY24,NTT,MISC
27,GLAXO,0.71,-0.41,36.25,35.69,71943.0,-820.0,198464.0,3380.16,-23.87,68.0,X-MC,4.28,56.0,-0.01,1.30,17.95,X40,ATH,PHARMA
49,JSWINFRA,-2.75,14.97,1.27,16.43,3238.0,33190.0,254964.0,342.00,-1.46,62.0,X-MC,16.74,61.0,10.25,1.67,44.56,X40N,NTT,REALTY

In [24]:
# Top N allocation
df_tmp = df_portfolio_features.sort_values(by = 'CurrAlloc%', ascending=False)
top_n_values = [10, 25, 50]

sum_df = pd.DataFrame({
    'Top_N': top_n_values,
    'Sum_Alloc%': [df_tmp['CurrAlloc%'].head(n).sum() for n in top_n_values]
})

sum_df

   Top_N  Sum_Alloc%
0     10       19.30
1     25       42.50
2     50       72.73

In [25]:
# market-cap-wise allocation
df_tmp = df_portfolio_features[cols]
df_tmp.groupby(df_tmp['Conviction'].str[-2:])['CurrAlloc%'].sum().sort_values(ascending=False)

Conviction
SC    43.97
LC    29.86
MC    26.16
Name: CurrAlloc%, dtype: float64

In [26]:
# criteria-wise allocation
df_portfolio_features.groupby('Criteria')['CurrAlloc%'].sum().sort_values(ascending=False)

Criteria
XY24     27.88
X40      24.62
X40N     17.30
XR        8.87
OX40N     7.11
AR        6.90
XY25      6.40
SR        0.91
Name: CurrAlloc%, dtype: float64

In [27]:
# conviction-wise allocation
df_portfolio_features.groupby('Conviction')['CurrAlloc%'].sum().sort_values(ascending=False)

Conviction
X-LC    27.89
H-SC    23.29
X-MC    21.00
M-SC    10.07
X-SC    10.06
H-MC     2.75
M-MC     2.03
H-LC     1.17
M-LC     0.80
L-SC     0.55
L-MC     0.38
Name: CurrAlloc%, dtype: float64

In [28]:
# sector-wise stats
df_tmp = df_portfolio_features.groupby('Category')[['CurrAlloc%', 'Current', 'Current P/L', 'FTT Amt']].sum().sort_values(by=['Current', 'Current P/L'], ascending=False)
df_tmp['Current P/L%'] = round(df_tmp['Current P/L'] * 100 / df_tmp['Current'], 2)
df_tmp['FTT%'] = round(df_tmp['FTT Amt'] * 100 / df_tmp['Current'], 2)
cols = ['CurrAlloc%', 'Current P/L%', 'FTT%']
df_tmp[cols].sort_values(by=['CurrAlloc%'], ascending=False)

               CurrAlloc%  Current P/L%    FTT%
Category
FMCG                14.04        -23.22   66.44
FINANCE             11.32         -6.54   52.71
IT                   9.96        -47.90  121.43
MISC                 7.28        -20.47   72.17
AUTO                 6.56         -8.98   49.62
BANKS                5.98          0.70   45.22
INSURANCE            5.38         -0.75   34.73
PAINTS               5.37        -20.12   40.61
PHARMA               5.23          7.37   21.30
ELECTRICAL           4.08        -13.49   53.54
CHEMICALS            2.18        -21.44   93.49
HEALTHCARE           2.08        -12.37   41.69
APPARELS             1.85          4.89   27.06
AC                   1.84        -13.63   44.44
FOOTWEAR             1.68        -71.60  140.40
REALTY               1.67         13.02    1.27
DURABLES             1.64        -54.05   91.52
BREWERIES            1.56          1.60   18.84
TRAVEL               1.50        -94.52  191.93
CERAMICS             1.39        -43.74   87.41
ENGINEERING          1.32        -20.16   75.12
CABLES               1.27         23.87   58.28
REFINERIES           1.10        -19.79   50.10
JEWELLERY            1.08        -92.42  159.27
CEMENT               1.08        -61.95  183.11
ENTERTAINMENT        0.74        -69.97  171.34
TEXTILES             0.41        -47.16   89.13
HOTELS               0.40        -84.81  150.00

In [29]:
# money to be made criteria-wise
df_portfolio_features.groupby('Criteria')['FTT Amt'].agg(['sum', 'count']).sort_values(by='sum', ascending=False)

                sum  count
Criteria
XY24      3332650.0     21
X40       1907906.0     19
XR        1323076.0     13
AR        1118200.0      9
X40N      1078245.0     13
OX40N      704171.0     10
XY25       457090.0      5
SR         278049.0      2

In [30]:
# money to be made conviction-wise
df_portfolio_features.groupby('Conviction')['FTT Amt'].agg(['sum', 'count']).sort_values(by='sum', ascending=False)

                  sum  count
Conviction
H-SC        3211557.0     24
X-LC        2009252.0     21
X-MC        1509615.0     15
M-SC        1377333.0     14
X-SC        1264435.0      9
H-MC         276995.0      2
L-SC         205990.0      2
M-LC         169836.0      1
M-MC          74651.0      2
H-LC          54988.0      1
L-MC          44735.0      1

In [31]:
# money to be made criteria and conviction-wise
df_portfolio_features.groupby(['Conviction', 'Criteria'])['FTT Amt'].agg(['sum', 'count']).sort_values(by='sum', ascending=False)

                           sum  count
Conviction Criteria
X-LC       X40       1044204.0     10
H-SC       AR         939225.0      5
           XY24       921612.0      6
M-SC       XY24       810639.0      6
H-SC       XR         782526.0      7
X-SC       XY24       748997.0      4
X-MC       X40        654289.0      7
X-LC       X40N       392997.0      6
X-MC       X40N       379223.0      4
X-LC       XY24       364778.0      2
X-SC       X40N       306025.0      3
M-SC       OX40N      300196.0      5
H-SC       OX40N      290145.0      4
           SR         278049.0      2
H-MC       XY24       250195.0      1
X-MC       XY25       239674.0      2
           XY24       236429.0      2
X-SC       X40        209413.0      2
M-SC       XR         192898.0      2
M-LC       XR         169836.0      1
X-LC       XY25       166352.0      2
L-SC       OX40N      113830.0      1
           XR          92160.0      1
M-SC       AR          73600.0      1
H-LC       AR          54988.0      1
M-MC       XY25        51064.0      1
L-MC       XR          44735.0      1
X-LC       XR          40921.0      1
H-MC       AR          26800.0      1
M-MC       AR          23587.0      1

In [32]:
# notebook execution time

end_time = time.time()
execution_time = round(end_time - start_time, 0)
print(f"Notebook execution time: {execution_time} seconds")

Notebook execution time: 28.0 seconds