<a href="https://colab.research.google.com/github/ankit-rathi/Quantvesting_v2/blob/main/myStocks_Portfolio_Analysis.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
'''
!pip install pandas==2.2.2 -qq
!pip install pyxirr -qq
!pip install ta -qq
!pip install yfinance==0.2.59 -qq
'''

'\n!pip install pandas==2.2.2 -qq\n!pip install pyxirr -qq\n!pip install ta -qq\n!pip install yfinance==0.2.59 -qq\n'

In [2]:
# import libraries

import numpy as np
import pandas as pd
import datetime
import warnings
warnings.filterwarnings('ignore')
import yfinance as yfin
import ta
import matplotlib.pyplot as plt
import requests

In [3]:
# notebook start time
import time
import datetime
import pytz

start_time = time.time()

# function to print date timestamp
def print_date_time():
  tz_NY = pytz.timezone('Asia/Kolkata')
  datetime_NY = datetime.datetime.now(tz_NY)
  print("Run date time (IST):", datetime_NY.strftime("%Y-%m-%d %H:%M:%S"))

In [4]:
# function to get booked and reserved amount
def get_amt():
  # fetch the JSON data from the URL
  url = "https://raw.githubusercontent.com/ankit-rathi/Tradevesting_v1/main/data/myPortfolioAmts.json"
  response = requests.get(url)
  pf_amts = response.json()  # parse the JSON data

  # extract values from the JSON
  py_booked_amt_dm = pf_amts["py_booked_amt_dm"]
  py_booked_amt_sv = pf_amts["py_booked_amt_sv"]
  cy_booked_amt_dm = pf_amts["cy_booked_amt_dm"]
  cy_booked_amt_sv = pf_amts["cy_booked_amt_sv"]
  reserve_amt_dm = pf_amts["reserve_amt_dm"]
  reserve_amt_sv = pf_amts["reserve_amt_sv"]

  # perform calculations
  py_booked_amt = py_booked_amt_dm + py_booked_amt_sv
  cy_booked_amt = cy_booked_amt_dm + cy_booked_amt_sv
  reserve_amt = reserve_amt_dm + reserve_amt_sv
  total_booked_amt = py_booked_amt + cy_booked_amt

  return total_booked_amt, reserve_amt, cy_booked_amt, py_booked_amt

gen_output = 0

In [5]:
# function to format the amount
def format_amt(number):
    abs_number = abs(number)

    if abs_number >= 1_00_00_000:  # Crores
        formatted_amt = f"{number / 1_00_00_000:.2f} C"
    elif abs_number >= 1_00_000:  # Lakhs
        formatted_amt = f"{number / 1_00_000:.2f} L"
    elif abs_number >= 1_000:  # Thousands
        formatted_amt = f"{number / 1_000:.2f} K"
    else:
        formatted_amt = f"{number:.2f}"

    return formatted_amt

# function to set start and end date
def get_start_end_date():
  start_date = (datetime.date.today() + datetime.timedelta(days=-365)).strftime('%Y-%m-%d')
  end_date = (datetime.date.today() + datetime.timedelta(days=1)).strftime('%Y-%m-%d')
  return start_date, end_date

# function to fetch my portfolio csv
def get_mypfs_df():
  mypfs_df = pd.read_csv('https://raw.githubusercontent.com/ankit-rathi/Tradevesting_v1/main/data/myPortfolioStocks.csv')
  return mypfs_df

# function to fetch my prospects csv
def get_mypps_df():
  mypps_df = pd.read_csv('https://raw.githubusercontent.com/ankit-rathi/Tradevesting_v1/main/data/myProspectsScrips.csv')
  return mypps_df

# function to fetch screener data
def get_myscreen_df():
  myscreen_df = pd.read_csv('https://raw.githubusercontent.com/ankit-rathi/Tradevesting_v1/main/data/myScreenerDB.csv')
  return myscreen_df

# function to fetch momentum data
def get_myinvmt_df():
  myinvmt_df = pd.read_csv('https://raw.githubusercontent.com/ankit-rathi/Tradevesting_v1/main/data/myInvestments.csv')
  return myinvmt_df

# function to get the stock ids
def get_stock_ids(df_pf):
  stock_n100 = df_pf['Symbol'].unique()

  exclude = ['CADILAHC','MMTC', 'MASFIN']

  stock_ids = df_pf[~df_pf['Symbol'].isin(exclude) ]['Symbol'].unique()

  #mypf = mypf[mypf.Forecast.notnull()]
  #stock_ids = mypf['Symbol'].unique()

  #stock_ids.sort()
  return stock_ids

# get features from screener data
def get_screener_features():
  myscreen_df = get_myscreen_df()
  cols = ['Symbol', 'EPS', 'MedPE', 'ROCE%', 'ROE%', 'CapType']
  return myscreen_df[cols]

# get relative strength
def get_relative_strength(stock_list):

    # Dictionary to store stock tickers and their corresponding percentage price change
    stock_changes = {}

    # Loop through each stock and fetch its price data
    for stock in stock_list:
        try:
            # Download the stock data for the given date range
            stock_data = yfin.Ticker(stock + '.NS').history(period='1mo', interval='1d')[map(str.title, ['open', 'close', 'low', 'high', 'volume'])]

            # Calculate the percentage change for the stock
            if len(stock_data) > 0:
                start_price = stock_data['Close'].iloc[0]
                end_price = stock_data['Close'].iloc[-1]
                percent_change = round(((end_price - start_price) / start_price) * 100, 2)
                stock_changes[stock] = percent_change
            else:
                stock_changes[stock] = np.nan  # If no data is available, set to NaN

        except Exception as e:
            print(f"Error fetching data for {stock}: {e}")
            stock_changes[stock] = np.nan

    # Create a DataFrame with stock tickers and their percentage changes
    df = pd.DataFrame(list(stock_changes.items()), columns=['Symbol', 'Percent_Change'])

    # Drop any stocks with missing data (NaN values)
    df = df.dropna()

    # Calculate the percentile rank based on percentage change
    df['RSP'] = round(df['Percent_Change'].rank(pct=True) * 100, 2)
    cols = ['Symbol', 'RSP']
    df = df[cols]
    # Sort by percentile rank (optional)
    df = df.sort_values(by='RSP', ascending=False).reset_index(drop=True)

    return df

In [6]:
# function to get stock technicals
def stock_prec_dev(stock_symbol):
    #stock_symbol = 'ULTRACEMCO.NS'
    short_window = 20
    mid_window = 50
    long_window = 200
    moving_avg = 'SMA'

    start = datetime.datetime(*map(int, start_date.split('-')))
    end = datetime.datetime(*map(int, end_date.split('-')))

    stock_df = yfin.Ticker(stock_symbol + '.NS').history(period='max', interval='1d')[map(str.title, ['open', 'close', 'low', 'high', 'volume'])]

    stock_df['Max'] = round(max(stock_df['Close']),2)
    stock_df = stock_df[(stock_df.index <= end_date) & (stock_df.index >= start_date)]
    stock_df['200_SMA'] = round(stock_df['Close'].rolling(window = 200, min_periods = 1).mean(),0)
    stock_df['Dev%_200'] = round((stock_df['Close'] - stock_df['200_SMA'])*100/stock_df['200_SMA'],2)
    stock_df.dropna(axis = 0, inplace = True) # remove any null rows

    stock_df['20_SMA'] = stock_df['Close'].rolling(window=20).mean()
    stock_df['50_SMA'] = stock_df['Close'].rolling(window=50).mean()
    stock_df['Symbol'] = stock_symbol

    stock_df['Close'] = round(stock_df['Close'],2)
    stock_df['Min'] = round(min(stock_df['Close']),2)
    stock_df['RSI_14'] = ta.momentum.RSIIndicator(close=stock_df['Close'], window=14).rsi()
    stock_df['RSI_14'] = round(stock_df['RSI_14'],0)
    stock_df['Prev_Close'] = stock_df['Close'].shift(1)
    stock_df.drop(['Open', 'Low', 'High', 'Volume'], axis=1, inplace=True)
    stock_df = stock_df.tail(1)

    max_SMA = max(stock_df['20_SMA'].item(), stock_df['50_SMA'].item(), stock_df['200_SMA'].item())
    min_SMA = min(stock_df['20_SMA'].item(), stock_df['50_SMA'].item(), stock_df['200_SMA'].item())
    ABS_Spread = max_SMA - min_SMA
    stock_df['Spread%'] = round((ABS_Spread / stock_df['200_SMA'].item()) * 100,2)

    return stock_df

# function to compute stock attributes
def get_common_features(stock_ids, df_mypf):

  df_prec_dev = pd.DataFrame()
  df_tmp = get_screener_features()
  df_rs = get_relative_strength(stock_ids)

  for stock_id in stock_ids:
      tmp = stock_prec_dev(stock_id)
      tmp = tmp.reset_index()
      df_prec_dev = pd.concat([df_prec_dev, tmp], ignore_index = True)
  df_prec_dev = pd.merge(df_prec_dev, df_mypf, on= 'Symbol')
  df_prec_dev = pd.merge(df_prec_dev, df_tmp, on= 'Symbol', how='left')
  df_prec_dev = pd.merge(df_prec_dev, df_rs, on= 'Symbol', how='left')
  #print(df_prec_dev.columns)
  df_prec_dev['Curr_PE'] = round(df_prec_dev['Close']/df_prec_dev['EPS'],1)
  df_prec_dev['Dev%_PE'] = round((df_prec_dev['Curr_PE'] - df_prec_dev['MedPE'])*100/df_prec_dev['MedPE'],2)
  df_prec_dev['Conviction'] = df_prec_dev['Conviction'] + '-' + df_prec_dev['CapType']
  return df_prec_dev

# function to arrange stock features
def arrange_features(df_stocks, common_cols, diff_cols):
  df_stocks_common = df_stocks[common_cols].drop_duplicates()
  df_stocks_diff = df_stocks[diff_cols]
  df_stocks_diff['Investment'] = df_stocks_diff['AvgCost'] * df_stocks_diff['Shares']
  df_stocks_diff = df_stocks_diff.groupby(['Symbol'])[['Shares', 'Investment']].aggregate(['sum']).reset_index()
  df_stocks_diff.columns = ['Symbol', 'Shares', 'Investment']
  df_stocks_diff['AvgCost'] = round(df_stocks_diff['Investment']/df_stocks_diff['Shares'],2)
  df_stocks = pd.merge(df_stocks_diff, df_stocks_common, on='Symbol')
  return df_stocks

# plot fact distribution across dimension
def plot_pie_chart(df, dimension, fact):
  # grouping the data by category and calculating the sum of fact for each type
  grouped_data = df.groupby(dimension)[fact].sum()

  # sorting the grouped data in descending order
  grouped_data = grouped_data.sort_values(ascending=False)

  # creating a pie chart
  grouped_data.plot.pie(autopct='%1.1f%%', startangle=90, figsize=(6, 6))

  # adding a title and displaying the plot
  plt.title(f'{dimension} {fact} Distribution')
  plt.ylabel('')  # To hide the y-label
  plt.show()

In [7]:
# function to get portfolio features

def get_portfolio_features(df_common_features):

  print_date_time()
  print('-------------------')

  #df_common_features["Target"] = df_common_features["Target"].fillna(df_common_features["Max"])
  df_common_features['NTT'] = np.where(df_common_features['Strategy']== 'NTT', df_common_features["Target"], df_common_features['Max'])
  df_common_features['LTT'] = np.where(df_common_features['Strategy']== 'BTT', df_common_features["Target"], df_common_features['Max'])
  df_common_features['BOL'] = df_common_features['Min']

  tmp_df = df_common_features[df_common_features['Symbol'].isin(mypf_df[mypf_df['InPortfolio'] != 'NA'].Symbol.values)]
  print('qualified stocks: '+str(len(tmp_df['Symbol'].unique())))
  tmp_df1 = tmp_df[tmp_df['LatestQtr'] == 1]
  print('with latest results: '+str(len(tmp_df1['Symbol'].unique())))
  tmp_df1 = tmp_df1[tmp_df1['StarStock'] == 1]
  print('still star stocks: '+str(len(tmp_df1['Symbol'].unique())))
  tmp_df['Investment'] = tmp_df['AvgCost'] * tmp_df['Shares']
  tmp_df['Current'] = round(tmp_df['Close'] * tmp_df['Shares'],0)
  tmp_df['Previous'] = tmp_df['Prev_Close'] * tmp_df['Shares']
  tmp_df['EstimatedST'] = tmp_df['NTT'] * tmp_df['Shares']
  tmp_df['EstimatedLT'] = tmp_df['LTT'] * tmp_df['Shares']
  tmp_df['Current P/L'] = round((tmp_df['Current'] - tmp_df['Investment']),0)
  tmp_df['Today P/L%'] = round((tmp_df['Current'] - tmp_df['Previous'])*100/tmp_df['Previous'],2)
  tmp_df['Current P/L%'] = round((tmp_df['Current'] - tmp_df['Investment'])*100/tmp_df['Investment'],2)
  tmp_df['EstimatedST P/L%'] = round((tmp_df['EstimatedST'] - tmp_df['Investment'])*100/tmp_df['Investment'],2)
  tmp_df['EstimatedLT P/L%'] = round((tmp_df['EstimatedLT'] - tmp_df['Investment'])*100/tmp_df['Investment'],2)
  tmp_df['NTT%'] = round((tmp_df['NTT'] - tmp_df['Close'])*100/tmp_df['Close'],2)
  tmp_df['LTT%'] = round((tmp_df['LTT'] - tmp_df['Close'])*100/tmp_df['Close'],2)
  tmp_df['Gained%'] = round((tmp_df['Close'] - tmp_df['BOL'])*100/tmp_df['BOL'],2)
  investment = round(sum(tmp_df['AvgCost']*tmp_df['Shares']),0)
  current = round(sum(tmp_df['Close']*tmp_df['Shares']),0)
  tmp_df['InitAlloc%'] = round(tmp_df['Investment']*100/investment,2)
  tmp_df['CurrAlloc%'] = round(tmp_df['Current']*100/current,2)
  tmp_df['FTT'] = tmp_df['LTT']
  tmp_df.loc[tmp_df['Strategy'] == 'NTT', 'FTT'] = tmp_df['NTT']
  tmp_df['FTT%'] = tmp_df['LTT%']
  tmp_df.loc[tmp_df['Strategy'] == 'NTT', 'FTT%'] = tmp_df['NTT%']
  tmp_df['FTT Amt'] = round(tmp_df['FTT%'] * tmp_df['Current']/100,0)
  tmp_df['OTT%'] = round((tmp_df['FTT'] - tmp_df['AvgCost'])*100/tmp_df['AvgCost'],2)
  tmp_df['RRR Ind'] = round(tmp_df['Current P/L']/tmp_df['FTT Amt'],2)
  tmp_df['Risk Ind'] = round(tmp_df['Current P/L%']*tmp_df['CurrAlloc%'],0)

  return tmp_df

# function to print portfolio features
def print_portfolio_stats(df_portfolio_features, myinvmt_df):
  from pyxirr import xirr

  total_booked_amt, reserve_amt, cy_booked_amt, py_booked_amt = get_amt()

  dates = myinvmt_df['Date'].values
  dates = np.append(dates, datetime.date.today().strftime('%d-%b-%y'))
  investment = myinvmt_df['Investment'].values
  dates= pd.to_datetime(dates)

  current = round(sum(df_portfolio_features['Close']*df_portfolio_features['Shares']),0) + reserve_amt
  investment_xirr = np.append(investment, current)
  cagr = round(xirr(pd.DataFrame({"dates": dates, "amounts": investment_xirr}))*100,2)

  investment = -sum(investment)
  invested = round(sum(df_portfolio_features['AvgCost']*df_portfolio_features['Shares']),0) + reserve_amt
  previous = round(sum(df_portfolio_features['Prev_Close']*df_portfolio_features['Shares']),0) + reserve_amt
  cy_invested = investment + py_booked_amt

  today_pnl_amount = current-previous
  today_pnl_percentage = round((current-previous)*100/previous,2)

  curr_pnl_amount = current-invested
  curr_pnl_percentage = round((curr_pnl_amount)*100/(cy_invested),2)

  cy_pnl_amount = cy_booked_amt + curr_pnl_amount
  cy_pnl_percentage = round((cy_pnl_amount)*100/cy_invested,2)

  overall_pnl_amount = total_booked_amt + curr_pnl_amount
  overall_pnl_percentage = round((overall_pnl_amount)*100/investment,2)

  estimate_st = round(sum(df_portfolio_features['FTT']*df_portfolio_features['Shares']),0)  + reserve_amt
  est_st_pnl_amount = estimate_st-current
  est_st_pnl_percentage = round((est_st_pnl_amount)*100/current,2)

  estimate_lt = round(sum(df_portfolio_features['LTT']*df_portfolio_features['Shares']),0)  + reserve_amt
  est_lt_pnl_amount = estimate_lt-current
  est_lt_pnl_percentage = round((est_lt_pnl_amount)*100/current,2)

  total_profit = round(sum(df_portfolio_features[df_portfolio_features['Current P/L%'] > 0]['Current']) - sum(df_portfolio_features[df_portfolio_features['Current P/L%'] > 0]['Investment']),0)
  total_loss = round(sum(df_portfolio_features[df_portfolio_features['Current P/L%'] < 0]['Current']) - sum(df_portfolio_features[df_portfolio_features['Current P/L%'] < 0]['Investment']),0)

  cy_booked_percentage = round((cy_booked_amt)*100/current,2)
  py_booked_percentage = round((py_booked_amt)*100/investment,2)
  total_booked_percentage = round((total_booked_amt)*100/investment,2)

  print('-------------------')
  print('Initial Investment: ', format_amt(investment))
  print('CY Investment: ', format_amt(cy_invested))
  print('Reserve: ', format_amt(reserve_amt))
  print('Current: ',  format_amt(current))
  print('-------------------')
  print('Today PnL: '+ '{} ({}%)'.format(format_amt(today_pnl_amount), today_pnl_percentage))
  print('Current PnL: '+ '{} ({}%)'.format(format_amt(curr_pnl_amount), curr_pnl_percentage))
  print('CY Booked + Current PnL: '+ '{} ({}%)'.format(format_amt(cy_pnl_amount), cy_pnl_percentage))
  print('-------------------')
  print('Total profit: ', format_amt(total_profit))
  print('Total loss: ', format_amt(total_loss))
  print('-------------------')
  print('Total Booked + Current PnL: '+ '{} ({}%)'.format(format_amt(overall_pnl_amount), overall_pnl_percentage))
  print('Total Booked PnL: '+ '{} ({}%)'.format(format_amt(total_booked_amt), total_booked_percentage))
  print('Curr Year Booked PnL: '+ '{} ({}%)'.format(format_amt(cy_booked_amt), cy_booked_percentage))
  print('Prev Year Booked PnL: '+ '{} ({}%)'.format(format_amt(py_booked_amt), py_booked_percentage))
  print('===================')
  print('Est FTT: ',  format_amt(estimate_st))
  print('Est FTT PnL: '+ '{} ({}%)'.format(format_amt(est_st_pnl_amount), est_st_pnl_percentage))

  print('===================')
  print('Deployed: ', format_amt(investment))

  print('Current: ', format_amt(current))

  print('CAGR/XIRR %: '+'{}%'.format(cagr))

In [8]:
# get start and end date
start_date, end_date = get_start_end_date()

# get portfolio and prospects data
mypfs_df = get_mypfs_df()
mypps_df = get_mypps_df()
myinvmt_df = get_myinvmt_df()

# merge above datasets
mypf_df = pd.merge(mypfs_df, mypps_df, on="Symbol")

# seggregate dm and sv portfolio
dm_pf = mypf_df[mypf_df['InPortfolio'] == 'DM']
sv_pf = mypf_df[mypf_df['InPortfolio'] == 'SV']

# build portfolio stock dataframe
dm_stocks = get_stock_ids(dm_pf)
sv_stocks = get_stock_ids(sv_pf)
df_stocks = pd.concat([dm_pf,sv_pf], ignore_index = True)

# arrange common and diff stock features
common_cols = ['Symbol', 'Target', 'Criteria', 'Strategy', 'CumlRnk', 'LatestQtr', 'StarStock', 'Conviction', 'Category', 'InFolio', 'XIRR', 'MBQ']
diff_cols = ['Symbol', 'AvgCost', 'Shares']
df_stocks = arrange_features(df_stocks, common_cols, diff_cols)

# get common features
stock_ids = df_stocks['Symbol'].values
df_common_features = get_common_features(stock_ids, df_stocks)

df_common_features.reset_index(drop=True, inplace=True)
df_common_features.drop(['Date'], axis=1, inplace=True)
# get and print portfolio features
df_portfolio_features = get_portfolio_features(df_common_features)

print_portfolio_stats(df_portfolio_features, myinvmt_df)

df = df_portfolio_features
#plot_pie_chart(df, 'CapType', 'Current')
list_ox40n = list(df[df['MBQ'].str.contains('OX40N', na=False)]['Symbol'].values)

Run date time (IST): 2026-04-07 13:20:35
-------------------
qualified stocks: 86
with latest results: 26
still star stocks: 16
-------------------
Initial Investment:  1.36 C
CY Investment:  1.62 C
Reserve:  1.61 K
Current:  1.31 C
-------------------
Today PnL: 31.49 K (0.24%)
Current PnL: -45.89 L (-28.24%)
CY Booked + Current PnL: -30.00 L (-18.46%)
-------------------
Total profit:  64.54 K
Total loss:  -46.53 L
-------------------
Total Booked + Current PnL: -3.02 L (-2.23%)
Total Booked PnL: 42.87 L (31.64%)
Curr Year Booked PnL: 15.89 L (12.11%)
Prev Year Booked PnL: 26.98 L (19.91%)
===================
Est FTT:  2.48 C
Est FTT PnL: 1.17 C (88.88%)
===================
Deployed:  1.36 C
Current:  1.31 C
CAGR/XIRR %: -1.54%

In [9]:
# top 5 near their targets
cols = ['Symbol', 'Today P/L%', 'Current P/L%', 'FTT%', 'OTT%', 'FTT Amt', 'Current P/L', 'Current', 'FTT', 'Dev%_PE', 'RSI_14','Conviction', 'Spread%',  'CumlRnk', 'RRR Ind', 'CurrAlloc%', 'Gained%', 'Criteria', 'Strategy', 'Category']
df_tmp = df_portfolio_features[~df_portfolio_features['Symbol'].isin(['ENRIN','BLUSPRING','DIGITIDE'])]
df_tmp = df_tmp.sort_values(by = 'FTT Amt', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
50,MASFIN,-0.46,-7.61,31.58,21.57,28588.0,-7455.0,90525.0,397.04,-20.51,49.0,H-SC,4.91,167.0,-0.26,0.69,23.47,XR,ATH,FINANCE
77,TTKPRESTIG,3.19,-38.83,63.62,0.09,39221.0,-39128.0,61649.0,770.00,43.01,46.0,M-SC,22.37,250.0,-1.00,0.47,9.77,OX40N,NTT,DURABLES
67,SONACOMS,0.74,-11.23,56.68,39.09,50899.0,-11358.0,89801.0,804.02,-29.65,53.0,M-MC,7.29,193.0,-0.22,0.68,27.04,AR,ATH,AUTO
24,DMART,-1.22,8.07,19.92,29.60,53733.0,20142.0,269742.0,5391.45,-8.90,74.0,X-LC,5.65,14.0,0.37,2.06,23.29,X40N,ATH,FMCG
37,ICICIGI,0.19,-9.09,31.27,19.34,56889.0,-18181.0,181928.0,2252.93,-23.51,34.0,X-MC,6.65,66.0,-0.32,1.39,1.61,X40,ATH,INSURANCE

In [10]:
# top 5 today
df_tmp = df_portfolio_features.sort_values(by = 'Today P/L%', ascending=False)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
74,TITAGARH,11.23,-33.05,117.68,45.74,190809.0,-80035.0,162142.0,1548.0,-10.72,60.0,H-SC,23.38,175.0,-0.42,1.24,23.71,XY24,NTT,ENGINEERING
55,RAJESHEXPO,5.00,-81.42,438.46,0.07,111777.0,-111684.0,25493.0,518.0,834.34,38.0,L-SC,44.02,268.0,-1.00,0.19,19.68,OX40N,NTT,JEWELLERY
0,5PAISA,4.26,-44.34,102.84,12.90,125072.0,-96878.0,121618.0,593.0,79.09,50.0,H-SC,16.78,170.0,-0.77,0.93,17.36,OX40N,NTT,FINANCE
54,QUESS,3.43,-24.39,130.00,73.90,104968.0,-26048.0,80745.0,424.0,-59.23,51.0,X-SC,22.36,80.0,-0.25,0.62,8.62,XY24,NTT,MISC
84,WIPRO,3.33,-16.39,106.03,72.27,150219.0,-27772.0,141676.0,420.0,-24.55,56.0,M-LC,17.95,98.0,-0.18,1.08,8.70,XR,NTT,IT

In [11]:
# bottom 5 today
df_tmp = df_portfolio_features.sort_values(by = 'Today P/L%', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
19,COFFEEDAY,-2.75,-61.16,248.28,35.27,109496.0,-69447.0,44102.0,80.0,-69.82,41.0,L-SC,32.82,266.0,-0.63,0.34,8.76,XR,NTT,HOTELS
82,VOLTAS,-2.72,-4.72,52.38,45.20,95698.0,-9042.0,182700.0,1856.0,9.08,33.0,X-MC,4.27,79.0,-0.09,1.39,1.76,XY25,NTT,AC
11,BANDHANBNK,-2.70,-28.58,169.43,92.42,337057.0,-79623.0,198936.0,400.0,70.98,41.0,H-SC,1.49,174.0,-0.24,1.52,9.59,XY24,NTT,BANKS
49,LAOPALA,-2.51,-47.59,165.39,39.09,113643.0,-62393.0,68712.0,464.0,50.07,40.0,H-SC,18.06,154.0,-0.55,0.52,6.61,AR,NTT,CERAMICS
47,JSWINFRA,-1.85,-20.27,46.03,16.43,81391.0,-44953.0,176821.0,342.0,-31.54,38.0,X-MC,12.21,61.0,-0.55,1.35,0.00,X40N,NTT,REALTY

In [12]:
# top 5 to exit based on CumlRnk
df_tmp = df_portfolio_features[~df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])]
df_tmp = df_tmp[(df_tmp['Current P/L%'] > -1) & (df_tmp['Current P/L%'] < 1)].sort_values(by = 'CumlRnk', ascending=False)
df_tmp[cols].head()

Empty DataFrame
Columns: [Symbol, Today P/L%, Current P/L%, FTT%, OTT%, FTT Amt, Current P/L, Current, FTT, Dev%_PE, RSI_14, Conviction, Spread%, CumlRnk, RRR Ind, CurrAlloc%, Gained%, Criteria, Strategy, Category]
Index: []

In [13]:
# OX40N stocks to exit
df_tmp = df_portfolio_features[(df_portfolio_features['Symbol'].isin(list_ox40n))].sort_values(by = 'Current P/L%', ascending=False)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
26,FINCABLES,-0.43,2.05,103.74,107.91,156301.0,3022.0,150666.0,1641.55,-8.17,45.0,M-SC,4.17,220.0,0.02,1.15,13.35,OX40N,ATH,CABLES
66,SIS,-0.02,-33.63,82.70,21.26,60946.0,-37337.0,73695.0,528.00,1725.91,49.0,H-SC,14.91,168.0,-0.61,0.56,9.57,OX40N,NTT,MISC
72,TATAELXSI,1.94,-37.23,110.35,32.03,91311.0,-49088.0,82747.0,9161.00,-21.54,50.0,H-SC,21.58,158.0,-0.54,0.63,9.52,OX40N,NTT,IT
18,CERA,-0.13,-37.47,98.11,23.89,107921.0,-65903.0,110000.0,9475.00,-39.62,51.0,H-SC,18.98,153.0,-0.61,0.84,5.71,OX40N,NTT,CERAMICS
77,TTKPRESTIG,3.19,-38.83,63.62,0.09,39221.0,-39128.0,61649.0,770.00,43.01,46.0,M-SC,22.37,250.0,-1.00,0.47,9.77,OX40N,NTT,DURABLES

In [14]:
# top 5 to book for rotation
df_tmp = df_portfolio_features[(df_portfolio_features['Current P/L%'] > 20) ].sort_values(by = 'CumlRnk', ascending=False)
df_tmp[cols].head()

Empty DataFrame
Columns: [Symbol, Today P/L%, Current P/L%, FTT%, OTT%, FTT Amt, Current P/L, Current, FTT, Dev%_PE, RSI_14, Conviction, Spread%, CumlRnk, RRR Ind, CurrAlloc%, Gained%, Criteria, Strategy, Category]
Index: []

In [15]:
# top 5 to monitor for exit
df_tmp = df_portfolio_features[~df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])]
df_tmp = df_tmp[(df_tmp['Current P/L%'] > 0) ].sort_values(by = 'Dev%_PE', ascending=False)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
26,FINCABLES,-0.43,2.05,103.74,107.91,156301.0,3022.0,150666.0,1641.55,-8.17,45.0,M-SC,4.17,220.0,0.02,1.15,13.35,OX40N,ATH,CABLES
1,ABB,1.07,14.85,26.74,45.57,80348.0,38861.0,300480.0,7934.00,-26.19,57.0,H-MC,13.92,125.0,0.48,2.29,33.43,AR,NTT,ELECTRICAL

In [16]:
# top 5 to book for rotation from weak conviction
df_tmp = df_portfolio_features[~df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])]
df_tmp = df_tmp[~df_tmp['Criteria'].isin(['XY25','XY24','X40', 'X40N'])].sort_values(by = 'RRR Ind', ascending=False)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
1,ABB,1.07,14.85,26.74,45.57,80348.0,38861.0,300480.0,7934.00,-26.19,57.0,H-MC,13.92,125.0,0.48,2.29,33.43,AR,NTT,ELECTRICAL
26,FINCABLES,-0.43,2.05,103.74,107.91,156301.0,3022.0,150666.0,1641.55,-8.17,45.0,M-SC,4.17,220.0,0.02,1.15,13.35,OX40N,ATH,CABLES
40,INDIAMART,-0.82,-11.87,134.57,106.72,146267.0,-14644.0,108692.0,4810.62,-60.16,47.0,H-SC,12.83,140.0,-0.10,0.83,8.73,AR,ATH,MISC
84,WIPRO,3.33,-16.39,106.03,72.27,150219.0,-27772.0,141676.0,420.00,-24.55,56.0,M-LC,17.95,98.0,-0.18,1.08,8.70,XR,NTT,IT
85,ZYDUSLIFE,0.59,-8.10,47.59,35.63,91654.0,-16984.0,192590.0,1286.17,-19.82,44.0,H-MC,5.93,120.0,-0.19,1.47,7.22,AR,ATH,PHARMA

In [17]:
# top 5 to accumulate based on lowest RSI_14
df_tmp = df_portfolio_features[df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])].sort_values(by = 'RSI_14', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
38,ICICIPRULI,-0.04,-15.13,54.03,30.73,90341.0,-29800.0,167205.0,790.00,-37.88,25.0,X-MC,10.40,78.0,-0.33,1.27,1.89,X40,ATH,INSURANCE
21,DABUR,0.16,-18.99,77.39,43.70,155523.0,-47108.0,200960.0,735.00,-26.49,30.0,X-MC,12.40,70.0,-0.30,1.53,0.95,XY24,BTT,FMCG
59,RELIANCE,-0.63,-16.78,50.56,25.30,84561.0,-33715.0,167248.0,1952.00,-18.88,32.0,X-LC,4.27,21.0,-0.40,1.27,11.67,XY25,BTT,REFINERIES
82,VOLTAS,-2.72,-4.72,52.38,45.20,95698.0,-9042.0,182700.0,1856.00,9.08,33.0,X-MC,4.27,79.0,-0.09,1.39,1.76,XY25,NTT,AC
37,ICICIGI,0.19,-9.09,31.27,19.34,56889.0,-18181.0,181928.0,2252.93,-23.51,34.0,X-MC,6.65,66.0,-0.32,1.39,1.61,X40,ATH,INSURANCE

In [18]:
# top 5 to accumulate based on Spread and CumlRnk
df_tmp = df_portfolio_features[df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])]
df_tmp = df_tmp[(df_tmp['CumlRnk'] < 100)].sort_values(by = 'Spread%', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
65,SIEMENS,0.35,-17.82,52.72,25.51,80630.0,-33155.0,152940.0,4671.50,28.36,46.0,H-LC,0.71,51.0,-0.41,1.17,12.63,AR,ATH,ELECTRICAL
78,UNITDSPR,-0.70,-9.82,33.92,20.77,71621.0,-22997.0,211147.0,1644.00,-20.03,38.0,X-MC,4.18,64.0,-0.32,1.61,0.72,X40N,NTT,BREWERIES
59,RELIANCE,-0.63,-16.78,50.56,25.30,84561.0,-33715.0,167248.0,1952.00,-18.88,32.0,X-LC,4.27,21.0,-0.40,1.27,11.67,XY25,BTT,REFINERIES
82,VOLTAS,-2.72,-4.72,52.38,45.20,95698.0,-9042.0,182700.0,1856.00,9.08,33.0,X-MC,4.27,79.0,-0.09,1.39,1.76,XY25,NTT,AC
24,DMART,-1.22,8.07,19.92,29.60,53733.0,20142.0,269742.0,5391.45,-8.90,74.0,X-LC,5.65,14.0,0.37,2.06,23.29,X40N,ATH,FMCG

In [19]:
# top 5 to accumulate based on lowest Gained%
df_tmp = df_portfolio_features[df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])].sort_values(by = 'Gained%', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
47,JSWINFRA,-1.85,-20.27,46.03,16.43,81391.0,-44953.0,176821.0,342.0,-31.54,38.0,X-MC,12.21,61.0,-0.55,1.35,0.00,X40N,NTT,REALTY
35,HINDUNILVR,-1.01,-19.72,41.58,13.67,85813.0,-50683.0,206380.0,2922.0,-40.44,36.0,X-LC,11.68,9.0,-0.59,1.57,0.57,XY25,NTT,FMCG
78,UNITDSPR,-0.70,-9.82,33.92,20.77,71621.0,-22997.0,211147.0,1644.0,-20.03,38.0,X-MC,4.18,64.0,-0.32,1.61,0.72,X40N,NTT,BREWERIES
2,ABBOTINDIA,-0.75,-13.78,36.95,18.07,56977.0,-24655.0,154200.0,35195.0,-26.70,42.0,X-MC,10.92,58.0,-0.43,1.18,0.84,X40,ATH,PHARMA
21,DABUR,0.16,-18.99,77.39,43.70,155523.0,-47108.0,200960.0,735.0,-26.49,30.0,X-MC,12.40,70.0,-0.30,1.53,0.95,XY24,BTT,FMCG

In [20]:
# top 5 to accumulate based on lowest CurrAlloc%
df_tmp = df_portfolio_features[df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])].sort_values(by = 'CurrAlloc%', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
58,RELAXO,0.54,-64.43,328.24,52.31,169460.0,-93533.0,51627.0,1176.00,-62.15,42.0,X-SC,32.29,92.0,-0.55,0.39,15.43,X40N,NTT,FOOTWEAR
12,BATAINDIA,0.75,-56.68,212.14,35.20,118234.0,-72936.0,55734.0,2096.00,-26.93,43.0,X-SC,34.35,91.0,-0.62,0.42,10.53,X40,NTT,FOOTWEAR
54,QUESS,3.43,-24.39,130.00,73.90,104968.0,-26048.0,80745.0,424.00,-59.23,51.0,X-SC,22.36,80.0,-0.25,0.62,8.62,XY24,NTT,MISC
36,HONAUT,-1.40,-29.73,115.34,51.31,156286.0,-57338.0,135500.0,58357.33,-41.61,36.0,X-SC,18.49,90.0,-0.37,1.03,2.94,X40N,ATH,ELECTRICAL
65,SIEMENS,0.35,-17.82,52.72,25.51,80630.0,-33155.0,152940.0,4671.50,28.36,46.0,H-LC,0.71,51.0,-0.41,1.17,12.63,AR,ATH,ELECTRICAL

In [21]:
# top 5 to accumulate based on CumlRnk
df_tmp = df_portfolio_features.sort_values(by = 'CumlRnk', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
45,ITC,0.86,-21.66,51.98,19.06,138511.0,-73696.0,266470.0,452.00,-57.14,44.0,X-LC,19.91,1.0,-0.53,2.03,3.37,X40,NTT,FMCG
73,TCS,2.35,-25.67,70.28,26.57,242020.0,-118907.0,344366.0,4311.59,-37.07,52.0,X-LC,18.63,2.0,-0.49,2.62,7.47,X40,ATH,IT
43,INFY,1.95,-9.34,48.08,34.24,136380.0,-29236.0,283652.0,1972.00,-28.52,55.0,X-LC,14.77,3.0,-0.21,2.16,9.08,X40,NTT,IT
75,TMPV,-0.57,-30.43,96.30,36.58,238416.0,-108265.0,247576.0,600.00,-85.81,39.0,X-LC,12.48,4.0,-0.45,1.89,3.19,XY24,NTT,AUTO
33,HCLTECH,2.85,-6.34,32.21,23.83,72987.0,-15326.0,226598.0,1908.19,-1.57,59.0,X-LC,10.93,8.0,-0.21,1.73,10.02,X40,ATH,IT

In [22]:
# top 5 for average up
df_tmp = df_portfolio_features[(df_portfolio_features['Dev%_200'] > 5)].sort_values(by = 'CurrAlloc%', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
67,SONACOMS,0.74,-11.23,56.68,39.09,50899.0,-11358.0,89801.0,804.02,-29.65,53.0,M-MC,7.29,193.0,-0.22,0.68,27.04,AR,ATH,AUTO
24,DMART,-1.22,8.07,19.92,29.60,53733.0,20142.0,269742.0,5391.45,-8.90,74.0,X-LC,5.65,14.0,0.37,2.06,23.29,X40N,ATH,FMCG
1,ABB,1.07,14.85,26.74,45.57,80348.0,38861.0,300480.0,7934.00,-26.19,57.0,H-MC,13.92,125.0,0.48,2.29,33.43,AR,NTT,ELECTRICAL

In [23]:
# top 5 RSP
df_tmp = df_portfolio_features.sort_values(by = 'RSP', ascending=False)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
80,VALIANTORG,1.38,-49.65,245.88,74.15,202544.0,-81230.0,82375.0,838.00,-248.47,54.0,H-SC,26.42,145.0,-0.40,0.63,22.59,XR,NTT,CHEMICALS
24,DMART,-1.22,8.07,19.92,29.60,53733.0,20142.0,269742.0,5391.45,-8.90,74.0,X-LC,5.65,14.0,0.37,2.06,23.29,X40N,ATH,FMCG
5,ANGELONE,-0.02,0.82,23.17,24.18,71251.0,2512.0,307512.0,303.00,-85.37,58.0,X-SC,8.61,97.0,0.04,2.34,18.37,X40N,NTT,FINANCE
30,HAPPSTMNDS,-1.01,-52.37,288.13,84.85,175875.0,-67125.0,61040.0,1480.71,-43.46,49.0,H-SC,23.22,152.0,-0.38,0.47,13.04,AR,ATH,IT
52,PAGEIND,-0.10,-9.45,48.12,34.11,116934.0,-25374.0,243005.0,51418.64,-35.06,65.0,X-MC,19.20,55.0,-0.22,1.85,14.95,X40,ATH,APPARELS

In [24]:
# Top N allocation
df_tmp = df_portfolio_features.sort_values(by = 'CurrAlloc%', ascending=False)
top_n_values = [10, 25, 50]

sum_df = pd.DataFrame({
    'Top_N': top_n_values,
    'Sum_Alloc%': [df_tmp['CurrAlloc%'].head(n).sum() for n in top_n_values]
})

sum_df

   Top_N  Sum_Alloc%
0     10       21.21
1     25       46.23
2     50       77.99

In [25]:
# market-cap-wise allocation
df_tmp = df_portfolio_features[cols]
df_tmp.groupby(df_tmp['Conviction'].str[-2:])['CurrAlloc%'].sum().sort_values(ascending=False)

Conviction
SC    44.77
MC    29.46
LC    25.80
Name: CurrAlloc%, dtype: float64

In [26]:
# criteria-wise allocation
df_portfolio_features.groupby('Criteria')['CurrAlloc%'].sum().sort_values(ascending=False)

Criteria
XY24     27.11
X40      25.48
X40N     15.33
AR        9.17
XR        8.43
XY25      7.00
OX40N     6.71
SR        0.80
Name: CurrAlloc%, dtype: float64

In [27]:
# conviction-wise allocation
df_portfolio_features.groupby('Conviction')['CurrAlloc%'].sum().sort_values(ascending=False)

Conviction
X-LC    23.55
X-MC    22.03
H-SC    22.01
X-SC    12.30
M-SC     9.93
H-MC     5.04
M-MC     2.05
H-LC     1.17
M-LC     1.08
L-SC     0.53
L-MC     0.34
Name: CurrAlloc%, dtype: float64

In [28]:
# sector-wise stats
df_tmp = df_portfolio_features.groupby('Category')[['CurrAlloc%', 'Current', 'Current P/L', 'FTT Amt']].sum().sort_values(by=['Current', 'Current P/L'], ascending=False)
df_tmp['Current P/L%'] = round(df_tmp['Current P/L'] * 100 / df_tmp['Current'], 2)
df_tmp['FTT%'] = round(df_tmp['FTT Amt'] * 100 / df_tmp['Current'], 2)
cols = ['CurrAlloc%', 'Current P/L%', 'FTT%']
df_tmp[cols].sort_values(by=['CurrAlloc%'], ascending=False)

               CurrAlloc%  Current P/L%    FTT%
Category
FMCG                15.13        -25.84   70.52
FINANCE             13.22        -23.83   74.29
IT                  12.21        -40.61  112.17
MISC                 7.11        -43.92  106.44
ELECTRICAL           6.46        -14.36   58.15
PAINTS               5.21        -43.97   68.98
INSURANCE            4.57        -13.20   51.95
BANKS                4.51        -30.32   96.47
PHARMA               4.07        -10.25   44.95
AUTO                 3.64        -36.96   91.30
HEALTHCARE           1.95        -39.88   76.39
AC                   1.88        -29.31   64.37
APPARELS             1.85        -10.44   48.12
FOOTWEAR             1.82        -84.01  157.79
TRAVEL               1.78        -91.87  187.95
DURABLES             1.77        -67.31  108.01
BREWERIES            1.61        -10.89   33.92
CERAMICS             1.36        -71.79  123.98
REALTY               1.35        -25.42   46.03
REFINERIES           1.27        -20.16   50.56
ENGINEERING          1.24        -49.36  117.68
CEMENT               1.22        -67.08  192.08
CABLES               1.15          2.01  103.74
CHEMICALS            1.07        -89.49  244.08
JEWELLERY            1.02       -138.61  221.51
ENTERTAINMENT        0.77        -90.48  204.08
TEXTILES             0.45        -54.98   99.17
HOTELS               0.34       -157.47  248.28

In [29]:
# money to be made criteria-wise
df_portfolio_features.groupby('Criteria')['FTT Amt'].agg(['sum', 'count']).sort_values(by='sum', ascending=False)

                sum  count
Criteria
XY24      4044131.0     21
X40       1830755.0     16
XR        1387412.0     12
AR        1369352.0     10
X40N      1286972.0     10
OX40N      911594.0     10
XY25       519780.0      5
SR         314677.0      2

In [30]:
# money to be made conviction-wise
df_portfolio_features.groupby('Conviction')['FTT Amt'].agg(['sum', 'count']).sort_values(by='sum', ascending=False)

                  sum  count
Conviction
H-SC        3909936.0     24
X-MC        1842110.0     15
X-LC        1684995.0     13
M-SC        1616141.0     14
X-SC        1567221.0     10
H-MC         418137.0      3
L-SC         221273.0      2
M-LC         150219.0      1
M-MC         115807.0      2
H-LC          80630.0      1
L-MC          58204.0      1

In [31]:
# money to be made criteria and conviction-wise
df_portfolio_features.groupby(['Conviction', 'Criteria'])['FTT Amt'].agg(['sum', 'count']).sort_values(by='sum', ascending=False)

                           sum  count
Conviction Criteria
H-SC       XY24      1346465.0      6
           AR         986459.0      5
M-SC       XY24       929804.0      6
X-LC       X40        896691.0      7
H-SC       XR         877085.0      7
X-SC       XY24       857766.0      4
X-MC       X40        714162.0      7
           X40N       569889.0      4
X-SC       X40N       489553.0      4
M-SC       OX40N      414567.0      5
X-LC       XY24       390400.0      2
H-SC       OX40N      385250.0      4
           SR         314677.0      2
X-MC       XY25       284498.0      2
           XY24       273561.0      2
H-MC       XY24       246135.0      1
X-LC       X40N       227530.0      2
X-SC       X40        219902.0      2
M-SC       XR         192408.0      2
H-MC       AR         172002.0      2
X-LC       XY25       170374.0      2
M-LC       XR         150219.0      1
L-SC       OX40N      111777.0      1
           XR         109496.0      1
H-LC       AR          80630.0      1
M-SC       AR          79362.0      1
M-MC       XY25        64908.0      1
L-MC       XR          58204.0      1
M-MC       AR          50899.0      1

In [32]:
# notebook execution time

end_time = time.time()
execution_time = round(end_time - start_time, 0)
print(f"Notebook execution time: {execution_time} seconds")

Notebook execution time: 25.0 seconds