<a href="https://colab.research.google.com/github/ankit-rathi/Quantvesting_v2/blob/main/myStocks_Portfolio_Analysis.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
'''
!pip install pandas==2.2.2 -qq
!pip install pyxirr -qq
!pip install ta -qq
!pip install yfinance==0.2.59 -qq
'''

'\n!pip install pandas==2.2.2 -qq\n!pip install pyxirr -qq\n!pip install ta -qq\n!pip install yfinance==0.2.59 -qq\n'

In [2]:
# import libraries

import numpy as np
import pandas as pd
import datetime
import warnings
warnings.filterwarnings('ignore')
import yfinance as yfin
import ta
import matplotlib.pyplot as plt
import requests

In [3]:
# notebook start time
import time
import datetime
import pytz

start_time = time.time()

# function to print date timestamp
def print_date_time():
  tz_NY = pytz.timezone('Asia/Kolkata')
  datetime_NY = datetime.datetime.now(tz_NY)
  print("Run date time (IST):", datetime_NY.strftime("%Y-%m-%d %H:%M:%S"))

In [4]:
# function to get booked and reserved amount
def get_amt():
  # fetch the JSON data from the URL
  url = "https://raw.githubusercontent.com/ankit-rathi/Tradevesting_v1/main/data/myPortfolioAmts.json"
  response = requests.get(url)
  pf_amts = response.json()  # parse the JSON data

  # extract values from the JSON
  py_booked_amt_dm = pf_amts["py_booked_amt_dm"]
  py_booked_amt_sv = pf_amts["py_booked_amt_sv"]
  cy_booked_amt_dm = pf_amts["cy_booked_amt_dm"]
  cy_booked_amt_sv = pf_amts["cy_booked_amt_sv"]
  reserve_amt_dm = pf_amts["reserve_amt_dm"]
  reserve_amt_sv = pf_amts["reserve_amt_sv"]

  # perform calculations
  py_booked_amt = py_booked_amt_dm + py_booked_amt_sv
  cy_booked_amt = cy_booked_amt_dm + cy_booked_amt_sv
  reserve_amt = reserve_amt_dm + reserve_amt_sv
  total_booked_amt = py_booked_amt + cy_booked_amt

  return total_booked_amt, reserve_amt, cy_booked_amt, py_booked_amt

gen_output = 0

In [5]:
# function to format the amount
def format_amt(number):
    abs_number = abs(number)

    if abs_number >= 1_00_00_000:  # Crores
        formatted_amt = f"{number / 1_00_00_000:.2f} C"
    elif abs_number >= 1_00_000:  # Lakhs
        formatted_amt = f"{number / 1_00_000:.2f} L"
    elif abs_number >= 1_000:  # Thousands
        formatted_amt = f"{number / 1_000:.2f} K"
    else:
        formatted_amt = f"{number:.2f}"

    return formatted_amt

# function to set start and end date
def get_start_end_date():
  start_date = (datetime.date.today() + datetime.timedelta(days=-365)).strftime('%Y-%m-%d')
  end_date = (datetime.date.today() + datetime.timedelta(days=1)).strftime('%Y-%m-%d')
  return start_date, end_date

# function to fetch my portfolio csv
def get_mypfs_df():
  mypfs_df = pd.read_csv('https://raw.githubusercontent.com/ankit-rathi/Tradevesting_v1/main/data/myPortfolioStocks.csv')
  return mypfs_df

# function to fetch my prospects csv
def get_mypps_df():
  mypps_df = pd.read_csv('https://raw.githubusercontent.com/ankit-rathi/Tradevesting_v1/main/data/myProspectsScrips.csv')
  return mypps_df

# function to fetch screener data
def get_myscreen_df():
  myscreen_df = pd.read_csv('https://raw.githubusercontent.com/ankit-rathi/Tradevesting_v1/main/data/myScreenerDB.csv')
  return myscreen_df

# function to fetch momentum data
def get_myinvmt_df():
  myinvmt_df = pd.read_csv('https://raw.githubusercontent.com/ankit-rathi/Tradevesting_v1/main/data/myInvestments.csv')
  return myinvmt_df

# function to get the stock ids
def get_stock_ids(df_pf):
  stock_n100 = df_pf['Symbol'].unique()

  exclude = ['CADILAHC','MMTC', 'MASFIN']

  stock_ids = df_pf[~df_pf['Symbol'].isin(exclude) ]['Symbol'].unique()

  #mypf = mypf[mypf.Forecast.notnull()]
  #stock_ids = mypf['Symbol'].unique()

  #stock_ids.sort()
  return stock_ids

# get features from screener data
def get_screener_features():
  myscreen_df = get_myscreen_df()
  cols = ['Symbol', 'EPS', 'MedPE', 'ROCE%', 'ROE%', 'CapType']
  return myscreen_df[cols]

# get relative strength
def get_relative_strength(stock_list):

    # Dictionary to store stock tickers and their corresponding percentage price change
    stock_changes = {}

    # Loop through each stock and fetch its price data
    for stock in stock_list:
        try:
            # Download the stock data for the given date range
            stock_data = yfin.Ticker(stock + '.NS').history(period='1mo', interval='1d')[map(str.title, ['open', 'close', 'low', 'high', 'volume'])]

            # Calculate the percentage change for the stock
            if len(stock_data) > 0:
                start_price = stock_data['Close'].iloc[0]
                end_price = stock_data['Close'].iloc[-1]
                percent_change = round(((end_price - start_price) / start_price) * 100, 2)
                stock_changes[stock] = percent_change
            else:
                stock_changes[stock] = np.nan  # If no data is available, set to NaN

        except Exception as e:
            print(f"Error fetching data for {stock}: {e}")
            stock_changes[stock] = np.nan

    # Create a DataFrame with stock tickers and their percentage changes
    df = pd.DataFrame(list(stock_changes.items()), columns=['Symbol', 'Percent_Change'])

    # Drop any stocks with missing data (NaN values)
    df = df.dropna()

    # Calculate the percentile rank based on percentage change
    df['RSP'] = round(df['Percent_Change'].rank(pct=True) * 100, 2)
    cols = ['Symbol', 'RSP']
    df = df[cols]
    # Sort by percentile rank (optional)
    df = df.sort_values(by='RSP', ascending=False).reset_index(drop=True)

    return df

In [6]:
# function to get stock technicals
def stock_prec_dev(stock_symbol):
    #stock_symbol = 'ULTRACEMCO.NS'
    short_window = 20
    mid_window = 50
    long_window = 200
    moving_avg = 'SMA'

    start = datetime.datetime(*map(int, start_date.split('-')))
    end = datetime.datetime(*map(int, end_date.split('-')))

    stock_df = yfin.Ticker(stock_symbol + '.NS').history(period='max', interval='1d')[map(str.title, ['open', 'close', 'low', 'high', 'volume'])]

    stock_df['Max'] = round(max(stock_df['Close']),2)
    stock_df = stock_df[(stock_df.index <= end_date) & (stock_df.index >= start_date)]
    stock_df['200_SMA'] = round(stock_df['Close'].rolling(window = 200, min_periods = 1).mean(),0)
    stock_df['Dev%_200'] = round((stock_df['Close'] - stock_df['200_SMA'])*100/stock_df['200_SMA'],2)
    stock_df.dropna(axis = 0, inplace = True) # remove any null rows

    stock_df['20_SMA'] = stock_df['Close'].rolling(window=20).mean()
    stock_df['50_SMA'] = stock_df['Close'].rolling(window=50).mean()
    stock_df['Symbol'] = stock_symbol

    stock_df['Close'] = round(stock_df['Close'],2)
    stock_df['Min'] = round(min(stock_df['Close']),2)
    stock_df['RSI_14'] = ta.momentum.RSIIndicator(close=stock_df['Close'], window=14).rsi()
    stock_df['RSI_14'] = round(stock_df['RSI_14'],0)
    stock_df['Prev_Close'] = stock_df['Close'].shift(1)
    stock_df.drop(['Open', 'Low', 'High', 'Volume'], axis=1, inplace=True)
    stock_df = stock_df.tail(1)

    max_SMA = max(stock_df['20_SMA'].item(), stock_df['50_SMA'].item(), stock_df['200_SMA'].item())
    min_SMA = min(stock_df['20_SMA'].item(), stock_df['50_SMA'].item(), stock_df['200_SMA'].item())
    ABS_Spread = max_SMA - min_SMA
    stock_df['Spread%'] = round((ABS_Spread / stock_df['200_SMA'].item()) * 100,2)

    return stock_df

# function to compute stock attributes
def get_common_features(stock_ids, df_mypf):

  df_prec_dev = pd.DataFrame()
  df_tmp = get_screener_features()
  df_rs = get_relative_strength(stock_ids)

  for stock_id in stock_ids:
      tmp = stock_prec_dev(stock_id)
      tmp = tmp.reset_index()
      df_prec_dev = pd.concat([df_prec_dev, tmp], ignore_index = True)
  df_prec_dev = pd.merge(df_prec_dev, df_mypf, on= 'Symbol')
  df_prec_dev = pd.merge(df_prec_dev, df_tmp, on= 'Symbol', how='left')
  df_prec_dev = pd.merge(df_prec_dev, df_rs, on= 'Symbol', how='left')
  #print(df_prec_dev.columns)
  df_prec_dev['Curr_PE'] = round(df_prec_dev['Close']/df_prec_dev['EPS'],1)
  df_prec_dev['Dev%_PE'] = round((df_prec_dev['Curr_PE'] - df_prec_dev['MedPE'])*100/df_prec_dev['MedPE'],2)
  df_prec_dev['Conviction'] = df_prec_dev['Conviction'] + '-' + df_prec_dev['CapType']
  return df_prec_dev

# function to arrange stock features
def arrange_features(df_stocks, common_cols, diff_cols):
  df_stocks_common = df_stocks[common_cols].drop_duplicates()
  df_stocks_diff = df_stocks[diff_cols]
  df_stocks_diff['Investment'] = df_stocks_diff['AvgCost'] * df_stocks_diff['Shares']
  df_stocks_diff = df_stocks_diff.groupby(['Symbol'])[['Shares', 'Investment']].aggregate(['sum']).reset_index()
  df_stocks_diff.columns = ['Symbol', 'Shares', 'Investment']
  df_stocks_diff['AvgCost'] = round(df_stocks_diff['Investment']/df_stocks_diff['Shares'],2)
  df_stocks = pd.merge(df_stocks_diff, df_stocks_common, on='Symbol')
  return df_stocks

# plot fact distribution across dimension
def plot_pie_chart(df, dimension, fact):
  # grouping the data by category and calculating the sum of fact for each type
  grouped_data = df.groupby(dimension)[fact].sum()

  # sorting the grouped data in descending order
  grouped_data = grouped_data.sort_values(ascending=False)

  # creating a pie chart
  grouped_data.plot.pie(autopct='%1.1f%%', startangle=90, figsize=(6, 6))

  # adding a title and displaying the plot
  plt.title(f'{dimension} {fact} Distribution')
  plt.ylabel('')  # To hide the y-label
  plt.show()

In [7]:
# function to get portfolio features

def get_portfolio_features(df_common_features):

  print_date_time()
  print('-------------------')

  #df_common_features["Target"] = df_common_features["Target"].fillna(df_common_features["Max"])
  df_common_features['NTT'] = np.where(df_common_features['Strategy']== 'NTT', df_common_features["Target"], df_common_features['Max'])
  df_common_features['LTT'] = np.where(df_common_features['Strategy']== 'BTT', df_common_features["Target"], df_common_features['Max'])
  df_common_features['BOL'] = df_common_features['Min']

  tmp_df = df_common_features[df_common_features['Symbol'].isin(mypf_df[mypf_df['InPortfolio'] != 'NA'].Symbol.values)]
  print('qualified stocks: '+str(len(tmp_df['Symbol'].unique())))
  tmp_df1 = tmp_df[tmp_df['LatestQtr'] == 1]
  print('with latest results: '+str(len(tmp_df1['Symbol'].unique())))
  tmp_df1 = tmp_df1[tmp_df1['StarStock'] == 1]
  print('still star stocks: '+str(len(tmp_df1['Symbol'].unique())))
  tmp_df['Investment'] = tmp_df['AvgCost'] * tmp_df['Shares']
  tmp_df['Current'] = round(tmp_df['Close'] * tmp_df['Shares'],0)
  tmp_df['Previous'] = tmp_df['Prev_Close'] * tmp_df['Shares']
  tmp_df['EstimatedST'] = tmp_df['NTT'] * tmp_df['Shares']
  tmp_df['EstimatedLT'] = tmp_df['LTT'] * tmp_df['Shares']
  tmp_df['Current P/L'] = round((tmp_df['Current'] - tmp_df['Investment']),0)
  tmp_df['Today P/L%'] = round((tmp_df['Current'] - tmp_df['Previous'])*100/tmp_df['Previous'],2)
  tmp_df['Current P/L%'] = round((tmp_df['Current'] - tmp_df['Investment'])*100/tmp_df['Investment'],2)
  tmp_df['EstimatedST P/L%'] = round((tmp_df['EstimatedST'] - tmp_df['Investment'])*100/tmp_df['Investment'],2)
  tmp_df['EstimatedLT P/L%'] = round((tmp_df['EstimatedLT'] - tmp_df['Investment'])*100/tmp_df['Investment'],2)
  tmp_df['NTT%'] = round((tmp_df['NTT'] - tmp_df['Close'])*100/tmp_df['Close'],2)
  tmp_df['LTT%'] = round((tmp_df['LTT'] - tmp_df['Close'])*100/tmp_df['Close'],2)
  tmp_df['Gained%'] = round((tmp_df['Close'] - tmp_df['BOL'])*100/tmp_df['BOL'],2)
  investment = round(sum(tmp_df['AvgCost']*tmp_df['Shares']),0)
  current = round(sum(tmp_df['Close']*tmp_df['Shares']),0)
  tmp_df['InitAlloc%'] = round(tmp_df['Investment']*100/investment,2)
  tmp_df['CurrAlloc%'] = round(tmp_df['Current']*100/current,2)
  tmp_df['FTT'] = tmp_df['LTT']
  tmp_df.loc[tmp_df['Strategy'] == 'NTT', 'FTT'] = tmp_df['NTT']
  tmp_df['FTT%'] = tmp_df['LTT%']
  tmp_df.loc[tmp_df['Strategy'] == 'NTT', 'FTT%'] = tmp_df['NTT%']
  tmp_df['FTT Amt'] = round(tmp_df['FTT%'] * tmp_df['Current']/100,0)
  tmp_df['OTT%'] = round((tmp_df['FTT'] - tmp_df['AvgCost'])*100/tmp_df['AvgCost'],2)
  tmp_df['RRR Ind'] = round(tmp_df['Current P/L']/tmp_df['FTT Amt'],2)
  tmp_df['Risk Ind'] = round(tmp_df['Current P/L%']*tmp_df['CurrAlloc%'],0)

  return tmp_df

# function to print portfolio features
def print_portfolio_stats(df_portfolio_features, myinvmt_df):
  from pyxirr import xirr

  total_booked_amt, reserve_amt, cy_booked_amt, py_booked_amt = get_amt()

  dates = myinvmt_df['Date'].values
  dates = np.append(dates, datetime.date.today().strftime('%d-%b-%y'))
  investment = myinvmt_df['Investment'].values
  dates= pd.to_datetime(dates)

  current = round(sum(df_portfolio_features['Close']*df_portfolio_features['Shares']),0) + reserve_amt
  investment_xirr = np.append(investment, current)
  cagr = round(xirr(pd.DataFrame({"dates": dates, "amounts": investment_xirr}))*100,2)

  investment = -sum(investment)
  invested = round(sum(df_portfolio_features['AvgCost']*df_portfolio_features['Shares']),0) + reserve_amt
  previous = round(sum(df_portfolio_features['Prev_Close']*df_portfolio_features['Shares']),0) + reserve_amt
  cy_invested = investment + py_booked_amt

  today_pnl_amount = current-previous
  today_pnl_percentage = round((current-previous)*100/previous,2)

  curr_pnl_amount = current-invested
  curr_pnl_percentage = round((curr_pnl_amount)*100/(cy_invested),2)

  cy_pnl_amount = cy_booked_amt + curr_pnl_amount
  cy_pnl_percentage = round((cy_pnl_amount)*100/cy_invested,2)

  overall_pnl_amount = total_booked_amt + curr_pnl_amount
  overall_pnl_percentage = round((overall_pnl_amount)*100/investment,2)

  estimate_st = round(sum(df_portfolio_features['FTT']*df_portfolio_features['Shares']),0)  + reserve_amt
  est_st_pnl_amount = estimate_st-current
  est_st_pnl_percentage = round((est_st_pnl_amount)*100/current,2)

  estimate_lt = round(sum(df_portfolio_features['LTT']*df_portfolio_features['Shares']),0)  + reserve_amt
  est_lt_pnl_amount = estimate_lt-current
  est_lt_pnl_percentage = round((est_lt_pnl_amount)*100/current,2)

  total_profit = round(sum(df_portfolio_features[df_portfolio_features['Current P/L%'] > 0]['Current']) - sum(df_portfolio_features[df_portfolio_features['Current P/L%'] > 0]['Investment']),0)
  total_loss = round(sum(df_portfolio_features[df_portfolio_features['Current P/L%'] < 0]['Current']) - sum(df_portfolio_features[df_portfolio_features['Current P/L%'] < 0]['Investment']),0)

  cy_booked_percentage = round((cy_booked_amt)*100/current,2)
  py_booked_percentage = round((py_booked_amt)*100/investment,2)
  total_booked_percentage = round((total_booked_amt)*100/investment,2)

  print('-------------------')
  print('Initial Investment: ', format_amt(investment))
  print('CY Investment: ', format_amt(cy_invested))
  print('Reserve: ', format_amt(reserve_amt))
  print('Current: ',  format_amt(current))
  print('-------------------')
  print('Today PnL: '+ '{} ({}%)'.format(format_amt(today_pnl_amount), today_pnl_percentage))
  print('Current PnL: '+ '{} ({}%)'.format(format_amt(curr_pnl_amount), curr_pnl_percentage))
  print('CY Booked + Current PnL: '+ '{} ({}%)'.format(format_amt(cy_pnl_amount), cy_pnl_percentage))
  print('-------------------')
  print('Total profit: ', format_amt(total_profit))
  print('Total loss: ', format_amt(total_loss))
  print('-------------------')
  print('Total Booked + Current PnL: '+ '{} ({}%)'.format(format_amt(overall_pnl_amount), overall_pnl_percentage))
  print('Total Booked PnL: '+ '{} ({}%)'.format(format_amt(total_booked_amt), total_booked_percentage))
  print('Curr Year Booked PnL: '+ '{} ({}%)'.format(format_amt(cy_booked_amt), cy_booked_percentage))
  print('Prev Year Booked PnL: '+ '{} ({}%)'.format(format_amt(py_booked_amt), py_booked_percentage))
  print('===================')
  print('Est FTT: ',  format_amt(estimate_st))
  print('Est FTT PnL: '+ '{} ({}%)'.format(format_amt(est_st_pnl_amount), est_st_pnl_percentage))

  print('===================')
  print('Deployed: ', format_amt(investment))

  print('Current: ', format_amt(current))

  print('CAGR/XIRR %: '+'{}%'.format(cagr))

In [8]:
# get start and end date
start_date, end_date = get_start_end_date()

# get portfolio and prospects data
mypfs_df = get_mypfs_df()
mypps_df = get_mypps_df()
myinvmt_df = get_myinvmt_df()

# merge above datasets
mypf_df = pd.merge(mypfs_df, mypps_df, on="Symbol")

# seggregate dm and sv portfolio
dm_pf = mypf_df[mypf_df['InPortfolio'] == 'DM']
sv_pf = mypf_df[mypf_df['InPortfolio'] == 'SV']

# build portfolio stock dataframe
dm_stocks = get_stock_ids(dm_pf)
sv_stocks = get_stock_ids(sv_pf)
df_stocks = pd.concat([dm_pf,sv_pf], ignore_index = True)

# arrange common and diff stock features
common_cols = ['Symbol', 'Target', 'Criteria', 'Strategy', 'CumlRnk', 'LatestQtr', 'StarStock', 'Conviction', 'Category', 'InFolio', 'XIRR', 'MBQ']
diff_cols = ['Symbol', 'AvgCost', 'Shares']
df_stocks = arrange_features(df_stocks, common_cols, diff_cols)

# get common features
stock_ids = df_stocks['Symbol'].values
df_common_features = get_common_features(stock_ids, df_stocks)

df_common_features.reset_index(drop=True, inplace=True)
df_common_features.drop(['Date'], axis=1, inplace=True)
# get and print portfolio features
df_portfolio_features = get_portfolio_features(df_common_features)

print_portfolio_stats(df_portfolio_features, myinvmt_df)

df = df_portfolio_features
#plot_pie_chart(df, 'CapType', 'Current')
list_ox40n = list(df[df['MBQ'].str.contains('OX40N', na=False)]['Symbol'].values)

Run date time (IST): 2026-04-02 12:51:45
-------------------
qualified stocks: 86
with latest results: 26
still star stocks: 16
-------------------
Initial Investment:  1.36 C
CY Investment:  1.62 C
Reserve:  1.61 K
Current:  1.27 C
-------------------
Today PnL: -1.39 L (-1.08%)
Current PnL: -49.64 L (-30.55%)
CY Booked + Current PnL: -33.75 L (-20.77%)
-------------------
Total profit:  37.15 K
Total loss:  -50.01 L
-------------------
Total Booked + Current PnL: -6.77 L (-5.0%)
Total Booked PnL: 42.87 L (31.64%)
Curr Year Booked PnL: 15.89 L (12.46%)
Prev Year Booked PnL: 26.98 L (19.91%)
===================
Est FTT:  2.48 C
Est FTT PnL: 1.20 C (94.44%)
===================
Deployed:  1.36 C
Current:  1.27 C
CAGR/XIRR %: -2.95%

In [9]:
# top 5 near their targets
cols = ['Symbol', 'Today P/L%', 'Current P/L%', 'FTT%', 'OTT%', 'FTT Amt', 'Current P/L', 'Current', 'FTT', 'Dev%_PE', 'RSI_14','Conviction', 'Spread%',  'CumlRnk', 'RRR Ind', 'CurrAlloc%', 'Gained%', 'Criteria', 'Strategy', 'Category']
df_tmp = df_portfolio_features[~df_portfolio_features['Symbol'].isin(['ENRIN','BLUSPRING','DIGITIDE'])]
df_tmp = df_tmp.sort_values(by = 'FTT Amt', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
50,MASFIN,0.58,-9.69,34.61,21.57,30625.0,-9495.0,88485.0,397.04,-22.31,45.0,H-SC,4.90,167.0,-0.31,0.69,20.69,XR,ATH,FINANCE
77,TTKPRESTIG,-1.57,-43.04,75.72,0.09,43466.0,-43373.0,57404.0,770.00,33.19,37.0,M-SC,22.17,250.0,-1.00,0.45,2.22,OX40N,NTT,DURABLES
2,ABBOTINDIA,-0.76,-11.81,33.87,18.07,53427.0,-21115.0,157740.0,35195.00,-24.86,47.0,X-MC,10.43,58.0,-0.40,1.24,3.16,X40,ATH,PHARMA
67,SONACOMS,-0.97,-14.81,63.27,39.09,54525.0,-14980.0,86179.0,804.02,-32.49,46.0,M-MC,6.72,193.0,-0.27,0.68,21.91,AR,ATH,AUTO
42,INDUSINDBK,-2.97,-43.72,136.11,32.89,59145.0,-33752.0,43454.0,1800.00,-304.48,35.0,L-MC,6.66,258.0,-0.57,0.34,12.79,XR,NTT,BANKS

In [10]:
# top 5 today
df_tmp = df_portfolio_features.sort_values(by = 'Today P/L%', ascending=False)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
55,RAJESHEXPO,4.85,-83.14,493.36,0.07,114134.0,-114043.0,23134.0,518.00,748.48,27.0,L-SC,42.39,268.0,-1.00,0.18,8.61,OX40N,NTT,JEWELLERY
52,PAGEIND,3.28,-12.13,52.62,34.11,124094.0,-32549.0,235830.0,51418.64,-36.94,61.0,X-MC,20.33,55.0,-0.26,1.85,11.56,X40,ATH,APPARELS
15,BSOFT,2.10,-35.28,132.97,50.79,121049.0,-49618.0,91035.0,831.70,-16.89,46.0,H-SC,8.51,172.0,-0.41,0.71,7.35,XR,ATH,IT
12,BATAINDIA,1.88,-58.73,227.58,35.20,120863.0,-75562.0,53108.0,2096.00,-30.40,35.0,X-SC,34.08,91.0,-0.63,0.42,5.33,X40,NTT,FOOTWEAR
0,5PAISA,1.65,-47.71,115.90,12.90,132426.0,-104237.0,114259.0,593.00,68.27,40.0,H-SC,16.64,170.0,-0.79,0.90,10.26,OX40N,NTT,FINANCE

In [11]:
# bottom 5 today
df_tmp = df_portfolio_features.sort_values(by = 'Today P/L%', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
38,ICICIPRULI,-3.77,-18.25,59.92,30.73,96498.0,-35961.0,161044.0,790.00,-40.17,18.0,X-MC,8.80,78.0,-0.37,1.26,0.00,X40,ATH,INSURANCE
11,BANDHANBNK,-3.72,-31.61,181.35,92.42,345486.0,-88051.0,190508.0,400.00,63.07,35.0,H-SC,0.98,174.0,-0.25,1.49,4.95,XY24,NTT,BANKS
47,JSWINFRA,-3.53,-18.57,42.98,16.43,77620.0,-41178.0,180596.0,342.00,-30.19,41.0,X-MC,11.94,61.0,-0.53,1.42,0.00,X40N,NTT,REALTY
37,ICICIGI,-3.35,-13.22,37.52,19.34,65153.0,-26460.0,173649.0,2252.93,-26.94,24.0,X-MC,6.10,66.0,-0.41,1.36,0.00,X40,ATH,INSURANCE
6,ASIANPAINT,-3.14,-22.41,60.49,24.52,133025.0,-63527.0,219912.0,3460.25,-21.71,40.0,X-LC,11.60,30.0,-0.48,1.73,1.64,X40,ATH,PAINTS

In [12]:
# top 5 to exit based on CumlRnk
df_tmp = df_portfolio_features[~df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])]
df_tmp = df_tmp[(df_tmp['Current P/L%'] > -1) & (df_tmp['Current P/L%'] < 1)].sort_values(by = 'CumlRnk', ascending=False)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
26,FINCABLES,-1.12,0.03,107.84,107.91,159272.0,49.0,147693.0,1641.55,-10.2,43.0,M-SC,5.62,220.0,0.0,1.16,11.11,OX40N,ATH,CABLES

In [13]:
# OX40N stocks to exit
df_tmp = df_portfolio_features[(df_portfolio_features['Symbol'].isin(list_ox40n))].sort_values(by = 'Current P/L%', ascending=False)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
26,FINCABLES,-1.12,0.03,107.84,107.91,159272.0,49.0,147693.0,1641.55,-10.20,43.0,M-SC,5.62,220.0,0.00,1.16,11.11,OX40N,ATH,CABLES
66,SIS,-0.14,-34.09,83.97,21.26,61453.0,-37847.0,73185.0,528.00,1713.47,48.0,H-SC,14.74,168.0,-0.62,0.57,8.82,OX40N,NTT,MISC
18,CERA,-1.76,-40.05,106.65,23.89,112470.0,-70446.0,105457.0,9475.00,-42.24,43.0,H-SC,19.37,153.0,-0.63,0.83,1.34,OX40N,NTT,CERAMICS
72,TATAELXSI,0.14,-40.44,121.65,32.03,95528.0,-53308.0,78527.0,9161.00,-25.57,40.0,H-SC,21.85,158.0,-0.56,0.62,3.93,OX40N,NTT,IT
48,KANSAINER,0.61,-41.05,92.49,13.47,147029.0,-110700.0,158967.0,340.00,-49.34,44.0,H-SC,23.14,162.0,-0.75,1.25,11.04,XY24,NTT,PAINTS

In [14]:
# top 5 to book for rotation
df_tmp = df_portfolio_features[(df_portfolio_features['Current P/L%'] > 20) ].sort_values(by = 'CumlRnk', ascending=False)
df_tmp[cols].head()

Empty DataFrame
Columns: [Symbol, Today P/L%, Current P/L%, FTT%, OTT%, FTT Amt, Current P/L, Current, FTT, Dev%_PE, RSI_14, Conviction, Spread%, CumlRnk, RRR Ind, CurrAlloc%, Gained%, Criteria, Strategy, Category]
Index: []

In [15]:
# top 5 to monitor for exit
df_tmp = df_portfolio_features[~df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])]
df_tmp = df_tmp[(df_tmp['Current P/L%'] > 0) ].sort_values(by = 'Dev%_PE', ascending=False)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
26,FINCABLES,-1.12,0.03,107.84,107.91,159272.0,49.0,147693.0,1641.55,-10.20,43.0,M-SC,5.62,220.0,0.00,1.16,11.11,OX40N,ATH,CABLES
1,ABB,-0.39,10.81,31.37,45.57,90940.0,28277.0,289896.0,7934.00,-28.75,49.0,H-MC,13.24,125.0,0.31,2.27,28.73,AR,NTT,ELECTRICAL

In [16]:
# top 5 to book for rotation from weak conviction
df_tmp = df_portfolio_features[~df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])]
df_tmp = df_tmp[~df_tmp['Criteria'].isin(['XY25','XY24','X40', 'X40N'])].sort_values(by = 'RRR Ind', ascending=False)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
1,ABB,-0.39,10.81,31.37,45.57,90940.0,28277.0,289896.0,7934.00,-28.75,49.0,H-MC,13.24,125.0,0.31,2.27,28.73,AR,NTT,ELECTRICAL
26,FINCABLES,-1.12,0.03,107.84,107.91,159272.0,49.0,147693.0,1641.55,-10.20,43.0,M-SC,5.62,220.0,0.00,1.16,11.11,OX40N,ATH,CABLES
40,INDIAMART,-0.93,-13.20,138.16,106.72,147907.0,-16281.0,107055.0,4810.62,-60.94,43.0,H-SC,12.93,140.0,-0.11,0.84,7.09,AR,ATH,MISC
85,ZYDUSLIFE,-0.93,-9.82,50.40,35.63,95250.0,-20586.0,188988.0,1286.17,-21.62,39.0,H-MC,5.69,120.0,-0.22,1.48,5.21,AR,ATH,PHARMA
84,WIPRO,0.37,-21.30,118.89,72.27,158548.0,-36091.0,133357.0,420.00,-28.77,40.0,M-LC,18.22,98.0,-0.23,1.05,2.31,XR,NTT,IT

In [17]:
# top 5 to accumulate based on lowest RSI_14
df_tmp = df_portfolio_features[df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])].sort_values(by = 'RSI_14', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
38,ICICIPRULI,-3.77,-18.25,59.92,30.73,96498.0,-35961.0,161044.0,790.00,-40.17,18.0,X-MC,8.80,78.0,-0.37,1.26,0.00,X40,ATH,INSURANCE
37,ICICIGI,-3.35,-13.22,37.52,19.34,65153.0,-26460.0,173649.0,2252.93,-26.94,24.0,X-MC,6.10,66.0,-0.41,1.36,0.00,X40,ATH,INSURANCE
21,DABUR,-1.75,-20.29,80.28,43.70,158741.0,-50334.0,197734.0,735.00,-27.60,27.0,X-MC,11.03,70.0,-0.32,1.55,0.00,XY24,BTT,FMCG
32,HAVELLS,-2.31,-25.83,78.06,32.08,189908.0,-84706.0,243285.0,2062.85,-30.22,28.0,X-MC,11.37,63.0,-0.45,1.91,0.00,X40,ATH,ELECTRICAL
34,HDFCBANK,-0.74,-11.86,45.64,28.37,94487.0,-27858.0,207027.0,1073.00,-24.98,29.0,X-LC,15.57,26.0,-0.29,1.62,0.71,X40,BTT,BANKS

In [18]:
# top 5 to accumulate based on Spread and CumlRnk
df_tmp = df_portfolio_features[df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])]
df_tmp = df_tmp[(df_tmp['CumlRnk'] < 100)].sort_values(by = 'Spread%', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
65,SIEMENS,-1.69,-20.31,57.51,25.51,85284.0,-37800.0,148295.0,4671.50,24.61,41.0,H-LC,0.44,51.0,-0.44,1.16,9.21,AR,ATH,ELECTRICAL
82,VOLTAS,-2.23,-4.42,51.91,45.20,95135.0,-8472.0,183270.0,1856.00,9.49,32.0,X-MC,3.02,79.0,-0.09,1.44,2.08,XY25,NTT,AC
78,UNITDSPR,-2.71,-10.71,35.25,20.77,73696.0,-25078.0,209066.0,1644.00,-20.80,36.0,X-MC,3.76,64.0,-0.34,1.64,0.00,X40N,NTT,BREWERIES
59,RELIANCE,-1.84,-13.73,45.24,25.30,78435.0,-27587.0,173376.0,1952.00,-15.80,39.0,X-LC,3.90,21.0,-0.35,1.36,15.76,XY25,BTT,REFINERIES
37,ICICIGI,-3.35,-13.22,37.52,19.34,65153.0,-26460.0,173649.0,2252.93,-26.94,24.0,X-MC,6.10,66.0,-0.41,1.36,0.00,X40,ATH,INSURANCE

In [19]:
# top 5 to accumulate based on lowest Gained%
df_tmp = df_portfolio_features[df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])].sort_values(by = 'Gained%', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
21,DABUR,-1.75,-20.29,80.28,43.70,158741.0,-50334.0,197734.0,735.00,-27.60,27.0,X-MC,11.03,70.0,-0.32,1.55,0.0,XY24,BTT,FMCG
38,ICICIPRULI,-3.77,-18.25,59.92,30.73,96498.0,-35961.0,161044.0,790.00,-40.17,18.0,X-MC,8.80,78.0,-0.37,1.26,0.0,X40,ATH,INSURANCE
35,HINDUNILVR,-1.18,-20.63,43.21,13.67,88166.0,-53023.0,204040.0,2922.00,-41.16,32.0,X-LC,11.03,9.0,-0.60,1.60,0.0,XY25,NTT,FMCG
47,JSWINFRA,-3.53,-18.57,42.98,16.43,77620.0,-41178.0,180596.0,342.00,-30.19,41.0,X-MC,11.94,61.0,-0.53,1.42,0.0,X40N,NTT,REALTY
37,ICICIGI,-3.35,-13.22,37.52,19.34,65153.0,-26460.0,173649.0,2252.93,-26.94,24.0,X-MC,6.10,66.0,-0.41,1.36,0.0,X40,ATH,INSURANCE

In [20]:
# top 5 to accumulate based on lowest CurrAlloc%
df_tmp = df_portfolio_features[df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])].sort_values(by = 'CurrAlloc%', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
58,RELAXO,0.83,-65.99,347.81,52.31,171717.0,-95789.0,49371.0,1176.00,-63.80,35.0,X-SC,31.45,92.0,-0.56,0.39,10.39,X40N,NTT,FOOTWEAR
12,BATAINDIA,1.88,-58.73,227.58,35.20,120863.0,-75562.0,53108.0,2096.00,-30.40,35.0,X-SC,34.08,91.0,-0.63,0.42,5.33,X40,NTT,FOOTWEAR
54,QUESS,-0.06,-27.73,140.64,73.90,108540.0,-29617.0,77176.0,424.00,-60.88,42.0,X-SC,22.38,80.0,-0.27,0.61,3.82,XY24,NTT,MISC
36,HONAUT,-2.09,-30.72,118.40,51.31,158182.0,-59238.0,133600.0,58357.33,-42.35,32.0,X-SC,17.99,90.0,-0.37,1.05,1.50,X40N,ATH,ELECTRICAL
51,MEDANTA,-1.27,-16.46,52.16,27.12,76919.0,-29050.0,147467.0,1486.00,-18.99,35.0,X-SC,15.19,87.0,-0.38,1.16,1.61,XY24,NTT,HEALTHCARE

In [21]:
# top 5 to accumulate based on CumlRnk
df_tmp = df_portfolio_features.sort_values(by = 'CumlRnk', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
45,ITC,0.03,-23.14,54.90,19.06,143538.0,-78713.0,261453.0,452.00,-57.95,36.0,X-LC,19.72,1.0,-0.55,2.05,1.43,X40,NTT,FMCG
73,TCS,0.11,-29.22,78.84,26.57,258502.0,-135391.0,327882.0,4311.59,-40.02,37.0,X-LC,18.64,2.0,-0.52,2.57,2.33,X40,ATH,IT
43,INFY,-0.49,-13.59,55.35,34.24,149656.0,-42506.0,270382.0,1972.00,-32.15,42.0,X-LC,15.07,3.0,-0.28,2.12,3.98,X40,NTT,IT
75,TMPV,-1.91,-32.36,101.92,36.58,245312.0,-115150.0,240691.0,600.00,-85.81,34.0,X-LC,11.27,4.0,-0.47,1.89,0.32,XY24,NTT,AUTO
33,HCLTECH,0.96,-11.26,39.55,23.83,84907.0,-27242.0,214682.0,1908.19,-6.95,46.0,X-LC,11.58,8.0,-0.32,1.68,4.24,X40,ATH,IT

In [22]:
# top 5 for average up
df_tmp = df_portfolio_features[(df_portfolio_features['Dev%_200'] > 5)].sort_values(by = 'CurrAlloc%', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
1,ABB,-0.39,10.81,31.37,45.57,90940.0,28277.0,289896.0,7934.0,-28.75,49.0,H-MC,13.24,125.0,0.31,2.27,28.73,AR,NTT,ELECTRICAL

In [23]:
# top 5 RSP
df_tmp = df_portfolio_features.sort_values(by = 'RSP', ascending=False)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
24,DMART,0.84,3.53,25.18,29.60,65070.0,8820.0,258420.0,5391.45,-12.73,72.0,X-LC,6.35,14.0,0.14,2.03,18.12,X40N,ATH,FMCG
30,HAPPSTMNDS,-1.62,-51.76,283.21,84.85,175092.0,-66341.0,61824.0,1480.71,-42.72,50.0,H-SC,24.42,152.0,-0.38,0.49,14.49,AR,ATH,IT
52,PAGEIND,3.28,-12.13,52.62,34.11,124094.0,-32549.0,235830.0,51418.64,-36.94,61.0,X-MC,20.33,55.0,-0.26,1.85,11.56,X40,ATH,APPARELS
5,ANGELONE,-2.04,-3.40,28.55,24.18,84115.0,-10375.0,294625.0,303.00,-85.87,52.0,X-SC,9.70,97.0,-0.12,2.31,13.40,X40N,NTT,FINANCE
80,VALIANTORG,1.06,-51.54,259.36,74.15,205634.0,-84320.0,79285.0,838.00,-242.86,51.0,H-SC,27.60,145.0,-0.41,0.62,17.99,XR,NTT,CHEMICALS

In [24]:
# Top N allocation
df_tmp = df_portfolio_features.sort_values(by = 'CurrAlloc%', ascending=False)
top_n_values = [10, 25, 50]

sum_df = pd.DataFrame({
    'Top_N': top_n_values,
    'Sum_Alloc%': [df_tmp['CurrAlloc%'].head(n).sum() for n in top_n_values]
})

sum_df

   Top_N  Sum_Alloc%
0     10       21.11
1     25       46.20
2     50       78.12

In [25]:
# market-cap-wise allocation
df_tmp = df_portfolio_features[cols]
df_tmp.groupby(df_tmp['Conviction'].str[-2:])['CurrAlloc%'].sum().sort_values(ascending=False)

Conviction
SC    44.55
MC    29.67
LC    25.80
Name: CurrAlloc%, dtype: float64

In [26]:
# criteria-wise allocation
df_portfolio_features.groupby('Criteria')['CurrAlloc%'].sum().sort_values(ascending=False)

Criteria
XY24     27.01
X40      25.38
X40N     15.47
AR        9.17
XR        8.33
XY25      7.20
OX40N     6.66
SR        0.80
Name: CurrAlloc%, dtype: float64

In [27]:
# conviction-wise allocation
df_portfolio_features.groupby('Conviction')['CurrAlloc%'].sum().sort_values(ascending=False)

Conviction
X-LC    23.59
X-MC    22.23
H-SC    21.79
X-SC    12.33
M-SC     9.89
H-MC     5.04
M-MC     2.06
H-LC     1.16
M-LC     1.05
L-SC     0.54
L-MC     0.34
Name: CurrAlloc%, dtype: float64

In [28]:
# sector-wise stats
df_tmp = df_portfolio_features.groupby('Category')[['CurrAlloc%', 'Current', 'Current P/L', 'FTT Amt']].sum().sort_values(by=['Current', 'Current P/L'], ascending=False)
df_tmp['Current P/L%'] = round(df_tmp['Current P/L'] * 100 / df_tmp['Current'], 2)
df_tmp['FTT%'] = round(df_tmp['FTT Amt'] * 100 / df_tmp['Current'], 2)
cols = ['CurrAlloc%', 'Current P/L%', 'FTT%']
df_tmp[cols].sort_values(by=['CurrAlloc%'], ascending=False)

               CurrAlloc%  Current P/L%    FTT%
Category
FMCG                15.35        -27.74   73.09
FINANCE             13.17        -28.00   80.16
IT                  12.09        -46.26  120.70
MISC                 7.03        -49.63  114.63
ELECTRICAL           6.39        -18.83   64.33
PAINTS               5.25        -47.33   72.91
INSURANCE            4.57        -16.17   55.92
BANKS                4.45        -35.52  104.31
PHARMA               4.16        -10.93   45.84
AUTO                 3.65        -40.75   96.59
AC                   1.93        -30.16   65.46
HEALTHCARE           1.90        -47.76   86.31
APPARELS             1.85        -13.80   52.62
FOOTWEAR             1.80        -92.82  170.14
TRAVEL               1.78        -97.94  197.05
DURABLES             1.76        -71.92  113.75
BREWERIES            1.64        -12.00   35.25
REALTY               1.42        -22.80   42.98
REFINERIES           1.36        -15.91   45.24
CERAMICS             1.36        -77.01  130.78
CEMENT               1.24        -70.12  197.40
CABLES               1.16          0.03  107.84
ENGINEERING          1.08        -75.99  156.48
CHEMICALS            1.06        -95.77  255.49
JEWELLERY            0.99       -152.93  240.80
ENTERTAINMENT        0.76        -99.57  218.59
TEXTILES             0.46        -58.26  103.39
HOTELS               0.36       -144.99  231.40

In [29]:
# money to be made criteria-wise
df_portfolio_features.groupby('Criteria')['FTT Amt'].agg(['sum', 'count']).sort_values(by='sum', ascending=False)

                sum  count
Criteria
XY24      4155036.0     21
X40       1939329.0     16
XR        1428887.0     12
AR        1402078.0     10
X40N      1329345.0     10
OX40N      943348.0     10
XY25       523580.0      5
SR         318091.0      2

In [30]:
# money to be made conviction-wise
df_portfolio_features.groupby('Conviction')['FTT Amt'].agg(['sum', 'count']).sort_values(by='sum', ascending=False)

                  sum  count
Conviction
H-SC        4015380.0     24
X-MC        1901028.0     15
X-LC        1769006.0     13
M-SC        1656406.0     14
X-SC        1613139.0     10
H-MC         436049.0      3
L-SC         221386.0      2
M-LC         158548.0      1
M-MC         124323.0      2
H-LC          85284.0      1
L-MC          59145.0      1

In [31]:
# money to be made criteria and conviction-wise
df_portfolio_features.groupby(['Conviction', 'Criteria'])['FTT Amt'].agg(['sum', 'count']).sort_values(by='sum', ascending=False)

                           sum  count
Conviction Criteria
H-SC       XY24      1390669.0      6
           AR         995759.0      5
X-LC       X40        959446.0      7
M-SC       XY24       953791.0      6
H-SC       XR         908984.0      7
X-SC       XY24       870129.0      4
X-MC       X40        752261.0      7
           X40N       576545.0      4
X-SC       X40N       515388.0      4
M-SC       OX40N      427337.0      5
X-LC       XY24       405547.0      2
H-SC       OX40N      401877.0      4
           SR         318091.0      2
X-MC       XY25       287181.0      2
           XY24       285041.0      2
H-MC       XY24       249859.0      1
X-LC       X40N       237412.0      2
X-SC       X40        227622.0      2
M-SC       XR         194958.0      2
H-MC       AR         186190.0      2
X-LC       XY25       166601.0      2
M-LC       XR         158548.0      1
L-SC       OX40N      114134.0      1
           XR         107252.0      1
H-LC       AR          85284.0      1
M-SC       AR          80320.0      1
M-MC       XY25        69798.0      1
L-MC       XR          59145.0      1
M-MC       AR          54525.0      1

In [32]:
# notebook execution time

end_time = time.time()
execution_time = round(end_time - start_time, 0)
print(f"Notebook execution time: {execution_time} seconds")

Notebook execution time: 26.0 seconds