<a href="https://colab.research.google.com/github/ankit-rathi/Quantvesting_v2/blob/main/myStocks_Portfolio_Analysis.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
'''
!pip install pandas==2.2.2 -qq
!pip install pyxirr -qq
!pip install ta -qq
!pip install yfinance==0.2.59 -qq
'''

'\n!pip install pandas==2.2.2 -qq\n!pip install pyxirr -qq\n!pip install ta -qq\n!pip install yfinance==0.2.59 -qq\n'

In [2]:
# import libraries

import numpy as np
import pandas as pd
import datetime
import warnings
warnings.filterwarnings('ignore')
import yfinance as yfin
import ta
import matplotlib.pyplot as plt
import requests

In [3]:
# notebook start time
import time
import datetime
import pytz

start_time = time.time()

# function to print date timestamp
def print_date_time():
  tz_NY = pytz.timezone('Asia/Kolkata')
  datetime_NY = datetime.datetime.now(tz_NY)
  print("Run date time (IST):", datetime_NY.strftime("%Y-%m-%d %H:%M:%S"))

In [4]:
# function to get booked and reserved amount
def get_amt():
  # fetch the JSON data from the URL
  url = "https://raw.githubusercontent.com/ankit-rathi/Tradevesting_v1/main/data/myPortfolioAmts.json"
  response = requests.get(url)
  pf_amts = response.json()  # parse the JSON data

  # extract values from the JSON
  py_booked_amt_dm = pf_amts["py_booked_amt_dm"]
  py_booked_amt_sv = pf_amts["py_booked_amt_sv"]
  cy_booked_amt_dm = pf_amts["cy_booked_amt_dm"]
  cy_booked_amt_sv = pf_amts["cy_booked_amt_sv"]
  reserve_amt_dm = pf_amts["reserve_amt_dm"]
  reserve_amt_sv = pf_amts["reserve_amt_sv"]

  # perform calculations
  py_booked_amt = py_booked_amt_dm + py_booked_amt_sv
  cy_booked_amt = cy_booked_amt_dm + cy_booked_amt_sv
  reserve_amt = reserve_amt_dm + reserve_amt_sv
  total_booked_amt = py_booked_amt + cy_booked_amt

  return total_booked_amt, reserve_amt, cy_booked_amt, py_booked_amt

gen_output = 0

In [5]:
# function to format the amount
def format_amt(number):
    abs_number = abs(number)

    if abs_number >= 1_00_00_000:  # Crores
        formatted_amt = f"{number / 1_00_00_000:.2f} C"
    elif abs_number >= 1_00_000:  # Lakhs
        formatted_amt = f"{number / 1_00_000:.2f} L"
    elif abs_number >= 1_000:  # Thousands
        formatted_amt = f"{number / 1_000:.2f} K"
    else:
        formatted_amt = f"{number:.2f}"

    return formatted_amt

# function to set start and end date
def get_start_end_date():
  start_date = (datetime.date.today() + datetime.timedelta(days=-365)).strftime('%Y-%m-%d')
  end_date = (datetime.date.today() + datetime.timedelta(days=1)).strftime('%Y-%m-%d')
  return start_date, end_date

# function to fetch my portfolio csv
def get_mypfs_df():
  mypfs_df = pd.read_csv('https://raw.githubusercontent.com/ankit-rathi/Tradevesting_v1/main/data/myPortfolioStocks.csv')
  return mypfs_df

# function to fetch my prospects csv
def get_mypps_df():
  mypps_df = pd.read_csv('https://raw.githubusercontent.com/ankit-rathi/Tradevesting_v1/main/data/myProspectsScrips.csv')
  return mypps_df

# function to fetch screener data
def get_myscreen_df():
  myscreen_df = pd.read_csv('https://raw.githubusercontent.com/ankit-rathi/Tradevesting_v1/main/data/myScreenerDB.csv')
  return myscreen_df

# function to fetch momentum data
def get_myinvmt_df():
  myinvmt_df = pd.read_csv('https://raw.githubusercontent.com/ankit-rathi/Tradevesting_v1/main/data/myInvestments.csv')
  return myinvmt_df

# function to get the stock ids
def get_stock_ids(df_pf):
  stock_n100 = df_pf['Symbol'].unique()

  exclude = ['CADILAHC','MMTC', 'MASFIN']

  stock_ids = df_pf[~df_pf['Symbol'].isin(exclude) ]['Symbol'].unique()

  #mypf = mypf[mypf.Forecast.notnull()]
  #stock_ids = mypf['Symbol'].unique()

  #stock_ids.sort()
  return stock_ids

# get features from screener data
def get_screener_features():
  myscreen_df = get_myscreen_df()
  cols = ['Symbol', 'EPS', 'MedPE', 'ROCE%', 'ROE%', 'CapType']
  return myscreen_df[cols]

# get relative strength
def get_relative_strength(stock_list):

    # Dictionary to store stock tickers and their corresponding percentage price change
    stock_changes = {}

    # Loop through each stock and fetch its price data
    for stock in stock_list:
        try:
            # Download the stock data for the given date range
            stock_data = yfin.Ticker(stock + '.NS').history(period='1mo', interval='1d')[map(str.title, ['open', 'close', 'low', 'high', 'volume'])]

            # Calculate the percentage change for the stock
            if len(stock_data) > 0:
                start_price = stock_data['Close'].iloc[0]
                end_price = stock_data['Close'].iloc[-1]
                percent_change = round(((end_price - start_price) / start_price) * 100, 2)
                stock_changes[stock] = percent_change
            else:
                stock_changes[stock] = np.nan  # If no data is available, set to NaN

        except Exception as e:
            print(f"Error fetching data for {stock}: {e}")
            stock_changes[stock] = np.nan

    # Create a DataFrame with stock tickers and their percentage changes
    df = pd.DataFrame(list(stock_changes.items()), columns=['Symbol', 'Percent_Change'])

    # Drop any stocks with missing data (NaN values)
    df = df.dropna()

    # Calculate the percentile rank based on percentage change
    df['RSP'] = round(df['Percent_Change'].rank(pct=True) * 100, 2)
    cols = ['Symbol', 'RSP']
    df = df[cols]
    # Sort by percentile rank (optional)
    df = df.sort_values(by='RSP', ascending=False).reset_index(drop=True)

    return df

In [6]:
# function to get stock technicals
def stock_prec_dev(stock_symbol):
    #stock_symbol = 'ULTRACEMCO.NS'
    short_window = 20
    mid_window = 50
    long_window = 200
    moving_avg = 'SMA'

    start = datetime.datetime(*map(int, start_date.split('-')))
    end = datetime.datetime(*map(int, end_date.split('-')))

    stock_df = yfin.Ticker(stock_symbol + '.NS').history(period='max', interval='1d')[map(str.title, ['open', 'close', 'low', 'high', 'volume'])]

    stock_df['Max'] = round(max(stock_df['Close']),2)
    stock_df = stock_df[(stock_df.index <= end_date) & (stock_df.index >= start_date)]
    stock_df['200_SMA'] = round(stock_df['Close'].rolling(window = 200, min_periods = 1).mean(),0)
    stock_df['Dev%_200'] = round((stock_df['Close'] - stock_df['200_SMA'])*100/stock_df['200_SMA'],2)
    stock_df.dropna(axis = 0, inplace = True) # remove any null rows

    stock_df['20_SMA'] = stock_df['Close'].rolling(window=20).mean()
    stock_df['50_SMA'] = stock_df['Close'].rolling(window=50).mean()
    stock_df['Symbol'] = stock_symbol

    stock_df['Close'] = round(stock_df['Close'],2)
    stock_df['Min'] = round(min(stock_df['Close']),2)
    stock_df['RSI_14'] = ta.momentum.RSIIndicator(close=stock_df['Close'], window=14).rsi()
    stock_df['RSI_14'] = round(stock_df['RSI_14'],0)
    stock_df['Prev_Close'] = stock_df['Close'].shift(1)
    stock_df.drop(['Open', 'Low', 'High', 'Volume'], axis=1, inplace=True)
    stock_df = stock_df.tail(1)

    max_SMA = max(stock_df['20_SMA'].item(), stock_df['50_SMA'].item(), stock_df['200_SMA'].item())
    min_SMA = min(stock_df['20_SMA'].item(), stock_df['50_SMA'].item(), stock_df['200_SMA'].item())
    ABS_Spread = max_SMA - min_SMA
    stock_df['Spread%'] = round((ABS_Spread / stock_df['200_SMA'].item()) * 100,2)

    return stock_df

# function to compute stock attributes
def get_common_features(stock_ids, df_mypf):

  df_prec_dev = pd.DataFrame()
  df_tmp = get_screener_features()
  df_rs = get_relative_strength(stock_ids)

  for stock_id in stock_ids:
      tmp = stock_prec_dev(stock_id)
      tmp = tmp.reset_index()
      df_prec_dev = pd.concat([df_prec_dev, tmp], ignore_index = True)
  df_prec_dev = pd.merge(df_prec_dev, df_mypf, on= 'Symbol')
  df_prec_dev = pd.merge(df_prec_dev, df_tmp, on= 'Symbol', how='left')
  df_prec_dev = pd.merge(df_prec_dev, df_rs, on= 'Symbol', how='left')
  #print(df_prec_dev.columns)
  df_prec_dev['Curr_PE'] = round(df_prec_dev['Close']/df_prec_dev['EPS'],1)
  df_prec_dev['Dev%_PE'] = round((df_prec_dev['Curr_PE'] - df_prec_dev['MedPE'])*100/df_prec_dev['MedPE'],2)
  df_prec_dev['Conviction'] = df_prec_dev['Conviction'] + '-' + df_prec_dev['CapType']
  return df_prec_dev

# function to arrange stock features
def arrange_features(df_stocks, common_cols, diff_cols):
  df_stocks_common = df_stocks[common_cols].drop_duplicates()
  df_stocks_diff = df_stocks[diff_cols]
  df_stocks_diff['Investment'] = df_stocks_diff['AvgCost'] * df_stocks_diff['Shares']
  df_stocks_diff = df_stocks_diff.groupby(['Symbol'])[['Shares', 'Investment']].aggregate(['sum']).reset_index()
  df_stocks_diff.columns = ['Symbol', 'Shares', 'Investment']
  df_stocks_diff['AvgCost'] = round(df_stocks_diff['Investment']/df_stocks_diff['Shares'],2)
  df_stocks = pd.merge(df_stocks_diff, df_stocks_common, on='Symbol')
  return df_stocks

# plot fact distribution across dimension
def plot_pie_chart(df, dimension, fact):
  # grouping the data by category and calculating the sum of fact for each type
  grouped_data = df.groupby(dimension)[fact].sum()

  # sorting the grouped data in descending order
  grouped_data = grouped_data.sort_values(ascending=False)

  # creating a pie chart
  grouped_data.plot.pie(autopct='%1.1f%%', startangle=90, figsize=(6, 6))

  # adding a title and displaying the plot
  plt.title(f'{dimension} {fact} Distribution')
  plt.ylabel('')  # To hide the y-label
  plt.show()

In [7]:
# function to get portfolio features

def get_portfolio_features(df_common_features):

  print_date_time()
  print('-------------------')

  #df_common_features["Target"] = df_common_features["Target"].fillna(df_common_features["Max"])
  df_common_features['NTT'] = np.where(df_common_features['Strategy']== 'NTT', df_common_features["Target"], df_common_features['Max'])
  df_common_features['LTT'] = np.where(df_common_features['Strategy']== 'BTT', df_common_features["Target"], df_common_features['Max'])
  df_common_features['BOL'] = df_common_features['Min']

  tmp_df = df_common_features[df_common_features['Symbol'].isin(mypf_df[mypf_df['InPortfolio'] != 'NA'].Symbol.values)]
  print('qualified stocks: '+str(len(tmp_df['Symbol'].unique())))
  tmp_df1 = tmp_df[tmp_df['LatestQtr'] == 1]
  print('with latest results: '+str(len(tmp_df1['Symbol'].unique())))
  tmp_df1 = tmp_df1[tmp_df1['StarStock'] == 1]
  print('still star stocks: '+str(len(tmp_df1['Symbol'].unique())))
  tmp_df['Investment'] = tmp_df['AvgCost'] * tmp_df['Shares']
  tmp_df['Current'] = round(tmp_df['Close'] * tmp_df['Shares'],0)
  tmp_df['Previous'] = tmp_df['Prev_Close'] * tmp_df['Shares']
  tmp_df['EstimatedST'] = tmp_df['NTT'] * tmp_df['Shares']
  tmp_df['EstimatedLT'] = tmp_df['LTT'] * tmp_df['Shares']
  tmp_df['Current P/L'] = round((tmp_df['Current'] - tmp_df['Investment']),0)
  tmp_df['Today P/L%'] = round((tmp_df['Current'] - tmp_df['Previous'])*100/tmp_df['Previous'],2)
  tmp_df['Current P/L%'] = round((tmp_df['Current'] - tmp_df['Investment'])*100/tmp_df['Investment'],2)
  tmp_df['EstimatedST P/L%'] = round((tmp_df['EstimatedST'] - tmp_df['Investment'])*100/tmp_df['Investment'],2)
  tmp_df['EstimatedLT P/L%'] = round((tmp_df['EstimatedLT'] - tmp_df['Investment'])*100/tmp_df['Investment'],2)
  tmp_df['NTT%'] = round((tmp_df['NTT'] - tmp_df['Close'])*100/tmp_df['Close'],2)
  tmp_df['LTT%'] = round((tmp_df['LTT'] - tmp_df['Close'])*100/tmp_df['Close'],2)
  tmp_df['Gained%'] = round((tmp_df['Close'] - tmp_df['BOL'])*100/tmp_df['BOL'],2)
  investment = round(sum(tmp_df['AvgCost']*tmp_df['Shares']),0)
  current = round(sum(tmp_df['Close']*tmp_df['Shares']),0)
  tmp_df['InitAlloc%'] = round(tmp_df['Investment']*100/investment,2)
  tmp_df['CurrAlloc%'] = round(tmp_df['Current']*100/current,2)
  tmp_df['FTT'] = tmp_df['LTT']
  tmp_df.loc[tmp_df['Strategy'] == 'NTT', 'FTT'] = tmp_df['NTT']
  tmp_df['FTT%'] = tmp_df['LTT%']
  tmp_df.loc[tmp_df['Strategy'] == 'NTT', 'FTT%'] = tmp_df['NTT%']
  tmp_df['FTT Amt'] = round(tmp_df['FTT%'] * tmp_df['Current']/100,0)
  tmp_df['OTT%'] = round((tmp_df['FTT'] - tmp_df['AvgCost'])*100/tmp_df['AvgCost'],2)
  tmp_df['RRR Ind'] = round(tmp_df['Current P/L']/tmp_df['FTT Amt'],2)
  tmp_df['Risk Ind'] = round(tmp_df['Current P/L%']*tmp_df['CurrAlloc%'],0)

  return tmp_df

# function to print portfolio features
def print_portfolio_stats(df_portfolio_features, myinvmt_df):
  from pyxirr import xirr

  total_booked_amt, reserve_amt, cy_booked_amt, py_booked_amt = get_amt()

  dates = myinvmt_df['Date'].values
  dates = np.append(dates, datetime.date.today().strftime('%d-%b-%y'))
  investment = myinvmt_df['Investment'].values
  dates= pd.to_datetime(dates)

  current = round(sum(df_portfolio_features['Close']*df_portfolio_features['Shares']),0) + reserve_amt
  investment_xirr = np.append(investment, current)
  cagr = round(xirr(pd.DataFrame({"dates": dates, "amounts": investment_xirr}))*100,2)

  investment = -sum(investment)
  invested = round(sum(df_portfolio_features['AvgCost']*df_portfolio_features['Shares']),0) + reserve_amt
  previous = round(sum(df_portfolio_features['Prev_Close']*df_portfolio_features['Shares']),0) + reserve_amt
  cy_invested = investment + py_booked_amt

  today_pnl_amount = current-previous
  today_pnl_percentage = round((current-previous)*100/previous,2)

  curr_pnl_amount = current-invested
  curr_pnl_percentage = round((curr_pnl_amount)*100/(cy_invested),2)

  cy_pnl_amount = cy_booked_amt + curr_pnl_amount
  cy_pnl_percentage = round((cy_pnl_amount)*100/cy_invested,2)

  overall_pnl_amount = total_booked_amt + curr_pnl_amount
  overall_pnl_percentage = round((overall_pnl_amount)*100/investment,2)

  estimate_st = round(sum(df_portfolio_features['FTT']*df_portfolio_features['Shares']),0)  + reserve_amt
  est_st_pnl_amount = estimate_st-current
  est_st_pnl_percentage = round((est_st_pnl_amount)*100/current,2)

  estimate_lt = round(sum(df_portfolio_features['LTT']*df_portfolio_features['Shares']),0)  + reserve_amt
  est_lt_pnl_amount = estimate_lt-current
  est_lt_pnl_percentage = round((est_lt_pnl_amount)*100/current,2)

  total_profit = round(sum(df_portfolio_features[df_portfolio_features['Current P/L%'] > 0]['Current']) - sum(df_portfolio_features[df_portfolio_features['Current P/L%'] > 0]['Investment']),0)
  total_loss = round(sum(df_portfolio_features[df_portfolio_features['Current P/L%'] < 0]['Current']) - sum(df_portfolio_features[df_portfolio_features['Current P/L%'] < 0]['Investment']),0)

  cy_booked_percentage = round((cy_booked_amt)*100/current,2)
  py_booked_percentage = round((py_booked_amt)*100/investment,2)
  total_booked_percentage = round((total_booked_amt)*100/investment,2)

  print('-------------------')
  print('Initial Investment: ', format_amt(investment))
  print('CY Investment: ', format_amt(cy_invested))
  print('Reserve: ', format_amt(reserve_amt))
  print('Current: ',  format_amt(current))
  print('-------------------')
  print('Today PnL: '+ '{} ({}%)'.format(format_amt(today_pnl_amount), today_pnl_percentage))
  print('Current PnL: '+ '{} ({}%)'.format(format_amt(curr_pnl_amount), curr_pnl_percentage))
  print('CY Booked + Current PnL: '+ '{} ({}%)'.format(format_amt(cy_pnl_amount), cy_pnl_percentage))
  print('-------------------')
  print('Total profit: ', format_amt(total_profit))
  print('Total loss: ', format_amt(total_loss))
  print('-------------------')
  print('Total Booked + Current PnL: '+ '{} ({}%)'.format(format_amt(overall_pnl_amount), overall_pnl_percentage))
  print('Total Booked PnL: '+ '{} ({}%)'.format(format_amt(total_booked_amt), total_booked_percentage))
  print('Curr Year Booked PnL: '+ '{} ({}%)'.format(format_amt(cy_booked_amt), cy_booked_percentage))
  print('Prev Year Booked PnL: '+ '{} ({}%)'.format(format_amt(py_booked_amt), py_booked_percentage))
  print('===================')
  print('Est FTT: ',  format_amt(estimate_st))
  print('Est FTT PnL: '+ '{} ({}%)'.format(format_amt(est_st_pnl_amount), est_st_pnl_percentage))

  print('===================')
  print('Deployed: ', format_amt(investment))

  print('Current: ', format_amt(current))

  print('CAGR/XIRR %: '+'{}%'.format(cagr))

In [8]:
# get start and end date
start_date, end_date = get_start_end_date()

# get portfolio and prospects data
mypfs_df = get_mypfs_df()
mypps_df = get_mypps_df()
myinvmt_df = get_myinvmt_df()

# merge above datasets
mypf_df = pd.merge(mypfs_df, mypps_df, on="Symbol")

# seggregate dm and sv portfolio
dm_pf = mypf_df[mypf_df['InPortfolio'] == 'DM']
sv_pf = mypf_df[mypf_df['InPortfolio'] == 'SV']

# build portfolio stock dataframe
dm_stocks = get_stock_ids(dm_pf)
sv_stocks = get_stock_ids(sv_pf)
df_stocks = pd.concat([dm_pf,sv_pf], ignore_index = True)

# arrange common and diff stock features
common_cols = ['Symbol', 'Target', 'Criteria', 'Strategy', 'CumlRnk', 'LatestQtr', 'StarStock', 'Conviction', 'Category', 'InFolio', 'XIRR', 'MBQ']
diff_cols = ['Symbol', 'AvgCost', 'Shares']
df_stocks = arrange_features(df_stocks, common_cols, diff_cols)

# get common features
stock_ids = df_stocks['Symbol'].values
df_common_features = get_common_features(stock_ids, df_stocks)

df_common_features.reset_index(drop=True, inplace=True)
df_common_features.drop(['Date'], axis=1, inplace=True)
# get and print portfolio features
df_portfolio_features = get_portfolio_features(df_common_features)

print_portfolio_stats(df_portfolio_features, myinvmt_df)

df = df_portfolio_features
#plot_pie_chart(df, 'CapType', 'Current')
list_ox40n = list(df[df['MBQ'].str.contains('OX40N', na=False)]['Symbol'].values)

Run date time (IST): 2026-03-17 14:05:18
-------------------
qualified stocks: 86
with latest results: 26
still star stocks: 16
-------------------
Initial Investment:  1.36 C
CY Investment:  1.62 C
Reserve:  1.61 K
Current:  1.32 C
-------------------
Today PnL: 25.48 K (0.19%)
Current PnL: -45.00 L (-27.69%)
CY Booked + Current PnL: -29.11 L (-17.91%)
-------------------
Total profit:  74.08 K
Total loss:  -45.74 L
-------------------
Total Booked + Current PnL: -2.13 L (-1.57%)
Total Booked PnL: 42.87 L (31.64%)
Curr Year Booked PnL: 15.89 L (12.03%)
Prev Year Booked PnL: 26.98 L (19.91%)
===================
Est FTT:  2.48 C
Est FTT PnL: 1.16 C (87.61%)
===================
Deployed:  1.36 C
Current:  1.32 C
CAGR/XIRR %: -1.25%

In [9]:
# top 5 near their targets
cols = ['Symbol', 'Today P/L%', 'Current P/L%', 'FTT%', 'OTT%', 'FTT Amt', 'Current P/L', 'Current', 'FTT', 'Dev%_PE', 'RSI_14','Conviction', 'Spread%',  'CumlRnk', 'RRR Ind', 'CurrAlloc%', 'Gained%', 'Criteria', 'Strategy', 'Category']
df_tmp = df_portfolio_features[~df_portfolio_features['Symbol'].isin(['ENRIN','BLUSPRING','DIGITIDE'])]
df_tmp = df_tmp.sort_values(by = 'FTT Amt', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
50,MASFIN,0.27,-9.61,34.50,21.57,30553.0,-9420.0,88560.0,397.04,-21.86,35.0,H-SC,2.28,167.0,-0.31,0.67,22.81,XR,ATH,FINANCE
77,TTKPRESTIG,0.70,-35.60,55.41,0.09,35963.0,-35873.0,64904.0,770.00,50.69,43.0,M-SC,16.34,250.0,-1.00,0.49,9.66,OX40N,NTT,DURABLES
37,ICICIGI,-0.40,-2.37,22.24,19.34,43450.0,-4740.0,195369.0,2252.93,-17.87,40.0,X-MC,2.15,66.0,-0.11,1.48,8.00,X40,ATH,INSURANCE
2,ABBOTINDIA,-0.26,-10.77,32.31,18.07,51567.0,-19255.0,159600.0,35195.00,-24.04,45.0,X-MC,10.83,58.0,-0.37,1.21,1.18,X40,ATH,PHARMA
67,SONACOMS,2.16,-13.55,60.88,39.09,53243.0,-13703.0,87456.0,804.02,-31.54,45.0,M-MC,8.90,193.0,-0.26,0.66,23.72,AR,ATH,AUTO

In [10]:
# top 5 today
df_tmp = df_portfolio_features.sort_values(by = 'Today P/L%', ascending=False)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
15,BSOFT,4.99,-33.65,127.24,50.79,118753.0,-47323.0,93330.0,831.70,-14.96,42.0,H-SC,7.45,172.0,-0.40,0.71,8.67,XR,ATH,IT
13,BERGEPAINT,3.14,-23.12,62.99,25.32,124827.0,-59579.0,198170.0,680.00,-27.22,31.0,X-MC,16.82,68.0,-0.48,1.50,3.14,XY24,NTT,PAINTS
69,SURYODAY,2.94,-26.16,66.62,23.03,88094.0,-46838.0,132233.0,216.00,44.74,50.0,H-SC,7.44,166.0,-0.53,1.00,31.20,XR,NTT,BANKS
67,SONACOMS,2.16,-13.55,60.88,39.09,53243.0,-13703.0,87456.0,804.02,-31.54,45.0,M-MC,8.90,193.0,-0.26,0.66,23.72,AR,ATH,AUTO
38,ICICIPRULI,2.12,-1.33,32.49,30.73,63153.0,-2627.0,194378.0,790.00,-27.79,34.0,X-MC,2.73,78.0,-0.04,1.47,11.20,X40,ATH,INSURANCE

In [11]:
# bottom 5 today
df_tmp = df_portfolio_features.sort_values(by = 'Today P/L%', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
55,RAJESHEXPO,-3.62,-80.44,411.55,0.07,110435.0,-110343.0,26834.0,518.00,883.59,19.0,L-SC,25.96,268.0,-1.00,0.20,0.00,OX40N,NTT,JEWELLERY
72,TATAELXSI,-3.13,-41.33,125.04,32.03,96712.0,-54490.0,77345.0,9161.00,-26.58,22.0,H-SC,18.67,158.0,-0.56,0.59,0.00,OX40N,NTT,IT
61,ROUTE,-2.37,-66.19,397.35,68.16,178768.0,-88076.0,44990.0,2215.45,-72.65,24.0,H-SC,35.52,141.0,-0.49,0.34,0.00,SR,ATH,IT
40,INDIAMART,-2.09,-11.31,133.07,106.72,145568.0,-13944.0,109392.0,4810.62,-59.96,37.0,H-SC,10.04,140.0,-0.10,0.83,9.43,AR,ATH,MISC
11,BANDHANBNK,-2.07,-23.43,151.29,92.42,322703.0,-65258.0,213301.0,400.00,83.19,39.0,H-SC,8.99,174.0,-0.20,1.61,17.50,XY24,NTT,BANKS

In [12]:
# top 5 to exit based on CumlRnk
df_tmp = df_portfolio_features[~df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])]
df_tmp = df_tmp[(df_tmp['Current P/L%'] > -1) & (df_tmp['Current P/L%'] < 1)].sort_values(by = 'CumlRnk', ascending=False)
df_tmp[cols].head()

Empty DataFrame
Columns: [Symbol, Today P/L%, Current P/L%, FTT%, OTT%, FTT Amt, Current P/L, Current, FTT, Dev%_PE, RSI_14, Conviction, Spread%, CumlRnk, RRR Ind, CurrAlloc%, Gained%, Criteria, Strategy, Category]
Index: []

In [13]:
# OX40N stocks to exit
df_tmp = df_portfolio_features[(df_portfolio_features['Symbol'].isin(list_ox40n))].sort_values(by = 'Current P/L%', ascending=False)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
26,FINCABLES,0.82,7.90,92.69,107.91,147660.0,11661.0,159305.0,1641.55,-3.09,49.0,M-SC,7.90,220.0,0.08,1.21,19.85,OX40N,ATH,CABLES
77,TTKPRESTIG,0.70,-35.60,55.41,0.09,35963.0,-35873.0,64904.0,770.00,50.69,43.0,M-SC,16.34,250.0,-1.00,0.49,9.66,OX40N,NTT,DURABLES
66,SIS,-1.15,-37.06,92.67,21.26,64761.0,-41149.0,69883.0,528.00,1631.61,28.0,H-SC,12.56,168.0,-0.64,0.53,0.00,OX40N,NTT,MISC
70,SYMPHONY,0.61,-39.66,65.66,-0.03,67810.0,-67867.0,103274.0,1306.00,-51.59,40.0,M-SC,14.68,205.0,-1.00,0.78,4.44,OX40N,NTT,DURABLES
18,CERA,0.22,-39.97,106.39,23.89,112335.0,-70315.0,105588.0,9475.00,-42.00,34.0,H-SC,17.94,153.0,-0.63,0.80,1.47,OX40N,NTT,CERAMICS

In [14]:
# top 5 to book for rotation
df_tmp = df_portfolio_features[(df_portfolio_features['Current P/L%'] > 20) ].sort_values(by = 'CumlRnk', ascending=False)
df_tmp[cols].head()

Empty DataFrame
Columns: [Symbol, Today P/L%, Current P/L%, FTT%, OTT%, FTT Amt, Current P/L, Current, FTT, Dev%_PE, RSI_14, Conviction, Spread%, CumlRnk, RRR Ind, CurrAlloc%, Gained%, Criteria, Strategy, Category]
Index: []

In [15]:
# top 5 to monitor for exit
df_tmp = df_portfolio_features[~df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])]
df_tmp = df_tmp[(df_tmp['Current P/L%'] > 0) ].sort_values(by = 'Dev%_PE', ascending=False)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
26,FINCABLES,0.82,7.9,92.69,107.91,147660.0,11661.0,159305.0,1641.55,-3.09,49.0,M-SC,7.9,220.0,0.08,1.21,19.85,OX40N,ATH,CABLES
1,ABB,1.07,15.3,26.25,45.57,79185.0,40037.0,301656.0,7934.00,-25.90,62.0,H-MC,11.8,125.0,0.51,2.28,33.96,AR,NTT,ELECTRICAL

In [16]:
# top 5 to book for rotation from weak conviction
df_tmp = df_portfolio_features[~df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])]
df_tmp = df_tmp[~df_tmp['Criteria'].isin(['XY25','XY24','X40', 'X40N'])].sort_values(by = 'RRR Ind', ascending=False)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
1,ABB,1.07,15.30,26.25,45.57,79185.0,40037.0,301656.0,7934.00,-25.90,62.0,H-MC,11.80,125.0,0.51,2.28,33.96,AR,NTT,ELECTRICAL
26,FINCABLES,0.82,7.90,92.69,107.91,147660.0,11661.0,159305.0,1641.55,-3.09,49.0,M-SC,7.90,220.0,0.08,1.21,19.85,OX40N,ATH,CABLES
40,INDIAMART,-2.09,-11.31,133.07,106.72,145568.0,-13944.0,109392.0,4810.62,-59.96,37.0,H-SC,10.04,140.0,-0.10,0.83,9.43,AR,ATH,MISC
85,ZYDUSLIFE,0.79,-5.74,43.88,35.63,86686.0,-12022.0,197552.0,1286.17,-18.02,45.0,H-MC,5.14,120.0,-0.14,1.50,9.98,AR,ATH,PHARMA
84,WIPRO,-1.86,-21.46,119.33,72.27,158812.0,-36362.0,133086.0,420.00,-29.24,25.0,M-LC,15.99,98.0,-0.23,1.01,0.00,XR,NTT,IT

In [17]:
# top 5 to accumulate based on lowest RSI_14
df_tmp = df_portfolio_features[df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])].sort_values(by = 'RSI_14', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
58,RELAXO,-1.99,-63.66,319.10,52.31,168335.0,-92407.0,52753.0,1176.00,-61.28,14.0,X-SC,21.58,92.0,-0.55,0.40,0.00,X40N,NTT,FOOTWEAR
12,BATAINDIA,-0.29,-56.40,210.08,35.20,117863.0,-72566.0,56104.0,2096.00,-26.50,16.0,X-SC,28.03,91.0,-0.62,0.42,0.00,X40,NTT,FOOTWEAR
53,PGHH,-1.23,-24.80,75.54,32.01,121299.0,-52944.0,160576.0,17616.87,-49.14,16.0,X-MC,12.85,57.0,-0.44,1.22,0.00,X40,ATH,FMCG
3,ACC,0.31,-38.35,183.56,74.81,303425.0,-102828.0,165300.0,3906.00,-56.11,18.0,X-SC,14.69,85.0,-0.34,1.25,0.31,XY24,BTT,CEMENT
73,TCS,-0.33,-29.51,79.55,26.57,259792.0,-136696.0,326577.0,4311.59,-40.35,19.0,X-LC,15.55,2.0,-0.53,2.47,0.00,X40,ATH,IT

In [18]:
# top 5 to accumulate based on Spread and CumlRnk
df_tmp = df_portfolio_features[df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])]
df_tmp = df_tmp[(df_tmp['CumlRnk'] < 100)].sort_values(by = 'Spread%', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
78,UNITDSPR,-0.54,-3.75,25.47,20.77,57402.0,-8772.0,225372.0,1644.00,-14.64,40.0,X-MC,0.94,64.0,-0.15,1.71,2.71,X40N,NTT,BREWERIES
37,ICICIGI,-0.40,-2.37,22.24,19.34,43450.0,-4740.0,195369.0,2252.93,-17.87,40.0,X-MC,2.15,66.0,-0.11,1.48,8.00,X40,ATH,INSURANCE
21,DABUR,-1.08,-11.26,61.93,43.70,136334.0,-27926.0,220142.0,735.00,-19.47,31.0,X-MC,2.67,70.0,-0.20,1.67,2.10,XY24,BTT,FMCG
38,ICICIPRULI,2.12,-1.33,32.49,30.73,63153.0,-2627.0,194378.0,790.00,-27.79,34.0,X-MC,2.73,78.0,-0.04,1.47,11.20,X40,ATH,INSURANCE
75,TMPV,1.73,-27.19,87.59,36.58,226927.0,-96762.0,259079.0,600.00,-84.72,33.0,X-LC,2.91,4.0,-0.43,1.96,1.83,XY24,NTT,AUTO

In [19]:
# top 5 to accumulate based on lowest Gained%
df_tmp = df_portfolio_features[df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])].sort_values(by = 'Gained%', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
12,BATAINDIA,-0.29,-56.40,210.08,35.20,117863.0,-72566.0,56104.0,2096.00,-26.50,16.0,X-SC,28.03,91.0,-0.62,0.42,0.0,X40,NTT,FOOTWEAR
20,COLPAL,-0.06,-26.34,92.11,41.51,178693.0,-69365.0,194000.0,3726.84,-10.78,29.0,X-MC,4.20,62.0,-0.39,1.47,0.0,XY25,ATH,FMCG
43,INFY,-1.30,-16.03,59.87,34.24,157300.0,-50152.0,262736.0,1972.00,-33.96,22.0,X-LC,13.80,3.0,-0.32,1.99,0.0,X40,NTT,IT
33,HCLTECH,-0.41,-14.13,44.21,23.83,91843.0,-34182.0,207742.0,1908.19,-9.84,26.0,X-LC,10.47,8.0,-0.37,1.57,0.0,X40,ATH,IT
58,RELAXO,-1.99,-63.66,319.10,52.31,168335.0,-92407.0,52753.0,1176.00,-61.28,14.0,X-SC,21.58,92.0,-0.55,0.40,0.0,X40N,NTT,FOOTWEAR

In [20]:
# top 5 to accumulate based on lowest CurrAlloc%
df_tmp = df_portfolio_features[df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])].sort_values(by = 'CurrAlloc%', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
58,RELAXO,-1.99,-63.66,319.10,52.31,168335.0,-92407.0,52753.0,1176.00,-61.28,14.0,X-SC,21.58,92.0,-0.55,0.40,0.00,X40N,NTT,FOOTWEAR
12,BATAINDIA,-0.29,-56.40,210.08,35.20,117863.0,-72566.0,56104.0,2096.00,-26.50,16.0,X-SC,28.03,91.0,-0.62,0.42,0.00,X40,NTT,FOOTWEAR
54,QUESS,0.03,-28.12,141.94,73.90,108953.0,-30033.0,76760.0,424.00,-61.43,30.0,X-SC,19.47,80.0,-0.28,0.58,0.03,XY24,NTT,MISC
36,HONAUT,0.05,-23.98,99.04,51.31,145193.0,-46238.0,146600.0,58357.33,-36.81,32.0,X-SC,14.30,90.0,-0.32,1.11,0.05,X40N,ATH,ELECTRICAL
51,MEDANTA,-0.45,-11.37,43.42,27.12,67931.0,-20066.0,156451.0,1486.00,-14.08,31.0,X-SC,9.55,87.0,-0.30,1.18,0.59,XY24,NTT,HEALTHCARE

In [21]:
# top 5 to accumulate based on CumlRnk
df_tmp = df_portfolio_features.sort_values(by = 'CumlRnk', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
45,ITC,-0.68,-19.36,47.64,19.06,130681.0,-65856.0,274310.0,452.00,-55.92,39.0,X-LC,17.28,1.0,-0.50,2.08,1.56,X40,NTT,FMCG
73,TCS,-0.33,-29.51,79.55,26.57,259792.0,-136696.0,326577.0,4311.59,-40.35,19.0,X-LC,15.55,2.0,-0.53,2.47,0.00,X40,ATH,IT
43,INFY,-1.30,-16.03,59.87,34.24,157300.0,-50152.0,262736.0,1972.00,-33.96,22.0,X-LC,13.80,3.0,-0.32,1.99,0.00,X40,NTT,IT
75,TMPV,1.73,-27.19,87.59,36.58,226927.0,-96762.0,259079.0,600.00,-84.72,33.0,X-LC,2.91,4.0,-0.43,1.96,1.83,XY24,NTT,AUTO
33,HCLTECH,-0.41,-14.13,44.21,23.83,91843.0,-34182.0,207742.0,1908.19,-9.84,26.0,X-LC,10.47,8.0,-0.37,1.57,0.00,X40,ATH,IT

In [22]:
# top 5 for average up
df_tmp = df_portfolio_features[(df_portfolio_features['Dev%_200'] > 5)].sort_values(by = 'CurrAlloc%', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
1,ABB,1.07,15.3,26.25,45.57,79185.0,40037.0,301656.0,7934.0,-25.9,62.0,H-MC,11.8,125.0,0.51,2.28,33.96,AR,NTT,ELECTRICAL

In [23]:
# top 5 RSP
df_tmp = df_portfolio_features.sort_values(by = 'RSP', ascending=False)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
1,ABB,1.07,15.30,26.25,45.57,79185.0,40037.0,301656.0,7934.00,-25.90,62.0,H-MC,11.80,125.0,0.51,2.28,33.96,AR,NTT,ELECTRICAL
26,FINCABLES,0.82,7.90,92.69,107.91,147660.0,11661.0,159305.0,1641.55,-3.09,49.0,M-SC,7.90,220.0,0.08,1.21,19.85,OX40N,ATH,CABLES
69,SURYODAY,2.94,-26.16,66.62,23.03,88094.0,-46838.0,132233.0,216.00,44.74,50.0,H-SC,7.44,166.0,-0.53,1.00,31.20,XR,NTT,BANKS
2,ABBOTINDIA,-0.26,-10.77,32.31,18.07,51567.0,-19255.0,159600.0,35195.00,-24.04,45.0,X-MC,10.83,58.0,-0.37,1.21,1.18,X40,ATH,PHARMA
65,SIEMENS,0.30,-15.12,47.87,25.51,75613.0,-28140.0,157955.0,4671.50,32.74,46.0,H-LC,3.65,51.0,-0.37,1.20,16.32,AR,ATH,ELECTRICAL

In [24]:
# Top N allocation
df_tmp = df_portfolio_features.sort_values(by = 'CurrAlloc%', ascending=False)
top_n_values = [10, 25, 50]

sum_df = pd.DataFrame({
    'Top_N': top_n_values,
    'Sum_Alloc%': [df_tmp['CurrAlloc%'].head(n).sum() for n in top_n_values]
})

sum_df

   Top_N  Sum_Alloc%
0     10       20.60
1     25       45.62
2     50       78.21

In [25]:
# market-cap-wise allocation
df_tmp = df_portfolio_features[cols]
df_tmp.groupby(df_tmp['Conviction'].str[-2:])['CurrAlloc%'].sum().sort_values(ascending=False)

Conviction
SC    44.08
MC    30.43
LC    25.50
Name: CurrAlloc%, dtype: float64

In [26]:
# criteria-wise allocation
df_portfolio_features.groupby('Criteria')['CurrAlloc%'].sum().sort_values(ascending=False)

Criteria
XY24     27.00
X40      25.68
X40N     14.97
AR        9.19
XR        8.18
XY25      7.47
OX40N     6.77
SR        0.75
Name: CurrAlloc%, dtype: float64

In [27]:
# conviction-wise allocation
df_portfolio_features.groupby('Conviction')['CurrAlloc%'].sum().sort_values(ascending=False)

Conviction
X-LC    23.29
X-MC    22.94
H-SC    21.44
X-SC    12.04
M-SC    10.04
H-MC     5.08
M-MC     2.06
H-LC     1.20
M-LC     1.01
L-SC     0.56
L-MC     0.35
Name: CurrAlloc%, dtype: float64

In [28]:
# sector-wise stats
df_tmp = df_portfolio_features.groupby('Category')[['CurrAlloc%', 'Current', 'Current P/L', 'FTT Amt']].sum().sort_values(by=['Current', 'Current P/L'], ascending=False)
df_tmp['Current P/L%'] = round(df_tmp['Current P/L'] * 100 / df_tmp['Current'], 2)
df_tmp['FTT%'] = round(df_tmp['FTT Amt'] * 100 / df_tmp['Current'], 2)
cols = ['CurrAlloc%', 'Current P/L%', 'FTT%']
df_tmp[cols].sort_values(by=['CurrAlloc%'], ascending=False)

               CurrAlloc%  Current P/L%    FTT%
Category
FMCG                15.21        -24.42   68.59
FINANCE             12.94        -25.59   76.77
IT                  11.57        -47.53  122.61
MISC                 6.91        -46.89  110.71
ELECTRICAL           6.68         -9.82   51.87
PAINTS               5.13        -45.59   70.87
INSURANCE            4.84         -6.04   42.33
BANKS                4.75        -22.37   84.49
PHARMA               4.18         -6.61   40.17
AUTO                 3.68        -34.46   87.81
AC                   2.13        -13.09   43.75
HEALTHCARE           1.91        -41.39   78.29
DURABLES             1.84        -58.58   97.16
FOOTWEAR             1.82        -83.45  157.01
TRAVEL               1.81        -87.85  181.91
BREWERIES            1.71         -3.89   25.47
APPARELS             1.62        -25.15   67.84
REALTY               1.45        -15.87   34.91
REFINERIES           1.37        -11.16   39.28
CERAMICS             1.36        -70.88  122.78
CEMENT               1.25        -62.21  183.56
CABLES               1.21          7.32   92.69
JEWELLERY            1.09       -122.45  199.74
ENGINEERING          1.08        -69.07  146.40
CHEMICALS            0.93       -115.43  291.19
ENTERTAINMENT        0.76        -92.17  206.78
TEXTILES             0.42        -67.64  115.44
HOTELS               0.36       -138.47  222.58

In [29]:
# money to be made criteria-wise
df_portfolio_features.groupby('Criteria')['FTT Amt'].agg(['sum', 'count']).sort_values(by='sum', ascending=False)

                sum  count
Criteria
XY24      4029200.0     21
X40       1782553.0     16
XR        1411690.0     12
AR        1358072.0     10
X40N      1324320.0     10
OX40N      896752.0     10
XY25       453050.0      5
SR         319791.0      2

In [30]:
# money to be made conviction-wise
df_portfolio_features.groupby('Conviction')['FTT Amt'].agg(['sum', 'count']).sort_values(by='sum', ascending=False)

                  sum  count
Conviction
H-SC        3959294.0     24
X-MC        1704640.0     15
X-LC        1698114.0     13
X-SC        1592450.0     10
M-SC        1591874.0     14
H-MC         408182.0      3
L-SC         216419.0      2
M-LC         158812.0      1
M-MC         113886.0      2
H-LC          75613.0      1
L-MC          56144.0      1

In [31]:
# money to be made criteria and conviction-wise
df_portfolio_features.groupby(['Conviction', 'Criteria'])['FTT Amt'].agg(['sum', 'count']).sort_values(by='sum', ascending=False)

                           sum  count
Conviction Criteria
H-SC       XY24      1363095.0      6
           AR         985314.0      5
M-SC       XY24       927870.0      6
X-LC       X40        910828.0      7
H-SC       XR         894064.0      7
X-SC       XY24       860314.0      4
X-MC       X40        665610.0      7
           X40N       532763.0      4
X-SC       X40N       526021.0      4
H-SC       OX40N      397030.0      4
M-SC       OX40N      389287.0      5
X-LC       XY24       374449.0      2
H-SC       SR         319791.0      2
X-LC       X40N       265536.0      2
X-MC       XY24       261161.0      2
           XY25       245106.0      2
H-MC       XY24       242311.0      1
X-SC       X40        206115.0      2
M-SC       XR         196686.0      2
H-MC       AR         165871.0      2
M-LC       XR         158812.0      1
X-LC       XY25       147301.0      2
L-SC       OX40N      110435.0      1
           XR         105984.0      1
M-SC       AR          78031.0      1
H-LC       AR          75613.0      1
M-MC       XY25        60643.0      1
L-MC       XR          56144.0      1
M-MC       AR          53243.0      1

In [32]:
# notebook execution time

end_time = time.time()
execution_time = round(end_time - start_time, 0)
print(f"Notebook execution time: {execution_time} seconds")

Notebook execution time: 48.0 seconds