<a href="https://colab.research.google.com/github/ankit-rathi/Quantvesting_v2/blob/main/myStocks_Portfolio_Analysis.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
'''
!pip install pandas==2.2.2 -qq
!pip install pyxirr -qq
!pip install ta -qq
!pip install yfinance==0.2.59 -qq
'''

'\n!pip install pandas==2.2.2 -qq\n!pip install pyxirr -qq\n!pip install ta -qq\n!pip install yfinance==0.2.59 -qq\n'

In [2]:
# import libraries

import numpy as np
import pandas as pd
import datetime
import warnings
warnings.filterwarnings('ignore')
import yfinance as yfin
import ta
import matplotlib.pyplot as plt
import requests

In [3]:
# notebook start time
import time
import datetime
import pytz

start_time = time.time()

# function to print date timestamp
def print_date_time():
  tz_NY = pytz.timezone('Asia/Kolkata')
  datetime_NY = datetime.datetime.now(tz_NY)
  print("Run date time (IST):", datetime_NY.strftime("%Y-%m-%d %H:%M:%S"))

In [4]:
# function to get booked and reserved amount
def get_amt():
  # fetch the JSON data from the URL
  url = "https://raw.githubusercontent.com/ankit-rathi/Tradevesting_v1/main/data/myPortfolioAmts.json"
  response = requests.get(url)
  pf_amts = response.json()  # parse the JSON data

  # extract values from the JSON
  py_booked_amt_dm = pf_amts["py_booked_amt_dm"]
  py_booked_amt_sv = pf_amts["py_booked_amt_sv"]
  cy_booked_amt_dm = pf_amts["cy_booked_amt_dm"]
  cy_booked_amt_sv = pf_amts["cy_booked_amt_sv"]
  reserve_amt_dm = pf_amts["reserve_amt_dm"]
  reserve_amt_sv = pf_amts["reserve_amt_sv"]

  # perform calculations
  py_booked_amt = py_booked_amt_dm + py_booked_amt_sv
  cy_booked_amt = cy_booked_amt_dm + cy_booked_amt_sv
  reserve_amt = reserve_amt_dm + reserve_amt_sv
  total_booked_amt = py_booked_amt + cy_booked_amt

  return total_booked_amt, reserve_amt, cy_booked_amt, py_booked_amt

gen_output = 0

In [5]:
# function to format the amount
def format_amt(number):
    abs_number = abs(number)

    if abs_number >= 1_00_00_000:  # Crores
        formatted_amt = f"{number / 1_00_00_000:.2f} C"
    elif abs_number >= 1_00_000:  # Lakhs
        formatted_amt = f"{number / 1_00_000:.2f} L"
    elif abs_number >= 1_000:  # Thousands
        formatted_amt = f"{number / 1_000:.2f} K"
    else:
        formatted_amt = f"{number:.2f}"

    return formatted_amt

# function to set start and end date
def get_start_end_date():
  start_date = (datetime.date.today() + datetime.timedelta(days=-365)).strftime('%Y-%m-%d')
  end_date = (datetime.date.today() + datetime.timedelta(days=1)).strftime('%Y-%m-%d')
  return start_date, end_date

# function to fetch my portfolio csv
def get_mypfs_df():
  mypfs_df = pd.read_csv('https://raw.githubusercontent.com/ankit-rathi/Tradevesting_v1/main/data/myPortfolioStocks.csv')
  return mypfs_df

# function to fetch my prospects csv
def get_mypps_df():
  mypps_df = pd.read_csv('https://raw.githubusercontent.com/ankit-rathi/Tradevesting_v1/main/data/myProspectsScrips.csv')
  return mypps_df

# function to fetch screener data
def get_myscreen_df():
  myscreen_df = pd.read_csv('https://raw.githubusercontent.com/ankit-rathi/Tradevesting_v1/main/data/myScreenerDB.csv')
  return myscreen_df

# function to fetch momentum data
def get_myinvmt_df():
  myinvmt_df = pd.read_csv('https://raw.githubusercontent.com/ankit-rathi/Tradevesting_v1/main/data/myInvestments.csv')
  return myinvmt_df

# function to get the stock ids
def get_stock_ids(df_pf):
  stock_n100 = df_pf['Symbol'].unique()

  exclude = ['CADILAHC','MMTC', 'MASFIN']

  stock_ids = df_pf[~df_pf['Symbol'].isin(exclude) ]['Symbol'].unique()

  #mypf = mypf[mypf.Forecast.notnull()]
  #stock_ids = mypf['Symbol'].unique()

  #stock_ids.sort()
  return stock_ids

# get features from screener data
def get_screener_features():
  myscreen_df = get_myscreen_df()
  cols = ['Symbol', 'EPS', 'MedPE', 'ROCE%', 'ROE%', 'CapType']
  return myscreen_df[cols]

# get relative strength
def get_relative_strength(stock_list):

    # Dictionary to store stock tickers and their corresponding percentage price change
    stock_changes = {}

    # Loop through each stock and fetch its price data
    for stock in stock_list:
        try:
            # Download the stock data for the given date range
            stock_data = yfin.Ticker(stock + '.NS').history(period='1mo', interval='1d')[map(str.title, ['open', 'close', 'low', 'high', 'volume'])]

            # Calculate the percentage change for the stock
            if len(stock_data) > 0:
                start_price = stock_data['Close'].iloc[0]
                end_price = stock_data['Close'].iloc[-1]
                percent_change = round(((end_price - start_price) / start_price) * 100, 2)
                stock_changes[stock] = percent_change
            else:
                stock_changes[stock] = np.nan  # If no data is available, set to NaN

        except Exception as e:
            print(f"Error fetching data for {stock}: {e}")
            stock_changes[stock] = np.nan

    # Create a DataFrame with stock tickers and their percentage changes
    df = pd.DataFrame(list(stock_changes.items()), columns=['Symbol', 'Percent_Change'])

    # Drop any stocks with missing data (NaN values)
    df = df.dropna()

    # Calculate the percentile rank based on percentage change
    df['RSP'] = round(df['Percent_Change'].rank(pct=True) * 100, 2)
    cols = ['Symbol', 'RSP']
    df = df[cols]
    # Sort by percentile rank (optional)
    df = df.sort_values(by='RSP', ascending=False).reset_index(drop=True)

    return df

In [6]:
# function to get stock technicals
def stock_prec_dev(stock_symbol):
    #stock_symbol = 'ULTRACEMCO.NS'
    short_window = 20
    mid_window = 50
    long_window = 200
    moving_avg = 'SMA'

    start = datetime.datetime(*map(int, start_date.split('-')))
    end = datetime.datetime(*map(int, end_date.split('-')))

    stock_df = yfin.Ticker(stock_symbol + '.NS').history(period='max', interval='1d')[map(str.title, ['open', 'close', 'low', 'high', 'volume'])]

    stock_df['Max'] = round(max(stock_df['Close']),2)
    stock_df = stock_df[(stock_df.index <= end_date) & (stock_df.index >= start_date)]
    stock_df['200_SMA'] = round(stock_df['Close'].rolling(window = 200, min_periods = 1).mean(),0)
    stock_df['Dev%_200'] = round((stock_df['Close'] - stock_df['200_SMA'])*100/stock_df['200_SMA'],2)
    stock_df.dropna(axis = 0, inplace = True) # remove any null rows

    stock_df['20_SMA'] = stock_df['Close'].rolling(window=20).mean()
    stock_df['50_SMA'] = stock_df['Close'].rolling(window=50).mean()
    stock_df['Symbol'] = stock_symbol

    stock_df['Close'] = round(stock_df['Close'],2)
    stock_df['Min'] = round(min(stock_df['Close']),2)
    stock_df['RSI_14'] = ta.momentum.RSIIndicator(close=stock_df['Close'], window=14).rsi()
    stock_df['RSI_14'] = round(stock_df['RSI_14'],0)
    stock_df['Prev_Close'] = stock_df['Close'].shift(1)
    stock_df.drop(['Open', 'Low', 'High', 'Volume'], axis=1, inplace=True)
    stock_df = stock_df.tail(1)

    max_SMA = max(stock_df['20_SMA'].item(), stock_df['50_SMA'].item(), stock_df['200_SMA'].item())
    min_SMA = min(stock_df['20_SMA'].item(), stock_df['50_SMA'].item(), stock_df['200_SMA'].item())
    ABS_Spread = max_SMA - min_SMA
    stock_df['Spread%'] = round((ABS_Spread / stock_df['200_SMA'].item()) * 100,2)

    return stock_df

# function to compute stock attributes
def get_common_features(stock_ids, df_mypf):

  df_prec_dev = pd.DataFrame()
  df_tmp = get_screener_features()
  df_rs = get_relative_strength(stock_ids)

  for stock_id in stock_ids:
      tmp = stock_prec_dev(stock_id)
      tmp = tmp.reset_index()
      df_prec_dev = pd.concat([df_prec_dev, tmp], ignore_index = True)
  df_prec_dev = pd.merge(df_prec_dev, df_mypf, on= 'Symbol')
  df_prec_dev = pd.merge(df_prec_dev, df_tmp, on= 'Symbol', how='left')
  df_prec_dev = pd.merge(df_prec_dev, df_rs, on= 'Symbol', how='left')
  #print(df_prec_dev.columns)
  df_prec_dev['Curr_PE'] = round(df_prec_dev['Close']/df_prec_dev['EPS'],1)
  df_prec_dev['Dev%_PE'] = round((df_prec_dev['Curr_PE'] - df_prec_dev['MedPE'])*100/df_prec_dev['MedPE'],2)
  df_prec_dev['Conviction'] = df_prec_dev['Conviction'] + '-' + df_prec_dev['CapType']
  return df_prec_dev

# function to arrange stock features
def arrange_features(df_stocks, common_cols, diff_cols):
  df_stocks_common = df_stocks[common_cols].drop_duplicates()
  df_stocks_diff = df_stocks[diff_cols]
  df_stocks_diff['Investment'] = df_stocks_diff['AvgCost'] * df_stocks_diff['Shares']
  df_stocks_diff = df_stocks_diff.groupby(['Symbol'])[['Shares', 'Investment']].aggregate(['sum']).reset_index()
  df_stocks_diff.columns = ['Symbol', 'Shares', 'Investment']
  df_stocks_diff['AvgCost'] = round(df_stocks_diff['Investment']/df_stocks_diff['Shares'],2)
  df_stocks = pd.merge(df_stocks_diff, df_stocks_common, on='Symbol')
  return df_stocks

# plot fact distribution across dimension
def plot_pie_chart(df, dimension, fact):
  # grouping the data by category and calculating the sum of fact for each type
  grouped_data = df.groupby(dimension)[fact].sum()

  # sorting the grouped data in descending order
  grouped_data = grouped_data.sort_values(ascending=False)

  # creating a pie chart
  grouped_data.plot.pie(autopct='%1.1f%%', startangle=90, figsize=(6, 6))

  # adding a title and displaying the plot
  plt.title(f'{dimension} {fact} Distribution')
  plt.ylabel('')  # To hide the y-label
  plt.show()

In [7]:
# function to get portfolio features

def get_portfolio_features(df_common_features):

  print_date_time()
  print('-------------------')

  #df_common_features["Target"] = df_common_features["Target"].fillna(df_common_features["Max"])
  df_common_features['NTT'] = np.where(df_common_features['Strategy']== 'NTT', df_common_features["Target"], df_common_features['Max'])
  df_common_features['LTT'] = np.where(df_common_features['Strategy']== 'BTT', df_common_features["Target"], df_common_features['Max'])
  df_common_features['BOL'] = df_common_features['Min']

  tmp_df = df_common_features[df_common_features['Symbol'].isin(mypf_df[mypf_df['InPortfolio'] != 'NA'].Symbol.values)]
  print('qualified stocks: '+str(len(tmp_df['Symbol'].unique())))
  tmp_df1 = tmp_df[tmp_df['LatestQtr'] == 1]
  print('with latest results: '+str(len(tmp_df1['Symbol'].unique())))
  tmp_df1 = tmp_df1[tmp_df1['StarStock'] == 1]
  print('still star stocks: '+str(len(tmp_df1['Symbol'].unique())))
  tmp_df['Investment'] = tmp_df['AvgCost'] * tmp_df['Shares']
  tmp_df['Current'] = round(tmp_df['Close'] * tmp_df['Shares'],0)
  tmp_df['Previous'] = tmp_df['Prev_Close'] * tmp_df['Shares']
  tmp_df['EstimatedST'] = tmp_df['NTT'] * tmp_df['Shares']
  tmp_df['EstimatedLT'] = tmp_df['LTT'] * tmp_df['Shares']
  tmp_df['Current P/L'] = round((tmp_df['Current'] - tmp_df['Investment']),0)
  tmp_df['Today P/L%'] = round((tmp_df['Current'] - tmp_df['Previous'])*100/tmp_df['Previous'],2)
  tmp_df['Current P/L%'] = round((tmp_df['Current'] - tmp_df['Investment'])*100/tmp_df['Investment'],2)
  tmp_df['EstimatedST P/L%'] = round((tmp_df['EstimatedST'] - tmp_df['Investment'])*100/tmp_df['Investment'],2)
  tmp_df['EstimatedLT P/L%'] = round((tmp_df['EstimatedLT'] - tmp_df['Investment'])*100/tmp_df['Investment'],2)
  tmp_df['NTT%'] = round((tmp_df['NTT'] - tmp_df['Close'])*100/tmp_df['Close'],2)
  tmp_df['LTT%'] = round((tmp_df['LTT'] - tmp_df['Close'])*100/tmp_df['Close'],2)
  tmp_df['Gained%'] = round((tmp_df['Close'] - tmp_df['BOL'])*100/tmp_df['BOL'],2)
  investment = round(sum(tmp_df['AvgCost']*tmp_df['Shares']),0)
  current = round(sum(tmp_df['Close']*tmp_df['Shares']),0)
  tmp_df['InitAlloc%'] = round(tmp_df['Investment']*100/investment,2)
  tmp_df['CurrAlloc%'] = round(tmp_df['Current']*100/current,2)
  tmp_df['FTT'] = tmp_df['LTT']
  tmp_df.loc[tmp_df['Strategy'] == 'NTT', 'FTT'] = tmp_df['NTT']
  tmp_df['FTT%'] = tmp_df['LTT%']
  tmp_df.loc[tmp_df['Strategy'] == 'NTT', 'FTT%'] = tmp_df['NTT%']
  tmp_df['FTT Amt'] = round(tmp_df['FTT%'] * tmp_df['Current']/100,0)
  tmp_df['OTT%'] = round((tmp_df['FTT'] - tmp_df['AvgCost'])*100/tmp_df['AvgCost'],2)
  tmp_df['RRR Ind'] = round(tmp_df['Current P/L']/tmp_df['FTT Amt'],2)
  tmp_df['Risk Ind'] = round(tmp_df['Current P/L%']*tmp_df['CurrAlloc%'],0)

  return tmp_df

# function to print portfolio features
def print_portfolio_stats(df_portfolio_features, myinvmt_df):
  from pyxirr import xirr

  total_booked_amt, reserve_amt, cy_booked_amt, py_booked_amt = get_amt()

  dates = myinvmt_df['Date'].values
  dates = np.append(dates, datetime.date.today().strftime('%d-%b-%y'))
  investment = myinvmt_df['Investment'].values
  dates= pd.to_datetime(dates)

  current = round(sum(df_portfolio_features['Close']*df_portfolio_features['Shares']),0) + reserve_amt
  investment_xirr = np.append(investment, current)
  cagr = round(xirr(pd.DataFrame({"dates": dates, "amounts": investment_xirr}))*100,2)

  investment = -sum(investment)
  invested = round(sum(df_portfolio_features['AvgCost']*df_portfolio_features['Shares']),0) + reserve_amt
  previous = round(sum(df_portfolio_features['Prev_Close']*df_portfolio_features['Shares']),0) + reserve_amt
  cy_invested = investment + py_booked_amt

  today_pnl_amount = current-previous
  today_pnl_percentage = round((current-previous)*100/previous,2)

  curr_pnl_amount = current-invested
  curr_pnl_percentage = round((curr_pnl_amount)*100/(cy_invested),2)

  cy_pnl_amount = cy_booked_amt + curr_pnl_amount
  cy_pnl_percentage = round((cy_pnl_amount)*100/cy_invested,2)

  overall_pnl_amount = total_booked_amt + curr_pnl_amount
  overall_pnl_percentage = round((overall_pnl_amount)*100/investment,2)

  estimate_st = round(sum(df_portfolio_features['FTT']*df_portfolio_features['Shares']),0)  + reserve_amt
  est_st_pnl_amount = estimate_st-current
  est_st_pnl_percentage = round((est_st_pnl_amount)*100/current,2)

  estimate_lt = round(sum(df_portfolio_features['LTT']*df_portfolio_features['Shares']),0)  + reserve_amt
  est_lt_pnl_amount = estimate_lt-current
  est_lt_pnl_percentage = round((est_lt_pnl_amount)*100/current,2)

  total_profit = round(sum(df_portfolio_features[df_portfolio_features['Current P/L%'] > 0]['Current']) - sum(df_portfolio_features[df_portfolio_features['Current P/L%'] > 0]['Investment']),0)
  total_loss = round(sum(df_portfolio_features[df_portfolio_features['Current P/L%'] < 0]['Current']) - sum(df_portfolio_features[df_portfolio_features['Current P/L%'] < 0]['Investment']),0)

  cy_booked_percentage = round((cy_booked_amt)*100/current,2)
  py_booked_percentage = round((py_booked_amt)*100/investment,2)
  total_booked_percentage = round((total_booked_amt)*100/investment,2)

  print('-------------------')
  print('Initial Investment: ', format_amt(investment))
  print('CY Investment: ', format_amt(cy_invested))
  print('Reserve: ', format_amt(reserve_amt))
  print('Current: ',  format_amt(current))
  print('-------------------')
  print('Today PnL: '+ '{} ({}%)'.format(format_amt(today_pnl_amount), today_pnl_percentage))
  print('Current PnL: '+ '{} ({}%)'.format(format_amt(curr_pnl_amount), curr_pnl_percentage))
  print('CY Booked + Current PnL: '+ '{} ({}%)'.format(format_amt(cy_pnl_amount), cy_pnl_percentage))
  print('-------------------')
  print('Total profit: ', format_amt(total_profit))
  print('Total loss: ', format_amt(total_loss))
  print('-------------------')
  print('Total Booked + Current PnL: '+ '{} ({}%)'.format(format_amt(overall_pnl_amount), overall_pnl_percentage))
  print('Total Booked PnL: '+ '{} ({}%)'.format(format_amt(total_booked_amt), total_booked_percentage))
  print('Curr Year Booked PnL: '+ '{} ({}%)'.format(format_amt(cy_booked_amt), cy_booked_percentage))
  print('Prev Year Booked PnL: '+ '{} ({}%)'.format(format_amt(py_booked_amt), py_booked_percentage))
  print('===================')
  print('Est FTT: ',  format_amt(estimate_st))
  print('Est FTT PnL: '+ '{} ({}%)'.format(format_amt(est_st_pnl_amount), est_st_pnl_percentage))

  print('===================')
  print('Deployed: ', format_amt(investment))

  print('Current: ', format_amt(current))

  print('CAGR/XIRR %: '+'{}%'.format(cagr))

In [8]:
# get start and end date
start_date, end_date = get_start_end_date()

# get portfolio and prospects data
mypfs_df = get_mypfs_df()
mypps_df = get_mypps_df()
myinvmt_df = get_myinvmt_df()

# merge above datasets
mypf_df = pd.merge(mypfs_df, mypps_df, on="Symbol")

# seggregate dm and sv portfolio
dm_pf = mypf_df[mypf_df['InPortfolio'] == 'DM']
sv_pf = mypf_df[mypf_df['InPortfolio'] == 'SV']

# build portfolio stock dataframe
dm_stocks = get_stock_ids(dm_pf)
sv_stocks = get_stock_ids(sv_pf)
df_stocks = pd.concat([dm_pf,sv_pf], ignore_index = True)

# arrange common and diff stock features
common_cols = ['Symbol', 'Target', 'Criteria', 'Strategy', 'CumlRnk', 'LatestQtr', 'StarStock', 'Conviction', 'Category', 'InFolio', 'XIRR', 'MBQ']
diff_cols = ['Symbol', 'AvgCost', 'Shares']
df_stocks = arrange_features(df_stocks, common_cols, diff_cols)

# get common features
stock_ids = df_stocks['Symbol'].values
df_common_features = get_common_features(stock_ids, df_stocks)

df_common_features.reset_index(drop=True, inplace=True)
df_common_features.drop(['Date'], axis=1, inplace=True)
# get and print portfolio features
df_portfolio_features = get_portfolio_features(df_common_features)

print_portfolio_stats(df_portfolio_features, myinvmt_df)

df = df_portfolio_features
#plot_pie_chart(df, 'CapType', 'Current')
list_ox40n = list(df[df['MBQ'].str.contains('OX40N', na=False)]['Symbol'].values)

Run date time (IST): 2026-05-22 15:19:45
-------------------
qualified stocks: 92
with latest results: 31
still star stocks: 20
-------------------
Initial Investment:  1.40 C
CY Investment:  1.82 C
Reserve:  1.49 K
Current:  1.49 C
-------------------
Today PnL: 62.51 K (0.42%)
Current PnL: -34.32 L (-18.82%)
CY Booked + Current PnL: -32.24 L (-17.68%)
-------------------
Total profit:  2.03 L
Total loss:  -36.35 L
-------------------
Total Booked + Current PnL: 10.63 L (7.62%)
Total Booked PnL: 44.95 L (32.22%)
Curr Year Booked PnL: 2.08 L (1.4%)
Prev Year Booked PnL: 42.87 L (30.73%)
===================
Est FTT:  2.55 C
Est FTT PnL: 1.07 C (71.58%)
===================
Deployed:  1.40 C
Current:  1.49 C
CAGR/XIRR %: 3.14%

In [9]:
# top 5 near their targets
cols = ['Symbol', 'Today P/L%', 'Current P/L%', 'FTT%', 'OTT%', 'FTT Amt', 'Current P/L', 'Current', 'FTT', 'Dev%_PE', 'RSI_14','Conviction', 'Spread%',  'CumlRnk', 'RRR Ind', 'CurrAlloc%', 'Gained%', 'Criteria', 'Strategy', 'Category']
df_tmp = df_portfolio_features[~df_portfolio_features['Symbol'].isin(['ENRIN','BLUSPRING','DIGITIDE'])]
df_tmp = df_tmp.sort_values(by = 'FTT Amt', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
59,PIDILITIND,0.43,4.83,12.92,18.37,19111.0,6810.0,147920.0,1670.26,-26.53,62.0,X-LC,5.48,5.0,0.36,0.99,16.14,X40,ATH,CHEMICALS
51,KOTAKBANK,1.01,2.79,17.82,21.11,25365.0,3866.0,142339.0,453.24,-12.01,54.0,X-LC,7.83,12.0,0.15,0.96,8.86,X40,ATH,BANKS
55,MASFIN,0.57,-5.77,29.01,21.57,26783.0,-5655.0,92325.0,397.04,-18.70,37.0,H-SC,5.01,167.0,-0.21,0.62,10.05,XR,ATH,FINANCE
83,TTKPRESTIG,-0.90,-30.22,43.43,0.09,30543.0,-30450.0,70327.0,770.00,63.29,58.0,M-SC,15.79,250.0,-1.00,0.47,25.23,OX40N,NTT,DURABLES
53,M&M,-0.58,-0.03,23.41,23.38,32457.0,-36.0,138645.0,3802.40,-15.13,44.0,X-LC,8.85,25.0,-0.00,0.93,5.11,X40N,ATH,AUTO

In [10]:
# top 5 today
df_tmp = df_portfolio_features.sort_values(by = 'Today P/L%', ascending=False)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
29,GREENPANEL,7.51,-48.29,176.80,43.14,167380.0,-88406.0,94672.0,537.00,111.89,41.0,M-SC,16.22,225.0,-0.53,0.64,13.72,XY24,NTT,MISC
69,SFL,7.48,-37.03,101.09,26.63,166920.0,-97098.0,165120.0,1287.00,25.06,70.0,M-SC,11.62,242.0,-0.58,1.11,37.62,XY24,NTT,MISC
22,DIXON,4.28,-14.47,61.26,37.92,136647.0,-37738.0,223060.0,18931.72,-63.68,61.0,X-MC,19.95,54.0,-0.28,1.50,21.37,X40N,ATH,IT
87,VBL,4.07,9.28,23.87,35.37,82389.0,29316.0,345158.0,670.16,-3.60,73.0,X-LC,11.00,13.0,0.36,2.32,41.86,X40N,ATH,FMCG
49,JSWINFRA,3.86,-6.14,24.05,16.43,50061.0,-13620.0,208154.0,342.00,-19.42,55.0,X-MC,5.94,61.0,-0.27,1.40,17.66,X40N,NTT,REALTY

In [11]:
# bottom 5 today
df_tmp = df_portfolio_features.sort_values(by = 'Today P/L%', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
89,WHIRLPOOL,-3.91,-32.43,169.23,81.92,131272.0,-37228.0,77570.0,2270.0,-60.49,39.0,M-SC,16.00,210.0,-0.28,0.52,8.96,XR,NTT,DURABLES
68,SATIN,-3.23,16.70,30.10,51.83,97051.0,46145.0,322429.0,274.0,5.12,62.0,H-SC,32.15,159.0,0.48,2.17,57.07,XY24,NTT,FINANCE
85,VAIBHAVGBL,-3.10,-31.80,135.75,60.77,169204.0,-58131.0,124644.0,521.0,43.80,51.0,H-SC,6.27,160.0,-0.34,0.84,26.03,XR,NTT,JEWELLERY
86,VALIANTORG,-2.53,-40.74,193.88,74.15,187969.0,-66654.0,96951.0,838.0,-274.67,52.0,H-SC,9.13,145.0,-0.35,0.65,44.28,XR,NTT,CHEMICALS
47,ITC,-2.11,-20.57,49.89,19.06,134797.0,-69977.0,270189.0,452.0,-56.33,42.0,X-LC,14.89,1.0,-0.52,1.82,4.81,X40,NTT,FMCG

In [12]:
# top 5 to exit based on CumlRnk
df_tmp = df_portfolio_features[~df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])]
df_tmp = df_tmp[(df_tmp['Current P/L%'] > -1) & (df_tmp['Current P/L%'] < 1)].sort_values(by = 'CumlRnk', ascending=False)
df_tmp[cols].head()

Empty DataFrame
Columns: [Symbol, Today P/L%, Current P/L%, FTT%, OTT%, FTT Amt, Current P/L, Current, FTT, Dev%_PE, RSI_14, Conviction, Spread%, CumlRnk, RRR Ind, CurrAlloc%, Gained%, Criteria, Strategy, Category]
Index: []

In [13]:
# OX40N stocks to exit
df_tmp = df_portfolio_features[(df_portfolio_features['Symbol'].isin(list_ox40n))].sort_values(by = 'Current P/L%', ascending=False)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
25,FINCABLES,-0.89,30.94,58.78,107.91,113639.0,45686.0,193330.0,1641.55,17.71,54.0,M-SC,25.57,220.0,0.40,1.30,45.45,OX40N,ATH,CABLES
72,SIS,0.00,-10.02,34.76,21.26,34728.0,-11123.0,99909.0,528.00,2375.65,63.0,H-SC,15.55,168.0,-0.32,0.67,48.55,OX40N,NTT,MISC
16,CERA,-1.30,-25.31,65.86,23.89,86532.0,-44515.0,131388.0,9475.00,-27.92,57.0,H-SC,7.04,153.0,-0.51,0.88,26.26,OX40N,NTT,CERAMICS
50,KANSAINER,-0.02,-27.27,56.01,13.47,109856.0,-73530.0,196137.0,340.00,-37.50,62.0,H-SC,13.42,162.0,-0.67,1.32,37.00,XY24,NTT,PAINTS
43,INDIGOPNTS,1.23,-28.70,40.27,0.02,50122.0,-50094.0,124465.0,1408.00,89.73,68.0,M-SC,19.06,222.0,-1.00,0.84,41.21,OX40N,NTT,PAINTS

In [14]:
# top 5 to book for rotation
df_tmp = df_portfolio_features[(df_portfolio_features['Current P/L%'] > 20) ].sort_values(by = 'CumlRnk', ascending=False)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
25,FINCABLES,-0.89,30.94,58.78,107.91,113639.0,45686.0,193330.0,1641.55,17.71,54.0,M-SC,25.57,220.0,0.4,1.3,45.45,OX40N,ATH,CABLES

In [15]:
# top 5 to monitor for exit
df_tmp = df_portfolio_features[~df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])]
df_tmp = df_tmp[(df_tmp['Current P/L%'] > 0) ].sort_values(by = 'Dev%_PE', ascending=False)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
74,STARHEALTH,-0.68,1.22,45.49,47.26,129437.0,3416.0,284539.0,761.00,59.71,61.0,H-SC,10.26,173.0,0.03,1.91,24.92,XY24,NTT,INSURANCE
25,FINCABLES,-0.89,30.94,58.78,107.91,113639.0,45686.0,193330.0,1641.55,17.71,54.0,M-SC,25.57,220.0,0.40,1.30,45.45,OX40N,ATH,CABLES
68,SATIN,-3.23,16.70,30.10,51.83,97051.0,46145.0,322429.0,274.00,5.12,62.0,H-SC,32.15,159.0,0.48,2.17,57.07,XY24,NTT,FINANCE
91,ZYDUSLIFE,0.21,9.53,23.83,35.63,54700.0,19968.0,229542.0,1286.17,-4.50,70.0,H-MC,3.37,120.0,0.37,1.54,20.69,AR,ATH,PHARMA
73,SONACOMS,1.66,2.76,35.36,39.09,36757.0,2791.0,103950.0,804.02,-18.58,57.0,M-MC,19.31,193.0,0.08,0.70,47.05,AR,ATH,AUTO

In [16]:
# top 5 to book for rotation from weak conviction
df_tmp = df_portfolio_features[~df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])]
df_tmp = df_tmp[~df_tmp['Criteria'].isin(['XY25','XY24','X40', 'X40N'])].sort_values(by = 'RRR Ind', ascending=False)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
25,FINCABLES,-0.89,30.94,58.78,107.91,113639.0,45686.0,193330.0,1641.55,17.71,54.0,M-SC,25.57,220.0,0.40,1.30,45.45,OX40N,ATH,CABLES
91,ZYDUSLIFE,0.21,9.53,23.83,35.63,54700.0,19968.0,229542.0,1286.17,-4.50,70.0,H-MC,3.37,120.0,0.37,1.54,20.69,AR,ATH,PHARMA
73,SONACOMS,1.66,2.76,35.36,39.09,36757.0,2791.0,103950.0,804.02,-18.58,57.0,M-MC,19.31,193.0,0.08,0.70,47.05,AR,ATH,AUTO
42,INDIAMART,0.02,-12.74,136.91,106.72,147345.0,-15714.0,107622.0,4810.62,-60.55,47.0,H-SC,10.34,140.0,-0.11,0.72,4.19,AR,ATH,MISC
90,WIPRO,1.63,-16.74,106.90,72.27,150820.0,-28363.0,141085.0,420.00,-25.02,59.0,M-LC,13.91,98.0,-0.19,0.95,8.24,XR,NTT,IT

In [17]:
# top 5 to accumulate based on lowest RSI_14
df_tmp = df_portfolio_features[df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])].sort_values(by = 'RSI_14', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
23,DMART,-0.42,-0.96,30.86,29.60,76286.0,-2400.0,247200.0,5391.45,-16.48,34.0,X-LC,5.23,14.0,-0.03,1.66,12.99,X40N,ATH,FMCG
58,PGHH,-0.69,-28.12,83.64,32.01,128377.0,-60032.0,153488.0,17616.87,-51.42,37.0,X-MC,17.51,57.0,-0.47,1.03,4.98,X40,ATH,FMCG
33,HCLTECH,-0.27,-24.40,60.72,21.51,111060.0,-59019.0,182905.0,1872.35,-20.60,38.0,X-LC,18.52,8.0,-0.53,1.23,3.65,X40,ATH,IT
27,GLAXO,-0.33,-7.15,49.86,39.15,92261.0,-14244.0,185040.0,3466.20,-29.05,38.0,X-MC,6.34,56.0,-0.15,1.24,2.37,X40,ATH,PHARMA
79,TCS,-0.39,-31.95,86.00,26.57,271125.0,-148011.0,315262.0,4311.59,-42.31,39.0,X-LC,17.11,2.0,-0.55,2.12,3.21,X40,ATH,IT

In [18]:
# top 5 to accumulate based on Spread and CumlRnk
df_tmp = df_portfolio_features[df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])]
df_tmp = df_tmp[(df_tmp['CumlRnk'] < 100)].sort_values(by = 'Spread%', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
88,VOLTAS,-0.37,-0.74,46.28,45.20,88080.0,-1422.0,190320.0,1856.00,13.69,41.0,X-MC,2.62,79.0,-0.02,1.28,3.98,XY25,NTT,AC
84,UNITDSPR,0.75,-5.81,28.22,20.77,62236.0,-13606.0,220538.0,1644.00,-16.49,46.0,X-MC,3.42,64.0,-0.22,1.48,5.20,X40N,NTT,BREWERIES
65,RELIANCE,0.37,-13.05,44.10,25.30,77062.0,-26220.0,174743.0,1952.00,-15.42,45.0,X-LC,3.80,21.0,-0.34,1.17,3.83,XY25,BTT,REFINERIES
39,ICICIGI,1.40,-3.26,23.36,19.34,45222.0,-6521.0,193588.0,2252.93,-18.61,53.0,X-MC,4.91,66.0,-0.14,1.30,8.12,X40,ATH,INSURANCE
23,DMART,-0.42,-0.96,30.86,29.60,76286.0,-2400.0,247200.0,5391.45,-16.48,34.0,X-LC,5.23,14.0,-0.03,1.66,12.99,X40N,ATH,FMCG

In [19]:
# top 5 to accumulate based on lowest Gained%
df_tmp = df_portfolio_features[df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])].sort_values(by = 'Gained%', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
32,HAVELLS,-0.24,-23.12,70.94,31.42,178888.0,-75823.0,252168.0,2052.62,-27.65,42.0,X-MC,12.37,63.0,-0.42,1.69,2.22,X40,ATH,ELECTRICAL
27,GLAXO,-0.33,-7.15,49.86,39.15,92261.0,-14244.0,185040.0,3466.20,-29.05,38.0,X-MC,6.34,56.0,-0.15,1.24,2.37,X40,ATH,PHARMA
79,TCS,-0.39,-31.95,86.00,26.57,271125.0,-148011.0,315262.0,4311.59,-42.31,39.0,X-LC,17.11,2.0,-0.55,2.12,3.21,X40,ATH,IT
40,ICICIPRULI,1.98,-13.92,51.86,30.73,87947.0,-27420.0,169585.0,790.00,-37.08,43.0,X-MC,12.13,78.0,-0.31,1.14,3.34,X40,ATH,INSURANCE
33,HCLTECH,-0.27,-24.40,60.72,21.51,111060.0,-59019.0,182905.0,1872.35,-20.60,38.0,X-LC,18.52,8.0,-0.53,1.23,3.65,X40,ATH,IT

In [20]:
# top 5 to accumulate based on lowest CurrAlloc%
df_tmp = df_portfolio_features[df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])].sort_values(by = 'CurrAlloc%', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
64,RELAXO,0.78,-61.65,297.16,52.31,165420.0,-89493.0,55667.0,1176.00,-59.15,50.0,X-SC,25.02,92.0,-0.54,0.37,24.46,X40N,NTT,FOOTWEAR
10,BATAINDIA,-0.10,-55.61,204.58,35.20,116848.0,-71554.0,57116.0,2096.00,-25.05,40.0,X-SC,25.78,91.0,-0.61,0.38,13.28,X40,NTT,FOOTWEAR
60,QUESS,0.60,-16.89,109.25,73.90,96962.0,-18041.0,88752.0,424.00,-55.37,50.0,X-SC,10.59,80.0,-0.19,0.60,20.99,XY24,NTT,MISC
28,GODREJCP,1.09,-7.97,42.85,31.47,58609.0,-11837.0,136777.0,1469.04,-3.15,45.0,X-LC,8.38,32.0,-0.20,0.92,4.95,X40N,ATH,FMCG
53,M&M,-0.58,-0.03,23.41,23.38,32457.0,-36.0,138645.0,3802.40,-15.13,44.0,X-LC,8.85,25.0,-0.00,0.93,5.11,X40N,ATH,AUTO

In [21]:
# top 5 to accumulate based on CumlRnk
df_tmp = df_portfolio_features.sort_values(by = 'CumlRnk', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
47,ITC,-2.11,-20.57,49.89,19.06,134797.0,-69977.0,270189.0,452.00,-56.33,42.0,X-LC,14.89,1.0,-0.52,1.82,4.81,X40,NTT,FMCG
79,TCS,-0.39,-31.95,86.00,26.57,271125.0,-148011.0,315262.0,4311.59,-42.31,39.0,X-LC,17.11,2.0,-0.55,2.12,3.21,X40,ATH,IT
45,INFY,-0.57,-20.05,67.90,34.24,169864.0,-62720.0,250168.0,1972.00,-37.23,46.0,X-LC,19.09,3.0,-0.37,1.68,7.26,X40,NTT,IT
81,TMPV,0.57,-17.28,65.11,36.58,191654.0,-61487.0,294354.0,600.00,-82.53,60.0,X-LC,6.04,4.0,-0.32,1.98,22.69,XY24,NTT,AUTO
59,PIDILITIND,0.43,4.83,12.92,18.37,19111.0,6810.0,147920.0,1670.26,-26.53,62.0,X-LC,5.48,5.0,0.36,0.99,16.14,X40,ATH,CHEMICALS

In [22]:
# top 5 for average up
df_tmp = df_portfolio_features[(df_portfolio_features['Dev%_200'] > 5)].sort_values(by = 'CurrAlloc%', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
44,INDUSINDBK,1.17,-32.78,97.69,32.89,50699.0,-25308.0,51898.0,1800.00,-344.40,56.0,L-MC,8.58,258.0,-0.50,0.35,27.74,XR,NTT,BANKS
72,SIS,0.00,-10.02,34.76,21.26,34728.0,-11123.0,99909.0,528.00,2375.65,63.0,H-SC,15.55,168.0,-0.32,0.67,48.55,OX40N,NTT,MISC
73,SONACOMS,1.66,2.76,35.36,39.09,36757.0,2791.0,103950.0,804.02,-18.58,57.0,M-MC,19.31,193.0,0.08,0.70,47.05,AR,ATH,AUTO
75,SURYODAY,-0.05,-9.09,35.34,23.03,57531.0,-16279.0,162792.0,216.00,77.63,53.0,H-SC,17.29,166.0,-0.28,1.09,37.07,XR,NTT,BANKS
69,SFL,7.48,-37.03,101.09,26.63,166920.0,-97098.0,165120.0,1287.00,25.06,70.0,M-SC,11.62,242.0,-0.58,1.11,37.62,XY24,NTT,MISC

In [23]:
# top 5 RSP
df_tmp = df_portfolio_features.sort_values(by = 'RSP', ascending=False)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
68,SATIN,-3.23,16.70,30.10,51.83,97051.0,46145.0,322429.0,274.00,5.12,62.0,H-SC,32.15,159.0,0.48,2.17,57.07,XY24,NTT,FINANCE
72,SIS,0.00,-10.02,34.76,21.26,34728.0,-11123.0,99909.0,528.00,2375.65,63.0,H-SC,15.55,168.0,-0.32,0.67,48.55,OX40N,NTT,MISC
3,ALKYLAMINE,-1.02,-26.55,163.60,93.63,121329.0,-26801.0,74162.0,4546.37,-21.40,60.0,H-SC,13.44,142.0,-0.22,0.50,40.04,SR,ATH,CHEMICALS
69,SFL,7.48,-37.03,101.09,26.63,166920.0,-97098.0,165120.0,1287.00,25.06,70.0,M-SC,11.62,242.0,-0.58,1.11,37.62,XY24,NTT,MISC
17,CIPLA,-0.13,13.35,18.82,34.69,32674.0,20451.0,173612.0,1663.60,-12.20,62.0,X-LC,10.08,18.0,0.63,1.17,17.42,X40N,ATH,PHARMA

In [24]:
# Top N allocation
df_tmp = df_portfolio_features.sort_values(by = 'CurrAlloc%', ascending=False)
top_n_values = [10, 25, 50]

sum_df = pd.DataFrame({
    'Top_N': top_n_values,
    'Sum_Alloc%': [df_tmp['CurrAlloc%'].head(n).sum() for n in top_n_values]
})

sum_df

   Top_N  Sum_Alloc%
0     10       19.43
1     25       42.81
2     50       72.97

In [25]:
# market-cap-wise allocation
df_tmp = df_portfolio_features[cols]
df_tmp.groupby(df_tmp['Conviction'].str[-2:])['CurrAlloc%'].sum().sort_values(ascending=False)

Conviction
SC    42.41
LC    31.70
MC    25.92
Name: CurrAlloc%, dtype: float64

In [26]:
# criteria-wise allocation
df_portfolio_features.groupby('Criteria')['CurrAlloc%'].sum().sort_values(ascending=False)

Criteria
XY24     27.38
X40      25.60
X40N     17.00
XR        8.83
OX40N     6.92
AR        6.82
XY25      6.63
SR        0.85
Name: CurrAlloc%, dtype: float64

In [27]:
# conviction-wise allocation
df_portfolio_features.groupby('Conviction')['CurrAlloc%'].sum().sort_values(ascending=False)

Conviction
X-LC    29.47
H-SC    22.10
X-MC    20.92
M-SC    10.05
X-SC     9.75
H-MC     2.70
M-MC     1.95
H-LC     1.28
M-LC     0.95
L-SC     0.51
L-MC     0.35
Name: CurrAlloc%, dtype: float64

In [28]:
# sector-wise stats
df_tmp = df_portfolio_features.groupby('Category')[['CurrAlloc%', 'Current', 'Current P/L', 'FTT Amt']].sum().sort_values(by=['Current', 'Current P/L'], ascending=False)
df_tmp['Current P/L%'] = round(df_tmp['Current P/L'] * 100 / df_tmp['Current'], 2)
df_tmp['FTT%'] = round(df_tmp['FTT Amt'] * 100 / df_tmp['Current'], 2)
cols = ['CurrAlloc%', 'Current P/L%', 'FTT%']
df_tmp[cols].sort_values(by=['CurrAlloc%'], ascending=False)

               CurrAlloc%  Current P/L%    FTT%
Category
FMCG                15.33        -16.07   56.98
FINANCE             10.69        -16.03   66.49
IT                  10.41        -45.59  118.89
MISC                 6.95        -29.74   86.11
AUTO                 6.70         -9.91   51.12
BANKS                5.60         -8.96   59.34
PAINTS               5.57        -19.02   39.69
INSURANCE            5.36         -3.67   38.95
PHARMA               5.07          1.86   29.68
ELECTRICAL           4.16        -14.13   54.40
CHEMICALS            2.14        -27.16  102.94
HEALTHCARE           2.05        -16.92   47.44
APPARELS             1.86          2.97   30.12
AC                   1.79        -20.11   52.68
TRAVEL               1.69        -77.99  167.12
FOOTWEAR             1.65        -78.55  150.13
DURABLES             1.62        -60.49   99.53
BREWERIES            1.48         -6.17   28.22
REALTY               1.40         -6.54   24.05
CERAMICS             1.33        -54.72  101.72
CABLES               1.30         23.63   58.78
REFINERIES           1.17        -15.00   44.10
ENGINEERING          1.16        -39.90  103.89
CEMENT               1.10        -64.35  187.31
JEWELLERY            1.03       -108.79  181.34
ENTERTAINMENT        0.70        -85.79  196.60
TEXTILES             0.40        -53.20   96.88
HOTELS               0.32       -141.78  227.06

In [29]:
# money to be made criteria-wise
df_portfolio_features.groupby('Criteria')['FTT Amt'].agg(['sum', 'count']).sort_values(by='sum', ascending=False)

                sum  count
Criteria
XY24      3524421.0     21
X40       1890124.0     19
XR        1367424.0     13
X40N      1194729.0     13
AR        1169266.0      9
OX40N      762162.0     10
XY25       453872.0      5
SR         293498.0      2

In [30]:
# money to be made conviction-wise
df_portfolio_features.groupby('Conviction')['FTT Amt'].agg(['sum', 'count']).sort_values(by='sum', ascending=False)

                  sum  count
Conviction
H-SC        3496896.0     24
X-LC        1912854.0     21
X-MC        1617525.0     15
M-SC        1423069.0     14
X-SC        1353375.0      9
H-MC         295442.0      2
L-SC         215311.0      2
M-LC         150820.0      1
M-MC          96633.0      2
L-MC          50699.0      1
H-LC          42872.0      1

In [31]:
# money to be made criteria and conviction-wise
df_portfolio_features.groupby(['Conviction', 'Criteria'])['FTT Amt'].agg(['sum', 'count']).sort_values(by='sum', ascending=False)

                           sum  count
Conviction Criteria
H-SC       XY24      1093866.0      6
X-LC       X40       1016647.0     10
H-SC       AR         958136.0      5
M-SC       XY24       832265.0      6
H-SC       XR         822302.0      7
X-SC       XY24       796028.0      4
X-MC       X40        660444.0      7
           X40N       489164.0      4
X-LC       X40N       361251.0      6
X-SC       X40N       344314.0      3
X-LC       XY24       338734.0      2
H-SC       OX40N      329094.0      4
M-SC       OX40N      324391.0      5
H-SC       SR         293498.0      2
X-MC       XY25       245131.0      2
H-MC       XY24       240742.0      1
X-MC       XY24       222786.0      2
X-SC       X40        213033.0      2
M-SC       XR         189612.0      2
M-LC       XR         150820.0      1
X-LC       XY25       148865.0      2
L-SC       OX40N      108677.0      1
           XR         106634.0      1
M-SC       AR          76801.0      1
M-MC       XY25        59876.0      1
H-MC       AR          54700.0      1
L-MC       XR          50699.0      1
X-LC       XR          47357.0      1
H-LC       AR          42872.0      1
M-MC       AR          36757.0      1

In [32]:
# notebook execution time

end_time = time.time()
execution_time = round(end_time - start_time, 0)
print(f"Notebook execution time: {execution_time} seconds")

Notebook execution time: 28.0 seconds