<a href="https://colab.research.google.com/github/ankit-rathi/Quantvesting_v2/blob/main/myStocks_Portfolio_Analysis.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
'''
!pip install pandas==2.2.2 -qq
!pip install pyxirr -qq
!pip install ta -qq
!pip install yfinance==0.2.59 -qq
'''

'\n!pip install pandas==2.2.2 -qq\n!pip install pyxirr -qq\n!pip install ta -qq\n!pip install yfinance==0.2.59 -qq\n'

In [2]:
# import libraries

import numpy as np
import pandas as pd
import datetime
import warnings
warnings.filterwarnings('ignore')
import yfinance as yfin
import ta
import matplotlib.pyplot as plt
import requests

In [3]:
# notebook start time
import time
import datetime
import pytz

start_time = time.time()

# function to print date timestamp
def print_date_time():
  tz_NY = pytz.timezone('Asia/Kolkata')
  datetime_NY = datetime.datetime.now(tz_NY)
  print("Run date time (IST):", datetime_NY.strftime("%Y-%m-%d %H:%M:%S"))

In [4]:
# function to get booked and reserved amount
def get_amt():
  # fetch the JSON data from the URL
  url = "https://raw.githubusercontent.com/ankit-rathi/Tradevesting_v1/main/data/myPortfolioAmts.json"
  response = requests.get(url)
  pf_amts = response.json()  # parse the JSON data

  # extract values from the JSON
  py_booked_amt_dm = pf_amts["py_booked_amt_dm"]
  py_booked_amt_sv = pf_amts["py_booked_amt_sv"]
  cy_booked_amt_dm = pf_amts["cy_booked_amt_dm"]
  cy_booked_amt_sv = pf_amts["cy_booked_amt_sv"]
  reserve_amt_dm = pf_amts["reserve_amt_dm"]
  reserve_amt_sv = pf_amts["reserve_amt_sv"]

  # perform calculations
  py_booked_amt = py_booked_amt_dm + py_booked_amt_sv
  cy_booked_amt = cy_booked_amt_dm + cy_booked_amt_sv
  reserve_amt = reserve_amt_dm + reserve_amt_sv
  total_booked_amt = py_booked_amt + cy_booked_amt

  return total_booked_amt, reserve_amt, cy_booked_amt, py_booked_amt

gen_output = 0

In [5]:
# function to format the amount
def format_amt(number):
    abs_number = abs(number)

    if abs_number >= 1_00_00_000:  # Crores
        formatted_amt = f"{number / 1_00_00_000:.2f} C"
    elif abs_number >= 1_00_000:  # Lakhs
        formatted_amt = f"{number / 1_00_000:.2f} L"
    elif abs_number >= 1_000:  # Thousands
        formatted_amt = f"{number / 1_000:.2f} K"
    else:
        formatted_amt = f"{number:.2f}"

    return formatted_amt

# function to set start and end date
def get_start_end_date():
  start_date = (datetime.date.today() + datetime.timedelta(days=-365)).strftime('%Y-%m-%d')
  end_date = (datetime.date.today() + datetime.timedelta(days=1)).strftime('%Y-%m-%d')
  return start_date, end_date

# function to fetch my portfolio csv
def get_mypfs_df():
  mypfs_df = pd.read_csv('https://raw.githubusercontent.com/ankit-rathi/Tradevesting_v1/main/data/myPortfolioStocks.csv')
  return mypfs_df

# function to fetch my prospects csv
def get_mypps_df():
  mypps_df = pd.read_csv('https://raw.githubusercontent.com/ankit-rathi/Tradevesting_v1/main/data/myProspectsScrips.csv')
  return mypps_df

# function to fetch screener data
def get_myscreen_df():
  myscreen_df = pd.read_csv('https://raw.githubusercontent.com/ankit-rathi/Tradevesting_v1/main/data/myScreenerDB.csv')
  return myscreen_df

# function to fetch momentum data
def get_myinvmt_df():
  myinvmt_df = pd.read_csv('https://raw.githubusercontent.com/ankit-rathi/Tradevesting_v1/main/data/myInvestments.csv')
  return myinvmt_df

# function to get the stock ids
def get_stock_ids(df_pf):
  stock_n100 = df_pf['Symbol'].unique()

  exclude = ['CADILAHC','MMTC', 'MASFIN']

  stock_ids = df_pf[~df_pf['Symbol'].isin(exclude) ]['Symbol'].unique()

  #mypf = mypf[mypf.Forecast.notnull()]
  #stock_ids = mypf['Symbol'].unique()

  #stock_ids.sort()
  return stock_ids

# get features from screener data
def get_screener_features():
  myscreen_df = get_myscreen_df()
  cols = ['Symbol', 'EPS', 'MedPE', 'ROCE%', 'ROE%', 'CapType']
  return myscreen_df[cols]

# get relative strength
def get_relative_strength(stock_list):

    # Dictionary to store stock tickers and their corresponding percentage price change
    stock_changes = {}

    # Loop through each stock and fetch its price data
    for stock in stock_list:
        try:
            # Download the stock data for the given date range
            stock_data = yfin.Ticker(stock + '.NS').history(period='1mo', interval='1d')[map(str.title, ['open', 'close', 'low', 'high', 'volume'])]

            # Calculate the percentage change for the stock
            if len(stock_data) > 0:
                start_price = stock_data['Close'].iloc[0]
                end_price = stock_data['Close'].iloc[-1]
                percent_change = round(((end_price - start_price) / start_price) * 100, 2)
                stock_changes[stock] = percent_change
            else:
                stock_changes[stock] = np.nan  # If no data is available, set to NaN

        except Exception as e:
            print(f"Error fetching data for {stock}: {e}")
            stock_changes[stock] = np.nan

    # Create a DataFrame with stock tickers and their percentage changes
    df = pd.DataFrame(list(stock_changes.items()), columns=['Symbol', 'Percent_Change'])

    # Drop any stocks with missing data (NaN values)
    df = df.dropna()

    # Calculate the percentile rank based on percentage change
    df['RSP'] = round(df['Percent_Change'].rank(pct=True) * 100, 2)
    cols = ['Symbol', 'RSP']
    df = df[cols]
    # Sort by percentile rank (optional)
    df = df.sort_values(by='RSP', ascending=False).reset_index(drop=True)

    return df

In [6]:
# function to get stock technicals
def stock_prec_dev(stock_symbol):
    #stock_symbol = 'ULTRACEMCO.NS'
    short_window = 20
    mid_window = 50
    long_window = 200
    moving_avg = 'SMA'

    start = datetime.datetime(*map(int, start_date.split('-')))
    end = datetime.datetime(*map(int, end_date.split('-')))

    stock_df = yfin.Ticker(stock_symbol + '.NS').history(period='max', interval='1d')[map(str.title, ['open', 'close', 'low', 'high', 'volume'])]

    stock_df['Max'] = round(max(stock_df['Close']),2)
    stock_df = stock_df[(stock_df.index <= end_date) & (stock_df.index >= start_date)]
    stock_df['200_SMA'] = round(stock_df['Close'].rolling(window = 200, min_periods = 1).mean(),0)
    stock_df['Dev%_200'] = round((stock_df['Close'] - stock_df['200_SMA'])*100/stock_df['200_SMA'],2)
    stock_df.dropna(axis = 0, inplace = True) # remove any null rows

    stock_df['20_SMA'] = stock_df['Close'].rolling(window=20).mean()
    stock_df['50_SMA'] = stock_df['Close'].rolling(window=50).mean()
    stock_df['Symbol'] = stock_symbol

    stock_df['Close'] = round(stock_df['Close'],2)
    stock_df['Min'] = round(min(stock_df['Close']),2)
    stock_df['RSI_14'] = ta.momentum.RSIIndicator(close=stock_df['Close'], window=14).rsi()
    stock_df['RSI_14'] = round(stock_df['RSI_14'],0)
    stock_df['Prev_Close'] = stock_df['Close'].shift(1)
    stock_df.drop(['Open', 'Low', 'High', 'Volume'], axis=1, inplace=True)
    stock_df = stock_df.tail(1)

    max_SMA = max(stock_df['20_SMA'].item(), stock_df['50_SMA'].item(), stock_df['200_SMA'].item())
    min_SMA = min(stock_df['20_SMA'].item(), stock_df['50_SMA'].item(), stock_df['200_SMA'].item())
    ABS_Spread = max_SMA - min_SMA
    stock_df['Spread%'] = round((ABS_Spread / stock_df['200_SMA'].item()) * 100,2)

    return stock_df

# function to compute stock attributes
def get_common_features(stock_ids, df_mypf):

  df_prec_dev = pd.DataFrame()
  df_tmp = get_screener_features()
  df_rs = get_relative_strength(stock_ids)

  for stock_id in stock_ids:
      tmp = stock_prec_dev(stock_id)
      tmp = tmp.reset_index()
      df_prec_dev = pd.concat([df_prec_dev, tmp], ignore_index = True)
  df_prec_dev = pd.merge(df_prec_dev, df_mypf, on= 'Symbol')
  df_prec_dev = pd.merge(df_prec_dev, df_tmp, on= 'Symbol', how='left')
  df_prec_dev = pd.merge(df_prec_dev, df_rs, on= 'Symbol', how='left')
  #print(df_prec_dev.columns)
  df_prec_dev['Curr_PE'] = round(df_prec_dev['Close']/df_prec_dev['EPS'],1)
  df_prec_dev['Dev%_PE'] = round((df_prec_dev['Curr_PE'] - df_prec_dev['MedPE'])*100/df_prec_dev['MedPE'],2)
  df_prec_dev['Conviction'] = df_prec_dev['Conviction'] + '-' + df_prec_dev['CapType']
  return df_prec_dev

# function to arrange stock features
def arrange_features(df_stocks, common_cols, diff_cols):
  df_stocks_common = df_stocks[common_cols].drop_duplicates()
  df_stocks_diff = df_stocks[diff_cols]
  df_stocks_diff['Investment'] = df_stocks_diff['AvgCost'] * df_stocks_diff['Shares']
  df_stocks_diff = df_stocks_diff.groupby(['Symbol'])[['Shares', 'Investment']].aggregate(['sum']).reset_index()
  df_stocks_diff.columns = ['Symbol', 'Shares', 'Investment']
  df_stocks_diff['AvgCost'] = round(df_stocks_diff['Investment']/df_stocks_diff['Shares'],2)
  df_stocks = pd.merge(df_stocks_diff, df_stocks_common, on='Symbol')
  return df_stocks

# plot fact distribution across dimension
def plot_pie_chart(df, dimension, fact):
  # grouping the data by category and calculating the sum of fact for each type
  grouped_data = df.groupby(dimension)[fact].sum()

  # sorting the grouped data in descending order
  grouped_data = grouped_data.sort_values(ascending=False)

  # creating a pie chart
  grouped_data.plot.pie(autopct='%1.1f%%', startangle=90, figsize=(6, 6))

  # adding a title and displaying the plot
  plt.title(f'{dimension} {fact} Distribution')
  plt.ylabel('')  # To hide the y-label
  plt.show()

In [7]:
# function to get portfolio features

def get_portfolio_features(df_common_features):

  print_date_time()
  print('-------------------')

  #df_common_features["Target"] = df_common_features["Target"].fillna(df_common_features["Max"])
  df_common_features['NTT'] = np.where(df_common_features['Strategy']== 'NTT', df_common_features["Target"], df_common_features['Max'])
  df_common_features['LTT'] = np.where(df_common_features['Strategy']== 'BTT', df_common_features["Target"], df_common_features['Max'])
  df_common_features['BOL'] = df_common_features['Min']

  tmp_df = df_common_features[df_common_features['Symbol'].isin(mypf_df[mypf_df['InPortfolio'] != 'NA'].Symbol.values)]
  print('qualified stocks: '+str(len(tmp_df['Symbol'].unique())))
  tmp_df1 = tmp_df[tmp_df['LatestQtr'] == 1]
  print('with latest results: '+str(len(tmp_df1['Symbol'].unique())))
  tmp_df1 = tmp_df1[tmp_df1['StarStock'] == 1]
  print('still star stocks: '+str(len(tmp_df1['Symbol'].unique())))
  tmp_df['Investment'] = tmp_df['AvgCost'] * tmp_df['Shares']
  tmp_df['Current'] = round(tmp_df['Close'] * tmp_df['Shares'],0)
  tmp_df['Previous'] = tmp_df['Prev_Close'] * tmp_df['Shares']
  tmp_df['EstimatedST'] = tmp_df['NTT'] * tmp_df['Shares']
  tmp_df['EstimatedLT'] = tmp_df['LTT'] * tmp_df['Shares']
  tmp_df['Current P/L'] = round((tmp_df['Current'] - tmp_df['Investment']),0)
  tmp_df['Today P/L%'] = round((tmp_df['Current'] - tmp_df['Previous'])*100/tmp_df['Previous'],2)
  tmp_df['Current P/L%'] = round((tmp_df['Current'] - tmp_df['Investment'])*100/tmp_df['Investment'],2)
  tmp_df['EstimatedST P/L%'] = round((tmp_df['EstimatedST'] - tmp_df['Investment'])*100/tmp_df['Investment'],2)
  tmp_df['EstimatedLT P/L%'] = round((tmp_df['EstimatedLT'] - tmp_df['Investment'])*100/tmp_df['Investment'],2)
  tmp_df['NTT%'] = round((tmp_df['NTT'] - tmp_df['Close'])*100/tmp_df['Close'],2)
  tmp_df['LTT%'] = round((tmp_df['LTT'] - tmp_df['Close'])*100/tmp_df['Close'],2)
  tmp_df['Gained%'] = round((tmp_df['Close'] - tmp_df['BOL'])*100/tmp_df['BOL'],2)
  investment = round(sum(tmp_df['AvgCost']*tmp_df['Shares']),0)
  current = round(sum(tmp_df['Close']*tmp_df['Shares']),0)
  tmp_df['InitAlloc%'] = round(tmp_df['Investment']*100/investment,2)
  tmp_df['CurrAlloc%'] = round(tmp_df['Current']*100/current,2)
  tmp_df['FTT'] = tmp_df['LTT']
  tmp_df.loc[tmp_df['Strategy'] == 'NTT', 'FTT'] = tmp_df['NTT']
  tmp_df['FTT%'] = tmp_df['LTT%']
  tmp_df.loc[tmp_df['Strategy'] == 'NTT', 'FTT%'] = tmp_df['NTT%']
  tmp_df['FTT Amt'] = round(tmp_df['FTT%'] * tmp_df['Current']/100,0)
  tmp_df['OTT%'] = round((tmp_df['FTT'] - tmp_df['AvgCost'])*100/tmp_df['AvgCost'],2)
  tmp_df['RRR Ind'] = round(tmp_df['Current P/L']/tmp_df['FTT Amt'],2)
  tmp_df['Risk Ind'] = round(tmp_df['Current P/L%']*tmp_df['CurrAlloc%'],0)

  return tmp_df

# function to print portfolio features
def print_portfolio_stats(df_portfolio_features, myinvmt_df):
  from pyxirr import xirr

  total_booked_amt, reserve_amt, cy_booked_amt, py_booked_amt = get_amt()

  dates = myinvmt_df['Date'].values
  dates = np.append(dates, datetime.date.today().strftime('%d-%b-%y'))
  investment = myinvmt_df['Investment'].values
  dates= pd.to_datetime(dates)

  current = round(sum(df_portfolio_features['Close']*df_portfolio_features['Shares']),0) + reserve_amt
  investment_xirr = np.append(investment, current)
  cagr = round(xirr(pd.DataFrame({"dates": dates, "amounts": investment_xirr}))*100,2)

  investment = -sum(investment)
  invested = round(sum(df_portfolio_features['AvgCost']*df_portfolio_features['Shares']),0) + reserve_amt
  previous = round(sum(df_portfolio_features['Prev_Close']*df_portfolio_features['Shares']),0) + reserve_amt
  cy_invested = investment + py_booked_amt

  today_pnl_amount = current-previous
  today_pnl_percentage = round((current-previous)*100/previous,2)

  curr_pnl_amount = current-invested
  curr_pnl_percentage = round((curr_pnl_amount)*100/(cy_invested),2)

  cy_pnl_amount = cy_booked_amt + curr_pnl_amount
  cy_pnl_percentage = round((cy_pnl_amount)*100/cy_invested,2)

  overall_pnl_amount = total_booked_amt + curr_pnl_amount
  overall_pnl_percentage = round((overall_pnl_amount)*100/investment,2)

  estimate_st = round(sum(df_portfolio_features['FTT']*df_portfolio_features['Shares']),0)  + reserve_amt
  est_st_pnl_amount = estimate_st-current
  est_st_pnl_percentage = round((est_st_pnl_amount)*100/current,2)

  estimate_lt = round(sum(df_portfolio_features['LTT']*df_portfolio_features['Shares']),0)  + reserve_amt
  est_lt_pnl_amount = estimate_lt-current
  est_lt_pnl_percentage = round((est_lt_pnl_amount)*100/current,2)

  total_profit = round(sum(df_portfolio_features[df_portfolio_features['Current P/L%'] > 0]['Current']) - sum(df_portfolio_features[df_portfolio_features['Current P/L%'] > 0]['Investment']),0)
  total_loss = round(sum(df_portfolio_features[df_portfolio_features['Current P/L%'] < 0]['Current']) - sum(df_portfolio_features[df_portfolio_features['Current P/L%'] < 0]['Investment']),0)

  cy_booked_percentage = round((cy_booked_amt)*100/current,2)
  py_booked_percentage = round((py_booked_amt)*100/investment,2)
  total_booked_percentage = round((total_booked_amt)*100/investment,2)

  print('-------------------')
  print('Initial Investment: ', format_amt(investment))
  print('CY Investment: ', format_amt(cy_invested))
  print('Reserve: ', format_amt(reserve_amt))
  print('Current: ',  format_amt(current))
  print('-------------------')
  print('Today PnL: '+ '{} ({}%)'.format(format_amt(today_pnl_amount), today_pnl_percentage))
  print('Current PnL: '+ '{} ({}%)'.format(format_amt(curr_pnl_amount), curr_pnl_percentage))
  print('CY Booked + Current PnL: '+ '{} ({}%)'.format(format_amt(cy_pnl_amount), cy_pnl_percentage))
  print('-------------------')
  print('Total profit: ', format_amt(total_profit))
  print('Total loss: ', format_amt(total_loss))
  print('-------------------')
  print('Total Booked + Current PnL: '+ '{} ({}%)'.format(format_amt(overall_pnl_amount), overall_pnl_percentage))
  print('Total Booked PnL: '+ '{} ({}%)'.format(format_amt(total_booked_amt), total_booked_percentage))
  print('Curr Year Booked PnL: '+ '{} ({}%)'.format(format_amt(cy_booked_amt), cy_booked_percentage))
  print('Prev Year Booked PnL: '+ '{} ({}%)'.format(format_amt(py_booked_amt), py_booked_percentage))
  print('===================')
  print('Est FTT: ',  format_amt(estimate_st))
  print('Est FTT PnL: '+ '{} ({}%)'.format(format_amt(est_st_pnl_amount), est_st_pnl_percentage))

  print('===================')
  print('Deployed: ', format_amt(investment))

  print('Current: ', format_amt(current))

  print('CAGR/XIRR %: '+'{}%'.format(cagr))

In [8]:
# get start and end date
start_date, end_date = get_start_end_date()

# get portfolio and prospects data
mypfs_df = get_mypfs_df()
mypps_df = get_mypps_df()
myinvmt_df = get_myinvmt_df()

# merge above datasets
mypf_df = pd.merge(mypfs_df, mypps_df, on="Symbol")

# seggregate dm and sv portfolio
dm_pf = mypf_df[mypf_df['InPortfolio'] == 'DM']
sv_pf = mypf_df[mypf_df['InPortfolio'] == 'SV']

# build portfolio stock dataframe
dm_stocks = get_stock_ids(dm_pf)
sv_stocks = get_stock_ids(sv_pf)
df_stocks = pd.concat([dm_pf,sv_pf], ignore_index = True)

# arrange common and diff stock features
common_cols = ['Symbol', 'Target', 'Criteria', 'Strategy', 'CumlRnk', 'LatestQtr', 'StarStock', 'Conviction', 'Category', 'InFolio', 'XIRR', 'MBQ']
diff_cols = ['Symbol', 'AvgCost', 'Shares']
df_stocks = arrange_features(df_stocks, common_cols, diff_cols)

# get common features
stock_ids = df_stocks['Symbol'].values
df_common_features = get_common_features(stock_ids, df_stocks)

df_common_features.reset_index(drop=True, inplace=True)
df_common_features.drop(['Date'], axis=1, inplace=True)
# get and print portfolio features
df_portfolio_features = get_portfolio_features(df_common_features)

print_portfolio_stats(df_portfolio_features, myinvmt_df)

df = df_portfolio_features
#plot_pie_chart(df, 'CapType', 'Current')
list_ox40n = list(df[df['MBQ'].str.contains('OX40N', na=False)]['Symbol'].values)

Run date time (IST): 2026-03-02 11:01:51
-------------------
qualified stocks: 86
with latest results: 26
still star stocks: 15
-------------------
Initial Investment:  1.33 C
CY Investment:  1.60 C
Reserve:  2.44 L
Current:  1.35 C
-------------------
Today PnL: -2.17 L (-1.58%)
Current PnL: -39.56 L (-24.73%)
CY Booked + Current PnL: -23.88 L (-14.93%)
-------------------
Total profit:  1.25 L
Total loss:  -40.81 L
-------------------
Total Booked + Current PnL: 3.10 L (2.33%)
Total Booked PnL: 42.66 L (32.07%)
Curr Year Booked PnL: 15.68 L (11.63%)
Prev Year Booked PnL: 26.98 L (20.29%)
===================
Est FTT:  2.41 C
Est FTT PnL: 1.06 C (78.72%)
===================
Deployed:  1.33 C
Current:  1.35 C
CAGR/XIRR %: 0.71%

In [9]:
# top 5 near their targets
cols = ['Symbol', 'Today P/L%', 'Current P/L%', 'FTT%', 'OTT%', 'FTT Amt', 'Current P/L', 'Current', 'FTT', 'Dev%_PE', 'RSI_14','Conviction', 'Spread%',  'CumlRnk', 'RRR Ind', 'CurrAlloc%', 'Gained%', 'Criteria', 'Strategy', 'Category']
df_tmp = df_portfolio_features[~df_portfolio_features['Symbol'].isin(['ENRIN','BLUSPRING','DIGITIDE'])]
df_tmp = df_tmp.sort_values(by = 'FTT Amt', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
19,COALINDIA,-0.66,5.90,11.11,17.67,17703.0,8880.0,159340.0,478.51,27.69,56.0,L-LC,11.04,185.0,0.50,1.20,27.91,XY25,ATH,MINING
50,MASFIN,-2.44,-3.11,25.47,21.57,24180.0,-3045.0,94935.0,397.04,-16.44,42.0,H-SC,6.71,167.0,-0.13,0.72,38.54,XR,ATH,FINANCE
77,TTKPRESTIG,-2.18,-33.54,50.60,0.09,33892.0,-33797.0,66980.0,770.00,55.39,27.0,M-SC,11.98,250.0,-1.00,0.51,0.00,OX40N,NTT,DURABLES
51,MEDANTA,-1.97,-4.91,30.49,24.08,36805.0,-6237.0,120713.0,1486.00,-5.52,49.0,X-SC,7.99,87.0,-0.17,0.91,10.56,XY24,NTT,HEALTHCARE
37,ICICIGI,0.08,0.80,18.39,19.34,37096.0,1609.0,201718.0,2252.93,-15.18,49.0,X-MC,1.19,66.0,0.04,1.52,16.87,X40,ATH,INSURANCE

In [10]:
# top 5 today
df_tmp = df_portfolio_features.sort_values(by = 'Today P/L%', ascending=False)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
27,FINCABLES,3.03,19.23,74.38,107.91,130933.0,28388.0,176032.0,1641.55,7.05,78.0,M-SC,6.68,220.0,0.22,1.33,32.44,OX40N,ATH,CABLES
66,SIS,0.97,-29.21,71.29,21.26,56037.0,-32428.0,78604.0,528.00,1847.67,44.0,H-SC,5.88,168.0,-0.58,0.59,8.36,OX40N,NTT,MISC
44,IRCTC,0.87,-30.76,120.89,52.93,226411.0,-83221.0,187287.0,1269.00,-48.71,33.0,H-MC,12.22,119.0,-0.37,1.41,0.87,XY24,BTT,TRAVEL
2,ABBOTINDIA,0.15,-10.87,32.46,18.07,51748.0,-19435.0,159420.0,35195.00,-24.24,43.0,X-MC,11.53,58.0,-0.38,1.20,1.07,X40,ATH,PHARMA
70,SYMPHONY,0.09,-39.27,64.60,-0.03,67147.0,-67199.0,103942.0,1306.00,-51.21,31.0,M-SC,9.37,205.0,-1.00,0.78,0.09,OX40N,NTT,DURABLES

In [11]:
# bottom 5 today
df_tmp = df_portfolio_features.sort_values(by = 'Today P/L%', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
26,EASEMYTRIP,-6.50,-55.52,227.54,45.70,178958.0,-98166.0,78649.0,26.4,-18.31,52.0,M-SC,18.09,204.0,-0.55,0.59,29.58,XY24,NTT,TRAVEL
69,SURYODAY,-5.63,-29.00,73.29,23.03,93183.0,-51928.0,127143.0,216.0,38.16,45.0,H-SC,5.84,166.0,-0.56,0.96,26.15,XR,NTT,BANKS
55,RAJESHEXPO,-4.74,-73.53,278.10,0.07,100964.0,-100872.0,36305.0,518.0,1230.81,26.0,L-SC,10.14,268.0,-1.00,0.27,0.00,OX40N,NTT,JEWELLERY
76,TRIDENT,-4.14,-34.35,95.76,28.51,57996.0,-31690.0,60564.0,48.0,-15.68,36.0,M-SC,9.01,223.0,-0.55,0.46,3.63,XR,NTT,TEXTILES
49,LAOPALA,-3.96,-40.60,134.14,39.09,104470.0,-53224.0,77881.0,464.0,70.57,47.0,H-SC,13.45,154.0,-0.51,0.59,4.15,AR,NTT,CERAMICS

In [12]:
# top 5 to exit based on CumlRnk
df_tmp = df_portfolio_features[~df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])]
df_tmp = df_tmp[(df_tmp['Current P/L%'] > -1) & (df_tmp['Current P/L%'] < 1)].sort_values(by = 'CumlRnk', ascending=False)
df_tmp[cols].head()

Empty DataFrame
Columns: [Symbol, Today P/L%, Current P/L%, FTT%, OTT%, FTT Amt, Current P/L, Current, FTT, Dev%_PE, RSI_14, Conviction, Spread%, CumlRnk, RRR Ind, CurrAlloc%, Gained%, Criteria, Strategy, Category]
Index: []

In [13]:
# OX40N stocks to exit
df_tmp = df_portfolio_features[(df_portfolio_features['Symbol'].isin(list_ox40n))].sort_values(by = 'Current P/L%', ascending=False)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
27,FINCABLES,3.03,19.23,74.38,107.91,130933.0,28388.0,176032.0,1641.55,7.05,78.0,M-SC,6.68,220.0,0.22,1.33,32.44,OX40N,ATH,CABLES
66,SIS,0.97,-29.21,71.29,21.26,56037.0,-32428.0,78604.0,528.00,1847.67,44.0,H-SC,5.88,168.0,-0.58,0.59,8.36,OX40N,NTT,MISC
77,TTKPRESTIG,-2.18,-33.54,50.60,0.09,33892.0,-33797.0,66980.0,770.00,55.39,27.0,M-SC,11.98,250.0,-1.00,0.51,0.00,OX40N,NTT,DURABLES
48,KANSAINER,-2.89,-34.05,72.05,13.47,128147.0,-91809.0,177858.0,340.00,-43.31,33.0,H-SC,13.40,162.0,-0.72,1.34,0.00,XY24,NTT,PAINTS
41,INDIGOPNTS,-2.91,-35.39,54.80,0.02,61806.0,-61775.0,112784.0,1408.00,71.88,22.0,M-SC,12.66,222.0,-1.00,0.85,0.00,OX40N,NTT,PAINTS

In [14]:
# top 5 to book for rotation
df_tmp = df_portfolio_features[(df_portfolio_features['Current P/L%'] > 20) ].sort_values(by = 'CumlRnk', ascending=False)
df_tmp[cols].head()

Empty DataFrame
Columns: [Symbol, Today P/L%, Current P/L%, FTT%, OTT%, FTT Amt, Current P/L, Current, FTT, Dev%_PE, RSI_14, Conviction, Spread%, CumlRnk, RRR Ind, CurrAlloc%, Gained%, Criteria, Strategy, Category]
Index: []

In [15]:
# top 5 to monitor for exit
df_tmp = df_portfolio_features[~df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])]
df_tmp = df_tmp[(df_tmp['Current P/L%'] > 0) ].sort_values(by = 'Dev%_PE', ascending=False)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
19,COALINDIA,-0.66,5.90,11.11,17.67,17703.0,8880.0,159340.0,478.51,27.69,56.0,L-LC,11.04,185.0,0.50,1.20,27.91,XY25,ATH,MINING
27,FINCABLES,3.03,19.23,74.38,107.91,130933.0,28388.0,176032.0,1641.55,7.05,78.0,M-SC,6.68,220.0,0.22,1.33,32.44,OX40N,ATH,CABLES
1,ABB,-1.12,10.18,32.12,45.57,92583.0,26621.0,288240.0,7934.00,-29.24,62.0,H-MC,8.96,125.0,0.29,2.18,28.00,AR,NTT,ELECTRICAL

In [16]:
# top 5 to book for rotation from weak conviction
df_tmp = df_portfolio_features[~df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])]
df_tmp = df_tmp[~df_tmp['Criteria'].isin(['XY25','XY24','X40', 'X40N'])].sort_values(by = 'RRR Ind', ascending=False)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
1,ABB,-1.12,10.18,32.12,45.57,92583.0,26621.0,288240.0,7934.00,-29.24,62.0,H-MC,8.96,125.0,0.29,2.18,28.00,AR,NTT,ELECTRICAL
27,FINCABLES,3.03,19.23,74.38,107.91,130933.0,28388.0,176032.0,1641.55,7.05,78.0,M-SC,6.68,220.0,0.22,1.33,32.44,OX40N,ATH,CABLES
40,INDIAMART,-1.30,-9.58,128.62,106.72,143441.0,-11813.0,111523.0,4810.62,-59.18,36.0,H-SC,8.20,140.0,-0.08,0.84,11.56,AR,ATH,MISC
85,ZYDUSLIFE,-1.97,-4.72,42.35,35.63,84567.0,-9889.0,199685.0,1286.17,-17.12,49.0,H-MC,4.91,120.0,-0.12,1.51,11.17,AR,ATH,PHARMA
50,MASFIN,-2.44,-3.11,25.47,21.57,24180.0,-3045.0,94935.0,397.04,-16.44,42.0,H-SC,6.71,167.0,-0.13,0.72,38.54,XR,ATH,FINANCE

In [17]:
# top 5 to accumulate based on lowest RSI_14
df_tmp = df_portfolio_features[df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])].sort_values(by = 'RSI_14', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
8,AWL,-3.51,-40.86,165.81,57.19,319781.0,-133267.0,192860.0,485.00,-66.22,14.0,X-SC,19.43,81.0,-0.42,1.46,0.00,XY24,NTT,FMCG
9,BAJAJHFL,-3.27,-27.88,115.58,55.47,202787.0,-67834.0,175452.0,181.50,-38.22,23.0,X-MC,17.46,60.0,-0.33,1.32,0.00,X40N,ATH,FINANCE
12,BATAINDIA,-2.43,-50.34,172.26,35.20,110071.0,-64772.0,63898.0,2096.00,-16.25,24.0,X-SC,22.62,91.0,-0.59,0.48,0.00,X40,NTT,FOOTWEAR
43,INFY,-0.27,-11.73,52.09,34.24,143860.0,-36712.0,276176.0,1972.00,-30.70,24.0,X-LC,9.36,3.0,-0.26,2.09,1.65,X40,NTT,IT
53,PGHH,-0.30,-15.20,55.67,32.01,100803.0,-32448.0,181072.0,17616.87,-42.70,26.0,X-MC,9.65,57.0,-0.32,1.37,0.00,X40,ATH,FMCG

In [18]:
# top 5 to accumulate based on Spread and CumlRnk
df_tmp = df_portfolio_features[df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])]
df_tmp = df_tmp[(df_tmp['CumlRnk'] < 100)].sort_values(by = 'Spread%', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
37,ICICIGI,0.08,0.80,18.39,19.34,37096.0,1609.0,201718.0,2252.93,-15.18,49.0,X-MC,1.19,66.0,0.04,1.52,16.87,X40,ATH,INSURANCE
78,UNITDSPR,-0.70,0.73,19.89,20.77,46910.0,1702.0,235846.0,1644.00,-10.63,45.0,X-MC,1.44,64.0,0.04,1.78,7.88,X40N,NTT,BREWERIES
22,DABUR,-1.99,-0.64,44.63,43.70,110003.0,-1591.0,246477.0,735.00,-9.86,46.0,X-MC,1.56,70.0,-0.01,1.86,14.31,XY24,BTT,FMCG
59,RELIANCE,-1.99,-12.31,42.89,25.30,75584.0,-24736.0,176227.0,1952.00,-14.65,35.0,X-LC,2.15,21.0,-0.33,1.33,18.04,XY25,BTT,REFINERIES
5,ANGELONE,-2.66,-90.70,1236.12,24.20,350749.0,-276875.0,28375.0,3033.00,-86.38,32.0,X-SC,2.43,97.0,-0.79,0.21,18.84,X40N,NTT,FINANCE

In [19]:
# top 5 to accumulate based on lowest Gained%
df_tmp = df_portfolio_features[df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])].sort_values(by = 'Gained%', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
3,ACC,-2.08,-34.47,150.51,64.15,234675.0,-82031.0,155920.0,3906.00,-50.74,27.0,X-SC,9.62,85.0,-0.35,1.18,0.0,XY24,BTT,CEMENT
10,BAJAJHLDNG,-2.39,-5.70,37.03,29.22,66388.0,-10843.0,179282.0,14451.52,-12.59,37.0,X-LC,11.85,28.0,-0.16,1.35,0.0,X40,ATH,FINANCE
9,BAJAJHFL,-3.27,-27.88,115.58,55.47,202787.0,-67834.0,175452.0,181.50,-38.22,23.0,X-MC,17.46,60.0,-0.33,1.32,0.0,X40N,ATH,FINANCE
8,AWL,-3.51,-40.86,165.81,57.19,319781.0,-133267.0,192860.0,485.00,-66.22,14.0,X-SC,19.43,81.0,-0.42,1.46,0.0,XY24,NTT,FMCG
12,BATAINDIA,-2.43,-50.34,172.26,35.20,110071.0,-64772.0,63898.0,2096.00,-16.25,24.0,X-SC,22.62,91.0,-0.59,0.48,0.0,X40,NTT,FOOTWEAR

In [20]:
# top 5 to accumulate based on lowest CurrAlloc%
df_tmp = df_portfolio_features[df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])].sort_values(by = 'CurrAlloc%', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
5,ANGELONE,-2.66,-90.70,1236.12,24.20,350749.0,-276875.0,28375.0,3033.0,-86.38,32.0,X-SC,2.43,97.0,-0.79,0.21,18.84,X40N,NTT,FINANCE
54,QUESS,-2.13,-35.46,121.34,42.84,50905.0,-23054.0,41952.0,424.0,-57.58,35.0,X-SC,17.17,80.0,-0.45,0.32,0.91,XY24,NTT,MISC
58,RELAXO,-2.93,-56.24,248.03,52.31,157561.0,-81635.0,63525.0,1176.0,-53.44,30.0,X-SC,15.34,92.0,-0.52,0.48,0.00,X40N,NTT,FOOTWEAR
12,BATAINDIA,-2.43,-50.34,172.26,35.20,110071.0,-64772.0,63898.0,2096.0,-16.25,24.0,X-SC,22.62,91.0,-0.59,0.48,0.00,X40,NTT,FOOTWEAR
51,MEDANTA,-1.97,-4.91,30.49,24.08,36805.0,-6237.0,120713.0,1486.0,-5.52,49.0,X-SC,7.99,87.0,-0.17,0.91,10.56,XY24,NTT,HEALTHCARE

In [21]:
# top 5 to accumulate based on CumlRnk
df_tmp = df_portfolio_features.sort_values(by = 'CumlRnk', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
45,ITC,-0.06,-17.45,44.22,19.06,124172.0,-59360.0,280806.0,452.00,-54.71,39.0,X-LC,17.14,1.0,-0.48,2.12,1.67,X40,NTT,FMCG
73,TCS,-0.77,-24.99,64.74,23.58,210103.0,-108096.0,324533.0,4311.59,-35.10,29.0,X-LC,9.89,2.0,-0.51,2.45,1.69,X40,ATH,IT
43,INFY,-0.27,-11.73,52.09,34.24,143860.0,-36712.0,276176.0,1972.00,-30.70,24.0,X-LC,9.36,3.0,-0.26,2.09,1.65,X40,NTT,IT
75,TMPV,-2.48,-17.08,60.79,33.33,164231.0,-55639.0,270161.0,600.00,-82.53,50.0,X-LC,3.90,4.0,-0.34,2.04,10.45,XY24,NTT,AUTO
34,HCLTECH,-0.54,-10.34,38.11,23.83,82665.0,-25013.0,216911.0,1908.19,-5.71,29.0,X-LC,6.67,8.0,-0.30,1.64,4.07,X40,ATH,IT

In [22]:
# top 5 for average up
df_tmp = df_portfolio_features[(df_portfolio_features['Dev%_200'] > 5)].sort_values(by = 'CurrAlloc%', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
42,INDUSINDBK,-1.31,-30.29,90.63,32.89,48779.0,-23384.0,53822.0,1800.00,-353.50,57.0,L-MC,12.16,258.0,-0.48,0.41,48.22,XR,NTT,BANKS
67,SONACOMS,-2.64,-9.97,54.50,39.09,49633.0,-10089.0,91070.0,804.02,-28.71,51.0,M-MC,11.28,193.0,-0.20,0.69,28.83,AR,ATH,AUTO
19,COALINDIA,-0.66,5.90,11.11,17.67,17703.0,8880.0,159340.0,478.51,27.69,56.0,L-LC,11.04,185.0,0.50,1.20,27.91,XY25,ATH,MINING
7,ATULAUTO,-1.41,-15.70,72.67,45.57,120772.0,-30940.0,166192.0,844.00,3602.70,55.0,M-SC,7.11,248.0,-0.26,1.25,25.77,XY24,NTT,AUTO
65,SIEMENS,-1.84,-9.84,39.21,25.51,65788.0,-18310.0,167785.0,4671.50,40.86,61.0,H-LC,3.84,51.0,-0.28,1.27,23.56,AR,ATH,ELECTRICAL

In [23]:
# top 5 RSP
df_tmp = df_portfolio_features.sort_values(by = 'RSP', ascending=False)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
27,FINCABLES,3.03,19.23,74.38,107.91,130933.0,28388.0,176032.0,1641.55,7.05,78.0,M-SC,6.68,220.0,0.22,1.33,32.44,OX40N,ATH,CABLES
26,EASEMYTRIP,-6.50,-55.52,227.54,45.70,178958.0,-98166.0,78649.0,26.40,-18.31,52.0,M-SC,18.09,204.0,-0.55,0.59,29.58,XY24,NTT,TRAVEL
11,BANDHANBNK,-1.14,-13.46,122.35,92.42,294944.0,-37493.0,241066.0,400.00,106.90,67.0,H-SC,8.63,174.0,-0.13,1.82,32.80,XY24,NTT,BANKS
7,ATULAUTO,-1.41,-15.70,72.67,45.57,120772.0,-30940.0,166192.0,844.00,3602.70,55.0,M-SC,7.11,248.0,-0.26,1.25,25.77,XY24,NTT,AUTO
82,VOLTAS,-2.34,19.28,21.73,45.20,49698.0,36963.0,228705.0,1856.00,36.59,57.0,X-MC,9.73,79.0,0.74,1.73,27.39,XY25,NTT,AC

In [24]:
# Top N allocation
df_tmp = df_portfolio_features.sort_values(by = 'CurrAlloc%', ascending=False)
top_n_values = [10, 25, 50]

sum_df = pd.DataFrame({
    'Top_N': top_n_values,
    'Sum_Alloc%': [df_tmp['CurrAlloc%'].head(n).sum() for n in top_n_values]
})

sum_df

   Top_N  Sum_Alloc%
0     10       20.81
1     25       45.93
2     50       78.00

In [25]:
# market-cap-wise allocation
df_tmp = df_portfolio_features[cols]
df_tmp.groupby(df_tmp['Conviction'].str[-2:])['CurrAlloc%'].sum().sort_values(ascending=False)

Conviction
SC    43.78
MC    30.87
LC    25.34
Name: CurrAlloc%, dtype: float64

In [26]:
# criteria-wise allocation
df_portfolio_features.groupby('Criteria')['CurrAlloc%'].sum().sort_values(ascending=False)

Criteria
XY24     27.44
X40      24.34
X40N     12.94
AR        9.33
XY25      9.10
XR        8.63
OX40N     7.36
SR        0.85
Name: CurrAlloc%, dtype: float64

In [27]:
# conviction-wise allocation
df_portfolio_features.groupby('Conviction')['CurrAlloc%'].sum().sort_values(ascending=False)

Conviction
X-MC    23.25
H-SC    22.63
X-LC    21.82
M-SC    11.00
X-SC     9.46
H-MC     5.10
M-MC     2.11
H-LC     1.27
L-LC     1.20
M-LC     1.05
L-SC     0.69
L-MC     0.41
Name: CurrAlloc%, dtype: float64

In [28]:
# sector-wise stats
df_tmp = df_portfolio_features.groupby('Category')[['CurrAlloc%', 'Current', 'Current P/L', 'FTT Amt']].sum().sort_values(by=['Current', 'Current P/L'], ascending=False)
df_tmp['Current P/L%'] = round(df_tmp['Current P/L'] * 100 / df_tmp['Current'], 2)
df_tmp['FTT%'] = round(df_tmp['FTT Amt'] * 100 / df_tmp['Current'], 2)
cols = ['CurrAlloc%', 'Current P/L%', 'FTT%']
df_tmp[cols].sort_values(by=['CurrAlloc%'], ascending=False)

               CurrAlloc%  Current P/L%    FTT%
Category
FMCG                15.98        -16.63   56.08
IT                  11.69        -41.64  112.62
FINANCE             11.13        -41.57   97.28
MISC                 6.92        -41.63   99.57
ELECTRICAL           6.53         -8.58   48.20
PAINTS               5.11        -36.39   56.65
INSURANCE            5.02         -1.91   36.79
PHARMA               4.25         -4.37   37.22
AUTO                 3.98        -18.33   63.45
BANKS                3.19        -26.73  103.52
AC                   2.32         -4.32   32.61
FOOTWEAR             2.04        -63.41  128.93
TRAVEL               2.00        -68.21  152.43
DURABLES             1.92        -52.34   89.40
BREWERIES            1.78          0.72   19.89
HEALTHCARE           1.71        -36.32   69.96
REALTY               1.44        -16.31   35.42
CERAMICS             1.42        -62.99  112.51
APPARELS             1.42        -26.17   64.20
REFINERIES           1.33        -14.04   42.89
CABLES               1.33         16.13   74.38
JEWELLERY            1.21        -98.24  167.11
MINING               1.20          5.57   11.11
CEMENT               1.18        -52.61  150.51
ENGINEERING          1.17        -56.39  127.92
CHEMICALS            1.04        -91.85  248.37
ENTERTAINMENT        0.80        -83.20  192.46
TEXTILES             0.46        -52.32   95.76
HOTELS               0.42       -102.12  173.41

In [29]:
# money to be made criteria-wise
df_portfolio_features.groupby('Criteria')['FTT Amt'].agg(['sum', 'count']).sort_values(by='sum', ascending=False)

                sum  count
Criteria
XY24      3493387.0     21
X40       1496989.0     15
X40N      1405940.0     10
XR        1348349.0     12
AR        1338480.0     10
OX40N      815471.0     10
XY25       411666.0      6
SR         307026.0      2

In [30]:
# money to be made conviction-wise
df_portfolio_features.groupby('Conviction')['FTT Amt'].agg(['sum', 'count']).sort_values(by='sum', ascending=False)

                  sum  count
Conviction
H-SC        3793980.0     24
X-SC        1551626.0     10
M-SC        1461710.0     14
X-MC        1432325.0     15
X-LC        1383515.0     12
H-MC         403561.0      3
L-SC         198384.0      2
M-LC         152976.0      1
M-MC         106961.0      2
H-LC          65788.0      1
L-MC          48779.0      1
L-LC          17703.0      1

In [31]:
# money to be made criteria and conviction-wise
df_portfolio_features.groupby(['Conviction', 'Criteria'])['FTT Amt'].agg(['sum', 'count']).sort_values(by='sum', ascending=False)

                           sum  count
Conviction Criteria
H-SC       XY24      1281762.0      6
           AR         969381.0      5
           XR         865269.0      7
M-SC       XY24       857312.0      6
X-LC       X40        727707.0      6
X-SC       X40N       714830.0      4
           XY24       642166.0      4
X-MC       X40        574652.0      7
           X40N       455275.0      4
H-SC       OX40N      370542.0      4
M-SC       OX40N      343965.0      5
H-SC       SR         307026.0      2
X-LC       XY24       282705.0      2
           X40N       235835.0      2
H-MC       XY24       226411.0      1
X-MC       XY24       203031.0      2
           XY25       199367.0      2
X-SC       X40        194630.0      2
M-SC       XR         183905.0      2
H-MC       AR         177150.0      2
M-LC       XR         152976.0      1
X-LC       XY25       137268.0      2
L-SC       OX40N      100964.0      1
           XR          97420.0      1
M-SC       AR          76528.0      1
H-LC       AR          65788.0      1
M-MC       XY25        57328.0      1
           AR          49633.0      1
L-MC       XR          48779.0      1
L-LC       XY25        17703.0      1

In [32]:
# notebook execution time

end_time = time.time()
execution_time = round(end_time - start_time, 0)
print(f"Notebook execution time: {execution_time} seconds")

Notebook execution time: 30.0 seconds