<a href="https://colab.research.google.com/github/ankit-rathi/Quantvesting_v2/blob/main/myStocks_Portfolio_Analysis.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
'''
!pip install pandas==2.2.2 -qq
!pip install pyxirr -qq
!pip install ta -qq
!pip install yfinance==0.2.59 -qq
'''

'\n!pip install pandas==2.2.2 -qq\n!pip install pyxirr -qq\n!pip install ta -qq\n!pip install yfinance==0.2.59 -qq\n'

In [2]:
# import libraries

import numpy as np
import pandas as pd
import datetime
import warnings
warnings.filterwarnings('ignore')
import yfinance as yfin
import ta
import matplotlib.pyplot as plt
import requests

In [3]:
# notebook start time
import time
import datetime
import pytz

start_time = time.time()

# function to print date timestamp
def print_date_time():
  tz_NY = pytz.timezone('Asia/Kolkata')
  datetime_NY = datetime.datetime.now(tz_NY)
  print("Run date time (IST):", datetime_NY.strftime("%Y-%m-%d %H:%M:%S"))

In [4]:
# function to get booked and reserved amount
def get_amt():
  # fetch the JSON data from the URL
  url = "https://raw.githubusercontent.com/ankit-rathi/Tradevesting_v1/main/data/myPortfolioAmts.json"
  response = requests.get(url)
  pf_amts = response.json()  # parse the JSON data

  # extract values from the JSON
  py_booked_amt_dm = pf_amts["py_booked_amt_dm"]
  py_booked_amt_sv = pf_amts["py_booked_amt_sv"]
  cy_booked_amt_dm = pf_amts["cy_booked_amt_dm"]
  cy_booked_amt_sv = pf_amts["cy_booked_amt_sv"]
  reserve_amt_dm = pf_amts["reserve_amt_dm"]
  reserve_amt_sv = pf_amts["reserve_amt_sv"]

  # perform calculations
  py_booked_amt = py_booked_amt_dm + py_booked_amt_sv
  cy_booked_amt = cy_booked_amt_dm + cy_booked_amt_sv
  reserve_amt = reserve_amt_dm + reserve_amt_sv
  total_booked_amt = py_booked_amt + cy_booked_amt

  return total_booked_amt, reserve_amt, cy_booked_amt, py_booked_amt

gen_output = 0

In [5]:
# function to format the amount
def format_amt(number):
    abs_number = abs(number)

    if abs_number >= 1_00_00_000:  # Crores
        formatted_amt = f"{number / 1_00_00_000:.2f} C"
    elif abs_number >= 1_00_000:  # Lakhs
        formatted_amt = f"{number / 1_00_000:.2f} L"
    elif abs_number >= 1_000:  # Thousands
        formatted_amt = f"{number / 1_000:.2f} K"
    else:
        formatted_amt = f"{number:.2f}"

    return formatted_amt

# function to set start and end date
def get_start_end_date():
  start_date = (datetime.date.today() + datetime.timedelta(days=-365)).strftime('%Y-%m-%d')
  end_date = (datetime.date.today() + datetime.timedelta(days=1)).strftime('%Y-%m-%d')
  return start_date, end_date

# function to fetch my portfolio csv
def get_mypfs_df():
  mypfs_df = pd.read_csv('https://raw.githubusercontent.com/ankit-rathi/Tradevesting_v1/main/data/myPortfolioStocks.csv')
  return mypfs_df

# function to fetch my prospects csv
def get_mypps_df():
  mypps_df = pd.read_csv('https://raw.githubusercontent.com/ankit-rathi/Tradevesting_v1/main/data/myProspectsScrips.csv')
  return mypps_df

# function to fetch screener data
def get_myscreen_df():
  myscreen_df = pd.read_csv('https://raw.githubusercontent.com/ankit-rathi/Tradevesting_v1/main/data/myScreenerDB.csv')
  return myscreen_df

# function to fetch momentum data
def get_myinvmt_df():
  myinvmt_df = pd.read_csv('https://raw.githubusercontent.com/ankit-rathi/Tradevesting_v1/main/data/myInvestments.csv')
  return myinvmt_df

# function to get the stock ids
def get_stock_ids(df_pf):
  stock_n100 = df_pf['Symbol'].unique()

  exclude = ['CADILAHC','MMTC', 'MASFIN']

  stock_ids = df_pf[~df_pf['Symbol'].isin(exclude) ]['Symbol'].unique()

  #mypf = mypf[mypf.Forecast.notnull()]
  #stock_ids = mypf['Symbol'].unique()

  #stock_ids.sort()
  return stock_ids

# get features from screener data
def get_screener_features():
  myscreen_df = get_myscreen_df()
  cols = ['Symbol', 'EPS', 'MedPE', 'ROCE%', 'ROE%', 'CapType']
  return myscreen_df[cols]

# get relative strength
def get_relative_strength(stock_list):

    # Dictionary to store stock tickers and their corresponding percentage price change
    stock_changes = {}

    # Loop through each stock and fetch its price data
    for stock in stock_list:
        try:
            # Download the stock data for the given date range
            stock_data = yfin.Ticker(stock + '.NS').history(period='1mo', interval='1d')[map(str.title, ['open', 'close', 'low', 'high', 'volume'])]

            # Calculate the percentage change for the stock
            if len(stock_data) > 0:
                start_price = stock_data['Close'].iloc[0]
                end_price = stock_data['Close'].iloc[-1]
                percent_change = round(((end_price - start_price) / start_price) * 100, 2)
                stock_changes[stock] = percent_change
            else:
                stock_changes[stock] = np.nan  # If no data is available, set to NaN

        except Exception as e:
            print(f"Error fetching data for {stock}: {e}")
            stock_changes[stock] = np.nan

    # Create a DataFrame with stock tickers and their percentage changes
    df = pd.DataFrame(list(stock_changes.items()), columns=['Symbol', 'Percent_Change'])

    # Drop any stocks with missing data (NaN values)
    df = df.dropna()

    # Calculate the percentile rank based on percentage change
    df['RSP'] = round(df['Percent_Change'].rank(pct=True) * 100, 2)
    cols = ['Symbol', 'RSP']
    df = df[cols]
    # Sort by percentile rank (optional)
    df = df.sort_values(by='RSP', ascending=False).reset_index(drop=True)

    return df

In [6]:
# function to get stock technicals
def stock_prec_dev(stock_symbol):
    #stock_symbol = 'ULTRACEMCO.NS'
    short_window = 20
    mid_window = 50
    long_window = 200
    moving_avg = 'SMA'

    start = datetime.datetime(*map(int, start_date.split('-')))
    end = datetime.datetime(*map(int, end_date.split('-')))

    stock_df = yfin.Ticker(stock_symbol + '.NS').history(period='max', interval='1d')[map(str.title, ['open', 'close', 'low', 'high', 'volume'])]

    stock_df['Max'] = round(max(stock_df['Close']),2)
    stock_df = stock_df[(stock_df.index <= end_date) & (stock_df.index >= start_date)]
    stock_df['200_SMA'] = round(stock_df['Close'].rolling(window = 200, min_periods = 1).mean(),0)
    stock_df['Dev%_200'] = round((stock_df['Close'] - stock_df['200_SMA'])*100/stock_df['200_SMA'],2)
    stock_df.dropna(axis = 0, inplace = True) # remove any null rows

    stock_df['20_SMA'] = stock_df['Close'].rolling(window=20).mean()
    stock_df['50_SMA'] = stock_df['Close'].rolling(window=50).mean()
    stock_df['Symbol'] = stock_symbol

    stock_df['Close'] = round(stock_df['Close'],2)
    stock_df['Min'] = round(min(stock_df['Close']),2)
    stock_df['RSI_14'] = ta.momentum.RSIIndicator(close=stock_df['Close'], window=14).rsi()
    stock_df['RSI_14'] = round(stock_df['RSI_14'],0)
    stock_df['Prev_Close'] = stock_df['Close'].shift(1)
    stock_df.drop(['Open', 'Low', 'High', 'Volume'], axis=1, inplace=True)
    stock_df = stock_df.tail(1)

    max_SMA = max(stock_df['20_SMA'].item(), stock_df['50_SMA'].item(), stock_df['200_SMA'].item())
    min_SMA = min(stock_df['20_SMA'].item(), stock_df['50_SMA'].item(), stock_df['200_SMA'].item())
    ABS_Spread = max_SMA - min_SMA
    stock_df['Spread%'] = round((ABS_Spread / stock_df['200_SMA'].item()) * 100,2)

    return stock_df

# function to compute stock attributes
def get_common_features(stock_ids, df_mypf):

  df_prec_dev = pd.DataFrame()
  df_tmp = get_screener_features()
  df_rs = get_relative_strength(stock_ids)

  for stock_id in stock_ids:
      tmp = stock_prec_dev(stock_id)
      tmp = tmp.reset_index()
      df_prec_dev = pd.concat([df_prec_dev, tmp], ignore_index = True)
  df_prec_dev = pd.merge(df_prec_dev, df_mypf, on= 'Symbol')
  df_prec_dev = pd.merge(df_prec_dev, df_tmp, on= 'Symbol', how='left')
  df_prec_dev = pd.merge(df_prec_dev, df_rs, on= 'Symbol', how='left')
  #print(df_prec_dev.columns)
  df_prec_dev['Curr_PE'] = round(df_prec_dev['Close']/df_prec_dev['EPS'],1)
  df_prec_dev['Dev%_PE'] = round((df_prec_dev['Curr_PE'] - df_prec_dev['MedPE'])*100/df_prec_dev['MedPE'],2)
  df_prec_dev['Conviction'] = df_prec_dev['Conviction'] + '-' + df_prec_dev['CapType']
  return df_prec_dev

# function to arrange stock features
def arrange_features(df_stocks, common_cols, diff_cols):
  df_stocks_common = df_stocks[common_cols].drop_duplicates()
  df_stocks_diff = df_stocks[diff_cols]
  df_stocks_diff['Investment'] = df_stocks_diff['AvgCost'] * df_stocks_diff['Shares']
  df_stocks_diff = df_stocks_diff.groupby(['Symbol'])[['Shares', 'Investment']].aggregate(['sum']).reset_index()
  df_stocks_diff.columns = ['Symbol', 'Shares', 'Investment']
  df_stocks_diff['AvgCost'] = round(df_stocks_diff['Investment']/df_stocks_diff['Shares'],2)
  df_stocks = pd.merge(df_stocks_diff, df_stocks_common, on='Symbol')
  return df_stocks

# plot fact distribution across dimension
def plot_pie_chart(df, dimension, fact):
  # grouping the data by category and calculating the sum of fact for each type
  grouped_data = df.groupby(dimension)[fact].sum()

  # sorting the grouped data in descending order
  grouped_data = grouped_data.sort_values(ascending=False)

  # creating a pie chart
  grouped_data.plot.pie(autopct='%1.1f%%', startangle=90, figsize=(6, 6))

  # adding a title and displaying the plot
  plt.title(f'{dimension} {fact} Distribution')
  plt.ylabel('')  # To hide the y-label
  plt.show()

In [7]:
# function to get portfolio features

def get_portfolio_features(df_common_features):

  print_date_time()
  print('-------------------')

  #df_common_features["Target"] = df_common_features["Target"].fillna(df_common_features["Max"])
  df_common_features['NTT'] = np.where(df_common_features['Strategy']== 'NTT', df_common_features["Target"], df_common_features['Max'])
  df_common_features['LTT'] = np.where(df_common_features['Strategy']== 'BTT', df_common_features["Target"], df_common_features['Max'])
  df_common_features['BOL'] = df_common_features['Min']

  tmp_df = df_common_features[df_common_features['Symbol'].isin(mypf_df[mypf_df['InPortfolio'] != 'NA'].Symbol.values)]
  print('qualified stocks: '+str(len(tmp_df['Symbol'].unique())))
  tmp_df1 = tmp_df[tmp_df['LatestQtr'] == 1]
  print('with latest results: '+str(len(tmp_df1['Symbol'].unique())))
  tmp_df1 = tmp_df1[tmp_df1['StarStock'] == 1]
  print('still star stocks: '+str(len(tmp_df1['Symbol'].unique())))
  tmp_df['Investment'] = tmp_df['AvgCost'] * tmp_df['Shares']
  tmp_df['Current'] = round(tmp_df['Close'] * tmp_df['Shares'],0)
  tmp_df['Previous'] = tmp_df['Prev_Close'] * tmp_df['Shares']
  tmp_df['EstimatedST'] = tmp_df['NTT'] * tmp_df['Shares']
  tmp_df['EstimatedLT'] = tmp_df['LTT'] * tmp_df['Shares']
  tmp_df['Current P/L'] = round((tmp_df['Current'] - tmp_df['Investment']),0)
  tmp_df['Today P/L%'] = round((tmp_df['Current'] - tmp_df['Previous'])*100/tmp_df['Previous'],2)
  tmp_df['Current P/L%'] = round((tmp_df['Current'] - tmp_df['Investment'])*100/tmp_df['Investment'],2)
  tmp_df['EstimatedST P/L%'] = round((tmp_df['EstimatedST'] - tmp_df['Investment'])*100/tmp_df['Investment'],2)
  tmp_df['EstimatedLT P/L%'] = round((tmp_df['EstimatedLT'] - tmp_df['Investment'])*100/tmp_df['Investment'],2)
  tmp_df['NTT%'] = round((tmp_df['NTT'] - tmp_df['Close'])*100/tmp_df['Close'],2)
  tmp_df['LTT%'] = round((tmp_df['LTT'] - tmp_df['Close'])*100/tmp_df['Close'],2)
  tmp_df['Gained%'] = round((tmp_df['Close'] - tmp_df['BOL'])*100/tmp_df['BOL'],2)
  investment = round(sum(tmp_df['AvgCost']*tmp_df['Shares']),0)
  current = round(sum(tmp_df['Close']*tmp_df['Shares']),0)
  tmp_df['InitAlloc%'] = round(tmp_df['Investment']*100/investment,2)
  tmp_df['CurrAlloc%'] = round(tmp_df['Current']*100/current,2)
  tmp_df['FTT'] = tmp_df['LTT']
  tmp_df.loc[tmp_df['Strategy'] == 'NTT', 'FTT'] = tmp_df['NTT']
  tmp_df['FTT%'] = tmp_df['LTT%']
  tmp_df.loc[tmp_df['Strategy'] == 'NTT', 'FTT%'] = tmp_df['NTT%']
  tmp_df['FTT Amt'] = round(tmp_df['FTT%'] * tmp_df['Current']/100,0)
  tmp_df['OTT%'] = round((tmp_df['FTT'] - tmp_df['AvgCost'])*100/tmp_df['AvgCost'],2)
  tmp_df['RRR Ind'] = round(tmp_df['Current P/L']/tmp_df['FTT Amt'],2)
  tmp_df['Risk Ind'] = round(tmp_df['Current P/L%']*tmp_df['CurrAlloc%'],0)

  return tmp_df

# function to print portfolio features
def print_portfolio_stats(df_portfolio_features, myinvmt_df):
  from pyxirr import xirr

  total_booked_amt, reserve_amt, cy_booked_amt, py_booked_amt = get_amt()

  dates = myinvmt_df['Date'].values
  dates = np.append(dates, datetime.date.today().strftime('%d-%b-%y'))
  investment = myinvmt_df['Investment'].values
  dates= pd.to_datetime(dates)

  current = round(sum(df_portfolio_features['Close']*df_portfolio_features['Shares']),0) + reserve_amt
  investment_xirr = np.append(investment, current)
  cagr = round(xirr(pd.DataFrame({"dates": dates, "amounts": investment_xirr}))*100,2)

  investment = -sum(investment)
  invested = round(sum(df_portfolio_features['AvgCost']*df_portfolio_features['Shares']),0) + reserve_amt
  previous = round(sum(df_portfolio_features['Prev_Close']*df_portfolio_features['Shares']),0) + reserve_amt
  cy_invested = investment + py_booked_amt

  today_pnl_amount = current-previous
  today_pnl_percentage = round((current-previous)*100/previous,2)

  curr_pnl_amount = current-invested
  curr_pnl_percentage = round((curr_pnl_amount)*100/(cy_invested),2)

  cy_pnl_amount = cy_booked_amt + curr_pnl_amount
  cy_pnl_percentage = round((cy_pnl_amount)*100/cy_invested,2)

  overall_pnl_amount = total_booked_amt + curr_pnl_amount
  overall_pnl_percentage = round((overall_pnl_amount)*100/investment,2)

  estimate_st = round(sum(df_portfolio_features['FTT']*df_portfolio_features['Shares']),0)  + reserve_amt
  est_st_pnl_amount = estimate_st-current
  est_st_pnl_percentage = round((est_st_pnl_amount)*100/current,2)

  estimate_lt = round(sum(df_portfolio_features['LTT']*df_portfolio_features['Shares']),0)  + reserve_amt
  est_lt_pnl_amount = estimate_lt-current
  est_lt_pnl_percentage = round((est_lt_pnl_amount)*100/current,2)

  total_profit = round(sum(df_portfolio_features[df_portfolio_features['Current P/L%'] > 0]['Current']) - sum(df_portfolio_features[df_portfolio_features['Current P/L%'] > 0]['Investment']),0)
  total_loss = round(sum(df_portfolio_features[df_portfolio_features['Current P/L%'] < 0]['Current']) - sum(df_portfolio_features[df_portfolio_features['Current P/L%'] < 0]['Investment']),0)

  cy_booked_percentage = round((cy_booked_amt)*100/current,2)
  py_booked_percentage = round((py_booked_amt)*100/investment,2)
  total_booked_percentage = round((total_booked_amt)*100/investment,2)

  print('-------------------')
  print('Initial Investment: ', format_amt(investment))
  print('CY Investment: ', format_amt(cy_invested))
  print('Reserve: ', format_amt(reserve_amt))
  print('Current: ',  format_amt(current))
  print('-------------------')
  print('Today PnL: '+ '{} ({}%)'.format(format_amt(today_pnl_amount), today_pnl_percentage))
  print('Current PnL: '+ '{} ({}%)'.format(format_amt(curr_pnl_amount), curr_pnl_percentage))
  print('CY Booked + Current PnL: '+ '{} ({}%)'.format(format_amt(cy_pnl_amount), cy_pnl_percentage))
  print('-------------------')
  print('Total profit: ', format_amt(total_profit))
  print('Total loss: ', format_amt(total_loss))
  print('-------------------')
  print('Total Booked + Current PnL: '+ '{} ({}%)'.format(format_amt(overall_pnl_amount), overall_pnl_percentage))
  print('Total Booked PnL: '+ '{} ({}%)'.format(format_amt(total_booked_amt), total_booked_percentage))
  print('Curr Year Booked PnL: '+ '{} ({}%)'.format(format_amt(cy_booked_amt), cy_booked_percentage))
  print('Prev Year Booked PnL: '+ '{} ({}%)'.format(format_amt(py_booked_amt), py_booked_percentage))
  print('===================')
  print('Est FTT: ',  format_amt(estimate_st))
  print('Est FTT PnL: '+ '{} ({}%)'.format(format_amt(est_st_pnl_amount), est_st_pnl_percentage))

  print('===================')
  print('Deployed: ', format_amt(investment))

  print('Current: ', format_amt(current))

  print('CAGR/XIRR %: '+'{}%'.format(cagr))

In [8]:
# get start and end date
start_date, end_date = get_start_end_date()

# get portfolio and prospects data
mypfs_df = get_mypfs_df()
mypps_df = get_mypps_df()
myinvmt_df = get_myinvmt_df()

# merge above datasets
mypf_df = pd.merge(mypfs_df, mypps_df, on="Symbol")

# seggregate dm and sv portfolio
dm_pf = mypf_df[mypf_df['InPortfolio'] == 'DM']
sv_pf = mypf_df[mypf_df['InPortfolio'] == 'SV']

# build portfolio stock dataframe
dm_stocks = get_stock_ids(dm_pf)
sv_stocks = get_stock_ids(sv_pf)
df_stocks = pd.concat([dm_pf,sv_pf], ignore_index = True)

# arrange common and diff stock features
common_cols = ['Symbol', 'Target', 'Criteria', 'Strategy', 'CumlRnk', 'LatestQtr', 'StarStock', 'Conviction', 'Category', 'InFolio', 'XIRR', 'MBQ']
diff_cols = ['Symbol', 'AvgCost', 'Shares']
df_stocks = arrange_features(df_stocks, common_cols, diff_cols)

# get common features
stock_ids = df_stocks['Symbol'].values
df_common_features = get_common_features(stock_ids, df_stocks)

df_common_features.reset_index(drop=True, inplace=True)
df_common_features.drop(['Date'], axis=1, inplace=True)
# get and print portfolio features
df_portfolio_features = get_portfolio_features(df_common_features)

print_portfolio_stats(df_portfolio_features, myinvmt_df)

df = df_portfolio_features
#plot_pie_chart(df, 'CapType', 'Current')
list_ox40n = list(df[df['MBQ'].str.contains('OX40N', na=False)]['Symbol'].values)

Run date time (IST): 2026-06-17 12:38:59
-------------------
qualified stocks: 92
with latest results: 31
still star stocks: 20
-------------------
Initial Investment:  1.40 C
CY Investment:  1.82 C
Reserve:  1.49 K
Current:  1.52 C
-------------------
Today PnL: 59.44 K (0.39%)
Current PnL: -31.35 L (-17.19%)
CY Booked + Current PnL: -29.27 L (-16.05%)
-------------------
Total profit:  3.32 L
Total loss:  -34.67 L
-------------------
Total Booked + Current PnL: 13.60 L (9.75%)
Total Booked PnL: 44.95 L (32.22%)
Curr Year Booked PnL: 2.08 L (1.37%)
Prev Year Booked PnL: 42.87 L (30.73%)
===================
Est FTT:  2.55 C
Est FTT PnL: 1.03 C (68.07%)
===================
Deployed:  1.40 C
Current:  1.52 C
CAGR/XIRR %: 3.97%

In [9]:
# top 5 near their targets
cols = ['Symbol', 'Today P/L%', 'Current P/L%', 'FTT%', 'OTT%', 'FTT Amt', 'Current P/L', 'Current', 'FTT', 'Dev%_PE', 'RSI_14','Conviction', 'Spread%',  'CumlRnk', 'RRR Ind', 'CurrAlloc%', 'Gained%', 'Criteria', 'Strategy', 'Category']
df_tmp = df_portfolio_features[~df_portfolio_features['Symbol'].isin(['ENRIN','BLUSPRING','DIGITIDE'])]
df_tmp = df_tmp.sort_values(by = 'FTT Amt', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
59,PIDILITIND,0.17,11.53,6.13,18.37,9647.0,16270.0,157380.0,1670.26,-21.83,74.0,X-LC,3.71,5.0,1.69,1.04,23.57,X40,ATH,CHEMICALS
51,KOTAKBANK,-0.81,8.10,12.04,21.11,18022.0,11212.0,149684.0,453.24,-7.24,66.0,X-LC,5.74,12.0,0.62,0.99,14.47,X40,ATH,BANKS
55,MASFIN,1.46,-2.86,25.15,21.57,23937.0,-2805.0,95175.0,397.04,-16.44,56.0,H-SC,3.51,167.0,-0.12,0.63,13.45,XR,ATH,FINANCE
72,SIS,0.85,-1.93,23.65,21.26,25751.0,-2147.0,108885.0,528.00,2597.93,63.0,H-SC,22.27,168.0,-0.08,0.72,61.90,OX40N,NTT,MISC
83,TTKPRESTIG,0.19,-29.52,42.01,0.09,29839.0,-29749.0,71028.0,770.00,64.78,55.0,M-SC,10.67,250.0,-1.00,0.47,26.48,OX40N,NTT,DURABLES

In [10]:
# top 5 today
df_tmp = df_portfolio_features.sort_values(by = 'Today P/L%', ascending=False)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
86,VALIANTORG,7.32,-36.00,172.12,74.15,180215.0,-58902.0,104703.0,838.00,-288.40,60.0,H-SC,2.73,145.0,-0.33,0.69,55.81,XR,NTT,CHEMICALS
61,RAJESHEXPO,5.00,-82.91,485.64,0.07,113829.0,-113738.0,23439.0,518.00,758.59,38.0,L-SC,34.93,268.0,-1.00,0.15,15.76,OX40N,NTT,JEWELLERY
22,DIXON,4.67,-6.70,47.83,37.92,116377.0,-17484.0,243314.0,18931.72,-60.35,71.0,X-MC,13.36,54.0,-0.15,1.60,32.39,X40N,ATH,IT
88,VOLTAS,3.61,7.61,34.93,45.20,72069.0,14583.0,206325.0,1856.00,23.17,63.0,X-MC,7.35,79.0,0.20,1.36,13.08,XY25,NTT,AC
18,COFFEEDAY,3.42,-41.66,131.88,35.27,87357.0,-47309.0,66240.0,80.00,-55.73,58.0,L-SC,14.83,266.0,-0.54,0.44,63.35,XR,NTT,HOTELS

In [11]:
# bottom 5 today
df_tmp = df_portfolio_features.sort_values(by = 'Today P/L%', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
12,BOSCH-HCIL,-3.51,-43.02,75.47,-0.01,54963.0,-54977.0,72828.0,2282.00,14813.04,38.0,M-SC,8.30,231.0,-1.00,0.48,23.96,OX40N,BTT,AC
19,COLPAL,-2.71,-22.54,80.56,39.86,164342.0,-59365.0,204000.0,3683.41,-6.30,48.0,X-MC,3.17,62.0,-0.36,1.34,15.39,XY25,ATH,FMCG
81,TMPV,-2.31,-12.48,56.05,36.58,174565.0,-44396.0,311445.0,600.00,-81.44,53.0,X-LC,12.30,4.0,-0.25,2.05,29.81,XY24,NTT,AUTO
17,CIPLA,-2.07,8.88,22.56,33.43,37620.0,13594.0,166755.0,1648.14,-15.73,43.0,X-LC,5.70,18.0,0.36,1.10,13.84,X40N,ATH,PHARMA
6,AWL,-1.96,-33.40,150.76,67.02,357775.0,-118995.0,237314.0,485.00,-64.08,51.0,X-SC,14.55,81.0,-0.33,1.56,12.25,XY24,NTT,FMCG

In [12]:
# top 5 to exit based on CumlRnk
df_tmp = df_portfolio_features[~df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])]
df_tmp = df_tmp[(df_tmp['Current P/L%'] > -1) & (df_tmp['Current P/L%'] < 1)].sort_values(by = 'CumlRnk', ascending=False)
df_tmp[cols].head()

Empty DataFrame
Columns: [Symbol, Today P/L%, Current P/L%, FTT%, OTT%, FTT Amt, Current P/L, Current, FTT, Dev%_PE, RSI_14, Conviction, Spread%, CumlRnk, RRR Ind, CurrAlloc%, Gained%, Criteria, Strategy, Category]
Index: []

In [13]:
# OX40N stocks to exit
df_tmp = df_portfolio_features[(df_portfolio_features['Symbol'].isin(list_ox40n))].sort_values(by = 'Current P/L%', ascending=False)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
25,FINCABLES,2.72,37.32,51.41,107.91,104231.0,55101.0,202745.0,1641.55,23.29,57.0,M-SC,23.46,220.0,0.53,1.34,52.53,OX40N,ATH,CABLES
72,SIS,0.85,-1.93,23.65,21.26,25751.0,-2147.0,108885.0,528.00,2597.93,63.0,H-SC,22.27,168.0,-0.08,0.72,61.90,OX40N,NTT,MISC
16,CERA,-0.58,-19.30,53.52,23.89,75975.0,-33947.0,141956.0,9475.00,-22.20,67.0,H-SC,5.10,153.0,-0.45,0.94,36.42,OX40N,NTT,CERAMICS
43,INDIGOPNTS,-0.24,-27.10,37.19,0.02,47328.0,-47298.0,127261.0,1408.00,94.20,63.0,M-SC,10.28,222.0,-1.00,0.84,44.39,OX40N,NTT,PAINTS
50,KANSAINER,-0.78,-28.58,58.88,13.47,113403.0,-77067.0,192600.0,340.00,-38.54,52.0,H-SC,6.17,162.0,-0.68,1.27,34.53,XY24,NTT,PAINTS

In [14]:
# top 5 to book for rotation
df_tmp = df_portfolio_features[(df_portfolio_features['Current P/L%'] > 20) ].sort_values(by = 'CumlRnk', ascending=False)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
25,FINCABLES,2.72,37.32,51.41,107.91,104231.0,55101.0,202745.0,1641.55,23.29,57.0,M-SC,23.46,220.0,0.53,1.34,52.53,OX40N,ATH,CABLES
68,SATIN,2.10,30.92,15.98,51.83,57800.0,85415.0,361699.0,274.00,16.95,61.0,H-SC,40.70,159.0,1.48,2.38,76.20,XY24,NTT,FINANCE

In [15]:
# top 5 to monitor for exit
df_tmp = df_portfolio_features[~df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])]
df_tmp = df_tmp[(df_tmp['Current P/L%'] > 0) ].sort_values(by = 'Dev%_PE', ascending=False)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
9,BANDHANBNK,-1.21,3.00,86.82,92.42,249093.0,8348.0,286907.0,400.00,146.41,62.0,H-SC,22.31,174.0,0.03,1.89,58.05,XY24,NTT,BANKS
74,STARHEALTH,2.83,3.82,41.85,47.26,122142.0,10733.0,291856.0,761.00,63.89,62.0,H-SC,10.23,173.0,0.09,1.92,28.13,XY24,NTT,INSURANCE
25,FINCABLES,2.72,37.32,51.41,107.91,104231.0,55101.0,202745.0,1641.55,23.29,57.0,M-SC,23.46,220.0,0.53,1.34,52.53,OX40N,ATH,CABLES
68,SATIN,2.10,30.92,15.98,51.83,57800.0,85415.0,361699.0,274.00,16.95,61.0,H-SC,40.70,159.0,1.48,2.38,76.20,XY24,NTT,FINANCE
91,ZYDUSLIFE,-1.61,11.92,21.19,35.63,49701.0,24973.0,234547.0,1286.17,-2.70,53.0,H-MC,13.35,120.0,0.50,1.55,23.32,AR,ATH,PHARMA

In [16]:
# top 5 to book for rotation from weak conviction
df_tmp = df_portfolio_features[~df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])]
df_tmp = df_tmp[~df_tmp['Criteria'].isin(['XY25','XY24','X40', 'X40N'])].sort_values(by = 'RRR Ind', ascending=False)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
25,FINCABLES,2.72,37.32,51.41,107.91,104231.0,55101.0,202745.0,1641.55,23.29,57.0,M-SC,23.46,220.0,0.53,1.34,52.53,OX40N,ATH,CABLES
91,ZYDUSLIFE,-1.61,11.92,21.19,35.63,49701.0,24973.0,234547.0,1286.17,-2.70,53.0,H-MC,13.35,120.0,0.50,1.55,23.32,AR,ATH,PHARMA
73,SONACOMS,0.23,3.81,33.99,39.09,35693.0,3850.0,105009.0,804.02,-17.77,54.0,M-MC,18.54,193.0,0.11,0.69,48.55,AR,ATH,AUTO
75,SURYODAY,-0.42,-1.57,24.99,23.03,44049.0,-2805.0,176266.0,216.00,92.98,60.0,H-SC,17.96,166.0,-0.06,1.16,48.41,XR,NTT,BANKS
72,SIS,0.85,-1.93,23.65,21.26,25751.0,-2147.0,108885.0,528.00,2597.93,63.0,H-SC,22.27,168.0,-0.08,0.72,61.90,OX40N,NTT,MISC

In [17]:
# top 5 to accumulate based on lowest RSI_14
df_tmp = df_portfolio_features[df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])].sort_values(by = 'RSI_14', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
58,PGHH,-1.17,-32.78,96.38,32.01,138340.0,-69984.0,143536.0,17616.87,-54.51,32.0,X-MC,19.55,57.0,-0.51,0.95,0.00,X40,ATH,FMCG
1,ABBOTINDIA,-0.33,-12.73,35.29,18.07,55084.0,-22765.0,156090.0,35195.00,-25.68,42.0,X-MC,5.91,58.0,-0.41,1.03,3.32,X40,ATH,PHARMA
27,GLAXO,-1.26,-12.69,55.41,35.69,96413.0,-25284.0,174000.0,3380.16,-33.30,43.0,X-MC,10.28,56.0,-0.26,1.15,3.41,X40,ATH,PHARMA
17,CIPLA,-2.07,8.88,22.56,33.43,37620.0,13594.0,166755.0,1648.14,-15.73,43.0,X-LC,5.70,18.0,0.36,1.10,13.84,X40N,ATH,PHARMA
20,DABUR,-1.27,-15.95,70.97,43.70,147974.0,-39566.0,208502.0,735.00,-23.72,45.0,X-MC,11.09,70.0,-0.27,1.37,4.74,XY24,BTT,FMCG

In [18]:
# top 5 to accumulate based on Spread and CumlRnk
df_tmp = df_portfolio_features[df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])]
df_tmp = df_tmp[(df_tmp['CumlRnk'] < 100)].sort_values(by = 'Spread%', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
49,JSWINFRA,1.05,1.08,15.19,16.43,34050.0,2385.0,224159.0,342.00,-13.36,64.0,X-MC,1.43,61.0,0.07,1.48,26.71,X40N,NTT,REALTY
57,PAGEIND,0.24,2.14,30.79,33.59,84402.0,5741.0,274120.0,51217.29,-26.77,60.0,X-MC,3.00,55.0,0.07,1.81,30.18,X40,ATH,APPARELS
19,COLPAL,-2.71,-22.54,80.56,39.86,164342.0,-59365.0,204000.0,3683.41,-6.30,48.0,X-MC,3.17,62.0,-0.36,1.34,15.39,XY25,ATH,FMCG
11,BERGEPAINT,0.81,-5.16,32.13,25.32,78545.0,-13290.0,244459.0,680.00,-10.37,56.0,X-MC,3.22,68.0,-0.17,1.61,27.23,XY24,NTT,PAINTS
15,CAMS,1.86,5.73,17.73,24.48,47214.0,14438.0,266294.0,950.00,1.42,62.0,X-SC,3.35,89.0,0.31,1.75,29.64,X40N,NTT,MISC

In [19]:
# top 5 to accumulate based on lowest Gained%
df_tmp = df_portfolio_features[df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])].sort_values(by = 'Gained%', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
58,PGHH,-1.17,-32.78,96.38,32.01,138340.0,-69984.0,143536.0,17616.87,-54.51,32.0,X-MC,19.55,57.0,-0.51,0.95,0.00,X40,ATH,FMCG
1,ABBOTINDIA,-0.33,-12.73,35.29,18.07,55084.0,-22765.0,156090.0,35195.00,-25.68,42.0,X-MC,5.91,58.0,-0.41,1.03,3.32,X40,ATH,PHARMA
27,GLAXO,-1.26,-12.69,55.41,35.69,96413.0,-25284.0,174000.0,3380.16,-33.30,43.0,X-MC,10.28,56.0,-0.26,1.15,3.41,X40,ATH,PHARMA
79,TCS,0.77,-34.95,91.96,24.88,277145.0,-161897.0,301376.0,4253.91,-44.94,46.0,X-LC,18.93,2.0,-0.58,1.99,3.76,X40,ATH,IT
28,GODREJCP,-1.25,-8.57,43.80,31.47,59512.0,-12741.0,135873.0,1469.04,-3.82,48.0,X-LC,9.52,32.0,-0.21,0.90,4.25,X40N,ATH,FMCG

In [20]:
# top 5 to accumulate based on lowest CurrAlloc%
df_tmp = df_portfolio_features[df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])].sort_values(by = 'CurrAlloc%', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
10,BATAINDIA,-0.04,-56.23,208.87,35.20,117644.0,-72346.0,56324.0,2096.00,-26.21,48.0,X-SC,25.14,91.0,-0.61,0.37,11.70,X40,NTT,FOOTWEAR
64,RELAXO,3.06,-53.17,225.22,52.31,153107.0,-77179.0,67981.0,1176.00,-50.15,68.0,X-SC,17.67,92.0,-0.50,0.45,52.00,X40N,NTT,FOOTWEAR
60,QUESS,0.15,2.61,69.47,73.90,76127.0,2790.0,109583.0,424.00,-44.90,79.0,X-SC,6.49,80.0,0.04,0.72,49.39,XY24,NTT,MISC
28,GODREJCP,-1.25,-8.57,43.80,31.47,59512.0,-12741.0,135873.0,1469.04,-3.82,48.0,X-LC,9.52,32.0,-0.21,0.90,4.25,X40N,ATH,FMCG
53,M&M,-0.38,1.43,21.64,23.38,30441.0,1989.0,140670.0,3802.40,-14.09,55.0,X-LC,10.51,25.0,0.07,0.93,6.65,X40N,ATH,AUTO

In [21]:
# top 5 to accumulate based on CumlRnk
df_tmp = df_portfolio_features.sort_values(by = 'CumlRnk', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
47,ITC,-0.45,-23.52,55.67,19.06,144828.0,-80012.0,260154.0,452.00,-57.95,52.0,X-LC,15.16,1.0,-0.55,1.71,4.82,X40,NTT,FMCG
79,TCS,0.77,-34.95,91.96,24.88,277145.0,-161897.0,301376.0,4253.91,-44.94,46.0,X-LC,18.93,2.0,-0.58,1.99,3.76,X40,ATH,IT
45,INFY,0.95,-21.41,70.81,34.24,174127.0,-66980.0,245908.0,1972.00,-38.32,50.0,X-LC,16.57,3.0,-0.38,1.62,7.71,X40,NTT,IT
81,TMPV,-2.31,-12.48,56.05,36.58,174565.0,-44396.0,311445.0,600.00,-81.44,53.0,X-LC,12.30,4.0,-0.25,2.05,29.81,XY24,NTT,AUTO
59,PIDILITIND,0.17,11.53,6.13,18.37,9647.0,16270.0,157380.0,1670.26,-21.83,74.0,X-LC,3.71,5.0,1.69,1.04,23.57,X40,ATH,CHEMICALS

In [22]:
# top 5 for average up
df_tmp = df_portfolio_features[(df_portfolio_features['Dev%_200'] > 5)].sort_values(by = 'CurrAlloc%', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
44,INDUSINDBK,0.88,-31.03,92.69,32.89,49355.0,-23960.0,53247.0,1800.00,-350.70,58.0,L-MC,7.47,258.0,-0.49,0.35,31.06,XR,NTT,BANKS
3,ALKYLAMINE,1.33,-22.82,150.89,93.63,117573.0,-23043.0,77920.0,4546.37,-17.40,57.0,H-SC,7.38,142.0,-0.20,0.51,47.13,SR,ATH,CHEMICALS
86,VALIANTORG,7.32,-36.00,172.12,74.15,180215.0,-58902.0,104703.0,838.00,-288.40,60.0,H-SC,2.73,145.0,-0.33,0.69,55.81,XR,NTT,CHEMICALS
73,SONACOMS,0.23,3.81,33.99,39.09,35693.0,3850.0,105009.0,804.02,-17.77,54.0,M-MC,18.54,193.0,0.11,0.69,48.55,AR,ATH,AUTO
72,SIS,0.85,-1.93,23.65,21.26,25751.0,-2147.0,108885.0,528.00,2597.93,63.0,H-SC,22.27,168.0,-0.08,0.72,61.90,OX40N,NTT,MISC

In [23]:
# top 5 RSP
df_tmp = df_portfolio_features.sort_values(by = 'RSP', ascending=False)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
18,COFFEEDAY,3.42,-41.66,131.88,35.27,87357.0,-47309.0,66240.0,80.00,-55.73,58.0,L-SC,14.83,266.0,-0.54,0.44,63.35,XR,NTT,HOTELS
37,HONAUT,-0.14,-5.18,59.58,51.31,108942.0,-9988.0,182850.0,58357.33,-21.16,65.0,X-SC,9.28,90.0,-0.09,1.20,38.92,X40N,ATH,ELECTRICAL
64,RELAXO,3.06,-53.17,225.22,52.31,153107.0,-77179.0,67981.0,1176.00,-50.15,68.0,X-SC,17.67,92.0,-0.50,0.45,52.00,X40N,NTT,FOOTWEAR
60,QUESS,0.15,2.61,69.47,73.90,76127.0,2790.0,109583.0,424.00,-44.90,79.0,X-SC,6.49,80.0,0.04,0.72,49.39,XY24,NTT,MISC
80,TITAGARH,1.68,-14.38,70.21,45.74,145584.0,-34822.0,207355.0,1548.00,14.12,68.0,H-SC,5.43,175.0,-0.24,1.37,58.21,XY24,NTT,ENGINEERING

In [24]:
# Top N allocation
df_tmp = df_portfolio_features.sort_values(by = 'CurrAlloc%', ascending=False)
top_n_values = [10, 25, 50]

sum_df = pd.DataFrame({
    'Top_N': top_n_values,
    'Sum_Alloc%': [df_tmp['CurrAlloc%'].head(n).sum() for n in top_n_values]
})

sum_df

   Top_N  Sum_Alloc%
0     10       19.65
1     25       42.87
2     50       72.78

In [25]:
# market-cap-wise allocation
df_tmp = df_portfolio_features[cols]
df_tmp.groupby(df_tmp['Conviction'].str[-2:])['CurrAlloc%'].sum().sort_values(ascending=False)

Conviction
SC    43.32
LC    31.18
MC    25.52
Name: CurrAlloc%, dtype: float64

In [26]:
# criteria-wise allocation
df_portfolio_features.groupby('Criteria')['CurrAlloc%'].sum().sort_values(ascending=False)

Criteria
XY24     27.80
X40      24.81
X40N     17.30
XR        9.00
OX40N     6.92
AR        6.76
XY25      6.56
SR        0.87
Name: CurrAlloc%, dtype: float64

In [27]:
# conviction-wise allocation
df_portfolio_features.groupby('Conviction')['CurrAlloc%'].sum().sort_values(ascending=False)

Conviction
X-LC    29.13
H-SC    22.83
X-MC    20.52
M-SC     9.98
X-SC     9.92
H-MC     2.67
M-MC     1.98
H-LC     1.21
M-LC     0.84
L-SC     0.59
L-MC     0.35
Name: CurrAlloc%, dtype: float64

In [28]:
# sector-wise stats
df_tmp = df_portfolio_features.groupby('Category')[['CurrAlloc%', 'Current', 'Current P/L', 'FTT Amt']].sum().sort_values(by=['Current', 'Current P/L'], ascending=False)
df_tmp['Current P/L%'] = round(df_tmp['Current P/L'] * 100 / df_tmp['Current'], 2)
df_tmp['FTT%'] = round(df_tmp['FTT Amt'] * 100 / df_tmp['Current'], 2)
cols = ['CurrAlloc%', 'Current P/L%', 'FTT%']
df_tmp[cols].sort_values(by=['CurrAlloc%'], ascending=False)

               CurrAlloc%  Current P/L%    FTT%
Category
FMCG                14.81        -17.70   58.99
FINANCE             10.91        -11.32   59.74
IT                  10.10        -46.67  120.00
MISC                 7.21        -22.61   75.87
AUTO                 6.77         -6.47   46.39
BANKS                5.85         -2.29   49.59
PAINTS               5.56        -16.78   37.06
INSURANCE            5.18         -5.29   40.89
PHARMA               4.83         -1.30   32.65
ELECTRICAL           4.06        -14.53   54.94
CHEMICALS            2.24        -19.32   90.42
HEALTHCARE           2.03        -16.07   46.36
AC                   1.84        -14.47   45.51
APPARELS             1.81          2.09   30.79
FOOTWEAR             1.70        -71.72  140.57
TRAVEL               1.65        -78.61  168.04
DURABLES             1.54        -65.19  105.38
REALTY               1.48          1.06   15.19
BREWERIES            1.47         -5.20   27.05
CERAMICS             1.41        -43.60   87.23
ENGINEERING          1.37        -16.79   70.21
CABLES               1.34         27.18   51.41
REFINERIES           1.13        -17.30   46.98
JEWELLERY            1.07        -96.54  164.82
CEMENT               1.06        -65.93  190.06
ENTERTAINMENT        0.75        -69.56  170.69
HOTELS               0.44        -71.42  131.88
TEXTILES             0.41        -49.58   92.23

In [29]:
# money to be made criteria-wise
df_portfolio_features.groupby('Criteria')['FTT Amt'].agg(['sum', 'count']).sort_values(by='sum', ascending=False)

                sum  count
Criteria
XY24      3376582.0     21
X40       1920585.0     19
XR        1315624.0     13
AR        1157987.0      9
X40N      1097103.0     13
OX40N      741138.0     10
XY25       438524.0      5
SR         286652.0      2

In [30]:
# money to be made conviction-wise
df_portfolio_features.groupby('Conviction')['FTT Amt'].agg(['sum', 'count']).sort_values(by='sum', ascending=False)

                  sum  count
Conviction
H-SC        3318860.0     24
X-LC        1868555.0     21
X-MC        1603567.0     15
M-SC        1404256.0     14
X-SC        1296345.0      9
H-MC         293936.0      2
L-SC         201186.0      2
M-LC         163723.0      1
M-MC          84423.0      2
H-LC          49989.0      1
L-MC          49355.0      1

In [31]:
# money to be made criteria and conviction-wise
df_portfolio_features.groupby(['Conviction', 'Criteria'])['FTT Amt'].agg(['sum', 'count']).sort_values(by='sum', ascending=False)

                           sum  count
Conviction Criteria
X-LC       X40       1013174.0     10
H-SC       XY24       990873.0      6
           AR         949278.0      5
M-SC       XY24       820832.0      6
H-SC       XR         781933.0      7
X-SC       XY24       776261.0      4
X-MC       X40        696590.0      7
           X40N       444047.0      4
X-LC       X40N       343793.0      6
           XY24       317862.0      2
M-SC       OX40N      317185.0      5
H-SC       OX40N      310124.0      4
X-SC       X40N       309263.0      3
H-SC       SR         286652.0      2
H-MC       XY24       244235.0      1
X-MC       XY25       236411.0      2
           XY24       226519.0      2
X-SC       X40        210821.0      2
M-SC       XR         192913.0      2
M-LC       XR         163723.0      1
X-LC       XY25       153383.0      2
L-SC       OX40N      113829.0      1
           XR          87357.0      1
M-SC       AR          73326.0      1
H-LC       AR          49989.0      1
H-MC       AR          49701.0      1
L-MC       XR          49355.0      1
M-MC       XY25        48730.0      1
X-LC       XR          40343.0      1
M-MC       AR          35693.0      1

In [32]:
# notebook execution time

end_time = time.time()
execution_time = round(end_time - start_time, 0)
print(f"Notebook execution time: {execution_time} seconds")

Notebook execution time: 40.0 seconds