<a href="https://colab.research.google.com/github/ankit-rathi/Quantvesting_v2/blob/main/myStocks_Portfolio_Analysis.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
'''
!pip install pandas==2.2.2 -qq
!pip install pyxirr -qq
!pip install ta -qq
!pip install yfinance==0.2.59 -qq
'''

'\n!pip install pandas==2.2.2 -qq\n!pip install pyxirr -qq\n!pip install ta -qq\n!pip install yfinance==0.2.59 -qq\n'

In [2]:
# import libraries

import numpy as np
import pandas as pd
import datetime
import warnings
warnings.filterwarnings('ignore')
import yfinance as yfin
import ta
import matplotlib.pyplot as plt
import requests

In [3]:
# notebook start time
import time
import datetime
import pytz

start_time = time.time()

# function to print date timestamp
def print_date_time():
  tz_NY = pytz.timezone('Asia/Kolkata')
  datetime_NY = datetime.datetime.now(tz_NY)
  print("Run date time (IST):", datetime_NY.strftime("%Y-%m-%d %H:%M:%S"))

In [4]:
# function to get booked and reserved amount
def get_amt():
  # fetch the JSON data from the URL
  url = "https://raw.githubusercontent.com/ankit-rathi/Tradevesting_v1/main/data/myPortfolioAmts.json"
  response = requests.get(url)
  pf_amts = response.json()  # parse the JSON data

  # extract values from the JSON
  py_booked_amt_dm = pf_amts["py_booked_amt_dm"]
  py_booked_amt_sv = pf_amts["py_booked_amt_sv"]
  cy_booked_amt_dm = pf_amts["cy_booked_amt_dm"]
  cy_booked_amt_sv = pf_amts["cy_booked_amt_sv"]
  reserve_amt_dm = pf_amts["reserve_amt_dm"]
  reserve_amt_sv = pf_amts["reserve_amt_sv"]

  # perform calculations
  py_booked_amt = py_booked_amt_dm + py_booked_amt_sv
  cy_booked_amt = cy_booked_amt_dm + cy_booked_amt_sv
  reserve_amt = reserve_amt_dm + reserve_amt_sv
  total_booked_amt = py_booked_amt + cy_booked_amt

  return total_booked_amt, reserve_amt, cy_booked_amt, py_booked_amt

gen_output = 0

In [5]:
# function to format the amount
def format_amt(number):
    abs_number = abs(number)

    if abs_number >= 1_00_00_000:  # Crores
        formatted_amt = f"{number / 1_00_00_000:.2f} C"
    elif abs_number >= 1_00_000:  # Lakhs
        formatted_amt = f"{number / 1_00_000:.2f} L"
    elif abs_number >= 1_000:  # Thousands
        formatted_amt = f"{number / 1_000:.2f} K"
    else:
        formatted_amt = f"{number:.2f}"

    return formatted_amt

# function to set start and end date
def get_start_end_date():
  start_date = (datetime.date.today() + datetime.timedelta(days=-365)).strftime('%Y-%m-%d')
  end_date = (datetime.date.today() + datetime.timedelta(days=1)).strftime('%Y-%m-%d')
  return start_date, end_date

# function to fetch my portfolio csv
def get_mypfs_df():
  mypfs_df = pd.read_csv('https://raw.githubusercontent.com/ankit-rathi/Tradevesting_v1/main/data/myPortfolioStocks.csv')
  return mypfs_df

# function to fetch my prospects csv
def get_mypps_df():
  mypps_df = pd.read_csv('https://raw.githubusercontent.com/ankit-rathi/Tradevesting_v1/main/data/myProspectsScrips.csv')
  return mypps_df

# function to fetch screener data
def get_myscreen_df():
  myscreen_df = pd.read_csv('https://raw.githubusercontent.com/ankit-rathi/Tradevesting_v1/main/data/myScreenerDB.csv')
  return myscreen_df

# function to fetch momentum data
def get_myinvmt_df():
  myinvmt_df = pd.read_csv('https://raw.githubusercontent.com/ankit-rathi/Tradevesting_v1/main/data/myInvestments.csv')
  return myinvmt_df

# function to get the stock ids
def get_stock_ids(df_pf):
  stock_n100 = df_pf['Symbol'].unique()

  exclude = ['CADILAHC','MMTC', 'MASFIN']

  stock_ids = df_pf[~df_pf['Symbol'].isin(exclude) ]['Symbol'].unique()

  #mypf = mypf[mypf.Forecast.notnull()]
  #stock_ids = mypf['Symbol'].unique()

  #stock_ids.sort()
  return stock_ids

# get features from screener data
def get_screener_features():
  myscreen_df = get_myscreen_df()
  cols = ['Symbol', 'EPS', 'MedPE', 'ROCE%', 'ROE%', 'CapType']
  return myscreen_df[cols]

# get relative strength
def get_relative_strength(stock_list):

    # Dictionary to store stock tickers and their corresponding percentage price change
    stock_changes = {}

    # Loop through each stock and fetch its price data
    for stock in stock_list:
        try:
            # Download the stock data for the given date range
            stock_data = yfin.Ticker(stock + '.NS').history(period='1mo', interval='1d')[map(str.title, ['open', 'close', 'low', 'high', 'volume'])]

            # Calculate the percentage change for the stock
            if len(stock_data) > 0:
                start_price = stock_data['Close'].iloc[0]
                end_price = stock_data['Close'].iloc[-1]
                percent_change = round(((end_price - start_price) / start_price) * 100, 2)
                stock_changes[stock] = percent_change
            else:
                stock_changes[stock] = np.nan  # If no data is available, set to NaN

        except Exception as e:
            print(f"Error fetching data for {stock}: {e}")
            stock_changes[stock] = np.nan

    # Create a DataFrame with stock tickers and their percentage changes
    df = pd.DataFrame(list(stock_changes.items()), columns=['Symbol', 'Percent_Change'])

    # Drop any stocks with missing data (NaN values)
    df = df.dropna()

    # Calculate the percentile rank based on percentage change
    df['RSP'] = round(df['Percent_Change'].rank(pct=True) * 100, 2)
    cols = ['Symbol', 'RSP']
    df = df[cols]
    # Sort by percentile rank (optional)
    df = df.sort_values(by='RSP', ascending=False).reset_index(drop=True)

    return df

In [6]:
# function to get stock technicals
def stock_prec_dev(stock_symbol):
    #stock_symbol = 'ULTRACEMCO.NS'
    short_window = 20
    mid_window = 50
    long_window = 200
    moving_avg = 'SMA'

    start = datetime.datetime(*map(int, start_date.split('-')))
    end = datetime.datetime(*map(int, end_date.split('-')))

    stock_df = yfin.Ticker(stock_symbol + '.NS').history(period='max', interval='1d')[map(str.title, ['open', 'close', 'low', 'high', 'volume'])]

    stock_df['Max'] = round(max(stock_df['Close']),2)
    stock_df = stock_df[(stock_df.index <= end_date) & (stock_df.index >= start_date)]
    stock_df['200_SMA'] = round(stock_df['Close'].rolling(window = 200, min_periods = 1).mean(),0)
    stock_df['Dev%_200'] = round((stock_df['Close'] - stock_df['200_SMA'])*100/stock_df['200_SMA'],2)
    stock_df.dropna(axis = 0, inplace = True) # remove any null rows

    stock_df['20_SMA'] = stock_df['Close'].rolling(window=20).mean()
    stock_df['50_SMA'] = stock_df['Close'].rolling(window=50).mean()
    stock_df['Symbol'] = stock_symbol

    stock_df['Close'] = round(stock_df['Close'],2)
    stock_df['Min'] = round(min(stock_df['Close']),2)
    stock_df['RSI_14'] = ta.momentum.RSIIndicator(close=stock_df['Close'], window=14).rsi()
    stock_df['RSI_14'] = round(stock_df['RSI_14'],0)
    stock_df['Prev_Close'] = stock_df['Close'].shift(1)
    stock_df.drop(['Open', 'Low', 'High', 'Volume'], axis=1, inplace=True)
    stock_df = stock_df.tail(1)

    max_SMA = max(stock_df['20_SMA'].item(), stock_df['50_SMA'].item(), stock_df['200_SMA'].item())
    min_SMA = min(stock_df['20_SMA'].item(), stock_df['50_SMA'].item(), stock_df['200_SMA'].item())
    ABS_Spread = max_SMA - min_SMA
    stock_df['Spread%'] = round((ABS_Spread / stock_df['200_SMA'].item()) * 100,2)

    return stock_df

# function to compute stock attributes
def get_common_features(stock_ids, df_mypf):

  df_prec_dev = pd.DataFrame()
  df_tmp = get_screener_features()
  df_rs = get_relative_strength(stock_ids)

  for stock_id in stock_ids:
      tmp = stock_prec_dev(stock_id)
      tmp = tmp.reset_index()
      df_prec_dev = pd.concat([df_prec_dev, tmp], ignore_index = True)
  df_prec_dev = pd.merge(df_prec_dev, df_mypf, on= 'Symbol')
  df_prec_dev = pd.merge(df_prec_dev, df_tmp, on= 'Symbol', how='left')
  df_prec_dev = pd.merge(df_prec_dev, df_rs, on= 'Symbol', how='left')
  #print(df_prec_dev.columns)
  df_prec_dev['Curr_PE'] = round(df_prec_dev['Close']/df_prec_dev['EPS'],1)
  df_prec_dev['Dev%_PE'] = round((df_prec_dev['Curr_PE'] - df_prec_dev['MedPE'])*100/df_prec_dev['MedPE'],2)
  df_prec_dev['Conviction'] = df_prec_dev['Conviction'] + '-' + df_prec_dev['CapType']
  return df_prec_dev

# function to arrange stock features
def arrange_features(df_stocks, common_cols, diff_cols):
  df_stocks_common = df_stocks[common_cols].drop_duplicates()
  df_stocks_diff = df_stocks[diff_cols]
  df_stocks_diff['Investment'] = df_stocks_diff['AvgCost'] * df_stocks_diff['Shares']
  df_stocks_diff = df_stocks_diff.groupby(['Symbol'])[['Shares', 'Investment']].aggregate(['sum']).reset_index()
  df_stocks_diff.columns = ['Symbol', 'Shares', 'Investment']
  df_stocks_diff['AvgCost'] = round(df_stocks_diff['Investment']/df_stocks_diff['Shares'],2)
  df_stocks = pd.merge(df_stocks_diff, df_stocks_common, on='Symbol')
  return df_stocks

# plot fact distribution across dimension
def plot_pie_chart(df, dimension, fact):
  # grouping the data by category and calculating the sum of fact for each type
  grouped_data = df.groupby(dimension)[fact].sum()

  # sorting the grouped data in descending order
  grouped_data = grouped_data.sort_values(ascending=False)

  # creating a pie chart
  grouped_data.plot.pie(autopct='%1.1f%%', startangle=90, figsize=(6, 6))

  # adding a title and displaying the plot
  plt.title(f'{dimension} {fact} Distribution')
  plt.ylabel('')  # To hide the y-label
  plt.show()

In [7]:
# function to get portfolio features

def get_portfolio_features(df_common_features):

  print_date_time()
  print('-------------------')

  #df_common_features["Target"] = df_common_features["Target"].fillna(df_common_features["Max"])
  df_common_features['NTT'] = np.where(df_common_features['Strategy']== 'NTT', df_common_features["Target"], df_common_features['Max'])
  df_common_features['LTT'] = np.where(df_common_features['Strategy']== 'BTT', df_common_features["Target"], df_common_features['Max'])
  df_common_features['BOL'] = df_common_features['Min']

  tmp_df = df_common_features[df_common_features['Symbol'].isin(mypf_df[mypf_df['InPortfolio'] != 'NA'].Symbol.values)]
  print('qualified stocks: '+str(len(tmp_df['Symbol'].unique())))
  tmp_df1 = tmp_df[tmp_df['LatestQtr'] == 1]
  print('with latest results: '+str(len(tmp_df1['Symbol'].unique())))
  tmp_df1 = tmp_df1[tmp_df1['StarStock'] == 1]
  print('still star stocks: '+str(len(tmp_df1['Symbol'].unique())))
  tmp_df['Investment'] = tmp_df['AvgCost'] * tmp_df['Shares']
  tmp_df['Current'] = round(tmp_df['Close'] * tmp_df['Shares'],0)
  tmp_df['Previous'] = tmp_df['Prev_Close'] * tmp_df['Shares']
  tmp_df['EstimatedST'] = tmp_df['NTT'] * tmp_df['Shares']
  tmp_df['EstimatedLT'] = tmp_df['LTT'] * tmp_df['Shares']
  tmp_df['Current P/L'] = round((tmp_df['Current'] - tmp_df['Investment']),0)
  tmp_df['Today P/L%'] = round((tmp_df['Current'] - tmp_df['Previous'])*100/tmp_df['Previous'],2)
  tmp_df['Current P/L%'] = round((tmp_df['Current'] - tmp_df['Investment'])*100/tmp_df['Investment'],2)
  tmp_df['EstimatedST P/L%'] = round((tmp_df['EstimatedST'] - tmp_df['Investment'])*100/tmp_df['Investment'],2)
  tmp_df['EstimatedLT P/L%'] = round((tmp_df['EstimatedLT'] - tmp_df['Investment'])*100/tmp_df['Investment'],2)
  tmp_df['NTT%'] = round((tmp_df['NTT'] - tmp_df['Close'])*100/tmp_df['Close'],2)
  tmp_df['LTT%'] = round((tmp_df['LTT'] - tmp_df['Close'])*100/tmp_df['Close'],2)
  tmp_df['Gained%'] = round((tmp_df['Close'] - tmp_df['BOL'])*100/tmp_df['BOL'],2)
  investment = round(sum(tmp_df['AvgCost']*tmp_df['Shares']),0)
  current = round(sum(tmp_df['Close']*tmp_df['Shares']),0)
  tmp_df['InitAlloc%'] = round(tmp_df['Investment']*100/investment,2)
  tmp_df['CurrAlloc%'] = round(tmp_df['Current']*100/current,2)
  tmp_df['FTT'] = tmp_df['LTT']
  tmp_df.loc[tmp_df['Strategy'] == 'NTT', 'FTT'] = tmp_df['NTT']
  tmp_df['FTT%'] = tmp_df['LTT%']
  tmp_df.loc[tmp_df['Strategy'] == 'NTT', 'FTT%'] = tmp_df['NTT%']
  tmp_df['FTT Amt'] = round(tmp_df['FTT%'] * tmp_df['Current']/100,0)
  tmp_df['OTT%'] = round((tmp_df['FTT'] - tmp_df['AvgCost'])*100/tmp_df['AvgCost'],2)
  tmp_df['RRR Ind'] = round(tmp_df['Current P/L']/tmp_df['FTT Amt'],2)
  tmp_df['Risk Ind'] = round(tmp_df['Current P/L%']*tmp_df['CurrAlloc%'],0)

  return tmp_df

# function to print portfolio features
def print_portfolio_stats(df_portfolio_features, myinvmt_df):
  from pyxirr import xirr

  total_booked_amt, reserve_amt, cy_booked_amt, py_booked_amt = get_amt()

  dates = myinvmt_df['Date'].values
  dates = np.append(dates, datetime.date.today().strftime('%d-%b-%y'))
  investment = myinvmt_df['Investment'].values
  dates= pd.to_datetime(dates)

  current = round(sum(df_portfolio_features['Close']*df_portfolio_features['Shares']),0) + reserve_amt
  investment_xirr = np.append(investment, current)
  cagr = round(xirr(pd.DataFrame({"dates": dates, "amounts": investment_xirr}))*100,2)

  investment = -sum(investment)
  invested = round(sum(df_portfolio_features['AvgCost']*df_portfolio_features['Shares']),0) + reserve_amt
  previous = round(sum(df_portfolio_features['Prev_Close']*df_portfolio_features['Shares']),0) + reserve_amt
  cy_invested = investment + py_booked_amt

  today_pnl_amount = current-previous
  today_pnl_percentage = round((current-previous)*100/previous,2)

  curr_pnl_amount = current-invested
  curr_pnl_percentage = round((curr_pnl_amount)*100/(cy_invested),2)

  cy_pnl_amount = cy_booked_amt + curr_pnl_amount
  cy_pnl_percentage = round((cy_pnl_amount)*100/cy_invested,2)

  overall_pnl_amount = total_booked_amt + curr_pnl_amount
  overall_pnl_percentage = round((overall_pnl_amount)*100/investment,2)

  estimate_st = round(sum(df_portfolio_features['FTT']*df_portfolio_features['Shares']),0)  + reserve_amt
  est_st_pnl_amount = estimate_st-current
  est_st_pnl_percentage = round((est_st_pnl_amount)*100/current,2)

  estimate_lt = round(sum(df_portfolio_features['LTT']*df_portfolio_features['Shares']),0)  + reserve_amt
  est_lt_pnl_amount = estimate_lt-current
  est_lt_pnl_percentage = round((est_lt_pnl_amount)*100/current,2)

  total_profit = round(sum(df_portfolio_features[df_portfolio_features['Current P/L%'] > 0]['Current']) - sum(df_portfolio_features[df_portfolio_features['Current P/L%'] > 0]['Investment']),0)
  total_loss = round(sum(df_portfolio_features[df_portfolio_features['Current P/L%'] < 0]['Current']) - sum(df_portfolio_features[df_portfolio_features['Current P/L%'] < 0]['Investment']),0)

  cy_booked_percentage = round((cy_booked_amt)*100/current,2)
  py_booked_percentage = round((py_booked_amt)*100/investment,2)
  total_booked_percentage = round((total_booked_amt)*100/investment,2)

  print('-------------------')
  print('Initial Investment: ', format_amt(investment))
  print('CY Investment: ', format_amt(cy_invested))
  print('Reserve: ', format_amt(reserve_amt))
  print('Current: ',  format_amt(current))
  print('-------------------')
  print('Today PnL: '+ '{} ({}%)'.format(format_amt(today_pnl_amount), today_pnl_percentage))
  print('Current PnL: '+ '{} ({}%)'.format(format_amt(curr_pnl_amount), curr_pnl_percentage))
  print('CY Booked + Current PnL: '+ '{} ({}%)'.format(format_amt(cy_pnl_amount), cy_pnl_percentage))
  print('-------------------')
  print('Total profit: ', format_amt(total_profit))
  print('Total loss: ', format_amt(total_loss))
  print('-------------------')
  print('Total Booked + Current PnL: '+ '{} ({}%)'.format(format_amt(overall_pnl_amount), overall_pnl_percentage))
  print('Total Booked PnL: '+ '{} ({}%)'.format(format_amt(total_booked_amt), total_booked_percentage))
  print('Curr Year Booked PnL: '+ '{} ({}%)'.format(format_amt(cy_booked_amt), cy_booked_percentage))
  print('Prev Year Booked PnL: '+ '{} ({}%)'.format(format_amt(py_booked_amt), py_booked_percentage))
  print('===================')
  print('Est FTT: ',  format_amt(estimate_st))
  print('Est FTT PnL: '+ '{} ({}%)'.format(format_amt(est_st_pnl_amount), est_st_pnl_percentage))

  print('===================')
  print('Deployed: ', format_amt(investment))

  print('Current: ', format_amt(current))

  print('CAGR/XIRR %: '+'{}%'.format(cagr))

In [8]:
# get start and end date
start_date, end_date = get_start_end_date()

# get portfolio and prospects data
mypfs_df = get_mypfs_df()
mypps_df = get_mypps_df()
myinvmt_df = get_myinvmt_df()

# merge above datasets
mypf_df = pd.merge(mypfs_df, mypps_df, on="Symbol")

# seggregate dm and sv portfolio
dm_pf = mypf_df[mypf_df['InPortfolio'] == 'DM']
sv_pf = mypf_df[mypf_df['InPortfolio'] == 'SV']

# build portfolio stock dataframe
dm_stocks = get_stock_ids(dm_pf)
sv_stocks = get_stock_ids(sv_pf)
df_stocks = pd.concat([dm_pf,sv_pf], ignore_index = True)

# arrange common and diff stock features
common_cols = ['Symbol', 'Target', 'Criteria', 'Strategy', 'CumlRnk', 'LatestQtr', 'StarStock', 'Conviction', 'Category', 'InFolio', 'XIRR', 'MBQ']
diff_cols = ['Symbol', 'AvgCost', 'Shares']
df_stocks = arrange_features(df_stocks, common_cols, diff_cols)

# get common features
stock_ids = df_stocks['Symbol'].values
df_common_features = get_common_features(stock_ids, df_stocks)

df_common_features.reset_index(drop=True, inplace=True)
df_common_features.drop(['Date'], axis=1, inplace=True)
# get and print portfolio features
df_portfolio_features = get_portfolio_features(df_common_features)

print_portfolio_stats(df_portfolio_features, myinvmt_df)

df = df_portfolio_features
#plot_pie_chart(df, 'CapType', 'Current')
list_ox40n = list(df[df['MBQ'].str.contains('OX40N', na=False)]['Symbol'].values)

Run date time (IST): 2026-03-25 15:07:38
-------------------
qualified stocks: 86
with latest results: 26
still star stocks: 16

-------------------
Initial Investment:  1.36 C
CY Investment:  1.62 C
Reserve:  1.61 K
Current:  1.31 C
-------------------
Today PnL: 2.30 L (1.78%)
Current PnL: -45.87 L (-28.23%)
CY Booked + Current PnL: -29.98 L (-18.45%)
-------------------
Total profit:  58.04 K
Total loss:  -46.45 L
-------------------
Total Booked + Current PnL: -3.00 L (-2.21%)
Total Booked PnL: 42.87 L (31.64%)
Curr Year Booked PnL: 15.89 L (12.11%)
Prev Year Booked PnL: 26.98 L (19.91%)
===================
Est FTT:  2.48 C
Est FTT PnL: 1.17 C (88.85%)
===================
Deployed:  1.36 C
Current:  1.31 C
CAGR/XIRR %: -1.56%

In [9]:
# top 5 near their targets
cols = ['Symbol', 'Today P/L%', 'Current P/L%', 'FTT%', 'OTT%', 'FTT Amt', 'Current P/L', 'Current', 'FTT', 'Dev%_PE', 'RSI_14','Conviction', 'Spread%',  'CumlRnk', 'RRR Ind', 'CurrAlloc%', 'Gained%', 'Criteria', 'Strategy', 'Category']
df_tmp = df_portfolio_features[~df_portfolio_features['Symbol'].isin(['ENRIN','BLUSPRING','DIGITIDE'])]
df_tmp = df_tmp.sort_values(by = 'FTT Amt', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
50,MASFIN,1.56,-7.36,31.23,21.57,28346.0,-7215.0,90765.0,397.04,-20.05,46.0,H-SC,2.86,167.0,-0.25,0.69,23.80,XR,ATH,FINANCE
77,TTKPRESTIG,0.22,-42.87,75.20,0.09,43296.0,-43203.0,57574.0,770.00,33.62,34.0,M-SC,20.01,250.0,-1.00,0.44,0.22,OX40N,NTT,DURABLES
37,ICICIGI,2.31,-6.24,27.28,19.34,51186.0,-12478.0,187631.0,2252.93,-21.06,37.0,X-MC,4.03,66.0,-0.24,1.43,3.72,X40,ATH,INSURANCE
67,SONACOMS,3.31,-11.59,57.33,39.09,51273.0,-11725.0,89434.0,804.02,-29.92,51.0,M-MC,7.27,193.0,-0.23,0.68,26.52,AR,ATH,AUTO
2,ABBOTINDIA,-1.49,-11.44,33.31,18.07,52763.0,-20455.0,158400.0,35195.00,-24.65,47.0,X-MC,10.52,58.0,-0.39,1.21,3.59,X40,ATH,PHARMA

In [10]:
# top 5 today
df_tmp = df_portfolio_features.sort_values(by = 'Today P/L%', ascending=False)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
48,KANSAINER,7.26,-42.26,96.53,13.47,150297.0,-113967.0,155700.0,340.0,-50.37,37.0,H-SC,21.43,162.0,-0.76,1.19,8.76,XY24,NTT,PAINTS
56,RAJOOENG,6.96,-46.96,163.20,39.61,88732.0,-48130.0,54370.0,143.1,-64.09,39.0,H-SC,32.21,136.0,-0.54,0.41,6.96,AR,ATH,MISC
16,CAMPUS,5.46,-20.78,68.24,33.28,90703.0,-34857.0,132918.0,393.0,-36.14,42.0,M-SC,10.95,218.0,-0.38,1.01,6.59,XY24,NTT,FOOTWEAR
55,RAJESHEXPO,4.98,-82.79,481.50,0.07,113663.0,-113571.0,23606.0,518.0,764.90,20.0,L-SC,36.05,268.0,-1.00,0.18,4.99,OX40N,NTT,JEWELLERY
82,VOLTAS,4.98,6.93,35.78,45.20,73362.0,13293.0,205035.0,1856.0,22.36,44.0,X-MC,3.55,79.0,0.18,1.56,14.20,XY25,NTT,AC

In [11]:
# bottom 5 today
df_tmp = df_portfolio_features.sort_values(by = 'Today P/L%', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
4,ALKYLAMINE,-2.83,-41.46,230.74,93.63,136386.0,-41855.0,59108.0,4546.37,-37.39,49.0,H-SC,25.93,142.0,-0.31,0.45,10.91,SR,ATH,CHEMICALS
76,TRIDENT,-1.85,-33.23,92.46,28.51,56957.0,-30652.0,61602.0,48.00,-14.03,52.0,M-SC,14.16,223.0,-0.54,0.47,13.06,XR,NTT,TEXTILES
2,ABBOTINDIA,-1.49,-11.44,33.31,18.07,52763.0,-20455.0,158400.0,35195.00,-24.65,47.0,X-MC,10.52,58.0,-0.39,1.21,3.59,X40,ATH,PHARMA
78,UNITDSPR,-1.14,-3.56,25.22,20.77,56952.0,-8325.0,225819.0,1644.00,-14.48,45.0,X-MC,1.94,64.0,-0.15,1.72,2.96,X40N,NTT,BREWERIES
73,TCS,-0.73,-30.10,81.07,26.57,262540.0,-139430.0,323843.0,4311.59,-40.68,29.0,X-LC,17.58,2.0,-0.53,2.47,1.07,X40,ATH,IT

In [12]:
# top 5 to exit based on CumlRnk
df_tmp = df_portfolio_features[~df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])]
df_tmp = df_tmp[(df_tmp['Current P/L%'] > -1) & (df_tmp['Current P/L%'] < 1)].sort_values(by = 'CumlRnk', ascending=False)
df_tmp[cols].head()

Empty DataFrame
Columns: [Symbol, Today P/L%, Current P/L%, FTT%, OTT%, FTT Amt, Current P/L, Current, FTT, Dev%_PE, RSI_14, Conviction, Spread%, CumlRnk, RRR Ind, CurrAlloc%, Gained%, Criteria, Strategy, Category]
Index: []

In [13]:
# OX40N stocks to exit
df_tmp = df_portfolio_features[(df_portfolio_features['Symbol'].isin(list_ox40n))].sort_values(by = 'Current P/L%', ascending=False)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
26,FINCABLES,2.42,5.76,96.59,107.91,150820.0,8501.0,156145.0,1641.55,-4.62,48.0,M-SC,8.13,220.0,0.06,1.19,17.47,OX40N,ATH,CABLES
66,SIS,1.05,-34.78,85.92,21.26,62223.0,-38612.0,72420.0,528.00,1694.30,45.0,H-SC,14.36,168.0,-0.62,0.55,7.68,OX40N,NTT,MISC
18,CERA,0.49,-38.24,100.58,23.89,109275.0,-67258.0,108645.0,9475.00,-40.33,47.0,H-SC,19.06,153.0,-0.62,0.83,4.41,OX40N,NTT,CERAMICS
72,TATAELXSI,1.12,-39.08,116.73,32.03,93749.0,-51522.0,80313.0,9161.00,-23.72,40.0,H-SC,21.04,158.0,-0.55,0.61,4.65,OX40N,NTT,IT
48,KANSAINER,7.26,-42.26,96.53,13.47,150297.0,-113967.0,155700.0,340.00,-50.37,37.0,H-SC,21.43,162.0,-0.76,1.19,8.76,XY24,NTT,PAINTS

In [14]:
# top 5 to book for rotation
df_tmp = df_portfolio_features[(df_portfolio_features['Current P/L%'] > 20) ].sort_values(by = 'CumlRnk', ascending=False)
df_tmp[cols].head()

Empty DataFrame
Columns: [Symbol, Today P/L%, Current P/L%, FTT%, OTT%, FTT Amt, Current P/L, Current, FTT, Dev%_PE, RSI_14, Conviction, Spread%, CumlRnk, RRR Ind, CurrAlloc%, Gained%, Criteria, Strategy, Category]
Index: []

In [15]:
# top 5 to monitor for exit
df_tmp = df_portfolio_features[~df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])]
df_tmp = df_tmp[(df_tmp['Current P/L%'] > 0) ].sort_values(by = 'Dev%_PE', ascending=False)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
26,FINCABLES,2.42,5.76,96.59,107.91,150820.0,8501.0,156145.0,1641.55,-4.62,48.0,M-SC,8.13,220.0,0.06,1.19,17.47,OX40N,ATH,CABLES
1,ABB,0.71,13.85,27.85,45.57,82955.0,36245.0,297864.0,7934.00,-26.88,55.0,H-MC,13.41,125.0,0.44,2.27,32.27,AR,NTT,ELECTRICAL

In [16]:
# top 5 to book for rotation from weak conviction
df_tmp = df_portfolio_features[~df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])]
df_tmp = df_tmp[~df_tmp['Criteria'].isin(['XY25','XY24','X40', 'X40N'])].sort_values(by = 'RRR Ind', ascending=False)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
1,ABB,0.71,13.85,27.85,45.57,82955.0,36245.0,297864.0,7934.00,-26.88,55.0,H-MC,13.41,125.0,0.44,2.27,32.27,AR,NTT,ELECTRICAL
26,FINCABLES,2.42,5.76,96.59,107.91,150820.0,8501.0,156145.0,1641.55,-4.62,48.0,M-SC,8.13,220.0,0.06,1.19,17.47,OX40N,ATH,CABLES
40,INDIAMART,2.79,-13.25,138.30,106.72,147969.0,-16345.0,106991.0,4810.62,-60.94,39.0,H-SC,11.98,140.0,-0.11,0.82,7.03,AR,ATH,MISC
85,ZYDUSLIFE,2.00,-4.66,42.25,35.63,84423.0,-9757.0,199817.0,1286.17,-17.12,51.0,H-MC,5.39,120.0,-0.12,1.52,11.24,AR,ATH,PHARMA
67,SONACOMS,3.31,-11.59,57.33,39.09,51273.0,-11725.0,89434.0,804.02,-29.92,51.0,M-MC,7.27,193.0,-0.23,0.68,26.52,AR,ATH,AUTO

In [17]:
# top 5 to accumulate based on lowest RSI_14
df_tmp = df_portfolio_features[df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])].sort_values(by = 'RSI_14', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
53,PGHH,1.98,-27.43,81.92,32.01,126930.0,-58576.0,154944.0,17616.87,-50.89,23.0,X-MC,16.44,57.0,-0.46,1.18,2.41,X40,ATH,FMCG
38,ICICIPRULI,0.62,-10.50,46.07,30.73,81229.0,-20688.0,176317.0,790.00,-34.56,24.0,X-MC,4.95,78.0,-0.25,1.34,1.81,X40,ATH,INSURANCE
58,RELAXO,2.63,-65.64,343.27,52.31,171209.0,-95284.0,49876.0,1176.00,-63.41,26.0,X-SC,27.45,92.0,-0.56,0.38,4.10,X40N,NTT,FOOTWEAR
9,BAJAJHFL,0.53,-29.28,129.25,62.13,249577.0,-79950.0,193096.0,181.50,-41.72,29.0,X-MC,20.81,60.0,-0.32,1.47,0.84,X40N,ATH,FINANCE
73,TCS,-0.73,-30.10,81.07,26.57,262540.0,-139430.0,323843.0,4311.59,-40.68,29.0,X-LC,17.58,2.0,-0.53,2.47,1.07,X40,ATH,IT

In [18]:
# top 5 to accumulate based on Spread and CumlRnk
df_tmp = df_portfolio_features[df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])]
df_tmp = df_tmp[(df_tmp['CumlRnk'] < 100)].sort_values(by = 'Spread%', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
78,UNITDSPR,-1.14,-3.56,25.22,20.77,56952.0,-8325.0,225819.0,1644.00,-14.48,45.0,X-MC,1.94,64.0,-0.15,1.72,2.96,X40N,NTT,BREWERIES
65,SIEMENS,3.18,-16.78,50.82,25.51,78702.0,-31230.0,154865.0,4671.50,30.03,46.0,H-LC,2.33,51.0,-0.40,1.18,14.05,AR,ATH,ELECTRICAL
59,RELIANCE,0.23,-9.16,37.94,25.30,69259.0,-18415.0,182548.0,1952.00,-11.57,52.0,X-LC,3.50,21.0,-0.27,1.39,21.88,XY25,BTT,REFINERIES
82,VOLTAS,4.98,6.93,35.78,45.20,73362.0,13293.0,205035.0,1856.00,22.36,44.0,X-MC,3.55,79.0,0.18,1.56,14.20,XY25,NTT,AC
37,ICICIGI,2.31,-6.24,27.28,19.34,51186.0,-12478.0,187631.0,2252.93,-21.06,37.0,X-MC,4.03,66.0,-0.24,1.43,3.72,X40,ATH,INSURANCE

In [19]:
# top 5 to accumulate based on lowest Gained%
df_tmp = df_portfolio_features[df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])].sort_values(by = 'Gained%', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
9,BAJAJHFL,0.53,-29.28,129.25,62.13,249577.0,-79950.0,193096.0,181.50,-41.72,29.0,X-MC,20.81,60.0,-0.32,1.47,0.84,X40N,ATH,FINANCE
73,TCS,-0.73,-30.10,81.07,26.57,262540.0,-139430.0,323843.0,4311.59,-40.68,29.0,X-LC,17.58,2.0,-0.53,2.47,1.07,X40,ATH,IT
27,GILLETTE,-0.52,-9.20,42.86,29.72,98814.0,-23346.0,230550.0,10978.86,-30.15,32.0,X-SC,11.41,83.0,-0.24,1.76,1.49,X40,ATH,FMCG
45,ITC,1.48,-22.15,52.94,19.06,140192.0,-75353.0,264813.0,452.00,-57.14,36.0,X-LC,18.81,1.0,-0.54,2.02,1.76,X40,NTT,FMCG
38,ICICIPRULI,0.62,-10.50,46.07,30.73,81229.0,-20688.0,176317.0,790.00,-34.56,24.0,X-MC,4.95,78.0,-0.25,1.34,1.81,X40,ATH,INSURANCE

In [20]:
# top 5 to accumulate based on lowest CurrAlloc%
df_tmp = df_portfolio_features[df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])].sort_values(by = 'CurrAlloc%', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
58,RELAXO,2.63,-65.64,343.27,52.31,171209.0,-95284.0,49876.0,1176.00,-63.41,26.0,X-SC,27.45,92.0,-0.56,0.38,4.10,X40N,NTT,FOOTWEAR
12,BATAINDIA,2.93,-57.50,218.15,35.20,119284.0,-73990.0,54680.0,2096.00,-28.38,31.0,X-SC,31.76,91.0,-0.62,0.42,5.28,X40,NTT,FOOTWEAR
54,QUESS,0.87,-27.41,139.56,73.90,108190.0,-29271.0,77522.0,424.00,-60.88,39.0,X-SC,21.61,80.0,-0.27,0.59,4.19,XY24,NTT,MISC
36,HONAUT,2.03,-26.88,106.94,51.31,150785.0,-51838.0,141000.0,58357.33,-39.15,34.0,X-SC,16.19,90.0,-0.34,1.07,3.62,X40N,ATH,ELECTRICAL
51,MEDANTA,3.83,-13.51,46.97,27.12,71712.0,-23841.0,152676.0,1486.00,-16.14,37.0,X-SC,12.80,87.0,-0.33,1.16,4.28,XY24,NTT,HEALTHCARE

In [21]:
# top 5 to accumulate based on CumlRnk
df_tmp = df_portfolio_features.sort_values(by = 'CumlRnk', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
45,ITC,1.48,-22.15,52.94,19.06,140192.0,-75353.0,264813.0,452.00,-57.14,36.0,X-LC,18.81,1.0,-0.54,2.02,1.76,X40,NTT,FMCG
73,TCS,-0.73,-30.10,81.07,26.57,262540.0,-139430.0,323843.0,4311.59,-40.68,29.0,X-LC,17.58,2.0,-0.53,2.47,1.07,X40,ATH,IT
43,INFY,0.05,-12.93,54.18,34.24,147601.0,-40461.0,272427.0,1972.00,-31.42,42.0,X-LC,15.07,3.0,-0.27,2.08,4.77,X40,NTT,IT
75,TMPV,1.95,-29.16,92.80,36.58,233923.0,-103769.0,252072.0,600.00,-85.81,35.0,X-LC,6.70,4.0,-0.44,1.92,1.95,XY24,NTT,AUTO
33,HCLTECH,0.64,-10.31,38.06,23.83,82586.0,-24934.0,216990.0,1908.19,-5.71,47.0,X-LC,11.65,8.0,-0.30,1.65,5.36,X40,ATH,IT

In [22]:
# top 5 for average up
df_tmp = df_portfolio_features[(df_portfolio_features['Dev%_200'] > 5)].sort_values(by = 'CurrAlloc%', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
67,SONACOMS,3.31,-11.59,57.33,39.09,51273.0,-11725.0,89434.0,804.02,-29.92,51.0,M-MC,7.27,193.0,-0.23,0.68,26.52,AR,ATH,AUTO
1,ABB,0.71,13.85,27.85,45.57,82955.0,36245.0,297864.0,7934.00,-26.88,55.0,H-MC,13.41,125.0,0.44,2.27,32.27,AR,NTT,ELECTRICAL

In [23]:
# top 5 RSP
df_tmp = df_portfolio_features.sort_values(by = 'RSP', ascending=False)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
30,HAPPSTMNDS,0.10,-50.09,270.36,84.85,172944.0,-64197.0,63968.0,1480.71,-40.67,55.0,H-SC,26.12,152.0,-0.37,0.49,18.46,AR,ATH,IT
69,SURYODAY,3.27,-26.16,66.63,23.03,88100.0,-46848.0,132223.0,216.00,44.74,52.0,H-SC,5.85,166.0,-0.53,1.01,29.23,XR,NTT,BANKS
47,JSWINFRA,2.24,-12.13,32.51,16.43,63351.0,-26908.0,194866.0,342.00,-24.58,51.0,X-MC,11.53,61.0,-0.42,1.48,6.96,X40N,NTT,REALTY
59,RELIANCE,0.23,-9.16,37.94,25.30,69259.0,-18415.0,182548.0,1952.00,-11.57,52.0,X-LC,3.50,21.0,-0.27,1.39,21.88,XY25,BTT,REFINERIES
26,FINCABLES,2.42,5.76,96.59,107.91,150820.0,8501.0,156145.0,1641.55,-4.62,48.0,M-SC,8.13,220.0,0.06,1.19,17.47,OX40N,ATH,CABLES

In [24]:
# Top N allocation
df_tmp = df_portfolio_features.sort_values(by = 'CurrAlloc%', ascending=False)
top_n_values = [10, 25, 50]

sum_df = pd.DataFrame({
    'Top_N': top_n_values,
    'Sum_Alloc%': [df_tmp['CurrAlloc%'].head(n).sum() for n in top_n_values]
})

sum_df

   Top_N  Sum_Alloc%
0     10       20.62
1     25       45.83
2     50       78.15

In [25]:
# market-cap-wise allocation
df_tmp = df_portfolio_features[cols]
df_tmp.groupby(df_tmp['Conviction'].str[-2:])['CurrAlloc%'].sum().sort_values(ascending=False)

Conviction
SC    44.25
MC    30.16
LC    25.56
Name: CurrAlloc%, dtype: float64

In [26]:
# criteria-wise allocation
df_portfolio_features.groupby('Criteria')['CurrAlloc%'].sum().sort_values(ascending=False)

Criteria
XY24     27.03
X40      25.41
X40N     15.19
AR        9.18
XR        8.29
XY25      7.41
OX40N     6.65
SR        0.81
Name: CurrAlloc%, dtype: float64

In [27]:
# conviction-wise allocation
df_portfolio_features.groupby('Conviction')['CurrAlloc%'].sum().sort_values(ascending=False)

Conviction
X-LC    23.38
X-MC    22.66
H-SC    21.61
X-SC    12.15
M-SC     9.96
H-MC     5.09
M-MC     2.05
H-LC     1.18
M-LC     1.00
L-SC     0.53
L-MC     0.36
Name: CurrAlloc%, dtype: float64

In [28]:
# sector-wise stats
df_tmp = df_portfolio_features.groupby('Category')[['CurrAlloc%', 'Current', 'Current P/L', 'FTT Amt']].sum().sort_values(by=['Current', 'Current P/L'], ascending=False)
df_tmp['Current P/L%'] = round(df_tmp['Current P/L'] * 100 / df_tmp['Current'], 2)
df_tmp['FTT%'] = round(df_tmp['FTT Amt'] * 100 / df_tmp['Current'], 2)
cols = ['CurrAlloc%', 'Current P/L%', 'FTT%']
df_tmp[cols].sort_values(by=['CurrAlloc%'], ascending=False)

               CurrAlloc%  Current P/L%    FTT%
Category
FMCG                15.10        -26.08   70.84
FINANCE             13.06        -25.22   76.25
IT                  11.81        -45.47  119.50
MISC                 6.94        -47.21  111.16
ELECTRICAL           6.54        -12.77   55.94
PAINTS               5.21        -43.98   68.98
INSURANCE            4.67        -10.51   48.33
BANKS                4.61        -27.45   92.15
PHARMA               4.14         -8.08   42.09
AUTO                 3.67        -35.77   89.64
AC                   2.08        -17.19   48.96
HEALTHCARE           1.88        -44.44   82.14
TRAVEL               1.81        -88.32  182.61
FOOTWEAR             1.81        -85.96  160.52
DURABLES             1.75        -68.63  109.65
APPARELS             1.74        -17.34   57.36
BREWERIES            1.72         -3.69   25.22
REALTY               1.48        -13.81   32.51
REFINERIES           1.39        -10.09   37.94
CERAMICS             1.37        -70.83  122.73
CEMENT               1.25        -62.98  184.90
CABLES               1.19          5.44   96.59
ENGINEERING          1.09        -68.83  146.05
CHEMICALS            1.06        -89.58  244.25
JEWELLERY            1.02       -138.85  221.84
ENTERTAINMENT        0.76        -93.56  209.00
TEXTILES             0.47        -49.76   92.46
HOTELS               0.35       -150.49  238.84

In [29]:
# money to be made criteria-wise
df_portfolio_features.groupby('Criteria')['FTT Amt'].agg(['sum', 'count']).sort_values(by='sum', ascending=False)

                sum  count
Criteria
XY24      4046308.0     21
X40       1839845.0     16
XR        1405958.0     12
AR        1365819.0     10
X40N      1305726.0     10
OX40N      918902.0     10
XY25       466488.0      5
SR         313553.0      2

In [30]:
# money to be made conviction-wise
df_portfolio_features.groupby('Conviction')['FTT Amt'].agg(['sum', 'count']).sort_values(by='sum', ascending=False)

                  sum  count
Conviction
H-SC        3957053.0     24
X-MC        1756728.0     15
X-LC        1708824.0     13
M-SC        1610254.0     14
X-SC        1586169.0     10
H-MC         410277.0      3
L-SC         221932.0      2
M-LC         160538.0      1
M-MC         116137.0      2
H-LC          78702.0      1
L-MC          55985.0      1

In [31]:
# money to be made criteria and conviction-wise
df_portfolio_features.groupby(['Conviction', 'Criteria'])['FTT Amt'].agg(['sum', 'count']).sort_values(by='sum', ascending=False)

                           sum  count
Conviction Criteria
H-SC       XY24      1366719.0      6
           AR         989472.0      5
M-SC       XY24       932164.0      6
X-LC       X40        918694.0      7
H-SC       XR         889544.0      7
X-SC       XY24       854442.0      4
X-MC       X40        703053.0      7
           X40N       531433.0      4
X-SC       X40N       513629.0      4
M-SC       OX40N      407474.0      5
H-SC       OX40N      397765.0      4
X-LC       XY24       381729.0      2
H-SC       SR         313553.0      2
X-MC       XY24       268355.0      2
X-LC       X40N       260664.0      2
X-MC       XY25       253887.0      2
H-MC       XY24       242899.0      1
X-SC       X40        218098.0      2
M-SC       XR         191622.0      2
H-MC       AR         167378.0      2
M-LC       XR         160538.0      1
X-LC       XY25       147737.0      2
L-SC       OX40N      113663.0      1
           XR         108269.0      1
M-SC       AR          78994.0      1
H-LC       AR          78702.0      1
M-MC       XY25        64864.0      1
L-MC       XR          55985.0      1
M-MC       AR          51273.0      1

In [32]:
# notebook execution time

end_time = time.time()
execution_time = round(end_time - start_time, 0)
print(f"Notebook execution time: {execution_time} seconds")

Notebook execution time: 34.0 seconds