<a href="https://colab.research.google.com/github/ankit-rathi/Quantvesting_v2/blob/main/myStocks_Portfolio_Analysis.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
'''
!pip install pandas==2.2.2 -qq
!pip install pyxirr -qq
!pip install ta -qq
!pip install yfinance==0.2.59 -qq
'''

'\n!pip install pandas==2.2.2 -qq\n!pip install pyxirr -qq\n!pip install ta -qq\n!pip install yfinance==0.2.59 -qq\n'

In [2]:
# import libraries

import numpy as np
import pandas as pd
import datetime
import warnings
warnings.filterwarnings('ignore')
import yfinance as yfin
import ta
import matplotlib.pyplot as plt
import requests

In [3]:
# notebook start time
import time
import datetime
import pytz

start_time = time.time()

# function to print date timestamp
def print_date_time():
  tz_NY = pytz.timezone('Asia/Kolkata')
  datetime_NY = datetime.datetime.now(tz_NY)
  print("Run date time (IST):", datetime_NY.strftime("%Y-%m-%d %H:%M:%S"))

In [4]:
# function to get booked and reserved amount
def get_amt():
  # fetch the JSON data from the URL
  url = "https://raw.githubusercontent.com/ankit-rathi/Tradevesting_v1/main/data/myPortfolioAmts.json"
  response = requests.get(url)
  pf_amts = response.json()  # parse the JSON data

  # extract values from the JSON
  py_booked_amt_dm = pf_amts["py_booked_amt_dm"]
  py_booked_amt_sv = pf_amts["py_booked_amt_sv"]
  cy_booked_amt_dm = pf_amts["cy_booked_amt_dm"]
  cy_booked_amt_sv = pf_amts["cy_booked_amt_sv"]
  reserve_amt_dm = pf_amts["reserve_amt_dm"]
  reserve_amt_sv = pf_amts["reserve_amt_sv"]

  # perform calculations
  py_booked_amt = py_booked_amt_dm + py_booked_amt_sv
  cy_booked_amt = cy_booked_amt_dm + cy_booked_amt_sv
  reserve_amt = reserve_amt_dm + reserve_amt_sv
  total_booked_amt = py_booked_amt + cy_booked_amt

  return total_booked_amt, reserve_amt, cy_booked_amt, py_booked_amt

gen_output = 0

In [5]:
# function to format the amount
def format_amt(number):
    abs_number = abs(number)

    if abs_number >= 1_00_00_000:  # Crores
        formatted_amt = f"{number / 1_00_00_000:.2f} C"
    elif abs_number >= 1_00_000:  # Lakhs
        formatted_amt = f"{number / 1_00_000:.2f} L"
    elif abs_number >= 1_000:  # Thousands
        formatted_amt = f"{number / 1_000:.2f} K"
    else:
        formatted_amt = f"{number:.2f}"

    return formatted_amt

# function to set start and end date
def get_start_end_date():
  start_date = (datetime.date.today() + datetime.timedelta(days=-365)).strftime('%Y-%m-%d')
  end_date = (datetime.date.today() + datetime.timedelta(days=1)).strftime('%Y-%m-%d')
  return start_date, end_date

# function to fetch my portfolio csv
def get_mypfs_df():
  mypfs_df = pd.read_csv('https://raw.githubusercontent.com/ankit-rathi/Tradevesting_v1/main/data/myPortfolioStocks.csv')
  return mypfs_df

# function to fetch my prospects csv
def get_mypps_df():
  mypps_df = pd.read_csv('https://raw.githubusercontent.com/ankit-rathi/Tradevesting_v1/main/data/myProspectsScrips.csv')
  return mypps_df

# function to fetch screener data
def get_myscreen_df():
  myscreen_df = pd.read_csv('https://raw.githubusercontent.com/ankit-rathi/Tradevesting_v1/main/data/myScreenerDB.csv')
  return myscreen_df

# function to fetch momentum data
def get_myinvmt_df():
  myinvmt_df = pd.read_csv('https://raw.githubusercontent.com/ankit-rathi/Tradevesting_v1/main/data/myInvestments.csv')
  return myinvmt_df

# function to get the stock ids
def get_stock_ids(df_pf):
  stock_n100 = df_pf['Symbol'].unique()

  exclude = ['CADILAHC','MMTC', 'MASFIN']

  stock_ids = df_pf[~df_pf['Symbol'].isin(exclude) ]['Symbol'].unique()

  #mypf = mypf[mypf.Forecast.notnull()]
  #stock_ids = mypf['Symbol'].unique()

  #stock_ids.sort()
  return stock_ids

# get features from screener data
def get_screener_features():
  myscreen_df = get_myscreen_df()
  cols = ['Symbol', 'EPS', 'MedPE', 'ROCE%', 'ROE%', 'CapType']
  return myscreen_df[cols]

# get relative strength
def get_relative_strength(stock_list):

    # Dictionary to store stock tickers and their corresponding percentage price change
    stock_changes = {}

    # Loop through each stock and fetch its price data
    for stock in stock_list:
        try:
            # Download the stock data for the given date range
            stock_data = yfin.Ticker(stock + '.NS').history(period='1mo', interval='1d')[map(str.title, ['open', 'close', 'low', 'high', 'volume'])]

            # Calculate the percentage change for the stock
            if len(stock_data) > 0:
                start_price = stock_data['Close'].iloc[0]
                end_price = stock_data['Close'].iloc[-1]
                percent_change = round(((end_price - start_price) / start_price) * 100, 2)
                stock_changes[stock] = percent_change
            else:
                stock_changes[stock] = np.nan  # If no data is available, set to NaN

        except Exception as e:
            print(f"Error fetching data for {stock}: {e}")
            stock_changes[stock] = np.nan

    # Create a DataFrame with stock tickers and their percentage changes
    df = pd.DataFrame(list(stock_changes.items()), columns=['Symbol', 'Percent_Change'])

    # Drop any stocks with missing data (NaN values)
    df = df.dropna()

    # Calculate the percentile rank based on percentage change
    df['RSP'] = round(df['Percent_Change'].rank(pct=True) * 100, 2)
    cols = ['Symbol', 'RSP']
    df = df[cols]
    # Sort by percentile rank (optional)
    df = df.sort_values(by='RSP', ascending=False).reset_index(drop=True)

    return df

In [6]:
# function to get stock technicals
def stock_prec_dev(stock_symbol):
    #stock_symbol = 'ULTRACEMCO.NS'
    short_window = 20
    mid_window = 50
    long_window = 200
    moving_avg = 'SMA'

    start = datetime.datetime(*map(int, start_date.split('-')))
    end = datetime.datetime(*map(int, end_date.split('-')))

    stock_df = yfin.Ticker(stock_symbol + '.NS').history(period='max', interval='1d')[map(str.title, ['open', 'close', 'low', 'high', 'volume'])]

    stock_df['Max'] = round(max(stock_df['Close']),2)
    stock_df = stock_df[(stock_df.index <= end_date) & (stock_df.index >= start_date)]
    stock_df['200_SMA'] = round(stock_df['Close'].rolling(window = 200, min_periods = 1).mean(),0)
    stock_df['Dev%_200'] = round((stock_df['Close'] - stock_df['200_SMA'])*100/stock_df['200_SMA'],2)
    stock_df.dropna(axis = 0, inplace = True) # remove any null rows

    stock_df['20_SMA'] = stock_df['Close'].rolling(window=20).mean()
    stock_df['50_SMA'] = stock_df['Close'].rolling(window=50).mean()
    stock_df['Symbol'] = stock_symbol

    stock_df['Close'] = round(stock_df['Close'],2)
    stock_df['Min'] = round(min(stock_df['Close']),2)
    stock_df['RSI_14'] = ta.momentum.RSIIndicator(close=stock_df['Close'], window=14).rsi()
    stock_df['RSI_14'] = round(stock_df['RSI_14'],0)
    stock_df['Prev_Close'] = stock_df['Close'].shift(1)
    stock_df.drop(['Open', 'Low', 'High', 'Volume'], axis=1, inplace=True)
    stock_df = stock_df.tail(1)

    max_SMA = max(stock_df['20_SMA'].item(), stock_df['50_SMA'].item(), stock_df['200_SMA'].item())
    min_SMA = min(stock_df['20_SMA'].item(), stock_df['50_SMA'].item(), stock_df['200_SMA'].item())
    ABS_Spread = max_SMA - min_SMA
    stock_df['Spread%'] = round((ABS_Spread / stock_df['200_SMA'].item()) * 100,2)

    return stock_df

# function to compute stock attributes
def get_common_features(stock_ids, df_mypf):

  df_prec_dev = pd.DataFrame()
  df_tmp = get_screener_features()
  df_rs = get_relative_strength(stock_ids)

  for stock_id in stock_ids:
      tmp = stock_prec_dev(stock_id)
      tmp = tmp.reset_index()
      df_prec_dev = pd.concat([df_prec_dev, tmp], ignore_index = True)
  df_prec_dev = pd.merge(df_prec_dev, df_mypf, on= 'Symbol')
  df_prec_dev = pd.merge(df_prec_dev, df_tmp, on= 'Symbol', how='left')
  df_prec_dev = pd.merge(df_prec_dev, df_rs, on= 'Symbol', how='left')
  #print(df_prec_dev.columns)
  df_prec_dev['Curr_PE'] = round(df_prec_dev['Close']/df_prec_dev['EPS'],1)
  df_prec_dev['Dev%_PE'] = round((df_prec_dev['Curr_PE'] - df_prec_dev['MedPE'])*100/df_prec_dev['MedPE'],2)
  df_prec_dev['Conviction'] = df_prec_dev['Conviction'] + '-' + df_prec_dev['CapType']
  return df_prec_dev

# function to arrange stock features
def arrange_features(df_stocks, common_cols, diff_cols):
  df_stocks_common = df_stocks[common_cols].drop_duplicates()
  df_stocks_diff = df_stocks[diff_cols]
  df_stocks_diff['Investment'] = df_stocks_diff['AvgCost'] * df_stocks_diff['Shares']
  df_stocks_diff = df_stocks_diff.groupby(['Symbol'])[['Shares', 'Investment']].aggregate(['sum']).reset_index()
  df_stocks_diff.columns = ['Symbol', 'Shares', 'Investment']
  df_stocks_diff['AvgCost'] = round(df_stocks_diff['Investment']/df_stocks_diff['Shares'],2)
  df_stocks = pd.merge(df_stocks_diff, df_stocks_common, on='Symbol')
  return df_stocks

# plot fact distribution across dimension
def plot_pie_chart(df, dimension, fact):
  # grouping the data by category and calculating the sum of fact for each type
  grouped_data = df.groupby(dimension)[fact].sum()

  # sorting the grouped data in descending order
  grouped_data = grouped_data.sort_values(ascending=False)

  # creating a pie chart
  grouped_data.plot.pie(autopct='%1.1f%%', startangle=90, figsize=(6, 6))

  # adding a title and displaying the plot
  plt.title(f'{dimension} {fact} Distribution')
  plt.ylabel('')  # To hide the y-label
  plt.show()

In [7]:
# function to get portfolio features

def get_portfolio_features(df_common_features):

  print_date_time()
  print('-------------------')

  #df_common_features["Target"] = df_common_features["Target"].fillna(df_common_features["Max"])
  df_common_features['NTT'] = np.where(df_common_features['Strategy']== 'NTT', df_common_features["Target"], df_common_features['Max'])
  df_common_features['LTT'] = np.where(df_common_features['Strategy']== 'BTT', df_common_features["Target"], df_common_features['Max'])
  df_common_features['BOL'] = df_common_features['Min']

  tmp_df = df_common_features[df_common_features['Symbol'].isin(mypf_df[mypf_df['InPortfolio'] != 'NA'].Symbol.values)]
  print('qualified stocks: '+str(len(tmp_df['Symbol'].unique())))
  tmp_df1 = tmp_df[tmp_df['LatestQtr'] == 1]
  print('with latest results: '+str(len(tmp_df1['Symbol'].unique())))
  tmp_df1 = tmp_df1[tmp_df1['StarStock'] == 1]
  print('still star stocks: '+str(len(tmp_df1['Symbol'].unique())))
  tmp_df['Investment'] = tmp_df['AvgCost'] * tmp_df['Shares']
  tmp_df['Current'] = round(tmp_df['Close'] * tmp_df['Shares'],0)
  tmp_df['Previous'] = tmp_df['Prev_Close'] * tmp_df['Shares']
  tmp_df['EstimatedST'] = tmp_df['NTT'] * tmp_df['Shares']
  tmp_df['EstimatedLT'] = tmp_df['LTT'] * tmp_df['Shares']
  tmp_df['Current P/L'] = round((tmp_df['Current'] - tmp_df['Investment']),0)
  tmp_df['Today P/L%'] = round((tmp_df['Current'] - tmp_df['Previous'])*100/tmp_df['Previous'],2)
  tmp_df['Current P/L%'] = round((tmp_df['Current'] - tmp_df['Investment'])*100/tmp_df['Investment'],2)
  tmp_df['EstimatedST P/L%'] = round((tmp_df['EstimatedST'] - tmp_df['Investment'])*100/tmp_df['Investment'],2)
  tmp_df['EstimatedLT P/L%'] = round((tmp_df['EstimatedLT'] - tmp_df['Investment'])*100/tmp_df['Investment'],2)
  tmp_df['NTT%'] = round((tmp_df['NTT'] - tmp_df['Close'])*100/tmp_df['Close'],2)
  tmp_df['LTT%'] = round((tmp_df['LTT'] - tmp_df['Close'])*100/tmp_df['Close'],2)
  tmp_df['Gained%'] = round((tmp_df['Close'] - tmp_df['BOL'])*100/tmp_df['BOL'],2)
  investment = round(sum(tmp_df['AvgCost']*tmp_df['Shares']),0)
  current = round(sum(tmp_df['Close']*tmp_df['Shares']),0)
  tmp_df['InitAlloc%'] = round(tmp_df['Investment']*100/investment,2)
  tmp_df['CurrAlloc%'] = round(tmp_df['Current']*100/current,2)
  tmp_df['FTT'] = tmp_df['LTT']
  tmp_df.loc[tmp_df['Strategy'] == 'NTT', 'FTT'] = tmp_df['NTT']
  tmp_df['FTT%'] = tmp_df['LTT%']
  tmp_df.loc[tmp_df['Strategy'] == 'NTT', 'FTT%'] = tmp_df['NTT%']
  tmp_df['FTT Amt'] = round(tmp_df['FTT%'] * tmp_df['Current']/100,0)
  tmp_df['OTT%'] = round((tmp_df['FTT'] - tmp_df['AvgCost'])*100/tmp_df['AvgCost'],2)
  tmp_df['RRR Ind'] = round(tmp_df['Current P/L']/tmp_df['FTT Amt'],2)
  tmp_df['Risk Ind'] = round(tmp_df['Current P/L%']*tmp_df['CurrAlloc%'],0)

  return tmp_df

# function to print portfolio features
def print_portfolio_stats(df_portfolio_features, myinvmt_df):
  from pyxirr import xirr

  total_booked_amt, reserve_amt, cy_booked_amt, py_booked_amt = get_amt()

  dates = myinvmt_df['Date'].values
  dates = np.append(dates, datetime.date.today().strftime('%d-%b-%y'))
  investment = myinvmt_df['Investment'].values
  dates= pd.to_datetime(dates)

  current = round(sum(df_portfolio_features['Close']*df_portfolio_features['Shares']),0) + reserve_amt
  investment_xirr = np.append(investment, current)
  cagr = round(xirr(pd.DataFrame({"dates": dates, "amounts": investment_xirr}))*100,2)

  investment = -sum(investment)
  invested = round(sum(df_portfolio_features['AvgCost']*df_portfolio_features['Shares']),0) + reserve_amt
  previous = round(sum(df_portfolio_features['Prev_Close']*df_portfolio_features['Shares']),0) + reserve_amt
  cy_invested = investment + py_booked_amt

  today_pnl_amount = current-previous
  today_pnl_percentage = round((current-previous)*100/previous,2)

  curr_pnl_amount = current-invested
  curr_pnl_percentage = round((curr_pnl_amount)*100/(cy_invested),2)

  cy_pnl_amount = cy_booked_amt + curr_pnl_amount
  cy_pnl_percentage = round((cy_pnl_amount)*100/cy_invested,2)

  overall_pnl_amount = total_booked_amt + curr_pnl_amount
  overall_pnl_percentage = round((overall_pnl_amount)*100/investment,2)

  estimate_st = round(sum(df_portfolio_features['FTT']*df_portfolio_features['Shares']),0)  + reserve_amt
  est_st_pnl_amount = estimate_st-current
  est_st_pnl_percentage = round((est_st_pnl_amount)*100/current,2)

  estimate_lt = round(sum(df_portfolio_features['LTT']*df_portfolio_features['Shares']),0)  + reserve_amt
  est_lt_pnl_amount = estimate_lt-current
  est_lt_pnl_percentage = round((est_lt_pnl_amount)*100/current,2)

  total_profit = round(sum(df_portfolio_features[df_portfolio_features['Current P/L%'] > 0]['Current']) - sum(df_portfolio_features[df_portfolio_features['Current P/L%'] > 0]['Investment']),0)
  total_loss = round(sum(df_portfolio_features[df_portfolio_features['Current P/L%'] < 0]['Current']) - sum(df_portfolio_features[df_portfolio_features['Current P/L%'] < 0]['Investment']),0)

  cy_booked_percentage = round((cy_booked_amt)*100/current,2)
  py_booked_percentage = round((py_booked_amt)*100/investment,2)
  total_booked_percentage = round((total_booked_amt)*100/investment,2)

  print('-------------------')
  print('Initial Investment: ', format_amt(investment))
  print('CY Investment: ', format_amt(cy_invested))
  print('Reserve: ', format_amt(reserve_amt))
  print('Current: ',  format_amt(current))
  print('-------------------')
  print('Today PnL: '+ '{} ({}%)'.format(format_amt(today_pnl_amount), today_pnl_percentage))
  print('Current PnL: '+ '{} ({}%)'.format(format_amt(curr_pnl_amount), curr_pnl_percentage))
  print('CY Booked + Current PnL: '+ '{} ({}%)'.format(format_amt(cy_pnl_amount), cy_pnl_percentage))
  print('-------------------')
  print('Total profit: ', format_amt(total_profit))
  print('Total loss: ', format_amt(total_loss))
  print('-------------------')
  print('Total Booked + Current PnL: '+ '{} ({}%)'.format(format_amt(overall_pnl_amount), overall_pnl_percentage))
  print('Total Booked PnL: '+ '{} ({}%)'.format(format_amt(total_booked_amt), total_booked_percentage))
  print('Curr Year Booked PnL: '+ '{} ({}%)'.format(format_amt(cy_booked_amt), cy_booked_percentage))
  print('Prev Year Booked PnL: '+ '{} ({}%)'.format(format_amt(py_booked_amt), py_booked_percentage))
  print('===================')
  print('Est FTT: ',  format_amt(estimate_st))
  print('Est FTT PnL: '+ '{} ({}%)'.format(format_amt(est_st_pnl_amount), est_st_pnl_percentage))

  print('===================')
  print('Deployed: ', format_amt(investment))

  print('Current: ', format_amt(current))

  print('CAGR/XIRR %: '+'{}%'.format(cagr))

In [8]:
# get start and end date
start_date, end_date = get_start_end_date()

# get portfolio and prospects data
mypfs_df = get_mypfs_df()
mypps_df = get_mypps_df()
myinvmt_df = get_myinvmt_df()

# merge above datasets
mypf_df = pd.merge(mypfs_df, mypps_df, on="Symbol")

# seggregate dm and sv portfolio
dm_pf = mypf_df[mypf_df['InPortfolio'] == 'DM']
sv_pf = mypf_df[mypf_df['InPortfolio'] == 'SV']

# build portfolio stock dataframe
dm_stocks = get_stock_ids(dm_pf)
sv_stocks = get_stock_ids(sv_pf)
df_stocks = pd.concat([dm_pf,sv_pf], ignore_index = True)

# arrange common and diff stock features
common_cols = ['Symbol', 'Target', 'Criteria', 'Strategy', 'CumlRnk', 'LatestQtr', 'StarStock', 'Conviction', 'Category', 'InFolio', 'XIRR', 'MBQ']
diff_cols = ['Symbol', 'AvgCost', 'Shares']
df_stocks = arrange_features(df_stocks, common_cols, diff_cols)

# get common features
stock_ids = df_stocks['Symbol'].values
df_common_features = get_common_features(stock_ids, df_stocks)

df_common_features.reset_index(drop=True, inplace=True)
df_common_features.drop(['Date'], axis=1, inplace=True)
# get and print portfolio features
df_portfolio_features = get_portfolio_features(df_common_features)

print_portfolio_stats(df_portfolio_features, myinvmt_df)

df = df_portfolio_features
#plot_pie_chart(df, 'CapType', 'Current')
list_ox40n = list(df[df['MBQ'].str.contains('OX40N', na=False)]['Symbol'].values)

Run date time (IST): 2026-08-20 12:12:33
-------------------
qualified stocks: 87
with latest results: 30
still star stocks: 19
-------------------
Initial Investment:  1.46 C
CY Investment:  1.89 C
Reserve:  3.69 L
Current:  1.58 C
-------------------
Today PnL: 77.75 K (0.49%)
Current PnL: -34.47 L (-18.25%)
CY Booked + Current PnL: -29.41 L (-15.57%)
-------------------
Total profit:  3.64 L
Total loss:  -38.11 L
-------------------
Total Booked + Current PnL: 13.46 L (9.22%)
Total Booked PnL: 47.93 L (32.82%)
Curr Year Booked PnL: 5.06 L (3.19%)
Prev Year Booked PnL: 42.87 L (29.35%)
===================
Est FTT:  2.67 C
Est FTT PnL: 1.09 C (68.55%)
===================
Deployed:  1.46 C
Current:  1.58 C
CAGR/XIRR %: 3.7%

In [9]:
# top 5 near their targets
cols = ['Symbol', 'Today P/L%', 'Current P/L%', 'FTT%', 'OTT%', 'FTT Amt', 'Current P/L', 'Current', 'FTT', 'Dev%_PE', 'RSI_14','Conviction', 'Spread%',  'CumlRnk', 'RRR Ind', 'CurrAlloc%', 'Gained%', 'Criteria', 'Strategy', 'Category']
df_tmp = df_portfolio_features[~df_portfolio_features['Symbol'].isin(['ENRIN','BLUSPRING','DIGITIDE'])]
df_tmp = df_tmp.sort_values(by = 'FTT Amt', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
66,SIEMENS,0.36,5.14,5.42,10.83,10605.0,9560.0,195655.0,4125.00,-14.90,58.0,H-LC,14.11,51.0,0.90,1.26,38.04,AR,NTT,ELECTRICAL
78,UNITDSPR,0.53,12.32,7.52,20.77,19777.0,28844.0,262988.0,1644.00,-4.30,62.0,X-MC,10.91,64.0,1.46,1.70,26.42,X40N,NTT,BREWERIES
77,TTKPRESTIG,0.15,-22.59,29.30,0.09,22857.0,-22767.0,78010.0,770.00,-5.78,43.0,M-SC,9.74,250.0,-1.00,0.50,40.41,OX40N,NTT,DURABLES
52,M&M,0.86,8.77,9.24,18.82,24189.0,21101.0,261782.0,3762.88,-6.15,60.0,X-LC,4.89,25.0,0.87,1.69,18.75,X40N,ATH,AUTO
12,BOSCH-HCIL,1.63,-21.51,27.39,-0.01,27476.0,-27492.0,100313.0,2282.00,787.59,80.0,M-SC,8.85,231.0,-1.00,0.65,70.75,OX40N,BTT,AC

In [10]:
# top 5 today
df_tmp = df_portfolio_features.sort_values(by = 'Today P/L%', ascending=False)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
62,REPCOHOME,4.91,-20.77,139.59,89.82,316857.0,-59514.0,226991.0,880.0,NaN,41.0,NaN,4.43,161.0,-0.19,1.47,9.12,XY24,NTT,FINANCE
81,VALIANTORG,4.04,-33.10,160.33,74.15,175475.0,-54159.0,109446.0,838.0,NaN,62.0,NaN,8.09,145.0,-0.31,0.71,62.87,XR,NTT,CHEMICALS
9,BANDHANBNK,3.52,-15.74,128.38,92.42,301309.0,-43858.0,234701.0,400.0,50.14,45.0,H-SC,11.65,174.0,-0.15,1.52,30.41,XY24,NTT,BANKS
0,5PAISA,3.22,-23.69,47.95,12.90,79948.0,-51763.0,166733.0,593.0,6.97,64.0,H-SC,11.86,170.0,-0.65,1.08,60.90,OX40N,NTT,FINANCE
14,CAMPUS,2.80,-24.48,76.48,33.28,96909.0,-41064.0,126711.0,393.0,NaN,50.0,NaN,10.56,218.0,-0.42,0.82,3.63,XY24,NTT,FOOTWEAR

In [11]:
# bottom 5 today
df_tmp = df_portfolio_features.sort_values(by = 'Today P/L%', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
51,LAOPALA,-6.28,-46.82,161.53,39.09,112628.0,-61379.0,69726.0,464.0,NaN,37.0,NaN,4.03,154.0,-0.54,0.45,8.18,AR,NTT,CERAMICS
29,GREENPANEL,-3.38,-57.21,234.50,43.14,183717.0,-104734.0,78344.0,537.0,NaN,25.0,NaN,11.97,225.0,-0.57,0.51,0.00,XY24,NTT,MISC
11,BERGEPAINT,-2.61,-2.87,29.02,25.32,72651.0,-7400.0,250349.0,680.0,-15.59,51.0,X-MC,4.96,68.0,-0.10,1.62,31.28,XY24,NTT,PAINTS
60,RELAXO,-2.58,-51.56,214.40,52.31,150768.0,-74839.0,70321.0,1176.0,NaN,38.0,NaN,11.97,92.0,-0.50,0.45,57.23,X40N,NTT,FOOTWEAR
59,RECLTD,-2.57,-11.11,35.83,20.74,64706.0,-22578.0,180592.0,446.0,-2.70,32.0,M-MC,2.40,191.0,-0.35,1.17,9.34,XY25,NTT,FINANCE

In [12]:
# top 5 to exit based on CumlRnk
df_tmp = df_portfolio_features[~df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])]
df_tmp = df_tmp[(df_tmp['Current P/L%'] > -1) & (df_tmp['Current P/L%'] < 1)].sort_values(by = 'CumlRnk', ascending=False)
df_tmp[cols].head()

Empty DataFrame
Columns: [Symbol, Today P/L%, Current P/L%, FTT%, OTT%, FTT Amt, Current P/L, Current, FTT, Dev%_PE, RSI_14, Conviction, Spread%, CumlRnk, RRR Ind, CurrAlloc%, Gained%, Criteria, Strategy, Category]
Index: []

In [13]:
# OX40N stocks to exit
df_tmp = df_portfolio_features[(df_portfolio_features['Symbol'].isin(list_ox40n))].sort_values(by = 'Current P/L%', ascending=False)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
25,FINCABLES,-0.31,65.87,25.35,107.91,62081.0,97251.0,244895.0,1641.55,20.71,72.0,M-SC,21.73,220.0,1.57,1.58,84.24,OX40N,ATH,CABLES
67,SIS,0.17,-4.85,27.44,21.26,28989.0,-5386.0,105646.0,528.00,103.25,38.0,H-SC,20.83,168.0,-0.19,0.68,57.08,OX40N,NTT,MISC
43,INDIGOPNTS,0.59,-17.77,21.63,0.02,31048.0,-31017.0,143542.0,1408.00,-21.49,66.0,M-SC,7.26,222.0,-1.00,0.93,62.86,OX40N,NTT,PAINTS
12,BOSCH-HCIL,1.63,-21.51,27.39,-0.01,27476.0,-27492.0,100313.0,2282.00,787.59,80.0,M-SC,8.85,231.0,-1.00,0.65,70.75,OX40N,BTT,AC
77,TTKPRESTIG,0.15,-22.59,29.30,0.09,22857.0,-22767.0,78010.0,770.00,-5.78,43.0,M-SC,9.74,250.0,-1.00,0.50,40.41,OX40N,NTT,DURABLES

In [14]:
# top 5 to book for rotation
df_tmp = df_portfolio_features[(df_portfolio_features['Current P/L%'] > 20) ].sort_values(by = 'CumlRnk', ascending=False)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
25,FINCABLES,-0.31,65.87,25.35,107.91,62081.0,97251.0,244895.0,1641.55,20.71,72.0,M-SC,21.73,220.0,1.57,1.58,84.24,OX40N,ATH,CABLES
27,GLAXO,-1.07,20.43,12.67,35.69,30408.0,40716.0,240000.0,3380.16,-9.68,82.0,X-MC,10.78,56.0,1.34,1.55,42.64,X40,ATH,PHARMA

In [15]:
# top 5 to monitor for exit
df_tmp = df_portfolio_features[~df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])]
df_tmp = df_tmp[(df_tmp['Current P/L%'] > 0) ].sort_values(by = 'Dev%_PE', ascending=False)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
25,FINCABLES,-0.31,65.87,25.35,107.91,62081.0,97251.0,244895.0,1641.55,20.71,72.0,M-SC,21.73,220.0,1.57,1.58,84.24,OX40N,ATH,CABLES
68,STARHEALTH,-0.67,12.24,31.21,47.26,98474.0,34397.0,315520.0,761.00,-1.10,48.0,H-SC,16.24,173.0,0.35,2.04,36.42,XY24,NTT,INSURANCE

In [16]:
# top 5 to book for rotation from weak conviction
df_tmp = df_portfolio_features[~df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])]
df_tmp = df_tmp[~df_tmp['Criteria'].isin(['XY25','XY24','X40', 'X40N'])].sort_values(by = 'RRR Ind', ascending=False)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
25,FINCABLES,-0.31,65.87,25.35,107.91,62081.0,97251.0,244895.0,1641.55,20.71,72.0,M-SC,21.73,220.0,1.57,1.58,84.24,OX40N,ATH,CABLES
3,ALKYLAMINE,-0.52,-17.12,132.33,92.54,110726.0,-17289.0,83674.0,4520.85,NaN,58.0,NaN,14.71,142.0,-0.16,0.54,58.89,SR,ATH,CHEMICALS
67,SIS,0.17,-4.85,27.44,21.26,28989.0,-5386.0,105646.0,528.00,103.25,38.0,H-SC,20.83,168.0,-0.19,0.68,57.08,OX40N,NTT,MISC
42,INDIAMART,0.06,-24.62,166.54,100.92,154837.0,-30363.0,92973.0,4675.60,NaN,37.0,NaN,13.86,140.0,-0.20,0.60,0.64,AR,ATH,MISC
71,TANLA,1.48,-34.49,231.63,117.25,410849.0,-93388.0,177373.0,1922.32,NaN,49.0,NaN,15.64,147.0,-0.23,1.15,55.29,AR,ATH,IT

In [17]:
# top 5 to accumulate based on lowest RSI_14
df_tmp = df_portfolio_features[df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])].sort_values(by = 'RSI_14', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
56,PGHH,-0.82,-38.19,113.56,32.01,149881.0,-81536.0,131984.0,17616.87,-54.51,28.0,X-SC,19.67,57.0,-0.54,0.85,0.00,X40,ATH,FMCG
47,ITC,-0.02,-26.34,69.29,24.70,202765.0,-104646.0,292632.0,452.00,-31.16,29.0,X-LC,10.91,1.0,-0.52,1.89,0.00,X40,NTT,FMCG
55,PAGEIND,-2.03,-7.43,43.52,32.85,108117.0,-19949.0,248430.0,50936.07,-31.21,29.0,X-MC,8.60,55.0,-0.18,1.60,18.63,X40,ATH,APPARELS
19,COLPAL,0.71,-28.12,94.58,39.86,179040.0,-74065.0,189300.0,3683.41,-12.94,31.0,X-MC,1.96,62.0,-0.41,1.22,7.08,XY25,ATH,FMCG
20,DABUR,0.05,-21.81,83.77,43.70,162494.0,-54092.0,193976.0,735.00,-32.48,33.0,X-MC,10.26,70.0,-0.33,1.25,0.05,XY24,BTT,FMCG

In [18]:
# top 5 to accumulate based on Spread and CumlRnk
df_tmp = df_portfolio_features[df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])]
df_tmp = df_tmp[(df_tmp['CumlRnk'] < 100)].sort_values(by = 'Spread%', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
19,COLPAL,0.71,-28.12,94.58,39.86,179040.0,-74065.0,189300.0,3683.41,-12.94,31.0,X-MC,1.96,62.0,-0.41,1.22,7.08,XY25,ATH,FMCG
50,KOTAKBANK,1.79,4.41,13.90,18.92,34787.0,10566.0,250268.0,452.46,-11.48,57.0,X-LC,2.17,12.0,0.30,1.62,12.60,X40,ATH,BANKS
23,DMART,0.59,-2.78,35.17,31.42,106609.0,-8664.0,303126.0,5391.45,-18.43,48.0,X-LC,2.30,14.0,-0.08,1.96,9.38,X40N,ATH,FMCG
26,GILLETTE,-0.17,-11.32,46.29,29.72,104222.0,-28746.0,225150.0,10978.86,-36.01,36.0,X-SC,3.71,83.0,-0.28,1.45,3.47,X40,ATH,FMCG
1,ABBOTINDIA,-1.20,-11.91,30.96,15.37,48781.0,-21295.0,157560.0,34390.26,-28.20,36.0,X-MC,4.05,58.0,-0.44,1.02,6.73,X40,ATH,PHARMA

In [19]:
# top 5 to accumulate based on lowest Gained%
df_tmp = df_portfolio_features[df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])].sort_values(by = 'Gained%', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
47,ITC,-0.02,-26.34,69.29,24.70,202765.0,-104646.0,292632.0,452.00,-31.16,29.0,X-LC,10.91,1.0,-0.52,1.89,0.00,X40,NTT,FMCG
56,PGHH,-0.82,-38.19,113.56,32.01,149881.0,-81536.0,131984.0,17616.87,-54.51,28.0,X-SC,19.67,57.0,-0.54,0.85,0.00,X40,ATH,FMCG
20,DABUR,0.05,-21.81,83.77,43.70,162494.0,-54092.0,193976.0,735.00,-32.48,33.0,X-MC,10.26,70.0,-0.33,1.25,0.05,XY24,BTT,FMCG
36,HINDUNILVR,0.36,-15.63,44.08,21.56,125152.0,-52597.0,283920.0,2922.00,-41.80,39.0,X-LC,6.70,9.0,-0.42,1.83,0.36,XY25,NTT,FMCG
83,VOLTAS,0.16,-4.18,51.52,45.20,94660.0,-8007.0,183735.0,1856.00,31.93,36.0,X-MC,4.78,79.0,-0.08,1.19,0.70,XY25,NTT,AC

In [20]:
# top 5 to accumulate based on lowest CurrAlloc%
df_tmp = df_portfolio_features[df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])].sort_values(by = 'CurrAlloc%', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
56,PGHH,-0.82,-38.19,113.56,32.01,149881.0,-81536.0,131984.0,17616.87,-54.51,28.0,X-SC,19.67,57.0,-0.54,0.85,0.00,X40,ATH,FMCG
2,ACC,1.39,-41.52,198.94,74.81,311922.0,-111336.0,156792.0,3906.00,-41.79,40.0,X-SC,11.71,85.0,-0.36,1.01,4.75,XY24,BTT,CEMENT
1,ABBOTINDIA,-1.20,-11.91,30.96,15.37,48781.0,-21295.0,157560.0,34390.26,-28.20,36.0,X-MC,4.05,58.0,-0.44,1.02,6.73,X40,ATH,PHARMA
40,ICICIPRULI,0.94,-16.57,56.14,30.28,92277.0,-32636.0,164369.0,787.27,-46.46,50.0,X-MC,12.34,78.0,-0.35,1.06,9.51,X40,ATH,INSURANCE
39,ICICIGI,1.04,-13.09,36.80,18.89,64000.0,-26195.0,173914.0,2244.41,-13.30,44.0,X-MC,10.37,66.0,-0.41,1.12,3.61,X40,ATH,INSURANCE

In [21]:
# top 5 to accumulate based on CumlRnk
df_tmp = df_portfolio_features.sort_values(by = 'CumlRnk', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
47,ITC,-0.02,-26.34,69.29,24.70,202765.0,-104646.0,292632.0,452.00,-31.16,29.0,X-LC,10.91,1.0,-0.52,1.89,0.00,X40,NTT,FMCG
73,TCS,0.05,-32.77,84.74,24.20,263926.0,-151819.0,311454.0,4230.71,-44.31,47.0,X-LC,14.04,2.0,-0.58,2.01,16.14,X40,ATH,IT
45,INFY,0.86,-19.60,74.61,40.38,225829.0,-73791.0,302679.0,1972.00,-40.86,50.0,X-LC,15.88,3.0,-0.33,1.96,14.62,X40,NTT,IT
75,TMPV,0.56,-23.13,85.70,42.75,274128.0,-96238.0,319869.0,600.00,-84.91,37.0,X-LC,4.55,4.0,-0.35,2.07,9.99,XY24,NTT,AUTO
33,HCLTECH,0.02,-11.37,39.87,23.97,109362.0,-35190.0,274296.0,1853.42,-13.84,56.0,X-LC,10.95,8.0,-0.32,1.77,29.44,X40,ATH,IT

In [22]:
# top 5 for average up
df_tmp = df_portfolio_features[(df_portfolio_features['Dev%_200'] > 5)].sort_values(by = 'CurrAlloc%', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
44,INDUSINDBK,-0.73,-25.61,78.64,32.89,45165.0,-19774.0,57433.0,1800.00,323.08,51.0,L-MC,13.12,258.0,-0.44,0.37,41.60,XR,NTT,BANKS
3,ALKYLAMINE,-0.52,-17.12,132.33,92.54,110726.0,-17289.0,83674.0,4520.85,NaN,58.0,NaN,14.71,142.0,-0.16,0.54,58.89,SR,ATH,CHEMICALS
12,BOSCH-HCIL,1.63,-21.51,27.39,-0.01,27476.0,-27492.0,100313.0,2282.00,787.59,80.0,M-SC,8.85,231.0,-1.00,0.65,70.75,OX40N,BTT,AC
67,SIS,0.17,-4.85,27.44,21.26,28989.0,-5386.0,105646.0,528.00,103.25,38.0,H-SC,20.83,168.0,-0.19,0.68,57.08,OX40N,NTT,MISC
81,VALIANTORG,4.04,-33.10,160.33,74.15,175475.0,-54159.0,109446.0,838.00,NaN,62.0,NaN,8.09,145.0,-0.31,0.71,62.87,XR,NTT,CHEMICALS

In [23]:
# top 5 RSP
df_tmp = df_portfolio_features.sort_values(by = 'RSP', ascending=False)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
12,BOSCH-HCIL,1.63,-21.51,27.39,-0.01,27476.0,-27492.0,100313.0,2282.00,787.59,80.0,M-SC,8.85,231.0,-1.00,0.65,70.75,OX40N,BTT,AC
25,FINCABLES,-0.31,65.87,25.35,107.91,62081.0,97251.0,244895.0,1641.55,20.71,72.0,M-SC,21.73,220.0,1.57,1.58,84.24,OX40N,ATH,CABLES
81,VALIANTORG,4.04,-33.10,160.33,74.15,175475.0,-54159.0,109446.0,838.00,NaN,62.0,NaN,8.09,145.0,-0.31,0.71,62.87,XR,NTT,CHEMICALS
27,GLAXO,-1.07,20.43,12.67,35.69,30408.0,40716.0,240000.0,3380.16,-9.68,82.0,X-MC,10.78,56.0,1.34,1.55,42.64,X40,ATH,PHARMA
38,HYUNDAI,1.53,14.19,26.05,43.94,74764.0,35669.0,287001.0,2782.73,18.18,64.0,X-LC,5.67,29.0,0.48,1.85,31.77,X40N,ATH,AUTO

In [24]:
# Top N allocation
df_tmp = df_portfolio_features.sort_values(by = 'CurrAlloc%', ascending=False)
top_n_values = [10, 25, 50]

sum_df = pd.DataFrame({
    'Top_N': top_n_values,
    'Sum_Alloc%': [df_tmp['CurrAlloc%'].head(n).sum() for n in top_n_values]
})

sum_df

   Top_N  Sum_Alloc%
0     10       19.68
1     25       44.96
2     50       77.63

In [25]:
# market-cap-wise allocation
df_tmp = df_portfolio_features[cols]
df_tmp.groupby(df_tmp['Conviction'].str[-2:])['CurrAlloc%'].sum().sort_values(ascending=False)

Conviction
LC    38.01
MC    22.20
SC    21.63
Name: CurrAlloc%, dtype: float64

In [26]:
# criteria-wise allocation
df_portfolio_features.groupby('Criteria')['CurrAlloc%'].sum().sort_values(ascending=False)

Criteria
X40      26.61
XY24     24.03
X40N     18.72
XR        9.13
OX40N     7.40
XY25      7.14
AR        6.10
SR        0.87
Name: CurrAlloc%, dtype: float64

In [27]:
# conviction-wise allocation
df_portfolio_features.groupby('Conviction')['CurrAlloc%'].sum().sort_values(ascending=False)

Conviction
X-LC    34.34
X-MC    19.63
H-SC     8.56
X-SC     7.60
M-SC     5.47
H-LC     2.86
M-MC     1.17
H-MC     1.03
M-LC     0.81
L-MC     0.37
Name: CurrAlloc%, dtype: float64

In [28]:
# sector-wise stats
df_tmp = df_portfolio_features.groupby('Category')[['CurrAlloc%', 'Current', 'Current P/L', 'FTT Amt']].sum().sort_values(by=['Current', 'Current P/L'], ascending=False)
df_tmp['Current P/L%'] = round(df_tmp['Current P/L'] * 100 / df_tmp['Current'], 2)
df_tmp['FTT%'] = round(df_tmp['FTT Amt'] * 100 / df_tmp['Current'], 2)
cols = ['CurrAlloc%', 'Current P/L%', 'FTT%']
df_tmp[cols].sort_values(by=['CurrAlloc%'], ascending=False)

               CurrAlloc%  Current P/L%    FTT%
Category
FMCG                15.36        -25.27   70.31
IT                  11.24        -37.07  105.05
FINANCE             10.82        -15.32   65.00
AUTO                 8.29         -5.36   43.10
BANKS                6.21        -11.10   59.02
MISC                 5.93        -34.44   88.51
PHARMA               5.87          8.70   17.20
INSURANCE            5.72         -4.82   41.88
PAINTS               5.45        -16.88   36.81
ELECTRICAL           4.18         -9.31   43.54
AC                   1.84        -12.50   43.00
REFINERIES           1.73        -11.45   48.88
BREWERIES            1.70         10.97    7.52
FOOTWEAR             1.65        -72.30  141.39
APPARELS             1.60         -8.03   43.52
CABLES               1.58         39.71   25.35
DURABLES             1.48        -69.17  110.32
TRAVEL               1.42       -104.19  206.44
CERAMICS             1.31        -51.30   97.27
CHEMICALS            1.25        -37.00  148.20
ENGINEERING          1.25        -25.58   83.02
CEMENT               1.01        -71.01  198.94
JEWELLERY            0.97       -112.65  186.53
HEALTHCARE           0.70        -67.99  110.15
ENTERTAINMENT        0.69        -81.33  189.47
TEXTILES             0.39        -51.28   94.41
HOTELS               0.36       -103.93  175.86

In [29]:
# money to be made criteria-wise
df_portfolio_features.groupby('Criteria')['FTT Amt'].agg(['sum', 'count']).sort_values(by='sum', ascending=False)

                sum  count
Criteria
XY24      3612053.0     19
X40       2101972.0     18
XR        1381979.0     13
X40N      1181281.0     12
AR        1062091.0      8
OX40N      648045.0     10
XY25       594294.0      5
SR         281070.0      2

In [30]:
# money to be made conviction-wise
df_portfolio_features.groupby('Conviction')['FTT Amt'].agg(['sum', 'count']).sort_values(by='sum', ascending=False)

                  sum  count
Conviction
X-LC        2408209.0     19
X-MC        1463446.0     14
X-SC        1100947.0      6
H-SC         826465.0      8
M-SC         317620.0      6
H-MC         254254.0      1
M-LC         166341.0      1
M-MC          64706.0      1
H-LC          47647.0      2
L-MC          45165.0      1

In [31]:
# money to be made criteria and conviction-wise
df_portfolio_features.groupby(['Conviction', 'Criteria'])['FTT Amt'].agg(['sum', 'count']).sort_values(by='sum', ascending=False)

                           sum  count
Conviction Criteria
X-LC       X40       1227275.0      9
X-SC       XY24       674472.0      2
H-SC       XY24       523173.0      3
X-MC       X40        505886.0      6
X-LC       XY24       455438.0      2
X-MC       X40N       448715.0      4
X-LC       X40N       409426.0      5
X-MC       XY25       273700.0      2
X-LC       XY25       255888.0      2
H-MC       XY24       254254.0      1
X-SC       X40        254103.0      2
X-MC       XY24       235145.0      2
H-SC       OX40N      212508.0      3
X-SC       X40N       172372.0      2
M-LC       XR         166341.0      1
M-SC       OX40N      143462.0      4
           XY24       116583.0      1
H-SC       XR          90784.0      2
M-MC       XY25        64706.0      1
X-LC       XR          60182.0      1
M-SC       XR          57575.0      1
H-LC       AR          47647.0      2
L-MC       XR          45165.0      1

In [32]:
# notebook execution time

end_time = time.time()
execution_time = round(end_time - start_time, 0)
print(f"Notebook execution time: {execution_time} seconds")

Notebook execution time: 43.0 seconds