<a href="https://colab.research.google.com/github/ankit-rathi/Quantvesting_v2/blob/main/myStocks_Portfolio_Analysis.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
'''
!pip install pandas==2.2.2 -qq
!pip install pyxirr -qq
!pip install ta -qq
!pip install yfinance==0.2.59 -qq
'''

'\n!pip install pandas==2.2.2 -qq\n!pip install pyxirr -qq\n!pip install ta -qq\n!pip install yfinance==0.2.59 -qq\n'

In [2]:
# import libraries

import numpy as np
import pandas as pd
import datetime
import warnings
warnings.filterwarnings('ignore')
import yfinance as yfin
import ta
import matplotlib.pyplot as plt
import requests

In [3]:
# notebook start time
import time
import datetime
import pytz

start_time = time.time()

# function to print date timestamp
def print_date_time():
  tz_NY = pytz.timezone('Asia/Kolkata')
  datetime_NY = datetime.datetime.now(tz_NY)
  print("Run date time (IST):", datetime_NY.strftime("%Y-%m-%d %H:%M:%S"))

In [4]:
# function to get booked and reserved amount
def get_amt():
  # fetch the JSON data from the URL
  url = "https://raw.githubusercontent.com/ankit-rathi/Tradevesting_v1/main/data/myPortfolioAmts.json"
  response = requests.get(url)
  pf_amts = response.json()  # parse the JSON data

  # extract values from the JSON
  py_booked_amt_dm = pf_amts["py_booked_amt_dm"]
  py_booked_amt_sv = pf_amts["py_booked_amt_sv"]
  cy_booked_amt_dm = pf_amts["cy_booked_amt_dm"]
  cy_booked_amt_sv = pf_amts["cy_booked_amt_sv"]
  reserve_amt_dm = pf_amts["reserve_amt_dm"]
  reserve_amt_sv = pf_amts["reserve_amt_sv"]

  # perform calculations
  py_booked_amt = py_booked_amt_dm + py_booked_amt_sv
  cy_booked_amt = cy_booked_amt_dm + cy_booked_amt_sv
  reserve_amt = reserve_amt_dm + reserve_amt_sv
  total_booked_amt = py_booked_amt + cy_booked_amt

  return total_booked_amt, reserve_amt, cy_booked_amt, py_booked_amt

gen_output = 0

In [5]:
# function to format the amount
def format_amt(number):
    abs_number = abs(number)

    if abs_number >= 1_00_00_000:  # Crores
        formatted_amt = f"{number / 1_00_00_000:.2f} C"
    elif abs_number >= 1_00_000:  # Lakhs
        formatted_amt = f"{number / 1_00_000:.2f} L"
    elif abs_number >= 1_000:  # Thousands
        formatted_amt = f"{number / 1_000:.2f} K"
    else:
        formatted_amt = f"{number:.2f}"

    return formatted_amt

# function to set start and end date
def get_start_end_date():
  start_date = (datetime.date.today() + datetime.timedelta(days=-365)).strftime('%Y-%m-%d')
  end_date = (datetime.date.today() + datetime.timedelta(days=1)).strftime('%Y-%m-%d')
  return start_date, end_date

# function to fetch my portfolio csv
def get_mypfs_df():
  mypfs_df = pd.read_csv('https://raw.githubusercontent.com/ankit-rathi/Tradevesting_v1/main/data/myPortfolioStocks.csv')
  return mypfs_df

# function to fetch my prospects csv
def get_mypps_df():
  mypps_df = pd.read_csv('https://raw.githubusercontent.com/ankit-rathi/Tradevesting_v1/main/data/myProspectsScrips.csv')
  return mypps_df

# function to fetch screener data
def get_myscreen_df():
  myscreen_df = pd.read_csv('https://raw.githubusercontent.com/ankit-rathi/Tradevesting_v1/main/data/myScreenerDB.csv')
  return myscreen_df

# function to fetch momentum data
def get_myinvmt_df():
  myinvmt_df = pd.read_csv('https://raw.githubusercontent.com/ankit-rathi/Tradevesting_v1/main/data/myInvestments.csv')
  return myinvmt_df

# function to get the stock ids
def get_stock_ids(df_pf):
  stock_n100 = df_pf['Symbol'].unique()

  exclude = ['CADILAHC','MMTC', 'MASFIN']

  stock_ids = df_pf[~df_pf['Symbol'].isin(exclude) ]['Symbol'].unique()

  #mypf = mypf[mypf.Forecast.notnull()]
  #stock_ids = mypf['Symbol'].unique()

  #stock_ids.sort()
  return stock_ids

# get features from screener data
def get_screener_features():
  myscreen_df = get_myscreen_df()
  cols = ['Symbol', 'EPS', 'MedPE', 'ROCE%', 'ROE%', 'CapType']
  return myscreen_df[cols]

# get relative strength
def get_relative_strength(stock_list):

    # Dictionary to store stock tickers and their corresponding percentage price change
    stock_changes = {}

    # Loop through each stock and fetch its price data
    for stock in stock_list:
        try:
            # Download the stock data for the given date range
            stock_data = yfin.Ticker(stock + '.NS').history(period='1mo', interval='1d')[map(str.title, ['open', 'close', 'low', 'high', 'volume'])]

            # Calculate the percentage change for the stock
            if len(stock_data) > 0:
                start_price = stock_data['Close'].iloc[0]
                end_price = stock_data['Close'].iloc[-1]
                percent_change = round(((end_price - start_price) / start_price) * 100, 2)
                stock_changes[stock] = percent_change
            else:
                stock_changes[stock] = np.nan  # If no data is available, set to NaN

        except Exception as e:
            print(f"Error fetching data for {stock}: {e}")
            stock_changes[stock] = np.nan

    # Create a DataFrame with stock tickers and their percentage changes
    df = pd.DataFrame(list(stock_changes.items()), columns=['Symbol', 'Percent_Change'])

    # Drop any stocks with missing data (NaN values)
    df = df.dropna()

    # Calculate the percentile rank based on percentage change
    df['RSP'] = round(df['Percent_Change'].rank(pct=True) * 100, 2)
    cols = ['Symbol', 'RSP']
    df = df[cols]
    # Sort by percentile rank (optional)
    df = df.sort_values(by='RSP', ascending=False).reset_index(drop=True)

    return df

In [6]:
# function to get stock technicals
def stock_prec_dev(stock_symbol):
    #stock_symbol = 'ULTRACEMCO.NS'
    short_window = 20
    mid_window = 50
    long_window = 200
    moving_avg = 'SMA'

    start = datetime.datetime(*map(int, start_date.split('-')))
    end = datetime.datetime(*map(int, end_date.split('-')))

    stock_df = yfin.Ticker(stock_symbol + '.NS').history(period='max', interval='1d')[map(str.title, ['open', 'close', 'low', 'high', 'volume'])]

    stock_df['Max'] = round(max(stock_df['Close']),2)
    stock_df = stock_df[(stock_df.index <= end_date) & (stock_df.index >= start_date)]
    stock_df['200_SMA'] = round(stock_df['Close'].rolling(window = 200, min_periods = 1).mean(),0)
    stock_df['Dev%_200'] = round((stock_df['Close'] - stock_df['200_SMA'])*100/stock_df['200_SMA'],2)
    stock_df.dropna(axis = 0, inplace = True) # remove any null rows

    stock_df['20_SMA'] = stock_df['Close'].rolling(window=20).mean()
    stock_df['50_SMA'] = stock_df['Close'].rolling(window=50).mean()
    stock_df['Symbol'] = stock_symbol

    stock_df['Close'] = round(stock_df['Close'],2)
    stock_df['Min'] = round(min(stock_df['Close']),2)
    stock_df['RSI_14'] = ta.momentum.RSIIndicator(close=stock_df['Close'], window=14).rsi()
    stock_df['RSI_14'] = round(stock_df['RSI_14'],0)
    stock_df['Prev_Close'] = stock_df['Close'].shift(1)
    stock_df.drop(['Open', 'Low', 'High', 'Volume'], axis=1, inplace=True)
    stock_df = stock_df.tail(1)

    max_SMA = max(stock_df['20_SMA'].item(), stock_df['50_SMA'].item(), stock_df['200_SMA'].item())
    min_SMA = min(stock_df['20_SMA'].item(), stock_df['50_SMA'].item(), stock_df['200_SMA'].item())
    ABS_Spread = max_SMA - min_SMA
    stock_df['Spread%'] = round((ABS_Spread / stock_df['200_SMA'].item()) * 100,2)

    return stock_df

# function to compute stock attributes
def get_common_features(stock_ids, df_mypf):

  df_prec_dev = pd.DataFrame()
  df_tmp = get_screener_features()
  df_rs = get_relative_strength(stock_ids)

  for stock_id in stock_ids:
      tmp = stock_prec_dev(stock_id)
      tmp = tmp.reset_index()
      df_prec_dev = pd.concat([df_prec_dev, tmp], ignore_index = True)
  df_prec_dev = pd.merge(df_prec_dev, df_mypf, on= 'Symbol')
  df_prec_dev = pd.merge(df_prec_dev, df_tmp, on= 'Symbol', how='left')
  df_prec_dev = pd.merge(df_prec_dev, df_rs, on= 'Symbol', how='left')
  #print(df_prec_dev.columns)
  df_prec_dev['Curr_PE'] = round(df_prec_dev['Close']/df_prec_dev['EPS'],1)
  df_prec_dev['Dev%_PE'] = round((df_prec_dev['Curr_PE'] - df_prec_dev['MedPE'])*100/df_prec_dev['MedPE'],2)
  df_prec_dev['Conviction'] = df_prec_dev['Conviction'] + '-' + df_prec_dev['CapType']
  return df_prec_dev

# function to arrange stock features
def arrange_features(df_stocks, common_cols, diff_cols):
  df_stocks_common = df_stocks[common_cols].drop_duplicates()
  df_stocks_diff = df_stocks[diff_cols]
  df_stocks_diff['Investment'] = df_stocks_diff['AvgCost'] * df_stocks_diff['Shares']
  df_stocks_diff = df_stocks_diff.groupby(['Symbol'])[['Shares', 'Investment']].aggregate(['sum']).reset_index()
  df_stocks_diff.columns = ['Symbol', 'Shares', 'Investment']
  df_stocks_diff['AvgCost'] = round(df_stocks_diff['Investment']/df_stocks_diff['Shares'],2)
  df_stocks = pd.merge(df_stocks_diff, df_stocks_common, on='Symbol')
  return df_stocks

# plot fact distribution across dimension
def plot_pie_chart(df, dimension, fact):
  # grouping the data by category and calculating the sum of fact for each type
  grouped_data = df.groupby(dimension)[fact].sum()

  # sorting the grouped data in descending order
  grouped_data = grouped_data.sort_values(ascending=False)

  # creating a pie chart
  grouped_data.plot.pie(autopct='%1.1f%%', startangle=90, figsize=(6, 6))

  # adding a title and displaying the plot
  plt.title(f'{dimension} {fact} Distribution')
  plt.ylabel('')  # To hide the y-label
  plt.show()

In [7]:
# function to get portfolio features

def get_portfolio_features(df_common_features):

  print_date_time()
  print('-------------------')

  #df_common_features["Target"] = df_common_features["Target"].fillna(df_common_features["Max"])
  df_common_features['NTT'] = np.where(df_common_features['Strategy']== 'NTT', df_common_features["Target"], df_common_features['Max'])
  df_common_features['LTT'] = np.where(df_common_features['Strategy']== 'BTT', df_common_features["Target"], df_common_features['Max'])
  df_common_features['BOL'] = df_common_features['Min']

  tmp_df = df_common_features[df_common_features['Symbol'].isin(mypf_df[mypf_df['InPortfolio'] != 'NA'].Symbol.values)]
  print('qualified stocks: '+str(len(tmp_df['Symbol'].unique())))
  tmp_df1 = tmp_df[tmp_df['LatestQtr'] == 1]
  print('with latest results: '+str(len(tmp_df1['Symbol'].unique())))
  tmp_df1 = tmp_df1[tmp_df1['StarStock'] == 1]
  print('still star stocks: '+str(len(tmp_df1['Symbol'].unique())))
  tmp_df['Investment'] = tmp_df['AvgCost'] * tmp_df['Shares']
  tmp_df['Current'] = round(tmp_df['Close'] * tmp_df['Shares'],0)
  tmp_df['Previous'] = tmp_df['Prev_Close'] * tmp_df['Shares']
  tmp_df['EstimatedST'] = tmp_df['NTT'] * tmp_df['Shares']
  tmp_df['EstimatedLT'] = tmp_df['LTT'] * tmp_df['Shares']
  tmp_df['Current P/L'] = round((tmp_df['Current'] - tmp_df['Investment']),0)
  tmp_df['Today P/L%'] = round((tmp_df['Current'] - tmp_df['Previous'])*100/tmp_df['Previous'],2)
  tmp_df['Current P/L%'] = round((tmp_df['Current'] - tmp_df['Investment'])*100/tmp_df['Investment'],2)
  tmp_df['EstimatedST P/L%'] = round((tmp_df['EstimatedST'] - tmp_df['Investment'])*100/tmp_df['Investment'],2)
  tmp_df['EstimatedLT P/L%'] = round((tmp_df['EstimatedLT'] - tmp_df['Investment'])*100/tmp_df['Investment'],2)
  tmp_df['NTT%'] = round((tmp_df['NTT'] - tmp_df['Close'])*100/tmp_df['Close'],2)
  tmp_df['LTT%'] = round((tmp_df['LTT'] - tmp_df['Close'])*100/tmp_df['Close'],2)
  tmp_df['Gained%'] = round((tmp_df['Close'] - tmp_df['BOL'])*100/tmp_df['BOL'],2)
  investment = round(sum(tmp_df['AvgCost']*tmp_df['Shares']),0)
  current = round(sum(tmp_df['Close']*tmp_df['Shares']),0)
  tmp_df['InitAlloc%'] = round(tmp_df['Investment']*100/investment,2)
  tmp_df['CurrAlloc%'] = round(tmp_df['Current']*100/current,2)
  tmp_df['FTT'] = tmp_df['LTT']
  tmp_df.loc[tmp_df['Strategy'] == 'NTT', 'FTT'] = tmp_df['NTT']
  tmp_df['FTT%'] = tmp_df['LTT%']
  tmp_df.loc[tmp_df['Strategy'] == 'NTT', 'FTT%'] = tmp_df['NTT%']
  tmp_df['FTT Amt'] = round(tmp_df['FTT%'] * tmp_df['Current']/100,0)
  tmp_df['OTT%'] = round((tmp_df['FTT'] - tmp_df['AvgCost'])*100/tmp_df['AvgCost'],2)
  tmp_df['RRR Ind'] = round(tmp_df['Current P/L']/tmp_df['FTT Amt'],2)
  tmp_df['Risk Ind'] = round(tmp_df['Current P/L%']*tmp_df['CurrAlloc%'],0)

  return tmp_df

# function to print portfolio features
def print_portfolio_stats(df_portfolio_features, myinvmt_df):
  from pyxirr import xirr

  total_booked_amt, reserve_amt, cy_booked_amt, py_booked_amt = get_amt()

  dates = myinvmt_df['Date'].values
  dates = np.append(dates, datetime.date.today().strftime('%d-%b-%y'))
  investment = myinvmt_df['Investment'].values
  dates= pd.to_datetime(dates)

  current = round(sum(df_portfolio_features['Close']*df_portfolio_features['Shares']),0) + reserve_amt
  investment_xirr = np.append(investment, current)
  cagr = round(xirr(pd.DataFrame({"dates": dates, "amounts": investment_xirr}))*100,2)

  investment = -sum(investment)
  invested = round(sum(df_portfolio_features['AvgCost']*df_portfolio_features['Shares']),0) + reserve_amt
  previous = round(sum(df_portfolio_features['Prev_Close']*df_portfolio_features['Shares']),0) + reserve_amt
  cy_invested = investment + py_booked_amt

  today_pnl_amount = current-previous
  today_pnl_percentage = round((current-previous)*100/previous,2)

  curr_pnl_amount = current-invested
  curr_pnl_percentage = round((curr_pnl_amount)*100/(cy_invested),2)

  cy_pnl_amount = cy_booked_amt + curr_pnl_amount
  cy_pnl_percentage = round((cy_pnl_amount)*100/cy_invested,2)

  overall_pnl_amount = total_booked_amt + curr_pnl_amount
  overall_pnl_percentage = round((overall_pnl_amount)*100/investment,2)

  estimate_st = round(sum(df_portfolio_features['FTT']*df_portfolio_features['Shares']),0)  + reserve_amt
  est_st_pnl_amount = estimate_st-current
  est_st_pnl_percentage = round((est_st_pnl_amount)*100/current,2)

  estimate_lt = round(sum(df_portfolio_features['LTT']*df_portfolio_features['Shares']),0)  + reserve_amt
  est_lt_pnl_amount = estimate_lt-current
  est_lt_pnl_percentage = round((est_lt_pnl_amount)*100/current,2)

  total_profit = round(sum(df_portfolio_features[df_portfolio_features['Current P/L%'] > 0]['Current']) - sum(df_portfolio_features[df_portfolio_features['Current P/L%'] > 0]['Investment']),0)
  total_loss = round(sum(df_portfolio_features[df_portfolio_features['Current P/L%'] < 0]['Current']) - sum(df_portfolio_features[df_portfolio_features['Current P/L%'] < 0]['Investment']),0)

  cy_booked_percentage = round((cy_booked_amt)*100/current,2)
  py_booked_percentage = round((py_booked_amt)*100/investment,2)
  total_booked_percentage = round((total_booked_amt)*100/investment,2)

  print('-------------------')
  print('Initial Investment: ', format_amt(investment))
  print('CY Investment: ', format_amt(cy_invested))
  print('Reserve: ', format_amt(reserve_amt))
  print('Current: ',  format_amt(current))
  print('-------------------')
  print('Today PnL: '+ '{} ({}%)'.format(format_amt(today_pnl_amount), today_pnl_percentage))
  print('Current PnL: '+ '{} ({}%)'.format(format_amt(curr_pnl_amount), curr_pnl_percentage))
  print('CY Booked + Current PnL: '+ '{} ({}%)'.format(format_amt(cy_pnl_amount), cy_pnl_percentage))
  print('-------------------')
  print('Total profit: ', format_amt(total_profit))
  print('Total loss: ', format_amt(total_loss))
  print('-------------------')
  print('Total Booked + Current PnL: '+ '{} ({}%)'.format(format_amt(overall_pnl_amount), overall_pnl_percentage))
  print('Total Booked PnL: '+ '{} ({}%)'.format(format_amt(total_booked_amt), total_booked_percentage))
  print('Curr Year Booked PnL: '+ '{} ({}%)'.format(format_amt(cy_booked_amt), cy_booked_percentage))
  print('Prev Year Booked PnL: '+ '{} ({}%)'.format(format_amt(py_booked_amt), py_booked_percentage))
  print('===================')
  print('Est FTT: ',  format_amt(estimate_st))
  print('Est FTT PnL: '+ '{} ({}%)'.format(format_amt(est_st_pnl_amount), est_st_pnl_percentage))

  print('===================')
  print('Deployed: ', format_amt(investment))

  print('Current: ', format_amt(current))

  print('CAGR/XIRR %: '+'{}%'.format(cagr))

In [8]:
# get start and end date
start_date, end_date = get_start_end_date()

# get portfolio and prospects data
mypfs_df = get_mypfs_df()
mypps_df = get_mypps_df()
myinvmt_df = get_myinvmt_df()

# merge above datasets
mypf_df = pd.merge(mypfs_df, mypps_df, on="Symbol")

# seggregate dm and sv portfolio
dm_pf = mypf_df[mypf_df['InPortfolio'] == 'DM']
sv_pf = mypf_df[mypf_df['InPortfolio'] == 'SV']

# build portfolio stock dataframe
dm_stocks = get_stock_ids(dm_pf)
sv_stocks = get_stock_ids(sv_pf)
df_stocks = pd.concat([dm_pf,sv_pf], ignore_index = True)

# arrange common and diff stock features
common_cols = ['Symbol', 'Target', 'Criteria', 'Strategy', 'CumlRnk', 'LatestQtr', 'StarStock', 'Conviction', 'Category', 'InFolio', 'XIRR', 'MBQ']
diff_cols = ['Symbol', 'AvgCost', 'Shares']
df_stocks = arrange_features(df_stocks, common_cols, diff_cols)

# get common features
stock_ids = df_stocks['Symbol'].values
df_common_features = get_common_features(stock_ids, df_stocks)

df_common_features.reset_index(drop=True, inplace=True)
df_common_features.drop(['Date'], axis=1, inplace=True)
# get and print portfolio features
df_portfolio_features = get_portfolio_features(df_common_features)

print_portfolio_stats(df_portfolio_features, myinvmt_df)

df = df_portfolio_features
#plot_pie_chart(df, 'CapType', 'Current')
list_ox40n = list(df[df['MBQ'].str.contains('OX40N', na=False)]['Symbol'].values)

Run date time (IST): 2026-03-12 14:39:11
-------------------
qualified stocks: 86
with latest results: 26
still star stocks: 15
-------------------
Initial Investment:  1.36 C
CY Investment:  1.62 C
Reserve:  66.25 K
Current:  1.36 C
-------------------
Today PnL: -47.46 K (-0.35%)
Current PnL: -40.73 L (-25.07%)
CY Booked + Current PnL: -25.05 L (-15.42%)
-------------------
Total profit:  1.20 L
Total loss:  -41.93 L
-------------------
Total Booked + Current PnL: 1.93 L (1.42%)
Total Booked PnL: 42.66 L (31.48%)
Curr Year Booked PnL: 15.68 L (11.51%)
Prev Year Booked PnL: 26.98 L (19.91%)
===================
Est FTT:  2.47 C
Est FTT PnL: 1.11 C (81.57%)
===================
Deployed:  1.36 C
Current:  1.36 C
CAGR/XIRR %: 0.25%

In [9]:
# top 5 near their targets
cols = ['Symbol', 'Today P/L%', 'Current P/L%', 'FTT%', 'OTT%', 'FTT Amt', 'Current P/L', 'Current', 'FTT', 'Dev%_PE', 'RSI_14','Conviction', 'Spread%',  'CumlRnk', 'RRR Ind', 'CurrAlloc%', 'Gained%', 'Criteria', 'Strategy', 'Category']
df_tmp = df_portfolio_features[~df_portfolio_features['Symbol'].isin(['ENRIN','BLUSPRING','DIGITIDE'])]
df_tmp = df_tmp.sort_values(by = 'FTT Amt', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
19,COALINDIA,5.43,15.82,1.59,17.67,2771.0,23810.0,174270.0,478.51,39.17,70.0,L-LC,12.21,185.0,8.59,1.29,35.33,XY25,ATH,MINING
77,TTKPRESTIG,7.33,-25.29,33.98,0.09,25582.0,-25491.0,75286.0,770.00,74.81,60.0,M-SC,15.27,250.0,-1.00,0.56,27.20,OX40N,NTT,DURABLES
50,MASFIN,0.64,-6.51,30.03,21.57,27509.0,-6375.0,91605.0,397.04,-19.60,40.0,H-SC,4.18,167.0,-0.23,0.68,27.08,XR,ATH,FINANCE
37,ICICIGI,-1.34,-2.00,21.78,19.34,42711.0,-4009.0,196100.0,2252.93,-17.63,40.0,X-MC,1.78,66.0,-0.09,1.45,11.84,X40,ATH,INSURANCE
78,UNITDSPR,-1.06,0.45,20.23,20.77,47580.0,1049.0,235193.0,1644.00,-10.94,48.0,X-MC,1.41,64.0,0.02,1.74,7.19,X40N,NTT,BREWERIES

In [10]:
# top 5 today
df_tmp = df_portfolio_features.sort_values(by = 'Today P/L%', ascending=False)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
77,TTKPRESTIG,7.33,-25.29,33.98,0.09,25582.0,-25491.0,75286.0,770.00,74.81,60.0,M-SC,15.27,250.0,-1.00,0.56,27.20,OX40N,NTT,DURABLES
30,GREENPANEL,6.19,-44.84,159.48,43.14,161062.0,-82086.0,100992.0,537.00,126.10,47.0,M-SC,19.86,225.0,-0.51,0.75,6.19,XY24,NTT,MISC
19,COALINDIA,5.43,15.82,1.59,17.67,2771.0,23810.0,174270.0,478.51,39.17,70.0,L-LC,12.21,185.0,8.59,1.29,35.33,XY25,ATH,MINING
57,RECLTD,3.36,-6.81,29.56,20.74,55968.0,-13832.0,189338.0,446.00,3.52,48.0,M-MC,5.06,191.0,-0.25,1.40,6.12,XY25,NTT,FINANCE
46,JIOFIN,2.05,-19.16,58.87,28.43,141973.0,-57163.0,241164.0,387.00,-20.40,39.0,X-LC,15.39,34.0,-0.40,1.78,14.26,XY24,BTT,FINANCE

In [11]:
# bottom 5 today
df_tmp = df_portfolio_features.sort_values(by = 'Today P/L%', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
69,SURYODAY,-4.80,-27.32,69.28,23.03,90169.0,-48919.0,130152.0,216.00,42.54,47.0,H-SC,7.46,166.0,-0.54,0.96,29.14,XR,NTT,BANKS
42,INDUSINDBK,-4.37,-38.07,114.58,32.89,54785.0,-29392.0,47814.0,1800.00,-324.79,31.0,L-MC,10.63,258.0,-0.54,0.35,31.68,XR,NTT,BANKS
81,VBL,-3.85,-16.24,61.98,35.67,163966.0,-51295.0,264547.0,671.64,-26.02,31.0,X-LC,5.06,13.0,-0.31,1.95,0.00,X40N,ATH,FMCG
21,COLPAL,-3.67,-24.81,88.21,41.51,174673.0,-65345.0,198020.0,3726.84,-8.99,32.0,X-MC,4.12,62.0,-0.37,1.46,0.00,XY25,ATH,FMCG
10,BAJAJHLDNG,-3.16,-11.88,46.64,29.22,78138.0,-22590.0,167535.0,14451.52,-18.46,25.0,X-LC,12.31,28.0,-0.29,1.24,0.00,X40,ATH,FINANCE

In [12]:
# top 5 to exit based on CumlRnk
df_tmp = df_portfolio_features[~df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])]
df_tmp = df_tmp[(df_tmp['Current P/L%'] > -1) & (df_tmp['Current P/L%'] < 1)].sort_values(by = 'CumlRnk', ascending=False)
df_tmp[cols].head()

Empty DataFrame
Columns: [Symbol, Today P/L%, Current P/L%, FTT%, OTT%, FTT Amt, Current P/L, Current, FTT, Dev%_PE, RSI_14, Conviction, Spread%, CumlRnk, RRR Ind, CurrAlloc%, Gained%, Criteria, Strategy, Category]
Index: []

In [13]:
# OX40N stocks to exit
df_tmp = df_portfolio_features[(df_portfolio_features['Symbol'].isin(list_ox40n))].sort_values(by = 'Current P/L%', ascending=False)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
27,FINCABLES,1.37,14.00,82.38,107.91,138653.0,20665.0,168309.0,1641.55,2.49,57.0,M-SC,7.76,220.0,0.15,1.24,26.62,OX40N,ATH,CABLES
77,TTKPRESTIG,7.33,-25.29,33.98,0.09,25582.0,-25491.0,75286.0,770.00,74.81,60.0,M-SC,15.27,250.0,-1.00,0.56,27.20,OX40N,NTT,DURABLES
66,SIS,-0.84,-33.62,82.67,21.26,60934.0,-37324.0,73708.0,528.00,1726.42,36.0,H-SC,10.59,168.0,-0.61,0.54,1.61,OX40N,NTT,MISC
48,KANSAINER,0.97,-36.98,80.05,13.47,136050.0,-99711.0,169956.0,340.00,-45.81,31.0,H-SC,16.71,162.0,-0.73,1.25,1.89,XY24,NTT,PAINTS
72,TATAELXSI,0.31,-37.21,110.26,32.03,91277.0,-49052.0,82783.0,9161.00,-21.54,30.0,H-SC,17.24,158.0,-0.54,0.61,1.24,OX40N,NTT,IT

In [14]:
# top 5 to book for rotation
df_tmp = df_portfolio_features[(df_portfolio_features['Current P/L%'] > 20) ].sort_values(by = 'CumlRnk', ascending=False)
df_tmp[cols].head()

Empty DataFrame
Columns: [Symbol, Today P/L%, Current P/L%, FTT%, OTT%, FTT Amt, Current P/L, Current, FTT, Dev%_PE, RSI_14, Conviction, Spread%, CumlRnk, RRR Ind, CurrAlloc%, Gained%, Criteria, Strategy, Category]
Index: []

In [15]:
# top 5 to monitor for exit
df_tmp = df_portfolio_features[~df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])]
df_tmp = df_tmp[(df_tmp['Current P/L%'] > 0) ].sort_values(by = 'Dev%_PE', ascending=False)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
19,COALINDIA,5.43,15.82,1.59,17.67,2771.0,23810.0,174270.0,478.51,39.17,70.0,L-LC,12.21,185.0,8.59,1.29,35.33,XY25,ATH,MINING
27,FINCABLES,1.37,14.00,82.38,107.91,138653.0,20665.0,168309.0,1641.55,2.49,57.0,M-SC,7.76,220.0,0.15,1.24,26.62,OX40N,ATH,CABLES
1,ABB,1.93,17.44,23.95,45.57,73586.0,45629.0,307248.0,7934.00,-24.53,69.0,H-MC,10.55,125.0,0.62,2.27,36.44,AR,NTT,ELECTRICAL

In [16]:
# top 5 to book for rotation from weak conviction
df_tmp = df_portfolio_features[~df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])]
df_tmp = df_tmp[~df_tmp['Criteria'].isin(['XY25','XY24','X40', 'X40N'])].sort_values(by = 'RRR Ind', ascending=False)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
1,ABB,1.93,17.44,23.95,45.57,73586.0,45629.0,307248.0,7934.00,-24.53,69.0,H-MC,10.55,125.0,0.62,2.27,36.44,AR,NTT,ELECTRICAL
27,FINCABLES,1.37,14.00,82.38,107.91,138653.0,20665.0,168309.0,1641.55,2.49,57.0,M-SC,7.76,220.0,0.15,1.24,26.62,OX40N,ATH,CABLES
40,INDIAMART,-1.12,-9.47,128.36,106.72,143314.0,-11686.0,111650.0,4810.62,-59.18,41.0,H-SC,9.45,140.0,-0.08,0.82,11.69,AR,ATH,MISC
85,ZYDUSLIFE,-0.38,-3.17,40.07,35.63,81315.0,-6641.0,202933.0,1286.17,-15.77,53.0,H-MC,5.01,120.0,-0.08,1.50,12.98,AR,ATH,PHARMA
84,WIPRO,0.16,-16.92,107.35,72.27,151126.0,-28669.0,140779.0,420.00,-25.02,35.0,M-LC,15.05,98.0,-0.19,1.04,3.66,XR,NTT,IT

In [17]:
# top 5 to accumulate based on lowest RSI_14
df_tmp = df_portfolio_features[df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])].sort_values(by = 'RSI_14', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
58,RELAXO,0.26,-60.44,285.01,52.31,163667.0,-87735.0,57425.0,1176.00,-57.89,20.0,X-SC,19.51,92.0,-0.54,0.42,0.26,X40N,NTT,FOOTWEAR
3,ACC,-1.54,-35.82,172.38,74.81,296632.0,-96048.0,172080.0,3906.00,-54.32,21.0,X-SC,12.81,85.0,-0.32,1.27,0.00,XY24,BTT,CEMENT
12,BATAINDIA,-0.38,-53.82,192.76,35.20,114546.0,-69246.0,59424.0,2096.00,-22.02,21.0,X-SC,26.23,91.0,-0.60,0.44,0.00,X40,NTT,FOOTWEAR
73,TCS,-0.49,-27.99,75.78,26.57,252798.0,-129679.0,333594.0,4311.59,-39.04,21.0,X-LC,14.43,2.0,-0.51,2.46,0.00,X40,ATH,IT
8,AWL,-0.56,-38.57,171.86,67.02,376196.0,-137412.0,218897.0,485.00,-66.89,22.0,X-SC,23.35,81.0,-0.37,1.62,1.59,XY24,NTT,FMCG

In [18]:
# top 5 to accumulate based on Spread and CumlRnk
df_tmp = df_portfolio_features[df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])]
df_tmp = df_tmp[(df_tmp['CumlRnk'] < 100)].sort_values(by = 'Spread%', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
78,UNITDSPR,-1.06,0.45,20.23,20.77,47580.0,1049.0,235193.0,1644.00,-10.94,48.0,X-MC,1.41,64.0,0.02,1.74,7.19,X40N,NTT,BREWERIES
22,DABUR,-2.43,-9.99,59.64,43.70,133173.0,-24774.0,223294.0,735.00,-18.36,31.0,X-MC,1.51,70.0,-0.19,1.65,3.56,XY24,BTT,FMCG
75,TMPV,-2.86,-25.85,84.19,36.58,222142.0,-91983.0,263858.0,600.00,-84.72,33.0,X-LC,1.78,4.0,-0.41,1.95,0.00,XY24,NTT,AUTO
37,ICICIGI,-1.34,-2.00,21.78,19.34,42711.0,-4009.0,196100.0,2252.93,-17.63,40.0,X-MC,1.78,66.0,-0.09,1.45,11.84,X40,ATH,INSURANCE
59,RELIANCE,0.81,-10.04,39.29,25.30,71029.0,-20182.0,180781.0,1952.00,-12.34,47.0,X-LC,2.71,21.0,-0.28,1.33,20.70,XY25,BTT,REFINERIES

In [19]:
# top 5 to accumulate based on lowest Gained%
df_tmp = df_portfolio_features[df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])].sort_values(by = 'Gained%', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
3,ACC,-1.54,-35.82,172.38,74.81,296632.0,-96048.0,172080.0,3906.00,-54.32,21.0,X-SC,12.81,85.0,-0.32,1.27,0.0,XY24,BTT,CEMENT
12,BATAINDIA,-0.38,-53.82,192.76,35.20,114546.0,-69246.0,59424.0,2096.00,-22.02,21.0,X-SC,26.23,91.0,-0.60,0.44,0.0,X40,NTT,FOOTWEAR
10,BAJAJHLDNG,-3.16,-11.88,46.64,29.22,78138.0,-22590.0,167535.0,14451.52,-18.46,25.0,X-LC,12.31,28.0,-0.29,1.24,0.0,X40,ATH,FINANCE
13,BERGEPAINT,-1.96,-22.19,61.06,25.32,122453.0,-57204.0,200545.0,680.00,-26.43,25.0,X-MC,15.68,68.0,-0.47,1.48,0.0,XY24,NTT,PAINTS
21,COLPAL,-3.67,-24.81,88.21,41.51,174673.0,-65345.0,198020.0,3726.84,-8.99,32.0,X-MC,4.12,62.0,-0.37,1.46,0.0,XY25,ATH,FMCG

In [20]:
# top 5 to accumulate based on lowest CurrAlloc%
df_tmp = df_portfolio_features[df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])].sort_values(by = 'CurrAlloc%', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
58,RELAXO,0.26,-60.44,285.01,52.31,163667.0,-87735.0,57425.0,1176.00,-57.89,20.0,X-SC,19.51,92.0,-0.54,0.42,0.26,X40N,NTT,FOOTWEAR
12,BATAINDIA,-0.38,-53.82,192.76,35.20,114546.0,-69246.0,59424.0,2096.00,-22.02,21.0,X-SC,26.23,91.0,-0.60,0.44,0.00,X40,NTT,FOOTWEAR
54,QUESS,-0.98,-21.56,121.70,73.90,101946.0,-23025.0,83768.0,424.00,-57.58,42.0,X-SC,18.33,80.0,-0.23,0.62,3.33,XY24,NTT,MISC
36,HONAUT,0.13,-20.43,90.15,51.31,138335.0,-39388.0,153450.0,58357.33,-33.85,43.0,X-SC,13.77,90.0,-0.28,1.13,3.33,X40N,ATH,ELECTRICAL
2,ABBOTINDIA,-2.22,-10.78,32.34,18.07,51605.0,-19285.0,159570.0,35195.00,-24.04,44.0,X-MC,11.12,58.0,-0.37,1.18,1.16,X40,ATH,PHARMA

In [21]:
# top 5 to accumulate based on CumlRnk
df_tmp = df_portfolio_features.sort_values(by = 'CumlRnk', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
45,ITC,-1.08,-19.49,47.88,19.06,131125.0,-66304.0,273862.0,452.00,-55.92,35.0,X-LC,17.04,1.0,-0.51,2.02,0.00,X40,NTT,FMCG
73,TCS,-0.49,-27.99,75.78,26.57,252798.0,-129679.0,333594.0,4311.59,-39.04,21.0,X-LC,14.43,2.0,-0.51,2.46,0.00,X40,ATH,IT
43,INFY,-0.42,-13.48,55.17,34.24,149346.0,-42186.0,270702.0,1972.00,-31.79,25.0,X-LC,12.73,3.0,-0.28,2.00,0.00,X40,NTT,IT
75,TMPV,-2.86,-25.85,84.19,36.58,222142.0,-91983.0,263858.0,600.00,-84.72,33.0,X-LC,1.78,4.0,-0.41,1.95,0.00,XY24,NTT,AUTO
34,HCLTECH,0.70,-11.76,40.34,23.83,86115.0,-28451.0,213473.0,1908.19,-7.36,30.0,X-LC,9.80,8.0,-0.33,1.58,2.42,X40,ATH,IT

In [22]:
# top 5 for average up
df_tmp = df_portfolio_features[(df_portfolio_features['Dev%_200'] > 5)].sort_values(by = 'CurrAlloc%', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
67,SONACOMS,-1.19,-11.74,57.59,39.09,51419.0,-11874.0,89285.0,804.02,-30.06,48.0,M-MC,9.84,193.0,-0.23,0.66,26.31,AR,ATH,AUTO
65,SIEMENS,1.92,-10.40,40.07,25.51,66817.0,-19345.0,166750.0,4671.50,40.03,58.0,H-LC,3.81,51.0,-0.29,1.23,22.80,AR,ATH,ELECTRICAL
27,FINCABLES,1.37,14.00,82.38,107.91,138653.0,20665.0,168309.0,1641.55,2.49,57.0,M-SC,7.76,220.0,0.15,1.24,26.62,OX40N,ATH,CABLES
19,COALINDIA,5.43,15.82,1.59,17.67,2771.0,23810.0,174270.0,478.51,39.17,70.0,L-LC,12.21,185.0,8.59,1.29,35.33,XY25,ATH,MINING
82,VOLTAS,-0.59,14.43,26.89,45.20,58998.0,27663.0,219405.0,1856.00,31.03,48.0,X-MC,9.40,79.0,0.47,1.62,22.21,XY25,NTT,AC

In [23]:
# top 5 RSP
df_tmp = df_portfolio_features.sort_values(by = 'RSP', ascending=False)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
19,COALINDIA,5.43,15.82,1.59,17.67,2771.0,23810.0,174270.0,478.51,39.17,70.0,L-LC,12.21,185.0,8.59,1.29,35.33,XY25,ATH,MINING
1,ABB,1.93,17.44,23.95,45.57,73586.0,45629.0,307248.0,7934.00,-24.53,69.0,H-MC,10.55,125.0,0.62,2.27,36.44,AR,NTT,ELECTRICAL
27,FINCABLES,1.37,14.00,82.38,107.91,138653.0,20665.0,168309.0,1641.55,2.49,57.0,M-SC,7.76,220.0,0.15,1.24,26.62,OX40N,ATH,CABLES
26,EASEMYTRIP,-1.22,-59.93,263.64,45.70,186770.0,-105972.0,70843.0,26.40,-26.57,42.0,M-SC,18.19,204.0,-0.57,0.52,16.72,XY24,NTT,TRAVEL
31,HAPPSTMNDS,-1.02,-49.13,263.36,84.85,171711.0,-62965.0,65200.0,1480.71,-39.56,61.0,H-SC,28.37,152.0,-0.37,0.48,20.74,AR,ATH,IT

In [24]:
# Top N allocation
df_tmp = df_portfolio_features.sort_values(by = 'CurrAlloc%', ascending=False)
top_n_values = [10, 25, 50]

sum_df = pd.DataFrame({
    'Top_N': top_n_values,
    'Sum_Alloc%': [df_tmp['CurrAlloc%'].head(n).sum() for n in top_n_values]
})

sum_df

   Top_N  Sum_Alloc%
0     10       20.35
1     25       45.18
2     50       77.75

In [25]:
# market-cap-wise allocation
df_tmp = df_portfolio_features[cols]
df_tmp.groupby(df_tmp['Conviction'].str[-2:])['CurrAlloc%'].sum().sort_values(ascending=False)

Conviction
SC    44.75
MC    30.40
LC    24.88
Name: CurrAlloc%, dtype: float64

In [26]:
# criteria-wise allocation
df_portfolio_features.groupby('Criteria')['CurrAlloc%'].sum().sort_values(ascending=False)

Criteria
XY24     27.34
X40      23.69
X40N     15.04
AR        9.26
XY25      8.69
XR        8.25
OX40N     6.99
SR        0.77
Name: CurrAlloc%, dtype: float64

In [27]:
# conviction-wise allocation
df_portfolio_features.groupby('Conviction')['CurrAlloc%'].sum().sort_values(ascending=False)

Conviction
X-MC    22.92
H-SC    21.72
X-LC    21.32
X-SC    12.09
M-SC    10.35
H-MC     5.07
M-MC     2.06
L-LC     1.29
H-LC     1.23
M-LC     1.04
L-SC     0.59
L-MC     0.35
Name: CurrAlloc%, dtype: float64

In [28]:
# sector-wise stats
df_tmp = df_portfolio_features.groupby('Category')[['CurrAlloc%', 'Current', 'Current P/L', 'FTT Amt']].sum().sort_values(by=['Current', 'Current P/L'], ascending=False)
df_tmp['Current P/L%'] = round(df_tmp['Current P/L'] * 100 / df_tmp['Current'], 2)
df_tmp['FTT%'] = round(df_tmp['FTT Amt'] * 100 / df_tmp['Current'], 2)
cols = ['CurrAlloc%', 'Current P/L%', 'FTT%']
df_tmp[cols].sort_values(by=['CurrAlloc%'], ascending=False)

               CurrAlloc%  Current P/L%    FTT%
Category
FMCG                15.08        -22.21   65.60
FINANCE             12.86        -23.38   73.67
IT                  11.71        -41.97  114.22
MISC                 7.04        -40.44  101.45
ELECTRICAL           6.74         -5.99   46.57
PAINTS               5.15        -40.88   65.34
INSURANCE            4.72         -6.02   42.30
PHARMA               4.16         -4.38   37.24
AUTO                 3.68        -31.40   83.53
BANKS                3.08        -27.88  105.37
AC                   2.17         -8.81   38.32
HEALTHCARE           1.99        -33.17   67.92
DURABLES             1.94        -47.15   82.95
FOOTWEAR             1.87        -74.27  144.14
TRAVEL               1.82        -81.15  171.86
BREWERIES            1.74          0.45   20.23
APPARELS             1.59        -24.48   66.94
REALTY               1.45        -12.96   31.51
CERAMICS             1.36        -66.74  117.39
REFINERIES           1.33        -11.16   39.29
MINING               1.29         13.66    1.59
CEMENT               1.27        -55.82  172.38
CABLES               1.24         12.28   82.38
JEWELLERY            1.12       -111.78  185.37
ENGINEERING          1.11        -60.81  134.37
CHEMICALS            0.95       -105.52  273.18
ENTERTAINMENT        0.77        -85.81  196.63
TEXTILES             0.43        -60.02  105.66
HOTELS               0.37       -128.34  208.88

In [29]:
# money to be made criteria-wise
df_portfolio_features.groupby('Criteria')['FTT Amt'].agg(['sum', 'count']).sort_values(by='sum', ascending=False)

                sum  count
Criteria
XY24      3893816.0     21
X40       1663513.0     15
XR        1375723.0     12
AR        1316575.0     10
X40N      1261025.0     10
OX40N      844167.0     10
XY25       439499.0      6
SR         314821.0      2

In [30]:
# money to be made conviction-wise
df_portfolio_features.groupby('Conviction')['FTT Amt'].agg(['sum', 'count']).sort_values(by='sum', ascending=False)

                  sum  count
Conviction
H-SC        3847809.0     24
X-MC        1628102.0     15
X-LC        1585210.0     12
X-SC        1544797.0     10
M-SC        1516104.0     14
H-MC         392498.0      3
L-SC         211733.0      2
M-LC         151126.0      1
M-MC         107387.0      2
H-LC          66817.0      1
L-MC          54785.0      1
L-LC           2771.0      1

In [31]:
# money to be made criteria and conviction-wise
df_portfolio_features.groupby(['Conviction', 'Criteria'])['FTT Amt'].agg(['sum', 'count']).sort_values(by='sum', ascending=False)

                           sum  count
Conviction Criteria
H-SC       XY24      1307588.0      6
           AR         966686.0      5
M-SC       XY24       895820.0      6
H-SC       XR         876290.0      7
X-SC       XY24       833070.0      4
X-LC       X40        823627.0      6
X-MC       X40        635355.0      7
X-SC       X40N       507196.0      4
X-MC       X40N       503450.0      4
H-SC       OX40N      382424.0      4
X-LC       XY24       364115.0      2
M-SC       OX40N      353882.0      5
H-SC       SR         314821.0      2
X-MC       XY24       255626.0      2
X-LC       X40N       250379.0      2
H-MC       XY24       237597.0      1
X-MC       XY25       233671.0      2
X-SC       X40        204531.0      2
M-SC       XR         189650.0      2
H-MC       AR         154901.0      2
M-LC       XR         151126.0      1
X-LC       XY25       147089.0      2
L-SC       OX40N      107861.0      1
           XR         103872.0      1
M-SC       AR          76752.0      1
H-LC       AR          66817.0      1
M-MC       XY25        55968.0      1
L-MC       XR          54785.0      1
M-MC       AR          51419.0      1
L-LC       XY25         2771.0      1

In [32]:
# notebook execution time

end_time = time.time()
execution_time = round(end_time - start_time, 0)
print(f"Notebook execution time: {execution_time} seconds")

Notebook execution time: 32.0 seconds