<a href="https://colab.research.google.com/github/ankit-rathi/Quantvesting_v2/blob/main/myStocks_Portfolio_Analysis.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
'''
!pip install pandas==2.2.2 -qq
!pip install pyxirr -qq
!pip install ta -qq
!pip install yfinance==0.2.59 -qq
'''

'\n!pip install pandas==2.2.2 -qq\n!pip install pyxirr -qq\n!pip install ta -qq\n!pip install yfinance==0.2.59 -qq\n'

In [2]:
# import libraries

import numpy as np
import pandas as pd
import datetime
import warnings
warnings.filterwarnings('ignore')
import yfinance as yfin
import ta
import matplotlib.pyplot as plt
import requests

In [3]:
# notebook start time
import time
import datetime
import pytz

start_time = time.time()

# function to print date timestamp
def print_date_time():
  tz_NY = pytz.timezone('Asia/Kolkata')
  datetime_NY = datetime.datetime.now(tz_NY)
  print("Run date time (IST):", datetime_NY.strftime("%Y-%m-%d %H:%M:%S"))

In [4]:
# function to get booked and reserved amount
def get_amt():
  # fetch the JSON data from the URL
  url = "https://raw.githubusercontent.com/ankit-rathi/Tradevesting_v1/main/data/myPortfolioAmts.json"
  response = requests.get(url)
  pf_amts = response.json()  # parse the JSON data

  # extract values from the JSON
  py_booked_amt_dm = pf_amts["py_booked_amt_dm"]
  py_booked_amt_sv = pf_amts["py_booked_amt_sv"]
  cy_booked_amt_dm = pf_amts["cy_booked_amt_dm"]
  cy_booked_amt_sv = pf_amts["cy_booked_amt_sv"]
  reserve_amt_dm = pf_amts["reserve_amt_dm"]
  reserve_amt_sv = pf_amts["reserve_amt_sv"]

  # perform calculations
  py_booked_amt = py_booked_amt_dm + py_booked_amt_sv
  cy_booked_amt = cy_booked_amt_dm + cy_booked_amt_sv
  reserve_amt = reserve_amt_dm + reserve_amt_sv
  total_booked_amt = py_booked_amt + cy_booked_amt

  return total_booked_amt, reserve_amt, cy_booked_amt, py_booked_amt

gen_output = 0

In [5]:
# function to format the amount
def format_amt(number):
    abs_number = abs(number)

    if abs_number >= 1_00_00_000:  # Crores
        formatted_amt = f"{number / 1_00_00_000:.2f} C"
    elif abs_number >= 1_00_000:  # Lakhs
        formatted_amt = f"{number / 1_00_000:.2f} L"
    elif abs_number >= 1_000:  # Thousands
        formatted_amt = f"{number / 1_000:.2f} K"
    else:
        formatted_amt = f"{number:.2f}"

    return formatted_amt

# function to set start and end date
def get_start_end_date():
  start_date = (datetime.date.today() + datetime.timedelta(days=-365)).strftime('%Y-%m-%d')
  end_date = (datetime.date.today() + datetime.timedelta(days=1)).strftime('%Y-%m-%d')
  return start_date, end_date

# function to fetch my portfolio csv
def get_mypfs_df():
  mypfs_df = pd.read_csv('https://raw.githubusercontent.com/ankit-rathi/Tradevesting_v1/main/data/myPortfolioStocks.csv')
  return mypfs_df

# function to fetch my prospects csv
def get_mypps_df():
  mypps_df = pd.read_csv('https://raw.githubusercontent.com/ankit-rathi/Tradevesting_v1/main/data/myProspectsScrips.csv')
  return mypps_df

# function to fetch screener data
def get_myscreen_df():
  myscreen_df = pd.read_csv('https://raw.githubusercontent.com/ankit-rathi/Tradevesting_v1/main/data/myScreenerDB.csv')
  return myscreen_df

# function to fetch momentum data
def get_myinvmt_df():
  myinvmt_df = pd.read_csv('https://raw.githubusercontent.com/ankit-rathi/Tradevesting_v1/main/data/myInvestments.csv')
  return myinvmt_df

# function to get the stock ids
def get_stock_ids(df_pf):
  stock_n100 = df_pf['Symbol'].unique()

  exclude = ['CADILAHC','MMTC', 'MASFIN']

  stock_ids = df_pf[~df_pf['Symbol'].isin(exclude) ]['Symbol'].unique()

  #mypf = mypf[mypf.Forecast.notnull()]
  #stock_ids = mypf['Symbol'].unique()

  #stock_ids.sort()
  return stock_ids

# get features from screener data
def get_screener_features():
  myscreen_df = get_myscreen_df()
  cols = ['Symbol', 'EPS', 'MedPE', 'ROCE%', 'ROE%', 'CapType']
  return myscreen_df[cols]

# get relative strength
def get_relative_strength(stock_list):

    # Dictionary to store stock tickers and their corresponding percentage price change
    stock_changes = {}

    # Loop through each stock and fetch its price data
    for stock in stock_list:
        try:
            # Download the stock data for the given date range
            stock_data = yfin.Ticker(stock + '.NS').history(period='1mo', interval='1d')[map(str.title, ['open', 'close', 'low', 'high', 'volume'])]

            # Calculate the percentage change for the stock
            if len(stock_data) > 0:
                start_price = stock_data['Close'].iloc[0]
                end_price = stock_data['Close'].iloc[-1]
                percent_change = round(((end_price - start_price) / start_price) * 100, 2)
                stock_changes[stock] = percent_change
            else:
                stock_changes[stock] = np.nan  # If no data is available, set to NaN

        except Exception as e:
            print(f"Error fetching data for {stock}: {e}")
            stock_changes[stock] = np.nan

    # Create a DataFrame with stock tickers and their percentage changes
    df = pd.DataFrame(list(stock_changes.items()), columns=['Symbol', 'Percent_Change'])

    # Drop any stocks with missing data (NaN values)
    df = df.dropna()

    # Calculate the percentile rank based on percentage change
    df['RSP'] = round(df['Percent_Change'].rank(pct=True) * 100, 2)
    cols = ['Symbol', 'RSP']
    df = df[cols]
    # Sort by percentile rank (optional)
    df = df.sort_values(by='RSP', ascending=False).reset_index(drop=True)

    return df

In [6]:
# function to get stock technicals
def stock_prec_dev(stock_symbol):
    #stock_symbol = 'ULTRACEMCO.NS'
    short_window = 20
    mid_window = 50
    long_window = 200
    moving_avg = 'SMA'

    start = datetime.datetime(*map(int, start_date.split('-')))
    end = datetime.datetime(*map(int, end_date.split('-')))

    stock_df = yfin.Ticker(stock_symbol + '.NS').history(period='max', interval='1d')[map(str.title, ['open', 'close', 'low', 'high', 'volume'])]

    stock_df['Max'] = round(max(stock_df['Close']),2)
    stock_df = stock_df[(stock_df.index <= end_date) & (stock_df.index >= start_date)]
    stock_df['200_SMA'] = round(stock_df['Close'].rolling(window = 200, min_periods = 1).mean(),0)
    stock_df['Dev%_200'] = round((stock_df['Close'] - stock_df['200_SMA'])*100/stock_df['200_SMA'],2)
    stock_df.dropna(axis = 0, inplace = True) # remove any null rows

    stock_df['20_SMA'] = stock_df['Close'].rolling(window=20).mean()
    stock_df['50_SMA'] = stock_df['Close'].rolling(window=50).mean()
    stock_df['Symbol'] = stock_symbol

    stock_df['Close'] = round(stock_df['Close'],2)
    stock_df['Min'] = round(min(stock_df['Close']),2)
    stock_df['RSI_14'] = ta.momentum.RSIIndicator(close=stock_df['Close'], window=14).rsi()
    stock_df['RSI_14'] = round(stock_df['RSI_14'],0)
    stock_df['Prev_Close'] = stock_df['Close'].shift(1)
    stock_df.drop(['Open', 'Low', 'High', 'Volume'], axis=1, inplace=True)
    stock_df = stock_df.tail(1)

    max_SMA = max(stock_df['20_SMA'].item(), stock_df['50_SMA'].item(), stock_df['200_SMA'].item())
    min_SMA = min(stock_df['20_SMA'].item(), stock_df['50_SMA'].item(), stock_df['200_SMA'].item())
    ABS_Spread = max_SMA - min_SMA
    stock_df['Spread%'] = round((ABS_Spread / stock_df['200_SMA'].item()) * 100,2)

    return stock_df

# function to compute stock attributes
def get_common_features(stock_ids, df_mypf):

  df_prec_dev = pd.DataFrame()
  df_tmp = get_screener_features()
  df_rs = get_relative_strength(stock_ids)

  for stock_id in stock_ids:
      tmp = stock_prec_dev(stock_id)
      tmp = tmp.reset_index()
      df_prec_dev = pd.concat([df_prec_dev, tmp], ignore_index = True)
  df_prec_dev = pd.merge(df_prec_dev, df_mypf, on= 'Symbol')
  df_prec_dev = pd.merge(df_prec_dev, df_tmp, on= 'Symbol', how='left')
  df_prec_dev = pd.merge(df_prec_dev, df_rs, on= 'Symbol', how='left')
  #print(df_prec_dev.columns)
  df_prec_dev['Curr_PE'] = round(df_prec_dev['Close']/df_prec_dev['EPS'],1)
  df_prec_dev['Dev%_PE'] = round((df_prec_dev['Curr_PE'] - df_prec_dev['MedPE'])*100/df_prec_dev['MedPE'],2)
  df_prec_dev['Conviction'] = df_prec_dev['Conviction'] + '-' + df_prec_dev['CapType']
  return df_prec_dev

# function to arrange stock features
def arrange_features(df_stocks, common_cols, diff_cols):
  df_stocks_common = df_stocks[common_cols].drop_duplicates()
  df_stocks_diff = df_stocks[diff_cols]
  df_stocks_diff['Investment'] = df_stocks_diff['AvgCost'] * df_stocks_diff['Shares']
  df_stocks_diff = df_stocks_diff.groupby(['Symbol'])[['Shares', 'Investment']].aggregate(['sum']).reset_index()
  df_stocks_diff.columns = ['Symbol', 'Shares', 'Investment']
  df_stocks_diff['AvgCost'] = round(df_stocks_diff['Investment']/df_stocks_diff['Shares'],2)
  df_stocks = pd.merge(df_stocks_diff, df_stocks_common, on='Symbol')
  return df_stocks

# plot fact distribution across dimension
def plot_pie_chart(df, dimension, fact):
  # grouping the data by category and calculating the sum of fact for each type
  grouped_data = df.groupby(dimension)[fact].sum()

  # sorting the grouped data in descending order
  grouped_data = grouped_data.sort_values(ascending=False)

  # creating a pie chart
  grouped_data.plot.pie(autopct='%1.1f%%', startangle=90, figsize=(6, 6))

  # adding a title and displaying the plot
  plt.title(f'{dimension} {fact} Distribution')
  plt.ylabel('')  # To hide the y-label
  plt.show()

In [7]:
# function to get portfolio features

def get_portfolio_features(df_common_features):

  print_date_time()
  print('-------------------')

  #df_common_features["Target"] = df_common_features["Target"].fillna(df_common_features["Max"])
  df_common_features['NTT'] = np.where(df_common_features['Strategy']== 'NTT', df_common_features["Target"], df_common_features['Max'])
  df_common_features['LTT'] = np.where(df_common_features['Strategy']== 'BTT', df_common_features["Target"], df_common_features['Max'])
  df_common_features['BOL'] = df_common_features['Min']

  tmp_df = df_common_features[df_common_features['Symbol'].isin(mypf_df[mypf_df['InPortfolio'] != 'NA'].Symbol.values)]
  print('qualified stocks: '+str(len(tmp_df['Symbol'].unique())))
  tmp_df1 = tmp_df[tmp_df['LatestQtr'] == 1]
  print('with latest results: '+str(len(tmp_df1['Symbol'].unique())))
  tmp_df1 = tmp_df1[tmp_df1['StarStock'] == 1]
  print('still star stocks: '+str(len(tmp_df1['Symbol'].unique())))
  tmp_df['Investment'] = tmp_df['AvgCost'] * tmp_df['Shares']
  tmp_df['Current'] = round(tmp_df['Close'] * tmp_df['Shares'],0)
  tmp_df['Previous'] = tmp_df['Prev_Close'] * tmp_df['Shares']
  tmp_df['EstimatedST'] = tmp_df['NTT'] * tmp_df['Shares']
  tmp_df['EstimatedLT'] = tmp_df['LTT'] * tmp_df['Shares']
  tmp_df['Current P/L'] = round((tmp_df['Current'] - tmp_df['Investment']),0)
  tmp_df['Today P/L%'] = round((tmp_df['Current'] - tmp_df['Previous'])*100/tmp_df['Previous'],2)
  tmp_df['Current P/L%'] = round((tmp_df['Current'] - tmp_df['Investment'])*100/tmp_df['Investment'],2)
  tmp_df['EstimatedST P/L%'] = round((tmp_df['EstimatedST'] - tmp_df['Investment'])*100/tmp_df['Investment'],2)
  tmp_df['EstimatedLT P/L%'] = round((tmp_df['EstimatedLT'] - tmp_df['Investment'])*100/tmp_df['Investment'],2)
  tmp_df['NTT%'] = round((tmp_df['NTT'] - tmp_df['Close'])*100/tmp_df['Close'],2)
  tmp_df['LTT%'] = round((tmp_df['LTT'] - tmp_df['Close'])*100/tmp_df['Close'],2)
  tmp_df['Gained%'] = round((tmp_df['Close'] - tmp_df['BOL'])*100/tmp_df['BOL'],2)
  investment = round(sum(tmp_df['AvgCost']*tmp_df['Shares']),0)
  current = round(sum(tmp_df['Close']*tmp_df['Shares']),0)
  tmp_df['InitAlloc%'] = round(tmp_df['Investment']*100/investment,2)
  tmp_df['CurrAlloc%'] = round(tmp_df['Current']*100/current,2)
  tmp_df['FTT'] = tmp_df['LTT']
  tmp_df.loc[tmp_df['Strategy'] == 'NTT', 'FTT'] = tmp_df['NTT']
  tmp_df['FTT%'] = tmp_df['LTT%']
  tmp_df.loc[tmp_df['Strategy'] == 'NTT', 'FTT%'] = tmp_df['NTT%']
  tmp_df['FTT Amt'] = round(tmp_df['FTT%'] * tmp_df['Current']/100,0)
  tmp_df['OTT%'] = round((tmp_df['FTT'] - tmp_df['AvgCost'])*100/tmp_df['AvgCost'],2)
  tmp_df['RRR Ind'] = round(tmp_df['Current P/L']/tmp_df['FTT Amt'],2)
  tmp_df['Risk Ind'] = round(tmp_df['Current P/L%']*tmp_df['CurrAlloc%'],0)

  return tmp_df

# function to print portfolio features
def print_portfolio_stats(df_portfolio_features, myinvmt_df):
  from pyxirr import xirr

  total_booked_amt, reserve_amt, cy_booked_amt, py_booked_amt = get_amt()

  dates = myinvmt_df['Date'].values
  dates = np.append(dates, datetime.date.today().strftime('%d-%b-%y'))
  investment = myinvmt_df['Investment'].values
  dates= pd.to_datetime(dates)

  current = round(sum(df_portfolio_features['Close']*df_portfolio_features['Shares']),0) + reserve_amt
  investment_xirr = np.append(investment, current)
  cagr = round(xirr(pd.DataFrame({"dates": dates, "amounts": investment_xirr}))*100,2)

  investment = -sum(investment)
  invested = round(sum(df_portfolio_features['AvgCost']*df_portfolio_features['Shares']),0) + reserve_amt
  previous = round(sum(df_portfolio_features['Prev_Close']*df_portfolio_features['Shares']),0) + reserve_amt
  cy_invested = investment + py_booked_amt

  today_pnl_amount = current-previous
  today_pnl_percentage = round((current-previous)*100/previous,2)

  curr_pnl_amount = current-invested
  curr_pnl_percentage = round((curr_pnl_amount)*100/(cy_invested),2)

  cy_pnl_amount = cy_booked_amt + curr_pnl_amount
  cy_pnl_percentage = round((cy_pnl_amount)*100/cy_invested,2)

  overall_pnl_amount = total_booked_amt + curr_pnl_amount
  overall_pnl_percentage = round((overall_pnl_amount)*100/investment,2)

  estimate_st = round(sum(df_portfolio_features['FTT']*df_portfolio_features['Shares']),0)  + reserve_amt
  est_st_pnl_amount = estimate_st-current
  est_st_pnl_percentage = round((est_st_pnl_amount)*100/current,2)

  estimate_lt = round(sum(df_portfolio_features['LTT']*df_portfolio_features['Shares']),0)  + reserve_amt
  est_lt_pnl_amount = estimate_lt-current
  est_lt_pnl_percentage = round((est_lt_pnl_amount)*100/current,2)

  total_profit = round(sum(df_portfolio_features[df_portfolio_features['Current P/L%'] > 0]['Current']) - sum(df_portfolio_features[df_portfolio_features['Current P/L%'] > 0]['Investment']),0)
  total_loss = round(sum(df_portfolio_features[df_portfolio_features['Current P/L%'] < 0]['Current']) - sum(df_portfolio_features[df_portfolio_features['Current P/L%'] < 0]['Investment']),0)

  cy_booked_percentage = round((cy_booked_amt)*100/current,2)
  py_booked_percentage = round((py_booked_amt)*100/investment,2)
  total_booked_percentage = round((total_booked_amt)*100/investment,2)

  print('-------------------')
  print('Initial Investment: ', format_amt(investment))
  print('CY Investment: ', format_amt(cy_invested))
  print('Reserve: ', format_amt(reserve_amt))
  print('Current: ',  format_amt(current))
  print('-------------------')
  print('Today PnL: '+ '{} ({}%)'.format(format_amt(today_pnl_amount), today_pnl_percentage))
  print('Current PnL: '+ '{} ({}%)'.format(format_amt(curr_pnl_amount), curr_pnl_percentage))
  print('CY Booked + Current PnL: '+ '{} ({}%)'.format(format_amt(cy_pnl_amount), cy_pnl_percentage))
  print('-------------------')
  print('Total profit: ', format_amt(total_profit))
  print('Total loss: ', format_amt(total_loss))
  print('-------------------')
  print('Total Booked + Current PnL: '+ '{} ({}%)'.format(format_amt(overall_pnl_amount), overall_pnl_percentage))
  print('Total Booked PnL: '+ '{} ({}%)'.format(format_amt(total_booked_amt), total_booked_percentage))
  print('Curr Year Booked PnL: '+ '{} ({}%)'.format(format_amt(cy_booked_amt), cy_booked_percentage))
  print('Prev Year Booked PnL: '+ '{} ({}%)'.format(format_amt(py_booked_amt), py_booked_percentage))
  print('===================')
  print('Est FTT: ',  format_amt(estimate_st))
  print('Est FTT PnL: '+ '{} ({}%)'.format(format_amt(est_st_pnl_amount), est_st_pnl_percentage))

  print('===================')
  print('Deployed: ', format_amt(investment))

  print('Current: ', format_amt(current))

  print('CAGR/XIRR %: '+'{}%'.format(cagr))

In [8]:
# get start and end date
start_date, end_date = get_start_end_date()

# get portfolio and prospects data
mypfs_df = get_mypfs_df()
mypps_df = get_mypps_df()
myinvmt_df = get_myinvmt_df()

# merge above datasets
mypf_df = pd.merge(mypfs_df, mypps_df, on="Symbol")

# seggregate dm and sv portfolio
dm_pf = mypf_df[mypf_df['InPortfolio'] == 'DM']
sv_pf = mypf_df[mypf_df['InPortfolio'] == 'SV']

# build portfolio stock dataframe
dm_stocks = get_stock_ids(dm_pf)
sv_stocks = get_stock_ids(sv_pf)
df_stocks = pd.concat([dm_pf,sv_pf], ignore_index = True)

# arrange common and diff stock features
common_cols = ['Symbol', 'Target', 'Criteria', 'Strategy', 'CumlRnk', 'LatestQtr', 'StarStock', 'Conviction', 'Category', 'InFolio', 'XIRR', 'MBQ']
diff_cols = ['Symbol', 'AvgCost', 'Shares']
df_stocks = arrange_features(df_stocks, common_cols, diff_cols)

# get common features
stock_ids = df_stocks['Symbol'].values
df_common_features = get_common_features(stock_ids, df_stocks)

df_common_features.reset_index(drop=True, inplace=True)
df_common_features.drop(['Date'], axis=1, inplace=True)
# get and print portfolio features
df_portfolio_features = get_portfolio_features(df_common_features)

print_portfolio_stats(df_portfolio_features, myinvmt_df)

df = df_portfolio_features
#plot_pie_chart(df, 'CapType', 'Current')
list_ox40n = list(df[df['MBQ'].str.contains('OX40N', na=False)]['Symbol'].values)

Run date time (IST): 2026-07-02 14:53:26
-------------------
qualified stocks: 92
with latest results: 31
still star stocks: 20

-------------------
Initial Investment:  1.40 C
CY Investment:  1.82 C
Reserve:  1.49 K
Current:  1.53 C
-------------------
Today PnL: 1.33 L (0.87%)
Current PnL: -29.87 L (-16.38%)
CY Booked + Current PnL: -27.79 L (-15.24%)
-------------------
Total profit:  4.86 L
Total loss:  -34.73 L
-------------------
Total Booked + Current PnL: 15.08 L (10.81%)
Total Booked PnL: 44.95 L (32.22%)
Curr Year Booked PnL: 2.08 L (1.36%)
Prev Year Booked PnL: 42.87 L (30.73%)
===================
Est FTT:  2.55 C
Est FTT PnL: 1.02 C (66.33%)
===================
Deployed:  1.40 C
Current:  1.53 C
CAGR/XIRR %: 4.35%

In [9]:
# top 5 near their targets
cols = ['Symbol', 'Today P/L%', 'Current P/L%', 'FTT%', 'OTT%', 'FTT Amt', 'Current P/L', 'Current', 'FTT', 'Dev%_PE', 'RSI_14','Conviction', 'Spread%',  'CumlRnk', 'RRR Ind', 'CurrAlloc%', 'Gained%', 'Criteria', 'Strategy', 'Category']
df_tmp = df_portfolio_features[~df_portfolio_features['Symbol'].isin(['ENRIN','BLUSPRING','DIGITIDE'])]
df_tmp = df_tmp.sort_values(by = 'FTT Amt', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
59,PIDILITIND,1.36,13.63,4.17,18.37,6686.0,19230.0,160340.0,1670.26,-20.38,70.0,X-LC,6.46,5.0,2.88,1.05,25.90,X40,ATH,CHEMICALS
49,JSWINFRA,-1.07,11.29,4.62,16.43,11403.0,25035.0,246809.0,342.00,-4.60,66.0,X-MC,9.16,61.0,2.20,1.61,39.93,X40N,NTT,REALTY
83,TTKPRESTIG,2.15,-16.29,19.57,0.09,16510.0,-16413.0,84364.0,770.00,95.73,80.0,M-SC,6.39,250.0,-0.99,0.55,50.22,OX40N,NTT,DURABLES
51,KOTAKBANK,-0.35,6.63,13.58,21.11,20051.0,9176.0,147648.0,453.24,-8.54,53.0,X-LC,4.44,12.0,0.46,0.96,12.92,X40,ATH,BANKS
56,MEDANTA,1.37,15.16,10.38,27.12,21100.0,26759.0,203276.0,1486.00,11.60,73.0,X-SC,6.37,87.0,1.27,1.33,40.07,XY24,NTT,HEALTHCARE

In [10]:
# top 5 today
df_tmp = df_portfolio_features.sort_values(by = 'Today P/L%', ascending=False)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
0,5PAISA,7.32,-25.74,52.03,12.90,84424.0,-56235.0,162261.0,593.00,139.18,81.0,H-SC,1.23,170.0,-0.67,1.06,56.58,OX40N,NTT,FINANCE
73,SONACOMS,6.68,14.31,21.33,38.69,24664.0,14472.0,115631.0,801.69,-9.40,76.0,M-MC,18.13,193.0,0.59,0.75,64.05,AR,ATH,AUTO
45,INFY,5.65,-29.13,89.43,34.24,198296.0,-91155.0,221733.0,1972.00,-44.12,42.0,X-LC,20.05,3.0,-0.46,1.45,5.65,X40,NTT,IT
43,INDIGOPNTS,5.40,-23.42,30.60,0.02,40907.0,-40875.0,133684.0,1408.00,103.68,69.0,M-SC,5.78,222.0,-1.00,0.87,51.67,OX40N,NTT,PAINTS
61,RAJESHEXPO,4.99,-82.29,465.01,0.07,112974.0,-112882.0,24295.0,518.00,790.15,44.0,L-SC,38.82,268.0,-1.00,0.16,19.98,OX40N,NTT,JEWELLERY

In [11]:
# bottom 5 today
df_tmp = df_portfolio_features.sort_values(by = 'Today P/L%', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
23,DMART,-2.97,0.96,28.37,29.60,71492.0,2400.0,252000.0,5391.45,-14.87,46.0,X-LC,3.88,14.0,0.03,1.64,15.19,X40N,ATH,FMCG
27,GLAXO,-1.94,-2.98,39.86,35.69,77067.0,-5940.0,193344.0,3380.16,-25.91,64.0,X-MC,6.47,56.0,-0.08,1.26,14.91,X40,ATH,PHARMA
57,PAGEIND,-1.65,11.87,19.42,33.59,58305.0,31851.0,300230.0,51217.29,-19.73,69.0,X-MC,7.73,55.0,0.55,1.96,42.58,X40,ATH,APPARELS
25,FINCABLES,-1.51,42.77,45.63,107.91,96182.0,63142.0,210786.0,1641.55,28.36,54.0,M-SC,26.20,220.0,0.66,1.38,58.58,OX40N,ATH,CABLES
91,ZYDUSLIFE,-1.13,15.65,17.28,35.63,41882.0,32797.0,242371.0,1286.17,0.45,56.0,H-MC,14.20,120.0,0.78,1.58,27.43,AR,ATH,PHARMA

In [12]:
# top 5 to exit based on CumlRnk
df_tmp = df_portfolio_features[~df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])]
df_tmp = df_tmp[(df_tmp['Current P/L%'] > -1) & (df_tmp['Current P/L%'] < 1)].sort_values(by = 'CumlRnk', ascending=False)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
63,RECLTD,-0.27,-0.08,20.83,20.74,42286.0,-165.0,203005.0,446.0,9.37,62.0,M-MC,1.76,191.0,-0.0,1.32,20.98,XY25,NTT,FINANCE

In [13]:
# OX40N stocks to exit
df_tmp = df_portfolio_features[(df_portfolio_features['Symbol'].isin(list_ox40n))].sort_values(by = 'Current P/L%', ascending=False)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
25,FINCABLES,-1.51,42.77,45.63,107.91,96182.0,63142.0,210786.0,1641.55,28.36,54.0,M-SC,26.20,220.0,0.66,1.38,58.58,OX40N,ATH,CABLES
72,SIS,1.19,-2.32,24.15,21.26,26191.0,-2580.0,108452.0,528.00,2587.56,54.0,H-SC,25.17,168.0,-0.10,0.71,61.25,OX40N,NTT,MISC
16,CERA,0.76,-15.14,45.99,23.89,68649.0,-26633.0,149270.0,9475.00,-18.14,66.0,H-SC,11.63,153.0,-0.39,0.97,43.45,OX40N,NTT,CERAMICS
83,TTKPRESTIG,2.15,-16.29,19.57,0.09,16510.0,-16413.0,84364.0,770.00,95.73,80.0,M-SC,6.39,250.0,-0.99,0.55,50.22,OX40N,NTT,DURABLES
43,INDIGOPNTS,5.40,-23.42,30.60,0.02,40907.0,-40875.0,133684.0,1408.00,103.68,69.0,M-SC,5.78,222.0,-1.00,0.87,51.67,OX40N,NTT,PAINTS

In [14]:
# top 5 to book for rotation
df_tmp = df_portfolio_features[(df_portfolio_features['Current P/L%'] > 20) ].sort_values(by = 'CumlRnk', ascending=False)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
25,FINCABLES,-1.51,42.77,45.63,107.91,96182.0,63142.0,210786.0,1641.55,28.36,54.0,M-SC,26.20,220.0,0.66,1.38,58.58,OX40N,ATH,CABLES
68,SATIN,3.31,44.06,5.40,51.83,21493.0,121730.0,398014.0,274.00,28.78,69.0,H-SC,41.94,159.0,5.66,2.60,93.89,XY24,NTT,FINANCE

In [15]:
# top 5 to monitor for exit
df_tmp = df_portfolio_features[~df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])]
df_tmp = df_tmp[(df_tmp['Current P/L%'] > 0) ].sort_values(by = 'Dev%_PE', ascending=False)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
75,SURYODAY,3.37,5.10,17.06,23.03,32109.0,9139.0,188210.0,216.00,106.14,70.0,H-SC,20.23,166.0,0.28,1.23,58.47,XR,NTT,BANKS
74,STARHEALTH,0.01,13.56,29.68,47.26,94752.0,38123.0,319246.0,761.00,79.18,73.0,H-SC,14.45,173.0,0.40,2.08,40.09,XY24,NTT,INSURANCE
68,SATIN,3.31,44.06,5.40,51.83,21493.0,121730.0,398014.0,274.00,28.78,69.0,H-SC,41.94,159.0,5.66,2.60,93.89,XY24,NTT,FINANCE
25,FINCABLES,-1.51,42.77,45.63,107.91,96182.0,63142.0,210786.0,1641.55,28.36,54.0,M-SC,26.20,220.0,0.66,1.38,58.58,OX40N,ATH,CABLES
91,ZYDUSLIFE,-1.13,15.65,17.28,35.63,41882.0,32797.0,242371.0,1286.17,0.45,56.0,H-MC,14.20,120.0,0.78,1.58,27.43,AR,ATH,PHARMA

In [16]:
# top 5 to book for rotation from weak conviction
df_tmp = df_portfolio_features[~df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])]
df_tmp = df_tmp[~df_tmp['Criteria'].isin(['XY25','XY24','X40', 'X40N'])].sort_values(by = 'RRR Ind', ascending=False)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
91,ZYDUSLIFE,-1.13,15.65,17.28,35.63,41882.0,32797.0,242371.0,1286.17,0.45,56.0,H-MC,14.20,120.0,0.78,1.58,27.43,AR,ATH,PHARMA
25,FINCABLES,-1.51,42.77,45.63,107.91,96182.0,63142.0,210786.0,1641.55,28.36,54.0,M-SC,26.20,220.0,0.66,1.38,58.58,OX40N,ATH,CABLES
73,SONACOMS,6.68,14.31,21.33,38.69,24664.0,14472.0,115631.0,801.69,-9.40,76.0,M-MC,18.13,193.0,0.59,0.75,64.05,AR,ATH,AUTO
75,SURYODAY,3.37,5.10,17.06,23.03,32109.0,9139.0,188210.0,216.00,106.14,70.0,H-SC,20.23,166.0,0.28,1.23,58.47,XR,NTT,BANKS
72,SIS,1.19,-2.32,24.15,21.26,26191.0,-2580.0,108452.0,528.00,2587.56,54.0,H-SC,25.17,168.0,-0.10,0.71,61.25,OX40N,NTT,MISC

In [17]:
# top 5 to accumulate based on lowest RSI_14
df_tmp = df_portfolio_features[df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])].sort_values(by = 'RSI_14', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
33,HCLTECH,4.28,-30.01,73.61,21.51,124639.0,-72600.0,169324.0,1872.35,-26.39,39.0,X-LC,20.34,8.0,-0.58,1.10,4.28,X40,ATH,IT
58,PGHH,-0.67,-33.32,97.98,32.01,139500.0,-71144.0,142376.0,17616.87,-54.91,40.0,X-MC,20.99,57.0,-0.51,0.93,0.97,X40,ATH,FMCG
81,TMPV,-0.42,-21.16,73.24,36.58,205470.0,-75297.0,280544.0,600.00,-83.62,40.0,X-LC,7.97,4.0,-0.37,1.83,17.90,XY24,NTT,AUTO
26,GILLETTE,-0.40,-9.98,44.10,29.72,100799.0,-25326.0,228570.0,10978.86,-30.84,42.0,X-SC,6.34,83.0,-0.25,1.49,5.04,X40,ATH,FMCG
45,INFY,5.65,-29.13,89.43,34.24,198296.0,-91155.0,221733.0,1972.00,-44.12,42.0,X-LC,20.05,3.0,-0.46,1.45,5.65,X40,NTT,IT

In [18]:
# top 5 to accumulate based on Spread and CumlRnk
df_tmp = df_portfolio_features[df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])]
df_tmp = df_tmp[(df_tmp['CumlRnk'] < 100)].sort_values(by = 'Spread%', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
17,CIPLA,-0.19,17.72,13.35,33.43,24070.0,27135.0,180296.0,1648.14,-9.03,66.0,X-LC,2.18,18.0,1.13,1.18,23.08,X40N,ATH,PHARMA
11,BERGEPAINT,0.32,-4.72,31.53,25.32,77430.0,-12174.0,245575.0,680.00,-9.89,50.0,X-MC,2.89,68.0,-0.16,1.60,27.81,XY24,NTT,PAINTS
84,UNITDSPR,1.72,1.05,19.51,20.77,46161.0,2459.0,236603.0,1644.00,-10.32,62.0,X-MC,3.14,64.0,0.05,1.54,12.87,X40N,NTT,BREWERIES
19,COLPAL,-0.77,-21.93,79.15,39.86,162732.0,-57765.0,205600.0,3683.41,-5.63,54.0,X-MC,3.56,62.0,-0.35,1.34,16.30,XY25,ATH,FMCG
23,DMART,-2.97,0.96,28.37,29.60,71492.0,2400.0,252000.0,5391.45,-14.87,46.0,X-LC,3.88,14.0,0.03,1.64,15.19,X40N,ATH,FMCG

In [19]:
# top 5 to accumulate based on lowest Gained%
df_tmp = df_portfolio_features[df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])].sort_values(by = 'Gained%', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
58,PGHH,-0.67,-33.32,97.98,32.01,139500.0,-71144.0,142376.0,17616.87,-54.91,40.0,X-MC,20.99,57.0,-0.51,0.93,0.97,X40,ATH,FMCG
1,ABBOTINDIA,0.80,-13.60,36.65,18.07,56635.0,-24325.0,154530.0,35195.00,-26.49,45.0,X-MC,6.60,58.0,-0.43,1.01,2.28,X40,ATH,PHARMA
65,RELIANCE,-0.33,-16.31,49.73,25.30,83634.0,-32786.0,168177.0,1952.00,-18.49,46.0,X-LC,7.87,21.0,-0.39,1.10,3.57,XY25,BTT,REFINERIES
33,HCLTECH,4.28,-30.01,73.61,21.51,124639.0,-72600.0,169324.0,1872.35,-26.39,39.0,X-LC,20.34,8.0,-0.58,1.10,4.28,X40,ATH,IT
79,TCS,4.63,-39.10,105.07,24.88,296421.0,-181155.0,282118.0,4253.91,-48.54,42.0,X-LC,21.55,2.0,-0.61,1.84,4.63,X40,ATH,IT

In [20]:
# top 5 to accumulate based on lowest CurrAlloc%
df_tmp = df_portfolio_features[df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])].sort_values(by = 'CurrAlloc%', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
10,BATAINDIA,2.23,-55.02,200.59,35.20,116093.0,-70794.0,57876.0,2096.00,-24.19,50.0,X-SC,20.51,91.0,-0.61,0.38,14.78,X40,NTT,FOOTWEAR
64,RELAXO,-0.96,-47.41,189.62,52.31,144750.0,-68823.0,76337.0,1176.00,-44.05,69.0,X-SC,11.04,92.0,-0.48,0.50,70.68,X40N,NTT,FOOTWEAR
60,QUESS,2.07,14.45,51.94,73.90,63483.0,15431.0,122224.0,424.00,-38.29,83.0,X-SC,17.80,80.0,0.24,0.80,66.62,XY24,NTT,MISC
35,HDFCLIFE,0.48,-6.33,41.68,32.71,58482.0,-9488.0,140312.0,811.41,-26.88,43.0,X-LC,16.11,31.0,-0.16,0.92,5.41,X40,ATH,INSURANCE
28,GODREJCP,3.10,-3.71,36.53,31.47,52277.0,-5506.0,143108.0,1469.04,1.21,64.0,X-LC,8.17,32.0,-0.11,0.93,9.80,X40N,ATH,FMCG

In [21]:
# top 5 to accumulate based on CumlRnk
df_tmp = df_portfolio_features.sort_values(by = 'CumlRnk', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
47,ITC,-0.10,-23.61,55.86,19.06,145147.0,-80326.0,259840.0,452.00,-57.95,51.0,X-LC,13.59,1.0,-0.55,1.70,4.69,X40,NTT,FMCG
79,TCS,4.63,-39.10,105.07,24.88,296421.0,-181155.0,282118.0,4253.91,-48.54,42.0,X-LC,21.55,2.0,-0.61,1.84,4.63,X40,ATH,IT
45,INFY,5.65,-29.13,89.43,34.24,198296.0,-91155.0,221733.0,1972.00,-44.12,42.0,X-LC,20.05,3.0,-0.46,1.45,5.65,X40,NTT,IT
81,TMPV,-0.42,-21.16,73.24,36.58,205470.0,-75297.0,280544.0,600.00,-83.62,40.0,X-LC,7.97,4.0,-0.37,1.83,17.90,XY24,NTT,AUTO
59,PIDILITIND,1.36,13.63,4.17,18.37,6686.0,19230.0,160340.0,1670.26,-20.38,70.0,X-LC,6.46,5.0,2.88,1.05,25.90,X40,ATH,CHEMICALS

In [22]:
# top 5 for average up
df_tmp = df_portfolio_features[(df_portfolio_features['Dev%_200'] > 5)].sort_values(by = 'CurrAlloc%', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
44,INDUSINDBK,0.05,-30.45,91.06,32.89,48899.0,-23506.0,53700.0,1800.00,-352.80,58.0,L-MC,7.16,258.0,-0.48,0.35,32.39,XR,NTT,BANKS
64,RELAXO,-0.96,-47.41,189.62,52.31,144750.0,-68823.0,76337.0,1176.00,-44.05,69.0,X-SC,11.04,92.0,-0.48,0.50,70.68,X40N,NTT,FOOTWEAR
3,ALKYLAMINE,4.11,-21.70,145.90,92.54,115343.0,-21907.0,79056.0,4520.85,-16.07,58.0,H-SC,8.62,142.0,-0.19,0.52,50.12,SR,ATH,CHEMICALS
83,TTKPRESTIG,2.15,-16.29,19.57,0.09,16510.0,-16413.0,84364.0,770.00,95.73,80.0,M-SC,6.39,250.0,-0.99,0.55,50.22,OX40N,NTT,DURABLES
72,SIS,1.19,-2.32,24.15,21.26,26191.0,-2580.0,108452.0,528.00,2587.56,54.0,H-SC,25.17,168.0,-0.10,0.71,61.25,OX40N,NTT,MISC

In [23]:
# top 5 RSP
df_tmp = df_portfolio_features.sort_values(by = 'RSP', ascending=False)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
60,QUESS,2.07,14.45,51.94,73.90,63483.0,15431.0,122224.0,424.0,-38.29,83.0,X-SC,17.80,80.0,0.24,0.80,66.62,XY24,NTT,MISC
69,SFL,2.99,-25.33,69.58,26.63,136244.0,-66409.0,195809.0,1287.0,48.38,72.0,M-SC,18.17,242.0,-0.49,1.28,63.20,XY24,NTT,MISC
64,RELAXO,-0.96,-47.41,189.62,52.31,144750.0,-68823.0,76337.0,1176.0,-44.05,69.0,X-SC,11.04,92.0,-0.48,0.50,70.68,X40N,NTT,FOOTWEAR
0,5PAISA,7.32,-25.74,52.03,12.90,84424.0,-56235.0,162261.0,593.0,139.18,81.0,H-SC,1.23,170.0,-0.67,1.06,56.58,OX40N,NTT,FINANCE
83,TTKPRESTIG,2.15,-16.29,19.57,0.09,16510.0,-16413.0,84364.0,770.0,95.73,80.0,M-SC,6.39,250.0,-0.99,0.55,50.22,OX40N,NTT,DURABLES

In [24]:
# Top N allocation
df_tmp = df_portfolio_features.sort_values(by = 'CurrAlloc%', ascending=False)
top_n_values = [10, 25, 50]

sum_df = pd.DataFrame({
    'Top_N': top_n_values,
    'Sum_Alloc%': [df_tmp['CurrAlloc%'].head(n).sum() for n in top_n_values]
})

sum_df

   Top_N  Sum_Alloc%
0     10       19.49
1     25       42.63
2     50       72.77

In [25]:
# market-cap-wise allocation
df_tmp = df_portfolio_features[cols]
df_tmp.groupby(df_tmp['Conviction'].str[-2:])['CurrAlloc%'].sum().sort_values(ascending=False)

Conviction
SC    43.95
LC    30.26
MC    25.84
Name: CurrAlloc%, dtype: float64

In [26]:
# criteria-wise allocation
df_portfolio_features.groupby('Criteria')['CurrAlloc%'].sum().sort_values(ascending=False)

Criteria
XY24     28.03
X40      24.43
X40N     17.44
XR        8.86
OX40N     7.24
AR        6.71
XY25      6.46
SR        0.88
Name: CurrAlloc%, dtype: float64

In [27]:
# conviction-wise allocation
df_portfolio_features.groupby('Conviction')['CurrAlloc%'].sum().sort_values(ascending=False)

Conviction
X-LC    28.30
H-SC    23.09
X-MC    20.76
M-SC    10.21
X-SC    10.08
H-MC     2.66
M-MC     2.07
H-LC     1.17
M-LC     0.79
L-SC     0.57
L-MC     0.35
Name: CurrAlloc%, dtype: float64

In [28]:
# sector-wise stats
df_tmp = df_portfolio_features.groupby('Category')[['CurrAlloc%', 'Current', 'Current P/L', 'FTT Amt']].sum().sort_values(by=['Current', 'Current P/L'], ascending=False)
df_tmp['Current P/L%'] = round(df_tmp['Current P/L'] * 100 / df_tmp['Current'], 2)
df_tmp['FTT%'] = round(df_tmp['FTT Amt'] * 100 / df_tmp['Current'], 2)
cols = ['CurrAlloc%', 'Current P/L%', 'FTT%']
df_tmp[cols].sort_values(by=['CurrAlloc%'], ascending=False)

               CurrAlloc%  Current P/L%    FTT%
Category
FMCG                14.52        -18.83   60.52
FINANCE             11.48         -4.84   50.27
IT                   9.44        -55.84  133.75
MISC                 7.22        -21.54   73.69
AUTO                 6.68         -6.83   46.67
BANKS                5.79         -2.26   49.54
PAINTS               5.55        -15.81   35.57
INSURANCE            5.27         -2.48   37.05
PHARMA               5.03          3.85   25.91
ELECTRICAL           4.08        -12.92   52.77
CHEMICALS            2.18        -21.74   93.96
HEALTHCARE           2.11        -10.55   39.39
APPARELS             1.96         10.61   19.42
AC                   1.75        -18.89   51.12
FOOTWEAR             1.75        -65.25  131.51
DURABLES             1.63        -55.02   92.74
REALTY               1.61         10.14    4.62
BREWERIES            1.54          1.04   19.51
TRAVEL               1.54        -90.39  185.72
CERAMICS             1.44        -39.03   81.27
CABLES               1.38         29.96   45.63
ENGINEERING          1.31        -20.40   75.47
REFINERIES           1.10        -19.49   49.73
CEMENT               1.06        -65.76  189.76
JEWELLERY            1.03       -102.62  173.01
ENTERTAINMENT        0.76        -66.58  165.94
TEXTILES             0.43        -40.31   80.32
HOTELS               0.41        -81.36  145.32

In [29]:
# money to be made criteria-wise
df_portfolio_features.groupby('Criteria')['FTT Amt'].agg(['sum', 'count']).sort_values(by='sum', ascending=False)

                sum  count
Criteria
XY24      3305347.0     21
X40       1931639.0     19
XR        1325141.0     13
AR        1148307.0      9
X40N      1046322.0     13
OX40N      682829.0     10
XY25       445120.0      5
SR         284358.0      2

In [30]:
# money to be made conviction-wise
df_portfolio_features.groupby('Conviction')['FTT Amt'].agg(['sum', 'count']).sort_values(by='sum', ascending=False)

                  sum  count
Conviction
H-SC        3242885.0     24
X-LC        1940549.0     21
X-MC        1534380.0     15
M-SC        1354755.0     14
X-SC        1260837.0      9
H-MC         290586.0      2
L-SC         203960.0      2
M-LC         170864.0      1
M-MC          66950.0      2
H-LC          54398.0      1
L-MC          48899.0      1

In [31]:
# money to be made criteria and conviction-wise
df_portfolio_features.groupby(['Conviction', 'Criteria'])['FTT Amt'].agg(['sum', 'count']).sort_values(by='sum', ascending=False)

                           sum  count
Conviction Criteria
X-LC       X40       1055121.0     10
H-SC       AR         954931.0      5
           XY24       924870.0      6
M-SC       XY24       808899.0      6
H-SC       XR         795371.0      7
X-SC       XY24       754687.0      4
X-MC       X40        659626.0      7
           X40N       409918.0      4
X-LC       XY24       351310.0      2
           X40N       347146.0      6
X-SC       X40N       289258.0      3
M-SC       OX40N      286500.0      5
H-SC       SR         284358.0      2
           OX40N      283355.0      4
H-MC       XY24       248704.0      1
X-MC       XY25       247959.0      2
X-SC       X40        216892.0      2
X-MC       XY24       216877.0      2
M-SC       XR         186924.0      2
M-LC       XR         170864.0      1
X-LC       XY25       154875.0      2
L-SC       OX40N      112974.0      1
           XR          90986.0      1
M-SC       AR          72432.0      1
H-LC       AR          54398.0      1
L-MC       XR          48899.0      1
M-MC       XY25        42286.0      1
H-MC       AR          41882.0      1
X-LC       XR          32097.0      1
M-MC       AR          24664.0      1

In [32]:
# notebook execution time

end_time = time.time()
execution_time = round(end_time - start_time, 0)
print(f"Notebook execution time: {execution_time} seconds")

Notebook execution time: 38.0 seconds