<a href="https://colab.research.google.com/github/ankit-rathi/Quantvesting_v2/blob/main/myStocks_Portfolio_Analysis.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
'''
!pip install pandas==2.2.2 -qq
!pip install pyxirr -qq
!pip install ta -qq
!pip install yfinance==0.2.59 -qq
'''

'\n!pip install pandas==2.2.2 -qq\n!pip install pyxirr -qq\n!pip install ta -qq\n!pip install yfinance==0.2.59 -qq\n'

In [2]:
# import libraries

import numpy as np
import pandas as pd
import datetime
import warnings
warnings.filterwarnings('ignore')
import yfinance as yfin
import ta
import matplotlib.pyplot as plt
import requests

In [3]:
# notebook start time
import time
import datetime
import pytz

start_time = time.time()

# function to print date timestamp
def print_date_time():
  tz_NY = pytz.timezone('Asia/Kolkata')
  datetime_NY = datetime.datetime.now(tz_NY)
  print("Run date time (IST):", datetime_NY.strftime("%Y-%m-%d %H:%M:%S"))

In [4]:
# function to get booked and reserved amount
def get_amt():
  # fetch the JSON data from the URL
  url = "https://raw.githubusercontent.com/ankit-rathi/Tradevesting_v1/main/data/myPortfolioAmts.json"
  response = requests.get(url)
  pf_amts = response.json()  # parse the JSON data

  # extract values from the JSON
  py_booked_amt_dm = pf_amts["py_booked_amt_dm"]
  py_booked_amt_sv = pf_amts["py_booked_amt_sv"]
  cy_booked_amt_dm = pf_amts["cy_booked_amt_dm"]
  cy_booked_amt_sv = pf_amts["cy_booked_amt_sv"]
  reserve_amt_dm = pf_amts["reserve_amt_dm"]
  reserve_amt_sv = pf_amts["reserve_amt_sv"]

  # perform calculations
  py_booked_amt = py_booked_amt_dm + py_booked_amt_sv
  cy_booked_amt = cy_booked_amt_dm + cy_booked_amt_sv
  reserve_amt = reserve_amt_dm + reserve_amt_sv
  total_booked_amt = py_booked_amt + cy_booked_amt

  return total_booked_amt, reserve_amt, cy_booked_amt, py_booked_amt

gen_output = 0

In [5]:
# function to format the amount
def format_amt(number):
    abs_number = abs(number)

    if abs_number >= 1_00_00_000:  # Crores
        formatted_amt = f"{number / 1_00_00_000:.2f} C"
    elif abs_number >= 1_00_000:  # Lakhs
        formatted_amt = f"{number / 1_00_000:.2f} L"
    elif abs_number >= 1_000:  # Thousands
        formatted_amt = f"{number / 1_000:.2f} K"
    else:
        formatted_amt = f"{number:.2f}"

    return formatted_amt

# function to set start and end date
def get_start_end_date():
  start_date = (datetime.date.today() + datetime.timedelta(days=-365)).strftime('%Y-%m-%d')
  end_date = (datetime.date.today() + datetime.timedelta(days=1)).strftime('%Y-%m-%d')
  return start_date, end_date

# function to fetch my portfolio csv
def get_mypfs_df():
  mypfs_df = pd.read_csv('https://raw.githubusercontent.com/ankit-rathi/Tradevesting_v1/main/data/myPortfolioStocks.csv')
  return mypfs_df

# function to fetch my prospects csv
def get_mypps_df():
  mypps_df = pd.read_csv('https://raw.githubusercontent.com/ankit-rathi/Tradevesting_v1/main/data/myProspectsScrips.csv')
  return mypps_df

# function to fetch screener data
def get_myscreen_df():
  myscreen_df = pd.read_csv('https://raw.githubusercontent.com/ankit-rathi/Tradevesting_v1/main/data/myScreenerDB.csv')
  return myscreen_df

# function to fetch momentum data
def get_myinvmt_df():
  myinvmt_df = pd.read_csv('https://raw.githubusercontent.com/ankit-rathi/Tradevesting_v1/main/data/myInvestments.csv')
  return myinvmt_df

# function to get the stock ids
def get_stock_ids(df_pf):
  stock_n100 = df_pf['Symbol'].unique()

  exclude = ['CADILAHC','MMTC', 'MASFIN']

  stock_ids = df_pf[~df_pf['Symbol'].isin(exclude) ]['Symbol'].unique()

  #mypf = mypf[mypf.Forecast.notnull()]
  #stock_ids = mypf['Symbol'].unique()

  #stock_ids.sort()
  return stock_ids

# get features from screener data
def get_screener_features():
  myscreen_df = get_myscreen_df()
  cols = ['Symbol', 'EPS', 'MedPE', 'ROCE%', 'ROE%', 'CapType']
  return myscreen_df[cols]

# get relative strength
def get_relative_strength(stock_list):

    # Dictionary to store stock tickers and their corresponding percentage price change
    stock_changes = {}

    # Loop through each stock and fetch its price data
    for stock in stock_list:
        try:
            # Download the stock data for the given date range
            stock_data = yfin.Ticker(stock + '.NS').history(period='1mo', interval='1d')[map(str.title, ['open', 'close', 'low', 'high', 'volume'])]

            # Calculate the percentage change for the stock
            if len(stock_data) > 0:
                start_price = stock_data['Close'].iloc[0]
                end_price = stock_data['Close'].iloc[-1]
                percent_change = round(((end_price - start_price) / start_price) * 100, 2)
                stock_changes[stock] = percent_change
            else:
                stock_changes[stock] = np.nan  # If no data is available, set to NaN

        except Exception as e:
            print(f"Error fetching data for {stock}: {e}")
            stock_changes[stock] = np.nan

    # Create a DataFrame with stock tickers and their percentage changes
    df = pd.DataFrame(list(stock_changes.items()), columns=['Symbol', 'Percent_Change'])

    # Drop any stocks with missing data (NaN values)
    df = df.dropna()

    # Calculate the percentile rank based on percentage change
    df['RSP'] = round(df['Percent_Change'].rank(pct=True) * 100, 2)
    cols = ['Symbol', 'RSP']
    df = df[cols]
    # Sort by percentile rank (optional)
    df = df.sort_values(by='RSP', ascending=False).reset_index(drop=True)

    return df

In [6]:
# function to get stock technicals
def stock_prec_dev(stock_symbol):
    #stock_symbol = 'ULTRACEMCO.NS'
    short_window = 20
    mid_window = 50
    long_window = 200
    moving_avg = 'SMA'

    start = datetime.datetime(*map(int, start_date.split('-')))
    end = datetime.datetime(*map(int, end_date.split('-')))

    stock_df = yfin.Ticker(stock_symbol + '.NS').history(period='max', interval='1d')[map(str.title, ['open', 'close', 'low', 'high', 'volume'])]

    stock_df['Max'] = round(max(stock_df['Close']),2)
    stock_df = stock_df[(stock_df.index <= end_date) & (stock_df.index >= start_date)]
    stock_df['200_SMA'] = round(stock_df['Close'].rolling(window = 200, min_periods = 1).mean(),0)
    stock_df['Dev%_200'] = round((stock_df['Close'] - stock_df['200_SMA'])*100/stock_df['200_SMA'],2)
    stock_df.dropna(axis = 0, inplace = True) # remove any null rows

    stock_df['20_SMA'] = stock_df['Close'].rolling(window=20).mean()
    stock_df['50_SMA'] = stock_df['Close'].rolling(window=50).mean()
    stock_df['Symbol'] = stock_symbol

    stock_df['Close'] = round(stock_df['Close'],2)
    stock_df['Min'] = round(min(stock_df['Close']),2)
    stock_df['RSI_14'] = ta.momentum.RSIIndicator(close=stock_df['Close'], window=14).rsi()
    stock_df['RSI_14'] = round(stock_df['RSI_14'],0)
    stock_df['Prev_Close'] = stock_df['Close'].shift(1)
    stock_df.drop(['Open', 'Low', 'High', 'Volume'], axis=1, inplace=True)
    stock_df = stock_df.tail(1)

    max_SMA = max(stock_df['20_SMA'].item(), stock_df['50_SMA'].item(), stock_df['200_SMA'].item())
    min_SMA = min(stock_df['20_SMA'].item(), stock_df['50_SMA'].item(), stock_df['200_SMA'].item())
    ABS_Spread = max_SMA - min_SMA
    stock_df['Spread%'] = round((ABS_Spread / stock_df['200_SMA'].item()) * 100,2)

    return stock_df

# function to compute stock attributes
def get_common_features(stock_ids, df_mypf):

  df_prec_dev = pd.DataFrame()
  df_tmp = get_screener_features()
  df_rs = get_relative_strength(stock_ids)

  for stock_id in stock_ids:
      tmp = stock_prec_dev(stock_id)
      tmp = tmp.reset_index()
      df_prec_dev = pd.concat([df_prec_dev, tmp], ignore_index = True)
  df_prec_dev = pd.merge(df_prec_dev, df_mypf, on= 'Symbol')
  df_prec_dev = pd.merge(df_prec_dev, df_tmp, on= 'Symbol', how='left')
  df_prec_dev = pd.merge(df_prec_dev, df_rs, on= 'Symbol', how='left')
  #print(df_prec_dev.columns)
  df_prec_dev['Curr_PE'] = round(df_prec_dev['Close']/df_prec_dev['EPS'],1)
  df_prec_dev['Dev%_PE'] = round((df_prec_dev['Curr_PE'] - df_prec_dev['MedPE'])*100/df_prec_dev['MedPE'],2)
  df_prec_dev['Conviction'] = df_prec_dev['Conviction'] + '-' + df_prec_dev['CapType']
  return df_prec_dev

# function to arrange stock features
def arrange_features(df_stocks, common_cols, diff_cols):
  df_stocks_common = df_stocks[common_cols].drop_duplicates()
  df_stocks_diff = df_stocks[diff_cols]
  df_stocks_diff['Investment'] = df_stocks_diff['AvgCost'] * df_stocks_diff['Shares']
  df_stocks_diff = df_stocks_diff.groupby(['Symbol'])[['Shares', 'Investment']].aggregate(['sum']).reset_index()
  df_stocks_diff.columns = ['Symbol', 'Shares', 'Investment']
  df_stocks_diff['AvgCost'] = round(df_stocks_diff['Investment']/df_stocks_diff['Shares'],2)
  df_stocks = pd.merge(df_stocks_diff, df_stocks_common, on='Symbol')
  return df_stocks

# plot fact distribution across dimension
def plot_pie_chart(df, dimension, fact):
  # grouping the data by category and calculating the sum of fact for each type
  grouped_data = df.groupby(dimension)[fact].sum()

  # sorting the grouped data in descending order
  grouped_data = grouped_data.sort_values(ascending=False)

  # creating a pie chart
  grouped_data.plot.pie(autopct='%1.1f%%', startangle=90, figsize=(6, 6))

  # adding a title and displaying the plot
  plt.title(f'{dimension} {fact} Distribution')
  plt.ylabel('')  # To hide the y-label
  plt.show()

In [7]:
# function to get portfolio features

def get_portfolio_features(df_common_features):

  print_date_time()
  print('-------------------')

  #df_common_features["Target"] = df_common_features["Target"].fillna(df_common_features["Max"])
  df_common_features['NTT'] = np.where(df_common_features['Strategy']== 'NTT', df_common_features["Target"], df_common_features['Max'])
  df_common_features['LTT'] = np.where(df_common_features['Strategy']== 'BTT', df_common_features["Target"], df_common_features['Max'])
  df_common_features['BOL'] = df_common_features['Min']

  tmp_df = df_common_features[df_common_features['Symbol'].isin(mypf_df[mypf_df['InPortfolio'] != 'NA'].Symbol.values)]
  print('qualified stocks: '+str(len(tmp_df['Symbol'].unique())))
  tmp_df1 = tmp_df[tmp_df['LatestQtr'] == 1]
  print('with latest results: '+str(len(tmp_df1['Symbol'].unique())))
  tmp_df1 = tmp_df1[tmp_df1['StarStock'] == 1]
  print('still star stocks: '+str(len(tmp_df1['Symbol'].unique())))
  tmp_df['Investment'] = tmp_df['AvgCost'] * tmp_df['Shares']
  tmp_df['Current'] = round(tmp_df['Close'] * tmp_df['Shares'],0)
  tmp_df['Previous'] = tmp_df['Prev_Close'] * tmp_df['Shares']
  tmp_df['EstimatedST'] = tmp_df['NTT'] * tmp_df['Shares']
  tmp_df['EstimatedLT'] = tmp_df['LTT'] * tmp_df['Shares']
  tmp_df['Current P/L'] = round((tmp_df['Current'] - tmp_df['Investment']),0)
  tmp_df['Today P/L%'] = round((tmp_df['Current'] - tmp_df['Previous'])*100/tmp_df['Previous'],2)
  tmp_df['Current P/L%'] = round((tmp_df['Current'] - tmp_df['Investment'])*100/tmp_df['Investment'],2)
  tmp_df['EstimatedST P/L%'] = round((tmp_df['EstimatedST'] - tmp_df['Investment'])*100/tmp_df['Investment'],2)
  tmp_df['EstimatedLT P/L%'] = round((tmp_df['EstimatedLT'] - tmp_df['Investment'])*100/tmp_df['Investment'],2)
  tmp_df['NTT%'] = round((tmp_df['NTT'] - tmp_df['Close'])*100/tmp_df['Close'],2)
  tmp_df['LTT%'] = round((tmp_df['LTT'] - tmp_df['Close'])*100/tmp_df['Close'],2)
  tmp_df['Gained%'] = round((tmp_df['Close'] - tmp_df['BOL'])*100/tmp_df['BOL'],2)
  investment = round(sum(tmp_df['AvgCost']*tmp_df['Shares']),0)
  current = round(sum(tmp_df['Close']*tmp_df['Shares']),0)
  tmp_df['InitAlloc%'] = round(tmp_df['Investment']*100/investment,2)
  tmp_df['CurrAlloc%'] = round(tmp_df['Current']*100/current,2)
  tmp_df['FTT'] = tmp_df['LTT']
  tmp_df.loc[tmp_df['Strategy'] == 'NTT', 'FTT'] = tmp_df['NTT']
  tmp_df['FTT%'] = tmp_df['LTT%']
  tmp_df.loc[tmp_df['Strategy'] == 'NTT', 'FTT%'] = tmp_df['NTT%']
  tmp_df['FTT Amt'] = round(tmp_df['FTT%'] * tmp_df['Current']/100,0)
  tmp_df['OTT%'] = round((tmp_df['FTT'] - tmp_df['AvgCost'])*100/tmp_df['AvgCost'],2)
  tmp_df['RRR Ind'] = round(tmp_df['Current P/L']/tmp_df['FTT Amt'],2)
  tmp_df['Risk Ind'] = round(tmp_df['Current P/L%']*tmp_df['CurrAlloc%'],0)

  return tmp_df

# function to print portfolio features
def print_portfolio_stats(df_portfolio_features, myinvmt_df):
  from pyxirr import xirr

  total_booked_amt, reserve_amt, cy_booked_amt, py_booked_amt = get_amt()

  dates = myinvmt_df['Date'].values
  dates = np.append(dates, datetime.date.today().strftime('%d-%b-%y'))
  investment = myinvmt_df['Investment'].values
  dates= pd.to_datetime(dates)

  current = round(sum(df_portfolio_features['Close']*df_portfolio_features['Shares']),0) + reserve_amt
  investment_xirr = np.append(investment, current)
  cagr = round(xirr(pd.DataFrame({"dates": dates, "amounts": investment_xirr}))*100,2)

  investment = -sum(investment)
  invested = round(sum(df_portfolio_features['AvgCost']*df_portfolio_features['Shares']),0) + reserve_amt
  previous = round(sum(df_portfolio_features['Prev_Close']*df_portfolio_features['Shares']),0) + reserve_amt
  cy_invested = investment + py_booked_amt

  today_pnl_amount = current-previous
  today_pnl_percentage = round((current-previous)*100/previous,2)

  curr_pnl_amount = current-invested
  curr_pnl_percentage = round((curr_pnl_amount)*100/(cy_invested),2)

  cy_pnl_amount = cy_booked_amt + curr_pnl_amount
  cy_pnl_percentage = round((cy_pnl_amount)*100/cy_invested,2)

  overall_pnl_amount = total_booked_amt + curr_pnl_amount
  overall_pnl_percentage = round((overall_pnl_amount)*100/investment,2)

  estimate_st = round(sum(df_portfolio_features['FTT']*df_portfolio_features['Shares']),0)  + reserve_amt
  est_st_pnl_amount = estimate_st-current
  est_st_pnl_percentage = round((est_st_pnl_amount)*100/current,2)

  estimate_lt = round(sum(df_portfolio_features['LTT']*df_portfolio_features['Shares']),0)  + reserve_amt
  est_lt_pnl_amount = estimate_lt-current
  est_lt_pnl_percentage = round((est_lt_pnl_amount)*100/current,2)

  total_profit = round(sum(df_portfolio_features[df_portfolio_features['Current P/L%'] > 0]['Current']) - sum(df_portfolio_features[df_portfolio_features['Current P/L%'] > 0]['Investment']),0)
  total_loss = round(sum(df_portfolio_features[df_portfolio_features['Current P/L%'] < 0]['Current']) - sum(df_portfolio_features[df_portfolio_features['Current P/L%'] < 0]['Investment']),0)

  cy_booked_percentage = round((cy_booked_amt)*100/current,2)
  py_booked_percentage = round((py_booked_amt)*100/investment,2)
  total_booked_percentage = round((total_booked_amt)*100/investment,2)

  print('-------------------')
  print('Initial Investment: ', format_amt(investment))
  print('CY Investment: ', format_amt(cy_invested))
  print('Reserve: ', format_amt(reserve_amt))
  print('Current: ',  format_amt(current))
  print('-------------------')
  print('Today PnL: '+ '{} ({}%)'.format(format_amt(today_pnl_amount), today_pnl_percentage))
  print('Current PnL: '+ '{} ({}%)'.format(format_amt(curr_pnl_amount), curr_pnl_percentage))
  print('CY Booked + Current PnL: '+ '{} ({}%)'.format(format_amt(cy_pnl_amount), cy_pnl_percentage))
  print('-------------------')
  print('Total profit: ', format_amt(total_profit))
  print('Total loss: ', format_amt(total_loss))
  print('-------------------')
  print('Total Booked + Current PnL: '+ '{} ({}%)'.format(format_amt(overall_pnl_amount), overall_pnl_percentage))
  print('Total Booked PnL: '+ '{} ({}%)'.format(format_amt(total_booked_amt), total_booked_percentage))
  print('Curr Year Booked PnL: '+ '{} ({}%)'.format(format_amt(cy_booked_amt), cy_booked_percentage))
  print('Prev Year Booked PnL: '+ '{} ({}%)'.format(format_amt(py_booked_amt), py_booked_percentage))
  print('===================')
  print('Est FTT: ',  format_amt(estimate_st))
  print('Est FTT PnL: '+ '{} ({}%)'.format(format_amt(est_st_pnl_amount), est_st_pnl_percentage))

  print('===================')
  print('Deployed: ', format_amt(investment))

  print('Current: ', format_amt(current))

  print('CAGR/XIRR %: '+'{}%'.format(cagr))

In [8]:
# get start and end date
start_date, end_date = get_start_end_date()

# get portfolio and prospects data
mypfs_df = get_mypfs_df()
mypps_df = get_mypps_df()
myinvmt_df = get_myinvmt_df()

# merge above datasets
mypf_df = pd.merge(mypfs_df, mypps_df, on="Symbol")

# seggregate dm and sv portfolio
dm_pf = mypf_df[mypf_df['InPortfolio'] == 'DM']
sv_pf = mypf_df[mypf_df['InPortfolio'] == 'SV']

# build portfolio stock dataframe
dm_stocks = get_stock_ids(dm_pf)
sv_stocks = get_stock_ids(sv_pf)
df_stocks = pd.concat([dm_pf,sv_pf], ignore_index = True)

# arrange common and diff stock features
common_cols = ['Symbol', 'Target', 'Criteria', 'Strategy', 'CumlRnk', 'LatestQtr', 'StarStock', 'Conviction', 'Category', 'InFolio', 'XIRR', 'MBQ']
diff_cols = ['Symbol', 'AvgCost', 'Shares']
df_stocks = arrange_features(df_stocks, common_cols, diff_cols)

# get common features
stock_ids = df_stocks['Symbol'].values
df_common_features = get_common_features(stock_ids, df_stocks)

df_common_features.reset_index(drop=True, inplace=True)
df_common_features.drop(['Date'], axis=1, inplace=True)
# get and print portfolio features
df_portfolio_features = get_portfolio_features(df_common_features)

print_portfolio_stats(df_portfolio_features, myinvmt_df)

df = df_portfolio_features
#plot_pie_chart(df, 'CapType', 'Current')
list_ox40n = list(df[df['MBQ'].str.contains('OX40N', na=False)]['Symbol'].values)

Run date time (IST): 2026-07-24 13:24:46
-------------------
qualified stocks: 92
with latest results: 31
still star stocks: 20
-------------------
Initial Investment:  1.40 C
CY Investment:  1.82 C
Reserve:  1.49 K
Current:  1.51 C
-------------------
Today PnL: 30.48 K (0.2%)
Current PnL: -31.85 L (-17.47%)
CY Booked + Current PnL: -29.77 L (-16.32%)
-------------------
Total profit:  4.73 L
Total loss:  -36.58 L
-------------------
Total Booked + Current PnL: 13.10 L (9.39%)
Total Booked PnL: 44.95 L (32.22%)
Curr Year Booked PnL: 2.08 L (1.37%)
Prev Year Booked PnL: 42.87 L (30.73%)
===================
Est FTT:  2.55 C
Est FTT PnL: 1.04 C (68.42%)
===================
Deployed:  1.40 C
Current:  1.51 C
CAGR/XIRR %: 3.64%

In [9]:
# top 5 near their targets
cols = ['Symbol', 'Today P/L%', 'Current P/L%', 'FTT%', 'OTT%', 'FTT Amt', 'Current P/L', 'Current', 'FTT', 'Dev%_PE', 'RSI_14','Conviction', 'Spread%',  'CumlRnk', 'RRR Ind', 'CurrAlloc%', 'Gained%', 'Criteria', 'Strategy', 'Category']
df_tmp = df_portfolio_features[~df_portfolio_features['Symbol'].isin(['ENRIN','BLUSPRING','DIGITIDE'])]
df_tmp = df_tmp.sort_values(by = 'FTT Amt', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
59,PIDILITIND,0.63,11.54,5.36,17.52,8437.0,16290.0,157400.0,1658.32,-21.83,54.0,X-LC,8.05,5.0,1.93,1.04,24.48,X40,ATH,CHEMICALS
68,SATIN,6.24,48.27,2.40,51.83,9832.0,133366.0,409650.0,274.00,32.72,60.0,H-SC,45.05,159.0,13.56,2.71,99.56,XY24,NTT,FINANCE
73,SONACOMS,0.32,26.09,9.99,38.69,12742.0,26390.0,127549.0,801.69,-0.08,80.0,M-MC,25.60,193.0,2.07,0.84,80.96,AR,ATH,AUTO
75,SURYODAY,12.02,15.66,6.37,23.03,13194.0,28050.0,207121.0,216.00,125.88,67.0,H-SC,23.48,166.0,2.13,1.37,75.81,XR,NTT,BANKS
49,JSWINFRA,-1.28,9.06,6.76,16.43,16350.0,20090.0,241864.0,342.00,-6.40,48.0,X-MC,18.76,61.0,1.23,1.60,37.13,X40N,NTT,REALTY

In [10]:
# top 5 today
df_tmp = df_portfolio_features.sort_values(by = 'Today P/L%', ascending=False)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
75,SURYODAY,12.02,15.66,6.37,23.03,13194.0,28050.0,207121.0,216.00,125.88,67.0,H-SC,23.48,166.0,2.13,1.37,75.81,XR,NTT,BANKS
68,SATIN,6.24,48.27,2.40,51.83,9832.0,133366.0,409650.0,274.00,32.72,60.0,H-SC,45.05,159.0,13.56,2.71,99.56,XY24,NTT,FINANCE
84,UNITDSPR,4.97,8.28,11.53,20.77,29232.0,19384.0,253528.0,1644.00,-4.01,72.0,X-MC,4.59,64.0,0.66,1.68,21.87,X40N,NTT,BREWERIES
39,ICICIGI,4.63,-12.24,35.47,18.89,62293.0,-24488.0,175621.0,2244.41,-26.21,41.0,X-MC,6.64,66.0,-0.39,1.16,4.63,X40,ATH,INSURANCE
78,TATAELXSI,4.52,-48.97,158.73,32.03,106786.0,-64560.0,67275.0,9161.00,-36.16,41.0,H-SC,21.63,158.0,-0.60,0.44,4.52,OX40N,NTT,IT

In [11]:
# bottom 5 today
df_tmp = df_portfolio_features.sort_values(by = 'Today P/L%', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
62,RAJOOENG,-4.96,-47.80,167.48,39.61,89602.0,-49000.0,53500.0,143.10,-64.67,53.0,H-SC,20.51,136.0,-0.55,0.35,14.61,AR,ATH,MISC
67,ROUTE,-4.24,-56.36,285.30,68.16,165688.0,-74991.0,58075.0,2215.45,-64.57,56.0,H-SC,8.46,141.0,-0.45,0.38,38.35,SR,ATH,IT
1,ABBOTINDIA,-3.25,-6.20,25.88,18.07,43416.0,-11095.0,167760.0,35195.00,-20.15,60.0,X-MC,2.63,58.0,-0.26,1.11,11.04,X40,ATH,PHARMA
52,LAOPALA,-3.16,-44.92,152.50,39.09,110132.0,-58887.0,72218.0,464.00,58.13,52.0,H-SC,8.71,154.0,-0.53,0.48,12.05,AR,NTT,CERAMICS
27,GLAXO,-3.09,-0.69,36.63,35.69,72495.0,-1372.0,197912.0,3380.16,-24.24,57.0,X-MC,5.01,56.0,-0.02,1.31,17.63,X40,ATH,PHARMA

In [12]:
# top 5 to exit based on CumlRnk
df_tmp = df_portfolio_features[~df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])]
df_tmp = df_tmp[(df_tmp['Current P/L%'] > -1) & (df_tmp['Current P/L%'] < 1)].sort_values(by = 'CumlRnk', ascending=False)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
72,SIS,0.38,0.76,20.34,21.26,22757.0,849.0,111881.0,528.0,2672.54,58.0,H-SC,24.63,168.0,0.04,0.74,66.35,OX40N,NTT,MISC

In [13]:
# OX40N stocks to exit
df_tmp = df_portfolio_features[(df_portfolio_features['Symbol'].isin(list_ox40n))].sort_values(by = 'Current P/L%', ascending=False)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
25,FINCABLES,-1.86,26.15,64.81,107.91,120710.0,38608.0,186252.0,1641.55,13.65,38.0,M-SC,20.82,220.0,0.32,1.23,40.12,OX40N,ATH,CABLES
72,SIS,0.38,0.76,20.34,21.26,22757.0,849.0,111881.0,528.00,2672.54,58.0,H-SC,24.63,168.0,0.04,0.74,66.35,OX40N,NTT,MISC
83,TTKPRESTIG,-2.24,-16.50,19.87,0.09,16720.0,-16629.0,84148.0,770.00,95.30,57.0,M-SC,10.62,250.0,-0.99,0.56,49.84,OX40N,NTT,DURABLES
16,CERA,-1.01,-20.97,56.77,23.89,78917.0,-36891.0,139012.0,9475.00,-23.87,45.0,H-SC,14.71,153.0,-0.47,0.92,35.13,OX40N,NTT,CERAMICS
43,INDIGOPNTS,-0.61,-24.82,33.04,0.02,43358.0,-43330.0,131229.0,1408.00,100.33,54.0,M-SC,3.81,222.0,-1.00,0.87,48.89,OX40N,NTT,PAINTS

In [14]:
# top 5 to book for rotation
df_tmp = df_portfolio_features[(df_portfolio_features['Current P/L%'] > 20) ].sort_values(by = 'CumlRnk', ascending=False)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
25,FINCABLES,-1.86,26.15,64.81,107.91,120710.0,38608.0,186252.0,1641.55,13.65,38.0,M-SC,20.82,220.0,0.32,1.23,40.12,OX40N,ATH,CABLES
73,SONACOMS,0.32,26.09,9.99,38.69,12742.0,26390.0,127549.0,801.69,-0.08,80.0,M-MC,25.60,193.0,2.07,0.84,80.96,AR,ATH,AUTO
68,SATIN,6.24,48.27,2.40,51.83,9832.0,133366.0,409650.0,274.00,32.72,60.0,H-SC,45.05,159.0,13.56,2.71,99.56,XY24,NTT,FINANCE
60,QUESS,0.08,21.36,43.29,73.90,56106.0,22811.0,129604.0,424.00,-34.99,67.0,X-SC,33.37,80.0,0.41,0.86,76.68,XY24,NTT,MISC

In [15]:
# top 5 to monitor for exit
df_tmp = df_portfolio_features[~df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])]
df_tmp = df_tmp[(df_tmp['Current P/L%'] > 0) ].sort_values(by = 'Dev%_PE', ascending=False)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
72,SIS,0.38,0.76,20.34,21.26,22757.0,849.0,111881.0,528.00,2672.54,58.0,H-SC,24.63,168.0,0.04,0.74,66.35,OX40N,NTT,MISC
75,SURYODAY,12.02,15.66,6.37,23.03,13194.0,28050.0,207121.0,216.00,125.88,67.0,H-SC,23.48,166.0,2.13,1.37,75.81,XR,NTT,BANKS
74,STARHEALTH,1.28,13.67,29.55,47.26,94426.0,38423.0,319546.0,761.00,79.42,55.0,H-SC,19.03,173.0,0.41,2.11,38.67,XY24,NTT,INSURANCE
68,SATIN,6.24,48.27,2.40,51.83,9832.0,133366.0,409650.0,274.00,32.72,60.0,H-SC,45.05,159.0,13.56,2.71,99.56,XY24,NTT,FINANCE
25,FINCABLES,-1.86,26.15,64.81,107.91,120710.0,38608.0,186252.0,1641.55,13.65,38.0,M-SC,20.82,220.0,0.32,1.23,40.12,OX40N,ATH,CABLES

In [16]:
# top 5 to book for rotation from weak conviction
df_tmp = df_portfolio_features[~df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])]
df_tmp = df_tmp[~df_tmp['Criteria'].isin(['XY25','XY24','X40', 'X40N'])].sort_values(by = 'RRR Ind', ascending=False)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
75,SURYODAY,12.02,15.66,6.37,23.03,13194.0,28050.0,207121.0,216.00,125.88,67.0,H-SC,23.48,166.0,2.13,1.37,75.81,XR,NTT,BANKS
73,SONACOMS,0.32,26.09,9.99,38.69,12742.0,26390.0,127549.0,801.69,-0.08,80.0,M-MC,25.60,193.0,2.07,0.84,80.96,AR,ATH,AUTO
91,ZYDUSLIFE,-1.54,16.95,15.98,35.63,39165.0,35515.0,245089.0,1286.17,1.80,46.0,H-MC,17.20,120.0,0.91,1.62,28.86,AR,ATH,PHARMA
25,FINCABLES,-1.86,26.15,64.81,107.91,120710.0,38608.0,186252.0,1641.55,13.65,38.0,M-SC,20.82,220.0,0.32,1.23,40.12,OX40N,ATH,CABLES
72,SIS,0.38,0.76,20.34,21.26,22757.0,849.0,111881.0,528.00,2672.54,58.0,H-SC,24.63,168.0,0.04,0.74,66.35,OX40N,NTT,MISC

In [17]:
# top 5 to accumulate based on lowest RSI_14
df_tmp = df_portfolio_features[df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])].sort_values(by = 'RSI_14', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
87,VBL,-0.71,-7.93,47.03,35.37,136763.0,-25042.0,290800.0,670.16,-18.65,30.0,X-LC,6.99,13.0,-0.18,1.92,19.52,X40N,ATH,FMCG
81,TMPV,0.11,-26.10,84.81,36.58,223021.0,-92875.0,262966.0,600.00,-84.72,34.0,X-LC,7.55,4.0,-0.42,1.74,10.52,XY24,NTT,AUTO
34,HDFCBANK,-0.13,-10.72,43.79,28.37,91826.0,-25189.0,209696.0,1073.00,-23.99,35.0,X-LC,10.70,26.0,-0.27,1.39,3.70,X40,BTT,BANKS
7,BAJAJHFL,-0.52,-24.64,115.12,62.13,236892.0,-67268.0,205778.0,181.50,-38.00,39.0,X-MC,6.65,60.0,-0.28,1.36,15.43,X40N,ATH,FINANCE
45,INFY,-1.67,-29.89,91.47,34.24,200657.0,-93519.0,219369.0,1972.00,-44.85,40.0,X-LC,20.66,3.0,-0.47,1.45,4.53,X40,NTT,IT

In [18]:
# top 5 to accumulate based on Spread and CumlRnk
df_tmp = df_portfolio_features[df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])]
df_tmp = df_tmp[(df_tmp['CumlRnk'] < 100)].sort_values(by = 'Spread%', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
11,BERGEPAINT,1.11,-8.02,36.25,25.32,85939.0,-20677.0,237072.0,680.00,-13.04,47.0,X-MC,1.47,68.0,-0.24,1.57,23.39,XY24,NTT,PAINTS
19,COLPAL,-0.79,-20.63,76.21,39.86,159309.0,-54325.0,209040.0,3683.41,-4.06,56.0,X-MC,1.69,62.0,-0.34,1.38,18.24,XY25,ATH,FMCG
23,DMART,0.41,-3.44,34.21,29.60,82455.0,-8574.0,241026.0,5391.45,-18.53,44.0,X-LC,1.82,14.0,-0.10,1.59,10.17,X40N,ATH,FMCG
1,ABBOTINDIA,-3.25,-6.20,25.88,18.07,43416.0,-11095.0,167760.0,35195.00,-20.15,60.0,X-MC,2.63,58.0,-0.26,1.11,11.04,X40,ATH,PHARMA
17,CIPLA,0.28,14.88,16.15,33.43,28417.0,22795.0,175956.0,1648.14,-11.14,48.0,X-LC,3.10,18.0,0.80,1.16,20.12,X40N,ATH,PHARMA

In [19]:
# top 5 to accumulate based on lowest Gained%
df_tmp = df_portfolio_features[df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])].sort_values(by = 'Gained%', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
65,RELIANCE,0.71,-17.76,52.36,25.30,86538.0,-35688.0,165275.0,1952.00,-20.03,43.0,X-LC,7.67,21.0,-0.41,1.09,1.78,XY25,BTT,REFINERIES
35,HDFCLIFE,0.78,-9.19,46.13,32.71,62753.0,-13764.0,136036.0,811.41,-29.12,42.0,X-LC,15.72,31.0,-0.22,0.90,2.20,X40,ATH,INSURANCE
47,ITC,0.87,-25.26,59.30,19.06,150764.0,-85926.0,254240.0,452.00,-59.16,49.0,X-LC,12.49,1.0,-0.57,1.68,2.98,X40,NTT,FMCG
58,PGHH,0.06,-32.53,95.65,32.01,137805.0,-69448.0,144072.0,17616.87,-54.37,51.0,X-MC,19.94,57.0,-0.50,0.95,3.26,X40,ATH,FMCG
34,HDFCBANK,-0.13,-10.72,43.79,28.37,91826.0,-25189.0,209696.0,1073.00,-23.99,35.0,X-LC,10.70,26.0,-0.27,1.39,3.70,X40,BTT,BANKS

In [20]:
# top 5 to accumulate based on lowest CurrAlloc%
df_tmp = df_portfolio_features[df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])].sort_values(by = 'CurrAlloc%', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
10,BATAINDIA,-1.76,-56.00,207.26,35.20,117346.0,-72052.0,56618.0,2096.00,-25.78,46.0,X-SC,17.55,91.0,-0.61,0.37,12.29,X40,NTT,FOOTWEAR
64,RELAXO,-1.42,-48.74,197.12,52.31,146677.0,-70750.0,74410.0,1176.00,-45.41,52.0,X-SC,11.53,92.0,-0.48,0.49,66.37,X40N,NTT,FOOTWEAR
60,QUESS,0.08,21.36,43.29,73.90,56106.0,22811.0,129604.0,424.00,-34.99,67.0,X-SC,33.37,80.0,0.41,0.86,76.68,XY24,NTT,MISC
35,HDFCLIFE,0.78,-9.19,46.13,32.71,62753.0,-13764.0,136036.0,811.41,-29.12,42.0,X-LC,15.72,31.0,-0.22,0.90,2.20,X40,ATH,INSURANCE
28,GODREJCP,-0.60,-4.92,38.28,31.47,54089.0,-7315.0,141299.0,1469.04,0.03,52.0,X-LC,6.23,32.0,-0.14,0.93,8.42,X40N,ATH,FMCG

In [21]:
# top 5 to accumulate based on CumlRnk
df_tmp = df_portfolio_features.sort_values(by = 'CumlRnk', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
47,ITC,0.87,-25.26,59.30,19.06,150764.0,-85926.0,254240.0,452.00,-59.16,49.0,X-LC,12.49,1.0,-0.57,1.68,2.98,X40,NTT,FMCG
79,TCS,0.39,-33.90,87.90,24.20,269166.0,-157055.0,306218.0,4230.71,-43.95,60.0,X-LC,19.04,2.0,-0.58,2.02,14.19,X40,ATH,IT
45,INFY,-1.67,-29.89,91.47,34.24,200657.0,-93519.0,219369.0,1972.00,-44.85,40.0,X-LC,20.66,3.0,-0.47,1.45,4.53,X40,NTT,IT
81,TMPV,0.11,-26.10,84.81,36.58,223021.0,-92875.0,262966.0,600.00,-84.72,34.0,X-LC,7.55,4.0,-0.42,1.74,10.52,XY24,NTT,AUTO
59,PIDILITIND,0.63,11.54,5.36,17.52,8437.0,16290.0,157400.0,1658.32,-21.83,54.0,X-LC,8.05,5.0,1.93,1.04,24.48,X40,ATH,CHEMICALS

In [22]:
# top 5 for average up
df_tmp = df_portfolio_features[(df_portfolio_features['Dev%_200'] > 5)].sort_values(by = 'CurrAlloc%', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
44,INDUSINDBK,-0.48,-26.12,79.88,32.89,45561.0,-20170.0,57037.0,1800.00,-368.21,53.0,L-MC,13.45,258.0,-0.44,0.38,40.62,XR,NTT,BANKS
64,RELAXO,-1.42,-48.74,197.12,52.31,146677.0,-70750.0,74410.0,1176.00,-45.41,52.0,X-SC,11.53,92.0,-0.48,0.49,66.37,X40N,NTT,FOOTWEAR
3,ALKYLAMINE,-1.94,-23.85,152.84,92.54,117510.0,-24079.0,76884.0,4520.85,-18.40,46.0,H-SC,12.01,142.0,-0.20,0.51,46.00,SR,ATH,CHEMICALS
83,TTKPRESTIG,-2.24,-16.50,19.87,0.09,16720.0,-16629.0,84148.0,770.00,95.30,57.0,M-SC,10.62,250.0,-0.99,0.56,49.84,OX40N,NTT,DURABLES
72,SIS,0.38,0.76,20.34,21.26,22757.0,849.0,111881.0,528.00,2672.54,58.0,H-SC,24.63,168.0,0.04,0.74,66.35,OX40N,NTT,MISC

In [23]:
# top 5 RSP
df_tmp = df_portfolio_features.sort_values(by = 'RSP', ascending=False)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
60,QUESS,0.08,21.36,43.29,73.90,56106.0,22811.0,129604.0,424.00,-34.99,67.0,X-SC,33.37,80.0,0.41,0.86,76.68,XY24,NTT,MISC
75,SURYODAY,12.02,15.66,6.37,23.03,13194.0,28050.0,207121.0,216.00,125.88,67.0,H-SC,23.48,166.0,2.13,1.37,75.81,XR,NTT,BANKS
73,SONACOMS,0.32,26.09,9.99,38.69,12742.0,26390.0,127549.0,801.69,-0.08,80.0,M-MC,25.60,193.0,2.07,0.84,80.96,AR,ATH,AUTO
77,TANLA,-1.71,-31.29,216.20,117.25,402203.0,-84728.0,186033.0,1922.32,-30.60,65.0,H-SC,6.39,147.0,-0.21,1.23,62.88,AR,ATH,IT
33,HCLTECH,1.53,-17.98,46.65,20.28,92562.0,-43507.0,198417.0,1853.42,-13.98,68.0,X-LC,16.59,8.0,-0.47,1.31,23.45,X40,ATH,IT

In [24]:
# Top N allocation
df_tmp = df_portfolio_features.sort_values(by = 'CurrAlloc%', ascending=False)
top_n_values = [10, 25, 50]

sum_df = pd.DataFrame({
    'Top_N': top_n_values,
    'Sum_Alloc%': [df_tmp['CurrAlloc%'].head(n).sum() for n in top_n_values]
})

sum_df

   Top_N  Sum_Alloc%
0     10       19.30
1     25       42.34
2     50       72.76

In [25]:
# market-cap-wise allocation
df_tmp = df_portfolio_features[cols]
df_tmp.groupby(df_tmp['Conviction'].str[-2:])['CurrAlloc%'].sum().sort_values(ascending=False)

Conviction
SC    43.45
LC    30.13
MC    26.43
Name: CurrAlloc%, dtype: float64

In [26]:
# criteria-wise allocation
df_portfolio_features.groupby('Criteria')['CurrAlloc%'].sum().sort_values(ascending=False)

Criteria
XY24     27.35
X40      24.84
X40N     17.38
XR        8.96
AR        7.04
OX40N     7.02
XY25      6.53
SR        0.89
Name: CurrAlloc%, dtype: float64

In [27]:
# conviction-wise allocation
df_portfolio_features.groupby('Conviction')['CurrAlloc%'].sum().sort_values(ascending=False)

Conviction
X-LC    28.10
H-SC    22.87
X-MC    21.21
X-SC    10.13
M-SC     9.91
H-MC     2.68
M-MC     2.16
H-LC     1.22
M-LC     0.81
L-SC     0.54
L-MC     0.38
Name: CurrAlloc%, dtype: float64

In [28]:
# sector-wise stats
df_tmp = df_portfolio_features.groupby('Category')[['CurrAlloc%', 'Current', 'Current P/L', 'FTT Amt']].sum().sort_values(by=['Current', 'Current P/L'], ascending=False)
df_tmp['Current P/L%'] = round(df_tmp['Current P/L'] * 100 / df_tmp['Current'], 2)
df_tmp['FTT%'] = round(df_tmp['FTT Amt'] * 100 / df_tmp['Current'], 2)
cols = ['CurrAlloc%', 'Current P/L%', 'FTT%']
df_tmp[cols].sort_values(by=['CurrAlloc%'], ascending=False)

               CurrAlloc%  Current P/L%    FTT%
Category
FMCG                14.31        -22.18   65.04
FINANCE             11.36         -7.27   53.75
IT                  10.24        -45.18  117.03
MISC                 7.27        -21.82   74.09
AUTO                 6.63         -9.17   49.88
BANKS                5.55         -8.30   58.34
PAINTS               5.38        -21.30   41.99
INSURANCE            5.25         -4.21   39.36
PHARMA               5.20          5.83   23.32
ELECTRICAL           4.18        -11.87   51.22
CHEMICALS            2.14        -25.48   99.54
HEALTHCARE           2.12        -11.61   40.73
APPARELS             1.87          5.08   26.81
AC                   1.81        -16.53   48.14
FOOTWEAR             1.69        -72.55  141.74
BREWERIES            1.68          7.65   11.53
DURABLES             1.62        -58.62   97.21
REALTY               1.60          8.31    6.76
TRAVEL               1.50        -96.88  195.46
CERAMICS             1.40        -45.34   89.50
ENGINEERING          1.23        -29.90   89.31
CABLES               1.23         20.73   64.81
JEWELLERY            1.10        -92.63  159.56
REFINERIES           1.09        -21.59   52.36
CEMENT               1.06        -66.86  191.69
ENTERTAINMENT        0.71        -79.27  186.20
TEXTILES             0.41        -48.69   91.08
HOTELS               0.38        -97.13  166.67

In [29]:
# money to be made criteria-wise
df_portfolio_features.groupby('Criteria')['FTT Amt'].agg(['sum', 'count']).sort_values(by='sum', ascending=False)

                sum  count
Criteria
XY24      3462252.0     21
X40       1909754.0     19
XR        1321583.0     13
AR        1108220.0      9
X40N      1089681.0     13
OX40N      730736.0     10
XY25       447919.0      5
SR         283198.0      2

In [30]:
# money to be made conviction-wise
df_portfolio_features.groupby('Conviction')['FTT Amt'].agg(['sum', 'count']).sort_values(by='sum', ascending=False)

                  sum  count
Conviction
H-SC        3309571.0     24
X-LC        2018611.0     21
X-MC        1510622.0     15
M-SC        1421062.0     14
X-SC        1270247.0      9
H-MC         292002.0      2
L-SC         209686.0      2
M-LC         168849.0      1
M-MC          58772.0      2
H-LC          48360.0      1
L-MC          45561.0      1

In [31]:
# money to be made criteria and conviction-wise
df_portfolio_features.groupby(['Conviction', 'Criteria'])['FTT Amt'].agg(['sum', 'count']).sort_values(by='sum', ascending=False)

                           sum  count
Conviction Criteria
X-LC       X40       1041125.0     10
H-SC       XY24      1019645.0      6
           AR         931631.0      5
M-SC       XY24       833662.0      6
H-SC       XR         774736.0      7
X-SC       XY24       745580.0      4
X-MC       X40        656372.0      7
X-LC       X40N       397688.0      6
X-MC       X40N       379583.0      4
X-LC       XY24       373659.0      2
M-SC       OX40N      316691.0      5
X-SC       X40N       312410.0      3
H-SC       OX40N      300361.0      4
           SR         283198.0      2
H-MC       XY24       252837.0      1
X-MC       XY25       237798.0      2
           XY24       236869.0      2
X-SC       X40        212257.0      2
M-SC       XR         194387.0      2
M-LC       XR         168849.0      1
X-LC       XY25       164091.0      2
L-SC       OX40N      113684.0      1
           XR          96002.0      1
M-SC       AR          76322.0      1
H-LC       AR          48360.0      1
M-MC       XY25        46030.0      1
L-MC       XR          45561.0      1
X-LC       XR          42048.0      1
H-MC       AR          39165.0      1
M-MC       AR          12742.0      1

In [32]:
# notebook execution time

end_time = time.time()
execution_time = round(end_time - start_time, 0)
print(f"Notebook execution time: {execution_time} seconds")

Notebook execution time: 58.0 seconds