<a href="https://colab.research.google.com/github/ankit-rathi/Quantvesting_v2/blob/main/myStocks_Portfolio_Analysis.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
'''
!pip install pandas==2.2.2 -qq
!pip install pyxirr -qq
!pip install ta -qq
!pip install yfinance==0.2.59 -qq
'''

'\n!pip install pandas==2.2.2 -qq\n!pip install pyxirr -qq\n!pip install ta -qq\n!pip install yfinance==0.2.59 -qq\n'

In [2]:
# import libraries

import numpy as np
import pandas as pd
import datetime
import warnings
warnings.filterwarnings('ignore')
import yfinance as yfin
import ta
import matplotlib.pyplot as plt
import requests

In [3]:
# notebook start time
import time
import datetime
import pytz

start_time = time.time()

# function to print date timestamp
def print_date_time():
  tz_NY = pytz.timezone('Asia/Kolkata')
  datetime_NY = datetime.datetime.now(tz_NY)
  print("Run date time (IST):", datetime_NY.strftime("%Y-%m-%d %H:%M:%S"))

In [4]:
# function to get booked and reserved amount
def get_amt():
  # fetch the JSON data from the URL
  url = "https://raw.githubusercontent.com/ankit-rathi/Tradevesting_v1/main/data/myPortfolioAmts.json"
  response = requests.get(url)
  pf_amts = response.json()  # parse the JSON data

  # extract values from the JSON
  py_booked_amt_dm = pf_amts["py_booked_amt_dm"]
  py_booked_amt_sv = pf_amts["py_booked_amt_sv"]
  cy_booked_amt_dm = pf_amts["cy_booked_amt_dm"]
  cy_booked_amt_sv = pf_amts["cy_booked_amt_sv"]
  reserve_amt_dm = pf_amts["reserve_amt_dm"]
  reserve_amt_sv = pf_amts["reserve_amt_sv"]

  # perform calculations
  py_booked_amt = py_booked_amt_dm + py_booked_amt_sv
  cy_booked_amt = cy_booked_amt_dm + cy_booked_amt_sv
  reserve_amt = reserve_amt_dm + reserve_amt_sv
  total_booked_amt = py_booked_amt + cy_booked_amt

  return total_booked_amt, reserve_amt, cy_booked_amt, py_booked_amt

gen_output = 0

In [5]:
# function to format the amount
def format_amt(number):
    abs_number = abs(number)

    if abs_number >= 1_00_00_000:  # Crores
        formatted_amt = f"{number / 1_00_00_000:.2f} C"
    elif abs_number >= 1_00_000:  # Lakhs
        formatted_amt = f"{number / 1_00_000:.2f} L"
    elif abs_number >= 1_000:  # Thousands
        formatted_amt = f"{number / 1_000:.2f} K"
    else:
        formatted_amt = f"{number:.2f}"

    return formatted_amt

# function to set start and end date
def get_start_end_date():
  start_date = (datetime.date.today() + datetime.timedelta(days=-365)).strftime('%Y-%m-%d')
  end_date = (datetime.date.today() + datetime.timedelta(days=1)).strftime('%Y-%m-%d')
  return start_date, end_date

# function to fetch my portfolio csv
def get_mypfs_df():
  mypfs_df = pd.read_csv('https://raw.githubusercontent.com/ankit-rathi/Tradevesting_v1/main/data/myPortfolioStocks.csv')
  return mypfs_df

# function to fetch my prospects csv
def get_mypps_df():
  mypps_df = pd.read_csv('https://raw.githubusercontent.com/ankit-rathi/Tradevesting_v1/main/data/myProspectsScrips.csv')
  return mypps_df

# function to fetch screener data
def get_myscreen_df():
  myscreen_df = pd.read_csv('https://raw.githubusercontent.com/ankit-rathi/Tradevesting_v1/main/data/myScreenerDB.csv')
  return myscreen_df

# function to fetch momentum data
def get_myinvmt_df():
  myinvmt_df = pd.read_csv('https://raw.githubusercontent.com/ankit-rathi/Tradevesting_v1/main/data/myInvestments.csv')
  return myinvmt_df

# function to get the stock ids
def get_stock_ids(df_pf):
  stock_n100 = df_pf['Symbol'].unique()

  exclude = ['CADILAHC','MMTC', 'MASFIN']

  stock_ids = df_pf[~df_pf['Symbol'].isin(exclude) ]['Symbol'].unique()

  #mypf = mypf[mypf.Forecast.notnull()]
  #stock_ids = mypf['Symbol'].unique()

  #stock_ids.sort()
  return stock_ids

# get features from screener data
def get_screener_features():
  myscreen_df = get_myscreen_df()
  cols = ['Symbol', 'EPS', 'MedPE', 'ROCE%', 'ROE%', 'CapType']
  return myscreen_df[cols]

# get relative strength
def get_relative_strength(stock_list):

    # Dictionary to store stock tickers and their corresponding percentage price change
    stock_changes = {}

    # Loop through each stock and fetch its price data
    for stock in stock_list:
        try:
            # Download the stock data for the given date range
            stock_data = yfin.Ticker(stock + '.NS').history(period='1mo', interval='1d')[map(str.title, ['open', 'close', 'low', 'high', 'volume'])]

            # Calculate the percentage change for the stock
            if len(stock_data) > 0:
                start_price = stock_data['Close'].iloc[0]
                end_price = stock_data['Close'].iloc[-1]
                percent_change = round(((end_price - start_price) / start_price) * 100, 2)
                stock_changes[stock] = percent_change
            else:
                stock_changes[stock] = np.nan  # If no data is available, set to NaN

        except Exception as e:
            print(f"Error fetching data for {stock}: {e}")
            stock_changes[stock] = np.nan

    # Create a DataFrame with stock tickers and their percentage changes
    df = pd.DataFrame(list(stock_changes.items()), columns=['Symbol', 'Percent_Change'])

    # Drop any stocks with missing data (NaN values)
    df = df.dropna()

    # Calculate the percentile rank based on percentage change
    df['RSP'] = round(df['Percent_Change'].rank(pct=True) * 100, 2)
    cols = ['Symbol', 'RSP']
    df = df[cols]
    # Sort by percentile rank (optional)
    df = df.sort_values(by='RSP', ascending=False).reset_index(drop=True)

    return df

In [6]:
# function to get stock technicals
def stock_prec_dev(stock_symbol):
    #stock_symbol = 'ULTRACEMCO.NS'
    short_window = 20
    mid_window = 50
    long_window = 200
    moving_avg = 'SMA'

    start = datetime.datetime(*map(int, start_date.split('-')))
    end = datetime.datetime(*map(int, end_date.split('-')))

    stock_df = yfin.Ticker(stock_symbol + '.NS').history(period='max', interval='1d')[map(str.title, ['open', 'close', 'low', 'high', 'volume'])]

    stock_df['Max'] = round(max(stock_df['Close']),2)
    stock_df = stock_df[(stock_df.index <= end_date) & (stock_df.index >= start_date)]
    stock_df['200_SMA'] = round(stock_df['Close'].rolling(window = 200, min_periods = 1).mean(),0)
    stock_df['Dev%_200'] = round((stock_df['Close'] - stock_df['200_SMA'])*100/stock_df['200_SMA'],2)
    stock_df.dropna(axis = 0, inplace = True) # remove any null rows

    stock_df['20_SMA'] = stock_df['Close'].rolling(window=20).mean()
    stock_df['50_SMA'] = stock_df['Close'].rolling(window=50).mean()
    stock_df['Symbol'] = stock_symbol

    stock_df['Close'] = round(stock_df['Close'],2)
    stock_df['Min'] = round(min(stock_df['Close']),2)
    stock_df['RSI_14'] = ta.momentum.RSIIndicator(close=stock_df['Close'], window=14).rsi()
    stock_df['RSI_14'] = round(stock_df['RSI_14'],0)
    stock_df['Prev_Close'] = stock_df['Close'].shift(1)
    stock_df.drop(['Open', 'Low', 'High', 'Volume'], axis=1, inplace=True)
    stock_df = stock_df.tail(1)

    max_SMA = max(stock_df['20_SMA'].item(), stock_df['50_SMA'].item(), stock_df['200_SMA'].item())
    min_SMA = min(stock_df['20_SMA'].item(), stock_df['50_SMA'].item(), stock_df['200_SMA'].item())
    ABS_Spread = max_SMA - min_SMA
    stock_df['Spread%'] = round((ABS_Spread / stock_df['200_SMA'].item()) * 100,2)

    return stock_df

# function to compute stock attributes
def get_common_features(stock_ids, df_mypf):

  df_prec_dev = pd.DataFrame()
  df_tmp = get_screener_features()
  df_rs = get_relative_strength(stock_ids)

  for stock_id in stock_ids:
      tmp = stock_prec_dev(stock_id)
      tmp = tmp.reset_index()
      df_prec_dev = pd.concat([df_prec_dev, tmp], ignore_index = True)
  df_prec_dev = pd.merge(df_prec_dev, df_mypf, on= 'Symbol')
  df_prec_dev = pd.merge(df_prec_dev, df_tmp, on= 'Symbol', how='left')
  df_prec_dev = pd.merge(df_prec_dev, df_rs, on= 'Symbol', how='left')
  #print(df_prec_dev.columns)
  df_prec_dev['Curr_PE'] = round(df_prec_dev['Close']/df_prec_dev['EPS'],1)
  df_prec_dev['Dev%_PE'] = round((df_prec_dev['Curr_PE'] - df_prec_dev['MedPE'])*100/df_prec_dev['MedPE'],2)
  df_prec_dev['Conviction'] = df_prec_dev['Conviction'] + '-' + df_prec_dev['CapType']
  return df_prec_dev

# function to arrange stock features
def arrange_features(df_stocks, common_cols, diff_cols):
  df_stocks_common = df_stocks[common_cols].drop_duplicates()
  df_stocks_diff = df_stocks[diff_cols]
  df_stocks_diff['Investment'] = df_stocks_diff['AvgCost'] * df_stocks_diff['Shares']
  df_stocks_diff = df_stocks_diff.groupby(['Symbol'])[['Shares', 'Investment']].aggregate(['sum']).reset_index()
  df_stocks_diff.columns = ['Symbol', 'Shares', 'Investment']
  df_stocks_diff['AvgCost'] = round(df_stocks_diff['Investment']/df_stocks_diff['Shares'],2)
  df_stocks = pd.merge(df_stocks_diff, df_stocks_common, on='Symbol')
  return df_stocks

# plot fact distribution across dimension
def plot_pie_chart(df, dimension, fact):
  # grouping the data by category and calculating the sum of fact for each type
  grouped_data = df.groupby(dimension)[fact].sum()

  # sorting the grouped data in descending order
  grouped_data = grouped_data.sort_values(ascending=False)

  # creating a pie chart
  grouped_data.plot.pie(autopct='%1.1f%%', startangle=90, figsize=(6, 6))

  # adding a title and displaying the plot
  plt.title(f'{dimension} {fact} Distribution')
  plt.ylabel('')  # To hide the y-label
  plt.show()

In [7]:
# function to get portfolio features

def get_portfolio_features(df_common_features):

  print_date_time()
  print('-------------------')

  #df_common_features["Target"] = df_common_features["Target"].fillna(df_common_features["Max"])
  df_common_features['NTT'] = np.where(df_common_features['Strategy']== 'NTT', df_common_features["Target"], df_common_features['Max'])
  df_common_features['LTT'] = np.where(df_common_features['Strategy']== 'BTT', df_common_features["Target"], df_common_features['Max'])
  df_common_features['BOL'] = df_common_features['Min']

  tmp_df = df_common_features[df_common_features['Symbol'].isin(mypf_df[mypf_df['InPortfolio'] != 'NA'].Symbol.values)]
  print('qualified stocks: '+str(len(tmp_df['Symbol'].unique())))
  tmp_df1 = tmp_df[tmp_df['LatestQtr'] == 1]
  print('with latest results: '+str(len(tmp_df1['Symbol'].unique())))
  tmp_df1 = tmp_df1[tmp_df1['StarStock'] == 1]
  print('still star stocks: '+str(len(tmp_df1['Symbol'].unique())))
  tmp_df['Investment'] = tmp_df['AvgCost'] * tmp_df['Shares']
  tmp_df['Current'] = round(tmp_df['Close'] * tmp_df['Shares'],0)
  tmp_df['Previous'] = tmp_df['Prev_Close'] * tmp_df['Shares']
  tmp_df['EstimatedST'] = tmp_df['NTT'] * tmp_df['Shares']
  tmp_df['EstimatedLT'] = tmp_df['LTT'] * tmp_df['Shares']
  tmp_df['Current P/L'] = round((tmp_df['Current'] - tmp_df['Investment']),0)
  tmp_df['Today P/L%'] = round((tmp_df['Current'] - tmp_df['Previous'])*100/tmp_df['Previous'],2)
  tmp_df['Current P/L%'] = round((tmp_df['Current'] - tmp_df['Investment'])*100/tmp_df['Investment'],2)
  tmp_df['EstimatedST P/L%'] = round((tmp_df['EstimatedST'] - tmp_df['Investment'])*100/tmp_df['Investment'],2)
  tmp_df['EstimatedLT P/L%'] = round((tmp_df['EstimatedLT'] - tmp_df['Investment'])*100/tmp_df['Investment'],2)
  tmp_df['NTT%'] = round((tmp_df['NTT'] - tmp_df['Close'])*100/tmp_df['Close'],2)
  tmp_df['LTT%'] = round((tmp_df['LTT'] - tmp_df['Close'])*100/tmp_df['Close'],2)
  tmp_df['Gained%'] = round((tmp_df['Close'] - tmp_df['BOL'])*100/tmp_df['BOL'],2)
  investment = round(sum(tmp_df['AvgCost']*tmp_df['Shares']),0)
  current = round(sum(tmp_df['Close']*tmp_df['Shares']),0)
  tmp_df['InitAlloc%'] = round(tmp_df['Investment']*100/investment,2)
  tmp_df['CurrAlloc%'] = round(tmp_df['Current']*100/current,2)
  tmp_df['FTT'] = tmp_df['LTT']
  tmp_df.loc[tmp_df['Strategy'] == 'NTT', 'FTT'] = tmp_df['NTT']
  tmp_df['FTT%'] = tmp_df['LTT%']
  tmp_df.loc[tmp_df['Strategy'] == 'NTT', 'FTT%'] = tmp_df['NTT%']
  tmp_df['FTT Amt'] = round(tmp_df['FTT%'] * tmp_df['Current']/100,0)
  tmp_df['OTT%'] = round((tmp_df['FTT'] - tmp_df['AvgCost'])*100/tmp_df['AvgCost'],2)
  tmp_df['RRR Ind'] = round(tmp_df['Current P/L']/tmp_df['FTT Amt'],2)
  tmp_df['Risk Ind'] = round(tmp_df['Current P/L%']*tmp_df['CurrAlloc%'],0)

  return tmp_df

# function to print portfolio features
def print_portfolio_stats(df_portfolio_features, myinvmt_df):
  from pyxirr import xirr

  total_booked_amt, reserve_amt, cy_booked_amt, py_booked_amt = get_amt()

  dates = myinvmt_df['Date'].values
  dates = np.append(dates, datetime.date.today().strftime('%d-%b-%y'))
  investment = myinvmt_df['Investment'].values
  dates= pd.to_datetime(dates)

  current = round(sum(df_portfolio_features['Close']*df_portfolio_features['Shares']),0) + reserve_amt
  investment_xirr = np.append(investment, current)
  cagr = round(xirr(pd.DataFrame({"dates": dates, "amounts": investment_xirr}))*100,2)

  investment = -sum(investment)
  invested = round(sum(df_portfolio_features['AvgCost']*df_portfolio_features['Shares']),0) + reserve_amt
  previous = round(sum(df_portfolio_features['Prev_Close']*df_portfolio_features['Shares']),0) + reserve_amt
  cy_invested = investment + py_booked_amt

  today_pnl_amount = current-previous
  today_pnl_percentage = round((current-previous)*100/previous,2)

  curr_pnl_amount = current-invested
  curr_pnl_percentage = round((curr_pnl_amount)*100/(cy_invested),2)

  cy_pnl_amount = cy_booked_amt + curr_pnl_amount
  cy_pnl_percentage = round((cy_pnl_amount)*100/cy_invested,2)

  overall_pnl_amount = total_booked_amt + curr_pnl_amount
  overall_pnl_percentage = round((overall_pnl_amount)*100/investment,2)

  estimate_st = round(sum(df_portfolio_features['FTT']*df_portfolio_features['Shares']),0)  + reserve_amt
  est_st_pnl_amount = estimate_st-current
  est_st_pnl_percentage = round((est_st_pnl_amount)*100/current,2)

  estimate_lt = round(sum(df_portfolio_features['LTT']*df_portfolio_features['Shares']),0)  + reserve_amt
  est_lt_pnl_amount = estimate_lt-current
  est_lt_pnl_percentage = round((est_lt_pnl_amount)*100/current,2)

  total_profit = round(sum(df_portfolio_features[df_portfolio_features['Current P/L%'] > 0]['Current']) - sum(df_portfolio_features[df_portfolio_features['Current P/L%'] > 0]['Investment']),0)
  total_loss = round(sum(df_portfolio_features[df_portfolio_features['Current P/L%'] < 0]['Current']) - sum(df_portfolio_features[df_portfolio_features['Current P/L%'] < 0]['Investment']),0)

  cy_booked_percentage = round((cy_booked_amt)*100/current,2)
  py_booked_percentage = round((py_booked_amt)*100/investment,2)
  total_booked_percentage = round((total_booked_amt)*100/investment,2)

  print('-------------------')
  print('Initial Investment: ', format_amt(investment))
  print('CY Investment: ', format_amt(cy_invested))
  print('Reserve: ', format_amt(reserve_amt))
  print('Current: ',  format_amt(current))
  print('-------------------')
  print('Today PnL: '+ '{} ({}%)'.format(format_amt(today_pnl_amount), today_pnl_percentage))
  print('Current PnL: '+ '{} ({}%)'.format(format_amt(curr_pnl_amount), curr_pnl_percentage))
  print('CY Booked + Current PnL: '+ '{} ({}%)'.format(format_amt(cy_pnl_amount), cy_pnl_percentage))
  print('-------------------')
  print('Total profit: ', format_amt(total_profit))
  print('Total loss: ', format_amt(total_loss))
  print('-------------------')
  print('Total Booked + Current PnL: '+ '{} ({}%)'.format(format_amt(overall_pnl_amount), overall_pnl_percentage))
  print('Total Booked PnL: '+ '{} ({}%)'.format(format_amt(total_booked_amt), total_booked_percentage))
  print('Curr Year Booked PnL: '+ '{} ({}%)'.format(format_amt(cy_booked_amt), cy_booked_percentage))
  print('Prev Year Booked PnL: '+ '{} ({}%)'.format(format_amt(py_booked_amt), py_booked_percentage))
  print('===================')
  print('Est FTT: ',  format_amt(estimate_st))
  print('Est FTT PnL: '+ '{} ({}%)'.format(format_amt(est_st_pnl_amount), est_st_pnl_percentage))

  print('===================')
  print('Deployed: ', format_amt(investment))

  print('Current: ', format_amt(current))

  print('CAGR/XIRR %: '+'{}%'.format(cagr))

In [8]:
# get start and end date
start_date, end_date = get_start_end_date()

# get portfolio and prospects data
mypfs_df = get_mypfs_df()
mypps_df = get_mypps_df()
myinvmt_df = get_myinvmt_df()

# merge above datasets
mypf_df = pd.merge(mypfs_df, mypps_df, on="Symbol")

# seggregate dm and sv portfolio
dm_pf = mypf_df[mypf_df['InPortfolio'] == 'DM']
sv_pf = mypf_df[mypf_df['InPortfolio'] == 'SV']

# build portfolio stock dataframe
dm_stocks = get_stock_ids(dm_pf)
sv_stocks = get_stock_ids(sv_pf)
df_stocks = pd.concat([dm_pf,sv_pf], ignore_index = True)

# arrange common and diff stock features
common_cols = ['Symbol', 'Target', 'Criteria', 'Strategy', 'CumlRnk', 'LatestQtr', 'StarStock', 'Conviction', 'Category', 'InFolio', 'XIRR', 'MBQ']
diff_cols = ['Symbol', 'AvgCost', 'Shares']
df_stocks = arrange_features(df_stocks, common_cols, diff_cols)

# get common features
stock_ids = df_stocks['Symbol'].values
df_common_features = get_common_features(stock_ids, df_stocks)

df_common_features.reset_index(drop=True, inplace=True)
df_common_features.drop(['Date'], axis=1, inplace=True)
# get and print portfolio features
df_portfolio_features = get_portfolio_features(df_common_features)

print_portfolio_stats(df_portfolio_features, myinvmt_df)

df = df_portfolio_features
#plot_pie_chart(df, 'CapType', 'Current')
list_ox40n = list(df[df['MBQ'].str.contains('OX40N', na=False)]['Symbol'].values)

Run date time (IST): 2026-07-13 11:06:43
-------------------
qualified stocks: 92
with latest results: 31
still star stocks: 20
-------------------
Initial Investment:  1.40 C
CY Investment:  1.82 C
Reserve:  1.49 K
Current:  1.53 C
-------------------
Today PnL: 75.38 K (0.49%)
Current PnL: -29.70 L (-16.28%)
CY Booked + Current PnL: -27.62 L (-15.14%)
-------------------
Total profit:  4.90 L
Total loss:  -34.59 L
-------------------
Total Booked + Current PnL: 15.25 L (10.93%)
Total Booked PnL: 44.95 L (32.22%)
Curr Year Booked PnL: 2.08 L (1.36%)
Prev Year Booked PnL: 42.87 L (30.73%)
===================
Est FTT:  2.55 C
Est FTT PnL: 1.01 C (66.12%)
===================
Deployed:  1.40 C
Current:  1.53 C
CAGR/XIRR %: 4.34%

In [9]:
# top 5 near their targets
cols = ['Symbol', 'Today P/L%', 'Current P/L%', 'FTT%', 'OTT%', 'FTT Amt', 'Current P/L', 'Current', 'FTT', 'Dev%_PE', 'RSI_14','Conviction', 'Spread%',  'CumlRnk', 'RRR Ind', 'CurrAlloc%', 'Gained%', 'Criteria', 'Strategy', 'Category']
df_tmp = df_portfolio_features[~df_portfolio_features['Symbol'].isin(['ENRIN','BLUSPRING','DIGITIDE'])]
df_tmp = df_tmp.sort_values(by = 'FTT Amt', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
49,JSWINFRA,6.42,19.58,-2.63,16.43,-6975.0,43420.0,265194.0,342.00,2.58,72.0,X-MC,15.07,61.0,-6.23,1.73,50.36,X40N,NTT,REALTY
68,SATIN,4.91,49.22,1.75,51.83,7215.0,135999.0,412283.0,274.00,34.03,67.0,H-SC,43.34,159.0,18.85,2.69,100.84,XY24,NTT,FINANCE
59,PIDILITIND,-1.56,11.52,6.14,18.37,9662.0,16250.0,157360.0,1670.26,-21.94,52.0,X-LC,8.44,5.0,1.68,1.03,23.56,X40,ATH,CHEMICALS
83,TTKPRESTIG,3.15,-15.38,18.28,0.09,15589.0,-15496.0,85281.0,770.00,97.87,69.0,M-SC,6.51,250.0,-0.99,0.56,51.85,OX40N,NTT,DURABLES
55,MASFIN,0.48,-0.80,22.54,21.57,21909.0,-780.0,97200.0,397.04,-14.63,58.0,H-SC,0.91,167.0,-0.04,0.63,15.86,XR,ATH,FINANCE

In [10]:
# top 5 today
df_tmp = df_portfolio_features.sort_values(by = 'Today P/L%', ascending=False)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
69,SFL,6.66,-19.69,57.67,26.63,121448.0,-51626.0,210592.0,1287.00,59.44,76.0,M-SC,22.47,242.0,-0.43,1.37,75.76,XY24,NTT,MISC
49,JSWINFRA,6.42,19.58,-2.63,16.43,-6975.0,43420.0,265194.0,342.00,2.58,72.0,X-MC,15.07,61.0,-6.23,1.73,50.36,X40N,NTT,REALTY
68,SATIN,4.91,49.22,1.75,51.83,7215.0,135999.0,412283.0,274.00,34.03,67.0,H-SC,43.34,159.0,18.85,2.69,100.84,XY24,NTT,FINANCE
67,ROUTE,4.88,-56.52,286.71,68.16,165899.0,-75203.0,57863.0,2215.45,-64.89,65.0,H-SC,11.15,141.0,-0.45,0.38,37.85,SR,ATH,IT
60,QUESS,3.87,22.75,41.66,73.90,54613.0,24300.0,131093.0,424.00,-33.88,75.0,X-SC,26.22,80.0,0.44,0.85,78.71,XY24,NTT,MISC

In [11]:
# bottom 5 today
df_tmp = df_portfolio_features.sort_values(by = 'Today P/L%', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
39,ICICIGI,-3.30,-6.46,27.10,18.89,50727.0,-12924.0,187185.0,2244.41,-21.30,46.0,X-MC,4.11,66.0,-0.25,1.22,4.94,X40,ATH,INSURANCE
3,ALKYLAMINE,-2.26,-18.58,136.48,92.54,112191.0,-18760.0,82203.0,4520.85,-12.74,61.0,H-SC,10.58,142.0,-0.17,0.54,56.10,SR,ATH,CHEMICALS
23,DMART,-2.26,-4.12,35.17,29.60,84170.0,-10278.0,239322.0,5391.45,-19.16,37.0,X-LC,3.24,14.0,-0.12,1.56,9.39,X40N,ATH,FMCG
87,VBL,-1.82,-5.18,42.77,35.37,128086.0,-16365.0,299477.0,670.16,-16.25,31.0,X-LC,8.74,13.0,-0.13,1.95,23.09,X40N,ATH,FMCG
59,PIDILITIND,-1.56,11.52,6.14,18.37,9662.0,16250.0,157360.0,1670.26,-21.94,52.0,X-LC,8.44,5.0,1.68,1.03,23.56,X40,ATH,CHEMICALS

In [12]:
# top 5 to exit based on CumlRnk
df_tmp = df_portfolio_features[~df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])]
df_tmp = df_tmp[(df_tmp['Current P/L%'] > -1) & (df_tmp['Current P/L%'] < 1)].sort_values(by = 'CumlRnk', ascending=False)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
72,SIS,0.39,0.41,20.77,21.26,23156.0,454.0,111486.0,528.00,2662.69,61.0,H-SC,25.28,168.0,0.02,0.73,65.76,OX40N,NTT,MISC
55,MASFIN,0.48,-0.80,22.54,21.57,21909.0,-780.0,97200.0,397.04,-14.63,58.0,H-SC,0.91,167.0,-0.04,0.63,15.86,XR,ATH,FINANCE

In [13]:
# OX40N stocks to exit
df_tmp = df_portfolio_features[(df_portfolio_features['Symbol'].isin(list_ox40n))].sort_values(by = 'Current P/L%', ascending=False)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
25,FINCABLES,0.87,34.72,54.32,107.91,108049.0,51268.0,198912.0,1641.55,21.26,46.0,M-SC,26.81,220.0,0.47,1.30,49.65,OX40N,ATH,CABLES
72,SIS,0.39,0.41,20.77,21.26,23156.0,454.0,111486.0,528.00,2662.69,61.0,H-SC,25.28,168.0,0.02,0.73,65.76,OX40N,NTT,MISC
83,TTKPRESTIG,3.15,-15.38,18.28,0.09,15589.0,-15496.0,85281.0,770.00,97.87,69.0,M-SC,6.51,250.0,-0.99,0.56,51.85,OX40N,NTT,DURABLES
16,CERA,1.79,-15.97,47.44,23.89,70121.0,-28093.0,147810.0,9475.00,-18.85,62.0,H-SC,16.05,153.0,-0.40,0.96,43.68,OX40N,NTT,CERAMICS
69,SFL,6.66,-19.69,57.67,26.63,121448.0,-51626.0,210592.0,1287.00,59.44,76.0,M-SC,22.47,242.0,-0.43,1.37,75.76,XY24,NTT,MISC

In [14]:
# top 5 to book for rotation
df_tmp = df_portfolio_features[(df_portfolio_features['Current P/L%'] > 20) ].sort_values(by = 'CumlRnk', ascending=False)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
25,FINCABLES,0.87,34.72,54.32,107.91,108049.0,51268.0,198912.0,1641.55,21.26,46.0,M-SC,26.81,220.0,0.47,1.30,49.65,OX40N,ATH,CABLES
68,SATIN,4.91,49.22,1.75,51.83,7215.0,135999.0,412283.0,274.00,34.03,67.0,H-SC,43.34,159.0,18.85,2.69,100.84,XY24,NTT,FINANCE
60,QUESS,3.87,22.75,41.66,73.90,54613.0,24300.0,131093.0,424.00,-33.88,75.0,X-SC,26.22,80.0,0.44,0.85,78.71,XY24,NTT,MISC

In [15]:
# top 5 to monitor for exit
df_tmp = df_portfolio_features[~df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])]
df_tmp = df_tmp[(df_tmp['Current P/L%'] > 0) ].sort_values(by = 'Dev%_PE', ascending=False)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
72,SIS,0.39,0.41,20.77,21.26,23156.0,454.0,111486.0,528.0,2662.69,61.0,H-SC,25.28,168.0,0.02,0.73,65.76,OX40N,NTT,MISC
9,BANDHANBNK,1.18,2.21,88.25,92.42,251268.0,6164.0,284723.0,400.0,144.25,58.0,H-SC,20.81,174.0,0.02,1.86,56.85,XY24,NTT,BANKS
75,SURYODAY,1.29,6.33,15.71,23.03,29914.0,11343.0,190414.0,216.0,108.33,67.0,H-SC,20.98,166.0,0.38,1.24,60.32,XR,NTT,BANKS
74,STARHEALTH,0.73,17.59,25.24,47.26,83434.0,49439.0,330562.0,761.0,85.67,74.0,H-SC,18.31,173.0,0.59,2.15,43.92,XY24,NTT,INSURANCE
68,SATIN,4.91,49.22,1.75,51.83,7215.0,135999.0,412283.0,274.0,34.03,67.0,H-SC,43.34,159.0,18.85,2.69,100.84,XY24,NTT,FINANCE

In [16]:
# top 5 to book for rotation from weak conviction
df_tmp = df_portfolio_features[~df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])]
df_tmp = df_tmp[~df_tmp['Criteria'].isin(['XY25','XY24','X40', 'X40N'])].sort_values(by = 'RRR Ind', ascending=False)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
91,ZYDUSLIFE,-1.38,19.68,13.33,35.63,33433.0,41239.0,250813.0,1286.17,4.05,59.0,H-MC,15.71,120.0,1.23,1.63,31.87,AR,ATH,PHARMA
73,SONACOMS,0.21,15.90,19.66,38.69,23050.0,16082.0,117241.0,801.69,-8.18,72.0,M-MC,21.37,193.0,0.70,0.76,66.34,AR,ATH,AUTO
25,FINCABLES,0.87,34.72,54.32,107.91,108049.0,51268.0,198912.0,1641.55,21.26,46.0,M-SC,26.81,220.0,0.47,1.30,49.65,OX40N,ATH,CABLES
75,SURYODAY,1.29,6.33,15.71,23.03,29914.0,11343.0,190414.0,216.00,108.33,67.0,H-SC,20.98,166.0,0.38,1.24,60.32,XR,NTT,BANKS
72,SIS,0.39,0.41,20.77,21.26,23156.0,454.0,111486.0,528.00,2662.69,61.0,H-SC,25.28,168.0,0.02,0.73,65.76,OX40N,NTT,MISC

In [17]:
# top 5 to accumulate based on lowest RSI_14
df_tmp = df_portfolio_features[df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])].sort_values(by = 'RSI_14', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
87,VBL,-1.82,-5.18,42.77,35.37,128086.0,-16365.0,299477.0,670.16,-16.25,31.0,X-LC,8.74,13.0,-0.13,1.95,23.09,X40N,ATH,FMCG
47,ITC,-0.34,-26.04,60.97,19.06,153399.0,-88569.0,251597.0,452.00,-59.56,36.0,X-LC,12.34,1.0,-0.58,1.64,1.37,X40,NTT,FMCG
23,DMART,-2.26,-4.12,35.17,29.60,84170.0,-10278.0,239322.0,5391.45,-19.16,37.0,X-LC,3.24,14.0,-0.12,1.56,9.39,X40N,ATH,FMCG
81,TMPV,-0.65,-23.57,78.70,36.58,214031.0,-83883.0,271958.0,600.00,-83.62,38.0,X-LC,8.09,4.0,-0.39,1.77,14.29,XY24,NTT,AUTO
51,KOTAKBANK,-0.28,0.61,20.37,21.11,28380.0,852.0,139324.0,453.24,-13.74,39.0,X-LC,4.36,12.0,0.03,0.91,6.55,X40,ATH,BANKS

In [18]:
# top 5 to accumulate based on Spread and CumlRnk
df_tmp = df_portfolio_features[df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])]
df_tmp = df_tmp[(df_tmp['CumlRnk'] < 100)].sort_values(by = 'Spread%', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
17,CIPLA,-1.06,15.30,15.72,33.43,27762.0,23440.0,176601.0,1648.14,-10.79,51.0,X-LC,2.25,18.0,0.84,1.15,20.56,X40N,ATH,PHARMA
19,COLPAL,-1.03,-22.88,81.34,39.86,165218.0,-60245.0,203120.0,3683.41,-6.75,49.0,X-MC,2.85,62.0,-0.36,1.32,14.90,XY25,ATH,FMCG
11,BERGEPAINT,-0.68,-8.99,37.69,25.32,88413.0,-23170.0,234579.0,680.00,-13.99,40.0,X-MC,3.00,68.0,-0.26,1.53,22.09,XY24,NTT,PAINTS
23,DMART,-2.26,-4.12,35.17,29.60,84170.0,-10278.0,239322.0,5391.45,-19.16,37.0,X-LC,3.24,14.0,-0.12,1.56,9.39,X40N,ATH,FMCG
84,UNITDSPR,-0.27,1.52,18.96,20.77,45069.0,3560.0,237704.0,1644.00,-10.02,58.0,X-MC,4.09,64.0,0.08,1.55,14.26,X40N,NTT,BREWERIES

In [19]:
# top 5 to accumulate based on lowest Gained%
df_tmp = df_portfolio_features[df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])].sort_values(by = 'Gained%', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
47,ITC,-0.34,-26.04,60.97,19.06,153399.0,-88569.0,251597.0,452.00,-59.56,36.0,X-LC,12.34,1.0,-0.58,1.64,1.37,X40,NTT,FMCG
58,PGHH,0.21,-32.87,96.65,32.01,138534.0,-70184.0,143336.0,17616.87,-54.64,44.0,X-MC,20.42,57.0,-0.51,0.93,1.65,X40,ATH,FMCG
65,RELIANCE,-0.65,-16.60,50.23,25.30,84191.0,-33353.0,167610.0,1952.00,-18.88,47.0,X-LC,7.14,21.0,-0.40,1.09,3.22,XY25,BTT,REFINERIES
32,HAVELLS,-0.60,-24.37,73.76,31.42,182979.0,-79918.0,248073.0,2052.62,-28.80,49.0,X-MC,11.19,63.0,-0.44,1.62,4.63,X40,ATH,ELECTRICAL
36,HINDUNILVR,-1.15,-17.30,37.45,13.67,79611.0,-44483.0,212580.0,2922.00,-38.66,43.0,X-LC,5.07,9.0,-0.56,1.39,4.64,XY25,NTT,FMCG

In [20]:
# top 5 to accumulate based on lowest CurrAlloc%
df_tmp = df_portfolio_features[df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])].sort_values(by = 'CurrAlloc%', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
10,BATAINDIA,-0.30,-55.58,204.39,35.20,116817.0,-71516.0,57154.0,2096.00,-25.05,48.0,X-SC,19.00,91.0,-0.61,0.37,13.35,X40,NTT,FOOTWEAR
64,RELAXO,2.41,-47.65,190.95,52.31,145103.0,-69170.0,75990.0,1176.00,-44.25,64.0,X-SC,12.27,92.0,-0.48,0.50,69.90,X40N,NTT,FOOTWEAR
60,QUESS,3.87,22.75,41.66,73.90,54613.0,24300.0,131093.0,424.00,-33.88,75.0,X-SC,26.22,80.0,0.44,0.85,78.71,XY24,NTT,MISC
35,HDFCLIFE,0.88,-6.33,41.68,32.71,58482.0,-9488.0,140312.0,811.41,-26.88,48.0,X-LC,15.00,31.0,-0.16,0.91,5.41,X40,ATH,INSURANCE
51,KOTAKBANK,-0.28,0.61,20.37,21.11,28380.0,852.0,139324.0,453.24,-13.74,39.0,X-LC,4.36,12.0,0.03,0.91,6.55,X40,ATH,BANKS

In [21]:
# top 5 to accumulate based on CumlRnk
df_tmp = df_portfolio_features.sort_values(by = 'CumlRnk', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
47,ITC,-0.34,-26.04,60.97,19.06,153399.0,-88569.0,251597.0,452.00,-59.56,36.0,X-LC,12.34,1.0,-0.58,1.64,1.37,X40,NTT,FMCG
79,TCS,3.48,-37.15,98.68,24.88,287346.0,-172083.0,291190.0,4253.91,-46.90,52.0,X-LC,21.62,2.0,-0.60,1.90,7.99,X40,ATH,IT
45,INFY,1.10,-26.50,82.64,34.24,190052.0,-82912.0,229976.0,1972.00,-42.31,50.0,X-LC,21.34,3.0,-0.44,1.50,9.58,X40,NTT,IT
81,TMPV,-0.65,-23.57,78.70,36.58,214031.0,-83883.0,271958.0,600.00,-83.62,38.0,X-LC,8.09,4.0,-0.39,1.77,14.29,XY24,NTT,AUTO
59,PIDILITIND,-1.56,11.52,6.14,18.37,9662.0,16250.0,157360.0,1670.26,-21.94,52.0,X-LC,8.44,5.0,1.68,1.03,23.56,X40,ATH,CHEMICALS

In [22]:
# top 5 for average up
df_tmp = df_portfolio_features[(df_portfolio_features['Dev%_200'] > 5)].sort_values(by = 'CurrAlloc%', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
44,INDUSINDBK,-0.60,-25.46,78.27,32.89,45047.0,-19654.0,57553.0,1800.00,-371.01,65.0,L-MC,10.00,258.0,-0.44,0.38,41.89,XR,NTT,BANKS
64,RELAXO,2.41,-47.65,190.95,52.31,145103.0,-69170.0,75990.0,1176.00,-44.25,64.0,X-SC,12.27,92.0,-0.48,0.50,69.90,X40N,NTT,FOOTWEAR
3,ALKYLAMINE,-2.26,-18.58,136.48,92.54,112191.0,-18760.0,82203.0,4520.85,-12.74,61.0,H-SC,10.58,142.0,-0.17,0.54,56.10,SR,ATH,CHEMICALS
83,TTKPRESTIG,3.15,-15.38,18.28,0.09,15589.0,-15496.0,85281.0,770.00,97.87,69.0,M-SC,6.51,250.0,-0.99,0.56,51.85,OX40N,NTT,DURABLES
72,SIS,0.39,0.41,20.77,21.26,23156.0,454.0,111486.0,528.00,2662.69,61.0,H-SC,25.28,168.0,0.02,0.73,65.76,OX40N,NTT,MISC

In [23]:
# top 5 RSP
df_tmp = df_portfolio_features.sort_values(by = 'RSP', ascending=False)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
60,QUESS,3.87,22.75,41.66,73.90,54613.0,24300.0,131093.0,424.0,-33.88,75.0,X-SC,26.22,80.0,0.44,0.85,78.71,XY24,NTT,MISC
83,TTKPRESTIG,3.15,-15.38,18.28,0.09,15589.0,-15496.0,85281.0,770.0,97.87,69.0,M-SC,6.51,250.0,-0.99,0.56,51.85,OX40N,NTT,DURABLES
49,JSWINFRA,6.42,19.58,-2.63,16.43,-6975.0,43420.0,265194.0,342.0,2.58,72.0,X-MC,15.07,61.0,-6.23,1.73,50.36,X40N,NTT,REALTY
64,RELAXO,2.41,-47.65,190.95,52.31,145103.0,-69170.0,75990.0,1176.0,-44.25,64.0,X-SC,12.27,92.0,-0.48,0.50,69.90,X40N,NTT,FOOTWEAR
0,5PAISA,1.05,-29.63,60.44,12.90,92929.0,-64742.0,153754.0,593.0,125.96,60.0,H-SC,8.57,170.0,-0.70,1.00,48.37,OX40N,NTT,FINANCE

In [24]:
# Top N allocation
df_tmp = df_portfolio_features.sort_values(by = 'CurrAlloc%', ascending=False)
top_n_values = [10, 25, 50]

sum_df = pd.DataFrame({
    'Top_N': top_n_values,
    'Sum_Alloc%': [df_tmp['CurrAlloc%'].head(n).sum() for n in top_n_values]
})

sum_df

   Top_N  Sum_Alloc%
0     10       19.32
1     25       42.61
2     50       72.62

In [25]:
# market-cap-wise allocation
df_tmp = df_portfolio_features[cols]
df_tmp.groupby(df_tmp['Conviction'].str[-2:])['CurrAlloc%'].sum().sort_values(ascending=False)

Conviction
SC    44.05
LC    29.91
MC    26.01
Name: CurrAlloc%, dtype: float64

In [26]:
# criteria-wise allocation
df_portfolio_features.groupby('Criteria')['CurrAlloc%'].sum().sort_values(ascending=False)

Criteria
XY24     27.99
X40      24.54
X40N     17.34
XR        8.88
OX40N     7.11
AR        6.84
XY25      6.35
SR        0.92
Name: CurrAlloc%, dtype: float64

In [27]:
# conviction-wise allocation
df_portfolio_features.groupby('Conviction')['CurrAlloc%'].sum().sort_values(ascending=False)

Conviction
X-LC    27.97
H-SC    23.27
X-MC    20.93
M-SC    10.13
X-SC    10.09
H-MC     2.69
M-MC     2.01
H-LC     1.14
M-LC     0.80
L-SC     0.56
L-MC     0.38
Name: CurrAlloc%, dtype: float64

In [28]:
# sector-wise stats
df_tmp = df_portfolio_features.groupby('Category')[['CurrAlloc%', 'Current', 'Current P/L', 'FTT Amt']].sum().sort_values(by=['Current', 'Current P/L'], ascending=False)
df_tmp['Current P/L%'] = round(df_tmp['Current P/L'] * 100 / df_tmp['Current'], 2)
df_tmp['FTT%'] = round(df_tmp['FTT Amt'] * 100 / df_tmp['Current'], 2)
cols = ['CurrAlloc%', 'Current P/L%', 'FTT%']
df_tmp[cols].sort_values(by=['CurrAlloc%'], ascending=False)

               CurrAlloc%  Current P/L%    FTT%
Category
FMCG                14.17        -21.58   64.22
FINANCE             11.43         -5.17   50.74
IT                   9.96        -47.31  120.76
MISC                 7.30        -19.60   70.92
AUTO                 6.58         -8.31   48.71
BANKS                5.89         -0.60   47.12
INSURANCE            5.39          0.02   33.70
PAINTS               5.31        -20.89   41.51
PHARMA               5.11          5.68   23.52
ELECTRICAL           4.00        -15.33   56.03
CHEMICALS            2.19        -21.40   93.42
HEALTHCARE           2.09        -11.65   40.79
APPARELS             1.83          4.25   27.92
AC                   1.79        -16.30   47.83
REALTY               1.73         16.37   -2.63
FOOTWEAR             1.72        -67.23  134.28
DURABLES             1.65        -53.40   90.71
BREWERIES            1.55          1.50   18.96
TRAVEL               1.50        -93.46  190.33
CERAMICS             1.42        -40.56   83.26
CABLES               1.30         25.77   54.32
ENGINEERING          1.23        -27.83   86.29
JEWELLERY            1.11        -87.42  152.53
REFINERIES           1.09        -19.90   50.23
CEMENT               1.07        -62.56  184.18
ENTERTAINMENT        0.75        -67.51  167.41
TEXTILES             0.41        -45.33   86.77
HOTELS               0.40        -84.06  148.99

In [29]:
# money to be made criteria-wise
df_portfolio_features.groupby('Criteria')['FTT Amt'].agg(['sum', 'count']).sort_values(by='sum', ascending=False)

                sum  count
Criteria
XY24      3297615.0     21
X40       1911394.0     19
XR        1315738.0     13
AR        1125720.0      9
X40N      1058501.0     13
OX40N      699994.0     10
XY25       461503.0      5
SR         278090.0      2

In [30]:
# money to be made conviction-wise
df_portfolio_features.groupby('Conviction')['FTT Amt'].agg(['sum', 'count']).sort_values(by='sum', ascending=False)

                  sum  count
Conviction
H-SC        3203269.0     24
X-LC        1988675.0     21
X-MC        1504592.0     15
M-SC        1360958.0     14
X-SC        1253147.0      9
H-MC         283914.0      2
L-SC         204513.0      2
M-LC         168784.0      1
M-MC          76289.0      2
H-LC          59367.0      1
L-MC          45047.0      1

In [31]:
# money to be made criteria and conviction-wise
df_portfolio_features.groupby(['Conviction', 'Criteria'])['FTT Amt'].agg(['sum', 'count']).sort_values(by='sum', ascending=False)

                           sum  count
Conviction Criteria
X-LC       X40       1041313.0     10
H-SC       AR         937760.0      5
           XY24       917987.0      6
M-SC       XY24       799468.0      6
H-SC       XR         780407.0      7
X-SC       XY24       742316.0      4
X-MC       X40        660513.0      7
X-LC       X40N       388471.0      6
X-MC       X40N       368767.0      4
X-LC       XY24       356513.0      2
X-SC       X40N       301263.0      3
M-SC       OX40N      298368.0      5
H-SC       OX40N      289025.0      4
           SR         278090.0      2
H-MC       XY24       250481.0      1
X-MC       XY25       244462.0      2
           XY24       230850.0      2
X-SC       X40        209568.0      2
M-SC       XR         191012.0      2
M-LC       XR         168784.0      1
X-LC       XY25       163802.0      2
L-SC       OX40N      112601.0      1
           XR          91912.0      1
M-SC       AR          72110.0      1
H-LC       AR          59367.0      1
M-MC       XY25        53239.0      1
L-MC       XR          45047.0      1
X-LC       XR          38576.0      1
H-MC       AR          33433.0      1
M-MC       AR          23050.0      1

In [32]:
# notebook execution time

end_time = time.time()
execution_time = round(end_time - start_time, 0)
print(f"Notebook execution time: {execution_time} seconds")

Notebook execution time: 36.0 seconds