<a href="https://colab.research.google.com/github/ankit-rathi/Quantvesting_v2/blob/main/myStocks_Portfolio_Analysis.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
'''
!pip install pandas==2.2.2 -qq
!pip install pyxirr -qq
!pip install ta -qq
!pip install yfinance==0.2.59 -qq
'''

'\n!pip install pandas==2.2.2 -qq\n!pip install pyxirr -qq\n!pip install ta -qq\n!pip install yfinance==0.2.59 -qq\n'

In [2]:
# import libraries

import numpy as np
import pandas as pd
import datetime
import warnings
warnings.filterwarnings('ignore')
import yfinance as yfin
import ta
import matplotlib.pyplot as plt
import requests

In [3]:
# notebook start time
import time
import datetime
import pytz

start_time = time.time()

# function to print date timestamp
def print_date_time():
  tz_NY = pytz.timezone('Asia/Kolkata')
  datetime_NY = datetime.datetime.now(tz_NY)
  print("Run date time (IST):", datetime_NY.strftime("%Y-%m-%d %H:%M:%S"))

In [4]:
# function to get booked and reserved amount
def get_amt():
  # fetch the JSON data from the URL
  url = "https://raw.githubusercontent.com/ankit-rathi/Tradevesting_v1/main/data/myPortfolioAmts.json"
  response = requests.get(url)
  pf_amts = response.json()  # parse the JSON data

  # extract values from the JSON
  py_booked_amt_dm = pf_amts["py_booked_amt_dm"]
  py_booked_amt_sv = pf_amts["py_booked_amt_sv"]
  cy_booked_amt_dm = pf_amts["cy_booked_amt_dm"]
  cy_booked_amt_sv = pf_amts["cy_booked_amt_sv"]
  reserve_amt_dm = pf_amts["reserve_amt_dm"]
  reserve_amt_sv = pf_amts["reserve_amt_sv"]

  # perform calculations
  py_booked_amt = py_booked_amt_dm + py_booked_amt_sv
  cy_booked_amt = cy_booked_amt_dm + cy_booked_amt_sv
  reserve_amt = reserve_amt_dm + reserve_amt_sv
  total_booked_amt = py_booked_amt + cy_booked_amt

  return total_booked_amt, reserve_amt, cy_booked_amt, py_booked_amt

gen_output = 0

In [5]:
# function to format the amount
def format_amt(number):
    abs_number = abs(number)

    if abs_number >= 1_00_00_000:  # Crores
        formatted_amt = f"{number / 1_00_00_000:.2f} C"
    elif abs_number >= 1_00_000:  # Lakhs
        formatted_amt = f"{number / 1_00_000:.2f} L"
    elif abs_number >= 1_000:  # Thousands
        formatted_amt = f"{number / 1_000:.2f} K"
    else:
        formatted_amt = f"{number:.2f}"

    return formatted_amt

# function to set start and end date
def get_start_end_date():
  start_date = (datetime.date.today() + datetime.timedelta(days=-365)).strftime('%Y-%m-%d')
  end_date = (datetime.date.today() + datetime.timedelta(days=1)).strftime('%Y-%m-%d')
  return start_date, end_date

# function to fetch my portfolio csv
def get_mypfs_df():
  mypfs_df = pd.read_csv('https://raw.githubusercontent.com/ankit-rathi/Tradevesting_v1/main/data/myPortfolioStocks.csv')
  return mypfs_df

# function to fetch my prospects csv
def get_mypps_df():
  mypps_df = pd.read_csv('https://raw.githubusercontent.com/ankit-rathi/Tradevesting_v1/main/data/myProspectsScrips.csv')
  return mypps_df

# function to fetch screener data
def get_myscreen_df():
  myscreen_df = pd.read_csv('https://raw.githubusercontent.com/ankit-rathi/Tradevesting_v1/main/data/myScreenerDB.csv')
  return myscreen_df

# function to fetch momentum data
def get_myinvmt_df():
  myinvmt_df = pd.read_csv('https://raw.githubusercontent.com/ankit-rathi/Tradevesting_v1/main/data/myInvestments.csv')
  return myinvmt_df

# function to get the stock ids
def get_stock_ids(df_pf):
  stock_n100 = df_pf['Symbol'].unique()

  exclude = ['CADILAHC','MMTC', 'MASFIN']

  stock_ids = df_pf[~df_pf['Symbol'].isin(exclude) ]['Symbol'].unique()

  #mypf = mypf[mypf.Forecast.notnull()]
  #stock_ids = mypf['Symbol'].unique()

  #stock_ids.sort()
  return stock_ids

# get features from screener data
def get_screener_features():
  myscreen_df = get_myscreen_df()
  cols = ['Symbol', 'EPS', 'MedPE', 'ROCE%', 'ROE%', 'CapType']
  return myscreen_df[cols]

# get relative strength
def get_relative_strength(stock_list):

    # Dictionary to store stock tickers and their corresponding percentage price change
    stock_changes = {}

    # Loop through each stock and fetch its price data
    for stock in stock_list:
        try:
            # Download the stock data for the given date range
            stock_data = yfin.Ticker(stock + '.NS').history(period='1mo', interval='1d')[map(str.title, ['open', 'close', 'low', 'high', 'volume'])]

            # Calculate the percentage change for the stock
            if len(stock_data) > 0:
                start_price = stock_data['Close'].iloc[0]
                end_price = stock_data['Close'].iloc[-1]
                percent_change = round(((end_price - start_price) / start_price) * 100, 2)
                stock_changes[stock] = percent_change
            else:
                stock_changes[stock] = np.nan  # If no data is available, set to NaN

        except Exception as e:
            print(f"Error fetching data for {stock}: {e}")
            stock_changes[stock] = np.nan

    # Create a DataFrame with stock tickers and their percentage changes
    df = pd.DataFrame(list(stock_changes.items()), columns=['Symbol', 'Percent_Change'])

    # Drop any stocks with missing data (NaN values)
    df = df.dropna()

    # Calculate the percentile rank based on percentage change
    df['RSP'] = round(df['Percent_Change'].rank(pct=True) * 100, 2)
    cols = ['Symbol', 'RSP']
    df = df[cols]
    # Sort by percentile rank (optional)
    df = df.sort_values(by='RSP', ascending=False).reset_index(drop=True)

    return df

In [6]:
# function to get stock technicals
def stock_prec_dev(stock_symbol):
    #stock_symbol = 'ULTRACEMCO.NS'
    short_window = 20
    mid_window = 50
    long_window = 200
    moving_avg = 'SMA'

    start = datetime.datetime(*map(int, start_date.split('-')))
    end = datetime.datetime(*map(int, end_date.split('-')))

    stock_df = yfin.Ticker(stock_symbol + '.NS').history(period='max', interval='1d')[map(str.title, ['open', 'close', 'low', 'high', 'volume'])]

    stock_df['Max'] = round(max(stock_df['Close']),2)
    stock_df = stock_df[(stock_df.index <= end_date) & (stock_df.index >= start_date)]
    stock_df['200_SMA'] = round(stock_df['Close'].rolling(window = 200, min_periods = 1).mean(),0)
    stock_df['Dev%_200'] = round((stock_df['Close'] - stock_df['200_SMA'])*100/stock_df['200_SMA'],2)
    stock_df.dropna(axis = 0, inplace = True) # remove any null rows

    stock_df['20_SMA'] = stock_df['Close'].rolling(window=20).mean()
    stock_df['50_SMA'] = stock_df['Close'].rolling(window=50).mean()
    stock_df['Symbol'] = stock_symbol

    stock_df['Close'] = round(stock_df['Close'],2)
    stock_df['Min'] = round(min(stock_df['Close']),2)
    stock_df['RSI_14'] = ta.momentum.RSIIndicator(close=stock_df['Close'], window=14).rsi()
    stock_df['RSI_14'] = round(stock_df['RSI_14'],0)
    stock_df['Prev_Close'] = stock_df['Close'].shift(1)
    stock_df.drop(['Open', 'Low', 'High', 'Volume'], axis=1, inplace=True)
    stock_df = stock_df.tail(1)

    max_SMA = max(stock_df['20_SMA'].item(), stock_df['50_SMA'].item(), stock_df['200_SMA'].item())
    min_SMA = min(stock_df['20_SMA'].item(), stock_df['50_SMA'].item(), stock_df['200_SMA'].item())
    ABS_Spread = max_SMA - min_SMA
    stock_df['Spread%'] = round((ABS_Spread / stock_df['200_SMA'].item()) * 100,2)

    return stock_df

# function to compute stock attributes
def get_common_features(stock_ids, df_mypf):

  df_prec_dev = pd.DataFrame()
  df_tmp = get_screener_features()
  df_rs = get_relative_strength(stock_ids)

  for stock_id in stock_ids:
      tmp = stock_prec_dev(stock_id)
      tmp = tmp.reset_index()
      df_prec_dev = pd.concat([df_prec_dev, tmp], ignore_index = True)
  df_prec_dev = pd.merge(df_prec_dev, df_mypf, on= 'Symbol')
  df_prec_dev = pd.merge(df_prec_dev, df_tmp, on= 'Symbol', how='left')
  df_prec_dev = pd.merge(df_prec_dev, df_rs, on= 'Symbol', how='left')
  #print(df_prec_dev.columns)
  df_prec_dev['Curr_PE'] = round(df_prec_dev['Close']/df_prec_dev['EPS'],1)
  df_prec_dev['Dev%_PE'] = round((df_prec_dev['Curr_PE'] - df_prec_dev['MedPE'])*100/df_prec_dev['MedPE'],2)
  df_prec_dev['Conviction'] = df_prec_dev['Conviction'] + '-' + df_prec_dev['CapType']
  return df_prec_dev

# function to arrange stock features
def arrange_features(df_stocks, common_cols, diff_cols):
  df_stocks_common = df_stocks[common_cols].drop_duplicates()
  df_stocks_diff = df_stocks[diff_cols]
  df_stocks_diff['Investment'] = df_stocks_diff['AvgCost'] * df_stocks_diff['Shares']
  df_stocks_diff = df_stocks_diff.groupby(['Symbol'])[['Shares', 'Investment']].aggregate(['sum']).reset_index()
  df_stocks_diff.columns = ['Symbol', 'Shares', 'Investment']
  df_stocks_diff['AvgCost'] = round(df_stocks_diff['Investment']/df_stocks_diff['Shares'],2)
  df_stocks = pd.merge(df_stocks_diff, df_stocks_common, on='Symbol')
  return df_stocks

# plot fact distribution across dimension
def plot_pie_chart(df, dimension, fact):
  # grouping the data by category and calculating the sum of fact for each type
  grouped_data = df.groupby(dimension)[fact].sum()

  # sorting the grouped data in descending order
  grouped_data = grouped_data.sort_values(ascending=False)

  # creating a pie chart
  grouped_data.plot.pie(autopct='%1.1f%%', startangle=90, figsize=(6, 6))

  # adding a title and displaying the plot
  plt.title(f'{dimension} {fact} Distribution')
  plt.ylabel('')  # To hide the y-label
  plt.show()

In [7]:
# function to get portfolio features

def get_portfolio_features(df_common_features):

  print_date_time()
  print('-------------------')

  #df_common_features["Target"] = df_common_features["Target"].fillna(df_common_features["Max"])
  df_common_features['NTT'] = np.where(df_common_features['Strategy']== 'NTT', df_common_features["Target"], df_common_features['Max'])
  df_common_features['LTT'] = np.where(df_common_features['Strategy']== 'BTT', df_common_features["Target"], df_common_features['Max'])
  df_common_features['BOL'] = df_common_features['Min']

  tmp_df = df_common_features[df_common_features['Symbol'].isin(mypf_df[mypf_df['InPortfolio'] != 'NA'].Symbol.values)]
  print('qualified stocks: '+str(len(tmp_df['Symbol'].unique())))
  tmp_df1 = tmp_df[tmp_df['LatestQtr'] == 1]
  print('with latest results: '+str(len(tmp_df1['Symbol'].unique())))
  tmp_df1 = tmp_df1[tmp_df1['StarStock'] == 1]
  print('still star stocks: '+str(len(tmp_df1['Symbol'].unique())))
  tmp_df['Investment'] = tmp_df['AvgCost'] * tmp_df['Shares']
  tmp_df['Current'] = round(tmp_df['Close'] * tmp_df['Shares'],0)
  tmp_df['Previous'] = tmp_df['Prev_Close'] * tmp_df['Shares']
  tmp_df['EstimatedST'] = tmp_df['NTT'] * tmp_df['Shares']
  tmp_df['EstimatedLT'] = tmp_df['LTT'] * tmp_df['Shares']
  tmp_df['Current P/L'] = round((tmp_df['Current'] - tmp_df['Investment']),0)
  tmp_df['Today P/L%'] = round((tmp_df['Current'] - tmp_df['Previous'])*100/tmp_df['Previous'],2)
  tmp_df['Current P/L%'] = round((tmp_df['Current'] - tmp_df['Investment'])*100/tmp_df['Investment'],2)
  tmp_df['EstimatedST P/L%'] = round((tmp_df['EstimatedST'] - tmp_df['Investment'])*100/tmp_df['Investment'],2)
  tmp_df['EstimatedLT P/L%'] = round((tmp_df['EstimatedLT'] - tmp_df['Investment'])*100/tmp_df['Investment'],2)
  tmp_df['NTT%'] = round((tmp_df['NTT'] - tmp_df['Close'])*100/tmp_df['Close'],2)
  tmp_df['LTT%'] = round((tmp_df['LTT'] - tmp_df['Close'])*100/tmp_df['Close'],2)
  tmp_df['Gained%'] = round((tmp_df['Close'] - tmp_df['BOL'])*100/tmp_df['BOL'],2)
  investment = round(sum(tmp_df['AvgCost']*tmp_df['Shares']),0)
  current = round(sum(tmp_df['Close']*tmp_df['Shares']),0)
  tmp_df['InitAlloc%'] = round(tmp_df['Investment']*100/investment,2)
  tmp_df['CurrAlloc%'] = round(tmp_df['Current']*100/current,2)
  tmp_df['FTT'] = tmp_df['LTT']
  tmp_df.loc[tmp_df['Strategy'] == 'NTT', 'FTT'] = tmp_df['NTT']
  tmp_df['FTT%'] = tmp_df['LTT%']
  tmp_df.loc[tmp_df['Strategy'] == 'NTT', 'FTT%'] = tmp_df['NTT%']
  tmp_df['FTT Amt'] = round(tmp_df['FTT%'] * tmp_df['Current']/100,0)
  tmp_df['OTT%'] = round((tmp_df['FTT'] - tmp_df['AvgCost'])*100/tmp_df['AvgCost'],2)
  tmp_df['RRR Ind'] = round(tmp_df['Current P/L']/tmp_df['FTT Amt'],2)
  tmp_df['Risk Ind'] = round(tmp_df['Current P/L%']*tmp_df['CurrAlloc%'],0)

  return tmp_df

# function to print portfolio features
def print_portfolio_stats(df_portfolio_features, myinvmt_df):
  from pyxirr import xirr

  total_booked_amt, reserve_amt, cy_booked_amt, py_booked_amt = get_amt()

  dates = myinvmt_df['Date'].values
  dates = np.append(dates, datetime.date.today().strftime('%d-%b-%y'))
  investment = myinvmt_df['Investment'].values
  dates= pd.to_datetime(dates)

  current = round(sum(df_portfolio_features['Close']*df_portfolio_features['Shares']),0) + reserve_amt
  investment_xirr = np.append(investment, current)
  cagr = round(xirr(pd.DataFrame({"dates": dates, "amounts": investment_xirr}))*100,2)

  investment = -sum(investment)
  invested = round(sum(df_portfolio_features['AvgCost']*df_portfolio_features['Shares']),0) + reserve_amt
  previous = round(sum(df_portfolio_features['Prev_Close']*df_portfolio_features['Shares']),0) + reserve_amt
  cy_invested = investment + py_booked_amt

  today_pnl_amount = current-previous
  today_pnl_percentage = round((current-previous)*100/previous,2)

  curr_pnl_amount = current-invested
  curr_pnl_percentage = round((curr_pnl_amount)*100/(cy_invested),2)

  cy_pnl_amount = cy_booked_amt + curr_pnl_amount
  cy_pnl_percentage = round((cy_pnl_amount)*100/cy_invested,2)

  overall_pnl_amount = total_booked_amt + curr_pnl_amount
  overall_pnl_percentage = round((overall_pnl_amount)*100/investment,2)

  estimate_st = round(sum(df_portfolio_features['FTT']*df_portfolio_features['Shares']),0)  + reserve_amt
  est_st_pnl_amount = estimate_st-current
  est_st_pnl_percentage = round((est_st_pnl_amount)*100/current,2)

  estimate_lt = round(sum(df_portfolio_features['LTT']*df_portfolio_features['Shares']),0)  + reserve_amt
  est_lt_pnl_amount = estimate_lt-current
  est_lt_pnl_percentage = round((est_lt_pnl_amount)*100/current,2)

  total_profit = round(sum(df_portfolio_features[df_portfolio_features['Current P/L%'] > 0]['Current']) - sum(df_portfolio_features[df_portfolio_features['Current P/L%'] > 0]['Investment']),0)
  total_loss = round(sum(df_portfolio_features[df_portfolio_features['Current P/L%'] < 0]['Current']) - sum(df_portfolio_features[df_portfolio_features['Current P/L%'] < 0]['Investment']),0)

  cy_booked_percentage = round((cy_booked_amt)*100/current,2)
  py_booked_percentage = round((py_booked_amt)*100/investment,2)
  total_booked_percentage = round((total_booked_amt)*100/investment,2)

  print('-------------------')
  print('Initial Investment: ', format_amt(investment))
  print('CY Investment: ', format_amt(cy_invested))
  print('Reserve: ', format_amt(reserve_amt))
  print('Current: ',  format_amt(current))
  print('-------------------')
  print('Today PnL: '+ '{} ({}%)'.format(format_amt(today_pnl_amount), today_pnl_percentage))
  print('Current PnL: '+ '{} ({}%)'.format(format_amt(curr_pnl_amount), curr_pnl_percentage))
  print('CY Booked + Current PnL: '+ '{} ({}%)'.format(format_amt(cy_pnl_amount), cy_pnl_percentage))
  print('-------------------')
  print('Total profit: ', format_amt(total_profit))
  print('Total loss: ', format_amt(total_loss))
  print('-------------------')
  print('Total Booked + Current PnL: '+ '{} ({}%)'.format(format_amt(overall_pnl_amount), overall_pnl_percentage))
  print('Total Booked PnL: '+ '{} ({}%)'.format(format_amt(total_booked_amt), total_booked_percentage))
  print('Curr Year Booked PnL: '+ '{} ({}%)'.format(format_amt(cy_booked_amt), cy_booked_percentage))
  print('Prev Year Booked PnL: '+ '{} ({}%)'.format(format_amt(py_booked_amt), py_booked_percentage))
  print('===================')
  print('Est FTT: ',  format_amt(estimate_st))
  print('Est FTT PnL: '+ '{} ({}%)'.format(format_amt(est_st_pnl_amount), est_st_pnl_percentage))

  print('===================')
  print('Deployed: ', format_amt(investment))

  print('Current: ', format_amt(current))

  print('CAGR/XIRR %: '+'{}%'.format(cagr))

In [8]:
# get start and end date
start_date, end_date = get_start_end_date()

# get portfolio and prospects data
mypfs_df = get_mypfs_df()
mypps_df = get_mypps_df()
myinvmt_df = get_myinvmt_df()

# merge above datasets
mypf_df = pd.merge(mypfs_df, mypps_df, on="Symbol")

# seggregate dm and sv portfolio
dm_pf = mypf_df[mypf_df['InPortfolio'] == 'DM']
sv_pf = mypf_df[mypf_df['InPortfolio'] == 'SV']

# build portfolio stock dataframe
dm_stocks = get_stock_ids(dm_pf)
sv_stocks = get_stock_ids(sv_pf)
df_stocks = pd.concat([dm_pf,sv_pf], ignore_index = True)

# arrange common and diff stock features
common_cols = ['Symbol', 'Target', 'Criteria', 'Strategy', 'CumlRnk', 'LatestQtr', 'StarStock', 'Conviction', 'Category', 'InFolio', 'XIRR', 'MBQ']
diff_cols = ['Symbol', 'AvgCost', 'Shares']
df_stocks = arrange_features(df_stocks, common_cols, diff_cols)

# get common features
stock_ids = df_stocks['Symbol'].values
df_common_features = get_common_features(stock_ids, df_stocks)

df_common_features.reset_index(drop=True, inplace=True)
df_common_features.drop(['Date'], axis=1, inplace=True)
# get and print portfolio features
df_portfolio_features = get_portfolio_features(df_common_features)

print_portfolio_stats(df_portfolio_features, myinvmt_df)

df = df_portfolio_features
#plot_pie_chart(df, 'CapType', 'Current')
list_ox40n = list(df[df['MBQ'].str.contains('OX40N', na=False)]['Symbol'].values)

Run date time (IST): 2026-04-08 10:07:18
-------------------
qualified stocks: 86
with latest results: 26
still star stocks: 16
-------------------
Initial Investment:  1.36 C
CY Investment:  1.62 C
Reserve:  1.61 K
Current:  1.36 C
-------------------
Today PnL: 4.02 L (3.05%)
Current PnL: -41.49 L (-25.53%)
CY Booked + Current PnL: -25.60 L (-15.75%)
-------------------
Total profit:  86.85 K
Total loss:  -42.35 L
-------------------
Total Booked + Current PnL: 1.38 L (1.02%)
Total Booked PnL: 42.87 L (31.64%)
Curr Year Booked PnL: 15.89 L (11.72%)
Prev Year Booked PnL: 26.98 L (19.91%)
===================
Est FTT:  2.48 C
Est FTT PnL: 1.12 C (82.75%)
===================
Deployed:  1.36 C
Current:  1.36 C
CAGR/XIRR %: 0.05%

In [9]:
# top 5 near their targets
cols = ['Symbol', 'Today P/L%', 'Current P/L%', 'FTT%', 'OTT%', 'FTT Amt', 'Current P/L', 'Current', 'FTT', 'Dev%_PE', 'RSI_14','Conviction', 'Spread%',  'CumlRnk', 'RRR Ind', 'CurrAlloc%', 'Gained%', 'Criteria', 'Strategy', 'Category']
df_tmp = df_portfolio_features[~df_portfolio_features['Symbol'].isin(['ENRIN','BLUSPRING','DIGITIDE'])]
df_tmp = df_tmp.sort_values(by = 'FTT Amt', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
50,MASFIN,4.94,-3.83,26.41,21.57,24886.0,-3750.0,94230.0,397.04,-16.89,56.0,H-SC,4.82,167.0,-0.15,0.69,23.98,XR,ATH,FINANCE
77,TTKPRESTIG,2.03,-37.58,60.37,0.09,37973.0,-37877.0,62900.0,770.00,46.00,49.0,M-SC,22.15,250.0,-1.00,0.46,12.00,OX40N,NTT,DURABLES
67,SONACOMS,5.10,-6.34,48.51,39.09,45961.0,-6414.0,94745.0,804.02,-25.74,61.0,M-MC,7.72,193.0,-0.14,0.70,34.03,AR,ATH,AUTO
37,ICICIGI,2.25,-6.48,27.62,19.34,51686.0,-12977.0,187132.0,2252.93,-21.30,45.0,X-MC,6.88,66.0,-0.25,1.38,4.52,X40,ATH,INSURANCE
2,ABBOTINDIA,1.97,-12.21,34.49,18.07,54156.0,-21835.0,157020.0,35195.00,-25.27,47.0,X-MC,11.04,58.0,-0.40,1.16,2.69,X40,ATH,PHARMA

In [10]:
# top 5 today
df_tmp = df_portfolio_features.sort_values(by = 'Today P/L%', ascending=False)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
25,EASEMYTRIP,12.50,-58.28,249.21,45.70,183842.0,-103045.0,73770.0,26.4,-23.41,58.0,M-SC,14.79,204.0,-0.56,0.54,29.23,XY24,NTT,TRAVEL
19,COFFEEDAY,7.53,-57.27,216.58,35.27,105080.0,-65031.0,48518.0,80.0,-67.81,49.0,L-SC,33.00,266.0,-0.62,0.36,19.65,XR,NTT,HOTELS
75,TMPV,7.29,-24.61,81.16,36.58,217730.0,-87569.0,268272.0,600.0,-84.72,53.0,X-LC,12.46,4.0,-0.40,1.98,11.82,XY24,NTT,AUTO
11,BANDHANBNK,7.12,-23.15,150.39,92.42,321932.0,-64494.0,214065.0,400.0,83.91,51.0,H-SC,2.47,174.0,-0.20,1.58,17.92,XY24,NTT,BANKS
29,GREENPANEL,6.73,-46.83,169.21,43.14,164711.0,-85737.0,97341.0,537.0,118.35,55.0,M-SC,25.66,225.0,-0.52,0.72,16.93,XY24,NTT,MISC

In [11]:
# bottom 5 today
df_tmp = df_portfolio_features.sort_values(by = 'Today P/L%', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
24,DMART,-0.94,6.35,21.87,29.60,58052.0,15840.0,265440.0,5391.45,-10.32,69.0,X-LC,5.34,14.0,0.27,1.96,21.33,X40N,ATH,FMCG
84,WIPRO,-0.49,-16.44,106.17,72.27,150321.0,-27863.0,141585.0,420.00,-24.55,56.0,M-LC,17.75,98.0,-0.19,1.04,8.63,XR,NTT,IT
43,INFY,-0.03,-8.85,47.27,34.24,134817.0,-27681.0,285207.0,1972.00,-28.16,56.0,X-LC,14.52,3.0,-0.21,2.10,9.68,X40,NTT,IT
33,HCLTECH,0.03,-6.42,32.33,23.83,73193.0,-15530.0,226394.0,1908.19,-1.57,59.0,X-LC,10.59,8.0,-0.21,1.67,9.93,X40,ATH,IT
73,TCS,0.60,-24.99,68.75,26.57,238892.0,-115793.0,347480.0,4311.59,-36.41,55.0,X-LC,18.48,2.0,-0.48,2.56,8.45,X40,ATH,IT

In [12]:
# top 5 to exit based on CumlRnk
df_tmp = df_portfolio_features[~df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])]
df_tmp = df_tmp[(df_tmp['Current P/L%'] > -1) & (df_tmp['Current P/L%'] < 1)].sort_values(by = 'CumlRnk', ascending=False)
df_tmp[cols].head()

Empty DataFrame
Columns: [Symbol, Today P/L%, Current P/L%, FTT%, OTT%, FTT Amt, Current P/L, Current, FTT, Dev%_PE, RSI_14, Conviction, Spread%, CumlRnk, RRR Ind, CurrAlloc%, Gained%, Criteria, Strategy, Category]
Index: []

In [13]:
# OX40N stocks to exit
df_tmp = df_portfolio_features[(df_portfolio_features['Symbol'].isin(list_ox40n))].sort_values(by = 'Current P/L%', ascending=False)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
26,FINCABLES,3.45,6.19,95.78,107.91,150173.0,9146.0,156790.0,1641.55,-4.62,51.0,M-SC,3.09,220.0,0.06,1.16,17.96,OX40N,ATH,CABLES
66,SIS,1.35,-32.91,80.76,21.26,60155.0,-36546.0,74486.0,528.00,1745.60,52.0,H-SC,14.76,168.0,-0.61,0.55,10.75,OX40N,NTT,MISC
18,CERA,4.55,-34.26,88.45,23.89,102283.0,-60264.0,115639.0,9475.00,-36.52,60.0,H-SC,18.57,153.0,-0.59,0.85,11.13,OX40N,NTT,CERAMICS
72,TATAELXSI,1.37,-36.34,107.38,32.03,90126.0,-47903.0,83932.0,9161.00,-20.36,52.0,H-SC,21.35,158.0,-0.53,0.62,11.09,OX40N,NTT,IT
77,TTKPRESTIG,2.03,-37.58,60.37,0.09,37973.0,-37877.0,62900.0,770.00,46.00,49.0,M-SC,22.15,250.0,-1.00,0.46,12.00,OX40N,NTT,DURABLES

In [14]:
# top 5 to book for rotation
df_tmp = df_portfolio_features[(df_portfolio_features['Current P/L%'] > 20) ].sort_values(by = 'CumlRnk', ascending=False)
df_tmp[cols].head()

Empty DataFrame
Columns: [Symbol, Today P/L%, Current P/L%, FTT%, OTT%, FTT Amt, Current P/L, Current, FTT, Dev%_PE, RSI_14, Conviction, Spread%, CumlRnk, RRR Ind, CurrAlloc%, Gained%, Criteria, Strategy, Category]
Index: []

In [15]:
# top 5 to monitor for exit
df_tmp = df_portfolio_features[~df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])]
df_tmp = df_tmp[(df_tmp['Current P/L%'] > 0) ].sort_values(by = 'Dev%_PE', ascending=False)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
26,FINCABLES,3.45,6.19,95.78,107.91,150173.0,9146.0,156790.0,1641.55,-4.62,51.0,M-SC,3.09,220.0,0.06,1.16,17.96,OX40N,ATH,CABLES
1,ABB,2.46,17.84,23.52,45.57,72513.0,46685.0,308304.0,7934.00,-24.23,61.0,H-MC,14.21,125.0,0.64,2.27,36.91,AR,NTT,ELECTRICAL

In [16]:
# top 5 to book for rotation from weak conviction
df_tmp = df_portfolio_features[~df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])]
df_tmp = df_tmp[~df_tmp['Criteria'].isin(['XY25','XY24','X40', 'X40N'])].sort_values(by = 'RRR Ind', ascending=False)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
1,ABB,2.46,17.84,23.52,45.57,72513.0,46685.0,308304.0,7934.00,-24.23,61.0,H-MC,14.21,125.0,0.64,2.27,36.91,AR,NTT,ELECTRICAL
26,FINCABLES,3.45,6.19,95.78,107.91,150173.0,9146.0,156790.0,1641.55,-4.62,51.0,M-SC,3.09,220.0,0.06,1.16,17.96,OX40N,ATH,CABLES
40,INDIAMART,2.26,-9.76,129.08,106.72,143666.0,-12036.0,111300.0,4810.62,-59.38,53.0,H-SC,12.83,140.0,-0.08,0.82,7.97,AR,ATH,MISC
67,SONACOMS,5.10,-6.34,48.51,39.09,45961.0,-6414.0,94745.0,804.02,-25.74,61.0,M-MC,7.72,193.0,-0.14,0.70,34.03,AR,ATH,AUTO
50,MASFIN,4.94,-3.83,26.41,21.57,24886.0,-3750.0,94230.0,397.04,-16.89,56.0,H-SC,4.82,167.0,-0.15,0.69,23.98,XR,ATH,FINANCE

In [17]:
# top 5 to accumulate based on lowest RSI_14
df_tmp = df_portfolio_features[df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])].sort_values(by = 'RSI_14', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
21,DABUR,2.70,-16.82,72.76,43.70,150135.0,-41725.0,206343.0,735.00,-24.46,38.0,X-MC,12.93,70.0,-0.28,1.52,3.65,XY24,BTT,FMCG
38,ICICIPRULI,3.94,-11.14,47.11,30.73,82472.0,-21943.0,175062.0,790.00,-35.01,38.0,X-MC,10.84,78.0,-0.27,1.29,6.67,X40,ATH,INSURANCE
20,COLPAL,1.56,-28.65,98.32,41.51,184763.0,-75445.0,187920.0,3726.84,-13.70,40.0,X-MC,12.22,62.0,-0.41,1.39,5.06,XY25,ATH,FMCG
82,VOLTAS,3.52,-1.18,46.93,45.20,88923.0,-2262.0,189480.0,1856.00,13.14,40.0,X-MC,5.01,79.0,-0.03,1.40,5.54,XY25,NTT,AC
53,PGHH,2.00,-25.80,77.91,32.01,123434.0,-55088.0,158432.0,17616.87,-49.81,42.0,X-MC,20.20,57.0,-0.45,1.17,8.36,X40,ATH,FMCG

In [18]:
# top 5 to accumulate based on Spread and CumlRnk
df_tmp = df_portfolio_features[df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])]
df_tmp = df_tmp[(df_tmp['CumlRnk'] < 100)].sort_values(by = 'Spread%', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
65,SIEMENS,3.29,-14.65,47.06,25.51,74745.0,-27265.0,158830.0,4671.50,33.36,53.0,H-LC,0.98,51.0,-0.36,1.17,16.97,AR,ATH,ELECTRICAL
59,RELIANCE,3.02,-13.73,45.24,25.30,78435.0,-27587.0,173376.0,1952.00,-15.80,43.0,X-LC,4.45,21.0,-0.35,1.28,14.14,XY25,BTT,REFINERIES
78,UNITDSPR,2.06,-7.18,30.10,20.77,65419.0,-16805.0,217339.0,1644.00,-17.72,44.0,X-MC,4.54,64.0,-0.26,1.60,3.68,X40N,NTT,BREWERIES
82,VOLTAS,3.52,-1.18,46.93,45.20,88923.0,-2262.0,189480.0,1856.00,13.14,40.0,X-MC,5.01,79.0,-0.03,1.40,5.54,XY25,NTT,AC
24,DMART,-0.94,6.35,21.87,29.60,58052.0,15840.0,265440.0,5391.45,-10.32,69.0,X-LC,5.34,14.0,0.27,1.96,21.33,X40N,ATH,FMCG

In [19]:
# top 5 to accumulate based on lowest Gained%
df_tmp = df_portfolio_features[df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])].sort_values(by = 'Gained%', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
2,ABBOTINDIA,1.97,-12.21,34.49,18.07,54156.0,-21835.0,157020.0,35195.00,-25.27,47.0,X-MC,11.04,58.0,-0.40,1.16,2.69,X40,ATH,PHARMA
21,DABUR,2.70,-16.82,72.76,43.70,150135.0,-41725.0,206343.0,735.00,-24.46,38.0,X-MC,12.93,70.0,-0.28,1.52,3.65,XY24,BTT,FMCG
78,UNITDSPR,2.06,-7.18,30.10,20.77,65419.0,-16805.0,217339.0,1644.00,-17.72,44.0,X-MC,4.54,64.0,-0.26,1.60,3.68,X40N,NTT,BREWERIES
37,ICICIGI,2.25,-6.48,27.62,19.34,51686.0,-12977.0,187132.0,2252.93,-21.30,45.0,X-MC,6.88,66.0,-0.25,1.38,4.52,X40,ATH,INSURANCE
45,ITC,1.26,-20.40,49.57,19.06,134221.0,-69395.0,270771.0,452.00,-56.33,49.0,X-LC,19.78,1.0,-0.52,2.00,5.04,X40,NTT,FMCG

In [20]:
# top 5 to accumulate based on lowest CurrAlloc%
df_tmp = df_portfolio_features[df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])].sort_values(by = 'CurrAlloc%', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
58,RELAXO,3.34,-63.88,321.69,52.31,168659.0,-92731.0,52429.0,1176.00,-61.57,44.0,X-SC,32.71,92.0,-0.55,0.39,17.23,X40N,NTT,FOOTWEAR
12,BATAINDIA,4.22,-54.99,200.39,35.20,116052.0,-70757.0,57913.0,2096.00,-24.04,50.0,X-SC,34.39,91.0,-0.61,0.43,14.86,X40,NTT,FOOTWEAR
54,QUESS,3.54,-22.56,124.55,73.90,103007.0,-24090.0,82703.0,424.00,-58.13,55.0,X-SC,22.42,80.0,-0.23,0.61,11.25,XY24,NTT,MISC
36,HONAUT,2.81,-27.45,108.57,51.31,151889.0,-52938.0,139900.0,58357.33,-39.64,44.0,X-SC,18.65,90.0,-0.35,1.03,6.29,X40N,ATH,ELECTRICAL
2,ABBOTINDIA,1.97,-12.21,34.49,18.07,54156.0,-21835.0,157020.0,35195.00,-25.27,47.0,X-MC,11.04,58.0,-0.40,1.16,2.69,X40,ATH,PHARMA

In [21]:
# top 5 to accumulate based on CumlRnk
df_tmp = df_portfolio_features.sort_values(by = 'CumlRnk', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
45,ITC,1.26,-20.40,49.57,19.06,134221.0,-69395.0,270771.0,452.00,-56.33,49.0,X-LC,19.78,1.0,-0.52,2.00,5.04,X40,NTT,FMCG
73,TCS,0.60,-24.99,68.75,26.57,238892.0,-115793.0,347480.0,4311.59,-36.41,55.0,X-LC,18.48,2.0,-0.48,2.56,8.45,X40,ATH,IT
43,INFY,-0.03,-8.85,47.27,34.24,134817.0,-27681.0,285207.0,1972.00,-28.16,56.0,X-LC,14.52,3.0,-0.21,2.10,9.68,X40,NTT,IT
75,TMPV,7.29,-24.61,81.16,36.58,217730.0,-87569.0,268272.0,600.00,-84.72,53.0,X-LC,12.46,4.0,-0.40,1.98,11.82,XY24,NTT,AUTO
33,HCLTECH,0.03,-6.42,32.33,23.83,73193.0,-15530.0,226394.0,1908.19,-1.57,59.0,X-LC,10.59,8.0,-0.21,1.67,9.93,X40,ATH,IT

In [22]:
# top 5 for average up
df_tmp = df_portfolio_features[(df_portfolio_features['Dev%_200'] > 5)].sort_values(by = 'CurrAlloc%', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
67,SONACOMS,5.10,-6.34,48.51,39.09,45961.0,-6414.0,94745.0,804.02,-25.74,61.0,M-MC,7.72,193.0,-0.14,0.70,34.03,AR,ATH,AUTO
24,DMART,-0.94,6.35,21.87,29.60,58052.0,15840.0,265440.0,5391.45,-10.32,69.0,X-LC,5.34,14.0,0.27,1.96,21.33,X40N,ATH,FMCG
1,ABB,2.46,17.84,23.52,45.57,72513.0,46685.0,308304.0,7934.00,-24.23,61.0,H-MC,14.21,125.0,0.64,2.27,36.91,AR,NTT,ELECTRICAL

In [23]:
# top 5 RSP
df_tmp = df_portfolio_features.sort_values(by = 'RSP', ascending=False)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
80,VALIANTORG,1.03,-45.08,217.08,74.15,195066.0,-73746.0,89859.0,838.00,-261.57,60.0,H-SC,25.04,145.0,-0.38,0.66,33.72,XR,NTT,CHEMICALS
5,ANGELONE,4.08,4.98,18.29,24.18,58560.0,15175.0,320175.0,303.00,-84.86,63.0,X-SC,7.47,97.0,0.26,2.36,22.49,X40N,NTT,FINANCE
52,PAGEIND,1.10,-7.60,45.15,34.11,111961.0,-20404.0,247975.0,51418.64,-33.80,69.0,X-MC,18.58,55.0,-0.18,1.83,17.30,X40,ATH,APPARELS
30,HAPPSTMNDS,1.07,-52.33,287.77,84.85,175816.0,-67069.0,61096.0,1480.71,-43.28,49.0,H-SC,23.19,152.0,-0.38,0.45,13.14,AR,ATH,IT
24,DMART,-0.94,6.35,21.87,29.60,58052.0,15840.0,265440.0,5391.45,-10.32,69.0,X-LC,5.34,14.0,0.27,1.96,21.33,X40N,ATH,FMCG

In [24]:
# Top N allocation
df_tmp = df_portfolio_features.sort_values(by = 'CurrAlloc%', ascending=False)
top_n_values = [10, 25, 50]

sum_df = pd.DataFrame({
    'Top_N': top_n_values,
    'Sum_Alloc%': [df_tmp['CurrAlloc%'].head(n).sum() for n in top_n_values]
})

sum_df

   Top_N  Sum_Alloc%
0     10       21.03
1     25       46.05
2     50       77.85

In [25]:
# market-cap-wise allocation
df_tmp = df_portfolio_features[cols]
df_tmp.groupby(df_tmp['Conviction'].str[-2:])['CurrAlloc%'].sum().sort_values(ascending=False)

Conviction
SC    44.84
MC    29.41
LC    25.73
Name: CurrAlloc%, dtype: float64

In [26]:
# criteria-wise allocation
df_portfolio_features.groupby('Criteria')['CurrAlloc%'].sum().sort_values(ascending=False)

Criteria
XY24     27.26
X40      25.27
X40N     15.37
AR        9.11
XR        8.43
XY25      7.03
OX40N     6.71
SR        0.80
Name: CurrAlloc%, dtype: float64

In [27]:
# conviction-wise allocation
df_portfolio_features.groupby('Conviction')['CurrAlloc%'].sum().sort_values(ascending=False)

Conviction
X-LC    23.52
X-MC    22.00
H-SC    21.97
X-SC    12.30
M-SC    10.01
H-MC     4.99
M-MC     2.07
H-LC     1.17
M-LC     1.04
L-SC     0.56
L-MC     0.35
Name: CurrAlloc%, dtype: float64

In [28]:
# sector-wise stats
df_tmp = df_portfolio_features.groupby('Category')[['CurrAlloc%', 'Current', 'Current P/L', 'FTT Amt']].sum().sort_values(by=['Current', 'Current P/L'], ascending=False)
df_tmp['Current P/L%'] = round(df_tmp['Current P/L'] * 100 / df_tmp['Current'], 2)
df_tmp['FTT%'] = round(df_tmp['FTT Amt'] * 100 / df_tmp['Current'], 2)
cols = ['CurrAlloc%', 'Current P/L%', 'FTT%']
df_tmp[cols].sort_values(by=['CurrAlloc%'], ascending=False)

               CurrAlloc%  Current P/L%    FTT%
Category
FMCG                14.93        -23.35   67.12
FINANCE             13.30        -19.10   67.64
IT                  11.97        -38.60  109.12
MISC                 7.14        -38.51   98.68
ELECTRICAL           6.42        -11.14   53.70
PAINTS               5.25        -38.46   62.50
BANKS                4.62        -22.84   85.20
INSURANCE            4.56         -9.56   47.05
PHARMA               4.00         -8.26   42.34
AUTO                 3.77        -28.12   78.95
HEALTHCARE           1.95        -35.23   70.52
AC                   1.89        -24.62   58.42
APPARELS             1.83         -8.23   45.15
TRAVEL               1.82        -80.80  171.33
FOOTWEAR             1.81        -80.19  152.43
DURABLES             1.75        -62.40  101.91
BREWERIES            1.60         -7.73   30.10
REALTY               1.38        -18.92   38.46
CERAMICS             1.37        -65.13  115.29
REFINERIES           1.28        -15.91   45.24
CEMENT               1.25        -58.23  176.61
ENGINEERING          1.20        -49.18  117.42
CABLES               1.16          5.83   95.78
CHEMICALS            1.10        -77.05  221.49
JEWELLERY            1.05       -125.80  204.25
ENTERTAINMENT        0.77        -84.39  194.37
TEXTILES             0.45        -49.76   92.46
HOTELS               0.36       -134.03  216.58

In [29]:
# money to be made criteria-wise
df_portfolio_features.groupby('Criteria')['FTT Amt'].agg(['sum', 'count']).sort_values(by='sum', ascending=False)

                sum  count
Criteria
XY24      3900737.0     21
X40       1747595.0     16
XR        1344487.0     12
AR        1334820.0     10
X40N      1215637.0     10
OX40N      882422.0     10
XY25       487226.0      5
SR         310855.0      2

In [30]:
# money to be made conviction-wise
df_portfolio_features.groupby('Conviction')['FTT Amt'].agg(['sum', 'count']).sort_values(by='sum', ascending=False)

                  sum  count
Conviction
H-SC        3810856.0     24
X-MC        1751993.0     15
X-LC        1586192.0     13
M-SC        1558224.0     14
X-SC        1514687.0     10
H-MC         400930.0      3
L-SC         215591.0      2
M-LC         150321.0      1
M-MC         105119.0      2
H-LC          74745.0      1
L-MC          55121.0      1

In [31]:
# money to be made criteria and conviction-wise
df_portfolio_features.groupby(['Conviction', 'Criteria'])['FTT Amt'].agg(['sum', 'count']).sort_values(by='sum', ascending=False)

                           sum  count
Conviction Criteria
H-SC       XY24      1303684.0      6
           AR         975116.0      5
M-SC       XY24       895436.0      6
X-LC       X40        853348.0      7
H-SC       XR         846112.0      7
X-SC       XY24       839495.0      4
X-MC       X40        679835.0      7
           X40N       534889.0      4
X-SC       X40N       460780.0      4
M-SC       OX40N      396822.0      5
H-SC       OX40N      375089.0      4
X-LC       XY24       358494.0      2
H-SC       SR         310855.0      2
X-MC       XY25       273686.0      2
           XY24       263583.0      2
H-MC       XY24       240045.0      1
X-LC       X40N       219968.0      2
X-SC       X40        214412.0      2
M-SC       XR         187853.0      2
H-MC       AR         160885.0      2
X-LC       XY25       154382.0      2
M-LC       XR         150321.0      1
L-SC       OX40N      110511.0      1
           XR         105080.0      1
M-SC       AR          78113.0      1
H-LC       AR          74745.0      1
M-MC       XY25        59158.0      1
L-MC       XR          55121.0      1
M-MC       AR          45961.0      1

In [32]:
# notebook execution time

end_time = time.time()
execution_time = round(end_time - start_time, 0)
print(f"Notebook execution time: {execution_time} seconds")

Notebook execution time: 30.0 seconds