<a href="https://colab.research.google.com/github/ankit-rathi/Quantvesting_v2/blob/main/myStocks_Portfolio_Analysis.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
'''
!pip install pandas==2.2.2 -qq
!pip install pyxirr -qq
!pip install ta -qq
!pip install yfinance==0.2.59 -qq
'''

'\n!pip install pandas==2.2.2 -qq\n!pip install pyxirr -qq\n!pip install ta -qq\n!pip install yfinance==0.2.59 -qq\n'

In [2]:
# import libraries

import numpy as np
import pandas as pd
import datetime
import warnings
warnings.filterwarnings('ignore')
import yfinance as yfin
import ta
import matplotlib.pyplot as plt
import requests

In [3]:
# notebook start time
import time
import datetime
import pytz

start_time = time.time()

# function to print date timestamp
def print_date_time():
  tz_NY = pytz.timezone('Asia/Kolkata')
  datetime_NY = datetime.datetime.now(tz_NY)
  print("Run date time (IST):", datetime_NY.strftime("%Y-%m-%d %H:%M:%S"))

In [4]:
# function to get booked and reserved amount
def get_amt():
  # fetch the JSON data from the URL
  url = "https://raw.githubusercontent.com/ankit-rathi/Tradevesting_v1/main/data/myPortfolioAmts.json"
  response = requests.get(url)
  pf_amts = response.json()  # parse the JSON data

  # extract values from the JSON
  py_booked_amt_dm = pf_amts["py_booked_amt_dm"]
  py_booked_amt_sv = pf_amts["py_booked_amt_sv"]
  cy_booked_amt_dm = pf_amts["cy_booked_amt_dm"]
  cy_booked_amt_sv = pf_amts["cy_booked_amt_sv"]
  reserve_amt_dm = pf_amts["reserve_amt_dm"]
  reserve_amt_sv = pf_amts["reserve_amt_sv"]

  # perform calculations
  py_booked_amt = py_booked_amt_dm + py_booked_amt_sv
  cy_booked_amt = cy_booked_amt_dm + cy_booked_amt_sv
  reserve_amt = reserve_amt_dm + reserve_amt_sv
  total_booked_amt = py_booked_amt + cy_booked_amt

  return total_booked_amt, reserve_amt, cy_booked_amt, py_booked_amt

gen_output = 0

In [5]:
# function to format the amount
def format_amt(number):
    abs_number = abs(number)

    if abs_number >= 1_00_00_000:  # Crores
        formatted_amt = f"{number / 1_00_00_000:.2f} C"
    elif abs_number >= 1_00_000:  # Lakhs
        formatted_amt = f"{number / 1_00_000:.2f} L"
    elif abs_number >= 1_000:  # Thousands
        formatted_amt = f"{number / 1_000:.2f} K"
    else:
        formatted_amt = f"{number:.2f}"

    return formatted_amt

# function to set start and end date
def get_start_end_date():
  start_date = (datetime.date.today() + datetime.timedelta(days=-365)).strftime('%Y-%m-%d')
  end_date = (datetime.date.today() + datetime.timedelta(days=1)).strftime('%Y-%m-%d')
  return start_date, end_date

# function to fetch my portfolio csv
def get_mypfs_df():
  mypfs_df = pd.read_csv('https://raw.githubusercontent.com/ankit-rathi/Tradevesting_v1/main/data/myPortfolioStocks.csv')
  return mypfs_df

# function to fetch my prospects csv
def get_mypps_df():
  mypps_df = pd.read_csv('https://raw.githubusercontent.com/ankit-rathi/Tradevesting_v1/main/data/myProspectsScrips.csv')
  return mypps_df

# function to fetch screener data
def get_myscreen_df():
  myscreen_df = pd.read_csv('https://raw.githubusercontent.com/ankit-rathi/Tradevesting_v1/main/data/myScreenerDB.csv')
  return myscreen_df

# function to fetch momentum data
def get_myinvmt_df():
  myinvmt_df = pd.read_csv('https://raw.githubusercontent.com/ankit-rathi/Tradevesting_v1/main/data/myInvestments.csv')
  return myinvmt_df

# function to get the stock ids
def get_stock_ids(df_pf):
  stock_n100 = df_pf['Symbol'].unique()

  exclude = ['CADILAHC','MMTC', 'MASFIN']

  stock_ids = df_pf[~df_pf['Symbol'].isin(exclude) ]['Symbol'].unique()

  #mypf = mypf[mypf.Forecast.notnull()]
  #stock_ids = mypf['Symbol'].unique()

  #stock_ids.sort()
  return stock_ids

# get features from screener data
def get_screener_features():
  myscreen_df = get_myscreen_df()
  cols = ['Symbol', 'EPS', 'MedPE', 'ROCE%', 'ROE%', 'CapType']
  return myscreen_df[cols]

# get relative strength
def get_relative_strength(stock_list):

    # Dictionary to store stock tickers and their corresponding percentage price change
    stock_changes = {}

    # Loop through each stock and fetch its price data
    for stock in stock_list:
        try:
            # Download the stock data for the given date range
            stock_data = yfin.Ticker(stock + '.NS').history(period='1mo', interval='1d')[map(str.title, ['open', 'close', 'low', 'high', 'volume'])]

            # Calculate the percentage change for the stock
            if len(stock_data) > 0:
                start_price = stock_data['Close'].iloc[0]
                end_price = stock_data['Close'].iloc[-1]
                percent_change = round(((end_price - start_price) / start_price) * 100, 2)
                stock_changes[stock] = percent_change
            else:
                stock_changes[stock] = np.nan  # If no data is available, set to NaN

        except Exception as e:
            print(f"Error fetching data for {stock}: {e}")
            stock_changes[stock] = np.nan

    # Create a DataFrame with stock tickers and their percentage changes
    df = pd.DataFrame(list(stock_changes.items()), columns=['Symbol', 'Percent_Change'])

    # Drop any stocks with missing data (NaN values)
    df = df.dropna()

    # Calculate the percentile rank based on percentage change
    df['RSP'] = round(df['Percent_Change'].rank(pct=True) * 100, 2)
    cols = ['Symbol', 'RSP']
    df = df[cols]
    # Sort by percentile rank (optional)
    df = df.sort_values(by='RSP', ascending=False).reset_index(drop=True)

    return df

In [6]:
# function to get stock technicals
def stock_prec_dev(stock_symbol):
    #stock_symbol = 'ULTRACEMCO.NS'
    short_window = 20
    mid_window = 50
    long_window = 200
    moving_avg = 'SMA'

    start = datetime.datetime(*map(int, start_date.split('-')))
    end = datetime.datetime(*map(int, end_date.split('-')))

    stock_df = yfin.Ticker(stock_symbol + '.NS').history(period='max', interval='1d')[map(str.title, ['open', 'close', 'low', 'high', 'volume'])]

    stock_df['Max'] = round(max(stock_df['Close']),2)
    stock_df = stock_df[(stock_df.index <= end_date) & (stock_df.index >= start_date)]
    stock_df['200_SMA'] = round(stock_df['Close'].rolling(window = 200, min_periods = 1).mean(),0)
    stock_df['Dev%_200'] = round((stock_df['Close'] - stock_df['200_SMA'])*100/stock_df['200_SMA'],2)
    stock_df.dropna(axis = 0, inplace = True) # remove any null rows

    stock_df['20_SMA'] = stock_df['Close'].rolling(window=20).mean()
    stock_df['50_SMA'] = stock_df['Close'].rolling(window=50).mean()
    stock_df['Symbol'] = stock_symbol

    stock_df['Close'] = round(stock_df['Close'],2)
    stock_df['Min'] = round(min(stock_df['Close']),2)
    stock_df['RSI_14'] = ta.momentum.RSIIndicator(close=stock_df['Close'], window=14).rsi()
    stock_df['RSI_14'] = round(stock_df['RSI_14'],0)
    stock_df['Prev_Close'] = stock_df['Close'].shift(1)
    stock_df.drop(['Open', 'Low', 'High', 'Volume'], axis=1, inplace=True)
    stock_df = stock_df.tail(1)

    max_SMA = max(stock_df['20_SMA'].item(), stock_df['50_SMA'].item(), stock_df['200_SMA'].item())
    min_SMA = min(stock_df['20_SMA'].item(), stock_df['50_SMA'].item(), stock_df['200_SMA'].item())
    ABS_Spread = max_SMA - min_SMA
    stock_df['Spread%'] = round((ABS_Spread / stock_df['200_SMA'].item()) * 100,2)

    return stock_df

# function to compute stock attributes
def get_common_features(stock_ids, df_mypf):

  df_prec_dev = pd.DataFrame()
  df_tmp = get_screener_features()
  df_rs = get_relative_strength(stock_ids)

  for stock_id in stock_ids:
      tmp = stock_prec_dev(stock_id)
      tmp = tmp.reset_index()
      df_prec_dev = pd.concat([df_prec_dev, tmp], ignore_index = True)
  df_prec_dev = pd.merge(df_prec_dev, df_mypf, on= 'Symbol')
  df_prec_dev = pd.merge(df_prec_dev, df_tmp, on= 'Symbol', how='left')
  df_prec_dev = pd.merge(df_prec_dev, df_rs, on= 'Symbol', how='left')
  #print(df_prec_dev.columns)
  df_prec_dev['Curr_PE'] = round(df_prec_dev['Close']/df_prec_dev['EPS'],1)
  df_prec_dev['Dev%_PE'] = round((df_prec_dev['Curr_PE'] - df_prec_dev['MedPE'])*100/df_prec_dev['MedPE'],2)
  df_prec_dev['Conviction'] = df_prec_dev['Conviction'] + '-' + df_prec_dev['CapType']
  return df_prec_dev

# function to arrange stock features
def arrange_features(df_stocks, common_cols, diff_cols):
  df_stocks_common = df_stocks[common_cols].drop_duplicates()
  df_stocks_diff = df_stocks[diff_cols]
  df_stocks_diff['Investment'] = df_stocks_diff['AvgCost'] * df_stocks_diff['Shares']
  df_stocks_diff = df_stocks_diff.groupby(['Symbol'])[['Shares', 'Investment']].aggregate(['sum']).reset_index()
  df_stocks_diff.columns = ['Symbol', 'Shares', 'Investment']
  df_stocks_diff['AvgCost'] = round(df_stocks_diff['Investment']/df_stocks_diff['Shares'],2)
  df_stocks = pd.merge(df_stocks_diff, df_stocks_common, on='Symbol')
  return df_stocks

# plot fact distribution across dimension
def plot_pie_chart(df, dimension, fact):
  # grouping the data by category and calculating the sum of fact for each type
  grouped_data = df.groupby(dimension)[fact].sum()

  # sorting the grouped data in descending order
  grouped_data = grouped_data.sort_values(ascending=False)

  # creating a pie chart
  grouped_data.plot.pie(autopct='%1.1f%%', startangle=90, figsize=(6, 6))

  # adding a title and displaying the plot
  plt.title(f'{dimension} {fact} Distribution')
  plt.ylabel('')  # To hide the y-label
  plt.show()

In [7]:
# function to get portfolio features

def get_portfolio_features(df_common_features):

  print_date_time()
  print('-------------------')

  #df_common_features["Target"] = df_common_features["Target"].fillna(df_common_features["Max"])
  df_common_features['NTT'] = np.where(df_common_features['Strategy']== 'NTT', df_common_features["Target"], df_common_features['Max'])
  df_common_features['LTT'] = np.where(df_common_features['Strategy']== 'BTT', df_common_features["Target"], df_common_features['Max'])
  df_common_features['BOL'] = df_common_features['Min']

  tmp_df = df_common_features[df_common_features['Symbol'].isin(mypf_df[mypf_df['InPortfolio'] != 'NA'].Symbol.values)]
  print('qualified stocks: '+str(len(tmp_df['Symbol'].unique())))
  tmp_df1 = tmp_df[tmp_df['LatestQtr'] == 1]
  print('with latest results: '+str(len(tmp_df1['Symbol'].unique())))
  tmp_df1 = tmp_df1[tmp_df1['StarStock'] == 1]
  print('still star stocks: '+str(len(tmp_df1['Symbol'].unique())))
  tmp_df['Investment'] = tmp_df['AvgCost'] * tmp_df['Shares']
  tmp_df['Current'] = round(tmp_df['Close'] * tmp_df['Shares'],0)
  tmp_df['Previous'] = tmp_df['Prev_Close'] * tmp_df['Shares']
  tmp_df['EstimatedST'] = tmp_df['NTT'] * tmp_df['Shares']
  tmp_df['EstimatedLT'] = tmp_df['LTT'] * tmp_df['Shares']
  tmp_df['Current P/L'] = round((tmp_df['Current'] - tmp_df['Investment']),0)
  tmp_df['Today P/L%'] = round((tmp_df['Current'] - tmp_df['Previous'])*100/tmp_df['Previous'],2)
  tmp_df['Current P/L%'] = round((tmp_df['Current'] - tmp_df['Investment'])*100/tmp_df['Investment'],2)
  tmp_df['EstimatedST P/L%'] = round((tmp_df['EstimatedST'] - tmp_df['Investment'])*100/tmp_df['Investment'],2)
  tmp_df['EstimatedLT P/L%'] = round((tmp_df['EstimatedLT'] - tmp_df['Investment'])*100/tmp_df['Investment'],2)
  tmp_df['NTT%'] = round((tmp_df['NTT'] - tmp_df['Close'])*100/tmp_df['Close'],2)
  tmp_df['LTT%'] = round((tmp_df['LTT'] - tmp_df['Close'])*100/tmp_df['Close'],2)
  tmp_df['Gained%'] = round((tmp_df['Close'] - tmp_df['BOL'])*100/tmp_df['BOL'],2)
  investment = round(sum(tmp_df['AvgCost']*tmp_df['Shares']),0)
  current = round(sum(tmp_df['Close']*tmp_df['Shares']),0)
  tmp_df['InitAlloc%'] = round(tmp_df['Investment']*100/investment,2)
  tmp_df['CurrAlloc%'] = round(tmp_df['Current']*100/current,2)
  tmp_df['FTT'] = tmp_df['LTT']
  tmp_df.loc[tmp_df['Strategy'] == 'NTT', 'FTT'] = tmp_df['NTT']
  tmp_df['FTT%'] = tmp_df['LTT%']
  tmp_df.loc[tmp_df['Strategy'] == 'NTT', 'FTT%'] = tmp_df['NTT%']
  tmp_df['FTT Amt'] = round(tmp_df['FTT%'] * tmp_df['Current']/100,0)
  tmp_df['OTT%'] = round((tmp_df['FTT'] - tmp_df['AvgCost'])*100/tmp_df['AvgCost'],2)
  tmp_df['RRR Ind'] = round(tmp_df['Current P/L']/tmp_df['FTT Amt'],2)
  tmp_df['Risk Ind'] = round(tmp_df['Current P/L%']*tmp_df['CurrAlloc%'],0)

  return tmp_df

# function to print portfolio features
def print_portfolio_stats(df_portfolio_features, myinvmt_df):
  from pyxirr import xirr

  total_booked_amt, reserve_amt, cy_booked_amt, py_booked_amt = get_amt()

  dates = myinvmt_df['Date'].values
  dates = np.append(dates, datetime.date.today().strftime('%d-%b-%y'))
  investment = myinvmt_df['Investment'].values
  dates= pd.to_datetime(dates)

  current = round(sum(df_portfolio_features['Close']*df_portfolio_features['Shares']),0) + reserve_amt
  investment_xirr = np.append(investment, current)
  cagr = round(xirr(pd.DataFrame({"dates": dates, "amounts": investment_xirr}))*100,2)

  investment = -sum(investment)
  invested = round(sum(df_portfolio_features['AvgCost']*df_portfolio_features['Shares']),0) + reserve_amt
  previous = round(sum(df_portfolio_features['Prev_Close']*df_portfolio_features['Shares']),0) + reserve_amt
  cy_invested = investment + py_booked_amt

  today_pnl_amount = current-previous
  today_pnl_percentage = round((current-previous)*100/previous,2)

  curr_pnl_amount = current-invested
  curr_pnl_percentage = round((curr_pnl_amount)*100/(cy_invested),2)

  cy_pnl_amount = cy_booked_amt + curr_pnl_amount
  cy_pnl_percentage = round((cy_pnl_amount)*100/cy_invested,2)

  overall_pnl_amount = total_booked_amt + curr_pnl_amount
  overall_pnl_percentage = round((overall_pnl_amount)*100/investment,2)

  estimate_st = round(sum(df_portfolio_features['FTT']*df_portfolio_features['Shares']),0)  + reserve_amt
  est_st_pnl_amount = estimate_st-current
  est_st_pnl_percentage = round((est_st_pnl_amount)*100/current,2)

  estimate_lt = round(sum(df_portfolio_features['LTT']*df_portfolio_features['Shares']),0)  + reserve_amt
  est_lt_pnl_amount = estimate_lt-current
  est_lt_pnl_percentage = round((est_lt_pnl_amount)*100/current,2)

  total_profit = round(sum(df_portfolio_features[df_portfolio_features['Current P/L%'] > 0]['Current']) - sum(df_portfolio_features[df_portfolio_features['Current P/L%'] > 0]['Investment']),0)
  total_loss = round(sum(df_portfolio_features[df_portfolio_features['Current P/L%'] < 0]['Current']) - sum(df_portfolio_features[df_portfolio_features['Current P/L%'] < 0]['Investment']),0)

  cy_booked_percentage = round((cy_booked_amt)*100/current,2)
  py_booked_percentage = round((py_booked_amt)*100/investment,2)
  total_booked_percentage = round((total_booked_amt)*100/investment,2)

  print('-------------------')
  print('Initial Investment: ', format_amt(investment))
  print('CY Investment: ', format_amt(cy_invested))
  print('Reserve: ', format_amt(reserve_amt))
  print('Current: ',  format_amt(current))
  print('-------------------')
  print('Today PnL: '+ '{} ({}%)'.format(format_amt(today_pnl_amount), today_pnl_percentage))
  print('Current PnL: '+ '{} ({}%)'.format(format_amt(curr_pnl_amount), curr_pnl_percentage))
  print('CY Booked + Current PnL: '+ '{} ({}%)'.format(format_amt(cy_pnl_amount), cy_pnl_percentage))
  print('-------------------')
  print('Total profit: ', format_amt(total_profit))
  print('Total loss: ', format_amt(total_loss))
  print('-------------------')
  print('Total Booked + Current PnL: '+ '{} ({}%)'.format(format_amt(overall_pnl_amount), overall_pnl_percentage))
  print('Total Booked PnL: '+ '{} ({}%)'.format(format_amt(total_booked_amt), total_booked_percentage))
  print('Curr Year Booked PnL: '+ '{} ({}%)'.format(format_amt(cy_booked_amt), cy_booked_percentage))
  print('Prev Year Booked PnL: '+ '{} ({}%)'.format(format_amt(py_booked_amt), py_booked_percentage))
  print('===================')
  print('Est FTT: ',  format_amt(estimate_st))
  print('Est FTT PnL: '+ '{} ({}%)'.format(format_amt(est_st_pnl_amount), est_st_pnl_percentage))

  print('===================')
  print('Deployed: ', format_amt(investment))

  print('Current: ', format_amt(current))

  print('CAGR/XIRR %: '+'{}%'.format(cagr))

In [8]:
# get start and end date
start_date, end_date = get_start_end_date()

# get portfolio and prospects data
mypfs_df = get_mypfs_df()
mypps_df = get_mypps_df()
myinvmt_df = get_myinvmt_df()

# merge above datasets
mypf_df = pd.merge(mypfs_df, mypps_df, on="Symbol")

# seggregate dm and sv portfolio
dm_pf = mypf_df[mypf_df['InPortfolio'] == 'DM']
sv_pf = mypf_df[mypf_df['InPortfolio'] == 'SV']

# build portfolio stock dataframe
dm_stocks = get_stock_ids(dm_pf)
sv_stocks = get_stock_ids(sv_pf)
df_stocks = pd.concat([dm_pf,sv_pf], ignore_index = True)

# arrange common and diff stock features
common_cols = ['Symbol', 'Target', 'Criteria', 'Strategy', 'CumlRnk', 'LatestQtr', 'StarStock', 'Conviction', 'Category', 'InFolio', 'XIRR', 'MBQ']
diff_cols = ['Symbol', 'AvgCost', 'Shares']
df_stocks = arrange_features(df_stocks, common_cols, diff_cols)

# get common features
stock_ids = df_stocks['Symbol'].values
df_common_features = get_common_features(stock_ids, df_stocks)

df_common_features.reset_index(drop=True, inplace=True)
df_common_features.drop(['Date'], axis=1, inplace=True)
# get and print portfolio features
df_portfolio_features = get_portfolio_features(df_common_features)

print_portfolio_stats(df_portfolio_features, myinvmt_df)

df = df_portfolio_features
#plot_pie_chart(df, 'CapType', 'Current')
list_ox40n = list(df[df['MBQ'].str.contains('OX40N', na=False)]['Symbol'].values)

Run date time (IST): 2026-06-11 12:18:36
-------------------
qualified stocks: 92
with latest results: 31
still star stocks: 20
-------------------
Initial Investment:  1.40 C
CY Investment:  1.82 C
Reserve:  1.49 K
Current:  1.46 C
-------------------
Today PnL: -74.28 K (-0.5%)
Current PnL: -36.79 L (-20.17%)
CY Booked + Current PnL: -34.71 L (-19.03%)
-------------------
Total profit:  2.28 L
Total loss:  -39.07 L
-------------------
Total Booked + Current PnL: 8.16 L (5.85%)
Total Booked PnL: 44.95 L (32.22%)
Curr Year Booked PnL: 2.08 L (1.42%)
Prev Year Booked PnL: 42.87 L (30.73%)
===================
Est FTT:  2.55 C
Est FTT PnL: 1.09 C (74.31%)
===================
Deployed:  1.40 C
Current:  1.46 C
CAGR/XIRR %: 2.26%

In [9]:
# top 5 near their targets
cols = ['Symbol', 'Today P/L%', 'Current P/L%', 'FTT%', 'OTT%', 'FTT Amt', 'Current P/L', 'Current', 'FTT', 'Dev%_PE', 'RSI_14','Conviction', 'Spread%',  'CumlRnk', 'RRR Ind', 'CurrAlloc%', 'Gained%', 'Criteria', 'Strategy', 'Category']
df_tmp = df_portfolio_features[~df_portfolio_features['Symbol'].isin(['ENRIN','BLUSPRING','DIGITIDE'])]
df_tmp = df_tmp.sort_values(by = 'FTT Amt', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
59,PIDILITIND,-0.28,6.46,11.18,18.37,16796.0,9120.0,150230.0,1670.26,-25.41,63.0,X-LC,3.75,5.0,0.54,1.03,17.96,X40,ATH,CHEMICALS
51,KOTAKBANK,1.86,5.62,14.66,21.11,21442.0,7788.0,146261.0,453.24,-9.41,62.0,X-LC,6.64,12.0,0.36,1.00,11.86,X40,ATH,BANKS
72,SIS,3.27,-1.46,23.06,21.26,25229.0,-1624.0,109408.0,528.00,2610.88,67.0,H-SC,20.92,168.0,-0.06,0.75,62.67,OX40N,NTT,MISC
83,TTKPRESTIG,-1.93,-30.56,44.14,0.09,30889.0,-30797.0,69980.0,770.00,62.43,52.0,M-SC,12.28,250.0,-1.00,0.48,24.61,OX40N,NTT,DURABLES
55,MASFIN,-1.48,-10.41,35.69,21.57,31329.0,-10200.0,87780.0,397.04,-22.76,35.0,H-SC,2.96,167.0,-0.33,0.60,4.63,XR,ATH,FINANCE

In [10]:
# top 5 today
df_tmp = df_portfolio_features.sort_values(by = 'Today P/L%', ascending=False)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
18,COFFEEDAY,3.35,-42.10,133.64,35.27,87856.0,-47808.0,65741.0,80.00,-55.73,58.0,L-SC,17.36,266.0,-0.54,0.45,62.12,XR,NTT,HOTELS
72,SIS,3.27,-1.46,23.06,21.26,25229.0,-1624.0,109408.0,528.00,2610.88,67.0,H-SC,20.92,168.0,-0.06,0.75,62.67,OX40N,NTT,MISC
38,HYUNDAI,2.86,3.40,44.44,49.35,70877.0,5249.0,159490.0,2809.30,-16.67,61.0,X-LC,16.27,29.0,0.07,1.09,14.99,X40N,ATH,AUTO
60,QUESS,2.42,0.02,73.86,73.90,78897.0,26.0,106819.0,424.00,-46.01,76.0,X-SC,4.96,80.0,0.00,0.73,45.62,XY24,NTT,MISC
25,FINCABLES,1.96,28.43,61.89,107.91,117355.0,41974.0,189618.0,1641.55,15.68,47.0,M-SC,23.76,220.0,0.36,1.30,42.66,OX40N,ATH,CABLES

In [11]:
# bottom 5 today
df_tmp = df_portfolio_features.sort_values(by = 'Today P/L%', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
61,RAJESHEXPO,-5.00,-84.46,544.04,0.07,115957.0,-115863.0,21314.0,518.00,681.57,24.0,L-SC,32.47,268.0,-1.00,0.15,0.06,OX40N,NTT,JEWELLERY
24,EASEMYTRIP,-4.54,-53.53,213.54,45.70,175449.0,-94653.0,82162.0,26.40,-14.66,61.0,M-SC,4.90,204.0,-0.54,0.56,43.93,XY24,NTT,TRAVEL
27,GLAXO,-2.44,-14.82,59.31,35.69,100675.0,-29540.0,169744.0,3380.16,-34.96,27.0,X-MC,9.21,56.0,-0.29,1.16,0.00,X40,ATH,PHARMA
68,SATIN,-2.28,26.62,19.91,51.83,69652.0,73550.0,349834.0,274.00,13.01,57.0,H-SC,41.53,159.0,1.06,2.39,70.42,XY24,NTT,FINANCE
63,RECLTD,-2.21,-7.66,30.75,20.74,57689.0,-15565.0,187605.0,446.00,1.56,49.0,M-MC,3.96,191.0,-0.27,1.28,11.80,XY25,NTT,FINANCE

In [12]:
# top 5 to exit based on CumlRnk
df_tmp = df_portfolio_features[~df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])]
df_tmp = df_tmp[(df_tmp['Current P/L%'] > -1) & (df_tmp['Current P/L%'] < 1)].sort_values(by = 'CumlRnk', ascending=False)
df_tmp[cols].head()

Empty DataFrame
Columns: [Symbol, Today P/L%, Current P/L%, FTT%, OTT%, FTT Amt, Current P/L, Current, FTT, Dev%_PE, RSI_14, Conviction, Spread%, CumlRnk, RRR Ind, CurrAlloc%, Gained%, Criteria, Strategy, Category]
Index: []

In [13]:
# OX40N stocks to exit
df_tmp = df_portfolio_features[(df_portfolio_features['Symbol'].isin(list_ox40n))].sort_values(by = 'Current P/L%', ascending=False)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
25,FINCABLES,1.96,28.43,61.89,107.91,117355.0,41974.0,189618.0,1641.55,15.68,47.0,M-SC,23.76,220.0,0.36,1.30,42.66,OX40N,ATH,CABLES
72,SIS,3.27,-1.46,23.06,21.26,25229.0,-1624.0,109408.0,528.00,2610.88,67.0,H-SC,20.92,168.0,-0.06,0.75,62.67,OX40N,NTT,MISC
16,CERA,-0.04,-23.29,61.50,23.89,82989.0,-40962.0,134941.0,9475.00,-26.01,62.0,H-SC,4.06,153.0,-0.49,0.92,29.68,OX40N,NTT,CERAMICS
50,KANSAINER,0.27,-28.25,58.15,13.47,112510.0,-76185.0,193482.0,340.00,-38.33,56.0,H-SC,7.63,162.0,-0.68,1.32,35.15,XY24,NTT,PAINTS
83,TTKPRESTIG,-1.93,-30.56,44.14,0.09,30889.0,-30797.0,69980.0,770.00,62.43,52.0,M-SC,12.28,250.0,-1.00,0.48,24.61,OX40N,NTT,DURABLES

In [14]:
# top 5 to book for rotation
df_tmp = df_portfolio_features[(df_portfolio_features['Current P/L%'] > 20) ].sort_values(by = 'CumlRnk', ascending=False)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
25,FINCABLES,1.96,28.43,61.89,107.91,117355.0,41974.0,189618.0,1641.55,15.68,47.0,M-SC,23.76,220.0,0.36,1.30,42.66,OX40N,ATH,CABLES
68,SATIN,-2.28,26.62,19.91,51.83,69652.0,73550.0,349834.0,274.00,13.01,57.0,H-SC,41.53,159.0,1.06,2.39,70.42,XY24,NTT,FINANCE

In [15]:
# top 5 to monitor for exit
df_tmp = df_portfolio_features[~df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])]
df_tmp = df_tmp[(df_tmp['Current P/L%'] > 0) ].sort_values(by = 'Dev%_PE', ascending=False)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
74,STARHEALTH,1.28,2.77,43.29,47.26,125073.0,7795.0,288918.0,761.00,62.26,61.0,H-SC,10.10,173.0,0.06,1.97,26.84,XY24,NTT,INSURANCE
25,FINCABLES,1.96,28.43,61.89,107.91,117355.0,41974.0,189618.0,1641.55,15.68,47.0,M-SC,23.76,220.0,0.36,1.30,42.66,OX40N,ATH,CABLES
68,SATIN,-2.28,26.62,19.91,51.83,69652.0,73550.0,349834.0,274.00,13.01,57.0,H-SC,41.53,159.0,1.06,2.39,70.42,XY24,NTT,FINANCE
91,ZYDUSLIFE,0.43,16.31,16.61,35.63,40489.0,34189.0,243763.0,1286.17,1.35,71.0,H-MC,12.15,120.0,0.84,1.67,28.17,AR,ATH,PHARMA
73,SONACOMS,0.50,2.45,35.77,39.09,37070.0,2476.0,103635.0,804.02,-18.85,50.0,M-MC,18.54,193.0,0.07,0.71,46.61,AR,ATH,AUTO

In [16]:
# top 5 to book for rotation from weak conviction
df_tmp = df_portfolio_features[~df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])]
df_tmp = df_tmp[~df_tmp['Criteria'].isin(['XY25','XY24','X40', 'X40N'])].sort_values(by = 'RRR Ind', ascending=False)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
91,ZYDUSLIFE,0.43,16.31,16.61,35.63,40489.0,34189.0,243763.0,1286.17,1.35,71.0,H-MC,12.15,120.0,0.84,1.67,28.17,AR,ATH,PHARMA
25,FINCABLES,1.96,28.43,61.89,107.91,117355.0,41974.0,189618.0,1641.55,15.68,47.0,M-SC,23.76,220.0,0.36,1.30,42.66,OX40N,ATH,CABLES
73,SONACOMS,0.50,2.45,35.77,39.09,37070.0,2476.0,103635.0,804.02,-18.85,50.0,M-MC,18.54,193.0,0.07,0.71,46.61,AR,ATH,AUTO
72,SIS,3.27,-1.46,23.06,21.26,25229.0,-1624.0,109408.0,528.00,2610.88,67.0,H-SC,20.92,168.0,-0.06,0.75,62.67,OX40N,NTT,MISC
42,INDIAMART,-0.29,-13.88,140.04,106.72,148746.0,-17119.0,106217.0,4810.62,-61.13,45.0,H-SC,10.84,140.0,-0.12,0.73,2.83,AR,ATH,MISC

In [17]:
# top 5 to accumulate based on lowest RSI_14
df_tmp = df_portfolio_features[df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])].sort_values(by = 'RSI_14', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
35,HDFCLIFE,-0.34,-10.42,48.68,33.18,65322.0,-15614.0,134186.0,814.30,-30.01,25.0,X-LC,15.89,31.0,-0.24,0.92,0.00,X40,ATH,INSURANCE
27,GLAXO,-2.44,-14.82,59.31,35.69,100675.0,-29540.0,169744.0,3380.16,-34.96,27.0,X-MC,9.21,56.0,-0.29,1.16,0.00,X40,ATH,PHARMA
40,ICICIPRULI,-0.58,-23.37,70.00,30.28,105680.0,-46034.0,150971.0,787.27,-43.95,28.0,X-MC,16.20,78.0,-0.44,1.03,0.00,X40,ATH,INSURANCE
58,PGHH,-0.34,-32.56,95.74,32.01,137866.0,-69520.0,144000.0,17616.87,-54.37,31.0,X-MC,18.98,57.0,-0.50,0.98,0.00,X40,ATH,FMCG
2,ACC,-0.85,-41.60,199.31,74.81,312119.0,-111528.0,156600.0,3906.00,-58.80,33.0,X-SC,17.49,85.0,-0.36,1.07,4.02,XY24,BTT,CEMENT

In [18]:
# top 5 to accumulate based on Spread and CumlRnk
df_tmp = df_portfolio_features[df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])]
df_tmp = df_tmp[(df_tmp['CumlRnk'] < 100)].sort_values(by = 'Spread%', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
49,JSWINFRA,-1.15,-6.24,24.18,16.43,50277.0,-13847.0,207927.0,342.00,-19.64,51.0,X-MC,2.90,61.0,-0.28,1.42,17.54,X40N,NTT,REALTY
57,PAGEIND,0.01,-0.99,34.92,33.59,92789.0,-2659.0,265720.0,51217.29,-29.03,53.0,X-MC,3.02,55.0,-0.03,1.82,26.19,X40,ATH,APPARELS
15,CAMS,-1.57,-4.42,30.23,24.48,72774.0,-11121.0,240735.0,950.00,-8.50,39.0,X-SC,3.28,89.0,-0.15,1.64,17.20,X40N,NTT,MISC
19,COLPAL,-0.32,-22.17,79.70,39.86,163361.0,-58395.0,204970.0,3683.41,-5.85,49.0,X-MC,3.46,62.0,-0.36,1.40,15.94,XY25,ATH,FMCG
59,PIDILITIND,-0.28,6.46,11.18,18.37,16796.0,9120.0,150230.0,1670.26,-25.41,63.0,X-LC,3.75,5.0,0.54,1.03,17.96,X40,ATH,CHEMICALS

In [19]:
# top 5 to accumulate based on lowest Gained%
df_tmp = df_portfolio_features[df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])].sort_values(by = 'Gained%', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
27,GLAXO,-2.44,-14.82,59.31,35.69,100675.0,-29540.0,169744.0,3380.16,-34.96,27.0,X-MC,9.21,56.0,-0.29,1.16,0.0,X40,ATH,PHARMA
40,ICICIPRULI,-0.58,-23.37,70.00,30.28,105680.0,-46034.0,150971.0,787.27,-43.95,28.0,X-MC,16.20,78.0,-0.44,1.03,0.0,X40,ATH,INSURANCE
35,HDFCLIFE,-0.34,-10.42,48.68,33.18,65322.0,-15614.0,134186.0,814.30,-30.01,25.0,X-LC,15.89,31.0,-0.24,0.92,0.0,X40,ATH,INSURANCE
33,HCLTECH,-1.78,-27.84,68.38,21.51,119381.0,-67340.0,174584.0,1872.35,-24.32,34.0,X-LC,18.47,8.0,-0.56,1.19,0.0,X40,ATH,IT
79,TCS,-0.54,-37.11,98.58,24.88,287202.0,-171934.0,291339.0,4253.91,-46.90,35.0,X-LC,18.77,2.0,-0.60,1.99,0.0,X40,ATH,IT

In [20]:
# top 5 to accumulate based on lowest CurrAlloc%
df_tmp = df_portfolio_features[df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])].sort_values(by = 'CurrAlloc%', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
10,BATAINDIA,-0.38,-57.33,216.86,35.20,119065.0,-73766.0,54904.0,2096.0,-28.09,38.0,X-SC,25.54,91.0,-0.62,0.38,8.89,X40,NTT,FOOTWEAR
64,RELAXO,-0.38,-55.54,242.56,52.31,156548.0,-80620.0,64540.0,1176.0,-52.67,63.0,X-SC,19.96,92.0,-0.51,0.44,44.30,X40N,NTT,FOOTWEAR
60,QUESS,2.42,0.02,73.86,73.90,78897.0,26.0,106819.0,424.0,-46.01,76.0,X-SC,4.96,80.0,0.00,0.73,45.62,XY24,NTT,MISC
53,M&M,1.68,-2.59,26.66,23.38,36015.0,-3591.0,135090.0,3802.4,-17.57,44.0,X-LC,10.70,25.0,-0.10,0.92,2.42,X40N,ATH,AUTO
35,HDFCLIFE,-0.34,-10.42,48.68,33.18,65322.0,-15614.0,134186.0,814.3,-30.01,25.0,X-LC,15.89,31.0,-0.24,0.92,0.00,X40,ATH,INSURANCE

In [21]:
# top 5 to accumulate based on CumlRnk
df_tmp = df_portfolio_features.sort_values(by = 'CumlRnk', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
47,ITC,-0.49,-25.66,60.14,19.06,152092.0,-87270.0,252896.0,452.00,-59.16,40.0,X-LC,14.93,1.0,-0.57,1.73,1.90,X40,NTT,FMCG
79,TCS,-0.54,-37.11,98.58,24.88,287202.0,-171934.0,291339.0,4253.91,-46.90,35.0,X-LC,18.77,2.0,-0.60,1.99,0.00,X40,ATH,IT
45,INFY,-1.89,-23.51,75.51,34.24,180716.0,-73561.0,239327.0,1972.00,-39.77,42.0,X-LC,16.89,3.0,-0.41,1.64,4.83,X40,NTT,IT
81,TMPV,-1.09,-14.22,59.21,36.58,180737.0,-50593.0,305248.0,600.00,-82.53,51.0,X-LC,15.16,4.0,-0.28,2.09,27.23,XY24,NTT,AUTO
59,PIDILITIND,-0.28,6.46,11.18,18.37,16796.0,9120.0,150230.0,1670.26,-25.41,63.0,X-LC,3.75,5.0,0.54,1.03,17.96,X40,ATH,CHEMICALS

In [22]:
# top 5 for average up
df_tmp = df_portfolio_features[(df_portfolio_features['Dev%_200'] > 5)].sort_values(by = 'CurrAlloc%', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
44,INDUSINDBK,1.25,-33.92,101.12,32.89,51586.0,-26192.0,51015.0,1800.00,-340.20,48.0,L-MC,7.06,258.0,-0.51,0.35,25.57,XR,NTT,BANKS
3,ALKYLAMINE,-0.17,-23.60,153.45,93.63,118361.0,-23830.0,77133.0,4546.37,-18.23,57.0,H-SC,8.85,142.0,-0.20,0.53,45.65,SR,ATH,CHEMICALS
24,EASEMYTRIP,-4.54,-53.53,213.54,45.70,175449.0,-94653.0,82162.0,26.40,-14.66,61.0,M-SC,4.90,204.0,-0.54,0.56,43.93,XY24,NTT,TRAVEL
73,SONACOMS,0.50,2.45,35.77,39.09,37070.0,2476.0,103635.0,804.02,-18.85,50.0,M-MC,18.54,193.0,0.07,0.71,46.61,AR,ATH,AUTO
60,QUESS,2.42,0.02,73.86,73.90,78897.0,26.0,106819.0,424.00,-46.01,76.0,X-SC,4.96,80.0,0.00,0.73,45.62,XY24,NTT,MISC

In [23]:
# top 5 RSP
df_tmp = df_portfolio_features.sort_values(by = 'RSP', ascending=False)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
18,COFFEEDAY,3.35,-42.10,133.64,35.27,87856.0,-47808.0,65741.0,80.00,-55.73,58.0,L-SC,17.36,266.0,-0.54,0.45,62.12,XR,NTT,HOTELS
37,HONAUT,-1.88,-8.08,64.62,51.31,114539.0,-15588.0,177250.0,58357.33,-23.63,62.0,X-SC,7.29,90.0,-0.14,1.21,34.66,X40N,ATH,ELECTRICAL
69,SFL,-2.12,-32.92,88.77,26.63,156150.0,-86314.0,175904.0,1287.00,33.18,69.0,M-SC,9.36,242.0,-0.55,1.20,46.61,XY24,NTT,MISC
91,ZYDUSLIFE,0.43,16.31,16.61,35.63,40489.0,34189.0,243763.0,1286.17,1.35,71.0,H-MC,12.15,120.0,0.84,1.67,28.17,AR,ATH,PHARMA
72,SIS,3.27,-1.46,23.06,21.26,25229.0,-1624.0,109408.0,528.00,2610.88,67.0,H-SC,20.92,168.0,-0.06,0.75,62.67,OX40N,NTT,MISC

In [24]:
# Top N allocation
df_tmp = df_portfolio_features.sort_values(by = 'CurrAlloc%', ascending=False)
top_n_values = [10, 25, 50]

sum_df = pd.DataFrame({
    'Top_N': top_n_values,
    'Sum_Alloc%': [df_tmp['CurrAlloc%'].head(n).sum() for n in top_n_values]
})

sum_df

   Top_N  Sum_Alloc%
0     10       19.61
1     25       42.81
2     50       72.76

In [25]:
# market-cap-wise allocation
df_tmp = df_portfolio_features[cols]
df_tmp.groupby(df_tmp['Conviction'].str[-2:])['CurrAlloc%'].sum().sort_values(ascending=False)

Conviction
SC    43.04
LC    31.27
MC    25.71
Name: CurrAlloc%, dtype: float64

In [26]:
# criteria-wise allocation
df_portfolio_features.groupby('Criteria')['CurrAlloc%'].sum().sort_values(ascending=False)

Criteria
XY24     27.92
X40      24.89
X40N     17.10
XR        8.84
OX40N     6.92
AR        6.88
XY25      6.59
SR        0.88
Name: CurrAlloc%, dtype: float64

In [27]:
# conviction-wise allocation
df_portfolio_features.groupby('Conviction')['CurrAlloc%'].sum().sort_values(ascending=False)

Conviction
X-LC    29.23
H-SC    22.59
X-MC    20.54
M-SC     9.99
X-SC     9.86
H-MC     2.83
M-MC     1.99
H-LC     1.20
M-LC     0.84
L-SC     0.60
L-MC     0.35
Name: CurrAlloc%, dtype: float64

In [28]:
# sector-wise stats
df_tmp = df_portfolio_features.groupby('Category')[['CurrAlloc%', 'Current', 'Current P/L', 'FTT Amt']].sum().sort_values(by=['Current', 'Current P/L'], ascending=False)
df_tmp['Current P/L%'] = round(df_tmp['Current P/L'] * 100 / df_tmp['Current'], 2)
df_tmp['FTT%'] = round(df_tmp['FTT Amt'] * 100 / df_tmp['Current'], 2)
cols = ['CurrAlloc%', 'Current P/L%', 'FTT%']
df_tmp[cols].sort_values(by=['CurrAlloc%'], ascending=False)

               CurrAlloc%  Current P/L%    FTT%
Category
FMCG                14.98        -20.57   62.86
FINANCE             10.77        -17.07   67.99
IT                  10.01        -53.72  130.58
MISC                 7.15        -28.05   83.67
AUTO                 6.82         -9.67   50.78
BANKS                5.76         -7.81   57.66
PAINTS               5.68        -18.54   39.12
INSURANCE            5.17         -9.48   46.50
PHARMA               5.08          0.21   30.69
ELECTRICAL           4.05        -19.08   61.10
CHEMICALS            2.18        -27.43  103.37
HEALTHCARE           2.03        -20.29   51.68
AC                   1.83        -19.63   52.07
APPARELS             1.82         -1.00   34.92
FOOTWEAR             1.73        -75.23  145.49
TRAVEL               1.72        -77.63  166.57
DURABLES             1.56        -68.98  110.09
BREWERIES            1.49         -7.49   29.81
REALTY               1.42         -6.66   24.18
CERAMICS             1.39        -50.27   95.92
CABLES               1.30         22.14   61.89
ENGINEERING          1.29        -28.23   86.88
REFINERIES           1.12        -22.51   53.51
CEMENT               1.07        -71.22  199.31
JEWELLERY            1.03       -113.83  188.12
ENTERTAINMENT        0.72        -83.48  192.91
HOTELS               0.45        -72.72  133.64
TEXTILES             0.40        -57.60  102.53

In [29]:
# money to be made criteria-wise
df_portfolio_features.groupby('Criteria')['FTT Amt'].agg(['sum', 'count']).sort_values(by='sum', ascending=False)

                sum  count
Criteria
XY24      3510544.0     21
X40       2043244.0     19
XR        1386523.0     13
X40N      1216881.0     13
AR        1178173.0      9
OX40N      781259.0     10
XY25       471197.0      5
SR         290449.0      2

In [30]:
# money to be made conviction-wise
df_portfolio_features.groupby('Conviction')['FTT Amt'].agg(['sum', 'count']).sort_values(by='sum', ascending=False)

                  sum  count
Conviction
H-SC        3479837.0     24
X-LC        2009990.0     21
X-MC        1713338.0     15
M-SC        1455502.0     14
X-SC        1359257.0      9
H-MC         284521.0      2
L-SC         203813.0      2
M-LC         168269.0      1
M-MC          94759.0      2
H-LC          57398.0      1
L-MC          51586.0      1

In [31]:
# money to be made criteria and conviction-wise
df_portfolio_features.groupby(['Conviction', 'Criteria'])['FTT Amt'].agg(['sum', 'count']).sort_values(by='sum', ascending=False)

                           sum  count
Conviction Criteria
X-LC       X40       1087675.0     10
H-SC       XY24      1062268.0      6
           AR         965743.0      5
M-SC       XY24       840415.0      6
H-SC       XR         835787.0      7
X-SC       XY24       797066.0      4
X-MC       X40        737239.0      7
           X40N       498000.0      4
X-LC       X40N       375020.0      6
X-SC       X40N       343861.0      3
M-SC       OX40N      339712.0      5
X-LC       XY24       337696.0      2
H-SC       OX40N      325590.0      4
           SR         290449.0      2
X-MC       XY25       249032.0      2
H-MC       XY24       244032.0      1
X-MC       XY24       229067.0      2
X-SC       X40        218330.0      2
M-SC       XR         197902.0      2
M-LC       XR         168269.0      1
X-LC       XY25       164476.0      2
L-SC       OX40N      115957.0      1
           XR          87856.0      1
M-SC       AR          77473.0      1
M-MC       XY25        57689.0      1
H-LC       AR          57398.0      1
L-MC       XR          51586.0      1
X-LC       XR          45123.0      1
H-MC       AR          40489.0      1
M-MC       AR          37070.0      1

In [32]:
# notebook execution time

end_time = time.time()
execution_time = round(end_time - start_time, 0)
print(f"Notebook execution time: {execution_time} seconds")

Notebook execution time: 25.0 seconds