<a href="https://colab.research.google.com/github/ankit-rathi/Quantvesting_v2/blob/main/myStocks_Portfolio_Analysis.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
'''
!pip install pandas==2.2.2 -qq
!pip install pyxirr -qq
!pip install ta -qq
!pip install yfinance==0.2.59 -qq
'''

'\n!pip install pandas==2.2.2 -qq\n!pip install pyxirr -qq\n!pip install ta -qq\n!pip install yfinance==0.2.59 -qq\n'

In [2]:
# import libraries

import numpy as np
import pandas as pd
import datetime
import warnings
warnings.filterwarnings('ignore')
import yfinance as yfin
import ta
import matplotlib.pyplot as plt
import requests

In [3]:
# notebook start time
import time
import datetime
import pytz

start_time = time.time()

# function to print date timestamp
def print_date_time():
  tz_NY = pytz.timezone('Asia/Kolkata')
  datetime_NY = datetime.datetime.now(tz_NY)
  print("Run date time (IST):", datetime_NY.strftime("%Y-%m-%d %H:%M:%S"))

In [4]:
# function to get booked and reserved amount
def get_amt():
  # fetch the JSON data from the URL
  url = "https://raw.githubusercontent.com/ankit-rathi/Tradevesting_v1/main/data/myPortfolioAmts.json"
  response = requests.get(url)
  pf_amts = response.json()  # parse the JSON data

  # extract values from the JSON
  py_booked_amt_dm = pf_amts["py_booked_amt_dm"]
  py_booked_amt_sv = pf_amts["py_booked_amt_sv"]
  cy_booked_amt_dm = pf_amts["cy_booked_amt_dm"]
  cy_booked_amt_sv = pf_amts["cy_booked_amt_sv"]
  reserve_amt_dm = pf_amts["reserve_amt_dm"]
  reserve_amt_sv = pf_amts["reserve_amt_sv"]

  # perform calculations
  py_booked_amt = py_booked_amt_dm + py_booked_amt_sv
  cy_booked_amt = cy_booked_amt_dm + cy_booked_amt_sv
  reserve_amt = reserve_amt_dm + reserve_amt_sv
  total_booked_amt = py_booked_amt + cy_booked_amt

  return total_booked_amt, reserve_amt, cy_booked_amt, py_booked_amt

gen_output = 0

In [5]:
# function to format the amount
def format_amt(number):
    abs_number = abs(number)

    if abs_number >= 1_00_00_000:  # Crores
        formatted_amt = f"{number / 1_00_00_000:.2f} C"
    elif abs_number >= 1_00_000:  # Lakhs
        formatted_amt = f"{number / 1_00_000:.2f} L"
    elif abs_number >= 1_000:  # Thousands
        formatted_amt = f"{number / 1_000:.2f} K"
    else:
        formatted_amt = f"{number:.2f}"

    return formatted_amt

# function to set start and end date
def get_start_end_date():
  start_date = (datetime.date.today() + datetime.timedelta(days=-365)).strftime('%Y-%m-%d')
  end_date = (datetime.date.today() + datetime.timedelta(days=1)).strftime('%Y-%m-%d')
  return start_date, end_date

# function to fetch my portfolio csv
def get_mypfs_df():
  mypfs_df = pd.read_csv('https://raw.githubusercontent.com/ankit-rathi/Tradevesting_v1/main/data/myPortfolioStocks.csv')
  return mypfs_df

# function to fetch my prospects csv
def get_mypps_df():
  mypps_df = pd.read_csv('https://raw.githubusercontent.com/ankit-rathi/Tradevesting_v1/main/data/myProspectsScrips.csv')
  return mypps_df

# function to fetch screener data
def get_myscreen_df():
  myscreen_df = pd.read_csv('https://raw.githubusercontent.com/ankit-rathi/Tradevesting_v1/main/data/myScreenerDB.csv')
  return myscreen_df

# function to fetch momentum data
def get_myinvmt_df():
  myinvmt_df = pd.read_csv('https://raw.githubusercontent.com/ankit-rathi/Tradevesting_v1/main/data/myInvestments.csv')
  return myinvmt_df

# function to get the stock ids
def get_stock_ids(df_pf):
  stock_n100 = df_pf['Symbol'].unique()

  exclude = ['CADILAHC','MMTC', 'MASFIN']

  stock_ids = df_pf[~df_pf['Symbol'].isin(exclude) ]['Symbol'].unique()

  #mypf = mypf[mypf.Forecast.notnull()]
  #stock_ids = mypf['Symbol'].unique()

  #stock_ids.sort()
  return stock_ids

# get features from screener data
def get_screener_features():
  myscreen_df = get_myscreen_df()
  cols = ['Symbol', 'EPS', 'MedPE', 'ROCE%', 'ROE%', 'CapType']
  return myscreen_df[cols]

# get relative strength
def get_relative_strength(stock_list):

    # Dictionary to store stock tickers and their corresponding percentage price change
    stock_changes = {}

    # Loop through each stock and fetch its price data
    for stock in stock_list:
        try:
            # Download the stock data for the given date range
            stock_data = yfin.Ticker(stock + '.NS').history(period='1mo', interval='1d')[map(str.title, ['open', 'close', 'low', 'high', 'volume'])]

            # Calculate the percentage change for the stock
            if len(stock_data) > 0:
                start_price = stock_data['Close'].iloc[0]
                end_price = stock_data['Close'].iloc[-1]
                percent_change = round(((end_price - start_price) / start_price) * 100, 2)
                stock_changes[stock] = percent_change
            else:
                stock_changes[stock] = np.nan  # If no data is available, set to NaN

        except Exception as e:
            print(f"Error fetching data for {stock}: {e}")
            stock_changes[stock] = np.nan

    # Create a DataFrame with stock tickers and their percentage changes
    df = pd.DataFrame(list(stock_changes.items()), columns=['Symbol', 'Percent_Change'])

    # Drop any stocks with missing data (NaN values)
    df = df.dropna()

    # Calculate the percentile rank based on percentage change
    df['RSP'] = round(df['Percent_Change'].rank(pct=True) * 100, 2)
    cols = ['Symbol', 'RSP']
    df = df[cols]
    # Sort by percentile rank (optional)
    df = df.sort_values(by='RSP', ascending=False).reset_index(drop=True)

    return df

In [6]:
# function to get stock technicals
def stock_prec_dev(stock_symbol):
    #stock_symbol = 'ULTRACEMCO.NS'
    short_window = 20
    mid_window = 50
    long_window = 200
    moving_avg = 'SMA'

    start = datetime.datetime(*map(int, start_date.split('-')))
    end = datetime.datetime(*map(int, end_date.split('-')))

    stock_df = yfin.Ticker(stock_symbol + '.NS').history(period='max', interval='1d')[map(str.title, ['open', 'close', 'low', 'high', 'volume'])]

    stock_df['Max'] = round(max(stock_df['Close']),2)
    stock_df = stock_df[(stock_df.index <= end_date) & (stock_df.index >= start_date)]
    stock_df['200_SMA'] = round(stock_df['Close'].rolling(window = 200, min_periods = 1).mean(),0)
    stock_df['Dev%_200'] = round((stock_df['Close'] - stock_df['200_SMA'])*100/stock_df['200_SMA'],2)
    stock_df.dropna(axis = 0, inplace = True) # remove any null rows

    stock_df['20_SMA'] = stock_df['Close'].rolling(window=20).mean()
    stock_df['50_SMA'] = stock_df['Close'].rolling(window=50).mean()
    stock_df['Symbol'] = stock_symbol

    stock_df['Close'] = round(stock_df['Close'],2)
    stock_df['Min'] = round(min(stock_df['Close']),2)
    stock_df['RSI_14'] = ta.momentum.RSIIndicator(close=stock_df['Close'], window=14).rsi()
    stock_df['RSI_14'] = round(stock_df['RSI_14'],0)
    stock_df['Prev_Close'] = stock_df['Close'].shift(1)
    stock_df.drop(['Open', 'Low', 'High', 'Volume'], axis=1, inplace=True)
    stock_df = stock_df.tail(1)

    max_SMA = max(stock_df['20_SMA'].item(), stock_df['50_SMA'].item(), stock_df['200_SMA'].item())
    min_SMA = min(stock_df['20_SMA'].item(), stock_df['50_SMA'].item(), stock_df['200_SMA'].item())
    ABS_Spread = max_SMA - min_SMA
    stock_df['Spread%'] = round((ABS_Spread / stock_df['200_SMA'].item()) * 100,2)

    return stock_df

# function to compute stock attributes
def get_common_features(stock_ids, df_mypf):

  df_prec_dev = pd.DataFrame()
  df_tmp = get_screener_features()
  df_rs = get_relative_strength(stock_ids)

  for stock_id in stock_ids:
      tmp = stock_prec_dev(stock_id)
      tmp = tmp.reset_index()
      df_prec_dev = pd.concat([df_prec_dev, tmp], ignore_index = True)
  df_prec_dev = pd.merge(df_prec_dev, df_mypf, on= 'Symbol')
  df_prec_dev = pd.merge(df_prec_dev, df_tmp, on= 'Symbol', how='left')
  df_prec_dev = pd.merge(df_prec_dev, df_rs, on= 'Symbol', how='left')
  #print(df_prec_dev.columns)
  df_prec_dev['Curr_PE'] = round(df_prec_dev['Close']/df_prec_dev['EPS'],1)
  df_prec_dev['Dev%_PE'] = round((df_prec_dev['Curr_PE'] - df_prec_dev['MedPE'])*100/df_prec_dev['MedPE'],2)
  df_prec_dev['Conviction'] = df_prec_dev['Conviction'] + '-' + df_prec_dev['CapType']
  return df_prec_dev

# function to arrange stock features
def arrange_features(df_stocks, common_cols, diff_cols):
  df_stocks_common = df_stocks[common_cols].drop_duplicates()
  df_stocks_diff = df_stocks[diff_cols]
  df_stocks_diff['Investment'] = df_stocks_diff['AvgCost'] * df_stocks_diff['Shares']
  df_stocks_diff = df_stocks_diff.groupby(['Symbol'])[['Shares', 'Investment']].aggregate(['sum']).reset_index()
  df_stocks_diff.columns = ['Symbol', 'Shares', 'Investment']
  df_stocks_diff['AvgCost'] = round(df_stocks_diff['Investment']/df_stocks_diff['Shares'],2)
  df_stocks = pd.merge(df_stocks_diff, df_stocks_common, on='Symbol')
  return df_stocks

# plot fact distribution across dimension
def plot_pie_chart(df, dimension, fact):
  # grouping the data by category and calculating the sum of fact for each type
  grouped_data = df.groupby(dimension)[fact].sum()

  # sorting the grouped data in descending order
  grouped_data = grouped_data.sort_values(ascending=False)

  # creating a pie chart
  grouped_data.plot.pie(autopct='%1.1f%%', startangle=90, figsize=(6, 6))

  # adding a title and displaying the plot
  plt.title(f'{dimension} {fact} Distribution')
  plt.ylabel('')  # To hide the y-label
  plt.show()

In [7]:
# function to get portfolio features

def get_portfolio_features(df_common_features):

  print_date_time()
  print('-------------------')

  #df_common_features["Target"] = df_common_features["Target"].fillna(df_common_features["Max"])
  df_common_features['NTT'] = np.where(df_common_features['Strategy']== 'NTT', df_common_features["Target"], df_common_features['Max'])
  df_common_features['LTT'] = np.where(df_common_features['Strategy']== 'BTT', df_common_features["Target"], df_common_features['Max'])
  df_common_features['BOL'] = df_common_features['Min']

  tmp_df = df_common_features[df_common_features['Symbol'].isin(mypf_df[mypf_df['InPortfolio'] != 'NA'].Symbol.values)]
  print('qualified stocks: '+str(len(tmp_df['Symbol'].unique())))
  tmp_df1 = tmp_df[tmp_df['LatestQtr'] == 1]
  print('with latest results: '+str(len(tmp_df1['Symbol'].unique())))
  tmp_df1 = tmp_df1[tmp_df1['StarStock'] == 1]
  print('still star stocks: '+str(len(tmp_df1['Symbol'].unique())))
  tmp_df['Investment'] = tmp_df['AvgCost'] * tmp_df['Shares']
  tmp_df['Current'] = round(tmp_df['Close'] * tmp_df['Shares'],0)
  tmp_df['Previous'] = tmp_df['Prev_Close'] * tmp_df['Shares']
  tmp_df['EstimatedST'] = tmp_df['NTT'] * tmp_df['Shares']
  tmp_df['EstimatedLT'] = tmp_df['LTT'] * tmp_df['Shares']
  tmp_df['Current P/L'] = round((tmp_df['Current'] - tmp_df['Investment']),0)
  tmp_df['Today P/L%'] = round((tmp_df['Current'] - tmp_df['Previous'])*100/tmp_df['Previous'],2)
  tmp_df['Current P/L%'] = round((tmp_df['Current'] - tmp_df['Investment'])*100/tmp_df['Investment'],2)
  tmp_df['EstimatedST P/L%'] = round((tmp_df['EstimatedST'] - tmp_df['Investment'])*100/tmp_df['Investment'],2)
  tmp_df['EstimatedLT P/L%'] = round((tmp_df['EstimatedLT'] - tmp_df['Investment'])*100/tmp_df['Investment'],2)
  tmp_df['NTT%'] = round((tmp_df['NTT'] - tmp_df['Close'])*100/tmp_df['Close'],2)
  tmp_df['LTT%'] = round((tmp_df['LTT'] - tmp_df['Close'])*100/tmp_df['Close'],2)
  tmp_df['Gained%'] = round((tmp_df['Close'] - tmp_df['BOL'])*100/tmp_df['BOL'],2)
  investment = round(sum(tmp_df['AvgCost']*tmp_df['Shares']),0)
  current = round(sum(tmp_df['Close']*tmp_df['Shares']),0)
  tmp_df['InitAlloc%'] = round(tmp_df['Investment']*100/investment,2)
  tmp_df['CurrAlloc%'] = round(tmp_df['Current']*100/current,2)
  tmp_df['FTT'] = tmp_df['LTT']
  tmp_df.loc[tmp_df['Strategy'] == 'NTT', 'FTT'] = tmp_df['NTT']
  tmp_df['FTT%'] = tmp_df['LTT%']
  tmp_df.loc[tmp_df['Strategy'] == 'NTT', 'FTT%'] = tmp_df['NTT%']
  tmp_df['FTT Amt'] = round(tmp_df['FTT%'] * tmp_df['Current']/100,0)
  tmp_df['OTT%'] = round((tmp_df['FTT'] - tmp_df['AvgCost'])*100/tmp_df['AvgCost'],2)
  tmp_df['RRR Ind'] = round(tmp_df['Current P/L']/tmp_df['FTT Amt'],2)
  tmp_df['Risk Ind'] = round(tmp_df['Current P/L%']*tmp_df['CurrAlloc%'],0)

  return tmp_df

# function to print portfolio features
def print_portfolio_stats(df_portfolio_features, myinvmt_df):
  from pyxirr import xirr

  total_booked_amt, reserve_amt, cy_booked_amt, py_booked_amt = get_amt()

  dates = myinvmt_df['Date'].values
  dates = np.append(dates, datetime.date.today().strftime('%d-%b-%y'))
  investment = myinvmt_df['Investment'].values
  dates= pd.to_datetime(dates)

  current = round(sum(df_portfolio_features['Close']*df_portfolio_features['Shares']),0) + reserve_amt
  investment_xirr = np.append(investment, current)
  cagr = round(xirr(pd.DataFrame({"dates": dates, "amounts": investment_xirr}))*100,2)

  investment = -sum(investment)
  invested = round(sum(df_portfolio_features['AvgCost']*df_portfolio_features['Shares']),0) + reserve_amt
  previous = round(sum(df_portfolio_features['Prev_Close']*df_portfolio_features['Shares']),0) + reserve_amt
  cy_invested = investment + py_booked_amt

  today_pnl_amount = current-previous
  today_pnl_percentage = round((current-previous)*100/previous,2)

  curr_pnl_amount = current-invested
  curr_pnl_percentage = round((curr_pnl_amount)*100/(cy_invested),2)

  cy_pnl_amount = cy_booked_amt + curr_pnl_amount
  cy_pnl_percentage = round((cy_pnl_amount)*100/cy_invested,2)

  overall_pnl_amount = total_booked_amt + curr_pnl_amount
  overall_pnl_percentage = round((overall_pnl_amount)*100/investment,2)

  estimate_st = round(sum(df_portfolio_features['FTT']*df_portfolio_features['Shares']),0)  + reserve_amt
  est_st_pnl_amount = estimate_st-current
  est_st_pnl_percentage = round((est_st_pnl_amount)*100/current,2)

  estimate_lt = round(sum(df_portfolio_features['LTT']*df_portfolio_features['Shares']),0)  + reserve_amt
  est_lt_pnl_amount = estimate_lt-current
  est_lt_pnl_percentage = round((est_lt_pnl_amount)*100/current,2)

  total_profit = round(sum(df_portfolio_features[df_portfolio_features['Current P/L%'] > 0]['Current']) - sum(df_portfolio_features[df_portfolio_features['Current P/L%'] > 0]['Investment']),0)
  total_loss = round(sum(df_portfolio_features[df_portfolio_features['Current P/L%'] < 0]['Current']) - sum(df_portfolio_features[df_portfolio_features['Current P/L%'] < 0]['Investment']),0)

  cy_booked_percentage = round((cy_booked_amt)*100/current,2)
  py_booked_percentage = round((py_booked_amt)*100/investment,2)
  total_booked_percentage = round((total_booked_amt)*100/investment,2)

  print('-------------------')
  print('Initial Investment: ', format_amt(investment))
  print('CY Investment: ', format_amt(cy_invested))
  print('Reserve: ', format_amt(reserve_amt))
  print('Current: ',  format_amt(current))
  print('-------------------')
  print('Today PnL: '+ '{} ({}%)'.format(format_amt(today_pnl_amount), today_pnl_percentage))
  print('Current PnL: '+ '{} ({}%)'.format(format_amt(curr_pnl_amount), curr_pnl_percentage))
  print('CY Booked + Current PnL: '+ '{} ({}%)'.format(format_amt(cy_pnl_amount), cy_pnl_percentage))
  print('-------------------')
  print('Total profit: ', format_amt(total_profit))
  print('Total loss: ', format_amt(total_loss))
  print('-------------------')
  print('Total Booked + Current PnL: '+ '{} ({}%)'.format(format_amt(overall_pnl_amount), overall_pnl_percentage))
  print('Total Booked PnL: '+ '{} ({}%)'.format(format_amt(total_booked_amt), total_booked_percentage))
  print('Curr Year Booked PnL: '+ '{} ({}%)'.format(format_amt(cy_booked_amt), cy_booked_percentage))
  print('Prev Year Booked PnL: '+ '{} ({}%)'.format(format_amt(py_booked_amt), py_booked_percentage))
  print('===================')
  print('Est FTT: ',  format_amt(estimate_st))
  print('Est FTT PnL: '+ '{} ({}%)'.format(format_amt(est_st_pnl_amount), est_st_pnl_percentage))

  print('===================')
  print('Deployed: ', format_amt(investment))

  print('Current: ', format_amt(current))

  print('CAGR/XIRR %: '+'{}%'.format(cagr))

In [8]:
# get start and end date
start_date, end_date = get_start_end_date()

# get portfolio and prospects data
mypfs_df = get_mypfs_df()
mypps_df = get_mypps_df()
myinvmt_df = get_myinvmt_df()

# merge above datasets
mypf_df = pd.merge(mypfs_df, mypps_df, on="Symbol")

# seggregate dm and sv portfolio
dm_pf = mypf_df[mypf_df['InPortfolio'] == 'DM']
sv_pf = mypf_df[mypf_df['InPortfolio'] == 'SV']

# build portfolio stock dataframe
dm_stocks = get_stock_ids(dm_pf)
sv_stocks = get_stock_ids(sv_pf)
df_stocks = pd.concat([dm_pf,sv_pf], ignore_index = True)

# arrange common and diff stock features
common_cols = ['Symbol', 'Target', 'Criteria', 'Strategy', 'CumlRnk', 'LatestQtr', 'StarStock', 'Conviction', 'Category', 'InFolio', 'XIRR', 'MBQ']
diff_cols = ['Symbol', 'AvgCost', 'Shares']
df_stocks = arrange_features(df_stocks, common_cols, diff_cols)

# get common features
stock_ids = df_stocks['Symbol'].values
df_common_features = get_common_features(stock_ids, df_stocks)

df_common_features.reset_index(drop=True, inplace=True)
df_common_features.drop(['Date'], axis=1, inplace=True)
# get and print portfolio features
df_portfolio_features = get_portfolio_features(df_common_features)

print_portfolio_stats(df_portfolio_features, myinvmt_df)

df = df_portfolio_features
#plot_pie_chart(df, 'CapType', 'Current')
list_ox40n = list(df[df['MBQ'].str.contains('OX40N', na=False)]['Symbol'].values)

Run date time (IST): 2026-07-03 14:46:03
-------------------
qualified stocks: 92
with latest results: 31
still star stocks: 20
-------------------
Initial Investment:  1.40 C
CY Investment:  1.82 C
Reserve:  1.49 K
Current:  1.53 C
-------------------
Today PnL: 887.00 (0.01%)
Current PnL: -29.88 L (-16.38%)
CY Booked + Current PnL: -27.80 L (-15.24%)
-------------------
Total profit:  4.80 L
Total loss:  -34.68 L
-------------------
Total Booked + Current PnL: 15.07 L (10.8%)
Total Booked PnL: 44.95 L (32.22%)
Curr Year Booked PnL: 2.08 L (1.36%)
Prev Year Booked PnL: 42.87 L (30.73%)
===================
Est FTT:  2.55 C
Est FTT PnL: 1.02 C (66.34%)
===================
Deployed:  1.40 C
Current:  1.53 C
CAGR/XIRR %: 4.34%

In [9]:
# top 5 near their targets
cols = ['Symbol', 'Today P/L%', 'Current P/L%', 'FTT%', 'OTT%', 'FTT Amt', 'Current P/L', 'Current', 'FTT', 'Dev%_PE', 'RSI_14','Conviction', 'Spread%',  'CumlRnk', 'RRR Ind', 'CurrAlloc%', 'Gained%', 'Criteria', 'Strategy', 'Category']
df_tmp = df_portfolio_features[~df_portfolio_features['Symbol'].isin(['ENRIN','BLUSPRING','DIGITIDE'])]
df_tmp = df_tmp.sort_values(by = 'FTT Amt', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
59,PIDILITIND,-0.50,13.20,4.57,18.37,7300.0,18620.0,159730.0,1670.26,-20.71,67.0,X-LC,6.81,5.0,2.55,1.04,25.42,X40,ATH,CHEMICALS
49,JSWINFRA,-0.52,10.91,4.97,16.43,12225.0,24205.0,245979.0,342.00,-4.83,65.0,X-MC,10.04,61.0,1.98,1.60,39.46,X40N,NTT,REALTY
83,TTKPRESTIG,-3.22,-18.74,23.17,0.09,18975.0,-18882.0,81895.0,770.00,90.18,69.0,M-SC,6.02,250.0,-1.00,0.53,45.82,OX40N,NTT,DURABLES
56,MEDANTA,-0.04,15.03,10.51,27.12,21341.0,26533.0,203050.0,1486.00,11.45,73.0,X-SC,6.80,87.0,1.24,1.32,39.91,XY24,NTT,HEALTHCARE
51,KOTAKBANK,-0.95,5.68,14.60,21.11,21365.0,7862.0,146335.0,453.24,-9.41,50.0,X-LC,4.31,12.0,0.37,0.95,11.91,X40,ATH,BANKS

In [10]:
# top 5 today
df_tmp = df_portfolio_features.sort_values(by = 'Today P/L%', ascending=False)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
33,HCLTECH,5.72,-26.03,64.27,21.51,115011.0,-62975.0,178949.0,1872.35,-22.25,52.0,X-LC,20.34,8.0,-0.55,1.17,10.21,X40,ATH,IT
61,RAJESHEXPO,4.17,-81.55,442.41,0.07,111965.0,-111869.0,25308.0,518.00,828.03,48.0,L-SC,38.93,268.0,-1.00,0.17,24.98,OX40N,NTT,JEWELLERY
6,AWL,3.65,-34.34,154.37,67.02,361152.0,-122357.0,233952.0,485.00,-64.61,55.0,X-SC,14.82,81.0,-0.34,1.53,11.24,XY24,NTT,FMCG
7,BAJAJHFL,3.59,-17.97,97.65,62.13,218710.0,-49073.0,223973.0,181.50,-32.55,70.0,X-MC,8.65,60.0,-0.22,1.46,25.64,X40N,ATH,FINANCE
91,ZYDUSLIFE,3.34,19.85,13.17,35.63,33079.0,41592.0,251166.0,1286.17,4.50,66.0,H-MC,14.47,120.0,1.26,1.64,32.06,AR,ATH,PHARMA

In [11]:
# bottom 5 today
df_tmp = df_portfolio_features.sort_values(by = 'Today P/L%', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
23,DMART,-4.47,-3.85,34.79,29.60,83496.0,-9600.0,240000.0,5391.45,-18.89,36.0,X-LC,3.76,14.0,-0.11,1.57,9.70,X40N,ATH,FMCG
25,FINCABLES,-3.25,38.45,50.17,107.91,102552.0,56766.0,204410.0,1641.55,24.30,49.0,M-SC,26.36,220.0,0.55,1.33,53.78,OX40N,ATH,CABLES
83,TTKPRESTIG,-3.22,-18.74,23.17,0.09,18975.0,-18882.0,81895.0,770.00,90.18,69.0,M-SC,6.02,250.0,-1.00,0.53,45.82,OX40N,NTT,DURABLES
40,ICICIPRULI,-2.22,-19.75,62.34,30.28,98556.0,-38911.0,158094.0,787.27,-41.32,44.0,X-MC,16.54,78.0,-0.39,1.03,5.33,X40,ATH,INSURANCE
68,SATIN,-2.03,40.98,7.70,51.83,29993.0,113233.0,389517.0,274.00,26.15,64.0,H-SC,41.46,159.0,3.78,2.54,89.75,XY24,NTT,FINANCE

In [12]:
# top 5 to exit based on CumlRnk
df_tmp = df_portfolio_features[~df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])]
df_tmp = df_tmp[(df_tmp['Current P/L%'] > -1) & (df_tmp['Current P/L%'] < 1)].sort_values(by = 'CumlRnk', ascending=False)
df_tmp[cols].head()

Empty DataFrame
Columns: [Symbol, Today P/L%, Current P/L%, FTT%, OTT%, FTT Amt, Current P/L, Current, FTT, Dev%_PE, RSI_14, Conviction, Spread%, CumlRnk, RRR Ind, CurrAlloc%, Gained%, Criteria, Strategy, Category]
Index: []

In [13]:
# OX40N stocks to exit
df_tmp = df_portfolio_features[(df_portfolio_features['Symbol'].isin(list_ox40n))].sort_values(by = 'Current P/L%', ascending=False)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
25,FINCABLES,-3.25,38.45,50.17,107.91,102552.0,56766.0,204410.0,1641.55,24.30,49.0,M-SC,26.36,220.0,0.55,1.33,53.78,OX40N,ATH,CABLES
72,SIS,0.19,-2.11,23.87,21.26,25945.0,-2338.0,108694.0,528.00,2593.26,55.0,H-SC,24.94,168.0,-0.09,0.71,61.61,OX40N,NTT,MISC
16,CERA,0.02,-15.30,46.28,23.89,68949.0,-26921.0,148982.0,9475.00,-18.38,66.0,H-SC,13.20,153.0,-0.39,0.97,43.17,OX40N,NTT,CERAMICS
83,TTKPRESTIG,-3.22,-18.74,23.17,0.09,18975.0,-18882.0,81895.0,770.00,90.18,69.0,M-SC,6.02,250.0,-1.00,0.53,45.82,OX40N,NTT,DURABLES
43,INDIGOPNTS,-0.85,-24.14,31.85,0.02,42176.0,-42139.0,132420.0,1408.00,102.01,66.0,M-SC,5.28,222.0,-1.00,0.86,50.24,OX40N,NTT,PAINTS

In [14]:
# top 5 to book for rotation
df_tmp = df_portfolio_features[(df_portfolio_features['Current P/L%'] > 20) ].sort_values(by = 'CumlRnk', ascending=False)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
25,FINCABLES,-3.25,38.45,50.17,107.91,102552.0,56766.0,204410.0,1641.55,24.30,49.0,M-SC,26.36,220.0,0.55,1.33,53.78,OX40N,ATH,CABLES
68,SATIN,-2.03,40.98,7.70,51.83,29993.0,113233.0,389517.0,274.00,26.15,64.0,H-SC,41.46,159.0,3.78,2.54,89.75,XY24,NTT,FINANCE

In [15]:
# top 5 to monitor for exit
df_tmp = df_portfolio_features[~df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])]
df_tmp = df_tmp[(df_tmp['Current P/L%'] > 0) ].sort_values(by = 'Dev%_PE', ascending=False)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
75,SURYODAY,-0.92,3.67,18.67,23.03,34661.0,6579.0,185650.0,216.00,101.75,66.0,H-SC,19.72,166.0,0.19,1.21,56.31,XR,NTT,BANKS
74,STARHEALTH,-1.33,12.37,31.05,47.26,98087.0,34778.0,315901.0,761.00,77.33,67.0,H-SC,15.03,173.0,0.35,2.06,38.62,XY24,NTT,INSURANCE
68,SATIN,-2.03,40.98,7.70,51.83,29993.0,113233.0,389517.0,274.00,26.15,64.0,H-SC,41.46,159.0,3.78,2.54,89.75,XY24,NTT,FINANCE
25,FINCABLES,-3.25,38.45,50.17,107.91,102552.0,56766.0,204410.0,1641.55,24.30,49.0,M-SC,26.36,220.0,0.55,1.33,53.78,OX40N,ATH,CABLES
91,ZYDUSLIFE,3.34,19.85,13.17,35.63,33079.0,41592.0,251166.0,1286.17,4.50,66.0,H-MC,14.47,120.0,1.26,1.64,32.06,AR,ATH,PHARMA

In [16]:
# top 5 to book for rotation from weak conviction
df_tmp = df_portfolio_features[~df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])]
df_tmp = df_tmp[~df_tmp['Criteria'].isin(['XY25','XY24','X40', 'X40N'])].sort_values(by = 'RRR Ind', ascending=False)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
91,ZYDUSLIFE,3.34,19.85,13.17,35.63,33079.0,41592.0,251166.0,1286.17,4.50,66.0,H-MC,14.47,120.0,1.26,1.64,32.06,AR,ATH,PHARMA
73,SONACOMS,-0.29,14.25,21.39,38.69,24720.0,14411.0,115570.0,801.69,-9.53,75.0,M-MC,18.50,193.0,0.58,0.75,63.96,AR,ATH,AUTO
25,FINCABLES,-3.25,38.45,50.17,107.91,102552.0,56766.0,204410.0,1641.55,24.30,49.0,M-SC,26.36,220.0,0.55,1.33,53.78,OX40N,ATH,CABLES
75,SURYODAY,-0.92,3.67,18.67,23.03,34661.0,6579.0,185650.0,216.00,101.75,66.0,H-SC,19.72,166.0,0.19,1.21,56.31,XR,NTT,BANKS
55,MASFIN,1.16,-1.29,23.15,21.57,22391.0,-1260.0,96720.0,397.04,-15.09,59.0,H-SC,2.43,167.0,-0.06,0.63,15.29,XR,ATH,FINANCE

In [17]:
# top 5 to accumulate based on lowest RSI_14
df_tmp = df_portfolio_features[df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])].sort_values(by = 'RSI_14', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
23,DMART,-4.47,-3.85,34.79,29.60,83496.0,-9600.0,240000.0,5391.45,-18.89,36.0,X-LC,3.76,14.0,-0.11,1.57,9.70,X40N,ATH,FMCG
81,TMPV,-0.81,-21.89,74.85,36.58,208047.0,-77889.0,277952.0,600.00,-83.62,38.0,X-LC,7.53,4.0,-0.37,1.81,16.81,XY24,NTT,AUTO
58,PGHH,-0.03,-33.43,98.31,32.01,139734.0,-71384.0,142136.0,17616.87,-54.91,39.0,X-MC,21.07,57.0,-0.51,0.93,0.80,X40,ATH,FMCG
35,HDFCLIFE,-0.58,-7.10,42.84,32.71,59621.0,-10628.0,139172.0,811.41,-27.44,40.0,X-LC,16.03,31.0,-0.18,0.91,4.55,X40,ATH,INSURANCE
26,GILLETTE,-0.13,-10.16,44.39,29.72,101256.0,-25791.0,228105.0,10978.86,-31.02,41.0,X-SC,6.32,83.0,-0.25,1.49,4.83,X40,ATH,FMCG

In [18]:
# top 5 to accumulate based on Spread and CumlRnk
df_tmp = df_portfolio_features[df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])]
df_tmp = df_tmp[(df_tmp['CumlRnk'] < 100)].sort_values(by = 'Spread%', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
17,CIPLA,0.14,18.04,13.04,33.43,23575.0,27631.0,180792.0,1648.14,-8.67,68.0,X-LC,2.13,18.0,1.17,1.18,23.42,X40N,ATH,PHARMA
84,UNITDSPR,1.21,2.11,18.27,20.77,43680.0,4936.0,239080.0,1644.00,-9.40,65.0,X-MC,3.15,64.0,0.11,1.56,14.05,X40N,NTT,BREWERIES
11,BERGEPAINT,-0.40,-4.42,31.11,25.32,76642.0,-11390.0,246359.0,680.00,-9.58,51.0,X-MC,3.21,68.0,-0.15,1.61,28.22,XY24,NTT,PAINTS
19,COLPAL,-0.79,-22.34,80.10,39.86,163821.0,-58845.0,204520.0,3683.41,-6.07,52.0,X-MC,3.40,62.0,-0.36,1.33,15.69,XY25,ATH,FMCG
23,DMART,-4.47,-3.85,34.79,29.60,83496.0,-9600.0,240000.0,5391.45,-18.89,36.0,X-LC,3.76,14.0,-0.11,1.57,9.70,X40N,ATH,FMCG

In [19]:
# top 5 to accumulate based on lowest Gained%
df_tmp = df_portfolio_features[df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])].sort_values(by = 'Gained%', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
58,PGHH,-0.03,-33.43,98.31,32.01,139734.0,-71384.0,142136.0,17616.87,-54.91,39.0,X-MC,21.07,57.0,-0.51,0.93,0.80,X40,ATH,FMCG
1,ABBOTINDIA,0.41,-13.35,36.26,18.07,56196.0,-23875.0,154980.0,35195.00,-26.29,46.0,X-MC,6.56,58.0,-0.42,1.01,2.58,X40,ATH,PHARMA
65,RELIANCE,0.05,-16.28,49.67,25.30,83566.0,-32721.0,168242.0,1952.00,-18.49,46.0,X-LC,7.82,21.0,-0.39,1.10,3.61,XY25,BTT,REFINERIES
32,HAVELLS,-0.68,-24.54,74.16,31.42,183550.0,-80485.0,247506.0,2052.62,-28.94,49.0,X-MC,12.95,63.0,-0.44,1.61,4.39,X40,ATH,ELECTRICAL
35,HDFCLIFE,-0.58,-7.10,42.84,32.71,59621.0,-10628.0,139172.0,811.41,-27.44,40.0,X-LC,16.03,31.0,-0.18,0.91,4.55,X40,ATH,INSURANCE

In [20]:
# top 5 to accumulate based on lowest CurrAlloc%
df_tmp = df_portfolio_features[df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])].sort_values(by = 'CurrAlloc%', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
10,BATAINDIA,-0.36,-55.10,201.13,35.20,116197.0,-70898.0,57772.0,2096.00,-24.19,49.0,X-SC,20.05,91.0,-0.61,0.38,14.58,X40,NTT,FOOTWEAR
64,RELAXO,-1.70,-48.38,195.07,52.31,146160.0,-70233.0,74927.0,1176.00,-45.02,65.0,X-SC,10.65,92.0,-0.48,0.49,67.53,X40N,NTT,FOOTWEAR
60,QUESS,1.80,18.39,46.89,73.90,59283.0,19636.0,126429.0,424.00,-36.09,85.0,X-SC,19.16,80.0,0.33,0.82,72.35,XY24,NTT,MISC
35,HDFCLIFE,-0.58,-7.10,42.84,32.71,59621.0,-10628.0,139172.0,811.41,-27.44,40.0,X-LC,16.03,31.0,-0.18,0.91,4.55,X40,ATH,INSURANCE
53,M&M,-1.48,1.51,20.26,22.08,28522.0,2097.0,140778.0,3762.31,-14.09,55.0,X-LC,9.01,25.0,0.07,0.92,7.87,X40N,ATH,AUTO

In [21]:
# top 5 to accumulate based on CumlRnk
df_tmp = df_portfolio_features.sort_values(by = 'CumlRnk', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
47,ITC,0.12,-23.55,55.73,19.06,144934.0,-80102.0,260064.0,452.00,-57.95,51.0,X-LC,13.19,1.0,-0.55,1.70,4.78,X40,NTT,FMCG
79,TCS,1.06,-38.65,103.54,24.88,294302.0,-179033.0,284240.0,4253.91,-48.21,43.0,X-LC,21.62,2.0,-0.61,1.85,5.42,X40,ATH,IT
45,INFY,0.68,-28.66,88.17,34.24,196817.0,-89664.0,223224.0,1972.00,-43.76,43.0,X-LC,20.39,3.0,-0.46,1.46,6.36,X40,NTT,IT
81,TMPV,-0.81,-21.89,74.85,36.58,208047.0,-77889.0,277952.0,600.00,-83.62,38.0,X-LC,7.53,4.0,-0.37,1.81,16.81,XY24,NTT,AUTO
59,PIDILITIND,-0.50,13.20,4.57,18.37,7300.0,18620.0,159730.0,1670.26,-20.71,67.0,X-LC,6.81,5.0,2.55,1.04,25.42,X40,ATH,CHEMICALS

In [22]:
# top 5 for average up
df_tmp = df_portfolio_features[(df_portfolio_features['Dev%_200'] > 5)].sort_values(by = 'CurrAlloc%', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
44,INDUSINDBK,2.99,-28.26,85.24,32.89,47212.0,-21820.0,55387.0,1800.00,-360.50,65.0,L-MC,7.44,258.0,-0.46,0.36,36.55,XR,NTT,BANKS
64,RELAXO,-1.70,-48.38,195.07,52.31,146160.0,-70233.0,74927.0,1176.00,-45.02,65.0,X-SC,10.65,92.0,-0.48,0.49,67.53,X40N,NTT,FOOTWEAR
3,ALKYLAMINE,0.04,-22.12,147.23,92.54,115767.0,-22333.0,78630.0,4520.85,-16.57,57.0,H-SC,8.85,142.0,-0.19,0.51,49.31,SR,ATH,CHEMICALS
83,TTKPRESTIG,-3.22,-18.74,23.17,0.09,18975.0,-18882.0,81895.0,770.00,90.18,69.0,M-SC,6.02,250.0,-1.00,0.53,45.82,OX40N,NTT,DURABLES
72,SIS,0.19,-2.11,23.87,21.26,25945.0,-2338.0,108694.0,528.00,2593.26,55.0,H-SC,24.94,168.0,-0.09,0.71,61.61,OX40N,NTT,MISC

In [23]:
# top 5 RSP
df_tmp = df_portfolio_features.sort_values(by = 'RSP', ascending=False)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
60,QUESS,1.80,18.39,46.89,73.90,59283.0,19636.0,126429.0,424.0,-36.09,85.0,X-SC,19.16,80.0,0.33,0.82,72.35,XY24,NTT,MISC
69,SFL,0.89,-24.26,67.19,26.63,133445.0,-63610.0,198608.0,1287.0,50.46,74.0,M-SC,19.25,242.0,-0.48,1.30,65.53,XY24,NTT,MISC
49,JSWINFRA,-0.52,10.91,4.97,16.43,12225.0,24205.0,245979.0,342.0,-4.83,65.0,X-MC,10.04,61.0,1.98,1.60,39.46,X40N,NTT,REALTY
0,5PAISA,1.00,-25.91,52.38,12.90,84796.0,-56610.0,161886.0,593.0,137.98,80.0,H-SC,2.21,170.0,-0.67,1.06,56.22,OX40N,NTT,FINANCE
64,RELAXO,-1.70,-48.38,195.07,52.31,146160.0,-70233.0,74927.0,1176.0,-45.02,65.0,X-SC,10.65,92.0,-0.48,0.49,67.53,X40N,NTT,FOOTWEAR

In [24]:
# Top N allocation
df_tmp = df_portfolio_features.sort_values(by = 'CurrAlloc%', ascending=False)
top_n_values = [10, 25, 50]

sum_df = pd.DataFrame({
    'Top_N': top_n_values,
    'Sum_Alloc%': [df_tmp['CurrAlloc%'].head(n).sum() for n in top_n_values]
})

sum_df

   Top_N  Sum_Alloc%
0     10       19.41
1     25       42.63
2     50       72.79

In [25]:
# market-cap-wise allocation
df_tmp = df_portfolio_features[cols]
df_tmp.groupby(df_tmp['Conviction'].str[-2:])['CurrAlloc%'].sum().sort_values(ascending=False)

Conviction
SC    43.81
LC    30.28
MC    25.90
Name: CurrAlloc%, dtype: float64

In [26]:
# criteria-wise allocation
df_portfolio_features.groupby('Criteria')['CurrAlloc%'].sum().sort_values(ascending=False)

Criteria
XY24     27.97
X40      24.47
X40N     17.47
XR        8.85
OX40N     7.17
AR        6.75
XY25      6.43
SR        0.88
Name: CurrAlloc%, dtype: float64

In [27]:
# conviction-wise allocation
df_portfolio_features.groupby('Conviction')['CurrAlloc%'].sum().sort_values(ascending=False)

Conviction
X-LC    28.33
H-SC    22.97
X-MC    20.76
X-SC    10.13
M-SC    10.13
H-MC     2.72
M-MC     2.06
H-LC     1.15
M-LC     0.80
L-SC     0.58
L-MC     0.36
Name: CurrAlloc%, dtype: float64

In [28]:
# sector-wise stats
df_tmp = df_portfolio_features.groupby('Category')[['CurrAlloc%', 'Current', 'Current P/L', 'FTT Amt']].sum().sort_values(by=['Current', 'Current P/L'], ascending=False)
df_tmp['Current P/L%'] = round(df_tmp['Current P/L'] * 100 / df_tmp['Current'], 2)
df_tmp['FTT%'] = round(df_tmp['FTT Amt'] * 100 / df_tmp['Current'], 2)
cols = ['CurrAlloc%', 'Current P/L%', 'FTT%']
df_tmp[cols].sort_values(by=['CurrAlloc%'], ascending=False)

               CurrAlloc%  Current P/L%    FTT%
Category
FMCG                14.45        -19.51   61.43
FINANCE             11.53         -4.44   49.70
IT                   9.56        -53.89  130.84
MISC                 7.25        -20.62   72.38
AUTO                 6.67         -7.11   47.04
BANKS                5.75         -2.93   50.52
PAINTS               5.54        -15.98   35.76
INSURANCE            5.22         -3.42   38.31
PHARMA               5.07          4.74   24.74
ELECTRICAL           4.05        -13.73   53.87
CHEMICALS            2.17        -21.84   94.13
HEALTHCARE           2.10        -10.92   39.87
APPARELS             1.96         10.57   19.47
AC                   1.75        -19.23   51.56
FOOTWEAR             1.74        -65.97  132.52
DURABLES             1.61        -56.28   94.30
REALTY               1.60          9.84    4.97
BREWERIES            1.56          2.06   18.27
TRAVEL               1.53        -89.93  185.03
CERAMICS             1.44        -39.29   81.61
CABLES               1.33         27.77   50.17
ENGINEERING          1.30        -21.27   76.74
REFINERIES           1.10        -19.45   49.67
CEMENT               1.09        -60.73  180.97
JEWELLERY            1.03       -102.97  173.48
ENTERTAINMENT        0.75        -67.93  168.08
TEXTILES             0.43        -39.47   79.24
HOTELS               0.41        -81.41  145.40

In [29]:
# money to be made criteria-wise
df_portfolio_features.groupby('Criteria')['FTT Amt'].agg(['sum', 'count']).sort_values(by='sum', ascending=False)

                sum  count
Criteria
XY24      3309575.0     21
X40       1925232.0     19
XR        1325460.0     13
AR        1141252.0      9
X40N      1042128.0     13
OX40N      691832.0     10
XY25       450769.0      5
SR         283472.0      2

In [30]:
# money to be made conviction-wise
df_portfolio_features.groupby('Conviction')['FTT Amt'].agg(['sum', 'count']).sort_values(by='sum', ascending=False)

                  sum  count
Conviction
H-SC        3256963.0     24
X-LC        1938357.0     21
X-MC        1531909.0     15
M-SC        1363973.0     14
X-SC        1251232.0      9
H-MC         280533.0      2
L-SC         202974.0      2
M-LC         170033.0      1
M-MC          69334.0      2
H-LC          57200.0      1
L-MC          47212.0      1

In [31]:
# money to be made criteria and conviction-wise
df_portfolio_features.groupby(['Conviction', 'Criteria'])['FTT Amt'].agg(['sum', 'count']).sort_values(by='sum', ascending=False)

                           sum  count
Conviction Criteria
X-LC       X40       1041289.0     10
H-SC       AR         953612.0      5
           XY24       937794.0      6
M-SC       XY24       808651.0      6
H-SC       XR         798187.0      7
X-SC       XY24       743677.0      4
X-MC       X40        666490.0      7
           X40N       397722.0      4
X-LC       X40N       354304.0      6
           XY24       354109.0      2
M-SC       OX40N      295969.0      5
X-SC       X40N       290102.0      3
H-SC       OX40N      283898.0      4
           SR         283472.0      2
X-MC       XY25       249807.0      2
H-MC       XY24       247454.0      1
X-MC       XY24       217890.0      2
X-SC       X40        217453.0      2
M-SC       XR         186712.0      2
M-LC       XR         170033.0      1
X-LC       XY25       156348.0      2
L-SC       OX40N      111965.0      1
           XR          91009.0      1
M-SC       AR          72641.0      1
H-LC       AR          57200.0      1
L-MC       XR          47212.0      1
M-MC       XY25        44614.0      1
H-MC       AR          33079.0      1
X-LC       XR          32307.0      1
M-MC       AR          24720.0      1

In [32]:
# notebook execution time

end_time = time.time()
execution_time = round(end_time - start_time, 0)
print(f"Notebook execution time: {execution_time} seconds")

Notebook execution time: 26.0 seconds