<a href="https://colab.research.google.com/github/ankit-rathi/Quantvesting_v2/blob/main/myStocks_Portfolio_Analysis.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
'''
!pip install pandas==2.2.2 -qq
!pip install pyxirr -qq
!pip install ta -qq
!pip install yfinance==0.2.59 -qq
'''

'\n!pip install pandas==2.2.2 -qq\n!pip install pyxirr -qq\n!pip install ta -qq\n!pip install yfinance==0.2.59 -qq\n'

In [2]:
# import libraries

import numpy as np
import pandas as pd
import datetime
import warnings
warnings.filterwarnings('ignore')
import yfinance as yfin
import ta
import matplotlib.pyplot as plt
import requests

In [3]:
# notebook start time
import time
import datetime
import pytz

start_time = time.time()

# function to print date timestamp
def print_date_time():
  tz_NY = pytz.timezone('Asia/Kolkata')
  datetime_NY = datetime.datetime.now(tz_NY)
  print("Run date time (IST):", datetime_NY.strftime("%Y-%m-%d %H:%M:%S"))

In [4]:
# function to get booked and reserved amount
def get_amt():
  # fetch the JSON data from the URL
  url = "https://raw.githubusercontent.com/ankit-rathi/Tradevesting_v1/main/data/myPortfolioAmts.json"
  response = requests.get(url)
  pf_amts = response.json()  # parse the JSON data

  # extract values from the JSON
  py_booked_amt_dm = pf_amts["py_booked_amt_dm"]
  py_booked_amt_sv = pf_amts["py_booked_amt_sv"]
  cy_booked_amt_dm = pf_amts["cy_booked_amt_dm"]
  cy_booked_amt_sv = pf_amts["cy_booked_amt_sv"]
  reserve_amt_dm = pf_amts["reserve_amt_dm"]
  reserve_amt_sv = pf_amts["reserve_amt_sv"]

  # perform calculations
  py_booked_amt = py_booked_amt_dm + py_booked_amt_sv
  cy_booked_amt = cy_booked_amt_dm + cy_booked_amt_sv
  reserve_amt = reserve_amt_dm + reserve_amt_sv
  total_booked_amt = py_booked_amt + cy_booked_amt

  return total_booked_amt, reserve_amt, cy_booked_amt, py_booked_amt

gen_output = 0

In [5]:
# function to format the amount
def format_amt(number):
    abs_number = abs(number)

    if abs_number >= 1_00_00_000:  # Crores
        formatted_amt = f"{number / 1_00_00_000:.2f} C"
    elif abs_number >= 1_00_000:  # Lakhs
        formatted_amt = f"{number / 1_00_000:.2f} L"
    elif abs_number >= 1_000:  # Thousands
        formatted_amt = f"{number / 1_000:.2f} K"
    else:
        formatted_amt = f"{number:.2f}"

    return formatted_amt

# function to set start and end date
def get_start_end_date():
  start_date = (datetime.date.today() + datetime.timedelta(days=-365)).strftime('%Y-%m-%d')
  end_date = (datetime.date.today() + datetime.timedelta(days=1)).strftime('%Y-%m-%d')
  return start_date, end_date

# function to fetch my portfolio csv
def get_mypfs_df():
  mypfs_df = pd.read_csv('https://raw.githubusercontent.com/ankit-rathi/Tradevesting_v1/main/data/myPortfolioStocks.csv')
  return mypfs_df

# function to fetch my prospects csv
def get_mypps_df():
  mypps_df = pd.read_csv('https://raw.githubusercontent.com/ankit-rathi/Tradevesting_v1/main/data/myProspectsScrips.csv')
  return mypps_df

# function to fetch screener data
def get_myscreen_df():
  myscreen_df = pd.read_csv('https://raw.githubusercontent.com/ankit-rathi/Tradevesting_v1/main/data/myScreenerDB.csv')
  return myscreen_df

# function to fetch momentum data
def get_myinvmt_df():
  myinvmt_df = pd.read_csv('https://raw.githubusercontent.com/ankit-rathi/Tradevesting_v1/main/data/myInvestments.csv')
  return myinvmt_df

# function to get the stock ids
def get_stock_ids(df_pf):
  stock_n100 = df_pf['Symbol'].unique()

  exclude = ['CADILAHC','MMTC', 'MASFIN']

  stock_ids = df_pf[~df_pf['Symbol'].isin(exclude) ]['Symbol'].unique()

  #mypf = mypf[mypf.Forecast.notnull()]
  #stock_ids = mypf['Symbol'].unique()

  #stock_ids.sort()
  return stock_ids

# get features from screener data
def get_screener_features():
  myscreen_df = get_myscreen_df()
  cols = ['Symbol', 'EPS', 'MedPE', 'ROCE%', 'ROE%', 'CapType']
  return myscreen_df[cols]

# get relative strength
def get_relative_strength(stock_list):

    # Dictionary to store stock tickers and their corresponding percentage price change
    stock_changes = {}

    # Loop through each stock and fetch its price data
    for stock in stock_list:
        try:
            # Download the stock data for the given date range
            stock_data = yfin.Ticker(stock + '.NS').history(period='1mo', interval='1d')[map(str.title, ['open', 'close', 'low', 'high', 'volume'])]

            # Calculate the percentage change for the stock
            if len(stock_data) > 0:
                start_price = stock_data['Close'].iloc[0]
                end_price = stock_data['Close'].iloc[-1]
                percent_change = round(((end_price - start_price) / start_price) * 100, 2)
                stock_changes[stock] = percent_change
            else:
                stock_changes[stock] = np.nan  # If no data is available, set to NaN

        except Exception as e:
            print(f"Error fetching data for {stock}: {e}")
            stock_changes[stock] = np.nan

    # Create a DataFrame with stock tickers and their percentage changes
    df = pd.DataFrame(list(stock_changes.items()), columns=['Symbol', 'Percent_Change'])

    # Drop any stocks with missing data (NaN values)
    df = df.dropna()

    # Calculate the percentile rank based on percentage change
    df['RSP'] = round(df['Percent_Change'].rank(pct=True) * 100, 2)
    cols = ['Symbol', 'RSP']
    df = df[cols]
    # Sort by percentile rank (optional)
    df = df.sort_values(by='RSP', ascending=False).reset_index(drop=True)

    return df

In [6]:
# function to get stock technicals
def stock_prec_dev(stock_symbol):
    #stock_symbol = 'ULTRACEMCO.NS'
    short_window = 20
    mid_window = 50
    long_window = 200
    moving_avg = 'SMA'

    start = datetime.datetime(*map(int, start_date.split('-')))
    end = datetime.datetime(*map(int, end_date.split('-')))

    stock_df = yfin.Ticker(stock_symbol + '.NS').history(period='max', interval='1d')[map(str.title, ['open', 'close', 'low', 'high', 'volume'])]

    stock_df['Max'] = round(max(stock_df['Close']),2)
    stock_df = stock_df[(stock_df.index <= end_date) & (stock_df.index >= start_date)]
    stock_df['200_SMA'] = round(stock_df['Close'].rolling(window = 200, min_periods = 1).mean(),0)
    stock_df['Dev%_200'] = round((stock_df['Close'] - stock_df['200_SMA'])*100/stock_df['200_SMA'],2)
    stock_df.dropna(axis = 0, inplace = True) # remove any null rows

    stock_df['20_SMA'] = stock_df['Close'].rolling(window=20).mean()
    stock_df['50_SMA'] = stock_df['Close'].rolling(window=50).mean()
    stock_df['Symbol'] = stock_symbol

    stock_df['Close'] = round(stock_df['Close'],2)
    stock_df['Min'] = round(min(stock_df['Close']),2)
    stock_df['RSI_14'] = ta.momentum.RSIIndicator(close=stock_df['Close'], window=14).rsi()
    stock_df['RSI_14'] = round(stock_df['RSI_14'],0)
    stock_df['Prev_Close'] = stock_df['Close'].shift(1)
    stock_df.drop(['Open', 'Low', 'High', 'Volume'], axis=1, inplace=True)
    stock_df = stock_df.tail(1)

    max_SMA = max(stock_df['20_SMA'].item(), stock_df['50_SMA'].item(), stock_df['200_SMA'].item())
    min_SMA = min(stock_df['20_SMA'].item(), stock_df['50_SMA'].item(), stock_df['200_SMA'].item())
    ABS_Spread = max_SMA - min_SMA
    stock_df['Spread%'] = round((ABS_Spread / stock_df['200_SMA'].item()) * 100,2)

    return stock_df

# function to compute stock attributes
def get_common_features(stock_ids, df_mypf):

  df_prec_dev = pd.DataFrame()
  df_tmp = get_screener_features()
  df_rs = get_relative_strength(stock_ids)

  for stock_id in stock_ids:
      tmp = stock_prec_dev(stock_id)
      tmp = tmp.reset_index()
      df_prec_dev = pd.concat([df_prec_dev, tmp], ignore_index = True)
  df_prec_dev = pd.merge(df_prec_dev, df_mypf, on= 'Symbol')
  df_prec_dev = pd.merge(df_prec_dev, df_tmp, on= 'Symbol', how='left')
  df_prec_dev = pd.merge(df_prec_dev, df_rs, on= 'Symbol', how='left')
  #print(df_prec_dev.columns)
  df_prec_dev['Curr_PE'] = round(df_prec_dev['Close']/df_prec_dev['EPS'],1)
  df_prec_dev['Dev%_PE'] = round((df_prec_dev['Curr_PE'] - df_prec_dev['MedPE'])*100/df_prec_dev['MedPE'],2)
  df_prec_dev['Conviction'] = df_prec_dev['Conviction'] + '-' + df_prec_dev['CapType']
  return df_prec_dev

# function to arrange stock features
def arrange_features(df_stocks, common_cols, diff_cols):
  df_stocks_common = df_stocks[common_cols].drop_duplicates()
  df_stocks_diff = df_stocks[diff_cols]
  df_stocks_diff['Investment'] = df_stocks_diff['AvgCost'] * df_stocks_diff['Shares']
  df_stocks_diff = df_stocks_diff.groupby(['Symbol'])[['Shares', 'Investment']].aggregate(['sum']).reset_index()
  df_stocks_diff.columns = ['Symbol', 'Shares', 'Investment']
  df_stocks_diff['AvgCost'] = round(df_stocks_diff['Investment']/df_stocks_diff['Shares'],2)
  df_stocks = pd.merge(df_stocks_diff, df_stocks_common, on='Symbol')
  return df_stocks

# plot fact distribution across dimension
def plot_pie_chart(df, dimension, fact):
  # grouping the data by category and calculating the sum of fact for each type
  grouped_data = df.groupby(dimension)[fact].sum()

  # sorting the grouped data in descending order
  grouped_data = grouped_data.sort_values(ascending=False)

  # creating a pie chart
  grouped_data.plot.pie(autopct='%1.1f%%', startangle=90, figsize=(6, 6))

  # adding a title and displaying the plot
  plt.title(f'{dimension} {fact} Distribution')
  plt.ylabel('')  # To hide the y-label
  plt.show()

In [7]:
# function to get portfolio features

def get_portfolio_features(df_common_features):

  print_date_time()
  print('-------------------')

  #df_common_features["Target"] = df_common_features["Target"].fillna(df_common_features["Max"])
  df_common_features['NTT'] = np.where(df_common_features['Strategy']== 'NTT', df_common_features["Target"], df_common_features['Max'])
  df_common_features['LTT'] = np.where(df_common_features['Strategy']== 'BTT', df_common_features["Target"], df_common_features['Max'])
  df_common_features['BOL'] = df_common_features['Min']

  tmp_df = df_common_features[df_common_features['Symbol'].isin(mypf_df[mypf_df['InPortfolio'] != 'NA'].Symbol.values)]
  print('qualified stocks: '+str(len(tmp_df['Symbol'].unique())))
  tmp_df1 = tmp_df[tmp_df['LatestQtr'] == 1]
  print('with latest results: '+str(len(tmp_df1['Symbol'].unique())))
  tmp_df1 = tmp_df1[tmp_df1['StarStock'] == 1]
  print('still star stocks: '+str(len(tmp_df1['Symbol'].unique())))
  tmp_df['Investment'] = tmp_df['AvgCost'] * tmp_df['Shares']
  tmp_df['Current'] = round(tmp_df['Close'] * tmp_df['Shares'],0)
  tmp_df['Previous'] = tmp_df['Prev_Close'] * tmp_df['Shares']
  tmp_df['EstimatedST'] = tmp_df['NTT'] * tmp_df['Shares']
  tmp_df['EstimatedLT'] = tmp_df['LTT'] * tmp_df['Shares']
  tmp_df['Current P/L'] = round((tmp_df['Current'] - tmp_df['Investment']),0)
  tmp_df['Today P/L%'] = round((tmp_df['Current'] - tmp_df['Previous'])*100/tmp_df['Previous'],2)
  tmp_df['Current P/L%'] = round((tmp_df['Current'] - tmp_df['Investment'])*100/tmp_df['Investment'],2)
  tmp_df['EstimatedST P/L%'] = round((tmp_df['EstimatedST'] - tmp_df['Investment'])*100/tmp_df['Investment'],2)
  tmp_df['EstimatedLT P/L%'] = round((tmp_df['EstimatedLT'] - tmp_df['Investment'])*100/tmp_df['Investment'],2)
  tmp_df['NTT%'] = round((tmp_df['NTT'] - tmp_df['Close'])*100/tmp_df['Close'],2)
  tmp_df['LTT%'] = round((tmp_df['LTT'] - tmp_df['Close'])*100/tmp_df['Close'],2)
  tmp_df['Gained%'] = round((tmp_df['Close'] - tmp_df['BOL'])*100/tmp_df['BOL'],2)
  investment = round(sum(tmp_df['AvgCost']*tmp_df['Shares']),0)
  current = round(sum(tmp_df['Close']*tmp_df['Shares']),0)
  tmp_df['InitAlloc%'] = round(tmp_df['Investment']*100/investment,2)
  tmp_df['CurrAlloc%'] = round(tmp_df['Current']*100/current,2)
  tmp_df['FTT'] = tmp_df['LTT']
  tmp_df.loc[tmp_df['Strategy'] == 'NTT', 'FTT'] = tmp_df['NTT']
  tmp_df['FTT%'] = tmp_df['LTT%']
  tmp_df.loc[tmp_df['Strategy'] == 'NTT', 'FTT%'] = tmp_df['NTT%']
  tmp_df['FTT Amt'] = round(tmp_df['FTT%'] * tmp_df['Current']/100,0)
  tmp_df['OTT%'] = round((tmp_df['FTT'] - tmp_df['AvgCost'])*100/tmp_df['AvgCost'],2)
  tmp_df['RRR Ind'] = round(tmp_df['Current P/L']/tmp_df['FTT Amt'],2)
  tmp_df['Risk Ind'] = round(tmp_df['Current P/L%']*tmp_df['CurrAlloc%'],0)

  return tmp_df

# function to print portfolio features
def print_portfolio_stats(df_portfolio_features, myinvmt_df):
  from pyxirr import xirr

  total_booked_amt, reserve_amt, cy_booked_amt, py_booked_amt = get_amt()

  dates = myinvmt_df['Date'].values
  dates = np.append(dates, datetime.date.today().strftime('%d-%b-%y'))
  investment = myinvmt_df['Investment'].values
  dates= pd.to_datetime(dates)

  current = round(sum(df_portfolio_features['Close']*df_portfolio_features['Shares']),0) + reserve_amt
  investment_xirr = np.append(investment, current)
  cagr = round(xirr(pd.DataFrame({"dates": dates, "amounts": investment_xirr}))*100,2)

  investment = -sum(investment)
  invested = round(sum(df_portfolio_features['AvgCost']*df_portfolio_features['Shares']),0) + reserve_amt
  previous = round(sum(df_portfolio_features['Prev_Close']*df_portfolio_features['Shares']),0) + reserve_amt
  cy_invested = investment + py_booked_amt

  today_pnl_amount = current-previous
  today_pnl_percentage = round((current-previous)*100/previous,2)

  curr_pnl_amount = current-invested
  curr_pnl_percentage = round((curr_pnl_amount)*100/(cy_invested),2)

  cy_pnl_amount = cy_booked_amt + curr_pnl_amount
  cy_pnl_percentage = round((cy_pnl_amount)*100/cy_invested,2)

  overall_pnl_amount = total_booked_amt + curr_pnl_amount
  overall_pnl_percentage = round((overall_pnl_amount)*100/investment,2)

  estimate_st = round(sum(df_portfolio_features['FTT']*df_portfolio_features['Shares']),0)  + reserve_amt
  est_st_pnl_amount = estimate_st-current
  est_st_pnl_percentage = round((est_st_pnl_amount)*100/current,2)

  estimate_lt = round(sum(df_portfolio_features['LTT']*df_portfolio_features['Shares']),0)  + reserve_amt
  est_lt_pnl_amount = estimate_lt-current
  est_lt_pnl_percentage = round((est_lt_pnl_amount)*100/current,2)

  total_profit = round(sum(df_portfolio_features[df_portfolio_features['Current P/L%'] > 0]['Current']) - sum(df_portfolio_features[df_portfolio_features['Current P/L%'] > 0]['Investment']),0)
  total_loss = round(sum(df_portfolio_features[df_portfolio_features['Current P/L%'] < 0]['Current']) - sum(df_portfolio_features[df_portfolio_features['Current P/L%'] < 0]['Investment']),0)

  cy_booked_percentage = round((cy_booked_amt)*100/current,2)
  py_booked_percentage = round((py_booked_amt)*100/investment,2)
  total_booked_percentage = round((total_booked_amt)*100/investment,2)

  print('-------------------')
  print('Initial Investment: ', format_amt(investment))
  print('CY Investment: ', format_amt(cy_invested))
  print('Reserve: ', format_amt(reserve_amt))
  print('Current: ',  format_amt(current))
  print('-------------------')
  print('Today PnL: '+ '{} ({}%)'.format(format_amt(today_pnl_amount), today_pnl_percentage))
  print('Current PnL: '+ '{} ({}%)'.format(format_amt(curr_pnl_amount), curr_pnl_percentage))
  print('CY Booked + Current PnL: '+ '{} ({}%)'.format(format_amt(cy_pnl_amount), cy_pnl_percentage))
  print('-------------------')
  print('Total profit: ', format_amt(total_profit))
  print('Total loss: ', format_amt(total_loss))
  print('-------------------')
  print('Total Booked + Current PnL: '+ '{} ({}%)'.format(format_amt(overall_pnl_amount), overall_pnl_percentage))
  print('Total Booked PnL: '+ '{} ({}%)'.format(format_amt(total_booked_amt), total_booked_percentage))
  print('Curr Year Booked PnL: '+ '{} ({}%)'.format(format_amt(cy_booked_amt), cy_booked_percentage))
  print('Prev Year Booked PnL: '+ '{} ({}%)'.format(format_amt(py_booked_amt), py_booked_percentage))
  print('===================')
  print('Est FTT: ',  format_amt(estimate_st))
  print('Est FTT PnL: '+ '{} ({}%)'.format(format_amt(est_st_pnl_amount), est_st_pnl_percentage))

  print('===================')
  print('Deployed: ', format_amt(investment))

  print('Current: ', format_amt(current))

  print('CAGR/XIRR %: '+'{}%'.format(cagr))

In [8]:
# get start and end date
start_date, end_date = get_start_end_date()

# get portfolio and prospects data
mypfs_df = get_mypfs_df()
mypps_df = get_mypps_df()
myinvmt_df = get_myinvmt_df()

# merge above datasets
mypf_df = pd.merge(mypfs_df, mypps_df, on="Symbol")

# seggregate dm and sv portfolio
dm_pf = mypf_df[mypf_df['InPortfolio'] == 'DM']
sv_pf = mypf_df[mypf_df['InPortfolio'] == 'SV']

# build portfolio stock dataframe
dm_stocks = get_stock_ids(dm_pf)
sv_stocks = get_stock_ids(sv_pf)
df_stocks = pd.concat([dm_pf,sv_pf], ignore_index = True)

# arrange common and diff stock features
common_cols = ['Symbol', 'Target', 'Criteria', 'Strategy', 'CumlRnk', 'LatestQtr', 'StarStock', 'Conviction', 'Category', 'InFolio', 'XIRR', 'MBQ']
diff_cols = ['Symbol', 'AvgCost', 'Shares']
df_stocks = arrange_features(df_stocks, common_cols, diff_cols)

# get common features
stock_ids = df_stocks['Symbol'].values
df_common_features = get_common_features(stock_ids, df_stocks)

df_common_features.reset_index(drop=True, inplace=True)
df_common_features.drop(['Date'], axis=1, inplace=True)
# get and print portfolio features
df_portfolio_features = get_portfolio_features(df_common_features)

print_portfolio_stats(df_portfolio_features, myinvmt_df)

df = df_portfolio_features
#plot_pie_chart(df, 'CapType', 'Current')
list_ox40n = list(df[df['MBQ'].str.contains('OX40N', na=False)]['Symbol'].values)

Run date time (IST): 2026-07-21 10:50:03
-------------------
qualified stocks: 92
with latest results: 31
still star stocks: 20
-------------------
Initial Investment:  1.40 C
CY Investment:  1.82 C
Reserve:  1.49 K
Current:  1.53 C
-------------------
Today PnL: 14.80 K (0.1%)
Current PnL: -30.28 L (-16.6%)
CY Booked + Current PnL: -28.20 L (-15.46%)
-------------------
Total profit:  4.65 L
Total loss:  -34.93 L
-------------------
Total Booked + Current PnL: 14.67 L (10.52%)
Total Booked PnL: 44.95 L (32.22%)
Curr Year Booked PnL: 2.08 L (1.36%)
Prev Year Booked PnL: 42.87 L (30.73%)
===================
Est FTT:  2.55 C
Est FTT PnL: 1.02 C (66.69%)
===================
Deployed:  1.40 C
Current:  1.53 C
CAGR/XIRR %: 4.13%

In [9]:
# top 5 near their targets
cols = ['Symbol', 'Today P/L%', 'Current P/L%', 'FTT%', 'OTT%', 'FTT Amt', 'Current P/L', 'Current', 'FTT', 'Dev%_PE', 'RSI_14','Conviction', 'Spread%',  'CumlRnk', 'RRR Ind', 'CurrAlloc%', 'Gained%', 'Criteria', 'Strategy', 'Category']
df_tmp = df_portfolio_features[~df_portfolio_features['Symbol'].isin(['ENRIN','BLUSPRING','DIGITIDE'])]
df_tmp = df_tmp.sort_values(by = 'FTT Amt', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
49,JSWINFRA,0.79,17.40,-0.83,16.43,-2161.0,38588.0,260362.0,342.00,0.56,65.0,X-MC,18.59,61.0,-17.86,1.70,47.62,X40N,NTT,REALTY
59,PIDILITIND,0.73,11.78,5.89,18.37,9290.0,16620.0,157730.0,1670.26,-21.72,54.0,X-LC,8.12,5.0,1.79,1.03,23.85,X40,ATH,CHEMICALS
73,SONACOMS,0.58,24.33,11.55,38.69,14527.0,24614.0,125773.0,801.69,-1.43,82.0,M-MC,24.38,193.0,1.69,0.82,78.44,AR,ATH,AUTO
83,TTKPRESTIG,-2.04,-14.37,16.89,0.09,14575.0,-14481.0,86296.0,770.00,100.21,65.0,M-SC,9.45,250.0,-0.99,0.56,53.66,OX40N,NTT,DURABLES
56,MEDANTA,2.30,15.24,10.30,27.12,20953.0,26910.0,203427.0,1486.00,11.76,61.0,X-SC,11.04,87.0,1.28,1.33,40.17,XY24,NTT,HEALTHCARE

In [10]:
# top 5 today
df_tmp = df_portfolio_features.sort_values(by = 'Today P/L%', ascending=False)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
62,RAJOOENG,6.81,-47.70,166.93,39.61,89491.0,-48890.0,53610.0,143.10,-64.67,57.0,H-SC,20.03,136.0,-0.55,0.35,14.85,AR,ATH,MISC
75,SURYODAY,3.94,6.45,15.58,23.03,29698.0,11547.0,190618.0,216.00,108.33,61.0,H-SC,22.34,166.0,0.39,1.25,61.80,XR,NTT,BANKS
11,BERGEPAINT,3.67,-5.68,32.86,25.32,79884.0,-14644.0,243105.0,680.00,-10.84,52.0,X-MC,1.82,68.0,-0.18,1.59,26.53,XY24,NTT,PAINTS
6,AWL,3.57,-32.46,147.28,67.02,354432.0,-115657.0,240652.0,485.00,-63.67,62.0,X-SC,13.08,81.0,-0.33,1.57,14.43,XY24,NTT,FMCG
55,MASFIN,3.41,-0.64,22.35,21.57,21758.0,-630.0,97350.0,397.04,-14.18,55.0,H-SC,1.23,167.0,-0.03,0.64,16.04,XR,ATH,FINANCE

In [11]:
# bottom 5 today
df_tmp = df_portfolio_features.sort_values(by = 'Today P/L%', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
64,RELAXO,-4.70,-46.06,182.35,52.31,142784.0,-66858.0,78302.0,1176.00,-42.60,59.0,X-SC,12.57,92.0,-0.47,0.51,75.07,X40N,NTT,FOOTWEAR
85,VAIBHAVGBL,-3.14,-21.67,105.25,60.77,150682.0,-39609.0,143166.0,521.00,65.29,59.0,H-SC,6.74,160.0,-0.26,0.94,45.66,XR,NTT,JEWELLERY
54,MARUTI,-3.12,-0.49,29.31,28.68,43113.0,-725.0,147092.0,17292.00,-18.07,43.0,X-LC,8.31,33.0,-0.02,0.96,9.54,XR,ATH,AUTO
77,TANLA,-2.82,-35.80,238.41,117.25,414411.0,-96938.0,173823.0,1922.32,-35.11,58.0,H-SC,3.35,147.0,-0.23,1.14,52.19,AR,ATH,IT
22,DIXON,-2.43,3.71,32.99,37.92,89226.0,9667.0,270465.0,18931.72,-55.89,67.0,X-MC,6.93,54.0,0.11,1.77,47.16,X40N,ATH,IT

In [12]:
# top 5 to exit based on CumlRnk
df_tmp = df_portfolio_features[~df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])]
df_tmp = df_tmp[(df_tmp['Current P/L%'] > -1) & (df_tmp['Current P/L%'] < 1)].sort_values(by = 'CumlRnk', ascending=False)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
55,MASFIN,3.41,-0.64,22.35,21.57,21758.0,-630.0,97350.0,397.04,-14.18,55.0,H-SC,1.23,167.0,-0.03,0.64,16.04,XR,ATH,FINANCE

In [13]:
# OX40N stocks to exit
df_tmp = df_portfolio_features[(df_portfolio_features['Symbol'].isin(list_ox40n))].sort_values(by = 'Current P/L%', ascending=False)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
25,FINCABLES,-0.72,27.92,62.53,107.91,118100.0,41226.0,188870.0,1641.55,15.17,39.0,M-SC,22.85,220.0,0.35,1.24,42.09,OX40N,ATH,CABLES
72,SIS,1.78,1.35,19.65,21.26,22113.0,1500.0,112532.0,528.00,2688.60,61.0,H-SC,24.91,168.0,0.07,0.74,67.32,OX40N,NTT,MISC
83,TTKPRESTIG,-2.04,-14.37,16.89,0.09,14575.0,-14481.0,86296.0,770.00,100.21,65.0,M-SC,9.45,250.0,-0.99,0.56,53.66,OX40N,NTT,DURABLES
16,CERA,1.18,-18.20,51.45,23.89,74030.0,-32015.0,143888.0,9475.00,-21.00,55.0,H-SC,15.08,153.0,-0.43,0.94,39.87,OX40N,NTT,CERAMICS
43,INDIGOPNTS,1.60,-23.13,30.12,0.02,40415.0,-40379.0,134180.0,1408.00,104.80,60.0,M-SC,3.64,222.0,-1.00,0.88,52.24,OX40N,NTT,PAINTS

In [14]:
# top 5 to book for rotation
df_tmp = df_portfolio_features[(df_portfolio_features['Current P/L%'] > 20) ].sort_values(by = 'CumlRnk', ascending=False)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
25,FINCABLES,-0.72,27.92,62.53,107.91,118100.0,41226.0,188870.0,1641.55,15.17,39.0,M-SC,22.85,220.0,0.35,1.24,42.09,OX40N,ATH,CABLES
73,SONACOMS,0.58,24.33,11.55,38.69,14527.0,24614.0,125773.0,801.69,-1.43,82.0,M-MC,24.38,193.0,1.69,0.82,78.44,AR,ATH,AUTO
68,SATIN,0.01,41.91,6.99,51.83,27406.0,115790.0,392074.0,274.00,27.46,55.0,H-SC,44.41,159.0,4.22,2.56,91.00,XY24,NTT,FINANCE
91,ZYDUSLIFE,-0.80,20.19,12.84,35.63,32343.0,42322.0,251896.0,1286.17,4.50,57.0,H-MC,17.13,120.0,1.31,1.65,32.44,AR,ATH,PHARMA
60,QUESS,1.10,22.30,42.19,73.90,55105.0,23819.0,130612.0,424.00,-34.44,71.0,X-SC,31.84,80.0,0.43,0.85,78.05,XY24,NTT,MISC

In [15]:
# top 5 to monitor for exit
df_tmp = df_portfolio_features[~df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])]
df_tmp = df_tmp[(df_tmp['Current P/L%'] > 0) ].sort_values(by = 'Dev%_PE', ascending=False)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
72,SIS,1.78,1.35,19.65,21.26,22113.0,1500.0,112532.0,528.0,2688.60,61.0,H-SC,24.91,168.0,0.07,0.74,67.32,OX40N,NTT,MISC
9,BANDHANBNK,0.38,2.97,86.86,92.42,249149.0,8281.0,286840.0,400.0,145.69,57.0,H-SC,20.27,174.0,0.03,1.88,58.01,XY24,NTT,BANKS
75,SURYODAY,3.94,6.45,15.58,23.03,29698.0,11547.0,190618.0,216.0,108.33,61.0,H-SC,22.34,166.0,0.39,1.25,61.80,XR,NTT,BANKS
74,STARHEALTH,-0.03,12.77,30.59,47.26,96975.0,35893.0,317016.0,761.0,78.03,54.0,H-SC,19.31,173.0,0.37,2.07,37.57,XY24,NTT,INSURANCE
68,SATIN,0.01,41.91,6.99,51.83,27406.0,115790.0,392074.0,274.0,27.46,55.0,H-SC,44.41,159.0,4.22,2.56,91.00,XY24,NTT,FINANCE

In [16]:
# top 5 to book for rotation from weak conviction
df_tmp = df_portfolio_features[~df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])]
df_tmp = df_tmp[~df_tmp['Criteria'].isin(['XY25','XY24','X40', 'X40N'])].sort_values(by = 'RRR Ind', ascending=False)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
73,SONACOMS,0.58,24.33,11.55,38.69,14527.0,24614.0,125773.0,801.69,-1.43,82.0,M-MC,24.38,193.0,1.69,0.82,78.44,AR,ATH,AUTO
91,ZYDUSLIFE,-0.80,20.19,12.84,35.63,32343.0,42322.0,251896.0,1286.17,4.50,57.0,H-MC,17.13,120.0,1.31,1.65,32.44,AR,ATH,PHARMA
75,SURYODAY,3.94,6.45,15.58,23.03,29698.0,11547.0,190618.0,216.00,108.33,61.0,H-SC,22.34,166.0,0.39,1.25,61.80,XR,NTT,BANKS
25,FINCABLES,-0.72,27.92,62.53,107.91,118100.0,41226.0,188870.0,1641.55,15.17,39.0,M-SC,22.85,220.0,0.35,1.24,42.09,OX40N,ATH,CABLES
72,SIS,1.78,1.35,19.65,21.26,22113.0,1500.0,112532.0,528.00,2688.60,61.0,H-SC,24.91,168.0,0.07,0.74,67.32,OX40N,NTT,MISC

In [17]:
# top 5 to accumulate based on lowest RSI_14
df_tmp = df_portfolio_features[df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])].sort_values(by = 'RSI_14', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
39,ICICIGI,0.24,-14.40,38.89,18.89,66617.0,-28813.0,171296.0,2244.41,-27.92,31.0,X-MC,5.23,66.0,-0.43,1.12,0.24,X40,ATH,INSURANCE
87,VBL,0.36,-5.12,42.68,35.37,127899.0,-16173.0,299669.0,670.16,-16.25,36.0,X-LC,7.78,13.0,-0.13,1.96,23.16,X40N,ATH,FMCG
58,PGHH,0.77,-34.15,100.47,32.01,141269.0,-72912.0,140608.0,17616.87,-55.45,39.0,X-MC,20.31,57.0,-0.52,0.92,0.77,X40,ATH,FMCG
81,TMPV,-0.79,-24.02,79.75,36.58,215626.0,-85463.0,270378.0,600.00,-84.72,39.0,X-LC,7.97,4.0,-0.40,1.77,13.63,XY24,NTT,AUTO
34,HDFCBANK,-1.26,-8.15,39.75,28.37,85761.0,-19133.0,215752.0,1073.00,-22.01,40.0,X-LC,10.99,26.0,-0.22,1.41,6.69,X40,BTT,BANKS

In [18]:
# top 5 to accumulate based on Spread and CumlRnk
df_tmp = df_portfolio_features[df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])]
df_tmp = df_tmp[(df_tmp['CumlRnk'] < 100)].sort_values(by = 'Spread%', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
11,BERGEPAINT,3.67,-5.68,32.86,25.32,79884.0,-14644.0,243105.0,680.00,-10.84,52.0,X-MC,1.82,68.0,-0.18,1.59,26.53,XY24,NTT,PAINTS
23,DMART,0.64,-4.40,35.56,29.60,84855.0,-10974.0,238626.0,5391.45,-19.43,40.0,X-LC,2.14,14.0,-0.13,1.56,9.07,X40N,ATH,FMCG
19,COLPAL,2.68,-20.37,75.64,39.86,158625.0,-53655.0,209710.0,3683.41,-3.61,59.0,X-MC,2.62,62.0,-0.34,1.37,18.62,XY25,ATH,FMCG
17,CIPLA,-1.08,15.45,15.58,33.43,27549.0,23663.0,176824.0,1648.14,-10.79,50.0,X-LC,3.16,18.0,0.86,1.16,20.71,X40N,ATH,PHARMA
1,ABBOTINDIA,1.25,-4.71,23.90,18.07,40733.0,-8425.0,170430.0,35195.00,-18.92,74.0,X-MC,3.58,58.0,-0.21,1.11,12.81,X40,ATH,PHARMA

In [19]:
# top 5 to accumulate based on lowest Gained%
df_tmp = df_portfolio_features[df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])].sort_values(by = 'Gained%', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
39,ICICIGI,0.24,-14.40,38.89,18.89,66617.0,-28813.0,171296.0,2244.41,-27.92,31.0,X-MC,5.23,66.0,-0.43,1.12,0.24,X40,ATH,INSURANCE
58,PGHH,0.77,-34.15,100.47,32.01,141269.0,-72912.0,140608.0,17616.87,-55.45,39.0,X-MC,20.31,57.0,-0.52,0.92,0.77,X40,ATH,FMCG
47,ITC,0.04,-25.51,59.83,19.06,151603.0,-86777.0,253389.0,452.00,-59.16,46.0,X-LC,12.62,1.0,-0.57,1.66,2.63,X40,NTT,FMCG
35,HDFCLIFE,-0.79,-8.54,45.10,32.71,61789.0,-12796.0,137004.0,811.41,-28.56,43.0,X-LC,15.22,31.0,-0.21,0.90,2.92,X40,ATH,INSURANCE
65,RELIANCE,-0.57,-15.55,48.37,25.30,82090.0,-31251.0,169712.0,1952.00,-17.72,52.0,X-LC,7.31,21.0,-0.38,1.11,4.51,XY25,BTT,REFINERIES

In [20]:
# top 5 to accumulate based on lowest CurrAlloc%
df_tmp = df_portfolio_features[df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])].sort_values(by = 'CurrAlloc%', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
10,BATAINDIA,-0.40,-54.99,200.42,35.20,116061.0,-70761.0,57909.0,2096.00,-24.04,52.0,X-SC,18.05,91.0,-0.61,0.38,14.85,X40,NTT,FOOTWEAR
64,RELAXO,-4.70,-46.06,182.35,52.31,142784.0,-66858.0,78302.0,1176.00,-42.60,59.0,X-SC,12.57,92.0,-0.47,0.51,75.07,X40N,NTT,FOOTWEAR
60,QUESS,1.10,22.30,42.19,73.90,55105.0,23819.0,130612.0,424.00,-34.44,71.0,X-SC,31.84,80.0,0.43,0.85,78.05,XY24,NTT,MISC
35,HDFCLIFE,-0.79,-8.54,45.10,32.71,61789.0,-12796.0,137004.0,811.41,-28.56,43.0,X-LC,15.22,31.0,-0.21,0.90,2.92,X40,ATH,INSURANCE
28,GODREJCP,-2.10,-6.09,39.99,31.47,55814.0,-9044.0,139570.0,1469.04,-1.14,49.0,X-LC,6.51,32.0,-0.16,0.91,7.09,X40N,ATH,FMCG

In [21]:
# top 5 to accumulate based on CumlRnk
df_tmp = df_portfolio_features.sort_values(by = 'CumlRnk', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
47,ITC,0.04,-25.51,59.83,19.06,151603.0,-86777.0,253389.0,452.00,-59.16,46.0,X-LC,12.62,1.0,-0.57,1.66,2.63,X40,NTT,FMCG
79,TCS,-1.08,-34.63,89.98,24.20,272512.0,-160415.0,302858.0,4230.71,-44.61,58.0,X-LC,20.13,2.0,-0.59,1.98,12.94,X40,ATH,IT
45,INFY,-1.49,-27.10,84.14,34.24,191925.0,-84786.0,228102.0,1972.00,-42.67,48.0,X-LC,20.93,3.0,-0.44,1.49,8.69,X40,NTT,IT
81,TMPV,-0.79,-24.02,79.75,36.58,215626.0,-85463.0,270378.0,600.00,-84.72,39.0,X-LC,7.97,4.0,-0.40,1.77,13.63,XY24,NTT,AUTO
59,PIDILITIND,0.73,11.78,5.89,18.37,9290.0,16620.0,157730.0,1670.26,-21.72,54.0,X-LC,8.12,5.0,1.79,1.03,23.85,X40,ATH,CHEMICALS

In [22]:
# top 5 for average up
df_tmp = df_portfolio_features[(df_portfolio_features['Dev%_200'] > 5)].sort_values(by = 'CurrAlloc%', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
44,INDUSINDBK,2.72,-22.10,70.59,32.89,42456.0,-17062.0,60144.0,1800.00,-382.91,72.0,L-MC,11.66,258.0,-0.40,0.39,48.28,XR,NTT,BANKS
64,RELAXO,-4.70,-46.06,182.35,52.31,142784.0,-66858.0,78302.0,1176.00,-42.60,59.0,X-SC,12.57,92.0,-0.47,0.51,75.07,X40N,NTT,FOOTWEAR
3,ALKYLAMINE,1.37,-21.13,144.12,92.54,114766.0,-21331.0,79632.0,4520.85,-15.57,53.0,H-SC,11.64,142.0,-0.19,0.52,51.21,SR,ATH,CHEMICALS
83,TTKPRESTIG,-2.04,-14.37,16.89,0.09,14575.0,-14481.0,86296.0,770.00,100.21,65.0,M-SC,9.45,250.0,-0.99,0.56,53.66,OX40N,NTT,DURABLES
72,SIS,1.78,1.35,19.65,21.26,22113.0,1500.0,112532.0,528.00,2688.60,61.0,H-SC,24.91,168.0,0.07,0.74,67.32,OX40N,NTT,MISC

In [23]:
# top 5 RSP
df_tmp = df_portfolio_features.sort_values(by = 'RSP', ascending=False)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
60,QUESS,1.10,22.30,42.19,73.90,55105.0,23819.0,130612.0,424.00,-34.44,71.0,X-SC,31.84,80.0,0.43,0.85,78.05,XY24,NTT,MISC
64,RELAXO,-4.70,-46.06,182.35,52.31,142784.0,-66858.0,78302.0,1176.00,-42.60,59.0,X-SC,12.57,92.0,-0.47,0.51,75.07,X40N,NTT,FOOTWEAR
83,TTKPRESTIG,-2.04,-14.37,16.89,0.09,14575.0,-14481.0,86296.0,770.00,100.21,65.0,M-SC,9.45,250.0,-0.99,0.56,53.66,OX40N,NTT,DURABLES
73,SONACOMS,0.58,24.33,11.55,38.69,14527.0,24614.0,125773.0,801.69,-1.43,82.0,M-MC,24.38,193.0,1.69,0.82,78.44,AR,ATH,AUTO
22,DIXON,-2.43,3.71,32.99,37.92,89226.0,9667.0,270465.0,18931.72,-55.89,67.0,X-MC,6.93,54.0,0.11,1.77,47.16,X40N,ATH,IT

In [24]:
# Top N allocation
df_tmp = df_portfolio_features.sort_values(by = 'CurrAlloc%', ascending=False)
top_n_values = [10, 25, 50]

sum_df = pd.DataFrame({
    'Top_N': top_n_values,
    'Sum_Alloc%': [df_tmp['CurrAlloc%'].head(n).sum() for n in top_n_values]
})

sum_df

   Top_N  Sum_Alloc%
0     10       19.33
1     25       42.66
2     50       72.76

In [25]:
# market-cap-wise allocation
df_tmp = df_portfolio_features[cols]
df_tmp.groupby(df_tmp['Conviction'].str[-2:])['CurrAlloc%'].sum().sort_values(ascending=False)

Conviction
SC    43.76
LC    29.96
MC    26.29
Name: CurrAlloc%, dtype: float64

In [26]:
# criteria-wise allocation
df_portfolio_features.groupby('Criteria')['CurrAlloc%'].sum().sort_values(ascending=False)

Criteria
XY24     27.75
X40      24.56
X40N     17.42
XR        8.85
OX40N     7.04
AR        6.99
XY25      6.51
SR        0.89
Name: CurrAlloc%, dtype: float64

In [27]:
# conviction-wise allocation
df_portfolio_features.groupby('Conviction')['CurrAlloc%'].sum().sort_values(ascending=False)

Conviction
X-LC    27.97
H-SC    23.11
X-MC    21.06
X-SC    10.20
M-SC     9.91
H-MC     2.72
M-MC     2.12
H-LC     1.19
M-LC     0.80
L-SC     0.54
L-MC     0.39
Name: CurrAlloc%, dtype: float64

In [28]:
# sector-wise stats
df_tmp = df_portfolio_features.groupby('Category')[['CurrAlloc%', 'Current', 'Current P/L', 'FTT Amt']].sum().sort_values(by=['Current', 'Current P/L'], ascending=False)
df_tmp['Current P/L%'] = round(df_tmp['Current P/L'] * 100 / df_tmp['Current'], 2)
df_tmp['FTT%'] = round(df_tmp['FTT Amt'] * 100 / df_tmp['Current'], 2)
cols = ['CurrAlloc%', 'Current P/L%', 'FTT%']
df_tmp[cols].sort_values(by=['CurrAlloc%'], ascending=False)

               CurrAlloc%  Current P/L%    FTT%
Category
FMCG                14.23        -21.61   64.26
FINANCE             11.23         -7.57   54.18
IT                  10.12        -45.70  117.80
MISC                 7.30        -20.12   71.66
AUTO                 6.59         -8.65   49.17
BANKS                5.86         -1.45   48.32
PAINTS               5.47        -17.83   37.93
PHARMA               5.22          7.09   21.66
INSURANCE            5.15         -5.23   40.73
ELECTRICAL           4.12        -12.21   51.68
CHEMICALS            2.15        -23.28   96.42
HEALTHCARE           2.08        -12.62   42.01
APPARELS             1.83          4.31   27.84
AC                   1.81        -15.04   46.24
FOOTWEAR             1.72        -67.65  134.87
REALTY               1.70         14.82   -0.83
DURABLES             1.62        -55.20   92.96
BREWERIES            1.57          2.60   17.63
TRAVEL               1.51        -94.77  192.30
CERAMICS             1.42        -41.52   84.51
ENGINEERING          1.27        -24.97   82.13
CABLES               1.24         21.83   62.53
REFINERIES           1.11        -18.41   48.37
CEMENT               1.09        -60.52  180.60
JEWELLERY            1.09        -92.78  159.76
ENTERTAINMENT        0.71        -76.51  181.79
TEXTILES             0.41        -48.10   90.33
HOTELS               0.39        -89.55  156.41

In [29]:
# money to be made criteria-wise
df_portfolio_features.groupby('Criteria')['FTT Amt'].agg(['sum', 'count']).sort_values(by='sum', ascending=False)

                sum  count
Criteria
XY24      3353241.0     21
X40       1916647.0     19
XR        1326689.0     13
AR        1106286.0      9
X40N      1056120.0     13
OX40N      715426.0     10
XY25       441375.0      5
SR         281231.0      2

In [30]:
# money to be made conviction-wise
df_portfolio_features.groupby('Conviction')['FTT Amt'].agg(['sum', 'count']).sort_values(by='sum', ascending=False)

                  sum  count
Conviction
H-SC        3242343.0     24
X-LC        1998738.0     21
X-MC        1496185.0     15
M-SC        1400631.0     14
X-SC        1242023.0      9
H-MC         283123.0      2
L-SC         208162.0      2
M-LC         170199.0      1
M-MC          61717.0      2
H-LC          51438.0      1
L-MC          42456.0      1

In [31]:
# money to be made criteria and conviction-wise
df_portfolio_features.groupby(['Conviction', 'Criteria'])['FTT Amt'].agg(['sum', 'count']).sort_values(by='sum', ascending=False)

                           sum  count
Conviction Criteria
X-LC       X40       1035883.0     10
H-SC       XY24       951526.0      6
           AR         931481.0      5
M-SC       XY24       824054.0      6
H-SC       XR         782844.0      7
X-SC       XY24       732164.0      4
X-MC       X40        670279.0      7
X-LC       X40N       395012.0      6
           XY24       363926.0      2
X-MC       X40N       361734.0      4
M-SC       OX40N      305699.0      5
X-SC       X40N       299374.0      3
H-SC       OX40N      295261.0      4
           SR         281231.0      2
H-MC       XY24       250780.0      1
X-MC       XY25       233381.0      2
           XY24       230791.0      2
X-SC       X40        210485.0      2
M-SC       XR         194381.0      2
M-LC       XR         170199.0      1
X-LC       XY25       160804.0      2
L-SC       OX40N      114466.0      1
           XR          93696.0      1
M-SC       AR          76497.0      1
H-LC       AR          51438.0      1
M-MC       XY25        47190.0      1
X-LC       XR          43113.0      1
L-MC       XR          42456.0      1
H-MC       AR          32343.0      1
M-MC       AR          14527.0      1

In [32]:
# notebook execution time

end_time = time.time()
execution_time = round(end_time - start_time, 0)
print(f"Notebook execution time: {execution_time} seconds")

Notebook execution time: 27.0 seconds