<a href="https://colab.research.google.com/github/ankit-rathi/Quantvesting_v2/blob/main/myStocks_Portfolio_Analysis.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
'''
!pip install pandas==2.2.2 -qq
!pip install pyxirr -qq
!pip install ta -qq
!pip install yfinance==0.2.59 -qq
'''

'\n!pip install pandas==2.2.2 -qq\n!pip install pyxirr -qq\n!pip install ta -qq\n!pip install yfinance==0.2.59 -qq\n'

In [2]:
# import libraries

import numpy as np
import pandas as pd
import datetime
import warnings
warnings.filterwarnings('ignore')
import yfinance as yfin
import ta
import matplotlib.pyplot as plt
import requests

In [3]:
# notebook start time
import time
import datetime
import pytz

start_time = time.time()

# function to print date timestamp
def print_date_time():
  tz_NY = pytz.timezone('Asia/Kolkata')
  datetime_NY = datetime.datetime.now(tz_NY)
  print("Run date time (IST):", datetime_NY.strftime("%Y-%m-%d %H:%M:%S"))

In [4]:
# function to get booked and reserved amount
def get_amt():
  # fetch the JSON data from the URL
  url = "https://raw.githubusercontent.com/ankit-rathi/Tradevesting_v1/main/data/myPortfolioAmts.json"
  response = requests.get(url)
  pf_amts = response.json()  # parse the JSON data

  # extract values from the JSON
  py_booked_amt_dm = pf_amts["py_booked_amt_dm"]
  py_booked_amt_sv = pf_amts["py_booked_amt_sv"]
  cy_booked_amt_dm = pf_amts["cy_booked_amt_dm"]
  cy_booked_amt_sv = pf_amts["cy_booked_amt_sv"]
  reserve_amt_dm = pf_amts["reserve_amt_dm"]
  reserve_amt_sv = pf_amts["reserve_amt_sv"]

  # perform calculations
  py_booked_amt = py_booked_amt_dm + py_booked_amt_sv
  cy_booked_amt = cy_booked_amt_dm + cy_booked_amt_sv
  reserve_amt = reserve_amt_dm + reserve_amt_sv
  total_booked_amt = py_booked_amt + cy_booked_amt

  return total_booked_amt, reserve_amt, cy_booked_amt, py_booked_amt

gen_output = 0

In [5]:
# function to format the amount
def format_amt(number):
    abs_number = abs(number)

    if abs_number >= 1_00_00_000:  # Crores
        formatted_amt = f"{number / 1_00_00_000:.2f} C"
    elif abs_number >= 1_00_000:  # Lakhs
        formatted_amt = f"{number / 1_00_000:.2f} L"
    elif abs_number >= 1_000:  # Thousands
        formatted_amt = f"{number / 1_000:.2f} K"
    else:
        formatted_amt = f"{number:.2f}"

    return formatted_amt

# function to set start and end date
def get_start_end_date():
  start_date = (datetime.date.today() + datetime.timedelta(days=-365)).strftime('%Y-%m-%d')
  end_date = (datetime.date.today() + datetime.timedelta(days=1)).strftime('%Y-%m-%d')
  return start_date, end_date

# function to fetch my portfolio csv
def get_mypfs_df():
  mypfs_df = pd.read_csv('https://raw.githubusercontent.com/ankit-rathi/Tradevesting_v1/main/data/myPortfolioStocks.csv')
  return mypfs_df

# function to fetch my prospects csv
def get_mypps_df():
  mypps_df = pd.read_csv('https://raw.githubusercontent.com/ankit-rathi/Tradevesting_v1/main/data/myProspectsScrips.csv')
  return mypps_df

# function to fetch screener data
def get_myscreen_df():
  myscreen_df = pd.read_csv('https://raw.githubusercontent.com/ankit-rathi/Tradevesting_v1/main/data/myScreenerDB.csv')
  return myscreen_df

# function to fetch momentum data
def get_myinvmt_df():
  myinvmt_df = pd.read_csv('https://raw.githubusercontent.com/ankit-rathi/Tradevesting_v1/main/data/myInvestments.csv')
  return myinvmt_df

# function to get the stock ids
def get_stock_ids(df_pf):
  stock_n100 = df_pf['Symbol'].unique()

  exclude = ['CADILAHC','MMTC', 'MASFIN']

  stock_ids = df_pf[~df_pf['Symbol'].isin(exclude) ]['Symbol'].unique()

  #mypf = mypf[mypf.Forecast.notnull()]
  #stock_ids = mypf['Symbol'].unique()

  #stock_ids.sort()
  return stock_ids

# get features from screener data
def get_screener_features():
  myscreen_df = get_myscreen_df()
  cols = ['Symbol', 'EPS', 'MedPE', 'ROCE%', 'ROE%', 'CapType']
  return myscreen_df[cols]

# get relative strength
def get_relative_strength(stock_list):

    # Dictionary to store stock tickers and their corresponding percentage price change
    stock_changes = {}

    # Loop through each stock and fetch its price data
    for stock in stock_list:
        try:
            # Download the stock data for the given date range
            stock_data = yfin.Ticker(stock + '.NS').history(period='1mo', interval='1d')[map(str.title, ['open', 'close', 'low', 'high', 'volume'])]

            # Calculate the percentage change for the stock
            if len(stock_data) > 0:
                start_price = stock_data['Close'].iloc[0]
                end_price = stock_data['Close'].iloc[-1]
                percent_change = round(((end_price - start_price) / start_price) * 100, 2)
                stock_changes[stock] = percent_change
            else:
                stock_changes[stock] = np.nan  # If no data is available, set to NaN

        except Exception as e:
            print(f"Error fetching data for {stock}: {e}")
            stock_changes[stock] = np.nan

    # Create a DataFrame with stock tickers and their percentage changes
    df = pd.DataFrame(list(stock_changes.items()), columns=['Symbol', 'Percent_Change'])

    # Drop any stocks with missing data (NaN values)
    df = df.dropna()

    # Calculate the percentile rank based on percentage change
    df['RSP'] = round(df['Percent_Change'].rank(pct=True) * 100, 2)
    cols = ['Symbol', 'RSP']
    df = df[cols]
    # Sort by percentile rank (optional)
    df = df.sort_values(by='RSP', ascending=False).reset_index(drop=True)

    return df

In [6]:
# function to get stock technicals
def stock_prec_dev(stock_symbol):
    #stock_symbol = 'ULTRACEMCO.NS'
    short_window = 20
    mid_window = 50
    long_window = 200
    moving_avg = 'SMA'

    start = datetime.datetime(*map(int, start_date.split('-')))
    end = datetime.datetime(*map(int, end_date.split('-')))

    stock_df = yfin.Ticker(stock_symbol + '.NS').history(period='max', interval='1d')[map(str.title, ['open', 'close', 'low', 'high', 'volume'])]

    stock_df['Max'] = round(max(stock_df['Close']),2)
    stock_df = stock_df[(stock_df.index <= end_date) & (stock_df.index >= start_date)]
    stock_df['200_SMA'] = round(stock_df['Close'].rolling(window = 200, min_periods = 1).mean(),0)
    stock_df['Dev%_200'] = round((stock_df['Close'] - stock_df['200_SMA'])*100/stock_df['200_SMA'],2)
    stock_df.dropna(axis = 0, inplace = True) # remove any null rows

    stock_df['20_SMA'] = stock_df['Close'].rolling(window=20).mean()
    stock_df['50_SMA'] = stock_df['Close'].rolling(window=50).mean()
    stock_df['Symbol'] = stock_symbol

    stock_df['Close'] = round(stock_df['Close'],2)
    stock_df['Min'] = round(min(stock_df['Close']),2)
    stock_df['RSI_14'] = ta.momentum.RSIIndicator(close=stock_df['Close'], window=14).rsi()
    stock_df['RSI_14'] = round(stock_df['RSI_14'],0)
    stock_df['Prev_Close'] = stock_df['Close'].shift(1)
    stock_df.drop(['Open', 'Low', 'High', 'Volume'], axis=1, inplace=True)
    stock_df = stock_df.tail(1)

    max_SMA = max(stock_df['20_SMA'].item(), stock_df['50_SMA'].item(), stock_df['200_SMA'].item())
    min_SMA = min(stock_df['20_SMA'].item(), stock_df['50_SMA'].item(), stock_df['200_SMA'].item())
    ABS_Spread = max_SMA - min_SMA
    stock_df['Spread%'] = round((ABS_Spread / stock_df['200_SMA'].item()) * 100,2)

    return stock_df

# function to compute stock attributes
def get_common_features(stock_ids, df_mypf):

  df_prec_dev = pd.DataFrame()
  df_tmp = get_screener_features()
  df_rs = get_relative_strength(stock_ids)

  for stock_id in stock_ids:
      tmp = stock_prec_dev(stock_id)
      tmp = tmp.reset_index()
      df_prec_dev = pd.concat([df_prec_dev, tmp], ignore_index = True)
  df_prec_dev = pd.merge(df_prec_dev, df_mypf, on= 'Symbol')
  df_prec_dev = pd.merge(df_prec_dev, df_tmp, on= 'Symbol', how='left')
  df_prec_dev = pd.merge(df_prec_dev, df_rs, on= 'Symbol', how='left')
  #print(df_prec_dev.columns)
  df_prec_dev['Curr_PE'] = round(df_prec_dev['Close']/df_prec_dev['EPS'],1)
  df_prec_dev['Dev%_PE'] = round((df_prec_dev['Curr_PE'] - df_prec_dev['MedPE'])*100/df_prec_dev['MedPE'],2)
  df_prec_dev['Conviction'] = df_prec_dev['Conviction'] + '-' + df_prec_dev['CapType']
  return df_prec_dev

# function to arrange stock features
def arrange_features(df_stocks, common_cols, diff_cols):
  df_stocks_common = df_stocks[common_cols].drop_duplicates()
  df_stocks_diff = df_stocks[diff_cols]
  df_stocks_diff['Investment'] = df_stocks_diff['AvgCost'] * df_stocks_diff['Shares']
  df_stocks_diff = df_stocks_diff.groupby(['Symbol'])[['Shares', 'Investment']].aggregate(['sum']).reset_index()
  df_stocks_diff.columns = ['Symbol', 'Shares', 'Investment']
  df_stocks_diff['AvgCost'] = round(df_stocks_diff['Investment']/df_stocks_diff['Shares'],2)
  df_stocks = pd.merge(df_stocks_diff, df_stocks_common, on='Symbol')
  return df_stocks

# plot fact distribution across dimension
def plot_pie_chart(df, dimension, fact):
  # grouping the data by category and calculating the sum of fact for each type
  grouped_data = df.groupby(dimension)[fact].sum()

  # sorting the grouped data in descending order
  grouped_data = grouped_data.sort_values(ascending=False)

  # creating a pie chart
  grouped_data.plot.pie(autopct='%1.1f%%', startangle=90, figsize=(6, 6))

  # adding a title and displaying the plot
  plt.title(f'{dimension} {fact} Distribution')
  plt.ylabel('')  # To hide the y-label
  plt.show()

In [7]:
# function to get portfolio features

def get_portfolio_features(df_common_features):

  print_date_time()
  print('-------------------')

  #df_common_features["Target"] = df_common_features["Target"].fillna(df_common_features["Max"])
  df_common_features['NTT'] = np.where(df_common_features['Strategy']== 'NTT', df_common_features["Target"], df_common_features['Max'])
  df_common_features['LTT'] = np.where(df_common_features['Strategy']== 'BTT', df_common_features["Target"], df_common_features['Max'])
  df_common_features['BOL'] = df_common_features['Min']

  tmp_df = df_common_features[df_common_features['Symbol'].isin(mypf_df[mypf_df['InPortfolio'] != 'NA'].Symbol.values)]
  print('qualified stocks: '+str(len(tmp_df['Symbol'].unique())))
  tmp_df1 = tmp_df[tmp_df['LatestQtr'] == 1]
  print('with latest results: '+str(len(tmp_df1['Symbol'].unique())))
  tmp_df1 = tmp_df1[tmp_df1['StarStock'] == 1]
  print('still star stocks: '+str(len(tmp_df1['Symbol'].unique())))
  tmp_df['Investment'] = tmp_df['AvgCost'] * tmp_df['Shares']
  tmp_df['Current'] = round(tmp_df['Close'] * tmp_df['Shares'],0)
  tmp_df['Previous'] = tmp_df['Prev_Close'] * tmp_df['Shares']
  tmp_df['EstimatedST'] = tmp_df['NTT'] * tmp_df['Shares']
  tmp_df['EstimatedLT'] = tmp_df['LTT'] * tmp_df['Shares']
  tmp_df['Current P/L'] = round((tmp_df['Current'] - tmp_df['Investment']),0)
  tmp_df['Today P/L%'] = round((tmp_df['Current'] - tmp_df['Previous'])*100/tmp_df['Previous'],2)
  tmp_df['Current P/L%'] = round((tmp_df['Current'] - tmp_df['Investment'])*100/tmp_df['Investment'],2)
  tmp_df['EstimatedST P/L%'] = round((tmp_df['EstimatedST'] - tmp_df['Investment'])*100/tmp_df['Investment'],2)
  tmp_df['EstimatedLT P/L%'] = round((tmp_df['EstimatedLT'] - tmp_df['Investment'])*100/tmp_df['Investment'],2)
  tmp_df['NTT%'] = round((tmp_df['NTT'] - tmp_df['Close'])*100/tmp_df['Close'],2)
  tmp_df['LTT%'] = round((tmp_df['LTT'] - tmp_df['Close'])*100/tmp_df['Close'],2)
  tmp_df['Gained%'] = round((tmp_df['Close'] - tmp_df['BOL'])*100/tmp_df['BOL'],2)
  investment = round(sum(tmp_df['AvgCost']*tmp_df['Shares']),0)
  current = round(sum(tmp_df['Close']*tmp_df['Shares']),0)
  tmp_df['InitAlloc%'] = round(tmp_df['Investment']*100/investment,2)
  tmp_df['CurrAlloc%'] = round(tmp_df['Current']*100/current,2)
  tmp_df['FTT'] = tmp_df['LTT']
  tmp_df.loc[tmp_df['Strategy'] == 'NTT', 'FTT'] = tmp_df['NTT']
  tmp_df['FTT%'] = tmp_df['LTT%']
  tmp_df.loc[tmp_df['Strategy'] == 'NTT', 'FTT%'] = tmp_df['NTT%']
  tmp_df['FTT Amt'] = round(tmp_df['FTT%'] * tmp_df['Current']/100,0)
  tmp_df['OTT%'] = round((tmp_df['FTT'] - tmp_df['AvgCost'])*100/tmp_df['AvgCost'],2)
  tmp_df['RRR Ind'] = round(tmp_df['Current P/L']/tmp_df['FTT Amt'],2)
  tmp_df['Risk Ind'] = round(tmp_df['Current P/L%']*tmp_df['CurrAlloc%'],0)

  return tmp_df

# function to print portfolio features
def print_portfolio_stats(df_portfolio_features, myinvmt_df):
  from pyxirr import xirr

  total_booked_amt, reserve_amt, cy_booked_amt, py_booked_amt = get_amt()

  dates = myinvmt_df['Date'].values
  dates = np.append(dates, datetime.date.today().strftime('%d-%b-%y'))
  investment = myinvmt_df['Investment'].values
  dates= pd.to_datetime(dates)

  current = round(sum(df_portfolio_features['Close']*df_portfolio_features['Shares']),0) + reserve_amt
  investment_xirr = np.append(investment, current)
  cagr = round(xirr(pd.DataFrame({"dates": dates, "amounts": investment_xirr}))*100,2)

  investment = -sum(investment)
  invested = round(sum(df_portfolio_features['AvgCost']*df_portfolio_features['Shares']),0) + reserve_amt
  previous = round(sum(df_portfolio_features['Prev_Close']*df_portfolio_features['Shares']),0) + reserve_amt
  cy_invested = investment + py_booked_amt

  today_pnl_amount = current-previous
  today_pnl_percentage = round((current-previous)*100/previous,2)

  curr_pnl_amount = current-invested
  curr_pnl_percentage = round((curr_pnl_amount)*100/(cy_invested),2)

  cy_pnl_amount = cy_booked_amt + curr_pnl_amount
  cy_pnl_percentage = round((cy_pnl_amount)*100/cy_invested,2)

  overall_pnl_amount = total_booked_amt + curr_pnl_amount
  overall_pnl_percentage = round((overall_pnl_amount)*100/investment,2)

  estimate_st = round(sum(df_portfolio_features['FTT']*df_portfolio_features['Shares']),0)  + reserve_amt
  est_st_pnl_amount = estimate_st-current
  est_st_pnl_percentage = round((est_st_pnl_amount)*100/current,2)

  estimate_lt = round(sum(df_portfolio_features['LTT']*df_portfolio_features['Shares']),0)  + reserve_amt
  est_lt_pnl_amount = estimate_lt-current
  est_lt_pnl_percentage = round((est_lt_pnl_amount)*100/current,2)

  total_profit = round(sum(df_portfolio_features[df_portfolio_features['Current P/L%'] > 0]['Current']) - sum(df_portfolio_features[df_portfolio_features['Current P/L%'] > 0]['Investment']),0)
  total_loss = round(sum(df_portfolio_features[df_portfolio_features['Current P/L%'] < 0]['Current']) - sum(df_portfolio_features[df_portfolio_features['Current P/L%'] < 0]['Investment']),0)

  cy_booked_percentage = round((cy_booked_amt)*100/current,2)
  py_booked_percentage = round((py_booked_amt)*100/investment,2)
  total_booked_percentage = round((total_booked_amt)*100/investment,2)

  print('-------------------')
  print('Initial Investment: ', format_amt(investment))
  print('CY Investment: ', format_amt(cy_invested))
  print('Reserve: ', format_amt(reserve_amt))
  print('Current: ',  format_amt(current))
  print('-------------------')
  print('Today PnL: '+ '{} ({}%)'.format(format_amt(today_pnl_amount), today_pnl_percentage))
  print('Current PnL: '+ '{} ({}%)'.format(format_amt(curr_pnl_amount), curr_pnl_percentage))
  print('CY Booked + Current PnL: '+ '{} ({}%)'.format(format_amt(cy_pnl_amount), cy_pnl_percentage))
  print('-------------------')
  print('Total profit: ', format_amt(total_profit))
  print('Total loss: ', format_amt(total_loss))
  print('-------------------')
  print('Total Booked + Current PnL: '+ '{} ({}%)'.format(format_amt(overall_pnl_amount), overall_pnl_percentage))
  print('Total Booked PnL: '+ '{} ({}%)'.format(format_amt(total_booked_amt), total_booked_percentage))
  print('Curr Year Booked PnL: '+ '{} ({}%)'.format(format_amt(cy_booked_amt), cy_booked_percentage))
  print('Prev Year Booked PnL: '+ '{} ({}%)'.format(format_amt(py_booked_amt), py_booked_percentage))
  print('===================')
  print('Est FTT: ',  format_amt(estimate_st))
  print('Est FTT PnL: '+ '{} ({}%)'.format(format_amt(est_st_pnl_amount), est_st_pnl_percentage))

  print('===================')
  print('Deployed: ', format_amt(investment))

  print('Current: ', format_amt(current))

  print('CAGR/XIRR %: '+'{}%'.format(cagr))

In [8]:
# get start and end date
start_date, end_date = get_start_end_date()

# get portfolio and prospects data
mypfs_df = get_mypfs_df()
mypps_df = get_mypps_df()
myinvmt_df = get_myinvmt_df()

# merge above datasets
mypf_df = pd.merge(mypfs_df, mypps_df, on="Symbol")

# seggregate dm and sv portfolio
dm_pf = mypf_df[mypf_df['InPortfolio'] == 'DM']
sv_pf = mypf_df[mypf_df['InPortfolio'] == 'SV']

# build portfolio stock dataframe
dm_stocks = get_stock_ids(dm_pf)
sv_stocks = get_stock_ids(sv_pf)
df_stocks = pd.concat([dm_pf,sv_pf], ignore_index = True)

# arrange common and diff stock features
common_cols = ['Symbol', 'Target', 'Criteria', 'Strategy', 'CumlRnk', 'LatestQtr', 'StarStock', 'Conviction', 'Category', 'InFolio', 'XIRR', 'MBQ']
diff_cols = ['Symbol', 'AvgCost', 'Shares']
df_stocks = arrange_features(df_stocks, common_cols, diff_cols)

# get common features
stock_ids = df_stocks['Symbol'].values
df_common_features = get_common_features(stock_ids, df_stocks)

df_common_features.reset_index(drop=True, inplace=True)
df_common_features.drop(['Date'], axis=1, inplace=True)
# get and print portfolio features
df_portfolio_features = get_portfolio_features(df_common_features)

print_portfolio_stats(df_portfolio_features, myinvmt_df)

df = df_portfolio_features
#plot_pie_chart(df, 'CapType', 'Current')
list_ox40n = list(df[df['MBQ'].str.contains('OX40N', na=False)]['Symbol'].values)

Run date time (IST): 2026-08-07 16:03:37
-------------------
qualified stocks: 88
with latest results: 30
still star stocks: 19
-------------------
Initial Investment:  1.46 C
CY Investment:  1.89 C
Reserve:  2.24 L
Current:  1.62 C
-------------------
Today PnL: -42.60 K (-0.26%)
Current PnL: -30.50 L (-16.15%)
CY Booked + Current PnL: -26.28 L (-13.91%)
-------------------
Total profit:  3.60 L
Total loss:  -34.10 L
-------------------
Total Booked + Current PnL: 16.59 L (11.36%)
Total Booked PnL: 47.09 L (32.24%)
Curr Year Booked PnL: 4.22 L (2.61%)
Prev Year Booked PnL: 42.87 L (29.35%)
===================
Est FTT:  2.67 C
Est FTT PnL: 1.05 C (65.03%)
===================
Deployed:  1.46 C
Current:  1.62 C
CAGR/XIRR %: 4.67%

In [9]:
# top 5 near their targets
cols = ['Symbol', 'Today P/L%', 'Current P/L%', 'FTT%', 'OTT%', 'FTT Amt', 'Current P/L', 'Current', 'FTT', 'Dev%_PE', 'RSI_14','Conviction', 'Spread%',  'CumlRnk', 'RRR Ind', 'CurrAlloc%', 'Gained%', 'Criteria', 'Strategy', 'Category']
df_tmp = df_portfolio_features[~df_portfolio_features['Symbol'].isin(['ENRIN','BLUSPRING','DIGITIDE'])]
df_tmp = df_tmp.sort_values(by = 'FTT Amt', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
55,MEDANTA,0.78,24.52,2.09,27.12,4594.0,43279.0,219796.0,1486.00,20.64,68.0,X-SC,15.09,87.0,9.42,1.38,51.45,XY24,NTT,HEALTHCARE
52,M&M,2.82,10.58,7.45,18.82,19828.0,25471.0,266152.0,3762.88,-3.65,69.0,X-LC,5.71,25.0,1.28,1.67,20.73,X40N,ATH,AUTO
79,TTKPRESTIG,-3.27,-19.93,25.01,0.09,20180.0,-20088.0,80689.0,770.00,87.19,45.0,M-SC,13.83,250.0,-1.00,0.51,45.23,OX40N,NTT,DURABLES
80,UNITDSPR,-0.83,11.10,8.70,20.77,22632.0,25989.0,260133.0,1644.00,-1.54,69.0,X-MC,7.14,64.0,1.15,1.63,25.04,X40N,NTT,BREWERIES
69,SIS,-0.22,-0.11,21.39,21.26,23724.0,-120.0,110912.0,528.00,2648.19,55.0,H-SC,23.02,168.0,-0.01,0.70,64.91,OX40N,NTT,MISC

In [10]:
# top 5 today
df_tmp = df_portfolio_features.sort_values(by = 'Today P/L%', ascending=False)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
82,VALIANTORG,3.52,-40.04,190.47,74.15,186832.0,-65515.0,98090.0,838.00,-276.54,59.0,H-SC,4.32,145.0,-0.35,0.62,45.97,XR,NTT,CHEMICALS
75,TCS,3.36,-28.00,72.49,24.20,241803.0,-129706.0,333567.0,4230.71,-39.04,63.0,X-LC,15.70,2.0,-0.54,2.09,24.39,X40,ATH,IT
52,M&M,2.82,10.58,7.45,18.82,19828.0,25471.0,266152.0,3762.88,-3.65,69.0,X-LC,5.71,25.0,1.28,1.67,20.73,X40N,ATH,AUTO
14,CAMPUS,2.45,-23.91,75.16,33.28,95955.0,-40108.0,127667.0,393.00,-38.69,49.0,M-SC,10.18,218.0,-0.42,0.80,4.41,XY24,NTT,FOOTWEAR
12,BOSCH-HCIL,2.26,-26.28,35.64,-0.01,33578.0,-33591.0,94214.0,2282.00,19182.61,85.0,M-SC,3.97,231.0,-1.00,0.59,60.37,OX40N,BTT,AC

In [11]:
# bottom 5 today
df_tmp = df_portfolio_features.sort_values(by = 'Today P/L%', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
18,COFFEEDAY,-4.99,-45.21,146.91,35.27,91390.0,-51341.0,62208.0,80.0,-57.75,52.0,L-SC,5.27,266.0,-0.56,0.39,53.41,XR,NTT,HOTELS
29,GREENPANEL,-4.95,-48.76,179.32,43.14,168234.0,-89260.0,93818.0,537.0,109.95,47.0,M-SC,11.23,225.0,-0.53,0.59,12.99,XY24,NTT,MISC
16,CERA,-4.15,-20.74,56.30,23.89,78497.0,-36477.0,139426.0,9475.0,-23.63,45.0,H-SC,12.98,153.0,-0.46,0.87,35.53,OX40N,NTT,CERAMICS
79,TTKPRESTIG,-3.27,-19.93,25.01,0.09,20180.0,-20088.0,80689.0,770.0,87.19,45.0,M-SC,13.83,250.0,-1.00,0.51,45.23,OX40N,NTT,DURABLES
66,SFL,-2.82,-33.35,89.99,26.63,157275.0,-87449.0,174769.0,1287.0,32.32,34.0,M-SC,24.63,242.0,-0.56,1.10,45.86,XY24,NTT,MISC

In [12]:
# top 5 to exit based on CumlRnk
df_tmp = df_portfolio_features[~df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])]
df_tmp = df_tmp[(df_tmp['Current P/L%'] > -1) & (df_tmp['Current P/L%'] < 1)].sort_values(by = 'CumlRnk', ascending=False)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
5,ATULAUTO,-0.46,-0.50,46.30,45.57,90816.0,-986.0,196146.0,844.0,4267.57,76.0,M-SC,9.33,248.0,-0.01,1.23,50.94,XY24,NTT,AUTO
61,RECLTD,1.52,-0.65,21.53,20.74,43458.0,-1320.0,201850.0,446.0,9.37,58.0,M-MC,3.42,191.0,-0.03,1.27,21.67,XY25,NTT,FINANCE
69,SIS,-0.22,-0.11,21.39,21.26,23724.0,-120.0,110912.0,528.0,2648.19,55.0,H-SC,23.02,168.0,-0.01,0.70,64.91,OX40N,NTT,MISC

In [13]:
# OX40N stocks to exit
df_tmp = df_portfolio_features[(df_portfolio_features['Symbol'].isin(list_ox40n))].sort_values(by = 'Current P/L%', ascending=False)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
25,FINCABLES,-0.98,29.78,60.21,107.91,115368.0,43966.0,191610.0,1641.55,16.69,50.0,M-SC,17.71,220.0,0.38,1.20,44.15,OX40N,ATH,CABLES
69,SIS,-0.22,-0.11,21.39,21.26,23724.0,-120.0,110912.0,528.00,2648.19,55.0,H-SC,23.02,168.0,-0.01,0.70,64.91,OX40N,NTT,MISC
79,TTKPRESTIG,-3.27,-19.93,25.01,0.09,20180.0,-20088.0,80689.0,770.00,87.19,45.0,M-SC,13.83,250.0,-1.00,0.51,45.23,OX40N,NTT,DURABLES
43,INDIGOPNTS,-0.72,-20.40,25.66,0.02,35653.0,-35617.0,138942.0,1408.00,112.05,63.0,M-SC,4.73,222.0,-1.00,0.87,57.64,OX40N,NTT,PAINTS
16,CERA,-4.15,-20.74,56.30,23.89,78497.0,-36477.0,139426.0,9475.00,-23.63,45.0,H-SC,12.98,153.0,-0.46,0.87,35.53,OX40N,NTT,CERAMICS

In [14]:
# top 5 to book for rotation
df_tmp = df_portfolio_features[(df_portfolio_features['Current P/L%'] > 20) ].sort_values(by = 'CumlRnk', ascending=False)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
25,FINCABLES,-0.98,29.78,60.21,107.91,115368.0,43966.0,191610.0,1641.55,16.69,50.0,M-SC,17.71,220.0,0.38,1.20,44.15,OX40N,ATH,CABLES
55,MEDANTA,0.78,24.52,2.09,27.12,4594.0,43279.0,219796.0,1486.00,20.64,68.0,X-SC,15.09,87.0,9.42,1.38,51.45,XY24,NTT,HEALTHCARE
58,QUESS,-0.38,27.57,36.31,73.90,49469.0,29447.0,136240.0,424.00,-31.13,59.0,X-SC,39.49,80.0,0.60,0.85,87.52,XY24,NTT,MISC

In [15]:
# top 5 to monitor for exit
df_tmp = df_portfolio_features[~df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])]
df_tmp = df_tmp[(df_tmp['Current P/L%'] > 0) ].sort_values(by = 'Dev%_PE', ascending=False)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
70,STARHEALTH,-0.66,10.27,33.54,47.26,103973.0,28875.0,309998.0,761.00,74.08,43.0,H-SC,17.61,173.0,0.28,1.95,34.04,XY24,NTT,INSURANCE
25,FINCABLES,-0.98,29.78,60.21,107.91,115368.0,43966.0,191610.0,1641.55,16.69,50.0,M-SC,17.71,220.0,0.38,1.20,44.15,OX40N,ATH,CABLES
87,ZYDUSLIFE,0.56,17.49,15.33,35.51,37748.0,36664.0,246238.0,1285.01,2.25,49.0,H-MC,15.83,120.0,0.97,1.55,29.58,AR,ATH,PHARMA

In [16]:
# top 5 to book for rotation from weak conviction
df_tmp = df_portfolio_features[~df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])]
df_tmp = df_tmp[~df_tmp['Criteria'].isin(['XY25','XY24','X40', 'X40N'])].sort_values(by = 'RRR Ind', ascending=False)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
87,ZYDUSLIFE,0.56,17.49,15.33,35.51,37748.0,36664.0,246238.0,1285.01,2.25,49.0,H-MC,15.83,120.0,0.97,1.55,29.58,AR,ATH,PHARMA
25,FINCABLES,-0.98,29.78,60.21,107.91,115368.0,43966.0,191610.0,1641.55,16.69,50.0,M-SC,17.71,220.0,0.38,1.20,44.15,OX40N,ATH,CABLES
69,SIS,-0.22,-0.11,21.39,21.26,23724.0,-120.0,110912.0,528.00,2648.19,55.0,H-SC,23.02,168.0,-0.01,0.70,64.91,OX40N,NTT,MISC
3,ALKYLAMINE,-1.46,-19.34,138.71,92.54,112963.0,-19525.0,81438.0,4520.85,-13.57,56.0,H-SC,13.69,142.0,-0.17,0.51,54.64,SR,ATH,CHEMICALS
42,INDIAMART,-0.48,-24.58,166.42,100.92,154796.0,-30321.0,93015.0,4675.60,-66.02,35.0,H-SC,11.94,140.0,-0.20,0.58,0.69,AR,ATH,MISC

In [17]:
# top 5 to accumulate based on lowest RSI_14
df_tmp = df_portfolio_features[df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])].sort_values(by = 'RSI_14', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
34,HDFCBANK,-0.45,-10.72,46.79,31.05,122448.0,-31422.0,261698.0,1073.00,-25.47,35.0,X-LC,10.58,26.0,-0.26,1.64,1.58,X40,BTT,BANKS
57,PGHH,0.15,-36.33,107.33,32.01,145917.0,-77568.0,135952.0,17616.87,-56.92,35.0,X-MC,19.20,57.0,-0.53,0.85,0.24,X40,ATH,FMCG
83,VBL,-0.45,-10.43,51.45,35.66,162143.0,-36698.0,315146.0,669.42,-21.22,38.0,X-LC,7.75,13.0,-0.23,1.98,16.03,X40N,ATH,FMCG
20,DABUR,-0.32,-19.84,79.27,43.70,157628.0,-49218.0,198850.0,735.00,-27.23,38.0,X-MC,8.96,70.0,-0.31,1.25,1.19,XY24,BTT,FMCG
35,HDFCLIFE,-0.46,-7.39,50.26,39.15,116704.0,-18537.0,232200.0,811.41,-31.02,40.0,X-LC,15.97,31.0,-0.16,1.46,0.76,X40,ATH,INSURANCE

In [18]:
# top 5 to accumulate based on Spread and CumlRnk
df_tmp = df_portfolio_features[df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])]
df_tmp = df_tmp[(df_tmp['CumlRnk'] < 100)].sort_values(by = 'Spread%', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
19,COLPAL,0.08,-22.92,81.45,39.86,165344.0,-60365.0,203000.0,3683.41,-6.75,45.0,X-MC,1.66,62.0,-0.37,1.27,14.83,XY25,ATH,FMCG
11,BERGEPAINT,-1.31,-2.23,28.17,25.32,70991.0,-5738.0,252011.0,680.00,-7.53,60.0,X-MC,1.96,68.0,-0.08,1.58,32.15,XY24,NTT,PAINTS
8,BAJAJHLDNG,-1.09,1.19,26.73,28.24,69244.0,3044.0,259049.0,14274.15,-6.72,61.0,X-LC,2.57,28.0,0.04,1.63,30.38,X40,ATH,FINANCE
23,DMART,-0.79,-4.94,38.24,31.42,113343.0,-15390.0,296400.0,5391.45,-20.94,41.0,X-LC,3.11,14.0,-0.14,1.86,6.96,X40N,ATH,FMCG
26,GILLETTE,-0.14,-9.21,42.89,29.72,98864.0,-23391.0,230505.0,10978.86,-30.15,45.0,X-SC,3.41,83.0,-0.24,1.45,5.93,X40,ATH,FMCG

In [19]:
# top 5 to accumulate based on lowest Gained%
df_tmp = df_portfolio_features[df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])].sort_values(by = 'Gained%', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
57,PGHH,0.15,-36.33,107.33,32.01,145917.0,-77568.0,135952.0,17616.87,-56.92,35.0,X-MC,19.20,57.0,-0.53,0.85,0.24,X40,ATH,FMCG
35,HDFCLIFE,-0.46,-7.39,50.26,39.15,116704.0,-18537.0,232200.0,811.41,-31.02,40.0,X-LC,15.97,31.0,-0.16,1.46,0.76,X40,ATH,INSURANCE
20,DABUR,-0.32,-19.84,79.27,43.70,157628.0,-49218.0,198850.0,735.00,-27.23,38.0,X-MC,8.96,70.0,-0.31,1.25,1.19,XY24,BTT,FMCG
34,HDFCBANK,-0.45,-10.72,46.79,31.05,122448.0,-31422.0,261698.0,1073.00,-25.47,35.0,X-LC,10.58,26.0,-0.26,1.64,1.58,X40,BTT,BANKS
39,ICICIGI,-1.15,-13.18,36.94,18.89,64177.0,-26375.0,173734.0,2244.41,-26.94,42.0,X-MC,9.32,66.0,-0.41,1.09,3.50,X40,ATH,INSURANCE

In [20]:
# top 5 to accumulate based on lowest CurrAlloc%
df_tmp = df_portfolio_features[df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])].sort_values(by = 'CurrAlloc%', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
10,BATAINDIA,-1.04,-53.52,190.91,35.20,114168.0,-68868.0,59802.0,2096.00,-21.59,61.0,X-SC,14.41,91.0,-0.60,0.38,20.15,X40,NTT,FOOTWEAR
62,RELAXO,-0.49,-45.16,177.72,52.31,141481.0,-65551.0,79609.0,1176.00,-41.63,60.0,X-SC,11.35,92.0,-0.46,0.50,77.99,X40N,NTT,FOOTWEAR
58,QUESS,-0.38,27.57,36.31,73.90,49469.0,29447.0,136240.0,424.00,-31.13,59.0,X-SC,39.49,80.0,0.60,0.85,87.52,XY24,NTT,MISC
57,PGHH,0.15,-36.33,107.33,32.01,145917.0,-77568.0,135952.0,17616.87,-56.92,35.0,X-MC,19.20,57.0,-0.53,0.85,0.24,X40,ATH,FMCG
40,ICICIPRULI,-1.17,-17.09,57.12,30.28,93301.0,-33663.0,163342.0,787.27,-39.37,47.0,X-MC,13.70,78.0,-0.36,1.02,8.83,X40,ATH,INSURANCE

In [21]:
# top 5 to accumulate based on CumlRnk
df_tmp = df_portfolio_features.sort_values(by = 'CumlRnk', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
47,ITC,0.07,-21.07,57.99,24.70,181837.0,-83712.0,313566.0,452.00,-58.75,52.0,X-LC,11.58,1.0,-0.46,1.97,3.83,X40,NTT,FMCG
75,TCS,3.36,-28.00,72.49,24.20,241803.0,-129706.0,333567.0,4230.71,-39.04,63.0,X-LC,15.70,2.0,-0.54,2.09,24.39,X40,ATH,IT
45,INFY,0.87,-16.35,67.82,40.38,213583.0,-61543.0,314927.0,1972.00,-37.23,62.0,X-LC,16.36,3.0,-0.29,1.98,19.26,X40,NTT,IT
77,TMPV,0.48,-17.44,72.91,42.75,250468.0,-72577.0,343530.0,600.00,-83.62,55.0,X-LC,5.38,4.0,-0.29,2.16,18.12,XY24,NTT,AUTO
33,HCLTECH,1.62,-9.26,36.62,23.97,102835.0,-28670.0,280816.0,1853.42,-7.36,69.0,X-LC,13.57,8.0,-0.28,1.76,32.51,X40,ATH,IT

In [22]:
# top 5 for average up
df_tmp = df_portfolio_features[(df_portfolio_features['Dev%_200'] > 5)].sort_values(by = 'CurrAlloc%', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
44,INDUSINDBK,0.57,-24.55,76.13,32.89,44349.0,-18952.0,58254.0,1800.00,-374.51,56.0,L-MC,14.10,258.0,-0.43,0.37,43.62,XR,NTT,BANKS
62,RELAXO,-0.49,-45.16,177.72,52.31,141481.0,-65551.0,79609.0,1176.00,-41.63,60.0,X-SC,11.35,92.0,-0.46,0.50,77.99,X40N,NTT,FOOTWEAR
3,ALKYLAMINE,-1.46,-19.34,138.71,92.54,112963.0,-19525.0,81438.0,4520.85,-13.57,56.0,H-SC,13.69,142.0,-0.17,0.51,54.64,SR,ATH,CHEMICALS
79,TTKPRESTIG,-3.27,-19.93,25.01,0.09,20180.0,-20088.0,80689.0,770.00,87.19,45.0,M-SC,13.83,250.0,-1.00,0.51,45.23,OX40N,NTT,DURABLES
12,BOSCH-HCIL,2.26,-26.28,35.64,-0.01,33578.0,-33591.0,94214.0,2282.00,19182.61,85.0,M-SC,3.97,231.0,-1.00,0.59,60.37,OX40N,BTT,AC

In [23]:
# top 5 RSP
df_tmp = df_portfolio_features.sort_values(by = 'RSP', ascending=False)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
12,BOSCH-HCIL,2.26,-26.28,35.64,-0.01,33578.0,-33591.0,94214.0,2282.00,19182.61,85.0,M-SC,3.97,231.0,-1.00,0.59,60.37,OX40N,BTT,AC
30,HAPPSTMNDS,0.38,-49.10,259.71,83.08,169414.0,-62933.0,65232.0,1466.54,-39.56,68.0,H-SC,10.64,152.0,-0.37,0.41,22.18,AR,ATH,IT
75,TCS,3.36,-28.00,72.49,24.20,241803.0,-129706.0,333567.0,4230.71,-39.04,63.0,X-LC,15.70,2.0,-0.54,2.09,24.39,X40,ATH,IT
33,HCLTECH,1.62,-9.26,36.62,23.97,102835.0,-28670.0,280816.0,1853.42,-7.36,69.0,X-LC,13.57,8.0,-0.28,1.76,32.51,X40,ATH,IT
5,ATULAUTO,-0.46,-0.50,46.30,45.57,90816.0,-986.0,196146.0,844.00,4267.57,76.0,M-SC,9.33,248.0,-0.01,1.23,50.94,XY24,NTT,AUTO

In [24]:
# Top N allocation
df_tmp = df_portfolio_features.sort_values(by = 'CurrAlloc%', ascending=False)
top_n_values = [10, 25, 50]

sum_df = pd.DataFrame({
    'Top_N': top_n_values,
    'Sum_Alloc%': [df_tmp['CurrAlloc%'].head(n).sum() for n in top_n_values]
})

sum_df

   Top_N  Sum_Alloc%
0     10       19.71
1     25       44.68
2     50       76.89

In [25]:
# market-cap-wise allocation
df_tmp = df_portfolio_features[cols]
df_tmp.groupby(df_tmp['Conviction'].str[-2:])['CurrAlloc%'].sum().sort_values(ascending=False)

Conviction
SC    39.31
LC    37.76
MC    22.96
Name: CurrAlloc%, dtype: float64

In [26]:
# criteria-wise allocation
df_portfolio_features.groupby('Criteria')['CurrAlloc%'].sum().sort_values(ascending=False)

Criteria
X40      26.42
XY24     25.05
X40N     18.45
XR        9.12
XY25      7.30
OX40N     6.83
AR        6.02
SR        0.84
Name: CurrAlloc%, dtype: float64

In [27]:
# conviction-wise allocation
df_portfolio_features.groupby('Conviction')['CurrAlloc%'].sum().sort_values(ascending=False)

Conviction
X-LC    35.70
H-SC    19.19
X-MC    18.71
X-SC     9.93
M-SC     9.66
H-MC     2.61
M-MC     1.27
H-LC     1.24
M-LC     0.82
L-SC     0.53
L-MC     0.37
Name: CurrAlloc%, dtype: float64

In [28]:
# sector-wise stats
df_tmp = df_portfolio_features.groupby('Category')[['CurrAlloc%', 'Current', 'Current P/L', 'FTT Amt']].sum().sort_values(by=['Current', 'Current P/L'], ascending=False)
df_tmp['Current P/L%'] = round(df_tmp['Current P/L'] * 100 / df_tmp['Current'], 2)
df_tmp['FTT%'] = round(df_tmp['FTT Amt'] * 100 / df_tmp['Current'], 2)
cols = ['CurrAlloc%', 'Current P/L%', 'FTT%']
df_tmp[cols].sort_values(by=['CurrAlloc%'], ascending=False)

               CurrAlloc%  Current P/L%    FTT%
Category
FMCG                15.49        -20.85   64.38
IT                  11.22        -33.27   99.41
FINANCE              9.30        -15.26   63.70
AUTO                 8.45         -0.59   36.61
MISC                 6.85        -22.69   75.34
BANKS                6.07        -10.38   57.99
PHARMA               5.60          6.92   19.47
INSURANCE            5.52         -5.65   43.01
PAINTS               5.40        -14.44   33.97
ELECTRICAL           4.13         -7.60   45.27
HEALTHCARE           2.08         -8.14   36.36
AC                   1.80        -11.35   41.55
APPARELS             1.75          3.91   28.36
REFINERIES           1.71         -9.47   46.24
FOOTWEAR             1.68        -65.35  131.65
BREWERIES            1.63          9.99    8.70
DURABLES             1.52        -60.34   99.35
TRAVEL               1.46        -91.40  187.24
CERAMICS             1.34        -43.41   86.97
ENGINEERING          1.21        -25.34   82.67
CABLES               1.20         22.95   60.21
CHEMICALS            1.13        -47.37  166.99
CEMENT               1.03        -63.96  186.62
JEWELLERY            1.00       -101.01  170.85
ENTERTAINMENT        0.68        -76.95  182.49
HOTELS               0.39        -82.53  146.91
TEXTILES             0.39        -48.33   90.63

In [29]:
# money to be made criteria-wise
df_portfolio_features.groupby('Criteria')['FTT Amt'].agg(['sum', 'count']).sort_values(by='sum', ascending=False)

                sum  count
Criteria
XY24      3410671.0     20
X40       2016225.0     18
XR        1345803.0     13
X40N      1142552.0     12
AR        1073264.0      8
OX40N      703540.0     10
XY25       536016.0      5
SR         281740.0      2

In [30]:
# money to be made conviction-wise
df_portfolio_features.groupby('Conviction')['FTT Amt'].agg(['sum', 'count']).sort_values(by='sum', ascending=False)

                  sum  count
Conviction
H-SC        3292470.0     23
X-LC        2373773.0     20
X-MC        1470506.0     14
M-SC        1378224.0     14
X-SC        1221600.0      9
H-MC         281935.0      2
L-SC         206514.0      2
M-LC         161561.0      1
L-MC          44349.0      1
M-MC          43458.0      1
H-LC          35421.0      1

In [31]:
# money to be made criteria and conviction-wise
df_portfolio_features.groupby(['Conviction', 'Criteria'])['FTT Amt'].agg(['sum', 'count']).sort_values(by='sum', ascending=False)

                           sum  count
Conviction Criteria
X-LC       X40       1158267.0      9
H-SC       XY24       986070.0      5
           AR         923809.0      5
M-SC       XY24       821355.0      6
H-SC       XR         802621.0      7
X-SC       XY24       712017.0      4
X-MC       X40        644926.0      7
X-LC       X40N       500042.0      6
           XY24       418423.0      2
X-MC       X40N       345959.0      3
H-SC       OX40N      298230.0      4
X-SC       X40N       296551.0      3
M-SC       OX40N      290186.0      5
H-SC       SR         281740.0      2
X-MC       XY25       251002.0      2
H-MC       XY24       244187.0      1
X-LC       XY25       241556.0      2
X-MC       XY24       228619.0      2
X-SC       X40        213032.0      2
M-SC       XR         190397.0      2
M-LC       XR         161561.0      1
L-SC       OX40N      115124.0      1
           XR          91390.0      1
M-SC       AR          76286.0      1
X-LC       XR          55485.0      1
L-MC       XR          44349.0      1
M-MC       XY25        43458.0      1
H-MC       AR          37748.0      1
H-LC       AR          35421.0      1

In [32]:
# notebook execution time

end_time = time.time()
execution_time = round(end_time - start_time, 0)
print(f"Notebook execution time: {execution_time} seconds")

Notebook execution time: 25.0 seconds