<a href="https://colab.research.google.com/github/ankit-rathi/Quantvesting_v2/blob/main/myStocks_Portfolio_Analysis.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
'''
!pip install pandas==2.2.2 -qq
!pip install pyxirr -qq
!pip install ta -qq
!pip install yfinance==0.2.59 -qq
'''

'\n!pip install pandas==2.2.2 -qq\n!pip install pyxirr -qq\n!pip install ta -qq\n!pip install yfinance==0.2.59 -qq\n'

In [2]:
# import libraries

import numpy as np
import pandas as pd
import datetime
import warnings
warnings.filterwarnings('ignore')
import yfinance as yfin
import ta
import matplotlib.pyplot as plt
import requests

In [3]:
# notebook start time
import time
import datetime
import pytz

start_time = time.time()

# function to print date timestamp
def print_date_time():
  tz_NY = pytz.timezone('Asia/Kolkata')
  datetime_NY = datetime.datetime.now(tz_NY)
  print("Run date time (IST):", datetime_NY.strftime("%Y-%m-%d %H:%M:%S"))

In [4]:
# function to get booked and reserved amount
def get_amt():
  # fetch the JSON data from the URL
  url = "https://raw.githubusercontent.com/ankit-rathi/Tradevesting_v1/main/data/myPortfolioAmts.json"
  response = requests.get(url)
  pf_amts = response.json()  # parse the JSON data

  # extract values from the JSON
  py_booked_amt_dm = pf_amts["py_booked_amt_dm"]
  py_booked_amt_sv = pf_amts["py_booked_amt_sv"]
  cy_booked_amt_dm = pf_amts["cy_booked_amt_dm"]
  cy_booked_amt_sv = pf_amts["cy_booked_amt_sv"]
  reserve_amt_dm = pf_amts["reserve_amt_dm"]
  reserve_amt_sv = pf_amts["reserve_amt_sv"]

  # perform calculations
  py_booked_amt = py_booked_amt_dm + py_booked_amt_sv
  cy_booked_amt = cy_booked_amt_dm + cy_booked_amt_sv
  reserve_amt = reserve_amt_dm + reserve_amt_sv
  total_booked_amt = py_booked_amt + cy_booked_amt

  return total_booked_amt, reserve_amt, cy_booked_amt, py_booked_amt

gen_output = 0

In [5]:
# function to format the amount
def format_amt(number):
    abs_number = abs(number)

    if abs_number >= 1_00_00_000:  # Crores
        formatted_amt = f"{number / 1_00_00_000:.2f} C"
    elif abs_number >= 1_00_000:  # Lakhs
        formatted_amt = f"{number / 1_00_000:.2f} L"
    elif abs_number >= 1_000:  # Thousands
        formatted_amt = f"{number / 1_000:.2f} K"
    else:
        formatted_amt = f"{number:.2f}"

    return formatted_amt

# function to set start and end date
def get_start_end_date():
  start_date = (datetime.date.today() + datetime.timedelta(days=-365)).strftime('%Y-%m-%d')
  end_date = (datetime.date.today() + datetime.timedelta(days=1)).strftime('%Y-%m-%d')
  return start_date, end_date

# function to fetch my portfolio csv
def get_mypfs_df():
  mypfs_df = pd.read_csv('https://raw.githubusercontent.com/ankit-rathi/Tradevesting_v1/main/data/myPortfolioStocks.csv')
  return mypfs_df

# function to fetch my prospects csv
def get_mypps_df():
  mypps_df = pd.read_csv('https://raw.githubusercontent.com/ankit-rathi/Tradevesting_v1/main/data/myProspectsScrips.csv')
  return mypps_df

# function to fetch screener data
def get_myscreen_df():
  myscreen_df = pd.read_csv('https://raw.githubusercontent.com/ankit-rathi/Tradevesting_v1/main/data/myScreenerDB.csv')
  return myscreen_df

# function to fetch momentum data
def get_myinvmt_df():
  myinvmt_df = pd.read_csv('https://raw.githubusercontent.com/ankit-rathi/Tradevesting_v1/main/data/myInvestments.csv')
  return myinvmt_df

# function to get the stock ids
def get_stock_ids(df_pf):
  stock_n100 = df_pf['Symbol'].unique()

  exclude = ['CADILAHC','MMTC', 'MASFIN']

  stock_ids = df_pf[~df_pf['Symbol'].isin(exclude) ]['Symbol'].unique()

  #mypf = mypf[mypf.Forecast.notnull()]
  #stock_ids = mypf['Symbol'].unique()

  #stock_ids.sort()
  return stock_ids

# get features from screener data
def get_screener_features():
  myscreen_df = get_myscreen_df()
  cols = ['Symbol', 'EPS', 'MedPE', 'ROCE%', 'ROE%', 'CapType']
  return myscreen_df[cols]

# get relative strength
def get_relative_strength(stock_list):

    # Dictionary to store stock tickers and their corresponding percentage price change
    stock_changes = {}

    # Loop through each stock and fetch its price data
    for stock in stock_list:
        try:
            # Download the stock data for the given date range
            stock_data = yfin.Ticker(stock + '.NS').history(period='1mo', interval='1d')[map(str.title, ['open', 'close', 'low', 'high', 'volume'])]

            # Calculate the percentage change for the stock
            if len(stock_data) > 0:
                start_price = stock_data['Close'].iloc[0]
                end_price = stock_data['Close'].iloc[-1]
                percent_change = round(((end_price - start_price) / start_price) * 100, 2)
                stock_changes[stock] = percent_change
            else:
                stock_changes[stock] = np.nan  # If no data is available, set to NaN

        except Exception as e:
            print(f"Error fetching data for {stock}: {e}")
            stock_changes[stock] = np.nan

    # Create a DataFrame with stock tickers and their percentage changes
    df = pd.DataFrame(list(stock_changes.items()), columns=['Symbol', 'Percent_Change'])

    # Drop any stocks with missing data (NaN values)
    df = df.dropna()

    # Calculate the percentile rank based on percentage change
    df['RSP'] = round(df['Percent_Change'].rank(pct=True) * 100, 2)
    cols = ['Symbol', 'RSP']
    df = df[cols]
    # Sort by percentile rank (optional)
    df = df.sort_values(by='RSP', ascending=False).reset_index(drop=True)

    return df

In [6]:
# function to get stock technicals
def stock_prec_dev(stock_symbol):
    #stock_symbol = 'ULTRACEMCO.NS'
    short_window = 20
    mid_window = 50
    long_window = 200
    moving_avg = 'SMA'

    start = datetime.datetime(*map(int, start_date.split('-')))
    end = datetime.datetime(*map(int, end_date.split('-')))

    stock_df = yfin.Ticker(stock_symbol + '.NS').history(period='max', interval='1d')[map(str.title, ['open', 'close', 'low', 'high', 'volume'])]

    stock_df['Max'] = round(max(stock_df['Close']),2)
    stock_df = stock_df[(stock_df.index <= end_date) & (stock_df.index >= start_date)]
    stock_df['200_SMA'] = round(stock_df['Close'].rolling(window = 200, min_periods = 1).mean(),0)
    stock_df['Dev%_200'] = round((stock_df['Close'] - stock_df['200_SMA'])*100/stock_df['200_SMA'],2)
    stock_df.dropna(axis = 0, inplace = True) # remove any null rows

    stock_df['20_SMA'] = stock_df['Close'].rolling(window=20).mean()
    stock_df['50_SMA'] = stock_df['Close'].rolling(window=50).mean()
    stock_df['Symbol'] = stock_symbol

    stock_df['Close'] = round(stock_df['Close'],2)
    stock_df['Min'] = round(min(stock_df['Close']),2)
    stock_df['RSI_14'] = ta.momentum.RSIIndicator(close=stock_df['Close'], window=14).rsi()
    stock_df['RSI_14'] = round(stock_df['RSI_14'],0)
    stock_df['Prev_Close'] = stock_df['Close'].shift(1)
    stock_df.drop(['Open', 'Low', 'High', 'Volume'], axis=1, inplace=True)
    stock_df = stock_df.tail(1)

    max_SMA = max(stock_df['20_SMA'].item(), stock_df['50_SMA'].item(), stock_df['200_SMA'].item())
    min_SMA = min(stock_df['20_SMA'].item(), stock_df['50_SMA'].item(), stock_df['200_SMA'].item())
    ABS_Spread = max_SMA - min_SMA
    stock_df['Spread%'] = round((ABS_Spread / stock_df['200_SMA'].item()) * 100,2)

    return stock_df

# function to compute stock attributes
def get_common_features(stock_ids, df_mypf):

  df_prec_dev = pd.DataFrame()
  df_tmp = get_screener_features()
  df_rs = get_relative_strength(stock_ids)

  for stock_id in stock_ids:
      tmp = stock_prec_dev(stock_id)
      tmp = tmp.reset_index()
      df_prec_dev = pd.concat([df_prec_dev, tmp], ignore_index = True)
  df_prec_dev = pd.merge(df_prec_dev, df_mypf, on= 'Symbol')
  df_prec_dev = pd.merge(df_prec_dev, df_tmp, on= 'Symbol', how='left')
  df_prec_dev = pd.merge(df_prec_dev, df_rs, on= 'Symbol', how='left')
  #print(df_prec_dev.columns)
  df_prec_dev['Curr_PE'] = round(df_prec_dev['Close']/df_prec_dev['EPS'],1)
  df_prec_dev['Dev%_PE'] = round((df_prec_dev['Curr_PE'] - df_prec_dev['MedPE'])*100/df_prec_dev['MedPE'],2)
  df_prec_dev['Conviction'] = df_prec_dev['Conviction'] + '-' + df_prec_dev['CapType']
  return df_prec_dev

# function to arrange stock features
def arrange_features(df_stocks, common_cols, diff_cols):
  df_stocks_common = df_stocks[common_cols].drop_duplicates()
  df_stocks_diff = df_stocks[diff_cols]
  df_stocks_diff['Investment'] = df_stocks_diff['AvgCost'] * df_stocks_diff['Shares']
  df_stocks_diff = df_stocks_diff.groupby(['Symbol'])[['Shares', 'Investment']].aggregate(['sum']).reset_index()
  df_stocks_diff.columns = ['Symbol', 'Shares', 'Investment']
  df_stocks_diff['AvgCost'] = round(df_stocks_diff['Investment']/df_stocks_diff['Shares'],2)
  df_stocks = pd.merge(df_stocks_diff, df_stocks_common, on='Symbol')
  return df_stocks

# plot fact distribution across dimension
def plot_pie_chart(df, dimension, fact):
  # grouping the data by category and calculating the sum of fact for each type
  grouped_data = df.groupby(dimension)[fact].sum()

  # sorting the grouped data in descending order
  grouped_data = grouped_data.sort_values(ascending=False)

  # creating a pie chart
  grouped_data.plot.pie(autopct='%1.1f%%', startangle=90, figsize=(6, 6))

  # adding a title and displaying the plot
  plt.title(f'{dimension} {fact} Distribution')
  plt.ylabel('')  # To hide the y-label
  plt.show()

In [7]:
# function to get portfolio features

def get_portfolio_features(df_common_features):

  print_date_time()
  print('-------------------')

  #df_common_features["Target"] = df_common_features["Target"].fillna(df_common_features["Max"])
  df_common_features['NTT'] = np.where(df_common_features['Strategy']== 'NTT', df_common_features["Target"], df_common_features['Max'])
  df_common_features['LTT'] = np.where(df_common_features['Strategy']== 'BTT', df_common_features["Target"], df_common_features['Max'])
  df_common_features['BOL'] = df_common_features['Min']

  tmp_df = df_common_features[df_common_features['Symbol'].isin(mypf_df[mypf_df['InPortfolio'] != 'NA'].Symbol.values)]
  print('qualified stocks: '+str(len(tmp_df['Symbol'].unique())))
  tmp_df1 = tmp_df[tmp_df['LatestQtr'] == 1]
  print('with latest results: '+str(len(tmp_df1['Symbol'].unique())))
  tmp_df1 = tmp_df1[tmp_df1['StarStock'] == 1]
  print('still star stocks: '+str(len(tmp_df1['Symbol'].unique())))
  tmp_df['Investment'] = tmp_df['AvgCost'] * tmp_df['Shares']
  tmp_df['Current'] = round(tmp_df['Close'] * tmp_df['Shares'],0)
  tmp_df['Previous'] = tmp_df['Prev_Close'] * tmp_df['Shares']
  tmp_df['EstimatedST'] = tmp_df['NTT'] * tmp_df['Shares']
  tmp_df['EstimatedLT'] = tmp_df['LTT'] * tmp_df['Shares']
  tmp_df['Current P/L'] = round((tmp_df['Current'] - tmp_df['Investment']),0)
  tmp_df['Today P/L%'] = round((tmp_df['Current'] - tmp_df['Previous'])*100/tmp_df['Previous'],2)
  tmp_df['Current P/L%'] = round((tmp_df['Current'] - tmp_df['Investment'])*100/tmp_df['Investment'],2)
  tmp_df['EstimatedST P/L%'] = round((tmp_df['EstimatedST'] - tmp_df['Investment'])*100/tmp_df['Investment'],2)
  tmp_df['EstimatedLT P/L%'] = round((tmp_df['EstimatedLT'] - tmp_df['Investment'])*100/tmp_df['Investment'],2)
  tmp_df['NTT%'] = round((tmp_df['NTT'] - tmp_df['Close'])*100/tmp_df['Close'],2)
  tmp_df['LTT%'] = round((tmp_df['LTT'] - tmp_df['Close'])*100/tmp_df['Close'],2)
  tmp_df['Gained%'] = round((tmp_df['Close'] - tmp_df['BOL'])*100/tmp_df['BOL'],2)
  investment = round(sum(tmp_df['AvgCost']*tmp_df['Shares']),0)
  current = round(sum(tmp_df['Close']*tmp_df['Shares']),0)
  tmp_df['InitAlloc%'] = round(tmp_df['Investment']*100/investment,2)
  tmp_df['CurrAlloc%'] = round(tmp_df['Current']*100/current,2)
  tmp_df['FTT'] = tmp_df['LTT']
  tmp_df.loc[tmp_df['Strategy'] == 'NTT', 'FTT'] = tmp_df['NTT']
  tmp_df['FTT%'] = tmp_df['LTT%']
  tmp_df.loc[tmp_df['Strategy'] == 'NTT', 'FTT%'] = tmp_df['NTT%']
  tmp_df['FTT Amt'] = round(tmp_df['FTT%'] * tmp_df['Current']/100,0)
  tmp_df['OTT%'] = round((tmp_df['FTT'] - tmp_df['AvgCost'])*100/tmp_df['AvgCost'],2)
  tmp_df['RRR Ind'] = round(tmp_df['Current P/L']/tmp_df['FTT Amt'],2)
  tmp_df['Risk Ind'] = round(tmp_df['Current P/L%']*tmp_df['CurrAlloc%'],0)

  return tmp_df

# function to print portfolio features
def print_portfolio_stats(df_portfolio_features, myinvmt_df):
  from pyxirr import xirr

  total_booked_amt, reserve_amt, cy_booked_amt, py_booked_amt = get_amt()

  dates = myinvmt_df['Date'].values
  dates = np.append(dates, datetime.date.today().strftime('%d-%b-%y'))
  investment = myinvmt_df['Investment'].values
  dates= pd.to_datetime(dates)

  current = round(sum(df_portfolio_features['Close']*df_portfolio_features['Shares']),0) + reserve_amt
  investment_xirr = np.append(investment, current)
  cagr = round(xirr(pd.DataFrame({"dates": dates, "amounts": investment_xirr}))*100,2)

  investment = -sum(investment)
  invested = round(sum(df_portfolio_features['AvgCost']*df_portfolio_features['Shares']),0) + reserve_amt
  previous = round(sum(df_portfolio_features['Prev_Close']*df_portfolio_features['Shares']),0) + reserve_amt
  cy_invested = investment + py_booked_amt

  today_pnl_amount = current-previous
  today_pnl_percentage = round((current-previous)*100/previous,2)

  curr_pnl_amount = current-invested
  curr_pnl_percentage = round((curr_pnl_amount)*100/(cy_invested),2)

  cy_pnl_amount = cy_booked_amt + curr_pnl_amount
  cy_pnl_percentage = round((cy_pnl_amount)*100/cy_invested,2)

  overall_pnl_amount = total_booked_amt + curr_pnl_amount
  overall_pnl_percentage = round((overall_pnl_amount)*100/investment,2)

  estimate_st = round(sum(df_portfolio_features['FTT']*df_portfolio_features['Shares']),0)  + reserve_amt
  est_st_pnl_amount = estimate_st-current
  est_st_pnl_percentage = round((est_st_pnl_amount)*100/current,2)

  estimate_lt = round(sum(df_portfolio_features['LTT']*df_portfolio_features['Shares']),0)  + reserve_amt
  est_lt_pnl_amount = estimate_lt-current
  est_lt_pnl_percentage = round((est_lt_pnl_amount)*100/current,2)

  total_profit = round(sum(df_portfolio_features[df_portfolio_features['Current P/L%'] > 0]['Current']) - sum(df_portfolio_features[df_portfolio_features['Current P/L%'] > 0]['Investment']),0)
  total_loss = round(sum(df_portfolio_features[df_portfolio_features['Current P/L%'] < 0]['Current']) - sum(df_portfolio_features[df_portfolio_features['Current P/L%'] < 0]['Investment']),0)

  cy_booked_percentage = round((cy_booked_amt)*100/current,2)
  py_booked_percentage = round((py_booked_amt)*100/investment,2)
  total_booked_percentage = round((total_booked_amt)*100/investment,2)

  print('-------------------')
  print('Initial Investment: ', format_amt(investment))
  print('CY Investment: ', format_amt(cy_invested))
  print('Reserve: ', format_amt(reserve_amt))
  print('Current: ',  format_amt(current))
  print('-------------------')
  print('Today PnL: '+ '{} ({}%)'.format(format_amt(today_pnl_amount), today_pnl_percentage))
  print('Current PnL: '+ '{} ({}%)'.format(format_amt(curr_pnl_amount), curr_pnl_percentage))
  print('CY Booked + Current PnL: '+ '{} ({}%)'.format(format_amt(cy_pnl_amount), cy_pnl_percentage))
  print('-------------------')
  print('Total profit: ', format_amt(total_profit))
  print('Total loss: ', format_amt(total_loss))
  print('-------------------')
  print('Total Booked + Current PnL: '+ '{} ({}%)'.format(format_amt(overall_pnl_amount), overall_pnl_percentage))
  print('Total Booked PnL: '+ '{} ({}%)'.format(format_amt(total_booked_amt), total_booked_percentage))
  print('Curr Year Booked PnL: '+ '{} ({}%)'.format(format_amt(cy_booked_amt), cy_booked_percentage))
  print('Prev Year Booked PnL: '+ '{} ({}%)'.format(format_amt(py_booked_amt), py_booked_percentage))
  print('===================')
  print('Est FTT: ',  format_amt(estimate_st))
  print('Est FTT PnL: '+ '{} ({}%)'.format(format_amt(est_st_pnl_amount), est_st_pnl_percentage))

  print('===================')
  print('Deployed: ', format_amt(investment))

  print('Current: ', format_amt(current))

  print('CAGR/XIRR %: '+'{}%'.format(cagr))

In [8]:
# get start and end date
start_date, end_date = get_start_end_date()

# get portfolio and prospects data
mypfs_df = get_mypfs_df()
mypps_df = get_mypps_df()
myinvmt_df = get_myinvmt_df()

# merge above datasets
mypf_df = pd.merge(mypfs_df, mypps_df, on="Symbol")

# seggregate dm and sv portfolio
dm_pf = mypf_df[mypf_df['InPortfolio'] == 'DM']
sv_pf = mypf_df[mypf_df['InPortfolio'] == 'SV']

# build portfolio stock dataframe
dm_stocks = get_stock_ids(dm_pf)
sv_stocks = get_stock_ids(sv_pf)
df_stocks = pd.concat([dm_pf,sv_pf], ignore_index = True)

# arrange common and diff stock features
common_cols = ['Symbol', 'Target', 'Criteria', 'Strategy', 'CumlRnk', 'LatestQtr', 'StarStock', 'Conviction', 'Category', 'InFolio', 'XIRR', 'MBQ']
diff_cols = ['Symbol', 'AvgCost', 'Shares']
df_stocks = arrange_features(df_stocks, common_cols, diff_cols)

# get common features
stock_ids = df_stocks['Symbol'].values
df_common_features = get_common_features(stock_ids, df_stocks)

df_common_features.reset_index(drop=True, inplace=True)
df_common_features.drop(['Date'], axis=1, inplace=True)
# get and print portfolio features
df_portfolio_features = get_portfolio_features(df_common_features)

print_portfolio_stats(df_portfolio_features, myinvmt_df)

df = df_portfolio_features
#plot_pie_chart(df, 'CapType', 'Current')
list_ox40n = list(df[df['MBQ'].str.contains('OX40N', na=False)]['Symbol'].values)

Run date time (IST): 2026-08-11 09:13:03
-------------------
qualified stocks: 88
with latest results: 30
still star stocks: 19
-------------------
Initial Investment:  1.46 C
CY Investment:  1.89 C
Reserve:  2.24 L
Current:  1.61 C
-------------------
Today PnL: 17.01 K (0.11%)
Current PnL: -30.66 L (-16.23%)
CY Booked + Current PnL: -26.44 L (-14.0%)
-------------------
Total profit:  3.81 L
Total loss:  -34.47 L
-------------------
Total Booked + Current PnL: 16.43 L (11.25%)
Total Booked PnL: 47.09 L (32.24%)
Curr Year Booked PnL: 4.22 L (2.61%)
Prev Year Booked PnL: 42.87 L (29.35%)
===================
Est FTT:  2.67 C
Est FTT PnL: 1.05 C (65.2%)
===================
Deployed:  1.46 C
Current:  1.61 C
CAGR/XIRR %: 4.6%

In [9]:
# top 5 near their targets
cols = ['Symbol', 'Today P/L%', 'Current P/L%', 'FTT%', 'OTT%', 'FTT Amt', 'Current P/L', 'Current', 'FTT', 'Dev%_PE', 'RSI_14','Conviction', 'Spread%',  'CumlRnk', 'RRR Ind', 'CurrAlloc%', 'Gained%', 'Criteria', 'Strategy', 'Category']
df_tmp = df_portfolio_features[~df_portfolio_features['Symbol'].isin(['ENRIN','BLUSPRING','DIGITIDE'])]
df_tmp = df_tmp.sort_values(by = 'FTT Amt', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
55,MEDANTA,-0.00,26.28,0.66,27.12,1471.0,46389.0,222906.0,1486.00,22.38,70.0,X-SC,16.54,87.0,31.54,1.40,53.59,XY24,NTT,HEALTHCARE
52,M&M,0.00,11.06,6.99,18.82,18684.0,26611.0,267292.0,3762.88,-3.30,70.0,X-LC,5.01,25.0,1.42,1.68,21.25,X40N,ATH,AUTO
80,UNITDSPR,0.63,11.80,8.02,20.77,20995.0,27640.0,261784.0,1644.00,-0.77,69.0,X-MC,8.01,64.0,1.32,1.64,25.84,X40N,NTT,BREWERIES
79,TTKPRESTIG,0.00,-21.28,27.15,0.09,21539.0,-21443.0,79334.0,770.00,84.20,42.0,M-SC,12.91,250.0,-1.00,0.50,42.79,OX40N,NTT,DURABLES
69,SIS,-1.75,-1.85,23.55,21.26,25663.0,-2058.0,108974.0,528.00,2600.52,47.0,H-SC,22.39,168.0,-0.08,0.68,62.03,OX40N,NTT,MISC

In [10]:
# top 5 today
df_tmp = df_portfolio_features.sort_values(by = 'Today P/L%', ascending=False)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
58,QUESS,4.08,32.78,30.97,73.90,43916.0,35009.0,141802.0,424.00,-28.37,65.0,X-SC,39.51,80.0,0.80,0.89,95.17,XY24,NTT,MISC
25,FINCABLES,3.26,34.01,55.15,107.91,109117.0,50211.0,197855.0,1641.55,20.75,57.0,M-SC,17.14,220.0,0.46,1.24,48.85,OX40N,ATH,CABLES
82,VALIANTORG,3.21,-38.12,181.44,74.15,183681.0,-62370.0,101235.0,838.00,-282.16,65.0,H-SC,4.15,145.0,-0.34,0.64,50.65,XR,NTT,CHEMICALS
11,BERGEPAINT,2.18,-0.10,25.44,25.32,65507.0,-251.0,257498.0,680.00,-5.48,64.0,X-MC,2.38,68.0,-0.00,1.62,35.03,XY24,NTT,PAINTS
43,INDIGOPNTS,1.85,-18.93,23.38,0.02,33085.0,-33050.0,141509.0,1408.00,115.96,65.0,M-SC,5.36,222.0,-1.00,0.89,60.55,OX40N,NTT,PAINTS

In [11]:
# bottom 5 today
df_tmp = df_portfolio_features.sort_values(by = 'Today P/L%', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
59,RAJESHEXPO,-1.96,-84.17,532.17,0.07,115555.0,-115463.0,21714.0,518.00,695.45,35.0,L-SC,36.59,268.0,-1.00,0.14,7.24,OX40N,NTT,JEWELLERY
81,VAIBHAVGBL,-1.85,-26.42,118.49,60.77,159352.0,-48289.0,134486.0,521.00,55.37,40.0,H-SC,11.23,160.0,-0.30,0.84,36.83,XR,NTT,JEWELLERY
69,SIS,-1.75,-1.85,23.55,21.26,25663.0,-2058.0,108974.0,528.00,2600.52,47.0,H-SC,22.39,168.0,-0.08,0.68,62.03,OX40N,NTT,MISC
28,GODREJCP,-1.62,-6.03,42.21,33.64,98979.0,-15046.0,234491.0,1469.04,-2.82,41.0,X-LC,5.13,32.0,-0.15,1.47,5.42,X40N,ATH,FMCG
84,VOLTAS,-1.33,-0.81,46.38,45.20,88208.0,-1557.0,190185.0,1856.00,13.55,39.0,X-MC,4.07,79.0,-0.02,1.19,4.24,XY25,NTT,AC

In [12]:
# top 5 to exit based on CumlRnk
df_tmp = df_portfolio_features[~df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])]
df_tmp = df_tmp[(df_tmp['Current P/L%'] > -1) & (df_tmp['Current P/L%'] < 1)].sort_values(by = 'CumlRnk', ascending=False)
df_tmp[cols].head()

Empty DataFrame
Columns: [Symbol, Today P/L%, Current P/L%, FTT%, OTT%, FTT Amt, Current P/L, Current, FTT, Dev%_PE, RSI_14, Conviction, Spread%, CumlRnk, RRR Ind, CurrAlloc%, Gained%, Criteria, Strategy, Category]
Index: []

In [13]:
# OX40N stocks to exit
df_tmp = df_portfolio_features[(df_portfolio_features['Symbol'].isin(list_ox40n))].sort_values(by = 'Current P/L%', ascending=False)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
25,FINCABLES,3.26,34.01,55.15,107.91,109117.0,50211.0,197855.0,1641.55,20.75,57.0,M-SC,17.14,220.0,0.46,1.24,48.85,OX40N,ATH,CABLES
69,SIS,-1.75,-1.85,23.55,21.26,25663.0,-2058.0,108974.0,528.00,2600.52,47.0,H-SC,22.39,168.0,-0.08,0.68,62.03,OX40N,NTT,MISC
43,INDIGOPNTS,1.85,-18.93,23.38,0.02,33085.0,-33050.0,141509.0,1408.00,115.96,65.0,M-SC,5.36,222.0,-1.00,0.89,60.55,OX40N,NTT,PAINTS
16,CERA,-0.47,-21.11,57.04,23.89,79154.0,-37133.0,138770.0,9475.00,-23.87,43.0,H-SC,12.72,153.0,-0.47,0.87,34.90,OX40N,NTT,CERAMICS
79,TTKPRESTIG,0.00,-21.28,27.15,0.09,21539.0,-21443.0,79334.0,770.00,84.20,42.0,M-SC,12.91,250.0,-1.00,0.50,42.79,OX40N,NTT,DURABLES

In [14]:
# top 5 to book for rotation
df_tmp = df_portfolio_features[(df_portfolio_features['Current P/L%'] > 20) ].sort_values(by = 'CumlRnk', ascending=False)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
25,FINCABLES,3.26,34.01,55.15,107.91,109117.0,50211.0,197855.0,1641.55,20.75,57.0,M-SC,17.14,220.0,0.46,1.24,48.85,OX40N,ATH,CABLES
55,MEDANTA,-0.00,26.28,0.66,27.12,1471.0,46389.0,222906.0,1486.00,22.38,70.0,X-SC,16.54,87.0,31.54,1.40,53.59,XY24,NTT,HEALTHCARE
58,QUESS,4.08,32.78,30.97,73.90,43916.0,35009.0,141802.0,424.00,-28.37,65.0,X-SC,39.51,80.0,0.80,0.89,95.17,XY24,NTT,MISC

In [15]:
# top 5 to monitor for exit
df_tmp = df_portfolio_features[~df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])]
df_tmp = df_tmp[(df_tmp['Current P/L%'] > 0) ].sort_values(by = 'Dev%_PE', ascending=False)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
70,STARHEALTH,0.00,11.26,32.36,47.26,101213.0,31650.0,312773.0,761.00,75.71,46.0,H-SC,16.90,173.0,0.31,1.96,35.23,XY24,NTT,INSURANCE
25,FINCABLES,3.26,34.01,55.15,107.91,109117.0,50211.0,197855.0,1641.55,20.75,57.0,M-SC,17.14,220.0,0.46,1.24,48.85,OX40N,ATH,CABLES
87,ZYDUSLIFE,0.00,18.00,14.84,35.51,36699.0,37725.0,247299.0,1285.01,2.70,50.0,H-MC,15.35,120.0,1.03,1.55,30.14,AR,ATH,PHARMA

In [16]:
# top 5 to book for rotation from weak conviction
df_tmp = df_portfolio_features[~df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])]
df_tmp = df_tmp[~df_tmp['Criteria'].isin(['XY25','XY24','X40', 'X40N'])].sort_values(by = 'RRR Ind', ascending=False)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
87,ZYDUSLIFE,0.00,18.00,14.84,35.51,36699.0,37725.0,247299.0,1285.01,2.70,50.0,H-MC,15.35,120.0,1.03,1.55,30.14,AR,ATH,PHARMA
25,FINCABLES,3.26,34.01,55.15,107.91,109117.0,50211.0,197855.0,1641.55,20.75,57.0,M-SC,17.14,220.0,0.46,1.24,48.85,OX40N,ATH,CABLES
69,SIS,-1.75,-1.85,23.55,21.26,25663.0,-2058.0,108974.0,528.00,2600.52,47.0,H-SC,22.39,168.0,-0.08,0.68,62.03,OX40N,NTT,MISC
3,ALKYLAMINE,1.19,-18.38,135.90,92.54,111988.0,-18558.0,82405.0,4520.85,-12.57,59.0,H-SC,13.34,142.0,-0.17,0.52,56.48,SR,ATH,CHEMICALS
42,INDIAMART,1.58,-23.39,162.28,100.92,153327.0,-28853.0,94483.0,4675.60,-65.43,41.0,H-SC,12.18,140.0,-0.19,0.59,2.28,AR,ATH,MISC

In [17]:
# top 5 to accumulate based on lowest RSI_14
df_tmp = df_portfolio_features[df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])].sort_values(by = 'RSI_14', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
34,HDFCBANK,0.00,-10.72,46.79,31.05,122448.0,-31422.0,261698.0,1073.00,-25.47,35.0,X-LC,11.34,26.0,-0.26,1.64,1.58,X40,BTT,BANKS
57,PGHH,-0.18,-36.44,107.70,32.01,146162.0,-77808.0,135712.0,17616.87,-57.06,35.0,X-MC,19.07,57.0,-0.53,0.85,0.06,X40,ATH,FMCG
56,PAGEIND,0.00,0.84,32.48,33.59,87897.0,2241.0,270620.0,51217.30,-27.65,38.0,X-MC,8.92,55.0,0.03,1.70,28.52,X40,ATH,APPARELS
84,VOLTAS,-1.33,-0.81,46.38,45.20,88208.0,-1557.0,190185.0,1856.00,13.55,39.0,X-MC,4.07,79.0,-0.02,1.19,4.24,XY25,NTT,AC
35,HDFCLIFE,0.00,-7.39,50.26,39.15,116704.0,-18537.0,232200.0,811.41,-31.02,40.0,X-LC,16.08,31.0,-0.16,1.46,0.76,X40,ATH,INSURANCE

In [18]:
# top 5 to accumulate based on Spread and CumlRnk
df_tmp = df_portfolio_features[df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])]
df_tmp = df_tmp[(df_tmp['CumlRnk'] < 100)].sort_values(by = 'Spread%', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
19,COLPAL,-0.52,-23.32,82.39,39.86,166387.0,-61415.0,201950.0,3683.41,-7.20,44.0,X-MC,1.50,62.0,-0.37,1.27,14.23,XY25,ATH,FMCG
11,BERGEPAINT,2.18,-0.10,25.44,25.32,65507.0,-251.0,257498.0,680.00,-5.48,64.0,X-MC,2.38,68.0,-0.00,1.62,35.03,XY24,NTT,PAINTS
8,BAJAJHLDNG,1.85,3.06,24.44,28.24,64481.0,7828.0,263833.0,14274.15,-5.41,65.0,X-LC,2.78,28.0,0.12,1.66,32.79,X40,ATH,FINANCE
23,DMART,0.00,-1.18,32.99,31.42,101644.0,-3686.0,308104.0,5391.45,-17.82,54.0,X-LC,2.99,14.0,-0.04,1.94,11.18,X40N,ATH,FMCG
50,KOTAKBANK,0.00,3.42,14.98,18.92,37136.0,8203.0,247905.0,452.46,-9.84,54.0,X-LC,3.14,12.0,0.22,1.56,11.54,X40,ATH,BANKS

In [19]:
# top 5 to accumulate based on lowest Gained%
df_tmp = df_portfolio_features[df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])].sort_values(by = 'Gained%', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
57,PGHH,-0.18,-36.44,107.70,32.01,146162.0,-77808.0,135712.0,17616.87,-57.06,35.0,X-MC,19.07,57.0,-0.53,0.85,0.06,X40,ATH,FMCG
35,HDFCLIFE,0.00,-7.39,50.26,39.15,116704.0,-18537.0,232200.0,811.41,-31.02,40.0,X-LC,16.08,31.0,-0.16,1.46,0.76,X40,ATH,INSURANCE
34,HDFCBANK,0.00,-10.72,46.79,31.05,122448.0,-31422.0,261698.0,1073.00,-25.47,35.0,X-LC,11.34,26.0,-0.26,1.64,1.58,X40,BTT,BANKS
20,DABUR,0.00,-19.02,77.45,43.70,155587.0,-47181.0,200887.0,735.00,-26.49,43.0,X-MC,9.30,70.0,-0.30,1.26,2.22,XY24,BTT,FMCG
47,ITC,-0.00,-22.02,59.92,24.70,185623.0,-87494.0,309784.0,452.00,-59.16,46.0,X-LC,10.86,1.0,-0.47,1.95,2.58,X40,NTT,FMCG

In [20]:
# top 5 to accumulate based on lowest CurrAlloc%
df_tmp = df_portfolio_features[df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])].sort_values(by = 'CurrAlloc%', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
10,BATAINDIA,0.00,-54.02,194.03,35.20,114802.0,-69503.0,59167.0,2096.00,-22.45,57.0,X-SC,13.71,91.0,-0.61,0.37,18.87,X40,NTT,FOOTWEAR
62,RELAXO,0.24,-45.03,177.06,52.31,141289.0,-65363.0,79797.0,1176.00,-41.44,60.0,X-SC,11.83,92.0,-0.46,0.50,78.42,X40N,NTT,FOOTWEAR
57,PGHH,-0.18,-36.44,107.70,32.01,146162.0,-77808.0,135712.0,17616.87,-57.06,35.0,X-MC,19.07,57.0,-0.53,0.85,0.06,X40,ATH,FMCG
58,QUESS,4.08,32.78,30.97,73.90,43916.0,35009.0,141802.0,424.00,-28.37,65.0,X-SC,39.51,80.0,0.80,0.89,95.17,XY24,NTT,MISC
40,ICICIPRULI,-0.26,-17.30,57.53,30.28,93727.0,-34087.0,162918.0,787.27,-39.48,46.0,X-MC,13.51,78.0,-0.36,1.02,8.55,X40,ATH,INSURANCE

In [21]:
# top 5 to accumulate based on CumlRnk
df_tmp = df_portfolio_features.sort_values(by = 'CumlRnk', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
47,ITC,-0.0,-22.02,59.92,24.70,185623.0,-87494.0,309784.0,452.00,-59.16,46.0,X-LC,10.86,1.0,-0.47,1.95,2.58,X40,NTT,FMCG
75,TCS,-0.0,-28.79,74.41,24.20,245475.0,-133378.0,329895.0,4230.71,-39.69,61.0,X-LC,15.44,2.0,-0.54,2.07,23.02,X40,ATH,IT
45,INFY,0.0,-15.79,66.69,40.38,211437.0,-59426.0,317044.0,1972.00,-36.50,63.0,X-LC,16.25,3.0,-0.28,1.99,20.06,X40,NTT,IT
77,TMPV,0.0,-17.42,72.86,42.75,250368.0,-72478.0,343629.0,600.00,-83.62,55.0,X-LC,5.12,4.0,-0.29,2.16,18.16,XY24,NTT,AUTO
33,HCLTECH,-0.0,-9.22,36.56,23.97,102712.0,-28546.0,280940.0,1853.42,-7.36,69.0,X-LC,13.07,8.0,-0.28,1.76,32.57,X40,ATH,IT

In [22]:
# top 5 for average up
df_tmp = df_portfolio_features[(df_portfolio_features['Dev%_200'] > 5)].sort_values(by = 'CurrAlloc%', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
44,INDUSINDBK,0.52,-24.16,75.22,32.89,44046.0,-18650.0,58556.0,1800.00,-375.91,58.0,L-MC,13.78,258.0,-0.42,0.37,44.36,XR,NTT,BANKS
62,RELAXO,0.24,-45.03,177.06,52.31,141289.0,-65363.0,79797.0,1176.00,-41.44,60.0,X-SC,11.83,92.0,-0.46,0.50,78.42,X40N,NTT,FOOTWEAR
79,TTKPRESTIG,0.00,-21.28,27.15,0.09,21539.0,-21443.0,79334.0,770.00,84.20,42.0,M-SC,12.91,250.0,-1.00,0.50,42.79,OX40N,NTT,DURABLES
3,ALKYLAMINE,1.19,-18.38,135.90,92.54,111988.0,-18558.0,82405.0,4520.85,-12.57,59.0,H-SC,13.34,142.0,-0.17,0.52,56.48,SR,ATH,CHEMICALS
12,BOSCH-HCIL,1.59,-25.11,33.52,-0.01,32082.0,-32095.0,95710.0,2282.00,19486.96,86.0,M-SC,3.27,231.0,-1.00,0.60,62.91,OX40N,BTT,AC

In [23]:
# top 5 RSP
df_tmp = df_portfolio_features.sort_values(by = 'RSP', ascending=False)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
12,BOSCH-HCIL,1.59,-25.11,33.52,-0.01,32082.0,-32095.0,95710.0,2282.00,19486.96,86.0,M-SC,3.27,231.0,-1.00,0.60,62.91,OX40N,BTT,AC
75,TCS,-0.00,-28.79,74.41,24.20,245475.0,-133378.0,329895.0,4230.71,-39.69,61.0,X-LC,15.44,2.0,-0.54,2.07,23.02,X40,ATH,IT
33,HCLTECH,-0.00,-9.22,36.56,23.97,102712.0,-28546.0,280940.0,1853.42,-7.36,69.0,X-LC,13.07,8.0,-0.28,1.76,32.57,X40,ATH,IT
73,TANLA,0.00,-28.56,204.12,117.25,394815.0,-77338.0,193423.0,1922.32,-27.72,65.0,H-SC,15.19,147.0,-0.20,1.21,69.35,AR,ATH,IT
58,QUESS,4.08,32.78,30.97,73.90,43916.0,35009.0,141802.0,424.00,-28.37,65.0,X-SC,39.51,80.0,0.80,0.89,95.17,XY24,NTT,MISC

In [24]:
# Top N allocation
df_tmp = df_portfolio_features.sort_values(by = 'CurrAlloc%', ascending=False)
top_n_values = [10, 25, 50]

sum_df = pd.DataFrame({
    'Top_N': top_n_values,
    'Sum_Alloc%': [df_tmp['CurrAlloc%'].head(n).sum() for n in top_n_values]
})

sum_df

   Top_N  Sum_Alloc%
0     10       19.79
1     25       44.81
2     50       76.81

In [25]:
# market-cap-wise allocation
df_tmp = df_portfolio_features[cols]
df_tmp.groupby(df_tmp['Conviction'].str[-2:])['CurrAlloc%'].sum().sort_values(ascending=False)

Conviction
SC    39.24
LC    37.85
MC    22.85
Name: CurrAlloc%, dtype: float64

In [26]:
# criteria-wise allocation
df_portfolio_features.groupby('Criteria')['CurrAlloc%'].sum().sort_values(ascending=False)

Criteria
X40      26.37
XY24     24.95
X40N     18.56
XR        9.06
XY25      7.19
OX40N     6.90
AR        6.05
SR        0.86
Name: CurrAlloc%, dtype: float64

In [27]:
# conviction-wise allocation
df_portfolio_features.groupby('Conviction')['CurrAlloc%'].sum().sort_values(ascending=False)

Conviction
X-LC    35.81
H-SC    19.25
X-MC    18.67
X-SC     9.96
M-SC     9.52
H-MC     2.62
H-LC     1.23
M-MC     1.19
M-LC     0.81
L-SC     0.51
L-MC     0.37
Name: CurrAlloc%, dtype: float64

In [28]:
# sector-wise stats
df_tmp = df_portfolio_features.groupby('Category')[['CurrAlloc%', 'Current', 'Current P/L', 'FTT Amt']].sum().sort_values(by=['Current', 'Current P/L'], ascending=False)
df_tmp['Current P/L%'] = round(df_tmp['Current P/L'] * 100 / df_tmp['Current'], 2)
df_tmp['FTT%'] = round(df_tmp['FTT Amt'] * 100 / df_tmp['Current'], 2)
cols = ['CurrAlloc%', 'Current P/L%', 'FTT%']
df_tmp[cols].sort_values(by=['CurrAlloc%'], ascending=False)

               CurrAlloc%  Current P/L%    FTT%
Category
FMCG                15.53        -20.69   64.15
IT                  11.22        -33.18   99.28
FINANCE              9.26        -15.88   64.59
AUTO                 8.34         -1.94   38.45
MISC                 6.87        -22.43   74.96
BANKS                6.05        -10.75   58.52
PHARMA               5.60          6.93   19.47
INSURANCE            5.54         -5.25   42.46
PAINTS               5.49        -12.80   32.04
ELECTRICAL           4.11         -7.81   45.55
HEALTHCARE           2.10         -6.74   34.59
AC                   1.79        -11.77   42.07
REFINERIES           1.70        -10.09   47.07
APPARELS             1.70          0.83   32.48
FOOTWEAR             1.66        -66.44  133.18
BREWERIES            1.64         10.56    8.02
DURABLES             1.49        -62.64  102.21
TRAVEL               1.47        -91.11  186.80
CERAMICS             1.35        -42.86   86.27
CABLES               1.24         25.38   55.15
ENGINEERING          1.20        -26.53   84.41
CHEMICALS            1.16        -44.07  161.00
CEMENT               1.02        -64.58  187.71
JEWELLERY            0.98       -104.83  176.00
ENTERTAINMENT        0.68        -78.09  184.30
TEXTILES             0.38        -50.54   93.47
HOTELS               0.37        -90.35  157.48

In [29]:
# money to be made criteria-wise
df_portfolio_features.groupby('Criteria')['FTT Amt'].agg(['sum', 'count']).sort_values(by='sum', ascending=False)

                sum  count
Criteria
XY24      3426902.0     20
X40       2025671.0     18
XR        1352817.0     13
X40N      1127703.0     12
AR        1066128.0      8
OX40N      691182.0     10
XY25       555175.0      5
SR         280039.0      2

In [30]:
# money to be made conviction-wise
df_portfolio_features.groupby('Conviction')['FTT Amt'].agg(['sum', 'count']).sort_values(by='sum', ascending=False)

                  sum  count
Conviction
H-SC        3282677.0     23
X-LC        2361020.0     20
X-MC        1479008.0     14
M-SC        1397954.0     14
X-SC        1215324.0      9
H-MC         280145.0      2
L-SC         209498.0      2
M-LC         162983.0      1
M-MC          56246.0      1
L-MC          44046.0      1
H-LC          36716.0      1

In [31]:
# money to be made criteria and conviction-wise
df_portfolio_features.groupby(['Conviction', 'Criteria'])['FTT Amt'].agg(['sum', 'count']).sort_values(by='sum', ascending=False)

                           sum  count
Conviction Criteria
X-LC       X40       1155440.0      9
H-SC       XY24       987831.0      5
           AR         916328.0      5
M-SC       XY24       846979.0      6
H-SC       XR         805174.0      7
X-SC       XY24       705621.0      4
X-MC       X40        655600.0      7
X-LC       X40N       484912.0      6
           XY24       421931.0      2
X-MC       X40N       347719.0      3
X-SC       X40N       295072.0      3
H-SC       OX40N      293305.0      4
M-SC       OX40N      282322.0      5
H-SC       SR         280039.0      2
X-MC       XY25       254595.0      2
X-LC       XY25       244334.0      2
H-MC       XY24       243446.0      1
X-MC       XY24       221094.0      2
X-SC       X40        214631.0      2
M-SC       XR         192268.0      2
M-LC       XR         162983.0      1
L-SC       OX40N      115555.0      1
           XR          93943.0      1
M-SC       AR          76385.0      1
M-MC       XY25        56246.0      1
X-LC       XR          54403.0      1
L-MC       XR          44046.0      1
H-LC       AR          36716.0      1
H-MC       AR          36699.0      1

In [32]:
# notebook execution time

end_time = time.time()
execution_time = round(end_time - start_time, 0)
print(f"Notebook execution time: {execution_time} seconds")

Notebook execution time: 39.0 seconds