<a href="https://colab.research.google.com/github/ankit-rathi/Quantvesting_v2/blob/main/myStocks_Portfolio_Analysis.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
'''
!pip install pandas==2.2.2 -qq
!pip install pyxirr -qq
!pip install ta -qq
!pip install yfinance==0.2.59 -qq
'''

'\n!pip install pandas==2.2.2 -qq\n!pip install pyxirr -qq\n!pip install ta -qq\n!pip install yfinance==0.2.59 -qq\n'

In [2]:
# import libraries

import numpy as np
import pandas as pd
import datetime
import warnings
warnings.filterwarnings('ignore')
import yfinance as yfin
import ta
import matplotlib.pyplot as plt
import requests

In [3]:
# notebook start time
import time
import datetime
import pytz

start_time = time.time()

# function to print date timestamp
def print_date_time():
  tz_NY = pytz.timezone('Asia/Kolkata')
  datetime_NY = datetime.datetime.now(tz_NY)
  print("Run date time (IST):", datetime_NY.strftime("%Y-%m-%d %H:%M:%S"))

In [4]:
# function to get booked and reserved amount
def get_amt():
  # fetch the JSON data from the URL
  url = "https://raw.githubusercontent.com/ankit-rathi/Tradevesting_v1/main/data/myPortfolioAmts.json"
  response = requests.get(url)
  pf_amts = response.json()  # parse the JSON data

  # extract values from the JSON
  py_booked_amt_dm = pf_amts["py_booked_amt_dm"]
  py_booked_amt_sv = pf_amts["py_booked_amt_sv"]
  cy_booked_amt_dm = pf_amts["cy_booked_amt_dm"]
  cy_booked_amt_sv = pf_amts["cy_booked_amt_sv"]
  reserve_amt_dm = pf_amts["reserve_amt_dm"]
  reserve_amt_sv = pf_amts["reserve_amt_sv"]

  # perform calculations
  py_booked_amt = py_booked_amt_dm + py_booked_amt_sv
  cy_booked_amt = cy_booked_amt_dm + cy_booked_amt_sv
  reserve_amt = reserve_amt_dm + reserve_amt_sv
  total_booked_amt = py_booked_amt + cy_booked_amt

  return total_booked_amt, reserve_amt, cy_booked_amt, py_booked_amt

gen_output = 0

In [5]:
# function to format the amount
def format_amt(number):
    abs_number = abs(number)

    if abs_number >= 1_00_00_000:  # Crores
        formatted_amt = f"{number / 1_00_00_000:.2f} C"
    elif abs_number >= 1_00_000:  # Lakhs
        formatted_amt = f"{number / 1_00_000:.2f} L"
    elif abs_number >= 1_000:  # Thousands
        formatted_amt = f"{number / 1_000:.2f} K"
    else:
        formatted_amt = f"{number:.2f}"

    return formatted_amt

# function to set start and end date
def get_start_end_date():
  start_date = (datetime.date.today() + datetime.timedelta(days=-365)).strftime('%Y-%m-%d')
  end_date = (datetime.date.today() + datetime.timedelta(days=1)).strftime('%Y-%m-%d')
  return start_date, end_date

# function to fetch my portfolio csv
def get_mypfs_df():
  mypfs_df = pd.read_csv('https://raw.githubusercontent.com/ankit-rathi/Tradevesting_v1/main/data/myPortfolioStocks.csv')
  return mypfs_df

# function to fetch my prospects csv
def get_mypps_df():
  mypps_df = pd.read_csv('https://raw.githubusercontent.com/ankit-rathi/Tradevesting_v1/main/data/myProspectsScrips.csv')
  return mypps_df

# function to fetch screener data
def get_myscreen_df():
  myscreen_df = pd.read_csv('https://raw.githubusercontent.com/ankit-rathi/Tradevesting_v1/main/data/myScreenerDB.csv')
  return myscreen_df

# function to fetch momentum data
def get_myinvmt_df():
  myinvmt_df = pd.read_csv('https://raw.githubusercontent.com/ankit-rathi/Tradevesting_v1/main/data/myInvestments.csv')
  return myinvmt_df

# function to get the stock ids
def get_stock_ids(df_pf):
  stock_n100 = df_pf['Symbol'].unique()

  exclude = ['CADILAHC','MMTC', 'MASFIN']

  stock_ids = df_pf[~df_pf['Symbol'].isin(exclude) ]['Symbol'].unique()

  #mypf = mypf[mypf.Forecast.notnull()]
  #stock_ids = mypf['Symbol'].unique()

  #stock_ids.sort()
  return stock_ids

# get features from screener data
def get_screener_features():
  myscreen_df = get_myscreen_df()
  cols = ['Symbol', 'EPS', 'MedPE', 'ROCE%', 'ROE%', 'CapType']
  return myscreen_df[cols]

# get relative strength
def get_relative_strength(stock_list):

    # Dictionary to store stock tickers and their corresponding percentage price change
    stock_changes = {}

    # Loop through each stock and fetch its price data
    for stock in stock_list:
        try:
            # Download the stock data for the given date range
            stock_data = yfin.Ticker(stock + '.NS').history(period='1mo', interval='1d')[map(str.title, ['open', 'close', 'low', 'high', 'volume'])]

            # Calculate the percentage change for the stock
            if len(stock_data) > 0:
                start_price = stock_data['Close'].iloc[0]
                end_price = stock_data['Close'].iloc[-1]
                percent_change = round(((end_price - start_price) / start_price) * 100, 2)
                stock_changes[stock] = percent_change
            else:
                stock_changes[stock] = np.nan  # If no data is available, set to NaN

        except Exception as e:
            print(f"Error fetching data for {stock}: {e}")
            stock_changes[stock] = np.nan

    # Create a DataFrame with stock tickers and their percentage changes
    df = pd.DataFrame(list(stock_changes.items()), columns=['Symbol', 'Percent_Change'])

    # Drop any stocks with missing data (NaN values)
    df = df.dropna()

    # Calculate the percentile rank based on percentage change
    df['RSP'] = round(df['Percent_Change'].rank(pct=True) * 100, 2)
    cols = ['Symbol', 'RSP']
    df = df[cols]
    # Sort by percentile rank (optional)
    df = df.sort_values(by='RSP', ascending=False).reset_index(drop=True)

    return df

In [6]:
# function to get stock technicals
def stock_prec_dev(stock_symbol):
    #stock_symbol = 'ULTRACEMCO.NS'
    short_window = 20
    mid_window = 50
    long_window = 200
    moving_avg = 'SMA'

    start = datetime.datetime(*map(int, start_date.split('-')))
    end = datetime.datetime(*map(int, end_date.split('-')))

    stock_df = yfin.Ticker(stock_symbol + '.NS').history(period='max', interval='1d')[map(str.title, ['open', 'close', 'low', 'high', 'volume'])]

    stock_df['Max'] = round(max(stock_df['Close']),2)
    stock_df = stock_df[(stock_df.index <= end_date) & (stock_df.index >= start_date)]
    stock_df['200_SMA'] = round(stock_df['Close'].rolling(window = 200, min_periods = 1).mean(),0)
    stock_df['Dev%_200'] = round((stock_df['Close'] - stock_df['200_SMA'])*100/stock_df['200_SMA'],2)
    stock_df.dropna(axis = 0, inplace = True) # remove any null rows

    stock_df['20_SMA'] = stock_df['Close'].rolling(window=20).mean()
    stock_df['50_SMA'] = stock_df['Close'].rolling(window=50).mean()
    stock_df['Symbol'] = stock_symbol

    stock_df['Close'] = round(stock_df['Close'],2)
    stock_df['Min'] = round(min(stock_df['Close']),2)
    stock_df['RSI_14'] = ta.momentum.RSIIndicator(close=stock_df['Close'], window=14).rsi()
    stock_df['RSI_14'] = round(stock_df['RSI_14'],0)
    stock_df['Prev_Close'] = stock_df['Close'].shift(1)
    stock_df.drop(['Open', 'Low', 'High', 'Volume'], axis=1, inplace=True)
    stock_df = stock_df.tail(1)

    max_SMA = max(stock_df['20_SMA'].item(), stock_df['50_SMA'].item(), stock_df['200_SMA'].item())
    min_SMA = min(stock_df['20_SMA'].item(), stock_df['50_SMA'].item(), stock_df['200_SMA'].item())
    ABS_Spread = max_SMA - min_SMA
    stock_df['Spread%'] = round((ABS_Spread / stock_df['200_SMA'].item()) * 100,2)

    return stock_df

# function to compute stock attributes
def get_common_features(stock_ids, df_mypf):

  df_prec_dev = pd.DataFrame()
  df_tmp = get_screener_features()
  df_rs = get_relative_strength(stock_ids)

  for stock_id in stock_ids:
      tmp = stock_prec_dev(stock_id)
      tmp = tmp.reset_index()
      df_prec_dev = pd.concat([df_prec_dev, tmp], ignore_index = True)
  df_prec_dev = pd.merge(df_prec_dev, df_mypf, on= 'Symbol')
  df_prec_dev = pd.merge(df_prec_dev, df_tmp, on= 'Symbol', how='left')
  df_prec_dev = pd.merge(df_prec_dev, df_rs, on= 'Symbol', how='left')
  #print(df_prec_dev.columns)
  df_prec_dev['Curr_PE'] = round(df_prec_dev['Close']/df_prec_dev['EPS'],1)
  df_prec_dev['Dev%_PE'] = round((df_prec_dev['Curr_PE'] - df_prec_dev['MedPE'])*100/df_prec_dev['MedPE'],2)
  df_prec_dev['Conviction'] = df_prec_dev['Conviction'] + '-' + df_prec_dev['CapType']
  return df_prec_dev

# function to arrange stock features
def arrange_features(df_stocks, common_cols, diff_cols):
  df_stocks_common = df_stocks[common_cols].drop_duplicates()
  df_stocks_diff = df_stocks[diff_cols]
  df_stocks_diff['Investment'] = df_stocks_diff['AvgCost'] * df_stocks_diff['Shares']
  df_stocks_diff = df_stocks_diff.groupby(['Symbol'])[['Shares', 'Investment']].aggregate(['sum']).reset_index()
  df_stocks_diff.columns = ['Symbol', 'Shares', 'Investment']
  df_stocks_diff['AvgCost'] = round(df_stocks_diff['Investment']/df_stocks_diff['Shares'],2)
  df_stocks = pd.merge(df_stocks_diff, df_stocks_common, on='Symbol')
  return df_stocks

# plot fact distribution across dimension
def plot_pie_chart(df, dimension, fact):
  # grouping the data by category and calculating the sum of fact for each type
  grouped_data = df.groupby(dimension)[fact].sum()

  # sorting the grouped data in descending order
  grouped_data = grouped_data.sort_values(ascending=False)

  # creating a pie chart
  grouped_data.plot.pie(autopct='%1.1f%%', startangle=90, figsize=(6, 6))

  # adding a title and displaying the plot
  plt.title(f'{dimension} {fact} Distribution')
  plt.ylabel('')  # To hide the y-label
  plt.show()

In [7]:
# function to get portfolio features

def get_portfolio_features(df_common_features):

  print_date_time()
  print('-------------------')

  #df_common_features["Target"] = df_common_features["Target"].fillna(df_common_features["Max"])
  df_common_features['NTT'] = np.where(df_common_features['Strategy']== 'NTT', df_common_features["Target"], df_common_features['Max'])
  df_common_features['LTT'] = np.where(df_common_features['Strategy']== 'BTT', df_common_features["Target"], df_common_features['Max'])
  df_common_features['BOL'] = df_common_features['Min']

  tmp_df = df_common_features[df_common_features['Symbol'].isin(mypf_df[mypf_df['InPortfolio'] != 'NA'].Symbol.values)]
  print('qualified stocks: '+str(len(tmp_df['Symbol'].unique())))
  tmp_df1 = tmp_df[tmp_df['LatestQtr'] == 1]
  print('with latest results: '+str(len(tmp_df1['Symbol'].unique())))
  tmp_df1 = tmp_df1[tmp_df1['StarStock'] == 1]
  print('still star stocks: '+str(len(tmp_df1['Symbol'].unique())))
  tmp_df['Investment'] = tmp_df['AvgCost'] * tmp_df['Shares']
  tmp_df['Current'] = round(tmp_df['Close'] * tmp_df['Shares'],0)
  tmp_df['Previous'] = tmp_df['Prev_Close'] * tmp_df['Shares']
  tmp_df['EstimatedST'] = tmp_df['NTT'] * tmp_df['Shares']
  tmp_df['EstimatedLT'] = tmp_df['LTT'] * tmp_df['Shares']
  tmp_df['Current P/L'] = round((tmp_df['Current'] - tmp_df['Investment']),0)
  tmp_df['Today P/L%'] = round((tmp_df['Current'] - tmp_df['Previous'])*100/tmp_df['Previous'],2)
  tmp_df['Current P/L%'] = round((tmp_df['Current'] - tmp_df['Investment'])*100/tmp_df['Investment'],2)
  tmp_df['EstimatedST P/L%'] = round((tmp_df['EstimatedST'] - tmp_df['Investment'])*100/tmp_df['Investment'],2)
  tmp_df['EstimatedLT P/L%'] = round((tmp_df['EstimatedLT'] - tmp_df['Investment'])*100/tmp_df['Investment'],2)
  tmp_df['NTT%'] = round((tmp_df['NTT'] - tmp_df['Close'])*100/tmp_df['Close'],2)
  tmp_df['LTT%'] = round((tmp_df['LTT'] - tmp_df['Close'])*100/tmp_df['Close'],2)
  tmp_df['Gained%'] = round((tmp_df['Close'] - tmp_df['BOL'])*100/tmp_df['BOL'],2)
  investment = round(sum(tmp_df['AvgCost']*tmp_df['Shares']),0)
  current = round(sum(tmp_df['Close']*tmp_df['Shares']),0)
  tmp_df['InitAlloc%'] = round(tmp_df['Investment']*100/investment,2)
  tmp_df['CurrAlloc%'] = round(tmp_df['Current']*100/current,2)
  tmp_df['FTT'] = tmp_df['LTT']
  tmp_df.loc[tmp_df['Strategy'] == 'NTT', 'FTT'] = tmp_df['NTT']
  tmp_df['FTT%'] = tmp_df['LTT%']
  tmp_df.loc[tmp_df['Strategy'] == 'NTT', 'FTT%'] = tmp_df['NTT%']
  tmp_df['FTT Amt'] = round(tmp_df['FTT%'] * tmp_df['Current']/100,0)
  tmp_df['OTT%'] = round((tmp_df['FTT'] - tmp_df['AvgCost'])*100/tmp_df['AvgCost'],2)
  tmp_df['RRR Ind'] = round(tmp_df['Current P/L']/tmp_df['FTT Amt'],2)
  tmp_df['Risk Ind'] = round(tmp_df['Current P/L%']*tmp_df['CurrAlloc%'],0)

  return tmp_df

# function to print portfolio features
def print_portfolio_stats(df_portfolio_features, myinvmt_df):
  from pyxirr import xirr

  total_booked_amt, reserve_amt, cy_booked_amt, py_booked_amt = get_amt()

  dates = myinvmt_df['Date'].values
  dates = np.append(dates, datetime.date.today().strftime('%d-%b-%y'))
  investment = myinvmt_df['Investment'].values
  dates= pd.to_datetime(dates)

  current = round(sum(df_portfolio_features['Close']*df_portfolio_features['Shares']),0) + reserve_amt
  investment_xirr = np.append(investment, current)
  cagr = round(xirr(pd.DataFrame({"dates": dates, "amounts": investment_xirr}))*100,2)

  investment = -sum(investment)
  invested = round(sum(df_portfolio_features['AvgCost']*df_portfolio_features['Shares']),0) + reserve_amt
  previous = round(sum(df_portfolio_features['Prev_Close']*df_portfolio_features['Shares']),0) + reserve_amt
  cy_invested = investment + py_booked_amt

  today_pnl_amount = current-previous
  today_pnl_percentage = round((current-previous)*100/previous,2)

  curr_pnl_amount = current-invested
  curr_pnl_percentage = round((curr_pnl_amount)*100/(cy_invested),2)

  cy_pnl_amount = cy_booked_amt + curr_pnl_amount
  cy_pnl_percentage = round((cy_pnl_amount)*100/cy_invested,2)

  overall_pnl_amount = total_booked_amt + curr_pnl_amount
  overall_pnl_percentage = round((overall_pnl_amount)*100/investment,2)

  estimate_st = round(sum(df_portfolio_features['FTT']*df_portfolio_features['Shares']),0)  + reserve_amt
  est_st_pnl_amount = estimate_st-current
  est_st_pnl_percentage = round((est_st_pnl_amount)*100/current,2)

  estimate_lt = round(sum(df_portfolio_features['LTT']*df_portfolio_features['Shares']),0)  + reserve_amt
  est_lt_pnl_amount = estimate_lt-current
  est_lt_pnl_percentage = round((est_lt_pnl_amount)*100/current,2)

  total_profit = round(sum(df_portfolio_features[df_portfolio_features['Current P/L%'] > 0]['Current']) - sum(df_portfolio_features[df_portfolio_features['Current P/L%'] > 0]['Investment']),0)
  total_loss = round(sum(df_portfolio_features[df_portfolio_features['Current P/L%'] < 0]['Current']) - sum(df_portfolio_features[df_portfolio_features['Current P/L%'] < 0]['Investment']),0)

  cy_booked_percentage = round((cy_booked_amt)*100/current,2)
  py_booked_percentage = round((py_booked_amt)*100/investment,2)
  total_booked_percentage = round((total_booked_amt)*100/investment,2)

  print('-------------------')
  print('Initial Investment: ', format_amt(investment))
  print('CY Investment: ', format_amt(cy_invested))
  print('Reserve: ', format_amt(reserve_amt))
  print('Current: ',  format_amt(current))
  print('-------------------')
  print('Today PnL: '+ '{} ({}%)'.format(format_amt(today_pnl_amount), today_pnl_percentage))
  print('Current PnL: '+ '{} ({}%)'.format(format_amt(curr_pnl_amount), curr_pnl_percentage))
  print('CY Booked + Current PnL: '+ '{} ({}%)'.format(format_amt(cy_pnl_amount), cy_pnl_percentage))
  print('-------------------')
  print('Total profit: ', format_amt(total_profit))
  print('Total loss: ', format_amt(total_loss))
  print('-------------------')
  print('Total Booked + Current PnL: '+ '{} ({}%)'.format(format_amt(overall_pnl_amount), overall_pnl_percentage))
  print('Total Booked PnL: '+ '{} ({}%)'.format(format_amt(total_booked_amt), total_booked_percentage))
  print('Curr Year Booked PnL: '+ '{} ({}%)'.format(format_amt(cy_booked_amt), cy_booked_percentage))
  print('Prev Year Booked PnL: '+ '{} ({}%)'.format(format_amt(py_booked_amt), py_booked_percentage))
  print('===================')
  print('Est FTT: ',  format_amt(estimate_st))
  print('Est FTT PnL: '+ '{} ({}%)'.format(format_amt(est_st_pnl_amount), est_st_pnl_percentage))

  print('===================')
  print('Deployed: ', format_amt(investment))

  print('Current: ', format_amt(current))

  print('CAGR/XIRR %: '+'{}%'.format(cagr))

In [8]:
# get start and end date
start_date, end_date = get_start_end_date()

# get portfolio and prospects data
mypfs_df = get_mypfs_df()
mypps_df = get_mypps_df()
myinvmt_df = get_myinvmt_df()

# merge above datasets
mypf_df = pd.merge(mypfs_df, mypps_df, on="Symbol")

# seggregate dm and sv portfolio
dm_pf = mypf_df[mypf_df['InPortfolio'] == 'DM']
sv_pf = mypf_df[mypf_df['InPortfolio'] == 'SV']

# build portfolio stock dataframe
dm_stocks = get_stock_ids(dm_pf)
sv_stocks = get_stock_ids(sv_pf)
df_stocks = pd.concat([dm_pf,sv_pf], ignore_index = True)

# arrange common and diff stock features
common_cols = ['Symbol', 'Target', 'Criteria', 'Strategy', 'CumlRnk', 'LatestQtr', 'StarStock', 'Conviction', 'Category', 'InFolio', 'XIRR', 'MBQ']
diff_cols = ['Symbol', 'AvgCost', 'Shares']
df_stocks = arrange_features(df_stocks, common_cols, diff_cols)

# get common features
stock_ids = df_stocks['Symbol'].values
df_common_features = get_common_features(stock_ids, df_stocks)

df_common_features.reset_index(drop=True, inplace=True)
df_common_features.drop(['Date'], axis=1, inplace=True)
# get and print portfolio features
df_portfolio_features = get_portfolio_features(df_common_features)

print_portfolio_stats(df_portfolio_features, myinvmt_df)

df = df_portfolio_features
#plot_pie_chart(df, 'CapType', 'Current')
list_ox40n = list(df[df['MBQ'].str.contains('OX40N', na=False)]['Symbol'].values)

Run date time (IST): 2026-05-13 11:18:42
-------------------
qualified stocks: 92
with latest results: 31
still star stocks: 20
-------------------
Initial Investment:  1.40 C
CY Investment:  1.82 C
Reserve:  1.49 K
Current:  1.47 C
-------------------
Today PnL: 60.68 K (0.41%)
Current PnL: -35.76 L (-19.61%)
CY Booked + Current PnL: -33.68 L (-18.47%)
-------------------
Total profit:  1.69 L
Total loss:  -37.46 L
-------------------
Total Booked + Current PnL: 9.19 L (6.58%)
Total Booked PnL: 44.95 L (32.22%)
Curr Year Booked PnL: 2.08 L (1.41%)
Prev Year Booked PnL: 42.87 L (30.73%)
===================
Est FTT:  2.55 C
Est FTT PnL: 1.08 C (73.28%)
===================
Deployed:  1.40 C
Current:  1.47 C
CAGR/XIRR %: 2.7%

In [9]:
# top 5 near their targets
cols = ['Symbol', 'Today P/L%', 'Current P/L%', 'FTT%', 'OTT%', 'FTT Amt', 'Current P/L', 'Current', 'FTT', 'Dev%_PE', 'RSI_14','Conviction', 'Spread%',  'CumlRnk', 'RRR Ind', 'CurrAlloc%', 'Gained%', 'Criteria', 'Strategy', 'Category']
df_tmp = df_portfolio_features[~df_portfolio_features['Symbol'].isin(['ENRIN','BLUSPRING','DIGITIDE'])]
df_tmp = df_tmp.sort_values(by = 'FTT Amt', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
55,MASFIN,-0.47,1.03,20.33,21.57,20124.0,1005.0,98985.0,397.04,-12.83,52.0,H-SC,5.65,167.0,0.05,0.67,24.50,XR,ATH,FINANCE
59,PIDILITIND,0.09,3.06,14.85,18.37,21596.0,4320.0,145430.0,1670.26,-27.87,61.0,X-LC,5.52,5.0,0.20,0.99,14.19,X40,ATH,CHEMICALS
51,KOTAKBANK,1.32,1.79,18.98,21.11,26753.0,2480.0,140952.0,453.24,-12.87,53.0,X-LC,7.31,12.0,0.09,0.96,7.80,X40,ATH,BANKS
53,M&M,-1.74,1.27,21.84,23.38,30671.0,1755.0,140436.0,3802.40,-14.09,46.0,X-LC,8.06,25.0,0.06,0.95,6.47,X40N,ATH,AUTO
83,TTKPRESTIG,0.13,-31.18,45.45,0.09,31520.0,-31426.0,69351.0,770.00,60.94,59.0,M-SC,17.09,250.0,-1.00,0.47,23.49,OX40N,NTT,DURABLES

In [10]:
# top 5 today
df_tmp = df_portfolio_features.sort_values(by = 'Today P/L%', ascending=False)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
43,INDIGOPNTS,5.98,-29.30,41.46,0.02,51169.0,-51142.0,123417.0,1408.00,88.06,71.0,M-SC,20.59,222.0,-1.00,0.84,40.03,OX40N,NTT,PAINTS
75,SURYODAY,5.67,3.91,18.40,23.03,34239.0,7008.0,186079.0,216.00,101.75,77.0,H-SC,13.65,166.0,0.20,1.26,56.67,XR,NTT,BANKS
11,BERGEPAINT,5.61,-5.00,31.91,25.32,78135.0,-12887.0,244862.0,680.00,-10.21,67.0,X-MC,12.06,68.0,-0.16,1.66,27.44,XY24,NTT,PAINTS
4,ASIANPAINT,4.41,-5.86,32.27,24.52,86107.0,-16607.0,266832.0,3460.25,-4.98,65.0,X-LC,6.89,30.0,-0.19,1.81,23.32,X40,ATH,PAINTS
0,5PAISA,3.72,-39.54,86.74,12.90,114584.0,-86395.0,132101.0,593.00,94.71,48.0,H-SC,7.95,170.0,-0.75,0.90,27.48,OX40N,NTT,FINANCE

In [11]:
# bottom 5 today
df_tmp = df_portfolio_features.sort_values(by = 'Today P/L%', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
12,BOSCH-HCIL,-2.79,-38.82,63.44,-0.01,49602.0,-49618.0,78187.0,2282.0,15900.00,52.0,M-SC,5.70,231.0,-1.00,0.53,33.09,OX40N,BTT,AC
69,SFL,-2.58,-46.64,137.32,26.63,192129.0,-122305.0,139913.0,1287.0,5.89,51.0,M-SC,13.37,242.0,-0.64,0.95,16.61,XY24,NTT,MISC
53,M&M,-1.74,1.27,21.84,23.38,30671.0,1755.0,140436.0,3802.4,-14.09,46.0,X-LC,8.06,25.0,0.06,0.95,6.47,X40N,ATH,AUTO
14,CAMPUS,-1.73,-18.81,64.16,33.28,87398.0,-31556.0,136219.0,393.0,-34.65,43.0,M-SC,8.03,218.0,-0.36,0.92,9.39,XY24,NTT,FOOTWEAR
20,DABUR,-1.42,-8.78,57.54,43.70,130200.0,-21791.0,226277.0,735.0,-17.25,55.0,X-MC,9.09,70.0,-0.17,1.54,13.67,XY24,BTT,FMCG

In [12]:
# top 5 to exit based on CumlRnk
df_tmp = df_portfolio_features[~df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])]
df_tmp = df_tmp[(df_tmp['Current P/L%'] > -1) & (df_tmp['Current P/L%'] < 1)].sort_values(by = 'CumlRnk', ascending=False)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
74,STARHEALTH,0.39,-0.69,48.29,47.26,134817.0,-1942.0,279181.0,761.0,56.7,57.0,H-SC,10.4,173.0,-0.01,1.89,31.79,XY24,NTT,INSURANCE

In [13]:
# OX40N stocks to exit
df_tmp = df_portfolio_features[(df_portfolio_features['Symbol'].isin(list_ox40n))].sort_values(by = 'Current P/L%', ascending=False)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
25,FINCABLES,-0.10,35.83,53.07,107.91,106431.0,52904.0,200548.0,1641.55,22.27,64.0,M-SC,22.37,220.0,0.50,1.36,50.88,OX40N,ATH,CABLES
72,SIS,-0.05,-14.28,41.46,21.26,39461.0,-15853.0,95179.0,528.00,2258.55,61.0,H-SC,12.56,168.0,-0.40,0.65,41.52,OX40N,NTT,MISC
16,CERA,-0.40,-22.82,60.53,23.89,82174.0,-40145.0,135758.0,9475.00,-25.54,68.0,H-SC,9.80,153.0,-0.49,0.92,30.46,OX40N,NTT,CERAMICS
50,KANSAINER,2.72,-26.69,54.79,13.47,108312.0,-71982.0,197685.0,340.00,-37.08,67.0,H-SC,15.13,162.0,-0.66,1.34,38.08,XY24,NTT,PAINTS
43,INDIGOPNTS,5.98,-29.30,41.46,0.02,51169.0,-51142.0,123417.0,1408.00,88.06,71.0,M-SC,20.59,222.0,-1.00,0.84,40.03,OX40N,NTT,PAINTS

In [14]:
# top 5 to book for rotation
df_tmp = df_portfolio_features[(df_portfolio_features['Current P/L%'] > 20) ].sort_values(by = 'CumlRnk', ascending=False)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
25,FINCABLES,-0.10,35.83,53.07,107.91,106431.0,52904.0,200548.0,1641.55,22.27,64.0,M-SC,22.37,220.0,0.50,1.36,50.88,OX40N,ATH,CABLES
68,SATIN,-0.99,23.50,22.95,51.83,78305.0,64915.0,341199.0,274.00,10.38,82.0,H-SC,22.12,159.0,0.83,2.31,66.21,XY24,NTT,FINANCE

In [15]:
# top 5 to monitor for exit
df_tmp = df_portfolio_features[~df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])]
df_tmp = df_tmp[(df_tmp['Current P/L%'] > 0) ].sort_values(by = 'Dev%_PE', ascending=False)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
75,SURYODAY,5.67,3.91,18.40,23.03,34239.0,7008.0,186079.0,216.00,101.75,77.0,H-SC,13.65,166.0,0.20,1.26,56.67,XR,NTT,BANKS
25,FINCABLES,-0.10,35.83,53.07,107.91,106431.0,52904.0,200548.0,1641.55,22.27,64.0,M-SC,22.37,220.0,0.50,1.36,50.88,OX40N,ATH,CABLES
68,SATIN,-0.99,23.50,22.95,51.83,78305.0,64915.0,341199.0,274.00,10.38,82.0,H-SC,22.12,159.0,0.83,2.31,66.21,XY24,NTT,FINANCE
55,MASFIN,-0.47,1.03,20.33,21.57,20124.0,1005.0,98985.0,397.04,-12.83,52.0,H-SC,5.65,167.0,0.05,0.67,24.50,XR,ATH,FINANCE
73,SONACOMS,1.37,2.43,35.79,39.09,37085.0,2459.0,103618.0,804.02,-18.85,58.0,M-MC,19.89,193.0,0.07,0.70,46.58,AR,ATH,AUTO

In [16]:
# top 5 to book for rotation from weak conviction
df_tmp = df_portfolio_features[~df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])]
df_tmp = df_tmp[~df_tmp['Criteria'].isin(['XY25','XY24','X40', 'X40N'])].sort_values(by = 'RRR Ind', ascending=False)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
25,FINCABLES,-0.10,35.83,53.07,107.91,106431.0,52904.0,200548.0,1641.55,22.27,64.0,M-SC,22.37,220.0,0.50,1.36,50.88,OX40N,ATH,CABLES
75,SURYODAY,5.67,3.91,18.40,23.03,34239.0,7008.0,186079.0,216.00,101.75,77.0,H-SC,13.65,166.0,0.20,1.26,56.67,XR,NTT,BANKS
73,SONACOMS,1.37,2.43,35.79,39.09,37085.0,2459.0,103618.0,804.02,-18.85,58.0,M-MC,19.89,193.0,0.07,0.70,46.58,AR,ATH,AUTO
55,MASFIN,-0.47,1.03,20.33,21.57,20124.0,1005.0,98985.0,397.04,-12.83,52.0,H-SC,5.65,167.0,0.05,0.67,24.50,XR,ATH,FINANCE
91,ZYDUSLIFE,0.19,-1.68,37.94,35.63,78179.0,-3514.0,206060.0,1286.17,-14.41,54.0,H-MC,3.36,120.0,-0.04,1.40,8.34,AR,ATH,PHARMA

In [17]:
# top 5 to accumulate based on lowest RSI_14
df_tmp = df_portfolio_features[df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])].sort_values(by = 'RSI_14', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
33,HCLTECH,0.25,-25.45,63.00,21.51,113618.0,-61578.0,180346.0,1872.35,-21.84,27.0,X-LC,14.65,8.0,-0.54,1.22,0.25,X40,ATH,IT
79,TCS,-0.47,-32.79,88.33,26.57,275023.0,-151915.0,311358.0,4311.59,-42.97,30.0,X-LC,14.86,2.0,-0.55,2.11,0.00,X40,ATH,IT
45,INFY,-0.68,-22.90,74.11,34.24,178786.0,-71644.0,241244.0,1972.00,-39.40,32.0,X-LC,16.94,3.0,-0.40,1.64,0.00,X40,NTT,IT
37,HONAUT,-0.62,-26.67,106.36,51.31,150393.0,-51438.0,141400.0,58357.33,-39.02,36.0,X-SC,12.34,90.0,-0.34,0.96,7.43,X40N,ATH,ELECTRICAL
84,UNITDSPR,-0.32,-8.65,32.21,20.77,68891.0,-20262.0,213882.0,1644.00,-18.95,36.0,X-MC,2.80,64.0,-0.29,1.45,2.03,X40N,NTT,BREWERIES

In [18]:
# top 5 to accumulate based on Spread and CumlRnk
df_tmp = df_portfolio_features[df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])]
df_tmp = df_tmp[(df_tmp['CumlRnk'] < 100)].sort_values(by = 'Spread%', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
88,VOLTAS,1.45,0.76,44.10,45.20,85201.0,1458.0,193200.0,1856.00,15.31,37.0,X-MC,1.73,79.0,0.02,1.31,5.56,XY25,NTT,AC
84,UNITDSPR,-0.32,-8.65,32.21,20.77,68891.0,-20262.0,213882.0,1644.00,-18.95,36.0,X-MC,2.80,64.0,-0.29,1.45,2.03,X40N,NTT,BREWERIES
65,RELIANCE,-0.64,-13.00,44.03,25.30,76979.0,-26129.0,174834.0,1952.00,-15.42,42.0,X-LC,3.52,21.0,-0.34,1.19,3.89,XY25,BTT,REFINERIES
39,ICICIGI,0.88,-4.73,25.27,19.34,48175.0,-9468.0,190641.0,2252.93,-19.83,49.0,X-MC,4.58,66.0,-0.20,1.29,6.48,X40,ATH,INSURANCE
19,COLPAL,-0.34,-19.58,75.97,41.51,160897.0,-51575.0,211790.0,3726.84,-2.71,53.0,X-MC,5.27,62.0,-0.32,1.44,18.40,XY25,ATH,FMCG

In [19]:
# top 5 to accumulate based on lowest Gained%
df_tmp = df_portfolio_features[df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])].sort_values(by = 'Gained%', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
45,INFY,-0.68,-22.90,74.11,34.24,178786.0,-71644.0,241244.0,1972.00,-39.40,32.0,X-LC,16.94,3.0,-0.40,1.64,0.00,X40,NTT,IT
79,TCS,-0.47,-32.79,88.33,26.57,275023.0,-151915.0,311358.0,4311.59,-42.97,30.0,X-LC,14.86,2.0,-0.55,2.11,0.00,X40,ATH,IT
33,HCLTECH,0.25,-25.45,63.00,21.51,113618.0,-61578.0,180346.0,1872.35,-21.84,27.0,X-LC,14.65,8.0,-0.54,1.22,0.25,X40,ATH,IT
32,HAVELLS,0.02,-23.74,73.19,32.08,183071.0,-77860.0,250131.0,2062.85,-28.22,37.0,X-MC,10.86,63.0,-0.43,1.70,0.89,X40,ATH,ELECTRICAL
84,UNITDSPR,-0.32,-8.65,32.21,20.77,68891.0,-20262.0,213882.0,1644.00,-18.95,36.0,X-MC,2.80,64.0,-0.29,1.45,2.03,X40N,NTT,BREWERIES

In [20]:
# top 5 to accumulate based on lowest CurrAlloc%
df_tmp = df_portfolio_features[df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])].sort_values(by = 'CurrAlloc%', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
64,RELAXO,-1.38,-63.04,312.05,52.31,167430.0,-91505.0,53655.0,1176.00,-60.60,40.0,X-SC,24.74,92.0,-0.55,0.36,19.97,X40N,NTT,FOOTWEAR
10,BATAINDIA,0.73,-54.54,197.41,35.20,115473.0,-70176.0,58494.0,2096.00,-23.32,43.0,X-SC,26.21,91.0,-0.61,0.40,16.01,X40,NTT,FOOTWEAR
60,QUESS,-0.10,-14.52,103.45,73.90,94433.0,-15509.0,91284.0,424.00,-54.27,56.0,X-SC,12.76,80.0,-0.16,0.62,24.44,XY24,NTT,MISC
28,GODREJCP,-0.85,-8.59,43.83,31.47,59541.0,-12768.0,135846.0,1469.04,-3.82,41.0,X-LC,7.16,32.0,-0.21,0.92,4.23,X40N,ATH,FMCG
53,M&M,-1.74,1.27,21.84,23.38,30671.0,1755.0,140436.0,3802.40,-14.09,46.0,X-LC,8.06,25.0,0.06,0.95,6.47,X40N,ATH,AUTO

In [21]:
# top 5 to accumulate based on CumlRnk
df_tmp = df_portfolio_features.sort_values(by = 'CumlRnk', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
47,ITC,0.98,-20.02,48.86,19.06,132933.0,-68096.0,272070.0,452.00,-55.92,46.0,X-LC,15.66,1.0,-0.51,1.85,5.54,X40,NTT,FMCG
79,TCS,-0.47,-32.79,88.33,26.57,275023.0,-151915.0,311358.0,4311.59,-42.97,30.0,X-LC,14.86,2.0,-0.55,2.11,0.00,X40,ATH,IT
45,INFY,-0.68,-22.90,74.11,34.24,178786.0,-71644.0,241244.0,1972.00,-39.40,32.0,X-LC,16.94,3.0,-0.40,1.64,0.00,X40,NTT,IT
81,TMPV,0.94,-22.61,76.47,36.58,210598.0,-80441.0,275400.0,600.00,-83.62,47.0,X-LC,5.53,4.0,-0.38,1.87,14.79,XY24,NTT,AUTO
59,PIDILITIND,0.09,3.06,14.85,18.37,21596.0,4320.0,145430.0,1670.26,-27.87,61.0,X-LC,5.52,5.0,0.20,0.99,14.19,X40,ATH,CHEMICALS

In [22]:
# top 5 for average up
df_tmp = df_portfolio_features[(df_portfolio_features['Dev%_200'] > 5)].sort_values(by = 'CurrAlloc%', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
44,INDUSINDBK,0.87,-33.51,99.86,32.89,51265.0,-25870.0,51337.0,1800.00,-341.60,53.0,L-MC,7.09,258.0,-0.50,0.35,26.36,XR,NTT,BANKS
72,SIS,-0.05,-14.28,41.46,21.26,39461.0,-15853.0,95179.0,528.00,2258.55,61.0,H-SC,12.56,168.0,-0.40,0.65,41.52,OX40N,NTT,MISC
55,MASFIN,-0.47,1.03,20.33,21.57,20124.0,1005.0,98985.0,397.04,-12.83,52.0,H-SC,5.65,167.0,0.05,0.67,24.50,XR,ATH,FINANCE
73,SONACOMS,1.37,2.43,35.79,39.09,37085.0,2459.0,103618.0,804.02,-18.85,58.0,M-MC,19.89,193.0,0.07,0.70,46.58,AR,ATH,AUTO
16,CERA,-0.40,-22.82,60.53,23.89,82174.0,-40145.0,135758.0,9475.00,-25.54,68.0,H-SC,9.80,153.0,-0.49,0.92,30.46,OX40N,NTT,CERAMICS

In [23]:
# top 5 RSP
df_tmp = df_portfolio_features.sort_values(by = 'RSP', ascending=False)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
68,SATIN,-0.99,23.50,22.95,51.83,78305.0,64915.0,341199.0,274.00,10.38,82.0,H-SC,22.12,159.0,0.83,2.31,66.21,XY24,NTT,FINANCE
75,SURYODAY,5.67,3.91,18.40,23.03,34239.0,7008.0,186079.0,216.00,101.75,77.0,H-SC,13.65,166.0,0.20,1.26,56.67,XR,NTT,BANKS
25,FINCABLES,-0.10,35.83,53.07,107.91,106431.0,52904.0,200548.0,1641.55,22.27,64.0,M-SC,22.37,220.0,0.50,1.36,50.88,OX40N,ATH,CABLES
43,INDIGOPNTS,5.98,-29.30,41.46,0.02,51169.0,-51142.0,123417.0,1408.00,88.06,71.0,M-SC,20.59,222.0,-1.00,0.84,40.03,OX40N,NTT,PAINTS
72,SIS,-0.05,-14.28,41.46,21.26,39461.0,-15853.0,95179.0,528.00,2258.55,61.0,H-SC,12.56,168.0,-0.40,0.65,41.52,OX40N,NTT,MISC

In [24]:
# Top N allocation
df_tmp = df_portfolio_features.sort_values(by = 'CurrAlloc%', ascending=False)
top_n_values = [10, 25, 50]

sum_df = pd.DataFrame({
    'Top_N': top_n_values,
    'Sum_Alloc%': [df_tmp['CurrAlloc%'].head(n).sum() for n in top_n_values]
})

sum_df

   Top_N  Sum_Alloc%
0     10       19.30
1     25       42.58
2     50       72.86

In [25]:
# market-cap-wise allocation
df_tmp = df_portfolio_features[cols]
df_tmp.groupby(df_tmp['Conviction'].str[-2:])['CurrAlloc%'].sum().sort_values(ascending=False)

Conviction
SC    42.92
LC    31.30
MC    25.79
Name: CurrAlloc%, dtype: float64

In [26]:
# criteria-wise allocation
df_portfolio_features.groupby('Criteria')['CurrAlloc%'].sum().sort_values(ascending=False)

Criteria
XY24     27.55
X40      25.52
X40N     16.57
XR        9.08
OX40N     7.08
XY25      6.75
AR        6.64
SR        0.82
Name: CurrAlloc%, dtype: float64

In [27]:
# conviction-wise allocation
df_portfolio_features.groupby('Conviction')['CurrAlloc%'].sum().sort_values(ascending=False)

Conviction
X-LC    29.21
H-SC    22.66
X-MC    20.88
M-SC    10.08
X-SC     9.66
H-MC     2.58
M-MC     1.98
H-LC     1.20
M-LC     0.89
L-SC     0.52
L-MC     0.35
Name: CurrAlloc%, dtype: float64

In [28]:
# sector-wise stats
df_tmp = df_portfolio_features.groupby('Category')[['CurrAlloc%', 'Current', 'Current P/L', 'FTT Amt']].sum().sort_values(by=['Current', 'Current P/L'], ascending=False)
df_tmp['Current P/L%'] = round(df_tmp['Current P/L'] * 100 / df_tmp['Current'], 2)
df_tmp['FTT%'] = round(df_tmp['FTT Amt'] * 100 / df_tmp['Current'], 2)
cols = ['CurrAlloc%', 'Current P/L%', 'FTT%']
df_tmp[cols].sort_values(by=['CurrAlloc%'], ascending=False)

               CurrAlloc%  Current P/L%    FTT%
Category
FMCG                15.48        -16.13   57.06
FINANCE             10.91        -14.50   64.31
IT                  10.13        -51.01  127.03
MISC                 6.96        -30.83   87.66
AUTO                 6.64        -11.77   53.67
BANKS                5.80         -6.31   55.47
PAINTS               5.65        -18.33   38.87
INSURANCE            5.38         -4.20   39.67
PHARMA               4.95         -1.62   34.28
ELECTRICAL           3.86        -24.26   68.49
CHEMICALS            2.13        -29.40  106.51
HEALTHCARE           2.00        -21.75   53.52
AC                   1.84        -17.75   49.67
DURABLES             1.69        -55.19   92.94
FOOTWEAR             1.68        -77.80  149.09
TRAVEL               1.68        -80.51  170.90
APPARELS             1.66         -9.51   46.87
BREWERIES            1.45         -9.47   32.21
CERAMICS             1.39        -50.06   95.65
REALTY               1.39         -7.93   25.67
CABLES               1.36         26.38   53.07
ENGINEERING          1.21        -35.90   98.06
REFINERIES           1.19        -14.95   44.03
CEMENT               1.10        -65.21  188.80
JEWELLERY            1.03       -112.23  185.97
ENTERTAINMENT        0.71        -84.72  194.89
TEXTILES             0.42        -48.33   90.63
HOTELS               0.32       -137.22  220.90

In [29]:
# money to be made criteria-wise
df_portfolio_features.groupby('Criteria')['FTT Amt'].agg(['sum', 'count']).sort_values(by='sum', ascending=False)

                sum  count
Criteria
XY24      3537292.0     21
X40       1941515.0     19
XR        1344073.0     13
X40N      1279063.0     13
AR        1205667.0      9
OX40N      750517.0     10
XY25       445837.0      5
SR         298000.0      2

In [30]:
# money to be made conviction-wise
df_portfolio_features.groupby('Conviction')['FTT Amt'].agg(['sum', 'count']).sort_values(by='sum', ascending=False)

                  sum  count
Conviction
H-SC        3448871.0     24
X-LC        1991883.0     21
X-MC        1655378.0     15
M-SC        1431863.0     14
X-SC        1380572.0      9
H-MC         317549.0      2
L-SC         213856.0      2
M-LC         161323.0      1
M-MC          93212.0      2
H-LC          56192.0      1
L-MC          51265.0      1

In [31]:
# money to be made criteria and conviction-wise
df_portfolio_features.groupby(['Conviction', 'Criteria'])['FTT Amt'].agg(['sum', 'count']).sort_values(by='sum', ascending=False)

                           sum  count
Conviction Criteria
H-SC       XY24      1068987.0      6
X-LC       X40       1050663.0     10
H-SC       AR         955969.0      5
M-SC       XY24       858445.0      6
X-SC       XY24       798039.0      4
H-SC       XR         792253.0      7
X-MC       X40        681257.0      7
           X40N       519688.0      4
X-LC       X40N       386437.0      6
X-SC       X40N       372938.0      3
X-LC       XY24       364116.0      2
H-SC       OX40N      333662.0      4
M-SC       OX40N      308735.0      5
H-SC       SR         298000.0      2
X-MC       XY25       246098.0      2
H-MC       XY24       239370.0      1
X-SC       X40        209595.0      2
X-MC       XY24       208335.0      2
M-SC       XR         186441.0      2
M-LC       XR         161323.0      1
X-LC       XY25       143612.0      2
L-SC       OX40N      108120.0      1
           XR         105736.0      1
M-SC       AR          78242.0      1
H-MC       AR          78179.0      1
H-LC       AR          56192.0      1
M-MC       XY25        56127.0      1
L-MC       XR          51265.0      1
X-LC       XR          47055.0      1
M-MC       AR          37085.0      1

In [32]:
# notebook execution time

end_time = time.time()
execution_time = round(end_time - start_time, 0)
print(f"Notebook execution time: {execution_time} seconds")

Notebook execution time: 29.0 seconds