<a href="https://colab.research.google.com/github/ankit-rathi/Quantvesting_v2/blob/main/myStocks_Portfolio_Analysis.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
'''
!pip install pandas==2.2.2 -qq
!pip install pyxirr -qq
!pip install ta -qq
!pip install yfinance==0.2.59 -qq
'''

'\n!pip install pandas==2.2.2 -qq\n!pip install pyxirr -qq\n!pip install ta -qq\n!pip install yfinance==0.2.59 -qq\n'

In [2]:
# import libraries

import numpy as np
import pandas as pd
import datetime
import warnings
warnings.filterwarnings('ignore')
import yfinance as yfin
import ta
import matplotlib.pyplot as plt
import requests

In [3]:
# notebook start time
import time
import datetime
import pytz

start_time = time.time()

# function to print date timestamp
def print_date_time():
  tz_NY = pytz.timezone('Asia/Kolkata')
  datetime_NY = datetime.datetime.now(tz_NY)
  print("Run date time (IST):", datetime_NY.strftime("%Y-%m-%d %H:%M:%S"))

In [4]:
# function to get booked and reserved amount
def get_amt():
  # fetch the JSON data from the URL
  url = "https://raw.githubusercontent.com/ankit-rathi/Tradevesting_v1/main/data/myPortfolioAmts.json"
  response = requests.get(url)
  pf_amts = response.json()  # parse the JSON data

  # extract values from the JSON
  py_booked_amt_dm = pf_amts["py_booked_amt_dm"]
  py_booked_amt_sv = pf_amts["py_booked_amt_sv"]
  cy_booked_amt_dm = pf_amts["cy_booked_amt_dm"]
  cy_booked_amt_sv = pf_amts["cy_booked_amt_sv"]
  reserve_amt_dm = pf_amts["reserve_amt_dm"]
  reserve_amt_sv = pf_amts["reserve_amt_sv"]

  # perform calculations
  py_booked_amt = py_booked_amt_dm + py_booked_amt_sv
  cy_booked_amt = cy_booked_amt_dm + cy_booked_amt_sv
  reserve_amt = reserve_amt_dm + reserve_amt_sv
  total_booked_amt = py_booked_amt + cy_booked_amt

  return total_booked_amt, reserve_amt, cy_booked_amt, py_booked_amt

gen_output = 0

In [5]:
# function to format the amount
def format_amt(number):
    abs_number = abs(number)

    if abs_number >= 1_00_00_000:  # Crores
        formatted_amt = f"{number / 1_00_00_000:.2f} C"
    elif abs_number >= 1_00_000:  # Lakhs
        formatted_amt = f"{number / 1_00_000:.2f} L"
    elif abs_number >= 1_000:  # Thousands
        formatted_amt = f"{number / 1_000:.2f} K"
    else:
        formatted_amt = f"{number:.2f}"

    return formatted_amt

# function to set start and end date
def get_start_end_date():
  start_date = (datetime.date.today() + datetime.timedelta(days=-365)).strftime('%Y-%m-%d')
  end_date = (datetime.date.today() + datetime.timedelta(days=1)).strftime('%Y-%m-%d')
  return start_date, end_date

# function to fetch my portfolio csv
def get_mypfs_df():
  mypfs_df = pd.read_csv('https://raw.githubusercontent.com/ankit-rathi/Tradevesting_v1/main/data/myPortfolioStocks.csv')
  return mypfs_df

# function to fetch my prospects csv
def get_mypps_df():
  mypps_df = pd.read_csv('https://raw.githubusercontent.com/ankit-rathi/Tradevesting_v1/main/data/myProspectsScrips.csv')
  return mypps_df

# function to fetch screener data
def get_myscreen_df():
  myscreen_df = pd.read_csv('https://raw.githubusercontent.com/ankit-rathi/Tradevesting_v1/main/data/myScreenerDB.csv')
  return myscreen_df

# function to fetch momentum data
def get_myinvmt_df():
  myinvmt_df = pd.read_csv('https://raw.githubusercontent.com/ankit-rathi/Tradevesting_v1/main/data/myInvestments.csv')
  return myinvmt_df

# function to get the stock ids
def get_stock_ids(df_pf):
  stock_n100 = df_pf['Symbol'].unique()

  exclude = ['CADILAHC','MMTC', 'MASFIN']

  stock_ids = df_pf[~df_pf['Symbol'].isin(exclude) ]['Symbol'].unique()

  #mypf = mypf[mypf.Forecast.notnull()]
  #stock_ids = mypf['Symbol'].unique()

  #stock_ids.sort()
  return stock_ids

# get features from screener data
def get_screener_features():
  myscreen_df = get_myscreen_df()
  cols = ['Symbol', 'EPS', 'MedPE', 'ROCE%', 'ROE%', 'CapType']
  return myscreen_df[cols]

# get relative strength
def get_relative_strength(stock_list):

    # Dictionary to store stock tickers and their corresponding percentage price change
    stock_changes = {}

    # Loop through each stock and fetch its price data
    for stock in stock_list:
        try:
            # Download the stock data for the given date range
            stock_data = yfin.Ticker(stock + '.NS').history(period='1mo', interval='1d')[map(str.title, ['open', 'close', 'low', 'high', 'volume'])]

            # Calculate the percentage change for the stock
            if len(stock_data) > 0:
                start_price = stock_data['Close'].iloc[0]
                end_price = stock_data['Close'].iloc[-1]
                percent_change = round(((end_price - start_price) / start_price) * 100, 2)
                stock_changes[stock] = percent_change
            else:
                stock_changes[stock] = np.nan  # If no data is available, set to NaN

        except Exception as e:
            print(f"Error fetching data for {stock}: {e}")
            stock_changes[stock] = np.nan

    # Create a DataFrame with stock tickers and their percentage changes
    df = pd.DataFrame(list(stock_changes.items()), columns=['Symbol', 'Percent_Change'])

    # Drop any stocks with missing data (NaN values)
    df = df.dropna()

    # Calculate the percentile rank based on percentage change
    df['RSP'] = round(df['Percent_Change'].rank(pct=True) * 100, 2)
    cols = ['Symbol', 'RSP']
    df = df[cols]
    # Sort by percentile rank (optional)
    df = df.sort_values(by='RSP', ascending=False).reset_index(drop=True)

    return df

In [6]:
# function to get stock technicals
def stock_prec_dev(stock_symbol):
    #stock_symbol = 'ULTRACEMCO.NS'
    short_window = 20
    mid_window = 50
    long_window = 200
    moving_avg = 'SMA'

    start = datetime.datetime(*map(int, start_date.split('-')))
    end = datetime.datetime(*map(int, end_date.split('-')))

    stock_df = yfin.Ticker(stock_symbol + '.NS').history(period='max', interval='1d')[map(str.title, ['open', 'close', 'low', 'high', 'volume'])]

    stock_df['Max'] = round(max(stock_df['Close']),2)
    stock_df = stock_df[(stock_df.index <= end_date) & (stock_df.index >= start_date)]
    stock_df['200_SMA'] = round(stock_df['Close'].rolling(window = 200, min_periods = 1).mean(),0)
    stock_df['Dev%_200'] = round((stock_df['Close'] - stock_df['200_SMA'])*100/stock_df['200_SMA'],2)
    stock_df.dropna(axis = 0, inplace = True) # remove any null rows

    stock_df['20_SMA'] = stock_df['Close'].rolling(window=20).mean()
    stock_df['50_SMA'] = stock_df['Close'].rolling(window=50).mean()
    stock_df['Symbol'] = stock_symbol

    stock_df['Close'] = round(stock_df['Close'],2)
    stock_df['Min'] = round(min(stock_df['Close']),2)
    stock_df['RSI_14'] = ta.momentum.RSIIndicator(close=stock_df['Close'], window=14).rsi()
    stock_df['RSI_14'] = round(stock_df['RSI_14'],0)
    stock_df['Prev_Close'] = stock_df['Close'].shift(1)
    stock_df.drop(['Open', 'Low', 'High', 'Volume'], axis=1, inplace=True)
    stock_df = stock_df.tail(1)

    max_SMA = max(stock_df['20_SMA'].item(), stock_df['50_SMA'].item(), stock_df['200_SMA'].item())
    min_SMA = min(stock_df['20_SMA'].item(), stock_df['50_SMA'].item(), stock_df['200_SMA'].item())
    ABS_Spread = max_SMA - min_SMA
    stock_df['Spread%'] = round((ABS_Spread / stock_df['200_SMA'].item()) * 100,2)

    return stock_df

# function to compute stock attributes
def get_common_features(stock_ids, df_mypf):

  df_prec_dev = pd.DataFrame()
  df_tmp = get_screener_features()
  df_rs = get_relative_strength(stock_ids)

  for stock_id in stock_ids:
      tmp = stock_prec_dev(stock_id)
      tmp = tmp.reset_index()
      df_prec_dev = pd.concat([df_prec_dev, tmp], ignore_index = True)
  df_prec_dev = pd.merge(df_prec_dev, df_mypf, on= 'Symbol')
  df_prec_dev = pd.merge(df_prec_dev, df_tmp, on= 'Symbol', how='left')
  df_prec_dev = pd.merge(df_prec_dev, df_rs, on= 'Symbol', how='left')
  #print(df_prec_dev.columns)
  df_prec_dev['Curr_PE'] = round(df_prec_dev['Close']/df_prec_dev['EPS'],1)
  df_prec_dev['Dev%_PE'] = round((df_prec_dev['Curr_PE'] - df_prec_dev['MedPE'])*100/df_prec_dev['MedPE'],2)
  df_prec_dev['Conviction'] = df_prec_dev['Conviction'] + '-' + df_prec_dev['CapType']
  return df_prec_dev

# function to arrange stock features
def arrange_features(df_stocks, common_cols, diff_cols):
  df_stocks_common = df_stocks[common_cols].drop_duplicates()
  df_stocks_diff = df_stocks[diff_cols]
  df_stocks_diff['Investment'] = df_stocks_diff['AvgCost'] * df_stocks_diff['Shares']
  df_stocks_diff = df_stocks_diff.groupby(['Symbol'])[['Shares', 'Investment']].aggregate(['sum']).reset_index()
  df_stocks_diff.columns = ['Symbol', 'Shares', 'Investment']
  df_stocks_diff['AvgCost'] = round(df_stocks_diff['Investment']/df_stocks_diff['Shares'],2)
  df_stocks = pd.merge(df_stocks_diff, df_stocks_common, on='Symbol')
  return df_stocks

# plot fact distribution across dimension
def plot_pie_chart(df, dimension, fact):
  # grouping the data by category and calculating the sum of fact for each type
  grouped_data = df.groupby(dimension)[fact].sum()

  # sorting the grouped data in descending order
  grouped_data = grouped_data.sort_values(ascending=False)

  # creating a pie chart
  grouped_data.plot.pie(autopct='%1.1f%%', startangle=90, figsize=(6, 6))

  # adding a title and displaying the plot
  plt.title(f'{dimension} {fact} Distribution')
  plt.ylabel('')  # To hide the y-label
  plt.show()

In [7]:
# function to get portfolio features

def get_portfolio_features(df_common_features):

  print_date_time()
  print('-------------------')

  #df_common_features["Target"] = df_common_features["Target"].fillna(df_common_features["Max"])
  df_common_features['NTT'] = np.where(df_common_features['Strategy']== 'NTT', df_common_features["Target"], df_common_features['Max'])
  df_common_features['LTT'] = np.where(df_common_features['Strategy']== 'BTT', df_common_features["Target"], df_common_features['Max'])
  df_common_features['BOL'] = df_common_features['Min']

  tmp_df = df_common_features[df_common_features['Symbol'].isin(mypf_df[mypf_df['InPortfolio'] != 'NA'].Symbol.values)]
  print('qualified stocks: '+str(len(tmp_df['Symbol'].unique())))
  tmp_df1 = tmp_df[tmp_df['LatestQtr'] == 1]
  print('with latest results: '+str(len(tmp_df1['Symbol'].unique())))
  tmp_df1 = tmp_df1[tmp_df1['StarStock'] == 1]
  print('still star stocks: '+str(len(tmp_df1['Symbol'].unique())))
  tmp_df['Investment'] = tmp_df['AvgCost'] * tmp_df['Shares']
  tmp_df['Current'] = round(tmp_df['Close'] * tmp_df['Shares'],0)
  tmp_df['Previous'] = tmp_df['Prev_Close'] * tmp_df['Shares']
  tmp_df['EstimatedST'] = tmp_df['NTT'] * tmp_df['Shares']
  tmp_df['EstimatedLT'] = tmp_df['LTT'] * tmp_df['Shares']
  tmp_df['Current P/L'] = round((tmp_df['Current'] - tmp_df['Investment']),0)
  tmp_df['Today P/L%'] = round((tmp_df['Current'] - tmp_df['Previous'])*100/tmp_df['Previous'],2)
  tmp_df['Current P/L%'] = round((tmp_df['Current'] - tmp_df['Investment'])*100/tmp_df['Investment'],2)
  tmp_df['EstimatedST P/L%'] = round((tmp_df['EstimatedST'] - tmp_df['Investment'])*100/tmp_df['Investment'],2)
  tmp_df['EstimatedLT P/L%'] = round((tmp_df['EstimatedLT'] - tmp_df['Investment'])*100/tmp_df['Investment'],2)
  tmp_df['NTT%'] = round((tmp_df['NTT'] - tmp_df['Close'])*100/tmp_df['Close'],2)
  tmp_df['LTT%'] = round((tmp_df['LTT'] - tmp_df['Close'])*100/tmp_df['Close'],2)
  tmp_df['Gained%'] = round((tmp_df['Close'] - tmp_df['BOL'])*100/tmp_df['BOL'],2)
  investment = round(sum(tmp_df['AvgCost']*tmp_df['Shares']),0)
  current = round(sum(tmp_df['Close']*tmp_df['Shares']),0)
  tmp_df['InitAlloc%'] = round(tmp_df['Investment']*100/investment,2)
  tmp_df['CurrAlloc%'] = round(tmp_df['Current']*100/current,2)
  tmp_df['FTT'] = tmp_df['LTT']
  tmp_df.loc[tmp_df['Strategy'] == 'NTT', 'FTT'] = tmp_df['NTT']
  tmp_df['FTT%'] = tmp_df['LTT%']
  tmp_df.loc[tmp_df['Strategy'] == 'NTT', 'FTT%'] = tmp_df['NTT%']
  tmp_df['FTT Amt'] = round(tmp_df['FTT%'] * tmp_df['Current']/100,0)
  tmp_df['OTT%'] = round((tmp_df['FTT'] - tmp_df['AvgCost'])*100/tmp_df['AvgCost'],2)
  tmp_df['RRR Ind'] = round(tmp_df['Current P/L']/tmp_df['FTT Amt'],2)
  tmp_df['Risk Ind'] = round(tmp_df['Current P/L%']*tmp_df['CurrAlloc%'],0)

  return tmp_df

# function to print portfolio features
def print_portfolio_stats(df_portfolio_features, myinvmt_df):
  from pyxirr import xirr

  total_booked_amt, reserve_amt, cy_booked_amt, py_booked_amt = get_amt()

  dates = myinvmt_df['Date'].values
  dates = np.append(dates, datetime.date.today().strftime('%d-%b-%y'))
  investment = myinvmt_df['Investment'].values
  dates= pd.to_datetime(dates)

  current = round(sum(df_portfolio_features['Close']*df_portfolio_features['Shares']),0) + reserve_amt
  investment_xirr = np.append(investment, current)
  cagr = round(xirr(pd.DataFrame({"dates": dates, "amounts": investment_xirr}))*100,2)

  investment = -sum(investment)
  invested = round(sum(df_portfolio_features['AvgCost']*df_portfolio_features['Shares']),0) + reserve_amt
  previous = round(sum(df_portfolio_features['Prev_Close']*df_portfolio_features['Shares']),0) + reserve_amt
  cy_invested = investment + py_booked_amt

  today_pnl_amount = current-previous
  today_pnl_percentage = round((current-previous)*100/previous,2)

  curr_pnl_amount = current-invested
  curr_pnl_percentage = round((curr_pnl_amount)*100/(cy_invested),2)

  cy_pnl_amount = cy_booked_amt + curr_pnl_amount
  cy_pnl_percentage = round((cy_pnl_amount)*100/cy_invested,2)

  overall_pnl_amount = total_booked_amt + curr_pnl_amount
  overall_pnl_percentage = round((overall_pnl_amount)*100/investment,2)

  estimate_st = round(sum(df_portfolio_features['FTT']*df_portfolio_features['Shares']),0)  + reserve_amt
  est_st_pnl_amount = estimate_st-current
  est_st_pnl_percentage = round((est_st_pnl_amount)*100/current,2)

  estimate_lt = round(sum(df_portfolio_features['LTT']*df_portfolio_features['Shares']),0)  + reserve_amt
  est_lt_pnl_amount = estimate_lt-current
  est_lt_pnl_percentage = round((est_lt_pnl_amount)*100/current,2)

  total_profit = round(sum(df_portfolio_features[df_portfolio_features['Current P/L%'] > 0]['Current']) - sum(df_portfolio_features[df_portfolio_features['Current P/L%'] > 0]['Investment']),0)
  total_loss = round(sum(df_portfolio_features[df_portfolio_features['Current P/L%'] < 0]['Current']) - sum(df_portfolio_features[df_portfolio_features['Current P/L%'] < 0]['Investment']),0)

  cy_booked_percentage = round((cy_booked_amt)*100/current,2)
  py_booked_percentage = round((py_booked_amt)*100/investment,2)
  total_booked_percentage = round((total_booked_amt)*100/investment,2)

  print('-------------------')
  print('Initial Investment: ', format_amt(investment))
  print('CY Investment: ', format_amt(cy_invested))
  print('Reserve: ', format_amt(reserve_amt))
  print('Current: ',  format_amt(current))
  print('-------------------')
  print('Today PnL: '+ '{} ({}%)'.format(format_amt(today_pnl_amount), today_pnl_percentage))
  print('Current PnL: '+ '{} ({}%)'.format(format_amt(curr_pnl_amount), curr_pnl_percentage))
  print('CY Booked + Current PnL: '+ '{} ({}%)'.format(format_amt(cy_pnl_amount), cy_pnl_percentage))
  print('-------------------')
  print('Total profit: ', format_amt(total_profit))
  print('Total loss: ', format_amt(total_loss))
  print('-------------------')
  print('Total Booked + Current PnL: '+ '{} ({}%)'.format(format_amt(overall_pnl_amount), overall_pnl_percentage))
  print('Total Booked PnL: '+ '{} ({}%)'.format(format_amt(total_booked_amt), total_booked_percentage))
  print('Curr Year Booked PnL: '+ '{} ({}%)'.format(format_amt(cy_booked_amt), cy_booked_percentage))
  print('Prev Year Booked PnL: '+ '{} ({}%)'.format(format_amt(py_booked_amt), py_booked_percentage))
  print('===================')
  print('Est FTT: ',  format_amt(estimate_st))
  print('Est FTT PnL: '+ '{} ({}%)'.format(format_amt(est_st_pnl_amount), est_st_pnl_percentage))

  print('===================')
  print('Deployed: ', format_amt(investment))

  print('Current: ', format_amt(current))

  print('CAGR/XIRR %: '+'{}%'.format(cagr))

In [8]:
# get start and end date
start_date, end_date = get_start_end_date()

# get portfolio and prospects data
mypfs_df = get_mypfs_df()
mypps_df = get_mypps_df()
myinvmt_df = get_myinvmt_df()

# merge above datasets
mypf_df = pd.merge(mypfs_df, mypps_df, on="Symbol")

# seggregate dm and sv portfolio
dm_pf = mypf_df[mypf_df['InPortfolio'] == 'DM']
sv_pf = mypf_df[mypf_df['InPortfolio'] == 'SV']

# build portfolio stock dataframe
dm_stocks = get_stock_ids(dm_pf)
sv_stocks = get_stock_ids(sv_pf)
df_stocks = pd.concat([dm_pf,sv_pf], ignore_index = True)

# arrange common and diff stock features
common_cols = ['Symbol', 'Target', 'Criteria', 'Strategy', 'CumlRnk', 'LatestQtr', 'StarStock', 'Conviction', 'Category', 'InFolio', 'XIRR', 'MBQ']
diff_cols = ['Symbol', 'AvgCost', 'Shares']
df_stocks = arrange_features(df_stocks, common_cols, diff_cols)

# get common features
stock_ids = df_stocks['Symbol'].values
df_common_features = get_common_features(stock_ids, df_stocks)

df_common_features.reset_index(drop=True, inplace=True)
df_common_features.drop(['Date'], axis=1, inplace=True)
# get and print portfolio features
df_portfolio_features = get_portfolio_features(df_common_features)

print_portfolio_stats(df_portfolio_features, myinvmt_df)

df = df_portfolio_features
#plot_pie_chart(df, 'CapType', 'Current')
list_ox40n = list(df[df['MBQ'].str.contains('OX40N', na=False)]['Symbol'].values)

Run date time (IST): 2026-04-21 12:28:56
-------------------
qualified stocks: 85
with latest results: 25
still star stocks: 15
-------------------
Initial Investment:  1.36 C
CY Investment:  1.78 C
Reserve:  1.61 K
Current:  1.41 C
-------------------
Today PnL: 1.24 L (0.89%)
Current PnL: -33.06 L (-18.54%)
CY Booked + Current PnL: -32.10 L (-18.0%)
-------------------
Total profit:  1.79 L
Total loss:  -34.85 L
-------------------
Total Booked + Current PnL: 10.77 L (7.94%)
Total Booked PnL: 43.83 L (32.35%)
Curr Year Booked PnL: 96.00 K (0.68%)
Prev Year Booked PnL: 42.87 L (31.64%)
===================
Est FTT:  2.44 C
Est FTT PnL: 1.03 C (73.1%)
===================
Deployed:  1.36 C
Current:  1.41 C
CAGR/XIRR %: 1.91%

In [9]:
# top 5 near their targets
cols = ['Symbol', 'Today P/L%', 'Current P/L%', 'FTT%', 'OTT%', 'FTT Amt', 'Current P/L', 'Current', 'FTT', 'Dev%_PE', 'RSI_14','Conviction', 'Spread%',  'CumlRnk', 'RRR Ind', 'CurrAlloc%', 'Gained%', 'Criteria', 'Strategy', 'Category']
df_tmp = df_portfolio_features[~df_portfolio_features['Symbol'].isin(['ENRIN','BLUSPRING','DIGITIDE'])]
df_tmp = df_tmp.sort_values(by = 'FTT Amt', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
49,MASFIN,0.03,-3.55,26.04,21.57,24608.0,-3480.0,94500.0,397.04,-16.89,56.0,H-SC,3.31,167.0,-0.14,0.67,22.12,XR,ATH,FINANCE
1,ABB,1.56,33.38,9.13,45.57,31860.0,87341.0,348960.0,7934.00,-14.32,78.0,H-MC,18.42,125.0,2.74,2.48,54.96,AR,NTT,ELECTRICAL
76,TTKPRESTIG,1.14,-34.97,53.92,0.09,35335.0,-35244.0,65533.0,770.00,52.19,56.0,M-SC,22.94,250.0,-1.00,0.46,16.69,OX40N,NTT,DURABLES
56,RECLTD,-0.37,3.22,16.97,20.74,35589.0,6545.0,209715.0,446.00,13.28,70.0,M-MC,4.85,191.0,0.18,1.49,24.98,XY25,NTT,FINANCE
66,SONACOMS,0.79,0.53,38.36,39.09,39009.0,533.0,101692.0,804.02,-20.33,64.0,M-MC,10.47,193.0,0.01,0.72,43.86,AR,ATH,AUTO

In [10]:
# top 5 today
df_tmp = df_portfolio_features.sort_values(by = 'Today P/L%', ascending=False)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
40,INDIGOPNTS,3.92,-38.30,62.10,0.02,66885.0,-66853.0,107706.0,1408.00,64.06,61.0,M-SC,27.60,222.0,-1.00,0.76,22.20,OX40N,NTT,PAINTS
59,REPCOHOME,3.84,-9.59,109.95,89.82,284809.0,-27470.0,259035.0,880.00,-54.55,68.0,H-SC,4.56,161.0,-0.10,1.84,24.52,XY24,NTT,FINANCE
61,SATIN,3.53,-3.03,56.57,51.83,151565.0,-8359.0,267925.0,274.00,-13.27,70.0,H-SC,2.17,159.0,-0.06,1.90,30.52,XY24,NTT,FINANCE
14,BSOFT,3.25,-28.57,111.09,50.79,111612.0,-40183.0,100470.0,831.70,-8.39,60.0,H-SC,6.82,172.0,-0.36,0.71,18.48,XR,ATH,IT
4,ALKYLAMINE,3.14,-38.17,213.15,93.63,133063.0,-38536.0,62427.0,4546.37,-33.72,58.0,H-SC,23.90,142.0,-0.29,0.44,17.88,SR,ATH,CHEMICALS

In [11]:
# bottom 5 today
df_tmp = df_portfolio_features.sort_values(by = 'Today P/L%', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
54,RAJESHEXPO,-3.91,-77.24,339.73,0.07,106054.0,-105960.0,31217.0,518.00,1043.94,54.0,L-SC,41.15,268.0,-1.00,0.22,46.55,OX40N,NTT,JEWELLERY
19,COLPAL,-2.14,-20.89,78.87,41.51,164326.0,-55015.0,208350.0,3726.84,-4.28,60.0,X-MC,11.90,62.0,-0.33,1.48,16.48,XY25,ATH,FMCG
37,ICICIPRULI,-1.77,-9.31,44.15,30.73,78880.0,-18341.0,178664.0,790.00,-33.64,44.0,X-MC,12.96,78.0,-0.23,1.27,8.87,X40,ATH,INSURANCE
36,ICICIGI,-1.54,-2.13,21.94,19.34,42969.0,-4263.0,195846.0,2252.93,-17.63,56.0,X-MC,7.11,66.0,-0.10,1.39,9.38,X40,ATH,INSURANCE
39,INDIAMART,-1.20,-7.25,122.88,106.72,140569.0,-8941.0,114395.0,4810.62,-58.20,58.0,H-SC,11.94,140.0,-0.06,0.81,9.90,AR,ATH,MISC

In [12]:
# top 5 to exit based on CumlRnk
df_tmp = df_portfolio_features[~df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])]
df_tmp = df_tmp[(df_tmp['Current P/L%'] > -1) & (df_tmp['Current P/L%'] < 1)].sort_values(by = 'CumlRnk', ascending=False)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
66,SONACOMS,0.79,0.53,38.36,39.09,39009.0,533.0,101692.0,804.02,-20.33,64.0,M-MC,10.47,193.0,0.01,0.72,43.86,AR,ATH,AUTO
67,STARHEALTH,1.78,-0.26,47.64,47.26,133585.0,-718.0,280405.0,761.00,57.39,75.0,H-SC,2.54,173.0,-0.01,1.99,45.22,XY24,NTT,INSURANCE

In [13]:
# OX40N stocks to exit
df_tmp = df_portfolio_features[(df_portfolio_features['Symbol'].isin(list_ox40n))].sort_values(by = 'Current P/L%', ascending=False)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
25,FINCABLES,0.32,20.27,72.87,107.91,129399.0,29931.0,177575.0,1641.55,8.07,68.0,M-SC,3.43,220.0,0.23,1.26,33.60,OX40N,ATH,CABLES
65,SIS,2.80,-22.95,57.38,21.26,49090.0,-25480.0,85552.0,528.00,2019.69,75.0,H-SC,10.16,168.0,-0.52,0.61,27.20,OX40N,NTT,MISC
17,CERA,0.08,-30.56,78.42,23.89,95785.0,-53759.0,122144.0,9475.00,-32.94,67.0,H-SC,13.51,153.0,-0.56,0.87,17.38,OX40N,NTT,CERAMICS
47,KANSAINER,1.19,-31.08,64.65,13.47,120152.0,-83817.0,185850.0,340.00,-40.82,67.0,H-SC,20.10,162.0,-0.70,1.32,29.82,XY24,NTT,PAINTS
71,TATAELXSI,2.85,-33.05,97.21,32.03,85799.0,-43574.0,88261.0,9161.00,-16.33,60.0,H-SC,18.30,158.0,-0.51,0.63,16.82,OX40N,NTT,IT

In [14]:
# top 5 to book for rotation
df_tmp = df_portfolio_features[(df_portfolio_features['Current P/L%'] > 20) ].sort_values(by = 'CumlRnk', ascending=False)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
25,FINCABLES,0.32,20.27,72.87,107.91,129399.0,29931.0,177575.0,1641.55,8.07,68.0,M-SC,3.43,220.0,0.23,1.26,33.60,OX40N,ATH,CABLES
1,ABB,1.56,33.38,9.13,45.57,31860.0,87341.0,348960.0,7934.00,-14.32,78.0,H-MC,18.42,125.0,2.74,2.48,54.96,AR,NTT,ELECTRICAL

In [15]:
# top 5 to monitor for exit
df_tmp = df_portfolio_features[~df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])]
df_tmp = df_tmp[(df_tmp['Current P/L%'] > 0) ].sort_values(by = 'Dev%_PE', ascending=False)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
56,RECLTD,-0.37,3.22,16.97,20.74,35589.0,6545.0,209715.0,446.00,13.28,70.0,M-MC,4.85,191.0,0.18,1.49,24.98,XY25,NTT,FINANCE
25,FINCABLES,0.32,20.27,72.87,107.91,129399.0,29931.0,177575.0,1641.55,8.07,68.0,M-SC,3.43,220.0,0.23,1.26,33.60,OX40N,ATH,CABLES
1,ABB,1.56,33.38,9.13,45.57,31860.0,87341.0,348960.0,7934.00,-14.32,78.0,H-MC,18.42,125.0,2.74,2.48,54.96,AR,NTT,ELECTRICAL
66,SONACOMS,0.79,0.53,38.36,39.09,39009.0,533.0,101692.0,804.02,-20.33,64.0,M-MC,10.47,193.0,0.01,0.72,43.86,AR,ATH,AUTO

In [16]:
# top 5 to book for rotation from weak conviction
df_tmp = df_portfolio_features[~df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])]
df_tmp = df_tmp[~df_tmp['Criteria'].isin(['XY25','XY24','X40', 'X40N'])].sort_values(by = 'RRR Ind', ascending=False)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
1,ABB,1.56,33.38,9.13,45.57,31860.0,87341.0,348960.0,7934.00,-14.32,78.0,H-MC,18.42,125.0,2.74,2.48,54.96,AR,NTT,ELECTRICAL
25,FINCABLES,0.32,20.27,72.87,107.91,129399.0,29931.0,177575.0,1641.55,8.07,68.0,M-SC,3.43,220.0,0.23,1.26,33.60,OX40N,ATH,CABLES
66,SONACOMS,0.79,0.53,38.36,39.09,39009.0,533.0,101692.0,804.02,-20.33,64.0,M-MC,10.47,193.0,0.01,0.72,43.86,AR,ATH,AUTO
84,ZYDUSLIFE,-0.90,-2.13,38.58,35.63,79131.0,-4464.0,205110.0,1286.17,-14.86,58.0,H-MC,4.93,120.0,-0.06,1.45,11.05,AR,ATH,PHARMA
39,INDIAMART,-1.20,-7.25,122.88,106.72,140569.0,-8941.0,114395.0,4810.62,-58.20,58.0,H-SC,11.94,140.0,-0.06,0.81,9.90,AR,ATH,MISC

In [17]:
# top 5 to accumulate based on lowest RSI_14
df_tmp = df_portfolio_features[df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])].sort_values(by = 'RSI_14', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
2,ABBOTINDIA,-0.33,-14.57,38.21,18.07,58381.0,-26065.0,152790.0,35195.0,-27.31,40.0,X-MC,11.80,58.0,-0.45,1.08,0.00,X40,ATH,PHARMA
37,ICICIPRULI,-1.77,-9.31,44.15,30.73,78880.0,-18341.0,178664.0,790.0,-33.64,44.0,X-MC,12.96,78.0,-0.23,1.27,8.87,X40,ATH,INSURANCE
45,JIOFIN,-0.93,-22.03,64.72,28.43,150539.0,-65727.0,232600.0,387.0,-23.21,46.0,X-LC,18.73,34.0,-0.44,1.65,4.84,XY24,BTT,FINANCE
58,RELIANCE,-0.42,-12.85,43.78,25.30,76672.0,-25833.0,175130.0,1952.0,-15.03,48.0,X-LC,5.60,21.0,-0.34,1.24,5.56,XY25,BTT,REFINERIES
33,HDFCBANK,1.57,-3.35,32.81,28.37,74485.0,-7865.0,227020.0,1073.0,-18.07,50.0,X-LC,17.52,26.0,-0.11,1.61,10.44,X40,BTT,BANKS

In [18]:
# top 5 to accumulate based on Spread and CumlRnk
df_tmp = df_portfolio_features[df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])]
df_tmp = df_tmp[(df_tmp['CumlRnk'] < 100)].sort_values(by = 'Spread%', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
64,SIEMENS,1.24,0.89,24.41,25.51,45830.0,1655.0,187750.0,4671.50,57.74,73.0,H-LC,2.66,51.0,0.04,1.33,32.83,AR,ATH,ELECTRICAL
23,DMART,-0.63,10.01,17.81,29.60,48902.0,24978.0,274578.0,5391.45,-7.20,68.0,X-LC,5.15,14.0,0.51,1.95,25.51,X40N,ATH,FMCG
58,RELIANCE,-0.42,-12.85,43.78,25.30,76672.0,-25833.0,175130.0,1952.00,-15.03,48.0,X-LC,5.60,21.0,-0.34,1.24,5.56,XY25,BTT,REFINERIES
77,UNITDSPR,2.63,-1.41,22.49,20.77,51916.0,-3303.0,230841.0,1644.00,-12.63,58.0,X-MC,6.21,64.0,-0.06,1.64,10.12,X40N,NTT,BREWERIES
81,VOLTAS,1.89,14.62,26.67,45.20,58615.0,28038.0,219780.0,1856.00,31.17,62.0,X-MC,6.89,79.0,0.48,1.56,22.41,XY25,NTT,AC

In [19]:
# top 5 to accumulate based on lowest Gained%
df_tmp = df_portfolio_features[df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])].sort_values(by = 'Gained%', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
2,ABBOTINDIA,-0.33,-14.57,38.21,18.07,58381.0,-26065.0,152790.0,35195.0,-27.31,40.0,X-MC,11.80,58.0,-0.45,1.08,0.00,X40,ATH,PHARMA
45,JIOFIN,-0.93,-22.03,64.72,28.43,150539.0,-65727.0,232600.0,387.0,-23.21,46.0,X-LC,18.73,34.0,-0.44,1.65,4.84,XY24,BTT,FINANCE
58,RELIANCE,-0.42,-12.85,43.78,25.30,76672.0,-25833.0,175130.0,1952.0,-15.03,48.0,X-LC,5.60,21.0,-0.34,1.24,5.56,XY25,BTT,REFINERIES
44,ITC,0.29,-19.43,47.76,19.06,130903.0,-66080.0,274086.0,452.0,-55.92,53.0,X-LC,19.14,1.0,-0.50,1.94,6.33,X40,NTT,FMCG
27,GLAXO,0.05,-2.41,42.58,39.15,82813.0,-4796.0,194488.0,3466.2,-25.54,54.0,X-MC,10.92,56.0,-0.06,1.38,7.59,X40,ATH,PHARMA

In [20]:
# top 5 to accumulate based on lowest CurrAlloc%
df_tmp = df_portfolio_features[df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])].sort_values(by = 'CurrAlloc%', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
57,RELAXO,1.09,-60.03,281.03,52.31,163065.0,-87136.0,58024.0,1176.00,-57.41,58.0,X-SC,31.66,92.0,-0.53,0.41,29.74,X40N,NTT,FOOTWEAR
11,BATAINDIA,0.97,-50.65,173.95,35.20,110463.0,-65167.0,63503.0,2096.00,-16.68,64.0,X-SC,31.54,91.0,-0.59,0.45,25.94,X40,NTT,FOOTWEAR
53,QUESS,1.70,-19.38,115.71,73.90,99618.0,-20700.0,86093.0,424.00,-56.47,59.0,X-SC,19.34,80.0,-0.21,0.61,15.81,XY24,NTT,MISC
2,ABBOTINDIA,-0.33,-14.57,38.21,18.07,58381.0,-26065.0,152790.0,35195.00,-27.31,40.0,X-MC,11.80,58.0,-0.45,1.08,0.00,X40,ATH,PHARMA
35,HONAUT,-0.03,-15.62,79.31,51.31,129057.0,-30113.0,162725.0,58357.33,-29.79,69.0,X-SC,17.16,90.0,-0.23,1.15,23.63,X40N,ATH,ELECTRICAL

In [21]:
# top 5 to accumulate based on CumlRnk
df_tmp = df_portfolio_features.sort_values(by = 'CumlRnk', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
44,ITC,0.29,-19.43,47.76,19.06,130903.0,-66080.0,274086.0,452.00,-55.92,53.0,X-LC,19.14,1.0,-0.50,1.94,6.33,X40,NTT,FMCG
72,TCS,0.88,-23.61,65.69,26.57,232476.0,-109374.0,353899.0,4311.58,-35.43,58.0,X-LC,16.13,2.0,-0.47,2.51,10.45,X40,ATH,IT
42,INFY,0.77,-9.96,49.09,34.24,138304.0,-31153.0,281735.0,1972.00,-29.25,53.0,X-LC,12.76,3.0,-0.23,2.00,8.35,X40,NTT,IT
74,TMPV,0.72,-18.45,67.48,36.58,195815.0,-65659.0,290182.0,600.00,-82.53,62.0,X-LC,9.64,4.0,-0.34,2.06,20.95,XY24,NTT,AUTO
32,HCLTECH,1.20,-6.19,32.01,23.83,72645.0,-14980.0,226944.0,1908.19,-1.57,56.0,X-LC,7.29,8.0,-0.21,1.61,10.19,X40,ATH,IT

In [22]:
# top 5 for average up
df_tmp = df_portfolio_features[(df_portfolio_features['Dev%_200'] > 5)].sort_values(by = 'CurrAlloc%', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
66,SONACOMS,0.79,0.53,38.36,39.09,39009.0,533.0,101692.0,804.02,-20.33,64.0,M-MC,10.47,193.0,0.01,0.72,43.86,AR,ATH,AUTO
68,SURYODAY,0.49,-17.48,49.09,23.03,72544.0,-31293.0,147778.0,216.00,60.09,64.0,H-SC,3.68,166.0,-0.43,1.05,26.03,XR,NTT,BANKS
25,FINCABLES,0.32,20.27,72.87,107.91,129399.0,29931.0,177575.0,1641.55,8.07,68.0,M-SC,3.43,220.0,0.23,1.26,33.60,OX40N,ATH,CABLES
64,SIEMENS,1.24,0.89,24.41,25.51,45830.0,1655.0,187750.0,4671.50,57.74,73.0,H-LC,2.66,51.0,0.04,1.33,32.83,AR,ATH,ELECTRICAL
56,RECLTD,-0.37,3.22,16.97,20.74,35589.0,6545.0,209715.0,446.00,13.28,70.0,M-MC,4.85,191.0,0.18,1.49,24.98,XY25,NTT,FINANCE

In [23]:
# top 5 RSP
df_tmp = df_portfolio_features.sort_values(by = 'RSP', ascending=False)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
54,RAJESHEXPO,-3.91,-77.24,339.73,0.07,106054.0,-105960.0,31217.0,518.0,1043.94,54.0,L-SC,41.15,268.0,-1.00,0.22,46.55,OX40N,NTT,JEWELLERY
47,KANSAINER,1.19,-31.08,64.65,13.47,120152.0,-83817.0,185850.0,340.0,-40.82,67.0,H-SC,20.10,162.0,-0.70,1.32,29.82,XY24,NTT,PAINTS
55,RAJOOENG,1.51,-35.25,115.61,39.61,76730.0,-36130.0,66370.0,143.1,-56.22,62.0,H-SC,29.01,136.0,-0.47,0.47,42.18,AR,ATH,MISC
65,SIS,2.80,-22.95,57.38,21.26,49090.0,-25480.0,85552.0,528.0,2019.69,75.0,H-SC,10.16,168.0,-0.52,0.61,27.20,OX40N,NTT,MISC
80,VBL,2.93,-3.00,39.69,35.50,121597.0,-9474.0,306368.0,670.8,-14.33,70.0,X-LC,9.82,13.0,-0.08,2.17,25.80,X40N,ATH,FMCG

In [24]:
# Top N allocation
df_tmp = df_portfolio_features.sort_values(by = 'CurrAlloc%', ascending=False)
top_n_values = [10, 25, 50]

sum_df = pd.DataFrame({
    'Top_N': top_n_values,
    'Sum_Alloc%': [df_tmp['CurrAlloc%'].head(n).sum() for n in top_n_values]
})

sum_df

   Top_N  Sum_Alloc%
0     10       20.98
1     25       46.21
2     50       78.39

In [25]:
# market-cap-wise allocation
df_tmp = df_portfolio_features[cols]
df_tmp.groupby(df_tmp['Conviction'].str[-2:])['CurrAlloc%'].sum().sort_values(ascending=False)

Conviction
SC    43.84
MC    30.40
LC    25.77
Name: CurrAlloc%, dtype: float64

In [26]:
# criteria-wise allocation
df_portfolio_features.groupby('Criteria')['CurrAlloc%'].sum().sort_values(ascending=False)

Criteria
XY24     27.96
X40      25.07
X40N     13.69
AR        9.60
XR        8.45
XY25      7.36
OX40N     7.07
SR        0.81
Name: CurrAlloc%, dtype: float64

In [27]:
# conviction-wise allocation
df_portfolio_features.groupby('Conviction')['CurrAlloc%'].sum().sort_values(ascending=False)

Conviction
X-LC    23.43
H-SC    22.76
X-MC    22.61
M-SC    10.38
X-SC    10.11
H-MC     5.23
M-MC     2.21
H-LC     1.33
M-LC     1.01
L-SC     0.59
L-MC     0.35
Name: CurrAlloc%, dtype: float64

In [28]:
# sector-wise stats
df_tmp = df_portfolio_features.groupby('Category')[['CurrAlloc%', 'Current', 'Current P/L', 'FTT Amt']].sum().sort_values(by=['Current', 'Current P/L'], ascending=False)
df_tmp['Current P/L%'] = round(df_tmp['Current P/L'] * 100 / df_tmp['Current'], 2)
df_tmp['FTT%'] = round(df_tmp['FTT Amt'] * 100 / df_tmp['Current'], 2)
cols = ['CurrAlloc%', 'Current P/L%', 'FTT%']
df_tmp[cols].sort_values(by=['CurrAlloc%'], ascending=False)

               CurrAlloc%  Current P/L%    FTT%
Category
FMCG                15.16        -16.91   58.39
IT                  11.87        -34.64  103.16
FINANCE             11.36        -15.19   65.30
MISC                 7.22        -31.63   88.81
ELECTRICAL           6.94          1.01   36.90
PAINTS               5.55        -25.90   47.76
BANKS                4.69        -16.47   75.59
INSURANCE            4.65         -3.56   39.00
AUTO                 3.92        -18.44   65.43
PHARMA               3.91         -6.39   39.89
AC                   2.10         -7.88   37.13
HEALTHCARE           1.96        -30.06   64.01
APPARELS             1.90         -0.45   34.71
FOOTWEAR             1.87        -67.02  133.99
TRAVEL               1.84        -72.38  158.69
DURABLES             1.81        -51.10   87.86
BREWERIES            1.64         -1.43   22.49
REALTY               1.49         -5.35   22.66
CERAMICS             1.38        -57.86  105.82
CABLES               1.26         16.86   72.87
REFINERIES           1.24        -14.75   43.78
CEMENT               1.23        -55.16  171.23
ENGINEERING          1.19        -43.95  109.78
JEWELLERY            1.11       -103.87  174.71
CHEMICALS            1.09        -71.69  211.76
ENTERTAINMENT        0.80        -70.94  172.88
TEXTILES             0.46        -43.32   84.19
HOTELS               0.37       -116.95  193.47

In [29]:
# money to be made criteria-wise
df_portfolio_features.groupby('Criteria')['FTT Amt'].agg(['sum', 'count']).sort_values(by='sum', ascending=False)

                sum  count
Criteria
XY24      3657326.0     21
X40       1640792.0     16
XR        1300667.0     12
AR        1216614.0     10
X40N       989568.0      9
OX40N      795132.0     10
XY25       402702.0      5
SR         305147.0      2

In [30]:
# money to be made conviction-wise
df_portfolio_features.groupby('Conviction')['FTT Amt'].agg(['sum', 'count']).sort_values(by='sum', ascending=False)

                  sum  count
Conviction
H-SC        3584748.0     24
X-MC        1548126.0     15
X-LC        1470765.0     13
M-SC        1453270.0     14
X-SC        1378996.0      9
H-MC         341196.0      3
L-SC         207314.0      2
M-LC         149525.0      1
M-MC          74598.0      2
L-MC          53580.0      1
H-LC          45830.0      1

In [31]:
# money to be made criteria and conviction-wise
df_portfolio_features.groupby(['Conviction', 'Criteria'])['FTT Amt'].agg(['sum', 'count']).sort_values(by='sum', ascending=False)

                           sum  count
Conviction Criteria
H-SC       XY24      1173737.0      6
           AR         947201.0      5
M-SC       XY24       852970.0      6
X-SC       XY24       820204.0      4
H-SC       XR         817670.0      7
X-LC       X40        809740.0      7
X-MC       X40        629050.0      7
           X40N       462279.0      4
X-SC       X40N       356790.0      3
M-SC       OX40N      348085.0      5
X-LC       XY24       346354.0      2
H-SC       OX40N      340993.0      4
           SR         305147.0      2
X-MC       XY24       233856.0      2
H-MC       XY24       230205.0      1
X-MC       XY25       222941.0      2
X-SC       X40        202002.0      2
M-SC       XR         178632.0      2
X-LC       X40N       170499.0      2
M-LC       XR         149525.0      1
X-LC       XY25       144172.0      2
H-MC       AR         110991.0      2
L-SC       OX40N      106054.0      1
           XR         101260.0      1
M-SC       AR          73583.0      1
L-MC       XR          53580.0      1
H-LC       AR          45830.0      1
M-MC       AR          39009.0      1
           XY25        35589.0      1

In [32]:
# notebook execution time

end_time = time.time()
execution_time = round(end_time - start_time, 0)
print(f"Notebook execution time: {execution_time} seconds")

Notebook execution time: 46.0 seconds