<a href="https://colab.research.google.com/github/ankit-rathi/Quantvesting_v2/blob/main/myStocks_Portfolio_Analysis.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
'''
!pip install pandas==2.2.2 -qq
!pip install pyxirr -qq
!pip install ta -qq
!pip install yfinance==0.2.59 -qq
'''

'\n!pip install pandas==2.2.2 -qq\n!pip install pyxirr -qq\n!pip install ta -qq\n!pip install yfinance==0.2.59 -qq\n'

In [2]:
# import libraries

import numpy as np
import pandas as pd
import datetime
import warnings
warnings.filterwarnings('ignore')
import yfinance as yfin
import ta
import matplotlib.pyplot as plt
import requests

In [3]:
# notebook start time
import time
import datetime
import pytz

start_time = time.time()

# function to print date timestamp
def print_date_time():
  tz_NY = pytz.timezone('Asia/Kolkata')
  datetime_NY = datetime.datetime.now(tz_NY)
  print("Run date time (IST):", datetime_NY.strftime("%Y-%m-%d %H:%M:%S"))

In [4]:
# function to get booked and reserved amount
def get_amt():
  # fetch the JSON data from the URL
  url = "https://raw.githubusercontent.com/ankit-rathi/Tradevesting_v1/main/data/myPortfolioAmts.json"
  response = requests.get(url)
  pf_amts = response.json()  # parse the JSON data

  # extract values from the JSON
  py_booked_amt_dm = pf_amts["py_booked_amt_dm"]
  py_booked_amt_sv = pf_amts["py_booked_amt_sv"]
  cy_booked_amt_dm = pf_amts["cy_booked_amt_dm"]
  cy_booked_amt_sv = pf_amts["cy_booked_amt_sv"]
  reserve_amt_dm = pf_amts["reserve_amt_dm"]
  reserve_amt_sv = pf_amts["reserve_amt_sv"]

  # perform calculations
  py_booked_amt = py_booked_amt_dm + py_booked_amt_sv
  cy_booked_amt = cy_booked_amt_dm + cy_booked_amt_sv
  reserve_amt = reserve_amt_dm + reserve_amt_sv
  total_booked_amt = py_booked_amt + cy_booked_amt

  return total_booked_amt, reserve_amt, cy_booked_amt, py_booked_amt

gen_output = 0

In [5]:
# function to format the amount
def format_amt(number):
    abs_number = abs(number)

    if abs_number >= 1_00_00_000:  # Crores
        formatted_amt = f"{number / 1_00_00_000:.2f} C"
    elif abs_number >= 1_00_000:  # Lakhs
        formatted_amt = f"{number / 1_00_000:.2f} L"
    elif abs_number >= 1_000:  # Thousands
        formatted_amt = f"{number / 1_000:.2f} K"
    else:
        formatted_amt = f"{number:.2f}"

    return formatted_amt

# function to set start and end date
def get_start_end_date():
  start_date = (datetime.date.today() + datetime.timedelta(days=-365)).strftime('%Y-%m-%d')
  end_date = (datetime.date.today() + datetime.timedelta(days=1)).strftime('%Y-%m-%d')
  return start_date, end_date

# function to fetch my portfolio csv
def get_mypfs_df():
  mypfs_df = pd.read_csv('https://raw.githubusercontent.com/ankit-rathi/Tradevesting_v1/main/data/myPortfolioStocks.csv')
  return mypfs_df

# function to fetch my prospects csv
def get_mypps_df():
  mypps_df = pd.read_csv('https://raw.githubusercontent.com/ankit-rathi/Tradevesting_v1/main/data/myProspectsScrips.csv')
  return mypps_df

# function to fetch screener data
def get_myscreen_df():
  myscreen_df = pd.read_csv('https://raw.githubusercontent.com/ankit-rathi/Tradevesting_v1/main/data/myScreenerDB.csv')
  return myscreen_df

# function to fetch momentum data
def get_myinvmt_df():
  myinvmt_df = pd.read_csv('https://raw.githubusercontent.com/ankit-rathi/Tradevesting_v1/main/data/myInvestments.csv')
  return myinvmt_df

# function to get the stock ids
def get_stock_ids(df_pf):
  stock_n100 = df_pf['Symbol'].unique()

  exclude = ['CADILAHC','MMTC', 'MASFIN']

  stock_ids = df_pf[~df_pf['Symbol'].isin(exclude) ]['Symbol'].unique()

  #mypf = mypf[mypf.Forecast.notnull()]
  #stock_ids = mypf['Symbol'].unique()

  #stock_ids.sort()
  return stock_ids

# get features from screener data
def get_screener_features():
  myscreen_df = get_myscreen_df()
  cols = ['Symbol', 'EPS', 'MedPE', 'ROCE%', 'ROE%', 'CapType']
  return myscreen_df[cols]

# get relative strength
def get_relative_strength(stock_list):

    # Dictionary to store stock tickers and their corresponding percentage price change
    stock_changes = {}

    # Loop through each stock and fetch its price data
    for stock in stock_list:
        try:
            # Download the stock data for the given date range
            stock_data = yfin.Ticker(stock + '.NS').history(period='1mo', interval='1d')[map(str.title, ['open', 'close', 'low', 'high', 'volume'])]

            # Calculate the percentage change for the stock
            if len(stock_data) > 0:
                start_price = stock_data['Close'].iloc[0]
                end_price = stock_data['Close'].iloc[-1]
                percent_change = round(((end_price - start_price) / start_price) * 100, 2)
                stock_changes[stock] = percent_change
            else:
                stock_changes[stock] = np.nan  # If no data is available, set to NaN

        except Exception as e:
            print(f"Error fetching data for {stock}: {e}")
            stock_changes[stock] = np.nan

    # Create a DataFrame with stock tickers and their percentage changes
    df = pd.DataFrame(list(stock_changes.items()), columns=['Symbol', 'Percent_Change'])

    # Drop any stocks with missing data (NaN values)
    df = df.dropna()

    # Calculate the percentile rank based on percentage change
    df['RSP'] = round(df['Percent_Change'].rank(pct=True) * 100, 2)
    cols = ['Symbol', 'RSP']
    df = df[cols]
    # Sort by percentile rank (optional)
    df = df.sort_values(by='RSP', ascending=False).reset_index(drop=True)

    return df

In [6]:
# function to get stock technicals
def stock_prec_dev(stock_symbol):
    #stock_symbol = 'ULTRACEMCO.NS'
    short_window = 20
    mid_window = 50
    long_window = 200
    moving_avg = 'SMA'

    start = datetime.datetime(*map(int, start_date.split('-')))
    end = datetime.datetime(*map(int, end_date.split('-')))

    stock_df = yfin.Ticker(stock_symbol + '.NS').history(period='max', interval='1d')[map(str.title, ['open', 'close', 'low', 'high', 'volume'])]

    stock_df['Max'] = round(max(stock_df['Close']),2)
    stock_df = stock_df[(stock_df.index <= end_date) & (stock_df.index >= start_date)]
    stock_df['200_SMA'] = round(stock_df['Close'].rolling(window = 200, min_periods = 1).mean(),0)
    stock_df['Dev%_200'] = round((stock_df['Close'] - stock_df['200_SMA'])*100/stock_df['200_SMA'],2)
    stock_df.dropna(axis = 0, inplace = True) # remove any null rows

    stock_df['20_SMA'] = stock_df['Close'].rolling(window=20).mean()
    stock_df['50_SMA'] = stock_df['Close'].rolling(window=50).mean()
    stock_df['Symbol'] = stock_symbol

    stock_df['Close'] = round(stock_df['Close'],2)
    stock_df['Min'] = round(min(stock_df['Close']),2)
    stock_df['RSI_14'] = ta.momentum.RSIIndicator(close=stock_df['Close'], window=14).rsi()
    stock_df['RSI_14'] = round(stock_df['RSI_14'],0)
    stock_df['Prev_Close'] = stock_df['Close'].shift(1)
    stock_df.drop(['Open', 'Low', 'High', 'Volume'], axis=1, inplace=True)
    stock_df = stock_df.tail(1)

    max_SMA = max(stock_df['20_SMA'].item(), stock_df['50_SMA'].item(), stock_df['200_SMA'].item())
    min_SMA = min(stock_df['20_SMA'].item(), stock_df['50_SMA'].item(), stock_df['200_SMA'].item())
    ABS_Spread = max_SMA - min_SMA
    stock_df['Spread%'] = round((ABS_Spread / stock_df['200_SMA'].item()) * 100,2)

    return stock_df

# function to compute stock attributes
def get_common_features(stock_ids, df_mypf):

  df_prec_dev = pd.DataFrame()
  df_tmp = get_screener_features()
  df_rs = get_relative_strength(stock_ids)

  for stock_id in stock_ids:
      tmp = stock_prec_dev(stock_id)
      tmp = tmp.reset_index()
      df_prec_dev = pd.concat([df_prec_dev, tmp], ignore_index = True)
  df_prec_dev = pd.merge(df_prec_dev, df_mypf, on= 'Symbol')
  df_prec_dev = pd.merge(df_prec_dev, df_tmp, on= 'Symbol', how='left')
  df_prec_dev = pd.merge(df_prec_dev, df_rs, on= 'Symbol', how='left')
  #print(df_prec_dev.columns)
  df_prec_dev['Curr_PE'] = round(df_prec_dev['Close']/df_prec_dev['EPS'],1)
  df_prec_dev['Dev%_PE'] = round((df_prec_dev['Curr_PE'] - df_prec_dev['MedPE'])*100/df_prec_dev['MedPE'],2)
  df_prec_dev['Conviction'] = df_prec_dev['Conviction'] + '-' + df_prec_dev['CapType']
  return df_prec_dev

# function to arrange stock features
def arrange_features(df_stocks, common_cols, diff_cols):
  df_stocks_common = df_stocks[common_cols].drop_duplicates()
  df_stocks_diff = df_stocks[diff_cols]
  df_stocks_diff['Investment'] = df_stocks_diff['AvgCost'] * df_stocks_diff['Shares']
  df_stocks_diff = df_stocks_diff.groupby(['Symbol'])[['Shares', 'Investment']].aggregate(['sum']).reset_index()
  df_stocks_diff.columns = ['Symbol', 'Shares', 'Investment']
  df_stocks_diff['AvgCost'] = round(df_stocks_diff['Investment']/df_stocks_diff['Shares'],2)
  df_stocks = pd.merge(df_stocks_diff, df_stocks_common, on='Symbol')
  return df_stocks

# plot fact distribution across dimension
def plot_pie_chart(df, dimension, fact):
  # grouping the data by category and calculating the sum of fact for each type
  grouped_data = df.groupby(dimension)[fact].sum()

  # sorting the grouped data in descending order
  grouped_data = grouped_data.sort_values(ascending=False)

  # creating a pie chart
  grouped_data.plot.pie(autopct='%1.1f%%', startangle=90, figsize=(6, 6))

  # adding a title and displaying the plot
  plt.title(f'{dimension} {fact} Distribution')
  plt.ylabel('')  # To hide the y-label
  plt.show()

In [7]:
# function to get portfolio features

def get_portfolio_features(df_common_features):

  print_date_time()
  print('-------------------')

  #df_common_features["Target"] = df_common_features["Target"].fillna(df_common_features["Max"])
  df_common_features['NTT'] = np.where(df_common_features['Strategy']== 'NTT', df_common_features["Target"], df_common_features['Max'])
  df_common_features['LTT'] = np.where(df_common_features['Strategy']== 'BTT', df_common_features["Target"], df_common_features['Max'])
  df_common_features['BOL'] = df_common_features['Min']

  tmp_df = df_common_features[df_common_features['Symbol'].isin(mypf_df[mypf_df['InPortfolio'] != 'NA'].Symbol.values)]
  print('qualified stocks: '+str(len(tmp_df['Symbol'].unique())))
  tmp_df1 = tmp_df[tmp_df['LatestQtr'] == 1]
  print('with latest results: '+str(len(tmp_df1['Symbol'].unique())))
  tmp_df1 = tmp_df1[tmp_df1['StarStock'] == 1]
  print('still star stocks: '+str(len(tmp_df1['Symbol'].unique())))
  tmp_df['Investment'] = tmp_df['AvgCost'] * tmp_df['Shares']
  tmp_df['Current'] = round(tmp_df['Close'] * tmp_df['Shares'],0)
  tmp_df['Previous'] = tmp_df['Prev_Close'] * tmp_df['Shares']
  tmp_df['EstimatedST'] = tmp_df['NTT'] * tmp_df['Shares']
  tmp_df['EstimatedLT'] = tmp_df['LTT'] * tmp_df['Shares']
  tmp_df['Current P/L'] = round((tmp_df['Current'] - tmp_df['Investment']),0)
  tmp_df['Today P/L%'] = round((tmp_df['Current'] - tmp_df['Previous'])*100/tmp_df['Previous'],2)
  tmp_df['Current P/L%'] = round((tmp_df['Current'] - tmp_df['Investment'])*100/tmp_df['Investment'],2)
  tmp_df['EstimatedST P/L%'] = round((tmp_df['EstimatedST'] - tmp_df['Investment'])*100/tmp_df['Investment'],2)
  tmp_df['EstimatedLT P/L%'] = round((tmp_df['EstimatedLT'] - tmp_df['Investment'])*100/tmp_df['Investment'],2)
  tmp_df['NTT%'] = round((tmp_df['NTT'] - tmp_df['Close'])*100/tmp_df['Close'],2)
  tmp_df['LTT%'] = round((tmp_df['LTT'] - tmp_df['Close'])*100/tmp_df['Close'],2)
  tmp_df['Gained%'] = round((tmp_df['Close'] - tmp_df['BOL'])*100/tmp_df['BOL'],2)
  investment = round(sum(tmp_df['AvgCost']*tmp_df['Shares']),0)
  current = round(sum(tmp_df['Close']*tmp_df['Shares']),0)
  tmp_df['InitAlloc%'] = round(tmp_df['Investment']*100/investment,2)
  tmp_df['CurrAlloc%'] = round(tmp_df['Current']*100/current,2)
  tmp_df['FTT'] = tmp_df['LTT']
  tmp_df.loc[tmp_df['Strategy'] == 'NTT', 'FTT'] = tmp_df['NTT']
  tmp_df['FTT%'] = tmp_df['LTT%']
  tmp_df.loc[tmp_df['Strategy'] == 'NTT', 'FTT%'] = tmp_df['NTT%']
  tmp_df['FTT Amt'] = round(tmp_df['FTT%'] * tmp_df['Current']/100,0)
  tmp_df['OTT%'] = round((tmp_df['FTT'] - tmp_df['AvgCost'])*100/tmp_df['AvgCost'],2)
  tmp_df['RRR Ind'] = round(tmp_df['Current P/L']/tmp_df['FTT Amt'],2)
  tmp_df['Risk Ind'] = round(tmp_df['Current P/L%']*tmp_df['CurrAlloc%'],0)

  return tmp_df

# function to print portfolio features
def print_portfolio_stats(df_portfolio_features, myinvmt_df):
  from pyxirr import xirr

  total_booked_amt, reserve_amt, cy_booked_amt, py_booked_amt = get_amt()

  dates = myinvmt_df['Date'].values
  dates = np.append(dates, datetime.date.today().strftime('%d-%b-%y'))
  investment = myinvmt_df['Investment'].values
  dates= pd.to_datetime(dates)

  current = round(sum(df_portfolio_features['Close']*df_portfolio_features['Shares']),0) + reserve_amt
  investment_xirr = np.append(investment, current)
  cagr = round(xirr(pd.DataFrame({"dates": dates, "amounts": investment_xirr}))*100,2)

  investment = -sum(investment)
  invested = round(sum(df_portfolio_features['AvgCost']*df_portfolio_features['Shares']),0) + reserve_amt
  previous = round(sum(df_portfolio_features['Prev_Close']*df_portfolio_features['Shares']),0) + reserve_amt
  cy_invested = investment + py_booked_amt

  today_pnl_amount = current-previous
  today_pnl_percentage = round((current-previous)*100/previous,2)

  curr_pnl_amount = current-invested
  curr_pnl_percentage = round((curr_pnl_amount)*100/(cy_invested),2)

  cy_pnl_amount = cy_booked_amt + curr_pnl_amount
  cy_pnl_percentage = round((cy_pnl_amount)*100/cy_invested,2)

  overall_pnl_amount = total_booked_amt + curr_pnl_amount
  overall_pnl_percentage = round((overall_pnl_amount)*100/investment,2)

  estimate_st = round(sum(df_portfolio_features['FTT']*df_portfolio_features['Shares']),0)  + reserve_amt
  est_st_pnl_amount = estimate_st-current
  est_st_pnl_percentage = round((est_st_pnl_amount)*100/current,2)

  estimate_lt = round(sum(df_portfolio_features['LTT']*df_portfolio_features['Shares']),0)  + reserve_amt
  est_lt_pnl_amount = estimate_lt-current
  est_lt_pnl_percentage = round((est_lt_pnl_amount)*100/current,2)

  total_profit = round(sum(df_portfolio_features[df_portfolio_features['Current P/L%'] > 0]['Current']) - sum(df_portfolio_features[df_portfolio_features['Current P/L%'] > 0]['Investment']),0)
  total_loss = round(sum(df_portfolio_features[df_portfolio_features['Current P/L%'] < 0]['Current']) - sum(df_portfolio_features[df_portfolio_features['Current P/L%'] < 0]['Investment']),0)

  cy_booked_percentage = round((cy_booked_amt)*100/current,2)
  py_booked_percentage = round((py_booked_amt)*100/investment,2)
  total_booked_percentage = round((total_booked_amt)*100/investment,2)

  print('-------------------')
  print('Initial Investment: ', format_amt(investment))
  print('CY Investment: ', format_amt(cy_invested))
  print('Reserve: ', format_amt(reserve_amt))
  print('Current: ',  format_amt(current))
  print('-------------------')
  print('Today PnL: '+ '{} ({}%)'.format(format_amt(today_pnl_amount), today_pnl_percentage))
  print('Current PnL: '+ '{} ({}%)'.format(format_amt(curr_pnl_amount), curr_pnl_percentage))
  print('CY Booked + Current PnL: '+ '{} ({}%)'.format(format_amt(cy_pnl_amount), cy_pnl_percentage))
  print('-------------------')
  print('Total profit: ', format_amt(total_profit))
  print('Total loss: ', format_amt(total_loss))
  print('-------------------')
  print('Total Booked + Current PnL: '+ '{} ({}%)'.format(format_amt(overall_pnl_amount), overall_pnl_percentage))
  print('Total Booked PnL: '+ '{} ({}%)'.format(format_amt(total_booked_amt), total_booked_percentage))
  print('Curr Year Booked PnL: '+ '{} ({}%)'.format(format_amt(cy_booked_amt), cy_booked_percentage))
  print('Prev Year Booked PnL: '+ '{} ({}%)'.format(format_amt(py_booked_amt), py_booked_percentage))
  print('===================')
  print('Est FTT: ',  format_amt(estimate_st))
  print('Est FTT PnL: '+ '{} ({}%)'.format(format_amt(est_st_pnl_amount), est_st_pnl_percentage))

  print('===================')
  print('Deployed: ', format_amt(investment))

  print('Current: ', format_amt(current))

  print('CAGR/XIRR %: '+'{}%'.format(cagr))

In [8]:
# get start and end date
start_date, end_date = get_start_end_date()

# get portfolio and prospects data
mypfs_df = get_mypfs_df()
mypps_df = get_mypps_df()
myinvmt_df = get_myinvmt_df()

# merge above datasets
mypf_df = pd.merge(mypfs_df, mypps_df, on="Symbol")

# seggregate dm and sv portfolio
dm_pf = mypf_df[mypf_df['InPortfolio'] == 'DM']
sv_pf = mypf_df[mypf_df['InPortfolio'] == 'SV']

# build portfolio stock dataframe
dm_stocks = get_stock_ids(dm_pf)
sv_stocks = get_stock_ids(sv_pf)
df_stocks = pd.concat([dm_pf,sv_pf], ignore_index = True)

# arrange common and diff stock features
common_cols = ['Symbol', 'Target', 'Criteria', 'Strategy', 'CumlRnk', 'LatestQtr', 'StarStock', 'Conviction', 'Category', 'InFolio', 'XIRR', 'MBQ']
diff_cols = ['Symbol', 'AvgCost', 'Shares']
df_stocks = arrange_features(df_stocks, common_cols, diff_cols)

# get common features
stock_ids = df_stocks['Symbol'].values
df_common_features = get_common_features(stock_ids, df_stocks)

df_common_features.reset_index(drop=True, inplace=True)
df_common_features.drop(['Date'], axis=1, inplace=True)
# get and print portfolio features
df_portfolio_features = get_portfolio_features(df_common_features)

print_portfolio_stats(df_portfolio_features, myinvmt_df)

df = df_portfolio_features
#plot_pie_chart(df, 'CapType', 'Current')
list_ox40n = list(df[df['MBQ'].str.contains('OX40N', na=False)]['Symbol'].values)

Run date time (IST): 2026-08-19 11:16:24
-------------------
qualified stocks: 87
with latest results: 30
still star stocks: 19
-------------------
Initial Investment:  1.46 C
CY Investment:  1.89 C
Reserve:  3.69 L
Current:  1.57 C
-------------------
Today PnL: -69.58 K (-0.44%)
Current PnL: -35.45 L (-18.77%)
CY Booked + Current PnL: -30.39 L (-16.09%)
-------------------
Total profit:  3.40 L
Total loss:  -38.85 L
-------------------
Total Booked + Current PnL: 12.48 L (8.54%)
Total Booked PnL: 47.93 L (32.82%)
Curr Year Booked PnL: 5.06 L (3.21%)
Prev Year Booked PnL: 42.87 L (29.35%)
===================
Est FTT:  2.67 C
Est FTT PnL: 1.10 C (69.6%)
===================
Deployed:  1.46 C
Current:  1.57 C
CAGR/XIRR %: 3.42%

In [9]:
# top 5 near their targets
cols = ['Symbol', 'Today P/L%', 'Current P/L%', 'FTT%', 'OTT%', 'FTT Amt', 'Current P/L', 'Current', 'FTT', 'Dev%_PE', 'RSI_14','Conviction', 'Spread%',  'CumlRnk', 'RRR Ind', 'CurrAlloc%', 'Gained%', 'Criteria', 'Strategy', 'Category']
df_tmp = df_portfolio_features[~df_portfolio_features['Symbol'].isin(['ENRIN','BLUSPRING','DIGITIDE'])]
df_tmp = df_tmp.sort_values(by = 'FTT Amt', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
66,SIEMENS,-1.10,5.15,5.40,10.83,10567.0,9585.0,195680.0,4125.00,-14.90,58.0,H-LC,13.94,51.0,0.91,1.27,38.06,AR,NTT,ELECTRICAL
78,UNITDSPR,0.10,11.83,7.99,20.77,20922.0,27709.0,261853.0,1644.00,-4.62,61.0,X-MC,10.88,64.0,1.32,1.70,25.87,X40N,NTT,BREWERIES
77,TTKPRESTIG,-1.82,-24.11,31.89,0.09,24389.0,-24299.0,76478.0,770.00,-7.57,39.0,M-SC,9.64,250.0,-1.00,0.50,37.65,OX40N,NTT,DURABLES
52,M&M,-0.06,7.97,10.05,18.82,26117.0,19186.0,259867.0,3762.88,-6.96,58.0,X-LC,4.86,25.0,0.73,1.69,17.88,X40N,ATH,AUTO
67,SIS,1.20,-3.21,25.28,21.26,27168.0,-3562.0,107470.0,528.00,106.30,43.0,H-SC,21.05,168.0,-0.13,0.70,59.79,OX40N,NTT,MISC

In [10]:
# top 5 today
df_tmp = df_portfolio_features.sort_values(by = 'Today P/L%', ascending=False)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
0,5PAISA,6.79,-22.58,45.83,12.90,77529.0,-49330.0,169166.0,593.00,8.48,67.0,H-SC,11.35,170.0,-0.64,1.10,63.25,OX40N,NTT,FINANCE
27,GLAXO,4.40,20.60,12.52,35.69,30089.0,41044.0,240328.0,3380.16,-9.68,85.0,X-MC,9.81,56.0,1.36,1.56,42.83,X40,ATH,PHARMA
74,TITAGARH,2.06,-21.12,84.75,45.74,161907.0,-51136.0,191041.0,1548.00,NaN,49.0,NaN,7.68,175.0,-0.32,1.24,45.76,XY24,NTT,ENGINEERING
65,SHALBY,1.76,-40.38,109.82,25.10,118610.0,-73139.0,108004.0,327.00,NaN,38.0,NaN,7.72,236.0,-0.62,0.70,22.91,XY24,NTT,HEALTHCARE
62,REPCOHOME,1.72,-23.30,147.47,89.82,324082.0,-66744.0,219761.0,880.00,NaN,31.0,NaN,4.14,161.0,-0.21,1.43,5.64,XY24,NTT,FINANCE

In [11]:
# bottom 5 today
df_tmp = df_portfolio_features.sort_values(by = 'Today P/L%', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
81,VALIANTORG,-3.67,-38.28,182.15,74.15,183935.0,-62625.0,100980.0,838.00,NaN,52.0,NaN,6.83,145.0,-0.34,0.66,50.27,XR,NTT,CHEMICALS
25,FINCABLES,-3.39,62.66,27.82,107.91,66814.0,92520.0,240164.0,1641.55,18.30,69.0,M-SC,19.81,220.0,1.38,1.56,80.68,OX40N,ATH,CABLES
29,GREENPANEL,-3.18,-56.23,227.04,43.14,181927.0,-102948.0,80130.0,537.00,NaN,27.0,NaN,11.25,225.0,-0.57,0.52,0.00,XY24,NTT,MISC
30,HAPPSTMNDS,-2.89,-49.09,259.62,83.08,169397.0,-62917.0,65248.0,1466.54,NaN,58.0,NaN,7.64,152.0,-0.37,0.42,22.21,AR,ATH,IT
11,BERGEPAINT,-2.73,-1.53,27.26,25.32,69190.0,-3933.0,253816.0,680.00,-14.42,54.0,X-MC,5.22,68.0,-0.06,1.65,33.10,XY24,NTT,PAINTS

In [12]:
# top 5 to exit based on CumlRnk
df_tmp = df_portfolio_features[~df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])]
df_tmp = df_tmp[(df_tmp['Current P/L%'] > -1) & (df_tmp['Current P/L%'] < 1)].sort_values(by = 'CumlRnk', ascending=False)
df_tmp[cols].head()

Empty DataFrame
Columns: [Symbol, Today P/L%, Current P/L%, FTT%, OTT%, FTT Amt, Current P/L, Current, FTT, Dev%_PE, RSI_14, Conviction, Spread%, CumlRnk, RRR Ind, CurrAlloc%, Gained%, Criteria, Strategy, Category]
Index: []

In [13]:
# OX40N stocks to exit
df_tmp = df_portfolio_features[(df_portfolio_features['Symbol'].isin(list_ox40n))].sort_values(by = 'Current P/L%', ascending=False)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
25,FINCABLES,-3.39,62.66,27.82,107.91,66814.0,92520.0,240164.0,1641.55,18.30,69.0,M-SC,19.81,220.0,1.38,1.56,80.68,OX40N,ATH,CABLES
67,SIS,1.20,-3.21,25.28,21.26,27168.0,-3562.0,107470.0,528.00,106.30,43.0,H-SC,21.05,168.0,-0.13,0.70,59.79,OX40N,NTT,MISC
43,INDIGOPNTS,-2.14,-19.29,23.92,0.02,33701.0,-33670.0,140889.0,1408.00,-22.93,59.0,M-SC,6.97,222.0,-1.00,0.92,59.85,OX40N,NTT,PAINTS
0,5PAISA,6.79,-22.58,45.83,12.90,77529.0,-49330.0,169166.0,593.00,8.48,67.0,H-SC,11.35,170.0,-0.64,1.10,63.25,OX40N,NTT,FINANCE
77,TTKPRESTIG,-1.82,-24.11,31.89,0.09,24389.0,-24299.0,76478.0,770.00,-7.57,39.0,M-SC,9.64,250.0,-1.00,0.50,37.65,OX40N,NTT,DURABLES

In [14]:
# top 5 to book for rotation
df_tmp = df_portfolio_features[(df_portfolio_features['Current P/L%'] > 20) ].sort_values(by = 'CumlRnk', ascending=False)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
25,FINCABLES,-3.39,62.66,27.82,107.91,66814.0,92520.0,240164.0,1641.55,18.30,69.0,M-SC,19.81,220.0,1.38,1.56,80.68,OX40N,ATH,CABLES
27,GLAXO,4.40,20.60,12.52,35.69,30089.0,41044.0,240328.0,3380.16,-9.68,85.0,X-MC,9.81,56.0,1.36,1.56,42.83,X40,ATH,PHARMA

In [15]:
# top 5 to monitor for exit
df_tmp = df_portfolio_features[~df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])]
df_tmp = df_tmp[(df_tmp['Current P/L%'] > 0) ].sort_values(by = 'Dev%_PE', ascending=False)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
25,FINCABLES,-3.39,62.66,27.82,107.91,66814.0,92520.0,240164.0,1641.55,18.30,69.0,M-SC,19.81,220.0,1.38,1.56,80.68,OX40N,ATH,CABLES
68,STARHEALTH,-0.05,13.00,30.32,47.26,96317.0,36546.0,317669.0,761.00,-0.37,50.0,H-SC,16.24,173.0,0.38,2.07,37.35,XY24,NTT,INSURANCE

In [16]:
# top 5 to book for rotation from weak conviction
df_tmp = df_portfolio_features[~df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])]
df_tmp = df_tmp[~df_tmp['Criteria'].isin(['XY25','XY24','X40', 'X40N'])].sort_values(by = 'RRR Ind', ascending=False)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
25,FINCABLES,-3.39,62.66,27.82,107.91,66814.0,92520.0,240164.0,1641.55,18.3,69.0,M-SC,19.81,220.0,1.38,1.56,80.68,OX40N,ATH,CABLES
67,SIS,1.20,-3.21,25.28,21.26,27168.0,-3562.0,107470.0,528.00,106.3,43.0,H-SC,21.05,168.0,-0.13,0.70,59.79,OX40N,NTT,MISC
3,ALKYLAMINE,0.85,-17.52,133.45,92.54,111124.0,-17693.0,83270.0,4520.85,NaN,58.0,NaN,14.18,142.0,-0.16,0.54,58.12,SR,ATH,CHEMICALS
42,INDIAMART,-0.74,-25.22,168.68,100.92,155575.0,-31105.0,92231.0,4675.60,NaN,35.0,NaN,13.69,140.0,-0.20,0.60,0.00,AR,ATH,MISC
71,TANLA,-0.31,-35.02,234.35,117.25,412304.0,-94826.0,175935.0,1922.32,NaN,46.0,NaN,15.74,147.0,-0.23,1.14,54.03,AR,ATH,IT

In [17]:
# top 5 to accumulate based on lowest RSI_14
df_tmp = df_portfolio_features[df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])].sort_values(by = 'RSI_14', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
19,COLPAL,-1.28,-28.67,96.07,39.86,180477.0,-75505.0,187860.0,3683.41,-13.63,27.0,X-MC,1.56,62.0,-0.42,1.22,6.26,XY25,ATH,FMCG
56,PGHH,-1.21,-38.08,113.19,32.01,149655.0,-81304.0,132216.0,17616.87,-54.51,28.0,X-SC,19.11,57.0,-0.54,0.86,0.00,X40,ATH,FMCG
55,PAGEIND,-1.85,-7.26,43.26,32.85,107668.0,-19494.0,248885.0,50936.07,-31.08,29.0,X-MC,8.76,55.0,-0.18,1.62,18.85,X40,ATH,APPARELS
34,HDFCBANK,-0.96,-12.55,49.85,31.05,127788.0,-36774.0,256346.0,1073.00,-29.51,30.0,X-LC,12.80,26.0,-0.29,1.67,0.00,X40,BTT,BANKS
47,ITC,-0.74,-26.06,68.66,24.70,201674.0,-103550.0,293728.0,452.00,-31.16,30.0,X-LC,10.67,1.0,-0.51,1.91,0.00,X40,NTT,FMCG

In [18]:
# top 5 to accumulate based on Spread and CumlRnk
df_tmp = df_portfolio_features[df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])]
df_tmp = df_tmp[(df_tmp['CumlRnk'] < 100)].sort_values(by = 'Spread%', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
19,COLPAL,-1.28,-28.67,96.07,39.86,180477.0,-75505.0,187860.0,3683.41,-13.63,27.0,X-MC,1.56,62.0,-0.42,1.22,6.26,XY25,ATH,FMCG
23,DMART,-0.18,-2.79,35.20,31.42,106684.0,-8710.0,303080.0,5391.45,-18.52,47.0,X-LC,2.31,14.0,-0.08,1.97,9.37,X40N,ATH,FMCG
50,KOTAKBANK,0.32,2.21,16.34,18.92,40034.0,5305.0,245007.0,452.46,-13.30,49.0,X-LC,2.33,12.0,0.13,1.59,10.24,X40,ATH,BANKS
26,GILLETTE,-0.88,-11.35,46.33,29.72,104284.0,-28806.0,225090.0,10978.86,-36.01,36.0,X-SC,3.49,83.0,-0.28,1.46,3.44,X40,ATH,FMCG
1,ABBOTINDIA,-1.69,-11.27,30.02,15.37,47642.0,-20155.0,158700.0,34390.26,-27.79,37.0,X-MC,4.05,58.0,-0.42,1.03,7.50,X40,ATH,PHARMA

In [19]:
# top 5 to accumulate based on lowest Gained%
df_tmp = df_portfolio_features[df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])].sort_values(by = 'Gained%', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
20,DABUR,-0.77,-21.72,83.57,43.70,162288.0,-53874.0,194194.0,735.00,-32.48,34.0,X-MC,10.02,70.0,-0.33,1.26,0.0,XY24,BTT,FMCG
36,HINDUNILVR,-0.80,-16.02,44.75,21.56,126472.0,-53899.0,282618.0,2922.00,-42.16,37.0,X-LC,6.40,9.0,-0.43,1.84,0.0,XY25,NTT,FMCG
34,HDFCBANK,-0.96,-12.55,49.85,31.05,127788.0,-36774.0,256346.0,1073.00,-29.51,30.0,X-LC,12.80,26.0,-0.29,1.67,0.0,X40,BTT,BANKS
35,HDFCLIFE,-0.65,-8.29,51.74,39.15,118972.0,-20795.0,229942.0,811.41,-32.57,39.0,X-LC,16.63,31.0,-0.17,1.50,0.0,X40,ATH,INSURANCE
47,ITC,-0.74,-26.06,68.66,24.70,201674.0,-103550.0,293728.0,452.00,-31.16,30.0,X-LC,10.67,1.0,-0.51,1.91,0.0,X40,NTT,FMCG

In [20]:
# top 5 to accumulate based on lowest CurrAlloc%
df_tmp = df_portfolio_features[df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])].sort_values(by = 'CurrAlloc%', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
56,PGHH,-1.21,-38.08,113.19,32.01,149655.0,-81304.0,132216.0,17616.87,-54.51,28.0,X-SC,19.11,57.0,-0.54,0.86,0.00,X40,ATH,FMCG
2,ACC,-1.10,-42.29,202.91,74.81,313983.0,-113388.0,154740.0,3906.00,-42.69,33.0,X-SC,11.42,85.0,-0.36,1.01,3.38,XY24,BTT,CEMENT
1,ABBOTINDIA,-1.69,-11.27,30.02,15.37,47642.0,-20155.0,158700.0,34390.26,-27.79,37.0,X-MC,4.05,58.0,-0.42,1.03,7.50,X40,ATH,PHARMA
40,ICICIPRULI,-2.14,-17.90,58.68,30.28,94912.0,-35260.0,161745.0,787.27,-47.40,43.0,X-MC,12.48,78.0,-0.37,1.05,7.76,X40,ATH,INSURANCE
39,ICICIGI,-0.62,-14.39,38.87,18.89,66591.0,-28792.0,171317.0,2244.41,-14.59,40.0,X-MC,10.34,66.0,-0.43,1.11,2.07,X40,ATH,INSURANCE

In [21]:
# top 5 to accumulate based on CumlRnk
df_tmp = df_portfolio_features.sort_values(by = 'CumlRnk', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
47,ITC,-0.74,-26.06,68.66,24.70,201674.0,-103550.0,293728.0,452.00,-31.16,30.0,X-LC,10.67,1.0,-0.51,1.91,0.00,X40,NTT,FMCG
73,TCS,-0.70,-33.54,86.87,24.20,267476.0,-155369.0,307904.0,4230.71,-44.98,45.0,X-LC,14.12,2.0,-0.58,2.00,14.82,X40,ATH,IT
45,INFY,0.13,-20.53,76.64,40.38,229303.0,-77275.0,299195.0,1972.00,-41.63,46.0,X-LC,15.84,3.0,-0.34,1.95,13.31,X40,NTT,IT
75,TMPV,-0.31,-23.44,86.45,42.75,275414.0,-97525.0,318582.0,600.00,-84.91,35.0,X-LC,4.53,4.0,-0.35,2.07,9.55,XY24,NTT,AUTO
33,HCLTECH,0.51,-12.74,42.07,23.97,113611.0,-39434.0,270052.0,1853.42,-15.10,52.0,X-LC,11.11,8.0,-0.35,1.76,27.43,X40,ATH,IT

In [22]:
# top 5 for average up
df_tmp = df_portfolio_features[(df_portfolio_features['Dev%_200'] > 5)].sort_values(by = 'CurrAlloc%', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
44,INDUSINDBK,-0.12,-25.48,78.32,32.89,45062.0,-19670.0,57536.0,1800.00,323.79,50.0,L-MC,12.73,258.0,-0.44,0.37,41.85,XR,NTT,BANKS
60,RELAXO,-1.37,-50.03,204.78,52.31,148547.0,-72620.0,72540.0,1176.00,NaN,42.0,NaN,12.28,92.0,-0.49,0.47,62.19,X40N,NTT,FOOTWEAR
3,ALKYLAMINE,0.85,-17.52,133.45,92.54,111124.0,-17693.0,83270.0,4520.85,NaN,58.0,NaN,14.18,142.0,-0.16,0.54,58.12,SR,ATH,CHEMICALS
12,BOSCH-HCIL,0.86,-24.85,33.06,-0.01,31751.0,-31765.0,96040.0,2282.00,749.75,76.0,M-SC,6.82,231.0,-1.00,0.62,63.47,OX40N,BTT,AC
81,VALIANTORG,-3.67,-38.28,182.15,74.15,183935.0,-62625.0,100980.0,838.00,NaN,52.0,NaN,6.83,145.0,-0.34,0.66,50.27,XR,NTT,CHEMICALS

In [23]:
# top 5 RSP
df_tmp = df_portfolio_features.sort_values(by = 'RSP', ascending=False)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
12,BOSCH-HCIL,0.86,-24.85,33.06,-0.01,31751.0,-31765.0,96040.0,2282.00,749.75,76.0,M-SC,6.82,231.0,-1.00,0.62,63.47,OX40N,BTT,AC
25,FINCABLES,-3.39,62.66,27.82,107.91,66814.0,92520.0,240164.0,1641.55,18.30,69.0,M-SC,19.81,220.0,1.38,1.56,80.68,OX40N,ATH,CABLES
27,GLAXO,4.40,20.60,12.52,35.69,30089.0,41044.0,240328.0,3380.16,-9.68,85.0,X-MC,9.81,56.0,1.36,1.56,42.83,X40,ATH,PHARMA
38,HYUNDAI,1.03,14.24,26.00,43.94,74651.0,35786.0,287118.0,2782.73,18.18,65.0,X-LC,5.33,29.0,0.48,1.87,31.83,X40N,ATH,AUTO
81,VALIANTORG,-3.67,-38.28,182.15,74.15,183935.0,-62625.0,100980.0,838.00,NaN,52.0,NaN,6.83,145.0,-0.34,0.66,50.27,XR,NTT,CHEMICALS

In [24]:
# Top N allocation
df_tmp = df_portfolio_features.sort_values(by = 'CurrAlloc%', ascending=False)
top_n_values = [10, 25, 50]

sum_df = pd.DataFrame({
    'Top_N': top_n_values,
    'Sum_Alloc%': [df_tmp['CurrAlloc%'].head(n).sum() for n in top_n_values]
})

sum_df

   Top_N  Sum_Alloc%
0     10       19.75
1     25       45.04
2     50       77.65

In [25]:
# market-cap-wise allocation
df_tmp = df_portfolio_features[cols]
df_tmp.groupby(df_tmp['Conviction'].str[-2:])['CurrAlloc%'].sum().sort_values(ascending=False)

Conviction
LC    38.05
MC    22.24
SC    21.61
Name: CurrAlloc%, dtype: float64

In [26]:
# criteria-wise allocation
df_portfolio_features.groupby('Criteria')['CurrAlloc%'].sum().sort_values(ascending=False)

Criteria
X40      26.62
XY24     24.03
X40N     18.70
XR        9.07
OX40N     7.36
XY25      7.20
AR        6.14
SR        0.87
Name: CurrAlloc%, dtype: float64

In [27]:
# conviction-wise allocation
df_portfolio_features.groupby('Conviction')['CurrAlloc%'].sum().sort_values(ascending=False)

Conviction
X-LC    34.36
X-MC    19.62
H-SC     8.57
X-SC     7.63
M-SC     5.41
H-LC     2.88
M-MC     1.21
H-MC     1.04
M-LC     0.81
L-MC     0.37
Name: CurrAlloc%, dtype: float64

In [28]:
# sector-wise stats
df_tmp = df_portfolio_features.groupby('Category')[['CurrAlloc%', 'Current', 'Current P/L', 'FTT Amt']].sum().sort_values(by=['Current', 'Current P/L'], ascending=False)
df_tmp['Current P/L%'] = round(df_tmp['Current P/L'] * 100 / df_tmp['Current'], 2)
df_tmp['FTT%'] = round(df_tmp['FTT Amt'] * 100 / df_tmp['Current'], 2)
cols = ['CurrAlloc%', 'Current P/L%', 'FTT%']
df_tmp[cols].sort_values(by=['CurrAlloc%'], ascending=False)

               CurrAlloc%  Current P/L%    FTT%
Category
FMCG                15.43        -25.67   70.85
IT                  11.12        -39.41  108.55
FINANCE             10.84        -15.82   65.71
AUTO                 8.31         -5.81   43.70
BANKS                6.11        -13.55   62.52
MISC                 5.98        -34.13   88.08
PHARMA               5.91          8.79   17.07
INSURANCE            5.73         -5.48   42.78
PAINTS               5.48        -16.97   36.92
ELECTRICAL           4.19         -9.55   43.85
AC                   1.81        -14.52   45.57
REFINERIES           1.74        -11.11   48.43
BREWERIES            1.70         10.58    7.99
FOOTWEAR             1.66        -71.81  140.70
APPARELS             1.62         -7.83   43.26
CABLES               1.56         38.52   27.82
DURABLES             1.46        -71.74  113.52
TRAVEL               1.43       -104.30  206.59
CERAMICS             1.34        -49.05   94.33
ENGINEERING          1.24        -26.77   84.75
CHEMICALS            1.20        -43.59  160.14
CEMENT               1.01        -73.28  202.91
JEWELLERY            0.96       -116.25  191.38
HEALTHCARE           0.70        -67.72  109.82
ENTERTAINMENT        0.70        -80.75  188.55
TEXTILES             0.39        -52.82   96.40
HOTELS               0.37       -100.75  171.55

In [29]:
# money to be made criteria-wise
df_portfolio_features.groupby('Criteria')['FTT Amt'].agg(['sum', 'count']).sort_values(by='sum', ascending=False)

                sum  count
Criteria
XY24      3633208.0     19
X40       2127726.0     18
XR        1401291.0     13
X40N      1204428.0     12
AR        1061249.0      8
OX40N      659804.0     10
XY25       591433.0      5
SR         281923.0      2

In [30]:
# money to be made conviction-wise
df_portfolio_features.groupby('Conviction')['FTT Amt'].agg(['sum', 'count']).sort_values(by='sum', ascending=False)

                  sum  count
Conviction
X-LC        2443866.0     19
X-MC        1482187.0     14
X-SC        1105295.0      6
H-SC         834038.0      8
M-SC         332858.0      6
H-MC         254160.0      1
M-LC         167635.0      1
M-MC          59158.0      1
H-LC          47156.0      2
L-MC          45062.0      1

In [31]:
# money to be made criteria and conviction-wise
df_portfolio_features.groupby(['Conviction', 'Criteria'])['FTT Amt'].agg(['sum', 'count']).sort_values(by='sum', ascending=False)

                           sum  count
Conviction Criteria
X-LC       X40       1250203.0      9
X-SC       XY24       676951.0      2
H-SC       XY24       530872.0      3
X-MC       X40        508786.0      6
           X40N       466048.0      4
X-LC       XY24       459750.0      2
           X40N       415428.0      5
X-MC       XY25       275875.0      2
X-LC       XY25       256400.0      2
H-MC       XY24       254160.0      1
X-SC       X40        253939.0      2
X-MC       XY24       231478.0      2
H-SC       OX40N      209449.0      3
X-SC       X40N       174405.0      2
M-LC       XR         167635.0      1
M-SC       OX40N      156655.0      4
           XY24       118009.0      1
H-SC       XR          93717.0      2
X-LC       XR          62085.0      1
M-MC       XY25        59158.0      1
M-SC       XR          58194.0      1
H-LC       AR          47156.0      2
L-MC       XR          45062.0      1

In [32]:
# notebook execution time

end_time = time.time()
execution_time = round(end_time - start_time, 0)
print(f"Notebook execution time: {execution_time} seconds")

Notebook execution time: 27.0 seconds