<a href="https://colab.research.google.com/github/ankit-rathi/Quantvesting_v2/blob/main/myStocks_Portfolio_Analysis.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
'''
!pip install pandas==2.2.2 -qq
!pip install pyxirr -qq
!pip install ta -qq
!pip install yfinance==0.2.59 -qq
'''

'\n!pip install pandas==2.2.2 -qq\n!pip install pyxirr -qq\n!pip install ta -qq\n!pip install yfinance==0.2.59 -qq\n'

In [2]:
# import libraries

import numpy as np
import pandas as pd
import datetime
import warnings
warnings.filterwarnings('ignore')
import yfinance as yfin
import ta
import matplotlib.pyplot as plt
import requests

In [3]:
# notebook start time
import time
import datetime
import pytz

start_time = time.time()

# function to print date timestamp
def print_date_time():
  tz_NY = pytz.timezone('Asia/Kolkata')
  datetime_NY = datetime.datetime.now(tz_NY)
  print("Run date time (IST):", datetime_NY.strftime("%Y-%m-%d %H:%M:%S"))

In [4]:
# function to get booked and reserved amount
def get_amt():
  # fetch the JSON data from the URL
  url = "https://raw.githubusercontent.com/ankit-rathi/Tradevesting_v1/main/data/myPortfolioAmts.json"
  response = requests.get(url)
  pf_amts = response.json()  # parse the JSON data

  # extract values from the JSON
  py_booked_amt_dm = pf_amts["py_booked_amt_dm"]
  py_booked_amt_sv = pf_amts["py_booked_amt_sv"]
  cy_booked_amt_dm = pf_amts["cy_booked_amt_dm"]
  cy_booked_amt_sv = pf_amts["cy_booked_amt_sv"]
  reserve_amt_dm = pf_amts["reserve_amt_dm"]
  reserve_amt_sv = pf_amts["reserve_amt_sv"]

  # perform calculations
  py_booked_amt = py_booked_amt_dm + py_booked_amt_sv
  cy_booked_amt = cy_booked_amt_dm + cy_booked_amt_sv
  reserve_amt = reserve_amt_dm + reserve_amt_sv
  total_booked_amt = py_booked_amt + cy_booked_amt

  return total_booked_amt, reserve_amt, cy_booked_amt, py_booked_amt

gen_output = 0

In [5]:
# function to format the amount
def format_amt(number):
    abs_number = abs(number)

    if abs_number >= 1_00_00_000:  # Crores
        formatted_amt = f"{number / 1_00_00_000:.2f} C"
    elif abs_number >= 1_00_000:  # Lakhs
        formatted_amt = f"{number / 1_00_000:.2f} L"
    elif abs_number >= 1_000:  # Thousands
        formatted_amt = f"{number / 1_000:.2f} K"
    else:
        formatted_amt = f"{number:.2f}"

    return formatted_amt

# function to set start and end date
def get_start_end_date():
  start_date = (datetime.date.today() + datetime.timedelta(days=-365)).strftime('%Y-%m-%d')
  end_date = (datetime.date.today() + datetime.timedelta(days=1)).strftime('%Y-%m-%d')
  return start_date, end_date

# function to fetch my portfolio csv
def get_mypfs_df():
  mypfs_df = pd.read_csv('https://raw.githubusercontent.com/ankit-rathi/Tradevesting_v1/main/data/myPortfolioStocks.csv')
  return mypfs_df

# function to fetch my prospects csv
def get_mypps_df():
  mypps_df = pd.read_csv('https://raw.githubusercontent.com/ankit-rathi/Tradevesting_v1/main/data/myProspectsScrips.csv')
  return mypps_df

# function to fetch screener data
def get_myscreen_df():
  myscreen_df = pd.read_csv('https://raw.githubusercontent.com/ankit-rathi/Tradevesting_v1/main/data/myScreenerDB.csv')
  return myscreen_df

# function to fetch momentum data
def get_myinvmt_df():
  myinvmt_df = pd.read_csv('https://raw.githubusercontent.com/ankit-rathi/Tradevesting_v1/main/data/myInvestments.csv')
  return myinvmt_df

# function to get the stock ids
def get_stock_ids(df_pf):
  stock_n100 = df_pf['Symbol'].unique()

  exclude = ['CADILAHC','MMTC', 'MASFIN']

  stock_ids = df_pf[~df_pf['Symbol'].isin(exclude) ]['Symbol'].unique()

  #mypf = mypf[mypf.Forecast.notnull()]
  #stock_ids = mypf['Symbol'].unique()

  #stock_ids.sort()
  return stock_ids

# get features from screener data
def get_screener_features():
  myscreen_df = get_myscreen_df()
  cols = ['Symbol', 'EPS', 'MedPE', 'ROCE%', 'ROE%', 'CapType']
  return myscreen_df[cols]

# get relative strength
def get_relative_strength(stock_list):

    # Dictionary to store stock tickers and their corresponding percentage price change
    stock_changes = {}

    # Loop through each stock and fetch its price data
    for stock in stock_list:
        try:
            # Download the stock data for the given date range
            stock_data = yfin.Ticker(stock + '.NS').history(period='1mo', interval='1d')[map(str.title, ['open', 'close', 'low', 'high', 'volume'])]

            # Calculate the percentage change for the stock
            if len(stock_data) > 0:
                start_price = stock_data['Close'].iloc[0]
                end_price = stock_data['Close'].iloc[-1]
                percent_change = round(((end_price - start_price) / start_price) * 100, 2)
                stock_changes[stock] = percent_change
            else:
                stock_changes[stock] = np.nan  # If no data is available, set to NaN

        except Exception as e:
            print(f"Error fetching data for {stock}: {e}")
            stock_changes[stock] = np.nan

    # Create a DataFrame with stock tickers and their percentage changes
    df = pd.DataFrame(list(stock_changes.items()), columns=['Symbol', 'Percent_Change'])

    # Drop any stocks with missing data (NaN values)
    df = df.dropna()

    # Calculate the percentile rank based on percentage change
    df['RSP'] = round(df['Percent_Change'].rank(pct=True) * 100, 2)
    cols = ['Symbol', 'RSP']
    df = df[cols]
    # Sort by percentile rank (optional)
    df = df.sort_values(by='RSP', ascending=False).reset_index(drop=True)

    return df

In [6]:
# function to get stock technicals
def stock_prec_dev(stock_symbol):
    #stock_symbol = 'ULTRACEMCO.NS'
    short_window = 20
    mid_window = 50
    long_window = 200
    moving_avg = 'SMA'

    start = datetime.datetime(*map(int, start_date.split('-')))
    end = datetime.datetime(*map(int, end_date.split('-')))

    stock_df = yfin.Ticker(stock_symbol + '.NS').history(period='max', interval='1d')[map(str.title, ['open', 'close', 'low', 'high', 'volume'])]

    stock_df['Max'] = round(max(stock_df['Close']),2)
    stock_df = stock_df[(stock_df.index <= end_date) & (stock_df.index >= start_date)]
    stock_df['200_SMA'] = round(stock_df['Close'].rolling(window = 200, min_periods = 1).mean(),0)
    stock_df['Dev%_200'] = round((stock_df['Close'] - stock_df['200_SMA'])*100/stock_df['200_SMA'],2)
    stock_df.dropna(axis = 0, inplace = True) # remove any null rows

    stock_df['20_SMA'] = stock_df['Close'].rolling(window=20).mean()
    stock_df['50_SMA'] = stock_df['Close'].rolling(window=50).mean()
    stock_df['Symbol'] = stock_symbol

    stock_df['Close'] = round(stock_df['Close'],2)
    stock_df['Min'] = round(min(stock_df['Close']),2)
    stock_df['RSI_14'] = ta.momentum.RSIIndicator(close=stock_df['Close'], window=14).rsi()
    stock_df['RSI_14'] = round(stock_df['RSI_14'],0)
    stock_df['Prev_Close'] = stock_df['Close'].shift(1)
    stock_df.drop(['Open', 'Low', 'High', 'Volume'], axis=1, inplace=True)
    stock_df = stock_df.tail(1)

    max_SMA = max(stock_df['20_SMA'].item(), stock_df['50_SMA'].item(), stock_df['200_SMA'].item())
    min_SMA = min(stock_df['20_SMA'].item(), stock_df['50_SMA'].item(), stock_df['200_SMA'].item())
    ABS_Spread = max_SMA - min_SMA
    stock_df['Spread%'] = round((ABS_Spread / stock_df['200_SMA'].item()) * 100,2)

    return stock_df

# function to compute stock attributes
def get_common_features(stock_ids, df_mypf):

  df_prec_dev = pd.DataFrame()
  df_tmp = get_screener_features()
  df_rs = get_relative_strength(stock_ids)

  for stock_id in stock_ids:
      tmp = stock_prec_dev(stock_id)
      tmp = tmp.reset_index()
      df_prec_dev = pd.concat([df_prec_dev, tmp], ignore_index = True)
  df_prec_dev = pd.merge(df_prec_dev, df_mypf, on= 'Symbol')
  df_prec_dev = pd.merge(df_prec_dev, df_tmp, on= 'Symbol', how='left')
  df_prec_dev = pd.merge(df_prec_dev, df_rs, on= 'Symbol', how='left')
  #print(df_prec_dev.columns)
  df_prec_dev['Curr_PE'] = round(df_prec_dev['Close']/df_prec_dev['EPS'],1)
  df_prec_dev['Dev%_PE'] = round((df_prec_dev['Curr_PE'] - df_prec_dev['MedPE'])*100/df_prec_dev['MedPE'],2)
  df_prec_dev['Conviction'] = df_prec_dev['Conviction'] + '-' + df_prec_dev['CapType']
  return df_prec_dev

# function to arrange stock features
def arrange_features(df_stocks, common_cols, diff_cols):
  df_stocks_common = df_stocks[common_cols].drop_duplicates()
  df_stocks_diff = df_stocks[diff_cols]
  df_stocks_diff['Investment'] = df_stocks_diff['AvgCost'] * df_stocks_diff['Shares']
  df_stocks_diff = df_stocks_diff.groupby(['Symbol'])[['Shares', 'Investment']].aggregate(['sum']).reset_index()
  df_stocks_diff.columns = ['Symbol', 'Shares', 'Investment']
  df_stocks_diff['AvgCost'] = round(df_stocks_diff['Investment']/df_stocks_diff['Shares'],2)
  df_stocks = pd.merge(df_stocks_diff, df_stocks_common, on='Symbol')
  return df_stocks

# plot fact distribution across dimension
def plot_pie_chart(df, dimension, fact):
  # grouping the data by category and calculating the sum of fact for each type
  grouped_data = df.groupby(dimension)[fact].sum()

  # sorting the grouped data in descending order
  grouped_data = grouped_data.sort_values(ascending=False)

  # creating a pie chart
  grouped_data.plot.pie(autopct='%1.1f%%', startangle=90, figsize=(6, 6))

  # adding a title and displaying the plot
  plt.title(f'{dimension} {fact} Distribution')
  plt.ylabel('')  # To hide the y-label
  plt.show()

In [7]:
# function to get portfolio features

def get_portfolio_features(df_common_features):

  print_date_time()
  print('-------------------')

  #df_common_features["Target"] = df_common_features["Target"].fillna(df_common_features["Max"])
  df_common_features['NTT'] = np.where(df_common_features['Strategy']== 'NTT', df_common_features["Target"], df_common_features['Max'])
  df_common_features['LTT'] = np.where(df_common_features['Strategy']== 'BTT', df_common_features["Target"], df_common_features['Max'])
  df_common_features['BOL'] = df_common_features['Min']

  tmp_df = df_common_features[df_common_features['Symbol'].isin(mypf_df[mypf_df['InPortfolio'] != 'NA'].Symbol.values)]
  print('qualified stocks: '+str(len(tmp_df['Symbol'].unique())))
  tmp_df1 = tmp_df[tmp_df['LatestQtr'] == 1]
  print('with latest results: '+str(len(tmp_df1['Symbol'].unique())))
  tmp_df1 = tmp_df1[tmp_df1['StarStock'] == 1]
  print('still star stocks: '+str(len(tmp_df1['Symbol'].unique())))
  tmp_df['Investment'] = tmp_df['AvgCost'] * tmp_df['Shares']
  tmp_df['Current'] = round(tmp_df['Close'] * tmp_df['Shares'],0)
  tmp_df['Previous'] = tmp_df['Prev_Close'] * tmp_df['Shares']
  tmp_df['EstimatedST'] = tmp_df['NTT'] * tmp_df['Shares']
  tmp_df['EstimatedLT'] = tmp_df['LTT'] * tmp_df['Shares']
  tmp_df['Current P/L'] = round((tmp_df['Current'] - tmp_df['Investment']),0)
  tmp_df['Today P/L%'] = round((tmp_df['Current'] - tmp_df['Previous'])*100/tmp_df['Previous'],2)
  tmp_df['Current P/L%'] = round((tmp_df['Current'] - tmp_df['Investment'])*100/tmp_df['Investment'],2)
  tmp_df['EstimatedST P/L%'] = round((tmp_df['EstimatedST'] - tmp_df['Investment'])*100/tmp_df['Investment'],2)
  tmp_df['EstimatedLT P/L%'] = round((tmp_df['EstimatedLT'] - tmp_df['Investment'])*100/tmp_df['Investment'],2)
  tmp_df['NTT%'] = round((tmp_df['NTT'] - tmp_df['Close'])*100/tmp_df['Close'],2)
  tmp_df['LTT%'] = round((tmp_df['LTT'] - tmp_df['Close'])*100/tmp_df['Close'],2)
  tmp_df['Gained%'] = round((tmp_df['Close'] - tmp_df['BOL'])*100/tmp_df['BOL'],2)
  investment = round(sum(tmp_df['AvgCost']*tmp_df['Shares']),0)
  current = round(sum(tmp_df['Close']*tmp_df['Shares']),0)
  tmp_df['InitAlloc%'] = round(tmp_df['Investment']*100/investment,2)
  tmp_df['CurrAlloc%'] = round(tmp_df['Current']*100/current,2)
  tmp_df['FTT'] = tmp_df['LTT']
  tmp_df.loc[tmp_df['Strategy'] == 'NTT', 'FTT'] = tmp_df['NTT']
  tmp_df['FTT%'] = tmp_df['LTT%']
  tmp_df.loc[tmp_df['Strategy'] == 'NTT', 'FTT%'] = tmp_df['NTT%']
  tmp_df['FTT Amt'] = round(tmp_df['FTT%'] * tmp_df['Current']/100,0)
  tmp_df['OTT%'] = round((tmp_df['FTT'] - tmp_df['AvgCost'])*100/tmp_df['AvgCost'],2)
  tmp_df['RRR Ind'] = round(tmp_df['Current P/L']/tmp_df['FTT Amt'],2)
  tmp_df['Risk Ind'] = round(tmp_df['Current P/L%']*tmp_df['CurrAlloc%'],0)

  return tmp_df

# function to print portfolio features
def print_portfolio_stats(df_portfolio_features, myinvmt_df):
  from pyxirr import xirr

  total_booked_amt, reserve_amt, cy_booked_amt, py_booked_amt = get_amt()

  dates = myinvmt_df['Date'].values
  dates = np.append(dates, datetime.date.today().strftime('%d-%b-%y'))
  investment = myinvmt_df['Investment'].values
  dates= pd.to_datetime(dates)

  current = round(sum(df_portfolio_features['Close']*df_portfolio_features['Shares']),0) + reserve_amt
  investment_xirr = np.append(investment, current)
  cagr = round(xirr(pd.DataFrame({"dates": dates, "amounts": investment_xirr}))*100,2)

  investment = -sum(investment)
  invested = round(sum(df_portfolio_features['AvgCost']*df_portfolio_features['Shares']),0) + reserve_amt
  previous = round(sum(df_portfolio_features['Prev_Close']*df_portfolio_features['Shares']),0) + reserve_amt
  cy_invested = investment + py_booked_amt

  today_pnl_amount = current-previous
  today_pnl_percentage = round((current-previous)*100/previous,2)

  curr_pnl_amount = current-invested
  curr_pnl_percentage = round((curr_pnl_amount)*100/(cy_invested),2)

  cy_pnl_amount = cy_booked_amt + curr_pnl_amount
  cy_pnl_percentage = round((cy_pnl_amount)*100/cy_invested,2)

  overall_pnl_amount = total_booked_amt + curr_pnl_amount
  overall_pnl_percentage = round((overall_pnl_amount)*100/investment,2)

  estimate_st = round(sum(df_portfolio_features['FTT']*df_portfolio_features['Shares']),0)  + reserve_amt
  est_st_pnl_amount = estimate_st-current
  est_st_pnl_percentage = round((est_st_pnl_amount)*100/current,2)

  estimate_lt = round(sum(df_portfolio_features['LTT']*df_portfolio_features['Shares']),0)  + reserve_amt
  est_lt_pnl_amount = estimate_lt-current
  est_lt_pnl_percentage = round((est_lt_pnl_amount)*100/current,2)

  total_profit = round(sum(df_portfolio_features[df_portfolio_features['Current P/L%'] > 0]['Current']) - sum(df_portfolio_features[df_portfolio_features['Current P/L%'] > 0]['Investment']),0)
  total_loss = round(sum(df_portfolio_features[df_portfolio_features['Current P/L%'] < 0]['Current']) - sum(df_portfolio_features[df_portfolio_features['Current P/L%'] < 0]['Investment']),0)

  cy_booked_percentage = round((cy_booked_amt)*100/current,2)
  py_booked_percentage = round((py_booked_amt)*100/investment,2)
  total_booked_percentage = round((total_booked_amt)*100/investment,2)

  print('-------------------')
  print('Initial Investment: ', format_amt(investment))
  print('CY Investment: ', format_amt(cy_invested))
  print('Reserve: ', format_amt(reserve_amt))
  print('Current: ',  format_amt(current))
  print('-------------------')
  print('Today PnL: '+ '{} ({}%)'.format(format_amt(today_pnl_amount), today_pnl_percentage))
  print('Current PnL: '+ '{} ({}%)'.format(format_amt(curr_pnl_amount), curr_pnl_percentage))
  print('CY Booked + Current PnL: '+ '{} ({}%)'.format(format_amt(cy_pnl_amount), cy_pnl_percentage))
  print('-------------------')
  print('Total profit: ', format_amt(total_profit))
  print('Total loss: ', format_amt(total_loss))
  print('-------------------')
  print('Total Booked + Current PnL: '+ '{} ({}%)'.format(format_amt(overall_pnl_amount), overall_pnl_percentage))
  print('Total Booked PnL: '+ '{} ({}%)'.format(format_amt(total_booked_amt), total_booked_percentage))
  print('Curr Year Booked PnL: '+ '{} ({}%)'.format(format_amt(cy_booked_amt), cy_booked_percentage))
  print('Prev Year Booked PnL: '+ '{} ({}%)'.format(format_amt(py_booked_amt), py_booked_percentage))
  print('===================')
  print('Est FTT: ',  format_amt(estimate_st))
  print('Est FTT PnL: '+ '{} ({}%)'.format(format_amt(est_st_pnl_amount), est_st_pnl_percentage))

  print('===================')
  print('Deployed: ', format_amt(investment))

  print('Current: ', format_amt(current))

  print('CAGR/XIRR %: '+'{}%'.format(cagr))

In [8]:
# get start and end date
start_date, end_date = get_start_end_date()

# get portfolio and prospects data
mypfs_df = get_mypfs_df()
mypps_df = get_mypps_df()
myinvmt_df = get_myinvmt_df()

# merge above datasets
mypf_df = pd.merge(mypfs_df, mypps_df, on="Symbol")

# seggregate dm and sv portfolio
dm_pf = mypf_df[mypf_df['InPortfolio'] == 'DM']
sv_pf = mypf_df[mypf_df['InPortfolio'] == 'SV']

# build portfolio stock dataframe
dm_stocks = get_stock_ids(dm_pf)
sv_stocks = get_stock_ids(sv_pf)
df_stocks = pd.concat([dm_pf,sv_pf], ignore_index = True)

# arrange common and diff stock features
common_cols = ['Symbol', 'Target', 'Criteria', 'Strategy', 'CumlRnk', 'LatestQtr', 'StarStock', 'Conviction', 'Category', 'InFolio', 'XIRR', 'MBQ']
diff_cols = ['Symbol', 'AvgCost', 'Shares']
df_stocks = arrange_features(df_stocks, common_cols, diff_cols)

# get common features
stock_ids = df_stocks['Symbol'].values
df_common_features = get_common_features(stock_ids, df_stocks)

df_common_features.reset_index(drop=True, inplace=True)
df_common_features.drop(['Date'], axis=1, inplace=True)
# get and print portfolio features
df_portfolio_features = get_portfolio_features(df_common_features)

print_portfolio_stats(df_portfolio_features, myinvmt_df)

df = df_portfolio_features
#plot_pie_chart(df, 'CapType', 'Current')
list_ox40n = list(df[df['MBQ'].str.contains('OX40N', na=False)]['Symbol'].values)

Run date time (IST): 2026-03-04 13:23:23
-------------------
qualified stocks: 86
with latest results: 26
still star stocks: 15
-------------------
Initial Investment:  1.33 C
CY Investment:  1.60 C
Reserve:  2.44 L
Current:  1.34 C
-------------------
Today PnL: -2.75 L (-2.01%)
Current PnL: -40.32 L (-25.2%)
CY Booked + Current PnL: -24.64 L (-15.4%)
-------------------
Total profit:  82.00 K
Total loss:  -41.14 L
-------------------
Total Booked + Current PnL: 2.34 L (1.76%)
Total Booked PnL: 42.66 L (32.07%)
Curr Year Booked PnL: 15.68 L (11.69%)
Prev Year Booked PnL: 26.98 L (20.29%)
===================
Est FTT:  2.41 C
Est FTT PnL: 1.07 C (79.74%)
===================
Deployed:  1.33 C
Current:  1.34 C
CAGR/XIRR %: 0.42%

In [9]:
# top 5 near their targets
cols = ['Symbol', 'Today P/L%', 'Current P/L%', 'FTT%', 'OTT%', 'FTT Amt', 'Current P/L', 'Current', 'FTT', 'Dev%_PE', 'RSI_14','Conviction', 'Spread%',  'CumlRnk', 'RRR Ind', 'CurrAlloc%', 'Gained%', 'Criteria', 'Strategy', 'Category']
df_tmp = df_portfolio_features[~df_portfolio_features['Symbol'].isin(['ENRIN','BLUSPRING','DIGITIDE'])]
df_tmp = df_tmp.sort_values(by = 'FTT Amt', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
19,COALINDIA,2.29,7.22,9.75,17.67,15729.0,10860.0,161320.0,478.51,29.12,58.0,L-LC,11.02,185.0,0.69,1.23,28.25,XY25,ATH,MINING
50,MASFIN,-3.00,-6.34,29.79,21.57,27338.0,-6210.0,91770.0,397.04,-19.15,37.0,H-SC,6.51,167.0,-0.23,0.70,32.90,XR,ATH,FINANCE
77,TTKPRESTIG,-2.81,-36.69,58.09,0.09,37064.0,-36973.0,63804.0,770.00,48.13,22.0,M-SC,12.50,250.0,-1.00,0.48,0.00,OX40N,NTT,DURABLES
51,MEDANTA,-1.76,-7.31,33.86,24.08,39843.0,-9279.0,117671.0,1486.00,-7.89,44.0,X-SC,8.03,87.0,-0.23,0.89,7.78,XY24,NTT,HEALTHCARE
37,ICICIGI,-2.19,-1.79,21.52,19.34,42292.0,-3585.0,196524.0,2252.93,-17.38,41.0,X-MC,1.30,66.0,-0.08,1.49,13.86,X40,ATH,INSURANCE

In [10]:
# top 5 today
df_tmp = df_portfolio_features.sort_values(by = 'Today P/L%', ascending=False)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
69,SURYODAY,2.45,-26.98,68.49,23.03,89560.0,-48307.0,130764.0,216.00,42.54,49.0,H-SC,6.07,166.0,-0.54,0.99,29.74,XR,NTT,BANKS
19,COALINDIA,2.29,7.22,9.75,17.67,15729.0,10860.0,161320.0,478.51,29.12,58.0,L-LC,11.02,185.0,0.69,1.23,28.25,XY25,ATH,MINING
43,INFY,1.10,-11.29,51.33,34.24,142472.0,-35328.0,277560.0,1972.00,-30.33,27.0,X-LC,10.10,3.0,-0.25,2.11,2.16,X40,NTT,IT
2,ABBOTINDIA,0.90,-9.27,30.13,18.07,48892.0,-16585.0,162270.0,35195.00,-22.81,52.0,X-MC,11.43,58.0,-0.34,1.23,2.87,X40,ATH,PHARMA
8,AWL,0.45,-41.30,167.79,57.19,321205.0,-134694.0,191433.0,485.00,-66.49,16.0,X-SC,19.83,81.0,-0.42,1.45,0.45,XY24,NTT,FMCG

In [11]:
# bottom 5 today
df_tmp = df_portfolio_features.sort_values(by = 'Today P/L%', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
75,TMPV,-5.09,-21.83,70.58,33.33,179744.0,-71133.0,254667.0,600.00,-83.62,37.0,X-LC,3.57,4.0,-0.40,1.93,4.11,XY24,NTT,AUTO
27,FINCABLES,-5.07,13.79,82.71,107.91,138961.0,20366.0,168010.0,1641.55,2.49,65.0,M-SC,6.40,220.0,0.15,1.28,26.40,OX40N,ATH,CABLES
55,RAJESHEXPO,-5.00,-74.56,293.35,0.07,102373.0,-102279.0,34898.0,518.00,1179.04,24.0,L-SC,11.12,268.0,-1.00,0.27,0.00,OX40N,NTT,JEWELLERY
7,ATULAUTO,-4.96,-21.73,85.99,45.57,132676.0,-42840.0,154292.0,844.00,3337.84,45.0,M-SC,7.20,248.0,-0.32,1.17,16.76,XY24,NTT,AUTO
12,BATAINDIA,-4.70,-52.69,185.81,35.20,113099.0,-67802.0,60868.0,2096.00,-20.14,19.0,X-SC,23.02,91.0,-0.60,0.46,0.00,X40,NTT,FOOTWEAR

In [12]:
# top 5 to exit based on CumlRnk
df_tmp = df_portfolio_features[~df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])]
df_tmp = df_tmp[(df_tmp['Current P/L%'] > -1) & (df_tmp['Current P/L%'] < 1)].sort_values(by = 'CumlRnk', ascending=False)
df_tmp[cols].head()

Empty DataFrame
Columns: [Symbol, Today P/L%, Current P/L%, FTT%, OTT%, FTT Amt, Current P/L, Current, FTT, Dev%_PE, RSI_14, Conviction, Spread%, CumlRnk, RRR Ind, CurrAlloc%, Gained%, Criteria, Strategy, Category]
Index: []

In [13]:
# OX40N stocks to exit
df_tmp = df_portfolio_features[(df_portfolio_features['Symbol'].isin(list_ox40n))].sort_values(by = 'Current P/L%', ascending=False)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
27,FINCABLES,-5.07,13.79,82.71,107.91,138961.0,20366.0,168010.0,1641.55,2.49,65.0,M-SC,6.40,220.0,0.15,1.28,26.40,OX40N,ATH,CABLES
66,SIS,-2.77,-31.95,78.20,21.26,59085.0,-35476.0,75556.0,528.00,1772.02,36.0,H-SC,6.50,168.0,-0.60,0.57,4.16,OX40N,NTT,MISC
48,KANSAINER,-0.35,-34.71,73.80,13.47,129937.0,-93600.0,176067.0,340.00,-43.94,31.0,H-SC,14.11,162.0,-0.72,1.34,0.00,XY24,NTT,PAINTS
41,INDIGOPNTS,-0.90,-35.36,54.73,0.02,61757.0,-61719.0,112840.0,1408.00,71.88,22.0,M-SC,13.16,222.0,-1.00,0.86,0.00,OX40N,NTT,PAINTS
77,TTKPRESTIG,-2.81,-36.69,58.09,0.09,37064.0,-36973.0,63804.0,770.00,48.13,22.0,M-SC,12.50,250.0,-1.00,0.48,0.00,OX40N,NTT,DURABLES

In [14]:
# top 5 to book for rotation
df_tmp = df_portfolio_features[(df_portfolio_features['Current P/L%'] > 20) ].sort_values(by = 'CumlRnk', ascending=False)
df_tmp[cols].head()

Empty DataFrame
Columns: [Symbol, Today P/L%, Current P/L%, FTT%, OTT%, FTT Amt, Current P/L, Current, FTT, Dev%_PE, RSI_14, Conviction, Spread%, CumlRnk, RRR Ind, CurrAlloc%, Gained%, Criteria, Strategy, Category]
Index: []

In [15]:
# top 5 to monitor for exit
df_tmp = df_portfolio_features[~df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])]
df_tmp = df_tmp[(df_tmp['Current P/L%'] > 0) ].sort_values(by = 'Dev%_PE', ascending=False)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
19,COALINDIA,2.29,7.22,9.75,17.67,15729.0,10860.0,161320.0,478.51,29.12,58.0,L-LC,11.02,185.0,0.69,1.23,28.25,XY25,ATH,MINING
27,FINCABLES,-5.07,13.79,82.71,107.91,138961.0,20366.0,168010.0,1641.55,2.49,65.0,M-SC,6.40,220.0,0.15,1.28,26.40,OX40N,ATH,CABLES
1,ABB,-2.85,6.64,36.50,45.57,101835.0,17381.0,279000.0,7934.00,-31.49,53.0,H-MC,8.85,125.0,0.17,2.12,23.89,AR,NTT,ELECTRICAL

In [16]:
# top 5 to book for rotation from weak conviction
df_tmp = df_portfolio_features[~df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])]
df_tmp = df_tmp[~df_tmp['Criteria'].isin(['XY25','XY24','X40', 'X40N'])].sort_values(by = 'RRR Ind', ascending=False)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
1,ABB,-2.85,6.64,36.50,45.57,101835.0,17381.0,279000.0,7934.00,-31.49,53.0,H-MC,8.85,125.0,0.17,2.12,23.89,AR,NTT,ELECTRICAL
27,FINCABLES,-5.07,13.79,82.71,107.91,138961.0,20366.0,168010.0,1641.55,2.49,65.0,M-SC,6.40,220.0,0.15,1.28,26.40,OX40N,ATH,CABLES
40,INDIAMART,-2.03,-11.01,132.30,106.72,145210.0,-13578.0,109758.0,4810.62,-59.77,32.0,H-SC,8.24,140.0,-0.09,0.83,9.80,AR,ATH,MISC
85,ZYDUSLIFE,-1.64,-5.94,44.19,35.63,87113.0,-12442.0,197132.0,1286.17,-18.02,45.0,H-MC,4.96,120.0,-0.14,1.50,9.75,AR,ATH,PHARMA
84,WIPRO,-1.55,-19.81,114.83,72.27,156022.0,-33576.0,135872.0,420.00,-27.84,20.0,M-LC,11.40,98.0,-0.22,1.03,0.00,XR,NTT,IT

In [17]:
# top 5 to accumulate based on lowest RSI_14
df_tmp = df_portfolio_features[df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])].sort_values(by = 'RSI_14', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
8,AWL,0.45,-41.30,167.79,57.19,321205.0,-134694.0,191433.0,485.00,-66.49,16.0,X-SC,19.83,81.0,-0.42,1.45,0.45,XY24,NTT,FMCG
12,BATAINDIA,-4.70,-52.69,185.81,35.20,113099.0,-67802.0,60868.0,2096.00,-20.14,19.0,X-SC,23.02,91.0,-0.60,0.46,0.00,X40,NTT,FOOTWEAR
53,PGHH,-0.83,-16.62,58.33,32.01,103846.0,-35488.0,178032.0,17616.87,-43.64,21.0,X-MC,9.82,57.0,-0.34,1.35,0.00,X40,ATH,FMCG
9,BAJAJHFL,-1.90,-28.34,116.95,55.47,203899.0,-68939.0,174347.0,181.50,-38.44,22.0,X-MC,17.75,60.0,-0.34,1.32,0.00,X40N,ATH,FINANCE
3,ACC,-2.00,-36.03,156.62,64.15,238391.0,-85741.0,152210.0,3906.00,-51.63,23.0,X-SC,9.94,85.0,-0.36,1.16,0.00,XY24,BTT,CEMENT

In [18]:
# top 5 to accumulate based on Spread and CumlRnk
df_tmp = df_portfolio_features[df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])]
df_tmp = df_tmp[(df_tmp['CumlRnk'] < 100)].sort_values(by = 'Spread%', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
37,ICICIGI,-2.19,-1.79,21.52,19.34,42292.0,-3585.0,196524.0,2252.93,-17.38,41.0,X-MC,1.30,66.0,-0.08,1.49,13.86,X40,ATH,INSURANCE
78,UNITDSPR,-3.19,-2.81,24.26,20.77,55205.0,-6588.0,227556.0,1644.00,-13.87,36.0,X-MC,1.36,64.0,-0.12,1.73,4.09,X40N,NTT,BREWERIES
22,DABUR,-3.47,-4.20,50.00,43.70,118825.0,-10418.0,237650.0,735.00,-13.00,36.0,X-MC,1.45,70.0,-0.09,1.80,10.22,XY24,BTT,FMCG
59,RELIANCE,-1.34,-14.00,45.69,25.30,78968.0,-28129.0,172834.0,1952.00,-16.19,31.0,X-LC,2.19,21.0,-0.36,1.31,15.77,XY25,BTT,REFINERIES
35,HINDUNILVR,-1.70,-11.26,28.10,13.67,64099.0,-28953.0,228110.0,2922.00,-34.20,40.0,X-LC,2.51,9.0,-0.45,1.73,7.69,XY25,NTT,FMCG

In [19]:
# top 5 to accumulate based on lowest Gained%
df_tmp = df_portfolio_features[df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])].sort_values(by = 'Gained%', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
3,ACC,-2.00,-36.03,156.62,64.15,238391.0,-85741.0,152210.0,3906.00,-51.63,23.0,X-SC,9.94,85.0,-0.36,1.16,0.0,XY24,BTT,CEMENT
9,BAJAJHFL,-1.90,-28.34,116.95,55.47,203899.0,-68939.0,174347.0,181.50,-38.44,22.0,X-MC,17.75,60.0,-0.34,1.32,0.0,X40N,ATH,FINANCE
12,BATAINDIA,-4.70,-52.69,185.81,35.20,113099.0,-67802.0,60868.0,2096.00,-20.14,19.0,X-SC,23.02,91.0,-0.60,0.46,0.0,X40,NTT,FOOTWEAR
13,BERGEPAINT,-2.09,-21.96,55.23,21.14,97984.0,-49929.0,177410.0,680.00,-23.60,26.0,X-MC,14.36,68.0,-0.51,1.35,0.0,XY24,NTT,PAINTS
24,DIXON,-1.55,-30.71,89.43,31.26,143002.0,-70864.0,159904.0,18931.72,-69.03,34.0,X-MC,24.19,54.0,-0.50,1.21,0.0,X40N,ATH,IT

In [20]:
# top 5 to accumulate based on lowest CurrAlloc%
df_tmp = df_portfolio_features[df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])].sort_values(by = 'CurrAlloc%', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
54,QUESS,-1.20,-36.16,123.75,42.84,51356.0,-23506.0,41500.0,424.00,-58.13,33.0,X-SC,16.96,80.0,-0.46,0.32,0.00,XY24,NTT,MISC
12,BATAINDIA,-4.70,-52.69,185.81,35.20,113099.0,-67802.0,60868.0,2096.00,-20.14,19.0,X-SC,23.02,91.0,-0.60,0.46,0.00,X40,NTT,FOOTWEAR
58,RELAXO,-1.53,-57.91,261.85,52.31,159990.0,-84060.0,61100.0,1176.00,-55.18,25.0,X-SC,15.89,92.0,-0.53,0.46,0.00,X40N,NTT,FOOTWEAR
51,MEDANTA,-1.76,-7.31,33.86,24.08,39843.0,-9279.0,117671.0,1486.00,-7.89,44.0,X-SC,8.03,87.0,-0.23,0.89,7.78,XY24,NTT,HEALTHCARE
36,HONAUT,-1.24,-26.46,94.88,43.32,113647.0,-43092.0,119780.0,58357.33,-35.45,31.0,X-SC,12.56,90.0,-0.38,0.91,0.00,X40N,ATH,ELECTRICAL

In [21]:
# top 5 to accumulate based on CumlRnk
df_tmp = df_portfolio_features.sort_values(by = 'CumlRnk', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
45,ITC,-0.81,-17.73,44.71,19.06,125128.0,-60300.0,279866.0,452.00,-54.71,38.0,X-LC,16.88,1.0,-0.48,2.13,1.33,X40,NTT,FMCG
73,TCS,-0.82,-25.71,66.34,23.58,213230.0,-111209.0,321420.0,4311.59,-35.43,28.0,X-LC,10.80,2.0,-0.52,2.44,0.71,X40,ATH,IT
43,INFY,1.10,-11.29,51.33,34.24,142472.0,-35328.0,277560.0,1972.00,-30.33,27.0,X-LC,10.10,3.0,-0.25,2.11,2.16,X40,NTT,IT
75,TMPV,-5.09,-21.83,70.58,33.33,179744.0,-71133.0,254667.0,600.00,-83.62,37.0,X-LC,3.57,4.0,-0.40,1.93,4.11,XY24,NTT,AUTO
34,HCLTECH,0.01,-11.01,39.16,23.83,84303.0,-26646.0,215278.0,1908.19,-6.53,28.0,X-LC,7.41,8.0,-0.32,1.63,3.29,X40,ATH,IT

In [22]:
# top 5 for average up
df_tmp = df_portfolio_features[(df_portfolio_features['Dev%_200'] > 5)].sort_values(by = 'CurrAlloc%', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
42,INDUSINDBK,-1.72,-31.61,94.32,32.89,49800.0,-24408.0,52799.0,1800.00,-348.60,50.0,L-MC,12.17,258.0,-0.49,0.40,45.40,XR,NTT,BANKS
67,SONACOMS,-3.12,-13.31,60.45,39.09,53010.0,-13467.0,87692.0,804.02,-31.27,42.0,M-MC,10.94,193.0,-0.25,0.67,24.06,AR,ATH,AUTO
19,COALINDIA,2.29,7.22,9.75,17.67,15729.0,10860.0,161320.0,478.51,29.12,58.0,L-LC,11.02,185.0,0.69,1.23,28.25,XY25,ATH,MINING
27,FINCABLES,-5.07,13.79,82.71,107.91,138961.0,20366.0,168010.0,1641.55,2.49,65.0,M-SC,6.40,220.0,0.15,1.28,26.40,OX40N,ATH,CABLES
82,VOLTAS,-3.31,13.39,28.04,45.20,60966.0,25683.0,217425.0,1856.00,29.81,45.0,X-MC,9.85,79.0,0.42,1.65,21.10,XY25,NTT,AC

In [23]:
# top 5 RSP
df_tmp = df_portfolio_features.sort_values(by = 'RSP', ascending=False)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
27,FINCABLES,-5.07,13.79,82.71,107.91,138961.0,20366.0,168010.0,1641.55,2.49,65.0,M-SC,6.40,220.0,0.15,1.28,26.40,OX40N,ATH,CABLES
26,EASEMYTRIP,-3.13,-57.28,241.09,45.70,182088.0,-101288.0,75527.0,26.40,-21.71,48.0,M-SC,18.06,204.0,-0.56,0.57,24.44,XY24,NTT,TRAVEL
83,WHIRLPOOL,-1.47,-27.80,151.97,81.92,125957.0,-31915.0,82883.0,2270.00,-57.77,53.0,M-SC,25.85,210.0,-0.25,0.63,16.43,XR,NTT,DURABLES
11,BANDHANBNK,-0.66,-15.10,126.64,92.42,299500.0,-42062.0,236497.0,400.00,102.59,62.0,H-SC,8.92,174.0,-0.14,1.80,30.28,XY24,NTT,BANKS
7,ATULAUTO,-4.96,-21.73,85.99,45.57,132676.0,-42840.0,154292.0,844.00,3337.84,45.0,M-SC,7.20,248.0,-0.32,1.17,16.76,XY24,NTT,AUTO

In [24]:
# Top N allocation
df_tmp = df_portfolio_features.sort_values(by = 'CurrAlloc%', ascending=False)
top_n_values = [10, 25, 50]

sum_df = pd.DataFrame({
    'Top_N': top_n_values,
    'Sum_Alloc%': [df_tmp['CurrAlloc%'].head(n).sum() for n in top_n_values]
})

sum_df

   Top_N  Sum_Alloc%
0     10       20.69
1     25       45.58
2     50       77.56

In [25]:
# market-cap-wise allocation
df_tmp = df_portfolio_features[cols]
df_tmp.groupby(df_tmp['Conviction'].str[-2:])['CurrAlloc%'].sum().sort_values(ascending=False)

Conviction
SC    44.76
MC    30.21
LC    25.00
Name: CurrAlloc%, dtype: float64

In [26]:
# criteria-wise allocation
df_portfolio_features.groupby('Criteria')['CurrAlloc%'].sum().sort_values(ascending=False)

Criteria
XY24     26.75
X40      24.13
X40N     14.48
AR        9.11
XY25      8.96
XR        8.52
OX40N     7.20
SR        0.82
Name: CurrAlloc%, dtype: float64

In [27]:
# conviction-wise allocation
df_portfolio_features.groupby('Conviction')['CurrAlloc%'].sum().sort_values(ascending=False)

Conviction
X-MC    22.79
H-SC    22.26
X-LC    21.53
X-SC    11.13
M-SC    10.69
H-MC     4.98
M-MC     2.04
L-LC     1.23
H-LC     1.21
M-LC     1.03
L-SC     0.68
L-MC     0.40
Name: CurrAlloc%, dtype: float64

In [28]:
# sector-wise stats
df_tmp = df_portfolio_features.groupby('Category')[['CurrAlloc%', 'Current', 'Current P/L', 'FTT Amt']].sum().sort_values(by=['Current', 'Current P/L'], ascending=False)
df_tmp['Current P/L%'] = round(df_tmp['Current P/L'] * 100 / df_tmp['Current'], 2)
df_tmp['FTT%'] = round(df_tmp['FTT Amt'] * 100 / df_tmp['Current'], 2)
cols = ['CurrAlloc%', 'Current P/L%', 'FTT%']
df_tmp[cols].sort_values(by=['CurrAlloc%'], ascending=False)

               CurrAlloc%  Current P/L%    FTT%
Category
FMCG                15.73        -19.05   59.32
FINANCE             12.83        -23.71   72.39
IT                  11.58        -43.62  115.59
MISC                 6.74        -46.20  106.01
ELECTRICAL           6.35        -12.27   53.24
PAINTS               5.07        -38.56   59.15
INSURANCE            4.91         -4.70   40.54
PHARMA               4.24         -5.16   38.26
AUTO                 3.77        -25.66   73.58
BANKS                3.19        -27.32  104.48
AC                   2.22         -9.32   38.96
FOOTWEAR             1.96        -70.25  138.52
TRAVEL               1.93        -75.35  163.15
DURABLES             1.87        -56.64   94.74
BREWERIES            1.73         -2.90   24.26
HEALTHCARE           1.66        -40.65   75.36
REALTY               1.41        -19.33   38.94
APPARELS             1.41        -28.09   66.70
CERAMICS             1.40        -66.46  117.03
REFINERIES           1.31        -16.28   45.69
CABLES               1.28         12.12   82.71
MINING               1.23          6.73    9.75
JEWELLERY            1.19       -105.61  177.04
CEMENT               1.16        -56.33  156.62
ENGINEERING          1.12        -64.70  140.04
CHEMICALS            1.04        -93.23  250.87
ENTERTAINMENT        0.79        -86.11  197.11
TEXTILES             0.44        -58.20  103.30
HOTELS               0.41       -108.68  182.29

In [29]:
# money to be made criteria-wise
df_portfolio_features.groupby('Criteria')['FTT Amt'].agg(['sum', 'count']).sort_values(by='sum', ascending=False)

                sum  count
Criteria
XY24      3604998.0     21
X40       1542040.0     15
AR        1372679.0     10
XR        1368632.0     12
X40N      1212636.0     10
OX40N      844246.0     10
XY25       438127.0      6
SR         310404.0      2

In [30]:
# money to be made conviction-wise
df_portfolio_features.groupby('Conviction')['FTT Amt'].agg(['sum', 'count']).sort_values(by='sum', ascending=False)

                  sum  count
Conviction
H-SC        3860596.0     24
M-SC        1510137.0     14
X-MC        1510057.0     15
X-LC        1437550.0     12
X-SC        1336808.0     10
H-MC         423063.0      3
L-SC         201562.0      2
M-LC         156022.0      1
M-MC         118353.0      2
H-LC          74085.0      1
L-MC          49800.0      1
L-LC          15729.0      1

In [31]:
# money to be made criteria and conviction-wise
df_portfolio_features.groupby(['Conviction', 'Criteria'])['FTT Amt'].agg(['sum', 'count']).sort_values(by='sum', ascending=False)

                           sum  count
Conviction Criteria
H-SC       XY24      1312885.0      6
           AR         979596.0      5
M-SC       XY24       885314.0      6
H-SC       XR         877423.0      7
X-LC       X40        735080.0      6
X-SC       XY24       650795.0      4
X-MC       X40        604787.0      7
X-SC       X40N       483840.0      4
X-MC       X40N       474473.0      4
H-SC       OX40N      380288.0      4
M-SC       OX40N      361585.0      5
H-SC       SR         310404.0      2
X-LC       XY24       305080.0      2
           X40N       254323.0      2
H-MC       XY24       234115.0      1
X-MC       XY24       216809.0      2
           XY25       213988.0      2
X-SC       X40        202173.0      2
H-MC       AR         188948.0      2
M-SC       XR         186198.0      2
M-LC       XR         156022.0      1
X-LC       XY25       143067.0      2
L-SC       OX40N      102373.0      1
           XR          99189.0      1
M-SC       AR          77040.0      1
H-LC       AR          74085.0      1
M-MC       XY25        65343.0      1
           AR          53010.0      1
L-MC       XR          49800.0      1
L-LC       XY25        15729.0      1

In [32]:
# notebook execution time

end_time = time.time()
execution_time = round(end_time - start_time, 0)
print(f"Notebook execution time: {execution_time} seconds")

Notebook execution time: 23.0 seconds