<a href="https://colab.research.google.com/github/ankit-rathi/Quantvesting_v2/blob/main/myStocks_Portfolio_Analysis.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
'''
!pip install pandas==2.2.2 -qq
!pip install pyxirr -qq
!pip install ta -qq
!pip install yfinance==0.2.59 -qq
'''

'\n!pip install pandas==2.2.2 -qq\n!pip install pyxirr -qq\n!pip install ta -qq\n!pip install yfinance==0.2.59 -qq\n'

In [2]:
# import libraries

import numpy as np
import pandas as pd
import datetime
import warnings
warnings.filterwarnings('ignore')
import yfinance as yfin
import ta
import matplotlib.pyplot as plt
import requests

In [3]:
# notebook start time
import time
import datetime
import pytz

start_time = time.time()

# function to print date timestamp
def print_date_time():
  tz_NY = pytz.timezone('Asia/Kolkata')
  datetime_NY = datetime.datetime.now(tz_NY)
  print("Run date time (IST):", datetime_NY.strftime("%Y-%m-%d %H:%M:%S"))

In [4]:
# function to get booked and reserved amount
def get_amt():
  # fetch the JSON data from the URL
  url = "https://raw.githubusercontent.com/ankit-rathi/Tradevesting_v1/main/data/myPortfolioAmts.json"
  response = requests.get(url)
  pf_amts = response.json()  # parse the JSON data

  # extract values from the JSON
  py_booked_amt_dm = pf_amts["py_booked_amt_dm"]
  py_booked_amt_sv = pf_amts["py_booked_amt_sv"]
  cy_booked_amt_dm = pf_amts["cy_booked_amt_dm"]
  cy_booked_amt_sv = pf_amts["cy_booked_amt_sv"]
  reserve_amt_dm = pf_amts["reserve_amt_dm"]
  reserve_amt_sv = pf_amts["reserve_amt_sv"]

  # perform calculations
  py_booked_amt = py_booked_amt_dm + py_booked_amt_sv
  cy_booked_amt = cy_booked_amt_dm + cy_booked_amt_sv
  reserve_amt = reserve_amt_dm + reserve_amt_sv
  total_booked_amt = py_booked_amt + cy_booked_amt

  return total_booked_amt, reserve_amt, cy_booked_amt, py_booked_amt

gen_output = 0

In [5]:
# function to format the amount
def format_amt(number):
    abs_number = abs(number)

    if abs_number >= 1_00_00_000:  # Crores
        formatted_amt = f"{number / 1_00_00_000:.2f} C"
    elif abs_number >= 1_00_000:  # Lakhs
        formatted_amt = f"{number / 1_00_000:.2f} L"
    elif abs_number >= 1_000:  # Thousands
        formatted_amt = f"{number / 1_000:.2f} K"
    else:
        formatted_amt = f"{number:.2f}"

    return formatted_amt

# function to set start and end date
def get_start_end_date():
  start_date = (datetime.date.today() + datetime.timedelta(days=-365)).strftime('%Y-%m-%d')
  end_date = (datetime.date.today() + datetime.timedelta(days=1)).strftime('%Y-%m-%d')
  return start_date, end_date

# function to fetch my portfolio csv
def get_mypfs_df():
  mypfs_df = pd.read_csv('https://raw.githubusercontent.com/ankit-rathi/Tradevesting_v1/main/data/myPortfolioStocks.csv')
  return mypfs_df

# function to fetch my prospects csv
def get_mypps_df():
  mypps_df = pd.read_csv('https://raw.githubusercontent.com/ankit-rathi/Tradevesting_v1/main/data/myProspectsScrips.csv')
  return mypps_df

# function to fetch screener data
def get_myscreen_df():
  myscreen_df = pd.read_csv('https://raw.githubusercontent.com/ankit-rathi/Tradevesting_v1/main/data/myScreenerDB.csv')
  return myscreen_df

# function to fetch momentum data
def get_myinvmt_df():
  myinvmt_df = pd.read_csv('https://raw.githubusercontent.com/ankit-rathi/Tradevesting_v1/main/data/myInvestments.csv')
  return myinvmt_df

# function to get the stock ids
def get_stock_ids(df_pf):
  stock_n100 = df_pf['Symbol'].unique()

  exclude = ['CADILAHC','MMTC', 'MASFIN']

  stock_ids = df_pf[~df_pf['Symbol'].isin(exclude) ]['Symbol'].unique()

  #mypf = mypf[mypf.Forecast.notnull()]
  #stock_ids = mypf['Symbol'].unique()

  #stock_ids.sort()
  return stock_ids

# get features from screener data
def get_screener_features():
  myscreen_df = get_myscreen_df()
  cols = ['Symbol', 'EPS', 'MedPE', 'ROCE%', 'ROE%', 'CapType']
  return myscreen_df[cols]

# get relative strength
def get_relative_strength(stock_list):

    # Dictionary to store stock tickers and their corresponding percentage price change
    stock_changes = {}

    # Loop through each stock and fetch its price data
    for stock in stock_list:
        try:
            # Download the stock data for the given date range
            stock_data = yfin.Ticker(stock + '.NS').history(period='1mo', interval='1d')[map(str.title, ['open', 'close', 'low', 'high', 'volume'])]

            # Calculate the percentage change for the stock
            if len(stock_data) > 0:
                start_price = stock_data['Close'].iloc[0]
                end_price = stock_data['Close'].iloc[-1]
                percent_change = round(((end_price - start_price) / start_price) * 100, 2)
                stock_changes[stock] = percent_change
            else:
                stock_changes[stock] = np.nan  # If no data is available, set to NaN

        except Exception as e:
            print(f"Error fetching data for {stock}: {e}")
            stock_changes[stock] = np.nan

    # Create a DataFrame with stock tickers and their percentage changes
    df = pd.DataFrame(list(stock_changes.items()), columns=['Symbol', 'Percent_Change'])

    # Drop any stocks with missing data (NaN values)
    df = df.dropna()

    # Calculate the percentile rank based on percentage change
    df['RSP'] = round(df['Percent_Change'].rank(pct=True) * 100, 2)
    cols = ['Symbol', 'RSP']
    df = df[cols]
    # Sort by percentile rank (optional)
    df = df.sort_values(by='RSP', ascending=False).reset_index(drop=True)

    return df

In [6]:
# function to get stock technicals
def stock_prec_dev(stock_symbol):
    #stock_symbol = 'ULTRACEMCO.NS'
    short_window = 20
    mid_window = 50
    long_window = 200
    moving_avg = 'SMA'

    start = datetime.datetime(*map(int, start_date.split('-')))
    end = datetime.datetime(*map(int, end_date.split('-')))

    stock_df = yfin.Ticker(stock_symbol + '.NS').history(period='max', interval='1d')[map(str.title, ['open', 'close', 'low', 'high', 'volume'])]

    stock_df['Max'] = round(max(stock_df['Close']),2)
    stock_df = stock_df[(stock_df.index <= end_date) & (stock_df.index >= start_date)]
    stock_df['200_SMA'] = round(stock_df['Close'].rolling(window = 200, min_periods = 1).mean(),0)
    stock_df['Dev%_200'] = round((stock_df['Close'] - stock_df['200_SMA'])*100/stock_df['200_SMA'],2)
    stock_df.dropna(axis = 0, inplace = True) # remove any null rows

    stock_df['20_SMA'] = stock_df['Close'].rolling(window=20).mean()
    stock_df['50_SMA'] = stock_df['Close'].rolling(window=50).mean()
    stock_df['Symbol'] = stock_symbol

    stock_df['Close'] = round(stock_df['Close'],2)
    stock_df['Min'] = round(min(stock_df['Close']),2)
    stock_df['RSI_14'] = ta.momentum.RSIIndicator(close=stock_df['Close'], window=14).rsi()
    stock_df['RSI_14'] = round(stock_df['RSI_14'],0)
    stock_df['Prev_Close'] = stock_df['Close'].shift(1)
    stock_df.drop(['Open', 'Low', 'High', 'Volume'], axis=1, inplace=True)
    stock_df = stock_df.tail(1)

    max_SMA = max(stock_df['20_SMA'].item(), stock_df['50_SMA'].item(), stock_df['200_SMA'].item())
    min_SMA = min(stock_df['20_SMA'].item(), stock_df['50_SMA'].item(), stock_df['200_SMA'].item())
    ABS_Spread = max_SMA - min_SMA
    stock_df['Spread%'] = round((ABS_Spread / stock_df['200_SMA'].item()) * 100,2)

    return stock_df

# function to compute stock attributes
def get_common_features(stock_ids, df_mypf):

  df_prec_dev = pd.DataFrame()
  df_tmp = get_screener_features()
  df_rs = get_relative_strength(stock_ids)

  for stock_id in stock_ids:
      tmp = stock_prec_dev(stock_id)
      tmp = tmp.reset_index()
      df_prec_dev = pd.concat([df_prec_dev, tmp], ignore_index = True)
  df_prec_dev = pd.merge(df_prec_dev, df_mypf, on= 'Symbol')
  df_prec_dev = pd.merge(df_prec_dev, df_tmp, on= 'Symbol', how='left')
  df_prec_dev = pd.merge(df_prec_dev, df_rs, on= 'Symbol', how='left')
  #print(df_prec_dev.columns)
  df_prec_dev['Curr_PE'] = round(df_prec_dev['Close']/df_prec_dev['EPS'],1)
  df_prec_dev['Dev%_PE'] = round((df_prec_dev['Curr_PE'] - df_prec_dev['MedPE'])*100/df_prec_dev['MedPE'],2)
  df_prec_dev['Conviction'] = df_prec_dev['Conviction'] + '-' + df_prec_dev['CapType']
  return df_prec_dev

# function to arrange stock features
def arrange_features(df_stocks, common_cols, diff_cols):
  df_stocks_common = df_stocks[common_cols].drop_duplicates()
  df_stocks_diff = df_stocks[diff_cols]
  df_stocks_diff['Investment'] = df_stocks_diff['AvgCost'] * df_stocks_diff['Shares']
  df_stocks_diff = df_stocks_diff.groupby(['Symbol'])[['Shares', 'Investment']].aggregate(['sum']).reset_index()
  df_stocks_diff.columns = ['Symbol', 'Shares', 'Investment']
  df_stocks_diff['AvgCost'] = round(df_stocks_diff['Investment']/df_stocks_diff['Shares'],2)
  df_stocks = pd.merge(df_stocks_diff, df_stocks_common, on='Symbol')
  return df_stocks

# plot fact distribution across dimension
def plot_pie_chart(df, dimension, fact):
  # grouping the data by category and calculating the sum of fact for each type
  grouped_data = df.groupby(dimension)[fact].sum()

  # sorting the grouped data in descending order
  grouped_data = grouped_data.sort_values(ascending=False)

  # creating a pie chart
  grouped_data.plot.pie(autopct='%1.1f%%', startangle=90, figsize=(6, 6))

  # adding a title and displaying the plot
  plt.title(f'{dimension} {fact} Distribution')
  plt.ylabel('')  # To hide the y-label
  plt.show()

In [7]:
# function to get portfolio features

def get_portfolio_features(df_common_features):

  print_date_time()
  print('-------------------')

  #df_common_features["Target"] = df_common_features["Target"].fillna(df_common_features["Max"])
  df_common_features['NTT'] = np.where(df_common_features['Strategy']== 'NTT', df_common_features["Target"], df_common_features['Max'])
  df_common_features['LTT'] = np.where(df_common_features['Strategy']== 'BTT', df_common_features["Target"], df_common_features['Max'])
  df_common_features['BOL'] = df_common_features['Min']

  tmp_df = df_common_features[df_common_features['Symbol'].isin(mypf_df[mypf_df['InPortfolio'] != 'NA'].Symbol.values)]
  print('qualified stocks: '+str(len(tmp_df['Symbol'].unique())))
  tmp_df1 = tmp_df[tmp_df['LatestQtr'] == 1]
  print('with latest results: '+str(len(tmp_df1['Symbol'].unique())))
  tmp_df1 = tmp_df1[tmp_df1['StarStock'] == 1]
  print('still star stocks: '+str(len(tmp_df1['Symbol'].unique())))
  tmp_df['Investment'] = tmp_df['AvgCost'] * tmp_df['Shares']
  tmp_df['Current'] = round(tmp_df['Close'] * tmp_df['Shares'],0)
  tmp_df['Previous'] = tmp_df['Prev_Close'] * tmp_df['Shares']
  tmp_df['EstimatedST'] = tmp_df['NTT'] * tmp_df['Shares']
  tmp_df['EstimatedLT'] = tmp_df['LTT'] * tmp_df['Shares']
  tmp_df['Current P/L'] = round((tmp_df['Current'] - tmp_df['Investment']),0)
  tmp_df['Today P/L%'] = round((tmp_df['Current'] - tmp_df['Previous'])*100/tmp_df['Previous'],2)
  tmp_df['Current P/L%'] = round((tmp_df['Current'] - tmp_df['Investment'])*100/tmp_df['Investment'],2)
  tmp_df['EstimatedST P/L%'] = round((tmp_df['EstimatedST'] - tmp_df['Investment'])*100/tmp_df['Investment'],2)
  tmp_df['EstimatedLT P/L%'] = round((tmp_df['EstimatedLT'] - tmp_df['Investment'])*100/tmp_df['Investment'],2)
  tmp_df['NTT%'] = round((tmp_df['NTT'] - tmp_df['Close'])*100/tmp_df['Close'],2)
  tmp_df['LTT%'] = round((tmp_df['LTT'] - tmp_df['Close'])*100/tmp_df['Close'],2)
  tmp_df['Gained%'] = round((tmp_df['Close'] - tmp_df['BOL'])*100/tmp_df['BOL'],2)
  investment = round(sum(tmp_df['AvgCost']*tmp_df['Shares']),0)
  current = round(sum(tmp_df['Close']*tmp_df['Shares']),0)
  tmp_df['InitAlloc%'] = round(tmp_df['Investment']*100/investment,2)
  tmp_df['CurrAlloc%'] = round(tmp_df['Current']*100/current,2)
  tmp_df['FTT'] = tmp_df['LTT']
  tmp_df.loc[tmp_df['Strategy'] == 'NTT', 'FTT'] = tmp_df['NTT']
  tmp_df['FTT%'] = tmp_df['LTT%']
  tmp_df.loc[tmp_df['Strategy'] == 'NTT', 'FTT%'] = tmp_df['NTT%']
  tmp_df['FTT Amt'] = round(tmp_df['FTT%'] * tmp_df['Current']/100,0)
  tmp_df['OTT%'] = round((tmp_df['FTT'] - tmp_df['AvgCost'])*100/tmp_df['AvgCost'],2)
  tmp_df['RRR Ind'] = round(tmp_df['Current P/L']/tmp_df['FTT Amt'],2)
  tmp_df['Risk Ind'] = round(tmp_df['Current P/L%']*tmp_df['CurrAlloc%'],0)

  return tmp_df

# function to print portfolio features
def print_portfolio_stats(df_portfolio_features, myinvmt_df):
  from pyxirr import xirr

  total_booked_amt, reserve_amt, cy_booked_amt, py_booked_amt = get_amt()

  dates = myinvmt_df['Date'].values
  dates = np.append(dates, datetime.date.today().strftime('%d-%b-%y'))
  investment = myinvmt_df['Investment'].values
  dates= pd.to_datetime(dates)

  current = round(sum(df_portfolio_features['Close']*df_portfolio_features['Shares']),0) + reserve_amt
  investment_xirr = np.append(investment, current)
  cagr = round(xirr(pd.DataFrame({"dates": dates, "amounts": investment_xirr}))*100,2)

  investment = -sum(investment)
  invested = round(sum(df_portfolio_features['AvgCost']*df_portfolio_features['Shares']),0) + reserve_amt
  previous = round(sum(df_portfolio_features['Prev_Close']*df_portfolio_features['Shares']),0) + reserve_amt
  cy_invested = investment + py_booked_amt

  today_pnl_amount = current-previous
  today_pnl_percentage = round((current-previous)*100/previous,2)

  curr_pnl_amount = current-invested
  curr_pnl_percentage = round((curr_pnl_amount)*100/(cy_invested),2)

  cy_pnl_amount = cy_booked_amt + curr_pnl_amount
  cy_pnl_percentage = round((cy_pnl_amount)*100/cy_invested,2)

  overall_pnl_amount = total_booked_amt + curr_pnl_amount
  overall_pnl_percentage = round((overall_pnl_amount)*100/investment,2)

  estimate_st = round(sum(df_portfolio_features['FTT']*df_portfolio_features['Shares']),0)  + reserve_amt
  est_st_pnl_amount = estimate_st-current
  est_st_pnl_percentage = round((est_st_pnl_amount)*100/current,2)

  estimate_lt = round(sum(df_portfolio_features['LTT']*df_portfolio_features['Shares']),0)  + reserve_amt
  est_lt_pnl_amount = estimate_lt-current
  est_lt_pnl_percentage = round((est_lt_pnl_amount)*100/current,2)

  total_profit = round(sum(df_portfolio_features[df_portfolio_features['Current P/L%'] > 0]['Current']) - sum(df_portfolio_features[df_portfolio_features['Current P/L%'] > 0]['Investment']),0)
  total_loss = round(sum(df_portfolio_features[df_portfolio_features['Current P/L%'] < 0]['Current']) - sum(df_portfolio_features[df_portfolio_features['Current P/L%'] < 0]['Investment']),0)

  cy_booked_percentage = round((cy_booked_amt)*100/current,2)
  py_booked_percentage = round((py_booked_amt)*100/investment,2)
  total_booked_percentage = round((total_booked_amt)*100/investment,2)

  print('-------------------')
  print('Initial Investment: ', format_amt(investment))
  print('CY Investment: ', format_amt(cy_invested))
  print('Reserve: ', format_amt(reserve_amt))
  print('Current: ',  format_amt(current))
  print('-------------------')
  print('Today PnL: '+ '{} ({}%)'.format(format_amt(today_pnl_amount), today_pnl_percentage))
  print('Current PnL: '+ '{} ({}%)'.format(format_amt(curr_pnl_amount), curr_pnl_percentage))
  print('CY Booked + Current PnL: '+ '{} ({}%)'.format(format_amt(cy_pnl_amount), cy_pnl_percentage))
  print('-------------------')
  print('Total profit: ', format_amt(total_profit))
  print('Total loss: ', format_amt(total_loss))
  print('-------------------')
  print('Total Booked + Current PnL: '+ '{} ({}%)'.format(format_amt(overall_pnl_amount), overall_pnl_percentage))
  print('Total Booked PnL: '+ '{} ({}%)'.format(format_amt(total_booked_amt), total_booked_percentage))
  print('Curr Year Booked PnL: '+ '{} ({}%)'.format(format_amt(cy_booked_amt), cy_booked_percentage))
  print('Prev Year Booked PnL: '+ '{} ({}%)'.format(format_amt(py_booked_amt), py_booked_percentage))
  print('===================')
  print('Est FTT: ',  format_amt(estimate_st))
  print('Est FTT PnL: '+ '{} ({}%)'.format(format_amt(est_st_pnl_amount), est_st_pnl_percentage))

  print('===================')
  print('Deployed: ', format_amt(investment))

  print('Current: ', format_amt(current))

  print('CAGR/XIRR %: '+'{}%'.format(cagr))

In [8]:
# get start and end date
start_date, end_date = get_start_end_date()

# get portfolio and prospects data
mypfs_df = get_mypfs_df()
mypps_df = get_mypps_df()
myinvmt_df = get_myinvmt_df()

# merge above datasets
mypf_df = pd.merge(mypfs_df, mypps_df, on="Symbol")

# seggregate dm and sv portfolio
dm_pf = mypf_df[mypf_df['InPortfolio'] == 'DM']
sv_pf = mypf_df[mypf_df['InPortfolio'] == 'SV']

# build portfolio stock dataframe
dm_stocks = get_stock_ids(dm_pf)
sv_stocks = get_stock_ids(sv_pf)
df_stocks = pd.concat([dm_pf,sv_pf], ignore_index = True)

# arrange common and diff stock features
common_cols = ['Symbol', 'Target', 'Criteria', 'Strategy', 'CumlRnk', 'LatestQtr', 'StarStock', 'Conviction', 'Category', 'InFolio', 'XIRR', 'MBQ']
diff_cols = ['Symbol', 'AvgCost', 'Shares']
df_stocks = arrange_features(df_stocks, common_cols, diff_cols)

# get common features
stock_ids = df_stocks['Symbol'].values
df_common_features = get_common_features(stock_ids, df_stocks)

df_common_features.reset_index(drop=True, inplace=True)
df_common_features.drop(['Date'], axis=1, inplace=True)
# get and print portfolio features
df_portfolio_features = get_portfolio_features(df_common_features)

print_portfolio_stats(df_portfolio_features, myinvmt_df)

df = df_portfolio_features
#plot_pie_chart(df, 'CapType', 'Current')
list_ox40n = list(df[df['MBQ'].str.contains('OX40N', na=False)]['Symbol'].values)

Run date time (IST): 2026-06-24 15:21:14
-------------------
qualified stocks: 92
with latest results: 31
still star stocks: 20
-------------------
Initial Investment:  1.40 C
CY Investment:  1.82 C
Reserve:  1.49 K
Current:  1.52 C
-------------------
Today PnL: 38.52 K (0.25%)
Current PnL: -31.31 L (-17.17%)
CY Booked + Current PnL: -29.23 L (-16.03%)
-------------------
Total profit:  4.04 L
Total loss:  -35.35 L
-------------------
Total Booked + Current PnL: 13.64 L (9.78%)
Total Booked PnL: 44.95 L (32.22%)
Curr Year Booked PnL: 2.08 L (1.37%)
Prev Year Booked PnL: 42.87 L (30.73%)
===================
Est FTT:  2.55 C
Est FTT PnL: 1.03 C (67.95%)
===================
Deployed:  1.40 C
Current:  1.52 C
CAGR/XIRR %: 3.95%

In [9]:
# top 5 near their targets
cols = ['Symbol', 'Today P/L%', 'Current P/L%', 'FTT%', 'OTT%', 'FTT Amt', 'Current P/L', 'Current', 'FTT', 'Dev%_PE', 'RSI_14','Conviction', 'Spread%',  'CumlRnk', 'RRR Ind', 'CurrAlloc%', 'Gained%', 'Criteria', 'Strategy', 'Category']
df_tmp = df_portfolio_features[~df_portfolio_features['Symbol'].isin(['ENRIN','BLUSPRING','DIGITIDE'])]
df_tmp = df_tmp.sort_values(by = 'FTT Amt', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
49,JSWINFRA,7.29,15.03,1.21,16.43,3087.0,33340.0,255114.0,342.00,-1.46,80.0,X-MC,3.83,61.0,10.80,1.68,44.64,X40N,NTT,REALTY
59,PIDILITIND,0.82,11.94,5.74,18.37,9067.0,16850.0,157960.0,1670.26,-21.61,71.0,X-LC,3.95,5.0,1.86,1.04,24.03,X40,ATH,CHEMICALS
51,KOTAKBANK,0.96,8.35,11.77,21.11,17659.0,11562.0,150035.0,453.24,-7.24,64.0,X-LC,5.10,12.0,0.65,0.99,14.74,X40,ATH,BANKS
72,SIS,4.73,3.22,17.48,21.26,20034.0,3578.0,114610.0,528.00,2739.90,70.0,H-SC,24.47,168.0,0.18,0.75,70.41,OX40N,NTT,MISC
55,MASFIN,1.19,-3.74,26.28,21.57,24787.0,-3660.0,94320.0,397.04,-16.89,52.0,H-SC,3.10,167.0,-0.15,0.62,12.43,XR,ATH,FINANCE

In [10]:
# top 5 today
df_tmp = df_portfolio_features.sort_values(by = 'Today P/L%', ascending=False)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
49,JSWINFRA,7.29,15.03,1.21,16.43,3087.0,33340.0,255114.0,342.0,-1.46,80.0,X-MC,3.83,61.0,10.80,1.68,44.64,X40N,NTT,REALTY
82,TRIDENT,5.06,-27.76,77.91,28.51,51920.0,-25614.0,66641.0,48.0,-7.14,70.0,M-SC,4.78,223.0,-0.49,0.44,24.85,XR,NTT,TEXTILES
72,SIS,4.73,3.22,17.48,21.26,20034.0,3578.0,114610.0,528.0,2739.90,70.0,H-SC,24.47,168.0,0.18,0.75,70.41,OX40N,NTT,MISC
0,5PAISA,3.89,-33.34,69.38,12.90,101046.0,-72854.0,145642.0,593.0,115.14,69.0,H-SC,1.48,170.0,-0.72,0.96,40.55,OX40N,NTT,FINANCE
21,DEN,2.85,-38.45,130.84,42.07,68016.0,-32480.0,51984.0,75.0,83.94,69.0,M-SC,6.65,235.0,-0.48,0.34,41.38,AR,NTT,ENTERTAINMENT

In [11]:
# bottom 5 today
df_tmp = df_portfolio_features.sort_values(by = 'Today P/L%', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
61,RAJESHEXPO,-5.00,-80.27,407.25,0.07,110210.0,-110115.0,27062.0,518.0,892.42,52.0,L-SC,36.23,268.0,-1.00,0.18,33.65,OX40N,NTT,JEWELLERY
24,EASEMYTRIP,-3.82,-58.33,249.67,45.70,183939.0,-103142.0,73673.0,26.4,-23.41,45.0,M-SC,4.35,204.0,-0.56,0.49,29.06,XY24,NTT,TRAVEL
71,SIEMENS,-3.55,-4.48,31.40,25.51,55815.0,-8340.0,177755.0,4671.5,49.20,42.0,H-LC,12.72,51.0,-0.15,1.17,24.80,AR,ATH,ELECTRICAL
11,BERGEPAINT,-3.02,-2.37,28.36,25.32,71363.0,-6118.0,251631.0,680.0,-7.69,56.0,X-MC,2.86,68.0,-0.09,1.66,30.96,XY24,NTT,PAINTS
10,BATAINDIA,-2.41,-53.81,192.74,35.20,114542.0,-69242.0,59428.0,2096.0,-22.02,54.0,X-SC,22.88,91.0,-0.60,0.39,17.86,X40,NTT,FOOTWEAR

In [12]:
# top 5 to exit based on CumlRnk
df_tmp = df_portfolio_features[~df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])]
df_tmp = df_tmp[(df_tmp['Current P/L%'] > -1) & (df_tmp['Current P/L%'] < 1)].sort_values(by = 'CumlRnk', ascending=False)
df_tmp[cols].head()

Empty DataFrame
Columns: [Symbol, Today P/L%, Current P/L%, FTT%, OTT%, FTT Amt, Current P/L, Current, FTT, Dev%_PE, RSI_14, Conviction, Spread%, CumlRnk, RRR Ind, CurrAlloc%, Gained%, Criteria, Strategy, Category]
Index: []

In [13]:
# OX40N stocks to exit
df_tmp = df_portfolio_features[(df_portfolio_features['Symbol'].isin(list_ox40n))].sort_values(by = 'Current P/L%', ascending=False)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
25,FINCABLES,-1.85,43.86,44.53,107.91,94579.0,64751.0,212395.0,1641.55,29.38,58.0,M-SC,24.70,220.0,0.68,1.40,59.79,OX40N,ATH,CABLES
72,SIS,4.73,3.22,17.48,21.26,20034.0,3578.0,114610.0,528.00,2739.90,70.0,H-SC,24.47,168.0,0.18,0.75,70.41,OX40N,NTT,MISC
16,CERA,-1.46,-17.15,49.54,23.89,72194.0,-30175.0,145728.0,9475.00,-20.05,62.0,H-SC,7.99,153.0,-0.42,0.96,40.04,OX40N,NTT,CERAMICS
83,TTKPRESTIG,1.90,-26.44,36.07,0.09,26740.0,-26644.0,74133.0,770.00,72.04,62.0,M-SC,8.88,250.0,-1.00,0.49,32.00,OX40N,NTT,DURABLES
43,INDIGOPNTS,1.67,-27.05,37.11,0.02,47254.0,-47223.0,127336.0,1408.00,94.20,61.0,M-SC,7.98,222.0,-1.00,0.84,44.47,OX40N,NTT,PAINTS

In [14]:
# top 5 to book for rotation
df_tmp = df_portfolio_features[(df_portfolio_features['Current P/L%'] > 20) ].sort_values(by = 'CumlRnk', ascending=False)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
25,FINCABLES,-1.85,43.86,44.53,107.91,94579.0,64751.0,212395.0,1641.55,29.38,58.0,M-SC,24.7,220.0,0.68,1.4,59.79,OX40N,ATH,CABLES
68,SATIN,2.43,32.03,15.00,51.83,54716.0,88492.0,364776.0,274.00,18.27,60.0,H-SC,40.7,159.0,1.62,2.4,77.70,XY24,NTT,FINANCE

In [15]:
# top 5 to monitor for exit
df_tmp = df_portfolio_features[~df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])]
df_tmp = df_tmp[(df_tmp['Current P/L%'] > 0) ].sort_values(by = 'Dev%_PE', ascending=False)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
72,SIS,4.73,3.22,17.48,21.26,20034.0,3578.0,114610.0,528.00,2739.90,70.0,H-SC,24.47,168.0,0.18,0.75,70.41,OX40N,NTT,MISC
9,BANDHANBNK,1.99,1.62,89.36,92.42,252944.0,4503.0,283062.0,400.00,142.82,58.0,H-SC,23.37,174.0,0.02,1.86,55.93,XY24,NTT,BANKS
74,STARHEALTH,-1.53,11.20,32.43,47.26,101379.0,31487.0,312610.0,761.00,75.48,71.0,H-SC,12.25,173.0,0.31,2.06,37.25,XY24,NTT,INSURANCE
25,FINCABLES,-1.85,43.86,44.53,107.91,94579.0,64751.0,212395.0,1641.55,29.38,58.0,M-SC,24.70,220.0,0.68,1.40,59.79,OX40N,ATH,CABLES
68,SATIN,2.43,32.03,15.00,51.83,54716.0,88492.0,364776.0,274.00,18.27,60.0,H-SC,40.70,159.0,1.62,2.40,77.70,XY24,NTT,FINANCE

In [16]:
# top 5 to book for rotation from weak conviction
df_tmp = df_portfolio_features[~df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])]
df_tmp = df_tmp[~df_tmp['Criteria'].isin(['XY25','XY24','X40', 'X40N'])].sort_values(by = 'RRR Ind', ascending=False)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
91,ZYDUSLIFE,-1.17,15.91,17.01,35.63,41321.0,33349.0,242923.0,1286.17,0.90,61.0,H-MC,13.78,120.0,0.81,1.60,27.72,AR,ATH,PHARMA
25,FINCABLES,-1.85,43.86,44.53,107.91,94579.0,64751.0,212395.0,1641.55,29.38,58.0,M-SC,24.70,220.0,0.68,1.40,59.79,OX40N,ATH,CABLES
73,SONACOMS,0.82,7.43,29.47,39.09,32027.0,7516.0,108675.0,804.02,-14.93,62.0,M-MC,18.15,193.0,0.23,0.72,53.74,AR,ATH,AUTO
72,SIS,4.73,3.22,17.48,21.26,20034.0,3578.0,114610.0,528.00,2739.90,70.0,H-SC,24.47,168.0,0.18,0.75,70.41,OX40N,NTT,MISC
75,SURYODAY,0.78,-1.37,24.75,23.03,43712.0,-2458.0,176613.0,216.00,92.98,57.0,H-SC,19.18,166.0,-0.06,1.16,48.70,XR,NTT,BANKS

In [17]:
# top 5 to accumulate based on lowest RSI_14
df_tmp = df_portfolio_features[df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])].sort_values(by = 'RSI_14', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
58,PGHH,-1.34,-32.73,96.24,32.01,138231.0,-69888.0,143632.0,17616.87,-54.51,37.0,X-MC,20.32,57.0,-0.51,0.95,0.00,X40,ATH,FMCG
19,COLPAL,-0.92,-25.50,87.72,39.86,172124.0,-67145.0,196220.0,3683.41,-9.89,38.0,X-MC,4.03,62.0,-0.39,1.29,10.99,XY25,ATH,FMCG
45,INFY,2.65,-28.07,86.64,34.24,194989.0,-87832.0,225056.0,1972.00,-43.40,38.0,X-LC,17.40,3.0,-0.45,1.48,2.65,X40,NTT,IT
33,HCLTECH,0.33,-27.76,68.20,21.51,119195.0,-67152.0,174772.0,1872.35,-23.90,39.0,X-LC,18.62,8.0,-0.56,1.15,0.33,X40,ATH,IT
79,TCS,2.37,-38.11,101.76,24.88,291789.0,-176531.0,286742.0,4253.91,-47.56,39.0,X-LC,19.78,2.0,-0.60,1.89,2.37,X40,ATH,IT

In [18]:
# top 5 to accumulate based on Spread and CumlRnk
df_tmp = df_portfolio_features[df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])]
df_tmp = df_tmp[(df_tmp['CumlRnk'] < 100)].sort_values(by = 'Spread%', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
11,BERGEPAINT,-3.02,-2.37,28.36,25.32,71363.0,-6118.0,251631.0,680.00,-7.69,56.0,X-MC,2.86,68.0,-0.09,1.66,30.96,XY24,NTT,PAINTS
56,MEDANTA,1.24,12.83,12.66,27.12,25215.0,22652.0,199169.0,1486.00,9.38,71.0,X-SC,3.19,87.0,0.90,1.31,37.24,XY24,NTT,HEALTHCARE
49,JSWINFRA,7.29,15.03,1.21,16.43,3087.0,33340.0,255114.0,342.00,-1.46,80.0,X-MC,3.83,61.0,10.80,1.68,44.64,X40N,NTT,REALTY
59,PIDILITIND,0.82,11.94,5.74,18.37,9067.0,16850.0,157960.0,1670.26,-21.61,71.0,X-LC,3.95,5.0,1.86,1.04,24.03,X40,ATH,CHEMICALS
19,COLPAL,-0.92,-25.50,87.72,39.86,172124.0,-67145.0,196220.0,3683.41,-9.89,38.0,X-MC,4.03,62.0,-0.39,1.29,10.99,XY25,ATH,FMCG

In [19]:
# top 5 to accumulate based on lowest Gained%
df_tmp = df_portfolio_features[df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])].sort_values(by = 'Gained%', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
58,PGHH,-1.34,-32.73,96.24,32.01,138231.0,-69888.0,143632.0,17616.87,-54.51,37.0,X-MC,20.32,57.0,-0.51,0.95,0.00,X40,ATH,FMCG
33,HCLTECH,0.33,-27.76,68.20,21.51,119195.0,-67152.0,174772.0,1872.35,-23.90,39.0,X-LC,18.62,8.0,-0.56,1.15,0.33,X40,ATH,IT
1,ABBOTINDIA,0.20,-14.05,37.37,18.07,57445.0,-25135.0,153720.0,35195.00,-26.90,39.0,X-MC,5.98,58.0,-0.44,1.01,1.75,X40,ATH,PHARMA
79,TCS,2.37,-38.11,101.76,24.88,291789.0,-176531.0,286742.0,4253.91,-47.56,39.0,X-LC,19.78,2.0,-0.60,1.89,2.37,X40,ATH,IT
45,INFY,2.65,-28.07,86.64,34.24,194989.0,-87832.0,225056.0,1972.00,-43.40,38.0,X-LC,17.40,3.0,-0.45,1.48,2.65,X40,NTT,IT

In [20]:
# top 5 to accumulate based on lowest CurrAlloc%
df_tmp = df_portfolio_features[df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])].sort_values(by = 'CurrAlloc%', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
10,BATAINDIA,-2.41,-53.81,192.74,35.20,114542.0,-69242.0,59428.0,2096.00,-22.02,54.0,X-SC,22.88,91.0,-0.60,0.39,17.86,X40,NTT,FOOTWEAR
64,RELAXO,1.28,-52.20,218.66,52.31,151708.0,-75779.0,69381.0,1176.00,-49.09,67.0,X-SC,14.86,92.0,-0.50,0.46,55.13,X40N,NTT,FOOTWEAR
60,QUESS,-0.27,2.69,69.34,73.90,76042.0,2873.0,109666.0,424.00,-44.90,73.0,X-SC,10.68,80.0,0.04,0.72,49.50,XY24,NTT,MISC
28,GODREJCP,-0.08,-8.73,44.04,31.47,59739.0,-12967.0,135647.0,1469.04,-3.99,49.0,X-LC,9.36,32.0,-0.22,0.89,4.08,X40N,ATH,FMCG
53,M&M,0.93,-0.53,24.04,23.38,33161.0,-738.0,137943.0,3802.40,-15.83,49.0,X-LC,10.62,25.0,-0.02,0.91,4.58,X40N,ATH,AUTO

In [21]:
# top 5 to accumulate based on CumlRnk
df_tmp = df_portfolio_features.sort_values(by = 'CumlRnk', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
47,ITC,0.12,-23.52,55.67,19.06,144828.0,-80012.0,260154.0,452.00,-57.95,51.0,X-LC,14.94,1.0,-0.55,1.71,4.82,X40,NTT,FMCG
79,TCS,2.37,-38.11,101.76,24.88,291789.0,-176531.0,286742.0,4253.91,-47.56,39.0,X-LC,19.78,2.0,-0.60,1.89,2.37,X40,ATH,IT
45,INFY,2.65,-28.07,86.64,34.24,194989.0,-87832.0,225056.0,1972.00,-43.40,38.0,X-LC,17.40,3.0,-0.45,1.48,2.65,X40,NTT,IT
81,TMPV,-1.42,-20.44,71.67,36.58,202894.0,-72746.0,283095.0,600.00,-83.62,39.0,X-LC,10.12,4.0,-0.36,1.86,18.97,XY24,NTT,AUTO
59,PIDILITIND,0.82,11.94,5.74,18.37,9067.0,16850.0,157960.0,1670.26,-21.61,71.0,X-LC,3.95,5.0,1.86,1.04,24.03,X40,ATH,CHEMICALS

In [22]:
# top 5 for average up
df_tmp = df_portfolio_features[(df_portfolio_features['Dev%_200'] > 5)].sort_values(by = 'CurrAlloc%', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
21,DEN,2.85,-38.45,130.84,42.07,68016.0,-32480.0,51984.0,75.00,83.94,69.0,M-SC,6.65,235.0,-0.48,0.34,41.38,AR,NTT,ENTERTAINMENT
44,INDUSINDBK,2.32,-31.60,94.28,32.89,49789.0,-24396.0,52810.0,1800.00,-348.60,53.0,L-MC,7.21,258.0,-0.49,0.35,29.99,XR,NTT,BANKS
3,ALKYLAMINE,-1.18,-24.12,155.18,93.63,118882.0,-24354.0,76609.0,4546.37,-18.73,52.0,H-SC,7.24,142.0,-0.20,0.50,44.66,SR,ATH,CHEMICALS
60,QUESS,-0.27,2.69,69.34,73.90,76042.0,2873.0,109666.0,424.00,-44.90,73.0,X-SC,10.68,80.0,0.04,0.72,49.50,XY24,NTT,MISC
73,SONACOMS,0.82,7.43,29.47,39.09,32027.0,7516.0,108675.0,804.02,-14.93,62.0,M-MC,18.15,193.0,0.23,0.72,53.74,AR,ATH,AUTO

In [23]:
# top 5 RSP
df_tmp = df_portfolio_features.sort_values(by = 'RSP', ascending=False)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
18,COFFEEDAY,-0.67,-42.32,134.54,35.27,88112.0,-48058.0,65491.0,80.0,-55.73,56.0,L-SC,16.47,266.0,-0.55,0.43,61.51,XR,NTT,HOTELS
64,RELAXO,1.28,-52.20,218.66,52.31,151708.0,-75779.0,69381.0,1176.0,-49.09,67.0,X-SC,14.86,92.0,-0.50,0.46,55.13,X40N,NTT,FOOTWEAR
49,JSWINFRA,7.29,15.03,1.21,16.43,3087.0,33340.0,255114.0,342.0,-1.46,80.0,X-MC,3.83,61.0,10.80,1.68,44.64,X40N,NTT,REALTY
60,QUESS,-0.27,2.69,69.34,73.90,76042.0,2873.0,109666.0,424.0,-44.90,73.0,X-SC,10.68,80.0,0.04,0.72,49.50,XY24,NTT,MISC
21,DEN,2.85,-38.45,130.84,42.07,68016.0,-32480.0,51984.0,75.0,83.94,69.0,M-SC,6.65,235.0,-0.48,0.34,41.38,AR,NTT,ENTERTAINMENT

In [24]:
# Top N allocation
df_tmp = df_portfolio_features.sort_values(by = 'CurrAlloc%', ascending=False)
top_n_values = [10, 25, 50]

sum_df = pd.DataFrame({
    'Top_N': top_n_values,
    'Sum_Alloc%': [df_tmp['CurrAlloc%'].head(n).sum() for n in top_n_values]
})

sum_df

   Top_N  Sum_Alloc%
0     10       19.31
1     25       42.60
2     50       72.72

In [25]:
# market-cap-wise allocation
df_tmp = df_portfolio_features[cols]
df_tmp.groupby(df_tmp['Conviction'].str[-2:])['CurrAlloc%'].sum().sort_values(ascending=False)

Conviction
SC    43.68
LC    30.41
MC    25.90
Name: CurrAlloc%, dtype: float64

In [26]:
# criteria-wise allocation
df_portfolio_features.groupby('Criteria')['CurrAlloc%'].sum().sort_values(ascending=False)

Criteria
XY24     27.73
X40      24.66
X40N     17.47
XR        8.89
OX40N     7.18
AR        6.77
XY25      6.44
SR        0.85
Name: CurrAlloc%, dtype: float64

In [27]:
# conviction-wise allocation
df_portfolio_features.groupby('Conviction')['CurrAlloc%'].sum().sort_values(ascending=False)

Conviction
X-LC    28.44
H-SC    22.95
X-MC    20.80
M-SC    10.15
X-SC     9.97
H-MC     2.71
M-MC     2.04
H-LC     1.17
M-LC     0.80
L-SC     0.61
L-MC     0.35
Name: CurrAlloc%, dtype: float64

In [28]:
# sector-wise stats
df_tmp = df_portfolio_features.groupby('Category')[['CurrAlloc%', 'Current', 'Current P/L', 'FTT Amt']].sum().sort_values(by=['Current', 'Current P/L'], ascending=False)
df_tmp['Current P/L%'] = round(df_tmp['Current P/L'] * 100 / df_tmp['Current'], 2)
df_tmp['FTT%'] = round(df_tmp['FTT Amt'] * 100 / df_tmp['Current'], 2)
cols = ['CurrAlloc%', 'Current P/L%', 'FTT%']
df_tmp[cols].sort_values(by=['CurrAlloc%'], ascending=False)

               CurrAlloc%  Current P/L%    FTT%
Category
FMCG                14.47        -20.38   62.61
FINANCE             11.04        -10.00   57.84
IT                   9.61        -54.17  131.26
MISC                 7.24        -21.93   74.25
AUTO                 6.55        -10.14   51.43
BANKS                5.83         -2.55   49.97
PAINTS               5.56        -16.77   36.69
INSURANCE            5.36         -1.92   36.30
PHARMA               5.03          3.04   26.97
ELECTRICAL           4.09        -13.72   53.85
CHEMICALS            2.18        -22.49   95.49
HEALTHCARE           2.09        -12.44   41.78
APPARELS             1.88          6.14   25.38
AC                   1.80        -16.48   48.06
FOOTWEAR             1.72        -68.98  136.74
REALTY               1.68         13.07    1.21
TRAVEL               1.60        -85.23  177.97
DURABLES             1.57        -63.14  102.83
BREWERIES            1.54         -0.15   20.94
CERAMICS             1.43        -40.96   83.78
CABLES               1.40         30.49   44.53
ENGINEERING          1.39        -15.08   67.71
REFINERIES           1.12        -18.58   48.58
JEWELLERY            1.07        -96.51  164.78
CEMENT               1.06        -65.81  189.85
ENTERTAINMENT        0.81        -57.41  151.30
TEXTILES             0.44        -38.44   77.91
HOTELS               0.43        -73.38  134.54

In [29]:
# money to be made criteria-wise
df_portfolio_features.groupby('Criteria')['FTT Amt'].agg(['sum', 'count']).sort_values(by='sum', ascending=False)

                sum  count
Criteria
XY24      3385552.0     21
X40       1935271.0     19
XR        1333605.0     13
AR        1148097.0      9
X40N      1067648.0     13
OX40N      701701.0     10
XY25       458311.0      5
SR         288745.0      2

In [30]:
# money to be made conviction-wise
df_portfolio_features.groupby('Conviction')['FTT Amt'].agg(['sum', 'count']).sort_values(by='sum', ascending=False)

                  sum  count
Conviction
H-SC        3291147.0     24
X-LC        1964647.0     21
X-MC        1558468.0     15
M-SC        1377079.0     14
X-SC        1288428.0      9
H-MC         287185.0      2
L-SC         198322.0      2
M-LC         170626.0      1
M-MC          77424.0      2
H-LC          55815.0      1
L-MC          49789.0      1

In [31]:
# money to be made criteria and conviction-wise
df_portfolio_features.groupby(['Conviction', 'Criteria'])['FTT Amt'].agg(['sum', 'count']).sort_values(by='sum', ascending=False)

                           sum  count
Conviction Criteria
X-LC       X40       1053459.0     10
H-SC       XY24       966977.0      6
           AR         950918.0      5
M-SC       XY24       821600.0      6
H-SC       XR         793546.0      7
X-SC       XY24       778830.0      4
X-MC       X40        671433.0      7
           X40N       410577.0      4
X-LC       X40N       357852.0      6
           XY24       349848.0      2
M-SC       OX40N      300530.0      5
X-SC       X40N       299219.0      3
H-SC       OX40N      290961.0      4
           SR         288745.0      2
X-MC       XY25       254025.0      2
H-MC       XY24       245864.0      1
X-MC       XY24       222433.0      2
X-SC       X40        210379.0      2
M-SC       XR         186933.0      2
M-LC       XR         170626.0      1
X-LC       XY25       158889.0      2
L-SC       OX40N      110210.0      1
           XR          88112.0      1
M-SC       AR          68016.0      1
H-LC       AR          55815.0      1
L-MC       XR          49789.0      1
M-MC       XY25        45397.0      1
X-LC       XR          44599.0      1
H-MC       AR          41321.0      1
M-MC       AR          32027.0      1

In [32]:
# notebook execution time

end_time = time.time()
execution_time = round(end_time - start_time, 0)
print(f"Notebook execution time: {execution_time} seconds")

Notebook execution time: 28.0 seconds