<a href="https://colab.research.google.com/github/ankit-rathi/Quantvesting_v2/blob/main/myStocks_Portfolio_Analysis.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
'''
!pip install pandas==2.2.2 -qq
!pip install pyxirr -qq
!pip install ta -qq
!pip install yfinance==0.2.59 -qq
'''

'\n!pip install pandas==2.2.2 -qq\n!pip install pyxirr -qq\n!pip install ta -qq\n!pip install yfinance==0.2.59 -qq\n'

In [2]:
# import libraries

import numpy as np
import pandas as pd
import datetime
import warnings
warnings.filterwarnings('ignore')
import yfinance as yfin
import ta
import matplotlib.pyplot as plt
import requests

In [3]:
# notebook start time
import time
import datetime
import pytz

start_time = time.time()

# function to print date timestamp
def print_date_time():
  tz_NY = pytz.timezone('Asia/Kolkata')
  datetime_NY = datetime.datetime.now(tz_NY)
  print("Run date time (IST):", datetime_NY.strftime("%Y-%m-%d %H:%M:%S"))

In [4]:
# function to get booked and reserved amount
def get_amt():
  # fetch the JSON data from the URL
  url = "https://raw.githubusercontent.com/ankit-rathi/Tradevesting_v1/main/data/myPortfolioAmts.json"
  response = requests.get(url)
  pf_amts = response.json()  # parse the JSON data

  # extract values from the JSON
  py_booked_amt_dm = pf_amts["py_booked_amt_dm"]
  py_booked_amt_sv = pf_amts["py_booked_amt_sv"]
  cy_booked_amt_dm = pf_amts["cy_booked_amt_dm"]
  cy_booked_amt_sv = pf_amts["cy_booked_amt_sv"]
  reserve_amt_dm = pf_amts["reserve_amt_dm"]
  reserve_amt_sv = pf_amts["reserve_amt_sv"]

  # perform calculations
  py_booked_amt = py_booked_amt_dm + py_booked_amt_sv
  cy_booked_amt = cy_booked_amt_dm + cy_booked_amt_sv
  reserve_amt = reserve_amt_dm + reserve_amt_sv
  total_booked_amt = py_booked_amt + cy_booked_amt

  return total_booked_amt, reserve_amt, cy_booked_amt, py_booked_amt

gen_output = 0

In [5]:
# function to format the amount
def format_amt(number):
    abs_number = abs(number)

    if abs_number >= 1_00_00_000:  # Crores
        formatted_amt = f"{number / 1_00_00_000:.2f} C"
    elif abs_number >= 1_00_000:  # Lakhs
        formatted_amt = f"{number / 1_00_000:.2f} L"
    elif abs_number >= 1_000:  # Thousands
        formatted_amt = f"{number / 1_000:.2f} K"
    else:
        formatted_amt = f"{number:.2f}"

    return formatted_amt

# function to set start and end date
def get_start_end_date():
  start_date = (datetime.date.today() + datetime.timedelta(days=-365)).strftime('%Y-%m-%d')
  end_date = (datetime.date.today() + datetime.timedelta(days=1)).strftime('%Y-%m-%d')
  return start_date, end_date

# function to fetch my portfolio csv
def get_mypfs_df():
  mypfs_df = pd.read_csv('https://raw.githubusercontent.com/ankit-rathi/Tradevesting_v1/main/data/myPortfolioStocks.csv')
  return mypfs_df

# function to fetch my prospects csv
def get_mypps_df():
  mypps_df = pd.read_csv('https://raw.githubusercontent.com/ankit-rathi/Tradevesting_v1/main/data/myProspectsScrips.csv')
  return mypps_df

# function to fetch screener data
def get_myscreen_df():
  myscreen_df = pd.read_csv('https://raw.githubusercontent.com/ankit-rathi/Tradevesting_v1/main/data/myScreenerDB.csv')
  return myscreen_df

# function to fetch momentum data
def get_myinvmt_df():
  myinvmt_df = pd.read_csv('https://raw.githubusercontent.com/ankit-rathi/Tradevesting_v1/main/data/myInvestments.csv')
  return myinvmt_df

# function to get the stock ids
def get_stock_ids(df_pf):
  stock_n100 = df_pf['Symbol'].unique()

  exclude = ['CADILAHC','MMTC', 'MASFIN']

  stock_ids = df_pf[~df_pf['Symbol'].isin(exclude) ]['Symbol'].unique()

  #mypf = mypf[mypf.Forecast.notnull()]
  #stock_ids = mypf['Symbol'].unique()

  #stock_ids.sort()
  return stock_ids

# get features from screener data
def get_screener_features():
  myscreen_df = get_myscreen_df()
  cols = ['Symbol', 'EPS', 'MedPE', 'ROCE%', 'ROE%', 'CapType']
  return myscreen_df[cols]

# get relative strength
def get_relative_strength(stock_list):

    # Dictionary to store stock tickers and their corresponding percentage price change
    stock_changes = {}

    # Loop through each stock and fetch its price data
    for stock in stock_list:
        try:
            # Download the stock data for the given date range
            stock_data = yfin.Ticker(stock + '.NS').history(period='1mo', interval='1d')[map(str.title, ['open', 'close', 'low', 'high', 'volume'])]

            # Calculate the percentage change for the stock
            if len(stock_data) > 0:
                start_price = stock_data['Close'].iloc[0]
                end_price = stock_data['Close'].iloc[-1]
                percent_change = round(((end_price - start_price) / start_price) * 100, 2)
                stock_changes[stock] = percent_change
            else:
                stock_changes[stock] = np.nan  # If no data is available, set to NaN

        except Exception as e:
            print(f"Error fetching data for {stock}: {e}")
            stock_changes[stock] = np.nan

    # Create a DataFrame with stock tickers and their percentage changes
    df = pd.DataFrame(list(stock_changes.items()), columns=['Symbol', 'Percent_Change'])

    # Drop any stocks with missing data (NaN values)
    df = df.dropna()

    # Calculate the percentile rank based on percentage change
    df['RSP'] = round(df['Percent_Change'].rank(pct=True) * 100, 2)
    cols = ['Symbol', 'RSP']
    df = df[cols]
    # Sort by percentile rank (optional)
    df = df.sort_values(by='RSP', ascending=False).reset_index(drop=True)

    return df

In [6]:
# function to get stock technicals
def stock_prec_dev(stock_symbol):
    #stock_symbol = 'ULTRACEMCO.NS'
    short_window = 20
    mid_window = 50
    long_window = 200
    moving_avg = 'SMA'

    start = datetime.datetime(*map(int, start_date.split('-')))
    end = datetime.datetime(*map(int, end_date.split('-')))

    stock_df = yfin.Ticker(stock_symbol + '.NS').history(period='max', interval='1d')[map(str.title, ['open', 'close', 'low', 'high', 'volume'])]

    stock_df['Max'] = round(max(stock_df['Close']),2)
    stock_df = stock_df[(stock_df.index <= end_date) & (stock_df.index >= start_date)]
    stock_df['200_SMA'] = round(stock_df['Close'].rolling(window = 200, min_periods = 1).mean(),0)
    stock_df['Dev%_200'] = round((stock_df['Close'] - stock_df['200_SMA'])*100/stock_df['200_SMA'],2)
    stock_df.dropna(axis = 0, inplace = True) # remove any null rows

    stock_df['20_SMA'] = stock_df['Close'].rolling(window=20).mean()
    stock_df['50_SMA'] = stock_df['Close'].rolling(window=50).mean()
    stock_df['Symbol'] = stock_symbol

    stock_df['Close'] = round(stock_df['Close'],2)
    stock_df['Min'] = round(min(stock_df['Close']),2)
    stock_df['RSI_14'] = ta.momentum.RSIIndicator(close=stock_df['Close'], window=14).rsi()
    stock_df['RSI_14'] = round(stock_df['RSI_14'],0)
    stock_df['Prev_Close'] = stock_df['Close'].shift(1)
    stock_df.drop(['Open', 'Low', 'High', 'Volume'], axis=1, inplace=True)
    stock_df = stock_df.tail(1)

    max_SMA = max(stock_df['20_SMA'].item(), stock_df['50_SMA'].item(), stock_df['200_SMA'].item())
    min_SMA = min(stock_df['20_SMA'].item(), stock_df['50_SMA'].item(), stock_df['200_SMA'].item())
    ABS_Spread = max_SMA - min_SMA
    stock_df['Spread%'] = round((ABS_Spread / stock_df['200_SMA'].item()) * 100,2)

    return stock_df

# function to compute stock attributes
def get_common_features(stock_ids, df_mypf):

  df_prec_dev = pd.DataFrame()
  df_tmp = get_screener_features()
  df_rs = get_relative_strength(stock_ids)

  for stock_id in stock_ids:
      tmp = stock_prec_dev(stock_id)
      tmp = tmp.reset_index()
      df_prec_dev = pd.concat([df_prec_dev, tmp], ignore_index = True)
  df_prec_dev = pd.merge(df_prec_dev, df_mypf, on= 'Symbol')
  df_prec_dev = pd.merge(df_prec_dev, df_tmp, on= 'Symbol', how='left')
  df_prec_dev = pd.merge(df_prec_dev, df_rs, on= 'Symbol', how='left')
  #print(df_prec_dev.columns)
  df_prec_dev['Curr_PE'] = round(df_prec_dev['Close']/df_prec_dev['EPS'],1)
  df_prec_dev['Dev%_PE'] = round((df_prec_dev['Curr_PE'] - df_prec_dev['MedPE'])*100/df_prec_dev['MedPE'],2)
  df_prec_dev['Conviction'] = df_prec_dev['Conviction'] + '-' + df_prec_dev['CapType']
  return df_prec_dev

# function to arrange stock features
def arrange_features(df_stocks, common_cols, diff_cols):
  df_stocks_common = df_stocks[common_cols].drop_duplicates()
  df_stocks_diff = df_stocks[diff_cols]
  df_stocks_diff['Investment'] = df_stocks_diff['AvgCost'] * df_stocks_diff['Shares']
  df_stocks_diff = df_stocks_diff.groupby(['Symbol'])[['Shares', 'Investment']].aggregate(['sum']).reset_index()
  df_stocks_diff.columns = ['Symbol', 'Shares', 'Investment']
  df_stocks_diff['AvgCost'] = round(df_stocks_diff['Investment']/df_stocks_diff['Shares'],2)
  df_stocks = pd.merge(df_stocks_diff, df_stocks_common, on='Symbol')
  return df_stocks

# plot fact distribution across dimension
def plot_pie_chart(df, dimension, fact):
  # grouping the data by category and calculating the sum of fact for each type
  grouped_data = df.groupby(dimension)[fact].sum()

  # sorting the grouped data in descending order
  grouped_data = grouped_data.sort_values(ascending=False)

  # creating a pie chart
  grouped_data.plot.pie(autopct='%1.1f%%', startangle=90, figsize=(6, 6))

  # adding a title and displaying the plot
  plt.title(f'{dimension} {fact} Distribution')
  plt.ylabel('')  # To hide the y-label
  plt.show()

In [7]:
# function to get portfolio features

def get_portfolio_features(df_common_features):

  print_date_time()
  print('-------------------')

  #df_common_features["Target"] = df_common_features["Target"].fillna(df_common_features["Max"])
  df_common_features['NTT'] = np.where(df_common_features['Strategy']== 'NTT', df_common_features["Target"], df_common_features['Max'])
  df_common_features['LTT'] = np.where(df_common_features['Strategy']== 'BTT', df_common_features["Target"], df_common_features['Max'])
  df_common_features['BOL'] = df_common_features['Min']

  tmp_df = df_common_features[df_common_features['Symbol'].isin(mypf_df[mypf_df['InPortfolio'] != 'NA'].Symbol.values)]
  print('qualified stocks: '+str(len(tmp_df['Symbol'].unique())))
  tmp_df1 = tmp_df[tmp_df['LatestQtr'] == 1]
  print('with latest results: '+str(len(tmp_df1['Symbol'].unique())))
  tmp_df1 = tmp_df1[tmp_df1['StarStock'] == 1]
  print('still star stocks: '+str(len(tmp_df1['Symbol'].unique())))
  tmp_df['Investment'] = tmp_df['AvgCost'] * tmp_df['Shares']
  tmp_df['Current'] = round(tmp_df['Close'] * tmp_df['Shares'],0)
  tmp_df['Previous'] = tmp_df['Prev_Close'] * tmp_df['Shares']
  tmp_df['EstimatedST'] = tmp_df['NTT'] * tmp_df['Shares']
  tmp_df['EstimatedLT'] = tmp_df['LTT'] * tmp_df['Shares']
  tmp_df['Current P/L'] = round((tmp_df['Current'] - tmp_df['Investment']),0)
  tmp_df['Today P/L%'] = round((tmp_df['Current'] - tmp_df['Previous'])*100/tmp_df['Previous'],2)
  tmp_df['Current P/L%'] = round((tmp_df['Current'] - tmp_df['Investment'])*100/tmp_df['Investment'],2)
  tmp_df['EstimatedST P/L%'] = round((tmp_df['EstimatedST'] - tmp_df['Investment'])*100/tmp_df['Investment'],2)
  tmp_df['EstimatedLT P/L%'] = round((tmp_df['EstimatedLT'] - tmp_df['Investment'])*100/tmp_df['Investment'],2)
  tmp_df['NTT%'] = round((tmp_df['NTT'] - tmp_df['Close'])*100/tmp_df['Close'],2)
  tmp_df['LTT%'] = round((tmp_df['LTT'] - tmp_df['Close'])*100/tmp_df['Close'],2)
  tmp_df['Gained%'] = round((tmp_df['Close'] - tmp_df['BOL'])*100/tmp_df['BOL'],2)
  investment = round(sum(tmp_df['AvgCost']*tmp_df['Shares']),0)
  current = round(sum(tmp_df['Close']*tmp_df['Shares']),0)
  tmp_df['InitAlloc%'] = round(tmp_df['Investment']*100/investment,2)
  tmp_df['CurrAlloc%'] = round(tmp_df['Current']*100/current,2)
  tmp_df['FTT'] = tmp_df['LTT']
  tmp_df.loc[tmp_df['Strategy'] == 'NTT', 'FTT'] = tmp_df['NTT']
  tmp_df['FTT%'] = tmp_df['LTT%']
  tmp_df.loc[tmp_df['Strategy'] == 'NTT', 'FTT%'] = tmp_df['NTT%']
  tmp_df['FTT Amt'] = round(tmp_df['FTT%'] * tmp_df['Current']/100,0)
  tmp_df['OTT%'] = round((tmp_df['FTT'] - tmp_df['AvgCost'])*100/tmp_df['AvgCost'],2)
  tmp_df['RRR Ind'] = round(tmp_df['Current P/L']/tmp_df['FTT Amt'],2)
  tmp_df['Risk Ind'] = round(tmp_df['Current P/L%']*tmp_df['CurrAlloc%'],0)

  return tmp_df

# function to print portfolio features
def print_portfolio_stats(df_portfolio_features, myinvmt_df):
  from pyxirr import xirr

  total_booked_amt, reserve_amt, cy_booked_amt, py_booked_amt = get_amt()

  dates = myinvmt_df['Date'].values
  dates = np.append(dates, datetime.date.today().strftime('%d-%b-%y'))
  investment = myinvmt_df['Investment'].values
  dates= pd.to_datetime(dates)

  current = round(sum(df_portfolio_features['Close']*df_portfolio_features['Shares']),0) + reserve_amt
  investment_xirr = np.append(investment, current)
  cagr = round(xirr(pd.DataFrame({"dates": dates, "amounts": investment_xirr}))*100,2)

  investment = -sum(investment)
  invested = round(sum(df_portfolio_features['AvgCost']*df_portfolio_features['Shares']),0) + reserve_amt
  previous = round(sum(df_portfolio_features['Prev_Close']*df_portfolio_features['Shares']),0) + reserve_amt
  cy_invested = investment + py_booked_amt

  today_pnl_amount = current-previous
  today_pnl_percentage = round((current-previous)*100/previous,2)

  curr_pnl_amount = current-invested
  curr_pnl_percentage = round((curr_pnl_amount)*100/(cy_invested),2)

  cy_pnl_amount = cy_booked_amt + curr_pnl_amount
  cy_pnl_percentage = round((cy_pnl_amount)*100/cy_invested,2)

  overall_pnl_amount = total_booked_amt + curr_pnl_amount
  overall_pnl_percentage = round((overall_pnl_amount)*100/investment,2)

  estimate_st = round(sum(df_portfolio_features['FTT']*df_portfolio_features['Shares']),0)  + reserve_amt
  est_st_pnl_amount = estimate_st-current
  est_st_pnl_percentage = round((est_st_pnl_amount)*100/current,2)

  estimate_lt = round(sum(df_portfolio_features['LTT']*df_portfolio_features['Shares']),0)  + reserve_amt
  est_lt_pnl_amount = estimate_lt-current
  est_lt_pnl_percentage = round((est_lt_pnl_amount)*100/current,2)

  total_profit = round(sum(df_portfolio_features[df_portfolio_features['Current P/L%'] > 0]['Current']) - sum(df_portfolio_features[df_portfolio_features['Current P/L%'] > 0]['Investment']),0)
  total_loss = round(sum(df_portfolio_features[df_portfolio_features['Current P/L%'] < 0]['Current']) - sum(df_portfolio_features[df_portfolio_features['Current P/L%'] < 0]['Investment']),0)

  cy_booked_percentage = round((cy_booked_amt)*100/current,2)
  py_booked_percentage = round((py_booked_amt)*100/investment,2)
  total_booked_percentage = round((total_booked_amt)*100/investment,2)

  print('-------------------')
  print('Initial Investment: ', format_amt(investment))
  print('CY Investment: ', format_amt(cy_invested))
  print('Reserve: ', format_amt(reserve_amt))
  print('Current: ',  format_amt(current))
  print('-------------------')
  print('Today PnL: '+ '{} ({}%)'.format(format_amt(today_pnl_amount), today_pnl_percentage))
  print('Current PnL: '+ '{} ({}%)'.format(format_amt(curr_pnl_amount), curr_pnl_percentage))
  print('CY Booked + Current PnL: '+ '{} ({}%)'.format(format_amt(cy_pnl_amount), cy_pnl_percentage))
  print('-------------------')
  print('Total profit: ', format_amt(total_profit))
  print('Total loss: ', format_amt(total_loss))
  print('-------------------')
  print('Total Booked + Current PnL: '+ '{} ({}%)'.format(format_amt(overall_pnl_amount), overall_pnl_percentage))
  print('Total Booked PnL: '+ '{} ({}%)'.format(format_amt(total_booked_amt), total_booked_percentage))
  print('Curr Year Booked PnL: '+ '{} ({}%)'.format(format_amt(cy_booked_amt), cy_booked_percentage))
  print('Prev Year Booked PnL: '+ '{} ({}%)'.format(format_amt(py_booked_amt), py_booked_percentage))
  print('===================')
  print('Est FTT: ',  format_amt(estimate_st))
  print('Est FTT PnL: '+ '{} ({}%)'.format(format_amt(est_st_pnl_amount), est_st_pnl_percentage))

  print('===================')
  print('Deployed: ', format_amt(investment))

  print('Current: ', format_amt(current))

  print('CAGR/XIRR %: '+'{}%'.format(cagr))

In [8]:
# get start and end date
start_date, end_date = get_start_end_date()

# get portfolio and prospects data
mypfs_df = get_mypfs_df()
mypps_df = get_mypps_df()
myinvmt_df = get_myinvmt_df()

# merge above datasets
mypf_df = pd.merge(mypfs_df, mypps_df, on="Symbol")

# seggregate dm and sv portfolio
dm_pf = mypf_df[mypf_df['InPortfolio'] == 'DM']
sv_pf = mypf_df[mypf_df['InPortfolio'] == 'SV']

# build portfolio stock dataframe
dm_stocks = get_stock_ids(dm_pf)
sv_stocks = get_stock_ids(sv_pf)
df_stocks = pd.concat([dm_pf,sv_pf], ignore_index = True)

# arrange common and diff stock features
common_cols = ['Symbol', 'Target', 'Criteria', 'Strategy', 'CumlRnk', 'LatestQtr', 'StarStock', 'Conviction', 'Category', 'InFolio', 'XIRR', 'MBQ']
diff_cols = ['Symbol', 'AvgCost', 'Shares']
df_stocks = arrange_features(df_stocks, common_cols, diff_cols)

# get common features
stock_ids = df_stocks['Symbol'].values
df_common_features = get_common_features(stock_ids, df_stocks)

df_common_features.reset_index(drop=True, inplace=True)
df_common_features.drop(['Date'], axis=1, inplace=True)
# get and print portfolio features
df_portfolio_features = get_portfolio_features(df_common_features)

print_portfolio_stats(df_portfolio_features, myinvmt_df)

df = df_portfolio_features
#plot_pie_chart(df, 'CapType', 'Current')
list_ox40n = list(df[df['MBQ'].str.contains('OX40N', na=False)]['Symbol'].values)

Run date time (IST): 2026-07-14 10:21:07
-------------------
qualified stocks: 92
with latest results: 31
still star stocks: 20
-------------------
Initial Investment:  1.40 C
CY Investment:  1.82 C
Reserve:  1.49 K
Current:  1.52 C
-------------------
Today PnL: -98.10 K (-0.64%)
Current PnL: -30.80 L (-16.89%)
CY Booked + Current PnL: -28.72 L (-15.75%)
-------------------
Total profit:  4.55 L
Total loss:  -35.35 L
-------------------
Total Booked + Current PnL: 14.15 L (10.14%)
Total Booked PnL: 44.95 L (32.22%)
Curr Year Booked PnL: 2.08 L (1.37%)
Prev Year Booked PnL: 42.87 L (30.73%)
===================
Est FTT:  2.55 C
Est FTT PnL: 1.03 C (67.33%)
===================
Deployed:  1.40 C
Current:  1.52 C
CAGR/XIRR %: 4.0%

In [9]:
# top 5 near their targets
cols = ['Symbol', 'Today P/L%', 'Current P/L%', 'FTT%', 'OTT%', 'FTT Amt', 'Current P/L', 'Current', 'FTT', 'Dev%_PE', 'RSI_14','Conviction', 'Spread%',  'CumlRnk', 'RRR Ind', 'CurrAlloc%', 'Gained%', 'Criteria', 'Strategy', 'Category']
df_tmp = df_portfolio_features[~df_portfolio_features['Symbol'].isin(['ENRIN','BLUSPRING','DIGITIDE'])]
df_tmp = df_tmp.sort_values(by = 'FTT Amt', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
49,JSWINFRA,3.76,16.58,-0.13,16.43,-336.0,36776.0,258550.0,342.00,-0.11,69.0,X-MC,14.91,61.0,-109.45,1.70,46.59,X40N,NTT,REALTY
68,SATIN,4.82,49.10,1.84,51.83,7580.0,135647.0,411931.0,274.00,34.03,67.0,H-SC,43.34,159.0,17.90,2.70,100.67,XY24,NTT,FINANCE
59,PIDILITIND,-1.86,9.94,7.67,18.37,11898.0,14020.0,155130.0,1670.26,-22.95,47.0,X-LC,8.39,5.0,1.18,1.02,21.80,X40,ATH,CHEMICALS
83,TTKPRESTIG,0.56,-12.99,15.04,0.09,13188.0,-13092.0,87685.0,770.00,103.42,72.0,M-SC,7.22,250.0,-0.99,0.58,56.13,OX40N,NTT,DURABLES
55,MASFIN,-0.23,-1.50,23.42,21.57,22603.0,-1470.0,96510.0,397.04,-15.09,56.0,H-SC,0.88,167.0,-0.07,0.63,15.04,XR,ATH,FINANCE

In [10]:
# top 5 today
df_tmp = df_portfolio_features.sort_values(by = 'Today P/L%', ascending=False)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
68,SATIN,4.82,49.10,1.84,51.83,7580.0,135647.0,411931.0,274.0,34.03,67.0,H-SC,43.34,159.0,17.90,2.70,100.67,XY24,NTT,FINANCE
21,DEN,4.25,-42.36,146.47,42.07,71313.0,-35776.0,48688.0,75.0,73.58,57.0,M-SC,6.18,235.0,-0.50,0.32,32.42,AR,NTT,ENTERTAINMENT
29,GREENPANEL,3.81,-47.25,171.35,43.14,165481.0,-86503.0,96575.0,537.0,116.41,56.0,M-SC,15.25,225.0,-0.52,0.63,16.01,XY24,NTT,MISC
49,JSWINFRA,3.76,16.58,-0.13,16.43,-336.0,36776.0,258550.0,342.0,-0.11,69.0,X-MC,14.91,61.0,-109.45,1.70,46.59,X40N,NTT,REALTY
0,5PAISA,2.19,-28.84,58.66,12.90,91205.0,-63016.0,155480.0,593.0,129.57,62.0,H-SC,8.64,170.0,-0.69,1.02,50.04,OX40N,NTT,FINANCE

In [11]:
# bottom 5 today
df_tmp = df_portfolio_features.sort_values(by = 'Today P/L%', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
16,CERA,-3.94,-20.70,56.22,23.89,78424.0,-36408.0,139495.0,9475.00,-23.39,46.0,H-SC,15.76,153.0,-0.46,0.92,35.60,OX40N,NTT,CERAMICS
77,TANLA,-3.76,-38.05,250.69,117.25,420492.0,-103027.0,167734.0,1922.32,-37.58,56.0,H-SC,0.99,147.0,-0.25,1.10,46.85,AR,ATH,IT
5,ATULAUTO,-3.17,-17.95,77.42,45.57,125218.0,-35394.0,161738.0,844.00,3500.00,48.0,M-SC,3.59,248.0,-0.28,1.06,24.46,XY24,NTT,AUTO
33,HCLTECH,-2.72,-22.90,57.61,21.51,107452.0,-55408.0,186516.0,1872.35,-18.94,57.0,X-LC,18.95,8.0,-0.52,1.22,14.87,X40,ATH,IT
15,CAMS,-2.69,0.79,23.50,24.48,59651.0,1980.0,253836.0,950.00,-3.31,47.0,X-SC,6.82,89.0,0.03,1.67,24.22,X40N,NTT,MISC

In [12]:
# top 5 to exit based on CumlRnk
df_tmp = df_portfolio_features[~df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])]
df_tmp = df_tmp[(df_tmp['Current P/L%'] > -1) & (df_tmp['Current P/L%'] < 1)].sort_values(by = 'CumlRnk', ascending=False)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
9,BANDHANBNK,-2.33,0.14,92.14,92.42,257035.0,402.0,278961.0,400.0,139.22,53.0,H-SC,20.58,174.0,0.00,1.83,53.67,XY24,NTT,BANKS
72,SIS,0.39,0.19,21.03,21.26,23395.0,212.0,111244.0,528.0,2656.48,60.0,H-SC,25.07,168.0,0.01,0.73,65.40,OX40N,NTT,MISC

In [13]:
# OX40N stocks to exit
df_tmp = df_portfolio_features[(df_portfolio_features['Symbol'].isin(list_ox40n))].sort_values(by = 'Current P/L%', ascending=False)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
25,FINCABLES,-1.86,31.08,58.62,107.91,113445.0,45882.0,193526.0,1641.55,17.71,42.0,M-SC,26.64,220.0,0.40,1.27,45.60,OX40N,ATH,CABLES
72,SIS,0.39,0.19,21.03,21.26,23395.0,212.0,111244.0,528.00,2656.48,60.0,H-SC,25.07,168.0,0.01,0.73,65.40,OX40N,NTT,MISC
83,TTKPRESTIG,0.56,-12.99,15.04,0.09,13188.0,-13092.0,87685.0,770.00,103.42,72.0,M-SC,7.22,250.0,-0.99,0.58,56.13,OX40N,NTT,DURABLES
16,CERA,-3.94,-20.70,56.22,23.89,78424.0,-36408.0,139495.0,9475.00,-23.39,46.0,H-SC,15.76,153.0,-0.46,0.92,35.60,OX40N,NTT,CERAMICS
69,SFL,-0.42,-20.94,60.16,26.63,124721.0,-54902.0,207316.0,1287.00,57.02,74.0,M-SC,23.03,242.0,-0.44,1.36,73.02,XY24,NTT,MISC

In [14]:
# top 5 to book for rotation
df_tmp = df_portfolio_features[(df_portfolio_features['Current P/L%'] > 20) ].sort_values(by = 'CumlRnk', ascending=False)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
25,FINCABLES,-1.86,31.08,58.62,107.91,113445.0,45882.0,193526.0,1641.55,17.71,42.0,M-SC,26.64,220.0,0.40,1.27,45.60,OX40N,ATH,CABLES
68,SATIN,4.82,49.10,1.84,51.83,7580.0,135647.0,411931.0,274.00,34.03,67.0,H-SC,43.34,159.0,17.90,2.70,100.67,XY24,NTT,FINANCE
60,QUESS,-0.25,21.81,42.76,73.90,55625.0,23293.0,130086.0,424.00,-34.44,74.0,X-SC,27.29,80.0,0.42,0.85,77.33,XY24,NTT,MISC

In [15]:
# top 5 to monitor for exit
df_tmp = df_portfolio_features[~df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])]
df_tmp = df_tmp[(df_tmp['Current P/L%'] > 0) ].sort_values(by = 'Dev%_PE', ascending=False)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
72,SIS,0.39,0.19,21.03,21.26,23395.0,212.0,111244.0,528.0,2656.48,60.0,H-SC,25.07,168.0,0.01,0.73,65.40,OX40N,NTT,MISC
9,BANDHANBNK,-2.33,0.14,92.14,92.42,257035.0,402.0,278961.0,400.0,139.22,53.0,H-SC,20.58,174.0,0.00,1.83,53.67,XY24,NTT,BANKS
75,SURYODAY,-0.77,8.28,13.62,23.03,26409.0,14831.0,193902.0,216.0,110.53,68.0,H-SC,20.89,166.0,0.56,1.27,63.26,XR,NTT,BANKS
74,STARHEALTH,-0.15,15.88,27.08,47.26,88220.0,44651.0,325774.0,761.0,82.89,69.0,H-SC,19.01,173.0,0.51,2.14,41.84,XY24,NTT,INSURANCE
68,SATIN,4.82,49.10,1.84,51.83,7580.0,135647.0,411931.0,274.0,34.03,67.0,H-SC,43.34,159.0,17.90,2.70,100.67,XY24,NTT,FINANCE

In [16]:
# top 5 to book for rotation from weak conviction
df_tmp = df_portfolio_features[~df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])]
df_tmp = df_tmp[~df_tmp['Criteria'].isin(['XY25','XY24','X40', 'X40N'])].sort_values(by = 'RRR Ind', ascending=False)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
91,ZYDUSLIFE,-1.62,19.38,13.61,35.63,34051.0,40620.0,250194.0,1286.17,4.05,58.0,H-MC,15.69,120.0,1.19,1.64,31.55,AR,ATH,PHARMA
73,SONACOMS,-0.66,14.89,20.71,38.69,24070.0,15067.0,116226.0,801.69,-8.99,68.0,M-MC,21.32,193.0,0.63,0.76,64.90,AR,ATH,AUTO
75,SURYODAY,-0.77,8.28,13.62,23.03,26409.0,14831.0,193902.0,216.00,110.53,68.0,H-SC,20.89,166.0,0.56,1.27,63.26,XR,NTT,BANKS
25,FINCABLES,-1.86,31.08,58.62,107.91,113445.0,45882.0,193526.0,1641.55,17.71,42.0,M-SC,26.64,220.0,0.40,1.27,45.60,OX40N,ATH,CABLES
72,SIS,0.39,0.19,21.03,21.26,23395.0,212.0,111244.0,528.00,2656.48,60.0,H-SC,25.07,168.0,0.01,0.73,65.40,OX40N,NTT,MISC

In [17]:
# top 5 to accumulate based on lowest RSI_14
df_tmp = df_portfolio_features[df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])].sort_values(by = 'RSI_14', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
87,VBL,0.37,-4.89,42.33,35.37,127160.0,-15440.0,300402.0,670.16,-16.09,33.0,X-LC,8.57,13.0,-0.12,1.97,23.47,X40N,ATH,FMCG
47,ITC,-0.14,-26.45,61.86,19.06,154779.0,-89958.0,250208.0,452.00,-59.56,34.0,X-LC,12.55,1.0,-0.58,1.64,0.81,X40,NTT,FMCG
23,DMART,-1.55,-5.48,37.12,29.60,87574.0,-13680.0,235920.0,5391.45,-20.32,35.0,X-LC,3.01,14.0,-0.16,1.55,7.84,X40N,ATH,FMCG
11,BERGEPAINT,-1.61,-9.84,38.99,25.32,90610.0,-25355.0,232394.0,680.00,-14.78,38.0,X-MC,2.96,68.0,-0.28,1.53,20.95,XY24,NTT,PAINTS
71,SIEMENS,-1.51,-7.47,35.65,25.51,61384.0,-13910.0,172185.0,4671.50,44.61,38.0,H-LC,10.14,51.0,-0.23,1.13,20.89,AR,ATH,ELECTRICAL

In [18]:
# top 5 to accumulate based on Spread and CumlRnk
df_tmp = df_portfolio_features[df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])]
df_tmp = df_tmp[(df_tmp['CumlRnk'] < 100)].sort_values(by = 'Spread%', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
17,CIPLA,0.52,17.14,13.91,33.43,24957.0,26255.0,179416.0,1648.14,-9.38,58.0,X-LC,2.29,18.0,1.05,1.18,22.48,X40N,ATH,PHARMA
11,BERGEPAINT,-1.61,-9.84,38.99,25.32,90610.0,-25355.0,232394.0,680.00,-14.78,38.0,X-MC,2.96,68.0,-0.28,1.53,20.95,XY24,NTT,PAINTS
19,COLPAL,-0.46,-23.46,82.74,39.86,166779.0,-61795.0,201570.0,3683.41,-7.42,46.0,X-MC,3.01,62.0,-0.37,1.32,14.02,XY25,ATH,FMCG
23,DMART,-1.55,-5.48,37.12,29.60,87574.0,-13680.0,235920.0,5391.45,-20.32,35.0,X-LC,3.01,14.0,-0.16,1.55,7.84,X40N,ATH,FMCG
39,ICICIGI,-1.49,-6.74,27.48,18.89,51284.0,-13485.0,186624.0,2244.41,-21.55,45.0,X-MC,4.05,66.0,-0.26,1.22,4.63,X40,ATH,INSURANCE

In [19]:
# top 5 to accumulate based on lowest Gained%
df_tmp = df_portfolio_features[df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])].sort_values(by = 'Gained%', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
47,ITC,-0.14,-26.45,61.86,19.06,154779.0,-89958.0,250208.0,452.00,-59.56,34.0,X-LC,12.55,1.0,-0.58,1.64,0.81,X40,NTT,FMCG
58,PGHH,-0.39,-33.27,97.83,32.01,139388.0,-71040.0,142480.0,17616.87,-54.91,42.0,X-MC,20.45,57.0,-0.51,0.94,1.04,X40,ATH,FMCG
65,RELIANCE,0.13,-16.64,50.32,25.30,84296.0,-33444.0,167519.0,1952.00,-18.88,47.0,X-LC,7.25,21.0,-0.40,1.10,3.16,XY25,BTT,REFINERIES
35,HDFCLIFE,-1.66,-7.77,43.89,32.71,60637.0,-11644.0,138156.0,811.41,-28.00,44.0,X-LC,14.93,31.0,-0.19,0.91,3.79,X40,ATH,INSURANCE
32,HAVELLS,-0.48,-24.88,74.96,31.42,184680.0,-81619.0,246372.0,2052.62,-29.37,46.0,X-MC,11.10,63.0,-0.44,1.62,3.91,X40,ATH,ELECTRICAL

In [20]:
# top 5 to accumulate based on lowest CurrAlloc%
df_tmp = df_portfolio_features[df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])].sort_values(by = 'CurrAlloc%', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
10,BATAINDIA,-1.24,-55.68,205.09,35.20,116944.0,-71649.0,57021.0,2096.00,-25.20,48.0,X-SC,18.87,91.0,-0.61,0.37,13.09,X40,NTT,FOOTWEAR
64,RELAXO,-0.38,-49.08,199.08,52.31,147164.0,-71238.0,73922.0,1176.00,-45.79,60.0,X-SC,12.18,92.0,-0.48,0.49,65.28,X40N,NTT,FOOTWEAR
60,QUESS,-0.25,21.81,42.76,73.90,55625.0,23293.0,130086.0,424.00,-34.44,74.0,X-SC,27.29,80.0,0.42,0.85,77.33,XY24,NTT,MISC
35,HDFCLIFE,-1.66,-7.77,43.89,32.71,60637.0,-11644.0,138156.0,811.41,-28.00,44.0,X-LC,14.93,31.0,-0.19,0.91,3.79,X40,ATH,INSURANCE
53,M&M,-2.05,0.44,21.56,22.10,30033.0,617.0,139298.0,3762.88,-14.78,50.0,X-LC,7.78,25.0,0.02,0.91,6.72,X40N,ATH,AUTO

In [21]:
# top 5 to accumulate based on CumlRnk
df_tmp = df_portfolio_features.sort_values(by = 'CumlRnk', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
47,ITC,-0.14,-26.45,61.86,19.06,154779.0,-89958.0,250208.0,452.00,-59.56,34.0,X-LC,12.55,1.0,-0.58,1.64,0.81,X40,NTT,FMCG
79,TCS,0.51,-35.63,94.01,24.88,280332.0,-165079.0,298194.0,4253.91,-45.59,56.0,X-LC,21.44,2.0,-0.59,1.96,10.59,X40,ATH,IT
45,INFY,-0.71,-25.47,80.12,34.24,186833.0,-79696.0,233192.0,1972.00,-41.22,53.0,X-LC,21.38,3.0,-0.43,1.53,11.11,X40,NTT,IT
81,TMPV,-1.83,-23.52,78.57,36.58,213836.0,-83681.0,272160.0,600.00,-83.62,39.0,X-LC,8.24,4.0,-0.39,1.79,14.38,XY24,NTT,AUTO
59,PIDILITIND,-1.86,9.94,7.67,18.37,11898.0,14020.0,155130.0,1670.26,-22.95,47.0,X-LC,8.39,5.0,1.18,1.02,21.80,X40,ATH,CHEMICALS

In [22]:
# top 5 for average up
df_tmp = df_portfolio_features[(df_portfolio_features['Dev%_200'] > 5)].sort_values(by = 'CurrAlloc%', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
44,INDUSINDBK,-1.30,-26.19,80.05,32.89,45617.0,-20220.0,56986.0,1800.00,-368.21,62.0,L-MC,10.33,258.0,-0.44,0.37,40.49,XR,NTT,BANKS
64,RELAXO,-0.38,-49.08,199.08,52.31,147164.0,-71238.0,73922.0,1176.00,-45.79,60.0,X-SC,12.18,92.0,-0.48,0.49,65.28,X40N,NTT,FOOTWEAR
3,ALKYLAMINE,-1.55,-20.19,141.24,92.54,113814.0,-20381.0,80582.0,4520.85,-14.57,57.0,H-SC,10.84,142.0,-0.18,0.53,53.02,SR,ATH,CHEMICALS
83,TTKPRESTIG,0.56,-12.99,15.04,0.09,13188.0,-13092.0,87685.0,770.00,103.42,72.0,M-SC,7.22,250.0,-0.99,0.58,56.13,OX40N,NTT,DURABLES
72,SIS,0.39,0.19,21.03,21.26,23395.0,212.0,111244.0,528.00,2656.48,60.0,H-SC,25.07,168.0,0.01,0.73,65.40,OX40N,NTT,MISC

In [23]:
# top 5 RSP
df_tmp = df_portfolio_features.sort_values(by = 'RSP', ascending=False)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
83,TTKPRESTIG,0.56,-12.99,15.04,0.09,13188.0,-13092.0,87685.0,770.0,103.42,72.0,M-SC,7.22,250.0,-0.99,0.58,56.13,OX40N,NTT,DURABLES
60,QUESS,-0.25,21.81,42.76,73.90,55625.0,23293.0,130086.0,424.0,-34.44,74.0,X-SC,27.29,80.0,0.42,0.85,77.33,XY24,NTT,MISC
0,5PAISA,2.19,-28.84,58.66,12.90,91205.0,-63016.0,155480.0,593.0,129.57,62.0,H-SC,8.64,170.0,-0.69,1.02,50.04,OX40N,NTT,FINANCE
49,JSWINFRA,3.76,16.58,-0.13,16.43,-336.0,36776.0,258550.0,342.0,-0.11,69.0,X-MC,14.91,61.0,-109.45,1.70,46.59,X40N,NTT,REALTY
68,SATIN,4.82,49.10,1.84,51.83,7580.0,135647.0,411931.0,274.0,34.03,67.0,H-SC,43.34,159.0,17.90,2.70,100.67,XY24,NTT,FINANCE

In [24]:
# Top N allocation
df_tmp = df_portfolio_features.sort_values(by = 'CurrAlloc%', ascending=False)
top_n_values = [10, 25, 50]

sum_df = pd.DataFrame({
    'Top_N': top_n_values,
    'Sum_Alloc%': [df_tmp['CurrAlloc%'].head(n).sum() for n in top_n_values]
})

sum_df

   Top_N  Sum_Alloc%
0     10       19.36
1     25       42.64
2     50       72.64

In [25]:
# market-cap-wise allocation
df_tmp = df_portfolio_features[cols]
df_tmp.groupby(df_tmp['Conviction'].str[-2:])['CurrAlloc%'].sum().sort_values(ascending=False)

Conviction
SC    43.96
LC    30.01
MC    26.00
Name: CurrAlloc%, dtype: float64

In [26]:
# criteria-wise allocation
df_portfolio_features.groupby('Criteria')['CurrAlloc%'].sum().sort_values(ascending=False)

Criteria
XY24     27.94
X40      24.63
X40N     17.31
XR        8.86
OX40N     7.09
AR        6.83
XY25      6.39
SR        0.92
Name: CurrAlloc%, dtype: float64

In [27]:
# conviction-wise allocation
df_portfolio_features.groupby('Conviction')['CurrAlloc%'].sum().sort_values(ascending=False)

Conviction
X-LC    28.07
H-SC    23.22
X-MC    20.91
M-SC    10.11
X-SC    10.07
H-MC     2.70
M-MC     2.02
H-LC     1.13
M-LC     0.81
L-SC     0.56
L-MC     0.37
Name: CurrAlloc%, dtype: float64

In [28]:
# sector-wise stats
df_tmp = df_portfolio_features.groupby('Category')[['CurrAlloc%', 'Current', 'Current P/L', 'FTT Amt']].sum().sort_values(by=['Current', 'Current P/L'], ascending=False)
df_tmp['Current P/L%'] = round(df_tmp['Current P/L'] * 100 / df_tmp['Current'], 2)
df_tmp['FTT%'] = round(df_tmp['FTT Amt'] * 100 / df_tmp['Current'], 2)
cols = ['CurrAlloc%', 'Current P/L%', 'FTT%']
df_tmp[cols].sort_values(by=['CurrAlloc%'], ascending=False)

               CurrAlloc%  Current P/L%    FTT%
Category
FMCG                14.20        -22.33   65.24
FINANCE             11.40         -6.18   52.19
IT                  10.04        -47.14  120.50
MISC                 7.28        -20.75   72.56
AUTO                 6.56         -9.45   50.26
BANKS                5.89         -1.07   47.80
INSURANCE            5.36         -1.47   35.70
PAINTS               5.31        -21.85   42.63
PHARMA               5.18          6.15   22.90
ELECTRICAL           4.00        -16.01   56.95
CHEMICALS            2.16        -23.27   96.40
HEALTHCARE           2.08        -12.74   42.17
APPARELS             1.83          3.92   28.35
AC                   1.80        -16.61   48.23
FOOTWEAR             1.71        -69.78  137.85
REALTY               1.70         14.22   -0.13
DURABLES             1.67        -52.28   89.33
BREWERIES            1.55          0.92   19.66
TRAVEL               1.51        -94.51  191.91
CERAMICS             1.38        -46.30   90.75
CABLES               1.27         23.71   58.62
ENGINEERING          1.25        -27.13   85.28
REFINERIES           1.10        -19.96   50.32
JEWELLERY            1.09        -92.13  158.89
CEMENT               1.07        -63.98  186.66
ENTERTAINMENT        0.77        -64.57  162.72
TEXTILES             0.41        -47.11   89.05
HOTELS               0.40        -84.81  150.00

In [29]:
# money to be made criteria-wise
df_portfolio_features.groupby('Criteria')['FTT Amt'].agg(['sum', 'count']).sort_values(by='sum', ascending=False)

                sum  count
Criteria
XY24      3339872.0     21
X40       1923538.0     19
XR        1323259.0     13
AR        1134273.0      9
X40N      1084338.0     13
OX40N      713100.0     10
XY25       462705.0      5
SR         278266.0      2

In [30]:
# money to be made conviction-wise
df_portfolio_features.groupby('Conviction')['FTT Amt'].agg(['sum', 'count']).sort_values(by='sum', ascending=False)

                  sum  count
Conviction
H-SC        3233121.0     24
X-LC        2003672.0     21
X-MC        1533669.0     15
M-SC        1377338.0     14
X-SC        1267823.0      9
H-MC         285597.0      2
L-SC         205194.0      2
M-LC         167968.0      1
M-MC          77968.0      2
H-LC          61384.0      1
L-MC          45617.0      1

In [31]:
# money to be made criteria and conviction-wise
df_portfolio_features.groupby(['Conviction', 'Criteria'])['FTT Amt'].agg(['sum', 'count']).sort_values(by='sum', ascending=False)

                           sum  count
Conviction Criteria
X-LC       X40       1046084.0     10
H-SC       AR         943455.0      5
           XY24       931783.0      6
M-SC       XY24       808971.0      6
H-SC       XR         784031.0      7
X-SC       XY24       750092.0      4
X-MC       X40        667504.0      7
X-LC       X40N       392046.0      6
X-MC       X40N       384511.0      4
X-LC       XY24       361437.0      2
X-SC       X40N       307781.0      3
M-SC       OX40N      304480.0      5
H-SC       OX40N      295586.0      4
           SR         278266.0      2
H-MC       XY24       251546.0      1
X-MC       XY25       245611.0      2
           XY24       236043.0      2
X-SC       X40        209950.0      2
M-SC       XR         192574.0      2
M-LC       XR         167968.0      1
X-LC       XY25       163196.0      2
L-SC       OX40N      113034.0      1
           XR          92160.0      1
M-SC       AR          71313.0      1
H-LC       AR          61384.0      1
M-MC       XY25        53898.0      1
L-MC       XR          45617.0      1
X-LC       XR          40909.0      1
H-MC       AR          34051.0      1
M-MC       AR          24070.0      1

In [32]:
# notebook execution time

end_time = time.time()
execution_time = round(end_time - start_time, 0)
print(f"Notebook execution time: {execution_time} seconds")

Notebook execution time: 51.0 seconds