<a href="https://colab.research.google.com/github/ankit-rathi/Quantvesting_v2/blob/main/myStocks_Portfolio_Analysis.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
'''
!pip install pandas==2.2.2 -qq
!pip install pyxirr -qq
!pip install ta -qq
!pip install yfinance==0.2.59 -qq
'''

'\n!pip install pandas==2.2.2 -qq\n!pip install pyxirr -qq\n!pip install ta -qq\n!pip install yfinance==0.2.59 -qq\n'

In [2]:
# import libraries

import numpy as np
import pandas as pd
import datetime
import warnings
warnings.filterwarnings('ignore')
import yfinance as yfin
import ta
import matplotlib.pyplot as plt
import requests

In [3]:
# notebook start time
import time
import datetime
import pytz

start_time = time.time()

# function to print date timestamp
def print_date_time():
  tz_NY = pytz.timezone('Asia/Kolkata')
  datetime_NY = datetime.datetime.now(tz_NY)
  print("Run date time (IST):", datetime_NY.strftime("%Y-%m-%d %H:%M:%S"))

In [4]:
# function to get booked and reserved amount
def get_amt():
  # fetch the JSON data from the URL
  url = "https://raw.githubusercontent.com/ankit-rathi/Tradevesting_v1/main/data/myPortfolioAmts.json"
  response = requests.get(url)
  pf_amts = response.json()  # parse the JSON data

  # extract values from the JSON
  py_booked_amt_dm = pf_amts["py_booked_amt_dm"]
  py_booked_amt_sv = pf_amts["py_booked_amt_sv"]
  cy_booked_amt_dm = pf_amts["cy_booked_amt_dm"]
  cy_booked_amt_sv = pf_amts["cy_booked_amt_sv"]
  reserve_amt_dm = pf_amts["reserve_amt_dm"]
  reserve_amt_sv = pf_amts["reserve_amt_sv"]

  # perform calculations
  py_booked_amt = py_booked_amt_dm + py_booked_amt_sv
  cy_booked_amt = cy_booked_amt_dm + cy_booked_amt_sv
  reserve_amt = reserve_amt_dm + reserve_amt_sv
  total_booked_amt = py_booked_amt + cy_booked_amt

  return total_booked_amt, reserve_amt, cy_booked_amt, py_booked_amt

gen_output = 0

In [5]:
# function to format the amount
def format_amt(number):
    abs_number = abs(number)

    if abs_number >= 1_00_00_000:  # Crores
        formatted_amt = f"{number / 1_00_00_000:.2f} C"
    elif abs_number >= 1_00_000:  # Lakhs
        formatted_amt = f"{number / 1_00_000:.2f} L"
    elif abs_number >= 1_000:  # Thousands
        formatted_amt = f"{number / 1_000:.2f} K"
    else:
        formatted_amt = f"{number:.2f}"

    return formatted_amt

# function to set start and end date
def get_start_end_date():
  start_date = (datetime.date.today() + datetime.timedelta(days=-365)).strftime('%Y-%m-%d')
  end_date = (datetime.date.today() + datetime.timedelta(days=1)).strftime('%Y-%m-%d')
  return start_date, end_date

# function to fetch my portfolio csv
def get_mypfs_df():
  mypfs_df = pd.read_csv('https://raw.githubusercontent.com/ankit-rathi/Tradevesting_v1/main/data/myPortfolioStocks.csv')
  return mypfs_df

# function to fetch my prospects csv
def get_mypps_df():
  mypps_df = pd.read_csv('https://raw.githubusercontent.com/ankit-rathi/Tradevesting_v1/main/data/myProspectsScrips.csv')
  return mypps_df

# function to fetch screener data
def get_myscreen_df():
  myscreen_df = pd.read_csv('https://raw.githubusercontent.com/ankit-rathi/Tradevesting_v1/main/data/myScreenerDB.csv')
  return myscreen_df

# function to fetch momentum data
def get_myinvmt_df():
  myinvmt_df = pd.read_csv('https://raw.githubusercontent.com/ankit-rathi/Tradevesting_v1/main/data/myInvestments.csv')
  return myinvmt_df

# function to get the stock ids
def get_stock_ids(df_pf):
  stock_n100 = df_pf['Symbol'].unique()

  exclude = ['CADILAHC','MMTC', 'MASFIN']

  stock_ids = df_pf[~df_pf['Symbol'].isin(exclude) ]['Symbol'].unique()

  #mypf = mypf[mypf.Forecast.notnull()]
  #stock_ids = mypf['Symbol'].unique()

  #stock_ids.sort()
  return stock_ids

# get features from screener data
def get_screener_features():
  myscreen_df = get_myscreen_df()
  cols = ['Symbol', 'EPS', 'MedPE', 'ROCE%', 'ROE%', 'CapType']
  return myscreen_df[cols]

# get relative strength
def get_relative_strength(stock_list):

    # Dictionary to store stock tickers and their corresponding percentage price change
    stock_changes = {}

    # Loop through each stock and fetch its price data
    for stock in stock_list:
        try:
            # Download the stock data for the given date range
            stock_data = yfin.Ticker(stock + '.NS').history(period='1mo', interval='1d')[map(str.title, ['open', 'close', 'low', 'high', 'volume'])]

            # Calculate the percentage change for the stock
            if len(stock_data) > 0:
                start_price = stock_data['Close'].iloc[0]
                end_price = stock_data['Close'].iloc[-1]
                percent_change = round(((end_price - start_price) / start_price) * 100, 2)
                stock_changes[stock] = percent_change
            else:
                stock_changes[stock] = np.nan  # If no data is available, set to NaN

        except Exception as e:
            print(f"Error fetching data for {stock}: {e}")
            stock_changes[stock] = np.nan

    # Create a DataFrame with stock tickers and their percentage changes
    df = pd.DataFrame(list(stock_changes.items()), columns=['Symbol', 'Percent_Change'])

    # Drop any stocks with missing data (NaN values)
    df = df.dropna()

    # Calculate the percentile rank based on percentage change
    df['RSP'] = round(df['Percent_Change'].rank(pct=True) * 100, 2)
    cols = ['Symbol', 'RSP']
    df = df[cols]
    # Sort by percentile rank (optional)
    df = df.sort_values(by='RSP', ascending=False).reset_index(drop=True)

    return df

In [6]:
# function to get stock technicals
def stock_prec_dev(stock_symbol):
    #stock_symbol = 'ULTRACEMCO.NS'
    short_window = 20
    mid_window = 50
    long_window = 200
    moving_avg = 'SMA'

    start = datetime.datetime(*map(int, start_date.split('-')))
    end = datetime.datetime(*map(int, end_date.split('-')))

    stock_df = yfin.Ticker(stock_symbol + '.NS').history(period='max', interval='1d')[map(str.title, ['open', 'close', 'low', 'high', 'volume'])]

    stock_df['Max'] = round(max(stock_df['Close']),2)
    stock_df = stock_df[(stock_df.index <= end_date) & (stock_df.index >= start_date)]
    stock_df['200_SMA'] = round(stock_df['Close'].rolling(window = 200, min_periods = 1).mean(),0)
    stock_df['Dev%_200'] = round((stock_df['Close'] - stock_df['200_SMA'])*100/stock_df['200_SMA'],2)
    stock_df.dropna(axis = 0, inplace = True) # remove any null rows

    stock_df['20_SMA'] = stock_df['Close'].rolling(window=20).mean()
    stock_df['50_SMA'] = stock_df['Close'].rolling(window=50).mean()
    stock_df['Symbol'] = stock_symbol

    stock_df['Close'] = round(stock_df['Close'],2)
    stock_df['Min'] = round(min(stock_df['Close']),2)
    stock_df['RSI_14'] = ta.momentum.RSIIndicator(close=stock_df['Close'], window=14).rsi()
    stock_df['RSI_14'] = round(stock_df['RSI_14'],0)
    stock_df['Prev_Close'] = stock_df['Close'].shift(1)
    stock_df.drop(['Open', 'Low', 'High', 'Volume'], axis=1, inplace=True)
    stock_df = stock_df.tail(1)

    max_SMA = max(stock_df['20_SMA'].item(), stock_df['50_SMA'].item(), stock_df['200_SMA'].item())
    min_SMA = min(stock_df['20_SMA'].item(), stock_df['50_SMA'].item(), stock_df['200_SMA'].item())
    ABS_Spread = max_SMA - min_SMA
    stock_df['Spread%'] = round((ABS_Spread / stock_df['200_SMA'].item()) * 100,2)

    return stock_df

# function to compute stock attributes
def get_common_features(stock_ids, df_mypf):

  df_prec_dev = pd.DataFrame()
  df_tmp = get_screener_features()
  df_rs = get_relative_strength(stock_ids)

  for stock_id in stock_ids:
      tmp = stock_prec_dev(stock_id)
      tmp = tmp.reset_index()
      df_prec_dev = pd.concat([df_prec_dev, tmp], ignore_index = True)
  df_prec_dev = pd.merge(df_prec_dev, df_mypf, on= 'Symbol')
  df_prec_dev = pd.merge(df_prec_dev, df_tmp, on= 'Symbol', how='left')
  df_prec_dev = pd.merge(df_prec_dev, df_rs, on= 'Symbol', how='left')
  #print(df_prec_dev.columns)
  df_prec_dev['Curr_PE'] = round(df_prec_dev['Close']/df_prec_dev['EPS'],1)
  df_prec_dev['Dev%_PE'] = round((df_prec_dev['Curr_PE'] - df_prec_dev['MedPE'])*100/df_prec_dev['MedPE'],2)
  df_prec_dev['Conviction'] = df_prec_dev['Conviction'] + '-' + df_prec_dev['CapType']
  return df_prec_dev

# function to arrange stock features
def arrange_features(df_stocks, common_cols, diff_cols):
  df_stocks_common = df_stocks[common_cols].drop_duplicates()
  df_stocks_diff = df_stocks[diff_cols]
  df_stocks_diff['Investment'] = df_stocks_diff['AvgCost'] * df_stocks_diff['Shares']
  df_stocks_diff = df_stocks_diff.groupby(['Symbol'])[['Shares', 'Investment']].aggregate(['sum']).reset_index()
  df_stocks_diff.columns = ['Symbol', 'Shares', 'Investment']
  df_stocks_diff['AvgCost'] = round(df_stocks_diff['Investment']/df_stocks_diff['Shares'],2)
  df_stocks = pd.merge(df_stocks_diff, df_stocks_common, on='Symbol')
  return df_stocks

# plot fact distribution across dimension
def plot_pie_chart(df, dimension, fact):
  # grouping the data by category and calculating the sum of fact for each type
  grouped_data = df.groupby(dimension)[fact].sum()

  # sorting the grouped data in descending order
  grouped_data = grouped_data.sort_values(ascending=False)

  # creating a pie chart
  grouped_data.plot.pie(autopct='%1.1f%%', startangle=90, figsize=(6, 6))

  # adding a title and displaying the plot
  plt.title(f'{dimension} {fact} Distribution')
  plt.ylabel('')  # To hide the y-label
  plt.show()

In [7]:
# function to get portfolio features

def get_portfolio_features(df_common_features):

  print_date_time()
  print('-------------------')

  #df_common_features["Target"] = df_common_features["Target"].fillna(df_common_features["Max"])
  df_common_features['NTT'] = np.where(df_common_features['Strategy']== 'NTT', df_common_features["Target"], df_common_features['Max'])
  df_common_features['LTT'] = np.where(df_common_features['Strategy']== 'BTT', df_common_features["Target"], df_common_features['Max'])
  df_common_features['BOL'] = df_common_features['Min']

  tmp_df = df_common_features[df_common_features['Symbol'].isin(mypf_df[mypf_df['InPortfolio'] != 'NA'].Symbol.values)]
  print('qualified stocks: '+str(len(tmp_df['Symbol'].unique())))
  tmp_df1 = tmp_df[tmp_df['LatestQtr'] == 1]
  print('with latest results: '+str(len(tmp_df1['Symbol'].unique())))
  tmp_df1 = tmp_df1[tmp_df1['StarStock'] == 1]
  print('still star stocks: '+str(len(tmp_df1['Symbol'].unique())))
  tmp_df['Investment'] = tmp_df['AvgCost'] * tmp_df['Shares']
  tmp_df['Current'] = round(tmp_df['Close'] * tmp_df['Shares'],0)
  tmp_df['Previous'] = tmp_df['Prev_Close'] * tmp_df['Shares']
  tmp_df['EstimatedST'] = tmp_df['NTT'] * tmp_df['Shares']
  tmp_df['EstimatedLT'] = tmp_df['LTT'] * tmp_df['Shares']
  tmp_df['Current P/L'] = round((tmp_df['Current'] - tmp_df['Investment']),0)
  tmp_df['Today P/L%'] = round((tmp_df['Current'] - tmp_df['Previous'])*100/tmp_df['Previous'],2)
  tmp_df['Current P/L%'] = round((tmp_df['Current'] - tmp_df['Investment'])*100/tmp_df['Investment'],2)
  tmp_df['EstimatedST P/L%'] = round((tmp_df['EstimatedST'] - tmp_df['Investment'])*100/tmp_df['Investment'],2)
  tmp_df['EstimatedLT P/L%'] = round((tmp_df['EstimatedLT'] - tmp_df['Investment'])*100/tmp_df['Investment'],2)
  tmp_df['NTT%'] = round((tmp_df['NTT'] - tmp_df['Close'])*100/tmp_df['Close'],2)
  tmp_df['LTT%'] = round((tmp_df['LTT'] - tmp_df['Close'])*100/tmp_df['Close'],2)
  tmp_df['Gained%'] = round((tmp_df['Close'] - tmp_df['BOL'])*100/tmp_df['BOL'],2)
  investment = round(sum(tmp_df['AvgCost']*tmp_df['Shares']),0)
  current = round(sum(tmp_df['Close']*tmp_df['Shares']),0)
  tmp_df['InitAlloc%'] = round(tmp_df['Investment']*100/investment,2)
  tmp_df['CurrAlloc%'] = round(tmp_df['Current']*100/current,2)
  tmp_df['FTT'] = tmp_df['LTT']
  tmp_df.loc[tmp_df['Strategy'] == 'NTT', 'FTT'] = tmp_df['NTT']
  tmp_df['FTT%'] = tmp_df['LTT%']
  tmp_df.loc[tmp_df['Strategy'] == 'NTT', 'FTT%'] = tmp_df['NTT%']
  tmp_df['FTT Amt'] = round(tmp_df['FTT%'] * tmp_df['Current']/100,0)
  tmp_df['OTT%'] = round((tmp_df['FTT'] - tmp_df['AvgCost'])*100/tmp_df['AvgCost'],2)
  tmp_df['RRR Ind'] = round(tmp_df['Current P/L']/tmp_df['FTT Amt'],2)
  tmp_df['Risk Ind'] = round(tmp_df['Current P/L%']*tmp_df['CurrAlloc%'],0)

  return tmp_df

# function to print portfolio features
def print_portfolio_stats(df_portfolio_features, myinvmt_df):
  from pyxirr import xirr

  total_booked_amt, reserve_amt, cy_booked_amt, py_booked_amt = get_amt()

  dates = myinvmt_df['Date'].values
  dates = np.append(dates, datetime.date.today().strftime('%d-%b-%y'))
  investment = myinvmt_df['Investment'].values
  dates= pd.to_datetime(dates)

  current = round(sum(df_portfolio_features['Close']*df_portfolio_features['Shares']),0) + reserve_amt
  investment_xirr = np.append(investment, current)
  cagr = round(xirr(pd.DataFrame({"dates": dates, "amounts": investment_xirr}))*100,2)

  investment = -sum(investment)
  invested = round(sum(df_portfolio_features['AvgCost']*df_portfolio_features['Shares']),0) + reserve_amt
  previous = round(sum(df_portfolio_features['Prev_Close']*df_portfolio_features['Shares']),0) + reserve_amt
  cy_invested = investment + py_booked_amt

  today_pnl_amount = current-previous
  today_pnl_percentage = round((current-previous)*100/previous,2)

  curr_pnl_amount = current-invested
  curr_pnl_percentage = round((curr_pnl_amount)*100/(cy_invested),2)

  cy_pnl_amount = cy_booked_amt + curr_pnl_amount
  cy_pnl_percentage = round((cy_pnl_amount)*100/cy_invested,2)

  overall_pnl_amount = total_booked_amt + curr_pnl_amount
  overall_pnl_percentage = round((overall_pnl_amount)*100/investment,2)

  estimate_st = round(sum(df_portfolio_features['FTT']*df_portfolio_features['Shares']),0)  + reserve_amt
  est_st_pnl_amount = estimate_st-current
  est_st_pnl_percentage = round((est_st_pnl_amount)*100/current,2)

  estimate_lt = round(sum(df_portfolio_features['LTT']*df_portfolio_features['Shares']),0)  + reserve_amt
  est_lt_pnl_amount = estimate_lt-current
  est_lt_pnl_percentage = round((est_lt_pnl_amount)*100/current,2)

  total_profit = round(sum(df_portfolio_features[df_portfolio_features['Current P/L%'] > 0]['Current']) - sum(df_portfolio_features[df_portfolio_features['Current P/L%'] > 0]['Investment']),0)
  total_loss = round(sum(df_portfolio_features[df_portfolio_features['Current P/L%'] < 0]['Current']) - sum(df_portfolio_features[df_portfolio_features['Current P/L%'] < 0]['Investment']),0)

  cy_booked_percentage = round((cy_booked_amt)*100/current,2)
  py_booked_percentage = round((py_booked_amt)*100/investment,2)
  total_booked_percentage = round((total_booked_amt)*100/investment,2)

  print('-------------------')
  print('Initial Investment: ', format_amt(investment))
  print('CY Investment: ', format_amt(cy_invested))
  print('Reserve: ', format_amt(reserve_amt))
  print('Current: ',  format_amt(current))
  print('-------------------')
  print('Today PnL: '+ '{} ({}%)'.format(format_amt(today_pnl_amount), today_pnl_percentage))
  print('Current PnL: '+ '{} ({}%)'.format(format_amt(curr_pnl_amount), curr_pnl_percentage))
  print('CY Booked + Current PnL: '+ '{} ({}%)'.format(format_amt(cy_pnl_amount), cy_pnl_percentage))
  print('-------------------')
  print('Total profit: ', format_amt(total_profit))
  print('Total loss: ', format_amt(total_loss))
  print('-------------------')
  print('Total Booked + Current PnL: '+ '{} ({}%)'.format(format_amt(overall_pnl_amount), overall_pnl_percentage))
  print('Total Booked PnL: '+ '{} ({}%)'.format(format_amt(total_booked_amt), total_booked_percentage))
  print('Curr Year Booked PnL: '+ '{} ({}%)'.format(format_amt(cy_booked_amt), cy_booked_percentage))
  print('Prev Year Booked PnL: '+ '{} ({}%)'.format(format_amt(py_booked_amt), py_booked_percentage))
  print('===================')
  print('Est FTT: ',  format_amt(estimate_st))
  print('Est FTT PnL: '+ '{} ({}%)'.format(format_amt(est_st_pnl_amount), est_st_pnl_percentage))

  print('===================')
  print('Deployed: ', format_amt(investment))

  print('Current: ', format_amt(current))

  print('CAGR/XIRR %: '+'{}%'.format(cagr))

In [8]:
# get start and end date
start_date, end_date = get_start_end_date()

# get portfolio and prospects data
mypfs_df = get_mypfs_df()
mypps_df = get_mypps_df()
myinvmt_df = get_myinvmt_df()

# merge above datasets
mypf_df = pd.merge(mypfs_df, mypps_df, on="Symbol")

# seggregate dm and sv portfolio
dm_pf = mypf_df[mypf_df['InPortfolio'] == 'DM']
sv_pf = mypf_df[mypf_df['InPortfolio'] == 'SV']

# build portfolio stock dataframe
dm_stocks = get_stock_ids(dm_pf)
sv_stocks = get_stock_ids(sv_pf)
df_stocks = pd.concat([dm_pf,sv_pf], ignore_index = True)

# arrange common and diff stock features
common_cols = ['Symbol', 'Target', 'Criteria', 'Strategy', 'CumlRnk', 'LatestQtr', 'StarStock', 'Conviction', 'Category', 'InFolio', 'XIRR', 'MBQ']
diff_cols = ['Symbol', 'AvgCost', 'Shares']
df_stocks = arrange_features(df_stocks, common_cols, diff_cols)

# get common features
stock_ids = df_stocks['Symbol'].values
df_common_features = get_common_features(stock_ids, df_stocks)

df_common_features.reset_index(drop=True, inplace=True)
df_common_features.drop(['Date'], axis=1, inplace=True)
# get and print portfolio features
df_portfolio_features = get_portfolio_features(df_common_features)

print_portfolio_stats(df_portfolio_features, myinvmt_df)

df = df_portfolio_features
#plot_pie_chart(df, 'CapType', 'Current')
list_ox40n = list(df[df['MBQ'].str.contains('OX40N', na=False)]['Symbol'].values)

Run date time (IST): 2026-07-03 17:13:01
-------------------
qualified stocks: 92
with latest results: 31
still star stocks: 20
-------------------
Initial Investment:  1.40 C
CY Investment:  1.82 C
Reserve:  1.49 K
Current:  1.53 C
-------------------
Today PnL: 8.95 K (0.06%)
Current PnL: -29.80 L (-16.34%)
CY Booked + Current PnL: -27.72 L (-15.2%)
-------------------
Total profit:  4.86 L
Total loss:  -34.65 L
-------------------
Total Booked + Current PnL: 15.15 L (10.86%)
Total Booked PnL: 44.95 L (32.22%)
Curr Year Booked PnL: 2.08 L (1.36%)
Prev Year Booked PnL: 42.87 L (30.73%)
===================
Est FTT:  2.55 C
Est FTT PnL: 1.02 C (66.25%)
===================
Deployed:  1.40 C
Current:  1.53 C
CAGR/XIRR %: 4.36%

In [9]:
# top 5 near their targets
cols = ['Symbol', 'Today P/L%', 'Current P/L%', 'FTT%', 'OTT%', 'FTT Amt', 'Current P/L', 'Current', 'FTT', 'Dev%_PE', 'RSI_14','Conviction', 'Spread%',  'CumlRnk', 'RRR Ind', 'CurrAlloc%', 'Gained%', 'Criteria', 'Strategy', 'Category']
df_tmp = df_portfolio_features[~df_portfolio_features['Symbol'].isin(['ENRIN','BLUSPRING','DIGITIDE'])]
df_tmp = df_tmp.sort_values(by = 'FTT Amt', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
59,PIDILITIND,-0.46,13.24,4.52,18.37,7223.0,18690.0,159800.0,1670.26,-20.71,67.0,X-LC,6.81,5.0,2.59,1.04,25.47,X40,ATH,CHEMICALS
49,JSWINFRA,-0.44,11.00,4.89,16.43,12038.0,24394.0,246168.0,342.00,-4.83,65.0,X-MC,10.05,61.0,2.03,1.61,39.57,X40N,NTT,REALTY
83,TTKPRESTIG,-3.36,-18.85,23.35,0.09,19095.0,-19000.0,81777.0,770.00,89.75,69.0,M-SC,6.03,250.0,-1.00,0.53,45.61,OX40N,NTT,DURABLES
56,MEDANTA,0.40,15.54,10.02,27.12,20436.0,27439.0,203956.0,1486.00,11.92,74.0,X-SC,6.83,87.0,1.34,1.33,40.54,XY24,NTT,HEALTHCARE
51,KOTAKBANK,-0.64,6.01,14.24,21.11,20904.0,8326.0,146798.0,453.24,-8.97,51.0,X-LC,4.31,12.0,0.40,0.96,12.27,X40,ATH,BANKS

In [10]:
# top 5 today
df_tmp = df_portfolio_features.sort_values(by = 'Today P/L%', ascending=False)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
33,HCLTECH,5.65,-26.08,64.39,21.51,115144.0,-63101.0,178823.0,1872.35,-22.25,52.0,X-LC,20.34,8.0,-0.55,1.17,10.13,X40,ATH,IT
6,AWL,3.89,-34.19,153.78,67.02,360602.0,-121817.0,234492.0,485.00,-64.61,56.0,X-SC,14.81,81.0,-0.34,1.53,11.50,XY24,NTT,FMCG
91,ZYDUSLIFE,3.71,20.28,12.76,35.63,32165.0,42499.0,252073.0,1286.17,4.50,67.0,H-MC,14.49,120.0,1.32,1.64,32.54,AR,ATH,PHARMA
61,RAJESHEXPO,3.64,-81.64,445.15,0.07,112089.0,-111997.0,25180.0,518.00,822.98,48.0,L-SC,38.94,268.0,-1.00,0.16,24.36,OX40N,NTT,JEWELLERY
44,INDUSINDBK,3.27,-28.07,84.74,32.89,47063.0,-21668.0,55538.0,1800.00,-361.20,66.0,L-MC,7.46,258.0,-0.46,0.36,36.92,XR,NTT,BANKS

In [11]:
# bottom 5 today
df_tmp = df_portfolio_features.sort_values(by = 'Today P/L%', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
23,DMART,-4.60,-3.98,34.98,29.60,83834.0,-9936.0,239664.0,5391.45,-19.07,35.0,X-LC,3.76,14.0,-0.12,1.56,9.55,X40N,ATH,FMCG
83,TTKPRESTIG,-3.36,-18.85,23.35,0.09,19095.0,-19000.0,81777.0,770.00,89.75,69.0,M-SC,6.03,250.0,-1.00,0.53,45.61,OX40N,NTT,DURABLES
24,EASEMYTRIP,-2.91,-61.37,277.14,45.70,189303.0,-108509.0,68306.0,26.40,-29.01,39.0,M-SC,3.88,204.0,-0.57,0.45,19.66,XY24,NTT,TRAVEL
25,FINCABLES,-2.63,39.33,49.22,107.91,101255.0,58075.0,205719.0,1641.55,25.32,50.0,M-SC,26.40,220.0,0.57,1.34,54.77,OX40N,ATH,CABLES
9,BANDHANBNK,-2.19,-3.50,99.40,92.42,267191.0,-9755.0,268804.0,400.00,130.60,46.0,H-SC,21.17,174.0,-0.04,1.75,48.08,XY24,NTT,BANKS

In [12]:
# top 5 to exit based on CumlRnk
df_tmp = df_portfolio_features[~df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])]
df_tmp = df_tmp[(df_tmp['Current P/L%'] > -1) & (df_tmp['Current P/L%'] < 1)].sort_values(by = 'CumlRnk', ascending=False)
df_tmp[cols].head()

Empty DataFrame
Columns: [Symbol, Today P/L%, Current P/L%, FTT%, OTT%, FTT Amt, Current P/L, Current, FTT, Dev%_PE, RSI_14, Conviction, Spread%, CumlRnk, RRR Ind, CurrAlloc%, Gained%, Criteria, Strategy, Category]
Index: []

In [13]:
# OX40N stocks to exit
df_tmp = df_portfolio_features[(df_portfolio_features['Symbol'].isin(list_ox40n))].sort_values(by = 'Current P/L%', ascending=False)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
25,FINCABLES,-2.63,39.33,49.22,107.91,101255.0,58075.0,205719.0,1641.55,25.32,50.0,M-SC,26.40,220.0,0.57,1.34,54.77,OX40N,ATH,CABLES
72,SIS,0.07,-2.22,24.02,21.26,26078.0,-2466.0,108566.0,528.00,2590.16,55.0,H-SC,24.93,168.0,-0.09,0.71,61.42,OX40N,NTT,MISC
16,CERA,-0.25,-15.53,46.67,23.89,69342.0,-27323.0,148580.0,9475.00,-18.62,65.0,H-SC,13.18,153.0,-0.39,0.97,42.78,OX40N,NTT,CERAMICS
83,TTKPRESTIG,-3.36,-18.85,23.35,0.09,19095.0,-19000.0,81777.0,770.00,89.75,69.0,M-SC,6.03,250.0,-1.00,0.53,45.61,OX40N,NTT,DURABLES
43,INDIGOPNTS,-1.04,-24.28,32.09,0.02,42414.0,-42387.0,132172.0,1408.00,101.45,65.0,M-SC,5.29,222.0,-1.00,0.86,49.96,OX40N,NTT,PAINTS

In [14]:
# top 5 to book for rotation
df_tmp = df_portfolio_features[(df_portfolio_features['Current P/L%'] > 20) ].sort_values(by = 'CumlRnk', ascending=False)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
25,FINCABLES,-2.63,39.33,49.22,107.91,101255.0,58075.0,205719.0,1641.55,25.32,50.0,M-SC,26.40,220.0,0.57,1.34,54.77,OX40N,ATH,CABLES
68,SATIN,-1.88,41.19,7.54,51.83,29413.0,113815.0,390099.0,274.00,26.15,65.0,H-SC,41.47,159.0,3.87,2.54,90.04,XY24,NTT,FINANCE
91,ZYDUSLIFE,3.71,20.28,12.76,35.63,32165.0,42499.0,252073.0,1286.17,4.50,67.0,H-MC,14.49,120.0,1.32,1.64,32.54,AR,ATH,PHARMA

In [15]:
# top 5 to monitor for exit
df_tmp = df_portfolio_features[~df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])]
df_tmp = df_tmp[(df_tmp['Current P/L%'] > 0) ].sort_values(by = 'Dev%_PE', ascending=False)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
75,SURYODAY,-0.84,3.75,18.58,23.03,34520.0,6722.0,185793.0,216.00,101.75,66.0,H-SC,19.73,166.0,0.19,1.21,56.43,XR,NTT,BANKS
74,STARHEALTH,-1.39,12.29,31.14,47.26,98304.0,34560.0,315683.0,761.00,77.33,66.0,H-SC,15.02,173.0,0.35,2.06,38.53,XY24,NTT,INSURANCE
68,SATIN,-1.88,41.19,7.54,51.83,29413.0,113815.0,390099.0,274.00,26.15,65.0,H-SC,41.47,159.0,3.87,2.54,90.04,XY24,NTT,FINANCE
25,FINCABLES,-2.63,39.33,49.22,107.91,101255.0,58075.0,205719.0,1641.55,25.32,50.0,M-SC,26.40,220.0,0.57,1.34,54.77,OX40N,ATH,CABLES
91,ZYDUSLIFE,3.71,20.28,12.76,35.63,32165.0,42499.0,252073.0,1286.17,4.50,67.0,H-MC,14.49,120.0,1.32,1.64,32.54,AR,ATH,PHARMA

In [16]:
# top 5 to book for rotation from weak conviction
df_tmp = df_portfolio_features[~df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])]
df_tmp = df_tmp[~df_tmp['Criteria'].isin(['XY25','XY24','X40', 'X40N'])].sort_values(by = 'RRR Ind', ascending=False)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
91,ZYDUSLIFE,3.71,20.28,12.76,35.63,32165.0,42499.0,252073.0,1286.17,4.50,67.0,H-MC,14.49,120.0,1.32,1.64,32.54,AR,ATH,PHARMA
73,SONACOMS,-0.33,14.19,21.45,38.69,24779.0,14359.0,115518.0,801.69,-9.53,75.0,M-MC,18.50,193.0,0.58,0.75,63.89,AR,ATH,AUTO
25,FINCABLES,-2.63,39.33,49.22,107.91,101255.0,58075.0,205719.0,1641.55,25.32,50.0,M-SC,26.40,220.0,0.57,1.34,54.77,OX40N,ATH,CABLES
75,SURYODAY,-0.84,3.75,18.58,23.03,34520.0,6722.0,185793.0,216.00,101.75,66.0,H-SC,19.73,166.0,0.19,1.21,56.43,XR,NTT,BANKS
55,MASFIN,1.05,-1.39,23.29,21.57,22502.0,-1365.0,96615.0,397.04,-15.09,59.0,H-SC,2.43,167.0,-0.06,0.63,15.16,XR,ATH,FINANCE

In [17]:
# top 5 to accumulate based on lowest RSI_14
df_tmp = df_portfolio_features[df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])].sort_values(by = 'RSI_14', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
23,DMART,-4.60,-3.98,34.98,29.60,83834.0,-9936.0,239664.0,5391.45,-19.07,35.0,X-LC,3.76,14.0,-0.12,1.56,9.55,X40N,ATH,FMCG
81,TMPV,-0.53,-21.67,74.37,36.58,207285.0,-77120.0,278721.0,600.00,-83.62,38.0,X-LC,7.52,4.0,-0.37,1.82,17.14,XY24,NTT,AUTO
58,PGHH,0.18,-33.29,97.90,32.01,139441.0,-71088.0,142432.0,17616.87,-54.91,40.0,X-MC,21.06,57.0,-0.51,0.93,1.01,X40,ATH,FMCG
35,HDFCLIFE,-0.64,-7.15,42.93,32.71,59710.0,-10714.0,139086.0,811.41,-27.55,40.0,X-LC,16.04,31.0,-0.18,0.91,4.49,X40,ATH,INSURANCE
26,GILLETTE,-0.04,-10.08,44.26,29.72,101052.0,-25581.0,228315.0,10978.86,-30.84,41.0,X-SC,6.31,83.0,-0.25,1.49,4.92,X40,ATH,FMCG

In [18]:
# top 5 to accumulate based on Spread and CumlRnk
df_tmp = df_portfolio_features[df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])]
df_tmp = df_tmp[(df_tmp['CumlRnk'] < 100)].sort_values(by = 'Spread%', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
17,CIPLA,0.15,18.06,13.03,33.43,23560.0,27656.0,180817.0,1648.14,-8.67,68.0,X-LC,2.13,18.0,1.17,1.18,23.44,X40N,ATH,PHARMA
84,UNITDSPR,1.45,2.35,17.99,20.77,43113.0,5504.0,239648.0,1644.00,-9.24,65.0,X-MC,3.14,64.0,0.13,1.56,14.32,X40N,NTT,BREWERIES
11,BERGEPAINT,-0.25,-4.27,30.91,25.32,76267.0,-11010.0,246739.0,680.00,-9.42,51.0,X-MC,3.22,68.0,-0.14,1.61,28.42,XY24,NTT,PAINTS
19,COLPAL,-0.70,-22.28,79.94,39.86,163637.0,-58665.0,204700.0,3683.41,-5.85,53.0,X-MC,3.39,62.0,-0.36,1.33,15.79,XY25,ATH,FMCG
23,DMART,-4.60,-3.98,34.98,29.60,83834.0,-9936.0,239664.0,5391.45,-19.07,35.0,X-LC,3.76,14.0,-0.12,1.56,9.55,X40N,ATH,FMCG

In [19]:
# top 5 to accumulate based on lowest Gained%
df_tmp = df_portfolio_features[df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])].sort_values(by = 'Gained%', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
58,PGHH,0.18,-33.29,97.90,32.01,139441.0,-71088.0,142432.0,17616.87,-54.91,40.0,X-MC,21.06,57.0,-0.51,0.93,1.01,X40,ATH,FMCG
1,ABBOTINDIA,0.66,-13.13,35.91,18.07,55793.0,-23485.0,155370.0,35195.00,-26.09,48.0,X-MC,6.55,58.0,-0.42,1.01,2.84,X40,ATH,PHARMA
65,RELIANCE,0.04,-16.29,49.69,25.30,83587.0,-32747.0,168216.0,1952.00,-18.49,46.0,X-LC,7.82,21.0,-0.39,1.10,3.59,XY25,BTT,REFINERIES
35,HDFCLIFE,-0.64,-7.15,42.93,32.71,59710.0,-10714.0,139086.0,811.41,-27.55,40.0,X-LC,16.04,31.0,-0.18,0.91,4.49,X40,ATH,INSURANCE
32,HAVELLS,-0.47,-24.38,73.79,31.42,183022.0,-79960.0,248031.0,2052.62,-28.80,50.0,X-MC,12.94,63.0,-0.44,1.62,4.61,X40,ATH,ELECTRICAL

In [20]:
# top 5 to accumulate based on lowest CurrAlloc%
df_tmp = df_portfolio_features[df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])].sort_values(by = 'CurrAlloc%', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
10,BATAINDIA,-0.28,-55.06,200.89,35.20,116151.0,-70852.0,57818.0,2096.00,-24.19,49.0,X-SC,20.04,91.0,-0.61,0.38,14.67,X40,NTT,FOOTWEAR
64,RELAXO,-2.05,-48.56,196.11,52.31,146424.0,-70496.0,74664.0,1176.00,-45.21,64.0,X-SC,10.64,92.0,-0.48,0.49,66.94,X40N,NTT,FOOTWEAR
60,QUESS,2.57,19.29,45.78,73.90,58320.0,20599.0,127392.0,424.00,-36.09,86.0,X-SC,19.21,80.0,0.35,0.83,73.66,XY24,NTT,MISC
35,HDFCLIFE,-0.64,-7.15,42.93,32.71,59710.0,-10714.0,139086.0,811.41,-27.55,40.0,X-LC,16.04,31.0,-0.18,0.91,4.49,X40,ATH,INSURANCE
53,M&M,-1.21,1.79,19.94,22.08,28147.0,2479.0,141160.0,3762.31,-13.74,56.0,X-LC,9.00,25.0,0.09,0.92,8.16,X40N,ATH,AUTO

In [21]:
# top 5 to accumulate based on CumlRnk
df_tmp = df_portfolio_features.sort_values(by = 'CumlRnk', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
47,ITC,0.02,-23.63,55.89,19.06,145199.0,-80371.0,259795.0,452.00,-57.95,51.0,X-LC,13.19,1.0,-0.55,1.69,4.68,X40,NTT,FMCG
79,TCS,1.23,-38.54,103.20,24.88,293827.0,-178557.0,284716.0,4253.91,-47.89,44.0,X-LC,21.61,2.0,-0.61,1.86,5.59,X40,ATH,IT
45,INFY,0.61,-28.71,88.31,34.24,196979.0,-89834.0,223054.0,1972.00,-43.76,43.0,X-LC,20.39,3.0,-0.46,1.45,6.28,X40,NTT,IT
81,TMPV,-0.53,-21.67,74.37,36.58,207285.0,-77120.0,278721.0,600.00,-83.62,38.0,X-LC,7.52,4.0,-0.37,1.82,17.14,XY24,NTT,AUTO
59,PIDILITIND,-0.46,13.24,4.52,18.37,7223.0,18690.0,159800.0,1670.26,-20.71,67.0,X-LC,6.81,5.0,2.59,1.04,25.47,X40,ATH,CHEMICALS

In [22]:
# top 5 for average up
df_tmp = df_portfolio_features[(df_portfolio_features['Dev%_200'] > 5)].sort_values(by = 'CurrAlloc%', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
44,INDUSINDBK,3.27,-28.07,84.74,32.89,47063.0,-21668.0,55538.0,1800.00,-361.20,66.0,L-MC,7.46,258.0,-0.46,0.36,36.92,XR,NTT,BANKS
64,RELAXO,-2.05,-48.56,196.11,52.31,146424.0,-70496.0,74664.0,1176.00,-45.21,64.0,X-SC,10.64,92.0,-0.48,0.49,66.94,X40N,NTT,FOOTWEAR
3,ALKYLAMINE,-0.05,-22.19,147.45,92.54,115838.0,-22402.0,78561.0,4520.85,-16.74,57.0,H-SC,8.84,142.0,-0.19,0.51,49.18,SR,ATH,CHEMICALS
83,TTKPRESTIG,-3.36,-18.85,23.35,0.09,19095.0,-19000.0,81777.0,770.00,89.75,69.0,M-SC,6.03,250.0,-1.00,0.53,45.61,OX40N,NTT,DURABLES
72,SIS,0.07,-2.22,24.02,21.26,26078.0,-2466.0,108566.0,528.00,2590.16,55.0,H-SC,24.93,168.0,-0.09,0.71,61.42,OX40N,NTT,MISC

In [23]:
# top 5 RSP
df_tmp = df_portfolio_features.sort_values(by = 'RSP', ascending=False)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
60,QUESS,2.57,19.29,45.78,73.90,58320.0,20599.0,127392.0,424.0,-36.09,86.0,X-SC,19.21,80.0,0.35,0.83,73.66,XY24,NTT,MISC
69,SFL,0.47,-24.58,67.90,26.63,134286.0,-64448.0,197770.0,1287.0,49.77,73.0,M-SC,19.23,242.0,-0.48,1.29,64.83,XY24,NTT,MISC
49,JSWINFRA,-0.44,11.00,4.89,16.43,12038.0,24394.0,246168.0,342.0,-4.83,65.0,X-MC,10.05,61.0,2.03,1.61,39.57,X40N,NTT,REALTY
0,5PAISA,0.61,-26.19,52.97,12.90,85420.0,-57234.0,161262.0,593.0,137.98,80.0,H-SC,2.19,170.0,-0.67,1.05,55.62,OX40N,NTT,FINANCE
64,RELAXO,-2.05,-48.56,196.11,52.31,146424.0,-70496.0,74664.0,1176.0,-45.21,64.0,X-SC,10.64,92.0,-0.48,0.49,66.94,X40N,NTT,FOOTWEAR

In [24]:
# Top N allocation
df_tmp = df_portfolio_features.sort_values(by = 'CurrAlloc%', ascending=False)
top_n_values = [10, 25, 50]

sum_df = pd.DataFrame({
    'Top_N': top_n_values,
    'Sum_Alloc%': [df_tmp['CurrAlloc%'].head(n).sum() for n in top_n_values]
})

sum_df

   Top_N  Sum_Alloc%
0     10       19.42
1     25       42.63
2     50       72.80

In [25]:
# market-cap-wise allocation
df_tmp = df_portfolio_features[cols]
df_tmp.groupby(df_tmp['Conviction'].str[-2:])['CurrAlloc%'].sum().sort_values(ascending=False)

Conviction
SC    43.79
LC    30.30
MC    25.92
Name: CurrAlloc%, dtype: float64

In [26]:
# criteria-wise allocation
df_portfolio_features.groupby('Criteria')['CurrAlloc%'].sum().sort_values(ascending=False)

Criteria
XY24     27.98
X40      24.49
X40N     17.47
XR        8.85
OX40N     7.16
AR        6.76
XY25      6.43
SR        0.87
Name: CurrAlloc%, dtype: float64

In [27]:
# conviction-wise allocation
df_portfolio_features.groupby('Conviction')['CurrAlloc%'].sum().sort_values(ascending=False)

Conviction
X-LC    28.35
H-SC    22.95
X-MC    20.78
X-SC    10.15
M-SC    10.12
H-MC     2.72
M-MC     2.06
H-LC     1.15
M-LC     0.80
L-SC     0.57
L-MC     0.36
Name: CurrAlloc%, dtype: float64

In [28]:
# sector-wise stats
df_tmp = df_portfolio_features.groupby('Category')[['CurrAlloc%', 'Current', 'Current P/L', 'FTT Amt']].sum().sort_values(by=['Current', 'Current P/L'], ascending=False)
df_tmp['Current P/L%'] = round(df_tmp['Current P/L'] * 100 / df_tmp['Current'], 2)
df_tmp['FTT%'] = round(df_tmp['FTT Amt'] * 100 / df_tmp['Current'], 2)
cols = ['CurrAlloc%', 'Current P/L%', 'FTT%']
df_tmp[cols].sort_values(by=['CurrAlloc%'], ascending=False)

               CurrAlloc%  Current P/L%    FTT%
Category
FMCG                14.46        -19.35   61.22
FINANCE             11.51         -4.49   49.76
IT                   9.56        -53.83  130.75
MISC                 7.25        -20.64   72.40
AUTO                 6.68         -6.98   46.87
BANKS                5.75         -2.97   50.58
PAINTS               5.53        -16.09   35.90
INSURANCE            5.23         -3.39   38.27
PHARMA               5.08          5.00   24.40
ELECTRICAL           4.06        -13.58   53.66
CHEMICALS            2.17        -21.83   94.11
HEALTHCARE           2.11        -10.63   39.50
APPARELS             1.95         10.42   19.67
AC                   1.74        -19.35   51.72
FOOTWEAR             1.74        -65.87  132.38
REALTY               1.61          9.91    4.89
DURABLES             1.60        -56.44   94.50
BREWERIES            1.56          2.30   17.99
TRAVEL               1.53        -90.72  186.21
CERAMICS             1.44        -39.52   81.91
CABLES               1.34         28.23   49.22
ENGINEERING          1.30        -21.08   76.46
REFINERIES           1.10        -19.47   49.69
CEMENT               1.09        -60.31  180.24
JEWELLERY            1.03       -102.05  172.25
ENTERTAINMENT        0.75        -67.43  167.29
TEXTILES             0.43        -39.73   79.57
HOTELS               0.41        -81.86  146.00

In [29]:
# money to be made criteria-wise
df_portfolio_features.groupby('Criteria')['FTT Amt'].agg(['sum', 'count']).sort_values(by='sum', ascending=False)

                sum  count
Criteria
XY24      3307616.0     21
X40       1921975.0     19
XR        1324585.0     13
AR        1139823.0      9
X40N      1041850.0     13
OX40N      691951.0     10
XY25       450152.0      5
SR         283700.0      2

In [30]:
# money to be made conviction-wise
df_portfolio_features.groupby('Conviction')['FTT Amt'].agg(['sum', 'count']).sort_values(by='sum', ascending=False)

                  sum  count
Conviction
H-SC        3259248.0     24
X-LC        1934793.0     21
X-MC        1529717.0     15
M-SC        1363728.0     14
X-SC        1248708.0      9
H-MC         279619.0      2
L-SC         203248.0      2
M-LC         169527.0      1
M-MC          69243.0      2
H-LC          56758.0      1
L-MC          47063.0      1

In [31]:
# money to be made criteria and conviction-wise
df_portfolio_features.groupby(['Conviction', 'Criteria'])['FTT Amt'].agg(['sum', 'count']).sort_values(by='sum', ascending=False)

                           sum  count
Conviction Criteria
X-LC       X40       1040376.0     10
H-SC       AR         953703.0      5
           XY24       939230.0      6
M-SC       XY24       809417.0      6
H-SC       XR         797619.0      7
X-SC       XY24       740820.0      4
X-MC       X40        664396.0      7
           X40N       398077.0      4
X-LC       XY24       353463.0      2
           X40N       353088.0      6
M-SC       OX40N      294866.0      5
X-SC       X40N       290685.0      3
H-SC       OX40N      284996.0      4
           SR         283700.0      2
X-MC       XY25       250012.0      2
H-MC       XY24       247454.0      1
X-MC       XY24       217232.0      2
X-SC       X40        217203.0      2
M-SC       XR         187027.0      2
M-LC       XR         169527.0      1
X-LC       XY25       155676.0      2
L-SC       OX40N      112089.0      1
           XR          91159.0      1
M-SC       AR          72418.0      1
H-LC       AR          56758.0      1
L-MC       XR          47063.0      1
M-MC       XY25        44464.0      1
X-LC       XR          32190.0      1
H-MC       AR          32165.0      1
M-MC       AR          24779.0      1

In [32]:
# notebook execution time

end_time = time.time()
execution_time = round(end_time - start_time, 0)
print(f"Notebook execution time: {execution_time} seconds")

Notebook execution time: 28.0 seconds