<a href="https://colab.research.google.com/github/ankit-rathi/Quantvesting_v2/blob/main/myStocks_Portfolio_Analysis.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
'''
!pip install pandas==2.2.2 -qq
!pip install pyxirr -qq
!pip install ta -qq
!pip install yfinance==0.2.59 -qq
'''

'\n!pip install pandas==2.2.2 -qq\n!pip install pyxirr -qq\n!pip install ta -qq\n!pip install yfinance==0.2.59 -qq\n'

In [2]:
# import libraries

import numpy as np
import pandas as pd
import datetime
import warnings
warnings.filterwarnings('ignore')
import yfinance as yfin
import ta
import matplotlib.pyplot as plt
import requests

In [3]:
# notebook start time
import time
import datetime
import pytz

start_time = time.time()

# function to print date timestamp
def print_date_time():
  tz_NY = pytz.timezone('Asia/Kolkata')
  datetime_NY = datetime.datetime.now(tz_NY)
  print("Run date time (IST):", datetime_NY.strftime("%Y-%m-%d %H:%M:%S"))

In [4]:
# function to get booked and reserved amount
def get_amt():
  # fetch the JSON data from the URL
  url = "https://raw.githubusercontent.com/ankit-rathi/Tradevesting_v1/main/data/myPortfolioAmts.json"
  response = requests.get(url)
  pf_amts = response.json()  # parse the JSON data

  # extract values from the JSON
  py_booked_amt_dm = pf_amts["py_booked_amt_dm"]
  py_booked_amt_sv = pf_amts["py_booked_amt_sv"]
  cy_booked_amt_dm = pf_amts["cy_booked_amt_dm"]
  cy_booked_amt_sv = pf_amts["cy_booked_amt_sv"]
  reserve_amt_dm = pf_amts["reserve_amt_dm"]
  reserve_amt_sv = pf_amts["reserve_amt_sv"]

  # perform calculations
  py_booked_amt = py_booked_amt_dm + py_booked_amt_sv
  cy_booked_amt = cy_booked_amt_dm + cy_booked_amt_sv
  reserve_amt = reserve_amt_dm + reserve_amt_sv
  total_booked_amt = py_booked_amt + cy_booked_amt

  return total_booked_amt, reserve_amt, cy_booked_amt, py_booked_amt

gen_output = 0

In [5]:
# function to format the amount
def format_amt(number):
    abs_number = abs(number)

    if abs_number >= 1_00_00_000:  # Crores
        formatted_amt = f"{number / 1_00_00_000:.2f} C"
    elif abs_number >= 1_00_000:  # Lakhs
        formatted_amt = f"{number / 1_00_000:.2f} L"
    elif abs_number >= 1_000:  # Thousands
        formatted_amt = f"{number / 1_000:.2f} K"
    else:
        formatted_amt = f"{number:.2f}"

    return formatted_amt

# function to set start and end date
def get_start_end_date():
  start_date = (datetime.date.today() + datetime.timedelta(days=-365)).strftime('%Y-%m-%d')
  end_date = (datetime.date.today() + datetime.timedelta(days=1)).strftime('%Y-%m-%d')
  return start_date, end_date

# function to fetch my portfolio csv
def get_mypfs_df():
  mypfs_df = pd.read_csv('https://raw.githubusercontent.com/ankit-rathi/Tradevesting_v1/main/data/myPortfolioStocks.csv')
  return mypfs_df

# function to fetch my prospects csv
def get_mypps_df():
  mypps_df = pd.read_csv('https://raw.githubusercontent.com/ankit-rathi/Tradevesting_v1/main/data/myProspectsScrips.csv')
  return mypps_df

# function to fetch screener data
def get_myscreen_df():
  myscreen_df = pd.read_csv('https://raw.githubusercontent.com/ankit-rathi/Tradevesting_v1/main/data/myScreenerDB.csv')
  return myscreen_df

# function to fetch momentum data
def get_myinvmt_df():
  myinvmt_df = pd.read_csv('https://raw.githubusercontent.com/ankit-rathi/Tradevesting_v1/main/data/myInvestments.csv')
  return myinvmt_df

# function to get the stock ids
def get_stock_ids(df_pf):
  stock_n100 = df_pf['Symbol'].unique()

  exclude = ['CADILAHC','MMTC', 'MASFIN']

  stock_ids = df_pf[~df_pf['Symbol'].isin(exclude) ]['Symbol'].unique()

  #mypf = mypf[mypf.Forecast.notnull()]
  #stock_ids = mypf['Symbol'].unique()

  #stock_ids.sort()
  return stock_ids

# get features from screener data
def get_screener_features():
  myscreen_df = get_myscreen_df()
  cols = ['Symbol', 'EPS', 'MedPE', 'ROCE%', 'ROE%', 'CapType']
  return myscreen_df[cols]

# get relative strength
def get_relative_strength(stock_list):

    # Dictionary to store stock tickers and their corresponding percentage price change
    stock_changes = {}

    # Loop through each stock and fetch its price data
    for stock in stock_list:
        try:
            # Download the stock data for the given date range
            stock_data = yfin.Ticker(stock + '.NS').history(period='1mo', interval='1d')[map(str.title, ['open', 'close', 'low', 'high', 'volume'])]

            # Calculate the percentage change for the stock
            if len(stock_data) > 0:
                start_price = stock_data['Close'].iloc[0]
                end_price = stock_data['Close'].iloc[-1]
                percent_change = round(((end_price - start_price) / start_price) * 100, 2)
                stock_changes[stock] = percent_change
            else:
                stock_changes[stock] = np.nan  # If no data is available, set to NaN

        except Exception as e:
            print(f"Error fetching data for {stock}: {e}")
            stock_changes[stock] = np.nan

    # Create a DataFrame with stock tickers and their percentage changes
    df = pd.DataFrame(list(stock_changes.items()), columns=['Symbol', 'Percent_Change'])

    # Drop any stocks with missing data (NaN values)
    df = df.dropna()

    # Calculate the percentile rank based on percentage change
    df['RSP'] = round(df['Percent_Change'].rank(pct=True) * 100, 2)
    cols = ['Symbol', 'RSP']
    df = df[cols]
    # Sort by percentile rank (optional)
    df = df.sort_values(by='RSP', ascending=False).reset_index(drop=True)

    return df

In [6]:
# function to get stock technicals
def stock_prec_dev(stock_symbol):
    #stock_symbol = 'ULTRACEMCO.NS'
    short_window = 20
    mid_window = 50
    long_window = 200
    moving_avg = 'SMA'

    start = datetime.datetime(*map(int, start_date.split('-')))
    end = datetime.datetime(*map(int, end_date.split('-')))

    stock_df = yfin.Ticker(stock_symbol + '.NS').history(period='max', interval='1d')[map(str.title, ['open', 'close', 'low', 'high', 'volume'])]

    stock_df['Max'] = round(max(stock_df['Close']),2)
    stock_df = stock_df[(stock_df.index <= end_date) & (stock_df.index >= start_date)]
    stock_df['200_SMA'] = round(stock_df['Close'].rolling(window = 200, min_periods = 1).mean(),0)
    stock_df['Dev%_200'] = round((stock_df['Close'] - stock_df['200_SMA'])*100/stock_df['200_SMA'],2)
    stock_df.dropna(axis = 0, inplace = True) # remove any null rows

    stock_df['20_SMA'] = stock_df['Close'].rolling(window=20).mean()
    stock_df['50_SMA'] = stock_df['Close'].rolling(window=50).mean()
    stock_df['Symbol'] = stock_symbol

    stock_df['Close'] = round(stock_df['Close'],2)
    stock_df['Min'] = round(min(stock_df['Close']),2)
    stock_df['RSI_14'] = ta.momentum.RSIIndicator(close=stock_df['Close'], window=14).rsi()
    stock_df['RSI_14'] = round(stock_df['RSI_14'],0)
    stock_df['Prev_Close'] = stock_df['Close'].shift(1)
    stock_df.drop(['Open', 'Low', 'High', 'Volume'], axis=1, inplace=True)
    stock_df = stock_df.tail(1)

    max_SMA = max(stock_df['20_SMA'].item(), stock_df['50_SMA'].item(), stock_df['200_SMA'].item())
    min_SMA = min(stock_df['20_SMA'].item(), stock_df['50_SMA'].item(), stock_df['200_SMA'].item())
    ABS_Spread = max_SMA - min_SMA
    stock_df['Spread%'] = round((ABS_Spread / stock_df['200_SMA'].item()) * 100,2)

    return stock_df

# function to compute stock attributes
def get_common_features(stock_ids, df_mypf):

  df_prec_dev = pd.DataFrame()
  df_tmp = get_screener_features()
  df_rs = get_relative_strength(stock_ids)

  for stock_id in stock_ids:
      tmp = stock_prec_dev(stock_id)
      tmp = tmp.reset_index()
      df_prec_dev = pd.concat([df_prec_dev, tmp], ignore_index = True)
  df_prec_dev = pd.merge(df_prec_dev, df_mypf, on= 'Symbol')
  df_prec_dev = pd.merge(df_prec_dev, df_tmp, on= 'Symbol', how='left')
  df_prec_dev = pd.merge(df_prec_dev, df_rs, on= 'Symbol', how='left')
  #print(df_prec_dev.columns)
  df_prec_dev['Curr_PE'] = round(df_prec_dev['Close']/df_prec_dev['EPS'],1)
  df_prec_dev['Dev%_PE'] = round((df_prec_dev['Curr_PE'] - df_prec_dev['MedPE'])*100/df_prec_dev['MedPE'],2)
  df_prec_dev['Conviction'] = df_prec_dev['Conviction'] + '-' + df_prec_dev['CapType']
  return df_prec_dev

# function to arrange stock features
def arrange_features(df_stocks, common_cols, diff_cols):
  df_stocks_common = df_stocks[common_cols].drop_duplicates()
  df_stocks_diff = df_stocks[diff_cols]
  df_stocks_diff['Investment'] = df_stocks_diff['AvgCost'] * df_stocks_diff['Shares']
  df_stocks_diff = df_stocks_diff.groupby(['Symbol'])[['Shares', 'Investment']].aggregate(['sum']).reset_index()
  df_stocks_diff.columns = ['Symbol', 'Shares', 'Investment']
  df_stocks_diff['AvgCost'] = round(df_stocks_diff['Investment']/df_stocks_diff['Shares'],2)
  df_stocks = pd.merge(df_stocks_diff, df_stocks_common, on='Symbol')
  return df_stocks

# plot fact distribution across dimension
def plot_pie_chart(df, dimension, fact):
  # grouping the data by category and calculating the sum of fact for each type
  grouped_data = df.groupby(dimension)[fact].sum()

  # sorting the grouped data in descending order
  grouped_data = grouped_data.sort_values(ascending=False)

  # creating a pie chart
  grouped_data.plot.pie(autopct='%1.1f%%', startangle=90, figsize=(6, 6))

  # adding a title and displaying the plot
  plt.title(f'{dimension} {fact} Distribution')
  plt.ylabel('')  # To hide the y-label
  plt.show()

In [7]:
# function to get portfolio features

def get_portfolio_features(df_common_features):

  print_date_time()
  print('-------------------')

  #df_common_features["Target"] = df_common_features["Target"].fillna(df_common_features["Max"])
  df_common_features['NTT'] = np.where(df_common_features['Strategy']== 'NTT', df_common_features["Target"], df_common_features['Max'])
  df_common_features['LTT'] = np.where(df_common_features['Strategy']== 'BTT', df_common_features["Target"], df_common_features['Max'])
  df_common_features['BOL'] = df_common_features['Min']

  tmp_df = df_common_features[df_common_features['Symbol'].isin(mypf_df[mypf_df['InPortfolio'] != 'NA'].Symbol.values)]
  print('qualified stocks: '+str(len(tmp_df['Symbol'].unique())))
  tmp_df1 = tmp_df[tmp_df['LatestQtr'] == 1]
  print('with latest results: '+str(len(tmp_df1['Symbol'].unique())))
  tmp_df1 = tmp_df1[tmp_df1['StarStock'] == 1]
  print('still star stocks: '+str(len(tmp_df1['Symbol'].unique())))
  tmp_df['Investment'] = tmp_df['AvgCost'] * tmp_df['Shares']
  tmp_df['Current'] = round(tmp_df['Close'] * tmp_df['Shares'],0)
  tmp_df['Previous'] = tmp_df['Prev_Close'] * tmp_df['Shares']
  tmp_df['EstimatedST'] = tmp_df['NTT'] * tmp_df['Shares']
  tmp_df['EstimatedLT'] = tmp_df['LTT'] * tmp_df['Shares']
  tmp_df['Current P/L'] = round((tmp_df['Current'] - tmp_df['Investment']),0)
  tmp_df['Today P/L%'] = round((tmp_df['Current'] - tmp_df['Previous'])*100/tmp_df['Previous'],2)
  tmp_df['Current P/L%'] = round((tmp_df['Current'] - tmp_df['Investment'])*100/tmp_df['Investment'],2)
  tmp_df['EstimatedST P/L%'] = round((tmp_df['EstimatedST'] - tmp_df['Investment'])*100/tmp_df['Investment'],2)
  tmp_df['EstimatedLT P/L%'] = round((tmp_df['EstimatedLT'] - tmp_df['Investment'])*100/tmp_df['Investment'],2)
  tmp_df['NTT%'] = round((tmp_df['NTT'] - tmp_df['Close'])*100/tmp_df['Close'],2)
  tmp_df['LTT%'] = round((tmp_df['LTT'] - tmp_df['Close'])*100/tmp_df['Close'],2)
  tmp_df['Gained%'] = round((tmp_df['Close'] - tmp_df['BOL'])*100/tmp_df['BOL'],2)
  investment = round(sum(tmp_df['AvgCost']*tmp_df['Shares']),0)
  current = round(sum(tmp_df['Close']*tmp_df['Shares']),0)
  tmp_df['InitAlloc%'] = round(tmp_df['Investment']*100/investment,2)
  tmp_df['CurrAlloc%'] = round(tmp_df['Current']*100/current,2)
  tmp_df['FTT'] = tmp_df['LTT']
  tmp_df.loc[tmp_df['Strategy'] == 'NTT', 'FTT'] = tmp_df['NTT']
  tmp_df['FTT%'] = tmp_df['LTT%']
  tmp_df.loc[tmp_df['Strategy'] == 'NTT', 'FTT%'] = tmp_df['NTT%']
  tmp_df['FTT Amt'] = round(tmp_df['FTT%'] * tmp_df['Current']/100,0)
  tmp_df['OTT%'] = round((tmp_df['FTT'] - tmp_df['AvgCost'])*100/tmp_df['AvgCost'],2)
  tmp_df['RRR Ind'] = round(tmp_df['Current P/L']/tmp_df['FTT Amt'],2)
  tmp_df['Risk Ind'] = round(tmp_df['Current P/L%']*tmp_df['CurrAlloc%'],0)

  return tmp_df

# function to print portfolio features
def print_portfolio_stats(df_portfolio_features, myinvmt_df):
  from pyxirr import xirr

  total_booked_amt, reserve_amt, cy_booked_amt, py_booked_amt = get_amt()

  dates = myinvmt_df['Date'].values
  dates = np.append(dates, datetime.date.today().strftime('%d-%b-%y'))
  investment = myinvmt_df['Investment'].values
  dates= pd.to_datetime(dates)

  current = round(sum(df_portfolio_features['Close']*df_portfolio_features['Shares']),0) + reserve_amt
  investment_xirr = np.append(investment, current)
  cagr = round(xirr(pd.DataFrame({"dates": dates, "amounts": investment_xirr}))*100,2)

  investment = -sum(investment)
  invested = round(sum(df_portfolio_features['AvgCost']*df_portfolio_features['Shares']),0) + reserve_amt
  previous = round(sum(df_portfolio_features['Prev_Close']*df_portfolio_features['Shares']),0) + reserve_amt
  cy_invested = investment + py_booked_amt

  today_pnl_amount = current-previous
  today_pnl_percentage = round((current-previous)*100/previous,2)

  curr_pnl_amount = current-invested
  curr_pnl_percentage = round((curr_pnl_amount)*100/(cy_invested),2)

  cy_pnl_amount = cy_booked_amt + curr_pnl_amount
  cy_pnl_percentage = round((cy_pnl_amount)*100/cy_invested,2)

  overall_pnl_amount = total_booked_amt + curr_pnl_amount
  overall_pnl_percentage = round((overall_pnl_amount)*100/investment,2)

  estimate_st = round(sum(df_portfolio_features['FTT']*df_portfolio_features['Shares']),0)  + reserve_amt
  est_st_pnl_amount = estimate_st-current
  est_st_pnl_percentage = round((est_st_pnl_amount)*100/current,2)

  estimate_lt = round(sum(df_portfolio_features['LTT']*df_portfolio_features['Shares']),0)  + reserve_amt
  est_lt_pnl_amount = estimate_lt-current
  est_lt_pnl_percentage = round((est_lt_pnl_amount)*100/current,2)

  total_profit = round(sum(df_portfolio_features[df_portfolio_features['Current P/L%'] > 0]['Current']) - sum(df_portfolio_features[df_portfolio_features['Current P/L%'] > 0]['Investment']),0)
  total_loss = round(sum(df_portfolio_features[df_portfolio_features['Current P/L%'] < 0]['Current']) - sum(df_portfolio_features[df_portfolio_features['Current P/L%'] < 0]['Investment']),0)

  cy_booked_percentage = round((cy_booked_amt)*100/current,2)
  py_booked_percentage = round((py_booked_amt)*100/investment,2)
  total_booked_percentage = round((total_booked_amt)*100/investment,2)

  print('-------------------')
  print('Initial Investment: ', format_amt(investment))
  print('CY Investment: ', format_amt(cy_invested))
  print('Reserve: ', format_amt(reserve_amt))
  print('Current: ',  format_amt(current))
  print('-------------------')
  print('Today PnL: '+ '{} ({}%)'.format(format_amt(today_pnl_amount), today_pnl_percentage))
  print('Current PnL: '+ '{} ({}%)'.format(format_amt(curr_pnl_amount), curr_pnl_percentage))
  print('CY Booked + Current PnL: '+ '{} ({}%)'.format(format_amt(cy_pnl_amount), cy_pnl_percentage))
  print('-------------------')
  print('Total profit: ', format_amt(total_profit))
  print('Total loss: ', format_amt(total_loss))
  print('-------------------')
  print('Total Booked + Current PnL: '+ '{} ({}%)'.format(format_amt(overall_pnl_amount), overall_pnl_percentage))
  print('Total Booked PnL: '+ '{} ({}%)'.format(format_amt(total_booked_amt), total_booked_percentage))
  print('Curr Year Booked PnL: '+ '{} ({}%)'.format(format_amt(cy_booked_amt), cy_booked_percentage))
  print('Prev Year Booked PnL: '+ '{} ({}%)'.format(format_amt(py_booked_amt), py_booked_percentage))
  print('===================')
  print('Est FTT: ',  format_amt(estimate_st))
  print('Est FTT PnL: '+ '{} ({}%)'.format(format_amt(est_st_pnl_amount), est_st_pnl_percentage))

  print('===================')
  print('Deployed: ', format_amt(investment))

  print('Current: ', format_amt(current))

  print('CAGR/XIRR %: '+'{}%'.format(cagr))

In [8]:
# get start and end date
start_date, end_date = get_start_end_date()

# get portfolio and prospects data
mypfs_df = get_mypfs_df()
mypps_df = get_mypps_df()
myinvmt_df = get_myinvmt_df()

# merge above datasets
mypf_df = pd.merge(mypfs_df, mypps_df, on="Symbol")

# seggregate dm and sv portfolio
dm_pf = mypf_df[mypf_df['InPortfolio'] == 'DM']
sv_pf = mypf_df[mypf_df['InPortfolio'] == 'SV']

# build portfolio stock dataframe
dm_stocks = get_stock_ids(dm_pf)
sv_stocks = get_stock_ids(sv_pf)
df_stocks = pd.concat([dm_pf,sv_pf], ignore_index = True)

# arrange common and diff stock features
common_cols = ['Symbol', 'Target', 'Criteria', 'Strategy', 'CumlRnk', 'LatestQtr', 'StarStock', 'Conviction', 'Category', 'InFolio', 'XIRR', 'MBQ']
diff_cols = ['Symbol', 'AvgCost', 'Shares']
df_stocks = arrange_features(df_stocks, common_cols, diff_cols)

# get common features
stock_ids = df_stocks['Symbol'].values
df_common_features = get_common_features(stock_ids, df_stocks)

df_common_features.reset_index(drop=True, inplace=True)
df_common_features.drop(['Date'], axis=1, inplace=True)
# get and print portfolio features
df_portfolio_features = get_portfolio_features(df_common_features)

print_portfolio_stats(df_portfolio_features, myinvmt_df)

df = df_portfolio_features
#plot_pie_chart(df, 'CapType', 'Current')
list_ox40n = list(df[df['MBQ'].str.contains('OX40N', na=False)]['Symbol'].values)

Run date time (IST): 2026-08-19 12:55:32
-------------------
qualified stocks: 87
with latest results: 30
still star stocks: 19
-------------------
Initial Investment:  1.46 C
CY Investment:  1.89 C
Reserve:  3.69 L
Current:  1.58 C
-------------------
Today PnL: -50.24 K (-0.32%)
Current PnL: -35.26 L (-18.66%)
CY Booked + Current PnL: -30.20 L (-15.99%)
-------------------
Total profit:  3.37 L
Total loss:  -38.63 L
-------------------
Total Booked + Current PnL: 12.67 L (8.67%)
Total Booked PnL: 47.93 L (32.82%)
Curr Year Booked PnL: 5.06 L (3.21%)
Prev Year Booked PnL: 42.87 L (29.35%)
===================
Est FTT:  2.67 C
Est FTT PnL: 1.09 C (69.39%)
===================
Deployed:  1.46 C
Current:  1.58 C
CAGR/XIRR %: 3.47%

In [9]:
# top 5 near their targets
cols = ['Symbol', 'Today P/L%', 'Current P/L%', 'FTT%', 'OTT%', 'FTT Amt', 'Current P/L', 'Current', 'FTT', 'Dev%_PE', 'RSI_14','Conviction', 'Spread%',  'CumlRnk', 'RRR Ind', 'CurrAlloc%', 'Gained%', 'Criteria', 'Strategy', 'Category']
df_tmp = df_portfolio_features[~df_portfolio_features['Symbol'].isin(['ENRIN','BLUSPRING','DIGITIDE'])]
df_tmp = df_tmp.sort_values(by = 'FTT Amt', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
66,SIEMENS,-1.23,5.01,5.54,10.83,10827.0,9330.0,195425.0,4125.00,-14.90,58.0,H-LC,13.85,51.0,0.86,1.27,37.88,AR,NTT,ELECTRICAL
78,UNITDSPR,-0.06,11.66,8.16,20.77,21334.0,27296.0,261440.0,1644.00,-4.79,59.0,X-MC,11.25,64.0,1.28,1.70,25.67,X40N,NTT,BREWERIES
77,TTKPRESTIG,-1.28,-23.70,31.18,0.09,23976.0,-23880.0,76897.0,770.00,-7.12,40.0,M-SC,9.67,250.0,-1.00,0.50,38.40,OX40N,NTT,DURABLES
52,M&M,-0.19,7.84,10.18,18.82,26422.0,18867.0,259548.0,3762.88,-6.96,58.0,X-LC,4.86,25.0,0.71,1.69,17.74,X40N,ATH,AUTO
67,SIS,0.07,-4.29,26.69,21.26,28364.0,-4761.0,106271.0,528.00,104.27,39.0,H-SC,21.60,168.0,-0.17,0.69,58.01,OX40N,NTT,MISC

In [10]:
# top 5 today
df_tmp = df_portfolio_features.sort_values(by = 'Today P/L%', ascending=False)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
0,5PAISA,6.14,-23.04,46.71,12.90,78541.0,-50349.0,168147.0,593.00,7.98,65.0,H-SC,11.74,170.0,-0.64,1.09,62.26,OX40N,NTT,FINANCE
27,GLAXO,4.30,20.48,12.63,35.69,30323.0,40804.0,240088.0,3380.16,-9.68,86.0,X-MC,9.81,56.0,1.35,1.56,42.69,X40,ATH,PHARMA
3,ALKYLAMINE,2.93,-15.83,128.74,92.54,109410.0,-15978.0,84985.0,4520.85,NaN,62.0,NaN,14.23,142.0,-0.15,0.55,61.38,SR,ATH,CHEMICALS
62,REPCOHOME,2.29,-22.86,146.09,89.82,322855.0,-65508.0,220997.0,880.00,NaN,33.0,NaN,3.93,161.0,-0.20,1.44,6.24,XY24,NTT,FINANCE
74,TITAGARH,2.20,-21.01,84.49,45.74,161632.0,-50874.0,191303.0,1548.00,NaN,49.0,NaN,7.69,175.0,-0.31,1.24,45.96,XY24,NTT,ENGINEERING

In [11]:
# bottom 5 today
df_tmp = df_portfolio_features.sort_values(by = 'Today P/L%', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
29,GREENPANEL,-3.93,-56.57,229.61,43.14,182551.0,-103573.0,79505.0,537.00,NaN,26.0,NaN,11.61,225.0,-0.57,0.52,0.00,XY24,NTT,MISC
60,RELAXO,-3.26,-50.99,210.74,52.31,149939.0,-74011.0,71149.0,1176.00,NaN,40.0,NaN,12.76,92.0,-0.49,0.46,59.08,X40N,NTT,FOOTWEAR
11,BERGEPAINT,-2.73,-1.53,27.26,25.32,69190.0,-3933.0,253816.0,680.00,-14.42,54.0,X-MC,4.52,68.0,-0.06,1.65,33.10,XY24,NTT,PAINTS
25,FINCABLES,-2.52,64.13,26.68,107.91,64652.0,94680.0,242324.0,1641.55,19.75,70.0,M-SC,20.37,220.0,1.46,1.57,82.31,OX40N,ATH,CABLES
70,SYMPHONY,-2.44,-53.66,115.73,-0.03,91782.0,-91834.0,79307.0,1306.00,NaN,24.0,NaN,16.10,205.0,-1.00,0.51,0.00,OX40N,NTT,DURABLES

In [12]:
# top 5 to exit based on CumlRnk
df_tmp = df_portfolio_features[~df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])]
df_tmp = df_tmp[(df_tmp['Current P/L%'] > -1) & (df_tmp['Current P/L%'] < 1)].sort_values(by = 'CumlRnk', ascending=False)
df_tmp[cols].head()

Empty DataFrame
Columns: [Symbol, Today P/L%, Current P/L%, FTT%, OTT%, FTT Amt, Current P/L, Current, FTT, Dev%_PE, RSI_14, Conviction, Spread%, CumlRnk, RRR Ind, CurrAlloc%, Gained%, Criteria, Strategy, Category]
Index: []

In [13]:
# OX40N stocks to exit
df_tmp = df_portfolio_features[(df_portfolio_features['Symbol'].isin(list_ox40n))].sort_values(by = 'Current P/L%', ascending=False)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
25,FINCABLES,-2.52,64.13,26.68,107.91,64652.0,94680.0,242324.0,1641.55,19.75,70.0,M-SC,20.37,220.0,1.46,1.57,82.31,OX40N,ATH,CABLES
67,SIS,0.07,-4.29,26.69,21.26,28364.0,-4761.0,106271.0,528.00,104.27,39.0,H-SC,21.60,168.0,-0.17,0.69,58.01,OX40N,NTT,MISC
43,INDIGOPNTS,-1.29,-18.59,22.86,0.02,32485.0,-32455.0,142104.0,1408.00,-22.31,62.0,M-SC,7.02,222.0,-1.00,0.92,61.23,OX40N,NTT,PAINTS
0,5PAISA,6.14,-23.04,46.71,12.90,78541.0,-50349.0,168147.0,593.00,7.98,65.0,H-SC,11.74,170.0,-0.64,1.09,62.26,OX40N,NTT,FINANCE
77,TTKPRESTIG,-1.28,-23.70,31.18,0.09,23976.0,-23880.0,76897.0,770.00,-7.12,40.0,M-SC,9.67,250.0,-1.00,0.50,38.40,OX40N,NTT,DURABLES

In [14]:
# top 5 to book for rotation
df_tmp = df_portfolio_features[(df_portfolio_features['Current P/L%'] > 20) ].sort_values(by = 'CumlRnk', ascending=False)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
25,FINCABLES,-2.52,64.13,26.68,107.91,64652.0,94680.0,242324.0,1641.55,19.75,70.0,M-SC,20.37,220.0,1.46,1.57,82.31,OX40N,ATH,CABLES
27,GLAXO,4.30,20.48,12.63,35.69,30323.0,40804.0,240088.0,3380.16,-9.68,86.0,X-MC,9.81,56.0,1.35,1.56,42.69,X40,ATH,PHARMA

In [15]:
# top 5 to monitor for exit
df_tmp = df_portfolio_features[~df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])]
df_tmp = df_tmp[(df_tmp['Current P/L%'] > 0) ].sort_values(by = 'Dev%_PE', ascending=False)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
25,FINCABLES,-2.52,64.13,26.68,107.91,64652.0,94680.0,242324.0,1641.55,19.75,70.0,M-SC,20.37,220.0,1.46,1.57,82.31,OX40N,ATH,CABLES
68,STARHEALTH,-0.36,12.65,30.72,47.26,97287.0,35567.0,316690.0,761.00,-0.61,49.0,H-SC,16.22,173.0,0.37,2.06,36.93,XY24,NTT,INSURANCE

In [16]:
# top 5 to book for rotation from weak conviction
df_tmp = df_portfolio_features[~df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])]
df_tmp = df_tmp[~df_tmp['Criteria'].isin(['XY25','XY24','X40', 'X40N'])].sort_values(by = 'RRR Ind', ascending=False)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
25,FINCABLES,-2.52,64.13,26.68,107.91,64652.0,94680.0,242324.0,1641.55,19.75,70.0,M-SC,20.37,220.0,1.46,1.57,82.31,OX40N,ATH,CABLES
3,ALKYLAMINE,2.93,-15.83,128.74,92.54,109410.0,-15978.0,84985.0,4520.85,NaN,62.0,NaN,14.23,142.0,-0.15,0.55,61.38,SR,ATH,CHEMICALS
67,SIS,0.07,-4.29,26.69,21.26,28364.0,-4761.0,106271.0,528.00,104.27,39.0,H-SC,21.60,168.0,-0.17,0.69,58.01,OX40N,NTT,MISC
42,INDIAMART,-1.02,-25.43,169.46,100.92,155846.0,-31370.0,91966.0,4675.60,NaN,34.0,NaN,13.91,140.0,-0.20,0.60,0.00,AR,ATH,MISC
71,TANLA,-0.39,-35.07,234.61,117.25,412437.0,-94964.0,175797.0,1922.32,NaN,46.0,NaN,15.74,147.0,-0.23,1.14,53.91,AR,ATH,IT

In [17]:
# top 5 to accumulate based on lowest RSI_14
df_tmp = df_portfolio_features[df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])].sort_values(by = 'RSI_14', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
19,COLPAL,-1.75,-29.01,97.01,39.86,181380.0,-76395.0,186970.0,3683.41,-14.08,27.0,X-MC,1.69,62.0,-0.42,1.21,5.76,XY25,ATH,FMCG
47,ITC,-0.76,-26.08,68.69,24.70,201724.0,-103605.0,293673.0,452.00,-31.16,29.0,X-LC,10.67,1.0,-0.51,1.91,0.00,X40,NTT,FMCG
56,PGHH,-1.15,-38.04,113.06,32.01,149574.0,-81224.0,132296.0,17616.87,-54.51,29.0,X-SC,19.66,57.0,-0.54,0.86,0.00,X40,ATH,FMCG
55,PAGEIND,-1.26,-6.70,42.40,32.85,106165.0,-17989.0,250390.0,50936.07,-30.68,30.0,X-MC,8.55,55.0,-0.17,1.63,19.57,X40,ATH,APPARELS
34,HDFCBANK,-0.38,-12.03,48.98,31.05,126295.0,-35270.0,257850.0,1073.00,-29.01,32.0,X-LC,12.88,26.0,-0.28,1.67,0.08,X40,BTT,BANKS

In [18]:
# top 5 to accumulate based on Spread and CumlRnk
df_tmp = df_portfolio_features[df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])]
df_tmp = df_tmp[(df_tmp['CumlRnk'] < 100)].sort_values(by = 'Spread%', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
19,COLPAL,-1.75,-29.01,97.01,39.86,181380.0,-76395.0,186970.0,3683.41,-14.08,27.0,X-MC,1.69,62.0,-0.42,1.21,5.76,XY25,ATH,FMCG
50,KOTAKBANK,0.48,2.37,16.16,18.92,39654.0,5683.0,245385.0,452.46,-13.30,49.0,X-LC,2.32,12.0,0.14,1.59,10.41,X40,ATH,BANKS
23,DMART,0.30,-2.33,34.55,31.42,105216.0,-7258.0,304532.0,5391.45,-18.14,49.0,X-LC,2.35,14.0,-0.07,1.98,9.89,X40N,ATH,FMCG
26,GILLETTE,-1.14,-11.58,46.72,29.72,104882.0,-29406.0,224490.0,10978.86,-36.19,35.0,X-SC,3.56,83.0,-0.28,1.46,3.16,X40,ATH,FMCG
1,ABBOTINDIA,-2.04,-11.59,30.49,15.37,48214.0,-20725.0,158130.0,34390.26,-27.99,36.0,X-MC,4.04,58.0,-0.43,1.03,7.12,X40,ATH,PHARMA

In [19]:
# top 5 to accumulate based on lowest Gained%
df_tmp = df_portfolio_features[df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])].sort_values(by = 'Gained%', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
20,DABUR,-0.66,-21.63,83.36,43.70,162062.0,-53656.0,194412.0,735.00,-32.48,33.0,X-MC,10.15,70.0,-0.33,1.26,0.00,XY24,BTT,FMCG
36,HINDUNILVR,-0.71,-15.94,44.62,21.56,126217.0,-53647.0,282870.0,2922.00,-42.16,37.0,X-LC,6.40,9.0,-0.43,1.84,0.00,XY25,NTT,FMCG
47,ITC,-0.76,-26.08,68.69,24.70,201724.0,-103605.0,293673.0,452.00,-31.16,29.0,X-LC,10.67,1.0,-0.51,1.91,0.00,X40,NTT,FMCG
56,PGHH,-1.15,-38.04,113.06,32.01,149574.0,-81224.0,132296.0,17616.87,-54.51,29.0,X-SC,19.66,57.0,-0.54,0.86,0.00,X40,ATH,FMCG
34,HDFCBANK,-0.38,-12.03,48.98,31.05,126295.0,-35270.0,257850.0,1073.00,-29.01,32.0,X-LC,12.88,26.0,-0.28,1.67,0.08,X40,BTT,BANKS

In [20]:
# top 5 to accumulate based on lowest CurrAlloc%
df_tmp = df_portfolio_features[df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])].sort_values(by = 'CurrAlloc%', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
56,PGHH,-1.15,-38.04,113.06,32.01,149574.0,-81224.0,132296.0,17616.87,-54.51,29.0,X-SC,19.66,57.0,-0.54,0.86,0.00,X40,ATH,FMCG
2,ACC,-1.21,-42.36,203.26,74.81,314159.0,-113568.0,154560.0,3906.00,-42.69,33.0,X-SC,11.43,85.0,-0.36,1.00,3.26,XY24,BTT,CEMENT
1,ABBOTINDIA,-2.04,-11.59,30.49,15.37,48214.0,-20725.0,158130.0,34390.26,-27.99,36.0,X-MC,4.04,58.0,-0.43,1.03,7.12,X40,ATH,PHARMA
40,ICICIPRULI,-1.23,-17.14,57.22,30.28,93408.0,-33761.0,163244.0,787.27,-46.81,46.0,X-MC,12.47,78.0,-0.36,1.06,8.76,X40,ATH,INSURANCE
39,ICICIGI,-0.22,-14.04,38.31,18.89,65895.0,-28103.0,172006.0,2244.41,-14.33,40.0,X-MC,10.52,66.0,-0.43,1.12,2.48,X40,ATH,INSURANCE

In [21]:
# top 5 to accumulate based on CumlRnk
df_tmp = df_portfolio_features.sort_values(by = 'CumlRnk', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
47,ITC,-0.76,-26.08,68.69,24.70,201724.0,-103605.0,293673.0,452.00,-31.16,29.0,X-LC,10.67,1.0,-0.51,1.91,0.00,X40,NTT,FMCG
73,TCS,-0.08,-33.12,85.71,24.20,265548.0,-153451.0,309822.0,4230.71,-44.31,46.0,X-LC,14.30,2.0,-0.58,2.01,15.53,X40,ATH,IT
45,INFY,0.35,-20.35,76.24,40.38,228617.0,-76605.0,299865.0,1972.00,-41.25,47.0,X-LC,15.84,3.0,-0.34,1.95,13.56,X40,NTT,IT
75,TMPV,0.12,-23.10,85.64,42.75,274021.0,-96139.0,319968.0,600.00,-84.91,36.0,X-LC,4.51,4.0,-0.35,2.08,10.02,XY24,NTT,AUTO
33,HCLTECH,1.54,-11.85,40.62,23.97,110822.0,-36660.0,272826.0,1853.42,-14.26,55.0,X-LC,11.32,8.0,-0.33,1.77,28.74,X40,ATH,IT

In [22]:
# top 5 for average up
df_tmp = df_portfolio_features[(df_portfolio_features['Dev%_200'] > 5)].sort_values(by = 'CurrAlloc%', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
44,INDUSINDBK,-0.13,-25.49,78.34,32.89,45069.0,-19676.0,57530.0,1800.00,323.79,50.0,L-MC,12.73,258.0,-0.44,0.37,41.84,XR,NTT,BANKS
3,ALKYLAMINE,2.93,-15.83,128.74,92.54,109410.0,-15978.0,84985.0,4520.85,NaN,62.0,NaN,14.23,142.0,-0.15,0.55,61.38,SR,ATH,CHEMICALS
12,BOSCH-HCIL,1.89,-24.08,31.71,-0.01,30767.0,-30779.0,97026.0,2282.00,758.45,77.0,M-SC,6.67,231.0,-1.00,0.63,65.15,OX40N,BTT,AC
81,VALIANTORG,0.55,-35.58,170.32,74.15,179517.0,-58205.0,105400.0,838.00,NaN,58.0,NaN,7.09,145.0,-0.32,0.68,56.85,XR,NTT,CHEMICALS
67,SIS,0.07,-4.29,26.69,21.26,28364.0,-4761.0,106271.0,528.00,104.27,39.0,H-SC,21.60,168.0,-0.17,0.69,58.01,OX40N,NTT,MISC

In [23]:
# top 5 RSP
df_tmp = df_portfolio_features.sort_values(by = 'RSP', ascending=False)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
12,BOSCH-HCIL,1.89,-24.08,31.71,-0.01,30767.0,-30779.0,97026.0,2282.00,758.45,77.0,M-SC,6.67,231.0,-1.00,0.63,65.15,OX40N,BTT,AC
25,FINCABLES,-2.52,64.13,26.68,107.91,64652.0,94680.0,242324.0,1641.55,19.75,70.0,M-SC,20.37,220.0,1.46,1.57,82.31,OX40N,ATH,CABLES
27,GLAXO,4.30,20.48,12.63,35.69,30323.0,40804.0,240088.0,3380.16,-9.68,86.0,X-MC,9.81,56.0,1.35,1.56,42.69,X40,ATH,PHARMA
81,VALIANTORG,0.55,-35.58,170.32,74.15,179517.0,-58205.0,105400.0,838.00,NaN,58.0,NaN,7.09,145.0,-0.32,0.68,56.85,XR,NTT,CHEMICALS
38,HYUNDAI,0.55,13.70,26.60,43.94,76010.0,34421.0,285753.0,2782.73,17.86,64.0,X-LC,5.31,29.0,0.45,1.86,31.20,X40N,ATH,AUTO

In [24]:
# Top N allocation
df_tmp = df_portfolio_features.sort_values(by = 'CurrAlloc%', ascending=False)
top_n_values = [10, 25, 50]

sum_df = pd.DataFrame({
    'Top_N': top_n_values,
    'Sum_Alloc%': [df_tmp['CurrAlloc%'].head(n).sum() for n in top_n_values]
})

sum_df

   Top_N  Sum_Alloc%
0     10       19.74
1     25       45.03
2     50       77.65

In [25]:
# market-cap-wise allocation
df_tmp = df_portfolio_features[cols]
df_tmp.groupby(df_tmp['Conviction'].str[-2:])['CurrAlloc%'].sum().sort_values(ascending=False)

Conviction
LC    38.03
MC    22.27
SC    21.56
Name: CurrAlloc%, dtype: float64

In [26]:
# criteria-wise allocation
df_portfolio_features.groupby('Criteria')['CurrAlloc%'].sum().sort_values(ascending=False)

Criteria
X40      26.67
XY24     24.01
X40N     18.69
XR        9.09
OX40N     7.35
XY25      7.19
AR        6.13
SR        0.88
Name: CurrAlloc%, dtype: float64

In [27]:
# conviction-wise allocation
df_portfolio_features.groupby('Conviction')['CurrAlloc%'].sum().sort_values(ascending=False)

Conviction
X-LC    34.36
X-MC    19.65
H-SC     8.52
X-SC     7.61
M-SC     5.43
H-LC     2.86
M-MC     1.21
H-MC     1.04
M-LC     0.81
L-MC     0.37
Name: CurrAlloc%, dtype: float64

In [28]:
# sector-wise stats
df_tmp = df_portfolio_features.groupby('Category')[['CurrAlloc%', 'Current', 'Current P/L', 'FTT Amt']].sum().sort_values(by=['Current', 'Current P/L'], ascending=False)
df_tmp['Current P/L%'] = round(df_tmp['Current P/L'] * 100 / df_tmp['Current'], 2)
df_tmp['FTT%'] = round(df_tmp['FTT Amt'] * 100 / df_tmp['Current'], 2)
cols = ['CurrAlloc%', 'Current P/L%', 'FTT%']
df_tmp[cols].sort_values(by=['CurrAlloc%'], ascending=False)

               CurrAlloc%  Current P/L%    FTT%
Category
FMCG                15.41        -25.67   70.86
IT                  11.17        -38.56  107.28
FINANCE             10.83        -15.83   65.73
AUTO                 8.31         -5.79   43.68
BANKS                6.10        -13.34   62.22
MISC                 5.99        -34.00   87.90
PHARMA               5.88          8.30   17.70
INSURANCE            5.74         -5.13   42.31
PAINTS               5.47        -17.04   37.00
ELECTRICAL           4.18         -9.76   44.12
AC                   1.82        -13.83   44.70
REFINERIES           1.74        -11.11   48.43
BREWERIES            1.70         10.44    8.16
FOOTWEAR             1.66        -72.49  141.65
APPARELS             1.63         -7.18   42.40
CABLES               1.57         39.07   26.68
DURABLES             1.46        -71.14  112.77
TRAVEL               1.43       -104.24  206.51
CERAMICS             1.33        -49.26   94.61
ENGINEERING          1.24        -26.59   84.49
CHEMICALS            1.23        -38.96  151.76
CEMENT               1.00        -73.48  203.26
JEWELLERY            0.96       -116.59  191.85
HEALTHCARE           0.70        -68.62  110.94
ENTERTAINMENT        0.70        -80.55  188.23
TEXTILES             0.39        -53.01   96.64
HOTELS               0.37       -100.27  170.91

In [29]:
# money to be made criteria-wise
df_portfolio_features.groupby('Criteria')['FTT Amt'].agg(['sum', 'count']).sort_values(by='sum', ascending=False)

                sum  count
Criteria
XY24      3632150.0     19
X40       2117932.0     18
XR        1395314.0     13
X40N      1205090.0     12
AR        1062834.0      8
OX40N      657313.0     10
XY25       591012.0      5
SR         279990.0      2

In [30]:
# money to be made conviction-wise
df_portfolio_features.groupby('Conviction')['FTT Amt'].agg(['sum', 'count']).sort_values(by='sum', ascending=False)

                  sum  count
Conviction
X-LC        2436384.0     19
X-MC        1476884.0     14
X-SC        1107532.0      6
H-SC         838110.0      8
M-SC         328156.0      6
H-MC         254205.0      1
M-LC         167163.0      1
M-MC          58776.0      1
H-LC          50145.0      2
L-MC          45069.0      1

In [31]:
# money to be made criteria and conviction-wise
df_portfolio_features.groupby(['Conviction', 'Criteria'])['FTT Amt'].agg(['sum', 'count']).sort_values(by='sum', ascending=False)

                           sum  count
Conviction Criteria
X-LC       X40       1242678.0      9
X-SC       XY24       678149.0      2
H-SC       XY24       532112.0      3
X-MC       X40        506434.0      6
           X40N       463107.0      4
X-LC       XY24       458615.0      2
           X40N       417117.0      5
X-MC       XY25       276091.0      2
X-LC       XY25       256145.0      2
X-SC       X40        254456.0      2
H-MC       XY24       254205.0      1
X-MC       XY24       231252.0      2
H-SC       OX40N      211533.0      3
X-SC       X40N       174927.0      2
M-LC       XR         167163.0      1
M-SC       OX40N      151880.0      4
           XY24       118009.0      1
H-SC       XR          94465.0      2
X-LC       XR          61829.0      1
M-MC       XY25        58776.0      1
M-SC       XR          58267.0      1
H-LC       AR          50145.0      2
L-MC       XR          45069.0      1

In [32]:
# notebook execution time

end_time = time.time()
execution_time = round(end_time - start_time, 0)
print(f"Notebook execution time: {execution_time} seconds")

Notebook execution time: 30.0 seconds