<a href="https://colab.research.google.com/github/ankit-rathi/Quantvesting_v2/blob/main/myStocks_Portfolio_Analysis.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
'''
!pip install pandas==2.2.2 -qq
!pip install pyxirr -qq
!pip install ta -qq
!pip install yfinance==0.2.59 -qq
'''

'\n!pip install pandas==2.2.2 -qq\n!pip install pyxirr -qq\n!pip install ta -qq\n!pip install yfinance==0.2.59 -qq\n'

In [2]:
# import libraries

import numpy as np
import pandas as pd
import datetime
import warnings
warnings.filterwarnings('ignore')
import yfinance as yfin
import ta
import matplotlib.pyplot as plt
import requests

In [3]:
# notebook start time
import time
import datetime
import pytz

start_time = time.time()

# function to print date timestamp
def print_date_time():
  tz_NY = pytz.timezone('Asia/Kolkata')
  datetime_NY = datetime.datetime.now(tz_NY)
  print("Run date time (IST):", datetime_NY.strftime("%Y-%m-%d %H:%M:%S"))

In [4]:
# function to get booked and reserved amount
def get_amt():
  # fetch the JSON data from the URL
  url = "https://raw.githubusercontent.com/ankit-rathi/Tradevesting_v1/main/data/myPortfolioAmts.json"
  response = requests.get(url)
  pf_amts = response.json()  # parse the JSON data

  # extract values from the JSON
  py_booked_amt_dm = pf_amts["py_booked_amt_dm"]
  py_booked_amt_sv = pf_amts["py_booked_amt_sv"]
  cy_booked_amt_dm = pf_amts["cy_booked_amt_dm"]
  cy_booked_amt_sv = pf_amts["cy_booked_amt_sv"]
  reserve_amt_dm = pf_amts["reserve_amt_dm"]
  reserve_amt_sv = pf_amts["reserve_amt_sv"]

  # perform calculations
  py_booked_amt = py_booked_amt_dm + py_booked_amt_sv
  cy_booked_amt = cy_booked_amt_dm + cy_booked_amt_sv
  reserve_amt = reserve_amt_dm + reserve_amt_sv
  total_booked_amt = py_booked_amt + cy_booked_amt

  return total_booked_amt, reserve_amt, cy_booked_amt, py_booked_amt

gen_output = 0

In [5]:
# function to format the amount
def format_amt(number):
    abs_number = abs(number)

    if abs_number >= 1_00_00_000:  # Crores
        formatted_amt = f"{number / 1_00_00_000:.2f} C"
    elif abs_number >= 1_00_000:  # Lakhs
        formatted_amt = f"{number / 1_00_000:.2f} L"
    elif abs_number >= 1_000:  # Thousands
        formatted_amt = f"{number / 1_000:.2f} K"
    else:
        formatted_amt = f"{number:.2f}"

    return formatted_amt

# function to set start and end date
def get_start_end_date():
  start_date = (datetime.date.today() + datetime.timedelta(days=-365)).strftime('%Y-%m-%d')
  end_date = (datetime.date.today() + datetime.timedelta(days=1)).strftime('%Y-%m-%d')
  return start_date, end_date

# function to fetch my portfolio csv
def get_mypfs_df():
  mypfs_df = pd.read_csv('https://raw.githubusercontent.com/ankit-rathi/Tradevesting_v1/main/data/myPortfolioStocks.csv')
  return mypfs_df

# function to fetch my prospects csv
def get_mypps_df():
  mypps_df = pd.read_csv('https://raw.githubusercontent.com/ankit-rathi/Tradevesting_v1/main/data/myProspectsScrips.csv')
  return mypps_df

# function to fetch screener data
def get_myscreen_df():
  myscreen_df = pd.read_csv('https://raw.githubusercontent.com/ankit-rathi/Tradevesting_v1/main/data/myScreenerDB.csv')
  return myscreen_df

# function to fetch momentum data
def get_myinvmt_df():
  myinvmt_df = pd.read_csv('https://raw.githubusercontent.com/ankit-rathi/Tradevesting_v1/main/data/myInvestments.csv')
  return myinvmt_df

# function to get the stock ids
def get_stock_ids(df_pf):
  stock_n100 = df_pf['Symbol'].unique()

  exclude = ['CADILAHC','MMTC', 'MASFIN']

  stock_ids = df_pf[~df_pf['Symbol'].isin(exclude) ]['Symbol'].unique()

  #mypf = mypf[mypf.Forecast.notnull()]
  #stock_ids = mypf['Symbol'].unique()

  #stock_ids.sort()
  return stock_ids

# get features from screener data
def get_screener_features():
  myscreen_df = get_myscreen_df()
  cols = ['Symbol', 'EPS', 'MedPE', 'ROCE%', 'ROE%', 'CapType']
  return myscreen_df[cols]

# get relative strength
def get_relative_strength(stock_list):

    # Dictionary to store stock tickers and their corresponding percentage price change
    stock_changes = {}

    # Loop through each stock and fetch its price data
    for stock in stock_list:
        try:
            # Download the stock data for the given date range
            stock_data = yfin.Ticker(stock + '.NS').history(period='1mo', interval='1d')[map(str.title, ['open', 'close', 'low', 'high', 'volume'])]

            # Calculate the percentage change for the stock
            if len(stock_data) > 0:
                start_price = stock_data['Close'].iloc[0]
                end_price = stock_data['Close'].iloc[-1]
                percent_change = round(((end_price - start_price) / start_price) * 100, 2)
                stock_changes[stock] = percent_change
            else:
                stock_changes[stock] = np.nan  # If no data is available, set to NaN

        except Exception as e:
            print(f"Error fetching data for {stock}: {e}")
            stock_changes[stock] = np.nan

    # Create a DataFrame with stock tickers and their percentage changes
    df = pd.DataFrame(list(stock_changes.items()), columns=['Symbol', 'Percent_Change'])

    # Drop any stocks with missing data (NaN values)
    df = df.dropna()

    # Calculate the percentile rank based on percentage change
    df['RSP'] = round(df['Percent_Change'].rank(pct=True) * 100, 2)
    cols = ['Symbol', 'RSP']
    df = df[cols]
    # Sort by percentile rank (optional)
    df = df.sort_values(by='RSP', ascending=False).reset_index(drop=True)

    return df

In [6]:
# function to get stock technicals
def stock_prec_dev(stock_symbol):
    #stock_symbol = 'ULTRACEMCO.NS'
    short_window = 20
    mid_window = 50
    long_window = 200
    moving_avg = 'SMA'

    start = datetime.datetime(*map(int, start_date.split('-')))
    end = datetime.datetime(*map(int, end_date.split('-')))

    stock_df = yfin.Ticker(stock_symbol + '.NS').history(period='max', interval='1d')[map(str.title, ['open', 'close', 'low', 'high', 'volume'])]

    stock_df['Max'] = round(max(stock_df['Close']),2)
    stock_df = stock_df[(stock_df.index <= end_date) & (stock_df.index >= start_date)]
    stock_df['200_SMA'] = round(stock_df['Close'].rolling(window = 200, min_periods = 1).mean(),0)
    stock_df['Dev%_200'] = round((stock_df['Close'] - stock_df['200_SMA'])*100/stock_df['200_SMA'],2)
    stock_df.dropna(axis = 0, inplace = True) # remove any null rows

    stock_df['20_SMA'] = stock_df['Close'].rolling(window=20).mean()
    stock_df['50_SMA'] = stock_df['Close'].rolling(window=50).mean()
    stock_df['Symbol'] = stock_symbol

    stock_df['Close'] = round(stock_df['Close'],2)
    stock_df['Min'] = round(min(stock_df['Close']),2)
    stock_df['RSI_14'] = ta.momentum.RSIIndicator(close=stock_df['Close'], window=14).rsi()
    stock_df['RSI_14'] = round(stock_df['RSI_14'],0)
    stock_df['Prev_Close'] = stock_df['Close'].shift(1)
    stock_df.drop(['Open', 'Low', 'High', 'Volume'], axis=1, inplace=True)
    stock_df = stock_df.tail(1)

    max_SMA = max(stock_df['20_SMA'].item(), stock_df['50_SMA'].item(), stock_df['200_SMA'].item())
    min_SMA = min(stock_df['20_SMA'].item(), stock_df['50_SMA'].item(), stock_df['200_SMA'].item())
    ABS_Spread = max_SMA - min_SMA
    stock_df['Spread%'] = round((ABS_Spread / stock_df['200_SMA'].item()) * 100,2)

    return stock_df

# function to compute stock attributes
def get_common_features(stock_ids, df_mypf):

  df_prec_dev = pd.DataFrame()
  df_tmp = get_screener_features()
  df_rs = get_relative_strength(stock_ids)

  for stock_id in stock_ids:
      tmp = stock_prec_dev(stock_id)
      tmp = tmp.reset_index()
      df_prec_dev = pd.concat([df_prec_dev, tmp], ignore_index = True)
  df_prec_dev = pd.merge(df_prec_dev, df_mypf, on= 'Symbol')
  df_prec_dev = pd.merge(df_prec_dev, df_tmp, on= 'Symbol', how='left')
  df_prec_dev = pd.merge(df_prec_dev, df_rs, on= 'Symbol', how='left')
  #print(df_prec_dev.columns)
  df_prec_dev['Curr_PE'] = round(df_prec_dev['Close']/df_prec_dev['EPS'],1)
  df_prec_dev['Dev%_PE'] = round((df_prec_dev['Curr_PE'] - df_prec_dev['MedPE'])*100/df_prec_dev['MedPE'],2)
  df_prec_dev['Conviction'] = df_prec_dev['Conviction'] + '-' + df_prec_dev['CapType']
  return df_prec_dev

# function to arrange stock features
def arrange_features(df_stocks, common_cols, diff_cols):
  df_stocks_common = df_stocks[common_cols].drop_duplicates()
  df_stocks_diff = df_stocks[diff_cols]
  df_stocks_diff['Investment'] = df_stocks_diff['AvgCost'] * df_stocks_diff['Shares']
  df_stocks_diff = df_stocks_diff.groupby(['Symbol'])[['Shares', 'Investment']].aggregate(['sum']).reset_index()
  df_stocks_diff.columns = ['Symbol', 'Shares', 'Investment']
  df_stocks_diff['AvgCost'] = round(df_stocks_diff['Investment']/df_stocks_diff['Shares'],2)
  df_stocks = pd.merge(df_stocks_diff, df_stocks_common, on='Symbol')
  return df_stocks

# plot fact distribution across dimension
def plot_pie_chart(df, dimension, fact):
  # grouping the data by category and calculating the sum of fact for each type
  grouped_data = df.groupby(dimension)[fact].sum()

  # sorting the grouped data in descending order
  grouped_data = grouped_data.sort_values(ascending=False)

  # creating a pie chart
  grouped_data.plot.pie(autopct='%1.1f%%', startangle=90, figsize=(6, 6))

  # adding a title and displaying the plot
  plt.title(f'{dimension} {fact} Distribution')
  plt.ylabel('')  # To hide the y-label
  plt.show()

In [7]:
# function to get portfolio features

def get_portfolio_features(df_common_features):

  print_date_time()
  print('-------------------')

  #df_common_features["Target"] = df_common_features["Target"].fillna(df_common_features["Max"])
  df_common_features['NTT'] = np.where(df_common_features['Strategy']== 'NTT', df_common_features["Target"], df_common_features['Max'])
  df_common_features['LTT'] = np.where(df_common_features['Strategy']== 'BTT', df_common_features["Target"], df_common_features['Max'])
  df_common_features['BOL'] = df_common_features['Min']

  tmp_df = df_common_features[df_common_features['Symbol'].isin(mypf_df[mypf_df['InPortfolio'] != 'NA'].Symbol.values)]
  print('qualified stocks: '+str(len(tmp_df['Symbol'].unique())))
  tmp_df1 = tmp_df[tmp_df['LatestQtr'] == 1]
  print('with latest results: '+str(len(tmp_df1['Symbol'].unique())))
  tmp_df1 = tmp_df1[tmp_df1['StarStock'] == 1]
  print('still star stocks: '+str(len(tmp_df1['Symbol'].unique())))
  tmp_df['Investment'] = tmp_df['AvgCost'] * tmp_df['Shares']
  tmp_df['Current'] = round(tmp_df['Close'] * tmp_df['Shares'],0)
  tmp_df['Previous'] = tmp_df['Prev_Close'] * tmp_df['Shares']
  tmp_df['EstimatedST'] = tmp_df['NTT'] * tmp_df['Shares']
  tmp_df['EstimatedLT'] = tmp_df['LTT'] * tmp_df['Shares']
  tmp_df['Current P/L'] = round((tmp_df['Current'] - tmp_df['Investment']),0)
  tmp_df['Today P/L%'] = round((tmp_df['Current'] - tmp_df['Previous'])*100/tmp_df['Previous'],2)
  tmp_df['Current P/L%'] = round((tmp_df['Current'] - tmp_df['Investment'])*100/tmp_df['Investment'],2)
  tmp_df['EstimatedST P/L%'] = round((tmp_df['EstimatedST'] - tmp_df['Investment'])*100/tmp_df['Investment'],2)
  tmp_df['EstimatedLT P/L%'] = round((tmp_df['EstimatedLT'] - tmp_df['Investment'])*100/tmp_df['Investment'],2)
  tmp_df['NTT%'] = round((tmp_df['NTT'] - tmp_df['Close'])*100/tmp_df['Close'],2)
  tmp_df['LTT%'] = round((tmp_df['LTT'] - tmp_df['Close'])*100/tmp_df['Close'],2)
  tmp_df['Gained%'] = round((tmp_df['Close'] - tmp_df['BOL'])*100/tmp_df['BOL'],2)
  investment = round(sum(tmp_df['AvgCost']*tmp_df['Shares']),0)
  current = round(sum(tmp_df['Close']*tmp_df['Shares']),0)
  tmp_df['InitAlloc%'] = round(tmp_df['Investment']*100/investment,2)
  tmp_df['CurrAlloc%'] = round(tmp_df['Current']*100/current,2)
  tmp_df['FTT'] = tmp_df['LTT']
  tmp_df.loc[tmp_df['Strategy'] == 'NTT', 'FTT'] = tmp_df['NTT']
  tmp_df['FTT%'] = tmp_df['LTT%']
  tmp_df.loc[tmp_df['Strategy'] == 'NTT', 'FTT%'] = tmp_df['NTT%']
  tmp_df['FTT Amt'] = round(tmp_df['FTT%'] * tmp_df['Current']/100,0)
  tmp_df['OTT%'] = round((tmp_df['FTT'] - tmp_df['AvgCost'])*100/tmp_df['AvgCost'],2)
  tmp_df['RRR Ind'] = round(tmp_df['Current P/L']/tmp_df['FTT Amt'],2)
  tmp_df['Risk Ind'] = round(tmp_df['Current P/L%']*tmp_df['CurrAlloc%'],0)

  return tmp_df

# function to print portfolio features
def print_portfolio_stats(df_portfolio_features, myinvmt_df):
  from pyxirr import xirr

  total_booked_amt, reserve_amt, cy_booked_amt, py_booked_amt = get_amt()

  dates = myinvmt_df['Date'].values
  dates = np.append(dates, datetime.date.today().strftime('%d-%b-%y'))
  investment = myinvmt_df['Investment'].values
  dates= pd.to_datetime(dates)

  current = round(sum(df_portfolio_features['Close']*df_portfolio_features['Shares']),0) + reserve_amt
  investment_xirr = np.append(investment, current)
  cagr = round(xirr(pd.DataFrame({"dates": dates, "amounts": investment_xirr}))*100,2)

  investment = -sum(investment)
  invested = round(sum(df_portfolio_features['AvgCost']*df_portfolio_features['Shares']),0) + reserve_amt
  previous = round(sum(df_portfolio_features['Prev_Close']*df_portfolio_features['Shares']),0) + reserve_amt
  cy_invested = investment + py_booked_amt

  today_pnl_amount = current-previous
  today_pnl_percentage = round((current-previous)*100/previous,2)

  curr_pnl_amount = current-invested
  curr_pnl_percentage = round((curr_pnl_amount)*100/(cy_invested),2)

  cy_pnl_amount = cy_booked_amt + curr_pnl_amount
  cy_pnl_percentage = round((cy_pnl_amount)*100/cy_invested,2)

  overall_pnl_amount = total_booked_amt + curr_pnl_amount
  overall_pnl_percentage = round((overall_pnl_amount)*100/investment,2)

  estimate_st = round(sum(df_portfolio_features['FTT']*df_portfolio_features['Shares']),0)  + reserve_amt
  est_st_pnl_amount = estimate_st-current
  est_st_pnl_percentage = round((est_st_pnl_amount)*100/current,2)

  estimate_lt = round(sum(df_portfolio_features['LTT']*df_portfolio_features['Shares']),0)  + reserve_amt
  est_lt_pnl_amount = estimate_lt-current
  est_lt_pnl_percentage = round((est_lt_pnl_amount)*100/current,2)

  total_profit = round(sum(df_portfolio_features[df_portfolio_features['Current P/L%'] > 0]['Current']) - sum(df_portfolio_features[df_portfolio_features['Current P/L%'] > 0]['Investment']),0)
  total_loss = round(sum(df_portfolio_features[df_portfolio_features['Current P/L%'] < 0]['Current']) - sum(df_portfolio_features[df_portfolio_features['Current P/L%'] < 0]['Investment']),0)

  cy_booked_percentage = round((cy_booked_amt)*100/current,2)
  py_booked_percentage = round((py_booked_amt)*100/investment,2)
  total_booked_percentage = round((total_booked_amt)*100/investment,2)

  print('-------------------')
  print('Initial Investment: ', format_amt(investment))
  print('CY Investment: ', format_amt(cy_invested))
  print('Reserve: ', format_amt(reserve_amt))
  print('Current: ',  format_amt(current))
  print('-------------------')
  print('Today PnL: '+ '{} ({}%)'.format(format_amt(today_pnl_amount), today_pnl_percentage))
  print('Current PnL: '+ '{} ({}%)'.format(format_amt(curr_pnl_amount), curr_pnl_percentage))
  print('CY Booked + Current PnL: '+ '{} ({}%)'.format(format_amt(cy_pnl_amount), cy_pnl_percentage))
  print('-------------------')
  print('Total profit: ', format_amt(total_profit))
  print('Total loss: ', format_amt(total_loss))
  print('-------------------')
  print('Total Booked + Current PnL: '+ '{} ({}%)'.format(format_amt(overall_pnl_amount), overall_pnl_percentage))
  print('Total Booked PnL: '+ '{} ({}%)'.format(format_amt(total_booked_amt), total_booked_percentage))
  print('Curr Year Booked PnL: '+ '{} ({}%)'.format(format_amt(cy_booked_amt), cy_booked_percentage))
  print('Prev Year Booked PnL: '+ '{} ({}%)'.format(format_amt(py_booked_amt), py_booked_percentage))
  print('===================')
  print('Est FTT: ',  format_amt(estimate_st))
  print('Est FTT PnL: '+ '{} ({}%)'.format(format_amt(est_st_pnl_amount), est_st_pnl_percentage))

  print('===================')
  print('Deployed: ', format_amt(investment))

  print('Current: ', format_amt(current))

  print('CAGR/XIRR %: '+'{}%'.format(cagr))

In [8]:
# get start and end date
start_date, end_date = get_start_end_date()

# get portfolio and prospects data
mypfs_df = get_mypfs_df()
mypps_df = get_mypps_df()
myinvmt_df = get_myinvmt_df()

# merge above datasets
mypf_df = pd.merge(mypfs_df, mypps_df, on="Symbol")

# seggregate dm and sv portfolio
dm_pf = mypf_df[mypf_df['InPortfolio'] == 'DM']
sv_pf = mypf_df[mypf_df['InPortfolio'] == 'SV']

# build portfolio stock dataframe
dm_stocks = get_stock_ids(dm_pf)
sv_stocks = get_stock_ids(sv_pf)
df_stocks = pd.concat([dm_pf,sv_pf], ignore_index = True)

# arrange common and diff stock features
common_cols = ['Symbol', 'Target', 'Criteria', 'Strategy', 'CumlRnk', 'LatestQtr', 'StarStock', 'Conviction', 'Category', 'InFolio', 'XIRR', 'MBQ']
diff_cols = ['Symbol', 'AvgCost', 'Shares']
df_stocks = arrange_features(df_stocks, common_cols, diff_cols)

# get common features
stock_ids = df_stocks['Symbol'].values
df_common_features = get_common_features(stock_ids, df_stocks)

df_common_features.reset_index(drop=True, inplace=True)
df_common_features.drop(['Date'], axis=1, inplace=True)
# get and print portfolio features
df_portfolio_features = get_portfolio_features(df_common_features)

print_portfolio_stats(df_portfolio_features, myinvmt_df)

df = df_portfolio_features
#plot_pie_chart(df, 'CapType', 'Current')
list_ox40n = list(df[df['MBQ'].str.contains('OX40N', na=False)]['Symbol'].values)

Run date time (IST): 2026-03-24 11:13:20
-------------------
qualified stocks: 86
with latest results: 26
still star stocks: 16
-------------------
Initial Investment:  1.36 C
CY Investment:  1.62 C
Reserve:  1.61 K
Current:  1.27 C
-------------------
Today PnL: 46.66 K (0.37%)
Current PnL: -49.88 L (-30.7%)
CY Booked + Current PnL: -33.99 L (-20.92%)
-------------------
Total profit:  34.73 K
Total loss:  -50.23 L
-------------------
Total Booked + Current PnL: -7.01 L (-5.17%)
Total Booked PnL: 42.87 L (31.64%)
Curr Year Booked PnL: 15.89 L (12.49%)
Prev Year Booked PnL: 26.98 L (19.91%)
===================
Est FTT:  2.48 C
Est FTT PnL: 1.21 C (94.81%)
===================
Deployed:  1.36 C
Current:  1.27 C
CAGR/XIRR %: -3.08%

In [9]:
# top 5 near their targets
cols = ['Symbol', 'Today P/L%', 'Current P/L%', 'FTT%', 'OTT%', 'FTT Amt', 'Current P/L', 'Current', 'FTT', 'Dev%_PE', 'RSI_14','Conviction', 'Spread%',  'CumlRnk', 'RRR Ind', 'CurrAlloc%', 'Gained%', 'Criteria', 'Strategy', 'Category']
df_tmp = df_portfolio_features[~df_portfolio_features['Symbol'].isin(['ENRIN','BLUSPRING','DIGITIDE'])]
df_tmp = df_tmp.sort_values(by = 'FTT Amt', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
50,MASFIN,-0.82,-10.93,36.49,21.57,31845.0,-10710.0,87270.0,397.04,-23.22,38.0,H-SC,2.42,167.0,-0.34,0.69,19.03,XR,ATH,FINANCE
77,TTKPRESTIG,-4.84,-43.54,77.28,0.09,43972.0,-43877.0,56900.0,770.00,32.12,33.0,M-SC,19.22,250.0,-1.00,0.45,0.00,OX40N,NTT,DURABLES
67,SONACOMS,-0.42,-16.46,66.50,39.09,56198.0,-16651.0,84508.0,804.02,-33.84,41.0,M-MC,7.34,193.0,-0.30,0.66,19.55,AR,ATH,AUTO
2,ABBOTINDIA,0.39,-14.17,37.56,18.07,57658.0,-25345.0,153510.0,35195.00,-26.90,36.0,X-MC,10.78,58.0,-0.44,1.21,0.39,X40,ATH,PHARMA
37,ICICIGI,-0.83,-9.53,31.91,19.34,57769.0,-19072.0,181037.0,2252.93,-24.00,23.0,X-MC,3.79,66.0,-0.33,1.42,0.08,X40,ATH,INSURANCE

In [10]:
# top 5 today
df_tmp = df_portfolio_features.sort_values(by = 'Today P/L%', ascending=False)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
4,ALKYLAMINE,4.97,-44.59,249.45,93.63,139550.0,-45020.0,55943.0,4546.37,-40.72,40.0,H-SC,26.03,142.0,-0.32,0.44,4.97,SR,ATH,CHEMICALS
41,INDIGOPNTS,2.81,-47.93,92.10,0.02,83706.0,-83673.0,90886.0,1408.00,38.39,19.0,M-SC,24.41,222.0,-1.00,0.71,2.81,OX40N,NTT,PAINTS
19,COFFEEDAY,2.33,-61.35,249.96,35.27,109710.0,-69658.0,43891.0,80.00,-69.82,26.0,L-SC,26.21,266.0,-0.63,0.34,2.33,XR,NTT,HOTELS
6,ASIANPAINT,2.12,-22.05,59.74,24.52,131997.0,-62487.0,220952.0,3460.25,-21.42,35.0,X-LC,9.94,30.0,-0.47,1.74,2.12,X40,ATH,PAINTS
7,ATULAUTO,2.07,-31.15,111.42,45.57,151228.0,-61404.0,135728.0,844.00,2921.62,37.0,M-SC,4.55,248.0,-0.41,1.07,2.71,XY24,NTT,AUTO

In [11]:
# bottom 5 today
df_tmp = df_portfolio_features.sort_values(by = 'Today P/L%', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
55,RAJESHEXPO,-4.99,-83.61,510.49,0.07,114784.0,-114692.0,22485.0,518.0,724.49,14.0,L-SC,34.55,268.0,-1.00,0.18,0.00,OX40N,NTT,JEWELLERY
77,TTKPRESTIG,-4.84,-43.54,77.28,0.09,43972.0,-43877.0,56900.0,770.0,32.12,33.0,M-SC,19.22,250.0,-1.00,0.45,0.00,OX40N,NTT,DURABLES
21,DABUR,-3.10,-18.40,76.11,43.70,154058.0,-45653.0,202415.0,735.0,-25.93,21.0,X-MC,5.46,70.0,-0.30,1.59,0.00,XY24,BTT,FMCG
76,TRIDENT,-2.87,-34.86,97.29,28.51,58466.0,-32160.0,60095.0,48.0,-16.23,49.0,M-SC,14.18,223.0,-0.55,0.47,10.29,XR,NTT,TEXTILES
80,VALIANTORG,-2.79,-51.21,256.98,74.15,205109.0,-83790.0,79815.0,838.0,-243.48,50.0,H-SC,28.26,145.0,-0.41,0.63,18.78,XR,NTT,CHEMICALS

In [12]:
# top 5 to exit based on CumlRnk
df_tmp = df_portfolio_features[~df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])]
df_tmp = df_tmp[(df_tmp['Current P/L%'] > -1) & (df_tmp['Current P/L%'] < 1)].sort_values(by = 'CumlRnk', ascending=False)
df_tmp[cols].head()

Empty DataFrame
Columns: [Symbol, Today P/L%, Current P/L%, FTT%, OTT%, FTT Amt, Current P/L, Current, FTT, Dev%_PE, RSI_14, Conviction, Spread%, CumlRnk, RRR Ind, CurrAlloc%, Gained%, Criteria, Strategy, Category]
Index: []

In [13]:
# OX40N stocks to exit
df_tmp = df_portfolio_features[(df_portfolio_features['Symbol'].isin(list_ox40n))].sort_values(by = 'Current P/L%', ascending=False)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
26,FINCABLES,1.22,3.67,100.56,107.91,153917.0,5416.0,153060.0,1641.55,-6.65,45.0,M-SC,8.19,220.0,0.04,1.20,15.15,OX40N,ATH,CABLES
66,SIS,0.09,-39.37,100.00,21.26,67320.0,-43712.0,67320.0,528.00,1568.39,28.0,H-SC,14.46,168.0,-0.65,0.53,0.09,OX40N,NTT,MISC
18,CERA,0.29,-39.90,106.15,23.89,112211.0,-70193.0,105710.0,9475.00,-42.00,41.0,H-SC,19.03,153.0,-0.63,0.83,1.59,OX40N,NTT,CERAMICS
72,TATAELXSI,-0.04,-40.49,121.86,32.03,95603.0,-53382.0,78453.0,9161.00,-25.57,35.0,H-SC,21.00,158.0,-0.56,0.62,2.22,OX40N,NTT,IT
77,TTKPRESTIG,-4.84,-43.54,77.28,0.09,43972.0,-43877.0,56900.0,770.00,32.12,33.0,M-SC,19.22,250.0,-1.00,0.45,0.00,OX40N,NTT,DURABLES

In [14]:
# top 5 to book for rotation
df_tmp = df_portfolio_features[(df_portfolio_features['Current P/L%'] > 20) ].sort_values(by = 'CumlRnk', ascending=False)
df_tmp[cols].head()

Empty DataFrame
Columns: [Symbol, Today P/L%, Current P/L%, FTT%, OTT%, FTT Amt, Current P/L, Current, FTT, Dev%_PE, RSI_14, Conviction, Spread%, CumlRnk, RRR Ind, CurrAlloc%, Gained%, Criteria, Strategy, Category]
Index: []

In [15]:
# top 5 to monitor for exit
df_tmp = df_portfolio_features[~df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])]
df_tmp = df_tmp[(df_tmp['Current P/L%'] > 0) ].sort_values(by = 'Dev%_PE', ascending=False)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
26,FINCABLES,1.22,3.67,100.56,107.91,153917.0,5416.0,153060.0,1641.55,-6.65,45.0,M-SC,8.19,220.0,0.04,1.20,15.15,OX40N,ATH,CABLES
1,ABB,0.32,11.20,30.90,45.57,89897.0,29309.0,290928.0,7934.00,-28.55,51.0,H-MC,13.20,125.0,0.33,2.29,29.19,AR,NTT,ELECTRICAL

In [16]:
# top 5 to book for rotation from weak conviction
df_tmp = df_portfolio_features[~df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])]
df_tmp = df_tmp[~df_tmp['Criteria'].isin(['XY25','XY24','X40', 'X40N'])].sort_values(by = 'RRR Ind', ascending=False)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
1,ABB,0.32,11.20,30.90,45.57,89897.0,29309.0,290928.0,7934.00,-28.55,51.0,H-MC,13.20,125.0,0.33,2.29,29.19,AR,NTT,ELECTRICAL
26,FINCABLES,1.22,3.67,100.56,107.91,153917.0,5416.0,153060.0,1641.55,-6.65,45.0,M-SC,8.19,220.0,0.04,1.20,15.15,OX40N,ATH,CABLES
40,INDIAMART,-0.21,-15.50,144.64,106.72,150742.0,-19117.0,104219.0,4810.62,-61.91,30.0,H-SC,11.64,140.0,-0.13,0.82,4.25,AR,ATH,MISC
85,ZYDUSLIFE,0.95,-8.38,48.04,35.63,92239.0,-17569.0,192005.0,1286.17,-20.27,41.0,H-MC,5.45,120.0,-0.19,1.51,6.89,AR,ATH,PHARMA
84,WIPRO,0.52,-22.68,122.80,72.27,160885.0,-38434.0,131014.0,420.00,-30.18,30.0,M-LC,17.84,98.0,-0.24,1.03,0.52,XR,NTT,IT

In [17]:
# top 5 to accumulate based on lowest RSI_14
df_tmp = df_portfolio_features[df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])].sort_values(by = 'RSI_14', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
53,PGHH,-0.86,-29.75,87.91,32.01,131865.0,-63520.0,150000.0,17616.87,-52.50,11.0,X-MC,15.89,57.0,-0.48,1.18,0.00,X40,ATH,FMCG
38,ICICIPRULI,-0.84,-12.83,49.96,30.73,85800.0,-25268.0,171737.0,790.00,-36.28,17.0,X-MC,4.48,78.0,-0.29,1.35,0.00,X40,ATH,INSURANCE
58,RELAXO,-0.24,-67.07,362.54,52.31,173290.0,-97361.0,47799.0,1176.00,-64.96,17.0,X-SC,26.62,92.0,-0.56,0.38,0.00,X40N,NTT,FOOTWEAR
12,BATAINDIA,0.28,-59.52,234.02,35.20,121882.0,-76588.0,52082.0,2096.00,-31.70,18.0,X-SC,31.27,91.0,-0.63,0.41,0.28,X40,NTT,FOOTWEAR
36,HONAUT,-0.42,-29.73,115.34,51.31,156286.0,-57338.0,135500.0,58357.33,-41.61,20.0,X-SC,15.91,90.0,-0.37,1.07,0.00,X40N,ATH,ELECTRICAL

In [18]:
# top 5 to accumulate based on Spread and CumlRnk
df_tmp = df_portfolio_features[df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])]
df_tmp = df_tmp[(df_tmp['CumlRnk'] < 100)].sort_values(by = 'Spread%', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
78,UNITDSPR,2.02,-4.43,26.36,20.77,58986.0,-10372.0,223772.0,1644.00,-15.25,43.0,X-MC,1.72,64.0,-0.18,1.76,2.02,X40N,NTT,BREWERIES
65,SIEMENS,0.39,-19.40,55.72,25.51,83580.0,-36095.0,150000.0,4671.50,26.07,39.0,H-LC,2.79,51.0,-0.43,1.18,10.46,AR,ATH,ELECTRICAL
59,RELIANCE,0.43,-9.25,38.07,25.30,69432.0,-18583.0,182380.0,1952.00,-11.57,51.0,X-LC,3.45,21.0,-0.27,1.43,21.77,XY25,BTT,REFINERIES
37,ICICIGI,-0.83,-9.53,31.91,19.34,57769.0,-19072.0,181037.0,2252.93,-24.00,23.0,X-MC,3.79,66.0,-0.33,1.42,0.08,X40,ATH,INSURANCE
82,VOLTAS,1.19,-0.95,46.59,45.20,88481.0,-1827.0,189915.0,1856.00,13.41,29.0,X-MC,3.86,79.0,-0.02,1.49,5.78,XY25,NTT,AC

In [19]:
# top 5 to accumulate based on lowest Gained%
df_tmp = df_portfolio_features[df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])].sort_values(by = 'Gained%', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
3,ACC,-0.11,-40.55,194.04,74.81,309315.0,-108720.0,159408.0,3906.00,-57.90,24.0,X-SC,17.78,85.0,-0.35,1.25,0.0,XY24,BTT,CEMENT
9,BAJAJHFL,-1.18,-30.70,133.95,62.13,253458.0,-83828.0,189218.0,181.50,-43.03,23.0,X-MC,20.48,60.0,-0.33,1.49,0.0,X40N,ATH,FINANCE
20,COLPAL,-0.24,-29.95,102.02,41.51,188206.0,-78885.0,184480.0,3726.84,-15.27,25.0,X-MC,6.24,62.0,-0.42,1.45,0.0,XY25,ATH,FMCG
21,DABUR,-3.10,-18.40,76.11,43.70,154058.0,-45653.0,202415.0,735.00,-25.93,21.0,X-MC,5.46,70.0,-0.30,1.59,0.0,XY24,BTT,FMCG
45,ITC,-0.31,-23.73,56.10,19.06,145544.0,-80729.0,259437.0,452.00,-58.35,29.0,X-LC,18.68,1.0,-0.55,2.04,0.0,X40,NTT,FMCG

In [20]:
# top 5 to accumulate based on lowest CurrAlloc%
df_tmp = df_portfolio_features[df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])].sort_values(by = 'CurrAlloc%', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
58,RELAXO,-0.24,-67.07,362.54,52.31,173290.0,-97361.0,47799.0,1176.00,-64.96,17.0,X-SC,26.62,92.0,-0.56,0.38,0.00,X40N,NTT,FOOTWEAR
12,BATAINDIA,0.28,-59.52,234.02,35.20,121882.0,-76588.0,52082.0,2096.00,-31.70,18.0,X-SC,31.27,91.0,-0.63,0.41,0.28,X40,NTT,FOOTWEAR
54,QUESS,1.44,-29.33,146.05,73.90,110233.0,-31317.0,75476.0,424.00,-61.98,34.0,X-SC,21.53,80.0,-0.28,0.59,1.44,XY24,NTT,MISC
36,HONAUT,-0.42,-29.73,115.34,51.31,156286.0,-57338.0,135500.0,58357.33,-41.61,20.0,X-SC,15.91,90.0,-0.37,1.07,0.00,X40N,ATH,ELECTRICAL
51,MEDANTA,1.59,-15.74,50.86,27.12,75647.0,-27782.0,148735.0,1486.00,-18.36,29.0,X-SC,12.27,87.0,-0.37,1.17,1.59,XY24,NTT,HEALTHCARE

In [21]:
# top 5 to accumulate based on CumlRnk
df_tmp = df_portfolio_features.sort_values(by = 'CumlRnk', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
45,ITC,-0.31,-23.73,56.10,19.06,145544.0,-80729.0,259437.0,452.00,-58.35,29.0,X-LC,18.68,1.0,-0.55,2.04,0.00,X40,NTT,FMCG
73,TCS,0.44,-29.72,80.08,26.57,260749.0,-137662.0,325611.0,4311.59,-40.35,29.0,X-LC,17.38,2.0,-0.53,2.56,1.62,X40,ATH,IT
43,INFY,1.43,-13.22,54.69,34.24,148501.0,-41356.0,271532.0,1972.00,-31.79,41.0,X-LC,15.20,3.0,-0.28,2.13,4.42,X40,NTT,IT
75,TMPV,0.54,-30.14,95.50,36.58,237402.0,-107252.0,248589.0,600.00,-85.81,33.0,X-LC,6.76,4.0,-0.45,1.95,0.54,XY24,NTT,AUTO
33,HCLTECH,1.25,-10.73,38.72,23.83,83623.0,-25955.0,215969.0,1908.19,-6.12,46.0,X-LC,11.84,8.0,-0.31,1.70,4.86,X40,ATH,IT

In [22]:
# top 5 for average up
df_tmp = df_portfolio_features[(df_portfolio_features['Dev%_200'] > 5)].sort_values(by = 'CurrAlloc%', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
1,ABB,0.32,11.2,30.9,45.57,89897.0,29309.0,290928.0,7934.0,-28.55,51.0,H-MC,13.2,125.0,0.33,2.29,29.19,AR,NTT,ELECTRICAL

In [23]:
# top 5 RSP
df_tmp = df_portfolio_features.sort_values(by = 'RSP', ascending=False)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
30,HAPPSTMNDS,-1.34,-51.64,282.22,84.85,174931.0,-66181.0,61984.0,1480.71,-42.53,51.0,H-SC,26.60,152.0,-0.38,0.49,14.79,AR,ATH,IT
69,SURYODAY,-2.69,-30.51,77.05,23.03,95881.0,-54631.0,124440.0,216.00,35.96,42.0,H-SC,6.47,166.0,-0.57,0.98,21.62,XR,NTT,BANKS
33,HCLTECH,1.25,-10.73,38.72,23.83,83623.0,-25955.0,215969.0,1908.19,-6.12,46.0,X-LC,11.84,8.0,-0.31,1.70,4.86,X40,ATH,IT
26,FINCABLES,1.22,3.67,100.56,107.91,153917.0,5416.0,153060.0,1641.55,-6.65,45.0,M-SC,8.19,220.0,0.04,1.20,15.15,OX40N,ATH,CABLES
1,ABB,0.32,11.20,30.90,45.57,89897.0,29309.0,290928.0,7934.00,-28.55,51.0,H-MC,13.20,125.0,0.33,2.29,29.19,AR,NTT,ELECTRICAL

In [24]:
# Top N allocation
df_tmp = df_portfolio_features.sort_values(by = 'CurrAlloc%', ascending=False)
top_n_values = [10, 25, 50]

sum_df = pd.DataFrame({
    'Top_N': top_n_values,
    'Sum_Alloc%': [df_tmp['CurrAlloc%'].head(n).sum() for n in top_n_values]
})

sum_df

   Top_N  Sum_Alloc%
0     10       20.84
1     25       45.96
2     50       78.19

In [25]:
# market-cap-wise allocation
df_tmp = df_portfolio_features[cols]
df_tmp.groupby(df_tmp['Conviction'].str[-2:])['CurrAlloc%'].sum().sort_values(ascending=False)

Conviction
SC    44.17
MC    30.05
LC    25.76
Name: CurrAlloc%, dtype: float64

In [26]:
# criteria-wise allocation
df_portfolio_features.groupby('Criteria')['CurrAlloc%'].sum().sort_values(ascending=False)

Criteria
XY24     26.84
X40      25.67
X40N     15.11
AR        9.18
XR        8.29
XY25      7.37
OX40N     6.73
SR        0.79
Name: CurrAlloc%, dtype: float64

In [27]:
# conviction-wise allocation
df_portfolio_features.groupby('Conviction')['CurrAlloc%'].sum().sort_values(ascending=False)

Conviction
X-LC    23.55
X-MC    22.58
H-SC    21.51
X-SC    12.21
M-SC     9.93
H-MC     5.10
M-MC     2.02
H-LC     1.18
M-LC     1.03
L-SC     0.52
L-MC     0.35
Name: CurrAlloc%, dtype: float64

In [28]:
# sector-wise stats
df_tmp = df_portfolio_features.groupby('Category')[['CurrAlloc%', 'Current', 'Current P/L', 'FTT Amt']].sum().sort_values(by=['Current', 'Current P/L'], ascending=False)
df_tmp['Current P/L%'] = round(df_tmp['Current P/L'] * 100 / df_tmp['Current'], 2)
df_tmp['FTT%'] = round(df_tmp['FTT Amt'] * 100 / df_tmp['Current'], 2)
cols = ['CurrAlloc%', 'Current P/L%', 'FTT%']
df_tmp[cols].sort_values(by=['CurrAlloc%'], ascending=False)

               CurrAlloc%  Current P/L%    FTT%
Category
FMCG                15.09        -30.08   76.27
FINANCE             13.06        -29.30   81.99
IT                  12.03        -47.17  122.07
MISC                 6.89        -52.86  119.27
ELECTRICAL           6.56        -16.22   60.72
PAINTS               5.12        -51.21   77.46
INSURANCE            4.67        -14.06   53.09
BANKS                4.54        -33.35  101.03
PHARMA               4.16        -11.12   46.09
AUTO                 3.68        -39.53   94.88
AC                   2.03        -23.66   57.19
HEALTHCARE           1.89        -49.03   87.92
TRAVEL               1.80        -95.43  193.29
DURABLES             1.76        -72.44  114.39
BREWERIES            1.76         -4.64   26.36
FOOTWEAR             1.76        -97.21  176.29
APPARELS             1.73        -21.83   63.39
REFINERIES           1.43        -10.19   38.07
REALTY               1.43        -21.66   41.64
CERAMICS             1.37        -75.52  128.85
CEMENT               1.25        -68.20  194.04
CABLES               1.20          3.54  100.56
ENGINEERING          1.09        -74.99  155.02
CHEMICALS            1.07        -94.88  253.88
JEWELLERY            1.05       -140.72  224.35
ENTERTAINMENT        0.75       -102.69  223.59
TEXTILES             0.47        -53.52   97.29
HOTELS               0.34       -158.71  249.96

In [29]:
# money to be made criteria-wise
df_portfolio_features.groupby('Criteria')['FTT Amt'].agg(['sum', 'count']).sort_values(by='sum', ascending=False)

                sum  count
Criteria
XY24      4179446.0     21
X40       1909045.0     16
XR        1436683.0     12
AR        1404353.0     10
X40N      1378053.0     10
OX40N      935962.0     10
XY25       502102.0      5
SR         318185.0      2

In [30]:
# money to be made conviction-wise
df_portfolio_features.groupby('Conviction')['FTT Amt'].agg(['sum', 'count']).sort_values(by='sum', ascending=False)

                  sum  count
Conviction
H-SC        4056693.0     24
X-MC        1860536.0     15
X-LC        1778676.0     13
M-SC        1652719.0     14
X-SC        1629230.0     10
H-MC         430361.0      3
L-SC         224494.0      2
M-LC         160885.0      1
M-MC         128189.0      2
H-LC          83580.0      1
L-MC          58466.0      1

In [31]:
# money to be made criteria and conviction-wise
df_portfolio_features.groupby(['Conviction', 'Criteria'])['FTT Amt'].agg(['sum', 'count']).sort_values(by='sum', ascending=False)

                           sum  count
Conviction Criteria
H-SC       XY24      1419875.0      6
           AR        1001765.0      5
M-SC       XY24       960113.0      6
X-LC       X40        947290.0      7
H-SC       XR         912147.0      7
X-SC       XY24       874752.0      4
X-MC       X40        742878.0      7
           X40N       558209.0      4
X-SC       X40N       535601.0      4
M-SC       OX40N      416457.0      5
H-SC       OX40N      404721.0      4
X-LC       XY24       393719.0      2
H-SC       SR         318185.0      2
X-LC       X40N       284243.0      2
X-MC       XY24       282762.0      2
           XY25       276687.0      2
H-MC       XY24       248225.0      1
X-SC       X40        218877.0      2
M-SC       XR         195475.0      2
H-MC       AR         182136.0      2
M-LC       XR         160885.0      1
X-LC       XY25       153424.0      2
L-SC       OX40N      114784.0      1
           XR         109710.0      1
H-LC       AR          83580.0      1
M-SC       AR          80674.0      1
M-MC       XY25        71991.0      1
L-MC       XR          58466.0      1
M-MC       AR          56198.0      1

In [32]:
# notebook execution time

end_time = time.time()
execution_time = round(end_time - start_time, 0)
print(f"Notebook execution time: {execution_time} seconds")

Notebook execution time: 25.0 seconds