<a href="https://colab.research.google.com/github/ankit-rathi/Quantvesting_v2/blob/main/myStocks_Portfolio_Analysis.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
'''
!pip install pandas==2.2.2 -qq
!pip install pyxirr -qq
!pip install ta -qq
!pip install yfinance==0.2.59 -qq
'''

'\n!pip install pandas==2.2.2 -qq\n!pip install pyxirr -qq\n!pip install ta -qq\n!pip install yfinance==0.2.59 -qq\n'

In [2]:
# import libraries

import numpy as np
import pandas as pd
import datetime
import warnings
warnings.filterwarnings('ignore')
import yfinance as yfin
import ta
import matplotlib.pyplot as plt
import requests

In [3]:
# notebook start time
import time
import datetime
import pytz

start_time = time.time()

# function to print date timestamp
def print_date_time():
  tz_NY = pytz.timezone('Asia/Kolkata')
  datetime_NY = datetime.datetime.now(tz_NY)
  print("Run date time (IST):", datetime_NY.strftime("%Y-%m-%d %H:%M:%S"))

In [4]:
# function to get booked and reserved amount
def get_amt():
  # fetch the JSON data from the URL
  url = "https://raw.githubusercontent.com/ankit-rathi/Tradevesting_v1/main/data/myPortfolioAmts.json"
  response = requests.get(url)
  pf_amts = response.json()  # parse the JSON data

  # extract values from the JSON
  py_booked_amt_dm = pf_amts["py_booked_amt_dm"]
  py_booked_amt_sv = pf_amts["py_booked_amt_sv"]
  cy_booked_amt_dm = pf_amts["cy_booked_amt_dm"]
  cy_booked_amt_sv = pf_amts["cy_booked_amt_sv"]
  reserve_amt_dm = pf_amts["reserve_amt_dm"]
  reserve_amt_sv = pf_amts["reserve_amt_sv"]

  # perform calculations
  py_booked_amt = py_booked_amt_dm + py_booked_amt_sv
  cy_booked_amt = cy_booked_amt_dm + cy_booked_amt_sv
  reserve_amt = reserve_amt_dm + reserve_amt_sv
  total_booked_amt = py_booked_amt + cy_booked_amt

  return total_booked_amt, reserve_amt, cy_booked_amt, py_booked_amt

gen_output = 0

In [5]:
# function to format the amount
def format_amt(number):
    abs_number = abs(number)

    if abs_number >= 1_00_00_000:  # Crores
        formatted_amt = f"{number / 1_00_00_000:.2f} C"
    elif abs_number >= 1_00_000:  # Lakhs
        formatted_amt = f"{number / 1_00_000:.2f} L"
    elif abs_number >= 1_000:  # Thousands
        formatted_amt = f"{number / 1_000:.2f} K"
    else:
        formatted_amt = f"{number:.2f}"

    return formatted_amt

# function to set start and end date
def get_start_end_date():
  start_date = (datetime.date.today() + datetime.timedelta(days=-365)).strftime('%Y-%m-%d')
  end_date = (datetime.date.today() + datetime.timedelta(days=1)).strftime('%Y-%m-%d')
  return start_date, end_date

# function to fetch my portfolio csv
def get_mypfs_df():
  mypfs_df = pd.read_csv('https://raw.githubusercontent.com/ankit-rathi/Tradevesting_v1/main/data/myPortfolioStocks.csv')
  return mypfs_df

# function to fetch my prospects csv
def get_mypps_df():
  mypps_df = pd.read_csv('https://raw.githubusercontent.com/ankit-rathi/Tradevesting_v1/main/data/myProspectsScrips.csv')
  return mypps_df

# function to fetch screener data
def get_myscreen_df():
  myscreen_df = pd.read_csv('https://raw.githubusercontent.com/ankit-rathi/Tradevesting_v1/main/data/myScreenerDB.csv')
  return myscreen_df

# function to fetch momentum data
def get_myinvmt_df():
  myinvmt_df = pd.read_csv('https://raw.githubusercontent.com/ankit-rathi/Tradevesting_v1/main/data/myInvestments.csv')
  return myinvmt_df

# function to get the stock ids
def get_stock_ids(df_pf):
  stock_n100 = df_pf['Symbol'].unique()

  exclude = ['CADILAHC','MMTC', 'MASFIN']

  stock_ids = df_pf[~df_pf['Symbol'].isin(exclude) ]['Symbol'].unique()

  #mypf = mypf[mypf.Forecast.notnull()]
  #stock_ids = mypf['Symbol'].unique()

  #stock_ids.sort()
  return stock_ids

# get features from screener data
def get_screener_features():
  myscreen_df = get_myscreen_df()
  cols = ['Symbol', 'EPS', 'MedPE', 'ROCE%', 'ROE%', 'CapType']
  return myscreen_df[cols]

# get relative strength
def get_relative_strength(stock_list):

    # Dictionary to store stock tickers and their corresponding percentage price change
    stock_changes = {}

    # Loop through each stock and fetch its price data
    for stock in stock_list:
        try:
            # Download the stock data for the given date range
            stock_data = yfin.Ticker(stock + '.NS').history(period='1mo', interval='1d')[map(str.title, ['open', 'close', 'low', 'high', 'volume'])]

            # Calculate the percentage change for the stock
            if len(stock_data) > 0:
                start_price = stock_data['Close'].iloc[0]
                end_price = stock_data['Close'].iloc[-1]
                percent_change = round(((end_price - start_price) / start_price) * 100, 2)
                stock_changes[stock] = percent_change
            else:
                stock_changes[stock] = np.nan  # If no data is available, set to NaN

        except Exception as e:
            print(f"Error fetching data for {stock}: {e}")
            stock_changes[stock] = np.nan

    # Create a DataFrame with stock tickers and their percentage changes
    df = pd.DataFrame(list(stock_changes.items()), columns=['Symbol', 'Percent_Change'])

    # Drop any stocks with missing data (NaN values)
    df = df.dropna()

    # Calculate the percentile rank based on percentage change
    df['RSP'] = round(df['Percent_Change'].rank(pct=True) * 100, 2)
    cols = ['Symbol', 'RSP']
    df = df[cols]
    # Sort by percentile rank (optional)
    df = df.sort_values(by='RSP', ascending=False).reset_index(drop=True)

    return df

In [6]:
# function to get stock technicals
def stock_prec_dev(stock_symbol):
    #stock_symbol = 'ULTRACEMCO.NS'
    short_window = 20
    mid_window = 50
    long_window = 200
    moving_avg = 'SMA'

    start = datetime.datetime(*map(int, start_date.split('-')))
    end = datetime.datetime(*map(int, end_date.split('-')))

    stock_df = yfin.Ticker(stock_symbol + '.NS').history(period='max', interval='1d')[map(str.title, ['open', 'close', 'low', 'high', 'volume'])]

    stock_df['Max'] = round(max(stock_df['Close']),2)
    stock_df = stock_df[(stock_df.index <= end_date) & (stock_df.index >= start_date)]
    stock_df['200_SMA'] = round(stock_df['Close'].rolling(window = 200, min_periods = 1).mean(),0)
    stock_df['Dev%_200'] = round((stock_df['Close'] - stock_df['200_SMA'])*100/stock_df['200_SMA'],2)
    stock_df.dropna(axis = 0, inplace = True) # remove any null rows

    stock_df['20_SMA'] = stock_df['Close'].rolling(window=20).mean()
    stock_df['50_SMA'] = stock_df['Close'].rolling(window=50).mean()
    stock_df['Symbol'] = stock_symbol

    stock_df['Close'] = round(stock_df['Close'],2)
    stock_df['Min'] = round(min(stock_df['Close']),2)
    stock_df['RSI_14'] = ta.momentum.RSIIndicator(close=stock_df['Close'], window=14).rsi()
    stock_df['RSI_14'] = round(stock_df['RSI_14'],0)
    stock_df['Prev_Close'] = stock_df['Close'].shift(1)
    stock_df.drop(['Open', 'Low', 'High', 'Volume'], axis=1, inplace=True)
    stock_df = stock_df.tail(1)

    max_SMA = max(stock_df['20_SMA'].item(), stock_df['50_SMA'].item(), stock_df['200_SMA'].item())
    min_SMA = min(stock_df['20_SMA'].item(), stock_df['50_SMA'].item(), stock_df['200_SMA'].item())
    ABS_Spread = max_SMA - min_SMA
    stock_df['Spread%'] = round((ABS_Spread / stock_df['200_SMA'].item()) * 100,2)

    return stock_df

# function to compute stock attributes
def get_common_features(stock_ids, df_mypf):

  df_prec_dev = pd.DataFrame()
  df_tmp = get_screener_features()
  df_rs = get_relative_strength(stock_ids)

  for stock_id in stock_ids:
      tmp = stock_prec_dev(stock_id)
      tmp = tmp.reset_index()
      df_prec_dev = pd.concat([df_prec_dev, tmp], ignore_index = True)
  df_prec_dev = pd.merge(df_prec_dev, df_mypf, on= 'Symbol')
  df_prec_dev = pd.merge(df_prec_dev, df_tmp, on= 'Symbol', how='left')
  df_prec_dev = pd.merge(df_prec_dev, df_rs, on= 'Symbol', how='left')
  #print(df_prec_dev.columns)
  df_prec_dev['Curr_PE'] = round(df_prec_dev['Close']/df_prec_dev['EPS'],1)
  df_prec_dev['Dev%_PE'] = round((df_prec_dev['Curr_PE'] - df_prec_dev['MedPE'])*100/df_prec_dev['MedPE'],2)
  df_prec_dev['Conviction'] = df_prec_dev['Conviction'] + '-' + df_prec_dev['CapType']
  return df_prec_dev

# function to arrange stock features
def arrange_features(df_stocks, common_cols, diff_cols):
  df_stocks_common = df_stocks[common_cols].drop_duplicates()
  df_stocks_diff = df_stocks[diff_cols]
  df_stocks_diff['Investment'] = df_stocks_diff['AvgCost'] * df_stocks_diff['Shares']
  df_stocks_diff = df_stocks_diff.groupby(['Symbol'])[['Shares', 'Investment']].aggregate(['sum']).reset_index()
  df_stocks_diff.columns = ['Symbol', 'Shares', 'Investment']
  df_stocks_diff['AvgCost'] = round(df_stocks_diff['Investment']/df_stocks_diff['Shares'],2)
  df_stocks = pd.merge(df_stocks_diff, df_stocks_common, on='Symbol')
  return df_stocks

# plot fact distribution across dimension
def plot_pie_chart(df, dimension, fact):
  # grouping the data by category and calculating the sum of fact for each type
  grouped_data = df.groupby(dimension)[fact].sum()

  # sorting the grouped data in descending order
  grouped_data = grouped_data.sort_values(ascending=False)

  # creating a pie chart
  grouped_data.plot.pie(autopct='%1.1f%%', startangle=90, figsize=(6, 6))

  # adding a title and displaying the plot
  plt.title(f'{dimension} {fact} Distribution')
  plt.ylabel('')  # To hide the y-label
  plt.show()

In [7]:
# function to get portfolio features

def get_portfolio_features(df_common_features):

  print_date_time()
  print('-------------------')

  #df_common_features["Target"] = df_common_features["Target"].fillna(df_common_features["Max"])
  df_common_features['NTT'] = np.where(df_common_features['Strategy']== 'NTT', df_common_features["Target"], df_common_features['Max'])
  df_common_features['LTT'] = np.where(df_common_features['Strategy']== 'BTT', df_common_features["Target"], df_common_features['Max'])
  df_common_features['BOL'] = df_common_features['Min']

  tmp_df = df_common_features[df_common_features['Symbol'].isin(mypf_df[mypf_df['InPortfolio'] != 'NA'].Symbol.values)]
  print('qualified stocks: '+str(len(tmp_df['Symbol'].unique())))
  tmp_df1 = tmp_df[tmp_df['LatestQtr'] == 1]
  print('with latest results: '+str(len(tmp_df1['Symbol'].unique())))
  tmp_df1 = tmp_df1[tmp_df1['StarStock'] == 1]
  print('still star stocks: '+str(len(tmp_df1['Symbol'].unique())))
  tmp_df['Investment'] = tmp_df['AvgCost'] * tmp_df['Shares']
  tmp_df['Current'] = round(tmp_df['Close'] * tmp_df['Shares'],0)
  tmp_df['Previous'] = tmp_df['Prev_Close'] * tmp_df['Shares']
  tmp_df['EstimatedST'] = tmp_df['NTT'] * tmp_df['Shares']
  tmp_df['EstimatedLT'] = tmp_df['LTT'] * tmp_df['Shares']
  tmp_df['Current P/L'] = round((tmp_df['Current'] - tmp_df['Investment']),0)
  tmp_df['Today P/L%'] = round((tmp_df['Current'] - tmp_df['Previous'])*100/tmp_df['Previous'],2)
  tmp_df['Current P/L%'] = round((tmp_df['Current'] - tmp_df['Investment'])*100/tmp_df['Investment'],2)
  tmp_df['EstimatedST P/L%'] = round((tmp_df['EstimatedST'] - tmp_df['Investment'])*100/tmp_df['Investment'],2)
  tmp_df['EstimatedLT P/L%'] = round((tmp_df['EstimatedLT'] - tmp_df['Investment'])*100/tmp_df['Investment'],2)
  tmp_df['NTT%'] = round((tmp_df['NTT'] - tmp_df['Close'])*100/tmp_df['Close'],2)
  tmp_df['LTT%'] = round((tmp_df['LTT'] - tmp_df['Close'])*100/tmp_df['Close'],2)
  tmp_df['Gained%'] = round((tmp_df['Close'] - tmp_df['BOL'])*100/tmp_df['BOL'],2)
  investment = round(sum(tmp_df['AvgCost']*tmp_df['Shares']),0)
  current = round(sum(tmp_df['Close']*tmp_df['Shares']),0)
  tmp_df['InitAlloc%'] = round(tmp_df['Investment']*100/investment,2)
  tmp_df['CurrAlloc%'] = round(tmp_df['Current']*100/current,2)
  tmp_df['FTT'] = tmp_df['LTT']
  tmp_df.loc[tmp_df['Strategy'] == 'NTT', 'FTT'] = tmp_df['NTT']
  tmp_df['FTT%'] = tmp_df['LTT%']
  tmp_df.loc[tmp_df['Strategy'] == 'NTT', 'FTT%'] = tmp_df['NTT%']
  tmp_df['FTT Amt'] = round(tmp_df['FTT%'] * tmp_df['Current']/100,0)
  tmp_df['OTT%'] = round((tmp_df['FTT'] - tmp_df['AvgCost'])*100/tmp_df['AvgCost'],2)
  tmp_df['RRR Ind'] = round(tmp_df['Current P/L']/tmp_df['FTT Amt'],2)
  tmp_df['Risk Ind'] = round(tmp_df['Current P/L%']*tmp_df['CurrAlloc%'],0)

  return tmp_df

# function to print portfolio features
def print_portfolio_stats(df_portfolio_features, myinvmt_df):
  from pyxirr import xirr

  total_booked_amt, reserve_amt, cy_booked_amt, py_booked_amt = get_amt()

  dates = myinvmt_df['Date'].values
  dates = np.append(dates, datetime.date.today().strftime('%d-%b-%y'))
  investment = myinvmt_df['Investment'].values
  dates= pd.to_datetime(dates)

  current = round(sum(df_portfolio_features['Close']*df_portfolio_features['Shares']),0) + reserve_amt
  investment_xirr = np.append(investment, current)
  cagr = round(xirr(pd.DataFrame({"dates": dates, "amounts": investment_xirr}))*100,2)

  investment = -sum(investment)
  invested = round(sum(df_portfolio_features['AvgCost']*df_portfolio_features['Shares']),0) + reserve_amt
  previous = round(sum(df_portfolio_features['Prev_Close']*df_portfolio_features['Shares']),0) + reserve_amt
  cy_invested = investment + py_booked_amt

  today_pnl_amount = current-previous
  today_pnl_percentage = round((current-previous)*100/previous,2)

  curr_pnl_amount = current-invested
  curr_pnl_percentage = round((curr_pnl_amount)*100/(cy_invested),2)

  cy_pnl_amount = cy_booked_amt + curr_pnl_amount
  cy_pnl_percentage = round((cy_pnl_amount)*100/cy_invested,2)

  overall_pnl_amount = total_booked_amt + curr_pnl_amount
  overall_pnl_percentage = round((overall_pnl_amount)*100/investment,2)

  estimate_st = round(sum(df_portfolio_features['FTT']*df_portfolio_features['Shares']),0)  + reserve_amt
  est_st_pnl_amount = estimate_st-current
  est_st_pnl_percentage = round((est_st_pnl_amount)*100/current,2)

  estimate_lt = round(sum(df_portfolio_features['LTT']*df_portfolio_features['Shares']),0)  + reserve_amt
  est_lt_pnl_amount = estimate_lt-current
  est_lt_pnl_percentage = round((est_lt_pnl_amount)*100/current,2)

  total_profit = round(sum(df_portfolio_features[df_portfolio_features['Current P/L%'] > 0]['Current']) - sum(df_portfolio_features[df_portfolio_features['Current P/L%'] > 0]['Investment']),0)
  total_loss = round(sum(df_portfolio_features[df_portfolio_features['Current P/L%'] < 0]['Current']) - sum(df_portfolio_features[df_portfolio_features['Current P/L%'] < 0]['Investment']),0)

  cy_booked_percentage = round((cy_booked_amt)*100/current,2)
  py_booked_percentage = round((py_booked_amt)*100/investment,2)
  total_booked_percentage = round((total_booked_amt)*100/investment,2)

  print('-------------------')
  print('Initial Investment: ', format_amt(investment))
  print('CY Investment: ', format_amt(cy_invested))
  print('Reserve: ', format_amt(reserve_amt))
  print('Current: ',  format_amt(current))
  print('-------------------')
  print('Today PnL: '+ '{} ({}%)'.format(format_amt(today_pnl_amount), today_pnl_percentage))
  print('Current PnL: '+ '{} ({}%)'.format(format_amt(curr_pnl_amount), curr_pnl_percentage))
  print('CY Booked + Current PnL: '+ '{} ({}%)'.format(format_amt(cy_pnl_amount), cy_pnl_percentage))
  print('-------------------')
  print('Total profit: ', format_amt(total_profit))
  print('Total loss: ', format_amt(total_loss))
  print('-------------------')
  print('Total Booked + Current PnL: '+ '{} ({}%)'.format(format_amt(overall_pnl_amount), overall_pnl_percentage))
  print('Total Booked PnL: '+ '{} ({}%)'.format(format_amt(total_booked_amt), total_booked_percentage))
  print('Curr Year Booked PnL: '+ '{} ({}%)'.format(format_amt(cy_booked_amt), cy_booked_percentage))
  print('Prev Year Booked PnL: '+ '{} ({}%)'.format(format_amt(py_booked_amt), py_booked_percentage))
  print('===================')
  print('Est FTT: ',  format_amt(estimate_st))
  print('Est FTT PnL: '+ '{} ({}%)'.format(format_amt(est_st_pnl_amount), est_st_pnl_percentage))

  print('===================')
  print('Deployed: ', format_amt(investment))

  print('Current: ', format_amt(current))

  print('CAGR/XIRR %: '+'{}%'.format(cagr))

In [8]:
# get start and end date
start_date, end_date = get_start_end_date()

# get portfolio and prospects data
mypfs_df = get_mypfs_df()
mypps_df = get_mypps_df()
myinvmt_df = get_myinvmt_df()

# merge above datasets
mypf_df = pd.merge(mypfs_df, mypps_df, on="Symbol")

# seggregate dm and sv portfolio
dm_pf = mypf_df[mypf_df['InPortfolio'] == 'DM']
sv_pf = mypf_df[mypf_df['InPortfolio'] == 'SV']

# build portfolio stock dataframe
dm_stocks = get_stock_ids(dm_pf)
sv_stocks = get_stock_ids(sv_pf)
df_stocks = pd.concat([dm_pf,sv_pf], ignore_index = True)

# arrange common and diff stock features
common_cols = ['Symbol', 'Target', 'Criteria', 'Strategy', 'CumlRnk', 'LatestQtr', 'StarStock', 'Conviction', 'Category', 'InFolio', 'XIRR', 'MBQ']
diff_cols = ['Symbol', 'AvgCost', 'Shares']
df_stocks = arrange_features(df_stocks, common_cols, diff_cols)

# get common features
stock_ids = df_stocks['Symbol'].values
df_common_features = get_common_features(stock_ids, df_stocks)

df_common_features.reset_index(drop=True, inplace=True)
df_common_features.drop(['Date'], axis=1, inplace=True)
# get and print portfolio features
df_portfolio_features = get_portfolio_features(df_common_features)

print_portfolio_stats(df_portfolio_features, myinvmt_df)

df = df_portfolio_features
#plot_pie_chart(df, 'CapType', 'Current')
list_ox40n = list(df[df['MBQ'].str.contains('OX40N', na=False)]['Symbol'].values)

Run date time (IST): 2026-04-24 10:24:40
-------------------
qualified stocks: 92
with latest results: 31
still star stocks: 20
-------------------
Initial Investment:  1.40 C
CY Investment:  1.82 C
Reserve:  1.49 K
Current:  1.48 C
-------------------
Today PnL: -1.13 L (-0.76%)
Current PnL: -35.58 L (-19.51%)
CY Booked + Current PnL: -33.50 L (-18.37%)
-------------------
Total profit:  94.21 K
Total loss:  -36.52 L
-------------------
Total Booked + Current PnL: 9.37 L (6.72%)
Total Booked PnL: 44.95 L (32.22%)
Curr Year Booked PnL: 2.08 L (1.41%)
Prev Year Booked PnL: 42.87 L (30.73%)
===================
Est FTT:  2.56 C
Est FTT PnL: 1.08 C (73.11%)
===================
Deployed:  1.40 C
Current:  1.48 C
CAGR/XIRR %: 2.83%

In [9]:
# top 5 near their targets
cols = ['Symbol', 'Today P/L%', 'Current P/L%', 'FTT%', 'OTT%', 'FTT Amt', 'Current P/L', 'Current', 'FTT', 'Dev%_PE', 'RSI_14','Conviction', 'Spread%',  'CumlRnk', 'RRR Ind', 'CurrAlloc%', 'Gained%', 'Criteria', 'Strategy', 'Category']
df_tmp = df_portfolio_features[~df_portfolio_features['Symbol'].isin(['ENRIN','BLUSPRING','DIGITIDE'])]
df_tmp = df_tmp.sort_values(by = 'FTT Amt', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
55,MASFIN,-0.22,-2.30,24.42,21.57,23377.0,-2250.0,95730.0,397.04,-15.99,57.0,H-SC,2.21,167.0,-0.10,0.65,23.71,XR,ATH,FINANCE
59,PIDILITIND,-0.42,-1.06,19.63,18.37,27407.0,-1490.0,139620.0,1670.26,-30.66,55.0,X-LC,8.32,5.0,-0.05,0.95,9.63,X40,ATH,CHEMICALS
51,KOTAKBANK,-0.24,-1.27,22.66,21.11,30980.0,-1758.0,136715.0,453.24,-15.47,44.0,X-LC,9.77,12.0,-0.06,0.93,4.56,X40,ATH,BANKS
53,M&M,0.93,-0.19,23.61,23.38,32682.0,-257.0,138424.0,3802.40,-15.48,44.0,X-LC,9.10,25.0,-0.01,0.94,8.26,X40N,ATH,AUTO
83,TTKPRESTIG,-0.01,-32.41,48.08,0.09,32752.0,-32657.0,68120.0,770.00,58.16,62.0,M-SC,21.53,250.0,-1.00,0.46,21.30,OX40N,NTT,DURABLES

In [10]:
# top 5 today
df_tmp = df_portfolio_features.sort_values(by = 'Today P/L%', ascending=False)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
5,ATULAUTO,6.63,-12.91,67.15,45.57,115285.0,-25449.0,171683.0,844.00,3721.62,68.0,M-SC,3.58,248.0,-0.22,1.16,32.12,XY24,NTT,AUTO
49,JSWINFRA,2.19,-4.57,22.00,16.43,46563.0,-10125.0,211649.0,342.00,-18.07,63.0,X-MC,9.27,61.0,-0.22,1.43,19.64,X40N,NTT,REALTY
89,WHIRLPOOL,1.73,-22.78,135.60,81.92,120199.0,-26156.0,88642.0,2270.00,-54.79,70.0,M-SC,21.77,210.0,-0.22,0.60,24.52,XR,NTT,DURABLES
22,DIXON,1.43,-19.70,71.77,37.92,150292.0,-51390.0,209408.0,18931.72,-65.87,55.0,X-MC,23.88,54.0,-0.34,1.42,13.94,X40N,ATH,IT
72,SIS,1.12,-23.45,58.42,21.26,49652.0,-26040.0,84992.0,528.00,2006.22,69.0,H-SC,8.35,168.0,-0.52,0.58,26.37,OX40N,NTT,MISC

In [11]:
# bottom 5 today
df_tmp = df_portfolio_features.sort_values(by = 'Today P/L%', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
45,INFY,-4.30,-19.17,66.09,34.24,167138.0,-59993.0,252895.0,1972.00,-36.50,30.0,X-LC,12.62,3.0,-0.36,1.71,0.00,X40,NTT,IT
77,TANLA,-2.88,-45.07,299.94,119.69,446104.0,-122030.0,148731.0,1943.92,-44.56,59.0,H-SC,20.16,147.0,-0.27,1.01,28.77,AR,ATH,IT
28,GODREJCP,-2.84,-0.62,32.94,32.12,48651.0,-918.0,147696.0,1476.34,4.56,55.0,X-LC,8.92,32.0,-0.02,1.00,12.76,X40N,ATH,FMCG
79,TCS,-2.56,-27.87,75.47,26.57,252205.0,-129094.0,334179.0,4311.58,-39.04,42.0,X-LC,15.09,2.0,-0.51,2.26,4.30,X40,ATH,IT
3,ALKYLAMINE,-2.54,-36.70,205.89,93.63,131586.0,-37052.0,63911.0,4546.37,-32.22,59.0,H-SC,21.34,142.0,-0.28,0.43,20.68,SR,ATH,CHEMICALS

In [12]:
# top 5 to exit based on CumlRnk
df_tmp = df_portfolio_features[~df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])]
df_tmp = df_tmp[(df_tmp['Current P/L%'] > -1) & (df_tmp['Current P/L%'] < 1)].sort_values(by = 'CumlRnk', ascending=False)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
74,STARHEALTH,-0.2,-0.27,47.67,47.26,133643.0,-773.0,280350.0,761.0,57.39,72.0,H-SC,4.16,173.0,-0.01,1.9,45.19,XY24,NTT,INSURANCE

In [13]:
# OX40N stocks to exit
df_tmp = df_portfolio_features[(df_portfolio_features['Symbol'].isin(list_ox40n))].sort_values(by = 'Current P/L%', ascending=False)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
25,FINCABLES,0.58,23.36,68.54,107.91,124837.0,34494.0,182138.0,1641.55,11.11,69.0,M-SC,5.77,220.0,0.28,1.23,37.03,OX40N,ATH,CABLES
72,SIS,1.12,-23.45,58.42,21.26,49652.0,-26040.0,84992.0,528.00,2006.22,69.0,H-SC,8.35,168.0,-0.52,0.58,26.37,OX40N,NTT,MISC
16,CERA,-1.74,-29.73,76.30,23.89,94317.0,-52289.0,123614.0,9475.00,-32.22,64.0,H-SC,12.79,153.0,-0.55,0.84,18.79,OX40N,NTT,CERAMICS
83,TTKPRESTIG,-0.01,-32.41,48.08,0.09,32752.0,-32657.0,68120.0,770.00,58.16,62.0,M-SC,21.53,250.0,-1.00,0.46,21.30,OX40N,NTT,DURABLES
50,KANSAINER,-0.53,-33.36,70.29,13.47,126307.0,-89973.0,179694.0,340.00,-42.69,58.0,H-SC,17.69,162.0,-0.71,1.22,25.52,XY24,NTT,PAINTS

In [14]:
# top 5 to book for rotation
df_tmp = df_portfolio_features[(df_portfolio_features['Current P/L%'] > 20) ].sort_values(by = 'CumlRnk', ascending=False)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
25,FINCABLES,0.58,23.36,68.54,107.91,124837.0,34494.0,182138.0,1641.55,11.11,69.0,M-SC,5.77,220.0,0.28,1.23,37.03,OX40N,ATH,CABLES

In [15]:
# top 5 to monitor for exit
df_tmp = df_portfolio_features[~df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])]
df_tmp = df_tmp[(df_tmp['Current P/L%'] > 0) ].sort_values(by = 'Dev%_PE', ascending=False)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
63,RECLTD,-0.86,1.03,19.51,20.74,40046.0,2090.0,205260.0,446.00,11.33,63.0,M-MC,3.71,191.0,0.05,1.39,22.32,XY25,NTT,FINANCE
25,FINCABLES,0.58,23.36,68.54,107.91,124837.0,34494.0,182138.0,1641.55,11.11,69.0,M-SC,5.77,220.0,0.28,1.23,37.03,OX40N,ATH,CABLES

In [16]:
# top 5 to book for rotation from weak conviction
df_tmp = df_portfolio_features[~df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])]
df_tmp = df_tmp[~df_tmp['Criteria'].isin(['XY25','XY24','X40', 'X40N'])].sort_values(by = 'RRR Ind', ascending=False)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
25,FINCABLES,0.58,23.36,68.54,107.91,124837.0,34494.0,182138.0,1641.55,11.11,69.0,M-SC,5.77,220.0,0.28,1.23,37.03,OX40N,ATH,CABLES
73,SONACOMS,-1.62,-2.21,42.24,39.09,41783.0,-2240.0,98919.0,804.02,-22.50,57.0,M-MC,12.72,193.0,-0.05,0.67,39.93,AR,ATH,AUTO
91,ZYDUSLIFE,-2.01,-2.21,38.69,35.63,79293.0,-4630.0,204944.0,1286.17,-14.86,55.0,H-MC,4.10,120.0,-0.06,1.39,9.11,AR,ATH,PHARMA
42,INDIAMART,-1.29,-8.40,125.68,106.72,141987.0,-10361.0,112975.0,4810.62,-58.59,53.0,H-SC,10.70,140.0,-0.07,0.77,8.54,AR,ATH,MISC
55,MASFIN,-0.22,-2.30,24.42,21.57,23377.0,-2250.0,95730.0,397.04,-15.99,57.0,H-SC,2.21,167.0,-0.10,0.65,23.71,XR,ATH,FINANCE

In [17]:
# top 5 to accumulate based on lowest RSI_14
df_tmp = df_portfolio_features[df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])].sort_values(by = 'RSI_14', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
33,HCLTECH,-2.41,-20.61,53.04,21.51,101876.0,-49850.0,192074.0,1872.35,-16.46,29.0,X-LC,7.60,8.0,-0.49,1.30,0.00,X40,ATH,IT
45,INFY,-4.30,-19.17,66.09,34.24,167138.0,-59993.0,252895.0,1972.00,-36.50,30.0,X-LC,12.62,3.0,-0.36,1.71,0.00,X40,NTT,IT
40,ICICIPRULI,-1.72,-12.94,50.16,30.73,86029.0,-25496.0,171509.0,790.00,-36.28,36.0,X-MC,13.03,78.0,-0.30,1.16,4.51,X40,ATH,INSURANCE
1,ABBOTINDIA,-0.31,-15.03,38.95,18.07,59196.0,-26875.0,151980.0,35195.00,-27.72,38.0,X-MC,11.83,58.0,-0.45,1.03,0.00,X40,ATH,PHARMA
35,HDFCLIFE,-0.25,-2.34,36.36,33.18,53195.0,-3498.0,146302.0,814.30,-23.74,41.0,X-LC,17.74,31.0,-0.07,0.99,5.48,X40,ATH,INSURANCE

In [18]:
# top 5 to accumulate based on Spread and CumlRnk
df_tmp = df_portfolio_features[df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])]
df_tmp = df_tmp[(df_tmp['CumlRnk'] < 100)].sort_values(by = 'Spread%', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
84,UNITDSPR,-0.24,1.30,19.22,20.77,45588.0,3044.0,237188.0,1644.00,-10.17,62.0,X-MC,5.06,64.0,0.07,1.61,13.14,X40N,NTT,BREWERIES
88,VOLTAS,-0.17,12.89,28.61,45.20,61931.0,24723.0,216465.0,1856.00,29.27,58.0,X-MC,5.42,79.0,0.40,1.47,20.57,XY25,NTT,AC
71,SIEMENS,-0.80,3.00,21.86,25.51,41899.0,5575.0,191670.0,4671.50,61.08,74.0,H-LC,6.01,51.0,0.13,1.30,35.29,AR,ATH,ELECTRICAL
65,RELIANCE,-0.67,-14.34,46.28,25.30,79665.0,-28825.0,172138.0,1952.00,-16.57,44.0,X-LC,6.06,21.0,-0.36,1.17,3.02,XY25,BTT,REFINERIES
39,ICICIGI,-0.64,-4.74,25.27,19.34,48172.0,-9479.0,190630.0,2252.93,-19.83,47.0,X-MC,6.55,66.0,-0.20,1.29,6.47,X40,ATH,INSURANCE

In [19]:
# top 5 to accumulate based on lowest Gained%
df_tmp = df_portfolio_features[df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])].sort_values(by = 'Gained%', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
1,ABBOTINDIA,-0.31,-15.03,38.95,18.07,59196.0,-26875.0,151980.0,35195.00,-27.72,38.0,X-MC,11.83,58.0,-0.45,1.03,0.00,X40,ATH,PHARMA
33,HCLTECH,-2.41,-20.61,53.04,21.51,101876.0,-49850.0,192074.0,1872.35,-16.46,29.0,X-LC,7.60,8.0,-0.49,1.30,0.00,X40,ATH,IT
45,INFY,-4.30,-19.17,66.09,34.24,167138.0,-59993.0,252895.0,1972.00,-36.50,30.0,X-LC,12.62,3.0,-0.36,1.71,0.00,X40,NTT,IT
65,RELIANCE,-0.67,-14.34,46.28,25.30,79665.0,-28825.0,172138.0,1952.00,-16.57,44.0,X-LC,6.06,21.0,-0.36,1.17,3.02,XY25,BTT,REFINERIES
79,TCS,-2.56,-27.87,75.47,26.57,252205.0,-129094.0,334179.0,4311.58,-39.04,42.0,X-LC,15.09,2.0,-0.51,2.26,4.30,X40,ATH,IT

In [20]:
# top 5 to accumulate based on lowest CurrAlloc%
df_tmp = df_portfolio_features[df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])].sort_values(by = 'CurrAlloc%', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
64,RELAXO,-1.34,-60.44,285.04,52.31,163667.0,-87741.0,57419.0,1176.00,-57.89,55.0,X-SC,29.81,92.0,-0.54,0.39,28.38,X40N,NTT,FOOTWEAR
10,BATAINDIA,-1.47,-52.01,181.72,35.20,112216.0,-66918.0,61752.0,2096.00,-18.99,55.0,X-SC,29.38,91.0,-0.60,0.42,22.47,X40,NTT,FOOTWEAR
60,QUESS,-1.34,-22.03,123.04,73.90,102448.0,-23529.0,83264.0,424.00,-58.13,51.0,X-SC,17.44,80.0,-0.23,0.56,12.01,XY24,NTT,MISC
51,KOTAKBANK,-0.24,-1.27,22.66,21.11,30980.0,-1758.0,136715.0,453.24,-15.47,44.0,X-LC,9.77,12.0,-0.06,0.93,4.56,X40,ATH,BANKS
53,M&M,0.93,-0.19,23.61,23.38,32682.0,-257.0,138424.0,3802.40,-15.48,44.0,X-LC,9.10,25.0,-0.01,0.94,8.26,X40N,ATH,AUTO

In [21]:
# top 5 to accumulate based on CumlRnk
df_tmp = df_portfolio_features.sort_values(by = 'CumlRnk', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
47,ITC,-0.39,-19.90,48.64,19.06,132531.0,-67692.0,272474.0,452.00,-55.92,50.0,X-LC,18.29,1.0,-0.51,1.85,5.70,X40,NTT,FMCG
79,TCS,-2.56,-27.87,75.47,26.57,252205.0,-129094.0,334179.0,4311.58,-39.04,42.0,X-LC,15.09,2.0,-0.51,2.26,4.30,X40,ATH,IT
45,INFY,-4.30,-19.17,66.09,34.24,167138.0,-59993.0,252895.0,1972.00,-36.50,30.0,X-LC,12.62,3.0,-0.36,1.71,0.00,X40,NTT,IT
81,TMPV,-0.67,-20.42,71.62,36.58,202811.0,-72665.0,283176.0,600.00,-83.62,55.0,X-LC,7.81,4.0,-0.36,1.92,18.03,XY24,NTT,AUTO
59,PIDILITIND,-0.42,-1.06,19.63,18.37,27407.0,-1490.0,139620.0,1670.26,-30.66,55.0,X-LC,8.32,5.0,-0.05,0.95,9.63,X40,ATH,CHEMICALS

In [22]:
# top 5 for average up
df_tmp = df_portfolio_features[(df_portfolio_features['Dev%_200'] > 5)].sort_values(by = 'CurrAlloc%', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
73,SONACOMS,-1.62,-2.21,42.24,39.09,41783.0,-2240.0,98919.0,804.02,-22.50,57.0,M-MC,12.72,193.0,-0.05,0.67,39.93,AR,ATH,AUTO
75,SURYODAY,-1.53,-18.36,50.71,23.03,74131.0,-32885.0,146186.0,216.00,60.09,59.0,H-SC,3.49,166.0,-0.44,0.99,24.67,XR,NTT,BANKS
5,ATULAUTO,6.63,-12.91,67.15,45.57,115285.0,-25449.0,171683.0,844.00,3721.62,68.0,M-SC,3.58,248.0,-0.22,1.16,32.12,XY24,NTT,AUTO
25,FINCABLES,0.58,23.36,68.54,107.91,124837.0,34494.0,182138.0,1641.55,11.11,69.0,M-SC,5.77,220.0,0.28,1.23,37.03,OX40N,ATH,CABLES
71,SIEMENS,-0.80,3.00,21.86,25.51,41899.0,5575.0,191670.0,4671.50,61.08,74.0,H-LC,6.01,51.0,0.13,1.30,35.29,AR,ATH,ELECTRICAL

In [23]:
# top 5 RSP
df_tmp = df_portfolio_features.sort_values(by = 'RSP', ascending=False)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
61,RAJESHEXPO,-1.39,-75.49,308.20,0.07,103641.0,-103549.0,33628.0,518.0,1132.32,60.0,L-SC,38.02,268.0,-1.00,0.23,57.88,OX40N,NTT,JEWELLERY
62,RAJOOENG,-0.18,-29.83,98.97,39.61,71179.0,-30580.0,71920.0,143.1,-52.57,69.0,H-SC,25.18,136.0,-0.43,0.49,54.07,AR,ATH,MISC
71,SIEMENS,-0.80,3.00,21.86,25.51,41899.0,5575.0,191670.0,4671.5,61.08,74.0,H-LC,6.01,51.0,0.13,1.30,35.29,AR,ATH,ELECTRICAL
87,VBL,0.32,-1.87,38.08,35.50,118025.0,-5902.0,309940.0,670.8,-13.37,68.0,X-LC,6.97,13.0,-0.05,2.10,27.27,X40N,ATH,FMCG
0,5PAISA,0.84,-35.38,74.71,12.90,105487.0,-77301.0,141195.0,593.0,107.93,66.0,H-SC,11.65,170.0,-0.73,0.96,36.25,OX40N,NTT,FINANCE

In [24]:
# Top N allocation
df_tmp = df_portfolio_features.sort_values(by = 'CurrAlloc%', ascending=False)
top_n_values = [10, 25, 50]

sum_df = pd.DataFrame({
    'Top_N': top_n_values,
    'Sum_Alloc%': [df_tmp['CurrAlloc%'].head(n).sum() for n in top_n_values]
})

sum_df

   Top_N  Sum_Alloc%
0     10       18.90
1     25       42.61
2     50       72.72

In [25]:
# market-cap-wise allocation
df_tmp = df_portfolio_features[cols]
df_tmp.groupby(df_tmp['Conviction'].str[-2:])['CurrAlloc%'].sum().sort_values(ascending=False)

Conviction
SC    41.75
LC    31.88
MC    26.36
Name: CurrAlloc%, dtype: float64

In [26]:
# criteria-wise allocation
df_portfolio_features.groupby('Criteria')['CurrAlloc%'].sum().sort_values(ascending=False)

Criteria
XY24     26.51
X40      25.99
X40N     17.07
XR        8.95
XY25      7.08
OX40N     6.82
AR        6.80
SR        0.77
Name: CurrAlloc%, dtype: float64

In [27]:
# conviction-wise allocation
df_portfolio_features.groupby('Conviction')['CurrAlloc%'].sum().sort_values(ascending=False)

Conviction
X-LC    29.65
H-SC    21.45
X-MC    21.38
M-SC    10.00
X-SC     9.72
H-MC     2.59
M-MC     2.06
H-LC     1.30
M-LC     0.93
L-SC     0.58
L-MC     0.33
Name: CurrAlloc%, dtype: float64

In [28]:
# sector-wise stats
df_tmp = df_portfolio_features.groupby('Category')[['CurrAlloc%', 'Current', 'Current P/L', 'FTT Amt']].sum().sort_values(by=['Current', 'Current P/L'], ascending=False)
df_tmp['Current P/L%'] = round(df_tmp['Current P/L'] * 100 / df_tmp['Current'], 2)
df_tmp['FTT%'] = round(df_tmp['FTT Amt'] * 100 / df_tmp['Current'], 2)
cols = ['CurrAlloc%', 'Current P/L%', 'FTT%']
df_tmp[cols].sort_values(by=['CurrAlloc%'], ascending=False)

               CurrAlloc%  Current P/L%    FTT%
Category
FMCG                15.71        -14.18   54.47
FINANCE             10.82        -15.46   65.68
IT                  10.56        -44.35  117.45
MISC                 6.92        -31.42   88.51
AUTO                 6.68        -11.14   52.81
INSURANCE            5.34         -4.98   40.70
BANKS                5.28        -16.51   70.38
PAINTS               5.18        -29.04   51.45
PHARMA               4.84         -3.68   37.00
ELECTRICAL           4.16        -15.20   56.20
AC                   2.00         -8.70   38.17
CHEMICALS            1.97        -39.45  122.56
HEALTHCARE           1.86        -29.90   63.80
APPARELS             1.80         -0.81   35.21
DURABLES             1.78        -47.40   83.26
FOOTWEAR             1.76        -70.00  138.16
TRAVEL               1.71        -77.14  165.83
BREWERIES            1.61          1.28   19.22
REALTY               1.43         -4.78   22.00
CERAMICS             1.31        -58.81  107.06
CABLES               1.23         18.94   68.54
REFINERIES           1.17        -16.75   46.28
CEMENT               1.14        -58.94  177.85
ENGINEERING          1.13        -45.13  111.50
JEWELLERY            1.07       -102.59  172.98
ENTERTAINMENT        0.75        -73.13  176.39
TEXTILES             0.43        -44.99   86.34
HOTELS               0.35       -122.75  201.32

In [29]:
# money to be made criteria-wise
df_portfolio_features.groupby('Criteria')['FTT Amt'].agg(['sum', 'count']).sort_values(by='sum', ascending=False)

                sum  count
Criteria
XY24      3682627.0     21
X40       1865120.0     19
XR        1359926.0     13
X40N      1205889.0     13
AR        1188362.0      9
OX40N      787761.0     10
XY25       396934.0      5
SR         304434.0      2

In [30]:
# money to be made conviction-wise
df_portfolio_features.groupby('Conviction')['FTT Amt'].agg(['sum', 'count']).sort_values(by='sum', ascending=False)

                  sum  count
Conviction
H-SC        3626925.0     24
X-LC        1923676.0     21
X-MC        1577364.0     15
M-SC        1442303.0     14
X-SC        1367374.0      9
H-MC         315195.0      2
L-SC         206266.0      2
M-LC         154185.0      1
M-MC          81829.0      2
L-MC          54037.0      1
H-LC          41899.0      1

In [31]:
# money to be made criteria and conviction-wise
df_portfolio_features.groupby(['Conviction', 'Criteria'])['FTT Amt'].agg(['sum', 'count']).sort_values(by='sum', ascending=False)

                           sum  count
Conviction Criteria
H-SC       XY24      1201234.0      6
X-LC       X40       1013840.0     10
H-SC       AR         950186.0      5
M-SC       XY24       851053.0      6
H-SC       XR         827865.0      7
X-SC       XY24       814844.0      4
X-MC       X40        653744.0      7
           X40N       466456.0      4
X-LC       X40N       384439.0      6
X-SC       X40N       354994.0      3
H-SC       OX40N      343206.0      4
X-LC       XY24       341943.0      2
M-SC       OX40N      340914.0      5
H-SC       SR         304434.0      2
X-MC       XY24       237651.0      2
H-MC       XY24       235902.0      1
X-MC       XY25       219513.0      2
X-SC       X40        197536.0      2
M-SC       XR         175135.0      2
M-LC       XR         154185.0      1
X-LC       XY25       137375.0      2
L-SC       OX40N      103641.0      1
           XR         102625.0      1
H-MC       AR          79293.0      1
M-SC       AR          75201.0      1
L-MC       XR          54037.0      1
X-LC       XR          46079.0      1
H-LC       AR          41899.0      1
M-MC       AR          41783.0      1
           XY25        40046.0      1

In [32]:
# notebook execution time

end_time = time.time()
execution_time = round(end_time - start_time, 0)
print(f"Notebook execution time: {execution_time} seconds")

Notebook execution time: 25.0 seconds