<a href="https://colab.research.google.com/github/ankit-rathi/Quantvesting_v2/blob/main/myStocks_Portfolio_Analysis.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
'''
!pip install pandas==2.2.2 -qq
!pip install pyxirr -qq
!pip install ta -qq
!pip install yfinance==0.2.59 -qq
'''

'\n!pip install pandas==2.2.2 -qq\n!pip install pyxirr -qq\n!pip install ta -qq\n!pip install yfinance==0.2.59 -qq\n'

In [2]:
# import libraries

import numpy as np
import pandas as pd
import datetime
import warnings
warnings.filterwarnings('ignore')
import yfinance as yfin
import ta
import matplotlib.pyplot as plt
import requests

In [3]:
# notebook start time
import time
import datetime
import pytz

start_time = time.time()

# function to print date timestamp
def print_date_time():
  tz_NY = pytz.timezone('Asia/Kolkata')
  datetime_NY = datetime.datetime.now(tz_NY)
  print("Run date time (IST):", datetime_NY.strftime("%Y-%m-%d %H:%M:%S"))

In [4]:
# function to get booked and reserved amount
def get_amt():
  # fetch the JSON data from the URL
  url = "https://raw.githubusercontent.com/ankit-rathi/Tradevesting_v1/main/data/myPortfolioAmts.json"
  response = requests.get(url)
  pf_amts = response.json()  # parse the JSON data

  # extract values from the JSON
  py_booked_amt_dm = pf_amts["py_booked_amt_dm"]
  py_booked_amt_sv = pf_amts["py_booked_amt_sv"]
  cy_booked_amt_dm = pf_amts["cy_booked_amt_dm"]
  cy_booked_amt_sv = pf_amts["cy_booked_amt_sv"]
  reserve_amt_dm = pf_amts["reserve_amt_dm"]
  reserve_amt_sv = pf_amts["reserve_amt_sv"]

  # perform calculations
  py_booked_amt = py_booked_amt_dm + py_booked_amt_sv
  cy_booked_amt = cy_booked_amt_dm + cy_booked_amt_sv
  reserve_amt = reserve_amt_dm + reserve_amt_sv
  total_booked_amt = py_booked_amt + cy_booked_amt

  return total_booked_amt, reserve_amt, cy_booked_amt, py_booked_amt

gen_output = 0

In [5]:
# function to format the amount
def format_amt(number):
    abs_number = abs(number)

    if abs_number >= 1_00_00_000:  # Crores
        formatted_amt = f"{number / 1_00_00_000:.2f} C"
    elif abs_number >= 1_00_000:  # Lakhs
        formatted_amt = f"{number / 1_00_000:.2f} L"
    elif abs_number >= 1_000:  # Thousands
        formatted_amt = f"{number / 1_000:.2f} K"
    else:
        formatted_amt = f"{number:.2f}"

    return formatted_amt

# function to set start and end date
def get_start_end_date():
  start_date = (datetime.date.today() + datetime.timedelta(days=-365)).strftime('%Y-%m-%d')
  end_date = (datetime.date.today() + datetime.timedelta(days=1)).strftime('%Y-%m-%d')
  return start_date, end_date

# function to fetch my portfolio csv
def get_mypfs_df():
  mypfs_df = pd.read_csv('https://raw.githubusercontent.com/ankit-rathi/Tradevesting_v1/main/data/myPortfolioStocks.csv')
  return mypfs_df

# function to fetch my prospects csv
def get_mypps_df():
  mypps_df = pd.read_csv('https://raw.githubusercontent.com/ankit-rathi/Tradevesting_v1/main/data/myProspectsScrips.csv')
  return mypps_df

# function to fetch screener data
def get_myscreen_df():
  myscreen_df = pd.read_csv('https://raw.githubusercontent.com/ankit-rathi/Tradevesting_v1/main/data/myScreenerDB.csv')
  return myscreen_df

# function to fetch momentum data
def get_myinvmt_df():
  myinvmt_df = pd.read_csv('https://raw.githubusercontent.com/ankit-rathi/Tradevesting_v1/main/data/myInvestments.csv')
  return myinvmt_df

# function to get the stock ids
def get_stock_ids(df_pf):
  stock_n100 = df_pf['Symbol'].unique()

  exclude = ['CADILAHC','MMTC', 'MASFIN']

  stock_ids = df_pf[~df_pf['Symbol'].isin(exclude) ]['Symbol'].unique()

  #mypf = mypf[mypf.Forecast.notnull()]
  #stock_ids = mypf['Symbol'].unique()

  #stock_ids.sort()
  return stock_ids

# get features from screener data
def get_screener_features():
  myscreen_df = get_myscreen_df()
  cols = ['Symbol', 'EPS', 'MedPE', 'ROCE%', 'ROE%', 'CapType']
  return myscreen_df[cols]

# get relative strength
def get_relative_strength(stock_list):

    # Dictionary to store stock tickers and their corresponding percentage price change
    stock_changes = {}

    # Loop through each stock and fetch its price data
    for stock in stock_list:
        try:
            # Download the stock data for the given date range
            stock_data = yfin.Ticker(stock + '.NS').history(period='1mo', interval='1d')[map(str.title, ['open', 'close', 'low', 'high', 'volume'])]

            # Calculate the percentage change for the stock
            if len(stock_data) > 0:
                start_price = stock_data['Close'].iloc[0]
                end_price = stock_data['Close'].iloc[-1]
                percent_change = round(((end_price - start_price) / start_price) * 100, 2)
                stock_changes[stock] = percent_change
            else:
                stock_changes[stock] = np.nan  # If no data is available, set to NaN

        except Exception as e:
            print(f"Error fetching data for {stock}: {e}")
            stock_changes[stock] = np.nan

    # Create a DataFrame with stock tickers and their percentage changes
    df = pd.DataFrame(list(stock_changes.items()), columns=['Symbol', 'Percent_Change'])

    # Drop any stocks with missing data (NaN values)
    df = df.dropna()

    # Calculate the percentile rank based on percentage change
    df['RSP'] = round(df['Percent_Change'].rank(pct=True) * 100, 2)
    cols = ['Symbol', 'RSP']
    df = df[cols]
    # Sort by percentile rank (optional)
    df = df.sort_values(by='RSP', ascending=False).reset_index(drop=True)

    return df

In [6]:
# function to get stock technicals
def stock_prec_dev(stock_symbol):
    #stock_symbol = 'ULTRACEMCO.NS'
    short_window = 20
    mid_window = 50
    long_window = 200
    moving_avg = 'SMA'

    start = datetime.datetime(*map(int, start_date.split('-')))
    end = datetime.datetime(*map(int, end_date.split('-')))

    stock_df = yfin.Ticker(stock_symbol + '.NS').history(period='max', interval='1d')[map(str.title, ['open', 'close', 'low', 'high', 'volume'])]

    stock_df['Max'] = round(max(stock_df['Close']),2)
    stock_df = stock_df[(stock_df.index <= end_date) & (stock_df.index >= start_date)]
    stock_df['200_SMA'] = round(stock_df['Close'].rolling(window = 200, min_periods = 1).mean(),0)
    stock_df['Dev%_200'] = round((stock_df['Close'] - stock_df['200_SMA'])*100/stock_df['200_SMA'],2)
    stock_df.dropna(axis = 0, inplace = True) # remove any null rows

    stock_df['20_SMA'] = stock_df['Close'].rolling(window=20).mean()
    stock_df['50_SMA'] = stock_df['Close'].rolling(window=50).mean()
    stock_df['Symbol'] = stock_symbol

    stock_df['Close'] = round(stock_df['Close'],2)
    stock_df['Min'] = round(min(stock_df['Close']),2)
    stock_df['RSI_14'] = ta.momentum.RSIIndicator(close=stock_df['Close'], window=14).rsi()
    stock_df['RSI_14'] = round(stock_df['RSI_14'],0)
    stock_df['Prev_Close'] = stock_df['Close'].shift(1)
    stock_df.drop(['Open', 'Low', 'High', 'Volume'], axis=1, inplace=True)
    stock_df = stock_df.tail(1)

    max_SMA = max(stock_df['20_SMA'].item(), stock_df['50_SMA'].item(), stock_df['200_SMA'].item())
    min_SMA = min(stock_df['20_SMA'].item(), stock_df['50_SMA'].item(), stock_df['200_SMA'].item())
    ABS_Spread = max_SMA - min_SMA
    stock_df['Spread%'] = round((ABS_Spread / stock_df['200_SMA'].item()) * 100,2)

    return stock_df

# function to compute stock attributes
def get_common_features(stock_ids, df_mypf):

  df_prec_dev = pd.DataFrame()
  df_tmp = get_screener_features()
  df_rs = get_relative_strength(stock_ids)

  for stock_id in stock_ids:
      tmp = stock_prec_dev(stock_id)
      tmp = tmp.reset_index()
      df_prec_dev = pd.concat([df_prec_dev, tmp], ignore_index = True)
  df_prec_dev = pd.merge(df_prec_dev, df_mypf, on= 'Symbol')
  df_prec_dev = pd.merge(df_prec_dev, df_tmp, on= 'Symbol', how='left')
  df_prec_dev = pd.merge(df_prec_dev, df_rs, on= 'Symbol', how='left')
  #print(df_prec_dev.columns)
  df_prec_dev['Curr_PE'] = round(df_prec_dev['Close']/df_prec_dev['EPS'],1)
  df_prec_dev['Dev%_PE'] = round((df_prec_dev['Curr_PE'] - df_prec_dev['MedPE'])*100/df_prec_dev['MedPE'],2)
  df_prec_dev['Conviction'] = df_prec_dev['Conviction'] + '-' + df_prec_dev['CapType']
  return df_prec_dev

# function to arrange stock features
def arrange_features(df_stocks, common_cols, diff_cols):
  df_stocks_common = df_stocks[common_cols].drop_duplicates()
  df_stocks_diff = df_stocks[diff_cols]
  df_stocks_diff['Investment'] = df_stocks_diff['AvgCost'] * df_stocks_diff['Shares']
  df_stocks_diff = df_stocks_diff.groupby(['Symbol'])[['Shares', 'Investment']].aggregate(['sum']).reset_index()
  df_stocks_diff.columns = ['Symbol', 'Shares', 'Investment']
  df_stocks_diff['AvgCost'] = round(df_stocks_diff['Investment']/df_stocks_diff['Shares'],2)
  df_stocks = pd.merge(df_stocks_diff, df_stocks_common, on='Symbol')
  return df_stocks

# plot fact distribution across dimension
def plot_pie_chart(df, dimension, fact):
  # grouping the data by category and calculating the sum of fact for each type
  grouped_data = df.groupby(dimension)[fact].sum()

  # sorting the grouped data in descending order
  grouped_data = grouped_data.sort_values(ascending=False)

  # creating a pie chart
  grouped_data.plot.pie(autopct='%1.1f%%', startangle=90, figsize=(6, 6))

  # adding a title and displaying the plot
  plt.title(f'{dimension} {fact} Distribution')
  plt.ylabel('')  # To hide the y-label
  plt.show()

In [7]:
# function to get portfolio features

def get_portfolio_features(df_common_features):

  print_date_time()
  print('-------------------')

  #df_common_features["Target"] = df_common_features["Target"].fillna(df_common_features["Max"])
  df_common_features['NTT'] = np.where(df_common_features['Strategy']== 'NTT', df_common_features["Target"], df_common_features['Max'])
  df_common_features['LTT'] = np.where(df_common_features['Strategy']== 'BTT', df_common_features["Target"], df_common_features['Max'])
  df_common_features['BOL'] = df_common_features['Min']

  tmp_df = df_common_features[df_common_features['Symbol'].isin(mypf_df[mypf_df['InPortfolio'] != 'NA'].Symbol.values)]
  print('qualified stocks: '+str(len(tmp_df['Symbol'].unique())))
  tmp_df1 = tmp_df[tmp_df['LatestQtr'] == 1]
  print('with latest results: '+str(len(tmp_df1['Symbol'].unique())))
  tmp_df1 = tmp_df1[tmp_df1['StarStock'] == 1]
  print('still star stocks: '+str(len(tmp_df1['Symbol'].unique())))
  tmp_df['Investment'] = tmp_df['AvgCost'] * tmp_df['Shares']
  tmp_df['Current'] = round(tmp_df['Close'] * tmp_df['Shares'],0)
  tmp_df['Previous'] = tmp_df['Prev_Close'] * tmp_df['Shares']
  tmp_df['EstimatedST'] = tmp_df['NTT'] * tmp_df['Shares']
  tmp_df['EstimatedLT'] = tmp_df['LTT'] * tmp_df['Shares']
  tmp_df['Current P/L'] = round((tmp_df['Current'] - tmp_df['Investment']),0)
  tmp_df['Today P/L%'] = round((tmp_df['Current'] - tmp_df['Previous'])*100/tmp_df['Previous'],2)
  tmp_df['Current P/L%'] = round((tmp_df['Current'] - tmp_df['Investment'])*100/tmp_df['Investment'],2)
  tmp_df['EstimatedST P/L%'] = round((tmp_df['EstimatedST'] - tmp_df['Investment'])*100/tmp_df['Investment'],2)
  tmp_df['EstimatedLT P/L%'] = round((tmp_df['EstimatedLT'] - tmp_df['Investment'])*100/tmp_df['Investment'],2)
  tmp_df['NTT%'] = round((tmp_df['NTT'] - tmp_df['Close'])*100/tmp_df['Close'],2)
  tmp_df['LTT%'] = round((tmp_df['LTT'] - tmp_df['Close'])*100/tmp_df['Close'],2)
  tmp_df['Gained%'] = round((tmp_df['Close'] - tmp_df['BOL'])*100/tmp_df['BOL'],2)
  investment = round(sum(tmp_df['AvgCost']*tmp_df['Shares']),0)
  current = round(sum(tmp_df['Close']*tmp_df['Shares']),0)
  tmp_df['InitAlloc%'] = round(tmp_df['Investment']*100/investment,2)
  tmp_df['CurrAlloc%'] = round(tmp_df['Current']*100/current,2)
  tmp_df['FTT'] = tmp_df['LTT']
  tmp_df.loc[tmp_df['Strategy'] == 'NTT', 'FTT'] = tmp_df['NTT']
  tmp_df['FTT%'] = tmp_df['LTT%']
  tmp_df.loc[tmp_df['Strategy'] == 'NTT', 'FTT%'] = tmp_df['NTT%']
  tmp_df['FTT Amt'] = round(tmp_df['FTT%'] * tmp_df['Current']/100,0)
  tmp_df['OTT%'] = round((tmp_df['FTT'] - tmp_df['AvgCost'])*100/tmp_df['AvgCost'],2)
  tmp_df['RRR Ind'] = round(tmp_df['Current P/L']/tmp_df['FTT Amt'],2)
  tmp_df['Risk Ind'] = round(tmp_df['Current P/L%']*tmp_df['CurrAlloc%'],0)

  return tmp_df

# function to print portfolio features
def print_portfolio_stats(df_portfolio_features, myinvmt_df):
  from pyxirr import xirr

  total_booked_amt, reserve_amt, cy_booked_amt, py_booked_amt = get_amt()

  dates = myinvmt_df['Date'].values
  dates = np.append(dates, datetime.date.today().strftime('%d-%b-%y'))
  investment = myinvmt_df['Investment'].values
  dates= pd.to_datetime(dates)

  current = round(sum(df_portfolio_features['Close']*df_portfolio_features['Shares']),0) + reserve_amt
  investment_xirr = np.append(investment, current)
  cagr = round(xirr(pd.DataFrame({"dates": dates, "amounts": investment_xirr}))*100,2)

  investment = -sum(investment)
  invested = round(sum(df_portfolio_features['AvgCost']*df_portfolio_features['Shares']),0) + reserve_amt
  previous = round(sum(df_portfolio_features['Prev_Close']*df_portfolio_features['Shares']),0) + reserve_amt
  cy_invested = investment + py_booked_amt

  today_pnl_amount = current-previous
  today_pnl_percentage = round((current-previous)*100/previous,2)

  curr_pnl_amount = current-invested
  curr_pnl_percentage = round((curr_pnl_amount)*100/(cy_invested),2)

  cy_pnl_amount = cy_booked_amt + curr_pnl_amount
  cy_pnl_percentage = round((cy_pnl_amount)*100/cy_invested,2)

  overall_pnl_amount = total_booked_amt + curr_pnl_amount
  overall_pnl_percentage = round((overall_pnl_amount)*100/investment,2)

  estimate_st = round(sum(df_portfolio_features['FTT']*df_portfolio_features['Shares']),0)  + reserve_amt
  est_st_pnl_amount = estimate_st-current
  est_st_pnl_percentage = round((est_st_pnl_amount)*100/current,2)

  estimate_lt = round(sum(df_portfolio_features['LTT']*df_portfolio_features['Shares']),0)  + reserve_amt
  est_lt_pnl_amount = estimate_lt-current
  est_lt_pnl_percentage = round((est_lt_pnl_amount)*100/current,2)

  total_profit = round(sum(df_portfolio_features[df_portfolio_features['Current P/L%'] > 0]['Current']) - sum(df_portfolio_features[df_portfolio_features['Current P/L%'] > 0]['Investment']),0)
  total_loss = round(sum(df_portfolio_features[df_portfolio_features['Current P/L%'] < 0]['Current']) - sum(df_portfolio_features[df_portfolio_features['Current P/L%'] < 0]['Investment']),0)

  cy_booked_percentage = round((cy_booked_amt)*100/current,2)
  py_booked_percentage = round((py_booked_amt)*100/investment,2)
  total_booked_percentage = round((total_booked_amt)*100/investment,2)

  print('-------------------')
  print('Initial Investment: ', format_amt(investment))
  print('CY Investment: ', format_amt(cy_invested))
  print('Reserve: ', format_amt(reserve_amt))
  print('Current: ',  format_amt(current))
  print('-------------------')
  print('Today PnL: '+ '{} ({}%)'.format(format_amt(today_pnl_amount), today_pnl_percentage))
  print('Current PnL: '+ '{} ({}%)'.format(format_amt(curr_pnl_amount), curr_pnl_percentage))
  print('CY Booked + Current PnL: '+ '{} ({}%)'.format(format_amt(cy_pnl_amount), cy_pnl_percentage))
  print('-------------------')
  print('Total profit: ', format_amt(total_profit))
  print('Total loss: ', format_amt(total_loss))
  print('-------------------')
  print('Total Booked + Current PnL: '+ '{} ({}%)'.format(format_amt(overall_pnl_amount), overall_pnl_percentage))
  print('Total Booked PnL: '+ '{} ({}%)'.format(format_amt(total_booked_amt), total_booked_percentage))
  print('Curr Year Booked PnL: '+ '{} ({}%)'.format(format_amt(cy_booked_amt), cy_booked_percentage))
  print('Prev Year Booked PnL: '+ '{} ({}%)'.format(format_amt(py_booked_amt), py_booked_percentage))
  print('===================')
  print('Est FTT: ',  format_amt(estimate_st))
  print('Est FTT PnL: '+ '{} ({}%)'.format(format_amt(est_st_pnl_amount), est_st_pnl_percentage))

  print('===================')
  print('Deployed: ', format_amt(investment))

  print('Current: ', format_amt(current))

  print('CAGR/XIRR %: '+'{}%'.format(cagr))

In [8]:
# get start and end date
start_date, end_date = get_start_end_date()

# get portfolio and prospects data
mypfs_df = get_mypfs_df()
mypps_df = get_mypps_df()
myinvmt_df = get_myinvmt_df()

# merge above datasets
mypf_df = pd.merge(mypfs_df, mypps_df, on="Symbol")

# seggregate dm and sv portfolio
dm_pf = mypf_df[mypf_df['InPortfolio'] == 'DM']
sv_pf = mypf_df[mypf_df['InPortfolio'] == 'SV']

# build portfolio stock dataframe
dm_stocks = get_stock_ids(dm_pf)
sv_stocks = get_stock_ids(sv_pf)
df_stocks = pd.concat([dm_pf,sv_pf], ignore_index = True)

# arrange common and diff stock features
common_cols = ['Symbol', 'Target', 'Criteria', 'Strategy', 'CumlRnk', 'LatestQtr', 'StarStock', 'Conviction', 'Category', 'InFolio', 'XIRR', 'MBQ']
diff_cols = ['Symbol', 'AvgCost', 'Shares']
df_stocks = arrange_features(df_stocks, common_cols, diff_cols)

# get common features
stock_ids = df_stocks['Symbol'].values
df_common_features = get_common_features(stock_ids, df_stocks)

df_common_features.reset_index(drop=True, inplace=True)
df_common_features.drop(['Date'], axis=1, inplace=True)
# get and print portfolio features
df_portfolio_features = get_portfolio_features(df_common_features)

print_portfolio_stats(df_portfolio_features, myinvmt_df)

df = df_portfolio_features
#plot_pie_chart(df, 'CapType', 'Current')
list_ox40n = list(df[df['MBQ'].str.contains('OX40N', na=False)]['Symbol'].values)

Run date time (IST): 2026-03-23 11:25:40
-------------------
qualified stocks: 86
with latest results: 26
still star stocks: 16
-------------------
Initial Investment:  1.36 C
CY Investment:  1.62 C
Reserve:  1.61 K
Current:  1.27 C
-------------------
Today PnL: -4.17 L (-3.17%)
Current PnL: -49.79 L (-30.64%)
CY Booked + Current PnL: -33.90 L (-20.87%)
-------------------
Total profit:  36.74 K
Total loss:  -50.16 L
-------------------
Total Booked + Current PnL: -6.92 L (-5.11%)
Total Booked PnL: 42.87 L (31.64%)
Curr Year Booked PnL: 15.89 L (12.48%)
Prev Year Booked PnL: 26.98 L (19.91%)
===================
Est FTT:  2.48 C
Est FTT PnL: 1.21 C (94.68%)
===================
Deployed:  1.36 C
Current:  1.27 C
CAGR/XIRR %: -3.05%

In [9]:
# top 5 near their targets
cols = ['Symbol', 'Today P/L%', 'Current P/L%', 'FTT%', 'OTT%', 'FTT Amt', 'Current P/L', 'Current', 'FTT', 'Dev%_PE', 'RSI_14','Conviction', 'Spread%',  'CumlRnk', 'RRR Ind', 'CurrAlloc%', 'Gained%', 'Criteria', 'Strategy', 'Category']
df_tmp = df_portfolio_features[~df_portfolio_features['Symbol'].isin(['ENRIN','BLUSPRING','DIGITIDE'])]
df_tmp = df_tmp.sort_values(by = 'FTT Amt', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
50,MASFIN,-4.08,-11.15,36.82,21.57,32055.0,-10920.0,87060.0,397.04,-23.22,37.0,H-SC,1.76,167.0,-0.34,0.68,18.74,XR,ATH,FINANCE
77,TTKPRESTIG,-1.19,-40.09,67.08,0.09,40497.0,-40406.0,60371.0,770.00,40.02,38.0,M-SC,18.54,250.0,-1.00,0.47,2.00,OX40N,NTT,DURABLES
67,SONACOMS,-3.88,-15.82,65.23,39.09,55547.0,-16004.0,85155.0,804.02,-33.30,42.0,M-MC,7.91,193.0,-0.29,0.67,20.47,AR,ATH,AUTO
37,ICICIGI,-3.44,-9.10,31.29,19.34,56915.0,-18213.0,181896.0,2252.93,-23.51,24.0,X-MC,3.22,66.0,-0.32,1.43,0.55,X40,ATH,INSURANCE
2,ABBOTINDIA,-4.21,-14.15,37.53,18.07,57624.0,-25315.0,153540.0,35195.00,-26.90,35.0,X-MC,10.70,58.0,-0.44,1.21,0.00,X40,ATH,PHARMA

In [10]:
# top 5 today
df_tmp = df_portfolio_features.sort_values(by = 'Today P/L%', ascending=False)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
33,HCLTECH,1.08,-12.51,41.55,23.83,87941.0,-30272.0,211652.0,1908.19,-8.19,40.0,X-LC,11.76,8.0,-0.34,1.66,2.77,X40,ATH,IT
17,CAMS,0.13,-16.05,48.28,24.48,102079.0,-40425.0,211431.0,950.00,-19.54,39.0,X-SC,11.97,89.0,-0.40,1.66,1.71,X40N,NTT,MISC
62,SATIN,0.02,-19.54,88.72,51.83,197212.0,-53998.0,222286.0,274.00,-27.73,41.0,H-SC,1.83,159.0,-0.27,1.75,8.29,XY24,NTT,FINANCE
73,TCS,-0.37,-30.08,81.02,26.57,262444.0,-139348.0,323925.0,4311.59,-40.68,28.0,X-LC,17.06,2.0,-0.53,2.54,1.10,X40,ATH,IT
43,INFY,-0.74,-15.14,58.19,34.24,154510.0,-47362.0,265526.0,1972.00,-33.24,35.0,X-LC,15.12,3.0,-0.31,2.09,2.11,X40,NTT,IT

In [11]:
# bottom 5 today
df_tmp = df_portfolio_features.sort_values(by = 'Today P/L%', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
8,AWL,-7.86,-39.05,174.01,67.02,377913.0,-139130.0,217179.0,485.0,-67.16,40.0,X-SC,26.01,81.0,-0.37,1.71,2.73,XY24,NTT,FMCG
82,VOLTAS,-6.63,-3.25,50.08,45.20,92901.0,-6237.0,185505.0,1856.0,10.70,26.0,X-MC,4.86,79.0,-0.07,1.46,3.32,XY25,NTT,AC
11,BANDHANBNK,-6.56,-28.79,170.20,92.42,337633.0,-80185.0,198374.0,400.0,70.26,33.0,H-SC,6.87,174.0,-0.24,1.56,9.28,XY24,NTT,BANKS
80,VALIANTORG,-6.42,-47.63,232.54,74.15,199240.0,-77925.0,85680.0,838.0,-254.09,57.0,H-SC,28.23,145.0,-0.39,0.67,27.50,XR,NTT,CHEMICALS
83,WHIRLPOOL,-6.42,-37.27,190.02,81.92,136830.0,-42790.0,72008.0,2270.0,-63.21,35.0,M-SC,25.39,210.0,-0.31,0.57,1.15,XR,NTT,DURABLES

In [12]:
# top 5 to exit based on CumlRnk
df_tmp = df_portfolio_features[~df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])]
df_tmp = df_tmp[(df_tmp['Current P/L%'] > -1) & (df_tmp['Current P/L%'] < 1)].sort_values(by = 'CumlRnk', ascending=False)
df_tmp[cols].head()

Empty DataFrame
Columns: [Symbol, Today P/L%, Current P/L%, FTT%, OTT%, FTT Amt, Current P/L, Current, FTT, Dev%_PE, RSI_14, Conviction, Spread%, CumlRnk, RRR Ind, CurrAlloc%, Gained%, Criteria, Strategy, Category]
Index: []

In [13]:
# OX40N stocks to exit
df_tmp = df_portfolio_features[(df_portfolio_features['Symbol'].isin(list_ox40n))].sort_values(by = 'Current P/L%', ascending=False)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
26,FINCABLES,-5.07,5.59,96.91,107.91,151076.0,8249.0,155893.0,1641.55,-5.12,46.0,M-SC,8.42,220.0,0.05,1.22,17.28,OX40N,ATH,CABLES
18,CERA,-3.53,-40.04,106.62,23.89,112453.0,-70432.0,105471.0,9475.00,-42.24,40.0,H-SC,18.75,153.0,-0.63,0.83,1.36,OX40N,NTT,CERAMICS
77,TTKPRESTIG,-1.19,-40.09,67.08,0.09,40497.0,-40406.0,60371.0,770.00,40.02,38.0,M-SC,18.54,250.0,-1.00,0.47,2.00,OX40N,NTT,DURABLES
66,SIS,-4.80,-40.17,102.69,21.26,68215.0,-44604.0,66428.0,528.00,1546.11,26.0,H-SC,14.23,168.0,-0.65,0.52,0.00,OX40N,NTT,MISC
72,TATAELXSI,-2.69,-40.57,122.15,32.03,95707.0,-53483.0,78352.0,9161.00,-25.74,34.0,H-SC,20.63,158.0,-0.56,0.62,2.09,OX40N,NTT,IT

In [14]:
# top 5 to book for rotation
df_tmp = df_portfolio_features[(df_portfolio_features['Current P/L%'] > 20) ].sort_values(by = 'CumlRnk', ascending=False)
df_tmp[cols].head()

Empty DataFrame
Columns: [Symbol, Today P/L%, Current P/L%, FTT%, OTT%, FTT Amt, Current P/L, Current, FTT, Dev%_PE, RSI_14, Conviction, Spread%, CumlRnk, RRR Ind, CurrAlloc%, Gained%, Criteria, Strategy, Category]
Index: []

In [15]:
# top 5 to monitor for exit
df_tmp = df_portfolio_features[~df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])]
df_tmp = df_tmp[(df_tmp['Current P/L%'] > 0) ].sort_values(by = 'Dev%_PE', ascending=False)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
26,FINCABLES,-5.07,5.59,96.91,107.91,151076.0,8249.0,155893.0,1641.55,-5.12,46.0,M-SC,8.42,220.0,0.05,1.22,17.28,OX40N,ATH,CABLES
1,ABB,-4.02,10.89,31.27,45.57,90718.0,28493.0,290112.0,7934.00,-28.75,50.0,H-MC,13.07,125.0,0.31,2.28,28.83,AR,NTT,ELECTRICAL

In [16]:
# top 5 to book for rotation from weak conviction
df_tmp = df_portfolio_features[~df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])]
df_tmp = df_tmp[~df_tmp['Criteria'].isin(['XY25','XY24','X40', 'X40N'])].sort_values(by = 'RRR Ind', ascending=False)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
1,ABB,-4.02,10.89,31.27,45.57,90718.0,28493.0,290112.0,7934.00,-28.75,50.0,H-MC,13.07,125.0,0.31,2.28,28.83,AR,NTT,ELECTRICAL
26,FINCABLES,-5.07,5.59,96.91,107.91,151076.0,8249.0,155893.0,1641.55,-5.12,46.0,M-SC,8.42,220.0,0.05,1.22,17.28,OX40N,ATH,CABLES
40,INDIAMART,-1.44,-15.53,144.73,106.72,150783.0,-19154.0,104182.0,4810.62,-61.91,30.0,H-SC,11.24,140.0,-0.13,0.82,4.22,AR,ATH,MISC
85,ZYDUSLIFE,-1.41,-7.42,46.51,35.63,90237.0,-15558.0,194016.0,1286.17,-19.37,42.0,H-MC,5.35,120.0,-0.17,1.52,8.01,AR,ATH,PHARMA
84,WIPRO,-0.97,-22.46,122.16,72.27,160506.0,-38058.0,131390.0,420.00,-30.18,30.0,M-LC,17.44,98.0,-0.24,1.03,0.34,XR,NTT,IT

In [17]:
# top 5 to accumulate based on lowest RSI_14
df_tmp = df_portfolio_features[df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])].sort_values(by = 'RSI_14', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
53,PGHH,-2.29,-28.92,85.73,32.01,130104.0,-61760.0,151760.0,17616.87,-51.96,12.0,X-MC,15.17,57.0,-0.47,1.19,0.0,X40,ATH,FMCG
58,RELAXO,-5.99,-66.64,356.61,52.31,172667.0,-96741.0,48419.0,1176.00,-64.48,17.0,X-SC,25.54,92.0,-0.56,0.38,0.0,X40N,NTT,FOOTWEAR
12,BATAINDIA,-4.99,-59.35,232.59,35.20,121661.0,-76363.0,52307.0,2096.00,-31.41,18.0,X-SC,30.57,91.0,-0.63,0.41,0.0,X40,NTT,FOOTWEAR
38,ICICIPRULI,-2.78,-11.18,47.18,30.73,82556.0,-22025.0,174980.0,790.00,-35.01,19.0,X-MC,3.86,78.0,-0.27,1.37,0.1,X40,ATH,INSURANCE
36,HONAUT,-4.11,-29.57,114.83,51.31,155968.0,-57013.0,135825.0,58357.33,-41.49,20.0,X-SC,15.43,90.0,-0.37,1.07,0.0,X40N,ATH,ELECTRICAL

In [18]:
# top 5 to accumulate based on Spread and CumlRnk
df_tmp = df_portfolio_features[df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])]
df_tmp = df_tmp[(df_tmp['CumlRnk'] < 100)].sort_values(by = 'Spread%', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
78,UNITDSPR,-1.89,-6.30,28.89,20.77,63381.0,-14758.0,219386.0,1644.00,-16.95,38.0,X-MC,1.44,64.0,-0.23,1.72,0.00,X40N,NTT,BREWERIES
37,ICICIGI,-3.44,-9.10,31.29,19.34,56915.0,-18213.0,181896.0,2252.93,-23.51,24.0,X-MC,3.22,66.0,-0.32,1.43,0.55,X40,ATH,INSURANCE
65,SIEMENS,-5.21,-20.30,57.48,25.51,85257.0,-37770.0,148325.0,4671.50,24.61,38.0,H-LC,3.24,51.0,-0.44,1.17,9.23,AR,ATH,ELECTRICAL
59,RELIANCE,-1.24,-10.33,39.74,25.30,71611.0,-20763.0,180200.0,1952.00,-12.73,48.0,X-LC,3.43,21.0,-0.29,1.42,20.31,XY25,BTT,REFINERIES
38,ICICIPRULI,-2.78,-11.18,47.18,30.73,82556.0,-22025.0,174980.0,790.00,-35.01,19.0,X-MC,3.86,78.0,-0.27,1.37,0.10,X40,ATH,INSURANCE

In [19]:
# top 5 to accumulate based on lowest Gained%
df_tmp = df_portfolio_features[df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])].sort_values(by = 'Gained%', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
2,ABBOTINDIA,-4.21,-14.15,37.53,18.07,57624.0,-25315.0,153540.0,35195.00,-26.90,35.0,X-MC,10.70,58.0,-0.44,1.21,0.0,X40,ATH,PHARMA
3,ACC,-2.92,-39.98,191.25,74.81,307782.0,-107196.0,160932.0,3906.00,-57.46,25.0,X-SC,17.07,85.0,-0.35,1.26,0.0,XY24,BTT,CEMENT
6,ASIANPAINT,-2.82,-23.22,62.18,24.52,135320.0,-65812.0,217627.0,3460.26,-22.58,29.0,X-LC,9.40,30.0,-0.49,1.71,0.0,X40,ATH,PAINTS
9,BAJAJHFL,-3.62,-29.88,131.21,62.13,251217.0,-81584.0,191462.0,181.50,-42.37,25.0,X-MC,20.02,60.0,-0.32,1.50,0.0,X40N,ATH,FINANCE
12,BATAINDIA,-4.99,-59.35,232.59,35.20,121661.0,-76363.0,52307.0,2096.00,-31.41,18.0,X-SC,30.57,91.0,-0.63,0.41,0.0,X40,NTT,FOOTWEAR

In [20]:
# top 5 to accumulate based on lowest CurrAlloc%
df_tmp = df_portfolio_features[df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])].sort_values(by = 'CurrAlloc%', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
58,RELAXO,-5.99,-66.64,356.61,52.31,172667.0,-96741.0,48419.0,1176.00,-64.48,17.0,X-SC,25.54,92.0,-0.56,0.38,0.0,X40N,NTT,FOOTWEAR
12,BATAINDIA,-4.99,-59.35,232.59,35.20,121661.0,-76363.0,52307.0,2096.00,-31.41,18.0,X-SC,30.57,91.0,-0.63,0.41,0.0,X40,NTT,FOOTWEAR
54,QUESS,-3.37,-29.56,146.88,73.90,110486.0,-31571.0,75222.0,424.00,-61.98,32.0,X-SC,20.83,80.0,-0.29,0.59,0.0,XY24,NTT,MISC
36,HONAUT,-4.11,-29.57,114.83,51.31,155968.0,-57013.0,135825.0,58357.33,-41.49,20.0,X-SC,15.43,90.0,-0.37,1.07,0.0,X40N,ATH,ELECTRICAL
51,MEDANTA,-2.88,-16.45,52.14,27.12,76897.0,-29035.0,147482.0,1486.00,-18.99,25.0,X-SC,11.58,87.0,-0.38,1.16,0.0,XY24,NTT,HEALTHCARE

In [21]:
# top 5 to accumulate based on CumlRnk
df_tmp = df_portfolio_features.sort_values(by = 'CumlRnk', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
45,ITC,-2.15,-22.69,54.00,19.06,142007.0,-77190.0,262976.0,452.00,-57.54,31.0,X-LC,18.16,1.0,-0.54,2.07,0.00,X40,NTT,FMCG
73,TCS,-0.37,-30.08,81.02,26.57,262444.0,-139348.0,323925.0,4311.59,-40.68,28.0,X-LC,17.06,2.0,-0.53,2.54,1.10,X40,ATH,IT
43,INFY,-0.74,-15.14,58.19,34.24,154510.0,-47362.0,265526.0,1972.00,-33.24,35.0,X-LC,15.12,3.0,-0.31,2.09,2.11,X40,NTT,IT
75,TMPV,-2.48,-30.28,95.89,36.58,237906.0,-107738.0,248103.0,600.00,-85.81,32.0,X-LC,6.00,4.0,-0.45,1.95,0.00,XY24,NTT,AUTO
33,HCLTECH,1.08,-12.51,41.55,23.83,87941.0,-30272.0,211652.0,1908.19,-8.19,40.0,X-LC,11.76,8.0,-0.34,1.66,2.77,X40,ATH,IT

In [22]:
# top 5 for average up
df_tmp = df_portfolio_features[(df_portfolio_features['Dev%_200'] > 5)].sort_values(by = 'CurrAlloc%', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
1,ABB,-4.02,10.89,31.27,45.57,90718.0,28493.0,290112.0,7934.0,-28.75,50.0,H-MC,13.07,125.0,0.31,2.28,28.83,AR,NTT,ELECTRICAL

In [23]:
# top 5 RSP
df_tmp = df_portfolio_features.sort_values(by = 'RSP', ascending=False)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
30,HAPPSTMNDS,-4.61,-51.08,277.83,84.85,174211.0,-65461.0,62704.0,1480.71,-41.79,52.0,H-SC,26.96,152.0,-0.38,0.49,16.12,AR,ATH,IT
80,VALIANTORG,-6.42,-47.63,232.54,74.15,199240.0,-77925.0,85680.0,838.00,-254.09,57.0,H-SC,28.23,145.0,-0.39,0.67,27.50,XR,NTT,CHEMICALS
69,SURYODAY,-1.46,-30.66,77.44,23.03,96153.0,-54906.0,124165.0,216.00,35.96,41.0,H-SC,6.72,166.0,-0.57,0.98,21.35,XR,NTT,BANKS
1,ABB,-4.02,10.89,31.27,45.57,90718.0,28493.0,290112.0,7934.00,-28.75,50.0,H-MC,13.07,125.0,0.31,2.28,28.83,AR,NTT,ELECTRICAL
26,FINCABLES,-5.07,5.59,96.91,107.91,151076.0,8249.0,155893.0,1641.55,-5.12,46.0,M-SC,8.42,220.0,0.05,1.22,17.28,OX40N,ATH,CABLES

In [24]:
# Top N allocation
df_tmp = df_portfolio_features.sort_values(by = 'CurrAlloc%', ascending=False)
top_n_values = [10, 25, 50]

sum_df = pd.DataFrame({
    'Top_N': top_n_values,
    'Sum_Alloc%': [df_tmp['CurrAlloc%'].head(n).sum() for n in top_n_values]
})

sum_df

   Top_N  Sum_Alloc%
0     10       20.79
1     25       45.86
2     50       78.08

In [25]:
# market-cap-wise allocation
df_tmp = df_portfolio_features[cols]
df_tmp.groupby(df_tmp['Conviction'].str[-2:])['CurrAlloc%'].sum().sort_values(ascending=False)

Conviction
SC    44.38
MC    30.05
LC    25.57
Name: CurrAlloc%, dtype: float64

In [26]:
# criteria-wise allocation
df_portfolio_features.groupby('Criteria')['CurrAlloc%'].sum().sort_values(ascending=False)

Criteria
XY24     26.92
X40      25.63
X40N     15.05
AR        9.22
XR        8.34
XY25      7.29
OX40N     6.78
SR        0.77
Name: CurrAlloc%, dtype: float64

In [27]:
# conviction-wise allocation
df_portfolio_features.groupby('Conviction')['CurrAlloc%'].sum().sort_values(ascending=False)

Conviction
X-LC    23.37
X-MC    22.58
H-SC    21.58
X-SC    12.25
M-SC    10.01
H-MC     5.10
M-MC     2.02
H-LC     1.17
M-LC     1.03
L-SC     0.54
L-MC     0.35
Name: CurrAlloc%, dtype: float64

In [28]:
# sector-wise stats
df_tmp = df_portfolio_features.groupby('Category')[['CurrAlloc%', 'Current', 'Current P/L', 'FTT Amt']].sum().sort_values(by=['Current', 'Current P/L'], ascending=False)
df_tmp['Current P/L%'] = round(df_tmp['Current P/L'] * 100 / df_tmp['Current'], 2)
df_tmp['FTT%'] = round(df_tmp['FTT Amt'] * 100 / df_tmp['Current'], 2)
cols = ['CurrAlloc%', 'Current P/L%', 'FTT%']
df_tmp[cols].sort_values(by=['CurrAlloc%'], ascending=False)

               CurrAlloc%  Current P/L%    FTT%
Category
FMCG                15.13        -29.67   75.71
FINANCE             13.04        -29.44   82.19
IT                  11.92        -48.40  123.91
MISC                 6.98        -50.85  116.38
ELECTRICAL           6.56        -16.14   60.61
PAINTS               5.06        -52.91   79.46
INSURANCE            4.69        -13.53   52.37
BANKS                4.55        -32.91  100.37
PHARMA               4.18        -10.36   45.10
AUTO                 3.68        -39.84   95.32
AC                   2.01        -25.13   59.07
HEALTHCARE           1.88        -49.63   88.67
TRAVEL               1.80        -94.81  192.35
DURABLES             1.80        -68.86  109.94
FOOTWEAR             1.77        -96.27  174.97
APPARELS             1.73        -21.62   63.10
BREWERIES            1.72         -6.73   28.89
REALTY               1.43        -21.71   41.70
REFINERIES           1.42        -11.52   39.74
CERAMICS             1.38        -74.65  127.70
CEMENT               1.26        -66.61  191.25
CABLES               1.22          5.29   96.91
CHEMICALS            1.09        -89.63  244.33
ENGINEERING          1.08        -76.27  156.89
JEWELLERY            1.06       -137.00  219.34
ENTERTAINMENT        0.76       -100.04  219.35
TEXTILES             0.45        -61.55  107.61
HOTELS               0.35       -158.25  249.34

In [29]:
# money to be made criteria-wise
df_portfolio_features.groupby('Criteria')['FTT Amt'].agg(['sum', 'count']).sort_values(by='sum', ascending=False)

                sum  count
Criteria
XY24      4170474.0     21
X40       1910104.0     16
XR        1429318.0     12
AR        1398963.0     10
X40N      1383409.0     10
OX40N      928971.0     10
XY25       513555.0      5
SR         320332.0      2

In [30]:
# money to be made conviction-wise
df_portfolio_features.groupby('Conviction')['FTT Amt'].agg(['sum', 'count']).sort_values(by='sum', ascending=False)

                  sum  count
Conviction
H-SC        4044823.0     24
X-MC        1857629.0     15
X-LC        1801538.0     13
M-SC        1643041.0     14
X-SC        1623042.0     10
H-MC         429036.0      3
L-SC         223232.0      2
M-LC         160506.0      1
M-MC         129271.0      2
H-LC          85257.0      1
L-MC          57751.0      1

In [31]:
# money to be made criteria and conviction-wise
df_portfolio_features.groupby(['Conviction', 'Criteria'])['FTT Amt'].agg(['sum', 'count']).sort_values(by='sum', ascending=False)

                           sum  count
Conviction Criteria
H-SC       XY24      1417680.0      6
           AR         997557.0      5
X-LC       X40        961009.0      7
M-SC       XY24       955848.0      6
H-SC       XR         903149.0      7
X-SC       XY24       873078.0      4
X-MC       X40        732274.0      7
           X40N       563612.0      4
X-SC       X40N       533143.0      4
M-SC       OX40N      409264.0      5
H-SC       OX40N      406105.0      4
X-LC       XY24       394831.0      2
H-SC       SR         320332.0      2
X-LC       X40N       286654.0      2
X-MC       XY24       280956.0      2
           XY25       280787.0      2
H-MC       XY24       248081.0      1
X-SC       X40        216821.0      2
M-SC       XR         198282.0      2
H-MC       AR         180955.0      2
M-LC       XR         160506.0      1
X-LC       XY25       159044.0      2
L-SC       OX40N      113602.0      1
           XR         109630.0      1
H-LC       AR          85257.0      1
M-SC       AR          79647.0      1
M-MC       XY25        73724.0      1
L-MC       XR          57751.0      1
M-MC       AR          55547.0      1

In [32]:
# notebook execution time

end_time = time.time()
execution_time = round(end_time - start_time, 0)
print(f"Notebook execution time: {execution_time} seconds")

Notebook execution time: 28.0 seconds