<a href="https://colab.research.google.com/github/ankit-rathi/Quantvesting_v2/blob/main/myStocks_Portfolio_Analysis.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
'''
!pip install pandas==2.2.2 -qq
!pip install pyxirr -qq
!pip install ta -qq
!pip install yfinance==0.2.59 -qq
'''

'\n!pip install pandas==2.2.2 -qq\n!pip install pyxirr -qq\n!pip install ta -qq\n!pip install yfinance==0.2.59 -qq\n'

In [2]:
# import libraries

import numpy as np
import pandas as pd
import datetime
import warnings
warnings.filterwarnings('ignore')
import yfinance as yfin
import ta
import matplotlib.pyplot as plt
import requests

In [3]:
# notebook start time
import time
import datetime
import pytz

start_time = time.time()

# function to print date timestamp
def print_date_time():
  tz_NY = pytz.timezone('Asia/Kolkata')
  datetime_NY = datetime.datetime.now(tz_NY)
  print("Run date time (IST):", datetime_NY.strftime("%Y-%m-%d %H:%M:%S"))

In [4]:
# function to get booked and reserved amount
def get_amt():
  # fetch the JSON data from the URL
  url = "https://raw.githubusercontent.com/ankit-rathi/Tradevesting_v1/main/data/myPortfolioAmts.json"
  response = requests.get(url)
  pf_amts = response.json()  # parse the JSON data

  # extract values from the JSON
  py_booked_amt_dm = pf_amts["py_booked_amt_dm"]
  py_booked_amt_sv = pf_amts["py_booked_amt_sv"]
  cy_booked_amt_dm = pf_amts["cy_booked_amt_dm"]
  cy_booked_amt_sv = pf_amts["cy_booked_amt_sv"]
  reserve_amt_dm = pf_amts["reserve_amt_dm"]
  reserve_amt_sv = pf_amts["reserve_amt_sv"]

  # perform calculations
  py_booked_amt = py_booked_amt_dm + py_booked_amt_sv
  cy_booked_amt = cy_booked_amt_dm + cy_booked_amt_sv
  reserve_amt = reserve_amt_dm + reserve_amt_sv
  total_booked_amt = py_booked_amt + cy_booked_amt

  return total_booked_amt, reserve_amt, cy_booked_amt, py_booked_amt

gen_output = 0

In [5]:
# function to format the amount
def format_amt(number):
    abs_number = abs(number)

    if abs_number >= 1_00_00_000:  # Crores
        formatted_amt = f"{number / 1_00_00_000:.2f} C"
    elif abs_number >= 1_00_000:  # Lakhs
        formatted_amt = f"{number / 1_00_000:.2f} L"
    elif abs_number >= 1_000:  # Thousands
        formatted_amt = f"{number / 1_000:.2f} K"
    else:
        formatted_amt = f"{number:.2f}"

    return formatted_amt

# function to set start and end date
def get_start_end_date():
  start_date = (datetime.date.today() + datetime.timedelta(days=-365)).strftime('%Y-%m-%d')
  end_date = (datetime.date.today() + datetime.timedelta(days=1)).strftime('%Y-%m-%d')
  return start_date, end_date

# function to fetch my portfolio csv
def get_mypfs_df():
  mypfs_df = pd.read_csv('https://raw.githubusercontent.com/ankit-rathi/Tradevesting_v1/main/data/myPortfolioStocks.csv')
  return mypfs_df

# function to fetch my prospects csv
def get_mypps_df():
  mypps_df = pd.read_csv('https://raw.githubusercontent.com/ankit-rathi/Tradevesting_v1/main/data/myProspectsScrips.csv')
  return mypps_df

# function to fetch screener data
def get_myscreen_df():
  myscreen_df = pd.read_csv('https://raw.githubusercontent.com/ankit-rathi/Tradevesting_v1/main/data/myScreenerDB.csv')
  return myscreen_df

# function to fetch momentum data
def get_myinvmt_df():
  myinvmt_df = pd.read_csv('https://raw.githubusercontent.com/ankit-rathi/Tradevesting_v1/main/data/myInvestments.csv')
  return myinvmt_df

# function to get the stock ids
def get_stock_ids(df_pf):
  stock_n100 = df_pf['Symbol'].unique()

  exclude = ['CADILAHC','MMTC', 'MASFIN']

  stock_ids = df_pf[~df_pf['Symbol'].isin(exclude) ]['Symbol'].unique()

  #mypf = mypf[mypf.Forecast.notnull()]
  #stock_ids = mypf['Symbol'].unique()

  #stock_ids.sort()
  return stock_ids

# get features from screener data
def get_screener_features():
  myscreen_df = get_myscreen_df()
  cols = ['Symbol', 'EPS', 'MedPE', 'ROCE%', 'ROE%', 'CapType']
  return myscreen_df[cols]

# get relative strength
def get_relative_strength(stock_list):

    # Dictionary to store stock tickers and their corresponding percentage price change
    stock_changes = {}

    # Loop through each stock and fetch its price data
    for stock in stock_list:
        try:
            # Download the stock data for the given date range
            stock_data = yfin.Ticker(stock + '.NS').history(period='1mo', interval='1d')[map(str.title, ['open', 'close', 'low', 'high', 'volume'])]

            # Calculate the percentage change for the stock
            if len(stock_data) > 0:
                start_price = stock_data['Close'].iloc[0]
                end_price = stock_data['Close'].iloc[-1]
                percent_change = round(((end_price - start_price) / start_price) * 100, 2)
                stock_changes[stock] = percent_change
            else:
                stock_changes[stock] = np.nan  # If no data is available, set to NaN

        except Exception as e:
            print(f"Error fetching data for {stock}: {e}")
            stock_changes[stock] = np.nan

    # Create a DataFrame with stock tickers and their percentage changes
    df = pd.DataFrame(list(stock_changes.items()), columns=['Symbol', 'Percent_Change'])

    # Drop any stocks with missing data (NaN values)
    df = df.dropna()

    # Calculate the percentile rank based on percentage change
    df['RSP'] = round(df['Percent_Change'].rank(pct=True) * 100, 2)
    cols = ['Symbol', 'RSP']
    df = df[cols]
    # Sort by percentile rank (optional)
    df = df.sort_values(by='RSP', ascending=False).reset_index(drop=True)

    return df

In [6]:
# function to get stock technicals
def stock_prec_dev(stock_symbol):
    #stock_symbol = 'ULTRACEMCO.NS'
    short_window = 20
    mid_window = 50
    long_window = 200
    moving_avg = 'SMA'

    start = datetime.datetime(*map(int, start_date.split('-')))
    end = datetime.datetime(*map(int, end_date.split('-')))

    stock_df = yfin.Ticker(stock_symbol + '.NS').history(period='max', interval='1d')[map(str.title, ['open', 'close', 'low', 'high', 'volume'])]

    stock_df['Max'] = round(max(stock_df['Close']),2)
    stock_df = stock_df[(stock_df.index <= end_date) & (stock_df.index >= start_date)]
    stock_df['200_SMA'] = round(stock_df['Close'].rolling(window = 200, min_periods = 1).mean(),0)
    stock_df['Dev%_200'] = round((stock_df['Close'] - stock_df['200_SMA'])*100/stock_df['200_SMA'],2)
    stock_df.dropna(axis = 0, inplace = True) # remove any null rows

    stock_df['20_SMA'] = stock_df['Close'].rolling(window=20).mean()
    stock_df['50_SMA'] = stock_df['Close'].rolling(window=50).mean()
    stock_df['Symbol'] = stock_symbol

    stock_df['Close'] = round(stock_df['Close'],2)
    stock_df['Min'] = round(min(stock_df['Close']),2)
    stock_df['RSI_14'] = ta.momentum.RSIIndicator(close=stock_df['Close'], window=14).rsi()
    stock_df['RSI_14'] = round(stock_df['RSI_14'],0)
    stock_df['Prev_Close'] = stock_df['Close'].shift(1)
    stock_df.drop(['Open', 'Low', 'High', 'Volume'], axis=1, inplace=True)
    stock_df = stock_df.tail(1)

    max_SMA = max(stock_df['20_SMA'].item(), stock_df['50_SMA'].item(), stock_df['200_SMA'].item())
    min_SMA = min(stock_df['20_SMA'].item(), stock_df['50_SMA'].item(), stock_df['200_SMA'].item())
    ABS_Spread = max_SMA - min_SMA
    stock_df['Spread%'] = round((ABS_Spread / stock_df['200_SMA'].item()) * 100,2)

    return stock_df

# function to compute stock attributes
def get_common_features(stock_ids, df_mypf):

  df_prec_dev = pd.DataFrame()
  df_tmp = get_screener_features()
  df_rs = get_relative_strength(stock_ids)

  for stock_id in stock_ids:
      tmp = stock_prec_dev(stock_id)
      tmp = tmp.reset_index()
      df_prec_dev = pd.concat([df_prec_dev, tmp], ignore_index = True)
  df_prec_dev = pd.merge(df_prec_dev, df_mypf, on= 'Symbol')
  df_prec_dev = pd.merge(df_prec_dev, df_tmp, on= 'Symbol', how='left')
  df_prec_dev = pd.merge(df_prec_dev, df_rs, on= 'Symbol', how='left')
  #print(df_prec_dev.columns)
  df_prec_dev['Curr_PE'] = round(df_prec_dev['Close']/df_prec_dev['EPS'],1)
  df_prec_dev['Dev%_PE'] = round((df_prec_dev['Curr_PE'] - df_prec_dev['MedPE'])*100/df_prec_dev['MedPE'],2)
  df_prec_dev['Conviction'] = df_prec_dev['Conviction'] + '-' + df_prec_dev['CapType']
  return df_prec_dev

# function to arrange stock features
def arrange_features(df_stocks, common_cols, diff_cols):
  df_stocks_common = df_stocks[common_cols].drop_duplicates()
  df_stocks_diff = df_stocks[diff_cols]
  df_stocks_diff['Investment'] = df_stocks_diff['AvgCost'] * df_stocks_diff['Shares']
  df_stocks_diff = df_stocks_diff.groupby(['Symbol'])[['Shares', 'Investment']].aggregate(['sum']).reset_index()
  df_stocks_diff.columns = ['Symbol', 'Shares', 'Investment']
  df_stocks_diff['AvgCost'] = round(df_stocks_diff['Investment']/df_stocks_diff['Shares'],2)
  df_stocks = pd.merge(df_stocks_diff, df_stocks_common, on='Symbol')
  return df_stocks

# plot fact distribution across dimension
def plot_pie_chart(df, dimension, fact):
  # grouping the data by category and calculating the sum of fact for each type
  grouped_data = df.groupby(dimension)[fact].sum()

  # sorting the grouped data in descending order
  grouped_data = grouped_data.sort_values(ascending=False)

  # creating a pie chart
  grouped_data.plot.pie(autopct='%1.1f%%', startangle=90, figsize=(6, 6))

  # adding a title and displaying the plot
  plt.title(f'{dimension} {fact} Distribution')
  plt.ylabel('')  # To hide the y-label
  plt.show()

In [7]:
# function to get portfolio features

def get_portfolio_features(df_common_features):

  print_date_time()
  print('-------------------')

  #df_common_features["Target"] = df_common_features["Target"].fillna(df_common_features["Max"])
  df_common_features['NTT'] = np.where(df_common_features['Strategy']== 'NTT', df_common_features["Target"], df_common_features['Max'])
  df_common_features['LTT'] = np.where(df_common_features['Strategy']== 'BTT', df_common_features["Target"], df_common_features['Max'])
  df_common_features['BOL'] = df_common_features['Min']

  tmp_df = df_common_features[df_common_features['Symbol'].isin(mypf_df[mypf_df['InPortfolio'] != 'NA'].Symbol.values)]
  print('qualified stocks: '+str(len(tmp_df['Symbol'].unique())))
  tmp_df1 = tmp_df[tmp_df['LatestQtr'] == 1]
  print('with latest results: '+str(len(tmp_df1['Symbol'].unique())))
  tmp_df1 = tmp_df1[tmp_df1['StarStock'] == 1]
  print('still star stocks: '+str(len(tmp_df1['Symbol'].unique())))
  tmp_df['Investment'] = tmp_df['AvgCost'] * tmp_df['Shares']
  tmp_df['Current'] = round(tmp_df['Close'] * tmp_df['Shares'],0)
  tmp_df['Previous'] = tmp_df['Prev_Close'] * tmp_df['Shares']
  tmp_df['EstimatedST'] = tmp_df['NTT'] * tmp_df['Shares']
  tmp_df['EstimatedLT'] = tmp_df['LTT'] * tmp_df['Shares']
  tmp_df['Current P/L'] = round((tmp_df['Current'] - tmp_df['Investment']),0)
  tmp_df['Today P/L%'] = round((tmp_df['Current'] - tmp_df['Previous'])*100/tmp_df['Previous'],2)
  tmp_df['Current P/L%'] = round((tmp_df['Current'] - tmp_df['Investment'])*100/tmp_df['Investment'],2)
  tmp_df['EstimatedST P/L%'] = round((tmp_df['EstimatedST'] - tmp_df['Investment'])*100/tmp_df['Investment'],2)
  tmp_df['EstimatedLT P/L%'] = round((tmp_df['EstimatedLT'] - tmp_df['Investment'])*100/tmp_df['Investment'],2)
  tmp_df['NTT%'] = round((tmp_df['NTT'] - tmp_df['Close'])*100/tmp_df['Close'],2)
  tmp_df['LTT%'] = round((tmp_df['LTT'] - tmp_df['Close'])*100/tmp_df['Close'],2)
  tmp_df['Gained%'] = round((tmp_df['Close'] - tmp_df['BOL'])*100/tmp_df['BOL'],2)
  investment = round(sum(tmp_df['AvgCost']*tmp_df['Shares']),0)
  current = round(sum(tmp_df['Close']*tmp_df['Shares']),0)
  tmp_df['InitAlloc%'] = round(tmp_df['Investment']*100/investment,2)
  tmp_df['CurrAlloc%'] = round(tmp_df['Current']*100/current,2)
  tmp_df['FTT'] = tmp_df['LTT']
  tmp_df.loc[tmp_df['Strategy'] == 'NTT', 'FTT'] = tmp_df['NTT']
  tmp_df['FTT%'] = tmp_df['LTT%']
  tmp_df.loc[tmp_df['Strategy'] == 'NTT', 'FTT%'] = tmp_df['NTT%']
  tmp_df['FTT Amt'] = round(tmp_df['FTT%'] * tmp_df['Current']/100,0)
  tmp_df['OTT%'] = round((tmp_df['FTT'] - tmp_df['AvgCost'])*100/tmp_df['AvgCost'],2)
  tmp_df['RRR Ind'] = round(tmp_df['Current P/L']/tmp_df['FTT Amt'],2)
  tmp_df['Risk Ind'] = round(tmp_df['Current P/L%']*tmp_df['CurrAlloc%'],0)

  return tmp_df

# function to print portfolio features
def print_portfolio_stats(df_portfolio_features, myinvmt_df):
  from pyxirr import xirr

  total_booked_amt, reserve_amt, cy_booked_amt, py_booked_amt = get_amt()

  dates = myinvmt_df['Date'].values
  dates = np.append(dates, datetime.date.today().strftime('%d-%b-%y'))
  investment = myinvmt_df['Investment'].values
  dates= pd.to_datetime(dates)

  current = round(sum(df_portfolio_features['Close']*df_portfolio_features['Shares']),0) + reserve_amt
  investment_xirr = np.append(investment, current)
  cagr = round(xirr(pd.DataFrame({"dates": dates, "amounts": investment_xirr}))*100,2)

  investment = -sum(investment)
  invested = round(sum(df_portfolio_features['AvgCost']*df_portfolio_features['Shares']),0) + reserve_amt
  previous = round(sum(df_portfolio_features['Prev_Close']*df_portfolio_features['Shares']),0) + reserve_amt
  cy_invested = investment + py_booked_amt

  today_pnl_amount = current-previous
  today_pnl_percentage = round((current-previous)*100/previous,2)

  curr_pnl_amount = current-invested
  curr_pnl_percentage = round((curr_pnl_amount)*100/(cy_invested),2)

  cy_pnl_amount = cy_booked_amt + curr_pnl_amount
  cy_pnl_percentage = round((cy_pnl_amount)*100/cy_invested,2)

  overall_pnl_amount = total_booked_amt + curr_pnl_amount
  overall_pnl_percentage = round((overall_pnl_amount)*100/investment,2)

  estimate_st = round(sum(df_portfolio_features['FTT']*df_portfolio_features['Shares']),0)  + reserve_amt
  est_st_pnl_amount = estimate_st-current
  est_st_pnl_percentage = round((est_st_pnl_amount)*100/current,2)

  estimate_lt = round(sum(df_portfolio_features['LTT']*df_portfolio_features['Shares']),0)  + reserve_amt
  est_lt_pnl_amount = estimate_lt-current
  est_lt_pnl_percentage = round((est_lt_pnl_amount)*100/current,2)

  total_profit = round(sum(df_portfolio_features[df_portfolio_features['Current P/L%'] > 0]['Current']) - sum(df_portfolio_features[df_portfolio_features['Current P/L%'] > 0]['Investment']),0)
  total_loss = round(sum(df_portfolio_features[df_portfolio_features['Current P/L%'] < 0]['Current']) - sum(df_portfolio_features[df_portfolio_features['Current P/L%'] < 0]['Investment']),0)

  cy_booked_percentage = round((cy_booked_amt)*100/current,2)
  py_booked_percentage = round((py_booked_amt)*100/investment,2)
  total_booked_percentage = round((total_booked_amt)*100/investment,2)

  print('-------------------')
  print('Initial Investment: ', format_amt(investment))
  print('CY Investment: ', format_amt(cy_invested))
  print('Reserve: ', format_amt(reserve_amt))
  print('Current: ',  format_amt(current))
  print('-------------------')
  print('Today PnL: '+ '{} ({}%)'.format(format_amt(today_pnl_amount), today_pnl_percentage))
  print('Current PnL: '+ '{} ({}%)'.format(format_amt(curr_pnl_amount), curr_pnl_percentage))
  print('CY Booked + Current PnL: '+ '{} ({}%)'.format(format_amt(cy_pnl_amount), cy_pnl_percentage))
  print('-------------------')
  print('Total profit: ', format_amt(total_profit))
  print('Total loss: ', format_amt(total_loss))
  print('-------------------')
  print('Total Booked + Current PnL: '+ '{} ({}%)'.format(format_amt(overall_pnl_amount), overall_pnl_percentage))
  print('Total Booked PnL: '+ '{} ({}%)'.format(format_amt(total_booked_amt), total_booked_percentage))
  print('Curr Year Booked PnL: '+ '{} ({}%)'.format(format_amt(cy_booked_amt), cy_booked_percentage))
  print('Prev Year Booked PnL: '+ '{} ({}%)'.format(format_amt(py_booked_amt), py_booked_percentage))
  print('===================')
  print('Est FTT: ',  format_amt(estimate_st))
  print('Est FTT PnL: '+ '{} ({}%)'.format(format_amt(est_st_pnl_amount), est_st_pnl_percentage))

  print('===================')
  print('Deployed: ', format_amt(investment))

  print('Current: ', format_amt(current))

  print('CAGR/XIRR %: '+'{}%'.format(cagr))

In [8]:
# get start and end date
start_date, end_date = get_start_end_date()

# get portfolio and prospects data
mypfs_df = get_mypfs_df()
mypps_df = get_mypps_df()
myinvmt_df = get_myinvmt_df()

# merge above datasets
mypf_df = pd.merge(mypfs_df, mypps_df, on="Symbol")

# seggregate dm and sv portfolio
dm_pf = mypf_df[mypf_df['InPortfolio'] == 'DM']
sv_pf = mypf_df[mypf_df['InPortfolio'] == 'SV']

# build portfolio stock dataframe
dm_stocks = get_stock_ids(dm_pf)
sv_stocks = get_stock_ids(sv_pf)
df_stocks = pd.concat([dm_pf,sv_pf], ignore_index = True)

# arrange common and diff stock features
common_cols = ['Symbol', 'Target', 'Criteria', 'Strategy', 'CumlRnk', 'LatestQtr', 'StarStock', 'Conviction', 'Category', 'InFolio', 'XIRR', 'MBQ']
diff_cols = ['Symbol', 'AvgCost', 'Shares']
df_stocks = arrange_features(df_stocks, common_cols, diff_cols)

# get common features
stock_ids = df_stocks['Symbol'].values
df_common_features = get_common_features(stock_ids, df_stocks)

df_common_features.reset_index(drop=True, inplace=True)
df_common_features.drop(['Date'], axis=1, inplace=True)
# get and print portfolio features
df_portfolio_features = get_portfolio_features(df_common_features)

print_portfolio_stats(df_portfolio_features, myinvmt_df)

df = df_portfolio_features
#plot_pie_chart(df, 'CapType', 'Current')
list_ox40n = list(df[df['MBQ'].str.contains('OX40N', na=False)]['Symbol'].values)

Run date time (IST): 2026-03-23 14:44:11
-------------------
qualified stocks: 86
with latest results: 26
still star stocks: 16
-------------------
Initial Investment:  1.36 C
CY Investment:  1.62 C
Reserve:  1.61 K
Current:  1.27 C
-------------------
Today PnL: -4.40 L (-3.35%)
Current PnL: -50.02 L (-30.79%)
CY Booked + Current PnL: -34.13 L (-21.01%)
-------------------
Total profit:  31.67 K
Total loss:  -50.34 L
-------------------
Total Booked + Current PnL: -7.15 L (-5.28%)
Total Booked PnL: 42.87 L (31.64%)
Curr Year Booked PnL: 15.89 L (12.5%)
Prev Year Booked PnL: 26.98 L (19.91%)
===================
Est FTT:  2.48 C
Est FTT PnL: 1.21 C (95.03%)
===================
Deployed:  1.36 C
Current:  1.27 C
CAGR/XIRR %: -3.13%

In [9]:
# top 5 near their targets
cols = ['Symbol', 'Today P/L%', 'Current P/L%', 'FTT%', 'OTT%', 'FTT Amt', 'Current P/L', 'Current', 'FTT', 'Dev%_PE', 'RSI_14','Conviction', 'Spread%',  'CumlRnk', 'RRR Ind', 'CurrAlloc%', 'Gained%', 'Criteria', 'Strategy', 'Category']
df_tmp = df_portfolio_features[~df_portfolio_features['Symbol'].isin(['ENRIN','BLUSPRING','DIGITIDE'])]
df_tmp = df_tmp.sort_values(by = 'FTT Amt', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
50,MASFIN,-3.16,-10.29,35.51,21.57,31213.0,-10080.0,87900.0,397.04,-22.76,39.0,H-SC,1.73,167.0,-0.32,0.69,19.89,XR,ATH,FINANCE
77,TTKPRESTIG,-2.64,-40.97,69.57,0.09,41385.0,-41290.0,59487.0,770.00,38.10,37.0,M-SC,18.60,250.0,-1.00,0.47,0.51,OX40N,NTT,DURABLES
37,ICICIGI,-2.68,-8.38,30.26,19.34,55478.0,-16771.0,183338.0,2252.93,-23.02,25.0,X-MC,3.18,66.0,-0.30,1.44,1.35,X40,ATH,INSURANCE
67,SONACOMS,-4.02,-15.94,65.47,39.09,55670.0,-16127.0,85032.0,804.02,-33.43,42.0,M-MC,7.91,193.0,-0.29,0.67,20.29,AR,ATH,AUTO
76,TRIDENT,3.88,-32.56,90.55,28.51,56339.0,-30036.0,62219.0,48.00,-13.20,54.0,M-SC,13.76,223.0,-0.53,0.49,14.19,XR,NTT,TEXTILES

In [10]:
# top 5 today
df_tmp = df_portfolio_features.sort_values(by = 'Today P/L%', ascending=False)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
76,TRIDENT,3.88,-32.56,90.55,28.51,56339.0,-30036.0,62219.0,48.00,-13.20,54.0,M-SC,13.76,223.0,-0.53,0.49,14.19,XR,NTT,TEXTILES
69,SURYODAY,3.72,-27.01,68.57,23.03,89623.0,-48368.0,130703.0,216.00,42.54,49.0,H-SC,6.48,166.0,-0.54,1.03,27.74,XR,NTT,BANKS
33,HCLTECH,1.90,-11.80,40.40,23.83,86205.0,-28545.0,213379.0,1908.19,-7.36,42.0,X-LC,11.73,8.0,-0.33,1.68,3.61,X40,ATH,IT
73,TCS,0.28,-29.62,79.85,26.57,260337.0,-137240.0,326033.0,4311.58,-40.35,29.0,X-LC,17.03,2.0,-0.53,2.57,1.75,X40,ATH,IT
43,INFY,0.09,-14.43,56.88,34.24,152291.0,-45147.0,267741.0,1972.00,-32.51,37.0,X-LC,15.08,3.0,-0.30,2.11,2.97,X40,NTT,IT

In [11]:
# bottom 5 today
df_tmp = df_portfolio_features.sort_values(by = 'Today P/L%', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
80,VALIANTORG,-10.06,-49.67,246.00,74.15,202576.0,-81257.0,82348.0,838.00,-247.85,53.0,H-SC,28.39,145.0,-0.40,0.65,22.55,XR,NTT,CHEMICALS
8,AWL,-8.58,-39.52,176.16,67.02,379600.0,-140823.0,215486.0,485.00,-67.43,39.0,X-SC,26.03,81.0,-0.37,1.70,1.93,XY24,NTT,FMCG
26,FINCABLES,-7.92,2.41,103.01,107.91,155759.0,3564.0,151208.0,1641.55,-7.66,43.0,M-SC,8.33,220.0,0.02,1.19,13.76,OX40N,ATH,CABLES
29,GREENPANEL,-7.84,-52.33,200.25,43.14,174776.0,-95799.0,87279.0,537.00,95.74,28.0,M-SC,22.68,225.0,-0.55,0.69,0.00,XY24,NTT,MISC
56,RAJOOENG,-7.23,-49.41,175.99,39.61,91251.0,-50650.0,51850.0,143.10,-65.82,28.0,H-SC,31.87,136.0,-0.56,0.41,0.00,AR,ATH,MISC

In [12]:
# top 5 to exit based on CumlRnk
df_tmp = df_portfolio_features[~df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])]
df_tmp = df_tmp[(df_tmp['Current P/L%'] > -1) & (df_tmp['Current P/L%'] < 1)].sort_values(by = 'CumlRnk', ascending=False)
df_tmp[cols].head()

Empty DataFrame
Columns: [Symbol, Today P/L%, Current P/L%, FTT%, OTT%, FTT Amt, Current P/L, Current, FTT, Dev%_PE, RSI_14, Conviction, Spread%, CumlRnk, RRR Ind, CurrAlloc%, Gained%, Criteria, Strategy, Category]
Index: []

In [13]:
# OX40N stocks to exit
df_tmp = df_portfolio_features[(df_portfolio_features['Symbol'].isin(list_ox40n))].sort_values(by = 'Current P/L%', ascending=False)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
26,FINCABLES,-7.92,2.41,103.01,107.91,155759.0,3564.0,151208.0,1641.55,-7.66,43.0,M-SC,8.33,220.0,0.02,1.19,13.76,OX40N,ATH,CABLES
66,SIS,-2.96,-39.01,98.83,21.26,66923.0,-43317.0,67715.0,528.00,1577.72,28.0,H-SC,14.16,168.0,-0.65,0.53,0.00,OX40N,NTT,MISC
18,CERA,-3.51,-40.03,106.58,23.89,112433.0,-70411.0,105492.0,9475.00,-42.24,40.0,H-SC,18.75,153.0,-0.63,0.83,1.38,OX40N,NTT,CERAMICS
72,TATAELXSI,-2.19,-40.27,121.02,32.03,95304.0,-53084.0,78751.0,9161.00,-25.24,35.0,H-SC,20.61,158.0,-0.56,0.62,2.61,OX40N,NTT,IT
77,TTKPRESTIG,-2.64,-40.97,69.57,0.09,41385.0,-41290.0,59487.0,770.00,38.10,37.0,M-SC,18.60,250.0,-1.00,0.47,0.51,OX40N,NTT,DURABLES

In [14]:
# top 5 to book for rotation
df_tmp = df_portfolio_features[(df_portfolio_features['Current P/L%'] > 20) ].sort_values(by = 'CumlRnk', ascending=False)
df_tmp[cols].head()

Empty DataFrame
Columns: [Symbol, Today P/L%, Current P/L%, FTT%, OTT%, FTT Amt, Current P/L, Current, FTT, Dev%_PE, RSI_14, Conviction, Spread%, CumlRnk, RRR Ind, CurrAlloc%, Gained%, Criteria, Strategy, Category]
Index: []

In [15]:
# top 5 to monitor for exit
df_tmp = df_portfolio_features[~df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])]
df_tmp = df_tmp[(df_tmp['Current P/L%'] > 0) ].sort_values(by = 'Dev%_PE', ascending=False)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
26,FINCABLES,-7.92,2.41,103.01,107.91,155759.0,3564.0,151208.0,1641.55,-7.66,43.0,M-SC,8.33,220.0,0.02,1.19,13.76,OX40N,ATH,CABLES
1,ABB,-4.14,10.74,31.44,45.57,91090.0,28109.0,289728.0,7934.00,-28.84,50.0,H-MC,13.06,125.0,0.31,2.28,28.66,AR,NTT,ELECTRICAL

In [16]:
# top 5 to book for rotation from weak conviction
df_tmp = df_portfolio_features[~df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])]
df_tmp = df_tmp[~df_tmp['Criteria'].isin(['XY25','XY24','X40', 'X40N'])].sort_values(by = 'RRR Ind', ascending=False)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
1,ABB,-4.14,10.74,31.44,45.57,91090.0,28109.0,289728.0,7934.00,-28.84,50.0,H-MC,13.06,125.0,0.31,2.28,28.66,AR,NTT,ELECTRICAL
26,FINCABLES,-7.92,2.41,103.01,107.91,155759.0,3564.0,151208.0,1641.55,-7.66,43.0,M-SC,8.33,220.0,0.02,1.19,13.76,OX40N,ATH,CABLES
40,INDIAMART,-1.30,-15.41,144.39,106.72,150635.0,-19011.0,104325.0,4810.62,-61.91,30.0,H-SC,11.23,140.0,-0.13,0.82,4.36,AR,ATH,MISC
85,ZYDUSLIFE,-2.45,-8.40,48.07,35.63,92281.0,-17602.0,191972.0,1286.17,-20.27,40.0,H-MC,5.37,120.0,-0.19,1.51,6.87,AR,ATH,PHARMA
84,WIPRO,-1.42,-22.81,123.18,72.27,161110.0,-38656.0,130792.0,420.00,-30.18,29.0,M-LC,17.46,98.0,-0.24,1.03,0.00,XR,NTT,IT

In [17]:
# top 5 to accumulate based on lowest RSI_14
df_tmp = df_portfolio_features[df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])].sort_values(by = 'RSI_14', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
53,PGHH,-2.48,-29.07,86.11,32.01,130419.0,-62064.0,151456.0,17616.87,-51.96,12.0,X-MC,15.18,57.0,-0.48,1.19,0.0,X40,ATH,FMCG
58,RELAXO,-5.99,-66.64,356.61,52.31,172667.0,-96741.0,48419.0,1176.00,-64.48,17.0,X-SC,25.54,92.0,-0.56,0.38,0.0,X40N,NTT,FOOTWEAR
12,BATAINDIA,-5.62,-59.62,234.82,35.20,122008.0,-76712.0,51958.0,2096.00,-31.84,18.0,X-SC,30.59,91.0,-0.63,0.41,0.0,X40,NTT,FOOTWEAR
38,ICICIPRULI,-3.40,-11.74,48.12,30.73,83667.0,-23133.0,173872.0,790.00,-35.47,18.0,X-MC,3.88,78.0,-0.28,1.37,0.0,X40,ATH,INSURANCE
34,HDFCBANK,-3.75,-10.13,42.84,28.37,90430.0,-23798.0,211087.0,1073.00,-23.49,20.0,X-LC,11.51,26.0,-0.26,1.66,0.0,X40,BTT,BANKS

In [18]:
# top 5 to accumulate based on Spread and CumlRnk
df_tmp = df_portfolio_features[df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])]
df_tmp = df_tmp[(df_tmp['CumlRnk'] < 100)].sort_values(by = 'Spread%', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
78,UNITDSPR,-1.75,-6.16,28.70,20.77,63058.0,-14431.0,219713.0,1644.00,-16.80,38.0,X-MC,1.43,64.0,-0.23,1.73,0.13,X40N,NTT,BREWERIES
37,ICICIGI,-2.68,-8.38,30.26,19.34,55478.0,-16771.0,183338.0,2252.93,-23.02,25.0,X-MC,3.18,66.0,-0.30,1.44,1.35,X40,ATH,INSURANCE
65,SIEMENS,-3.94,-19.23,55.39,25.51,83259.0,-35780.0,150315.0,4671.50,26.28,39.0,H-LC,3.27,51.0,-0.43,1.18,10.69,AR,ATH,ELECTRICAL
59,RELIANCE,-0.30,-9.48,38.43,25.30,69905.0,-19060.0,181903.0,1952.00,-11.96,50.0,X-LC,3.39,21.0,-0.27,1.43,21.45,XY25,BTT,REFINERIES
38,ICICIPRULI,-3.40,-11.74,48.12,30.73,83667.0,-23133.0,173872.0,790.00,-35.47,18.0,X-MC,3.88,78.0,-0.28,1.37,0.00,X40,ATH,INSURANCE

In [19]:
# top 5 to accumulate based on lowest Gained%
df_tmp = df_portfolio_features[df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])].sort_values(by = 'Gained%', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
2,ABBOTINDIA,-4.55,-14.46,38.02,18.07,58171.0,-25855.0,153000.0,35195.00,-27.11,35.0,X-MC,10.72,58.0,-0.44,1.20,0.0,X40,ATH,PHARMA
3,ACC,-3.52,-40.35,193.07,74.81,308788.0,-108192.0,159936.0,3906.00,-57.90,25.0,X-SC,17.10,85.0,-0.35,1.26,0.0,XY24,BTT,CEMENT
6,ASIANPAINT,-3.04,-23.40,62.55,24.52,135813.0,-66312.0,217127.0,3460.25,-22.73,29.0,X-LC,9.41,30.0,-0.49,1.71,0.0,X40,ATH,PAINTS
9,BAJAJHFL,-3.84,-30.04,131.74,62.13,251652.0,-82024.0,191022.0,181.50,-42.37,25.0,X-MC,20.03,60.0,-0.33,1.50,0.0,X40N,ATH,FINANCE
12,BATAINDIA,-5.62,-59.62,234.82,35.20,122008.0,-76712.0,51958.0,2096.00,-31.84,18.0,X-SC,30.59,91.0,-0.63,0.41,0.0,X40,NTT,FOOTWEAR

In [20]:
# top 5 to accumulate based on lowest CurrAlloc%
df_tmp = df_portfolio_features[df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])].sort_values(by = 'CurrAlloc%', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
58,RELAXO,-5.99,-66.64,356.61,52.31,172667.0,-96741.0,48419.0,1176.00,-64.48,17.0,X-SC,25.54,92.0,-0.56,0.38,0.0,X40N,NTT,FOOTWEAR
12,BATAINDIA,-5.62,-59.62,234.82,35.20,122008.0,-76712.0,51958.0,2096.00,-31.84,18.0,X-SC,30.59,91.0,-0.63,0.41,0.0,X40,NTT,FOOTWEAR
54,QUESS,-4.87,-30.66,150.78,73.90,111657.0,-32740.0,74053.0,424.00,-62.53,30.0,X-SC,20.88,80.0,-0.29,0.58,0.0,XY24,NTT,MISC
36,HONAUT,-3.46,-29.09,113.37,51.31,155033.0,-56088.0,136750.0,58357.33,-41.00,21.0,X-SC,15.41,90.0,-0.36,1.08,0.0,X40N,ATH,ELECTRICAL
51,MEDANTA,-3.46,-16.95,53.05,27.12,77774.0,-29911.0,146606.0,1486.00,-19.47,24.0,X-SC,11.60,87.0,-0.38,1.15,0.0,XY24,NTT,HEALTHCARE

In [21]:
# top 5 to accumulate based on CumlRnk
df_tmp = df_portfolio_features.sort_values(by = 'CumlRnk', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
45,ITC,-3.10,-23.44,55.51,19.06,144560.0,-79744.0,260422.0,452.00,-57.95,29.0,X-LC,18.20,1.0,-0.55,2.05,0.00,X40,NTT,FMCG
73,TCS,0.28,-29.62,79.85,26.57,260337.0,-137240.0,326033.0,4311.58,-40.35,29.0,X-LC,17.03,2.0,-0.53,2.57,1.75,X40,ATH,IT
43,INFY,0.09,-14.43,56.88,34.24,152291.0,-45147.0,267741.0,1972.00,-32.51,37.0,X-LC,15.08,3.0,-0.30,2.11,2.97,X40,NTT,IT
75,TMPV,-2.74,-30.46,96.40,36.58,238547.0,-108386.0,247455.0,600.00,-85.81,32.0,X-LC,6.02,4.0,-0.45,1.95,0.00,XY24,NTT,AUTO
33,HCLTECH,1.90,-11.80,40.40,23.83,86205.0,-28545.0,213379.0,1908.19,-7.36,42.0,X-LC,11.73,8.0,-0.33,1.68,3.61,X40,ATH,IT

In [22]:
# top 5 for average up
df_tmp = df_portfolio_features[(df_portfolio_features['Dev%_200'] > 5)].sort_values(by = 'CurrAlloc%', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
1,ABB,-4.14,10.74,31.44,45.57,91090.0,28109.0,289728.0,7934.0,-28.84,50.0,H-MC,13.06,125.0,0.31,2.28,28.66,AR,NTT,ELECTRICAL

In [23]:
# top 5 RSP
df_tmp = df_portfolio_features.sort_values(by = 'RSP', ascending=False)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
69,SURYODAY,3.72,-27.01,68.57,23.03,89623.0,-48368.0,130703.0,216.00,42.54,49.0,H-SC,6.48,166.0,-0.54,1.03,27.74,XR,NTT,BANKS
30,HAPPSTMNDS,-4.78,-51.16,278.50,84.85,174319.0,-65573.0,62592.0,1480.71,-41.98,52.0,H-SC,26.97,152.0,-0.38,0.49,15.91,AR,ATH,IT
1,ABB,-4.14,10.74,31.44,45.57,91090.0,28109.0,289728.0,7934.00,-28.84,50.0,H-MC,13.06,125.0,0.31,2.28,28.66,AR,NTT,ELECTRICAL
80,VALIANTORG,-10.06,-49.67,246.00,74.15,202576.0,-81257.0,82348.0,838.00,-247.85,53.0,H-SC,28.39,145.0,-0.40,0.65,22.55,XR,NTT,CHEMICALS
59,RELIANCE,-0.30,-9.48,38.43,25.30,69905.0,-19060.0,181903.0,1952.00,-11.96,50.0,X-LC,3.39,21.0,-0.27,1.43,21.45,XY25,BTT,REFINERIES

In [24]:
# Top N allocation
df_tmp = df_portfolio_features.sort_values(by = 'CurrAlloc%', ascending=False)
top_n_values = [10, 25, 50]

sum_df = pd.DataFrame({
    'Top_N': top_n_values,
    'Sum_Alloc%': [df_tmp['CurrAlloc%'].head(n).sum() for n in top_n_values]
})

sum_df

   Top_N  Sum_Alloc%
0     10       20.85
1     25       45.84
2     50       78.10

In [25]:
# market-cap-wise allocation
df_tmp = df_portfolio_features[cols]
df_tmp.groupby(df_tmp['Conviction'].str[-2:])['CurrAlloc%'].sum().sort_values(ascending=False)

Conviction
SC    44.24
MC    30.13
LC    25.66
Name: CurrAlloc%, dtype: float64

In [26]:
# criteria-wise allocation
df_portfolio_features.groupby('Criteria')['CurrAlloc%'].sum().sort_values(ascending=False)

Criteria
XY24     26.80
X40      25.67
X40N     15.06
AR        9.20
XR        8.38
XY25      7.39
OX40N     6.75
SR        0.78
Name: CurrAlloc%, dtype: float64

In [27]:
# conviction-wise allocation
df_portfolio_features.groupby('Conviction')['CurrAlloc%'].sum().sort_values(ascending=False)

Conviction
X-LC    23.45
X-MC    22.63
H-SC    21.54
X-SC    12.19
M-SC     9.98
H-MC     5.10
M-MC     2.05
H-LC     1.18
M-LC     1.03
L-SC     0.53
L-MC     0.35
Name: CurrAlloc%, dtype: float64

In [28]:
# sector-wise stats
df_tmp = df_portfolio_features.groupby('Category')[['CurrAlloc%', 'Current', 'Current P/L', 'FTT Amt']].sum().sort_values(by=['Current', 'Current P/L'], ascending=False)
df_tmp['Current P/L%'] = round(df_tmp['Current P/L'] * 100 / df_tmp['Current'], 2)
df_tmp['FTT%'] = round(df_tmp['FTT Amt'] * 100 / df_tmp['Current'], 2)
cols = ['CurrAlloc%', 'Current P/L%', 'FTT%']
df_tmp[cols].sort_values(by=['CurrAlloc%'], ascending=False)

               CurrAlloc%  Current P/L%    FTT%
Category
FMCG                15.14        -29.93   76.07
FINANCE             13.01        -29.90   82.84
IT                  11.99        -47.97  123.28
MISC                 6.87        -53.68  120.43
ELECTRICAL           6.57        -16.03   60.45
PAINTS               5.06        -53.29   79.91
INSURANCE            4.72        -13.05   51.73
BANKS                4.60        -31.73   98.60
PHARMA               4.15        -11.20   46.20
AUTO                 3.67        -40.41   96.11
AC                   2.04        -23.62   57.15
HEALTHCARE           1.87        -49.90   89.02
TRAVEL               1.81        -93.90  190.99
DURABLES             1.80        -69.37  110.57
FOOTWEAR             1.77        -96.83  175.75
APPARELS             1.73        -21.83   63.39
BREWERIES            1.73         -6.57   28.70
REALTY               1.45        -20.53   40.34
REFINERIES           1.43        -10.48   38.43
CERAMICS             1.38        -75.24  128.47
CEMENT               1.26        -67.65  193.07
CABLES               1.19          2.36  103.01
ENGINEERING          1.07        -77.89  159.25
CHEMICALS            1.07        -94.84  253.81
JEWELLERY            1.06       -139.09  222.16
ENTERTAINMENT        0.76        -99.94  219.19
TEXTILES             0.49        -48.27   90.55
HOTELS               0.34       -161.45  253.67

In [29]:
# money to be made criteria-wise
df_portfolio_features.groupby('Criteria')['FTT Amt'].agg(['sum', 'count']).sort_values(by='sum', ascending=False)

                sum  count
Criteria
XY24      4191270.0     21
X40       1911656.0     16
XR        1426321.0     12
AR        1402015.0     10
X40N      1388841.0     10
OX40N      934812.0     10
XY25       502370.0      5
SR         320678.0      2

In [30]:
# money to be made conviction-wise
df_portfolio_features.groupby('Conviction')['FTT Amt'].agg(['sum', 'count']).sort_values(by='sum', ascending=False)

                  sum  count
Conviction
H-SC        4054410.0     24
X-MC        1856758.0     15
X-LC        1799438.0     13
M-SC        1651238.0     14
X-SC        1633671.0     10
H-MC         430292.0      3
L-SC         223771.0      2
M-LC         161110.0      1
M-MC         126180.0      2
H-LC          83259.0      1
L-MC          57836.0      1

In [31]:
# money to be made criteria and conviction-wise
df_portfolio_features.groupby(['Conviction', 'Criteria'])['FTT Amt'].agg(['sum', 'count']).sort_values(by='sum', ascending=False)

                           sum  count
Conviction Criteria
H-SC       XY24      1423849.0      6
           AR        1000115.0      5
M-SC       XY24       962990.0      6
X-LC       X40        959191.0      7
H-SC       XR         904524.0      7
X-SC       XY24       877819.0      4
X-MC       X40        736353.0      7
           X40N       560964.0      4
X-SC       X40N       539740.0      4
M-SC       OX40N      415966.0      5
H-SC       OX40N      405244.0      4
X-LC       XY24       396739.0      2
H-SC       SR         320678.0      2
X-LC       X40N       288137.0      2
X-MC       XY24       282952.0      2
           XY25       276489.0      2
H-MC       XY24       246921.0      1
X-SC       X40        216112.0      2
M-SC       XR         192682.0      2
H-MC       AR         183371.0      2
M-LC       XR         161110.0      1
X-LC       XY25       155371.0      2
L-SC       OX40N      113602.0      1
           XR         110169.0      1
H-LC       AR          83259.0      1
M-SC       AR          79600.0      1
M-MC       XY25        70510.0      1
L-MC       XR          57836.0      1
M-MC       AR          55670.0      1

In [32]:
# notebook execution time

end_time = time.time()
execution_time = round(end_time - start_time, 0)
print(f"Notebook execution time: {execution_time} seconds")

Notebook execution time: 48.0 seconds