<a href="https://colab.research.google.com/github/ankit-rathi/Quantvesting_v2/blob/main/myStocks_Portfolio_Analysis.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
'''
!pip install pandas==2.2.2 -qq
!pip install pyxirr -qq
!pip install ta -qq
!pip install yfinance==0.2.59 -qq
'''

'\n!pip install pandas==2.2.2 -qq\n!pip install pyxirr -qq\n!pip install ta -qq\n!pip install yfinance==0.2.59 -qq\n'

In [2]:
# import libraries

import numpy as np
import pandas as pd
import datetime
import warnings
warnings.filterwarnings('ignore')
import yfinance as yfin
import ta
import matplotlib.pyplot as plt
import requests

In [3]:
# notebook start time
import time
import datetime
import pytz

start_time = time.time()

# function to print date timestamp
def print_date_time():
  tz_NY = pytz.timezone('Asia/Kolkata')
  datetime_NY = datetime.datetime.now(tz_NY)
  print("Run date time (IST):", datetime_NY.strftime("%Y-%m-%d %H:%M:%S"))

In [4]:
# function to get booked and reserved amount
def get_amt():
  # fetch the JSON data from the URL
  url = "https://raw.githubusercontent.com/ankit-rathi/Tradevesting_v1/main/data/myPortfolioAmts.json"
  response = requests.get(url)
  pf_amts = response.json()  # parse the JSON data

  # extract values from the JSON
  py_booked_amt_dm = pf_amts["py_booked_amt_dm"]
  py_booked_amt_sv = pf_amts["py_booked_amt_sv"]
  cy_booked_amt_dm = pf_amts["cy_booked_amt_dm"]
  cy_booked_amt_sv = pf_amts["cy_booked_amt_sv"]
  reserve_amt_dm = pf_amts["reserve_amt_dm"]
  reserve_amt_sv = pf_amts["reserve_amt_sv"]

  # perform calculations
  py_booked_amt = py_booked_amt_dm + py_booked_amt_sv
  cy_booked_amt = cy_booked_amt_dm + cy_booked_amt_sv
  reserve_amt = reserve_amt_dm + reserve_amt_sv
  total_booked_amt = py_booked_amt + cy_booked_amt

  return total_booked_amt, reserve_amt, cy_booked_amt, py_booked_amt

gen_output = 0

In [5]:
# function to format the amount
def format_amt(number):
    abs_number = abs(number)

    if abs_number >= 1_00_00_000:  # Crores
        formatted_amt = f"{number / 1_00_00_000:.2f} C"
    elif abs_number >= 1_00_000:  # Lakhs
        formatted_amt = f"{number / 1_00_000:.2f} L"
    elif abs_number >= 1_000:  # Thousands
        formatted_amt = f"{number / 1_000:.2f} K"
    else:
        formatted_amt = f"{number:.2f}"

    return formatted_amt

# function to set start and end date
def get_start_end_date():
  start_date = (datetime.date.today() + datetime.timedelta(days=-365)).strftime('%Y-%m-%d')
  end_date = (datetime.date.today() + datetime.timedelta(days=1)).strftime('%Y-%m-%d')
  return start_date, end_date

# function to fetch my portfolio csv
def get_mypfs_df():
  mypfs_df = pd.read_csv('https://raw.githubusercontent.com/ankit-rathi/Tradevesting_v1/main/data/myPortfolioStocks.csv')
  return mypfs_df

# function to fetch my prospects csv
def get_mypps_df():
  mypps_df = pd.read_csv('https://raw.githubusercontent.com/ankit-rathi/Tradevesting_v1/main/data/myProspectsScrips.csv')
  return mypps_df

# function to fetch screener data
def get_myscreen_df():
  myscreen_df = pd.read_csv('https://raw.githubusercontent.com/ankit-rathi/Tradevesting_v1/main/data/myScreenerDB.csv')
  return myscreen_df

# function to fetch momentum data
def get_myinvmt_df():
  myinvmt_df = pd.read_csv('https://raw.githubusercontent.com/ankit-rathi/Tradevesting_v1/main/data/myInvestments.csv')
  return myinvmt_df

# function to get the stock ids
def get_stock_ids(df_pf):
  stock_n100 = df_pf['Symbol'].unique()

  exclude = ['CADILAHC','MMTC', 'MASFIN']

  stock_ids = df_pf[~df_pf['Symbol'].isin(exclude) ]['Symbol'].unique()

  #mypf = mypf[mypf.Forecast.notnull()]
  #stock_ids = mypf['Symbol'].unique()

  #stock_ids.sort()
  return stock_ids

# get features from screener data
def get_screener_features():
  myscreen_df = get_myscreen_df()
  cols = ['Symbol', 'EPS', 'MedPE', 'ROCE%', 'ROE%', 'CapType']
  return myscreen_df[cols]

# get relative strength
def get_relative_strength(stock_list):

    # Dictionary to store stock tickers and their corresponding percentage price change
    stock_changes = {}

    # Loop through each stock and fetch its price data
    for stock in stock_list:
        try:
            # Download the stock data for the given date range
            stock_data = yfin.Ticker(stock + '.NS').history(period='1mo', interval='1d')[map(str.title, ['open', 'close', 'low', 'high', 'volume'])]

            # Calculate the percentage change for the stock
            if len(stock_data) > 0:
                start_price = stock_data['Close'].iloc[0]
                end_price = stock_data['Close'].iloc[-1]
                percent_change = round(((end_price - start_price) / start_price) * 100, 2)
                stock_changes[stock] = percent_change
            else:
                stock_changes[stock] = np.nan  # If no data is available, set to NaN

        except Exception as e:
            print(f"Error fetching data for {stock}: {e}")
            stock_changes[stock] = np.nan

    # Create a DataFrame with stock tickers and their percentage changes
    df = pd.DataFrame(list(stock_changes.items()), columns=['Symbol', 'Percent_Change'])

    # Drop any stocks with missing data (NaN values)
    df = df.dropna()

    # Calculate the percentile rank based on percentage change
    df['RSP'] = round(df['Percent_Change'].rank(pct=True) * 100, 2)
    cols = ['Symbol', 'RSP']
    df = df[cols]
    # Sort by percentile rank (optional)
    df = df.sort_values(by='RSP', ascending=False).reset_index(drop=True)

    return df

In [6]:
# function to get stock technicals
def stock_prec_dev(stock_symbol):
    #stock_symbol = 'ULTRACEMCO.NS'
    short_window = 20
    mid_window = 50
    long_window = 200
    moving_avg = 'SMA'

    start = datetime.datetime(*map(int, start_date.split('-')))
    end = datetime.datetime(*map(int, end_date.split('-')))

    stock_df = yfin.Ticker(stock_symbol + '.NS').history(period='max', interval='1d')[map(str.title, ['open', 'close', 'low', 'high', 'volume'])]

    stock_df['Max'] = round(max(stock_df['Close']),2)
    stock_df = stock_df[(stock_df.index <= end_date) & (stock_df.index >= start_date)]
    stock_df['200_SMA'] = round(stock_df['Close'].rolling(window = 200, min_periods = 1).mean(),0)
    stock_df['Dev%_200'] = round((stock_df['Close'] - stock_df['200_SMA'])*100/stock_df['200_SMA'],2)
    stock_df.dropna(axis = 0, inplace = True) # remove any null rows

    stock_df['20_SMA'] = stock_df['Close'].rolling(window=20).mean()
    stock_df['50_SMA'] = stock_df['Close'].rolling(window=50).mean()
    stock_df['Symbol'] = stock_symbol

    stock_df['Close'] = round(stock_df['Close'],2)
    stock_df['Min'] = round(min(stock_df['Close']),2)
    stock_df['RSI_14'] = ta.momentum.RSIIndicator(close=stock_df['Close'], window=14).rsi()
    stock_df['RSI_14'] = round(stock_df['RSI_14'],0)
    stock_df['Prev_Close'] = stock_df['Close'].shift(1)
    stock_df.drop(['Open', 'Low', 'High', 'Volume'], axis=1, inplace=True)
    stock_df = stock_df.tail(1)

    max_SMA = max(stock_df['20_SMA'].item(), stock_df['50_SMA'].item(), stock_df['200_SMA'].item())
    min_SMA = min(stock_df['20_SMA'].item(), stock_df['50_SMA'].item(), stock_df['200_SMA'].item())
    ABS_Spread = max_SMA - min_SMA
    stock_df['Spread%'] = round((ABS_Spread / stock_df['200_SMA'].item()) * 100,2)

    return stock_df

# function to compute stock attributes
def get_common_features(stock_ids, df_mypf):

  df_prec_dev = pd.DataFrame()
  df_tmp = get_screener_features()
  df_rs = get_relative_strength(stock_ids)

  for stock_id in stock_ids:
      tmp = stock_prec_dev(stock_id)
      tmp = tmp.reset_index()
      df_prec_dev = pd.concat([df_prec_dev, tmp], ignore_index = True)
  df_prec_dev = pd.merge(df_prec_dev, df_mypf, on= 'Symbol')
  df_prec_dev = pd.merge(df_prec_dev, df_tmp, on= 'Symbol', how='left')
  df_prec_dev = pd.merge(df_prec_dev, df_rs, on= 'Symbol', how='left')
  #print(df_prec_dev.columns)
  df_prec_dev['Curr_PE'] = round(df_prec_dev['Close']/df_prec_dev['EPS'],1)
  df_prec_dev['Dev%_PE'] = round((df_prec_dev['Curr_PE'] - df_prec_dev['MedPE'])*100/df_prec_dev['MedPE'],2)
  df_prec_dev['Conviction'] = df_prec_dev['Conviction'] + '-' + df_prec_dev['CapType']
  return df_prec_dev

# function to arrange stock features
def arrange_features(df_stocks, common_cols, diff_cols):
  df_stocks_common = df_stocks[common_cols].drop_duplicates()
  df_stocks_diff = df_stocks[diff_cols]
  df_stocks_diff['Investment'] = df_stocks_diff['AvgCost'] * df_stocks_diff['Shares']
  df_stocks_diff = df_stocks_diff.groupby(['Symbol'])[['Shares', 'Investment']].aggregate(['sum']).reset_index()
  df_stocks_diff.columns = ['Symbol', 'Shares', 'Investment']
  df_stocks_diff['AvgCost'] = round(df_stocks_diff['Investment']/df_stocks_diff['Shares'],2)
  df_stocks = pd.merge(df_stocks_diff, df_stocks_common, on='Symbol')
  return df_stocks

# plot fact distribution across dimension
def plot_pie_chart(df, dimension, fact):
  # grouping the data by category and calculating the sum of fact for each type
  grouped_data = df.groupby(dimension)[fact].sum()

  # sorting the grouped data in descending order
  grouped_data = grouped_data.sort_values(ascending=False)

  # creating a pie chart
  grouped_data.plot.pie(autopct='%1.1f%%', startangle=90, figsize=(6, 6))

  # adding a title and displaying the plot
  plt.title(f'{dimension} {fact} Distribution')
  plt.ylabel('')  # To hide the y-label
  plt.show()

In [7]:
# function to get portfolio features

def get_portfolio_features(df_common_features):

  print_date_time()
  print('-------------------')

  #df_common_features["Target"] = df_common_features["Target"].fillna(df_common_features["Max"])
  df_common_features['NTT'] = np.where(df_common_features['Strategy']== 'NTT', df_common_features["Target"], df_common_features['Max'])
  df_common_features['LTT'] = np.where(df_common_features['Strategy']== 'BTT', df_common_features["Target"], df_common_features['Max'])
  df_common_features['BOL'] = df_common_features['Min']

  tmp_df = df_common_features[df_common_features['Symbol'].isin(mypf_df[mypf_df['InPortfolio'] != 'NA'].Symbol.values)]
  print('qualified stocks: '+str(len(tmp_df['Symbol'].unique())))
  tmp_df1 = tmp_df[tmp_df['LatestQtr'] == 1]
  print('with latest results: '+str(len(tmp_df1['Symbol'].unique())))
  tmp_df1 = tmp_df1[tmp_df1['StarStock'] == 1]
  print('still star stocks: '+str(len(tmp_df1['Symbol'].unique())))
  tmp_df['Investment'] = tmp_df['AvgCost'] * tmp_df['Shares']
  tmp_df['Current'] = round(tmp_df['Close'] * tmp_df['Shares'],0)
  tmp_df['Previous'] = tmp_df['Prev_Close'] * tmp_df['Shares']
  tmp_df['EstimatedST'] = tmp_df['NTT'] * tmp_df['Shares']
  tmp_df['EstimatedLT'] = tmp_df['LTT'] * tmp_df['Shares']
  tmp_df['Current P/L'] = round((tmp_df['Current'] - tmp_df['Investment']),0)
  tmp_df['Today P/L%'] = round((tmp_df['Current'] - tmp_df['Previous'])*100/tmp_df['Previous'],2)
  tmp_df['Current P/L%'] = round((tmp_df['Current'] - tmp_df['Investment'])*100/tmp_df['Investment'],2)
  tmp_df['EstimatedST P/L%'] = round((tmp_df['EstimatedST'] - tmp_df['Investment'])*100/tmp_df['Investment'],2)
  tmp_df['EstimatedLT P/L%'] = round((tmp_df['EstimatedLT'] - tmp_df['Investment'])*100/tmp_df['Investment'],2)
  tmp_df['NTT%'] = round((tmp_df['NTT'] - tmp_df['Close'])*100/tmp_df['Close'],2)
  tmp_df['LTT%'] = round((tmp_df['LTT'] - tmp_df['Close'])*100/tmp_df['Close'],2)
  tmp_df['Gained%'] = round((tmp_df['Close'] - tmp_df['BOL'])*100/tmp_df['BOL'],2)
  investment = round(sum(tmp_df['AvgCost']*tmp_df['Shares']),0)
  current = round(sum(tmp_df['Close']*tmp_df['Shares']),0)
  tmp_df['InitAlloc%'] = round(tmp_df['Investment']*100/investment,2)
  tmp_df['CurrAlloc%'] = round(tmp_df['Current']*100/current,2)
  tmp_df['FTT'] = tmp_df['LTT']
  tmp_df.loc[tmp_df['Strategy'] == 'NTT', 'FTT'] = tmp_df['NTT']
  tmp_df['FTT%'] = tmp_df['LTT%']
  tmp_df.loc[tmp_df['Strategy'] == 'NTT', 'FTT%'] = tmp_df['NTT%']
  tmp_df['FTT Amt'] = round(tmp_df['FTT%'] * tmp_df['Current']/100,0)
  tmp_df['OTT%'] = round((tmp_df['FTT'] - tmp_df['AvgCost'])*100/tmp_df['AvgCost'],2)
  tmp_df['RRR Ind'] = round(tmp_df['Current P/L']/tmp_df['FTT Amt'],2)
  tmp_df['Risk Ind'] = round(tmp_df['Current P/L%']*tmp_df['CurrAlloc%'],0)

  return tmp_df

# function to print portfolio features
def print_portfolio_stats(df_portfolio_features, myinvmt_df):
  from pyxirr import xirr

  total_booked_amt, reserve_amt, cy_booked_amt, py_booked_amt = get_amt()

  dates = myinvmt_df['Date'].values
  dates = np.append(dates, datetime.date.today().strftime('%d-%b-%y'))
  investment = myinvmt_df['Investment'].values
  dates= pd.to_datetime(dates)

  current = round(sum(df_portfolio_features['Close']*df_portfolio_features['Shares']),0) + reserve_amt
  investment_xirr = np.append(investment, current)
  cagr = round(xirr(pd.DataFrame({"dates": dates, "amounts": investment_xirr}))*100,2)

  investment = -sum(investment)
  invested = round(sum(df_portfolio_features['AvgCost']*df_portfolio_features['Shares']),0) + reserve_amt
  previous = round(sum(df_portfolio_features['Prev_Close']*df_portfolio_features['Shares']),0) + reserve_amt
  cy_invested = investment + py_booked_amt

  today_pnl_amount = current-previous
  today_pnl_percentage = round((current-previous)*100/previous,2)

  curr_pnl_amount = current-invested
  curr_pnl_percentage = round((curr_pnl_amount)*100/(cy_invested),2)

  cy_pnl_amount = cy_booked_amt + curr_pnl_amount
  cy_pnl_percentage = round((cy_pnl_amount)*100/cy_invested,2)

  overall_pnl_amount = total_booked_amt + curr_pnl_amount
  overall_pnl_percentage = round((overall_pnl_amount)*100/investment,2)

  estimate_st = round(sum(df_portfolio_features['FTT']*df_portfolio_features['Shares']),0)  + reserve_amt
  est_st_pnl_amount = estimate_st-current
  est_st_pnl_percentage = round((est_st_pnl_amount)*100/current,2)

  estimate_lt = round(sum(df_portfolio_features['LTT']*df_portfolio_features['Shares']),0)  + reserve_amt
  est_lt_pnl_amount = estimate_lt-current
  est_lt_pnl_percentage = round((est_lt_pnl_amount)*100/current,2)

  total_profit = round(sum(df_portfolio_features[df_portfolio_features['Current P/L%'] > 0]['Current']) - sum(df_portfolio_features[df_portfolio_features['Current P/L%'] > 0]['Investment']),0)
  total_loss = round(sum(df_portfolio_features[df_portfolio_features['Current P/L%'] < 0]['Current']) - sum(df_portfolio_features[df_portfolio_features['Current P/L%'] < 0]['Investment']),0)

  cy_booked_percentage = round((cy_booked_amt)*100/current,2)
  py_booked_percentage = round((py_booked_amt)*100/investment,2)
  total_booked_percentage = round((total_booked_amt)*100/investment,2)

  print('-------------------')
  print('Initial Investment: ', format_amt(investment))
  print('CY Investment: ', format_amt(cy_invested))
  print('Reserve: ', format_amt(reserve_amt))
  print('Current: ',  format_amt(current))
  print('-------------------')
  print('Today PnL: '+ '{} ({}%)'.format(format_amt(today_pnl_amount), today_pnl_percentage))
  print('Current PnL: '+ '{} ({}%)'.format(format_amt(curr_pnl_amount), curr_pnl_percentage))
  print('CY Booked + Current PnL: '+ '{} ({}%)'.format(format_amt(cy_pnl_amount), cy_pnl_percentage))
  print('-------------------')
  print('Total profit: ', format_amt(total_profit))
  print('Total loss: ', format_amt(total_loss))
  print('-------------------')
  print('Total Booked + Current PnL: '+ '{} ({}%)'.format(format_amt(overall_pnl_amount), overall_pnl_percentage))
  print('Total Booked PnL: '+ '{} ({}%)'.format(format_amt(total_booked_amt), total_booked_percentage))
  print('Curr Year Booked PnL: '+ '{} ({}%)'.format(format_amt(cy_booked_amt), cy_booked_percentage))
  print('Prev Year Booked PnL: '+ '{} ({}%)'.format(format_amt(py_booked_amt), py_booked_percentage))
  print('===================')
  print('Est FTT: ',  format_amt(estimate_st))
  print('Est FTT PnL: '+ '{} ({}%)'.format(format_amt(est_st_pnl_amount), est_st_pnl_percentage))

  print('===================')
  print('Deployed: ', format_amt(investment))

  print('Current: ', format_amt(current))

  print('CAGR/XIRR %: '+'{}%'.format(cagr))

In [8]:
# get start and end date
start_date, end_date = get_start_end_date()

# get portfolio and prospects data
mypfs_df = get_mypfs_df()
mypps_df = get_mypps_df()
myinvmt_df = get_myinvmt_df()

# merge above datasets
mypf_df = pd.merge(mypfs_df, mypps_df, on="Symbol")

# seggregate dm and sv portfolio
dm_pf = mypf_df[mypf_df['InPortfolio'] == 'DM']
sv_pf = mypf_df[mypf_df['InPortfolio'] == 'SV']

# build portfolio stock dataframe
dm_stocks = get_stock_ids(dm_pf)
sv_stocks = get_stock_ids(sv_pf)
df_stocks = pd.concat([dm_pf,sv_pf], ignore_index = True)

# arrange common and diff stock features
common_cols = ['Symbol', 'Target', 'Criteria', 'Strategy', 'CumlRnk', 'LatestQtr', 'StarStock', 'Conviction', 'Category', 'InFolio', 'XIRR', 'MBQ']
diff_cols = ['Symbol', 'AvgCost', 'Shares']
df_stocks = arrange_features(df_stocks, common_cols, diff_cols)

# get common features
stock_ids = df_stocks['Symbol'].values
df_common_features = get_common_features(stock_ids, df_stocks)

df_common_features.reset_index(drop=True, inplace=True)
df_common_features.drop(['Date'], axis=1, inplace=True)
# get and print portfolio features
df_portfolio_features = get_portfolio_features(df_common_features)

print_portfolio_stats(df_portfolio_features, myinvmt_df)

df = df_portfolio_features
#plot_pie_chart(df, 'CapType', 'Current')
list_ox40n = list(df[df['MBQ'].str.contains('OX40N', na=False)]['Symbol'].values)

Run date time (IST): 2026-08-21 13:50:23
-------------------
qualified stocks: 87
with latest results: 30
still star stocks: 19
-------------------
Initial Investment:  1.46 C
CY Investment:  1.89 C
Reserve:  3.69 L
Current:  1.58 C
-------------------
Today PnL: -24.89 K (-0.16%)
Current PnL: -35.07 L (-18.56%)
CY Booked + Current PnL: -30.01 L (-15.88%)
-------------------
Total profit:  3.46 L
Total loss:  -38.53 L
-------------------
Total Booked + Current PnL: 12.86 L (8.81%)
Total Booked PnL: 47.93 L (32.82%)
Curr Year Booked PnL: 5.06 L (3.2%)
Prev Year Booked PnL: 42.87 L (29.35%)
===================
Est FTT:  2.67 C
Est FTT PnL: 1.09 C (69.18%)
===================
Deployed:  1.46 C
Current:  1.58 C
CAGR/XIRR %: 3.52%

In [9]:
# top 5 near their targets
cols = ['Symbol', 'Today P/L%', 'Current P/L%', 'FTT%', 'OTT%', 'FTT Amt', 'Current P/L', 'Current', 'FTT', 'Dev%_PE', 'RSI_14','Conviction', 'Spread%',  'CumlRnk', 'RRR Ind', 'CurrAlloc%', 'Gained%', 'Criteria', 'Strategy', 'Category']
df_tmp = df_portfolio_features[~df_portfolio_features['Symbol'].isin(['ENRIN','BLUSPRING','DIGITIDE'])]
df_tmp = df_tmp.sort_values(by = 'FTT Amt', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
66,SIEMENS,0.83,5.11,5.44,10.83,10641.0,9510.0,195605.0,4125.00,-14.90,58.0,H-LC,14.32,51.0,0.89,1.27,38.01,AR,NTT,ELECTRICAL
78,UNITDSPR,0.80,14.33,5.63,20.77,15072.0,33557.0,267701.0,1644.00,-2.51,66.0,X-MC,11.98,64.0,2.23,1.74,28.68,X40N,NTT,BREWERIES
77,TTKPRESTIG,-0.05,-23.00,29.99,0.09,23272.0,-23179.0,77598.0,770.00,-6.23,42.0,M-SC,9.05,250.0,-1.00,0.50,39.67,OX40N,NTT,DURABLES
52,M&M,0.07,8.22,9.79,18.82,25501.0,19794.0,260475.0,3762.88,-6.55,59.0,X-LC,5.03,25.0,0.78,1.69,18.16,X40N,ATH,AUTO
67,SIS,1.52,-3.66,25.86,21.26,27663.0,-4060.0,106972.0,528.00,105.79,44.0,H-SC,20.13,168.0,-0.15,0.69,59.05,OX40N,NTT,MISC

In [10]:
# top 5 today
df_tmp = df_portfolio_features.sort_values(by = 'Today P/L%', ascending=False)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
30,HAPPSTMNDS,5.90,-45.23,234.25,83.08,164444.0,-57965.0,70200.0,1466.54,NaN,69.0,NaN,6.58,152.0,-0.35,0.46,31.49,AR,ATH,IT
3,ALKYLAMINE,5.48,-13.57,122.78,92.54,107138.0,-13703.0,87260.0,4520.85,NaN,65.0,NaN,15.58,142.0,-0.13,0.57,65.70,SR,ATH,CHEMICALS
24,EASEMYTRIP,4.60,-64.85,314.44,45.70,195450.0,-114657.0,62158.0,26.40,NaN,44.0,NaN,7.65,204.0,-0.59,0.40,8.89,XY24,NTT,TRAVEL
40,ICICIPRULI,2.86,-14.56,52.47,30.28,88323.0,-28675.0,168330.0,787.27,-45.16,58.0,X-MC,11.89,78.0,-0.32,1.09,12.15,X40,ATH,INSURANCE
14,CAMPUS,2.43,-22.49,71.96,33.28,93576.0,-37736.0,130039.0,393.00,NaN,58.0,NaN,9.80,218.0,-0.40,0.84,6.35,XY24,NTT,FOOTWEAR

In [11]:
# bottom 5 today
df_tmp = df_portfolio_features.sort_values(by = 'Today P/L%', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
27,GLAXO,-2.67,17.20,15.78,35.69,36856.0,34276.0,233560.0,3380.16,-12.14,71.0,X-MC,11.57,56.0,0.93,1.51,38.81,X40,ATH,PHARMA
51,LAOPALA,-2.30,-47.77,166.28,39.09,113869.0,-62625.0,68480.0,464.00,NaN,38.0,NaN,3.13,154.0,-0.55,0.44,9.17,AR,NTT,CERAMICS
81,VALIANTORG,-2.24,-36.82,175.66,74.15,181562.0,-60245.0,103360.0,838.00,NaN,54.0,NaN,9.64,145.0,-0.33,0.67,53.82,XR,NTT,CHEMICALS
23,DMART,-1.89,-5.30,38.78,31.42,114502.0,-16530.0,295260.0,5391.45,-20.63,39.0,X-LC,2.51,14.0,-0.14,1.91,6.55,X40N,ATH,FMCG
25,FINCABLES,-1.75,60.68,29.40,107.91,69745.0,89584.0,237228.0,1641.55,16.85,66.0,M-SC,22.48,220.0,1.28,1.54,78.47,OX40N,ATH,CABLES

In [12]:
# top 5 to exit based on CumlRnk
df_tmp = df_portfolio_features[~df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])]
df_tmp = df_tmp[(df_tmp['Current P/L%'] > -1) & (df_tmp['Current P/L%'] < 1)].sort_values(by = 'CumlRnk', ascending=False)
df_tmp[cols].head()

Empty DataFrame
Columns: [Symbol, Today P/L%, Current P/L%, FTT%, OTT%, FTT Amt, Current P/L, Current, FTT, Dev%_PE, RSI_14, Conviction, Spread%, CumlRnk, RRR Ind, CurrAlloc%, Gained%, Criteria, Strategy, Category]
Index: []

In [13]:
# OX40N stocks to exit
df_tmp = df_portfolio_features[(df_portfolio_features['Symbol'].isin(list_ox40n))].sort_values(by = 'Current P/L%', ascending=False)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
25,FINCABLES,-1.75,60.68,29.40,107.91,69745.0,89584.0,237228.0,1641.55,16.85,66.0,M-SC,22.48,220.0,1.28,1.54,78.47,OX40N,ATH,CABLES
67,SIS,1.52,-3.66,25.86,21.26,27663.0,-4060.0,106972.0,528.00,105.79,44.0,H-SC,20.13,168.0,-0.15,0.69,59.05,OX40N,NTT,MISC
43,INDIGOPNTS,1.80,-18.23,22.32,0.02,31859.0,-31823.0,142736.0,1408.00,-22.11,61.0,M-SC,8.13,222.0,-1.00,0.93,61.94,OX40N,NTT,PAINTS
77,TTKPRESTIG,-0.05,-23.00,29.99,0.09,23272.0,-23179.0,77598.0,770.00,-6.23,42.0,M-SC,9.05,250.0,-1.00,0.50,39.67,OX40N,NTT,DURABLES
16,CERA,0.03,-23.38,61.69,23.89,83146.0,-41123.0,134780.0,9475.00,NaN,42.0,NaN,13.01,153.0,-0.49,0.87,31.02,OX40N,NTT,CERAMICS

In [14]:
# top 5 to book for rotation
df_tmp = df_portfolio_features[(df_portfolio_features['Current P/L%'] > 20) ].sort_values(by = 'CumlRnk', ascending=False)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
25,FINCABLES,-1.75,60.68,29.4,107.91,69745.0,89584.0,237228.0,1641.55,16.85,66.0,M-SC,22.48,220.0,1.28,1.54,78.47,OX40N,ATH,CABLES

In [15]:
# top 5 to monitor for exit
df_tmp = df_portfolio_features[~df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])]
df_tmp = df_tmp[(df_tmp['Current P/L%'] > 0) ].sort_values(by = 'Dev%_PE', ascending=False)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
25,FINCABLES,-1.75,60.68,29.40,107.91,69745.0,89584.0,237228.0,1641.55,16.85,66.0,M-SC,22.48,220.0,1.28,1.54,78.47,OX40N,ATH,CABLES
68,STARHEALTH,-0.61,10.69,33.04,47.26,102810.0,30045.0,311168.0,761.00,-2.33,42.0,H-SC,15.70,173.0,0.29,2.02,34.54,XY24,NTT,INSURANCE

In [16]:
# top 5 to book for rotation from weak conviction
df_tmp = df_portfolio_features[~df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])]
df_tmp = df_tmp[~df_tmp['Criteria'].isin(['XY25','XY24','X40', 'X40N'])].sort_values(by = 'RRR Ind', ascending=False)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
25,FINCABLES,-1.75,60.68,29.40,107.91,69745.0,89584.0,237228.0,1641.55,16.85,66.0,M-SC,22.48,220.0,1.28,1.54,78.47,OX40N,ATH,CABLES
3,ALKYLAMINE,5.48,-13.57,122.78,92.54,107138.0,-13703.0,87260.0,4520.85,NaN,65.0,NaN,15.58,142.0,-0.13,0.57,65.70,SR,ATH,CHEMICALS
67,SIS,1.52,-3.66,25.86,21.26,27663.0,-4060.0,106972.0,528.00,105.79,44.0,H-SC,20.13,168.0,-0.15,0.69,59.05,OX40N,NTT,MISC
42,INDIAMART,-0.30,-25.06,168.10,100.92,155378.0,-30904.0,92432.0,4675.60,NaN,38.0,NaN,13.59,140.0,-0.20,0.60,0.56,AR,ATH,MISC
71,TANLA,0.06,-35.23,235.40,117.25,412854.0,-95377.0,175384.0,1922.32,NaN,46.0,NaN,15.01,147.0,-0.23,1.14,53.55,AR,ATH,IT

In [17]:
# top 5 to accumulate based on lowest RSI_14
df_tmp = df_portfolio_features[df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])].sort_values(by = 'RSI_14', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
56,PGHH,-0.73,-38.64,115.15,32.01,150856.0,-82512.0,131008.0,17616.87,-54.92,26.0,X-SC,19.61,57.0,-0.55,0.85,0.00,X40,ATH,FMCG
55,PAGEIND,-0.06,-7.45,43.54,32.85,108151.0,-19984.0,248395.0,50936.07,-31.21,30.0,X-MC,8.63,55.0,-0.18,1.61,18.61,X40,ATH,APPARELS
19,COLPAL,-1.36,-28.46,95.51,39.86,179941.0,-74965.0,188400.0,3683.41,-13.40,31.0,X-MC,2.33,62.0,-0.42,1.22,6.57,XY25,ATH,FMCG
20,DABUR,-0.51,-22.20,84.70,43.70,163476.0,-55062.0,193006.0,735.00,-32.86,32.0,X-MC,10.35,70.0,-0.34,1.25,0.00,XY24,BTT,FMCG
1,ABBOTINDIA,-0.46,-12.78,32.27,15.37,50341.0,-22855.0,156000.0,34390.26,-29.03,32.0,X-MC,2.88,58.0,-0.45,1.01,5.67,X40,ATH,PHARMA

In [18]:
# top 5 to accumulate based on Spread and CumlRnk
df_tmp = df_portfolio_features[df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])]
df_tmp = df_tmp[(df_tmp['CumlRnk'] < 100)].sort_values(by = 'Spread%', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
50,KOTAKBANK,1.31,5.80,12.40,18.92,31447.0,13904.0,253606.0,452.46,-10.58,62.0,X-LC,2.10,12.0,0.44,1.64,14.10,X40,ATH,BANKS
19,COLPAL,-1.36,-28.46,95.51,39.86,179941.0,-74965.0,188400.0,3683.41,-13.40,31.0,X-MC,2.33,62.0,-0.42,1.22,6.57,XY25,ATH,FMCG
23,DMART,-1.89,-5.30,38.78,31.42,114502.0,-16530.0,295260.0,5391.45,-20.63,39.0,X-LC,2.51,14.0,-0.14,1.91,6.55,X40N,ATH,FMCG
1,ABBOTINDIA,-0.46,-12.78,32.27,15.37,50341.0,-22855.0,156000.0,34390.26,-29.03,32.0,X-MC,2.88,58.0,-0.45,1.01,5.67,X40,ATH,PHARMA
7,BAJAJHFL,-0.64,-24.04,113.43,62.13,235269.0,-65633.0,207413.0,181.50,-36.70,46.0,X-MC,3.81,60.0,-0.28,1.35,16.35,X40N,ATH,FINANCE

In [19]:
# top 5 to accumulate based on lowest Gained%
df_tmp = df_portfolio_features[df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])].sort_values(by = 'Gained%', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
20,DABUR,-0.51,-22.20,84.70,43.70,163476.0,-55062.0,193006.0,735.00,-32.86,32.0,X-MC,10.35,70.0,-0.34,1.25,0.00,XY24,BTT,FMCG
56,PGHH,-0.73,-38.64,115.15,32.01,150856.0,-82512.0,131008.0,17616.87,-54.92,26.0,X-SC,19.61,57.0,-0.55,0.85,0.00,X40,ATH,FMCG
36,HINDUNILVR,-0.28,-15.87,44.49,21.56,125961.0,-53395.0,283122.0,2922.00,-41.98,38.0,X-LC,6.81,9.0,-0.42,1.84,0.08,XY25,NTT,FMCG
83,VOLTAS,0.53,-4.09,51.39,45.20,94506.0,-7842.0,183900.0,1856.00,32.05,36.0,X-MC,5.17,79.0,-0.08,1.19,0.79,XY25,NTT,AC
47,ITC,-0.81,-25.66,67.75,24.70,200077.0,-101961.0,295317.0,452.00,-30.75,35.0,X-LC,10.49,1.0,-0.51,1.92,0.90,X40,NTT,FMCG

In [20]:
# top 5 to accumulate based on lowest CurrAlloc%
df_tmp = df_portfolio_features[df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])].sort_values(by = 'CurrAlloc%', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
56,PGHH,-0.73,-38.64,115.15,32.01,150856.0,-82512.0,131008.0,17616.87,-54.92,26.0,X-SC,19.61,57.0,-0.55,0.85,0.00,X40,ATH,FMCG
1,ABBOTINDIA,-0.46,-12.78,32.27,15.37,50341.0,-22855.0,156000.0,34390.26,-29.03,32.0,X-MC,2.88,58.0,-0.45,1.01,5.67,X40,ATH,PHARMA
2,ACC,0.54,-41.46,198.60,74.81,311746.0,-111156.0,156972.0,3906.00,-41.79,40.0,X-SC,11.35,85.0,-0.36,1.02,4.87,XY24,BTT,CEMENT
40,ICICIPRULI,2.86,-14.56,52.47,30.28,88323.0,-28675.0,168330.0,787.27,-45.16,58.0,X-MC,11.89,78.0,-0.32,1.09,12.15,X40,ATH,INSURANCE
39,ICICIGI,-0.32,-14.20,38.56,18.89,66207.0,-28410.0,171699.0,2244.41,-14.59,41.0,X-MC,10.04,66.0,-0.43,1.11,2.29,X40,ATH,INSURANCE

In [21]:
# top 5 to accumulate based on CumlRnk
df_tmp = df_portfolio_features.sort_values(by = 'CumlRnk', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
47,ITC,-0.81,-25.66,67.75,24.70,200077.0,-101961.0,295317.0,452.00,-30.75,35.0,X-LC,10.49,1.0,-0.51,1.92,0.90,X40,NTT,FMCG
73,TCS,-0.17,-32.65,84.42,24.20,263389.0,-151275.0,311998.0,4230.71,-43.98,47.0,X-LC,13.66,2.0,-0.57,2.02,16.35,X40,ATH,IT
45,INFY,-0.26,-19.76,74.96,40.38,226426.0,-74407.0,302063.0,1972.00,-40.86,49.0,X-LC,15.60,3.0,-0.33,1.96,14.39,X40,NTT,IT
75,TMPV,-0.94,-24.52,89.13,42.75,279938.0,-102029.0,314078.0,600.00,-84.91,33.0,X-LC,4.41,4.0,-0.36,2.04,8.00,XY24,NTT,AUTO
33,HCLTECH,-0.42,-12.19,41.17,23.97,111888.0,-37716.0,271770.0,1853.42,-14.26,53.0,X-LC,10.31,8.0,-0.34,1.76,28.24,X40,ATH,IT

In [22]:
# top 5 for average up
df_tmp = df_portfolio_features[(df_portfolio_features['Dev%_200'] > 5)].sort_values(by = 'CurrAlloc%', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
44,INDUSINDBK,-0.65,-26.07,79.75,32.89,45521.0,-20126.0,57080.0,1800.00,320.23,47.0,L-MC,12.14,258.0,-0.44,0.37,40.73,XR,NTT,BANKS
30,HAPPSTMNDS,5.90,-45.23,234.25,83.08,164444.0,-57965.0,70200.0,1466.54,NaN,69.0,NaN,6.58,152.0,-0.35,0.46,31.49,AR,ATH,IT
3,ALKYLAMINE,5.48,-13.57,122.78,92.54,107138.0,-13703.0,87260.0,4520.85,NaN,65.0,NaN,15.58,142.0,-0.13,0.57,65.70,SR,ATH,CHEMICALS
12,BOSCH-HCIL,-1.43,-23.47,30.65,-0.01,29979.0,-29995.0,97810.0,2282.00,765.43,74.0,M-SC,10.74,231.0,-1.00,0.63,66.49,OX40N,BTT,AC
81,VALIANTORG,-2.24,-36.82,175.66,74.15,181562.0,-60245.0,103360.0,838.00,NaN,54.0,NaN,9.64,145.0,-0.33,0.67,53.82,XR,NTT,CHEMICALS

In [23]:
# top 5 RSP
df_tmp = df_portfolio_features.sort_values(by = 'RSP', ascending=False)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
12,BOSCH-HCIL,-1.43,-23.47,30.65,-0.01,29979.0,-29995.0,97810.0,2282.00,765.43,74.0,M-SC,10.74,231.0,-1.00,0.63,66.49,OX40N,BTT,AC
25,FINCABLES,-1.75,60.68,29.40,107.91,69745.0,89584.0,237228.0,1641.55,16.85,66.0,M-SC,22.48,220.0,1.28,1.54,78.47,OX40N,ATH,CABLES
30,HAPPSTMNDS,5.90,-45.23,234.25,83.08,164444.0,-57965.0,70200.0,1466.54,NaN,69.0,NaN,6.58,152.0,-0.35,0.46,31.49,AR,ATH,IT
27,GLAXO,-2.67,17.20,15.78,35.69,36856.0,34276.0,233560.0,3380.16,-12.14,71.0,X-MC,11.57,56.0,0.93,1.51,38.81,X40,ATH,PHARMA
38,HYUNDAI,-0.58,14.52,25.68,43.94,73916.0,36501.0,287833.0,2782.73,18.51,64.0,X-LC,6.14,29.0,0.49,1.87,32.15,X40N,ATH,AUTO

In [24]:
# Top N allocation
df_tmp = df_portfolio_features.sort_values(by = 'CurrAlloc%', ascending=False)
top_n_values = [10, 25, 50]

sum_df = pd.DataFrame({
    'Top_N': top_n_values,
    'Sum_Alloc%': [df_tmp['CurrAlloc%'].head(n).sum() for n in top_n_values]
})

sum_df

   Top_N  Sum_Alloc%
0     10       19.62
1     25       44.99
2     50       77.58

In [25]:
# market-cap-wise allocation
df_tmp = df_portfolio_features[cols]
df_tmp.groupby(df_tmp['Conviction'].str[-2:])['CurrAlloc%'].sum().sort_values(ascending=False)

Conviction
LC    38.03
MC    22.18
SC    21.62
Name: CurrAlloc%, dtype: float64

In [26]:
# criteria-wise allocation
df_portfolio_features.groupby('Criteria')['CurrAlloc%'].sum().sort_values(ascending=False)

Criteria
X40      26.71
XY24     23.97
X40N     18.72
XR        9.13
OX40N     7.32
XY25      7.15
AR        6.11
SR        0.90
Name: CurrAlloc%, dtype: float64

In [27]:
# conviction-wise allocation
df_portfolio_features.groupby('Conviction')['CurrAlloc%'].sum().sort_values(ascending=False)

Conviction
X-LC    34.37
X-MC    19.62
H-SC     8.56
X-SC     7.65
M-SC     5.41
H-LC     2.85
M-MC     1.17
H-MC     1.02
M-LC     0.81
L-MC     0.37
Name: CurrAlloc%, dtype: float64

In [28]:
# sector-wise stats
df_tmp = df_portfolio_features.groupby('Category')[['CurrAlloc%', 'Current', 'Current P/L', 'FTT Amt']].sum().sort_values(by=['Current', 'Current P/L'], ascending=False)
df_tmp['Current P/L%'] = round(df_tmp['Current P/L'] * 100 / df_tmp['Current'], 2)
df_tmp['FTT%'] = round(df_tmp['FTT Amt'] * 100 / df_tmp['Current'], 2)
cols = ['CurrAlloc%', 'Current P/L%', 'FTT%']
df_tmp[cols].sort_values(by=['CurrAlloc%'], ascending=False)

               CurrAlloc%  Current P/L%    FTT%
Category
FMCG                15.34        -26.07   71.40
IT                  11.27        -37.23  105.29
FINANCE             10.74        -16.57   66.78
AUTO                 8.26         -6.32   44.40
BANKS                6.29        -10.19   57.71
MISC                 5.95        -34.55   88.67
PHARMA               5.80          7.29   19.01
INSURANCE            5.75         -4.64   41.64
PAINTS               5.46        -17.15   37.13
ELECTRICAL           4.19         -9.62   43.94
AC                   1.82        -13.43   44.19
BREWERIES            1.74         12.54    5.63
REFINERIES           1.73        -11.55   49.02
FOOTWEAR             1.68        -70.45  138.80
APPARELS             1.61         -8.05   43.54
CABLES               1.54         37.76   29.40
DURABLES             1.48        -69.20  110.35
TRAVEL               1.42       -103.38  205.22
CERAMICS             1.31        -51.04   96.93
ENGINEERING          1.25        -25.51   82.91
CHEMICALS            1.24        -38.79  151.45
CEMENT               1.02        -70.81  198.60
JEWELLERY            0.97       -115.37  190.20
ENTERTAINMENT        0.71        -75.76  180.58
HEALTHCARE           0.69        -69.84  112.48
TEXTILES             0.39        -52.20   95.60
HOTELS               0.36       -104.57  176.72

In [29]:
# money to be made criteria-wise
df_portfolio_features.groupby('Criteria')['FTT Amt'].agg(['sum', 'count']).sort_values(by='sum', ascending=False)

                sum  count
Criteria
XY24      3631677.0     19
X40       2103344.0     18
XR        1388769.0     13
X40N      1196851.0     12
AR        1065157.0      8
OX40N      661846.0     10
XY25       596742.0      5
SR         277957.0      2

In [30]:
# money to be made conviction-wise
df_portfolio_features.groupby('Conviction')['FTT Amt'].agg(['sum', 'count']).sort_values(by='sum', ascending=False)

                  sum  count
Conviction
X-LC        2427756.0     19
X-MC        1475037.0     14
X-SC        1101170.0      6
H-SC         831629.0      8
M-SC         329447.0      6
H-MC         255910.0      1
M-LC         166310.0      1
M-MC          65343.0      1
H-LC          51592.0      2
L-MC          45521.0      1

In [31]:
# money to be made criteria and conviction-wise
df_portfolio_features.groupby(['Conviction', 'Criteria'])['FTT Amt'].agg(['sum', 'count']).sort_values(by='sum', ascending=False)

                           sum  count
Conviction Criteria
X-LC       X40       1218180.0      9
X-SC       XY24       673192.0      2
H-SC       XY24       527484.0      3
X-MC       X40        514895.0      6
X-LC       XY24       464419.0      2
X-MC       X40N       448200.0      4
X-LC       X40N       424925.0      5
X-MC       XY25       274447.0      2
X-LC       XY25       256952.0      2
H-MC       XY24       255910.0      1
X-SC       X40        254632.0      2
X-MC       XY24       237495.0      2
H-SC       OX40N      217063.0      3
X-SC       X40N       173346.0      2
M-LC       XR         166310.0      1
M-SC       OX40N      154855.0      4
           XY24       116645.0      1
H-SC       XR          87082.0      2
M-MC       XY25        65343.0      1
X-LC       XR          63280.0      1
M-SC       XR          57947.0      1
H-LC       AR          51592.0      2
L-MC       XR          45521.0      1

In [32]:
# notebook execution time

end_time = time.time()
execution_time = round(end_time - start_time, 0)
print(f"Notebook execution time: {execution_time} seconds")

Notebook execution time: 29.0 seconds