<a href="https://colab.research.google.com/github/ankit-rathi/Quantvesting_v2/blob/main/myStocks_Portfolio_Analysis.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
'''
!pip install pandas==2.2.2 -qq
!pip install pyxirr -qq
!pip install ta -qq
!pip install yfinance==0.2.59 -qq
'''

'\n!pip install pandas==2.2.2 -qq\n!pip install pyxirr -qq\n!pip install ta -qq\n!pip install yfinance==0.2.59 -qq\n'

In [2]:
# import libraries

import numpy as np
import pandas as pd
import datetime
import warnings
warnings.filterwarnings('ignore')
import yfinance as yfin
import ta
import matplotlib.pyplot as plt
import requests

In [3]:
# notebook start time
import time
import datetime
import pytz

start_time = time.time()

# function to print date timestamp
def print_date_time():
  tz_NY = pytz.timezone('Asia/Kolkata')
  datetime_NY = datetime.datetime.now(tz_NY)
  print("Run date time (IST):", datetime_NY.strftime("%Y-%m-%d %H:%M:%S"))

In [4]:
# function to get booked and reserved amount
def get_amt():
  # fetch the JSON data from the URL
  url = "https://raw.githubusercontent.com/ankit-rathi/Tradevesting_v1/main/data/myPortfolioAmts.json"
  response = requests.get(url)
  pf_amts = response.json()  # parse the JSON data

  # extract values from the JSON
  py_booked_amt_dm = pf_amts["py_booked_amt_dm"]
  py_booked_amt_sv = pf_amts["py_booked_amt_sv"]
  cy_booked_amt_dm = pf_amts["cy_booked_amt_dm"]
  cy_booked_amt_sv = pf_amts["cy_booked_amt_sv"]
  reserve_amt_dm = pf_amts["reserve_amt_dm"]
  reserve_amt_sv = pf_amts["reserve_amt_sv"]

  # perform calculations
  py_booked_amt = py_booked_amt_dm + py_booked_amt_sv
  cy_booked_amt = cy_booked_amt_dm + cy_booked_amt_sv
  reserve_amt = reserve_amt_dm + reserve_amt_sv
  total_booked_amt = py_booked_amt + cy_booked_amt

  return total_booked_amt, reserve_amt, cy_booked_amt, py_booked_amt

gen_output = 0

In [5]:
# function to format the amount
def format_amt(number):
    abs_number = abs(number)

    if abs_number >= 1_00_00_000:  # Crores
        formatted_amt = f"{number / 1_00_00_000:.2f} C"
    elif abs_number >= 1_00_000:  # Lakhs
        formatted_amt = f"{number / 1_00_000:.2f} L"
    elif abs_number >= 1_000:  # Thousands
        formatted_amt = f"{number / 1_000:.2f} K"
    else:
        formatted_amt = f"{number:.2f}"

    return formatted_amt

# function to set start and end date
def get_start_end_date():
  start_date = (datetime.date.today() + datetime.timedelta(days=-365)).strftime('%Y-%m-%d')
  end_date = (datetime.date.today() + datetime.timedelta(days=1)).strftime('%Y-%m-%d')
  return start_date, end_date

# function to fetch my portfolio csv
def get_mypfs_df():
  mypfs_df = pd.read_csv('https://raw.githubusercontent.com/ankit-rathi/Tradevesting_v1/main/data/myPortfolioStocks.csv')
  return mypfs_df

# function to fetch my prospects csv
def get_mypps_df():
  mypps_df = pd.read_csv('https://raw.githubusercontent.com/ankit-rathi/Tradevesting_v1/main/data/myProspectsScrips.csv')
  return mypps_df

# function to fetch screener data
def get_myscreen_df():
  myscreen_df = pd.read_csv('https://raw.githubusercontent.com/ankit-rathi/Tradevesting_v1/main/data/myScreenerDB.csv')
  return myscreen_df

# function to fetch momentum data
def get_myinvmt_df():
  myinvmt_df = pd.read_csv('https://raw.githubusercontent.com/ankit-rathi/Tradevesting_v1/main/data/myInvestments.csv')
  return myinvmt_df

# function to get the stock ids
def get_stock_ids(df_pf):
  stock_n100 = df_pf['Symbol'].unique()

  exclude = ['CADILAHC','MMTC', 'MASFIN']

  stock_ids = df_pf[~df_pf['Symbol'].isin(exclude) ]['Symbol'].unique()

  #mypf = mypf[mypf.Forecast.notnull()]
  #stock_ids = mypf['Symbol'].unique()

  #stock_ids.sort()
  return stock_ids

# get features from screener data
def get_screener_features():
  myscreen_df = get_myscreen_df()
  cols = ['Symbol', 'EPS', 'MedPE', 'ROCE%', 'ROE%', 'CapType']
  return myscreen_df[cols]

# get relative strength
def get_relative_strength(stock_list):

    # Dictionary to store stock tickers and their corresponding percentage price change
    stock_changes = {}

    # Loop through each stock and fetch its price data
    for stock in stock_list:
        try:
            # Download the stock data for the given date range
            stock_data = yfin.Ticker(stock + '.NS').history(period='1mo', interval='1d')[map(str.title, ['open', 'close', 'low', 'high', 'volume'])]

            # Calculate the percentage change for the stock
            if len(stock_data) > 0:
                start_price = stock_data['Close'].iloc[0]
                end_price = stock_data['Close'].iloc[-1]
                percent_change = round(((end_price - start_price) / start_price) * 100, 2)
                stock_changes[stock] = percent_change
            else:
                stock_changes[stock] = np.nan  # If no data is available, set to NaN

        except Exception as e:
            print(f"Error fetching data for {stock}: {e}")
            stock_changes[stock] = np.nan

    # Create a DataFrame with stock tickers and their percentage changes
    df = pd.DataFrame(list(stock_changes.items()), columns=['Symbol', 'Percent_Change'])

    # Drop any stocks with missing data (NaN values)
    df = df.dropna()

    # Calculate the percentile rank based on percentage change
    df['RSP'] = round(df['Percent_Change'].rank(pct=True) * 100, 2)
    cols = ['Symbol', 'RSP']
    df = df[cols]
    # Sort by percentile rank (optional)
    df = df.sort_values(by='RSP', ascending=False).reset_index(drop=True)

    return df

In [6]:
# function to get stock technicals
def stock_prec_dev(stock_symbol):
    #stock_symbol = 'ULTRACEMCO.NS'
    short_window = 20
    mid_window = 50
    long_window = 200
    moving_avg = 'SMA'

    start = datetime.datetime(*map(int, start_date.split('-')))
    end = datetime.datetime(*map(int, end_date.split('-')))

    stock_df = yfin.Ticker(stock_symbol + '.NS').history(period='max', interval='1d')[map(str.title, ['open', 'close', 'low', 'high', 'volume'])]

    stock_df['Max'] = round(max(stock_df['Close']),2)
    stock_df = stock_df[(stock_df.index <= end_date) & (stock_df.index >= start_date)]
    stock_df['200_SMA'] = round(stock_df['Close'].rolling(window = 200, min_periods = 1).mean(),0)
    stock_df['Dev%_200'] = round((stock_df['Close'] - stock_df['200_SMA'])*100/stock_df['200_SMA'],2)
    stock_df.dropna(axis = 0, inplace = True) # remove any null rows

    stock_df['20_SMA'] = stock_df['Close'].rolling(window=20).mean()
    stock_df['50_SMA'] = stock_df['Close'].rolling(window=50).mean()
    stock_df['Symbol'] = stock_symbol

    stock_df['Close'] = round(stock_df['Close'],2)
    stock_df['Min'] = round(min(stock_df['Close']),2)
    stock_df['RSI_14'] = ta.momentum.RSIIndicator(close=stock_df['Close'], window=14).rsi()
    stock_df['RSI_14'] = round(stock_df['RSI_14'],0)
    stock_df['Prev_Close'] = stock_df['Close'].shift(1)
    stock_df.drop(['Open', 'Low', 'High', 'Volume'], axis=1, inplace=True)
    stock_df = stock_df.tail(1)

    max_SMA = max(stock_df['20_SMA'].item(), stock_df['50_SMA'].item(), stock_df['200_SMA'].item())
    min_SMA = min(stock_df['20_SMA'].item(), stock_df['50_SMA'].item(), stock_df['200_SMA'].item())
    ABS_Spread = max_SMA - min_SMA
    stock_df['Spread%'] = round((ABS_Spread / stock_df['200_SMA'].item()) * 100,2)

    return stock_df

# function to compute stock attributes
def get_common_features(stock_ids, df_mypf):

  df_prec_dev = pd.DataFrame()
  df_tmp = get_screener_features()
  df_rs = get_relative_strength(stock_ids)

  for stock_id in stock_ids:
      tmp = stock_prec_dev(stock_id)
      tmp = tmp.reset_index()
      df_prec_dev = pd.concat([df_prec_dev, tmp], ignore_index = True)
  df_prec_dev = pd.merge(df_prec_dev, df_mypf, on= 'Symbol')
  df_prec_dev = pd.merge(df_prec_dev, df_tmp, on= 'Symbol', how='left')
  df_prec_dev = pd.merge(df_prec_dev, df_rs, on= 'Symbol', how='left')
  #print(df_prec_dev.columns)
  df_prec_dev['Curr_PE'] = round(df_prec_dev['Close']/df_prec_dev['EPS'],1)
  df_prec_dev['Dev%_PE'] = round((df_prec_dev['Curr_PE'] - df_prec_dev['MedPE'])*100/df_prec_dev['MedPE'],2)
  df_prec_dev['Conviction'] = df_prec_dev['Conviction'] + '-' + df_prec_dev['CapType']
  return df_prec_dev

# function to arrange stock features
def arrange_features(df_stocks, common_cols, diff_cols):
  df_stocks_common = df_stocks[common_cols].drop_duplicates()
  df_stocks_diff = df_stocks[diff_cols]
  df_stocks_diff['Investment'] = df_stocks_diff['AvgCost'] * df_stocks_diff['Shares']
  df_stocks_diff = df_stocks_diff.groupby(['Symbol'])[['Shares', 'Investment']].aggregate(['sum']).reset_index()
  df_stocks_diff.columns = ['Symbol', 'Shares', 'Investment']
  df_stocks_diff['AvgCost'] = round(df_stocks_diff['Investment']/df_stocks_diff['Shares'],2)
  df_stocks = pd.merge(df_stocks_diff, df_stocks_common, on='Symbol')
  return df_stocks

# plot fact distribution across dimension
def plot_pie_chart(df, dimension, fact):
  # grouping the data by category and calculating the sum of fact for each type
  grouped_data = df.groupby(dimension)[fact].sum()

  # sorting the grouped data in descending order
  grouped_data = grouped_data.sort_values(ascending=False)

  # creating a pie chart
  grouped_data.plot.pie(autopct='%1.1f%%', startangle=90, figsize=(6, 6))

  # adding a title and displaying the plot
  plt.title(f'{dimension} {fact} Distribution')
  plt.ylabel('')  # To hide the y-label
  plt.show()

In [7]:
# function to get portfolio features

def get_portfolio_features(df_common_features):

  print_date_time()
  print('-------------------')

  #df_common_features["Target"] = df_common_features["Target"].fillna(df_common_features["Max"])
  df_common_features['NTT'] = np.where(df_common_features['Strategy']== 'NTT', df_common_features["Target"], df_common_features['Max'])
  df_common_features['LTT'] = np.where(df_common_features['Strategy']== 'BTT', df_common_features["Target"], df_common_features['Max'])
  df_common_features['BOL'] = df_common_features['Min']

  tmp_df = df_common_features[df_common_features['Symbol'].isin(mypf_df[mypf_df['InPortfolio'] != 'NA'].Symbol.values)]
  print('qualified stocks: '+str(len(tmp_df['Symbol'].unique())))
  tmp_df1 = tmp_df[tmp_df['LatestQtr'] == 1]
  print('with latest results: '+str(len(tmp_df1['Symbol'].unique())))
  tmp_df1 = tmp_df1[tmp_df1['StarStock'] == 1]
  print('still star stocks: '+str(len(tmp_df1['Symbol'].unique())))
  tmp_df['Investment'] = tmp_df['AvgCost'] * tmp_df['Shares']
  tmp_df['Current'] = round(tmp_df['Close'] * tmp_df['Shares'],0)
  tmp_df['Previous'] = tmp_df['Prev_Close'] * tmp_df['Shares']
  tmp_df['EstimatedST'] = tmp_df['NTT'] * tmp_df['Shares']
  tmp_df['EstimatedLT'] = tmp_df['LTT'] * tmp_df['Shares']
  tmp_df['Current P/L'] = round((tmp_df['Current'] - tmp_df['Investment']),0)
  tmp_df['Today P/L%'] = round((tmp_df['Current'] - tmp_df['Previous'])*100/tmp_df['Previous'],2)
  tmp_df['Current P/L%'] = round((tmp_df['Current'] - tmp_df['Investment'])*100/tmp_df['Investment'],2)
  tmp_df['EstimatedST P/L%'] = round((tmp_df['EstimatedST'] - tmp_df['Investment'])*100/tmp_df['Investment'],2)
  tmp_df['EstimatedLT P/L%'] = round((tmp_df['EstimatedLT'] - tmp_df['Investment'])*100/tmp_df['Investment'],2)
  tmp_df['NTT%'] = round((tmp_df['NTT'] - tmp_df['Close'])*100/tmp_df['Close'],2)
  tmp_df['LTT%'] = round((tmp_df['LTT'] - tmp_df['Close'])*100/tmp_df['Close'],2)
  tmp_df['Gained%'] = round((tmp_df['Close'] - tmp_df['BOL'])*100/tmp_df['BOL'],2)
  investment = round(sum(tmp_df['AvgCost']*tmp_df['Shares']),0)
  current = round(sum(tmp_df['Close']*tmp_df['Shares']),0)
  tmp_df['InitAlloc%'] = round(tmp_df['Investment']*100/investment,2)
  tmp_df['CurrAlloc%'] = round(tmp_df['Current']*100/current,2)
  tmp_df['FTT'] = tmp_df['LTT']
  tmp_df.loc[tmp_df['Strategy'] == 'NTT', 'FTT'] = tmp_df['NTT']
  tmp_df['FTT%'] = tmp_df['LTT%']
  tmp_df.loc[tmp_df['Strategy'] == 'NTT', 'FTT%'] = tmp_df['NTT%']
  tmp_df['FTT Amt'] = round(tmp_df['FTT%'] * tmp_df['Current']/100,0)
  tmp_df['OTT%'] = round((tmp_df['FTT'] - tmp_df['AvgCost'])*100/tmp_df['AvgCost'],2)
  tmp_df['RRR Ind'] = round(tmp_df['Current P/L']/tmp_df['FTT Amt'],2)
  tmp_df['Risk Ind'] = round(tmp_df['Current P/L%']*tmp_df['CurrAlloc%'],0)

  return tmp_df

# function to print portfolio features
def print_portfolio_stats(df_portfolio_features, myinvmt_df):
  from pyxirr import xirr

  total_booked_amt, reserve_amt, cy_booked_amt, py_booked_amt = get_amt()

  dates = myinvmt_df['Date'].values
  dates = np.append(dates, datetime.date.today().strftime('%d-%b-%y'))
  investment = myinvmt_df['Investment'].values
  dates= pd.to_datetime(dates)

  current = round(sum(df_portfolio_features['Close']*df_portfolio_features['Shares']),0) + reserve_amt
  investment_xirr = np.append(investment, current)
  cagr = round(xirr(pd.DataFrame({"dates": dates, "amounts": investment_xirr}))*100,2)

  investment = -sum(investment)
  invested = round(sum(df_portfolio_features['AvgCost']*df_portfolio_features['Shares']),0) + reserve_amt
  previous = round(sum(df_portfolio_features['Prev_Close']*df_portfolio_features['Shares']),0) + reserve_amt
  cy_invested = investment + py_booked_amt

  today_pnl_amount = current-previous
  today_pnl_percentage = round((current-previous)*100/previous,2)

  curr_pnl_amount = current-invested
  curr_pnl_percentage = round((curr_pnl_amount)*100/(cy_invested),2)

  cy_pnl_amount = cy_booked_amt + curr_pnl_amount
  cy_pnl_percentage = round((cy_pnl_amount)*100/cy_invested,2)

  overall_pnl_amount = total_booked_amt + curr_pnl_amount
  overall_pnl_percentage = round((overall_pnl_amount)*100/investment,2)

  estimate_st = round(sum(df_portfolio_features['FTT']*df_portfolio_features['Shares']),0)  + reserve_amt
  est_st_pnl_amount = estimate_st-current
  est_st_pnl_percentage = round((est_st_pnl_amount)*100/current,2)

  estimate_lt = round(sum(df_portfolio_features['LTT']*df_portfolio_features['Shares']),0)  + reserve_amt
  est_lt_pnl_amount = estimate_lt-current
  est_lt_pnl_percentage = round((est_lt_pnl_amount)*100/current,2)

  total_profit = round(sum(df_portfolio_features[df_portfolio_features['Current P/L%'] > 0]['Current']) - sum(df_portfolio_features[df_portfolio_features['Current P/L%'] > 0]['Investment']),0)
  total_loss = round(sum(df_portfolio_features[df_portfolio_features['Current P/L%'] < 0]['Current']) - sum(df_portfolio_features[df_portfolio_features['Current P/L%'] < 0]['Investment']),0)

  cy_booked_percentage = round((cy_booked_amt)*100/current,2)
  py_booked_percentage = round((py_booked_amt)*100/investment,2)
  total_booked_percentage = round((total_booked_amt)*100/investment,2)

  print('-------------------')
  print('Initial Investment: ', format_amt(investment))
  print('CY Investment: ', format_amt(cy_invested))
  print('Reserve: ', format_amt(reserve_amt))
  print('Current: ',  format_amt(current))
  print('-------------------')
  print('Today PnL: '+ '{} ({}%)'.format(format_amt(today_pnl_amount), today_pnl_percentage))
  print('Current PnL: '+ '{} ({}%)'.format(format_amt(curr_pnl_amount), curr_pnl_percentage))
  print('CY Booked + Current PnL: '+ '{} ({}%)'.format(format_amt(cy_pnl_amount), cy_pnl_percentage))
  print('-------------------')
  print('Total profit: ', format_amt(total_profit))
  print('Total loss: ', format_amt(total_loss))
  print('-------------------')
  print('Total Booked + Current PnL: '+ '{} ({}%)'.format(format_amt(overall_pnl_amount), overall_pnl_percentage))
  print('Total Booked PnL: '+ '{} ({}%)'.format(format_amt(total_booked_amt), total_booked_percentage))
  print('Curr Year Booked PnL: '+ '{} ({}%)'.format(format_amt(cy_booked_amt), cy_booked_percentage))
  print('Prev Year Booked PnL: '+ '{} ({}%)'.format(format_amt(py_booked_amt), py_booked_percentage))
  print('===================')
  print('Est FTT: ',  format_amt(estimate_st))
  print('Est FTT PnL: '+ '{} ({}%)'.format(format_amt(est_st_pnl_amount), est_st_pnl_percentage))

  print('===================')
  print('Deployed: ', format_amt(investment))

  print('Current: ', format_amt(current))

  print('CAGR/XIRR %: '+'{}%'.format(cagr))

In [8]:
# get start and end date
start_date, end_date = get_start_end_date()

# get portfolio and prospects data
mypfs_df = get_mypfs_df()
mypps_df = get_mypps_df()
myinvmt_df = get_myinvmt_df()

# merge above datasets
mypf_df = pd.merge(mypfs_df, mypps_df, on="Symbol")

# seggregate dm and sv portfolio
dm_pf = mypf_df[mypf_df['InPortfolio'] == 'DM']
sv_pf = mypf_df[mypf_df['InPortfolio'] == 'SV']

# build portfolio stock dataframe
dm_stocks = get_stock_ids(dm_pf)
sv_stocks = get_stock_ids(sv_pf)
df_stocks = pd.concat([dm_pf,sv_pf], ignore_index = True)

# arrange common and diff stock features
common_cols = ['Symbol', 'Target', 'Criteria', 'Strategy', 'CumlRnk', 'LatestQtr', 'StarStock', 'Conviction', 'Category', 'InFolio', 'XIRR', 'MBQ']
diff_cols = ['Symbol', 'AvgCost', 'Shares']
df_stocks = arrange_features(df_stocks, common_cols, diff_cols)

# get common features
stock_ids = df_stocks['Symbol'].values
df_common_features = get_common_features(stock_ids, df_stocks)

df_common_features.reset_index(drop=True, inplace=True)
df_common_features.drop(['Date'], axis=1, inplace=True)
# get and print portfolio features
df_portfolio_features = get_portfolio_features(df_common_features)

print_portfolio_stats(df_portfolio_features, myinvmt_df)

df = df_portfolio_features
#plot_pie_chart(df, 'CapType', 'Current')
list_ox40n = list(df[df['MBQ'].str.contains('OX40N', na=False)]['Symbol'].values)

Run date time (IST): 2026-07-10 15:23:12
-------------------
qualified stocks: 92
with latest results: 31
still star stocks: 20
-------------------
Initial Investment:  1.40 C
CY Investment:  1.82 C
Reserve:  1.49 K
Current:  1.53 C
-------------------
Today PnL: 1.38 L (0.91%)
Current PnL: -30.46 L (-16.7%)
CY Booked + Current PnL: -28.38 L (-15.56%)
-------------------
Total profit:  4.39 L
Total loss:  -34.85 L
-------------------
Total Booked + Current PnL: 14.49 L (10.39%)
Total Booked PnL: 44.95 L (32.22%)
Curr Year Booked PnL: 2.08 L (1.36%)
Prev Year Booked PnL: 42.87 L (30.73%)
===================
Est FTT:  2.55 C
Est FTT PnL: 1.02 C (66.95%)
===================
Deployed:  1.40 C
Current:  1.53 C
CAGR/XIRR %: 4.13%

In [9]:
# top 5 near their targets
cols = ['Symbol', 'Today P/L%', 'Current P/L%', 'FTT%', 'OTT%', 'FTT Amt', 'Current P/L', 'Current', 'FTT', 'Dev%_PE', 'RSI_14','Conviction', 'Spread%',  'CumlRnk', 'RRR Ind', 'CurrAlloc%', 'Gained%', 'Criteria', 'Strategy', 'Category']
df_tmp = df_portfolio_features[~df_portfolio_features['Symbol'].isin(['ENRIN','BLUSPRING','DIGITIDE'])]
df_tmp = df_tmp.sort_values(by = 'FTT Amt', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
59,PIDILITIND,0.25,12.99,4.76,18.37,7589.0,18330.0,159440.0,1670.26,-20.82,59.0,X-LC,8.49,5.0,2.42,1.04,25.19,X40,ATH,CHEMICALS
49,JSWINFRA,1.81,12.26,3.71,16.43,9236.0,27187.0,248961.0,342.00,-3.70,63.0,X-MC,14.03,61.0,2.94,1.63,41.15,X40N,NTT,REALTY
83,TTKPRESTIG,0.81,-17.87,21.87,0.09,18101.0,-18011.0,82766.0,770.00,92.10,65.0,M-SC,5.90,250.0,-1.00,0.54,47.38,OX40N,NTT,DURABLES
55,MASFIN,3.06,-1.13,22.96,21.57,22241.0,-1110.0,96870.0,397.04,-14.63,58.0,H-SC,0.98,167.0,-0.05,0.63,15.47,XR,ATH,FINANCE
56,MEDANTA,-0.86,14.35,11.17,27.12,22546.0,25325.0,201842.0,1486.00,10.81,62.0,X-SC,9.11,87.0,1.12,1.32,39.08,XY24,NTT,HEALTHCARE

In [10]:
# top 5 today
df_tmp = df_portfolio_features.sort_values(by = 'Today P/L%', ascending=False)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
13,BSOFT,7.13,-47.40,182.47,48.59,135006.0,-66665.0,73988.0,819.60,-32.35,46.0,H-SC,19.62,172.0,-0.49,0.48,8.17,XR,ATH,IT
77,TANLA,5.87,-37.58,248.06,117.25,419231.0,-101757.0,169004.0,1922.32,-37.17,61.0,H-SC,0.52,147.0,-0.24,1.11,47.97,AR,ATH,IT
30,HAPPSTMNDS,5.42,-51.89,284.20,84.85,175249.0,-66501.0,61664.0,1480.71,-42.72,68.0,H-SC,17.38,152.0,-0.38,0.40,14.40,AR,ATH,IT
9,BANDHANBNK,4.95,0.90,90.70,92.42,254926.0,2506.0,281065.0,400.00,141.38,56.0,H-SC,20.76,174.0,0.01,1.84,54.83,XY24,NTT,BANKS
40,ICICIPRULI,3.90,-15.63,54.41,30.28,90435.0,-30794.0,166211.0,787.27,-38.34,58.0,X-MC,15.17,78.0,-0.34,1.09,10.74,X40,ATH,INSURANCE

In [11]:
# bottom 5 today
df_tmp = df_portfolio_features.sort_values(by = 'Today P/L%', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
0,5PAISA,-3.25,-30.35,62.11,12.90,94515.0,-66323.0,152173.0,593.00,124.76,59.0,H-SC,7.77,170.0,-0.70,1.00,46.85,OX40N,NTT,FINANCE
57,PAGEIND,-3.16,2.58,30.22,33.59,83199.0,6931.0,275310.0,51217.29,-26.39,44.0,X-MC,10.44,55.0,0.08,1.80,30.74,X40,ATH,APPARELS
60,QUESS,-2.19,18.16,47.17,73.90,59523.0,19395.0,126188.0,424.00,-36.64,71.0,X-SC,24.95,80.0,0.33,0.83,72.02,XY24,NTT,MISC
56,MEDANTA,-0.86,14.35,11.17,27.12,22546.0,25325.0,201842.0,1486.00,10.81,62.0,X-SC,9.11,87.0,1.12,1.32,39.08,XY24,NTT,HEALTHCARE
91,ZYDUSLIFE,-0.70,21.36,11.75,35.63,29886.0,44775.0,254349.0,1286.17,5.41,66.0,H-MC,15.47,120.0,1.50,1.67,33.73,AR,ATH,PHARMA

In [12]:
# top 5 to exit based on CumlRnk
df_tmp = df_portfolio_features[~df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])]
df_tmp = df_tmp[(df_tmp['Current P/L%'] > -1) & (df_tmp['Current P/L%'] < 1)].sort_values(by = 'CumlRnk', ascending=False)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
9,BANDHANBNK,4.95,0.9,90.70,92.42,254926.0,2506.0,281065.0,400.0,141.38,56.0,H-SC,20.76,174.0,0.01,1.84,54.83,XY24,NTT,BANKS
72,SIS,-0.64,-0.1,21.38,21.26,23716.0,-107.0,110925.0,528.0,2648.70,59.0,H-SC,25.14,168.0,-0.00,0.73,64.93,OX40N,NTT,MISC

In [13]:
# OX40N stocks to exit
df_tmp = df_portfolio_features[(df_portfolio_features['Symbol'].isin(list_ox40n))].sort_values(by = 'Current P/L%', ascending=False)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
25,FINCABLES,0.79,33.61,55.61,107.91,109700.0,49622.0,197266.0,1641.55,20.24,45.0,M-SC,26.84,220.0,0.45,1.29,48.41,OX40N,ATH,CABLES
72,SIS,-0.64,-0.10,21.38,21.26,23716.0,-107.0,110925.0,528.00,2648.70,59.0,H-SC,25.14,168.0,-0.00,0.73,64.93,OX40N,NTT,MISC
16,CERA,0.23,-17.55,50.27,23.89,72905.0,-30877.0,145026.0,9475.00,-20.53,57.0,H-SC,15.85,153.0,-0.42,0.95,40.98,OX40N,NTT,CERAMICS
83,TTKPRESTIG,0.81,-17.87,21.87,0.09,18101.0,-18011.0,82766.0,770.00,92.10,65.0,M-SC,5.90,250.0,-1.00,0.54,47.38,OX40N,NTT,DURABLES
69,SFL,1.55,-24.81,68.42,26.63,134891.0,-65067.0,197151.0,1287.00,49.25,68.0,M-SC,21.77,242.0,-0.48,1.29,64.54,XY24,NTT,MISC

In [14]:
# top 5 to book for rotation
df_tmp = df_portfolio_features[(df_portfolio_features['Current P/L%'] > 20) ].sort_values(by = 'CumlRnk', ascending=False)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
25,FINCABLES,0.79,33.61,55.61,107.91,109700.0,49622.0,197266.0,1641.55,20.24,45.0,M-SC,26.84,220.0,0.45,1.29,48.41,OX40N,ATH,CABLES
68,SATIN,0.64,42.28,6.71,51.83,26377.0,116816.0,393100.0,274.00,27.46,61.0,H-SC,42.26,159.0,4.43,2.57,91.50,XY24,NTT,FINANCE
91,ZYDUSLIFE,-0.70,21.36,11.75,35.63,29886.0,44775.0,254349.0,1286.17,5.41,66.0,H-MC,15.47,120.0,1.50,1.67,33.73,AR,ATH,PHARMA

In [15]:
# top 5 to monitor for exit
df_tmp = df_portfolio_features[~df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])]
df_tmp = df_tmp[(df_tmp['Current P/L%'] > 0) ].sort_values(by = 'Dev%_PE', ascending=False)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
9,BANDHANBNK,4.95,0.90,90.70,92.42,254926.0,2506.0,281065.0,400.00,141.38,56.0,H-SC,20.76,174.0,0.01,1.84,54.83,XY24,NTT,BANKS
75,SURYODAY,3.78,4.70,17.51,23.03,32831.0,8425.0,187496.0,216.00,103.95,64.0,H-SC,20.46,166.0,0.26,1.23,57.87,XR,NTT,BANKS
74,STARHEALTH,0.02,16.75,26.13,47.26,85764.0,47099.0,328222.0,761.00,84.28,73.0,H-SC,17.74,173.0,0.55,2.15,42.91,XY24,NTT,INSURANCE
68,SATIN,0.64,42.28,6.71,51.83,26377.0,116816.0,393100.0,274.00,27.46,61.0,H-SC,42.26,159.0,4.43,2.57,91.50,XY24,NTT,FINANCE
25,FINCABLES,0.79,33.61,55.61,107.91,109700.0,49622.0,197266.0,1641.55,20.24,45.0,M-SC,26.84,220.0,0.45,1.29,48.41,OX40N,ATH,CABLES

In [16]:
# top 5 to book for rotation from weak conviction
df_tmp = df_portfolio_features[~df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])]
df_tmp = df_tmp[~df_tmp['Criteria'].isin(['XY25','XY24','X40', 'X40N'])].sort_values(by = 'RRR Ind', ascending=False)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
91,ZYDUSLIFE,-0.70,21.36,11.75,35.63,29886.0,44775.0,254349.0,1286.17,5.41,66.0,H-MC,15.47,120.0,1.50,1.67,33.73,AR,ATH,PHARMA
73,SONACOMS,-0.29,15.70,19.87,38.69,23256.0,15881.0,117040.0,801.69,-8.32,72.0,M-MC,20.88,193.0,0.68,0.77,66.05,AR,ATH,AUTO
25,FINCABLES,0.79,33.61,55.61,107.91,109700.0,49622.0,197266.0,1641.55,20.24,45.0,M-SC,26.84,220.0,0.45,1.29,48.41,OX40N,ATH,CABLES
75,SURYODAY,3.78,4.70,17.51,23.03,32831.0,8425.0,187496.0,216.00,103.95,64.0,H-SC,20.46,166.0,0.26,1.23,57.87,XR,NTT,BANKS
72,SIS,-0.64,-0.10,21.38,21.26,23716.0,-107.0,110925.0,528.00,2648.70,59.0,H-SC,25.14,168.0,-0.00,0.73,64.93,OX40N,NTT,MISC

In [17]:
# top 5 to accumulate based on lowest RSI_14
df_tmp = df_portfolio_features[df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])].sort_values(by = 'RSI_14', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
87,VBL,-0.53,-3.27,39.95,35.37,122050.0,-10336.0,305506.0,670.16,-14.65,35.0,X-LC,8.90,13.0,-0.08,2.00,25.56,X40N,ATH,FMCG
47,ITC,-0.11,-25.79,60.43,19.06,152554.0,-87718.0,252448.0,452.00,-59.16,38.0,X-LC,12.50,1.0,-0.57,1.65,1.71,X40,NTT,FMCG
81,TMPV,1.76,-23.21,77.86,36.58,212756.0,-82587.0,273254.0,600.00,-83.62,38.0,X-LC,7.83,4.0,-0.39,1.79,14.84,XY24,NTT,AUTO
51,KOTAKBANK,0.17,0.95,19.97,21.11,27915.0,1314.0,139786.0,453.24,-13.31,40.0,X-LC,4.38,12.0,0.05,0.92,6.90,X40,ATH,BANKS
71,SIEMENS,0.39,-6.23,33.85,25.51,59068.0,-11595.0,174500.0,4671.50,46.49,41.0,H-LC,10.41,51.0,-0.20,1.14,22.52,AR,ATH,ELECTRICAL

In [18]:
# top 5 to accumulate based on Spread and CumlRnk
df_tmp = df_portfolio_features[df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])]
df_tmp = df_tmp[(df_tmp['CumlRnk'] < 100)].sort_values(by = 'Spread%', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
17,CIPLA,-0.08,16.59,14.45,33.43,25804.0,25411.0,178572.0,1648.14,-9.73,57.0,X-LC,2.24,18.0,0.98,1.17,21.91,X40N,ATH,PHARMA
19,COLPAL,-0.48,-22.04,79.41,39.86,163037.0,-58055.0,205310.0,3683.41,-5.63,52.0,X-MC,2.88,62.0,-0.36,1.34,16.13,XY25,ATH,FMCG
11,BERGEPAINT,-0.02,-8.43,36.85,25.32,86976.0,-21721.0,236028.0,680.00,-13.36,42.0,X-MC,3.25,68.0,-0.25,1.55,22.84,XY24,NTT,PAINTS
23,DMART,0.27,-1.67,31.80,29.60,78047.0,-4170.0,245430.0,5391.45,-17.11,43.0,X-LC,3.31,14.0,-0.05,1.61,12.18,X40N,ATH,FMCG
84,UNITDSPR,0.11,1.57,18.90,20.77,44949.0,3680.0,237824.0,1644.00,-9.86,59.0,X-MC,3.75,64.0,0.08,1.56,14.32,X40N,NTT,BREWERIES

In [19]:
# top 5 to accumulate based on lowest Gained%
df_tmp = df_portfolio_features[df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])].sort_values(by = 'Gained%', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
58,PGHH,0.55,-33.00,97.03,32.01,138807.0,-70464.0,143056.0,17616.87,-54.64,43.0,X-MC,20.57,57.0,-0.51,0.94,1.45,X40,ATH,FMCG
47,ITC,-0.11,-25.79,60.43,19.06,152554.0,-87718.0,252448.0,452.00,-59.16,38.0,X-LC,12.50,1.0,-0.57,1.65,1.71,X40,NTT,FMCG
65,RELIANCE,2.35,-15.92,49.02,25.30,82833.0,-31986.0,168977.0,1952.00,-18.11,50.0,X-LC,7.10,21.0,-0.39,1.11,4.06,XY25,BTT,REFINERIES
79,TCS,0.85,-39.32,105.81,24.88,297430.0,-182175.0,281098.0,4253.91,-48.54,43.0,X-LC,21.70,2.0,-0.61,1.84,4.25,X40,ATH,IT
35,HDFCLIFE,2.76,-7.25,43.08,32.71,59855.0,-10860.0,138940.0,811.41,-27.55,45.0,X-LC,15.08,31.0,-0.18,0.91,4.38,X40,ATH,INSURANCE

In [20]:
# top 5 to accumulate based on lowest CurrAlloc%
df_tmp = df_portfolio_features[df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])].sort_values(by = 'CurrAlloc%', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
10,BATAINDIA,2.63,-55.49,203.79,35.20,116702.0,-71404.0,57266.0,2096.00,-24.91,49.0,X-SC,19.21,91.0,-0.61,0.38,13.57,X40,NTT,FOOTWEAR
64,RELAXO,1.78,-49.00,198.67,52.31,147065.0,-71135.0,74025.0,1176.00,-45.70,60.0,X-SC,11.94,92.0,-0.48,0.48,65.51,X40N,NTT,FOOTWEAR
60,QUESS,-2.19,18.16,47.17,73.90,59523.0,19395.0,126188.0,424.00,-36.64,71.0,X-SC,24.95,80.0,0.33,0.83,72.02,XY24,NTT,MISC
35,HDFCLIFE,2.76,-7.25,43.08,32.71,59855.0,-10860.0,138940.0,811.41,-27.55,45.0,X-LC,15.08,31.0,-0.18,0.91,4.38,X40,ATH,INSURANCE
51,KOTAKBANK,0.17,0.95,19.97,21.11,27915.0,1314.0,139786.0,453.24,-13.31,40.0,X-LC,4.38,12.0,0.05,0.92,6.90,X40,ATH,BANKS

In [21]:
# top 5 to accumulate based on CumlRnk
df_tmp = df_portfolio_features.sort_values(by = 'CumlRnk', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
47,ITC,-0.11,-25.79,60.43,19.06,152554.0,-87718.0,252448.0,452.00,-59.16,38.0,X-LC,12.50,1.0,-0.57,1.65,1.71,X40,NTT,FMCG
79,TCS,0.85,-39.32,105.81,24.88,297430.0,-182175.0,281098.0,4253.91,-48.54,43.0,X-LC,21.70,2.0,-0.61,1.84,4.25,X40,ATH,IT
45,INFY,1.78,-27.19,84.39,34.24,192244.0,-85084.0,227804.0,1972.00,-42.67,48.0,X-LC,21.25,3.0,-0.44,1.49,8.55,X40,NTT,IT
81,TMPV,1.76,-23.21,77.86,36.58,212756.0,-82587.0,273254.0,600.00,-83.62,38.0,X-LC,7.83,4.0,-0.39,1.79,14.84,XY24,NTT,AUTO
59,PIDILITIND,0.25,12.99,4.76,18.37,7589.0,18330.0,159440.0,1670.26,-20.82,59.0,X-LC,8.49,5.0,2.42,1.04,25.19,X40,ATH,CHEMICALS

In [22]:
# top 5 for average up
df_tmp = df_portfolio_features[(df_portfolio_features['Dev%_200'] > 5)].sort_values(by = 'CurrAlloc%', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
44,INDUSINDBK,0.06,-25.01,77.21,32.89,44703.0,-19308.0,57898.0,1800.00,-372.41,67.0,L-MC,9.81,258.0,-0.43,0.38,42.74,XR,NTT,BANKS
64,RELAXO,1.78,-49.00,198.67,52.31,147065.0,-71135.0,74025.0,1176.00,-45.70,60.0,X-SC,11.94,92.0,-0.48,0.48,65.51,X40N,NTT,FOOTWEAR
83,TTKPRESTIG,0.81,-17.87,21.87,0.09,18101.0,-18011.0,82766.0,770.00,92.10,65.0,M-SC,5.90,250.0,-1.00,0.54,47.38,OX40N,NTT,DURABLES
3,ALKYLAMINE,0.16,-16.62,130.91,92.54,110207.0,-16778.0,84185.0,4520.85,-10.74,66.0,H-SC,10.19,142.0,-0.15,0.55,59.86,SR,ATH,CHEMICALS
72,SIS,-0.64,-0.10,21.38,21.26,23716.0,-107.0,110925.0,528.00,2648.70,59.0,H-SC,25.14,168.0,-0.00,0.73,64.93,OX40N,NTT,MISC

In [23]:
# top 5 RSP
df_tmp = df_portfolio_features.sort_values(by = 'RSP', ascending=False)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
60,QUESS,-2.19,18.16,47.17,73.90,59523.0,19395.0,126188.0,424.00,-36.64,71.0,X-SC,24.95,80.0,0.33,0.83,72.02,XY24,NTT,MISC
0,5PAISA,-3.25,-30.35,62.11,12.90,94515.0,-66323.0,152173.0,593.00,124.76,59.0,H-SC,7.77,170.0,-0.70,1.00,46.85,OX40N,NTT,FINANCE
49,JSWINFRA,1.81,12.26,3.71,16.43,9236.0,27187.0,248961.0,342.00,-3.70,63.0,X-MC,14.03,61.0,2.94,1.63,41.15,X40N,NTT,REALTY
85,VAIBHAVGBL,2.20,-19.34,99.30,60.77,146403.0,-35340.0,147435.0,521.00,70.25,72.0,H-SC,5.26,160.0,-0.24,0.97,50.00,XR,NTT,JEWELLERY
22,DIXON,-0.54,-2.35,41.24,37.92,105028.0,-6122.0,254676.0,18931.72,-58.49,67.0,X-MC,6.34,54.0,-0.06,1.67,38.57,X40N,ATH,IT

In [24]:
# Top N allocation
df_tmp = df_portfolio_features.sort_values(by = 'CurrAlloc%', ascending=False)
top_n_values = [10, 25, 50]

sum_df = pd.DataFrame({
    'Top_N': top_n_values,
    'Sum_Alloc%': [df_tmp['CurrAlloc%'].head(n).sum() for n in top_n_values]
})

sum_df

   Top_N  Sum_Alloc%
0     10       19.16
1     25       42.59
2     50       72.65

In [25]:
# market-cap-wise allocation
df_tmp = df_portfolio_features[cols]
df_tmp.groupby(df_tmp['Conviction'].str[-2:])['CurrAlloc%'].sum().sort_values(ascending=False)

Conviction
SC    43.87
LC    30.09
MC    26.07
Name: CurrAlloc%, dtype: float64

In [26]:
# criteria-wise allocation
df_portfolio_features.groupby('Criteria')['CurrAlloc%'].sum().sort_values(ascending=False)

Criteria
XY24     27.91
X40      24.54
X40N     17.43
XR        8.89
OX40N     7.10
AR        6.86
XY25      6.39
SR        0.91
Name: CurrAlloc%, dtype: float64

In [27]:
# conviction-wise allocation
df_portfolio_features.groupby('Conviction')['CurrAlloc%'].sum().sort_values(ascending=False)

Conviction
X-LC    28.15
H-SC    23.11
X-MC    20.90
X-SC    10.13
M-SC    10.07
H-MC     2.75
M-MC     2.04
H-LC     1.14
M-LC     0.80
L-SC     0.56
L-MC     0.38
Name: CurrAlloc%, dtype: float64

In [28]:
# sector-wise stats
df_tmp = df_portfolio_features.groupby('Category')[['CurrAlloc%', 'Current', 'Current P/L', 'FTT Amt']].sum().sort_values(by=['Current', 'Current P/L'], ascending=False)
df_tmp['Current P/L%'] = round(df_tmp['Current P/L'] * 100 / df_tmp['Current'], 2)
df_tmp['FTT%'] = round(df_tmp['FTT Amt'] * 100 / df_tmp['Current'], 2)
cols = ['CurrAlloc%', 'Current P/L%', 'FTT%']
df_tmp[cols].sort_values(by=['CurrAlloc%'], ascending=False)

               CurrAlloc%  Current P/L%    FTT%
Category
FMCG                14.38        -20.56   62.86
FINANCE             11.30         -6.94   53.27
IT                   9.81        -50.34  125.30
MISC                 7.23        -21.51   73.65
AUTO                 6.64         -8.02   48.30
BANKS                5.89         -1.14   47.90
INSURANCE            5.42         -0.13   33.90
PAINTS               5.40        -19.84   40.28
PHARMA               5.18          6.24   22.78
ELECTRICAL           4.02        -14.93   55.49
CHEMICALS            2.21        -20.03   91.24
HEALTHCARE           2.10        -11.49   40.59
APPARELS             1.80          2.52   30.22
AC                   1.75        -18.97   51.22
FOOTWEAR             1.72        -68.22  135.67
DURABLES             1.64        -54.59   92.20
REALTY               1.63         10.92    3.71
BREWERIES            1.56          1.55   18.90
TRAVEL               1.52        -92.95  189.57
CERAMICS             1.41        -42.31   85.55
CABLES               1.29         25.15   55.61
ENGINEERING          1.25        -26.99   85.07
JEWELLERY            1.13        -85.62  150.10
REFINERIES           1.11        -18.93   49.02
CEMENT               1.09        -61.39  182.12
ENTERTAINMENT        0.74        -71.00  172.98
TEXTILES             0.41        -46.47   88.24
HOTELS               0.40        -84.81  150.00

In [29]:
# money to be made criteria-wise
df_portfolio_features.groupby('Criteria')['FTT Amt'].agg(['sum', 'count']).sort_values(by='sum', ascending=False)

                sum  count
Criteria
XY24      3338059.0     21
X40       1929906.0     19
XR        1319783.0     13
AR        1130240.0      9
X40N      1059632.0     13
OX40N      708120.0     10
XY25       460248.0      5
SR         278828.0      2

In [30]:
# money to be made conviction-wise
df_portfolio_features.groupby('Conviction')['FTT Amt'].agg(['sum', 'count']).sort_values(by='sum', ascending=False)

                  sum  count
Conviction
H-SC        3246499.0     24
X-LC        1983080.0     21
X-MC        1526506.0     15
M-SC        1379165.0     14
X-SC        1257141.0      9
H-MC         279185.0      2
L-SC         204492.0      2
M-LC         170030.0      1
M-MC          74947.0      2
H-LC          59068.0      1
L-MC          44703.0      1

In [31]:
# money to be made criteria and conviction-wise
df_portfolio_features.groupby(['Conviction', 'Criteria'])['FTT Amt'].agg(['sum', 'count']).sort_values(by='sum', ascending=False)

                           sum  count
Conviction Criteria
X-LC       X40       1056739.0     10
H-SC       AR         944767.0      5
           XY24       943885.0      6
M-SC       XY24       813920.0      6
H-SC       XR         783990.0      7
X-SC       XY24       746601.0      4
X-MC       X40        662612.0      7
           X40N       387098.0      4
X-LC       X40N       372549.0      6
           XY24       355968.0      2
M-SC       OX40N      300759.0      5
X-SC       X40N       299985.0      3
H-SC       OX40N      295029.0      4
           SR         278828.0      2
H-MC       XY24       249299.0      1
X-MC       XY25       248410.0      2
           XY24       228386.0      2
X-SC       X40        210555.0      2
M-SC       XR         191223.0      2
M-LC       XR         170030.0      1
X-LC       XY25       160147.0      2
L-SC       OX40N      112332.0      1
           XR          92160.0      1
M-SC       AR          73263.0      1
H-LC       AR          59068.0      1
M-MC       XY25        51691.0      1
L-MC       XR          44703.0      1
X-LC       XR          37677.0      1
H-MC       AR          29886.0      1
M-MC       AR          23256.0      1

In [32]:
# notebook execution time

end_time = time.time()
execution_time = round(end_time - start_time, 0)
print(f"Notebook execution time: {execution_time} seconds")

Notebook execution time: 37.0 seconds