<a href="https://colab.research.google.com/github/ankit-rathi/Quantvesting_v2/blob/main/myStocks_Portfolio_Analysis.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
'''
!pip install pandas==2.2.2 -qq
!pip install pyxirr -qq
!pip install ta -qq
!pip install yfinance==0.2.59 -qq
'''

'\n!pip install pandas==2.2.2 -qq\n!pip install pyxirr -qq\n!pip install ta -qq\n!pip install yfinance==0.2.59 -qq\n'

In [2]:
# import libraries

import numpy as np
import pandas as pd
import datetime
import warnings
warnings.filterwarnings('ignore')
import yfinance as yfin
import ta
import matplotlib.pyplot as plt
import requests

In [3]:
# notebook start time
import time
import datetime
import pytz

start_time = time.time()

# function to print date timestamp
def print_date_time():
  tz_NY = pytz.timezone('Asia/Kolkata')
  datetime_NY = datetime.datetime.now(tz_NY)
  print("Run date time (IST):", datetime_NY.strftime("%Y-%m-%d %H:%M:%S"))

In [4]:
# function to get booked and reserved amount
def get_amt():
  # fetch the JSON data from the URL
  url = "https://raw.githubusercontent.com/ankit-rathi/Tradevesting_v1/main/data/myPortfolioAmts.json"
  response = requests.get(url)
  pf_amts = response.json()  # parse the JSON data

  # extract values from the JSON
  py_booked_amt_dm = pf_amts["py_booked_amt_dm"]
  py_booked_amt_sv = pf_amts["py_booked_amt_sv"]
  cy_booked_amt_dm = pf_amts["cy_booked_amt_dm"]
  cy_booked_amt_sv = pf_amts["cy_booked_amt_sv"]
  reserve_amt_dm = pf_amts["reserve_amt_dm"]
  reserve_amt_sv = pf_amts["reserve_amt_sv"]

  # perform calculations
  py_booked_amt = py_booked_amt_dm + py_booked_amt_sv
  cy_booked_amt = cy_booked_amt_dm + cy_booked_amt_sv
  reserve_amt = reserve_amt_dm + reserve_amt_sv
  total_booked_amt = py_booked_amt + cy_booked_amt

  return total_booked_amt, reserve_amt, cy_booked_amt, py_booked_amt

gen_output = 0

In [5]:
# function to format the amount
def format_amt(number):
    abs_number = abs(number)

    if abs_number >= 1_00_00_000:  # Crores
        formatted_amt = f"{number / 1_00_00_000:.2f} C"
    elif abs_number >= 1_00_000:  # Lakhs
        formatted_amt = f"{number / 1_00_000:.2f} L"
    elif abs_number >= 1_000:  # Thousands
        formatted_amt = f"{number / 1_000:.2f} K"
    else:
        formatted_amt = f"{number:.2f}"

    return formatted_amt

# function to set start and end date
def get_start_end_date():
  start_date = (datetime.date.today() + datetime.timedelta(days=-365)).strftime('%Y-%m-%d')
  end_date = (datetime.date.today() + datetime.timedelta(days=1)).strftime('%Y-%m-%d')
  return start_date, end_date

# function to fetch my portfolio csv
def get_mypfs_df():
  mypfs_df = pd.read_csv('https://raw.githubusercontent.com/ankit-rathi/Tradevesting_v1/main/data/myPortfolioStocks.csv')
  return mypfs_df

# function to fetch my prospects csv
def get_mypps_df():
  mypps_df = pd.read_csv('https://raw.githubusercontent.com/ankit-rathi/Tradevesting_v1/main/data/myProspectsScrips.csv')
  return mypps_df

# function to fetch screener data
def get_myscreen_df():
  myscreen_df = pd.read_csv('https://raw.githubusercontent.com/ankit-rathi/Tradevesting_v1/main/data/myScreenerDB.csv')
  return myscreen_df

# function to fetch momentum data
def get_myinvmt_df():
  myinvmt_df = pd.read_csv('https://raw.githubusercontent.com/ankit-rathi/Tradevesting_v1/main/data/myInvestments.csv')
  return myinvmt_df

# function to get the stock ids
def get_stock_ids(df_pf):
  stock_n100 = df_pf['Symbol'].unique()

  exclude = ['CADILAHC','MMTC', 'MASFIN']

  stock_ids = df_pf[~df_pf['Symbol'].isin(exclude) ]['Symbol'].unique()

  #mypf = mypf[mypf.Forecast.notnull()]
  #stock_ids = mypf['Symbol'].unique()

  #stock_ids.sort()
  return stock_ids

# get features from screener data
def get_screener_features():
  myscreen_df = get_myscreen_df()
  cols = ['Symbol', 'EPS', 'MedPE', 'ROCE%', 'ROE%', 'CapType']
  return myscreen_df[cols]

# get relative strength
def get_relative_strength(stock_list):

    # Dictionary to store stock tickers and their corresponding percentage price change
    stock_changes = {}

    # Loop through each stock and fetch its price data
    for stock in stock_list:
        try:
            # Download the stock data for the given date range
            stock_data = yfin.Ticker(stock + '.NS').history(period='1mo', interval='1d')[map(str.title, ['open', 'close', 'low', 'high', 'volume'])]

            # Calculate the percentage change for the stock
            if len(stock_data) > 0:
                start_price = stock_data['Close'].iloc[0]
                end_price = stock_data['Close'].iloc[-1]
                percent_change = round(((end_price - start_price) / start_price) * 100, 2)
                stock_changes[stock] = percent_change
            else:
                stock_changes[stock] = np.nan  # If no data is available, set to NaN

        except Exception as e:
            print(f"Error fetching data for {stock}: {e}")
            stock_changes[stock] = np.nan

    # Create a DataFrame with stock tickers and their percentage changes
    df = pd.DataFrame(list(stock_changes.items()), columns=['Symbol', 'Percent_Change'])

    # Drop any stocks with missing data (NaN values)
    df = df.dropna()

    # Calculate the percentile rank based on percentage change
    df['RSP'] = round(df['Percent_Change'].rank(pct=True) * 100, 2)
    cols = ['Symbol', 'RSP']
    df = df[cols]
    # Sort by percentile rank (optional)
    df = df.sort_values(by='RSP', ascending=False).reset_index(drop=True)

    return df

In [6]:
# function to get stock technicals
def stock_prec_dev(stock_symbol):
    #stock_symbol = 'ULTRACEMCO.NS'
    short_window = 20
    mid_window = 50
    long_window = 200
    moving_avg = 'SMA'

    start = datetime.datetime(*map(int, start_date.split('-')))
    end = datetime.datetime(*map(int, end_date.split('-')))

    stock_df = yfin.Ticker(stock_symbol + '.NS').history(period='max', interval='1d')[map(str.title, ['open', 'close', 'low', 'high', 'volume'])]

    stock_df['Max'] = round(max(stock_df['Close']),2)
    stock_df = stock_df[(stock_df.index <= end_date) & (stock_df.index >= start_date)]
    stock_df['200_SMA'] = round(stock_df['Close'].rolling(window = 200, min_periods = 1).mean(),0)
    stock_df['Dev%_200'] = round((stock_df['Close'] - stock_df['200_SMA'])*100/stock_df['200_SMA'],2)
    stock_df.dropna(axis = 0, inplace = True) # remove any null rows

    stock_df['20_SMA'] = stock_df['Close'].rolling(window=20).mean()
    stock_df['50_SMA'] = stock_df['Close'].rolling(window=50).mean()
    stock_df['Symbol'] = stock_symbol

    stock_df['Close'] = round(stock_df['Close'],2)
    stock_df['Min'] = round(min(stock_df['Close']),2)
    stock_df['RSI_14'] = ta.momentum.RSIIndicator(close=stock_df['Close'], window=14).rsi()
    stock_df['RSI_14'] = round(stock_df['RSI_14'],0)
    stock_df['Prev_Close'] = stock_df['Close'].shift(1)
    stock_df.drop(['Open', 'Low', 'High', 'Volume'], axis=1, inplace=True)
    stock_df = stock_df.tail(1)

    max_SMA = max(stock_df['20_SMA'].item(), stock_df['50_SMA'].item(), stock_df['200_SMA'].item())
    min_SMA = min(stock_df['20_SMA'].item(), stock_df['50_SMA'].item(), stock_df['200_SMA'].item())
    ABS_Spread = max_SMA - min_SMA
    stock_df['Spread%'] = round((ABS_Spread / stock_df['200_SMA'].item()) * 100,2)

    return stock_df

# function to compute stock attributes
def get_common_features(stock_ids, df_mypf):

  df_prec_dev = pd.DataFrame()
  df_tmp = get_screener_features()
  df_rs = get_relative_strength(stock_ids)

  for stock_id in stock_ids:
      tmp = stock_prec_dev(stock_id)
      tmp = tmp.reset_index()
      df_prec_dev = pd.concat([df_prec_dev, tmp], ignore_index = True)
  df_prec_dev = pd.merge(df_prec_dev, df_mypf, on= 'Symbol')
  df_prec_dev = pd.merge(df_prec_dev, df_tmp, on= 'Symbol', how='left')
  df_prec_dev = pd.merge(df_prec_dev, df_rs, on= 'Symbol', how='left')
  #print(df_prec_dev.columns)
  df_prec_dev['Curr_PE'] = round(df_prec_dev['Close']/df_prec_dev['EPS'],1)
  df_prec_dev['Dev%_PE'] = round((df_prec_dev['Curr_PE'] - df_prec_dev['MedPE'])*100/df_prec_dev['MedPE'],2)
  df_prec_dev['Conviction'] = df_prec_dev['Conviction'] + '-' + df_prec_dev['CapType']
  return df_prec_dev

# function to arrange stock features
def arrange_features(df_stocks, common_cols, diff_cols):
  df_stocks_common = df_stocks[common_cols].drop_duplicates()
  df_stocks_diff = df_stocks[diff_cols]
  df_stocks_diff['Investment'] = df_stocks_diff['AvgCost'] * df_stocks_diff['Shares']
  df_stocks_diff = df_stocks_diff.groupby(['Symbol'])[['Shares', 'Investment']].aggregate(['sum']).reset_index()
  df_stocks_diff.columns = ['Symbol', 'Shares', 'Investment']
  df_stocks_diff['AvgCost'] = round(df_stocks_diff['Investment']/df_stocks_diff['Shares'],2)
  df_stocks = pd.merge(df_stocks_diff, df_stocks_common, on='Symbol')
  return df_stocks

# plot fact distribution across dimension
def plot_pie_chart(df, dimension, fact):
  # grouping the data by category and calculating the sum of fact for each type
  grouped_data = df.groupby(dimension)[fact].sum()

  # sorting the grouped data in descending order
  grouped_data = grouped_data.sort_values(ascending=False)

  # creating a pie chart
  grouped_data.plot.pie(autopct='%1.1f%%', startangle=90, figsize=(6, 6))

  # adding a title and displaying the plot
  plt.title(f'{dimension} {fact} Distribution')
  plt.ylabel('')  # To hide the y-label
  plt.show()

In [7]:
# function to get portfolio features

def get_portfolio_features(df_common_features):

  print_date_time()
  print('-------------------')

  #df_common_features["Target"] = df_common_features["Target"].fillna(df_common_features["Max"])
  df_common_features['NTT'] = np.where(df_common_features['Strategy']== 'NTT', df_common_features["Target"], df_common_features['Max'])
  df_common_features['LTT'] = np.where(df_common_features['Strategy']== 'BTT', df_common_features["Target"], df_common_features['Max'])
  df_common_features['BOL'] = df_common_features['Min']

  tmp_df = df_common_features[df_common_features['Symbol'].isin(mypf_df[mypf_df['InPortfolio'] != 'NA'].Symbol.values)]
  print('qualified stocks: '+str(len(tmp_df['Symbol'].unique())))
  tmp_df1 = tmp_df[tmp_df['LatestQtr'] == 1]
  print('with latest results: '+str(len(tmp_df1['Symbol'].unique())))
  tmp_df1 = tmp_df1[tmp_df1['StarStock'] == 1]
  print('still star stocks: '+str(len(tmp_df1['Symbol'].unique())))
  tmp_df['Investment'] = tmp_df['AvgCost'] * tmp_df['Shares']
  tmp_df['Current'] = round(tmp_df['Close'] * tmp_df['Shares'],0)
  tmp_df['Previous'] = tmp_df['Prev_Close'] * tmp_df['Shares']
  tmp_df['EstimatedST'] = tmp_df['NTT'] * tmp_df['Shares']
  tmp_df['EstimatedLT'] = tmp_df['LTT'] * tmp_df['Shares']
  tmp_df['Current P/L'] = round((tmp_df['Current'] - tmp_df['Investment']),0)
  tmp_df['Today P/L%'] = round((tmp_df['Current'] - tmp_df['Previous'])*100/tmp_df['Previous'],2)
  tmp_df['Current P/L%'] = round((tmp_df['Current'] - tmp_df['Investment'])*100/tmp_df['Investment'],2)
  tmp_df['EstimatedST P/L%'] = round((tmp_df['EstimatedST'] - tmp_df['Investment'])*100/tmp_df['Investment'],2)
  tmp_df['EstimatedLT P/L%'] = round((tmp_df['EstimatedLT'] - tmp_df['Investment'])*100/tmp_df['Investment'],2)
  tmp_df['NTT%'] = round((tmp_df['NTT'] - tmp_df['Close'])*100/tmp_df['Close'],2)
  tmp_df['LTT%'] = round((tmp_df['LTT'] - tmp_df['Close'])*100/tmp_df['Close'],2)
  tmp_df['Gained%'] = round((tmp_df['Close'] - tmp_df['BOL'])*100/tmp_df['BOL'],2)
  investment = round(sum(tmp_df['AvgCost']*tmp_df['Shares']),0)
  current = round(sum(tmp_df['Close']*tmp_df['Shares']),0)
  tmp_df['InitAlloc%'] = round(tmp_df['Investment']*100/investment,2)
  tmp_df['CurrAlloc%'] = round(tmp_df['Current']*100/current,2)
  tmp_df['FTT'] = tmp_df['LTT']
  tmp_df.loc[tmp_df['Strategy'] == 'NTT', 'FTT'] = tmp_df['NTT']
  tmp_df['FTT%'] = tmp_df['LTT%']
  tmp_df.loc[tmp_df['Strategy'] == 'NTT', 'FTT%'] = tmp_df['NTT%']
  tmp_df['FTT Amt'] = round(tmp_df['FTT%'] * tmp_df['Current']/100,0)
  tmp_df['OTT%'] = round((tmp_df['FTT'] - tmp_df['AvgCost'])*100/tmp_df['AvgCost'],2)
  tmp_df['RRR Ind'] = round(tmp_df['Current P/L']/tmp_df['FTT Amt'],2)
  tmp_df['Risk Ind'] = round(tmp_df['Current P/L%']*tmp_df['CurrAlloc%'],0)

  return tmp_df

# function to print portfolio features
def print_portfolio_stats(df_portfolio_features, myinvmt_df):
  from pyxirr import xirr

  total_booked_amt, reserve_amt, cy_booked_amt, py_booked_amt = get_amt()

  dates = myinvmt_df['Date'].values
  dates = np.append(dates, datetime.date.today().strftime('%d-%b-%y'))
  investment = myinvmt_df['Investment'].values
  dates= pd.to_datetime(dates)

  current = round(sum(df_portfolio_features['Close']*df_portfolio_features['Shares']),0) + reserve_amt
  investment_xirr = np.append(investment, current)
  cagr = round(xirr(pd.DataFrame({"dates": dates, "amounts": investment_xirr}))*100,2)

  investment = -sum(investment)
  invested = round(sum(df_portfolio_features['AvgCost']*df_portfolio_features['Shares']),0) + reserve_amt
  previous = round(sum(df_portfolio_features['Prev_Close']*df_portfolio_features['Shares']),0) + reserve_amt
  cy_invested = investment + py_booked_amt

  today_pnl_amount = current-previous
  today_pnl_percentage = round((current-previous)*100/previous,2)

  curr_pnl_amount = current-invested
  curr_pnl_percentage = round((curr_pnl_amount)*100/(cy_invested),2)

  cy_pnl_amount = cy_booked_amt + curr_pnl_amount
  cy_pnl_percentage = round((cy_pnl_amount)*100/cy_invested,2)

  overall_pnl_amount = total_booked_amt + curr_pnl_amount
  overall_pnl_percentage = round((overall_pnl_amount)*100/investment,2)

  estimate_st = round(sum(df_portfolio_features['FTT']*df_portfolio_features['Shares']),0)  + reserve_amt
  est_st_pnl_amount = estimate_st-current
  est_st_pnl_percentage = round((est_st_pnl_amount)*100/current,2)

  estimate_lt = round(sum(df_portfolio_features['LTT']*df_portfolio_features['Shares']),0)  + reserve_amt
  est_lt_pnl_amount = estimate_lt-current
  est_lt_pnl_percentage = round((est_lt_pnl_amount)*100/current,2)

  total_profit = round(sum(df_portfolio_features[df_portfolio_features['Current P/L%'] > 0]['Current']) - sum(df_portfolio_features[df_portfolio_features['Current P/L%'] > 0]['Investment']),0)
  total_loss = round(sum(df_portfolio_features[df_portfolio_features['Current P/L%'] < 0]['Current']) - sum(df_portfolio_features[df_portfolio_features['Current P/L%'] < 0]['Investment']),0)

  cy_booked_percentage = round((cy_booked_amt)*100/current,2)
  py_booked_percentage = round((py_booked_amt)*100/investment,2)
  total_booked_percentage = round((total_booked_amt)*100/investment,2)

  print('-------------------')
  print('Initial Investment: ', format_amt(investment))
  print('CY Investment: ', format_amt(cy_invested))
  print('Reserve: ', format_amt(reserve_amt))
  print('Current: ',  format_amt(current))
  print('-------------------')
  print('Today PnL: '+ '{} ({}%)'.format(format_amt(today_pnl_amount), today_pnl_percentage))
  print('Current PnL: '+ '{} ({}%)'.format(format_amt(curr_pnl_amount), curr_pnl_percentage))
  print('CY Booked + Current PnL: '+ '{} ({}%)'.format(format_amt(cy_pnl_amount), cy_pnl_percentage))
  print('-------------------')
  print('Total profit: ', format_amt(total_profit))
  print('Total loss: ', format_amt(total_loss))
  print('-------------------')
  print('Total Booked + Current PnL: '+ '{} ({}%)'.format(format_amt(overall_pnl_amount), overall_pnl_percentage))
  print('Total Booked PnL: '+ '{} ({}%)'.format(format_amt(total_booked_amt), total_booked_percentage))
  print('Curr Year Booked PnL: '+ '{} ({}%)'.format(format_amt(cy_booked_amt), cy_booked_percentage))
  print('Prev Year Booked PnL: '+ '{} ({}%)'.format(format_amt(py_booked_amt), py_booked_percentage))
  print('===================')
  print('Est FTT: ',  format_amt(estimate_st))
  print('Est FTT PnL: '+ '{} ({}%)'.format(format_amt(est_st_pnl_amount), est_st_pnl_percentage))

  print('===================')
  print('Deployed: ', format_amt(investment))

  print('Current: ', format_amt(current))

  print('CAGR/XIRR %: '+'{}%'.format(cagr))

In [8]:
# get start and end date
start_date, end_date = get_start_end_date()

# get portfolio and prospects data
mypfs_df = get_mypfs_df()
mypps_df = get_mypps_df()
myinvmt_df = get_myinvmt_df()

# merge above datasets
mypf_df = pd.merge(mypfs_df, mypps_df, on="Symbol")

# seggregate dm and sv portfolio
dm_pf = mypf_df[mypf_df['InPortfolio'] == 'DM']
sv_pf = mypf_df[mypf_df['InPortfolio'] == 'SV']

# build portfolio stock dataframe
dm_stocks = get_stock_ids(dm_pf)
sv_stocks = get_stock_ids(sv_pf)
df_stocks = pd.concat([dm_pf,sv_pf], ignore_index = True)

# arrange common and diff stock features
common_cols = ['Symbol', 'Target', 'Criteria', 'Strategy', 'CumlRnk', 'LatestQtr', 'StarStock', 'Conviction', 'Category', 'InFolio', 'XIRR', 'MBQ']
diff_cols = ['Symbol', 'AvgCost', 'Shares']
df_stocks = arrange_features(df_stocks, common_cols, diff_cols)

# get common features
stock_ids = df_stocks['Symbol'].values
df_common_features = get_common_features(stock_ids, df_stocks)

df_common_features.reset_index(drop=True, inplace=True)
df_common_features.drop(['Date'], axis=1, inplace=True)
# get and print portfolio features
df_portfolio_features = get_portfolio_features(df_common_features)

print_portfolio_stats(df_portfolio_features, myinvmt_df)

df = df_portfolio_features
#plot_pie_chart(df, 'CapType', 'Current')
list_ox40n = list(df[df['MBQ'].str.contains('OX40N', na=False)]['Symbol'].values)

Run date time (IST): 2026-08-07 12:43:51
-------------------
qualified stocks: 88
with latest results: 30
still star stocks: 19
-------------------
Initial Investment:  1.46 C
CY Investment:  1.89 C
Reserve:  2.24 L
Current:  1.62 C
-------------------
Today PnL: -35.82 K (-0.22%)
Current PnL: -30.49 L (-16.14%)
CY Booked + Current PnL: -26.27 L (-13.9%)
-------------------
Total profit:  3.63 L
Total loss:  -34.12 L
-------------------
Total Booked + Current PnL: 16.60 L (11.37%)
Total Booked PnL: 47.09 L (32.24%)
Curr Year Booked PnL: 4.22 L (2.61%)
Prev Year Booked PnL: 42.87 L (29.35%)
===================
Est FTT:  2.67 C
Est FTT PnL: 1.05 C (65.02%)
===================
Deployed:  1.46 C
Current:  1.62 C
CAGR/XIRR %: 4.67%

In [9]:
# top 5 near their targets
cols = ['Symbol', 'Today P/L%', 'Current P/L%', 'FTT%', 'OTT%', 'FTT Amt', 'Current P/L', 'Current', 'FTT', 'Dev%_PE', 'RSI_14','Conviction', 'Spread%',  'CumlRnk', 'RRR Ind', 'CurrAlloc%', 'Gained%', 'Criteria', 'Strategy', 'Category']
df_tmp = df_portfolio_features[~df_portfolio_features['Symbol'].isin(['ENRIN','BLUSPRING','DIGITIDE'])]
df_tmp = df_tmp.sort_values(by = 'FTT Amt', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
55,MEDANTA,1.45,25.35,1.41,27.12,3120.0,44743.0,221260.0,1486.00,21.43,68.0,X-SC,15.41,87.0,14.34,1.39,52.46,XY24,NTT,HEALTHCARE
79,TTKPRESTIG,0.05,-18.29,22.50,0.09,18526.0,-18437.0,82340.0,770.00,91.04,49.0,M-SC,13.83,250.0,-1.00,0.52,48.20,OX40N,NTT,DURABLES
52,M&M,2.26,9.98,8.04,18.82,21282.0,24019.0,264700.0,3762.88,-4.35,68.0,X-LC,5.72,25.0,1.13,1.66,20.07,X40N,ATH,AUTO
80,UNITDSPR,-0.16,11.47,8.34,20.77,21768.0,26866.0,261010.0,1644.00,-1.08,70.0,X-MC,7.12,64.0,1.23,1.64,25.47,X40N,NTT,BREWERIES
69,SIS,1.29,0.16,21.07,21.26,23431.0,174.0,111206.0,528.00,2655.44,57.0,H-SC,22.85,168.0,0.01,0.70,65.35,OX40N,NTT,MISC

In [10]:
# top 5 today
df_tmp = df_portfolio_features.sort_values(by = 'Today P/L%', ascending=False)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
25,FINCABLES,2.89,30.75,59.01,107.91,113918.0,45405.0,193049.0,1641.55,17.71,52.0,M-SC,17.62,220.0,0.40,1.21,45.24,OX40N,ATH,CABLES
82,VALIANTORG,2.83,-40.44,192.39,74.15,187473.0,-66161.0,97444.0,838.00,-275.30,59.0,H-SC,4.08,145.0,-0.35,0.61,45.01,XR,NTT,CHEMICALS
75,TCS,2.47,-28.61,73.98,24.20,244660.0,-132562.0,330711.0,4230.71,-39.69,62.0,X-LC,15.69,2.0,-0.54,2.07,23.32,X40,ATH,IT
78,TRIDENT,2.29,-31.81,88.46,28.51,55651.0,-29344.0,62911.0,48.00,-12.37,55.0,M-SC,3.39,223.0,-0.53,0.39,17.86,XR,NTT,TEXTILES
52,M&M,2.26,9.98,8.04,18.82,21282.0,24019.0,264700.0,3762.88,-4.35,68.0,X-LC,5.72,25.0,1.13,1.66,20.07,X40N,ATH,AUTO

In [11]:
# bottom 5 today
df_tmp = df_portfolio_features.sort_values(by = 'Today P/L%', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
18,COFFEEDAY,-5.04,-45.21,146.91,35.27,91390.0,-51341.0,62208.0,80.00,-57.75,53.0,L-SC,5.65,266.0,-0.56,0.39,53.41,XR,NTT,HOTELS
16,CERA,-4.17,-20.75,56.33,23.89,78526.0,-36500.0,139403.0,9475.00,-23.63,44.0,H-SC,12.78,153.0,-0.46,0.87,35.51,OX40N,NTT,CERAMICS
28,GODREJCP,-3.28,-5.21,40.98,33.64,96932.0,-13003.0,236534.0,1469.04,-1.98,44.0,X-LC,5.19,32.0,-0.13,1.48,6.33,X40N,ATH,FMCG
11,BERGEPAINT,-2.74,-2.28,28.24,25.32,71128.0,-5880.0,251869.0,680.00,-7.53,60.0,X-MC,2.08,68.0,-0.08,1.58,32.08,XY24,NTT,PAINTS
66,SFL,-2.62,-33.21,89.60,26.63,156916.0,-87088.0,175130.0,1287.00,32.67,33.0,M-SC,24.59,242.0,-0.55,1.10,46.16,XY24,NTT,MISC

In [12]:
# top 5 to exit based on CumlRnk
df_tmp = df_portfolio_features[~df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])]
df_tmp = df_tmp[(df_tmp['Current P/L%'] > -1) & (df_tmp['Current P/L%'] < 1)].sort_values(by = 'CumlRnk', ascending=False)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
5,ATULAUTO,-1.07,-0.87,46.85,45.57,91552.0,-1717.0,195415.0,844.0,4251.35,75.0,M-SC,8.59,248.0,-0.02,1.23,50.38,XY24,NTT,AUTO
61,RECLTD,1.36,-0.81,21.72,20.74,43770.0,-1650.0,201520.0,446.0,9.37,57.0,M-MC,3.41,191.0,-0.04,1.26,21.47,XY25,NTT,FINANCE
69,SIS,1.29,0.16,21.07,21.26,23431.0,174.0,111206.0,528.0,2655.44,57.0,H-SC,22.85,168.0,0.01,0.70,65.35,OX40N,NTT,MISC

In [13]:
# OX40N stocks to exit
df_tmp = df_portfolio_features[(df_portfolio_features['Symbol'].isin(list_ox40n))].sort_values(by = 'Current P/L%', ascending=False)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
25,FINCABLES,2.89,30.75,59.01,107.91,113918.0,45405.0,193049.0,1641.55,17.71,52.0,M-SC,17.62,220.0,0.40,1.21,45.24,OX40N,ATH,CABLES
69,SIS,1.29,0.16,21.07,21.26,23431.0,174.0,111206.0,528.00,2655.44,57.0,H-SC,22.85,168.0,0.01,0.70,65.35,OX40N,NTT,MISC
79,TTKPRESTIG,0.05,-18.29,22.50,0.09,18526.0,-18437.0,82340.0,770.00,91.04,49.0,M-SC,13.83,250.0,-1.00,0.52,48.20,OX40N,NTT,DURABLES
16,CERA,-4.17,-20.75,56.33,23.89,78526.0,-36500.0,139403.0,9475.00,-23.63,44.0,H-SC,12.78,153.0,-0.46,0.87,35.51,OX40N,NTT,CERAMICS
43,INDIGOPNTS,1.96,-20.99,26.60,0.02,36685.0,-36646.0,137913.0,1408.00,110.38,61.0,M-SC,4.61,222.0,-1.00,0.87,56.47,OX40N,NTT,PAINTS

In [14]:
# top 5 to book for rotation
df_tmp = df_portfolio_features[(df_portfolio_features['Current P/L%'] > 20) ].sort_values(by = 'CumlRnk', ascending=False)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
25,FINCABLES,2.89,30.75,59.01,107.91,113918.0,45405.0,193049.0,1641.55,17.71,52.0,M-SC,17.62,220.0,0.40,1.21,45.24,OX40N,ATH,CABLES
55,MEDANTA,1.45,25.35,1.41,27.12,3120.0,44743.0,221260.0,1486.00,21.43,68.0,X-SC,15.41,87.0,14.34,1.39,52.46,XY24,NTT,HEALTHCARE
58,QUESS,-1.78,25.79,38.25,73.90,51383.0,27542.0,134335.0,424.00,-32.23,56.0,X-SC,39.39,80.0,0.54,0.84,84.89,XY24,NTT,MISC

In [15]:
# top 5 to monitor for exit
df_tmp = df_portfolio_features[~df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])]
df_tmp = df_tmp[(df_tmp['Current P/L%'] > 0) ].sort_values(by = 'Dev%_PE', ascending=False)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
69,SIS,1.29,0.16,21.07,21.26,23431.0,174.0,111206.0,528.00,2655.44,57.0,H-SC,22.85,168.0,0.01,0.70,65.35,OX40N,NTT,MISC
70,STARHEALTH,-0.30,10.68,33.05,47.26,102832.0,30018.0,311141.0,761.00,74.78,44.0,H-SC,17.63,173.0,0.29,1.95,34.53,XY24,NTT,INSURANCE
25,FINCABLES,2.89,30.75,59.01,107.91,113918.0,45405.0,193049.0,1641.55,17.71,52.0,M-SC,17.62,220.0,0.40,1.21,45.24,OX40N,ATH,CABLES
87,ZYDUSLIFE,-0.19,16.62,16.20,35.51,39593.0,34830.0,244404.0,1285.01,1.35,45.0,H-MC,15.55,120.0,0.88,1.53,28.62,AR,ATH,PHARMA

In [16]:
# top 5 to book for rotation from weak conviction
df_tmp = df_portfolio_features[~df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])]
df_tmp = df_tmp[~df_tmp['Criteria'].isin(['XY25','XY24','X40', 'X40N'])].sort_values(by = 'RRR Ind', ascending=False)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
87,ZYDUSLIFE,-0.19,16.62,16.20,35.51,39593.0,34830.0,244404.0,1285.01,1.35,45.0,H-MC,15.55,120.0,0.88,1.53,28.62,AR,ATH,PHARMA
25,FINCABLES,2.89,30.75,59.01,107.91,113918.0,45405.0,193049.0,1641.55,17.71,52.0,M-SC,17.62,220.0,0.40,1.21,45.24,OX40N,ATH,CABLES
69,SIS,1.29,0.16,21.07,21.26,23431.0,174.0,111206.0,528.00,2655.44,57.0,H-SC,22.85,168.0,0.01,0.70,65.35,OX40N,NTT,MISC
3,ALKYLAMINE,-2.06,-19.08,137.95,92.54,112700.0,-19267.0,81696.0,4520.85,-13.41,58.0,H-SC,13.36,142.0,-0.17,0.51,55.13,SR,ATH,CHEMICALS
42,INDIAMART,-1.08,-24.52,166.19,100.92,154713.0,-30242.0,93094.0,4675.60,-66.02,35.0,H-SC,11.64,140.0,-0.20,0.58,0.77,AR,ATH,MISC

In [17]:
# top 5 to accumulate based on lowest RSI_14
df_tmp = df_portfolio_features[df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])].sort_values(by = 'RSI_14', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
34,HDFCBANK,-0.16,-10.46,46.35,31.05,121654.0,-30652.0,262468.0,1073.00,-25.47,35.0,X-LC,10.56,26.0,-0.25,1.65,1.88,X40,BTT,BANKS
57,PGHH,0.17,-36.32,107.31,32.01,145907.0,-77552.0,135968.0,17616.87,-56.92,36.0,X-MC,19.20,57.0,-0.53,0.85,0.25,X40,ATH,FMCG
83,VBL,-0.74,-10.69,51.90,35.66,163080.0,-37625.0,314219.0,669.42,-21.38,38.0,X-LC,7.76,13.0,-0.23,1.97,15.69,X40N,ATH,FMCG
20,DABUR,-0.52,-20.01,79.64,43.70,158036.0,-49630.0,198438.0,735.00,-27.41,38.0,X-MC,9.15,70.0,-0.31,1.25,0.98,XY24,BTT,FMCG
35,HDFCLIFE,0.16,-6.82,49.33,39.15,115255.0,-17097.0,233640.0,811.41,-30.57,41.0,X-LC,15.94,31.0,-0.15,1.47,1.38,X40,ATH,INSURANCE

In [18]:
# top 5 to accumulate based on Spread and CumlRnk
df_tmp = df_portfolio_features[df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])]
df_tmp = df_tmp[(df_tmp['CumlRnk'] < 100)].sort_values(by = 'Spread%', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
19,COLPAL,-0.32,-23.23,82.18,39.86,166160.0,-61175.0,202190.0,3683.41,-7.20,44.0,X-MC,1.63,62.0,-0.37,1.27,14.37,XY25,ATH,FMCG
11,BERGEPAINT,-2.74,-2.28,28.24,25.32,71128.0,-5880.0,251869.0,680.00,-7.53,60.0,X-MC,2.08,68.0,-0.08,1.58,32.08,XY24,NTT,PAINTS
8,BAJAJHLDNG,-1.31,1.93,25.82,28.24,67373.0,4930.0,260935.0,14274.15,-6.07,64.0,X-LC,2.58,28.0,0.07,1.64,31.33,X40,ATH,FINANCE
23,DMART,-0.76,-4.90,38.20,31.42,113263.0,-15291.0,296499.0,5391.45,-20.94,41.0,X-LC,3.24,14.0,-0.14,1.86,6.99,X40N,ATH,FMCG
26,GILLETTE,-0.31,-9.37,43.14,29.72,99265.0,-23796.0,230100.0,10978.86,-30.33,45.0,X-SC,3.41,83.0,-0.24,1.44,5.74,X40,ATH,FMCG

In [19]:
# top 5 to accumulate based on lowest Gained%
df_tmp = df_portfolio_features[df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])].sort_values(by = 'Gained%', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
57,PGHH,0.17,-36.32,107.31,32.01,145907.0,-77552.0,135968.0,17616.87,-56.92,36.0,X-MC,19.20,57.0,-0.53,0.85,0.25,X40,ATH,FMCG
20,DABUR,-0.52,-20.01,79.64,43.70,158036.0,-49630.0,198438.0,735.00,-27.41,38.0,X-MC,9.15,70.0,-0.31,1.25,0.98,XY24,BTT,FMCG
35,HDFCLIFE,0.16,-6.82,49.33,39.15,115255.0,-17097.0,233640.0,811.41,-30.57,41.0,X-LC,15.94,31.0,-0.15,1.47,1.38,X40,ATH,INSURANCE
34,HDFCBANK,-0.16,-10.46,46.35,31.05,121654.0,-30652.0,262468.0,1073.00,-25.47,35.0,X-LC,10.56,26.0,-0.25,1.65,1.88,X40,BTT,BANKS
47,ITC,-0.38,-21.43,58.71,24.70,183258.0,-85137.0,312141.0,452.00,-58.75,50.0,X-LC,11.32,1.0,-0.46,1.96,3.36,X40,NTT,FMCG

In [20]:
# top 5 to accumulate based on lowest CurrAlloc%
df_tmp = df_portfolio_features[df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])].sort_values(by = 'CurrAlloc%', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
10,BATAINDIA,-1.09,-53.42,190.26,35.20,114030.0,-68736.0,59934.0,2096.00,-21.44,62.0,X-SC,14.79,91.0,-0.60,0.38,20.41,X40,NTT,FOOTWEAR
62,RELAXO,1.91,-45.07,177.29,52.31,141355.0,-65429.0,79731.0,1176.00,-41.54,61.0,X-SC,11.07,92.0,-0.46,0.50,78.27,X40N,NTT,FOOTWEAR
58,QUESS,-1.78,25.79,38.25,73.90,51383.0,27542.0,134335.0,424.00,-32.23,56.0,X-SC,39.39,80.0,0.54,0.84,84.89,XY24,NTT,MISC
57,PGHH,0.17,-36.32,107.31,32.01,145907.0,-77552.0,135968.0,17616.87,-56.92,36.0,X-MC,19.20,57.0,-0.53,0.85,0.25,X40,ATH,FMCG
40,ICICIPRULI,-2.32,-16.51,56.03,30.28,92160.0,-32522.0,164483.0,787.27,-38.91,49.0,X-MC,13.71,78.0,-0.35,1.03,9.59,X40,ATH,INSURANCE

In [21]:
# top 5 to accumulate based on CumlRnk
df_tmp = df_portfolio_features.sort_values(by = 'CumlRnk', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
47,ITC,-0.38,-21.43,58.71,24.70,183258.0,-85137.0,312141.0,452.00,-58.75,50.0,X-LC,11.32,1.0,-0.46,1.96,3.36,X40,NTT,FMCG
75,TCS,2.47,-28.61,73.98,24.20,244660.0,-132562.0,330711.0,4230.71,-39.69,62.0,X-LC,15.69,2.0,-0.54,2.07,23.32,X40,ATH,IT
45,INFY,0.71,-16.48,68.07,40.38,214042.0,-62026.0,314444.0,1972.00,-37.23,62.0,X-LC,16.36,3.0,-0.29,1.97,19.08,X40,NTT,IT
77,TMPV,-0.03,-17.86,73.79,42.75,252213.0,-74309.0,341798.0,600.00,-83.62,54.0,X-LC,5.41,4.0,-0.29,2.14,17.53,XY24,NTT,AUTO
33,HCLTECH,0.67,-10.11,37.90,23.97,105441.0,-31278.0,278208.0,1853.42,-8.19,67.0,X-LC,13.59,8.0,-0.30,1.75,31.28,X40,ATH,IT

In [22]:
# top 5 for average up
df_tmp = df_portfolio_features[(df_portfolio_features['Dev%_200'] > 5)].sort_values(by = 'CurrAlloc%', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
44,INDUSINDBK,-0.67,-25.48,78.32,32.89,45062.0,-19670.0,57536.0,1800.00,-371.01,52.0,L-MC,13.88,258.0,-0.44,0.36,41.85,XR,NTT,BANKS
62,RELAXO,1.91,-45.07,177.29,52.31,141355.0,-65429.0,79731.0,1176.00,-41.54,61.0,X-SC,11.07,92.0,-0.46,0.50,78.27,X40N,NTT,FOOTWEAR
3,ALKYLAMINE,-2.06,-19.08,137.95,92.54,112700.0,-19267.0,81696.0,4520.85,-13.41,58.0,H-SC,13.36,142.0,-0.17,0.51,55.13,SR,ATH,CHEMICALS
79,TTKPRESTIG,0.05,-18.29,22.50,0.09,18526.0,-18437.0,82340.0,770.00,91.04,49.0,M-SC,13.83,250.0,-1.00,0.52,48.20,OX40N,NTT,DURABLES
12,BOSCH-HCIL,1.22,-27.04,37.04,-0.01,34540.0,-34554.0,93251.0,2282.00,18986.96,84.0,M-SC,3.87,231.0,-1.00,0.59,58.73,OX40N,BTT,AC

In [23]:
# top 5 RSP
df_tmp = df_portfolio_features.sort_values(by = 'RSP', ascending=False)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
12,BOSCH-HCIL,1.22,-27.04,37.04,-0.01,34540.0,-34554.0,93251.0,2282.00,18986.96,84.0,M-SC,3.87,231.0,-1.00,0.59,58.73,OX40N,BTT,AC
30,HAPPSTMNDS,0.70,-48.94,258.57,83.08,169208.0,-62725.0,65440.0,1466.54,-39.37,68.0,H-SC,10.37,152.0,-0.37,0.41,22.57,AR,ATH,IT
75,TCS,2.47,-28.61,73.98,24.20,244660.0,-132562.0,330711.0,4230.71,-39.69,62.0,X-LC,15.69,2.0,-0.54,2.07,23.32,X40,ATH,IT
5,ATULAUTO,-1.07,-0.87,46.85,45.57,91552.0,-1717.0,195415.0,844.00,4251.35,75.0,M-SC,8.59,248.0,-0.02,1.23,50.38,XY24,NTT,AUTO
33,HCLTECH,0.67,-10.11,37.90,23.97,105441.0,-31278.0,278208.0,1853.42,-8.19,67.0,X-LC,13.59,8.0,-0.30,1.75,31.28,X40,ATH,IT

In [24]:
# Top N allocation
df_tmp = df_portfolio_features.sort_values(by = 'CurrAlloc%', ascending=False)
top_n_values = [10, 25, 50]

sum_df = pd.DataFrame({
    'Top_N': top_n_values,
    'Sum_Alloc%': [df_tmp['CurrAlloc%'].head(n).sum() for n in top_n_values]
})

sum_df

   Top_N  Sum_Alloc%
0     10       19.66
1     25       44.60
2     50       76.83

In [25]:
# market-cap-wise allocation
df_tmp = df_portfolio_features[cols]
df_tmp.groupby(df_tmp['Conviction'].str[-2:])['CurrAlloc%'].sum().sort_values(ascending=False)

Conviction
SC    39.35
LC    37.68
MC    22.96
Name: CurrAlloc%, dtype: float64

In [26]:
# criteria-wise allocation
df_portfolio_features.groupby('Criteria')['CurrAlloc%'].sum().sort_values(ascending=False)

Criteria
X40      26.40
XY24     25.08
X40N     18.40
XR        9.10
XY25      7.29
OX40N     6.85
AR        6.02
SR        0.85
Name: CurrAlloc%, dtype: float64

In [27]:
# conviction-wise allocation
df_portfolio_features.groupby('Conviction')['CurrAlloc%'].sum().sort_values(ascending=False)

Conviction
X-LC    35.62
H-SC    19.22
X-MC    18.74
X-SC     9.91
M-SC     9.69
H-MC     2.60
M-MC     1.26
H-LC     1.25
M-LC     0.81
L-SC     0.53
L-MC     0.36
Name: CurrAlloc%, dtype: float64

In [28]:
# sector-wise stats
df_tmp = df_portfolio_features.groupby('Category')[['CurrAlloc%', 'Current', 'Current P/L', 'FTT Amt']].sum().sort_values(by=['Current', 'Current P/L'], ascending=False)
df_tmp['Current P/L%'] = round(df_tmp['Current P/L'] * 100 / df_tmp['Current'], 2)
df_tmp['FTT%'] = round(df_tmp['FTT Amt'] * 100 / df_tmp['Current'], 2)
cols = ['CurrAlloc%', 'Current P/L%', 'FTT%']
df_tmp[cols].sort_values(by=['CurrAlloc%'], ascending=False)

               CurrAlloc%  Current P/L%    FTT%
Category
FMCG                15.45        -21.12   64.74
IT                  11.18        -33.68  100.04
FINANCE              9.33        -14.76   62.98
AUTO                 8.41         -0.88   37.02
MISC                 6.84        -22.92   75.65
BANKS                6.09        -10.07   57.54
PHARMA               5.57          6.82   19.61
INSURANCE            5.55         -4.99   42.11
PAINTS               5.37        -15.17   34.82
ELECTRICAL           4.14         -7.31   44.89
HEALTHCARE           2.09         -7.48   35.52
AC                   1.80        -11.84   42.17
APPARELS             1.76          4.53   27.53
REFINERIES           1.71         -9.68   46.52
FOOTWEAR             1.67        -65.88  132.39
BREWERIES            1.64         10.29    8.34
DURABLES             1.53        -58.99   97.67
TRAVEL               1.48        -90.71  186.20
CERAMICS             1.34        -42.74   86.11
ENGINEERING          1.22        -25.00   82.17
CABLES               1.21         23.52   59.01
CHEMICALS            1.12        -47.69  167.56
CEMENT               1.03        -63.09  185.11
JEWELLERY            1.00       -101.75  171.84
ENTERTAINMENT        0.68        -77.21  182.89
TEXTILES             0.39        -46.64   88.46
HOTELS               0.39        -82.53  146.91

In [29]:
# money to be made criteria-wise
df_portfolio_features.groupby('Criteria')['FTT Amt'].agg(['sum', 'count']).sort_values(by='sum', ascending=False)

                sum  count
Criteria
XY24      3407244.0     20
X40       2016943.0     18
XR        1344819.0     13
X40N      1146770.0     12
AR        1071197.0      8
OX40N      701419.0     10
XY25       538418.0      5
SR         281280.0      2

In [30]:
# money to be made conviction-wise
df_portfolio_features.groupby('Conviction')['FTT Amt'].agg(['sum', 'count']).sort_values(by='sum', ascending=False)

                  sum  count
Conviction
H-SC        3286843.0     23
X-LC        2382327.0     20
X-MC        1466423.0     14
M-SC        1375005.0     14
X-SC        1222620.0      9
H-MC         283430.0      2
L-SC         206558.0      2
M-LC         162075.0      1
L-MC          45062.0      1
M-MC          43770.0      1
H-LC          33977.0      1

In [31]:
# money to be made criteria and conviction-wise
df_portfolio_features.groupby(['Conviction', 'Criteria'])['FTT Amt'].agg(['sum', 'count']).sort_values(by='sum', ascending=False)

                           sum  count
Conviction Criteria
X-LC       X40       1163831.0      9
H-SC       XY24       986688.0      5
           AR         921242.0      5
M-SC       XY24       820271.0      6
H-SC       XR         800232.0      7
X-SC       XY24       710779.0      4
X-MC       X40        639817.0      7
X-LC       X40N       502878.0      6
           XY24       416505.0      2
X-MC       X40N       345346.0      3
X-SC       X40N       298546.0      3
H-SC       OX40N      297401.0      4
M-SC       OX40N      288850.0      5
H-SC       SR         281280.0      2
X-MC       XY25       252096.0      2
H-MC       XY24       243837.0      1
X-LC       XY25       242552.0      2
X-MC       XY24       229164.0      2
X-SC       X40        213295.0      2
M-SC       XR         189499.0      2
M-LC       XR         162075.0      1
L-SC       OX40N      115168.0      1
           XR          91390.0      1
M-SC       AR          76385.0      1
X-LC       XR          56561.0      1
L-MC       XR          45062.0      1
M-MC       XY25        43770.0      1
H-MC       AR          39593.0      1
H-LC       AR          33977.0      1

In [32]:
# notebook execution time

end_time = time.time()
execution_time = round(end_time - start_time, 0)
print(f"Notebook execution time: {execution_time} seconds")

Notebook execution time: 50.0 seconds