<a href="https://colab.research.google.com/github/ankit-rathi/Quantvesting_v2/blob/main/myStocks_Portfolio_Analysis.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
'''
!pip install pandas==2.2.2 -qq
!pip install pyxirr -qq
!pip install ta -qq
!pip install yfinance==0.2.59 -qq
'''

'\n!pip install pandas==2.2.2 -qq\n!pip install pyxirr -qq\n!pip install ta -qq\n!pip install yfinance==0.2.59 -qq\n'

In [2]:
# import libraries

import numpy as np
import pandas as pd
import datetime
import warnings
warnings.filterwarnings('ignore')
import yfinance as yfin
import ta
import matplotlib.pyplot as plt
import requests

In [3]:
# notebook start time
import time
import datetime
import pytz

start_time = time.time()

# function to print date timestamp
def print_date_time():
  tz_NY = pytz.timezone('Asia/Kolkata')
  datetime_NY = datetime.datetime.now(tz_NY)
  print("Run date time (IST):", datetime_NY.strftime("%Y-%m-%d %H:%M:%S"))

In [4]:
# function to get booked and reserved amount
def get_amt():
  # fetch the JSON data from the URL
  url = "https://raw.githubusercontent.com/ankit-rathi/Tradevesting_v1/main/data/myPortfolioAmts.json"
  response = requests.get(url)
  pf_amts = response.json()  # parse the JSON data

  # extract values from the JSON
  py_booked_amt_dm = pf_amts["py_booked_amt_dm"]
  py_booked_amt_sv = pf_amts["py_booked_amt_sv"]
  cy_booked_amt_dm = pf_amts["cy_booked_amt_dm"]
  cy_booked_amt_sv = pf_amts["cy_booked_amt_sv"]
  reserve_amt_dm = pf_amts["reserve_amt_dm"]
  reserve_amt_sv = pf_amts["reserve_amt_sv"]

  # perform calculations
  py_booked_amt = py_booked_amt_dm + py_booked_amt_sv
  cy_booked_amt = cy_booked_amt_dm + cy_booked_amt_sv
  reserve_amt = reserve_amt_dm + reserve_amt_sv
  total_booked_amt = py_booked_amt + cy_booked_amt

  return total_booked_amt, reserve_amt, cy_booked_amt, py_booked_amt

gen_output = 0

In [5]:
# function to format the amount
def format_amt(number):
    abs_number = abs(number)

    if abs_number >= 1_00_00_000:  # Crores
        formatted_amt = f"{number / 1_00_00_000:.2f} C"
    elif abs_number >= 1_00_000:  # Lakhs
        formatted_amt = f"{number / 1_00_000:.2f} L"
    elif abs_number >= 1_000:  # Thousands
        formatted_amt = f"{number / 1_000:.2f} K"
    else:
        formatted_amt = f"{number:.2f}"

    return formatted_amt

# function to set start and end date
def get_start_end_date():
  start_date = (datetime.date.today() + datetime.timedelta(days=-365)).strftime('%Y-%m-%d')
  end_date = (datetime.date.today() + datetime.timedelta(days=1)).strftime('%Y-%m-%d')
  return start_date, end_date

# function to fetch my portfolio csv
def get_mypfs_df():
  mypfs_df = pd.read_csv('https://raw.githubusercontent.com/ankit-rathi/Tradevesting_v1/main/data/myPortfolioStocks.csv')
  return mypfs_df

# function to fetch my prospects csv
def get_mypps_df():
  mypps_df = pd.read_csv('https://raw.githubusercontent.com/ankit-rathi/Tradevesting_v1/main/data/myProspectsScrips.csv')
  return mypps_df

# function to fetch screener data
def get_myscreen_df():
  myscreen_df = pd.read_csv('https://raw.githubusercontent.com/ankit-rathi/Tradevesting_v1/main/data/myScreenerDB.csv')
  return myscreen_df

# function to fetch momentum data
def get_myinvmt_df():
  myinvmt_df = pd.read_csv('https://raw.githubusercontent.com/ankit-rathi/Tradevesting_v1/main/data/myInvestments.csv')
  return myinvmt_df

# function to get the stock ids
def get_stock_ids(df_pf):
  stock_n100 = df_pf['Symbol'].unique()

  exclude = ['CADILAHC','MMTC', 'MASFIN']

  stock_ids = df_pf[~df_pf['Symbol'].isin(exclude) ]['Symbol'].unique()

  #mypf = mypf[mypf.Forecast.notnull()]
  #stock_ids = mypf['Symbol'].unique()

  #stock_ids.sort()
  return stock_ids

# get features from screener data
def get_screener_features():
  myscreen_df = get_myscreen_df()
  cols = ['Symbol', 'EPS', 'MedPE', 'ROCE%', 'ROE%', 'CapType']
  return myscreen_df[cols]

# get relative strength
def get_relative_strength(stock_list):

    # Dictionary to store stock tickers and their corresponding percentage price change
    stock_changes = {}

    # Loop through each stock and fetch its price data
    for stock in stock_list:
        try:
            # Download the stock data for the given date range
            stock_data = yfin.Ticker(stock + '.NS').history(period='1mo', interval='1d')[map(str.title, ['open', 'close', 'low', 'high', 'volume'])]

            # Calculate the percentage change for the stock
            if len(stock_data) > 0:
                start_price = stock_data['Close'].iloc[0]
                end_price = stock_data['Close'].iloc[-1]
                percent_change = round(((end_price - start_price) / start_price) * 100, 2)
                stock_changes[stock] = percent_change
            else:
                stock_changes[stock] = np.nan  # If no data is available, set to NaN

        except Exception as e:
            print(f"Error fetching data for {stock}: {e}")
            stock_changes[stock] = np.nan

    # Create a DataFrame with stock tickers and their percentage changes
    df = pd.DataFrame(list(stock_changes.items()), columns=['Symbol', 'Percent_Change'])

    # Drop any stocks with missing data (NaN values)
    df = df.dropna()

    # Calculate the percentile rank based on percentage change
    df['RSP'] = round(df['Percent_Change'].rank(pct=True) * 100, 2)
    cols = ['Symbol', 'RSP']
    df = df[cols]
    # Sort by percentile rank (optional)
    df = df.sort_values(by='RSP', ascending=False).reset_index(drop=True)

    return df

In [6]:
# function to get stock technicals
def stock_prec_dev(stock_symbol):
    #stock_symbol = 'ULTRACEMCO.NS'
    short_window = 20
    mid_window = 50
    long_window = 200
    moving_avg = 'SMA'

    start = datetime.datetime(*map(int, start_date.split('-')))
    end = datetime.datetime(*map(int, end_date.split('-')))

    stock_df = yfin.Ticker(stock_symbol + '.NS').history(period='max', interval='1d')[map(str.title, ['open', 'close', 'low', 'high', 'volume'])]

    stock_df['Max'] = round(max(stock_df['Close']),2)
    stock_df = stock_df[(stock_df.index <= end_date) & (stock_df.index >= start_date)]
    stock_df['200_SMA'] = round(stock_df['Close'].rolling(window = 200, min_periods = 1).mean(),0)
    stock_df['Dev%_200'] = round((stock_df['Close'] - stock_df['200_SMA'])*100/stock_df['200_SMA'],2)
    stock_df.dropna(axis = 0, inplace = True) # remove any null rows

    stock_df['20_SMA'] = stock_df['Close'].rolling(window=20).mean()
    stock_df['50_SMA'] = stock_df['Close'].rolling(window=50).mean()
    stock_df['Symbol'] = stock_symbol

    stock_df['Close'] = round(stock_df['Close'],2)
    stock_df['Min'] = round(min(stock_df['Close']),2)
    stock_df['RSI_14'] = ta.momentum.RSIIndicator(close=stock_df['Close'], window=14).rsi()
    stock_df['RSI_14'] = round(stock_df['RSI_14'],0)
    stock_df['Prev_Close'] = stock_df['Close'].shift(1)
    stock_df.drop(['Open', 'Low', 'High', 'Volume'], axis=1, inplace=True)
    stock_df = stock_df.tail(1)

    max_SMA = max(stock_df['20_SMA'].item(), stock_df['50_SMA'].item(), stock_df['200_SMA'].item())
    min_SMA = min(stock_df['20_SMA'].item(), stock_df['50_SMA'].item(), stock_df['200_SMA'].item())
    ABS_Spread = max_SMA - min_SMA
    stock_df['Spread%'] = round((ABS_Spread / stock_df['200_SMA'].item()) * 100,2)

    return stock_df

# function to compute stock attributes
def get_common_features(stock_ids, df_mypf):

  df_prec_dev = pd.DataFrame()
  df_tmp = get_screener_features()
  df_rs = get_relative_strength(stock_ids)

  for stock_id in stock_ids:
      tmp = stock_prec_dev(stock_id)
      tmp = tmp.reset_index()
      df_prec_dev = pd.concat([df_prec_dev, tmp], ignore_index = True)
  df_prec_dev = pd.merge(df_prec_dev, df_mypf, on= 'Symbol')
  df_prec_dev = pd.merge(df_prec_dev, df_tmp, on= 'Symbol', how='left')
  df_prec_dev = pd.merge(df_prec_dev, df_rs, on= 'Symbol', how='left')
  #print(df_prec_dev.columns)
  df_prec_dev['Curr_PE'] = round(df_prec_dev['Close']/df_prec_dev['EPS'],1)
  df_prec_dev['Dev%_PE'] = round((df_prec_dev['Curr_PE'] - df_prec_dev['MedPE'])*100/df_prec_dev['MedPE'],2)
  df_prec_dev['Conviction'] = df_prec_dev['Conviction'] + '-' + df_prec_dev['CapType']
  return df_prec_dev

# function to arrange stock features
def arrange_features(df_stocks, common_cols, diff_cols):
  df_stocks_common = df_stocks[common_cols].drop_duplicates()
  df_stocks_diff = df_stocks[diff_cols]
  df_stocks_diff['Investment'] = df_stocks_diff['AvgCost'] * df_stocks_diff['Shares']
  df_stocks_diff = df_stocks_diff.groupby(['Symbol'])[['Shares', 'Investment']].aggregate(['sum']).reset_index()
  df_stocks_diff.columns = ['Symbol', 'Shares', 'Investment']
  df_stocks_diff['AvgCost'] = round(df_stocks_diff['Investment']/df_stocks_diff['Shares'],2)
  df_stocks = pd.merge(df_stocks_diff, df_stocks_common, on='Symbol')
  return df_stocks

# plot fact distribution across dimension
def plot_pie_chart(df, dimension, fact):
  # grouping the data by category and calculating the sum of fact for each type
  grouped_data = df.groupby(dimension)[fact].sum()

  # sorting the grouped data in descending order
  grouped_data = grouped_data.sort_values(ascending=False)

  # creating a pie chart
  grouped_data.plot.pie(autopct='%1.1f%%', startangle=90, figsize=(6, 6))

  # adding a title and displaying the plot
  plt.title(f'{dimension} {fact} Distribution')
  plt.ylabel('')  # To hide the y-label
  plt.show()

In [7]:
# function to get portfolio features

def get_portfolio_features(df_common_features):

  print_date_time()
  print('-------------------')

  #df_common_features["Target"] = df_common_features["Target"].fillna(df_common_features["Max"])
  df_common_features['NTT'] = np.where(df_common_features['Strategy']== 'NTT', df_common_features["Target"], df_common_features['Max'])
  df_common_features['LTT'] = np.where(df_common_features['Strategy']== 'BTT', df_common_features["Target"], df_common_features['Max'])
  df_common_features['BOL'] = df_common_features['Min']

  tmp_df = df_common_features[df_common_features['Symbol'].isin(mypf_df[mypf_df['InPortfolio'] != 'NA'].Symbol.values)]
  print('qualified stocks: '+str(len(tmp_df['Symbol'].unique())))
  tmp_df1 = tmp_df[tmp_df['LatestQtr'] == 1]
  print('with latest results: '+str(len(tmp_df1['Symbol'].unique())))
  tmp_df1 = tmp_df1[tmp_df1['StarStock'] == 1]
  print('still star stocks: '+str(len(tmp_df1['Symbol'].unique())))
  tmp_df['Investment'] = tmp_df['AvgCost'] * tmp_df['Shares']
  tmp_df['Current'] = round(tmp_df['Close'] * tmp_df['Shares'],0)
  tmp_df['Previous'] = tmp_df['Prev_Close'] * tmp_df['Shares']
  tmp_df['EstimatedST'] = tmp_df['NTT'] * tmp_df['Shares']
  tmp_df['EstimatedLT'] = tmp_df['LTT'] * tmp_df['Shares']
  tmp_df['Current P/L'] = round((tmp_df['Current'] - tmp_df['Investment']),0)
  tmp_df['Today P/L%'] = round((tmp_df['Current'] - tmp_df['Previous'])*100/tmp_df['Previous'],2)
  tmp_df['Current P/L%'] = round((tmp_df['Current'] - tmp_df['Investment'])*100/tmp_df['Investment'],2)
  tmp_df['EstimatedST P/L%'] = round((tmp_df['EstimatedST'] - tmp_df['Investment'])*100/tmp_df['Investment'],2)
  tmp_df['EstimatedLT P/L%'] = round((tmp_df['EstimatedLT'] - tmp_df['Investment'])*100/tmp_df['Investment'],2)
  tmp_df['NTT%'] = round((tmp_df['NTT'] - tmp_df['Close'])*100/tmp_df['Close'],2)
  tmp_df['LTT%'] = round((tmp_df['LTT'] - tmp_df['Close'])*100/tmp_df['Close'],2)
  tmp_df['Gained%'] = round((tmp_df['Close'] - tmp_df['BOL'])*100/tmp_df['BOL'],2)
  investment = round(sum(tmp_df['AvgCost']*tmp_df['Shares']),0)
  current = round(sum(tmp_df['Close']*tmp_df['Shares']),0)
  tmp_df['InitAlloc%'] = round(tmp_df['Investment']*100/investment,2)
  tmp_df['CurrAlloc%'] = round(tmp_df['Current']*100/current,2)
  tmp_df['FTT'] = tmp_df['LTT']
  tmp_df.loc[tmp_df['Strategy'] == 'NTT', 'FTT'] = tmp_df['NTT']
  tmp_df['FTT%'] = tmp_df['LTT%']
  tmp_df.loc[tmp_df['Strategy'] == 'NTT', 'FTT%'] = tmp_df['NTT%']
  tmp_df['FTT Amt'] = round(tmp_df['FTT%'] * tmp_df['Current']/100,0)
  tmp_df['OTT%'] = round((tmp_df['FTT'] - tmp_df['AvgCost'])*100/tmp_df['AvgCost'],2)
  tmp_df['RRR Ind'] = round(tmp_df['Current P/L']/tmp_df['FTT Amt'],2)
  tmp_df['Risk Ind'] = round(tmp_df['Current P/L%']*tmp_df['CurrAlloc%'],0)

  return tmp_df

# function to print portfolio features
def print_portfolio_stats(df_portfolio_features, myinvmt_df):
  from pyxirr import xirr

  total_booked_amt, reserve_amt, cy_booked_amt, py_booked_amt = get_amt()

  dates = myinvmt_df['Date'].values
  dates = np.append(dates, datetime.date.today().strftime('%d-%b-%y'))
  investment = myinvmt_df['Investment'].values
  dates= pd.to_datetime(dates)

  current = round(sum(df_portfolio_features['Close']*df_portfolio_features['Shares']),0) + reserve_amt
  investment_xirr = np.append(investment, current)
  cagr = round(xirr(pd.DataFrame({"dates": dates, "amounts": investment_xirr}))*100,2)

  investment = -sum(investment)
  invested = round(sum(df_portfolio_features['AvgCost']*df_portfolio_features['Shares']),0) + reserve_amt
  previous = round(sum(df_portfolio_features['Prev_Close']*df_portfolio_features['Shares']),0) + reserve_amt
  cy_invested = investment + py_booked_amt

  today_pnl_amount = current-previous
  today_pnl_percentage = round((current-previous)*100/previous,2)

  curr_pnl_amount = current-invested
  curr_pnl_percentage = round((curr_pnl_amount)*100/(cy_invested),2)

  cy_pnl_amount = cy_booked_amt + curr_pnl_amount
  cy_pnl_percentage = round((cy_pnl_amount)*100/cy_invested,2)

  overall_pnl_amount = total_booked_amt + curr_pnl_amount
  overall_pnl_percentage = round((overall_pnl_amount)*100/investment,2)

  estimate_st = round(sum(df_portfolio_features['FTT']*df_portfolio_features['Shares']),0)  + reserve_amt
  est_st_pnl_amount = estimate_st-current
  est_st_pnl_percentage = round((est_st_pnl_amount)*100/current,2)

  estimate_lt = round(sum(df_portfolio_features['LTT']*df_portfolio_features['Shares']),0)  + reserve_amt
  est_lt_pnl_amount = estimate_lt-current
  est_lt_pnl_percentage = round((est_lt_pnl_amount)*100/current,2)

  total_profit = round(sum(df_portfolio_features[df_portfolio_features['Current P/L%'] > 0]['Current']) - sum(df_portfolio_features[df_portfolio_features['Current P/L%'] > 0]['Investment']),0)
  total_loss = round(sum(df_portfolio_features[df_portfolio_features['Current P/L%'] < 0]['Current']) - sum(df_portfolio_features[df_portfolio_features['Current P/L%'] < 0]['Investment']),0)

  cy_booked_percentage = round((cy_booked_amt)*100/current,2)
  py_booked_percentage = round((py_booked_amt)*100/investment,2)
  total_booked_percentage = round((total_booked_amt)*100/investment,2)

  print('-------------------')
  print('Initial Investment: ', format_amt(investment))
  print('CY Investment: ', format_amt(cy_invested))
  print('Reserve: ', format_amt(reserve_amt))
  print('Current: ',  format_amt(current))
  print('-------------------')
  print('Today PnL: '+ '{} ({}%)'.format(format_amt(today_pnl_amount), today_pnl_percentage))
  print('Current PnL: '+ '{} ({}%)'.format(format_amt(curr_pnl_amount), curr_pnl_percentage))
  print('CY Booked + Current PnL: '+ '{} ({}%)'.format(format_amt(cy_pnl_amount), cy_pnl_percentage))
  print('-------------------')
  print('Total profit: ', format_amt(total_profit))
  print('Total loss: ', format_amt(total_loss))
  print('-------------------')
  print('Total Booked + Current PnL: '+ '{} ({}%)'.format(format_amt(overall_pnl_amount), overall_pnl_percentage))
  print('Total Booked PnL: '+ '{} ({}%)'.format(format_amt(total_booked_amt), total_booked_percentage))
  print('Curr Year Booked PnL: '+ '{} ({}%)'.format(format_amt(cy_booked_amt), cy_booked_percentage))
  print('Prev Year Booked PnL: '+ '{} ({}%)'.format(format_amt(py_booked_amt), py_booked_percentage))
  print('===================')
  print('Est FTT: ',  format_amt(estimate_st))
  print('Est FTT PnL: '+ '{} ({}%)'.format(format_amt(est_st_pnl_amount), est_st_pnl_percentage))

  print('===================')
  print('Deployed: ', format_amt(investment))

  print('Current: ', format_amt(current))

  print('CAGR/XIRR %: '+'{}%'.format(cagr))

In [8]:
# get start and end date
start_date, end_date = get_start_end_date()

# get portfolio and prospects data
mypfs_df = get_mypfs_df()
mypps_df = get_mypps_df()
myinvmt_df = get_myinvmt_df()

# merge above datasets
mypf_df = pd.merge(mypfs_df, mypps_df, on="Symbol")

# seggregate dm and sv portfolio
dm_pf = mypf_df[mypf_df['InPortfolio'] == 'DM']
sv_pf = mypf_df[mypf_df['InPortfolio'] == 'SV']

# build portfolio stock dataframe
dm_stocks = get_stock_ids(dm_pf)
sv_stocks = get_stock_ids(sv_pf)
df_stocks = pd.concat([dm_pf,sv_pf], ignore_index = True)

# arrange common and diff stock features
common_cols = ['Symbol', 'Target', 'Criteria', 'Strategy', 'CumlRnk', 'LatestQtr', 'StarStock', 'Conviction', 'Category', 'InFolio', 'XIRR', 'MBQ']
diff_cols = ['Symbol', 'AvgCost', 'Shares']
df_stocks = arrange_features(df_stocks, common_cols, diff_cols)

# get common features
stock_ids = df_stocks['Symbol'].values
df_common_features = get_common_features(stock_ids, df_stocks)

df_common_features.reset_index(drop=True, inplace=True)
df_common_features.drop(['Date'], axis=1, inplace=True)
# get and print portfolio features
df_portfolio_features = get_portfolio_features(df_common_features)

print_portfolio_stats(df_portfolio_features, myinvmt_df)

df = df_portfolio_features
#plot_pie_chart(df, 'CapType', 'Current')
list_ox40n = list(df[df['MBQ'].str.contains('OX40N', na=False)]['Symbol'].values)

Run date time (IST): 2026-03-11 13:26:54
-------------------
qualified stocks: 86
with latest results: 26
still star stocks: 15
-------------------
Initial Investment:  1.36 C
CY Investment:  1.62 C
Reserve:  66.25 K
Current:  1.37 C
-------------------
Today PnL: 2.76 K (0.02%)
Current PnL: -39.51 L (-24.32%)
CY Booked + Current PnL: -23.83 L (-14.67%)
-------------------
Total profit:  1.13 L
Total loss:  -40.64 L
-------------------
Total Booked + Current PnL: 3.15 L (2.32%)
Total Booked PnL: 42.66 L (31.48%)
Curr Year Booked PnL: 15.68 L (11.41%)
Prev Year Booked PnL: 26.98 L (19.91%)
===================
Est FTT:  2.47 C
Est FTT PnL: 1.10 C (79.96%)
===================
Deployed:  1.36 C
Current:  1.37 C
CAGR/XIRR %: 0.71%

In [9]:
# top 5 near their targets
cols = ['Symbol', 'Today P/L%', 'Current P/L%', 'FTT%', 'OTT%', 'FTT Amt', 'Current P/L', 'Current', 'FTT', 'Dev%_PE', 'RSI_14','Conviction', 'Spread%',  'CumlRnk', 'RRR Ind', 'CurrAlloc%', 'Gained%', 'Criteria', 'Strategy', 'Category']
df_tmp = df_portfolio_features[~df_portfolio_features['Symbol'].isin(['ENRIN','BLUSPRING','DIGITIDE'])]
df_tmp = df_tmp.sort_values(by = 'FTT Amt', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
19,COALINDIA,1.41,10.61,6.38,17.67,10618.0,15966.0,166426.0,478.51,33.43,62.0,L-LC,11.56,185.0,1.50,1.22,29.24,XY25,ATH,MINING
50,MASFIN,-0.97,-6.20,29.60,21.57,27204.0,-6075.0,91905.0,397.04,-19.15,40.0,H-SC,4.62,167.0,-0.22,0.67,28.24,XR,ATH,FINANCE
77,TTKPRESTIG,9.18,-31.24,45.56,0.09,31573.0,-31478.0,69299.0,770.00,60.94,49.0,M-SC,15.21,250.0,-1.00,0.51,17.09,OX40N,NTT,DURABLES
37,ICICIGI,0.06,0.14,19.17,19.34,38415.0,284.0,200393.0,2252.93,-15.67,48.0,X-MC,1.65,66.0,0.01,1.47,14.29,X40,ATH,INSURANCE
78,UNITDSPR,-1.27,2.05,18.34,20.77,43822.0,4798.0,238942.0,1644.00,-9.55,52.0,X-MC,1.51,64.0,0.11,1.75,8.89,X40N,NTT,BREWERIES

In [10]:
# top 5 today
df_tmp = df_portfolio_features.sort_values(by = 'Today P/L%', ascending=False)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
77,TTKPRESTIG,9.18,-31.24,45.56,0.09,31573.0,-31478.0,69299.0,770.00,60.94,49.0,M-SC,15.21,250.0,-1.00,0.51,17.09,OX40N,NTT,DURABLES
31,HAPPSTMNDS,7.38,-46.32,244.35,84.85,168113.0,-59365.0,68800.0,1480.71,-36.21,67.0,H-SC,28.48,152.0,-0.35,0.50,27.41,AR,ATH,IT
55,RAJESHEXPO,4.99,-77.85,351.85,0.07,106892.0,-106797.0,30380.0,518.00,1013.64,23.0,L-SC,18.85,268.0,-1.00,0.22,4.99,OX40N,NTT,JEWELLERY
70,SYMPHONY,4.31,-36.69,57.90,-0.03,62735.0,-62791.0,108350.0,1306.00,-49.12,48.0,M-SC,13.20,205.0,-1.00,0.79,9.57,OX40N,NTT,DURABLES
8,AWL,3.63,-36.12,161.44,67.02,367471.0,-128688.0,227621.0,485.00,-65.55,36.0,X-SC,22.60,81.0,-0.35,1.66,5.64,XY24,NTT,FMCG

In [11]:
# bottom 5 today
df_tmp = df_portfolio_features.sort_values(by = 'Today P/L%', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
21,COLPAL,-5.75,-21.33,79.87,41.51,165491.0,-56165.0,207200.0,3726.84,-4.73,38.0,X-MC,4.17,62.0,-0.34,1.52,1.24,XY25,ATH,FMCG
27,FINCABLES,-3.19,13.91,82.52,107.91,138789.0,20544.0,168188.0,1641.55,2.49,57.0,M-SC,7.71,220.0,0.15,1.23,26.53,OX40N,ATH,CABLES
75,TMPV,-2.25,-23.19,77.80,36.58,212654.0,-82507.0,273334.0,600.00,-83.62,36.0,X-LC,1.87,4.0,-0.39,2.00,1.64,XY24,NTT,AUTO
5,ANGELONE,-2.21,-9.70,37.52,24.18,103335.0,-29588.0,275412.0,303.00,-86.88,34.0,X-SC,4.73,97.0,-0.29,2.01,15.34,X40N,NTT,FINANCE
20,COFFEEDAY,-1.95,-55.77,205.81,35.27,103372.0,-63322.0,50227.0,80.00,-65.79,27.0,L-SC,18.04,266.0,-0.61,0.37,12.13,XR,NTT,HOTELS

In [12]:
# top 5 to exit based on CumlRnk
df_tmp = df_portfolio_features[~df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])]
df_tmp = df_tmp[(df_tmp['Current P/L%'] > -1) & (df_tmp['Current P/L%'] < 1)].sort_values(by = 'CumlRnk', ascending=False)
df_tmp[cols].head()

Empty DataFrame
Columns: [Symbol, Today P/L%, Current P/L%, FTT%, OTT%, FTT Amt, Current P/L, Current, FTT, Dev%_PE, RSI_14, Conviction, Spread%, CumlRnk, RRR Ind, CurrAlloc%, Gained%, Criteria, Strategy, Category]
Index: []

In [13]:
# OX40N stocks to exit
df_tmp = df_portfolio_features[(df_portfolio_features['Symbol'].isin(list_ox40n))].sort_values(by = 'Current P/L%', ascending=False)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
27,FINCABLES,-3.19,13.91,82.52,107.91,138789.0,20544.0,168188.0,1641.55,2.49,57.0,M-SC,7.71,220.0,0.15,1.23,26.53,OX40N,ATH,CABLES
77,TTKPRESTIG,9.18,-31.24,45.56,0.09,31573.0,-31478.0,69299.0,770.00,60.94,49.0,M-SC,15.21,250.0,-1.00,0.51,17.09,OX40N,NTT,DURABLES
66,SIS,0.31,-33.12,81.32,21.26,60385.0,-36776.0,74256.0,528.00,1739.90,37.0,H-SC,10.02,168.0,-0.61,0.54,2.37,OX40N,NTT,MISC
70,SYMPHONY,4.31,-36.69,57.90,-0.03,62735.0,-62791.0,108350.0,1306.00,-49.12,48.0,M-SC,13.20,205.0,-1.00,0.79,9.57,OX40N,NTT,DURABLES
72,TATAELXSI,0.67,-36.79,108.87,32.03,90724.0,-48503.0,83332.0,9161.00,-20.87,32.0,H-SC,16.55,158.0,-0.53,0.61,1.91,OX40N,NTT,IT

In [14]:
# top 5 to book for rotation
df_tmp = df_portfolio_features[(df_portfolio_features['Current P/L%'] > 20) ].sort_values(by = 'CumlRnk', ascending=False)
df_tmp[cols].head()

Empty DataFrame
Columns: [Symbol, Today P/L%, Current P/L%, FTT%, OTT%, FTT Amt, Current P/L, Current, FTT, Dev%_PE, RSI_14, Conviction, Spread%, CumlRnk, RRR Ind, CurrAlloc%, Gained%, Criteria, Strategy, Category]
Index: []

In [15]:
# top 5 to monitor for exit
df_tmp = df_portfolio_features[~df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])]
df_tmp = df_tmp[(df_tmp['Current P/L%'] > 0) ].sort_values(by = 'Dev%_PE', ascending=False)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
19,COALINDIA,1.41,10.61,6.38,17.67,10618.0,15966.0,166426.0,478.51,33.43,62.0,L-LC,11.56,185.0,1.50,1.22,29.24,XY25,ATH,MINING
27,FINCABLES,-3.19,13.91,82.52,107.91,138789.0,20544.0,168188.0,1641.55,2.49,57.0,M-SC,7.71,220.0,0.15,1.23,26.53,OX40N,ATH,CABLES
1,ABB,0.84,15.17,26.40,45.57,79542.0,39677.0,301296.0,7934.00,-26.00,66.0,H-MC,10.07,125.0,0.50,2.20,33.80,AR,NTT,ELECTRICAL

In [16]:
# top 5 to book for rotation from weak conviction
df_tmp = df_portfolio_features[~df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])]
df_tmp = df_tmp[~df_tmp['Criteria'].isin(['XY25','XY24','X40', 'X40N'])].sort_values(by = 'RRR Ind', ascending=False)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
1,ABB,0.84,15.17,26.40,45.57,79542.0,39677.0,301296.0,7934.00,-26.00,66.0,H-MC,10.07,125.0,0.50,2.20,33.80,AR,NTT,ELECTRICAL
27,FINCABLES,-3.19,13.91,82.52,107.91,138789.0,20544.0,168188.0,1641.55,2.49,57.0,M-SC,7.71,220.0,0.15,1.23,26.53,OX40N,ATH,CABLES
85,ZYDUSLIFE,0.53,-2.14,38.60,35.63,79164.0,-4486.0,205088.0,1286.17,-14.86,57.0,H-MC,5.04,120.0,-0.06,1.50,14.17,AR,ATH,PHARMA
40,INDIAMART,-1.67,-7.90,124.45,106.72,141369.0,-9741.0,113595.0,4810.62,-58.40,45.0,H-SC,9.17,140.0,-0.07,0.83,13.63,AR,ATH,MISC
84,WIPRO,1.20,-16.60,106.55,72.27,150578.0,-28127.0,141321.0,420.00,-24.55,37.0,M-LC,14.46,98.0,-0.19,1.03,4.06,XR,NTT,IT

In [17]:
# top 5 to accumulate based on lowest RSI_14
df_tmp = df_portfolio_features[df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])].sort_values(by = 'RSI_14', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
58,RELAXO,-0.26,-60.22,282.87,52.31,163340.0,-87416.0,57744.0,1176.00,-57.60,20.0,X-SC,18.71,92.0,-0.54,0.42,0.00,X40N,NTT,FOOTWEAR
73,TCS,-1.41,-27.26,74.02,26.57,249423.0,-126306.0,336967.0,4311.59,-38.38,22.0,X-LC,13.80,2.0,-0.51,2.46,0.00,X40,ATH,IT
12,BATAINDIA,0.65,-53.46,190.49,35.20,114083.0,-68781.0,59889.0,2096.00,-21.44,23.0,X-SC,25.47,91.0,-0.60,0.44,0.65,X40,NTT,FOOTWEAR
3,ACC,0.00,-34.03,164.99,74.81,291834.0,-91248.0,176880.0,3906.00,-53.43,24.0,X-SC,12.18,85.0,-0.31,1.29,1.62,XY24,BTT,CEMENT
53,PGHH,-0.25,-19.21,63.41,32.01,109380.0,-41024.0,172496.0,17616.87,-45.38,25.0,X-MC,11.28,57.0,-0.38,1.26,1.67,X40,ATH,FMCG

In [18]:
# top 5 to accumulate based on Spread and CumlRnk
df_tmp = df_portfolio_features[df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])]
df_tmp = df_tmp[(df_tmp['CumlRnk'] < 100)].sort_values(by = 'Spread%', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
22,DABUR,-1.23,-7.13,54.74,43.70,126107.0,-17693.0,230375.0,735.00,-15.77,36.0,X-MC,1.02,70.0,-0.14,1.68,6.84,XY24,BTT,FMCG
78,UNITDSPR,-1.27,2.05,18.34,20.77,43822.0,4798.0,238942.0,1644.00,-9.55,52.0,X-MC,1.51,64.0,0.11,1.75,8.89,X40N,NTT,BREWERIES
37,ICICIGI,0.06,0.14,19.17,19.34,38415.0,284.0,200393.0,2252.93,-15.67,48.0,X-MC,1.65,66.0,0.01,1.47,14.29,X40,ATH,INSURANCE
75,TMPV,-2.25,-23.19,77.80,36.58,212654.0,-82507.0,273334.0,600.00,-83.62,36.0,X-LC,1.87,4.0,-0.39,2.00,1.64,XY24,NTT,AUTO
59,RELIANCE,-0.36,-9.89,39.05,25.30,70716.0,-19873.0,181090.0,1952.00,-12.34,47.0,X-LC,2.43,21.0,-0.28,1.32,20.91,XY25,BTT,REFINERIES

In [19]:
# top 5 to accumulate based on lowest Gained%
df_tmp = df_portfolio_features[df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])].sort_values(by = 'Gained%', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
10,BAJAJHLDNG,-0.38,-8.35,40.99,29.22,71425.0,-15875.0,174250.0,14451.52,-15.20,32.0,X-LC,11.98,28.0,-0.22,1.27,0.00,X40,ATH,FINANCE
58,RELAXO,-0.26,-60.22,282.87,52.31,163340.0,-87416.0,57744.0,1176.00,-57.60,20.0,X-SC,18.71,92.0,-0.54,0.42,0.00,X40N,NTT,FOOTWEAR
73,TCS,-1.41,-27.26,74.02,26.57,249423.0,-126306.0,336967.0,4311.59,-38.38,22.0,X-LC,13.80,2.0,-0.51,2.46,0.00,X40,ATH,IT
13,BERGEPAINT,-0.52,-19.94,56.52,25.32,116637.0,-51385.0,206364.0,680.00,-24.23,30.0,X-MC,15.46,68.0,-0.44,1.51,0.06,XY24,NTT,PAINTS
43,INFY,-1.26,-12.91,54.15,34.24,147554.0,-40397.0,272491.0,1972.00,-31.42,26.0,X-LC,12.12,3.0,-0.27,1.99,0.30,X40,NTT,IT

In [20]:
# top 5 to accumulate based on lowest CurrAlloc%
df_tmp = df_portfolio_features[df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])].sort_values(by = 'CurrAlloc%', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
58,RELAXO,-0.26,-60.22,282.87,52.31,163340.0,-87416.0,57744.0,1176.00,-57.60,20.0,X-SC,18.71,92.0,-0.54,0.42,0.00,X40N,NTT,FOOTWEAR
12,BATAINDIA,0.65,-53.46,190.49,35.20,114083.0,-68781.0,59889.0,2096.00,-21.44,23.0,X-SC,25.47,91.0,-0.60,0.44,0.65,X40,NTT,FOOTWEAR
54,QUESS,1.92,-20.84,119.69,73.90,101179.0,-22259.0,84534.0,424.00,-57.58,44.0,X-SC,17.93,80.0,-0.22,0.62,4.28,XY24,NTT,MISC
36,HONAUT,0.20,-20.08,89.32,51.31,137664.0,-38713.0,154125.0,58357.33,-33.60,45.0,X-SC,13.61,90.0,-0.28,1.13,3.79,X40N,ATH,ELECTRICAL
2,ABBOTINDIA,-0.19,-10.23,31.52,18.07,50609.0,-18295.0,160560.0,35195.00,-23.63,46.0,X-MC,11.18,58.0,-0.36,1.17,1.79,X40,ATH,PHARMA

In [21]:
# top 5 to accumulate based on CumlRnk
df_tmp = df_portfolio_features.sort_values(by = 'CumlRnk', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
45,ITC,-0.28,-18.82,46.66,19.06,128850.0,-64019.0,276147.0,452.00,-55.52,37.0,X-LC,17.10,1.0,-0.50,2.02,0.72,X40,NTT,FMCG
73,TCS,-1.41,-27.26,74.02,26.57,249423.0,-126306.0,336967.0,4311.59,-38.38,22.0,X-LC,13.80,2.0,-0.51,2.46,0.00,X40,ATH,IT
43,INFY,-1.26,-12.91,54.15,34.24,147554.0,-40397.0,272491.0,1972.00,-31.42,26.0,X-LC,12.12,3.0,-0.27,1.99,0.30,X40,NTT,IT
75,TMPV,-2.25,-23.19,77.80,36.58,212654.0,-82507.0,273334.0,600.00,-83.62,36.0,X-LC,1.87,4.0,-0.39,2.00,1.64,XY24,NTT,AUTO
34,HCLTECH,-0.37,-11.97,40.67,23.83,86615.0,-28954.0,212970.0,1908.19,-7.36,28.0,X-LC,9.47,8.0,-0.33,1.56,2.18,X40,ATH,IT

In [22]:
# top 5 for average up
df_tmp = df_portfolio_features[(df_portfolio_features['Dev%_200'] > 5)].sort_values(by = 'CurrAlloc%', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
42,INDUSINDBK,-1.36,-34.55,103.06,32.89,52074.0,-26678.0,50528.0,1800.00,-338.10,40.0,L-MC,11.34,258.0,-0.51,0.37,39.15,XR,NTT,BANKS
67,SONACOMS,1.82,-9.86,54.31,39.09,49522.0,-9975.0,91184.0,804.02,-28.57,52.0,M-MC,10.18,193.0,-0.20,0.67,29.00,AR,ATH,AUTO
19,COALINDIA,1.41,10.61,6.38,17.67,10618.0,15966.0,166426.0,478.51,33.43,62.0,L-LC,11.56,185.0,1.50,1.22,29.24,XY25,ATH,MINING
27,FINCABLES,-3.19,13.91,82.52,107.91,138789.0,20544.0,168188.0,1641.55,2.49,57.0,M-SC,7.71,220.0,0.15,1.23,26.53,OX40N,ATH,CABLES
82,VOLTAS,1.58,15.14,26.10,45.20,57621.0,29028.0,220770.0,1856.00,31.84,49.0,X-MC,9.64,79.0,0.50,1.61,22.97,XY25,NTT,AC

In [23]:
# top 5 RSP
df_tmp = df_portfolio_features.sort_values(by = 'RSP', ascending=False)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
27,FINCABLES,-3.19,13.91,82.52,107.91,138789.0,20544.0,168188.0,1641.55,2.49,57.0,M-SC,7.71,220.0,0.15,1.23,26.53,OX40N,ATH,CABLES
31,HAPPSTMNDS,7.38,-46.32,244.35,84.85,168113.0,-59365.0,68800.0,1480.71,-36.21,67.0,H-SC,28.48,152.0,-0.35,0.50,27.41,AR,ATH,IT
11,BANDHANBNK,1.15,-11.32,116.98,92.42,288975.0,-31530.0,247029.0,400.00,111.93,63.0,H-SC,10.06,174.0,-0.11,1.81,36.08,XY24,NTT,BANKS
19,COALINDIA,1.41,10.61,6.38,17.67,10618.0,15966.0,166426.0,478.51,33.43,62.0,L-LC,11.56,185.0,1.50,1.22,29.24,XY25,ATH,MINING
1,ABB,0.84,15.17,26.40,45.57,79542.0,39677.0,301296.0,7934.00,-26.00,66.0,H-MC,10.07,125.0,0.50,2.20,33.80,AR,NTT,ELECTRICAL

In [24]:
# Top N allocation
df_tmp = df_portfolio_features.sort_values(by = 'CurrAlloc%', ascending=False)
top_n_values = [10, 25, 50]

sum_df = pd.DataFrame({
    'Top_N': top_n_values,
    'Sum_Alloc%': [df_tmp['CurrAlloc%'].head(n).sum() for n in top_n_values]
})

sum_df

   Top_N  Sum_Alloc%
0     10       20.45
1     25       45.26
2     50       77.73

In [25]:
# market-cap-wise allocation
df_tmp = df_portfolio_features[cols]
df_tmp.groupby(df_tmp['Conviction'].str[-2:])['CurrAlloc%'].sum().sort_values(ascending=False)

Conviction
SC    44.74
MC    30.42
LC    24.83
Name: CurrAlloc%, dtype: float64

In [26]:
# criteria-wise allocation
df_portfolio_features.groupby('Criteria')['CurrAlloc%'].sum().sort_values(ascending=False)

Criteria
XY24     27.33
X40      23.71
X40N     15.13
AR        9.23
XY25      8.60
XR        8.31
OX40N     6.91
SR        0.77
Name: CurrAlloc%, dtype: float64

In [27]:
# conviction-wise allocation
df_portfolio_features.groupby('Conviction')['CurrAlloc%'].sum().sort_values(ascending=False)

Conviction
X-MC    23.04
H-SC    21.78
X-LC    21.37
X-SC    12.18
M-SC    10.19
H-MC     4.99
M-MC     2.02
L-LC     1.22
H-LC     1.21
M-LC     1.03
L-SC     0.59
L-MC     0.37
Name: CurrAlloc%, dtype: float64

In [28]:
# sector-wise stats
df_tmp = df_portfolio_features.groupby('Category')[['CurrAlloc%', 'Current', 'Current P/L', 'FTT Amt']].sum().sort_values(by=['Current', 'Current P/L'], ascending=False)
df_tmp['Current P/L%'] = round(df_tmp['Current P/L'] * 100 / df_tmp['Current'], 2)
df_tmp['FTT%'] = round(df_tmp['FTT Amt'] * 100 / df_tmp['Current'], 2)
cols = ['CurrAlloc%', 'Current P/L%', 'FTT%']
df_tmp[cols].sort_values(by=['CurrAlloc%'], ascending=False)

               CurrAlloc%  Current P/L%    FTT%
Category
FMCG                15.23        -19.89   62.46
FINANCE             12.77        -22.96   73.07
IT                  11.72        -40.41  111.86
MISC                 6.99        -40.13  101.00
ELECTRICAL           6.65         -6.61   47.43
PAINTS               5.18        -39.30   63.49
INSURANCE            4.72         -5.21   41.22
PHARMA               4.15         -3.54   36.14
AUTO                 3.75        -27.83   78.54
BANKS                3.18        -23.05   97.61
AC                   2.15         -8.31   37.68
HEALTHCARE           1.99        -31.34   65.62
DURABLES             1.90        -48.69   84.86
FOOTWEAR             1.84        -75.38  145.70
TRAVEL               1.82        -79.94  170.05
BREWERIES            1.75          2.01   18.34
APPARELS             1.62        -20.91   62.15
REALTY               1.44        -12.98   31.54
CERAMICS             1.35        -67.29  118.12
REFINERIES           1.32        -10.97   39.05
CEMENT               1.29        -51.59  164.99
CABLES               1.23         12.21   82.52
MINING               1.22          9.59    6.38
JEWELLERY            1.13       -107.54  179.64
ENGINEERING          1.10        -60.55  133.98
CHEMICALS            0.95       -102.33  267.40
ENTERTAINMENT        0.76        -86.37  197.52
TEXTILES             0.42        -60.78  106.63
HOTELS               0.37       -126.07  205.81

In [29]:
# money to be made criteria-wise
df_portfolio_features.groupby('Criteria')['FTT Amt'].agg(['sum', 'count']).sort_values(by='sum', ascending=False)

                sum  count
Criteria
XY24      3859848.0     21
X40       1629662.0     15
XR        1354526.0     12
AR        1309475.0     10
X40N      1231847.0     10
OX40N      847138.0     10
XY25       440739.0      6
SR         313859.0      2

In [30]:
# money to be made conviction-wise
df_portfolio_features.groupby('Conviction')['FTT Amt'].agg(['sum', 'count']).sort_values(by='sum', ascending=False)

                  sum  count
Conviction
H-SC        3816401.0     24
X-MC        1583340.0     15
X-LC        1551803.0     12
M-SC        1523260.0     14
X-SC        1514183.0     10
H-MC         396417.0      3
L-SC         210264.0      2
M-LC         150578.0      1
M-MC         109549.0      2
H-LC          68607.0      1
L-MC          52074.0      1
L-LC          10618.0      1

In [31]:
# money to be made criteria and conviction-wise
df_portfolio_features.groupby(['Conviction', 'Criteria'])['FTT Amt'].agg(['sum', 'count']).sort_values(by='sum', ascending=False)

                           sum  count
Conviction Criteria
H-SC       XY24      1304574.0      6
           AR         955216.0      5
M-SC       XY24       899840.0      6
H-SC       XR         860911.0      7
X-SC       XY24       816147.0      4
X-LC       X40        807720.0      6
X-MC       X40        618378.0      7
           X40N       499106.0      4
X-SC       X40N       494472.0      4
H-SC       OX40N      381841.0      4
X-LC       XY24       358832.0      2
M-SC       OX40N      358405.0      5
H-SC       SR         313859.0      2
X-MC       XY24       242744.0      2
X-LC       X40N       238269.0      2
H-MC       XY24       237711.0      1
X-MC       XY25       223112.0      2
X-SC       X40        203564.0      2
M-SC       XR         187591.0      2
H-MC       AR         158706.0      2
M-LC       XR         150578.0      1
X-LC       XY25       146982.0      2
L-SC       OX40N      106892.0      1
           XR         103372.0      1
M-SC       AR          77424.0      1
H-LC       AR          68607.0      1
M-MC       XY25        60027.0      1
L-MC       XR          52074.0      1
M-MC       AR          49522.0      1
L-LC       XY25        10618.0      1

In [32]:
# notebook execution time

end_time = time.time()
execution_time = round(end_time - start_time, 0)
print(f"Notebook execution time: {execution_time} seconds")

Notebook execution time: 48.0 seconds