<a href="https://colab.research.google.com/github/ankit-rathi/Quantvesting_v2/blob/main/myStocks_Portfolio_Analysis.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
'''
!pip install pandas==2.2.2 -qq
!pip install pyxirr -qq
!pip install ta -qq
!pip install yfinance==0.2.59 -qq
'''

'\n!pip install pandas==2.2.2 -qq\n!pip install pyxirr -qq\n!pip install ta -qq\n!pip install yfinance==0.2.59 -qq\n'

In [2]:
# import libraries

import numpy as np
import pandas as pd
import datetime
import warnings
warnings.filterwarnings('ignore')
import yfinance as yfin
import ta
import matplotlib.pyplot as plt
import requests

In [3]:
# notebook start time
import time
import datetime
import pytz

start_time = time.time()

# function to print date timestamp
def print_date_time():
  tz_NY = pytz.timezone('Asia/Kolkata')
  datetime_NY = datetime.datetime.now(tz_NY)
  print("Run date time (IST):", datetime_NY.strftime("%Y-%m-%d %H:%M:%S"))

In [4]:
# function to get booked and reserved amount
def get_amt():
  # fetch the JSON data from the URL
  url = "https://raw.githubusercontent.com/ankit-rathi/Tradevesting_v1/main/data/myPortfolioAmts.json"
  response = requests.get(url)
  pf_amts = response.json()  # parse the JSON data

  # extract values from the JSON
  py_booked_amt_dm = pf_amts["py_booked_amt_dm"]
  py_booked_amt_sv = pf_amts["py_booked_amt_sv"]
  cy_booked_amt_dm = pf_amts["cy_booked_amt_dm"]
  cy_booked_amt_sv = pf_amts["cy_booked_amt_sv"]
  reserve_amt_dm = pf_amts["reserve_amt_dm"]
  reserve_amt_sv = pf_amts["reserve_amt_sv"]

  # perform calculations
  py_booked_amt = py_booked_amt_dm + py_booked_amt_sv
  cy_booked_amt = cy_booked_amt_dm + cy_booked_amt_sv
  reserve_amt = reserve_amt_dm + reserve_amt_sv
  total_booked_amt = py_booked_amt + cy_booked_amt

  return total_booked_amt, reserve_amt, cy_booked_amt, py_booked_amt

gen_output = 0

In [5]:
# function to format the amount
def format_amt(number):
    abs_number = abs(number)

    if abs_number >= 1_00_00_000:  # Crores
        formatted_amt = f"{number / 1_00_00_000:.2f} C"
    elif abs_number >= 1_00_000:  # Lakhs
        formatted_amt = f"{number / 1_00_000:.2f} L"
    elif abs_number >= 1_000:  # Thousands
        formatted_amt = f"{number / 1_000:.2f} K"
    else:
        formatted_amt = f"{number:.2f}"

    return formatted_amt

# function to set start and end date
def get_start_end_date():
  start_date = (datetime.date.today() + datetime.timedelta(days=-365)).strftime('%Y-%m-%d')
  end_date = (datetime.date.today() + datetime.timedelta(days=1)).strftime('%Y-%m-%d')
  return start_date, end_date

# function to fetch my portfolio csv
def get_mypfs_df():
  mypfs_df = pd.read_csv('https://raw.githubusercontent.com/ankit-rathi/Tradevesting_v1/main/data/myPortfolioStocks.csv')
  return mypfs_df

# function to fetch my prospects csv
def get_mypps_df():
  mypps_df = pd.read_csv('https://raw.githubusercontent.com/ankit-rathi/Tradevesting_v1/main/data/myProspectsScrips.csv')
  return mypps_df

# function to fetch screener data
def get_myscreen_df():
  myscreen_df = pd.read_csv('https://raw.githubusercontent.com/ankit-rathi/Tradevesting_v1/main/data/myScreenerDB.csv')
  return myscreen_df

# function to fetch momentum data
def get_myinvmt_df():
  myinvmt_df = pd.read_csv('https://raw.githubusercontent.com/ankit-rathi/Tradevesting_v1/main/data/myInvestments.csv')
  return myinvmt_df

# function to get the stock ids
def get_stock_ids(df_pf):
  stock_n100 = df_pf['Symbol'].unique()

  exclude = ['CADILAHC','MMTC', 'MASFIN']

  stock_ids = df_pf[~df_pf['Symbol'].isin(exclude) ]['Symbol'].unique()

  #mypf = mypf[mypf.Forecast.notnull()]
  #stock_ids = mypf['Symbol'].unique()

  #stock_ids.sort()
  return stock_ids

# get features from screener data
def get_screener_features():
  myscreen_df = get_myscreen_df()
  cols = ['Symbol', 'EPS', 'MedPE', 'ROCE%', 'ROE%', 'CapType']
  return myscreen_df[cols]

# get relative strength
def get_relative_strength(stock_list):

    # Dictionary to store stock tickers and their corresponding percentage price change
    stock_changes = {}

    # Loop through each stock and fetch its price data
    for stock in stock_list:
        try:
            # Download the stock data for the given date range
            stock_data = yfin.Ticker(stock + '.NS').history(period='1mo', interval='1d')[map(str.title, ['open', 'close', 'low', 'high', 'volume'])]

            # Calculate the percentage change for the stock
            if len(stock_data) > 0:
                start_price = stock_data['Close'].iloc[0]
                end_price = stock_data['Close'].iloc[-1]
                percent_change = round(((end_price - start_price) / start_price) * 100, 2)
                stock_changes[stock] = percent_change
            else:
                stock_changes[stock] = np.nan  # If no data is available, set to NaN

        except Exception as e:
            print(f"Error fetching data for {stock}: {e}")
            stock_changes[stock] = np.nan

    # Create a DataFrame with stock tickers and their percentage changes
    df = pd.DataFrame(list(stock_changes.items()), columns=['Symbol', 'Percent_Change'])

    # Drop any stocks with missing data (NaN values)
    df = df.dropna()

    # Calculate the percentile rank based on percentage change
    df['RSP'] = round(df['Percent_Change'].rank(pct=True) * 100, 2)
    cols = ['Symbol', 'RSP']
    df = df[cols]
    # Sort by percentile rank (optional)
    df = df.sort_values(by='RSP', ascending=False).reset_index(drop=True)

    return df

In [6]:
# function to get stock technicals
def stock_prec_dev(stock_symbol):
    #stock_symbol = 'ULTRACEMCO.NS'
    short_window = 20
    mid_window = 50
    long_window = 200
    moving_avg = 'SMA'

    start = datetime.datetime(*map(int, start_date.split('-')))
    end = datetime.datetime(*map(int, end_date.split('-')))

    stock_df = yfin.Ticker(stock_symbol + '.NS').history(period='max', interval='1d')[map(str.title, ['open', 'close', 'low', 'high', 'volume'])]

    stock_df['Max'] = round(max(stock_df['Close']),2)
    stock_df = stock_df[(stock_df.index <= end_date) & (stock_df.index >= start_date)]
    stock_df['200_SMA'] = round(stock_df['Close'].rolling(window = 200, min_periods = 1).mean(),0)
    stock_df['Dev%_200'] = round((stock_df['Close'] - stock_df['200_SMA'])*100/stock_df['200_SMA'],2)
    stock_df.dropna(axis = 0, inplace = True) # remove any null rows

    stock_df['20_SMA'] = stock_df['Close'].rolling(window=20).mean()
    stock_df['50_SMA'] = stock_df['Close'].rolling(window=50).mean()
    stock_df['Symbol'] = stock_symbol

    stock_df['Close'] = round(stock_df['Close'],2)
    stock_df['Min'] = round(min(stock_df['Close']),2)
    stock_df['RSI_14'] = ta.momentum.RSIIndicator(close=stock_df['Close'], window=14).rsi()
    stock_df['RSI_14'] = round(stock_df['RSI_14'],0)
    stock_df['Prev_Close'] = stock_df['Close'].shift(1)
    stock_df.drop(['Open', 'Low', 'High', 'Volume'], axis=1, inplace=True)
    stock_df = stock_df.tail(1)

    max_SMA = max(stock_df['20_SMA'].item(), stock_df['50_SMA'].item(), stock_df['200_SMA'].item())
    min_SMA = min(stock_df['20_SMA'].item(), stock_df['50_SMA'].item(), stock_df['200_SMA'].item())
    ABS_Spread = max_SMA - min_SMA
    stock_df['Spread%'] = round((ABS_Spread / stock_df['200_SMA'].item()) * 100,2)

    return stock_df

# function to compute stock attributes
def get_common_features(stock_ids, df_mypf):

  df_prec_dev = pd.DataFrame()
  df_tmp = get_screener_features()
  df_rs = get_relative_strength(stock_ids)

  for stock_id in stock_ids:
      tmp = stock_prec_dev(stock_id)
      tmp = tmp.reset_index()
      df_prec_dev = pd.concat([df_prec_dev, tmp], ignore_index = True)
  df_prec_dev = pd.merge(df_prec_dev, df_mypf, on= 'Symbol')
  df_prec_dev = pd.merge(df_prec_dev, df_tmp, on= 'Symbol', how='left')
  df_prec_dev = pd.merge(df_prec_dev, df_rs, on= 'Symbol', how='left')
  #print(df_prec_dev.columns)
  df_prec_dev['Curr_PE'] = round(df_prec_dev['Close']/df_prec_dev['EPS'],1)
  df_prec_dev['Dev%_PE'] = round((df_prec_dev['Curr_PE'] - df_prec_dev['MedPE'])*100/df_prec_dev['MedPE'],2)
  df_prec_dev['Conviction'] = df_prec_dev['Conviction'] + '-' + df_prec_dev['CapType']
  return df_prec_dev

# function to arrange stock features
def arrange_features(df_stocks, common_cols, diff_cols):
  df_stocks_common = df_stocks[common_cols].drop_duplicates()
  df_stocks_diff = df_stocks[diff_cols]
  df_stocks_diff['Investment'] = df_stocks_diff['AvgCost'] * df_stocks_diff['Shares']
  df_stocks_diff = df_stocks_diff.groupby(['Symbol'])[['Shares', 'Investment']].aggregate(['sum']).reset_index()
  df_stocks_diff.columns = ['Symbol', 'Shares', 'Investment']
  df_stocks_diff['AvgCost'] = round(df_stocks_diff['Investment']/df_stocks_diff['Shares'],2)
  df_stocks = pd.merge(df_stocks_diff, df_stocks_common, on='Symbol')
  return df_stocks

# plot fact distribution across dimension
def plot_pie_chart(df, dimension, fact):
  # grouping the data by category and calculating the sum of fact for each type
  grouped_data = df.groupby(dimension)[fact].sum()

  # sorting the grouped data in descending order
  grouped_data = grouped_data.sort_values(ascending=False)

  # creating a pie chart
  grouped_data.plot.pie(autopct='%1.1f%%', startangle=90, figsize=(6, 6))

  # adding a title and displaying the plot
  plt.title(f'{dimension} {fact} Distribution')
  plt.ylabel('')  # To hide the y-label
  plt.show()

In [7]:
# function to get portfolio features

def get_portfolio_features(df_common_features):

  print_date_time()
  print('-------------------')

  #df_common_features["Target"] = df_common_features["Target"].fillna(df_common_features["Max"])
  df_common_features['NTT'] = np.where(df_common_features['Strategy']== 'NTT', df_common_features["Target"], df_common_features['Max'])
  df_common_features['LTT'] = np.where(df_common_features['Strategy']== 'BTT', df_common_features["Target"], df_common_features['Max'])
  df_common_features['BOL'] = df_common_features['Min']

  tmp_df = df_common_features[df_common_features['Symbol'].isin(mypf_df[mypf_df['InPortfolio'] != 'NA'].Symbol.values)]
  print('qualified stocks: '+str(len(tmp_df['Symbol'].unique())))
  tmp_df1 = tmp_df[tmp_df['LatestQtr'] == 1]
  print('with latest results: '+str(len(tmp_df1['Symbol'].unique())))
  tmp_df1 = tmp_df1[tmp_df1['StarStock'] == 1]
  print('still star stocks: '+str(len(tmp_df1['Symbol'].unique())))
  tmp_df['Investment'] = tmp_df['AvgCost'] * tmp_df['Shares']
  tmp_df['Current'] = round(tmp_df['Close'] * tmp_df['Shares'],0)
  tmp_df['Previous'] = tmp_df['Prev_Close'] * tmp_df['Shares']
  tmp_df['EstimatedST'] = tmp_df['NTT'] * tmp_df['Shares']
  tmp_df['EstimatedLT'] = tmp_df['LTT'] * tmp_df['Shares']
  tmp_df['Current P/L'] = round((tmp_df['Current'] - tmp_df['Investment']),0)
  tmp_df['Today P/L%'] = round((tmp_df['Current'] - tmp_df['Previous'])*100/tmp_df['Previous'],2)
  tmp_df['Current P/L%'] = round((tmp_df['Current'] - tmp_df['Investment'])*100/tmp_df['Investment'],2)
  tmp_df['EstimatedST P/L%'] = round((tmp_df['EstimatedST'] - tmp_df['Investment'])*100/tmp_df['Investment'],2)
  tmp_df['EstimatedLT P/L%'] = round((tmp_df['EstimatedLT'] - tmp_df['Investment'])*100/tmp_df['Investment'],2)
  tmp_df['NTT%'] = round((tmp_df['NTT'] - tmp_df['Close'])*100/tmp_df['Close'],2)
  tmp_df['LTT%'] = round((tmp_df['LTT'] - tmp_df['Close'])*100/tmp_df['Close'],2)
  tmp_df['Gained%'] = round((tmp_df['Close'] - tmp_df['BOL'])*100/tmp_df['BOL'],2)
  investment = round(sum(tmp_df['AvgCost']*tmp_df['Shares']),0)
  current = round(sum(tmp_df['Close']*tmp_df['Shares']),0)
  tmp_df['InitAlloc%'] = round(tmp_df['Investment']*100/investment,2)
  tmp_df['CurrAlloc%'] = round(tmp_df['Current']*100/current,2)
  tmp_df['FTT'] = tmp_df['LTT']
  tmp_df.loc[tmp_df['Strategy'] == 'NTT', 'FTT'] = tmp_df['NTT']
  tmp_df['FTT%'] = tmp_df['LTT%']
  tmp_df.loc[tmp_df['Strategy'] == 'NTT', 'FTT%'] = tmp_df['NTT%']
  tmp_df['FTT Amt'] = round(tmp_df['FTT%'] * tmp_df['Current']/100,0)
  tmp_df['OTT%'] = round((tmp_df['FTT'] - tmp_df['AvgCost'])*100/tmp_df['AvgCost'],2)
  tmp_df['RRR Ind'] = round(tmp_df['Current P/L']/tmp_df['FTT Amt'],2)
  tmp_df['Risk Ind'] = round(tmp_df['Current P/L%']*tmp_df['CurrAlloc%'],0)

  return tmp_df

# function to print portfolio features
def print_portfolio_stats(df_portfolio_features, myinvmt_df):
  from pyxirr import xirr

  total_booked_amt, reserve_amt, cy_booked_amt, py_booked_amt = get_amt()

  dates = myinvmt_df['Date'].values
  dates = np.append(dates, datetime.date.today().strftime('%d-%b-%y'))
  investment = myinvmt_df['Investment'].values
  dates= pd.to_datetime(dates)

  current = round(sum(df_portfolio_features['Close']*df_portfolio_features['Shares']),0) + reserve_amt
  investment_xirr = np.append(investment, current)
  cagr = round(xirr(pd.DataFrame({"dates": dates, "amounts": investment_xirr}))*100,2)

  investment = -sum(investment)
  invested = round(sum(df_portfolio_features['AvgCost']*df_portfolio_features['Shares']),0) + reserve_amt
  previous = round(sum(df_portfolio_features['Prev_Close']*df_portfolio_features['Shares']),0) + reserve_amt
  cy_invested = investment + py_booked_amt

  today_pnl_amount = current-previous
  today_pnl_percentage = round((current-previous)*100/previous,2)

  curr_pnl_amount = current-invested
  curr_pnl_percentage = round((curr_pnl_amount)*100/(cy_invested),2)

  cy_pnl_amount = cy_booked_amt + curr_pnl_amount
  cy_pnl_percentage = round((cy_pnl_amount)*100/cy_invested,2)

  overall_pnl_amount = total_booked_amt + curr_pnl_amount
  overall_pnl_percentage = round((overall_pnl_amount)*100/investment,2)

  estimate_st = round(sum(df_portfolio_features['FTT']*df_portfolio_features['Shares']),0)  + reserve_amt
  est_st_pnl_amount = estimate_st-current
  est_st_pnl_percentage = round((est_st_pnl_amount)*100/current,2)

  estimate_lt = round(sum(df_portfolio_features['LTT']*df_portfolio_features['Shares']),0)  + reserve_amt
  est_lt_pnl_amount = estimate_lt-current
  est_lt_pnl_percentage = round((est_lt_pnl_amount)*100/current,2)

  total_profit = round(sum(df_portfolio_features[df_portfolio_features['Current P/L%'] > 0]['Current']) - sum(df_portfolio_features[df_portfolio_features['Current P/L%'] > 0]['Investment']),0)
  total_loss = round(sum(df_portfolio_features[df_portfolio_features['Current P/L%'] < 0]['Current']) - sum(df_portfolio_features[df_portfolio_features['Current P/L%'] < 0]['Investment']),0)

  cy_booked_percentage = round((cy_booked_amt)*100/current,2)
  py_booked_percentage = round((py_booked_amt)*100/investment,2)
  total_booked_percentage = round((total_booked_amt)*100/investment,2)

  print('-------------------')
  print('Initial Investment: ', format_amt(investment))
  print('CY Investment: ', format_amt(cy_invested))
  print('Reserve: ', format_amt(reserve_amt))
  print('Current: ',  format_amt(current))
  print('-------------------')
  print('Today PnL: '+ '{} ({}%)'.format(format_amt(today_pnl_amount), today_pnl_percentage))
  print('Current PnL: '+ '{} ({}%)'.format(format_amt(curr_pnl_amount), curr_pnl_percentage))
  print('CY Booked + Current PnL: '+ '{} ({}%)'.format(format_amt(cy_pnl_amount), cy_pnl_percentage))
  print('-------------------')
  print('Total profit: ', format_amt(total_profit))
  print('Total loss: ', format_amt(total_loss))
  print('-------------------')
  print('Total Booked + Current PnL: '+ '{} ({}%)'.format(format_amt(overall_pnl_amount), overall_pnl_percentage))
  print('Total Booked PnL: '+ '{} ({}%)'.format(format_amt(total_booked_amt), total_booked_percentage))
  print('Curr Year Booked PnL: '+ '{} ({}%)'.format(format_amt(cy_booked_amt), cy_booked_percentage))
  print('Prev Year Booked PnL: '+ '{} ({}%)'.format(format_amt(py_booked_amt), py_booked_percentage))
  print('===================')
  print('Est FTT: ',  format_amt(estimate_st))
  print('Est FTT PnL: '+ '{} ({}%)'.format(format_amt(est_st_pnl_amount), est_st_pnl_percentage))

  print('===================')
  print('Deployed: ', format_amt(investment))

  print('Current: ', format_amt(current))

  print('CAGR/XIRR %: '+'{}%'.format(cagr))

In [8]:
# get start and end date
start_date, end_date = get_start_end_date()

# get portfolio and prospects data
mypfs_df = get_mypfs_df()
mypps_df = get_mypps_df()
myinvmt_df = get_myinvmt_df()

# merge above datasets
mypf_df = pd.merge(mypfs_df, mypps_df, on="Symbol")

# seggregate dm and sv portfolio
dm_pf = mypf_df[mypf_df['InPortfolio'] == 'DM']
sv_pf = mypf_df[mypf_df['InPortfolio'] == 'SV']

# build portfolio stock dataframe
dm_stocks = get_stock_ids(dm_pf)
sv_stocks = get_stock_ids(sv_pf)
df_stocks = pd.concat([dm_pf,sv_pf], ignore_index = True)

# arrange common and diff stock features
common_cols = ['Symbol', 'Target', 'Criteria', 'Strategy', 'CumlRnk', 'LatestQtr', 'StarStock', 'Conviction', 'Category', 'InFolio', 'XIRR', 'MBQ']
diff_cols = ['Symbol', 'AvgCost', 'Shares']
df_stocks = arrange_features(df_stocks, common_cols, diff_cols)

# get common features
stock_ids = df_stocks['Symbol'].values
df_common_features = get_common_features(stock_ids, df_stocks)

df_common_features.reset_index(drop=True, inplace=True)
df_common_features.drop(['Date'], axis=1, inplace=True)
# get and print portfolio features
df_portfolio_features = get_portfolio_features(df_common_features)

print_portfolio_stats(df_portfolio_features, myinvmt_df)

df = df_portfolio_features
#plot_pie_chart(df, 'CapType', 'Current')
list_ox40n = list(df[df['MBQ'].str.contains('OX40N', na=False)]['Symbol'].values)

Run date time (IST): 2026-08-04 13:19:09
-------------------
qualified stocks: 90
with latest results: 31
still star stocks: 20

-------------------
Initial Investment:  1.40 C
CY Investment:  1.82 C
Reserve:  6.53 L
Current:  1.55 C
-------------------
Today PnL: 1.53 L (0.99%)
Current PnL: -29.43 L (-16.14%)
CY Booked + Current PnL: -25.79 L (-14.14%)
-------------------
Total profit:  4.41 L
Total loss:  -33.84 L
-------------------
Total Booked + Current PnL: 17.08 L (12.24%)
Total Booked PnL: 46.51 L (33.34%)
Curr Year Booked PnL: 3.64 L (2.34%)
Prev Year Booked PnL: 42.87 L (30.73%)
===================
Est FTT:  2.55 C
Est FTT PnL: 99.24 L (63.91%)
===================
Deployed:  1.40 C
Current:  1.55 C
CAGR/XIRR %: 4.75%

In [9]:
# top 5 near their targets
cols = ['Symbol', 'Today P/L%', 'Current P/L%', 'FTT%', 'OTT%', 'FTT Amt', 'Current P/L', 'Current', 'FTT', 'Dev%_PE', 'RSI_14','Conviction', 'Spread%',  'CumlRnk', 'RRR Ind', 'CurrAlloc%', 'Gained%', 'Criteria', 'Strategy', 'Category']
df_tmp = df_portfolio_features[~df_portfolio_features['Symbol'].isin(['ENRIN','BLUSPRING','DIGITIDE'])]
df_tmp = df_tmp.sort_values(by = 'FTT Amt', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
58,PIDILITIND,0.57,16.16,1.17,17.52,1918.0,22810.0,163920.0,1658.32,-18.59,66.0,X-LC,8.46,5.0,11.89,1.10,29.63,X40,ATH,CHEMICALS
71,SONACOMS,2.58,36.54,1.58,38.69,2182.0,36960.0,138119.0,801.69,8.16,83.0,M-MC,29.63,193.0,16.94,0.93,95.96,AR,ATH,AUTO
55,MEDANTA,1.45,22.92,3.42,27.12,7420.0,40455.0,216972.0,1486.00,19.21,70.0,X-SC,13.51,87.0,5.45,1.46,49.51,XY24,NTT,HEALTHCARE
52,M&M,0.03,10.31,10.69,22.10,16353.0,14292.0,152973.0,3762.88,-6.43,67.0,X-LC,6.70,25.0,0.87,1.03,17.19,X40N,ATH,AUTO
81,TTKPRESTIG,-1.57,-17.91,21.93,0.09,18142.0,-18051.0,82726.0,770.00,92.10,50.0,M-SC,13.23,250.0,-0.99,0.56,48.90,OX40N,NTT,DURABLES

In [10]:
# top 5 today
df_tmp = df_portfolio_features.sort_values(by = 'Today P/L%', ascending=False)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
18,COFFEEDAY,10.23,-43.13,137.88,35.27,89029.0,-48979.0,64570.0,80.00,-55.73,63.0,L-SC,5.04,266.0,-0.55,0.43,59.23,XR,NTT,HOTELS
69,SIEMENS,9.65,7.79,15.87,24.90,31835.0,14505.0,200600.0,4648.66,68.58,76.0,H-LC,8.91,51.0,0.46,1.35,41.53,AR,ATH,ELECTRICAL
5,ATULAUTO,9.53,-2.63,49.50,45.57,95014.0,-5185.0,191947.0,844.00,4175.68,77.0,M-SC,6.08,248.0,-0.05,1.29,47.71,XY24,NTT,AUTO
12,BOSCH-HCIL,9.27,-37.25,59.36,-0.01,47602.0,-47613.0,80192.0,2282.00,16313.04,67.0,M-SC,6.47,231.0,-1.00,0.54,36.50,OX40N,BTT,AC
84,VALIANTORG,7.87,-40.36,191.99,74.15,187344.0,-66025.0,97580.0,838.00,-275.30,62.0,H-SC,4.24,145.0,-0.35,0.66,45.21,XR,NTT,CHEMICALS

In [11]:
# bottom 5 today
df_tmp = df_portfolio_features.sort_values(by = 'Today P/L%', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
20,DABUR,-3.83,-19.88,79.36,43.70,157730.0,-49315.0,198753.0,735.00,-27.23,37.0,X-MC,8.84,70.0,-0.31,1.34,1.14,XY24,BTT,FMCG
37,HONAUT,-3.21,-0.86,52.20,50.88,99793.0,-1663.0,191175.0,58192.80,-17.59,51.0,X-SC,13.80,90.0,-0.02,1.29,45.65,X40N,ATH,ELECTRICAL
35,HDFCLIFE,-3.02,-13.00,52.54,32.71,68474.0,-19472.0,130328.0,811.41,-32.03,33.0,X-LC,16.00,31.0,-0.28,0.88,0.00,X40,ATH,INSURANCE
66,ROUTE,-3.01,-59.56,312.83,66.94,168328.0,-79258.0,53808.0,2199.37,-67.37,45.0,H-SC,6.98,141.0,-0.47,0.36,29.13,SR,ATH,IT
19,COLPAL,-2.89,-23.13,81.94,39.86,165888.0,-60915.0,202450.0,3683.41,-6.97,44.0,X-MC,1.76,62.0,-0.37,1.36,14.52,XY25,ATH,FMCG

In [12]:
# top 5 to exit based on CumlRnk
df_tmp = df_portfolio_features[~df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])]
df_tmp = df_tmp[(df_tmp['Current P/L%'] > -1) & (df_tmp['Current P/L%'] < 1)].sort_values(by = 'CumlRnk', ascending=False)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
62,RECLTD,-0.84,0.11,20.61,20.74,41919.0,220.0,203390.0,446.0,9.37,63.0,M-MC,2.45,191.0,0.01,1.37,22.6,XY25,NTT,FINANCE

In [13]:
# OX40N stocks to exit
df_tmp = df_portfolio_features[(df_portfolio_features['Symbol'].isin(list_ox40n))].sort_values(by = 'Current P/L%', ascending=False)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
25,FINCABLES,2.42,26.21,64.73,107.91,120622.0,38702.0,186346.0,1641.55,13.65,43.0,M-SC,19.25,220.0,0.32,1.25,40.19,OX40N,ATH,CABLES
70,SIS,1.06,-1.53,23.15,21.26,25310.0,-1701.0,109331.0,528.00,2609.33,49.0,H-SC,23.64,168.0,-0.07,0.74,62.56,OX40N,NTT,MISC
16,CERA,3.40,-17.30,49.80,23.89,72447.0,-30428.0,145475.0,9475.00,-20.29,57.0,H-SC,13.59,153.0,-0.42,0.98,41.41,OX40N,NTT,CERAMICS
81,TTKPRESTIG,-1.57,-17.91,21.93,0.09,18142.0,-18051.0,82726.0,770.00,92.10,50.0,M-SC,13.23,250.0,-0.99,0.56,48.90,OX40N,NTT,DURABLES
67,SFL,3.99,-20.57,59.43,26.63,123775.0,-53948.0,208270.0,1287.00,57.71,66.0,M-SC,25.60,242.0,-0.44,1.40,73.82,XY24,NTT,MISC

In [14]:
# top 5 to book for rotation
df_tmp = df_portfolio_features[(df_portfolio_features['Current P/L%'] > 20) ].sort_values(by = 'CumlRnk', ascending=False)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
25,FINCABLES,2.42,26.21,64.73,107.91,120622.0,38702.0,186346.0,1641.55,13.65,43.0,M-SC,19.25,220.0,0.32,1.25,40.19,OX40N,ATH,CABLES
71,SONACOMS,2.58,36.54,1.58,38.69,2182.0,36960.0,138119.0,801.69,8.16,83.0,M-MC,29.63,193.0,16.94,0.93,95.96,AR,ATH,AUTO
55,MEDANTA,1.45,22.92,3.42,27.12,7420.0,40455.0,216972.0,1486.00,19.21,70.0,X-SC,13.51,87.0,5.45,1.46,49.51,XY24,NTT,HEALTHCARE
59,QUESS,-1.73,34.03,29.74,73.90,42569.0,36345.0,143138.0,424.00,-27.82,75.0,X-SC,37.60,80.0,0.85,0.96,95.13,XY24,NTT,MISC

In [15]:
# top 5 to monitor for exit
df_tmp = df_portfolio_features[~df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])]
df_tmp = df_tmp[(df_tmp['Current P/L%'] > 0) ].sort_values(by = 'Dev%_PE', ascending=False)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
72,STARHEALTH,-1.28,14.81,28.27,47.26,91243.0,41632.0,322755.0,761.00,81.27,54.0,H-SC,18.70,173.0,0.46,2.17,39.55,XY24,NTT,INSURANCE
25,FINCABLES,2.42,26.21,64.73,107.91,120622.0,38702.0,186346.0,1641.55,13.65,43.0,M-SC,19.25,220.0,0.32,1.25,40.19,OX40N,ATH,CABLES
62,RECLTD,-0.84,0.11,20.61,20.74,41919.0,220.0,203390.0,446.00,9.37,63.0,M-MC,2.45,191.0,0.01,1.37,22.60,XY25,NTT,FINANCE
71,SONACOMS,2.58,36.54,1.58,38.69,2182.0,36960.0,138119.0,801.69,8.16,83.0,M-MC,29.63,193.0,16.94,0.93,95.96,AR,ATH,AUTO
89,ZYDUSLIFE,0.40,18.06,14.77,35.51,36546.0,37858.0,247432.0,1285.01,2.70,51.0,H-MC,16.73,120.0,1.04,1.66,30.21,AR,ATH,PHARMA

In [16]:
# top 5 to book for rotation from weak conviction
df_tmp = df_portfolio_features[~df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])]
df_tmp = df_tmp[~df_tmp['Criteria'].isin(['XY25','XY24','X40', 'X40N'])].sort_values(by = 'RRR Ind', ascending=False)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
71,SONACOMS,2.58,36.54,1.58,38.69,2182.0,36960.0,138119.0,801.69,8.16,83.0,M-MC,29.63,193.0,16.94,0.93,95.96,AR,ATH,AUTO
89,ZYDUSLIFE,0.40,18.06,14.77,35.51,36546.0,37858.0,247432.0,1285.01,2.70,51.0,H-MC,16.73,120.0,1.04,1.66,30.21,AR,ATH,PHARMA
25,FINCABLES,2.42,26.21,64.73,107.91,120622.0,38702.0,186346.0,1641.55,13.65,43.0,M-SC,19.25,220.0,0.32,1.25,40.19,OX40N,ATH,CABLES
70,SIS,1.06,-1.53,23.15,21.26,25310.0,-1701.0,109331.0,528.00,2609.33,49.0,H-SC,23.64,168.0,-0.07,0.74,62.56,OX40N,NTT,MISC
54,MASFIN,-1.75,-3.89,26.49,21.57,24946.0,-3810.0,94170.0,397.04,-17.34,48.0,H-SC,1.74,167.0,-0.15,0.63,12.25,XR,ATH,FINANCE

In [17]:
# top 5 to accumulate based on lowest RSI_14
df_tmp = df_portfolio_features[df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])].sort_values(by = 'RSI_14', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
35,HDFCLIFE,-3.02,-13.00,52.54,32.71,68474.0,-19472.0,130328.0,811.41,-32.03,33.0,X-LC,16.00,31.0,-0.28,0.88,0.00,X40,ATH,INSURANCE
85,VBL,0.19,-10.48,51.06,35.22,144362.0,-33112.0,282730.0,669.42,-21.06,36.0,X-LC,7.67,13.0,-0.23,1.90,16.33,X40N,ATH,FMCG
34,HDFCBANK,-1.19,-11.56,45.15,28.37,93790.0,-27156.0,207729.0,1073.00,-24.98,37.0,X-LC,10.13,26.0,-0.29,1.40,2.72,X40,BTT,BANKS
20,DABUR,-3.83,-19.88,79.36,43.70,157730.0,-49315.0,198753.0,735.00,-27.23,37.0,X-MC,8.84,70.0,-0.31,1.34,1.14,XY24,BTT,FMCG
39,ICICIGI,-0.12,-13.34,37.20,18.89,64507.0,-26704.0,173405.0,2244.41,-27.19,40.0,X-MC,8.23,66.0,-0.41,1.17,3.31,X40,ATH,INSURANCE

In [18]:
# top 5 to accumulate based on Spread and CumlRnk
df_tmp = df_portfolio_features[df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])]
df_tmp = df_tmp[(df_tmp['CumlRnk'] < 100)].sort_values(by = 'Spread%', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
19,COLPAL,-2.89,-23.13,81.94,39.86,165888.0,-60915.0,202450.0,3683.41,-6.97,44.0,X-MC,1.76,62.0,-0.37,1.36,14.52,XY25,ATH,FMCG
11,BERGEPAINT,3.33,-0.72,26.23,25.32,67118.0,-1866.0,255883.0,680.00,-6.11,65.0,X-MC,1.83,68.0,-0.03,1.72,33.18,XY24,NTT,PAINTS
8,BAJAJHLDNG,4.51,2.51,24.50,27.63,47752.0,4780.0,194905.0,14274.15,-5.41,72.0,X-LC,2.24,28.0,0.10,1.31,32.72,X40,ATH,FINANCE
23,DMART,3.25,-3.85,34.79,29.60,83496.0,-9600.0,240000.0,5391.45,-18.89,48.0,X-LC,2.88,14.0,-0.11,1.61,9.70,X40N,ATH,FMCG
17,CIPLA,-1.00,18.08,13.00,33.43,23511.0,27693.0,180854.0,1648.14,-8.67,57.0,X-LC,2.99,18.0,1.18,1.22,23.46,X40N,ATH,PHARMA

In [19]:
# top 5 to accumulate based on lowest Gained%
df_tmp = df_portfolio_features[df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])].sort_values(by = 'Gained%', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
35,HDFCLIFE,-3.02,-13.00,52.54,32.71,68474.0,-19472.0,130328.0,811.41,-32.03,33.0,X-LC,16.00,31.0,-0.28,0.88,0.00,X40,ATH,INSURANCE
20,DABUR,-3.83,-19.88,79.36,43.70,157730.0,-49315.0,198753.0,735.00,-27.23,37.0,X-MC,8.84,70.0,-0.31,1.34,1.14,XY24,BTT,FMCG
57,PGHH,2.59,-34.83,102.57,32.01,142720.0,-74376.0,139144.0,17616.87,-55.98,42.0,X-MC,19.23,57.0,-0.52,0.94,2.59,X40,ATH,FMCG
64,RELIANCE,-1.15,-17.01,50.99,25.30,85037.0,-34192.0,166771.0,1952.00,-19.26,49.0,X-LC,7.89,21.0,-0.40,1.12,2.70,XY25,BTT,REFINERIES
34,HDFCBANK,-1.19,-11.56,45.15,28.37,93790.0,-27156.0,207729.0,1073.00,-24.98,37.0,X-LC,10.13,26.0,-0.29,1.40,2.72,X40,BTT,BANKS

In [20]:
# top 5 to accumulate based on lowest CurrAlloc%
df_tmp = df_portfolio_features[df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])].sort_values(by = 'CurrAlloc%', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
10,BATAINDIA,2.62,-53.92,193.39,35.20,114671.0,-69375.0,59295.0,2096.00,-22.31,62.0,X-SC,15.67,91.0,-0.60,0.40,19.13,X40,NTT,FOOTWEAR
63,RELAXO,0.01,-47.13,188.09,52.31,144344.0,-68418.0,76742.0,1176.00,-43.76,56.0,X-SC,9.58,92.0,-0.47,0.52,71.58,X40N,NTT,FOOTWEAR
35,HDFCLIFE,-3.02,-13.00,52.54,32.71,68474.0,-19472.0,130328.0,811.41,-32.03,33.0,X-LC,16.00,31.0,-0.28,0.88,0.00,X40,ATH,INSURANCE
57,PGHH,2.59,-34.83,102.57,32.01,142720.0,-74376.0,139144.0,17616.87,-55.98,42.0,X-MC,19.23,57.0,-0.52,0.94,2.59,X40,ATH,FMCG
28,GODREJCP,-0.05,-4.25,37.31,31.47,53091.0,-6317.0,142297.0,1469.04,0.70,54.0,X-LC,5.48,32.0,-0.12,0.96,9.18,X40N,ATH,FMCG

In [21]:
# top 5 to accumulate based on CumlRnk
df_tmp = df_portfolio_features.sort_values(by = 'CumlRnk', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
47,ITC,2.19,-24.36,57.41,19.06,147708.0,-82880.0,257286.0,452.00,-58.35,55.0,X-LC,12.36,1.0,-0.56,1.73,4.21,X40,NTT,FMCG
77,TCS,3.74,-27.96,72.40,24.20,241631.0,-129529.0,333744.0,4230.71,-39.04,68.0,X-LC,16.47,2.0,-0.54,2.24,24.46,X40,ATH,IT
45,INFY,2.53,-21.12,70.19,34.24,173231.0,-66085.0,246803.0,1972.00,-37.95,62.0,X-LC,17.69,3.0,-0.38,1.66,17.60,X40,NTT,IT
79,TMPV,1.93,-21.17,73.26,36.58,205496.0,-75338.0,280503.0,600.00,-83.62,56.0,X-LC,6.44,4.0,-0.37,1.89,17.89,XY24,NTT,AUTO
58,PIDILITIND,0.57,16.16,1.17,17.52,1918.0,22810.0,163920.0,1658.32,-18.59,66.0,X-LC,8.46,5.0,11.89,1.10,29.63,X40,ATH,CHEMICALS

In [22]:
# top 5 for average up
df_tmp = df_portfolio_features[(df_portfolio_features['Dev%_200'] > 5)].sort_values(by = 'CurrAlloc%', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
44,INDUSINDBK,0.73,-24.78,76.68,32.89,44530.0,-19134.0,58072.0,1800.00,-373.11,56.0,L-MC,14.58,258.0,-0.43,0.39,43.17,XR,NTT,BANKS
18,COFFEEDAY,10.23,-43.13,137.88,35.27,89029.0,-48979.0,64570.0,80.00,-55.73,63.0,L-SC,5.04,266.0,-0.55,0.43,59.23,XR,NTT,HOTELS
63,RELAXO,0.01,-47.13,188.09,52.31,144344.0,-68418.0,76742.0,1176.00,-43.76,56.0,X-SC,9.58,92.0,-0.47,0.52,71.58,X40N,NTT,FOOTWEAR
3,ALKYLAMINE,2.69,-21.84,146.34,92.54,115483.0,-22049.0,78914.0,4520.85,-16.24,52.0,H-SC,12.95,142.0,-0.19,0.53,49.85,SR,ATH,CHEMICALS
81,TTKPRESTIG,-1.57,-17.91,21.93,0.09,18142.0,-18051.0,82726.0,770.00,92.10,50.0,M-SC,13.23,250.0,-0.99,0.56,48.90,OX40N,NTT,DURABLES

In [23]:
# top 5 RSP
df_tmp = df_portfolio_features.sort_values(by = 'RSP', ascending=False)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
33,HCLTECH,0.23,-12.39,37.29,20.28,79036.0,-29974.0,211950.0,1853.42,-7.78,75.0,X-LC,14.88,8.0,-0.38,1.42,31.87,X40,ATH,IT
77,TCS,3.74,-27.96,72.40,24.20,241631.0,-129529.0,333744.0,4230.71,-39.04,68.0,X-LC,16.47,2.0,-0.54,2.24,24.46,X40,ATH,IT
71,SONACOMS,2.58,36.54,1.58,38.69,2182.0,36960.0,138119.0,801.69,8.16,83.0,M-MC,29.63,193.0,16.94,0.93,95.96,AR,ATH,AUTO
13,BSOFT,5.24,-42.30,157.53,48.59,127842.0,-59499.0,81154.0,819.60,-26.17,63.0,H-SC,19.74,172.0,-0.47,0.55,18.64,XR,ATH,IT
83,VAIBHAVGBL,0.80,-17.15,94.04,60.77,142409.0,-31341.0,151434.0,521.00,74.66,63.0,H-SC,11.47,160.0,-0.22,1.02,54.07,XR,NTT,JEWELLERY

In [24]:
# Top N allocation
df_tmp = df_portfolio_features.sort_values(by = 'CurrAlloc%', ascending=False)
top_n_values = [10, 25, 50]

sum_df = pd.DataFrame({
    'Top_N': top_n_values,
    'Sum_Alloc%': [df_tmp['CurrAlloc%'].head(n).sum() for n in top_n_values]
})

sum_df

   Top_N  Sum_Alloc%
0     10       19.15
1     25       42.69
2     50       73.75

In [25]:
# market-cap-wise allocation
df_tmp = df_portfolio_features[cols]
df_tmp.groupby(df_tmp['Conviction'].str[-2:])['CurrAlloc%'].sum().sort_values(ascending=False)

Conviction
SC    42.37
LC    32.01
MC    25.68
Name: CurrAlloc%, dtype: float64

In [26]:
# criteria-wise allocation
df_portfolio_features.groupby('Criteria')['CurrAlloc%'].sum().sort_values(ascending=False)

Criteria
XY24     26.18
X40      26.02
X40N     16.54
XR        9.26
AR        7.39
OX40N     7.19
XY25      6.59
SR        0.89
Name: CurrAlloc%, dtype: float64

In [27]:
# conviction-wise allocation
df_portfolio_features.groupby('Conviction')['CurrAlloc%'].sum().sort_values(ascending=False)

Conviction
X-LC    29.78
H-SC    20.66
X-MC    20.21
X-SC    10.66
M-SC    10.47
H-MC     2.78
M-MC     2.30
H-LC     1.35
M-LC     0.88
L-SC     0.58
L-MC     0.39
Name: CurrAlloc%, dtype: float64

In [28]:
# sector-wise stats
df_tmp = df_portfolio_features.groupby('Category')[['CurrAlloc%', 'Current', 'Current P/L', 'FTT Amt']].sum().sort_values(by=['Current', 'Current P/L'], ascending=False)
df_tmp['Current P/L%'] = round(df_tmp['Current P/L'] * 100 / df_tmp['Current'], 2)
df_tmp['FTT%'] = round(df_tmp['FTT Amt'] * 100 / df_tmp['Current'], 2)
cols = ['CurrAlloc%', 'Current P/L%', 'FTT%']
df_tmp[cols].sort_values(by=['CurrAlloc%'], ascending=False)

               CurrAlloc%  Current P/L%    FTT%
Category
FMCG                14.36        -23.94   67.39
IT                  11.04        -37.15  104.93
FINANCE              9.08        -16.10   64.67
MISC                 7.70        -17.14   67.40
AUTO                 7.42          0.61   36.46
PAINTS               5.73        -15.62   35.35
BANKS                5.44        -12.22   64.08
PHARMA               5.42          8.20   19.59
INSURANCE            5.33         -4.62   39.91
ELECTRICAL           4.45         -6.95   44.40
CHEMICALS            2.29        -19.17   89.52
HEALTHCARE           2.23         -7.88   36.04
APPARELS             1.89          4.35   27.77
AC                   1.88        -14.34   45.35
BREWERIES            1.77         11.17    7.28
FOOTWEAR             1.77        -68.36  135.87
DURABLES             1.67        -56.86   95.02
TRAVEL               1.55        -93.66  190.62
CERAMICS             1.48        -39.63   82.05
ENGINEERING          1.31        -24.70   81.73
CABLES               1.25         20.77   64.73
JEWELLERY            1.17        -83.98  147.90
REFINERIES           1.12        -20.50   50.99
CEMENT               1.12        -60.92  181.31
ENTERTAINMENT        0.74        -76.29  181.44
HOTELS               0.43        -75.85  137.88
TEXTILES             0.42        -48.92   91.39

In [29]:
# money to be made criteria-wise
df_portfolio_features.groupby('Criteria')['FTT Amt'].agg(['sum', 'count']).sort_values(by='sum', ascending=False)

                sum  count
Criteria
XY24      3284456.0     20
X40       1794090.0     19
XR        1302507.0     13
AR        1075324.0      9
X40N      1003414.0     12
OX40N      724072.0     10
XY25       455951.0      5
SR         283811.0      2

In [30]:
# money to be made conviction-wise
df_portfolio_features.groupby('Conviction')['FTT Amt'].agg(['sum', 'count']).sort_values(by='sum', ascending=False)

                  sum  count
Conviction
H-SC        3281536.0     23
X-LC        1843532.0     21
X-MC        1449575.0     14
M-SC        1361186.0     14
X-SC        1218431.0      9
H-MC         283851.0      2
L-SC         203827.0      2
M-LC         161221.0      1
L-MC          44530.0      1
M-MC          44101.0      2
H-LC          31835.0      1

In [31]:
# money to be made criteria and conviction-wise
df_portfolio_features.groupby(['Conviction', 'Criteria'])['FTT Amt'].agg(['sum', 'count']).sort_values(by='sum', ascending=False)

                          sum  count
Conviction Criteria
H-SC       XY24      985730.0      5
X-LC       X40       943133.0     10
H-SC       AR        928760.0      5
M-SC       XY24      786052.0      6
H-SC       XR        782894.0      7
X-SC       XY24      712508.0      4
X-MC       X40       636654.0      7
X-LC       X40N      368741.0      6
X-MC       X40N      343053.0      3
X-LC       XY24      328013.0      2
M-SC       OX40N     308933.0      5
H-SC       OX40N     300341.0      4
X-SC       X40N      291620.0      3
H-SC       SR        283811.0      2
H-MC       XY24      247305.0      1
X-MC       XY25      245020.0      2
           XY24      224848.0      2
X-SC       X40       214303.0      2
M-SC       XR        190200.0      2
X-LC       XY25      169012.0      2
M-LC       XR        161221.0      1
L-SC       OX40N     114798.0      1
           XR         89029.0      1
M-SC       AR         76001.0      1
L-MC       XR         44530.0      1
M-MC       XY25       41919.0      1
H-MC       AR         36546.0      1
X-LC       XR         34633.0      1
H-LC       AR         31835.0      1
M-MC       AR          2182.0      1

In [32]:
# notebook execution time

end_time = time.time()
execution_time = round(end_time - start_time, 0)
print(f"Notebook execution time: {execution_time} seconds")

Notebook execution time: 30.0 seconds