<a href="https://colab.research.google.com/github/ankit-rathi/Quantvesting_v2/blob/main/myStocks_Portfolio_Analysis.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
'''
!pip install pandas==2.2.2 -qq
!pip install pyxirr -qq
!pip install ta -qq
!pip install yfinance==0.2.59 -qq
'''

'\n!pip install pandas==2.2.2 -qq\n!pip install pyxirr -qq\n!pip install ta -qq\n!pip install yfinance==0.2.59 -qq\n'

In [2]:
# import libraries

import numpy as np
import pandas as pd
import datetime
import warnings
warnings.filterwarnings('ignore')
import yfinance as yfin
import ta
import matplotlib.pyplot as plt
import requests

In [3]:
# notebook start time
import time
import datetime
import pytz

start_time = time.time()

# function to print date timestamp
def print_date_time():
  tz_NY = pytz.timezone('Asia/Kolkata')
  datetime_NY = datetime.datetime.now(tz_NY)
  print("Run date time (IST):", datetime_NY.strftime("%Y-%m-%d %H:%M:%S"))

In [4]:
# function to get booked and reserved amount
def get_amt():
  # fetch the JSON data from the URL
  url = "https://raw.githubusercontent.com/ankit-rathi/Tradevesting_v1/main/data/myPortfolioAmts.json"
  response = requests.get(url)
  pf_amts = response.json()  # parse the JSON data

  # extract values from the JSON
  py_booked_amt_dm = pf_amts["py_booked_amt_dm"]
  py_booked_amt_sv = pf_amts["py_booked_amt_sv"]
  cy_booked_amt_dm = pf_amts["cy_booked_amt_dm"]
  cy_booked_amt_sv = pf_amts["cy_booked_amt_sv"]
  reserve_amt_dm = pf_amts["reserve_amt_dm"]
  reserve_amt_sv = pf_amts["reserve_amt_sv"]

  # perform calculations
  py_booked_amt = py_booked_amt_dm + py_booked_amt_sv
  cy_booked_amt = cy_booked_amt_dm + cy_booked_amt_sv
  reserve_amt = reserve_amt_dm + reserve_amt_sv
  total_booked_amt = py_booked_amt + cy_booked_amt

  return total_booked_amt, reserve_amt, cy_booked_amt, py_booked_amt

gen_output = 0

In [5]:
# function to format the amount
def format_amt(number):
    abs_number = abs(number)

    if abs_number >= 1_00_00_000:  # Crores
        formatted_amt = f"{number / 1_00_00_000:.2f} C"
    elif abs_number >= 1_00_000:  # Lakhs
        formatted_amt = f"{number / 1_00_000:.2f} L"
    elif abs_number >= 1_000:  # Thousands
        formatted_amt = f"{number / 1_000:.2f} K"
    else:
        formatted_amt = f"{number:.2f}"

    return formatted_amt

# function to set start and end date
def get_start_end_date():
  start_date = (datetime.date.today() + datetime.timedelta(days=-365)).strftime('%Y-%m-%d')
  end_date = (datetime.date.today() + datetime.timedelta(days=1)).strftime('%Y-%m-%d')
  return start_date, end_date

# function to fetch my portfolio csv
def get_mypfs_df():
  mypfs_df = pd.read_csv('https://raw.githubusercontent.com/ankit-rathi/Tradevesting_v1/main/data/myPortfolioStocks.csv')
  return mypfs_df

# function to fetch my prospects csv
def get_mypps_df():
  mypps_df = pd.read_csv('https://raw.githubusercontent.com/ankit-rathi/Tradevesting_v1/main/data/myProspectsScrips.csv')
  return mypps_df

# function to fetch screener data
def get_myscreen_df():
  myscreen_df = pd.read_csv('https://raw.githubusercontent.com/ankit-rathi/Tradevesting_v1/main/data/myScreenerDB.csv')
  return myscreen_df

# function to fetch momentum data
def get_myinvmt_df():
  myinvmt_df = pd.read_csv('https://raw.githubusercontent.com/ankit-rathi/Tradevesting_v1/main/data/myInvestments.csv')
  return myinvmt_df

# function to get the stock ids
def get_stock_ids(df_pf):
  stock_n100 = df_pf['Symbol'].unique()

  exclude = ['CADILAHC','MMTC', 'MASFIN']

  stock_ids = df_pf[~df_pf['Symbol'].isin(exclude) ]['Symbol'].unique()

  #mypf = mypf[mypf.Forecast.notnull()]
  #stock_ids = mypf['Symbol'].unique()

  #stock_ids.sort()
  return stock_ids

# get features from screener data
def get_screener_features():
  myscreen_df = get_myscreen_df()
  cols = ['Symbol', 'EPS', 'MedPE', 'ROCE%', 'ROE%', 'CapType']
  return myscreen_df[cols]

# get relative strength
def get_relative_strength(stock_list):

    # Dictionary to store stock tickers and their corresponding percentage price change
    stock_changes = {}

    # Loop through each stock and fetch its price data
    for stock in stock_list:
        try:
            # Download the stock data for the given date range
            stock_data = yfin.Ticker(stock + '.NS').history(period='1mo', interval='1d')[map(str.title, ['open', 'close', 'low', 'high', 'volume'])]

            # Calculate the percentage change for the stock
            if len(stock_data) > 0:
                start_price = stock_data['Close'].iloc[0]
                end_price = stock_data['Close'].iloc[-1]
                percent_change = round(((end_price - start_price) / start_price) * 100, 2)
                stock_changes[stock] = percent_change
            else:
                stock_changes[stock] = np.nan  # If no data is available, set to NaN

        except Exception as e:
            print(f"Error fetching data for {stock}: {e}")
            stock_changes[stock] = np.nan

    # Create a DataFrame with stock tickers and their percentage changes
    df = pd.DataFrame(list(stock_changes.items()), columns=['Symbol', 'Percent_Change'])

    # Drop any stocks with missing data (NaN values)
    df = df.dropna()

    # Calculate the percentile rank based on percentage change
    df['RSP'] = round(df['Percent_Change'].rank(pct=True) * 100, 2)
    cols = ['Symbol', 'RSP']
    df = df[cols]
    # Sort by percentile rank (optional)
    df = df.sort_values(by='RSP', ascending=False).reset_index(drop=True)

    return df

In [6]:
# function to get stock technicals
def stock_prec_dev(stock_symbol):
    #stock_symbol = 'ULTRACEMCO.NS'
    short_window = 20
    mid_window = 50
    long_window = 200
    moving_avg = 'SMA'

    start = datetime.datetime(*map(int, start_date.split('-')))
    end = datetime.datetime(*map(int, end_date.split('-')))

    stock_df = yfin.Ticker(stock_symbol + '.NS').history(period='max', interval='1d')[map(str.title, ['open', 'close', 'low', 'high', 'volume'])]

    stock_df['Max'] = round(max(stock_df['Close']),2)
    stock_df = stock_df[(stock_df.index <= end_date) & (stock_df.index >= start_date)]
    stock_df['200_SMA'] = round(stock_df['Close'].rolling(window = 200, min_periods = 1).mean(),0)
    stock_df['Dev%_200'] = round((stock_df['Close'] - stock_df['200_SMA'])*100/stock_df['200_SMA'],2)
    stock_df.dropna(axis = 0, inplace = True) # remove any null rows

    stock_df['20_SMA'] = stock_df['Close'].rolling(window=20).mean()
    stock_df['50_SMA'] = stock_df['Close'].rolling(window=50).mean()
    stock_df['Symbol'] = stock_symbol

    stock_df['Close'] = round(stock_df['Close'],2)
    stock_df['Min'] = round(min(stock_df['Close']),2)
    stock_df['RSI_14'] = ta.momentum.RSIIndicator(close=stock_df['Close'], window=14).rsi()
    stock_df['RSI_14'] = round(stock_df['RSI_14'],0)
    stock_df['Prev_Close'] = stock_df['Close'].shift(1)
    stock_df.drop(['Open', 'Low', 'High', 'Volume'], axis=1, inplace=True)
    stock_df = stock_df.tail(1)

    max_SMA = max(stock_df['20_SMA'].item(), stock_df['50_SMA'].item(), stock_df['200_SMA'].item())
    min_SMA = min(stock_df['20_SMA'].item(), stock_df['50_SMA'].item(), stock_df['200_SMA'].item())
    ABS_Spread = max_SMA - min_SMA
    stock_df['Spread%'] = round((ABS_Spread / stock_df['200_SMA'].item()) * 100,2)

    return stock_df

# function to compute stock attributes
def get_common_features(stock_ids, df_mypf):

  df_prec_dev = pd.DataFrame()
  df_tmp = get_screener_features()
  df_rs = get_relative_strength(stock_ids)

  for stock_id in stock_ids:
      tmp = stock_prec_dev(stock_id)
      tmp = tmp.reset_index()
      df_prec_dev = pd.concat([df_prec_dev, tmp], ignore_index = True)
  df_prec_dev = pd.merge(df_prec_dev, df_mypf, on= 'Symbol')
  df_prec_dev = pd.merge(df_prec_dev, df_tmp, on= 'Symbol', how='left')
  df_prec_dev = pd.merge(df_prec_dev, df_rs, on= 'Symbol', how='left')
  #print(df_prec_dev.columns)
  df_prec_dev['Curr_PE'] = round(df_prec_dev['Close']/df_prec_dev['EPS'],1)
  df_prec_dev['Dev%_PE'] = round((df_prec_dev['Curr_PE'] - df_prec_dev['MedPE'])*100/df_prec_dev['MedPE'],2)
  df_prec_dev['Conviction'] = df_prec_dev['Conviction'] + '-' + df_prec_dev['CapType']
  return df_prec_dev

# function to arrange stock features
def arrange_features(df_stocks, common_cols, diff_cols):
  df_stocks_common = df_stocks[common_cols].drop_duplicates()
  df_stocks_diff = df_stocks[diff_cols]
  df_stocks_diff['Investment'] = df_stocks_diff['AvgCost'] * df_stocks_diff['Shares']
  df_stocks_diff = df_stocks_diff.groupby(['Symbol'])[['Shares', 'Investment']].aggregate(['sum']).reset_index()
  df_stocks_diff.columns = ['Symbol', 'Shares', 'Investment']
  df_stocks_diff['AvgCost'] = round(df_stocks_diff['Investment']/df_stocks_diff['Shares'],2)
  df_stocks = pd.merge(df_stocks_diff, df_stocks_common, on='Symbol')
  return df_stocks

# plot fact distribution across dimension
def plot_pie_chart(df, dimension, fact):
  # grouping the data by category and calculating the sum of fact for each type
  grouped_data = df.groupby(dimension)[fact].sum()

  # sorting the grouped data in descending order
  grouped_data = grouped_data.sort_values(ascending=False)

  # creating a pie chart
  grouped_data.plot.pie(autopct='%1.1f%%', startangle=90, figsize=(6, 6))

  # adding a title and displaying the plot
  plt.title(f'{dimension} {fact} Distribution')
  plt.ylabel('')  # To hide the y-label
  plt.show()

In [7]:
# function to get portfolio features

def get_portfolio_features(df_common_features):

  print_date_time()
  print('-------------------')

  #df_common_features["Target"] = df_common_features["Target"].fillna(df_common_features["Max"])
  df_common_features['NTT'] = np.where(df_common_features['Strategy']== 'NTT', df_common_features["Target"], df_common_features['Max'])
  df_common_features['LTT'] = np.where(df_common_features['Strategy']== 'BTT', df_common_features["Target"], df_common_features['Max'])
  df_common_features['BOL'] = df_common_features['Min']

  tmp_df = df_common_features[df_common_features['Symbol'].isin(mypf_df[mypf_df['InPortfolio'] != 'NA'].Symbol.values)]
  print('qualified stocks: '+str(len(tmp_df['Symbol'].unique())))
  tmp_df1 = tmp_df[tmp_df['LatestQtr'] == 1]
  print('with latest results: '+str(len(tmp_df1['Symbol'].unique())))
  tmp_df1 = tmp_df1[tmp_df1['StarStock'] == 1]
  print('still star stocks: '+str(len(tmp_df1['Symbol'].unique())))
  tmp_df['Investment'] = tmp_df['AvgCost'] * tmp_df['Shares']
  tmp_df['Current'] = round(tmp_df['Close'] * tmp_df['Shares'],0)
  tmp_df['Previous'] = tmp_df['Prev_Close'] * tmp_df['Shares']
  tmp_df['EstimatedST'] = tmp_df['NTT'] * tmp_df['Shares']
  tmp_df['EstimatedLT'] = tmp_df['LTT'] * tmp_df['Shares']
  tmp_df['Current P/L'] = round((tmp_df['Current'] - tmp_df['Investment']),0)
  tmp_df['Today P/L%'] = round((tmp_df['Current'] - tmp_df['Previous'])*100/tmp_df['Previous'],2)
  tmp_df['Current P/L%'] = round((tmp_df['Current'] - tmp_df['Investment'])*100/tmp_df['Investment'],2)
  tmp_df['EstimatedST P/L%'] = round((tmp_df['EstimatedST'] - tmp_df['Investment'])*100/tmp_df['Investment'],2)
  tmp_df['EstimatedLT P/L%'] = round((tmp_df['EstimatedLT'] - tmp_df['Investment'])*100/tmp_df['Investment'],2)
  tmp_df['NTT%'] = round((tmp_df['NTT'] - tmp_df['Close'])*100/tmp_df['Close'],2)
  tmp_df['LTT%'] = round((tmp_df['LTT'] - tmp_df['Close'])*100/tmp_df['Close'],2)
  tmp_df['Gained%'] = round((tmp_df['Close'] - tmp_df['BOL'])*100/tmp_df['BOL'],2)
  investment = round(sum(tmp_df['AvgCost']*tmp_df['Shares']),0)
  current = round(sum(tmp_df['Close']*tmp_df['Shares']),0)
  tmp_df['InitAlloc%'] = round(tmp_df['Investment']*100/investment,2)
  tmp_df['CurrAlloc%'] = round(tmp_df['Current']*100/current,2)
  tmp_df['FTT'] = tmp_df['LTT']
  tmp_df.loc[tmp_df['Strategy'] == 'NTT', 'FTT'] = tmp_df['NTT']
  tmp_df['FTT%'] = tmp_df['LTT%']
  tmp_df.loc[tmp_df['Strategy'] == 'NTT', 'FTT%'] = tmp_df['NTT%']
  tmp_df['FTT Amt'] = round(tmp_df['FTT%'] * tmp_df['Current']/100,0)
  tmp_df['OTT%'] = round((tmp_df['FTT'] - tmp_df['AvgCost'])*100/tmp_df['AvgCost'],2)
  tmp_df['RRR Ind'] = round(tmp_df['Current P/L']/tmp_df['FTT Amt'],2)
  tmp_df['Risk Ind'] = round(tmp_df['Current P/L%']*tmp_df['CurrAlloc%'],0)

  return tmp_df

# function to print portfolio features
def print_portfolio_stats(df_portfolio_features, myinvmt_df):
  from pyxirr import xirr

  total_booked_amt, reserve_amt, cy_booked_amt, py_booked_amt = get_amt()

  dates = myinvmt_df['Date'].values
  dates = np.append(dates, datetime.date.today().strftime('%d-%b-%y'))
  investment = myinvmt_df['Investment'].values
  dates= pd.to_datetime(dates)

  current = round(sum(df_portfolio_features['Close']*df_portfolio_features['Shares']),0) + reserve_amt
  investment_xirr = np.append(investment, current)
  cagr = round(xirr(pd.DataFrame({"dates": dates, "amounts": investment_xirr}))*100,2)

  investment = -sum(investment)
  invested = round(sum(df_portfolio_features['AvgCost']*df_portfolio_features['Shares']),0) + reserve_amt
  previous = round(sum(df_portfolio_features['Prev_Close']*df_portfolio_features['Shares']),0) + reserve_amt
  cy_invested = investment + py_booked_amt

  today_pnl_amount = current-previous
  today_pnl_percentage = round((current-previous)*100/previous,2)

  curr_pnl_amount = current-invested
  curr_pnl_percentage = round((curr_pnl_amount)*100/(cy_invested),2)

  cy_pnl_amount = cy_booked_amt + curr_pnl_amount
  cy_pnl_percentage = round((cy_pnl_amount)*100/cy_invested,2)

  overall_pnl_amount = total_booked_amt + curr_pnl_amount
  overall_pnl_percentage = round((overall_pnl_amount)*100/investment,2)

  estimate_st = round(sum(df_portfolio_features['FTT']*df_portfolio_features['Shares']),0)  + reserve_amt
  est_st_pnl_amount = estimate_st-current
  est_st_pnl_percentage = round((est_st_pnl_amount)*100/current,2)

  estimate_lt = round(sum(df_portfolio_features['LTT']*df_portfolio_features['Shares']),0)  + reserve_amt
  est_lt_pnl_amount = estimate_lt-current
  est_lt_pnl_percentage = round((est_lt_pnl_amount)*100/current,2)

  total_profit = round(sum(df_portfolio_features[df_portfolio_features['Current P/L%'] > 0]['Current']) - sum(df_portfolio_features[df_portfolio_features['Current P/L%'] > 0]['Investment']),0)
  total_loss = round(sum(df_portfolio_features[df_portfolio_features['Current P/L%'] < 0]['Current']) - sum(df_portfolio_features[df_portfolio_features['Current P/L%'] < 0]['Investment']),0)

  cy_booked_percentage = round((cy_booked_amt)*100/current,2)
  py_booked_percentage = round((py_booked_amt)*100/investment,2)
  total_booked_percentage = round((total_booked_amt)*100/investment,2)

  print('-------------------')
  print('Initial Investment: ', format_amt(investment))
  print('CY Investment: ', format_amt(cy_invested))
  print('Reserve: ', format_amt(reserve_amt))
  print('Current: ',  format_amt(current))
  print('-------------------')
  print('Today PnL: '+ '{} ({}%)'.format(format_amt(today_pnl_amount), today_pnl_percentage))
  print('Current PnL: '+ '{} ({}%)'.format(format_amt(curr_pnl_amount), curr_pnl_percentage))
  print('CY Booked + Current PnL: '+ '{} ({}%)'.format(format_amt(cy_pnl_amount), cy_pnl_percentage))
  print('-------------------')
  print('Total profit: ', format_amt(total_profit))
  print('Total loss: ', format_amt(total_loss))
  print('-------------------')
  print('Total Booked + Current PnL: '+ '{} ({}%)'.format(format_amt(overall_pnl_amount), overall_pnl_percentage))
  print('Total Booked PnL: '+ '{} ({}%)'.format(format_amt(total_booked_amt), total_booked_percentage))
  print('Curr Year Booked PnL: '+ '{} ({}%)'.format(format_amt(cy_booked_amt), cy_booked_percentage))
  print('Prev Year Booked PnL: '+ '{} ({}%)'.format(format_amt(py_booked_amt), py_booked_percentage))
  print('===================')
  print('Est FTT: ',  format_amt(estimate_st))
  print('Est FTT PnL: '+ '{} ({}%)'.format(format_amt(est_st_pnl_amount), est_st_pnl_percentage))

  print('===================')
  print('Deployed: ', format_amt(investment))

  print('Current: ', format_amt(current))

  print('CAGR/XIRR %: '+'{}%'.format(cagr))

In [8]:
# get start and end date
start_date, end_date = get_start_end_date()

# get portfolio and prospects data
mypfs_df = get_mypfs_df()
mypps_df = get_mypps_df()
myinvmt_df = get_myinvmt_df()

# merge above datasets
mypf_df = pd.merge(mypfs_df, mypps_df, on="Symbol")

# seggregate dm and sv portfolio
dm_pf = mypf_df[mypf_df['InPortfolio'] == 'DM']
sv_pf = mypf_df[mypf_df['InPortfolio'] == 'SV']

# build portfolio stock dataframe
dm_stocks = get_stock_ids(dm_pf)
sv_stocks = get_stock_ids(sv_pf)
df_stocks = pd.concat([dm_pf,sv_pf], ignore_index = True)

# arrange common and diff stock features
common_cols = ['Symbol', 'Target', 'Criteria', 'Strategy', 'CumlRnk', 'LatestQtr', 'StarStock', 'Conviction', 'Category', 'InFolio', 'XIRR', 'MBQ']
diff_cols = ['Symbol', 'AvgCost', 'Shares']
df_stocks = arrange_features(df_stocks, common_cols, diff_cols)

# get common features
stock_ids = df_stocks['Symbol'].values
df_common_features = get_common_features(stock_ids, df_stocks)

df_common_features.reset_index(drop=True, inplace=True)
df_common_features.drop(['Date'], axis=1, inplace=True)
# get and print portfolio features
df_portfolio_features = get_portfolio_features(df_common_features)

print_portfolio_stats(df_portfolio_features, myinvmt_df)

df = df_portfolio_features
#plot_pie_chart(df, 'CapType', 'Current')
list_ox40n = list(df[df['MBQ'].str.contains('OX40N', na=False)]['Symbol'].values)

Run date time (IST): 2026-03-05 11:37:50
-------------------
qualified stocks: 86
with latest results: 26
still star stocks: 15
-------------------
Initial Investment:  1.33 C
CY Investment:  1.60 C
Reserve:  2.44 L
Current:  1.34 C
-------------------
Today PnL: 10.10 K (0.08%)
Current PnL: -39.94 L (-24.97%)
CY Booked + Current PnL: -24.26 L (-15.16%)
-------------------
Total profit:  93.82 K
Total loss:  -40.88 L
-------------------
Total Booked + Current PnL: 2.72 L (2.04%)
Total Booked PnL: 42.66 L (32.07%)
Curr Year Booked PnL: 15.68 L (11.66%)
Prev Year Booked PnL: 26.98 L (20.29%)
===================
Est FTT:  2.41 C
Est FTT PnL: 1.07 C (79.23%)
===================
Deployed:  1.33 C
Current:  1.34 C
CAGR/XIRR %: 0.56%

In [9]:
# top 5 near their targets
cols = ['Symbol', 'Today P/L%', 'Current P/L%', 'FTT%', 'OTT%', 'FTT Amt', 'Current P/L', 'Current', 'FTT', 'Dev%_PE', 'RSI_14','Conviction', 'Spread%',  'CumlRnk', 'RRR Ind', 'CurrAlloc%', 'Gained%', 'Criteria', 'Strategy', 'Category']
df_tmp = df_portfolio_features[~df_portfolio_features['Symbol'].isin(['ENRIN','BLUSPRING','DIGITIDE'])]
df_tmp = df_tmp.sort_values(by = 'FTT Amt', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
19,COALINDIA,3.54,10.80,6.21,17.67,10352.0,16244.0,166704.0,478.51,33.43,65.0,L-LC,11.29,185.0,1.57,1.26,30.95,XY25,ATH,MINING
50,MASFIN,-0.51,-6.78,30.41,21.57,27775.0,-6645.0,91335.0,397.04,-19.60,36.0,H-SC,6.40,167.0,-0.24,0.69,27.44,XR,ATH,FINANCE
77,TTKPRESTIG,-1.30,-37.18,59.34,0.09,37566.0,-37471.0,63306.0,770.00,46.85,22.0,M-SC,12.91,250.0,-1.00,0.48,0.00,OX40N,NTT,DURABLES
2,ABBOTINDIA,2.25,-4.56,23.71,18.07,40473.0,-8155.0,170700.0,35195.00,-18.71,69.0,X-MC,11.06,58.0,-0.20,1.29,8.22,X40,ATH,PHARMA
51,MEDANTA,-0.70,-7.99,34.86,24.08,40717.0,-10149.0,116801.0,1486.00,-8.69,42.0,X-SC,8.06,87.0,-0.25,0.88,6.98,XY24,NTT,HEALTHCARE

In [10]:
# top 5 today
df_tmp = df_portfolio_features.sort_values(by = 'Today P/L%', ascending=False)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
47,JSWINFRA,4.11,-12.56,33.15,16.43,64285.0,-27852.0,193922.0,342.00,-25.03,48.0,X-MC,11.28,61.0,-0.43,1.47,4.11,X40N,NTT,REALTY
19,COALINDIA,3.54,10.80,6.21,17.67,10352.0,16244.0,166704.0,478.51,33.43,65.0,L-LC,11.29,185.0,1.57,1.26,30.95,XY25,ATH,MINING
57,RECLTD,3.27,-8.09,31.37,20.74,58576.0,-16445.0,186725.0,446.00,1.56,40.0,M-MC,3.64,191.0,-0.28,1.41,3.27,XY25,NTT,FINANCE
27,FINCABLES,2.98,16.00,79.24,107.91,135710.0,23620.0,171264.0,1641.55,4.52,66.0,M-SC,6.11,220.0,0.17,1.30,28.85,OX40N,ATH,CABLES
59,RELIANCE,2.75,-11.29,41.24,25.30,73522.0,-22685.0,178278.0,1952.00,-13.49,42.0,X-LC,2.17,21.0,-0.31,1.35,19.03,XY25,BTT,REFINERIES

In [11]:
# bottom 5 today
df_tmp = df_portfolio_features.sort_values(by = 'Today P/L%', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
55,RAJESHEXPO,-4.24,-75.64,310.75,0.07,103850.0,-103758.0,33419.0,518.0,1124.75,22.0,L-SC,12.51,268.0,-1.00,0.25,0.00,OX40N,NTT,JEWELLERY
20,COFFEEDAY,-2.61,-53.31,189.75,35.27,100588.0,-60538.0,53011.0,80.0,-63.78,30.0,L-SC,15.52,266.0,-0.60,0.40,18.35,XR,NTT,HOTELS
35,HINDUNILVR,-2.56,-12.03,29.22,13.67,66075.0,-30933.0,226130.0,2922.0,-34.74,38.0,X-LC,2.55,9.0,-0.47,1.71,6.11,XY25,NTT,FMCG
16,CAMPUS,-2.56,-18.84,64.23,33.28,87457.0,-31613.0,136162.0,393.0,-34.65,29.0,M-SC,3.86,218.0,-0.36,1.03,5.53,XY24,NTT,FOOTWEAR
41,INDIGOPNTS,-2.43,-37.04,58.87,0.02,64695.0,-64664.0,109895.0,1408.0,67.41,19.0,M-SC,13.70,222.0,-1.00,0.83,0.00,OX40N,NTT,PAINTS

In [12]:
# top 5 to exit based on CumlRnk
df_tmp = df_portfolio_features[~df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])]
df_tmp = df_tmp[(df_tmp['Current P/L%'] > -1) & (df_tmp['Current P/L%'] < 1)].sort_values(by = 'CumlRnk', ascending=False)
df_tmp[cols].head()

Empty DataFrame
Columns: [Symbol, Today P/L%, Current P/L%, FTT%, OTT%, FTT Amt, Current P/L, Current, FTT, Dev%_PE, RSI_14, Conviction, Spread%, CumlRnk, RRR Ind, CurrAlloc%, Gained%, Criteria, Strategy, Category]
Index: []

In [13]:
# OX40N stocks to exit
df_tmp = df_portfolio_features[(df_portfolio_features['Symbol'].isin(list_ox40n))].sort_values(by = 'Current P/L%', ascending=False)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
27,FINCABLES,2.98,16.00,79.24,107.91,135710.0,23620.0,171264.0,1641.55,4.52,66.0,M-SC,6.11,220.0,0.17,1.30,28.85,OX40N,ATH,CABLES
66,SIS,0.25,-32.02,78.38,21.26,59161.0,-35552.0,75480.0,528.00,1770.47,36.0,H-SC,7.14,168.0,-0.60,0.57,4.06,OX40N,NTT,MISC
48,KANSAINER,-0.67,-35.38,75.59,13.47,131728.0,-95400.0,174267.0,340.00,-44.56,29.0,H-SC,14.72,162.0,-0.72,1.32,0.00,XY24,NTT,PAINTS
41,INDIGOPNTS,-2.43,-37.04,58.87,0.02,64695.0,-64664.0,109895.0,1408.00,67.41,19.0,M-SC,13.70,222.0,-1.00,0.83,0.00,OX40N,NTT,PAINTS
77,TTKPRESTIG,-1.30,-37.18,59.34,0.09,37566.0,-37471.0,63306.0,770.00,46.85,22.0,M-SC,12.91,250.0,-1.00,0.48,0.00,OX40N,NTT,DURABLES

In [14]:
# top 5 to book for rotation
df_tmp = df_portfolio_features[(df_portfolio_features['Current P/L%'] > 20) ].sort_values(by = 'CumlRnk', ascending=False)
df_tmp[cols].head()

Empty DataFrame
Columns: [Symbol, Today P/L%, Current P/L%, FTT%, OTT%, FTT Amt, Current P/L, Current, FTT, Dev%_PE, RSI_14, Conviction, Spread%, CumlRnk, RRR Ind, CurrAlloc%, Gained%, Criteria, Strategy, Category]
Index: []

In [15]:
# top 5 to monitor for exit
df_tmp = df_portfolio_features[~df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])]
df_tmp = df_tmp[(df_tmp['Current P/L%'] > 0) ].sort_values(by = 'Dev%_PE', ascending=False)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
19,COALINDIA,3.54,10.80,6.21,17.67,10352.0,16244.0,166704.0,478.51,33.43,65.0,L-LC,11.29,185.0,1.57,1.26,30.95,XY25,ATH,MINING
27,FINCABLES,2.98,16.00,79.24,107.91,135710.0,23620.0,171264.0,1641.55,4.52,66.0,M-SC,6.11,220.0,0.17,1.30,28.85,OX40N,ATH,CABLES
1,ABB,0.76,7.79,35.05,45.57,98841.0,20381.0,282000.0,7934.00,-30.71,55.0,H-MC,8.95,125.0,0.21,2.14,25.23,AR,NTT,ELECTRICAL

In [16]:
# top 5 to book for rotation from weak conviction
df_tmp = df_portfolio_features[~df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])]
df_tmp = df_tmp[~df_tmp['Criteria'].isin(['XY25','XY24','X40', 'X40N'])].sort_values(by = 'RRR Ind', ascending=False)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
1,ABB,0.76,7.79,35.05,45.57,98841.0,20381.0,282000.0,7934.00,-30.71,55.0,H-MC,8.95,125.0,0.21,2.14,25.23,AR,NTT,ELECTRICAL
27,FINCABLES,2.98,16.00,79.24,107.91,135710.0,23620.0,171264.0,1641.55,4.52,66.0,M-SC,6.11,220.0,0.17,1.30,28.85,OX40N,ATH,CABLES
40,INDIAMART,-1.24,-11.69,134.09,106.72,146044.0,-14421.0,108915.0,4810.62,-60.16,31.0,H-SC,8.51,140.0,-0.10,0.82,8.95,AR,ATH,MISC
85,ZYDUSLIFE,1.10,-4.38,41.84,35.63,83844.0,-9182.0,200392.0,1286.17,-16.67,50.0,H-MC,4.98,120.0,-0.11,1.52,11.56,AR,ATH,PHARMA
84,WIPRO,-1.52,-19.79,114.78,72.27,155994.0,-33541.0,135907.0,420.00,-27.84,20.0,M-LC,11.40,98.0,-0.22,1.03,0.00,XR,NTT,IT

In [17]:
# top 5 to accumulate based on lowest RSI_14
df_tmp = df_portfolio_features[df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])].sort_values(by = 'RSI_14', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
8,AWL,-0.61,-42.11,171.56,57.19,323871.0,-137347.0,188780.0,485.00,-66.89,13.0,X-SC,20.62,81.0,-0.42,1.43,0.00,XY24,NTT,FMCG
53,PGHH,-1.46,-17.11,59.26,32.01,104885.0,-36528.0,176992.0,17616.87,-43.91,20.0,X-MC,9.97,57.0,-0.35,1.34,0.00,X40,ATH,FMCG
3,ACC,-1.09,-36.42,158.16,64.15,239296.0,-86651.0,151300.0,3906.00,-52.08,22.0,X-SC,10.31,85.0,-0.36,1.15,0.00,XY24,BTT,CEMENT
12,BATAINDIA,1.54,-52.02,181.80,35.20,112234.0,-66935.0,61735.0,2096.00,-18.99,24.0,X-SC,23.42,91.0,-0.60,0.47,1.54,X40,NTT,FOOTWEAR
58,RELAXO,-1.00,-58.16,264.03,52.31,160353.0,-84427.0,60733.0,1176.00,-55.47,24.0,X-SC,16.49,92.0,-0.53,0.46,0.00,X40N,NTT,FOOTWEAR

In [18]:
# top 5 to accumulate based on Spread and CumlRnk
df_tmp = df_portfolio_features[df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])]
df_tmp = df_tmp[(df_tmp['CumlRnk'] < 100)].sort_values(by = 'Spread%', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
22,DABUR,-0.80,-5.47,52.02,43.70,121986.0,-13570.0,234498.0,735.00,-14.30,33.0,X-MC,1.25,70.0,-0.11,1.78,8.76,XY24,BTT,FMCG
78,UNITDSPR,0.28,-3.00,24.50,20.77,55646.0,-7018.0,227126.0,1644.00,-14.02,36.0,X-MC,1.33,64.0,-0.13,1.72,3.51,X40N,NTT,BREWERIES
37,ICICIGI,-0.71,-2.41,22.29,19.34,43529.0,-4825.0,195284.0,2252.93,-17.87,39.0,X-MC,1.36,66.0,-0.11,1.48,11.38,X40,ATH,INSURANCE
59,RELIANCE,2.75,-11.29,41.24,25.30,73522.0,-22685.0,178278.0,1952.00,-13.49,42.0,X-LC,2.17,21.0,-0.31,1.35,19.03,XY25,BTT,REFINERIES
35,HINDUNILVR,-2.56,-12.03,29.22,13.67,66075.0,-30933.0,226130.0,2922.00,-34.74,38.0,X-LC,2.55,9.0,-0.47,1.71,6.11,XY25,NTT,FMCG

In [19]:
# top 5 to accumulate based on lowest Gained%
df_tmp = df_portfolio_features[df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])].sort_values(by = 'Gained%', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
3,ACC,-1.09,-36.42,158.16,64.15,239296.0,-86651.0,151300.0,3906.00,-52.08,22.0,X-SC,10.31,85.0,-0.36,1.15,0.0,XY24,BTT,CEMENT
8,AWL,-0.61,-42.11,171.56,57.19,323871.0,-137347.0,188780.0,485.00,-66.89,13.0,X-SC,20.62,81.0,-0.42,1.43,0.0,XY24,NTT,FMCG
24,DIXON,-0.31,-29.94,87.35,31.26,141227.0,-69088.0,161680.0,18931.72,-68.70,35.0,X-MC,24.52,54.0,-0.49,1.22,0.0,X40N,ATH,IT
13,BERGEPAINT,-1.03,-22.64,56.59,21.14,99525.0,-51468.0,175871.0,680.00,-24.39,24.0,X-MC,14.62,68.0,-0.52,1.33,0.0,XY24,NTT,PAINTS
58,RELAXO,-1.00,-58.16,264.03,52.31,160353.0,-84427.0,60733.0,1176.00,-55.47,24.0,X-SC,16.49,92.0,-0.53,0.46,0.0,X40N,NTT,FOOTWEAR

In [20]:
# top 5 to accumulate based on lowest CurrAlloc%
df_tmp = df_portfolio_features[df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])].sort_values(by = 'CurrAlloc%', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
54,QUESS,0.82,-36.02,123.26,42.84,51264.0,-23416.0,41590.0,424.00,-58.13,35.0,X-SC,17.03,80.0,-0.46,0.31,0.82,XY24,NTT,MISC
58,RELAXO,-1.00,-58.16,264.03,52.31,160353.0,-84427.0,60733.0,1176.00,-55.47,24.0,X-SC,16.49,92.0,-0.53,0.46,0.00,X40N,NTT,FOOTWEAR
12,BATAINDIA,1.54,-52.02,181.80,35.20,112234.0,-66935.0,61735.0,2096.00,-18.99,24.0,X-SC,23.42,91.0,-0.60,0.47,1.54,X40,NTT,FOOTWEAR
51,MEDANTA,-0.70,-7.99,34.86,24.08,40717.0,-10149.0,116801.0,1486.00,-8.69,42.0,X-SC,8.06,87.0,-0.25,0.88,6.98,XY24,NTT,HEALTHCARE
36,HONAUT,-0.25,-26.20,94.20,43.32,113228.0,-42672.0,120200.0,58357.33,-35.21,31.0,X-SC,12.84,90.0,-0.38,0.91,0.00,X40N,ATH,ELECTRICAL

In [21]:
# top 5 to accumulate based on CumlRnk
df_tmp = df_portfolio_features.sort_values(by = 'CumlRnk', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
45,ITC,-0.42,-18.17,45.50,19.06,126646.0,-61824.0,278342.0,452.00,-55.12,37.0,X-LC,16.93,1.0,-0.49,2.11,0.78,X40,NTT,FMCG
73,TCS,-1.59,-27.01,69.31,23.58,218866.0,-116851.0,315778.0,4311.59,-36.74,26.0,X-LC,11.43,2.0,-0.53,2.39,0.00,X40,ATH,IT
43,INFY,-1.05,-11.93,52.43,34.24,144475.0,-37330.0,275558.0,1972.00,-30.70,27.0,X-LC,10.37,3.0,-0.26,2.09,1.43,X40,NTT,IT
75,TMPV,-0.61,-22.43,71.90,33.33,181700.0,-73088.0,252712.0,600.00,-83.62,36.0,X-LC,3.23,4.0,-0.40,1.91,3.32,XY24,NTT,AUTO
34,HCLTECH,-2.21,-13.44,43.06,23.83,90171.0,-32517.0,209407.0,1908.19,-9.02,25.0,X-LC,7.94,8.0,-0.36,1.59,0.47,X40,ATH,IT

In [22]:
# top 5 for average up
df_tmp = df_portfolio_features[(df_portfolio_features['Dev%_200'] > 5)].sort_values(by = 'CurrAlloc%', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
42,INDUSINDBK,1.26,-30.66,91.64,32.89,49061.0,-23670.0,53537.0,1800.00,-352.10,55.0,L-MC,12.15,258.0,-0.48,0.41,47.44,XR,NTT,BANKS
67,SONACOMS,0.70,-12.65,59.24,39.09,52343.0,-12801.0,88358.0,804.02,-30.73,44.0,M-MC,10.65,193.0,-0.24,0.67,25.00,AR,ATH,AUTO
19,COALINDIA,3.54,10.80,6.21,17.67,10352.0,16244.0,166704.0,478.51,33.43,65.0,L-LC,11.29,185.0,1.57,1.26,30.95,XY25,ATH,MINING
27,FINCABLES,2.98,16.00,79.24,107.91,135710.0,23620.0,171264.0,1641.55,4.52,66.0,M-SC,6.11,220.0,0.17,1.30,28.85,OX40N,ATH,CABLES
82,VOLTAS,1.07,13.77,27.62,45.20,60252.0,26403.0,218145.0,1856.00,30.22,46.0,X-MC,9.86,79.0,0.44,1.65,21.50,XY25,NTT,AC

In [23]:
# top 5 RSP
df_tmp = df_portfolio_features.sort_values(by = 'RSP', ascending=False)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
27,FINCABLES,2.98,16.00,79.24,107.91,135710.0,23620.0,171264.0,1641.55,4.52,66.0,M-SC,6.11,220.0,0.17,1.30,28.85,OX40N,ATH,CABLES
26,EASEMYTRIP,-1.29,-57.89,246.00,45.70,183157.0,-102361.0,74454.0,26.40,-22.68,46.0,M-SC,18.04,204.0,-0.56,0.56,22.67,XY24,NTT,TRAVEL
11,BANDHANBNK,1.63,-13.27,121.85,92.42,294392.0,-36957.0,241602.0,400.00,106.90,66.0,H-SC,9.26,174.0,-0.13,1.83,33.09,XY24,NTT,BANKS
83,WHIRLPOOL,-0.42,-28.18,153.31,81.92,126398.0,-32352.0,82446.0,2270.00,-57.90,51.0,M-SC,25.83,210.0,-0.26,0.62,15.81,XR,NTT,DURABLES
19,COALINDIA,3.54,10.80,6.21,17.67,10352.0,16244.0,166704.0,478.51,33.43,65.0,L-LC,11.29,185.0,1.57,1.26,30.95,XY25,ATH,MINING

In [24]:
# Top N allocation
df_tmp = df_portfolio_features.sort_values(by = 'CurrAlloc%', ascending=False)
top_n_values = [10, 25, 50]

sum_df = pd.DataFrame({
    'Top_N': top_n_values,
    'Sum_Alloc%': [df_tmp['CurrAlloc%'].head(n).sum() for n in top_n_values]
})

sum_df

   Top_N  Sum_Alloc%
0     10       20.73
1     25       45.59
2     50       77.76

In [25]:
# market-cap-wise allocation
df_tmp = df_portfolio_features[cols]
df_tmp.groupby(df_tmp['Conviction'].str[-2:])['CurrAlloc%'].sum().sort_values(ascending=False)

Conviction
SC    44.69
MC    30.39
LC    24.93
Name: CurrAlloc%, dtype: float64

In [26]:
# criteria-wise allocation
df_portfolio_features.groupby('Criteria')['CurrAlloc%'].sum().sort_values(ascending=False)

Criteria
XY24     26.63
X40      24.09
X40N     14.67
AR        9.12
XY25      9.03
XR        8.50
OX40N     7.15
SR        0.82
Name: CurrAlloc%, dtype: float64

In [27]:
# conviction-wise allocation
df_portfolio_features.groupby('Conviction')['CurrAlloc%'].sum().sort_values(ascending=False)

Conviction
X-MC    22.87
H-SC    22.26
X-LC    21.43
X-SC    11.18
M-SC    10.60
H-MC     5.03
M-MC     2.08
L-LC     1.26
H-LC     1.21
M-LC     1.03
L-SC     0.65
L-MC     0.41
Name: CurrAlloc%, dtype: float64

In [28]:
# sector-wise stats
df_tmp = df_portfolio_features.groupby('Category')[['CurrAlloc%', 'Current', 'Current P/L', 'FTT Amt']].sum().sort_values(by=['Current', 'Current P/L'], ascending=False)
df_tmp['Current P/L%'] = round(df_tmp['Current P/L'] * 100 / df_tmp['Current'], 2)
df_tmp['FTT%'] = round(df_tmp['FTT Amt'] * 100 / df_tmp['Current'], 2)
cols = ['CurrAlloc%', 'Current P/L%', 'FTT%']
df_tmp[cols].sort_values(by=['CurrAlloc%'], ascending=False)

               CurrAlloc%  Current P/L%    FTT%
Category
FMCG                15.70        -19.05   59.31
FINANCE             12.91        -22.56   70.78
IT                  11.46        -44.87  117.48
MISC                 6.75        -45.66  105.24
ELECTRICAL           6.38        -11.55   52.25
PAINTS               4.99        -40.15   60.96
INSURANCE            4.92         -4.56   40.35
PHARMA               4.31         -3.25   35.75
AUTO                 3.73        -26.66   74.96
BANKS                3.24        -25.04  100.80
AC                   2.22         -8.95   38.50
FOOTWEAR             1.96        -70.75  139.21
TRAVEL               1.93        -75.13  162.83
DURABLES             1.85        -58.29   96.80
BREWERIES            1.72         -3.09   24.50
HEALTHCARE           1.65        -40.95   75.73
REALTY               1.47        -14.36   33.15
APPARELS             1.43        -25.21   62.95
CERAMICS             1.39        -66.72  117.38
REFINERIES           1.35        -12.72   41.24
CABLES               1.30         13.79   79.24
MINING               1.26          9.74    6.21
JEWELLERY            1.17       -106.05  177.63
CEMENT               1.15        -57.27  158.16
ENGINEERING          1.12        -64.21  139.31
CHEMICALS            1.02        -96.49  256.80
ENTERTAINMENT        0.79        -85.46  196.07
TEXTILES             0.44        -57.46  102.36
HOTELS               0.40       -114.20  189.75

In [29]:
# money to be made criteria-wise
df_portfolio_features.groupby('Criteria')['FTT Amt'].agg(['sum', 'count']).sort_values(by='sum', ascending=False)

                sum  count
Criteria
XY24      3611813.0     21
X40       1542586.0     15
AR        1367941.0     10
XR        1367574.0     12
X40N      1184081.0     10
OX40N      847030.0     10
XY25       423470.0      6
SR         311049.0      2

In [30]:
# money to be made conviction-wise
df_portfolio_features.groupby('Conviction')['FTT Amt'].agg(['sum', 'count']).sort_values(by='sum', ascending=False)

                  sum  count
Conviction
H-SC        3851523.0     24
M-SC        1518037.0     14
X-MC        1493281.0     15
X-LC        1443608.0     12
X-SC        1328587.0     10
H-MC         415422.0      3
L-SC         204438.0      2
M-LC         155994.0      1
M-MC         110919.0      2
H-LC          74322.0      1
L-MC          49061.0      1
L-LC          10352.0      1

In [31]:
# money to be made criteria and conviction-wise
df_portfolio_features.groupby(['Conviction', 'Criteria'])['FTT Amt'].agg(['sum', 'count']).sort_values(by='sum', ascending=False)

                           sum  count
Conviction Criteria
H-SC       XY24      1302783.0      6
           AR         982094.0      5
M-SC       XY24       892026.0      6
H-SC       XR         875562.0      7
X-LC       X40        750783.0      6
X-SC       XY24       655148.0      4
X-MC       X40        593888.0      7
X-SC       X40N       475524.0      4
X-MC       X40N       462937.0      4
H-SC       OX40N      380035.0      4
M-SC       OX40N      363145.0      5
H-SC       SR         311049.0      2
X-LC       XY24       307608.0      2
           X40N       245620.0      2
H-MC       XY24       232737.0      1
X-MC       XY24       221511.0      2
           XY25       214945.0      2
X-SC       X40        197915.0      2
M-SC       XR         186369.0      2
H-MC       AR         182685.0      2
M-LC       XR         155994.0      1
X-LC       XY25       139597.0      2
L-SC       OX40N      103850.0      1
           XR         100588.0      1
M-SC       AR          76497.0      1
H-LC       AR          74322.0      1
M-MC       XY25        58576.0      1
           AR          52343.0      1
L-MC       XR          49061.0      1
L-LC       XY25        10352.0      1

In [32]:
# notebook execution time

end_time = time.time()
execution_time = round(end_time - start_time, 0)
print(f"Notebook execution time: {execution_time} seconds")

Notebook execution time: 30.0 seconds