<a href="https://colab.research.google.com/github/ankit-rathi/Quantvesting_v2/blob/main/myStocks_Portfolio_Analysis.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
'''
!pip install pandas==2.2.2 -qq
!pip install pyxirr -qq
!pip install ta -qq
!pip install yfinance==0.2.59 -qq
'''

'\n!pip install pandas==2.2.2 -qq\n!pip install pyxirr -qq\n!pip install ta -qq\n!pip install yfinance==0.2.59 -qq\n'

In [2]:
# import libraries

import numpy as np
import pandas as pd
import datetime
import warnings
warnings.filterwarnings('ignore')
import yfinance as yfin
import ta
import matplotlib.pyplot as plt
import requests

In [3]:
# notebook start time
import time
import datetime
import pytz

start_time = time.time()

# function to print date timestamp
def print_date_time():
  tz_NY = pytz.timezone('Asia/Kolkata')
  datetime_NY = datetime.datetime.now(tz_NY)
  print("Run date time (IST):", datetime_NY.strftime("%Y-%m-%d %H:%M:%S"))

In [4]:
# function to get booked and reserved amount
def get_amt():
  # fetch the JSON data from the URL
  url = "https://raw.githubusercontent.com/ankit-rathi/Tradevesting_v1/main/data/myPortfolioAmts.json"
  response = requests.get(url)
  pf_amts = response.json()  # parse the JSON data

  # extract values from the JSON
  py_booked_amt_dm = pf_amts["py_booked_amt_dm"]
  py_booked_amt_sv = pf_amts["py_booked_amt_sv"]
  cy_booked_amt_dm = pf_amts["cy_booked_amt_dm"]
  cy_booked_amt_sv = pf_amts["cy_booked_amt_sv"]
  reserve_amt_dm = pf_amts["reserve_amt_dm"]
  reserve_amt_sv = pf_amts["reserve_amt_sv"]

  # perform calculations
  py_booked_amt = py_booked_amt_dm + py_booked_amt_sv
  cy_booked_amt = cy_booked_amt_dm + cy_booked_amt_sv
  reserve_amt = reserve_amt_dm + reserve_amt_sv
  total_booked_amt = py_booked_amt + cy_booked_amt

  return total_booked_amt, reserve_amt, cy_booked_amt, py_booked_amt

gen_output = 0

In [5]:
# function to format the amount
def format_amt(number):
    abs_number = abs(number)

    if abs_number >= 1_00_00_000:  # Crores
        formatted_amt = f"{number / 1_00_00_000:.2f} C"
    elif abs_number >= 1_00_000:  # Lakhs
        formatted_amt = f"{number / 1_00_000:.2f} L"
    elif abs_number >= 1_000:  # Thousands
        formatted_amt = f"{number / 1_000:.2f} K"
    else:
        formatted_amt = f"{number:.2f}"

    return formatted_amt

# function to set start and end date
def get_start_end_date():
  start_date = (datetime.date.today() + datetime.timedelta(days=-365)).strftime('%Y-%m-%d')
  end_date = (datetime.date.today() + datetime.timedelta(days=1)).strftime('%Y-%m-%d')
  return start_date, end_date

# function to fetch my portfolio csv
def get_mypfs_df():
  mypfs_df = pd.read_csv('https://raw.githubusercontent.com/ankit-rathi/Tradevesting_v1/main/data/myPortfolioStocks.csv')
  return mypfs_df

# function to fetch my prospects csv
def get_mypps_df():
  mypps_df = pd.read_csv('https://raw.githubusercontent.com/ankit-rathi/Tradevesting_v1/main/data/myProspectsScrips.csv')
  return mypps_df

# function to fetch screener data
def get_myscreen_df():
  myscreen_df = pd.read_csv('https://raw.githubusercontent.com/ankit-rathi/Tradevesting_v1/main/data/myScreenerDB.csv')
  return myscreen_df

# function to fetch momentum data
def get_myinvmt_df():
  myinvmt_df = pd.read_csv('https://raw.githubusercontent.com/ankit-rathi/Tradevesting_v1/main/data/myInvestments.csv')
  return myinvmt_df

# function to get the stock ids
def get_stock_ids(df_pf):
  stock_n100 = df_pf['Symbol'].unique()

  exclude = ['CADILAHC','MMTC', 'MASFIN']

  stock_ids = df_pf[~df_pf['Symbol'].isin(exclude) ]['Symbol'].unique()

  #mypf = mypf[mypf.Forecast.notnull()]
  #stock_ids = mypf['Symbol'].unique()

  #stock_ids.sort()
  return stock_ids

# get features from screener data
def get_screener_features():
  myscreen_df = get_myscreen_df()
  cols = ['Symbol', 'EPS', 'MedPE', 'ROCE%', 'ROE%', 'CapType']
  return myscreen_df[cols]

# get relative strength
def get_relative_strength(stock_list):

    # Dictionary to store stock tickers and their corresponding percentage price change
    stock_changes = {}

    # Loop through each stock and fetch its price data
    for stock in stock_list:
        try:
            # Download the stock data for the given date range
            stock_data = yfin.Ticker(stock + '.NS').history(period='1mo', interval='1d')[map(str.title, ['open', 'close', 'low', 'high', 'volume'])]

            # Calculate the percentage change for the stock
            if len(stock_data) > 0:
                start_price = stock_data['Close'].iloc[0]
                end_price = stock_data['Close'].iloc[-1]
                percent_change = round(((end_price - start_price) / start_price) * 100, 2)
                stock_changes[stock] = percent_change
            else:
                stock_changes[stock] = np.nan  # If no data is available, set to NaN

        except Exception as e:
            print(f"Error fetching data for {stock}: {e}")
            stock_changes[stock] = np.nan

    # Create a DataFrame with stock tickers and their percentage changes
    df = pd.DataFrame(list(stock_changes.items()), columns=['Symbol', 'Percent_Change'])

    # Drop any stocks with missing data (NaN values)
    df = df.dropna()

    # Calculate the percentile rank based on percentage change
    df['RSP'] = round(df['Percent_Change'].rank(pct=True) * 100, 2)
    cols = ['Symbol', 'RSP']
    df = df[cols]
    # Sort by percentile rank (optional)
    df = df.sort_values(by='RSP', ascending=False).reset_index(drop=True)

    return df

In [6]:
# function to get stock technicals
def stock_prec_dev(stock_symbol):
    #stock_symbol = 'ULTRACEMCO.NS'
    short_window = 20
    mid_window = 50
    long_window = 200
    moving_avg = 'SMA'

    start = datetime.datetime(*map(int, start_date.split('-')))
    end = datetime.datetime(*map(int, end_date.split('-')))

    stock_df = yfin.Ticker(stock_symbol + '.NS').history(period='max', interval='1d')[map(str.title, ['open', 'close', 'low', 'high', 'volume'])]

    stock_df['Max'] = round(max(stock_df['Close']),2)
    stock_df = stock_df[(stock_df.index <= end_date) & (stock_df.index >= start_date)]
    stock_df['200_SMA'] = round(stock_df['Close'].rolling(window = 200, min_periods = 1).mean(),0)
    stock_df['Dev%_200'] = round((stock_df['Close'] - stock_df['200_SMA'])*100/stock_df['200_SMA'],2)
    stock_df.dropna(axis = 0, inplace = True) # remove any null rows

    stock_df['20_SMA'] = stock_df['Close'].rolling(window=20).mean()
    stock_df['50_SMA'] = stock_df['Close'].rolling(window=50).mean()
    stock_df['Symbol'] = stock_symbol

    stock_df['Close'] = round(stock_df['Close'],2)
    stock_df['Min'] = round(min(stock_df['Close']),2)
    stock_df['RSI_14'] = ta.momentum.RSIIndicator(close=stock_df['Close'], window=14).rsi()
    stock_df['RSI_14'] = round(stock_df['RSI_14'],0)
    stock_df['Prev_Close'] = stock_df['Close'].shift(1)
    stock_df.drop(['Open', 'Low', 'High', 'Volume'], axis=1, inplace=True)
    stock_df = stock_df.tail(1)

    max_SMA = max(stock_df['20_SMA'].item(), stock_df['50_SMA'].item(), stock_df['200_SMA'].item())
    min_SMA = min(stock_df['20_SMA'].item(), stock_df['50_SMA'].item(), stock_df['200_SMA'].item())
    ABS_Spread = max_SMA - min_SMA
    stock_df['Spread%'] = round((ABS_Spread / stock_df['200_SMA'].item()) * 100,2)

    return stock_df

# function to compute stock attributes
def get_common_features(stock_ids, df_mypf):

  df_prec_dev = pd.DataFrame()
  df_tmp = get_screener_features()
  df_rs = get_relative_strength(stock_ids)

  for stock_id in stock_ids:
      tmp = stock_prec_dev(stock_id)
      tmp = tmp.reset_index()
      df_prec_dev = pd.concat([df_prec_dev, tmp], ignore_index = True)
  df_prec_dev = pd.merge(df_prec_dev, df_mypf, on= 'Symbol')
  df_prec_dev = pd.merge(df_prec_dev, df_tmp, on= 'Symbol', how='left')
  df_prec_dev = pd.merge(df_prec_dev, df_rs, on= 'Symbol', how='left')
  #print(df_prec_dev.columns)
  df_prec_dev['Curr_PE'] = round(df_prec_dev['Close']/df_prec_dev['EPS'],1)
  df_prec_dev['Dev%_PE'] = round((df_prec_dev['Curr_PE'] - df_prec_dev['MedPE'])*100/df_prec_dev['MedPE'],2)
  df_prec_dev['Conviction'] = df_prec_dev['Conviction'] + '-' + df_prec_dev['CapType']
  return df_prec_dev

# function to arrange stock features
def arrange_features(df_stocks, common_cols, diff_cols):
  df_stocks_common = df_stocks[common_cols].drop_duplicates()
  df_stocks_diff = df_stocks[diff_cols]
  df_stocks_diff['Investment'] = df_stocks_diff['AvgCost'] * df_stocks_diff['Shares']
  df_stocks_diff = df_stocks_diff.groupby(['Symbol'])[['Shares', 'Investment']].aggregate(['sum']).reset_index()
  df_stocks_diff.columns = ['Symbol', 'Shares', 'Investment']
  df_stocks_diff['AvgCost'] = round(df_stocks_diff['Investment']/df_stocks_diff['Shares'],2)
  df_stocks = pd.merge(df_stocks_diff, df_stocks_common, on='Symbol')
  return df_stocks

# plot fact distribution across dimension
def plot_pie_chart(df, dimension, fact):
  # grouping the data by category and calculating the sum of fact for each type
  grouped_data = df.groupby(dimension)[fact].sum()

  # sorting the grouped data in descending order
  grouped_data = grouped_data.sort_values(ascending=False)

  # creating a pie chart
  grouped_data.plot.pie(autopct='%1.1f%%', startangle=90, figsize=(6, 6))

  # adding a title and displaying the plot
  plt.title(f'{dimension} {fact} Distribution')
  plt.ylabel('')  # To hide the y-label
  plt.show()

In [7]:
# function to get portfolio features

def get_portfolio_features(df_common_features):

  print_date_time()
  print('-------------------')

  #df_common_features["Target"] = df_common_features["Target"].fillna(df_common_features["Max"])
  df_common_features['NTT'] = np.where(df_common_features['Strategy']== 'NTT', df_common_features["Target"], df_common_features['Max'])
  df_common_features['LTT'] = np.where(df_common_features['Strategy']== 'BTT', df_common_features["Target"], df_common_features['Max'])
  df_common_features['BOL'] = df_common_features['Min']

  tmp_df = df_common_features[df_common_features['Symbol'].isin(mypf_df[mypf_df['InPortfolio'] != 'NA'].Symbol.values)]
  print('qualified stocks: '+str(len(tmp_df['Symbol'].unique())))
  tmp_df1 = tmp_df[tmp_df['LatestQtr'] == 1]
  print('with latest results: '+str(len(tmp_df1['Symbol'].unique())))
  tmp_df1 = tmp_df1[tmp_df1['StarStock'] == 1]
  print('still star stocks: '+str(len(tmp_df1['Symbol'].unique())))
  tmp_df['Investment'] = tmp_df['AvgCost'] * tmp_df['Shares']
  tmp_df['Current'] = round(tmp_df['Close'] * tmp_df['Shares'],0)
  tmp_df['Previous'] = tmp_df['Prev_Close'] * tmp_df['Shares']
  tmp_df['EstimatedST'] = tmp_df['NTT'] * tmp_df['Shares']
  tmp_df['EstimatedLT'] = tmp_df['LTT'] * tmp_df['Shares']
  tmp_df['Current P/L'] = round((tmp_df['Current'] - tmp_df['Investment']),0)
  tmp_df['Today P/L%'] = round((tmp_df['Current'] - tmp_df['Previous'])*100/tmp_df['Previous'],2)
  tmp_df['Current P/L%'] = round((tmp_df['Current'] - tmp_df['Investment'])*100/tmp_df['Investment'],2)
  tmp_df['EstimatedST P/L%'] = round((tmp_df['EstimatedST'] - tmp_df['Investment'])*100/tmp_df['Investment'],2)
  tmp_df['EstimatedLT P/L%'] = round((tmp_df['EstimatedLT'] - tmp_df['Investment'])*100/tmp_df['Investment'],2)
  tmp_df['NTT%'] = round((tmp_df['NTT'] - tmp_df['Close'])*100/tmp_df['Close'],2)
  tmp_df['LTT%'] = round((tmp_df['LTT'] - tmp_df['Close'])*100/tmp_df['Close'],2)
  tmp_df['Gained%'] = round((tmp_df['Close'] - tmp_df['BOL'])*100/tmp_df['BOL'],2)
  investment = round(sum(tmp_df['AvgCost']*tmp_df['Shares']),0)
  current = round(sum(tmp_df['Close']*tmp_df['Shares']),0)
  tmp_df['InitAlloc%'] = round(tmp_df['Investment']*100/investment,2)
  tmp_df['CurrAlloc%'] = round(tmp_df['Current']*100/current,2)
  tmp_df['FTT'] = tmp_df['LTT']
  tmp_df.loc[tmp_df['Strategy'] == 'NTT', 'FTT'] = tmp_df['NTT']
  tmp_df['FTT%'] = tmp_df['LTT%']
  tmp_df.loc[tmp_df['Strategy'] == 'NTT', 'FTT%'] = tmp_df['NTT%']
  tmp_df['FTT Amt'] = round(tmp_df['FTT%'] * tmp_df['Current']/100,0)
  tmp_df['OTT%'] = round((tmp_df['FTT'] - tmp_df['AvgCost'])*100/tmp_df['AvgCost'],2)
  tmp_df['RRR Ind'] = round(tmp_df['Current P/L']/tmp_df['FTT Amt'],2)
  tmp_df['Risk Ind'] = round(tmp_df['Current P/L%']*tmp_df['CurrAlloc%'],0)

  return tmp_df

# function to print portfolio features
def print_portfolio_stats(df_portfolio_features, myinvmt_df):
  from pyxirr import xirr

  total_booked_amt, reserve_amt, cy_booked_amt, py_booked_amt = get_amt()

  dates = myinvmt_df['Date'].values
  dates = np.append(dates, datetime.date.today().strftime('%d-%b-%y'))
  investment = myinvmt_df['Investment'].values
  dates= pd.to_datetime(dates)

  current = round(sum(df_portfolio_features['Close']*df_portfolio_features['Shares']),0) + reserve_amt
  investment_xirr = np.append(investment, current)
  cagr = round(xirr(pd.DataFrame({"dates": dates, "amounts": investment_xirr}))*100,2)

  investment = -sum(investment)
  invested = round(sum(df_portfolio_features['AvgCost']*df_portfolio_features['Shares']),0) + reserve_amt
  previous = round(sum(df_portfolio_features['Prev_Close']*df_portfolio_features['Shares']),0) + reserve_amt
  cy_invested = investment + py_booked_amt

  today_pnl_amount = current-previous
  today_pnl_percentage = round((current-previous)*100/previous,2)

  curr_pnl_amount = current-invested
  curr_pnl_percentage = round((curr_pnl_amount)*100/(cy_invested),2)

  cy_pnl_amount = cy_booked_amt + curr_pnl_amount
  cy_pnl_percentage = round((cy_pnl_amount)*100/cy_invested,2)

  overall_pnl_amount = total_booked_amt + curr_pnl_amount
  overall_pnl_percentage = round((overall_pnl_amount)*100/investment,2)

  estimate_st = round(sum(df_portfolio_features['FTT']*df_portfolio_features['Shares']),0)  + reserve_amt
  est_st_pnl_amount = estimate_st-current
  est_st_pnl_percentage = round((est_st_pnl_amount)*100/current,2)

  estimate_lt = round(sum(df_portfolio_features['LTT']*df_portfolio_features['Shares']),0)  + reserve_amt
  est_lt_pnl_amount = estimate_lt-current
  est_lt_pnl_percentage = round((est_lt_pnl_amount)*100/current,2)

  total_profit = round(sum(df_portfolio_features[df_portfolio_features['Current P/L%'] > 0]['Current']) - sum(df_portfolio_features[df_portfolio_features['Current P/L%'] > 0]['Investment']),0)
  total_loss = round(sum(df_portfolio_features[df_portfolio_features['Current P/L%'] < 0]['Current']) - sum(df_portfolio_features[df_portfolio_features['Current P/L%'] < 0]['Investment']),0)

  cy_booked_percentage = round((cy_booked_amt)*100/current,2)
  py_booked_percentage = round((py_booked_amt)*100/investment,2)
  total_booked_percentage = round((total_booked_amt)*100/investment,2)

  print('-------------------')
  print('Initial Investment: ', format_amt(investment))
  print('CY Investment: ', format_amt(cy_invested))
  print('Reserve: ', format_amt(reserve_amt))
  print('Current: ',  format_amt(current))
  print('-------------------')
  print('Today PnL: '+ '{} ({}%)'.format(format_amt(today_pnl_amount), today_pnl_percentage))
  print('Current PnL: '+ '{} ({}%)'.format(format_amt(curr_pnl_amount), curr_pnl_percentage))
  print('CY Booked + Current PnL: '+ '{} ({}%)'.format(format_amt(cy_pnl_amount), cy_pnl_percentage))
  print('-------------------')
  print('Total profit: ', format_amt(total_profit))
  print('Total loss: ', format_amt(total_loss))
  print('-------------------')
  print('Total Booked + Current PnL: '+ '{} ({}%)'.format(format_amt(overall_pnl_amount), overall_pnl_percentage))
  print('Total Booked PnL: '+ '{} ({}%)'.format(format_amt(total_booked_amt), total_booked_percentage))
  print('Curr Year Booked PnL: '+ '{} ({}%)'.format(format_amt(cy_booked_amt), cy_booked_percentage))
  print('Prev Year Booked PnL: '+ '{} ({}%)'.format(format_amt(py_booked_amt), py_booked_percentage))
  print('===================')
  print('Est FTT: ',  format_amt(estimate_st))
  print('Est FTT PnL: '+ '{} ({}%)'.format(format_amt(est_st_pnl_amount), est_st_pnl_percentage))

  print('===================')
  print('Deployed: ', format_amt(investment))

  print('Current: ', format_amt(current))

  print('CAGR/XIRR %: '+'{}%'.format(cagr))

In [8]:
# get start and end date
start_date, end_date = get_start_end_date()

# get portfolio and prospects data
mypfs_df = get_mypfs_df()
mypps_df = get_mypps_df()
myinvmt_df = get_myinvmt_df()

# merge above datasets
mypf_df = pd.merge(mypfs_df, mypps_df, on="Symbol")

# seggregate dm and sv portfolio
dm_pf = mypf_df[mypf_df['InPortfolio'] == 'DM']
sv_pf = mypf_df[mypf_df['InPortfolio'] == 'SV']

# build portfolio stock dataframe
dm_stocks = get_stock_ids(dm_pf)
sv_stocks = get_stock_ids(sv_pf)
df_stocks = pd.concat([dm_pf,sv_pf], ignore_index = True)

# arrange common and diff stock features
common_cols = ['Symbol', 'Target', 'Criteria', 'Strategy', 'CumlRnk', 'LatestQtr', 'StarStock', 'Conviction', 'Category', 'InFolio', 'XIRR', 'MBQ']
diff_cols = ['Symbol', 'AvgCost', 'Shares']
df_stocks = arrange_features(df_stocks, common_cols, diff_cols)

# get common features
stock_ids = df_stocks['Symbol'].values
df_common_features = get_common_features(stock_ids, df_stocks)

df_common_features.reset_index(drop=True, inplace=True)
df_common_features.drop(['Date'], axis=1, inplace=True)
# get and print portfolio features
df_portfolio_features = get_portfolio_features(df_common_features)

print_portfolio_stats(df_portfolio_features, myinvmt_df)

df = df_portfolio_features
#plot_pie_chart(df, 'CapType', 'Current')
list_ox40n = list(df[df['MBQ'].str.contains('OX40N', na=False)]['Symbol'].values)

Run date time (IST): 2026-03-20 15:29:16
-------------------
qualified stocks: 86
with latest results: 26
still star stocks: 16
-------------------
Initial Investment:  1.36 C
CY Investment:  1.62 C
Reserve:  1.61 K
Current:  1.31 C
-------------------
Today PnL: 52.13 K (0.4%)
Current PnL: -45.68 L (-28.11%)
CY Booked + Current PnL: -29.79 L (-18.33%)
-------------------
Total profit:  63.94 K
Total loss:  -46.32 L
-------------------
Total Booked + Current PnL: -2.81 L (-2.07%)
Total Booked PnL: 42.87 L (31.64%)
Curr Year Booked PnL: 15.89 L (12.09%)
Prev Year Booked PnL: 26.98 L (19.91%)
===================
Est FTT:  2.48 C
Est FTT PnL: 1.16 C (88.59%)
===================
Deployed:  1.36 C
Current:  1.31 C
CAGR/XIRR %: -1.5%

In [9]:
# top 5 near their targets
cols = ['Symbol', 'Today P/L%', 'Current P/L%', 'FTT%', 'OTT%', 'FTT Amt', 'Current P/L', 'Current', 'FTT', 'Dev%_PE', 'RSI_14','Conviction', 'Spread%',  'CumlRnk', 'RRR Ind', 'CurrAlloc%', 'Gained%', 'Criteria', 'Strategy', 'Category']
df_tmp = df_portfolio_features[~df_portfolio_features['Symbol'].isin(['ENRIN','BLUSPRING','DIGITIDE'])]
df_tmp = df_tmp.sort_values(by = 'FTT Amt', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
50,MASFIN,3.11,-7.53,31.47,21.57,28512.0,-7380.0,90600.0,397.04,-20.05,44.0,H-SC,1.67,167.0,-0.26,0.69,23.57,XR,ATH,FINANCE
77,TTKPRESTIG,-4.03,-39.56,65.61,0.09,39962.0,-39869.0,60908.0,770.00,41.30,38.0,M-SC,18.09,250.0,-1.00,0.46,2.91,OX40N,NTT,DURABLES
37,ICICIGI,-0.85,-5.88,26.79,19.34,50459.0,-11758.0,188351.0,2252.93,-20.81,30.0,X-MC,2.68,66.0,-0.23,1.43,4.12,X40,ATH,INSURANCE
2,ABBOTINDIA,0.77,-10.36,31.72,18.07,50854.0,-18535.0,160320.0,35195.00,-23.63,48.0,X-MC,10.66,58.0,-0.36,1.22,1.64,X40,ATH,PHARMA
67,SONACOMS,1.44,-12.48,58.93,39.09,52172.0,-12627.0,88532.0,804.02,-30.60,48.0,M-MC,8.16,193.0,-0.24,0.67,25.24,AR,ATH,AUTO

In [10]:
# top 5 today
df_tmp = df_portfolio_features.sort_values(by = 'Today P/L%', ascending=False)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
30,HAPPSTMNDS,7.94,-49.92,269.12,84.85,172732.0,-63981.0,64184.0,1480.71,-40.49,56.0,H-SC,27.35,152.0,-0.37,0.49,18.86,AR,ATH,IT
8,AWL,7.22,-34.92,156.61,67.02,363183.0,-124406.0,231903.0,485.00,-65.01,52.0,X-SC,25.63,81.0,-0.34,1.76,9.69,XY24,NTT,FMCG
72,TATAELXSI,4.76,-39.02,116.50,32.03,93663.0,-51438.0,80397.0,9161.00,-23.72,38.0,H-SC,20.12,158.0,-0.55,0.61,4.76,OX40N,NTT,IT
80,VALIANTORG,3.83,-44.02,211.11,74.15,193339.0,-72023.0,91582.0,838.00,-264.69,67.0,H-SC,28.55,145.0,-0.37,0.70,36.29,XR,NTT,CHEMICALS
26,FINCABLES,3.55,11.46,86.54,107.91,142410.0,16916.0,164560.0,1641.55,0.46,54.0,M-SC,8.32,220.0,0.12,1.25,23.80,OX40N,ATH,CABLES

In [11]:
# bottom 5 today
df_tmp = df_portfolio_features.sort_values(by = 'Today P/L%', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
55,RAJESHEXPO,-4.99,-81.88,452.12,0.07,112406.0,-112315.0,24862.0,518.00,811.62,17.0,L-SC,30.99,268.0,-1.00,0.19,0.00,OX40N,NTT,JEWELLERY
77,TTKPRESTIG,-4.03,-39.56,65.61,0.09,39962.0,-39869.0,60908.0,770.00,41.30,38.0,M-SC,18.09,250.0,-1.00,0.46,2.91,OX40N,NTT,DURABLES
69,SURYODAY,-3.03,-29.60,74.77,23.03,94257.0,-53009.0,126062.0,216.00,38.16,43.0,H-SC,6.70,166.0,-0.56,0.96,23.21,XR,NTT,BANKS
61,ROUTE,-2.35,-64.64,375.62,68.16,176714.0,-86020.0,47046.0,2215.45,-71.41,37.0,H-SC,36.04,141.0,-0.49,0.36,4.57,SR,ATH,IT
38,ICICIPRULI,-2.34,-9.03,43.70,30.73,78318.0,-17787.0,179218.0,790.00,-33.41,21.0,X-MC,3.42,78.0,-0.23,1.36,2.53,X40,ATH,INSURANCE

In [12]:
# top 5 to exit based on CumlRnk
df_tmp = df_portfolio_features[~df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])]
df_tmp = df_tmp[(df_tmp['Current P/L%'] > -1) & (df_tmp['Current P/L%'] < 1)].sort_values(by = 'CumlRnk', ascending=False)
df_tmp[cols].head()

Empty DataFrame
Columns: [Symbol, Today P/L%, Current P/L%, FTT%, OTT%, FTT Amt, Current P/L, Current, FTT, Dev%_PE, RSI_14, Conviction, Spread%, CumlRnk, RRR Ind, CurrAlloc%, Gained%, Criteria, Strategy, Category]
Index: []

In [13]:
# OX40N stocks to exit
df_tmp = df_portfolio_features[(df_portfolio_features['Symbol'].isin(list_ox40n))].sort_values(by = 'Current P/L%', ascending=False)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
26,FINCABLES,3.55,11.46,86.54,107.91,142410.0,16916.0,164560.0,1641.55,0.46,54.0,M-SC,8.32,220.0,0.12,1.25,23.80,OX40N,ATH,CABLES
66,SIS,-1.62,-37.18,93.02,21.26,64886.0,-41277.0,69755.0,528.00,1628.50,32.0,H-SC,13.69,168.0,-0.64,0.53,0.53,OX40N,NTT,MISC
18,CERA,-0.34,-38.00,99.81,23.89,108861.0,-66835.0,109068.0,9475.00,-40.10,46.0,H-SC,18.45,153.0,-0.61,0.83,4.81,OX40N,NTT,CERAMICS
72,TATAELXSI,4.76,-39.02,116.50,32.03,93663.0,-51438.0,80397.0,9161.00,-23.72,38.0,H-SC,20.12,158.0,-0.55,0.61,4.76,OX40N,NTT,IT
77,TTKPRESTIG,-4.03,-39.56,65.61,0.09,39962.0,-39869.0,60908.0,770.00,41.30,38.0,M-SC,18.09,250.0,-1.00,0.46,2.91,OX40N,NTT,DURABLES

In [14]:
# top 5 to book for rotation
df_tmp = df_portfolio_features[(df_portfolio_features['Current P/L%'] > 20) ].sort_values(by = 'CumlRnk', ascending=False)
df_tmp[cols].head()

Empty DataFrame
Columns: [Symbol, Today P/L%, Current P/L%, FTT%, OTT%, FTT Amt, Current P/L, Current, FTT, Dev%_PE, RSI_14, Conviction, Spread%, CumlRnk, RRR Ind, CurrAlloc%, Gained%, Criteria, Strategy, Category]
Index: []

In [15]:
# top 5 to monitor for exit
df_tmp = df_portfolio_features[~df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])]
df_tmp = df_tmp[(df_tmp['Current P/L%'] > 0) ].sort_values(by = 'Dev%_PE', ascending=False)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
26,FINCABLES,3.55,11.46,86.54,107.91,142410.0,16916.0,164560.0,1641.55,0.46,54.0,M-SC,8.32,220.0,0.12,1.25,23.80,OX40N,ATH,CABLES
1,ABB,1.41,15.62,25.91,45.57,78370.0,40853.0,302472.0,7934.00,-25.70,60.0,H-MC,13.02,125.0,0.52,2.30,34.32,AR,NTT,ELECTRICAL

In [16]:
# top 5 to book for rotation from weak conviction
df_tmp = df_portfolio_features[~df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])]
df_tmp = df_tmp[~df_tmp['Criteria'].isin(['XY25','XY24','X40', 'X40N'])].sort_values(by = 'RRR Ind', ascending=False)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
1,ABB,1.41,15.62,25.91,45.57,78370.0,40853.0,302472.0,7934.00,-25.70,60.0,H-MC,13.02,125.0,0.52,2.30,34.32,AR,NTT,ELECTRICAL
26,FINCABLES,3.55,11.46,86.54,107.91,142410.0,16916.0,164560.0,1641.55,0.46,54.0,M-SC,8.32,220.0,0.12,1.25,23.80,OX40N,ATH,CABLES
40,INDIAMART,-2.25,-14.77,142.54,106.72,149838.0,-18216.0,105120.0,4810.62,-61.52,32.0,H-SC,10.84,140.0,-0.12,0.80,5.16,AR,ATH,MISC
85,ZYDUSLIFE,1.21,-6.49,45.04,35.63,88266.0,-13602.0,195972.0,1286.17,-18.47,44.0,H-MC,5.30,120.0,-0.15,1.49,9.10,AR,ATH,PHARMA
84,WIPRO,1.37,-21.66,119.90,72.27,159161.0,-36703.0,132745.0,420.00,-29.24,31.0,M-LC,17.00,98.0,-0.23,1.01,1.37,XR,NTT,IT

In [17]:
# top 5 to accumulate based on lowest RSI_14
df_tmp = df_portfolio_features[df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])].sort_values(by = 'RSI_14', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
53,PGHH,-1.83,-27.04,80.93,32.01,126082.0,-57728.0,155792.0,17616.87,-50.62,14.0,X-MC,14.49,57.0,-0.46,1.19,0.00,X40,ATH,FMCG
12,BATAINDIA,2.01,-57.36,217.10,35.20,119108.0,-73807.0,54863.0,2096.00,-28.09,21.0,X-SC,29.91,91.0,-0.62,0.42,2.01,X40,NTT,FOOTWEAR
38,ICICIPRULI,-2.34,-9.03,43.70,30.73,78318.0,-17787.0,179218.0,790.00,-33.41,21.0,X-MC,3.42,78.0,-0.23,1.36,2.53,X40,ATH,INSURANCE
58,RELAXO,1.47,-64.16,325.01,52.31,169070.0,-93140.0,52020.0,1176.00,-61.86,23.0,X-SC,24.49,92.0,-0.55,0.40,1.47,X40N,NTT,FOOTWEAR
34,HDFCBANK,-2.14,-6.55,37.37,28.37,82023.0,-15396.0,219489.0,1073.00,-20.53,24.0,X-LC,10.76,26.0,-0.19,1.67,0.00,X40,BTT,BANKS

In [18]:
# top 5 to accumulate based on Spread and CumlRnk
df_tmp = df_portfolio_features[df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])]
df_tmp = df_tmp[(df_tmp['CumlRnk'] < 100)].sort_values(by = 'Spread%', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
78,UNITDSPR,1.13,-4.25,26.13,20.77,58580.0,-9959.0,224185.0,1644.00,-15.10,41.0,X-MC,1.12,64.0,-0.17,1.71,2.17,X40N,NTT,BREWERIES
37,ICICIGI,-0.85,-5.88,26.79,19.34,50459.0,-11758.0,188351.0,2252.93,-20.81,30.0,X-MC,2.68,66.0,-0.23,1.43,4.12,X40,ATH,INSURANCE
59,RELIANCE,2.22,-9.14,37.90,25.30,69205.0,-18363.0,182600.0,1952.00,-11.57,52.0,X-LC,3.42,21.0,-0.27,1.39,21.91,XY25,BTT,REFINERIES
38,ICICIPRULI,-2.34,-9.03,43.70,30.73,78318.0,-17787.0,179218.0,790.00,-33.41,21.0,X-MC,3.42,78.0,-0.23,1.36,2.53,X40,ATH,INSURANCE
65,SIEMENS,2.08,-15.55,48.63,25.51,76422.0,-28945.0,157150.0,4671.50,31.90,46.0,H-LC,3.52,51.0,-0.38,1.20,15.73,AR,ATH,ELECTRICAL

In [19]:
# top 5 to accumulate based on lowest Gained%
df_tmp = df_portfolio_features[df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])].sort_values(by = 'Gained%', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
51,MEDANTA,-1.29,-14.33,48.38,27.12,73163.0,-25291.0,151226.0,1486.00,-16.93,28.0,X-SC,11.04,87.0,-0.35,1.15,0.0,XY24,NTT,HEALTHCARE
53,PGHH,-1.83,-27.04,80.93,32.01,126082.0,-57728.0,155792.0,17616.87,-50.62,14.0,X-MC,14.49,57.0,-0.46,1.19,0.0,X40,ATH,FMCG
36,HONAUT,-0.32,-26.45,105.74,51.31,149966.0,-51013.0,141825.0,58357.33,-38.90,26.0,X-SC,15.04,90.0,-0.34,1.08,0.0,X40N,ATH,ELECTRICAL
34,HDFCBANK,-2.14,-6.55,37.37,28.37,82023.0,-15396.0,219489.0,1073.00,-20.53,24.0,X-LC,10.76,26.0,-0.19,1.67,0.0,X40,BTT,BANKS
81,VBL,-0.85,-18.96,67.41,35.67,172547.0,-59876.0,255966.0,671.64,-28.42,32.0,X-LC,7.89,13.0,-0.35,1.95,0.0,X40N,ATH,FMCG

In [20]:
# top 5 to accumulate based on lowest CurrAlloc%
df_tmp = df_portfolio_features[df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])].sort_values(by = 'CurrAlloc%', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
58,RELAXO,1.47,-64.16,325.01,52.31,169070.0,-93140.0,52020.0,1176.00,-61.86,23.0,X-SC,24.49,92.0,-0.55,0.40,1.47,X40N,NTT,FOOTWEAR
12,BATAINDIA,2.01,-57.36,217.10,35.20,119108.0,-73807.0,54863.0,2096.00,-28.09,21.0,X-SC,29.91,91.0,-0.62,0.42,2.01,X40,NTT,FOOTWEAR
54,QUESS,-1.05,-27.41,139.56,73.90,108190.0,-29271.0,77522.0,424.00,-60.88,35.0,X-SC,20.53,80.0,-0.27,0.59,1.03,XY24,NTT,MISC
36,HONAUT,-0.32,-26.45,105.74,51.31,149966.0,-51013.0,141825.0,58357.33,-38.90,26.0,X-SC,15.04,90.0,-0.34,1.08,0.00,X40N,ATH,ELECTRICAL
51,MEDANTA,-1.29,-14.33,48.38,27.12,73163.0,-25291.0,151226.0,1486.00,-16.93,28.0,X-SC,11.04,87.0,-0.35,1.15,0.00,XY24,NTT,HEALTHCARE

In [21]:
# top 5 to accumulate based on CumlRnk
df_tmp = df_portfolio_features.sort_values(by = 'CumlRnk', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
45,ITC,0.60,-21.03,50.77,19.06,136379.0,-71545.0,268621.0,452.00,-56.73,35.0,X-LC,17.94,1.0,-0.52,2.04,0.60,X40,NTT,FMCG
73,TCS,1.66,-29.69,80.02,26.57,260641.0,-137553.0,325720.0,4311.59,-40.35,29.0,X-LC,16.66,2.0,-0.53,2.48,1.66,X40,ATH,IT
43,INFY,2.99,-14.41,56.84,34.24,152220.0,-45083.0,267805.0,1972.00,-32.51,37.0,X-LC,14.81,3.0,-0.30,2.04,2.99,X40,NTT,IT
75,TMPV,1.84,-28.30,90.48,36.58,230860.0,-100691.0,255150.0,600.00,-84.72,35.0,X-LC,5.01,4.0,-0.44,1.94,1.84,XY24,NTT,AUTO
33,HCLTECH,2.07,-13.11,42.52,23.83,89380.0,-31717.0,210207.0,1908.19,-8.60,38.0,X-LC,11.52,8.0,-0.35,1.60,2.07,X40,ATH,IT

In [22]:
# top 5 for average up
df_tmp = df_portfolio_features[(df_portfolio_features['Dev%_200'] > 5)].sort_values(by = 'CurrAlloc%', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
67,SONACOMS,1.44,-12.48,58.93,39.09,52172.0,-12627.0,88532.0,804.02,-30.60,48.0,M-MC,8.16,193.0,-0.24,0.67,25.24,AR,ATH,AUTO
26,FINCABLES,3.55,11.46,86.54,107.91,142410.0,16916.0,164560.0,1641.55,0.46,54.0,M-SC,8.32,220.0,0.12,1.25,23.80,OX40N,ATH,CABLES
1,ABB,1.41,15.62,25.91,45.57,78370.0,40853.0,302472.0,7934.00,-25.70,60.0,H-MC,13.02,125.0,0.52,2.30,34.32,AR,NTT,ELECTRICAL

In [23]:
# top 5 RSP
df_tmp = df_portfolio_features.sort_values(by = 'RSP', ascending=False)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
26,FINCABLES,3.55,11.46,86.54,107.91,142410.0,16916.0,164560.0,1641.55,0.46,54.0,M-SC,8.32,220.0,0.12,1.25,23.80,OX40N,ATH,CABLES
80,VALIANTORG,3.83,-44.02,211.11,74.15,193339.0,-72023.0,91582.0,838.00,-264.69,67.0,H-SC,28.55,145.0,-0.37,0.70,36.29,XR,NTT,CHEMICALS
30,HAPPSTMNDS,7.94,-49.92,269.12,84.85,172732.0,-63981.0,64184.0,1480.71,-40.49,56.0,H-SC,27.35,152.0,-0.37,0.49,18.86,AR,ATH,IT
1,ABB,1.41,15.62,25.91,45.57,78370.0,40853.0,302472.0,7934.00,-25.70,60.0,H-MC,13.02,125.0,0.52,2.30,34.32,AR,NTT,ELECTRICAL
2,ABBOTINDIA,0.77,-10.36,31.72,18.07,50854.0,-18535.0,160320.0,35195.00,-23.63,48.0,X-MC,10.66,58.0,-0.36,1.22,1.64,X40,ATH,PHARMA

In [24]:
# Top N allocation
df_tmp = df_portfolio_features.sort_values(by = 'CurrAlloc%', ascending=False)
top_n_values = [10, 25, 50]

sum_df = pd.DataFrame({
    'Top_N': top_n_values,
    'Sum_Alloc%': [df_tmp['CurrAlloc%'].head(n).sum() for n in top_n_values]
})

sum_df

   Top_N  Sum_Alloc%
0     10       20.67
1     25       45.60
2     50       77.94

In [25]:
# market-cap-wise allocation
df_tmp = df_portfolio_features[cols]
df_tmp.groupby(df_tmp['Conviction'].str[-2:])['CurrAlloc%'].sum().sort_values(ascending=False)

Conviction
SC    44.56
MC    30.09
LC    25.36
Name: CurrAlloc%, dtype: float64

In [26]:
# criteria-wise allocation
df_portfolio_features.groupby('Criteria')['CurrAlloc%'].sum().sort_values(ascending=False)

Criteria
XY24     26.98
X40      25.40
X40N     15.11
AR        9.23
XR        8.39
XY25      7.31
OX40N     6.81
SR        0.78
Name: CurrAlloc%, dtype: float64

In [27]:
# conviction-wise allocation
df_portfolio_features.groupby('Conviction')['CurrAlloc%'].sum().sort_values(ascending=False)

Conviction
X-LC    23.15
X-MC    22.59
H-SC    21.60
X-SC    12.29
M-SC    10.13
H-MC     5.09
M-MC     2.05
H-LC     1.20
M-LC     1.01
L-SC     0.54
L-MC     0.36
Name: CurrAlloc%, dtype: float64

In [28]:
# sector-wise stats
df_tmp = df_portfolio_features.groupby('Category')[['CurrAlloc%', 'Current', 'Current P/L', 'FTT Amt']].sum().sort_values(by=['Current', 'Current P/L'], ascending=False)
df_tmp['Current P/L%'] = round(df_tmp['Current P/L'] * 100 / df_tmp['Current'], 2)
df_tmp['FTT%'] = round(df_tmp['FTT Amt'] * 100 / df_tmp['Current'], 2)
cols = ['CurrAlloc%', 'Current P/L%', 'FTT%']
df_tmp[cols].sort_values(by=['CurrAlloc%'], ascending=False)

               CurrAlloc%  Current P/L%    FTT%
Category
FMCG                15.10        -25.80   70.47
FINANCE             13.06        -25.14   76.14
IT                  11.78        -45.64  119.75
MISC                 6.94        -47.08  110.97
ELECTRICAL           6.63        -11.30   53.91
PAINTS               5.03        -48.68   74.50
INSURANCE            4.65        -10.76   48.66
BANKS                4.61        -27.25   91.85
PHARMA               4.15         -7.63   41.51
AUTO                 3.69        -34.76   88.23
AC                   2.06        -18.53   50.67
HEALTHCARE           1.89        -43.67   81.17
DURABLES             1.81        -61.89  101.28
TRAVEL               1.81        -88.20  182.44
FOOTWEAR             1.79        -88.20  163.66
BREWERIES            1.71         -4.44   26.13
APPARELS             1.71        -19.72   60.56
REALTY               1.44        -17.19   36.45
REFINERIES           1.39        -10.06   37.90
CERAMICS             1.38        -69.16  120.55
CEMENT               1.27        -60.86  181.21
CABLES               1.25         10.28   86.54
CHEMICALS            1.12        -79.90  226.68
ENGINEERING          1.09        -69.24  146.65
JEWELLERY            1.07       -126.99  205.85
ENTERTAINMENT        0.77        -92.39  207.13
TEXTILES             0.46        -54.28   98.27
HOTELS               0.35       -148.49  236.13

In [29]:
# money to be made criteria-wise
df_portfolio_features.groupby('Criteria')['FTT Amt'].agg(['sum', 'count']).sort_values(by='sum', ascending=False)

                sum  count
Criteria
XY24      4049936.0     21
X40       1835813.0     16
XR        1390756.0     12
AR        1358191.0     10
X40N      1317170.0     10
OX40N      895903.0     10
XY25       479456.0      5
SR         316732.0      2

In [30]:
# money to be made conviction-wise
df_portfolio_features.groupby('Conviction')['FTT Amt'].agg(['sum', 'count']).sort_values(by='sum', ascending=False)

                  sum  count
Conviction
H-SC        3953632.0     24
X-MC        1765523.0     15
X-LC        1732887.0     13
M-SC        1586755.0     14
X-SC        1567574.0     10
H-MC         409686.0      3
L-SC         220308.0      2
M-LC         159161.0      1
M-MC         116076.0      2
H-LC          76422.0      1
L-MC          55933.0      1

In [31]:
# money to be made criteria and conviction-wise
df_portfolio_features.groupby(['Conviction', 'Criteria'])['FTT Amt'].agg(['sum', 'count']).sort_values(by='sum', ascending=False)

                           sum  count
Conviction Criteria
H-SC       XY24      1382797.0      6
           AR         984515.0      5
X-LC       X40        933266.0      7
M-SC       XY24       926640.0      6
H-SC       XR         876923.0      7
X-SC       XY24       846577.0      4
X-MC       X40        693423.0      7
           X40N       534860.0      4
X-SC       X40N       511873.0      4
H-SC       OX40N      392665.0      4
M-SC       OX40N      390832.0      5
X-LC       XY24       377079.0      2
H-SC       SR         316732.0      2
X-MC       XY24       273793.0      2
X-LC       X40N       270437.0      2
X-MC       XY25       263447.0      2
H-MC       XY24       243050.0      1
X-SC       X40        209124.0      2
M-SC       XR         190837.0      2
H-MC       AR         166636.0      2
M-LC       XR         159161.0      1
X-LC       XY25       152105.0      2
L-SC       OX40N      112406.0      1
           XR         107902.0      1
M-SC       AR          78446.0      1
H-LC       AR          76422.0      1
M-MC       XY25        63904.0      1
L-MC       XR          55933.0      1
M-MC       AR          52172.0      1

In [32]:
# notebook execution time

end_time = time.time()
execution_time = round(end_time - start_time, 0)
print(f"Notebook execution time: {execution_time} seconds")

Notebook execution time: 32.0 seconds