<a href="https://colab.research.google.com/github/ankit-rathi/Quantvesting_v2/blob/main/myStocks_Portfolio_Analysis.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
'''
!pip install pandas==2.2.2 -qq
!pip install pyxirr -qq
!pip install ta -qq
!pip install yfinance==0.2.59 -qq
'''

'\n!pip install pandas==2.2.2 -qq\n!pip install pyxirr -qq\n!pip install ta -qq\n!pip install yfinance==0.2.59 -qq\n'

In [2]:
# import libraries

import numpy as np
import pandas as pd
import datetime
import warnings
warnings.filterwarnings('ignore')
import yfinance as yfin
import ta
import matplotlib.pyplot as plt
import requests

In [3]:
# notebook start time
import time
import datetime
import pytz

start_time = time.time()

# function to print date timestamp
def print_date_time():
  tz_NY = pytz.timezone('Asia/Kolkata')
  datetime_NY = datetime.datetime.now(tz_NY)
  print("Run date time (IST):", datetime_NY.strftime("%Y-%m-%d %H:%M:%S"))

In [4]:
# function to get booked and reserved amount
def get_amt():
  # fetch the JSON data from the URL
  url = "https://raw.githubusercontent.com/ankit-rathi/Tradevesting_v1/main/data/myPortfolioAmts.json"
  response = requests.get(url)
  pf_amts = response.json()  # parse the JSON data

  # extract values from the JSON
  py_booked_amt_dm = pf_amts["py_booked_amt_dm"]
  py_booked_amt_sv = pf_amts["py_booked_amt_sv"]
  cy_booked_amt_dm = pf_amts["cy_booked_amt_dm"]
  cy_booked_amt_sv = pf_amts["cy_booked_amt_sv"]
  reserve_amt_dm = pf_amts["reserve_amt_dm"]
  reserve_amt_sv = pf_amts["reserve_amt_sv"]

  # perform calculations
  py_booked_amt = py_booked_amt_dm + py_booked_amt_sv
  cy_booked_amt = cy_booked_amt_dm + cy_booked_amt_sv
  reserve_amt = reserve_amt_dm + reserve_amt_sv
  total_booked_amt = py_booked_amt + cy_booked_amt

  return total_booked_amt, reserve_amt, cy_booked_amt, py_booked_amt

gen_output = 0

In [5]:
# function to format the amount
def format_amt(number):
    abs_number = abs(number)

    if abs_number >= 1_00_00_000:  # Crores
        formatted_amt = f"{number / 1_00_00_000:.2f} C"
    elif abs_number >= 1_00_000:  # Lakhs
        formatted_amt = f"{number / 1_00_000:.2f} L"
    elif abs_number >= 1_000:  # Thousands
        formatted_amt = f"{number / 1_000:.2f} K"
    else:
        formatted_amt = f"{number:.2f}"

    return formatted_amt

# function to set start and end date
def get_start_end_date():
  start_date = (datetime.date.today() + datetime.timedelta(days=-365)).strftime('%Y-%m-%d')
  end_date = (datetime.date.today() + datetime.timedelta(days=1)).strftime('%Y-%m-%d')
  return start_date, end_date

# function to fetch my portfolio csv
def get_mypfs_df():
  mypfs_df = pd.read_csv('https://raw.githubusercontent.com/ankit-rathi/Tradevesting_v1/main/data/myPortfolioStocks.csv')
  return mypfs_df

# function to fetch my prospects csv
def get_mypps_df():
  mypps_df = pd.read_csv('https://raw.githubusercontent.com/ankit-rathi/Tradevesting_v1/main/data/myProspectsScrips.csv')
  return mypps_df

# function to fetch screener data
def get_myscreen_df():
  myscreen_df = pd.read_csv('https://raw.githubusercontent.com/ankit-rathi/Tradevesting_v1/main/data/myScreenerDB.csv')
  return myscreen_df

# function to fetch momentum data
def get_myinvmt_df():
  myinvmt_df = pd.read_csv('https://raw.githubusercontent.com/ankit-rathi/Tradevesting_v1/main/data/myInvestments.csv')
  return myinvmt_df

# function to get the stock ids
def get_stock_ids(df_pf):
  stock_n100 = df_pf['Symbol'].unique()

  exclude = ['CADILAHC','MMTC', 'MASFIN']

  stock_ids = df_pf[~df_pf['Symbol'].isin(exclude) ]['Symbol'].unique()

  #mypf = mypf[mypf.Forecast.notnull()]
  #stock_ids = mypf['Symbol'].unique()

  #stock_ids.sort()
  return stock_ids

# get features from screener data
def get_screener_features():
  myscreen_df = get_myscreen_df()
  cols = ['Symbol', 'EPS', 'MedPE', 'ROCE%', 'ROE%', 'CapType']
  return myscreen_df[cols]

# get relative strength
def get_relative_strength(stock_list):

    # Dictionary to store stock tickers and their corresponding percentage price change
    stock_changes = {}

    # Loop through each stock and fetch its price data
    for stock in stock_list:
        try:
            # Download the stock data for the given date range
            stock_data = yfin.Ticker(stock + '.NS').history(period='1mo', interval='1d')[map(str.title, ['open', 'close', 'low', 'high', 'volume'])]

            # Calculate the percentage change for the stock
            if len(stock_data) > 0:
                start_price = stock_data['Close'].iloc[0]
                end_price = stock_data['Close'].iloc[-1]
                percent_change = round(((end_price - start_price) / start_price) * 100, 2)
                stock_changes[stock] = percent_change
            else:
                stock_changes[stock] = np.nan  # If no data is available, set to NaN

        except Exception as e:
            print(f"Error fetching data for {stock}: {e}")
            stock_changes[stock] = np.nan

    # Create a DataFrame with stock tickers and their percentage changes
    df = pd.DataFrame(list(stock_changes.items()), columns=['Symbol', 'Percent_Change'])

    # Drop any stocks with missing data (NaN values)
    df = df.dropna()

    # Calculate the percentile rank based on percentage change
    df['RSP'] = round(df['Percent_Change'].rank(pct=True) * 100, 2)
    cols = ['Symbol', 'RSP']
    df = df[cols]
    # Sort by percentile rank (optional)
    df = df.sort_values(by='RSP', ascending=False).reset_index(drop=True)

    return df

In [6]:
# function to get stock technicals
def stock_prec_dev(stock_symbol):
    #stock_symbol = 'ULTRACEMCO.NS'
    short_window = 20
    mid_window = 50
    long_window = 200
    moving_avg = 'SMA'

    start = datetime.datetime(*map(int, start_date.split('-')))
    end = datetime.datetime(*map(int, end_date.split('-')))

    stock_df = yfin.Ticker(stock_symbol + '.NS').history(period='max', interval='1d')[map(str.title, ['open', 'close', 'low', 'high', 'volume'])]

    stock_df['Max'] = round(max(stock_df['Close']),2)
    stock_df = stock_df[(stock_df.index <= end_date) & (stock_df.index >= start_date)]
    stock_df['200_SMA'] = round(stock_df['Close'].rolling(window = 200, min_periods = 1).mean(),0)
    stock_df['Dev%_200'] = round((stock_df['Close'] - stock_df['200_SMA'])*100/stock_df['200_SMA'],2)
    stock_df.dropna(axis = 0, inplace = True) # remove any null rows

    stock_df['20_SMA'] = stock_df['Close'].rolling(window=20).mean()
    stock_df['50_SMA'] = stock_df['Close'].rolling(window=50).mean()
    stock_df['Symbol'] = stock_symbol

    stock_df['Close'] = round(stock_df['Close'],2)
    stock_df['Min'] = round(min(stock_df['Close']),2)
    stock_df['RSI_14'] = ta.momentum.RSIIndicator(close=stock_df['Close'], window=14).rsi()
    stock_df['RSI_14'] = round(stock_df['RSI_14'],0)
    stock_df['Prev_Close'] = stock_df['Close'].shift(1)
    stock_df.drop(['Open', 'Low', 'High', 'Volume'], axis=1, inplace=True)
    stock_df = stock_df.tail(1)

    max_SMA = max(stock_df['20_SMA'].item(), stock_df['50_SMA'].item(), stock_df['200_SMA'].item())
    min_SMA = min(stock_df['20_SMA'].item(), stock_df['50_SMA'].item(), stock_df['200_SMA'].item())
    ABS_Spread = max_SMA - min_SMA
    stock_df['Spread%'] = round((ABS_Spread / stock_df['200_SMA'].item()) * 100,2)

    return stock_df

# function to compute stock attributes
def get_common_features(stock_ids, df_mypf):

  df_prec_dev = pd.DataFrame()
  df_tmp = get_screener_features()
  df_rs = get_relative_strength(stock_ids)

  for stock_id in stock_ids:
      tmp = stock_prec_dev(stock_id)
      tmp = tmp.reset_index()
      df_prec_dev = pd.concat([df_prec_dev, tmp], ignore_index = True)
  df_prec_dev = pd.merge(df_prec_dev, df_mypf, on= 'Symbol')
  df_prec_dev = pd.merge(df_prec_dev, df_tmp, on= 'Symbol', how='left')
  df_prec_dev = pd.merge(df_prec_dev, df_rs, on= 'Symbol', how='left')
  #print(df_prec_dev.columns)
  df_prec_dev['Curr_PE'] = round(df_prec_dev['Close']/df_prec_dev['EPS'],1)
  df_prec_dev['Dev%_PE'] = round((df_prec_dev['Curr_PE'] - df_prec_dev['MedPE'])*100/df_prec_dev['MedPE'],2)
  df_prec_dev['Conviction'] = df_prec_dev['Conviction'] + '-' + df_prec_dev['CapType']
  return df_prec_dev

# function to arrange stock features
def arrange_features(df_stocks, common_cols, diff_cols):
  df_stocks_common = df_stocks[common_cols].drop_duplicates()
  df_stocks_diff = df_stocks[diff_cols]
  df_stocks_diff['Investment'] = df_stocks_diff['AvgCost'] * df_stocks_diff['Shares']
  df_stocks_diff = df_stocks_diff.groupby(['Symbol'])[['Shares', 'Investment']].aggregate(['sum']).reset_index()
  df_stocks_diff.columns = ['Symbol', 'Shares', 'Investment']
  df_stocks_diff['AvgCost'] = round(df_stocks_diff['Investment']/df_stocks_diff['Shares'],2)
  df_stocks = pd.merge(df_stocks_diff, df_stocks_common, on='Symbol')
  return df_stocks

# plot fact distribution across dimension
def plot_pie_chart(df, dimension, fact):
  # grouping the data by category and calculating the sum of fact for each type
  grouped_data = df.groupby(dimension)[fact].sum()

  # sorting the grouped data in descending order
  grouped_data = grouped_data.sort_values(ascending=False)

  # creating a pie chart
  grouped_data.plot.pie(autopct='%1.1f%%', startangle=90, figsize=(6, 6))

  # adding a title and displaying the plot
  plt.title(f'{dimension} {fact} Distribution')
  plt.ylabel('')  # To hide the y-label
  plt.show()

In [7]:
# function to get portfolio features

def get_portfolio_features(df_common_features):

  print_date_time()
  print('-------------------')

  #df_common_features["Target"] = df_common_features["Target"].fillna(df_common_features["Max"])
  df_common_features['NTT'] = np.where(df_common_features['Strategy']== 'NTT', df_common_features["Target"], df_common_features['Max'])
  df_common_features['LTT'] = np.where(df_common_features['Strategy']== 'BTT', df_common_features["Target"], df_common_features['Max'])
  df_common_features['BOL'] = df_common_features['Min']

  tmp_df = df_common_features[df_common_features['Symbol'].isin(mypf_df[mypf_df['InPortfolio'] != 'NA'].Symbol.values)]
  print('qualified stocks: '+str(len(tmp_df['Symbol'].unique())))
  tmp_df1 = tmp_df[tmp_df['LatestQtr'] == 1]
  print('with latest results: '+str(len(tmp_df1['Symbol'].unique())))
  tmp_df1 = tmp_df1[tmp_df1['StarStock'] == 1]
  print('still star stocks: '+str(len(tmp_df1['Symbol'].unique())))
  tmp_df['Investment'] = tmp_df['AvgCost'] * tmp_df['Shares']
  tmp_df['Current'] = round(tmp_df['Close'] * tmp_df['Shares'],0)
  tmp_df['Previous'] = tmp_df['Prev_Close'] * tmp_df['Shares']
  tmp_df['EstimatedST'] = tmp_df['NTT'] * tmp_df['Shares']
  tmp_df['EstimatedLT'] = tmp_df['LTT'] * tmp_df['Shares']
  tmp_df['Current P/L'] = round((tmp_df['Current'] - tmp_df['Investment']),0)
  tmp_df['Today P/L%'] = round((tmp_df['Current'] - tmp_df['Previous'])*100/tmp_df['Previous'],2)
  tmp_df['Current P/L%'] = round((tmp_df['Current'] - tmp_df['Investment'])*100/tmp_df['Investment'],2)
  tmp_df['EstimatedST P/L%'] = round((tmp_df['EstimatedST'] - tmp_df['Investment'])*100/tmp_df['Investment'],2)
  tmp_df['EstimatedLT P/L%'] = round((tmp_df['EstimatedLT'] - tmp_df['Investment'])*100/tmp_df['Investment'],2)
  tmp_df['NTT%'] = round((tmp_df['NTT'] - tmp_df['Close'])*100/tmp_df['Close'],2)
  tmp_df['LTT%'] = round((tmp_df['LTT'] - tmp_df['Close'])*100/tmp_df['Close'],2)
  tmp_df['Gained%'] = round((tmp_df['Close'] - tmp_df['BOL'])*100/tmp_df['BOL'],2)
  investment = round(sum(tmp_df['AvgCost']*tmp_df['Shares']),0)
  current = round(sum(tmp_df['Close']*tmp_df['Shares']),0)
  tmp_df['InitAlloc%'] = round(tmp_df['Investment']*100/investment,2)
  tmp_df['CurrAlloc%'] = round(tmp_df['Current']*100/current,2)
  tmp_df['FTT'] = tmp_df['LTT']
  tmp_df.loc[tmp_df['Strategy'] == 'NTT', 'FTT'] = tmp_df['NTT']
  tmp_df['FTT%'] = tmp_df['LTT%']
  tmp_df.loc[tmp_df['Strategy'] == 'NTT', 'FTT%'] = tmp_df['NTT%']
  tmp_df['FTT Amt'] = round(tmp_df['FTT%'] * tmp_df['Current']/100,0)
  tmp_df['OTT%'] = round((tmp_df['FTT'] - tmp_df['AvgCost'])*100/tmp_df['AvgCost'],2)
  tmp_df['RRR Ind'] = round(tmp_df['Current P/L']/tmp_df['FTT Amt'],2)
  tmp_df['Risk Ind'] = round(tmp_df['Current P/L%']*tmp_df['CurrAlloc%'],0)

  return tmp_df

# function to print portfolio features
def print_portfolio_stats(df_portfolio_features, myinvmt_df):
  from pyxirr import xirr

  total_booked_amt, reserve_amt, cy_booked_amt, py_booked_amt = get_amt()

  dates = myinvmt_df['Date'].values
  dates = np.append(dates, datetime.date.today().strftime('%d-%b-%y'))
  investment = myinvmt_df['Investment'].values
  dates= pd.to_datetime(dates)

  current = round(sum(df_portfolio_features['Close']*df_portfolio_features['Shares']),0) + reserve_amt
  investment_xirr = np.append(investment, current)
  cagr = round(xirr(pd.DataFrame({"dates": dates, "amounts": investment_xirr}))*100,2)

  investment = -sum(investment)
  invested = round(sum(df_portfolio_features['AvgCost']*df_portfolio_features['Shares']),0) + reserve_amt
  previous = round(sum(df_portfolio_features['Prev_Close']*df_portfolio_features['Shares']),0) + reserve_amt
  cy_invested = investment + py_booked_amt

  today_pnl_amount = current-previous
  today_pnl_percentage = round((current-previous)*100/previous,2)

  curr_pnl_amount = current-invested
  curr_pnl_percentage = round((curr_pnl_amount)*100/(cy_invested),2)

  cy_pnl_amount = cy_booked_amt + curr_pnl_amount
  cy_pnl_percentage = round((cy_pnl_amount)*100/cy_invested,2)

  overall_pnl_amount = total_booked_amt + curr_pnl_amount
  overall_pnl_percentage = round((overall_pnl_amount)*100/investment,2)

  estimate_st = round(sum(df_portfolio_features['FTT']*df_portfolio_features['Shares']),0)  + reserve_amt
  est_st_pnl_amount = estimate_st-current
  est_st_pnl_percentage = round((est_st_pnl_amount)*100/current,2)

  estimate_lt = round(sum(df_portfolio_features['LTT']*df_portfolio_features['Shares']),0)  + reserve_amt
  est_lt_pnl_amount = estimate_lt-current
  est_lt_pnl_percentage = round((est_lt_pnl_amount)*100/current,2)

  total_profit = round(sum(df_portfolio_features[df_portfolio_features['Current P/L%'] > 0]['Current']) - sum(df_portfolio_features[df_portfolio_features['Current P/L%'] > 0]['Investment']),0)
  total_loss = round(sum(df_portfolio_features[df_portfolio_features['Current P/L%'] < 0]['Current']) - sum(df_portfolio_features[df_portfolio_features['Current P/L%'] < 0]['Investment']),0)

  cy_booked_percentage = round((cy_booked_amt)*100/current,2)
  py_booked_percentage = round((py_booked_amt)*100/investment,2)
  total_booked_percentage = round((total_booked_amt)*100/investment,2)

  print('-------------------')
  print('Initial Investment: ', format_amt(investment))
  print('CY Investment: ', format_amt(cy_invested))
  print('Reserve: ', format_amt(reserve_amt))
  print('Current: ',  format_amt(current))
  print('-------------------')
  print('Today PnL: '+ '{} ({}%)'.format(format_amt(today_pnl_amount), today_pnl_percentage))
  print('Current PnL: '+ '{} ({}%)'.format(format_amt(curr_pnl_amount), curr_pnl_percentage))
  print('CY Booked + Current PnL: '+ '{} ({}%)'.format(format_amt(cy_pnl_amount), cy_pnl_percentage))
  print('-------------------')
  print('Total profit: ', format_amt(total_profit))
  print('Total loss: ', format_amt(total_loss))
  print('-------------------')
  print('Total Booked + Current PnL: '+ '{} ({}%)'.format(format_amt(overall_pnl_amount), overall_pnl_percentage))
  print('Total Booked PnL: '+ '{} ({}%)'.format(format_amt(total_booked_amt), total_booked_percentage))
  print('Curr Year Booked PnL: '+ '{} ({}%)'.format(format_amt(cy_booked_amt), cy_booked_percentage))
  print('Prev Year Booked PnL: '+ '{} ({}%)'.format(format_amt(py_booked_amt), py_booked_percentage))
  print('===================')
  print('Est FTT: ',  format_amt(estimate_st))
  print('Est FTT PnL: '+ '{} ({}%)'.format(format_amt(est_st_pnl_amount), est_st_pnl_percentage))

  print('===================')
  print('Deployed: ', format_amt(investment))

  print('Current: ', format_amt(current))

  print('CAGR/XIRR %: '+'{}%'.format(cagr))

In [8]:
# get start and end date
start_date, end_date = get_start_end_date()

# get portfolio and prospects data
mypfs_df = get_mypfs_df()
mypps_df = get_mypps_df()
myinvmt_df = get_myinvmt_df()

# merge above datasets
mypf_df = pd.merge(mypfs_df, mypps_df, on="Symbol")

# seggregate dm and sv portfolio
dm_pf = mypf_df[mypf_df['InPortfolio'] == 'DM']
sv_pf = mypf_df[mypf_df['InPortfolio'] == 'SV']

# build portfolio stock dataframe
dm_stocks = get_stock_ids(dm_pf)
sv_stocks = get_stock_ids(sv_pf)
df_stocks = pd.concat([dm_pf,sv_pf], ignore_index = True)

# arrange common and diff stock features
common_cols = ['Symbol', 'Target', 'Criteria', 'Strategy', 'CumlRnk', 'LatestQtr', 'StarStock', 'Conviction', 'Category', 'InFolio', 'XIRR', 'MBQ']
diff_cols = ['Symbol', 'AvgCost', 'Shares']
df_stocks = arrange_features(df_stocks, common_cols, diff_cols)

# get common features
stock_ids = df_stocks['Symbol'].values
df_common_features = get_common_features(stock_ids, df_stocks)

df_common_features.reset_index(drop=True, inplace=True)
df_common_features.drop(['Date'], axis=1, inplace=True)
# get and print portfolio features
df_portfolio_features = get_portfolio_features(df_common_features)

print_portfolio_stats(df_portfolio_features, myinvmt_df)

df = df_portfolio_features
#plot_pie_chart(df, 'CapType', 'Current')
list_ox40n = list(df[df['MBQ'].str.contains('OX40N', na=False)]['Symbol'].values)

Run date time (IST): 2026-06-19 12:35:54
-------------------
qualified stocks: 92
with latest results: 31
still star stocks: 20
-------------------
Initial Investment:  1.40 C
CY Investment:  1.82 C
Reserve:  1.49 K
Current:  1.52 C
-------------------
Today PnL: -58.33 K (-0.38%)
Current PnL: -31.13 L (-17.07%)
CY Booked + Current PnL: -29.05 L (-15.93%)
-------------------
Total profit:  3.80 L
Total loss:  -34.93 L
-------------------
Total Booked + Current PnL: 13.82 L (9.91%)
Total Booked PnL: 44.95 L (32.22%)
Curr Year Booked PnL: 2.08 L (1.37%)
Prev Year Booked PnL: 42.87 L (30.73%)
===================
Est FTT:  2.55 C
Est FTT PnL: 1.03 C (67.77%)
===================
Deployed:  1.40 C
Current:  1.52 C
CAGR/XIRR %: 4.03%

In [9]:
# top 5 near their targets
cols = ['Symbol', 'Today P/L%', 'Current P/L%', 'FTT%', 'OTT%', 'FTT Amt', 'Current P/L', 'Current', 'FTT', 'Dev%_PE', 'RSI_14','Conviction', 'Spread%',  'CumlRnk', 'RRR Ind', 'CurrAlloc%', 'Gained%', 'Criteria', 'Strategy', 'Category']
df_tmp = df_portfolio_features[~df_portfolio_features['Symbol'].isin(['ENRIN','BLUSPRING','DIGITIDE'])]
df_tmp = df_tmp.sort_values(by = 'FTT Amt', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
59,PIDILITIND,0.10,12.16,5.53,18.37,8752.0,17160.0,158270.0,1670.26,-21.49,75.0,X-LC,3.81,5.0,1.96,1.04,24.27,X40,ATH,CHEMICALS
51,KOTAKBANK,-0.73,6.88,13.31,21.11,19699.0,9528.0,148000.0,453.24,-8.11,60.0,X-LC,5.49,12.0,0.48,0.97,13.19,X40,ATH,BANKS
55,MASFIN,-0.31,-2.31,24.44,21.57,23393.0,-2265.0,95715.0,397.04,-15.99,57.0,H-SC,3.26,167.0,-0.10,0.63,14.09,XR,ATH,FINANCE
49,JSWINFRA,0.32,5.18,10.70,16.43,24958.0,11483.0,233257.0,342.00,-9.76,70.0,X-MC,2.10,61.0,0.46,1.53,32.25,X40N,NTT,REALTY
72,SIS,0.31,-2.28,24.09,21.26,26138.0,-2530.0,108502.0,528.00,2588.60,62.0,H-SC,22.87,168.0,-0.10,0.71,61.33,OX40N,NTT,MISC

In [10]:
# top 5 today
df_tmp = df_portfolio_features.sort_values(by = 'Today P/L%', ascending=False)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
11,BERGEPAINT,7.07,-0.35,25.75,25.32,66140.0,-893.0,256856.0,680.0,-5.80,64.0,X-MC,2.96,68.0,-0.01,1.69,33.68,XY24,NTT,PAINTS
31,HATHWAY,5.69,-32.34,156.12,73.29,114842.0,-35160.0,73560.0,31.4,755.07,71.0,H-SC,9.25,171.0,-0.31,0.48,38.22,XR,NTT,ENTERTAINMENT
21,DEN,5.59,-37.37,126.86,42.07,67104.0,-31568.0,52896.0,75.0,89.12,77.0,M-SC,7.43,235.0,-0.47,0.35,43.86,AR,NTT,ENTERTAINMENT
61,RAJESHEXPO,5.00,-81.16,431.23,0.07,111430.0,-111337.0,25840.0,518.0,846.97,48.0,L-SC,35.30,268.0,-1.00,0.17,27.61,OX40N,NTT,JEWELLERY
16,CERA,3.51,-16.63,48.60,23.89,71271.0,-29255.0,146648.0,9475.0,-19.57,72.0,H-SC,6.03,153.0,-0.41,0.96,40.93,OX40N,NTT,CERAMICS

In [11]:
# bottom 5 today
df_tmp = df_portfolio_features.sort_values(by = 'Today P/L%', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
45,INFY,-7.62,-29.09,89.32,34.24,198166.0,-91027.0,221861.0,1972.00,-44.12,32.0,X-LC,16.82,3.0,-0.46,1.46,0.00,X40,NTT,IT
79,TCS,-5.54,-38.90,104.39,24.88,295483.0,-180216.0,283057.0,4253.91,-48.21,34.0,X-LC,19.22,2.0,-0.61,1.86,0.00,X40,ATH,IT
86,VALIANTORG,-5.26,-38.83,184.70,74.15,184846.0,-63526.0,100079.0,838.00,-280.29,53.0,H-SC,3.28,145.0,-0.34,0.66,48.93,XR,NTT,CHEMICALS
33,HCLTECH,-3.94,-27.58,67.77,21.51,118741.0,-66712.0,175212.0,1872.35,-23.90,39.0,X-LC,18.41,8.0,-0.56,1.15,0.58,X40,ATH,IT
10,BATAINDIA,-3.90,-51.03,176.12,35.20,110964.0,-65665.0,63005.0,2096.00,-17.40,66.0,X-SC,23.94,91.0,-0.59,0.41,24.95,X40,NTT,FOOTWEAR

In [12]:
# top 5 to exit based on CumlRnk
df_tmp = df_portfolio_features[~df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])]
df_tmp = df_tmp[(df_tmp['Current P/L%'] > -1) & (df_tmp['Current P/L%'] < 1)].sort_values(by = 'CumlRnk', ascending=False)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
9,BANDHANBNK,-2.7,0.29,91.86,92.42,256636.0,818.0,279377.0,400.0,139.94,55.0,H-SC,23.41,174.0,0.0,1.84,53.9,XY24,NTT,BANKS

In [13]:
# OX40N stocks to exit
df_tmp = df_portfolio_features[(df_portfolio_features['Symbol'].isin(list_ox40n))].sort_values(by = 'Current P/L%', ascending=False)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
25,FINCABLES,-0.65,45.79,42.61,107.91,91721.0,67612.0,215256.0,1641.55,30.90,63.0,M-SC,24.47,220.0,0.74,1.42,61.94,OX40N,ATH,CABLES
72,SIS,0.31,-2.28,24.09,21.26,26138.0,-2530.0,108502.0,528.00,2588.60,62.0,H-SC,22.87,168.0,-0.10,0.71,61.33,OX40N,NTT,MISC
16,CERA,3.51,-16.63,48.60,23.89,71271.0,-29255.0,146648.0,9475.00,-19.57,72.0,H-SC,6.03,153.0,-0.41,0.96,40.93,OX40N,NTT,CERAMICS
43,INDIGOPNTS,-0.52,-27.40,37.78,0.02,47876.0,-47837.0,126722.0,1408.00,93.08,62.0,M-SC,9.33,222.0,-1.00,0.83,43.77,OX40N,NTT,PAINTS
50,KANSAINER,1.73,-28.89,59.56,13.47,114219.0,-77895.0,191772.0,340.00,-38.95,51.0,H-SC,5.69,162.0,-0.68,1.26,33.95,XY24,NTT,PAINTS

In [14]:
# top 5 to book for rotation
df_tmp = df_portfolio_features[(df_portfolio_features['Current P/L%'] > 20) ].sort_values(by = 'CumlRnk', ascending=False)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
25,FINCABLES,-0.65,45.79,42.61,107.91,91721.0,67612.0,215256.0,1641.55,30.90,63.0,M-SC,24.47,220.0,0.74,1.42,61.94,OX40N,ATH,CABLES
68,SATIN,1.54,30.22,16.60,51.83,59724.0,83501.0,359785.0,274.00,16.95,59.0,H-SC,41.00,159.0,1.40,2.37,75.27,XY24,NTT,FINANCE

In [15]:
# top 5 to monitor for exit
df_tmp = df_portfolio_features[~df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])]
df_tmp = df_tmp[(df_tmp['Current P/L%'] > 0) ].sort_values(by = 'Dev%_PE', ascending=False)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
9,BANDHANBNK,-2.70,0.29,91.86,92.42,256636.0,818.0,279377.0,400.00,139.94,55.0,H-SC,23.41,174.0,0.00,1.84,53.90,XY24,NTT,BANKS
74,STARHEALTH,3.14,12.89,30.44,47.26,96607.0,36247.0,317370.0,761.00,78.26,78.0,H-SC,11.02,173.0,0.38,2.09,39.34,XY24,NTT,INSURANCE
25,FINCABLES,-0.65,45.79,42.61,107.91,91721.0,67612.0,215256.0,1641.55,30.90,63.0,M-SC,24.47,220.0,0.74,1.42,61.94,OX40N,ATH,CABLES
68,SATIN,1.54,30.22,16.60,51.83,59724.0,83501.0,359785.0,274.00,16.95,59.0,H-SC,41.00,159.0,1.40,2.37,75.27,XY24,NTT,FINANCE
91,ZYDUSLIFE,-0.36,12.89,20.15,35.63,47671.0,27006.0,236580.0,1286.17,-1.80,55.0,H-MC,13.59,120.0,0.57,1.56,24.39,AR,ATH,PHARMA

In [16]:
# top 5 to book for rotation from weak conviction
df_tmp = df_portfolio_features[~df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])]
df_tmp = df_tmp[~df_tmp['Criteria'].isin(['XY25','XY24','X40', 'X40N'])].sort_values(by = 'RRR Ind', ascending=False)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
25,FINCABLES,-0.65,45.79,42.61,107.91,91721.0,67612.0,215256.0,1641.55,30.90,63.0,M-SC,24.47,220.0,0.74,1.42,61.94,OX40N,ATH,CABLES
91,ZYDUSLIFE,-0.36,12.89,20.15,35.63,47671.0,27006.0,236580.0,1286.17,-1.80,55.0,H-MC,13.59,120.0,0.57,1.56,24.39,AR,ATH,PHARMA
73,SONACOMS,1.72,6.47,30.64,39.09,33001.0,6545.0,107704.0,804.02,-15.61,60.0,M-MC,18.51,193.0,0.20,0.71,52.36,AR,ATH,AUTO
75,SURYODAY,-0.76,-1.97,25.50,23.03,44766.0,-3519.0,175552.0,216.00,90.79,57.0,H-SC,18.82,166.0,-0.08,1.15,47.81,XR,NTT,BANKS
42,INDIAMART,1.25,-9.60,122.26,100.92,136315.0,-11840.0,111496.0,4675.60,-59.18,72.0,H-SC,8.93,140.0,-0.09,0.73,11.05,AR,ATH,MISC

In [17]:
# top 5 to accumulate based on lowest RSI_14
df_tmp = df_portfolio_features[df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])].sort_values(by = 'RSI_14', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
45,INFY,-7.62,-29.09,89.32,34.24,198166.0,-91027.0,221861.0,1972.00,-44.12,32.0,X-LC,16.82,3.0,-0.46,1.46,0.00,X40,NTT,IT
79,TCS,-5.54,-38.90,104.39,24.88,295483.0,-180216.0,283057.0,4253.91,-48.21,34.0,X-LC,19.22,2.0,-0.61,1.86,0.00,X40,ATH,IT
33,HCLTECH,-3.94,-27.58,67.77,21.51,118741.0,-66712.0,175212.0,1872.35,-23.90,39.0,X-LC,18.41,8.0,-0.56,1.15,0.58,X40,ATH,IT
20,DABUR,-0.86,-16.91,72.94,43.70,150348.0,-41943.0,206125.0,735.00,-24.64,42.0,X-MC,11.37,70.0,-0.28,1.36,3.54,XY24,BTT,FMCG
58,PGHH,1.82,-31.30,92.15,32.01,135180.0,-66824.0,146696.0,17616.87,-53.57,42.0,X-MC,19.74,57.0,-0.49,0.96,1.96,X40,ATH,FMCG

In [18]:
# top 5 to accumulate based on Spread and CumlRnk
df_tmp = df_portfolio_features[df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])]
df_tmp = df_tmp[(df_tmp['CumlRnk'] < 100)].sort_values(by = 'Spread%', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
49,JSWINFRA,0.32,5.18,10.70,16.43,24958.0,11483.0,233257.0,342.00,-9.76,70.0,X-MC,2.10,61.0,0.46,1.53,32.25,X40N,NTT,REALTY
11,BERGEPAINT,7.07,-0.35,25.75,25.32,66140.0,-893.0,256856.0,680.00,-5.80,64.0,X-MC,2.96,68.0,-0.01,1.69,33.68,XY24,NTT,PAINTS
56,MEDANTA,0.54,8.21,17.47,27.12,33370.0,14498.0,191015.0,1486.00,4.95,62.0,X-SC,3.39,87.0,0.43,1.26,31.62,XY24,NTT,HEALTHCARE
57,PAGEIND,-0.17,4.62,27.69,33.59,77745.0,12391.0,280770.0,51217.29,-25.01,65.0,X-MC,3.54,55.0,0.16,1.85,33.34,X40,ATH,APPARELS
19,COLPAL,-1.12,-23.89,83.76,39.86,167897.0,-62915.0,200450.0,3683.41,-7.87,43.0,X-MC,3.66,62.0,-0.37,1.32,13.39,XY25,ATH,FMCG

In [19]:
# top 5 to accumulate based on lowest Gained%
df_tmp = df_portfolio_features[df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])].sort_values(by = 'Gained%', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
45,INFY,-7.62,-29.09,89.32,34.24,198166.0,-91027.0,221861.0,1972.00,-44.12,32.0,X-LC,16.82,3.0,-0.46,1.46,0.00,X40,NTT,IT
79,TCS,-5.54,-38.90,104.39,24.88,295483.0,-180216.0,283057.0,4253.91,-48.21,34.0,X-LC,19.22,2.0,-0.61,1.86,0.00,X40,ATH,IT
33,HCLTECH,-3.94,-27.58,67.77,21.51,118741.0,-66712.0,175212.0,1872.35,-23.90,39.0,X-LC,18.41,8.0,-0.56,1.15,0.58,X40,ATH,IT
58,PGHH,1.82,-31.30,92.15,32.01,135180.0,-66824.0,146696.0,17616.87,-53.57,42.0,X-MC,19.74,57.0,-0.49,0.96,1.96,X40,ATH,FMCG
28,GODREJCP,-0.69,-10.31,46.58,31.47,62088.0,-15321.0,133293.0,1469.04,-5.66,43.0,X-LC,9.52,32.0,-0.25,0.88,2.27,X40N,ATH,FMCG

In [20]:
# top 5 to accumulate based on lowest CurrAlloc%
df_tmp = df_portfolio_features[df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])].sort_values(by = 'CurrAlloc%', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
10,BATAINDIA,-3.90,-51.03,176.12,35.20,110964.0,-65665.0,63005.0,2096.00,-17.40,66.0,X-SC,23.94,91.0,-0.59,0.41,24.95,X40,NTT,FOOTWEAR
64,RELAXO,-3.28,-53.92,230.52,52.31,154195.0,-78270.0,66890.0,1176.00,-50.92,62.0,X-SC,16.51,92.0,-0.51,0.44,49.56,X40N,NTT,FOOTWEAR
60,QUESS,0.49,3.01,68.81,73.90,75699.0,3219.0,110012.0,424.00,-44.35,79.0,X-SC,7.80,80.0,0.04,0.72,49.97,XY24,NTT,MISC
28,GODREJCP,-0.69,-10.31,46.58,31.47,62088.0,-15321.0,133293.0,1469.04,-5.66,43.0,X-LC,9.52,32.0,-0.25,0.88,2.27,X40N,ATH,FMCG
53,M&M,-1.72,0.02,23.35,23.38,32389.0,31.0,138712.0,3802.40,-15.13,50.0,X-LC,10.42,25.0,0.00,0.91,5.17,X40N,ATH,AUTO

In [21]:
# top 5 to accumulate based on CumlRnk
df_tmp = df_portfolio_features.sort_values(by = 'CumlRnk', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
47,ITC,-0.53,-23.72,56.08,19.06,145518.0,-80684.0,259482.0,452.00,-57.95,51.0,X-LC,15.09,1.0,-0.55,1.71,4.55,X40,NTT,FMCG
79,TCS,-5.54,-38.90,104.39,24.88,295483.0,-180216.0,283057.0,4253.91,-48.21,34.0,X-LC,19.22,2.0,-0.61,1.86,0.00,X40,ATH,IT
45,INFY,-7.62,-29.09,89.32,34.24,198166.0,-91027.0,221861.0,1972.00,-44.12,32.0,X-LC,16.82,3.0,-0.46,1.46,0.00,X40,NTT,IT
81,TMPV,-1.00,-18.50,67.57,36.58,195967.0,-65821.0,290020.0,600.00,-83.62,42.0,X-LC,11.36,4.0,-0.34,1.91,21.89,XY24,NTT,AUTO
59,PIDILITIND,0.10,12.16,5.53,18.37,8752.0,17160.0,158270.0,1670.26,-21.49,75.0,X-LC,3.81,5.0,1.96,1.04,24.27,X40,ATH,CHEMICALS

In [22]:
# top 5 for average up
df_tmp = df_portfolio_features[(df_portfolio_features['Dev%_200'] > 5)].sort_values(by = 'CurrAlloc%', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
21,DEN,5.59,-37.37,126.86,42.07,67104.0,-31568.0,52896.0,75.00,89.12,77.0,M-SC,7.43,235.0,-0.47,0.35,43.86,AR,NTT,ENTERTAINMENT
44,INDUSINDBK,0.29,-30.49,91.19,32.89,48935.0,-23544.0,53663.0,1800.00,-352.80,59.0,L-MC,7.64,258.0,-0.48,0.35,32.09,XR,NTT,BANKS
3,ALKYLAMINE,0.49,-23.34,152.58,93.63,118097.0,-23563.0,77400.0,4546.37,-17.90,56.0,H-SC,6.77,142.0,-0.20,0.51,46.15,SR,ATH,CHEMICALS
86,VALIANTORG,-5.26,-38.83,184.70,74.15,184846.0,-63526.0,100079.0,838.00,-280.29,53.0,H-SC,3.28,145.0,-0.34,0.66,48.93,XR,NTT,CHEMICALS
73,SONACOMS,1.72,6.47,30.64,39.09,33001.0,6545.0,107704.0,804.02,-15.61,60.0,M-MC,18.51,193.0,0.20,0.71,52.36,AR,ATH,AUTO

In [23]:
# top 5 RSP
df_tmp = df_portfolio_features.sort_values(by = 'RSP', ascending=False)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
18,COFFEEDAY,-0.20,-41.66,131.88,35.27,87357.0,-47309.0,66240.0,80.00,-55.73,58.0,L-SC,14.44,266.0,-0.54,0.44,63.35,XR,NTT,HOTELS
37,HONAUT,0.75,-2.90,55.83,51.31,104542.0,-5588.0,187250.0,58357.33,-19.32,68.0,X-SC,8.69,90.0,-0.05,1.23,42.26,X40N,ATH,ELECTRICAL
80,TITAGARH,-0.49,-12.63,66.81,45.74,141359.0,-30593.0,211584.0,1548.00,16.36,70.0,H-SC,6.54,175.0,-0.22,1.39,61.43,XY24,NTT,ENGINEERING
21,DEN,5.59,-37.37,126.86,42.07,67104.0,-31568.0,52896.0,75.00,89.12,77.0,M-SC,7.43,235.0,-0.47,0.35,43.86,AR,NTT,ENTERTAINMENT
64,RELAXO,-3.28,-53.92,230.52,52.31,154195.0,-78270.0,66890.0,1176.00,-50.92,62.0,X-SC,16.51,92.0,-0.51,0.44,49.56,X40N,NTT,FOOTWEAR

In [24]:
# Top N allocation
df_tmp = df_portfolio_features.sort_values(by = 'CurrAlloc%', ascending=False)
top_n_values = [10, 25, 50]

sum_df = pd.DataFrame({
    'Top_N': top_n_values,
    'Sum_Alloc%': [df_tmp['CurrAlloc%'].head(n).sum() for n in top_n_values]
})

sum_df

   Top_N  Sum_Alloc%
0     10       19.49
1     25       42.67
2     50       72.73

In [25]:
# market-cap-wise allocation
df_tmp = df_portfolio_features[cols]
df_tmp.groupby(df_tmp['Conviction'].str[-2:])['CurrAlloc%'].sum().sort_values(ascending=False)

Conviction
SC    43.62
LC    30.58
MC    25.80
Name: CurrAlloc%, dtype: float64

In [26]:
# criteria-wise allocation
df_portfolio_features.groupby('Criteria')['CurrAlloc%'].sum().sort_values(ascending=False)

Criteria
XY24     27.83
X40      24.60
X40N     17.37
XR        8.94
OX40N     7.06
AR        6.81
XY25      6.52
SR        0.87
Name: CurrAlloc%, dtype: float64

In [27]:
# conviction-wise allocation
df_portfolio_features.groupby('Conviction')['CurrAlloc%'].sum().sort_values(ascending=False)

Conviction
X-LC    28.54
H-SC    22.92
X-MC    20.77
M-SC    10.11
X-SC     9.98
H-MC     2.68
M-MC     2.00
H-LC     1.23
M-LC     0.81
L-SC     0.61
L-MC     0.35
Name: CurrAlloc%, dtype: float64

In [28]:
# sector-wise stats
df_tmp = df_portfolio_features.groupby('Category')[['CurrAlloc%', 'Current', 'Current P/L', 'FTT Amt']].sum().sort_values(by=['Current', 'Current P/L'], ascending=False)
df_tmp['Current P/L%'] = round(df_tmp['Current P/L'] * 100 / df_tmp['Current'], 2)
df_tmp['FTT%'] = round(df_tmp['FTT Amt'] * 100 / df_tmp['Current'], 2)
cols = ['CurrAlloc%', 'Current P/L%', 'FTT%']
df_tmp[cols].sort_values(by=['CurrAlloc%'], ascending=False)

               CurrAlloc%  Current P/L%    FTT%
Category
FMCG                14.65        -18.86   60.55
FINANCE             10.99        -10.41   58.43
IT                   9.64        -53.66  130.48
MISC                 7.22        -22.02   74.37
AUTO                 6.63         -8.70   49.45
BANKS                5.75         -3.75   51.72
PAINTS               5.61        -15.45   35.49
INSURANCE            5.41         -0.62   34.56
PHARMA               4.91          0.58   30.19
ELECTRICAL           4.09        -13.39   53.40
CHEMICALS            2.21        -20.83   92.84
HEALTHCARE           2.04        -15.71   45.90
AC                   1.86        -12.81   43.40
APPARELS             1.85          4.41   27.69
FOOTWEAR             1.74        -66.30  132.98
TRAVEL               1.63        -81.41  172.25
DURABLES             1.53        -65.32  105.53
REALTY               1.53          4.92   10.70
BREWERIES            1.50         -2.87   24.23
CERAMICS             1.43        -40.97   83.79
CABLES               1.42         31.41   42.61
ENGINEERING          1.39        -14.46   66.81
REFINERIES           1.13        -17.32   47.00
JEWELLERY            1.08        -95.60  163.56
CEMENT               1.07        -65.47  189.27
ENTERTAINMENT        0.83        -52.77  143.88
HOTELS               0.44        -71.42  131.88
TEXTILES             0.42        -45.05   86.41

In [29]:
# money to be made criteria-wise
df_portfolio_features.groupby('Criteria')['FTT Amt'].agg(['sum', 'count']).sort_values(by='sum', ascending=False)

                sum  count
Criteria
XY24      3369759.0     21
X40       1938458.0     19
XR        1322745.0     13
AR        1141750.0      9
X40N      1081603.0     13
OX40N      716611.0     10
XY25       445472.0      5
SR         287691.0      2

In [30]:
# money to be made conviction-wise
df_portfolio_features.groupby('Conviction')['FTT Amt'].agg(['sum', 'count']).sort_values(by='sum', ascending=False)

                  sum  count
Conviction
H-SC        3295625.0     24
X-LC        1948481.0     21
X-MC        1557276.0     15
M-SC        1380755.0     14
X-SC        1285746.0      9
H-MC         291675.0      2
L-SC         198787.0      2
M-LC         168391.0      1
M-MC          82576.0      2
L-MC          48935.0      1
H-LC          45842.0      1

In [31]:
# money to be made criteria and conviction-wise
df_portfolio_features.groupby(['Conviction', 'Criteria'])['FTT Amt'].agg(['sum', 'count']).sort_values(by='sum', ascending=False)

                           sum  count
Conviction Criteria
X-LC       X40       1063329.0     10
H-SC       XY24       969583.0      6
           AR         948132.0      5
M-SC       XY24       823215.0      6
H-SC       XR         785093.0      7
X-SC       XY24       780600.0      4
X-MC       X40        669040.0      7
           X40N       429931.0      4
X-LC       X40N       352615.0      6
           XY24       335869.0      2
H-SC       OX40N      305126.0      4
M-SC       OX40N      300055.0      5
X-SC       X40N       299057.0      3
H-SC       SR         287691.0      2
H-MC       XY24       244004.0      1
X-MC       XY25       241817.0      2
           XY24       216488.0      2
X-SC       X40        206089.0      2
M-SC       XR         190381.0      2
M-LC       XR         168391.0      1
X-LC       XY25       154080.0      2
L-SC       OX40N      111430.0      1
           XR          87357.0      1
M-SC       AR          67104.0      1
M-MC       XY25        49575.0      1
L-MC       XR          48935.0      1
H-MC       AR          47671.0      1
H-LC       AR          45842.0      1
X-LC       XR          42588.0      1
M-MC       AR          33001.0      1

In [32]:
# notebook execution time

end_time = time.time()
execution_time = round(end_time - start_time, 0)
print(f"Notebook execution time: {execution_time} seconds")

Notebook execution time: 31.0 seconds