<a href="https://colab.research.google.com/github/ankit-rathi/Quantvesting_v2/blob/main/myStocks_Portfolio_Analysis.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
'''
!pip install pandas==2.2.2 -qq
!pip install pyxirr -qq
!pip install ta -qq
!pip install yfinance==0.2.59 -qq
'''

'\n!pip install pandas==2.2.2 -qq\n!pip install pyxirr -qq\n!pip install ta -qq\n!pip install yfinance==0.2.59 -qq\n'

In [2]:
# import libraries

import numpy as np
import pandas as pd
import datetime
import warnings
warnings.filterwarnings('ignore')
import yfinance as yfin
import ta
import matplotlib.pyplot as plt
import requests

In [3]:
# notebook start time
import time
import datetime
import pytz

start_time = time.time()

# function to print date timestamp
def print_date_time():
  tz_NY = pytz.timezone('Asia/Kolkata')
  datetime_NY = datetime.datetime.now(tz_NY)
  print("Run date time (IST):", datetime_NY.strftime("%Y-%m-%d %H:%M:%S"))

In [4]:
# function to get booked and reserved amount
def get_amt():
  # fetch the JSON data from the URL
  url = "https://raw.githubusercontent.com/ankit-rathi/Tradevesting_v1/main/data/myPortfolioAmts.json"
  response = requests.get(url)
  pf_amts = response.json()  # parse the JSON data

  # extract values from the JSON
  py_booked_amt_dm = pf_amts["py_booked_amt_dm"]
  py_booked_amt_sv = pf_amts["py_booked_amt_sv"]
  cy_booked_amt_dm = pf_amts["cy_booked_amt_dm"]
  cy_booked_amt_sv = pf_amts["cy_booked_amt_sv"]
  reserve_amt_dm = pf_amts["reserve_amt_dm"]
  reserve_amt_sv = pf_amts["reserve_amt_sv"]

  # perform calculations
  py_booked_amt = py_booked_amt_dm + py_booked_amt_sv
  cy_booked_amt = cy_booked_amt_dm + cy_booked_amt_sv
  reserve_amt = reserve_amt_dm + reserve_amt_sv
  total_booked_amt = py_booked_amt + cy_booked_amt

  return total_booked_amt, reserve_amt, cy_booked_amt, py_booked_amt

gen_output = 0

In [5]:
# function to format the amount
def format_amt(number):
    abs_number = abs(number)

    if abs_number >= 1_00_00_000:  # Crores
        formatted_amt = f"{number / 1_00_00_000:.2f} C"
    elif abs_number >= 1_00_000:  # Lakhs
        formatted_amt = f"{number / 1_00_000:.2f} L"
    elif abs_number >= 1_000:  # Thousands
        formatted_amt = f"{number / 1_000:.2f} K"
    else:
        formatted_amt = f"{number:.2f}"

    return formatted_amt

# function to set start and end date
def get_start_end_date():
  start_date = (datetime.date.today() + datetime.timedelta(days=-365)).strftime('%Y-%m-%d')
  end_date = (datetime.date.today() + datetime.timedelta(days=1)).strftime('%Y-%m-%d')
  return start_date, end_date

# function to fetch my portfolio csv
def get_mypfs_df():
  mypfs_df = pd.read_csv('https://raw.githubusercontent.com/ankit-rathi/Tradevesting_v1/main/data/myPortfolioStocks.csv')
  return mypfs_df

# function to fetch my prospects csv
def get_mypps_df():
  mypps_df = pd.read_csv('https://raw.githubusercontent.com/ankit-rathi/Tradevesting_v1/main/data/myProspectsScrips.csv')
  return mypps_df

# function to fetch screener data
def get_myscreen_df():
  myscreen_df = pd.read_csv('https://raw.githubusercontent.com/ankit-rathi/Tradevesting_v1/main/data/myScreenerDB.csv')
  return myscreen_df

# function to fetch momentum data
def get_myinvmt_df():
  myinvmt_df = pd.read_csv('https://raw.githubusercontent.com/ankit-rathi/Tradevesting_v1/main/data/myInvestments.csv')
  return myinvmt_df

# function to get the stock ids
def get_stock_ids(df_pf):
  stock_n100 = df_pf['Symbol'].unique()

  exclude = ['CADILAHC','MMTC', 'MASFIN']

  stock_ids = df_pf[~df_pf['Symbol'].isin(exclude) ]['Symbol'].unique()

  #mypf = mypf[mypf.Forecast.notnull()]
  #stock_ids = mypf['Symbol'].unique()

  #stock_ids.sort()
  return stock_ids

# get features from screener data
def get_screener_features():
  myscreen_df = get_myscreen_df()
  cols = ['Symbol', 'EPS', 'MedPE', 'ROCE%', 'ROE%', 'CapType']
  return myscreen_df[cols]

# get relative strength
def get_relative_strength(stock_list):

    # Dictionary to store stock tickers and their corresponding percentage price change
    stock_changes = {}

    # Loop through each stock and fetch its price data
    for stock in stock_list:
        try:
            # Download the stock data for the given date range
            stock_data = yfin.Ticker(stock + '.NS').history(period='1mo', interval='1d')[map(str.title, ['open', 'close', 'low', 'high', 'volume'])]

            # Calculate the percentage change for the stock
            if len(stock_data) > 0:
                start_price = stock_data['Close'].iloc[0]
                end_price = stock_data['Close'].iloc[-1]
                percent_change = round(((end_price - start_price) / start_price) * 100, 2)
                stock_changes[stock] = percent_change
            else:
                stock_changes[stock] = np.nan  # If no data is available, set to NaN

        except Exception as e:
            print(f"Error fetching data for {stock}: {e}")
            stock_changes[stock] = np.nan

    # Create a DataFrame with stock tickers and their percentage changes
    df = pd.DataFrame(list(stock_changes.items()), columns=['Symbol', 'Percent_Change'])

    # Drop any stocks with missing data (NaN values)
    df = df.dropna()

    # Calculate the percentile rank based on percentage change
    df['RSP'] = round(df['Percent_Change'].rank(pct=True) * 100, 2)
    cols = ['Symbol', 'RSP']
    df = df[cols]
    # Sort by percentile rank (optional)
    df = df.sort_values(by='RSP', ascending=False).reset_index(drop=True)

    return df

In [6]:
# function to get stock technicals
def stock_prec_dev(stock_symbol):
    #stock_symbol = 'ULTRACEMCO.NS'
    short_window = 20
    mid_window = 50
    long_window = 200
    moving_avg = 'SMA'

    start = datetime.datetime(*map(int, start_date.split('-')))
    end = datetime.datetime(*map(int, end_date.split('-')))

    stock_df = yfin.Ticker(stock_symbol + '.NS').history(period='max', interval='1d')[map(str.title, ['open', 'close', 'low', 'high', 'volume'])]

    stock_df['Max'] = round(max(stock_df['Close']),2)
    stock_df = stock_df[(stock_df.index <= end_date) & (stock_df.index >= start_date)]
    stock_df['200_SMA'] = round(stock_df['Close'].rolling(window = 200, min_periods = 1).mean(),0)
    stock_df['Dev%_200'] = round((stock_df['Close'] - stock_df['200_SMA'])*100/stock_df['200_SMA'],2)
    stock_df.dropna(axis = 0, inplace = True) # remove any null rows

    stock_df['20_SMA'] = stock_df['Close'].rolling(window=20).mean()
    stock_df['50_SMA'] = stock_df['Close'].rolling(window=50).mean()
    stock_df['Symbol'] = stock_symbol

    stock_df['Close'] = round(stock_df['Close'],2)
    stock_df['Min'] = round(min(stock_df['Close']),2)
    stock_df['RSI_14'] = ta.momentum.RSIIndicator(close=stock_df['Close'], window=14).rsi()
    stock_df['RSI_14'] = round(stock_df['RSI_14'],0)
    stock_df['Prev_Close'] = stock_df['Close'].shift(1)
    stock_df.drop(['Open', 'Low', 'High', 'Volume'], axis=1, inplace=True)
    stock_df = stock_df.tail(1)

    max_SMA = max(stock_df['20_SMA'].item(), stock_df['50_SMA'].item(), stock_df['200_SMA'].item())
    min_SMA = min(stock_df['20_SMA'].item(), stock_df['50_SMA'].item(), stock_df['200_SMA'].item())
    ABS_Spread = max_SMA - min_SMA
    stock_df['Spread%'] = round((ABS_Spread / stock_df['200_SMA'].item()) * 100,2)

    return stock_df

# function to compute stock attributes
def get_common_features(stock_ids, df_mypf):

  df_prec_dev = pd.DataFrame()
  df_tmp = get_screener_features()
  df_rs = get_relative_strength(stock_ids)

  for stock_id in stock_ids:
      tmp = stock_prec_dev(stock_id)
      tmp = tmp.reset_index()
      df_prec_dev = pd.concat([df_prec_dev, tmp], ignore_index = True)
  df_prec_dev = pd.merge(df_prec_dev, df_mypf, on= 'Symbol')
  df_prec_dev = pd.merge(df_prec_dev, df_tmp, on= 'Symbol', how='left')
  df_prec_dev = pd.merge(df_prec_dev, df_rs, on= 'Symbol', how='left')
  #print(df_prec_dev.columns)
  df_prec_dev['Curr_PE'] = round(df_prec_dev['Close']/df_prec_dev['EPS'],1)
  df_prec_dev['Dev%_PE'] = round((df_prec_dev['Curr_PE'] - df_prec_dev['MedPE'])*100/df_prec_dev['MedPE'],2)
  df_prec_dev['Conviction'] = df_prec_dev['Conviction'] + '-' + df_prec_dev['CapType']
  return df_prec_dev

# function to arrange stock features
def arrange_features(df_stocks, common_cols, diff_cols):
  df_stocks_common = df_stocks[common_cols].drop_duplicates()
  df_stocks_diff = df_stocks[diff_cols]
  df_stocks_diff['Investment'] = df_stocks_diff['AvgCost'] * df_stocks_diff['Shares']
  df_stocks_diff = df_stocks_diff.groupby(['Symbol'])[['Shares', 'Investment']].aggregate(['sum']).reset_index()
  df_stocks_diff.columns = ['Symbol', 'Shares', 'Investment']
  df_stocks_diff['AvgCost'] = round(df_stocks_diff['Investment']/df_stocks_diff['Shares'],2)
  df_stocks = pd.merge(df_stocks_diff, df_stocks_common, on='Symbol')
  return df_stocks

# plot fact distribution across dimension
def plot_pie_chart(df, dimension, fact):
  # grouping the data by category and calculating the sum of fact for each type
  grouped_data = df.groupby(dimension)[fact].sum()

  # sorting the grouped data in descending order
  grouped_data = grouped_data.sort_values(ascending=False)

  # creating a pie chart
  grouped_data.plot.pie(autopct='%1.1f%%', startangle=90, figsize=(6, 6))

  # adding a title and displaying the plot
  plt.title(f'{dimension} {fact} Distribution')
  plt.ylabel('')  # To hide the y-label
  plt.show()

In [7]:
# function to get portfolio features

def get_portfolio_features(df_common_features):

  print_date_time()
  print('-------------------')

  #df_common_features["Target"] = df_common_features["Target"].fillna(df_common_features["Max"])
  df_common_features['NTT'] = np.where(df_common_features['Strategy']== 'NTT', df_common_features["Target"], df_common_features['Max'])
  df_common_features['LTT'] = np.where(df_common_features['Strategy']== 'BTT', df_common_features["Target"], df_common_features['Max'])
  df_common_features['BOL'] = df_common_features['Min']

  tmp_df = df_common_features[df_common_features['Symbol'].isin(mypf_df[mypf_df['InPortfolio'] != 'NA'].Symbol.values)]
  print('qualified stocks: '+str(len(tmp_df['Symbol'].unique())))
  tmp_df1 = tmp_df[tmp_df['LatestQtr'] == 1]
  print('with latest results: '+str(len(tmp_df1['Symbol'].unique())))
  tmp_df1 = tmp_df1[tmp_df1['StarStock'] == 1]
  print('still star stocks: '+str(len(tmp_df1['Symbol'].unique())))
  tmp_df['Investment'] = tmp_df['AvgCost'] * tmp_df['Shares']
  tmp_df['Current'] = round(tmp_df['Close'] * tmp_df['Shares'],0)
  tmp_df['Previous'] = tmp_df['Prev_Close'] * tmp_df['Shares']
  tmp_df['EstimatedST'] = tmp_df['NTT'] * tmp_df['Shares']
  tmp_df['EstimatedLT'] = tmp_df['LTT'] * tmp_df['Shares']
  tmp_df['Current P/L'] = round((tmp_df['Current'] - tmp_df['Investment']),0)
  tmp_df['Today P/L%'] = round((tmp_df['Current'] - tmp_df['Previous'])*100/tmp_df['Previous'],2)
  tmp_df['Current P/L%'] = round((tmp_df['Current'] - tmp_df['Investment'])*100/tmp_df['Investment'],2)
  tmp_df['EstimatedST P/L%'] = round((tmp_df['EstimatedST'] - tmp_df['Investment'])*100/tmp_df['Investment'],2)
  tmp_df['EstimatedLT P/L%'] = round((tmp_df['EstimatedLT'] - tmp_df['Investment'])*100/tmp_df['Investment'],2)
  tmp_df['NTT%'] = round((tmp_df['NTT'] - tmp_df['Close'])*100/tmp_df['Close'],2)
  tmp_df['LTT%'] = round((tmp_df['LTT'] - tmp_df['Close'])*100/tmp_df['Close'],2)
  tmp_df['Gained%'] = round((tmp_df['Close'] - tmp_df['BOL'])*100/tmp_df['BOL'],2)
  investment = round(sum(tmp_df['AvgCost']*tmp_df['Shares']),0)
  current = round(sum(tmp_df['Close']*tmp_df['Shares']),0)
  tmp_df['InitAlloc%'] = round(tmp_df['Investment']*100/investment,2)
  tmp_df['CurrAlloc%'] = round(tmp_df['Current']*100/current,2)
  tmp_df['FTT'] = tmp_df['LTT']
  tmp_df.loc[tmp_df['Strategy'] == 'NTT', 'FTT'] = tmp_df['NTT']
  tmp_df['FTT%'] = tmp_df['LTT%']
  tmp_df.loc[tmp_df['Strategy'] == 'NTT', 'FTT%'] = tmp_df['NTT%']
  tmp_df['FTT Amt'] = round(tmp_df['FTT%'] * tmp_df['Current']/100,0)
  tmp_df['OTT%'] = round((tmp_df['FTT'] - tmp_df['AvgCost'])*100/tmp_df['AvgCost'],2)
  tmp_df['RRR Ind'] = round(tmp_df['Current P/L']/tmp_df['FTT Amt'],2)
  tmp_df['Risk Ind'] = round(tmp_df['Current P/L%']*tmp_df['CurrAlloc%'],0)

  return tmp_df

# function to print portfolio features
def print_portfolio_stats(df_portfolio_features, myinvmt_df):
  from pyxirr import xirr

  total_booked_amt, reserve_amt, cy_booked_amt, py_booked_amt = get_amt()

  dates = myinvmt_df['Date'].values
  dates = np.append(dates, datetime.date.today().strftime('%d-%b-%y'))
  investment = myinvmt_df['Investment'].values
  dates= pd.to_datetime(dates)

  current = round(sum(df_portfolio_features['Close']*df_portfolio_features['Shares']),0) + reserve_amt
  investment_xirr = np.append(investment, current)
  cagr = round(xirr(pd.DataFrame({"dates": dates, "amounts": investment_xirr}))*100,2)

  investment = -sum(investment)
  invested = round(sum(df_portfolio_features['AvgCost']*df_portfolio_features['Shares']),0) + reserve_amt
  previous = round(sum(df_portfolio_features['Prev_Close']*df_portfolio_features['Shares']),0) + reserve_amt
  cy_invested = investment + py_booked_amt

  today_pnl_amount = current-previous
  today_pnl_percentage = round((current-previous)*100/previous,2)

  curr_pnl_amount = current-invested
  curr_pnl_percentage = round((curr_pnl_amount)*100/(cy_invested),2)

  cy_pnl_amount = cy_booked_amt + curr_pnl_amount
  cy_pnl_percentage = round((cy_pnl_amount)*100/cy_invested,2)

  overall_pnl_amount = total_booked_amt + curr_pnl_amount
  overall_pnl_percentage = round((overall_pnl_amount)*100/investment,2)

  estimate_st = round(sum(df_portfolio_features['FTT']*df_portfolio_features['Shares']),0)  + reserve_amt
  est_st_pnl_amount = estimate_st-current
  est_st_pnl_percentage = round((est_st_pnl_amount)*100/current,2)

  estimate_lt = round(sum(df_portfolio_features['LTT']*df_portfolio_features['Shares']),0)  + reserve_amt
  est_lt_pnl_amount = estimate_lt-current
  est_lt_pnl_percentage = round((est_lt_pnl_amount)*100/current,2)

  total_profit = round(sum(df_portfolio_features[df_portfolio_features['Current P/L%'] > 0]['Current']) - sum(df_portfolio_features[df_portfolio_features['Current P/L%'] > 0]['Investment']),0)
  total_loss = round(sum(df_portfolio_features[df_portfolio_features['Current P/L%'] < 0]['Current']) - sum(df_portfolio_features[df_portfolio_features['Current P/L%'] < 0]['Investment']),0)

  cy_booked_percentage = round((cy_booked_amt)*100/current,2)
  py_booked_percentage = round((py_booked_amt)*100/investment,2)
  total_booked_percentage = round((total_booked_amt)*100/investment,2)

  print('-------------------')
  print('Initial Investment: ', format_amt(investment))
  print('CY Investment: ', format_amt(cy_invested))
  print('Reserve: ', format_amt(reserve_amt))
  print('Current: ',  format_amt(current))
  print('-------------------')
  print('Today PnL: '+ '{} ({}%)'.format(format_amt(today_pnl_amount), today_pnl_percentage))
  print('Current PnL: '+ '{} ({}%)'.format(format_amt(curr_pnl_amount), curr_pnl_percentage))
  print('CY Booked + Current PnL: '+ '{} ({}%)'.format(format_amt(cy_pnl_amount), cy_pnl_percentage))
  print('-------------------')
  print('Total profit: ', format_amt(total_profit))
  print('Total loss: ', format_amt(total_loss))
  print('-------------------')
  print('Total Booked + Current PnL: '+ '{} ({}%)'.format(format_amt(overall_pnl_amount), overall_pnl_percentage))
  print('Total Booked PnL: '+ '{} ({}%)'.format(format_amt(total_booked_amt), total_booked_percentage))
  print('Curr Year Booked PnL: '+ '{} ({}%)'.format(format_amt(cy_booked_amt), cy_booked_percentage))
  print('Prev Year Booked PnL: '+ '{} ({}%)'.format(format_amt(py_booked_amt), py_booked_percentage))
  print('===================')
  print('Est FTT: ',  format_amt(estimate_st))
  print('Est FTT PnL: '+ '{} ({}%)'.format(format_amt(est_st_pnl_amount), est_st_pnl_percentage))

  print('===================')
  print('Deployed: ', format_amt(investment))

  print('Current: ', format_amt(current))

  print('CAGR/XIRR %: '+'{}%'.format(cagr))

In [8]:
# get start and end date
start_date, end_date = get_start_end_date()

# get portfolio and prospects data
mypfs_df = get_mypfs_df()
mypps_df = get_mypps_df()
myinvmt_df = get_myinvmt_df()

# merge above datasets
mypf_df = pd.merge(mypfs_df, mypps_df, on="Symbol")

# seggregate dm and sv portfolio
dm_pf = mypf_df[mypf_df['InPortfolio'] == 'DM']
sv_pf = mypf_df[mypf_df['InPortfolio'] == 'SV']

# build portfolio stock dataframe
dm_stocks = get_stock_ids(dm_pf)
sv_stocks = get_stock_ids(sv_pf)
df_stocks = pd.concat([dm_pf,sv_pf], ignore_index = True)

# arrange common and diff stock features
common_cols = ['Symbol', 'Target', 'Criteria', 'Strategy', 'CumlRnk', 'LatestQtr', 'StarStock', 'Conviction', 'Category', 'InFolio', 'XIRR', 'MBQ']
diff_cols = ['Symbol', 'AvgCost', 'Shares']
df_stocks = arrange_features(df_stocks, common_cols, diff_cols)

# get common features
stock_ids = df_stocks['Symbol'].values
df_common_features = get_common_features(stock_ids, df_stocks)

df_common_features.reset_index(drop=True, inplace=True)
df_common_features.drop(['Date'], axis=1, inplace=True)
# get and print portfolio features
df_portfolio_features = get_portfolio_features(df_common_features)

print_portfolio_stats(df_portfolio_features, myinvmt_df)

df = df_portfolio_features
#plot_pie_chart(df, 'CapType', 'Current')
list_ox40n = list(df[df['MBQ'].str.contains('OX40N', na=False)]['Symbol'].values)

Run date time (IST): 2026-03-30 11:52:00
-------------------
qualified stocks: 86
with latest results: 26
still star stocks: 16
-------------------
Initial Investment:  1.36 C
CY Investment:  1.62 C
Reserve:  1.61 K
Current:  1.25 C
-------------------
Today PnL: -2.80 L (-2.19%)
Current PnL: -51.96 L (-31.98%)
CY Booked + Current PnL: -36.07 L (-22.2%)
-------------------
Total profit:  26.42 K
Total loss:  -52.22 L
-------------------
Total Booked + Current PnL: -9.09 L (-6.71%)
Total Booked PnL: 42.87 L (31.64%)
Curr Year Booked PnL: 15.89 L (12.7%)
Prev Year Booked PnL: 26.98 L (19.91%)
===================
Est FTT:  2.48 C
Est FTT PnL: 1.23 C (98.04%)
===================
Deployed:  1.36 C
Current:  1.25 C
CAGR/XIRR %: -3.84%

In [9]:
# top 5 near their targets
cols = ['Symbol', 'Today P/L%', 'Current P/L%', 'FTT%', 'OTT%', 'FTT Amt', 'Current P/L', 'Current', 'FTT', 'Dev%_PE', 'RSI_14','Conviction', 'Spread%',  'CumlRnk', 'RRR Ind', 'CurrAlloc%', 'Gained%', 'Criteria', 'Strategy', 'Category']
df_tmp = df_portfolio_features[~df_portfolio_features['Symbol'].isin(['ENRIN','BLUSPRING','DIGITIDE'])]
df_tmp = df_tmp.sort_values(by = 'FTT Amt', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
50,MASFIN,-3.13,-13.33,40.27,21.57,34195.0,-13065.0,84915.0,397.04,-25.47,35.0,H-SC,4.24,167.0,-0.38,0.68,15.82,XR,ATH,FINANCE
77,TTKPRESTIG,-2.80,-44.40,80.01,0.09,44834.0,-44742.0,56035.0,770.00,29.99,32.0,M-SC,21.29,250.0,-1.00,0.45,0.00,OX40N,NTT,DURABLES
67,SONACOMS,-0.72,-16.05,65.69,39.09,55783.0,-16240.0,84919.0,804.02,-33.43,43.0,M-MC,6.44,193.0,-0.29,0.68,20.13,AR,ATH,AUTO
2,ABBOTINDIA,-1.59,-13.72,36.84,18.07,56851.0,-24535.0,154320.0,35195.00,-26.49,41.0,X-MC,10.51,58.0,-0.43,1.23,0.92,X40,ATH,PHARMA
37,ICICIGI,-2.24,-9.53,31.91,19.34,57769.0,-19072.0,181037.0,2252.93,-24.00,30.0,X-MC,5.00,66.0,-0.33,1.45,0.08,X40,ATH,INSURANCE

In [10]:
# top 5 today
df_tmp = df_portfolio_features.sort_values(by = 'Today P/L%', ascending=False)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
53,PGHH,0.53,-31.17,91.78,32.01,134895.0,-66544.0,146976.0,17616.87,-53.44,18.0,X-MC,18.00,57.0,-0.49,1.17,0.53,X40,ATH,FMCG
64,SHALBY,0.23,-49.75,148.97,25.10,135591.0,-90124.0,91019.0,327.00,569.86,35.0,M-SC,27.95,236.0,-0.66,0.73,0.23,XY24,NTT,HEALTHCARE
24,DMART,0.13,-6.05,37.95,29.60,88994.0,-15096.0,234504.0,5391.45,-20.76,55.0,X-LC,6.80,14.0,-0.17,1.87,7.19,X40N,ATH,FMCG
52,PAGEIND,-0.47,-17.44,62.43,34.11,138336.0,-46794.0,221585.0,51418.64,-40.84,47.0,X-MC,20.99,55.0,-0.34,1.77,4.82,X40,ATH,APPARELS
59,RELIANCE,-0.62,-14.00,45.69,25.30,78968.0,-28129.0,172834.0,1952.00,-16.19,36.0,X-LC,3.85,21.0,-0.36,1.38,15.39,XY25,BTT,REFINERIES

In [11]:
# bottom 5 today
df_tmp = df_portfolio_features.sort_values(by = 'Today P/L%', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
56,RAJOOENG,-5.83,-53.32,199.06,39.61,95250.0,-54650.0,47850.0,143.1,-68.51,29.0,H-SC,33.04,136.0,-0.57,0.38,0.00,AR,ATH,MISC
60,REPCOHOME,-5.57,-24.72,152.15,89.82,328160.0,-70823.0,215682.0,880.0,-62.74,41.0,H-SC,8.44,161.0,-0.22,1.72,5.08,XY24,NTT,FINANCE
19,COFFEEDAY,-5.07,-63.88,274.53,35.27,112587.0,-72538.0,41011.0,80.0,-71.83,25.0,L-SC,29.62,266.0,-0.64,0.33,0.00,XR,NTT,HOTELS
55,RAJESHEXPO,-5.00,-84.47,544.44,0.07,115971.0,-115876.0,21301.0,518.0,680.30,17.0,L-SC,39.57,268.0,-1.00,0.17,0.00,OX40N,NTT,JEWELLERY
69,SURYODAY,-4.66,-30.53,77.09,23.03,95907.0,-54662.0,124409.0,216.0,35.96,42.0,H-SC,5.64,166.0,-0.57,0.99,16.80,XR,NTT,BANKS

In [12]:
# top 5 to exit based on CumlRnk
df_tmp = df_portfolio_features[~df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])]
df_tmp = df_tmp[(df_tmp['Current P/L%'] > -1) & (df_tmp['Current P/L%'] < 1)].sort_values(by = 'CumlRnk', ascending=False)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
26,FINCABLES,-1.52,0.62,106.64,107.91,158417.0,909.0,148553.0,1641.55,-9.69,42.0,M-SC,7.39,220.0,0.01,1.19,11.76,OX40N,ATH,CABLES

In [13]:
# OX40N stocks to exit
df_tmp = df_portfolio_features[(df_portfolio_features['Symbol'].isin(list_ox40n))].sort_values(by = 'Current P/L%', ascending=False)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
26,FINCABLES,-1.52,0.62,106.64,107.91,158417.0,909.0,148553.0,1641.55,-9.69,42.0,M-SC,7.39,220.0,0.01,1.19,11.76,OX40N,ATH,CABLES
66,SIS,-1.07,-34.42,84.91,21.26,61827.0,-38217.0,72815.0,528.00,1704.15,46.0,H-SC,14.38,168.0,-0.62,0.58,8.27,OX40N,NTT,MISC
18,CERA,-1.34,-40.14,106.96,23.89,112628.0,-70604.0,105299.0,9475.00,-42.24,41.0,H-SC,19.32,153.0,-0.63,0.84,1.19,OX40N,NTT,CERAMICS
72,TATAELXSI,-2.66,-41.63,126.20,32.03,97111.0,-54885.0,76950.0,9161.00,-26.92,34.0,H-SC,21.49,158.0,-0.57,0.61,0.26,OX40N,NTT,IT
48,KANSAINER,-1.30,-43.84,102.04,13.47,154542.0,-118215.0,151452.0,340.00,-51.83,34.0,H-SC,22.42,162.0,-0.76,1.21,5.79,XY24,NTT,PAINTS

In [14]:
# top 5 to book for rotation
df_tmp = df_portfolio_features[(df_portfolio_features['Current P/L%'] > 20) ].sort_values(by = 'CumlRnk', ascending=False)
df_tmp[cols].head()

Empty DataFrame
Columns: [Symbol, Today P/L%, Current P/L%, FTT%, OTT%, FTT Amt, Current P/L, Current, FTT, Dev%_PE, RSI_14, Conviction, Spread%, CumlRnk, RRR Ind, CurrAlloc%, Gained%, Criteria, Strategy, Category]
Index: []

In [15]:
# top 5 to monitor for exit
df_tmp = df_portfolio_features[~df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])]
df_tmp = df_tmp[(df_tmp['Current P/L%'] > 0) ].sort_values(by = 'Dev%_PE', ascending=False)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
26,FINCABLES,-1.52,0.62,106.64,107.91,158417.0,909.0,148553.0,1641.55,-9.69,42.0,M-SC,7.39,220.0,0.01,1.19,11.76,OX40N,ATH,CABLES
1,ABB,-2.06,9.70,32.70,45.57,93846.0,25373.0,286992.0,7934.00,-29.53,47.0,H-MC,13.24,125.0,0.27,2.29,27.44,AR,NTT,ELECTRICAL

In [16]:
# top 5 to book for rotation from weak conviction
df_tmp = df_portfolio_features[~df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])]
df_tmp = df_tmp[~df_tmp['Criteria'].isin(['XY25','XY24','X40', 'X40N'])].sort_values(by = 'RRR Ind', ascending=False)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
1,ABB,-2.06,9.70,32.70,45.57,93846.0,25373.0,286992.0,7934.00,-29.53,47.0,H-MC,13.24,125.0,0.27,2.29,27.44,AR,NTT,ELECTRICAL
26,FINCABLES,-1.52,0.62,106.64,107.91,158417.0,909.0,148553.0,1641.55,-9.69,42.0,M-SC,7.39,220.0,0.01,1.19,11.76,OX40N,ATH,CABLES
40,INDIAMART,-1.83,-16.86,148.65,106.72,152424.0,-20797.0,102539.0,4810.62,-62.50,32.0,H-SC,12.79,140.0,-0.14,0.82,2.57,AR,ATH,MISC
85,ZYDUSLIFE,-1.47,-6.83,45.57,35.63,88982.0,-14309.0,195265.0,1286.17,-18.92,46.0,H-MC,5.30,120.0,-0.16,1.56,8.71,AR,ATH,PHARMA
84,WIPRO,-0.73,-21.99,120.82,72.27,159711.0,-37259.0,132189.0,420.00,-29.71,35.0,M-LC,18.17,98.0,-0.23,1.06,1.42,XR,NTT,IT

In [17]:
# top 5 to accumulate based on lowest RSI_14
df_tmp = df_portfolio_features[df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])].sort_values(by = 'RSI_14', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
53,PGHH,0.53,-31.17,91.78,32.01,134895.0,-66544.0,146976.0,17616.87,-53.44,18.0,X-MC,18.00,57.0,-0.49,1.17,0.53,X40,ATH,FMCG
9,BAJAJHFL,-3.08,-34.34,146.91,62.13,263396.0,-93755.0,179291.0,181.50,-45.86,19.0,X-MC,21.30,60.0,-0.36,1.43,0.00,X40N,ATH,FINANCE
38,ICICIPRULI,-3.40,-15.22,54.19,30.73,90511.0,-29979.0,167026.0,790.00,-37.99,19.0,X-MC,6.51,78.0,-0.33,1.33,0.00,X40,ATH,INSURANCE
58,RELAXO,-3.18,-68.68,386.35,52.31,175627.0,-99702.0,45458.0,1176.00,-66.70,20.0,X-SC,29.70,92.0,-0.57,0.36,0.00,X40N,NTT,FOOTWEAR
27,GILLETTE,-2.28,-13.73,50.37,29.72,110325.0,-34866.0,219030.0,10978.86,-33.78,24.0,X-SC,12.30,83.0,-0.32,1.75,0.00,X40,ATH,FMCG

In [18]:
# top 5 to accumulate based on Spread and CumlRnk
df_tmp = df_portfolio_features[df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])]
df_tmp = df_tmp[(df_tmp['CumlRnk'] < 100)].sort_values(by = 'Spread%', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
65,SIEMENS,-3.03,-20.57,58.01,25.51,85750.0,-38275.0,147820.0,4671.50,24.19,39.0,H-LC,1.21,51.0,-0.45,1.18,8.86,AR,ATH,ELECTRICAL
78,UNITDSPR,-1.85,-9.60,33.59,20.77,71098.0,-22481.0,211663.0,1644.00,-19.88,35.0,X-MC,2.89,64.0,-0.32,1.69,0.00,X40N,NTT,BREWERIES
82,VOLTAS,-3.28,0.07,45.09,45.20,86519.0,138.0,191880.0,1856.00,14.50,37.0,X-MC,3.12,79.0,0.00,1.53,6.87,XY25,NTT,AC
59,RELIANCE,-0.62,-14.00,45.69,25.30,78968.0,-28129.0,172834.0,1952.00,-16.19,36.0,X-LC,3.85,21.0,-0.36,1.38,15.39,XY25,BTT,REFINERIES
37,ICICIGI,-2.24,-9.53,31.91,19.34,57769.0,-19072.0,181037.0,2252.93,-24.00,30.0,X-MC,5.00,66.0,-0.33,1.45,0.08,X40,ATH,INSURANCE

In [19]:
# top 5 to accumulate based on lowest Gained%
df_tmp = df_portfolio_features[df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])].sort_values(by = 'Gained%', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
3,ACC,-2.99,-42.93,206.33,74.81,315710.0,-115116.0,153012.0,3906.00,-59.70,25.0,X-SC,19.93,85.0,-0.36,1.22,0.0,XY24,BTT,CEMENT
12,BATAINDIA,-2.58,-60.27,240.34,35.20,122852.0,-77554.0,51116.0,2096.00,-33.00,25.0,X-SC,33.02,91.0,-0.63,0.41,0.0,X40,NTT,FOOTWEAR
10,BAJAJHLDNG,-2.97,-20.62,62.78,29.22,94751.0,-39199.0,150926.0,14451.52,-26.94,28.0,X-LC,18.55,28.0,-0.41,1.21,0.0,X40,ATH,FINANCE
9,BAJAJHFL,-3.08,-34.34,146.91,62.13,263396.0,-93755.0,179291.0,181.50,-45.86,19.0,X-MC,21.30,60.0,-0.36,1.43,0.0,X40N,ATH,FINANCE
28,GLAXO,-0.82,-10.04,54.68,39.15,98026.0,-20012.0,179272.0,3466.20,-31.26,30.0,X-MC,10.51,56.0,-0.20,1.43,0.0,X40,ATH,PHARMA

In [20]:
# top 5 to accumulate based on lowest CurrAlloc%
df_tmp = df_portfolio_features[df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])].sort_values(by = 'CurrAlloc%', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
58,RELAXO,-3.18,-68.68,386.35,52.31,175627.0,-99702.0,45458.0,1176.00,-66.70,20.0,X-SC,29.70,92.0,-0.57,0.36,0.00,X40N,NTT,FOOTWEAR
12,BATAINDIA,-2.58,-60.27,240.34,35.20,122852.0,-77554.0,51116.0,2096.00,-33.00,25.0,X-SC,33.02,91.0,-0.63,0.41,0.00,X40,NTT,FOOTWEAR
54,QUESS,-1.74,-29.87,147.95,73.90,110812.0,-31895.0,74898.0,424.00,-62.53,35.0,X-SC,22.27,80.0,-0.29,0.60,0.67,XY24,NTT,MISC
36,HONAUT,-1.96,-31.29,120.22,51.31,159292.0,-60338.0,132500.0,58357.33,-42.84,26.0,X-SC,17.21,90.0,-0.38,1.06,0.00,X40N,ATH,ELECTRICAL
53,PGHH,0.53,-31.17,91.78,32.01,134895.0,-66544.0,146976.0,17616.87,-53.44,18.0,X-MC,18.00,57.0,-0.49,1.17,0.53,X40,ATH,FMCG

In [21]:
# top 5 to accumulate based on CumlRnk
df_tmp = df_portfolio_features.sort_values(by = 'CumlRnk', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
45,ITC,-1.53,-23.56,55.75,19.06,144961.0,-80147.0,260019.0,452.00,-57.95,32.0,X-LC,19.30,1.0,-0.55,2.08,0.00,X40,NTT,FMCG
73,TCS,-0.89,-30.47,82.04,26.57,264264.0,-141157.0,322116.0,4311.58,-41.00,29.0,X-LC,18.18,2.0,-0.53,2.57,0.53,X40,ATH,IT
43,INFY,-1.08,-14.50,57.01,34.24,152518.0,-45360.0,267528.0,1972.00,-32.87,38.0,X-LC,15.07,3.0,-0.30,2.14,2.88,X40,NTT,IT
75,TMPV,-0.81,-31.54,99.50,36.58,242390.0,-112233.0,243608.0,600.00,-85.81,34.0,X-LC,9.59,4.0,-0.46,1.95,0.00,XY24,NTT,AUTO
33,HCLTECH,-1.33,-12.64,41.75,23.83,88240.0,-30571.0,211353.0,1908.19,-8.19,41.0,X-LC,11.61,8.0,-0.35,1.69,2.62,X40,ATH,IT

In [22]:
# top 5 for average up
df_tmp = df_portfolio_features[(df_portfolio_features['Dev%_200'] > 5)].sort_values(by = 'CurrAlloc%', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
1,ABB,-2.06,9.7,32.7,45.57,93846.0,25373.0,286992.0,7934.0,-29.53,47.0,H-MC,13.24,125.0,0.27,2.29,27.44,AR,NTT,ELECTRICAL

In [23]:
# top 5 RSP
df_tmp = df_portfolio_features.sort_values(by = 'RSP', ascending=False)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
30,HAPPSTMNDS,-4.50,-53.63,298.63,84.85,177482.0,-68733.0,59432.0,1480.71,-44.95,45.0,H-SC,25.32,152.0,-0.39,0.47,10.06,AR,ATH,IT
24,DMART,0.13,-6.05,37.95,29.60,88994.0,-15096.0,234504.0,5391.45,-20.76,55.0,X-LC,6.80,14.0,-0.17,1.87,7.19,X40N,ATH,FMCG
5,ANGELONE,-2.16,-5.66,31.64,24.18,91036.0,-17275.0,287725.0,303.00,-86.38,49.0,X-SC,10.41,97.0,-0.19,2.30,10.75,X40N,NTT,FINANCE
52,PAGEIND,-0.47,-17.44,62.43,34.11,138336.0,-46794.0,221585.0,51418.64,-40.84,47.0,X-MC,20.99,55.0,-0.34,1.77,4.82,X40,ATH,APPARELS
1,ABB,-2.06,9.70,32.70,45.57,93846.0,25373.0,286992.0,7934.00,-29.53,47.0,H-MC,13.24,125.0,0.27,2.29,27.44,AR,NTT,ELECTRICAL

In [24]:
# Top N allocation
df_tmp = df_portfolio_features.sort_values(by = 'CurrAlloc%', ascending=False)
top_n_values = [10, 25, 50]

sum_df = pd.DataFrame({
    'Top_N': top_n_values,
    'Sum_Alloc%': [df_tmp['CurrAlloc%'].head(n).sum() for n in top_n_values]
})

sum_df

   Top_N  Sum_Alloc%
0     10       21.11
1     25       46.42
2     50       78.64

In [25]:
# market-cap-wise allocation
df_tmp = df_portfolio_features[cols]
df_tmp.groupby(df_tmp['Conviction'].str[-2:])['CurrAlloc%'].sum().sort_values(ascending=False)

Conviction
SC    43.90
MC    30.11
LC    25.96
Name: CurrAlloc%, dtype: float64

In [26]:
# criteria-wise allocation
df_portfolio_features.groupby('Criteria')['CurrAlloc%'].sum().sort_values(ascending=False)

Criteria
XY24     26.98
X40      25.66
X40N     15.28
AR        9.16
XR        8.17
XY25      7.37
OX40N     6.58
SR        0.77
Name: CurrAlloc%, dtype: float64

In [27]:
# conviction-wise allocation
df_portfolio_features.groupby('Conviction')['CurrAlloc%'].sum().sort_values(ascending=False)

Conviction
X-LC    23.72
X-MC    22.57
H-SC    21.38
X-SC    12.27
M-SC     9.75
H-MC     5.15
M-MC     2.05
H-LC     1.18
M-LC     1.06
L-SC     0.50
L-MC     0.34
Name: CurrAlloc%, dtype: float64

In [28]:
# sector-wise stats
df_tmp = df_portfolio_features.groupby('Category')[['CurrAlloc%', 'Current', 'Current P/L', 'FTT Amt']].sum().sort_values(by=['Current', 'Current P/L'], ascending=False)
df_tmp['Current P/L%'] = round(df_tmp['Current P/L'] * 100 / df_tmp['Current'], 2)
df_tmp['FTT%'] = round(df_tmp['FTT Amt'] * 100 / df_tmp['Current'], 2)
cols = ['CurrAlloc%', 'Current P/L%', 'FTT%']
df_tmp[cols].sort_values(by=['CurrAlloc%'], ascending=False)

               CurrAlloc%  Current P/L%    FTT%
Category
FMCG                15.26        -30.65   77.04
FINANCE             13.07        -31.36   84.89
IT                  11.99        -50.00  126.34
MISC                 6.92        -54.82  122.07
ELECTRICAL           6.52        -18.65   64.08
PAINTS               5.23        -50.65   76.81
INSURANCE            4.74        -14.33   53.45
BANKS                4.52        -35.84  104.79
PHARMA               4.22        -11.13   46.11
AUTO                 3.69        -41.94   98.25
AC                   2.00        -27.44   62.00
HEALTHCARE           1.91        -50.12   89.30
APPARELS             1.77        -21.12   62.43
TRAVEL               1.77       -102.89  204.48
FOOTWEAR             1.76        -99.83  179.96
DURABLES             1.75        -76.79  119.79
BREWERIES            1.69        -10.62   33.59
REALTY               1.46        -21.13   41.03
REFINERIES           1.38        -16.28   45.69
CERAMICS             1.37        -79.49  134.02
CEMENT               1.22        -75.23  206.33
CABLES               1.19          0.61  106.64
ENGINEERING          1.04        -85.87  170.89
CHEMICALS            1.01       -109.79  280.94
JEWELLERY            0.98       -161.02  251.71
ENTERTAINMENT        0.73       -110.72  236.39
TEXTILES             0.45        -63.03  109.52
HOTELS               0.33       -176.87  274.53

In [29]:
# money to be made criteria-wise
df_portfolio_features.groupby('Criteria')['FTT Amt'].agg(['sum', 'count']).sort_values(by='sum', ascending=False)

                sum  count
Criteria
XY24      4221977.0     21
X40       1963578.0     16
XR        1468653.0     12
AR        1425235.0     10
X40N      1385915.0     10
OX40N      967351.0     10
XY25       516599.0      5
SR         322432.0      2

In [30]:
# money to be made conviction-wise
df_portfolio_features.groupby('Conviction')['FTT Amt'].agg(['sum', 'count']).sort_values(by='sum', ascending=False)

                  sum  count
Conviction
H-SC        4114311.0     24
X-MC        1905949.0     15
X-LC        1808501.0     13
M-SC        1698891.0     14
X-SC        1646676.0     10
H-MC         434298.0      3
L-SC         228558.0      2
M-LC         159711.0      1
M-MC         129615.0      2
H-LC          85750.0      1
L-MC          59480.0      1

In [31]:
# money to be made criteria and conviction-wise
df_portfolio_features.groupby(['Conviction', 'Criteria'])['FTT Amt'].agg(['sum', 'count']).sort_values(by='sum', ascending=False)

                           sum  count
Conviction Criteria
H-SC       XY24      1422459.0      6
           AR        1018315.0      5
M-SC       XY24       979182.0      6
X-LC       X40        969796.0      7
H-SC       XR         938096.0      7
X-SC       XY24       880781.0      4
X-MC       X40        760605.0      7
           X40N       581483.0      4
X-SC       X40N       532718.0      4
M-SC       OX40N      438371.0      5
H-SC       OX40N      413009.0      4
X-LC       XY24       401424.0      2
H-SC       SR         322432.0      2
X-MC       XY24       286661.0      2
           XY25       277200.0      2
X-LC       X40N       271714.0      2
H-MC       XY24       251470.0      1
X-SC       X40        233177.0      2
M-SC       XR         198779.0      2
H-MC       AR         182828.0      2
X-LC       XY25       165567.0      2
M-LC       XR         159711.0      1
L-SC       OX40N      115971.0      1
           XR         112587.0      1
H-LC       AR          85750.0      1
M-SC       AR          82559.0      1
M-MC       XY25        73832.0      1
L-MC       XR          59480.0      1
M-MC       AR          55783.0      1

In [32]:
# notebook execution time

end_time = time.time()
execution_time = round(end_time - start_time, 0)
print(f"Notebook execution time: {execution_time} seconds")

Notebook execution time: 24.0 seconds