<a href="https://colab.research.google.com/github/ankit-rathi/Quantvesting_v2/blob/main/myStocks_Portfolio_Analysis.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
'''
!pip install pandas==2.2.2 -qq
!pip install pyxirr -qq
!pip install ta -qq
!pip install yfinance==0.2.59 -qq
'''

'\n!pip install pandas==2.2.2 -qq\n!pip install pyxirr -qq\n!pip install ta -qq\n!pip install yfinance==0.2.59 -qq\n'

In [2]:
# import libraries

import numpy as np
import pandas as pd
import datetime
import warnings
warnings.filterwarnings('ignore')
import yfinance as yfin
import ta
import matplotlib.pyplot as plt
import requests

In [3]:
# notebook start time
import time
import datetime
import pytz

start_time = time.time()

# function to print date timestamp
def print_date_time():
  tz_NY = pytz.timezone('Asia/Kolkata')
  datetime_NY = datetime.datetime.now(tz_NY)
  print("Run date time (IST):", datetime_NY.strftime("%Y-%m-%d %H:%M:%S"))

In [4]:
# function to get booked and reserved amount
def get_amt():
  # fetch the JSON data from the URL
  url = "https://raw.githubusercontent.com/ankit-rathi/Tradevesting_v1/main/data/myPortfolioAmts.json"
  response = requests.get(url)
  pf_amts = response.json()  # parse the JSON data

  # extract values from the JSON
  py_booked_amt_dm = pf_amts["py_booked_amt_dm"]
  py_booked_amt_sv = pf_amts["py_booked_amt_sv"]
  cy_booked_amt_dm = pf_amts["cy_booked_amt_dm"]
  cy_booked_amt_sv = pf_amts["cy_booked_amt_sv"]
  reserve_amt_dm = pf_amts["reserve_amt_dm"]
  reserve_amt_sv = pf_amts["reserve_amt_sv"]

  # perform calculations
  py_booked_amt = py_booked_amt_dm + py_booked_amt_sv
  cy_booked_amt = cy_booked_amt_dm + cy_booked_amt_sv
  reserve_amt = reserve_amt_dm + reserve_amt_sv
  total_booked_amt = py_booked_amt + cy_booked_amt

  return total_booked_amt, reserve_amt, cy_booked_amt, py_booked_amt

gen_output = 0

In [5]:
# function to format the amount
def format_amt(number):
    abs_number = abs(number)

    if abs_number >= 1_00_00_000:  # Crores
        formatted_amt = f"{number / 1_00_00_000:.2f} C"
    elif abs_number >= 1_00_000:  # Lakhs
        formatted_amt = f"{number / 1_00_000:.2f} L"
    elif abs_number >= 1_000:  # Thousands
        formatted_amt = f"{number / 1_000:.2f} K"
    else:
        formatted_amt = f"{number:.2f}"

    return formatted_amt

# function to set start and end date
def get_start_end_date():
  start_date = (datetime.date.today() + datetime.timedelta(days=-365)).strftime('%Y-%m-%d')
  end_date = (datetime.date.today() + datetime.timedelta(days=1)).strftime('%Y-%m-%d')
  return start_date, end_date

# function to fetch my portfolio csv
def get_mypfs_df():
  mypfs_df = pd.read_csv('https://raw.githubusercontent.com/ankit-rathi/Tradevesting_v1/main/data/myPortfolioStocks.csv')
  return mypfs_df

# function to fetch my prospects csv
def get_mypps_df():
  mypps_df = pd.read_csv('https://raw.githubusercontent.com/ankit-rathi/Tradevesting_v1/main/data/myProspectsScrips.csv')
  return mypps_df

# function to fetch screener data
def get_myscreen_df():
  myscreen_df = pd.read_csv('https://raw.githubusercontent.com/ankit-rathi/Tradevesting_v1/main/data/myScreenerDB.csv')
  return myscreen_df

# function to fetch momentum data
def get_myinvmt_df():
  myinvmt_df = pd.read_csv('https://raw.githubusercontent.com/ankit-rathi/Tradevesting_v1/main/data/myInvestments.csv')
  return myinvmt_df

# function to get the stock ids
def get_stock_ids(df_pf):
  stock_n100 = df_pf['Symbol'].unique()

  exclude = ['CADILAHC','MMTC', 'MASFIN']

  stock_ids = df_pf[~df_pf['Symbol'].isin(exclude) ]['Symbol'].unique()

  #mypf = mypf[mypf.Forecast.notnull()]
  #stock_ids = mypf['Symbol'].unique()

  #stock_ids.sort()
  return stock_ids

# get features from screener data
def get_screener_features():
  myscreen_df = get_myscreen_df()
  cols = ['Symbol', 'EPS', 'MedPE', 'ROCE%', 'ROE%', 'CapType']
  return myscreen_df[cols]

# get relative strength
def get_relative_strength(stock_list):

    # Dictionary to store stock tickers and their corresponding percentage price change
    stock_changes = {}

    # Loop through each stock and fetch its price data
    for stock in stock_list:
        try:
            # Download the stock data for the given date range
            stock_data = yfin.Ticker(stock + '.NS').history(period='1mo', interval='1d')[map(str.title, ['open', 'close', 'low', 'high', 'volume'])]

            # Calculate the percentage change for the stock
            if len(stock_data) > 0:
                start_price = stock_data['Close'].iloc[0]
                end_price = stock_data['Close'].iloc[-1]
                percent_change = round(((end_price - start_price) / start_price) * 100, 2)
                stock_changes[stock] = percent_change
            else:
                stock_changes[stock] = np.nan  # If no data is available, set to NaN

        except Exception as e:
            print(f"Error fetching data for {stock}: {e}")
            stock_changes[stock] = np.nan

    # Create a DataFrame with stock tickers and their percentage changes
    df = pd.DataFrame(list(stock_changes.items()), columns=['Symbol', 'Percent_Change'])

    # Drop any stocks with missing data (NaN values)
    df = df.dropna()

    # Calculate the percentile rank based on percentage change
    df['RSP'] = round(df['Percent_Change'].rank(pct=True) * 100, 2)
    cols = ['Symbol', 'RSP']
    df = df[cols]
    # Sort by percentile rank (optional)
    df = df.sort_values(by='RSP', ascending=False).reset_index(drop=True)

    return df

In [6]:
# function to get stock technicals
def stock_prec_dev(stock_symbol):
    #stock_symbol = 'ULTRACEMCO.NS'
    short_window = 20
    mid_window = 50
    long_window = 200
    moving_avg = 'SMA'

    start = datetime.datetime(*map(int, start_date.split('-')))
    end = datetime.datetime(*map(int, end_date.split('-')))

    stock_df = yfin.Ticker(stock_symbol + '.NS').history(period='max', interval='1d')[map(str.title, ['open', 'close', 'low', 'high', 'volume'])]

    stock_df['Max'] = round(max(stock_df['Close']),2)
    stock_df = stock_df[(stock_df.index <= end_date) & (stock_df.index >= start_date)]
    stock_df['200_SMA'] = round(stock_df['Close'].rolling(window = 200, min_periods = 1).mean(),0)
    stock_df['Dev%_200'] = round((stock_df['Close'] - stock_df['200_SMA'])*100/stock_df['200_SMA'],2)
    stock_df.dropna(axis = 0, inplace = True) # remove any null rows

    stock_df['20_SMA'] = stock_df['Close'].rolling(window=20).mean()
    stock_df['50_SMA'] = stock_df['Close'].rolling(window=50).mean()
    stock_df['Symbol'] = stock_symbol

    stock_df['Close'] = round(stock_df['Close'],2)
    stock_df['Min'] = round(min(stock_df['Close']),2)
    stock_df['RSI_14'] = ta.momentum.RSIIndicator(close=stock_df['Close'], window=14).rsi()
    stock_df['RSI_14'] = round(stock_df['RSI_14'],0)
    stock_df['Prev_Close'] = stock_df['Close'].shift(1)
    stock_df.drop(['Open', 'Low', 'High', 'Volume'], axis=1, inplace=True)
    stock_df = stock_df.tail(1)

    max_SMA = max(stock_df['20_SMA'].item(), stock_df['50_SMA'].item(), stock_df['200_SMA'].item())
    min_SMA = min(stock_df['20_SMA'].item(), stock_df['50_SMA'].item(), stock_df['200_SMA'].item())
    ABS_Spread = max_SMA - min_SMA
    stock_df['Spread%'] = round((ABS_Spread / stock_df['200_SMA'].item()) * 100,2)

    return stock_df

# function to compute stock attributes
def get_common_features(stock_ids, df_mypf):

  df_prec_dev = pd.DataFrame()
  df_tmp = get_screener_features()
  df_rs = get_relative_strength(stock_ids)

  for stock_id in stock_ids:
      tmp = stock_prec_dev(stock_id)
      tmp = tmp.reset_index()
      df_prec_dev = pd.concat([df_prec_dev, tmp], ignore_index = True)
  df_prec_dev = pd.merge(df_prec_dev, df_mypf, on= 'Symbol')
  df_prec_dev = pd.merge(df_prec_dev, df_tmp, on= 'Symbol', how='left')
  df_prec_dev = pd.merge(df_prec_dev, df_rs, on= 'Symbol', how='left')
  #print(df_prec_dev.columns)
  df_prec_dev['Curr_PE'] = round(df_prec_dev['Close']/df_prec_dev['EPS'],1)
  df_prec_dev['Dev%_PE'] = round((df_prec_dev['Curr_PE'] - df_prec_dev['MedPE'])*100/df_prec_dev['MedPE'],2)
  df_prec_dev['Conviction'] = df_prec_dev['Conviction'] + '-' + df_prec_dev['CapType']
  return df_prec_dev

# function to arrange stock features
def arrange_features(df_stocks, common_cols, diff_cols):
  df_stocks_common = df_stocks[common_cols].drop_duplicates()
  df_stocks_diff = df_stocks[diff_cols]
  df_stocks_diff['Investment'] = df_stocks_diff['AvgCost'] * df_stocks_diff['Shares']
  df_stocks_diff = df_stocks_diff.groupby(['Symbol'])[['Shares', 'Investment']].aggregate(['sum']).reset_index()
  df_stocks_diff.columns = ['Symbol', 'Shares', 'Investment']
  df_stocks_diff['AvgCost'] = round(df_stocks_diff['Investment']/df_stocks_diff['Shares'],2)
  df_stocks = pd.merge(df_stocks_diff, df_stocks_common, on='Symbol')
  return df_stocks

# plot fact distribution across dimension
def plot_pie_chart(df, dimension, fact):
  # grouping the data by category and calculating the sum of fact for each type
  grouped_data = df.groupby(dimension)[fact].sum()

  # sorting the grouped data in descending order
  grouped_data = grouped_data.sort_values(ascending=False)

  # creating a pie chart
  grouped_data.plot.pie(autopct='%1.1f%%', startangle=90, figsize=(6, 6))

  # adding a title and displaying the plot
  plt.title(f'{dimension} {fact} Distribution')
  plt.ylabel('')  # To hide the y-label
  plt.show()

In [7]:
# function to get portfolio features

def get_portfolio_features(df_common_features):

  print_date_time()
  print('-------------------')

  #df_common_features["Target"] = df_common_features["Target"].fillna(df_common_features["Max"])
  df_common_features['NTT'] = np.where(df_common_features['Strategy']== 'NTT', df_common_features["Target"], df_common_features['Max'])
  df_common_features['LTT'] = np.where(df_common_features['Strategy']== 'BTT', df_common_features["Target"], df_common_features['Max'])
  df_common_features['BOL'] = df_common_features['Min']

  tmp_df = df_common_features[df_common_features['Symbol'].isin(mypf_df[mypf_df['InPortfolio'] != 'NA'].Symbol.values)]
  print('qualified stocks: '+str(len(tmp_df['Symbol'].unique())))
  tmp_df1 = tmp_df[tmp_df['LatestQtr'] == 1]
  print('with latest results: '+str(len(tmp_df1['Symbol'].unique())))
  tmp_df1 = tmp_df1[tmp_df1['StarStock'] == 1]
  print('still star stocks: '+str(len(tmp_df1['Symbol'].unique())))
  tmp_df['Investment'] = tmp_df['AvgCost'] * tmp_df['Shares']
  tmp_df['Current'] = round(tmp_df['Close'] * tmp_df['Shares'],0)
  tmp_df['Previous'] = tmp_df['Prev_Close'] * tmp_df['Shares']
  tmp_df['EstimatedST'] = tmp_df['NTT'] * tmp_df['Shares']
  tmp_df['EstimatedLT'] = tmp_df['LTT'] * tmp_df['Shares']
  tmp_df['Current P/L'] = round((tmp_df['Current'] - tmp_df['Investment']),0)
  tmp_df['Today P/L%'] = round((tmp_df['Current'] - tmp_df['Previous'])*100/tmp_df['Previous'],2)
  tmp_df['Current P/L%'] = round((tmp_df['Current'] - tmp_df['Investment'])*100/tmp_df['Investment'],2)
  tmp_df['EstimatedST P/L%'] = round((tmp_df['EstimatedST'] - tmp_df['Investment'])*100/tmp_df['Investment'],2)
  tmp_df['EstimatedLT P/L%'] = round((tmp_df['EstimatedLT'] - tmp_df['Investment'])*100/tmp_df['Investment'],2)
  tmp_df['NTT%'] = round((tmp_df['NTT'] - tmp_df['Close'])*100/tmp_df['Close'],2)
  tmp_df['LTT%'] = round((tmp_df['LTT'] - tmp_df['Close'])*100/tmp_df['Close'],2)
  tmp_df['Gained%'] = round((tmp_df['Close'] - tmp_df['BOL'])*100/tmp_df['BOL'],2)
  investment = round(sum(tmp_df['AvgCost']*tmp_df['Shares']),0)
  current = round(sum(tmp_df['Close']*tmp_df['Shares']),0)
  tmp_df['InitAlloc%'] = round(tmp_df['Investment']*100/investment,2)
  tmp_df['CurrAlloc%'] = round(tmp_df['Current']*100/current,2)
  tmp_df['FTT'] = tmp_df['LTT']
  tmp_df.loc[tmp_df['Strategy'] == 'NTT', 'FTT'] = tmp_df['NTT']
  tmp_df['FTT%'] = tmp_df['LTT%']
  tmp_df.loc[tmp_df['Strategy'] == 'NTT', 'FTT%'] = tmp_df['NTT%']
  tmp_df['FTT Amt'] = round(tmp_df['FTT%'] * tmp_df['Current']/100,0)
  tmp_df['OTT%'] = round((tmp_df['FTT'] - tmp_df['AvgCost'])*100/tmp_df['AvgCost'],2)
  tmp_df['RRR Ind'] = round(tmp_df['Current P/L']/tmp_df['FTT Amt'],2)
  tmp_df['Risk Ind'] = round(tmp_df['Current P/L%']*tmp_df['CurrAlloc%'],0)

  return tmp_df

# function to print portfolio features
def print_portfolio_stats(df_portfolio_features, myinvmt_df):
  from pyxirr import xirr

  total_booked_amt, reserve_amt, cy_booked_amt, py_booked_amt = get_amt()

  dates = myinvmt_df['Date'].values
  dates = np.append(dates, datetime.date.today().strftime('%d-%b-%y'))
  investment = myinvmt_df['Investment'].values
  dates= pd.to_datetime(dates)

  current = round(sum(df_portfolio_features['Close']*df_portfolio_features['Shares']),0) + reserve_amt
  investment_xirr = np.append(investment, current)
  cagr = round(xirr(pd.DataFrame({"dates": dates, "amounts": investment_xirr}))*100,2)

  investment = -sum(investment)
  invested = round(sum(df_portfolio_features['AvgCost']*df_portfolio_features['Shares']),0) + reserve_amt
  previous = round(sum(df_portfolio_features['Prev_Close']*df_portfolio_features['Shares']),0) + reserve_amt
  cy_invested = investment + py_booked_amt

  today_pnl_amount = current-previous
  today_pnl_percentage = round((current-previous)*100/previous,2)

  curr_pnl_amount = current-invested
  curr_pnl_percentage = round((curr_pnl_amount)*100/(cy_invested),2)

  cy_pnl_amount = cy_booked_amt + curr_pnl_amount
  cy_pnl_percentage = round((cy_pnl_amount)*100/cy_invested,2)

  overall_pnl_amount = total_booked_amt + curr_pnl_amount
  overall_pnl_percentage = round((overall_pnl_amount)*100/investment,2)

  estimate_st = round(sum(df_portfolio_features['FTT']*df_portfolio_features['Shares']),0)  + reserve_amt
  est_st_pnl_amount = estimate_st-current
  est_st_pnl_percentage = round((est_st_pnl_amount)*100/current,2)

  estimate_lt = round(sum(df_portfolio_features['LTT']*df_portfolio_features['Shares']),0)  + reserve_amt
  est_lt_pnl_amount = estimate_lt-current
  est_lt_pnl_percentage = round((est_lt_pnl_amount)*100/current,2)

  total_profit = round(sum(df_portfolio_features[df_portfolio_features['Current P/L%'] > 0]['Current']) - sum(df_portfolio_features[df_portfolio_features['Current P/L%'] > 0]['Investment']),0)
  total_loss = round(sum(df_portfolio_features[df_portfolio_features['Current P/L%'] < 0]['Current']) - sum(df_portfolio_features[df_portfolio_features['Current P/L%'] < 0]['Investment']),0)

  cy_booked_percentage = round((cy_booked_amt)*100/current,2)
  py_booked_percentage = round((py_booked_amt)*100/investment,2)
  total_booked_percentage = round((total_booked_amt)*100/investment,2)

  print('-------------------')
  print('Initial Investment: ', format_amt(investment))
  print('CY Investment: ', format_amt(cy_invested))
  print('Reserve: ', format_amt(reserve_amt))
  print('Current: ',  format_amt(current))
  print('-------------------')
  print('Today PnL: '+ '{} ({}%)'.format(format_amt(today_pnl_amount), today_pnl_percentage))
  print('Current PnL: '+ '{} ({}%)'.format(format_amt(curr_pnl_amount), curr_pnl_percentage))
  print('CY Booked + Current PnL: '+ '{} ({}%)'.format(format_amt(cy_pnl_amount), cy_pnl_percentage))
  print('-------------------')
  print('Total profit: ', format_amt(total_profit))
  print('Total loss: ', format_amt(total_loss))
  print('-------------------')
  print('Total Booked + Current PnL: '+ '{} ({}%)'.format(format_amt(overall_pnl_amount), overall_pnl_percentage))
  print('Total Booked PnL: '+ '{} ({}%)'.format(format_amt(total_booked_amt), total_booked_percentage))
  print('Curr Year Booked PnL: '+ '{} ({}%)'.format(format_amt(cy_booked_amt), cy_booked_percentage))
  print('Prev Year Booked PnL: '+ '{} ({}%)'.format(format_amt(py_booked_amt), py_booked_percentage))
  print('===================')
  print('Est FTT: ',  format_amt(estimate_st))
  print('Est FTT PnL: '+ '{} ({}%)'.format(format_amt(est_st_pnl_amount), est_st_pnl_percentage))

  print('===================')
  print('Deployed: ', format_amt(investment))

  print('Current: ', format_amt(current))

  print('CAGR/XIRR %: '+'{}%'.format(cagr))

In [8]:
# get start and end date
start_date, end_date = get_start_end_date()

# get portfolio and prospects data
mypfs_df = get_mypfs_df()
mypps_df = get_mypps_df()
myinvmt_df = get_myinvmt_df()

# merge above datasets
mypf_df = pd.merge(mypfs_df, mypps_df, on="Symbol")

# seggregate dm and sv portfolio
dm_pf = mypf_df[mypf_df['InPortfolio'] == 'DM']
sv_pf = mypf_df[mypf_df['InPortfolio'] == 'SV']

# build portfolio stock dataframe
dm_stocks = get_stock_ids(dm_pf)
sv_stocks = get_stock_ids(sv_pf)
df_stocks = pd.concat([dm_pf,sv_pf], ignore_index = True)

# arrange common and diff stock features
common_cols = ['Symbol', 'Target', 'Criteria', 'Strategy', 'CumlRnk', 'LatestQtr', 'StarStock', 'Conviction', 'Category', 'InFolio', 'XIRR', 'MBQ']
diff_cols = ['Symbol', 'AvgCost', 'Shares']
df_stocks = arrange_features(df_stocks, common_cols, diff_cols)

# get common features
stock_ids = df_stocks['Symbol'].values
df_common_features = get_common_features(stock_ids, df_stocks)

df_common_features.reset_index(drop=True, inplace=True)
df_common_features.drop(['Date'], axis=1, inplace=True)
# get and print portfolio features
df_portfolio_features = get_portfolio_features(df_common_features)

print_portfolio_stats(df_portfolio_features, myinvmt_df)

df = df_portfolio_features
#plot_pie_chart(df, 'CapType', 'Current')
list_ox40n = list(df[df['MBQ'].str.contains('OX40N', na=False)]['Symbol'].values)

Run date time (IST): 2026-06-05 16:01:20
-------------------
qualified stocks: 92
with latest results: 31
still star stocks: 20
-------------------
Initial Investment:  1.40 C
CY Investment:  1.82 C
Reserve:  1.49 K
Current:  1.48 C
-------------------
Today PnL: -5.14 K (-0.03%)
Current PnL: -34.83 L (-19.1%)
CY Booked + Current PnL: -32.75 L (-17.96%)
-------------------
Total profit:  2.47 L
Total loss:  -37.29 L
-------------------
Total Booked + Current PnL: 10.12 L (7.26%)
Total Booked PnL: 44.95 L (32.22%)
Curr Year Booked PnL: 2.08 L (1.4%)
Prev Year Booked PnL: 42.87 L (30.73%)
===================
Est FTT:  2.55 C
Est FTT PnL: 1.07 C (72.0%)
===================
Deployed:  1.40 C
Current:  1.48 C
CAGR/XIRR %: 2.92%

In [9]:
# top 5 near their targets
cols = ['Symbol', 'Today P/L%', 'Current P/L%', 'FTT%', 'OTT%', 'FTT Amt', 'Current P/L', 'Current', 'FTT', 'Dev%_PE', 'RSI_14','Conviction', 'Spread%',  'CumlRnk', 'RRR Ind', 'CurrAlloc%', 'Gained%', 'Criteria', 'Strategy', 'Category']
df_tmp = df_portfolio_features[~df_portfolio_features['Symbol'].isin(['ENRIN','BLUSPRING','DIGITIDE'])]
df_tmp = df_tmp.sort_values(by = 'FTT Amt', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
59,PIDILITIND,0.37,4.64,13.12,18.37,19373.0,6550.0,147660.0,1670.26,-26.75,59.0,X-LC,4.20,5.0,0.34,1.00,15.94,X40,ATH,CHEMICALS
55,MASFIN,0.10,-6.26,29.69,21.57,27269.0,-6135.0,91845.0,397.04,-19.15,41.0,H-SC,0.96,167.0,-0.22,0.62,9.48,XR,ATH,FINANCE
51,KOTAKBANK,-1.06,0.85,20.08,21.11,28043.0,1184.0,139656.0,453.24,-13.31,45.0,X-LC,7.06,12.0,0.04,0.94,6.81,X40,ATH,BANKS
72,SIS,-1.64,-4.22,26.60,21.26,28289.0,-4684.0,106348.0,528.00,2535.23,67.0,H-SC,19.33,168.0,-0.17,0.72,58.12,OX40N,NTT,MISC
17,CIPLA,1.13,13.45,17.62,33.43,30617.0,20600.0,173761.0,1648.14,-12.20,61.0,X-LC,8.11,18.0,0.67,1.17,18.62,X40N,ATH,PHARMA

In [10]:
# top 5 today
df_tmp = df_portfolio_features.sort_values(by = 'Today P/L%', ascending=False)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
60,QUESS,9.61,-3.33,79.88,73.90,82469.0,-3552.0,103241.0,424.00,-48.21,72.0,X-SC,6.14,80.0,-0.04,0.70,40.74,XY24,NTT,MISC
29,GREENPANEL,6.22,-46.18,165.96,43.14,163524.0,-84546.0,98532.0,537.00,120.93,52.0,M-SC,17.58,225.0,-0.52,0.66,18.36,XY24,NTT,MISC
31,HATHWAY,4.82,-38.85,183.39,73.29,121918.0,-42240.0,66480.0,31.40,671.74,59.0,H-SC,12.25,171.0,-0.35,0.45,24.92,XR,NTT,ENTERTAINMENT
25,FINCABLES,3.87,33.94,55.23,107.91,109218.0,50108.0,197752.0,1641.55,20.24,52.0,M-SC,26.11,220.0,0.46,1.33,48.78,OX40N,ATH,CABLES
69,SFL,3.15,-36.76,100.23,26.63,166211.0,-96388.0,165830.0,1287.00,25.58,66.0,M-SC,7.90,242.0,-0.58,1.12,38.21,XY24,NTT,MISC

In [11]:
# bottom 5 today
df_tmp = df_portfolio_features.sort_values(by = 'Today P/L%', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
61,RAJESHEXPO,-5.00,-80.93,424.66,0.07,111104.0,-111014.0,26163.0,518.0,858.33,35.0,L-SC,30.17,268.0,-1.00,0.18,22.83,OX40N,NTT,JEWELLERY
18,COFFEEDAY,-4.99,-35.02,108.17,35.27,79814.0,-39763.0,73786.0,80.0,-49.70,74.0,L-SC,20.21,266.0,-0.50,0.50,81.96,XR,NTT,HOTELS
14,CAMPUS,-3.21,-17.55,61.66,33.28,85291.0,-29451.0,138324.0,393.0,-33.59,47.0,M-SC,6.63,218.0,-0.35,0.93,11.08,XY24,NTT,FOOTWEAR
86,VALIANTORG,-3.08,-40.73,193.83,74.15,187953.0,-66637.0,96968.0,838.0,-274.67,49.0,H-SC,6.63,145.0,-0.35,0.65,44.30,XR,NTT,CHEMICALS
80,TITAGARH,-3.02,-21.12,84.75,45.74,161907.0,-51136.0,191041.0,1548.0,5.17,58.0,H-SC,6.07,175.0,-0.32,1.29,45.76,XY24,NTT,ENGINEERING

In [12]:
# top 5 to exit based on CumlRnk
df_tmp = df_portfolio_features[~df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])]
df_tmp = df_tmp[(df_tmp['Current P/L%'] > -1) & (df_tmp['Current P/L%'] < 1)].sort_values(by = 'CumlRnk', ascending=False)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
9,BANDHANBNK,0.21,-0.97,94.3,92.42,260142.0,-2693.0,275866.0,400.0,136.35,62.0,H-SC,20.33,174.0,-0.01,1.86,51.97,XY24,NTT,BANKS

In [13]:
# OX40N stocks to exit
df_tmp = df_portfolio_features[(df_portfolio_features['Symbol'].isin(list_ox40n))].sort_values(by = 'Current P/L%', ascending=False)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
25,FINCABLES,3.87,33.94,55.23,107.91,109218.0,50108.0,197752.0,1641.55,20.24,52.0,M-SC,26.11,220.0,0.46,1.33,48.78,OX40N,ATH,CABLES
72,SIS,-1.64,-4.22,26.60,21.26,28289.0,-4684.0,106348.0,528.00,2535.23,67.0,H-SC,19.33,168.0,-0.17,0.72,58.12,OX40N,NTT,MISC
16,CERA,-0.40,-27.92,71.88,23.89,91135.0,-49115.0,126788.0,9475.00,-30.55,47.0,H-SC,6.12,153.0,-0.54,0.85,21.84,OX40N,NTT,CERAMICS
50,KANSAINER,-1.29,-29.62,61.22,13.47,116196.0,-79866.0,189801.0,340.00,-39.58,48.0,H-SC,9.71,162.0,-0.69,1.28,32.58,XY24,NTT,PAINTS
83,TTKPRESTIG,-2.01,-30.63,44.29,0.09,30962.0,-30869.0,69908.0,770.00,62.22,53.0,M-SC,13.92,250.0,-1.00,0.47,24.48,OX40N,NTT,DURABLES

In [14]:
# top 5 to book for rotation
df_tmp = df_portfolio_features[(df_portfolio_features['Current P/L%'] > 20) ].sort_values(by = 'CumlRnk', ascending=False)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
25,FINCABLES,3.87,33.94,55.23,107.91,109218.0,50108.0,197752.0,1641.55,20.24,52.0,M-SC,26.11,220.0,0.46,1.33,48.78,OX40N,ATH,CABLES
68,SATIN,-0.22,33.76,13.51,51.83,49929.0,93284.0,369568.0,274.00,19.58,75.0,H-SC,40.79,159.0,1.87,2.49,80.03,XY24,NTT,FINANCE

In [15]:
# top 5 to monitor for exit
df_tmp = df_portfolio_features[~df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])]
df_tmp = df_tmp[(df_tmp['Current P/L%'] > 0) ].sort_values(by = 'Dev%_PE', ascending=False)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
74,STARHEALTH,-0.05,1.79,44.68,47.26,127849.0,5021.0,286144.0,761.00,60.64,58.0,H-SC,9.76,173.0,0.04,1.93,25.63,XY24,NTT,INSURANCE
25,FINCABLES,3.87,33.94,55.23,107.91,109218.0,50108.0,197752.0,1641.55,20.24,52.0,M-SC,26.11,220.0,0.46,1.33,48.78,OX40N,ATH,CABLES
68,SATIN,-0.22,33.76,13.51,51.83,49929.0,93284.0,369568.0,274.00,19.58,75.0,H-SC,40.79,159.0,1.87,2.49,80.03,XY24,NTT,FINANCE
91,ZYDUSLIFE,0.41,14.84,18.11,35.63,43585.0,31095.0,240669.0,1286.17,0.00,71.0,H-MC,9.36,120.0,0.71,1.62,26.54,AR,ATH,PHARMA
73,SONACOMS,0.19,4.19,33.49,39.09,35299.0,4243.0,105402.0,804.02,-17.50,55.0,M-MC,18.86,193.0,0.12,0.71,49.11,AR,ATH,AUTO

In [16]:
# top 5 to book for rotation from weak conviction
df_tmp = df_portfolio_features[~df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])]
df_tmp = df_tmp[~df_tmp['Criteria'].isin(['XY25','XY24','X40', 'X40N'])].sort_values(by = 'RRR Ind', ascending=False)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
91,ZYDUSLIFE,0.41,14.84,18.11,35.63,43585.0,31095.0,240669.0,1286.17,0.00,71.0,H-MC,9.36,120.0,0.71,1.62,26.54,AR,ATH,PHARMA
25,FINCABLES,3.87,33.94,55.23,107.91,109218.0,50108.0,197752.0,1641.55,20.24,52.0,M-SC,26.11,220.0,0.46,1.33,48.78,OX40N,ATH,CABLES
73,SONACOMS,0.19,4.19,33.49,39.09,35299.0,4243.0,105402.0,804.02,-17.50,55.0,M-MC,18.86,193.0,0.12,0.71,49.11,AR,ATH,AUTO
75,SURYODAY,0.26,-2.12,25.71,23.03,45061.0,-3804.0,175267.0,216.00,90.79,66.0,H-SC,19.05,166.0,-0.08,1.18,47.57,XR,NTT,BANKS
42,INDIAMART,0.31,-14.04,140.48,106.72,148938.0,-17315.0,106021.0,4810.62,-61.13,44.0,H-SC,11.31,140.0,-0.12,0.71,2.64,AR,ATH,MISC

In [17]:
# top 5 to accumulate based on lowest RSI_14
df_tmp = df_portfolio_features[df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])].sort_values(by = 'RSI_14', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
27,GLAXO,-0.12,-13.12,56.19,35.69,97281.0,-26156.0,173128.0,3380.16,-33.67,28.0,X-MC,8.04,56.0,-0.27,1.17,0.00,X40,ATH,PHARMA
65,RELIANCE,-0.52,-17.13,51.20,25.30,85268.0,-34424.0,166539.0,1952.00,-19.26,33.0,X-LC,6.04,21.0,-0.40,1.12,0.00,XY25,BTT,REFINERIES
40,ICICIPRULI,1.64,-20.03,62.91,30.28,99108.0,-39465.0,157540.0,787.27,-41.55,34.0,X-MC,14.07,78.0,-0.40,1.06,1.68,X40,ATH,INSURANCE
35,HDFCLIFE,0.27,-5.91,41.54,33.18,58550.0,-8852.0,140948.0,814.30,-26.54,35.0,X-LC,15.06,31.0,-0.15,0.95,1.63,X40,ATH,INSURANCE
47,ITC,0.14,-26.06,61.03,19.06,153495.0,-88659.0,251507.0,452.00,-59.56,36.0,X-LC,14.54,1.0,-0.58,1.70,1.34,X40,NTT,FMCG

In [18]:
# top 5 to accumulate based on Spread and CumlRnk
df_tmp = df_portfolio_features[df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])]
df_tmp = df_tmp[(df_tmp['CumlRnk'] < 100)].sort_values(by = 'Spread%', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
57,PAGEIND,-1.26,0.01,33.57,33.59,90107.0,36.0,268415.0,51217.29,-28.28,57.0,X-MC,2.91,55.0,0.00,1.81,27.47,X40,ATH,APPARELS
49,JSWINFRA,1.94,-5.32,22.98,16.43,48250.0,-11808.0,209966.0,342.00,-18.74,55.0,X-MC,3.65,61.0,-0.24,1.42,18.69,X40N,NTT,REALTY
23,DMART,0.12,-0.38,30.10,29.60,74844.0,-948.0,248652.0,5391.45,-16.03,44.0,X-LC,3.93,14.0,-0.01,1.68,13.65,X40N,ATH,FMCG
59,PIDILITIND,0.37,4.64,13.12,18.37,19373.0,6550.0,147660.0,1670.26,-26.75,59.0,X-LC,4.20,5.0,0.34,1.00,15.94,X40,ATH,CHEMICALS
19,COLPAL,-0.24,-24.08,84.22,39.86,168398.0,-63415.0,199950.0,3683.41,-8.09,39.0,X-MC,4.31,62.0,-0.38,1.35,13.10,XY25,ATH,FMCG

In [19]:
# top 5 to accumulate based on lowest Gained%
df_tmp = df_portfolio_features[df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])].sort_values(by = 'Gained%', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
27,GLAXO,-0.12,-13.12,56.19,35.69,97281.0,-26156.0,173128.0,3380.16,-33.67,28.0,X-MC,8.04,56.0,-0.27,1.17,0.00,X40,ATH,PHARMA
65,RELIANCE,-0.52,-17.13,51.20,25.30,85268.0,-34424.0,166539.0,1952.00,-19.26,33.0,X-LC,6.04,21.0,-0.40,1.12,0.00,XY25,BTT,REFINERIES
79,TCS,-1.88,-35.45,93.46,24.88,279492.0,-164223.0,299050.0,4253.91,-45.26,39.0,X-LC,18.36,2.0,-0.59,2.02,0.00,X40,ATH,IT
32,HAVELLS,-1.36,-26.34,78.41,31.42,189442.0,-86386.0,241605.0,2052.62,-30.65,37.0,X-MC,13.95,63.0,-0.46,1.63,0.64,X40,ATH,ELECTRICAL
47,ITC,0.14,-26.06,61.03,19.06,153495.0,-88659.0,251507.0,452.00,-59.56,36.0,X-LC,14.54,1.0,-0.58,1.70,1.34,X40,NTT,FMCG

In [20]:
# top 5 to accumulate based on lowest CurrAlloc%
df_tmp = df_portfolio_features[df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])].sort_values(by = 'CurrAlloc%', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
10,BATAINDIA,1.07,-57.13,215.38,35.20,118808.0,-73508.0,55162.0,2096.00,-27.65,37.0,X-SC,25.37,91.0,-0.62,0.37,9.40,X40,NTT,FOOTWEAR
64,RELAXO,-2.12,-57.25,256.31,52.31,159038.0,-83111.0,62049.0,1176.00,-54.51,62.0,X-SC,22.30,92.0,-0.52,0.42,38.73,X40N,NTT,FOOTWEAR
60,QUESS,9.61,-3.33,79.88,73.90,82469.0,-3552.0,103241.0,424.00,-48.21,72.0,X-SC,6.14,80.0,-0.04,0.70,40.74,XY24,NTT,MISC
28,GODREJCP,0.26,-10.69,47.20,31.47,62650.0,-15880.0,132734.0,1469.04,-6.00,40.0,X-LC,10.05,32.0,-0.25,0.89,1.84,X40N,ATH,FMCG
53,M&M,0.81,-1.34,25.06,23.38,34288.0,-1859.0,136822.0,3802.40,-16.52,44.0,X-LC,9.72,25.0,-0.05,0.92,3.73,X40N,ATH,AUTO

In [21]:
# top 5 to accumulate based on CumlRnk
df_tmp = df_portfolio_features.sort_values(by = 'CumlRnk', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
47,ITC,0.14,-26.06,61.03,19.06,153495.0,-88659.0,251507.0,452.00,-59.56,36.0,X-LC,14.54,1.0,-0.58,1.70,1.34,X40,NTT,FMCG
79,TCS,-1.88,-35.45,93.46,24.88,279492.0,-164223.0,299050.0,4253.91,-45.26,39.0,X-LC,18.36,2.0,-0.59,2.02,0.00,X40,ATH,IT
45,INFY,-0.32,-18.48,64.68,34.24,164978.0,-57820.0,255068.0,1972.00,-35.78,51.0,X-LC,17.70,3.0,-0.35,1.72,9.36,X40,NTT,IT
81,TMPV,-0.48,-9.45,50.83,36.58,163783.0,-33623.0,322218.0,600.00,-81.44,67.0,X-LC,17.78,4.0,-0.21,2.17,34.30,XY24,NTT,AUTO
59,PIDILITIND,0.37,4.64,13.12,18.37,19373.0,6550.0,147660.0,1670.26,-26.75,59.0,X-LC,4.20,5.0,0.34,1.00,15.94,X40,ATH,CHEMICALS

In [22]:
# top 5 for average up
df_tmp = df_portfolio_features[(df_portfolio_features['Dev%_200'] > 5)].sort_values(by = 'CurrAlloc%', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
44,INDUSINDBK,0.18,-33.20,98.94,32.89,51027.0,-25632.0,51574.0,1800.00,-343.00,50.0,L-MC,7.56,258.0,-0.50,0.35,26.94,XR,NTT,BANKS
18,COFFEEDAY,-4.99,-35.02,108.17,35.27,79814.0,-39763.0,73786.0,80.00,-49.70,74.0,L-SC,20.21,266.0,-0.50,0.50,81.96,XR,NTT,HOTELS
3,ALKYLAMINE,-1.42,-24.39,156.09,93.63,119156.0,-24625.0,76338.0,4546.37,-19.07,58.0,H-SC,9.29,142.0,-0.21,0.51,44.15,SR,ATH,CHEMICALS
60,QUESS,9.61,-3.33,79.88,73.90,82469.0,-3552.0,103241.0,424.00,-48.21,72.0,X-SC,6.14,80.0,-0.04,0.70,40.74,XY24,NTT,MISC
73,SONACOMS,0.19,4.19,33.49,39.09,35299.0,4243.0,105402.0,804.02,-17.50,55.0,M-MC,18.86,193.0,0.12,0.71,49.11,AR,ATH,AUTO

In [23]:
# top 5 RSP
df_tmp = df_portfolio_features.sort_values(by = 'RSP', ascending=False)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
18,COFFEEDAY,-4.99,-35.02,108.17,35.27,79814.0,-39763.0,73786.0,80.00,-49.70,74.0,L-SC,20.21,266.0,-0.50,0.50,81.96,XR,NTT,HOTELS
68,SATIN,-0.22,33.76,13.51,51.83,49929.0,93284.0,369568.0,274.00,19.58,75.0,H-SC,40.79,159.0,1.87,2.49,80.03,XY24,NTT,FINANCE
69,SFL,3.15,-36.76,100.23,26.63,166211.0,-96388.0,165830.0,1287.00,25.58,66.0,M-SC,7.90,242.0,-0.58,1.12,38.21,XY24,NTT,MISC
91,ZYDUSLIFE,0.41,14.84,18.11,35.63,43585.0,31095.0,240669.0,1286.17,0.00,71.0,H-MC,9.36,120.0,0.71,1.62,26.54,AR,ATH,PHARMA
81,TMPV,-0.48,-9.45,50.83,36.58,163783.0,-33623.0,322218.0,600.00,-81.44,67.0,X-LC,17.78,4.0,-0.21,2.17,34.30,XY24,NTT,AUTO

In [24]:
# Top N allocation
df_tmp = df_portfolio_features.sort_values(by = 'CurrAlloc%', ascending=False)
top_n_values = [10, 25, 50]

sum_df = pd.DataFrame({
    'Top_N': top_n_values,
    'Sum_Alloc%': [df_tmp['CurrAlloc%'].head(n).sum() for n in top_n_values]
})

sum_df

   Top_N  Sum_Alloc%
0     10       19.80
1     25       42.80
2     50       72.73

In [25]:
# market-cap-wise allocation
df_tmp = df_portfolio_features[cols]
df_tmp.groupby(df_tmp['Conviction'].str[-2:])['CurrAlloc%'].sum().sort_values(ascending=False)

Conviction
SC    43.16
LC    31.41
MC    25.44
Name: CurrAlloc%, dtype: float64

In [26]:
# criteria-wise allocation
df_portfolio_features.groupby('Criteria')['CurrAlloc%'].sum().sort_values(ascending=False)

Criteria
XY24     27.88
X40      24.92
X40N     16.96
XR        9.11
OX40N     6.90
AR        6.88
XY25      6.49
SR        0.87
Name: CurrAlloc%, dtype: float64

In [27]:
# conviction-wise allocation
df_portfolio_features.groupby('Conviction')['CurrAlloc%'].sum().sort_values(ascending=False)

Conviction
X-LC    29.23
H-SC    22.69
X-MC    20.32
M-SC     9.97
X-SC     9.82
H-MC     2.78
M-MC     1.99
H-LC     1.25
M-LC     0.93
L-SC     0.68
L-MC     0.35
Name: CurrAlloc%, dtype: float64

In [28]:
# sector-wise stats
df_tmp = df_portfolio_features.groupby('Category')[['CurrAlloc%', 'Current', 'Current P/L', 'FTT Amt']].sum().sort_values(by=['Current', 'Current P/L'], ascending=False)
df_tmp['Current P/L%'] = round(df_tmp['Current P/L'] * 100 / df_tmp['Current'], 2)
df_tmp['FTT%'] = round(df_tmp['FTT Amt'] * 100 / df_tmp['Current'], 2)
cols = ['CurrAlloc%', 'Current P/L%', 'FTT%']
df_tmp[cols].sort_values(by=['CurrAlloc%'], ascending=False)

               CurrAlloc%  Current P/L%    FTT%
Category
FMCG                14.83        -20.31   62.52
FINANCE             10.92        -13.78   63.27
IT                  10.28        -47.68  121.51
MISC                 7.09        -27.52   82.92
AUTO                 6.90         -6.89   46.97
BANKS                5.75         -6.56   55.83
PAINTS               5.50        -20.90   41.90
INSURANCE            5.20         -7.40   43.72
PHARMA               5.01          0.39   30.44
ELECTRICAL           4.05        -17.79   59.36
CHEMICALS            2.16        -26.39  101.72
HEALTHCARE           2.07        -16.24   46.58
AC                   1.83        -17.63   49.53
APPARELS             1.81          0.01   33.57
FOOTWEAR             1.72        -72.82  142.11
TRAVEL               1.60        -87.88  181.95
DURABLES             1.58        -65.57  105.85
BREWERIES            1.45         -9.19   31.87
REALTY               1.42         -5.62   22.98
CABLES               1.33         25.34   55.23
CERAMICS             1.31        -57.32  105.11
ENGINEERING          1.29        -26.77   84.75
REFINERIES           1.12        -20.67   51.20
CEMENT               1.08        -68.03  193.73
JEWELLERY            1.05       -106.40  178.11
ENTERTAINMENT        0.75        -75.14  179.59
HOTELS               0.50        -53.89  108.17
TEXTILES             0.41        -53.26   96.96

In [29]:
# money to be made criteria-wise
df_portfolio_features.groupby('Criteria')['FTT Amt'].agg(['sum', 'count']).sort_values(by='sum', ascending=False)

                sum  count
Criteria
XY24      3459926.0     21
X40       1988602.0     19
XR        1331941.0     13
X40N      1205779.0     13
AR        1163895.0      9
OX40N      768306.0     10
XY25       473529.0      5
SR         289845.0      2

In [30]:
# money to be made conviction-wise
df_portfolio_features.groupby('Conviction')['FTT Amt'].agg(['sum', 'count']).sort_values(by='sum', ascending=False)

                  sum  count
Conviction
H-SC        3418307.0     24
X-LC        1953301.0     21
X-MC        1703401.0     15
M-SC        1438763.0     14
X-SC        1347116.0      9
H-MC         284959.0      2
L-SC         190918.0      2
M-LC         154039.0      1
M-MC          91456.0      2
L-MC          51027.0      1
H-LC          48536.0      1

In [31]:
# money to be made criteria and conviction-wise
df_portfolio_features.groupby(['Conviction', 'Criteria'])['FTT Amt'].agg(['sum', 'count']).sort_values(by='sum', ascending=False)

                           sum  count
Conviction Criteria
X-LC       X40       1059388.0     10
H-SC       XY24      1032536.0      6
           AR         960300.0      5
M-SC       XY24       840619.0      6
H-SC       XR         806800.0      7
X-SC       XY24       792111.0      4
X-MC       X40        713920.0      7
           X40N       496534.0      4
X-LC       X40N       369534.0      6
X-SC       X40N       339711.0      3
H-SC       OX40N      328826.0      4
M-SC       OX40N      328376.0      5
X-LC       XY24       312399.0      2
H-SC       SR         289845.0      2
X-MC       XY25       252060.0      2
H-MC       XY24       241374.0      1
X-MC       XY24       240887.0      2
X-SC       X40        215294.0      2
M-SC       XR         193593.0      2
X-LC       XY25       165312.0      2
M-LC       XR         154039.0      1
L-SC       OX40N      111104.0      1
           XR          79814.0      1
M-SC       AR          76175.0      1
M-MC       XY25        56157.0      1
L-MC       XR          51027.0      1
H-LC       AR          48536.0      1
X-LC       XR          46668.0      1
H-MC       AR          43585.0      1
M-MC       AR          35299.0      1

In [32]:
# notebook execution time

end_time = time.time()
execution_time = round(end_time - start_time, 0)
print(f"Notebook execution time: {execution_time} seconds")

Notebook execution time: 33.0 seconds