<a href="https://colab.research.google.com/github/ankit-rathi/Quantvesting_v2/blob/main/myStocks_Portfolio_Analysis.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
'''
!pip install pandas==2.2.2 -qq
!pip install pyxirr -qq
!pip install ta -qq
!pip install yfinance==0.2.59 -qq
'''

'\n!pip install pandas==2.2.2 -qq\n!pip install pyxirr -qq\n!pip install ta -qq\n!pip install yfinance==0.2.59 -qq\n'

In [2]:
# import libraries

import numpy as np
import pandas as pd
import datetime
import warnings
warnings.filterwarnings('ignore')
import yfinance as yfin
import ta
import matplotlib.pyplot as plt
import requests

In [3]:
# notebook start time
import time
import datetime
import pytz

start_time = time.time()

# function to print date timestamp
def print_date_time():
  tz_NY = pytz.timezone('Asia/Kolkata')
  datetime_NY = datetime.datetime.now(tz_NY)
  print("Run date time (IST):", datetime_NY.strftime("%Y-%m-%d %H:%M:%S"))

In [4]:
# function to get booked and reserved amount
def get_amt():
  # fetch the JSON data from the URL
  url = "https://raw.githubusercontent.com/ankit-rathi/Tradevesting_v1/main/data/myPortfolioAmts.json"
  response = requests.get(url)
  pf_amts = response.json()  # parse the JSON data

  # extract values from the JSON
  py_booked_amt_dm = pf_amts["py_booked_amt_dm"]
  py_booked_amt_sv = pf_amts["py_booked_amt_sv"]
  cy_booked_amt_dm = pf_amts["cy_booked_amt_dm"]
  cy_booked_amt_sv = pf_amts["cy_booked_amt_sv"]
  reserve_amt_dm = pf_amts["reserve_amt_dm"]
  reserve_amt_sv = pf_amts["reserve_amt_sv"]

  # perform calculations
  py_booked_amt = py_booked_amt_dm + py_booked_amt_sv
  cy_booked_amt = cy_booked_amt_dm + cy_booked_amt_sv
  reserve_amt = reserve_amt_dm + reserve_amt_sv
  total_booked_amt = py_booked_amt + cy_booked_amt

  return total_booked_amt, reserve_amt, cy_booked_amt, py_booked_amt

gen_output = 0

In [5]:
# function to format the amount
def format_amt(number):
    abs_number = abs(number)

    if abs_number >= 1_00_00_000:  # Crores
        formatted_amt = f"{number / 1_00_00_000:.2f} C"
    elif abs_number >= 1_00_000:  # Lakhs
        formatted_amt = f"{number / 1_00_000:.2f} L"
    elif abs_number >= 1_000:  # Thousands
        formatted_amt = f"{number / 1_000:.2f} K"
    else:
        formatted_amt = f"{number:.2f}"

    return formatted_amt

# function to set start and end date
def get_start_end_date():
  start_date = (datetime.date.today() + datetime.timedelta(days=-365)).strftime('%Y-%m-%d')
  end_date = (datetime.date.today() + datetime.timedelta(days=1)).strftime('%Y-%m-%d')
  return start_date, end_date

# function to fetch my portfolio csv
def get_mypfs_df():
  mypfs_df = pd.read_csv('https://raw.githubusercontent.com/ankit-rathi/Tradevesting_v1/main/data/myPortfolioStocks.csv')
  return mypfs_df

# function to fetch my prospects csv
def get_mypps_df():
  mypps_df = pd.read_csv('https://raw.githubusercontent.com/ankit-rathi/Tradevesting_v1/main/data/myProspectsScrips.csv')
  return mypps_df

# function to fetch screener data
def get_myscreen_df():
  myscreen_df = pd.read_csv('https://raw.githubusercontent.com/ankit-rathi/Tradevesting_v1/main/data/myScreenerDB.csv')
  return myscreen_df

# function to fetch momentum data
def get_myinvmt_df():
  myinvmt_df = pd.read_csv('https://raw.githubusercontent.com/ankit-rathi/Tradevesting_v1/main/data/myInvestments.csv')
  return myinvmt_df

# function to get the stock ids
def get_stock_ids(df_pf):
  stock_n100 = df_pf['Symbol'].unique()

  exclude = ['CADILAHC','MMTC', 'MASFIN']

  stock_ids = df_pf[~df_pf['Symbol'].isin(exclude) ]['Symbol'].unique()

  #mypf = mypf[mypf.Forecast.notnull()]
  #stock_ids = mypf['Symbol'].unique()

  #stock_ids.sort()
  return stock_ids

# get features from screener data
def get_screener_features():
  myscreen_df = get_myscreen_df()
  cols = ['Symbol', 'EPS', 'MedPE', 'ROCE%', 'ROE%', 'CapType']
  return myscreen_df[cols]

# get relative strength
def get_relative_strength(stock_list):

    # Dictionary to store stock tickers and their corresponding percentage price change
    stock_changes = {}

    # Loop through each stock and fetch its price data
    for stock in stock_list:
        try:
            # Download the stock data for the given date range
            stock_data = yfin.Ticker(stock + '.NS').history(period='1mo', interval='1d')[map(str.title, ['open', 'close', 'low', 'high', 'volume'])]

            # Calculate the percentage change for the stock
            if len(stock_data) > 0:
                start_price = stock_data['Close'].iloc[0]
                end_price = stock_data['Close'].iloc[-1]
                percent_change = round(((end_price - start_price) / start_price) * 100, 2)
                stock_changes[stock] = percent_change
            else:
                stock_changes[stock] = np.nan  # If no data is available, set to NaN

        except Exception as e:
            print(f"Error fetching data for {stock}: {e}")
            stock_changes[stock] = np.nan

    # Create a DataFrame with stock tickers and their percentage changes
    df = pd.DataFrame(list(stock_changes.items()), columns=['Symbol', 'Percent_Change'])

    # Drop any stocks with missing data (NaN values)
    df = df.dropna()

    # Calculate the percentile rank based on percentage change
    df['RSP'] = round(df['Percent_Change'].rank(pct=True) * 100, 2)
    cols = ['Symbol', 'RSP']
    df = df[cols]
    # Sort by percentile rank (optional)
    df = df.sort_values(by='RSP', ascending=False).reset_index(drop=True)

    return df

In [6]:
# function to get stock technicals
def stock_prec_dev(stock_symbol):
    #stock_symbol = 'ULTRACEMCO.NS'
    short_window = 20
    mid_window = 50
    long_window = 200
    moving_avg = 'SMA'

    start = datetime.datetime(*map(int, start_date.split('-')))
    end = datetime.datetime(*map(int, end_date.split('-')))

    stock_df = yfin.Ticker(stock_symbol + '.NS').history(period='max', interval='1d')[map(str.title, ['open', 'close', 'low', 'high', 'volume'])]

    stock_df['Max'] = round(max(stock_df['Close']),2)
    stock_df = stock_df[(stock_df.index <= end_date) & (stock_df.index >= start_date)]
    stock_df['200_SMA'] = round(stock_df['Close'].rolling(window = 200, min_periods = 1).mean(),0)
    stock_df['Dev%_200'] = round((stock_df['Close'] - stock_df['200_SMA'])*100/stock_df['200_SMA'],2)
    stock_df.dropna(axis = 0, inplace = True) # remove any null rows

    stock_df['20_SMA'] = stock_df['Close'].rolling(window=20).mean()
    stock_df['50_SMA'] = stock_df['Close'].rolling(window=50).mean()
    stock_df['Symbol'] = stock_symbol

    stock_df['Close'] = round(stock_df['Close'],2)
    stock_df['Min'] = round(min(stock_df['Close']),2)
    stock_df['RSI_14'] = ta.momentum.RSIIndicator(close=stock_df['Close'], window=14).rsi()
    stock_df['RSI_14'] = round(stock_df['RSI_14'],0)
    stock_df['Prev_Close'] = stock_df['Close'].shift(1)
    stock_df.drop(['Open', 'Low', 'High', 'Volume'], axis=1, inplace=True)
    stock_df = stock_df.tail(1)

    max_SMA = max(stock_df['20_SMA'].item(), stock_df['50_SMA'].item(), stock_df['200_SMA'].item())
    min_SMA = min(stock_df['20_SMA'].item(), stock_df['50_SMA'].item(), stock_df['200_SMA'].item())
    ABS_Spread = max_SMA - min_SMA
    stock_df['Spread%'] = round((ABS_Spread / stock_df['200_SMA'].item()) * 100,2)

    return stock_df

# function to compute stock attributes
def get_common_features(stock_ids, df_mypf):

  df_prec_dev = pd.DataFrame()
  df_tmp = get_screener_features()
  df_rs = get_relative_strength(stock_ids)

  for stock_id in stock_ids:
      tmp = stock_prec_dev(stock_id)
      tmp = tmp.reset_index()
      df_prec_dev = pd.concat([df_prec_dev, tmp], ignore_index = True)
  df_prec_dev = pd.merge(df_prec_dev, df_mypf, on= 'Symbol')
  df_prec_dev = pd.merge(df_prec_dev, df_tmp, on= 'Symbol', how='left')
  df_prec_dev = pd.merge(df_prec_dev, df_rs, on= 'Symbol', how='left')
  #print(df_prec_dev.columns)
  df_prec_dev['Curr_PE'] = round(df_prec_dev['Close']/df_prec_dev['EPS'],1)
  df_prec_dev['Dev%_PE'] = round((df_prec_dev['Curr_PE'] - df_prec_dev['MedPE'])*100/df_prec_dev['MedPE'],2)
  df_prec_dev['Conviction'] = df_prec_dev['Conviction'] + '-' + df_prec_dev['CapType']
  return df_prec_dev

# function to arrange stock features
def arrange_features(df_stocks, common_cols, diff_cols):
  df_stocks_common = df_stocks[common_cols].drop_duplicates()
  df_stocks_diff = df_stocks[diff_cols]
  df_stocks_diff['Investment'] = df_stocks_diff['AvgCost'] * df_stocks_diff['Shares']
  df_stocks_diff = df_stocks_diff.groupby(['Symbol'])[['Shares', 'Investment']].aggregate(['sum']).reset_index()
  df_stocks_diff.columns = ['Symbol', 'Shares', 'Investment']
  df_stocks_diff['AvgCost'] = round(df_stocks_diff['Investment']/df_stocks_diff['Shares'],2)
  df_stocks = pd.merge(df_stocks_diff, df_stocks_common, on='Symbol')
  return df_stocks

# plot fact distribution across dimension
def plot_pie_chart(df, dimension, fact):
  # grouping the data by category and calculating the sum of fact for each type
  grouped_data = df.groupby(dimension)[fact].sum()

  # sorting the grouped data in descending order
  grouped_data = grouped_data.sort_values(ascending=False)

  # creating a pie chart
  grouped_data.plot.pie(autopct='%1.1f%%', startangle=90, figsize=(6, 6))

  # adding a title and displaying the plot
  plt.title(f'{dimension} {fact} Distribution')
  plt.ylabel('')  # To hide the y-label
  plt.show()

In [7]:
# function to get portfolio features

def get_portfolio_features(df_common_features):

  print_date_time()
  print('-------------------')

  #df_common_features["Target"] = df_common_features["Target"].fillna(df_common_features["Max"])
  df_common_features['NTT'] = np.where(df_common_features['Strategy']== 'NTT', df_common_features["Target"], df_common_features['Max'])
  df_common_features['LTT'] = np.where(df_common_features['Strategy']== 'BTT', df_common_features["Target"], df_common_features['Max'])
  df_common_features['BOL'] = df_common_features['Min']

  tmp_df = df_common_features[df_common_features['Symbol'].isin(mypf_df[mypf_df['InPortfolio'] != 'NA'].Symbol.values)]
  print('qualified stocks: '+str(len(tmp_df['Symbol'].unique())))
  tmp_df1 = tmp_df[tmp_df['LatestQtr'] == 1]
  print('with latest results: '+str(len(tmp_df1['Symbol'].unique())))
  tmp_df1 = tmp_df1[tmp_df1['StarStock'] == 1]
  print('still star stocks: '+str(len(tmp_df1['Symbol'].unique())))
  tmp_df['Investment'] = tmp_df['AvgCost'] * tmp_df['Shares']
  tmp_df['Current'] = round(tmp_df['Close'] * tmp_df['Shares'],0)
  tmp_df['Previous'] = tmp_df['Prev_Close'] * tmp_df['Shares']
  tmp_df['EstimatedST'] = tmp_df['NTT'] * tmp_df['Shares']
  tmp_df['EstimatedLT'] = tmp_df['LTT'] * tmp_df['Shares']
  tmp_df['Current P/L'] = round((tmp_df['Current'] - tmp_df['Investment']),0)
  tmp_df['Today P/L%'] = round((tmp_df['Current'] - tmp_df['Previous'])*100/tmp_df['Previous'],2)
  tmp_df['Current P/L%'] = round((tmp_df['Current'] - tmp_df['Investment'])*100/tmp_df['Investment'],2)
  tmp_df['EstimatedST P/L%'] = round((tmp_df['EstimatedST'] - tmp_df['Investment'])*100/tmp_df['Investment'],2)
  tmp_df['EstimatedLT P/L%'] = round((tmp_df['EstimatedLT'] - tmp_df['Investment'])*100/tmp_df['Investment'],2)
  tmp_df['NTT%'] = round((tmp_df['NTT'] - tmp_df['Close'])*100/tmp_df['Close'],2)
  tmp_df['LTT%'] = round((tmp_df['LTT'] - tmp_df['Close'])*100/tmp_df['Close'],2)
  tmp_df['Gained%'] = round((tmp_df['Close'] - tmp_df['BOL'])*100/tmp_df['BOL'],2)
  investment = round(sum(tmp_df['AvgCost']*tmp_df['Shares']),0)
  current = round(sum(tmp_df['Close']*tmp_df['Shares']),0)
  tmp_df['InitAlloc%'] = round(tmp_df['Investment']*100/investment,2)
  tmp_df['CurrAlloc%'] = round(tmp_df['Current']*100/current,2)
  tmp_df['FTT'] = tmp_df['LTT']
  tmp_df.loc[tmp_df['Strategy'] == 'NTT', 'FTT'] = tmp_df['NTT']
  tmp_df['FTT%'] = tmp_df['LTT%']
  tmp_df.loc[tmp_df['Strategy'] == 'NTT', 'FTT%'] = tmp_df['NTT%']
  tmp_df['FTT Amt'] = round(tmp_df['FTT%'] * tmp_df['Current']/100,0)
  tmp_df['OTT%'] = round((tmp_df['FTT'] - tmp_df['AvgCost'])*100/tmp_df['AvgCost'],2)
  tmp_df['RRR Ind'] = round(tmp_df['Current P/L']/tmp_df['FTT Amt'],2)
  tmp_df['Risk Ind'] = round(tmp_df['Current P/L%']*tmp_df['CurrAlloc%'],0)

  return tmp_df

# function to print portfolio features
def print_portfolio_stats(df_portfolio_features, myinvmt_df):
  from pyxirr import xirr

  total_booked_amt, reserve_amt, cy_booked_amt, py_booked_amt = get_amt()

  dates = myinvmt_df['Date'].values
  dates = np.append(dates, datetime.date.today().strftime('%d-%b-%y'))
  investment = myinvmt_df['Investment'].values
  dates= pd.to_datetime(dates)

  current = round(sum(df_portfolio_features['Close']*df_portfolio_features['Shares']),0) + reserve_amt
  investment_xirr = np.append(investment, current)
  cagr = round(xirr(pd.DataFrame({"dates": dates, "amounts": investment_xirr}))*100,2)

  investment = -sum(investment)
  invested = round(sum(df_portfolio_features['AvgCost']*df_portfolio_features['Shares']),0) + reserve_amt
  previous = round(sum(df_portfolio_features['Prev_Close']*df_portfolio_features['Shares']),0) + reserve_amt
  cy_invested = investment + py_booked_amt

  today_pnl_amount = current-previous
  today_pnl_percentage = round((current-previous)*100/previous,2)

  curr_pnl_amount = current-invested
  curr_pnl_percentage = round((curr_pnl_amount)*100/(cy_invested),2)

  cy_pnl_amount = cy_booked_amt + curr_pnl_amount
  cy_pnl_percentage = round((cy_pnl_amount)*100/cy_invested,2)

  overall_pnl_amount = total_booked_amt + curr_pnl_amount
  overall_pnl_percentage = round((overall_pnl_amount)*100/investment,2)

  estimate_st = round(sum(df_portfolio_features['FTT']*df_portfolio_features['Shares']),0)  + reserve_amt
  est_st_pnl_amount = estimate_st-current
  est_st_pnl_percentage = round((est_st_pnl_amount)*100/current,2)

  estimate_lt = round(sum(df_portfolio_features['LTT']*df_portfolio_features['Shares']),0)  + reserve_amt
  est_lt_pnl_amount = estimate_lt-current
  est_lt_pnl_percentage = round((est_lt_pnl_amount)*100/current,2)

  total_profit = round(sum(df_portfolio_features[df_portfolio_features['Current P/L%'] > 0]['Current']) - sum(df_portfolio_features[df_portfolio_features['Current P/L%'] > 0]['Investment']),0)
  total_loss = round(sum(df_portfolio_features[df_portfolio_features['Current P/L%'] < 0]['Current']) - sum(df_portfolio_features[df_portfolio_features['Current P/L%'] < 0]['Investment']),0)

  cy_booked_percentage = round((cy_booked_amt)*100/current,2)
  py_booked_percentage = round((py_booked_amt)*100/investment,2)
  total_booked_percentage = round((total_booked_amt)*100/investment,2)

  print('-------------------')
  print('Initial Investment: ', format_amt(investment))
  print('CY Investment: ', format_amt(cy_invested))
  print('Reserve: ', format_amt(reserve_amt))
  print('Current: ',  format_amt(current))
  print('-------------------')
  print('Today PnL: '+ '{} ({}%)'.format(format_amt(today_pnl_amount), today_pnl_percentage))
  print('Current PnL: '+ '{} ({}%)'.format(format_amt(curr_pnl_amount), curr_pnl_percentage))
  print('CY Booked + Current PnL: '+ '{} ({}%)'.format(format_amt(cy_pnl_amount), cy_pnl_percentage))
  print('-------------------')
  print('Total profit: ', format_amt(total_profit))
  print('Total loss: ', format_amt(total_loss))
  print('-------------------')
  print('Total Booked + Current PnL: '+ '{} ({}%)'.format(format_amt(overall_pnl_amount), overall_pnl_percentage))
  print('Total Booked PnL: '+ '{} ({}%)'.format(format_amt(total_booked_amt), total_booked_percentage))
  print('Curr Year Booked PnL: '+ '{} ({}%)'.format(format_amt(cy_booked_amt), cy_booked_percentage))
  print('Prev Year Booked PnL: '+ '{} ({}%)'.format(format_amt(py_booked_amt), py_booked_percentage))
  print('===================')
  print('Est FTT: ',  format_amt(estimate_st))
  print('Est FTT PnL: '+ '{} ({}%)'.format(format_amt(est_st_pnl_amount), est_st_pnl_percentage))

  print('===================')
  print('Deployed: ', format_amt(investment))

  print('Current: ', format_amt(current))

  print('CAGR/XIRR %: '+'{}%'.format(cagr))

In [8]:
# get start and end date
start_date, end_date = get_start_end_date()

# get portfolio and prospects data
mypfs_df = get_mypfs_df()
mypps_df = get_mypps_df()
myinvmt_df = get_myinvmt_df()

# merge above datasets
mypf_df = pd.merge(mypfs_df, mypps_df, on="Symbol")

# seggregate dm and sv portfolio
dm_pf = mypf_df[mypf_df['InPortfolio'] == 'DM']
sv_pf = mypf_df[mypf_df['InPortfolio'] == 'SV']

# build portfolio stock dataframe
dm_stocks = get_stock_ids(dm_pf)
sv_stocks = get_stock_ids(sv_pf)
df_stocks = pd.concat([dm_pf,sv_pf], ignore_index = True)

# arrange common and diff stock features
common_cols = ['Symbol', 'Target', 'Criteria', 'Strategy', 'CumlRnk', 'LatestQtr', 'StarStock', 'Conviction', 'Category', 'InFolio', 'XIRR', 'MBQ']
diff_cols = ['Symbol', 'AvgCost', 'Shares']
df_stocks = arrange_features(df_stocks, common_cols, diff_cols)

# get common features
stock_ids = df_stocks['Symbol'].values
df_common_features = get_common_features(stock_ids, df_stocks)

df_common_features.reset_index(drop=True, inplace=True)
df_common_features.drop(['Date'], axis=1, inplace=True)
# get and print portfolio features
df_portfolio_features = get_portfolio_features(df_common_features)

print_portfolio_stats(df_portfolio_features, myinvmt_df)

df = df_portfolio_features
#plot_pie_chart(df, 'CapType', 'Current')
list_ox40n = list(df[df['MBQ'].str.contains('OX40N', na=False)]['Symbol'].values)

Run date time (IST): 2026-03-04 11:31:54
-------------------
qualified stocks: 86
with latest results: 26
still star stocks: 15
-------------------
Initial Investment:  1.33 C
CY Investment:  1.60 C
Reserve:  2.44 L
Current:  1.34 C
-------------------
Today PnL: -2.77 L (-2.03%)
Current PnL: -40.35 L (-25.22%)
CY Booked + Current PnL: -24.67 L (-15.42%)
-------------------
Total profit:  81.59 K
Total loss:  -41.17 L
-------------------
Total Booked + Current PnL: 2.31 L (1.73%)
Total Booked PnL: 42.66 L (32.07%)
Curr Year Booked PnL: 15.68 L (11.69%)
Prev Year Booked PnL: 26.98 L (20.29%)
===================
Est FTT:  2.41 C
Est FTT PnL: 1.07 C (79.78%)
===================
Deployed:  1.33 C
Current:  1.34 C
CAGR/XIRR %: 0.41%

In [9]:
# top 5 near their targets
cols = ['Symbol', 'Today P/L%', 'Current P/L%', 'FTT%', 'OTT%', 'FTT Amt', 'Current P/L', 'Current', 'FTT', 'Dev%_PE', 'RSI_14','Conviction', 'Spread%',  'CumlRnk', 'RRR Ind', 'CurrAlloc%', 'Gained%', 'Criteria', 'Strategy', 'Category']
df_tmp = df_portfolio_features[~df_portfolio_features['Symbol'].isin(['ENRIN','BLUSPRING','DIGITIDE'])]
df_tmp = df_tmp.sort_values(by = 'FTT Amt', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
19,COALINDIA,1.91,6.82,10.15,17.67,16314.0,10268.0,160728.0,478.51,29.12,58.0,L-LC,11.00,185.0,0.63,1.22,27.78,XY25,ATH,MINING
50,MASFIN,-3.76,-7.07,30.82,21.57,28062.0,-6930.0,91050.0,397.04,-20.05,36.0,H-SC,6.47,167.0,-0.25,0.69,31.86,XR,ATH,FINANCE
77,TTKPRESTIG,-2.82,-36.69,58.11,0.09,37072.0,-36980.0,63797.0,770.00,48.13,22.0,M-SC,12.50,250.0,-1.00,0.48,0.00,OX40N,NTT,DURABLES
51,MEDANTA,-1.77,-7.32,33.87,24.08,39851.0,-9290.0,117660.0,1486.00,-7.89,44.0,X-SC,8.03,87.0,-0.23,0.89,7.77,XY24,NTT,HEALTHCARE
37,ICICIGI,-1.71,-1.31,20.92,19.34,41315.0,-2620.0,197489.0,2252.93,-16.89,42.0,X-MC,1.30,66.0,-0.06,1.50,14.42,X40,ATH,INSURANCE

In [10]:
# top 5 today
df_tmp = df_portfolio_features.sort_values(by = 'Today P/L%', ascending=False)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
8,AWL,2.45,-40.14,162.59,57.19,317421.0,-130899.0,195228.0,485.00,-65.82,24.0,X-SC,19.76,81.0,-0.41,1.48,2.45,XY24,NTT,FMCG
19,COALINDIA,1.91,6.82,10.15,17.67,16314.0,10268.0,160728.0,478.51,29.12,58.0,L-LC,11.00,185.0,0.63,1.22,27.78,XY25,ATH,MINING
80,VALIANTORG,1.10,-52.74,268.48,74.15,207597.0,-86282.0,77323.0,838.00,-239.11,35.0,H-SC,23.55,145.0,-0.42,0.59,1.10,XR,NTT,CHEMICALS
43,INFY,0.68,-11.67,51.97,34.24,143639.0,-36499.0,276389.0,1972.00,-30.33,26.0,X-LC,10.11,3.0,-0.25,2.10,1.73,X40,NTT,IT
2,ABBOTINDIA,0.43,-9.69,30.74,18.07,49651.0,-17335.0,161520.0,35195.00,-23.22,50.0,X-MC,11.44,58.0,-0.35,1.23,2.40,X40,ATH,PHARMA

In [11]:
# bottom 5 today
df_tmp = df_portfolio_features.sort_values(by = 'Today P/L%', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
7,ATULAUTO,-4.99,-21.76,86.05,45.57,132724.0,-42891.0,154241.0,844.00,3332.43,45.0,M-SC,7.20,248.0,-0.32,1.17,16.72,XY24,NTT,AUTO
27,FINCABLES,-4.90,14.00,82.38,107.91,138653.0,20665.0,168309.0,1641.55,2.49,65.0,M-SC,6.40,220.0,0.15,1.28,26.62,OX40N,ATH,CABLES
65,SIEMENS,-4.80,-14.53,46.85,25.51,74520.0,-27035.0,159060.0,4671.50,33.57,49.0,H-LC,3.71,51.0,-0.36,1.21,17.13,AR,ATH,ELECTRICAL
55,RAJESHEXPO,-4.70,-74.48,292.13,0.07,102263.0,-102171.0,35006.0,518.00,1182.83,24.0,L-SC,11.10,268.0,-1.00,0.27,0.00,OX40N,NTT,JEWELLERY
12,BATAINDIA,-4.62,-52.66,185.58,35.20,113052.0,-67752.0,60918.0,2096.00,-20.14,19.0,X-SC,23.02,91.0,-0.60,0.46,0.00,X40,NTT,FOOTWEAR

In [12]:
# top 5 to exit based on CumlRnk
df_tmp = df_portfolio_features[~df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])]
df_tmp = df_tmp[(df_tmp['Current P/L%'] > -1) & (df_tmp['Current P/L%'] < 1)].sort_values(by = 'CumlRnk', ascending=False)
df_tmp[cols].head()

Empty DataFrame
Columns: [Symbol, Today P/L%, Current P/L%, FTT%, OTT%, FTT Amt, Current P/L, Current, FTT, Dev%_PE, RSI_14, Conviction, Spread%, CumlRnk, RRR Ind, CurrAlloc%, Gained%, Criteria, Strategy, Category]
Index: []

In [13]:
# OX40N stocks to exit
df_tmp = df_portfolio_features[(df_portfolio_features['Symbol'].isin(list_ox40n))].sort_values(by = 'Current P/L%', ascending=False)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
27,FINCABLES,-4.90,14.00,82.38,107.91,138653.0,20665.0,168309.0,1641.55,2.49,65.0,M-SC,6.40,220.0,0.15,1.28,26.62,OX40N,ATH,CABLES
66,SIS,-2.10,-31.48,76.97,21.26,58558.0,-34953.0,76079.0,528.00,1784.97,37.0,H-SC,6.47,168.0,-0.60,0.58,4.88,OX40N,NTT,MISC
48,KANSAINER,-0.19,-34.61,73.52,13.47,129650.0,-93321.0,176346.0,340.00,-43.73,31.0,H-SC,14.11,162.0,-0.72,1.34,0.00,XY24,NTT,PAINTS
41,INDIGOPNTS,-0.88,-35.35,54.70,0.02,61734.0,-61700.0,112859.0,1408.00,71.88,22.0,M-SC,13.16,222.0,-1.00,0.86,0.00,OX40N,NTT,PAINTS
77,TTKPRESTIG,-2.82,-36.69,58.11,0.09,37072.0,-36980.0,63797.0,770.00,48.13,22.0,M-SC,12.50,250.0,-1.00,0.48,0.00,OX40N,NTT,DURABLES

In [14]:
# top 5 to book for rotation
df_tmp = df_portfolio_features[(df_portfolio_features['Current P/L%'] > 20) ].sort_values(by = 'CumlRnk', ascending=False)
df_tmp[cols].head()

Empty DataFrame
Columns: [Symbol, Today P/L%, Current P/L%, FTT%, OTT%, FTT Amt, Current P/L, Current, FTT, Dev%_PE, RSI_14, Conviction, Spread%, CumlRnk, RRR Ind, CurrAlloc%, Gained%, Criteria, Strategy, Category]
Index: []

In [15]:
# top 5 to monitor for exit
df_tmp = df_portfolio_features[~df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])]
df_tmp = df_tmp[(df_tmp['Current P/L%'] > 0) ].sort_values(by = 'Dev%_PE', ascending=False)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
19,COALINDIA,1.91,6.82,10.15,17.67,16314.0,10268.0,160728.0,478.51,29.12,58.0,L-LC,11.00,185.0,0.63,1.22,27.78,XY25,ATH,MINING
27,FINCABLES,-4.90,14.00,82.38,107.91,138653.0,20665.0,168309.0,1641.55,2.49,65.0,M-SC,6.40,220.0,0.15,1.28,26.62,OX40N,ATH,CABLES
1,ABB,-2.65,6.86,36.22,45.57,101262.0,17957.0,279576.0,7934.00,-31.30,53.0,H-MC,8.86,125.0,0.18,2.12,24.15,AR,NTT,ELECTRICAL

In [16]:
# top 5 to book for rotation from weak conviction
df_tmp = df_portfolio_features[~df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])]
df_tmp = df_tmp[~df_tmp['Criteria'].isin(['XY25','XY24','X40', 'X40N'])].sort_values(by = 'RRR Ind', ascending=False)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
1,ABB,-2.65,6.86,36.22,45.57,101262.0,17957.0,279576.0,7934.00,-31.30,53.0,H-MC,8.86,125.0,0.18,2.12,24.15,AR,NTT,ELECTRICAL
27,FINCABLES,-4.90,14.00,82.38,107.91,138653.0,20665.0,168309.0,1641.55,2.49,65.0,M-SC,6.40,220.0,0.15,1.28,26.62,OX40N,ATH,CABLES
40,INDIAMART,-2.97,-11.86,134.55,106.72,146260.0,-14633.0,108703.0,4810.62,-60.16,31.0,H-SC,8.25,140.0,-0.10,0.83,8.74,AR,ATH,MISC
85,ZYDUSLIFE,-1.95,-6.23,44.64,35.63,87723.0,-13061.0,196513.0,1286.17,-18.47,44.0,H-MC,4.97,120.0,-0.15,1.49,9.40,AR,ATH,PHARMA
84,WIPRO,-1.30,-19.61,114.30,72.27,155691.0,-33235.0,136213.0,420.00,-27.37,20.0,M-LC,11.39,98.0,-0.21,1.03,0.00,XR,NTT,IT

In [17]:
# top 5 to accumulate based on lowest RSI_14
df_tmp = df_portfolio_features[df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])].sort_values(by = 'RSI_14', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
12,BATAINDIA,-4.62,-52.66,185.58,35.20,113052.0,-67752.0,60918.0,2096.00,-20.14,19.0,X-SC,23.02,91.0,-0.60,0.46,0.00,X40,NTT,FOOTWEAR
3,ACC,-2.46,-36.33,157.82,64.15,239097.0,-86451.0,151500.0,3906.00,-52.08,22.0,X-SC,9.96,85.0,-0.36,1.15,0.00,XY24,BTT,CEMENT
9,BAJAJHFL,-2.02,-28.42,117.21,55.47,204108.0,-69147.0,174139.0,181.50,-38.66,22.0,X-MC,17.76,60.0,-0.34,1.32,0.00,X40N,ATH,FINANCE
53,PGHH,-0.15,-16.05,57.25,32.01,102619.0,-34272.0,179248.0,17616.87,-43.24,23.0,X-MC,9.79,57.0,-0.33,1.36,0.00,X40,ATH,FMCG
17,CAMS,-3.98,-18.06,51.90,24.48,107112.0,-45474.0,206382.0,950.00,-21.57,24.0,X-SC,6.52,89.0,-0.42,1.57,1.28,X40N,NTT,MISC

In [18]:
# top 5 to accumulate based on Spread and CumlRnk
df_tmp = df_portfolio_features[df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])]
df_tmp = df_tmp[(df_tmp['CumlRnk'] < 100)].sort_values(by = 'Spread%', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
37,ICICIGI,-1.71,-1.31,20.92,19.34,41315.0,-2620.0,197489.0,2252.93,-16.89,42.0,X-MC,1.30,66.0,-0.06,1.50,14.42,X40,ATH,INSURANCE
78,UNITDSPR,-2.58,-2.20,23.49,20.77,53788.0,-5160.0,228984.0,1644.00,-13.25,37.0,X-MC,1.38,64.0,-0.10,1.74,4.75,X40N,NTT,BREWERIES
22,DABUR,-3.02,-3.76,49.31,43.70,117723.0,-9327.0,238741.0,735.00,-12.63,37.0,X-MC,1.48,70.0,-0.08,1.81,10.72,XY24,BTT,FMCG
59,RELIANCE,-1.04,-13.73,45.25,25.30,78447.0,-27600.0,173363.0,1952.00,-15.80,32.0,X-LC,2.18,21.0,-0.35,1.32,16.13,XY25,BTT,REFINERIES
35,HINDUNILVR,-0.95,-10.58,27.12,13.67,62338.0,-27203.0,229860.0,2922.00,-33.67,42.0,X-LC,2.53,9.0,-0.44,1.75,8.51,XY25,NTT,FMCG

In [19]:
# top 5 to accumulate based on lowest Gained%
df_tmp = df_portfolio_features[df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])].sort_values(by = 'Gained%', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
3,ACC,-2.46,-36.33,157.82,64.15,239097.0,-86451.0,151500.0,3906.00,-52.08,22.0,X-SC,9.96,85.0,-0.36,1.15,0.0,XY24,BTT,CEMENT
12,BATAINDIA,-4.62,-52.66,185.58,35.20,113052.0,-67752.0,60918.0,2096.00,-20.14,19.0,X-SC,23.02,91.0,-0.60,0.46,0.0,X40,NTT,FOOTWEAR
10,BAJAJHLDNG,-1.27,-5.59,36.86,29.22,66165.0,-10622.0,179503.0,14451.52,-12.59,37.0,X-LC,11.85,28.0,-0.16,1.36,0.0,X40,ATH,FINANCE
9,BAJAJHFL,-2.02,-28.42,117.21,55.47,204108.0,-69147.0,174139.0,181.50,-38.66,22.0,X-MC,17.76,60.0,-0.34,1.32,0.0,X40N,ATH,FINANCE
24,DIXON,-3.09,-31.80,92.45,31.26,145509.0,-73376.0,157392.0,18931.72,-69.52,33.0,X-MC,24.24,54.0,-0.50,1.20,0.0,X40N,ATH,IT

In [20]:
# top 5 to accumulate based on lowest CurrAlloc%
df_tmp = df_portfolio_features[df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])].sort_values(by = 'CurrAlloc%', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
54,QUESS,-0.57,-35.75,122.33,42.84,51091.0,-23241.0,41765.0,424.00,-58.13,34.0,X-SC,16.95,80.0,-0.45,0.32,0.46,XY24,NTT,MISC
12,BATAINDIA,-4.62,-52.66,185.58,35.20,113052.0,-67752.0,60918.0,2096.00,-20.14,19.0,X-SC,23.02,91.0,-0.60,0.46,0.00,X40,NTT,FOOTWEAR
58,RELAXO,-1.50,-57.90,261.73,52.31,159967.0,-84041.0,61119.0,1176.00,-55.18,25.0,X-SC,15.89,92.0,-0.53,0.46,0.00,X40N,NTT,FOOTWEAR
51,MEDANTA,-1.77,-7.32,33.87,24.08,39851.0,-9290.0,117660.0,1486.00,-7.89,44.0,X-SC,8.03,87.0,-0.23,0.89,7.77,XY24,NTT,HEALTHCARE
36,HONAUT,-1.19,-26.42,94.78,43.32,113584.0,-43032.0,119840.0,58357.33,-35.45,31.0,X-SC,12.56,90.0,-0.38,0.91,0.00,X40N,ATH,ELECTRICAL

In [21]:
# top 5 to accumulate based on CumlRnk
df_tmp = df_portfolio_features.sort_values(by = 'CumlRnk', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
45,ITC,-1.27,-18.11,45.38,19.06,126413.0,-61600.0,278566.0,452.00,-55.12,37.0,X-LC,16.90,1.0,-0.49,2.12,0.86,X40,NTT,FMCG
73,TCS,-0.86,-25.74,66.41,23.58,213357.0,-111357.0,321272.0,4311.59,-35.76,28.0,X-LC,10.81,2.0,-0.52,2.44,0.67,X40,ATH,IT
43,INFY,0.68,-11.67,51.97,34.24,143639.0,-36499.0,276389.0,1972.00,-30.33,26.0,X-LC,10.11,3.0,-0.25,2.10,1.73,X40,NTT,IT
75,TMPV,-4.33,-21.21,69.23,33.33,177709.0,-69106.0,256694.0,600.00,-83.62,39.0,X-LC,3.60,4.0,-0.39,1.95,4.94,XY24,NTT,AUTO
34,HCLTECH,-0.71,-11.66,40.17,23.83,85853.0,-28200.0,213724.0,1908.19,-7.36,27.0,X-LC,7.43,8.0,-0.33,1.62,2.54,X40,ATH,IT

In [22]:
# top 5 for average up
df_tmp = df_portfolio_features[(df_portfolio_features['Dev%_200'] > 5)].sort_values(by = 'CurrAlloc%', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
42,INDUSINDBK,-1.89,-31.74,94.67,32.89,49896.0,-24502.0,52705.0,1800.00,-347.90,50.0,L-MC,12.16,258.0,-0.49,0.40,45.15,XR,NTT,BANKS
19,COALINDIA,1.91,6.82,10.15,17.67,16314.0,10268.0,160728.0,478.51,29.12,58.0,L-LC,11.00,185.0,0.63,1.22,27.78,XY25,ATH,MINING
27,FINCABLES,-4.90,14.00,82.38,107.91,138653.0,20665.0,168309.0,1641.55,2.49,65.0,M-SC,6.40,220.0,0.15,1.28,26.62,OX40N,ATH,CABLES
11,BANDHANBNK,-1.92,-16.18,129.57,92.42,302523.0,-45077.0,233482.0,400.00,100.43,59.0,H-SC,8.88,174.0,-0.15,1.77,28.62,XY24,NTT,BANKS
1,ABB,-2.65,6.86,36.22,45.57,101262.0,17957.0,279576.0,7934.00,-31.30,53.0,H-MC,8.86,125.0,0.18,2.12,24.15,AR,NTT,ELECTRICAL

In [23]:
# top 5 RSP
df_tmp = df_portfolio_features.sort_values(by = 'RSP', ascending=False)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
27,FINCABLES,-4.90,14.00,82.38,107.91,138653.0,20665.0,168309.0,1641.55,2.49,65.0,M-SC,6.40,220.0,0.15,1.28,26.62,OX40N,ATH,CABLES
26,EASEMYTRIP,-2.63,-57.06,239.33,45.70,181692.0,-100898.0,75917.0,26.40,-21.23,48.0,M-SC,18.05,204.0,-0.56,0.58,25.08,XY24,NTT,TRAVEL
83,WHIRLPOOL,-1.41,-27.76,151.82,81.92,125909.0,-31865.0,82933.0,2270.00,-57.64,53.0,M-SC,25.85,210.0,-0.25,0.63,16.50,XR,NTT,DURABLES
11,BANDHANBNK,-1.92,-16.18,129.57,92.42,302523.0,-45077.0,233482.0,400.00,100.43,59.0,H-SC,8.88,174.0,-0.15,1.77,28.62,XY24,NTT,BANKS
7,ATULAUTO,-4.99,-21.76,86.05,45.57,132724.0,-42891.0,154241.0,844.00,3332.43,45.0,M-SC,7.20,248.0,-0.32,1.17,16.72,XY24,NTT,AUTO

In [24]:
# Top N allocation
df_tmp = df_portfolio_features.sort_values(by = 'CurrAlloc%', ascending=False)
top_n_values = [10, 25, 50]

sum_df = pd.DataFrame({
    'Top_N': top_n_values,
    'Sum_Alloc%': [df_tmp['CurrAlloc%'].head(n).sum() for n in top_n_values]
})

sum_df

   Top_N  Sum_Alloc%
0     10       20.71
1     25       45.60
2     50       77.60

In [25]:
# market-cap-wise allocation
df_tmp = df_portfolio_features[cols]
df_tmp.groupby(df_tmp['Conviction'].str[-2:])['CurrAlloc%'].sum().sort_values(ascending=False)

Conviction
SC    44.75
MC    30.23
LC    25.01
Name: CurrAlloc%, dtype: float64

In [26]:
# criteria-wise allocation
df_portfolio_features.groupby('Criteria')['CurrAlloc%'].sum().sort_values(ascending=False)

Criteria
XY24     26.79
X40      24.13
X40N     14.48
AR        9.09
XY25      8.97
XR        8.50
OX40N     7.21
SR        0.82
Name: CurrAlloc%, dtype: float64

In [27]:
# conviction-wise allocation
df_portfolio_features.groupby('Conviction')['CurrAlloc%'].sum().sort_values(ascending=False)

Conviction
X-MC    22.82
H-SC    22.21
X-LC    21.55
X-SC    11.15
M-SC    10.70
H-MC     4.98
M-MC     2.03
L-LC     1.22
H-LC     1.21
M-LC     1.03
L-SC     0.69
L-MC     0.40
Name: CurrAlloc%, dtype: float64

In [28]:
# sector-wise stats
df_tmp = df_portfolio_features.groupby('Category')[['CurrAlloc%', 'Current', 'Current P/L', 'FTT Amt']].sum().sort_values(by=['Current', 'Current P/L'], ascending=False)
df_tmp['Current P/L%'] = round(df_tmp['Current P/L'] * 100 / df_tmp['Current'], 2)
df_tmp['FTT%'] = round(df_tmp['FTT Amt'] * 100 / df_tmp['Current'], 2)
cols = ['CurrAlloc%', 'Current P/L%', 'FTT%']
df_tmp[cols].sort_values(by=['CurrAlloc%'], ascending=False)

               CurrAlloc%  Current P/L%    FTT%
Category
FMCG                15.82        -18.53   58.62
FINANCE             12.80        -23.93   72.70
IT                  11.53        -44.16  116.40
MISC                 6.74        -46.55  106.49
ELECTRICAL           6.35        -12.21   53.15
PAINTS               5.06        -38.75   59.37
INSURANCE            4.93         -4.49   40.25
PHARMA               4.24         -5.30   38.44
AUTO                 3.78        -25.24   73.00
BANKS                3.14        -29.30  107.65
AC                   2.21         -9.98   39.81
FOOTWEAR             1.97        -69.93  138.06
TRAVEL               1.95        -74.21  161.44
DURABLES             1.87        -56.78   94.92
BREWERIES            1.74         -2.25   23.49
HEALTHCARE           1.66        -40.76   75.49
CERAMICS             1.41        -65.09  115.24
APPARELS             1.41        -28.13   66.75
REALTY               1.40        -20.14   39.88
REFINERIES           1.32        -15.92   45.25
CABLES               1.28         12.28   82.38
MINING               1.22          6.39   10.15
JEWELLERY            1.19       -104.79  175.94
CEMENT               1.15        -57.06  157.82
ENGINEERING          1.12        -64.17  139.26
CHEMICALS            1.05        -91.81  248.30
ENTERTAINMENT        0.79        -86.49  197.72
TEXTILES             0.44        -58.13  103.22
HOTELS               0.42       -107.58  180.80

In [29]:
# money to be made criteria-wise
df_portfolio_features.groupby('Criteria')['FTT Amt'].agg(['sum', 'count']).sort_values(by='sum', ascending=False)

                sum  count
Criteria
XY24      3600132.0     21
X40       1544371.0     15
AR        1373363.0     10
XR        1371149.0     12
X40N      1214152.0     10
OX40N      843866.0     10
XY25       438834.0      6
SR         310739.0      2

In [30]:
# money to be made conviction-wise
df_portfolio_features.groupby('Conviction')['FTT Amt'].agg(['sum', 'count']).sort_values(by='sum', ascending=False)

                  sum  count
Conviction
H-SC        3866319.0     24
X-MC        1511145.0     15
M-SC        1510026.0     14
X-LC        1436847.0     12
X-SC        1334059.0     10
H-MC         421827.0      3
L-SC         201162.0      2
M-LC         155691.0      1
M-MC         118800.0      2
H-LC          74520.0      1
L-MC          49896.0      1
L-LC          16314.0      1

In [31]:
# money to be made criteria and conviction-wise
df_portfolio_features.groupby(['Conviction', 'Criteria'])['FTT Amt'].agg(['sum', 'count']).sort_values(by='sum', ascending=False)

                           sum  count
Conviction Criteria
H-SC       XY24      1315402.0      6
           AR         979458.0      5
M-SC       XY24       885407.0      6
H-SC       XR         880534.0      7
X-LC       X40        740934.0      6
X-SC       XY24       647460.0      4
X-MC       X40        601977.0      7
X-SC       X40N       485139.0      4
X-MC       X40N       477023.0      4
H-SC       OX40N      380186.0      4
M-SC       OX40N      361417.0      5
H-SC       SR         310739.0      2
X-LC       XY24       303138.0      2
           X40N       251990.0      2
H-MC       XY24       232842.0      1
X-MC       XY25       216262.0      2
           XY24       215883.0      2
X-SC       X40        201460.0      2
H-MC       AR         188985.0      2
M-SC       XR         186129.0      2
M-LC       XR         155691.0      1
X-LC       XY25       140785.0      2
L-SC       OX40N      102263.0      1
           XR          98899.0      1
M-SC       AR          77073.0      1
H-LC       AR          74520.0      1
M-MC       XY25        65473.0      1
           AR          53327.0      1
L-MC       XR          49896.0      1
L-LC       XY25        16314.0      1

In [32]:
# notebook execution time

end_time = time.time()
execution_time = round(end_time - start_time, 0)
print(f"Notebook execution time: {execution_time} seconds")

Notebook execution time: 29.0 seconds