<a href="https://colab.research.google.com/github/ankit-rathi/Quantvesting_v2/blob/main/myStocks_Portfolio_Analysis.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
'''
!pip install pandas==2.2.2 -qq
!pip install pyxirr -qq
!pip install ta -qq
!pip install yfinance==0.2.59 -qq
'''

'\n!pip install pandas==2.2.2 -qq\n!pip install pyxirr -qq\n!pip install ta -qq\n!pip install yfinance==0.2.59 -qq\n'

In [2]:
# import libraries

import numpy as np
import pandas as pd
import datetime
import warnings
warnings.filterwarnings('ignore')
import yfinance as yfin
import ta
import matplotlib.pyplot as plt
import requests

In [3]:
# notebook start time
import time
import datetime
import pytz

start_time = time.time()

# function to print date timestamp
def print_date_time():
  tz_NY = pytz.timezone('Asia/Kolkata')
  datetime_NY = datetime.datetime.now(tz_NY)
  print("Run date time (IST):", datetime_NY.strftime("%Y-%m-%d %H:%M:%S"))

In [4]:
# function to get booked and reserved amount
def get_amt():
  # fetch the JSON data from the URL
  url = "https://raw.githubusercontent.com/ankit-rathi/Tradevesting_v1/main/data/myPortfolioAmts.json"
  response = requests.get(url)
  pf_amts = response.json()  # parse the JSON data

  # extract values from the JSON
  py_booked_amt_dm = pf_amts["py_booked_amt_dm"]
  py_booked_amt_sv = pf_amts["py_booked_amt_sv"]
  cy_booked_amt_dm = pf_amts["cy_booked_amt_dm"]
  cy_booked_amt_sv = pf_amts["cy_booked_amt_sv"]
  reserve_amt_dm = pf_amts["reserve_amt_dm"]
  reserve_amt_sv = pf_amts["reserve_amt_sv"]

  # perform calculations
  py_booked_amt = py_booked_amt_dm + py_booked_amt_sv
  cy_booked_amt = cy_booked_amt_dm + cy_booked_amt_sv
  reserve_amt = reserve_amt_dm + reserve_amt_sv
  total_booked_amt = py_booked_amt + cy_booked_amt

  return total_booked_amt, reserve_amt, cy_booked_amt, py_booked_amt

gen_output = 0

In [5]:
# function to format the amount
def format_amt(number):
    abs_number = abs(number)

    if abs_number >= 1_00_00_000:  # Crores
        formatted_amt = f"{number / 1_00_00_000:.2f} C"
    elif abs_number >= 1_00_000:  # Lakhs
        formatted_amt = f"{number / 1_00_000:.2f} L"
    elif abs_number >= 1_000:  # Thousands
        formatted_amt = f"{number / 1_000:.2f} K"
    else:
        formatted_amt = f"{number:.2f}"

    return formatted_amt

# function to set start and end date
def get_start_end_date():
  start_date = (datetime.date.today() + datetime.timedelta(days=-365)).strftime('%Y-%m-%d')
  end_date = (datetime.date.today() + datetime.timedelta(days=1)).strftime('%Y-%m-%d')
  return start_date, end_date

# function to fetch my portfolio csv
def get_mypfs_df():
  mypfs_df = pd.read_csv('https://raw.githubusercontent.com/ankit-rathi/Tradevesting_v1/main/data/myPortfolioStocks.csv')
  return mypfs_df

# function to fetch my prospects csv
def get_mypps_df():
  mypps_df = pd.read_csv('https://raw.githubusercontent.com/ankit-rathi/Tradevesting_v1/main/data/myProspectsScrips.csv')
  return mypps_df

# function to fetch screener data
def get_myscreen_df():
  myscreen_df = pd.read_csv('https://raw.githubusercontent.com/ankit-rathi/Tradevesting_v1/main/data/myScreenerDB.csv')
  return myscreen_df

# function to fetch momentum data
def get_myinvmt_df():
  myinvmt_df = pd.read_csv('https://raw.githubusercontent.com/ankit-rathi/Tradevesting_v1/main/data/myInvestments.csv')
  return myinvmt_df

# function to get the stock ids
def get_stock_ids(df_pf):
  stock_n100 = df_pf['Symbol'].unique()

  exclude = ['CADILAHC','MMTC', 'MASFIN']

  stock_ids = df_pf[~df_pf['Symbol'].isin(exclude) ]['Symbol'].unique()

  #mypf = mypf[mypf.Forecast.notnull()]
  #stock_ids = mypf['Symbol'].unique()

  #stock_ids.sort()
  return stock_ids

# get features from screener data
def get_screener_features():
  myscreen_df = get_myscreen_df()
  cols = ['Symbol', 'EPS', 'MedPE', 'ROCE%', 'ROE%', 'CapType']
  return myscreen_df[cols]

# get relative strength
def get_relative_strength(stock_list):

    # Dictionary to store stock tickers and their corresponding percentage price change
    stock_changes = {}

    # Loop through each stock and fetch its price data
    for stock in stock_list:
        try:
            # Download the stock data for the given date range
            stock_data = yfin.Ticker(stock + '.NS').history(period='1mo', interval='1d')[map(str.title, ['open', 'close', 'low', 'high', 'volume'])]

            # Calculate the percentage change for the stock
            if len(stock_data) > 0:
                start_price = stock_data['Close'].iloc[0]
                end_price = stock_data['Close'].iloc[-1]
                percent_change = round(((end_price - start_price) / start_price) * 100, 2)
                stock_changes[stock] = percent_change
            else:
                stock_changes[stock] = np.nan  # If no data is available, set to NaN

        except Exception as e:
            print(f"Error fetching data for {stock}: {e}")
            stock_changes[stock] = np.nan

    # Create a DataFrame with stock tickers and their percentage changes
    df = pd.DataFrame(list(stock_changes.items()), columns=['Symbol', 'Percent_Change'])

    # Drop any stocks with missing data (NaN values)
    df = df.dropna()

    # Calculate the percentile rank based on percentage change
    df['RSP'] = round(df['Percent_Change'].rank(pct=True) * 100, 2)
    cols = ['Symbol', 'RSP']
    df = df[cols]
    # Sort by percentile rank (optional)
    df = df.sort_values(by='RSP', ascending=False).reset_index(drop=True)

    return df

In [6]:
# function to get stock technicals
def stock_prec_dev(stock_symbol):
    #stock_symbol = 'ULTRACEMCO.NS'
    short_window = 20
    mid_window = 50
    long_window = 200
    moving_avg = 'SMA'

    start = datetime.datetime(*map(int, start_date.split('-')))
    end = datetime.datetime(*map(int, end_date.split('-')))

    stock_df = yfin.Ticker(stock_symbol + '.NS').history(period='max', interval='1d')[map(str.title, ['open', 'close', 'low', 'high', 'volume'])]

    stock_df['Max'] = round(max(stock_df['Close']),2)
    stock_df = stock_df[(stock_df.index <= end_date) & (stock_df.index >= start_date)]
    stock_df['200_SMA'] = round(stock_df['Close'].rolling(window = 200, min_periods = 1).mean(),0)
    stock_df['Dev%_200'] = round((stock_df['Close'] - stock_df['200_SMA'])*100/stock_df['200_SMA'],2)
    stock_df.dropna(axis = 0, inplace = True) # remove any null rows

    stock_df['20_SMA'] = stock_df['Close'].rolling(window=20).mean()
    stock_df['50_SMA'] = stock_df['Close'].rolling(window=50).mean()
    stock_df['Symbol'] = stock_symbol

    stock_df['Close'] = round(stock_df['Close'],2)
    stock_df['Min'] = round(min(stock_df['Close']),2)
    stock_df['RSI_14'] = ta.momentum.RSIIndicator(close=stock_df['Close'], window=14).rsi()
    stock_df['RSI_14'] = round(stock_df['RSI_14'],0)
    stock_df['Prev_Close'] = stock_df['Close'].shift(1)
    stock_df.drop(['Open', 'Low', 'High', 'Volume'], axis=1, inplace=True)
    stock_df = stock_df.tail(1)

    max_SMA = max(stock_df['20_SMA'].item(), stock_df['50_SMA'].item(), stock_df['200_SMA'].item())
    min_SMA = min(stock_df['20_SMA'].item(), stock_df['50_SMA'].item(), stock_df['200_SMA'].item())
    ABS_Spread = max_SMA - min_SMA
    stock_df['Spread%'] = round((ABS_Spread / stock_df['200_SMA'].item()) * 100,2)

    return stock_df

# function to compute stock attributes
def get_common_features(stock_ids, df_mypf):

  df_prec_dev = pd.DataFrame()
  df_tmp = get_screener_features()
  df_rs = get_relative_strength(stock_ids)

  for stock_id in stock_ids:
      tmp = stock_prec_dev(stock_id)
      tmp = tmp.reset_index()
      df_prec_dev = pd.concat([df_prec_dev, tmp], ignore_index = True)
  df_prec_dev = pd.merge(df_prec_dev, df_mypf, on= 'Symbol')
  df_prec_dev = pd.merge(df_prec_dev, df_tmp, on= 'Symbol', how='left')
  df_prec_dev = pd.merge(df_prec_dev, df_rs, on= 'Symbol', how='left')
  #print(df_prec_dev.columns)
  df_prec_dev['Curr_PE'] = round(df_prec_dev['Close']/df_prec_dev['EPS'],1)
  df_prec_dev['Dev%_PE'] = round((df_prec_dev['Curr_PE'] - df_prec_dev['MedPE'])*100/df_prec_dev['MedPE'],2)
  df_prec_dev['Conviction'] = df_prec_dev['Conviction'] + '-' + df_prec_dev['CapType']
  return df_prec_dev

# function to arrange stock features
def arrange_features(df_stocks, common_cols, diff_cols):
  df_stocks_common = df_stocks[common_cols].drop_duplicates()
  df_stocks_diff = df_stocks[diff_cols]
  df_stocks_diff['Investment'] = df_stocks_diff['AvgCost'] * df_stocks_diff['Shares']
  df_stocks_diff = df_stocks_diff.groupby(['Symbol'])[['Shares', 'Investment']].aggregate(['sum']).reset_index()
  df_stocks_diff.columns = ['Symbol', 'Shares', 'Investment']
  df_stocks_diff['AvgCost'] = round(df_stocks_diff['Investment']/df_stocks_diff['Shares'],2)
  df_stocks = pd.merge(df_stocks_diff, df_stocks_common, on='Symbol')
  return df_stocks

# plot fact distribution across dimension
def plot_pie_chart(df, dimension, fact):
  # grouping the data by category and calculating the sum of fact for each type
  grouped_data = df.groupby(dimension)[fact].sum()

  # sorting the grouped data in descending order
  grouped_data = grouped_data.sort_values(ascending=False)

  # creating a pie chart
  grouped_data.plot.pie(autopct='%1.1f%%', startangle=90, figsize=(6, 6))

  # adding a title and displaying the plot
  plt.title(f'{dimension} {fact} Distribution')
  plt.ylabel('')  # To hide the y-label
  plt.show()

In [7]:
# function to get portfolio features

def get_portfolio_features(df_common_features):

  print_date_time()
  print('-------------------')

  #df_common_features["Target"] = df_common_features["Target"].fillna(df_common_features["Max"])
  df_common_features['NTT'] = np.where(df_common_features['Strategy']== 'NTT', df_common_features["Target"], df_common_features['Max'])
  df_common_features['LTT'] = np.where(df_common_features['Strategy']== 'BTT', df_common_features["Target"], df_common_features['Max'])
  df_common_features['BOL'] = df_common_features['Min']

  tmp_df = df_common_features[df_common_features['Symbol'].isin(mypf_df[mypf_df['InPortfolio'] != 'NA'].Symbol.values)]
  print('qualified stocks: '+str(len(tmp_df['Symbol'].unique())))
  tmp_df1 = tmp_df[tmp_df['LatestQtr'] == 1]
  print('with latest results: '+str(len(tmp_df1['Symbol'].unique())))
  tmp_df1 = tmp_df1[tmp_df1['StarStock'] == 1]
  print('still star stocks: '+str(len(tmp_df1['Symbol'].unique())))
  tmp_df['Investment'] = tmp_df['AvgCost'] * tmp_df['Shares']
  tmp_df['Current'] = round(tmp_df['Close'] * tmp_df['Shares'],0)
  tmp_df['Previous'] = tmp_df['Prev_Close'] * tmp_df['Shares']
  tmp_df['EstimatedST'] = tmp_df['NTT'] * tmp_df['Shares']
  tmp_df['EstimatedLT'] = tmp_df['LTT'] * tmp_df['Shares']
  tmp_df['Current P/L'] = round((tmp_df['Current'] - tmp_df['Investment']),0)
  tmp_df['Today P/L%'] = round((tmp_df['Current'] - tmp_df['Previous'])*100/tmp_df['Previous'],2)
  tmp_df['Current P/L%'] = round((tmp_df['Current'] - tmp_df['Investment'])*100/tmp_df['Investment'],2)
  tmp_df['EstimatedST P/L%'] = round((tmp_df['EstimatedST'] - tmp_df['Investment'])*100/tmp_df['Investment'],2)
  tmp_df['EstimatedLT P/L%'] = round((tmp_df['EstimatedLT'] - tmp_df['Investment'])*100/tmp_df['Investment'],2)
  tmp_df['NTT%'] = round((tmp_df['NTT'] - tmp_df['Close'])*100/tmp_df['Close'],2)
  tmp_df['LTT%'] = round((tmp_df['LTT'] - tmp_df['Close'])*100/tmp_df['Close'],2)
  tmp_df['Gained%'] = round((tmp_df['Close'] - tmp_df['BOL'])*100/tmp_df['BOL'],2)
  investment = round(sum(tmp_df['AvgCost']*tmp_df['Shares']),0)
  current = round(sum(tmp_df['Close']*tmp_df['Shares']),0)
  tmp_df['InitAlloc%'] = round(tmp_df['Investment']*100/investment,2)
  tmp_df['CurrAlloc%'] = round(tmp_df['Current']*100/current,2)
  tmp_df['FTT'] = tmp_df['LTT']
  tmp_df.loc[tmp_df['Strategy'] == 'NTT', 'FTT'] = tmp_df['NTT']
  tmp_df['FTT%'] = tmp_df['LTT%']
  tmp_df.loc[tmp_df['Strategy'] == 'NTT', 'FTT%'] = tmp_df['NTT%']
  tmp_df['FTT Amt'] = round(tmp_df['FTT%'] * tmp_df['Current']/100,0)
  tmp_df['OTT%'] = round((tmp_df['FTT'] - tmp_df['AvgCost'])*100/tmp_df['AvgCost'],2)
  tmp_df['RRR Ind'] = round(tmp_df['Current P/L']/tmp_df['FTT Amt'],2)
  tmp_df['Risk Ind'] = round(tmp_df['Current P/L%']*tmp_df['CurrAlloc%'],0)

  return tmp_df

# function to print portfolio features
def print_portfolio_stats(df_portfolio_features, myinvmt_df):
  from pyxirr import xirr

  total_booked_amt, reserve_amt, cy_booked_amt, py_booked_amt = get_amt()

  dates = myinvmt_df['Date'].values
  dates = np.append(dates, datetime.date.today().strftime('%d-%b-%y'))
  investment = myinvmt_df['Investment'].values
  dates= pd.to_datetime(dates)

  current = round(sum(df_portfolio_features['Close']*df_portfolio_features['Shares']),0) + reserve_amt
  investment_xirr = np.append(investment, current)
  cagr = round(xirr(pd.DataFrame({"dates": dates, "amounts": investment_xirr}))*100,2)

  investment = -sum(investment)
  invested = round(sum(df_portfolio_features['AvgCost']*df_portfolio_features['Shares']),0) + reserve_amt
  previous = round(sum(df_portfolio_features['Prev_Close']*df_portfolio_features['Shares']),0) + reserve_amt
  cy_invested = investment + py_booked_amt

  today_pnl_amount = current-previous
  today_pnl_percentage = round((current-previous)*100/previous,2)

  curr_pnl_amount = current-invested
  curr_pnl_percentage = round((curr_pnl_amount)*100/(cy_invested),2)

  cy_pnl_amount = cy_booked_amt + curr_pnl_amount
  cy_pnl_percentage = round((cy_pnl_amount)*100/cy_invested,2)

  overall_pnl_amount = total_booked_amt + curr_pnl_amount
  overall_pnl_percentage = round((overall_pnl_amount)*100/investment,2)

  estimate_st = round(sum(df_portfolio_features['FTT']*df_portfolio_features['Shares']),0)  + reserve_amt
  est_st_pnl_amount = estimate_st-current
  est_st_pnl_percentage = round((est_st_pnl_amount)*100/current,2)

  estimate_lt = round(sum(df_portfolio_features['LTT']*df_portfolio_features['Shares']),0)  + reserve_amt
  est_lt_pnl_amount = estimate_lt-current
  est_lt_pnl_percentage = round((est_lt_pnl_amount)*100/current,2)

  total_profit = round(sum(df_portfolio_features[df_portfolio_features['Current P/L%'] > 0]['Current']) - sum(df_portfolio_features[df_portfolio_features['Current P/L%'] > 0]['Investment']),0)
  total_loss = round(sum(df_portfolio_features[df_portfolio_features['Current P/L%'] < 0]['Current']) - sum(df_portfolio_features[df_portfolio_features['Current P/L%'] < 0]['Investment']),0)

  cy_booked_percentage = round((cy_booked_amt)*100/current,2)
  py_booked_percentage = round((py_booked_amt)*100/investment,2)
  total_booked_percentage = round((total_booked_amt)*100/investment,2)

  print('-------------------')
  print('Initial Investment: ', format_amt(investment))
  print('CY Investment: ', format_amt(cy_invested))
  print('Reserve: ', format_amt(reserve_amt))
  print('Current: ',  format_amt(current))
  print('-------------------')
  print('Today PnL: '+ '{} ({}%)'.format(format_amt(today_pnl_amount), today_pnl_percentage))
  print('Current PnL: '+ '{} ({}%)'.format(format_amt(curr_pnl_amount), curr_pnl_percentage))
  print('CY Booked + Current PnL: '+ '{} ({}%)'.format(format_amt(cy_pnl_amount), cy_pnl_percentage))
  print('-------------------')
  print('Total profit: ', format_amt(total_profit))
  print('Total loss: ', format_amt(total_loss))
  print('-------------------')
  print('Total Booked + Current PnL: '+ '{} ({}%)'.format(format_amt(overall_pnl_amount), overall_pnl_percentage))
  print('Total Booked PnL: '+ '{} ({}%)'.format(format_amt(total_booked_amt), total_booked_percentage))
  print('Curr Year Booked PnL: '+ '{} ({}%)'.format(format_amt(cy_booked_amt), cy_booked_percentage))
  print('Prev Year Booked PnL: '+ '{} ({}%)'.format(format_amt(py_booked_amt), py_booked_percentage))
  print('===================')
  print('Est FTT: ',  format_amt(estimate_st))
  print('Est FTT PnL: '+ '{} ({}%)'.format(format_amt(est_st_pnl_amount), est_st_pnl_percentage))

  print('===================')
  print('Deployed: ', format_amt(investment))

  print('Current: ', format_amt(current))

  print('CAGR/XIRR %: '+'{}%'.format(cagr))

In [8]:
# get start and end date
start_date, end_date = get_start_end_date()

# get portfolio and prospects data
mypfs_df = get_mypfs_df()
mypps_df = get_mypps_df()
myinvmt_df = get_myinvmt_df()

# merge above datasets
mypf_df = pd.merge(mypfs_df, mypps_df, on="Symbol")

# seggregate dm and sv portfolio
dm_pf = mypf_df[mypf_df['InPortfolio'] == 'DM']
sv_pf = mypf_df[mypf_df['InPortfolio'] == 'SV']

# build portfolio stock dataframe
dm_stocks = get_stock_ids(dm_pf)
sv_stocks = get_stock_ids(sv_pf)
df_stocks = pd.concat([dm_pf,sv_pf], ignore_index = True)

# arrange common and diff stock features
common_cols = ['Symbol', 'Target', 'Criteria', 'Strategy', 'CumlRnk', 'LatestQtr', 'StarStock', 'Conviction', 'Category', 'InFolio', 'XIRR', 'MBQ']
diff_cols = ['Symbol', 'AvgCost', 'Shares']
df_stocks = arrange_features(df_stocks, common_cols, diff_cols)

# get common features
stock_ids = df_stocks['Symbol'].values
df_common_features = get_common_features(stock_ids, df_stocks)

df_common_features.reset_index(drop=True, inplace=True)
df_common_features.drop(['Date'], axis=1, inplace=True)
# get and print portfolio features
df_portfolio_features = get_portfolio_features(df_common_features)

print_portfolio_stats(df_portfolio_features, myinvmt_df)

df = df_portfolio_features
#plot_pie_chart(df, 'CapType', 'Current')
list_ox40n = list(df[df['MBQ'].str.contains('OX40N', na=False)]['Symbol'].values)

Run date time (IST): 2026-08-18 10:33:02
-------------------
qualified stocks: 87
with latest results: 30
still star stocks: 19

-------------------
Initial Investment:  1.46 C
CY Investment:  1.89 C
Reserve:  3.69 L
Current:  1.58 C
-------------------
Today PnL: -82.82 K (-0.52%)
Current PnL: -34.55 L (-18.29%)
CY Booked + Current PnL: -29.49 L (-15.61%)
-------------------
Total profit:  3.32 L
Total loss:  -37.86 L
-------------------
Total Booked + Current PnL: 13.38 L (9.16%)
Total Booked PnL: 47.93 L (32.82%)
Curr Year Booked PnL: 5.06 L (3.19%)
Prev Year Booked PnL: 42.87 L (29.35%)
===================
Est FTT:  2.67 C
Est FTT PnL: 1.09 C (68.64%)
===================
Deployed:  1.46 C
Current:  1.58 C
CAGR/XIRR %: 3.68%

In [9]:
# top 5 near their targets
cols = ['Symbol', 'Today P/L%', 'Current P/L%', 'FTT%', 'OTT%', 'FTT Amt', 'Current P/L', 'Current', 'FTT', 'Dev%_PE', 'RSI_14','Conviction', 'Spread%',  'CumlRnk', 'RRR Ind', 'CurrAlloc%', 'Gained%', 'Criteria', 'Strategy', 'Category']
df_tmp = df_portfolio_features[~df_portfolio_features['Symbol'].isin(['ENRIN','BLUSPRING','DIGITIDE'])]
df_tmp = df_tmp.sort_values(by = 'FTT Amt', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
66,SIEMENS,0.28,6.24,4.32,10.83,8541.0,11610.0,197705.0,4125.00,-13.90,63.0,H-LC,13.59,51.0,1.36,1.28,39.49,AR,NTT,ELECTRICAL
78,UNITDSPR,-0.71,12.69,7.16,20.77,18893.0,29721.0,263865.0,1644.00,-3.97,64.0,X-MC,10.50,64.0,1.57,1.71,26.84,X40N,NTT,BREWERIES
77,TTKPRESTIG,0.03,-23.01,30.01,0.09,23283.0,-23192.0,77585.0,770.00,-6.23,41.0,M-SC,10.20,250.0,-1.00,0.50,39.64,OX40N,NTT,DURABLES
52,M&M,0.70,7.80,10.22,18.82,26517.0,18783.0,259464.0,3762.88,-6.96,58.0,X-LC,4.79,25.0,0.71,1.68,17.70,X40N,ATH,AUTO
54,MASFIN,0.63,-7.10,30.86,21.57,28089.0,-6960.0,91020.0,397.04,-28.13,43.0,H-SC,0.94,167.0,-0.25,0.59,8.49,XR,ATH,FINANCE

In [10]:
# top 5 today
df_tmp = df_portfolio_features.sort_values(by = 'Today P/L%', ascending=False)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
12,BOSCH-HCIL,3.74,-24.81,32.98,-0.01,31692.0,-31709.0,96096.0,2282.00,750.26,76.0,M-SC,5.88,231.0,-1.00,0.62,63.57,OX40N,BTT,AC
18,COFFEEDAY,3.54,-49.54,168.10,35.27,96310.0,-56256.0,57293.0,80.00,NaN,42.0,NaN,3.94,266.0,-0.58,0.37,41.29,XR,NTT,HOTELS
0,5PAISA,2.38,-25.19,50.91,12.90,83221.0,-55029.0,163467.0,593.00,4.96,62.0,H-SC,11.53,170.0,-0.66,1.06,57.75,OX40N,NTT,FINANCE
76,TRIDENT,1.51,-33.23,92.46,28.51,56957.0,-30652.0,61602.0,48.00,-11.89,50.0,M-SC,1.63,223.0,-0.54,0.40,15.41,XR,NTT,TEXTILES
22,DIXON,1.37,3.58,33.16,37.92,89573.0,9325.0,270123.0,18931.72,-60.63,58.0,X-MC,15.10,54.0,0.10,1.75,46.98,X40N,ATH,IT

In [11]:
# bottom 5 today
df_tmp = df_portfolio_features.sort_values(by = 'Today P/L%', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
81,VALIANTORG,-8.72,-38.44,182.92,74.15,184215.0,-62897.0,100708.0,838.00,NaN,52.0,NaN,6.06,145.0,-0.34,0.65,49.87,XR,NTT,CHEMICALS
29,GREENPANEL,-4.30,-55.47,221.48,43.14,180542.0,-101562.0,81516.0,537.00,NaN,29.0,NaN,10.98,225.0,-0.56,0.53,0.00,XY24,NTT,MISC
33,HCLTECH,-3.55,-12.27,41.30,23.97,112139.0,-37964.0,271522.0,1853.42,-14.68,53.0,X-LC,11.76,8.0,-0.34,1.76,28.13,X40,ATH,IT
60,RELAXO,-3.51,-50.48,207.57,52.31,149205.0,-73278.0,71882.0,1176.00,NaN,41.0,NaN,12.96,92.0,-0.49,0.46,60.72,X40N,NTT,FOOTWEAR
19,COLPAL,-3.35,-27.30,92.39,39.86,176890.0,-71905.0,191460.0,3683.41,-12.03,31.0,X-MC,1.50,62.0,-0.41,1.24,8.30,XY25,ATH,FMCG

In [12]:
# top 5 to exit based on CumlRnk
df_tmp = df_portfolio_features[~df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])]
df_tmp = df_tmp[(df_tmp['Current P/L%'] > -1) & (df_tmp['Current P/L%'] < 1)].sort_values(by = 'CumlRnk', ascending=False)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
79,UTIAMC,-0.94,-0.88,52.49,51.15,115676.0,-1952.0,220378.0,1371.68,25.5,44.0,M-SC,7.72,229.0,-0.02,1.42,3.23,XY24,ATH,FINANCE

In [13]:
# OX40N stocks to exit
df_tmp = df_portfolio_features[(df_portfolio_features['Symbol'].isin(list_ox40n))].sort_values(by = 'Current P/L%', ascending=False)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
25,FINCABLES,-0.59,66.30,25.02,107.91,61432.0,97887.0,245531.0,1641.55,21.20,75.0,M-SC,18.84,220.0,1.59,1.59,84.72,OX40N,ATH,CABLES
67,SIS,0.31,-4.06,26.39,21.26,28112.0,-4506.0,106526.0,528.00,104.78,40.0,H-SC,21.27,168.0,-0.16,0.69,58.39,OX40N,NTT,MISC
43,INDIGOPNTS,-0.49,-18.80,23.17,0.02,32842.0,-32815.0,141744.0,1408.00,-22.52,64.0,M-SC,6.64,222.0,-1.00,0.92,60.82,OX40N,NTT,PAINTS
77,TTKPRESTIG,0.03,-23.01,30.01,0.09,23283.0,-23192.0,77585.0,770.00,-6.23,41.0,M-SC,10.20,250.0,-1.00,0.50,39.64,OX40N,NTT,DURABLES
12,BOSCH-HCIL,3.74,-24.81,32.98,-0.01,31692.0,-31709.0,96096.0,2282.00,750.26,76.0,M-SC,5.88,231.0,-1.00,0.62,63.57,OX40N,BTT,AC

In [14]:
# top 5 to book for rotation
df_tmp = df_portfolio_features[(df_portfolio_features['Current P/L%'] > 20) ].sort_values(by = 'CumlRnk', ascending=False)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
25,FINCABLES,-0.59,66.30,25.02,107.91,61432.0,97887.0,245531.0,1641.55,21.20,75.0,M-SC,18.84,220.0,1.59,1.59,84.72,OX40N,ATH,CABLES
86,ZYDUSLIFE,0.42,20.22,12.72,35.51,32047.0,42366.0,251940.0,1285.01,19.19,52.0,H-LC,15.71,120.0,1.32,1.63,32.58,AR,ATH,PHARMA

In [15]:
# top 5 to monitor for exit
df_tmp = df_portfolio_features[~df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])]
df_tmp = df_tmp[(df_tmp['Current P/L%'] > 0) ].sort_values(by = 'Dev%_PE', ascending=False)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
25,FINCABLES,-0.59,66.30,25.02,107.91,61432.0,97887.0,245531.0,1641.55,21.20,75.0,M-SC,18.84,220.0,1.59,1.59,84.72,OX40N,ATH,CABLES
68,STARHEALTH,-0.40,12.78,30.58,47.26,96952.0,35920.0,317043.0,761.00,-0.61,50.0,H-SC,16.27,173.0,0.37,2.05,37.08,XY24,NTT,INSURANCE

In [16]:
# top 5 to book for rotation from weak conviction
df_tmp = df_portfolio_features[~df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])]
df_tmp = df_tmp[~df_tmp['Criteria'].isin(['XY25','XY24','X40', 'X40N'])].sort_values(by = 'RRR Ind', ascending=False)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
25,FINCABLES,-0.59,66.30,25.02,107.91,61432.0,97887.0,245531.0,1641.55,21.20,75.0,M-SC,18.84,220.0,1.59,1.59,84.72,OX40N,ATH,CABLES
67,SIS,0.31,-4.06,26.39,21.26,28112.0,-4506.0,106526.0,528.00,104.78,40.0,H-SC,21.27,168.0,-0.16,0.69,58.39,OX40N,NTT,MISC
3,ALKYLAMINE,-0.41,-18.69,136.81,92.54,112309.0,-18872.0,82091.0,4520.85,NaN,55.0,NaN,14.10,142.0,-0.17,0.53,55.88,SR,ATH,CHEMICALS
42,INDIAMART,-1.58,-24.30,165.42,100.92,154444.0,-29971.0,93365.0,4675.60,NaN,39.0,NaN,13.41,140.0,-0.19,0.60,1.07,AR,ATH,MISC
71,TANLA,-2.50,-35.86,238.73,117.25,414567.0,-97106.0,173655.0,1922.32,NaN,44.0,NaN,15.31,147.0,-0.23,1.12,52.04,AR,ATH,IT

In [17]:
# top 5 to accumulate based on lowest RSI_14
df_tmp = df_portfolio_features[df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])].sort_values(by = 'RSI_14', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
28,GODREJCP,-0.46,-15.40,57.09,32.90,120523.0,-38427.0,211110.0,1460.97,-17.06,31.0,X-MC,5.71,32.0,-0.32,1.36,2.76,X40N,ATH,FMCG
19,COLPAL,-3.35,-27.30,92.39,39.86,176890.0,-71905.0,191460.0,3683.41,-12.03,31.0,X-MC,1.50,62.0,-0.41,1.24,8.30,XY25,ATH,FMCG
56,PGHH,-0.91,-37.43,110.98,32.01,148269.0,-79920.0,133600.0,17616.87,-53.98,31.0,X-SC,19.19,57.0,-0.54,0.86,0.00,X40,ATH,FMCG
55,PAGEIND,0.41,-3.76,38.80,33.59,100220.0,-10079.0,258300.0,51217.29,-28.42,32.0,X-MC,8.76,55.0,-0.10,1.67,22.67,X40,ATH,APPARELS
47,ITC,-0.24,-24.85,65.93,24.70,196834.0,-98728.0,298550.0,452.00,-29.94,34.0,X-LC,10.42,1.0,-0.50,1.93,0.00,X40,NTT,FMCG

In [18]:
# top 5 to accumulate based on Spread and CumlRnk
df_tmp = df_portfolio_features[df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])]
df_tmp = df_tmp[(df_tmp['CumlRnk'] < 100)].sort_values(by = 'Spread%', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
19,COLPAL,-3.35,-27.30,92.39,39.86,176890.0,-71905.0,191460.0,3683.41,-12.03,31.0,X-MC,1.50,62.0,-0.41,1.24,8.30,XY25,ATH,FMCG
23,DMART,-0.21,-2.83,35.24,31.42,106768.0,-8816.0,302974.0,5391.45,-18.52,47.0,X-LC,2.33,14.0,-0.08,1.96,9.33,X40N,ATH,FMCG
50,KOTAKBANK,-0.56,2.63,15.87,18.92,39043.0,6313.0,246015.0,452.46,-13.30,50.0,X-LC,2.39,12.0,0.16,1.59,10.69,X40,ATH,BANKS
26,GILLETTE,-0.41,-10.93,45.64,29.72,103217.0,-27741.0,226155.0,10978.86,-35.66,38.0,X-SC,3.47,83.0,-0.27,1.46,3.93,X40,ATH,FMCG
8,BAJAJHLDNG,-2.20,0.83,27.19,28.24,70185.0,2124.0,258129.0,14274.15,-8.74,54.0,X-LC,4.17,28.0,0.03,1.67,29.92,X40,ATH,FINANCE

In [19]:
# top 5 to accumulate based on lowest Gained%
df_tmp = df_portfolio_features[df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])].sort_values(by = 'Gained%', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
20,DABUR,-0.69,-21.01,81.93,43.70,160534.0,-52128.0,195940.0,735.00,-31.92,35.0,X-MC,9.87,70.0,-0.32,1.27,0.00,XY24,BTT,FMCG
47,ITC,-0.24,-24.85,65.93,24.70,196834.0,-98728.0,298550.0,452.00,-29.94,34.0,X-LC,10.42,1.0,-0.50,1.93,0.00,X40,NTT,FMCG
56,PGHH,-0.91,-37.43,110.98,32.01,148269.0,-79920.0,133600.0,17616.87,-53.98,31.0,X-SC,19.19,57.0,-0.54,0.86,0.00,X40,ATH,FMCG
34,HDFCBANK,-0.49,-11.40,47.92,31.05,124445.0,-33427.0,259693.0,1073.00,-28.50,34.0,X-LC,12.67,26.0,-0.27,1.68,0.80,X40,BTT,BANKS
36,HINDUNILVR,-0.74,-15.14,43.26,21.56,123532.0,-50959.0,285558.0,2922.00,-41.62,40.0,X-LC,6.17,9.0,-0.41,1.85,0.84,XY25,NTT,FMCG

In [20]:
# top 5 to accumulate based on lowest CurrAlloc%
df_tmp = df_portfolio_features[df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])].sort_values(by = 'CurrAlloc%', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
56,PGHH,-0.91,-37.43,110.98,32.01,148269.0,-79920.0,133600.0,17616.87,-53.98,31.0,X-SC,19.19,57.0,-0.54,0.86,0.00,X40,ATH,FMCG
2,ACC,-0.11,-41.14,196.99,74.81,310897.0,-110304.0,157824.0,3906.00,-41.79,39.0,X-SC,11.40,85.0,-0.35,1.02,5.44,XY24,BTT,CEMENT
1,ABBOTINDIA,-1.61,-10.68,29.17,15.37,46599.0,-19105.0,159750.0,34390.26,-27.37,40.0,X-MC,4.56,58.0,-0.41,1.03,8.21,X40,ATH,PHARMA
40,ICICIPRULI,-0.04,-15.78,54.69,30.28,90741.0,-31087.0,165918.0,787.27,-45.99,53.0,X-MC,12.70,78.0,-0.34,1.07,10.55,X40,ATH,INSURANCE
39,ICICIGI,-0.56,-14.34,38.78,18.89,66478.0,-28686.0,171423.0,2244.41,-14.59,40.0,X-MC,10.44,66.0,-0.43,1.11,2.13,X40,ATH,INSURANCE

In [21]:
# top 5 to accumulate based on CumlRnk
df_tmp = df_portfolio_features.sort_values(by = 'CumlRnk', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
47,ITC,-0.24,-24.85,65.93,24.70,196834.0,-98728.0,298550.0,452.00,-29.94,34.0,X-LC,10.42,1.0,-0.50,1.93,0.00,X40,NTT,FMCG
73,TCS,-0.83,-32.66,84.43,24.20,263396.0,-151303.0,311970.0,4230.71,-43.98,47.0,X-LC,14.31,2.0,-0.57,2.02,16.34,X40,ATH,IT
45,INFY,-1.67,-20.21,75.93,40.38,228094.0,-76069.0,300401.0,1972.00,-41.25,47.0,X-LC,15.92,3.0,-0.33,1.94,13.76,X40,NTT,IT
75,TMPV,-1.00,-22.22,83.54,42.75,270361.0,-92476.0,323631.0,600.00,-83.84,38.0,X-LC,4.38,4.0,-0.34,2.09,11.28,XY24,NTT,AUTO
33,HCLTECH,-3.55,-12.27,41.30,23.97,112139.0,-37964.0,271522.0,1853.42,-14.68,53.0,X-LC,11.76,8.0,-0.34,1.76,28.13,X40,ATH,IT

In [22]:
# top 5 for average up
df_tmp = df_portfolio_features[(df_portfolio_features['Dev%_200'] > 5)].sort_values(by = 'CurrAlloc%', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
44,INDUSINDBK,-0.63,-25.11,77.44,32.89,44777.0,-19386.0,57821.0,1800.00,325.93,52.0,L-MC,13.42,258.0,-0.43,0.37,42.55,XR,NTT,BANKS
60,RELAXO,-3.51,-50.48,207.57,52.31,149205.0,-73278.0,71882.0,1176.00,NaN,41.0,NaN,12.96,92.0,-0.49,0.46,60.72,X40N,NTT,FOOTWEAR
3,ALKYLAMINE,-0.41,-18.69,136.81,92.54,112309.0,-18872.0,82091.0,4520.85,NaN,55.0,NaN,14.10,142.0,-0.17,0.53,55.88,SR,ATH,CHEMICALS
12,BOSCH-HCIL,3.74,-24.81,32.98,-0.01,31692.0,-31709.0,96096.0,2282.00,750.26,76.0,M-SC,5.88,231.0,-1.00,0.62,63.57,OX40N,BTT,AC
81,VALIANTORG,-8.72,-38.44,182.92,74.15,184215.0,-62897.0,100708.0,838.00,NaN,52.0,NaN,6.06,145.0,-0.34,0.65,49.87,XR,NTT,CHEMICALS

In [23]:
# top 5 RSP
df_tmp = df_portfolio_features.sort_values(by = 'RSP', ascending=False)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
25,FINCABLES,-0.59,66.30,25.02,107.91,61432.0,97887.0,245531.0,1641.55,21.20,75.0,M-SC,18.84,220.0,1.59,1.59,84.72,OX40N,ATH,CABLES
12,BOSCH-HCIL,3.74,-24.81,32.98,-0.01,31692.0,-31709.0,96096.0,2282.00,750.26,76.0,M-SC,5.88,231.0,-1.00,0.62,63.57,OX40N,BTT,AC
38,HYUNDAI,1.22,14.66,25.53,43.94,73570.0,36839.0,288171.0,2782.73,18.84,66.0,X-LC,5.02,29.0,0.50,1.86,32.31,X40N,ATH,AUTO
11,BERGEPAINT,-0.62,-0.17,25.53,25.32,65691.0,-441.0,257308.0,680.00,-13.25,58.0,X-MC,4.53,68.0,-0.01,1.66,34.93,XY24,NTT,PAINTS
81,VALIANTORG,-8.72,-38.44,182.92,74.15,184215.0,-62897.0,100708.0,838.00,NaN,52.0,NaN,6.06,145.0,-0.34,0.65,49.87,XR,NTT,CHEMICALS

In [24]:
# Top N allocation
df_tmp = df_portfolio_features.sort_values(by = 'CurrAlloc%', ascending=False)
top_n_values = [10, 25, 50]

sum_df = pd.DataFrame({
    'Top_N': top_n_values,
    'Sum_Alloc%': [df_tmp['CurrAlloc%'].head(n).sum() for n in top_n_values]
})

sum_df

   Top_N  Sum_Alloc%
0     10       19.79
1     25       45.20
2     50       77.65

In [25]:
# market-cap-wise allocation
df_tmp = df_portfolio_features[cols]
df_tmp.groupby(df_tmp['Conviction'].str[-2:])['CurrAlloc%'].sum().sort_values(ascending=False)

Conviction
LC    38.16
MC    22.21
SC    21.64
Name: CurrAlloc%, dtype: float64

In [26]:
# criteria-wise allocation
df_portfolio_features.groupby('Criteria')['CurrAlloc%'].sum().sort_values(ascending=False)

Criteria
X40      26.61
XY24     24.04
X40N     18.65
XR        9.11
OX40N     7.36
XY25      7.26
AR        6.16
SR        0.86
Name: CurrAlloc%, dtype: float64

In [27]:
# conviction-wise allocation
df_portfolio_features.groupby('Conviction')['CurrAlloc%'].sum().sort_values(ascending=False)

Conviction
X-LC    34.44
X-MC    19.58
H-SC     8.53
X-SC     7.66
M-SC     5.45
H-LC     2.91
M-MC     1.21
H-MC     1.05
M-LC     0.81
L-MC     0.37
Name: CurrAlloc%, dtype: float64

In [28]:
# sector-wise stats
df_tmp = df_portfolio_features.groupby('Category')[['CurrAlloc%', 'Current', 'Current P/L', 'FTT Amt']].sum().sort_values(by=['Current', 'Current P/L'], ascending=False)
df_tmp['Current P/L%'] = round(df_tmp['Current P/L'] * 100 / df_tmp['Current'], 2)
df_tmp['FTT%'] = round(df_tmp['FTT Amt'] * 100 / df_tmp['Current'], 2)
cols = ['CurrAlloc%', 'Current P/L%', 'FTT%']
df_tmp[cols].sort_values(by=['CurrAlloc%'], ascending=False)

               CurrAlloc%  Current P/L%    FTT%
Category
FMCG                15.48        -24.55   69.34
IT                  11.14        -38.60  107.35
FINANCE             10.74        -16.16   66.19
AUTO                 8.33         -4.98   42.58
BANKS                6.13        -12.57   61.12
MISC                 5.98        -33.32   86.94
PHARMA               5.77          7.03   19.34
INSURANCE            5.74         -4.67   41.69
PAINTS               5.52        -15.54   35.25
ELECTRICAL           4.21         -8.45   42.40
AC                   1.84        -12.39   42.86
REFINERIES           1.74        -10.44   47.54
BREWERIES            1.71         11.26    7.16
FOOTWEAR             1.67        -70.29  138.57
APPARELS             1.67         -3.90   38.80
CABLES               1.59         39.87   25.02
DURABLES             1.50        -67.39  108.11
TRAVEL               1.44       -100.44  200.80
CERAMICS             1.33        -48.70   93.87
ENGINEERING          1.20        -30.17   89.71
CHEMICALS            1.18        -44.73  162.21
CEMENT               1.02        -69.89  196.99
JEWELLERY            0.96       -115.96  190.99
ENTERTAINMENT        0.70        -79.75  186.96
HEALTHCARE           0.69        -70.41  113.18
TEXTILES             0.40        -49.76   92.46
HOTELS               0.37        -98.19  168.10

In [29]:
# money to be made criteria-wise
df_portfolio_features.groupby('Criteria')['FTT Amt'].agg(['sum', 'count']).sort_values(by='sum', ascending=False)

                sum  count
Criteria
XY24      3609763.0     19
X40       2109245.0     18
XR        1389595.0     13
X40N      1195840.0     12
AR        1053557.0      8
OX40N      655214.0     10
XY25       576281.0      5
SR         282569.0      2

In [30]:
# money to be made conviction-wise
df_portfolio_features.groupby('Conviction')['FTT Amt'].agg(['sum', 'count']).sort_values(by='sum', ascending=False)

                  sum  count
Conviction
X-LC        2402121.0     19
X-MC        1475693.0     14
X-SC        1092830.0      6
H-SC         833913.0      8
M-SC         321882.0      6
H-MC         251115.0      1
M-LC         167021.0      1
M-MC          57387.0      1
L-MC          44777.0      1
H-LC          40588.0      2

In [31]:
# money to be made criteria and conviction-wise
df_portfolio_features.groupby(['Conviction', 'Criteria'])['FTT Amt'].agg(['sum', 'count']).sort_values(by='sum', ascending=False)

                           sum  count
Conviction Criteria
X-LC       X40       1229448.0      9
X-SC       XY24       670393.0      2
H-SC       XY24       525519.0      3
X-MC       X40        516941.0      6
           X40N       465472.0      4
X-LC       XY24       451078.0      2
           X40N       410212.0      5
X-MC       XY25       267055.0      2
X-LC       XY25       251839.0      2
X-SC       X40        251486.0      2
H-MC       XY24       251115.0      1
X-MC       XY24       226225.0      2
H-SC       OX40N      214865.0      3
X-SC       X40N       170951.0      2
M-LC       XR         167021.0      1
M-SC       OX40N      149249.0      4
           XY24       115676.0      1
H-SC       XR          93529.0      2
X-LC       XR          59544.0      1
M-MC       XY25        57387.0      1
M-SC       XR          56957.0      1
L-MC       XR          44777.0      1
H-LC       AR          40588.0      2

In [32]:
# notebook execution time

end_time = time.time()
execution_time = round(end_time - start_time, 0)
print(f"Notebook execution time: {execution_time} seconds")

Notebook execution time: 38.0 seconds