<a href="https://colab.research.google.com/github/ankit-rathi/Quantvesting_v2/blob/main/myStocks_Portfolio_Analysis.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
'''
!pip install pandas==2.2.2 -qq
!pip install pyxirr -qq
!pip install ta -qq
!pip install yfinance==0.2.59 -qq
'''

'\n!pip install pandas==2.2.2 -qq\n!pip install pyxirr -qq\n!pip install ta -qq\n!pip install yfinance==0.2.59 -qq\n'

In [2]:
# import libraries

import numpy as np
import pandas as pd
import datetime
import warnings
warnings.filterwarnings('ignore')
import yfinance as yfin
import ta
import matplotlib.pyplot as plt
import requests

In [3]:
# notebook start time
import time
import datetime
import pytz

start_time = time.time()

# function to print date timestamp
def print_date_time():
  tz_NY = pytz.timezone('Asia/Kolkata')
  datetime_NY = datetime.datetime.now(tz_NY)
  print("Run date time (IST):", datetime_NY.strftime("%Y-%m-%d %H:%M:%S"))

In [4]:
# function to get booked and reserved amount
def get_amt():
  # fetch the JSON data from the URL
  url = "https://raw.githubusercontent.com/ankit-rathi/Tradevesting_v1/main/data/myPortfolioAmts.json"
  response = requests.get(url)
  pf_amts = response.json()  # parse the JSON data

  # extract values from the JSON
  py_booked_amt_dm = pf_amts["py_booked_amt_dm"]
  py_booked_amt_sv = pf_amts["py_booked_amt_sv"]
  cy_booked_amt_dm = pf_amts["cy_booked_amt_dm"]
  cy_booked_amt_sv = pf_amts["cy_booked_amt_sv"]
  reserve_amt_dm = pf_amts["reserve_amt_dm"]
  reserve_amt_sv = pf_amts["reserve_amt_sv"]

  # perform calculations
  py_booked_amt = py_booked_amt_dm + py_booked_amt_sv
  cy_booked_amt = cy_booked_amt_dm + cy_booked_amt_sv
  reserve_amt = reserve_amt_dm + reserve_amt_sv
  total_booked_amt = py_booked_amt + cy_booked_amt

  return total_booked_amt, reserve_amt, cy_booked_amt, py_booked_amt

gen_output = 0

In [5]:
# function to format the amount
def format_amt(number):
    abs_number = abs(number)

    if abs_number >= 1_00_00_000:  # Crores
        formatted_amt = f"{number / 1_00_00_000:.2f} C"
    elif abs_number >= 1_00_000:  # Lakhs
        formatted_amt = f"{number / 1_00_000:.2f} L"
    elif abs_number >= 1_000:  # Thousands
        formatted_amt = f"{number / 1_000:.2f} K"
    else:
        formatted_amt = f"{number:.2f}"

    return formatted_amt

# function to set start and end date
def get_start_end_date():
  start_date = (datetime.date.today() + datetime.timedelta(days=-365)).strftime('%Y-%m-%d')
  end_date = (datetime.date.today() + datetime.timedelta(days=1)).strftime('%Y-%m-%d')
  return start_date, end_date

# function to fetch my portfolio csv
def get_mypfs_df():
  mypfs_df = pd.read_csv('https://raw.githubusercontent.com/ankit-rathi/Tradevesting_v1/main/data/myPortfolioStocks.csv')
  return mypfs_df

# function to fetch my prospects csv
def get_mypps_df():
  mypps_df = pd.read_csv('https://raw.githubusercontent.com/ankit-rathi/Tradevesting_v1/main/data/myProspectsScrips.csv')
  return mypps_df

# function to fetch screener data
def get_myscreen_df():
  myscreen_df = pd.read_csv('https://raw.githubusercontent.com/ankit-rathi/Tradevesting_v1/main/data/myScreenerDB.csv')
  return myscreen_df

# function to fetch momentum data
def get_myinvmt_df():
  myinvmt_df = pd.read_csv('https://raw.githubusercontent.com/ankit-rathi/Tradevesting_v1/main/data/myInvestments.csv')
  return myinvmt_df

# function to get the stock ids
def get_stock_ids(df_pf):
  stock_n100 = df_pf['Symbol'].unique()

  exclude = ['CADILAHC','MMTC', 'MASFIN']

  stock_ids = df_pf[~df_pf['Symbol'].isin(exclude) ]['Symbol'].unique()

  #mypf = mypf[mypf.Forecast.notnull()]
  #stock_ids = mypf['Symbol'].unique()

  #stock_ids.sort()
  return stock_ids

# get features from screener data
def get_screener_features():
  myscreen_df = get_myscreen_df()
  cols = ['Symbol', 'EPS', 'MedPE', 'ROCE%', 'ROE%', 'CapType']
  return myscreen_df[cols]

# get relative strength
def get_relative_strength(stock_list):

    # Dictionary to store stock tickers and their corresponding percentage price change
    stock_changes = {}

    # Loop through each stock and fetch its price data
    for stock in stock_list:
        try:
            # Download the stock data for the given date range
            stock_data = yfin.Ticker(stock + '.NS').history(period='1mo', interval='1d')[map(str.title, ['open', 'close', 'low', 'high', 'volume'])]

            # Calculate the percentage change for the stock
            if len(stock_data) > 0:
                start_price = stock_data['Close'].iloc[0]
                end_price = stock_data['Close'].iloc[-1]
                percent_change = round(((end_price - start_price) / start_price) * 100, 2)
                stock_changes[stock] = percent_change
            else:
                stock_changes[stock] = np.nan  # If no data is available, set to NaN

        except Exception as e:
            print(f"Error fetching data for {stock}: {e}")
            stock_changes[stock] = np.nan

    # Create a DataFrame with stock tickers and their percentage changes
    df = pd.DataFrame(list(stock_changes.items()), columns=['Symbol', 'Percent_Change'])

    # Drop any stocks with missing data (NaN values)
    df = df.dropna()

    # Calculate the percentile rank based on percentage change
    df['RSP'] = round(df['Percent_Change'].rank(pct=True) * 100, 2)
    cols = ['Symbol', 'RSP']
    df = df[cols]
    # Sort by percentile rank (optional)
    df = df.sort_values(by='RSP', ascending=False).reset_index(drop=True)

    return df

In [6]:
# function to get stock technicals
def stock_prec_dev(stock_symbol):
    #stock_symbol = 'ULTRACEMCO.NS'
    short_window = 20
    mid_window = 50
    long_window = 200
    moving_avg = 'SMA'

    start = datetime.datetime(*map(int, start_date.split('-')))
    end = datetime.datetime(*map(int, end_date.split('-')))

    stock_df = yfin.Ticker(stock_symbol + '.NS').history(period='max', interval='1d')[map(str.title, ['open', 'close', 'low', 'high', 'volume'])]

    stock_df['Max'] = round(max(stock_df['Close']),2)
    stock_df = stock_df[(stock_df.index <= end_date) & (stock_df.index >= start_date)]
    stock_df['200_SMA'] = round(stock_df['Close'].rolling(window = 200, min_periods = 1).mean(),0)
    stock_df['Dev%_200'] = round((stock_df['Close'] - stock_df['200_SMA'])*100/stock_df['200_SMA'],2)
    stock_df.dropna(axis = 0, inplace = True) # remove any null rows

    stock_df['20_SMA'] = stock_df['Close'].rolling(window=20).mean()
    stock_df['50_SMA'] = stock_df['Close'].rolling(window=50).mean()
    stock_df['Symbol'] = stock_symbol

    stock_df['Close'] = round(stock_df['Close'],2)
    stock_df['Min'] = round(min(stock_df['Close']),2)
    stock_df['RSI_14'] = ta.momentum.RSIIndicator(close=stock_df['Close'], window=14).rsi()
    stock_df['RSI_14'] = round(stock_df['RSI_14'],0)
    stock_df['Prev_Close'] = stock_df['Close'].shift(1)
    stock_df.drop(['Open', 'Low', 'High', 'Volume'], axis=1, inplace=True)
    stock_df = stock_df.tail(1)

    max_SMA = max(stock_df['20_SMA'].item(), stock_df['50_SMA'].item(), stock_df['200_SMA'].item())
    min_SMA = min(stock_df['20_SMA'].item(), stock_df['50_SMA'].item(), stock_df['200_SMA'].item())
    ABS_Spread = max_SMA - min_SMA
    stock_df['Spread%'] = round((ABS_Spread / stock_df['200_SMA'].item()) * 100,2)

    return stock_df

# function to compute stock attributes
def get_common_features(stock_ids, df_mypf):

  df_prec_dev = pd.DataFrame()
  df_tmp = get_screener_features()
  df_rs = get_relative_strength(stock_ids)

  for stock_id in stock_ids:
      tmp = stock_prec_dev(stock_id)
      tmp = tmp.reset_index()
      df_prec_dev = pd.concat([df_prec_dev, tmp], ignore_index = True)
  df_prec_dev = pd.merge(df_prec_dev, df_mypf, on= 'Symbol')
  df_prec_dev = pd.merge(df_prec_dev, df_tmp, on= 'Symbol', how='left')
  df_prec_dev = pd.merge(df_prec_dev, df_rs, on= 'Symbol', how='left')
  #print(df_prec_dev.columns)
  df_prec_dev['Curr_PE'] = round(df_prec_dev['Close']/df_prec_dev['EPS'],1)
  df_prec_dev['Dev%_PE'] = round((df_prec_dev['Curr_PE'] - df_prec_dev['MedPE'])*100/df_prec_dev['MedPE'],2)
  df_prec_dev['Conviction'] = df_prec_dev['Conviction'] + '-' + df_prec_dev['CapType']
  return df_prec_dev

# function to arrange stock features
def arrange_features(df_stocks, common_cols, diff_cols):
  df_stocks_common = df_stocks[common_cols].drop_duplicates()
  df_stocks_diff = df_stocks[diff_cols]
  df_stocks_diff['Investment'] = df_stocks_diff['AvgCost'] * df_stocks_diff['Shares']
  df_stocks_diff = df_stocks_diff.groupby(['Symbol'])[['Shares', 'Investment']].aggregate(['sum']).reset_index()
  df_stocks_diff.columns = ['Symbol', 'Shares', 'Investment']
  df_stocks_diff['AvgCost'] = round(df_stocks_diff['Investment']/df_stocks_diff['Shares'],2)
  df_stocks = pd.merge(df_stocks_diff, df_stocks_common, on='Symbol')
  return df_stocks

# plot fact distribution across dimension
def plot_pie_chart(df, dimension, fact):
  # grouping the data by category and calculating the sum of fact for each type
  grouped_data = df.groupby(dimension)[fact].sum()

  # sorting the grouped data in descending order
  grouped_data = grouped_data.sort_values(ascending=False)

  # creating a pie chart
  grouped_data.plot.pie(autopct='%1.1f%%', startangle=90, figsize=(6, 6))

  # adding a title and displaying the plot
  plt.title(f'{dimension} {fact} Distribution')
  plt.ylabel('')  # To hide the y-label
  plt.show()

In [7]:
# function to get portfolio features

def get_portfolio_features(df_common_features):

  print_date_time()
  print('-------------------')

  #df_common_features["Target"] = df_common_features["Target"].fillna(df_common_features["Max"])
  df_common_features['NTT'] = np.where(df_common_features['Strategy']== 'NTT', df_common_features["Target"], df_common_features['Max'])
  df_common_features['LTT'] = np.where(df_common_features['Strategy']== 'BTT', df_common_features["Target"], df_common_features['Max'])
  df_common_features['BOL'] = df_common_features['Min']

  tmp_df = df_common_features[df_common_features['Symbol'].isin(mypf_df[mypf_df['InPortfolio'] != 'NA'].Symbol.values)]
  print('qualified stocks: '+str(len(tmp_df['Symbol'].unique())))
  tmp_df1 = tmp_df[tmp_df['LatestQtr'] == 1]
  print('with latest results: '+str(len(tmp_df1['Symbol'].unique())))
  tmp_df1 = tmp_df1[tmp_df1['StarStock'] == 1]
  print('still star stocks: '+str(len(tmp_df1['Symbol'].unique())))
  tmp_df['Investment'] = tmp_df['AvgCost'] * tmp_df['Shares']
  tmp_df['Current'] = round(tmp_df['Close'] * tmp_df['Shares'],0)
  tmp_df['Previous'] = tmp_df['Prev_Close'] * tmp_df['Shares']
  tmp_df['EstimatedST'] = tmp_df['NTT'] * tmp_df['Shares']
  tmp_df['EstimatedLT'] = tmp_df['LTT'] * tmp_df['Shares']
  tmp_df['Current P/L'] = round((tmp_df['Current'] - tmp_df['Investment']),0)
  tmp_df['Today P/L%'] = round((tmp_df['Current'] - tmp_df['Previous'])*100/tmp_df['Previous'],2)
  tmp_df['Current P/L%'] = round((tmp_df['Current'] - tmp_df['Investment'])*100/tmp_df['Investment'],2)
  tmp_df['EstimatedST P/L%'] = round((tmp_df['EstimatedST'] - tmp_df['Investment'])*100/tmp_df['Investment'],2)
  tmp_df['EstimatedLT P/L%'] = round((tmp_df['EstimatedLT'] - tmp_df['Investment'])*100/tmp_df['Investment'],2)
  tmp_df['NTT%'] = round((tmp_df['NTT'] - tmp_df['Close'])*100/tmp_df['Close'],2)
  tmp_df['LTT%'] = round((tmp_df['LTT'] - tmp_df['Close'])*100/tmp_df['Close'],2)
  tmp_df['Gained%'] = round((tmp_df['Close'] - tmp_df['BOL'])*100/tmp_df['BOL'],2)
  investment = round(sum(tmp_df['AvgCost']*tmp_df['Shares']),0)
  current = round(sum(tmp_df['Close']*tmp_df['Shares']),0)
  tmp_df['InitAlloc%'] = round(tmp_df['Investment']*100/investment,2)
  tmp_df['CurrAlloc%'] = round(tmp_df['Current']*100/current,2)
  tmp_df['FTT'] = tmp_df['LTT']
  tmp_df.loc[tmp_df['Strategy'] == 'NTT', 'FTT'] = tmp_df['NTT']
  tmp_df['FTT%'] = tmp_df['LTT%']
  tmp_df.loc[tmp_df['Strategy'] == 'NTT', 'FTT%'] = tmp_df['NTT%']
  tmp_df['FTT Amt'] = round(tmp_df['FTT%'] * tmp_df['Current']/100,0)
  tmp_df['OTT%'] = round((tmp_df['FTT'] - tmp_df['AvgCost'])*100/tmp_df['AvgCost'],2)
  tmp_df['RRR Ind'] = round(tmp_df['Current P/L']/tmp_df['FTT Amt'],2)
  tmp_df['Risk Ind'] = round(tmp_df['Current P/L%']*tmp_df['CurrAlloc%'],0)

  return tmp_df

# function to print portfolio features
def print_portfolio_stats(df_portfolio_features, myinvmt_df):
  from pyxirr import xirr

  total_booked_amt, reserve_amt, cy_booked_amt, py_booked_amt = get_amt()

  dates = myinvmt_df['Date'].values
  dates = np.append(dates, datetime.date.today().strftime('%d-%b-%y'))
  investment = myinvmt_df['Investment'].values
  dates= pd.to_datetime(dates)

  current = round(sum(df_portfolio_features['Close']*df_portfolio_features['Shares']),0) + reserve_amt
  investment_xirr = np.append(investment, current)
  cagr = round(xirr(pd.DataFrame({"dates": dates, "amounts": investment_xirr}))*100,2)

  investment = -sum(investment)
  invested = round(sum(df_portfolio_features['AvgCost']*df_portfolio_features['Shares']),0) + reserve_amt
  previous = round(sum(df_portfolio_features['Prev_Close']*df_portfolio_features['Shares']),0) + reserve_amt
  cy_invested = investment + py_booked_amt

  today_pnl_amount = current-previous
  today_pnl_percentage = round((current-previous)*100/previous,2)

  curr_pnl_amount = current-invested
  curr_pnl_percentage = round((curr_pnl_amount)*100/(cy_invested),2)

  cy_pnl_amount = cy_booked_amt + curr_pnl_amount
  cy_pnl_percentage = round((cy_pnl_amount)*100/cy_invested,2)

  overall_pnl_amount = total_booked_amt + curr_pnl_amount
  overall_pnl_percentage = round((overall_pnl_amount)*100/investment,2)

  estimate_st = round(sum(df_portfolio_features['FTT']*df_portfolio_features['Shares']),0)  + reserve_amt
  est_st_pnl_amount = estimate_st-current
  est_st_pnl_percentage = round((est_st_pnl_amount)*100/current,2)

  estimate_lt = round(sum(df_portfolio_features['LTT']*df_portfolio_features['Shares']),0)  + reserve_amt
  est_lt_pnl_amount = estimate_lt-current
  est_lt_pnl_percentage = round((est_lt_pnl_amount)*100/current,2)

  total_profit = round(sum(df_portfolio_features[df_portfolio_features['Current P/L%'] > 0]['Current']) - sum(df_portfolio_features[df_portfolio_features['Current P/L%'] > 0]['Investment']),0)
  total_loss = round(sum(df_portfolio_features[df_portfolio_features['Current P/L%'] < 0]['Current']) - sum(df_portfolio_features[df_portfolio_features['Current P/L%'] < 0]['Investment']),0)

  cy_booked_percentage = round((cy_booked_amt)*100/current,2)
  py_booked_percentage = round((py_booked_amt)*100/investment,2)
  total_booked_percentage = round((total_booked_amt)*100/investment,2)

  print('-------------------')
  print('Initial Investment: ', format_amt(investment))
  print('CY Investment: ', format_amt(cy_invested))
  print('Reserve: ', format_amt(reserve_amt))
  print('Current: ',  format_amt(current))
  print('-------------------')
  print('Today PnL: '+ '{} ({}%)'.format(format_amt(today_pnl_amount), today_pnl_percentage))
  print('Current PnL: '+ '{} ({}%)'.format(format_amt(curr_pnl_amount), curr_pnl_percentage))
  print('CY Booked + Current PnL: '+ '{} ({}%)'.format(format_amt(cy_pnl_amount), cy_pnl_percentage))
  print('-------------------')
  print('Total profit: ', format_amt(total_profit))
  print('Total loss: ', format_amt(total_loss))
  print('-------------------')
  print('Total Booked + Current PnL: '+ '{} ({}%)'.format(format_amt(overall_pnl_amount), overall_pnl_percentage))
  print('Total Booked PnL: '+ '{} ({}%)'.format(format_amt(total_booked_amt), total_booked_percentage))
  print('Curr Year Booked PnL: '+ '{} ({}%)'.format(format_amt(cy_booked_amt), cy_booked_percentage))
  print('Prev Year Booked PnL: '+ '{} ({}%)'.format(format_amt(py_booked_amt), py_booked_percentage))
  print('===================')
  print('Est FTT: ',  format_amt(estimate_st))
  print('Est FTT PnL: '+ '{} ({}%)'.format(format_amt(est_st_pnl_amount), est_st_pnl_percentage))

  print('===================')
  print('Deployed: ', format_amt(investment))

  print('Current: ', format_amt(current))

  print('CAGR/XIRR %: '+'{}%'.format(cagr))

In [8]:
# get start and end date
start_date, end_date = get_start_end_date()

# get portfolio and prospects data
mypfs_df = get_mypfs_df()
mypps_df = get_mypps_df()
myinvmt_df = get_myinvmt_df()

# merge above datasets
mypf_df = pd.merge(mypfs_df, mypps_df, on="Symbol")

# seggregate dm and sv portfolio
dm_pf = mypf_df[mypf_df['InPortfolio'] == 'DM']
sv_pf = mypf_df[mypf_df['InPortfolio'] == 'SV']

# build portfolio stock dataframe
dm_stocks = get_stock_ids(dm_pf)
sv_stocks = get_stock_ids(sv_pf)
df_stocks = pd.concat([dm_pf,sv_pf], ignore_index = True)

# arrange common and diff stock features
common_cols = ['Symbol', 'Target', 'Criteria', 'Strategy', 'CumlRnk', 'LatestQtr', 'StarStock', 'Conviction', 'Category', 'InFolio', 'XIRR', 'MBQ']
diff_cols = ['Symbol', 'AvgCost', 'Shares']
df_stocks = arrange_features(df_stocks, common_cols, diff_cols)

# get common features
stock_ids = df_stocks['Symbol'].values
df_common_features = get_common_features(stock_ids, df_stocks)

df_common_features.reset_index(drop=True, inplace=True)
df_common_features.drop(['Date'], axis=1, inplace=True)
# get and print portfolio features
df_portfolio_features = get_portfolio_features(df_common_features)

print_portfolio_stats(df_portfolio_features, myinvmt_df)

df = df_portfolio_features
#plot_pie_chart(df, 'CapType', 'Current')
list_ox40n = list(df[df['MBQ'].str.contains('OX40N', na=False)]['Symbol'].values)

Run date time (IST): 2026-03-25 11:13:54
-------------------
qualified stocks: 86
with latest results: 26
still star stocks: 16
-------------------
Initial Investment:  1.36 C
CY Investment:  1.62 C
Reserve:  1.61 K
Current:  1.32 C
-------------------
Today PnL: 3.16 L (2.45%)
Current PnL: -44.84 L (-27.6%)
CY Booked + Current PnL: -28.95 L (-17.82%)
-------------------
Total profit:  58.38 K
Total loss:  -45.43 L
-------------------
Total Booked + Current PnL: -1.97 L (-1.46%)
Total Booked PnL: 42.87 L (31.64%)
Curr Year Booked PnL: 15.89 L (12.01%)
Prev Year Booked PnL: 26.98 L (19.91%)
===================
Est FTT:  2.48 C
Est FTT PnL: 1.16 C (87.39%)
===================
Deployed:  1.36 C
Current:  1.32 C
CAGR/XIRR %: -1.18%

In [9]:
# top 5 near their targets
cols = ['Symbol', 'Today P/L%', 'Current P/L%', 'FTT%', 'OTT%', 'FTT Amt', 'Current P/L', 'Current', 'FTT', 'Dev%_PE', 'RSI_14','Conviction', 'Spread%',  'CumlRnk', 'RRR Ind', 'CurrAlloc%', 'Gained%', 'Criteria', 'Strategy', 'Category']
df_tmp = df_portfolio_features[~df_portfolio_features['Symbol'].isin(['ENRIN','BLUSPRING','DIGITIDE'])]
df_tmp = df_tmp.sort_values(by = 'FTT Amt', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
50,MASFIN,1.95,-7.01,30.73,21.57,27998.0,-6870.0,91110.0,397.04,-20.05,47.0,H-SC,2.85,167.0,-0.25,0.69,24.27,XR,ATH,FINANCE
77,TTKPRESTIG,1.44,-42.17,73.09,0.09,42593.0,-42502.0,58275.0,770.00,35.33,36.0,M-SC,19.97,250.0,-1.00,0.44,1.44,OX40N,NTT,DURABLES
2,ABBOTINDIA,0.58,-9.57,30.57,18.07,49441.0,-17125.0,161730.0,35195.00,-23.01,52.0,X-MC,10.44,58.0,-0.35,1.22,5.77,X40,ATH,PHARMA
67,SONACOMS,4.46,-10.60,55.59,39.09,50271.0,-10728.0,90431.0,804.02,-29.11,53.0,M-MC,7.33,193.0,-0.21,0.68,27.93,AR,ATH,AUTO
42,INDUSINDBK,4.31,-38.60,116.45,32.89,55198.0,-29806.0,47401.0,1800.00,-323.39,43.0,L-MC,8.02,258.0,-0.54,0.36,30.54,XR,NTT,BANKS

In [10]:
# top 5 today
df_tmp = df_portfolio_features.sort_values(by = 'Today P/L%', ascending=False)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
56,RAJOOENG,6.16,-47.36,165.20,39.61,89142.0,-48540.0,53960.0,143.1,-64.48,37.0,H-SC,32.24,136.0,-0.54,0.41,6.16,AR,ATH,MISC
16,CAMPUS,6.00,-20.37,67.38,33.28,90020.0,-34174.0,133601.0,393.0,-35.82,44.0,M-SC,10.93,218.0,-0.38,1.01,7.14,XY24,NTT,FOOTWEAR
48,KANSAINER,5.19,-43.38,100.40,13.47,153305.0,-116973.0,152694.0,340.0,-51.41,33.0,H-SC,21.16,162.0,-0.76,1.15,6.66,XY24,NTT,PAINTS
55,RAJESHEXPO,5.00,-82.79,481.43,0.07,113661.0,-113568.0,23609.0,518.0,764.90,20.0,L-SC,36.05,268.0,-1.00,0.18,5.00,OX40N,NTT,JEWELLERY
51,MEDANTA,4.82,-12.69,45.59,27.12,70266.0,-22391.0,154126.0,1486.0,-15.35,39.0,X-SC,12.77,87.0,-0.32,1.17,5.27,XY24,NTT,HEALTHCARE

In [11]:
# bottom 5 today
df_tmp = df_portfolio_features.sort_values(by = 'Today P/L%', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
4,ALKYLAMINE,-1.56,-40.69,226.44,93.63,135606.0,-41077.0,59886.0,4546.37,-36.55,50.0,H-SC,25.92,142.0,-0.30,0.45,12.37,SR,ATH,CHEMICALS
78,UNITDSPR,-1.20,-3.62,25.30,20.77,57093.0,-8480.0,225664.0,1644.00,-14.48,45.0,X-MC,1.95,64.0,-0.15,1.71,2.89,X40N,NTT,BREWERIES
76,TRIDENT,-0.47,-32.29,89.80,28.51,56094.0,-29788.0,62466.0,48.00,-12.92,55.0,M-SC,14.09,223.0,-0.53,0.47,14.64,XR,NTT,TEXTILES
66,SIS,0.04,-35.43,87.80,21.26,62946.0,-39339.0,71693.0,528.00,1676.68,43.0,H-SC,14.40,168.0,-0.62,0.54,6.60,OX40N,NTT,MISC
49,LAOPALA,0.15,-45.62,155.79,39.09,111063.0,-59815.0,71290.0,464.00,55.93,37.0,H-SC,15.70,154.0,-0.54,0.54,2.40,AR,NTT,CERAMICS

In [12]:
# top 5 to exit based on CumlRnk
df_tmp = df_portfolio_features[~df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])]
df_tmp = df_tmp[(df_tmp['Current P/L%'] > -1) & (df_tmp['Current P/L%'] < 1)].sort_values(by = 'CumlRnk', ascending=False)
df_tmp[cols].head()

Empty DataFrame
Columns: [Symbol, Today P/L%, Current P/L%, FTT%, OTT%, FTT Amt, Current P/L, Current, FTT, Dev%_PE, RSI_14, Conviction, Spread%, CumlRnk, RRR Ind, CurrAlloc%, Gained%, Criteria, Strategy, Category]
Index: []

In [13]:
# OX40N stocks to exit
df_tmp = df_portfolio_features[(df_portfolio_features['Symbol'].isin(list_ox40n))].sort_values(by = 'Current P/L%', ascending=False)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
26,FINCABLES,2.26,5.59,96.90,107.91,151069.0,8258.0,155902.0,1641.55,-5.12,47.0,M-SC,8.13,220.0,0.05,1.18,17.29,OX40N,ATH,CABLES
66,SIS,0.04,-35.43,87.80,21.26,62946.0,-39339.0,71693.0,528.00,1676.68,43.0,H-SC,14.40,168.0,-0.62,0.54,6.60,OX40N,NTT,MISC
18,CERA,1.71,-37.48,98.17,23.89,107958.0,-65933.0,109970.0,9475.00,-39.62,49.0,H-SC,19.02,153.0,-0.61,0.83,5.68,OX40N,NTT,CERAMICS
72,TATAELXSI,2.02,-38.54,114.80,32.03,93024.0,-50804.0,81031.0,9161.00,-23.05,42.0,H-SC,21.00,158.0,-0.55,0.61,5.58,OX40N,NTT,IT
77,TTKPRESTIG,1.44,-42.17,73.09,0.09,42593.0,-42502.0,58275.0,770.00,35.33,36.0,M-SC,19.97,250.0,-1.00,0.44,1.44,OX40N,NTT,DURABLES

In [14]:
# top 5 to book for rotation
df_tmp = df_portfolio_features[(df_portfolio_features['Current P/L%'] > 20) ].sort_values(by = 'CumlRnk', ascending=False)
df_tmp[cols].head()

Empty DataFrame
Columns: [Symbol, Today P/L%, Current P/L%, FTT%, OTT%, FTT Amt, Current P/L, Current, FTT, Dev%_PE, RSI_14, Conviction, Spread%, CumlRnk, RRR Ind, CurrAlloc%, Gained%, Criteria, Strategy, Category]
Index: []

In [15]:
# top 5 to monitor for exit
df_tmp = df_portfolio_features[~df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])]
df_tmp = df_tmp[(df_tmp['Current P/L%'] > 0) ].sort_values(by = 'Dev%_PE', ascending=False)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
26,FINCABLES,2.26,5.59,96.90,107.91,151069.0,8258.0,155902.0,1641.55,-5.12,47.0,M-SC,8.13,220.0,0.05,1.18,17.29,OX40N,ATH,CABLES
1,ABB,1.20,14.41,27.23,45.57,81507.0,37709.0,299328.0,7934.00,-26.49,56.0,H-MC,13.44,125.0,0.46,2.26,32.92,AR,NTT,ELECTRICAL

In [16]:
# top 5 to book for rotation from weak conviction
df_tmp = df_portfolio_features[~df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])]
df_tmp = df_tmp[~df_tmp['Criteria'].isin(['XY25','XY24','X40', 'X40N'])].sort_values(by = 'RRR Ind', ascending=False)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
1,ABB,1.20,14.41,27.23,45.57,81507.0,37709.0,299328.0,7934.00,-26.49,56.0,H-MC,13.44,125.0,0.46,2.26,32.92,AR,NTT,ELECTRICAL
26,FINCABLES,2.26,5.59,96.90,107.91,151069.0,8258.0,155902.0,1641.55,-5.12,47.0,M-SC,8.13,220.0,0.05,1.18,17.29,OX40N,ATH,CABLES
40,INDIAMART,3.46,-12.68,136.75,106.72,147267.0,-15645.0,107691.0,4810.62,-60.55,41.0,H-SC,11.96,140.0,-0.11,0.81,7.73,AR,ATH,MISC
85,ZYDUSLIFE,2.15,-4.52,42.05,35.63,84144.0,-9470.0,200104.0,1286.17,-17.12,52.0,H-MC,5.39,120.0,-0.11,1.51,11.40,AR,ATH,PHARMA
67,SONACOMS,4.46,-10.60,55.59,39.09,50271.0,-10728.0,90431.0,804.02,-29.11,53.0,M-MC,7.33,193.0,-0.21,0.68,27.93,AR,ATH,AUTO

In [17]:
# top 5 to accumulate based on lowest RSI_14
df_tmp = df_portfolio_features[df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])].sort_values(by = 'RSI_14', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
53,PGHH,1.25,-27.95,83.22,32.01,128026.0,-59680.0,153840.0,17616.87,-51.29,20.0,X-MC,16.47,57.0,-0.47,1.16,1.68,X40,ATH,FMCG
37,ICICIGI,0.46,-8.35,30.22,19.34,55421.0,-16718.0,183391.0,2252.93,-23.02,27.0,X-MC,3.73,66.0,-0.30,1.39,1.38,X40,ATH,INSURANCE
58,RELAXO,4.08,-65.16,337.09,52.31,170503.0,-94579.0,50581.0,1176.00,-62.93,28.0,X-SC,27.40,92.0,-0.55,0.38,5.57,X40N,NTT,FOOTWEAR
38,ICICIPRULI,2.05,-9.24,44.03,30.73,78730.0,-18194.0,178811.0,790.00,-33.64,29.0,X-MC,4.91,78.0,-0.23,1.35,3.25,X40,ATH,INSURANCE
12,BATAINDIA,2.93,-57.50,218.15,35.20,119284.0,-73990.0,54680.0,2096.00,-28.38,31.0,X-SC,31.76,91.0,-0.62,0.41,5.28,X40,NTT,FOOTWEAR

In [18]:
# top 5 to accumulate based on Spread and CumlRnk
df_tmp = df_portfolio_features[df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])]
df_tmp = df_tmp[(df_tmp['CumlRnk'] < 100)].sort_values(by = 'Spread%', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
78,UNITDSPR,-1.20,-3.62,25.30,20.77,57093.0,-8480.0,225664.0,1644.00,-14.48,45.0,X-MC,1.95,64.0,-0.15,1.71,2.89,X40N,NTT,BREWERIES
65,SIEMENS,3.42,-16.59,50.47,25.51,78345.0,-30865.0,155230.0,4671.50,30.44,46.0,H-LC,2.34,51.0,-0.39,1.17,14.31,AR,ATH,ELECTRICAL
59,RELIANCE,1.09,-8.39,36.77,25.30,67697.0,-16854.0,184109.0,1952.00,-10.80,54.0,X-LC,3.46,21.0,-0.25,1.39,22.92,XY25,BTT,REFINERIES
82,VOLTAS,4.52,6.47,36.37,45.20,74249.0,12408.0,204150.0,1856.00,21.95,44.0,X-MC,3.54,79.0,0.17,1.54,13.71,XY25,NTT,AC
37,ICICIGI,0.46,-8.35,30.22,19.34,55421.0,-16718.0,183391.0,2252.93,-23.02,27.0,X-MC,3.73,66.0,-0.30,1.39,1.38,X40,ATH,INSURANCE

In [19]:
# top 5 to accumulate based on lowest Gained%
df_tmp = df_portfolio_features[df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])].sort_values(by = 'Gained%', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
37,ICICIGI,0.46,-8.35,30.22,19.34,55421.0,-16718.0,183391.0,2252.93,-23.02,27.0,X-MC,3.73,66.0,-0.30,1.39,1.38,X40,ATH,INSURANCE
53,PGHH,1.25,-27.95,83.22,32.01,128026.0,-59680.0,153840.0,17616.87,-51.29,20.0,X-MC,16.47,57.0,-0.47,1.16,1.68,X40,ATH,FMCG
9,BAJAJHFL,1.98,-28.26,126.00,62.13,246804.0,-77170.0,195876.0,181.50,-41.06,35.0,X-MC,20.76,60.0,-0.31,1.48,2.29,X40N,ATH,FINANCE
45,ITC,2.27,-21.55,51.75,19.06,138107.0,-73292.0,266874.0,452.00,-57.14,39.0,X-LC,18.78,1.0,-0.53,2.02,2.55,X40,NTT,FMCG
73,TCS,0.84,-28.99,78.24,26.57,257397.0,-134289.0,328984.0,4311.58,-40.02,33.0,X-LC,17.52,2.0,-0.52,2.49,2.67,X40,ATH,IT

In [20]:
# top 5 to accumulate based on lowest CurrAlloc%
df_tmp = df_portfolio_features[df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])].sort_values(by = 'CurrAlloc%', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
58,RELAXO,4.08,-65.16,337.09,52.31,170503.0,-94579.0,50581.0,1176.00,-62.93,28.0,X-SC,27.40,92.0,-0.55,0.38,5.57,X40N,NTT,FOOTWEAR
12,BATAINDIA,2.93,-57.50,218.15,35.20,119284.0,-73990.0,54680.0,2096.00,-28.38,31.0,X-SC,31.76,91.0,-0.62,0.41,5.28,X40,NTT,FOOTWEAR
54,QUESS,1.44,-27.00,138.23,73.90,107757.0,-28838.0,77955.0,424.00,-60.88,41.0,X-SC,21.59,80.0,-0.27,0.59,4.77,XY24,NTT,MISC
36,HONAUT,2.10,-26.83,106.79,51.31,150681.0,-51738.0,141100.0,58357.33,-39.15,34.0,X-SC,16.19,90.0,-0.34,1.07,3.69,X40N,ATH,ELECTRICAL
53,PGHH,1.25,-27.95,83.22,32.01,128026.0,-59680.0,153840.0,17616.87,-51.29,20.0,X-MC,16.47,57.0,-0.47,1.16,1.68,X40,ATH,FMCG

In [21]:
# top 5 to accumulate based on CumlRnk
df_tmp = df_portfolio_features.sort_values(by = 'CumlRnk', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
45,ITC,2.27,-21.55,51.75,19.06,138107.0,-73292.0,266874.0,452.00,-57.14,39.0,X-LC,18.78,1.0,-0.53,2.02,2.55,X40,NTT,FMCG
73,TCS,0.84,-28.99,78.24,26.57,257397.0,-134289.0,328984.0,4311.58,-40.02,33.0,X-LC,17.52,2.0,-0.52,2.49,2.67,X40,ATH,IT
43,INFY,0.87,-12.22,52.94,34.24,145395.0,-38246.0,274642.0,1972.00,-31.06,44.0,X-LC,15.03,3.0,-0.26,2.08,5.62,X40,NTT,IT
75,TMPV,3.34,-26.79,86.57,36.58,225511.0,-95345.0,260496.0,600.00,-84.72,42.0,X-LC,7.47,4.0,-0.42,1.97,5.36,XY24,NTT,AUTO
33,HCLTECH,1.56,-9.49,36.82,23.83,80624.0,-22956.0,218968.0,1908.19,-4.88,50.0,X-LC,11.61,8.0,-0.28,1.66,6.32,X40,ATH,IT

In [22]:
# top 5 for average up
df_tmp = df_portfolio_features[(df_portfolio_features['Dev%_200'] > 5)].sort_values(by = 'CurrAlloc%', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
67,SONACOMS,4.46,-10.60,55.59,39.09,50271.0,-10728.0,90431.0,804.02,-29.11,53.0,M-MC,7.33,193.0,-0.21,0.68,27.93,AR,ATH,AUTO
1,ABB,1.20,14.41,27.23,45.57,81507.0,37709.0,299328.0,7934.00,-26.49,56.0,H-MC,13.44,125.0,0.46,2.26,32.92,AR,NTT,ELECTRICAL

In [23]:
# top 5 RSP
df_tmp = df_portfolio_features.sort_values(by = 'RSP', ascending=False)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
30,HAPPSTMNDS,1.50,-49.39,265.25,84.85,172052.0,-63301.0,64864.0,1480.71,-39.74,56.0,H-SC,26.07,152.0,-0.37,0.49,20.12,AR,ATH,IT
69,SURYODAY,2.00,-27.07,68.70,23.03,89723.0,-48470.0,130601.0,216.00,42.54,50.0,H-SC,5.91,166.0,-0.54,0.99,27.64,XR,NTT,BANKS
59,RELIANCE,1.09,-8.39,36.77,25.30,67697.0,-16854.0,184109.0,1952.00,-10.80,54.0,X-LC,3.46,21.0,-0.25,1.39,22.92,XY25,BTT,REFINERIES
2,ABBOTINDIA,0.58,-9.57,30.57,18.07,49441.0,-17125.0,161730.0,35195.00,-23.01,52.0,X-MC,10.44,58.0,-0.35,1.22,5.77,X40,ATH,PHARMA
23,DIXON,3.69,-23.15,79.46,37.92,159262.0,-60367.0,200431.0,18931.72,-67.33,50.0,X-MC,27.81,54.0,-0.38,1.52,7.60,X40N,ATH,IT

In [24]:
# Top N allocation
df_tmp = df_portfolio_features.sort_values(by = 'CurrAlloc%', ascending=False)
top_n_values = [10, 25, 50]

sum_df = pd.DataFrame({
    'Top_N': top_n_values,
    'Sum_Alloc%': [df_tmp['CurrAlloc%'].head(n).sum() for n in top_n_values]
})

sum_df

   Top_N  Sum_Alloc%
0     10       20.75
1     25       45.93
2     50       78.18

In [25]:
# market-cap-wise allocation
df_tmp = df_portfolio_features[cols]
df_tmp.groupby(df_tmp['Conviction'].str[-2:])['CurrAlloc%'].sum().sort_values(ascending=False)

Conviction
SC    44.32
MC    30.08
LC    25.59
Name: CurrAlloc%, dtype: float64

In [26]:
# criteria-wise allocation
df_portfolio_features.groupby('Criteria')['CurrAlloc%'].sum().sort_values(ascending=False)

Criteria
XY24     27.08
X40      25.43
X40N     15.22
AR        9.17
XR        8.29
XY25      7.36
OX40N     6.63
SR        0.81
Name: CurrAlloc%, dtype: float64

In [27]:
# conviction-wise allocation
df_portfolio_features.groupby('Conviction')['CurrAlloc%'].sum().sort_values(ascending=False)

Conviction
X-LC    23.42
X-MC    22.60
H-SC    21.57
X-SC    12.26
M-SC     9.96
H-MC     5.07
M-MC     2.05
H-LC     1.17
M-LC     1.00
L-SC     0.53
L-MC     0.36
Name: CurrAlloc%, dtype: float64

In [28]:
# sector-wise stats
df_tmp = df_portfolio_features.groupby('Category')[['CurrAlloc%', 'Current', 'Current P/L', 'FTT Amt']].sum().sort_values(by=['Current', 'Current P/L'], ascending=False)
df_tmp['Current P/L%'] = round(df_tmp['Current P/L'] * 100 / df_tmp['Current'], 2)
df_tmp['FTT%'] = round(df_tmp['FTT Amt'] * 100 / df_tmp['Current'], 2)
cols = ['CurrAlloc%', 'Current P/L%', 'FTT%']
df_tmp[cols].sort_values(by=['CurrAlloc%'], ascending=False)

               CurrAlloc%  Current P/L%    FTT%
Category
FMCG                15.06        -25.37   69.88
FINANCE             13.11        -24.07   74.64
IT                  11.87        -43.66  116.77
MISC                 6.93        -46.16  109.66
ELECTRICAL           6.53        -12.01   54.90
PAINTS               5.14        -44.68   69.81
INSURANCE            4.64        -10.46   48.27
BANKS                4.60        -26.52   90.75
PHARMA               4.15         -6.96   40.63
AUTO                 3.74        -31.98   84.35
AC                   2.06        -16.92   48.62
HEALTHCARE           1.90        -42.81   80.07
TRAVEL               1.80        -87.11  180.80
FOOTWEAR             1.80        -84.88  159.01
APPARELS             1.76        -15.45   54.83
DURABLES             1.74        -68.21  109.13
BREWERIES            1.71         -3.76   25.30
REALTY               1.47        -14.18   32.94
REFINERIES           1.39         -9.15   36.77
CERAMICS             1.37        -69.37  120.83
CEMENT               1.25        -62.21  183.56
CABLES               1.18          5.30   96.90
ENGINEERING          1.10        -66.28  142.33
CHEMICALS            1.07        -87.17  239.87
JEWELLERY            1.03       -134.65  216.18
ENTERTAINMENT        0.77        -91.45  205.62
TEXTILES             0.47        -47.69   89.80
HOTELS               0.35       -146.32  233.19

In [29]:
# money to be made criteria-wise
df_portfolio_features.groupby('Criteria')['FTT Amt'].agg(['sum', 'count']).sort_values(by='sum', ascending=False)

                sum  count
Criteria
XY24      4014735.0     21
X40       1810797.0     16
XR        1396466.0     12
AR        1357446.0     10
X40N      1287763.0     10
OX40N      914866.0     10
XY25       466535.0      5
SR         311570.0      2

In [30]:
# money to be made conviction-wise
df_portfolio_features.groupby('Conviction')['FTT Amt'].agg(['sum', 'count']).sort_values(by='sum', ascending=False)

                  sum  count
Conviction
H-SC        3940244.0     24
X-MC        1744310.0     15
X-LC        1680389.0     13
M-SC        1598673.0     14
X-SC        1560447.0     10
H-MC         407025.0      3
L-SC         221159.0      2
M-LC         159621.0      1
M-MC         114767.0      2
H-LC          78345.0      1
L-MC          55198.0      1

In [31]:
# money to be made criteria and conviction-wise
df_portfolio_features.groupby(['Conviction', 'Criteria'])['FTT Amt'].agg(['sum', 'count']).sort_values(by='sum', ascending=False)

                           sum  count
Conviction Criteria
H-SC       XY24      1365259.0      6
           AR         985226.0      5
M-SC       XY24       923555.0      6
X-LC       X40        903608.0      7
H-SC       XR         883470.0      7
X-SC       XY24       845374.0      4
X-MC       X40        692913.0      7
           X40N       527136.0      4
X-SC       X40N       500797.0      4
M-SC       OX40N      406486.0      5
H-SC       OX40N      394719.0      4
X-LC       XY24       371041.0      2
H-SC       SR         311570.0      2
X-MC       XY24       268132.0      2
X-LC       X40N       259830.0      2
X-MC       XY25       256129.0      2
H-MC       XY24       241374.0      1
X-SC       X40        214276.0      2
M-SC       XR         190679.0      2
H-MC       AR         165651.0      2
M-LC       XR         159621.0      1
X-LC       XY25       145910.0      2
L-SC       OX40N      113661.0      1
           XR         107498.0      1
H-LC       AR          78345.0      1
M-SC       AR          77953.0      1
M-MC       XY25        64496.0      1
L-MC       XR          55198.0      1
M-MC       AR          50271.0      1

In [32]:
# notebook execution time

end_time = time.time()
execution_time = round(end_time - start_time, 0)
print(f"Notebook execution time: {execution_time} seconds")

Notebook execution time: 30.0 seconds