<a href="https://colab.research.google.com/github/ankit-rathi/Quantvesting_v2/blob/main/myStocks_Portfolio_Analysis.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
'''
!pip install pandas==2.2.2 -qq
!pip install pyxirr -qq
!pip install ta -qq
!pip install yfinance==0.2.59 -qq
'''

'\n!pip install pandas==2.2.2 -qq\n!pip install pyxirr -qq\n!pip install ta -qq\n!pip install yfinance==0.2.59 -qq\n'

In [2]:
# import libraries

import numpy as np
import pandas as pd
import datetime
import warnings
warnings.filterwarnings('ignore')
import yfinance as yfin
import ta
import matplotlib.pyplot as plt
import requests

In [3]:
# notebook start time
import time
import datetime
import pytz

start_time = time.time()

# function to print date timestamp
def print_date_time():
  tz_NY = pytz.timezone('Asia/Kolkata')
  datetime_NY = datetime.datetime.now(tz_NY)
  print("Run date time (IST):", datetime_NY.strftime("%Y-%m-%d %H:%M:%S"))

In [4]:
# function to get booked and reserved amount
def get_amt():
  # fetch the JSON data from the URL
  url = "https://raw.githubusercontent.com/ankit-rathi/Tradevesting_v1/main/data/myPortfolioAmts.json"
  response = requests.get(url)
  pf_amts = response.json()  # parse the JSON data

  # extract values from the JSON
  py_booked_amt_dm = pf_amts["py_booked_amt_dm"]
  py_booked_amt_sv = pf_amts["py_booked_amt_sv"]
  cy_booked_amt_dm = pf_amts["cy_booked_amt_dm"]
  cy_booked_amt_sv = pf_amts["cy_booked_amt_sv"]
  reserve_amt_dm = pf_amts["reserve_amt_dm"]
  reserve_amt_sv = pf_amts["reserve_amt_sv"]

  # perform calculations
  py_booked_amt = py_booked_amt_dm + py_booked_amt_sv
  cy_booked_amt = cy_booked_amt_dm + cy_booked_amt_sv
  reserve_amt = reserve_amt_dm + reserve_amt_sv
  total_booked_amt = py_booked_amt + cy_booked_amt

  return total_booked_amt, reserve_amt, cy_booked_amt, py_booked_amt

gen_output = 0

In [5]:
# function to format the amount
def format_amt(number):
    abs_number = abs(number)

    if abs_number >= 1_00_00_000:  # Crores
        formatted_amt = f"{number / 1_00_00_000:.2f} C"
    elif abs_number >= 1_00_000:  # Lakhs
        formatted_amt = f"{number / 1_00_000:.2f} L"
    elif abs_number >= 1_000:  # Thousands
        formatted_amt = f"{number / 1_000:.2f} K"
    else:
        formatted_amt = f"{number:.2f}"

    return formatted_amt

# function to set start and end date
def get_start_end_date():
  start_date = (datetime.date.today() + datetime.timedelta(days=-365)).strftime('%Y-%m-%d')
  end_date = (datetime.date.today() + datetime.timedelta(days=1)).strftime('%Y-%m-%d')
  return start_date, end_date

# function to fetch my portfolio csv
def get_mypfs_df():
  mypfs_df = pd.read_csv('https://raw.githubusercontent.com/ankit-rathi/Tradevesting_v1/main/data/myPortfolioStocks.csv')
  return mypfs_df

# function to fetch my prospects csv
def get_mypps_df():
  mypps_df = pd.read_csv('https://raw.githubusercontent.com/ankit-rathi/Tradevesting_v1/main/data/myProspectsScrips.csv')
  return mypps_df

# function to fetch screener data
def get_myscreen_df():
  myscreen_df = pd.read_csv('https://raw.githubusercontent.com/ankit-rathi/Tradevesting_v1/main/data/myScreenerDB.csv')
  return myscreen_df

# function to fetch momentum data
def get_myinvmt_df():
  myinvmt_df = pd.read_csv('https://raw.githubusercontent.com/ankit-rathi/Tradevesting_v1/main/data/myInvestments.csv')
  return myinvmt_df

# function to get the stock ids
def get_stock_ids(df_pf):
  stock_n100 = df_pf['Symbol'].unique()

  exclude = ['CADILAHC','MMTC', 'MASFIN']

  stock_ids = df_pf[~df_pf['Symbol'].isin(exclude) ]['Symbol'].unique()

  #mypf = mypf[mypf.Forecast.notnull()]
  #stock_ids = mypf['Symbol'].unique()

  #stock_ids.sort()
  return stock_ids

# get features from screener data
def get_screener_features():
  myscreen_df = get_myscreen_df()
  cols = ['Symbol', 'EPS', 'MedPE', 'ROCE%', 'ROE%', 'CapType']
  return myscreen_df[cols]

# get relative strength
def get_relative_strength(stock_list):

    # Dictionary to store stock tickers and their corresponding percentage price change
    stock_changes = {}

    # Loop through each stock and fetch its price data
    for stock in stock_list:
        try:
            # Download the stock data for the given date range
            stock_data = yfin.Ticker(stock + '.NS').history(period='1mo', interval='1d')[map(str.title, ['open', 'close', 'low', 'high', 'volume'])]

            # Calculate the percentage change for the stock
            if len(stock_data) > 0:
                start_price = stock_data['Close'].iloc[0]
                end_price = stock_data['Close'].iloc[-1]
                percent_change = round(((end_price - start_price) / start_price) * 100, 2)
                stock_changes[stock] = percent_change
            else:
                stock_changes[stock] = np.nan  # If no data is available, set to NaN

        except Exception as e:
            print(f"Error fetching data for {stock}: {e}")
            stock_changes[stock] = np.nan

    # Create a DataFrame with stock tickers and their percentage changes
    df = pd.DataFrame(list(stock_changes.items()), columns=['Symbol', 'Percent_Change'])

    # Drop any stocks with missing data (NaN values)
    df = df.dropna()

    # Calculate the percentile rank based on percentage change
    df['RSP'] = round(df['Percent_Change'].rank(pct=True) * 100, 2)
    cols = ['Symbol', 'RSP']
    df = df[cols]
    # Sort by percentile rank (optional)
    df = df.sort_values(by='RSP', ascending=False).reset_index(drop=True)

    return df

In [6]:
# function to get stock technicals
def stock_prec_dev(stock_symbol):
    #stock_symbol = 'ULTRACEMCO.NS'
    short_window = 20
    mid_window = 50
    long_window = 200
    moving_avg = 'SMA'

    start = datetime.datetime(*map(int, start_date.split('-')))
    end = datetime.datetime(*map(int, end_date.split('-')))

    stock_df = yfin.Ticker(stock_symbol + '.NS').history(period='max', interval='1d')[map(str.title, ['open', 'close', 'low', 'high', 'volume'])]

    stock_df['Max'] = round(max(stock_df['Close']),2)
    stock_df = stock_df[(stock_df.index <= end_date) & (stock_df.index >= start_date)]
    stock_df['200_SMA'] = round(stock_df['Close'].rolling(window = 200, min_periods = 1).mean(),0)
    stock_df['Dev%_200'] = round((stock_df['Close'] - stock_df['200_SMA'])*100/stock_df['200_SMA'],2)
    stock_df.dropna(axis = 0, inplace = True) # remove any null rows

    stock_df['20_SMA'] = stock_df['Close'].rolling(window=20).mean()
    stock_df['50_SMA'] = stock_df['Close'].rolling(window=50).mean()
    stock_df['Symbol'] = stock_symbol

    stock_df['Close'] = round(stock_df['Close'],2)
    stock_df['Min'] = round(min(stock_df['Close']),2)
    stock_df['RSI_14'] = ta.momentum.RSIIndicator(close=stock_df['Close'], window=14).rsi()
    stock_df['RSI_14'] = round(stock_df['RSI_14'],0)
    stock_df['Prev_Close'] = stock_df['Close'].shift(1)
    stock_df.drop(['Open', 'Low', 'High', 'Volume'], axis=1, inplace=True)
    stock_df = stock_df.tail(1)

    max_SMA = max(stock_df['20_SMA'].item(), stock_df['50_SMA'].item(), stock_df['200_SMA'].item())
    min_SMA = min(stock_df['20_SMA'].item(), stock_df['50_SMA'].item(), stock_df['200_SMA'].item())
    ABS_Spread = max_SMA - min_SMA
    stock_df['Spread%'] = round((ABS_Spread / stock_df['200_SMA'].item()) * 100,2)

    return stock_df

# function to compute stock attributes
def get_common_features(stock_ids, df_mypf):

  df_prec_dev = pd.DataFrame()
  df_tmp = get_screener_features()
  df_rs = get_relative_strength(stock_ids)

  for stock_id in stock_ids:
      tmp = stock_prec_dev(stock_id)
      tmp = tmp.reset_index()
      df_prec_dev = pd.concat([df_prec_dev, tmp], ignore_index = True)
  df_prec_dev = pd.merge(df_prec_dev, df_mypf, on= 'Symbol')
  df_prec_dev = pd.merge(df_prec_dev, df_tmp, on= 'Symbol', how='left')
  df_prec_dev = pd.merge(df_prec_dev, df_rs, on= 'Symbol', how='left')
  #print(df_prec_dev.columns)
  df_prec_dev['Curr_PE'] = round(df_prec_dev['Close']/df_prec_dev['EPS'],1)
  df_prec_dev['Dev%_PE'] = round((df_prec_dev['Curr_PE'] - df_prec_dev['MedPE'])*100/df_prec_dev['MedPE'],2)
  df_prec_dev['Conviction'] = df_prec_dev['Conviction'] + '-' + df_prec_dev['CapType']
  return df_prec_dev

# function to arrange stock features
def arrange_features(df_stocks, common_cols, diff_cols):
  df_stocks_common = df_stocks[common_cols].drop_duplicates()
  df_stocks_diff = df_stocks[diff_cols]
  df_stocks_diff['Investment'] = df_stocks_diff['AvgCost'] * df_stocks_diff['Shares']
  df_stocks_diff = df_stocks_diff.groupby(['Symbol'])[['Shares', 'Investment']].aggregate(['sum']).reset_index()
  df_stocks_diff.columns = ['Symbol', 'Shares', 'Investment']
  df_stocks_diff['AvgCost'] = round(df_stocks_diff['Investment']/df_stocks_diff['Shares'],2)
  df_stocks = pd.merge(df_stocks_diff, df_stocks_common, on='Symbol')
  return df_stocks

# plot fact distribution across dimension
def plot_pie_chart(df, dimension, fact):
  # grouping the data by category and calculating the sum of fact for each type
  grouped_data = df.groupby(dimension)[fact].sum()

  # sorting the grouped data in descending order
  grouped_data = grouped_data.sort_values(ascending=False)

  # creating a pie chart
  grouped_data.plot.pie(autopct='%1.1f%%', startangle=90, figsize=(6, 6))

  # adding a title and displaying the plot
  plt.title(f'{dimension} {fact} Distribution')
  plt.ylabel('')  # To hide the y-label
  plt.show()

In [7]:
# function to get portfolio features

def get_portfolio_features(df_common_features):

  print_date_time()
  print('-------------------')

  #df_common_features["Target"] = df_common_features["Target"].fillna(df_common_features["Max"])
  df_common_features['NTT'] = np.where(df_common_features['Strategy']== 'NTT', df_common_features["Target"], df_common_features['Max'])
  df_common_features['LTT'] = np.where(df_common_features['Strategy']== 'BTT', df_common_features["Target"], df_common_features['Max'])
  df_common_features['BOL'] = df_common_features['Min']

  tmp_df = df_common_features[df_common_features['Symbol'].isin(mypf_df[mypf_df['InPortfolio'] != 'NA'].Symbol.values)]
  print('qualified stocks: '+str(len(tmp_df['Symbol'].unique())))
  tmp_df1 = tmp_df[tmp_df['LatestQtr'] == 1]
  print('with latest results: '+str(len(tmp_df1['Symbol'].unique())))
  tmp_df1 = tmp_df1[tmp_df1['StarStock'] == 1]
  print('still star stocks: '+str(len(tmp_df1['Symbol'].unique())))
  tmp_df['Investment'] = tmp_df['AvgCost'] * tmp_df['Shares']
  tmp_df['Current'] = round(tmp_df['Close'] * tmp_df['Shares'],0)
  tmp_df['Previous'] = tmp_df['Prev_Close'] * tmp_df['Shares']
  tmp_df['EstimatedST'] = tmp_df['NTT'] * tmp_df['Shares']
  tmp_df['EstimatedLT'] = tmp_df['LTT'] * tmp_df['Shares']
  tmp_df['Current P/L'] = round((tmp_df['Current'] - tmp_df['Investment']),0)
  tmp_df['Today P/L%'] = round((tmp_df['Current'] - tmp_df['Previous'])*100/tmp_df['Previous'],2)
  tmp_df['Current P/L%'] = round((tmp_df['Current'] - tmp_df['Investment'])*100/tmp_df['Investment'],2)
  tmp_df['EstimatedST P/L%'] = round((tmp_df['EstimatedST'] - tmp_df['Investment'])*100/tmp_df['Investment'],2)
  tmp_df['EstimatedLT P/L%'] = round((tmp_df['EstimatedLT'] - tmp_df['Investment'])*100/tmp_df['Investment'],2)
  tmp_df['NTT%'] = round((tmp_df['NTT'] - tmp_df['Close'])*100/tmp_df['Close'],2)
  tmp_df['LTT%'] = round((tmp_df['LTT'] - tmp_df['Close'])*100/tmp_df['Close'],2)
  tmp_df['Gained%'] = round((tmp_df['Close'] - tmp_df['BOL'])*100/tmp_df['BOL'],2)
  investment = round(sum(tmp_df['AvgCost']*tmp_df['Shares']),0)
  current = round(sum(tmp_df['Close']*tmp_df['Shares']),0)
  tmp_df['InitAlloc%'] = round(tmp_df['Investment']*100/investment,2)
  tmp_df['CurrAlloc%'] = round(tmp_df['Current']*100/current,2)
  tmp_df['FTT'] = tmp_df['LTT']
  tmp_df.loc[tmp_df['Strategy'] == 'NTT', 'FTT'] = tmp_df['NTT']
  tmp_df['FTT%'] = tmp_df['LTT%']
  tmp_df.loc[tmp_df['Strategy'] == 'NTT', 'FTT%'] = tmp_df['NTT%']
  tmp_df['FTT Amt'] = round(tmp_df['FTT%'] * tmp_df['Current']/100,0)
  tmp_df['OTT%'] = round((tmp_df['FTT'] - tmp_df['AvgCost'])*100/tmp_df['AvgCost'],2)
  tmp_df['RRR Ind'] = round(tmp_df['Current P/L']/tmp_df['FTT Amt'],2)
  tmp_df['Risk Ind'] = round(tmp_df['Current P/L%']*tmp_df['CurrAlloc%'],0)

  return tmp_df

# function to print portfolio features
def print_portfolio_stats(df_portfolio_features, myinvmt_df):
  from pyxirr import xirr

  total_booked_amt, reserve_amt, cy_booked_amt, py_booked_amt = get_amt()

  dates = myinvmt_df['Date'].values
  dates = np.append(dates, datetime.date.today().strftime('%d-%b-%y'))
  investment = myinvmt_df['Investment'].values
  dates= pd.to_datetime(dates)

  current = round(sum(df_portfolio_features['Close']*df_portfolio_features['Shares']),0) + reserve_amt
  investment_xirr = np.append(investment, current)
  cagr = round(xirr(pd.DataFrame({"dates": dates, "amounts": investment_xirr}))*100,2)

  investment = -sum(investment)
  invested = round(sum(df_portfolio_features['AvgCost']*df_portfolio_features['Shares']),0) + reserve_amt
  previous = round(sum(df_portfolio_features['Prev_Close']*df_portfolio_features['Shares']),0) + reserve_amt
  cy_invested = investment + py_booked_amt

  today_pnl_amount = current-previous
  today_pnl_percentage = round((current-previous)*100/previous,2)

  curr_pnl_amount = current-invested
  curr_pnl_percentage = round((curr_pnl_amount)*100/(cy_invested),2)

  cy_pnl_amount = cy_booked_amt + curr_pnl_amount
  cy_pnl_percentage = round((cy_pnl_amount)*100/cy_invested,2)

  overall_pnl_amount = total_booked_amt + curr_pnl_amount
  overall_pnl_percentage = round((overall_pnl_amount)*100/investment,2)

  estimate_st = round(sum(df_portfolio_features['FTT']*df_portfolio_features['Shares']),0)  + reserve_amt
  est_st_pnl_amount = estimate_st-current
  est_st_pnl_percentage = round((est_st_pnl_amount)*100/current,2)

  estimate_lt = round(sum(df_portfolio_features['LTT']*df_portfolio_features['Shares']),0)  + reserve_amt
  est_lt_pnl_amount = estimate_lt-current
  est_lt_pnl_percentage = round((est_lt_pnl_amount)*100/current,2)

  total_profit = round(sum(df_portfolio_features[df_portfolio_features['Current P/L%'] > 0]['Current']) - sum(df_portfolio_features[df_portfolio_features['Current P/L%'] > 0]['Investment']),0)
  total_loss = round(sum(df_portfolio_features[df_portfolio_features['Current P/L%'] < 0]['Current']) - sum(df_portfolio_features[df_portfolio_features['Current P/L%'] < 0]['Investment']),0)

  cy_booked_percentage = round((cy_booked_amt)*100/current,2)
  py_booked_percentage = round((py_booked_amt)*100/investment,2)
  total_booked_percentage = round((total_booked_amt)*100/investment,2)

  print('-------------------')
  print('Initial Investment: ', format_amt(investment))
  print('CY Investment: ', format_amt(cy_invested))
  print('Reserve: ', format_amt(reserve_amt))
  print('Current: ',  format_amt(current))
  print('-------------------')
  print('Today PnL: '+ '{} ({}%)'.format(format_amt(today_pnl_amount), today_pnl_percentage))
  print('Current PnL: '+ '{} ({}%)'.format(format_amt(curr_pnl_amount), curr_pnl_percentage))
  print('CY Booked + Current PnL: '+ '{} ({}%)'.format(format_amt(cy_pnl_amount), cy_pnl_percentage))
  print('-------------------')
  print('Total profit: ', format_amt(total_profit))
  print('Total loss: ', format_amt(total_loss))
  print('-------------------')
  print('Total Booked + Current PnL: '+ '{} ({}%)'.format(format_amt(overall_pnl_amount), overall_pnl_percentage))
  print('Total Booked PnL: '+ '{} ({}%)'.format(format_amt(total_booked_amt), total_booked_percentage))
  print('Curr Year Booked PnL: '+ '{} ({}%)'.format(format_amt(cy_booked_amt), cy_booked_percentage))
  print('Prev Year Booked PnL: '+ '{} ({}%)'.format(format_amt(py_booked_amt), py_booked_percentage))
  print('===================')
  print('Est FTT: ',  format_amt(estimate_st))
  print('Est FTT PnL: '+ '{} ({}%)'.format(format_amt(est_st_pnl_amount), est_st_pnl_percentage))

  print('===================')
  print('Deployed: ', format_amt(investment))

  print('Current: ', format_amt(current))

  print('CAGR/XIRR %: '+'{}%'.format(cagr))

In [8]:
# get start and end date
start_date, end_date = get_start_end_date()

# get portfolio and prospects data
mypfs_df = get_mypfs_df()
mypps_df = get_mypps_df()
myinvmt_df = get_myinvmt_df()

# merge above datasets
mypf_df = pd.merge(mypfs_df, mypps_df, on="Symbol")

# seggregate dm and sv portfolio
dm_pf = mypf_df[mypf_df['InPortfolio'] == 'DM']
sv_pf = mypf_df[mypf_df['InPortfolio'] == 'SV']

# build portfolio stock dataframe
dm_stocks = get_stock_ids(dm_pf)
sv_stocks = get_stock_ids(sv_pf)
df_stocks = pd.concat([dm_pf,sv_pf], ignore_index = True)

# arrange common and diff stock features
common_cols = ['Symbol', 'Target', 'Criteria', 'Strategy', 'CumlRnk', 'LatestQtr', 'StarStock', 'Conviction', 'Category', 'InFolio', 'XIRR', 'MBQ']
diff_cols = ['Symbol', 'AvgCost', 'Shares']
df_stocks = arrange_features(df_stocks, common_cols, diff_cols)

# get common features
stock_ids = df_stocks['Symbol'].values
df_common_features = get_common_features(stock_ids, df_stocks)

df_common_features.reset_index(drop=True, inplace=True)
df_common_features.drop(['Date'], axis=1, inplace=True)
# get and print portfolio features
df_portfolio_features = get_portfolio_features(df_common_features)

print_portfolio_stats(df_portfolio_features, myinvmt_df)

df = df_portfolio_features
#plot_pie_chart(df, 'CapType', 'Current')
list_ox40n = list(df[df['MBQ'].str.contains('OX40N', na=False)]['Symbol'].values)

Run date time (IST): 2026-08-20 08:25:27
-------------------
qualified stocks: 87
with latest results: 30
still star stocks: 19
-------------------
Initial Investment:  1.46 C
CY Investment:  1.89 C
Reserve:  3.69 L
Current:  1.58 C
-------------------
Today PnL: -68.71 K (-0.43%)
Current PnL: -35.25 L (-18.66%)
CY Booked + Current PnL: -30.19 L (-15.98%)
-------------------
Total profit:  3.46 L
Total loss:  -38.71 L
-------------------
Total Booked + Current PnL: 12.68 L (8.68%)
Total Booked PnL: 47.93 L (32.82%)
Curr Year Booked PnL: 5.06 L (3.21%)
Prev Year Booked PnL: 42.87 L (29.35%)
===================
Est FTT:  2.67 C
Est FTT PnL: 1.09 C (69.38%)
===================
Deployed:  1.46 C
Current:  1.58 C
CAGR/XIRR %: 3.47%

In [9]:
# top 5 near their targets
cols = ['Symbol', 'Today P/L%', 'Current P/L%', 'FTT%', 'OTT%', 'FTT Amt', 'Current P/L', 'Current', 'FTT', 'Dev%_PE', 'RSI_14','Conviction', 'Spread%',  'CumlRnk', 'RRR Ind', 'CurrAlloc%', 'Gained%', 'Criteria', 'Strategy', 'Category']
df_tmp = df_portfolio_features[~df_portfolio_features['Symbol'].isin(['ENRIN','BLUSPRING','DIGITIDE'])]
df_tmp = df_tmp.sort_values(by = 'FTT Amt', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
66,SIEMENS,-1.47,4.76,5.80,10.83,11307.0,8850.0,194945.0,4125.00,-15.10,57.0,H-LC,13.83,51.0,0.78,1.27,37.54,AR,NTT,ELECTRICAL
78,UNITDSPR,-1.56,11.72,8.09,20.77,21163.0,27451.0,261595.0,1644.00,-4.79,60.0,X-MC,10.43,64.0,1.30,1.70,25.75,X40N,NTT,BREWERIES
77,TTKPRESTIG,0.42,-22.71,29.50,0.09,22978.0,-22884.0,77893.0,770.00,-6.01,42.0,M-SC,10.22,250.0,-1.00,0.51,40.20,OX40N,NTT,DURABLES
52,M&M,-0.19,7.84,10.19,18.82,26447.0,18859.0,259540.0,3762.88,-6.96,58.0,X-LC,4.86,25.0,0.71,1.69,17.73,X40N,ATH,AUTO
27,GLAXO,5.39,21.73,11.47,35.69,27825.0,43308.0,242592.0,3380.16,-8.73,86.0,X-MC,9.83,56.0,1.56,1.58,44.18,X40,ATH,PHARMA

In [10]:
# top 5 today
df_tmp = df_portfolio_features.sort_values(by = 'Today P/L%', ascending=False)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
27,GLAXO,5.39,21.73,11.47,35.69,27825.0,43308.0,242592.0,3380.16,-8.73,86.0,X-MC,9.83,56.0,1.56,1.58,44.18,X40,ATH,PHARMA
3,ALKYLAMINE,3.25,-16.69,131.12,92.54,110288.0,-16851.0,84112.0,4520.85,NaN,60.0,NaN,14.38,142.0,-0.15,0.55,59.72,SR,ATH,CHEMICALS
22,DIXON,2.20,5.36,30.91,37.92,84934.0,13980.0,274778.0,18931.72,-59.94,63.0,X-MC,15.28,54.0,0.16,1.78,49.51,X40N,ATH,IT
33,HCLTECH,2.06,-11.39,39.90,23.97,109419.0,-35252.0,274234.0,1853.42,-13.84,56.0,X-LC,11.31,8.0,-0.32,1.78,29.41,X40,ATH,IT
0,5PAISA,1.97,-26.07,52.72,12.90,85160.0,-56963.0,161533.0,593.00,3.70,60.0,H-SC,11.50,170.0,-0.67,1.05,55.88,OX40N,NTT,FINANCE

In [11]:
# bottom 5 today
df_tmp = df_portfolio_features.sort_values(by = 'Today P/L%', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
55,PAGEIND,-2.50,-5.52,40.61,32.85,102977.0,-14804.0,253575.0,50936.07,-29.75,32.0,X-MC,8.63,55.0,-0.14,1.65,21.09,X40,ATH,APPARELS
83,VOLTAS,-2.39,-4.32,51.76,45.20,94954.0,-8292.0,183450.0,1856.00,31.81,35.0,X-MC,4.54,79.0,-0.09,1.19,0.54,XY25,NTT,AC
49,KANSAINER,-2.31,-32.90,69.11,13.47,125051.0,-88722.0,180945.0,340.00,-29.72,45.0,H-SC,3.23,162.0,-0.71,1.17,27.89,XY24,NTT,PAINTS
30,HAPPSTMNDS,-2.27,-48.77,257.34,83.08,168980.0,-62501.0,65664.0,1466.54,NaN,59.0,NaN,8.49,152.0,-0.37,0.43,22.99,AR,ATH,IT
70,SYMPHONY,-2.21,-53.92,116.93,-0.03,92222.0,-92272.0,78869.0,1306.00,NaN,23.0,NaN,16.58,205.0,-1.00,0.51,0.00,OX40N,NTT,DURABLES

In [12]:
# top 5 to exit based on CumlRnk
df_tmp = df_portfolio_features[~df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])]
df_tmp = df_tmp[(df_tmp['Current P/L%'] > -1) & (df_tmp['Current P/L%'] < 1)].sort_values(by = 'CumlRnk', ascending=False)
df_tmp[cols].head()

Empty DataFrame
Columns: [Symbol, Today P/L%, Current P/L%, FTT%, OTT%, FTT Amt, Current P/L, Current, FTT, Dev%_PE, RSI_14, Conviction, Spread%, CumlRnk, RRR Ind, CurrAlloc%, Gained%, Criteria, Strategy, Category]
Index: []

In [13]:
# OX40N stocks to exit
df_tmp = df_portfolio_features[(df_portfolio_features['Symbol'].isin(list_ox40n))].sort_values(by = 'Current P/L%', ascending=False)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
25,FINCABLES,-1.18,66.39,24.96,107.91,61317.0,98018.0,245662.0,1641.55,21.20,73.0,M-SC,20.46,220.0,1.60,1.60,84.82,OX40N,ATH,CABLES
67,SIS,-0.68,-5.01,27.66,21.26,29172.0,-5564.0,105468.0,528.00,102.74,37.0,H-SC,21.55,168.0,-0.19,0.68,56.82,OX40N,NTT,MISC
43,INDIGOPNTS,-0.88,-18.25,22.35,0.02,31893.0,-31860.0,142699.0,1408.00,-22.11,64.0,M-SC,6.98,222.0,-1.00,0.93,61.90,OX40N,NTT,PAINTS
77,TTKPRESTIG,0.42,-22.71,29.50,0.09,22978.0,-22884.0,77893.0,770.00,-6.01,42.0,M-SC,10.22,250.0,-1.00,0.51,40.20,OX40N,NTT,DURABLES
12,BOSCH-HCIL,1.76,-22.77,29.47,-0.01,29089.0,-29099.0,98706.0,2282.00,773.36,78.0,M-SC,7.56,231.0,-1.00,0.64,68.01,OX40N,BTT,AC

In [14]:
# top 5 to book for rotation
df_tmp = df_portfolio_features[(df_portfolio_features['Current P/L%'] > 20) ].sort_values(by = 'CumlRnk', ascending=False)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
25,FINCABLES,-1.18,66.39,24.96,107.91,61317.0,98018.0,245662.0,1641.55,21.20,73.0,M-SC,20.46,220.0,1.60,1.60,84.82,OX40N,ATH,CABLES
27,GLAXO,5.39,21.73,11.47,35.69,27825.0,43308.0,242592.0,3380.16,-8.73,86.0,X-MC,9.83,56.0,1.56,1.58,44.18,X40,ATH,PHARMA

In [15]:
# top 5 to monitor for exit
df_tmp = df_portfolio_features[~df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])]
df_tmp = df_tmp[(df_tmp['Current P/L%'] > 0) ].sort_values(by = 'Dev%_PE', ascending=False)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
25,FINCABLES,-1.18,66.39,24.96,107.91,61317.0,98018.0,245662.0,1641.55,21.20,73.0,M-SC,20.46,220.0,1.60,1.60,84.82,OX40N,ATH,CABLES
68,STARHEALTH,-0.06,12.99,30.33,47.26,96341.0,36519.0,317642.0,761.00,-0.37,50.0,H-SC,16.24,173.0,0.38,2.06,37.34,XY24,NTT,INSURANCE

In [16]:
# top 5 to book for rotation from weak conviction
df_tmp = df_portfolio_features[~df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])]
df_tmp = df_tmp[~df_tmp['Criteria'].isin(['XY25','XY24','X40', 'X40N'])].sort_values(by = 'RRR Ind', ascending=False)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
25,FINCABLES,-1.18,66.39,24.96,107.91,61317.0,98018.0,245662.0,1641.55,21.20,73.0,M-SC,20.46,220.0,1.60,1.60,84.82,OX40N,ATH,CABLES
3,ALKYLAMINE,3.25,-16.69,131.12,92.54,110288.0,-16851.0,84112.0,4520.85,NaN,60.0,NaN,14.38,142.0,-0.15,0.55,59.72,SR,ATH,CHEMICALS
67,SIS,-0.68,-5.01,27.66,21.26,29172.0,-5564.0,105468.0,528.00,102.74,37.0,H-SC,21.55,168.0,-0.19,0.68,56.82,OX40N,NTT,MISC
42,INDIAMART,-0.96,-24.67,166.70,100.92,154888.0,-30422.0,92914.0,4675.60,NaN,37.0,NaN,13.63,140.0,-0.20,0.60,0.58,AR,ATH,MISC
71,TANLA,-0.96,-35.45,236.54,117.25,413441.0,-95974.0,174787.0,1922.32,NaN,46.0,NaN,15.27,147.0,-0.23,1.13,53.03,AR,ATH,IT

In [17]:
# top 5 to accumulate based on lowest RSI_14
df_tmp = df_portfolio_features[df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])].sort_values(by = 'RSI_14', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
19,COLPAL,-1.23,-28.63,95.97,39.86,180385.0,-75405.0,187960.0,3683.41,-13.63,28.0,X-MC,1.68,62.0,-0.42,1.22,6.32,XY25,ATH,FMCG
47,ITC,-1.09,-26.33,69.26,24.70,202715.0,-104591.0,292687.0,452.00,-31.16,29.0,X-LC,10.68,1.0,-0.52,1.90,0.00,X40,NTT,FMCG
28,GODREJCP,-0.11,-15.40,57.09,32.90,120523.0,-38427.0,211110.0,1460.97,-17.06,31.0,X-MC,6.69,32.0,-0.32,1.37,2.76,X40N,ATH,FMCG
56,PGHH,-0.57,-37.68,111.82,32.01,148801.0,-80448.0,133072.0,17616.87,-54.25,31.0,X-SC,19.64,57.0,-0.54,0.86,0.00,X40,ATH,FMCG
34,HDFCBANK,-0.41,-12.06,49.03,31.05,126380.0,-35360.0,257760.0,1073.00,-29.01,32.0,X-LC,12.88,26.0,-0.28,1.67,0.05,X40,BTT,BANKS

In [18]:
# top 5 to accumulate based on Spread and CumlRnk
df_tmp = df_portfolio_features[df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])]
df_tmp = df_tmp[(df_tmp['CumlRnk'] < 100)].sort_values(by = 'Spread%', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
19,COLPAL,-1.23,-28.63,95.97,39.86,180385.0,-75405.0,187960.0,3683.41,-13.63,28.0,X-MC,1.68,62.0,-0.42,1.22,6.32,XY25,ATH,FMCG
50,KOTAKBANK,0.67,2.57,15.94,18.92,39190.0,6156.0,245858.0,452.46,-13.30,50.0,X-LC,2.31,12.0,0.16,1.60,10.62,X40,ATH,BANKS
23,DMART,-0.40,-3.35,35.98,31.42,108422.0,-10450.0,301340.0,5391.45,-18.91,45.0,X-LC,2.34,14.0,-0.10,1.96,8.74,X40N,ATH,FMCG
26,GILLETTE,-0.69,-11.17,46.04,29.72,103832.0,-28371.0,225525.0,10978.86,-35.84,37.0,X-SC,3.54,83.0,-0.27,1.46,3.64,X40,ATH,FMCG
17,CIPLA,-0.03,9.17,15.17,25.73,39946.0,22126.0,263322.0,1648.14,22.11,44.0,X-LC,4.34,18.0,0.55,1.71,21.14,X40N,ATH,PHARMA

In [19]:
# top 5 to accumulate based on lowest Gained%
df_tmp = df_portfolio_features[df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])].sort_values(by = 'Gained%', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
20,DABUR,-0.93,-21.84,83.86,43.70,162587.0,-54189.0,193879.0,735.00,-32.67,32.0,X-MC,10.16,70.0,-0.33,1.26,0.00,XY24,BTT,FMCG
36,HINDUNILVR,-0.70,-15.93,44.60,21.56,126173.0,-53619.0,282898.0,2922.00,-42.16,38.0,X-LC,6.48,9.0,-0.42,1.84,0.00,XY25,NTT,FMCG
47,ITC,-1.09,-26.33,69.26,24.70,202715.0,-104591.0,292687.0,452.00,-31.16,29.0,X-LC,10.68,1.0,-0.52,1.90,0.00,X40,NTT,FMCG
56,PGHH,-0.57,-37.68,111.82,32.01,148801.0,-80448.0,133072.0,17616.87,-54.25,31.0,X-SC,19.64,57.0,-0.54,0.86,0.00,X40,ATH,FMCG
34,HDFCBANK,-0.41,-12.06,49.03,31.05,126380.0,-35360.0,257760.0,1073.00,-29.01,32.0,X-LC,12.88,26.0,-0.28,1.67,0.05,X40,BTT,BANKS

In [20]:
# top 5 to accumulate based on lowest CurrAlloc%
df_tmp = df_portfolio_features[df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])].sort_values(by = 'CurrAlloc%', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
56,PGHH,-0.57,-37.68,111.82,32.01,148801.0,-80448.0,133072.0,17616.87,-54.25,31.0,X-SC,19.64,57.0,-0.54,0.86,0.00,X40,ATH,FMCG
2,ACC,-1.16,-42.32,203.10,74.81,314082.0,-113484.0,154644.0,3906.00,-42.69,34.0,X-SC,11.71,85.0,-0.36,1.00,3.31,XY24,BTT,CEMENT
1,ABBOTINDIA,-1.21,-10.83,29.38,15.37,46855.0,-19375.0,159480.0,34390.26,-27.37,40.0,X-MC,4.48,58.0,-0.41,1.04,8.03,X40,ATH,PHARMA
40,ICICIPRULI,0.26,-17.34,57.61,30.28,93810.0,-34168.0,162837.0,787.27,-47.05,46.0,X-MC,12.48,78.0,-0.36,1.06,8.49,X40,ATH,INSURANCE
39,ICICIGI,-0.15,-13.99,38.22,18.89,65785.0,-27986.0,172123.0,2244.41,-14.33,40.0,X-MC,10.52,66.0,-0.43,1.12,2.54,X40,ATH,INSURANCE

In [21]:
# top 5 to accumulate based on CumlRnk
df_tmp = df_portfolio_features.sort_values(by = 'CumlRnk', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
47,ITC,-1.09,-26.33,69.26,24.70,202715.0,-104591.0,292687.0,452.00,-31.16,29.0,X-LC,10.68,1.0,-0.52,1.90,0.00,X40,NTT,FMCG
73,TCS,0.39,-32.80,84.83,24.20,264079.0,-151969.0,311304.0,4230.71,-44.31,47.0,X-LC,14.29,2.0,-0.58,2.02,16.09,X40,ATH,IT
45,INFY,0.43,-20.28,76.10,40.38,228381.0,-76364.0,300106.0,1972.00,-41.25,47.0,X-LC,15.91,3.0,-0.33,1.95,13.65,X40,NTT,IT
75,TMPV,-0.46,-23.56,86.74,42.75,275909.0,-98020.0,318087.0,600.00,-84.91,35.0,X-LC,4.53,4.0,-0.36,2.07,9.38,XY24,NTT,AUTO
33,HCLTECH,2.06,-11.39,39.90,23.97,109419.0,-35252.0,274234.0,1853.42,-13.84,56.0,X-LC,11.31,8.0,-0.32,1.78,29.41,X40,ATH,IT

In [22]:
# top 5 for average up
df_tmp = df_portfolio_features[(df_portfolio_features['Dev%_200'] > 5)].sort_values(by = 'CurrAlloc%', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
44,INDUSINDBK,0.44,-25.06,77.34,32.89,44745.0,-19352.0,57855.0,1800.00,325.93,53.0,L-MC,13.40,258.0,-0.43,0.38,42.64,XR,NTT,BANKS
60,RELAXO,-1.85,-50.27,206.29,52.31,148906.0,-72977.0,72183.0,1176.00,NaN,42.0,NaN,12.84,92.0,-0.49,0.47,61.39,X40N,NTT,FOOTWEAR
3,ALKYLAMINE,3.25,-16.69,131.12,92.54,110288.0,-16851.0,84112.0,4520.85,NaN,60.0,NaN,14.38,142.0,-0.15,0.55,59.72,SR,ATH,CHEMICALS
12,BOSCH-HCIL,1.76,-22.77,29.47,-0.01,29089.0,-29099.0,98706.0,2282.00,773.36,78.0,M-SC,7.56,231.0,-1.00,0.64,68.01,OX40N,BTT,AC
81,VALIANTORG,0.36,-35.70,170.85,74.15,179727.0,-58409.0,105196.0,838.00,NaN,58.0,NaN,7.07,145.0,-0.32,0.68,56.55,XR,NTT,CHEMICALS

In [23]:
# top 5 RSP
df_tmp = df_portfolio_features.sort_values(by = 'RSP', ascending=False)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
12,BOSCH-HCIL,1.76,-22.77,29.47,-0.01,29089.0,-29099.0,98706.0,2282.00,773.36,78.0,M-SC,7.56,231.0,-1.00,0.64,68.01,OX40N,BTT,AC
25,FINCABLES,-1.18,66.39,24.96,107.91,61317.0,98018.0,245662.0,1641.55,21.20,73.0,M-SC,20.46,220.0,1.60,1.60,84.82,OX40N,ATH,CABLES
27,GLAXO,5.39,21.73,11.47,35.69,27825.0,43308.0,242592.0,3380.16,-8.73,86.0,X-MC,9.83,56.0,1.56,1.58,44.18,X40,ATH,PHARMA
38,HYUNDAI,-0.53,12.47,27.97,43.94,79067.0,31353.0,282685.0,2782.73,16.55,60.0,X-LC,5.28,29.0,0.40,1.84,29.79,X40N,ATH,AUTO
30,HAPPSTMNDS,-2.27,-48.77,257.34,83.08,168980.0,-62501.0,65664.0,1466.54,NaN,59.0,NaN,8.49,152.0,-0.37,0.43,22.99,AR,ATH,IT

In [24]:
# Top N allocation
df_tmp = df_portfolio_features.sort_values(by = 'CurrAlloc%', ascending=False)
top_n_values = [10, 25, 50]

sum_df = pd.DataFrame({
    'Top_N': top_n_values,
    'Sum_Alloc%': [df_tmp['CurrAlloc%'].head(n).sum() for n in top_n_values]
})

sum_df

   Top_N  Sum_Alloc%
0     10       19.68
1     25       45.06
2     50       77.62

In [25]:
# market-cap-wise allocation
df_tmp = df_portfolio_features[cols]
df_tmp.groupby(df_tmp['Conviction'].str[-2:])['CurrAlloc%'].sum().sort_values(ascending=False)

Conviction
LC    38.01
MC    22.35
SC    21.58
Name: CurrAlloc%, dtype: float64

In [26]:
# criteria-wise allocation
df_portfolio_features.groupby('Criteria')['CurrAlloc%'].sum().sort_values(ascending=False)

Criteria
X40      26.75
XY24     23.93
X40N     18.67
XR        9.09
OX40N     7.37
XY25      7.19
AR        6.12
SR        0.88
Name: CurrAlloc%, dtype: float64

In [27]:
# conviction-wise allocation
df_portfolio_features.groupby('Conviction')['CurrAlloc%'].sum().sort_values(ascending=False)

Conviction
X-LC    34.33
X-MC    19.74
H-SC     8.47
X-SC     7.62
M-SC     5.49
H-LC     2.87
M-MC     1.20
H-MC     1.03
M-LC     0.81
L-MC     0.38
Name: CurrAlloc%, dtype: float64

In [28]:
# sector-wise stats
df_tmp = df_portfolio_features.groupby('Category')[['CurrAlloc%', 'Current', 'Current P/L', 'FTT Amt']].sum().sort_values(by=['Current', 'Current P/L'], ascending=False)
df_tmp['Current P/L%'] = round(df_tmp['Current P/L'] * 100 / df_tmp['Current'], 2)
df_tmp['FTT%'] = round(df_tmp['FTT Amt'] * 100 / df_tmp['Current'], 2)
cols = ['CurrAlloc%', 'Current P/L%', 'FTT%']
df_tmp[cols].sort_values(by=['CurrAlloc%'], ascending=False)

               CurrAlloc%  Current P/L%    FTT%
Category
FMCG                15.37        -25.94   71.22
IT                  11.19        -38.31  106.91
FINANCE             10.73        -16.74   67.03
AUTO                 8.28         -6.24   44.29
BANKS                6.12        -13.22   62.05
MISC                 5.96        -34.32   88.34
PHARMA               5.93          9.11   16.68
INSURANCE            5.74         -5.18   42.37
PAINTS               5.51        -16.06   35.86
ELECTRICAL           4.20         -9.23   43.43
AC                   1.83        -13.25   43.96
REFINERIES           1.74        -11.45   48.89
BREWERIES            1.70         10.49    8.09
FOOTWEAR             1.66        -72.97  142.32
APPARELS             1.65         -5.84   40.61
CABLES               1.60         39.90   24.96
DURABLES             1.47        -71.05  112.67
TRAVEL               1.42       -103.97  206.09
CERAMICS             1.34        -47.87   92.80
ENGINEERING          1.23        -27.70   86.11
CHEMICALS            1.23        -39.76  153.20
CEMENT               1.00        -73.38  203.10
JEWELLERY            0.96       -116.91  192.27
ENTERTAINMENT        0.69        -80.69  188.45
HEALTHCARE           0.69        -71.18  114.15
TEXTILES             0.39        -52.51   96.00
HOTELS               0.37        -99.53  169.91

In [29]:
# money to be made criteria-wise
df_portfolio_features.groupby('Criteria')['FTT Amt'].agg(['sum', 'count']).sort_values(by='sum', ascending=False)

                sum  count
Criteria
XY24      3640210.0     19
X40       2104286.0     18
XR        1395806.0     13
X40N      1207652.0     12
AR        1062395.0      8
OX40N      656886.0     10
XY25       592207.0      5
SR         281107.0      2

In [30]:
# money to be made conviction-wise
df_portfolio_features.groupby('Conviction')['FTT Amt'].agg(['sum', 'count']).sort_values(by='sum', ascending=False)

                  sum  count
Conviction
X-LC        2442930.0     19
X-MC        1463850.0     14
X-SC        1103772.0      6
H-SC         843315.0      8
M-SC         320234.0      6
H-MC         254484.0      1
M-LC         167115.0      1
M-MC          59942.0      1
H-LC          48758.0      2
L-MC          44745.0      1

In [31]:
# money to be made criteria and conviction-wise
df_portfolio_features.groupby(['Conviction', 'Criteria'])['FTT Amt'].agg(['sum', 'count']).sort_values(by='sum', ascending=False)

                           sum  count
Conviction Criteria
X-LC       X40       1239515.0      9
X-SC       XY24       677606.0      2
H-SC       XY24       530672.0      3
X-MC       X40        498036.0      6
           X40N       461950.0      4
X-LC       XY24       461473.0      2
           X40N       423263.0      5
X-MC       XY25       275339.0      2
X-LC       XY25       256926.0      2
H-MC       XY24       254484.0      1
X-SC       X40        252633.0      2
X-MC       XY24       228525.0      2
H-SC       OX40N      218856.0      3
X-SC       X40N       173533.0      2
M-LC       XR         167115.0      1
M-SC       OX40N      145277.0      4
           XY24       116887.0      1
H-SC       XR          93787.0      2
X-LC       XR          61753.0      1
M-MC       XY25        59942.0      1
M-SC       XR          58070.0      1
H-LC       AR          48758.0      2
L-MC       XR          44745.0      1

In [32]:
# notebook execution time

end_time = time.time()
execution_time = round(end_time - start_time, 0)
print(f"Notebook execution time: {execution_time} seconds")

Notebook execution time: 39.0 seconds