<a href="https://colab.research.google.com/github/ankit-rathi/Quantvesting_v2/blob/main/myStocks_Portfolio_Analysis.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
'''
!pip install pandas==2.2.2 -qq
!pip install pyxirr -qq
!pip install ta -qq
!pip install yfinance==0.2.59 -qq
'''

'\n!pip install pandas==2.2.2 -qq\n!pip install pyxirr -qq\n!pip install ta -qq\n!pip install yfinance==0.2.59 -qq\n'

In [2]:
# import libraries

import numpy as np
import pandas as pd
import datetime
import warnings
warnings.filterwarnings('ignore')
import yfinance as yfin
import ta
import matplotlib.pyplot as plt
import requests

In [3]:
# notebook start time
import time
import datetime
import pytz

start_time = time.time()

# function to print date timestamp
def print_date_time():
  tz_NY = pytz.timezone('Asia/Kolkata')
  datetime_NY = datetime.datetime.now(tz_NY)
  print("Run date time (IST):", datetime_NY.strftime("%Y-%m-%d %H:%M:%S"))

In [4]:
# function to get booked and reserved amount
def get_amt():
  # fetch the JSON data from the URL
  url = "https://raw.githubusercontent.com/ankit-rathi/Tradevesting_v1/main/data/myPortfolioAmts.json"
  response = requests.get(url)
  pf_amts = response.json()  # parse the JSON data

  # extract values from the JSON
  py_booked_amt_dm = pf_amts["py_booked_amt_dm"]
  py_booked_amt_sv = pf_amts["py_booked_amt_sv"]
  cy_booked_amt_dm = pf_amts["cy_booked_amt_dm"]
  cy_booked_amt_sv = pf_amts["cy_booked_amt_sv"]
  reserve_amt_dm = pf_amts["reserve_amt_dm"]
  reserve_amt_sv = pf_amts["reserve_amt_sv"]

  # perform calculations
  py_booked_amt = py_booked_amt_dm + py_booked_amt_sv
  cy_booked_amt = cy_booked_amt_dm + cy_booked_amt_sv
  reserve_amt = reserve_amt_dm + reserve_amt_sv
  total_booked_amt = py_booked_amt + cy_booked_amt

  return total_booked_amt, reserve_amt, cy_booked_amt, py_booked_amt

gen_output = 0

In [5]:
# function to format the amount
def format_amt(number):
    abs_number = abs(number)

    if abs_number >= 1_00_00_000:  # Crores
        formatted_amt = f"{number / 1_00_00_000:.2f} C"
    elif abs_number >= 1_00_000:  # Lakhs
        formatted_amt = f"{number / 1_00_000:.2f} L"
    elif abs_number >= 1_000:  # Thousands
        formatted_amt = f"{number / 1_000:.2f} K"
    else:
        formatted_amt = f"{number:.2f}"

    return formatted_amt

# function to set start and end date
def get_start_end_date():
  start_date = (datetime.date.today() + datetime.timedelta(days=-365)).strftime('%Y-%m-%d')
  end_date = (datetime.date.today() + datetime.timedelta(days=1)).strftime('%Y-%m-%d')
  return start_date, end_date

# function to fetch my portfolio csv
def get_mypfs_df():
  mypfs_df = pd.read_csv('https://raw.githubusercontent.com/ankit-rathi/Tradevesting_v1/main/data/myPortfolioStocks.csv')
  return mypfs_df

# function to fetch my prospects csv
def get_mypps_df():
  mypps_df = pd.read_csv('https://raw.githubusercontent.com/ankit-rathi/Tradevesting_v1/main/data/myProspectsScrips.csv')
  return mypps_df

# function to fetch screener data
def get_myscreen_df():
  myscreen_df = pd.read_csv('https://raw.githubusercontent.com/ankit-rathi/Tradevesting_v1/main/data/myScreenerDB.csv')
  return myscreen_df

# function to fetch momentum data
def get_myinvmt_df():
  myinvmt_df = pd.read_csv('https://raw.githubusercontent.com/ankit-rathi/Tradevesting_v1/main/data/myInvestments.csv')
  return myinvmt_df

# function to get the stock ids
def get_stock_ids(df_pf):
  stock_n100 = df_pf['Symbol'].unique()

  exclude = ['CADILAHC','MMTC', 'MASFIN']

  stock_ids = df_pf[~df_pf['Symbol'].isin(exclude) ]['Symbol'].unique()

  #mypf = mypf[mypf.Forecast.notnull()]
  #stock_ids = mypf['Symbol'].unique()

  #stock_ids.sort()
  return stock_ids

# get features from screener data
def get_screener_features():
  myscreen_df = get_myscreen_df()
  cols = ['Symbol', 'EPS', 'MedPE', 'ROCE%', 'ROE%', 'CapType']
  return myscreen_df[cols]

# get relative strength
def get_relative_strength(stock_list):

    # Dictionary to store stock tickers and their corresponding percentage price change
    stock_changes = {}

    # Loop through each stock and fetch its price data
    for stock in stock_list:
        try:
            # Download the stock data for the given date range
            stock_data = yfin.Ticker(stock + '.NS').history(period='1mo', interval='1d')[map(str.title, ['open', 'close', 'low', 'high', 'volume'])]

            # Calculate the percentage change for the stock
            if len(stock_data) > 0:
                start_price = stock_data['Close'].iloc[0]
                end_price = stock_data['Close'].iloc[-1]
                percent_change = round(((end_price - start_price) / start_price) * 100, 2)
                stock_changes[stock] = percent_change
            else:
                stock_changes[stock] = np.nan  # If no data is available, set to NaN

        except Exception as e:
            print(f"Error fetching data for {stock}: {e}")
            stock_changes[stock] = np.nan

    # Create a DataFrame with stock tickers and their percentage changes
    df = pd.DataFrame(list(stock_changes.items()), columns=['Symbol', 'Percent_Change'])

    # Drop any stocks with missing data (NaN values)
    df = df.dropna()

    # Calculate the percentile rank based on percentage change
    df['RSP'] = round(df['Percent_Change'].rank(pct=True) * 100, 2)
    cols = ['Symbol', 'RSP']
    df = df[cols]
    # Sort by percentile rank (optional)
    df = df.sort_values(by='RSP', ascending=False).reset_index(drop=True)

    return df

In [6]:
# function to get stock technicals
def stock_prec_dev(stock_symbol):
    #stock_symbol = 'ULTRACEMCO.NS'
    short_window = 20
    mid_window = 50
    long_window = 200
    moving_avg = 'SMA'

    start = datetime.datetime(*map(int, start_date.split('-')))
    end = datetime.datetime(*map(int, end_date.split('-')))

    stock_df = yfin.Ticker(stock_symbol + '.NS').history(period='max', interval='1d')[map(str.title, ['open', 'close', 'low', 'high', 'volume'])]

    stock_df['Max'] = round(max(stock_df['Close']),2)
    stock_df = stock_df[(stock_df.index <= end_date) & (stock_df.index >= start_date)]
    stock_df['200_SMA'] = round(stock_df['Close'].rolling(window = 200, min_periods = 1).mean(),0)
    stock_df['Dev%_200'] = round((stock_df['Close'] - stock_df['200_SMA'])*100/stock_df['200_SMA'],2)
    stock_df.dropna(axis = 0, inplace = True) # remove any null rows

    stock_df['20_SMA'] = stock_df['Close'].rolling(window=20).mean()
    stock_df['50_SMA'] = stock_df['Close'].rolling(window=50).mean()
    stock_df['Symbol'] = stock_symbol

    stock_df['Close'] = round(stock_df['Close'],2)
    stock_df['Min'] = round(min(stock_df['Close']),2)
    stock_df['RSI_14'] = ta.momentum.RSIIndicator(close=stock_df['Close'], window=14).rsi()
    stock_df['RSI_14'] = round(stock_df['RSI_14'],0)
    stock_df['Prev_Close'] = stock_df['Close'].shift(1)
    stock_df.drop(['Open', 'Low', 'High', 'Volume'], axis=1, inplace=True)
    stock_df = stock_df.tail(1)

    max_SMA = max(stock_df['20_SMA'].item(), stock_df['50_SMA'].item(), stock_df['200_SMA'].item())
    min_SMA = min(stock_df['20_SMA'].item(), stock_df['50_SMA'].item(), stock_df['200_SMA'].item())
    ABS_Spread = max_SMA - min_SMA
    stock_df['Spread%'] = round((ABS_Spread / stock_df['200_SMA'].item()) * 100,2)

    return stock_df

# function to compute stock attributes
def get_common_features(stock_ids, df_mypf):

  df_prec_dev = pd.DataFrame()
  df_tmp = get_screener_features()
  df_rs = get_relative_strength(stock_ids)

  for stock_id in stock_ids:
      tmp = stock_prec_dev(stock_id)
      tmp = tmp.reset_index()
      df_prec_dev = pd.concat([df_prec_dev, tmp], ignore_index = True)
  df_prec_dev = pd.merge(df_prec_dev, df_mypf, on= 'Symbol')
  df_prec_dev = pd.merge(df_prec_dev, df_tmp, on= 'Symbol', how='left')
  df_prec_dev = pd.merge(df_prec_dev, df_rs, on= 'Symbol', how='left')
  #print(df_prec_dev.columns)
  df_prec_dev['Curr_PE'] = round(df_prec_dev['Close']/df_prec_dev['EPS'],1)
  df_prec_dev['Dev%_PE'] = round((df_prec_dev['Curr_PE'] - df_prec_dev['MedPE'])*100/df_prec_dev['MedPE'],2)
  df_prec_dev['Conviction'] = df_prec_dev['Conviction'] + '-' + df_prec_dev['CapType']
  return df_prec_dev

# function to arrange stock features
def arrange_features(df_stocks, common_cols, diff_cols):
  df_stocks_common = df_stocks[common_cols].drop_duplicates()
  df_stocks_diff = df_stocks[diff_cols]
  df_stocks_diff['Investment'] = df_stocks_diff['AvgCost'] * df_stocks_diff['Shares']
  df_stocks_diff = df_stocks_diff.groupby(['Symbol'])[['Shares', 'Investment']].aggregate(['sum']).reset_index()
  df_stocks_diff.columns = ['Symbol', 'Shares', 'Investment']
  df_stocks_diff['AvgCost'] = round(df_stocks_diff['Investment']/df_stocks_diff['Shares'],2)
  df_stocks = pd.merge(df_stocks_diff, df_stocks_common, on='Symbol')
  return df_stocks

# plot fact distribution across dimension
def plot_pie_chart(df, dimension, fact):
  # grouping the data by category and calculating the sum of fact for each type
  grouped_data = df.groupby(dimension)[fact].sum()

  # sorting the grouped data in descending order
  grouped_data = grouped_data.sort_values(ascending=False)

  # creating a pie chart
  grouped_data.plot.pie(autopct='%1.1f%%', startangle=90, figsize=(6, 6))

  # adding a title and displaying the plot
  plt.title(f'{dimension} {fact} Distribution')
  plt.ylabel('')  # To hide the y-label
  plt.show()

In [7]:
# function to get portfolio features

def get_portfolio_features(df_common_features):

  print_date_time()
  print('-------------------')

  #df_common_features["Target"] = df_common_features["Target"].fillna(df_common_features["Max"])
  df_common_features['NTT'] = np.where(df_common_features['Strategy']== 'NTT', df_common_features["Target"], df_common_features['Max'])
  df_common_features['LTT'] = np.where(df_common_features['Strategy']== 'BTT', df_common_features["Target"], df_common_features['Max'])
  df_common_features['BOL'] = df_common_features['Min']

  tmp_df = df_common_features[df_common_features['Symbol'].isin(mypf_df[mypf_df['InPortfolio'] != 'NA'].Symbol.values)]
  print('qualified stocks: '+str(len(tmp_df['Symbol'].unique())))
  tmp_df1 = tmp_df[tmp_df['LatestQtr'] == 1]
  print('with latest results: '+str(len(tmp_df1['Symbol'].unique())))
  tmp_df1 = tmp_df1[tmp_df1['StarStock'] == 1]
  print('still star stocks: '+str(len(tmp_df1['Symbol'].unique())))
  tmp_df['Investment'] = tmp_df['AvgCost'] * tmp_df['Shares']
  tmp_df['Current'] = round(tmp_df['Close'] * tmp_df['Shares'],0)
  tmp_df['Previous'] = tmp_df['Prev_Close'] * tmp_df['Shares']
  tmp_df['EstimatedST'] = tmp_df['NTT'] * tmp_df['Shares']
  tmp_df['EstimatedLT'] = tmp_df['LTT'] * tmp_df['Shares']
  tmp_df['Current P/L'] = round((tmp_df['Current'] - tmp_df['Investment']),0)
  tmp_df['Today P/L%'] = round((tmp_df['Current'] - tmp_df['Previous'])*100/tmp_df['Previous'],2)
  tmp_df['Current P/L%'] = round((tmp_df['Current'] - tmp_df['Investment'])*100/tmp_df['Investment'],2)
  tmp_df['EstimatedST P/L%'] = round((tmp_df['EstimatedST'] - tmp_df['Investment'])*100/tmp_df['Investment'],2)
  tmp_df['EstimatedLT P/L%'] = round((tmp_df['EstimatedLT'] - tmp_df['Investment'])*100/tmp_df['Investment'],2)
  tmp_df['NTT%'] = round((tmp_df['NTT'] - tmp_df['Close'])*100/tmp_df['Close'],2)
  tmp_df['LTT%'] = round((tmp_df['LTT'] - tmp_df['Close'])*100/tmp_df['Close'],2)
  tmp_df['Gained%'] = round((tmp_df['Close'] - tmp_df['BOL'])*100/tmp_df['BOL'],2)
  investment = round(sum(tmp_df['AvgCost']*tmp_df['Shares']),0)
  current = round(sum(tmp_df['Close']*tmp_df['Shares']),0)
  tmp_df['InitAlloc%'] = round(tmp_df['Investment']*100/investment,2)
  tmp_df['CurrAlloc%'] = round(tmp_df['Current']*100/current,2)
  tmp_df['FTT'] = tmp_df['LTT']
  tmp_df.loc[tmp_df['Strategy'] == 'NTT', 'FTT'] = tmp_df['NTT']
  tmp_df['FTT%'] = tmp_df['LTT%']
  tmp_df.loc[tmp_df['Strategy'] == 'NTT', 'FTT%'] = tmp_df['NTT%']
  tmp_df['FTT Amt'] = round(tmp_df['FTT%'] * tmp_df['Current']/100,0)
  tmp_df['OTT%'] = round((tmp_df['FTT'] - tmp_df['AvgCost'])*100/tmp_df['AvgCost'],2)
  tmp_df['RRR Ind'] = round(tmp_df['Current P/L']/tmp_df['FTT Amt'],2)
  tmp_df['Risk Ind'] = round(tmp_df['Current P/L%']*tmp_df['CurrAlloc%'],0)

  return tmp_df

# function to print portfolio features
def print_portfolio_stats(df_portfolio_features, myinvmt_df):
  from pyxirr import xirr

  total_booked_amt, reserve_amt, cy_booked_amt, py_booked_amt = get_amt()

  dates = myinvmt_df['Date'].values
  dates = np.append(dates, datetime.date.today().strftime('%d-%b-%y'))
  investment = myinvmt_df['Investment'].values
  dates= pd.to_datetime(dates)

  current = round(sum(df_portfolio_features['Close']*df_portfolio_features['Shares']),0) + reserve_amt
  investment_xirr = np.append(investment, current)
  cagr = round(xirr(pd.DataFrame({"dates": dates, "amounts": investment_xirr}))*100,2)

  investment = -sum(investment)
  invested = round(sum(df_portfolio_features['AvgCost']*df_portfolio_features['Shares']),0) + reserve_amt
  previous = round(sum(df_portfolio_features['Prev_Close']*df_portfolio_features['Shares']),0) + reserve_amt
  cy_invested = investment + py_booked_amt

  today_pnl_amount = current-previous
  today_pnl_percentage = round((current-previous)*100/previous,2)

  curr_pnl_amount = current-invested
  curr_pnl_percentage = round((curr_pnl_amount)*100/(cy_invested),2)

  cy_pnl_amount = cy_booked_amt + curr_pnl_amount
  cy_pnl_percentage = round((cy_pnl_amount)*100/cy_invested,2)

  overall_pnl_amount = total_booked_amt + curr_pnl_amount
  overall_pnl_percentage = round((overall_pnl_amount)*100/investment,2)

  estimate_st = round(sum(df_portfolio_features['FTT']*df_portfolio_features['Shares']),0)  + reserve_amt
  est_st_pnl_amount = estimate_st-current
  est_st_pnl_percentage = round((est_st_pnl_amount)*100/current,2)

  estimate_lt = round(sum(df_portfolio_features['LTT']*df_portfolio_features['Shares']),0)  + reserve_amt
  est_lt_pnl_amount = estimate_lt-current
  est_lt_pnl_percentage = round((est_lt_pnl_amount)*100/current,2)

  total_profit = round(sum(df_portfolio_features[df_portfolio_features['Current P/L%'] > 0]['Current']) - sum(df_portfolio_features[df_portfolio_features['Current P/L%'] > 0]['Investment']),0)
  total_loss = round(sum(df_portfolio_features[df_portfolio_features['Current P/L%'] < 0]['Current']) - sum(df_portfolio_features[df_portfolio_features['Current P/L%'] < 0]['Investment']),0)

  cy_booked_percentage = round((cy_booked_amt)*100/current,2)
  py_booked_percentage = round((py_booked_amt)*100/investment,2)
  total_booked_percentage = round((total_booked_amt)*100/investment,2)

  print('-------------------')
  print('Initial Investment: ', format_amt(investment))
  print('CY Investment: ', format_amt(cy_invested))
  print('Reserve: ', format_amt(reserve_amt))
  print('Current: ',  format_amt(current))
  print('-------------------')
  print('Today PnL: '+ '{} ({}%)'.format(format_amt(today_pnl_amount), today_pnl_percentage))
  print('Current PnL: '+ '{} ({}%)'.format(format_amt(curr_pnl_amount), curr_pnl_percentage))
  print('CY Booked + Current PnL: '+ '{} ({}%)'.format(format_amt(cy_pnl_amount), cy_pnl_percentage))
  print('-------------------')
  print('Total profit: ', format_amt(total_profit))
  print('Total loss: ', format_amt(total_loss))
  print('-------------------')
  print('Total Booked + Current PnL: '+ '{} ({}%)'.format(format_amt(overall_pnl_amount), overall_pnl_percentage))
  print('Total Booked PnL: '+ '{} ({}%)'.format(format_amt(total_booked_amt), total_booked_percentage))
  print('Curr Year Booked PnL: '+ '{} ({}%)'.format(format_amt(cy_booked_amt), cy_booked_percentage))
  print('Prev Year Booked PnL: '+ '{} ({}%)'.format(format_amt(py_booked_amt), py_booked_percentage))
  print('===================')
  print('Est FTT: ',  format_amt(estimate_st))
  print('Est FTT PnL: '+ '{} ({}%)'.format(format_amt(est_st_pnl_amount), est_st_pnl_percentage))

  print('===================')
  print('Deployed: ', format_amt(investment))

  print('Current: ', format_amt(current))

  print('CAGR/XIRR %: '+'{}%'.format(cagr))

In [8]:
# get start and end date
start_date, end_date = get_start_end_date()

# get portfolio and prospects data
mypfs_df = get_mypfs_df()
mypps_df = get_mypps_df()
myinvmt_df = get_myinvmt_df()

# merge above datasets
mypf_df = pd.merge(mypfs_df, mypps_df, on="Symbol")

# seggregate dm and sv portfolio
dm_pf = mypf_df[mypf_df['InPortfolio'] == 'DM']
sv_pf = mypf_df[mypf_df['InPortfolio'] == 'SV']

# build portfolio stock dataframe
dm_stocks = get_stock_ids(dm_pf)
sv_stocks = get_stock_ids(sv_pf)
df_stocks = pd.concat([dm_pf,sv_pf], ignore_index = True)

# arrange common and diff stock features
common_cols = ['Symbol', 'Target', 'Criteria', 'Strategy', 'CumlRnk', 'LatestQtr', 'StarStock', 'Conviction', 'Category', 'InFolio', 'XIRR', 'MBQ']
diff_cols = ['Symbol', 'AvgCost', 'Shares']
df_stocks = arrange_features(df_stocks, common_cols, diff_cols)

# get common features
stock_ids = df_stocks['Symbol'].values
df_common_features = get_common_features(stock_ids, df_stocks)

df_common_features.reset_index(drop=True, inplace=True)
df_common_features.drop(['Date'], axis=1, inplace=True)
# get and print portfolio features
df_portfolio_features = get_portfolio_features(df_common_features)

print_portfolio_stats(df_portfolio_features, myinvmt_df)

df = df_portfolio_features
#plot_pie_chart(df, 'CapType', 'Current')
list_ox40n = list(df[df['MBQ'].str.contains('OX40N', na=False)]['Symbol'].values)

Run date time (IST): 2026-03-09 11:10:31
-------------------
qualified stocks: 86
with latest results: 26
still star stocks: 15
-------------------
Initial Investment:  1.36 C
CY Investment:  1.62 C
Reserve:  66.25 K
Current:  1.34 C
-------------------
Today PnL: -3.18 L (-2.31%)
Current PnL: -42.43 L (-26.11%)
CY Booked + Current PnL: -26.75 L (-16.46%)
-------------------
Total profit:  98.50 K
Total loss:  -43.42 L
-------------------
Total Booked + Current PnL: 22.73 K (0.17%)
Total Booked PnL: 42.66 L (31.48%)
Curr Year Booked PnL: 15.68 L (11.66%)
Prev Year Booked PnL: 26.98 L (19.91%)
===================
Est FTT:  2.47 C
Est FTT PnL: 1.13 C (83.86%)
===================
Deployed:  1.36 C
Current:  1.34 C
CAGR/XIRR %: -0.38%

In [9]:
# top 5 near their targets
cols = ['Symbol', 'Today P/L%', 'Current P/L%', 'FTT%', 'OTT%', 'FTT Amt', 'Current P/L', 'Current', 'FTT', 'Dev%_PE', 'RSI_14','Conviction', 'Spread%',  'CumlRnk', 'RRR Ind', 'CurrAlloc%', 'Gained%', 'Criteria', 'Strategy', 'Category']
df_tmp = df_portfolio_features[~df_portfolio_features['Symbol'].isin(['ENRIN','BLUSPRING','DIGITIDE'])]
df_tmp = df_tmp.sort_values(by = 'FTT Amt', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
19,COALINDIA,-0.35,7.93,9.02,17.67,14648.0,11932.0,162393.0,478.51,30.56,57.0,L-LC,11.32,185.0,0.81,1.21,26.11,XY25,ATH,MINING
50,MASFIN,-2.38,-10.06,35.16,21.57,30985.0,-9855.0,88125.0,397.04,-22.31,31.0,H-SC,5.68,167.0,-0.32,0.66,22.96,XR,ATH,FINANCE
37,ICICIGI,-0.82,-1.22,20.81,19.34,41135.0,-2440.0,197669.0,2252.93,-16.89,43.0,X-MC,1.56,66.0,-0.06,1.48,12.74,X40,ATH,INSURANCE
77,TTKPRESTIG,-3.15,-40.96,69.55,0.09,41378.0,-41283.0,59494.0,770.00,38.10,17.0,M-SC,14.27,250.0,-1.00,0.44,0.00,OX40N,NTT,DURABLES
2,ABBOTINDIA,-0.57,-8.85,29.54,18.07,48156.0,-15835.0,163020.0,35195.00,-22.40,52.0,X-MC,11.10,58.0,-0.33,1.22,3.35,X40,ATH,PHARMA

In [10]:
# top 5 today
df_tmp = df_portfolio_features.sort_values(by = 'Today P/L%', ascending=False)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
31,HAPPSTMNDS,1.59,-57.20,331.88,84.85,182056.0,-73309.0,54856.0,1480.71,-49.04,28.0,H-SC,29.12,152.0,-0.40,0.41,1.59,AR,ATH,IT
59,RELIANCE,1.11,-9.82,38.95,25.30,70585.0,-19744.0,181219.0,1952.00,-12.34,47.0,X-LC,2.06,21.0,-0.28,1.35,20.99,XY25,BTT,REFINERIES
34,HCLTECH,0.84,-11.22,39.48,23.83,84800.0,-27132.0,214792.0,1908.19,-6.53,30.0,X-LC,8.67,8.0,-0.32,1.60,3.05,X40,ATH,IT
27,FINCABLES,0.53,23.36,68.54,107.91,124837.0,34494.0,182138.0,1641.55,11.11,72.0,M-SC,7.26,220.0,0.28,1.36,37.03,OX40N,ATH,CABLES
84,WIPRO,0.39,-19.54,114.10,72.27,155562.0,-33110.0,136338.0,420.00,-27.37,22.0,M-LC,13.32,98.0,-0.21,1.02,0.39,XR,NTT,IT

In [11]:
# bottom 5 today
df_tmp = df_portfolio_features.sort_values(by = 'Today P/L%', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
75,TMPV,-5.43,-24.50,80.89,36.58,217333.0,-87164.0,268677.0,600.0,-84.72,30.0,X-LC,2.68,4.0,-0.40,2.01,0.00,XY24,NTT,AUTO
20,COFFEEDAY,-5.27,-56.58,211.53,35.27,104297.0,-64243.0,49306.0,80.0,-65.79,24.0,L-SC,16.53,266.0,-0.62,0.37,10.07,XR,NTT,HOTELS
55,RAJESHEXPO,-5.00,-78.18,358.61,0.07,107339.0,-107245.0,29932.0,518.0,997.22,18.0,L-SC,15.34,268.0,-1.00,0.22,0.00,OX40N,NTT,JEWELLERY
7,ATULAUTO,-4.96,-27.03,99.48,45.57,143106.0,-53278.0,143854.0,844.0,3105.41,37.0,M-SC,7.28,248.0,-0.37,1.07,8.86,XY24,NTT,AUTO
11,BANDHANBNK,-4.87,-16.24,129.73,92.42,302687.0,-45238.0,233321.0,400.0,100.43,54.0,H-SC,9.83,174.0,-0.15,1.74,28.53,XY24,NTT,BANKS

In [12]:
# top 5 to exit based on CumlRnk
df_tmp = df_portfolio_features[~df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])]
df_tmp = df_tmp[(df_tmp['Current P/L%'] > -1) & (df_tmp['Current P/L%'] < 1)].sort_values(by = 'CumlRnk', ascending=False)
df_tmp[cols].head()

Empty DataFrame
Columns: [Symbol, Today P/L%, Current P/L%, FTT%, OTT%, FTT Amt, Current P/L, Current, FTT, Dev%_PE, RSI_14, Conviction, Spread%, CumlRnk, RRR Ind, CurrAlloc%, Gained%, Criteria, Strategy, Category]
Index: []

In [13]:
# OX40N stocks to exit
df_tmp = df_portfolio_features[(df_portfolio_features['Symbol'].isin(list_ox40n))].sort_values(by = 'Current P/L%', ascending=False)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
27,FINCABLES,0.53,23.36,68.54,107.91,124837.0,34494.0,182138.0,1641.55,11.11,72.0,M-SC,7.26,220.0,0.28,1.36,37.03,OX40N,ATH,CABLES
66,SIS,-3.83,-34.20,84.29,21.26,61581.0,-37974.0,73058.0,528.00,1710.36,32.0,H-SC,8.36,168.0,-0.62,0.55,0.72,OX40N,NTT,MISC
72,TATAELXSI,-1.69,-38.65,115.19,32.03,93171.0,-50950.0,80885.0,9161.00,-23.22,25.0,H-SC,15.18,158.0,-0.55,0.60,0.00,OX40N,NTT,IT
18,CERA,-1.52,-38.93,102.87,23.89,110502.0,-68484.0,107419.0,9475.00,-41.05,27.0,H-SC,15.57,153.0,-0.62,0.80,0.00,OX40N,NTT,CERAMICS
48,KANSAINER,-3.74,-39.22,86.70,13.47,142100.0,-105768.0,163899.0,340.00,-47.67,21.0,H-SC,15.66,162.0,-0.74,1.22,0.00,XY24,NTT,PAINTS

In [14]:
# top 5 to book for rotation
df_tmp = df_portfolio_features[(df_portfolio_features['Current P/L%'] > 20) ].sort_values(by = 'CumlRnk', ascending=False)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
27,FINCABLES,0.53,23.36,68.54,107.91,124837.0,34494.0,182138.0,1641.55,11.11,72.0,M-SC,7.26,220.0,0.28,1.36,37.03,OX40N,ATH,CABLES

In [15]:
# top 5 to monitor for exit
df_tmp = df_portfolio_features[~df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])]
df_tmp = df_tmp[(df_tmp['Current P/L%'] > 0) ].sort_values(by = 'Dev%_PE', ascending=False)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
19,COALINDIA,-0.35,7.93,9.02,17.67,14648.0,11932.0,162393.0,478.51,30.56,57.0,L-LC,11.32,185.0,0.81,1.21,26.11,XY25,ATH,MINING
27,FINCABLES,0.53,23.36,68.54,107.91,124837.0,34494.0,182138.0,1641.55,11.11,72.0,M-SC,7.26,220.0,0.28,1.36,37.03,OX40N,ATH,CABLES
1,ABB,-2.51,8.43,34.25,45.57,97160.0,22061.0,283680.0,7934.00,-30.32,55.0,H-MC,9.31,125.0,0.23,2.12,25.97,AR,NTT,ELECTRICAL

In [16]:
# top 5 to book for rotation from weak conviction
df_tmp = df_portfolio_features[~df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])]
df_tmp = df_tmp[~df_tmp['Criteria'].isin(['XY25','XY24','X40', 'X40N'])].sort_values(by = 'RRR Ind', ascending=False)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
27,FINCABLES,0.53,23.36,68.54,107.91,124837.0,34494.0,182138.0,1641.55,11.11,72.0,M-SC,7.26,220.0,0.28,1.36,37.03,OX40N,ATH,CABLES
1,ABB,-2.51,8.43,34.25,45.57,97160.0,22061.0,283680.0,7934.00,-30.32,55.0,H-MC,9.31,125.0,0.23,2.12,25.97,AR,NTT,ELECTRICAL
40,INDIAMART,-0.40,-9.23,127.75,106.72,143012.0,-11389.0,111947.0,4810.62,-58.98,40.0,H-SC,8.99,140.0,-0.08,0.84,11.98,AR,ATH,MISC
85,ZYDUSLIFE,-2.39,-6.02,44.31,35.63,87276.0,-12608.0,196966.0,1286.17,-18.02,45.0,H-MC,5.15,120.0,-0.14,1.47,9.65,AR,ATH,PHARMA
84,WIPRO,0.39,-19.54,114.10,72.27,155562.0,-33110.0,136338.0,420.00,-27.37,22.0,M-LC,13.32,98.0,-0.21,1.02,0.39,XR,NTT,IT

In [17]:
# top 5 to accumulate based on lowest RSI_14
df_tmp = df_portfolio_features[df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])].sort_values(by = 'RSI_14', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
8,AWL,-0.18,-39.07,174.14,67.02,378025.0,-139228.0,217081.0,485.00,-67.16,12.0,X-SC,21.75,81.0,-0.37,1.62,0.0,XY24,NTT,FMCG
53,PGHH,-2.26,-20.28,65.59,32.01,111650.0,-43296.0,170224.0,17616.87,-46.05,13.0,X-MC,10.58,57.0,-0.39,1.27,0.0,X40,ATH,FMCG
3,ACC,-3.35,-35.07,169.21,74.81,294608.0,-94020.0,174108.0,3906.00,-53.87,17.0,X-SC,11.16,85.0,-0.32,1.30,0.0,XY24,BTT,CEMENT
6,ASIANPAINT,-4.38,-21.56,58.76,24.52,130635.0,-61120.0,222319.0,3460.25,-20.84,20.0,X-LC,7.35,30.0,-0.47,1.66,0.0,X40,ATH,PAINTS
12,BATAINDIA,-3.34,-53.63,191.56,35.20,114302.0,-69001.0,59669.0,2096.00,-21.73,21.0,X-SC,24.18,91.0,-0.60,0.45,0.0,X40,NTT,FOOTWEAR

In [18]:
# top 5 to accumulate based on Spread and CumlRnk
df_tmp = df_portfolio_features[df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])]
df_tmp = df_tmp[(df_tmp['CumlRnk'] < 100)].sort_values(by = 'Spread%', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
22,DABUR,-2.47,-8.74,57.46,43.70,130088.0,-21670.0,226398.0,735.00,-17.25,27.0,X-MC,0.96,70.0,-0.17,1.69,5.00,XY24,BTT,FMCG
78,UNITDSPR,-2.30,-0.26,21.08,20.77,49231.0,-602.0,233542.0,1644.00,-11.56,46.0,X-MC,1.54,64.0,-0.01,1.75,6.43,X40N,NTT,BREWERIES
37,ICICIGI,-0.82,-1.22,20.81,19.34,41135.0,-2440.0,197669.0,2252.93,-16.89,43.0,X-MC,1.56,66.0,-0.06,1.48,12.74,X40,ATH,INSURANCE
59,RELIANCE,1.11,-9.82,38.95,25.30,70585.0,-19744.0,181219.0,1952.00,-12.34,47.0,X-LC,2.06,21.0,-0.28,1.35,20.99,XY25,BTT,REFINERIES
75,TMPV,-5.43,-24.50,80.89,36.58,217333.0,-87164.0,268677.0,600.00,-84.72,30.0,X-LC,2.68,4.0,-0.40,2.01,0.00,XY24,NTT,AUTO

In [19]:
# top 5 to accumulate based on lowest Gained%
df_tmp = df_portfolio_features[df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])].sort_values(by = 'Gained%', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
3,ACC,-3.35,-35.07,169.21,74.81,294608.0,-94020.0,174108.0,3906.00,-53.87,17.0,X-SC,11.16,85.0,-0.32,1.30,0.0,XY24,BTT,CEMENT
6,ASIANPAINT,-4.38,-21.56,58.76,24.52,130635.0,-61120.0,222319.0,3460.25,-20.84,20.0,X-LC,7.35,30.0,-0.47,1.66,0.0,X40,ATH,PAINTS
9,BAJAJHFL,-2.37,-26.62,120.94,62.13,242320.0,-72682.0,200364.0,181.50,-39.53,21.0,X-MC,18.06,60.0,-0.30,1.50,0.0,X40N,ATH,FINANCE
8,AWL,-0.18,-39.07,174.14,67.02,378025.0,-139228.0,217081.0,485.00,-67.16,12.0,X-SC,21.75,81.0,-0.37,1.62,0.0,XY24,NTT,FMCG
10,BAJAJHLDNG,-2.77,-8.19,40.74,29.22,71114.0,-15569.0,174556.0,14451.52,-15.20,31.0,X-LC,11.90,28.0,-0.22,1.30,0.0,X40,ATH,FINANCE

In [20]:
# top 5 to accumulate based on lowest CurrAlloc%
df_tmp = df_portfolio_features[df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])].sort_values(by = 'CurrAlloc%', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
58,RELAXO,-1.68,-59.02,271.68,52.31,161603.0,-85677.0,59483.0,1176.00,-56.34,22.0,X-SC,17.51,92.0,-0.53,0.44,0.00,X40N,NTT,FOOTWEAR
12,BATAINDIA,-3.34,-53.63,191.56,35.20,114302.0,-69001.0,59669.0,2096.00,-21.73,21.0,X-SC,24.18,91.0,-0.60,0.45,0.00,X40,NTT,FOOTWEAR
54,QUESS,-3.25,-24.70,130.94,73.90,105298.0,-26376.0,80417.0,424.00,-59.78,31.0,X-SC,17.70,80.0,-0.25,0.60,0.00,XY24,NTT,MISC
36,HONAUT,-1.55,-23.51,97.82,51.31,144284.0,-45338.0,147500.0,58357.33,-36.44,28.0,X-SC,13.37,90.0,-0.31,1.10,0.00,X40N,ATH,ELECTRICAL
65,SIEMENS,-2.51,-14.37,46.58,25.51,74223.0,-26750.0,159345.0,4671.50,33.78,49.0,H-LC,3.36,51.0,-0.36,1.19,17.34,AR,ATH,ELECTRICAL

In [21]:
# top 5 to accumulate based on CumlRnk
df_tmp = df_portfolio_features.sort_values(by = 'CumlRnk', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
45,ITC,-1.23,-19.43,47.76,19.06,130903.0,-66080.0,274086.0,452.00,-55.92,33.0,X-LC,16.97,1.0,-0.50,2.05,0.00,X40,NTT,FMCG
73,TCS,-0.70,-25.45,69.77,26.57,240976.0,-117887.0,345386.0,4311.59,-36.74,25.0,X-LC,12.50,2.0,-0.49,2.58,0.00,X40,ATH,IT
43,INFY,-0.92,-11.75,52.11,34.24,143893.0,-36755.0,276133.0,1972.00,-30.70,27.0,X-LC,10.91,3.0,-0.26,2.06,1.64,X40,NTT,IT
75,TMPV,-5.43,-24.50,80.89,36.58,217333.0,-87164.0,268677.0,600.00,-84.72,30.0,X-LC,2.68,4.0,-0.40,2.01,0.00,XY24,NTT,AUTO
34,HCLTECH,0.84,-11.22,39.48,23.83,84800.0,-27132.0,214792.0,1908.19,-6.53,30.0,X-LC,8.67,8.0,-0.32,1.60,3.05,X40,ATH,IT

In [22]:
# top 5 for average up
df_tmp = df_portfolio_features[(df_portfolio_features['Dev%_200'] > 5)].sort_values(by = 'CurrAlloc%', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
42,INDUSINDBK,-4.42,-35.23,105.17,32.89,52591.0,-27200.0,50006.0,1800.00,-335.29,36.0,L-MC,11.87,258.0,-0.52,0.37,37.71,XR,NTT,BANKS
19,COALINDIA,-0.35,7.93,9.02,17.67,14648.0,11932.0,162393.0,478.51,30.56,57.0,L-LC,11.32,185.0,0.81,1.21,26.11,XY25,ATH,MINING
27,FINCABLES,0.53,23.36,68.54,107.91,124837.0,34494.0,182138.0,1641.55,11.11,72.0,M-SC,7.26,220.0,0.28,1.36,37.03,OX40N,ATH,CABLES
82,VOLTAS,-0.46,15.66,25.54,45.20,56638.0,30018.0,221760.0,1856.00,32.38,50.0,X-MC,10.08,79.0,0.53,1.66,23.52,XY25,NTT,AC
11,BANDHANBNK,-4.87,-16.24,129.73,92.42,302687.0,-45238.0,233321.0,400.00,100.43,54.0,H-SC,9.83,174.0,-0.15,1.74,28.53,XY24,NTT,BANKS

In [23]:
# top 5 RSP
df_tmp = df_portfolio_features.sort_values(by = 'RSP', ascending=False)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
27,FINCABLES,0.53,23.36,68.54,107.91,124837.0,34494.0,182138.0,1641.55,11.11,72.0,M-SC,7.26,220.0,0.28,1.36,37.03,OX40N,ATH,CABLES
11,BANDHANBNK,-4.87,-16.24,129.73,92.42,302687.0,-45238.0,233321.0,400.00,100.43,54.0,H-SC,9.83,174.0,-0.15,1.74,28.53,XY24,NTT,BANKS
26,EASEMYTRIP,-3.60,-60.15,265.65,45.70,187158.0,-106362.0,70453.0,26.40,-26.82,41.0,M-SC,18.15,204.0,-0.57,0.53,16.08,XY24,NTT,TRAVEL
19,COALINDIA,-0.35,7.93,9.02,17.67,14648.0,11932.0,162393.0,478.51,30.56,57.0,L-LC,11.32,185.0,0.81,1.21,26.11,XY25,ATH,MINING
65,SIEMENS,-2.51,-14.37,46.58,25.51,74223.0,-26750.0,159345.0,4671.50,33.78,49.0,H-LC,3.36,51.0,-0.36,1.19,17.34,AR,ATH,ELECTRICAL

In [24]:
# Top N allocation
df_tmp = df_portfolio_features.sort_values(by = 'CurrAlloc%', ascending=False)
top_n_values = [10, 25, 50]

sum_df = pd.DataFrame({
    'Top_N': top_n_values,
    'Sum_Alloc%': [df_tmp['CurrAlloc%'].head(n).sum() for n in top_n_values]
})

sum_df

   Top_N  Sum_Alloc%
0     10       20.55
1     25       45.44
2     50       77.97

In [25]:
# market-cap-wise allocation
df_tmp = df_portfolio_features[cols]
df_tmp.groupby(df_tmp['Conviction'].str[-2:])['CurrAlloc%'].sum().sort_values(ascending=False)

Conviction
SC    44.34
MC    30.42
LC    25.19
Name: CurrAlloc%, dtype: float64

In [26]:
# criteria-wise allocation
df_portfolio_features.groupby('Criteria')['CurrAlloc%'].sum().sort_values(ascending=False)

Criteria
XY24     27.13
X40      24.08
X40N     15.04
AR        8.99
XY25      8.80
XR        8.17
OX40N     6.96
SR        0.78
Name: CurrAlloc%, dtype: float64

In [27]:
# conviction-wise allocation
df_portfolio_features.groupby('Conviction')['CurrAlloc%'].sum().sort_values(ascending=False)

Conviction
X-MC    23.17
X-LC    21.77
H-SC    21.42
X-SC    12.10
M-SC    10.23
H-MC     4.90
M-MC     1.98
L-LC     1.21
H-LC     1.19
M-LC     1.02
L-SC     0.59
L-MC     0.37
Name: CurrAlloc%, dtype: float64

In [28]:
# sector-wise stats
df_tmp = df_portfolio_features.groupby('Category')[['CurrAlloc%', 'Current', 'Current P/L', 'FTT Amt']].sum().sort_values(by=['Current', 'Current P/L'], ascending=False)
df_tmp['Current P/L%'] = round(df_tmp['Current P/L'] * 100 / df_tmp['Current'], 2)
df_tmp['FTT%'] = round(df_tmp['FTT Amt'] * 100 / df_tmp['Current'], 2)
cols = ['CurrAlloc%', 'Current P/L%', 'FTT%']
df_tmp[cols].sort_values(by=['CurrAlloc%'], ascending=False)

               CurrAlloc%  Current P/L%    FTT%
Category
FMCG                15.47        -20.68   63.53
FINANCE             12.69        -26.51   78.07
IT                  11.70        -43.59  116.66
MISC                 6.91        -45.05  108.06
ELECTRICAL           6.49        -11.54   54.25
PAINTS               5.17        -42.35   67.07
INSURANCE            4.72         -7.49   44.27
PHARMA               4.17         -5.28   38.42
AUTO                 3.73        -30.88   82.80
BANKS                3.09        -28.99  107.15
AC                   2.21         -8.08   37.39
HEALTHCARE           1.97        -35.21   70.49
FOOTWEAR             1.89        -74.23  144.09
TRAVEL               1.84        -82.05  173.21
DURABLES             1.77        -62.56  102.11
BREWERIES            1.75         -0.26   21.08
APPARELS             1.63        -23.22   65.25
REALTY               1.45        -14.12   32.87
CERAMICS             1.36        -67.99  119.02
CABLES               1.36         18.94   68.54
REFINERIES           1.35        -10.90   38.95
CEMENT               1.30        -54.00  169.21
MINING               1.21          7.35    9.02
ENGINEERING          1.11        -63.35  138.06
JEWELLERY            1.10       -115.99  191.03
CHEMICALS            0.95       -108.76  279.07
ENTERTAINMENT        0.77        -88.40  200.76
TEXTILES             0.42        -62.81  109.24
HOTELS               0.37       -130.29  211.53

In [29]:
# money to be made criteria-wise
df_portfolio_features.groupby('Criteria')['FTT Amt'].agg(['sum', 'count']).sort_values(by='sum', ascending=False)

                sum  count
Criteria
XY24      3963998.0     21
X40       1650578.0     15
XR        1396174.0     12
AR        1368035.0     10
X40N      1287538.0     10
OX40N      859005.0     10
XY25       439257.0      6
SR         314543.0      2

In [30]:
# money to be made conviction-wise
df_portfolio_features.groupby('Conviction')['FTT Amt'].agg(['sum', 'count']).sort_values(by='sum', ascending=False)

                  sum  count
Conviction
H-SC        3923910.0     24
X-MC        1635196.0     15
X-SC        1562363.0     10
X-LC        1559800.0     12
M-SC        1546205.0     14
H-MC         422875.0      3
L-SC         211636.0      2
M-LC         155562.0      1
M-MC         120119.0      2
H-LC          74223.0      1
L-MC          52591.0      1
L-LC          14648.0      1

In [31]:
# money to be made criteria and conviction-wise
df_portfolio_features.groupby(['Conviction', 'Criteria'])['FTT Amt'].agg(['sum', 'count']).sort_values(by='sum', ascending=False)

                           sum  count
Conviction Criteria
H-SC       XY24      1349715.0      6
           AR         978429.0      5
M-SC       XY24       914516.0      6
H-SC       XR         892475.0      7
X-SC       XY24       837303.0      4
X-LC       X40        802321.0      6
X-MC       X40        641222.0      7
           X40N       528617.0      4
X-SC       X40N       518025.0      4
H-SC       OX40N      388748.0      4
X-LC       XY24       373001.0      2
M-SC       OX40N      362918.0      5
H-SC       SR         314543.0      2
X-MC       XY24       251024.0      2
X-LC       X40N       240896.0      2
H-MC       XY24       238439.0      1
X-MC       XY25       214333.0      2
X-SC       X40        207035.0      2
M-SC       XR         191249.0      2
H-MC       AR         184436.0      2
M-LC       XR         155562.0      1
X-LC       XY25       143582.0      2
L-SC       OX40N      107339.0      1
           XR         104297.0      1
M-SC       AR          77522.0      1
H-LC       AR          74223.0      1
M-MC       XY25        66694.0      1
           AR          53425.0      1
L-MC       XR          52591.0      1
L-LC       XY25        14648.0      1

In [32]:
# notebook execution time

end_time = time.time()
execution_time = round(end_time - start_time, 0)
print(f"Notebook execution time: {execution_time} seconds")

Notebook execution time: 33.0 seconds