<a href="https://colab.research.google.com/github/ankit-rathi/Quantvesting_v2/blob/main/myStocks_Portfolio_Analysis.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
'''
!pip install pandas==2.2.2 -qq
!pip install pyxirr -qq
!pip install ta -qq
!pip install yfinance==0.2.59 -qq
'''

'\n!pip install pandas==2.2.2 -qq\n!pip install pyxirr -qq\n!pip install ta -qq\n!pip install yfinance==0.2.59 -qq\n'

In [2]:
# import libraries

import numpy as np
import pandas as pd
import datetime
import warnings
warnings.filterwarnings('ignore')
import yfinance as yfin
import ta
import matplotlib.pyplot as plt
import requests

In [3]:
# notebook start time
import time
import datetime
import pytz

start_time = time.time()

# function to print date timestamp
def print_date_time():
  tz_NY = pytz.timezone('Asia/Kolkata')
  datetime_NY = datetime.datetime.now(tz_NY)
  print("Run date time (IST):", datetime_NY.strftime("%Y-%m-%d %H:%M:%S"))

In [4]:
# function to get booked and reserved amount
def get_amt():
  # fetch the JSON data from the URL
  url = "https://raw.githubusercontent.com/ankit-rathi/Tradevesting_v1/main/data/myPortfolioAmts.json"
  response = requests.get(url)
  pf_amts = response.json()  # parse the JSON data

  # extract values from the JSON
  py_booked_amt_dm = pf_amts["py_booked_amt_dm"]
  py_booked_amt_sv = pf_amts["py_booked_amt_sv"]
  cy_booked_amt_dm = pf_amts["cy_booked_amt_dm"]
  cy_booked_amt_sv = pf_amts["cy_booked_amt_sv"]
  reserve_amt_dm = pf_amts["reserve_amt_dm"]
  reserve_amt_sv = pf_amts["reserve_amt_sv"]

  # perform calculations
  py_booked_amt = py_booked_amt_dm + py_booked_amt_sv
  cy_booked_amt = cy_booked_amt_dm + cy_booked_amt_sv
  reserve_amt = reserve_amt_dm + reserve_amt_sv
  total_booked_amt = py_booked_amt + cy_booked_amt

  return total_booked_amt, reserve_amt, cy_booked_amt, py_booked_amt

gen_output = 0

In [5]:
# function to format the amount
def format_amt(number):
    abs_number = abs(number)

    if abs_number >= 1_00_00_000:  # Crores
        formatted_amt = f"{number / 1_00_00_000:.2f} C"
    elif abs_number >= 1_00_000:  # Lakhs
        formatted_amt = f"{number / 1_00_000:.2f} L"
    elif abs_number >= 1_000:  # Thousands
        formatted_amt = f"{number / 1_000:.2f} K"
    else:
        formatted_amt = f"{number:.2f}"

    return formatted_amt

# function to set start and end date
def get_start_end_date():
  start_date = (datetime.date.today() + datetime.timedelta(days=-365)).strftime('%Y-%m-%d')
  end_date = (datetime.date.today() + datetime.timedelta(days=1)).strftime('%Y-%m-%d')
  return start_date, end_date

# function to fetch my portfolio csv
def get_mypfs_df():
  mypfs_df = pd.read_csv('https://raw.githubusercontent.com/ankit-rathi/Tradevesting_v1/main/data/myPortfolioStocks.csv')
  return mypfs_df

# function to fetch my prospects csv
def get_mypps_df():
  mypps_df = pd.read_csv('https://raw.githubusercontent.com/ankit-rathi/Tradevesting_v1/main/data/myProspectsScrips.csv')
  return mypps_df

# function to fetch screener data
def get_myscreen_df():
  myscreen_df = pd.read_csv('https://raw.githubusercontent.com/ankit-rathi/Tradevesting_v1/main/data/myScreenerDB.csv')
  return myscreen_df

# function to fetch momentum data
def get_myinvmt_df():
  myinvmt_df = pd.read_csv('https://raw.githubusercontent.com/ankit-rathi/Tradevesting_v1/main/data/myInvestments.csv')
  return myinvmt_df

# function to get the stock ids
def get_stock_ids(df_pf):
  stock_n100 = df_pf['Symbol'].unique()

  exclude = ['CADILAHC','MMTC', 'MASFIN']

  stock_ids = df_pf[~df_pf['Symbol'].isin(exclude) ]['Symbol'].unique()

  #mypf = mypf[mypf.Forecast.notnull()]
  #stock_ids = mypf['Symbol'].unique()

  #stock_ids.sort()
  return stock_ids

# get features from screener data
def get_screener_features():
  myscreen_df = get_myscreen_df()
  cols = ['Symbol', 'EPS', 'MedPE', 'ROCE%', 'ROE%', 'CapType']
  return myscreen_df[cols]

# get relative strength
def get_relative_strength(stock_list):

    # Dictionary to store stock tickers and their corresponding percentage price change
    stock_changes = {}

    # Loop through each stock and fetch its price data
    for stock in stock_list:
        try:
            # Download the stock data for the given date range
            stock_data = yfin.Ticker(stock + '.NS').history(period='1mo', interval='1d')[map(str.title, ['open', 'close', 'low', 'high', 'volume'])]

            # Calculate the percentage change for the stock
            if len(stock_data) > 0:
                start_price = stock_data['Close'].iloc[0]
                end_price = stock_data['Close'].iloc[-1]
                percent_change = round(((end_price - start_price) / start_price) * 100, 2)
                stock_changes[stock] = percent_change
            else:
                stock_changes[stock] = np.nan  # If no data is available, set to NaN

        except Exception as e:
            print(f"Error fetching data for {stock}: {e}")
            stock_changes[stock] = np.nan

    # Create a DataFrame with stock tickers and their percentage changes
    df = pd.DataFrame(list(stock_changes.items()), columns=['Symbol', 'Percent_Change'])

    # Drop any stocks with missing data (NaN values)
    df = df.dropna()

    # Calculate the percentile rank based on percentage change
    df['RSP'] = round(df['Percent_Change'].rank(pct=True) * 100, 2)
    cols = ['Symbol', 'RSP']
    df = df[cols]
    # Sort by percentile rank (optional)
    df = df.sort_values(by='RSP', ascending=False).reset_index(drop=True)

    return df

In [6]:
# function to get stock technicals
def stock_prec_dev(stock_symbol):
    #stock_symbol = 'ULTRACEMCO.NS'
    short_window = 20
    mid_window = 50
    long_window = 200
    moving_avg = 'SMA'

    start = datetime.datetime(*map(int, start_date.split('-')))
    end = datetime.datetime(*map(int, end_date.split('-')))

    stock_df = yfin.Ticker(stock_symbol + '.NS').history(period='max', interval='1d')[map(str.title, ['open', 'close', 'low', 'high', 'volume'])]

    stock_df['Max'] = round(max(stock_df['Close']),2)
    stock_df = stock_df[(stock_df.index <= end_date) & (stock_df.index >= start_date)]
    stock_df['200_SMA'] = round(stock_df['Close'].rolling(window = 200, min_periods = 1).mean(),0)
    stock_df['Dev%_200'] = round((stock_df['Close'] - stock_df['200_SMA'])*100/stock_df['200_SMA'],2)
    stock_df.dropna(axis = 0, inplace = True) # remove any null rows

    stock_df['20_SMA'] = stock_df['Close'].rolling(window=20).mean()
    stock_df['50_SMA'] = stock_df['Close'].rolling(window=50).mean()
    stock_df['Symbol'] = stock_symbol

    stock_df['Close'] = round(stock_df['Close'],2)
    stock_df['Min'] = round(min(stock_df['Close']),2)
    stock_df['RSI_14'] = ta.momentum.RSIIndicator(close=stock_df['Close'], window=14).rsi()
    stock_df['RSI_14'] = round(stock_df['RSI_14'],0)
    stock_df['Prev_Close'] = stock_df['Close'].shift(1)
    stock_df.drop(['Open', 'Low', 'High', 'Volume'], axis=1, inplace=True)
    stock_df = stock_df.tail(1)

    max_SMA = max(stock_df['20_SMA'].item(), stock_df['50_SMA'].item(), stock_df['200_SMA'].item())
    min_SMA = min(stock_df['20_SMA'].item(), stock_df['50_SMA'].item(), stock_df['200_SMA'].item())
    ABS_Spread = max_SMA - min_SMA
    stock_df['Spread%'] = round((ABS_Spread / stock_df['200_SMA'].item()) * 100,2)

    return stock_df

# function to compute stock attributes
def get_common_features(stock_ids, df_mypf):

  df_prec_dev = pd.DataFrame()
  df_tmp = get_screener_features()
  df_rs = get_relative_strength(stock_ids)

  for stock_id in stock_ids:
      tmp = stock_prec_dev(stock_id)
      tmp = tmp.reset_index()
      df_prec_dev = pd.concat([df_prec_dev, tmp], ignore_index = True)
  df_prec_dev = pd.merge(df_prec_dev, df_mypf, on= 'Symbol')
  df_prec_dev = pd.merge(df_prec_dev, df_tmp, on= 'Symbol', how='left')
  df_prec_dev = pd.merge(df_prec_dev, df_rs, on= 'Symbol', how='left')
  #print(df_prec_dev.columns)
  df_prec_dev['Curr_PE'] = round(df_prec_dev['Close']/df_prec_dev['EPS'],1)
  df_prec_dev['Dev%_PE'] = round((df_prec_dev['Curr_PE'] - df_prec_dev['MedPE'])*100/df_prec_dev['MedPE'],2)
  df_prec_dev['Conviction'] = df_prec_dev['Conviction'] + '-' + df_prec_dev['CapType']
  return df_prec_dev

# function to arrange stock features
def arrange_features(df_stocks, common_cols, diff_cols):
  df_stocks_common = df_stocks[common_cols].drop_duplicates()
  df_stocks_diff = df_stocks[diff_cols]
  df_stocks_diff['Investment'] = df_stocks_diff['AvgCost'] * df_stocks_diff['Shares']
  df_stocks_diff = df_stocks_diff.groupby(['Symbol'])[['Shares', 'Investment']].aggregate(['sum']).reset_index()
  df_stocks_diff.columns = ['Symbol', 'Shares', 'Investment']
  df_stocks_diff['AvgCost'] = round(df_stocks_diff['Investment']/df_stocks_diff['Shares'],2)
  df_stocks = pd.merge(df_stocks_diff, df_stocks_common, on='Symbol')
  return df_stocks

# plot fact distribution across dimension
def plot_pie_chart(df, dimension, fact):
  # grouping the data by category and calculating the sum of fact for each type
  grouped_data = df.groupby(dimension)[fact].sum()

  # sorting the grouped data in descending order
  grouped_data = grouped_data.sort_values(ascending=False)

  # creating a pie chart
  grouped_data.plot.pie(autopct='%1.1f%%', startangle=90, figsize=(6, 6))

  # adding a title and displaying the plot
  plt.title(f'{dimension} {fact} Distribution')
  plt.ylabel('')  # To hide the y-label
  plt.show()

In [7]:
# function to get portfolio features

def get_portfolio_features(df_common_features):

  print_date_time()
  print('-------------------')

  #df_common_features["Target"] = df_common_features["Target"].fillna(df_common_features["Max"])
  df_common_features['NTT'] = np.where(df_common_features['Strategy']== 'NTT', df_common_features["Target"], df_common_features['Max'])
  df_common_features['LTT'] = np.where(df_common_features['Strategy']== 'BTT', df_common_features["Target"], df_common_features['Max'])
  df_common_features['BOL'] = df_common_features['Min']

  tmp_df = df_common_features[df_common_features['Symbol'].isin(mypf_df[mypf_df['InPortfolio'] != 'NA'].Symbol.values)]
  print('qualified stocks: '+str(len(tmp_df['Symbol'].unique())))
  tmp_df1 = tmp_df[tmp_df['LatestQtr'] == 1]
  print('with latest results: '+str(len(tmp_df1['Symbol'].unique())))
  tmp_df1 = tmp_df1[tmp_df1['StarStock'] == 1]
  print('still star stocks: '+str(len(tmp_df1['Symbol'].unique())))
  tmp_df['Investment'] = tmp_df['AvgCost'] * tmp_df['Shares']
  tmp_df['Current'] = round(tmp_df['Close'] * tmp_df['Shares'],0)
  tmp_df['Previous'] = tmp_df['Prev_Close'] * tmp_df['Shares']
  tmp_df['EstimatedST'] = tmp_df['NTT'] * tmp_df['Shares']
  tmp_df['EstimatedLT'] = tmp_df['LTT'] * tmp_df['Shares']
  tmp_df['Current P/L'] = round((tmp_df['Current'] - tmp_df['Investment']),0)
  tmp_df['Today P/L%'] = round((tmp_df['Current'] - tmp_df['Previous'])*100/tmp_df['Previous'],2)
  tmp_df['Current P/L%'] = round((tmp_df['Current'] - tmp_df['Investment'])*100/tmp_df['Investment'],2)
  tmp_df['EstimatedST P/L%'] = round((tmp_df['EstimatedST'] - tmp_df['Investment'])*100/tmp_df['Investment'],2)
  tmp_df['EstimatedLT P/L%'] = round((tmp_df['EstimatedLT'] - tmp_df['Investment'])*100/tmp_df['Investment'],2)
  tmp_df['NTT%'] = round((tmp_df['NTT'] - tmp_df['Close'])*100/tmp_df['Close'],2)
  tmp_df['LTT%'] = round((tmp_df['LTT'] - tmp_df['Close'])*100/tmp_df['Close'],2)
  tmp_df['Gained%'] = round((tmp_df['Close'] - tmp_df['BOL'])*100/tmp_df['BOL'],2)
  investment = round(sum(tmp_df['AvgCost']*tmp_df['Shares']),0)
  current = round(sum(tmp_df['Close']*tmp_df['Shares']),0)
  tmp_df['InitAlloc%'] = round(tmp_df['Investment']*100/investment,2)
  tmp_df['CurrAlloc%'] = round(tmp_df['Current']*100/current,2)
  tmp_df['FTT'] = tmp_df['LTT']
  tmp_df.loc[tmp_df['Strategy'] == 'NTT', 'FTT'] = tmp_df['NTT']
  tmp_df['FTT%'] = tmp_df['LTT%']
  tmp_df.loc[tmp_df['Strategy'] == 'NTT', 'FTT%'] = tmp_df['NTT%']
  tmp_df['FTT Amt'] = round(tmp_df['FTT%'] * tmp_df['Current']/100,0)
  tmp_df['OTT%'] = round((tmp_df['FTT'] - tmp_df['AvgCost'])*100/tmp_df['AvgCost'],2)
  tmp_df['RRR Ind'] = round(tmp_df['Current P/L']/tmp_df['FTT Amt'],2)
  tmp_df['Risk Ind'] = round(tmp_df['Current P/L%']*tmp_df['CurrAlloc%'],0)

  return tmp_df

# function to print portfolio features
def print_portfolio_stats(df_portfolio_features, myinvmt_df):
  from pyxirr import xirr

  total_booked_amt, reserve_amt, cy_booked_amt, py_booked_amt = get_amt()

  dates = myinvmt_df['Date'].values
  dates = np.append(dates, datetime.date.today().strftime('%d-%b-%y'))
  investment = myinvmt_df['Investment'].values
  dates= pd.to_datetime(dates)

  current = round(sum(df_portfolio_features['Close']*df_portfolio_features['Shares']),0) + reserve_amt
  investment_xirr = np.append(investment, current)
  cagr = round(xirr(pd.DataFrame({"dates": dates, "amounts": investment_xirr}))*100,2)

  investment = -sum(investment)
  invested = round(sum(df_portfolio_features['AvgCost']*df_portfolio_features['Shares']),0) + reserve_amt
  previous = round(sum(df_portfolio_features['Prev_Close']*df_portfolio_features['Shares']),0) + reserve_amt
  cy_invested = investment + py_booked_amt

  today_pnl_amount = current-previous
  today_pnl_percentage = round((current-previous)*100/previous,2)

  curr_pnl_amount = current-invested
  curr_pnl_percentage = round((curr_pnl_amount)*100/(cy_invested),2)

  cy_pnl_amount = cy_booked_amt + curr_pnl_amount
  cy_pnl_percentage = round((cy_pnl_amount)*100/cy_invested,2)

  overall_pnl_amount = total_booked_amt + curr_pnl_amount
  overall_pnl_percentage = round((overall_pnl_amount)*100/investment,2)

  estimate_st = round(sum(df_portfolio_features['FTT']*df_portfolio_features['Shares']),0)  + reserve_amt
  est_st_pnl_amount = estimate_st-current
  est_st_pnl_percentage = round((est_st_pnl_amount)*100/current,2)

  estimate_lt = round(sum(df_portfolio_features['LTT']*df_portfolio_features['Shares']),0)  + reserve_amt
  est_lt_pnl_amount = estimate_lt-current
  est_lt_pnl_percentage = round((est_lt_pnl_amount)*100/current,2)

  total_profit = round(sum(df_portfolio_features[df_portfolio_features['Current P/L%'] > 0]['Current']) - sum(df_portfolio_features[df_portfolio_features['Current P/L%'] > 0]['Investment']),0)
  total_loss = round(sum(df_portfolio_features[df_portfolio_features['Current P/L%'] < 0]['Current']) - sum(df_portfolio_features[df_portfolio_features['Current P/L%'] < 0]['Investment']),0)

  cy_booked_percentage = round((cy_booked_amt)*100/current,2)
  py_booked_percentage = round((py_booked_amt)*100/investment,2)
  total_booked_percentage = round((total_booked_amt)*100/investment,2)

  print('-------------------')
  print('Initial Investment: ', format_amt(investment))
  print('CY Investment: ', format_amt(cy_invested))
  print('Reserve: ', format_amt(reserve_amt))
  print('Current: ',  format_amt(current))
  print('-------------------')
  print('Today PnL: '+ '{} ({}%)'.format(format_amt(today_pnl_amount), today_pnl_percentage))
  print('Current PnL: '+ '{} ({}%)'.format(format_amt(curr_pnl_amount), curr_pnl_percentage))
  print('CY Booked + Current PnL: '+ '{} ({}%)'.format(format_amt(cy_pnl_amount), cy_pnl_percentage))
  print('-------------------')
  print('Total profit: ', format_amt(total_profit))
  print('Total loss: ', format_amt(total_loss))
  print('-------------------')
  print('Total Booked + Current PnL: '+ '{} ({}%)'.format(format_amt(overall_pnl_amount), overall_pnl_percentage))
  print('Total Booked PnL: '+ '{} ({}%)'.format(format_amt(total_booked_amt), total_booked_percentage))
  print('Curr Year Booked PnL: '+ '{} ({}%)'.format(format_amt(cy_booked_amt), cy_booked_percentage))
  print('Prev Year Booked PnL: '+ '{} ({}%)'.format(format_amt(py_booked_amt), py_booked_percentage))
  print('===================')
  print('Est FTT: ',  format_amt(estimate_st))
  print('Est FTT PnL: '+ '{} ({}%)'.format(format_amt(est_st_pnl_amount), est_st_pnl_percentage))

  print('===================')
  print('Deployed: ', format_amt(investment))

  print('Current: ', format_amt(current))

  print('CAGR/XIRR %: '+'{}%'.format(cagr))

In [8]:
# get start and end date
start_date, end_date = get_start_end_date()

# get portfolio and prospects data
mypfs_df = get_mypfs_df()
mypps_df = get_mypps_df()
myinvmt_df = get_myinvmt_df()

# merge above datasets
mypf_df = pd.merge(mypfs_df, mypps_df, on="Symbol")

# seggregate dm and sv portfolio
dm_pf = mypf_df[mypf_df['InPortfolio'] == 'DM']
sv_pf = mypf_df[mypf_df['InPortfolio'] == 'SV']

# build portfolio stock dataframe
dm_stocks = get_stock_ids(dm_pf)
sv_stocks = get_stock_ids(sv_pf)
df_stocks = pd.concat([dm_pf,sv_pf], ignore_index = True)

# arrange common and diff stock features
common_cols = ['Symbol', 'Target', 'Criteria', 'Strategy', 'CumlRnk', 'LatestQtr', 'StarStock', 'Conviction', 'Category', 'InFolio', 'XIRR', 'MBQ']
diff_cols = ['Symbol', 'AvgCost', 'Shares']
df_stocks = arrange_features(df_stocks, common_cols, diff_cols)

# get common features
stock_ids = df_stocks['Symbol'].values
df_common_features = get_common_features(stock_ids, df_stocks)

df_common_features.reset_index(drop=True, inplace=True)
df_common_features.drop(['Date'], axis=1, inplace=True)
# get and print portfolio features
df_portfolio_features = get_portfolio_features(df_common_features)

print_portfolio_stats(df_portfolio_features, myinvmt_df)

df = df_portfolio_features
#plot_pie_chart(df, 'CapType', 'Current')
list_ox40n = list(df[df['MBQ'].str.contains('OX40N', na=False)]['Symbol'].values)

Run date time (IST): 2026-07-24 15:46:02
-------------------
qualified stocks: 92
with latest results: 31
still star stocks: 20

-------------------
Initial Investment:  1.40 C
CY Investment:  1.82 C
Reserve:  1.49 K
Current:  1.51 C
-------------------
Today PnL: 43.94 K (0.29%)
Current PnL: -32.05 L (-17.58%)
CY Booked + Current PnL: -29.97 L (-16.44%)
-------------------
Total profit:  4.57 L
Total loss:  -36.62 L
-------------------
Total Booked + Current PnL: 12.90 L (9.24%)
Total Booked PnL: 44.95 L (32.22%)
Curr Year Booked PnL: 2.08 L (1.38%)
Prev Year Booked PnL: 42.87 L (30.73%)
===================
Est FTT:  2.55 C
Est FTT PnL: 1.04 C (68.61%)
===================
Deployed:  1.40 C
Current:  1.51 C
CAGR/XIRR %: 3.58%

In [9]:
# top 5 near their targets
cols = ['Symbol', 'Today P/L%', 'Current P/L%', 'FTT%', 'OTT%', 'FTT Amt', 'Current P/L', 'Current', 'FTT', 'Dev%_PE', 'RSI_14','Conviction', 'Spread%',  'CumlRnk', 'RRR Ind', 'CurrAlloc%', 'Gained%', 'Criteria', 'Strategy', 'Category']
df_tmp = df_portfolio_features[~df_portfolio_features['Symbol'].isin(['ENRIN','BLUSPRING','DIGITIDE'])]
df_tmp = df_tmp.sort_values(by = 'FTT Amt', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
68,SATIN,4.92,48.99,1.91,51.83,7862.0,135356.0,411640.0,274.00,34.03,61.0,H-SC,44.98,159.0,17.22,2.72,100.53,XY24,NTT,FINANCE
59,PIDILITIND,0.43,11.32,5.56,17.52,8734.0,15980.0,157090.0,1658.32,-22.05,53.0,X-LC,8.04,5.0,1.83,1.04,24.23,X40,ATH,CHEMICALS
49,JSWINFRA,-0.55,9.86,5.98,16.43,14570.0,21864.0,243638.0,342.00,-5.72,49.0,X-MC,18.81,61.0,1.50,1.61,38.14,X40N,NTT,REALTY
73,SONACOMS,-0.25,24.20,11.66,38.69,14650.0,24482.0,125641.0,801.69,-1.57,74.0,M-MC,26.20,193.0,1.67,0.83,78.25,AR,ATH,AUTO
83,TTKPRESTIG,-0.37,-16.37,19.69,0.09,16595.0,-16498.0,84279.0,770.00,95.52,58.0,M-SC,11.27,250.0,-0.99,0.56,50.07,OX40N,NTT,DURABLES

In [10]:
# top 5 today
df_tmp = df_portfolio_features.sort_values(by = 'Today P/L%', ascending=False)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
68,SATIN,4.92,48.99,1.91,51.83,7862.0,135356.0,411640.0,274.00,34.03,61.0,H-SC,44.98,159.0,17.22,2.72,100.53,XY24,NTT,FINANCE
78,TATAELXSI,4.44,-49.01,158.93,32.03,106836.0,-64613.0,67222.0,9161.00,-36.16,41.0,H-SC,21.63,158.0,-0.60,0.44,4.44,OX40N,NTT,IT
84,UNITDSPR,3.47,7.78,12.05,20.77,30409.0,18214.0,252358.0,1644.00,-4.47,71.0,X-MC,4.58,64.0,0.60,1.67,21.31,X40N,NTT,BREWERIES
39,ICICIGI,2.64,-11.97,35.06,18.89,61759.0,-23958.0,176151.0,2244.41,-25.96,42.0,X-MC,7.10,66.0,-0.39,1.17,4.94,X40,ATH,INSURANCE
25,FINCABLES,2.16,26.52,64.34,107.91,120183.0,39150.0,186794.0,1641.55,13.65,40.0,M-SC,20.53,220.0,0.33,1.24,40.53,OX40N,ATH,CABLES

In [11]:
# bottom 5 today
df_tmp = df_portfolio_features.sort_values(by = 'Today P/L%', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
67,ROUTE,-5.31,-56.85,289.67,68.16,166340.0,-75642.0,57424.0,2215.45,-65.20,54.0,H-SC,8.49,141.0,-0.45,0.38,36.80,SR,ATH,IT
61,RAJESHEXPO,-3.82,-82.82,482.48,0.07,113701.0,-113611.0,23566.0,518.00,763.64,45.0,L-SC,35.72,268.0,-1.00,0.16,16.39,OX40N,NTT,JEWELLERY
77,TANLA,-3.03,-32.22,220.52,117.25,404707.0,-87237.0,183524.0,1922.32,-31.42,62.0,H-SC,6.31,147.0,-0.22,1.21,60.68,AR,ATH,IT
53,M&M,-2.11,2.58,19.03,22.10,27073.0,3582.0,142263.0,3762.88,-13.04,53.0,X-LC,7.62,25.0,0.13,0.94,8.99,X40N,ATH,AUTO
42,INDIAMART,-1.71,-24.37,165.67,100.92,154529.0,-30061.0,93275.0,4675.60,-65.82,29.0,H-SC,9.76,140.0,-0.19,0.62,0.00,AR,ATH,MISC

In [12]:
# top 5 to exit based on CumlRnk
df_tmp = df_portfolio_features[~df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])]
df_tmp = df_tmp[(df_tmp['Current P/L%'] > -1) & (df_tmp['Current P/L%'] < 1)].sort_values(by = 'CumlRnk', ascending=False)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
72,SIS,-0.26,0.49,20.67,21.26,23063.0,543.0,111575.0,528.0,2664.77,57.0,H-SC,24.31,168.0,0.02,0.74,65.9,OX40N,NTT,MISC

In [13]:
# OX40N stocks to exit
df_tmp = df_portfolio_features[(df_portfolio_features['Symbol'].isin(list_ox40n))].sort_values(by = 'Current P/L%', ascending=False)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
25,FINCABLES,2.16,26.52,64.34,107.91,120183.0,39150.0,186794.0,1641.55,13.65,40.0,M-SC,20.53,220.0,0.33,1.24,40.53,OX40N,ATH,CABLES
72,SIS,-0.26,0.49,20.67,21.26,23063.0,543.0,111575.0,528.00,2664.77,57.0,H-SC,24.31,168.0,0.02,0.74,65.90,OX40N,NTT,MISC
83,TTKPRESTIG,-0.37,-16.37,19.69,0.09,16595.0,-16498.0,84279.0,770.00,95.52,58.0,M-SC,11.27,250.0,-0.99,0.56,50.07,OX40N,NTT,DURABLES
16,CERA,-0.07,-21.33,57.47,23.89,79533.0,-37512.0,138391.0,9475.00,-24.11,44.0,H-SC,14.49,153.0,-0.47,0.92,34.53,OX40N,NTT,CERAMICS
69,SFL,1.36,-25.03,68.91,26.63,135465.0,-65635.0,196583.0,1287.00,48.90,57.0,M-SC,24.95,242.0,-0.48,1.30,64.06,XY24,NTT,MISC

In [14]:
# top 5 to book for rotation
df_tmp = df_portfolio_features[(df_portfolio_features['Current P/L%'] > 20) ].sort_values(by = 'CumlRnk', ascending=False)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
25,FINCABLES,2.16,26.52,64.34,107.91,120183.0,39150.0,186794.0,1641.55,13.65,40.0,M-SC,20.53,220.0,0.33,1.24,40.53,OX40N,ATH,CABLES
73,SONACOMS,-0.25,24.20,11.66,38.69,14650.0,24482.0,125641.0,801.69,-1.57,74.0,M-MC,26.20,193.0,1.67,0.83,78.25,AR,ATH,AUTO
68,SATIN,4.92,48.99,1.91,51.83,7862.0,135356.0,411640.0,274.00,34.03,61.0,H-SC,44.98,159.0,17.22,2.72,100.53,XY24,NTT,FINANCE
60,QUESS,-0.76,21.15,43.53,73.90,56321.0,22592.0,129385.0,424.00,-34.99,65.0,X-SC,34.44,80.0,0.40,0.86,76.38,XY24,NTT,MISC

In [15]:
# top 5 to monitor for exit
df_tmp = df_portfolio_features[~df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])]
df_tmp = df_tmp[(df_tmp['Current P/L%'] > 0) ].sort_values(by = 'Dev%_PE', ascending=False)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
72,SIS,-0.26,0.49,20.67,21.26,23063.0,543.0,111575.0,528.00,2664.77,57.0,H-SC,24.31,168.0,0.02,0.74,65.90,OX40N,NTT,MISC
75,SURYODAY,-0.62,9.99,11.86,23.03,23360.0,17891.0,196962.0,216.00,114.91,61.0,H-SC,23.94,166.0,0.77,1.30,67.19,XR,NTT,BANKS
74,STARHEALTH,0.66,12.39,31.03,47.26,98041.0,34832.0,315955.0,761.00,77.33,52.0,H-SC,18.72,173.0,0.36,2.09,37.11,XY24,NTT,INSURANCE
68,SATIN,4.92,48.99,1.91,51.83,7862.0,135356.0,411640.0,274.00,34.03,61.0,H-SC,44.98,159.0,17.22,2.72,100.53,XY24,NTT,FINANCE
25,FINCABLES,2.16,26.52,64.34,107.91,120183.0,39150.0,186794.0,1641.55,13.65,40.0,M-SC,20.53,220.0,0.33,1.24,40.53,OX40N,ATH,CABLES

In [16]:
# top 5 to book for rotation from weak conviction
df_tmp = df_portfolio_features[~df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])]
df_tmp = df_tmp[~df_tmp['Criteria'].isin(['XY25','XY24','X40', 'X40N'])].sort_values(by = 'RRR Ind', ascending=False)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
73,SONACOMS,-0.25,24.20,11.66,38.69,14650.0,24482.0,125641.0,801.69,-1.57,74.0,M-MC,26.20,193.0,1.67,0.83,78.25,AR,ATH,AUTO
91,ZYDUSLIFE,-0.37,16.91,15.90,35.51,38959.0,35449.0,245023.0,1285.01,1.80,46.0,H-MC,17.16,120.0,0.91,1.62,28.94,AR,ATH,PHARMA
75,SURYODAY,-0.62,9.99,11.86,23.03,23360.0,17891.0,196962.0,216.00,114.91,61.0,H-SC,23.94,166.0,0.77,1.30,67.19,XR,NTT,BANKS
25,FINCABLES,2.16,26.52,64.34,107.91,120183.0,39150.0,186794.0,1641.55,13.65,40.0,M-SC,20.53,220.0,0.33,1.24,40.53,OX40N,ATH,CABLES
72,SIS,-0.26,0.49,20.67,21.26,23063.0,543.0,111575.0,528.00,2664.77,57.0,H-SC,24.31,168.0,0.02,0.74,65.90,OX40N,NTT,MISC

In [17]:
# top 5 to accumulate based on lowest RSI_14
df_tmp = df_portfolio_features[df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])].sort_values(by = 'RSI_14', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
87,VBL,-0.40,-7.65,46.58,35.37,135871.0,-24148.0,291694.0,670.16,-18.49,30.0,X-LC,7.00,13.0,-0.18,1.93,19.89,X40N,ATH,FMCG
81,TMPV,-0.15,-26.29,85.30,36.58,223723.0,-93563.0,262278.0,600.00,-84.72,33.0,X-LC,7.56,4.0,-0.42,1.74,10.23,XY24,NTT,AUTO
34,HDFCBANK,-0.60,-11.14,44.45,28.37,92779.0,-26158.0,208727.0,1073.00,-24.48,34.0,X-LC,10.60,26.0,-0.28,1.38,3.22,X40,BTT,BANKS
7,BAJAJHFL,-0.73,-24.80,115.58,62.13,237331.0,-67707.0,205339.0,181.50,-38.22,39.0,X-MC,6.66,60.0,-0.29,1.36,15.19,X40N,ATH,FINANCE
39,ICICIGI,2.64,-11.97,35.06,18.89,61759.0,-23958.0,176151.0,2244.41,-25.96,42.0,X-MC,7.10,66.0,-0.39,1.17,4.94,X40,ATH,INSURANCE

In [18]:
# top 5 to accumulate based on Spread and CumlRnk
df_tmp = df_portfolio_features[df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])]
df_tmp = df_tmp[(df_tmp['CumlRnk'] < 100)].sort_values(by = 'Spread%', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
11,BERGEPAINT,0.88,-8.23,36.56,25.32,86474.0,-21223.0,236526.0,680.00,-13.20,47.0,X-MC,1.48,68.0,-0.25,1.57,23.10,XY24,NTT,PAINTS
19,COLPAL,0.01,-20.79,76.57,39.86,159733.0,-54755.0,208610.0,3683.41,-4.06,56.0,X-MC,1.65,62.0,-0.34,1.38,18.00,XY25,ATH,FMCG
23,DMART,-0.40,-3.39,34.16,29.60,82369.0,-8472.0,241128.0,5391.45,-18.53,44.0,X-LC,1.68,14.0,-0.10,1.60,10.22,X40N,ATH,FMCG
1,ABBOTINDIA,-0.10,-6.05,22.80,15.37,38311.0,-10825.0,168030.0,34390.26,-20.15,72.0,X-MC,2.51,58.0,-0.28,1.11,13.82,X40,ATH,PHARMA
17,CIPLA,1.26,14.20,16.84,33.43,29456.0,21753.0,174914.0,1648.14,-11.50,47.0,X-LC,2.97,18.0,0.74,1.16,19.41,X40N,ATH,PHARMA

In [19]:
# top 5 to accumulate based on lowest Gained%
df_tmp = df_portfolio_features[df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])].sort_values(by = 'Gained%', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
65,RELIANCE,0.46,-17.96,52.74,25.30,86948.0,-36101.0,164862.0,1952.00,-20.03,42.0,X-LC,7.68,21.0,-0.42,1.09,1.53,XY25,BTT,REFINERIES
35,HDFCLIFE,0.74,-9.22,46.19,32.71,62812.0,-13813.0,135987.0,811.41,-29.12,42.0,X-LC,15.72,31.0,-0.22,0.90,2.16,X40,ATH,INSURANCE
47,ITC,0.76,-25.34,59.46,19.06,151011.0,-86195.0,253971.0,452.00,-59.16,49.0,X-LC,12.49,1.0,-0.57,1.68,2.87,X40,NTT,FMCG
58,PGHH,-0.11,-32.75,96.30,32.01,138279.0,-69928.0,143592.0,17616.87,-54.51,50.0,X-MC,19.79,57.0,-0.51,0.95,2.91,X40,ATH,FMCG
34,HDFCBANK,-0.60,-11.14,44.45,28.37,92779.0,-26158.0,208727.0,1073.00,-24.48,34.0,X-LC,10.60,26.0,-0.28,1.38,3.22,X40,BTT,BANKS

In [20]:
# top 5 to accumulate based on lowest CurrAlloc%
df_tmp = df_portfolio_features[df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])].sort_values(by = 'CurrAlloc%', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
10,BATAINDIA,2.03,-55.49,203.79,35.20,116702.0,-71404.0,57266.0,2096.00,-24.91,50.0,X-SC,17.54,91.0,-0.61,0.38,13.57,X40,NTT,FOOTWEAR
64,RELAXO,1.73,-47.81,191.85,52.31,145336.0,-69405.0,75755.0,1176.00,-44.44,54.0,X-SC,10.79,92.0,-0.48,0.50,69.38,X40N,NTT,FOOTWEAR
60,QUESS,-0.76,21.15,43.53,73.90,56321.0,22592.0,129385.0,424.00,-34.99,65.0,X-SC,34.44,80.0,0.40,0.86,76.38,XY24,NTT,MISC
35,HDFCLIFE,0.74,-9.22,46.19,32.71,62812.0,-13813.0,135987.0,811.41,-29.12,42.0,X-LC,15.72,31.0,-0.22,0.90,2.16,X40,ATH,INSURANCE
28,GODREJCP,0.09,-5.18,38.65,31.47,54463.0,-7700.0,140914.0,1469.04,-0.30,51.0,X-LC,6.12,32.0,-0.14,0.93,8.12,X40N,ATH,FMCG

In [21]:
# top 5 to accumulate based on CumlRnk
df_tmp = df_portfolio_features.sort_values(by = 'CumlRnk', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
47,ITC,0.76,-25.34,59.46,19.06,151011.0,-86195.0,253971.0,452.00,-59.16,49.0,X-LC,12.49,1.0,-0.57,1.68,2.87,X40,NTT,FMCG
79,TCS,0.51,-33.82,87.67,24.20,268783.0,-156688.0,306585.0,4230.71,-43.95,60.0,X-LC,19.03,2.0,-0.58,2.03,14.33,X40,ATH,IT
45,INFY,-0.62,-29.14,89.45,34.24,198321.0,-91176.0,221712.0,1972.00,-44.12,42.0,X-LC,20.61,3.0,-0.46,1.47,5.64,X40,NTT,IT
81,TMPV,-0.15,-26.29,85.30,36.58,223723.0,-93563.0,262278.0,600.00,-84.72,33.0,X-LC,7.56,4.0,-0.42,1.74,10.23,XY24,NTT,AUTO
59,PIDILITIND,0.43,11.32,5.56,17.52,8734.0,15980.0,157090.0,1658.32,-22.05,53.0,X-LC,8.04,5.0,1.83,1.04,24.23,X40,ATH,CHEMICALS

In [22]:
# top 5 for average up
df_tmp = df_portfolio_features[(df_portfolio_features['Dev%_200'] > 5)].sort_values(by = 'CurrAlloc%', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
44,INDUSINDBK,-0.94,-26.46,80.71,32.89,45823.0,-20432.0,56775.0,1800.00,-367.51,52.0,L-MC,13.42,258.0,-0.45,0.38,39.97,XR,NTT,BANKS
64,RELAXO,1.73,-47.81,191.85,52.31,145336.0,-69405.0,75755.0,1176.00,-44.44,54.0,X-SC,10.79,92.0,-0.48,0.50,69.38,X40N,NTT,FOOTWEAR
3,ALKYLAMINE,-1.25,-23.79,152.63,92.54,117446.0,-24015.0,76948.0,4520.85,-18.40,46.0,H-SC,12.08,142.0,-0.20,0.51,46.12,SR,ATH,CHEMICALS
83,TTKPRESTIG,-0.37,-16.37,19.69,0.09,16595.0,-16498.0,84279.0,770.00,95.52,58.0,M-SC,11.27,250.0,-0.99,0.56,50.07,OX40N,NTT,DURABLES
72,SIS,-0.26,0.49,20.67,21.26,23063.0,543.0,111575.0,528.00,2664.77,57.0,H-SC,24.31,168.0,0.02,0.74,65.90,OX40N,NTT,MISC

In [23]:
# top 5 RSP
df_tmp = df_portfolio_features.sort_values(by = 'RSP', ascending=False)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
60,QUESS,-0.76,21.15,43.53,73.90,56321.0,22592.0,129385.0,424.00,-34.99,65.0,X-SC,34.44,80.0,0.40,0.86,76.38,XY24,NTT,MISC
73,SONACOMS,-0.25,24.20,11.66,38.69,14650.0,24482.0,125641.0,801.69,-1.57,74.0,M-MC,26.20,193.0,1.67,0.83,78.25,AR,ATH,AUTO
33,HCLTECH,2.11,-17.52,45.82,20.28,91432.0,-42377.0,199547.0,1853.42,-13.15,69.0,X-LC,16.58,8.0,-0.46,1.32,24.15,X40,ATH,IT
77,TANLA,-3.03,-32.22,220.52,117.25,404707.0,-87237.0,183524.0,1922.32,-31.42,62.0,H-SC,6.31,147.0,-0.22,1.21,60.68,AR,ATH,IT
22,DIXON,0.12,0.87,36.73,37.92,96627.0,2276.0,263074.0,18931.72,-57.11,60.0,X-MC,7.78,54.0,0.02,1.74,43.14,X40N,ATH,IT

In [24]:
# Top N allocation
df_tmp = df_portfolio_features.sort_values(by = 'CurrAlloc%', ascending=False)
top_n_values = [10, 25, 50]

sum_df = pd.DataFrame({
    'Top_N': top_n_values,
    'Sum_Alloc%': [df_tmp['CurrAlloc%'].head(n).sum() for n in top_n_values]
})

sum_df

   Top_N  Sum_Alloc%
0     10       19.29
1     25       42.35
2     50       72.76

In [25]:
# market-cap-wise allocation
df_tmp = df_portfolio_features[cols]
df_tmp.groupby(df_tmp['Conviction'].str[-2:])['CurrAlloc%'].sum().sort_values(ascending=False)

Conviction
SC    43.43
LC    30.16
MC    26.45
Name: CurrAlloc%, dtype: float64

In [26]:
# criteria-wise allocation
df_portfolio_features.groupby('Criteria')['CurrAlloc%'].sum().sort_values(ascending=False)

Criteria
XY24     27.37
X40      24.89
X40N     17.40
XR        8.91
OX40N     7.03
AR        7.02
XY25      6.53
SR        0.89
Name: CurrAlloc%, dtype: float64

In [27]:
# conviction-wise allocation
df_portfolio_features.groupby('Conviction')['CurrAlloc%'].sum().sort_values(ascending=False)

Conviction
X-LC    28.13
H-SC    22.82
X-MC    21.23
X-SC    10.15
M-SC     9.92
H-MC     2.69
M-MC     2.15
H-LC     1.22
M-LC     0.81
L-SC     0.54
L-MC     0.38
Name: CurrAlloc%, dtype: float64

In [28]:
# sector-wise stats
df_tmp = df_portfolio_features.groupby('Category')[['CurrAlloc%', 'Current', 'Current P/L', 'FTT Amt']].sum().sort_values(by=['Current', 'Current P/L'], ascending=False)
df_tmp['Current P/L%'] = round(df_tmp['Current P/L'] * 100 / df_tmp['Current'], 2)
df_tmp['FTT%'] = round(df_tmp['FTT Amt'] * 100 / df_tmp['Current'], 2)
cols = ['CurrAlloc%', 'Current P/L%', 'FTT%']
df_tmp[cols].sort_values(by=['CurrAlloc%'], ascending=False)

               CurrAlloc%  Current P/L%    FTT%
Category
FMCG                14.33        -22.22   65.09
FINANCE             11.38         -7.26   53.74
IT                  10.27        -44.99  116.74
MISC                 7.29        -21.90   74.21
AUTO                 6.62         -9.58   50.45
BANKS                5.47         -9.80   60.53
PAINTS               5.36        -21.73   42.49
INSURANCE            5.24         -4.65   39.95
PHARMA               5.22          6.11   22.30
ELECTRICAL           4.17        -12.41   51.95
CHEMICALS            2.14        -25.44   99.48
HEALTHCARE           2.12        -11.75   40.92
APPARELS             1.87          4.80   27.17
AC                   1.81        -16.74   48.39
FOOTWEAR             1.70        -72.34  141.44
BREWERIES            1.67          7.22   12.05
DURABLES             1.62        -58.54   97.11
REALTY               1.61          8.97    5.98
TRAVEL               1.51        -96.17  194.39
CERAMICS             1.40        -45.61   89.85
ENGINEERING          1.24        -29.62   88.91
CABLES               1.24         20.96   64.34
JEWELLERY            1.10        -93.14  160.24
REFINERIES           1.09        -21.90   52.74
CEMENT               1.06        -66.63  191.30
ENTERTAINMENT        0.72        -78.85  185.51
TEXTILES             0.41        -48.69   91.08
HOTELS               0.38        -95.57  164.55

In [29]:
# money to be made criteria-wise
df_portfolio_features.groupby('Criteria')['FTT Amt'].agg(['sum', 'count']).sort_values(by='sum', ascending=False)

                sum  count
Criteria
XY24      3465509.0     21
X40       1903204.0     19
XR        1331988.0     13
AR        1112175.0      9
X40N      1090194.0     13
OX40N      731498.0     10
XY25       450092.0      5
SR         283786.0      2

In [30]:
# money to be made conviction-wise
df_portfolio_features.groupby('Conviction')['FTT Amt'].agg(['sum', 'count']).sort_values(by='sum', ascending=False)

                  sum  count
Conviction
H-SC        3324341.0     24
X-LC        2021849.0     21
X-MC        1506763.0     15
M-SC        1421472.0     14
X-SC        1268722.0      9
H-MC         291270.0      2
L-SC         209240.0      2
M-LC         168804.0      1
M-MC          61069.0      2
H-LC          49093.0      1
L-MC          45823.0      1

In [31]:
# money to be made criteria and conviction-wise
df_portfolio_features.groupby(['Conviction', 'Criteria'])['FTT Amt'].agg(['sum', 'count']).sort_values(by='sum', ascending=False)

                           sum  count
Conviction Criteria
X-LC       X40       1040907.0     10
H-SC       XY24      1021614.0      6
           AR         932930.0      5
M-SC       XY24       833669.0      6
H-SC       XR         785098.0      7
X-SC       XY24       745731.0      4
X-MC       X40        651089.0      7
X-LC       X40N       399474.0      6
X-MC       X40N       378937.0      4
X-LC       XY24       374480.0      2
M-SC       OX40N      316884.0      5
X-SC       X40N       311783.0      3
H-SC       OX40N      300913.0      4
           SR         283786.0      2
H-MC       XY24       252311.0      1
X-MC       XY25       239033.0      2
           XY24       237704.0      2
X-SC       X40        211208.0      2
M-SC       XR         194376.0      2
M-LC       XR         168804.0      1
X-LC       XY25       164640.0      2
L-SC       OX40N      113701.0      1
           XR          95539.0      1
M-SC       AR          76543.0      1
H-LC       AR          49093.0      1
M-MC       XY25        46419.0      1
L-MC       XR          45823.0      1
X-LC       XR          42348.0      1
H-MC       AR          38959.0      1
M-MC       AR          14650.0      1

In [32]:
# notebook execution time

end_time = time.time()
execution_time = round(end_time - start_time, 0)
print(f"Notebook execution time: {execution_time} seconds")

Notebook execution time: 65.0 seconds