<a href="https://colab.research.google.com/github/ankit-rathi/Quantvesting_v2/blob/main/myStocks_Portfolio_Analysis.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
'''
!pip install pandas==2.2.2 -qq
!pip install pyxirr -qq
!pip install ta -qq
!pip install yfinance==0.2.59 -qq
'''

'\n!pip install pandas==2.2.2 -qq\n!pip install pyxirr -qq\n!pip install ta -qq\n!pip install yfinance==0.2.59 -qq\n'

In [2]:
# import libraries

import numpy as np
import pandas as pd
import datetime
import warnings
warnings.filterwarnings('ignore')
import yfinance as yfin
import ta
import matplotlib.pyplot as plt
import requests

In [3]:
# notebook start time
import time
import datetime
import pytz

start_time = time.time()

# function to print date timestamp
def print_date_time():
  tz_NY = pytz.timezone('Asia/Kolkata')
  datetime_NY = datetime.datetime.now(tz_NY)
  print("Run date time (IST):", datetime_NY.strftime("%Y-%m-%d %H:%M:%S"))

In [4]:
# function to get booked and reserved amount
def get_amt():
  # fetch the JSON data from the URL
  url = "https://raw.githubusercontent.com/ankit-rathi/Tradevesting_v1/main/data/myPortfolioAmts.json"
  response = requests.get(url)
  pf_amts = response.json()  # parse the JSON data

  # extract values from the JSON
  py_booked_amt_dm = pf_amts["py_booked_amt_dm"]
  py_booked_amt_sv = pf_amts["py_booked_amt_sv"]
  cy_booked_amt_dm = pf_amts["cy_booked_amt_dm"]
  cy_booked_amt_sv = pf_amts["cy_booked_amt_sv"]
  reserve_amt_dm = pf_amts["reserve_amt_dm"]
  reserve_amt_sv = pf_amts["reserve_amt_sv"]

  # perform calculations
  py_booked_amt = py_booked_amt_dm + py_booked_amt_sv
  cy_booked_amt = cy_booked_amt_dm + cy_booked_amt_sv
  reserve_amt = reserve_amt_dm + reserve_amt_sv
  total_booked_amt = py_booked_amt + cy_booked_amt

  return total_booked_amt, reserve_amt, cy_booked_amt, py_booked_amt

gen_output = 0

In [5]:
# function to format the amount
def format_amt(number):
    abs_number = abs(number)

    if abs_number >= 1_00_00_000:  # Crores
        formatted_amt = f"{number / 1_00_00_000:.2f} C"
    elif abs_number >= 1_00_000:  # Lakhs
        formatted_amt = f"{number / 1_00_000:.2f} L"
    elif abs_number >= 1_000:  # Thousands
        formatted_amt = f"{number / 1_000:.2f} K"
    else:
        formatted_amt = f"{number:.2f}"

    return formatted_amt

# function to set start and end date
def get_start_end_date():
  start_date = (datetime.date.today() + datetime.timedelta(days=-365)).strftime('%Y-%m-%d')
  end_date = (datetime.date.today() + datetime.timedelta(days=1)).strftime('%Y-%m-%d')
  return start_date, end_date

# function to fetch my portfolio csv
def get_mypfs_df():
  mypfs_df = pd.read_csv('https://raw.githubusercontent.com/ankit-rathi/Tradevesting_v1/main/data/myPortfolioStocks.csv')
  return mypfs_df

# function to fetch my prospects csv
def get_mypps_df():
  mypps_df = pd.read_csv('https://raw.githubusercontent.com/ankit-rathi/Tradevesting_v1/main/data/myProspectsScrips.csv')
  return mypps_df

# function to fetch screener data
def get_myscreen_df():
  myscreen_df = pd.read_csv('https://raw.githubusercontent.com/ankit-rathi/Tradevesting_v1/main/data/myScreenerDB.csv')
  return myscreen_df

# function to fetch momentum data
def get_myinvmt_df():
  myinvmt_df = pd.read_csv('https://raw.githubusercontent.com/ankit-rathi/Tradevesting_v1/main/data/myInvestments.csv')
  return myinvmt_df

# function to get the stock ids
def get_stock_ids(df_pf):
  stock_n100 = df_pf['Symbol'].unique()

  exclude = ['CADILAHC','MMTC', 'MASFIN']

  stock_ids = df_pf[~df_pf['Symbol'].isin(exclude) ]['Symbol'].unique()

  #mypf = mypf[mypf.Forecast.notnull()]
  #stock_ids = mypf['Symbol'].unique()

  #stock_ids.sort()
  return stock_ids

# get features from screener data
def get_screener_features():
  myscreen_df = get_myscreen_df()
  cols = ['Symbol', 'EPS', 'MedPE', 'ROCE%', 'ROE%', 'CapType']
  return myscreen_df[cols]

# get relative strength
def get_relative_strength(stock_list):

    # Dictionary to store stock tickers and their corresponding percentage price change
    stock_changes = {}

    # Loop through each stock and fetch its price data
    for stock in stock_list:
        try:
            # Download the stock data for the given date range
            stock_data = yfin.Ticker(stock + '.NS').history(period='1mo', interval='1d')[map(str.title, ['open', 'close', 'low', 'high', 'volume'])]

            # Calculate the percentage change for the stock
            if len(stock_data) > 0:
                start_price = stock_data['Close'].iloc[0]
                end_price = stock_data['Close'].iloc[-1]
                percent_change = round(((end_price - start_price) / start_price) * 100, 2)
                stock_changes[stock] = percent_change
            else:
                stock_changes[stock] = np.nan  # If no data is available, set to NaN

        except Exception as e:
            print(f"Error fetching data for {stock}: {e}")
            stock_changes[stock] = np.nan

    # Create a DataFrame with stock tickers and their percentage changes
    df = pd.DataFrame(list(stock_changes.items()), columns=['Symbol', 'Percent_Change'])

    # Drop any stocks with missing data (NaN values)
    df = df.dropna()

    # Calculate the percentile rank based on percentage change
    df['RSP'] = round(df['Percent_Change'].rank(pct=True) * 100, 2)
    cols = ['Symbol', 'RSP']
    df = df[cols]
    # Sort by percentile rank (optional)
    df = df.sort_values(by='RSP', ascending=False).reset_index(drop=True)

    return df

In [6]:
# function to get stock technicals
def stock_prec_dev(stock_symbol):
    #stock_symbol = 'ULTRACEMCO.NS'
    short_window = 20
    mid_window = 50
    long_window = 200
    moving_avg = 'SMA'

    start = datetime.datetime(*map(int, start_date.split('-')))
    end = datetime.datetime(*map(int, end_date.split('-')))

    stock_df = yfin.Ticker(stock_symbol + '.NS').history(period='max', interval='1d')[map(str.title, ['open', 'close', 'low', 'high', 'volume'])]

    stock_df['Max'] = round(max(stock_df['Close']),2)
    stock_df = stock_df[(stock_df.index <= end_date) & (stock_df.index >= start_date)]
    stock_df['200_SMA'] = round(stock_df['Close'].rolling(window = 200, min_periods = 1).mean(),0)
    stock_df['Dev%_200'] = round((stock_df['Close'] - stock_df['200_SMA'])*100/stock_df['200_SMA'],2)
    stock_df.dropna(axis = 0, inplace = True) # remove any null rows

    stock_df['20_SMA'] = stock_df['Close'].rolling(window=20).mean()
    stock_df['50_SMA'] = stock_df['Close'].rolling(window=50).mean()
    stock_df['Symbol'] = stock_symbol

    stock_df['Close'] = round(stock_df['Close'],2)
    stock_df['Min'] = round(min(stock_df['Close']),2)
    stock_df['RSI_14'] = ta.momentum.RSIIndicator(close=stock_df['Close'], window=14).rsi()
    stock_df['RSI_14'] = round(stock_df['RSI_14'],0)
    stock_df['Prev_Close'] = stock_df['Close'].shift(1)
    stock_df.drop(['Open', 'Low', 'High', 'Volume'], axis=1, inplace=True)
    stock_df = stock_df.tail(1)

    max_SMA = max(stock_df['20_SMA'].item(), stock_df['50_SMA'].item(), stock_df['200_SMA'].item())
    min_SMA = min(stock_df['20_SMA'].item(), stock_df['50_SMA'].item(), stock_df['200_SMA'].item())
    ABS_Spread = max_SMA - min_SMA
    stock_df['Spread%'] = round((ABS_Spread / stock_df['200_SMA'].item()) * 100,2)

    return stock_df

# function to compute stock attributes
def get_common_features(stock_ids, df_mypf):

  df_prec_dev = pd.DataFrame()
  df_tmp = get_screener_features()
  df_rs = get_relative_strength(stock_ids)

  for stock_id in stock_ids:
      tmp = stock_prec_dev(stock_id)
      tmp = tmp.reset_index()
      df_prec_dev = pd.concat([df_prec_dev, tmp], ignore_index = True)
  df_prec_dev = pd.merge(df_prec_dev, df_mypf, on= 'Symbol')
  df_prec_dev = pd.merge(df_prec_dev, df_tmp, on= 'Symbol', how='left')
  df_prec_dev = pd.merge(df_prec_dev, df_rs, on= 'Symbol', how='left')
  #print(df_prec_dev.columns)
  df_prec_dev['Curr_PE'] = round(df_prec_dev['Close']/df_prec_dev['EPS'],1)
  df_prec_dev['Dev%_PE'] = round((df_prec_dev['Curr_PE'] - df_prec_dev['MedPE'])*100/df_prec_dev['MedPE'],2)
  df_prec_dev['Conviction'] = df_prec_dev['Conviction'] + '-' + df_prec_dev['CapType']
  return df_prec_dev

# function to arrange stock features
def arrange_features(df_stocks, common_cols, diff_cols):
  df_stocks_common = df_stocks[common_cols].drop_duplicates()
  df_stocks_diff = df_stocks[diff_cols]
  df_stocks_diff['Investment'] = df_stocks_diff['AvgCost'] * df_stocks_diff['Shares']
  df_stocks_diff = df_stocks_diff.groupby(['Symbol'])[['Shares', 'Investment']].aggregate(['sum']).reset_index()
  df_stocks_diff.columns = ['Symbol', 'Shares', 'Investment']
  df_stocks_diff['AvgCost'] = round(df_stocks_diff['Investment']/df_stocks_diff['Shares'],2)
  df_stocks = pd.merge(df_stocks_diff, df_stocks_common, on='Symbol')
  return df_stocks

# plot fact distribution across dimension
def plot_pie_chart(df, dimension, fact):
  # grouping the data by category and calculating the sum of fact for each type
  grouped_data = df.groupby(dimension)[fact].sum()

  # sorting the grouped data in descending order
  grouped_data = grouped_data.sort_values(ascending=False)

  # creating a pie chart
  grouped_data.plot.pie(autopct='%1.1f%%', startangle=90, figsize=(6, 6))

  # adding a title and displaying the plot
  plt.title(f'{dimension} {fact} Distribution')
  plt.ylabel('')  # To hide the y-label
  plt.show()

In [7]:
# function to get portfolio features

def get_portfolio_features(df_common_features):

  print_date_time()
  print('-------------------')

  #df_common_features["Target"] = df_common_features["Target"].fillna(df_common_features["Max"])
  df_common_features['NTT'] = np.where(df_common_features['Strategy']== 'NTT', df_common_features["Target"], df_common_features['Max'])
  df_common_features['LTT'] = np.where(df_common_features['Strategy']== 'BTT', df_common_features["Target"], df_common_features['Max'])
  df_common_features['BOL'] = df_common_features['Min']

  tmp_df = df_common_features[df_common_features['Symbol'].isin(mypf_df[mypf_df['InPortfolio'] != 'NA'].Symbol.values)]
  print('qualified stocks: '+str(len(tmp_df['Symbol'].unique())))
  tmp_df1 = tmp_df[tmp_df['LatestQtr'] == 1]
  print('with latest results: '+str(len(tmp_df1['Symbol'].unique())))
  tmp_df1 = tmp_df1[tmp_df1['StarStock'] == 1]
  print('still star stocks: '+str(len(tmp_df1['Symbol'].unique())))
  tmp_df['Investment'] = tmp_df['AvgCost'] * tmp_df['Shares']
  tmp_df['Current'] = round(tmp_df['Close'] * tmp_df['Shares'],0)
  tmp_df['Previous'] = tmp_df['Prev_Close'] * tmp_df['Shares']
  tmp_df['EstimatedST'] = tmp_df['NTT'] * tmp_df['Shares']
  tmp_df['EstimatedLT'] = tmp_df['LTT'] * tmp_df['Shares']
  tmp_df['Current P/L'] = round((tmp_df['Current'] - tmp_df['Investment']),0)
  tmp_df['Today P/L%'] = round((tmp_df['Current'] - tmp_df['Previous'])*100/tmp_df['Previous'],2)
  tmp_df['Current P/L%'] = round((tmp_df['Current'] - tmp_df['Investment'])*100/tmp_df['Investment'],2)
  tmp_df['EstimatedST P/L%'] = round((tmp_df['EstimatedST'] - tmp_df['Investment'])*100/tmp_df['Investment'],2)
  tmp_df['EstimatedLT P/L%'] = round((tmp_df['EstimatedLT'] - tmp_df['Investment'])*100/tmp_df['Investment'],2)
  tmp_df['NTT%'] = round((tmp_df['NTT'] - tmp_df['Close'])*100/tmp_df['Close'],2)
  tmp_df['LTT%'] = round((tmp_df['LTT'] - tmp_df['Close'])*100/tmp_df['Close'],2)
  tmp_df['Gained%'] = round((tmp_df['Close'] - tmp_df['BOL'])*100/tmp_df['BOL'],2)
  investment = round(sum(tmp_df['AvgCost']*tmp_df['Shares']),0)
  current = round(sum(tmp_df['Close']*tmp_df['Shares']),0)
  tmp_df['InitAlloc%'] = round(tmp_df['Investment']*100/investment,2)
  tmp_df['CurrAlloc%'] = round(tmp_df['Current']*100/current,2)
  tmp_df['FTT'] = tmp_df['LTT']
  tmp_df.loc[tmp_df['Strategy'] == 'NTT', 'FTT'] = tmp_df['NTT']
  tmp_df['FTT%'] = tmp_df['LTT%']
  tmp_df.loc[tmp_df['Strategy'] == 'NTT', 'FTT%'] = tmp_df['NTT%']
  tmp_df['FTT Amt'] = round(tmp_df['FTT%'] * tmp_df['Current']/100,0)
  tmp_df['OTT%'] = round((tmp_df['FTT'] - tmp_df['AvgCost'])*100/tmp_df['AvgCost'],2)
  tmp_df['RRR Ind'] = round(tmp_df['Current P/L']/tmp_df['FTT Amt'],2)
  tmp_df['Risk Ind'] = round(tmp_df['Current P/L%']*tmp_df['CurrAlloc%'],0)

  return tmp_df

# function to print portfolio features
def print_portfolio_stats(df_portfolio_features, myinvmt_df):
  from pyxirr import xirr

  total_booked_amt, reserve_amt, cy_booked_amt, py_booked_amt = get_amt()

  dates = myinvmt_df['Date'].values
  dates = np.append(dates, datetime.date.today().strftime('%d-%b-%y'))
  investment = myinvmt_df['Investment'].values
  dates= pd.to_datetime(dates)

  current = round(sum(df_portfolio_features['Close']*df_portfolio_features['Shares']),0) + reserve_amt
  investment_xirr = np.append(investment, current)
  cagr = round(xirr(pd.DataFrame({"dates": dates, "amounts": investment_xirr}))*100,2)

  investment = -sum(investment)
  invested = round(sum(df_portfolio_features['AvgCost']*df_portfolio_features['Shares']),0) + reserve_amt
  previous = round(sum(df_portfolio_features['Prev_Close']*df_portfolio_features['Shares']),0) + reserve_amt
  cy_invested = investment + py_booked_amt

  today_pnl_amount = current-previous
  today_pnl_percentage = round((current-previous)*100/previous,2)

  curr_pnl_amount = current-invested
  curr_pnl_percentage = round((curr_pnl_amount)*100/(cy_invested),2)

  cy_pnl_amount = cy_booked_amt + curr_pnl_amount
  cy_pnl_percentage = round((cy_pnl_amount)*100/cy_invested,2)

  overall_pnl_amount = total_booked_amt + curr_pnl_amount
  overall_pnl_percentage = round((overall_pnl_amount)*100/investment,2)

  estimate_st = round(sum(df_portfolio_features['FTT']*df_portfolio_features['Shares']),0)  + reserve_amt
  est_st_pnl_amount = estimate_st-current
  est_st_pnl_percentage = round((est_st_pnl_amount)*100/current,2)

  estimate_lt = round(sum(df_portfolio_features['LTT']*df_portfolio_features['Shares']),0)  + reserve_amt
  est_lt_pnl_amount = estimate_lt-current
  est_lt_pnl_percentage = round((est_lt_pnl_amount)*100/current,2)

  total_profit = round(sum(df_portfolio_features[df_portfolio_features['Current P/L%'] > 0]['Current']) - sum(df_portfolio_features[df_portfolio_features['Current P/L%'] > 0]['Investment']),0)
  total_loss = round(sum(df_portfolio_features[df_portfolio_features['Current P/L%'] < 0]['Current']) - sum(df_portfolio_features[df_portfolio_features['Current P/L%'] < 0]['Investment']),0)

  cy_booked_percentage = round((cy_booked_amt)*100/current,2)
  py_booked_percentage = round((py_booked_amt)*100/investment,2)
  total_booked_percentage = round((total_booked_amt)*100/investment,2)

  print('-------------------')
  print('Initial Investment: ', format_amt(investment))
  print('CY Investment: ', format_amt(cy_invested))
  print('Reserve: ', format_amt(reserve_amt))
  print('Current: ',  format_amt(current))
  print('-------------------')
  print('Today PnL: '+ '{} ({}%)'.format(format_amt(today_pnl_amount), today_pnl_percentage))
  print('Current PnL: '+ '{} ({}%)'.format(format_amt(curr_pnl_amount), curr_pnl_percentage))
  print('CY Booked + Current PnL: '+ '{} ({}%)'.format(format_amt(cy_pnl_amount), cy_pnl_percentage))
  print('-------------------')
  print('Total profit: ', format_amt(total_profit))
  print('Total loss: ', format_amt(total_loss))
  print('-------------------')
  print('Total Booked + Current PnL: '+ '{} ({}%)'.format(format_amt(overall_pnl_amount), overall_pnl_percentage))
  print('Total Booked PnL: '+ '{} ({}%)'.format(format_amt(total_booked_amt), total_booked_percentage))
  print('Curr Year Booked PnL: '+ '{} ({}%)'.format(format_amt(cy_booked_amt), cy_booked_percentage))
  print('Prev Year Booked PnL: '+ '{} ({}%)'.format(format_amt(py_booked_amt), py_booked_percentage))
  print('===================')
  print('Est FTT: ',  format_amt(estimate_st))
  print('Est FTT PnL: '+ '{} ({}%)'.format(format_amt(est_st_pnl_amount), est_st_pnl_percentage))

  print('===================')
  print('Deployed: ', format_amt(investment))

  print('Current: ', format_amt(current))

  print('CAGR/XIRR %: '+'{}%'.format(cagr))

In [8]:
# get start and end date
start_date, end_date = get_start_end_date()

# get portfolio and prospects data
mypfs_df = get_mypfs_df()
mypps_df = get_mypps_df()
myinvmt_df = get_myinvmt_df()

# merge above datasets
mypf_df = pd.merge(mypfs_df, mypps_df, on="Symbol")

# seggregate dm and sv portfolio
dm_pf = mypf_df[mypf_df['InPortfolio'] == 'DM']
sv_pf = mypf_df[mypf_df['InPortfolio'] == 'SV']

# build portfolio stock dataframe
dm_stocks = get_stock_ids(dm_pf)
sv_stocks = get_stock_ids(sv_pf)
df_stocks = pd.concat([dm_pf,sv_pf], ignore_index = True)

# arrange common and diff stock features
common_cols = ['Symbol', 'Target', 'Criteria', 'Strategy', 'CumlRnk', 'LatestQtr', 'StarStock', 'Conviction', 'Category', 'InFolio', 'XIRR', 'MBQ']
diff_cols = ['Symbol', 'AvgCost', 'Shares']
df_stocks = arrange_features(df_stocks, common_cols, diff_cols)

# get common features
stock_ids = df_stocks['Symbol'].values
df_common_features = get_common_features(stock_ids, df_stocks)

df_common_features.reset_index(drop=True, inplace=True)
df_common_features.drop(['Date'], axis=1, inplace=True)
# get and print portfolio features
df_portfolio_features = get_portfolio_features(df_common_features)

print_portfolio_stats(df_portfolio_features, myinvmt_df)

df = df_portfolio_features
#plot_pie_chart(df, 'CapType', 'Current')
list_ox40n = list(df[df['MBQ'].str.contains('OX40N', na=False)]['Symbol'].values)

Run date time (IST): 2026-07-08 10:50:58
-------------------
qualified stocks: 92
with latest results: 31
still star stocks: 20
-------------------
Initial Investment:  1.40 C
CY Investment:  1.82 C
Reserve:  1.49 K
Current:  1.53 C
-------------------
Today PnL: -1.16 L (-0.75%)
Current PnL: -30.60 L (-16.78%)
CY Booked + Current PnL: -28.52 L (-15.64%)
-------------------
Total profit:  4.57 L
Total loss:  -35.17 L
-------------------
Total Booked + Current PnL: 14.35 L (10.29%)
Total Booked PnL: 44.95 L (32.22%)
Curr Year Booked PnL: 2.08 L (1.36%)
Prev Year Booked PnL: 42.87 L (30.73%)
===================
Est FTT:  2.55 C
Est FTT PnL: 1.02 C (67.13%)
===================
Deployed:  1.40 C
Current:  1.53 C
CAGR/XIRR %: 4.09%

In [9]:
# top 5 near their targets
cols = ['Symbol', 'Today P/L%', 'Current P/L%', 'FTT%', 'OTT%', 'FTT Amt', 'Current P/L', 'Current', 'FTT', 'Dev%_PE', 'RSI_14','Conviction', 'Spread%',  'CumlRnk', 'RRR Ind', 'CurrAlloc%', 'Gained%', 'Criteria', 'Strategy', 'Category']
df_tmp = df_portfolio_features[~df_portfolio_features['Symbol'].isin(['ENRIN','BLUSPRING','DIGITIDE'])]
df_tmp = df_tmp.sort_values(by = 'FTT Amt', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
59,PIDILITIND,-0.98,13.46,4.33,18.37,6932.0,18990.0,160100.0,1670.26,-20.49,64.0,X-LC,7.76,5.0,2.74,1.05,25.71,X40,ATH,CHEMICALS
68,SATIN,0.21,46.20,3.85,51.83,15551.0,127640.0,403924.0,274.00,31.41,70.0,H-SC,41.60,159.0,8.21,2.65,96.77,XY24,NTT,FINANCE
49,JSWINFRA,-1.14,9.04,6.77,16.43,16372.0,20052.0,241826.0,342.00,-6.40,60.0,X-MC,11.74,61.0,1.22,1.59,37.11,X40N,NTT,REALTY
83,TTKPRESTIG,0.65,-18.03,22.12,0.09,18272.0,-18175.0,82602.0,770.00,91.68,70.0,M-SC,5.27,250.0,-0.99,0.54,47.08,OX40N,NTT,DURABLES
55,MASFIN,0.86,-1.42,23.32,21.57,22524.0,-1395.0,96585.0,397.04,-15.09,59.0,H-SC,1.62,167.0,-0.06,0.63,15.13,XR,ATH,FINANCE

In [10]:
# top 5 today
df_tmp = df_portfolio_features.sort_values(by = 'Today P/L%', ascending=False)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
85,VAIBHAVGBL,7.05,-22.55,107.58,60.77,152288.0,-41217.0,141558.0,521.00,63.09,66.0,H-SC,3.67,160.0,-0.27,0.93,44.02,XR,NTT,JEWELLERY
3,ALKYLAMINE,6.72,-18.39,135.93,92.54,112002.0,-18566.0,82397.0,4520.85,-12.57,63.0,H-SC,9.42,142.0,-0.17,0.54,56.46,SR,ATH,CHEMICALS
29,GREENPANEL,4.37,-47.50,172.63,43.14,165934.0,-86957.0,96121.0,537.00,115.12,55.0,M-SC,16.34,225.0,-0.52,0.63,15.46,XY24,NTT,MISC
39,ICICIGI,2.72,-2.85,22.38,18.89,43508.0,-5705.0,194404.0,2244.41,-18.36,58.0,X-MC,4.49,66.0,-0.13,1.27,8.99,X40,ATH,INSURANCE
60,QUESS,2.13,22.96,41.43,73.90,54403.0,24519.0,131312.0,424.00,-33.88,88.0,X-SC,22.04,80.0,0.45,0.86,79.01,XY24,NTT,MISC

In [11]:
# bottom 5 today
df_tmp = df_portfolio_features.sort_values(by = 'Today P/L%', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
25,FINCABLES,-3.94,32.25,57.21,107.91,111711.0,47621.0,195265.0,1641.55,18.72,42.0,M-SC,26.76,220.0,0.43,1.28,46.90,OX40N,ATH,CABLES
0,5PAISA,-3.89,-30.34,62.09,12.90,94497.0,-66302.0,152194.0,593.00,124.76,62.0,H-SC,4.79,170.0,-0.70,1.00,46.87,OX40N,NTT,FINANCE
5,ATULAUTO,-3.34,-16.10,73.50,45.57,121564.0,-31739.0,165393.0,844.00,3581.08,55.0,M-SC,3.71,248.0,-0.26,1.08,27.28,XY24,NTT,AUTO
50,KANSAINER,-3.23,-31.60,65.89,13.47,121537.0,-85212.0,184455.0,340.00,-41.24,42.0,H-SC,3.13,162.0,-0.70,1.21,30.38,XY24,NTT,PAINTS
56,MEDANTA,-3.18,11.91,13.59,27.12,26845.0,21021.0,197538.0,1486.00,8.43,58.0,X-SC,7.69,87.0,0.78,1.29,36.11,XY24,NTT,HEALTHCARE

In [12]:
# top 5 to exit based on CumlRnk
df_tmp = df_portfolio_features[~df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])]
df_tmp = df_tmp[(df_tmp['Current P/L%'] > -1) & (df_tmp['Current P/L%'] < 1)].sort_values(by = 'CumlRnk', ascending=False)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
72,SIS,1.98,-0.2,21.51,21.26,23835.0,-222.0,110810.0,528.0,2645.6,59.0,H-SC,25.05,168.0,-0.01,0.73,64.76,OX40N,NTT,MISC

In [13]:
# OX40N stocks to exit
df_tmp = df_portfolio_features[(df_portfolio_features['Symbol'].isin(list_ox40n))].sort_values(by = 'Current P/L%', ascending=False)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
25,FINCABLES,-3.94,32.25,57.21,107.91,111711.0,47621.0,195265.0,1641.55,18.72,42.0,M-SC,26.76,220.0,0.43,1.28,46.90,OX40N,ATH,CABLES
72,SIS,1.98,-0.20,21.51,21.26,23835.0,-222.0,110810.0,528.00,2645.60,59.0,H-SC,25.05,168.0,-0.01,0.73,64.76,OX40N,NTT,MISC
16,CERA,-2.37,-17.08,49.40,23.89,72058.0,-30037.0,145866.0,9475.00,-20.05,59.0,H-SC,14.77,153.0,-0.42,0.96,41.79,OX40N,NTT,CERAMICS
83,TTKPRESTIG,0.65,-18.03,22.12,0.09,18272.0,-18175.0,82602.0,770.00,91.68,70.0,M-SC,5.27,250.0,-0.99,0.54,47.08,OX40N,NTT,DURABLES
43,INDIGOPNTS,-1.30,-24.36,32.23,0.02,42555.0,-42524.0,132035.0,1408.00,101.45,63.0,M-SC,4.49,222.0,-1.00,0.87,49.80,OX40N,NTT,PAINTS

In [14]:
# top 5 to book for rotation
df_tmp = df_portfolio_features[(df_portfolio_features['Current P/L%'] > 20) ].sort_values(by = 'CumlRnk', ascending=False)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
25,FINCABLES,-3.94,32.25,57.21,107.91,111711.0,47621.0,195265.0,1641.55,18.72,42.0,M-SC,26.76,220.0,0.43,1.28,46.90,OX40N,ATH,CABLES
68,SATIN,0.21,46.20,3.85,51.83,15551.0,127640.0,403924.0,274.00,31.41,70.0,H-SC,41.60,159.0,8.21,2.65,96.77,XY24,NTT,FINANCE
91,ZYDUSLIFE,1.56,23.48,9.84,35.63,25465.0,49217.0,258791.0,1286.17,7.66,73.0,H-MC,15.19,120.0,1.93,1.70,36.07,AR,ATH,PHARMA
60,QUESS,2.13,22.96,41.43,73.90,54403.0,24519.0,131312.0,424.00,-33.88,88.0,X-SC,22.04,80.0,0.45,0.86,79.01,XY24,NTT,MISC

In [15]:
# top 5 to monitor for exit
df_tmp = df_portfolio_features[~df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])]
df_tmp = df_tmp[(df_tmp['Current P/L%'] > 0) ].sort_values(by = 'Dev%_PE', ascending=False)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
75,SURYODAY,-1.27,2.15,20.44,23.03,37390.0,3856.0,182927.0,216.00,99.56,60.0,H-SC,20.27,166.0,0.10,1.20,54.02,XR,NTT,BANKS
74,STARHEALTH,1.38,14.04,29.13,47.26,93393.0,39483.0,320606.0,761.00,79.88,70.0,H-SC,15.89,173.0,0.42,2.10,39.59,XY24,NTT,INSURANCE
68,SATIN,0.21,46.20,3.85,51.83,15551.0,127640.0,403924.0,274.00,31.41,70.0,H-SC,41.60,159.0,8.21,2.65,96.77,XY24,NTT,FINANCE
25,FINCABLES,-3.94,32.25,57.21,107.91,111711.0,47621.0,195265.0,1641.55,18.72,42.0,M-SC,26.76,220.0,0.43,1.28,46.90,OX40N,ATH,CABLES
91,ZYDUSLIFE,1.56,23.48,9.84,35.63,25465.0,49217.0,258791.0,1286.17,7.66,73.0,H-MC,15.19,120.0,1.93,1.70,36.07,AR,ATH,PHARMA

In [16]:
# top 5 to book for rotation from weak conviction
df_tmp = df_portfolio_features[~df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])]
df_tmp = df_tmp[~df_tmp['Criteria'].isin(['XY25','XY24','X40', 'X40N'])].sort_values(by = 'RRR Ind', ascending=False)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
91,ZYDUSLIFE,1.56,23.48,9.84,35.63,25465.0,49217.0,258791.0,1286.17,7.66,73.0,H-MC,15.19,120.0,1.93,1.70,36.07,AR,ATH,PHARMA
73,SONACOMS,0.69,16.27,19.28,38.69,22677.0,16459.0,117618.0,801.69,-7.91,78.0,M-MC,19.52,193.0,0.73,0.77,66.87,AR,ATH,AUTO
25,FINCABLES,-3.94,32.25,57.21,107.91,111711.0,47621.0,195265.0,1641.55,18.72,42.0,M-SC,26.76,220.0,0.43,1.28,46.90,OX40N,ATH,CABLES
75,SURYODAY,-1.27,2.15,20.44,23.03,37390.0,3856.0,182927.0,216.00,99.56,60.0,H-SC,20.27,166.0,0.10,1.20,54.02,XR,NTT,BANKS
72,SIS,1.98,-0.20,21.51,21.26,23835.0,-222.0,110810.0,528.00,2645.60,59.0,H-SC,25.05,168.0,-0.01,0.73,64.76,OX40N,NTT,MISC

In [17]:
# top 5 to accumulate based on lowest RSI_14
df_tmp = df_portfolio_features[df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])].sort_values(by = 'RSI_14', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
87,VBL,-0.80,-2.96,39.50,35.37,121066.0,-9347.0,306495.0,670.16,-14.33,33.0,X-LC,9.21,13.0,-0.08,2.01,25.97,X40N,ATH,FMCG
47,ITC,-2.41,-25.77,60.40,19.06,152506.0,-87673.0,252493.0,452.00,-59.16,36.0,X-LC,12.69,1.0,-0.57,1.66,1.73,X40,NTT,FMCG
81,TMPV,-1.23,-23.04,77.46,36.58,212133.0,-81980.0,273861.0,600.00,-83.62,36.0,X-LC,7.29,4.0,-0.39,1.80,15.09,XY24,NTT,AUTO
51,KOTAKBANK,-0.71,1.27,19.59,21.11,27471.0,1758.0,140230.0,453.24,-13.31,38.0,X-LC,4.28,12.0,0.06,0.92,7.24,X40,ATH,BANKS
23,DMART,-0.85,-2.98,33.58,29.60,81321.0,-7428.0,242172.0,5391.45,-18.18,39.0,X-LC,3.27,14.0,-0.09,1.59,10.69,X40N,ATH,FMCG

In [18]:
# top 5 to accumulate based on Spread and CumlRnk
df_tmp = df_portfolio_features[df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])]
df_tmp = df_tmp[(df_tmp['CumlRnk'] < 100)].sort_values(by = 'Spread%', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
17,CIPLA,-0.64,18.44,12.66,33.43,22965.0,28239.0,181400.0,1648.14,-8.32,66.0,X-LC,2.27,18.0,1.23,1.19,23.84,X40N,ATH,PHARMA
19,COLPAL,-1.46,-22.19,79.74,39.86,163411.0,-58435.0,204930.0,3683.41,-5.85,52.0,X-MC,3.01,62.0,-0.36,1.34,15.92,XY25,ATH,FMCG
84,UNITDSPR,-0.95,3.93,16.20,20.77,39422.0,9202.0,243346.0,1644.00,-7.86,67.0,X-MC,3.07,64.0,0.23,1.60,16.97,X40N,NTT,BREWERIES
23,DMART,-0.85,-2.98,33.58,29.60,81321.0,-7428.0,242172.0,5391.45,-18.18,39.0,X-LC,3.27,14.0,-0.09,1.59,10.69,X40N,ATH,FMCG
11,BERGEPAINT,-3.12,-6.83,34.51,25.32,82871.0,-17613.0,240136.0,680.00,-11.94,45.0,X-MC,3.55,68.0,-0.21,1.57,24.98,XY24,NTT,PAINTS

In [19]:
# top 5 to accumulate based on lowest Gained%
df_tmp = df_portfolio_features[df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])].sort_values(by = 'Gained%', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
58,PGHH,-0.19,-32.97,96.95,32.01,138755.0,-70400.0,143120.0,17616.87,-54.64,42.0,X-MC,20.90,57.0,-0.51,0.94,1.50,X40,ATH,FMCG
47,ITC,-2.41,-25.77,60.40,19.06,152506.0,-87673.0,252493.0,452.00,-59.16,36.0,X-LC,12.69,1.0,-0.57,1.66,1.73,X40,NTT,FMCG
65,RELIANCE,-1.18,-17.01,50.98,25.30,85026.0,-34179.0,166784.0,1952.00,-19.26,43.0,X-LC,7.29,21.0,-0.40,1.09,2.71,XY25,BTT,REFINERIES
35,HDFCLIFE,-0.42,-6.77,42.34,32.71,59133.0,-10138.0,139662.0,811.41,-27.21,43.0,X-LC,15.39,31.0,-0.17,0.92,4.92,X40,ATH,INSURANCE
88,VOLTAS,-0.55,-0.07,45.30,45.20,86799.0,-132.0,191610.0,1856.00,14.36,44.0,X-MC,4.97,79.0,-0.00,1.26,5.02,XY25,NTT,AC

In [20]:
# top 5 to accumulate based on lowest CurrAlloc%
df_tmp = df_portfolio_features[df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])].sort_values(by = 'CurrAlloc%', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
10,BATAINDIA,-0.51,-55.78,205.74,35.20,117068.0,-71769.0,56901.0,2096.00,-25.34,46.0,X-SC,19.75,91.0,-0.61,0.37,12.85,X40,NTT,FOOTWEAR
64,RELAXO,1.48,-48.42,195.29,52.31,146216.0,-70289.0,74871.0,1176.00,-45.12,63.0,X-SC,11.61,92.0,-0.48,0.49,67.40,X40N,NTT,FOOTWEAR
60,QUESS,2.13,22.96,41.43,73.90,54403.0,24519.0,131312.0,424.00,-33.88,88.0,X-SC,22.04,80.0,0.45,0.86,79.01,XY24,NTT,MISC
35,HDFCLIFE,-0.42,-6.77,42.34,32.71,59133.0,-10138.0,139662.0,811.41,-27.21,43.0,X-LC,15.39,31.0,-0.17,0.92,4.92,X40,ATH,INSURANCE
51,KOTAKBANK,-0.71,1.27,19.59,21.11,27471.0,1758.0,140230.0,453.24,-13.31,38.0,X-LC,4.28,12.0,0.06,0.92,7.24,X40,ATH,BANKS

In [21]:
# top 5 to accumulate based on CumlRnk
df_tmp = df_portfolio_features.sort_values(by = 'CumlRnk', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
47,ITC,-2.41,-25.77,60.40,19.06,152506.0,-87673.0,252493.0,452.00,-59.16,36.0,X-LC,12.69,1.0,-0.57,1.66,1.73,X40,NTT,FMCG
79,TCS,-0.54,-38.80,104.05,24.88,295002.0,-179754.0,283519.0,4253.91,-48.21,44.0,X-LC,21.61,2.0,-0.61,1.86,5.15,X40,ATH,IT
45,INFY,-0.49,-27.40,84.90,34.24,192862.0,-85724.0,227164.0,1972.00,-43.03,47.0,X-LC,21.08,3.0,-0.44,1.49,8.24,X40,NTT,IT
81,TMPV,-1.23,-23.04,77.46,36.58,212133.0,-81980.0,273861.0,600.00,-83.62,36.0,X-LC,7.29,4.0,-0.39,1.80,15.09,XY24,NTT,AUTO
59,PIDILITIND,-0.98,13.46,4.33,18.37,6932.0,18990.0,160100.0,1670.26,-20.49,64.0,X-LC,7.76,5.0,2.74,1.05,25.71,X40,ATH,CHEMICALS

In [22]:
# top 5 for average up
df_tmp = df_portfolio_features[(df_portfolio_features['Dev%_200'] > 5)].sort_values(by = 'CurrAlloc%', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
44,INDUSINDBK,-0.30,-24.76,76.61,32.89,44506.0,-19112.0,58094.0,1800.00,-373.11,72.0,L-MC,8.88,258.0,-0.43,0.38,43.23,XR,NTT,BANKS
64,RELAXO,1.48,-48.42,195.29,52.31,146216.0,-70289.0,74871.0,1176.00,-45.12,63.0,X-SC,11.61,92.0,-0.48,0.49,67.40,X40N,NTT,FOOTWEAR
3,ALKYLAMINE,6.72,-18.39,135.93,92.54,112002.0,-18566.0,82397.0,4520.85,-12.57,63.0,H-SC,9.42,142.0,-0.17,0.54,56.46,SR,ATH,CHEMICALS
83,TTKPRESTIG,0.65,-18.03,22.12,0.09,18272.0,-18175.0,82602.0,770.00,91.68,70.0,M-SC,5.27,250.0,-0.99,0.54,47.08,OX40N,NTT,DURABLES
72,SIS,1.98,-0.20,21.51,21.26,23835.0,-222.0,110810.0,528.00,2645.60,59.0,H-SC,25.05,168.0,-0.01,0.73,64.76,OX40N,NTT,MISC

In [23]:
# top 5 RSP
df_tmp = df_portfolio_features.sort_values(by = 'RSP', ascending=False)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
60,QUESS,2.13,22.96,41.43,73.90,54403.0,24519.0,131312.0,424.0,-33.88,88.0,X-SC,22.04,80.0,0.45,0.86,79.01,XY24,NTT,MISC
64,RELAXO,1.48,-48.42,195.29,52.31,146216.0,-70289.0,74871.0,1176.0,-45.12,63.0,X-SC,11.61,92.0,-0.48,0.49,67.40,X40N,NTT,FOOTWEAR
83,TTKPRESTIG,0.65,-18.03,22.12,0.09,18272.0,-18175.0,82602.0,770.0,91.68,70.0,M-SC,5.27,250.0,-0.99,0.54,47.08,OX40N,NTT,DURABLES
49,JSWINFRA,-1.14,9.04,6.77,16.43,16372.0,20052.0,241826.0,342.0,-6.40,60.0,X-MC,11.74,61.0,1.22,1.59,37.11,X40N,NTT,REALTY
0,5PAISA,-3.89,-30.34,62.09,12.90,94497.0,-66302.0,152194.0,593.0,124.76,62.0,H-SC,4.79,170.0,-0.70,1.00,46.87,OX40N,NTT,FINANCE

In [24]:
# Top N allocation
df_tmp = df_portfolio_features.sort_values(by = 'CurrAlloc%', ascending=False)
top_n_values = [10, 25, 50]

sum_df = pd.DataFrame({
    'Top_N': top_n_values,
    'Sum_Alloc%': [df_tmp['CurrAlloc%'].head(n).sum() for n in top_n_values]
})

sum_df

   Top_N  Sum_Alloc%
0     10       19.32
1     25       42.75
2     50       72.63

In [25]:
# market-cap-wise allocation
df_tmp = df_portfolio_features[cols]
df_tmp.groupby(df_tmp['Conviction'].str[-2:])['CurrAlloc%'].sum().sort_values(ascending=False)

Conviction
SC    43.67
LC    30.17
MC    26.21
Name: CurrAlloc%, dtype: float64

In [26]:
# criteria-wise allocation
df_portfolio_features.groupby('Criteria')['CurrAlloc%'].sum().sort_values(ascending=False)

Criteria
XY24     27.88
X40      24.69
X40N     17.39
XR        8.86
OX40N     7.10
AR        6.82
XY25      6.40
SR        0.91
Name: CurrAlloc%, dtype: float64

In [27]:
# conviction-wise allocation
df_portfolio_features.groupby('Conviction')['CurrAlloc%'].sum().sort_values(ascending=False)

Conviction
X-LC    28.24
H-SC    23.02
X-MC    21.01
M-SC    10.05
X-SC    10.02
H-MC     2.77
M-MC     2.05
H-LC     1.14
M-LC     0.79
L-SC     0.58
L-MC     0.38
Name: CurrAlloc%, dtype: float64

In [28]:
# sector-wise stats
df_tmp = df_portfolio_features.groupby('Category')[['CurrAlloc%', 'Current', 'Current P/L', 'FTT Amt']].sum().sort_values(by=['Current', 'Current P/L'], ascending=False)
df_tmp['Current P/L%'] = round(df_tmp['Current P/L'] * 100 / df_tmp['Current'], 2)
df_tmp['FTT%'] = round(df_tmp['FTT Amt'] * 100 / df_tmp['Current'], 2)
cols = ['CurrAlloc%', 'Current P/L%', 'FTT%']
df_tmp[cols].sort_values(by=['CurrAlloc%'], ascending=False)

               CurrAlloc%  Current P/L%    FTT%
Category
FMCG                14.35        -21.01   63.46
FINANCE             11.37         -6.19   52.19
IT                   9.73        -51.86  127.79
MISC                 7.24        -21.47   73.59
AUTO                 6.68         -7.54   47.64
BANKS                5.82         -2.38   49.73
PAINTS               5.45        -18.55   38.77
INSURANCE            5.34         -1.71   36.02
PHARMA               5.21          6.75   22.12
ELECTRICAL           4.07        -13.82   53.99
CHEMICALS            2.21        -20.25   91.59
HEALTHCARE           2.07        -12.97   42.45
APPARELS             1.92          8.61   22.09
AC                   1.75        -19.89   52.40
FOOTWEAR             1.72        -68.38  135.89
DURABLES             1.62        -56.96   95.14
BREWERIES            1.60          3.78   16.20
REALTY               1.59          8.29    6.77
TRAVEL               1.52        -92.33  188.64
CERAMICS             1.42        -42.11   85.29
CABLES               1.28         24.39   57.21
ENGINEERING          1.26        -26.28   84.04
JEWELLERY            1.10        -91.89  158.57
REFINERIES           1.09        -20.49   50.98
CEMENT               1.08        -62.71  184.45
ENTERTAINMENT        0.73        -72.78  175.82
TEXTILES             0.42        -44.77   86.05
HOTELS               0.41        -83.61  148.37

In [29]:
# money to be made criteria-wise
df_portfolio_features.groupby('Criteria')['FTT Amt'].agg(['sum', 'count']).sort_values(by='sum', ascending=False)

                sum  count
Criteria
XY24      3343254.0     21
X40       1909453.0     19
XR        1329341.0     13
AR        1137679.0      9
X40N      1070067.0     13
OX40N      712142.0     10
XY25       459770.0      5
SR         280011.0      2

In [30]:
# money to be made conviction-wise
df_portfolio_features.groupby('Conviction')['FTT Amt'].agg(['sum', 'count']).sort_values(by='sum', ascending=False)

                  sum  count
Conviction
H-SC        3270176.0     24
X-LC        1975759.0     21
X-MC        1511106.0     15
M-SC        1384631.0     14
X-SC        1273219.0      9
H-MC         275858.0      2
L-SC         203850.0      2
M-LC         170917.0      1
M-MC          72599.0      2
H-LC          59096.0      1
L-MC          44506.0      1

In [31]:
# money to be made criteria and conviction-wise
df_portfolio_features.groupby(['Conviction', 'Criteria'])['FTT Amt'].agg(['sum', 'count']).sort_values(by='sum', ascending=False)

                           sum  count
Conviction Criteria
X-LC       X40       1050937.0     10
H-SC       AR         956312.0      5
           XY24       940809.0      6
M-SC       XY24       814127.0      6
H-SC       XR         798376.0      7
X-SC       XY24       754584.0      4
X-MC       X40        646243.0      7
           X40N       391354.0      4
X-LC       X40N       372351.0      6
           XY24       360042.0      2
X-SC       X40N       306362.0      3
M-SC       OX40N      305380.0      5
H-SC       OX40N      294668.0      4
           SR         280011.0      2
H-MC       XY24       250393.0      1
X-MC       XY25       250210.0      2
           XY24       223299.0      2
X-SC       X40        212273.0      2
M-SC       XR         190995.0      2
M-LC       XR         170917.0      1
X-LC       XY25       159638.0      2
L-SC       OX40N      112094.0      1
           XR          91756.0      1
M-SC       AR          74129.0      1
H-LC       AR          59096.0      1
M-MC       XY25        49922.0      1
L-MC       XR          44506.0      1
X-LC       XR          32791.0      1
H-MC       AR          25465.0      1
M-MC       AR          22677.0      1

In [32]:
# notebook execution time

end_time = time.time()
execution_time = round(end_time - start_time, 0)
print(f"Notebook execution time: {execution_time} seconds")

Notebook execution time: 31.0 seconds