<a href="https://colab.research.google.com/github/ankit-rathi/Quantvesting_v2/blob/main/myStocks_Portfolio_Analysis.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
'''
!pip install pandas==2.2.2 -qq
!pip install pyxirr -qq
!pip install ta -qq
!pip install yfinance==0.2.59 -qq
'''

'\n!pip install pandas==2.2.2 -qq\n!pip install pyxirr -qq\n!pip install ta -qq\n!pip install yfinance==0.2.59 -qq\n'

In [2]:
# import libraries

import numpy as np
import pandas as pd
import datetime
import warnings
warnings.filterwarnings('ignore')
import yfinance as yfin
import ta
import matplotlib.pyplot as plt
import requests

In [3]:
# notebook start time
import time
import datetime
import pytz

start_time = time.time()

# function to print date timestamp
def print_date_time():
  tz_NY = pytz.timezone('Asia/Kolkata')
  datetime_NY = datetime.datetime.now(tz_NY)
  print("Run date time (IST):", datetime_NY.strftime("%Y-%m-%d %H:%M:%S"))

In [4]:
# function to get booked and reserved amount
def get_amt():
  # fetch the JSON data from the URL
  url = "https://raw.githubusercontent.com/ankit-rathi/Tradevesting_v1/main/data/myPortfolioAmts.json"
  response = requests.get(url)
  pf_amts = response.json()  # parse the JSON data

  # extract values from the JSON
  py_booked_amt_dm = pf_amts["py_booked_amt_dm"]
  py_booked_amt_sv = pf_amts["py_booked_amt_sv"]
  cy_booked_amt_dm = pf_amts["cy_booked_amt_dm"]
  cy_booked_amt_sv = pf_amts["cy_booked_amt_sv"]
  reserve_amt_dm = pf_amts["reserve_amt_dm"]
  reserve_amt_sv = pf_amts["reserve_amt_sv"]

  # perform calculations
  py_booked_amt = py_booked_amt_dm + py_booked_amt_sv
  cy_booked_amt = cy_booked_amt_dm + cy_booked_amt_sv
  reserve_amt = reserve_amt_dm + reserve_amt_sv
  total_booked_amt = py_booked_amt + cy_booked_amt

  return total_booked_amt, reserve_amt, cy_booked_amt, py_booked_amt

gen_output = 0

In [5]:
# function to format the amount
def format_amt(number):
    abs_number = abs(number)

    if abs_number >= 1_00_00_000:  # Crores
        formatted_amt = f"{number / 1_00_00_000:.2f} C"
    elif abs_number >= 1_00_000:  # Lakhs
        formatted_amt = f"{number / 1_00_000:.2f} L"
    elif abs_number >= 1_000:  # Thousands
        formatted_amt = f"{number / 1_000:.2f} K"
    else:
        formatted_amt = f"{number:.2f}"

    return formatted_amt

# function to set start and end date
def get_start_end_date():
  start_date = (datetime.date.today() + datetime.timedelta(days=-365)).strftime('%Y-%m-%d')
  end_date = (datetime.date.today() + datetime.timedelta(days=1)).strftime('%Y-%m-%d')
  return start_date, end_date

# function to fetch my portfolio csv
def get_mypfs_df():
  mypfs_df = pd.read_csv('https://raw.githubusercontent.com/ankit-rathi/Tradevesting_v1/main/data/myPortfolioStocks.csv')
  return mypfs_df

# function to fetch my prospects csv
def get_mypps_df():
  mypps_df = pd.read_csv('https://raw.githubusercontent.com/ankit-rathi/Tradevesting_v1/main/data/myProspectsScrips.csv')
  return mypps_df

# function to fetch screener data
def get_myscreen_df():
  myscreen_df = pd.read_csv('https://raw.githubusercontent.com/ankit-rathi/Tradevesting_v1/main/data/myScreenerDB.csv')
  return myscreen_df

# function to fetch momentum data
def get_myinvmt_df():
  myinvmt_df = pd.read_csv('https://raw.githubusercontent.com/ankit-rathi/Tradevesting_v1/main/data/myInvestments.csv')
  return myinvmt_df

# function to get the stock ids
def get_stock_ids(df_pf):
  stock_n100 = df_pf['Symbol'].unique()

  exclude = ['CADILAHC','MMTC', 'MASFIN']

  stock_ids = df_pf[~df_pf['Symbol'].isin(exclude) ]['Symbol'].unique()

  #mypf = mypf[mypf.Forecast.notnull()]
  #stock_ids = mypf['Symbol'].unique()

  #stock_ids.sort()
  return stock_ids

# get features from screener data
def get_screener_features():
  myscreen_df = get_myscreen_df()
  cols = ['Symbol', 'EPS', 'MedPE', 'ROCE%', 'ROE%', 'CapType']
  return myscreen_df[cols]

# get relative strength
def get_relative_strength(stock_list):

    # Dictionary to store stock tickers and their corresponding percentage price change
    stock_changes = {}

    # Loop through each stock and fetch its price data
    for stock in stock_list:
        try:
            # Download the stock data for the given date range
            stock_data = yfin.Ticker(stock + '.NS').history(period='1mo', interval='1d')[map(str.title, ['open', 'close', 'low', 'high', 'volume'])]

            # Calculate the percentage change for the stock
            if len(stock_data) > 0:
                start_price = stock_data['Close'].iloc[0]
                end_price = stock_data['Close'].iloc[-1]
                percent_change = round(((end_price - start_price) / start_price) * 100, 2)
                stock_changes[stock] = percent_change
            else:
                stock_changes[stock] = np.nan  # If no data is available, set to NaN

        except Exception as e:
            print(f"Error fetching data for {stock}: {e}")
            stock_changes[stock] = np.nan

    # Create a DataFrame with stock tickers and their percentage changes
    df = pd.DataFrame(list(stock_changes.items()), columns=['Symbol', 'Percent_Change'])

    # Drop any stocks with missing data (NaN values)
    df = df.dropna()

    # Calculate the percentile rank based on percentage change
    df['RSP'] = round(df['Percent_Change'].rank(pct=True) * 100, 2)
    cols = ['Symbol', 'RSP']
    df = df[cols]
    # Sort by percentile rank (optional)
    df = df.sort_values(by='RSP', ascending=False).reset_index(drop=True)

    return df

In [6]:
# function to get stock technicals
def stock_prec_dev(stock_symbol):
    #stock_symbol = 'ULTRACEMCO.NS'
    short_window = 20
    mid_window = 50
    long_window = 200
    moving_avg = 'SMA'

    start = datetime.datetime(*map(int, start_date.split('-')))
    end = datetime.datetime(*map(int, end_date.split('-')))

    stock_df = yfin.Ticker(stock_symbol + '.NS').history(period='max', interval='1d')[map(str.title, ['open', 'close', 'low', 'high', 'volume'])]

    stock_df['Max'] = round(max(stock_df['Close']),2)
    stock_df = stock_df[(stock_df.index <= end_date) & (stock_df.index >= start_date)]
    stock_df['200_SMA'] = round(stock_df['Close'].rolling(window = 200, min_periods = 1).mean(),0)
    stock_df['Dev%_200'] = round((stock_df['Close'] - stock_df['200_SMA'])*100/stock_df['200_SMA'],2)
    stock_df.dropna(axis = 0, inplace = True) # remove any null rows

    stock_df['20_SMA'] = stock_df['Close'].rolling(window=20).mean()
    stock_df['50_SMA'] = stock_df['Close'].rolling(window=50).mean()
    stock_df['Symbol'] = stock_symbol

    stock_df['Close'] = round(stock_df['Close'],2)
    stock_df['Min'] = round(min(stock_df['Close']),2)
    stock_df['RSI_14'] = ta.momentum.RSIIndicator(close=stock_df['Close'], window=14).rsi()
    stock_df['RSI_14'] = round(stock_df['RSI_14'],0)
    stock_df['Prev_Close'] = stock_df['Close'].shift(1)
    stock_df.drop(['Open', 'Low', 'High', 'Volume'], axis=1, inplace=True)
    stock_df = stock_df.tail(1)

    max_SMA = max(stock_df['20_SMA'].item(), stock_df['50_SMA'].item(), stock_df['200_SMA'].item())
    min_SMA = min(stock_df['20_SMA'].item(), stock_df['50_SMA'].item(), stock_df['200_SMA'].item())
    ABS_Spread = max_SMA - min_SMA
    stock_df['Spread%'] = round((ABS_Spread / stock_df['200_SMA'].item()) * 100,2)

    return stock_df

# function to compute stock attributes
def get_common_features(stock_ids, df_mypf):

  df_prec_dev = pd.DataFrame()
  df_tmp = get_screener_features()
  df_rs = get_relative_strength(stock_ids)

  for stock_id in stock_ids:
      tmp = stock_prec_dev(stock_id)
      tmp = tmp.reset_index()
      df_prec_dev = pd.concat([df_prec_dev, tmp], ignore_index = True)
  df_prec_dev = pd.merge(df_prec_dev, df_mypf, on= 'Symbol')
  df_prec_dev = pd.merge(df_prec_dev, df_tmp, on= 'Symbol', how='left')
  df_prec_dev = pd.merge(df_prec_dev, df_rs, on= 'Symbol', how='left')
  #print(df_prec_dev.columns)
  df_prec_dev['Curr_PE'] = round(df_prec_dev['Close']/df_prec_dev['EPS'],1)
  df_prec_dev['Dev%_PE'] = round((df_prec_dev['Curr_PE'] - df_prec_dev['MedPE'])*100/df_prec_dev['MedPE'],2)
  df_prec_dev['Conviction'] = df_prec_dev['Conviction'] + '-' + df_prec_dev['CapType']
  return df_prec_dev

# function to arrange stock features
def arrange_features(df_stocks, common_cols, diff_cols):
  df_stocks_common = df_stocks[common_cols].drop_duplicates()
  df_stocks_diff = df_stocks[diff_cols]
  df_stocks_diff['Investment'] = df_stocks_diff['AvgCost'] * df_stocks_diff['Shares']
  df_stocks_diff = df_stocks_diff.groupby(['Symbol'])[['Shares', 'Investment']].aggregate(['sum']).reset_index()
  df_stocks_diff.columns = ['Symbol', 'Shares', 'Investment']
  df_stocks_diff['AvgCost'] = round(df_stocks_diff['Investment']/df_stocks_diff['Shares'],2)
  df_stocks = pd.merge(df_stocks_diff, df_stocks_common, on='Symbol')
  return df_stocks

# plot fact distribution across dimension
def plot_pie_chart(df, dimension, fact):
  # grouping the data by category and calculating the sum of fact for each type
  grouped_data = df.groupby(dimension)[fact].sum()

  # sorting the grouped data in descending order
  grouped_data = grouped_data.sort_values(ascending=False)

  # creating a pie chart
  grouped_data.plot.pie(autopct='%1.1f%%', startangle=90, figsize=(6, 6))

  # adding a title and displaying the plot
  plt.title(f'{dimension} {fact} Distribution')
  plt.ylabel('')  # To hide the y-label
  plt.show()

In [7]:
# function to get portfolio features

def get_portfolio_features(df_common_features):

  print_date_time()
  print('-------------------')

  #df_common_features["Target"] = df_common_features["Target"].fillna(df_common_features["Max"])
  df_common_features['NTT'] = np.where(df_common_features['Strategy']== 'NTT', df_common_features["Target"], df_common_features['Max'])
  df_common_features['LTT'] = np.where(df_common_features['Strategy']== 'BTT', df_common_features["Target"], df_common_features['Max'])
  df_common_features['BOL'] = df_common_features['Min']

  tmp_df = df_common_features[df_common_features['Symbol'].isin(mypf_df[mypf_df['InPortfolio'] != 'NA'].Symbol.values)]
  print('qualified stocks: '+str(len(tmp_df['Symbol'].unique())))
  tmp_df1 = tmp_df[tmp_df['LatestQtr'] == 1]
  print('with latest results: '+str(len(tmp_df1['Symbol'].unique())))
  tmp_df1 = tmp_df1[tmp_df1['StarStock'] == 1]
  print('still star stocks: '+str(len(tmp_df1['Symbol'].unique())))
  tmp_df['Investment'] = tmp_df['AvgCost'] * tmp_df['Shares']
  tmp_df['Current'] = round(tmp_df['Close'] * tmp_df['Shares'],0)
  tmp_df['Previous'] = tmp_df['Prev_Close'] * tmp_df['Shares']
  tmp_df['EstimatedST'] = tmp_df['NTT'] * tmp_df['Shares']
  tmp_df['EstimatedLT'] = tmp_df['LTT'] * tmp_df['Shares']
  tmp_df['Current P/L'] = round((tmp_df['Current'] - tmp_df['Investment']),0)
  tmp_df['Today P/L%'] = round((tmp_df['Current'] - tmp_df['Previous'])*100/tmp_df['Previous'],2)
  tmp_df['Current P/L%'] = round((tmp_df['Current'] - tmp_df['Investment'])*100/tmp_df['Investment'],2)
  tmp_df['EstimatedST P/L%'] = round((tmp_df['EstimatedST'] - tmp_df['Investment'])*100/tmp_df['Investment'],2)
  tmp_df['EstimatedLT P/L%'] = round((tmp_df['EstimatedLT'] - tmp_df['Investment'])*100/tmp_df['Investment'],2)
  tmp_df['NTT%'] = round((tmp_df['NTT'] - tmp_df['Close'])*100/tmp_df['Close'],2)
  tmp_df['LTT%'] = round((tmp_df['LTT'] - tmp_df['Close'])*100/tmp_df['Close'],2)
  tmp_df['Gained%'] = round((tmp_df['Close'] - tmp_df['BOL'])*100/tmp_df['BOL'],2)
  investment = round(sum(tmp_df['AvgCost']*tmp_df['Shares']),0)
  current = round(sum(tmp_df['Close']*tmp_df['Shares']),0)
  tmp_df['InitAlloc%'] = round(tmp_df['Investment']*100/investment,2)
  tmp_df['CurrAlloc%'] = round(tmp_df['Current']*100/current,2)
  tmp_df['FTT'] = tmp_df['LTT']
  tmp_df.loc[tmp_df['Strategy'] == 'NTT', 'FTT'] = tmp_df['NTT']
  tmp_df['FTT%'] = tmp_df['LTT%']
  tmp_df.loc[tmp_df['Strategy'] == 'NTT', 'FTT%'] = tmp_df['NTT%']
  tmp_df['FTT Amt'] = round(tmp_df['FTT%'] * tmp_df['Current']/100,0)
  tmp_df['OTT%'] = round((tmp_df['FTT'] - tmp_df['AvgCost'])*100/tmp_df['AvgCost'],2)
  tmp_df['RRR Ind'] = round(tmp_df['Current P/L']/tmp_df['FTT Amt'],2)
  tmp_df['Risk Ind'] = round(tmp_df['Current P/L%']*tmp_df['CurrAlloc%'],0)

  return tmp_df

# function to print portfolio features
def print_portfolio_stats(df_portfolio_features, myinvmt_df):
  from pyxirr import xirr

  total_booked_amt, reserve_amt, cy_booked_amt, py_booked_amt = get_amt()

  dates = myinvmt_df['Date'].values
  dates = np.append(dates, datetime.date.today().strftime('%d-%b-%y'))
  investment = myinvmt_df['Investment'].values
  dates= pd.to_datetime(dates)

  current = round(sum(df_portfolio_features['Close']*df_portfolio_features['Shares']),0) + reserve_amt
  investment_xirr = np.append(investment, current)
  cagr = round(xirr(pd.DataFrame({"dates": dates, "amounts": investment_xirr}))*100,2)

  investment = -sum(investment)
  invested = round(sum(df_portfolio_features['AvgCost']*df_portfolio_features['Shares']),0) + reserve_amt
  previous = round(sum(df_portfolio_features['Prev_Close']*df_portfolio_features['Shares']),0) + reserve_amt
  cy_invested = investment + py_booked_amt

  today_pnl_amount = current-previous
  today_pnl_percentage = round((current-previous)*100/previous,2)

  curr_pnl_amount = current-invested
  curr_pnl_percentage = round((curr_pnl_amount)*100/(cy_invested),2)

  cy_pnl_amount = cy_booked_amt + curr_pnl_amount
  cy_pnl_percentage = round((cy_pnl_amount)*100/cy_invested,2)

  overall_pnl_amount = total_booked_amt + curr_pnl_amount
  overall_pnl_percentage = round((overall_pnl_amount)*100/investment,2)

  estimate_st = round(sum(df_portfolio_features['FTT']*df_portfolio_features['Shares']),0)  + reserve_amt
  est_st_pnl_amount = estimate_st-current
  est_st_pnl_percentage = round((est_st_pnl_amount)*100/current,2)

  estimate_lt = round(sum(df_portfolio_features['LTT']*df_portfolio_features['Shares']),0)  + reserve_amt
  est_lt_pnl_amount = estimate_lt-current
  est_lt_pnl_percentage = round((est_lt_pnl_amount)*100/current,2)

  total_profit = round(sum(df_portfolio_features[df_portfolio_features['Current P/L%'] > 0]['Current']) - sum(df_portfolio_features[df_portfolio_features['Current P/L%'] > 0]['Investment']),0)
  total_loss = round(sum(df_portfolio_features[df_portfolio_features['Current P/L%'] < 0]['Current']) - sum(df_portfolio_features[df_portfolio_features['Current P/L%'] < 0]['Investment']),0)

  cy_booked_percentage = round((cy_booked_amt)*100/current,2)
  py_booked_percentage = round((py_booked_amt)*100/investment,2)
  total_booked_percentage = round((total_booked_amt)*100/investment,2)

  print('-------------------')
  print('Initial Investment: ', format_amt(investment))
  print('CY Investment: ', format_amt(cy_invested))
  print('Reserve: ', format_amt(reserve_amt))
  print('Current: ',  format_amt(current))
  print('-------------------')
  print('Today PnL: '+ '{} ({}%)'.format(format_amt(today_pnl_amount), today_pnl_percentage))
  print('Current PnL: '+ '{} ({}%)'.format(format_amt(curr_pnl_amount), curr_pnl_percentage))
  print('CY Booked + Current PnL: '+ '{} ({}%)'.format(format_amt(cy_pnl_amount), cy_pnl_percentage))
  print('-------------------')
  print('Total profit: ', format_amt(total_profit))
  print('Total loss: ', format_amt(total_loss))
  print('-------------------')
  print('Total Booked + Current PnL: '+ '{} ({}%)'.format(format_amt(overall_pnl_amount), overall_pnl_percentage))
  print('Total Booked PnL: '+ '{} ({}%)'.format(format_amt(total_booked_amt), total_booked_percentage))
  print('Curr Year Booked PnL: '+ '{} ({}%)'.format(format_amt(cy_booked_amt), cy_booked_percentage))
  print('Prev Year Booked PnL: '+ '{} ({}%)'.format(format_amt(py_booked_amt), py_booked_percentage))
  print('===================')
  print('Est FTT: ',  format_amt(estimate_st))
  print('Est FTT PnL: '+ '{} ({}%)'.format(format_amt(est_st_pnl_amount), est_st_pnl_percentage))

  print('===================')
  print('Deployed: ', format_amt(investment))

  print('Current: ', format_amt(current))

  print('CAGR/XIRR %: '+'{}%'.format(cagr))

In [8]:
# get start and end date
start_date, end_date = get_start_end_date()

# get portfolio and prospects data
mypfs_df = get_mypfs_df()
mypps_df = get_mypps_df()
myinvmt_df = get_myinvmt_df()

# merge above datasets
mypf_df = pd.merge(mypfs_df, mypps_df, on="Symbol")

# seggregate dm and sv portfolio
dm_pf = mypf_df[mypf_df['InPortfolio'] == 'DM']
sv_pf = mypf_df[mypf_df['InPortfolio'] == 'SV']

# build portfolio stock dataframe
dm_stocks = get_stock_ids(dm_pf)
sv_stocks = get_stock_ids(sv_pf)
df_stocks = pd.concat([dm_pf,sv_pf], ignore_index = True)

# arrange common and diff stock features
common_cols = ['Symbol', 'Target', 'Criteria', 'Strategy', 'CumlRnk', 'LatestQtr', 'StarStock', 'Conviction', 'Category', 'InFolio', 'XIRR', 'MBQ']
diff_cols = ['Symbol', 'AvgCost', 'Shares']
df_stocks = arrange_features(df_stocks, common_cols, diff_cols)

# get common features
stock_ids = df_stocks['Symbol'].values
df_common_features = get_common_features(stock_ids, df_stocks)

df_common_features.reset_index(drop=True, inplace=True)
df_common_features.drop(['Date'], axis=1, inplace=True)
# get and print portfolio features
df_portfolio_features = get_portfolio_features(df_common_features)

print_portfolio_stats(df_portfolio_features, myinvmt_df)

df = df_portfolio_features
#plot_pie_chart(df, 'CapType', 'Current')
list_ox40n = list(df[df['MBQ'].str.contains('OX40N', na=False)]['Symbol'].values)

Run date time (IST): 2026-05-18 11:43:43
-------------------
qualified stocks: 92
with latest results: 31
still star stocks: 20

-------------------
Initial Investment:  1.40 C
CY Investment:  1.82 C
Reserve:  1.49 K
Current:  1.46 C
-------------------
Today PnL: -2.38 L (-1.61%)
Current PnL: -37.32 L (-20.46%)
CY Booked + Current PnL: -35.24 L (-19.32%)
-------------------
Total profit:  1.70 L
Total loss:  -39.02 L
-------------------
Total Booked + Current PnL: 7.63 L (5.47%)
Total Booked PnL: 44.95 L (32.22%)
Curr Year Booked PnL: 2.08 L (1.43%)
Prev Year Booked PnL: 42.87 L (30.73%)
===================
Est FTT:  2.55 C
Est FTT PnL: 1.10 C (75.13%)
===================
Deployed:  1.40 C
Current:  1.46 C
CAGR/XIRR %: 2.16%

In [9]:
# top 5 near their targets
cols = ['Symbol', 'Today P/L%', 'Current P/L%', 'FTT%', 'OTT%', 'FTT Amt', 'Current P/L', 'Current', 'FTT', 'Dev%_PE', 'RSI_14','Conviction', 'Spread%',  'CumlRnk', 'RRR Ind', 'CurrAlloc%', 'Gained%', 'Criteria', 'Strategy', 'Category']
df_tmp = df_portfolio_features[~df_portfolio_features['Symbol'].isin(['ENRIN','BLUSPRING','DIGITIDE'])]
df_tmp = df_tmp.sort_values(by = 'FTT Amt', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
59,PIDILITIND,-1.66,2.29,15.72,18.37,22690.0,3230.0,144340.0,1670.26,-28.32,56.0,X-LC,5.64,5.0,0.14,0.99,13.33,X40,ATH,CHEMICALS
51,KOTAKBANK,-0.43,2.98,17.60,21.11,25097.0,4126.0,142598.0,453.24,-11.57,56.0,X-LC,7.54,12.0,0.16,0.98,9.05,X40,ATH,BANKS
55,MASFIN,-2.27,-4.42,27.20,21.57,25471.0,-4335.0,93645.0,397.04,-17.80,39.0,H-SC,5.68,167.0,-0.17,0.64,15.62,XR,ATH,FINANCE
17,CIPLA,-0.29,15.61,16.50,34.69,29217.0,23911.0,177072.0,1663.60,-10.44,69.0,X-LC,10.72,18.0,0.82,1.21,19.76,X40N,ATH,PHARMA
53,M&M,-1.16,0.16,23.18,23.38,32198.0,225.0,138906.0,3802.40,-15.13,44.0,X-LC,8.50,25.0,0.01,0.95,5.31,X40N,ATH,AUTO

In [10]:
# top 5 today
df_tmp = df_portfolio_features.sort_values(by = 'Today P/L%', ascending=False)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
86,VALIANTORG,3.20,-36.39,173.77,74.15,180849.0,-59531.0,104074.0,838.00,-287.15,62.0,H-SC,11.61,145.0,-0.33,0.71,54.88,XR,NTT,CHEMICALS
45,INFY,1.12,-22.97,74.28,34.24,179022.0,-71878.0,241010.0,1972.00,-39.40,37.0,X-LC,18.67,3.0,-0.40,1.65,3.33,X40,NTT,IT
72,SIS,0.65,-9.79,34.42,21.26,34476.0,-10868.0,100164.0,528.00,2381.87,67.0,H-SC,14.08,168.0,-0.32,0.69,48.93,OX40N,NTT,MISC
33,HCLTECH,0.43,-26.18,64.60,21.51,115368.0,-63336.0,178588.0,1872.35,-22.25,28.0,X-LC,17.28,8.0,-0.55,1.22,1.20,X40,ATH,IT
90,WIPRO,0.43,-21.74,120.11,72.27,159281.0,-36835.0,132613.0,420.00,-29.24,38.0,M-LC,14.09,98.0,-0.23,0.91,1.74,XR,NTT,IT

In [11]:
# bottom 5 today
df_tmp = df_portfolio_features.sort_values(by = 'Today P/L%', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
76,SYMPHONY,-7.34,-44.39,79.75,-0.03,75904.0,-75963.0,95178.0,1306.0,-55.38,36.0,M-SC,11.00,205.0,-1.00,0.65,5.56,OX40N,NTT,DURABLES
40,ICICIPRULI,-5.69,-16.42,56.40,30.73,92870.0,-32342.0,164663.0,790.0,-38.91,35.0,X-MC,11.87,78.0,-0.35,1.13,0.34,X40,ATH,INSURANCE
12,BOSCH-HCIL,-4.59,-42.07,72.60,-0.01,53752.0,-53767.0,74038.0,2282.0,15052.17,41.0,M-SC,6.20,231.0,-1.00,0.51,26.02,OX40N,BTT,AC
29,GREENPANEL,-4.58,-48.45,177.68,43.14,167684.0,-88704.0,94374.0,537.0,111.24,33.0,M-SC,16.75,225.0,-0.53,0.65,13.37,XY24,NTT,MISC
5,ATULAUTO,-4.13,-14.37,69.99,45.57,118150.0,-28322.0,168810.0,844.0,3656.76,56.0,M-SC,8.02,248.0,-0.24,1.16,29.91,XY24,NTT,AUTO

In [12]:
# top 5 to exit based on CumlRnk
df_tmp = df_portfolio_features[~df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])]
df_tmp = df_tmp[(df_tmp['Current P/L%'] > -1) & (df_tmp['Current P/L%'] < 1)].sort_values(by = 'CumlRnk', ascending=False)
df_tmp[cols].head()

Empty DataFrame
Columns: [Symbol, Today P/L%, Current P/L%, FTT%, OTT%, FTT Amt, Current P/L, Current, FTT, Dev%_PE, RSI_14, Conviction, Spread%, CumlRnk, RRR Ind, CurrAlloc%, Gained%, Criteria, Strategy, Category]
Index: []

In [13]:
# OX40N stocks to exit
df_tmp = df_portfolio_features[(df_portfolio_features['Symbol'].isin(list_ox40n))].sort_values(by = 'Current P/L%', ascending=False)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
25,FINCABLES,-2.35,29.98,59.96,107.91,115069.0,44265.0,191909.0,1641.55,16.69,54.0,M-SC,24.22,220.0,0.38,1.32,44.38,OX40N,ATH,CABLES
72,SIS,0.65,-9.79,34.42,21.26,34476.0,-10868.0,100164.0,528.00,2381.87,67.0,H-SC,14.08,168.0,-0.32,0.69,48.93,OX40N,NTT,MISC
16,CERA,-1.99,-27.78,71.54,23.89,90884.0,-48863.0,127040.0,9475.00,-30.31,53.0,H-SC,8.73,153.0,-0.54,0.87,22.09,OX40N,NTT,CERAMICS
50,KANSAINER,-3.02,-28.12,57.88,13.47,112185.0,-75843.0,193824.0,340.00,-38.33,60.0,H-SC,14.65,162.0,-0.68,1.33,35.39,XY24,NTT,PAINTS
43,INDIGOPNTS,-2.72,-31.92,46.90,0.02,55740.0,-55711.0,118848.0,1408.00,81.36,62.0,M-SC,20.16,222.0,-1.00,0.81,34.84,OX40N,NTT,PAINTS

In [14]:
# top 5 to book for rotation
df_tmp = df_portfolio_features[(df_portfolio_features['Current P/L%'] > 20) ].sort_values(by = 'CumlRnk', ascending=False)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
25,FINCABLES,-2.35,29.98,59.96,107.91,115069.0,44265.0,191909.0,1641.55,16.69,54.0,M-SC,24.22,220.0,0.38,1.32,44.38,OX40N,ATH,CABLES
68,SATIN,-2.44,20.77,25.72,51.83,85819.0,57382.0,333666.0,274.00,7.75,74.0,H-SC,26.63,159.0,0.67,2.29,62.54,XY24,NTT,FINANCE

In [15]:
# top 5 to monitor for exit
df_tmp = df_portfolio_features[~df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])]
df_tmp = df_tmp[(df_tmp['Current P/L%'] > 0) ].sort_values(by = 'Dev%_PE', ascending=False)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
25,FINCABLES,-2.35,29.98,59.96,107.91,115069.0,44265.0,191909.0,1641.55,16.69,54.0,M-SC,24.22,220.0,0.38,1.32,44.38,OX40N,ATH,CABLES
68,SATIN,-2.44,20.77,25.72,51.83,85819.0,57382.0,333666.0,274.00,7.75,74.0,H-SC,26.63,159.0,0.67,2.29,62.54,XY24,NTT,FINANCE
91,ZYDUSLIFE,-2.14,4.40,29.91,35.63,65443.0,9227.0,218801.0,1286.17,-9.01,63.0,H-MC,2.87,120.0,0.14,1.50,15.04,AR,ATH,PHARMA

In [16]:
# top 5 to book for rotation from weak conviction
df_tmp = df_portfolio_features[~df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])]
df_tmp = df_tmp[~df_tmp['Criteria'].isin(['XY25','XY24','X40', 'X40N'])].sort_values(by = 'RRR Ind', ascending=False)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
25,FINCABLES,-2.35,29.98,59.96,107.91,115069.0,44265.0,191909.0,1641.55,16.69,54.0,M-SC,24.22,220.0,0.38,1.32,44.38,OX40N,ATH,CABLES
91,ZYDUSLIFE,-2.14,4.40,29.91,35.63,65443.0,9227.0,218801.0,1286.17,-9.01,63.0,H-MC,2.87,120.0,0.14,1.50,15.04,AR,ATH,PHARMA
73,SONACOMS,-1.39,-2.15,42.15,39.09,41720.0,-2179.0,98980.0,804.02,-22.50,47.0,M-MC,19.39,193.0,-0.05,0.68,40.02,AR,ATH,AUTO
42,INDIAMART,-0.81,-16.60,147.88,106.72,152105.0,-20479.0,102857.0,4810.62,-62.30,28.0,H-SC,9.61,140.0,-0.13,0.71,0.00,AR,ATH,MISC
55,MASFIN,-2.27,-4.42,27.20,21.57,25471.0,-4335.0,93645.0,397.04,-17.80,39.0,H-SC,5.68,167.0,-0.17,0.64,15.62,XR,ATH,FINANCE

In [17]:
# top 5 to accumulate based on lowest RSI_14
df_tmp = df_portfolio_features[df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])].sort_values(by = 'RSI_14', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
33,HCLTECH,0.43,-26.18,64.60,21.51,115368.0,-63336.0,178588.0,1872.35,-22.25,28.0,X-LC,17.28,8.0,-0.55,1.22,1.20,X40,ATH,IT
79,TCS,0.12,-33.46,90.21,26.57,278091.0,-155002.0,308271.0,4311.59,-43.63,30.0,X-LC,16.21,2.0,-0.56,2.11,0.92,X40,ATH,IT
58,PGHH,-2.12,-28.81,85.44,32.01,129869.0,-61520.0,152000.0,17616.87,-51.83,33.0,X-MC,16.83,57.0,-0.47,1.04,3.96,X40,ATH,FMCG
88,VOLTAS,0.28,-3.46,50.39,45.20,93279.0,-6627.0,185115.0,1856.00,10.57,34.0,X-MC,1.03,79.0,-0.07,1.27,1.14,XY25,NTT,AC
40,ICICIPRULI,-5.69,-16.42,56.40,30.73,92870.0,-32342.0,164663.0,790.00,-38.91,35.0,X-MC,11.87,78.0,-0.35,1.13,0.34,X40,ATH,INSURANCE

In [18]:
# top 5 to accumulate based on Spread and CumlRnk
df_tmp = df_portfolio_features[df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])]
df_tmp = df_tmp[(df_tmp['CumlRnk'] < 100)].sort_values(by = 'Spread%', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
88,VOLTAS,0.28,-3.46,50.39,45.20,93279.0,-6627.0,185115.0,1856.00,10.57,34.0,X-MC,1.03,79.0,-0.07,1.27,1.14,XY25,NTT,AC
84,UNITDSPR,-1.95,-4.87,26.95,20.77,60028.0,-11404.0,222740.0,1644.00,-15.56,48.0,X-MC,3.14,64.0,-0.19,1.53,6.25,X40N,NTT,BREWERIES
65,RELIANCE,0.22,-14.03,45.75,25.30,79042.0,-28193.0,172770.0,1952.00,-16.19,40.0,X-LC,3.62,21.0,-0.36,1.18,2.66,XY25,BTT,REFINERIES
39,ICICIGI,-1.80,-4.54,25.01,19.34,47777.0,-9076.0,191033.0,2252.93,-19.59,49.0,X-MC,4.88,66.0,-0.19,1.31,6.70,X40,ATH,INSURANCE
19,COLPAL,-1.23,-18.99,74.68,41.51,159330.0,-50015.0,213350.0,3726.84,-2.04,54.0,X-MC,5.47,62.0,-0.31,1.46,19.28,XY25,ATH,FMCG

In [19]:
# top 5 to accumulate based on lowest Gained%
df_tmp = df_portfolio_features[df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])].sort_values(by = 'Gained%', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
40,ICICIPRULI,-5.69,-16.42,56.40,30.73,92870.0,-32342.0,164663.0,790.00,-38.91,35.0,X-MC,11.87,78.0,-0.35,1.13,0.34,X40,ATH,INSURANCE
32,HAVELLS,-1.93,-24.05,73.90,32.08,184086.0,-78889.0,249102.0,2062.85,-28.51,37.0,X-MC,11.55,63.0,-0.43,1.71,0.47,X40,ATH,ELECTRICAL
79,TCS,0.12,-33.46,90.21,26.57,278091.0,-155002.0,308271.0,4311.59,-43.63,30.0,X-LC,16.21,2.0,-0.56,2.11,0.92,X40,ATH,IT
88,VOLTAS,0.28,-3.46,50.39,45.20,93279.0,-6627.0,185115.0,1856.00,10.57,34.0,X-MC,1.03,79.0,-0.07,1.27,1.14,XY25,NTT,AC
33,HCLTECH,0.43,-26.18,64.60,21.51,115368.0,-63336.0,178588.0,1872.35,-22.25,28.0,X-LC,17.28,8.0,-0.55,1.22,1.20,X40,ATH,IT

In [20]:
# top 5 to accumulate based on lowest CurrAlloc%
df_tmp = df_portfolio_features[df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])].sort_values(by = 'CurrAlloc%', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
64,RELAXO,-1.98,-63.39,315.99,52.31,167942.0,-92012.0,53148.0,1176.00,-60.99,40.0,X-SC,25.15,92.0,-0.55,0.36,18.83,X40N,NTT,FOOTWEAR
10,BATAINDIA,-2.04,-56.14,208.26,35.20,117534.0,-72234.0,56436.0,2096.00,-26.06,35.0,X-SC,26.17,91.0,-0.61,0.39,11.93,X40,NTT,FOOTWEAR
60,QUESS,-1.68,-18.16,112.48,73.90,98311.0,-19390.0,87403.0,424.00,-55.92,48.0,X-SC,12.03,80.0,-0.20,0.60,19.15,XY24,NTT,MISC
28,GODREJCP,-2.78,-9.58,45.41,31.47,61017.0,-14244.0,134370.0,1469.04,-4.83,39.0,X-LC,7.82,32.0,-0.23,0.92,3.10,X40N,ATH,FMCG
53,M&M,-1.16,0.16,23.18,23.38,32198.0,225.0,138906.0,3802.40,-15.13,44.0,X-LC,8.50,25.0,0.01,0.95,5.31,X40N,ATH,AUTO

In [21]:
# top 5 to accumulate based on CumlRnk
df_tmp = df_portfolio_features.sort_values(by = 'CumlRnk', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
47,ITC,-0.13,-18.60,46.25,19.06,128070.0,-63257.0,276909.0,452.00,-55.52,53.0,X-LC,15.31,1.0,-0.49,1.90,7.42,X40,NTT,FMCG
79,TCS,0.12,-33.46,90.21,26.57,278091.0,-155002.0,308271.0,4311.59,-43.63,30.0,X-LC,16.21,2.0,-0.56,2.11,0.92,X40,ATH,IT
45,INFY,1.12,-22.97,74.28,34.24,179022.0,-71878.0,241010.0,1972.00,-39.40,37.0,X-LC,18.67,3.0,-0.40,1.65,3.33,X40,NTT,IT
81,TMPV,-0.90,-19.57,69.80,36.58,199777.0,-69627.0,286214.0,600.00,-83.62,55.0,X-LC,6.15,4.0,-0.35,1.96,19.29,XY24,NTT,AUTO
59,PIDILITIND,-1.66,2.29,15.72,18.37,22690.0,3230.0,144340.0,1670.26,-28.32,56.0,X-LC,5.64,5.0,0.14,0.99,13.33,X40,ATH,CHEMICALS

In [22]:
# top 5 for average up
df_tmp = df_portfolio_features[(df_portfolio_features['Dev%_200'] > 5)].sort_values(by = 'CurrAlloc%', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
44,INDUSINDBK,-0.74,-35.05,104.59,32.89,52451.0,-27058.0,50149.0,1800.00,-335.99,48.0,L-MC,7.76,258.0,-0.52,0.34,23.44,XR,NTT,BANKS
73,SONACOMS,-1.39,-2.15,42.15,39.09,41720.0,-2179.0,98980.0,804.02,-22.50,47.0,M-MC,19.39,193.0,-0.05,0.68,40.02,AR,ATH,AUTO
72,SIS,0.65,-9.79,34.42,21.26,34476.0,-10868.0,100164.0,528.00,2381.87,67.0,H-SC,14.08,168.0,-0.32,0.69,48.93,OX40N,NTT,MISC
86,VALIANTORG,3.20,-36.39,173.77,74.15,180849.0,-59531.0,104074.0,838.00,-287.15,62.0,H-SC,11.61,145.0,-0.33,0.71,54.88,XR,NTT,CHEMICALS
75,SURYODAY,-3.01,-7.55,33.09,23.03,54779.0,-13525.0,165546.0,216.00,79.82,57.0,H-SC,16.05,166.0,-0.25,1.14,39.39,XR,NTT,BANKS

In [23]:
# top 5 RSP
df_tmp = df_portfolio_features.sort_values(by = 'RSP', ascending=False)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
68,SATIN,-2.44,20.77,25.72,51.83,85819.0,57382.0,333666.0,274.00,7.75,74.0,H-SC,26.63,159.0,0.67,2.29,62.54,XY24,NTT,FINANCE
72,SIS,0.65,-9.79,34.42,21.26,34476.0,-10868.0,100164.0,528.00,2381.87,67.0,H-SC,14.08,168.0,-0.32,0.69,48.93,OX40N,NTT,MISC
3,ALKYLAMINE,-3.34,-29.09,173.06,93.63,123902.0,-29368.0,71595.0,4546.37,-24.06,57.0,H-SC,15.72,142.0,-0.24,0.49,35.19,SR,ATH,CHEMICALS
17,CIPLA,-0.29,15.61,16.50,34.69,29217.0,23911.0,177072.0,1663.60,-10.44,69.0,X-LC,10.72,18.0,0.82,1.21,19.76,X40N,ATH,PHARMA
56,MEDANTA,-0.04,6.25,19.65,27.12,36852.0,11025.0,187542.0,1486.00,3.04,67.0,X-SC,9.71,87.0,0.30,1.29,29.23,XY24,NTT,HEALTHCARE

In [24]:
# Top N allocation
df_tmp = df_portfolio_features.sort_values(by = 'CurrAlloc%', ascending=False)
top_n_values = [10, 25, 50]

sum_df = pd.DataFrame({
    'Top_N': top_n_values,
    'Sum_Alloc%': [df_tmp['CurrAlloc%'].head(n).sum() for n in top_n_values]
})

sum_df

   Top_N  Sum_Alloc%
0     10       19.40
1     25       42.97
2     50       73.11

In [25]:
# market-cap-wise allocation
df_tmp = df_portfolio_features[cols]
df_tmp.groupby(df_tmp['Conviction'].str[-2:])['CurrAlloc%'].sum().sort_values(ascending=False)

Conviction
SC    42.26
LC    31.70
MC    26.00
Name: CurrAlloc%, dtype: float64

In [26]:
# criteria-wise allocation
df_portfolio_features.groupby('Criteria')['CurrAlloc%'].sum().sort_values(ascending=False)

Criteria
XY24     27.50
X40      25.72
X40N     16.83
XR        8.88
OX40N     6.89
XY25      6.70
AR        6.61
SR        0.83
Name: CurrAlloc%, dtype: float64

In [27]:
# conviction-wise allocation
df_portfolio_features.groupby('Conviction')['CurrAlloc%'].sum().sort_values(ascending=False)

Conviction
X-LC    29.60
H-SC    22.07
X-MC    21.03
M-SC     9.99
X-SC     9.69
H-MC     2.69
M-MC     1.94
H-LC     1.19
M-LC     0.91
L-SC     0.51
L-MC     0.34
Name: CurrAlloc%, dtype: float64

In [28]:
# sector-wise stats
df_tmp = df_portfolio_features.groupby('Category')[['CurrAlloc%', 'Current', 'Current P/L', 'FTT Amt']].sum().sort_values(by=['Current', 'Current P/L'], ascending=False)
df_tmp['Current P/L%'] = round(df_tmp['Current P/L'] * 100 / df_tmp['Current'], 2)
df_tmp['FTT%'] = round(df_tmp['FTT Amt'] * 100 / df_tmp['Current'], 2)
cols = ['CurrAlloc%', 'Current P/L%', 'FTT%']
df_tmp[cols].sort_values(by=['CurrAlloc%'], ascending=False)

               CurrAlloc%  Current P/L%    FTT%
Category
FMCG                15.57        -16.45   57.49
FINANCE             10.78        -17.21   68.19
IT                  10.13        -52.32  129.00
MISC                 6.95        -32.46   90.01
AUTO                 6.73        -11.54   53.36
BANKS                5.67         -9.92   60.75
PAINTS               5.63        -19.85   40.66
INSURANCE            5.30         -7.01   43.43
PHARMA               5.16          1.54   30.11
ELECTRICAL           3.88        -24.82   69.25
CHEMICALS            2.19        -26.77  102.32
HEALTHCARE           2.02        -21.54   53.27
AC                   1.78        -23.30   56.74
APPARELS             1.76         -4.47   40.11
TRAVEL               1.71        -80.11  170.30
DURABLES             1.65        -60.56   99.62
FOOTWEAR             1.65        -82.84  156.15
BREWERIES            1.53         -5.12   26.95
REALTY               1.39         -9.75   27.78
CERAMICS             1.32        -58.82  107.08
CABLES               1.32         23.07   59.96
REFINERIES           1.18        -16.32   45.75
ENGINEERING          1.15        -44.40  110.44
CEMENT               1.10        -66.39  190.86
JEWELLERY            0.99       -120.64  197.29
ENTERTAINMENT        0.69        -91.51  205.72
TEXTILES             0.41        -54.79   98.92
HOTELS               0.32       -146.42  233.33

In [29]:
# money to be made criteria-wise
df_portfolio_features.groupby('Criteria')['FTT Amt'].agg(['sum', 'count']).sort_values(by='sum', ascending=False)

                sum  count
Criteria
XY24      3586551.0     21
X40       1950884.0     19
XR        1386290.0     13
X40N      1268163.0     13
AR        1220867.0      9
OX40N      785735.0     10
XY25       461635.0      5
SR         297357.0      2

In [30]:
# money to be made conviction-wise
df_portfolio_features.groupby('Conviction')['FTT Amt'].agg(['sum', 'count']).sort_values(by='sum', ascending=False)

                  sum  count
Conviction
H-SC        3565480.0     24
X-LC        1975387.0     21
X-MC        1668912.0     15
M-SC        1461915.0     14
X-SC        1388447.0      9
H-MC         306119.0      2
L-SC         216569.0      2
M-LC         159281.0      1
M-MC         103204.0      2
H-LC          59717.0      1
L-MC          52451.0      1

In [31]:
# money to be made criteria and conviction-wise
df_portfolio_features.groupby(['Conviction', 'Criteria'])['FTT Amt'].agg(['sum', 'count']).sort_values(by='sum', ascending=False)

                           sum  count
Conviction Criteria
H-SC       XY24      1120916.0      6
X-LC       X40       1046554.0     10
H-SC       AR         974804.0      5
M-SC       XY24       859269.0      6
H-SC       XR         830009.0      7
X-SC       XY24       798214.0      4
X-MC       X40        689525.0      7
           X40N       514240.0      4
X-LC       X40N       378495.0      6
X-SC       X40N       375428.0      3
X-LC       XY24       354938.0      2
H-SC       OX40N      342394.0      4
M-SC       OX40N      334290.0      5
H-SC       SR         297357.0      2
X-MC       XY25       252609.0      2
H-MC       XY24       240676.0      1
X-SC       X40        214805.0      2
X-MC       XY24       212538.0      2
M-SC       XR         189173.0      2
M-LC       XR         159281.0      1
X-LC       XY25       147542.0      2
L-SC       OX40N      109051.0      1
           XR         107518.0      1
M-SC       AR          79183.0      1
H-MC       AR          65443.0      1
M-MC       XY25        61484.0      1
H-LC       AR          59717.0      1
L-MC       XR          52451.0      1
X-LC       XR          47858.0      1
M-MC       AR          41720.0      1

In [32]:
# notebook execution time

end_time = time.time()
execution_time = round(end_time - start_time, 0)
print(f"Notebook execution time: {execution_time} seconds")

Notebook execution time: 29.0 seconds