<a href="https://colab.research.google.com/github/ankit-rathi/Quantvesting_v2/blob/main/myStocks_Portfolio_Analysis.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
'''
!pip install pandas==2.2.2 -qq
!pip install pyxirr -qq
!pip install ta -qq
!pip install yfinance==0.2.59 -qq
'''

'\n!pip install pandas==2.2.2 -qq\n!pip install pyxirr -qq\n!pip install ta -qq\n!pip install yfinance==0.2.59 -qq\n'

In [2]:
# import libraries

import numpy as np
import pandas as pd
import datetime
import warnings
warnings.filterwarnings('ignore')
import yfinance as yfin
import ta
import matplotlib.pyplot as plt
import requests

In [3]:
# notebook start time
import time
import datetime
import pytz

start_time = time.time()

# function to print date timestamp
def print_date_time():
  tz_NY = pytz.timezone('Asia/Kolkata')
  datetime_NY = datetime.datetime.now(tz_NY)
  print("Run date time (IST):", datetime_NY.strftime("%Y-%m-%d %H:%M:%S"))

In [4]:
# function to get booked and reserved amount
def get_amt():
  # fetch the JSON data from the URL
  url = "https://raw.githubusercontent.com/ankit-rathi/Tradevesting_v1/main/data/myPortfolioAmts.json"
  response = requests.get(url)
  pf_amts = response.json()  # parse the JSON data

  # extract values from the JSON
  py_booked_amt_dm = pf_amts["py_booked_amt_dm"]
  py_booked_amt_sv = pf_amts["py_booked_amt_sv"]
  cy_booked_amt_dm = pf_amts["cy_booked_amt_dm"]
  cy_booked_amt_sv = pf_amts["cy_booked_amt_sv"]
  reserve_amt_dm = pf_amts["reserve_amt_dm"]
  reserve_amt_sv = pf_amts["reserve_amt_sv"]

  # perform calculations
  py_booked_amt = py_booked_amt_dm + py_booked_amt_sv
  cy_booked_amt = cy_booked_amt_dm + cy_booked_amt_sv
  reserve_amt = reserve_amt_dm + reserve_amt_sv
  total_booked_amt = py_booked_amt + cy_booked_amt

  return total_booked_amt, reserve_amt, cy_booked_amt, py_booked_amt

gen_output = 0

In [5]:
# function to format the amount
def format_amt(number):
    abs_number = abs(number)

    if abs_number >= 1_00_00_000:  # Crores
        formatted_amt = f"{number / 1_00_00_000:.2f} C"
    elif abs_number >= 1_00_000:  # Lakhs
        formatted_amt = f"{number / 1_00_000:.2f} L"
    elif abs_number >= 1_000:  # Thousands
        formatted_amt = f"{number / 1_000:.2f} K"
    else:
        formatted_amt = f"{number:.2f}"

    return formatted_amt

# function to set start and end date
def get_start_end_date():
  start_date = (datetime.date.today() + datetime.timedelta(days=-365)).strftime('%Y-%m-%d')
  end_date = (datetime.date.today() + datetime.timedelta(days=1)).strftime('%Y-%m-%d')
  return start_date, end_date

# function to fetch my portfolio csv
def get_mypfs_df():
  mypfs_df = pd.read_csv('https://raw.githubusercontent.com/ankit-rathi/Tradevesting_v1/main/data/myPortfolioStocks.csv')
  return mypfs_df

# function to fetch my prospects csv
def get_mypps_df():
  mypps_df = pd.read_csv('https://raw.githubusercontent.com/ankit-rathi/Tradevesting_v1/main/data/myProspectsScrips.csv')
  return mypps_df

# function to fetch screener data
def get_myscreen_df():
  myscreen_df = pd.read_csv('https://raw.githubusercontent.com/ankit-rathi/Tradevesting_v1/main/data/myScreenerDB.csv')
  return myscreen_df

# function to fetch momentum data
def get_myinvmt_df():
  myinvmt_df = pd.read_csv('https://raw.githubusercontent.com/ankit-rathi/Tradevesting_v1/main/data/myInvestments.csv')
  return myinvmt_df

# function to get the stock ids
def get_stock_ids(df_pf):
  stock_n100 = df_pf['Symbol'].unique()

  exclude = ['CADILAHC','MMTC', 'MASFIN']

  stock_ids = df_pf[~df_pf['Symbol'].isin(exclude) ]['Symbol'].unique()

  #mypf = mypf[mypf.Forecast.notnull()]
  #stock_ids = mypf['Symbol'].unique()

  #stock_ids.sort()
  return stock_ids

# get features from screener data
def get_screener_features():
  myscreen_df = get_myscreen_df()
  cols = ['Symbol', 'EPS', 'MedPE', 'ROCE%', 'ROE%', 'CapType']
  return myscreen_df[cols]

# get relative strength
def get_relative_strength(stock_list):

    # Dictionary to store stock tickers and their corresponding percentage price change
    stock_changes = {}

    # Loop through each stock and fetch its price data
    for stock in stock_list:
        try:
            # Download the stock data for the given date range
            stock_data = yfin.Ticker(stock + '.NS').history(period='1mo', interval='1d')[map(str.title, ['open', 'close', 'low', 'high', 'volume'])]

            # Calculate the percentage change for the stock
            if len(stock_data) > 0:
                start_price = stock_data['Close'].iloc[0]
                end_price = stock_data['Close'].iloc[-1]
                percent_change = round(((end_price - start_price) / start_price) * 100, 2)
                stock_changes[stock] = percent_change
            else:
                stock_changes[stock] = np.nan  # If no data is available, set to NaN

        except Exception as e:
            print(f"Error fetching data for {stock}: {e}")
            stock_changes[stock] = np.nan

    # Create a DataFrame with stock tickers and their percentage changes
    df = pd.DataFrame(list(stock_changes.items()), columns=['Symbol', 'Percent_Change'])

    # Drop any stocks with missing data (NaN values)
    df = df.dropna()

    # Calculate the percentile rank based on percentage change
    df['RSP'] = round(df['Percent_Change'].rank(pct=True) * 100, 2)
    cols = ['Symbol', 'RSP']
    df = df[cols]
    # Sort by percentile rank (optional)
    df = df.sort_values(by='RSP', ascending=False).reset_index(drop=True)

    return df

In [6]:
# function to get stock technicals
def stock_prec_dev(stock_symbol):
    #stock_symbol = 'ULTRACEMCO.NS'
    short_window = 20
    mid_window = 50
    long_window = 200
    moving_avg = 'SMA'

    start = datetime.datetime(*map(int, start_date.split('-')))
    end = datetime.datetime(*map(int, end_date.split('-')))

    stock_df = yfin.Ticker(stock_symbol + '.NS').history(period='max', interval='1d')[map(str.title, ['open', 'close', 'low', 'high', 'volume'])]

    stock_df['Max'] = round(max(stock_df['Close']),2)
    stock_df = stock_df[(stock_df.index <= end_date) & (stock_df.index >= start_date)]
    stock_df['200_SMA'] = round(stock_df['Close'].rolling(window = 200, min_periods = 1).mean(),0)
    stock_df['Dev%_200'] = round((stock_df['Close'] - stock_df['200_SMA'])*100/stock_df['200_SMA'],2)
    stock_df.dropna(axis = 0, inplace = True) # remove any null rows

    stock_df['20_SMA'] = stock_df['Close'].rolling(window=20).mean()
    stock_df['50_SMA'] = stock_df['Close'].rolling(window=50).mean()
    stock_df['Symbol'] = stock_symbol

    stock_df['Close'] = round(stock_df['Close'],2)
    stock_df['Min'] = round(min(stock_df['Close']),2)
    stock_df['RSI_14'] = ta.momentum.RSIIndicator(close=stock_df['Close'], window=14).rsi()
    stock_df['RSI_14'] = round(stock_df['RSI_14'],0)
    stock_df['Prev_Close'] = stock_df['Close'].shift(1)
    stock_df.drop(['Open', 'Low', 'High', 'Volume'], axis=1, inplace=True)
    stock_df = stock_df.tail(1)

    max_SMA = max(stock_df['20_SMA'].item(), stock_df['50_SMA'].item(), stock_df['200_SMA'].item())
    min_SMA = min(stock_df['20_SMA'].item(), stock_df['50_SMA'].item(), stock_df['200_SMA'].item())
    ABS_Spread = max_SMA - min_SMA
    stock_df['Spread%'] = round((ABS_Spread / stock_df['200_SMA'].item()) * 100,2)

    return stock_df

# function to compute stock attributes
def get_common_features(stock_ids, df_mypf):

  df_prec_dev = pd.DataFrame()
  df_tmp = get_screener_features()
  df_rs = get_relative_strength(stock_ids)

  for stock_id in stock_ids:
      tmp = stock_prec_dev(stock_id)
      tmp = tmp.reset_index()
      df_prec_dev = pd.concat([df_prec_dev, tmp], ignore_index = True)
  df_prec_dev = pd.merge(df_prec_dev, df_mypf, on= 'Symbol')
  df_prec_dev = pd.merge(df_prec_dev, df_tmp, on= 'Symbol', how='left')
  df_prec_dev = pd.merge(df_prec_dev, df_rs, on= 'Symbol', how='left')
  #print(df_prec_dev.columns)
  df_prec_dev['Curr_PE'] = round(df_prec_dev['Close']/df_prec_dev['EPS'],1)
  df_prec_dev['Dev%_PE'] = round((df_prec_dev['Curr_PE'] - df_prec_dev['MedPE'])*100/df_prec_dev['MedPE'],2)
  df_prec_dev['Conviction'] = df_prec_dev['Conviction'] + '-' + df_prec_dev['CapType']
  return df_prec_dev

# function to arrange stock features
def arrange_features(df_stocks, common_cols, diff_cols):
  df_stocks_common = df_stocks[common_cols].drop_duplicates()
  df_stocks_diff = df_stocks[diff_cols]
  df_stocks_diff['Investment'] = df_stocks_diff['AvgCost'] * df_stocks_diff['Shares']
  df_stocks_diff = df_stocks_diff.groupby(['Symbol'])[['Shares', 'Investment']].aggregate(['sum']).reset_index()
  df_stocks_diff.columns = ['Symbol', 'Shares', 'Investment']
  df_stocks_diff['AvgCost'] = round(df_stocks_diff['Investment']/df_stocks_diff['Shares'],2)
  df_stocks = pd.merge(df_stocks_diff, df_stocks_common, on='Symbol')
  return df_stocks

# plot fact distribution across dimension
def plot_pie_chart(df, dimension, fact):
  # grouping the data by category and calculating the sum of fact for each type
  grouped_data = df.groupby(dimension)[fact].sum()

  # sorting the grouped data in descending order
  grouped_data = grouped_data.sort_values(ascending=False)

  # creating a pie chart
  grouped_data.plot.pie(autopct='%1.1f%%', startangle=90, figsize=(6, 6))

  # adding a title and displaying the plot
  plt.title(f'{dimension} {fact} Distribution')
  plt.ylabel('')  # To hide the y-label
  plt.show()

In [7]:
# function to get portfolio features

def get_portfolio_features(df_common_features):

  print_date_time()
  print('-------------------')

  #df_common_features["Target"] = df_common_features["Target"].fillna(df_common_features["Max"])
  df_common_features['NTT'] = np.where(df_common_features['Strategy']== 'NTT', df_common_features["Target"], df_common_features['Max'])
  df_common_features['LTT'] = np.where(df_common_features['Strategy']== 'BTT', df_common_features["Target"], df_common_features['Max'])
  df_common_features['BOL'] = df_common_features['Min']

  tmp_df = df_common_features[df_common_features['Symbol'].isin(mypf_df[mypf_df['InPortfolio'] != 'NA'].Symbol.values)]
  print('qualified stocks: '+str(len(tmp_df['Symbol'].unique())))
  tmp_df1 = tmp_df[tmp_df['LatestQtr'] == 1]
  print('with latest results: '+str(len(tmp_df1['Symbol'].unique())))
  tmp_df1 = tmp_df1[tmp_df1['StarStock'] == 1]
  print('still star stocks: '+str(len(tmp_df1['Symbol'].unique())))
  tmp_df['Investment'] = tmp_df['AvgCost'] * tmp_df['Shares']
  tmp_df['Current'] = round(tmp_df['Close'] * tmp_df['Shares'],0)
  tmp_df['Previous'] = tmp_df['Prev_Close'] * tmp_df['Shares']
  tmp_df['EstimatedST'] = tmp_df['NTT'] * tmp_df['Shares']
  tmp_df['EstimatedLT'] = tmp_df['LTT'] * tmp_df['Shares']
  tmp_df['Current P/L'] = round((tmp_df['Current'] - tmp_df['Investment']),0)
  tmp_df['Today P/L%'] = round((tmp_df['Current'] - tmp_df['Previous'])*100/tmp_df['Previous'],2)
  tmp_df['Current P/L%'] = round((tmp_df['Current'] - tmp_df['Investment'])*100/tmp_df['Investment'],2)
  tmp_df['EstimatedST P/L%'] = round((tmp_df['EstimatedST'] - tmp_df['Investment'])*100/tmp_df['Investment'],2)
  tmp_df['EstimatedLT P/L%'] = round((tmp_df['EstimatedLT'] - tmp_df['Investment'])*100/tmp_df['Investment'],2)
  tmp_df['NTT%'] = round((tmp_df['NTT'] - tmp_df['Close'])*100/tmp_df['Close'],2)
  tmp_df['LTT%'] = round((tmp_df['LTT'] - tmp_df['Close'])*100/tmp_df['Close'],2)
  tmp_df['Gained%'] = round((tmp_df['Close'] - tmp_df['BOL'])*100/tmp_df['BOL'],2)
  investment = round(sum(tmp_df['AvgCost']*tmp_df['Shares']),0)
  current = round(sum(tmp_df['Close']*tmp_df['Shares']),0)
  tmp_df['InitAlloc%'] = round(tmp_df['Investment']*100/investment,2)
  tmp_df['CurrAlloc%'] = round(tmp_df['Current']*100/current,2)
  tmp_df['FTT'] = tmp_df['LTT']
  tmp_df.loc[tmp_df['Strategy'] == 'NTT', 'FTT'] = tmp_df['NTT']
  tmp_df['FTT%'] = tmp_df['LTT%']
  tmp_df.loc[tmp_df['Strategy'] == 'NTT', 'FTT%'] = tmp_df['NTT%']
  tmp_df['FTT Amt'] = round(tmp_df['FTT%'] * tmp_df['Current']/100,0)
  tmp_df['OTT%'] = round((tmp_df['FTT'] - tmp_df['AvgCost'])*100/tmp_df['AvgCost'],2)
  tmp_df['RRR Ind'] = round(tmp_df['Current P/L']/tmp_df['FTT Amt'],2)
  tmp_df['Risk Ind'] = round(tmp_df['Current P/L%']*tmp_df['CurrAlloc%'],0)

  return tmp_df

# function to print portfolio features
def print_portfolio_stats(df_portfolio_features, myinvmt_df):
  from pyxirr import xirr

  total_booked_amt, reserve_amt, cy_booked_amt, py_booked_amt = get_amt()

  dates = myinvmt_df['Date'].values
  dates = np.append(dates, datetime.date.today().strftime('%d-%b-%y'))
  investment = myinvmt_df['Investment'].values
  dates= pd.to_datetime(dates)

  current = round(sum(df_portfolio_features['Close']*df_portfolio_features['Shares']),0) + reserve_amt
  investment_xirr = np.append(investment, current)
  cagr = round(xirr(pd.DataFrame({"dates": dates, "amounts": investment_xirr}))*100,2)

  investment = -sum(investment)
  invested = round(sum(df_portfolio_features['AvgCost']*df_portfolio_features['Shares']),0) + reserve_amt
  previous = round(sum(df_portfolio_features['Prev_Close']*df_portfolio_features['Shares']),0) + reserve_amt
  cy_invested = investment + py_booked_amt

  today_pnl_amount = current-previous
  today_pnl_percentage = round((current-previous)*100/previous,2)

  curr_pnl_amount = current-invested
  curr_pnl_percentage = round((curr_pnl_amount)*100/(cy_invested),2)

  cy_pnl_amount = cy_booked_amt + curr_pnl_amount
  cy_pnl_percentage = round((cy_pnl_amount)*100/cy_invested,2)

  overall_pnl_amount = total_booked_amt + curr_pnl_amount
  overall_pnl_percentage = round((overall_pnl_amount)*100/investment,2)

  estimate_st = round(sum(df_portfolio_features['FTT']*df_portfolio_features['Shares']),0)  + reserve_amt
  est_st_pnl_amount = estimate_st-current
  est_st_pnl_percentage = round((est_st_pnl_amount)*100/current,2)

  estimate_lt = round(sum(df_portfolio_features['LTT']*df_portfolio_features['Shares']),0)  + reserve_amt
  est_lt_pnl_amount = estimate_lt-current
  est_lt_pnl_percentage = round((est_lt_pnl_amount)*100/current,2)

  total_profit = round(sum(df_portfolio_features[df_portfolio_features['Current P/L%'] > 0]['Current']) - sum(df_portfolio_features[df_portfolio_features['Current P/L%'] > 0]['Investment']),0)
  total_loss = round(sum(df_portfolio_features[df_portfolio_features['Current P/L%'] < 0]['Current']) - sum(df_portfolio_features[df_portfolio_features['Current P/L%'] < 0]['Investment']),0)

  cy_booked_percentage = round((cy_booked_amt)*100/current,2)
  py_booked_percentage = round((py_booked_amt)*100/investment,2)
  total_booked_percentage = round((total_booked_amt)*100/investment,2)

  print('-------------------')
  print('Initial Investment: ', format_amt(investment))
  print('CY Investment: ', format_amt(cy_invested))
  print('Reserve: ', format_amt(reserve_amt))
  print('Current: ',  format_amt(current))
  print('-------------------')
  print('Today PnL: '+ '{} ({}%)'.format(format_amt(today_pnl_amount), today_pnl_percentage))
  print('Current PnL: '+ '{} ({}%)'.format(format_amt(curr_pnl_amount), curr_pnl_percentage))
  print('CY Booked + Current PnL: '+ '{} ({}%)'.format(format_amt(cy_pnl_amount), cy_pnl_percentage))
  print('-------------------')
  print('Total profit: ', format_amt(total_profit))
  print('Total loss: ', format_amt(total_loss))
  print('-------------------')
  print('Total Booked + Current PnL: '+ '{} ({}%)'.format(format_amt(overall_pnl_amount), overall_pnl_percentage))
  print('Total Booked PnL: '+ '{} ({}%)'.format(format_amt(total_booked_amt), total_booked_percentage))
  print('Curr Year Booked PnL: '+ '{} ({}%)'.format(format_amt(cy_booked_amt), cy_booked_percentage))
  print('Prev Year Booked PnL: '+ '{} ({}%)'.format(format_amt(py_booked_amt), py_booked_percentage))
  print('===================')
  print('Est FTT: ',  format_amt(estimate_st))
  print('Est FTT PnL: '+ '{} ({}%)'.format(format_amt(est_st_pnl_amount), est_st_pnl_percentage))

  print('===================')
  print('Deployed: ', format_amt(investment))

  print('Current: ', format_amt(current))

  print('CAGR/XIRR %: '+'{}%'.format(cagr))

In [8]:
# get start and end date
start_date, end_date = get_start_end_date()

# get portfolio and prospects data
mypfs_df = get_mypfs_df()
mypps_df = get_mypps_df()
myinvmt_df = get_myinvmt_df()

# merge above datasets
mypf_df = pd.merge(mypfs_df, mypps_df, on="Symbol")

# seggregate dm and sv portfolio
dm_pf = mypf_df[mypf_df['InPortfolio'] == 'DM']
sv_pf = mypf_df[mypf_df['InPortfolio'] == 'SV']

# build portfolio stock dataframe
dm_stocks = get_stock_ids(dm_pf)
sv_stocks = get_stock_ids(sv_pf)
df_stocks = pd.concat([dm_pf,sv_pf], ignore_index = True)

# arrange common and diff stock features
common_cols = ['Symbol', 'Target', 'Criteria', 'Strategy', 'CumlRnk', 'LatestQtr', 'StarStock', 'Conviction', 'Category', 'InFolio', 'XIRR', 'MBQ']
diff_cols = ['Symbol', 'AvgCost', 'Shares']
df_stocks = arrange_features(df_stocks, common_cols, diff_cols)

# get common features
stock_ids = df_stocks['Symbol'].values
df_common_features = get_common_features(stock_ids, df_stocks)

df_common_features.reset_index(drop=True, inplace=True)
df_common_features.drop(['Date'], axis=1, inplace=True)
# get and print portfolio features
df_portfolio_features = get_portfolio_features(df_common_features)

print_portfolio_stats(df_portfolio_features, myinvmt_df)

df = df_portfolio_features
#plot_pie_chart(df, 'CapType', 'Current')
list_ox40n = list(df[df['MBQ'].str.contains('OX40N', na=False)]['Symbol'].values)

Run date time (IST): 2026-08-24 10:31:41
-------------------
qualified stocks: 87
with latest results: 30
still star stocks: 19
-------------------
Initial Investment:  1.46 C
CY Investment:  1.89 C
Reserve:  3.69 L
Current:  1.58 C
-------------------
Today PnL: 13.27 K (0.08%)
Current PnL: -34.92 L (-18.48%)
CY Booked + Current PnL: -29.86 L (-15.81%)
-------------------
Total profit:  3.54 L
Total loss:  -38.46 L
-------------------
Total Booked + Current PnL: 13.01 L (8.91%)
Total Booked PnL: 47.93 L (32.82%)
Curr Year Booked PnL: 5.06 L (3.2%)
Prev Year Booked PnL: 42.87 L (29.35%)
===================
Est FTT:  2.67 C
Est FTT PnL: 1.09 C (69.01%)
===================
Deployed:  1.46 C
Current:  1.58 C
CAGR/XIRR %: 3.55%

In [9]:
# top 5 near their targets
cols = ['Symbol', 'Today P/L%', 'Current P/L%', 'FTT%', 'OTT%', 'FTT Amt', 'Current P/L', 'Current', 'FTT', 'Dev%_PE', 'RSI_14','Conviction', 'Spread%',  'CumlRnk', 'RRR Ind', 'CurrAlloc%', 'Gained%', 'Criteria', 'Strategy', 'Category']
df_tmp = df_portfolio_features[~df_portfolio_features['Symbol'].isin(['ENRIN','BLUSPRING','DIGITIDE'])]
df_tmp = df_tmp.sort_values(by = 'FTT Amt', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
66,SIEMENS,4.01,9.54,1.17,10.83,2385.0,17760.0,203855.0,4125.00,-11.29,68.0,H-LC,14.72,51.0,7.45,1.32,43.83,AR,NTT,ELECTRICAL
78,UNITDSPR,-0.94,13.23,6.66,20.77,17657.0,30977.0,265121.0,1644.00,-3.49,61.0,X-MC,12.11,64.0,1.75,1.72,27.44,X40N,NTT,BREWERIES
77,TTKPRESTIG,-1.29,-24.09,31.85,0.09,24367.0,-24273.0,76504.0,770.00,-7.57,39.0,M-SC,8.48,250.0,-1.00,0.50,37.70,OX40N,NTT,DURABLES
52,M&M,0.75,8.56,9.45,18.82,24691.0,20599.0,261280.0,3762.88,-6.55,59.0,X-LC,5.11,25.0,0.83,1.69,18.52,X40N,ATH,AUTO
67,SIS,0.77,-3.32,25.43,21.26,27297.0,-3690.0,107342.0,528.00,106.30,45.0,H-SC,20.08,168.0,-0.14,0.70,59.60,OX40N,NTT,MISC

In [10]:
# top 5 today
df_tmp = df_portfolio_features.sort_values(by = 'Today P/L%', ascending=False)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
66,SIEMENS,4.01,9.54,1.17,10.83,2385.0,17760.0,203855.0,4125.00,-11.29,68.0,H-LC,14.72,51.0,7.45,1.32,43.83,AR,NTT,ELECTRICAL
81,VALIANTORG,3.29,-35.03,168.03,74.15,178618.0,-57304.0,106301.0,838.00,NaN,58.0,NaN,10.55,145.0,-0.32,0.69,58.19,XR,NTT,CHEMICALS
9,BANDHANBNK,2.91,-13.32,121.99,92.42,294551.0,-37104.0,241455.0,400.00,54.45,52.0,H-SC,10.22,174.0,-0.13,1.56,34.16,XY24,NTT,BANKS
3,ALKYLAMINE,2.65,-10.26,114.56,92.54,103793.0,-10362.0,90601.0,4520.85,NaN,70.0,NaN,16.38,142.0,-0.10,0.59,72.04,SR,ATH,CHEMICALS
25,FINCABLES,1.75,62.44,28.00,107.91,67152.0,92184.0,239828.0,1641.55,18.30,67.0,M-SC,23.58,220.0,1.37,1.55,80.43,OX40N,ATH,CABLES

In [11]:
# bottom 5 today
df_tmp = df_portfolio_features.sort_values(by = 'Today P/L%', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
12,BOSCH-HCIL,-3.51,-27.06,37.08,-0.01,34567.0,-34582.0,93223.0,2282.00,724.78,61.0,M-SC,11.91,231.0,-1.00,0.60,58.68,OX40N,BTT,AC
22,DIXON,-2.05,5.97,30.15,37.92,83327.0,15576.0,276374.0,18931.72,-59.69,60.0,X-MC,16.57,54.0,0.19,1.79,50.38,X40N,ATH,IT
24,EASEMYTRIP,-1.76,-66.11,329.97,45.70,197698.0,-116901.0,59914.0,26.40,NaN,36.0,NaN,8.22,204.0,-0.59,0.39,4.96,XY24,NTT,TRAVEL
10,BATAINDIA,-1.76,-55.57,204.34,35.20,116805.0,-71508.0,57162.0,2096.00,NaN,49.0,NaN,10.13,91.0,-0.61,0.37,18.79,X40,NTT,FOOTWEAR
51,LAOPALA,-1.36,-48.81,171.71,39.09,115240.0,-63992.0,67113.0,464.00,NaN,34.0,NaN,3.18,154.0,-0.56,0.43,6.99,AR,NTT,CERAMICS

In [12]:
# top 5 to exit based on CumlRnk
df_tmp = df_portfolio_features[~df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])]
df_tmp = df_tmp[(df_tmp['Current P/L%'] > -1) & (df_tmp['Current P/L%'] < 1)].sort_values(by = 'CumlRnk', ascending=False)
df_tmp[cols].head()

Empty DataFrame
Columns: [Symbol, Today P/L%, Current P/L%, FTT%, OTT%, FTT Amt, Current P/L, Current, FTT, Dev%_PE, RSI_14, Conviction, Spread%, CumlRnk, RRR Ind, CurrAlloc%, Gained%, Criteria, Strategy, Category]
Index: []

In [13]:
# OX40N stocks to exit
df_tmp = df_portfolio_features[(df_portfolio_features['Symbol'].isin(list_ox40n))].sort_values(by = 'Current P/L%', ascending=False)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
25,FINCABLES,1.75,62.44,28.00,107.91,67152.0,92184.0,239828.0,1641.55,18.30,67.0,M-SC,23.58,220.0,1.37,1.55,80.43,OX40N,ATH,CABLES
67,SIS,0.77,-3.32,25.43,21.26,27297.0,-3690.0,107342.0,528.00,106.30,45.0,H-SC,20.08,168.0,-0.14,0.70,59.60,OX40N,NTT,MISC
43,INDIGOPNTS,0.17,-18.04,22.03,0.02,31519.0,-31488.0,143071.0,1408.00,-21.90,62.0,M-SC,8.42,222.0,-1.00,0.93,62.32,OX40N,NTT,PAINTS
16,CERA,0.14,-23.20,61.32,23.89,82837.0,-40813.0,135090.0,9475.00,NaN,43.0,NaN,12.92,153.0,-0.49,0.88,31.32,OX40N,NTT,CERAMICS
77,TTKPRESTIG,-1.29,-24.09,31.85,0.09,24367.0,-24273.0,76504.0,770.00,-7.57,39.0,M-SC,8.48,250.0,-1.00,0.50,37.70,OX40N,NTT,DURABLES

In [14]:
# top 5 to book for rotation
df_tmp = df_portfolio_features[(df_portfolio_features['Current P/L%'] > 20) ].sort_values(by = 'CumlRnk', ascending=False)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
25,FINCABLES,1.75,62.44,28.0,107.91,67152.0,92184.0,239828.0,1641.55,18.3,67.0,M-SC,23.58,220.0,1.37,1.55,80.43,OX40N,ATH,CABLES

In [15]:
# top 5 to monitor for exit
df_tmp = df_portfolio_features[~df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])]
df_tmp = df_tmp[(df_tmp['Current P/L%'] > 0) ].sort_values(by = 'Dev%_PE', ascending=False)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
25,FINCABLES,1.75,62.44,28.00,107.91,67152.0,92184.0,239828.0,1641.55,18.30,67.0,M-SC,23.58,220.0,1.37,1.55,80.43,OX40N,ATH,CABLES
68,STARHEALTH,-1.08,10.74,32.98,47.26,102668.0,30181.0,311304.0,761.00,-2.33,43.0,H-SC,15.57,173.0,0.29,2.02,34.60,XY24,NTT,INSURANCE

In [16]:
# top 5 to book for rotation from weak conviction
df_tmp = df_portfolio_features[~df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])]
df_tmp = df_tmp[~df_tmp['Criteria'].isin(['XY25','XY24','X40', 'X40N'])].sort_values(by = 'RRR Ind', ascending=False)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
25,FINCABLES,1.75,62.44,28.00,107.91,67152.0,92184.0,239828.0,1641.55,18.3,67.0,M-SC,23.58,220.0,1.37,1.55,80.43,OX40N,ATH,CABLES
3,ALKYLAMINE,2.65,-10.26,114.56,92.54,103793.0,-10362.0,90601.0,4520.85,NaN,70.0,NaN,16.38,142.0,-0.10,0.59,72.04,SR,ATH,CHEMICALS
67,SIS,0.77,-3.32,25.43,21.26,27297.0,-3690.0,107342.0,528.00,106.3,45.0,H-SC,20.08,168.0,-0.14,0.70,59.60,OX40N,NTT,MISC
42,INDIAMART,-0.70,-25.66,170.27,100.92,156121.0,-31646.0,91690.0,4675.60,NaN,35.0,NaN,13.50,140.0,-0.20,0.59,0.00,AR,ATH,MISC
71,TANLA,0.11,-35.46,236.60,117.25,413475.0,-96004.0,174757.0,1922.32,NaN,45.0,NaN,15.05,147.0,-0.23,1.13,53.00,AR,ATH,IT

In [17]:
# top 5 to accumulate based on lowest RSI_14
df_tmp = df_portfolio_features[df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])].sort_values(by = 'RSI_14', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
56,PGHH,-0.50,-38.94,116.21,32.01,151501.0,-83152.0,130368.0,17616.87,-55.19,25.0,X-SC,19.81,57.0,-0.55,0.84,0.00,X40,ATH,FMCG
55,PAGEIND,0.31,-7.17,43.12,32.85,107425.0,-19249.0,249130.0,50936.07,-30.94,31.0,X-MC,8.50,55.0,-0.18,1.61,18.96,X40,ATH,APPARELS
19,COLPAL,0.05,-28.24,94.89,39.86,179342.0,-74365.0,189000.0,3683.41,-13.17,32.0,X-MC,2.87,62.0,-0.41,1.22,6.91,XY25,ATH,FMCG
20,DABUR,-0.36,-21.98,84.19,43.70,162940.0,-54529.0,193539.0,735.00,-32.67,33.0,X-MC,10.63,70.0,-0.33,1.25,0.00,XY24,BTT,FMCG
28,GODREJCP,-0.28,-15.36,57.03,32.90,120448.0,-38336.0,211201.0,1460.97,-16.89,34.0,X-MC,8.11,32.0,-0.32,1.37,2.81,X40N,ATH,FMCG

In [18]:
# top 5 to accumulate based on Spread and CumlRnk
df_tmp = df_portfolio_features[df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])]
df_tmp = df_tmp[(df_tmp['CumlRnk'] < 100)].sort_values(by = 'Spread%', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
50,KOTAKBANK,0.02,5.89,12.30,18.92,31221.0,14125.0,253827.0,452.46,-10.58,62.0,X-LC,2.10,12.0,0.45,1.64,14.20,X40,ATH,BANKS
1,ABBOTINDIA,-0.06,-12.06,31.19,15.37,49059.0,-21565.0,157290.0,34390.26,-28.41,35.0,X-MC,2.56,58.0,-0.44,1.02,6.55,X40,ATH,PHARMA
23,DMART,-0.09,-4.88,38.15,31.42,113149.0,-15200.0,296590.0,5391.45,-20.25,40.0,X-LC,2.56,14.0,-0.13,1.92,7.03,X40N,ATH,FMCG
19,COLPAL,0.05,-28.24,94.89,39.86,179342.0,-74365.0,189000.0,3683.41,-13.17,32.0,X-MC,2.87,62.0,-0.41,1.22,6.91,XY25,ATH,FMCG
53,MARUTI,0.26,-0.99,25.88,24.64,63354.0,-2438.0,244800.0,17120.06,-6.90,44.0,X-LC,3.81,33.0,-0.04,1.59,11.63,XR,ATH,AUTO

In [19]:
# top 5 to accumulate based on lowest Gained%
df_tmp = df_portfolio_features[df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])].sort_values(by = 'Gained%', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
20,DABUR,-0.36,-21.98,84.19,43.70,162940.0,-54529.0,193539.0,735.00,-32.67,33.0,X-MC,10.63,70.0,-0.33,1.25,0.00,XY24,BTT,FMCG
56,PGHH,-0.50,-38.94,116.21,32.01,151501.0,-83152.0,130368.0,17616.87,-55.19,25.0,X-SC,19.81,57.0,-0.55,0.84,0.00,X40,ATH,FMCG
36,HINDUNILVR,0.03,-16.14,44.96,21.56,126876.0,-54319.0,282198.0,2922.00,-42.16,37.0,X-LC,7.09,9.0,-0.43,1.83,0.03,XY25,NTT,FMCG
47,ITC,-0.19,-25.82,68.09,24.70,200671.0,-102564.0,294714.0,452.00,-30.75,35.0,X-LC,10.76,1.0,-0.51,1.91,0.69,X40,NTT,FMCG
83,VOLTAS,-0.47,-3.84,50.99,45.20,94015.0,-7362.0,184380.0,1856.00,32.42,37.0,X-MC,5.40,79.0,-0.08,1.19,1.05,XY25,NTT,AC

In [20]:
# top 5 to accumulate based on lowest CurrAlloc%
df_tmp = df_portfolio_features[df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])].sort_values(by = 'CurrAlloc%', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
56,PGHH,-0.50,-38.94,116.21,32.01,151501.0,-83152.0,130368.0,17616.87,-55.19,25.0,X-SC,19.81,57.0,-0.55,0.84,0.00,X40,ATH,FMCG
1,ABBOTINDIA,-0.06,-12.06,31.19,15.37,49059.0,-21565.0,157290.0,34390.26,-28.41,35.0,X-MC,2.56,58.0,-0.44,1.02,6.55,X40,ATH,PHARMA
2,ACC,0.16,-41.39,198.28,74.81,311577.0,-110988.0,157140.0,3906.00,-41.79,41.0,X-SC,11.33,85.0,-0.36,1.02,4.98,XY24,BTT,CEMENT
40,ICICIPRULI,0.36,-14.47,52.32,30.28,88156.0,-28512.0,168493.0,787.27,-45.16,58.0,X-MC,11.79,78.0,-0.32,1.09,12.26,X40,ATH,INSURANCE
39,ICICIGI,0.53,-13.90,38.08,18.89,65613.0,-27806.0,172303.0,2244.41,-14.07,43.0,X-MC,10.10,66.0,-0.42,1.12,2.65,X40,ATH,INSURANCE

In [21]:
# top 5 to accumulate based on CumlRnk
df_tmp = df_portfolio_features.sort_values(by = 'CumlRnk', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
47,ITC,-0.19,-25.82,68.09,24.70,200671.0,-102564.0,294714.0,452.00,-30.75,35.0,X-LC,10.76,1.0,-0.51,1.91,0.69,X40,NTT,FMCG
73,TCS,-0.10,-32.49,83.98,24.20,262644.0,-150527.0,312746.0,4230.71,-43.98,48.0,X-LC,13.44,2.0,-0.57,2.03,16.62,X40,ATH,IT
45,INFY,1.20,-19.24,73.82,40.38,224447.0,-72424.0,304046.0,1972.00,-40.47,51.0,X-LC,15.48,3.0,-0.32,1.97,15.14,X40,NTT,IT
75,TMPV,0.41,-24.06,87.97,42.75,277992.0,-100099.0,316008.0,600.00,-84.91,35.0,X-LC,4.25,4.0,-0.36,2.05,8.66,XY24,NTT,AUTO
33,HCLTECH,1.19,-11.85,40.62,23.97,110822.0,-36660.0,272826.0,1853.42,-14.26,54.0,X-LC,10.02,8.0,-0.33,1.77,28.74,X40,ATH,IT

In [22]:
# top 5 for average up
df_tmp = df_portfolio_features[(df_portfolio_features['Dev%_200'] > 5)].sort_values(by = 'CurrAlloc%', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
44,INDUSINDBK,0.82,-25.15,77.55,32.89,44814.0,-19420.0,57787.0,1800.00,325.21,52.0,L-MC,11.96,258.0,-0.43,0.37,42.47,XR,NTT,BANKS
30,HAPPSTMNDS,-0.57,-44.82,231.80,83.08,163929.0,-57445.0,70720.0,1466.54,NaN,69.0,NaN,6.74,152.0,-0.35,0.46,32.46,AR,ATH,IT
3,ALKYLAMINE,2.65,-10.26,114.56,92.54,103793.0,-10362.0,90601.0,4520.85,NaN,70.0,NaN,16.38,142.0,-0.10,0.59,72.04,SR,ATH,CHEMICALS
12,BOSCH-HCIL,-3.51,-27.06,37.08,-0.01,34567.0,-34582.0,93223.0,2282.00,724.78,61.0,M-SC,11.91,231.0,-1.00,0.60,58.68,OX40N,BTT,AC
81,VALIANTORG,3.29,-35.03,168.03,74.15,178618.0,-57304.0,106301.0,838.00,NaN,58.0,NaN,10.55,145.0,-0.32,0.69,58.19,XR,NTT,CHEMICALS

In [23]:
# top 5 RSP
df_tmp = df_portfolio_features.sort_values(by = 'RSP', ascending=False)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
25,FINCABLES,1.75,62.44,28.00,107.91,67152.0,92184.0,239828.0,1641.55,18.30,67.0,M-SC,23.58,220.0,1.37,1.55,80.43,OX40N,ATH,CABLES
12,BOSCH-HCIL,-3.51,-27.06,37.08,-0.01,34567.0,-34582.0,93223.0,2282.00,724.78,61.0,M-SC,11.91,231.0,-1.00,0.60,58.68,OX40N,BTT,AC
81,VALIANTORG,3.29,-35.03,168.03,74.15,178618.0,-57304.0,106301.0,838.00,NaN,58.0,NaN,10.55,145.0,-0.32,0.69,58.19,XR,NTT,CHEMICALS
30,HAPPSTMNDS,-0.57,-44.82,231.80,83.08,163929.0,-57445.0,70720.0,1466.54,NaN,69.0,NaN,6.74,152.0,-0.35,0.46,32.46,AR,ATH,IT
3,ALKYLAMINE,2.65,-10.26,114.56,92.54,103793.0,-10362.0,90601.0,4520.85,NaN,70.0,NaN,16.38,142.0,-0.10,0.59,72.04,SR,ATH,CHEMICALS

In [24]:
# Top N allocation
df_tmp = df_portfolio_features.sort_values(by = 'CurrAlloc%', ascending=False)
top_n_values = [10, 25, 50]

sum_df = pd.DataFrame({
    'Top_N': top_n_values,
    'Sum_Alloc%': [df_tmp['CurrAlloc%'].head(n).sum() for n in top_n_values]
})

sum_df

   Top_N  Sum_Alloc%
0     10       19.61
1     25       44.94
2     50       77.61

In [25]:
# market-cap-wise allocation
df_tmp = df_portfolio_features[cols]
df_tmp.groupby(df_tmp['Conviction'].str[-2:])['CurrAlloc%'].sum().sort_values(ascending=False)

Conviction
LC    38.12
MC    22.11
SC    21.61
Name: CurrAlloc%, dtype: float64

In [26]:
# criteria-wise allocation
df_portfolio_features.groupby('Criteria')['CurrAlloc%'].sum().sort_values(ascending=False)

Criteria
X40      26.69
XY24     24.04
X40N     18.65
XR        9.13
OX40N     7.29
XY25      7.14
AR        6.16
SR        0.91
Name: CurrAlloc%, dtype: float64

In [27]:
# conviction-wise allocation
df_portfolio_features.groupby('Conviction')['CurrAlloc%'].sum().sort_values(ascending=False)

Conviction
X-LC    34.38
X-MC    19.55
H-SC     8.58
X-SC     7.64
M-SC     5.39
H-LC     2.92
M-MC     1.16
H-MC     1.03
M-LC     0.82
L-MC     0.37
Name: CurrAlloc%, dtype: float64

In [28]:
# sector-wise stats
df_tmp = df_portfolio_features.groupby('Category')[['CurrAlloc%', 'Current', 'Current P/L', 'FTT Amt']].sum().sort_values(by=['Current', 'Current P/L'], ascending=False)
df_tmp['Current P/L%'] = round(df_tmp['Current P/L'] * 100 / df_tmp['Current'], 2)
df_tmp['FTT%'] = round(df_tmp['FTT Amt'] * 100 / df_tmp['Current'], 2)
cols = ['CurrAlloc%', 'Current P/L%', 'FTT%']
df_tmp[cols].sort_values(by=['CurrAlloc%'], ascending=False)

               CurrAlloc%  Current P/L%    FTT%
Category
FMCG                15.28        -26.35   71.66
IT                  11.25        -37.33  105.44
FINANCE             10.66        -17.27   67.79
AUTO                 8.27         -5.97   43.92
BANKS                6.30         -9.52   56.75
MISC                 5.96        -34.49   88.59
PHARMA               5.83          7.86   18.27
INSURANCE            5.77         -4.38   41.29
PAINTS               5.48        -16.84   36.77
ELECTRICAL           4.23         -8.11   41.96
AC                   1.79        -15.11   46.32
REFINERIES           1.74        -11.26   48.63
BREWERIES            1.72         11.68    6.66
FOOTWEAR             1.68        -70.40  138.72
APPARELS             1.61         -7.73   43.12
CABLES               1.55         38.44   28.00
DURABLES             1.48        -70.54  112.02
TRAVEL               1.42       -104.48  206.87
CERAMICS             1.31        -51.83   97.96
CHEMICALS            1.28        -34.37  143.43
ENGINEERING          1.26        -24.55   81.52
CEMENT               1.02        -70.63  198.28
JEWELLERY            0.95       -118.13  193.92
ENTERTAINMENT        0.72        -74.81  179.06
HEALTHCARE           0.70        -68.59  110.91
TEXTILES             0.39        -51.89   95.20
HOTELS               0.36       -103.93  175.86

In [29]:
# money to be made criteria-wise
df_portfolio_features.groupby('Criteria')['FTT Amt'].agg(['sum', 'count']).sort_values(by='sum', ascending=False)

                sum  count
Criteria
XY24      3620056.0     19
X40       2100422.0     18
XR        1387821.0     13
X40N      1202202.0     12
AR        1055186.0      8
OX40N      667660.0     10
XY25       596965.0      5
SR         274950.0      2

In [30]:
# money to be made conviction-wise
df_portfolio_features.groupby('Conviction')['FTT Amt'].agg(['sum', 'count']).sort_values(by='sum', ascending=False)

                  sum  count
Conviction
X-LC        2421061.0     19
X-MC        1482957.0     14
X-SC        1097678.0      6
H-SC         826577.0      8
M-SC         332268.0      6
H-MC         254849.0      1
M-LC         165920.0      1
M-MC          66446.0      1
L-MC          44814.0      1
H-LC          39726.0      2

In [31]:
# money to be made criteria and conviction-wise
df_portfolio_features.groupby(['Conviction', 'Criteria'])['FTT Amt'].agg(['sum', 'count']).sort_values(by='sum', ascending=False)

                           sum  count
Conviction Criteria
X-LC       X40       1214927.0      9
X-SC       XY24       671997.0      2
H-SC       XY24       518712.0      3
X-MC       X40        513831.0      6
X-LC       XY24       462473.0      2
X-MC       X40N       457584.0      4
X-LC       X40N       423145.0      5
X-MC       XY25       273357.0      2
X-LC       XY25       257162.0      2
X-SC       X40        254859.0      2
H-MC       XY24       254849.0      1
X-MC       XY24       238185.0      2
H-SC       OX40N      219165.0      3
X-SC       X40N       170822.0      2
M-LC       XR         165920.0      1
M-SC       OX40N      157605.0      4
           XY24       116841.0      1
H-SC       XR          88700.0      2
M-MC       XY25        66446.0      1
X-LC       XR          63354.0      1
M-SC       XR          57822.0      1
L-MC       XR          44814.0      1
H-LC       AR          39726.0      2

In [32]:
# notebook execution time

end_time = time.time()
execution_time = round(end_time - start_time, 0)
print(f"Notebook execution time: {execution_time} seconds")

Notebook execution time: 43.0 seconds