<a href="https://colab.research.google.com/github/ankit-rathi/Quantvesting_v2/blob/main/myStocks_Portfolio_Analysis.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
'''
!pip install pandas==2.2.2 -qq
!pip install pyxirr -qq
!pip install ta -qq
!pip install yfinance==0.2.59 -qq
'''

'\n!pip install pandas==2.2.2 -qq\n!pip install pyxirr -qq\n!pip install ta -qq\n!pip install yfinance==0.2.59 -qq\n'

In [2]:
# import libraries

import numpy as np
import pandas as pd
import datetime
import warnings
warnings.filterwarnings('ignore')
import yfinance as yfin
import ta
import matplotlib.pyplot as plt
import requests

In [3]:
# notebook start time
import time
import datetime
import pytz

start_time = time.time()

# function to print date timestamp
def print_date_time():
  tz_NY = pytz.timezone('Asia/Kolkata')
  datetime_NY = datetime.datetime.now(tz_NY)
  print("Run date time (IST):", datetime_NY.strftime("%Y-%m-%d %H:%M:%S"))

In [4]:
# function to get booked and reserved amount
def get_amt():
  # fetch the JSON data from the URL
  url = "https://raw.githubusercontent.com/ankit-rathi/Tradevesting_v1/main/data/myPortfolioAmts.json"
  response = requests.get(url)
  pf_amts = response.json()  # parse the JSON data

  # extract values from the JSON
  py_booked_amt_dm = pf_amts["py_booked_amt_dm"]
  py_booked_amt_sv = pf_amts["py_booked_amt_sv"]
  cy_booked_amt_dm = pf_amts["cy_booked_amt_dm"]
  cy_booked_amt_sv = pf_amts["cy_booked_amt_sv"]
  reserve_amt_dm = pf_amts["reserve_amt_dm"]
  reserve_amt_sv = pf_amts["reserve_amt_sv"]

  # perform calculations
  py_booked_amt = py_booked_amt_dm + py_booked_amt_sv
  cy_booked_amt = cy_booked_amt_dm + cy_booked_amt_sv
  reserve_amt = reserve_amt_dm + reserve_amt_sv
  total_booked_amt = py_booked_amt + cy_booked_amt

  return total_booked_amt, reserve_amt, cy_booked_amt, py_booked_amt

gen_output = 0

In [5]:
# function to format the amount
def format_amt(number):
    abs_number = abs(number)

    if abs_number >= 1_00_00_000:  # Crores
        formatted_amt = f"{number / 1_00_00_000:.2f} C"
    elif abs_number >= 1_00_000:  # Lakhs
        formatted_amt = f"{number / 1_00_000:.2f} L"
    elif abs_number >= 1_000:  # Thousands
        formatted_amt = f"{number / 1_000:.2f} K"
    else:
        formatted_amt = f"{number:.2f}"

    return formatted_amt

# function to set start and end date
def get_start_end_date():
  start_date = (datetime.date.today() + datetime.timedelta(days=-365)).strftime('%Y-%m-%d')
  end_date = (datetime.date.today() + datetime.timedelta(days=1)).strftime('%Y-%m-%d')
  return start_date, end_date

# function to fetch my portfolio csv
def get_mypfs_df():
  mypfs_df = pd.read_csv('https://raw.githubusercontent.com/ankit-rathi/Tradevesting_v1/main/data/myPortfolioStocks.csv')
  return mypfs_df

# function to fetch my prospects csv
def get_mypps_df():
  mypps_df = pd.read_csv('https://raw.githubusercontent.com/ankit-rathi/Tradevesting_v1/main/data/myProspectsScrips.csv')
  return mypps_df

# function to fetch screener data
def get_myscreen_df():
  myscreen_df = pd.read_csv('https://raw.githubusercontent.com/ankit-rathi/Tradevesting_v1/main/data/myScreenerDB.csv')
  return myscreen_df

# function to fetch momentum data
def get_myinvmt_df():
  myinvmt_df = pd.read_csv('https://raw.githubusercontent.com/ankit-rathi/Tradevesting_v1/main/data/myInvestments.csv')
  return myinvmt_df

# function to get the stock ids
def get_stock_ids(df_pf):
  stock_n100 = df_pf['Symbol'].unique()

  exclude = ['CADILAHC','MMTC', 'MASFIN']

  stock_ids = df_pf[~df_pf['Symbol'].isin(exclude) ]['Symbol'].unique()

  #mypf = mypf[mypf.Forecast.notnull()]
  #stock_ids = mypf['Symbol'].unique()

  #stock_ids.sort()
  return stock_ids

# get features from screener data
def get_screener_features():
  myscreen_df = get_myscreen_df()
  cols = ['Symbol', 'EPS', 'MedPE', 'ROCE%', 'ROE%', 'CapType']
  return myscreen_df[cols]

# get relative strength
def get_relative_strength(stock_list):

    # Dictionary to store stock tickers and their corresponding percentage price change
    stock_changes = {}

    # Loop through each stock and fetch its price data
    for stock in stock_list:
        try:
            # Download the stock data for the given date range
            stock_data = yfin.Ticker(stock + '.NS').history(period='1mo', interval='1d')[map(str.title, ['open', 'close', 'low', 'high', 'volume'])]

            # Calculate the percentage change for the stock
            if len(stock_data) > 0:
                start_price = stock_data['Close'].iloc[0]
                end_price = stock_data['Close'].iloc[-1]
                percent_change = round(((end_price - start_price) / start_price) * 100, 2)
                stock_changes[stock] = percent_change
            else:
                stock_changes[stock] = np.nan  # If no data is available, set to NaN

        except Exception as e:
            print(f"Error fetching data for {stock}: {e}")
            stock_changes[stock] = np.nan

    # Create a DataFrame with stock tickers and their percentage changes
    df = pd.DataFrame(list(stock_changes.items()), columns=['Symbol', 'Percent_Change'])

    # Drop any stocks with missing data (NaN values)
    df = df.dropna()

    # Calculate the percentile rank based on percentage change
    df['RSP'] = round(df['Percent_Change'].rank(pct=True) * 100, 2)
    cols = ['Symbol', 'RSP']
    df = df[cols]
    # Sort by percentile rank (optional)
    df = df.sort_values(by='RSP', ascending=False).reset_index(drop=True)

    return df

In [6]:
# function to get stock technicals
def stock_prec_dev(stock_symbol):
    #stock_symbol = 'ULTRACEMCO.NS'
    short_window = 20
    mid_window = 50
    long_window = 200
    moving_avg = 'SMA'

    start = datetime.datetime(*map(int, start_date.split('-')))
    end = datetime.datetime(*map(int, end_date.split('-')))

    stock_df = yfin.Ticker(stock_symbol + '.NS').history(period='max', interval='1d')[map(str.title, ['open', 'close', 'low', 'high', 'volume'])]

    stock_df['Max'] = round(max(stock_df['Close']),2)
    stock_df = stock_df[(stock_df.index <= end_date) & (stock_df.index >= start_date)]
    stock_df['200_SMA'] = round(stock_df['Close'].rolling(window = 200, min_periods = 1).mean(),0)
    stock_df['Dev%_200'] = round((stock_df['Close'] - stock_df['200_SMA'])*100/stock_df['200_SMA'],2)
    stock_df.dropna(axis = 0, inplace = True) # remove any null rows

    stock_df['20_SMA'] = stock_df['Close'].rolling(window=20).mean()
    stock_df['50_SMA'] = stock_df['Close'].rolling(window=50).mean()
    stock_df['Symbol'] = stock_symbol

    stock_df['Close'] = round(stock_df['Close'],2)
    stock_df['Min'] = round(min(stock_df['Close']),2)
    stock_df['RSI_14'] = ta.momentum.RSIIndicator(close=stock_df['Close'], window=14).rsi()
    stock_df['RSI_14'] = round(stock_df['RSI_14'],0)
    stock_df['Prev_Close'] = stock_df['Close'].shift(1)
    stock_df.drop(['Open', 'Low', 'High', 'Volume'], axis=1, inplace=True)
    stock_df = stock_df.tail(1)

    max_SMA = max(stock_df['20_SMA'].item(), stock_df['50_SMA'].item(), stock_df['200_SMA'].item())
    min_SMA = min(stock_df['20_SMA'].item(), stock_df['50_SMA'].item(), stock_df['200_SMA'].item())
    ABS_Spread = max_SMA - min_SMA
    stock_df['Spread%'] = round((ABS_Spread / stock_df['200_SMA'].item()) * 100,2)

    return stock_df

# function to compute stock attributes
def get_common_features(stock_ids, df_mypf):

  df_prec_dev = pd.DataFrame()
  df_tmp = get_screener_features()
  df_rs = get_relative_strength(stock_ids)

  for stock_id in stock_ids:
      tmp = stock_prec_dev(stock_id)
      tmp = tmp.reset_index()
      df_prec_dev = pd.concat([df_prec_dev, tmp], ignore_index = True)
  df_prec_dev = pd.merge(df_prec_dev, df_mypf, on= 'Symbol')
  df_prec_dev = pd.merge(df_prec_dev, df_tmp, on= 'Symbol', how='left')
  df_prec_dev = pd.merge(df_prec_dev, df_rs, on= 'Symbol', how='left')
  #print(df_prec_dev.columns)
  df_prec_dev['Curr_PE'] = round(df_prec_dev['Close']/df_prec_dev['EPS'],1)
  df_prec_dev['Dev%_PE'] = round((df_prec_dev['Curr_PE'] - df_prec_dev['MedPE'])*100/df_prec_dev['MedPE'],2)
  df_prec_dev['Conviction'] = df_prec_dev['Conviction'] + '-' + df_prec_dev['CapType']
  return df_prec_dev

# function to arrange stock features
def arrange_features(df_stocks, common_cols, diff_cols):
  df_stocks_common = df_stocks[common_cols].drop_duplicates()
  df_stocks_diff = df_stocks[diff_cols]
  df_stocks_diff['Investment'] = df_stocks_diff['AvgCost'] * df_stocks_diff['Shares']
  df_stocks_diff = df_stocks_diff.groupby(['Symbol'])[['Shares', 'Investment']].aggregate(['sum']).reset_index()
  df_stocks_diff.columns = ['Symbol', 'Shares', 'Investment']
  df_stocks_diff['AvgCost'] = round(df_stocks_diff['Investment']/df_stocks_diff['Shares'],2)
  df_stocks = pd.merge(df_stocks_diff, df_stocks_common, on='Symbol')
  return df_stocks

# plot fact distribution across dimension
def plot_pie_chart(df, dimension, fact):
  # grouping the data by category and calculating the sum of fact for each type
  grouped_data = df.groupby(dimension)[fact].sum()

  # sorting the grouped data in descending order
  grouped_data = grouped_data.sort_values(ascending=False)

  # creating a pie chart
  grouped_data.plot.pie(autopct='%1.1f%%', startangle=90, figsize=(6, 6))

  # adding a title and displaying the plot
  plt.title(f'{dimension} {fact} Distribution')
  plt.ylabel('')  # To hide the y-label
  plt.show()

In [7]:
# function to get portfolio features

def get_portfolio_features(df_common_features):

  print_date_time()
  print('-------------------')

  #df_common_features["Target"] = df_common_features["Target"].fillna(df_common_features["Max"])
  df_common_features['NTT'] = np.where(df_common_features['Strategy']== 'NTT', df_common_features["Target"], df_common_features['Max'])
  df_common_features['LTT'] = np.where(df_common_features['Strategy']== 'BTT', df_common_features["Target"], df_common_features['Max'])
  df_common_features['BOL'] = df_common_features['Min']

  tmp_df = df_common_features[df_common_features['Symbol'].isin(mypf_df[mypf_df['InPortfolio'] != 'NA'].Symbol.values)]
  print('qualified stocks: '+str(len(tmp_df['Symbol'].unique())))
  tmp_df1 = tmp_df[tmp_df['LatestQtr'] == 1]
  print('with latest results: '+str(len(tmp_df1['Symbol'].unique())))
  tmp_df1 = tmp_df1[tmp_df1['StarStock'] == 1]
  print('still star stocks: '+str(len(tmp_df1['Symbol'].unique())))
  tmp_df['Investment'] = tmp_df['AvgCost'] * tmp_df['Shares']
  tmp_df['Current'] = round(tmp_df['Close'] * tmp_df['Shares'],0)
  tmp_df['Previous'] = tmp_df['Prev_Close'] * tmp_df['Shares']
  tmp_df['EstimatedST'] = tmp_df['NTT'] * tmp_df['Shares']
  tmp_df['EstimatedLT'] = tmp_df['LTT'] * tmp_df['Shares']
  tmp_df['Current P/L'] = round((tmp_df['Current'] - tmp_df['Investment']),0)
  tmp_df['Today P/L%'] = round((tmp_df['Current'] - tmp_df['Previous'])*100/tmp_df['Previous'],2)
  tmp_df['Current P/L%'] = round((tmp_df['Current'] - tmp_df['Investment'])*100/tmp_df['Investment'],2)
  tmp_df['EstimatedST P/L%'] = round((tmp_df['EstimatedST'] - tmp_df['Investment'])*100/tmp_df['Investment'],2)
  tmp_df['EstimatedLT P/L%'] = round((tmp_df['EstimatedLT'] - tmp_df['Investment'])*100/tmp_df['Investment'],2)
  tmp_df['NTT%'] = round((tmp_df['NTT'] - tmp_df['Close'])*100/tmp_df['Close'],2)
  tmp_df['LTT%'] = round((tmp_df['LTT'] - tmp_df['Close'])*100/tmp_df['Close'],2)
  tmp_df['Gained%'] = round((tmp_df['Close'] - tmp_df['BOL'])*100/tmp_df['BOL'],2)
  investment = round(sum(tmp_df['AvgCost']*tmp_df['Shares']),0)
  current = round(sum(tmp_df['Close']*tmp_df['Shares']),0)
  tmp_df['InitAlloc%'] = round(tmp_df['Investment']*100/investment,2)
  tmp_df['CurrAlloc%'] = round(tmp_df['Current']*100/current,2)
  tmp_df['FTT'] = tmp_df['LTT']
  tmp_df.loc[tmp_df['Strategy'] == 'NTT', 'FTT'] = tmp_df['NTT']
  tmp_df['FTT%'] = tmp_df['LTT%']
  tmp_df.loc[tmp_df['Strategy'] == 'NTT', 'FTT%'] = tmp_df['NTT%']
  tmp_df['FTT Amt'] = round(tmp_df['FTT%'] * tmp_df['Current']/100,0)
  tmp_df['OTT%'] = round((tmp_df['FTT'] - tmp_df['AvgCost'])*100/tmp_df['AvgCost'],2)
  tmp_df['RRR Ind'] = round(tmp_df['Current P/L']/tmp_df['FTT Amt'],2)
  tmp_df['Risk Ind'] = round(tmp_df['Current P/L%']*tmp_df['CurrAlloc%'],0)

  return tmp_df

# function to print portfolio features
def print_portfolio_stats(df_portfolio_features, myinvmt_df):
  from pyxirr import xirr

  total_booked_amt, reserve_amt, cy_booked_amt, py_booked_amt = get_amt()

  dates = myinvmt_df['Date'].values
  dates = np.append(dates, datetime.date.today().strftime('%d-%b-%y'))
  investment = myinvmt_df['Investment'].values
  dates= pd.to_datetime(dates)

  current = round(sum(df_portfolio_features['Close']*df_portfolio_features['Shares']),0) + reserve_amt
  investment_xirr = np.append(investment, current)
  cagr = round(xirr(pd.DataFrame({"dates": dates, "amounts": investment_xirr}))*100,2)

  investment = -sum(investment)
  invested = round(sum(df_portfolio_features['AvgCost']*df_portfolio_features['Shares']),0) + reserve_amt
  previous = round(sum(df_portfolio_features['Prev_Close']*df_portfolio_features['Shares']),0) + reserve_amt
  cy_invested = investment + py_booked_amt

  today_pnl_amount = current-previous
  today_pnl_percentage = round((current-previous)*100/previous,2)

  curr_pnl_amount = current-invested
  curr_pnl_percentage = round((curr_pnl_amount)*100/(cy_invested),2)

  cy_pnl_amount = cy_booked_amt + curr_pnl_amount
  cy_pnl_percentage = round((cy_pnl_amount)*100/cy_invested,2)

  overall_pnl_amount = total_booked_amt + curr_pnl_amount
  overall_pnl_percentage = round((overall_pnl_amount)*100/investment,2)

  estimate_st = round(sum(df_portfolio_features['FTT']*df_portfolio_features['Shares']),0)  + reserve_amt
  est_st_pnl_amount = estimate_st-current
  est_st_pnl_percentage = round((est_st_pnl_amount)*100/current,2)

  estimate_lt = round(sum(df_portfolio_features['LTT']*df_portfolio_features['Shares']),0)  + reserve_amt
  est_lt_pnl_amount = estimate_lt-current
  est_lt_pnl_percentage = round((est_lt_pnl_amount)*100/current,2)

  total_profit = round(sum(df_portfolio_features[df_portfolio_features['Current P/L%'] > 0]['Current']) - sum(df_portfolio_features[df_portfolio_features['Current P/L%'] > 0]['Investment']),0)
  total_loss = round(sum(df_portfolio_features[df_portfolio_features['Current P/L%'] < 0]['Current']) - sum(df_portfolio_features[df_portfolio_features['Current P/L%'] < 0]['Investment']),0)

  cy_booked_percentage = round((cy_booked_amt)*100/current,2)
  py_booked_percentage = round((py_booked_amt)*100/investment,2)
  total_booked_percentage = round((total_booked_amt)*100/investment,2)

  print('-------------------')
  print('Initial Investment: ', format_amt(investment))
  print('CY Investment: ', format_amt(cy_invested))
  print('Reserve: ', format_amt(reserve_amt))
  print('Current: ',  format_amt(current))
  print('-------------------')
  print('Today PnL: '+ '{} ({}%)'.format(format_amt(today_pnl_amount), today_pnl_percentage))
  print('Current PnL: '+ '{} ({}%)'.format(format_amt(curr_pnl_amount), curr_pnl_percentage))
  print('CY Booked + Current PnL: '+ '{} ({}%)'.format(format_amt(cy_pnl_amount), cy_pnl_percentage))
  print('-------------------')
  print('Total profit: ', format_amt(total_profit))
  print('Total loss: ', format_amt(total_loss))
  print('-------------------')
  print('Total Booked + Current PnL: '+ '{} ({}%)'.format(format_amt(overall_pnl_amount), overall_pnl_percentage))
  print('Total Booked PnL: '+ '{} ({}%)'.format(format_amt(total_booked_amt), total_booked_percentage))
  print('Curr Year Booked PnL: '+ '{} ({}%)'.format(format_amt(cy_booked_amt), cy_booked_percentage))
  print('Prev Year Booked PnL: '+ '{} ({}%)'.format(format_amt(py_booked_amt), py_booked_percentage))
  print('===================')
  print('Est FTT: ',  format_amt(estimate_st))
  print('Est FTT PnL: '+ '{} ({}%)'.format(format_amt(est_st_pnl_amount), est_st_pnl_percentage))

  print('===================')
  print('Deployed: ', format_amt(investment))

  print('Current: ', format_amt(current))

  print('CAGR/XIRR %: '+'{}%'.format(cagr))

In [8]:
# get start and end date
start_date, end_date = get_start_end_date()

# get portfolio and prospects data
mypfs_df = get_mypfs_df()
mypps_df = get_mypps_df()
myinvmt_df = get_myinvmt_df()

# merge above datasets
mypf_df = pd.merge(mypfs_df, mypps_df, on="Symbol")

# seggregate dm and sv portfolio
dm_pf = mypf_df[mypf_df['InPortfolio'] == 'DM']
sv_pf = mypf_df[mypf_df['InPortfolio'] == 'SV']

# build portfolio stock dataframe
dm_stocks = get_stock_ids(dm_pf)
sv_stocks = get_stock_ids(sv_pf)
df_stocks = pd.concat([dm_pf,sv_pf], ignore_index = True)

# arrange common and diff stock features
common_cols = ['Symbol', 'Target', 'Criteria', 'Strategy', 'CumlRnk', 'LatestQtr', 'StarStock', 'Conviction', 'Category', 'InFolio', 'XIRR', 'MBQ']
diff_cols = ['Symbol', 'AvgCost', 'Shares']
df_stocks = arrange_features(df_stocks, common_cols, diff_cols)

# get common features
stock_ids = df_stocks['Symbol'].values
df_common_features = get_common_features(stock_ids, df_stocks)

df_common_features.reset_index(drop=True, inplace=True)
df_common_features.drop(['Date'], axis=1, inplace=True)
# get and print portfolio features
df_portfolio_features = get_portfolio_features(df_common_features)

print_portfolio_stats(df_portfolio_features, myinvmt_df)

df = df_portfolio_features
#plot_pie_chart(df, 'CapType', 'Current')
list_ox40n = list(df[df['MBQ'].str.contains('OX40N', na=False)]['Symbol'].values)

Run date time (IST): 2026-05-15 16:52:00
-------------------
qualified stocks: 92
with latest results: 31
still star stocks: 20
-------------------
Initial Investment:  1.40 C
CY Investment:  1.82 C
Reserve:  1.49 K
Current:  1.48 C
-------------------
Today PnL: 7.34 K (0.05%)
Current PnL: -34.94 L (-19.16%)
CY Booked + Current PnL: -32.86 L (-18.02%)
-------------------
Total profit:  2.01 L
Total loss:  -36.95 L
-------------------
Total Booked + Current PnL: 10.01 L (7.18%)
Total Booked PnL: 44.95 L (32.22%)
Curr Year Booked PnL: 2.08 L (1.4%)
Prev Year Booked PnL: 42.87 L (30.73%)
===================
Est FTT:  2.55 C
Est FTT PnL: 1.07 C (72.31%)
===================
Deployed:  1.40 C
Current:  1.48 C
CAGR/XIRR %: 2.96%

In [9]:
# top 5 near their targets
cols = ['Symbol', 'Today P/L%', 'Current P/L%', 'FTT%', 'OTT%', 'FTT Amt', 'Current P/L', 'Current', 'FTT', 'Dev%_PE', 'RSI_14','Conviction', 'Spread%',  'CumlRnk', 'RRR Ind', 'CurrAlloc%', 'Gained%', 'Criteria', 'Strategy', 'Category']
df_tmp = df_portfolio_features[~df_portfolio_features['Symbol'].isin(['ENRIN','BLUSPRING','DIGITIDE'])]
df_tmp = df_tmp.sort_values(by = 'FTT Amt', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
59,PIDILITIND,-1.09,4.01,13.80,18.37,20254.0,5660.0,146770.0,1670.26,-27.20,61.0,X-LC,5.61,5.0,0.28,0.99,15.24,X40,ATH,CHEMICALS
55,MASFIN,-1.74,-2.20,24.31,21.57,23294.0,-2160.0,95820.0,397.04,-15.54,44.0,H-SC,5.72,167.0,-0.09,0.65,18.94,XR,ATH,FINANCE
51,KOTAKBANK,1.00,3.42,17.10,21.11,24489.0,4736.0,143208.0,453.24,-11.14,58.0,X-LC,7.40,12.0,0.19,0.97,9.52,X40,ATH,BANKS
17,CIPLA,-0.32,15.94,16.17,34.69,28715.0,24419.0,177580.0,1663.60,-10.44,70.0,X-LC,10.89,18.0,0.85,1.20,20.10,X40N,ATH,PHARMA
53,M&M,-1.60,1.34,21.75,23.38,30567.0,1859.0,140540.0,3802.40,-14.09,46.0,X-LC,8.38,25.0,0.06,0.95,6.55,X40N,ATH,AUTO

In [10]:
# top 5 today
df_tmp = df_portfolio_features.sort_values(by = 'Today P/L%', ascending=False)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
69,SFL,11.34,-40.48,112.74,26.63,175961.0,-106141.0,156077.0,1287.0,18.16,66.0,M-SC,13.07,242.0,-0.60,1.05,30.08,XY24,NTT,MISC
5,ATULAUTO,5.87,-10.68,62.97,45.57,110881.0,-21046.0,176086.0,844.0,3818.92,65.0,M-SC,7.71,248.0,-0.19,1.19,35.50,XY24,NTT,AUTO
81,TMPV,5.25,-18.84,68.28,36.58,197197.0,-67035.0,288806.0,600.0,-83.62,57.0,X-LC,5.98,4.0,-0.34,1.95,20.37,XY24,NTT,AUTO
86,VALIANTORG,4.44,-38.36,182.54,74.15,184081.0,-62761.0,100844.0,838.0,-281.53,59.0,H-SC,12.14,145.0,-0.34,0.68,50.07,XR,NTT,CHEMICALS
84,UNITDSPR,3.79,-2.98,24.48,20.77,55609.0,-6984.0,227160.0,1644.0,-14.02,54.0,X-MC,3.02,64.0,-0.13,1.53,8.36,X40N,NTT,BREWERIES

In [11]:
# bottom 5 today
df_tmp = df_portfolio_features.sort_values(by = 'Today P/L%', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
88,VOLTAS,-4.86,-3.72,50.81,45.20,93798.0,-7137.0,184605.0,1856.00,10.16,33.0,X-MC,1.24,79.0,-0.08,1.25,0.86,XY25,NTT,AC
24,EASEMYTRIP,-4.35,-56.35,233.75,45.70,180422.0,-99629.0,77186.0,26.40,-19.77,53.0,M-SC,7.11,204.0,-0.55,0.52,35.21,XY24,NTT,TRAVEL
29,GREENPANEL,-3.47,-45.98,164.96,43.14,163150.0,-84175.0,98903.0,537.00,121.58,39.0,M-SC,16.67,225.0,-0.52,0.67,18.81,XY24,NTT,MISC
77,TANLA,-3.00,-43.78,286.40,117.25,436001.0,-118526.0,152235.0,1922.32,-43.33,47.0,H-SC,15.16,147.0,-0.27,1.03,33.29,AR,ATH,IT
71,SIEMENS,-2.87,-3.60,30.20,25.51,54177.0,-6700.0,179395.0,4671.50,50.66,48.0,H-LC,17.08,51.0,-0.12,1.21,25.95,AR,ATH,ELECTRICAL

In [12]:
# top 5 to exit based on CumlRnk
df_tmp = df_portfolio_features[~df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])]
df_tmp = df_tmp[(df_tmp['Current P/L%'] > -1) & (df_tmp['Current P/L%'] < 1)].sort_values(by = 'CumlRnk', ascending=False)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
73,SONACOMS,-2.38,-0.78,40.18,39.09,40329.0,-788.0,100371.0,804.02,-21.42,50.0,M-MC,19.5,193.0,-0.02,0.68,41.99,AR,ATH,AUTO

In [13]:
# OX40N stocks to exit
df_tmp = df_portfolio_features[(df_portfolio_features['Symbol'].isin(list_ox40n))].sort_values(by = 'Current P/L%', ascending=False)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
25,FINCABLES,-2.18,33.10,56.20,107.91,110443.0,48874.0,196518.0,1641.55,19.74,59.0,M-SC,23.89,220.0,0.44,1.33,47.85,OX40N,ATH,CABLES
72,SIS,1.25,-10.37,35.30,21.26,35128.0,-11518.0,99514.0,528.00,2365.80,66.0,H-SC,13.56,168.0,-0.33,0.67,47.96,OX40N,NTT,MISC
50,KANSAINER,0.05,-25.89,53.10,13.47,106127.0,-69804.0,199863.0,340.00,-36.25,68.0,H-SC,14.75,162.0,-0.66,1.35,39.61,XY24,NTT,PAINTS
16,CERA,-0.95,-26.31,68.13,23.89,88307.0,-46287.0,129616.0,9475.00,-28.88,57.0,H-SC,9.09,153.0,-0.52,0.87,24.56,OX40N,NTT,CERAMICS
43,INDIGOPNTS,0.79,-30.01,42.90,0.02,52414.0,-52382.0,122177.0,1408.00,86.38,69.0,M-SC,20.31,222.0,-1.00,0.82,38.62,OX40N,NTT,PAINTS

In [14]:
# top 5 to book for rotation
df_tmp = df_portfolio_features[(df_portfolio_features['Current P/L%'] > 20) ].sort_values(by = 'CumlRnk', ascending=False)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
25,FINCABLES,-2.18,33.10,56.20,107.91,110443.0,48874.0,196518.0,1641.55,19.74,59.0,M-SC,23.89,220.0,0.44,1.33,47.85,OX40N,ATH,CABLES
68,SATIN,-0.63,23.79,22.66,51.83,77499.0,65726.0,342010.0,274.00,10.38,82.0,H-SC,25.04,159.0,0.85,2.31,66.61,XY24,NTT,FINANCE

In [15]:
# top 5 to monitor for exit
df_tmp = df_portfolio_features[~df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])]
df_tmp = df_tmp[(df_tmp['Current P/L%'] > 0) ].sort_values(by = 'Dev%_PE', ascending=False)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
25,FINCABLES,-2.18,33.10,56.20,107.91,110443.0,48874.0,196518.0,1641.55,19.74,59.0,M-SC,23.89,220.0,0.44,1.33,47.85,OX40N,ATH,CABLES
68,SATIN,-0.63,23.79,22.66,51.83,77499.0,65726.0,342010.0,274.00,10.38,82.0,H-SC,25.04,159.0,0.85,2.31,66.61,XY24,NTT,FINANCE
91,ZYDUSLIFE,2.02,6.69,27.13,35.63,60659.0,14012.0,223586.0,1286.17,-7.21,70.0,H-MC,3.04,120.0,0.23,1.51,17.56,AR,ATH,PHARMA

In [16]:
# top 5 to book for rotation from weak conviction
df_tmp = df_portfolio_features[~df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])]
df_tmp = df_tmp[~df_tmp['Criteria'].isin(['XY25','XY24','X40', 'X40N'])].sort_values(by = 'RRR Ind', ascending=False)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
25,FINCABLES,-2.18,33.10,56.20,107.91,110443.0,48874.0,196518.0,1641.55,19.74,59.0,M-SC,23.89,220.0,0.44,1.33,47.85,OX40N,ATH,CABLES
91,ZYDUSLIFE,2.02,6.69,27.13,35.63,60659.0,14012.0,223586.0,1286.17,-7.21,70.0,H-MC,3.04,120.0,0.23,1.51,17.56,AR,ATH,PHARMA
73,SONACOMS,-2.38,-0.78,40.18,39.09,40329.0,-788.0,100371.0,804.02,-21.42,50.0,M-MC,19.50,193.0,-0.02,0.68,41.99,AR,ATH,AUTO
55,MASFIN,-1.74,-2.20,24.31,21.57,23294.0,-2160.0,95820.0,397.04,-15.54,44.0,H-SC,5.72,167.0,-0.09,0.65,18.94,XR,ATH,FINANCE
42,INDIAMART,-0.75,-15.93,145.88,106.72,151269.0,-19642.0,103694.0,4810.62,-62.11,30.0,H-SC,9.44,140.0,-0.13,0.70,0.00,AR,ATH,MISC

In [17]:
# top 5 to accumulate based on lowest RSI_14
df_tmp = df_portfolio_features[df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])].sort_values(by = 'RSI_14', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
33,HCLTECH,0.77,-26.50,65.31,21.51,116133.0,-64106.0,177818.0,1872.35,-22.66,27.0,X-LC,16.49,8.0,-0.55,1.20,0.77,X40,ATH,IT
79,TCS,0.80,-33.54,90.44,26.57,278468.0,-155369.0,307904.0,4311.59,-43.63,30.0,X-LC,15.78,2.0,-0.56,2.08,0.80,X40,ATH,IT
88,VOLTAS,-4.86,-3.72,50.81,45.20,93798.0,-7137.0,184605.0,1856.00,10.16,33.0,X-MC,1.24,79.0,-0.08,1.25,0.86,XY25,NTT,AC
45,INFY,2.19,-23.82,76.23,34.24,181692.0,-74541.0,238347.0,1972.00,-40.13,34.0,X-LC,18.16,3.0,-0.41,1.61,2.19,X40,NTT,IT
65,RELIANCE,-1.86,-14.21,46.06,25.30,79406.0,-28567.0,172396.0,1952.00,-16.57,39.0,X-LC,3.59,21.0,-0.36,1.16,2.44,XY25,BTT,REFINERIES

In [18]:
# top 5 to accumulate based on Spread and CumlRnk
df_tmp = df_portfolio_features[df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])]
df_tmp = df_tmp[(df_tmp['CumlRnk'] < 100)].sort_values(by = 'Spread%', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
88,VOLTAS,-4.86,-3.72,50.81,45.20,93798.0,-7137.0,184605.0,1856.00,10.16,33.0,X-MC,1.24,79.0,-0.08,1.25,0.86,XY25,NTT,AC
84,UNITDSPR,3.79,-2.98,24.48,20.77,55609.0,-6984.0,227160.0,1644.00,-14.02,54.0,X-MC,3.02,64.0,-0.13,1.53,8.36,X40N,NTT,BREWERIES
65,RELIANCE,-1.86,-14.21,46.06,25.30,79406.0,-28567.0,172396.0,1952.00,-16.57,39.0,X-LC,3.59,21.0,-0.36,1.16,2.44,XY25,BTT,REFINERIES
39,ICICIGI,-0.74,-2.79,22.76,19.34,44275.0,-5578.0,194531.0,2252.93,-18.12,55.0,X-MC,4.73,66.0,-0.13,1.31,8.65,X40,ATH,INSURANCE
19,COLPAL,0.62,-17.98,72.54,41.51,156686.0,-47365.0,216000.0,3726.84,-0.69,58.0,X-MC,5.40,62.0,-0.30,1.46,20.76,XY25,ATH,FMCG

In [19]:
# top 5 to accumulate based on lowest Gained%
df_tmp = df_portfolio_features[df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])].sort_values(by = 'Gained%', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
33,HCLTECH,0.77,-26.50,65.31,21.51,116133.0,-64106.0,177818.0,1872.35,-22.66,27.0,X-LC,16.49,8.0,-0.55,1.20,0.77,X40,ATH,IT
79,TCS,0.80,-33.54,90.44,26.57,278468.0,-155369.0,307904.0,4311.59,-43.63,30.0,X-LC,15.78,2.0,-0.56,2.08,0.80,X40,ATH,IT
88,VOLTAS,-4.86,-3.72,50.81,45.20,93798.0,-7137.0,184605.0,1856.00,10.16,33.0,X-MC,1.24,79.0,-0.08,1.25,0.86,XY25,NTT,AC
45,INFY,2.19,-23.82,76.23,34.24,181692.0,-74541.0,238347.0,1972.00,-40.13,34.0,X-LC,18.16,3.0,-0.41,1.61,2.19,X40,NTT,IT
65,RELIANCE,-1.86,-14.21,46.06,25.30,79406.0,-28567.0,172396.0,1952.00,-16.57,39.0,X-LC,3.59,21.0,-0.36,1.16,2.44,XY25,BTT,REFINERIES

In [20]:
# top 5 to accumulate based on lowest CurrAlloc%
df_tmp = df_portfolio_features[df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])].sort_values(by = 'CurrAlloc%', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
64,RELAXO,-0.89,-62.65,307.77,52.31,166870.0,-90941.0,54219.0,1176.00,-60.22,43.0,X-SC,25.01,92.0,-0.54,0.37,21.23,X40N,NTT,FOOTWEAR
10,BATAINDIA,-1.62,-55.23,201.97,35.20,116355.0,-71060.0,57610.0,2096.00,-24.48,39.0,X-SC,26.21,91.0,-0.61,0.39,14.26,X40,NTT,FOOTWEAR
60,QUESS,-2.00,-16.75,108.90,73.90,96813.0,-17892.0,88901.0,424.00,-55.37,51.0,X-SC,12.13,80.0,-0.18,0.60,21.19,XY24,NTT,MISC
28,GODREJCP,0.57,-7.00,41.36,31.47,57165.0,-10400.0,138214.0,1469.04,-2.14,45.0,X-LC,7.63,32.0,-0.18,0.93,6.05,X40N,ATH,FMCG
53,M&M,-1.60,1.34,21.75,23.38,30567.0,1859.0,140540.0,3802.40,-14.09,46.0,X-LC,8.38,25.0,0.06,0.95,6.55,X40N,ATH,AUTO

In [21]:
# top 5 to accumulate based on CumlRnk
df_tmp = df_portfolio_features.sort_values(by = 'CumlRnk', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
47,ITC,0.73,-18.49,46.07,19.06,127737.0,-62899.0,277267.0,452.00,-55.12,54.0,X-LC,15.51,1.0,-0.49,1.87,7.56,X40,NTT,FMCG
79,TCS,0.80,-33.54,90.44,26.57,278468.0,-155369.0,307904.0,4311.59,-43.63,30.0,X-LC,15.78,2.0,-0.56,2.08,0.80,X40,ATH,IT
45,INFY,2.19,-23.82,76.23,34.24,181692.0,-74541.0,238347.0,1972.00,-40.13,34.0,X-LC,18.16,3.0,-0.41,1.61,2.19,X40,NTT,IT
81,TMPV,5.25,-18.84,68.28,36.58,197197.0,-67035.0,288806.0,600.00,-83.62,57.0,X-LC,5.98,4.0,-0.34,1.95,20.37,XY24,NTT,AUTO
59,PIDILITIND,-1.09,4.01,13.80,18.37,20254.0,5660.0,146770.0,1670.26,-27.20,61.0,X-LC,5.61,5.0,0.28,0.99,15.24,X40,ATH,CHEMICALS

In [22]:
# top 5 for average up
df_tmp = df_portfolio_features[(df_portfolio_features['Dev%_200'] > 5)].sort_values(by = 'CurrAlloc%', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
44,INDUSINDBK,-2.37,-34.56,103.07,32.89,52076.0,-26682.0,50525.0,1800.00,-338.10,49.0,L-MC,7.59,258.0,-0.51,0.34,24.36,XR,NTT,BANKS
72,SIS,1.25,-10.37,35.30,21.26,35128.0,-11518.0,99514.0,528.00,2365.80,66.0,H-SC,13.56,168.0,-0.33,0.67,47.96,OX40N,NTT,MISC
73,SONACOMS,-2.38,-0.78,40.18,39.09,40329.0,-788.0,100371.0,804.02,-21.42,50.0,M-MC,19.50,193.0,-0.02,0.68,41.99,AR,ATH,AUTO
75,SURYODAY,-2.71,-4.69,29.09,23.03,49650.0,-8394.0,170677.0,216.00,86.40,63.0,H-SC,15.38,166.0,-0.17,1.15,43.70,XR,NTT,BANKS
5,ATULAUTO,5.87,-10.68,62.97,45.57,110881.0,-21046.0,176086.0,844.00,3818.92,65.0,M-SC,7.71,248.0,-0.19,1.19,35.50,XY24,NTT,AUTO

In [23]:
# top 5 RSP
df_tmp = df_portfolio_features.sort_values(by = 'RSP', ascending=False)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
68,SATIN,-0.63,23.79,22.66,51.83,77499.0,65726.0,342010.0,274.00,10.38,82.0,H-SC,25.04,159.0,0.85,2.31,66.61,XY24,NTT,FINANCE
3,ALKYLAMINE,-1.57,-26.63,163.92,93.63,121419.0,-26891.0,74072.0,4546.37,-21.40,63.0,H-SC,16.13,142.0,-0.22,0.50,39.87,SR,ATH,CHEMICALS
72,SIS,1.25,-10.37,35.30,21.26,35128.0,-11518.0,99514.0,528.00,2365.80,66.0,H-SC,13.56,168.0,-0.33,0.67,47.96,OX40N,NTT,MISC
75,SURYODAY,-2.71,-4.69,29.09,23.03,49650.0,-8394.0,170677.0,216.00,86.40,63.0,H-SC,15.38,166.0,-0.17,1.15,43.70,XR,NTT,BANKS
25,FINCABLES,-2.18,33.10,56.20,107.91,110443.0,48874.0,196518.0,1641.55,19.74,59.0,M-SC,23.89,220.0,0.44,1.33,47.85,OX40N,ATH,CABLES

In [24]:
# Top N allocation
df_tmp = df_portfolio_features.sort_values(by = 'CurrAlloc%', ascending=False)
top_n_values = [10, 25, 50]

sum_df = pd.DataFrame({
    'Top_N': top_n_values,
    'Sum_Alloc%': [df_tmp['CurrAlloc%'].head(n).sum() for n in top_n_values]
})

sum_df

   Top_N  Sum_Alloc%
0     10       19.28
1     25       42.89
2     50       73.07

In [25]:
# market-cap-wise allocation
df_tmp = df_portfolio_features[cols]
df_tmp.groupby(df_tmp['Conviction'].str[-2:])['CurrAlloc%'].sum().sort_values(ascending=False)

Conviction
SC    42.49
LC    31.46
MC    26.06
Name: CurrAlloc%, dtype: float64

In [26]:
# criteria-wise allocation
df_portfolio_features.groupby('Criteria')['CurrAlloc%'].sum().sort_values(ascending=False)

Criteria
XY24     27.68
X40      25.57
X40N     16.80
XR        8.86
OX40N     6.94
XY25      6.68
AR        6.64
SR        0.84
Name: CurrAlloc%, dtype: float64

In [27]:
# conviction-wise allocation
df_portfolio_features.groupby('Conviction')['CurrAlloc%'].sum().sort_values(ascending=False)

Conviction
X-LC    29.36
H-SC    22.16
X-MC    21.07
M-SC    10.12
X-SC     9.69
H-MC     2.69
M-MC     1.96
H-LC     1.21
M-LC     0.89
L-SC     0.52
L-MC     0.34
Name: CurrAlloc%, dtype: float64

In [28]:
# sector-wise stats
df_tmp = df_portfolio_features.groupby('Category')[['CurrAlloc%', 'Current', 'Current P/L', 'FTT Amt']].sum().sort_values(by=['Current', 'Current P/L'], ascending=False)
df_tmp['Current P/L%'] = round(df_tmp['Current P/L'] * 100 / df_tmp['Current'], 2)
df_tmp['FTT%'] = round(df_tmp['FTT Amt'] * 100 / df_tmp['Current'], 2)
cols = ['CurrAlloc%', 'Current P/L%', 'FTT%']
df_tmp[cols].sort_values(by=['CurrAlloc%'], ascending=False)

               CurrAlloc%  Current P/L%    FTT%
Category
FMCG                15.53        -14.91   55.41
FINANCE             10.83        -14.86   64.82
IT                  10.02        -51.79  128.21
MISC                 6.97        -29.94   86.39
AUTO                 6.76         -9.39   50.40
BANKS                5.68         -8.03   57.99
PAINTS               5.67        -17.14   37.48
INSURANCE            5.34         -4.66   40.27
PHARMA               5.16          3.02   28.16
ELECTRICAL           3.90        -22.24   65.76
CHEMICALS            2.17        -26.11  101.26
HEALTHCARE           2.01        -20.35   51.75
AC                   1.77        -21.87   54.91
APPARELS             1.74         -4.13   39.65
TRAVEL               1.70        -77.58  166.49
DURABLES             1.68        -54.49   92.08
FOOTWEAR             1.67        -78.51  150.09
BREWERIES            1.53         -3.07   24.48
REALTY               1.36         -9.97   28.04
CERAMICS             1.33        -55.60  102.87
CABLES               1.33         24.87   56.20
ENGINEERING          1.17        -39.16  102.80
REFINERIES           1.16        -16.57   46.06
CEMENT               1.10        -63.96  186.62
JEWELLERY            1.01       -114.02  188.38
ENTERTAINMENT        0.69        -87.03  198.57
TEXTILES             0.41        -51.22   94.33
HOTELS               0.32       -142.68  228.27

In [29]:
# money to be made criteria-wise
df_portfolio_features.groupby('Criteria')['FTT Amt'].agg(['sum', 'count']).sort_values(by='sum', ascending=False)

                sum  count
Criteria
XY24      3494482.0     21
X40       1915025.0     19
XR        1367678.0     13
X40N      1235233.0     13
AR        1201505.0      9
OX40N      760991.0     10
XY25       449962.0      5
SR         294324.0      2

In [30]:
# money to be made conviction-wise
df_portfolio_features.groupby('Conviction')['FTT Amt'].agg(['sum', 'count']).sort_values(by='sum', ascending=False)

                  sum  count
Conviction
H-SC        3500698.0     24
X-LC        1946603.0     21
X-MC        1612053.0     15
M-SC        1414799.0     14
X-SC        1368900.0      9
H-MC         299641.0      2
L-SC         214990.0      2
M-LC         159847.0      1
M-MC          95416.0      2
H-LC          54177.0      1
L-MC          52076.0      1

In [31]:
# money to be made criteria and conviction-wise
df_portfolio_features.groupby(['Conviction', 'Criteria'])['FTT Amt'].agg(['sum', 'count']).sort_values(by='sum', ascending=False)

                           sum  count
Conviction Criteria
H-SC       XY24      1082344.0      6
X-LC       X40       1042604.0     10
H-SC       AR         968130.0      5
M-SC       XY24       835511.0      6
H-SC       XR         816462.0      7
X-SC       XY24       788809.0      4
X-MC       X40        660889.0      7
           X40N       501438.0      4
X-SC       X40N       368559.0      3
X-LC       X40N       365236.0      6
           XY24       349594.0      2
H-SC       OX40N      339438.0      4
M-SC       OX40N      313371.0      5
H-SC       SR         294324.0      2
X-MC       XY25       250484.0      2
H-MC       XY24       238982.0      1
X-SC       X40        211532.0      2
X-MC       XY24       199242.0      2
M-SC       XR         187707.0      2
M-LC       XR         159847.0      1
X-LC       XY25       144391.0      2
L-SC       OX40N      108182.0      1
           XR         106808.0      1
M-SC       AR          78210.0      1
H-MC       AR          60659.0      1
M-MC       XY25        55087.0      1
H-LC       AR          54177.0      1
L-MC       XR          52076.0      1
X-LC       XR          44778.0      1
M-MC       AR          40329.0      1

In [32]:
# notebook execution time

end_time = time.time()
execution_time = round(end_time - start_time, 0)
print(f"Notebook execution time: {execution_time} seconds")

Notebook execution time: 55.0 seconds