<a href="https://colab.research.google.com/github/ankit-rathi/Quantvesting_v2/blob/main/myStocks_Portfolio_Analysis.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
'''
!pip install pandas==2.2.2 -qq
!pip install pyxirr -qq
!pip install ta -qq
!pip install yfinance==0.2.59 -qq
'''

'\n!pip install pandas==2.2.2 -qq\n!pip install pyxirr -qq\n!pip install ta -qq\n!pip install yfinance==0.2.59 -qq\n'

In [2]:
# import libraries

import numpy as np
import pandas as pd
import datetime
import warnings
warnings.filterwarnings('ignore')
import yfinance as yfin
import ta
import matplotlib.pyplot as plt
import requests

In [3]:
# notebook start time
import time
import datetime
import pytz

start_time = time.time()

# function to print date timestamp
def print_date_time():
  tz_NY = pytz.timezone('Asia/Kolkata')
  datetime_NY = datetime.datetime.now(tz_NY)
  print("Run date time (IST):", datetime_NY.strftime("%Y-%m-%d %H:%M:%S"))

In [4]:
# function to get booked and reserved amount
def get_amt():
  # fetch the JSON data from the URL
  url = "https://raw.githubusercontent.com/ankit-rathi/Tradevesting_v1/main/data/myPortfolioAmts.json"
  response = requests.get(url)
  pf_amts = response.json()  # parse the JSON data

  # extract values from the JSON
  py_booked_amt_dm = pf_amts["py_booked_amt_dm"]
  py_booked_amt_sv = pf_amts["py_booked_amt_sv"]
  cy_booked_amt_dm = pf_amts["cy_booked_amt_dm"]
  cy_booked_amt_sv = pf_amts["cy_booked_amt_sv"]
  reserve_amt_dm = pf_amts["reserve_amt_dm"]
  reserve_amt_sv = pf_amts["reserve_amt_sv"]

  # perform calculations
  py_booked_amt = py_booked_amt_dm + py_booked_amt_sv
  cy_booked_amt = cy_booked_amt_dm + cy_booked_amt_sv
  reserve_amt = reserve_amt_dm + reserve_amt_sv
  total_booked_amt = py_booked_amt + cy_booked_amt

  return total_booked_amt, reserve_amt, cy_booked_amt, py_booked_amt

gen_output = 0

In [5]:
# function to format the amount
def format_amt(number):
    abs_number = abs(number)

    if abs_number >= 1_00_00_000:  # Crores
        formatted_amt = f"{number / 1_00_00_000:.2f} C"
    elif abs_number >= 1_00_000:  # Lakhs
        formatted_amt = f"{number / 1_00_000:.2f} L"
    elif abs_number >= 1_000:  # Thousands
        formatted_amt = f"{number / 1_000:.2f} K"
    else:
        formatted_amt = f"{number:.2f}"

    return formatted_amt

# function to set start and end date
def get_start_end_date():
  start_date = (datetime.date.today() + datetime.timedelta(days=-365)).strftime('%Y-%m-%d')
  end_date = (datetime.date.today() + datetime.timedelta(days=1)).strftime('%Y-%m-%d')
  return start_date, end_date

# function to fetch my portfolio csv
def get_mypfs_df():
  mypfs_df = pd.read_csv('https://raw.githubusercontent.com/ankit-rathi/Tradevesting_v1/main/data/myPortfolioStocks.csv')
  return mypfs_df

# function to fetch my prospects csv
def get_mypps_df():
  mypps_df = pd.read_csv('https://raw.githubusercontent.com/ankit-rathi/Tradevesting_v1/main/data/myProspectsScrips.csv')
  return mypps_df

# function to fetch screener data
def get_myscreen_df():
  myscreen_df = pd.read_csv('https://raw.githubusercontent.com/ankit-rathi/Tradevesting_v1/main/data/myScreenerDB.csv')
  return myscreen_df

# function to fetch momentum data
def get_myinvmt_df():
  myinvmt_df = pd.read_csv('https://raw.githubusercontent.com/ankit-rathi/Tradevesting_v1/main/data/myInvestments.csv')
  return myinvmt_df

# function to get the stock ids
def get_stock_ids(df_pf):
  stock_n100 = df_pf['Symbol'].unique()

  exclude = ['CADILAHC','MMTC', 'MASFIN']

  stock_ids = df_pf[~df_pf['Symbol'].isin(exclude) ]['Symbol'].unique()

  #mypf = mypf[mypf.Forecast.notnull()]
  #stock_ids = mypf['Symbol'].unique()

  #stock_ids.sort()
  return stock_ids

# get features from screener data
def get_screener_features():
  myscreen_df = get_myscreen_df()
  cols = ['Symbol', 'EPS', 'MedPE', 'ROCE%', 'ROE%', 'CapType']
  return myscreen_df[cols]

# get relative strength
def get_relative_strength(stock_list):

    # Dictionary to store stock tickers and their corresponding percentage price change
    stock_changes = {}

    # Loop through each stock and fetch its price data
    for stock in stock_list:
        try:
            # Download the stock data for the given date range
            stock_data = yfin.Ticker(stock + '.NS').history(period='1mo', interval='1d')[map(str.title, ['open', 'close', 'low', 'high', 'volume'])]

            # Calculate the percentage change for the stock
            if len(stock_data) > 0:
                start_price = stock_data['Close'].iloc[0]
                end_price = stock_data['Close'].iloc[-1]
                percent_change = round(((end_price - start_price) / start_price) * 100, 2)
                stock_changes[stock] = percent_change
            else:
                stock_changes[stock] = np.nan  # If no data is available, set to NaN

        except Exception as e:
            print(f"Error fetching data for {stock}: {e}")
            stock_changes[stock] = np.nan

    # Create a DataFrame with stock tickers and their percentage changes
    df = pd.DataFrame(list(stock_changes.items()), columns=['Symbol', 'Percent_Change'])

    # Drop any stocks with missing data (NaN values)
    df = df.dropna()

    # Calculate the percentile rank based on percentage change
    df['RSP'] = round(df['Percent_Change'].rank(pct=True) * 100, 2)
    cols = ['Symbol', 'RSP']
    df = df[cols]
    # Sort by percentile rank (optional)
    df = df.sort_values(by='RSP', ascending=False).reset_index(drop=True)

    return df

In [6]:
# function to get stock technicals
def stock_prec_dev(stock_symbol):
    #stock_symbol = 'ULTRACEMCO.NS'
    short_window = 20
    mid_window = 50
    long_window = 200
    moving_avg = 'SMA'

    start = datetime.datetime(*map(int, start_date.split('-')))
    end = datetime.datetime(*map(int, end_date.split('-')))

    stock_df = yfin.Ticker(stock_symbol + '.NS').history(period='max', interval='1d')[map(str.title, ['open', 'close', 'low', 'high', 'volume'])]

    stock_df['Max'] = round(max(stock_df['Close']),2)
    stock_df = stock_df[(stock_df.index <= end_date) & (stock_df.index >= start_date)]
    stock_df['200_SMA'] = round(stock_df['Close'].rolling(window = 200, min_periods = 1).mean(),0)
    stock_df['Dev%_200'] = round((stock_df['Close'] - stock_df['200_SMA'])*100/stock_df['200_SMA'],2)
    stock_df.dropna(axis = 0, inplace = True) # remove any null rows

    stock_df['20_SMA'] = stock_df['Close'].rolling(window=20).mean()
    stock_df['50_SMA'] = stock_df['Close'].rolling(window=50).mean()
    stock_df['Symbol'] = stock_symbol

    stock_df['Close'] = round(stock_df['Close'],2)
    stock_df['Min'] = round(min(stock_df['Close']),2)
    stock_df['RSI_14'] = ta.momentum.RSIIndicator(close=stock_df['Close'], window=14).rsi()
    stock_df['RSI_14'] = round(stock_df['RSI_14'],0)
    stock_df['Prev_Close'] = stock_df['Close'].shift(1)
    stock_df.drop(['Open', 'Low', 'High', 'Volume'], axis=1, inplace=True)
    stock_df = stock_df.tail(1)

    max_SMA = max(stock_df['20_SMA'].item(), stock_df['50_SMA'].item(), stock_df['200_SMA'].item())
    min_SMA = min(stock_df['20_SMA'].item(), stock_df['50_SMA'].item(), stock_df['200_SMA'].item())
    ABS_Spread = max_SMA - min_SMA
    stock_df['Spread%'] = round((ABS_Spread / stock_df['200_SMA'].item()) * 100,2)

    return stock_df

# function to compute stock attributes
def get_common_features(stock_ids, df_mypf):

  df_prec_dev = pd.DataFrame()
  df_tmp = get_screener_features()
  df_rs = get_relative_strength(stock_ids)

  for stock_id in stock_ids:
      tmp = stock_prec_dev(stock_id)
      tmp = tmp.reset_index()
      df_prec_dev = pd.concat([df_prec_dev, tmp], ignore_index = True)
  df_prec_dev = pd.merge(df_prec_dev, df_mypf, on= 'Symbol')
  df_prec_dev = pd.merge(df_prec_dev, df_tmp, on= 'Symbol', how='left')
  df_prec_dev = pd.merge(df_prec_dev, df_rs, on= 'Symbol', how='left')
  #print(df_prec_dev.columns)
  df_prec_dev['Curr_PE'] = round(df_prec_dev['Close']/df_prec_dev['EPS'],1)
  df_prec_dev['Dev%_PE'] = round((df_prec_dev['Curr_PE'] - df_prec_dev['MedPE'])*100/df_prec_dev['MedPE'],2)
  df_prec_dev['Conviction'] = df_prec_dev['Conviction'] + '-' + df_prec_dev['CapType']
  return df_prec_dev

# function to arrange stock features
def arrange_features(df_stocks, common_cols, diff_cols):
  df_stocks_common = df_stocks[common_cols].drop_duplicates()
  df_stocks_diff = df_stocks[diff_cols]
  df_stocks_diff['Investment'] = df_stocks_diff['AvgCost'] * df_stocks_diff['Shares']
  df_stocks_diff = df_stocks_diff.groupby(['Symbol'])[['Shares', 'Investment']].aggregate(['sum']).reset_index()
  df_stocks_diff.columns = ['Symbol', 'Shares', 'Investment']
  df_stocks_diff['AvgCost'] = round(df_stocks_diff['Investment']/df_stocks_diff['Shares'],2)
  df_stocks = pd.merge(df_stocks_diff, df_stocks_common, on='Symbol')
  return df_stocks

# plot fact distribution across dimension
def plot_pie_chart(df, dimension, fact):
  # grouping the data by category and calculating the sum of fact for each type
  grouped_data = df.groupby(dimension)[fact].sum()

  # sorting the grouped data in descending order
  grouped_data = grouped_data.sort_values(ascending=False)

  # creating a pie chart
  grouped_data.plot.pie(autopct='%1.1f%%', startangle=90, figsize=(6, 6))

  # adding a title and displaying the plot
  plt.title(f'{dimension} {fact} Distribution')
  plt.ylabel('')  # To hide the y-label
  plt.show()

In [7]:
# function to get portfolio features

def get_portfolio_features(df_common_features):

  print_date_time()
  print('-------------------')

  #df_common_features["Target"] = df_common_features["Target"].fillna(df_common_features["Max"])
  df_common_features['NTT'] = np.where(df_common_features['Strategy']== 'NTT', df_common_features["Target"], df_common_features['Max'])
  df_common_features['LTT'] = np.where(df_common_features['Strategy']== 'BTT', df_common_features["Target"], df_common_features['Max'])
  df_common_features['BOL'] = df_common_features['Min']

  tmp_df = df_common_features[df_common_features['Symbol'].isin(mypf_df[mypf_df['InPortfolio'] != 'NA'].Symbol.values)]
  print('qualified stocks: '+str(len(tmp_df['Symbol'].unique())))
  tmp_df1 = tmp_df[tmp_df['LatestQtr'] == 1]
  print('with latest results: '+str(len(tmp_df1['Symbol'].unique())))
  tmp_df1 = tmp_df1[tmp_df1['StarStock'] == 1]
  print('still star stocks: '+str(len(tmp_df1['Symbol'].unique())))
  tmp_df['Investment'] = tmp_df['AvgCost'] * tmp_df['Shares']
  tmp_df['Current'] = round(tmp_df['Close'] * tmp_df['Shares'],0)
  tmp_df['Previous'] = tmp_df['Prev_Close'] * tmp_df['Shares']
  tmp_df['EstimatedST'] = tmp_df['NTT'] * tmp_df['Shares']
  tmp_df['EstimatedLT'] = tmp_df['LTT'] * tmp_df['Shares']
  tmp_df['Current P/L'] = round((tmp_df['Current'] - tmp_df['Investment']),0)
  tmp_df['Today P/L%'] = round((tmp_df['Current'] - tmp_df['Previous'])*100/tmp_df['Previous'],2)
  tmp_df['Current P/L%'] = round((tmp_df['Current'] - tmp_df['Investment'])*100/tmp_df['Investment'],2)
  tmp_df['EstimatedST P/L%'] = round((tmp_df['EstimatedST'] - tmp_df['Investment'])*100/tmp_df['Investment'],2)
  tmp_df['EstimatedLT P/L%'] = round((tmp_df['EstimatedLT'] - tmp_df['Investment'])*100/tmp_df['Investment'],2)
  tmp_df['NTT%'] = round((tmp_df['NTT'] - tmp_df['Close'])*100/tmp_df['Close'],2)
  tmp_df['LTT%'] = round((tmp_df['LTT'] - tmp_df['Close'])*100/tmp_df['Close'],2)
  tmp_df['Gained%'] = round((tmp_df['Close'] - tmp_df['BOL'])*100/tmp_df['BOL'],2)
  investment = round(sum(tmp_df['AvgCost']*tmp_df['Shares']),0)
  current = round(sum(tmp_df['Close']*tmp_df['Shares']),0)
  tmp_df['InitAlloc%'] = round(tmp_df['Investment']*100/investment,2)
  tmp_df['CurrAlloc%'] = round(tmp_df['Current']*100/current,2)
  tmp_df['FTT'] = tmp_df['LTT']
  tmp_df.loc[tmp_df['Strategy'] == 'NTT', 'FTT'] = tmp_df['NTT']
  tmp_df['FTT%'] = tmp_df['LTT%']
  tmp_df.loc[tmp_df['Strategy'] == 'NTT', 'FTT%'] = tmp_df['NTT%']
  tmp_df['FTT Amt'] = round(tmp_df['FTT%'] * tmp_df['Current']/100,0)
  tmp_df['OTT%'] = round((tmp_df['FTT'] - tmp_df['AvgCost'])*100/tmp_df['AvgCost'],2)
  tmp_df['RRR Ind'] = round(tmp_df['Current P/L']/tmp_df['FTT Amt'],2)
  tmp_df['Risk Ind'] = round(tmp_df['Current P/L%']*tmp_df['CurrAlloc%'],0)

  return tmp_df

# function to print portfolio features
def print_portfolio_stats(df_portfolio_features, myinvmt_df):
  from pyxirr import xirr

  total_booked_amt, reserve_amt, cy_booked_amt, py_booked_amt = get_amt()

  dates = myinvmt_df['Date'].values
  dates = np.append(dates, datetime.date.today().strftime('%d-%b-%y'))
  investment = myinvmt_df['Investment'].values
  dates= pd.to_datetime(dates)

  current = round(sum(df_portfolio_features['Close']*df_portfolio_features['Shares']),0) + reserve_amt
  investment_xirr = np.append(investment, current)
  cagr = round(xirr(pd.DataFrame({"dates": dates, "amounts": investment_xirr}))*100,2)

  investment = -sum(investment)
  invested = round(sum(df_portfolio_features['AvgCost']*df_portfolio_features['Shares']),0) + reserve_amt
  previous = round(sum(df_portfolio_features['Prev_Close']*df_portfolio_features['Shares']),0) + reserve_amt
  cy_invested = investment + py_booked_amt

  today_pnl_amount = current-previous
  today_pnl_percentage = round((current-previous)*100/previous,2)

  curr_pnl_amount = current-invested
  curr_pnl_percentage = round((curr_pnl_amount)*100/(cy_invested),2)

  cy_pnl_amount = cy_booked_amt + curr_pnl_amount
  cy_pnl_percentage = round((cy_pnl_amount)*100/cy_invested,2)

  overall_pnl_amount = total_booked_amt + curr_pnl_amount
  overall_pnl_percentage = round((overall_pnl_amount)*100/investment,2)

  estimate_st = round(sum(df_portfolio_features['FTT']*df_portfolio_features['Shares']),0)  + reserve_amt
  est_st_pnl_amount = estimate_st-current
  est_st_pnl_percentage = round((est_st_pnl_amount)*100/current,2)

  estimate_lt = round(sum(df_portfolio_features['LTT']*df_portfolio_features['Shares']),0)  + reserve_amt
  est_lt_pnl_amount = estimate_lt-current
  est_lt_pnl_percentage = round((est_lt_pnl_amount)*100/current,2)

  total_profit = round(sum(df_portfolio_features[df_portfolio_features['Current P/L%'] > 0]['Current']) - sum(df_portfolio_features[df_portfolio_features['Current P/L%'] > 0]['Investment']),0)
  total_loss = round(sum(df_portfolio_features[df_portfolio_features['Current P/L%'] < 0]['Current']) - sum(df_portfolio_features[df_portfolio_features['Current P/L%'] < 0]['Investment']),0)

  cy_booked_percentage = round((cy_booked_amt)*100/current,2)
  py_booked_percentage = round((py_booked_amt)*100/investment,2)
  total_booked_percentage = round((total_booked_amt)*100/investment,2)

  print('-------------------')
  print('Initial Investment: ', format_amt(investment))
  print('CY Investment: ', format_amt(cy_invested))
  print('Reserve: ', format_amt(reserve_amt))
  print('Current: ',  format_amt(current))
  print('-------------------')
  print('Today PnL: '+ '{} ({}%)'.format(format_amt(today_pnl_amount), today_pnl_percentage))
  print('Current PnL: '+ '{} ({}%)'.format(format_amt(curr_pnl_amount), curr_pnl_percentage))
  print('CY Booked + Current PnL: '+ '{} ({}%)'.format(format_amt(cy_pnl_amount), cy_pnl_percentage))
  print('-------------------')
  print('Total profit: ', format_amt(total_profit))
  print('Total loss: ', format_amt(total_loss))
  print('-------------------')
  print('Total Booked + Current PnL: '+ '{} ({}%)'.format(format_amt(overall_pnl_amount), overall_pnl_percentage))
  print('Total Booked PnL: '+ '{} ({}%)'.format(format_amt(total_booked_amt), total_booked_percentage))
  print('Curr Year Booked PnL: '+ '{} ({}%)'.format(format_amt(cy_booked_amt), cy_booked_percentage))
  print('Prev Year Booked PnL: '+ '{} ({}%)'.format(format_amt(py_booked_amt), py_booked_percentage))
  print('===================')
  print('Est FTT: ',  format_amt(estimate_st))
  print('Est FTT PnL: '+ '{} ({}%)'.format(format_amt(est_st_pnl_amount), est_st_pnl_percentage))

  print('===================')
  print('Deployed: ', format_amt(investment))

  print('Current: ', format_amt(current))

  print('CAGR/XIRR %: '+'{}%'.format(cagr))

In [8]:
# get start and end date
start_date, end_date = get_start_end_date()

# get portfolio and prospects data
mypfs_df = get_mypfs_df()
mypps_df = get_mypps_df()
myinvmt_df = get_myinvmt_df()

# merge above datasets
mypf_df = pd.merge(mypfs_df, mypps_df, on="Symbol")

# seggregate dm and sv portfolio
dm_pf = mypf_df[mypf_df['InPortfolio'] == 'DM']
sv_pf = mypf_df[mypf_df['InPortfolio'] == 'SV']

# build portfolio stock dataframe
dm_stocks = get_stock_ids(dm_pf)
sv_stocks = get_stock_ids(sv_pf)
df_stocks = pd.concat([dm_pf,sv_pf], ignore_index = True)

# arrange common and diff stock features
common_cols = ['Symbol', 'Target', 'Criteria', 'Strategy', 'CumlRnk', 'LatestQtr', 'StarStock', 'Conviction', 'Category', 'InFolio', 'XIRR', 'MBQ']
diff_cols = ['Symbol', 'AvgCost', 'Shares']
df_stocks = arrange_features(df_stocks, common_cols, diff_cols)

# get common features
stock_ids = df_stocks['Symbol'].values
df_common_features = get_common_features(stock_ids, df_stocks)

df_common_features.reset_index(drop=True, inplace=True)
df_common_features.drop(['Date'], axis=1, inplace=True)
# get and print portfolio features
df_portfolio_features = get_portfolio_features(df_common_features)

print_portfolio_stats(df_portfolio_features, myinvmt_df)

df = df_portfolio_features
#plot_pie_chart(df, 'CapType', 'Current')
list_ox40n = list(df[df['MBQ'].str.contains('OX40N', na=False)]['Symbol'].values)

Run date time (IST): 2026-06-16 12:56:07
-------------------
qualified stocks: 92
with latest results: 31
still star stocks: 20
-------------------
Initial Investment:  1.40 C
CY Investment:  1.82 C
Reserve:  1.49 K
Current:  1.51 C
-------------------
Today PnL: 27.44 K (0.18%)
Current PnL: -32.67 L (-17.91%)
CY Booked + Current PnL: -30.59 L (-16.77%)
-------------------
Total profit:  2.77 L
Total loss:  -35.44 L
-------------------
Total Booked + Current PnL: 12.28 L (8.8%)
Total Booked PnL: 44.95 L (32.22%)
Curr Year Booked PnL: 2.08 L (1.38%)
Prev Year Booked PnL: 42.87 L (30.73%)
===================
Est FTT:  2.55 C
Est FTT PnL: 1.05 C (69.54%)
===================
Deployed:  1.40 C
Current:  1.51 C
CAGR/XIRR %: 3.56%

In [9]:
# top 5 near their targets
cols = ['Symbol', 'Today P/L%', 'Current P/L%', 'FTT%', 'OTT%', 'FTT Amt', 'Current P/L', 'Current', 'FTT', 'Dev%_PE', 'RSI_14','Conviction', 'Spread%',  'CumlRnk', 'RRR Ind', 'CurrAlloc%', 'Gained%', 'Criteria', 'Strategy', 'Category']
df_tmp = df_portfolio_features[~df_portfolio_features['Symbol'].isin(['ENRIN','BLUSPRING','DIGITIDE'])]
df_tmp = df_tmp.sort_values(by = 'FTT Amt', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
59,PIDILITIND,-1.08,10.13,7.47,18.37,11609.0,14300.0,155410.0,1670.26,-22.84,68.0,X-LC,3.65,5.0,1.23,1.03,22.02,X40,ATH,CHEMICALS
51,KOTAKBANK,0.39,8.84,11.27,21.11,16986.0,12248.0,150720.0,453.24,-6.81,70.0,X-LC,5.95,12.0,0.72,1.00,15.27,X40,ATH,BANKS
55,MASFIN,0.51,-4.26,26.97,21.57,25301.0,-4170.0,93810.0,397.04,-17.34,52.0,H-SC,3.51,167.0,-0.16,0.62,11.82,XR,ATH,FINANCE
72,SIS,-0.10,-1.86,23.57,21.26,25682.0,-2070.0,108962.0,528.00,2600.00,64.0,H-SC,21.85,168.0,-0.08,0.72,62.01,OX40N,NTT,MISC
53,M&M,0.12,1.82,21.18,23.38,29907.0,2525.0,141206.0,3802.40,-13.74,56.0,X-LC,10.54,25.0,0.08,0.94,7.06,X40N,ATH,AUTO

In [10]:
# top 5 today
df_tmp = df_portfolio_features.sort_values(by = 'Today P/L%', ascending=False)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
61,RAJESHEXPO,5.00,-83.73,514.91,0.07,114949.0,-114853.0,22324.0,518.00,718.18,33.0,L-SC,34.70,268.0,-1.00,0.15,10.25,OX40N,NTT,JEWELLERY
0,5PAISA,3.06,-37.84,81.62,12.90,110860.0,-82672.0,135824.0,593.00,99.52,56.0,H-SC,2.67,170.0,-0.75,0.90,31.07,OX40N,NTT,FINANCE
67,ROUTE,3.02,-58.83,308.45,68.16,168975.0,-78284.0,54782.0,2215.45,-66.75,58.0,H-SC,17.27,141.0,-0.46,0.36,30.51,SR,ATH,IT
6,AWL,2.90,-32.26,146.57,67.02,353748.0,-114958.0,241351.0,485.00,-63.54,57.0,X-SC,14.87,81.0,-0.32,1.60,14.16,XY24,NTT,FMCG
27,GLAXO,2.34,-12.80,55.61,35.69,96637.0,-25508.0,173776.0,3380.16,-33.48,42.0,X-MC,10.22,56.0,-0.26,1.15,3.28,X40,ATH,PHARMA

In [11]:
# bottom 5 today
df_tmp = df_portfolio_features.sort_values(by = 'Today P/L%', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
18,COFFEEDAY,-2.16,-44.18,142.35,35.27,90220.0,-50170.0,63379.0,80.00,-57.75,53.0,L-SC,15.50,266.0,-0.56,0.42,56.30,XR,NTT,HOTELS
3,ALKYLAMINE,-1.97,-24.23,155.56,93.63,118999.0,-24466.0,76497.0,4546.37,-18.90,54.0,H-SC,7.82,142.0,-0.21,0.51,44.45,SR,ATH,CHEMICALS
21,DEN,-1.97,-45.31,159.79,42.07,73810.0,-38272.0,46192.0,75.00,63.21,61.0,M-SC,9.02,235.0,-0.52,0.31,25.63,AR,NTT,ENTERTAINMENT
81,TMPV,-1.88,-11.46,54.26,36.58,170946.0,-40791.0,315050.0,600.00,-81.44,56.0,X-LC,12.89,4.0,-0.24,2.09,31.31,XY24,NTT,AUTO
38,HYUNDAI,-1.77,6.02,40.87,49.35,66832.0,9283.0,163524.0,2809.30,-14.57,63.0,X-LC,15.23,29.0,0.14,1.09,17.90,X40N,ATH,AUTO

In [12]:
# top 5 to exit based on CumlRnk
df_tmp = df_portfolio_features[~df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])]
df_tmp = df_tmp[(df_tmp['Current P/L%'] > -1) & (df_tmp['Current P/L%'] < 1)].sort_values(by = 'CumlRnk', ascending=False)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
9,BANDHANBNK,-1.40,0.02,92.38,92.42,257383.0,54.0,278613.0,400.0,139.22,58.0,H-SC,21.39,174.0,0.00,1.85,53.48,XY24,NTT,BANKS
75,SURYODAY,1.15,-0.97,24.24,23.03,42986.0,-1734.0,177337.0,216.0,92.98,61.0,H-SC,18.39,166.0,-0.04,1.18,49.31,XR,NTT,BANKS

In [13]:
# OX40N stocks to exit
df_tmp = df_portfolio_features[(df_portfolio_features['Symbol'].isin(list_ox40n))].sort_values(by = 'Current P/L%', ascending=False)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
25,FINCABLES,1.37,34.05,55.10,107.91,109054.0,50277.0,197921.0,1641.55,20.75,53.0,M-SC,23.36,220.0,0.46,1.32,48.90,OX40N,ATH,CABLES
72,SIS,-0.10,-1.86,23.57,21.26,25682.0,-2070.0,108962.0,528.00,2600.00,64.0,H-SC,21.85,168.0,-0.08,0.72,62.01,OX40N,NTT,MISC
16,CERA,-0.54,-18.61,52.21,23.89,74752.0,-32728.0,143175.0,9475.00,-21.48,70.0,H-SC,4.69,153.0,-0.44,0.95,37.59,OX40N,NTT,CERAMICS
50,KANSAINER,0.97,-27.06,55.57,13.47,109303.0,-72972.0,196695.0,340.00,-37.29,61.0,H-SC,6.45,162.0,-0.67,1.31,37.39,XY24,NTT,PAINTS
43,INDIGOPNTS,0.83,-27.99,38.90,0.02,48895.0,-48866.0,125693.0,1408.00,91.41,62.0,M-SC,10.81,222.0,-1.00,0.84,42.61,OX40N,NTT,PAINTS

In [14]:
# top 5 to book for rotation
df_tmp = df_portfolio_features[(df_portfolio_features['Current P/L%'] > 20) ].sort_values(by = 'CumlRnk', ascending=False)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
25,FINCABLES,1.37,34.05,55.10,107.91,109054.0,50277.0,197921.0,1641.55,20.75,53.0,M-SC,23.36,220.0,0.46,1.32,48.90,OX40N,ATH,CABLES
68,SATIN,-0.73,27.68,18.92,51.83,66742.0,76474.0,352758.0,274.00,14.32,57.0,H-SC,40.24,159.0,1.15,2.34,71.85,XY24,NTT,FINANCE

In [15]:
# top 5 to monitor for exit
df_tmp = df_portfolio_features[~df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])]
df_tmp = df_tmp[(df_tmp['Current P/L%'] > 0) ].sort_values(by = 'Dev%_PE', ascending=False)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
9,BANDHANBNK,-1.40,0.02,92.38,92.42,257383.0,54.0,278613.0,400.00,139.22,58.0,H-SC,21.39,174.0,0.00,1.85,53.48,XY24,NTT,BANKS
74,STARHEALTH,-0.71,1.57,44.98,47.26,128439.0,4423.0,285546.0,761.00,60.41,54.0,H-SC,10.09,173.0,0.03,1.90,25.36,XY24,NTT,INSURANCE
25,FINCABLES,1.37,34.05,55.10,107.91,109054.0,50277.0,197921.0,1641.55,20.75,53.0,M-SC,23.36,220.0,0.46,1.32,48.90,OX40N,ATH,CABLES
68,SATIN,-0.73,27.68,18.92,51.83,66742.0,76474.0,352758.0,274.00,14.32,57.0,H-SC,40.24,159.0,1.15,2.34,71.85,XY24,NTT,FINANCE
91,ZYDUSLIFE,-1.24,13.32,19.69,35.63,46761.0,27913.0,237487.0,1286.17,-1.35,58.0,H-MC,13.34,120.0,0.60,1.58,24.87,AR,ATH,PHARMA

In [16]:
# top 5 to book for rotation from weak conviction
df_tmp = df_portfolio_features[~df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])]
df_tmp = df_tmp[~df_tmp['Criteria'].isin(['XY25','XY24','X40', 'X40N'])].sort_values(by = 'RRR Ind', ascending=False)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
91,ZYDUSLIFE,-1.24,13.32,19.69,35.63,46761.0,27913.0,237487.0,1286.17,-1.35,58.0,H-MC,13.34,120.0,0.60,1.58,24.87,AR,ATH,PHARMA
25,FINCABLES,1.37,34.05,55.10,107.91,109054.0,50277.0,197921.0,1641.55,20.75,53.0,M-SC,23.36,220.0,0.46,1.32,48.90,OX40N,ATH,CABLES
73,SONACOMS,-0.03,3.14,34.86,39.09,36371.0,3176.0,104335.0,804.02,-18.31,52.0,M-MC,18.41,193.0,0.09,0.69,47.60,AR,ATH,AUTO
75,SURYODAY,1.15,-0.97,24.24,23.03,42986.0,-1734.0,177337.0,216.00,92.98,61.0,H-SC,18.39,166.0,-0.04,1.18,49.31,XR,NTT,BANKS
72,SIS,-0.10,-1.86,23.57,21.26,25682.0,-2070.0,108962.0,528.00,2600.00,64.0,H-SC,21.85,168.0,-0.08,0.72,62.01,OX40N,NTT,MISC

In [17]:
# top 5 to accumulate based on lowest RSI_14
df_tmp = df_portfolio_features[df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])].sort_values(by = 'RSI_14', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
58,PGHH,0.48,-32.30,94.98,32.01,137303.0,-68960.0,144560.0,17616.87,-54.24,33.0,X-MC,19.42,57.0,-0.50,0.96,0.48,X40,ATH,FMCG
27,GLAXO,2.34,-12.80,55.61,35.69,96637.0,-25508.0,173776.0,3380.16,-33.48,42.0,X-MC,10.22,56.0,-0.26,1.15,3.28,X40,ATH,PHARMA
79,TCS,1.09,-35.84,94.64,24.88,281297.0,-166045.0,297228.0,4253.91,-45.59,42.0,X-LC,18.93,2.0,-0.59,1.98,2.34,X40,ATH,IT
1,ABBOTINDIA,-0.59,-12.44,34.85,18.07,54575.0,-22255.0,156600.0,35195.00,-25.47,44.0,X-MC,6.03,58.0,-0.41,1.04,3.65,X40,ATH,PHARMA
35,HDFCLIFE,-1.59,-6.46,42.37,33.18,59372.0,-9672.0,140128.0,814.30,-26.99,44.0,X-LC,16.38,31.0,-0.16,0.93,4.90,X40,ATH,INSURANCE

In [18]:
# top 5 to accumulate based on Spread and CumlRnk
df_tmp = df_portfolio_features[df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])]
df_tmp = df_tmp[(df_tmp['CumlRnk'] < 100)].sort_values(by = 'Spread%', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
49,JSWINFRA,-0.20,0.04,16.39,16.43,36362.0,83.0,221857.0,342.00,-14.25,63.0,X-MC,1.46,61.0,0.00,1.47,25.41,X40N,NTT,REALTY
57,PAGEIND,-0.59,1.63,31.44,33.59,85754.0,4376.0,272755.0,51217.29,-27.14,58.0,X-MC,2.77,55.0,0.05,1.81,29.53,X40,ATH,APPARELS
19,COLPAL,0.84,-21.21,77.51,39.86,160833.0,-55865.0,207500.0,3683.41,-4.73,53.0,X-MC,2.99,62.0,-0.35,1.38,17.37,XY25,ATH,FMCG
15,CAMS,0.47,2.33,21.64,24.48,55773.0,5874.0,257730.0,950.00,-1.96,56.0,X-SC,3.09,89.0,0.11,1.71,25.47,X40N,NTT,MISC
11,BERGEPAINT,0.14,-4.14,30.73,25.32,75925.0,-10678.0,247071.0,680.00,-9.42,59.0,X-MC,3.55,68.0,-0.14,1.64,28.59,XY24,NTT,PAINTS

In [19]:
# top 5 to accumulate based on lowest Gained%
df_tmp = df_portfolio_features[df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])].sort_values(by = 'Gained%', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
58,PGHH,0.48,-32.30,94.98,32.01,137303.0,-68960.0,144560.0,17616.87,-54.24,33.0,X-MC,19.42,57.0,-0.50,0.96,0.48,X40,ATH,FMCG
79,TCS,1.09,-35.84,94.64,24.88,281297.0,-166045.0,297228.0,4253.91,-45.59,42.0,X-LC,18.93,2.0,-0.59,1.98,2.34,X40,ATH,IT
33,HCLTECH,2.14,-25.80,63.77,21.51,114466.0,-62426.0,179498.0,1872.35,-22.25,44.0,X-LC,18.49,8.0,-0.55,1.19,3.04,X40,ATH,IT
27,GLAXO,2.34,-12.80,55.61,35.69,96637.0,-25508.0,173776.0,3380.16,-33.48,42.0,X-MC,10.22,56.0,-0.26,1.15,3.28,X40,ATH,PHARMA
1,ABBOTINDIA,-0.59,-12.44,34.85,18.07,54575.0,-22255.0,156600.0,35195.00,-25.47,44.0,X-MC,6.03,58.0,-0.41,1.04,3.65,X40,ATH,PHARMA

In [20]:
# top 5 to accumulate based on lowest CurrAlloc%
df_tmp = df_portfolio_features[df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])].sort_values(by = 'CurrAlloc%', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
10,BATAINDIA,-0.47,-56.32,209.56,35.20,117771.0,-72471.0,56199.0,2096.00,-26.35,48.0,X-SC,25.27,91.0,-0.62,0.37,11.46,X40,NTT,FOOTWEAR
64,RELAXO,1.86,-54.95,238.08,52.31,155695.0,-79764.0,65396.0,1176.00,-51.99,63.0,X-SC,18.16,92.0,-0.51,0.43,46.22,X40N,NTT,FOOTWEAR
60,QUESS,-0.05,0.66,72.77,73.90,78223.0,701.0,107494.0,424.00,-46.01,76.0,X-SC,5.95,80.0,0.01,0.71,46.54,XY24,NTT,MISC
28,GODREJCP,-0.89,-8.04,42.96,31.47,58714.0,-11943.0,136671.0,1469.04,-3.32,50.0,X-LC,9.63,32.0,-0.20,0.91,4.86,X40N,ATH,FMCG
35,HDFCLIFE,-1.59,-6.46,42.37,33.18,59372.0,-9672.0,140128.0,814.30,-26.99,44.0,X-LC,16.38,31.0,-0.16,0.93,4.90,X40,ATH,INSURANCE

In [21]:
# top 5 to accumulate based on CumlRnk
df_tmp = df_portfolio_features.sort_values(by = 'CumlRnk', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
47,ITC,0.97,-23.43,55.49,19.06,144533.0,-79699.0,260467.0,452.00,-57.95,53.0,X-LC,15.29,1.0,-0.55,1.73,4.95,X40,NTT,FMCG
79,TCS,1.09,-35.84,94.64,24.88,281297.0,-166045.0,297228.0,4253.91,-45.59,42.0,X-LC,18.93,2.0,-0.59,1.98,2.34,X40,ATH,IT
45,INFY,0.21,-22.58,73.39,34.24,177784.0,-70643.0,242245.0,1972.00,-39.04,46.0,X-LC,16.61,3.0,-0.40,1.61,6.11,X40,NTT,IT
81,TMPV,-1.88,-11.46,54.26,36.58,170946.0,-40791.0,315050.0,600.00,-81.44,56.0,X-LC,12.89,4.0,-0.24,2.09,31.31,XY24,NTT,AUTO
59,PIDILITIND,-1.08,10.13,7.47,18.37,11609.0,14300.0,155410.0,1670.26,-22.84,68.0,X-LC,3.65,5.0,1.23,1.03,22.02,X40,ATH,CHEMICALS

In [22]:
# top 5 for average up
df_tmp = df_portfolio_features[(df_portfolio_features['Dev%_200'] > 5)].sort_values(by = 'CurrAlloc%', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
44,INDUSINDBK,-1.07,-31.84,94.97,32.89,49975.0,-24584.0,52622.0,1800.00,-347.90,55.0,L-MC,7.37,258.0,-0.49,0.35,29.53,XR,NTT,BANKS
3,ALKYLAMINE,-1.97,-24.23,155.56,93.63,118999.0,-24466.0,76497.0,4546.37,-18.90,54.0,H-SC,7.82,142.0,-0.21,0.51,44.45,SR,ATH,CHEMICALS
73,SONACOMS,-0.03,3.14,34.86,39.09,36371.0,3176.0,104335.0,804.02,-18.31,52.0,M-MC,18.41,193.0,0.09,0.69,47.60,AR,ATH,AUTO
60,QUESS,-0.05,0.66,72.77,73.90,78223.0,701.0,107494.0,424.00,-46.01,76.0,X-SC,5.95,80.0,0.01,0.71,46.54,XY24,NTT,MISC
72,SIS,-0.10,-1.86,23.57,21.26,25682.0,-2070.0,108962.0,528.00,2600.00,64.0,H-SC,21.85,168.0,-0.08,0.72,62.01,OX40N,NTT,MISC

In [23]:
# top 5 RSP
df_tmp = df_portfolio_features.sort_values(by = 'RSP', ascending=False)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
18,COFFEEDAY,-2.16,-44.18,142.35,35.27,90220.0,-50170.0,63379.0,80.00,-57.75,53.0,L-SC,15.50,266.0,-0.56,0.42,56.30,XR,NTT,HOTELS
37,HONAUT,0.99,-5.98,60.94,51.31,110484.0,-11538.0,181300.0,58357.33,-21.78,64.0,X-SC,8.83,90.0,-0.10,1.20,37.74,X40N,ATH,ELECTRICAL
60,QUESS,-0.05,0.66,72.77,73.90,78223.0,701.0,107494.0,424.00,-46.01,76.0,X-SC,5.95,80.0,0.01,0.71,46.54,XY24,NTT,MISC
64,RELAXO,1.86,-54.95,238.08,52.31,155695.0,-79764.0,65396.0,1176.00,-51.99,63.0,X-SC,18.16,92.0,-0.51,0.43,46.22,X40N,NTT,FOOTWEAR
69,SFL,-1.32,-31.10,83.79,26.63,151378.0,-81554.0,180664.0,1287.00,36.81,69.0,M-SC,9.96,242.0,-0.54,1.20,50.58,XY24,NTT,MISC

In [24]:
# Top N allocation
df_tmp = df_portfolio_features.sort_values(by = 'CurrAlloc%', ascending=False)
top_n_values = [10, 25, 50]

sum_df = pd.DataFrame({
    'Top_N': top_n_values,
    'Sum_Alloc%': [df_tmp['CurrAlloc%'].head(n).sum() for n in top_n_values]
})

sum_df

   Top_N  Sum_Alloc%
0     10       19.55
1     25       42.78
2     50       72.75

In [25]:
# market-cap-wise allocation
df_tmp = df_portfolio_features[cols]
df_tmp.groupby(df_tmp['Conviction'].str[-2:])['CurrAlloc%'].sum().sort_values(ascending=False)

Conviction
SC    43.14
LC    31.31
MC    25.53
Name: CurrAlloc%, dtype: float64

In [26]:
# criteria-wise allocation
df_portfolio_features.groupby('Criteria')['CurrAlloc%'].sum().sort_values(ascending=False)

Criteria
XY24     27.85
X40      24.81
X40N     17.19
XR        8.94
OX40N     6.95
AR        6.78
XY25      6.59
SR        0.87
Name: CurrAlloc%, dtype: float64

In [27]:
# conviction-wise allocation
df_portfolio_features.groupby('Conviction')['CurrAlloc%'].sum().sort_values(ascending=False)

Conviction
X-LC    29.27
H-SC    22.70
X-MC    20.48
M-SC     9.98
X-SC     9.89
H-MC     2.71
M-MC     1.99
H-LC     1.20
M-LC     0.84
L-SC     0.57
L-MC     0.35
Name: CurrAlloc%, dtype: float64

In [28]:
# sector-wise stats
df_tmp = df_portfolio_features.groupby('Category')[['CurrAlloc%', 'Current', 'Current P/L', 'FTT Amt']].sum().sort_values(by=['Current', 'Current P/L'], ascending=False)
df_tmp['Current P/L%'] = round(df_tmp['Current P/L'] * 100 / df_tmp['Current'], 2)
df_tmp['FTT%'] = round(df_tmp['FTT Amt'] * 100 / df_tmp['Current'], 2)
cols = ['CurrAlloc%', 'Current P/L%', 'FTT%']
df_tmp[cols].sort_values(by=['CurrAlloc%'], ascending=False)

               CurrAlloc%  Current P/L%    FTT%
Category
FMCG                14.91        -17.92   59.29
FINANCE             10.91        -12.25   61.07
IT                   9.99        -49.88  124.81
MISC                 7.17        -24.03   77.91
AUTO                 6.85         -6.23   46.06
BANKS                5.85         -3.22   50.95
PAINTS               5.65        -15.94   36.07
INSURANCE            5.14         -7.23   43.48
PHARMA               4.90         -0.37   31.43
ELECTRICAL           4.05        -15.86   56.75
CHEMICALS            2.18        -23.51   97.11
HEALTHCARE           2.04        -16.64   47.08
APPARELS             1.81          1.60   31.44
AC                   1.81        -17.18   48.96
FOOTWEAR             1.68        -73.51  143.08
TRAVEL               1.66        -79.04  168.69
DURABLES             1.53        -68.24  109.17
BREWERIES            1.48         -5.45   27.34
REALTY               1.47          0.04   16.39
CERAMICS             1.42        -43.36   86.91
CABLES               1.32         25.40   55.10
ENGINEERING          1.31        -22.57   78.63
REFINERIES           1.14        -17.08   46.70
CEMENT               1.08        -65.29  188.95
JEWELLERY            1.05       -103.09  173.65
ENTERTAINMENT        0.75        -71.27  173.42
HOTELS               0.42        -79.16  142.35
TEXTILES             0.41        -50.85   93.86

In [29]:
# money to be made criteria-wise
df_portfolio_features.groupby('Criteria')['FTT Amt'].agg(['sum', 'count']).sort_values(by='sum', ascending=False)

                sum  count
Criteria
XY24      3404019.0     21
X40       1949080.0     19
XR        1336230.0     13
AR        1162514.0      9
X40N      1133623.0     13
OX40N      747657.0     10
XY25       444821.0      5
SR         287974.0      2

In [30]:
# money to be made conviction-wise
df_portfolio_features.groupby('Conviction')['FTT Amt'].agg(['sum', 'count']).sort_values(by='sum', ascending=False)

                  sum  count
Conviction
H-SC        3366447.0     24
X-LC        1883856.0     21
X-MC        1633645.0     15
M-SC        1419333.0     14
X-SC        1311912.0      9
H-MC         291023.0      2
L-SC         205169.0      2
M-LC         165468.0      1
M-MC          86510.0      2
H-LC          52580.0      1
L-MC          49975.0      1

In [31]:
# money to be made criteria and conviction-wise
df_portfolio_features.groupby(['Conviction', 'Criteria'])['FTT Amt'].agg(['sum', 'count']).sort_values(by='sum', ascending=False)

                           sum  count
Conviction Criteria
X-LC       X40       1028093.0     10
H-SC       XY24      1021133.0      6
           AR         952992.0      5
M-SC       XY24       826265.0      6
H-SC       XR         796796.0      7
X-SC       XY24       774431.0      4
X-MC       X40        705458.0      7
           X40N       464290.0      4
X-LC       X40N       347381.0      6
M-SC       OX40N      325156.0      5
X-SC       X40N       321952.0      3
X-LC       XY24       315395.0      2
H-SC       OX40N      307552.0      4
           SR         287974.0      2
H-MC       XY24       244262.0      1
X-MC       XY25       241364.0      2
           XY24       222533.0      2
X-SC       X40        215529.0      2
M-SC       XR         194102.0      2
M-LC       XR         165468.0      1
X-LC       XY25       153318.0      2
L-SC       OX40N      114949.0      1
           XR          90220.0      1
M-SC       AR          73810.0      1
H-LC       AR          52580.0      1
M-MC       XY25        50139.0      1
L-MC       XR          49975.0      1
H-MC       AR          46761.0      1
X-LC       XR          39669.0      1
M-MC       AR          36371.0      1

In [32]:
# notebook execution time

end_time = time.time()
execution_time = round(end_time - start_time, 0)
print(f"Notebook execution time: {execution_time} seconds")

Notebook execution time: 26.0 seconds