<a href="https://colab.research.google.com/github/ankit-rathi/Quantvesting_v2/blob/main/myStocks_Portfolio_Analysis.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
'''
!pip install pandas==2.2.2 -qq
!pip install pyxirr -qq
!pip install ta -qq
!pip install yfinance==0.2.59 -qq
'''

'\n!pip install pandas==2.2.2 -qq\n!pip install pyxirr -qq\n!pip install ta -qq\n!pip install yfinance==0.2.59 -qq\n'

In [2]:
# import libraries

import numpy as np
import pandas as pd
import datetime
import warnings
warnings.filterwarnings('ignore')
import yfinance as yfin
import ta
import matplotlib.pyplot as plt
import requests

In [3]:
# notebook start time
import time
import datetime
import pytz

start_time = time.time()

# function to print date timestamp
def print_date_time():
  tz_NY = pytz.timezone('Asia/Kolkata')
  datetime_NY = datetime.datetime.now(tz_NY)
  print("Run date time (IST):", datetime_NY.strftime("%Y-%m-%d %H:%M:%S"))

In [4]:
# function to get booked and reserved amount
def get_amt():
  # fetch the JSON data from the URL
  url = "https://raw.githubusercontent.com/ankit-rathi/Tradevesting_v1/main/data/myPortfolioAmts.json"
  response = requests.get(url)
  pf_amts = response.json()  # parse the JSON data

  # extract values from the JSON
  py_booked_amt_dm = pf_amts["py_booked_amt_dm"]
  py_booked_amt_sv = pf_amts["py_booked_amt_sv"]
  cy_booked_amt_dm = pf_amts["cy_booked_amt_dm"]
  cy_booked_amt_sv = pf_amts["cy_booked_amt_sv"]
  reserve_amt_dm = pf_amts["reserve_amt_dm"]
  reserve_amt_sv = pf_amts["reserve_amt_sv"]

  # perform calculations
  py_booked_amt = py_booked_amt_dm + py_booked_amt_sv
  cy_booked_amt = cy_booked_amt_dm + cy_booked_amt_sv
  reserve_amt = reserve_amt_dm + reserve_amt_sv
  total_booked_amt = py_booked_amt + cy_booked_amt

  return total_booked_amt, reserve_amt, cy_booked_amt, py_booked_amt

gen_output = 0

In [5]:
# function to format the amount
def format_amt(number):
    abs_number = abs(number)

    if abs_number >= 1_00_00_000:  # Crores
        formatted_amt = f"{number / 1_00_00_000:.2f} C"
    elif abs_number >= 1_00_000:  # Lakhs
        formatted_amt = f"{number / 1_00_000:.2f} L"
    elif abs_number >= 1_000:  # Thousands
        formatted_amt = f"{number / 1_000:.2f} K"
    else:
        formatted_amt = f"{number:.2f}"

    return formatted_amt

# function to set start and end date
def get_start_end_date():
  start_date = (datetime.date.today() + datetime.timedelta(days=-365)).strftime('%Y-%m-%d')
  end_date = (datetime.date.today() + datetime.timedelta(days=1)).strftime('%Y-%m-%d')
  return start_date, end_date

# function to fetch my portfolio csv
def get_mypfs_df():
  mypfs_df = pd.read_csv('https://raw.githubusercontent.com/ankit-rathi/Tradevesting_v1/main/data/myPortfolioStocks.csv')
  return mypfs_df

# function to fetch my prospects csv
def get_mypps_df():
  mypps_df = pd.read_csv('https://raw.githubusercontent.com/ankit-rathi/Tradevesting_v1/main/data/myProspectsScrips.csv')
  return mypps_df

# function to fetch screener data
def get_myscreen_df():
  myscreen_df = pd.read_csv('https://raw.githubusercontent.com/ankit-rathi/Tradevesting_v1/main/data/myScreenerDB.csv')
  return myscreen_df

# function to fetch momentum data
def get_myinvmt_df():
  myinvmt_df = pd.read_csv('https://raw.githubusercontent.com/ankit-rathi/Tradevesting_v1/main/data/myInvestments.csv')
  return myinvmt_df

# function to get the stock ids
def get_stock_ids(df_pf):
  stock_n100 = df_pf['Symbol'].unique()

  exclude = ['CADILAHC','MMTC', 'MASFIN']

  stock_ids = df_pf[~df_pf['Symbol'].isin(exclude) ]['Symbol'].unique()

  #mypf = mypf[mypf.Forecast.notnull()]
  #stock_ids = mypf['Symbol'].unique()

  #stock_ids.sort()
  return stock_ids

# get features from screener data
def get_screener_features():
  myscreen_df = get_myscreen_df()
  cols = ['Symbol', 'EPS', 'MedPE', 'ROCE%', 'ROE%', 'CapType']
  return myscreen_df[cols]

# get relative strength
def get_relative_strength(stock_list):

    # Dictionary to store stock tickers and their corresponding percentage price change
    stock_changes = {}

    # Loop through each stock and fetch its price data
    for stock in stock_list:
        try:
            # Download the stock data for the given date range
            stock_data = yfin.Ticker(stock + '.NS').history(period='1mo', interval='1d')[map(str.title, ['open', 'close', 'low', 'high', 'volume'])]

            # Calculate the percentage change for the stock
            if len(stock_data) > 0:
                start_price = stock_data['Close'].iloc[0]
                end_price = stock_data['Close'].iloc[-1]
                percent_change = round(((end_price - start_price) / start_price) * 100, 2)
                stock_changes[stock] = percent_change
            else:
                stock_changes[stock] = np.nan  # If no data is available, set to NaN

        except Exception as e:
            print(f"Error fetching data for {stock}: {e}")
            stock_changes[stock] = np.nan

    # Create a DataFrame with stock tickers and their percentage changes
    df = pd.DataFrame(list(stock_changes.items()), columns=['Symbol', 'Percent_Change'])

    # Drop any stocks with missing data (NaN values)
    df = df.dropna()

    # Calculate the percentile rank based on percentage change
    df['RSP'] = round(df['Percent_Change'].rank(pct=True) * 100, 2)
    cols = ['Symbol', 'RSP']
    df = df[cols]
    # Sort by percentile rank (optional)
    df = df.sort_values(by='RSP', ascending=False).reset_index(drop=True)

    return df

In [6]:
# function to get stock technicals
def stock_prec_dev(stock_symbol):
    #stock_symbol = 'ULTRACEMCO.NS'
    short_window = 20
    mid_window = 50
    long_window = 200
    moving_avg = 'SMA'

    start = datetime.datetime(*map(int, start_date.split('-')))
    end = datetime.datetime(*map(int, end_date.split('-')))

    stock_df = yfin.Ticker(stock_symbol + '.NS').history(period='max', interval='1d')[map(str.title, ['open', 'close', 'low', 'high', 'volume'])]

    stock_df['Max'] = round(max(stock_df['Close']),2)
    stock_df = stock_df[(stock_df.index <= end_date) & (stock_df.index >= start_date)]
    stock_df['200_SMA'] = round(stock_df['Close'].rolling(window = 200, min_periods = 1).mean(),0)
    stock_df['Dev%_200'] = round((stock_df['Close'] - stock_df['200_SMA'])*100/stock_df['200_SMA'],2)
    stock_df.dropna(axis = 0, inplace = True) # remove any null rows

    stock_df['20_SMA'] = stock_df['Close'].rolling(window=20).mean()
    stock_df['50_SMA'] = stock_df['Close'].rolling(window=50).mean()
    stock_df['Symbol'] = stock_symbol

    stock_df['Close'] = round(stock_df['Close'],2)
    stock_df['Min'] = round(min(stock_df['Close']),2)
    stock_df['RSI_14'] = ta.momentum.RSIIndicator(close=stock_df['Close'], window=14).rsi()
    stock_df['RSI_14'] = round(stock_df['RSI_14'],0)
    stock_df['Prev_Close'] = stock_df['Close'].shift(1)
    stock_df.drop(['Open', 'Low', 'High', 'Volume'], axis=1, inplace=True)
    stock_df = stock_df.tail(1)

    max_SMA = max(stock_df['20_SMA'].item(), stock_df['50_SMA'].item(), stock_df['200_SMA'].item())
    min_SMA = min(stock_df['20_SMA'].item(), stock_df['50_SMA'].item(), stock_df['200_SMA'].item())
    ABS_Spread = max_SMA - min_SMA
    stock_df['Spread%'] = round((ABS_Spread / stock_df['200_SMA'].item()) * 100,2)

    return stock_df

# function to compute stock attributes
def get_common_features(stock_ids, df_mypf):

  df_prec_dev = pd.DataFrame()
  df_tmp = get_screener_features()
  df_rs = get_relative_strength(stock_ids)

  for stock_id in stock_ids:
      tmp = stock_prec_dev(stock_id)
      tmp = tmp.reset_index()
      df_prec_dev = pd.concat([df_prec_dev, tmp], ignore_index = True)
  df_prec_dev = pd.merge(df_prec_dev, df_mypf, on= 'Symbol')
  df_prec_dev = pd.merge(df_prec_dev, df_tmp, on= 'Symbol', how='left')
  df_prec_dev = pd.merge(df_prec_dev, df_rs, on= 'Symbol', how='left')
  #print(df_prec_dev.columns)
  df_prec_dev['Curr_PE'] = round(df_prec_dev['Close']/df_prec_dev['EPS'],1)
  df_prec_dev['Dev%_PE'] = round((df_prec_dev['Curr_PE'] - df_prec_dev['MedPE'])*100/df_prec_dev['MedPE'],2)
  df_prec_dev['Conviction'] = df_prec_dev['Conviction'] + '-' + df_prec_dev['CapType']
  return df_prec_dev

# function to arrange stock features
def arrange_features(df_stocks, common_cols, diff_cols):
  df_stocks_common = df_stocks[common_cols].drop_duplicates()
  df_stocks_diff = df_stocks[diff_cols]
  df_stocks_diff['Investment'] = df_stocks_diff['AvgCost'] * df_stocks_diff['Shares']
  df_stocks_diff = df_stocks_diff.groupby(['Symbol'])[['Shares', 'Investment']].aggregate(['sum']).reset_index()
  df_stocks_diff.columns = ['Symbol', 'Shares', 'Investment']
  df_stocks_diff['AvgCost'] = round(df_stocks_diff['Investment']/df_stocks_diff['Shares'],2)
  df_stocks = pd.merge(df_stocks_diff, df_stocks_common, on='Symbol')
  return df_stocks

# plot fact distribution across dimension
def plot_pie_chart(df, dimension, fact):
  # grouping the data by category and calculating the sum of fact for each type
  grouped_data = df.groupby(dimension)[fact].sum()

  # sorting the grouped data in descending order
  grouped_data = grouped_data.sort_values(ascending=False)

  # creating a pie chart
  grouped_data.plot.pie(autopct='%1.1f%%', startangle=90, figsize=(6, 6))

  # adding a title and displaying the plot
  plt.title(f'{dimension} {fact} Distribution')
  plt.ylabel('')  # To hide the y-label
  plt.show()

In [7]:
# function to get portfolio features

def get_portfolio_features(df_common_features):

  print_date_time()
  print('-------------------')

  #df_common_features["Target"] = df_common_features["Target"].fillna(df_common_features["Max"])
  df_common_features['NTT'] = np.where(df_common_features['Strategy']== 'NTT', df_common_features["Target"], df_common_features['Max'])
  df_common_features['LTT'] = np.where(df_common_features['Strategy']== 'BTT', df_common_features["Target"], df_common_features['Max'])
  df_common_features['BOL'] = df_common_features['Min']

  tmp_df = df_common_features[df_common_features['Symbol'].isin(mypf_df[mypf_df['InPortfolio'] != 'NA'].Symbol.values)]
  print('qualified stocks: '+str(len(tmp_df['Symbol'].unique())))
  tmp_df1 = tmp_df[tmp_df['LatestQtr'] == 1]
  print('with latest results: '+str(len(tmp_df1['Symbol'].unique())))
  tmp_df1 = tmp_df1[tmp_df1['StarStock'] == 1]
  print('still star stocks: '+str(len(tmp_df1['Symbol'].unique())))
  tmp_df['Investment'] = tmp_df['AvgCost'] * tmp_df['Shares']
  tmp_df['Current'] = round(tmp_df['Close'] * tmp_df['Shares'],0)
  tmp_df['Previous'] = tmp_df['Prev_Close'] * tmp_df['Shares']
  tmp_df['EstimatedST'] = tmp_df['NTT'] * tmp_df['Shares']
  tmp_df['EstimatedLT'] = tmp_df['LTT'] * tmp_df['Shares']
  tmp_df['Current P/L'] = round((tmp_df['Current'] - tmp_df['Investment']),0)
  tmp_df['Today P/L%'] = round((tmp_df['Current'] - tmp_df['Previous'])*100/tmp_df['Previous'],2)
  tmp_df['Current P/L%'] = round((tmp_df['Current'] - tmp_df['Investment'])*100/tmp_df['Investment'],2)
  tmp_df['EstimatedST P/L%'] = round((tmp_df['EstimatedST'] - tmp_df['Investment'])*100/tmp_df['Investment'],2)
  tmp_df['EstimatedLT P/L%'] = round((tmp_df['EstimatedLT'] - tmp_df['Investment'])*100/tmp_df['Investment'],2)
  tmp_df['NTT%'] = round((tmp_df['NTT'] - tmp_df['Close'])*100/tmp_df['Close'],2)
  tmp_df['LTT%'] = round((tmp_df['LTT'] - tmp_df['Close'])*100/tmp_df['Close'],2)
  tmp_df['Gained%'] = round((tmp_df['Close'] - tmp_df['BOL'])*100/tmp_df['BOL'],2)
  investment = round(sum(tmp_df['AvgCost']*tmp_df['Shares']),0)
  current = round(sum(tmp_df['Close']*tmp_df['Shares']),0)
  tmp_df['InitAlloc%'] = round(tmp_df['Investment']*100/investment,2)
  tmp_df['CurrAlloc%'] = round(tmp_df['Current']*100/current,2)
  tmp_df['FTT'] = tmp_df['LTT']
  tmp_df.loc[tmp_df['Strategy'] == 'NTT', 'FTT'] = tmp_df['NTT']
  tmp_df['FTT%'] = tmp_df['LTT%']
  tmp_df.loc[tmp_df['Strategy'] == 'NTT', 'FTT%'] = tmp_df['NTT%']
  tmp_df['FTT Amt'] = round(tmp_df['FTT%'] * tmp_df['Current']/100,0)
  tmp_df['OTT%'] = round((tmp_df['FTT'] - tmp_df['AvgCost'])*100/tmp_df['AvgCost'],2)
  tmp_df['RRR Ind'] = round(tmp_df['Current P/L']/tmp_df['FTT Amt'],2)
  tmp_df['Risk Ind'] = round(tmp_df['Current P/L%']*tmp_df['CurrAlloc%'],0)

  return tmp_df

# function to print portfolio features
def print_portfolio_stats(df_portfolio_features, myinvmt_df):
  from pyxirr import xirr

  total_booked_amt, reserve_amt, cy_booked_amt, py_booked_amt = get_amt()

  dates = myinvmt_df['Date'].values
  dates = np.append(dates, datetime.date.today().strftime('%d-%b-%y'))
  investment = myinvmt_df['Investment'].values
  dates= pd.to_datetime(dates)

  current = round(sum(df_portfolio_features['Close']*df_portfolio_features['Shares']),0) + reserve_amt
  investment_xirr = np.append(investment, current)
  cagr = round(xirr(pd.DataFrame({"dates": dates, "amounts": investment_xirr}))*100,2)

  investment = -sum(investment)
  invested = round(sum(df_portfolio_features['AvgCost']*df_portfolio_features['Shares']),0) + reserve_amt
  previous = round(sum(df_portfolio_features['Prev_Close']*df_portfolio_features['Shares']),0) + reserve_amt
  cy_invested = investment + py_booked_amt

  today_pnl_amount = current-previous
  today_pnl_percentage = round((current-previous)*100/previous,2)

  curr_pnl_amount = current-invested
  curr_pnl_percentage = round((curr_pnl_amount)*100/(cy_invested),2)

  cy_pnl_amount = cy_booked_amt + curr_pnl_amount
  cy_pnl_percentage = round((cy_pnl_amount)*100/cy_invested,2)

  overall_pnl_amount = total_booked_amt + curr_pnl_amount
  overall_pnl_percentage = round((overall_pnl_amount)*100/investment,2)

  estimate_st = round(sum(df_portfolio_features['FTT']*df_portfolio_features['Shares']),0)  + reserve_amt
  est_st_pnl_amount = estimate_st-current
  est_st_pnl_percentage = round((est_st_pnl_amount)*100/current,2)

  estimate_lt = round(sum(df_portfolio_features['LTT']*df_portfolio_features['Shares']),0)  + reserve_amt
  est_lt_pnl_amount = estimate_lt-current
  est_lt_pnl_percentage = round((est_lt_pnl_amount)*100/current,2)

  total_profit = round(sum(df_portfolio_features[df_portfolio_features['Current P/L%'] > 0]['Current']) - sum(df_portfolio_features[df_portfolio_features['Current P/L%'] > 0]['Investment']),0)
  total_loss = round(sum(df_portfolio_features[df_portfolio_features['Current P/L%'] < 0]['Current']) - sum(df_portfolio_features[df_portfolio_features['Current P/L%'] < 0]['Investment']),0)

  cy_booked_percentage = round((cy_booked_amt)*100/current,2)
  py_booked_percentage = round((py_booked_amt)*100/investment,2)
  total_booked_percentage = round((total_booked_amt)*100/investment,2)

  print('-------------------')
  print('Initial Investment: ', format_amt(investment))
  print('CY Investment: ', format_amt(cy_invested))
  print('Reserve: ', format_amt(reserve_amt))
  print('Current: ',  format_amt(current))
  print('-------------------')
  print('Today PnL: '+ '{} ({}%)'.format(format_amt(today_pnl_amount), today_pnl_percentage))
  print('Current PnL: '+ '{} ({}%)'.format(format_amt(curr_pnl_amount), curr_pnl_percentage))
  print('CY Booked + Current PnL: '+ '{} ({}%)'.format(format_amt(cy_pnl_amount), cy_pnl_percentage))
  print('-------------------')
  print('Total profit: ', format_amt(total_profit))
  print('Total loss: ', format_amt(total_loss))
  print('-------------------')
  print('Total Booked + Current PnL: '+ '{} ({}%)'.format(format_amt(overall_pnl_amount), overall_pnl_percentage))
  print('Total Booked PnL: '+ '{} ({}%)'.format(format_amt(total_booked_amt), total_booked_percentage))
  print('Curr Year Booked PnL: '+ '{} ({}%)'.format(format_amt(cy_booked_amt), cy_booked_percentage))
  print('Prev Year Booked PnL: '+ '{} ({}%)'.format(format_amt(py_booked_amt), py_booked_percentage))
  print('===================')
  print('Est FTT: ',  format_amt(estimate_st))
  print('Est FTT PnL: '+ '{} ({}%)'.format(format_amt(est_st_pnl_amount), est_st_pnl_percentage))

  print('===================')
  print('Deployed: ', format_amt(investment))

  print('Current: ', format_amt(current))

  print('CAGR/XIRR %: '+'{}%'.format(cagr))

In [8]:
# get start and end date
start_date, end_date = get_start_end_date()

# get portfolio and prospects data
mypfs_df = get_mypfs_df()
mypps_df = get_mypps_df()
myinvmt_df = get_myinvmt_df()

# merge above datasets
mypf_df = pd.merge(mypfs_df, mypps_df, on="Symbol")

# seggregate dm and sv portfolio
dm_pf = mypf_df[mypf_df['InPortfolio'] == 'DM']
sv_pf = mypf_df[mypf_df['InPortfolio'] == 'SV']

# build portfolio stock dataframe
dm_stocks = get_stock_ids(dm_pf)
sv_stocks = get_stock_ids(sv_pf)
df_stocks = pd.concat([dm_pf,sv_pf], ignore_index = True)

# arrange common and diff stock features
common_cols = ['Symbol', 'Target', 'Criteria', 'Strategy', 'CumlRnk', 'LatestQtr', 'StarStock', 'Conviction', 'Category', 'InFolio', 'XIRR', 'MBQ']
diff_cols = ['Symbol', 'AvgCost', 'Shares']
df_stocks = arrange_features(df_stocks, common_cols, diff_cols)

# get common features
stock_ids = df_stocks['Symbol'].values
df_common_features = get_common_features(stock_ids, df_stocks)

df_common_features.reset_index(drop=True, inplace=True)
df_common_features.drop(['Date'], axis=1, inplace=True)
# get and print portfolio features
df_portfolio_features = get_portfolio_features(df_common_features)

print_portfolio_stats(df_portfolio_features, myinvmt_df)

df = df_portfolio_features
#plot_pie_chart(df, 'CapType', 'Current')
list_ox40n = list(df[df['MBQ'].str.contains('OX40N', na=False)]['Symbol'].values)

Run date time (IST): 2026-03-10 13:25:46
-------------------
qualified stocks: 86
with latest results: 26
still star stocks: 15
-------------------
Initial Investment:  1.36 C
CY Investment:  1.62 C
Reserve:  66.25 K
Current:  1.37 C
-------------------
Today PnL: 1.46 L (1.08%)
Current PnL: -40.21 L (-24.75%)
CY Booked + Current PnL: -24.53 L (-15.1%)
-------------------
Total profit:  1.07 L
Total loss:  -41.28 L
-------------------
Total Booked + Current PnL: 2.45 L (1.81%)
Total Booked PnL: 42.66 L (31.48%)
Curr Year Booked PnL: 15.68 L (11.47%)
Prev Year Booked PnL: 26.98 L (19.91%)
===================
Est FTT:  2.47 C
Est FTT PnL: 1.11 C (80.88%)
===================
Deployed:  1.36 C
Current:  1.37 C
CAGR/XIRR %: 0.45%

In [9]:
# top 5 near their targets
cols = ['Symbol', 'Today P/L%', 'Current P/L%', 'FTT%', 'OTT%', 'FTT Amt', 'Current P/L', 'Current', 'FTT', 'Dev%_PE', 'RSI_14','Conviction', 'Spread%',  'CumlRnk', 'RRR Ind', 'CurrAlloc%', 'Gained%', 'Criteria', 'Strategy', 'Category']
df_tmp = df_portfolio_features[~df_portfolio_features['Symbol'].isin(['ENRIN','BLUSPRING','DIGITIDE'])]
df_tmp = df_tmp.sort_values(by = 'FTT Amt', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
19,COALINDIA,0.80,8.48,8.47,17.67,13825.0,12766.0,163226.0,478.51,30.56,58.0,L-LC,11.50,185.0,0.92,1.20,26.76,XY25,ATH,MINING
50,MASFIN,2.04,-5.88,29.16,21.57,26891.0,-5760.0,92220.0,397.04,-18.70,41.0,H-SC,5.06,167.0,-0.21,0.68,28.68,XR,ATH,FINANCE
37,ICICIGI,0.39,0.49,18.76,19.34,37725.0,984.0,201093.0,2252.93,-15.42,49.0,X-MC,1.59,66.0,0.03,1.48,14.69,X40,ATH,INSURANCE
77,TTKPRESTIG,3.40,-39.27,64.83,0.09,39674.0,-39580.0,61197.0,770.00,41.94,26.0,M-SC,15.04,250.0,-1.00,0.45,3.40,OX40N,NTT,DURABLES
78,UNITDSPR,3.31,2.89,17.37,20.77,41848.0,6776.0,240920.0,1644.00,-8.78,54.0,X-MC,1.52,64.0,0.16,1.77,9.80,X40N,NTT,BREWERIES

In [10]:
# top 5 today
df_tmp = df_portfolio_features.sort_values(by = 'Today P/L%', ascending=False)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
31,HAPPSTMNDS,11.91,-52.42,288.54,84.85,175940.0,-67189.0,60976.0,1480.71,-43.46,52.0,H-SC,29.01,152.0,-0.38,0.45,12.92,AR,ATH,IT
24,DIXON,5.51,-24.64,83.02,37.92,163164.0,-64262.0,196536.0,18931.72,-67.97,43.0,X-MC,25.57,54.0,-0.39,1.44,5.51,X40N,ATH,IT
15,BSOFT,5.40,-29.57,114.11,50.79,113032.0,-41598.0,99055.0,831.70,-9.55,47.0,H-SC,4.97,172.0,-0.37,0.73,15.33,XR,ATH,IT
11,BANDHANBNK,3.89,-12.98,121.12,92.42,293602.0,-36153.0,242406.0,400.00,107.61,60.0,H-SC,9.97,174.0,-0.12,1.78,33.54,XY24,NTT,BANKS
26,EASEMYTRIP,3.61,-58.77,253.41,45.70,184716.0,-103923.0,72892.0,26.40,-24.39,45.0,M-SC,18.16,204.0,-0.56,0.54,20.10,XY24,NTT,TRAVEL

In [11]:
# bottom 5 today
df_tmp = df_portfolio_features.sort_values(by = 'Today P/L%', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
55,RAJESHEXPO,-3.50,-78.94,375.23,0.07,108385.0,-108292.0,28885.0,518.00,958.08,16.0,L-SC,16.85,268.0,-1.00,0.21,0.00,OX40N,NTT,JEWELLERY
27,FINCABLES,-2.47,18.90,74.87,107.91,131431.0,27902.0,175546.0,1641.55,7.05,65.0,M-SC,7.69,220.0,0.21,1.29,32.07,OX40N,ATH,CABLES
43,INFY,-1.86,-12.15,52.81,34.24,145162.0,-38012.0,274876.0,1972.00,-30.70,28.0,X-LC,11.47,3.0,-0.26,2.02,1.18,X40,NTT,IT
73,TCS,-1.18,-26.68,72.62,26.57,246681.0,-123586.0,339687.0,4311.58,-38.05,23.0,X-LC,13.12,2.0,-0.50,2.50,0.00,X40,ATH,IT
58,RELAXO,-1.03,-60.14,282.07,52.31,163223.0,-87294.0,57866.0,1176.00,-57.60,20.0,X-SC,18.12,92.0,-0.53,0.43,0.00,X40N,NTT,FOOTWEAR

In [12]:
# top 5 to exit based on CumlRnk
df_tmp = df_portfolio_features[~df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])]
df_tmp = df_tmp[(df_tmp['Current P/L%'] > -1) & (df_tmp['Current P/L%'] < 1)].sort_values(by = 'CumlRnk', ascending=False)
df_tmp[cols].head()

Empty DataFrame
Columns: [Symbol, Today P/L%, Current P/L%, FTT%, OTT%, FTT Amt, Current P/L, Current, FTT, Dev%_PE, RSI_14, Conviction, Spread%, CumlRnk, RRR Ind, CurrAlloc%, Gained%, Criteria, Strategy, Category]
Index: []

In [13]:
# OX40N stocks to exit
df_tmp = df_portfolio_features[(df_portfolio_features['Symbol'].isin(list_ox40n))].sort_values(by = 'Current P/L%', ascending=False)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
27,FINCABLES,-2.47,18.90,74.87,107.91,131431.0,27902.0,175546.0,1641.55,7.05,65.0,M-SC,7.69,220.0,0.21,1.29,32.07,OX40N,ATH,CABLES
66,SIS,0.65,-33.86,83.33,21.26,61198.0,-37592.0,73440.0,528.00,1719.69,34.0,H-SC,9.21,168.0,-0.61,0.54,1.24,OX40N,NTT,MISC
72,TATAELXSI,0.27,-37.81,112.29,32.03,92068.0,-49844.0,81991.0,9161.00,-22.21,27.0,H-SC,15.82,158.0,-0.54,0.60,0.27,OX40N,NTT,IT
48,KANSAINER,0.42,-37.89,82.69,13.47,138505.0,-102168.0,167499.0,340.00,-46.64,25.0,H-SC,16.15,162.0,-0.74,1.23,0.42,XY24,NTT,PAINTS
77,TTKPRESTIG,3.40,-39.27,64.83,0.09,39674.0,-39580.0,61197.0,770.00,41.94,26.0,M-SC,15.04,250.0,-1.00,0.45,3.40,OX40N,NTT,DURABLES

In [14]:
# top 5 to book for rotation
df_tmp = df_portfolio_features[(df_portfolio_features['Current P/L%'] > 20) ].sort_values(by = 'CumlRnk', ascending=False)
df_tmp[cols].head()

Empty DataFrame
Columns: [Symbol, Today P/L%, Current P/L%, FTT%, OTT%, FTT Amt, Current P/L, Current, FTT, Dev%_PE, RSI_14, Conviction, Spread%, CumlRnk, RRR Ind, CurrAlloc%, Gained%, Criteria, Strategy, Category]
Index: []

In [15]:
# top 5 to monitor for exit
df_tmp = df_portfolio_features[~df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])]
df_tmp = df_tmp[(df_tmp['Current P/L%'] > 0) ].sort_values(by = 'Dev%_PE', ascending=False)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
19,COALINDIA,0.80,8.48,8.47,17.67,13825.0,12766.0,163226.0,478.51,30.56,58.0,L-LC,11.50,185.0,0.92,1.20,26.76,XY25,ATH,MINING
27,FINCABLES,-2.47,18.90,74.87,107.91,131431.0,27902.0,175546.0,1641.55,7.05,65.0,M-SC,7.69,220.0,0.21,1.29,32.07,OX40N,ATH,CABLES
1,ABB,2.87,12.91,28.92,45.57,85427.0,33773.0,295392.0,7934.00,-27.47,63.0,H-MC,9.67,125.0,0.40,2.17,31.17,AR,NTT,ELECTRICAL

In [16]:
# top 5 to book for rotation from weak conviction
df_tmp = df_portfolio_features[~df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])]
df_tmp = df_tmp[~df_tmp['Criteria'].isin(['XY25','XY24','X40', 'X40N'])].sort_values(by = 'RRR Ind', ascending=False)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
1,ABB,2.87,12.91,28.92,45.57,85427.0,33773.0,295392.0,7934.00,-27.47,63.0,H-MC,9.67,125.0,0.40,2.17,31.17,AR,NTT,ELECTRICAL
27,FINCABLES,-2.47,18.90,74.87,107.91,131431.0,27902.0,175546.0,1641.55,7.05,65.0,M-SC,7.69,220.0,0.21,1.29,32.07,OX40N,ATH,CABLES
40,INDIAMART,-0.82,-6.94,122.14,106.72,140189.0,-8559.0,114777.0,4810.62,-58.01,48.0,H-SC,9.01,140.0,-0.06,0.84,14.82,AR,ATH,MISC
85,ZYDUSLIFE,1.31,-2.91,39.69,35.63,80764.0,-6088.0,203486.0,1286.17,-15.32,54.0,H-MC,5.09,120.0,-0.08,1.50,13.28,AR,ATH,PHARMA
84,WIPRO,0.25,-18.28,110.80,72.27,153427.0,-30976.0,138472.0,420.00,-26.43,29.0,M-LC,13.91,98.0,-0.20,1.02,1.97,XR,NTT,IT

In [17]:
# top 5 to accumulate based on lowest RSI_14
df_tmp = df_portfolio_features[df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])].sort_values(by = 'RSI_14', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
8,AWL,0.95,-38.95,173.59,67.02,377576.0,-138799.0,217510.0,485.00,-67.16,17.0,X-SC,22.45,81.0,-0.37,1.60,0.95,XY24,NTT,FMCG
12,BATAINDIA,-0.37,-53.88,193.19,35.20,114633.0,-69333.0,59337.0,2096.00,-22.17,20.0,X-SC,24.76,91.0,-0.60,0.44,0.00,X40,NTT,FOOTWEAR
58,RELAXO,-1.03,-60.14,282.07,52.31,163223.0,-87294.0,57866.0,1176.00,-57.60,20.0,X-SC,18.12,92.0,-0.53,0.43,0.00,X40N,NTT,FOOTWEAR
3,ACC,1.34,-34.21,165.71,74.81,292312.0,-91728.0,176400.0,3906.00,-53.43,23.0,X-SC,11.67,85.0,-0.31,1.30,1.34,XY24,BTT,CEMENT
73,TCS,-1.18,-26.68,72.62,26.57,246681.0,-123586.0,339687.0,4311.58,-38.05,23.0,X-LC,13.12,2.0,-0.50,2.50,0.00,X40,ATH,IT

In [18]:
# top 5 to accumulate based on Spread and CumlRnk
df_tmp = df_portfolio_features[df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])]
df_tmp = df_tmp[(df_tmp['CumlRnk'] < 100)].sort_values(by = 'Spread%', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
22,DABUR,2.44,-6.53,53.73,43.70,124588.0,-16190.0,231878.0,735.00,-15.22,36.0,X-MC,0.92,70.0,-0.13,1.70,7.54,XY24,BTT,FMCG
78,UNITDSPR,3.31,2.89,17.37,20.77,41848.0,6776.0,240920.0,1644.00,-8.78,54.0,X-MC,1.52,64.0,0.16,1.77,9.80,X40N,NTT,BREWERIES
37,ICICIGI,0.39,0.49,18.76,19.34,37725.0,984.0,201093.0,2252.93,-15.42,49.0,X-MC,1.59,66.0,0.03,1.48,14.69,X40,ATH,INSURANCE
59,RELIANCE,-1.02,-9.52,38.49,25.30,69985.0,-19137.0,181826.0,1952.00,-11.96,48.0,X-LC,2.24,21.0,-0.27,1.34,21.40,XY25,BTT,REFINERIES
75,TMPV,2.47,-22.56,76.37,36.58,210447.0,-80279.0,275562.0,600.00,-83.62,36.0,X-LC,2.28,4.0,-0.38,2.03,2.47,XY24,NTT,AUTO

In [19]:
# top 5 to accumulate based on lowest Gained%
df_tmp = df_portfolio_features[df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])].sort_values(by = 'Gained%', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
10,BAJAJHLDNG,-0.94,-9.21,42.32,29.22,73052.0,-17507.0,172618.0,14451.52,-15.85,29.0,X-LC,11.96,28.0,-0.24,1.27,0.00,X40,ATH,FINANCE
12,BATAINDIA,-0.37,-53.88,193.19,35.20,114633.0,-69333.0,59337.0,2096.00,-22.17,20.0,X-SC,24.76,91.0,-0.60,0.44,0.00,X40,NTT,FOOTWEAR
58,RELAXO,-1.03,-60.14,282.07,52.31,163223.0,-87294.0,57866.0,1176.00,-57.60,20.0,X-SC,18.12,92.0,-0.53,0.43,0.00,X40N,NTT,FOOTWEAR
73,TCS,-1.18,-26.68,72.62,26.57,246681.0,-123586.0,339687.0,4311.58,-38.05,23.0,X-LC,13.12,2.0,-0.50,2.50,0.00,X40,ATH,IT
13,BERGEPAINT,0.21,-19.82,56.29,25.32,116336.0,-51077.0,206672.0,680.00,-24.23,29.0,X-MC,15.25,68.0,-0.44,1.52,0.21,XY24,NTT,PAINTS

In [20]:
# top 5 to accumulate based on lowest CurrAlloc%
df_tmp = df_portfolio_features[df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])].sort_values(by = 'CurrAlloc%', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
58,RELAXO,-1.03,-60.14,282.07,52.31,163223.0,-87294.0,57866.0,1176.00,-57.60,20.0,X-SC,18.12,92.0,-0.53,0.43,0.00,X40N,NTT,FOOTWEAR
12,BATAINDIA,-0.37,-53.88,193.19,35.20,114633.0,-69333.0,59337.0,2096.00,-22.17,20.0,X-SC,24.76,91.0,-0.60,0.44,0.00,X40,NTT,FOOTWEAR
54,QUESS,2.12,-22.48,124.33,73.90,102928.0,-24007.0,82786.0,424.00,-58.13,38.0,X-SC,17.78,80.0,-0.23,0.61,2.12,XY24,NTT,MISC
36,HONAUT,2.91,-20.75,90.93,51.31,138964.0,-40013.0,152825.0,58357.33,-34.10,42.0,X-SC,13.52,90.0,-0.29,1.12,2.91,X40N,ATH,ELECTRICAL
2,ABBOTINDIA,-0.96,-9.68,30.71,18.07,49612.0,-17305.0,161550.0,35195.00,-23.22,48.0,X-MC,11.13,58.0,-0.35,1.19,2.42,X40,ATH,PHARMA

In [21]:
# top 5 to accumulate based on CumlRnk
df_tmp = df_portfolio_features.sort_values(by = 'CumlRnk', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
45,ITC,0.98,-18.61,46.28,19.06,128133.0,-63302.0,276864.0,452.00,-55.52,38.0,X-LC,16.93,1.0,-0.49,2.04,0.98,X40,NTT,FMCG
73,TCS,-1.18,-26.68,72.62,26.57,246681.0,-123586.0,339687.0,4311.58,-38.05,23.0,X-LC,13.12,2.0,-0.50,2.50,0.00,X40,ATH,IT
43,INFY,-1.86,-12.15,52.81,34.24,145162.0,-38012.0,274876.0,1972.00,-30.70,28.0,X-LC,11.47,3.0,-0.26,2.02,1.18,X40,NTT,IT
75,TMPV,2.47,-22.56,76.37,36.58,210447.0,-80279.0,275562.0,600.00,-83.62,36.0,X-LC,2.28,4.0,-0.38,2.03,2.47,XY24,NTT,AUTO
34,HCLTECH,-0.14,-11.96,40.65,23.83,86585.0,-28922.0,213002.0,1908.19,-7.36,28.0,X-LC,9.12,8.0,-0.33,1.57,2.19,X40,ATH,IT

In [22]:
# top 5 for average up
df_tmp = df_portfolio_features[(df_portfolio_features['Dev%_200'] > 5)].sort_values(by = 'CurrAlloc%', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
42,INDUSINDBK,1.54,-33.94,101.17,32.89,51598.0,-26206.0,51001.0,1800.00,-340.20,42.0,L-MC,11.56,258.0,-0.51,0.37,40.45,XR,NTT,BANKS
67,SONACOMS,1.00,-12.52,58.99,39.09,52205.0,-12661.0,88498.0,804.02,-30.73,46.0,M-MC,10.22,193.0,-0.24,0.65,25.19,AR,ATH,AUTO
19,COALINDIA,0.80,8.48,8.47,17.67,13825.0,12766.0,163226.0,478.51,30.56,58.0,L-LC,11.50,185.0,0.92,1.20,26.76,XY25,ATH,MINING
27,FINCABLES,-2.47,18.90,74.87,107.91,131431.0,27902.0,175546.0,1641.55,7.05,65.0,M-SC,7.69,220.0,0.21,1.29,32.07,OX40N,ATH,CABLES
11,BANDHANBNK,3.89,-12.98,121.12,92.42,293602.0,-36153.0,242406.0,400.00,107.61,60.0,H-SC,9.97,174.0,-0.12,1.78,33.54,XY24,NTT,BANKS

In [23]:
# top 5 RSP
df_tmp = df_portfolio_features.sort_values(by = 'RSP', ascending=False)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
27,FINCABLES,-2.47,18.90,74.87,107.91,131431.0,27902.0,175546.0,1641.55,7.05,65.0,M-SC,7.69,220.0,0.21,1.29,32.07,OX40N,ATH,CABLES
11,BANDHANBNK,3.89,-12.98,121.12,92.42,293602.0,-36153.0,242406.0,400.00,107.61,60.0,H-SC,9.97,174.0,-0.12,1.78,33.54,XY24,NTT,BANKS
26,EASEMYTRIP,3.61,-58.77,253.41,45.70,184716.0,-103923.0,72892.0,26.40,-24.39,45.0,M-SC,18.16,204.0,-0.56,0.54,20.10,XY24,NTT,TRAVEL
65,SIEMENS,1.66,-11.81,42.32,25.51,69456.0,-21975.0,164120.0,4671.50,37.95,54.0,H-LC,3.56,51.0,-0.32,1.21,20.86,AR,ATH,ELECTRICAL
1,ABB,2.87,12.91,28.92,45.57,85427.0,33773.0,295392.0,7934.00,-27.47,63.0,H-MC,9.67,125.0,0.40,2.17,31.17,AR,NTT,ELECTRICAL

In [24]:
# Top N allocation
df_tmp = df_portfolio_features.sort_values(by = 'CurrAlloc%', ascending=False)
top_n_values = [10, 25, 50]

sum_df = pd.DataFrame({
    'Top_N': top_n_values,
    'Sum_Alloc%': [df_tmp['CurrAlloc%'].head(n).sum() for n in top_n_values]
})

sum_df

   Top_N  Sum_Alloc%
0     10       20.57
1     25       45.48
2     50       77.99

In [25]:
# market-cap-wise allocation
df_tmp = df_portfolio_features[cols]
df_tmp.groupby(df_tmp['Conviction'].str[-2:])['CurrAlloc%'].sum().sort_values(ascending=False)

Conviction
SC    44.54
MC    30.49
LC    24.99
Name: CurrAlloc%, dtype: float64

In [26]:
# criteria-wise allocation
df_portfolio_features.groupby('Criteria')['CurrAlloc%'].sum().sort_values(ascending=False)

Criteria
XY24     27.26
X40      23.88
X40N     15.18
AR        9.11
XY25      8.71
XR        8.25
OX40N     6.86
SR        0.77
Name: CurrAlloc%, dtype: float64

In [27]:
# conviction-wise allocation
df_portfolio_features.groupby('Conviction')['CurrAlloc%'].sum().sort_values(ascending=False)

Conviction
X-MC    23.15
H-SC    21.61
X-LC    21.56
X-SC    12.20
M-SC    10.15
H-MC     4.97
M-MC     2.00
H-LC     1.21
L-LC     1.20
M-LC     1.02
L-SC     0.58
L-MC     0.37
Name: CurrAlloc%, dtype: float64

In [28]:
# sector-wise stats
df_tmp = df_portfolio_features.groupby('Category')[['CurrAlloc%', 'Current', 'Current P/L', 'FTT Amt']].sum().sort_values(by=['Current', 'Current P/L'], ascending=False)
df_tmp['Current P/L%'] = round(df_tmp['Current P/L'] * 100 / df_tmp['Current'], 2)
df_tmp['FTT%'] = round(df_tmp['FTT Amt'] * 100 / df_tmp['Current'], 2)
cols = ['CurrAlloc%', 'Current P/L%', 'FTT%']
df_tmp[cols].sort_values(by=['CurrAlloc%'], ascending=False)

               CurrAlloc%  Current P/L%    FTT%
Category
FMCG                15.42        -19.03   61.30
FINANCE             12.81        -23.48   73.80
IT                  11.66        -42.06  114.35
MISC                 6.93        -42.21  103.98
ELECTRICAL           6.59         -7.96   49.30
PAINTS               5.21        -39.08   63.23
INSURANCE            4.74         -5.21   41.22
PHARMA               4.16         -4.09   36.85
AUTO                 3.75        -28.31   79.22
BANKS                3.15        -24.55  100.03
AC                   2.14         -9.91   39.71
HEALTHCARE           1.97        -33.35   68.15
FOOTWEAR             1.86        -74.94  145.09
TRAVEL               1.84        -78.70  168.18
DURABLES             1.79        -58.65   97.24
BREWERIES            1.77          2.81   17.37
APPARELS             1.60        -23.08   65.07
REALTY               1.46        -11.60   29.94
REFINERIES           1.34        -10.52   38.49
CERAMICS             1.33        -69.86  121.47
CEMENT               1.30        -52.00  165.71
CABLES               1.29         15.89   74.87
MINING               1.20          7.82    8.47
JEWELLERY            1.10       -112.87  186.83
ENGINEERING          1.10        -61.54  135.42
CHEMICALS            0.96       -102.79  268.23
ENTERTAINMENT        0.76        -86.00  196.94
TEXTILES             0.42        -61.90  108.06
HOTELS               0.37       -122.75  201.32

In [29]:
# money to be made criteria-wise
df_portfolio_features.groupby('Criteria')['FTT Amt'].agg(['sum', 'count']).sort_values(by='sum', ascending=False)

                sum  count
Criteria
XY24      3887235.0     21
X40       1626312.0     15
XR        1368038.0     12
AR        1332883.0     10
X40N      1235109.0     10
OX40N      858740.0     10
XY25       434340.0      6
SR         314516.0      2

In [30]:
# money to be made conviction-wise
df_portfolio_features.groupby('Conviction')['FTT Amt'].agg(['sum', 'count']).sort_values(by='sum', ascending=False)

                  sum  count
Conviction
H-SC        3852462.0     24
X-MC        1584279.0     15
X-LC        1543236.0     12
M-SC        1536189.0     14
X-SC        1524756.0     10
H-MC         402451.0      3
L-SC         211010.0      2
M-LC         153427.0      1
M-MC         114484.0      2
H-LC          69456.0      1
L-MC          51598.0      1
L-LC          13825.0      1

In [31]:
# money to be made criteria and conviction-wise
df_portfolio_features.groupby(['Conviction', 'Criteria'])['FTT Amt'].agg(['sum', 'count']).sort_values(by='sum', ascending=False)

                           sum  count
Conviction Criteria
H-SC       XY24      1313401.0      6
           AR         968472.0      5
M-SC       XY24       904960.0      6
H-SC       XR         870207.0      7
X-SC       XY24       829626.0      4
X-LC       X40        801359.0      6
X-MC       X40        625982.0      7
           X40N       502183.0      4
X-SC       X40N       496159.0      4
H-SC       OX40N      385866.0      4
M-SC       OX40N      364489.0      5
X-LC       XY24       362064.0      2
H-SC       SR         314516.0      2
X-MC       XY24       240924.0      2
X-LC       X40N       236767.0      2
H-MC       XY24       236260.0      1
X-MC       XY25       215190.0      2
X-SC       X40        198971.0      2
M-SC       XR         190181.0      2
H-MC       AR         166191.0      2
M-LC       XR         153427.0      1
X-LC       XY25       143046.0      2
L-SC       OX40N      108385.0      1
           XR         102625.0      1
M-SC       AR          76559.0      1
H-LC       AR          69456.0      1
M-MC       XY25        62279.0      1
           AR          52205.0      1
L-MC       XR          51598.0      1
L-LC       XY25        13825.0      1

In [32]:
# notebook execution time

end_time = time.time()
execution_time = round(end_time - start_time, 0)
print(f"Notebook execution time: {execution_time} seconds")

Notebook execution time: 27.0 seconds