<a href="https://colab.research.google.com/github/ankit-rathi/Quantvesting_v2/blob/main/myStocks_Portfolio_Analysis.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
'''
!pip install pandas==2.2.2 -qq
!pip install pyxirr -qq
!pip install ta -qq
!pip install yfinance==0.2.59 -qq
'''

'\n!pip install pandas==2.2.2 -qq\n!pip install pyxirr -qq\n!pip install ta -qq\n!pip install yfinance==0.2.59 -qq\n'

In [2]:
# import libraries

import numpy as np
import pandas as pd
import datetime
import warnings
warnings.filterwarnings('ignore')
import yfinance as yfin
import ta
import matplotlib.pyplot as plt
import requests

In [3]:
# notebook start time
import time
import datetime
import pytz

start_time = time.time()

# function to print date timestamp
def print_date_time():
  tz_NY = pytz.timezone('Asia/Kolkata')
  datetime_NY = datetime.datetime.now(tz_NY)
  print("Run date time (IST):", datetime_NY.strftime("%Y-%m-%d %H:%M:%S"))

In [4]:
# function to get booked and reserved amount
def get_amt():
  # fetch the JSON data from the URL
  url = "https://raw.githubusercontent.com/ankit-rathi/Tradevesting_v1/main/data/myPortfolioAmts.json"
  response = requests.get(url)
  pf_amts = response.json()  # parse the JSON data

  # extract values from the JSON
  py_booked_amt_dm = pf_amts["py_booked_amt_dm"]
  py_booked_amt_sv = pf_amts["py_booked_amt_sv"]
  cy_booked_amt_dm = pf_amts["cy_booked_amt_dm"]
  cy_booked_amt_sv = pf_amts["cy_booked_amt_sv"]
  reserve_amt_dm = pf_amts["reserve_amt_dm"]
  reserve_amt_sv = pf_amts["reserve_amt_sv"]

  # perform calculations
  py_booked_amt = py_booked_amt_dm + py_booked_amt_sv
  cy_booked_amt = cy_booked_amt_dm + cy_booked_amt_sv
  reserve_amt = reserve_amt_dm + reserve_amt_sv
  total_booked_amt = py_booked_amt + cy_booked_amt

  return total_booked_amt, reserve_amt, cy_booked_amt, py_booked_amt

gen_output = 0

In [5]:
# function to format the amount
def format_amt(number):
    abs_number = abs(number)

    if abs_number >= 1_00_00_000:  # Crores
        formatted_amt = f"{number / 1_00_00_000:.2f} C"
    elif abs_number >= 1_00_000:  # Lakhs
        formatted_amt = f"{number / 1_00_000:.2f} L"
    elif abs_number >= 1_000:  # Thousands
        formatted_amt = f"{number / 1_000:.2f} K"
    else:
        formatted_amt = f"{number:.2f}"

    return formatted_amt

# function to set start and end date
def get_start_end_date():
  start_date = (datetime.date.today() + datetime.timedelta(days=-365)).strftime('%Y-%m-%d')
  end_date = (datetime.date.today() + datetime.timedelta(days=1)).strftime('%Y-%m-%d')
  return start_date, end_date

# function to fetch my portfolio csv
def get_mypfs_df():
  mypfs_df = pd.read_csv('https://raw.githubusercontent.com/ankit-rathi/Tradevesting_v1/main/data/myPortfolioStocks.csv')
  return mypfs_df

# function to fetch my prospects csv
def get_mypps_df():
  mypps_df = pd.read_csv('https://raw.githubusercontent.com/ankit-rathi/Tradevesting_v1/main/data/myProspectsScrips.csv')
  return mypps_df

# function to fetch screener data
def get_myscreen_df():
  myscreen_df = pd.read_csv('https://raw.githubusercontent.com/ankit-rathi/Tradevesting_v1/main/data/myScreenerDB.csv')
  return myscreen_df

# function to fetch momentum data
def get_myinvmt_df():
  myinvmt_df = pd.read_csv('https://raw.githubusercontent.com/ankit-rathi/Tradevesting_v1/main/data/myInvestments.csv')
  return myinvmt_df

# function to get the stock ids
def get_stock_ids(df_pf):
  stock_n100 = df_pf['Symbol'].unique()

  exclude = ['CADILAHC','MMTC', 'MASFIN']

  stock_ids = df_pf[~df_pf['Symbol'].isin(exclude) ]['Symbol'].unique()

  #mypf = mypf[mypf.Forecast.notnull()]
  #stock_ids = mypf['Symbol'].unique()

  #stock_ids.sort()
  return stock_ids

# get features from screener data
def get_screener_features():
  myscreen_df = get_myscreen_df()
  cols = ['Symbol', 'EPS', 'MedPE', 'ROCE%', 'ROE%', 'CapType']
  return myscreen_df[cols]

# get relative strength
def get_relative_strength(stock_list):

    # Dictionary to store stock tickers and their corresponding percentage price change
    stock_changes = {}

    # Loop through each stock and fetch its price data
    for stock in stock_list:
        try:
            # Download the stock data for the given date range
            stock_data = yfin.Ticker(stock + '.NS').history(period='1mo', interval='1d')[map(str.title, ['open', 'close', 'low', 'high', 'volume'])]

            # Calculate the percentage change for the stock
            if len(stock_data) > 0:
                start_price = stock_data['Close'].iloc[0]
                end_price = stock_data['Close'].iloc[-1]
                percent_change = round(((end_price - start_price) / start_price) * 100, 2)
                stock_changes[stock] = percent_change
            else:
                stock_changes[stock] = np.nan  # If no data is available, set to NaN

        except Exception as e:
            print(f"Error fetching data for {stock}: {e}")
            stock_changes[stock] = np.nan

    # Create a DataFrame with stock tickers and their percentage changes
    df = pd.DataFrame(list(stock_changes.items()), columns=['Symbol', 'Percent_Change'])

    # Drop any stocks with missing data (NaN values)
    df = df.dropna()

    # Calculate the percentile rank based on percentage change
    df['RSP'] = round(df['Percent_Change'].rank(pct=True) * 100, 2)
    cols = ['Symbol', 'RSP']
    df = df[cols]
    # Sort by percentile rank (optional)
    df = df.sort_values(by='RSP', ascending=False).reset_index(drop=True)

    return df

In [6]:
# function to get stock technicals
def stock_prec_dev(stock_symbol):
    #stock_symbol = 'ULTRACEMCO.NS'
    short_window = 20
    mid_window = 50
    long_window = 200
    moving_avg = 'SMA'

    start = datetime.datetime(*map(int, start_date.split('-')))
    end = datetime.datetime(*map(int, end_date.split('-')))

    stock_df = yfin.Ticker(stock_symbol + '.NS').history(period='max', interval='1d')[map(str.title, ['open', 'close', 'low', 'high', 'volume'])]

    stock_df['Max'] = round(max(stock_df['Close']),2)
    stock_df = stock_df[(stock_df.index <= end_date) & (stock_df.index >= start_date)]
    stock_df['200_SMA'] = round(stock_df['Close'].rolling(window = 200, min_periods = 1).mean(),0)
    stock_df['Dev%_200'] = round((stock_df['Close'] - stock_df['200_SMA'])*100/stock_df['200_SMA'],2)
    stock_df.dropna(axis = 0, inplace = True) # remove any null rows

    stock_df['20_SMA'] = stock_df['Close'].rolling(window=20).mean()
    stock_df['50_SMA'] = stock_df['Close'].rolling(window=50).mean()
    stock_df['Symbol'] = stock_symbol

    stock_df['Close'] = round(stock_df['Close'],2)
    stock_df['Min'] = round(min(stock_df['Close']),2)
    stock_df['RSI_14'] = ta.momentum.RSIIndicator(close=stock_df['Close'], window=14).rsi()
    stock_df['RSI_14'] = round(stock_df['RSI_14'],0)
    stock_df['Prev_Close'] = stock_df['Close'].shift(1)
    stock_df.drop(['Open', 'Low', 'High', 'Volume'], axis=1, inplace=True)
    stock_df = stock_df.tail(1)

    max_SMA = max(stock_df['20_SMA'].item(), stock_df['50_SMA'].item(), stock_df['200_SMA'].item())
    min_SMA = min(stock_df['20_SMA'].item(), stock_df['50_SMA'].item(), stock_df['200_SMA'].item())
    ABS_Spread = max_SMA - min_SMA
    stock_df['Spread%'] = round((ABS_Spread / stock_df['200_SMA'].item()) * 100,2)

    return stock_df

# function to compute stock attributes
def get_common_features(stock_ids, df_mypf):

  df_prec_dev = pd.DataFrame()
  df_tmp = get_screener_features()
  df_rs = get_relative_strength(stock_ids)

  for stock_id in stock_ids:
      tmp = stock_prec_dev(stock_id)
      tmp = tmp.reset_index()
      df_prec_dev = pd.concat([df_prec_dev, tmp], ignore_index = True)
  df_prec_dev = pd.merge(df_prec_dev, df_mypf, on= 'Symbol')
  df_prec_dev = pd.merge(df_prec_dev, df_tmp, on= 'Symbol', how='left')
  df_prec_dev = pd.merge(df_prec_dev, df_rs, on= 'Symbol', how='left')
  #print(df_prec_dev.columns)
  df_prec_dev['Curr_PE'] = round(df_prec_dev['Close']/df_prec_dev['EPS'],1)
  df_prec_dev['Dev%_PE'] = round((df_prec_dev['Curr_PE'] - df_prec_dev['MedPE'])*100/df_prec_dev['MedPE'],2)
  df_prec_dev['Conviction'] = df_prec_dev['Conviction'] + '-' + df_prec_dev['CapType']
  return df_prec_dev

# function to arrange stock features
def arrange_features(df_stocks, common_cols, diff_cols):
  df_stocks_common = df_stocks[common_cols].drop_duplicates()
  df_stocks_diff = df_stocks[diff_cols]
  df_stocks_diff['Investment'] = df_stocks_diff['AvgCost'] * df_stocks_diff['Shares']
  df_stocks_diff = df_stocks_diff.groupby(['Symbol'])[['Shares', 'Investment']].aggregate(['sum']).reset_index()
  df_stocks_diff.columns = ['Symbol', 'Shares', 'Investment']
  df_stocks_diff['AvgCost'] = round(df_stocks_diff['Investment']/df_stocks_diff['Shares'],2)
  df_stocks = pd.merge(df_stocks_diff, df_stocks_common, on='Symbol')
  return df_stocks

# plot fact distribution across dimension
def plot_pie_chart(df, dimension, fact):
  # grouping the data by category and calculating the sum of fact for each type
  grouped_data = df.groupby(dimension)[fact].sum()

  # sorting the grouped data in descending order
  grouped_data = grouped_data.sort_values(ascending=False)

  # creating a pie chart
  grouped_data.plot.pie(autopct='%1.1f%%', startangle=90, figsize=(6, 6))

  # adding a title and displaying the plot
  plt.title(f'{dimension} {fact} Distribution')
  plt.ylabel('')  # To hide the y-label
  plt.show()

In [7]:
# function to get portfolio features

def get_portfolio_features(df_common_features):

  print_date_time()
  print('-------------------')

  #df_common_features["Target"] = df_common_features["Target"].fillna(df_common_features["Max"])
  df_common_features['NTT'] = np.where(df_common_features['Strategy']== 'NTT', df_common_features["Target"], df_common_features['Max'])
  df_common_features['LTT'] = np.where(df_common_features['Strategy']== 'BTT', df_common_features["Target"], df_common_features['Max'])
  df_common_features['BOL'] = df_common_features['Min']

  tmp_df = df_common_features[df_common_features['Symbol'].isin(mypf_df[mypf_df['InPortfolio'] != 'NA'].Symbol.values)]
  print('qualified stocks: '+str(len(tmp_df['Symbol'].unique())))
  tmp_df1 = tmp_df[tmp_df['LatestQtr'] == 1]
  print('with latest results: '+str(len(tmp_df1['Symbol'].unique())))
  tmp_df1 = tmp_df1[tmp_df1['StarStock'] == 1]
  print('still star stocks: '+str(len(tmp_df1['Symbol'].unique())))
  tmp_df['Investment'] = tmp_df['AvgCost'] * tmp_df['Shares']
  tmp_df['Current'] = round(tmp_df['Close'] * tmp_df['Shares'],0)
  tmp_df['Previous'] = tmp_df['Prev_Close'] * tmp_df['Shares']
  tmp_df['EstimatedST'] = tmp_df['NTT'] * tmp_df['Shares']
  tmp_df['EstimatedLT'] = tmp_df['LTT'] * tmp_df['Shares']
  tmp_df['Current P/L'] = round((tmp_df['Current'] - tmp_df['Investment']),0)
  tmp_df['Today P/L%'] = round((tmp_df['Current'] - tmp_df['Previous'])*100/tmp_df['Previous'],2)
  tmp_df['Current P/L%'] = round((tmp_df['Current'] - tmp_df['Investment'])*100/tmp_df['Investment'],2)
  tmp_df['EstimatedST P/L%'] = round((tmp_df['EstimatedST'] - tmp_df['Investment'])*100/tmp_df['Investment'],2)
  tmp_df['EstimatedLT P/L%'] = round((tmp_df['EstimatedLT'] - tmp_df['Investment'])*100/tmp_df['Investment'],2)
  tmp_df['NTT%'] = round((tmp_df['NTT'] - tmp_df['Close'])*100/tmp_df['Close'],2)
  tmp_df['LTT%'] = round((tmp_df['LTT'] - tmp_df['Close'])*100/tmp_df['Close'],2)
  tmp_df['Gained%'] = round((tmp_df['Close'] - tmp_df['BOL'])*100/tmp_df['BOL'],2)
  investment = round(sum(tmp_df['AvgCost']*tmp_df['Shares']),0)
  current = round(sum(tmp_df['Close']*tmp_df['Shares']),0)
  tmp_df['InitAlloc%'] = round(tmp_df['Investment']*100/investment,2)
  tmp_df['CurrAlloc%'] = round(tmp_df['Current']*100/current,2)
  tmp_df['FTT'] = tmp_df['LTT']
  tmp_df.loc[tmp_df['Strategy'] == 'NTT', 'FTT'] = tmp_df['NTT']
  tmp_df['FTT%'] = tmp_df['LTT%']
  tmp_df.loc[tmp_df['Strategy'] == 'NTT', 'FTT%'] = tmp_df['NTT%']
  tmp_df['FTT Amt'] = round(tmp_df['FTT%'] * tmp_df['Current']/100,0)
  tmp_df['OTT%'] = round((tmp_df['FTT'] - tmp_df['AvgCost'])*100/tmp_df['AvgCost'],2)
  tmp_df['RRR Ind'] = round(tmp_df['Current P/L']/tmp_df['FTT Amt'],2)
  tmp_df['Risk Ind'] = round(tmp_df['Current P/L%']*tmp_df['CurrAlloc%'],0)

  return tmp_df

# function to print portfolio features
def print_portfolio_stats(df_portfolio_features, myinvmt_df):
  from pyxirr import xirr

  total_booked_amt, reserve_amt, cy_booked_amt, py_booked_amt = get_amt()

  dates = myinvmt_df['Date'].values
  dates = np.append(dates, datetime.date.today().strftime('%d-%b-%y'))
  investment = myinvmt_df['Investment'].values
  dates= pd.to_datetime(dates)

  current = round(sum(df_portfolio_features['Close']*df_portfolio_features['Shares']),0) + reserve_amt
  investment_xirr = np.append(investment, current)
  cagr = round(xirr(pd.DataFrame({"dates": dates, "amounts": investment_xirr}))*100,2)

  investment = -sum(investment)
  invested = round(sum(df_portfolio_features['AvgCost']*df_portfolio_features['Shares']),0) + reserve_amt
  previous = round(sum(df_portfolio_features['Prev_Close']*df_portfolio_features['Shares']),0) + reserve_amt
  cy_invested = investment + py_booked_amt

  today_pnl_amount = current-previous
  today_pnl_percentage = round((current-previous)*100/previous,2)

  curr_pnl_amount = current-invested
  curr_pnl_percentage = round((curr_pnl_amount)*100/(cy_invested),2)

  cy_pnl_amount = cy_booked_amt + curr_pnl_amount
  cy_pnl_percentage = round((cy_pnl_amount)*100/cy_invested,2)

  overall_pnl_amount = total_booked_amt + curr_pnl_amount
  overall_pnl_percentage = round((overall_pnl_amount)*100/investment,2)

  estimate_st = round(sum(df_portfolio_features['FTT']*df_portfolio_features['Shares']),0)  + reserve_amt
  est_st_pnl_amount = estimate_st-current
  est_st_pnl_percentage = round((est_st_pnl_amount)*100/current,2)

  estimate_lt = round(sum(df_portfolio_features['LTT']*df_portfolio_features['Shares']),0)  + reserve_amt
  est_lt_pnl_amount = estimate_lt-current
  est_lt_pnl_percentage = round((est_lt_pnl_amount)*100/current,2)

  total_profit = round(sum(df_portfolio_features[df_portfolio_features['Current P/L%'] > 0]['Current']) - sum(df_portfolio_features[df_portfolio_features['Current P/L%'] > 0]['Investment']),0)
  total_loss = round(sum(df_portfolio_features[df_portfolio_features['Current P/L%'] < 0]['Current']) - sum(df_portfolio_features[df_portfolio_features['Current P/L%'] < 0]['Investment']),0)

  cy_booked_percentage = round((cy_booked_amt)*100/current,2)
  py_booked_percentage = round((py_booked_amt)*100/investment,2)
  total_booked_percentage = round((total_booked_amt)*100/investment,2)

  print('-------------------')
  print('Initial Investment: ', format_amt(investment))
  print('CY Investment: ', format_amt(cy_invested))
  print('Reserve: ', format_amt(reserve_amt))
  print('Current: ',  format_amt(current))
  print('-------------------')
  print('Today PnL: '+ '{} ({}%)'.format(format_amt(today_pnl_amount), today_pnl_percentage))
  print('Current PnL: '+ '{} ({}%)'.format(format_amt(curr_pnl_amount), curr_pnl_percentage))
  print('CY Booked + Current PnL: '+ '{} ({}%)'.format(format_amt(cy_pnl_amount), cy_pnl_percentage))
  print('-------------------')
  print('Total profit: ', format_amt(total_profit))
  print('Total loss: ', format_amt(total_loss))
  print('-------------------')
  print('Total Booked + Current PnL: '+ '{} ({}%)'.format(format_amt(overall_pnl_amount), overall_pnl_percentage))
  print('Total Booked PnL: '+ '{} ({}%)'.format(format_amt(total_booked_amt), total_booked_percentage))
  print('Curr Year Booked PnL: '+ '{} ({}%)'.format(format_amt(cy_booked_amt), cy_booked_percentage))
  print('Prev Year Booked PnL: '+ '{} ({}%)'.format(format_amt(py_booked_amt), py_booked_percentage))
  print('===================')
  print('Est FTT: ',  format_amt(estimate_st))
  print('Est FTT PnL: '+ '{} ({}%)'.format(format_amt(est_st_pnl_amount), est_st_pnl_percentage))

  print('===================')
  print('Deployed: ', format_amt(investment))

  print('Current: ', format_amt(current))

  print('CAGR/XIRR %: '+'{}%'.format(cagr))

In [8]:
# get start and end date
start_date, end_date = get_start_end_date()

# get portfolio and prospects data
mypfs_df = get_mypfs_df()
mypps_df = get_mypps_df()
myinvmt_df = get_myinvmt_df()

# merge above datasets
mypf_df = pd.merge(mypfs_df, mypps_df, on="Symbol")

# seggregate dm and sv portfolio
dm_pf = mypf_df[mypf_df['InPortfolio'] == 'DM']
sv_pf = mypf_df[mypf_df['InPortfolio'] == 'SV']

# build portfolio stock dataframe
dm_stocks = get_stock_ids(dm_pf)
sv_stocks = get_stock_ids(sv_pf)
df_stocks = pd.concat([dm_pf,sv_pf], ignore_index = True)

# arrange common and diff stock features
common_cols = ['Symbol', 'Target', 'Criteria', 'Strategy', 'CumlRnk', 'LatestQtr', 'StarStock', 'Conviction', 'Category', 'InFolio', 'XIRR', 'MBQ']
diff_cols = ['Symbol', 'AvgCost', 'Shares']
df_stocks = arrange_features(df_stocks, common_cols, diff_cols)

# get common features
stock_ids = df_stocks['Symbol'].values
df_common_features = get_common_features(stock_ids, df_stocks)

df_common_features.reset_index(drop=True, inplace=True)
df_common_features.drop(['Date'], axis=1, inplace=True)
# get and print portfolio features
df_portfolio_features = get_portfolio_features(df_common_features)

print_portfolio_stats(df_portfolio_features, myinvmt_df)

df = df_portfolio_features
#plot_pie_chart(df, 'CapType', 'Current')
list_ox40n = list(df[df['MBQ'].str.contains('OX40N', na=False)]['Symbol'].values)

Run date time (IST): 2026-03-11 14:11:35
-------------------
qualified stocks: 86
with latest results: 26
still star stocks: 15

-------------------
Initial Investment:  1.36 C
CY Investment:  1.62 C
Reserve:  66.25 K
Current:  1.37 C
-------------------
Today PnL: 10.92 K (0.08%)
Current PnL: -39.69 L (-24.43%)
CY Booked + Current PnL: -24.01 L (-14.78%)
-------------------
Total profit:  1.09 L
Total loss:  -40.78 L
-------------------
Total Booked + Current PnL: 2.97 L (2.19%)
Total Booked PnL: 42.66 L (31.48%)
Curr Year Booked PnL: 15.68 L (11.43%)
Prev Year Booked PnL: 26.98 L (19.91%)
===================
Est FTT:  2.47 C
Est FTT PnL: 1.10 C (80.19%)
===================
Deployed:  1.36 C
Current:  1.37 C
CAGR/XIRR %: 0.64%

In [9]:
# top 5 near their targets
cols = ['Symbol', 'Today P/L%', 'Current P/L%', 'FTT%', 'OTT%', 'FTT Amt', 'Current P/L', 'Current', 'FTT', 'Dev%_PE', 'RSI_14','Conviction', 'Spread%',  'CumlRnk', 'RRR Ind', 'CurrAlloc%', 'Gained%', 'Criteria', 'Strategy', 'Category']
df_tmp = df_portfolio_features[~df_portfolio_features['Symbol'].isin(['ENRIN','BLUSPRING','DIGITIDE'])]
df_tmp = df_tmp.sort_values(by = 'FTT Amt', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
19,COALINDIA,1.27,10.46,6.52,17.67,10837.0,15744.0,166204.0,478.51,33.43,62.0,L-LC,11.55,185.0,1.45,1.22,29.07,XY25,ATH,MINING
50,MASFIN,-1.03,-6.26,29.69,21.57,27269.0,-6135.0,91845.0,397.04,-19.15,40.0,H-SC,4.62,167.0,-0.22,0.67,28.16,XR,ATH,FINANCE
77,TTKPRESTIG,11.66,-29.68,42.33,0.09,30000.0,-29906.0,70871.0,770.00,64.57,52.0,M-SC,15.12,250.0,-1.00,0.52,19.74,OX40N,NTT,DURABLES
37,ICICIGI,-0.08,-0.01,19.35,19.34,38719.0,-13.0,200096.0,2252.93,-15.91,47.0,X-MC,1.66,66.0,-0.00,1.47,14.12,X40,ATH,INSURANCE
78,UNITDSPR,-1.70,1.61,18.85,20.77,44846.0,3766.0,237910.0,1644.00,-9.86,51.0,X-MC,1.50,64.0,0.08,1.74,8.42,X40N,NTT,BREWERIES

In [10]:
# top 5 today
df_tmp = df_portfolio_features.sort_values(by = 'Today P/L%', ascending=False)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
77,TTKPRESTIG,11.66,-29.68,42.33,0.09,30000.0,-29906.0,70871.0,770.00,64.57,52.0,M-SC,15.12,250.0,-1.00,0.52,19.74,OX40N,NTT,DURABLES
24,DIXON,11.26,-20.53,73.56,37.92,152455.0,-53546.0,207252.0,18931.72,-66.19,52.0,X-MC,25.39,54.0,-0.35,1.52,11.26,X40N,ATH,IT
31,HAPPSTMNDS,5.52,-47.25,250.42,84.85,169304.0,-60557.0,67608.0,1480.71,-37.33,65.0,H-SC,28.55,152.0,-0.36,0.50,25.20,AR,ATH,IT
55,RAJESHEXPO,4.86,-77.88,352.40,0.07,106925.0,-106835.0,30342.0,518.00,1012.37,23.0,L-SC,18.86,268.0,-1.00,0.22,4.86,OX40N,NTT,JEWELLERY
15,BSOFT,4.48,-30.19,116.00,50.79,113898.0,-42465.0,98188.0,831.70,-10.32,46.0,H-SC,5.00,172.0,-0.37,0.72,14.32,XR,ATH,IT

In [11]:
# bottom 5 today
df_tmp = df_portfolio_features.sort_values(by = 'Today P/L%', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
21,COLPAL,-6.10,-21.62,80.55,41.51,166271.0,-56945.0,206420.0,3726.84,-5.18,38.0,X-MC,4.18,62.0,-0.34,1.51,0.86,XY25,ATH,FMCG
27,FINCABLES,-3.80,13.19,83.68,107.91,139848.0,19478.0,167122.0,1641.55,1.98,56.0,M-SC,7.69,220.0,0.14,1.22,25.73,OX40N,ATH,CABLES
75,TMPV,-2.56,-23.44,78.39,36.58,213569.0,-83397.0,272444.0,600.00,-83.62,36.0,X-LC,1.86,4.0,-0.39,1.99,1.31,XY24,NTT,AUTO
5,ANGELONE,-2.47,-9.94,37.88,24.18,104052.0,-30312.0,274688.0,303.00,-86.88,33.0,X-SC,4.74,97.0,-0.29,2.01,15.04,X40N,NTT,FINANCE
40,INDIAMART,-2.27,-8.47,125.84,106.72,142067.0,-10441.0,112895.0,4810.62,-58.79,44.0,H-SC,9.20,140.0,-0.07,0.83,12.93,AR,ATH,MISC

In [12]:
# top 5 to exit based on CumlRnk
df_tmp = df_portfolio_features[~df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])]
df_tmp = df_tmp[(df_tmp['Current P/L%'] > -1) & (df_tmp['Current P/L%'] < 1)].sort_values(by = 'CumlRnk', ascending=False)
df_tmp[cols].head()

Empty DataFrame
Columns: [Symbol, Today P/L%, Current P/L%, FTT%, OTT%, FTT Amt, Current P/L, Current, FTT, Dev%_PE, RSI_14, Conviction, Spread%, CumlRnk, RRR Ind, CurrAlloc%, Gained%, Criteria, Strategy, Category]
Index: []

In [13]:
# OX40N stocks to exit
df_tmp = df_portfolio_features[(df_portfolio_features['Symbol'].isin(list_ox40n))].sort_values(by = 'Current P/L%', ascending=False)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
27,FINCABLES,-3.80,13.19,83.68,107.91,139848.0,19478.0,167122.0,1641.55,1.98,56.0,M-SC,7.69,220.0,0.14,1.22,25.73,OX40N,ATH,CABLES
77,TTKPRESTIG,11.66,-29.68,42.33,0.09,30000.0,-29906.0,70871.0,770.00,64.57,52.0,M-SC,15.12,250.0,-1.00,0.52,19.74,OX40N,NTT,DURABLES
66,SIS,-0.03,-33.35,81.94,21.26,60636.0,-37031.0,74001.0,528.00,1733.68,36.0,H-SC,10.04,168.0,-0.61,0.54,2.02,OX40N,NTT,MISC
70,SYMPHONY,4.05,-36.85,58.30,-0.03,63008.0,-63066.0,108075.0,1306.00,-49.31,48.0,M-SC,13.21,205.0,-1.00,0.79,9.29,OX40N,NTT,DURABLES
72,TATAELXSI,0.51,-36.89,109.20,32.03,90855.0,-48634.0,83201.0,9161.00,-21.03,31.0,H-SC,16.55,158.0,-0.54,0.61,1.75,OX40N,NTT,IT

In [14]:
# top 5 to book for rotation
df_tmp = df_portfolio_features[(df_portfolio_features['Current P/L%'] > 20) ].sort_values(by = 'CumlRnk', ascending=False)
df_tmp[cols].head()

Empty DataFrame
Columns: [Symbol, Today P/L%, Current P/L%, FTT%, OTT%, FTT Amt, Current P/L, Current, FTT, Dev%_PE, RSI_14, Conviction, Spread%, CumlRnk, RRR Ind, CurrAlloc%, Gained%, Criteria, Strategy, Category]
Index: []

In [15]:
# top 5 to monitor for exit
df_tmp = df_portfolio_features[~df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])]
df_tmp = df_tmp[(df_tmp['Current P/L%'] > 0) ].sort_values(by = 'Dev%_PE', ascending=False)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
19,COALINDIA,1.27,10.46,6.52,17.67,10837.0,15744.0,166204.0,478.51,33.43,62.0,L-LC,11.55,185.0,1.45,1.22,29.07,XY25,ATH,MINING
27,FINCABLES,-3.80,13.19,83.68,107.91,139848.0,19478.0,167122.0,1641.55,1.98,56.0,M-SC,7.69,220.0,0.14,1.22,25.73,OX40N,ATH,CABLES
1,ABB,1.09,15.45,26.09,45.57,78802.0,40421.0,302040.0,7934.00,-25.80,66.0,H-MC,10.07,125.0,0.51,2.21,34.13,AR,NTT,ELECTRICAL

In [16]:
# top 5 to book for rotation from weak conviction
df_tmp = df_portfolio_features[~df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])]
df_tmp = df_tmp[~df_tmp['Criteria'].isin(['XY25','XY24','X40', 'X40N'])].sort_values(by = 'RRR Ind', ascending=False)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
1,ABB,1.09,15.45,26.09,45.57,78802.0,40421.0,302040.0,7934.00,-25.80,66.0,H-MC,10.07,125.0,0.51,2.21,34.13,AR,NTT,ELECTRICAL
27,FINCABLES,-3.80,13.19,83.68,107.91,139848.0,19478.0,167122.0,1641.55,1.98,56.0,M-SC,7.69,220.0,0.14,1.22,25.73,OX40N,ATH,CABLES
85,ZYDUSLIFE,0.50,-2.17,38.64,35.63,79221.0,-4552.0,205022.0,1286.17,-14.86,57.0,H-MC,5.04,120.0,-0.06,1.50,14.14,AR,ATH,PHARMA
40,INDIAMART,-2.27,-8.47,125.84,106.72,142067.0,-10441.0,112895.0,4810.62,-58.79,44.0,H-SC,9.20,140.0,-0.07,0.83,12.93,AR,ATH,MISC
84,WIPRO,0.83,-16.91,107.32,72.27,151107.0,-28648.0,140800.0,420.00,-25.02,35.0,M-LC,14.47,98.0,-0.19,1.03,3.68,XR,NTT,IT

In [17]:
# top 5 to accumulate based on lowest RSI_14
df_tmp = df_portfolio_features[df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])].sort_values(by = 'RSI_14', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
58,RELAXO,-0.78,-60.43,284.88,52.31,163644.0,-87717.0,57443.0,1176.00,-57.89,19.0,X-SC,18.73,92.0,-0.54,0.42,0.00,X40N,NTT,FOOTWEAR
12,BATAINDIA,0.31,-53.61,191.46,35.20,114281.0,-68981.0,59689.0,2096.00,-21.73,22.0,X-SC,25.48,91.0,-0.60,0.44,0.31,X40,NTT,FOOTWEAR
3,ACC,-0.49,-34.35,166.29,74.81,292697.0,-92112.0,176016.0,3906.00,-53.43,23.0,X-SC,12.20,85.0,-0.31,1.29,1.12,XY24,BTT,CEMENT
73,TCS,-0.57,-26.22,71.56,26.57,244579.0,-121491.0,341782.0,4311.59,-37.40,24.0,X-LC,13.09,2.0,-0.50,2.50,0.00,X40,ATH,IT
53,PGHH,-0.28,-19.24,63.45,32.01,109418.0,-41072.0,172448.0,17616.87,-45.38,25.0,X-MC,11.28,57.0,-0.38,1.26,1.64,X40,ATH,FMCG

In [18]:
# top 5 to accumulate based on Spread and CumlRnk
df_tmp = df_portfolio_features[df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])]
df_tmp = df_tmp[(df_tmp['CumlRnk'] < 100)].sort_values(by = 'Spread%', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
22,DABUR,-1.45,-7.34,55.08,43.70,126610.0,-18202.0,229866.0,735.00,-15.96,35.0,X-MC,1.03,70.0,-0.14,1.68,6.61,XY24,BTT,FMCG
78,UNITDSPR,-1.70,1.61,18.85,20.77,44846.0,3766.0,237910.0,1644.00,-9.86,51.0,X-MC,1.50,64.0,0.08,1.74,8.42,X40N,NTT,BREWERIES
37,ICICIGI,-0.08,-0.01,19.35,19.34,38719.0,-13.0,200096.0,2252.93,-15.91,47.0,X-MC,1.66,66.0,-0.00,1.47,14.12,X40,ATH,INSURANCE
75,TMPV,-2.56,-23.44,78.39,36.58,213569.0,-83397.0,272444.0,600.00,-83.62,36.0,X-LC,1.86,4.0,-0.39,1.99,1.31,XY24,NTT,AUTO
59,RELIANCE,-0.76,-10.25,39.62,25.30,71457.0,-20608.0,180355.0,1952.00,-12.73,46.0,X-LC,2.45,21.0,-0.29,1.32,20.42,XY25,BTT,REFINERIES

In [19]:
# top 5 to accumulate based on lowest Gained%
df_tmp = df_portfolio_features[df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])].sort_values(by = 'Gained%', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
10,BAJAJHLDNG,-0.56,-8.52,41.25,29.22,71745.0,-16198.0,173927.0,14451.52,-15.20,31.0,X-LC,11.98,28.0,-0.23,1.27,0.00,X40,ATH,FINANCE
13,BERGEPAINT,-0.82,-20.19,57.01,25.32,117282.0,-52027.0,205722.0,680.00,-24.54,29.0,X-MC,15.47,68.0,-0.44,1.51,0.00,XY24,NTT,PAINTS
58,RELAXO,-0.78,-60.43,284.88,52.31,163644.0,-87717.0,57443.0,1176.00,-57.89,19.0,X-SC,18.73,92.0,-0.54,0.42,0.00,X40N,NTT,FOOTWEAR
73,TCS,-0.57,-26.22,71.56,26.57,244579.0,-121491.0,341782.0,4311.59,-37.40,24.0,X-LC,13.09,2.0,-0.50,2.50,0.00,X40,ATH,IT
12,BATAINDIA,0.31,-53.61,191.46,35.20,114281.0,-68981.0,59689.0,2096.00,-21.73,22.0,X-SC,25.48,91.0,-0.60,0.44,0.31,X40,NTT,FOOTWEAR

In [20]:
# top 5 to accumulate based on lowest CurrAlloc%
df_tmp = df_portfolio_features[df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])].sort_values(by = 'CurrAlloc%', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
58,RELAXO,-0.78,-60.43,284.88,52.31,163644.0,-87717.0,57443.0,1176.00,-57.89,19.0,X-SC,18.73,92.0,-0.54,0.42,0.00,X40N,NTT,FOOTWEAR
12,BATAINDIA,0.31,-53.61,191.46,35.20,114281.0,-68981.0,59689.0,2096.00,-21.73,22.0,X-SC,25.48,91.0,-0.60,0.44,0.31,X40,NTT,FOOTWEAR
54,QUESS,1.92,-20.84,119.69,73.90,101179.0,-22259.0,84534.0,424.00,-57.58,44.0,X-SC,17.93,80.0,-0.22,0.62,4.28,XY24,NTT,MISC
36,HONAUT,-0.26,-20.44,90.18,51.31,138359.0,-39413.0,153425.0,58357.33,-33.85,43.0,X-SC,13.63,90.0,-0.28,1.12,3.32,X40N,ATH,ELECTRICAL
2,ABBOTINDIA,0.07,-9.99,31.18,18.07,50194.0,-17875.0,160980.0,35195.00,-23.42,47.0,X-MC,11.17,58.0,-0.36,1.18,2.05,X40,ATH,PHARMA

In [21]:
# top 5 to accumulate based on CumlRnk
df_tmp = df_portfolio_features.sort_values(by = 'CumlRnk', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
45,ITC,0.02,-18.58,46.23,19.06,128036.0,-63212.0,276954.0,452.00,-55.52,38.0,X-LC,17.09,1.0,-0.49,2.03,1.01,X40,NTT,FMCG
73,TCS,-0.57,-26.22,71.56,26.57,244579.0,-121491.0,341782.0,4311.59,-37.40,24.0,X-LC,13.09,2.0,-0.50,2.50,0.00,X40,ATH,IT
43,INFY,-1.19,-12.85,54.04,34.24,147358.0,-40205.0,272683.0,1972.00,-31.42,27.0,X-LC,12.11,3.0,-0.27,2.00,0.37,X40,NTT,IT
75,TMPV,-2.56,-23.44,78.39,36.58,213569.0,-83397.0,272444.0,600.00,-83.62,36.0,X-LC,1.86,4.0,-0.39,1.99,1.31,XY24,NTT,AUTO
34,HCLTECH,-0.51,-12.09,40.87,23.83,86919.0,-29252.0,212672.0,1908.19,-7.78,28.0,X-LC,9.48,8.0,-0.34,1.56,2.04,X40,ATH,IT

In [22]:
# top 5 for average up
df_tmp = df_portfolio_features[(df_portfolio_features['Dev%_200'] > 5)].sort_values(by = 'CurrAlloc%', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
42,INDUSINDBK,-1.81,-34.85,103.99,32.89,52304.0,-26910.0,50297.0,1800.00,-336.69,39.0,L-MC,11.31,258.0,-0.51,0.37,38.51,XR,NTT,BANKS
67,SONACOMS,1.39,-10.24,54.96,39.09,49903.0,-10360.0,90799.0,804.02,-28.84,51.0,M-MC,10.15,193.0,-0.21,0.66,28.45,AR,ATH,AUTO
27,FINCABLES,-3.80,13.19,83.68,107.91,139848.0,19478.0,167122.0,1641.55,1.98,56.0,M-SC,7.69,220.0,0.14,1.22,25.73,OX40N,ATH,CABLES
19,COALINDIA,1.27,10.46,6.52,17.67,10837.0,15744.0,166204.0,478.51,33.43,62.0,L-LC,11.55,185.0,1.45,1.22,29.07,XY25,ATH,MINING
82,VOLTAS,1.46,15.00,26.26,45.20,57903.0,28758.0,220500.0,1856.00,31.71,49.0,X-MC,9.63,79.0,0.50,1.61,22.82,XY25,NTT,AC

In [23]:
# top 5 RSP
df_tmp = df_portfolio_features.sort_values(by = 'RSP', ascending=False)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
11,BANDHANBNK,0.98,-11.46,117.33,92.42,289367.0,-31932.0,246627.0,400.00,111.21,63.0,H-SC,10.06,174.0,-0.11,1.81,35.86,XY24,NTT,BANKS
27,FINCABLES,-3.80,13.19,83.68,107.91,139848.0,19478.0,167122.0,1641.55,1.98,56.0,M-SC,7.69,220.0,0.14,1.22,25.73,OX40N,ATH,CABLES
1,ABB,1.09,15.45,26.09,45.57,78802.0,40421.0,302040.0,7934.00,-25.80,66.0,H-MC,10.07,125.0,0.51,2.21,34.13,AR,NTT,ELECTRICAL
31,HAPPSTMNDS,5.52,-47.25,250.42,84.85,169304.0,-60557.0,67608.0,1480.71,-37.33,65.0,H-SC,28.55,152.0,-0.36,0.50,25.20,AR,ATH,IT
19,COALINDIA,1.27,10.46,6.52,17.67,10837.0,15744.0,166204.0,478.51,33.43,62.0,L-LC,11.55,185.0,1.45,1.22,29.07,XY25,ATH,MINING

In [24]:
# Top N allocation
df_tmp = df_portfolio_features.sort_values(by = 'CurrAlloc%', ascending=False)
top_n_values = [10, 25, 50]

sum_df = pd.DataFrame({
    'Top_N': top_n_values,
    'Sum_Alloc%': [df_tmp['CurrAlloc%'].head(n).sum() for n in top_n_values]
})

sum_df

   Top_N  Sum_Alloc%
0     10       20.48
1     25       45.29
2     50       77.73

In [25]:
# market-cap-wise allocation
df_tmp = df_portfolio_features[cols]
df_tmp.groupby(df_tmp['Conviction'].str[-2:])['CurrAlloc%'].sum().sort_values(ascending=False)

Conviction
SC    44.70
MC    30.41
LC    24.86
Name: CurrAlloc%, dtype: float64

In [26]:
# criteria-wise allocation
df_portfolio_features.groupby('Criteria')['CurrAlloc%'].sum().sort_values(ascending=False)

Criteria
XY24     27.29
X40      23.75
X40N     15.16
AR        9.21
XY25      8.59
XR        8.30
OX40N     6.90
SR        0.77
Name: CurrAlloc%, dtype: float64

In [27]:
# conviction-wise allocation
df_portfolio_features.groupby('Conviction')['CurrAlloc%'].sum().sort_values(ascending=False)

Conviction
X-MC    23.04
H-SC    21.74
X-LC    21.41
X-SC    12.17
M-SC    10.20
H-MC     4.99
M-MC     2.01
L-LC     1.22
H-LC     1.20
M-LC     1.03
L-SC     0.59
L-MC     0.37
Name: CurrAlloc%, dtype: float64

In [28]:
# sector-wise stats
df_tmp = df_portfolio_features.groupby('Category')[['CurrAlloc%', 'Current', 'Current P/L', 'FTT Amt']].sum().sort_values(by=['Current', 'Current P/L'], ascending=False)
df_tmp['Current P/L%'] = round(df_tmp['Current P/L'] * 100 / df_tmp['Current'], 2)
df_tmp['FTT%'] = round(df_tmp['FTT Amt'] * 100 / df_tmp['Current'], 2)
cols = ['CurrAlloc%', 'Current P/L%', 'FTT%']
df_tmp[cols].sort_values(by=['CurrAlloc%'], ascending=False)

               CurrAlloc%  Current P/L%    FTT%
Category
FMCG                15.23        -20.01   62.63
FINANCE             12.76        -23.18   73.37
IT                  11.80        -39.96  111.19
MISC                 6.99        -40.65  101.75
ELECTRICAL           6.63         -6.82   47.73
PAINTS               5.17        -39.61   63.85
INSURANCE            4.71         -5.36   41.41
PHARMA               4.14         -3.85   36.54
AUTO                 3.73        -28.23   79.11
BANKS                3.18        -23.42   98.21
AC                   2.15         -8.47   37.89
HEALTHCARE           1.98        -32.43   66.98
DURABLES             1.91        -48.23   84.29
FOOTWEAR             1.85        -74.68  144.72
TRAVEL               1.81        -80.52  170.91
BREWERIES            1.74          1.58   18.85
APPARELS             1.62        -21.14   62.46
REALTY               1.45        -11.73   30.09
CERAMICS             1.35        -67.04  117.79
REFINERIES           1.32        -11.43   39.62
CEMENT               1.29        -52.33  166.29
CABLES               1.22         11.65   83.68
MINING               1.22          9.47    6.52
JEWELLERY            1.12       -108.53  180.98
ENGINEERING          1.10        -60.83  134.39
CHEMICALS            0.95       -102.98  268.58
ENTERTAINMENT        0.76        -86.54  197.79
TEXTILES             0.42        -60.99  106.90
HOTELS               0.37       -126.24  206.04

In [29]:
# money to be made criteria-wise
df_portfolio_features.groupby('Criteria')['FTT Amt'].agg(['sum', 'count']).sort_values(by='sum', ascending=False)

                sum  count
Criteria
XY24      3869875.0     21
X40       1628488.0     15
XR        1358499.0     12
AR        1313225.0     10
X40N      1229180.0     10
OX40N      847681.0     10
XY25       443692.0      6
SR         314040.0      2

In [30]:
# money to be made conviction-wise
df_portfolio_features.groupby('Conviction')['FTT Amt'].agg(['sum', 'count']).sort_values(by='sum', ascending=False)

                  sum  count
Conviction
H-SC        3824690.0     24
X-MC        1584940.0     15
X-LC        1548594.0     12
M-SC        1524581.0     14
X-SC        1520661.0     10
H-MC         396323.0      3
L-SC         210334.0      2
M-LC         151107.0      1
M-MC         110890.0      2
H-LC          69419.0      1
L-MC          52304.0      1
L-LC          10837.0      1

In [31]:
# money to be made criteria and conviction-wise
df_portfolio_features.groupby(['Conviction', 'Criteria'])['FTT Amt'].agg(['sum', 'count']).sort_values(by='sum', ascending=False)

                           sum  count
Conviction Criteria
H-SC       XY24      1306247.0      6
           AR         958663.0      5
M-SC       XY24       900669.0      6
H-SC       XR         863521.0      7
X-SC       XY24       820979.0      4
X-LC       X40        803084.0      6
X-MC       X40        621957.0      7
X-SC       X40N       496235.0      4
X-MC       X40N       494917.0      4
H-SC       OX40N      382219.0      4
X-LC       XY24       359788.0      2
M-SC       OX40N      358537.0      5
H-SC       SR         314040.0      2
X-MC       XY24       243892.0      2
H-MC       XY24       238300.0      1
X-LC       X40N       238028.0      2
X-MC       XY25       224174.0      2
X-SC       X40        203447.0      2
M-SC       XR         188158.0      2
H-MC       AR         158023.0      2
M-LC       XR         151107.0      1
X-LC       XY25       147694.0      2
L-SC       OX40N      106925.0      1
           XR         103409.0      1
M-SC       AR          77217.0      1
H-LC       AR          69419.0      1
M-MC       XY25        60987.0      1
L-MC       XR          52304.0      1
M-MC       AR          49903.0      1
L-LC       XY25        10837.0      1

In [32]:
# notebook execution time

end_time = time.time()
execution_time = round(end_time - start_time, 0)
print(f"Notebook execution time: {execution_time} seconds")

Notebook execution time: 34.0 seconds