<a href="https://colab.research.google.com/github/ankit-rathi/Quantvesting_v2/blob/main/myStocks_Portfolio_Analysis.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
'''
!pip install pandas==2.2.2 -qq
!pip install pyxirr -qq
!pip install ta -qq
!pip install yfinance==0.2.59 -qq
'''

'\n!pip install pandas==2.2.2 -qq\n!pip install pyxirr -qq\n!pip install ta -qq\n!pip install yfinance==0.2.59 -qq\n'

In [2]:
# import libraries

import numpy as np
import pandas as pd
import datetime
import warnings
warnings.filterwarnings('ignore')
import yfinance as yfin
import ta
import matplotlib.pyplot as plt
import requests

In [3]:
# notebook start time
import time
import datetime
import pytz

start_time = time.time()

# function to print date timestamp
def print_date_time():
  tz_NY = pytz.timezone('Asia/Kolkata')
  datetime_NY = datetime.datetime.now(tz_NY)
  print("Run date time (IST):", datetime_NY.strftime("%Y-%m-%d %H:%M:%S"))

In [4]:
# function to get booked and reserved amount
def get_amt():
  # fetch the JSON data from the URL
  url = "https://raw.githubusercontent.com/ankit-rathi/Tradevesting_v1/main/data/myPortfolioAmts.json"
  response = requests.get(url)
  pf_amts = response.json()  # parse the JSON data

  # extract values from the JSON
  py_booked_amt_dm = pf_amts["py_booked_amt_dm"]
  py_booked_amt_sv = pf_amts["py_booked_amt_sv"]
  cy_booked_amt_dm = pf_amts["cy_booked_amt_dm"]
  cy_booked_amt_sv = pf_amts["cy_booked_amt_sv"]
  reserve_amt_dm = pf_amts["reserve_amt_dm"]
  reserve_amt_sv = pf_amts["reserve_amt_sv"]

  # perform calculations
  py_booked_amt = py_booked_amt_dm + py_booked_amt_sv
  cy_booked_amt = cy_booked_amt_dm + cy_booked_amt_sv
  reserve_amt = reserve_amt_dm + reserve_amt_sv
  total_booked_amt = py_booked_amt + cy_booked_amt

  return total_booked_amt, reserve_amt, cy_booked_amt, py_booked_amt

gen_output = 0

In [5]:
# function to format the amount
def format_amt(number):
    abs_number = abs(number)

    if abs_number >= 1_00_00_000:  # Crores
        formatted_amt = f"{number / 1_00_00_000:.2f} C"
    elif abs_number >= 1_00_000:  # Lakhs
        formatted_amt = f"{number / 1_00_000:.2f} L"
    elif abs_number >= 1_000:  # Thousands
        formatted_amt = f"{number / 1_000:.2f} K"
    else:
        formatted_amt = f"{number:.2f}"

    return formatted_amt

# function to set start and end date
def get_start_end_date():
  start_date = (datetime.date.today() + datetime.timedelta(days=-365)).strftime('%Y-%m-%d')
  end_date = (datetime.date.today() + datetime.timedelta(days=1)).strftime('%Y-%m-%d')
  return start_date, end_date

# function to fetch my portfolio csv
def get_mypfs_df():
  mypfs_df = pd.read_csv('https://raw.githubusercontent.com/ankit-rathi/Tradevesting_v1/main/data/myPortfolioStocks.csv')
  return mypfs_df

# function to fetch my prospects csv
def get_mypps_df():
  mypps_df = pd.read_csv('https://raw.githubusercontent.com/ankit-rathi/Tradevesting_v1/main/data/myProspectsScrips.csv')
  return mypps_df

# function to fetch screener data
def get_myscreen_df():
  myscreen_df = pd.read_csv('https://raw.githubusercontent.com/ankit-rathi/Tradevesting_v1/main/data/myScreenerDB.csv')
  return myscreen_df

# function to fetch momentum data
def get_myinvmt_df():
  myinvmt_df = pd.read_csv('https://raw.githubusercontent.com/ankit-rathi/Tradevesting_v1/main/data/myInvestments.csv')
  return myinvmt_df

# function to get the stock ids
def get_stock_ids(df_pf):
  stock_n100 = df_pf['Symbol'].unique()

  exclude = ['CADILAHC','MMTC', 'MASFIN']

  stock_ids = df_pf[~df_pf['Symbol'].isin(exclude) ]['Symbol'].unique()

  #mypf = mypf[mypf.Forecast.notnull()]
  #stock_ids = mypf['Symbol'].unique()

  #stock_ids.sort()
  return stock_ids

# get features from screener data
def get_screener_features():
  myscreen_df = get_myscreen_df()
  cols = ['Symbol', 'EPS', 'MedPE', 'ROCE%', 'ROE%', 'CapType']
  return myscreen_df[cols]

# get relative strength
def get_relative_strength(stock_list):

    # Dictionary to store stock tickers and their corresponding percentage price change
    stock_changes = {}

    # Loop through each stock and fetch its price data
    for stock in stock_list:
        try:
            # Download the stock data for the given date range
            stock_data = yfin.Ticker(stock + '.NS').history(period='1mo', interval='1d')[map(str.title, ['open', 'close', 'low', 'high', 'volume'])]

            # Calculate the percentage change for the stock
            if len(stock_data) > 0:
                start_price = stock_data['Close'].iloc[0]
                end_price = stock_data['Close'].iloc[-1]
                percent_change = round(((end_price - start_price) / start_price) * 100, 2)
                stock_changes[stock] = percent_change
            else:
                stock_changes[stock] = np.nan  # If no data is available, set to NaN

        except Exception as e:
            print(f"Error fetching data for {stock}: {e}")
            stock_changes[stock] = np.nan

    # Create a DataFrame with stock tickers and their percentage changes
    df = pd.DataFrame(list(stock_changes.items()), columns=['Symbol', 'Percent_Change'])

    # Drop any stocks with missing data (NaN values)
    df = df.dropna()

    # Calculate the percentile rank based on percentage change
    df['RSP'] = round(df['Percent_Change'].rank(pct=True) * 100, 2)
    cols = ['Symbol', 'RSP']
    df = df[cols]
    # Sort by percentile rank (optional)
    df = df.sort_values(by='RSP', ascending=False).reset_index(drop=True)

    return df

In [6]:
# function to get stock technicals
def stock_prec_dev(stock_symbol):
    #stock_symbol = 'ULTRACEMCO.NS'
    short_window = 20
    mid_window = 50
    long_window = 200
    moving_avg = 'SMA'

    start = datetime.datetime(*map(int, start_date.split('-')))
    end = datetime.datetime(*map(int, end_date.split('-')))

    stock_df = yfin.Ticker(stock_symbol + '.NS').history(period='max', interval='1d')[map(str.title, ['open', 'close', 'low', 'high', 'volume'])]

    stock_df['Max'] = round(max(stock_df['Close']),2)
    stock_df = stock_df[(stock_df.index <= end_date) & (stock_df.index >= start_date)]
    stock_df['200_SMA'] = round(stock_df['Close'].rolling(window = 200, min_periods = 1).mean(),0)
    stock_df['Dev%_200'] = round((stock_df['Close'] - stock_df['200_SMA'])*100/stock_df['200_SMA'],2)
    stock_df.dropna(axis = 0, inplace = True) # remove any null rows

    stock_df['20_SMA'] = stock_df['Close'].rolling(window=20).mean()
    stock_df['50_SMA'] = stock_df['Close'].rolling(window=50).mean()
    stock_df['Symbol'] = stock_symbol

    stock_df['Close'] = round(stock_df['Close'],2)
    stock_df['Min'] = round(min(stock_df['Close']),2)
    stock_df['RSI_14'] = ta.momentum.RSIIndicator(close=stock_df['Close'], window=14).rsi()
    stock_df['RSI_14'] = round(stock_df['RSI_14'],0)
    stock_df['Prev_Close'] = stock_df['Close'].shift(1)
    stock_df.drop(['Open', 'Low', 'High', 'Volume'], axis=1, inplace=True)
    stock_df = stock_df.tail(1)

    max_SMA = max(stock_df['20_SMA'].item(), stock_df['50_SMA'].item(), stock_df['200_SMA'].item())
    min_SMA = min(stock_df['20_SMA'].item(), stock_df['50_SMA'].item(), stock_df['200_SMA'].item())
    ABS_Spread = max_SMA - min_SMA
    stock_df['Spread%'] = round((ABS_Spread / stock_df['200_SMA'].item()) * 100,2)

    return stock_df

# function to compute stock attributes
def get_common_features(stock_ids, df_mypf):

  df_prec_dev = pd.DataFrame()
  df_tmp = get_screener_features()
  df_rs = get_relative_strength(stock_ids)

  for stock_id in stock_ids:
      tmp = stock_prec_dev(stock_id)
      tmp = tmp.reset_index()
      df_prec_dev = pd.concat([df_prec_dev, tmp], ignore_index = True)
  df_prec_dev = pd.merge(df_prec_dev, df_mypf, on= 'Symbol')
  df_prec_dev = pd.merge(df_prec_dev, df_tmp, on= 'Symbol', how='left')
  df_prec_dev = pd.merge(df_prec_dev, df_rs, on= 'Symbol', how='left')
  #print(df_prec_dev.columns)
  df_prec_dev['Curr_PE'] = round(df_prec_dev['Close']/df_prec_dev['EPS'],1)
  df_prec_dev['Dev%_PE'] = round((df_prec_dev['Curr_PE'] - df_prec_dev['MedPE'])*100/df_prec_dev['MedPE'],2)
  df_prec_dev['Conviction'] = df_prec_dev['Conviction'] + '-' + df_prec_dev['CapType']
  return df_prec_dev

# function to arrange stock features
def arrange_features(df_stocks, common_cols, diff_cols):
  df_stocks_common = df_stocks[common_cols].drop_duplicates()
  df_stocks_diff = df_stocks[diff_cols]
  df_stocks_diff['Investment'] = df_stocks_diff['AvgCost'] * df_stocks_diff['Shares']
  df_stocks_diff = df_stocks_diff.groupby(['Symbol'])[['Shares', 'Investment']].aggregate(['sum']).reset_index()
  df_stocks_diff.columns = ['Symbol', 'Shares', 'Investment']
  df_stocks_diff['AvgCost'] = round(df_stocks_diff['Investment']/df_stocks_diff['Shares'],2)
  df_stocks = pd.merge(df_stocks_diff, df_stocks_common, on='Symbol')
  return df_stocks

# plot fact distribution across dimension
def plot_pie_chart(df, dimension, fact):
  # grouping the data by category and calculating the sum of fact for each type
  grouped_data = df.groupby(dimension)[fact].sum()

  # sorting the grouped data in descending order
  grouped_data = grouped_data.sort_values(ascending=False)

  # creating a pie chart
  grouped_data.plot.pie(autopct='%1.1f%%', startangle=90, figsize=(6, 6))

  # adding a title and displaying the plot
  plt.title(f'{dimension} {fact} Distribution')
  plt.ylabel('')  # To hide the y-label
  plt.show()

In [7]:
# function to get portfolio features

def get_portfolio_features(df_common_features):

  print_date_time()
  print('-------------------')

  #df_common_features["Target"] = df_common_features["Target"].fillna(df_common_features["Max"])
  df_common_features['NTT'] = np.where(df_common_features['Strategy']== 'NTT', df_common_features["Target"], df_common_features['Max'])
  df_common_features['LTT'] = np.where(df_common_features['Strategy']== 'BTT', df_common_features["Target"], df_common_features['Max'])
  df_common_features['BOL'] = df_common_features['Min']

  tmp_df = df_common_features[df_common_features['Symbol'].isin(mypf_df[mypf_df['InPortfolio'] != 'NA'].Symbol.values)]
  print('qualified stocks: '+str(len(tmp_df['Symbol'].unique())))
  tmp_df1 = tmp_df[tmp_df['LatestQtr'] == 1]
  print('with latest results: '+str(len(tmp_df1['Symbol'].unique())))
  tmp_df1 = tmp_df1[tmp_df1['StarStock'] == 1]
  print('still star stocks: '+str(len(tmp_df1['Symbol'].unique())))
  tmp_df['Investment'] = tmp_df['AvgCost'] * tmp_df['Shares']
  tmp_df['Current'] = round(tmp_df['Close'] * tmp_df['Shares'],0)
  tmp_df['Previous'] = tmp_df['Prev_Close'] * tmp_df['Shares']
  tmp_df['EstimatedST'] = tmp_df['NTT'] * tmp_df['Shares']
  tmp_df['EstimatedLT'] = tmp_df['LTT'] * tmp_df['Shares']
  tmp_df['Current P/L'] = round((tmp_df['Current'] - tmp_df['Investment']),0)
  tmp_df['Today P/L%'] = round((tmp_df['Current'] - tmp_df['Previous'])*100/tmp_df['Previous'],2)
  tmp_df['Current P/L%'] = round((tmp_df['Current'] - tmp_df['Investment'])*100/tmp_df['Investment'],2)
  tmp_df['EstimatedST P/L%'] = round((tmp_df['EstimatedST'] - tmp_df['Investment'])*100/tmp_df['Investment'],2)
  tmp_df['EstimatedLT P/L%'] = round((tmp_df['EstimatedLT'] - tmp_df['Investment'])*100/tmp_df['Investment'],2)
  tmp_df['NTT%'] = round((tmp_df['NTT'] - tmp_df['Close'])*100/tmp_df['Close'],2)
  tmp_df['LTT%'] = round((tmp_df['LTT'] - tmp_df['Close'])*100/tmp_df['Close'],2)
  tmp_df['Gained%'] = round((tmp_df['Close'] - tmp_df['BOL'])*100/tmp_df['BOL'],2)
  investment = round(sum(tmp_df['AvgCost']*tmp_df['Shares']),0)
  current = round(sum(tmp_df['Close']*tmp_df['Shares']),0)
  tmp_df['InitAlloc%'] = round(tmp_df['Investment']*100/investment,2)
  tmp_df['CurrAlloc%'] = round(tmp_df['Current']*100/current,2)
  tmp_df['FTT'] = tmp_df['LTT']
  tmp_df.loc[tmp_df['Strategy'] == 'NTT', 'FTT'] = tmp_df['NTT']
  tmp_df['FTT%'] = tmp_df['LTT%']
  tmp_df.loc[tmp_df['Strategy'] == 'NTT', 'FTT%'] = tmp_df['NTT%']
  tmp_df['FTT Amt'] = round(tmp_df['FTT%'] * tmp_df['Current']/100,0)
  tmp_df['OTT%'] = round((tmp_df['FTT'] - tmp_df['AvgCost'])*100/tmp_df['AvgCost'],2)
  tmp_df['RRR Ind'] = round(tmp_df['Current P/L']/tmp_df['FTT Amt'],2)
  tmp_df['Risk Ind'] = round(tmp_df['Current P/L%']*tmp_df['CurrAlloc%'],0)

  return tmp_df

# function to print portfolio features
def print_portfolio_stats(df_portfolio_features, myinvmt_df):
  from pyxirr import xirr

  total_booked_amt, reserve_amt, cy_booked_amt, py_booked_amt = get_amt()

  dates = myinvmt_df['Date'].values
  dates = np.append(dates, datetime.date.today().strftime('%d-%b-%y'))
  investment = myinvmt_df['Investment'].values
  dates= pd.to_datetime(dates)

  current = round(sum(df_portfolio_features['Close']*df_portfolio_features['Shares']),0) + reserve_amt
  investment_xirr = np.append(investment, current)
  cagr = round(xirr(pd.DataFrame({"dates": dates, "amounts": investment_xirr}))*100,2)

  investment = -sum(investment)
  invested = round(sum(df_portfolio_features['AvgCost']*df_portfolio_features['Shares']),0) + reserve_amt
  previous = round(sum(df_portfolio_features['Prev_Close']*df_portfolio_features['Shares']),0) + reserve_amt
  cy_invested = investment + py_booked_amt

  today_pnl_amount = current-previous
  today_pnl_percentage = round((current-previous)*100/previous,2)

  curr_pnl_amount = current-invested
  curr_pnl_percentage = round((curr_pnl_amount)*100/(cy_invested),2)

  cy_pnl_amount = cy_booked_amt + curr_pnl_amount
  cy_pnl_percentage = round((cy_pnl_amount)*100/cy_invested,2)

  overall_pnl_amount = total_booked_amt + curr_pnl_amount
  overall_pnl_percentage = round((overall_pnl_amount)*100/investment,2)

  estimate_st = round(sum(df_portfolio_features['FTT']*df_portfolio_features['Shares']),0)  + reserve_amt
  est_st_pnl_amount = estimate_st-current
  est_st_pnl_percentage = round((est_st_pnl_amount)*100/current,2)

  estimate_lt = round(sum(df_portfolio_features['LTT']*df_portfolio_features['Shares']),0)  + reserve_amt
  est_lt_pnl_amount = estimate_lt-current
  est_lt_pnl_percentage = round((est_lt_pnl_amount)*100/current,2)

  total_profit = round(sum(df_portfolio_features[df_portfolio_features['Current P/L%'] > 0]['Current']) - sum(df_portfolio_features[df_portfolio_features['Current P/L%'] > 0]['Investment']),0)
  total_loss = round(sum(df_portfolio_features[df_portfolio_features['Current P/L%'] < 0]['Current']) - sum(df_portfolio_features[df_portfolio_features['Current P/L%'] < 0]['Investment']),0)

  cy_booked_percentage = round((cy_booked_amt)*100/current,2)
  py_booked_percentage = round((py_booked_amt)*100/investment,2)
  total_booked_percentage = round((total_booked_amt)*100/investment,2)

  print('-------------------')
  print('Initial Investment: ', format_amt(investment))
  print('CY Investment: ', format_amt(cy_invested))
  print('Reserve: ', format_amt(reserve_amt))
  print('Current: ',  format_amt(current))
  print('-------------------')
  print('Today PnL: '+ '{} ({}%)'.format(format_amt(today_pnl_amount), today_pnl_percentage))
  print('Current PnL: '+ '{} ({}%)'.format(format_amt(curr_pnl_amount), curr_pnl_percentage))
  print('CY Booked + Current PnL: '+ '{} ({}%)'.format(format_amt(cy_pnl_amount), cy_pnl_percentage))
  print('-------------------')
  print('Total profit: ', format_amt(total_profit))
  print('Total loss: ', format_amt(total_loss))
  print('-------------------')
  print('Total Booked + Current PnL: '+ '{} ({}%)'.format(format_amt(overall_pnl_amount), overall_pnl_percentage))
  print('Total Booked PnL: '+ '{} ({}%)'.format(format_amt(total_booked_amt), total_booked_percentage))
  print('Curr Year Booked PnL: '+ '{} ({}%)'.format(format_amt(cy_booked_amt), cy_booked_percentage))
  print('Prev Year Booked PnL: '+ '{} ({}%)'.format(format_amt(py_booked_amt), py_booked_percentage))
  print('===================')
  print('Est FTT: ',  format_amt(estimate_st))
  print('Est FTT PnL: '+ '{} ({}%)'.format(format_amt(est_st_pnl_amount), est_st_pnl_percentage))

  print('===================')
  print('Deployed: ', format_amt(investment))

  print('Current: ', format_amt(current))

  print('CAGR/XIRR %: '+'{}%'.format(cagr))

In [8]:
# get start and end date
start_date, end_date = get_start_end_date()

# get portfolio and prospects data
mypfs_df = get_mypfs_df()
mypps_df = get_mypps_df()
myinvmt_df = get_myinvmt_df()

# merge above datasets
mypf_df = pd.merge(mypfs_df, mypps_df, on="Symbol")

# seggregate dm and sv portfolio
dm_pf = mypf_df[mypf_df['InPortfolio'] == 'DM']
sv_pf = mypf_df[mypf_df['InPortfolio'] == 'SV']

# build portfolio stock dataframe
dm_stocks = get_stock_ids(dm_pf)
sv_stocks = get_stock_ids(sv_pf)
df_stocks = pd.concat([dm_pf,sv_pf], ignore_index = True)

# arrange common and diff stock features
common_cols = ['Symbol', 'Target', 'Criteria', 'Strategy', 'CumlRnk', 'LatestQtr', 'StarStock', 'Conviction', 'Category', 'InFolio', 'XIRR', 'MBQ']
diff_cols = ['Symbol', 'AvgCost', 'Shares']
df_stocks = arrange_features(df_stocks, common_cols, diff_cols)

# get common features
stock_ids = df_stocks['Symbol'].values
df_common_features = get_common_features(stock_ids, df_stocks)

df_common_features.reset_index(drop=True, inplace=True)
df_common_features.drop(['Date'], axis=1, inplace=True)
# get and print portfolio features
df_portfolio_features = get_portfolio_features(df_common_features)

print_portfolio_stats(df_portfolio_features, myinvmt_df)

df = df_portfolio_features
#plot_pie_chart(df, 'CapType', 'Current')
list_ox40n = list(df[df['MBQ'].str.contains('OX40N', na=False)]['Symbol'].values)

Run date time (IST): 2026-07-29 10:51:17
-------------------
qualified stocks: 92
with latest results: 31
still star stocks: 20
-------------------
Initial Investment:  1.40 C
CY Investment:  1.82 C
Reserve:  1.49 K
Current:  1.53 C
-------------------
Today PnL: 47.41 K (0.31%)
Current PnL: -30.19 L (-16.55%)
CY Booked + Current PnL: -28.11 L (-15.41%)
-------------------
Total profit:  4.89 L
Total loss:  -35.08 L
-------------------
Total Booked + Current PnL: 14.76 L (10.58%)
Total Booked PnL: 44.95 L (32.22%)
Curr Year Booked PnL: 2.08 L (1.36%)
Prev Year Booked PnL: 42.87 L (30.73%)
===================
Est FTT:  2.55 C
Est FTT PnL: 1.02 C (66.56%)
===================
Deployed:  1.40 C
Current:  1.53 C
CAGR/XIRR %: 4.11%

In [9]:
# top 5 near their targets
cols = ['Symbol', 'Today P/L%', 'Current P/L%', 'FTT%', 'OTT%', 'FTT Amt', 'Current P/L', 'Current', 'FTT', 'Dev%_PE', 'RSI_14','Conviction', 'Spread%',  'CumlRnk', 'RRR Ind', 'CurrAlloc%', 'Gained%', 'Criteria', 'Strategy', 'Category']
df_tmp = df_portfolio_features[~df_portfolio_features['Symbol'].isin(['ENRIN','BLUSPRING','DIGITIDE'])]
df_tmp = df_tmp.sort_values(by = 'FTT Amt', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
59,PIDILITIND,0.12,14.92,2.26,17.52,3665.0,21050.0,162160.0,1658.32,-19.48,63.0,X-LC,8.27,5.0,5.74,1.06,28.24,X40,ATH,CHEMICALS
83,TTKPRESTIG,5.72,-9.94,11.14,0.09,10111.0,-10014.0,90763.0,770.00,110.67,70.0,M-SC,12.45,250.0,-0.99,0.59,61.62,OX40N,NTT,DURABLES
56,MEDANTA,-0.26,20.06,5.88,27.12,12461.0,35411.0,211928.0,1486.00,16.36,69.0,X-SC,12.42,87.0,2.84,1.39,46.03,XY24,NTT,HEALTHCARE
73,SONACOMS,-0.02,24.69,11.23,38.69,14165.0,24972.0,126131.0,801.69,-1.16,74.0,M-MC,27.37,193.0,1.76,0.82,78.95,AR,ATH,AUTO
68,SATIN,-0.26,44.54,5.05,51.83,20166.0,123047.0,399331.0,274.00,30.09,56.0,H-SC,45.30,159.0,6.10,2.61,94.53,XY24,NTT,FINANCE

In [10]:
# top 5 today
df_tmp = df_portfolio_features.sort_values(by = 'Today P/L%', ascending=False)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
83,TTKPRESTIG,5.72,-9.94,11.14,0.09,10111.0,-10014.0,90763.0,770.00,110.67,70.0,M-SC,12.45,250.0,-0.99,0.59,61.62,OX40N,NTT,DURABLES
45,INFY,4.12,-21.63,71.30,34.24,174832.0,-67682.0,245206.0,1972.00,-38.32,63.0,X-LC,19.13,3.0,-0.39,1.60,16.84,X40,NTT,IT
33,HCLTECH,3.94,-12.58,37.60,20.28,79516.0,-30445.0,211479.0,1853.42,-8.19,76.0,X-LC,16.09,8.0,-0.38,1.38,31.58,X40,ATH,IT
27,GLAXO,3.72,6.22,27.75,35.69,58741.0,12396.0,211680.0,3380.16,-18.88,72.0,X-MC,5.62,56.0,0.21,1.38,25.81,X40,ATH,PHARMA
36,HINDUNILVR,3.72,-18.39,39.28,13.67,82406.0,-47273.0,209790.0,2922.00,-39.37,45.0,X-LC,5.31,9.0,-0.57,1.37,3.72,XY25,NTT,FMCG

In [11]:
# bottom 5 today
df_tmp = df_portfolio_features.sort_values(by = 'Today P/L%', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
75,SURYODAY,-10.09,-5.45,30.13,23.03,51013.0,-9761.0,169310.0,216.00,84.21,41.0,H-SC,23.25,166.0,-0.19,1.11,43.71,XR,NTT,BANKS
62,RAJOOENG,-4.95,-49.76,177.86,39.61,91598.0,-51000.0,51500.0,143.10,-66.01,44.0,H-SC,19.14,136.0,-0.56,0.34,10.33,AR,ATH,MISC
87,VBL,-4.75,-10.63,51.47,35.37,145291.0,-33559.0,282283.0,670.16,-21.06,28.0,X-LC,6.50,13.0,-0.23,1.85,16.02,X40N,ATH,FMCG
23,DMART,-4.22,-7.26,39.75,29.60,92009.0,-18132.0,231468.0,5391.45,-21.83,33.0,X-LC,2.23,14.0,-0.20,1.51,5.80,X40N,ATH,FMCG
0,5PAISA,-4.16,-32.62,67.56,12.90,99463.0,-71274.0,147222.0,593.00,116.35,45.0,H-SC,14.02,170.0,-0.72,0.96,42.07,OX40N,NTT,FINANCE

In [12]:
# top 5 to exit based on CumlRnk
df_tmp = df_portfolio_features[~df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])]
df_tmp = df_tmp[(df_tmp['Current P/L%'] > -1) & (df_tmp['Current P/L%'] < 1)].sort_values(by = 'CumlRnk', ascending=False)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
63,RECLTD,0.47,0.22,20.48,20.74,41699.0,440.0,203610.0,446.0,11.33,63.0,M-MC,2.3,191.0,0.01,1.33,21.34,XY25,NTT,FINANCE

In [13]:
# OX40N stocks to exit
df_tmp = df_portfolio_features[(df_portfolio_features['Symbol'].isin(list_ox40n))].sort_values(by = 'Current P/L%', ascending=False)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
25,FINCABLES,1.21,24.74,66.67,107.91,122790.0,36532.0,184176.0,1641.55,12.13,39.0,M-SC,19.75,220.0,0.30,1.20,38.56,OX40N,ATH,CABLES
72,SIS,-1.01,-1.02,22.51,21.26,24740.0,-1127.0,109905.0,528.00,2623.32,50.0,H-SC,24.18,168.0,-0.05,0.72,63.41,OX40N,NTT,MISC
83,TTKPRESTIG,5.72,-9.94,11.14,0.09,10111.0,-10014.0,90763.0,770.00,110.67,70.0,M-SC,12.45,250.0,-0.99,0.59,61.62,OX40N,NTT,DURABLES
16,CERA,-0.28,-19.09,53.12,23.89,75603.0,-33579.0,142324.0,9475.00,-21.96,52.0,H-SC,14.10,153.0,-0.44,0.93,38.35,OX40N,NTT,CERAMICS
43,INDIGOPNTS,-0.16,-23.83,31.32,0.02,41641.0,-41606.0,132953.0,1408.00,102.57,57.0,M-SC,3.96,222.0,-1.00,0.87,50.84,OX40N,NTT,PAINTS

In [14]:
# top 5 to book for rotation
df_tmp = df_portfolio_features[(df_portfolio_features['Current P/L%'] > 20) ].sort_values(by = 'CumlRnk', ascending=False)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
25,FINCABLES,1.21,24.74,66.67,107.91,122790.0,36532.0,184176.0,1641.55,12.13,39.0,M-SC,19.75,220.0,0.30,1.20,38.56,OX40N,ATH,CABLES
73,SONACOMS,-0.02,24.69,11.23,38.69,14165.0,24972.0,126131.0,801.69,-1.16,74.0,M-MC,27.37,193.0,1.76,0.82,78.95,AR,ATH,AUTO
68,SATIN,-0.26,44.54,5.05,51.83,20166.0,123047.0,399331.0,274.00,30.09,56.0,H-SC,45.30,159.0,6.10,2.61,94.53,XY24,NTT,FINANCE
56,MEDANTA,-0.26,20.06,5.88,27.12,12461.0,35411.0,211928.0,1486.00,16.36,69.0,X-SC,12.42,87.0,2.84,1.39,46.03,XY24,NTT,HEALTHCARE
60,QUESS,3.06,25.01,39.11,73.90,52213.0,26709.0,133502.0,424.00,-32.78,71.0,X-SC,35.78,80.0,0.51,0.87,81.99,XY24,NTT,MISC

In [15]:
# top 5 to monitor for exit
df_tmp = df_portfolio_features[~df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])]
df_tmp = df_tmp[(df_tmp['Current P/L%'] > 0) ].sort_values(by = 'Dev%_PE', ascending=False)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
74,STARHEALTH,-0.24,14.30,28.84,47.26,92667.0,40191.0,321314.0,761.00,80.34,57.0,H-SC,18.57,173.0,0.43,2.10,38.93,XY24,NTT,INSURANCE
68,SATIN,-0.26,44.54,5.05,51.83,20166.0,123047.0,399331.0,274.00,30.09,56.0,H-SC,45.30,159.0,6.10,2.61,94.53,XY24,NTT,FINANCE
25,FINCABLES,1.21,24.74,66.67,107.91,122790.0,36532.0,184176.0,1641.55,12.13,39.0,M-SC,19.75,220.0,0.30,1.20,38.56,OX40N,ATH,CABLES
63,RECLTD,0.47,0.22,20.48,20.74,41699.0,440.0,203610.0,446.00,11.33,63.0,M-MC,2.30,191.0,0.01,1.33,21.34,XY25,NTT,FINANCE
91,ZYDUSLIFE,0.90,16.96,15.86,35.51,38875.0,35537.0,245111.0,1285.01,1.80,47.0,H-MC,16.92,120.0,0.91,1.60,28.99,AR,ATH,PHARMA

In [16]:
# top 5 to book for rotation from weak conviction
df_tmp = df_portfolio_features[~df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])]
df_tmp = df_tmp[~df_tmp['Criteria'].isin(['XY25','XY24','X40', 'X40N'])].sort_values(by = 'RRR Ind', ascending=False)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
73,SONACOMS,-0.02,24.69,11.23,38.69,14165.0,24972.0,126131.0,801.69,-1.16,74.0,M-MC,27.37,193.0,1.76,0.82,78.95,AR,ATH,AUTO
91,ZYDUSLIFE,0.90,16.96,15.86,35.51,38875.0,35537.0,245111.0,1285.01,1.80,47.0,H-MC,16.92,120.0,0.91,1.60,28.99,AR,ATH,PHARMA
25,FINCABLES,1.21,24.74,66.67,107.91,122790.0,36532.0,184176.0,1641.55,12.13,39.0,M-SC,19.75,220.0,0.30,1.20,38.56,OX40N,ATH,CABLES
72,SIS,-1.01,-1.02,22.51,21.26,24740.0,-1127.0,109905.0,528.00,2623.32,50.0,H-SC,24.18,168.0,-0.05,0.72,63.41,OX40N,NTT,MISC
55,MASFIN,-0.44,-2.97,25.29,21.57,24043.0,-2910.0,95070.0,397.04,-16.44,50.0,H-SC,1.85,167.0,-0.12,0.62,13.32,XR,ATH,FINANCE

In [17]:
# top 5 to accumulate based on lowest RSI_14
df_tmp = df_portfolio_features[df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])].sort_values(by = 'RSI_14', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
87,VBL,-4.75,-10.63,51.47,35.37,145291.0,-33559.0,282283.0,670.16,-21.06,28.0,X-LC,6.50,13.0,-0.23,1.85,16.02,X40N,ATH,FMCG
23,DMART,-4.22,-7.26,39.75,29.60,92009.0,-18132.0,231468.0,5391.45,-21.83,33.0,X-LC,2.23,14.0,-0.20,1.51,5.80,X40N,ATH,FMCG
34,HDFCBANK,1.54,-10.66,43.69,28.37,91678.0,-25048.0,209837.0,1073.00,-23.99,38.0,X-LC,10.37,26.0,-0.27,1.37,3.77,X40,BTT,BANKS
81,TMPV,0.83,-25.54,83.43,36.58,221049.0,-90890.0,264951.0,600.00,-84.72,39.0,X-LC,7.19,4.0,-0.41,1.73,11.35,XY24,NTT,AUTO
65,RELIANCE,-0.76,-18.46,53.66,25.30,87932.0,-37094.0,163869.0,1952.00,-20.42,40.0,X-LC,7.77,21.0,-0.42,1.07,0.91,XY25,BTT,REFINERIES

In [18]:
# top 5 to accumulate based on Spread and CumlRnk
df_tmp = df_portfolio_features[df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])]
df_tmp = df_tmp[(df_tmp['CumlRnk'] < 100)].sort_values(by = 'Spread%', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
11,BERGEPAINT,-0.52,-7.60,35.62,25.32,84834.0,-19584.0,238165.0,680.00,-12.57,49.0,X-MC,1.61,68.0,-0.23,1.56,23.96,XY24,NTT,PAINTS
19,COLPAL,-0.44,-19.23,73.16,39.86,155626.0,-50645.0,212720.0,3683.41,-2.26,60.0,X-MC,1.67,62.0,-0.33,1.39,20.33,XY25,ATH,FMCG
23,DMART,-4.22,-7.26,39.75,29.60,92009.0,-18132.0,231468.0,5391.45,-21.83,33.0,X-LC,2.23,14.0,-0.20,1.51,5.80,X40N,ATH,FMCG
1,ABBOTINDIA,0.58,-6.20,23.00,15.37,38585.0,-11095.0,167760.0,34390.26,-20.15,69.0,X-MC,2.36,58.0,-0.29,1.10,13.64,X40,ATH,PHARMA
8,BAJAJHLDNG,0.90,-2.48,30.87,27.63,57239.0,-4706.0,185419.0,14274.15,-9.98,61.0,X-LC,2.80,28.0,-0.08,1.21,26.26,X40,ATH,FINANCE

In [19]:
# top 5 to accumulate based on lowest Gained%
df_tmp = df_portfolio_features[df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])].sort_values(by = 'Gained%', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
65,RELIANCE,-0.76,-18.46,53.66,25.30,87932.0,-37094.0,163869.0,1952.00,-20.42,40.0,X-LC,7.77,21.0,-0.42,1.07,0.91,XY25,BTT,REFINERIES
35,HDFCLIFE,0.08,-8.54,45.10,32.71,61789.0,-12796.0,137004.0,811.41,-28.56,46.0,X-LC,15.78,31.0,-0.21,0.90,2.92,X40,ATH,INSURANCE
36,HINDUNILVR,3.72,-18.39,39.28,13.67,82406.0,-47273.0,209790.0,2922.00,-39.37,45.0,X-LC,5.31,9.0,-0.57,1.37,3.72,XY25,NTT,FMCG
34,HDFCBANK,1.54,-10.66,43.69,28.37,91678.0,-25048.0,209837.0,1073.00,-23.99,38.0,X-LC,10.37,26.0,-0.27,1.37,3.77,X40,BTT,BANKS
58,PGHH,0.80,-32.07,94.34,32.01,136831.0,-68480.0,145040.0,17616.87,-54.11,55.0,X-MC,19.35,57.0,-0.50,0.95,3.95,X40,ATH,FMCG

In [20]:
# top 5 to accumulate based on lowest CurrAlloc%
df_tmp = df_portfolio_features[df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])].sort_values(by = 'CurrAlloc%', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
10,BATAINDIA,0.31,-54.73,198.66,35.20,115717.0,-70421.0,58249.0,2096.00,-23.61,54.0,X-SC,16.91,91.0,-0.61,0.38,15.52,X40,NTT,FOOTWEAR
64,RELAXO,1.87,-47.04,187.60,52.31,144214.0,-68287.0,76873.0,1176.00,-43.66,56.0,X-SC,9.63,92.0,-0.47,0.50,71.88,X40N,NTT,FOOTWEAR
60,QUESS,3.06,25.01,39.11,73.90,52213.0,26709.0,133502.0,424.00,-32.78,71.0,X-SC,35.78,80.0,0.51,0.87,81.99,XY24,NTT,MISC
35,HDFCLIFE,0.08,-8.54,45.10,32.71,61789.0,-12796.0,137004.0,811.41,-28.56,46.0,X-LC,15.78,31.0,-0.21,0.90,2.92,X40,ATH,INSURANCE
28,GODREJCP,0.94,-3.01,35.55,31.47,51244.0,-4469.0,144145.0,1469.04,2.04,59.0,X-LC,5.90,32.0,-0.09,0.94,10.60,X40N,ATH,FMCG

In [21]:
# top 5 to accumulate based on CumlRnk
df_tmp = df_portfolio_features.sort_values(by = 'CumlRnk', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
47,ITC,0.67,-24.52,57.74,19.06,148247.0,-83417.0,256749.0,452.00,-58.75,55.0,X-LC,12.39,1.0,-0.56,1.68,3.99,X40,NTT,FMCG
79,TCS,2.15,-28.09,72.71,24.20,242230.0,-130127.0,333146.0,4230.71,-39.04,74.0,X-LC,16.99,2.0,-0.54,2.18,24.23,X40,ATH,IT
45,INFY,4.12,-21.63,71.30,34.24,174832.0,-67682.0,245206.0,1972.00,-38.32,63.0,X-LC,19.13,3.0,-0.39,1.60,16.84,X40,NTT,IT
81,TMPV,0.83,-25.54,83.43,36.58,221049.0,-90890.0,264951.0,600.00,-84.72,39.0,X-LC,7.19,4.0,-0.41,1.73,11.35,XY24,NTT,AUTO
59,PIDILITIND,0.12,14.92,2.26,17.52,3665.0,21050.0,162160.0,1658.32,-19.48,63.0,X-LC,8.27,5.0,5.74,1.06,28.24,X40,ATH,CHEMICALS

In [22]:
# top 5 for average up
df_tmp = df_portfolio_features[(df_portfolio_features['Dev%_200'] > 5)].sort_values(by = 'CurrAlloc%', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
44,INDUSINDBK,1.07,-25.98,79.53,32.89,45450.0,-20058.0,57148.0,1800.00,-368.91,53.0,L-MC,14.28,258.0,-0.44,0.37,40.89,XR,NTT,BANKS
64,RELAXO,1.87,-47.04,187.60,52.31,144214.0,-68287.0,76873.0,1176.00,-43.66,56.0,X-SC,9.63,92.0,-0.47,0.50,71.88,X40N,NTT,FOOTWEAR
3,ALKYLAMINE,-0.24,-22.61,148.79,92.54,116257.0,-22828.0,78135.0,4520.85,-17.07,50.0,H-SC,12.84,142.0,-0.20,0.51,48.37,SR,ATH,CHEMICALS
83,TTKPRESTIG,5.72,-9.94,11.14,0.09,10111.0,-10014.0,90763.0,770.00,110.67,70.0,M-SC,12.45,250.0,-0.99,0.59,61.62,OX40N,NTT,DURABLES
72,SIS,-1.01,-1.02,22.51,21.26,24740.0,-1127.0,109905.0,528.00,2623.32,50.0,H-SC,24.18,168.0,-0.05,0.72,63.41,OX40N,NTT,MISC

In [23]:
# top 5 RSP
df_tmp = df_portfolio_features.sort_values(by = 'RSP', ascending=False)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
33,HCLTECH,3.94,-12.58,37.60,20.28,79516.0,-30445.0,211479.0,1853.42,-8.19,76.0,X-LC,16.09,8.0,-0.38,1.38,31.58,X40,ATH,IT
60,QUESS,3.06,25.01,39.11,73.90,52213.0,26709.0,133502.0,424.00,-32.78,71.0,X-SC,35.78,80.0,0.51,0.87,81.99,XY24,NTT,MISC
22,DIXON,2.19,2.81,34.15,37.92,91566.0,7330.0,268128.0,18931.72,-56.30,63.0,X-MC,9.46,54.0,0.08,1.75,45.89,X40N,ATH,IT
79,TCS,2.15,-28.09,72.71,24.20,242230.0,-130127.0,333146.0,4230.71,-39.04,74.0,X-LC,16.99,2.0,-0.54,2.18,24.23,X40,ATH,IT
30,HAPPSTMNDS,1.67,-51.34,276.23,83.08,172279.0,-65797.0,62368.0,1466.54,-42.16,61.0,H-SC,11.96,152.0,-0.38,0.41,16.82,AR,ATH,IT

In [24]:
# Top N allocation
df_tmp = df_portfolio_features.sort_values(by = 'CurrAlloc%', ascending=False)
top_n_values = [10, 25, 50]

sum_df = pd.DataFrame({
    'Top_N': top_n_values,
    'Sum_Alloc%': [df_tmp['CurrAlloc%'].head(n).sum() for n in top_n_values]
})

sum_df

   Top_N  Sum_Alloc%
0     10       19.31
1     25       42.31
2     50       72.66

In [25]:
# market-cap-wise allocation
df_tmp = df_portfolio_features[cols]
df_tmp.groupby(df_tmp['Conviction'].str[-2:])['CurrAlloc%'].sum().sort_values(ascending=False)

Conviction
SC    43.21
LC    30.41
MC    26.36
Name: CurrAlloc%, dtype: float64

In [26]:
# criteria-wise allocation
df_portfolio_features.groupby('Criteria')['CurrAlloc%'].sum().sort_values(ascending=False)

Criteria
XY24     27.20
X40      25.30
X40N     17.34
XR        8.90
AR        6.98
OX40N     6.95
XY25      6.44
SR        0.87
Name: CurrAlloc%, dtype: float64

In [27]:
# conviction-wise allocation
df_portfolio_features.groupby('Conviction')['CurrAlloc%'].sum().sort_values(ascending=False)

Conviction
X-LC    28.38
H-SC    22.61
X-MC    21.19
X-SC    10.22
M-SC     9.84
H-MC     2.65
M-MC     2.15
H-LC     1.19
M-LC     0.84
L-SC     0.54
L-MC     0.37
Name: CurrAlloc%, dtype: float64

In [28]:
# sector-wise stats
df_tmp = df_portfolio_features.groupby('Category')[['CurrAlloc%', 'Current', 'Current P/L', 'FTT Amt']].sum().sort_values(by=['Current', 'Current P/L'], ascending=False)
df_tmp['Current P/L%'] = round(df_tmp['Current P/L'] * 100 / df_tmp['Current'], 2)
df_tmp['FTT%'] = round(df_tmp['FTT Amt'] * 100 / df_tmp['Current'], 2)
cols = ['CurrAlloc%', 'Current P/L%', 'FTT%']
df_tmp[cols].sort_values(by=['CurrAlloc%'], ascending=False)

               CurrAlloc%  Current P/L%    FTT%
Category
FMCG                14.12        -22.52   65.50
FINANCE             11.20         -7.54   54.14
IT                  10.73        -37.29  105.24
MISC                 7.34        -19.47   70.73
AUTO                 6.64         -7.67   47.82
PAINTS               5.44        -18.48   38.68
PHARMA               5.27          8.18   19.61
BANKS                5.27        -12.65   64.71
INSURANCE            5.25         -3.28   38.12
ELECTRICAL           4.13        -11.92   51.28
CHEMICALS            2.16        -22.66   95.06
HEALTHCARE           2.13        -10.21   38.97
APPARELS             1.83          4.09   28.12
AC                   1.76        -18.65   50.82
BREWERIES            1.71         10.68    7.87
FOOTWEAR             1.69        -70.12  138.33
DURABLES             1.65        -52.46   89.55
REALTY               1.55          6.75    8.57
TRAVEL               1.47        -98.30  197.59
CERAMICS             1.42        -41.64   84.66
ENGINEERING          1.24        -27.97   86.51
CABLES               1.20         19.84   66.67
JEWELLERY            1.14        -83.98  147.90
REFINERIES           1.07        -22.64   53.66
CEMENT               1.07        -63.69  186.15
ENTERTAINMENT        0.71        -77.87  183.96
TEXTILES             0.40        -49.82   92.54
HOTELS               0.39        -92.51  160.42

In [29]:
# money to be made criteria-wise
df_portfolio_features.groupby('Criteria')['FTT Amt'].agg(['sum', 'count']).sort_values(by='sum', ascending=False)

                sum  count
Criteria
XY24      3436239.0     21
X40       1794217.0     19
XR        1317245.0     13
AR        1107976.0      9
X40N      1063592.0     13
OX40N      727546.0     10
XY25       450408.0      5
SR         284758.0      2

In [30]:
# money to be made conviction-wise
df_portfolio_features.groupby('Conviction')['FTT Amt'].agg(['sum', 'count']).sort_values(by='sum', ascending=False)

                  sum  count
Conviction
H-SC        3316875.0     24
X-LC        1928136.0     21
X-MC        1470443.0     15
M-SC        1410267.0     14
X-SC        1238746.0      9
H-MC         291683.0      2
L-SC         208963.0      2
M-LC         163538.0      1
M-MC          55864.0      2
H-LC          52016.0      1
L-MC          45450.0      1

In [31]:
# money to be made criteria and conviction-wise
df_portfolio_features.groupby(['Conviction', 'Criteria'])['FTT Amt'].agg(['sum', 'count']).sort_values(by='sum', ascending=False)

                           sum  count
Conviction Criteria
H-SC       XY24      1018936.0      6
X-LC       X40        951274.0     10
H-SC       AR         926729.0      5
M-SC       XY24       831390.0      6
H-SC       XR         782411.0      7
X-SC       XY24       733071.0      4
X-MC       X40        634647.0      7
X-LC       X40N       400704.0      6
           XY24       368118.0      2
X-MC       X40N       365509.0      4
M-SC       OX40N      309161.0      5
H-SC       OX40N      304041.0      4
X-SC       X40N       297379.0      3
H-SC       SR         284758.0      2
H-MC       XY24       252808.0      1
X-MC       XY25       238371.0      2
           XY24       231916.0      2
X-SC       X40        208296.0      2
M-SC       XR         193525.0      2
X-LC       XY25       170338.0      2
M-LC       XR         163538.0      1
L-SC       OX40N      114344.0      1
           XR          94619.0      1
M-SC       AR          76191.0      1
H-LC       AR          52016.0      1
L-MC       XR          45450.0      1
M-MC       XY25        41699.0      1
H-MC       AR          38875.0      1
X-LC       XR          37702.0      1
M-MC       AR          14165.0      1

In [32]:
# notebook execution time

end_time = time.time()
execution_time = round(end_time - start_time, 0)
print(f"Notebook execution time: {execution_time} seconds")

Notebook execution time: 27.0 seconds