<a href="https://colab.research.google.com/github/ankit-rathi/Quantvesting_v2/blob/main/myStocks_Portfolio_Analysis.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
'''
!pip install pandas==2.2.2 -qq
!pip install pyxirr -qq
!pip install ta -qq
!pip install yfinance==0.2.59 -qq
'''

'\n!pip install pandas==2.2.2 -qq\n!pip install pyxirr -qq\n!pip install ta -qq\n!pip install yfinance==0.2.59 -qq\n'

In [2]:
# import libraries

import numpy as np
import pandas as pd
import datetime
import warnings
warnings.filterwarnings('ignore')
import yfinance as yfin
import ta
import matplotlib.pyplot as plt
import requests

In [3]:
# notebook start time
import time
import datetime
import pytz

start_time = time.time()

# function to print date timestamp
def print_date_time():
  tz_NY = pytz.timezone('Asia/Kolkata')
  datetime_NY = datetime.datetime.now(tz_NY)
  print("Run date time (IST):", datetime_NY.strftime("%Y-%m-%d %H:%M:%S"))

In [4]:
# function to get booked and reserved amount
def get_amt():
  # fetch the JSON data from the URL
  url = "https://raw.githubusercontent.com/ankit-rathi/Tradevesting_v1/main/data/myPortfolioAmts.json"
  response = requests.get(url)
  pf_amts = response.json()  # parse the JSON data

  # extract values from the JSON
  py_booked_amt_dm = pf_amts["py_booked_amt_dm"]
  py_booked_amt_sv = pf_amts["py_booked_amt_sv"]
  cy_booked_amt_dm = pf_amts["cy_booked_amt_dm"]
  cy_booked_amt_sv = pf_amts["cy_booked_amt_sv"]
  reserve_amt_dm = pf_amts["reserve_amt_dm"]
  reserve_amt_sv = pf_amts["reserve_amt_sv"]

  # perform calculations
  py_booked_amt = py_booked_amt_dm + py_booked_amt_sv
  cy_booked_amt = cy_booked_amt_dm + cy_booked_amt_sv
  reserve_amt = reserve_amt_dm + reserve_amt_sv
  total_booked_amt = py_booked_amt + cy_booked_amt

  return total_booked_amt, reserve_amt, cy_booked_amt, py_booked_amt

gen_output = 0

In [5]:
# function to format the amount
def format_amt(number):
    abs_number = abs(number)

    if abs_number >= 1_00_00_000:  # Crores
        formatted_amt = f"{number / 1_00_00_000:.2f} C"
    elif abs_number >= 1_00_000:  # Lakhs
        formatted_amt = f"{number / 1_00_000:.2f} L"
    elif abs_number >= 1_000:  # Thousands
        formatted_amt = f"{number / 1_000:.2f} K"
    else:
        formatted_amt = f"{number:.2f}"

    return formatted_amt

# function to set start and end date
def get_start_end_date():
  start_date = (datetime.date.today() + datetime.timedelta(days=-365)).strftime('%Y-%m-%d')
  end_date = (datetime.date.today() + datetime.timedelta(days=1)).strftime('%Y-%m-%d')
  return start_date, end_date

# function to fetch my portfolio csv
def get_mypfs_df():
  mypfs_df = pd.read_csv('https://raw.githubusercontent.com/ankit-rathi/Tradevesting_v1/main/data/myPortfolioStocks.csv')
  return mypfs_df

# function to fetch my prospects csv
def get_mypps_df():
  mypps_df = pd.read_csv('https://raw.githubusercontent.com/ankit-rathi/Tradevesting_v1/main/data/myProspectsScrips.csv')
  return mypps_df

# function to fetch screener data
def get_myscreen_df():
  myscreen_df = pd.read_csv('https://raw.githubusercontent.com/ankit-rathi/Tradevesting_v1/main/data/myScreenerDB.csv')
  return myscreen_df

# function to fetch momentum data
def get_myinvmt_df():
  myinvmt_df = pd.read_csv('https://raw.githubusercontent.com/ankit-rathi/Tradevesting_v1/main/data/myInvestments.csv')
  return myinvmt_df

# function to get the stock ids
def get_stock_ids(df_pf):
  stock_n100 = df_pf['Symbol'].unique()

  exclude = ['CADILAHC','MMTC', 'MASFIN']

  stock_ids = df_pf[~df_pf['Symbol'].isin(exclude) ]['Symbol'].unique()

  #mypf = mypf[mypf.Forecast.notnull()]
  #stock_ids = mypf['Symbol'].unique()

  #stock_ids.sort()
  return stock_ids

# get features from screener data
def get_screener_features():
  myscreen_df = get_myscreen_df()
  cols = ['Symbol', 'EPS', 'MedPE', 'ROCE%', 'ROE%', 'CapType']
  return myscreen_df[cols]

# get relative strength
def get_relative_strength(stock_list):

    # Dictionary to store stock tickers and their corresponding percentage price change
    stock_changes = {}

    # Loop through each stock and fetch its price data
    for stock in stock_list:
        try:
            # Download the stock data for the given date range
            stock_data = yfin.Ticker(stock + '.NS').history(period='1mo', interval='1d')[map(str.title, ['open', 'close', 'low', 'high', 'volume'])]

            # Calculate the percentage change for the stock
            if len(stock_data) > 0:
                start_price = stock_data['Close'].iloc[0]
                end_price = stock_data['Close'].iloc[-1]
                percent_change = round(((end_price - start_price) / start_price) * 100, 2)
                stock_changes[stock] = percent_change
            else:
                stock_changes[stock] = np.nan  # If no data is available, set to NaN

        except Exception as e:
            print(f"Error fetching data for {stock}: {e}")
            stock_changes[stock] = np.nan

    # Create a DataFrame with stock tickers and their percentage changes
    df = pd.DataFrame(list(stock_changes.items()), columns=['Symbol', 'Percent_Change'])

    # Drop any stocks with missing data (NaN values)
    df = df.dropna()

    # Calculate the percentile rank based on percentage change
    df['RSP'] = round(df['Percent_Change'].rank(pct=True) * 100, 2)
    cols = ['Symbol', 'RSP']
    df = df[cols]
    # Sort by percentile rank (optional)
    df = df.sort_values(by='RSP', ascending=False).reset_index(drop=True)

    return df

In [6]:
# function to get stock technicals
def stock_prec_dev(stock_symbol):
    #stock_symbol = 'ULTRACEMCO.NS'
    short_window = 20
    mid_window = 50
    long_window = 200
    moving_avg = 'SMA'

    start = datetime.datetime(*map(int, start_date.split('-')))
    end = datetime.datetime(*map(int, end_date.split('-')))

    stock_df = yfin.Ticker(stock_symbol + '.NS').history(period='max', interval='1d')[map(str.title, ['open', 'close', 'low', 'high', 'volume'])]

    stock_df['Max'] = round(max(stock_df['Close']),2)
    stock_df = stock_df[(stock_df.index <= end_date) & (stock_df.index >= start_date)]
    stock_df['200_SMA'] = round(stock_df['Close'].rolling(window = 200, min_periods = 1).mean(),0)
    stock_df['Dev%_200'] = round((stock_df['Close'] - stock_df['200_SMA'])*100/stock_df['200_SMA'],2)
    stock_df.dropna(axis = 0, inplace = True) # remove any null rows

    stock_df['20_SMA'] = stock_df['Close'].rolling(window=20).mean()
    stock_df['50_SMA'] = stock_df['Close'].rolling(window=50).mean()
    stock_df['Symbol'] = stock_symbol

    stock_df['Close'] = round(stock_df['Close'],2)
    stock_df['Min'] = round(min(stock_df['Close']),2)
    stock_df['RSI_14'] = ta.momentum.RSIIndicator(close=stock_df['Close'], window=14).rsi()
    stock_df['RSI_14'] = round(stock_df['RSI_14'],0)
    stock_df['Prev_Close'] = stock_df['Close'].shift(1)
    stock_df.drop(['Open', 'Low', 'High', 'Volume'], axis=1, inplace=True)
    stock_df = stock_df.tail(1)

    max_SMA = max(stock_df['20_SMA'].item(), stock_df['50_SMA'].item(), stock_df['200_SMA'].item())
    min_SMA = min(stock_df['20_SMA'].item(), stock_df['50_SMA'].item(), stock_df['200_SMA'].item())
    ABS_Spread = max_SMA - min_SMA
    stock_df['Spread%'] = round((ABS_Spread / stock_df['200_SMA'].item()) * 100,2)

    return stock_df

# function to compute stock attributes
def get_common_features(stock_ids, df_mypf):

  df_prec_dev = pd.DataFrame()
  df_tmp = get_screener_features()
  df_rs = get_relative_strength(stock_ids)

  for stock_id in stock_ids:
      tmp = stock_prec_dev(stock_id)
      tmp = tmp.reset_index()
      df_prec_dev = pd.concat([df_prec_dev, tmp], ignore_index = True)
  df_prec_dev = pd.merge(df_prec_dev, df_mypf, on= 'Symbol')
  df_prec_dev = pd.merge(df_prec_dev, df_tmp, on= 'Symbol', how='left')
  df_prec_dev = pd.merge(df_prec_dev, df_rs, on= 'Symbol', how='left')
  #print(df_prec_dev.columns)
  df_prec_dev['Curr_PE'] = round(df_prec_dev['Close']/df_prec_dev['EPS'],1)
  df_prec_dev['Dev%_PE'] = round((df_prec_dev['Curr_PE'] - df_prec_dev['MedPE'])*100/df_prec_dev['MedPE'],2)
  df_prec_dev['Conviction'] = df_prec_dev['Conviction'] + '-' + df_prec_dev['CapType']
  return df_prec_dev

# function to arrange stock features
def arrange_features(df_stocks, common_cols, diff_cols):
  df_stocks_common = df_stocks[common_cols].drop_duplicates()
  df_stocks_diff = df_stocks[diff_cols]
  df_stocks_diff['Investment'] = df_stocks_diff['AvgCost'] * df_stocks_diff['Shares']
  df_stocks_diff = df_stocks_diff.groupby(['Symbol'])[['Shares', 'Investment']].aggregate(['sum']).reset_index()
  df_stocks_diff.columns = ['Symbol', 'Shares', 'Investment']
  df_stocks_diff['AvgCost'] = round(df_stocks_diff['Investment']/df_stocks_diff['Shares'],2)
  df_stocks = pd.merge(df_stocks_diff, df_stocks_common, on='Symbol')
  return df_stocks

# plot fact distribution across dimension
def plot_pie_chart(df, dimension, fact):
  # grouping the data by category and calculating the sum of fact for each type
  grouped_data = df.groupby(dimension)[fact].sum()

  # sorting the grouped data in descending order
  grouped_data = grouped_data.sort_values(ascending=False)

  # creating a pie chart
  grouped_data.plot.pie(autopct='%1.1f%%', startangle=90, figsize=(6, 6))

  # adding a title and displaying the plot
  plt.title(f'{dimension} {fact} Distribution')
  plt.ylabel('')  # To hide the y-label
  plt.show()

In [7]:
# function to get portfolio features

def get_portfolio_features(df_common_features):

  print_date_time()
  print('-------------------')

  #df_common_features["Target"] = df_common_features["Target"].fillna(df_common_features["Max"])
  df_common_features['NTT'] = np.where(df_common_features['Strategy']== 'NTT', df_common_features["Target"], df_common_features['Max'])
  df_common_features['LTT'] = np.where(df_common_features['Strategy']== 'BTT', df_common_features["Target"], df_common_features['Max'])
  df_common_features['BOL'] = df_common_features['Min']

  tmp_df = df_common_features[df_common_features['Symbol'].isin(mypf_df[mypf_df['InPortfolio'] != 'NA'].Symbol.values)]
  print('qualified stocks: '+str(len(tmp_df['Symbol'].unique())))
  tmp_df1 = tmp_df[tmp_df['LatestQtr'] == 1]
  print('with latest results: '+str(len(tmp_df1['Symbol'].unique())))
  tmp_df1 = tmp_df1[tmp_df1['StarStock'] == 1]
  print('still star stocks: '+str(len(tmp_df1['Symbol'].unique())))
  tmp_df['Investment'] = tmp_df['AvgCost'] * tmp_df['Shares']
  tmp_df['Current'] = round(tmp_df['Close'] * tmp_df['Shares'],0)
  tmp_df['Previous'] = tmp_df['Prev_Close'] * tmp_df['Shares']
  tmp_df['EstimatedST'] = tmp_df['NTT'] * tmp_df['Shares']
  tmp_df['EstimatedLT'] = tmp_df['LTT'] * tmp_df['Shares']
  tmp_df['Current P/L'] = round((tmp_df['Current'] - tmp_df['Investment']),0)
  tmp_df['Today P/L%'] = round((tmp_df['Current'] - tmp_df['Previous'])*100/tmp_df['Previous'],2)
  tmp_df['Current P/L%'] = round((tmp_df['Current'] - tmp_df['Investment'])*100/tmp_df['Investment'],2)
  tmp_df['EstimatedST P/L%'] = round((tmp_df['EstimatedST'] - tmp_df['Investment'])*100/tmp_df['Investment'],2)
  tmp_df['EstimatedLT P/L%'] = round((tmp_df['EstimatedLT'] - tmp_df['Investment'])*100/tmp_df['Investment'],2)
  tmp_df['NTT%'] = round((tmp_df['NTT'] - tmp_df['Close'])*100/tmp_df['Close'],2)
  tmp_df['LTT%'] = round((tmp_df['LTT'] - tmp_df['Close'])*100/tmp_df['Close'],2)
  tmp_df['Gained%'] = round((tmp_df['Close'] - tmp_df['BOL'])*100/tmp_df['BOL'],2)
  investment = round(sum(tmp_df['AvgCost']*tmp_df['Shares']),0)
  current = round(sum(tmp_df['Close']*tmp_df['Shares']),0)
  tmp_df['InitAlloc%'] = round(tmp_df['Investment']*100/investment,2)
  tmp_df['CurrAlloc%'] = round(tmp_df['Current']*100/current,2)
  tmp_df['FTT'] = tmp_df['LTT']
  tmp_df.loc[tmp_df['Strategy'] == 'NTT', 'FTT'] = tmp_df['NTT']
  tmp_df['FTT%'] = tmp_df['LTT%']
  tmp_df.loc[tmp_df['Strategy'] == 'NTT', 'FTT%'] = tmp_df['NTT%']
  tmp_df['FTT Amt'] = round(tmp_df['FTT%'] * tmp_df['Current']/100,0)
  tmp_df['OTT%'] = round((tmp_df['FTT'] - tmp_df['AvgCost'])*100/tmp_df['AvgCost'],2)
  tmp_df['RRR Ind'] = round(tmp_df['Current P/L']/tmp_df['FTT Amt'],2)
  tmp_df['Risk Ind'] = round(tmp_df['Current P/L%']*tmp_df['CurrAlloc%'],0)

  return tmp_df

# function to print portfolio features
def print_portfolio_stats(df_portfolio_features, myinvmt_df):
  from pyxirr import xirr

  total_booked_amt, reserve_amt, cy_booked_amt, py_booked_amt = get_amt()

  dates = myinvmt_df['Date'].values
  dates = np.append(dates, datetime.date.today().strftime('%d-%b-%y'))
  investment = myinvmt_df['Investment'].values
  dates= pd.to_datetime(dates)

  current = round(sum(df_portfolio_features['Close']*df_portfolio_features['Shares']),0) + reserve_amt
  investment_xirr = np.append(investment, current)
  cagr = round(xirr(pd.DataFrame({"dates": dates, "amounts": investment_xirr}))*100,2)

  investment = -sum(investment)
  invested = round(sum(df_portfolio_features['AvgCost']*df_portfolio_features['Shares']),0) + reserve_amt
  previous = round(sum(df_portfolio_features['Prev_Close']*df_portfolio_features['Shares']),0) + reserve_amt
  cy_invested = investment + py_booked_amt

  today_pnl_amount = current-previous
  today_pnl_percentage = round((current-previous)*100/previous,2)

  curr_pnl_amount = current-invested
  curr_pnl_percentage = round((curr_pnl_amount)*100/(cy_invested),2)

  cy_pnl_amount = cy_booked_amt + curr_pnl_amount
  cy_pnl_percentage = round((cy_pnl_amount)*100/cy_invested,2)

  overall_pnl_amount = total_booked_amt + curr_pnl_amount
  overall_pnl_percentage = round((overall_pnl_amount)*100/investment,2)

  estimate_st = round(sum(df_portfolio_features['FTT']*df_portfolio_features['Shares']),0)  + reserve_amt
  est_st_pnl_amount = estimate_st-current
  est_st_pnl_percentage = round((est_st_pnl_amount)*100/current,2)

  estimate_lt = round(sum(df_portfolio_features['LTT']*df_portfolio_features['Shares']),0)  + reserve_amt
  est_lt_pnl_amount = estimate_lt-current
  est_lt_pnl_percentage = round((est_lt_pnl_amount)*100/current,2)

  total_profit = round(sum(df_portfolio_features[df_portfolio_features['Current P/L%'] > 0]['Current']) - sum(df_portfolio_features[df_portfolio_features['Current P/L%'] > 0]['Investment']),0)
  total_loss = round(sum(df_portfolio_features[df_portfolio_features['Current P/L%'] < 0]['Current']) - sum(df_portfolio_features[df_portfolio_features['Current P/L%'] < 0]['Investment']),0)

  cy_booked_percentage = round((cy_booked_amt)*100/current,2)
  py_booked_percentage = round((py_booked_amt)*100/investment,2)
  total_booked_percentage = round((total_booked_amt)*100/investment,2)

  print('-------------------')
  print('Initial Investment: ', format_amt(investment))
  print('CY Investment: ', format_amt(cy_invested))
  print('Reserve: ', format_amt(reserve_amt))
  print('Current: ',  format_amt(current))
  print('-------------------')
  print('Today PnL: '+ '{} ({}%)'.format(format_amt(today_pnl_amount), today_pnl_percentage))
  print('Current PnL: '+ '{} ({}%)'.format(format_amt(curr_pnl_amount), curr_pnl_percentage))
  print('CY Booked + Current PnL: '+ '{} ({}%)'.format(format_amt(cy_pnl_amount), cy_pnl_percentage))
  print('-------------------')
  print('Total profit: ', format_amt(total_profit))
  print('Total loss: ', format_amt(total_loss))
  print('-------------------')
  print('Total Booked + Current PnL: '+ '{} ({}%)'.format(format_amt(overall_pnl_amount), overall_pnl_percentage))
  print('Total Booked PnL: '+ '{} ({}%)'.format(format_amt(total_booked_amt), total_booked_percentage))
  print('Curr Year Booked PnL: '+ '{} ({}%)'.format(format_amt(cy_booked_amt), cy_booked_percentage))
  print('Prev Year Booked PnL: '+ '{} ({}%)'.format(format_amt(py_booked_amt), py_booked_percentage))
  print('===================')
  print('Est FTT: ',  format_amt(estimate_st))
  print('Est FTT PnL: '+ '{} ({}%)'.format(format_amt(est_st_pnl_amount), est_st_pnl_percentage))

  print('===================')
  print('Deployed: ', format_amt(investment))

  print('Current: ', format_amt(current))

  print('CAGR/XIRR %: '+'{}%'.format(cagr))

In [8]:
# get start and end date
start_date, end_date = get_start_end_date()

# get portfolio and prospects data
mypfs_df = get_mypfs_df()
mypps_df = get_mypps_df()
myinvmt_df = get_myinvmt_df()

# merge above datasets
mypf_df = pd.merge(mypfs_df, mypps_df, on="Symbol")

# seggregate dm and sv portfolio
dm_pf = mypf_df[mypf_df['InPortfolio'] == 'DM']
sv_pf = mypf_df[mypf_df['InPortfolio'] == 'SV']

# build portfolio stock dataframe
dm_stocks = get_stock_ids(dm_pf)
sv_stocks = get_stock_ids(sv_pf)
df_stocks = pd.concat([dm_pf,sv_pf], ignore_index = True)

# arrange common and diff stock features
common_cols = ['Symbol', 'Target', 'Criteria', 'Strategy', 'CumlRnk', 'LatestQtr', 'StarStock', 'Conviction', 'Category', 'InFolio', 'XIRR', 'MBQ']
diff_cols = ['Symbol', 'AvgCost', 'Shares']
df_stocks = arrange_features(df_stocks, common_cols, diff_cols)

# get common features
stock_ids = df_stocks['Symbol'].values
df_common_features = get_common_features(stock_ids, df_stocks)

df_common_features.reset_index(drop=True, inplace=True)
df_common_features.drop(['Date'], axis=1, inplace=True)
# get and print portfolio features
df_portfolio_features = get_portfolio_features(df_common_features)

print_portfolio_stats(df_portfolio_features, myinvmt_df)

df = df_portfolio_features
#plot_pie_chart(df, 'CapType', 'Current')
list_ox40n = list(df[df['MBQ'].str.contains('OX40N', na=False)]['Symbol'].values)

Run date time (IST): 2026-03-23 12:39:21
-------------------
qualified stocks: 86
with latest results: 26
still star stocks: 16
-------------------
Initial Investment:  1.36 C
CY Investment:  1.62 C
Reserve:  1.61 K
Current:  1.27 C
-------------------
Today PnL: -4.47 L (-3.4%)
Current PnL: -50.13 L (-30.85%)
CY Booked + Current PnL: -34.24 L (-21.07%)
-------------------
Total profit:  34.62 K
Total loss:  -50.48 L
-------------------
Total Booked + Current PnL: -7.26 L (-5.36%)
Total Booked PnL: 42.87 L (31.64%)
Curr Year Booked PnL: 15.89 L (12.51%)
Prev Year Booked PnL: 26.98 L (19.91%)
===================
Est FTT:  2.48 C
Est FTT PnL: 1.21 C (95.2%)
===================
Deployed:  1.36 C
Current:  1.27 C
CAGR/XIRR %: -3.18%

In [9]:
# top 5 near their targets
cols = ['Symbol', 'Today P/L%', 'Current P/L%', 'FTT%', 'OTT%', 'FTT Amt', 'Current P/L', 'Current', 'FTT', 'Dev%_PE', 'RSI_14','Conviction', 'Spread%',  'CumlRnk', 'RRR Ind', 'CurrAlloc%', 'Gained%', 'Criteria', 'Strategy', 'Category']
df_tmp = df_portfolio_features[~df_portfolio_features['Symbol'].isin(['ENRIN','BLUSPRING','DIGITIDE'])]
df_tmp = df_tmp.sort_values(by = 'FTT Amt', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
50,MASFIN,-4.15,-11.21,36.91,21.57,32112.0,-10980.0,87000.0,397.04,-23.67,37.0,H-SC,1.76,167.0,-0.34,0.69,18.66,XR,ATH,FINANCE
77,TTKPRESTIG,-2.00,-40.59,68.47,0.09,40996.0,-40903.0,59874.0,770.00,38.95,37.0,M-SC,18.57,250.0,-1.00,0.47,1.16,OX40N,NTT,DURABLES
37,ICICIGI,-2.45,-8.17,29.96,19.34,55055.0,-16347.0,183762.0,2252.93,-22.78,25.0,X-MC,3.17,66.0,-0.30,1.45,1.58,X40,ATH,INSURANCE
67,SONACOMS,-3.54,-15.52,64.64,39.09,55242.0,-15698.0,85461.0,804.02,-33.03,42.0,M-MC,7.93,193.0,-0.28,0.67,20.90,AR,ATH,AUTO
42,INDUSINDBK,-3.69,-41.79,128.31,32.89,57661.0,-32268.0,44939.0,1800.00,-311.48,30.0,L-MC,8.42,258.0,-0.56,0.35,23.76,XR,NTT,BANKS

In [10]:
# top 5 today
df_tmp = df_portfolio_features.sort_values(by = 'Today P/L%', ascending=False)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
73,TCS,1.47,-29.82,80.36,26.57,261268.0,-138151.0,325122.0,4311.59,-40.68,28.0,X-LC,16.66,2.0,-0.53,2.56,1.47,X40,ATH,IT
33,HCLTECH,1.44,-12.20,41.04,23.83,87171.0,-29519.0,212405.0,1908.19,-7.78,41.0,X-LC,11.75,8.0,-0.34,1.67,3.13,X40,ATH,IT
62,SATIN,-0.19,-19.71,89.11,51.83,197670.0,-54457.0,221827.0,274.00,-27.73,40.0,H-SC,1.83,159.0,-0.28,1.75,8.06,XY24,NTT,FINANCE
43,INFY,-0.60,-15.01,57.96,34.24,154121.0,-46979.0,265909.0,1972.00,-33.24,35.0,X-LC,15.11,3.0,-0.30,2.09,2.26,X40,NTT,IT
69,SURYODAY,-0.77,-30.17,76.20,23.03,95282.0,-54029.0,125042.0,216.00,35.96,42.0,H-SC,6.69,166.0,-0.57,0.98,22.21,XR,NTT,BANKS

In [11]:
# bottom 5 today
df_tmp = df_portfolio_features.sort_values(by = 'Today P/L%', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
80,VALIANTORG,-8.82,-48.97,241.29,74.15,201439.0,-80121.0,83484.0,838.00,-250.34,55.0,H-SC,28.33,145.0,-0.40,0.66,24.24,XR,NTT,CHEMICALS
8,AWL,-7.90,-39.07,174.14,67.02,378025.0,-139228.0,217081.0,485.00,-67.16,40.0,X-SC,26.01,81.0,-0.37,1.71,2.68,XY24,NTT,FMCG
11,BANDHANBNK,-7.67,-29.63,173.45,92.42,339988.0,-82544.0,196015.0,400.00,68.10,32.0,H-SC,6.84,174.0,-0.24,1.54,7.98,XY24,NTT,BANKS
82,VOLTAS,-7.00,-3.64,50.67,45.20,93623.0,-6972.0,184770.0,1856.00,10.30,25.0,X-MC,4.85,79.0,-0.07,1.46,2.91,XY25,NTT,AC
26,FINCABLES,-6.68,3.79,100.31,107.91,153721.0,5602.0,153246.0,1641.55,-6.65,45.0,M-SC,8.37,220.0,0.04,1.21,15.29,OX40N,ATH,CABLES

In [12]:
# top 5 to exit based on CumlRnk
df_tmp = df_portfolio_features[~df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])]
df_tmp = df_tmp[(df_tmp['Current P/L%'] > -1) & (df_tmp['Current P/L%'] < 1)].sort_values(by = 'CumlRnk', ascending=False)
df_tmp[cols].head()

Empty DataFrame
Columns: [Symbol, Today P/L%, Current P/L%, FTT%, OTT%, FTT Amt, Current P/L, Current, FTT, Dev%_PE, RSI_14, Conviction, Spread%, CumlRnk, RRR Ind, CurrAlloc%, Gained%, Criteria, Strategy, Category]
Index: []

In [13]:
# OX40N stocks to exit
df_tmp = df_portfolio_features[(df_portfolio_features['Symbol'].isin(list_ox40n))].sort_values(by = 'Current P/L%', ascending=False)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
26,FINCABLES,-6.68,3.79,100.31,107.91,153721.0,5602.0,153246.0,1641.55,-6.65,45.0,M-SC,8.37,220.0,0.04,1.21,15.29,OX40N,ATH,CABLES
72,TATAELXSI,-2.19,-40.27,121.02,32.03,95304.0,-53084.0,78751.0,9161.00,-25.24,35.0,H-SC,20.61,158.0,-0.56,0.62,2.61,OX40N,NTT,IT
66,SIS,-5.35,-40.52,103.86,21.26,68594.0,-44987.0,66045.0,528.00,1536.79,26.0,H-SC,14.25,168.0,-0.66,0.52,0.00,OX40N,NTT,MISC
18,CERA,-4.41,-40.59,108.52,23.89,113416.0,-71391.0,104512.0,9475.00,-42.72,39.0,H-SC,18.78,153.0,-0.63,0.82,0.44,OX40N,NTT,CERAMICS
77,TTKPRESTIG,-2.00,-40.59,68.47,0.09,40996.0,-40903.0,59874.0,770.00,38.95,37.0,M-SC,18.57,250.0,-1.00,0.47,1.16,OX40N,NTT,DURABLES

In [14]:
# top 5 to book for rotation
df_tmp = df_portfolio_features[(df_portfolio_features['Current P/L%'] > 20) ].sort_values(by = 'CumlRnk', ascending=False)
df_tmp[cols].head()

Empty DataFrame
Columns: [Symbol, Today P/L%, Current P/L%, FTT%, OTT%, FTT Amt, Current P/L, Current, FTT, Dev%_PE, RSI_14, Conviction, Spread%, CumlRnk, RRR Ind, CurrAlloc%, Gained%, Criteria, Strategy, Category]
Index: []

In [15]:
# top 5 to monitor for exit
df_tmp = df_portfolio_features[~df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])]
df_tmp = df_tmp[(df_tmp['Current P/L%'] > 0) ].sort_values(by = 'Dev%_PE', ascending=False)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
26,FINCABLES,-6.68,3.79,100.31,107.91,153721.0,5602.0,153246.0,1641.55,-6.65,45.0,M-SC,8.37,220.0,0.04,1.21,15.29,OX40N,ATH,CABLES
1,ABB,-3.84,11.09,31.03,45.57,90186.0,29021.0,290640.0,7934.00,-28.65,51.0,H-MC,13.08,125.0,0.32,2.29,29.06,AR,NTT,ELECTRICAL

In [16]:
# top 5 to book for rotation from weak conviction
df_tmp = df_portfolio_features[~df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])]
df_tmp = df_tmp[~df_tmp['Criteria'].isin(['XY25','XY24','X40', 'X40N'])].sort_values(by = 'RRR Ind', ascending=False)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
1,ABB,-3.84,11.09,31.03,45.57,90186.0,29021.0,290640.0,7934.00,-28.65,51.0,H-MC,13.08,125.0,0.32,2.29,29.06,AR,NTT,ELECTRICAL
26,FINCABLES,-6.68,3.79,100.31,107.91,153721.0,5602.0,153246.0,1641.55,-6.65,45.0,M-SC,8.37,220.0,0.04,1.21,15.29,OX40N,ATH,CABLES
40,INDIAMART,-1.91,-15.94,145.92,106.72,151288.0,-19657.0,103679.0,4810.62,-62.11,29.0,H-SC,11.22,140.0,-0.13,0.82,3.71,AR,ATH,MISC
85,ZYDUSLIFE,-1.73,-7.72,46.97,35.63,90839.0,-16177.0,193397.0,1286.17,-19.82,41.0,H-MC,5.36,120.0,-0.18,1.52,7.67,AR,ATH,PHARMA
84,WIPRO,-1.21,-22.65,122.71,72.27,160836.0,-38378.0,131070.0,420.00,-30.18,29.0,M-LC,17.45,98.0,-0.24,1.03,0.10,XR,NTT,IT

In [17]:
# top 5 to accumulate based on lowest RSI_14
df_tmp = df_portfolio_features[df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])].sort_values(by = 'RSI_14', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
53,PGHH,-2.98,-29.43,87.06,32.01,131189.0,-62832.0,150688.0,17616.87,-52.23,11.0,X-MC,15.19,57.0,-0.48,1.19,0.0,X40,ATH,FMCG
58,RELAXO,-6.33,-66.77,358.30,52.31,172848.0,-96919.0,48241.0,1176.00,-64.57,17.0,X-SC,25.55,92.0,-0.56,0.38,0.0,X40N,NTT,FOOTWEAR
12,BATAINDIA,-5.29,-59.48,233.65,35.20,121827.0,-76529.0,52141.0,2096.00,-31.70,18.0,X-SC,30.58,91.0,-0.63,0.41,0.0,X40,NTT,FOOTWEAR
38,ICICIPRULI,-3.43,-11.78,48.18,30.73,83740.0,-23198.0,173807.0,790.00,-35.47,18.0,X-MC,3.88,78.0,-0.28,1.37,0.0,X40,ATH,INSURANCE
34,HDFCBANK,-3.86,-10.24,43.01,28.37,90680.0,-24051.0,210834.0,1073.00,-23.49,20.0,X-LC,11.51,26.0,-0.27,1.66,0.0,X40,BTT,BANKS

In [18]:
# top 5 to accumulate based on Spread and CumlRnk
df_tmp = df_portfolio_features[df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])]
df_tmp = df_tmp[(df_tmp['CumlRnk'] < 100)].sort_values(by = 'Spread%', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
78,UNITDSPR,-1.98,-6.39,29.01,20.77,63584.0,-14964.0,219180.0,1644.00,-16.95,37.0,X-MC,1.44,64.0,-0.24,1.73,0.00,X40N,NTT,BREWERIES
37,ICICIGI,-2.45,-8.17,29.96,19.34,55055.0,-16347.0,183762.0,2252.93,-22.78,25.0,X-MC,3.17,66.0,-0.30,1.45,1.58,X40,ATH,INSURANCE
65,SIEMENS,-5.46,-20.51,57.90,25.51,85651.0,-38165.0,147930.0,4671.50,24.19,37.0,H-LC,3.23,51.0,-0.45,1.17,8.94,AR,ATH,ELECTRICAL
59,RELIANCE,-1.07,-10.18,39.51,25.30,71314.0,-20466.0,180497.0,1952.00,-12.34,48.0,X-LC,3.43,21.0,-0.29,1.42,20.51,XY25,BTT,REFINERIES
38,ICICIPRULI,-3.43,-11.78,48.18,30.73,83740.0,-23198.0,173807.0,790.00,-35.47,18.0,X-MC,3.88,78.0,-0.28,1.37,0.00,X40,ATH,INSURANCE

In [19]:
# top 5 to accumulate based on lowest Gained%
df_tmp = df_portfolio_features[df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])].sort_values(by = 'Gained%', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
2,ABBOTINDIA,-4.49,-14.41,37.94,18.07,58082.0,-25765.0,153090.0,35195.00,-27.11,35.0,X-MC,10.72,58.0,-0.44,1.21,0.0,X40,ATH,PHARMA
3,ACC,-3.52,-40.35,193.07,74.81,308788.0,-108192.0,159936.0,3906.00,-57.90,25.0,X-SC,17.10,85.0,-0.35,1.26,0.0,XY24,BTT,CEMENT
6,ASIANPAINT,-2.95,-23.32,62.40,24.52,135615.0,-66108.0,217331.0,3460.25,-22.73,29.0,X-LC,9.40,30.0,-0.49,1.71,0.0,X40,ATH,PAINTS
9,BAJAJHFL,-4.03,-30.17,132.19,62.13,252029.0,-82389.0,190657.0,181.50,-42.59,24.0,X-MC,20.03,60.0,-0.33,1.50,0.0,X40N,ATH,FINANCE
12,BATAINDIA,-5.29,-59.48,233.65,35.20,121827.0,-76529.0,52141.0,2096.00,-31.70,18.0,X-SC,30.58,91.0,-0.63,0.41,0.0,X40,NTT,FOOTWEAR

In [20]:
# top 5 to accumulate based on lowest CurrAlloc%
df_tmp = df_portfolio_features[df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])].sort_values(by = 'CurrAlloc%', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
58,RELAXO,-6.33,-66.77,358.30,52.31,172848.0,-96919.0,48241.0,1176.00,-64.57,17.0,X-SC,25.55,92.0,-0.56,0.38,0.0,X40N,NTT,FOOTWEAR
12,BATAINDIA,-5.29,-59.48,233.65,35.20,121827.0,-76529.0,52141.0,2096.00,-31.70,18.0,X-SC,30.58,91.0,-0.63,0.41,0.0,X40,NTT,FOOTWEAR
54,QUESS,-3.38,-29.57,146.91,73.90,110495.0,-31580.0,75213.0,424.00,-61.98,32.0,X-SC,20.83,80.0,-0.29,0.59,0.0,XY24,NTT,MISC
36,HONAUT,-3.72,-29.28,113.96,51.31,155413.0,-56463.0,136375.0,58357.33,-41.24,21.0,X-SC,15.42,90.0,-0.36,1.07,0.0,X40N,ATH,ELECTRICAL
51,MEDANTA,-3.02,-16.57,52.36,27.12,77111.0,-29247.0,147270.0,1486.00,-19.15,24.0,X-SC,11.58,87.0,-0.38,1.16,0.0,XY24,NTT,HEALTHCARE

In [21]:
# top 5 to accumulate based on CumlRnk
df_tmp = df_portfolio_features.sort_values(by = 'CumlRnk', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
45,ITC,-3.17,-23.50,55.62,19.06,144747.0,-79923.0,260243.0,452.00,-57.95,29.0,X-LC,18.20,1.0,-0.55,2.05,0.00,X40,NTT,FMCG
73,TCS,1.47,-29.82,80.36,26.57,261268.0,-138151.0,325122.0,4311.59,-40.68,28.0,X-LC,16.66,2.0,-0.53,2.56,1.47,X40,ATH,IT
43,INFY,-0.60,-15.01,57.96,34.24,154121.0,-46979.0,265909.0,1972.00,-33.24,35.0,X-LC,15.11,3.0,-0.30,2.09,2.26,X40,NTT,IT
75,TMPV,-2.55,-30.32,96.01,36.58,238048.0,-107900.0,247941.0,600.00,-85.81,32.0,X-LC,6.01,4.0,-0.45,1.95,0.00,XY24,NTT,AUTO
33,HCLTECH,1.44,-12.20,41.04,23.83,87171.0,-29519.0,212405.0,1908.19,-7.78,41.0,X-LC,11.75,8.0,-0.34,1.67,3.13,X40,ATH,IT

In [22]:
# top 5 for average up
df_tmp = df_portfolio_features[(df_portfolio_features['Dev%_200'] > 5)].sort_values(by = 'CurrAlloc%', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
1,ABB,-3.84,11.09,31.03,45.57,90186.0,29021.0,290640.0,7934.0,-28.65,51.0,H-MC,13.08,125.0,0.32,2.29,29.06,AR,NTT,ELECTRICAL

In [23]:
# top 5 RSP
df_tmp = df_portfolio_features.sort_values(by = 'RSP', ascending=False)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
30,HAPPSTMNDS,-4.53,-51.03,277.49,84.85,174153.0,-65405.0,62760.0,1480.71,-41.79,53.0,H-SC,26.96,152.0,-0.38,0.49,16.22,AR,ATH,IT
69,SURYODAY,-0.77,-30.17,76.20,23.03,95282.0,-54029.0,125042.0,216.00,35.96,42.0,H-SC,6.69,166.0,-0.57,0.98,22.21,XR,NTT,BANKS
1,ABB,-3.84,11.09,31.03,45.57,90186.0,29021.0,290640.0,7934.00,-28.65,51.0,H-MC,13.08,125.0,0.32,2.29,29.06,AR,NTT,ELECTRICAL
80,VALIANTORG,-8.82,-48.97,241.29,74.15,201439.0,-80121.0,83484.0,838.00,-250.34,55.0,H-SC,28.33,145.0,-0.40,0.66,24.24,XR,NTT,CHEMICALS
26,FINCABLES,-6.68,3.79,100.31,107.91,153721.0,5602.0,153246.0,1641.55,-6.65,45.0,M-SC,8.37,220.0,0.04,1.21,15.29,OX40N,ATH,CABLES

In [24]:
# Top N allocation
df_tmp = df_portfolio_features.sort_values(by = 'CurrAlloc%', ascending=False)
top_n_values = [10, 25, 50]

sum_df = pd.DataFrame({
    'Top_N': top_n_values,
    'Sum_Alloc%': [df_tmp['CurrAlloc%'].head(n).sum() for n in top_n_values]
})

sum_df

   Top_N  Sum_Alloc%
0     10       20.82
1     25       45.86
2     50       78.11

In [25]:
# market-cap-wise allocation
df_tmp = df_portfolio_features[cols]
df_tmp.groupby(df_tmp['Conviction'].str[-2:])['CurrAlloc%'].sum().sort_values(ascending=False)

Conviction
SC    44.25
MC    30.13
LC    25.62
Name: CurrAlloc%, dtype: float64

In [26]:
# criteria-wise allocation
df_portfolio_features.groupby('Criteria')['CurrAlloc%'].sum().sort_values(ascending=False)

Criteria
XY24     26.90
X40      25.65
X40N     15.07
AR        9.22
XR        8.32
XY25      7.30
OX40N     6.76
SR        0.78
Name: CurrAlloc%, dtype: float64

In [27]:
# conviction-wise allocation
df_portfolio_features.groupby('Conviction')['CurrAlloc%'].sum().sort_values(ascending=False)

Conviction
X-LC    23.42
X-MC    22.63
H-SC    21.54
X-SC    12.19
M-SC     9.99
H-MC     5.12
M-MC     2.03
H-LC     1.17
M-LC     1.03
L-SC     0.53
L-MC     0.35
Name: CurrAlloc%, dtype: float64

In [28]:
# sector-wise stats
df_tmp = df_portfolio_features.groupby('Category')[['CurrAlloc%', 'Current', 'Current P/L', 'FTT Amt']].sum().sort_values(by=['Current', 'Current P/L'], ascending=False)
df_tmp['Current P/L%'] = round(df_tmp['Current P/L'] * 100 / df_tmp['Current'], 2)
df_tmp['FTT%'] = round(df_tmp['FTT Amt'] * 100 / df_tmp['Current'], 2)
cols = ['CurrAlloc%', 'Current P/L%', 'FTT%']
df_tmp[cols].sort_values(by=['CurrAlloc%'], ascending=False)

               CurrAlloc%  Current P/L%    FTT%
Category
FMCG                15.17        -29.77   75.85
FINANCE             13.06        -29.65   82.48
IT                  11.97        -48.17  123.57
MISC                 6.89        -53.15  119.68
ELECTRICAL           6.55        -16.50   61.11
PAINTS               5.06        -53.18   79.79
INSURANCE            4.71        -13.46   52.29
BANKS                4.53        -33.44  101.18
PHARMA               4.18        -10.72   45.57
AUTO                 3.68        -39.96   95.49
AC                   2.01        -25.56   59.61
HEALTHCARE           1.88        -49.46   88.46
TRAVEL               1.81        -93.98  191.12
DURABLES             1.80        -69.32  110.51
FOOTWEAR             1.77        -96.77  175.67
APPARELS             1.74        -21.81   63.36
BREWERIES            1.73         -6.83   29.01
REALTY               1.44        -21.33   41.26
REFINERIES           1.42        -11.34   39.51
CERAMICS             1.37        -76.06  129.55
CEMENT               1.26        -67.65  193.07
CABLES               1.21          3.66  100.31
CHEMICALS            1.08        -93.06  250.56
ENGINEERING          1.07        -77.49  158.67
JEWELLERY            1.06       -139.23  222.35
ENTERTAINMENT        0.76       -100.15  219.52
TEXTILES             0.45        -61.13  107.08
HOTELS               0.34       -162.38  254.92

In [29]:
# money to be made criteria-wise
df_portfolio_features.groupby('Criteria')['FTT Amt'].agg(['sum', 'count']).sort_values(by='sum', ascending=False)

                sum  count
Criteria
XY24      4178916.0     21
X40       1918038.0     16
XR        1435238.0     12
AR        1400685.0     10
X40N      1388041.0     10
OX40N      934315.0     10
XY25       513443.0      5
SR         320522.0      2

In [30]:
# money to be made conviction-wise
df_portfolio_features.groupby('Conviction')['FTT Amt'].agg(['sum', 'count']).sort_values(by='sum', ascending=False)

                  sum  count
Conviction
H-SC        4057780.0     24
X-MC        1863190.0     15
X-LC        1800630.0     13
M-SC        1649429.0     14
X-SC        1634260.0     10
H-MC         427946.0      3
L-SC         223924.0      2
M-LC         160836.0      1
M-MC         127891.0      2
H-LC          85651.0      1
L-MC          57661.0      1

In [31]:
# money to be made criteria and conviction-wise
df_portfolio_features.groupby(['Conviction', 'Criteria'])['FTT Amt'].agg(['sum', 'count']).sort_values(by='sum', ascending=False)

                           sum  count
Conviction Criteria
H-SC       XY24      1422269.0      6
           AR         999248.0      5
X-LC       X40        962678.0      7
M-SC       XY24       958519.0      6
H-SC       XR         908203.0      7
X-SC       XY24       874419.0      4
X-MC       X40        737445.0      7
           X40N       563062.0      4
X-SC       X40N       541926.0      4
M-SC       OX40N      413175.0      5
H-SC       OX40N      407538.0      4
X-LC       XY24       396152.0      2
H-SC       SR         320522.0      2
X-LC       X40N       283053.0      2
X-MC       XY25       282047.0      2
           XY24       280636.0      2
H-MC       XY24       246921.0      1
X-SC       X40        217915.0      2
M-SC       XR         198216.0      2
H-MC       AR         181025.0      2
M-LC       XR         160836.0      1
X-LC       XY25       158747.0      2
L-SC       OX40N      113602.0      1
           XR         110322.0      1
H-LC       AR          85651.0      1
M-SC       AR          79519.0      1
M-MC       XY25        72649.0      1
L-MC       XR          57661.0      1
M-MC       AR          55242.0      1

In [32]:
# notebook execution time

end_time = time.time()
execution_time = round(end_time - start_time, 0)
print(f"Notebook execution time: {execution_time} seconds")

Notebook execution time: 25.0 seconds