<a href="https://colab.research.google.com/github/ankit-rathi/Quantvesting_v2/blob/main/myStocks_Performance_Over_Time.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
# notebook start time
import time
import datetime
import pytz

start_time = time.time()

# function to print date timestamp
def print_date_time():
  tz_NY = pytz.timezone('Asia/Kolkata')
  datetime_NY = datetime.datetime.now(tz_NY)
  print("Run date time (IST):", datetime_NY.strftime("%Y-%m-%d %H:%M:%S"))

print_date_time()

gen_output = 0

Run date time (IST): 2026-03-11 18:34:56

In [2]:
!pip install yfinance

Requirement already satisfied: yfinance in /usr/local/lib/python3.12/dist-packages (0.2.66)
Requirement already satisfied: pandas>=1.3.0 in /usr/local/lib/python3.12/dist-packages (from yfinance) (2.2.2)
Requirement already satisfied: numpy>=1.16.5 in /usr/local/lib/python3.12/dist-packages (from yfinance) (2.0.2)
Requirement already satisfied: requests>=2.31 in /usr/local/lib/python3.12/dist-packages (from yfinance) (2.32.4)
Requirement already satisfied: multitasking>=0.0.7 in /usr/local/lib/python3.12/dist-packages (from yfinance) (0.0.12)
Requirement already satisfied: platformdirs>=2.0.0 in /usr/local/lib/python3.12/dist-packages (from yfinance) (4.9.4)
Requirement already satisfied: pytz>=2022.5 in /usr/local/lib/python3.12/dist-packages (from yfinance) (2025.2)
Requirement already satisfied: frozendict>=2.3.4 in /usr/local/lib/python3.12/dist-packages (from yfinance) (2.4.7)
Requirement already satisfied: peewee>=3.16.2 in /usr/local/lib/python3.12/dist-packages (from yfinance) (4.0.1)
Requirement already satisfied: beautifulsoup4>=4.11.1 in /usr/local/lib/python3.12/dist-packages (from yfinance) (4.13.5)
Requirement already satisfied: curl_cffi>=0.7 in /usr/local/lib/python3.12/dist-packages (from yfinance) (0.14.0)
Requirement already satisfied: protobuf>=3.19.0 in /usr/local/lib/python3.12/dist-packages (from yfinance) (5.29.6)
Requirement already satisfied: websockets>=13.0 in /usr/local/lib/python3.12/dist-packages (from yfinance) (15.0.1)
Requirement already satisfied: soupsieve>1.2 in /usr/local/lib/python3.12/dist-packages (from beautifulsoup4>=4.11.1->yfinance) (2.8.3)
Requirement already satisfied: typing-extensions>=4.0.0 in /usr/local/lib/python3.12/dist-packages (from beautifulsoup4>=4.11.1->yfinance) (4.15.0)
Requirement already satisfied: cffi>=1.12.0 in /usr/local/lib/python3.12/dist-packages (from curl_cffi>=0.7->yfinance) (2.0.0)
Requirement already satisfied: certifi>=2024.2.2 in /usr/local/lib/python3.12/dist-packages (from curl_cffi>=0.7->yfinance) (2026.2.25)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.12/dist-packages (from pandas>=1.3.0->yfinance) (2.9.0.post0)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.12/dist-packages (from pandas>=1.3.0->yfinance) (2025.3)
Requirement already satisfied: charset_normalizer<4,>=2 in /usr/local/lib/python3.12/dist-packages (from requests>=2.31->yfinance) (3.4.4)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.12/dist-packages (from requests>=2.31->yfinance) (3.11)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.12/dist-packages (from requests>=2.31->yfinance) (2.5.0)
Requirement already satisfied: pycparser in /usr/local/lib/python3.12/dist-packages (from cffi>=1.12.0->curl_cffi>=0.7->yfinance) (3.0)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.12/dist-packages (from python-dateutil>=2.8.2->pandas>=1.3.0->yfinance) (1.17.0)

In [3]:
import pandas as pd
import numpy as np
from google.colab import data_table

#mypfs = pd.read_csv('https://raw.githubusercontent.com/ankit-rathi/Tradevesting/main/data/myPortfolioStocks.csv')
mypps = pd.read_csv('https://raw.githubusercontent.com/ankit-rathi/Tradevesting/main/data/myProspectsScrips.csv')

myscreen_df = pd.read_csv('https://raw.githubusercontent.com/ankit-rathi/Tradevesting_v1/main/data/myScreenerDB.csv')

#mypf = pd.merge(mypfs, mypps, on="Symbol")

#mypf = mypf[~mypf['InPortfolio'].isnull()]

#mypf = mypf[mypf['StarStock'] == 1]

stock_n100 = mypps['Symbol'].unique()

exclude = ['CADILAHC','MMTC', 'ADANITRANS']

#stock_n100 = mypf[~mypf['Symbol'].isin(exclude) ]['Symbol']
stock_ids = list(set(list(stock_n100)) - set(exclude))

In [4]:
import pandas as pd
import datetime
import warnings
warnings.filterwarnings('ignore')
import pandas_datareader.data as web
import yfinance as yfin

start_date = (datetime.date.today() + datetime.timedelta(days=-5)).strftime('%Y-%m-%d')
end_date = (datetime.date.today() + datetime.timedelta(days=1)).strftime('%Y-%m-%d')

df_perform = pd.DataFrame()

for stock_id in stock_ids:
    stock_id = stock_id.upper() + '.NS'
    #tmp = pd.DataFrame(web.DataReader(tickers = stock_id, start = start_date, end = end_date))
    tmp = yfin.Ticker(stock_id).history(period='5d', interval='1d')[map(str.title, ['open', 'close', 'low', 'high', 'volume'])]
    tmp['Stock'] = stock_id
    tmp['Prev_Close'] = tmp['Close'].shift(1)
    tmp['Change%'] = round((tmp['Close'] - tmp['Prev_Close'])*100/tmp['Prev_Close'],2)
    tmp = tmp.tail(1)
    #df_perform = df_perform.append(tmp)
    df_perform = pd.concat([df_perform, tmp], ignore_index = True)

ERROR:yfinance:HTTP Error 404: {"quoteSummary":{"result":null,"error":{"code":"Not Found","description":"Quote not found for symbol: SCHAEFFLER .NS"}}}
ERROR:yfinance:$SCHAEFFLER .NS: possibly delisted; no price data found  (period=5d) (Yahoo error = "No data found, symbol may be delisted")
ERROR:yfinance:$TV18BRDCST.NS: possibly delisted; no price data found  (period=5d) (Yahoo error = "No data found, symbol may be delisted")
ERROR:yfinance:$TIPSINDLTD.NS: possibly delisted; no price data found  (period=5d) (Yahoo error = "No data found, symbol may be delisted")

In [5]:
d = 365*5
start_date = (datetime.date.today() + datetime.timedelta(days=-d)).strftime('%Y-%m-%d')
end_date = (datetime.date.today() + datetime.timedelta(days=0)).strftime('%Y-%m-%d')

df_perform = pd.DataFrame()

for stock_id in stock_ids:
    #stock_id = stock_id.upper() + '.NS'

    #df_stock = pd.DataFrame(web.DataReader(tickers = stock_id, start = start_date, end = end_date))
    df_stock = yfin.Ticker(stock_id + '.NS').history(period='max', interval='1d')[map(str.title, ['open', 'close', 'low', 'high', 'volume'])]

    if df_stock.empty:
        print(f"Warning: No data found for {stock_id}. Skipping...")
        continue  # Skip to the next stock_id

    CMP = round(df_stock['Close'].values[-1],0)
    D1 = round((df_stock['Close'].values[-1] - df_stock['Close'].shift(1).values[-1])*100/df_stock['Close'].shift(1).values[-1],2)
    W1 = round((df_stock['Close'].values[-1] - df_stock['Close'].shift(5).values[-1])*100/df_stock['Close'].shift(5).values[-1],2)
    M1 = round((df_stock['Close'].values[-1] - df_stock['Close'].shift(20).values[-1])*100/df_stock['Close'].shift(20).values[-1],2)
    M3 = round((df_stock['Close'].values[-1] - df_stock['Close'].shift(60).values[-1])*100/df_stock['Close'].shift(60).values[-1],2)
    M6 = round((df_stock['Close'].values[-1] - df_stock['Close'].shift(120).values[-1])*100/df_stock['Close'].shift(120).values[-1],2)
    Y1 = round((df_stock['Close'].values[-1] - df_stock['Close'].shift(240).values[-1])*100/df_stock['Close'].shift(240).values[-1],2)
    Y2 = round(((df_stock['Close'].values[-1]/df_stock['Close'].shift(240*2).values[-1])**.5 - 1)*100,2)
    Y3 = round(((df_stock['Close'].values[-1]/df_stock['Close'].shift(240*3).values[-1])**.33 - 1)*100,2)
    Y5 = round(((df_stock['Close'].values[-1]/df_stock['Close'].shift(240*5).values[-1])**.2 - 1)*100,2)


    tmp = {'Stock':[stock_id],
           'CMP': CMP,
           '1D%' : [D1],
           '1W%' : [W1],
           '1M%' : [M1],
           '3M%' : [M3],
           '6M%' : [M6],
           '1Y%' : [Y1],
           '2Y%' : [Y2],
           '3Y%' : [Y3],
           '5Y%' : [Y5]
           }

    tmp = pd.DataFrame(tmp)

    #df_perform = df_perform.append(tmp)
    df_perform = pd.concat([df_perform, tmp], ignore_index = True)

mypps['Stock'] = mypps['Symbol']
cols = ['Stock', 'Category', 'InFolio', 'Conviction']
df_tmp = mypps[cols]
df_perform = pd.merge(df_tmp, df_perform, on="Stock")
cols = ['Symbol', 'EPS', 'MedPE', 'ROCE%', 'ROE%', 'CapType']
myscreen_df = myscreen_df[cols]
myscreen_df['Stock'] = myscreen_df['Symbol']
df_perform = pd.merge(myscreen_df, df_perform, on="Stock")
df_perform['Curr_PE'] = round(df_perform['CMP']/df_perform['EPS'],1)
df_perform['Dev%_PE'] = round((df_perform['Curr_PE'] - df_perform['MedPE'])*100/df_perform['MedPE'],2)
df_perform['Conviction'] = df_perform['Conviction'] + '-' + df_perform['CapType']
cols = ['Symbol', 'Category', 'InFolio', 'Conviction', 'Dev%_PE', '1W%','1M%','3M%','6M%','1Y%','2Y%','3Y%','5Y%'	]
df_perform = df_perform[cols]

ERROR:yfinance:$SCHAEFFLER .NS: possibly delisted; no timezone found

Warning: No data found for SCHAEFFLER . Skipping...

ERROR:yfinance:$TV18BRDCST.NS: possibly delisted; no timezone found

Warning: No data found for TV18BRDCST. Skipping...

ERROR:yfinance:$TIPSINDLTD.NS: possibly delisted; no timezone found

Warning: No data found for TIPSINDLTD. Skipping...

In [6]:
# all stocks
data_table.DataTable(df_perform, include_index=False)

In [7]:
# portfolio stocks
tmp_df = df_perform[(df_perform['InFolio'] == 1) ]
data_table.DataTable(tmp_df, include_index=False)

In [8]:
# high conviction prospects
tmp_df = df_perform[(df_perform['InFolio'] != 1) & (df_perform['Conviction'].isin(['X-LC','H-LC']))]
data_table.DataTable(tmp_df, include_index=False)

In [9]:
# notebook execution time

end_time = time.time()
execution_time = round(end_time - start_time, 0)
print(f"Notebook execution time: {execution_time} seconds")

Notebook execution time: 105.0 seconds