<a href="https://colab.research.google.com/github/ankit-rathi/Quantvesting_v2/blob/main/myStocks_Portfolio_Analysis.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
'''
!pip install pandas==2.2.2 -qq
!pip install pyxirr -qq
!pip install ta -qq
!pip install yfinance==0.2.59 -qq
'''

'\n!pip install pandas==2.2.2 -qq\n!pip install pyxirr -qq\n!pip install ta -qq\n!pip install yfinance==0.2.59 -qq\n'

In [2]:
# import libraries

import numpy as np
import pandas as pd
import datetime
import warnings
warnings.filterwarnings('ignore')
import yfinance as yfin
import ta
import matplotlib.pyplot as plt
import requests

In [3]:
# notebook start time
import time
import datetime
import pytz

start_time = time.time()

# function to print date timestamp
def print_date_time():
  tz_NY = pytz.timezone('Asia/Kolkata')
  datetime_NY = datetime.datetime.now(tz_NY)
  print("Run date time (IST):", datetime_NY.strftime("%Y-%m-%d %H:%M:%S"))

In [4]:
# function to get booked and reserved amount
def get_amt():
  # fetch the JSON data from the URL
  url = "https://raw.githubusercontent.com/ankit-rathi/Tradevesting_v1/main/data/myPortfolioAmts.json"
  response = requests.get(url)
  pf_amts = response.json()  # parse the JSON data

  # extract values from the JSON
  py_booked_amt_dm = pf_amts["py_booked_amt_dm"]
  py_booked_amt_sv = pf_amts["py_booked_amt_sv"]
  cy_booked_amt_dm = pf_amts["cy_booked_amt_dm"]
  cy_booked_amt_sv = pf_amts["cy_booked_amt_sv"]
  reserve_amt_dm = pf_amts["reserve_amt_dm"]
  reserve_amt_sv = pf_amts["reserve_amt_sv"]

  # perform calculations
  py_booked_amt = py_booked_amt_dm + py_booked_amt_sv
  cy_booked_amt = cy_booked_amt_dm + cy_booked_amt_sv
  reserve_amt = reserve_amt_dm + reserve_amt_sv
  total_booked_amt = py_booked_amt + cy_booked_amt

  return total_booked_amt, reserve_amt, cy_booked_amt, py_booked_amt

gen_output = 0

In [5]:
# function to format the amount
def format_amt(number):
    abs_number = abs(number)

    if abs_number >= 1_00_00_000:  # Crores
        formatted_amt = f"{number / 1_00_00_000:.2f} C"
    elif abs_number >= 1_00_000:  # Lakhs
        formatted_amt = f"{number / 1_00_000:.2f} L"
    elif abs_number >= 1_000:  # Thousands
        formatted_amt = f"{number / 1_000:.2f} K"
    else:
        formatted_amt = f"{number:.2f}"

    return formatted_amt

# function to set start and end date
def get_start_end_date():
  start_date = (datetime.date.today() + datetime.timedelta(days=-365)).strftime('%Y-%m-%d')
  end_date = (datetime.date.today() + datetime.timedelta(days=1)).strftime('%Y-%m-%d')
  return start_date, end_date

# function to fetch my portfolio csv
def get_mypfs_df():
  mypfs_df = pd.read_csv('https://raw.githubusercontent.com/ankit-rathi/Tradevesting_v1/main/data/myPortfolioStocks.csv')
  return mypfs_df

# function to fetch my prospects csv
def get_mypps_df():
  mypps_df = pd.read_csv('https://raw.githubusercontent.com/ankit-rathi/Tradevesting_v1/main/data/myProspectsScrips.csv')
  return mypps_df

# function to fetch screener data
def get_myscreen_df():
  myscreen_df = pd.read_csv('https://raw.githubusercontent.com/ankit-rathi/Tradevesting_v1/main/data/myScreenerDB.csv')
  return myscreen_df

# function to fetch momentum data
def get_myinvmt_df():
  myinvmt_df = pd.read_csv('https://raw.githubusercontent.com/ankit-rathi/Tradevesting_v1/main/data/myInvestments.csv')
  return myinvmt_df

# function to get the stock ids
def get_stock_ids(df_pf):
  stock_n100 = df_pf['Symbol'].unique()

  exclude = ['CADILAHC','MMTC', 'MASFIN']

  stock_ids = df_pf[~df_pf['Symbol'].isin(exclude) ]['Symbol'].unique()

  #mypf = mypf[mypf.Forecast.notnull()]
  #stock_ids = mypf['Symbol'].unique()

  #stock_ids.sort()
  return stock_ids

# get features from screener data
def get_screener_features():
  myscreen_df = get_myscreen_df()
  cols = ['Symbol', 'EPS', 'MedPE', 'ROCE%', 'ROE%', 'CapType']
  return myscreen_df[cols]

# get relative strength
def get_relative_strength(stock_list):

    # Dictionary to store stock tickers and their corresponding percentage price change
    stock_changes = {}

    # Loop through each stock and fetch its price data
    for stock in stock_list:
        try:
            # Download the stock data for the given date range
            stock_data = yfin.Ticker(stock + '.NS').history(period='1mo', interval='1d')[map(str.title, ['open', 'close', 'low', 'high', 'volume'])]

            # Calculate the percentage change for the stock
            if len(stock_data) > 0:
                start_price = stock_data['Close'].iloc[0]
                end_price = stock_data['Close'].iloc[-1]
                percent_change = round(((end_price - start_price) / start_price) * 100, 2)
                stock_changes[stock] = percent_change
            else:
                stock_changes[stock] = np.nan  # If no data is available, set to NaN

        except Exception as e:
            print(f"Error fetching data for {stock}: {e}")
            stock_changes[stock] = np.nan

    # Create a DataFrame with stock tickers and their percentage changes
    df = pd.DataFrame(list(stock_changes.items()), columns=['Symbol', 'Percent_Change'])

    # Drop any stocks with missing data (NaN values)
    df = df.dropna()

    # Calculate the percentile rank based on percentage change
    df['RSP'] = round(df['Percent_Change'].rank(pct=True) * 100, 2)
    cols = ['Symbol', 'RSP']
    df = df[cols]
    # Sort by percentile rank (optional)
    df = df.sort_values(by='RSP', ascending=False).reset_index(drop=True)

    return df

In [6]:
# function to get stock technicals
def stock_prec_dev(stock_symbol):
    #stock_symbol = 'ULTRACEMCO.NS'
    short_window = 20
    mid_window = 50
    long_window = 200
    moving_avg = 'SMA'

    start = datetime.datetime(*map(int, start_date.split('-')))
    end = datetime.datetime(*map(int, end_date.split('-')))

    stock_df = yfin.Ticker(stock_symbol + '.NS').history(period='max', interval='1d')[map(str.title, ['open', 'close', 'low', 'high', 'volume'])]

    stock_df['Max'] = round(max(stock_df['Close']),2)
    stock_df = stock_df[(stock_df.index <= end_date) & (stock_df.index >= start_date)]
    stock_df['200_SMA'] = round(stock_df['Close'].rolling(window = 200, min_periods = 1).mean(),0)
    stock_df['Dev%_200'] = round((stock_df['Close'] - stock_df['200_SMA'])*100/stock_df['200_SMA'],2)
    stock_df.dropna(axis = 0, inplace = True) # remove any null rows

    stock_df['20_SMA'] = stock_df['Close'].rolling(window=20).mean()
    stock_df['50_SMA'] = stock_df['Close'].rolling(window=50).mean()
    stock_df['Symbol'] = stock_symbol

    stock_df['Close'] = round(stock_df['Close'],2)
    stock_df['Min'] = round(min(stock_df['Close']),2)
    stock_df['RSI_14'] = ta.momentum.RSIIndicator(close=stock_df['Close'], window=14).rsi()
    stock_df['RSI_14'] = round(stock_df['RSI_14'],0)
    stock_df['Prev_Close'] = stock_df['Close'].shift(1)
    stock_df.drop(['Open', 'Low', 'High', 'Volume'], axis=1, inplace=True)
    stock_df = stock_df.tail(1)

    max_SMA = max(stock_df['20_SMA'].item(), stock_df['50_SMA'].item(), stock_df['200_SMA'].item())
    min_SMA = min(stock_df['20_SMA'].item(), stock_df['50_SMA'].item(), stock_df['200_SMA'].item())
    ABS_Spread = max_SMA - min_SMA
    stock_df['Spread%'] = round((ABS_Spread / stock_df['200_SMA'].item()) * 100,2)

    return stock_df

# function to compute stock attributes
def get_common_features(stock_ids, df_mypf):

  df_prec_dev = pd.DataFrame()
  df_tmp = get_screener_features()
  df_rs = get_relative_strength(stock_ids)

  for stock_id in stock_ids:
      tmp = stock_prec_dev(stock_id)
      tmp = tmp.reset_index()
      df_prec_dev = pd.concat([df_prec_dev, tmp], ignore_index = True)
  df_prec_dev = pd.merge(df_prec_dev, df_mypf, on= 'Symbol')
  df_prec_dev = pd.merge(df_prec_dev, df_tmp, on= 'Symbol', how='left')
  df_prec_dev = pd.merge(df_prec_dev, df_rs, on= 'Symbol', how='left')
  #print(df_prec_dev.columns)
  df_prec_dev['Curr_PE'] = round(df_prec_dev['Close']/df_prec_dev['EPS'],1)
  df_prec_dev['Dev%_PE'] = round((df_prec_dev['Curr_PE'] - df_prec_dev['MedPE'])*100/df_prec_dev['MedPE'],2)
  df_prec_dev['Conviction'] = df_prec_dev['Conviction'] + '-' + df_prec_dev['CapType']
  return df_prec_dev

# function to arrange stock features
def arrange_features(df_stocks, common_cols, diff_cols):
  df_stocks_common = df_stocks[common_cols].drop_duplicates()
  df_stocks_diff = df_stocks[diff_cols]
  df_stocks_diff['Investment'] = df_stocks_diff['AvgCost'] * df_stocks_diff['Shares']
  df_stocks_diff = df_stocks_diff.groupby(['Symbol'])[['Shares', 'Investment']].aggregate(['sum']).reset_index()
  df_stocks_diff.columns = ['Symbol', 'Shares', 'Investment']
  df_stocks_diff['AvgCost'] = round(df_stocks_diff['Investment']/df_stocks_diff['Shares'],2)
  df_stocks = pd.merge(df_stocks_diff, df_stocks_common, on='Symbol')
  return df_stocks

# plot fact distribution across dimension
def plot_pie_chart(df, dimension, fact):
  # grouping the data by category and calculating the sum of fact for each type
  grouped_data = df.groupby(dimension)[fact].sum()

  # sorting the grouped data in descending order
  grouped_data = grouped_data.sort_values(ascending=False)

  # creating a pie chart
  grouped_data.plot.pie(autopct='%1.1f%%', startangle=90, figsize=(6, 6))

  # adding a title and displaying the plot
  plt.title(f'{dimension} {fact} Distribution')
  plt.ylabel('')  # To hide the y-label
  plt.show()

In [7]:
# function to get portfolio features

def get_portfolio_features(df_common_features):

  print_date_time()
  print('-------------------')

  #df_common_features["Target"] = df_common_features["Target"].fillna(df_common_features["Max"])
  df_common_features['NTT'] = np.where(df_common_features['Strategy']== 'NTT', df_common_features["Target"], df_common_features['Max'])
  df_common_features['LTT'] = np.where(df_common_features['Strategy']== 'BTT', df_common_features["Target"], df_common_features['Max'])
  df_common_features['BOL'] = df_common_features['Min']

  tmp_df = df_common_features[df_common_features['Symbol'].isin(mypf_df[mypf_df['InPortfolio'] != 'NA'].Symbol.values)]
  print('qualified stocks: '+str(len(tmp_df['Symbol'].unique())))
  tmp_df1 = tmp_df[tmp_df['LatestQtr'] == 1]
  print('with latest results: '+str(len(tmp_df1['Symbol'].unique())))
  tmp_df1 = tmp_df1[tmp_df1['StarStock'] == 1]
  print('still star stocks: '+str(len(tmp_df1['Symbol'].unique())))
  tmp_df['Investment'] = tmp_df['AvgCost'] * tmp_df['Shares']
  tmp_df['Current'] = round(tmp_df['Close'] * tmp_df['Shares'],0)
  tmp_df['Previous'] = tmp_df['Prev_Close'] * tmp_df['Shares']
  tmp_df['EstimatedST'] = tmp_df['NTT'] * tmp_df['Shares']
  tmp_df['EstimatedLT'] = tmp_df['LTT'] * tmp_df['Shares']
  tmp_df['Current P/L'] = round((tmp_df['Current'] - tmp_df['Investment']),0)
  tmp_df['Today P/L%'] = round((tmp_df['Current'] - tmp_df['Previous'])*100/tmp_df['Previous'],2)
  tmp_df['Current P/L%'] = round((tmp_df['Current'] - tmp_df['Investment'])*100/tmp_df['Investment'],2)
  tmp_df['EstimatedST P/L%'] = round((tmp_df['EstimatedST'] - tmp_df['Investment'])*100/tmp_df['Investment'],2)
  tmp_df['EstimatedLT P/L%'] = round((tmp_df['EstimatedLT'] - tmp_df['Investment'])*100/tmp_df['Investment'],2)
  tmp_df['NTT%'] = round((tmp_df['NTT'] - tmp_df['Close'])*100/tmp_df['Close'],2)
  tmp_df['LTT%'] = round((tmp_df['LTT'] - tmp_df['Close'])*100/tmp_df['Close'],2)
  tmp_df['Gained%'] = round((tmp_df['Close'] - tmp_df['BOL'])*100/tmp_df['BOL'],2)
  investment = round(sum(tmp_df['AvgCost']*tmp_df['Shares']),0)
  current = round(sum(tmp_df['Close']*tmp_df['Shares']),0)
  tmp_df['InitAlloc%'] = round(tmp_df['Investment']*100/investment,2)
  tmp_df['CurrAlloc%'] = round(tmp_df['Current']*100/current,2)
  tmp_df['FTT'] = tmp_df['LTT']
  tmp_df.loc[tmp_df['Strategy'] == 'NTT', 'FTT'] = tmp_df['NTT']
  tmp_df['FTT%'] = tmp_df['LTT%']
  tmp_df.loc[tmp_df['Strategy'] == 'NTT', 'FTT%'] = tmp_df['NTT%']
  tmp_df['FTT Amt'] = round(tmp_df['FTT%'] * tmp_df['Current']/100,0)
  tmp_df['OTT%'] = round((tmp_df['FTT'] - tmp_df['AvgCost'])*100/tmp_df['AvgCost'],2)
  tmp_df['RRR Ind'] = round(tmp_df['Current P/L']/tmp_df['FTT Amt'],2)
  tmp_df['Risk Ind'] = round(tmp_df['Current P/L%']*tmp_df['CurrAlloc%'],0)

  return tmp_df

# function to print portfolio features
def print_portfolio_stats(df_portfolio_features, myinvmt_df):
  from pyxirr import xirr

  total_booked_amt, reserve_amt, cy_booked_amt, py_booked_amt = get_amt()

  dates = myinvmt_df['Date'].values
  dates = np.append(dates, datetime.date.today().strftime('%d-%b-%y'))
  investment = myinvmt_df['Investment'].values
  dates= pd.to_datetime(dates)

  current = round(sum(df_portfolio_features['Close']*df_portfolio_features['Shares']),0) + reserve_amt
  investment_xirr = np.append(investment, current)
  cagr = round(xirr(pd.DataFrame({"dates": dates, "amounts": investment_xirr}))*100,2)

  investment = -sum(investment)
  invested = round(sum(df_portfolio_features['AvgCost']*df_portfolio_features['Shares']),0) + reserve_amt
  previous = round(sum(df_portfolio_features['Prev_Close']*df_portfolio_features['Shares']),0) + reserve_amt
  cy_invested = investment + py_booked_amt

  today_pnl_amount = current-previous
  today_pnl_percentage = round((current-previous)*100/previous,2)

  curr_pnl_amount = current-invested
  curr_pnl_percentage = round((curr_pnl_amount)*100/(cy_invested),2)

  cy_pnl_amount = cy_booked_amt + curr_pnl_amount
  cy_pnl_percentage = round((cy_pnl_amount)*100/cy_invested,2)

  overall_pnl_amount = total_booked_amt + curr_pnl_amount
  overall_pnl_percentage = round((overall_pnl_amount)*100/investment,2)

  estimate_st = round(sum(df_portfolio_features['FTT']*df_portfolio_features['Shares']),0)  + reserve_amt
  est_st_pnl_amount = estimate_st-current
  est_st_pnl_percentage = round((est_st_pnl_amount)*100/current,2)

  estimate_lt = round(sum(df_portfolio_features['LTT']*df_portfolio_features['Shares']),0)  + reserve_amt
  est_lt_pnl_amount = estimate_lt-current
  est_lt_pnl_percentage = round((est_lt_pnl_amount)*100/current,2)

  total_profit = round(sum(df_portfolio_features[df_portfolio_features['Current P/L%'] > 0]['Current']) - sum(df_portfolio_features[df_portfolio_features['Current P/L%'] > 0]['Investment']),0)
  total_loss = round(sum(df_portfolio_features[df_portfolio_features['Current P/L%'] < 0]['Current']) - sum(df_portfolio_features[df_portfolio_features['Current P/L%'] < 0]['Investment']),0)

  cy_booked_percentage = round((cy_booked_amt)*100/current,2)
  py_booked_percentage = round((py_booked_amt)*100/investment,2)
  total_booked_percentage = round((total_booked_amt)*100/investment,2)

  print('-------------------')
  print('Initial Investment: ', format_amt(investment))
  print('CY Investment: ', format_amt(cy_invested))
  print('Reserve: ', format_amt(reserve_amt))
  print('Current: ',  format_amt(current))
  print('-------------------')
  print('Today PnL: '+ '{} ({}%)'.format(format_amt(today_pnl_amount), today_pnl_percentage))
  print('Current PnL: '+ '{} ({}%)'.format(format_amt(curr_pnl_amount), curr_pnl_percentage))
  print('CY Booked + Current PnL: '+ '{} ({}%)'.format(format_amt(cy_pnl_amount), cy_pnl_percentage))
  print('-------------------')
  print('Total profit: ', format_amt(total_profit))
  print('Total loss: ', format_amt(total_loss))
  print('-------------------')
  print('Total Booked + Current PnL: '+ '{} ({}%)'.format(format_amt(overall_pnl_amount), overall_pnl_percentage))
  print('Total Booked PnL: '+ '{} ({}%)'.format(format_amt(total_booked_amt), total_booked_percentage))
  print('Curr Year Booked PnL: '+ '{} ({}%)'.format(format_amt(cy_booked_amt), cy_booked_percentage))
  print('Prev Year Booked PnL: '+ '{} ({}%)'.format(format_amt(py_booked_amt), py_booked_percentage))
  print('===================')
  print('Est FTT: ',  format_amt(estimate_st))
  print('Est FTT PnL: '+ '{} ({}%)'.format(format_amt(est_st_pnl_amount), est_st_pnl_percentage))

  print('===================')
  print('Deployed: ', format_amt(investment))

  print('Current: ', format_amt(current))

  print('CAGR/XIRR %: '+'{}%'.format(cagr))

In [8]:
# get start and end date
start_date, end_date = get_start_end_date()

# get portfolio and prospects data
mypfs_df = get_mypfs_df()
mypps_df = get_mypps_df()
myinvmt_df = get_myinvmt_df()

# merge above datasets
mypf_df = pd.merge(mypfs_df, mypps_df, on="Symbol")

# seggregate dm and sv portfolio
dm_pf = mypf_df[mypf_df['InPortfolio'] == 'DM']
sv_pf = mypf_df[mypf_df['InPortfolio'] == 'SV']

# build portfolio stock dataframe
dm_stocks = get_stock_ids(dm_pf)
sv_stocks = get_stock_ids(sv_pf)
df_stocks = pd.concat([dm_pf,sv_pf], ignore_index = True)

# arrange common and diff stock features
common_cols = ['Symbol', 'Target', 'Criteria', 'Strategy', 'CumlRnk', 'LatestQtr', 'StarStock', 'Conviction', 'Category', 'InFolio', 'XIRR', 'MBQ']
diff_cols = ['Symbol', 'AvgCost', 'Shares']
df_stocks = arrange_features(df_stocks, common_cols, diff_cols)

# get common features
stock_ids = df_stocks['Symbol'].values
df_common_features = get_common_features(stock_ids, df_stocks)

df_common_features.reset_index(drop=True, inplace=True)
df_common_features.drop(['Date'], axis=1, inplace=True)
# get and print portfolio features
df_portfolio_features = get_portfolio_features(df_common_features)

print_portfolio_stats(df_portfolio_features, myinvmt_df)

df = df_portfolio_features
#plot_pie_chart(df, 'CapType', 'Current')
list_ox40n = list(df[df['MBQ'].str.contains('OX40N', na=False)]['Symbol'].values)

Run date time (IST): 2026-08-25 13:12:33
-------------------
qualified stocks: 87
with latest results: 30
still star stocks: 19

-------------------
Initial Investment:  1.46 C
CY Investment:  1.89 C
Reserve:  3.69 L
Current:  1.57 C
-------------------
Today PnL: -91.53 K (-0.58%)
Current PnL: -36.07 L (-19.09%)
CY Booked + Current PnL: -31.01 L (-16.41%)
-------------------
Total profit:  3.51 L
Total loss:  -39.57 L
-------------------
Total Booked + Current PnL: 11.86 L (8.12%)
Total Booked PnL: 47.93 L (32.82%)
Curr Year Booked PnL: 5.06 L (3.23%)
Prev Year Booked PnL: 42.87 L (29.35%)
===================
Est FTT:  2.67 C
Est FTT PnL: 1.10 C (70.24%)
===================
Deployed:  1.46 C
Current:  1.57 C
CAGR/XIRR %: 3.21%

In [9]:
# top 5 near their targets
cols = ['Symbol', 'Today P/L%', 'Current P/L%', 'FTT%', 'OTT%', 'FTT Amt', 'Current P/L', 'Current', 'FTT', 'Dev%_PE', 'RSI_14','Conviction', 'Spread%',  'CumlRnk', 'RRR Ind', 'CurrAlloc%', 'Gained%', 'Criteria', 'Strategy', 'Category']
df_tmp = df_portfolio_features[~df_portfolio_features['Symbol'].isin(['ENRIN','BLUSPRING','DIGITIDE'])]
df_tmp = df_tmp.sort_values(by = 'FTT Amt', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
66,SIEMENS,-0.40,10.09,0.67,10.83,1373.0,18780.0,204875.0,4125.00,-10.89,68.0,H-LC,15.24,51.0,13.68,1.34,44.55,AR,NTT,ELECTRICAL
78,UNITDSPR,-0.51,13.71,6.20,20.77,16508.0,32112.0,266256.0,1644.00,-3.00,63.0,X-MC,12.13,64.0,1.95,1.74,27.99,X40N,NTT,BREWERIES
77,TTKPRESTIG,0.41,-22.78,29.62,0.09,23051.0,-22956.0,77821.0,770.00,-6.01,43.0,M-SC,8.57,250.0,-1.00,0.51,40.07,OX40N,NTT,DURABLES
52,M&M,-0.03,7.78,10.24,18.82,26563.0,18722.0,259403.0,3762.88,-6.96,57.0,X-LC,5.12,25.0,0.70,1.69,17.67,X40N,ATH,AUTO
67,SIS,-0.53,-4.56,27.06,21.26,28674.0,-5067.0,105965.0,528.00,103.76,40.0,H-SC,20.05,168.0,-0.18,0.69,57.55,OX40N,NTT,MISC

In [10]:
# top 5 today
df_tmp = df_portfolio_features.sort_values(by = 'Today P/L%', ascending=False)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
6,AWL,5.26,-29.73,137.66,67.02,344692.0,-105915.0,250394.0,485.00,-48.08,68.0,X-SC,7.66,81.0,-0.31,1.63,19.06,XY24,NTT,FMCG
18,COFFEEDAY,4.47,-48.63,163.33,35.27,95270.0,-55219.0,58330.0,80.00,NaN,48.0,NaN,3.24,266.0,-0.58,0.38,43.84,XR,NTT,HOTELS
63,ROUTE,1.20,-61.42,330.95,66.28,169920.0,-81723.0,51343.0,2190.73,NaN,41.0,NaN,6.57,141.0,-0.48,0.34,23.70,SR,ATH,IT
68,STARHEALTH,0.98,13.04,30.27,47.26,96191.0,36655.0,317778.0,761.00,-0.37,51.0,H-SC,15.69,173.0,0.38,2.07,37.40,XY24,NTT,INSURANCE
27,GLAXO,0.63,18.43,14.58,35.69,34410.0,36724.0,236008.0,3380.16,-11.20,71.0,X-MC,12.80,56.0,1.07,1.54,40.27,X40,ATH,PHARMA

In [11]:
# bottom 5 today
df_tmp = df_portfolio_features.sort_values(by = 'Today P/L%', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
69,SURYODAY,-4.74,-13.81,42.75,23.03,65979.0,-24735.0,154336.0,216.00,-29.23,37.0,H-SC,14.83,166.0,-0.37,1.01,31.00,XR,NTT,BANKS
12,BOSCH-HCIL,-3.41,-26.98,36.93,-0.01,34465.0,-34481.0,93324.0,2282.00,725.72,61.0,M-SC,11.92,231.0,-1.00,0.61,58.85,OX40N,BTT,AC
25,FINCABLES,-3.16,58.42,31.24,107.91,73070.0,86256.0,233900.0,1641.55,15.40,61.0,M-SC,24.86,220.0,1.18,1.53,75.97,OX40N,ATH,CABLES
70,SYMPHONY,-2.86,-54.46,119.50,-0.03,93144.0,-93196.0,77945.0,1306.00,NaN,27.0,NaN,17.21,205.0,-1.00,0.51,0.00,OX40N,NTT,DURABLES
29,GREENPANEL,-2.80,-58.30,243.22,43.14,185703.0,-106726.0,76352.0,537.00,NaN,23.0,NaN,13.61,225.0,-0.57,0.50,0.00,XY24,NTT,MISC

In [12]:
# top 5 to exit based on CumlRnk
df_tmp = df_portfolio_features[~df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])]
df_tmp = df_tmp[(df_tmp['Current P/L%'] > -1) & (df_tmp['Current P/L%'] < 1)].sort_values(by = 'CumlRnk', ascending=False)
df_tmp[cols].head()

Empty DataFrame
Columns: [Symbol, Today P/L%, Current P/L%, FTT%, OTT%, FTT Amt, Current P/L, Current, FTT, Dev%_PE, RSI_14, Conviction, Spread%, CumlRnk, RRR Ind, CurrAlloc%, Gained%, Criteria, Strategy, Category]
Index: []

In [13]:
# OX40N stocks to exit
df_tmp = df_portfolio_features[(df_portfolio_features['Symbol'].isin(list_ox40n))].sort_values(by = 'Current P/L%', ascending=False)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
25,FINCABLES,-3.16,58.42,31.24,107.91,73070.0,86256.0,233900.0,1641.55,15.40,61.0,M-SC,24.86,220.0,1.18,1.53,75.97,OX40N,ATH,CABLES
67,SIS,-0.53,-4.56,27.06,21.26,28674.0,-5067.0,105965.0,528.00,103.76,40.0,H-SC,20.05,168.0,-0.18,0.69,57.55,OX40N,NTT,MISC
43,INDIGOPNTS,-1.28,-19.22,23.82,0.02,33586.0,-33559.0,141000.0,1408.00,-22.93,57.0,M-SC,8.34,222.0,-1.00,0.92,59.97,OX40N,NTT,PAINTS
77,TTKPRESTIG,0.41,-22.78,29.62,0.09,23051.0,-22956.0,77821.0,770.00,-6.01,43.0,M-SC,8.57,250.0,-1.00,0.51,40.07,OX40N,NTT,DURABLES
16,CERA,-0.27,-23.52,61.98,23.89,83387.0,-41365.0,134538.0,9475.00,NaN,42.0,NaN,12.91,153.0,-0.50,0.88,30.78,OX40N,NTT,CERAMICS

In [14]:
# top 5 to book for rotation
df_tmp = df_portfolio_features[(df_portfolio_features['Current P/L%'] > 20) ].sort_values(by = 'CumlRnk', ascending=False)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
25,FINCABLES,-3.16,58.42,31.24,107.91,73070.0,86256.0,233900.0,1641.55,15.4,61.0,M-SC,24.86,220.0,1.18,1.53,75.97,OX40N,ATH,CABLES

In [15]:
# top 5 to monitor for exit
df_tmp = df_portfolio_features[~df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])]
df_tmp = df_tmp[(df_tmp['Current P/L%'] > 0) ].sort_values(by = 'Dev%_PE', ascending=False)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
25,FINCABLES,-3.16,58.42,31.24,107.91,73070.0,86256.0,233900.0,1641.55,15.40,61.0,M-SC,24.86,220.0,1.18,1.53,75.97,OX40N,ATH,CABLES
68,STARHEALTH,0.98,13.04,30.27,47.26,96191.0,36655.0,317778.0,761.00,-0.37,51.0,H-SC,15.69,173.0,0.38,2.07,37.40,XY24,NTT,INSURANCE

In [16]:
# top 5 to book for rotation from weak conviction
df_tmp = df_portfolio_features[~df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])]
df_tmp = df_tmp[~df_tmp['Criteria'].isin(['XY25','XY24','X40', 'X40N'])].sort_values(by = 'RRR Ind', ascending=False)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
25,FINCABLES,-3.16,58.42,31.24,107.91,73070.0,86256.0,233900.0,1641.55,15.40,61.0,M-SC,24.86,220.0,1.18,1.53,75.97,OX40N,ATH,CABLES
3,ALKYLAMINE,-0.33,-12.86,120.96,92.54,106418.0,-12985.0,87978.0,4520.85,NaN,66.0,NaN,16.20,142.0,-0.12,0.57,67.06,SR,ATH,CHEMICALS
67,SIS,-0.53,-4.56,27.06,21.26,28674.0,-5067.0,105965.0,528.00,103.76,40.0,H-SC,20.05,168.0,-0.18,0.69,57.55,OX40N,NTT,MISC
42,INDIAMART,0.61,-24.51,166.16,100.92,154703.0,-30231.0,93105.0,4675.60,NaN,41.0,NaN,13.30,140.0,-0.20,0.61,1.29,AR,ATH,MISC
71,TANLA,-1.54,-37.20,245.93,117.25,418189.0,-100717.0,170044.0,1922.32,NaN,40.0,NaN,14.58,147.0,-0.24,1.11,48.88,AR,ATH,IT

In [17]:
# top 5 to accumulate based on lowest RSI_14
df_tmp = df_portfolio_features[df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])].sort_values(by = 'RSI_14', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
56,PGHH,-0.23,-39.24,117.26,32.01,152128.0,-83784.0,129736.0,17616.87,-55.32,23.0,X-SC,20.05,57.0,-0.55,0.85,0.00,X40,ATH,FMCG
20,DABUR,-1.49,-23.26,87.26,43.70,166110.0,-57706.0,190362.0,735.00,-33.80,29.0,X-MC,10.80,70.0,-0.35,1.24,0.00,XY24,BTT,FMCG
55,PAGEIND,-0.92,-8.31,44.89,32.85,110468.0,-22294.0,246085.0,50936.07,-31.87,29.0,X-MC,8.49,55.0,-0.20,1.61,17.51,X40,ATH,APPARELS
19,COLPAL,-1.06,-29.03,97.08,39.86,181443.0,-76465.0,186900.0,3683.41,-14.08,30.0,X-MC,2.87,62.0,-0.42,1.22,5.72,XY25,ATH,FMCG
75,TMPV,-0.83,-25.82,92.43,42.75,285315.0,-107425.0,308682.0,600.00,-84.91,30.0,X-LC,4.50,4.0,-0.38,2.02,6.14,XY24,NTT,AUTO

In [18]:
# top 5 to accumulate based on Spread and CumlRnk
df_tmp = df_portfolio_features[df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])]
df_tmp = df_tmp[(df_tmp['CumlRnk'] < 100)].sort_values(by = 'Spread%', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
50,KOTAKBANK,-0.68,5.14,13.10,18.92,33016.0,12330.0,252032.0,452.46,-11.03,59.0,X-LC,2.12,12.0,0.37,1.65,13.40,X40,ATH,BANKS
1,ABBOTINDIA,0.00,-11.37,30.17,15.37,47825.0,-20335.0,158520.0,34390.26,-27.79,39.0,X-MC,2.24,58.0,-0.43,1.03,7.38,X40,ATH,PHARMA
23,DMART,-0.34,-4.29,37.31,31.42,111338.0,-13376.0,298414.0,5391.45,-19.77,43.0,X-LC,2.29,14.0,-0.12,1.95,7.68,X40N,ATH,FMCG
19,COLPAL,-1.06,-29.03,97.08,39.86,181443.0,-76465.0,186900.0,3683.41,-14.08,30.0,X-MC,2.87,62.0,-0.42,1.22,5.72,XY25,ATH,FMCG
53,MARUTI,-0.45,-1.68,26.78,24.64,65095.0,-4166.0,243072.0,17120.06,-7.53,41.0,X-LC,3.82,33.0,-0.06,1.59,10.84,XR,ATH,AUTO

In [19]:
# top 5 to accumulate based on lowest Gained%
df_tmp = df_portfolio_features[df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])].sort_values(by = 'Gained%', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
20,DABUR,-1.49,-23.26,87.26,43.70,166110.0,-57706.0,190362.0,735.00,-33.80,29.0,X-MC,10.80,70.0,-0.35,1.24,0.00,XY24,BTT,FMCG
36,HINDUNILVR,-0.73,-16.17,45.01,21.56,126980.0,-54403.0,282114.0,2922.00,-42.16,38.0,X-LC,7.00,9.0,-0.43,1.84,0.00,XY25,NTT,FMCG
56,PGHH,-0.23,-39.24,117.26,32.01,152128.0,-83784.0,129736.0,17616.87,-55.32,23.0,X-SC,20.05,57.0,-0.55,0.85,0.00,X40,ATH,FMCG
34,HDFCBANK,-0.65,-11.54,48.15,31.05,124844.0,-33838.0,259282.0,1073.00,-28.50,37.0,X-LC,12.61,26.0,-0.27,1.69,0.64,X40,BTT,BANKS
47,ITC,-0.11,-25.68,67.78,24.70,200129.0,-102016.0,295262.0,452.00,-30.75,36.0,X-LC,10.71,1.0,-0.51,1.93,0.88,X40,NTT,FMCG

In [20]:
# top 5 to accumulate based on lowest CurrAlloc%
df_tmp = df_portfolio_features[df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])].sort_values(by = 'CurrAlloc%', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
56,PGHH,-0.23,-39.24,117.26,32.01,152128.0,-83784.0,129736.0,17616.87,-55.32,23.0,X-SC,20.05,57.0,-0.55,0.85,0.00,X40,ATH,FMCG
2,ACC,-0.53,-42.09,201.85,74.81,313433.0,-112848.0,155280.0,3906.00,-42.69,37.0,X-SC,11.35,85.0,-0.36,1.01,3.74,XY24,BTT,CEMENT
1,ABBOTINDIA,0.00,-11.37,30.17,15.37,47825.0,-20335.0,158520.0,34390.26,-27.79,39.0,X-MC,2.24,58.0,-0.43,1.03,7.38,X40,ATH,PHARMA
40,ICICIPRULI,-0.64,-15.94,54.97,30.28,91035.0,-31397.0,165608.0,787.27,-46.10,52.0,X-MC,11.59,78.0,-0.34,1.08,10.34,X40,ATH,INSURANCE
39,ICICIGI,0.01,-14.34,38.78,18.89,66478.0,-28686.0,171423.0,2244.41,-14.59,41.0,X-MC,10.12,66.0,-0.43,1.12,2.13,X40,ATH,INSURANCE

In [21]:
# top 5 to accumulate based on CumlRnk
df_tmp = df_portfolio_features.sort_values(by = 'CumlRnk', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
47,ITC,-0.11,-25.68,67.78,24.70,200129.0,-102016.0,295262.0,452.00,-30.75,36.0,X-LC,10.71,1.0,-0.51,1.93,0.88,X40,NTT,FMCG
73,TCS,-0.38,-33.20,85.93,24.20,265914.0,-153819.0,309454.0,4230.71,-44.65,46.0,X-LC,13.28,2.0,-0.58,2.02,15.40,X40,ATH,IT
45,INFY,-0.48,-19.94,75.35,40.38,227100.0,-75077.0,301393.0,1972.00,-41.25,48.0,X-LC,15.46,3.0,-0.33,1.97,14.14,X40,NTT,IT
75,TMPV,-0.83,-25.82,92.43,42.75,285315.0,-107425.0,308682.0,600.00,-84.91,30.0,X-LC,4.50,4.0,-0.38,2.02,6.14,XY24,NTT,AUTO
33,HCLTECH,-1.85,-13.22,42.85,23.97,115087.0,-40904.0,268582.0,1853.42,-15.52,49.0,X-LC,9.73,8.0,-0.36,1.75,26.74,X40,ATH,IT

In [22]:
# top 5 for average up
df_tmp = df_portfolio_features[(df_portfolio_features['Dev%_200'] > 5)].sort_values(by = 'CurrAlloc%', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
44,INDUSINDBK,-0.01,-25.77,79.02,32.89,45290.0,-19892.0,57314.0,1800.00,322.36,48.0,L-MC,11.91,258.0,-0.44,0.37,41.30,XR,NTT,BANKS
30,HAPPSTMNDS,-2.07,-45.65,236.86,83.08,164987.0,-58509.0,69656.0,1466.54,NaN,65.0,NaN,6.69,152.0,-0.35,0.45,30.47,AR,ATH,IT
3,ALKYLAMINE,-0.33,-12.86,120.96,92.54,106418.0,-12985.0,87978.0,4520.85,NaN,66.0,NaN,16.20,142.0,-0.12,0.57,67.06,SR,ATH,CHEMICALS
12,BOSCH-HCIL,-3.41,-26.98,36.93,-0.01,34465.0,-34481.0,93324.0,2282.00,725.72,61.0,M-SC,11.92,231.0,-1.00,0.61,58.85,OX40N,BTT,AC
81,VALIANTORG,-2.56,-38.70,184.12,74.15,184641.0,-63322.0,100283.0,838.00,NaN,50.0,NaN,10.22,145.0,-0.34,0.65,49.24,XR,NTT,CHEMICALS

In [23]:
# top 5 RSP
df_tmp = df_portfolio_features.sort_values(by = 'RSP', ascending=False)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
25,FINCABLES,-3.16,58.42,31.24,107.91,73070.0,86256.0,233900.0,1641.55,15.40,61.0,M-SC,24.86,220.0,1.18,1.53,75.97,OX40N,ATH,CABLES
12,BOSCH-HCIL,-3.41,-26.98,36.93,-0.01,34465.0,-34481.0,93324.0,2282.00,725.72,61.0,M-SC,11.92,231.0,-1.00,0.61,58.85,OX40N,BTT,AC
27,GLAXO,0.63,18.43,14.58,35.69,34410.0,36724.0,236008.0,3380.16,-11.20,71.0,X-MC,12.80,56.0,1.07,1.54,40.27,X40,ATH,PHARMA
38,HYUNDAI,0.23,14.41,25.80,43.94,74190.0,36228.0,287560.0,2782.73,18.51,63.0,X-LC,6.85,29.0,0.49,1.88,32.03,X40N,ATH,AUTO
81,VALIANTORG,-2.56,-38.70,184.12,74.15,184641.0,-63322.0,100283.0,838.00,NaN,50.0,NaN,10.22,145.0,-0.34,0.65,49.24,XR,NTT,CHEMICALS

In [24]:
# Top N allocation
df_tmp = df_portfolio_features.sort_values(by = 'CurrAlloc%', ascending=False)
top_n_values = [10, 25, 50]

sum_df = pd.DataFrame({
    'Top_N': top_n_values,
    'Sum_Alloc%': [df_tmp['CurrAlloc%'].head(n).sum() for n in top_n_values]
})

sum_df

   Top_N  Sum_Alloc%
0     10       19.71
1     25       45.09
2     50       77.71

In [25]:
# market-cap-wise allocation
df_tmp = df_portfolio_features[cols]
df_tmp.groupby(df_tmp['Conviction'].str[-2:])['CurrAlloc%'].sum().sort_values(ascending=False)

Conviction
LC    38.16
MC    22.20
SC    21.64
Name: CurrAlloc%, dtype: float64

In [26]:
# criteria-wise allocation
df_portfolio_features.groupby('Criteria')['CurrAlloc%'].sum().sort_values(ascending=False)

Criteria
X40      26.76
XY24     23.96
X40N     18.72
XR        9.05
OX40N     7.26
XY25      7.18
AR        6.15
SR        0.91
Name: CurrAlloc%, dtype: float64

In [27]:
# conviction-wise allocation
df_portfolio_features.groupby('Conviction')['CurrAlloc%'].sum().sort_values(ascending=False)

Conviction
X-LC    34.41
X-MC    19.63
H-SC     8.53
X-SC     7.73
M-SC     5.38
H-LC     2.94
M-MC     1.17
H-MC     1.03
M-LC     0.81
L-MC     0.37
Name: CurrAlloc%, dtype: float64

In [28]:
# sector-wise stats
df_tmp = df_portfolio_features.groupby('Category')[['CurrAlloc%', 'Current', 'Current P/L', 'FTT Amt']].sum().sort_values(by=['Current', 'Current P/L'], ascending=False)
df_tmp['Current P/L%'] = round(df_tmp['Current P/L'] * 100 / df_tmp['Current'], 2)
df_tmp['FTT%'] = round(df_tmp['FTT Amt'] * 100 / df_tmp['Current'], 2)
cols = ['CurrAlloc%', 'Current P/L%', 'FTT%']
df_tmp[cols].sort_values(by=['CurrAlloc%'], ascending=False)

               CurrAlloc%  Current P/L%    FTT%
Category
FMCG                15.47        -25.78   70.89
IT                  11.21        -38.91  107.81
FINANCE             10.68        -18.07   68.94
AUTO                 8.25         -7.06   45.40
BANKS                6.23        -11.80   60.02
MISC                 5.89        -36.52   91.43
PHARMA               5.87          7.90   18.22
INSURANCE            5.81         -4.32   41.21
PAINTS               5.42        -18.53   38.74
ELECTRICAL           4.27         -8.16   42.02
AC                   1.82        -14.86   46.01
BREWERIES            1.74         12.06    6.20
REFINERIES           1.74        -12.15   49.82
FOOTWEAR             1.66        -73.12  142.54
APPARELS             1.61         -9.06   44.89
CABLES               1.53         36.88   31.24
DURABLES             1.48        -71.05  112.66
TRAVEL               1.42       -106.19  209.43
CERAMICS             1.31        -53.41  100.02
ENGINEERING          1.24        -27.21   85.39
CHEMICALS            1.22        -40.53  154.60
CEMENT               1.01        -72.67  201.85
JEWELLERY            0.94       -121.75  198.80
ENTERTAINMENT        0.70        -78.71  185.29
HEALTHCARE           0.70        -70.11  112.81
TEXTILES             0.39        -53.26   96.96
HOTELS               0.38        -94.67  163.33

In [29]:
# money to be made criteria-wise
df_portfolio_features.groupby('Criteria')['FTT Amt'].agg(['sum', 'count']).sort_values(by='sum', ascending=False)

                sum  count
Criteria
XY24      3653586.0     19
X40       2122615.0     18
XR        1409694.0     13
X40N      1212609.0     12
AR        1063958.0      8
OX40N      679919.0     10
XY25       600943.0      5
SR         276338.0      2

In [30]:
# money to be made conviction-wise
df_portfolio_features.groupby('Conviction')['FTT Amt'].agg(['sum', 'count']).sort_values(by='sum', ascending=False)

                  sum  count
Conviction
X-LC        2457428.0     19
X-MC        1495362.0     14
X-SC        1091365.0      6
H-SC         843341.0      8
M-SC         340545.0      6
H-MC         256458.0      1
M-LC         167462.0      1
M-MC          66574.0      1
L-MC          45290.0      1
H-LC          40733.0      2

In [31]:
# money to be made criteria and conviction-wise
df_portfolio_features.groupby(['Conviction', 'Criteria'])['FTT Amt'].agg(['sum', 'count']).sort_values(by='sum', ascending=False)

                           sum  count
Conviction Criteria
X-LC       X40       1233727.0      9
X-SC       XY24       658125.0      2
H-SC       XY24       525466.0      3
X-MC       X40        515017.0      6
X-LC       XY24       474039.0      2
X-MC       X40N       459028.0      4
X-LC       X40N       425169.0      5
X-MC       XY25       274971.0      2
X-LC       XY25       259398.0      2
X-SC       X40        256565.0      2
H-MC       XY24       256458.0      1
X-MC       XY24       246346.0      2
H-SC       OX40N      222518.0      3
X-SC       X40N       176675.0      2
M-LC       XR         167462.0      1
M-SC       OX40N      164172.0      4
           XY24       118009.0      1
H-SC       XR          95357.0      2
M-MC       XY25        66574.0      1
X-LC       XR          65095.0      1
M-SC       XR          58364.0      1
L-MC       XR          45290.0      1
H-LC       AR          40733.0      2

In [32]:
# notebook execution time

end_time = time.time()
execution_time = round(end_time - start_time, 0)
print(f"Notebook execution time: {execution_time} seconds")

Notebook execution time: 50.0 seconds