<a href="https://colab.research.google.com/github/ankit-rathi/Quantvesting_v2/blob/main/myStocks_Portfolio_Analysis.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
'''
!pip install pandas==2.2.2 -qq
!pip install pyxirr -qq
!pip install ta -qq
!pip install yfinance==0.2.59 -qq
'''

'\n!pip install pandas==2.2.2 -qq\n!pip install pyxirr -qq\n!pip install ta -qq\n!pip install yfinance==0.2.59 -qq\n'

In [2]:
# import libraries

import numpy as np
import pandas as pd
import datetime
import warnings
warnings.filterwarnings('ignore')
import yfinance as yfin
import ta
import matplotlib.pyplot as plt
import requests

In [3]:
# notebook start time
import time
import datetime
import pytz

start_time = time.time()

# function to print date timestamp
def print_date_time():
  tz_NY = pytz.timezone('Asia/Kolkata')
  datetime_NY = datetime.datetime.now(tz_NY)
  print("Run date time (IST):", datetime_NY.strftime("%Y-%m-%d %H:%M:%S"))

In [4]:
# function to get booked and reserved amount
def get_amt():
  # fetch the JSON data from the URL
  url = "https://raw.githubusercontent.com/ankit-rathi/Tradevesting_v1/main/data/myPortfolioAmts.json"
  response = requests.get(url)
  pf_amts = response.json()  # parse the JSON data

  # extract values from the JSON
  py_booked_amt_dm = pf_amts["py_booked_amt_dm"]
  py_booked_amt_sv = pf_amts["py_booked_amt_sv"]
  cy_booked_amt_dm = pf_amts["cy_booked_amt_dm"]
  cy_booked_amt_sv = pf_amts["cy_booked_amt_sv"]
  reserve_amt_dm = pf_amts["reserve_amt_dm"]
  reserve_amt_sv = pf_amts["reserve_amt_sv"]

  # perform calculations
  py_booked_amt = py_booked_amt_dm + py_booked_amt_sv
  cy_booked_amt = cy_booked_amt_dm + cy_booked_amt_sv
  reserve_amt = reserve_amt_dm + reserve_amt_sv
  total_booked_amt = py_booked_amt + cy_booked_amt

  return total_booked_amt, reserve_amt, cy_booked_amt, py_booked_amt

gen_output = 0

In [5]:
# function to format the amount
def format_amt(number):
    abs_number = abs(number)

    if abs_number >= 1_00_00_000:  # Crores
        formatted_amt = f"{number / 1_00_00_000:.2f} C"
    elif abs_number >= 1_00_000:  # Lakhs
        formatted_amt = f"{number / 1_00_000:.2f} L"
    elif abs_number >= 1_000:  # Thousands
        formatted_amt = f"{number / 1_000:.2f} K"
    else:
        formatted_amt = f"{number:.2f}"

    return formatted_amt

# function to set start and end date
def get_start_end_date():
  start_date = (datetime.date.today() + datetime.timedelta(days=-365)).strftime('%Y-%m-%d')
  end_date = (datetime.date.today() + datetime.timedelta(days=1)).strftime('%Y-%m-%d')
  return start_date, end_date

# function to fetch my portfolio csv
def get_mypfs_df():
  mypfs_df = pd.read_csv('https://raw.githubusercontent.com/ankit-rathi/Tradevesting_v1/main/data/myPortfolioStocks.csv')
  return mypfs_df

# function to fetch my prospects csv
def get_mypps_df():
  mypps_df = pd.read_csv('https://raw.githubusercontent.com/ankit-rathi/Tradevesting_v1/main/data/myProspectsScrips.csv')
  return mypps_df

# function to fetch screener data
def get_myscreen_df():
  myscreen_df = pd.read_csv('https://raw.githubusercontent.com/ankit-rathi/Tradevesting_v1/main/data/myScreenerDB.csv')
  return myscreen_df

# function to fetch momentum data
def get_myinvmt_df():
  myinvmt_df = pd.read_csv('https://raw.githubusercontent.com/ankit-rathi/Tradevesting_v1/main/data/myInvestments.csv')
  return myinvmt_df

# function to get the stock ids
def get_stock_ids(df_pf):
  stock_n100 = df_pf['Symbol'].unique()

  exclude = ['CADILAHC','MMTC', 'MASFIN']

  stock_ids = df_pf[~df_pf['Symbol'].isin(exclude) ]['Symbol'].unique()

  #mypf = mypf[mypf.Forecast.notnull()]
  #stock_ids = mypf['Symbol'].unique()

  #stock_ids.sort()
  return stock_ids

# get features from screener data
def get_screener_features():
  myscreen_df = get_myscreen_df()
  cols = ['Symbol', 'EPS', 'MedPE', 'ROCE%', 'ROE%', 'CapType']
  return myscreen_df[cols]

# get relative strength
def get_relative_strength(stock_list):

    # Dictionary to store stock tickers and their corresponding percentage price change
    stock_changes = {}

    # Loop through each stock and fetch its price data
    for stock in stock_list:
        try:
            # Download the stock data for the given date range
            stock_data = yfin.Ticker(stock + '.NS').history(period='1mo', interval='1d')[map(str.title, ['open', 'close', 'low', 'high', 'volume'])]

            # Calculate the percentage change for the stock
            if len(stock_data) > 0:
                start_price = stock_data['Close'].iloc[0]
                end_price = stock_data['Close'].iloc[-1]
                percent_change = round(((end_price - start_price) / start_price) * 100, 2)
                stock_changes[stock] = percent_change
            else:
                stock_changes[stock] = np.nan  # If no data is available, set to NaN

        except Exception as e:
            print(f"Error fetching data for {stock}: {e}")
            stock_changes[stock] = np.nan

    # Create a DataFrame with stock tickers and their percentage changes
    df = pd.DataFrame(list(stock_changes.items()), columns=['Symbol', 'Percent_Change'])

    # Drop any stocks with missing data (NaN values)
    df = df.dropna()

    # Calculate the percentile rank based on percentage change
    df['RSP'] = round(df['Percent_Change'].rank(pct=True) * 100, 2)
    cols = ['Symbol', 'RSP']
    df = df[cols]
    # Sort by percentile rank (optional)
    df = df.sort_values(by='RSP', ascending=False).reset_index(drop=True)

    return df

In [6]:
# function to get stock technicals
def stock_prec_dev(stock_symbol):
    #stock_symbol = 'ULTRACEMCO.NS'
    short_window = 20
    mid_window = 50
    long_window = 200
    moving_avg = 'SMA'

    start = datetime.datetime(*map(int, start_date.split('-')))
    end = datetime.datetime(*map(int, end_date.split('-')))

    stock_df = yfin.Ticker(stock_symbol + '.NS').history(period='max', interval='1d')[map(str.title, ['open', 'close', 'low', 'high', 'volume'])]

    stock_df['Max'] = round(max(stock_df['Close']),2)
    stock_df = stock_df[(stock_df.index <= end_date) & (stock_df.index >= start_date)]
    stock_df['200_SMA'] = round(stock_df['Close'].rolling(window = 200, min_periods = 1).mean(),0)
    stock_df['Dev%_200'] = round((stock_df['Close'] - stock_df['200_SMA'])*100/stock_df['200_SMA'],2)
    stock_df.dropna(axis = 0, inplace = True) # remove any null rows

    stock_df['20_SMA'] = stock_df['Close'].rolling(window=20).mean()
    stock_df['50_SMA'] = stock_df['Close'].rolling(window=50).mean()
    stock_df['Symbol'] = stock_symbol

    stock_df['Close'] = round(stock_df['Close'],2)
    stock_df['Min'] = round(min(stock_df['Close']),2)
    stock_df['RSI_14'] = ta.momentum.RSIIndicator(close=stock_df['Close'], window=14).rsi()
    stock_df['RSI_14'] = round(stock_df['RSI_14'],0)
    stock_df['Prev_Close'] = stock_df['Close'].shift(1)
    stock_df.drop(['Open', 'Low', 'High', 'Volume'], axis=1, inplace=True)
    stock_df = stock_df.tail(1)

    max_SMA = max(stock_df['20_SMA'].item(), stock_df['50_SMA'].item(), stock_df['200_SMA'].item())
    min_SMA = min(stock_df['20_SMA'].item(), stock_df['50_SMA'].item(), stock_df['200_SMA'].item())
    ABS_Spread = max_SMA - min_SMA
    stock_df['Spread%'] = round((ABS_Spread / stock_df['200_SMA'].item()) * 100,2)

    return stock_df

# function to compute stock attributes
def get_common_features(stock_ids, df_mypf):

  df_prec_dev = pd.DataFrame()
  df_tmp = get_screener_features()
  df_rs = get_relative_strength(stock_ids)

  for stock_id in stock_ids:
      tmp = stock_prec_dev(stock_id)
      tmp = tmp.reset_index()
      df_prec_dev = pd.concat([df_prec_dev, tmp], ignore_index = True)
  df_prec_dev = pd.merge(df_prec_dev, df_mypf, on= 'Symbol')
  df_prec_dev = pd.merge(df_prec_dev, df_tmp, on= 'Symbol', how='left')
  df_prec_dev = pd.merge(df_prec_dev, df_rs, on= 'Symbol', how='left')
  #print(df_prec_dev.columns)
  df_prec_dev['Curr_PE'] = round(df_prec_dev['Close']/df_prec_dev['EPS'],1)
  df_prec_dev['Dev%_PE'] = round((df_prec_dev['Curr_PE'] - df_prec_dev['MedPE'])*100/df_prec_dev['MedPE'],2)
  df_prec_dev['Conviction'] = df_prec_dev['Conviction'] + '-' + df_prec_dev['CapType']
  return df_prec_dev

# function to arrange stock features
def arrange_features(df_stocks, common_cols, diff_cols):
  df_stocks_common = df_stocks[common_cols].drop_duplicates()
  df_stocks_diff = df_stocks[diff_cols]
  df_stocks_diff['Investment'] = df_stocks_diff['AvgCost'] * df_stocks_diff['Shares']
  df_stocks_diff = df_stocks_diff.groupby(['Symbol'])[['Shares', 'Investment']].aggregate(['sum']).reset_index()
  df_stocks_diff.columns = ['Symbol', 'Shares', 'Investment']
  df_stocks_diff['AvgCost'] = round(df_stocks_diff['Investment']/df_stocks_diff['Shares'],2)
  df_stocks = pd.merge(df_stocks_diff, df_stocks_common, on='Symbol')
  return df_stocks

# plot fact distribution across dimension
def plot_pie_chart(df, dimension, fact):
  # grouping the data by category and calculating the sum of fact for each type
  grouped_data = df.groupby(dimension)[fact].sum()

  # sorting the grouped data in descending order
  grouped_data = grouped_data.sort_values(ascending=False)

  # creating a pie chart
  grouped_data.plot.pie(autopct='%1.1f%%', startangle=90, figsize=(6, 6))

  # adding a title and displaying the plot
  plt.title(f'{dimension} {fact} Distribution')
  plt.ylabel('')  # To hide the y-label
  plt.show()

In [7]:
# function to get portfolio features

def get_portfolio_features(df_common_features):

  print_date_time()
  print('-------------------')

  #df_common_features["Target"] = df_common_features["Target"].fillna(df_common_features["Max"])
  df_common_features['NTT'] = np.where(df_common_features['Strategy']== 'NTT', df_common_features["Target"], df_common_features['Max'])
  df_common_features['LTT'] = np.where(df_common_features['Strategy']== 'BTT', df_common_features["Target"], df_common_features['Max'])
  df_common_features['BOL'] = df_common_features['Min']

  tmp_df = df_common_features[df_common_features['Symbol'].isin(mypf_df[mypf_df['InPortfolio'] != 'NA'].Symbol.values)]
  print('qualified stocks: '+str(len(tmp_df['Symbol'].unique())))
  tmp_df1 = tmp_df[tmp_df['LatestQtr'] == 1]
  print('with latest results: '+str(len(tmp_df1['Symbol'].unique())))
  tmp_df1 = tmp_df1[tmp_df1['StarStock'] == 1]
  print('still star stocks: '+str(len(tmp_df1['Symbol'].unique())))
  tmp_df['Investment'] = tmp_df['AvgCost'] * tmp_df['Shares']
  tmp_df['Current'] = round(tmp_df['Close'] * tmp_df['Shares'],0)
  tmp_df['Previous'] = tmp_df['Prev_Close'] * tmp_df['Shares']
  tmp_df['EstimatedST'] = tmp_df['NTT'] * tmp_df['Shares']
  tmp_df['EstimatedLT'] = tmp_df['LTT'] * tmp_df['Shares']
  tmp_df['Current P/L'] = round((tmp_df['Current'] - tmp_df['Investment']),0)
  tmp_df['Today P/L%'] = round((tmp_df['Current'] - tmp_df['Previous'])*100/tmp_df['Previous'],2)
  tmp_df['Current P/L%'] = round((tmp_df['Current'] - tmp_df['Investment'])*100/tmp_df['Investment'],2)
  tmp_df['EstimatedST P/L%'] = round((tmp_df['EstimatedST'] - tmp_df['Investment'])*100/tmp_df['Investment'],2)
  tmp_df['EstimatedLT P/L%'] = round((tmp_df['EstimatedLT'] - tmp_df['Investment'])*100/tmp_df['Investment'],2)
  tmp_df['NTT%'] = round((tmp_df['NTT'] - tmp_df['Close'])*100/tmp_df['Close'],2)
  tmp_df['LTT%'] = round((tmp_df['LTT'] - tmp_df['Close'])*100/tmp_df['Close'],2)
  tmp_df['Gained%'] = round((tmp_df['Close'] - tmp_df['BOL'])*100/tmp_df['BOL'],2)
  investment = round(sum(tmp_df['AvgCost']*tmp_df['Shares']),0)
  current = round(sum(tmp_df['Close']*tmp_df['Shares']),0)
  tmp_df['InitAlloc%'] = round(tmp_df['Investment']*100/investment,2)
  tmp_df['CurrAlloc%'] = round(tmp_df['Current']*100/current,2)
  tmp_df['FTT'] = tmp_df['LTT']
  tmp_df.loc[tmp_df['Strategy'] == 'NTT', 'FTT'] = tmp_df['NTT']
  tmp_df['FTT%'] = tmp_df['LTT%']
  tmp_df.loc[tmp_df['Strategy'] == 'NTT', 'FTT%'] = tmp_df['NTT%']
  tmp_df['FTT Amt'] = round(tmp_df['FTT%'] * tmp_df['Current']/100,0)
  tmp_df['OTT%'] = round((tmp_df['FTT'] - tmp_df['AvgCost'])*100/tmp_df['AvgCost'],2)
  tmp_df['RRR Ind'] = round(tmp_df['Current P/L']/tmp_df['FTT Amt'],2)
  tmp_df['Risk Ind'] = round(tmp_df['Current P/L%']*tmp_df['CurrAlloc%'],0)

  return tmp_df

# function to print portfolio features
def print_portfolio_stats(df_portfolio_features, myinvmt_df):
  from pyxirr import xirr

  total_booked_amt, reserve_amt, cy_booked_amt, py_booked_amt = get_amt()

  dates = myinvmt_df['Date'].values
  dates = np.append(dates, datetime.date.today().strftime('%d-%b-%y'))
  investment = myinvmt_df['Investment'].values
  dates= pd.to_datetime(dates)

  current = round(sum(df_portfolio_features['Close']*df_portfolio_features['Shares']),0) + reserve_amt
  investment_xirr = np.append(investment, current)
  cagr = round(xirr(pd.DataFrame({"dates": dates, "amounts": investment_xirr}))*100,2)

  investment = -sum(investment)
  invested = round(sum(df_portfolio_features['AvgCost']*df_portfolio_features['Shares']),0) + reserve_amt
  previous = round(sum(df_portfolio_features['Prev_Close']*df_portfolio_features['Shares']),0) + reserve_amt
  cy_invested = investment + py_booked_amt

  today_pnl_amount = current-previous
  today_pnl_percentage = round((current-previous)*100/previous,2)

  curr_pnl_amount = current-invested
  curr_pnl_percentage = round((curr_pnl_amount)*100/(cy_invested),2)

  cy_pnl_amount = cy_booked_amt + curr_pnl_amount
  cy_pnl_percentage = round((cy_pnl_amount)*100/cy_invested,2)

  overall_pnl_amount = total_booked_amt + curr_pnl_amount
  overall_pnl_percentage = round((overall_pnl_amount)*100/investment,2)

  estimate_st = round(sum(df_portfolio_features['FTT']*df_portfolio_features['Shares']),0)  + reserve_amt
  est_st_pnl_amount = estimate_st-current
  est_st_pnl_percentage = round((est_st_pnl_amount)*100/current,2)

  estimate_lt = round(sum(df_portfolio_features['LTT']*df_portfolio_features['Shares']),0)  + reserve_amt
  est_lt_pnl_amount = estimate_lt-current
  est_lt_pnl_percentage = round((est_lt_pnl_amount)*100/current,2)

  total_profit = round(sum(df_portfolio_features[df_portfolio_features['Current P/L%'] > 0]['Current']) - sum(df_portfolio_features[df_portfolio_features['Current P/L%'] > 0]['Investment']),0)
  total_loss = round(sum(df_portfolio_features[df_portfolio_features['Current P/L%'] < 0]['Current']) - sum(df_portfolio_features[df_portfolio_features['Current P/L%'] < 0]['Investment']),0)

  cy_booked_percentage = round((cy_booked_amt)*100/current,2)
  py_booked_percentage = round((py_booked_amt)*100/investment,2)
  total_booked_percentage = round((total_booked_amt)*100/investment,2)

  print('-------------------')
  print('Initial Investment: ', format_amt(investment))
  print('CY Investment: ', format_amt(cy_invested))
  print('Reserve: ', format_amt(reserve_amt))
  print('Current: ',  format_amt(current))
  print('-------------------')
  print('Today PnL: '+ '{} ({}%)'.format(format_amt(today_pnl_amount), today_pnl_percentage))
  print('Current PnL: '+ '{} ({}%)'.format(format_amt(curr_pnl_amount), curr_pnl_percentage))
  print('CY Booked + Current PnL: '+ '{} ({}%)'.format(format_amt(cy_pnl_amount), cy_pnl_percentage))
  print('-------------------')
  print('Total profit: ', format_amt(total_profit))
  print('Total loss: ', format_amt(total_loss))
  print('-------------------')
  print('Total Booked + Current PnL: '+ '{} ({}%)'.format(format_amt(overall_pnl_amount), overall_pnl_percentage))
  print('Total Booked PnL: '+ '{} ({}%)'.format(format_amt(total_booked_amt), total_booked_percentage))
  print('Curr Year Booked PnL: '+ '{} ({}%)'.format(format_amt(cy_booked_amt), cy_booked_percentage))
  print('Prev Year Booked PnL: '+ '{} ({}%)'.format(format_amt(py_booked_amt), py_booked_percentage))
  print('===================')
  print('Est FTT: ',  format_amt(estimate_st))
  print('Est FTT PnL: '+ '{} ({}%)'.format(format_amt(est_st_pnl_amount), est_st_pnl_percentage))

  print('===================')
  print('Deployed: ', format_amt(investment))

  print('Current: ', format_amt(current))

  print('CAGR/XIRR %: '+'{}%'.format(cagr))

In [8]:
# get start and end date
start_date, end_date = get_start_end_date()

# get portfolio and prospects data
mypfs_df = get_mypfs_df()
mypps_df = get_mypps_df()
myinvmt_df = get_myinvmt_df()

# merge above datasets
mypf_df = pd.merge(mypfs_df, mypps_df, on="Symbol")

# seggregate dm and sv portfolio
dm_pf = mypf_df[mypf_df['InPortfolio'] == 'DM']
sv_pf = mypf_df[mypf_df['InPortfolio'] == 'SV']

# build portfolio stock dataframe
dm_stocks = get_stock_ids(dm_pf)
sv_stocks = get_stock_ids(sv_pf)
df_stocks = pd.concat([dm_pf,sv_pf], ignore_index = True)

# arrange common and diff stock features
common_cols = ['Symbol', 'Target', 'Criteria', 'Strategy', 'CumlRnk', 'LatestQtr', 'StarStock', 'Conviction', 'Category', 'InFolio', 'XIRR', 'MBQ']
diff_cols = ['Symbol', 'AvgCost', 'Shares']
df_stocks = arrange_features(df_stocks, common_cols, diff_cols)

# get common features
stock_ids = df_stocks['Symbol'].values
df_common_features = get_common_features(stock_ids, df_stocks)

df_common_features.reset_index(drop=True, inplace=True)
df_common_features.drop(['Date'], axis=1, inplace=True)
# get and print portfolio features
df_portfolio_features = get_portfolio_features(df_common_features)

print_portfolio_stats(df_portfolio_features, myinvmt_df)

df = df_portfolio_features
#plot_pie_chart(df, 'CapType', 'Current')
list_ox40n = list(df[df['MBQ'].str.contains('OX40N', na=False)]['Symbol'].values)

Run date time (IST): 2026-06-24 11:36:41
-------------------
qualified stocks: 92
with latest results: 31
still star stocks: 20

-------------------
Initial Investment:  1.40 C
CY Investment:  1.82 C
Reserve:  1.49 K
Current:  1.52 C
-------------------
Today PnL: 2.69 K (0.02%)
Current PnL: -31.67 L (-17.36%)
CY Booked + Current PnL: -29.59 L (-16.22%)
-------------------
Total profit:  3.99 L
Total loss:  -35.66 L
-------------------
Total Booked + Current PnL: 13.28 L (9.52%)
Total Booked PnL: 44.95 L (32.22%)
Curr Year Booked PnL: 2.08 L (1.37%)
Prev Year Booked PnL: 42.87 L (30.73%)
===================
Est FTT:  2.55 C
Est FTT PnL: 1.04 C (68.35%)
===================
Deployed:  1.40 C
Current:  1.52 C
CAGR/XIRR %: 3.84%

In [9]:
# top 5 near their targets
cols = ['Symbol', 'Today P/L%', 'Current P/L%', 'FTT%', 'OTT%', 'FTT Amt', 'Current P/L', 'Current', 'FTT', 'Dev%_PE', 'RSI_14','Conviction', 'Spread%',  'CumlRnk', 'RRR Ind', 'CurrAlloc%', 'Gained%', 'Criteria', 'Strategy', 'Category']
df_tmp = df_portfolio_features[~df_portfolio_features['Symbol'].isin(['ENRIN','BLUSPRING','DIGITIDE'])]
df_tmp = df_tmp.sort_values(by = 'FTT Amt', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
49,JSWINFRA,5.97,13.62,2.47,16.43,6224.0,30207.0,251981.0,342.00,-2.58,79.0,X-MC,3.75,61.0,4.85,1.66,42.87,X40N,NTT,REALTY
59,PIDILITIND,0.64,11.74,5.93,18.37,9350.0,16570.0,157680.0,1670.26,-21.72,71.0,X-LC,3.94,5.0,1.77,1.04,23.81,X40,ATH,CHEMICALS
51,KOTAKBANK,1.39,8.82,11.29,21.11,17012.0,12210.0,150682.0,453.24,-6.81,65.0,X-LC,5.09,12.0,0.72,0.99,15.24,X40,ATH,BANKS
72,SIS,6.15,4.62,15.90,21.26,18470.0,5133.0,116165.0,528.00,2778.24,71.0,H-SC,24.56,168.0,0.28,0.77,72.72,OX40N,NTT,MISC
56,MEDANTA,2.00,13.67,11.83,27.12,23737.0,24132.0,200649.0,1486.00,10.18,72.0,X-SC,3.23,87.0,1.02,1.32,38.26,XY24,NTT,HEALTHCARE

In [10]:
# top 5 today
df_tmp = df_portfolio_features.sort_values(by = 'Today P/L%', ascending=False)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
72,SIS,6.15,4.62,15.90,21.26,18470.0,5133.0,116165.0,528.00,2778.24,71.0,H-SC,24.56,168.0,0.28,0.77,72.72,OX40N,NTT,MISC
49,JSWINFRA,5.97,13.62,2.47,16.43,6224.0,30207.0,251981.0,342.00,-2.58,79.0,X-MC,3.75,61.0,4.85,1.66,42.87,X40N,NTT,REALTY
82,TRIDENT,4.91,-27.87,78.17,28.51,52016.0,-25712.0,66542.0,48.00,-7.14,70.0,M-SC,4.79,223.0,-0.49,0.44,24.66,XR,NTT,TEXTILES
21,DEN,3.64,-37.98,129.08,42.07,67617.0,-32080.0,52384.0,75.00,86.53,69.0,M-SC,6.63,235.0,-0.47,0.35,42.47,AR,NTT,ENTERTAINMENT
37,HONAUT,2.34,1.38,49.25,51.31,96284.0,2662.0,195500.0,58357.33,-15.74,73.0,X-SC,8.32,90.0,0.03,1.29,48.53,X40N,ATH,ELECTRICAL

In [11]:
# bottom 5 today
df_tmp = df_portfolio_features.sort_values(by = 'Today P/L%', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
61,RAJESHEXPO,-5.00,-80.27,407.25,0.07,110210.0,-110115.0,27062.0,518.0,892.42,52.0,L-SC,36.23,268.0,-1.00,0.18,33.65,OX40N,NTT,JEWELLERY
69,SFL,-2.86,-29.63,79.94,26.63,147516.0,-77684.0,184534.0,1287.0,39.75,65.0,M-SC,11.79,242.0,-0.53,1.22,53.80,XY24,NTT,MISC
71,SIEMENS,-2.14,-3.09,29.51,25.51,53221.0,-5745.0,180350.0,4671.5,51.49,45.0,H-LC,12.75,51.0,-0.11,1.19,26.62,AR,ATH,ELECTRICAL
10,BATAINDIA,-2.11,-53.67,191.82,35.20,114353.0,-69055.0,59615.0,2096.0,-21.88,55.0,X-SC,22.87,91.0,-0.60,0.39,18.23,X40,NTT,FOOTWEAR
76,SYMPHONY,-1.95,-48.02,92.33,-0.03,82133.0,-82185.0,88956.0,1306.0,-58.23,41.0,M-SC,18.13,205.0,-1.00,0.59,2.67,OX40N,NTT,DURABLES

In [12]:
# top 5 to exit based on CumlRnk
df_tmp = df_portfolio_features[~df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])]
df_tmp = df_tmp[(df_tmp['Current P/L%'] > -1) & (df_tmp['Current P/L%'] < 1)].sort_values(by = 'CumlRnk', ascending=False)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
9,BANDHANBNK,0.85,0.49,91.49,92.42,256092.0,1354.0,279913.0,400.0,139.94,55.0,H-SC,23.3,174.0,0.01,1.85,54.2,XY24,NTT,BANKS

In [13]:
# OX40N stocks to exit
df_tmp = df_portfolio_features[(df_portfolio_features['Symbol'].isin(list_ox40n))].sort_values(by = 'Current P/L%', ascending=False)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
25,FINCABLES,-0.20,46.27,42.14,107.91,91008.0,68322.0,215966.0,1641.55,31.41,61.0,M-SC,24.81,220.0,0.75,1.43,62.48,OX40N,ATH,CABLES
72,SIS,6.15,4.62,15.90,21.26,18470.0,5133.0,116165.0,528.00,2778.24,71.0,H-SC,24.56,168.0,0.28,0.77,72.72,OX40N,NTT,MISC
16,CERA,-1.45,-17.14,49.52,23.89,72176.0,-30152.0,145751.0,9475.00,-20.05,62.0,H-SC,7.99,153.0,-0.42,0.96,40.07,OX40N,NTT,CERAMICS
83,TTKPRESTIG,-0.36,-28.07,39.15,0.09,28379.0,-28288.0,72489.0,770.00,68.20,57.0,M-SC,8.93,250.0,-1.00,0.48,29.08,OX40N,NTT,DURABLES
43,INDIGOPNTS,-0.35,-28.50,39.88,0.02,49775.0,-49747.0,124812.0,1408.00,90.29,57.0,M-SC,8.02,222.0,-1.00,0.82,41.61,OX40N,NTT,PAINTS

In [14]:
# top 5 to book for rotation
df_tmp = df_portfolio_features[(df_portfolio_features['Current P/L%'] > 20) ].sort_values(by = 'CumlRnk', ascending=False)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
25,FINCABLES,-0.20,46.27,42.14,107.91,91008.0,68322.0,215966.0,1641.55,31.41,61.0,M-SC,24.81,220.0,0.75,1.43,62.48,OX40N,ATH,CABLES
68,SATIN,1.35,30.63,16.23,51.83,58577.0,84634.0,360918.0,274.00,16.95,59.0,H-SC,40.62,159.0,1.44,2.38,75.82,XY24,NTT,FINANCE

In [15]:
# top 5 to monitor for exit
df_tmp = df_portfolio_features[~df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])]
df_tmp = df_tmp[(df_tmp['Current P/L%'] > 0) ].sort_values(by = 'Dev%_PE', ascending=False)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
72,SIS,6.15,4.62,15.90,21.26,18470.0,5133.0,116165.0,528.00,2778.24,71.0,H-SC,24.56,168.0,0.28,0.77,72.72,OX40N,NTT,MISC
9,BANDHANBNK,0.85,0.49,91.49,92.42,256092.0,1354.0,279913.0,400.00,139.94,55.0,H-SC,23.30,174.0,0.01,1.85,54.20,XY24,NTT,BANKS
74,STARHEALTH,-0.68,12.17,31.29,47.26,98667.0,34207.0,315330.0,761.00,77.10,75.0,H-SC,12.30,173.0,0.35,2.08,38.44,XY24,NTT,INSURANCE
25,FINCABLES,-0.20,46.27,42.14,107.91,91008.0,68322.0,215966.0,1641.55,31.41,61.0,M-SC,24.81,220.0,0.75,1.43,62.48,OX40N,ATH,CABLES
68,SATIN,1.35,30.63,16.23,51.83,58577.0,84634.0,360918.0,274.00,16.95,59.0,H-SC,40.62,159.0,1.44,2.38,75.82,XY24,NTT,FINANCE

In [16]:
# top 5 to book for rotation from weak conviction
df_tmp = df_portfolio_features[~df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])]
df_tmp = df_tmp[~df_tmp['Criteria'].isin(['XY25','XY24','X40', 'X40N'])].sort_values(by = 'RRR Ind', ascending=False)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
91,ZYDUSLIFE,-0.65,16.52,16.40,35.63,40050.0,34631.0,244205.0,1286.17,1.35,63.0,H-MC,13.81,120.0,0.86,1.61,28.40,AR,ATH,PHARMA
25,FINCABLES,-0.20,46.27,42.14,107.91,91008.0,68322.0,215966.0,1641.55,31.41,61.0,M-SC,24.81,220.0,0.75,1.43,62.48,OX40N,ATH,CABLES
72,SIS,6.15,4.62,15.90,21.26,18470.0,5133.0,116165.0,528.00,2778.24,71.0,H-SC,24.56,168.0,0.28,0.77,72.72,OX40N,NTT,MISC
73,SONACOMS,0.41,6.99,30.01,39.09,32480.0,7070.0,108229.0,804.02,-15.20,61.0,M-MC,18.13,193.0,0.22,0.71,53.10,AR,ATH,AUTO
75,SURYODAY,-1.46,-3.56,27.58,23.03,47630.0,-6375.0,172696.0,216.00,88.60,52.0,H-SC,19.05,166.0,-0.13,1.14,45.41,XR,NTT,BANKS

In [17]:
# top 5 to accumulate based on lowest RSI_14
df_tmp = df_portfolio_features[df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])].sort_values(by = 'RSI_14', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
45,INFY,1.85,-28.64,88.11,34.24,196739.0,-89600.0,223288.0,1972.00,-43.76,36.0,X-LC,17.43,3.0,-0.46,1.47,1.85,X40,NTT,IT
79,TCS,1.48,-38.65,103.54,24.88,294302.0,-179033.0,284240.0,4253.91,-48.21,37.0,X-LC,19.81,2.0,-0.61,1.88,1.48,X40,ATH,IT
33,HCLTECH,0.28,-27.80,68.29,21.51,119288.0,-67246.0,174678.0,1872.35,-24.32,38.0,X-LC,18.62,8.0,-0.56,1.15,0.28,X40,ATH,IT
20,DABUR,-0.10,-18.00,75.25,43.70,153065.0,-44659.0,203409.0,735.00,-25.56,38.0,X-MC,12.01,70.0,-0.29,1.34,2.18,XY24,BTT,FMCG
58,PGHH,-1.11,-32.57,95.79,32.01,137907.0,-69552.0,143968.0,17616.87,-54.37,38.0,X-MC,20.31,57.0,-0.50,0.95,0.07,X40,ATH,FMCG

In [18]:
# top 5 to accumulate based on Spread and CumlRnk
df_tmp = df_portfolio_features[df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])]
df_tmp = df_tmp[(df_tmp['CumlRnk'] < 100)].sort_values(by = 'Spread%', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
11,BERGEPAINT,-1.50,-0.84,26.38,25.32,67420.0,-2175.0,255574.0,680.00,-6.27,60.0,X-MC,2.91,68.0,-0.03,1.69,33.02,XY24,NTT,PAINTS
56,MEDANTA,2.00,13.67,11.83,27.12,23737.0,24132.0,200649.0,1486.00,10.18,72.0,X-SC,3.23,87.0,1.02,1.32,38.26,XY24,NTT,HEALTHCARE
49,JSWINFRA,5.97,13.62,2.47,16.43,6224.0,30207.0,251981.0,342.00,-2.58,79.0,X-MC,3.75,61.0,4.85,1.66,42.87,X40N,NTT,REALTY
59,PIDILITIND,0.64,11.74,5.93,18.37,9350.0,16570.0,157680.0,1670.26,-21.72,71.0,X-LC,3.94,5.0,1.77,1.04,23.81,X40,ATH,CHEMICALS
19,COLPAL,-0.04,-24.83,86.06,39.86,170373.0,-65395.0,197970.0,3683.41,-8.99,40.0,X-MC,3.99,62.0,-0.38,1.31,11.98,XY25,ATH,FMCG

In [19]:
# top 5 to accumulate based on lowest Gained%
df_tmp = df_portfolio_features[df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])].sort_values(by = 'Gained%', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
58,PGHH,-1.11,-32.57,95.79,32.01,137907.0,-69552.0,143968.0,17616.87,-54.37,38.0,X-MC,20.31,57.0,-0.50,0.95,0.07,X40,ATH,FMCG
33,HCLTECH,0.28,-27.80,68.29,21.51,119288.0,-67246.0,174678.0,1872.35,-24.32,38.0,X-LC,18.62,8.0,-0.56,1.15,0.28,X40,ATH,IT
79,TCS,1.48,-38.65,103.54,24.88,294302.0,-179033.0,284240.0,4253.91,-48.21,37.0,X-LC,19.81,2.0,-0.61,1.88,1.48,X40,ATH,IT
1,ABBOTINDIA,0.29,-13.97,37.24,18.07,57301.0,-24985.0,153870.0,35195.00,-26.70,39.0,X-MC,5.98,58.0,-0.44,1.02,1.85,X40,ATH,PHARMA
45,INFY,1.85,-28.64,88.11,34.24,196739.0,-89600.0,223288.0,1972.00,-43.76,36.0,X-LC,17.43,3.0,-0.46,1.47,1.85,X40,NTT,IT

In [20]:
# top 5 to accumulate based on lowest CurrAlloc%
df_tmp = df_portfolio_features[df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])].sort_values(by = 'CurrAlloc%', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
10,BATAINDIA,-2.11,-53.67,191.82,35.20,114353.0,-69055.0,59615.0,2096.00,-21.88,55.0,X-SC,22.87,91.0,-0.60,0.39,18.23,X40,NTT,FOOTWEAR
64,RELAXO,-0.56,-53.07,224.55,52.31,152968.0,-77038.0,68122.0,1176.00,-50.05,64.0,X-SC,14.90,92.0,-0.50,0.45,52.31,X40N,NTT,FOOTWEAR
60,QUESS,-0.39,2.56,69.55,73.90,76179.0,2738.0,109531.0,424.00,-44.90,72.0,X-SC,10.68,80.0,0.04,0.72,49.31,XY24,NTT,MISC
28,GODREJCP,0.41,-8.28,43.33,31.47,59064.0,-12302.0,136312.0,1469.04,-3.49,51.0,X-LC,9.34,32.0,-0.21,0.90,4.59,X40N,ATH,FMCG
53,M&M,0.92,-0.54,24.05,23.38,33172.0,-751.0,137930.0,3802.40,-15.83,49.0,X-LC,10.62,25.0,-0.02,0.91,4.57,X40N,ATH,AUTO

In [21]:
# top 5 to accumulate based on CumlRnk
df_tmp = df_portfolio_features.sort_values(by = 'CumlRnk', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
47,ITC,0.29,-23.39,55.41,19.06,144400.0,-79564.0,260602.0,452.00,-57.95,52.0,X-LC,14.93,1.0,-0.55,1.72,5.00,X40,NTT,FMCG
79,TCS,1.48,-38.65,103.54,24.88,294302.0,-179033.0,284240.0,4253.91,-48.21,37.0,X-LC,19.81,2.0,-0.61,1.88,1.48,X40,ATH,IT
45,INFY,1.85,-28.64,88.11,34.24,196739.0,-89600.0,223288.0,1972.00,-43.76,36.0,X-LC,17.43,3.0,-0.46,1.47,1.85,X40,NTT,IT
81,TMPV,-1.45,-20.47,71.72,36.58,202978.0,-72827.0,283014.0,600.00,-83.62,39.0,X-LC,10.12,4.0,-0.36,1.87,18.94,XY24,NTT,AUTO
59,PIDILITIND,0.64,11.74,5.93,18.37,9350.0,16570.0,157680.0,1670.26,-21.72,71.0,X-LC,3.94,5.0,1.77,1.04,23.81,X40,ATH,CHEMICALS

In [22]:
# top 5 for average up
df_tmp = df_portfolio_features[(df_portfolio_features['Dev%_200'] > 5)].sort_values(by = 'CurrAlloc%', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
44,INDUSINDBK,1.02,-32.47,96.80,32.89,50467.0,-25072.0,52135.0,1800.00,-345.10,50.0,L-MC,7.14,258.0,-0.50,0.34,28.33,XR,NTT,BANKS
21,DEN,3.64,-37.98,129.08,42.07,67617.0,-32080.0,52384.0,75.00,86.53,69.0,M-SC,6.63,235.0,-0.47,0.35,42.47,AR,NTT,ENTERTAINMENT
3,ALKYLAMINE,-0.55,-23.64,153.56,93.63,118393.0,-23864.0,77099.0,4546.37,-18.23,53.0,H-SC,7.28,142.0,-0.20,0.51,45.58,SR,ATH,CHEMICALS
73,SONACOMS,0.41,6.99,30.01,39.09,32480.0,7070.0,108229.0,804.02,-15.20,61.0,M-MC,18.13,193.0,0.22,0.71,53.10,AR,ATH,AUTO
60,QUESS,-0.39,2.56,69.55,73.90,76179.0,2738.0,109531.0,424.00,-44.90,72.0,X-SC,10.68,80.0,0.04,0.72,49.31,XY24,NTT,MISC

In [23]:
# top 5 RSP
df_tmp = df_portfolio_features.sort_values(by = 'RSP', ascending=False)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
18,COFFEEDAY,-0.41,-42.17,133.92,35.27,87937.0,-47885.0,65664.0,80.0,-55.73,56.0,L-SC,16.47,266.0,-0.54,0.43,61.93,XR,NTT,HOTELS
64,RELAXO,-0.56,-53.07,224.55,52.31,152968.0,-77038.0,68122.0,1176.0,-50.05,64.0,X-SC,14.90,92.0,-0.50,0.45,52.31,X40N,NTT,FOOTWEAR
60,QUESS,-0.39,2.56,69.55,73.90,76179.0,2738.0,109531.0,424.0,-44.90,72.0,X-SC,10.68,80.0,0.04,0.72,49.31,XY24,NTT,MISC
49,JSWINFRA,5.97,13.62,2.47,16.43,6224.0,30207.0,251981.0,342.0,-2.58,79.0,X-MC,3.75,61.0,4.85,1.66,42.87,X40N,NTT,REALTY
21,DEN,3.64,-37.98,129.08,42.07,67617.0,-32080.0,52384.0,75.0,86.53,69.0,M-SC,6.63,235.0,-0.47,0.35,42.47,AR,NTT,ENTERTAINMENT

In [24]:
# Top N allocation
df_tmp = df_portfolio_features.sort_values(by = 'CurrAlloc%', ascending=False)
top_n_values = [10, 25, 50]

sum_df = pd.DataFrame({
    'Top_N': top_n_values,
    'Sum_Alloc%': [df_tmp['CurrAlloc%'].head(n).sum() for n in top_n_values]
})

sum_df

   Top_N  Sum_Alloc%
0     10       19.31
1     25       42.60
2     50       72.74

In [25]:
# market-cap-wise allocation
df_tmp = df_portfolio_features[cols]
df_tmp.groupby(df_tmp['Conviction'].str[-2:])['CurrAlloc%'].sum().sort_values(ascending=False)

Conviction
SC    43.71
LC    30.43
MC    25.86
Name: CurrAlloc%, dtype: float64

In [26]:
# criteria-wise allocation
df_portfolio_features.groupby('Criteria')['CurrAlloc%'].sum().sort_values(ascending=False)

Criteria
XY24     27.72
X40      24.63
X40N     17.47
XR        8.86
OX40N     7.18
AR        6.81
XY25      6.46
SR        0.87
Name: CurrAlloc%, dtype: float64

In [27]:
# conviction-wise allocation
df_portfolio_features.groupby('Conviction')['CurrAlloc%'].sum().sort_values(ascending=False)

Conviction
X-LC    28.45
H-SC    22.94
X-MC    20.78
M-SC    10.14
X-SC    10.02
H-MC     2.72
M-MC     2.02
H-LC     1.19
M-LC     0.79
L-SC     0.61
L-MC     0.34
Name: CurrAlloc%, dtype: float64

In [28]:
# sector-wise stats
df_tmp = df_portfolio_features.groupby('Category')[['CurrAlloc%', 'Current', 'Current P/L', 'FTT Amt']].sum().sort_values(by=['Current', 'Current P/L'], ascending=False)
df_tmp['Current P/L%'] = round(df_tmp['Current P/L'] * 100 / df_tmp['Current'], 2)
df_tmp['FTT%'] = round(df_tmp['FTT Amt'] * 100 / df_tmp['Current'], 2)
cols = ['CurrAlloc%', 'Current P/L%', 'FTT%']
df_tmp[cols].sort_values(by=['CurrAlloc%'], ascending=False)

               CurrAlloc%  Current P/L%    FTT%
Category
FMCG                14.52        -20.31   62.51
FINANCE             10.96        -10.96   59.23
IT                   9.60        -54.79  132.19
MISC                 7.24        -22.24   74.69
AUTO                 6.55        -10.39   51.78
BANKS                5.78         -3.52   51.39
PAINTS               5.58        -16.69   36.59
INSURANCE            5.37         -1.70   36.00
PHARMA               5.07          3.39   26.52
ELECTRICAL           4.12        -13.19   53.13
CHEMICALS            2.20        -21.81   94.41
HEALTHCARE           2.11        -11.91   41.12
APPARELS             1.84          3.87   28.41
AC                   1.81        -16.69   48.33
FOOTWEAR             1.71        -69.90  138.03
REALTY               1.66         11.99    2.47
TRAVEL               1.61        -83.89  175.97
DURABLES             1.56        -64.43  104.43
BREWERIES            1.52         -1.53   22.61
CERAMICS             1.44        -40.72   83.47
CABLES               1.43         31.64   42.14
ENGINEERING          1.37        -16.66   70.02
REFINERIES           1.12        -18.75   48.79
JEWELLERY            1.07        -97.31  165.86
CEMENT               1.07        -66.13  190.41
ENTERTAINMENT        0.82        -57.06  150.72
TEXTILES             0.44        -38.64   78.17
HOTELS               0.43        -72.92  133.92

In [29]:
# money to be made criteria-wise
df_portfolio_features.groupby('Criteria')['FTT Amt'].agg(['sum', 'count']).sort_values(by='sum', ascending=False)

                sum  count
Criteria
XY24      3398628.0     21
X40       1945104.0     19
XR        1338654.0     13
AR        1144967.0      9
X40N      1075128.0     13
OX40N      705958.0     10
XY25       458119.0      5
SR         288368.0      2

In [30]:
# money to be made conviction-wise
df_portfolio_features.groupby('Conviction')['FTT Amt'].agg(['sum', 'count']).sort_values(by='sum', ascending=False)

                  sum  count
Conviction
H-SC        3306575.0     24
X-LC        1973144.0     21
X-MC        1568536.0     15
M-SC        1384243.0     14
X-SC        1283751.0      9
H-MC         285914.0      2
L-SC         198147.0      2
M-LC         171996.0      1
M-MC          78932.0      2
H-LC          53221.0      1
L-MC          50467.0      1

In [31]:
# money to be made criteria and conviction-wise
df_portfolio_features.groupby(['Conviction', 'Criteria'])['FTT Amt'].agg(['sum', 'count']).sort_values(by='sum', ascending=False)

                           sum  count
Conviction Criteria
X-LC       X40       1059538.0     10
H-SC       XY24       975954.0      6
           AR         951599.0      5
M-SC       XY24       827900.0      6
H-SC       XR         796526.0      7
X-SC       XY24       777527.0      4
X-MC       X40        676620.0      7
           X40N       419030.0      4
X-LC       X40N       358820.0      6
           XY24       350898.0      2
M-SC       OX40N      301620.0      5
X-SC       X40N       297278.0      3
H-SC       OX40N      294128.0      4
           SR         288368.0      2
X-MC       XY25       252401.0      2
H-MC       XY24       245864.0      1
X-MC       XY24       220485.0      2
X-SC       X40        208946.0      2
M-SC       XR         187106.0      2
M-LC       XR         171996.0      1
X-LC       XY25       159266.0      2
L-SC       OX40N      110210.0      1
           XR          87937.0      1
M-SC       AR          67617.0      1
H-LC       AR          53221.0      1
L-MC       XR          50467.0      1
M-MC       XY25        46452.0      1
X-LC       XR          44622.0      1
H-MC       AR          40050.0      1
M-MC       AR          32480.0      1

In [32]:
# notebook execution time

end_time = time.time()
execution_time = round(end_time - start_time, 0)
print(f"Notebook execution time: {execution_time} seconds")

Notebook execution time: 30.0 seconds