<a href="https://colab.research.google.com/github/ankit-rathi/Quantvesting_v2/blob/main/myStocks_Portfolio_Analysis.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
'''
!pip install pandas==2.2.2 -qq
!pip install pyxirr -qq
!pip install ta -qq
!pip install yfinance==0.2.59 -qq
'''

'\n!pip install pandas==2.2.2 -qq\n!pip install pyxirr -qq\n!pip install ta -qq\n!pip install yfinance==0.2.59 -qq\n'

In [2]:
# import libraries

import numpy as np
import pandas as pd
import datetime
import warnings
warnings.filterwarnings('ignore')
import yfinance as yfin
import ta
import matplotlib.pyplot as plt
import requests

In [3]:
# notebook start time
import time
import datetime
import pytz

start_time = time.time()

# function to print date timestamp
def print_date_time():
  tz_NY = pytz.timezone('Asia/Kolkata')
  datetime_NY = datetime.datetime.now(tz_NY)
  print("Run date time (IST):", datetime_NY.strftime("%Y-%m-%d %H:%M:%S"))

In [4]:
# function to get booked and reserved amount
def get_amt():
  # fetch the JSON data from the URL
  url = "https://raw.githubusercontent.com/ankit-rathi/Tradevesting_v1/main/data/myPortfolioAmts.json"
  response = requests.get(url)
  pf_amts = response.json()  # parse the JSON data

  # extract values from the JSON
  py_booked_amt_dm = pf_amts["py_booked_amt_dm"]
  py_booked_amt_sv = pf_amts["py_booked_amt_sv"]
  cy_booked_amt_dm = pf_amts["cy_booked_amt_dm"]
  cy_booked_amt_sv = pf_amts["cy_booked_amt_sv"]
  reserve_amt_dm = pf_amts["reserve_amt_dm"]
  reserve_amt_sv = pf_amts["reserve_amt_sv"]

  # perform calculations
  py_booked_amt = py_booked_amt_dm + py_booked_amt_sv
  cy_booked_amt = cy_booked_amt_dm + cy_booked_amt_sv
  reserve_amt = reserve_amt_dm + reserve_amt_sv
  total_booked_amt = py_booked_amt + cy_booked_amt

  return total_booked_amt, reserve_amt, cy_booked_amt, py_booked_amt

gen_output = 0

In [5]:
# function to format the amount
def format_amt(number):
    abs_number = abs(number)

    if abs_number >= 1_00_00_000:  # Crores
        formatted_amt = f"{number / 1_00_00_000:.2f} C"
    elif abs_number >= 1_00_000:  # Lakhs
        formatted_amt = f"{number / 1_00_000:.2f} L"
    elif abs_number >= 1_000:  # Thousands
        formatted_amt = f"{number / 1_000:.2f} K"
    else:
        formatted_amt = f"{number:.2f}"

    return formatted_amt

# function to set start and end date
def get_start_end_date():
  start_date = (datetime.date.today() + datetime.timedelta(days=-365)).strftime('%Y-%m-%d')
  end_date = (datetime.date.today() + datetime.timedelta(days=1)).strftime('%Y-%m-%d')
  return start_date, end_date

# function to fetch my portfolio csv
def get_mypfs_df():
  mypfs_df = pd.read_csv('https://raw.githubusercontent.com/ankit-rathi/Tradevesting_v1/main/data/myPortfolioStocks.csv')
  return mypfs_df

# function to fetch my prospects csv
def get_mypps_df():
  mypps_df = pd.read_csv('https://raw.githubusercontent.com/ankit-rathi/Tradevesting_v1/main/data/myProspectsScrips.csv')
  return mypps_df

# function to fetch screener data
def get_myscreen_df():
  myscreen_df = pd.read_csv('https://raw.githubusercontent.com/ankit-rathi/Tradevesting_v1/main/data/myScreenerDB.csv')
  return myscreen_df

# function to fetch momentum data
def get_myinvmt_df():
  myinvmt_df = pd.read_csv('https://raw.githubusercontent.com/ankit-rathi/Tradevesting_v1/main/data/myInvestments.csv')
  return myinvmt_df

# function to get the stock ids
def get_stock_ids(df_pf):
  stock_n100 = df_pf['Symbol'].unique()

  exclude = ['CADILAHC','MMTC', 'MASFIN']

  stock_ids = df_pf[~df_pf['Symbol'].isin(exclude) ]['Symbol'].unique()

  #mypf = mypf[mypf.Forecast.notnull()]
  #stock_ids = mypf['Symbol'].unique()

  #stock_ids.sort()
  return stock_ids

# get features from screener data
def get_screener_features():
  myscreen_df = get_myscreen_df()
  cols = ['Symbol', 'EPS', 'MedPE', 'ROCE%', 'ROE%', 'CapType']
  return myscreen_df[cols]

# get relative strength
def get_relative_strength(stock_list):

    # Dictionary to store stock tickers and their corresponding percentage price change
    stock_changes = {}

    # Loop through each stock and fetch its price data
    for stock in stock_list:
        try:
            # Download the stock data for the given date range
            stock_data = yfin.Ticker(stock + '.NS').history(period='1mo', interval='1d')[map(str.title, ['open', 'close', 'low', 'high', 'volume'])]

            # Calculate the percentage change for the stock
            if len(stock_data) > 0:
                start_price = stock_data['Close'].iloc[0]
                end_price = stock_data['Close'].iloc[-1]
                percent_change = round(((end_price - start_price) / start_price) * 100, 2)
                stock_changes[stock] = percent_change
            else:
                stock_changes[stock] = np.nan  # If no data is available, set to NaN

        except Exception as e:
            print(f"Error fetching data for {stock}: {e}")
            stock_changes[stock] = np.nan

    # Create a DataFrame with stock tickers and their percentage changes
    df = pd.DataFrame(list(stock_changes.items()), columns=['Symbol', 'Percent_Change'])

    # Drop any stocks with missing data (NaN values)
    df = df.dropna()

    # Calculate the percentile rank based on percentage change
    df['RSP'] = round(df['Percent_Change'].rank(pct=True) * 100, 2)
    cols = ['Symbol', 'RSP']
    df = df[cols]
    # Sort by percentile rank (optional)
    df = df.sort_values(by='RSP', ascending=False).reset_index(drop=True)

    return df

In [6]:
# function to get stock technicals
def stock_prec_dev(stock_symbol):
    #stock_symbol = 'ULTRACEMCO.NS'
    short_window = 20
    mid_window = 50
    long_window = 200
    moving_avg = 'SMA'

    start = datetime.datetime(*map(int, start_date.split('-')))
    end = datetime.datetime(*map(int, end_date.split('-')))

    stock_df = yfin.Ticker(stock_symbol + '.NS').history(period='max', interval='1d')[map(str.title, ['open', 'close', 'low', 'high', 'volume'])]

    stock_df['Max'] = round(max(stock_df['Close']),2)
    stock_df = stock_df[(stock_df.index <= end_date) & (stock_df.index >= start_date)]
    stock_df['200_SMA'] = round(stock_df['Close'].rolling(window = 200, min_periods = 1).mean(),0)
    stock_df['Dev%_200'] = round((stock_df['Close'] - stock_df['200_SMA'])*100/stock_df['200_SMA'],2)
    stock_df.dropna(axis = 0, inplace = True) # remove any null rows

    stock_df['20_SMA'] = stock_df['Close'].rolling(window=20).mean()
    stock_df['50_SMA'] = stock_df['Close'].rolling(window=50).mean()
    stock_df['Symbol'] = stock_symbol

    stock_df['Close'] = round(stock_df['Close'],2)
    stock_df['Min'] = round(min(stock_df['Close']),2)
    stock_df['RSI_14'] = ta.momentum.RSIIndicator(close=stock_df['Close'], window=14).rsi()
    stock_df['RSI_14'] = round(stock_df['RSI_14'],0)
    stock_df['Prev_Close'] = stock_df['Close'].shift(1)
    stock_df.drop(['Open', 'Low', 'High', 'Volume'], axis=1, inplace=True)
    stock_df = stock_df.tail(1)

    max_SMA = max(stock_df['20_SMA'].item(), stock_df['50_SMA'].item(), stock_df['200_SMA'].item())
    min_SMA = min(stock_df['20_SMA'].item(), stock_df['50_SMA'].item(), stock_df['200_SMA'].item())
    ABS_Spread = max_SMA - min_SMA
    stock_df['Spread%'] = round((ABS_Spread / stock_df['200_SMA'].item()) * 100,2)

    return stock_df

# function to compute stock attributes
def get_common_features(stock_ids, df_mypf):

  df_prec_dev = pd.DataFrame()
  df_tmp = get_screener_features()
  df_rs = get_relative_strength(stock_ids)

  for stock_id in stock_ids:
      tmp = stock_prec_dev(stock_id)
      tmp = tmp.reset_index()
      df_prec_dev = pd.concat([df_prec_dev, tmp], ignore_index = True)
  df_prec_dev = pd.merge(df_prec_dev, df_mypf, on= 'Symbol')
  df_prec_dev = pd.merge(df_prec_dev, df_tmp, on= 'Symbol', how='left')
  df_prec_dev = pd.merge(df_prec_dev, df_rs, on= 'Symbol', how='left')
  #print(df_prec_dev.columns)
  df_prec_dev['Curr_PE'] = round(df_prec_dev['Close']/df_prec_dev['EPS'],1)
  df_prec_dev['Dev%_PE'] = round((df_prec_dev['Curr_PE'] - df_prec_dev['MedPE'])*100/df_prec_dev['MedPE'],2)
  df_prec_dev['Conviction'] = df_prec_dev['Conviction'] + '-' + df_prec_dev['CapType']
  return df_prec_dev

# function to arrange stock features
def arrange_features(df_stocks, common_cols, diff_cols):
  df_stocks_common = df_stocks[common_cols].drop_duplicates()
  df_stocks_diff = df_stocks[diff_cols]
  df_stocks_diff['Investment'] = df_stocks_diff['AvgCost'] * df_stocks_diff['Shares']
  df_stocks_diff = df_stocks_diff.groupby(['Symbol'])[['Shares', 'Investment']].aggregate(['sum']).reset_index()
  df_stocks_diff.columns = ['Symbol', 'Shares', 'Investment']
  df_stocks_diff['AvgCost'] = round(df_stocks_diff['Investment']/df_stocks_diff['Shares'],2)
  df_stocks = pd.merge(df_stocks_diff, df_stocks_common, on='Symbol')
  return df_stocks

# plot fact distribution across dimension
def plot_pie_chart(df, dimension, fact):
  # grouping the data by category and calculating the sum of fact for each type
  grouped_data = df.groupby(dimension)[fact].sum()

  # sorting the grouped data in descending order
  grouped_data = grouped_data.sort_values(ascending=False)

  # creating a pie chart
  grouped_data.plot.pie(autopct='%1.1f%%', startangle=90, figsize=(6, 6))

  # adding a title and displaying the plot
  plt.title(f'{dimension} {fact} Distribution')
  plt.ylabel('')  # To hide the y-label
  plt.show()

In [7]:
# function to get portfolio features

def get_portfolio_features(df_common_features):

  print_date_time()
  print('-------------------')

  #df_common_features["Target"] = df_common_features["Target"].fillna(df_common_features["Max"])
  df_common_features['NTT'] = np.where(df_common_features['Strategy']== 'NTT', df_common_features["Target"], df_common_features['Max'])
  df_common_features['LTT'] = np.where(df_common_features['Strategy']== 'BTT', df_common_features["Target"], df_common_features['Max'])
  df_common_features['BOL'] = df_common_features['Min']

  tmp_df = df_common_features[df_common_features['Symbol'].isin(mypf_df[mypf_df['InPortfolio'] != 'NA'].Symbol.values)]
  print('qualified stocks: '+str(len(tmp_df['Symbol'].unique())))
  tmp_df1 = tmp_df[tmp_df['LatestQtr'] == 1]
  print('with latest results: '+str(len(tmp_df1['Symbol'].unique())))
  tmp_df1 = tmp_df1[tmp_df1['StarStock'] == 1]
  print('still star stocks: '+str(len(tmp_df1['Symbol'].unique())))
  tmp_df['Investment'] = tmp_df['AvgCost'] * tmp_df['Shares']
  tmp_df['Current'] = round(tmp_df['Close'] * tmp_df['Shares'],0)
  tmp_df['Previous'] = tmp_df['Prev_Close'] * tmp_df['Shares']
  tmp_df['EstimatedST'] = tmp_df['NTT'] * tmp_df['Shares']
  tmp_df['EstimatedLT'] = tmp_df['LTT'] * tmp_df['Shares']
  tmp_df['Current P/L'] = round((tmp_df['Current'] - tmp_df['Investment']),0)
  tmp_df['Today P/L%'] = round((tmp_df['Current'] - tmp_df['Previous'])*100/tmp_df['Previous'],2)
  tmp_df['Current P/L%'] = round((tmp_df['Current'] - tmp_df['Investment'])*100/tmp_df['Investment'],2)
  tmp_df['EstimatedST P/L%'] = round((tmp_df['EstimatedST'] - tmp_df['Investment'])*100/tmp_df['Investment'],2)
  tmp_df['EstimatedLT P/L%'] = round((tmp_df['EstimatedLT'] - tmp_df['Investment'])*100/tmp_df['Investment'],2)
  tmp_df['NTT%'] = round((tmp_df['NTT'] - tmp_df['Close'])*100/tmp_df['Close'],2)
  tmp_df['LTT%'] = round((tmp_df['LTT'] - tmp_df['Close'])*100/tmp_df['Close'],2)
  tmp_df['Gained%'] = round((tmp_df['Close'] - tmp_df['BOL'])*100/tmp_df['BOL'],2)
  investment = round(sum(tmp_df['AvgCost']*tmp_df['Shares']),0)
  current = round(sum(tmp_df['Close']*tmp_df['Shares']),0)
  tmp_df['InitAlloc%'] = round(tmp_df['Investment']*100/investment,2)
  tmp_df['CurrAlloc%'] = round(tmp_df['Current']*100/current,2)
  tmp_df['FTT'] = tmp_df['LTT']
  tmp_df.loc[tmp_df['Strategy'] == 'NTT', 'FTT'] = tmp_df['NTT']
  tmp_df['FTT%'] = tmp_df['LTT%']
  tmp_df.loc[tmp_df['Strategy'] == 'NTT', 'FTT%'] = tmp_df['NTT%']
  tmp_df['FTT Amt'] = round(tmp_df['FTT%'] * tmp_df['Current']/100,0)
  tmp_df['OTT%'] = round((tmp_df['FTT'] - tmp_df['AvgCost'])*100/tmp_df['AvgCost'],2)
  tmp_df['RRR Ind'] = round(tmp_df['Current P/L']/tmp_df['FTT Amt'],2)
  tmp_df['Risk Ind'] = round(tmp_df['Current P/L%']*tmp_df['CurrAlloc%'],0)

  return tmp_df

# function to print portfolio features
def print_portfolio_stats(df_portfolio_features, myinvmt_df):
  from pyxirr import xirr

  total_booked_amt, reserve_amt, cy_booked_amt, py_booked_amt = get_amt()

  dates = myinvmt_df['Date'].values
  dates = np.append(dates, datetime.date.today().strftime('%d-%b-%y'))
  investment = myinvmt_df['Investment'].values
  dates= pd.to_datetime(dates)

  current = round(sum(df_portfolio_features['Close']*df_portfolio_features['Shares']),0) + reserve_amt
  investment_xirr = np.append(investment, current)
  cagr = round(xirr(pd.DataFrame({"dates": dates, "amounts": investment_xirr}))*100,2)

  investment = -sum(investment)
  invested = round(sum(df_portfolio_features['AvgCost']*df_portfolio_features['Shares']),0) + reserve_amt
  previous = round(sum(df_portfolio_features['Prev_Close']*df_portfolio_features['Shares']),0) + reserve_amt
  cy_invested = investment + py_booked_amt

  today_pnl_amount = current-previous
  today_pnl_percentage = round((current-previous)*100/previous,2)

  curr_pnl_amount = current-invested
  curr_pnl_percentage = round((curr_pnl_amount)*100/(cy_invested),2)

  cy_pnl_amount = cy_booked_amt + curr_pnl_amount
  cy_pnl_percentage = round((cy_pnl_amount)*100/cy_invested,2)

  overall_pnl_amount = total_booked_amt + curr_pnl_amount
  overall_pnl_percentage = round((overall_pnl_amount)*100/investment,2)

  estimate_st = round(sum(df_portfolio_features['FTT']*df_portfolio_features['Shares']),0)  + reserve_amt
  est_st_pnl_amount = estimate_st-current
  est_st_pnl_percentage = round((est_st_pnl_amount)*100/current,2)

  estimate_lt = round(sum(df_portfolio_features['LTT']*df_portfolio_features['Shares']),0)  + reserve_amt
  est_lt_pnl_amount = estimate_lt-current
  est_lt_pnl_percentage = round((est_lt_pnl_amount)*100/current,2)

  total_profit = round(sum(df_portfolio_features[df_portfolio_features['Current P/L%'] > 0]['Current']) - sum(df_portfolio_features[df_portfolio_features['Current P/L%'] > 0]['Investment']),0)
  total_loss = round(sum(df_portfolio_features[df_portfolio_features['Current P/L%'] < 0]['Current']) - sum(df_portfolio_features[df_portfolio_features['Current P/L%'] < 0]['Investment']),0)

  cy_booked_percentage = round((cy_booked_amt)*100/current,2)
  py_booked_percentage = round((py_booked_amt)*100/investment,2)
  total_booked_percentage = round((total_booked_amt)*100/investment,2)

  print('-------------------')
  print('Initial Investment: ', format_amt(investment))
  print('CY Investment: ', format_amt(cy_invested))
  print('Reserve: ', format_amt(reserve_amt))
  print('Current: ',  format_amt(current))
  print('-------------------')
  print('Today PnL: '+ '{} ({}%)'.format(format_amt(today_pnl_amount), today_pnl_percentage))
  print('Current PnL: '+ '{} ({}%)'.format(format_amt(curr_pnl_amount), curr_pnl_percentage))
  print('CY Booked + Current PnL: '+ '{} ({}%)'.format(format_amt(cy_pnl_amount), cy_pnl_percentage))
  print('-------------------')
  print('Total profit: ', format_amt(total_profit))
  print('Total loss: ', format_amt(total_loss))
  print('-------------------')
  print('Total Booked + Current PnL: '+ '{} ({}%)'.format(format_amt(overall_pnl_amount), overall_pnl_percentage))
  print('Total Booked PnL: '+ '{} ({}%)'.format(format_amt(total_booked_amt), total_booked_percentage))
  print('Curr Year Booked PnL: '+ '{} ({}%)'.format(format_amt(cy_booked_amt), cy_booked_percentage))
  print('Prev Year Booked PnL: '+ '{} ({}%)'.format(format_amt(py_booked_amt), py_booked_percentage))
  print('===================')
  print('Est FTT: ',  format_amt(estimate_st))
  print('Est FTT PnL: '+ '{} ({}%)'.format(format_amt(est_st_pnl_amount), est_st_pnl_percentage))

  print('===================')
  print('Deployed: ', format_amt(investment))

  print('Current: ', format_amt(current))

  print('CAGR/XIRR %: '+'{}%'.format(cagr))

In [8]:
# get start and end date
start_date, end_date = get_start_end_date()

# get portfolio and prospects data
mypfs_df = get_mypfs_df()
mypps_df = get_mypps_df()
myinvmt_df = get_myinvmt_df()

# merge above datasets
mypf_df = pd.merge(mypfs_df, mypps_df, on="Symbol")

# seggregate dm and sv portfolio
dm_pf = mypf_df[mypf_df['InPortfolio'] == 'DM']
sv_pf = mypf_df[mypf_df['InPortfolio'] == 'SV']

# build portfolio stock dataframe
dm_stocks = get_stock_ids(dm_pf)
sv_stocks = get_stock_ids(sv_pf)
df_stocks = pd.concat([dm_pf,sv_pf], ignore_index = True)

# arrange common and diff stock features
common_cols = ['Symbol', 'Target', 'Criteria', 'Strategy', 'CumlRnk', 'LatestQtr', 'StarStock', 'Conviction', 'Category', 'InFolio', 'XIRR', 'MBQ']
diff_cols = ['Symbol', 'AvgCost', 'Shares']
df_stocks = arrange_features(df_stocks, common_cols, diff_cols)

# get common features
stock_ids = df_stocks['Symbol'].values
df_common_features = get_common_features(stock_ids, df_stocks)

df_common_features.reset_index(drop=True, inplace=True)
df_common_features.drop(['Date'], axis=1, inplace=True)
# get and print portfolio features
df_portfolio_features = get_portfolio_features(df_common_features)

print_portfolio_stats(df_portfolio_features, myinvmt_df)

df = df_portfolio_features
#plot_pie_chart(df, 'CapType', 'Current')
list_ox40n = list(df[df['MBQ'].str.contains('OX40N', na=False)]['Symbol'].values)

Run date time (IST): 2026-03-27 10:04:10
-------------------
qualified stocks: 86
with latest results: 26
still star stocks: 16
-------------------
Initial Investment:  1.36 C
CY Investment:  1.62 C
Reserve:  1.61 K
Current:  1.29 C
-------------------
Today PnL: -2.04 L (-1.55%)
Current PnL: -47.75 L (-29.39%)
CY Booked + Current PnL: -31.86 L (-19.61%)
-------------------
Total profit:  41.15 K
Total loss:  -48.16 L
-------------------
Total Booked + Current PnL: -4.88 L (-3.6%)
Total Booked PnL: 42.87 L (31.64%)
Curr Year Booked PnL: 15.89 L (12.28%)
Prev Year Booked PnL: 26.98 L (19.91%)
===================
Est FTT:  2.48 C
Est FTT PnL: 1.19 C (91.61%)
===================
Deployed:  1.36 C
Current:  1.29 C
CAGR/XIRR %: -2.26%

In [9]:
# top 5 near their targets
cols = ['Symbol', 'Today P/L%', 'Current P/L%', 'FTT%', 'OTT%', 'FTT Amt', 'Current P/L', 'Current', 'FTT', 'Dev%_PE', 'RSI_14','Conviction', 'Spread%',  'CumlRnk', 'RRR Ind', 'CurrAlloc%', 'Gained%', 'Criteria', 'Strategy', 'Category']
df_tmp = df_portfolio_features[~df_portfolio_features['Symbol'].isin(['ENRIN','BLUSPRING','DIGITIDE'])]
df_tmp = df_tmp.sort_values(by = 'FTT Amt', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
50,MASFIN,-1.52,-9.02,33.62,21.57,29971.0,-8835.0,89145.0,397.04,-21.41,43.0,H-SC,3.47,167.0,-0.29,0.69,21.59,XR,ATH,FINANCE
77,TTKPRESTIG,-1.32,-43.53,77.24,0.09,43960.0,-43864.0,56913.0,770.00,32.12,34.0,M-SC,20.66,250.0,-1.00,0.44,0.00,OX40N,NTT,DURABLES
37,ICICIGI,-0.58,-6.77,28.01,19.34,52255.0,-13549.0,186560.0,2252.93,-21.55,35.0,X-MC,4.44,66.0,-0.26,1.44,3.13,X40,ATH,INSURANCE
2,ABBOTINDIA,-0.21,-11.60,33.57,18.07,53074.0,-20755.0,158100.0,35195.00,-24.86,46.0,X-MC,10.45,58.0,-0.39,1.22,3.39,X40,ATH,PHARMA
67,SONACOMS,-2.74,-13.94,61.63,39.09,53651.0,-14105.0,87054.0,804.02,-31.81,47.0,M-MC,6.80,193.0,-0.26,0.67,23.15,AR,ATH,AUTO

In [10]:
# top 5 today
df_tmp = df_portfolio_features.sort_values(by = 'Today P/L%', ascending=False)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
73,TCS,1.03,-29.49,79.50,26.57,259704.0,-136601.0,326672.0,4311.59,-40.35,33.0,X-LC,17.83,2.0,-0.53,2.53,1.95,X40,ATH,IT
33,HCLTECH,0.85,-9.59,36.97,23.83,80860.0,-23207.0,218717.0,1908.19,-4.88,49.0,X-LC,11.54,8.0,-0.29,1.69,6.20,X40,ATH,IT
8,AWL,0.73,-36.57,163.32,67.02,369105.0,-130308.0,226001.0,485.00,-65.82,48.0,X-SC,26.07,81.0,-0.35,1.75,6.90,XY24,NTT,FMCG
17,CAMS,0.71,-15.03,46.49,24.48,99491.0,-37851.0,214005.0,950.00,-18.64,44.0,X-SC,13.54,89.0,-0.38,1.65,4.19,X40N,NTT,MISC
39,IEX,0.43,-17.07,79.21,48.63,131350.0,-34129.0,165825.0,219.00,-44.77,50.0,H-SC,15.86,137.0,-0.26,1.28,5.91,XR,NTT,MISC

In [11]:
# bottom 5 today
df_tmp = df_portfolio_features.sort_values(by = 'Today P/L%', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
55,RAJESHEXPO,-5.00,-83.65,512.22,0.07,114850.0,-114755.0,22422.0,518.0,721.97,19.0,L-SC,37.59,268.0,-1.00,0.17,0.0,OX40N,NTT,JEWELLERY
29,GREENPANEL,-4.89,-53.85,210.15,43.14,177560.0,-98586.0,84492.0,537.0,89.28,27.0,M-SC,23.90,225.0,-0.56,0.65,0.0,XY24,NTT,MISC
14,BOSCH-HCIL,-4.65,-49.61,98.43,-0.01,63389.0,-63405.0,64400.0,2282.0,13073.91,26.0,M-SC,5.82,231.0,-1.00,0.50,0.0,OX40N,BTT,AC
75,TMPV,-4.53,-30.90,97.66,36.58,240123.0,-109965.0,245876.0,600.0,-85.81,34.0,X-LC,8.34,4.0,-0.46,1.90,0.0,XY24,NTT,AUTO
22,DEN,-4.39,-53.38,204.75,42.07,80622.0,-45088.0,39376.0,75.0,39.90,29.0,M-SC,19.63,235.0,-0.56,0.30,0.0,AR,NTT,ENTERTAINMENT

In [12]:
# top 5 to exit based on CumlRnk
df_tmp = df_portfolio_features[~df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])]
df_tmp = df_tmp[(df_tmp['Current P/L%'] > -1) & (df_tmp['Current P/L%'] < 1)].sort_values(by = 'CumlRnk', ascending=False)
df_tmp[cols].head()

Empty DataFrame
Columns: [Symbol, Today P/L%, Current P/L%, FTT%, OTT%, FTT Amt, Current P/L, Current, FTT, Dev%_PE, RSI_14, Conviction, Spread%, CumlRnk, RRR Ind, CurrAlloc%, Gained%, Criteria, Strategy, Category]
Index: []

In [13]:
# OX40N stocks to exit
df_tmp = df_portfolio_features[(df_portfolio_features['Symbol'].isin(list_ox40n))].sort_values(by = 'Current P/L%', ascending=False)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
26,FINCABLES,-1.99,3.30,101.27,107.91,154454.0,4873.0,152517.0,1641.55,-7.15,45.0,M-SC,7.94,220.0,0.03,1.18,14.74,OX40N,ATH,CABLES
66,SIS,-3.24,-36.46,90.85,21.26,64091.0,-40486.0,70546.0,528.00,1648.19,41.0,H-SC,14.57,168.0,-0.63,0.55,4.89,OX40N,NTT,MISC
18,CERA,0.04,-38.15,100.30,23.89,109125.0,-67104.0,108799.0,9475.00,-40.33,47.0,H-SC,19.11,153.0,-0.61,0.84,4.56,OX40N,NTT,CERAMICS
72,TATAELXSI,0.27,-39.11,116.83,32.03,93783.0,-51562.0,80273.0,9161.00,-23.89,40.0,H-SC,21.20,158.0,-0.55,0.62,4.59,OX40N,NTT,IT
48,KANSAINER,-0.12,-42.13,96.08,13.47,149942.0,-113607.0,156060.0,340.00,-50.17,38.0,H-SC,21.67,162.0,-0.76,1.21,9.01,XY24,NTT,PAINTS

In [14]:
# top 5 to book for rotation
df_tmp = df_portfolio_features[(df_portfolio_features['Current P/L%'] > 20) ].sort_values(by = 'CumlRnk', ascending=False)
df_tmp[cols].head()

Empty DataFrame
Columns: [Symbol, Today P/L%, Current P/L%, FTT%, OTT%, FTT Amt, Current P/L, Current, FTT, Dev%_PE, RSI_14, Conviction, Spread%, CumlRnk, RRR Ind, CurrAlloc%, Gained%, Criteria, Strategy, Category]
Index: []

In [15]:
# top 5 to monitor for exit
df_tmp = df_portfolio_features[~df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])]
df_tmp = df_tmp[(df_tmp['Current P/L%'] > 0) ].sort_values(by = 'Dev%_PE', ascending=False)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
26,FINCABLES,-1.99,3.30,101.27,107.91,154454.0,4873.0,152517.0,1641.55,-7.15,45.0,M-SC,7.94,220.0,0.03,1.18,14.74,OX40N,ATH,CABLES
1,ABB,-2.65,10.96,31.18,45.57,90517.0,28685.0,290304.0,7934.00,-28.65,50.0,H-MC,13.31,125.0,0.32,2.24,28.91,AR,NTT,ELECTRICAL

In [16]:
# top 5 to book for rotation from weak conviction
df_tmp = df_portfolio_features[~df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])]
df_tmp = df_tmp[~df_tmp['Criteria'].isin(['XY25','XY24','X40', 'X40N'])].sort_values(by = 'RRR Ind', ascending=False)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
1,ABB,-2.65,10.96,31.18,45.57,90517.0,28685.0,290304.0,7934.00,-28.65,50.0,H-MC,13.31,125.0,0.32,2.24,28.91,AR,NTT,ELECTRICAL
26,FINCABLES,-1.99,3.30,101.27,107.91,154454.0,4873.0,152517.0,1641.55,-7.15,45.0,M-SC,7.94,220.0,0.03,1.18,14.74,OX40N,ATH,CABLES
40,INDIAMART,0.11,-13.28,138.39,106.72,148014.0,-16382.0,106954.0,4810.62,-60.94,39.0,H-SC,12.29,140.0,-0.11,0.83,6.99,AR,ATH,MISC
85,ZYDUSLIFE,0.39,-4.33,41.77,35.63,83750.0,-9072.0,200502.0,1286.17,-16.67,52.0,H-MC,5.28,120.0,-0.11,1.55,11.62,AR,ATH,PHARMA
84,WIPRO,0.26,-22.26,121.58,72.27,160166.0,-37711.0,131737.0,420.00,-29.71,32.0,M-LC,17.98,98.0,-0.24,1.02,1.07,XR,NTT,IT

In [17]:
# top 5 to accumulate based on lowest RSI_14
df_tmp = df_portfolio_features[df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])].sort_values(by = 'RSI_14', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
53,PGHH,-0.62,-28.11,83.62,32.01,128360.0,-60016.0,153504.0,17616.87,-51.42,21.0,X-MC,17.07,57.0,-0.47,1.19,1.46,X40,ATH,FMCG
38,ICICIPRULI,-2.05,-12.38,49.20,30.73,84928.0,-24388.0,172617.0,790.00,-35.93,22.0,X-MC,5.58,78.0,-0.29,1.33,0.00,X40,ATH,INSURANCE
58,RELAXO,-2.48,-66.44,353.79,52.31,172366.0,-96440.0,48720.0,1176.00,-64.28,24.0,X-SC,28.41,92.0,-0.56,0.38,1.69,X40N,NTT,FOOTWEAR
9,BAJAJHFL,-1.81,-30.59,133.59,62.13,253166.0,-83536.0,189510.0,181.50,-42.81,25.0,X-MC,20.54,60.0,-0.33,1.47,0.00,X40N,ATH,FINANCE
27,GILLETTE,-2.04,-11.07,45.88,29.72,103588.0,-28116.0,225780.0,10978.86,-31.71,28.0,X-SC,11.80,83.0,-0.27,1.75,0.00,X40,ATH,FMCG

In [18]:
# top 5 to accumulate based on Spread and CumlRnk
df_tmp = df_portfolio_features[df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])]
df_tmp = df_tmp[(df_tmp['CumlRnk'] < 100)].sort_values(by = 'Spread%', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
65,SIEMENS,-2.28,-18.57,54.14,25.51,82041.0,-34560.0,151535.0,4671.50,27.32,43.0,H-LC,1.80,51.0,-0.42,1.17,11.59,AR,ATH,ELECTRICAL
78,UNITDSPR,-2.36,-5.92,28.37,20.77,62493.0,-13864.0,220280.0,1644.00,-16.49,41.0,X-MC,2.36,64.0,-0.22,1.70,0.43,X40N,NTT,BREWERIES
82,VOLTAS,-2.91,3.96,39.66,45.20,79056.0,7593.0,199335.0,1856.00,18.97,41.0,X-MC,3.37,79.0,0.10,1.54,11.03,XY25,NTT,AC
59,RELIANCE,-2.46,-11.52,41.61,25.30,73988.0,-23149.0,177814.0,1952.00,-13.88,43.0,X-LC,3.58,21.0,-0.31,1.37,18.72,XY25,BTT,REFINERIES
37,ICICIGI,-0.58,-6.77,28.01,19.34,52255.0,-13549.0,186560.0,2252.93,-21.55,35.0,X-MC,4.44,66.0,-0.26,1.44,3.13,X40,ATH,INSURANCE

In [19]:
# top 5 to accumulate based on lowest Gained%
df_tmp = df_portfolio_features[df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])].sort_values(by = 'Gained%', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
9,BAJAJHFL,-1.81,-30.59,133.59,62.13,253166.0,-83536.0,189510.0,181.50,-42.81,25.0,X-MC,20.54,60.0,-0.33,1.47,0.00,X40N,ATH,FINANCE
27,GILLETTE,-2.04,-11.07,45.88,29.72,103588.0,-28116.0,225780.0,10978.86,-31.71,28.0,X-SC,11.80,83.0,-0.27,1.75,0.00,X40,ATH,FMCG
38,ICICIPRULI,-2.05,-12.38,49.20,30.73,84928.0,-24388.0,172617.0,790.00,-35.93,22.0,X-MC,5.58,78.0,-0.29,1.33,0.00,X40,ATH,INSURANCE
75,TMPV,-4.53,-30.90,97.66,36.58,240123.0,-109965.0,245876.0,600.00,-85.81,34.0,X-LC,8.34,4.0,-0.46,1.90,0.00,XY24,NTT,AUTO
3,ACC,-2.73,-40.45,193.55,74.81,309045.0,-108456.0,159672.0,3906.00,-57.90,29.0,X-SC,19.07,85.0,-0.35,1.23,0.06,XY24,BTT,CEMENT

In [20]:
# top 5 to accumulate based on lowest CurrAlloc%
df_tmp = df_portfolio_features[df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])].sort_values(by = 'CurrAlloc%', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
58,RELAXO,-2.48,-66.44,353.79,52.31,172366.0,-96440.0,48720.0,1176.00,-64.28,24.0,X-SC,28.41,92.0,-0.56,0.38,1.69,X40N,NTT,FOOTWEAR
12,BATAINDIA,-2.86,-58.64,226.91,35.20,120750.0,-75455.0,53215.0,2096.00,-30.25,28.0,X-SC,32.31,91.0,-0.62,0.41,2.46,X40,NTT,FOOTWEAR
54,QUESS,-1.22,-28.43,142.98,73.90,109281.0,-30362.0,76431.0,424.00,-61.43,37.0,X-SC,21.76,80.0,-0.28,0.59,2.73,XY24,NTT,MISC
36,HONAUT,-1.22,-27.76,109.47,51.31,152492.0,-53538.0,139300.0,58357.33,-39.89,32.0,X-SC,16.57,90.0,-0.35,1.08,2.37,X40N,ATH,ELECTRICAL
51,MEDANTA,-1.42,-14.72,49.06,27.12,73851.0,-25985.0,150532.0,1486.00,-17.41,35.0,X-SC,13.38,87.0,-0.35,1.16,2.82,XY24,NTT,HEALTHCARE

In [21]:
# top 5 to accumulate based on CumlRnk
df_tmp = df_portfolio_features.sort_values(by = 'CumlRnk', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
45,ITC,-0.86,-22.78,54.19,19.06,142337.0,-77504.0,262662.0,452.00,-57.54,35.0,X-LC,18.95,1.0,-0.54,2.03,0.93,X40,NTT,FMCG
73,TCS,1.03,-29.49,79.50,26.57,259704.0,-136601.0,326672.0,4311.59,-40.35,33.0,X-LC,17.83,2.0,-0.53,2.53,1.95,X40,ATH,IT
43,INFY,-0.06,-12.98,54.27,34.24,147765.0,-40610.0,272278.0,1972.00,-31.42,42.0,X-LC,15.05,3.0,-0.27,2.10,4.71,X40,NTT,IT
75,TMPV,-4.53,-30.90,97.66,36.58,240123.0,-109965.0,245876.0,600.00,-85.81,34.0,X-LC,8.34,4.0,-0.46,1.90,0.00,XY24,NTT,AUTO
33,HCLTECH,0.85,-9.59,36.97,23.83,80860.0,-23207.0,218717.0,1908.19,-4.88,49.0,X-LC,11.54,8.0,-0.29,1.69,6.20,X40,ATH,IT

In [22]:
# top 5 for average up
df_tmp = df_portfolio_features[(df_portfolio_features['Dev%_200'] > 5)].sort_values(by = 'CurrAlloc%', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
1,ABB,-2.65,10.96,31.18,45.57,90517.0,28685.0,290304.0,7934.0,-28.65,50.0,H-MC,13.31,125.0,0.32,2.24,28.91,AR,NTT,ELECTRICAL

In [23]:
# top 5 RSP
df_tmp = df_portfolio_features.sort_values(by = 'RSP', ascending=False)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
30,HAPPSTMNDS,0.06,-50.27,271.71,84.85,173177.0,-64429.0,63736.0,1480.71,-40.86,54.0,H-SC,25.61,152.0,-0.37,0.49,18.03,AR,ATH,IT
5,ANGELONE,-0.31,-1.98,26.68,24.18,79767.0,-6025.0,298975.0,303.00,-85.87,54.0,X-SC,10.04,97.0,-0.08,2.31,15.08,X40N,NTT,FINANCE
24,DMART,0.36,-5.65,37.36,29.60,87983.0,-14100.0,235500.0,5391.45,-20.41,56.0,X-LC,6.85,14.0,-0.16,1.82,7.64,X40N,ATH,FMCG
47,JSWINFRA,-0.21,-12.29,32.74,16.43,63688.0,-27248.0,194526.0,342.00,-24.80,51.0,X-MC,11.46,61.0,-0.43,1.50,6.78,X40N,NTT,REALTY
33,HCLTECH,0.85,-9.59,36.97,23.83,80860.0,-23207.0,218717.0,1908.19,-4.88,49.0,X-LC,11.54,8.0,-0.29,1.69,6.20,X40,ATH,IT

In [24]:
# Top N allocation
df_tmp = df_portfolio_features.sort_values(by = 'CurrAlloc%', ascending=False)
top_n_values = [10, 25, 50]

sum_df = pd.DataFrame({
    'Top_N': top_n_values,
    'Sum_Alloc%': [df_tmp['CurrAlloc%'].head(n).sum() for n in top_n_values]
})

sum_df

   Top_N  Sum_Alloc%
0     10       20.81
1     25       46.02
2     50       78.36

In [25]:
# market-cap-wise allocation
df_tmp = df_portfolio_features[cols]
df_tmp.groupby(df_tmp['Conviction'].str[-2:])['CurrAlloc%'].sum().sort_values(ascending=False)

Conviction
SC    44.20
MC    30.13
LC    25.66
Name: CurrAlloc%, dtype: float64

In [26]:
# criteria-wise allocation
df_portfolio_features.groupby('Criteria')['CurrAlloc%'].sum().sort_values(ascending=False)

Criteria
XY24     26.90
X40      25.54
X40N     15.34
AR        9.14
XR        8.27
XY25      7.39
OX40N     6.61
SR        0.80
Name: CurrAlloc%, dtype: float64

In [27]:
# conviction-wise allocation
df_portfolio_features.groupby('Conviction')['CurrAlloc%'].sum().sort_values(ascending=False)

Conviction
X-LC    23.47
X-MC    22.64
H-SC    21.55
X-SC    12.31
M-SC     9.83
H-MC     5.09
M-MC     2.05
H-LC     1.17
M-LC     1.02
L-SC     0.51
L-MC     0.35
Name: CurrAlloc%, dtype: float64

In [28]:
# sector-wise stats
df_tmp = df_portfolio_features.groupby('Category')[['CurrAlloc%', 'Current', 'Current P/L', 'FTT Amt']].sum().sort_values(by=['Current', 'Current P/L'], ascending=False)
df_tmp['Current P/L%'] = round(df_tmp['Current P/L'] * 100 / df_tmp['Current'], 2)
df_tmp['FTT%'] = round(df_tmp['FTT Amt'] * 100 / df_tmp['Current'], 2)
cols = ['CurrAlloc%', 'Current P/L%', 'FTT%']
df_tmp[cols].sort_values(by=['CurrAlloc%'], ascending=False)

               CurrAlloc%  Current P/L%    FTT%
Category
FMCG                15.17        -27.39   72.62
FINANCE             13.11        -26.77   78.43
IT                  11.91        -46.19  120.58
MISC                 6.96        -49.04  113.78
ELECTRICAL           6.52        -14.76   58.70
PAINTS               5.22        -45.85   71.17
INSURANCE            4.68        -11.81   50.07
BANKS                4.58        -29.77   95.65
PHARMA               4.19         -8.26   42.34
AUTO                 3.63        -39.15   94.36
AC                   2.04        -21.16   54.01
HEALTHCARE           1.88        -46.86   85.19
FOOTWEAR             1.80        -90.39  166.72
TRAVEL               1.79        -93.93  191.03
DURABLES             1.75        -71.36  113.04
APPARELS             1.73        -19.61   60.41
BREWERIES            1.70         -6.29   28.37
REALTY               1.50        -14.01   32.74
REFINERIES           1.37        -13.02   41.61
CERAMICS             1.37        -72.75  125.23
CEMENT               1.23        -67.92  193.55
CABLES               1.18          3.20  101.27
ENGINEERING          1.08        -73.94  153.50
CHEMICALS            1.06        -94.63  253.42
JEWELLERY            1.00       -147.57  233.58
ENTERTAINMENT        0.74       -100.57  220.19
TEXTILES             0.46        -55.04   99.25
HOTELS               0.34       -158.25  249.34

In [29]:
# money to be made criteria-wise
df_portfolio_features.groupby('Criteria')['FTT Amt'].agg(['sum', 'count']).sort_values(by='sum', ascending=False)

                sum  count
Criteria
XY24      4118880.0     21
X40       1868467.0     16
XR        1423114.0     12
AR        1387316.0     10
X40N      1316560.0     10
OX40N      936461.0     10
XY25       484305.0      5
SR         315950.0      2

In [30]:
# money to be made conviction-wise
df_portfolio_features.groupby('Conviction')['FTT Amt'].agg(['sum', 'count']).sort_values(by='sum', ascending=False)

                  sum  count
Conviction
H-SC        4007231.0     24
X-MC        1802831.0     15
X-LC        1739117.0     13
M-SC        1647129.0     14
X-SC        1589736.0     10
H-MC         420437.0      3
L-SC         224480.0      2
M-LC         160166.0      1
M-MC         120963.0      2
H-LC          82041.0      1
L-MC          56922.0      1

In [31]:
# money to be made criteria and conviction-wise
df_portfolio_features.groupby(['Conviction', 'Criteria'])['FTT Amt'].agg(['sum', 'count']).sort_values(by='sum', ascending=False)

                           sum  count
Conviction Criteria
H-SC       XY24      1390668.0      6
           AR         996735.0      5
M-SC       XY24       952378.0      6
X-LC       X40        926560.0      7
H-SC       XR         901805.0      7
X-SC       XY24       861282.0      4
X-MC       X40        717569.0      7
           X40N       546853.0      4
X-SC       X40N       504116.0      4
M-SC       OX40N      419538.0      5
H-SC       OX40N      402073.0      4
X-LC       XY24       391252.0      2
H-SC       SR         315950.0      2
X-MC       XY24       277130.0      2
X-LC       X40N       265591.0      2
X-MC       XY25       261279.0      2
H-MC       XY24       246170.0      1
X-SC       X40        224338.0      2
M-SC       XR         194591.0      2
H-MC       AR         174267.0      2
M-LC       XR         160166.0      1
X-LC       XY25       155714.0      2
L-SC       OX40N      114850.0      1
           XR         109630.0      1
H-LC       AR          82041.0      1
M-SC       AR          80622.0      1
M-MC       XY25        67312.0      1
L-MC       XR          56922.0      1
M-MC       AR          53651.0      1

In [32]:
# notebook execution time

end_time = time.time()
execution_time = round(end_time - start_time, 0)
print(f"Notebook execution time: {execution_time} seconds")

Notebook execution time: 25.0 seconds