<a href="https://colab.research.google.com/github/ankit-rathi/Quantvesting_v2/blob/main/myStocks_Portfolio_Analysis.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
'''
!pip install pandas==2.2.2 -qq
!pip install pyxirr -qq
!pip install ta -qq
!pip install yfinance==0.2.59 -qq
'''

'\n!pip install pandas==2.2.2 -qq\n!pip install pyxirr -qq\n!pip install ta -qq\n!pip install yfinance==0.2.59 -qq\n'

In [2]:
# import libraries

import numpy as np
import pandas as pd
import datetime
import warnings
warnings.filterwarnings('ignore')
import yfinance as yfin
import ta
import matplotlib.pyplot as plt
import requests

In [3]:
# notebook start time
import time
import datetime
import pytz

start_time = time.time()

# function to print date timestamp
def print_date_time():
  tz_NY = pytz.timezone('Asia/Kolkata')
  datetime_NY = datetime.datetime.now(tz_NY)
  print("Run date time (IST):", datetime_NY.strftime("%Y-%m-%d %H:%M:%S"))

In [4]:
# function to get booked and reserved amount
def get_amt():
  # fetch the JSON data from the URL
  url = "https://raw.githubusercontent.com/ankit-rathi/Tradevesting_v1/main/data/myPortfolioAmts.json"
  response = requests.get(url)
  pf_amts = response.json()  # parse the JSON data

  # extract values from the JSON
  py_booked_amt_dm = pf_amts["py_booked_amt_dm"]
  py_booked_amt_sv = pf_amts["py_booked_amt_sv"]
  cy_booked_amt_dm = pf_amts["cy_booked_amt_dm"]
  cy_booked_amt_sv = pf_amts["cy_booked_amt_sv"]
  reserve_amt_dm = pf_amts["reserve_amt_dm"]
  reserve_amt_sv = pf_amts["reserve_amt_sv"]

  # perform calculations
  py_booked_amt = py_booked_amt_dm + py_booked_amt_sv
  cy_booked_amt = cy_booked_amt_dm + cy_booked_amt_sv
  reserve_amt = reserve_amt_dm + reserve_amt_sv
  total_booked_amt = py_booked_amt + cy_booked_amt

  return total_booked_amt, reserve_amt, cy_booked_amt, py_booked_amt

gen_output = 0

In [5]:
# function to format the amount
def format_amt(number):
    abs_number = abs(number)

    if abs_number >= 1_00_00_000:  # Crores
        formatted_amt = f"{number / 1_00_00_000:.2f} C"
    elif abs_number >= 1_00_000:  # Lakhs
        formatted_amt = f"{number / 1_00_000:.2f} L"
    elif abs_number >= 1_000:  # Thousands
        formatted_amt = f"{number / 1_000:.2f} K"
    else:
        formatted_amt = f"{number:.2f}"

    return formatted_amt

# function to set start and end date
def get_start_end_date():
  start_date = (datetime.date.today() + datetime.timedelta(days=-365)).strftime('%Y-%m-%d')
  end_date = (datetime.date.today() + datetime.timedelta(days=1)).strftime('%Y-%m-%d')
  return start_date, end_date

# function to fetch my portfolio csv
def get_mypfs_df():
  mypfs_df = pd.read_csv('https://raw.githubusercontent.com/ankit-rathi/Tradevesting_v1/main/data/myPortfolioStocks.csv')
  return mypfs_df

# function to fetch my prospects csv
def get_mypps_df():
  mypps_df = pd.read_csv('https://raw.githubusercontent.com/ankit-rathi/Tradevesting_v1/main/data/myProspectsScrips.csv')
  return mypps_df

# function to fetch screener data
def get_myscreen_df():
  myscreen_df = pd.read_csv('https://raw.githubusercontent.com/ankit-rathi/Tradevesting_v1/main/data/myScreenerDB.csv')
  return myscreen_df

# function to fetch momentum data
def get_myinvmt_df():
  myinvmt_df = pd.read_csv('https://raw.githubusercontent.com/ankit-rathi/Tradevesting_v1/main/data/myInvestments.csv')
  return myinvmt_df

# function to get the stock ids
def get_stock_ids(df_pf):
  stock_n100 = df_pf['Symbol'].unique()

  exclude = ['CADILAHC','MMTC', 'MASFIN']

  stock_ids = df_pf[~df_pf['Symbol'].isin(exclude) ]['Symbol'].unique()

  #mypf = mypf[mypf.Forecast.notnull()]
  #stock_ids = mypf['Symbol'].unique()

  #stock_ids.sort()
  return stock_ids

# get features from screener data
def get_screener_features():
  myscreen_df = get_myscreen_df()
  cols = ['Symbol', 'EPS', 'MedPE', 'ROCE%', 'ROE%', 'CapType']
  return myscreen_df[cols]

# get relative strength
def get_relative_strength(stock_list):

    # Dictionary to store stock tickers and their corresponding percentage price change
    stock_changes = {}

    # Loop through each stock and fetch its price data
    for stock in stock_list:
        try:
            # Download the stock data for the given date range
            stock_data = yfin.Ticker(stock + '.NS').history(period='1mo', interval='1d')[map(str.title, ['open', 'close', 'low', 'high', 'volume'])]

            # Calculate the percentage change for the stock
            if len(stock_data) > 0:
                start_price = stock_data['Close'].iloc[0]
                end_price = stock_data['Close'].iloc[-1]
                percent_change = round(((end_price - start_price) / start_price) * 100, 2)
                stock_changes[stock] = percent_change
            else:
                stock_changes[stock] = np.nan  # If no data is available, set to NaN

        except Exception as e:
            print(f"Error fetching data for {stock}: {e}")
            stock_changes[stock] = np.nan

    # Create a DataFrame with stock tickers and their percentage changes
    df = pd.DataFrame(list(stock_changes.items()), columns=['Symbol', 'Percent_Change'])

    # Drop any stocks with missing data (NaN values)
    df = df.dropna()

    # Calculate the percentile rank based on percentage change
    df['RSP'] = round(df['Percent_Change'].rank(pct=True) * 100, 2)
    cols = ['Symbol', 'RSP']
    df = df[cols]
    # Sort by percentile rank (optional)
    df = df.sort_values(by='RSP', ascending=False).reset_index(drop=True)

    return df

In [6]:
# function to get stock technicals
def stock_prec_dev(stock_symbol):
    #stock_symbol = 'ULTRACEMCO.NS'
    short_window = 20
    mid_window = 50
    long_window = 200
    moving_avg = 'SMA'

    start = datetime.datetime(*map(int, start_date.split('-')))
    end = datetime.datetime(*map(int, end_date.split('-')))

    stock_df = yfin.Ticker(stock_symbol + '.NS').history(period='max', interval='1d')[map(str.title, ['open', 'close', 'low', 'high', 'volume'])]

    stock_df['Max'] = round(max(stock_df['Close']),2)
    stock_df = stock_df[(stock_df.index <= end_date) & (stock_df.index >= start_date)]
    stock_df['200_SMA'] = round(stock_df['Close'].rolling(window = 200, min_periods = 1).mean(),0)
    stock_df['Dev%_200'] = round((stock_df['Close'] - stock_df['200_SMA'])*100/stock_df['200_SMA'],2)
    stock_df.dropna(axis = 0, inplace = True) # remove any null rows

    stock_df['20_SMA'] = stock_df['Close'].rolling(window=20).mean()
    stock_df['50_SMA'] = stock_df['Close'].rolling(window=50).mean()
    stock_df['Symbol'] = stock_symbol

    stock_df['Close'] = round(stock_df['Close'],2)
    stock_df['Min'] = round(min(stock_df['Close']),2)
    stock_df['RSI_14'] = ta.momentum.RSIIndicator(close=stock_df['Close'], window=14).rsi()
    stock_df['RSI_14'] = round(stock_df['RSI_14'],0)
    stock_df['Prev_Close'] = stock_df['Close'].shift(1)
    stock_df.drop(['Open', 'Low', 'High', 'Volume'], axis=1, inplace=True)
    stock_df = stock_df.tail(1)

    max_SMA = max(stock_df['20_SMA'].item(), stock_df['50_SMA'].item(), stock_df['200_SMA'].item())
    min_SMA = min(stock_df['20_SMA'].item(), stock_df['50_SMA'].item(), stock_df['200_SMA'].item())
    ABS_Spread = max_SMA - min_SMA
    stock_df['Spread%'] = round((ABS_Spread / stock_df['200_SMA'].item()) * 100,2)

    return stock_df

# function to compute stock attributes
def get_common_features(stock_ids, df_mypf):

  df_prec_dev = pd.DataFrame()
  df_tmp = get_screener_features()
  df_rs = get_relative_strength(stock_ids)

  for stock_id in stock_ids:
      tmp = stock_prec_dev(stock_id)
      tmp = tmp.reset_index()
      df_prec_dev = pd.concat([df_prec_dev, tmp], ignore_index = True)
  df_prec_dev = pd.merge(df_prec_dev, df_mypf, on= 'Symbol')
  df_prec_dev = pd.merge(df_prec_dev, df_tmp, on= 'Symbol', how='left')
  df_prec_dev = pd.merge(df_prec_dev, df_rs, on= 'Symbol', how='left')
  #print(df_prec_dev.columns)
  df_prec_dev['Curr_PE'] = round(df_prec_dev['Close']/df_prec_dev['EPS'],1)
  df_prec_dev['Dev%_PE'] = round((df_prec_dev['Curr_PE'] - df_prec_dev['MedPE'])*100/df_prec_dev['MedPE'],2)
  df_prec_dev['Conviction'] = df_prec_dev['Conviction'] + '-' + df_prec_dev['CapType']
  return df_prec_dev

# function to arrange stock features
def arrange_features(df_stocks, common_cols, diff_cols):
  df_stocks_common = df_stocks[common_cols].drop_duplicates()
  df_stocks_diff = df_stocks[diff_cols]
  df_stocks_diff['Investment'] = df_stocks_diff['AvgCost'] * df_stocks_diff['Shares']
  df_stocks_diff = df_stocks_diff.groupby(['Symbol'])[['Shares', 'Investment']].aggregate(['sum']).reset_index()
  df_stocks_diff.columns = ['Symbol', 'Shares', 'Investment']
  df_stocks_diff['AvgCost'] = round(df_stocks_diff['Investment']/df_stocks_diff['Shares'],2)
  df_stocks = pd.merge(df_stocks_diff, df_stocks_common, on='Symbol')
  return df_stocks

# plot fact distribution across dimension
def plot_pie_chart(df, dimension, fact):
  # grouping the data by category and calculating the sum of fact for each type
  grouped_data = df.groupby(dimension)[fact].sum()

  # sorting the grouped data in descending order
  grouped_data = grouped_data.sort_values(ascending=False)

  # creating a pie chart
  grouped_data.plot.pie(autopct='%1.1f%%', startangle=90, figsize=(6, 6))

  # adding a title and displaying the plot
  plt.title(f'{dimension} {fact} Distribution')
  plt.ylabel('')  # To hide the y-label
  plt.show()

In [7]:
# function to get portfolio features

def get_portfolio_features(df_common_features):

  print_date_time()
  print('-------------------')

  #df_common_features["Target"] = df_common_features["Target"].fillna(df_common_features["Max"])
  df_common_features['NTT'] = np.where(df_common_features['Strategy']== 'NTT', df_common_features["Target"], df_common_features['Max'])
  df_common_features['LTT'] = np.where(df_common_features['Strategy']== 'BTT', df_common_features["Target"], df_common_features['Max'])
  df_common_features['BOL'] = df_common_features['Min']

  tmp_df = df_common_features[df_common_features['Symbol'].isin(mypf_df[mypf_df['InPortfolio'] != 'NA'].Symbol.values)]
  print('qualified stocks: '+str(len(tmp_df['Symbol'].unique())))
  tmp_df1 = tmp_df[tmp_df['LatestQtr'] == 1]
  print('with latest results: '+str(len(tmp_df1['Symbol'].unique())))
  tmp_df1 = tmp_df1[tmp_df1['StarStock'] == 1]
  print('still star stocks: '+str(len(tmp_df1['Symbol'].unique())))
  tmp_df['Investment'] = tmp_df['AvgCost'] * tmp_df['Shares']
  tmp_df['Current'] = round(tmp_df['Close'] * tmp_df['Shares'],0)
  tmp_df['Previous'] = tmp_df['Prev_Close'] * tmp_df['Shares']
  tmp_df['EstimatedST'] = tmp_df['NTT'] * tmp_df['Shares']
  tmp_df['EstimatedLT'] = tmp_df['LTT'] * tmp_df['Shares']
  tmp_df['Current P/L'] = round((tmp_df['Current'] - tmp_df['Investment']),0)
  tmp_df['Today P/L%'] = round((tmp_df['Current'] - tmp_df['Previous'])*100/tmp_df['Previous'],2)
  tmp_df['Current P/L%'] = round((tmp_df['Current'] - tmp_df['Investment'])*100/tmp_df['Investment'],2)
  tmp_df['EstimatedST P/L%'] = round((tmp_df['EstimatedST'] - tmp_df['Investment'])*100/tmp_df['Investment'],2)
  tmp_df['EstimatedLT P/L%'] = round((tmp_df['EstimatedLT'] - tmp_df['Investment'])*100/tmp_df['Investment'],2)
  tmp_df['NTT%'] = round((tmp_df['NTT'] - tmp_df['Close'])*100/tmp_df['Close'],2)
  tmp_df['LTT%'] = round((tmp_df['LTT'] - tmp_df['Close'])*100/tmp_df['Close'],2)
  tmp_df['Gained%'] = round((tmp_df['Close'] - tmp_df['BOL'])*100/tmp_df['BOL'],2)
  investment = round(sum(tmp_df['AvgCost']*tmp_df['Shares']),0)
  current = round(sum(tmp_df['Close']*tmp_df['Shares']),0)
  tmp_df['InitAlloc%'] = round(tmp_df['Investment']*100/investment,2)
  tmp_df['CurrAlloc%'] = round(tmp_df['Current']*100/current,2)
  tmp_df['FTT'] = tmp_df['LTT']
  tmp_df.loc[tmp_df['Strategy'] == 'NTT', 'FTT'] = tmp_df['NTT']
  tmp_df['FTT%'] = tmp_df['LTT%']
  tmp_df.loc[tmp_df['Strategy'] == 'NTT', 'FTT%'] = tmp_df['NTT%']
  tmp_df['FTT Amt'] = round(tmp_df['FTT%'] * tmp_df['Current']/100,0)
  tmp_df['OTT%'] = round((tmp_df['FTT'] - tmp_df['AvgCost'])*100/tmp_df['AvgCost'],2)
  tmp_df['RRR Ind'] = round(tmp_df['Current P/L']/tmp_df['FTT Amt'],2)
  tmp_df['Risk Ind'] = round(tmp_df['Current P/L%']*tmp_df['CurrAlloc%'],0)

  return tmp_df

# function to print portfolio features
def print_portfolio_stats(df_portfolio_features, myinvmt_df):
  from pyxirr import xirr

  total_booked_amt, reserve_amt, cy_booked_amt, py_booked_amt = get_amt()

  dates = myinvmt_df['Date'].values
  dates = np.append(dates, datetime.date.today().strftime('%d-%b-%y'))
  investment = myinvmt_df['Investment'].values
  dates= pd.to_datetime(dates)

  current = round(sum(df_portfolio_features['Close']*df_portfolio_features['Shares']),0) + reserve_amt
  investment_xirr = np.append(investment, current)
  cagr = round(xirr(pd.DataFrame({"dates": dates, "amounts": investment_xirr}))*100,2)

  investment = -sum(investment)
  invested = round(sum(df_portfolio_features['AvgCost']*df_portfolio_features['Shares']),0) + reserve_amt
  previous = round(sum(df_portfolio_features['Prev_Close']*df_portfolio_features['Shares']),0) + reserve_amt
  cy_invested = investment + py_booked_amt

  today_pnl_amount = current-previous
  today_pnl_percentage = round((current-previous)*100/previous,2)

  curr_pnl_amount = current-invested
  curr_pnl_percentage = round((curr_pnl_amount)*100/(cy_invested),2)

  cy_pnl_amount = cy_booked_amt + curr_pnl_amount
  cy_pnl_percentage = round((cy_pnl_amount)*100/cy_invested,2)

  overall_pnl_amount = total_booked_amt + curr_pnl_amount
  overall_pnl_percentage = round((overall_pnl_amount)*100/investment,2)

  estimate_st = round(sum(df_portfolio_features['FTT']*df_portfolio_features['Shares']),0)  + reserve_amt
  est_st_pnl_amount = estimate_st-current
  est_st_pnl_percentage = round((est_st_pnl_amount)*100/current,2)

  estimate_lt = round(sum(df_portfolio_features['LTT']*df_portfolio_features['Shares']),0)  + reserve_amt
  est_lt_pnl_amount = estimate_lt-current
  est_lt_pnl_percentage = round((est_lt_pnl_amount)*100/current,2)

  total_profit = round(sum(df_portfolio_features[df_portfolio_features['Current P/L%'] > 0]['Current']) - sum(df_portfolio_features[df_portfolio_features['Current P/L%'] > 0]['Investment']),0)
  total_loss = round(sum(df_portfolio_features[df_portfolio_features['Current P/L%'] < 0]['Current']) - sum(df_portfolio_features[df_portfolio_features['Current P/L%'] < 0]['Investment']),0)

  cy_booked_percentage = round((cy_booked_amt)*100/current,2)
  py_booked_percentage = round((py_booked_amt)*100/investment,2)
  total_booked_percentage = round((total_booked_amt)*100/investment,2)

  print('-------------------')
  print('Initial Investment: ', format_amt(investment))
  print('CY Investment: ', format_amt(cy_invested))
  print('Reserve: ', format_amt(reserve_amt))
  print('Current: ',  format_amt(current))
  print('-------------------')
  print('Today PnL: '+ '{} ({}%)'.format(format_amt(today_pnl_amount), today_pnl_percentage))
  print('Current PnL: '+ '{} ({}%)'.format(format_amt(curr_pnl_amount), curr_pnl_percentage))
  print('CY Booked + Current PnL: '+ '{} ({}%)'.format(format_amt(cy_pnl_amount), cy_pnl_percentage))
  print('-------------------')
  print('Total profit: ', format_amt(total_profit))
  print('Total loss: ', format_amt(total_loss))
  print('-------------------')
  print('Total Booked + Current PnL: '+ '{} ({}%)'.format(format_amt(overall_pnl_amount), overall_pnl_percentage))
  print('Total Booked PnL: '+ '{} ({}%)'.format(format_amt(total_booked_amt), total_booked_percentage))
  print('Curr Year Booked PnL: '+ '{} ({}%)'.format(format_amt(cy_booked_amt), cy_booked_percentage))
  print('Prev Year Booked PnL: '+ '{} ({}%)'.format(format_amt(py_booked_amt), py_booked_percentage))
  print('===================')
  print('Est FTT: ',  format_amt(estimate_st))
  print('Est FTT PnL: '+ '{} ({}%)'.format(format_amt(est_st_pnl_amount), est_st_pnl_percentage))

  print('===================')
  print('Deployed: ', format_amt(investment))

  print('Current: ', format_amt(current))

  print('CAGR/XIRR %: '+'{}%'.format(cagr))

In [8]:
# get start and end date
start_date, end_date = get_start_end_date()

# get portfolio and prospects data
mypfs_df = get_mypfs_df()
mypps_df = get_mypps_df()
myinvmt_df = get_myinvmt_df()

# merge above datasets
mypf_df = pd.merge(mypfs_df, mypps_df, on="Symbol")

# seggregate dm and sv portfolio
dm_pf = mypf_df[mypf_df['InPortfolio'] == 'DM']
sv_pf = mypf_df[mypf_df['InPortfolio'] == 'SV']

# build portfolio stock dataframe
dm_stocks = get_stock_ids(dm_pf)
sv_stocks = get_stock_ids(sv_pf)
df_stocks = pd.concat([dm_pf,sv_pf], ignore_index = True)

# arrange common and diff stock features
common_cols = ['Symbol', 'Target', 'Criteria', 'Strategy', 'CumlRnk', 'LatestQtr', 'StarStock', 'Conviction', 'Category', 'InFolio', 'XIRR', 'MBQ']
diff_cols = ['Symbol', 'AvgCost', 'Shares']
df_stocks = arrange_features(df_stocks, common_cols, diff_cols)

# get common features
stock_ids = df_stocks['Symbol'].values
df_common_features = get_common_features(stock_ids, df_stocks)

df_common_features.reset_index(drop=True, inplace=True)
df_common_features.drop(['Date'], axis=1, inplace=True)
# get and print portfolio features
df_portfolio_features = get_portfolio_features(df_common_features)

print_portfolio_stats(df_portfolio_features, myinvmt_df)

df = df_portfolio_features
#plot_pie_chart(df, 'CapType', 'Current')
list_ox40n = list(df[df['MBQ'].str.contains('OX40N', na=False)]['Symbol'].values)

Run date time (IST): 2026-08-10 15:27:37
-------------------
qualified stocks: 88
with latest results: 30
still star stocks: 19

-------------------
Initial Investment:  1.46 C
CY Investment:  1.89 C
Reserve:  2.24 L
Current:  1.61 C
-------------------
Today PnL: -20.75 K (-0.13%)
Current PnL: -30.72 L (-16.26%)
CY Booked + Current PnL: -26.50 L (-14.03%)
-------------------
Total profit:  3.81 L
Total loss:  -34.53 L
-------------------
Total Booked + Current PnL: 16.37 L (11.21%)
Total Booked PnL: 47.09 L (32.24%)
Curr Year Booked PnL: 4.22 L (2.61%)
Prev Year Booked PnL: 42.87 L (29.35%)
===================
Est FTT:  2.67 C
Est FTT PnL: 1.05 C (65.25%)
===================
Deployed:  1.46 C
Current:  1.61 C
CAGR/XIRR %: 4.59%

In [9]:
# top 5 near their targets
cols = ['Symbol', 'Today P/L%', 'Current P/L%', 'FTT%', 'OTT%', 'FTT Amt', 'Current P/L', 'Current', 'FTT', 'Dev%_PE', 'RSI_14','Conviction', 'Spread%',  'CumlRnk', 'RRR Ind', 'CurrAlloc%', 'Gained%', 'Criteria', 'Strategy', 'Category']
df_tmp = df_portfolio_features[~df_portfolio_features['Symbol'].isin(['ENRIN','BLUSPRING','DIGITIDE'])]
df_tmp = df_tmp.sort_values(by = 'FTT Amt', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
55,MEDANTA,1.55,26.45,0.53,27.12,1183.0,46691.0,223208.0,1486.00,22.54,71.0,X-SC,15.68,87.0,39.47,1.40,53.80,XY24,NTT,HEALTHCARE
52,M&M,0.26,10.87,7.17,18.82,19132.0,26155.0,266836.0,3762.88,-3.30,70.0,X-LC,5.37,25.0,1.37,1.68,21.04,X40N,ATH,AUTO
80,UNITDSPR,0.96,12.16,7.67,20.77,20143.0,28483.0,262627.0,1644.00,-0.46,71.0,X-MC,7.58,64.0,1.41,1.65,26.24,X40N,NTT,BREWERIES
79,TTKPRESTIG,-1.65,-21.25,27.10,0.09,21507.0,-21417.0,79360.0,770.00,84.20,42.0,M-SC,13.36,250.0,-1.00,0.50,42.84,OX40N,NTT,DURABLES
69,SIS,-1.48,-1.59,23.22,21.26,25372.0,-1764.0,109268.0,528.00,2607.77,48.0,H-SC,22.92,168.0,-0.07,0.69,62.46,OX40N,NTT,MISC

In [10]:
# top 5 today
df_tmp = df_portfolio_features.sort_values(by = 'Today P/L%', ascending=False)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
0,5PAISA,4.60,-26.80,54.25,12.90,86763.0,-58565.0,159931.0,593.00,135.58,62.0,H-SC,11.67,170.0,-0.67,1.00,54.34,OX40N,NTT,FINANCE
58,QUESS,4.24,32.99,30.76,73.90,43686.0,35229.0,142022.0,424.00,-28.37,65.0,X-SC,39.52,80.0,0.81,0.89,95.47,XY24,NTT,MISC
23,DMART,3.46,-1.64,33.61,31.42,103071.0,-5122.0,306668.0,5391.45,-18.18,52.0,X-LC,3.16,14.0,-0.05,1.93,10.66,X40N,ATH,FMCG
25,FINCABLES,3.32,34.08,55.06,107.91,109001.0,50324.0,197968.0,1641.55,20.75,56.0,M-SC,17.41,220.0,0.46,1.24,48.94,OX40N,ATH,CABLES
73,TANLA,3.05,-28.55,204.04,117.25,394752.0,-77293.0,193468.0,1922.32,-27.72,65.0,H-SC,14.23,147.0,-0.20,1.22,69.39,AR,ATH,IT

In [11]:
# bottom 5 today
df_tmp = df_portfolio_features.sort_values(by = 'Today P/L%', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
5,ATULAUTO,-12.08,-12.52,66.40,45.57,114505.0,-24684.0,172448.0,844.00,3737.84,49.0,M-SC,9.54,248.0,-0.22,1.08,32.71,XY24,NTT,AUTO
61,RECLTD,-6.61,-7.21,30.12,20.74,56780.0,-14658.0,188512.0,446.00,1.56,37.0,M-MC,3.36,191.0,-0.26,1.18,13.63,XY25,NTT,FINANCE
18,COFFEEDAY,-4.32,-47.58,158.06,35.27,94077.0,-54029.0,59520.0,80.00,-59.76,44.0,L-SC,4.98,266.0,-0.57,0.37,46.78,XR,NTT,HOTELS
56,PAGEIND,-2.93,1.02,32.24,33.59,87406.0,2731.0,271110.0,51217.29,-27.52,39.0,X-MC,8.98,55.0,0.03,1.70,28.75,X40,ATH,APPARELS
59,RAJESHEXPO,-2.37,-84.24,534.80,0.07,115645.0,-115553.0,21624.0,518.00,692.93,35.0,L-SC,36.35,268.0,-1.00,0.14,6.79,OX40N,NTT,JEWELLERY

In [12]:
# top 5 to exit based on CumlRnk
df_tmp = df_portfolio_features[~df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])]
df_tmp = df_tmp[(df_tmp['Current P/L%'] > -1) & (df_tmp['Current P/L%'] < 1)].sort_values(by = 'CumlRnk', ascending=False)
df_tmp[cols].head()

Empty DataFrame
Columns: [Symbol, Today P/L%, Current P/L%, FTT%, OTT%, FTT Amt, Current P/L, Current, FTT, Dev%_PE, RSI_14, Conviction, Spread%, CumlRnk, RRR Ind, CurrAlloc%, Gained%, Criteria, Strategy, Category]
Index: []

In [13]:
# OX40N stocks to exit
df_tmp = df_portfolio_features[(df_portfolio_features['Symbol'].isin(list_ox40n))].sort_values(by = 'Current P/L%', ascending=False)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
25,FINCABLES,3.32,34.08,55.06,107.91,109001.0,50324.0,197968.0,1641.55,20.75,56.0,M-SC,17.41,220.0,0.46,1.24,48.94,OX40N,ATH,CABLES
69,SIS,-1.48,-1.59,23.22,21.26,25372.0,-1764.0,109268.0,528.00,2607.77,48.0,H-SC,22.92,168.0,-0.07,0.69,62.46,OX40N,NTT,MISC
43,INDIGOPNTS,2.37,-18.52,22.76,0.02,32371.0,-32331.0,142228.0,1408.00,117.08,68.0,M-SC,5.09,222.0,-1.00,0.89,61.37,OX40N,NTT,PAINTS
16,CERA,-0.54,-21.17,57.16,23.89,79262.0,-37236.0,138667.0,9475.00,-23.87,43.0,H-SC,12.70,153.0,-0.47,0.87,34.80,OX40N,NTT,CERAMICS
79,TTKPRESTIG,-1.65,-21.25,27.10,0.09,21507.0,-21417.0,79360.0,770.00,84.20,42.0,M-SC,13.36,250.0,-1.00,0.50,42.84,OX40N,NTT,DURABLES

In [14]:
# top 5 to book for rotation
df_tmp = df_portfolio_features[(df_portfolio_features['Current P/L%'] > 20) ].sort_values(by = 'CumlRnk', ascending=False)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
25,FINCABLES,3.32,34.08,55.06,107.91,109001.0,50324.0,197968.0,1641.55,20.75,56.0,M-SC,17.41,220.0,0.46,1.24,48.94,OX40N,ATH,CABLES
55,MEDANTA,1.55,26.45,0.53,27.12,1183.0,46691.0,223208.0,1486.00,22.54,71.0,X-SC,15.68,87.0,39.47,1.40,53.80,XY24,NTT,HEALTHCARE
58,QUESS,4.24,32.99,30.76,73.90,43686.0,35229.0,142022.0,424.00,-28.37,65.0,X-SC,39.52,80.0,0.81,0.89,95.47,XY24,NTT,MISC

In [15]:
# top 5 to monitor for exit
df_tmp = df_portfolio_features[~df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])]
df_tmp = df_tmp[(df_tmp['Current P/L%'] > 0) ].sort_values(by = 'Dev%_PE', ascending=False)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
70,STARHEALTH,0.73,11.07,32.58,47.26,101733.0,31133.0,312256.0,761.00,75.24,45.0,H-SC,17.35,173.0,0.31,1.96,35.01,XY24,NTT,INSURANCE
25,FINCABLES,3.32,34.08,55.06,107.91,109001.0,50324.0,197968.0,1641.55,20.75,56.0,M-SC,17.41,220.0,0.46,1.24,48.94,OX40N,ATH,CABLES
87,ZYDUSLIFE,0.07,17.58,15.25,35.51,37578.0,36841.0,246415.0,1285.01,2.25,49.0,H-MC,15.53,120.0,0.98,1.55,29.68,AR,ATH,PHARMA

In [16]:
# top 5 to book for rotation from weak conviction
df_tmp = df_portfolio_features[~df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])]
df_tmp = df_tmp[~df_tmp['Criteria'].isin(['XY25','XY24','X40', 'X40N'])].sort_values(by = 'RRR Ind', ascending=False)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
87,ZYDUSLIFE,0.07,17.58,15.25,35.51,37578.0,36841.0,246415.0,1285.01,2.25,49.0,H-MC,15.53,120.0,0.98,1.55,29.68,AR,ATH,PHARMA
25,FINCABLES,3.32,34.08,55.06,107.91,109001.0,50324.0,197968.0,1641.55,20.75,56.0,M-SC,17.41,220.0,0.46,1.24,48.94,OX40N,ATH,CABLES
69,SIS,-1.48,-1.59,23.22,21.26,25372.0,-1764.0,109268.0,528.00,2607.77,48.0,H-SC,22.92,168.0,-0.07,0.69,62.46,OX40N,NTT,MISC
3,ALKYLAMINE,1.00,-18.53,136.33,92.54,112138.0,-18708.0,82255.0,4520.85,-12.74,58.0,H-SC,13.56,142.0,-0.17,0.52,56.19,SR,ATH,CHEMICALS
42,INDIAMART,1.30,-23.60,163.00,100.92,153583.0,-29113.0,94223.0,4675.60,-65.62,40.0,H-SC,12.24,140.0,-0.19,0.59,2.00,AR,ATH,MISC

In [17]:
# top 5 to accumulate based on lowest RSI_14
df_tmp = df_portfolio_features[df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])].sort_values(by = 'RSI_14', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
34,HDFCBANK,0.12,-10.61,46.60,31.05,122101.0,-31100.0,262020.0,1073.00,-25.47,35.0,X-LC,10.98,26.0,-0.25,1.65,1.70,X40,BTT,BANKS
57,PGHH,-0.28,-36.50,107.91,32.01,146300.0,-77944.0,135576.0,17616.87,-57.06,35.0,X-MC,19.22,57.0,-0.53,0.85,0.00,X40,ATH,FMCG
56,PAGEIND,-2.93,1.02,32.24,33.59,87406.0,2731.0,271110.0,51217.29,-27.52,39.0,X-MC,8.98,55.0,0.03,1.70,28.75,X40,ATH,APPARELS
84,VOLTAS,-1.37,-0.85,46.44,45.20,88287.0,-1632.0,190110.0,1856.00,13.55,39.0,X-MC,4.07,79.0,-0.02,1.19,4.19,XY25,NTT,AC
35,HDFCLIFE,0.19,-7.22,49.98,39.15,116268.0,-18107.0,232630.0,811.41,-30.91,40.0,X-LC,16.09,31.0,-0.16,1.46,0.94,X40,ATH,INSURANCE

In [18]:
# top 5 to accumulate based on Spread and CumlRnk
df_tmp = df_portfolio_features[df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])]
df_tmp = df_tmp[(df_tmp['CumlRnk'] < 100)].sort_values(by = 'Spread%', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
19,COLPAL,-0.98,-23.68,83.25,39.86,167341.0,-62355.0,201010.0,3683.41,-7.64,43.0,X-MC,1.64,62.0,-0.37,1.26,13.70,XY25,ATH,FMCG
11,BERGEPAINT,2.28,0.00,25.31,25.32,65239.0,10.0,257759.0,680.00,-5.48,64.0,X-MC,2.15,68.0,0.00,1.62,35.17,XY24,NTT,PAINTS
8,BAJAJHLDNG,1.66,2.87,24.67,28.24,64968.0,7345.0,263350.0,14274.15,-5.41,65.0,X-LC,2.72,28.0,0.11,1.65,32.54,X40,ATH,FINANCE
23,DMART,3.46,-1.64,33.61,31.42,103071.0,-5122.0,306668.0,5391.45,-18.18,52.0,X-LC,3.16,14.0,-0.05,1.93,10.66,X40N,ATH,FMCG
26,GILLETTE,-0.33,-9.51,43.36,29.72,99622.0,-24141.0,229755.0,10978.86,-30.50,44.0,X-SC,3.37,83.0,-0.24,1.44,5.58,X40,ATH,FMCG

In [19]:
# top 5 to accumulate based on lowest Gained%
df_tmp = df_portfolio_features[df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])].sort_values(by = 'Gained%', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
57,PGHH,-0.28,-36.50,107.91,32.01,146300.0,-77944.0,135576.0,17616.87,-57.06,35.0,X-MC,19.22,57.0,-0.53,0.85,0.00,X40,ATH,FMCG
35,HDFCLIFE,0.19,-7.22,49.98,39.15,116268.0,-18107.0,232630.0,811.41,-30.91,40.0,X-LC,16.09,31.0,-0.16,1.46,0.94,X40,ATH,INSURANCE
34,HDFCBANK,0.12,-10.61,46.60,31.05,122101.0,-31100.0,262020.0,1073.00,-25.47,35.0,X-LC,10.98,26.0,-0.25,1.65,1.70,X40,BTT,BANKS
20,DABUR,0.95,-19.08,77.58,43.70,155736.0,-47326.0,200742.0,735.00,-26.49,42.0,X-MC,9.22,70.0,-0.30,1.26,2.15,XY24,BTT,FMCG
47,ITC,-1.45,-22.22,60.31,24.70,186368.0,-88261.0,309017.0,452.00,-59.16,45.0,X-LC,11.27,1.0,-0.47,1.94,2.32,X40,NTT,FMCG

In [20]:
# top 5 to accumulate based on lowest CurrAlloc%
df_tmp = df_portfolio_features[df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])].sort_values(by = 'CurrAlloc%', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
10,BATAINDIA,-1.18,-54.07,194.38,35.20,114871.0,-69574.0,59096.0,2096.00,-22.45,57.0,X-SC,14.06,91.0,-0.61,0.37,18.73,X40,NTT,FOOTWEAR
62,RELAXO,0.13,-45.09,177.36,52.31,141377.0,-65448.0,79712.0,1176.00,-41.54,60.0,X-SC,11.76,92.0,-0.46,0.50,78.23,X40N,NTT,FOOTWEAR
57,PGHH,-0.28,-36.50,107.91,32.01,146300.0,-77944.0,135576.0,17616.87,-57.06,35.0,X-MC,19.22,57.0,-0.53,0.85,0.00,X40,ATH,FMCG
58,QUESS,4.24,32.99,30.76,73.90,43686.0,35229.0,142022.0,424.00,-28.37,65.0,X-SC,39.52,80.0,0.81,0.89,95.47,XY24,NTT,MISC
40,ICICIPRULI,-0.76,-17.72,58.32,30.28,94539.0,-34901.0,162104.0,787.27,-39.83,45.0,X-MC,13.51,78.0,-0.37,1.02,8.00,X40,ATH,INSURANCE

In [21]:
# top 5 to accumulate based on CumlRnk
df_tmp = df_portfolio_features.sort_values(by = 'CumlRnk', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
47,ITC,-1.45,-22.22,60.31,24.70,186368.0,-88261.0,309017.0,452.00,-59.16,45.0,X-LC,11.27,1.0,-0.47,1.94,2.32,X40,NTT,FMCG
75,TCS,-0.87,-28.62,74.00,24.20,244696.0,-132603.0,330670.0,4230.71,-39.69,61.0,X-LC,15.49,2.0,-0.54,2.08,23.31,X40,ATH,IT
45,INFY,0.59,-15.86,66.84,40.38,211733.0,-59694.0,316776.0,1972.00,-36.50,63.0,X-LC,16.29,3.0,-0.28,1.99,19.96,X40,NTT,IT
77,TMPV,-0.20,-17.61,73.26,42.75,251162.0,-73270.0,342837.0,600.00,-83.62,54.0,X-LC,5.33,4.0,-0.29,2.15,17.89,XY24,NTT,AUTO
33,HCLTECH,-0.21,-9.45,36.91,23.97,103435.0,-29249.0,280237.0,1853.42,-7.78,68.0,X-LC,13.33,8.0,-0.28,1.76,32.24,X40,ATH,IT

In [22]:
# top 5 for average up
df_tmp = df_portfolio_features[(df_portfolio_features['Dev%_200'] > 5)].sort_values(by = 'CurrAlloc%', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
44,INDUSINDBK,0.52,-24.16,75.22,32.89,44046.0,-18650.0,58556.0,1800.00,-375.91,58.0,L-MC,14.04,258.0,-0.42,0.37,44.36,XR,NTT,BANKS
62,RELAXO,0.13,-45.09,177.36,52.31,141377.0,-65448.0,79712.0,1176.00,-41.54,60.0,X-SC,11.76,92.0,-0.46,0.50,78.23,X40N,NTT,FOOTWEAR
79,TTKPRESTIG,-1.65,-21.25,27.10,0.09,21507.0,-21417.0,79360.0,770.00,84.20,42.0,M-SC,13.36,250.0,-1.00,0.50,42.84,OX40N,NTT,DURABLES
3,ALKYLAMINE,1.00,-18.53,136.33,92.54,112138.0,-18708.0,82255.0,4520.85,-12.74,58.0,H-SC,13.56,142.0,-0.17,0.52,56.19,SR,ATH,CHEMICALS
12,BOSCH-HCIL,0.77,-25.71,34.60,-0.01,32850.0,-32863.0,94942.0,2282.00,19334.78,85.0,M-SC,3.55,231.0,-1.00,0.60,61.61,OX40N,BTT,AC

In [23]:
# top 5 RSP
df_tmp = df_portfolio_features.sort_values(by = 'RSP', ascending=False)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
12,BOSCH-HCIL,0.77,-25.71,34.60,-0.01,32850.0,-32863.0,94942.0,2282.00,19334.78,85.0,M-SC,3.55,231.0,-1.00,0.60,61.61,OX40N,BTT,AC
75,TCS,-0.87,-28.62,74.00,24.20,244696.0,-132603.0,330670.0,4230.71,-39.69,61.0,X-LC,15.49,2.0,-0.54,2.08,23.31,X40,ATH,IT
33,HCLTECH,-0.21,-9.45,36.91,23.97,103435.0,-29249.0,280237.0,1853.42,-7.78,68.0,X-LC,13.33,8.0,-0.28,1.76,32.24,X40,ATH,IT
73,TANLA,3.05,-28.55,204.04,117.25,394752.0,-77293.0,193468.0,1922.32,-27.72,65.0,H-SC,14.23,147.0,-0.20,1.22,69.39,AR,ATH,IT
58,QUESS,4.24,32.99,30.76,73.90,43686.0,35229.0,142022.0,424.00,-28.37,65.0,X-SC,39.52,80.0,0.81,0.89,95.47,XY24,NTT,MISC

In [24]:
# Top N allocation
df_tmp = df_portfolio_features.sort_values(by = 'CurrAlloc%', ascending=False)
top_n_values = [10, 25, 50]

sum_df = pd.DataFrame({
    'Top_N': top_n_values,
    'Sum_Alloc%': [df_tmp['CurrAlloc%'].head(n).sum() for n in top_n_values]
})

sum_df

   Top_N  Sum_Alloc%
0     10       19.77
1     25       44.80
2     50       76.80

In [25]:
# market-cap-wise allocation
df_tmp = df_portfolio_features[cols]
df_tmp.groupby(df_tmp['Conviction'].str[-2:])['CurrAlloc%'].sum().sort_values(ascending=False)

Conviction
SC    39.29
LC    37.81
MC    22.86
Name: CurrAlloc%, dtype: float64

In [26]:
# criteria-wise allocation
df_portfolio_features.groupby('Criteria')['CurrAlloc%'].sum().sort_values(ascending=False)

Criteria
X40      26.37
XY24     24.94
X40N     18.58
XR        9.07
XY25      7.16
OX40N     6.91
AR        6.07
SR        0.86
Name: CurrAlloc%, dtype: float64

In [27]:
# conviction-wise allocation
df_portfolio_features.groupby('Conviction')['CurrAlloc%'].sum().sort_values(ascending=False)

Conviction
X-LC    35.77
H-SC    19.29
X-MC    18.69
X-SC     9.97
M-SC     9.52
H-MC     2.62
H-LC     1.23
M-MC     1.18
M-LC     0.81
L-SC     0.51
L-MC     0.37
Name: CurrAlloc%, dtype: float64

In [28]:
# sector-wise stats
df_tmp = df_portfolio_features.groupby('Category')[['CurrAlloc%', 'Current', 'Current P/L', 'FTT Amt']].sum().sort_values(by=['Current', 'Current P/L'], ascending=False)
df_tmp['Current P/L%'] = round(df_tmp['Current P/L'] * 100 / df_tmp['Current'], 2)
df_tmp['FTT%'] = round(df_tmp['FTT Amt'] * 100 / df_tmp['Current'], 2)
cols = ['CurrAlloc%', 'Current P/L%', 'FTT%']
df_tmp[cols].sort_values(by=['CurrAlloc%'], ascending=False)

               CurrAlloc%  Current P/L%    FTT%
Category
FMCG                15.50        -20.80   64.31
IT                  11.25        -33.14   99.22
FINANCE              9.24        -15.95   64.68
AUTO                 8.32         -2.06   38.61
MISC                 6.89        -22.38   74.89
BANKS                6.06        -10.82   58.61
PHARMA               5.59          6.82   19.60
INSURANCE            5.54         -5.35   42.60
PAINTS               5.49        -12.65   31.87
ELECTRICAL           4.13         -7.71   45.42
HEALTHCARE           2.10         -6.75   34.60
AC                   1.79        -12.10   42.50
APPARELS             1.70          1.01   32.24
REFINERIES           1.70        -10.36   47.43
FOOTWEAR             1.66        -66.71  133.56
BREWERIES            1.65         10.85    7.67
DURABLES             1.49        -62.70  102.28
TRAVEL               1.47        -91.04  186.69
CERAMICS             1.35        -43.10   86.58
CABLES               1.24         25.42   55.06
ENGINEERING          1.20        -26.41   84.22
CHEMICALS            1.15        -44.93  162.56
CEMENT               1.02        -64.44  187.46
JEWELLERY            0.99       -104.18  175.12
ENTERTAINMENT        0.68        -77.97  184.12
TEXTILES             0.39        -50.49   93.39
HOTELS               0.37        -90.77  158.06

In [29]:
# money to be made criteria-wise
df_portfolio_features.groupby('Criteria')['FTT Amt'].agg(['sum', 'count']).sort_values(by='sum', ascending=False)

                sum  count
Criteria
XY24      3428138.0     20
X40       2026756.0     18
XR        1353821.0     13
X40N      1126162.0     12
AR        1066916.0      8
OX40N      691042.0     10
XY25       558127.0      5
SR         280391.0      2

In [30]:
# money to be made conviction-wise
df_portfolio_features.groupby('Conviction')['FTT Amt'].agg(['sum', 'count']).sort_values(by='sum', ascending=False)

                  sum  count
Conviction
H-SC        3283156.0     23
X-LC        2365231.0     20
X-MC        1477686.0     14
M-SC        1399390.0     14
X-SC        1214627.0      9
H-MC         281034.0      2
L-SC         209722.0      2
M-LC         163245.0      1
M-MC          56780.0      1
L-MC          44046.0      1
H-LC          36436.0      1

In [31]:
# money to be made criteria and conviction-wise
df_portfolio_features.groupby(['Conviction', 'Criteria'])['FTT Amt'].agg(['sum', 'count']).sort_values(by='sum', ascending=False)

                           sum  count
Conviction Criteria
X-LC       X40       1156907.0      9
H-SC       XY24       987407.0      5
           AR         916471.0      5
M-SC       XY24       848381.0      6
H-SC       XR         805785.0      7
X-SC       XY24       705194.0      4
X-MC       X40        655356.0      7
X-LC       X40N       485495.0      6
           XY24       422725.0      2
X-MC       X40N       345727.0      3
X-SC       X40N       294940.0      3
H-SC       OX40N      293102.0      4
M-SC       OX40N      282295.0      5
H-SC       SR         280391.0      2
X-MC       XY25       255628.0      2
X-LC       XY25       245719.0      2
H-MC       XY24       243456.0      1
X-MC       XY24       220975.0      2
X-SC       X40        214493.0      2
M-SC       XR         192283.0      2
M-LC       XR         163245.0      1
L-SC       OX40N      115645.0      1
           XR          94077.0      1
M-SC       AR          76431.0      1
M-MC       XY25        56780.0      1
X-LC       XR          54385.0      1
L-MC       XR          44046.0      1
H-MC       AR          37578.0      1
H-LC       AR          36436.0      1

In [32]:
# notebook execution time

end_time = time.time()
execution_time = round(end_time - start_time, 0)
print(f"Notebook execution time: {execution_time} seconds")

Notebook execution time: 35.0 seconds