<a href="https://colab.research.google.com/github/ankit-rathi/Quantvesting_v2/blob/main/myStocks_Portfolio_Analysis.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
'''
!pip install pandas==2.2.2 -qq
!pip install pyxirr -qq
!pip install ta -qq
!pip install yfinance==0.2.59 -qq
'''

'\n!pip install pandas==2.2.2 -qq\n!pip install pyxirr -qq\n!pip install ta -qq\n!pip install yfinance==0.2.59 -qq\n'

In [2]:
# import libraries

import numpy as np
import pandas as pd
import datetime
import warnings
warnings.filterwarnings('ignore')
import yfinance as yfin
import ta
import matplotlib.pyplot as plt
import requests

In [3]:
# notebook start time
import time
import datetime
import pytz

start_time = time.time()

# function to print date timestamp
def print_date_time():
  tz_NY = pytz.timezone('Asia/Kolkata')
  datetime_NY = datetime.datetime.now(tz_NY)
  print("Run date time (IST):", datetime_NY.strftime("%Y-%m-%d %H:%M:%S"))

In [4]:
# function to get booked and reserved amount
def get_amt():
  # fetch the JSON data from the URL
  url = "https://raw.githubusercontent.com/ankit-rathi/Tradevesting_v1/main/data/myPortfolioAmts.json"
  response = requests.get(url)
  pf_amts = response.json()  # parse the JSON data

  # extract values from the JSON
  py_booked_amt_dm = pf_amts["py_booked_amt_dm"]
  py_booked_amt_sv = pf_amts["py_booked_amt_sv"]
  cy_booked_amt_dm = pf_amts["cy_booked_amt_dm"]
  cy_booked_amt_sv = pf_amts["cy_booked_amt_sv"]
  reserve_amt_dm = pf_amts["reserve_amt_dm"]
  reserve_amt_sv = pf_amts["reserve_amt_sv"]

  # perform calculations
  py_booked_amt = py_booked_amt_dm + py_booked_amt_sv
  cy_booked_amt = cy_booked_amt_dm + cy_booked_amt_sv
  reserve_amt = reserve_amt_dm + reserve_amt_sv
  total_booked_amt = py_booked_amt + cy_booked_amt

  return total_booked_amt, reserve_amt, cy_booked_amt, py_booked_amt

gen_output = 0

In [5]:
# function to format the amount
def format_amt(number):
    abs_number = abs(number)

    if abs_number >= 1_00_00_000:  # Crores
        formatted_amt = f"{number / 1_00_00_000:.2f} C"
    elif abs_number >= 1_00_000:  # Lakhs
        formatted_amt = f"{number / 1_00_000:.2f} L"
    elif abs_number >= 1_000:  # Thousands
        formatted_amt = f"{number / 1_000:.2f} K"
    else:
        formatted_amt = f"{number:.2f}"

    return formatted_amt

# function to set start and end date
def get_start_end_date():
  start_date = (datetime.date.today() + datetime.timedelta(days=-365)).strftime('%Y-%m-%d')
  end_date = (datetime.date.today() + datetime.timedelta(days=1)).strftime('%Y-%m-%d')
  return start_date, end_date

# function to fetch my portfolio csv
def get_mypfs_df():
  mypfs_df = pd.read_csv('https://raw.githubusercontent.com/ankit-rathi/Tradevesting_v1/main/data/myPortfolioStocks.csv')
  return mypfs_df

# function to fetch my prospects csv
def get_mypps_df():
  mypps_df = pd.read_csv('https://raw.githubusercontent.com/ankit-rathi/Tradevesting_v1/main/data/myProspectsScrips.csv')
  return mypps_df

# function to fetch screener data
def get_myscreen_df():
  myscreen_df = pd.read_csv('https://raw.githubusercontent.com/ankit-rathi/Tradevesting_v1/main/data/myScreenerDB.csv')
  return myscreen_df

# function to fetch momentum data
def get_myinvmt_df():
  myinvmt_df = pd.read_csv('https://raw.githubusercontent.com/ankit-rathi/Tradevesting_v1/main/data/myInvestments.csv')
  return myinvmt_df

# function to get the stock ids
def get_stock_ids(df_pf):
  stock_n100 = df_pf['Symbol'].unique()

  exclude = ['CADILAHC','MMTC', 'MASFIN']

  stock_ids = df_pf[~df_pf['Symbol'].isin(exclude) ]['Symbol'].unique()

  #mypf = mypf[mypf.Forecast.notnull()]
  #stock_ids = mypf['Symbol'].unique()

  #stock_ids.sort()
  return stock_ids

# get features from screener data
def get_screener_features():
  myscreen_df = get_myscreen_df()
  cols = ['Symbol', 'EPS', 'MedPE', 'ROCE%', 'ROE%', 'CapType']
  return myscreen_df[cols]

# get relative strength
def get_relative_strength(stock_list):

    # Dictionary to store stock tickers and their corresponding percentage price change
    stock_changes = {}

    # Loop through each stock and fetch its price data
    for stock in stock_list:
        try:
            # Download the stock data for the given date range
            stock_data = yfin.Ticker(stock + '.NS').history(period='1mo', interval='1d')[map(str.title, ['open', 'close', 'low', 'high', 'volume'])]

            # Calculate the percentage change for the stock
            if len(stock_data) > 0:
                start_price = stock_data['Close'].iloc[0]
                end_price = stock_data['Close'].iloc[-1]
                percent_change = round(((end_price - start_price) / start_price) * 100, 2)
                stock_changes[stock] = percent_change
            else:
                stock_changes[stock] = np.nan  # If no data is available, set to NaN

        except Exception as e:
            print(f"Error fetching data for {stock}: {e}")
            stock_changes[stock] = np.nan

    # Create a DataFrame with stock tickers and their percentage changes
    df = pd.DataFrame(list(stock_changes.items()), columns=['Symbol', 'Percent_Change'])

    # Drop any stocks with missing data (NaN values)
    df = df.dropna()

    # Calculate the percentile rank based on percentage change
    df['RSP'] = round(df['Percent_Change'].rank(pct=True) * 100, 2)
    cols = ['Symbol', 'RSP']
    df = df[cols]
    # Sort by percentile rank (optional)
    df = df.sort_values(by='RSP', ascending=False).reset_index(drop=True)

    return df

In [6]:
# function to get stock technicals
def stock_prec_dev(stock_symbol):
    #stock_symbol = 'ULTRACEMCO.NS'
    short_window = 20
    mid_window = 50
    long_window = 200
    moving_avg = 'SMA'

    start = datetime.datetime(*map(int, start_date.split('-')))
    end = datetime.datetime(*map(int, end_date.split('-')))

    stock_df = yfin.Ticker(stock_symbol + '.NS').history(period='max', interval='1d')[map(str.title, ['open', 'close', 'low', 'high', 'volume'])]

    stock_df['Max'] = round(max(stock_df['Close']),2)
    stock_df = stock_df[(stock_df.index <= end_date) & (stock_df.index >= start_date)]
    stock_df['200_SMA'] = round(stock_df['Close'].rolling(window = 200, min_periods = 1).mean(),0)
    stock_df['Dev%_200'] = round((stock_df['Close'] - stock_df['200_SMA'])*100/stock_df['200_SMA'],2)
    stock_df.dropna(axis = 0, inplace = True) # remove any null rows

    stock_df['20_SMA'] = stock_df['Close'].rolling(window=20).mean()
    stock_df['50_SMA'] = stock_df['Close'].rolling(window=50).mean()
    stock_df['Symbol'] = stock_symbol

    stock_df['Close'] = round(stock_df['Close'],2)
    stock_df['Min'] = round(min(stock_df['Close']),2)
    stock_df['RSI_14'] = ta.momentum.RSIIndicator(close=stock_df['Close'], window=14).rsi()
    stock_df['RSI_14'] = round(stock_df['RSI_14'],0)
    stock_df['Prev_Close'] = stock_df['Close'].shift(1)
    stock_df.drop(['Open', 'Low', 'High', 'Volume'], axis=1, inplace=True)
    stock_df = stock_df.tail(1)

    max_SMA = max(stock_df['20_SMA'].item(), stock_df['50_SMA'].item(), stock_df['200_SMA'].item())
    min_SMA = min(stock_df['20_SMA'].item(), stock_df['50_SMA'].item(), stock_df['200_SMA'].item())
    ABS_Spread = max_SMA - min_SMA
    stock_df['Spread%'] = round((ABS_Spread / stock_df['200_SMA'].item()) * 100,2)

    return stock_df

# function to compute stock attributes
def get_common_features(stock_ids, df_mypf):

  df_prec_dev = pd.DataFrame()
  df_tmp = get_screener_features()
  df_rs = get_relative_strength(stock_ids)

  for stock_id in stock_ids:
      tmp = stock_prec_dev(stock_id)
      tmp = tmp.reset_index()
      df_prec_dev = pd.concat([df_prec_dev, tmp], ignore_index = True)
  df_prec_dev = pd.merge(df_prec_dev, df_mypf, on= 'Symbol')
  df_prec_dev = pd.merge(df_prec_dev, df_tmp, on= 'Symbol', how='left')
  df_prec_dev = pd.merge(df_prec_dev, df_rs, on= 'Symbol', how='left')
  #print(df_prec_dev.columns)
  df_prec_dev['Curr_PE'] = round(df_prec_dev['Close']/df_prec_dev['EPS'],1)
  df_prec_dev['Dev%_PE'] = round((df_prec_dev['Curr_PE'] - df_prec_dev['MedPE'])*100/df_prec_dev['MedPE'],2)
  df_prec_dev['Conviction'] = df_prec_dev['Conviction'] + '-' + df_prec_dev['CapType']
  return df_prec_dev

# function to arrange stock features
def arrange_features(df_stocks, common_cols, diff_cols):
  df_stocks_common = df_stocks[common_cols].drop_duplicates()
  df_stocks_diff = df_stocks[diff_cols]
  df_stocks_diff['Investment'] = df_stocks_diff['AvgCost'] * df_stocks_diff['Shares']
  df_stocks_diff = df_stocks_diff.groupby(['Symbol'])[['Shares', 'Investment']].aggregate(['sum']).reset_index()
  df_stocks_diff.columns = ['Symbol', 'Shares', 'Investment']
  df_stocks_diff['AvgCost'] = round(df_stocks_diff['Investment']/df_stocks_diff['Shares'],2)
  df_stocks = pd.merge(df_stocks_diff, df_stocks_common, on='Symbol')
  return df_stocks

# plot fact distribution across dimension
def plot_pie_chart(df, dimension, fact):
  # grouping the data by category and calculating the sum of fact for each type
  grouped_data = df.groupby(dimension)[fact].sum()

  # sorting the grouped data in descending order
  grouped_data = grouped_data.sort_values(ascending=False)

  # creating a pie chart
  grouped_data.plot.pie(autopct='%1.1f%%', startangle=90, figsize=(6, 6))

  # adding a title and displaying the plot
  plt.title(f'{dimension} {fact} Distribution')
  plt.ylabel('')  # To hide the y-label
  plt.show()

In [7]:
# function to get portfolio features

def get_portfolio_features(df_common_features):

  print_date_time()
  print('-------------------')

  #df_common_features["Target"] = df_common_features["Target"].fillna(df_common_features["Max"])
  df_common_features['NTT'] = np.where(df_common_features['Strategy']== 'NTT', df_common_features["Target"], df_common_features['Max'])
  df_common_features['LTT'] = np.where(df_common_features['Strategy']== 'BTT', df_common_features["Target"], df_common_features['Max'])
  df_common_features['BOL'] = df_common_features['Min']

  tmp_df = df_common_features[df_common_features['Symbol'].isin(mypf_df[mypf_df['InPortfolio'] != 'NA'].Symbol.values)]
  print('qualified stocks: '+str(len(tmp_df['Symbol'].unique())))
  tmp_df1 = tmp_df[tmp_df['LatestQtr'] == 1]
  print('with latest results: '+str(len(tmp_df1['Symbol'].unique())))
  tmp_df1 = tmp_df1[tmp_df1['StarStock'] == 1]
  print('still star stocks: '+str(len(tmp_df1['Symbol'].unique())))
  tmp_df['Investment'] = tmp_df['AvgCost'] * tmp_df['Shares']
  tmp_df['Current'] = round(tmp_df['Close'] * tmp_df['Shares'],0)
  tmp_df['Previous'] = tmp_df['Prev_Close'] * tmp_df['Shares']
  tmp_df['EstimatedST'] = tmp_df['NTT'] * tmp_df['Shares']
  tmp_df['EstimatedLT'] = tmp_df['LTT'] * tmp_df['Shares']
  tmp_df['Current P/L'] = round((tmp_df['Current'] - tmp_df['Investment']),0)
  tmp_df['Today P/L%'] = round((tmp_df['Current'] - tmp_df['Previous'])*100/tmp_df['Previous'],2)
  tmp_df['Current P/L%'] = round((tmp_df['Current'] - tmp_df['Investment'])*100/tmp_df['Investment'],2)
  tmp_df['EstimatedST P/L%'] = round((tmp_df['EstimatedST'] - tmp_df['Investment'])*100/tmp_df['Investment'],2)
  tmp_df['EstimatedLT P/L%'] = round((tmp_df['EstimatedLT'] - tmp_df['Investment'])*100/tmp_df['Investment'],2)
  tmp_df['NTT%'] = round((tmp_df['NTT'] - tmp_df['Close'])*100/tmp_df['Close'],2)
  tmp_df['LTT%'] = round((tmp_df['LTT'] - tmp_df['Close'])*100/tmp_df['Close'],2)
  tmp_df['Gained%'] = round((tmp_df['Close'] - tmp_df['BOL'])*100/tmp_df['BOL'],2)
  investment = round(sum(tmp_df['AvgCost']*tmp_df['Shares']),0)
  current = round(sum(tmp_df['Close']*tmp_df['Shares']),0)
  tmp_df['InitAlloc%'] = round(tmp_df['Investment']*100/investment,2)
  tmp_df['CurrAlloc%'] = round(tmp_df['Current']*100/current,2)
  tmp_df['FTT'] = tmp_df['LTT']
  tmp_df.loc[tmp_df['Strategy'] == 'NTT', 'FTT'] = tmp_df['NTT']
  tmp_df['FTT%'] = tmp_df['LTT%']
  tmp_df.loc[tmp_df['Strategy'] == 'NTT', 'FTT%'] = tmp_df['NTT%']
  tmp_df['FTT Amt'] = round(tmp_df['FTT%'] * tmp_df['Current']/100,0)
  tmp_df['OTT%'] = round((tmp_df['FTT'] - tmp_df['AvgCost'])*100/tmp_df['AvgCost'],2)
  tmp_df['RRR Ind'] = round(tmp_df['Current P/L']/tmp_df['FTT Amt'],2)
  tmp_df['Risk Ind'] = round(tmp_df['Current P/L%']*tmp_df['CurrAlloc%'],0)

  return tmp_df

# function to print portfolio features
def print_portfolio_stats(df_portfolio_features, myinvmt_df):
  from pyxirr import xirr

  total_booked_amt, reserve_amt, cy_booked_amt, py_booked_amt = get_amt()

  dates = myinvmt_df['Date'].values
  dates = np.append(dates, datetime.date.today().strftime('%d-%b-%y'))
  investment = myinvmt_df['Investment'].values
  dates= pd.to_datetime(dates)

  current = round(sum(df_portfolio_features['Close']*df_portfolio_features['Shares']),0) + reserve_amt
  investment_xirr = np.append(investment, current)
  cagr = round(xirr(pd.DataFrame({"dates": dates, "amounts": investment_xirr}))*100,2)

  investment = -sum(investment)
  invested = round(sum(df_portfolio_features['AvgCost']*df_portfolio_features['Shares']),0) + reserve_amt
  previous = round(sum(df_portfolio_features['Prev_Close']*df_portfolio_features['Shares']),0) + reserve_amt
  cy_invested = investment + py_booked_amt

  today_pnl_amount = current-previous
  today_pnl_percentage = round((current-previous)*100/previous,2)

  curr_pnl_amount = current-invested
  curr_pnl_percentage = round((curr_pnl_amount)*100/(cy_invested),2)

  cy_pnl_amount = cy_booked_amt + curr_pnl_amount
  cy_pnl_percentage = round((cy_pnl_amount)*100/cy_invested,2)

  overall_pnl_amount = total_booked_amt + curr_pnl_amount
  overall_pnl_percentage = round((overall_pnl_amount)*100/investment,2)

  estimate_st = round(sum(df_portfolio_features['FTT']*df_portfolio_features['Shares']),0)  + reserve_amt
  est_st_pnl_amount = estimate_st-current
  est_st_pnl_percentage = round((est_st_pnl_amount)*100/current,2)

  estimate_lt = round(sum(df_portfolio_features['LTT']*df_portfolio_features['Shares']),0)  + reserve_amt
  est_lt_pnl_amount = estimate_lt-current
  est_lt_pnl_percentage = round((est_lt_pnl_amount)*100/current,2)

  total_profit = round(sum(df_portfolio_features[df_portfolio_features['Current P/L%'] > 0]['Current']) - sum(df_portfolio_features[df_portfolio_features['Current P/L%'] > 0]['Investment']),0)
  total_loss = round(sum(df_portfolio_features[df_portfolio_features['Current P/L%'] < 0]['Current']) - sum(df_portfolio_features[df_portfolio_features['Current P/L%'] < 0]['Investment']),0)

  cy_booked_percentage = round((cy_booked_amt)*100/current,2)
  py_booked_percentage = round((py_booked_amt)*100/investment,2)
  total_booked_percentage = round((total_booked_amt)*100/investment,2)

  print('-------------------')
  print('Initial Investment: ', format_amt(investment))
  print('CY Investment: ', format_amt(cy_invested))
  print('Reserve: ', format_amt(reserve_amt))
  print('Current: ',  format_amt(current))
  print('-------------------')
  print('Today PnL: '+ '{} ({}%)'.format(format_amt(today_pnl_amount), today_pnl_percentage))
  print('Current PnL: '+ '{} ({}%)'.format(format_amt(curr_pnl_amount), curr_pnl_percentage))
  print('CY Booked + Current PnL: '+ '{} ({}%)'.format(format_amt(cy_pnl_amount), cy_pnl_percentage))
  print('-------------------')
  print('Total profit: ', format_amt(total_profit))
  print('Total loss: ', format_amt(total_loss))
  print('-------------------')
  print('Total Booked + Current PnL: '+ '{} ({}%)'.format(format_amt(overall_pnl_amount), overall_pnl_percentage))
  print('Total Booked PnL: '+ '{} ({}%)'.format(format_amt(total_booked_amt), total_booked_percentage))
  print('Curr Year Booked PnL: '+ '{} ({}%)'.format(format_amt(cy_booked_amt), cy_booked_percentage))
  print('Prev Year Booked PnL: '+ '{} ({}%)'.format(format_amt(py_booked_amt), py_booked_percentage))
  print('===================')
  print('Est FTT: ',  format_amt(estimate_st))
  print('Est FTT PnL: '+ '{} ({}%)'.format(format_amt(est_st_pnl_amount), est_st_pnl_percentage))

  print('===================')
  print('Deployed: ', format_amt(investment))

  print('Current: ', format_amt(current))

  print('CAGR/XIRR %: '+'{}%'.format(cagr))

In [8]:
# get start and end date
start_date, end_date = get_start_end_date()

# get portfolio and prospects data
mypfs_df = get_mypfs_df()
mypps_df = get_mypps_df()
myinvmt_df = get_myinvmt_df()

# merge above datasets
mypf_df = pd.merge(mypfs_df, mypps_df, on="Symbol")

# seggregate dm and sv portfolio
dm_pf = mypf_df[mypf_df['InPortfolio'] == 'DM']
sv_pf = mypf_df[mypf_df['InPortfolio'] == 'SV']

# build portfolio stock dataframe
dm_stocks = get_stock_ids(dm_pf)
sv_stocks = get_stock_ids(sv_pf)
df_stocks = pd.concat([dm_pf,sv_pf], ignore_index = True)

# arrange common and diff stock features
common_cols = ['Symbol', 'Target', 'Criteria', 'Strategy', 'CumlRnk', 'LatestQtr', 'StarStock', 'Conviction', 'Category', 'InFolio', 'XIRR', 'MBQ']
diff_cols = ['Symbol', 'AvgCost', 'Shares']
df_stocks = arrange_features(df_stocks, common_cols, diff_cols)

# get common features
stock_ids = df_stocks['Symbol'].values
df_common_features = get_common_features(stock_ids, df_stocks)

df_common_features.reset_index(drop=True, inplace=True)
df_common_features.drop(['Date'], axis=1, inplace=True)
# get and print portfolio features
df_portfolio_features = get_portfolio_features(df_common_features)

print_portfolio_stats(df_portfolio_features, myinvmt_df)

df = df_portfolio_features
#plot_pie_chart(df, 'CapType', 'Current')
list_ox40n = list(df[df['MBQ'].str.contains('OX40N', na=False)]['Symbol'].values)

Run date time (IST): 2026-07-30 15:34:48
-------------------
qualified stocks: 90
with latest results: 31
still star stocks: 20

-------------------
Initial Investment:  1.40 C
CY Investment:  1.82 C
Reserve:  6.53 L
Current:  1.54 C
-------------------
Today PnL: -32.19 K (-0.21%)
Current PnL: -31.09 L (-17.04%)
CY Booked + Current PnL: -27.45 L (-15.05%)
-------------------
Total profit:  4.01 L
Total loss:  -35.10 L
-------------------
Total Booked + Current PnL: 15.42 L (11.06%)
Total Booked PnL: 46.51 L (33.34%)
Curr Year Booked PnL: 3.64 L (2.37%)
Prev Year Booked PnL: 42.87 L (30.73%)
===================
Est FTT:  2.55 C
Est FTT PnL: 1.01 C (65.68%)
===================
Deployed:  1.40 C
Current:  1.54 C
CAGR/XIRR %: 4.29%

In [9]:
# top 5 near their targets
cols = ['Symbol', 'Today P/L%', 'Current P/L%', 'FTT%', 'OTT%', 'FTT Amt', 'Current P/L', 'Current', 'FTT', 'Dev%_PE', 'RSI_14','Conviction', 'Spread%',  'CumlRnk', 'RRR Ind', 'CurrAlloc%', 'Gained%', 'Criteria', 'Strategy', 'Category']
df_tmp = df_portfolio_features[~df_portfolio_features['Symbol'].isin(['ENRIN','BLUSPRING','DIGITIDE'])]
df_tmp = df_tmp.sort_values(by = 'FTT Amt', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
58,PIDILITIND,0.00,15.51,1.74,17.52,2836.0,21880.0,162990.0,1658.32,-19.15,64.0,X-LC,8.35,5.0,7.72,1.11,28.90,X40,ATH,CHEMICALS
71,SONACOMS,6.00,32.13,4.97,38.69,6643.0,32497.0,133656.0,801.69,4.64,80.0,M-MC,28.46,193.0,4.89,0.91,89.62,AR,ATH,AUTO
55,MEDANTA,-1.15,21.16,4.91,27.12,10501.0,37359.0,213876.0,1486.00,17.47,67.0,X-SC,13.15,87.0,3.56,1.45,47.37,XY24,NTT,HEALTHCARE
81,TTKPRESTIG,-3.03,-14.65,17.27,0.09,14855.0,-14762.0,86015.0,770.00,99.57,57.0,M-SC,12.92,250.0,-0.99,0.58,54.81,OX40N,NTT,DURABLES
82,UNITDSPR,1.83,12.53,7.32,20.77,19287.0,29343.0,263487.0,1644.00,-0.15,77.0,X-MC,5.66,64.0,1.52,1.79,26.66,X40N,NTT,BREWERIES

In [10]:
# top 5 today
df_tmp = df_portfolio_features.sort_values(by = 'Today P/L%', ascending=False)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
71,SONACOMS,6.00,32.13,4.97,38.69,6643.0,32497.0,133656.0,801.69,4.64,80.0,M-MC,28.46,193.0,4.89,0.91,89.62,AR,ATH,AUTO
5,ATULAUTO,4.20,-11.00,63.57,45.57,111527.0,-21692.0,175440.0,844.00,3808.11,66.0,M-SC,5.14,248.0,-0.19,1.19,35.01,XY24,NTT,AUTO
87,WHIRLPOOL,2.14,-35.43,181.74,81.92,134713.0,-40674.0,74124.0,2270.00,-62.17,56.0,M-SC,15.28,210.0,-0.30,0.50,6.38,XR,NTT,DURABLES
56,PAGEIND,2.02,7.16,24.66,33.59,70921.0,19216.0,287595.0,51217.29,-23.13,57.0,X-MC,10.20,55.0,0.27,1.96,36.58,X40,ATH,APPARELS
32,HAVELLS,2.00,-19.22,62.69,31.42,166102.0,-63034.0,264957.0,2052.62,-23.94,67.0,X-MC,9.76,63.0,-0.38,1.80,11.75,X40,ATH,ELECTRICAL

In [11]:
# bottom 5 today
df_tmp = df_portfolio_features.sort_values(by = 'Today P/L%', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
19,COLPAL,-3.77,-20.84,76.68,39.86,159862.0,-54885.0,208480.0,3683.41,-4.28,52.0,X-MC,1.66,62.0,-0.34,1.42,17.93,XY25,ATH,FMCG
81,TTKPRESTIG,-3.03,-14.65,17.27,0.09,14855.0,-14762.0,86015.0,770.00,99.57,57.0,M-SC,12.92,250.0,-0.99,0.58,54.81,OX40N,NTT,DURABLES
75,TANLA,-2.92,-32.98,224.14,117.25,406754.0,-89288.0,181473.0,1922.32,-32.24,58.0,H-SC,9.32,147.0,-0.22,1.23,58.88,AR,ATH,IT
24,EASEMYTRIP,-2.53,-63.80,302.44,45.70,193598.0,-112803.0,64012.0,26.40,-33.63,36.0,M-SC,6.22,204.0,-0.58,0.44,12.14,XY24,NTT,TRAVEL
26,GILLETTE,-2.19,-8.79,42.23,29.72,97792.0,-22326.0,231570.0,10978.86,-29.98,46.0,X-SC,3.46,83.0,-0.23,1.57,6.42,X40,ATH,FMCG

In [12]:
# top 5 to exit based on CumlRnk
df_tmp = df_portfolio_features[~df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])]
df_tmp = df_tmp[(df_tmp['Current P/L%'] > -1) & (df_tmp['Current P/L%'] < 1)].sort_values(by = 'CumlRnk', ascending=False)
df_tmp[cols].head()

Empty DataFrame
Columns: [Symbol, Today P/L%, Current P/L%, FTT%, OTT%, FTT Amt, Current P/L, Current, FTT, Dev%_PE, RSI_14, Conviction, Spread%, CumlRnk, RRR Ind, CurrAlloc%, Gained%, Criteria, Strategy, Category]
Index: []

In [13]:
# OX40N stocks to exit
df_tmp = df_portfolio_features[(df_portfolio_features['Symbol'].isin(list_ox40n))].sort_values(by = 'Current P/L%', ascending=False)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
25,FINCABLES,-1.21,23.24,68.71,107.91,125019.0,34307.0,181951.0,1641.55,11.11,37.0,M-SC,19.46,220.0,0.27,1.24,36.89,OX40N,ATH,CABLES
70,SIS,-1.44,-2.57,24.45,21.26,26451.0,-2848.0,108184.0,528.00,2580.83,44.0,H-SC,23.95,168.0,-0.11,0.74,60.85,OX40N,NTT,MISC
81,TTKPRESTIG,-3.03,-14.65,17.27,0.09,14855.0,-14762.0,86015.0,770.00,99.57,57.0,M-SC,12.92,250.0,-0.99,0.58,54.81,OX40N,NTT,DURABLES
16,CERA,-0.42,-20.02,54.90,23.89,77239.0,-35212.0,140691.0,9475.00,-22.91,49.0,H-SC,13.68,153.0,-0.46,0.96,36.76,OX40N,NTT,CERAMICS
43,INDIGOPNTS,-1.94,-23.22,30.26,0.02,40558.0,-40527.0,134032.0,1408.00,104.24,57.0,M-SC,4.03,222.0,-1.00,0.91,52.07,OX40N,NTT,PAINTS

In [14]:
# top 5 to book for rotation
df_tmp = df_portfolio_features[(df_portfolio_features['Current P/L%'] > 20) ].sort_values(by = 'CumlRnk', ascending=False)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
25,FINCABLES,-1.21,23.24,68.71,107.91,125019.0,34307.0,181951.0,1641.55,11.11,37.0,M-SC,19.46,220.0,0.27,1.24,36.89,OX40N,ATH,CABLES
71,SONACOMS,6.00,32.13,4.97,38.69,6643.0,32497.0,133656.0,801.69,4.64,80.0,M-MC,28.46,193.0,4.89,0.91,89.62,AR,ATH,AUTO
55,MEDANTA,-1.15,21.16,4.91,27.12,10501.0,37359.0,213876.0,1486.00,17.47,67.0,X-SC,13.15,87.0,3.56,1.45,47.37,XY24,NTT,HEALTHCARE
59,QUESS,0.75,27.02,36.91,73.90,50068.0,28856.0,135649.0,424.00,-31.68,73.0,X-SC,36.51,80.0,0.58,0.92,84.92,XY24,NTT,MISC

In [15]:
# top 5 to monitor for exit
df_tmp = df_portfolio_features[~df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])]
df_tmp = df_tmp[(df_tmp['Current P/L%'] > 0) ].sort_values(by = 'Dev%_PE', ascending=False)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
72,STARHEALTH,1.93,18.12,24.67,47.26,81919.0,50935.0,332058.0,761.00,86.37,64.0,H-SC,18.61,173.0,0.62,2.26,43.57,XY24,NTT,INSURANCE
62,RECLTD,0.17,1.49,18.97,20.74,39115.0,3025.0,206195.0,446.00,11.33,67.0,M-MC,2.14,191.0,0.08,1.40,22.88,XY25,NTT,FINANCE
25,FINCABLES,-1.21,23.24,68.71,107.91,125019.0,34307.0,181951.0,1641.55,11.11,37.0,M-SC,19.46,220.0,0.27,1.24,36.89,OX40N,ATH,CABLES
71,SONACOMS,6.00,32.13,4.97,38.69,6643.0,32497.0,133656.0,801.69,4.64,80.0,M-MC,28.46,193.0,4.89,0.91,89.62,AR,ATH,AUTO
89,ZYDUSLIFE,-0.68,17.59,15.24,35.51,37557.0,36863.0,246437.0,1285.01,2.25,49.0,H-MC,16.96,120.0,0.98,1.68,29.69,AR,ATH,PHARMA

In [16]:
# top 5 to book for rotation from weak conviction
df_tmp = df_portfolio_features[~df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])]
df_tmp = df_tmp[~df_tmp['Criteria'].isin(['XY25','XY24','X40', 'X40N'])].sort_values(by = 'RRR Ind', ascending=False)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
71,SONACOMS,6.00,32.13,4.97,38.69,6643.0,32497.0,133656.0,801.69,4.64,80.0,M-MC,28.46,193.0,4.89,0.91,89.62,AR,ATH,AUTO
89,ZYDUSLIFE,-0.68,17.59,15.24,35.51,37557.0,36863.0,246437.0,1285.01,2.25,49.0,H-MC,16.96,120.0,0.98,1.68,29.69,AR,ATH,PHARMA
25,FINCABLES,-1.21,23.24,68.71,107.91,125019.0,34307.0,181951.0,1641.55,11.11,37.0,M-SC,19.46,220.0,0.27,1.24,36.89,OX40N,ATH,CABLES
54,MASFIN,-1.78,-2.17,24.27,21.57,23263.0,-2130.0,95850.0,397.04,-15.54,52.0,H-SC,1.90,167.0,-0.09,0.65,14.25,XR,ATH,FINANCE
70,SIS,-1.44,-2.57,24.45,21.26,26451.0,-2848.0,108184.0,528.00,2580.83,44.0,H-SC,23.95,168.0,-0.11,0.74,60.85,OX40N,NTT,MISC

In [17]:
# top 5 to accumulate based on lowest RSI_14
df_tmp = df_portfolio_features[df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])].sort_values(by = 'RSI_14', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
57,PGHH,-1.41,-36.48,107.82,32.01,146238.0,-77888.0,135632.0,17616.87,-57.06,31.0,X-MC,19.34,57.0,-0.53,0.92,0.00,X40,ATH,FMCG
23,DMART,0.67,-6.88,39.17,29.60,91047.0,-17160.0,232440.0,5391.45,-21.48,36.0,X-LC,2.94,14.0,-0.19,1.58,6.24,X40N,ATH,FMCG
35,HDFCLIFE,-2.03,-10.80,48.77,32.71,65168.0,-16177.0,133623.0,811.41,-30.35,38.0,X-LC,15.87,31.0,-0.25,0.91,0.38,X40,ATH,INSURANCE
85,VBL,0.93,-8.83,48.48,35.37,139603.0,-27881.0,287961.0,670.16,-19.46,39.0,X-LC,7.12,13.0,-0.20,1.96,18.35,X40N,ATH,FMCG
39,ICICIGI,-0.66,-13.24,37.03,18.89,64290.0,-26492.0,173617.0,2244.41,-26.94,40.0,X-MC,7.86,66.0,-0.41,1.18,3.44,X40,ATH,INSURANCE

In [18]:
# top 5 to accumulate based on Spread and CumlRnk
df_tmp = df_portfolio_features[df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])]
df_tmp = df_tmp[(df_tmp['CumlRnk'] < 100)].sort_values(by = 'Spread%', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
19,COLPAL,-3.77,-20.84,76.68,39.86,159862.0,-54885.0,208480.0,3683.41,-4.28,52.0,X-MC,1.66,62.0,-0.34,1.42,17.93,XY25,ATH,FMCG
11,BERGEPAINT,0.25,-3.92,30.43,25.32,75357.0,-10108.0,247641.0,680.00,-9.11,58.0,X-MC,1.70,68.0,-0.13,1.68,28.89,XY24,NTT,PAINTS
8,BAJAJHLDNG,0.19,-1.91,30.12,27.63,56171.0,-3635.0,186490.0,14274.15,-9.33,63.0,X-LC,2.48,28.0,-0.06,1.27,26.99,X40,ATH,FINANCE
17,CIPLA,-0.54,18.72,12.39,33.43,22529.0,28673.0,181834.0,1648.14,-7.97,60.0,X-LC,2.91,18.0,1.27,1.24,24.13,X40N,ATH,PHARMA
23,DMART,0.67,-6.88,39.17,29.60,91047.0,-17160.0,232440.0,5391.45,-21.48,36.0,X-LC,2.94,14.0,-0.19,1.58,6.24,X40N,ATH,FMCG

In [19]:
# top 5 to accumulate based on lowest Gained%
df_tmp = df_portfolio_features[df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])].sort_values(by = 'Gained%', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
57,PGHH,-1.41,-36.48,107.82,32.01,146238.0,-77888.0,135632.0,17616.87,-57.06,31.0,X-MC,19.34,57.0,-0.53,0.92,0.00,X40,ATH,FMCG
35,HDFCLIFE,-2.03,-10.80,48.77,32.71,65168.0,-16177.0,133623.0,811.41,-30.35,38.0,X-LC,15.87,31.0,-0.25,0.91,0.38,X40,ATH,INSURANCE
64,RELIANCE,1.33,-17.01,50.98,25.30,85026.0,-34179.0,166784.0,1952.00,-19.26,49.0,X-LC,7.87,21.0,-0.40,1.13,2.71,XY25,BTT,REFINERIES
39,ICICIGI,-0.66,-13.24,37.03,18.89,64290.0,-26492.0,173617.0,2244.41,-26.94,40.0,X-MC,7.86,66.0,-0.41,1.18,3.44,X40,ATH,INSURANCE
47,ITC,-0.42,-24.92,58.57,19.06,149591.0,-84761.0,255405.0,452.00,-58.75,51.0,X-LC,12.20,1.0,-0.57,1.74,3.45,X40,NTT,FMCG

In [20]:
# top 5 to accumulate based on lowest CurrAlloc%
df_tmp = df_portfolio_features[df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])].sort_values(by = 'CurrAlloc%', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
10,BATAINDIA,0.24,-54.84,199.41,35.20,115865.0,-70566.0,58104.0,2096.00,-23.75,53.0,X-SC,16.34,91.0,-0.61,0.40,15.23,X40,NTT,FOOTWEAR
63,RELAXO,-0.23,-47.14,188.13,52.31,144356.0,-68428.0,76732.0,1176.00,-43.76,56.0,X-SC,9.43,92.0,-0.47,0.52,71.56,X40N,NTT,FOOTWEAR
35,HDFCLIFE,-2.03,-10.80,48.77,32.71,65168.0,-16177.0,133623.0,811.41,-30.35,38.0,X-LC,15.87,31.0,-0.25,0.91,0.38,X40,ATH,INSURANCE
57,PGHH,-1.41,-36.48,107.82,32.01,146238.0,-77888.0,135632.0,17616.87,-57.06,31.0,X-MC,19.34,57.0,-0.53,0.92,0.00,X40,ATH,FMCG
59,QUESS,0.75,27.02,36.91,73.90,50068.0,28856.0,135649.0,424.00,-31.68,73.0,X-SC,36.51,80.0,0.58,0.92,84.92,XY24,NTT,MISC

In [21]:
# top 5 to accumulate based on CumlRnk
df_tmp = df_portfolio_features.sort_values(by = 'CumlRnk', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
47,ITC,-0.42,-24.92,58.57,19.06,149591.0,-84761.0,255405.0,452.00,-58.75,51.0,X-LC,12.20,1.0,-0.57,1.74,3.45,X40,NTT,FMCG
77,TCS,-0.60,-28.61,73.97,24.20,244637.0,-132548.0,330725.0,4230.71,-39.69,72.0,X-LC,16.82,2.0,-0.54,2.25,23.33,X40,ATH,IT
45,INFY,-0.04,-21.37,70.72,34.24,173997.0,-66852.0,246036.0,1972.00,-37.95,64.0,X-LC,18.63,3.0,-0.38,1.67,17.23,X40,NTT,IT
79,TMPV,1.33,-23.93,79.53,36.58,215289.0,-85139.0,270702.0,600.00,-84.72,46.0,X-LC,6.80,4.0,-0.40,1.84,13.77,XY24,NTT,AUTO
58,PIDILITIND,0.00,15.51,1.74,17.52,2836.0,21880.0,162990.0,1658.32,-19.15,64.0,X-LC,8.35,5.0,7.72,1.11,28.90,X40,ATH,CHEMICALS

In [22]:
# top 5 for average up
df_tmp = df_portfolio_features[(df_portfolio_features['Dev%_200'] > 5)].sort_values(by = 'CurrAlloc%', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
44,INDUSINDBK,-0.08,-25.33,77.96,32.89,44946.0,-19554.0,57653.0,1800.00,-371.71,55.0,L-MC,14.46,258.0,-0.44,0.39,42.14,XR,NTT,BANKS
3,ALKYLAMINE,-1.66,-23.88,152.96,92.54,117550.0,-24113.0,76850.0,4520.85,-18.40,46.0,H-SC,12.93,142.0,-0.21,0.52,45.93,SR,ATH,CHEMICALS
63,RELAXO,-0.23,-47.14,188.13,52.31,144356.0,-68428.0,76732.0,1176.00,-43.76,56.0,X-SC,9.43,92.0,-0.47,0.52,71.56,X40N,NTT,FOOTWEAR
81,TTKPRESTIG,-3.03,-14.65,17.27,0.09,14855.0,-14762.0,86015.0,770.00,99.57,57.0,M-SC,12.92,250.0,-0.99,0.58,54.81,OX40N,NTT,DURABLES
70,SIS,-1.44,-2.57,24.45,21.26,26451.0,-2848.0,108184.0,528.00,2580.83,44.0,H-SC,23.95,168.0,-0.11,0.74,60.85,OX40N,NTT,MISC

In [23]:
# top 5 RSP
df_tmp = df_portfolio_features.sort_values(by = 'RSP', ascending=False)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
33,HCLTECH,0.62,-12.21,37.02,20.28,78621.0,-29550.0,212374.0,1853.42,-7.78,77.0,X-LC,15.51,8.0,-0.38,1.44,32.13,X40,ATH,IT
71,SONACOMS,6.00,32.13,4.97,38.69,6643.0,32497.0,133656.0,801.69,4.64,80.0,M-MC,28.46,193.0,4.89,0.91,89.62,AR,ATH,AUTO
77,TCS,-0.60,-28.61,73.97,24.20,244637.0,-132548.0,330725.0,4230.71,-39.69,72.0,X-LC,16.82,2.0,-0.54,2.25,23.33,X40,ATH,IT
22,DIXON,0.44,4.46,32.04,37.92,87284.0,11624.0,272422.0,18931.72,-55.57,66.0,X-MC,11.39,54.0,0.13,1.85,48.23,X40N,ATH,IT
59,QUESS,0.75,27.02,36.91,73.90,50068.0,28856.0,135649.0,424.00,-31.68,73.0,X-SC,36.51,80.0,0.58,0.92,84.92,XY24,NTT,MISC

In [24]:
# Top N allocation
df_tmp = df_portfolio_features.sort_values(by = 'CurrAlloc%', ascending=False)
top_n_values = [10, 25, 50]

sum_df = pd.DataFrame({
    'Top_N': top_n_values,
    'Sum_Alloc%': [df_tmp['CurrAlloc%'].head(n).sum() for n in top_n_values]
})

sum_df

   Top_N  Sum_Alloc%
0     10       19.39
1     25       42.92
2     50       73.86

In [25]:
# market-cap-wise allocation
df_tmp = df_portfolio_features[cols]
df_tmp.groupby(df_tmp['Conviction'].str[-2:])['CurrAlloc%'].sum().sort_values(ascending=False)

Conviction
SC    42.18
LC    31.83
MC    25.93
Name: CurrAlloc%, dtype: float64

In [26]:
# criteria-wise allocation
df_portfolio_features.groupby('Criteria')['CurrAlloc%'].sum().sort_values(ascending=False)

Criteria
X40      26.21
XY24     25.91
X40N     16.59
XR        9.21
AR        7.24
OX40N     7.14
XY25      6.74
SR        0.90
Name: CurrAlloc%, dtype: float64

In [27]:
# conviction-wise allocation
df_portfolio_features.groupby('Conviction')['CurrAlloc%'].sum().sort_values(ascending=False)

Conviction
X-LC    29.71
H-SC    20.69
X-MC    20.46
X-SC    10.65
M-SC    10.29
H-MC     2.77
M-MC     2.31
H-LC     1.24
M-LC     0.88
L-SC     0.55
L-MC     0.39
Name: CurrAlloc%, dtype: float64

In [28]:
# sector-wise stats
df_tmp = df_portfolio_features.groupby('Category')[['CurrAlloc%', 'Current', 'Current P/L', 'FTT Amt']].sum().sort_values(by=['Current', 'Current P/L'], ascending=False)
df_tmp['Current P/L%'] = round(df_tmp['Current P/L'] * 100 / df_tmp['Current'], 2)
df_tmp['FTT%'] = round(df_tmp['FTT Amt'] * 100 / df_tmp['Current'], 2)
cols = ['CurrAlloc%', 'Current P/L%', 'FTT%']
df_tmp[cols].sort_values(by=['CurrAlloc%'], ascending=False)

               CurrAlloc%  Current P/L%    FTT%
Category
FMCG                14.55        -23.57   66.91
IT                  11.11        -37.66  105.69
FINANCE              9.02        -18.08   67.48
MISC                 7.63        -19.45   70.71
AUTO                 7.13         -4.36   43.28
PAINTS               5.71        -17.18   37.17
BANKS                5.50        -12.13   63.95
INSURANCE            5.48         -2.77   37.43
PHARMA               5.46          7.67   20.27
ELECTRICAL           4.38         -9.53   47.88
CHEMICALS            2.24        -22.82   95.32
HEALTHCARE           2.21         -9.89   38.56
APPARELS             1.96          6.68   24.66
AC                   1.86        -16.89   48.58
BREWERIES            1.79         11.14    7.32
FOOTWEAR             1.77        -69.71  137.75
DURABLES             1.69        -54.89   92.57
TRAVEL               1.53        -99.01  198.65
CERAMICS             1.45        -43.87   87.58
ENGINEERING          1.28        -28.78   87.68
CABLES               1.24         18.86   68.71
JEWELLERY            1.16        -86.88  151.81
REFINERIES           1.13        -20.49   50.98
CEMENT               1.11        -64.72  187.95
ENTERTAINMENT        0.74        -78.26  184.57
TEXTILES             0.41        -51.15   94.25
HOTELS               0.40        -92.26  160.08

In [29]:
# money to be made criteria-wise
df_portfolio_features.groupby('Criteria')['FTT Amt'].agg(['sum', 'count']).sort_values(by='sum', ascending=False)

                sum  count
Criteria
XY24      3364417.0     20
X40       1807789.0     19
XR        1320283.0     13
AR        1106756.0      9
X40N      1020185.0     12
OX40N      741699.0     10
XY25       443822.0      5
SR         284209.0      2

In [30]:
# money to be made conviction-wise
df_portfolio_features.groupby('Conviction')['FTT Amt'].agg(['sum', 'count']).sort_values(by='sum', ascending=False)

                  sum  count
Conviction
H-SC        3306589.0     23
X-LC        1900722.0     21
X-MC        1441990.0     14
M-SC        1402822.0     14
X-SC        1234671.0      9
H-MC         290492.0      2
L-SC         209280.0      2
M-LC         162405.0      1
H-LC          49485.0      1
M-MC          45758.0      2
L-MC          44946.0      1

In [31]:
# money to be made criteria and conviction-wise
df_portfolio_features.groupby(['Conviction', 'Criteria'])['FTT Amt'].agg(['sum', 'count']).sort_values(by='sum', ascending=False)

                          sum  count
Conviction Criteria
H-SC       XY24      982857.0      5
X-LC       X40       953810.0     10
H-SC       AR        936944.0      5
M-SC       XY24      818071.0      6
H-SC       XR        792004.0      7
X-SC       XY24      731457.0      4
X-MC       X40       640322.0      7
X-LC       X40N      392397.0      6
           XY24      353934.0      2
X-MC       X40N      338231.0      3
M-SC       OX40N     316386.0      5
H-SC       OX40N     310575.0      4
X-SC       X40N      289557.0      3
H-SC       SR        284209.0      2
H-MC       XY24      252935.0      1
X-MC       XY25      238274.0      2
           XY24      225163.0      2
X-SC       X40       213657.0      2
M-SC       XR        192238.0      2
X-LC       XY25      166433.0      2
M-LC       XR        162405.0      1
L-SC       OX40N     114738.0      1
           XR         94542.0      1
M-SC       AR         76127.0      1
H-LC       AR         49485.0      1
L-MC       XR         44946.0      1
M-MC       XY25       39115.0      1
H-MC       AR         37557.0      1
X-LC       XR         34148.0      1
M-MC       AR          6643.0      1

In [32]:
# notebook execution time

end_time = time.time()
execution_time = round(end_time - start_time, 0)
print(f"Notebook execution time: {execution_time} seconds")

Notebook execution time: 35.0 seconds