<a href="https://colab.research.google.com/github/ankit-rathi/Quantvesting_v2/blob/main/myStocks_Portfolio_Analysis.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
'''
!pip install pandas==2.2.2 -qq
!pip install pyxirr -qq
!pip install ta -qq
!pip install yfinance==0.2.59 -qq
'''

'\n!pip install pandas==2.2.2 -qq\n!pip install pyxirr -qq\n!pip install ta -qq\n!pip install yfinance==0.2.59 -qq\n'

In [2]:
# import libraries

import numpy as np
import pandas as pd
import datetime
import warnings
warnings.filterwarnings('ignore')
import yfinance as yfin
import ta
import matplotlib.pyplot as plt
import requests

In [3]:
# notebook start time
import time
import datetime
import pytz

start_time = time.time()

# function to print date timestamp
def print_date_time():
  tz_NY = pytz.timezone('Asia/Kolkata')
  datetime_NY = datetime.datetime.now(tz_NY)
  print("Run date time (IST):", datetime_NY.strftime("%Y-%m-%d %H:%M:%S"))

In [4]:
# function to get booked and reserved amount
def get_amt():
  # fetch the JSON data from the URL
  url = "https://raw.githubusercontent.com/ankit-rathi/Tradevesting_v1/main/data/myPortfolioAmts.json"
  response = requests.get(url)
  pf_amts = response.json()  # parse the JSON data

  # extract values from the JSON
  py_booked_amt_dm = pf_amts["py_booked_amt_dm"]
  py_booked_amt_sv = pf_amts["py_booked_amt_sv"]
  cy_booked_amt_dm = pf_amts["cy_booked_amt_dm"]
  cy_booked_amt_sv = pf_amts["cy_booked_amt_sv"]
  reserve_amt_dm = pf_amts["reserve_amt_dm"]
  reserve_amt_sv = pf_amts["reserve_amt_sv"]

  # perform calculations
  py_booked_amt = py_booked_amt_dm + py_booked_amt_sv
  cy_booked_amt = cy_booked_amt_dm + cy_booked_amt_sv
  reserve_amt = reserve_amt_dm + reserve_amt_sv
  total_booked_amt = py_booked_amt + cy_booked_amt

  return total_booked_amt, reserve_amt, cy_booked_amt, py_booked_amt

gen_output = 0

In [5]:
# function to format the amount
def format_amt(number):
    abs_number = abs(number)

    if abs_number >= 1_00_00_000:  # Crores
        formatted_amt = f"{number / 1_00_00_000:.2f} C"
    elif abs_number >= 1_00_000:  # Lakhs
        formatted_amt = f"{number / 1_00_000:.2f} L"
    elif abs_number >= 1_000:  # Thousands
        formatted_amt = f"{number / 1_000:.2f} K"
    else:
        formatted_amt = f"{number:.2f}"

    return formatted_amt

# function to set start and end date
def get_start_end_date():
  start_date = (datetime.date.today() + datetime.timedelta(days=-365)).strftime('%Y-%m-%d')
  end_date = (datetime.date.today() + datetime.timedelta(days=1)).strftime('%Y-%m-%d')
  return start_date, end_date

# function to fetch my portfolio csv
def get_mypfs_df():
  mypfs_df = pd.read_csv('https://raw.githubusercontent.com/ankit-rathi/Tradevesting_v1/main/data/myPortfolioStocks.csv')
  return mypfs_df

# function to fetch my prospects csv
def get_mypps_df():
  mypps_df = pd.read_csv('https://raw.githubusercontent.com/ankit-rathi/Tradevesting_v1/main/data/myProspectsScrips.csv')
  return mypps_df

# function to fetch screener data
def get_myscreen_df():
  myscreen_df = pd.read_csv('https://raw.githubusercontent.com/ankit-rathi/Tradevesting_v1/main/data/myScreenerDB.csv')
  return myscreen_df

# function to fetch momentum data
def get_myinvmt_df():
  myinvmt_df = pd.read_csv('https://raw.githubusercontent.com/ankit-rathi/Tradevesting_v1/main/data/myInvestments.csv')
  return myinvmt_df

# function to get the stock ids
def get_stock_ids(df_pf):
  stock_n100 = df_pf['Symbol'].unique()

  exclude = ['CADILAHC','MMTC', 'MASFIN']

  stock_ids = df_pf[~df_pf['Symbol'].isin(exclude) ]['Symbol'].unique()

  #mypf = mypf[mypf.Forecast.notnull()]
  #stock_ids = mypf['Symbol'].unique()

  #stock_ids.sort()
  return stock_ids

# get features from screener data
def get_screener_features():
  myscreen_df = get_myscreen_df()
  cols = ['Symbol', 'EPS', 'MedPE', 'ROCE%', 'ROE%', 'CapType']
  return myscreen_df[cols]

# get relative strength
def get_relative_strength(stock_list):

    # Dictionary to store stock tickers and their corresponding percentage price change
    stock_changes = {}

    # Loop through each stock and fetch its price data
    for stock in stock_list:
        try:
            # Download the stock data for the given date range
            stock_data = yfin.Ticker(stock + '.NS').history(period='1mo', interval='1d')[map(str.title, ['open', 'close', 'low', 'high', 'volume'])]

            # Calculate the percentage change for the stock
            if len(stock_data) > 0:
                start_price = stock_data['Close'].iloc[0]
                end_price = stock_data['Close'].iloc[-1]
                percent_change = round(((end_price - start_price) / start_price) * 100, 2)
                stock_changes[stock] = percent_change
            else:
                stock_changes[stock] = np.nan  # If no data is available, set to NaN

        except Exception as e:
            print(f"Error fetching data for {stock}: {e}")
            stock_changes[stock] = np.nan

    # Create a DataFrame with stock tickers and their percentage changes
    df = pd.DataFrame(list(stock_changes.items()), columns=['Symbol', 'Percent_Change'])

    # Drop any stocks with missing data (NaN values)
    df = df.dropna()

    # Calculate the percentile rank based on percentage change
    df['RSP'] = round(df['Percent_Change'].rank(pct=True) * 100, 2)
    cols = ['Symbol', 'RSP']
    df = df[cols]
    # Sort by percentile rank (optional)
    df = df.sort_values(by='RSP', ascending=False).reset_index(drop=True)

    return df

In [6]:
# function to get stock technicals
def stock_prec_dev(stock_symbol):
    #stock_symbol = 'ULTRACEMCO.NS'
    short_window = 20
    mid_window = 50
    long_window = 200
    moving_avg = 'SMA'

    start = datetime.datetime(*map(int, start_date.split('-')))
    end = datetime.datetime(*map(int, end_date.split('-')))

    stock_df = yfin.Ticker(stock_symbol + '.NS').history(period='max', interval='1d')[map(str.title, ['open', 'close', 'low', 'high', 'volume'])]

    stock_df['Max'] = round(max(stock_df['Close']),2)
    stock_df = stock_df[(stock_df.index <= end_date) & (stock_df.index >= start_date)]
    stock_df['200_SMA'] = round(stock_df['Close'].rolling(window = 200, min_periods = 1).mean(),0)
    stock_df['Dev%_200'] = round((stock_df['Close'] - stock_df['200_SMA'])*100/stock_df['200_SMA'],2)
    stock_df.dropna(axis = 0, inplace = True) # remove any null rows

    stock_df['20_SMA'] = stock_df['Close'].rolling(window=20).mean()
    stock_df['50_SMA'] = stock_df['Close'].rolling(window=50).mean()
    stock_df['Symbol'] = stock_symbol

    stock_df['Close'] = round(stock_df['Close'],2)
    stock_df['Min'] = round(min(stock_df['Close']),2)
    stock_df['RSI_14'] = ta.momentum.RSIIndicator(close=stock_df['Close'], window=14).rsi()
    stock_df['RSI_14'] = round(stock_df['RSI_14'],0)
    stock_df['Prev_Close'] = stock_df['Close'].shift(1)
    stock_df.drop(['Open', 'Low', 'High', 'Volume'], axis=1, inplace=True)
    stock_df = stock_df.tail(1)

    max_SMA = max(stock_df['20_SMA'].item(), stock_df['50_SMA'].item(), stock_df['200_SMA'].item())
    min_SMA = min(stock_df['20_SMA'].item(), stock_df['50_SMA'].item(), stock_df['200_SMA'].item())
    ABS_Spread = max_SMA - min_SMA
    stock_df['Spread%'] = round((ABS_Spread / stock_df['200_SMA'].item()) * 100,2)

    return stock_df

# function to compute stock attributes
def get_common_features(stock_ids, df_mypf):

  df_prec_dev = pd.DataFrame()
  df_tmp = get_screener_features()
  df_rs = get_relative_strength(stock_ids)

  for stock_id in stock_ids:
      tmp = stock_prec_dev(stock_id)
      tmp = tmp.reset_index()
      df_prec_dev = pd.concat([df_prec_dev, tmp], ignore_index = True)
  df_prec_dev = pd.merge(df_prec_dev, df_mypf, on= 'Symbol')
  df_prec_dev = pd.merge(df_prec_dev, df_tmp, on= 'Symbol', how='left')
  df_prec_dev = pd.merge(df_prec_dev, df_rs, on= 'Symbol', how='left')
  #print(df_prec_dev.columns)
  df_prec_dev['Curr_PE'] = round(df_prec_dev['Close']/df_prec_dev['EPS'],1)
  df_prec_dev['Dev%_PE'] = round((df_prec_dev['Curr_PE'] - df_prec_dev['MedPE'])*100/df_prec_dev['MedPE'],2)
  df_prec_dev['Conviction'] = df_prec_dev['Conviction'] + '-' + df_prec_dev['CapType']
  return df_prec_dev

# function to arrange stock features
def arrange_features(df_stocks, common_cols, diff_cols):
  df_stocks_common = df_stocks[common_cols].drop_duplicates()
  df_stocks_diff = df_stocks[diff_cols]
  df_stocks_diff['Investment'] = df_stocks_diff['AvgCost'] * df_stocks_diff['Shares']
  df_stocks_diff = df_stocks_diff.groupby(['Symbol'])[['Shares', 'Investment']].aggregate(['sum']).reset_index()
  df_stocks_diff.columns = ['Symbol', 'Shares', 'Investment']
  df_stocks_diff['AvgCost'] = round(df_stocks_diff['Investment']/df_stocks_diff['Shares'],2)
  df_stocks = pd.merge(df_stocks_diff, df_stocks_common, on='Symbol')
  return df_stocks

# plot fact distribution across dimension
def plot_pie_chart(df, dimension, fact):
  # grouping the data by category and calculating the sum of fact for each type
  grouped_data = df.groupby(dimension)[fact].sum()

  # sorting the grouped data in descending order
  grouped_data = grouped_data.sort_values(ascending=False)

  # creating a pie chart
  grouped_data.plot.pie(autopct='%1.1f%%', startangle=90, figsize=(6, 6))

  # adding a title and displaying the plot
  plt.title(f'{dimension} {fact} Distribution')
  plt.ylabel('')  # To hide the y-label
  plt.show()

In [7]:
# function to get portfolio features

def get_portfolio_features(df_common_features):

  print_date_time()
  print('-------------------')

  #df_common_features["Target"] = df_common_features["Target"].fillna(df_common_features["Max"])
  df_common_features['NTT'] = np.where(df_common_features['Strategy']== 'NTT', df_common_features["Target"], df_common_features['Max'])
  df_common_features['LTT'] = np.where(df_common_features['Strategy']== 'BTT', df_common_features["Target"], df_common_features['Max'])
  df_common_features['BOL'] = df_common_features['Min']

  tmp_df = df_common_features[df_common_features['Symbol'].isin(mypf_df[mypf_df['InPortfolio'] != 'NA'].Symbol.values)]
  print('qualified stocks: '+str(len(tmp_df['Symbol'].unique())))
  tmp_df1 = tmp_df[tmp_df['LatestQtr'] == 1]
  print('with latest results: '+str(len(tmp_df1['Symbol'].unique())))
  tmp_df1 = tmp_df1[tmp_df1['StarStock'] == 1]
  print('still star stocks: '+str(len(tmp_df1['Symbol'].unique())))
  tmp_df['Investment'] = tmp_df['AvgCost'] * tmp_df['Shares']
  tmp_df['Current'] = round(tmp_df['Close'] * tmp_df['Shares'],0)
  tmp_df['Previous'] = tmp_df['Prev_Close'] * tmp_df['Shares']
  tmp_df['EstimatedST'] = tmp_df['NTT'] * tmp_df['Shares']
  tmp_df['EstimatedLT'] = tmp_df['LTT'] * tmp_df['Shares']
  tmp_df['Current P/L'] = round((tmp_df['Current'] - tmp_df['Investment']),0)
  tmp_df['Today P/L%'] = round((tmp_df['Current'] - tmp_df['Previous'])*100/tmp_df['Previous'],2)
  tmp_df['Current P/L%'] = round((tmp_df['Current'] - tmp_df['Investment'])*100/tmp_df['Investment'],2)
  tmp_df['EstimatedST P/L%'] = round((tmp_df['EstimatedST'] - tmp_df['Investment'])*100/tmp_df['Investment'],2)
  tmp_df['EstimatedLT P/L%'] = round((tmp_df['EstimatedLT'] - tmp_df['Investment'])*100/tmp_df['Investment'],2)
  tmp_df['NTT%'] = round((tmp_df['NTT'] - tmp_df['Close'])*100/tmp_df['Close'],2)
  tmp_df['LTT%'] = round((tmp_df['LTT'] - tmp_df['Close'])*100/tmp_df['Close'],2)
  tmp_df['Gained%'] = round((tmp_df['Close'] - tmp_df['BOL'])*100/tmp_df['BOL'],2)
  investment = round(sum(tmp_df['AvgCost']*tmp_df['Shares']),0)
  current = round(sum(tmp_df['Close']*tmp_df['Shares']),0)
  tmp_df['InitAlloc%'] = round(tmp_df['Investment']*100/investment,2)
  tmp_df['CurrAlloc%'] = round(tmp_df['Current']*100/current,2)
  tmp_df['FTT'] = tmp_df['LTT']
  tmp_df.loc[tmp_df['Strategy'] == 'NTT', 'FTT'] = tmp_df['NTT']
  tmp_df['FTT%'] = tmp_df['LTT%']
  tmp_df.loc[tmp_df['Strategy'] == 'NTT', 'FTT%'] = tmp_df['NTT%']
  tmp_df['FTT Amt'] = round(tmp_df['FTT%'] * tmp_df['Current']/100,0)
  tmp_df['OTT%'] = round((tmp_df['FTT'] - tmp_df['AvgCost'])*100/tmp_df['AvgCost'],2)
  tmp_df['RRR Ind'] = round(tmp_df['Current P/L']/tmp_df['FTT Amt'],2)
  tmp_df['Risk Ind'] = round(tmp_df['Current P/L%']*tmp_df['CurrAlloc%'],0)

  return tmp_df

# function to print portfolio features
def print_portfolio_stats(df_portfolio_features, myinvmt_df):
  from pyxirr import xirr

  total_booked_amt, reserve_amt, cy_booked_amt, py_booked_amt = get_amt()

  dates = myinvmt_df['Date'].values
  dates = np.append(dates, datetime.date.today().strftime('%d-%b-%y'))
  investment = myinvmt_df['Investment'].values
  dates= pd.to_datetime(dates)

  current = round(sum(df_portfolio_features['Close']*df_portfolio_features['Shares']),0) + reserve_amt
  investment_xirr = np.append(investment, current)
  cagr = round(xirr(pd.DataFrame({"dates": dates, "amounts": investment_xirr}))*100,2)

  investment = -sum(investment)
  invested = round(sum(df_portfolio_features['AvgCost']*df_portfolio_features['Shares']),0) + reserve_amt
  previous = round(sum(df_portfolio_features['Prev_Close']*df_portfolio_features['Shares']),0) + reserve_amt
  cy_invested = investment + py_booked_amt

  today_pnl_amount = current-previous
  today_pnl_percentage = round((current-previous)*100/previous,2)

  curr_pnl_amount = current-invested
  curr_pnl_percentage = round((curr_pnl_amount)*100/(cy_invested),2)

  cy_pnl_amount = cy_booked_amt + curr_pnl_amount
  cy_pnl_percentage = round((cy_pnl_amount)*100/cy_invested,2)

  overall_pnl_amount = total_booked_amt + curr_pnl_amount
  overall_pnl_percentage = round((overall_pnl_amount)*100/investment,2)

  estimate_st = round(sum(df_portfolio_features['FTT']*df_portfolio_features['Shares']),0)  + reserve_amt
  est_st_pnl_amount = estimate_st-current
  est_st_pnl_percentage = round((est_st_pnl_amount)*100/current,2)

  estimate_lt = round(sum(df_portfolio_features['LTT']*df_portfolio_features['Shares']),0)  + reserve_amt
  est_lt_pnl_amount = estimate_lt-current
  est_lt_pnl_percentage = round((est_lt_pnl_amount)*100/current,2)

  total_profit = round(sum(df_portfolio_features[df_portfolio_features['Current P/L%'] > 0]['Current']) - sum(df_portfolio_features[df_portfolio_features['Current P/L%'] > 0]['Investment']),0)
  total_loss = round(sum(df_portfolio_features[df_portfolio_features['Current P/L%'] < 0]['Current']) - sum(df_portfolio_features[df_portfolio_features['Current P/L%'] < 0]['Investment']),0)

  cy_booked_percentage = round((cy_booked_amt)*100/current,2)
  py_booked_percentage = round((py_booked_amt)*100/investment,2)
  total_booked_percentage = round((total_booked_amt)*100/investment,2)

  print('-------------------')
  print('Initial Investment: ', format_amt(investment))
  print('CY Investment: ', format_amt(cy_invested))
  print('Reserve: ', format_amt(reserve_amt))
  print('Current: ',  format_amt(current))
  print('-------------------')
  print('Today PnL: '+ '{} ({}%)'.format(format_amt(today_pnl_amount), today_pnl_percentage))
  print('Current PnL: '+ '{} ({}%)'.format(format_amt(curr_pnl_amount), curr_pnl_percentage))
  print('CY Booked + Current PnL: '+ '{} ({}%)'.format(format_amt(cy_pnl_amount), cy_pnl_percentage))
  print('-------------------')
  print('Total profit: ', format_amt(total_profit))
  print('Total loss: ', format_amt(total_loss))
  print('-------------------')
  print('Total Booked + Current PnL: '+ '{} ({}%)'.format(format_amt(overall_pnl_amount), overall_pnl_percentage))
  print('Total Booked PnL: '+ '{} ({}%)'.format(format_amt(total_booked_amt), total_booked_percentage))
  print('Curr Year Booked PnL: '+ '{} ({}%)'.format(format_amt(cy_booked_amt), cy_booked_percentage))
  print('Prev Year Booked PnL: '+ '{} ({}%)'.format(format_amt(py_booked_amt), py_booked_percentage))
  print('===================')
  print('Est FTT: ',  format_amt(estimate_st))
  print('Est FTT PnL: '+ '{} ({}%)'.format(format_amt(est_st_pnl_amount), est_st_pnl_percentage))

  print('===================')
  print('Deployed: ', format_amt(investment))

  print('Current: ', format_amt(current))

  print('CAGR/XIRR %: '+'{}%'.format(cagr))

In [8]:
# get start and end date
start_date, end_date = get_start_end_date()

# get portfolio and prospects data
mypfs_df = get_mypfs_df()
mypps_df = get_mypps_df()
myinvmt_df = get_myinvmt_df()

# merge above datasets
mypf_df = pd.merge(mypfs_df, mypps_df, on="Symbol")

# seggregate dm and sv portfolio
dm_pf = mypf_df[mypf_df['InPortfolio'] == 'DM']
sv_pf = mypf_df[mypf_df['InPortfolio'] == 'SV']

# build portfolio stock dataframe
dm_stocks = get_stock_ids(dm_pf)
sv_stocks = get_stock_ids(sv_pf)
df_stocks = pd.concat([dm_pf,sv_pf], ignore_index = True)

# arrange common and diff stock features
common_cols = ['Symbol', 'Target', 'Criteria', 'Strategy', 'CumlRnk', 'LatestQtr', 'StarStock', 'Conviction', 'Category', 'InFolio', 'XIRR', 'MBQ']
diff_cols = ['Symbol', 'AvgCost', 'Shares']
df_stocks = arrange_features(df_stocks, common_cols, diff_cols)

# get common features
stock_ids = df_stocks['Symbol'].values
df_common_features = get_common_features(stock_ids, df_stocks)

df_common_features.reset_index(drop=True, inplace=True)
df_common_features.drop(['Date'], axis=1, inplace=True)
# get and print portfolio features
df_portfolio_features = get_portfolio_features(df_common_features)

print_portfolio_stats(df_portfolio_features, myinvmt_df)

df = df_portfolio_features
#plot_pie_chart(df, 'CapType', 'Current')
list_ox40n = list(df[df['MBQ'].str.contains('OX40N', na=False)]['Symbol'].values)

Run date time (IST): 2026-08-13 14:20:57
-------------------
qualified stocks: 88
with latest results: 30
still star stocks: 19
-------------------
Initial Investment:  1.46 C
CY Investment:  1.89 C
Reserve:  2.21 L
Current:  1.61 C
-------------------
Today PnL: -21.20 K (-0.13%)
Current PnL: -31.88 L (-16.87%)
CY Booked + Current PnL: -27.23 L (-14.41%)
-------------------
Total profit:  3.81 L
Total loss:  -35.69 L
-------------------
Total Booked + Current PnL: 15.64 L (10.71%)
Total Booked PnL: 47.52 L (32.53%)
Curr Year Booked PnL: 4.65 L (2.89%)
Prev Year Booked PnL: 42.87 L (29.35%)
===================
Est FTT:  2.68 C
Est FTT PnL: 1.07 C (66.68%)
===================
Deployed:  1.46 C
Current:  1.61 C
CAGR/XIRR %: 4.36%

In [9]:
# top 5 near their targets
cols = ['Symbol', 'Today P/L%', 'Current P/L%', 'FTT%', 'OTT%', 'FTT Amt', 'Current P/L', 'Current', 'FTT', 'Dev%_PE', 'RSI_14','Conviction', 'Spread%',  'CumlRnk', 'RRR Ind', 'CurrAlloc%', 'Gained%', 'Criteria', 'Strategy', 'Category']
df_tmp = df_portfolio_features[~df_portfolio_features['Symbol'].isin(['ENRIN','BLUSPRING','DIGITIDE'])]
df_tmp = df_tmp.sort_values(by = 'FTT Amt', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
79,UNITDSPR,-0.39,12.32,7.52,20.77,19777.0,28844.0,262988.0,1644.00,-0.31,67.0,X-MC,9.09,64.0,1.46,1.66,26.42,X40N,NTT,BREWERIES
78,TTKPRESTIG,0.78,-23.19,30.31,0.09,23462.0,-23369.0,77408.0,770.00,79.72,40.0,M-SC,11.41,250.0,-1.00,0.49,39.32,OX40N,NTT,DURABLES
68,SIS,-0.85,-0.08,21.37,21.26,23707.0,-94.0,110938.0,528.00,2648.70,53.0,H-SC,22.26,168.0,-0.00,0.70,64.95,OX40N,NTT,MISC
87,ZYDUSLIFE,-2.90,23.39,9.82,35.51,25394.0,49018.0,258592.0,1285.01,7.21,60.0,H-MC,15.95,120.0,1.93,1.63,36.09,AR,ATH,PHARMA
52,M&M,0.13,7.61,10.41,18.82,26963.0,18327.0,259008.0,3762.88,-6.43,59.0,X-LC,4.53,25.0,0.68,1.63,17.49,X40N,ATH,AUTO

In [10]:
# top 5 today
df_tmp = df_portfolio_features.sort_values(by = 'Today P/L%', ascending=False)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
82,VALIANTORG,5.00,-29.02,145.35,74.15,168791.0,-47478.0,116127.0,838.00,-308.98,79.0,H-SC,4.68,145.0,-0.28,0.73,72.81,XR,NTT,CHEMICALS
28,GODREJCP,3.13,-15.10,56.54,32.90,119785.0,-37678.0,211859.0,1460.97,-12.20,31.0,X-LC,5.07,32.0,-0.31,1.34,3.13,X40N,ATH,FMCG
21,DEN,3.00,-47.34,169.78,42.07,75518.0,-39984.0,44480.0,75.00,58.03,50.0,M-SC,5.63,235.0,-0.53,0.28,20.97,AR,NTT,ENTERTAINMENT
51,LAOPALA,2.51,-41.67,138.44,39.09,105876.0,-54627.0,76478.0,464.00,66.91,60.0,H-SC,4.96,154.0,-0.52,0.48,18.66,AR,NTT,CERAMICS
75,TITAGARH,2.38,-19.66,81.40,45.74,158375.0,-47613.0,194564.0,1548.00,6.96,52.0,H-SC,7.60,175.0,-0.30,1.23,48.45,XY24,NTT,ENGINEERING

In [11]:
# bottom 5 today
df_tmp = df_portfolio_features.sort_values(by = 'Today P/L%', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
24,EASEMYTRIP,-4.33,-65.84,326.49,45.70,197206.0,-116413.0,60402.0,26.40,-37.27,28.0,M-SC,6.55,204.0,-0.59,0.38,5.81,XY24,NTT,TRAVEL
87,ZYDUSLIFE,-2.90,23.39,9.82,35.51,25394.0,49018.0,258592.0,1285.01,7.21,60.0,H-MC,15.95,120.0,1.93,1.63,36.09,AR,ATH,PHARMA
29,GREENPANEL,-2.35,-54.02,211.30,43.14,177872.0,-98898.0,84180.0,537.00,88.63,30.0,M-SC,10.17,225.0,-0.56,0.53,1.38,XY24,NTT,MISC
1,ABBOTINDIA,-2.33,-7.80,25.12,15.37,41425.0,-13945.0,164910.0,34390.26,-21.58,52.0,X-MC,4.95,58.0,-0.34,1.04,11.71,X40,ATH,PHARMA
25,FINCABLES,-2.19,58.57,31.11,107.91,72836.0,86480.0,234124.0,1641.55,42.57,72.0,M-SC,18.16,220.0,1.19,1.48,76.14,OX40N,ATH,CABLES

In [12]:
# top 5 to exit based on CumlRnk
df_tmp = df_portfolio_features[~df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])]
df_tmp = df_tmp[(df_tmp['Current P/L%'] > -1) & (df_tmp['Current P/L%'] < 1)].sort_values(by = 'CumlRnk', ascending=False)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
80,UTIAMC,-0.88,0.17,50.90,51.15,113357.0,375.0,222705.0,1371.68,-19.39,48.0,M-SC,7.65,229.0,0.0,1.41,4.32,XY24,ATH,FINANCE
68,SIS,-0.85,-0.08,21.37,21.26,23707.0,-94.0,110938.0,528.00,2648.70,53.0,H-SC,22.26,168.0,-0.0,0.70,64.95,OX40N,NTT,MISC

In [13]:
# OX40N stocks to exit
df_tmp = df_portfolio_features[(df_portfolio_features['Symbol'].isin(list_ox40n))].sort_values(by = 'Current P/L%', ascending=False)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
25,FINCABLES,-2.19,58.57,31.11,107.91,72836.0,86480.0,234124.0,1641.55,42.57,72.0,M-SC,18.16,220.0,1.19,1.48,76.14,OX40N,ATH,CABLES
68,SIS,-0.85,-0.08,21.37,21.26,23707.0,-94.0,110938.0,528.00,2648.70,53.0,H-SC,22.26,168.0,-0.00,0.70,64.95,OX40N,NTT,MISC
43,INDIGOPNTS,1.37,-19.20,23.78,0.02,33542.0,-33509.0,141050.0,1408.00,114.84,64.0,M-SC,5.99,222.0,-1.00,0.89,60.03,OX40N,NTT,PAINTS
16,CERA,0.79,-22.44,59.73,23.89,81493.0,-39467.0,136436.0,9475.00,-25.06,41.0,H-SC,12.42,153.0,-0.48,0.86,32.63,OX40N,NTT,CERAMICS
78,TTKPRESTIG,0.78,-23.19,30.31,0.09,23462.0,-23369.0,77408.0,770.00,79.72,40.0,M-SC,11.41,250.0,-1.00,0.49,39.32,OX40N,NTT,DURABLES

In [14]:
# top 5 to book for rotation
df_tmp = df_portfolio_features[(df_portfolio_features['Current P/L%'] > 20) ].sort_values(by = 'CumlRnk', ascending=False)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
25,FINCABLES,-2.19,58.57,31.11,107.91,72836.0,86480.0,234124.0,1641.55,42.57,72.0,M-SC,18.16,220.0,1.19,1.48,76.14,OX40N,ATH,CABLES
87,ZYDUSLIFE,-2.90,23.39,9.82,35.51,25394.0,49018.0,258592.0,1285.01,7.21,60.0,H-MC,15.95,120.0,1.93,1.63,36.09,AR,ATH,PHARMA
57,QUESS,-0.30,36.66,27.25,73.90,39769.0,39149.0,145942.0,424.00,-26.72,68.0,X-SC,41.63,80.0,0.98,0.92,100.87,XY24,NTT,MISC

In [15]:
# top 5 to monitor for exit
df_tmp = df_portfolio_features[~df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])]
df_tmp = df_tmp[(df_tmp['Current P/L%'] > 0) ].sort_values(by = 'Dev%_PE', ascending=False)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
69,STARHEALTH,0.51,13.45,29.81,47.26,95070.0,37797.0,318920.0,761.00,78.95,52.0,H-SC,16.48,173.0,0.40,2.01,37.89,XY24,NTT,INSURANCE
25,FINCABLES,-2.19,58.57,31.11,107.91,72836.0,86480.0,234124.0,1641.55,42.57,72.0,M-SC,18.16,220.0,1.19,1.48,76.14,OX40N,ATH,CABLES
87,ZYDUSLIFE,-2.90,23.39,9.82,35.51,25394.0,49018.0,258592.0,1285.01,7.21,60.0,H-MC,15.95,120.0,1.93,1.63,36.09,AR,ATH,PHARMA
80,UTIAMC,-0.88,0.17,50.90,51.15,113357.0,375.0,222705.0,1371.68,-19.39,48.0,M-SC,7.65,229.0,0.00,1.41,4.32,XY24,ATH,FINANCE

In [16]:
# top 5 to book for rotation from weak conviction
df_tmp = df_portfolio_features[~df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])]
df_tmp = df_tmp[~df_tmp['Criteria'].isin(['XY25','XY24','X40', 'X40N'])].sort_values(by = 'RRR Ind', ascending=False)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
87,ZYDUSLIFE,-2.90,23.39,9.82,35.51,25394.0,49018.0,258592.0,1285.01,7.21,60.0,H-MC,15.95,120.0,1.93,1.63,36.09,AR,ATH,PHARMA
25,FINCABLES,-2.19,58.57,31.11,107.91,72836.0,86480.0,234124.0,1641.55,42.57,72.0,M-SC,18.16,220.0,1.19,1.48,76.14,OX40N,ATH,CABLES
68,SIS,-0.85,-0.08,21.37,21.26,23707.0,-94.0,110938.0,528.00,2648.70,53.0,H-SC,22.26,168.0,-0.00,0.70,64.95,OX40N,NTT,MISC
3,ALKYLAMINE,1.81,-18.06,134.97,92.54,111663.0,-18231.0,82732.0,4520.85,-12.24,57.0,H-SC,13.77,142.0,-0.16,0.52,57.10,SR,ATH,CHEMICALS
42,INDIAMART,0.66,-22.81,160.28,100.92,152601.0,-28127.0,95209.0,4675.60,-65.23,44.0,H-SC,12.97,140.0,-0.18,0.60,3.06,AR,ATH,MISC

In [17]:
# top 5 to accumulate based on lowest RSI_14
df_tmp = df_portfolio_features[df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])].sort_values(by = 'RSI_14', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
28,GODREJCP,3.13,-15.10,56.54,32.90,119785.0,-37678.0,211859.0,1460.97,-12.20,31.0,X-LC,5.07,32.0,-0.31,1.34,3.13,X40N,ATH,FMCG
34,HDFCBANK,-0.33,-11.26,47.67,31.05,124001.0,-32997.0,260123.0,1073.00,-25.96,33.0,X-LC,12.03,26.0,-0.27,1.64,0.97,X40,BTT,BANKS
55,PAGEIND,-1.36,-1.47,35.59,33.59,94109.0,-3954.0,264425.0,51217.29,-29.41,34.0,X-MC,8.89,55.0,-0.04,1.67,25.57,X40,ATH,APPARELS
56,PGHH,0.60,-36.33,107.33,32.01,145917.0,-77568.0,135952.0,17616.87,-56.92,37.0,X-MC,19.21,57.0,-0.53,0.86,0.60,X40,ATH,FMCG
83,VBL,-0.43,-11.12,52.63,35.66,164586.0,-39122.0,312722.0,669.42,-21.86,39.0,X-LC,7.35,13.0,-0.24,1.97,15.14,X40N,ATH,FMCG

In [18]:
# top 5 to accumulate based on Spread and CumlRnk
df_tmp = df_portfolio_features[df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])]
df_tmp = df_tmp[(df_tmp['CumlRnk'] < 100)].sort_values(by = 'Spread%', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
19,COLPAL,-0.90,-24.55,85.38,39.86,169650.0,-64665.0,198700.0,3683.41,-8.76,40.0,X-MC,1.50,62.0,-0.38,1.25,12.40,XY25,ATH,FMCG
23,DMART,0.46,-1.07,32.84,31.42,101299.0,-3329.0,308461.0,5391.45,-17.73,53.0,X-LC,2.69,14.0,-0.03,1.95,11.31,X40N,ATH,FMCG
50,KOTAKBANK,0.18,2.82,15.66,18.92,38595.0,6754.0,246456.0,452.46,-10.27,51.0,X-LC,2.97,12.0,0.17,1.56,10.89,X40,ATH,BANKS
26,GILLETTE,0.06,-10.27,44.57,29.72,101539.0,-26076.0,227820.0,10978.86,-31.02,41.0,X-SC,3.20,83.0,-0.26,1.44,4.69,X40,ATH,FMCG
8,BAJAJHLDNG,-0.70,3.30,24.14,28.24,63839.0,8449.0,264454.0,14274.15,-4.76,64.0,X-LC,3.26,28.0,0.13,1.67,33.10,X40,ATH,FINANCE

In [19]:
# top 5 to accumulate based on lowest Gained%
df_tmp = df_portfolio_features[df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])].sort_values(by = 'Gained%', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
35,HDFCLIFE,0.26,-7.67,50.71,39.15,117400.0,-19225.0,231512.0,811.41,-31.24,40.0,X-LC,16.32,31.0,-0.16,1.46,0.46,X40,ATH,INSURANCE
56,PGHH,0.60,-36.33,107.33,32.01,145917.0,-77568.0,135952.0,17616.87,-56.92,37.0,X-MC,19.21,57.0,-0.53,0.86,0.60,X40,ATH,FMCG
47,ITC,0.49,-23.44,62.88,24.70,191243.0,-93138.0,304140.0,452.00,-59.97,40.0,X-LC,10.68,1.0,-0.49,1.92,0.71,X40,NTT,FMCG
34,HDFCBANK,-0.33,-11.26,47.67,31.05,124001.0,-32997.0,260123.0,1073.00,-25.96,33.0,X-LC,12.03,26.0,-0.27,1.64,0.97,X40,BTT,BANKS
20,DABUR,-0.11,-19.68,78.92,43.70,157239.0,-48830.0,199238.0,735.00,-27.04,40.0,X-MC,9.59,70.0,-0.31,1.26,1.38,XY24,BTT,FMCG

In [20]:
# top 5 to accumulate based on lowest CurrAlloc%
df_tmp = df_portfolio_features[df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])].sort_values(by = 'CurrAlloc%', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
10,BATAINDIA,1.70,-53.08,188.19,35.20,113603.0,-68304.0,60366.0,2096.00,-20.87,61.0,X-SC,12.86,91.0,-0.60,0.38,21.28,X40,NTT,FOOTWEAR
61,RELAXO,0.65,-45.64,180.20,52.31,142185.0,-66256.0,78904.0,1176.00,-42.12,57.0,X-SC,13.04,92.0,-0.47,0.50,76.42,X40N,NTT,FOOTWEAR
56,PGHH,0.60,-36.33,107.33,32.01,145917.0,-77568.0,135952.0,17616.87,-56.92,37.0,X-MC,19.21,57.0,-0.53,0.86,0.60,X40,ATH,FMCG
57,QUESS,-0.30,36.66,27.25,73.90,39769.0,39149.0,145942.0,424.00,-26.72,68.0,X-SC,41.63,80.0,0.98,0.92,100.87,XY24,NTT,MISC
2,ACC,-0.62,-40.72,194.88,74.81,309766.0,-109176.0,158952.0,3906.00,-57.90,41.0,X-SC,11.83,85.0,-0.35,1.00,6.19,XY24,BTT,CEMENT

In [21]:
# top 5 to accumulate based on CumlRnk
df_tmp = df_portfolio_features.sort_values(by = 'CumlRnk', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
47,ITC,0.49,-23.44,62.88,24.70,191243.0,-93138.0,304140.0,452.00,-59.97,40.0,X-LC,10.68,1.0,-0.49,1.92,0.71,X40,NTT,FMCG
74,TCS,0.79,-30.48,78.64,24.20,253291.0,-141184.0,322089.0,4230.71,-41.00,54.0,X-LC,15.03,2.0,-0.56,2.03,20.11,X40,ATH,IT
45,INFY,-0.60,-16.78,68.69,40.38,215200.0,-63178.0,313292.0,1972.00,-37.23,59.0,X-LC,16.09,3.0,-0.29,1.98,18.64,X40,NTT,IT
76,TMPV,1.40,-17.25,72.51,42.75,249668.0,-71785.0,344322.0,600.00,-83.62,55.0,X-LC,4.48,4.0,-0.29,2.17,18.40,XY24,NTT,AUTO
33,HCLTECH,0.06,-8.62,35.66,23.97,100848.0,-26683.0,282803.0,1853.42,-6.95,70.0,X-LC,12.40,8.0,-0.26,1.78,33.45,X40,ATH,IT

In [22]:
# top 5 for average up
df_tmp = df_portfolio_features[(df_portfolio_features['Dev%_200'] > 5)].sort_values(by = 'CurrAlloc%', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
44,INDUSINDBK,0.29,-24.66,76.38,32.89,44429.0,-19038.0,58168.0,1800.00,-373.81,55.0,L-MC,13.68,258.0,-0.43,0.37,43.41,XR,NTT,BANKS
61,RELAXO,0.65,-45.64,180.20,52.31,142185.0,-66256.0,78904.0,1176.00,-42.12,57.0,X-SC,13.04,92.0,-0.47,0.50,76.42,X40N,NTT,FOOTWEAR
3,ALKYLAMINE,1.81,-18.06,134.97,92.54,111663.0,-18231.0,82732.0,4520.85,-12.24,57.0,H-SC,13.77,142.0,-0.16,0.52,57.10,SR,ATH,CHEMICALS
12,BOSCH-HCIL,-1.39,-25.95,35.03,-0.01,33152.0,-33165.0,94640.0,2282.00,19269.57,79.0,M-SC,4.22,231.0,-1.00,0.60,61.09,OX40N,BTT,AC
68,SIS,-0.85,-0.08,21.37,21.26,23707.0,-94.0,110938.0,528.00,2648.70,53.0,H-SC,22.26,168.0,-0.00,0.70,64.95,OX40N,NTT,MISC

In [23]:
# top 5 RSP
df_tmp = df_portfolio_features.sort_values(by = 'RSP', ascending=False)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
12,BOSCH-HCIL,-1.39,-25.95,35.03,-0.01,33152.0,-33165.0,94640.0,2282.00,19269.57,79.0,M-SC,4.22,231.0,-1.00,0.60,61.09,OX40N,BTT,AC
82,VALIANTORG,5.00,-29.02,145.35,74.15,168791.0,-47478.0,116127.0,838.00,-308.98,79.0,H-SC,4.68,145.0,-0.28,0.73,72.81,XR,NTT,CHEMICALS
25,FINCABLES,-2.19,58.57,31.11,107.91,72836.0,86480.0,234124.0,1641.55,42.57,72.0,M-SC,18.16,220.0,1.19,1.48,76.14,OX40N,ATH,CABLES
67,SIEMENS,-0.97,6.93,16.80,24.90,33432.0,12905.0,199000.0,4648.66,67.12,67.0,H-LC,12.69,51.0,0.39,1.26,40.40,AR,ATH,ELECTRICAL
38,HYUNDAI,-0.17,15.67,24.44,43.94,71049.0,39374.0,290706.0,2782.73,-4.08,73.0,X-LC,4.15,29.0,0.55,1.83,33.47,X40N,ATH,AUTO

In [24]:
# Top N allocation
df_tmp = df_portfolio_features.sort_values(by = 'CurrAlloc%', ascending=False)
top_n_values = [10, 25, 50]

sum_df = pd.DataFrame({
    'Top_N': top_n_values,
    'Sum_Alloc%': [df_tmp['CurrAlloc%'].head(n).sum() for n in top_n_values]
})

sum_df

   Top_N  Sum_Alloc%
0     10       19.78
1     25       44.79
2     50       76.84

In [25]:
# market-cap-wise allocation
df_tmp = df_portfolio_features[cols]
df_tmp.groupby(df_tmp['Conviction'].str[-2:])['CurrAlloc%'].sum().sort_values(ascending=False)

Conviction
SC    39.38
LC    37.63
MC    22.96
Name: CurrAlloc%, dtype: float64

In [26]:
# criteria-wise allocation
df_portfolio_features.groupby('Criteria')['CurrAlloc%'].sum().sort_values(ascending=False)

Criteria
X40      26.33
XY24     24.93
X40N     18.34
XR        9.07
XY25      7.20
OX40N     7.15
AR        6.10
SR        0.85
Name: CurrAlloc%, dtype: float64

In [27]:
# conviction-wise allocation
df_portfolio_features.groupby('Conviction')['CurrAlloc%'].sum().sort_values(ascending=False)

Conviction
X-LC    35.57
H-SC    19.28
X-MC    18.72
M-SC    11.09
X-SC     8.52
H-MC     2.67
H-LC     1.26
M-MC     1.20
M-LC     0.80
L-SC     0.49
L-MC     0.37
Name: CurrAlloc%, dtype: float64

In [28]:
# sector-wise stats
df_tmp = df_portfolio_features.groupby('Category')[['CurrAlloc%', 'Current', 'Current P/L', 'FTT Amt']].sum().sort_values(by=['Current', 'Current P/L'], ascending=False)
df_tmp['Current P/L%'] = round(df_tmp['Current P/L'] * 100 / df_tmp['Current'], 2)
df_tmp['FTT%'] = round(df_tmp['FTT Amt'] * 100 / df_tmp['Current'], 2)
cols = ['CurrAlloc%', 'Current P/L%', 'FTT%']
df_tmp[cols].sort_values(by=['CurrAlloc%'], ascending=False)

               CurrAlloc%  Current P/L%    FTT%
Category
FMCG                15.32        -22.87   67.04
IT                  11.08        -35.68  103.02
FINANCE             10.67        -14.20   63.40
AUTO                 8.29         -2.89   39.74
MISC                 6.88        -22.87   75.59
BANKS                6.08        -11.06   58.95
PHARMA               5.69          8.22   17.81
INSURANCE            5.60         -4.66   41.67
PAINTS               5.48        -13.46   32.82
ELECTRICAL           4.12         -8.42   46.39
AC                   1.82        -11.06   41.17
REFINERIES           1.69        -11.13   48.46
APPARELS             1.67         -1.50   35.59
FOOTWEAR             1.66        -67.63  134.84
BREWERIES            1.66         10.97    7.52
CABLES               1.48         36.94   31.11
DURABLES             1.47        -66.17  106.60
TRAVEL               1.42        -98.22  197.47
CERAMICS             1.34        -44.19   88.00
CHEMICALS            1.25        -33.04  141.03
ENGINEERING          1.23        -24.47   81.40
CEMENT               1.00        -68.68  194.88
JEWELLERY            0.97       -108.76  181.29
ENTERTAINMENT        0.69        -77.36  183.14
HEALTHCARE           0.68        -67.28  109.27
TEXTILES             0.38        -51.34   94.49
HOTELS               0.35       -102.05  173.32

In [29]:
# money to be made criteria-wise
df_portfolio_features.groupby('Criteria')['FTT Amt'].agg(['sum', 'count']).sort_values(by='sum', ascending=False)

                sum  count
Criteria
XY24      3561137.0     20
X40       2052922.0     18
XR        1357649.0     13
X40N      1174734.0     12
AR        1065958.0      8
OX40N      659427.0     10
XY25       557814.0      5
SR         281933.0      2

In [30]:
# money to be made conviction-wise
df_portfolio_features.groupby('Conviction')['FTT Amt'].agg(['sum', 'count']).sort_values(by='sum', ascending=False)

                  sum  count
Conviction
H-SC        3296330.0     23
X-LC        2418367.0     20
M-SC        1495350.0     15
X-MC        1487323.0     14
X-SC        1229279.0      8
H-MC         273822.0      2
L-SC         213077.0      2
M-LC         164606.0      1
M-MC          55559.0      1
L-MC          44429.0      1
H-LC          33432.0      1

In [31]:
# money to be made criteria and conviction-wise
df_portfolio_features.groupby(['Conviction', 'Criteria'])['FTT Amt'].agg(['sum', 'count']).sort_values(by='sum', ascending=False)

                           sum  count
Conviction Criteria
X-LC       X40       1175339.0      9
H-SC       XY24       991550.0      5
M-SC       XY24       974617.0      7
H-SC       AR         931614.0      5
           XR         798762.0      7
X-SC       XY24       708195.0      3
X-MC       X40        662441.0      7
X-LC       X40N       518498.0      6
           XY24       418718.0      2
X-MC       X40N       350294.0      3
X-SC       X40N       305942.0      3
H-SC       OX40N      292471.0      4
           SR         281933.0      2
X-MC       XY25       254959.0      2
M-SC       OX40N      251281.0      5
H-MC       XY24       248428.0      1
X-LC       XY25       247296.0      2
X-MC       XY24       219629.0      2
X-SC       X40        215142.0      2
M-SC       XR         193934.0      2
M-LC       XR         164606.0      1
L-SC       OX40N      115675.0      1
           XR          97402.0      1
M-SC       AR          75518.0      1
X-LC       XR          58516.0      1
M-MC       XY25        55559.0      1
L-MC       XR          44429.0      1
H-LC       AR          33432.0      1
H-MC       AR          25394.0      1

In [32]:
# notebook execution time

end_time = time.time()
execution_time = round(end_time - start_time, 0)
print(f"Notebook execution time: {execution_time} seconds")

Notebook execution time: 23.0 seconds