<a href="https://colab.research.google.com/github/ankit-rathi/Quantvesting_v2/blob/main/myStocks_Portfolio_Analysis.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
'''
!pip install pandas==2.2.2 -qq
!pip install pyxirr -qq
!pip install ta -qq
!pip install yfinance==0.2.59 -qq
'''

'\n!pip install pandas==2.2.2 -qq\n!pip install pyxirr -qq\n!pip install ta -qq\n!pip install yfinance==0.2.59 -qq\n'

In [2]:
# import libraries

import numpy as np
import pandas as pd
import datetime
import warnings
warnings.filterwarnings('ignore')
import yfinance as yfin
import ta
import matplotlib.pyplot as plt
import requests

In [3]:
# notebook start time
import time
import datetime
import pytz

start_time = time.time()

# function to print date timestamp
def print_date_time():
  tz_NY = pytz.timezone('Asia/Kolkata')
  datetime_NY = datetime.datetime.now(tz_NY)
  print("Run date time (IST):", datetime_NY.strftime("%Y-%m-%d %H:%M:%S"))

In [4]:
# function to get booked and reserved amount
def get_amt():
  # fetch the JSON data from the URL
  url = "https://raw.githubusercontent.com/ankit-rathi/Tradevesting_v1/main/data/myPortfolioAmts.json"
  response = requests.get(url)
  pf_amts = response.json()  # parse the JSON data

  # extract values from the JSON
  py_booked_amt_dm = pf_amts["py_booked_amt_dm"]
  py_booked_amt_sv = pf_amts["py_booked_amt_sv"]
  cy_booked_amt_dm = pf_amts["cy_booked_amt_dm"]
  cy_booked_amt_sv = pf_amts["cy_booked_amt_sv"]
  reserve_amt_dm = pf_amts["reserve_amt_dm"]
  reserve_amt_sv = pf_amts["reserve_amt_sv"]

  # perform calculations
  py_booked_amt = py_booked_amt_dm + py_booked_amt_sv
  cy_booked_amt = cy_booked_amt_dm + cy_booked_amt_sv
  reserve_amt = reserve_amt_dm + reserve_amt_sv
  total_booked_amt = py_booked_amt + cy_booked_amt

  return total_booked_amt, reserve_amt, cy_booked_amt, py_booked_amt

gen_output = 0

In [5]:
# function to format the amount
def format_amt(number):
    abs_number = abs(number)

    if abs_number >= 1_00_00_000:  # Crores
        formatted_amt = f"{number / 1_00_00_000:.2f} C"
    elif abs_number >= 1_00_000:  # Lakhs
        formatted_amt = f"{number / 1_00_000:.2f} L"
    elif abs_number >= 1_000:  # Thousands
        formatted_amt = f"{number / 1_000:.2f} K"
    else:
        formatted_amt = f"{number:.2f}"

    return formatted_amt

# function to set start and end date
def get_start_end_date():
  start_date = (datetime.date.today() + datetime.timedelta(days=-365)).strftime('%Y-%m-%d')
  end_date = (datetime.date.today() + datetime.timedelta(days=1)).strftime('%Y-%m-%d')
  return start_date, end_date

# function to fetch my portfolio csv
def get_mypfs_df():
  mypfs_df = pd.read_csv('https://raw.githubusercontent.com/ankit-rathi/Tradevesting_v1/main/data/myPortfolioStocks.csv')
  return mypfs_df

# function to fetch my prospects csv
def get_mypps_df():
  mypps_df = pd.read_csv('https://raw.githubusercontent.com/ankit-rathi/Tradevesting_v1/main/data/myProspectsScrips.csv')
  return mypps_df

# function to fetch screener data
def get_myscreen_df():
  myscreen_df = pd.read_csv('https://raw.githubusercontent.com/ankit-rathi/Tradevesting_v1/main/data/myScreenerDB.csv')
  return myscreen_df

# function to fetch momentum data
def get_myinvmt_df():
  myinvmt_df = pd.read_csv('https://raw.githubusercontent.com/ankit-rathi/Tradevesting_v1/main/data/myInvestments.csv')
  return myinvmt_df

# function to get the stock ids
def get_stock_ids(df_pf):
  stock_n100 = df_pf['Symbol'].unique()

  exclude = ['CADILAHC','MMTC', 'MASFIN']

  stock_ids = df_pf[~df_pf['Symbol'].isin(exclude) ]['Symbol'].unique()

  #mypf = mypf[mypf.Forecast.notnull()]
  #stock_ids = mypf['Symbol'].unique()

  #stock_ids.sort()
  return stock_ids

# get features from screener data
def get_screener_features():
  myscreen_df = get_myscreen_df()
  cols = ['Symbol', 'EPS', 'MedPE', 'ROCE%', 'ROE%', 'CapType']
  return myscreen_df[cols]

# get relative strength
def get_relative_strength(stock_list):

    # Dictionary to store stock tickers and their corresponding percentage price change
    stock_changes = {}

    # Loop through each stock and fetch its price data
    for stock in stock_list:
        try:
            # Download the stock data for the given date range
            stock_data = yfin.Ticker(stock + '.NS').history(period='1mo', interval='1d')[map(str.title, ['open', 'close', 'low', 'high', 'volume'])]

            # Calculate the percentage change for the stock
            if len(stock_data) > 0:
                start_price = stock_data['Close'].iloc[0]
                end_price = stock_data['Close'].iloc[-1]
                percent_change = round(((end_price - start_price) / start_price) * 100, 2)
                stock_changes[stock] = percent_change
            else:
                stock_changes[stock] = np.nan  # If no data is available, set to NaN

        except Exception as e:
            print(f"Error fetching data for {stock}: {e}")
            stock_changes[stock] = np.nan

    # Create a DataFrame with stock tickers and their percentage changes
    df = pd.DataFrame(list(stock_changes.items()), columns=['Symbol', 'Percent_Change'])

    # Drop any stocks with missing data (NaN values)
    df = df.dropna()

    # Calculate the percentile rank based on percentage change
    df['RSP'] = round(df['Percent_Change'].rank(pct=True) * 100, 2)
    cols = ['Symbol', 'RSP']
    df = df[cols]
    # Sort by percentile rank (optional)
    df = df.sort_values(by='RSP', ascending=False).reset_index(drop=True)

    return df

In [6]:
# function to get stock technicals
def stock_prec_dev(stock_symbol):
    #stock_symbol = 'ULTRACEMCO.NS'
    short_window = 20
    mid_window = 50
    long_window = 200
    moving_avg = 'SMA'

    start = datetime.datetime(*map(int, start_date.split('-')))
    end = datetime.datetime(*map(int, end_date.split('-')))

    stock_df = yfin.Ticker(stock_symbol + '.NS').history(period='max', interval='1d')[map(str.title, ['open', 'close', 'low', 'high', 'volume'])]

    stock_df['Max'] = round(max(stock_df['Close']),2)
    stock_df = stock_df[(stock_df.index <= end_date) & (stock_df.index >= start_date)]
    stock_df['200_SMA'] = round(stock_df['Close'].rolling(window = 200, min_periods = 1).mean(),0)
    stock_df['Dev%_200'] = round((stock_df['Close'] - stock_df['200_SMA'])*100/stock_df['200_SMA'],2)
    stock_df.dropna(axis = 0, inplace = True) # remove any null rows

    stock_df['20_SMA'] = stock_df['Close'].rolling(window=20).mean()
    stock_df['50_SMA'] = stock_df['Close'].rolling(window=50).mean()
    stock_df['Symbol'] = stock_symbol

    stock_df['Close'] = round(stock_df['Close'],2)
    stock_df['Min'] = round(min(stock_df['Close']),2)
    stock_df['RSI_14'] = ta.momentum.RSIIndicator(close=stock_df['Close'], window=14).rsi()
    stock_df['RSI_14'] = round(stock_df['RSI_14'],0)
    stock_df['Prev_Close'] = stock_df['Close'].shift(1)
    stock_df.drop(['Open', 'Low', 'High', 'Volume'], axis=1, inplace=True)
    stock_df = stock_df.tail(1)

    max_SMA = max(stock_df['20_SMA'].item(), stock_df['50_SMA'].item(), stock_df['200_SMA'].item())
    min_SMA = min(stock_df['20_SMA'].item(), stock_df['50_SMA'].item(), stock_df['200_SMA'].item())
    ABS_Spread = max_SMA - min_SMA
    stock_df['Spread%'] = round((ABS_Spread / stock_df['200_SMA'].item()) * 100,2)

    return stock_df

# function to compute stock attributes
def get_common_features(stock_ids, df_mypf):

  df_prec_dev = pd.DataFrame()
  df_tmp = get_screener_features()
  df_rs = get_relative_strength(stock_ids)

  for stock_id in stock_ids:
      tmp = stock_prec_dev(stock_id)
      tmp = tmp.reset_index()
      df_prec_dev = pd.concat([df_prec_dev, tmp], ignore_index = True)
  df_prec_dev = pd.merge(df_prec_dev, df_mypf, on= 'Symbol')
  df_prec_dev = pd.merge(df_prec_dev, df_tmp, on= 'Symbol', how='left')
  df_prec_dev = pd.merge(df_prec_dev, df_rs, on= 'Symbol', how='left')
  #print(df_prec_dev.columns)
  df_prec_dev['Curr_PE'] = round(df_prec_dev['Close']/df_prec_dev['EPS'],1)
  df_prec_dev['Dev%_PE'] = round((df_prec_dev['Curr_PE'] - df_prec_dev['MedPE'])*100/df_prec_dev['MedPE'],2)
  df_prec_dev['Conviction'] = df_prec_dev['Conviction'] + '-' + df_prec_dev['CapType']
  return df_prec_dev

# function to arrange stock features
def arrange_features(df_stocks, common_cols, diff_cols):
  df_stocks_common = df_stocks[common_cols].drop_duplicates()
  df_stocks_diff = df_stocks[diff_cols]
  df_stocks_diff['Investment'] = df_stocks_diff['AvgCost'] * df_stocks_diff['Shares']
  df_stocks_diff = df_stocks_diff.groupby(['Symbol'])[['Shares', 'Investment']].aggregate(['sum']).reset_index()
  df_stocks_diff.columns = ['Symbol', 'Shares', 'Investment']
  df_stocks_diff['AvgCost'] = round(df_stocks_diff['Investment']/df_stocks_diff['Shares'],2)
  df_stocks = pd.merge(df_stocks_diff, df_stocks_common, on='Symbol')
  return df_stocks

# plot fact distribution across dimension
def plot_pie_chart(df, dimension, fact):
  # grouping the data by category and calculating the sum of fact for each type
  grouped_data = df.groupby(dimension)[fact].sum()

  # sorting the grouped data in descending order
  grouped_data = grouped_data.sort_values(ascending=False)

  # creating a pie chart
  grouped_data.plot.pie(autopct='%1.1f%%', startangle=90, figsize=(6, 6))

  # adding a title and displaying the plot
  plt.title(f'{dimension} {fact} Distribution')
  plt.ylabel('')  # To hide the y-label
  plt.show()

In [7]:
# function to get portfolio features

def get_portfolio_features(df_common_features):

  print_date_time()
  print('-------------------')

  #df_common_features["Target"] = df_common_features["Target"].fillna(df_common_features["Max"])
  df_common_features['NTT'] = np.where(df_common_features['Strategy']== 'NTT', df_common_features["Target"], df_common_features['Max'])
  df_common_features['LTT'] = np.where(df_common_features['Strategy']== 'BTT', df_common_features["Target"], df_common_features['Max'])
  df_common_features['BOL'] = df_common_features['Min']

  tmp_df = df_common_features[df_common_features['Symbol'].isin(mypf_df[mypf_df['InPortfolio'] != 'NA'].Symbol.values)]
  print('qualified stocks: '+str(len(tmp_df['Symbol'].unique())))
  tmp_df1 = tmp_df[tmp_df['LatestQtr'] == 1]
  print('with latest results: '+str(len(tmp_df1['Symbol'].unique())))
  tmp_df1 = tmp_df1[tmp_df1['StarStock'] == 1]
  print('still star stocks: '+str(len(tmp_df1['Symbol'].unique())))
  tmp_df['Investment'] = tmp_df['AvgCost'] * tmp_df['Shares']
  tmp_df['Current'] = round(tmp_df['Close'] * tmp_df['Shares'],0)
  tmp_df['Previous'] = tmp_df['Prev_Close'] * tmp_df['Shares']
  tmp_df['EstimatedST'] = tmp_df['NTT'] * tmp_df['Shares']
  tmp_df['EstimatedLT'] = tmp_df['LTT'] * tmp_df['Shares']
  tmp_df['Current P/L'] = round((tmp_df['Current'] - tmp_df['Investment']),0)
  tmp_df['Today P/L%'] = round((tmp_df['Current'] - tmp_df['Previous'])*100/tmp_df['Previous'],2)
  tmp_df['Current P/L%'] = round((tmp_df['Current'] - tmp_df['Investment'])*100/tmp_df['Investment'],2)
  tmp_df['EstimatedST P/L%'] = round((tmp_df['EstimatedST'] - tmp_df['Investment'])*100/tmp_df['Investment'],2)
  tmp_df['EstimatedLT P/L%'] = round((tmp_df['EstimatedLT'] - tmp_df['Investment'])*100/tmp_df['Investment'],2)
  tmp_df['NTT%'] = round((tmp_df['NTT'] - tmp_df['Close'])*100/tmp_df['Close'],2)
  tmp_df['LTT%'] = round((tmp_df['LTT'] - tmp_df['Close'])*100/tmp_df['Close'],2)
  tmp_df['Gained%'] = round((tmp_df['Close'] - tmp_df['BOL'])*100/tmp_df['BOL'],2)
  investment = round(sum(tmp_df['AvgCost']*tmp_df['Shares']),0)
  current = round(sum(tmp_df['Close']*tmp_df['Shares']),0)
  tmp_df['InitAlloc%'] = round(tmp_df['Investment']*100/investment,2)
  tmp_df['CurrAlloc%'] = round(tmp_df['Current']*100/current,2)
  tmp_df['FTT'] = tmp_df['LTT']
  tmp_df.loc[tmp_df['Strategy'] == 'NTT', 'FTT'] = tmp_df['NTT']
  tmp_df['FTT%'] = tmp_df['LTT%']
  tmp_df.loc[tmp_df['Strategy'] == 'NTT', 'FTT%'] = tmp_df['NTT%']
  tmp_df['FTT Amt'] = round(tmp_df['FTT%'] * tmp_df['Current']/100,0)
  tmp_df['OTT%'] = round((tmp_df['FTT'] - tmp_df['AvgCost'])*100/tmp_df['AvgCost'],2)
  tmp_df['RRR Ind'] = round(tmp_df['Current P/L']/tmp_df['FTT Amt'],2)
  tmp_df['Risk Ind'] = round(tmp_df['Current P/L%']*tmp_df['CurrAlloc%'],0)

  return tmp_df

# function to print portfolio features
def print_portfolio_stats(df_portfolio_features, myinvmt_df):
  from pyxirr import xirr

  total_booked_amt, reserve_amt, cy_booked_amt, py_booked_amt = get_amt()

  dates = myinvmt_df['Date'].values
  dates = np.append(dates, datetime.date.today().strftime('%d-%b-%y'))
  investment = myinvmt_df['Investment'].values
  dates= pd.to_datetime(dates)

  current = round(sum(df_portfolio_features['Close']*df_portfolio_features['Shares']),0) + reserve_amt
  investment_xirr = np.append(investment, current)
  cagr = round(xirr(pd.DataFrame({"dates": dates, "amounts": investment_xirr}))*100,2)

  investment = -sum(investment)
  invested = round(sum(df_portfolio_features['AvgCost']*df_portfolio_features['Shares']),0) + reserve_amt
  previous = round(sum(df_portfolio_features['Prev_Close']*df_portfolio_features['Shares']),0) + reserve_amt
  cy_invested = investment + py_booked_amt

  today_pnl_amount = current-previous
  today_pnl_percentage = round((current-previous)*100/previous,2)

  curr_pnl_amount = current-invested
  curr_pnl_percentage = round((curr_pnl_amount)*100/(cy_invested),2)

  cy_pnl_amount = cy_booked_amt + curr_pnl_amount
  cy_pnl_percentage = round((cy_pnl_amount)*100/cy_invested,2)

  overall_pnl_amount = total_booked_amt + curr_pnl_amount
  overall_pnl_percentage = round((overall_pnl_amount)*100/investment,2)

  estimate_st = round(sum(df_portfolio_features['FTT']*df_portfolio_features['Shares']),0)  + reserve_amt
  est_st_pnl_amount = estimate_st-current
  est_st_pnl_percentage = round((est_st_pnl_amount)*100/current,2)

  estimate_lt = round(sum(df_portfolio_features['LTT']*df_portfolio_features['Shares']),0)  + reserve_amt
  est_lt_pnl_amount = estimate_lt-current
  est_lt_pnl_percentage = round((est_lt_pnl_amount)*100/current,2)

  total_profit = round(sum(df_portfolio_features[df_portfolio_features['Current P/L%'] > 0]['Current']) - sum(df_portfolio_features[df_portfolio_features['Current P/L%'] > 0]['Investment']),0)
  total_loss = round(sum(df_portfolio_features[df_portfolio_features['Current P/L%'] < 0]['Current']) - sum(df_portfolio_features[df_portfolio_features['Current P/L%'] < 0]['Investment']),0)

  cy_booked_percentage = round((cy_booked_amt)*100/current,2)
  py_booked_percentage = round((py_booked_amt)*100/investment,2)
  total_booked_percentage = round((total_booked_amt)*100/investment,2)

  print('-------------------')
  print('Initial Investment: ', format_amt(investment))
  print('CY Investment: ', format_amt(cy_invested))
  print('Reserve: ', format_amt(reserve_amt))
  print('Current: ',  format_amt(current))
  print('-------------------')
  print('Today PnL: '+ '{} ({}%)'.format(format_amt(today_pnl_amount), today_pnl_percentage))
  print('Current PnL: '+ '{} ({}%)'.format(format_amt(curr_pnl_amount), curr_pnl_percentage))
  print('CY Booked + Current PnL: '+ '{} ({}%)'.format(format_amt(cy_pnl_amount), cy_pnl_percentage))
  print('-------------------')
  print('Total profit: ', format_amt(total_profit))
  print('Total loss: ', format_amt(total_loss))
  print('-------------------')
  print('Total Booked + Current PnL: '+ '{} ({}%)'.format(format_amt(overall_pnl_amount), overall_pnl_percentage))
  print('Total Booked PnL: '+ '{} ({}%)'.format(format_amt(total_booked_amt), total_booked_percentage))
  print('Curr Year Booked PnL: '+ '{} ({}%)'.format(format_amt(cy_booked_amt), cy_booked_percentage))
  print('Prev Year Booked PnL: '+ '{} ({}%)'.format(format_amt(py_booked_amt), py_booked_percentage))
  print('===================')
  print('Est FTT: ',  format_amt(estimate_st))
  print('Est FTT PnL: '+ '{} ({}%)'.format(format_amt(est_st_pnl_amount), est_st_pnl_percentage))

  print('===================')
  print('Deployed: ', format_amt(investment))

  print('Current: ', format_amt(current))

  print('CAGR/XIRR %: '+'{}%'.format(cagr))

In [8]:
# get start and end date
start_date, end_date = get_start_end_date()

# get portfolio and prospects data
mypfs_df = get_mypfs_df()
mypps_df = get_mypps_df()
myinvmt_df = get_myinvmt_df()

# merge above datasets
mypf_df = pd.merge(mypfs_df, mypps_df, on="Symbol")

# seggregate dm and sv portfolio
dm_pf = mypf_df[mypf_df['InPortfolio'] == 'DM']
sv_pf = mypf_df[mypf_df['InPortfolio'] == 'SV']

# build portfolio stock dataframe
dm_stocks = get_stock_ids(dm_pf)
sv_stocks = get_stock_ids(sv_pf)
df_stocks = pd.concat([dm_pf,sv_pf], ignore_index = True)

# arrange common and diff stock features
common_cols = ['Symbol', 'Target', 'Criteria', 'Strategy', 'CumlRnk', 'LatestQtr', 'StarStock', 'Conviction', 'Category', 'InFolio', 'XIRR', 'MBQ']
diff_cols = ['Symbol', 'AvgCost', 'Shares']
df_stocks = arrange_features(df_stocks, common_cols, diff_cols)

# get common features
stock_ids = df_stocks['Symbol'].values
df_common_features = get_common_features(stock_ids, df_stocks)

df_common_features.reset_index(drop=True, inplace=True)
df_common_features.drop(['Date'], axis=1, inplace=True)
# get and print portfolio features
df_portfolio_features = get_portfolio_features(df_common_features)

print_portfolio_stats(df_portfolio_features, myinvmt_df)

df = df_portfolio_features
#plot_pie_chart(df, 'CapType', 'Current')
list_ox40n = list(df[df['MBQ'].str.contains('OX40N', na=False)]['Symbol'].values)

Run date time (IST): 2026-03-04 14:09:02
-------------------
qualified stocks: 86
with latest results: 26
still star stocks: 15
-------------------
Initial Investment:  1.33 C
CY Investment:  1.60 C
Reserve:  2.44 L
Current:  1.34 C
-------------------
Today PnL: -2.69 L (-1.96%)
Current PnL: -40.23 L (-25.15%)
CY Booked + Current PnL: -24.55 L (-15.35%)
-------------------
Total profit:  80.78 K
Total loss:  -41.04 L
-------------------
Total Booked + Current PnL: 2.43 L (1.82%)
Total Booked PnL: 42.66 L (32.07%)
Curr Year Booked PnL: 15.68 L (11.68%)
Prev Year Booked PnL: 26.98 L (20.29%)
===================
Est FTT:  2.41 C
Est FTT PnL: 1.07 C (79.62%)
===================
Deployed:  1.33 C
Current:  1.34 C
CAGR/XIRR %: 0.45%

In [9]:
# top 5 near their targets
cols = ['Symbol', 'Today P/L%', 'Current P/L%', 'FTT%', 'OTT%', 'FTT Amt', 'Current P/L', 'Current', 'FTT', 'Dev%_PE', 'RSI_14','Conviction', 'Spread%',  'CumlRnk', 'RRR Ind', 'CurrAlloc%', 'Gained%', 'Criteria', 'Strategy', 'Category']
df_tmp = df_portfolio_features[~df_portfolio_features['Symbol'].isin(['ENRIN','BLUSPRING','DIGITIDE'])]
df_tmp = df_tmp.sort_values(by = 'FTT Amt', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
19,COALINDIA,1.96,6.87,10.10,17.67,16241.0,10342.0,160802.0,478.51,29.12,58.0,L-LC,11.00,185.0,0.64,1.22,27.84,XY25,ATH,MINING
50,MASFIN,-3.66,-6.98,30.69,21.57,27971.0,-6840.0,91140.0,397.04,-19.60,36.0,H-SC,6.47,167.0,-0.24,0.69,31.99,XR,ATH,FINANCE
77,TTKPRESTIG,-2.64,-36.58,57.82,0.09,36956.0,-36862.0,63915.0,770.00,48.35,22.0,M-SC,12.50,250.0,-1.00,0.49,0.00,OX40N,NTT,DURABLES
37,ICICIGI,-0.32,0.41,18.86,19.34,37894.0,814.0,200923.0,2252.93,-15.42,47.0,X-MC,1.20,66.0,0.02,1.52,16.41,X40,ATH,INSURANCE
51,MEDANTA,-1.76,-7.31,33.86,24.08,39843.0,-9279.0,117671.0,1486.00,-7.89,44.0,X-SC,8.03,87.0,-0.23,0.89,7.78,XY24,NTT,HEALTHCARE

In [10]:
# top 5 today
df_tmp = df_portfolio_features.sort_values(by = 'Today P/L%', ascending=False)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
2,ABBOTINDIA,2.72,-7.63,27.82,18.07,45961.0,-13645.0,165210.0,35195.00,-21.38,59.0,X-MC,11.35,58.0,-0.30,1.25,4.74,X40,ATH,PHARMA
69,SURYODAY,2.51,-26.93,68.38,23.03,89472.0,-48225.0,130846.0,216.00,42.54,49.0,H-SC,6.07,166.0,-0.54,0.99,29.82,XR,NTT,BANKS
19,COALINDIA,1.96,6.87,10.10,17.67,16241.0,10342.0,160802.0,478.51,29.12,58.0,L-LC,11.00,185.0,0.64,1.22,27.84,XY25,ATH,MINING
11,BANDHANBNK,0.14,-14.42,124.85,92.42,297625.0,-40173.0,238386.0,400.00,104.74,64.0,H-SC,8.95,174.0,-0.13,1.81,31.32,XY24,NTT,BANKS
48,KANSAINER,0.02,-34.47,73.16,13.47,129285.0,-92952.0,176715.0,340.00,-43.73,31.0,H-SC,14.10,162.0,-0.72,1.34,0.02,XY24,NTT,PAINTS

In [11]:
# bottom 5 today
df_tmp = df_portfolio_features.sort_values(by = 'Today P/L%', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
27,FINCABLES,-5.84,12.87,84.21,107.91,140332.0,19001.0,166645.0,1641.55,1.47,63.0,M-SC,6.42,220.0,0.14,1.26,25.37,OX40N,ATH,CABLES
75,TMPV,-5.25,-21.97,70.87,33.33,180175.0,-71567.0,254233.0,600.00,-83.62,37.0,X-LC,3.57,4.0,-0.40,1.93,3.94,XY24,NTT,AUTO
7,ATULAUTO,-5.07,-21.82,86.19,45.57,132838.0,-43010.0,154122.0,844.00,3332.43,45.0,M-SC,7.19,248.0,-0.32,1.17,16.63,XY24,NTT,AUTO
55,RAJESHEXPO,-5.00,-74.56,293.35,0.07,102373.0,-102279.0,34898.0,518.00,1179.04,24.0,L-SC,11.12,268.0,-1.00,0.26,0.00,OX40N,NTT,JEWELLERY
65,SIEMENS,-5.00,-14.71,47.16,25.51,74852.0,-27375.0,158720.0,4671.50,33.36,48.0,H-LC,3.71,51.0,-0.37,1.20,16.88,AR,ATH,ELECTRICAL

In [12]:
# top 5 to exit based on CumlRnk
df_tmp = df_portfolio_features[~df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])]
df_tmp = df_tmp[(df_tmp['Current P/L%'] > -1) & (df_tmp['Current P/L%'] < 1)].sort_values(by = 'CumlRnk', ascending=False)
df_tmp[cols].head()

Empty DataFrame
Columns: [Symbol, Today P/L%, Current P/L%, FTT%, OTT%, FTT Amt, Current P/L, Current, FTT, Dev%_PE, RSI_14, Conviction, Spread%, CumlRnk, RRR Ind, CurrAlloc%, Gained%, Criteria, Strategy, Category]
Index: []

In [13]:
# OX40N stocks to exit
df_tmp = df_portfolio_features[(df_portfolio_features['Symbol'].isin(list_ox40n))].sort_values(by = 'Current P/L%', ascending=False)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
27,FINCABLES,-5.84,12.87,84.21,107.91,140332.0,19001.0,166645.0,1641.55,1.47,63.0,M-SC,6.42,220.0,0.14,1.26,25.37,OX40N,ATH,CABLES
66,SIS,-2.67,-31.88,78.02,21.26,59009.0,-35399.0,75633.0,528.00,1774.09,36.0,H-SC,6.49,168.0,-0.60,0.57,4.27,OX40N,NTT,MISC
48,KANSAINER,0.02,-34.47,73.16,13.47,129285.0,-92952.0,176715.0,340.00,-43.73,31.0,H-SC,14.10,162.0,-0.72,1.34,0.02,XY24,NTT,PAINTS
41,INDIGOPNTS,-1.01,-35.43,54.90,0.02,61881.0,-61843.0,112716.0,1408.00,71.88,22.0,M-SC,13.16,222.0,-1.00,0.86,0.00,OX40N,NTT,PAINTS
77,TTKPRESTIG,-2.64,-36.58,57.82,0.09,36956.0,-36862.0,63915.0,770.00,48.35,22.0,M-SC,12.50,250.0,-1.00,0.49,0.00,OX40N,NTT,DURABLES

In [14]:
# top 5 to book for rotation
df_tmp = df_portfolio_features[(df_portfolio_features['Current P/L%'] > 20) ].sort_values(by = 'CumlRnk', ascending=False)
df_tmp[cols].head()

Empty DataFrame
Columns: [Symbol, Today P/L%, Current P/L%, FTT%, OTT%, FTT Amt, Current P/L, Current, FTT, Dev%_PE, RSI_14, Conviction, Spread%, CumlRnk, RRR Ind, CurrAlloc%, Gained%, Criteria, Strategy, Category]
Index: []

In [15]:
# top 5 to monitor for exit
df_tmp = df_portfolio_features[~df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])]
df_tmp = df_tmp[(df_tmp['Current P/L%'] > 0) ].sort_values(by = 'Dev%_PE', ascending=False)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
19,COALINDIA,1.96,6.87,10.10,17.67,16241.0,10342.0,160802.0,478.51,29.12,58.0,L-LC,11.00,185.0,0.64,1.22,27.84,XY25,ATH,MINING
27,FINCABLES,-5.84,12.87,84.21,107.91,140332.0,19001.0,166645.0,1641.55,1.47,63.0,M-SC,6.42,220.0,0.14,1.26,25.37,OX40N,ATH,CABLES
1,ABB,-2.87,6.63,36.52,45.57,101873.0,17333.0,278952.0,7934.00,-31.49,53.0,H-MC,8.85,125.0,0.17,2.12,23.87,AR,NTT,ELECTRICAL

In [16]:
# top 5 to book for rotation from weak conviction
df_tmp = df_portfolio_features[~df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])]
df_tmp = df_tmp[~df_tmp['Criteria'].isin(['XY25','XY24','X40', 'X40N'])].sort_values(by = 'RRR Ind', ascending=False)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
1,ABB,-2.87,6.63,36.52,45.57,101873.0,17333.0,278952.0,7934.00,-31.49,53.0,H-MC,8.85,125.0,0.17,2.12,23.87,AR,NTT,ELECTRICAL
27,FINCABLES,-5.84,12.87,84.21,107.91,140332.0,19001.0,166645.0,1641.55,1.47,63.0,M-SC,6.42,220.0,0.14,1.26,25.37,OX40N,ATH,CABLES
40,INDIAMART,-1.84,-10.83,131.84,106.72,144991.0,-13361.0,109975.0,4810.62,-59.77,33.0,H-SC,8.27,140.0,-0.09,0.83,10.01,AR,ATH,MISC
85,ZYDUSLIFE,-1.47,-5.77,43.94,35.63,86771.0,-12099.0,197475.0,1286.17,-18.02,46.0,H-MC,4.96,120.0,-0.14,1.50,9.94,AR,ATH,PHARMA
84,WIPRO,-1.63,-19.88,115.01,72.27,156139.0,-33687.0,135761.0,420.00,-27.84,20.0,M-LC,11.41,98.0,-0.22,1.03,0.00,XR,NTT,IT

In [17]:
# top 5 to accumulate based on lowest RSI_14
df_tmp = df_portfolio_features[df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])].sort_values(by = 'RSI_14', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
8,AWL,-0.35,-41.77,169.95,57.19,322737.0,-136226.0,189901.0,485.00,-66.76,13.0,X-SC,19.86,81.0,-0.42,1.44,0.00,XY24,NTT,FMCG
12,BATAINDIA,-4.65,-52.67,185.68,35.20,113074.0,-67773.0,60897.0,2096.00,-20.14,19.0,X-SC,23.02,91.0,-0.60,0.46,0.00,X40,NTT,FOOTWEAR
53,PGHH,-0.90,-16.68,58.44,32.01,103967.0,-35616.0,177904.0,17616.87,-43.64,21.0,X-MC,9.82,57.0,-0.34,1.35,0.00,X40,ATH,FMCG
9,BAJAJHFL,-1.97,-28.39,117.11,55.47,204031.0,-69064.0,174222.0,181.50,-38.66,22.0,X-MC,17.76,60.0,-0.34,1.32,0.00,X40N,ATH,FINANCE
43,INFY,-0.86,-12.26,53.00,34.24,145504.0,-38352.0,274536.0,1972.00,-31.06,23.0,X-LC,9.38,3.0,-0.26,2.08,1.05,X40,NTT,IT

In [18]:
# top 5 to accumulate based on Spread and CumlRnk
df_tmp = df_portfolio_features[df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])]
df_tmp = df_tmp[(df_tmp['CumlRnk'] < 100)].sort_values(by = 'Spread%', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
37,ICICIGI,-0.32,0.41,18.86,19.34,37894.0,814.0,200923.0,2252.93,-15.42,47.0,X-MC,1.20,66.0,0.02,1.52,16.41,X40,ATH,INSURANCE
78,UNITDSPR,-3.27,-2.89,24.37,20.77,55409.0,-6777.0,227367.0,1644.00,-13.87,36.0,X-MC,1.36,64.0,-0.12,1.73,4.01,X40N,NTT,BREWERIES
22,DABUR,-3.20,-3.94,49.59,43.70,118175.0,-9763.0,238305.0,735.00,-12.82,37.0,X-MC,1.47,70.0,-0.08,1.81,10.52,XY24,BTT,FMCG
59,RELIANCE,-1.21,-13.88,45.50,25.30,78745.0,-27897.0,173066.0,1952.00,-16.19,31.0,X-LC,2.19,21.0,-0.35,1.31,15.93,XY25,BTT,REFINERIES
35,HINDUNILVR,-2.00,-11.54,28.49,13.67,64789.0,-29653.0,227410.0,2922.00,-34.38,39.0,X-LC,2.52,9.0,-0.46,1.73,7.36,XY25,NTT,FMCG

In [19]:
# top 5 to accumulate based on lowest Gained%
df_tmp = df_portfolio_features[df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])].sort_values(by = 'Gained%', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
3,ACC,-2.28,-36.21,157.35,64.15,238826.0,-86171.0,151780.0,3906.00,-51.63,23.0,X-SC,9.95,85.0,-0.36,1.15,0.0,XY24,BTT,CEMENT
12,BATAINDIA,-4.65,-52.67,185.68,35.20,113074.0,-67773.0,60897.0,2096.00,-20.14,19.0,X-SC,23.02,91.0,-0.60,0.46,0.0,X40,NTT,FOOTWEAR
9,BAJAJHFL,-1.97,-28.39,117.11,55.47,204031.0,-69064.0,174222.0,181.50,-38.66,22.0,X-MC,17.76,60.0,-0.34,1.32,0.0,X40N,ATH,FINANCE
8,AWL,-0.35,-41.77,169.95,57.19,322737.0,-136226.0,189901.0,485.00,-66.76,13.0,X-SC,19.86,81.0,-0.42,1.44,0.0,XY24,NTT,FMCG
24,DIXON,-0.50,-29.97,87.44,31.26,141303.0,-69168.0,161600.0,18931.72,-68.70,35.0,X-MC,24.16,54.0,-0.49,1.23,0.0,X40N,ATH,IT

In [20]:
# top 5 to accumulate based on lowest CurrAlloc%
df_tmp = df_portfolio_features[df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])].sort_values(by = 'CurrAlloc%', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
54,QUESS,-1.46,-36.33,124.34,42.84,51466.0,-23615.0,41391.0,424.00,-58.13,33.0,X-SC,16.96,80.0,-0.46,0.31,0.00,XY24,NTT,MISC
12,BATAINDIA,-4.65,-52.67,185.68,35.20,113074.0,-67773.0,60897.0,2096.00,-20.14,19.0,X-SC,23.02,91.0,-0.60,0.46,0.00,X40,NTT,FOOTWEAR
58,RELAXO,-1.30,-57.81,261.01,52.31,159845.0,-83919.0,61241.0,1176.00,-55.09,25.0,X-SC,15.88,92.0,-0.53,0.46,0.00,X40N,NTT,FOOTWEAR
51,MEDANTA,-1.76,-7.31,33.86,24.08,39843.0,-9279.0,117671.0,1486.00,-7.89,44.0,X-SC,8.03,87.0,-0.23,0.89,7.78,XY24,NTT,HEALTHCARE
36,HONAUT,-1.09,-26.35,94.59,43.32,113470.0,-42912.0,119960.0,58357.33,-35.33,31.0,X-SC,12.56,90.0,-0.38,0.91,0.00,X40N,ATH,ELECTRICAL

In [21]:
# top 5 to accumulate based on CumlRnk
df_tmp = df_portfolio_features.sort_values(by = 'CumlRnk', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
45,ITC,-0.83,-17.74,44.73,19.06,125164.0,-60345.0,279821.0,452.00,-54.71,38.0,X-LC,16.88,1.0,-0.48,2.12,1.32,X40,NTT,FMCG
73,TCS,-1.06,-25.89,66.74,23.58,213994.0,-111990.0,320639.0,4311.59,-35.76,28.0,X-LC,10.81,2.0,-0.52,2.43,0.47,X40,ATH,IT
43,INFY,-0.86,-12.26,53.00,34.24,145504.0,-38352.0,274536.0,1972.00,-31.06,23.0,X-LC,9.38,3.0,-0.26,2.08,1.05,X40,NTT,IT
75,TMPV,-5.25,-21.97,70.87,33.33,180175.0,-71567.0,254233.0,600.00,-83.62,37.0,X-LC,3.57,4.0,-0.40,1.93,3.94,XY24,NTT,AUTO
34,HCLTECH,-0.10,-11.12,39.32,23.83,84549.0,-26897.0,215027.0,1908.19,-6.53,28.0,X-LC,7.41,8.0,-0.32,1.63,3.17,X40,ATH,IT

In [22]:
# top 5 for average up
df_tmp = df_portfolio_features[(df_portfolio_features['Dev%_200'] > 5)].sort_values(by = 'CurrAlloc%', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
42,INDUSINDBK,-1.69,-31.60,94.27,32.89,49787.0,-24394.0,52813.0,1800.00,-348.60,50.0,L-MC,12.18,258.0,-0.49,0.40,45.44,XR,NTT,BANKS
67,SONACOMS,-2.90,-13.11,60.08,39.09,52807.0,-13265.0,87894.0,804.02,-31.14,43.0,M-MC,10.95,193.0,-0.25,0.67,24.34,AR,ATH,AUTO
19,COALINDIA,1.96,6.87,10.10,17.67,16241.0,10342.0,160802.0,478.51,29.12,58.0,L-LC,11.00,185.0,0.64,1.22,27.84,XY25,ATH,MINING
27,FINCABLES,-5.84,12.87,84.21,107.91,140332.0,19001.0,166645.0,1641.55,1.47,63.0,M-SC,6.42,220.0,0.14,1.26,25.37,OX40N,ATH,CABLES
82,VOLTAS,-3.48,13.19,28.27,45.20,61356.0,25293.0,217035.0,1856.00,29.54,45.0,X-MC,9.84,79.0,0.41,1.65,20.89,XY25,NTT,AC

In [23]:
# top 5 RSP
df_tmp = df_portfolio_features.sort_values(by = 'RSP', ascending=False)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
27,FINCABLES,-5.84,12.87,84.21,107.91,140332.0,19001.0,166645.0,1641.55,1.47,63.0,M-SC,6.42,220.0,0.14,1.26,25.37,OX40N,ATH,CABLES
26,EASEMYTRIP,-3.13,-57.28,241.09,45.70,182088.0,-101288.0,75527.0,26.40,-21.71,48.0,M-SC,18.06,204.0,-0.56,0.57,24.44,XY24,NTT,TRAVEL
83,WHIRLPOOL,-1.56,-27.87,152.21,81.92,126037.0,-31993.0,82805.0,2270.00,-57.77,52.0,M-SC,25.85,210.0,-0.25,0.63,16.32,XR,NTT,DURABLES
11,BANDHANBNK,0.14,-14.42,124.85,92.42,297625.0,-40173.0,238386.0,400.00,104.74,64.0,H-SC,8.95,174.0,-0.13,1.81,31.32,XY24,NTT,BANKS
7,ATULAUTO,-5.07,-21.82,86.19,45.57,132838.0,-43010.0,154122.0,844.00,3332.43,45.0,M-SC,7.19,248.0,-0.32,1.17,16.63,XY24,NTT,AUTO

In [24]:
# Top N allocation
df_tmp = df_portfolio_features.sort_values(by = 'CurrAlloc%', ascending=False)
top_n_values = [10, 25, 50]

sum_df = pd.DataFrame({
    'Top_N': top_n_values,
    'Sum_Alloc%': [df_tmp['CurrAlloc%'].head(n).sum() for n in top_n_values]
})

sum_df

   Top_N  Sum_Alloc%
0     10       20.66
1     25       45.58
2     50       77.54

In [25]:
# market-cap-wise allocation
df_tmp = df_portfolio_features[cols]
df_tmp.groupby(df_tmp['Conviction'].str[-2:])['CurrAlloc%'].sum().sort_values(ascending=False)

Conviction
SC    44.73
MC    30.28
LC    24.92
Name: CurrAlloc%, dtype: float64

In [26]:
# criteria-wise allocation
df_portfolio_features.groupby('Criteria')['CurrAlloc%'].sum().sort_values(ascending=False)

Criteria
XY24     26.72
X40      24.14
X40N     14.52
AR        9.10
XY25      8.94
XR        8.50
OX40N     7.19
SR        0.82
Name: CurrAlloc%, dtype: float64

In [27]:
# conviction-wise allocation
df_portfolio_features.groupby('Conviction')['CurrAlloc%'].sum().sort_values(ascending=False)

Conviction
X-MC    22.87
H-SC    22.25
X-LC    21.47
X-SC    11.12
M-SC    10.69
H-MC     4.98
M-MC     2.03
L-LC     1.22
H-LC     1.20
M-LC     1.03
L-SC     0.67
L-MC     0.40
Name: CurrAlloc%, dtype: float64

In [28]:
# sector-wise stats
df_tmp = df_portfolio_features.groupby('Category')[['CurrAlloc%', 'Current', 'Current P/L', 'FTT Amt']].sum().sort_values(by=['Current', 'Current P/L'], ascending=False)
df_tmp['Current P/L%'] = round(df_tmp['Current P/L'] * 100 / df_tmp['Current'], 2)
df_tmp['FTT%'] = round(df_tmp['FTT Amt'] * 100 / df_tmp['Current'], 2)
cols = ['CurrAlloc%', 'Current P/L%', 'FTT%']
df_tmp[cols].sort_values(by=['CurrAlloc%'], ascending=False)

               CurrAlloc%  Current P/L%    FTT%
Category
FMCG                15.72        -19.09   59.37
FINANCE             12.80        -23.70   72.37
IT                  11.56        -43.81  115.88
MISC                 6.74        -45.95  105.65
ELECTRICAL           6.34        -12.26   53.22
PAINTS               5.06        -38.50   59.07
INSURANCE            4.96         -3.74   39.24
PHARMA               4.26         -4.57   37.48
AUTO                 3.77        -25.76   73.72
BANKS                3.20        -26.73  103.52
AC                   2.22         -9.34   38.99
FOOTWEAR             1.97        -69.20  137.04
TRAVEL               1.93        -75.29  163.07
DURABLES             1.88        -56.52   94.61
BREWERIES            1.73         -2.98   24.37
HEALTHCARE           1.66        -40.88   75.64
REALTY               1.41        -19.29   38.88
APPARELS             1.41        -27.86   66.40
CERAMICS             1.41        -65.77  116.13
REFINERIES           1.31        -16.12   45.50
CABLES               1.26         11.40   84.21
MINING               1.22          6.43   10.10
JEWELLERY            1.18       -105.57  176.99
CEMENT               1.15        -56.77  157.35
ENGINEERING          1.11        -65.29  140.90
CHEMICALS            1.03        -94.68  253.50
ENTERTAINMENT        0.79        -86.32  197.44
TEXTILES             0.44        -58.06  103.13
HOTELS               0.41       -108.46  181.99

In [29]:
# money to be made criteria-wise
df_portfolio_features.groupby('Criteria')['FTT Amt'].agg(['sum', 'count']).sort_values(by='sum', ascending=False)

                sum  count
Criteria
XY24      3603940.0     21
X40       1537718.0     15
AR        1372563.0     10
XR        1369849.0     12
X40N      1205565.0     10
OX40N      844515.0     10
XY25       439825.0      6
SR         310792.0      2

In [30]:
# money to be made conviction-wise
df_portfolio_features.groupby('Conviction')['FTT Amt'].agg(['sum', 'count']).sort_values(by='sum', ascending=False)

                  sum  count
Conviction
H-SC        3858433.0     24
M-SC        1509925.0     14
X-MC        1500019.0     15
X-LC        1441532.0     12
X-SC        1334989.0     10
H-MC         422686.0      3
L-SC         201503.0      2
M-LC         156139.0      1
M-MC         118661.0      2
H-LC          74852.0      1
L-MC          49787.0      1
L-LC          16241.0      1

In [31]:
# money to be made criteria and conviction-wise
df_portfolio_features.groupby(['Conviction', 'Criteria'])['FTT Amt'].agg(['sum', 'count']).sort_values(by='sum', ascending=False)

                           sum  count
Conviction Criteria
H-SC       XY24      1310148.0      6
           AR         979286.0      5
M-SC       XY24       884223.0      6
H-SC       XR         878563.0      7
X-LC       X40        738909.0      6
X-SC       XY24       652872.0      4
X-MC       X40        596223.0      7
X-SC       X40N       479531.0      4
X-MC       X40N       473028.0      4
H-SC       OX40N      379644.0      4
M-SC       OX40N      362498.0      5
H-SC       SR         310792.0      2
X-LC       XY24       306083.0      2
           X40N       253006.0      2
H-MC       XY24       234042.0      1
X-MC       XY24       216572.0      2
           XY25       214196.0      2
X-SC       X40        202586.0      2
H-MC       AR         188644.0      2
M-SC       XR         186230.0      2
M-LC       XR         156139.0      1
X-LC       XY25       143534.0      2
L-SC       OX40N      102373.0      1
           XR          99130.0      1
M-SC       AR          76974.0      1
H-LC       AR          74852.0      1
M-MC       XY25        65854.0      1
           AR          52807.0      1
L-MC       XR          49787.0      1
L-LC       XY25        16241.0      1

In [32]:
# notebook execution time

end_time = time.time()
execution_time = round(end_time - start_time, 0)
print(f"Notebook execution time: {execution_time} seconds")

Notebook execution time: 35.0 seconds