<a href="https://colab.research.google.com/github/ankit-rathi/Quantvesting_v2/blob/main/myStocks_Portfolio_Analysis.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
'''
!pip install pandas==2.2.2 -qq
!pip install pyxirr -qq
!pip install ta -qq
!pip install yfinance==0.2.59 -qq
'''

'\n!pip install pandas==2.2.2 -qq\n!pip install pyxirr -qq\n!pip install ta -qq\n!pip install yfinance==0.2.59 -qq\n'

In [2]:
# import libraries

import numpy as np
import pandas as pd
import datetime
import warnings
warnings.filterwarnings('ignore')
import yfinance as yfin
import ta
import matplotlib.pyplot as plt
import requests

In [3]:
# notebook start time
import time
import datetime
import pytz

start_time = time.time()

# function to print date timestamp
def print_date_time():
  tz_NY = pytz.timezone('Asia/Kolkata')
  datetime_NY = datetime.datetime.now(tz_NY)
  print("Run date time (IST):", datetime_NY.strftime("%Y-%m-%d %H:%M:%S"))

In [4]:
# function to get booked and reserved amount
def get_amt():
  # fetch the JSON data from the URL
  url = "https://raw.githubusercontent.com/ankit-rathi/Tradevesting_v1/main/data/myPortfolioAmts.json"
  response = requests.get(url)
  pf_amts = response.json()  # parse the JSON data

  # extract values from the JSON
  py_booked_amt_dm = pf_amts["py_booked_amt_dm"]
  py_booked_amt_sv = pf_amts["py_booked_amt_sv"]
  cy_booked_amt_dm = pf_amts["cy_booked_amt_dm"]
  cy_booked_amt_sv = pf_amts["cy_booked_amt_sv"]
  reserve_amt_dm = pf_amts["reserve_amt_dm"]
  reserve_amt_sv = pf_amts["reserve_amt_sv"]

  # perform calculations
  py_booked_amt = py_booked_amt_dm + py_booked_amt_sv
  cy_booked_amt = cy_booked_amt_dm + cy_booked_amt_sv
  reserve_amt = reserve_amt_dm + reserve_amt_sv
  total_booked_amt = py_booked_amt + cy_booked_amt

  return total_booked_amt, reserve_amt, cy_booked_amt, py_booked_amt

gen_output = 0

In [5]:
# function to format the amount
def format_amt(number):
    abs_number = abs(number)

    if abs_number >= 1_00_00_000:  # Crores
        formatted_amt = f"{number / 1_00_00_000:.2f} C"
    elif abs_number >= 1_00_000:  # Lakhs
        formatted_amt = f"{number / 1_00_000:.2f} L"
    elif abs_number >= 1_000:  # Thousands
        formatted_amt = f"{number / 1_000:.2f} K"
    else:
        formatted_amt = f"{number:.2f}"

    return formatted_amt

# function to set start and end date
def get_start_end_date():
  start_date = (datetime.date.today() + datetime.timedelta(days=-365)).strftime('%Y-%m-%d')
  end_date = (datetime.date.today() + datetime.timedelta(days=1)).strftime('%Y-%m-%d')
  return start_date, end_date

# function to fetch my portfolio csv
def get_mypfs_df():
  mypfs_df = pd.read_csv('https://raw.githubusercontent.com/ankit-rathi/Tradevesting_v1/main/data/myPortfolioStocks.csv')
  return mypfs_df

# function to fetch my prospects csv
def get_mypps_df():
  mypps_df = pd.read_csv('https://raw.githubusercontent.com/ankit-rathi/Tradevesting_v1/main/data/myProspectsScrips.csv')
  return mypps_df

# function to fetch screener data
def get_myscreen_df():
  myscreen_df = pd.read_csv('https://raw.githubusercontent.com/ankit-rathi/Tradevesting_v1/main/data/myScreenerDB.csv')
  return myscreen_df

# function to fetch momentum data
def get_myinvmt_df():
  myinvmt_df = pd.read_csv('https://raw.githubusercontent.com/ankit-rathi/Tradevesting_v1/main/data/myInvestments.csv')
  return myinvmt_df

# function to get the stock ids
def get_stock_ids(df_pf):
  stock_n100 = df_pf['Symbol'].unique()

  exclude = ['CADILAHC','MMTC', 'MASFIN']

  stock_ids = df_pf[~df_pf['Symbol'].isin(exclude) ]['Symbol'].unique()

  #mypf = mypf[mypf.Forecast.notnull()]
  #stock_ids = mypf['Symbol'].unique()

  #stock_ids.sort()
  return stock_ids

# get features from screener data
def get_screener_features():
  myscreen_df = get_myscreen_df()
  cols = ['Symbol', 'EPS', 'MedPE', 'ROCE%', 'ROE%', 'CapType']
  return myscreen_df[cols]

# get relative strength
def get_relative_strength(stock_list):

    # Dictionary to store stock tickers and their corresponding percentage price change
    stock_changes = {}

    # Loop through each stock and fetch its price data
    for stock in stock_list:
        try:
            # Download the stock data for the given date range
            stock_data = yfin.Ticker(stock + '.NS').history(period='1mo', interval='1d')[map(str.title, ['open', 'close', 'low', 'high', 'volume'])]

            # Calculate the percentage change for the stock
            if len(stock_data) > 0:
                start_price = stock_data['Close'].iloc[0]
                end_price = stock_data['Close'].iloc[-1]
                percent_change = round(((end_price - start_price) / start_price) * 100, 2)
                stock_changes[stock] = percent_change
            else:
                stock_changes[stock] = np.nan  # If no data is available, set to NaN

        except Exception as e:
            print(f"Error fetching data for {stock}: {e}")
            stock_changes[stock] = np.nan

    # Create a DataFrame with stock tickers and their percentage changes
    df = pd.DataFrame(list(stock_changes.items()), columns=['Symbol', 'Percent_Change'])

    # Drop any stocks with missing data (NaN values)
    df = df.dropna()

    # Calculate the percentile rank based on percentage change
    df['RSP'] = round(df['Percent_Change'].rank(pct=True) * 100, 2)
    cols = ['Symbol', 'RSP']
    df = df[cols]
    # Sort by percentile rank (optional)
    df = df.sort_values(by='RSP', ascending=False).reset_index(drop=True)

    return df

In [6]:
# function to get stock technicals
def stock_prec_dev(stock_symbol):
    #stock_symbol = 'ULTRACEMCO.NS'
    short_window = 20
    mid_window = 50
    long_window = 200
    moving_avg = 'SMA'

    start = datetime.datetime(*map(int, start_date.split('-')))
    end = datetime.datetime(*map(int, end_date.split('-')))

    stock_df = yfin.Ticker(stock_symbol + '.NS').history(period='max', interval='1d')[map(str.title, ['open', 'close', 'low', 'high', 'volume'])]

    stock_df['Max'] = round(max(stock_df['Close']),2)
    stock_df = stock_df[(stock_df.index <= end_date) & (stock_df.index >= start_date)]
    stock_df['200_SMA'] = round(stock_df['Close'].rolling(window = 200, min_periods = 1).mean(),0)
    stock_df['Dev%_200'] = round((stock_df['Close'] - stock_df['200_SMA'])*100/stock_df['200_SMA'],2)
    stock_df.dropna(axis = 0, inplace = True) # remove any null rows

    stock_df['20_SMA'] = stock_df['Close'].rolling(window=20).mean()
    stock_df['50_SMA'] = stock_df['Close'].rolling(window=50).mean()
    stock_df['Symbol'] = stock_symbol

    stock_df['Close'] = round(stock_df['Close'],2)
    stock_df['Min'] = round(min(stock_df['Close']),2)
    stock_df['RSI_14'] = ta.momentum.RSIIndicator(close=stock_df['Close'], window=14).rsi()
    stock_df['RSI_14'] = round(stock_df['RSI_14'],0)
    stock_df['Prev_Close'] = stock_df['Close'].shift(1)
    stock_df.drop(['Open', 'Low', 'High', 'Volume'], axis=1, inplace=True)
    stock_df = stock_df.tail(1)

    max_SMA = max(stock_df['20_SMA'].item(), stock_df['50_SMA'].item(), stock_df['200_SMA'].item())
    min_SMA = min(stock_df['20_SMA'].item(), stock_df['50_SMA'].item(), stock_df['200_SMA'].item())
    ABS_Spread = max_SMA - min_SMA
    stock_df['Spread%'] = round((ABS_Spread / stock_df['200_SMA'].item()) * 100,2)

    return stock_df

# function to compute stock attributes
def get_common_features(stock_ids, df_mypf):

  df_prec_dev = pd.DataFrame()
  df_tmp = get_screener_features()
  df_rs = get_relative_strength(stock_ids)

  for stock_id in stock_ids:
      tmp = stock_prec_dev(stock_id)
      tmp = tmp.reset_index()
      df_prec_dev = pd.concat([df_prec_dev, tmp], ignore_index = True)
  df_prec_dev = pd.merge(df_prec_dev, df_mypf, on= 'Symbol')
  df_prec_dev = pd.merge(df_prec_dev, df_tmp, on= 'Symbol', how='left')
  df_prec_dev = pd.merge(df_prec_dev, df_rs, on= 'Symbol', how='left')
  #print(df_prec_dev.columns)
  df_prec_dev['Curr_PE'] = round(df_prec_dev['Close']/df_prec_dev['EPS'],1)
  df_prec_dev['Dev%_PE'] = round((df_prec_dev['Curr_PE'] - df_prec_dev['MedPE'])*100/df_prec_dev['MedPE'],2)
  df_prec_dev['Conviction'] = df_prec_dev['Conviction'] + '-' + df_prec_dev['CapType']
  return df_prec_dev

# function to arrange stock features
def arrange_features(df_stocks, common_cols, diff_cols):
  df_stocks_common = df_stocks[common_cols].drop_duplicates()
  df_stocks_diff = df_stocks[diff_cols]
  df_stocks_diff['Investment'] = df_stocks_diff['AvgCost'] * df_stocks_diff['Shares']
  df_stocks_diff = df_stocks_diff.groupby(['Symbol'])[['Shares', 'Investment']].aggregate(['sum']).reset_index()
  df_stocks_diff.columns = ['Symbol', 'Shares', 'Investment']
  df_stocks_diff['AvgCost'] = round(df_stocks_diff['Investment']/df_stocks_diff['Shares'],2)
  df_stocks = pd.merge(df_stocks_diff, df_stocks_common, on='Symbol')
  return df_stocks

# plot fact distribution across dimension
def plot_pie_chart(df, dimension, fact):
  # grouping the data by category and calculating the sum of fact for each type
  grouped_data = df.groupby(dimension)[fact].sum()

  # sorting the grouped data in descending order
  grouped_data = grouped_data.sort_values(ascending=False)

  # creating a pie chart
  grouped_data.plot.pie(autopct='%1.1f%%', startangle=90, figsize=(6, 6))

  # adding a title and displaying the plot
  plt.title(f'{dimension} {fact} Distribution')
  plt.ylabel('')  # To hide the y-label
  plt.show()

In [7]:
# function to get portfolio features

def get_portfolio_features(df_common_features):

  print_date_time()
  print('-------------------')

  #df_common_features["Target"] = df_common_features["Target"].fillna(df_common_features["Max"])
  df_common_features['NTT'] = np.where(df_common_features['Strategy']== 'NTT', df_common_features["Target"], df_common_features['Max'])
  df_common_features['LTT'] = np.where(df_common_features['Strategy']== 'BTT', df_common_features["Target"], df_common_features['Max'])
  df_common_features['BOL'] = df_common_features['Min']

  tmp_df = df_common_features[df_common_features['Symbol'].isin(mypf_df[mypf_df['InPortfolio'] != 'NA'].Symbol.values)]
  print('qualified stocks: '+str(len(tmp_df['Symbol'].unique())))
  tmp_df1 = tmp_df[tmp_df['LatestQtr'] == 1]
  print('with latest results: '+str(len(tmp_df1['Symbol'].unique())))
  tmp_df1 = tmp_df1[tmp_df1['StarStock'] == 1]
  print('still star stocks: '+str(len(tmp_df1['Symbol'].unique())))
  tmp_df['Investment'] = tmp_df['AvgCost'] * tmp_df['Shares']
  tmp_df['Current'] = round(tmp_df['Close'] * tmp_df['Shares'],0)
  tmp_df['Previous'] = tmp_df['Prev_Close'] * tmp_df['Shares']
  tmp_df['EstimatedST'] = tmp_df['NTT'] * tmp_df['Shares']
  tmp_df['EstimatedLT'] = tmp_df['LTT'] * tmp_df['Shares']
  tmp_df['Current P/L'] = round((tmp_df['Current'] - tmp_df['Investment']),0)
  tmp_df['Today P/L%'] = round((tmp_df['Current'] - tmp_df['Previous'])*100/tmp_df['Previous'],2)
  tmp_df['Current P/L%'] = round((tmp_df['Current'] - tmp_df['Investment'])*100/tmp_df['Investment'],2)
  tmp_df['EstimatedST P/L%'] = round((tmp_df['EstimatedST'] - tmp_df['Investment'])*100/tmp_df['Investment'],2)
  tmp_df['EstimatedLT P/L%'] = round((tmp_df['EstimatedLT'] - tmp_df['Investment'])*100/tmp_df['Investment'],2)
  tmp_df['NTT%'] = round((tmp_df['NTT'] - tmp_df['Close'])*100/tmp_df['Close'],2)
  tmp_df['LTT%'] = round((tmp_df['LTT'] - tmp_df['Close'])*100/tmp_df['Close'],2)
  tmp_df['Gained%'] = round((tmp_df['Close'] - tmp_df['BOL'])*100/tmp_df['BOL'],2)
  investment = round(sum(tmp_df['AvgCost']*tmp_df['Shares']),0)
  current = round(sum(tmp_df['Close']*tmp_df['Shares']),0)
  tmp_df['InitAlloc%'] = round(tmp_df['Investment']*100/investment,2)
  tmp_df['CurrAlloc%'] = round(tmp_df['Current']*100/current,2)
  tmp_df['FTT'] = tmp_df['LTT']
  tmp_df.loc[tmp_df['Strategy'] == 'NTT', 'FTT'] = tmp_df['NTT']
  tmp_df['FTT%'] = tmp_df['LTT%']
  tmp_df.loc[tmp_df['Strategy'] == 'NTT', 'FTT%'] = tmp_df['NTT%']
  tmp_df['FTT Amt'] = round(tmp_df['FTT%'] * tmp_df['Current']/100,0)
  tmp_df['OTT%'] = round((tmp_df['FTT'] - tmp_df['AvgCost'])*100/tmp_df['AvgCost'],2)
  tmp_df['RRR Ind'] = round(tmp_df['Current P/L']/tmp_df['FTT Amt'],2)
  tmp_df['Risk Ind'] = round(tmp_df['Current P/L%']*tmp_df['CurrAlloc%'],0)

  return tmp_df

# function to print portfolio features
def print_portfolio_stats(df_portfolio_features, myinvmt_df):
  from pyxirr import xirr

  total_booked_amt, reserve_amt, cy_booked_amt, py_booked_amt = get_amt()

  dates = myinvmt_df['Date'].values
  dates = np.append(dates, datetime.date.today().strftime('%d-%b-%y'))
  investment = myinvmt_df['Investment'].values
  dates= pd.to_datetime(dates)

  current = round(sum(df_portfolio_features['Close']*df_portfolio_features['Shares']),0) + reserve_amt
  investment_xirr = np.append(investment, current)
  cagr = round(xirr(pd.DataFrame({"dates": dates, "amounts": investment_xirr}))*100,2)

  investment = -sum(investment)
  invested = round(sum(df_portfolio_features['AvgCost']*df_portfolio_features['Shares']),0) + reserve_amt
  previous = round(sum(df_portfolio_features['Prev_Close']*df_portfolio_features['Shares']),0) + reserve_amt
  cy_invested = investment + py_booked_amt

  today_pnl_amount = current-previous
  today_pnl_percentage = round((current-previous)*100/previous,2)

  curr_pnl_amount = current-invested
  curr_pnl_percentage = round((curr_pnl_amount)*100/(cy_invested),2)

  cy_pnl_amount = cy_booked_amt + curr_pnl_amount
  cy_pnl_percentage = round((cy_pnl_amount)*100/cy_invested,2)

  overall_pnl_amount = total_booked_amt + curr_pnl_amount
  overall_pnl_percentage = round((overall_pnl_amount)*100/investment,2)

  estimate_st = round(sum(df_portfolio_features['FTT']*df_portfolio_features['Shares']),0)  + reserve_amt
  est_st_pnl_amount = estimate_st-current
  est_st_pnl_percentage = round((est_st_pnl_amount)*100/current,2)

  estimate_lt = round(sum(df_portfolio_features['LTT']*df_portfolio_features['Shares']),0)  + reserve_amt
  est_lt_pnl_amount = estimate_lt-current
  est_lt_pnl_percentage = round((est_lt_pnl_amount)*100/current,2)

  total_profit = round(sum(df_portfolio_features[df_portfolio_features['Current P/L%'] > 0]['Current']) - sum(df_portfolio_features[df_portfolio_features['Current P/L%'] > 0]['Investment']),0)
  total_loss = round(sum(df_portfolio_features[df_portfolio_features['Current P/L%'] < 0]['Current']) - sum(df_portfolio_features[df_portfolio_features['Current P/L%'] < 0]['Investment']),0)

  cy_booked_percentage = round((cy_booked_amt)*100/current,2)
  py_booked_percentage = round((py_booked_amt)*100/investment,2)
  total_booked_percentage = round((total_booked_amt)*100/investment,2)

  print('-------------------')
  print('Initial Investment: ', format_amt(investment))
  print('CY Investment: ', format_amt(cy_invested))
  print('Reserve: ', format_amt(reserve_amt))
  print('Current: ',  format_amt(current))
  print('-------------------')
  print('Today PnL: '+ '{} ({}%)'.format(format_amt(today_pnl_amount), today_pnl_percentage))
  print('Current PnL: '+ '{} ({}%)'.format(format_amt(curr_pnl_amount), curr_pnl_percentage))
  print('CY Booked + Current PnL: '+ '{} ({}%)'.format(format_amt(cy_pnl_amount), cy_pnl_percentage))
  print('-------------------')
  print('Total profit: ', format_amt(total_profit))
  print('Total loss: ', format_amt(total_loss))
  print('-------------------')
  print('Total Booked + Current PnL: '+ '{} ({}%)'.format(format_amt(overall_pnl_amount), overall_pnl_percentage))
  print('Total Booked PnL: '+ '{} ({}%)'.format(format_amt(total_booked_amt), total_booked_percentage))
  print('Curr Year Booked PnL: '+ '{} ({}%)'.format(format_amt(cy_booked_amt), cy_booked_percentage))
  print('Prev Year Booked PnL: '+ '{} ({}%)'.format(format_amt(py_booked_amt), py_booked_percentage))
  print('===================')
  print('Est FTT: ',  format_amt(estimate_st))
  print('Est FTT PnL: '+ '{} ({}%)'.format(format_amt(est_st_pnl_amount), est_st_pnl_percentage))

  print('===================')
  print('Deployed: ', format_amt(investment))

  print('Current: ', format_amt(current))

  print('CAGR/XIRR %: '+'{}%'.format(cagr))

In [8]:
# get start and end date
start_date, end_date = get_start_end_date()

# get portfolio and prospects data
mypfs_df = get_mypfs_df()
mypps_df = get_mypps_df()
myinvmt_df = get_myinvmt_df()

# merge above datasets
mypf_df = pd.merge(mypfs_df, mypps_df, on="Symbol")

# seggregate dm and sv portfolio
dm_pf = mypf_df[mypf_df['InPortfolio'] == 'DM']
sv_pf = mypf_df[mypf_df['InPortfolio'] == 'SV']

# build portfolio stock dataframe
dm_stocks = get_stock_ids(dm_pf)
sv_stocks = get_stock_ids(sv_pf)
df_stocks = pd.concat([dm_pf,sv_pf], ignore_index = True)

# arrange common and diff stock features
common_cols = ['Symbol', 'Target', 'Criteria', 'Strategy', 'CumlRnk', 'LatestQtr', 'StarStock', 'Conviction', 'Category', 'InFolio', 'XIRR', 'MBQ']
diff_cols = ['Symbol', 'AvgCost', 'Shares']
df_stocks = arrange_features(df_stocks, common_cols, diff_cols)

# get common features
stock_ids = df_stocks['Symbol'].values
df_common_features = get_common_features(stock_ids, df_stocks)

df_common_features.reset_index(drop=True, inplace=True)
df_common_features.drop(['Date'], axis=1, inplace=True)
# get and print portfolio features
df_portfolio_features = get_portfolio_features(df_common_features)

print_portfolio_stats(df_portfolio_features, myinvmt_df)

df = df_portfolio_features
#plot_pie_chart(df, 'CapType', 'Current')
list_ox40n = list(df[df['MBQ'].str.contains('OX40N', na=False)]['Symbol'].values)

Run date time (IST): 2026-08-14 09:37:32
-------------------
qualified stocks: 88
with latest results: 30
still star stocks: 19
-------------------
Initial Investment:  1.46 C
CY Investment:  1.89 C
Reserve:  2.21 L
Current:  1.60 C
-------------------
Today PnL: -76.39 K (-0.47%)
Current PnL: -32.35 L (-17.12%)
CY Booked + Current PnL: -27.70 L (-14.66%)
-------------------
Total profit:  3.79 L
Total loss:  -36.13 L
-------------------
Total Booked + Current PnL: 15.17 L (10.39%)
Total Booked PnL: 47.52 L (32.53%)
Curr Year Booked PnL: 4.65 L (2.9%)
Prev Year Booked PnL: 42.87 L (29.35%)
===================
Est FTT:  2.68 C
Est FTT PnL: 1.08 C (67.16%)
===================
Deployed:  1.46 C
Current:  1.60 C
CAGR/XIRR %: 4.22%

In [9]:
# top 5 near their targets
cols = ['Symbol', 'Today P/L%', 'Current P/L%', 'FTT%', 'OTT%', 'FTT Amt', 'Current P/L', 'Current', 'FTT', 'Dev%_PE', 'RSI_14','Conviction', 'Spread%',  'CumlRnk', 'RRR Ind', 'CurrAlloc%', 'Gained%', 'Criteria', 'Strategy', 'Category']
df_tmp = df_portfolio_features[~df_portfolio_features['Symbol'].isin(['ENRIN','BLUSPRING','DIGITIDE'])]
df_tmp = df_tmp.sort_values(by = 'FTT Amt', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
79,UNITDSPR,0.01,11.31,8.50,20.77,22152.0,26470.0,260614.0,1644.00,-1.23,63.0,X-MC,9.45,64.0,1.19,1.65,25.28,X40N,NTT,BREWERIES
78,TTKPRESTIG,-0.41,-22.20,28.65,0.09,22463.0,-22373.0,78404.0,770.00,82.07,42.0,M-SC,11.11,250.0,-1.00,0.50,41.12,OX40N,NTT,DURABLES
68,SIS,-0.27,0.50,20.66,21.26,23054.0,556.0,111588.0,528.00,2665.28,56.0,H-SC,22.30,168.0,0.02,0.71,65.91,OX40N,NTT,MISC
87,ZYDUSLIFE,-0.55,22.42,10.69,35.51,27426.0,46985.0,256559.0,1285.01,6.76,57.0,H-MC,15.98,120.0,1.71,1.62,35.02,AR,ATH,PHARMA
52,M&M,-0.94,7.24,10.80,18.82,27874.0,17415.0,258096.0,3762.88,-6.43,57.0,X-LC,4.65,25.0,0.62,1.63,17.08,X40N,ATH,AUTO

In [10]:
# top 5 today
df_tmp = df_portfolio_features.sort_values(by = 'Today P/L%', ascending=False)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
43,INDIGOPNTS,4.33,-16.84,20.27,0.02,29425.0,-29392.0,145167.0,1408.00,121.54,69.0,M-SC,6.15,222.0,-1.00,0.92,64.70,OX40N,NTT,PAINTS
10,BATAINDIA,4.32,-51.03,176.12,35.20,110964.0,-65665.0,63005.0,2096.00,-17.40,69.0,X-SC,12.49,91.0,-0.59,0.40,26.58,X40,NTT,FOOTWEAR
30,HAPPSTMNDS,2.09,-50.30,268.34,83.08,170943.0,-64461.0,63704.0,1466.54,-40.86,59.0,H-SC,9.71,152.0,-0.38,0.40,19.32,AR,ATH,IT
73,TATAELXSI,1.46,-45.72,143.24,32.03,102500.0,-60277.0,71558.0,9161.00,-32.12,54.0,H-SC,19.27,158.0,-0.59,0.45,11.18,OX40N,NTT,IT
84,VOLTAS,1.43,2.32,41.90,45.20,82208.0,4458.0,196200.0,1856.00,17.21,50.0,X-MC,3.69,79.0,0.05,1.24,7.53,XY25,NTT,AC

In [11]:
# bottom 5 today
df_tmp = df_portfolio_features.sort_values(by = 'Today P/L%', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
76,TMPV,-4.92,-20.92,80.51,42.75,264939.0,-87031.0,329076.0,600.00,-84.72,42.0,X-LC,4.50,4.0,-0.33,2.08,13.15,XY24,NTT,AUTO
46,IRCTC,-2.89,-39.90,154.46,52.93,251115.0,-107932.0,162576.0,1269.00,-55.54,44.0,H-MC,13.48,119.0,-0.43,1.03,2.62,XY24,BTT,TRAVEL
1,ABBOTINDIA,-2.86,-8.30,25.81,15.37,42331.0,-14845.0,164010.0,34390.26,-21.99,50.0,X-MC,4.93,58.0,-0.35,1.04,11.10,X40,ATH,PHARMA
61,RELAXO,-2.48,-47.33,189.19,52.31,144636.0,-68710.0,76450.0,1176.00,-43.96,51.0,X-SC,12.86,92.0,-0.48,0.48,70.93,X40N,NTT,FOOTWEAR
37,HONAUT,-2.27,-4.67,58.28,50.88,107133.0,-9013.0,183825.0,58192.80,-20.79,40.0,X-SC,13.21,90.0,-0.08,1.16,40.05,X40N,ATH,ELECTRICAL

In [12]:
# top 5 to exit based on CumlRnk
df_tmp = df_portfolio_features[~df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])]
df_tmp = df_tmp[(df_tmp['Current P/L%'] > -1) & (df_tmp['Current P/L%'] < 1)].sort_values(by = 'CumlRnk', ascending=False)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
80,UTIAMC,-0.77,0.28,50.73,51.15,113103.0,620.0,222950.0,1371.68,-19.39,48.0,M-SC,7.64,229.0,0.01,1.41,4.43,XY24,ATH,FINANCE
68,SIS,-0.27,0.50,20.66,21.26,23054.0,556.0,111588.0,528.00,2665.28,56.0,H-SC,22.30,168.0,0.02,0.71,65.91,OX40N,NTT,MISC

In [13]:
# OX40N stocks to exit
df_tmp = df_portfolio_features[(df_portfolio_features['Symbol'].isin(list_ox40n))].sort_values(by = 'Current P/L%', ascending=False)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
25,FINCABLES,0.92,59.69,30.19,107.91,71182.0,88135.0,235779.0,1641.55,43.58,73.0,M-SC,18.30,220.0,1.24,1.49,77.38,OX40N,ATH,CABLES
68,SIS,-0.27,0.50,20.66,21.26,23054.0,556.0,111588.0,528.00,2665.28,56.0,H-SC,22.30,168.0,0.02,0.71,65.91,OX40N,NTT,MISC
43,INDIGOPNTS,4.33,-16.84,20.27,0.02,29425.0,-29392.0,145167.0,1408.00,121.54,69.0,M-SC,6.15,222.0,-1.00,0.92,64.70,OX40N,NTT,PAINTS
78,TTKPRESTIG,-0.41,-22.20,28.65,0.09,22463.0,-22373.0,78404.0,770.00,82.07,42.0,M-SC,11.11,250.0,-1.00,0.50,41.12,OX40N,NTT,DURABLES
16,CERA,0.95,-22.31,59.47,23.89,81268.0,-39249.0,136654.0,9475.00,-25.06,41.0,H-SC,12.43,153.0,-0.48,0.87,32.84,OX40N,NTT,CERAMICS

In [14]:
# top 5 to book for rotation
df_tmp = df_portfolio_features[(df_portfolio_features['Current P/L%'] > 20) ].sort_values(by = 'CumlRnk', ascending=False)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
25,FINCABLES,0.92,59.69,30.19,107.91,71182.0,88135.0,235779.0,1641.55,43.58,73.0,M-SC,18.30,220.0,1.24,1.49,77.38,OX40N,ATH,CABLES
87,ZYDUSLIFE,-0.55,22.42,10.69,35.51,27426.0,46985.0,256559.0,1285.01,6.76,57.0,H-MC,15.98,120.0,1.71,1.62,35.02,AR,ATH,PHARMA
57,QUESS,-1.87,34.50,29.29,73.90,42073.0,36849.0,143642.0,424.00,-27.82,64.0,X-SC,41.51,80.0,0.88,0.91,97.70,XY24,NTT,MISC

In [15]:
# top 5 to monitor for exit
df_tmp = df_portfolio_features[~df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])]
df_tmp = df_tmp[(df_tmp['Current P/L%'] > 0) ].sort_values(by = 'Dev%_PE', ascending=False)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
68,SIS,-0.27,0.50,20.66,21.26,23054.0,556.0,111588.0,528.00,2665.28,56.0,H-SC,22.30,168.0,0.02,0.71,65.91,OX40N,NTT,MISC
69,STARHEALTH,-0.54,12.25,31.18,47.26,98396.0,34451.0,315574.0,761.00,77.10,48.0,H-SC,16.42,173.0,0.35,2.00,36.45,XY24,NTT,INSURANCE
25,FINCABLES,0.92,59.69,30.19,107.91,71182.0,88135.0,235779.0,1641.55,43.58,73.0,M-SC,18.30,220.0,1.24,1.49,77.38,OX40N,ATH,CABLES
87,ZYDUSLIFE,-0.55,22.42,10.69,35.51,27426.0,46985.0,256559.0,1285.01,6.76,57.0,H-MC,15.98,120.0,1.71,1.62,35.02,AR,ATH,PHARMA
80,UTIAMC,-0.77,0.28,50.73,51.15,113103.0,620.0,222950.0,1371.68,-19.39,48.0,M-SC,7.64,229.0,0.01,1.41,4.43,XY24,ATH,FINANCE

In [16]:
# top 5 to book for rotation from weak conviction
df_tmp = df_portfolio_features[~df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])]
df_tmp = df_tmp[~df_tmp['Criteria'].isin(['XY25','XY24','X40', 'X40N'])].sort_values(by = 'RRR Ind', ascending=False)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
87,ZYDUSLIFE,-0.55,22.42,10.69,35.51,27426.0,46985.0,256559.0,1285.01,6.76,57.0,H-MC,15.98,120.0,1.71,1.62,35.02,AR,ATH,PHARMA
25,FINCABLES,0.92,59.69,30.19,107.91,71182.0,88135.0,235779.0,1641.55,43.58,73.0,M-SC,18.30,220.0,1.24,1.49,77.38,OX40N,ATH,CABLES
68,SIS,-0.27,0.50,20.66,21.26,23054.0,556.0,111588.0,528.00,2665.28,56.0,H-SC,22.30,168.0,0.02,0.71,65.91,OX40N,NTT,MISC
3,ALKYLAMINE,0.82,-18.85,137.28,92.54,112471.0,-19035.0,81928.0,4520.85,-13.07,55.0,H-SC,13.71,142.0,-0.17,0.52,55.57,SR,ATH,CHEMICALS
42,INDIAMART,1.14,-22.44,159.04,100.92,152146.0,-27671.0,95665.0,4675.60,-65.04,46.0,H-SC,12.95,140.0,-0.18,0.61,3.56,AR,ATH,MISC

In [17]:
# top 5 to accumulate based on lowest RSI_14
df_tmp = df_portfolio_features[df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])].sort_values(by = 'RSI_14', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
28,GODREJCP,0.01,-14.76,55.92,32.90,118941.0,-36838.0,212699.0,1460.97,-11.86,32.0,X-LC,5.19,32.0,-0.31,1.35,3.54,X40N,ATH,FMCG
55,PAGEIND,-2.04,-2.15,36.52,33.59,95903.0,-5774.0,262605.0,51217.29,-29.78,33.0,X-MC,8.87,55.0,-0.06,1.66,24.71,X40,ATH,APPARELS
34,HDFCBANK,0.28,-11.20,47.58,31.05,123843.0,-32836.0,260284.0,1073.00,-25.96,34.0,X-LC,12.48,26.0,-0.27,1.65,1.03,X40,BTT,BANKS
56,PGHH,0.28,-36.53,108.00,32.01,146353.0,-78008.0,135512.0,17616.87,-57.06,35.0,X-MC,19.22,57.0,-0.53,0.86,0.28,X40,ATH,FMCG
19,COLPAL,-0.97,-24.97,86.40,39.86,170735.0,-65755.0,197610.0,3683.41,-9.21,38.0,X-MC,1.47,62.0,-0.39,1.25,11.78,XY25,ATH,FMCG

In [18]:
# top 5 to accumulate based on Spread and CumlRnk
df_tmp = df_portfolio_features[df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])]
df_tmp = df_tmp[(df_tmp['CumlRnk'] < 100)].sort_values(by = 'Spread%', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
19,COLPAL,-0.97,-24.97,86.40,39.86,170735.0,-65755.0,197610.0,3683.41,-9.21,38.0,X-MC,1.47,62.0,-0.39,1.25,11.78,XY25,ATH,FMCG
23,DMART,0.43,-1.10,32.88,31.42,101387.0,-3435.0,308355.0,5391.45,-17.73,53.0,X-LC,2.69,14.0,-0.03,1.95,11.27,X40N,ATH,FMCG
50,KOTAKBANK,0.06,3.20,15.23,18.92,37674.0,7668.0,247370.0,452.46,-9.84,53.0,X-LC,2.76,12.0,0.20,1.57,11.30,X40,ATH,BANKS
26,GILLETTE,-0.06,-10.38,44.74,29.72,101806.0,-26346.0,227550.0,10978.86,-31.19,40.0,X-SC,3.20,83.0,-0.26,1.44,4.57,X40,ATH,FMCG
8,BAJAJHLDNG,-1.62,2.34,25.31,28.24,66310.0,5988.0,261993.0,14274.15,-6.07,61.0,X-LC,3.23,28.0,0.09,1.66,31.86,X40,ATH,FINANCE

In [19]:
# top 5 to accumulate based on lowest Gained%
df_tmp = df_portfolio_features[df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])].sort_values(by = 'Gained%', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
35,HDFCLIFE,-0.16,-7.87,51.04,39.15,117900.0,-19741.0,230996.0,811.41,-31.35,39.0,X-LC,16.40,31.0,-0.17,1.46,0.23,X40,ATH,INSURANCE
56,PGHH,0.28,-36.53,108.00,32.01,146353.0,-78008.0,135512.0,17616.87,-57.06,35.0,X-MC,19.22,57.0,-0.53,0.86,0.28,X40,ATH,FMCG
47,ITC,-0.72,-23.72,63.47,24.70,192342.0,-94234.0,303044.0,452.00,-59.97,39.0,X-LC,10.73,1.0,-0.49,1.92,0.34,X40,NTT,FMCG
20,DABUR,-0.20,-20.00,79.62,43.70,158015.0,-49606.0,198462.0,735.00,-27.41,38.0,X-MC,9.56,70.0,-0.31,1.26,0.99,XY24,BTT,FMCG
34,HDFCBANK,0.28,-11.20,47.58,31.05,123843.0,-32836.0,260284.0,1073.00,-25.96,34.0,X-LC,12.48,26.0,-0.27,1.65,1.03,X40,BTT,BANKS

In [20]:
# top 5 to accumulate based on lowest CurrAlloc%
df_tmp = df_portfolio_features[df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])].sort_values(by = 'CurrAlloc%', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
10,BATAINDIA,4.32,-51.03,176.12,35.20,110964.0,-65665.0,63005.0,2096.00,-17.40,69.0,X-SC,12.49,91.0,-0.59,0.40,26.58,X40,NTT,FOOTWEAR
61,RELAXO,-2.48,-47.33,189.19,52.31,144636.0,-68710.0,76450.0,1176.00,-43.96,51.0,X-SC,12.86,92.0,-0.48,0.48,70.93,X40N,NTT,FOOTWEAR
56,PGHH,0.28,-36.53,108.00,32.01,146353.0,-78008.0,135512.0,17616.87,-57.06,35.0,X-MC,19.22,57.0,-0.53,0.86,0.28,X40,ATH,FMCG
57,QUESS,-1.87,34.50,29.29,73.90,42073.0,36849.0,143642.0,424.00,-27.82,64.0,X-SC,41.51,80.0,0.88,0.91,97.70,XY24,NTT,MISC
2,ACC,-0.15,-40.80,195.31,74.81,310004.0,-109404.0,158724.0,3906.00,-57.90,41.0,X-SC,11.74,85.0,-0.35,1.00,6.04,XY24,BTT,CEMENT

In [21]:
# top 5 to accumulate based on CumlRnk
df_tmp = df_portfolio_features.sort_values(by = 'CumlRnk', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
47,ITC,-0.72,-23.72,63.47,24.70,192342.0,-94234.0,303044.0,452.00,-59.97,39.0,X-LC,10.73,1.0,-0.49,1.92,0.34,X40,NTT,FMCG
74,TCS,-0.36,-30.53,78.77,24.20,253517.0,-141429.0,321844.0,4230.71,-41.33,54.0,X-LC,14.79,2.0,-0.56,2.04,20.02,X40,ATH,IT
45,INFY,-0.42,-16.70,68.53,40.38,214901.0,-62883.0,313587.0,1972.00,-37.23,59.0,X-LC,16.02,3.0,-0.29,1.98,18.76,X40,NTT,IT
76,TMPV,-4.92,-20.92,80.51,42.75,264939.0,-87031.0,329076.0,600.00,-84.72,42.0,X-LC,4.50,4.0,-0.33,2.08,13.15,XY24,NTT,AUTO
33,HCLTECH,-0.28,-8.63,35.67,23.97,100869.0,-26703.0,282783.0,1853.42,-6.95,69.0,X-LC,12.07,8.0,-0.26,1.79,33.44,X40,ATH,IT

In [22]:
# top 5 for average up
df_tmp = df_portfolio_features[(df_portfolio_features['Dev%_200'] > 5)].sort_values(by = 'CurrAlloc%', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
44,INDUSINDBK,-0.22,-24.51,76.04,32.89,44318.0,-18924.0,58282.0,1800.00,-374.51,55.0,L-MC,13.62,258.0,-0.43,0.37,43.69,XR,NTT,BANKS
61,RELAXO,-2.48,-47.33,189.19,52.31,144636.0,-68710.0,76450.0,1176.00,-43.96,51.0,X-SC,12.86,92.0,-0.48,0.48,70.93,X40N,NTT,FOOTWEAR
3,ALKYLAMINE,0.82,-18.85,137.28,92.54,112471.0,-19035.0,81928.0,4520.85,-13.07,55.0,H-SC,13.71,142.0,-0.17,0.52,55.57,SR,ATH,CHEMICALS
12,BOSCH-HCIL,-2.10,-26.48,36.01,-0.01,33834.0,-33848.0,93957.0,2282.00,19117.39,76.0,M-SC,4.20,231.0,-1.00,0.59,59.93,OX40N,BTT,AC
82,VALIANTORG,-0.25,-32.56,158.24,74.15,174586.0,-53275.0,110330.0,838.00,-298.38,74.0,H-SC,4.55,145.0,-0.31,0.70,64.19,XR,NTT,CHEMICALS

In [23]:
# top 5 RSP
df_tmp = df_portfolio_features.sort_values(by = 'RSP', ascending=False)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
12,BOSCH-HCIL,-2.10,-26.48,36.01,-0.01,33834.0,-33848.0,93957.0,2282.00,19117.39,76.0,M-SC,4.20,231.0,-1.00,0.59,59.93,OX40N,BTT,AC
25,FINCABLES,0.92,59.69,30.19,107.91,71182.0,88135.0,235779.0,1641.55,43.58,73.0,M-SC,18.30,220.0,1.24,1.49,77.38,OX40N,ATH,CABLES
33,HCLTECH,-0.28,-8.63,35.67,23.97,100869.0,-26703.0,282783.0,1853.42,-6.95,69.0,X-LC,12.07,8.0,-0.26,1.79,33.44,X40,ATH,IT
82,VALIANTORG,-0.25,-32.56,158.24,74.15,174586.0,-53275.0,110330.0,838.00,-298.38,74.0,H-SC,4.55,145.0,-0.31,0.70,64.19,XR,NTT,CHEMICALS
38,HYUNDAI,-0.14,15.55,24.56,43.94,71327.0,39088.0,290420.0,2782.73,-4.38,72.0,X-LC,4.45,29.0,0.55,1.84,33.34,X40N,ATH,AUTO

In [24]:
# Top N allocation
df_tmp = df_portfolio_features.sort_values(by = 'CurrAlloc%', ascending=False)
top_n_values = [10, 25, 50]

sum_df = pd.DataFrame({
    'Top_N': top_n_values,
    'Sum_Alloc%': [df_tmp['CurrAlloc%'].head(n).sum() for n in top_n_values]
})

sum_df

   Top_N  Sum_Alloc%
0     10       19.68
1     25       44.72
2     50       76.78

In [25]:
# market-cap-wise allocation
df_tmp = df_portfolio_features[cols]
df_tmp.groupby(df_tmp['Conviction'].str[-2:])['CurrAlloc%'].sum().sort_values(ascending=False)

Conviction
SC    39.38
LC    37.63
MC    22.97
Name: CurrAlloc%, dtype: float64

In [26]:
# criteria-wise allocation
df_portfolio_features.groupby('Criteria')['CurrAlloc%'].sum().sort_values(ascending=False)

Criteria
X40      26.39
XY24     24.82
X40N     18.33
XR        9.06
OX40N     7.21
XY25      7.21
AR        6.11
SR        0.85
Name: CurrAlloc%, dtype: float64

In [27]:
# conviction-wise allocation
df_portfolio_features.groupby('Conviction')['CurrAlloc%'].sum().sort_values(ascending=False)

Conviction
X-LC    35.54
H-SC    19.22
X-MC    18.76
M-SC    11.19
X-SC     8.48
H-MC     2.65
H-LC     1.27
M-MC     1.19
M-LC     0.82
L-SC     0.49
L-MC     0.37
Name: CurrAlloc%, dtype: float64

In [28]:
# sector-wise stats
df_tmp = df_portfolio_features.groupby('Category')[['CurrAlloc%', 'Current', 'Current P/L', 'FTT Amt']].sum().sort_values(by=['Current', 'Current P/L'], ascending=False)
df_tmp['Current P/L%'] = round(df_tmp['Current P/L'] * 100 / df_tmp['Current'], 2)
df_tmp['FTT%'] = round(df_tmp['FTT Amt'] * 100 / df_tmp['Current'], 2)
cols = ['CurrAlloc%', 'Current P/L%', 'FTT%']
df_tmp[cols].sort_values(by=['CurrAlloc%'], ascending=False)

               CurrAlloc%  Current P/L%    FTT%
Category
FMCG                15.33        -23.11   67.38
IT                  11.14        -35.37  102.55
FINANCE             10.61        -15.01   64.55
AUTO                 8.21         -4.22   41.54
MISC                 6.90        -23.13   75.96
BANKS                6.08        -11.20   59.16
PHARMA               5.71          8.22   17.81
INSURANCE            5.59         -5.28   42.51
PAINTS               5.54        -12.76   31.99
ELECTRICAL           4.11         -8.78   46.87
AC                   1.83        -10.13   39.99
REFINERIES           1.69        -11.55   49.02
FOOTWEAR             1.67        -66.97  133.92
APPARELS             1.66         -2.20   36.52
BREWERIES            1.65         10.16    8.50
CABLES               1.49         37.38   30.19
DURABLES             1.48        -65.34  105.57
TRAVEL               1.42       -100.09  200.27
CERAMICS             1.35        -44.67   88.62
ENGINEERING          1.22        -25.54   82.96
CHEMICALS            1.22        -37.61  149.31
CEMENT               1.00        -68.93  195.31
JEWELLERY            0.97       -109.81  182.70
HEALTHCARE           0.69        -67.16  109.12
ENTERTAINMENT        0.68        -78.70  185.27
TEXTILES             0.39        -51.15   94.25
HOTELS               0.35       -102.53  173.97

In [29]:
# money to be made criteria-wise
df_portfolio_features.groupby('Criteria')['FTT Amt'].agg(['sum', 'count']).sort_values(by='sum', ascending=False)

                sum  count
Criteria
XY24      3590967.0     20
X40       2057592.0     18
XR        1365471.0     13
X40N      1182106.0     12
AR        1067002.0      8
OX40N      652420.0     10
XY25       559456.0      5
SR         283015.0      2

In [30]:
# money to be made conviction-wise
df_portfolio_features.groupby('Conviction')['FTT Amt'].agg(['sum', 'count']).sort_values(by='sum', ascending=False)

                  sum  count
Conviction
H-SC        3314503.0     23
X-LC        2442639.0     20
X-MC        1490256.0     14
M-SC        1485776.0     15
X-SC        1236335.0      8
H-MC         278541.0      2
L-SC         213152.0      2
M-LC         162836.0      1
M-MC          57474.0      1
L-MC          44318.0      1
H-LC          32199.0      1

In [31]:
# money to be made criteria and conviction-wise
df_portfolio_features.groupby(['Conviction', 'Criteria'])['FTT Amt'].agg(['sum', 'count']).sort_values(by='sum', ascending=False)

                           sum  count
Conviction Criteria
X-LC       X40       1178142.0      9
H-SC       XY24      1000372.0      5
M-SC       XY24       971112.0      7
H-SC       AR         931587.0      5
           XR         807825.0      7
X-SC       XY24       711138.0      3
X-MC       X40        666680.0      7
X-LC       X40N       517886.0      6
           XY24       438390.0      2
X-MC       X40N       351793.0      3
X-SC       X40N       312427.0      3
H-SC       OX40N      291704.0      4
           SR         283015.0      2
X-MC       XY25       252943.0      2
H-MC       XY24       251115.0      1
X-LC       XY25       249039.0      2
M-SC       OX40N      245099.0      5
X-MC       XY24       218840.0      2
X-SC       X40        212770.0      2
M-SC       XR         193775.0      2
M-LC       XR         162836.0      1
L-SC       OX40N      115617.0      1
           XR          97535.0      1
M-SC       AR          75790.0      1
X-LC       XR          59182.0      1
M-MC       XY25        57474.0      1
L-MC       XR          44318.0      1
H-LC       AR          32199.0      1
H-MC       AR          27426.0      1

In [32]:
# notebook execution time

end_time = time.time()
execution_time = round(end_time - start_time, 0)
print(f"Notebook execution time: {execution_time} seconds")

Notebook execution time: 31.0 seconds