<a href="https://colab.research.google.com/github/ankit-rathi/Quantvesting_v2/blob/main/myStocks_Portfolio_Analysis.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
'''
!pip install pandas==2.2.2 -qq
!pip install pyxirr -qq
!pip install ta -qq
!pip install yfinance==0.2.59 -qq
'''

'\n!pip install pandas==2.2.2 -qq\n!pip install pyxirr -qq\n!pip install ta -qq\n!pip install yfinance==0.2.59 -qq\n'

In [2]:
# import libraries

import numpy as np
import pandas as pd
import datetime
import warnings
warnings.filterwarnings('ignore')
import yfinance as yfin
import ta
import matplotlib.pyplot as plt
import requests

In [3]:
# notebook start time
import time
import datetime
import pytz

start_time = time.time()

# function to print date timestamp
def print_date_time():
  tz_NY = pytz.timezone('Asia/Kolkata')
  datetime_NY = datetime.datetime.now(tz_NY)
  print("Run date time (IST):", datetime_NY.strftime("%Y-%m-%d %H:%M:%S"))

In [4]:
# function to get booked and reserved amount
def get_amt():
  # fetch the JSON data from the URL
  url = "https://raw.githubusercontent.com/ankit-rathi/Tradevesting_v1/main/data/myPortfolioAmts.json"
  response = requests.get(url)
  pf_amts = response.json()  # parse the JSON data

  # extract values from the JSON
  py_booked_amt_dm = pf_amts["py_booked_amt_dm"]
  py_booked_amt_sv = pf_amts["py_booked_amt_sv"]
  cy_booked_amt_dm = pf_amts["cy_booked_amt_dm"]
  cy_booked_amt_sv = pf_amts["cy_booked_amt_sv"]
  reserve_amt_dm = pf_amts["reserve_amt_dm"]
  reserve_amt_sv = pf_amts["reserve_amt_sv"]

  # perform calculations
  py_booked_amt = py_booked_amt_dm + py_booked_amt_sv
  cy_booked_amt = cy_booked_amt_dm + cy_booked_amt_sv
  reserve_amt = reserve_amt_dm + reserve_amt_sv
  total_booked_amt = py_booked_amt + cy_booked_amt

  return total_booked_amt, reserve_amt, cy_booked_amt, py_booked_amt

gen_output = 0

In [5]:
# function to format the amount
def format_amt(number):
    abs_number = abs(number)

    if abs_number >= 1_00_00_000:  # Crores
        formatted_amt = f"{number / 1_00_00_000:.2f} C"
    elif abs_number >= 1_00_000:  # Lakhs
        formatted_amt = f"{number / 1_00_000:.2f} L"
    elif abs_number >= 1_000:  # Thousands
        formatted_amt = f"{number / 1_000:.2f} K"
    else:
        formatted_amt = f"{number:.2f}"

    return formatted_amt

# function to set start and end date
def get_start_end_date():
  start_date = (datetime.date.today() + datetime.timedelta(days=-365)).strftime('%Y-%m-%d')
  end_date = (datetime.date.today() + datetime.timedelta(days=1)).strftime('%Y-%m-%d')
  return start_date, end_date

# function to fetch my portfolio csv
def get_mypfs_df():
  mypfs_df = pd.read_csv('https://raw.githubusercontent.com/ankit-rathi/Tradevesting_v1/main/data/myPortfolioStocks.csv')
  return mypfs_df

# function to fetch my prospects csv
def get_mypps_df():
  mypps_df = pd.read_csv('https://raw.githubusercontent.com/ankit-rathi/Tradevesting_v1/main/data/myProspectsScrips.csv')
  return mypps_df

# function to fetch screener data
def get_myscreen_df():
  myscreen_df = pd.read_csv('https://raw.githubusercontent.com/ankit-rathi/Tradevesting_v1/main/data/myScreenerDB.csv')
  return myscreen_df

# function to fetch momentum data
def get_myinvmt_df():
  myinvmt_df = pd.read_csv('https://raw.githubusercontent.com/ankit-rathi/Tradevesting_v1/main/data/myInvestments.csv')
  return myinvmt_df

# function to get the stock ids
def get_stock_ids(df_pf):
  stock_n100 = df_pf['Symbol'].unique()

  exclude = ['CADILAHC','MMTC', 'MASFIN']

  stock_ids = df_pf[~df_pf['Symbol'].isin(exclude) ]['Symbol'].unique()

  #mypf = mypf[mypf.Forecast.notnull()]
  #stock_ids = mypf['Symbol'].unique()

  #stock_ids.sort()
  return stock_ids

# get features from screener data
def get_screener_features():
  myscreen_df = get_myscreen_df()
  cols = ['Symbol', 'EPS', 'MedPE', 'ROCE%', 'ROE%', 'CapType']
  return myscreen_df[cols]

# get relative strength
def get_relative_strength(stock_list):

    # Dictionary to store stock tickers and their corresponding percentage price change
    stock_changes = {}

    # Loop through each stock and fetch its price data
    for stock in stock_list:
        try:
            # Download the stock data for the given date range
            stock_data = yfin.Ticker(stock + '.NS').history(period='1mo', interval='1d')[map(str.title, ['open', 'close', 'low', 'high', 'volume'])]

            # Calculate the percentage change for the stock
            if len(stock_data) > 0:
                start_price = stock_data['Close'].iloc[0]
                end_price = stock_data['Close'].iloc[-1]
                percent_change = round(((end_price - start_price) / start_price) * 100, 2)
                stock_changes[stock] = percent_change
            else:
                stock_changes[stock] = np.nan  # If no data is available, set to NaN

        except Exception as e:
            print(f"Error fetching data for {stock}: {e}")
            stock_changes[stock] = np.nan

    # Create a DataFrame with stock tickers and their percentage changes
    df = pd.DataFrame(list(stock_changes.items()), columns=['Symbol', 'Percent_Change'])

    # Drop any stocks with missing data (NaN values)
    df = df.dropna()

    # Calculate the percentile rank based on percentage change
    df['RSP'] = round(df['Percent_Change'].rank(pct=True) * 100, 2)
    cols = ['Symbol', 'RSP']
    df = df[cols]
    # Sort by percentile rank (optional)
    df = df.sort_values(by='RSP', ascending=False).reset_index(drop=True)

    return df

In [6]:
# function to get stock technicals
def stock_prec_dev(stock_symbol):
    #stock_symbol = 'ULTRACEMCO.NS'
    short_window = 20
    mid_window = 50
    long_window = 200
    moving_avg = 'SMA'

    start = datetime.datetime(*map(int, start_date.split('-')))
    end = datetime.datetime(*map(int, end_date.split('-')))

    stock_df = yfin.Ticker(stock_symbol + '.NS').history(period='max', interval='1d')[map(str.title, ['open', 'close', 'low', 'high', 'volume'])]

    stock_df['Max'] = round(max(stock_df['Close']),2)
    stock_df = stock_df[(stock_df.index <= end_date) & (stock_df.index >= start_date)]
    stock_df['200_SMA'] = round(stock_df['Close'].rolling(window = 200, min_periods = 1).mean(),0)
    stock_df['Dev%_200'] = round((stock_df['Close'] - stock_df['200_SMA'])*100/stock_df['200_SMA'],2)
    stock_df.dropna(axis = 0, inplace = True) # remove any null rows

    stock_df['20_SMA'] = stock_df['Close'].rolling(window=20).mean()
    stock_df['50_SMA'] = stock_df['Close'].rolling(window=50).mean()
    stock_df['Symbol'] = stock_symbol

    stock_df['Close'] = round(stock_df['Close'],2)
    stock_df['Min'] = round(min(stock_df['Close']),2)
    stock_df['RSI_14'] = ta.momentum.RSIIndicator(close=stock_df['Close'], window=14).rsi()
    stock_df['RSI_14'] = round(stock_df['RSI_14'],0)
    stock_df['Prev_Close'] = stock_df['Close'].shift(1)
    stock_df.drop(['Open', 'Low', 'High', 'Volume'], axis=1, inplace=True)
    stock_df = stock_df.tail(1)

    max_SMA = max(stock_df['20_SMA'].item(), stock_df['50_SMA'].item(), stock_df['200_SMA'].item())
    min_SMA = min(stock_df['20_SMA'].item(), stock_df['50_SMA'].item(), stock_df['200_SMA'].item())
    ABS_Spread = max_SMA - min_SMA
    stock_df['Spread%'] = round((ABS_Spread / stock_df['200_SMA'].item()) * 100,2)

    return stock_df

# function to compute stock attributes
def get_common_features(stock_ids, df_mypf):

  df_prec_dev = pd.DataFrame()
  df_tmp = get_screener_features()
  df_rs = get_relative_strength(stock_ids)

  for stock_id in stock_ids:
      tmp = stock_prec_dev(stock_id)
      tmp = tmp.reset_index()
      df_prec_dev = pd.concat([df_prec_dev, tmp], ignore_index = True)
  df_prec_dev = pd.merge(df_prec_dev, df_mypf, on= 'Symbol')
  df_prec_dev = pd.merge(df_prec_dev, df_tmp, on= 'Symbol', how='left')
  df_prec_dev = pd.merge(df_prec_dev, df_rs, on= 'Symbol', how='left')
  #print(df_prec_dev.columns)
  df_prec_dev['Curr_PE'] = round(df_prec_dev['Close']/df_prec_dev['EPS'],1)
  df_prec_dev['Dev%_PE'] = round((df_prec_dev['Curr_PE'] - df_prec_dev['MedPE'])*100/df_prec_dev['MedPE'],2)
  df_prec_dev['Conviction'] = df_prec_dev['Conviction'] + '-' + df_prec_dev['CapType']
  return df_prec_dev

# function to arrange stock features
def arrange_features(df_stocks, common_cols, diff_cols):
  df_stocks_common = df_stocks[common_cols].drop_duplicates()
  df_stocks_diff = df_stocks[diff_cols]
  df_stocks_diff['Investment'] = df_stocks_diff['AvgCost'] * df_stocks_diff['Shares']
  df_stocks_diff = df_stocks_diff.groupby(['Symbol'])[['Shares', 'Investment']].aggregate(['sum']).reset_index()
  df_stocks_diff.columns = ['Symbol', 'Shares', 'Investment']
  df_stocks_diff['AvgCost'] = round(df_stocks_diff['Investment']/df_stocks_diff['Shares'],2)
  df_stocks = pd.merge(df_stocks_diff, df_stocks_common, on='Symbol')
  return df_stocks

# plot fact distribution across dimension
def plot_pie_chart(df, dimension, fact):
  # grouping the data by category and calculating the sum of fact for each type
  grouped_data = df.groupby(dimension)[fact].sum()

  # sorting the grouped data in descending order
  grouped_data = grouped_data.sort_values(ascending=False)

  # creating a pie chart
  grouped_data.plot.pie(autopct='%1.1f%%', startangle=90, figsize=(6, 6))

  # adding a title and displaying the plot
  plt.title(f'{dimension} {fact} Distribution')
  plt.ylabel('')  # To hide the y-label
  plt.show()

In [7]:
# function to get portfolio features

def get_portfolio_features(df_common_features):

  print_date_time()
  print('-------------------')

  #df_common_features["Target"] = df_common_features["Target"].fillna(df_common_features["Max"])
  df_common_features['NTT'] = np.where(df_common_features['Strategy']== 'NTT', df_common_features["Target"], df_common_features['Max'])
  df_common_features['LTT'] = np.where(df_common_features['Strategy']== 'BTT', df_common_features["Target"], df_common_features['Max'])
  df_common_features['BOL'] = df_common_features['Min']

  tmp_df = df_common_features[df_common_features['Symbol'].isin(mypf_df[mypf_df['InPortfolio'] != 'NA'].Symbol.values)]
  print('qualified stocks: '+str(len(tmp_df['Symbol'].unique())))
  tmp_df1 = tmp_df[tmp_df['LatestQtr'] == 1]
  print('with latest results: '+str(len(tmp_df1['Symbol'].unique())))
  tmp_df1 = tmp_df1[tmp_df1['StarStock'] == 1]
  print('still star stocks: '+str(len(tmp_df1['Symbol'].unique())))
  tmp_df['Investment'] = tmp_df['AvgCost'] * tmp_df['Shares']
  tmp_df['Current'] = round(tmp_df['Close'] * tmp_df['Shares'],0)
  tmp_df['Previous'] = tmp_df['Prev_Close'] * tmp_df['Shares']
  tmp_df['EstimatedST'] = tmp_df['NTT'] * tmp_df['Shares']
  tmp_df['EstimatedLT'] = tmp_df['LTT'] * tmp_df['Shares']
  tmp_df['Current P/L'] = round((tmp_df['Current'] - tmp_df['Investment']),0)
  tmp_df['Today P/L%'] = round((tmp_df['Current'] - tmp_df['Previous'])*100/tmp_df['Previous'],2)
  tmp_df['Current P/L%'] = round((tmp_df['Current'] - tmp_df['Investment'])*100/tmp_df['Investment'],2)
  tmp_df['EstimatedST P/L%'] = round((tmp_df['EstimatedST'] - tmp_df['Investment'])*100/tmp_df['Investment'],2)
  tmp_df['EstimatedLT P/L%'] = round((tmp_df['EstimatedLT'] - tmp_df['Investment'])*100/tmp_df['Investment'],2)
  tmp_df['NTT%'] = round((tmp_df['NTT'] - tmp_df['Close'])*100/tmp_df['Close'],2)
  tmp_df['LTT%'] = round((tmp_df['LTT'] - tmp_df['Close'])*100/tmp_df['Close'],2)
  tmp_df['Gained%'] = round((tmp_df['Close'] - tmp_df['BOL'])*100/tmp_df['BOL'],2)
  investment = round(sum(tmp_df['AvgCost']*tmp_df['Shares']),0)
  current = round(sum(tmp_df['Close']*tmp_df['Shares']),0)
  tmp_df['InitAlloc%'] = round(tmp_df['Investment']*100/investment,2)
  tmp_df['CurrAlloc%'] = round(tmp_df['Current']*100/current,2)
  tmp_df['FTT'] = tmp_df['LTT']
  tmp_df.loc[tmp_df['Strategy'] == 'NTT', 'FTT'] = tmp_df['NTT']
  tmp_df['FTT%'] = tmp_df['LTT%']
  tmp_df.loc[tmp_df['Strategy'] == 'NTT', 'FTT%'] = tmp_df['NTT%']
  tmp_df['FTT Amt'] = round(tmp_df['FTT%'] * tmp_df['Current']/100,0)
  tmp_df['OTT%'] = round((tmp_df['FTT'] - tmp_df['AvgCost'])*100/tmp_df['AvgCost'],2)
  tmp_df['RRR Ind'] = round(tmp_df['Current P/L']/tmp_df['FTT Amt'],2)
  tmp_df['Risk Ind'] = round(tmp_df['Current P/L%']*tmp_df['CurrAlloc%'],0)

  return tmp_df

# function to print portfolio features
def print_portfolio_stats(df_portfolio_features, myinvmt_df):
  from pyxirr import xirr

  total_booked_amt, reserve_amt, cy_booked_amt, py_booked_amt = get_amt()

  dates = myinvmt_df['Date'].values
  dates = np.append(dates, datetime.date.today().strftime('%d-%b-%y'))
  investment = myinvmt_df['Investment'].values
  dates= pd.to_datetime(dates)

  current = round(sum(df_portfolio_features['Close']*df_portfolio_features['Shares']),0) + reserve_amt
  investment_xirr = np.append(investment, current)
  cagr = round(xirr(pd.DataFrame({"dates": dates, "amounts": investment_xirr}))*100,2)

  investment = -sum(investment)
  invested = round(sum(df_portfolio_features['AvgCost']*df_portfolio_features['Shares']),0) + reserve_amt
  previous = round(sum(df_portfolio_features['Prev_Close']*df_portfolio_features['Shares']),0) + reserve_amt
  cy_invested = investment + py_booked_amt

  today_pnl_amount = current-previous
  today_pnl_percentage = round((current-previous)*100/previous,2)

  curr_pnl_amount = current-invested
  curr_pnl_percentage = round((curr_pnl_amount)*100/(cy_invested),2)

  cy_pnl_amount = cy_booked_amt + curr_pnl_amount
  cy_pnl_percentage = round((cy_pnl_amount)*100/cy_invested,2)

  overall_pnl_amount = total_booked_amt + curr_pnl_amount
  overall_pnl_percentage = round((overall_pnl_amount)*100/investment,2)

  estimate_st = round(sum(df_portfolio_features['FTT']*df_portfolio_features['Shares']),0)  + reserve_amt
  est_st_pnl_amount = estimate_st-current
  est_st_pnl_percentage = round((est_st_pnl_amount)*100/current,2)

  estimate_lt = round(sum(df_portfolio_features['LTT']*df_portfolio_features['Shares']),0)  + reserve_amt
  est_lt_pnl_amount = estimate_lt-current
  est_lt_pnl_percentage = round((est_lt_pnl_amount)*100/current,2)

  total_profit = round(sum(df_portfolio_features[df_portfolio_features['Current P/L%'] > 0]['Current']) - sum(df_portfolio_features[df_portfolio_features['Current P/L%'] > 0]['Investment']),0)
  total_loss = round(sum(df_portfolio_features[df_portfolio_features['Current P/L%'] < 0]['Current']) - sum(df_portfolio_features[df_portfolio_features['Current P/L%'] < 0]['Investment']),0)

  cy_booked_percentage = round((cy_booked_amt)*100/current,2)
  py_booked_percentage = round((py_booked_amt)*100/investment,2)
  total_booked_percentage = round((total_booked_amt)*100/investment,2)

  print('-------------------')
  print('Initial Investment: ', format_amt(investment))
  print('CY Investment: ', format_amt(cy_invested))
  print('Reserve: ', format_amt(reserve_amt))
  print('Current: ',  format_amt(current))
  print('-------------------')
  print('Today PnL: '+ '{} ({}%)'.format(format_amt(today_pnl_amount), today_pnl_percentage))
  print('Current PnL: '+ '{} ({}%)'.format(format_amt(curr_pnl_amount), curr_pnl_percentage))
  print('CY Booked + Current PnL: '+ '{} ({}%)'.format(format_amt(cy_pnl_amount), cy_pnl_percentage))
  print('-------------------')
  print('Total profit: ', format_amt(total_profit))
  print('Total loss: ', format_amt(total_loss))
  print('-------------------')
  print('Total Booked + Current PnL: '+ '{} ({}%)'.format(format_amt(overall_pnl_amount), overall_pnl_percentage))
  print('Total Booked PnL: '+ '{} ({}%)'.format(format_amt(total_booked_amt), total_booked_percentage))
  print('Curr Year Booked PnL: '+ '{} ({}%)'.format(format_amt(cy_booked_amt), cy_booked_percentage))
  print('Prev Year Booked PnL: '+ '{} ({}%)'.format(format_amt(py_booked_amt), py_booked_percentage))
  print('===================')
  print('Est FTT: ',  format_amt(estimate_st))
  print('Est FTT PnL: '+ '{} ({}%)'.format(format_amt(est_st_pnl_amount), est_st_pnl_percentage))

  print('===================')
  print('Deployed: ', format_amt(investment))

  print('Current: ', format_amt(current))

  print('CAGR/XIRR %: '+'{}%'.format(cagr))

In [8]:
# get start and end date
start_date, end_date = get_start_end_date()

# get portfolio and prospects data
mypfs_df = get_mypfs_df()
mypps_df = get_mypps_df()
myinvmt_df = get_myinvmt_df()

# merge above datasets
mypf_df = pd.merge(mypfs_df, mypps_df, on="Symbol")

# seggregate dm and sv portfolio
dm_pf = mypf_df[mypf_df['InPortfolio'] == 'DM']
sv_pf = mypf_df[mypf_df['InPortfolio'] == 'SV']

# build portfolio stock dataframe
dm_stocks = get_stock_ids(dm_pf)
sv_stocks = get_stock_ids(sv_pf)
df_stocks = pd.concat([dm_pf,sv_pf], ignore_index = True)

# arrange common and diff stock features
common_cols = ['Symbol', 'Target', 'Criteria', 'Strategy', 'CumlRnk', 'LatestQtr', 'StarStock', 'Conviction', 'Category', 'InFolio', 'XIRR', 'MBQ']
diff_cols = ['Symbol', 'AvgCost', 'Shares']
df_stocks = arrange_features(df_stocks, common_cols, diff_cols)

# get common features
stock_ids = df_stocks['Symbol'].values
df_common_features = get_common_features(stock_ids, df_stocks)

df_common_features.reset_index(drop=True, inplace=True)
df_common_features.drop(['Date'], axis=1, inplace=True)
# get and print portfolio features
df_portfolio_features = get_portfolio_features(df_common_features)

print_portfolio_stats(df_portfolio_features, myinvmt_df)

df = df_portfolio_features
#plot_pie_chart(df, 'CapType', 'Current')
list_ox40n = list(df[df['MBQ'].str.contains('OX40N', na=False)]['Symbol'].values)

Run date time (IST): 2026-07-31 13:51:25
-------------------
qualified stocks: 90
with latest results: 31
still star stocks: 20

-------------------
Initial Investment:  1.40 C
CY Investment:  1.82 C
Reserve:  6.53 L
Current:  1.54 C
-------------------
Today PnL: 29.52 K (0.19%)
Current PnL: -30.60 L (-16.78%)
CY Booked + Current PnL: -26.96 L (-14.78%)
-------------------
Total profit:  4.35 L
Total loss:  -34.96 L
-------------------
Total Booked + Current PnL: 15.91 L (11.4%)
Total Booked PnL: 46.51 L (33.34%)
Curr Year Booked PnL: 3.64 L (2.36%)
Prev Year Booked PnL: 42.87 L (30.73%)
===================
Est FTT:  2.55 C
Est FTT PnL: 1.00 C (65.15%)
===================
Deployed:  1.40 C
Current:  1.54 C
CAGR/XIRR %: 4.43%

In [9]:
# top 5 near their targets
cols = ['Symbol', 'Today P/L%', 'Current P/L%', 'FTT%', 'OTT%', 'FTT Amt', 'Current P/L', 'Current', 'FTT', 'Dev%_PE', 'RSI_14','Conviction', 'Spread%',  'CumlRnk', 'RRR Ind', 'CurrAlloc%', 'Gained%', 'Criteria', 'Strategy', 'Category']
df_tmp = df_portfolio_features[~df_portfolio_features['Symbol'].isin(['ENRIN','BLUSPRING','DIGITIDE'])]
df_tmp = df_tmp.sort_values(by = 'FTT Amt', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
58,PIDILITIND,-0.67,14.73,2.43,17.52,3934.0,20780.0,161890.0,1658.32,-19.59,61.0,X-LC,8.39,5.0,5.28,1.10,28.03,X40,ATH,CHEMICALS
71,SONACOMS,0.82,33.21,4.12,38.69,5552.0,33591.0,134750.0,801.69,5.59,81.0,M-MC,29.00,193.0,6.05,0.91,91.18,AR,ATH,AUTO
55,MEDANTA,-1.85,20.31,5.66,27.12,12020.0,35849.0,212366.0,1486.00,16.68,65.0,X-SC,13.10,87.0,2.98,1.44,46.33,XY24,NTT,HEALTHCARE
52,M&M,6.12,10.94,10.06,22.10,15477.0,15169.0,153850.0,3762.88,-6.09,68.0,X-LC,7.04,25.0,0.98,1.04,17.87,X40N,ATH,AUTO
81,TTKPRESTIG,-4.81,-16.22,19.46,0.09,16431.0,-16341.0,84436.0,770.00,95.94,54.0,M-SC,13.01,250.0,-0.99,0.57,51.97,OX40N,NTT,DURABLES

In [10]:
# top 5 today
df_tmp = df_portfolio_features.sort_values(by = 'Today P/L%', ascending=False)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
59,QUESS,10.15,38.87,25.22,73.90,37403.0,41514.0,148307.0,424.00,-25.07,82.0,X-SC,37.17,80.0,1.11,1.00,102.17,XY24,NTT,MISC
38,HYUNDAI,8.66,16.58,28.11,49.35,50547.0,25577.0,179818.0,2809.30,-6.18,74.0,X-LC,6.64,29.0,0.51,1.22,29.65,X40N,ATH,AUTO
52,M&M,6.12,10.94,10.06,22.10,15477.0,15169.0,153850.0,3762.88,-6.09,68.0,X-LC,7.04,25.0,0.98,1.04,17.87,X40N,ATH,AUTO
12,BOSCH-HCIL,4.74,-39.53,65.36,-0.01,50510.0,-50525.0,77280.0,2282.00,15704.35,59.0,M-SC,6.64,231.0,-1.00,0.52,31.54,OX40N,BTT,AC
5,ATULAUTO,4.71,-10.57,62.78,45.57,110675.0,-20842.0,176290.0,844.00,3824.32,67.0,M-SC,5.16,248.0,-0.19,1.19,35.66,XY24,NTT,AUTO

In [11]:
# bottom 5 today
df_tmp = df_portfolio_features.sort_values(by = 'Today P/L%', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
81,TTKPRESTIG,-4.81,-16.22,19.46,0.09,16431.0,-16341.0,84436.0,770.00,95.94,54.0,M-SC,13.01,250.0,-0.99,0.57,51.97,OX40N,NTT,DURABLES
37,HONAUT,-4.48,-0.67,51.90,50.88,99414.0,-1288.0,191550.0,58192.80,-17.47,52.0,X-SC,13.85,90.0,-0.01,1.30,45.94,X40N,ATH,ELECTRICAL
75,TANLA,-3.99,-33.72,227.76,117.25,408759.0,-91292.0,179469.0,1922.32,-33.06,56.0,H-SC,9.26,147.0,-0.22,1.22,57.13,AR,ATH,IT
26,GILLETTE,-3.74,-10.24,44.53,29.72,101482.0,-26001.0,227895.0,10978.86,-31.02,41.0,X-SC,3.49,83.0,-0.26,1.54,4.73,X40,ATH,FMCG
77,TCS,-2.82,-30.62,79.02,24.20,253977.0,-141864.0,321409.0,4230.71,-41.33,62.0,X-LC,16.65,2.0,-0.56,2.18,19.86,X40,ATH,IT

In [12]:
# top 5 to exit based on CumlRnk
df_tmp = df_portfolio_features[~df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])]
df_tmp = df_tmp[(df_tmp['Current P/L%'] > -1) & (df_tmp['Current P/L%'] < 1)].sort_values(by = 'CumlRnk', ascending=False)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
62,RECLTD,0.54,0.88,19.68,20.74,40336.0,1788.0,204958.0,446.0,11.33,68.0,M-MC,2.31,191.0,0.04,1.39,23.54,XY25,NTT,FINANCE

In [13]:
# OX40N stocks to exit
df_tmp = df_portfolio_features[(df_portfolio_features['Symbol'].isin(list_ox40n))].sort_values(by = 'Current P/L%', ascending=False)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
25,FINCABLES,0.67,25.58,65.56,107.91,121555.0,37766.0,185410.0,1641.55,13.14,41.0,M-SC,19.50,220.0,0.31,1.26,39.49,OX40N,ATH,CABLES
70,SIS,-1.94,-3.06,25.09,21.26,27006.0,-3396.0,107636.0,528.00,2567.36,42.0,H-SC,23.92,168.0,-0.13,0.73,60.04,OX40N,NTT,MISC
81,TTKPRESTIG,-4.81,-16.22,19.46,0.09,16431.0,-16341.0,84436.0,770.00,95.94,54.0,M-SC,13.01,250.0,-0.99,0.57,51.97,OX40N,NTT,DURABLES
16,CERA,0.42,-19.34,53.60,23.89,76046.0,-34027.0,141876.0,9475.00,-22.20,51.0,H-SC,13.73,153.0,-0.45,0.96,37.92,OX40N,NTT,CERAMICS
43,INDIGOPNTS,1.02,-20.90,26.45,0.02,36521.0,-36485.0,138074.0,1408.00,110.38,65.0,M-SC,4.19,222.0,-1.00,0.94,56.65,OX40N,NTT,PAINTS

In [14]:
# top 5 to book for rotation
df_tmp = df_portfolio_features[(df_portfolio_features['Current P/L%'] > 20) ].sort_values(by = 'CumlRnk', ascending=False)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
25,FINCABLES,0.67,25.58,65.56,107.91,121555.0,37766.0,185410.0,1641.55,13.14,41.0,M-SC,19.50,220.0,0.31,1.26,39.49,OX40N,ATH,CABLES
71,SONACOMS,0.82,33.21,4.12,38.69,5552.0,33591.0,134750.0,801.69,5.59,81.0,M-MC,29.00,193.0,6.05,0.91,91.18,AR,ATH,AUTO
55,MEDANTA,-1.85,20.31,5.66,27.12,12020.0,35849.0,212366.0,1486.00,16.68,65.0,X-SC,13.10,87.0,2.98,1.44,46.33,XY24,NTT,HEALTHCARE
59,QUESS,10.15,38.87,25.22,73.90,37403.0,41514.0,148307.0,424.00,-25.07,82.0,X-SC,37.17,80.0,1.11,1.00,102.17,XY24,NTT,MISC

In [15]:
# top 5 to monitor for exit
df_tmp = df_portfolio_features[~df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])]
df_tmp = df_tmp[(df_tmp['Current P/L%'] > 0) ].sort_values(by = 'Dev%_PE', ascending=False)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
72,STARHEALTH,1.19,17.27,25.58,47.26,84328.0,48541.0,329664.0,761.00,84.98,63.0,H-SC,18.57,173.0,0.58,2.23,42.54,XY24,NTT,INSURANCE
25,FINCABLES,0.67,25.58,65.56,107.91,121555.0,37766.0,185410.0,1641.55,13.14,41.0,M-SC,19.50,220.0,0.31,1.26,39.49,OX40N,ATH,CABLES
62,RECLTD,0.54,0.88,19.68,20.74,40336.0,1788.0,204958.0,446.00,11.33,68.0,M-MC,2.31,191.0,0.04,1.39,23.54,XY25,NTT,FINANCE
71,SONACOMS,0.82,33.21,4.12,38.69,5552.0,33591.0,134750.0,801.69,5.59,81.0,M-MC,29.00,193.0,6.05,0.91,91.18,AR,ATH,AUTO
89,ZYDUSLIFE,0.72,18.43,14.42,35.51,35791.0,38631.0,248205.0,1285.01,3.15,52.0,H-MC,16.75,120.0,1.08,1.68,30.62,AR,ATH,PHARMA

In [16]:
# top 5 to book for rotation from weak conviction
df_tmp = df_portfolio_features[~df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])]
df_tmp = df_tmp[~df_tmp['Criteria'].isin(['XY25','XY24','X40', 'X40N'])].sort_values(by = 'RRR Ind', ascending=False)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
71,SONACOMS,0.82,33.21,4.12,38.69,5552.0,33591.0,134750.0,801.69,5.59,81.0,M-MC,29.00,193.0,6.05,0.91,91.18,AR,ATH,AUTO
89,ZYDUSLIFE,0.72,18.43,14.42,35.51,35791.0,38631.0,248205.0,1285.01,3.15,52.0,H-MC,16.75,120.0,1.08,1.68,30.62,AR,ATH,PHARMA
25,FINCABLES,0.67,25.58,65.56,107.91,121555.0,37766.0,185410.0,1641.55,13.14,41.0,M-SC,19.50,220.0,0.31,1.26,39.49,OX40N,ATH,CABLES
54,MASFIN,-1.48,-1.87,23.88,21.57,22961.0,-1830.0,96150.0,397.04,-15.54,53.0,H-SC,1.91,167.0,-0.08,0.65,14.61,XR,ATH,FINANCE
70,SIS,-1.94,-3.06,25.09,21.26,27006.0,-3396.0,107636.0,528.00,2567.36,42.0,H-SC,23.92,168.0,-0.13,0.73,60.04,OX40N,NTT,MISC

In [17]:
# top 5 to accumulate based on lowest RSI_14
df_tmp = df_portfolio_features[df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])].sort_values(by = 'RSI_14', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
57,PGHH,-0.17,-35.68,105.23,32.01,144527.0,-76176.0,137344.0,17616.87,-56.52,34.0,X-MC,19.29,57.0,-0.53,0.93,0.00,X40,ATH,FMCG
85,VBL,-1.20,-10.02,50.28,35.22,142894.0,-31645.0,284197.0,669.42,-20.58,37.0,X-LC,7.47,13.0,-0.22,1.93,16.93,X40N,ATH,FMCG
39,ICICIGI,-1.17,-13.68,37.74,18.89,65187.0,-27382.0,172727.0,2244.41,-27.43,39.0,X-MC,7.88,66.0,-0.42,1.17,2.90,X40,ATH,INSURANCE
34,HDFCBANK,-0.58,-10.32,43.14,28.37,90869.0,-24247.0,210638.0,1073.00,-23.99,40.0,X-LC,10.15,26.0,-0.27,1.43,4.16,X40,BTT,BANKS
35,HDFCLIFE,0.41,-10.43,48.16,32.71,64618.0,-15626.0,134174.0,811.41,-30.12,40.0,X-LC,15.89,31.0,-0.24,0.91,0.80,X40,ATH,INSURANCE

In [18]:
# top 5 to accumulate based on Spread and CumlRnk
df_tmp = df_portfolio_features[df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])]
df_tmp = df_tmp[(df_tmp['CumlRnk'] < 100)].sort_values(by = 'Spread%', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
11,BERGEPAINT,0.51,-3.67,30.09,25.32,74708.0,-9466.0,248283.0,680.00,-8.95,59.0,X-MC,1.69,68.0,-0.13,1.68,29.22,XY24,NTT,PAINTS
19,COLPAL,-0.52,-21.25,77.61,39.86,160955.0,-55975.0,207390.0,3683.41,-4.73,50.0,X-MC,1.72,62.0,-0.35,1.41,17.31,XY25,ATH,FMCG
8,BAJAJHLDNG,3.55,1.57,25.66,27.63,49550.0,2978.0,193103.0,14274.15,-6.07,70.0,X-LC,2.25,28.0,0.06,1.31,31.49,X40,ATH,FINANCE
23,DMART,1.56,-5.42,37.03,29.60,87414.0,-13536.0,236064.0,5391.45,-20.23,42.0,X-LC,2.93,14.0,-0.15,1.60,7.90,X40N,ATH,FMCG
17,CIPLA,0.15,19.54,11.62,33.43,21275.0,29925.0,183086.0,1648.14,-7.62,63.0,X-LC,2.95,18.0,1.41,1.24,24.99,X40N,ATH,PHARMA

In [19]:
# top 5 to accumulate based on lowest Gained%
df_tmp = df_portfolio_features[df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])].sort_values(by = 'Gained%', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
57,PGHH,-0.17,-35.68,105.23,32.01,144527.0,-76176.0,137344.0,17616.87,-56.52,34.0,X-MC,19.29,57.0,-0.53,0.93,0.00,X40,ATH,FMCG
35,HDFCLIFE,0.41,-10.43,48.16,32.71,64618.0,-15626.0,134174.0,811.41,-30.12,40.0,X-LC,15.89,31.0,-0.24,0.91,0.80,X40,ATH,INSURANCE
47,ITC,-1.73,-25.91,60.68,19.06,152941.0,-88121.0,252045.0,452.00,-59.16,45.0,X-LC,12.26,1.0,-0.58,1.71,2.09,X40,NTT,FMCG
39,ICICIGI,-1.17,-13.68,37.74,18.89,65187.0,-27382.0,172727.0,2244.41,-27.43,39.0,X-MC,7.88,66.0,-0.42,1.17,2.90,X40,ATH,INSURANCE
64,RELIANCE,0.74,-16.39,49.87,25.30,83793.0,-32941.0,168022.0,1952.00,-18.49,52.0,X-LC,7.88,21.0,-0.39,1.14,3.47,XY25,BTT,REFINERIES

In [20]:
# top 5 to accumulate based on lowest CurrAlloc%
df_tmp = df_portfolio_features[df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])].sort_values(by = 'CurrAlloc%', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
10,BATAINDIA,0.16,-54.88,199.64,35.20,115907.0,-70612.0,58058.0,2096.00,-23.90,53.0,X-SC,16.34,91.0,-0.61,0.39,15.14,X40,NTT,FOOTWEAR
63,RELAXO,-0.58,-47.44,189.80,52.31,144798.0,-68870.0,76290.0,1176.00,-44.05,55.0,X-SC,9.54,92.0,-0.48,0.52,70.58,X40N,NTT,FOOTWEAR
35,HDFCLIFE,0.41,-10.43,48.16,32.71,64618.0,-15626.0,134174.0,811.41,-30.12,40.0,X-LC,15.89,31.0,-0.24,0.91,0.80,X40,ATH,INSURANCE
57,PGHH,-0.17,-35.68,105.23,32.01,144527.0,-76176.0,137344.0,17616.87,-56.52,34.0,X-MC,19.29,57.0,-0.53,0.93,0.00,X40,ATH,FMCG
28,GODREJCP,-0.39,-4.04,37.00,31.47,52768.0,-5998.0,142616.0,1469.04,0.87,55.0,X-LC,5.65,32.0,-0.11,0.97,9.43,X40N,ATH,FMCG

In [21]:
# top 5 to accumulate based on CumlRnk
df_tmp = df_portfolio_features.sort_values(by = 'CumlRnk', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
47,ITC,-1.73,-25.91,60.68,19.06,152941.0,-88121.0,252045.0,452.00,-59.16,45.0,X-LC,12.26,1.0,-0.58,1.71,2.09,X40,NTT,FMCG
77,TCS,-2.82,-30.62,79.02,24.20,253977.0,-141864.0,321409.0,4230.71,-41.33,62.0,X-LC,16.65,2.0,-0.56,2.18,19.86,X40,ATH,IT
45,INFY,-1.97,-22.91,74.14,34.24,178826.0,-71687.0,241201.0,1972.00,-39.40,58.0,X-LC,18.18,3.0,-0.40,1.63,14.93,X40,NTT,IT
79,TMPV,1.32,-22.92,77.20,36.58,211733.0,-81575.0,274266.0,600.00,-83.62,50.0,X-LC,6.57,4.0,-0.39,1.86,15.26,XY24,NTT,AUTO
58,PIDILITIND,-0.67,14.73,2.43,17.52,3934.0,20780.0,161890.0,1658.32,-19.59,61.0,X-LC,8.39,5.0,5.28,1.10,28.03,X40,ATH,CHEMICALS

In [22]:
# top 5 for average up
df_tmp = df_portfolio_features[(df_portfolio_features['Dev%_200'] > 5)].sort_values(by = 'CurrAlloc%', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
44,INDUSINDBK,-0.09,-25.40,78.13,32.89,45001.0,-19608.0,57598.0,1800.00,-371.01,54.0,L-MC,14.53,258.0,-0.44,0.39,42.00,XR,NTT,BANKS
63,RELAXO,-0.58,-47.44,189.80,52.31,144798.0,-68870.0,76290.0,1176.00,-44.05,55.0,X-SC,9.54,92.0,-0.48,0.52,70.58,X40N,NTT,FOOTWEAR
3,ALKYLAMINE,-0.13,-22.70,149.08,92.54,116349.0,-22918.0,78045.0,4520.85,-17.24,49.0,H-SC,12.94,142.0,-0.20,0.53,48.20,SR,ATH,CHEMICALS
81,TTKPRESTIG,-4.81,-16.22,19.46,0.09,16431.0,-16341.0,84436.0,770.00,95.94,54.0,M-SC,13.01,250.0,-0.99,0.57,51.97,OX40N,NTT,DURABLES
70,SIS,-1.94,-3.06,25.09,21.26,27006.0,-3396.0,107636.0,528.00,2567.36,42.0,H-SC,23.92,168.0,-0.13,0.73,60.04,OX40N,NTT,MISC

In [23]:
# top 5 RSP
df_tmp = df_portfolio_features.sort_values(by = 'RSP', ascending=False)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
33,HCLTECH,-0.48,-12.64,37.68,20.28,79638.0,-30571.0,211353.0,1853.42,-8.19,75.0,X-LC,15.17,8.0,-0.38,1.43,31.50,X40,ATH,IT
59,QUESS,10.15,38.87,25.22,73.90,37403.0,41514.0,148307.0,424.00,-25.07,82.0,X-SC,37.17,80.0,1.11,1.00,102.17,XY24,NTT,MISC
71,SONACOMS,0.82,33.21,4.12,38.69,5552.0,33591.0,134750.0,801.69,5.59,81.0,M-MC,29.00,193.0,6.05,0.91,91.18,AR,ATH,AUTO
22,DIXON,0.99,5.03,31.32,37.92,85787.0,13106.0,273904.0,18931.72,-55.33,67.0,X-MC,11.42,54.0,0.15,1.86,49.03,X40N,ATH,IT
77,TCS,-2.82,-30.62,79.02,24.20,253977.0,-141864.0,321409.0,4230.71,-41.33,62.0,X-LC,16.65,2.0,-0.56,2.18,19.86,X40,ATH,IT

In [24]:
# Top N allocation
df_tmp = df_portfolio_features.sort_values(by = 'CurrAlloc%', ascending=False)
top_n_values = [10, 25, 50]

sum_df = pd.DataFrame({
    'Top_N': top_n_values,
    'Sum_Alloc%': [df_tmp['CurrAlloc%'].head(n).sum() for n in top_n_values]
})

sum_df

   Top_N  Sum_Alloc%
0     10       19.21
1     25       42.68
2     50       73.76

In [25]:
# market-cap-wise allocation
df_tmp = df_portfolio_features[cols]
df_tmp.groupby(df_tmp['Conviction'].str[-2:])['CurrAlloc%'].sum().sort_values(ascending=False)

Conviction
SC    42.24
LC    31.90
MC    25.86
Name: CurrAlloc%, dtype: float64

In [26]:
# criteria-wise allocation
df_portfolio_features.groupby('Criteria')['CurrAlloc%'].sum().sort_values(ascending=False)

Criteria
XY24     26.02
X40      26.01
X40N     16.66
XR        9.21
AR        7.29
OX40N     7.19
XY25      6.72
SR        0.90
Name: CurrAlloc%, dtype: float64

In [27]:
# conviction-wise allocation
df_portfolio_features.groupby('Conviction')['CurrAlloc%'].sum().sort_values(ascending=False)

Conviction
X-LC    29.75
H-SC    20.66
X-MC    20.40
X-SC    10.66
M-SC    10.37
H-MC     2.77
M-MC     2.30
H-LC     1.28
M-LC     0.87
L-SC     0.55
L-MC     0.39
Name: CurrAlloc%, dtype: float64

In [28]:
# sector-wise stats
df_tmp = df_portfolio_features.groupby('Category')[['CurrAlloc%', 'Current', 'Current P/L', 'FTT Amt']].sum().sort_values(by=['Current', 'Current P/L'], ascending=False)
df_tmp['Current P/L%'] = round(df_tmp['Current P/L'] * 100 / df_tmp['Current'], 2)
df_tmp['FTT%'] = round(df_tmp['FTT Amt'] * 100 / df_tmp['Current'], 2)
cols = ['CurrAlloc%', 'Current P/L%', 'FTT%']
df_tmp[cols].sort_values(by=['CurrAlloc%'], ascending=False)

               CurrAlloc%  Current P/L%    FTT%
Category
FMCG                14.48        -23.96   67.43
IT                  10.96        -39.35  108.21
FINANCE              9.06        -17.09   66.07
MISC                 7.74        -17.34   67.69
AUTO                 7.28         -1.79   39.75
PAINTS               5.73        -16.51   36.38
BANKS                5.52        -11.57   63.13
PHARMA               5.48          8.40   19.32
INSURANCE            5.45         -2.95   37.68
ELECTRICAL           4.37         -9.53   47.87
CHEMICALS            2.24        -22.79   95.28
HEALTHCARE           2.20        -10.32   39.11
APPARELS             1.91          4.54   27.52
AC                   1.88        -14.95   46.11
BREWERIES            1.77         10.46    8.14
FOOTWEAR             1.76        -69.56  137.55
DURABLES             1.68        -55.59   93.45
TRAVEL               1.53        -98.45  197.81
CERAMICS             1.45        -43.23   86.74
ENGINEERING          1.28        -28.31   87.00
CABLES               1.26         20.37   65.56
JEWELLERY            1.17        -84.84  149.06
REFINERIES           1.14        -19.61   49.87
CEMENT               1.11        -64.17  186.99
ENTERTAINMENT        0.74        -78.45  184.88
TEXTILES             0.41        -50.85   93.86
HOTELS               0.40        -93.14  161.27

In [29]:
# money to be made criteria-wise
df_portfolio_features.groupby('Criteria')['FTT Amt'].agg(['sum', 'count']).sort_values(by='sum', ascending=False)

                sum  count
Criteria
XY24      3337281.0     20
X40       1825285.0     19
XR        1318396.0     13
AR        1097314.0      9
X40N      1003194.0     12
OX40N      729700.0     10
XY25       445123.0      5
SR         284036.0      2

In [30]:
# money to be made conviction-wise
df_portfolio_features.groupby('Conviction')['FTT Amt'].agg(['sum', 'count']).sort_values(by='sum', ascending=False)

                  sum  count
Conviction
H-SC        3301492.0     23
X-LC        1881291.0     21
X-MC        1445173.0     14
M-SC        1387250.0     14
X-SC        1228895.0      9
H-MC         288674.0      2
L-SC         209556.0      2
M-LC         163877.0      1
M-MC          45888.0      2
L-MC          45001.0      1
H-LC          43232.0      1

In [31]:
# money to be made criteria and conviction-wise
df_portfolio_features.groupby(['Conviction', 'Criteria'])['FTT Amt'].agg(['sum', 'count']).sort_values(by='sum', ascending=False)

                          sum  count
Conviction Criteria
H-SC       XY24      983143.0      5
X-LC       X40       966308.0     10
H-SC       AR        936437.0      5
M-SC       XY24      812706.0      6
H-SC       XR        788833.0      7
X-SC       XY24      717128.0      4
X-MC       X40       641588.0      7
X-LC       X40N      370375.0      6
           XY24      344909.0      2
X-MC       X40N      338441.0      3
H-SC       OX40N     309043.0      4
M-SC       OX40N     305912.0      5
X-SC       X40N      294378.0      3
H-SC       SR        284036.0      2
H-MC       XY24      252883.0      1
X-MC       XY25      238632.0      2
           XY24      226512.0      2
X-SC       X40       217389.0      2
M-SC       XR        192330.0      2
X-LC       XY25      166155.0      2
M-LC       XR        163877.0      1
L-SC       OX40N     114745.0      1
           XR         94811.0      1
M-SC       AR         76302.0      1
L-MC       XR         45001.0      1
H-LC       AR         43232.0      1
M-MC       XY25       40336.0      1
H-MC       AR         35791.0      1
X-LC       XR         33544.0      1
M-MC       AR          5552.0      1

In [32]:
# notebook execution time

end_time = time.time()
execution_time = round(end_time - start_time, 0)
print(f"Notebook execution time: {execution_time} seconds")

Notebook execution time: 31.0 seconds