<a href="https://colab.research.google.com/github/ankit-rathi/Quantvesting_v2/blob/main/myStocks_Portfolio_Analysis.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
'''
!pip install pandas==2.2.2 -qq
!pip install pyxirr -qq
!pip install ta -qq
!pip install yfinance==0.2.59 -qq
'''

'\n!pip install pandas==2.2.2 -qq\n!pip install pyxirr -qq\n!pip install ta -qq\n!pip install yfinance==0.2.59 -qq\n'

In [2]:
# import libraries

import numpy as np
import pandas as pd
import datetime
import warnings
warnings.filterwarnings('ignore')
import yfinance as yfin
import ta
import matplotlib.pyplot as plt
import requests

In [3]:
# notebook start time
import time
import datetime
import pytz

start_time = time.time()

# function to print date timestamp
def print_date_time():
  tz_NY = pytz.timezone('Asia/Kolkata')
  datetime_NY = datetime.datetime.now(tz_NY)
  print("Run date time (IST):", datetime_NY.strftime("%Y-%m-%d %H:%M:%S"))

In [4]:
# function to get booked and reserved amount
def get_amt():
  # fetch the JSON data from the URL
  url = "https://raw.githubusercontent.com/ankit-rathi/Tradevesting_v1/main/data/myPortfolioAmts.json"
  response = requests.get(url)
  pf_amts = response.json()  # parse the JSON data

  # extract values from the JSON
  py_booked_amt_dm = pf_amts["py_booked_amt_dm"]
  py_booked_amt_sv = pf_amts["py_booked_amt_sv"]
  cy_booked_amt_dm = pf_amts["cy_booked_amt_dm"]
  cy_booked_amt_sv = pf_amts["cy_booked_amt_sv"]
  reserve_amt_dm = pf_amts["reserve_amt_dm"]
  reserve_amt_sv = pf_amts["reserve_amt_sv"]

  # perform calculations
  py_booked_amt = py_booked_amt_dm + py_booked_amt_sv
  cy_booked_amt = cy_booked_amt_dm + cy_booked_amt_sv
  reserve_amt = reserve_amt_dm + reserve_amt_sv
  total_booked_amt = py_booked_amt + cy_booked_amt

  return total_booked_amt, reserve_amt, cy_booked_amt, py_booked_amt

gen_output = 0

In [5]:
# function to format the amount
def format_amt(number):
    abs_number = abs(number)

    if abs_number >= 1_00_00_000:  # Crores
        formatted_amt = f"{number / 1_00_00_000:.2f} C"
    elif abs_number >= 1_00_000:  # Lakhs
        formatted_amt = f"{number / 1_00_000:.2f} L"
    elif abs_number >= 1_000:  # Thousands
        formatted_amt = f"{number / 1_000:.2f} K"
    else:
        formatted_amt = f"{number:.2f}"

    return formatted_amt

# function to set start and end date
def get_start_end_date():
  start_date = (datetime.date.today() + datetime.timedelta(days=-365)).strftime('%Y-%m-%d')
  end_date = (datetime.date.today() + datetime.timedelta(days=1)).strftime('%Y-%m-%d')
  return start_date, end_date

# function to fetch my portfolio csv
def get_mypfs_df():
  mypfs_df = pd.read_csv('https://raw.githubusercontent.com/ankit-rathi/Tradevesting_v1/main/data/myPortfolioStocks.csv')
  return mypfs_df

# function to fetch my prospects csv
def get_mypps_df():
  mypps_df = pd.read_csv('https://raw.githubusercontent.com/ankit-rathi/Tradevesting_v1/main/data/myProspectsScrips.csv')
  return mypps_df

# function to fetch screener data
def get_myscreen_df():
  myscreen_df = pd.read_csv('https://raw.githubusercontent.com/ankit-rathi/Tradevesting_v1/main/data/myScreenerDB.csv')
  return myscreen_df

# function to fetch momentum data
def get_myinvmt_df():
  myinvmt_df = pd.read_csv('https://raw.githubusercontent.com/ankit-rathi/Tradevesting_v1/main/data/myInvestments.csv')
  return myinvmt_df

# function to get the stock ids
def get_stock_ids(df_pf):
  stock_n100 = df_pf['Symbol'].unique()

  exclude = ['CADILAHC','MMTC', 'MASFIN']

  stock_ids = df_pf[~df_pf['Symbol'].isin(exclude) ]['Symbol'].unique()

  #mypf = mypf[mypf.Forecast.notnull()]
  #stock_ids = mypf['Symbol'].unique()

  #stock_ids.sort()
  return stock_ids

# get features from screener data
def get_screener_features():
  myscreen_df = get_myscreen_df()
  cols = ['Symbol', 'EPS', 'MedPE', 'ROCE%', 'ROE%', 'CapType']
  return myscreen_df[cols]

# get relative strength
def get_relative_strength(stock_list):

    # Dictionary to store stock tickers and their corresponding percentage price change
    stock_changes = {}

    # Loop through each stock and fetch its price data
    for stock in stock_list:
        try:
            # Download the stock data for the given date range
            stock_data = yfin.Ticker(stock + '.NS').history(period='1mo', interval='1d')[map(str.title, ['open', 'close', 'low', 'high', 'volume'])]

            # Calculate the percentage change for the stock
            if len(stock_data) > 0:
                start_price = stock_data['Close'].iloc[0]
                end_price = stock_data['Close'].iloc[-1]
                percent_change = round(((end_price - start_price) / start_price) * 100, 2)
                stock_changes[stock] = percent_change
            else:
                stock_changes[stock] = np.nan  # If no data is available, set to NaN

        except Exception as e:
            print(f"Error fetching data for {stock}: {e}")
            stock_changes[stock] = np.nan

    # Create a DataFrame with stock tickers and their percentage changes
    df = pd.DataFrame(list(stock_changes.items()), columns=['Symbol', 'Percent_Change'])

    # Drop any stocks with missing data (NaN values)
    df = df.dropna()

    # Calculate the percentile rank based on percentage change
    df['RSP'] = round(df['Percent_Change'].rank(pct=True) * 100, 2)
    cols = ['Symbol', 'RSP']
    df = df[cols]
    # Sort by percentile rank (optional)
    df = df.sort_values(by='RSP', ascending=False).reset_index(drop=True)

    return df

In [6]:
# function to get stock technicals
def stock_prec_dev(stock_symbol):
    #stock_symbol = 'ULTRACEMCO.NS'
    short_window = 20
    mid_window = 50
    long_window = 200
    moving_avg = 'SMA'

    start = datetime.datetime(*map(int, start_date.split('-')))
    end = datetime.datetime(*map(int, end_date.split('-')))

    stock_df = yfin.Ticker(stock_symbol + '.NS').history(period='max', interval='1d')[map(str.title, ['open', 'close', 'low', 'high', 'volume'])]

    stock_df['Max'] = round(max(stock_df['Close']),2)
    stock_df = stock_df[(stock_df.index <= end_date) & (stock_df.index >= start_date)]
    stock_df['200_SMA'] = round(stock_df['Close'].rolling(window = 200, min_periods = 1).mean(),0)
    stock_df['Dev%_200'] = round((stock_df['Close'] - stock_df['200_SMA'])*100/stock_df['200_SMA'],2)
    stock_df.dropna(axis = 0, inplace = True) # remove any null rows

    stock_df['20_SMA'] = stock_df['Close'].rolling(window=20).mean()
    stock_df['50_SMA'] = stock_df['Close'].rolling(window=50).mean()
    stock_df['Symbol'] = stock_symbol

    stock_df['Close'] = round(stock_df['Close'],2)
    stock_df['Min'] = round(min(stock_df['Close']),2)
    stock_df['RSI_14'] = ta.momentum.RSIIndicator(close=stock_df['Close'], window=14).rsi()
    stock_df['RSI_14'] = round(stock_df['RSI_14'],0)
    stock_df['Prev_Close'] = stock_df['Close'].shift(1)
    stock_df.drop(['Open', 'Low', 'High', 'Volume'], axis=1, inplace=True)
    stock_df = stock_df.tail(1)

    max_SMA = max(stock_df['20_SMA'].item(), stock_df['50_SMA'].item(), stock_df['200_SMA'].item())
    min_SMA = min(stock_df['20_SMA'].item(), stock_df['50_SMA'].item(), stock_df['200_SMA'].item())
    ABS_Spread = max_SMA - min_SMA
    stock_df['Spread%'] = round((ABS_Spread / stock_df['200_SMA'].item()) * 100,2)

    return stock_df

# function to compute stock attributes
def get_common_features(stock_ids, df_mypf):

  df_prec_dev = pd.DataFrame()
  df_tmp = get_screener_features()
  df_rs = get_relative_strength(stock_ids)

  for stock_id in stock_ids:
      tmp = stock_prec_dev(stock_id)
      tmp = tmp.reset_index()
      df_prec_dev = pd.concat([df_prec_dev, tmp], ignore_index = True)
  df_prec_dev = pd.merge(df_prec_dev, df_mypf, on= 'Symbol')
  df_prec_dev = pd.merge(df_prec_dev, df_tmp, on= 'Symbol', how='left')
  df_prec_dev = pd.merge(df_prec_dev, df_rs, on= 'Symbol', how='left')
  #print(df_prec_dev.columns)
  df_prec_dev['Curr_PE'] = round(df_prec_dev['Close']/df_prec_dev['EPS'],1)
  df_prec_dev['Dev%_PE'] = round((df_prec_dev['Curr_PE'] - df_prec_dev['MedPE'])*100/df_prec_dev['MedPE'],2)
  df_prec_dev['Conviction'] = df_prec_dev['Conviction'] + '-' + df_prec_dev['CapType']
  return df_prec_dev

# function to arrange stock features
def arrange_features(df_stocks, common_cols, diff_cols):
  df_stocks_common = df_stocks[common_cols].drop_duplicates()
  df_stocks_diff = df_stocks[diff_cols]
  df_stocks_diff['Investment'] = df_stocks_diff['AvgCost'] * df_stocks_diff['Shares']
  df_stocks_diff = df_stocks_diff.groupby(['Symbol'])[['Shares', 'Investment']].aggregate(['sum']).reset_index()
  df_stocks_diff.columns = ['Symbol', 'Shares', 'Investment']
  df_stocks_diff['AvgCost'] = round(df_stocks_diff['Investment']/df_stocks_diff['Shares'],2)
  df_stocks = pd.merge(df_stocks_diff, df_stocks_common, on='Symbol')
  return df_stocks

# plot fact distribution across dimension
def plot_pie_chart(df, dimension, fact):
  # grouping the data by category and calculating the sum of fact for each type
  grouped_data = df.groupby(dimension)[fact].sum()

  # sorting the grouped data in descending order
  grouped_data = grouped_data.sort_values(ascending=False)

  # creating a pie chart
  grouped_data.plot.pie(autopct='%1.1f%%', startangle=90, figsize=(6, 6))

  # adding a title and displaying the plot
  plt.title(f'{dimension} {fact} Distribution')
  plt.ylabel('')  # To hide the y-label
  plt.show()

In [7]:
# function to get portfolio features

def get_portfolio_features(df_common_features):

  print_date_time()
  print('-------------------')

  #df_common_features["Target"] = df_common_features["Target"].fillna(df_common_features["Max"])
  df_common_features['NTT'] = np.where(df_common_features['Strategy']== 'NTT', df_common_features["Target"], df_common_features['Max'])
  df_common_features['LTT'] = np.where(df_common_features['Strategy']== 'BTT', df_common_features["Target"], df_common_features['Max'])
  df_common_features['BOL'] = df_common_features['Min']

  tmp_df = df_common_features[df_common_features['Symbol'].isin(mypf_df[mypf_df['InPortfolio'] != 'NA'].Symbol.values)]
  print('qualified stocks: '+str(len(tmp_df['Symbol'].unique())))
  tmp_df1 = tmp_df[tmp_df['LatestQtr'] == 1]
  print('with latest results: '+str(len(tmp_df1['Symbol'].unique())))
  tmp_df1 = tmp_df1[tmp_df1['StarStock'] == 1]
  print('still star stocks: '+str(len(tmp_df1['Symbol'].unique())))
  tmp_df['Investment'] = tmp_df['AvgCost'] * tmp_df['Shares']
  tmp_df['Current'] = round(tmp_df['Close'] * tmp_df['Shares'],0)
  tmp_df['Previous'] = tmp_df['Prev_Close'] * tmp_df['Shares']
  tmp_df['EstimatedST'] = tmp_df['NTT'] * tmp_df['Shares']
  tmp_df['EstimatedLT'] = tmp_df['LTT'] * tmp_df['Shares']
  tmp_df['Current P/L'] = round((tmp_df['Current'] - tmp_df['Investment']),0)
  tmp_df['Today P/L%'] = round((tmp_df['Current'] - tmp_df['Previous'])*100/tmp_df['Previous'],2)
  tmp_df['Current P/L%'] = round((tmp_df['Current'] - tmp_df['Investment'])*100/tmp_df['Investment'],2)
  tmp_df['EstimatedST P/L%'] = round((tmp_df['EstimatedST'] - tmp_df['Investment'])*100/tmp_df['Investment'],2)
  tmp_df['EstimatedLT P/L%'] = round((tmp_df['EstimatedLT'] - tmp_df['Investment'])*100/tmp_df['Investment'],2)
  tmp_df['NTT%'] = round((tmp_df['NTT'] - tmp_df['Close'])*100/tmp_df['Close'],2)
  tmp_df['LTT%'] = round((tmp_df['LTT'] - tmp_df['Close'])*100/tmp_df['Close'],2)
  tmp_df['Gained%'] = round((tmp_df['Close'] - tmp_df['BOL'])*100/tmp_df['BOL'],2)
  investment = round(sum(tmp_df['AvgCost']*tmp_df['Shares']),0)
  current = round(sum(tmp_df['Close']*tmp_df['Shares']),0)
  tmp_df['InitAlloc%'] = round(tmp_df['Investment']*100/investment,2)
  tmp_df['CurrAlloc%'] = round(tmp_df['Current']*100/current,2)
  tmp_df['FTT'] = tmp_df['LTT']
  tmp_df.loc[tmp_df['Strategy'] == 'NTT', 'FTT'] = tmp_df['NTT']
  tmp_df['FTT%'] = tmp_df['LTT%']
  tmp_df.loc[tmp_df['Strategy'] == 'NTT', 'FTT%'] = tmp_df['NTT%']
  tmp_df['FTT Amt'] = round(tmp_df['FTT%'] * tmp_df['Current']/100,0)
  tmp_df['OTT%'] = round((tmp_df['FTT'] - tmp_df['AvgCost'])*100/tmp_df['AvgCost'],2)
  tmp_df['RRR Ind'] = round(tmp_df['Current P/L']/tmp_df['FTT Amt'],2)
  tmp_df['Risk Ind'] = round(tmp_df['Current P/L%']*tmp_df['CurrAlloc%'],0)

  return tmp_df

# function to print portfolio features
def print_portfolio_stats(df_portfolio_features, myinvmt_df):
  from pyxirr import xirr

  total_booked_amt, reserve_amt, cy_booked_amt, py_booked_amt = get_amt()

  dates = myinvmt_df['Date'].values
  dates = np.append(dates, datetime.date.today().strftime('%d-%b-%y'))
  investment = myinvmt_df['Investment'].values
  dates= pd.to_datetime(dates)

  current = round(sum(df_portfolio_features['Close']*df_portfolio_features['Shares']),0) + reserve_amt
  investment_xirr = np.append(investment, current)
  cagr = round(xirr(pd.DataFrame({"dates": dates, "amounts": investment_xirr}))*100,2)

  investment = -sum(investment)
  invested = round(sum(df_portfolio_features['AvgCost']*df_portfolio_features['Shares']),0) + reserve_amt
  previous = round(sum(df_portfolio_features['Prev_Close']*df_portfolio_features['Shares']),0) + reserve_amt
  cy_invested = investment + py_booked_amt

  today_pnl_amount = current-previous
  today_pnl_percentage = round((current-previous)*100/previous,2)

  curr_pnl_amount = current-invested
  curr_pnl_percentage = round((curr_pnl_amount)*100/(cy_invested),2)

  cy_pnl_amount = cy_booked_amt + curr_pnl_amount
  cy_pnl_percentage = round((cy_pnl_amount)*100/cy_invested,2)

  overall_pnl_amount = total_booked_amt + curr_pnl_amount
  overall_pnl_percentage = round((overall_pnl_amount)*100/investment,2)

  estimate_st = round(sum(df_portfolio_features['FTT']*df_portfolio_features['Shares']),0)  + reserve_amt
  est_st_pnl_amount = estimate_st-current
  est_st_pnl_percentage = round((est_st_pnl_amount)*100/current,2)

  estimate_lt = round(sum(df_portfolio_features['LTT']*df_portfolio_features['Shares']),0)  + reserve_amt
  est_lt_pnl_amount = estimate_lt-current
  est_lt_pnl_percentage = round((est_lt_pnl_amount)*100/current,2)

  total_profit = round(sum(df_portfolio_features[df_portfolio_features['Current P/L%'] > 0]['Current']) - sum(df_portfolio_features[df_portfolio_features['Current P/L%'] > 0]['Investment']),0)
  total_loss = round(sum(df_portfolio_features[df_portfolio_features['Current P/L%'] < 0]['Current']) - sum(df_portfolio_features[df_portfolio_features['Current P/L%'] < 0]['Investment']),0)

  cy_booked_percentage = round((cy_booked_amt)*100/current,2)
  py_booked_percentage = round((py_booked_amt)*100/investment,2)
  total_booked_percentage = round((total_booked_amt)*100/investment,2)

  print('-------------------')
  print('Initial Investment: ', format_amt(investment))
  print('CY Investment: ', format_amt(cy_invested))
  print('Reserve: ', format_amt(reserve_amt))
  print('Current: ',  format_amt(current))
  print('-------------------')
  print('Today PnL: '+ '{} ({}%)'.format(format_amt(today_pnl_amount), today_pnl_percentage))
  print('Current PnL: '+ '{} ({}%)'.format(format_amt(curr_pnl_amount), curr_pnl_percentage))
  print('CY Booked + Current PnL: '+ '{} ({}%)'.format(format_amt(cy_pnl_amount), cy_pnl_percentage))
  print('-------------------')
  print('Total profit: ', format_amt(total_profit))
  print('Total loss: ', format_amt(total_loss))
  print('-------------------')
  print('Total Booked + Current PnL: '+ '{} ({}%)'.format(format_amt(overall_pnl_amount), overall_pnl_percentage))
  print('Total Booked PnL: '+ '{} ({}%)'.format(format_amt(total_booked_amt), total_booked_percentage))
  print('Curr Year Booked PnL: '+ '{} ({}%)'.format(format_amt(cy_booked_amt), cy_booked_percentage))
  print('Prev Year Booked PnL: '+ '{} ({}%)'.format(format_amt(py_booked_amt), py_booked_percentage))
  print('===================')
  print('Est FTT: ',  format_amt(estimate_st))
  print('Est FTT PnL: '+ '{} ({}%)'.format(format_amt(est_st_pnl_amount), est_st_pnl_percentage))

  print('===================')
  print('Deployed: ', format_amt(investment))

  print('Current: ', format_amt(current))

  print('CAGR/XIRR %: '+'{}%'.format(cagr))

In [8]:
# get start and end date
start_date, end_date = get_start_end_date()

# get portfolio and prospects data
mypfs_df = get_mypfs_df()
mypps_df = get_mypps_df()
myinvmt_df = get_myinvmt_df()

# merge above datasets
mypf_df = pd.merge(mypfs_df, mypps_df, on="Symbol")

# seggregate dm and sv portfolio
dm_pf = mypf_df[mypf_df['InPortfolio'] == 'DM']
sv_pf = mypf_df[mypf_df['InPortfolio'] == 'SV']

# build portfolio stock dataframe
dm_stocks = get_stock_ids(dm_pf)
sv_stocks = get_stock_ids(sv_pf)
df_stocks = pd.concat([dm_pf,sv_pf], ignore_index = True)

# arrange common and diff stock features
common_cols = ['Symbol', 'Target', 'Criteria', 'Strategy', 'CumlRnk', 'LatestQtr', 'StarStock', 'Conviction', 'Category', 'InFolio', 'XIRR', 'MBQ']
diff_cols = ['Symbol', 'AvgCost', 'Shares']
df_stocks = arrange_features(df_stocks, common_cols, diff_cols)

# get common features
stock_ids = df_stocks['Symbol'].values
df_common_features = get_common_features(stock_ids, df_stocks)

df_common_features.reset_index(drop=True, inplace=True)
df_common_features.drop(['Date'], axis=1, inplace=True)
# get and print portfolio features
df_portfolio_features = get_portfolio_features(df_common_features)

print_portfolio_stats(df_portfolio_features, myinvmt_df)

df = df_portfolio_features
#plot_pie_chart(df, 'CapType', 'Current')
list_ox40n = list(df[df['MBQ'].str.contains('OX40N', na=False)]['Symbol'].values)

Run date time (IST): 2026-04-09 14:37:23
-------------------
qualified stocks: 86
with latest results: 26
still star stocks: 16
-------------------
Initial Investment:  1.36 C
CY Investment:  1.62 C
Reserve:  1.61 K
Current:  1.36 C
-------------------
Today PnL: -40.05 K (-0.29%)
Current PnL: -41.10 L (-25.29%)
CY Booked + Current PnL: -25.21 L (-15.51%)
-------------------
Total profit:  1.26 L
Total loss:  -42.36 L
-------------------
Total Booked + Current PnL: 1.77 L (1.31%)
Total Booked PnL: 42.87 L (31.64%)
Curr Year Booked PnL: 15.89 L (11.68%)
Prev Year Booked PnL: 26.98 L (19.91%)
===================
Est FTT:  2.48 C
Est FTT PnL: 1.12 C (82.23%)
===================
Deployed:  1.36 C
Current:  1.36 C
CAGR/XIRR %: 0.19%

In [9]:
# top 5 near their targets
cols = ['Symbol', 'Today P/L%', 'Current P/L%', 'FTT%', 'OTT%', 'FTT Amt', 'Current P/L', 'Current', 'FTT', 'Dev%_PE', 'RSI_14','Conviction', 'Spread%',  'CumlRnk', 'RRR Ind', 'CurrAlloc%', 'Gained%', 'Criteria', 'Strategy', 'Category']
df_tmp = df_portfolio_features[~df_portfolio_features['Symbol'].isin(['ENRIN','BLUSPRING','DIGITIDE'])]
df_tmp = df_tmp.sort_values(by = 'FTT Amt', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
50,MASFIN,-0.34,-4.93,27.87,21.57,25961.0,-4830.0,93150.0,397.04,-18.25,54.0,H-SC,4.73,167.0,-0.19,0.68,22.04,XR,ATH,FINANCE
5,ANGELONE,5.18,15.36,7.65,24.18,26916.0,46838.0,351838.0,303.00,-83.35,72.0,X-SC,6.32,97.0,1.74,2.59,34.60,X40N,NTT,FINANCE
77,TTKPRESTIG,-2.18,-38.79,63.52,0.09,39184.0,-39089.0,61688.0,770.00,43.22,47.0,M-SC,21.86,250.0,-1.00,0.45,9.84,OX40N,NTT,DURABLES
67,SONACOMS,-1.84,-9.37,53.47,39.09,49022.0,-9477.0,91682.0,804.02,-28.17,56.0,M-MC,7.92,193.0,-0.19,0.67,29.70,AR,ATH,AUTO
37,ICICIGI,1.07,-6.28,27.34,19.34,51272.0,-12574.0,187535.0,2252.93,-21.06,46.0,X-MC,7.18,66.0,-0.25,1.38,4.74,X40,ATH,INSURANCE

In [10]:
# top 5 today
df_tmp = df_portfolio_features.sort_values(by = 'Today P/L%', ascending=False)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
5,ANGELONE,5.18,15.36,7.65,24.18,26916.0,46838.0,351838.0,303.00,-83.35,72.0,X-SC,6.32,97.0,1.74,2.59,34.60,X40N,NTT,FINANCE
22,DEN,3.03,-48.44,175.53,42.07,76447.0,-40912.0,43552.0,75.00,55.44,57.0,M-SC,21.90,235.0,-0.54,0.32,18.45,AR,NTT,ENTERTAINMENT
55,RAJESHEXPO,2.51,-80.01,400.48,0.07,109844.0,-109749.0,27428.0,518.00,905.05,45.0,L-SC,44.48,268.0,-1.00,0.20,28.76,OX40N,NTT,JEWELLERY
66,SIS,2.47,-30.86,75.39,21.26,57875.0,-34264.0,76768.0,528.00,1802.07,58.0,H-SC,14.51,168.0,-0.59,0.56,14.14,OX40N,NTT,MISC
36,HONAUT,1.90,-28.27,110.94,51.31,153458.0,-54513.0,138325.0,58357.33,-40.38,42.0,X-SC,18.93,90.0,-0.36,1.02,5.09,X40N,ATH,ELECTRICAL

In [11]:
# bottom 5 today
df_tmp = df_portfolio_features.sort_values(by = 'Today P/L%', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
46,JIOFIN,-3.64,-21.06,62.69,28.43,147629.0,-62836.0,235491.0,387.0,-22.30,48.0,X-LC,19.44,34.0,-0.43,1.73,7.84,XY24,BTT,FINANCE
41,INDIGOPNTS,-3.01,-44.09,78.91,0.02,77007.0,-76971.0,97588.0,1408.0,49.00,45.0,M-SC,29.63,222.0,-1.00,0.72,10.72,OX40N,NTT,PAINTS
83,WHIRLPOOL,-2.93,-34.22,176.54,81.92,133319.0,-39280.0,75518.0,2270.0,-61.52,46.0,M-SC,25.91,210.0,-0.29,0.56,6.08,XR,NTT,DURABLES
34,HDFCBANK,-2.59,-4.89,34.97,28.37,78121.0,-11490.0,223395.0,1073.0,-19.05,46.0,X-LC,16.75,26.0,-0.15,1.64,8.67,X40,BTT,BANKS
42,INDUSINDBK,-2.57,-39.87,120.99,32.89,56171.0,-30780.0,46426.0,1800.0,-318.49,46.0,L-MC,7.86,258.0,-0.55,0.34,20.04,XR,NTT,BANKS

In [12]:
# top 5 to exit based on CumlRnk
df_tmp = df_portfolio_features[~df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])]
df_tmp = df_tmp[(df_tmp['Current P/L%'] > -1) & (df_tmp['Current P/L%'] < 1)].sort_values(by = 'CumlRnk', ascending=False)
df_tmp[cols].head()

Empty DataFrame
Columns: [Symbol, Today P/L%, Current P/L%, FTT%, OTT%, FTT Amt, Current P/L, Current, FTT, Dev%_PE, RSI_14, Conviction, Spread%, CumlRnk, RRR Ind, CurrAlloc%, Gained%, Criteria, Strategy, Category]
Index: []

In [13]:
# OX40N stocks to exit
df_tmp = df_portfolio_features[(df_portfolio_features['Symbol'].isin(list_ox40n))].sort_values(by = 'Current P/L%', ascending=False)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
26,FINCABLES,-0.46,6.92,94.45,107.91,149103.0,10221.0,157865.0,1641.55,-3.60,52.0,M-SC,2.20,220.0,0.07,1.16,18.77,OX40N,ATH,CABLES
66,SIS,2.47,-30.86,75.39,21.26,57875.0,-34264.0,76768.0,528.00,1802.07,58.0,H-SC,14.51,168.0,-0.59,0.56,14.14,OX40N,NTT,MISC
18,CERA,-0.75,-34.42,88.91,23.89,102566.0,-60544.0,115359.0,9475.00,-36.75,59.0,H-SC,18.00,153.0,-0.59,0.85,10.86,OX40N,NTT,CERAMICS
72,TATAELXSI,0.21,-35.96,106.15,32.03,89625.0,-47403.0,84432.0,9161.00,-19.86,53.0,H-SC,21.05,158.0,-0.53,0.62,11.75,OX40N,NTT,IT
48,KANSAINER,-1.75,-38.30,83.92,13.47,139621.0,-103293.0,166374.0,340.00,-47.05,52.0,H-SC,23.44,162.0,-0.74,1.22,16.21,XY24,NTT,PAINTS

In [14]:
# top 5 to book for rotation
df_tmp = df_portfolio_features[(df_portfolio_features['Current P/L%'] > 20) ].sort_values(by = 'CumlRnk', ascending=False)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
1,ABB,0.46,21.0,20.3,45.57,64262.0,54941.0,316560.0,7934.0,-22.27,65.0,H-MC,14.84,125.0,0.85,2.33,40.57,AR,NTT,ELECTRICAL

In [15]:
# top 5 to monitor for exit
df_tmp = df_portfolio_features[~df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])]
df_tmp = df_tmp[(df_tmp['Current P/L%'] > 0) ].sort_values(by = 'Dev%_PE', ascending=False)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
26,FINCABLES,-0.46,6.92,94.45,107.91,149103.0,10221.0,157865.0,1641.55,-3.60,52.0,M-SC,2.20,220.0,0.07,1.16,18.77,OX40N,ATH,CABLES
1,ABB,0.46,21.00,20.30,45.57,64262.0,54941.0,316560.0,7934.00,-22.27,65.0,H-MC,14.84,125.0,0.85,2.33,40.57,AR,NTT,ELECTRICAL

In [16]:
# top 5 to book for rotation from weak conviction
df_tmp = df_portfolio_features[~df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])]
df_tmp = df_tmp[~df_tmp['Criteria'].isin(['XY25','XY24','X40', 'X40N'])].sort_values(by = 'RRR Ind', ascending=False)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
1,ABB,0.46,21.00,20.30,45.57,64262.0,54941.0,316560.0,7934.00,-22.27,65.0,H-MC,14.84,125.0,0.85,2.33,40.57,AR,NTT,ELECTRICAL
26,FINCABLES,-0.46,6.92,94.45,107.91,149103.0,10221.0,157865.0,1641.55,-3.60,52.0,M-SC,2.20,220.0,0.07,1.16,18.77,OX40N,ATH,CABLES
40,INDIAMART,0.04,-9.93,129.51,106.72,143870.0,-12248.0,111088.0,4810.62,-59.38,52.0,H-SC,12.96,140.0,-0.09,0.82,7.33,AR,ATH,MISC
85,ZYDUSLIFE,1.07,-4.98,42.74,35.63,85109.0,-10442.0,199132.0,1286.17,-17.12,53.0,H-MC,5.98,120.0,-0.12,1.46,10.86,AR,ATH,PHARMA
67,SONACOMS,-1.84,-9.37,53.47,39.09,49022.0,-9477.0,91682.0,804.02,-28.17,56.0,M-MC,7.92,193.0,-0.19,0.67,29.70,AR,ATH,AUTO

In [17]:
# top 5 to accumulate based on lowest RSI_14
df_tmp = df_portfolio_features[df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])].sort_values(by = 'RSI_14', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
53,PGHH,-0.05,-28.22,83.90,32.01,128595.0,-60248.0,153272.0,17616.87,-51.42,34.0,X-MC,20.61,57.0,-0.47,1.13,4.83,X40,ATH,FMCG
21,DABUR,0.29,-16.22,71.53,43.70,148655.0,-40246.0,207822.0,735.00,-23.90,40.0,X-MC,13.12,70.0,-0.27,1.53,4.40,XY24,BTT,FMCG
38,ICICIPRULI,0.06,-10.33,45.78,30.73,80874.0,-20346.0,176659.0,790.00,-34.44,41.0,X-MC,11.28,78.0,-0.25,1.30,7.65,X40,ATH,INSURANCE
27,GILLETTE,-1.22,-10.31,44.63,29.72,101636.0,-26166.0,227730.0,10978.86,-31.02,41.0,X-SC,13.49,83.0,-0.26,1.67,4.65,X40,ATH,FMCG
78,UNITDSPR,-0.14,-8.39,31.83,20.77,68276.0,-19643.0,214501.0,1644.00,-18.80,41.0,X-MC,4.92,64.0,-0.29,1.58,2.32,X40N,NTT,BREWERIES

In [18]:
# top 5 to accumulate based on Spread and CumlRnk
df_tmp = df_portfolio_features[df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])]
df_tmp = df_tmp[(df_tmp['CumlRnk'] < 100)].sort_values(by = 'Spread%', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
65,SIEMENS,-0.41,-13.67,45.39,25.51,72919.0,-25445.0,160650.0,4671.50,35.03,55.0,H-LC,1.14,51.0,-0.35,1.18,18.31,AR,ATH,ELECTRICAL
59,RELIANCE,-1.42,-14.71,46.91,25.30,80405.0,-29561.0,171402.0,1952.00,-16.96,41.0,X-LC,4.71,21.0,-0.37,1.26,12.54,XY25,BTT,REFINERIES
78,UNITDSPR,-0.14,-8.39,31.83,20.77,68276.0,-19643.0,214501.0,1644.00,-18.80,41.0,X-MC,4.92,64.0,-0.29,1.58,2.32,X40N,NTT,BREWERIES
24,DMART,0.47,5.51,22.83,29.60,60123.0,13752.0,263352.0,5391.45,-11.04,67.0,X-LC,5.05,14.0,0.23,1.94,20.37,X40N,ATH,FMCG
82,VOLTAS,0.55,-0.51,45.95,45.20,87652.0,-987.0,190755.0,1856.00,13.96,41.0,X-MC,5.57,79.0,-0.01,1.40,6.25,XY25,NTT,AC

In [19]:
# top 5 to accumulate based on lowest Gained%
df_tmp = df_portfolio_features[df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])].sort_values(by = 'Gained%', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
2,ABBOTINDIA,-0.21,-13.47,36.44,18.07,56398.0,-24085.0,154770.0,35195.0,-26.29,43.0,X-MC,11.24,58.0,-0.43,1.14,1.22,X40,ATH,PHARMA
78,UNITDSPR,-0.14,-8.39,31.83,20.77,68276.0,-19643.0,214501.0,1644.0,-18.80,41.0,X-MC,4.92,64.0,-0.29,1.58,2.32,X40N,NTT,BREWERIES
8,AWL,-0.60,-38.74,172.63,67.02,376822.0,-138026.0,218283.0,485.0,-67.02,43.0,X-SC,25.33,81.0,-0.37,1.60,3.25,XY24,NTT,FMCG
35,HINDUNILVR,-0.89,-17.28,37.42,13.67,79570.0,-44423.0,212640.0,2922.0,-38.66,46.0,X-LC,11.85,9.0,-0.56,1.56,3.62,XY25,NTT,FMCG
21,DABUR,0.29,-16.22,71.53,43.70,148655.0,-40246.0,207822.0,735.0,-23.90,40.0,X-MC,13.12,70.0,-0.27,1.53,4.40,XY24,BTT,FMCG

In [20]:
# top 5 to accumulate based on lowest CurrAlloc%
df_tmp = df_portfolio_features[df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])].sort_values(by = 'CurrAlloc%', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
58,RELAXO,0.47,-63.55,317.85,52.31,168178.0,-92249.0,52911.0,1176.00,-61.18,46.0,X-SC,33.05,92.0,-0.55,0.39,18.30,X40N,NTT,FOOTWEAR
12,BATAINDIA,-0.30,-54.71,198.55,35.20,115695.0,-70400.0,58270.0,2096.00,-23.61,51.0,X-SC,34.31,91.0,-0.61,0.43,15.56,X40,NTT,FOOTWEAR
54,QUESS,0.21,-22.38,124.04,73.90,102819.0,-23901.0,82892.0,424.00,-58.13,55.0,X-SC,22.00,80.0,-0.23,0.61,11.51,XY24,NTT,MISC
36,HONAUT,1.90,-28.27,110.94,51.31,153458.0,-54513.0,138325.0,58357.33,-40.38,42.0,X-SC,18.93,90.0,-0.36,1.02,5.09,X40N,ATH,ELECTRICAL
53,PGHH,-0.05,-28.22,83.90,32.01,128595.0,-60248.0,153272.0,17616.87,-51.42,34.0,X-MC,20.61,57.0,-0.47,1.13,4.83,X40,ATH,FMCG

In [21]:
# top 5 to accumulate based on CumlRnk
df_tmp = df_portfolio_features.sort_values(by = 'CumlRnk', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
45,ITC,0.05,-20.29,49.37,19.06,133857.0,-69036.0,271130.0,452.00,-56.33,50.0,X-LC,19.60,1.0,-0.52,1.99,5.18,X40,NTT,FMCG
73,TCS,0.74,-24.32,67.24,26.57,235758.0,-112651.0,350622.0,4311.59,-36.09,57.0,X-LC,18.28,2.0,-0.48,2.58,9.43,X40,ATH,IT
43,INFY,-1.43,-9.67,48.62,34.24,137415.0,-30258.0,282630.0,1972.00,-28.88,53.0,X-LC,14.40,3.0,-0.22,2.08,8.69,X40,NTT,IT
75,TMPV,-0.75,-24.37,80.59,36.58,216885.0,-86719.0,269122.0,600.00,-84.72,53.0,X-LC,12.41,4.0,-0.40,1.98,12.17,XY24,NTT,AUTO
33,HCLTECH,-0.21,-5.39,30.89,23.83,70704.0,-13034.0,228890.0,1908.19,-0.74,61.0,X-LC,10.15,8.0,-0.18,1.68,11.14,X40,ATH,IT

In [22]:
# top 5 for average up
df_tmp = df_portfolio_features[(df_portfolio_features['Dev%_200'] > 5)].sort_values(by = 'CurrAlloc%', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
67,SONACOMS,-1.84,-9.37,53.47,39.09,49022.0,-9477.0,91682.0,804.02,-28.17,56.0,M-MC,7.92,193.0,-0.19,0.67,29.70,AR,ATH,AUTO
24,DMART,0.47,5.51,22.83,29.60,60123.0,13752.0,263352.0,5391.45,-11.04,67.0,X-LC,5.05,14.0,0.23,1.94,20.37,X40N,ATH,FMCG
1,ABB,0.46,21.00,20.30,45.57,64262.0,54941.0,316560.0,7934.00,-22.27,65.0,H-MC,14.84,125.0,0.85,2.33,40.57,AR,NTT,ELECTRICAL
5,ANGELONE,5.18,15.36,7.65,24.18,26916.0,46838.0,351838.0,303.00,-83.35,72.0,X-SC,6.32,97.0,1.74,2.59,34.60,X40N,NTT,FINANCE

In [23]:
# top 5 RSP
df_tmp = df_portfolio_features.sort_values(by = 'RSP', ascending=False)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
5,ANGELONE,5.18,15.36,7.65,24.18,26916.0,46838.0,351838.0,303.00,-83.35,72.0,X-SC,6.32,97.0,1.74,2.59,34.60,X40N,NTT,FINANCE
80,VALIANTORG,0.45,-44.84,215.73,74.15,194681.0,-73362.0,90243.0,838.00,-262.20,61.0,H-SC,23.89,145.0,-0.38,0.66,34.29,XR,NTT,CHEMICALS
52,PAGEIND,1.66,-6.34,43.19,34.11,108567.0,-17009.0,251370.0,51418.65,-32.80,71.0,X-MC,17.89,55.0,-0.16,1.85,18.91,X40,ATH,APPARELS
30,HAPPSTMNDS,-1.23,-52.85,292.03,84.85,176480.0,-67733.0,60432.0,1480.71,-44.02,48.0,H-SC,23.02,152.0,-0.38,0.44,11.91,AR,ATH,IT
24,DMART,0.47,5.51,22.83,29.60,60123.0,13752.0,263352.0,5391.45,-11.04,67.0,X-LC,5.05,14.0,0.23,1.94,20.37,X40N,ATH,FMCG

In [24]:
# Top N allocation
df_tmp = df_portfolio_features.sort_values(by = 'CurrAlloc%', ascending=False)
top_n_values = [10, 25, 50]

sum_df = pd.DataFrame({
    'Top_N': top_n_values,
    'Sum_Alloc%': [df_tmp['CurrAlloc%'].head(n).sum() for n in top_n_values]
})

sum_df

   Top_N  Sum_Alloc%
0     10       21.27
1     25       46.13
2     50       77.87

In [25]:
# market-cap-wise allocation
df_tmp = df_portfolio_features[cols]
df_tmp.groupby(df_tmp['Conviction'].str[-2:])['CurrAlloc%'].sum().sort_values(ascending=False)

Conviction
SC    44.98
MC    29.43
LC    25.57
Name: CurrAlloc%, dtype: float64

In [26]:
# criteria-wise allocation
df_portfolio_features.groupby('Criteria')['CurrAlloc%'].sum().sort_values(ascending=False)

Criteria
XY24     27.09
X40      25.14
X40N     15.59
AR        9.21
XR        8.42
XY25      7.02
OX40N     6.72
SR        0.79
Name: CurrAlloc%, dtype: float64

In [27]:
# conviction-wise allocation
df_portfolio_features.groupby('Conviction')['CurrAlloc%'].sum().sort_values(ascending=False)

Conviction
X-LC    23.36
H-SC    22.04
X-MC    21.96
X-SC    12.39
M-SC     9.99
H-MC     5.06
M-MC     2.07
H-LC     1.18
M-LC     1.03
L-SC     0.56
L-MC     0.34
Name: CurrAlloc%, dtype: float64

In [28]:
# sector-wise stats
df_tmp = df_portfolio_features.groupby('Category')[['CurrAlloc%', 'Current', 'Current P/L', 'FTT Amt']].sum().sort_values(by=['Current', 'Current P/L'], ascending=False)
df_tmp['Current P/L%'] = round(df_tmp['Current P/L'] * 100 / df_tmp['Current'], 2)
df_tmp['FTT%'] = round(df_tmp['FTT Amt'] * 100 / df_tmp['Current'], 2)
cols = ['CurrAlloc%', 'Current P/L%', 'FTT%']
df_tmp[cols].sort_values(by=['CurrAlloc%'], ascending=False)

               CurrAlloc%  Current P/L%    FTT%
Category
FMCG                14.80        -24.03   68.04
FINANCE             13.54        -16.74   64.31
IT                  12.00        -37.95  108.15
MISC                 7.11        -38.53   98.71
ELECTRICAL           6.47        -10.17   52.35
PAINTS               5.16        -40.55   64.95
BANKS                4.62        -22.50   84.68
INSURANCE            4.54         -9.84   47.43
PHARMA               3.99         -8.26   42.34
AUTO                 3.73        -28.91   80.06
HEALTHCARE           1.94        -35.92   71.39
AC                   1.93        -21.50   54.45
APPARELS             1.85         -6.77   43.19
TRAVEL               1.83        -79.18  168.89
FOOTWEAR             1.81        -79.22  151.09
DURABLES             1.72        -65.07  105.23
BREWERIES            1.58         -9.16   31.83
REALTY               1.43        -14.09   32.83
CERAMICS             1.35        -67.51  118.40
REFINERIES           1.26        -17.25   46.91
CEMENT               1.22        -61.10  181.61
ENGINEERING          1.18        -50.58  119.45
CABLES               1.16          6.47   94.45
CHEMICALS            1.09        -77.33  222.01
JEWELLERY            1.07       -120.52  197.14
ENTERTAINMENT        0.79        -78.89  185.57
TEXTILES             0.45        -50.00   92.77
HOTELS               0.36       -133.39  215.71

In [29]:
# money to be made criteria-wise
df_portfolio_features.groupby('Criteria')['FTT Amt'].agg(['sum', 'count']).sort_values(by='sum', ascending=False)

                sum  count
Criteria
XY24      3910972.0     21
X40       1756501.0     16
XR        1346183.0     12
AR        1317791.0     10
X40N      1180426.0     10
OX40N      876457.0     10
XY25       485323.0      5
SR         311472.0      2

In [30]:
# money to be made conviction-wise
df_portfolio_features.groupby('Conviction')['FTT Amt'].agg(['sum', 'count']).sort_values(by='sum', ascending=False)

                  sum  count
Conviction
H-SC        3794482.0     24
X-MC        1749183.0     15
X-LC        1598436.0     13
M-SC        1556536.0     14
X-SC        1497067.0     10
H-MC         390202.0      3
L-SC         214793.0      2
M-LC         151378.0      1
M-MC         103958.0      2
H-LC          72919.0      1
L-MC          56171.0      1

In [31]:
# money to be made criteria and conviction-wise
df_portfolio_features.groupby(['Conviction', 'Criteria'])['FTT Amt'].agg(['sum', 'count']).sort_values(by='sum', ascending=False)

                           sum  count
Conviction Criteria
H-SC       XY24      1297919.0      6
           AR         970032.0      5
M-SC       XY24       894850.0      6
X-LC       X40        855547.0      7
X-SC       XY24       847622.0      4
H-SC       XR         843310.0      7
X-MC       X40        683623.0      7
           X40N       529912.0      4
X-SC       X40N       432114.0      4
M-SC       OX40N      394864.0      5
H-SC       OX40N      371749.0      4
X-LC       XY24       364514.0      2
H-SC       SR         311472.0      2
X-MC       XY25       270412.0      2
           XY24       265236.0      2
H-MC       XY24       240831.0      1
X-LC       X40N       218400.0      2
X-SC       X40        217331.0      2
M-SC       XR         190375.0      2
X-LC       XY25       159975.0      2
M-LC       XR         151378.0      1
H-MC       AR         149371.0      2
L-SC       OX40N      109844.0      1
           XR         104949.0      1
M-SC       AR          76447.0      1
H-LC       AR          72919.0      1
L-MC       XR          56171.0      1
M-MC       XY25        54936.0      1
           AR          49022.0      1

In [32]:
# notebook execution time

end_time = time.time()
execution_time = round(end_time - start_time, 0)
print(f"Notebook execution time: {execution_time} seconds")

Notebook execution time: 41.0 seconds