<a href="https://colab.research.google.com/github/ankit-rathi/Quantvesting_v2/blob/main/myStocks_Portfolio_Analysis.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
'''
!pip install pandas==2.2.2 -qq
!pip install pyxirr -qq
!pip install ta -qq
!pip install yfinance==0.2.59 -qq
'''

'\n!pip install pandas==2.2.2 -qq\n!pip install pyxirr -qq\n!pip install ta -qq\n!pip install yfinance==0.2.59 -qq\n'

In [2]:
# import libraries

import numpy as np
import pandas as pd
import datetime
import warnings
warnings.filterwarnings('ignore')
import yfinance as yfin
import ta
import matplotlib.pyplot as plt
import requests

In [3]:
# notebook start time
import time
import datetime
import pytz

start_time = time.time()

# function to print date timestamp
def print_date_time():
  tz_NY = pytz.timezone('Asia/Kolkata')
  datetime_NY = datetime.datetime.now(tz_NY)
  print("Run date time (IST):", datetime_NY.strftime("%Y-%m-%d %H:%M:%S"))

In [4]:
# function to get booked and reserved amount
def get_amt():
  # fetch the JSON data from the URL
  url = "https://raw.githubusercontent.com/ankit-rathi/Tradevesting_v1/main/data/myPortfolioAmts.json"
  response = requests.get(url)
  pf_amts = response.json()  # parse the JSON data

  # extract values from the JSON
  py_booked_amt_dm = pf_amts["py_booked_amt_dm"]
  py_booked_amt_sv = pf_amts["py_booked_amt_sv"]
  cy_booked_amt_dm = pf_amts["cy_booked_amt_dm"]
  cy_booked_amt_sv = pf_amts["cy_booked_amt_sv"]
  reserve_amt_dm = pf_amts["reserve_amt_dm"]
  reserve_amt_sv = pf_amts["reserve_amt_sv"]

  # perform calculations
  py_booked_amt = py_booked_amt_dm + py_booked_amt_sv
  cy_booked_amt = cy_booked_amt_dm + cy_booked_amt_sv
  reserve_amt = reserve_amt_dm + reserve_amt_sv
  total_booked_amt = py_booked_amt + cy_booked_amt

  return total_booked_amt, reserve_amt, cy_booked_amt, py_booked_amt

gen_output = 0

In [5]:
# function to format the amount
def format_amt(number):
    abs_number = abs(number)

    if abs_number >= 1_00_00_000:  # Crores
        formatted_amt = f"{number / 1_00_00_000:.2f} C"
    elif abs_number >= 1_00_000:  # Lakhs
        formatted_amt = f"{number / 1_00_000:.2f} L"
    elif abs_number >= 1_000:  # Thousands
        formatted_amt = f"{number / 1_000:.2f} K"
    else:
        formatted_amt = f"{number:.2f}"

    return formatted_amt

# function to set start and end date
def get_start_end_date():
  start_date = (datetime.date.today() + datetime.timedelta(days=-365)).strftime('%Y-%m-%d')
  end_date = (datetime.date.today() + datetime.timedelta(days=1)).strftime('%Y-%m-%d')
  return start_date, end_date

# function to fetch my portfolio csv
def get_mypfs_df():
  mypfs_df = pd.read_csv('https://raw.githubusercontent.com/ankit-rathi/Tradevesting_v1/main/data/myPortfolioStocks.csv')
  return mypfs_df

# function to fetch my prospects csv
def get_mypps_df():
  mypps_df = pd.read_csv('https://raw.githubusercontent.com/ankit-rathi/Tradevesting_v1/main/data/myProspectsScrips.csv')
  return mypps_df

# function to fetch screener data
def get_myscreen_df():
  myscreen_df = pd.read_csv('https://raw.githubusercontent.com/ankit-rathi/Tradevesting_v1/main/data/myScreenerDB.csv')
  return myscreen_df

# function to fetch momentum data
def get_myinvmt_df():
  myinvmt_df = pd.read_csv('https://raw.githubusercontent.com/ankit-rathi/Tradevesting_v1/main/data/myInvestments.csv')
  return myinvmt_df

# function to get the stock ids
def get_stock_ids(df_pf):
  stock_n100 = df_pf['Symbol'].unique()

  exclude = ['CADILAHC','MMTC', 'MASFIN']

  stock_ids = df_pf[~df_pf['Symbol'].isin(exclude) ]['Symbol'].unique()

  #mypf = mypf[mypf.Forecast.notnull()]
  #stock_ids = mypf['Symbol'].unique()

  #stock_ids.sort()
  return stock_ids

# get features from screener data
def get_screener_features():
  myscreen_df = get_myscreen_df()
  cols = ['Symbol', 'EPS', 'MedPE', 'ROCE%', 'ROE%', 'CapType']
  return myscreen_df[cols]

# get relative strength
def get_relative_strength(stock_list):

    # Dictionary to store stock tickers and their corresponding percentage price change
    stock_changes = {}

    # Loop through each stock and fetch its price data
    for stock in stock_list:
        try:
            # Download the stock data for the given date range
            stock_data = yfin.Ticker(stock + '.NS').history(period='1mo', interval='1d')[map(str.title, ['open', 'close', 'low', 'high', 'volume'])]

            # Calculate the percentage change for the stock
            if len(stock_data) > 0:
                start_price = stock_data['Close'].iloc[0]
                end_price = stock_data['Close'].iloc[-1]
                percent_change = round(((end_price - start_price) / start_price) * 100, 2)
                stock_changes[stock] = percent_change
            else:
                stock_changes[stock] = np.nan  # If no data is available, set to NaN

        except Exception as e:
            print(f"Error fetching data for {stock}: {e}")
            stock_changes[stock] = np.nan

    # Create a DataFrame with stock tickers and their percentage changes
    df = pd.DataFrame(list(stock_changes.items()), columns=['Symbol', 'Percent_Change'])

    # Drop any stocks with missing data (NaN values)
    df = df.dropna()

    # Calculate the percentile rank based on percentage change
    df['RSP'] = round(df['Percent_Change'].rank(pct=True) * 100, 2)
    cols = ['Symbol', 'RSP']
    df = df[cols]
    # Sort by percentile rank (optional)
    df = df.sort_values(by='RSP', ascending=False).reset_index(drop=True)

    return df

In [6]:
# function to get stock technicals
def stock_prec_dev(stock_symbol):
    #stock_symbol = 'ULTRACEMCO.NS'
    short_window = 20
    mid_window = 50
    long_window = 200
    moving_avg = 'SMA'

    start = datetime.datetime(*map(int, start_date.split('-')))
    end = datetime.datetime(*map(int, end_date.split('-')))

    stock_df = yfin.Ticker(stock_symbol + '.NS').history(period='max', interval='1d')[map(str.title, ['open', 'close', 'low', 'high', 'volume'])]

    stock_df['Max'] = round(max(stock_df['Close']),2)
    stock_df = stock_df[(stock_df.index <= end_date) & (stock_df.index >= start_date)]
    stock_df['200_SMA'] = round(stock_df['Close'].rolling(window = 200, min_periods = 1).mean(),0)
    stock_df['Dev%_200'] = round((stock_df['Close'] - stock_df['200_SMA'])*100/stock_df['200_SMA'],2)
    stock_df.dropna(axis = 0, inplace = True) # remove any null rows

    stock_df['20_SMA'] = stock_df['Close'].rolling(window=20).mean()
    stock_df['50_SMA'] = stock_df['Close'].rolling(window=50).mean()
    stock_df['Symbol'] = stock_symbol

    stock_df['Close'] = round(stock_df['Close'],2)
    stock_df['Min'] = round(min(stock_df['Close']),2)
    stock_df['RSI_14'] = ta.momentum.RSIIndicator(close=stock_df['Close'], window=14).rsi()
    stock_df['RSI_14'] = round(stock_df['RSI_14'],0)
    stock_df['Prev_Close'] = stock_df['Close'].shift(1)
    stock_df.drop(['Open', 'Low', 'High', 'Volume'], axis=1, inplace=True)
    stock_df = stock_df.tail(1)

    max_SMA = max(stock_df['20_SMA'].item(), stock_df['50_SMA'].item(), stock_df['200_SMA'].item())
    min_SMA = min(stock_df['20_SMA'].item(), stock_df['50_SMA'].item(), stock_df['200_SMA'].item())
    ABS_Spread = max_SMA - min_SMA
    stock_df['Spread%'] = round((ABS_Spread / stock_df['200_SMA'].item()) * 100,2)

    return stock_df

# function to compute stock attributes
def get_common_features(stock_ids, df_mypf):

  df_prec_dev = pd.DataFrame()
  df_tmp = get_screener_features()
  df_rs = get_relative_strength(stock_ids)

  for stock_id in stock_ids:
      tmp = stock_prec_dev(stock_id)
      tmp = tmp.reset_index()
      df_prec_dev = pd.concat([df_prec_dev, tmp], ignore_index = True)
  df_prec_dev = pd.merge(df_prec_dev, df_mypf, on= 'Symbol')
  df_prec_dev = pd.merge(df_prec_dev, df_tmp, on= 'Symbol', how='left')
  df_prec_dev = pd.merge(df_prec_dev, df_rs, on= 'Symbol', how='left')
  #print(df_prec_dev.columns)
  df_prec_dev['Curr_PE'] = round(df_prec_dev['Close']/df_prec_dev['EPS'],1)
  df_prec_dev['Dev%_PE'] = round((df_prec_dev['Curr_PE'] - df_prec_dev['MedPE'])*100/df_prec_dev['MedPE'],2)
  df_prec_dev['Conviction'] = df_prec_dev['Conviction'] + '-' + df_prec_dev['CapType']
  return df_prec_dev

# function to arrange stock features
def arrange_features(df_stocks, common_cols, diff_cols):
  df_stocks_common = df_stocks[common_cols].drop_duplicates()
  df_stocks_diff = df_stocks[diff_cols]
  df_stocks_diff['Investment'] = df_stocks_diff['AvgCost'] * df_stocks_diff['Shares']
  df_stocks_diff = df_stocks_diff.groupby(['Symbol'])[['Shares', 'Investment']].aggregate(['sum']).reset_index()
  df_stocks_diff.columns = ['Symbol', 'Shares', 'Investment']
  df_stocks_diff['AvgCost'] = round(df_stocks_diff['Investment']/df_stocks_diff['Shares'],2)
  df_stocks = pd.merge(df_stocks_diff, df_stocks_common, on='Symbol')
  return df_stocks

# plot fact distribution across dimension
def plot_pie_chart(df, dimension, fact):
  # grouping the data by category and calculating the sum of fact for each type
  grouped_data = df.groupby(dimension)[fact].sum()

  # sorting the grouped data in descending order
  grouped_data = grouped_data.sort_values(ascending=False)

  # creating a pie chart
  grouped_data.plot.pie(autopct='%1.1f%%', startangle=90, figsize=(6, 6))

  # adding a title and displaying the plot
  plt.title(f'{dimension} {fact} Distribution')
  plt.ylabel('')  # To hide the y-label
  plt.show()

In [7]:
# function to get portfolio features

def get_portfolio_features(df_common_features):

  print_date_time()
  print('-------------------')

  #df_common_features["Target"] = df_common_features["Target"].fillna(df_common_features["Max"])
  df_common_features['NTT'] = np.where(df_common_features['Strategy']== 'NTT', df_common_features["Target"], df_common_features['Max'])
  df_common_features['LTT'] = np.where(df_common_features['Strategy']== 'BTT', df_common_features["Target"], df_common_features['Max'])
  df_common_features['BOL'] = df_common_features['Min']

  tmp_df = df_common_features[df_common_features['Symbol'].isin(mypf_df[mypf_df['InPortfolio'] != 'NA'].Symbol.values)]
  print('qualified stocks: '+str(len(tmp_df['Symbol'].unique())))
  tmp_df1 = tmp_df[tmp_df['LatestQtr'] == 1]
  print('with latest results: '+str(len(tmp_df1['Symbol'].unique())))
  tmp_df1 = tmp_df1[tmp_df1['StarStock'] == 1]
  print('still star stocks: '+str(len(tmp_df1['Symbol'].unique())))
  tmp_df['Investment'] = tmp_df['AvgCost'] * tmp_df['Shares']
  tmp_df['Current'] = round(tmp_df['Close'] * tmp_df['Shares'],0)
  tmp_df['Previous'] = tmp_df['Prev_Close'] * tmp_df['Shares']
  tmp_df['EstimatedST'] = tmp_df['NTT'] * tmp_df['Shares']
  tmp_df['EstimatedLT'] = tmp_df['LTT'] * tmp_df['Shares']
  tmp_df['Current P/L'] = round((tmp_df['Current'] - tmp_df['Investment']),0)
  tmp_df['Today P/L%'] = round((tmp_df['Current'] - tmp_df['Previous'])*100/tmp_df['Previous'],2)
  tmp_df['Current P/L%'] = round((tmp_df['Current'] - tmp_df['Investment'])*100/tmp_df['Investment'],2)
  tmp_df['EstimatedST P/L%'] = round((tmp_df['EstimatedST'] - tmp_df['Investment'])*100/tmp_df['Investment'],2)
  tmp_df['EstimatedLT P/L%'] = round((tmp_df['EstimatedLT'] - tmp_df['Investment'])*100/tmp_df['Investment'],2)
  tmp_df['NTT%'] = round((tmp_df['NTT'] - tmp_df['Close'])*100/tmp_df['Close'],2)
  tmp_df['LTT%'] = round((tmp_df['LTT'] - tmp_df['Close'])*100/tmp_df['Close'],2)
  tmp_df['Gained%'] = round((tmp_df['Close'] - tmp_df['BOL'])*100/tmp_df['BOL'],2)
  investment = round(sum(tmp_df['AvgCost']*tmp_df['Shares']),0)
  current = round(sum(tmp_df['Close']*tmp_df['Shares']),0)
  tmp_df['InitAlloc%'] = round(tmp_df['Investment']*100/investment,2)
  tmp_df['CurrAlloc%'] = round(tmp_df['Current']*100/current,2)
  tmp_df['FTT'] = tmp_df['LTT']
  tmp_df.loc[tmp_df['Strategy'] == 'NTT', 'FTT'] = tmp_df['NTT']
  tmp_df['FTT%'] = tmp_df['LTT%']
  tmp_df.loc[tmp_df['Strategy'] == 'NTT', 'FTT%'] = tmp_df['NTT%']
  tmp_df['FTT Amt'] = round(tmp_df['FTT%'] * tmp_df['Current']/100,0)
  tmp_df['OTT%'] = round((tmp_df['FTT'] - tmp_df['AvgCost'])*100/tmp_df['AvgCost'],2)
  tmp_df['RRR Ind'] = round(tmp_df['Current P/L']/tmp_df['FTT Amt'],2)
  tmp_df['Risk Ind'] = round(tmp_df['Current P/L%']*tmp_df['CurrAlloc%'],0)

  return tmp_df

# function to print portfolio features
def print_portfolio_stats(df_portfolio_features, myinvmt_df):
  from pyxirr import xirr

  total_booked_amt, reserve_amt, cy_booked_amt, py_booked_amt = get_amt()

  dates = myinvmt_df['Date'].values
  dates = np.append(dates, datetime.date.today().strftime('%d-%b-%y'))
  investment = myinvmt_df['Investment'].values
  dates= pd.to_datetime(dates)

  current = round(sum(df_portfolio_features['Close']*df_portfolio_features['Shares']),0) + reserve_amt
  investment_xirr = np.append(investment, current)
  cagr = round(xirr(pd.DataFrame({"dates": dates, "amounts": investment_xirr}))*100,2)

  investment = -sum(investment)
  invested = round(sum(df_portfolio_features['AvgCost']*df_portfolio_features['Shares']),0) + reserve_amt
  previous = round(sum(df_portfolio_features['Prev_Close']*df_portfolio_features['Shares']),0) + reserve_amt
  cy_invested = investment + py_booked_amt

  today_pnl_amount = current-previous
  today_pnl_percentage = round((current-previous)*100/previous,2)

  curr_pnl_amount = current-invested
  curr_pnl_percentage = round((curr_pnl_amount)*100/(cy_invested),2)

  cy_pnl_amount = cy_booked_amt + curr_pnl_amount
  cy_pnl_percentage = round((cy_pnl_amount)*100/cy_invested,2)

  overall_pnl_amount = total_booked_amt + curr_pnl_amount
  overall_pnl_percentage = round((overall_pnl_amount)*100/investment,2)

  estimate_st = round(sum(df_portfolio_features['FTT']*df_portfolio_features['Shares']),0)  + reserve_amt
  est_st_pnl_amount = estimate_st-current
  est_st_pnl_percentage = round((est_st_pnl_amount)*100/current,2)

  estimate_lt = round(sum(df_portfolio_features['LTT']*df_portfolio_features['Shares']),0)  + reserve_amt
  est_lt_pnl_amount = estimate_lt-current
  est_lt_pnl_percentage = round((est_lt_pnl_amount)*100/current,2)

  total_profit = round(sum(df_portfolio_features[df_portfolio_features['Current P/L%'] > 0]['Current']) - sum(df_portfolio_features[df_portfolio_features['Current P/L%'] > 0]['Investment']),0)
  total_loss = round(sum(df_portfolio_features[df_portfolio_features['Current P/L%'] < 0]['Current']) - sum(df_portfolio_features[df_portfolio_features['Current P/L%'] < 0]['Investment']),0)

  cy_booked_percentage = round((cy_booked_amt)*100/current,2)
  py_booked_percentage = round((py_booked_amt)*100/investment,2)
  total_booked_percentage = round((total_booked_amt)*100/investment,2)

  print('-------------------')
  print('Initial Investment: ', format_amt(investment))
  print('CY Investment: ', format_amt(cy_invested))
  print('Reserve: ', format_amt(reserve_amt))
  print('Current: ',  format_amt(current))
  print('-------------------')
  print('Today PnL: '+ '{} ({}%)'.format(format_amt(today_pnl_amount), today_pnl_percentage))
  print('Current PnL: '+ '{} ({}%)'.format(format_amt(curr_pnl_amount), curr_pnl_percentage))
  print('CY Booked + Current PnL: '+ '{} ({}%)'.format(format_amt(cy_pnl_amount), cy_pnl_percentage))
  print('-------------------')
  print('Total profit: ', format_amt(total_profit))
  print('Total loss: ', format_amt(total_loss))
  print('-------------------')
  print('Total Booked + Current PnL: '+ '{} ({}%)'.format(format_amt(overall_pnl_amount), overall_pnl_percentage))
  print('Total Booked PnL: '+ '{} ({}%)'.format(format_amt(total_booked_amt), total_booked_percentage))
  print('Curr Year Booked PnL: '+ '{} ({}%)'.format(format_amt(cy_booked_amt), cy_booked_percentage))
  print('Prev Year Booked PnL: '+ '{} ({}%)'.format(format_amt(py_booked_amt), py_booked_percentage))
  print('===================')
  print('Est FTT: ',  format_amt(estimate_st))
  print('Est FTT PnL: '+ '{} ({}%)'.format(format_amt(est_st_pnl_amount), est_st_pnl_percentage))

  print('===================')
  print('Deployed: ', format_amt(investment))

  print('Current: ', format_amt(current))

  print('CAGR/XIRR %: '+'{}%'.format(cagr))

In [8]:
# get start and end date
start_date, end_date = get_start_end_date()

# get portfolio and prospects data
mypfs_df = get_mypfs_df()
mypps_df = get_mypps_df()
myinvmt_df = get_myinvmt_df()

# merge above datasets
mypf_df = pd.merge(mypfs_df, mypps_df, on="Symbol")

# seggregate dm and sv portfolio
dm_pf = mypf_df[mypf_df['InPortfolio'] == 'DM']
sv_pf = mypf_df[mypf_df['InPortfolio'] == 'SV']

# build portfolio stock dataframe
dm_stocks = get_stock_ids(dm_pf)
sv_stocks = get_stock_ids(sv_pf)
df_stocks = pd.concat([dm_pf,sv_pf], ignore_index = True)

# arrange common and diff stock features
common_cols = ['Symbol', 'Target', 'Criteria', 'Strategy', 'CumlRnk', 'LatestQtr', 'StarStock', 'Conviction', 'Category', 'InFolio', 'XIRR', 'MBQ']
diff_cols = ['Symbol', 'AvgCost', 'Shares']
df_stocks = arrange_features(df_stocks, common_cols, diff_cols)

# get common features
stock_ids = df_stocks['Symbol'].values
df_common_features = get_common_features(stock_ids, df_stocks)

df_common_features.reset_index(drop=True, inplace=True)
df_common_features.drop(['Date'], axis=1, inplace=True)
# get and print portfolio features
df_portfolio_features = get_portfolio_features(df_common_features)

print_portfolio_stats(df_portfolio_features, myinvmt_df)

df = df_portfolio_features
#plot_pie_chart(df, 'CapType', 'Current')
list_ox40n = list(df[df['MBQ'].str.contains('OX40N', na=False)]['Symbol'].values)

Run date time (IST): 2026-04-09 11:41:14
-------------------
qualified stocks: 86
with latest results: 26
still star stocks: 16
-------------------
Initial Investment:  1.36 C
CY Investment:  1.62 C
Reserve:  1.61 K
Current:  1.37 C
-------------------
Today PnL: 65.84 K (0.48%)
Current PnL: -40.04 L (-24.64%)
CY Booked + Current PnL: -24.15 L (-14.86%)
-------------------
Total profit:  1.28 L
Total loss:  -41.32 L
-------------------
Total Booked + Current PnL: 2.83 L (2.09%)
Total Booked PnL: 42.87 L (31.64%)
Curr Year Booked PnL: 15.89 L (11.59%)
Prev Year Booked PnL: 26.98 L (19.91%)
===================
Est FTT:  2.48 C
Est FTT PnL: 1.11 C (80.82%)
===================
Deployed:  1.36 C
Current:  1.37 C
CAGR/XIRR %: 0.56%

In [9]:
# top 5 near their targets
cols = ['Symbol', 'Today P/L%', 'Current P/L%', 'FTT%', 'OTT%', 'FTT Amt', 'Current P/L', 'Current', 'FTT', 'Dev%_PE', 'RSI_14','Conviction', 'Spread%',  'CumlRnk', 'RRR Ind', 'CurrAlloc%', 'Gained%', 'Criteria', 'Strategy', 'Category']
df_tmp = df_portfolio_features[~df_portfolio_features['Symbol'].isin(['ENRIN','BLUSPRING','DIGITIDE'])]
df_tmp = df_tmp.sort_values(by = 'FTT Amt', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
50,MASFIN,1.27,-3.40,25.84,21.57,24458.0,-3330.0,94650.0,397.04,-16.89,56.0,H-SC,4.68,167.0,-0.14,0.69,24.01,XR,ATH,FINANCE
5,ANGELONE,5.30,15.50,7.52,24.18,26490.0,47262.0,352262.0,303.00,-83.35,72.0,X-SC,6.32,97.0,1.78,2.57,34.77,X40N,NTT,FINANCE
77,TTKPRESTIG,-0.03,-37.44,60.00,0.09,37826.0,-37733.0,63044.0,770.00,46.42,49.0,M-SC,21.77,250.0,-1.00,0.46,12.26,OX40N,NTT,DURABLES
67,SONACOMS,0.15,-7.53,50.42,39.09,47162.0,-7621.0,93538.0,804.02,-26.68,60.0,M-MC,7.97,193.0,-0.16,0.68,32.32,AR,ATH,AUTO
37,ICICIGI,1.35,-6.02,26.98,19.34,50740.0,-12044.0,188065.0,2252.93,-21.06,47.0,X-MC,7.17,66.0,-0.24,1.37,5.04,X40,ATH,INSURANCE

In [10]:
# top 5 today
df_tmp = df_portfolio_features.sort_values(by = 'Today P/L%', ascending=False)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
5,ANGELONE,5.30,15.50,7.52,24.18,26490.0,47262.0,352262.0,303.00,-83.35,72.0,X-SC,6.32,97.0,1.78,2.57,34.77,X40N,NTT,FINANCE
14,BOSCH-HCIL,4.98,-41.29,70.30,-0.01,52753.0,-52765.0,75040.0,2282.00,15247.83,59.0,M-SC,9.39,231.0,-1.00,0.55,27.73,OX40N,BTT,AC
22,DEN,3.52,-48.19,174.22,42.07,76239.0,-40704.0,43760.0,75.00,55.44,57.0,M-SC,21.88,235.0,-0.53,0.32,19.02,AR,NTT,ENTERTAINMENT
36,HONAUT,3.28,-27.30,108.12,51.31,151584.0,-52638.0,140200.0,58357.33,-39.52,45.0,X-SC,18.88,90.0,-0.35,1.02,6.51,X40N,ATH,ELECTRICAL
55,RAJESHEXPO,3.10,-79.89,397.60,0.07,109682.0,-109591.0,27586.0,518.00,911.36,46.0,L-SC,44.47,268.0,-1.00,0.20,29.51,OX40N,NTT,JEWELLERY

In [11]:
# bottom 5 today
df_tmp = df_portfolio_features.sort_values(by = 'Today P/L%', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
43,INFY,-1.66,-9.87,48.95,34.24,138035.0,-30897.0,281991.0,1972.0,-29.25,53.0,X-LC,14.41,3.0,-0.22,2.06,8.45,X40,NTT,IT
34,HDFCBANK,-1.66,-3.99,33.70,28.37,75999.0,-9368.0,225517.0,1073.0,-18.56,48.0,X-LC,16.71,26.0,-0.12,1.65,9.71,X40,BTT,BANKS
60,REPCOHOME,-1.58,-17.41,129.83,89.82,307219.0,-49873.0,236632.0,880.0,-59.02,55.0,H-SC,7.44,161.0,-0.16,1.73,13.76,XY24,NTT,FINANCE
46,JIOFIN,-1.49,-19.30,59.14,28.43,142378.0,-57579.0,240748.0,387.0,-20.57,52.0,X-LC,19.35,34.0,-0.40,1.76,10.25,XY24,BTT,FINANCE
16,CAMPUS,-1.19,-18.37,63.27,33.28,86653.0,-30817.0,136958.0,393.0,-34.23,53.0,M-SC,13.19,218.0,-0.36,1.00,9.98,XY24,NTT,FOOTWEAR

In [12]:
# top 5 to exit based on CumlRnk
df_tmp = df_portfolio_features[~df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])]
df_tmp = df_tmp[(df_tmp['Current P/L%'] > -1) & (df_tmp['Current P/L%'] < 1)].sort_values(by = 'CumlRnk', ascending=False)
df_tmp[cols].head()

Empty DataFrame
Columns: [Symbol, Today P/L%, Current P/L%, FTT%, OTT%, FTT Amt, Current P/L, Current, FTT, Dev%_PE, RSI_14, Conviction, Spread%, CumlRnk, RRR Ind, CurrAlloc%, Gained%, Criteria, Strategy, Category]
Index: []

In [13]:
# OX40N stocks to exit
df_tmp = df_portfolio_features[(df_portfolio_features['Symbol'].isin(list_ox40n))].sort_values(by = 'Current P/L%', ascending=False)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
26,FINCABLES,1.80,9.35,90.13,107.91,145520.0,13812.0,161456.0,1641.55,-1.57,55.0,M-SC,2.32,220.0,0.09,1.18,21.47,OX40N,ATH,CABLES
66,SIS,2.77,-30.65,74.86,21.26,57640.0,-34035.0,76997.0,528.00,1807.77,58.0,H-SC,14.49,168.0,-0.59,0.56,14.48,OX40N,NTT,MISC
18,CERA,0.68,-33.47,86.22,23.89,100898.0,-58879.0,117024.0,9475.00,-35.80,62.0,H-SC,17.95,153.0,-0.58,0.85,12.46,OX40N,NTT,CERAMICS
72,TATAELXSI,0.30,-35.90,105.97,32.03,89553.0,-47327.0,84508.0,9161.00,-19.86,54.0,H-SC,21.05,158.0,-0.53,0.62,11.85,OX40N,NTT,IT
77,TTKPRESTIG,-0.03,-37.44,60.00,0.09,37826.0,-37733.0,63044.0,770.00,46.42,49.0,M-SC,21.77,250.0,-1.00,0.46,12.26,OX40N,NTT,DURABLES

In [14]:
# top 5 to book for rotation
df_tmp = df_portfolio_features[(df_portfolio_features['Current P/L%'] > 20) ].sort_values(by = 'CumlRnk', ascending=False)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
1,ABB,-0.29,20.1,21.2,45.57,66612.0,52589.0,314208.0,7934.0,-22.86,64.0,H-MC,14.8,125.0,0.79,2.29,39.53,AR,NTT,ELECTRICAL

In [15]:
# top 5 to monitor for exit
df_tmp = df_portfolio_features[~df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])]
df_tmp = df_tmp[(df_tmp['Current P/L%'] > 0) ].sort_values(by = 'Dev%_PE', ascending=False)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
26,FINCABLES,1.80,9.35,90.13,107.91,145520.0,13812.0,161456.0,1641.55,-1.57,55.0,M-SC,2.32,220.0,0.09,1.18,21.47,OX40N,ATH,CABLES
1,ABB,-0.29,20.10,21.20,45.57,66612.0,52589.0,314208.0,7934.00,-22.86,64.0,H-MC,14.80,125.0,0.79,2.29,39.53,AR,NTT,ELECTRICAL

In [16]:
# top 5 to book for rotation from weak conviction
df_tmp = df_portfolio_features[~df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])]
df_tmp = df_tmp[~df_tmp['Criteria'].isin(['XY25','XY24','X40', 'X40N'])].sort_values(by = 'RRR Ind', ascending=False)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
1,ABB,-0.29,20.10,21.20,45.57,66612.0,52589.0,314208.0,7934.00,-22.86,64.0,H-MC,14.80,125.0,0.79,2.29,39.53,AR,NTT,ELECTRICAL
26,FINCABLES,1.80,9.35,90.13,107.91,145520.0,13812.0,161456.0,1641.55,-1.57,55.0,M-SC,2.32,220.0,0.09,1.18,21.47,OX40N,ATH,CABLES
40,INDIAMART,1.13,-8.95,127.04,106.72,142661.0,-11040.0,112296.0,4810.62,-58.98,55.0,H-SC,12.91,140.0,-0.08,0.82,8.49,AR,ATH,MISC
85,ZYDUSLIFE,1.50,-4.58,42.13,35.63,84253.0,-9591.0,199983.0,1286.17,-17.12,54.0,H-MC,5.96,120.0,-0.11,1.46,11.33,AR,ATH,PHARMA
50,MASFIN,1.27,-3.40,25.84,21.57,24458.0,-3330.0,94650.0,397.04,-16.89,56.0,H-SC,4.68,167.0,-0.14,0.69,24.01,XR,ATH,FINANCE

In [17]:
# top 5 to accumulate based on lowest RSI_14
df_tmp = df_portfolio_features[df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])].sort_values(by = 'RSI_14', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
53,PGHH,0.53,-27.80,82.84,32.01,127706.0,-59360.0,154160.0,17616.87,-51.15,36.0,X-MC,20.60,57.0,-0.46,1.12,5.44,X40,ATH,FMCG
82,VOLTAS,-0.55,-1.59,47.55,45.20,89720.0,-3057.0,188685.0,1856.00,12.60,39.0,X-MC,5.60,79.0,-0.03,1.38,5.09,XY25,NTT,AC
78,UNITDSPR,-0.11,-8.37,31.79,20.77,68206.0,-19591.0,214553.0,1644.00,-18.80,41.0,X-MC,4.92,64.0,-0.29,1.57,2.35,X40N,NTT,BREWERIES
21,DABUR,0.73,-15.86,70.79,43.70,147753.0,-39348.0,208720.0,735.00,-23.72,41.0,X-MC,13.10,70.0,-0.27,1.52,4.85,XY24,BTT,FMCG
59,RELIANCE,-0.85,-14.22,46.07,25.30,79417.0,-28580.0,172383.0,1952.00,-16.57,42.0,X-LC,4.68,21.0,-0.36,1.26,13.19,XY25,BTT,REFINERIES

In [18]:
# top 5 to accumulate based on Spread and CumlRnk
df_tmp = df_portfolio_features[df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])]
df_tmp = df_tmp[(df_tmp['CumlRnk'] < 100)].sort_values(by = 'Spread%', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
65,SIEMENS,0.20,-13.15,44.52,25.51,71955.0,-24470.0,161625.0,4671.50,35.65,56.0,H-LC,1.13,51.0,-0.34,1.18,19.02,AR,ATH,ELECTRICAL
59,RELIANCE,-0.85,-14.22,46.07,25.30,79417.0,-28580.0,172383.0,1952.00,-16.57,42.0,X-LC,4.68,21.0,-0.36,1.26,13.19,XY25,BTT,REFINERIES
78,UNITDSPR,-0.11,-8.37,31.79,20.77,68206.0,-19591.0,214553.0,1644.00,-18.80,41.0,X-MC,4.92,64.0,-0.29,1.57,2.35,X40N,NTT,BREWERIES
24,DMART,0.63,5.68,22.63,29.60,59694.0,14184.0,263784.0,5391.45,-10.86,67.0,X-LC,5.04,14.0,0.24,1.92,20.57,X40N,ATH,FMCG
82,VOLTAS,-0.55,-1.59,47.55,45.20,89720.0,-3057.0,188685.0,1856.00,12.60,39.0,X-MC,5.60,79.0,-0.03,1.38,5.09,XY25,NTT,AC

In [19]:
# top 5 to accumulate based on lowest Gained%
df_tmp = df_portfolio_features[df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])].sort_values(by = 'Gained%', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
2,ABBOTINDIA,0.00,-13.28,36.15,18.07,56069.0,-23755.0,155100.0,35195.0,-26.29,43.0,X-MC,11.23,58.0,-0.42,1.13,1.43,X40,ATH,PHARMA
78,UNITDSPR,-0.11,-8.37,31.79,20.77,68206.0,-19591.0,214553.0,1644.0,-18.80,41.0,X-MC,4.92,64.0,-0.29,1.57,2.35,X40N,NTT,BREWERIES
8,AWL,-0.55,-38.70,172.47,67.02,376685.0,-137903.0,218406.0,485.0,-67.02,44.0,X-SC,25.33,81.0,-0.37,1.59,3.31,XY24,NTT,FMCG
35,HINDUNILVR,-0.27,-16.76,36.55,13.67,78210.0,-43083.0,213980.0,2922.0,-38.30,47.0,X-LC,11.82,9.0,-0.55,1.56,4.27,XY25,NTT,FMCG
28,GLAXO,0.54,-4.98,46.44,39.15,87939.0,-9924.0,189360.0,3466.2,-27.38,47.0,X-MC,11.45,56.0,-0.11,1.38,4.76,X40,ATH,PHARMA

In [20]:
# top 5 to accumulate based on lowest CurrAlloc%
df_tmp = df_portfolio_features[df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])].sort_values(by = 'CurrAlloc%', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
58,RELAXO,0.27,-63.62,318.67,52.31,168280.0,-92353.0,52807.0,1176.00,-61.28,45.0,X-SC,33.06,92.0,-0.55,0.39,18.07,X40N,NTT,FOOTWEAR
12,BATAINDIA,-0.31,-54.72,198.58,35.20,115705.0,-70404.0,58266.0,2096.00,-23.61,51.0,X-SC,34.31,91.0,-0.61,0.43,15.56,X40,NTT,FOOTWEAR
54,QUESS,2.18,-20.86,119.72,73.90,101189.0,-22272.0,84521.0,424.00,-57.58,58.0,X-SC,21.91,80.0,-0.22,0.62,13.70,XY24,NTT,MISC
36,HONAUT,3.28,-27.30,108.12,51.31,151584.0,-52638.0,140200.0,58357.33,-39.52,45.0,X-SC,18.88,90.0,-0.35,1.02,6.51,X40N,ATH,ELECTRICAL
53,PGHH,0.53,-27.80,82.84,32.01,127706.0,-59360.0,154160.0,17616.87,-51.15,36.0,X-MC,20.60,57.0,-0.46,1.12,5.44,X40,ATH,FMCG

In [21]:
# top 5 to accumulate based on CumlRnk
df_tmp = df_portfolio_features.sort_values(by = 'CumlRnk', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
45,ITC,0.33,-20.07,48.95,19.06,133091.0,-68275.0,271891.0,452.00,-56.33,51.0,X-LC,19.59,1.0,-0.51,1.98,5.47,X40,NTT,FMCG
73,TCS,1.09,-24.05,66.65,26.57,234514.0,-111414.0,351859.0,4311.59,-35.76,58.0,X-LC,18.26,2.0,-0.48,2.57,9.81,X40,ATH,IT
43,INFY,-1.66,-9.87,48.95,34.24,138035.0,-30897.0,281991.0,1972.00,-29.25,53.0,X-LC,14.41,3.0,-0.22,2.06,8.45,X40,NTT,IT
75,TMPV,1.22,-22.87,77.07,36.58,211532.0,-81373.0,274468.0,600.00,-83.62,56.0,X-LC,12.32,4.0,-0.38,2.00,14.40,XY24,NTT,AUTO
33,HCLTECH,-0.92,-6.06,31.82,23.83,72318.0,-14651.0,227273.0,1908.19,-1.16,59.0,X-LC,10.18,8.0,-0.20,1.66,10.35,X40,ATH,IT

In [22]:
# top 5 for average up
df_tmp = df_portfolio_features[(df_portfolio_features['Dev%_200'] > 5)].sort_values(by = 'CurrAlloc%', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
67,SONACOMS,0.15,-7.53,50.42,39.09,47162.0,-7621.0,93538.0,804.02,-26.68,60.0,M-MC,7.97,193.0,-0.16,0.68,32.32,AR,ATH,AUTO
62,SATIN,0.99,-12.71,73.94,51.83,178327.0,-35106.0,241178.0,274.00,-21.16,63.0,H-SC,3.33,159.0,-0.20,1.76,17.49,XY24,NTT,FINANCE
24,DMART,0.63,5.68,22.63,29.60,59694.0,14184.0,263784.0,5391.45,-10.86,67.0,X-LC,5.04,14.0,0.24,1.92,20.57,X40N,ATH,FMCG
1,ABB,-0.29,20.10,21.20,45.57,66612.0,52589.0,314208.0,7934.00,-22.86,64.0,H-MC,14.80,125.0,0.79,2.29,39.53,AR,NTT,ELECTRICAL
5,ANGELONE,5.30,15.50,7.52,24.18,26490.0,47262.0,352262.0,303.00,-83.35,72.0,X-SC,6.32,97.0,1.78,2.57,34.77,X40N,NTT,FINANCE

In [23]:
# top 5 RSP
df_tmp = df_portfolio_features.sort_values(by = 'RSP', ascending=False)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
5,ANGELONE,5.30,15.50,7.52,24.18,26490.0,47262.0,352262.0,303.00,-83.35,72.0,X-SC,6.32,97.0,1.78,2.57,34.77,X40N,NTT,FINANCE
80,VALIANTORG,0.28,-44.93,216.24,74.15,194826.0,-73508.0,90097.0,838.00,-262.20,61.0,H-SC,23.90,145.0,-0.38,0.66,34.08,XR,NTT,CHEMICALS
52,PAGEIND,2.28,-5.76,42.32,34.11,107032.0,-15469.0,252910.0,51418.65,-32.42,72.0,X-MC,17.86,55.0,-0.14,1.85,19.64,X40,ATH,APPARELS
18,CERA,0.68,-33.47,86.22,23.89,100898.0,-58879.0,117024.0,9475.00,-35.80,62.0,H-SC,17.95,153.0,-0.58,0.85,12.46,OX40N,NTT,CERAMICS
30,HAPPSTMNDS,-0.65,-52.57,289.76,84.85,176128.0,-67381.0,60784.0,1480.71,-43.65,48.0,H-SC,23.01,152.0,-0.38,0.44,12.56,AR,ATH,IT

In [24]:
# Top N allocation
df_tmp = df_portfolio_features.sort_values(by = 'CurrAlloc%', ascending=False)
top_n_values = [10, 25, 50]

sum_df = pd.DataFrame({
    'Top_N': top_n_values,
    'Sum_Alloc%': [df_tmp['CurrAlloc%'].head(n).sum() for n in top_n_values]
})

sum_df

   Top_N  Sum_Alloc%
0     10       21.15
1     25       46.01
2     50       77.76

In [25]:
# market-cap-wise allocation
df_tmp = df_portfolio_features[cols]
df_tmp.groupby(df_tmp['Conviction'].str[-2:])['CurrAlloc%'].sum().sort_values(ascending=False)

Conviction
SC    45.14
MC    29.33
LC    25.54
Name: CurrAlloc%, dtype: float64

In [26]:
# criteria-wise allocation
df_portfolio_features.groupby('Criteria')['CurrAlloc%'].sum().sort_values(ascending=False)

Criteria
XY24     27.19
X40      25.04
X40N     15.56
AR        9.19
XR        8.45
XY25      7.00
OX40N     6.79
SR        0.79
Name: CurrAlloc%, dtype: float64

In [27]:
# conviction-wise allocation
df_portfolio_features.groupby('Conviction')['CurrAlloc%'].sum().sort_values(ascending=False)

Conviction
X-LC    23.33
H-SC    22.07
X-MC    21.88
X-SC    12.40
M-SC    10.11
H-MC     5.03
M-MC     2.08
H-LC     1.18
M-LC     1.03
L-SC     0.56
L-MC     0.34
Name: CurrAlloc%, dtype: float64

In [28]:
# sector-wise stats
df_tmp = df_portfolio_features.groupby('Category')[['CurrAlloc%', 'Current', 'Current P/L', 'FTT Amt']].sum().sort_values(by=['Current', 'Current P/L'], ascending=False)
df_tmp['Current P/L%'] = round(df_tmp['Current P/L'] * 100 / df_tmp['Current'], 2)
df_tmp['FTT%'] = round(df_tmp['FTT Amt'] * 100 / df_tmp['Current'], 2)
cols = ['CurrAlloc%', 'Current P/L%', 'FTT%']
df_tmp[cols].sort_values(by=['CurrAlloc%'], ascending=False)

               CurrAlloc%  Current P/L%    FTT%
Category
FMCG                14.75        -23.37   67.15
FINANCE             13.58        -15.61   62.72
IT                  11.95        -37.57  107.59
MISC                 7.12        -37.33   96.98
ELECTRICAL           6.42         -9.92   52.01
PAINTS               5.17        -38.97   63.10
BANKS                4.64        -21.04   82.48
INSURANCE            4.52         -9.28   46.68
PHARMA               3.97         -7.95   41.93
AUTO                 3.77        -26.46   76.63
HEALTHCARE           1.96        -33.59   68.45
AC                   1.93        -21.17   54.02
TRAVEL               1.85        -76.46  164.81
APPARELS             1.85         -6.12   42.32
FOOTWEAR             1.82        -78.04  149.43
DURABLES             1.74        -62.02  101.44
BREWERIES            1.57         -9.13   31.79
REALTY               1.43        -12.99   31.55
CERAMICS             1.35        -65.39  115.63
REFINERIES           1.26        -16.58   46.07
CEMENT               1.22        -60.13  179.92
ENGINEERING          1.18        -49.42  117.77
CABLES               1.18          8.55   90.13
CHEMICALS            1.09        -76.84  221.11
JEWELLERY            1.07       -118.83  194.86
ENTERTAINMENT        0.80        -77.36  183.14
TEXTILES             0.46        -47.74   89.87
HOTELS               0.36       -129.94  211.04

In [29]:
# money to be made criteria-wise
df_portfolio_features.groupby('Criteria')['FTT Amt'].agg(['sum', 'count']).sort_values(by='sum', ascending=False)

                sum  count
Criteria
XY24      3869889.0     21
X40       1742267.0     16
XR        1333918.0     12
AR        1311433.0     10
X40N      1166580.0     10
OX40N      862407.0     10
XY25       482271.0      5
SR         310471.0      2

In [30]:
# money to be made conviction-wise
df_portfolio_features.groupby('Conviction')['FTT Amt'].agg(['sum', 'count']).sort_values(by='sum', ascending=False)

                  sum  count
Conviction
H-SC        3767970.0     24
X-MC        1733188.0     15
X-LC        1578575.0     13
M-SC        1533975.0     14
X-SC        1483278.0     10
H-MC         389505.0      3
L-SC         213898.0      2
M-LC         150280.0      1
M-MC         101121.0      2
H-LC          71955.0      1
L-MC          55491.0      1

In [31]:
# money to be made criteria and conviction-wise
df_portfolio_features.groupby(['Conviction', 'Criteria'])['FTT Amt'].agg(['sum', 'count']).sort_values(by='sum', ascending=False)

                           sum  count
Conviction Criteria
H-SC       XY24      1287280.0      6
           AR         965212.0      5
M-SC       XY24       886087.0      6
X-LC       X40        850950.0      7
X-SC       XY24       842209.0      4
H-SC       XR         836133.0      7
X-MC       X40        676655.0      7
           X40N       524085.0      4
X-SC       X40N       426407.0      4
M-SC       OX40N      383851.0      5
H-SC       OX40N      368874.0      4
X-LC       XY24       353910.0      2
H-SC       SR         310471.0      2
X-MC       XY25       270685.0      2
           XY24       261763.0      2
H-MC       XY24       238640.0      1
X-LC       X40N       216088.0      2
X-SC       X40        214662.0      2
M-SC       XR         187798.0      2
X-LC       XY25       157627.0      2
H-MC       AR         150865.0      2
M-LC       XR         150280.0      1
L-SC       OX40N      109682.0      1
           XR         104216.0      1
M-SC       AR          76239.0      1
H-LC       AR          71955.0      1
L-MC       XR          55491.0      1
M-MC       XY25        53959.0      1
           AR          47162.0      1

In [32]:
# notebook execution time

end_time = time.time()
execution_time = round(end_time - start_time, 0)
print(f"Notebook execution time: {execution_time} seconds")

Notebook execution time: 23.0 seconds