<a href="https://colab.research.google.com/github/ankit-rathi/Quantvesting_v2/blob/main/myStocks_Portfolio_Analysis.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
'''
!pip install pandas==2.2.2 -qq
!pip install pyxirr -qq
!pip install ta -qq
!pip install yfinance==0.2.59 -qq
'''

'\n!pip install pandas==2.2.2 -qq\n!pip install pyxirr -qq\n!pip install ta -qq\n!pip install yfinance==0.2.59 -qq\n'

In [2]:
# import libraries

import numpy as np
import pandas as pd
import datetime
import warnings
warnings.filterwarnings('ignore')
import yfinance as yfin
import ta
import matplotlib.pyplot as plt
import requests

In [3]:
# notebook start time
import time
import datetime
import pytz

start_time = time.time()

# function to print date timestamp
def print_date_time():
  tz_NY = pytz.timezone('Asia/Kolkata')
  datetime_NY = datetime.datetime.now(tz_NY)
  print("Run date time (IST):", datetime_NY.strftime("%Y-%m-%d %H:%M:%S"))

In [4]:
# function to get booked and reserved amount
def get_amt():
  # fetch the JSON data from the URL
  url = "https://raw.githubusercontent.com/ankit-rathi/Tradevesting_v1/main/data/myPortfolioAmts.json"
  response = requests.get(url)
  pf_amts = response.json()  # parse the JSON data

  # extract values from the JSON
  py_booked_amt_dm = pf_amts["py_booked_amt_dm"]
  py_booked_amt_sv = pf_amts["py_booked_amt_sv"]
  cy_booked_amt_dm = pf_amts["cy_booked_amt_dm"]
  cy_booked_amt_sv = pf_amts["cy_booked_amt_sv"]
  reserve_amt_dm = pf_amts["reserve_amt_dm"]
  reserve_amt_sv = pf_amts["reserve_amt_sv"]

  # perform calculations
  py_booked_amt = py_booked_amt_dm + py_booked_amt_sv
  cy_booked_amt = cy_booked_amt_dm + cy_booked_amt_sv
  reserve_amt = reserve_amt_dm + reserve_amt_sv
  total_booked_amt = py_booked_amt + cy_booked_amt

  return total_booked_amt, reserve_amt, cy_booked_amt, py_booked_amt

gen_output = 0

In [5]:
# function to format the amount
def format_amt(number):
    abs_number = abs(number)

    if abs_number >= 1_00_00_000:  # Crores
        formatted_amt = f"{number / 1_00_00_000:.2f} C"
    elif abs_number >= 1_00_000:  # Lakhs
        formatted_amt = f"{number / 1_00_000:.2f} L"
    elif abs_number >= 1_000:  # Thousands
        formatted_amt = f"{number / 1_000:.2f} K"
    else:
        formatted_amt = f"{number:.2f}"

    return formatted_amt

# function to set start and end date
def get_start_end_date():
  start_date = (datetime.date.today() + datetime.timedelta(days=-365)).strftime('%Y-%m-%d')
  end_date = (datetime.date.today() + datetime.timedelta(days=1)).strftime('%Y-%m-%d')
  return start_date, end_date

# function to fetch my portfolio csv
def get_mypfs_df():
  mypfs_df = pd.read_csv('https://raw.githubusercontent.com/ankit-rathi/Tradevesting_v1/main/data/myPortfolioStocks.csv')
  return mypfs_df

# function to fetch my prospects csv
def get_mypps_df():
  mypps_df = pd.read_csv('https://raw.githubusercontent.com/ankit-rathi/Tradevesting_v1/main/data/myProspectsScrips.csv')
  return mypps_df

# function to fetch screener data
def get_myscreen_df():
  myscreen_df = pd.read_csv('https://raw.githubusercontent.com/ankit-rathi/Tradevesting_v1/main/data/myScreenerDB.csv')
  return myscreen_df

# function to fetch momentum data
def get_myinvmt_df():
  myinvmt_df = pd.read_csv('https://raw.githubusercontent.com/ankit-rathi/Tradevesting_v1/main/data/myInvestments.csv')
  return myinvmt_df

# function to get the stock ids
def get_stock_ids(df_pf):
  stock_n100 = df_pf['Symbol'].unique()

  exclude = ['CADILAHC','MMTC', 'MASFIN']

  stock_ids = df_pf[~df_pf['Symbol'].isin(exclude) ]['Symbol'].unique()

  #mypf = mypf[mypf.Forecast.notnull()]
  #stock_ids = mypf['Symbol'].unique()

  #stock_ids.sort()
  return stock_ids

# get features from screener data
def get_screener_features():
  myscreen_df = get_myscreen_df()
  cols = ['Symbol', 'EPS', 'MedPE', 'ROCE%', 'ROE%', 'CapType']
  return myscreen_df[cols]

# get relative strength
def get_relative_strength(stock_list):

    # Dictionary to store stock tickers and their corresponding percentage price change
    stock_changes = {}

    # Loop through each stock and fetch its price data
    for stock in stock_list:
        try:
            # Download the stock data for the given date range
            stock_data = yfin.Ticker(stock + '.NS').history(period='1mo', interval='1d')[map(str.title, ['open', 'close', 'low', 'high', 'volume'])]

            # Calculate the percentage change for the stock
            if len(stock_data) > 0:
                start_price = stock_data['Close'].iloc[0]
                end_price = stock_data['Close'].iloc[-1]
                percent_change = round(((end_price - start_price) / start_price) * 100, 2)
                stock_changes[stock] = percent_change
            else:
                stock_changes[stock] = np.nan  # If no data is available, set to NaN

        except Exception as e:
            print(f"Error fetching data for {stock}: {e}")
            stock_changes[stock] = np.nan

    # Create a DataFrame with stock tickers and their percentage changes
    df = pd.DataFrame(list(stock_changes.items()), columns=['Symbol', 'Percent_Change'])

    # Drop any stocks with missing data (NaN values)
    df = df.dropna()

    # Calculate the percentile rank based on percentage change
    df['RSP'] = round(df['Percent_Change'].rank(pct=True) * 100, 2)
    cols = ['Symbol', 'RSP']
    df = df[cols]
    # Sort by percentile rank (optional)
    df = df.sort_values(by='RSP', ascending=False).reset_index(drop=True)

    return df

In [6]:
# function to get stock technicals
def stock_prec_dev(stock_symbol):
    #stock_symbol = 'ULTRACEMCO.NS'
    short_window = 20
    mid_window = 50
    long_window = 200
    moving_avg = 'SMA'

    start = datetime.datetime(*map(int, start_date.split('-')))
    end = datetime.datetime(*map(int, end_date.split('-')))

    stock_df = yfin.Ticker(stock_symbol + '.NS').history(period='max', interval='1d')[map(str.title, ['open', 'close', 'low', 'high', 'volume'])]

    stock_df['Max'] = round(max(stock_df['Close']),2)
    stock_df = stock_df[(stock_df.index <= end_date) & (stock_df.index >= start_date)]
    stock_df['200_SMA'] = round(stock_df['Close'].rolling(window = 200, min_periods = 1).mean(),0)
    stock_df['Dev%_200'] = round((stock_df['Close'] - stock_df['200_SMA'])*100/stock_df['200_SMA'],2)
    stock_df.dropna(axis = 0, inplace = True) # remove any null rows

    stock_df['20_SMA'] = stock_df['Close'].rolling(window=20).mean()
    stock_df['50_SMA'] = stock_df['Close'].rolling(window=50).mean()
    stock_df['Symbol'] = stock_symbol

    stock_df['Close'] = round(stock_df['Close'],2)
    stock_df['Min'] = round(min(stock_df['Close']),2)
    stock_df['RSI_14'] = ta.momentum.RSIIndicator(close=stock_df['Close'], window=14).rsi()
    stock_df['RSI_14'] = round(stock_df['RSI_14'],0)
    stock_df['Prev_Close'] = stock_df['Close'].shift(1)
    stock_df.drop(['Open', 'Low', 'High', 'Volume'], axis=1, inplace=True)
    stock_df = stock_df.tail(1)

    max_SMA = max(stock_df['20_SMA'].item(), stock_df['50_SMA'].item(), stock_df['200_SMA'].item())
    min_SMA = min(stock_df['20_SMA'].item(), stock_df['50_SMA'].item(), stock_df['200_SMA'].item())
    ABS_Spread = max_SMA - min_SMA
    stock_df['Spread%'] = round((ABS_Spread / stock_df['200_SMA'].item()) * 100,2)

    return stock_df

# function to compute stock attributes
def get_common_features(stock_ids, df_mypf):

  df_prec_dev = pd.DataFrame()
  df_tmp = get_screener_features()
  df_rs = get_relative_strength(stock_ids)

  for stock_id in stock_ids:
      tmp = stock_prec_dev(stock_id)
      tmp = tmp.reset_index()
      df_prec_dev = pd.concat([df_prec_dev, tmp], ignore_index = True)
  df_prec_dev = pd.merge(df_prec_dev, df_mypf, on= 'Symbol')
  df_prec_dev = pd.merge(df_prec_dev, df_tmp, on= 'Symbol', how='left')
  df_prec_dev = pd.merge(df_prec_dev, df_rs, on= 'Symbol', how='left')
  #print(df_prec_dev.columns)
  df_prec_dev['Curr_PE'] = round(df_prec_dev['Close']/df_prec_dev['EPS'],1)
  df_prec_dev['Dev%_PE'] = round((df_prec_dev['Curr_PE'] - df_prec_dev['MedPE'])*100/df_prec_dev['MedPE'],2)
  df_prec_dev['Conviction'] = df_prec_dev['Conviction'] + '-' + df_prec_dev['CapType']
  return df_prec_dev

# function to arrange stock features
def arrange_features(df_stocks, common_cols, diff_cols):
  df_stocks_common = df_stocks[common_cols].drop_duplicates()
  df_stocks_diff = df_stocks[diff_cols]
  df_stocks_diff['Investment'] = df_stocks_diff['AvgCost'] * df_stocks_diff['Shares']
  df_stocks_diff = df_stocks_diff.groupby(['Symbol'])[['Shares', 'Investment']].aggregate(['sum']).reset_index()
  df_stocks_diff.columns = ['Symbol', 'Shares', 'Investment']
  df_stocks_diff['AvgCost'] = round(df_stocks_diff['Investment']/df_stocks_diff['Shares'],2)
  df_stocks = pd.merge(df_stocks_diff, df_stocks_common, on='Symbol')
  return df_stocks

# plot fact distribution across dimension
def plot_pie_chart(df, dimension, fact):
  # grouping the data by category and calculating the sum of fact for each type
  grouped_data = df.groupby(dimension)[fact].sum()

  # sorting the grouped data in descending order
  grouped_data = grouped_data.sort_values(ascending=False)

  # creating a pie chart
  grouped_data.plot.pie(autopct='%1.1f%%', startangle=90, figsize=(6, 6))

  # adding a title and displaying the plot
  plt.title(f'{dimension} {fact} Distribution')
  plt.ylabel('')  # To hide the y-label
  plt.show()

In [7]:
# function to get portfolio features

def get_portfolio_features(df_common_features):

  print_date_time()
  print('-------------------')

  #df_common_features["Target"] = df_common_features["Target"].fillna(df_common_features["Max"])
  df_common_features['NTT'] = np.where(df_common_features['Strategy']== 'NTT', df_common_features["Target"], df_common_features['Max'])
  df_common_features['LTT'] = np.where(df_common_features['Strategy']== 'BTT', df_common_features["Target"], df_common_features['Max'])
  df_common_features['BOL'] = df_common_features['Min']

  tmp_df = df_common_features[df_common_features['Symbol'].isin(mypf_df[mypf_df['InPortfolio'] != 'NA'].Symbol.values)]
  print('qualified stocks: '+str(len(tmp_df['Symbol'].unique())))
  tmp_df1 = tmp_df[tmp_df['LatestQtr'] == 1]
  print('with latest results: '+str(len(tmp_df1['Symbol'].unique())))
  tmp_df1 = tmp_df1[tmp_df1['StarStock'] == 1]
  print('still star stocks: '+str(len(tmp_df1['Symbol'].unique())))
  tmp_df['Investment'] = tmp_df['AvgCost'] * tmp_df['Shares']
  tmp_df['Current'] = round(tmp_df['Close'] * tmp_df['Shares'],0)
  tmp_df['Previous'] = tmp_df['Prev_Close'] * tmp_df['Shares']
  tmp_df['EstimatedST'] = tmp_df['NTT'] * tmp_df['Shares']
  tmp_df['EstimatedLT'] = tmp_df['LTT'] * tmp_df['Shares']
  tmp_df['Current P/L'] = round((tmp_df['Current'] - tmp_df['Investment']),0)
  tmp_df['Today P/L%'] = round((tmp_df['Current'] - tmp_df['Previous'])*100/tmp_df['Previous'],2)
  tmp_df['Current P/L%'] = round((tmp_df['Current'] - tmp_df['Investment'])*100/tmp_df['Investment'],2)
  tmp_df['EstimatedST P/L%'] = round((tmp_df['EstimatedST'] - tmp_df['Investment'])*100/tmp_df['Investment'],2)
  tmp_df['EstimatedLT P/L%'] = round((tmp_df['EstimatedLT'] - tmp_df['Investment'])*100/tmp_df['Investment'],2)
  tmp_df['NTT%'] = round((tmp_df['NTT'] - tmp_df['Close'])*100/tmp_df['Close'],2)
  tmp_df['LTT%'] = round((tmp_df['LTT'] - tmp_df['Close'])*100/tmp_df['Close'],2)
  tmp_df['Gained%'] = round((tmp_df['Close'] - tmp_df['BOL'])*100/tmp_df['BOL'],2)
  investment = round(sum(tmp_df['AvgCost']*tmp_df['Shares']),0)
  current = round(sum(tmp_df['Close']*tmp_df['Shares']),0)
  tmp_df['InitAlloc%'] = round(tmp_df['Investment']*100/investment,2)
  tmp_df['CurrAlloc%'] = round(tmp_df['Current']*100/current,2)
  tmp_df['FTT'] = tmp_df['LTT']
  tmp_df.loc[tmp_df['Strategy'] == 'NTT', 'FTT'] = tmp_df['NTT']
  tmp_df['FTT%'] = tmp_df['LTT%']
  tmp_df.loc[tmp_df['Strategy'] == 'NTT', 'FTT%'] = tmp_df['NTT%']
  tmp_df['FTT Amt'] = round(tmp_df['FTT%'] * tmp_df['Current']/100,0)
  tmp_df['OTT%'] = round((tmp_df['FTT'] - tmp_df['AvgCost'])*100/tmp_df['AvgCost'],2)
  tmp_df['RRR Ind'] = round(tmp_df['Current P/L']/tmp_df['FTT Amt'],2)
  tmp_df['Risk Ind'] = round(tmp_df['Current P/L%']*tmp_df['CurrAlloc%'],0)

  return tmp_df

# function to print portfolio features
def print_portfolio_stats(df_portfolio_features, myinvmt_df):
  from pyxirr import xirr

  total_booked_amt, reserve_amt, cy_booked_amt, py_booked_amt = get_amt()

  dates = myinvmt_df['Date'].values
  dates = np.append(dates, datetime.date.today().strftime('%d-%b-%y'))
  investment = myinvmt_df['Investment'].values
  dates= pd.to_datetime(dates)

  current = round(sum(df_portfolio_features['Close']*df_portfolio_features['Shares']),0) + reserve_amt
  investment_xirr = np.append(investment, current)
  cagr = round(xirr(pd.DataFrame({"dates": dates, "amounts": investment_xirr}))*100,2)

  investment = -sum(investment)
  invested = round(sum(df_portfolio_features['AvgCost']*df_portfolio_features['Shares']),0) + reserve_amt
  previous = round(sum(df_portfolio_features['Prev_Close']*df_portfolio_features['Shares']),0) + reserve_amt
  cy_invested = investment + py_booked_amt

  today_pnl_amount = current-previous
  today_pnl_percentage = round((current-previous)*100/previous,2)

  curr_pnl_amount = current-invested
  curr_pnl_percentage = round((curr_pnl_amount)*100/(cy_invested),2)

  cy_pnl_amount = cy_booked_amt + curr_pnl_amount
  cy_pnl_percentage = round((cy_pnl_amount)*100/cy_invested,2)

  overall_pnl_amount = total_booked_amt + curr_pnl_amount
  overall_pnl_percentage = round((overall_pnl_amount)*100/investment,2)

  estimate_st = round(sum(df_portfolio_features['FTT']*df_portfolio_features['Shares']),0)  + reserve_amt
  est_st_pnl_amount = estimate_st-current
  est_st_pnl_percentage = round((est_st_pnl_amount)*100/current,2)

  estimate_lt = round(sum(df_portfolio_features['LTT']*df_portfolio_features['Shares']),0)  + reserve_amt
  est_lt_pnl_amount = estimate_lt-current
  est_lt_pnl_percentage = round((est_lt_pnl_amount)*100/current,2)

  total_profit = round(sum(df_portfolio_features[df_portfolio_features['Current P/L%'] > 0]['Current']) - sum(df_portfolio_features[df_portfolio_features['Current P/L%'] > 0]['Investment']),0)
  total_loss = round(sum(df_portfolio_features[df_portfolio_features['Current P/L%'] < 0]['Current']) - sum(df_portfolio_features[df_portfolio_features['Current P/L%'] < 0]['Investment']),0)

  cy_booked_percentage = round((cy_booked_amt)*100/current,2)
  py_booked_percentage = round((py_booked_amt)*100/investment,2)
  total_booked_percentage = round((total_booked_amt)*100/investment,2)

  print('-------------------')
  print('Initial Investment: ', format_amt(investment))
  print('CY Investment: ', format_amt(cy_invested))
  print('Reserve: ', format_amt(reserve_amt))
  print('Current: ',  format_amt(current))
  print('-------------------')
  print('Today PnL: '+ '{} ({}%)'.format(format_amt(today_pnl_amount), today_pnl_percentage))
  print('Current PnL: '+ '{} ({}%)'.format(format_amt(curr_pnl_amount), curr_pnl_percentage))
  print('CY Booked + Current PnL: '+ '{} ({}%)'.format(format_amt(cy_pnl_amount), cy_pnl_percentage))
  print('-------------------')
  print('Total profit: ', format_amt(total_profit))
  print('Total loss: ', format_amt(total_loss))
  print('-------------------')
  print('Total Booked + Current PnL: '+ '{} ({}%)'.format(format_amt(overall_pnl_amount), overall_pnl_percentage))
  print('Total Booked PnL: '+ '{} ({}%)'.format(format_amt(total_booked_amt), total_booked_percentage))
  print('Curr Year Booked PnL: '+ '{} ({}%)'.format(format_amt(cy_booked_amt), cy_booked_percentage))
  print('Prev Year Booked PnL: '+ '{} ({}%)'.format(format_amt(py_booked_amt), py_booked_percentage))
  print('===================')
  print('Est FTT: ',  format_amt(estimate_st))
  print('Est FTT PnL: '+ '{} ({}%)'.format(format_amt(est_st_pnl_amount), est_st_pnl_percentage))

  print('===================')
  print('Deployed: ', format_amt(investment))

  print('Current: ', format_amt(current))

  print('CAGR/XIRR %: '+'{}%'.format(cagr))

In [8]:
# get start and end date
start_date, end_date = get_start_end_date()

# get portfolio and prospects data
mypfs_df = get_mypfs_df()
mypps_df = get_mypps_df()
myinvmt_df = get_myinvmt_df()

# merge above datasets
mypf_df = pd.merge(mypfs_df, mypps_df, on="Symbol")

# seggregate dm and sv portfolio
dm_pf = mypf_df[mypf_df['InPortfolio'] == 'DM']
sv_pf = mypf_df[mypf_df['InPortfolio'] == 'SV']

# build portfolio stock dataframe
dm_stocks = get_stock_ids(dm_pf)
sv_stocks = get_stock_ids(sv_pf)
df_stocks = pd.concat([dm_pf,sv_pf], ignore_index = True)

# arrange common and diff stock features
common_cols = ['Symbol', 'Target', 'Criteria', 'Strategy', 'CumlRnk', 'LatestQtr', 'StarStock', 'Conviction', 'Category', 'InFolio', 'XIRR', 'MBQ']
diff_cols = ['Symbol', 'AvgCost', 'Shares']
df_stocks = arrange_features(df_stocks, common_cols, diff_cols)

# get common features
stock_ids = df_stocks['Symbol'].values
df_common_features = get_common_features(stock_ids, df_stocks)

df_common_features.reset_index(drop=True, inplace=True)
df_common_features.drop(['Date'], axis=1, inplace=True)
# get and print portfolio features
df_portfolio_features = get_portfolio_features(df_common_features)

print_portfolio_stats(df_portfolio_features, myinvmt_df)

df = df_portfolio_features
#plot_pie_chart(df, 'CapType', 'Current')
list_ox40n = list(df[df['MBQ'].str.contains('OX40N', na=False)]['Symbol'].values)

Run date time (IST): 2026-03-06 14:52:45
-------------------
qualified stocks: 86
with latest results: 26
still star stocks: 15
-------------------
Initial Investment:  1.33 C
CY Investment:  1.60 C
Reserve:  2.44 L
Current:  1.36 C
-------------------
Today PnL: 3.46 K (0.03%)
Current PnL: -38.93 L (-24.33%)
CY Booked + Current PnL: -23.25 L (-14.53%)
-------------------
Total profit:  1.18 L
Total loss:  -40.11 L
-------------------
Total Booked + Current PnL: 3.73 L (2.81%)
Total Booked PnL: 42.66 L (32.07%)
Curr Year Booked PnL: 15.68 L (11.57%)
Prev Year Booked PnL: 26.98 L (20.29%)
===================
Est FTT:  2.41 C
Est FTT PnL: 1.06 C (77.89%)
===================
Deployed:  1.33 C
Current:  1.36 C
CAGR/XIRR %: 0.94%

In [9]:
# top 5 near their targets
cols = ['Symbol', 'Today P/L%', 'Current P/L%', 'FTT%', 'OTT%', 'FTT Amt', 'Current P/L', 'Current', 'FTT', 'Dev%_PE', 'RSI_14','Conviction', 'Spread%',  'CumlRnk', 'RRR Ind', 'CurrAlloc%', 'Gained%', 'Criteria', 'Strategy', 'Category']
df_tmp = df_portfolio_features[~df_portfolio_features['Symbol'].isin(['ENRIN','BLUSPRING','DIGITIDE'])]
df_tmp = df_tmp.sort_values(by = 'FTT Amt', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
19,COALINDIA,-2.16,8.13,8.83,17.67,14365.0,12228.0,162689.0,478.51,30.56,58.0,L-LC,11.16,185.0,0.85,1.22,26.34,XY25,ATH,MINING
50,MASFIN,-0.21,-7.41,31.30,21.57,28395.0,-7260.0,90720.0,397.04,-20.05,35.0,H-SC,6.20,167.0,-0.26,0.68,26.59,XR,ATH,FINANCE
37,ICICIGI,0.46,-0.21,19.59,19.34,39118.0,-426.0,199683.0,2252.93,-16.16,47.0,X-MC,1.46,66.0,-0.01,1.50,13.89,X40,ATH,INSURANCE
77,TTKPRESTIG,-2.39,-38.82,63.60,0.09,39213.0,-39122.0,61655.0,770.00,43.01,19.0,M-SC,13.47,250.0,-1.00,0.46,0.00,OX40N,NTT,DURABLES
51,MEDANTA,-0.00,-7.18,33.67,24.08,39677.0,-9110.0,117840.0,1486.00,-7.89,44.0,X-SC,8.17,87.0,-0.23,0.89,7.93,XY24,NTT,HEALTHCARE

In [10]:
# top 5 today
df_tmp = df_portfolio_features.sort_values(by = 'Today P/L%', ascending=False)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
27,FINCABLES,5.72,22.93,69.14,107.91,125484.0,33849.0,181493.0,1641.55,10.60,72.0,M-SC,6.54,220.0,0.27,1.36,36.54,OX40N,ATH,CABLES
78,UNITDSPR,5.23,2.48,17.84,20.77,42808.0,5813.0,239957.0,1644.00,-9.09,53.0,X-MC,1.51,64.0,0.14,1.80,9.36,X40N,NTT,BREWERIES
47,JSWINFRA,3.48,-7.89,26.41,16.43,53946.0,-17509.0,204265.0,342.00,-20.99,59.0,X-MC,11.08,61.0,-0.32,1.54,9.67,X40N,NTT,REALTY
56,RAJOOENG,2.73,-40.09,133.02,39.61,81688.0,-41090.0,61410.0,143.10,-59.49,44.0,H-SC,29.35,136.0,-0.50,0.46,4.99,AR,ATH,MISC
1,ABB,2.60,11.61,30.43,45.57,88851.0,30365.0,291984.0,7934.00,-28.26,62.0,H-MC,9.25,125.0,0.34,2.19,29.66,AR,NTT,ELECTRICAL

In [11]:
# bottom 5 today
df_tmp = df_portfolio_features.sort_values(by = 'Today P/L%', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
55,RAJESHEXPO,-4.99,-77.04,335.77,0.07,105771.0,-105676.0,31501.0,518.00,1054.04,19.0,L-SC,13.73,268.0,-1.00,0.24,0.00,OX40N,NTT,JEWELLERY
41,INDIGOPNTS,-2.57,-37.69,60.51,0.02,65819.0,-65786.0,108773.0,1408.00,65.74,18.0,M-SC,14.16,222.0,-1.00,0.82,0.00,OX40N,NTT,PAINTS
77,TTKPRESTIG,-2.39,-38.82,63.60,0.09,39213.0,-39122.0,61655.0,770.00,43.01,19.0,M-SC,13.47,250.0,-1.00,0.46,0.00,OX40N,NTT,DURABLES
19,COALINDIA,-2.16,8.13,8.83,17.67,14365.0,12228.0,162689.0,478.51,30.56,58.0,L-LC,11.16,185.0,0.85,1.22,26.34,XY25,ATH,MINING
38,ICICIPRULI,-1.96,1.79,28.42,30.73,56993.0,3534.0,200539.0,790.00,-25.50,34.0,X-MC,3.90,78.0,0.06,1.51,14.79,X40,ATH,INSURANCE

In [12]:
# top 5 to exit based on CumlRnk
df_tmp = df_portfolio_features[~df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])]
df_tmp = df_tmp[(df_tmp['Current P/L%'] > -1) & (df_tmp['Current P/L%'] < 1)].sort_values(by = 'CumlRnk', ascending=False)
df_tmp[cols].head()

Empty DataFrame
Columns: [Symbol, Today P/L%, Current P/L%, FTT%, OTT%, FTT Amt, Current P/L, Current, FTT, Dev%_PE, RSI_14, Conviction, Spread%, CumlRnk, RRR Ind, CurrAlloc%, Gained%, Criteria, Strategy, Category]
Index: []

In [13]:
# OX40N stocks to exit
df_tmp = df_portfolio_features[(df_portfolio_features['Symbol'].isin(list_ox40n))].sort_values(by = 'Current P/L%', ascending=False)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
27,FINCABLES,5.72,22.93,69.14,107.91,125484.0,33849.0,181493.0,1641.55,10.60,72.0,M-SC,6.54,220.0,0.27,1.36,36.54,OX40N,ATH,CABLES
66,SIS,1.30,-31.32,76.56,21.26,58383.0,-34774.0,76258.0,528.00,1789.64,39.0,H-SC,7.54,168.0,-0.60,0.57,5.13,OX40N,NTT,MISC
48,KANSAINER,-1.59,-36.48,78.66,13.47,134728.0,-98388.0,171279.0,340.00,-45.39,26.0,H-SC,14.96,162.0,-0.73,1.29,0.00,XY24,NTT,PAINTS
72,TATAELXSI,-1.41,-37.48,111.18,32.03,91639.0,-49411.0,82424.0,9161.00,-21.88,27.0,H-SC,14.48,158.0,-0.54,0.62,0.00,OX40N,NTT,IT
41,INDIGOPNTS,-2.57,-37.69,60.51,0.02,65819.0,-65786.0,108773.0,1408.00,65.74,18.0,M-SC,14.16,222.0,-1.00,0.82,0.00,OX40N,NTT,PAINTS

In [14]:
# top 5 to book for rotation
df_tmp = df_portfolio_features[(df_portfolio_features['Current P/L%'] > 20) ].sort_values(by = 'CumlRnk', ascending=False)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
27,FINCABLES,5.72,22.93,69.14,107.91,125484.0,33849.0,181493.0,1641.55,10.6,72.0,M-SC,6.54,220.0,0.27,1.36,36.54,OX40N,ATH,CABLES

In [15]:
# top 5 to monitor for exit
df_tmp = df_portfolio_features[~df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])]
df_tmp = df_tmp[(df_tmp['Current P/L%'] > 0) ].sort_values(by = 'Dev%_PE', ascending=False)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
19,COALINDIA,-2.16,8.13,8.83,17.67,14365.0,12228.0,162689.0,478.51,30.56,58.0,L-LC,11.16,185.0,0.85,1.22,26.34,XY25,ATH,MINING
27,FINCABLES,5.72,22.93,69.14,107.91,125484.0,33849.0,181493.0,1641.55,10.60,72.0,M-SC,6.54,220.0,0.27,1.36,36.54,OX40N,ATH,CABLES
1,ABB,2.60,11.61,30.43,45.57,88851.0,30365.0,291984.0,7934.00,-28.26,62.0,H-MC,9.25,125.0,0.34,2.19,29.66,AR,NTT,ELECTRICAL

In [16]:
# top 5 to book for rotation from weak conviction
df_tmp = df_portfolio_features[~df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])]
df_tmp = df_tmp[~df_tmp['Criteria'].isin(['XY25','XY24','X40', 'X40N'])].sort_values(by = 'RRR Ind', ascending=False)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
1,ABB,2.60,11.61,30.43,45.57,88851.0,30365.0,291984.0,7934.00,-28.26,62.0,H-MC,9.25,125.0,0.34,2.19,29.66,AR,NTT,ELECTRICAL
27,FINCABLES,5.72,22.93,69.14,107.91,125484.0,33849.0,181493.0,1641.55,10.60,72.0,M-SC,6.54,220.0,0.27,1.36,36.54,OX40N,ATH,CABLES
40,INDIAMART,2.02,-8.97,127.09,106.72,142690.0,-11061.0,112275.0,4810.62,-58.98,41.0,H-SC,8.77,140.0,-0.08,0.84,12.31,AR,ATH,MISC
85,ZYDUSLIFE,-0.14,-3.69,40.82,35.63,82395.0,-7724.0,201850.0,1286.17,-16.22,52.0,H-MC,5.09,120.0,-0.09,1.52,12.37,AR,ATH,PHARMA
67,SONACOMS,1.24,-10.51,55.43,39.09,50179.0,-10632.0,90527.0,804.02,-29.11,50.0,M-MC,10.64,193.0,-0.21,0.68,28.07,AR,ATH,AUTO

In [17]:
# top 5 to accumulate based on lowest RSI_14
df_tmp = df_portfolio_features[df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])].sort_values(by = 'RSI_14', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
8,AWL,-0.52,-42.34,172.61,57.19,324595.0,-138076.0,188051.0,485.00,-67.02,12.0,X-SC,21.04,81.0,-0.43,1.41,0.00,XY24,NTT,FMCG
53,PGHH,-1.41,-17.86,60.72,32.01,106488.0,-38144.0,175376.0,17616.87,-44.44,18.0,X-MC,10.18,57.0,-0.36,1.32,0.00,X40,ATH,FMCG
3,ACC,-1.26,-36.78,159.64,64.15,240162.0,-87511.0,150440.0,3906.00,-52.08,21.0,X-SC,10.66,85.0,-0.36,1.13,0.00,XY24,BTT,CEMENT
12,BATAINDIA,0.01,-52.05,181.99,35.20,112277.0,-66976.0,61694.0,2096.00,-19.13,24.0,X-SC,23.72,91.0,-0.60,0.46,1.47,X40,NTT,FOOTWEAR
58,RELAXO,0.31,-58.04,263.02,52.31,160187.0,-84257.0,60903.0,1176.00,-55.38,25.0,X-SC,16.87,92.0,-0.53,0.46,0.31,X40N,NTT,FOOTWEAR

In [18]:
# top 5 to accumulate based on Spread and CumlRnk
df_tmp = df_portfolio_features[df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])]
df_tmp = df_tmp[(df_tmp['CumlRnk'] < 100)].sort_values(by = 'Spread%', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
22,DABUR,-1.52,-6.06,52.97,43.70,123442.0,-15026.0,233042.0,735.00,-14.67,32.0,X-MC,1.07,70.0,-0.12,1.75,8.08,XY24,BTT,FMCG
37,ICICIGI,0.46,-0.21,19.59,19.34,39118.0,-426.0,199683.0,2252.93,-16.16,47.0,X-MC,1.46,66.0,-0.01,1.50,13.89,X40,ATH,INSURANCE
78,UNITDSPR,5.23,2.48,17.84,20.77,42808.0,5813.0,239957.0,1644.00,-9.09,53.0,X-MC,1.51,64.0,0.14,1.80,9.36,X40N,NTT,BREWERIES
59,RELIANCE,1.36,-9.60,38.61,25.30,70143.0,-19292.0,181671.0,1952.00,-11.96,48.0,X-LC,2.06,21.0,-0.28,1.37,21.29,XY25,BTT,REFINERIES
5,ANGELONE,-1.43,-9.23,36.81,24.18,101904.0,-28162.0,276838.0,303.00,-86.88,31.0,X-SC,2.76,97.0,-0.28,2.08,15.94,X40N,NTT,FINANCE

In [19]:
# top 5 to accumulate based on lowest Gained%
df_tmp = df_portfolio_features[df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])].sort_values(by = 'Gained%', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
3,ACC,-1.26,-36.78,159.64,64.15,240162.0,-87511.0,150440.0,3906.00,-52.08,21.0,X-SC,10.66,85.0,-0.36,1.13,0.0,XY24,BTT,CEMENT
8,AWL,-0.52,-42.34,172.61,57.19,324595.0,-138076.0,188051.0,485.00,-67.02,12.0,X-SC,21.04,81.0,-0.43,1.41,0.0,XY24,NTT,FMCG
24,DIXON,-1.43,-30.13,87.85,31.26,141656.0,-69520.0,161248.0,18931.72,-68.79,36.0,X-MC,24.76,54.0,-0.49,1.21,0.0,X40N,ATH,IT
53,PGHH,-1.41,-17.86,60.72,32.01,106488.0,-38144.0,175376.0,17616.87,-44.44,18.0,X-MC,10.18,57.0,-0.36,1.32,0.0,X40,ATH,FMCG
73,TCS,-0.73,-26.63,68.42,23.58,217192.0,-115189.0,317440.0,4311.58,-36.41,26.0,X-LC,11.96,2.0,-0.53,2.39,0.0,X40,ATH,IT

In [20]:
# top 5 to accumulate based on lowest CurrAlloc%
df_tmp = df_portfolio_features[df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])].sort_values(by = 'CurrAlloc%', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
54,QUESS,-0.97,-36.12,123.61,42.84,51332.0,-23479.0,41527.0,424.00,-58.13,36.0,X-SC,17.16,80.0,-0.46,0.31,0.67,XY24,NTT,MISC
12,BATAINDIA,0.01,-52.05,181.99,35.20,112277.0,-66976.0,61694.0,2096.00,-19.13,24.0,X-SC,23.72,91.0,-0.60,0.46,1.47,X40,NTT,FOOTWEAR
58,RELAXO,0.31,-58.04,263.02,52.31,160187.0,-84257.0,60903.0,1176.00,-55.38,25.0,X-SC,16.87,92.0,-0.53,0.46,0.31,X40N,NTT,FOOTWEAR
51,MEDANTA,-0.00,-7.18,33.67,24.08,39677.0,-9110.0,117840.0,1486.00,-7.89,44.0,X-SC,8.17,87.0,-0.23,0.89,7.93,XY24,NTT,HEALTHCARE
36,HONAUT,0.15,-26.35,94.59,43.32,113470.0,-42912.0,119960.0,58357.33,-35.33,31.0,X-SC,13.11,90.0,-0.38,0.90,0.15,X40N,ATH,ELECTRICAL

In [21]:
# top 5 to accumulate based on CumlRnk
df_tmp = df_portfolio_features.sort_values(by = 'CumlRnk', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
45,ITC,-0.39,-18.27,45.67,19.06,126976.0,-62137.0,278029.0,452.00,-55.12,37.0,X-LC,16.70,1.0,-0.49,2.09,0.67,X40,NTT,FMCG
73,TCS,-0.73,-26.63,68.42,23.58,217192.0,-115189.0,317440.0,4311.58,-36.41,26.0,X-LC,11.96,2.0,-0.53,2.39,0.00,X40,ATH,IT
43,INFY,0.45,-10.71,50.34,34.24,140646.0,-33496.0,279392.0,1972.00,-29.61,30.0,X-LC,10.57,3.0,-0.24,2.10,2.84,X40,NTT,IT
75,TMPV,-1.11,-21.96,70.84,33.33,180124.0,-71531.0,254269.0,600.00,-83.62,38.0,X-LC,3.02,4.0,-0.40,1.91,3.95,XY24,NTT,AUTO
34,HCLTECH,0.47,-11.71,40.27,23.83,86010.0,-28341.0,213583.0,1908.19,-7.36,28.0,X-LC,8.31,8.0,-0.33,1.61,2.47,X40,ATH,IT

In [22]:
# top 5 for average up
df_tmp = df_portfolio_features[(df_portfolio_features['Dev%_200'] > 5)].sort_values(by = 'CurrAlloc%', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
42,INDUSINDBK,1.04,-30.81,92.06,32.89,49178.0,-23786.0,53420.0,1800.00,-351.40,54.0,L-MC,12.14,258.0,-0.48,0.40,47.12,XR,NTT,BANKS
67,SONACOMS,1.24,-10.51,55.43,39.09,50179.0,-10632.0,90527.0,804.02,-29.11,50.0,M-MC,10.64,193.0,-0.21,0.68,28.07,AR,ATH,AUTO
19,COALINDIA,-2.16,8.13,8.83,17.67,14365.0,12228.0,162689.0,478.51,30.56,58.0,L-LC,11.16,185.0,0.85,1.22,26.34,XY25,ATH,MINING
27,FINCABLES,5.72,22.93,69.14,107.91,125484.0,33849.0,181493.0,1641.55,10.60,72.0,M-SC,6.54,220.0,0.27,1.36,36.54,OX40N,ATH,CABLES
82,VOLTAS,-0.47,15.65,25.55,45.20,56656.0,30003.0,221745.0,1856.00,32.38,50.0,X-MC,10.08,79.0,0.53,1.67,23.51,XY25,NTT,AC

In [23]:
# top 5 RSP
df_tmp = df_portfolio_features.sort_values(by = 'RSP', ascending=False)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
27,FINCABLES,5.72,22.93,69.14,107.91,125484.0,33849.0,181493.0,1641.55,10.60,72.0,M-SC,6.54,220.0,0.27,1.36,36.54,OX40N,ATH,CABLES
11,BANDHANBNK,-0.51,-11.45,117.30,92.42,289340.0,-31892.0,246667.0,400.00,111.93,68.0,H-SC,9.73,174.0,-0.11,1.85,35.88,XY24,NTT,BANKS
26,EASEMYTRIP,-1.19,-58.66,252.47,45.70,184523.0,-103728.0,73087.0,26.40,-24.14,45.0,M-SC,18.08,204.0,-0.56,0.55,20.42,XY24,NTT,TRAVEL
83,WHIRLPOOL,-0.70,-27.68,151.54,81.92,125816.0,-31773.0,83025.0,2270.00,-57.64,53.0,M-SC,25.75,210.0,-0.25,0.62,16.63,XR,NTT,DURABLES
1,ABB,2.60,11.61,30.43,45.57,88851.0,30365.0,291984.0,7934.00,-28.26,62.0,H-MC,9.25,125.0,0.34,2.19,29.66,AR,NTT,ELECTRICAL

In [24]:
# Top N allocation
df_tmp = df_portfolio_features.sort_values(by = 'CurrAlloc%', ascending=False)
top_n_values = [10, 25, 50]

sum_df = pd.DataFrame({
    'Top_N': top_n_values,
    'Sum_Alloc%': [df_tmp['CurrAlloc%'].head(n).sum() for n in top_n_values]
})

sum_df

   Top_N  Sum_Alloc%
0     10       20.76
1     25       45.69
2     50       77.82

In [25]:
# market-cap-wise allocation
df_tmp = df_portfolio_features[cols]
df_tmp.groupby(df_tmp['Conviction'].str[-2:])['CurrAlloc%'].sum().sort_values(ascending=False)

Conviction
SC    44.61
MC    30.49
LC    24.92
Name: CurrAlloc%, dtype: float64

In [26]:
# criteria-wise allocation
df_portfolio_features.groupby('Criteria')['CurrAlloc%'].sum().sort_values(ascending=False)

Criteria
XY24     26.52
X40      23.98
X40N     14.82
AR        9.28
XY25      9.00
XR        8.45
OX40N     7.15
SR        0.82
Name: CurrAlloc%, dtype: float64

In [27]:
# conviction-wise allocation
df_portfolio_features.groupby('Conviction')['CurrAlloc%'].sum().sort_values(ascending=False)

Conviction
X-MC    22.93
H-SC    22.28
X-LC    21.44
X-SC    11.09
M-SC    10.61
H-MC     5.07
M-MC     2.09
H-LC     1.24
L-LC     1.22
M-LC     1.02
L-SC     0.63
L-MC     0.40
Name: CurrAlloc%, dtype: float64

In [28]:
# sector-wise stats
df_tmp = df_portfolio_features.groupby('Category')[['CurrAlloc%', 'Current', 'Current P/L', 'FTT Amt']].sum().sort_values(by=['Current', 'Current P/L'], ascending=False)
df_tmp['Current P/L%'] = round(df_tmp['Current P/L'] * 100 / df_tmp['Current'], 2)
df_tmp['FTT%'] = round(df_tmp['FTT Amt'] * 100 / df_tmp['Current'], 2)
cols = ['CurrAlloc%', 'Current P/L%', 'FTT%']
df_tmp[cols].sort_values(by=['CurrAlloc%'], ascending=False)

               CurrAlloc%  Current P/L%    FTT%
Category
FMCG                15.62        -18.71   58.86
FINANCE             12.79        -22.68   70.95
IT                  11.48        -43.73  115.76
MISC                 6.80        -43.51  102.21
ELECTRICAL           6.46         -9.09   48.90
PAINTS               4.96        -39.83   60.60
INSURANCE            4.89         -4.27   39.95
PHARMA               4.27         -3.55   36.15
AUTO                 3.73        -25.70   73.62
BANKS                3.25        -23.63   98.55
AC                   2.23         -7.91   37.17
FOOTWEAR             1.96        -69.27  137.14
TRAVEL               1.91        -76.04  164.19
DURABLES             1.83        -58.58   97.16
BREWERIES            1.80          2.42   17.84
HEALTHCARE           1.68        -38.46   72.63
REALTY               1.54         -8.57   26.41
APPARELS             1.43        -24.42   61.92
CERAMICS             1.40        -64.07  113.91
REFINERIES           1.37        -10.62   38.61
CABLES               1.36         18.65   69.14
MINING               1.22          7.52    8.83
JEWELLERY            1.16       -108.09  180.40
CEMENT               1.13        -58.17  159.64
ENGINEERING          1.13        -61.43  135.26
CHEMICALS            1.00        -98.93  261.23
ENTERTAINMENT        0.79        -84.87  195.13
TEXTILES             0.44        -57.33  102.19
HOTELS               0.39       -116.87  193.36

In [29]:
# money to be made criteria-wise
df_portfolio_features.groupby('Criteria')['FTT Amt'].agg(['sum', 'count']).sort_values(by='sum', ascending=False)

                sum  count
Criteria
XY24      3598656.0     21
X40       1531216.0     15
XR        1366647.0     12
AR        1337291.0     10
X40N      1148564.0     10
OX40N      839797.0     10
XY25       421020.0      6
SR         310942.0      2

In [30]:
# money to be made conviction-wise
df_portfolio_features.groupby('Conviction')['FTT Amt'].agg(['sum', 'count']).sort_values(by='sum', ascending=False)

                  sum  count
Conviction
H-SC        3829054.0     24
M-SC        1506408.0     14
X-MC        1462087.0     15
X-LC        1420477.0     12
X-SC        1328454.0     10
H-MC         403937.0      3
L-SC         207010.0      2
M-LC         155838.0      1
M-MC         108168.0      2
H-LC          69157.0      1
L-MC          49178.0      1
L-LC          14365.0      1

In [31]:
# money to be made criteria and conviction-wise
df_portfolio_features.groupby(['Conviction', 'Criteria'])['FTT Amt'].agg(['sum', 'count']).sort_values(by='sum', ascending=False)

                           sum  count
Conviction Criteria
H-SC       XY24      1295251.0      6
           AR         970006.0      5
M-SC       XY24       888142.0      6
H-SC       XR         874654.0      7
X-LC       X40        740039.0      6
X-SC       XY24       655766.0      4
X-MC       X40        592589.0      7
X-SC       X40N       474100.0      4
X-MC       X40N       440662.0      4
H-SC       OX40N      378201.0      4
M-SC       OX40N      355825.0      5
H-SC       SR         310942.0      2
X-LC       XY24       306854.0      2
           X40N       233802.0      2
H-MC       XY24       232691.0      1
X-MC       XY24       219952.0      2
           XY25       208884.0      2
X-SC       X40        198588.0      2
M-SC       XR         185738.0      2
H-MC       AR         171246.0      2
M-LC       XR         155838.0      1
X-LC       XY25       139782.0      2
L-SC       OX40N      105771.0      1
           XR         101239.0      1
M-SC       AR          76703.0      1
H-LC       AR          69157.0      1
M-MC       XY25        57989.0      1
           AR          50179.0      1
L-MC       XR          49178.0      1
L-LC       XY25        14365.0      1

In [32]:
# notebook execution time

end_time = time.time()
execution_time = round(end_time - start_time, 0)
print(f"Notebook execution time: {execution_time} seconds")

Notebook execution time: 28.0 seconds