<a href="https://colab.research.google.com/github/ankit-rathi/Quantvesting_v2/blob/main/myStocks_Portfolio_Analysis.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
'''
!pip install pandas==2.2.2 -qq
!pip install pyxirr -qq
!pip install ta -qq
!pip install yfinance==0.2.59 -qq
'''

'\n!pip install pandas==2.2.2 -qq\n!pip install pyxirr -qq\n!pip install ta -qq\n!pip install yfinance==0.2.59 -qq\n'

In [2]:
# import libraries

import numpy as np
import pandas as pd
import datetime
import warnings
warnings.filterwarnings('ignore')
import yfinance as yfin
import ta
import matplotlib.pyplot as plt
import requests

In [3]:
# notebook start time
import time
import datetime
import pytz

start_time = time.time()

# function to print date timestamp
def print_date_time():
  tz_NY = pytz.timezone('Asia/Kolkata')
  datetime_NY = datetime.datetime.now(tz_NY)
  print("Run date time (IST):", datetime_NY.strftime("%Y-%m-%d %H:%M:%S"))

In [4]:
# function to get booked and reserved amount
def get_amt():
  # fetch the JSON data from the URL
  url = "https://raw.githubusercontent.com/ankit-rathi/Tradevesting_v1/main/data/myPortfolioAmts.json"
  response = requests.get(url)
  pf_amts = response.json()  # parse the JSON data

  # extract values from the JSON
  py_booked_amt_dm = pf_amts["py_booked_amt_dm"]
  py_booked_amt_sv = pf_amts["py_booked_amt_sv"]
  cy_booked_amt_dm = pf_amts["cy_booked_amt_dm"]
  cy_booked_amt_sv = pf_amts["cy_booked_amt_sv"]
  reserve_amt_dm = pf_amts["reserve_amt_dm"]
  reserve_amt_sv = pf_amts["reserve_amt_sv"]

  # perform calculations
  py_booked_amt = py_booked_amt_dm + py_booked_amt_sv
  cy_booked_amt = cy_booked_amt_dm + cy_booked_amt_sv
  reserve_amt = reserve_amt_dm + reserve_amt_sv
  total_booked_amt = py_booked_amt + cy_booked_amt

  return total_booked_amt, reserve_amt, cy_booked_amt, py_booked_amt

gen_output = 0

In [5]:
# function to format the amount
def format_amt(number):
    abs_number = abs(number)

    if abs_number >= 1_00_00_000:  # Crores
        formatted_amt = f"{number / 1_00_00_000:.2f} C"
    elif abs_number >= 1_00_000:  # Lakhs
        formatted_amt = f"{number / 1_00_000:.2f} L"
    elif abs_number >= 1_000:  # Thousands
        formatted_amt = f"{number / 1_000:.2f} K"
    else:
        formatted_amt = f"{number:.2f}"

    return formatted_amt

# function to set start and end date
def get_start_end_date():
  start_date = (datetime.date.today() + datetime.timedelta(days=-365)).strftime('%Y-%m-%d')
  end_date = (datetime.date.today() + datetime.timedelta(days=1)).strftime('%Y-%m-%d')
  return start_date, end_date

# function to fetch my portfolio csv
def get_mypfs_df():
  mypfs_df = pd.read_csv('https://raw.githubusercontent.com/ankit-rathi/Tradevesting_v1/main/data/myPortfolioStocks.csv')
  return mypfs_df

# function to fetch my prospects csv
def get_mypps_df():
  mypps_df = pd.read_csv('https://raw.githubusercontent.com/ankit-rathi/Tradevesting_v1/main/data/myProspectsScrips.csv')
  return mypps_df

# function to fetch screener data
def get_myscreen_df():
  myscreen_df = pd.read_csv('https://raw.githubusercontent.com/ankit-rathi/Tradevesting_v1/main/data/myScreenerDB.csv')
  return myscreen_df

# function to fetch momentum data
def get_myinvmt_df():
  myinvmt_df = pd.read_csv('https://raw.githubusercontent.com/ankit-rathi/Tradevesting_v1/main/data/myInvestments.csv')
  return myinvmt_df

# function to get the stock ids
def get_stock_ids(df_pf):
  stock_n100 = df_pf['Symbol'].unique()

  exclude = ['CADILAHC','MMTC', 'MASFIN']

  stock_ids = df_pf[~df_pf['Symbol'].isin(exclude) ]['Symbol'].unique()

  #mypf = mypf[mypf.Forecast.notnull()]
  #stock_ids = mypf['Symbol'].unique()

  #stock_ids.sort()
  return stock_ids

# get features from screener data
def get_screener_features():
  myscreen_df = get_myscreen_df()
  cols = ['Symbol', 'EPS', 'MedPE', 'ROCE%', 'ROE%', 'CapType']
  return myscreen_df[cols]

# get relative strength
def get_relative_strength(stock_list):

    # Dictionary to store stock tickers and their corresponding percentage price change
    stock_changes = {}

    # Loop through each stock and fetch its price data
    for stock in stock_list:
        try:
            # Download the stock data for the given date range
            stock_data = yfin.Ticker(stock + '.NS').history(period='1mo', interval='1d')[map(str.title, ['open', 'close', 'low', 'high', 'volume'])]

            # Calculate the percentage change for the stock
            if len(stock_data) > 0:
                start_price = stock_data['Close'].iloc[0]
                end_price = stock_data['Close'].iloc[-1]
                percent_change = round(((end_price - start_price) / start_price) * 100, 2)
                stock_changes[stock] = percent_change
            else:
                stock_changes[stock] = np.nan  # If no data is available, set to NaN

        except Exception as e:
            print(f"Error fetching data for {stock}: {e}")
            stock_changes[stock] = np.nan

    # Create a DataFrame with stock tickers and their percentage changes
    df = pd.DataFrame(list(stock_changes.items()), columns=['Symbol', 'Percent_Change'])

    # Drop any stocks with missing data (NaN values)
    df = df.dropna()

    # Calculate the percentile rank based on percentage change
    df['RSP'] = round(df['Percent_Change'].rank(pct=True) * 100, 2)
    cols = ['Symbol', 'RSP']
    df = df[cols]
    # Sort by percentile rank (optional)
    df = df.sort_values(by='RSP', ascending=False).reset_index(drop=True)

    return df

In [6]:
# function to get stock technicals
def stock_prec_dev(stock_symbol):
    #stock_symbol = 'ULTRACEMCO.NS'
    short_window = 20
    mid_window = 50
    long_window = 200
    moving_avg = 'SMA'

    start = datetime.datetime(*map(int, start_date.split('-')))
    end = datetime.datetime(*map(int, end_date.split('-')))

    stock_df = yfin.Ticker(stock_symbol + '.NS').history(period='max', interval='1d')[map(str.title, ['open', 'close', 'low', 'high', 'volume'])]

    stock_df['Max'] = round(max(stock_df['Close']),2)
    stock_df = stock_df[(stock_df.index <= end_date) & (stock_df.index >= start_date)]
    stock_df['200_SMA'] = round(stock_df['Close'].rolling(window = 200, min_periods = 1).mean(),0)
    stock_df['Dev%_200'] = round((stock_df['Close'] - stock_df['200_SMA'])*100/stock_df['200_SMA'],2)
    stock_df.dropna(axis = 0, inplace = True) # remove any null rows

    stock_df['20_SMA'] = stock_df['Close'].rolling(window=20).mean()
    stock_df['50_SMA'] = stock_df['Close'].rolling(window=50).mean()
    stock_df['Symbol'] = stock_symbol

    stock_df['Close'] = round(stock_df['Close'],2)
    stock_df['Min'] = round(min(stock_df['Close']),2)
    stock_df['RSI_14'] = ta.momentum.RSIIndicator(close=stock_df['Close'], window=14).rsi()
    stock_df['RSI_14'] = round(stock_df['RSI_14'],0)
    stock_df['Prev_Close'] = stock_df['Close'].shift(1)
    stock_df.drop(['Open', 'Low', 'High', 'Volume'], axis=1, inplace=True)
    stock_df = stock_df.tail(1)

    max_SMA = max(stock_df['20_SMA'].item(), stock_df['50_SMA'].item(), stock_df['200_SMA'].item())
    min_SMA = min(stock_df['20_SMA'].item(), stock_df['50_SMA'].item(), stock_df['200_SMA'].item())
    ABS_Spread = max_SMA - min_SMA
    stock_df['Spread%'] = round((ABS_Spread / stock_df['200_SMA'].item()) * 100,2)

    return stock_df

# function to compute stock attributes
def get_common_features(stock_ids, df_mypf):

  df_prec_dev = pd.DataFrame()
  df_tmp = get_screener_features()
  df_rs = get_relative_strength(stock_ids)

  for stock_id in stock_ids:
      tmp = stock_prec_dev(stock_id)
      tmp = tmp.reset_index()
      df_prec_dev = pd.concat([df_prec_dev, tmp], ignore_index = True)
  df_prec_dev = pd.merge(df_prec_dev, df_mypf, on= 'Symbol')
  df_prec_dev = pd.merge(df_prec_dev, df_tmp, on= 'Symbol', how='left')
  df_prec_dev = pd.merge(df_prec_dev, df_rs, on= 'Symbol', how='left')
  #print(df_prec_dev.columns)
  df_prec_dev['Curr_PE'] = round(df_prec_dev['Close']/df_prec_dev['EPS'],1)
  df_prec_dev['Dev%_PE'] = round((df_prec_dev['Curr_PE'] - df_prec_dev['MedPE'])*100/df_prec_dev['MedPE'],2)
  df_prec_dev['Conviction'] = df_prec_dev['Conviction'] + '-' + df_prec_dev['CapType']
  return df_prec_dev

# function to arrange stock features
def arrange_features(df_stocks, common_cols, diff_cols):
  df_stocks_common = df_stocks[common_cols].drop_duplicates()
  df_stocks_diff = df_stocks[diff_cols]
  df_stocks_diff['Investment'] = df_stocks_diff['AvgCost'] * df_stocks_diff['Shares']
  df_stocks_diff = df_stocks_diff.groupby(['Symbol'])[['Shares', 'Investment']].aggregate(['sum']).reset_index()
  df_stocks_diff.columns = ['Symbol', 'Shares', 'Investment']
  df_stocks_diff['AvgCost'] = round(df_stocks_diff['Investment']/df_stocks_diff['Shares'],2)
  df_stocks = pd.merge(df_stocks_diff, df_stocks_common, on='Symbol')
  return df_stocks

# plot fact distribution across dimension
def plot_pie_chart(df, dimension, fact):
  # grouping the data by category and calculating the sum of fact for each type
  grouped_data = df.groupby(dimension)[fact].sum()

  # sorting the grouped data in descending order
  grouped_data = grouped_data.sort_values(ascending=False)

  # creating a pie chart
  grouped_data.plot.pie(autopct='%1.1f%%', startangle=90, figsize=(6, 6))

  # adding a title and displaying the plot
  plt.title(f'{dimension} {fact} Distribution')
  plt.ylabel('')  # To hide the y-label
  plt.show()

In [7]:
# function to get portfolio features

def get_portfolio_features(df_common_features):

  print_date_time()
  print('-------------------')

  #df_common_features["Target"] = df_common_features["Target"].fillna(df_common_features["Max"])
  df_common_features['NTT'] = np.where(df_common_features['Strategy']== 'NTT', df_common_features["Target"], df_common_features['Max'])
  df_common_features['LTT'] = np.where(df_common_features['Strategy']== 'BTT', df_common_features["Target"], df_common_features['Max'])
  df_common_features['BOL'] = df_common_features['Min']

  tmp_df = df_common_features[df_common_features['Symbol'].isin(mypf_df[mypf_df['InPortfolio'] != 'NA'].Symbol.values)]
  print('qualified stocks: '+str(len(tmp_df['Symbol'].unique())))
  tmp_df1 = tmp_df[tmp_df['LatestQtr'] == 1]
  print('with latest results: '+str(len(tmp_df1['Symbol'].unique())))
  tmp_df1 = tmp_df1[tmp_df1['StarStock'] == 1]
  print('still star stocks: '+str(len(tmp_df1['Symbol'].unique())))
  tmp_df['Investment'] = tmp_df['AvgCost'] * tmp_df['Shares']
  tmp_df['Current'] = round(tmp_df['Close'] * tmp_df['Shares'],0)
  tmp_df['Previous'] = tmp_df['Prev_Close'] * tmp_df['Shares']
  tmp_df['EstimatedST'] = tmp_df['NTT'] * tmp_df['Shares']
  tmp_df['EstimatedLT'] = tmp_df['LTT'] * tmp_df['Shares']
  tmp_df['Current P/L'] = round((tmp_df['Current'] - tmp_df['Investment']),0)
  tmp_df['Today P/L%'] = round((tmp_df['Current'] - tmp_df['Previous'])*100/tmp_df['Previous'],2)
  tmp_df['Current P/L%'] = round((tmp_df['Current'] - tmp_df['Investment'])*100/tmp_df['Investment'],2)
  tmp_df['EstimatedST P/L%'] = round((tmp_df['EstimatedST'] - tmp_df['Investment'])*100/tmp_df['Investment'],2)
  tmp_df['EstimatedLT P/L%'] = round((tmp_df['EstimatedLT'] - tmp_df['Investment'])*100/tmp_df['Investment'],2)
  tmp_df['NTT%'] = round((tmp_df['NTT'] - tmp_df['Close'])*100/tmp_df['Close'],2)
  tmp_df['LTT%'] = round((tmp_df['LTT'] - tmp_df['Close'])*100/tmp_df['Close'],2)
  tmp_df['Gained%'] = round((tmp_df['Close'] - tmp_df['BOL'])*100/tmp_df['BOL'],2)
  investment = round(sum(tmp_df['AvgCost']*tmp_df['Shares']),0)
  current = round(sum(tmp_df['Close']*tmp_df['Shares']),0)
  tmp_df['InitAlloc%'] = round(tmp_df['Investment']*100/investment,2)
  tmp_df['CurrAlloc%'] = round(tmp_df['Current']*100/current,2)
  tmp_df['FTT'] = tmp_df['LTT']
  tmp_df.loc[tmp_df['Strategy'] == 'NTT', 'FTT'] = tmp_df['NTT']
  tmp_df['FTT%'] = tmp_df['LTT%']
  tmp_df.loc[tmp_df['Strategy'] == 'NTT', 'FTT%'] = tmp_df['NTT%']
  tmp_df['FTT Amt'] = round(tmp_df['FTT%'] * tmp_df['Current']/100,0)
  tmp_df['OTT%'] = round((tmp_df['FTT'] - tmp_df['AvgCost'])*100/tmp_df['AvgCost'],2)
  tmp_df['RRR Ind'] = round(tmp_df['Current P/L']/tmp_df['FTT Amt'],2)
  tmp_df['Risk Ind'] = round(tmp_df['Current P/L%']*tmp_df['CurrAlloc%'],0)

  return tmp_df

# function to print portfolio features
def print_portfolio_stats(df_portfolio_features, myinvmt_df):
  from pyxirr import xirr

  total_booked_amt, reserve_amt, cy_booked_amt, py_booked_amt = get_amt()

  dates = myinvmt_df['Date'].values
  dates = np.append(dates, datetime.date.today().strftime('%d-%b-%y'))
  investment = myinvmt_df['Investment'].values
  dates= pd.to_datetime(dates)

  current = round(sum(df_portfolio_features['Close']*df_portfolio_features['Shares']),0) + reserve_amt
  investment_xirr = np.append(investment, current)
  cagr = round(xirr(pd.DataFrame({"dates": dates, "amounts": investment_xirr}))*100,2)

  investment = -sum(investment)
  invested = round(sum(df_portfolio_features['AvgCost']*df_portfolio_features['Shares']),0) + reserve_amt
  previous = round(sum(df_portfolio_features['Prev_Close']*df_portfolio_features['Shares']),0) + reserve_amt
  cy_invested = investment + py_booked_amt

  today_pnl_amount = current-previous
  today_pnl_percentage = round((current-previous)*100/previous,2)

  curr_pnl_amount = current-invested
  curr_pnl_percentage = round((curr_pnl_amount)*100/(cy_invested),2)

  cy_pnl_amount = cy_booked_amt + curr_pnl_amount
  cy_pnl_percentage = round((cy_pnl_amount)*100/cy_invested,2)

  overall_pnl_amount = total_booked_amt + curr_pnl_amount
  overall_pnl_percentage = round((overall_pnl_amount)*100/investment,2)

  estimate_st = round(sum(df_portfolio_features['FTT']*df_portfolio_features['Shares']),0)  + reserve_amt
  est_st_pnl_amount = estimate_st-current
  est_st_pnl_percentage = round((est_st_pnl_amount)*100/current,2)

  estimate_lt = round(sum(df_portfolio_features['LTT']*df_portfolio_features['Shares']),0)  + reserve_amt
  est_lt_pnl_amount = estimate_lt-current
  est_lt_pnl_percentage = round((est_lt_pnl_amount)*100/current,2)

  total_profit = round(sum(df_portfolio_features[df_portfolio_features['Current P/L%'] > 0]['Current']) - sum(df_portfolio_features[df_portfolio_features['Current P/L%'] > 0]['Investment']),0)
  total_loss = round(sum(df_portfolio_features[df_portfolio_features['Current P/L%'] < 0]['Current']) - sum(df_portfolio_features[df_portfolio_features['Current P/L%'] < 0]['Investment']),0)

  cy_booked_percentage = round((cy_booked_amt)*100/current,2)
  py_booked_percentage = round((py_booked_amt)*100/investment,2)
  total_booked_percentage = round((total_booked_amt)*100/investment,2)

  print('-------------------')
  print('Initial Investment: ', format_amt(investment))
  print('CY Investment: ', format_amt(cy_invested))
  print('Reserve: ', format_amt(reserve_amt))
  print('Current: ',  format_amt(current))
  print('-------------------')
  print('Today PnL: '+ '{} ({}%)'.format(format_amt(today_pnl_amount), today_pnl_percentage))
  print('Current PnL: '+ '{} ({}%)'.format(format_amt(curr_pnl_amount), curr_pnl_percentage))
  print('CY Booked + Current PnL: '+ '{} ({}%)'.format(format_amt(cy_pnl_amount), cy_pnl_percentage))
  print('-------------------')
  print('Total profit: ', format_amt(total_profit))
  print('Total loss: ', format_amt(total_loss))
  print('-------------------')
  print('Total Booked + Current PnL: '+ '{} ({}%)'.format(format_amt(overall_pnl_amount), overall_pnl_percentage))
  print('Total Booked PnL: '+ '{} ({}%)'.format(format_amt(total_booked_amt), total_booked_percentage))
  print('Curr Year Booked PnL: '+ '{} ({}%)'.format(format_amt(cy_booked_amt), cy_booked_percentage))
  print('Prev Year Booked PnL: '+ '{} ({}%)'.format(format_amt(py_booked_amt), py_booked_percentage))
  print('===================')
  print('Est FTT: ',  format_amt(estimate_st))
  print('Est FTT PnL: '+ '{} ({}%)'.format(format_amt(est_st_pnl_amount), est_st_pnl_percentage))

  print('===================')
  print('Deployed: ', format_amt(investment))

  print('Current: ', format_amt(current))

  print('CAGR/XIRR %: '+'{}%'.format(cagr))

In [8]:
# get start and end date
start_date, end_date = get_start_end_date()

# get portfolio and prospects data
mypfs_df = get_mypfs_df()
mypps_df = get_mypps_df()
myinvmt_df = get_myinvmt_df()

# merge above datasets
mypf_df = pd.merge(mypfs_df, mypps_df, on="Symbol")

# seggregate dm and sv portfolio
dm_pf = mypf_df[mypf_df['InPortfolio'] == 'DM']
sv_pf = mypf_df[mypf_df['InPortfolio'] == 'SV']

# build portfolio stock dataframe
dm_stocks = get_stock_ids(dm_pf)
sv_stocks = get_stock_ids(sv_pf)
df_stocks = pd.concat([dm_pf,sv_pf], ignore_index = True)

# arrange common and diff stock features
common_cols = ['Symbol', 'Target', 'Criteria', 'Strategy', 'CumlRnk', 'LatestQtr', 'StarStock', 'Conviction', 'Category', 'InFolio', 'XIRR', 'MBQ']
diff_cols = ['Symbol', 'AvgCost', 'Shares']
df_stocks = arrange_features(df_stocks, common_cols, diff_cols)

# get common features
stock_ids = df_stocks['Symbol'].values
df_common_features = get_common_features(stock_ids, df_stocks)

df_common_features.reset_index(drop=True, inplace=True)
df_common_features.drop(['Date'], axis=1, inplace=True)
# get and print portfolio features
df_portfolio_features = get_portfolio_features(df_common_features)

print_portfolio_stats(df_portfolio_features, myinvmt_df)

df = df_portfolio_features
#plot_pie_chart(df, 'CapType', 'Current')
list_ox40n = list(df[df['MBQ'].str.contains('OX40N', na=False)]['Symbol'].values)

Run date time (IST): 2026-05-29 15:45:23
-------------------
qualified stocks: 92
with latest results: 31
still star stocks: 20
-------------------
Initial Investment:  1.40 C
CY Investment:  1.82 C
Reserve:  1.49 K
Current:  1.49 C
-------------------
Today PnL: -2.00 L (-1.32%)
Current PnL: -33.91 L (-18.59%)
CY Booked + Current PnL: -31.83 L (-17.45%)
-------------------
Total profit:  2.37 L
Total loss:  -36.28 L
-------------------
Total Booked + Current PnL: 11.04 L (7.91%)
Total Booked PnL: 44.95 L (32.22%)
Curr Year Booked PnL: 2.08 L (1.39%)
Prev Year Booked PnL: 42.87 L (30.73%)
===================
Est FTT:  2.55 C
Est FTT PnL: 1.06 C (71.05%)
===================
Deployed:  1.40 C
Current:  1.49 C
CAGR/XIRR %: 3.24%

In [9]:
# top 5 near their targets
cols = ['Symbol', 'Today P/L%', 'Current P/L%', 'FTT%', 'OTT%', 'FTT Amt', 'Current P/L', 'Current', 'FTT', 'Dev%_PE', 'RSI_14','Conviction', 'Spread%',  'CumlRnk', 'RRR Ind', 'CurrAlloc%', 'Gained%', 'Criteria', 'Strategy', 'Category']
df_tmp = df_portfolio_features[~df_portfolio_features['Symbol'].isin(['ENRIN','BLUSPRING','DIGITIDE'])]
df_tmp = df_tmp.sort_values(by = 'FTT Amt', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
59,PIDILITIND,0.14,5.08,12.64,18.37,18743.0,7170.0,148280.0,1670.26,-26.41,63.0,X-LC,4.98,5.0,0.38,0.99,16.43,X40,ATH,CHEMICALS
51,KOTAKBANK,-1.16,2.66,17.97,21.11,25545.0,3682.0,142154.0,453.24,-12.01,52.0,X-LC,7.42,12.0,0.14,0.95,8.72,X40,ATH,BANKS
55,MASFIN,-2.05,-5.40,28.51,21.57,26424.0,-5295.0,92685.0,397.04,-18.25,42.0,H-SC,3.88,167.0,-0.20,0.62,10.48,XR,ATH,FINANCE
83,TTKPRESTIG,1.57,-29.87,42.72,0.09,30192.0,-30103.0,70674.0,770.00,64.14,57.0,M-SC,15.61,250.0,-1.00,0.47,25.85,OX40N,NTT,DURABLES
72,SIS,2.00,-7.49,31.08,21.26,31924.0,-8318.0,102714.0,528.00,2445.08,65.0,H-SC,17.62,168.0,-0.26,0.69,52.72,OX40N,NTT,MISC

In [10]:
# top 5 today
df_tmp = df_portfolio_features.sort_values(by = 'Today P/L%', ascending=False)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
18,COFFEEDAY,19.97,-41.19,130.02,35.27,86825.0,-46771.0,66778.0,80.00,-55.73,83.0,L-SC,25.01,266.0,-0.54,0.45,64.68,XR,NTT,HOTELS
64,RELAXO,14.34,-55.28,240.57,52.31,156168.0,-80244.0,64916.0,1176.00,-52.38,76.0,X-SC,24.34,92.0,-0.51,0.43,45.15,X40N,NTT,FOOTWEAR
72,SIS,2.00,-7.49,31.08,21.26,31924.0,-8318.0,102714.0,528.00,2445.08,65.0,H-SC,17.62,168.0,-0.26,0.69,52.72,OX40N,NTT,MISC
33,HCLTECH,1.60,-23.18,58.16,21.51,108094.0,-56067.0,185857.0,1872.35,-19.35,45.0,X-LC,18.75,8.0,-0.52,1.25,5.32,X40,ATH,IT
83,TTKPRESTIG,1.57,-29.87,42.72,0.09,30192.0,-30103.0,70674.0,770.00,64.14,57.0,M-SC,15.61,250.0,-1.00,0.47,25.85,OX40N,NTT,DURABLES

In [11]:
# bottom 5 today
df_tmp = df_portfolio_features.sort_values(by = 'Today P/L%', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
29,GREENPANEL,-7.28,-50.54,189.38,43.14,171499.0,-92520.0,90558.0,537.00,102.84,37.0,M-SC,15.61,225.0,-0.54,0.61,8.78,XY24,NTT,MISC
11,BERGEPAINT,-5.00,-7.75,35.84,25.32,85222.0,-19964.0,237785.0,680.00,-12.73,52.0,X-MC,8.24,68.0,-0.23,1.59,23.76,XY24,NTT,PAINTS
58,PGHH,-4.59,-27.68,82.54,32.01,127455.0,-59104.0,154416.0,17616.87,-51.15,43.0,X-MC,17.74,57.0,-0.46,1.03,5.61,X40,ATH,FMCG
16,CERA,-4.02,-27.24,70.28,23.89,89947.0,-47919.0,127984.0,9475.00,-29.83,50.0,H-SC,7.06,153.0,-0.53,0.86,22.99,OX40N,NTT,CERAMICS
27,GLAXO,-3.75,-11.27,56.83,39.15,100485.0,-22468.0,176816.0,3466.20,-32.19,29.0,X-MC,6.71,56.0,-0.22,1.18,0.00,X40,ATH,PHARMA

In [12]:
# top 5 to exit based on CumlRnk
df_tmp = df_portfolio_features[~df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])]
df_tmp = df_tmp[(df_tmp['Current P/L%'] > -1) & (df_tmp['Current P/L%'] < 1)].sort_values(by = 'CumlRnk', ascending=False)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
9,BANDHANBNK,1.2,0.2,92.03,92.42,256876.0,563.0,279122.0,400.0,139.22,68.0,H-SC,21.71,174.0,0.0,1.87,53.76,XY24,NTT,BANKS

In [13]:
# OX40N stocks to exit
df_tmp = df_portfolio_features[(df_portfolio_features['Symbol'].isin(list_ox40n))].sort_values(by = 'Current P/L%', ascending=False)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
25,FINCABLES,-3.48,43.92,44.46,107.91,94472.0,64844.0,212488.0,1641.55,29.38,64.0,M-SC,27.58,220.0,0.69,1.42,59.86,OX40N,ATH,CABLES
72,SIS,2.00,-7.49,31.08,21.26,31924.0,-8318.0,102714.0,528.00,2445.08,65.0,H-SC,17.62,168.0,-0.26,0.69,52.72,OX40N,NTT,MISC
50,KANSAINER,-0.13,-27.22,55.92,13.47,109745.0,-73413.0,196254.0,340.00,-37.50,61.0,H-SC,12.29,162.0,-0.67,1.31,37.08,XY24,NTT,PAINTS
16,CERA,-4.02,-27.24,70.28,23.89,89947.0,-47919.0,127984.0,9475.00,-29.83,50.0,H-SC,7.06,153.0,-0.53,0.86,22.99,OX40N,NTT,CERAMICS
43,INDIGOPNTS,-0.84,-29.61,42.09,0.02,51717.0,-51687.0,122872.0,1408.00,87.50,63.0,M-SC,17.39,222.0,-1.00,0.82,39.41,OX40N,NTT,PAINTS

In [14]:
# top 5 to book for rotation
df_tmp = df_portfolio_features[(df_portfolio_features['Current P/L%'] > 20) ].sort_values(by = 'CumlRnk', ascending=False)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
25,FINCABLES,-3.48,43.92,44.46,107.91,94472.0,64844.0,212488.0,1641.55,29.38,64.0,M-SC,27.58,220.0,0.69,1.42,59.86,OX40N,ATH,CABLES
68,SATIN,-1.81,20.70,25.79,51.83,86005.0,57198.0,333482.0,274.00,7.75,63.0,H-SC,36.13,159.0,0.67,2.23,62.46,XY24,NTT,FINANCE

In [15]:
# top 5 to monitor for exit
df_tmp = df_portfolio_features[~df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])]
df_tmp = df_tmp[(df_tmp['Current P/L%'] > 0) ].sort_values(by = 'Dev%_PE', ascending=False)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
9,BANDHANBNK,1.20,0.20,92.03,92.42,256876.0,563.0,279122.0,400.00,139.22,68.0,H-SC,21.71,174.0,0.00,1.87,53.76,XY24,NTT,BANKS
74,STARHEALTH,0.63,2.16,44.14,47.26,126772.0,6082.0,287205.0,761.00,61.34,63.0,H-SC,9.90,173.0,0.05,1.92,26.09,XY24,NTT,INSURANCE
25,FINCABLES,-3.48,43.92,44.46,107.91,94472.0,64844.0,212488.0,1641.55,29.38,64.0,M-SC,27.58,220.0,0.69,1.42,59.86,OX40N,ATH,CABLES
68,SATIN,-1.81,20.70,25.79,51.83,86005.0,57198.0,333482.0,274.00,7.75,63.0,H-SC,36.13,159.0,0.67,2.23,62.46,XY24,NTT,FINANCE
91,ZYDUSLIFE,-0.75,13.65,19.34,35.63,46062.0,28598.0,238172.0,1286.17,-0.90,73.0,H-MC,5.49,120.0,0.62,1.60,25.23,AR,ATH,PHARMA

In [16]:
# top 5 to book for rotation from weak conviction
df_tmp = df_portfolio_features[~df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])]
df_tmp = df_tmp[~df_tmp['Criteria'].isin(['XY25','XY24','X40', 'X40N'])].sort_values(by = 'RRR Ind', ascending=False)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
25,FINCABLES,-3.48,43.92,44.46,107.91,94472.0,64844.0,212488.0,1641.55,29.38,64.0,M-SC,27.58,220.0,0.69,1.42,59.86,OX40N,ATH,CABLES
91,ZYDUSLIFE,-0.75,13.65,19.34,35.63,46062.0,28598.0,238172.0,1286.17,-0.90,73.0,H-MC,5.49,120.0,0.62,1.60,25.23,AR,ATH,PHARMA
73,SONACOMS,-1.82,5.09,32.36,39.09,34400.0,5145.0,106304.0,804.02,-16.69,60.0,M-MC,18.69,193.0,0.15,0.71,50.38,AR,ATH,AUTO
42,INDIAMART,-0.22,-13.38,138.66,106.72,148133.0,-16504.0,106832.0,4810.62,-60.94,44.0,H-SC,10.78,140.0,-0.11,0.72,3.42,AR,ATH,MISC
90,WIPRO,1.32,-16.23,105.63,72.27,149946.0,-27494.0,141954.0,420.00,-24.55,58.0,M-LC,13.34,98.0,-0.18,0.95,8.91,XR,NTT,IT

In [17]:
# top 5 to accumulate based on lowest RSI_14
df_tmp = df_portfolio_features[df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])].sort_values(by = 'RSI_14', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
27,GLAXO,-3.75,-11.27,56.83,39.15,100485.0,-22468.0,176816.0,3466.20,-32.19,29.0,X-MC,6.71,56.0,-0.22,1.18,0.00,X40,ATH,PHARMA
23,DMART,-1.69,-2.54,32.97,29.60,80206.0,-6330.0,243270.0,5391.45,-17.82,32.0,X-LC,3.08,14.0,-0.08,1.63,11.19,X40N,ATH,FMCG
10,BATAINDIA,-3.41,-56.85,213.33,35.20,118447.0,-73147.0,55523.0,2096.00,-27.22,34.0,X-SC,25.18,91.0,-0.62,0.37,10.12,X40,NTT,FOOTWEAR
47,ITC,-1.73,-24.43,57.55,19.06,147939.0,-83104.0,257062.0,452.00,-58.35,35.0,X-LC,14.65,1.0,-0.56,1.72,2.44,X40,NTT,FMCG
32,HAVELLS,-2.82,-24.65,74.42,31.42,183913.0,-80863.0,247128.0,2052.62,-29.08,37.0,X-MC,12.79,63.0,-0.44,1.66,0.18,X40,ATH,ELECTRICAL

In [18]:
# top 5 to accumulate based on Spread and CumlRnk
df_tmp = df_portfolio_features[df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])]
df_tmp = df_tmp[(df_tmp['CumlRnk'] < 100)].sort_values(by = 'Spread%', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
23,DMART,-1.69,-2.54,32.97,29.60,80206.0,-6330.0,243270.0,5391.45,-17.82,32.0,X-LC,3.08,14.0,-0.08,1.63,11.19,X40N,ATH,FMCG
65,RELIANCE,-2.17,-15.19,47.74,25.30,81366.0,-30528.0,170435.0,1952.00,-17.34,39.0,X-LC,3.98,21.0,-0.38,1.14,1.27,XY25,BTT,REFINERIES
84,UNITDSPR,-2.50,-6.71,29.45,20.77,64331.0,-15704.0,218440.0,1644.00,-17.26,44.0,X-MC,4.35,64.0,-0.24,1.46,4.20,X40N,NTT,BREWERIES
39,ICICIGI,-3.16,-5.07,25.71,19.34,48842.0,-10136.0,189973.0,2252.93,-20.08,46.0,X-MC,4.97,66.0,-0.21,1.27,6.10,X40,ATH,INSURANCE
59,PIDILITIND,0.14,5.08,12.64,18.37,18743.0,7170.0,148280.0,1670.26,-26.41,63.0,X-LC,4.98,5.0,0.38,0.99,16.43,X40,ATH,CHEMICALS

In [19]:
# top 5 to accumulate based on lowest Gained%
df_tmp = df_portfolio_features[df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])].sort_values(by = 'Gained%', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
27,GLAXO,-3.75,-11.27,56.83,39.15,100485.0,-22468.0,176816.0,3466.20,-32.19,29.0,X-MC,6.71,56.0,-0.22,1.18,0.00,X40,ATH,PHARMA
40,ICICIPRULI,-3.62,-16.61,56.76,30.73,93250.0,-32717.0,164288.0,790.00,-39.03,37.0,X-MC,11.86,78.0,-0.35,1.10,0.11,X40,ATH,INSURANCE
32,HAVELLS,-2.82,-24.65,74.42,31.42,183913.0,-80863.0,247128.0,2052.62,-29.08,37.0,X-MC,12.79,63.0,-0.44,1.66,0.18,X40,ATH,ELECTRICAL
65,RELIANCE,-2.17,-15.19,47.74,25.30,81366.0,-30528.0,170435.0,1952.00,-17.34,39.0,X-LC,3.98,21.0,-0.38,1.14,1.27,XY25,BTT,REFINERIES
34,HDFCBANK,-1.86,-10.93,44.11,28.37,92287.0,-25666.0,209219.0,1073.00,-24.48,39.0,X-LC,16.12,26.0,-0.28,1.40,1.78,X40,BTT,BANKS

In [20]:
# top 5 to accumulate based on lowest CurrAlloc%
df_tmp = df_portfolio_features[df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])].sort_values(by = 'CurrAlloc%', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
10,BATAINDIA,-3.41,-56.85,213.33,35.20,118447.0,-73147.0,55523.0,2096.00,-27.22,34.0,X-SC,25.18,91.0,-0.62,0.37,10.12,X40,NTT,FOOTWEAR
64,RELAXO,14.34,-55.28,240.57,52.31,156168.0,-80244.0,64916.0,1176.00,-52.38,76.0,X-SC,24.34,92.0,-0.51,0.43,45.15,X40N,NTT,FOOTWEAR
60,QUESS,-1.91,-14.24,102.78,73.90,94127.0,-15212.0,91581.0,424.00,-53.72,55.0,X-SC,9.35,80.0,-0.16,0.61,24.84,XY24,NTT,MISC
28,GODREJCP,-1.45,-7.88,42.72,31.47,58482.0,-11717.0,136897.0,1469.04,-3.15,46.0,X-LC,8.90,32.0,-0.20,0.92,5.04,X40N,ATH,FMCG
53,M&M,-2.43,-1.17,24.85,23.38,34057.0,-1629.0,137052.0,3802.40,-16.17,42.0,X-LC,8.83,25.0,-0.05,0.92,3.91,X40N,ATH,AUTO

In [21]:
# top 5 to accumulate based on CumlRnk
df_tmp = df_portfolio_features.sort_values(by = 'CumlRnk', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
47,ITC,-1.73,-24.43,57.55,19.06,147939.0,-83104.0,257062.0,452.00,-58.35,35.0,X-LC,14.65,1.0,-0.56,1.72,2.44,X40,NTT,FMCG
79,TCS,-1.11,-33.69,88.32,24.88,271328.0,-156063.0,307210.0,4253.91,-43.95,37.0,X-LC,17.77,2.0,-0.58,2.06,1.94,X40,ATH,IT
45,INFY,0.09,-20.97,69.87,34.24,172769.0,-65616.0,247272.0,1972.00,-37.95,44.0,X-LC,18.81,3.0,-0.38,1.66,6.02,X40,NTT,IT
81,TMPV,-1.76,-10.34,52.32,36.58,166932.0,-36782.0,319059.0,600.00,-81.44,70.0,X-LC,21.33,4.0,-0.22,2.14,32.98,XY24,NTT,AUTO
59,PIDILITIND,0.14,5.08,12.64,18.37,18743.0,7170.0,148280.0,1670.26,-26.41,63.0,X-LC,4.98,5.0,0.38,0.99,16.43,X40,ATH,CHEMICALS

In [22]:
# top 5 for average up
df_tmp = df_portfolio_features[(df_portfolio_features['Dev%_200'] > 5)].sort_values(by = 'CurrAlloc%', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
44,INDUSINDBK,-1.93,-32.50,96.86,32.89,50481.0,-25088.0,52118.0,1800.00,-345.10,54.0,L-MC,8.72,258.0,-0.50,0.35,28.28,XR,NTT,BANKS
72,SIS,2.00,-7.49,31.08,21.26,31924.0,-8318.0,102714.0,528.00,2445.08,65.0,H-SC,17.62,168.0,-0.26,0.69,52.72,OX40N,NTT,MISC
73,SONACOMS,-1.82,5.09,32.36,39.09,34400.0,5145.0,106304.0,804.02,-16.69,60.0,M-MC,18.69,193.0,0.15,0.71,50.38,AR,ATH,AUTO
75,SURYODAY,-1.33,-6.82,32.04,23.03,53463.0,-12209.0,166862.0,216.00,82.02,57.0,H-SC,18.43,166.0,-0.23,1.12,40.49,XR,NTT,BANKS
37,HONAUT,-1.82,-7.90,64.29,51.31,114179.0,-15238.0,177600.0,58357.33,-23.38,67.0,X-SC,10.04,90.0,-0.13,1.19,34.93,X40N,ATH,ELECTRICAL

In [23]:
# top 5 RSP
df_tmp = df_portfolio_features.sort_values(by = 'RSP', ascending=False)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
18,COFFEEDAY,19.97,-41.19,130.02,35.27,86825.0,-46771.0,66778.0,80.00,-55.73,83.0,L-SC,25.01,266.0,-0.54,0.45,64.68,XR,NTT,HOTELS
68,SATIN,-1.81,20.70,25.79,51.83,86005.0,57198.0,333482.0,274.00,7.75,63.0,H-SC,36.13,159.0,0.67,2.23,62.46,XY24,NTT,FINANCE
91,ZYDUSLIFE,-0.75,13.65,19.34,35.63,46062.0,28598.0,238172.0,1286.17,-0.90,73.0,H-MC,5.49,120.0,0.62,1.60,25.23,AR,ATH,PHARMA
69,SFL,-3.36,-40.47,112.73,26.63,175960.0,-106128.0,156090.0,1287.00,18.16,58.0,M-SC,10.11,242.0,-0.60,1.05,30.09,XY24,NTT,MISC
64,RELAXO,14.34,-55.28,240.57,52.31,156168.0,-80244.0,64916.0,1176.00,-52.38,76.0,X-SC,24.34,92.0,-0.51,0.43,45.15,X40N,NTT,FOOTWEAR

In [24]:
# Top N allocation
df_tmp = df_portfolio_features.sort_values(by = 'CurrAlloc%', ascending=False)
top_n_values = [10, 25, 50]

sum_df = pd.DataFrame({
    'Top_N': top_n_values,
    'Sum_Alloc%': [df_tmp['CurrAlloc%'].head(n).sum() for n in top_n_values]
})

sum_df

   Top_N  Sum_Alloc%
0     10       19.57
1     25       42.71
2     50       72.74

In [25]:
# market-cap-wise allocation
df_tmp = df_portfolio_features[cols]
df_tmp.groupby(df_tmp['Conviction'].str[-2:])['CurrAlloc%'].sum().sort_values(ascending=False)

Conviction
SC    43.02
LC    31.49
MC    25.49
Name: CurrAlloc%, dtype: float64

In [26]:
# criteria-wise allocation
df_portfolio_features.groupby('Criteria')['CurrAlloc%'].sum().sort_values(ascending=False)

Criteria
XY24     27.55
X40      25.11
X40N     17.03
XR        9.04
OX40N     7.06
AR        6.94
XY25      6.45
SR        0.82
Name: CurrAlloc%, dtype: float64

In [27]:
# conviction-wise allocation
df_portfolio_features.groupby('Conviction')['CurrAlloc%'].sum().sort_values(ascending=False)

Conviction
X-LC    29.25
H-SC    22.46
X-MC    20.48
M-SC    10.03
X-SC     9.87
H-MC     2.71
M-MC     1.95
H-LC     1.29
M-LC     0.95
L-SC     0.66
L-MC     0.35
Name: CurrAlloc%, dtype: float64

In [28]:
# sector-wise stats
df_tmp = df_portfolio_features.groupby('Category')[['CurrAlloc%', 'Current', 'Current P/L', 'FTT Amt']].sum().sort_values(by=['Current', 'Current P/L'], ascending=False)
df_tmp['Current P/L%'] = round(df_tmp['Current P/L'] * 100 / df_tmp['Current'], 2)
df_tmp['FTT%'] = round(df_tmp['FTT Amt'] * 100 / df_tmp['Current'], 2)
cols = ['CurrAlloc%', 'Current P/L%', 'FTT%']
df_tmp[cols].sort_values(by=['CurrAlloc%'], ascending=False)

               CurrAlloc%  Current P/L%    FTT%
Category
FMCG                15.01        -18.07   59.68
FINANCE             10.75        -14.87   64.83
IT                  10.31        -46.70  120.05
MISC                 6.97        -29.15   85.25
AUTO                 6.90         -6.50   46.42
BANKS                5.69         -6.91   56.35
PAINTS               5.55        -18.81   39.44
INSURANCE            5.27         -5.19   40.99
PHARMA               5.02          1.20   30.56
ELECTRICAL           4.14        -14.59   55.03
CHEMICALS            2.15        -26.64  102.11
HEALTHCARE           1.98        -20.62   52.10
APPARELS             1.79         -0.38   34.09
AC                   1.77        -20.56   53.25
FOOTWEAR             1.77        -66.95  133.89
DURABLES             1.59        -62.80  102.40
TRAVEL               1.58        -89.48  184.36
BREWERIES            1.46         -7.19   29.45
CABLES               1.42         30.52   44.46
REALTY               1.39         -6.70   24.23
CERAMICS             1.33        -54.69  101.69
ENGINEERING          1.26        -28.57   87.38
REFINERIES           1.14        -17.91   47.74
CEMENT               1.13        -59.68  179.14
JEWELLERY            1.05       -103.85  174.68
ENTERTAINMENT        0.73        -77.19  182.88
HOTELS               0.45        -70.04  130.02
TEXTILES             0.40        -55.37   99.67

In [29]:
# money to be made criteria-wise
df_portfolio_features.groupby('Criteria')['FTT Amt'].agg(['sum', 'count']).sort_values(by='sum', ascending=False)

                sum  count
Criteria
XY24      3484922.0     21
X40       1942907.0     19
XR        1334757.0     13
X40N      1182317.0     13
AR        1150572.0      9
OX40N      736655.0     10
XY25       476045.0      5
SR         296988.0      2

In [30]:
# money to be made conviction-wise
df_portfolio_features.groupby('Conviction')['FTT Amt'].agg(['sum', 'count']).sort_values(by='sum', ascending=False)

                  sum  count
Conviction
H-SC        3434670.0     24
X-LC        1926580.0     21
X-MC        1671081.0     15
M-SC        1421846.0     14
X-SC        1328898.0      9
H-MC         293550.0      2
L-SC         192736.0      2
M-LC         149946.0      1
M-MC          93994.0      2
L-MC          50481.0      1
H-LC          41381.0      1

In [31]:
# money to be made criteria and conviction-wise
df_portfolio_features.groupby(['Conviction', 'Criteria'])['FTT Amt'].agg(['sum', 'count']).sort_values(by='sum', ascending=False)

                           sum  count
Conviction Criteria
H-SC       XY24      1050525.0      6
X-LC       X40       1040460.0     10
H-SC       AR         952951.0      5
M-SC       XY24       847842.0      6
H-SC       XR         809333.0      7
X-SC       XY24       798924.0      4
X-MC       X40        695137.0      7
           X40N       491079.0      4
X-LC       X40N       368574.0      6
H-SC       OX40N      324873.0      4
X-SC       X40N       322664.0      3
X-LC       XY24       313505.0      2
M-SC       OX40N      305871.0      5
H-SC       SR         296988.0      2
X-MC       XY25       258227.0      2
H-MC       XY24       247488.0      1
X-MC       XY24       226638.0      2
X-SC       X40        207310.0      2
M-SC       XR         192355.0      2
X-LC       XY25       158224.0      2
M-LC       XR         149946.0      1
L-SC       OX40N      105911.0      1
           XR          86825.0      1
M-SC       AR          75778.0      1
M-MC       XY25        59594.0      1
L-MC       XR          50481.0      1
H-MC       AR          46062.0      1
X-LC       XR          45817.0      1
H-LC       AR          41381.0      1
M-MC       AR          34400.0      1

In [32]:
# notebook execution time

end_time = time.time()
execution_time = round(end_time - start_time, 0)
print(f"Notebook execution time: {execution_time} seconds")

Notebook execution time: 45.0 seconds