<a href="https://colab.research.google.com/github/ankit-rathi/Quantvesting_v2/blob/main/myStocks_Portfolio_Analysis.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
'''
!pip install pandas==2.2.2 -qq
!pip install pyxirr -qq
!pip install ta -qq
!pip install yfinance==0.2.59 -qq
'''

'\n!pip install pandas==2.2.2 -qq\n!pip install pyxirr -qq\n!pip install ta -qq\n!pip install yfinance==0.2.59 -qq\n'

In [2]:
# import libraries

import numpy as np
import pandas as pd
import datetime
import warnings
warnings.filterwarnings('ignore')
import yfinance as yfin
import ta
import matplotlib.pyplot as plt
import requests

In [3]:
# notebook start time
import time
import datetime
import pytz

start_time = time.time()

# function to print date timestamp
def print_date_time():
  tz_NY = pytz.timezone('Asia/Kolkata')
  datetime_NY = datetime.datetime.now(tz_NY)
  print("Run date time (IST):", datetime_NY.strftime("%Y-%m-%d %H:%M:%S"))

In [4]:
# function to get booked and reserved amount
def get_amt():
  # fetch the JSON data from the URL
  url = "https://raw.githubusercontent.com/ankit-rathi/Tradevesting_v1/main/data/myPortfolioAmts.json"
  response = requests.get(url)
  pf_amts = response.json()  # parse the JSON data

  # extract values from the JSON
  py_booked_amt_dm = pf_amts["py_booked_amt_dm"]
  py_booked_amt_sv = pf_amts["py_booked_amt_sv"]
  cy_booked_amt_dm = pf_amts["cy_booked_amt_dm"]
  cy_booked_amt_sv = pf_amts["cy_booked_amt_sv"]
  reserve_amt_dm = pf_amts["reserve_amt_dm"]
  reserve_amt_sv = pf_amts["reserve_amt_sv"]

  # perform calculations
  py_booked_amt = py_booked_amt_dm + py_booked_amt_sv
  cy_booked_amt = cy_booked_amt_dm + cy_booked_amt_sv
  reserve_amt = reserve_amt_dm + reserve_amt_sv
  total_booked_amt = py_booked_amt + cy_booked_amt

  return total_booked_amt, reserve_amt, cy_booked_amt, py_booked_amt

gen_output = 0

In [5]:
# function to format the amount
def format_amt(number):
    abs_number = abs(number)

    if abs_number >= 1_00_00_000:  # Crores
        formatted_amt = f"{number / 1_00_00_000:.2f} C"
    elif abs_number >= 1_00_000:  # Lakhs
        formatted_amt = f"{number / 1_00_000:.2f} L"
    elif abs_number >= 1_000:  # Thousands
        formatted_amt = f"{number / 1_000:.2f} K"
    else:
        formatted_amt = f"{number:.2f}"

    return formatted_amt

# function to set start and end date
def get_start_end_date():
  start_date = (datetime.date.today() + datetime.timedelta(days=-365)).strftime('%Y-%m-%d')
  end_date = (datetime.date.today() + datetime.timedelta(days=1)).strftime('%Y-%m-%d')
  return start_date, end_date

# function to fetch my portfolio csv
def get_mypfs_df():
  mypfs_df = pd.read_csv('https://raw.githubusercontent.com/ankit-rathi/Tradevesting_v1/main/data/myPortfolioStocks.csv')
  return mypfs_df

# function to fetch my prospects csv
def get_mypps_df():
  mypps_df = pd.read_csv('https://raw.githubusercontent.com/ankit-rathi/Tradevesting_v1/main/data/myProspectsScrips.csv')
  return mypps_df

# function to fetch screener data
def get_myscreen_df():
  myscreen_df = pd.read_csv('https://raw.githubusercontent.com/ankit-rathi/Tradevesting_v1/main/data/myScreenerDB.csv')
  return myscreen_df

# function to fetch momentum data
def get_myinvmt_df():
  myinvmt_df = pd.read_csv('https://raw.githubusercontent.com/ankit-rathi/Tradevesting_v1/main/data/myInvestments.csv')
  return myinvmt_df

# function to get the stock ids
def get_stock_ids(df_pf):
  stock_n100 = df_pf['Symbol'].unique()

  exclude = ['CADILAHC','MMTC', 'MASFIN']

  stock_ids = df_pf[~df_pf['Symbol'].isin(exclude) ]['Symbol'].unique()

  #mypf = mypf[mypf.Forecast.notnull()]
  #stock_ids = mypf['Symbol'].unique()

  #stock_ids.sort()
  return stock_ids

# get features from screener data
def get_screener_features():
  myscreen_df = get_myscreen_df()
  cols = ['Symbol', 'EPS', 'MedPE', 'ROCE%', 'ROE%', 'CapType']
  return myscreen_df[cols]

# get relative strength
def get_relative_strength(stock_list):

    # Dictionary to store stock tickers and their corresponding percentage price change
    stock_changes = {}

    # Loop through each stock and fetch its price data
    for stock in stock_list:
        try:
            # Download the stock data for the given date range
            stock_data = yfin.Ticker(stock + '.NS').history(period='1mo', interval='1d')[map(str.title, ['open', 'close', 'low', 'high', 'volume'])]

            # Calculate the percentage change for the stock
            if len(stock_data) > 0:
                start_price = stock_data['Close'].iloc[0]
                end_price = stock_data['Close'].iloc[-1]
                percent_change = round(((end_price - start_price) / start_price) * 100, 2)
                stock_changes[stock] = percent_change
            else:
                stock_changes[stock] = np.nan  # If no data is available, set to NaN

        except Exception as e:
            print(f"Error fetching data for {stock}: {e}")
            stock_changes[stock] = np.nan

    # Create a DataFrame with stock tickers and their percentage changes
    df = pd.DataFrame(list(stock_changes.items()), columns=['Symbol', 'Percent_Change'])

    # Drop any stocks with missing data (NaN values)
    df = df.dropna()

    # Calculate the percentile rank based on percentage change
    df['RSP'] = round(df['Percent_Change'].rank(pct=True) * 100, 2)
    cols = ['Symbol', 'RSP']
    df = df[cols]
    # Sort by percentile rank (optional)
    df = df.sort_values(by='RSP', ascending=False).reset_index(drop=True)

    return df

In [6]:
# function to get stock technicals
def stock_prec_dev(stock_symbol):
    #stock_symbol = 'ULTRACEMCO.NS'
    short_window = 20
    mid_window = 50
    long_window = 200
    moving_avg = 'SMA'

    start = datetime.datetime(*map(int, start_date.split('-')))
    end = datetime.datetime(*map(int, end_date.split('-')))

    stock_df = yfin.Ticker(stock_symbol + '.NS').history(period='max', interval='1d')[map(str.title, ['open', 'close', 'low', 'high', 'volume'])]

    stock_df['Max'] = round(max(stock_df['Close']),2)
    stock_df = stock_df[(stock_df.index <= end_date) & (stock_df.index >= start_date)]
    stock_df['200_SMA'] = round(stock_df['Close'].rolling(window = 200, min_periods = 1).mean(),0)
    stock_df['Dev%_200'] = round((stock_df['Close'] - stock_df['200_SMA'])*100/stock_df['200_SMA'],2)
    stock_df.dropna(axis = 0, inplace = True) # remove any null rows

    stock_df['20_SMA'] = stock_df['Close'].rolling(window=20).mean()
    stock_df['50_SMA'] = stock_df['Close'].rolling(window=50).mean()
    stock_df['Symbol'] = stock_symbol

    stock_df['Close'] = round(stock_df['Close'],2)
    stock_df['Min'] = round(min(stock_df['Close']),2)
    stock_df['RSI_14'] = ta.momentum.RSIIndicator(close=stock_df['Close'], window=14).rsi()
    stock_df['RSI_14'] = round(stock_df['RSI_14'],0)
    stock_df['Prev_Close'] = stock_df['Close'].shift(1)
    stock_df.drop(['Open', 'Low', 'High', 'Volume'], axis=1, inplace=True)
    stock_df = stock_df.tail(1)

    max_SMA = max(stock_df['20_SMA'].item(), stock_df['50_SMA'].item(), stock_df['200_SMA'].item())
    min_SMA = min(stock_df['20_SMA'].item(), stock_df['50_SMA'].item(), stock_df['200_SMA'].item())
    ABS_Spread = max_SMA - min_SMA
    stock_df['Spread%'] = round((ABS_Spread / stock_df['200_SMA'].item()) * 100,2)

    return stock_df

# function to compute stock attributes
def get_common_features(stock_ids, df_mypf):

  df_prec_dev = pd.DataFrame()
  df_tmp = get_screener_features()
  df_rs = get_relative_strength(stock_ids)

  for stock_id in stock_ids:
      tmp = stock_prec_dev(stock_id)
      tmp = tmp.reset_index()
      df_prec_dev = pd.concat([df_prec_dev, tmp], ignore_index = True)
  df_prec_dev = pd.merge(df_prec_dev, df_mypf, on= 'Symbol')
  df_prec_dev = pd.merge(df_prec_dev, df_tmp, on= 'Symbol', how='left')
  df_prec_dev = pd.merge(df_prec_dev, df_rs, on= 'Symbol', how='left')
  #print(df_prec_dev.columns)
  df_prec_dev['Curr_PE'] = round(df_prec_dev['Close']/df_prec_dev['EPS'],1)
  df_prec_dev['Dev%_PE'] = round((df_prec_dev['Curr_PE'] - df_prec_dev['MedPE'])*100/df_prec_dev['MedPE'],2)
  df_prec_dev['Conviction'] = df_prec_dev['Conviction'] + '-' + df_prec_dev['CapType']
  return df_prec_dev

# function to arrange stock features
def arrange_features(df_stocks, common_cols, diff_cols):
  df_stocks_common = df_stocks[common_cols].drop_duplicates()
  df_stocks_diff = df_stocks[diff_cols]
  df_stocks_diff['Investment'] = df_stocks_diff['AvgCost'] * df_stocks_diff['Shares']
  df_stocks_diff = df_stocks_diff.groupby(['Symbol'])[['Shares', 'Investment']].aggregate(['sum']).reset_index()
  df_stocks_diff.columns = ['Symbol', 'Shares', 'Investment']
  df_stocks_diff['AvgCost'] = round(df_stocks_diff['Investment']/df_stocks_diff['Shares'],2)
  df_stocks = pd.merge(df_stocks_diff, df_stocks_common, on='Symbol')
  return df_stocks

# plot fact distribution across dimension
def plot_pie_chart(df, dimension, fact):
  # grouping the data by category and calculating the sum of fact for each type
  grouped_data = df.groupby(dimension)[fact].sum()

  # sorting the grouped data in descending order
  grouped_data = grouped_data.sort_values(ascending=False)

  # creating a pie chart
  grouped_data.plot.pie(autopct='%1.1f%%', startangle=90, figsize=(6, 6))

  # adding a title and displaying the plot
  plt.title(f'{dimension} {fact} Distribution')
  plt.ylabel('')  # To hide the y-label
  plt.show()

In [7]:
# function to get portfolio features

def get_portfolio_features(df_common_features):

  print_date_time()
  print('-------------------')

  #df_common_features["Target"] = df_common_features["Target"].fillna(df_common_features["Max"])
  df_common_features['NTT'] = np.where(df_common_features['Strategy']== 'NTT', df_common_features["Target"], df_common_features['Max'])
  df_common_features['LTT'] = np.where(df_common_features['Strategy']== 'BTT', df_common_features["Target"], df_common_features['Max'])
  df_common_features['BOL'] = df_common_features['Min']

  tmp_df = df_common_features[df_common_features['Symbol'].isin(mypf_df[mypf_df['InPortfolio'] != 'NA'].Symbol.values)]
  print('qualified stocks: '+str(len(tmp_df['Symbol'].unique())))
  tmp_df1 = tmp_df[tmp_df['LatestQtr'] == 1]
  print('with latest results: '+str(len(tmp_df1['Symbol'].unique())))
  tmp_df1 = tmp_df1[tmp_df1['StarStock'] == 1]
  print('still star stocks: '+str(len(tmp_df1['Symbol'].unique())))
  tmp_df['Investment'] = tmp_df['AvgCost'] * tmp_df['Shares']
  tmp_df['Current'] = round(tmp_df['Close'] * tmp_df['Shares'],0)
  tmp_df['Previous'] = tmp_df['Prev_Close'] * tmp_df['Shares']
  tmp_df['EstimatedST'] = tmp_df['NTT'] * tmp_df['Shares']
  tmp_df['EstimatedLT'] = tmp_df['LTT'] * tmp_df['Shares']
  tmp_df['Current P/L'] = round((tmp_df['Current'] - tmp_df['Investment']),0)
  tmp_df['Today P/L%'] = round((tmp_df['Current'] - tmp_df['Previous'])*100/tmp_df['Previous'],2)
  tmp_df['Current P/L%'] = round((tmp_df['Current'] - tmp_df['Investment'])*100/tmp_df['Investment'],2)
  tmp_df['EstimatedST P/L%'] = round((tmp_df['EstimatedST'] - tmp_df['Investment'])*100/tmp_df['Investment'],2)
  tmp_df['EstimatedLT P/L%'] = round((tmp_df['EstimatedLT'] - tmp_df['Investment'])*100/tmp_df['Investment'],2)
  tmp_df['NTT%'] = round((tmp_df['NTT'] - tmp_df['Close'])*100/tmp_df['Close'],2)
  tmp_df['LTT%'] = round((tmp_df['LTT'] - tmp_df['Close'])*100/tmp_df['Close'],2)
  tmp_df['Gained%'] = round((tmp_df['Close'] - tmp_df['BOL'])*100/tmp_df['BOL'],2)
  investment = round(sum(tmp_df['AvgCost']*tmp_df['Shares']),0)
  current = round(sum(tmp_df['Close']*tmp_df['Shares']),0)
  tmp_df['InitAlloc%'] = round(tmp_df['Investment']*100/investment,2)
  tmp_df['CurrAlloc%'] = round(tmp_df['Current']*100/current,2)
  tmp_df['FTT'] = tmp_df['LTT']
  tmp_df.loc[tmp_df['Strategy'] == 'NTT', 'FTT'] = tmp_df['NTT']
  tmp_df['FTT%'] = tmp_df['LTT%']
  tmp_df.loc[tmp_df['Strategy'] == 'NTT', 'FTT%'] = tmp_df['NTT%']
  tmp_df['FTT Amt'] = round(tmp_df['FTT%'] * tmp_df['Current']/100,0)
  tmp_df['OTT%'] = round((tmp_df['FTT'] - tmp_df['AvgCost'])*100/tmp_df['AvgCost'],2)
  tmp_df['RRR Ind'] = round(tmp_df['Current P/L']/tmp_df['FTT Amt'],2)
  tmp_df['Risk Ind'] = round(tmp_df['Current P/L%']*tmp_df['CurrAlloc%'],0)

  return tmp_df

# function to print portfolio features
def print_portfolio_stats(df_portfolio_features, myinvmt_df):
  from pyxirr import xirr

  total_booked_amt, reserve_amt, cy_booked_amt, py_booked_amt = get_amt()

  dates = myinvmt_df['Date'].values
  dates = np.append(dates, datetime.date.today().strftime('%d-%b-%y'))
  investment = myinvmt_df['Investment'].values
  dates= pd.to_datetime(dates)

  current = round(sum(df_portfolio_features['Close']*df_portfolio_features['Shares']),0) + reserve_amt
  investment_xirr = np.append(investment, current)
  cagr = round(xirr(pd.DataFrame({"dates": dates, "amounts": investment_xirr}))*100,2)

  investment = -sum(investment)
  invested = round(sum(df_portfolio_features['AvgCost']*df_portfolio_features['Shares']),0) + reserve_amt
  previous = round(sum(df_portfolio_features['Prev_Close']*df_portfolio_features['Shares']),0) + reserve_amt
  cy_invested = investment + py_booked_amt

  today_pnl_amount = current-previous
  today_pnl_percentage = round((current-previous)*100/previous,2)

  curr_pnl_amount = current-invested
  curr_pnl_percentage = round((curr_pnl_amount)*100/(cy_invested),2)

  cy_pnl_amount = cy_booked_amt + curr_pnl_amount
  cy_pnl_percentage = round((cy_pnl_amount)*100/cy_invested,2)

  overall_pnl_amount = total_booked_amt + curr_pnl_amount
  overall_pnl_percentage = round((overall_pnl_amount)*100/investment,2)

  estimate_st = round(sum(df_portfolio_features['FTT']*df_portfolio_features['Shares']),0)  + reserve_amt
  est_st_pnl_amount = estimate_st-current
  est_st_pnl_percentage = round((est_st_pnl_amount)*100/current,2)

  estimate_lt = round(sum(df_portfolio_features['LTT']*df_portfolio_features['Shares']),0)  + reserve_amt
  est_lt_pnl_amount = estimate_lt-current
  est_lt_pnl_percentage = round((est_lt_pnl_amount)*100/current,2)

  total_profit = round(sum(df_portfolio_features[df_portfolio_features['Current P/L%'] > 0]['Current']) - sum(df_portfolio_features[df_portfolio_features['Current P/L%'] > 0]['Investment']),0)
  total_loss = round(sum(df_portfolio_features[df_portfolio_features['Current P/L%'] < 0]['Current']) - sum(df_portfolio_features[df_portfolio_features['Current P/L%'] < 0]['Investment']),0)

  cy_booked_percentage = round((cy_booked_amt)*100/current,2)
  py_booked_percentage = round((py_booked_amt)*100/investment,2)
  total_booked_percentage = round((total_booked_amt)*100/investment,2)

  print('-------------------')
  print('Initial Investment: ', format_amt(investment))
  print('CY Investment: ', format_amt(cy_invested))
  print('Reserve: ', format_amt(reserve_amt))
  print('Current: ',  format_amt(current))
  print('-------------------')
  print('Today PnL: '+ '{} ({}%)'.format(format_amt(today_pnl_amount), today_pnl_percentage))
  print('Current PnL: '+ '{} ({}%)'.format(format_amt(curr_pnl_amount), curr_pnl_percentage))
  print('CY Booked + Current PnL: '+ '{} ({}%)'.format(format_amt(cy_pnl_amount), cy_pnl_percentage))
  print('-------------------')
  print('Total profit: ', format_amt(total_profit))
  print('Total loss: ', format_amt(total_loss))
  print('-------------------')
  print('Total Booked + Current PnL: '+ '{} ({}%)'.format(format_amt(overall_pnl_amount), overall_pnl_percentage))
  print('Total Booked PnL: '+ '{} ({}%)'.format(format_amt(total_booked_amt), total_booked_percentage))
  print('Curr Year Booked PnL: '+ '{} ({}%)'.format(format_amt(cy_booked_amt), cy_booked_percentage))
  print('Prev Year Booked PnL: '+ '{} ({}%)'.format(format_amt(py_booked_amt), py_booked_percentage))
  print('===================')
  print('Est FTT: ',  format_amt(estimate_st))
  print('Est FTT PnL: '+ '{} ({}%)'.format(format_amt(est_st_pnl_amount), est_st_pnl_percentage))

  print('===================')
  print('Deployed: ', format_amt(investment))

  print('Current: ', format_amt(current))

  print('CAGR/XIRR %: '+'{}%'.format(cagr))

In [8]:
# get start and end date
start_date, end_date = get_start_end_date()

# get portfolio and prospects data
mypfs_df = get_mypfs_df()
mypps_df = get_mypps_df()
myinvmt_df = get_myinvmt_df()

# merge above datasets
mypf_df = pd.merge(mypfs_df, mypps_df, on="Symbol")

# seggregate dm and sv portfolio
dm_pf = mypf_df[mypf_df['InPortfolio'] == 'DM']
sv_pf = mypf_df[mypf_df['InPortfolio'] == 'SV']

# build portfolio stock dataframe
dm_stocks = get_stock_ids(dm_pf)
sv_stocks = get_stock_ids(sv_pf)
df_stocks = pd.concat([dm_pf,sv_pf], ignore_index = True)

# arrange common and diff stock features
common_cols = ['Symbol', 'Target', 'Criteria', 'Strategy', 'CumlRnk', 'LatestQtr', 'StarStock', 'Conviction', 'Category', 'InFolio', 'XIRR', 'MBQ']
diff_cols = ['Symbol', 'AvgCost', 'Shares']
df_stocks = arrange_features(df_stocks, common_cols, diff_cols)

# get common features
stock_ids = df_stocks['Symbol'].values
df_common_features = get_common_features(stock_ids, df_stocks)

df_common_features.reset_index(drop=True, inplace=True)
df_common_features.drop(['Date'], axis=1, inplace=True)
# get and print portfolio features
df_portfolio_features = get_portfolio_features(df_common_features)

print_portfolio_stats(df_portfolio_features, myinvmt_df)

df = df_portfolio_features
#plot_pie_chart(df, 'CapType', 'Current')
list_ox40n = list(df[df['MBQ'].str.contains('OX40N', na=False)]['Symbol'].values)

Run date time (IST): 2026-03-19 15:32:40
-------------------
qualified stocks: 86
with latest results: 26
still star stocks: 16
-------------------
Initial Investment:  1.36 C
CY Investment:  1.62 C
Reserve:  1.61 K
Current:  1.31 C
-------------------
Today PnL: -3.58 L (-2.66%)
Current PnL: -46.18 L (-28.42%)
CY Booked + Current PnL: -30.29 L (-18.64%)
-------------------
Total profit:  58.26 K
Total loss:  -46.77 L
-------------------
Total Booked + Current PnL: -3.31 L (-2.45%)
Total Booked PnL: 42.87 L (31.64%)
Curr Year Booked PnL: 15.89 L (12.14%)
Prev Year Booked PnL: 26.98 L (19.91%)
===================
Est FTT:  2.48 C
Est FTT PnL: 1.17 C (89.31%)
===================
Deployed:  1.36 C
Current:  1.31 C
CAGR/XIRR %: -1.7%

In [9]:
# top 5 near their targets
cols = ['Symbol', 'Today P/L%', 'Current P/L%', 'FTT%', 'OTT%', 'FTT Amt', 'Current P/L', 'Current', 'FTT', 'Dev%_PE', 'RSI_14','Conviction', 'Spread%',  'CumlRnk', 'RRR Ind', 'CurrAlloc%', 'Gained%', 'Criteria', 'Strategy', 'Category']
df_tmp = df_portfolio_features[~df_portfolio_features['Symbol'].isin(['ENRIN','BLUSPRING','DIGITIDE'])]
df_tmp = df_tmp.sort_values(by = 'FTT Amt', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
50,MASFIN,-2.45,-10.32,35.55,21.57,31238.0,-10110.0,87870.0,397.04,-22.76,36.0,H-SC,1.87,167.0,-0.32,0.67,20.49,XR,ATH,FINANCE
77,TTKPRESTIG,1.41,-37.03,58.94,0.09,37405.0,-37314.0,63463.0,770.00,47.28,42.0,M-SC,17.52,250.0,-1.00,0.48,7.23,OX40N,NTT,DURABLES
37,ICICIGI,-2.14,-5.07,25.71,19.34,48839.0,-10146.0,189963.0,2252.93,-20.08,32.0,X-MC,2.54,66.0,-0.21,1.45,5.01,X40,ATH,INSURANCE
2,ABBOTINDIA,0.53,-11.05,32.74,18.07,52086.0,-19765.0,159090.0,35195.00,-24.24,44.0,X-MC,10.78,58.0,-0.38,1.22,0.86,X40,ATH,PHARMA
67,SONACOMS,-2.56,-13.73,61.22,39.09,53428.0,-13887.0,87272.0,804.02,-31.68,45.0,M-MC,8.39,193.0,-0.26,0.67,23.46,AR,ATH,AUTO

In [10]:
# top 5 today
df_tmp = df_portfolio_features.sort_values(by = 'Today P/L%', ascending=False)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
80,VALIANTORG,9.39,-46.09,223.03,74.15,196719.0,-75402.0,88203.0,838.00,-258.45,64.0,H-SC,29.19,145.0,-0.38,0.67,31.26,XR,NTT,CHEMICALS
77,TTKPRESTIG,1.41,-37.03,58.94,0.09,37405.0,-37314.0,63463.0,770.00,47.28,42.0,M-SC,17.52,250.0,-1.00,0.48,7.23,OX40N,NTT,DURABLES
27,GILLETTE,0.68,-5.66,37.50,29.72,89826.0,-14361.0,239535.0,10978.86,-27.56,42.0,X-SC,10.23,83.0,-0.16,1.83,5.44,X40,ATH,FMCG
2,ABBOTINDIA,0.53,-11.05,32.74,18.07,52086.0,-19765.0,159090.0,35195.00,-24.24,44.0,X-MC,10.78,58.0,-0.38,1.22,0.86,X40,ATH,PHARMA
69,SURYODAY,0.26,-27.40,69.48,23.03,90323.0,-49072.0,129999.0,216.00,42.54,48.0,H-SC,6.68,166.0,-0.54,0.99,27.06,XR,NTT,BANKS

In [11]:
# bottom 5 today
df_tmp = df_portfolio_features.sort_values(by = 'Today P/L%', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
19,COFFEEDAY,-6.36,-59.71,235.71,35.27,107847.0,-67795.0,45754.0,80.00,-69.82,25.0,L-SC,24.67,266.0,-0.63,0.35,0.00,XR,NTT,HOTELS
34,HDFCBANK,-5.32,-4.51,34.43,28.37,77224.0,-10591.0,224294.0,1073.00,-19.05,27.0,X-LC,10.16,26.0,-0.14,1.71,0.00,X40,BTT,BANKS
82,VOLTAS,-5.30,5.39,37.77,45.20,76326.0,10338.0,202080.0,1856.00,20.60,35.0,X-MC,6.67,79.0,0.14,1.54,12.56,XY25,NTT,AC
79,VAIBHAVGBL,-5.18,-37.35,156.62,60.77,179335.0,-68272.0,114503.0,521.00,32.23,37.0,H-SC,5.24,160.0,-0.38,0.87,3.81,XR,NTT,JEWELLERY
23,DIXON,-4.81,-25.73,85.71,37.92,166008.0,-67112.0,193686.0,18931.72,-68.46,44.0,X-MC,27.40,54.0,-0.40,1.48,3.98,X40N,ATH,IT

In [12]:
# top 5 to exit based on CumlRnk
df_tmp = df_portfolio_features[~df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])]
df_tmp = df_tmp[(df_tmp['Current P/L%'] > -1) & (df_tmp['Current P/L%'] < 1)].sort_values(by = 'CumlRnk', ascending=False)
df_tmp[cols].head()

Empty DataFrame
Columns: [Symbol, Today P/L%, Current P/L%, FTT%, OTT%, FTT Amt, Current P/L, Current, FTT, Dev%_PE, RSI_14, Conviction, Spread%, CumlRnk, RRR Ind, CurrAlloc%, Gained%, Criteria, Strategy, Category]
Index: []

In [13]:
# OX40N stocks to exit
df_tmp = df_portfolio_features[(df_portfolio_features['Symbol'].isin(list_ox40n))].sort_values(by = 'Current P/L%', ascending=False)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
26,FINCABLES,-3.10,7.63,93.17,107.91,148059.0,11269.0,158913.0,1641.55,-3.09,49.0,M-SC,8.07,220.0,0.08,1.21,19.56,OX40N,ATH,CABLES
66,SIS,-0.54,-36.14,89.89,21.26,63735.0,-40129.0,70903.0,528.00,1656.99,34.0,H-SC,13.53,168.0,-0.63,0.54,2.19,OX40N,NTT,MISC
77,TTKPRESTIG,1.41,-37.03,58.94,0.09,37405.0,-37314.0,63463.0,770.00,47.28,42.0,M-SC,17.52,250.0,-1.00,0.48,7.23,OX40N,NTT,DURABLES
18,CERA,-4.49,-37.78,99.12,23.89,108483.0,-66457.0,109446.0,9475.00,-39.86,46.0,H-SC,18.25,153.0,-0.61,0.84,5.18,OX40N,NTT,CERAMICS
70,SYMPHONY,-4.10,-40.08,66.84,-0.03,68542.0,-68594.0,102547.0,1306.00,-51.97,41.0,M-SC,14.94,205.0,-1.00,0.78,3.70,OX40N,NTT,DURABLES

In [14]:
# top 5 to book for rotation
df_tmp = df_portfolio_features[(df_portfolio_features['Current P/L%'] > 20) ].sort_values(by = 'CumlRnk', ascending=False)
df_tmp[cols].head()

Empty DataFrame
Columns: [Symbol, Today P/L%, Current P/L%, FTT%, OTT%, FTT Amt, Current P/L, Current, FTT, Dev%_PE, RSI_14, Conviction, Spread%, CumlRnk, RRR Ind, CurrAlloc%, Gained%, Criteria, Strategy, Category]
Index: []

In [15]:
# top 5 to monitor for exit
df_tmp = df_portfolio_features[~df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])]
df_tmp = df_tmp[(df_tmp['Current P/L%'] > 0) ].sort_values(by = 'Dev%_PE', ascending=False)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
26,FINCABLES,-3.10,7.63,93.17,107.91,148059.0,11269.0,158913.0,1641.55,-3.09,49.0,M-SC,8.07,220.0,0.08,1.21,19.56,OX40N,ATH,CABLES
1,ABB,-1.95,14.01,27.68,45.57,82562.0,36653.0,298272.0,7934.00,-26.69,58.0,H-MC,12.53,125.0,0.44,2.28,32.45,AR,NTT,ELECTRICAL

In [16]:
# top 5 to book for rotation from weak conviction
df_tmp = df_portfolio_features[~df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])]
df_tmp = df_tmp[~df_tmp['Criteria'].isin(['XY25','XY24','X40', 'X40N'])].sort_values(by = 'RRR Ind', ascending=False)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
1,ABB,-1.95,14.01,27.68,45.57,82562.0,36653.0,298272.0,7934.00,-26.69,58.0,H-MC,12.53,125.0,0.44,2.28,32.45,AR,NTT,ELECTRICAL
26,FINCABLES,-3.10,7.63,93.17,107.91,148059.0,11269.0,158913.0,1641.55,-3.09,49.0,M-SC,8.07,220.0,0.08,1.21,19.56,OX40N,ATH,CABLES
40,INDIAMART,-3.29,-12.81,137.09,106.72,147422.0,-15799.0,107537.0,4810.62,-60.74,35.0,H-SC,10.54,140.0,-0.11,0.82,7.57,AR,ATH,MISC
85,ZYDUSLIFE,-2.61,-7.61,46.80,35.63,90618.0,-15945.0,193629.0,1286.17,-19.37,40.0,H-MC,5.31,120.0,-0.18,1.48,7.80,AR,ATH,PHARMA
84,WIPRO,-3.03,-22.72,122.92,72.27,160958.0,-38503.0,130945.0,420.00,-30.18,27.0,M-LC,16.58,98.0,-0.24,1.00,0.00,XR,NTT,IT

In [17]:
# top 5 to accumulate based on lowest RSI_14
df_tmp = df_portfolio_features[df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])].sort_values(by = 'RSI_14', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
12,BATAINDIA,-3.74,-58.20,223.48,35.20,120188.0,-74890.0,53780.0,2096.00,-29.53,14.0,X-SC,29.33,91.0,-0.62,0.41,0.0,X40,NTT,FOOTWEAR
53,PGHH,-1.00,-25.67,77.61,32.01,123170.0,-54816.0,158704.0,17616.87,-49.68,15.0,X-MC,13.90,57.0,-0.45,1.21,0.0,X40,ATH,FMCG
58,RELAXO,-4.52,-64.68,331.24,52.31,169820.0,-93892.0,51268.0,1176.00,-62.44,20.0,X-SC,23.62,92.0,-0.55,0.39,0.0,X40N,NTT,FOOTWEAR
3,ACC,-3.72,-39.45,188.71,74.81,306367.0,-105780.0,162348.0,3906.00,-57.01,22.0,X-SC,15.89,85.0,-0.35,1.24,0.0,XY24,BTT,CEMENT
73,TCS,-3.47,-30.84,83.00,26.57,265945.0,-142857.0,320416.0,4311.59,-41.33,23.0,X-LC,16.33,2.0,-0.54,2.45,0.0,X40,ATH,IT

In [18]:
# top 5 to accumulate based on Spread and CumlRnk
df_tmp = df_portfolio_features[df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])]
df_tmp = df_tmp[(df_tmp['CumlRnk'] < 100)].sort_values(by = 'Spread%', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
78,UNITDSPR,-2.38,-5.32,27.55,20.77,61076.0,-12453.0,221691.0,1644.00,-16.02,39.0,X-MC,1.00,64.0,-0.20,1.69,1.03,X40N,NTT,BREWERIES
37,ICICIGI,-2.14,-5.07,25.71,19.34,48839.0,-10146.0,189963.0,2252.93,-20.08,32.0,X-MC,2.54,66.0,-0.21,1.45,5.01,X40,ATH,INSURANCE
38,ICICIPRULI,-4.38,-6.85,40.34,30.73,74026.0,-13500.0,183505.0,790.00,-31.92,24.0,X-MC,3.06,78.0,-0.18,1.40,4.98,X40,ATH,INSURANCE
59,RELIANCE,-1.65,-11.11,40.96,25.30,73171.0,-22324.0,178639.0,1952.00,-13.49,44.0,X-LC,3.37,21.0,-0.31,1.36,19.27,XY25,BTT,REFINERIES
65,SIEMENS,-4.41,-17.27,51.72,25.51,79623.0,-32145.0,153950.0,4671.50,29.40,42.0,H-LC,3.47,51.0,-0.40,1.18,13.37,AR,ATH,ELECTRICAL

In [19]:
# top 5 to accumulate based on lowest Gained%
df_tmp = df_portfolio_features[df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])].sort_values(by = 'Gained%', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
3,ACC,-3.72,-39.45,188.71,74.81,306367.0,-105780.0,162348.0,3906.00,-57.01,22.0,X-SC,15.89,85.0,-0.35,1.24,0.0,XY24,BTT,CEMENT
6,ASIANPAINT,-3.36,-21.33,58.29,24.52,129970.0,-60467.0,222972.0,3460.25,-20.69,32.0,X-LC,8.44,30.0,-0.47,1.70,0.0,X40,ATH,PAINTS
12,BATAINDIA,-3.74,-58.20,223.48,35.20,120188.0,-74890.0,53780.0,2096.00,-29.53,14.0,X-SC,29.33,91.0,-0.62,0.41,0.0,X40,NTT,FOOTWEAR
21,DABUR,-4.79,-15.89,70.85,43.70,147826.0,-39421.0,208647.0,735.00,-23.72,24.0,X-MC,4.03,70.0,-0.27,1.59,0.0,XY24,BTT,FMCG
20,COLPAL,-2.67,-28.25,97.22,41.51,183717.0,-74395.0,188970.0,3726.84,-13.25,27.0,X-MC,4.39,62.0,-0.40,1.44,0.0,XY25,ATH,FMCG

In [20]:
# top 5 to accumulate based on lowest CurrAlloc%
df_tmp = df_portfolio_features[df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])].sort_values(by = 'CurrAlloc%', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
58,RELAXO,-4.52,-64.68,331.24,52.31,169820.0,-93892.0,51268.0,1176.00,-62.44,20.0,X-SC,23.62,92.0,-0.55,0.39,0.00,X40N,NTT,FOOTWEAR
12,BATAINDIA,-3.74,-58.20,223.48,35.20,120188.0,-74890.0,53780.0,2096.00,-29.53,14.0,X-SC,29.33,91.0,-0.62,0.41,0.00,X40,NTT,FOOTWEAR
54,QUESS,-2.07,-26.64,137.06,73.90,107374.0,-28452.0,78341.0,424.00,-60.33,37.0,X-SC,20.27,80.0,-0.26,0.60,2.09,XY24,NTT,MISC
36,HONAUT,-2.70,-26.22,105.09,51.31,149517.0,-50563.0,142275.0,58357.33,-38.65,27.0,X-SC,14.78,90.0,-0.34,1.09,0.00,X40N,ATH,ELECTRICAL
51,MEDANTA,-2.82,-13.21,46.46,27.12,71179.0,-23312.0,153205.0,1486.00,-15.82,29.0,X-SC,10.56,87.0,-0.33,1.17,0.00,XY24,NTT,HEALTHCARE

In [21]:
# top 5 to accumulate based on CumlRnk
df_tmp = df_portfolio_features.sort_values(by = 'CumlRnk', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
45,ITC,-1.99,-21.51,51.68,19.06,137990.0,-73158.0,267008.0,452.00,-56.73,33.0,X-LC,17.59,1.0,-0.53,2.04,0.0,X40,NTT,FMCG
73,TCS,-3.47,-30.84,83.00,26.57,265945.0,-142857.0,320416.0,4311.59,-41.33,23.0,X-LC,16.33,2.0,-0.54,2.45,0.0,X40,ATH,IT
43,INFY,-3.65,-16.89,61.53,34.24,159996.0,-52858.0,260030.0,1972.00,-34.69,27.0,X-LC,14.55,3.0,-0.33,1.99,0.0,X40,NTT,IT
75,TMPV,-4.76,-29.59,93.99,36.58,235476.0,-105308.0,250533.0,600.00,-85.81,31.0,X-LC,4.44,4.0,-0.45,1.91,0.0,XY24,NTT,AUTO
33,HCLTECH,-3.34,-14.87,45.46,23.83,93626.0,-35971.0,205953.0,1908.19,-10.67,31.0,X-LC,11.27,8.0,-0.38,1.57,0.0,X40,ATH,IT

In [22]:
# top 5 for average up
df_tmp = df_portfolio_features[(df_portfolio_features['Dev%_200'] > 5)].sort_values(by = 'CurrAlloc%', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
1,ABB,-1.95,14.01,27.68,45.57,82562.0,36653.0,298272.0,7934.0,-26.69,58.0,H-MC,12.53,125.0,0.44,2.28,32.45,AR,NTT,ELECTRICAL

In [23]:
# top 5 RSP
df_tmp = df_portfolio_features.sort_values(by = 'RSP', ascending=False)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
1,ABB,-1.95,14.01,27.68,45.57,82562.0,36653.0,298272.0,7934.00,-26.69,58.0,H-MC,12.53,125.0,0.44,2.28,32.45,AR,NTT,ELECTRICAL
80,VALIANTORG,9.39,-46.09,223.03,74.15,196719.0,-75402.0,88203.0,838.00,-258.45,64.0,H-SC,29.19,145.0,-0.38,0.67,31.26,XR,NTT,CHEMICALS
26,FINCABLES,-3.10,7.63,93.17,107.91,148059.0,11269.0,158913.0,1641.55,-3.09,49.0,M-SC,8.07,220.0,0.08,1.21,19.56,OX40N,ATH,CABLES
69,SURYODAY,0.26,-27.40,69.48,23.03,90323.0,-49072.0,129999.0,216.00,42.54,48.0,H-SC,6.68,166.0,-0.54,0.99,27.06,XR,NTT,BANKS
2,ABBOTINDIA,0.53,-11.05,32.74,18.07,52086.0,-19765.0,159090.0,35195.00,-24.24,44.0,X-MC,10.78,58.0,-0.38,1.22,0.86,X40,ATH,PHARMA

In [24]:
# Top N allocation
df_tmp = df_portfolio_features.sort_values(by = 'CurrAlloc%', ascending=False)
top_n_values = [10, 25, 50]

sum_df = pd.DataFrame({
    'Top_N': top_n_values,
    'Sum_Alloc%': [df_tmp['CurrAlloc%'].head(n).sum() for n in top_n_values]
})

sum_df

   Top_N  Sum_Alloc%
0     10       20.65
1     25       45.54
2     50       77.93

In [25]:
# market-cap-wise allocation
df_tmp = df_portfolio_features[cols]
df_tmp.groupby(df_tmp['Conviction'].str[-2:])['CurrAlloc%'].sum().sort_values(ascending=False)

Conviction
SC    44.52
MC    30.19
LC    25.29
Name: CurrAlloc%, dtype: float64

In [26]:
# criteria-wise allocation
df_portfolio_features.groupby('Criteria')['CurrAlloc%'].sum().sort_values(ascending=False)

Criteria
XY24     26.96
X40      25.44
X40N     15.18
AR        9.16
XR        8.32
XY25      7.33
OX40N     6.82
SR        0.79
Name: CurrAlloc%, dtype: float64

In [27]:
# conviction-wise allocation
df_portfolio_features.groupby('Conviction')['CurrAlloc%'].sum().sort_values(ascending=False)

Conviction
X-LC    23.11
X-MC    22.69
H-SC    21.63
X-SC    12.21
M-SC    10.13
H-MC     5.07
M-MC     2.07
H-LC     1.18
M-LC     1.00
L-SC     0.55
L-MC     0.36
Name: CurrAlloc%, dtype: float64

In [28]:
# sector-wise stats
df_tmp = df_portfolio_features.groupby('Category')[['CurrAlloc%', 'Current', 'Current P/L', 'FTT Amt']].sum().sort_values(by=['Current', 'Current P/L'], ascending=False)
df_tmp['Current P/L%'] = round(df_tmp['Current P/L'] * 100 / df_tmp['Current'], 2)
df_tmp['FTT%'] = round(df_tmp['FTT Amt'] * 100 / df_tmp['Current'], 2)
cols = ['CurrAlloc%', 'Current P/L%', 'FTT%']
df_tmp[cols].sort_values(by=['CurrAlloc%'], ascending=False)

               CurrAlloc%  Current P/L%    FTT%
Category
FMCG                15.07        -26.57   71.50
FINANCE             13.19        -24.49   75.23
IT                  11.58        -48.70  124.37
MISC                 6.98        -46.77  110.52
ELECTRICAL           6.63        -11.80   54.61
PAINTS               5.06        -48.99   74.86
INSURANCE            4.73         -9.44   46.89
BANKS                4.68        -25.64   89.42
PHARMA               4.15         -8.26   42.34
AUTO                 3.66        -36.50   90.66
AC                   2.09        -16.63   48.25
HEALTHCARE           1.90        -43.42   80.84
DURABLES             1.83        -60.67   99.76
TRAVEL               1.82        -87.51  181.39
FOOTWEAR             1.79        -87.93  163.29
BREWERIES            1.69         -5.62   27.55
APPARELS             1.67        -22.79   64.67
REALTY               1.46        -15.99   35.04
CERAMICS             1.40        -68.24  119.36
REFINERIES           1.36        -12.50   40.96
CEMENT               1.24        -65.16  188.71
CABLES               1.21          7.09   93.17
CHEMICALS            1.09        -84.41  234.86
ENGINEERING          1.08        -70.86  149.01
JEWELLERY            1.07       -127.45  206.46
ENTERTAINMENT        0.77        -92.54  207.37
TEXTILES             0.45        -57.73  102.70
HOTELS               0.35       -148.17  235.71

In [29]:
# money to be made criteria-wise
df_portfolio_features.groupby('Criteria')['FTT Amt'].agg(['sum', 'count']).sort_values(by='sum', ascending=False)

                sum  count
Criteria
XY24      4066163.0     21
X40       1844019.0     16
XR        1402340.0     12
AR        1374062.0     10
X40N      1312599.0     10
OX40N      899674.0     10
XY25       479601.0      5
SR         315813.0      2

In [30]:
# money to be made conviction-wise
df_portfolio_features.groupby('Conviction')['FTT Amt'].agg(['sum', 'count']).sort_values(by='sum', ascending=False)

                  sum  count
Conviction
H-SC        3961981.0     24
X-MC        1761790.0     15
X-LC        1750484.0     13
M-SC        1589986.0     14
X-SC        1583634.0     10
H-MC         415441.0      3
L-SC         218950.0      2
M-LC         160958.0      1
M-MC         115352.0      2
H-LC          79623.0      1
L-MC          56072.0      1

In [31]:
# money to be made criteria and conviction-wise
df_portfolio_features.groupby(['Conviction', 'Criteria'])['FTT Amt'].agg(['sum', 'count']).sort_values(by='sum', ascending=False)

                           sum  count
Conviction Criteria
H-SC       XY24      1377176.0      6
           AR         989365.0      5
X-LC       X40        945977.0      7
M-SC       XY24       925113.0      6
H-SC       XR         883231.0      7
X-SC       XY24       863719.0      4
X-MC       X40        688028.0      7
           X40N       537375.0      4
X-SC       X40N       509901.0      4
H-SC       OX40N      396396.0      4
M-SC       OX40N      392175.0      5
X-LC       XY24       381550.0      2
H-SC       SR         315813.0      2
X-MC       XY24       276344.0      2
X-LC       X40N       265323.0      2
X-MC       XY25       260043.0      2
H-MC       XY24       242261.0      1
X-SC       X40        210014.0      2
M-SC       XR         194232.0      2
H-MC       AR         173180.0      2
M-LC       XR         160958.0      1
X-LC       XY25       157634.0      2
L-SC       OX40N      111103.0      1
           XR         107847.0      1
H-LC       AR          79623.0      1
M-SC       AR          78466.0      1
M-MC       XY25        61924.0      1
L-MC       XR          56072.0      1
M-MC       AR          53428.0      1

In [32]:
# notebook execution time

end_time = time.time()
execution_time = round(end_time - start_time, 0)
print(f"Notebook execution time: {execution_time} seconds")

Notebook execution time: 50.0 seconds