<a href="https://colab.research.google.com/github/ankit-rathi/Quantvesting_v2/blob/main/myStocks_Portfolio_Analysis.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
'''
!pip install pandas==2.2.2 -qq
!pip install pyxirr -qq
!pip install ta -qq
!pip install yfinance==0.2.59 -qq
'''

'\n!pip install pandas==2.2.2 -qq\n!pip install pyxirr -qq\n!pip install ta -qq\n!pip install yfinance==0.2.59 -qq\n'

In [2]:
# import libraries

import numpy as np
import pandas as pd
import datetime
import warnings
warnings.filterwarnings('ignore')
import yfinance as yfin
import ta
import matplotlib.pyplot as plt
import requests

In [3]:
# notebook start time
import time
import datetime
import pytz

start_time = time.time()

# function to print date timestamp
def print_date_time():
  tz_NY = pytz.timezone('Asia/Kolkata')
  datetime_NY = datetime.datetime.now(tz_NY)
  print("Run date time (IST):", datetime_NY.strftime("%Y-%m-%d %H:%M:%S"))

In [4]:
# function to get booked and reserved amount
def get_amt():
  # fetch the JSON data from the URL
  url = "https://raw.githubusercontent.com/ankit-rathi/Tradevesting_v1/main/data/myPortfolioAmts.json"
  response = requests.get(url)
  pf_amts = response.json()  # parse the JSON data

  # extract values from the JSON
  py_booked_amt_dm = pf_amts["py_booked_amt_dm"]
  py_booked_amt_sv = pf_amts["py_booked_amt_sv"]
  cy_booked_amt_dm = pf_amts["cy_booked_amt_dm"]
  cy_booked_amt_sv = pf_amts["cy_booked_amt_sv"]
  reserve_amt_dm = pf_amts["reserve_amt_dm"]
  reserve_amt_sv = pf_amts["reserve_amt_sv"]

  # perform calculations
  py_booked_amt = py_booked_amt_dm + py_booked_amt_sv
  cy_booked_amt = cy_booked_amt_dm + cy_booked_amt_sv
  reserve_amt = reserve_amt_dm + reserve_amt_sv
  total_booked_amt = py_booked_amt + cy_booked_amt

  return total_booked_amt, reserve_amt, cy_booked_amt, py_booked_amt

gen_output = 0

In [5]:
# function to format the amount
def format_amt(number):
    abs_number = abs(number)

    if abs_number >= 1_00_00_000:  # Crores
        formatted_amt = f"{number / 1_00_00_000:.2f} C"
    elif abs_number >= 1_00_000:  # Lakhs
        formatted_amt = f"{number / 1_00_000:.2f} L"
    elif abs_number >= 1_000:  # Thousands
        formatted_amt = f"{number / 1_000:.2f} K"
    else:
        formatted_amt = f"{number:.2f}"

    return formatted_amt

# function to set start and end date
def get_start_end_date():
  start_date = (datetime.date.today() + datetime.timedelta(days=-365)).strftime('%Y-%m-%d')
  end_date = (datetime.date.today() + datetime.timedelta(days=1)).strftime('%Y-%m-%d')
  return start_date, end_date

# function to fetch my portfolio csv
def get_mypfs_df():
  mypfs_df = pd.read_csv('https://raw.githubusercontent.com/ankit-rathi/Tradevesting_v1/main/data/myPortfolioStocks.csv')
  return mypfs_df

# function to fetch my prospects csv
def get_mypps_df():
  mypps_df = pd.read_csv('https://raw.githubusercontent.com/ankit-rathi/Tradevesting_v1/main/data/myProspectsScrips.csv')
  return mypps_df

# function to fetch screener data
def get_myscreen_df():
  myscreen_df = pd.read_csv('https://raw.githubusercontent.com/ankit-rathi/Tradevesting_v1/main/data/myScreenerDB.csv')
  return myscreen_df

# function to fetch momentum data
def get_myinvmt_df():
  myinvmt_df = pd.read_csv('https://raw.githubusercontent.com/ankit-rathi/Tradevesting_v1/main/data/myInvestments.csv')
  return myinvmt_df

# function to get the stock ids
def get_stock_ids(df_pf):
  stock_n100 = df_pf['Symbol'].unique()

  exclude = ['CADILAHC','MMTC', 'MASFIN']

  stock_ids = df_pf[~df_pf['Symbol'].isin(exclude) ]['Symbol'].unique()

  #mypf = mypf[mypf.Forecast.notnull()]
  #stock_ids = mypf['Symbol'].unique()

  #stock_ids.sort()
  return stock_ids

# get features from screener data
def get_screener_features():
  myscreen_df = get_myscreen_df()
  cols = ['Symbol', 'EPS', 'MedPE', 'ROCE%', 'ROE%', 'CapType']
  return myscreen_df[cols]

# get relative strength
def get_relative_strength(stock_list):

    # Dictionary to store stock tickers and their corresponding percentage price change
    stock_changes = {}

    # Loop through each stock and fetch its price data
    for stock in stock_list:
        try:
            # Download the stock data for the given date range
            stock_data = yfin.Ticker(stock + '.NS').history(period='1mo', interval='1d')[map(str.title, ['open', 'close', 'low', 'high', 'volume'])]

            # Calculate the percentage change for the stock
            if len(stock_data) > 0:
                start_price = stock_data['Close'].iloc[0]
                end_price = stock_data['Close'].iloc[-1]
                percent_change = round(((end_price - start_price) / start_price) * 100, 2)
                stock_changes[stock] = percent_change
            else:
                stock_changes[stock] = np.nan  # If no data is available, set to NaN

        except Exception as e:
            print(f"Error fetching data for {stock}: {e}")
            stock_changes[stock] = np.nan

    # Create a DataFrame with stock tickers and their percentage changes
    df = pd.DataFrame(list(stock_changes.items()), columns=['Symbol', 'Percent_Change'])

    # Drop any stocks with missing data (NaN values)
    df = df.dropna()

    # Calculate the percentile rank based on percentage change
    df['RSP'] = round(df['Percent_Change'].rank(pct=True) * 100, 2)
    cols = ['Symbol', 'RSP']
    df = df[cols]
    # Sort by percentile rank (optional)
    df = df.sort_values(by='RSP', ascending=False).reset_index(drop=True)

    return df

In [6]:
# function to get stock technicals
def stock_prec_dev(stock_symbol):
    #stock_symbol = 'ULTRACEMCO.NS'
    short_window = 20
    mid_window = 50
    long_window = 200
    moving_avg = 'SMA'

    start = datetime.datetime(*map(int, start_date.split('-')))
    end = datetime.datetime(*map(int, end_date.split('-')))

    stock_df = yfin.Ticker(stock_symbol + '.NS').history(period='max', interval='1d')[map(str.title, ['open', 'close', 'low', 'high', 'volume'])]

    stock_df['Max'] = round(max(stock_df['Close']),2)
    stock_df = stock_df[(stock_df.index <= end_date) & (stock_df.index >= start_date)]
    stock_df['200_SMA'] = round(stock_df['Close'].rolling(window = 200, min_periods = 1).mean(),0)
    stock_df['Dev%_200'] = round((stock_df['Close'] - stock_df['200_SMA'])*100/stock_df['200_SMA'],2)
    stock_df.dropna(axis = 0, inplace = True) # remove any null rows

    stock_df['20_SMA'] = stock_df['Close'].rolling(window=20).mean()
    stock_df['50_SMA'] = stock_df['Close'].rolling(window=50).mean()
    stock_df['Symbol'] = stock_symbol

    stock_df['Close'] = round(stock_df['Close'],2)
    stock_df['Min'] = round(min(stock_df['Close']),2)
    stock_df['RSI_14'] = ta.momentum.RSIIndicator(close=stock_df['Close'], window=14).rsi()
    stock_df['RSI_14'] = round(stock_df['RSI_14'],0)
    stock_df['Prev_Close'] = stock_df['Close'].shift(1)
    stock_df.drop(['Open', 'Low', 'High', 'Volume'], axis=1, inplace=True)
    stock_df = stock_df.tail(1)

    max_SMA = max(stock_df['20_SMA'].item(), stock_df['50_SMA'].item(), stock_df['200_SMA'].item())
    min_SMA = min(stock_df['20_SMA'].item(), stock_df['50_SMA'].item(), stock_df['200_SMA'].item())
    ABS_Spread = max_SMA - min_SMA
    stock_df['Spread%'] = round((ABS_Spread / stock_df['200_SMA'].item()) * 100,2)

    return stock_df

# function to compute stock attributes
def get_common_features(stock_ids, df_mypf):

  df_prec_dev = pd.DataFrame()
  df_tmp = get_screener_features()
  df_rs = get_relative_strength(stock_ids)

  for stock_id in stock_ids:
      tmp = stock_prec_dev(stock_id)
      tmp = tmp.reset_index()
      df_prec_dev = pd.concat([df_prec_dev, tmp], ignore_index = True)
  df_prec_dev = pd.merge(df_prec_dev, df_mypf, on= 'Symbol')
  df_prec_dev = pd.merge(df_prec_dev, df_tmp, on= 'Symbol', how='left')
  df_prec_dev = pd.merge(df_prec_dev, df_rs, on= 'Symbol', how='left')
  #print(df_prec_dev.columns)
  df_prec_dev['Curr_PE'] = round(df_prec_dev['Close']/df_prec_dev['EPS'],1)
  df_prec_dev['Dev%_PE'] = round((df_prec_dev['Curr_PE'] - df_prec_dev['MedPE'])*100/df_prec_dev['MedPE'],2)
  df_prec_dev['Conviction'] = df_prec_dev['Conviction'] + '-' + df_prec_dev['CapType']
  return df_prec_dev

# function to arrange stock features
def arrange_features(df_stocks, common_cols, diff_cols):
  df_stocks_common = df_stocks[common_cols].drop_duplicates()
  df_stocks_diff = df_stocks[diff_cols]
  df_stocks_diff['Investment'] = df_stocks_diff['AvgCost'] * df_stocks_diff['Shares']
  df_stocks_diff = df_stocks_diff.groupby(['Symbol'])[['Shares', 'Investment']].aggregate(['sum']).reset_index()
  df_stocks_diff.columns = ['Symbol', 'Shares', 'Investment']
  df_stocks_diff['AvgCost'] = round(df_stocks_diff['Investment']/df_stocks_diff['Shares'],2)
  df_stocks = pd.merge(df_stocks_diff, df_stocks_common, on='Symbol')
  return df_stocks

# plot fact distribution across dimension
def plot_pie_chart(df, dimension, fact):
  # grouping the data by category and calculating the sum of fact for each type
  grouped_data = df.groupby(dimension)[fact].sum()

  # sorting the grouped data in descending order
  grouped_data = grouped_data.sort_values(ascending=False)

  # creating a pie chart
  grouped_data.plot.pie(autopct='%1.1f%%', startangle=90, figsize=(6, 6))

  # adding a title and displaying the plot
  plt.title(f'{dimension} {fact} Distribution')
  plt.ylabel('')  # To hide the y-label
  plt.show()

In [7]:
# function to get portfolio features

def get_portfolio_features(df_common_features):

  print_date_time()
  print('-------------------')

  #df_common_features["Target"] = df_common_features["Target"].fillna(df_common_features["Max"])
  df_common_features['NTT'] = np.where(df_common_features['Strategy']== 'NTT', df_common_features["Target"], df_common_features['Max'])
  df_common_features['LTT'] = np.where(df_common_features['Strategy']== 'BTT', df_common_features["Target"], df_common_features['Max'])
  df_common_features['BOL'] = df_common_features['Min']

  tmp_df = df_common_features[df_common_features['Symbol'].isin(mypf_df[mypf_df['InPortfolio'] != 'NA'].Symbol.values)]
  print('qualified stocks: '+str(len(tmp_df['Symbol'].unique())))
  tmp_df1 = tmp_df[tmp_df['LatestQtr'] == 1]
  print('with latest results: '+str(len(tmp_df1['Symbol'].unique())))
  tmp_df1 = tmp_df1[tmp_df1['StarStock'] == 1]
  print('still star stocks: '+str(len(tmp_df1['Symbol'].unique())))
  tmp_df['Investment'] = tmp_df['AvgCost'] * tmp_df['Shares']
  tmp_df['Current'] = round(tmp_df['Close'] * tmp_df['Shares'],0)
  tmp_df['Previous'] = tmp_df['Prev_Close'] * tmp_df['Shares']
  tmp_df['EstimatedST'] = tmp_df['NTT'] * tmp_df['Shares']
  tmp_df['EstimatedLT'] = tmp_df['LTT'] * tmp_df['Shares']
  tmp_df['Current P/L'] = round((tmp_df['Current'] - tmp_df['Investment']),0)
  tmp_df['Today P/L%'] = round((tmp_df['Current'] - tmp_df['Previous'])*100/tmp_df['Previous'],2)
  tmp_df['Current P/L%'] = round((tmp_df['Current'] - tmp_df['Investment'])*100/tmp_df['Investment'],2)
  tmp_df['EstimatedST P/L%'] = round((tmp_df['EstimatedST'] - tmp_df['Investment'])*100/tmp_df['Investment'],2)
  tmp_df['EstimatedLT P/L%'] = round((tmp_df['EstimatedLT'] - tmp_df['Investment'])*100/tmp_df['Investment'],2)
  tmp_df['NTT%'] = round((tmp_df['NTT'] - tmp_df['Close'])*100/tmp_df['Close'],2)
  tmp_df['LTT%'] = round((tmp_df['LTT'] - tmp_df['Close'])*100/tmp_df['Close'],2)
  tmp_df['Gained%'] = round((tmp_df['Close'] - tmp_df['BOL'])*100/tmp_df['BOL'],2)
  investment = round(sum(tmp_df['AvgCost']*tmp_df['Shares']),0)
  current = round(sum(tmp_df['Close']*tmp_df['Shares']),0)
  tmp_df['InitAlloc%'] = round(tmp_df['Investment']*100/investment,2)
  tmp_df['CurrAlloc%'] = round(tmp_df['Current']*100/current,2)
  tmp_df['FTT'] = tmp_df['LTT']
  tmp_df.loc[tmp_df['Strategy'] == 'NTT', 'FTT'] = tmp_df['NTT']
  tmp_df['FTT%'] = tmp_df['LTT%']
  tmp_df.loc[tmp_df['Strategy'] == 'NTT', 'FTT%'] = tmp_df['NTT%']
  tmp_df['FTT Amt'] = round(tmp_df['FTT%'] * tmp_df['Current']/100,0)
  tmp_df['OTT%'] = round((tmp_df['FTT'] - tmp_df['AvgCost'])*100/tmp_df['AvgCost'],2)
  tmp_df['RRR Ind'] = round(tmp_df['Current P/L']/tmp_df['FTT Amt'],2)
  tmp_df['Risk Ind'] = round(tmp_df['Current P/L%']*tmp_df['CurrAlloc%'],0)

  return tmp_df

# function to print portfolio features
def print_portfolio_stats(df_portfolio_features, myinvmt_df):
  from pyxirr import xirr

  total_booked_amt, reserve_amt, cy_booked_amt, py_booked_amt = get_amt()

  dates = myinvmt_df['Date'].values
  dates = np.append(dates, datetime.date.today().strftime('%d-%b-%y'))
  investment = myinvmt_df['Investment'].values
  dates= pd.to_datetime(dates)

  current = round(sum(df_portfolio_features['Close']*df_portfolio_features['Shares']),0) + reserve_amt
  investment_xirr = np.append(investment, current)
  cagr = round(xirr(pd.DataFrame({"dates": dates, "amounts": investment_xirr}))*100,2)

  investment = -sum(investment)
  invested = round(sum(df_portfolio_features['AvgCost']*df_portfolio_features['Shares']),0) + reserve_amt
  previous = round(sum(df_portfolio_features['Prev_Close']*df_portfolio_features['Shares']),0) + reserve_amt
  cy_invested = investment + py_booked_amt

  today_pnl_amount = current-previous
  today_pnl_percentage = round((current-previous)*100/previous,2)

  curr_pnl_amount = current-invested
  curr_pnl_percentage = round((curr_pnl_amount)*100/(cy_invested),2)

  cy_pnl_amount = cy_booked_amt + curr_pnl_amount
  cy_pnl_percentage = round((cy_pnl_amount)*100/cy_invested,2)

  overall_pnl_amount = total_booked_amt + curr_pnl_amount
  overall_pnl_percentage = round((overall_pnl_amount)*100/investment,2)

  estimate_st = round(sum(df_portfolio_features['FTT']*df_portfolio_features['Shares']),0)  + reserve_amt
  est_st_pnl_amount = estimate_st-current
  est_st_pnl_percentage = round((est_st_pnl_amount)*100/current,2)

  estimate_lt = round(sum(df_portfolio_features['LTT']*df_portfolio_features['Shares']),0)  + reserve_amt
  est_lt_pnl_amount = estimate_lt-current
  est_lt_pnl_percentage = round((est_lt_pnl_amount)*100/current,2)

  total_profit = round(sum(df_portfolio_features[df_portfolio_features['Current P/L%'] > 0]['Current']) - sum(df_portfolio_features[df_portfolio_features['Current P/L%'] > 0]['Investment']),0)
  total_loss = round(sum(df_portfolio_features[df_portfolio_features['Current P/L%'] < 0]['Current']) - sum(df_portfolio_features[df_portfolio_features['Current P/L%'] < 0]['Investment']),0)

  cy_booked_percentage = round((cy_booked_amt)*100/current,2)
  py_booked_percentage = round((py_booked_amt)*100/investment,2)
  total_booked_percentage = round((total_booked_amt)*100/investment,2)

  print('-------------------')
  print('Initial Investment: ', format_amt(investment))
  print('CY Investment: ', format_amt(cy_invested))
  print('Reserve: ', format_amt(reserve_amt))
  print('Current: ',  format_amt(current))
  print('-------------------')
  print('Today PnL: '+ '{} ({}%)'.format(format_amt(today_pnl_amount), today_pnl_percentage))
  print('Current PnL: '+ '{} ({}%)'.format(format_amt(curr_pnl_amount), curr_pnl_percentage))
  print('CY Booked + Current PnL: '+ '{} ({}%)'.format(format_amt(cy_pnl_amount), cy_pnl_percentage))
  print('-------------------')
  print('Total profit: ', format_amt(total_profit))
  print('Total loss: ', format_amt(total_loss))
  print('-------------------')
  print('Total Booked + Current PnL: '+ '{} ({}%)'.format(format_amt(overall_pnl_amount), overall_pnl_percentage))
  print('Total Booked PnL: '+ '{} ({}%)'.format(format_amt(total_booked_amt), total_booked_percentage))
  print('Curr Year Booked PnL: '+ '{} ({}%)'.format(format_amt(cy_booked_amt), cy_booked_percentage))
  print('Prev Year Booked PnL: '+ '{} ({}%)'.format(format_amt(py_booked_amt), py_booked_percentage))
  print('===================')
  print('Est FTT: ',  format_amt(estimate_st))
  print('Est FTT PnL: '+ '{} ({}%)'.format(format_amt(est_st_pnl_amount), est_st_pnl_percentage))

  print('===================')
  print('Deployed: ', format_amt(investment))

  print('Current: ', format_amt(current))

  print('CAGR/XIRR %: '+'{}%'.format(cagr))

In [8]:
# get start and end date
start_date, end_date = get_start_end_date()

# get portfolio and prospects data
mypfs_df = get_mypfs_df()
mypps_df = get_mypps_df()
myinvmt_df = get_myinvmt_df()

# merge above datasets
mypf_df = pd.merge(mypfs_df, mypps_df, on="Symbol")

# seggregate dm and sv portfolio
dm_pf = mypf_df[mypf_df['InPortfolio'] == 'DM']
sv_pf = mypf_df[mypf_df['InPortfolio'] == 'SV']

# build portfolio stock dataframe
dm_stocks = get_stock_ids(dm_pf)
sv_stocks = get_stock_ids(sv_pf)
df_stocks = pd.concat([dm_pf,sv_pf], ignore_index = True)

# arrange common and diff stock features
common_cols = ['Symbol', 'Target', 'Criteria', 'Strategy', 'CumlRnk', 'LatestQtr', 'StarStock', 'Conviction', 'Category', 'InFolio', 'XIRR', 'MBQ']
diff_cols = ['Symbol', 'AvgCost', 'Shares']
df_stocks = arrange_features(df_stocks, common_cols, diff_cols)

# get common features
stock_ids = df_stocks['Symbol'].values
df_common_features = get_common_features(stock_ids, df_stocks)

df_common_features.reset_index(drop=True, inplace=True)
df_common_features.drop(['Date'], axis=1, inplace=True)
# get and print portfolio features
df_portfolio_features = get_portfolio_features(df_common_features)

print_portfolio_stats(df_portfolio_features, myinvmt_df)

df = df_portfolio_features
#plot_pie_chart(df, 'CapType', 'Current')
list_ox40n = list(df[df['MBQ'].str.contains('OX40N', na=False)]['Symbol'].values)

Run date time (IST): 2026-05-05 14:59:20
-------------------
qualified stocks: 92
with latest results: 31
still star stocks: 20

-------------------
Initial Investment:  1.40 C
CY Investment:  1.82 C
Reserve:  1.49 K
Current:  1.49 C
-------------------
Today PnL: 24.91 K (0.17%)
Current PnL: -33.97 L (-18.63%)
CY Booked + Current PnL: -31.89 L (-17.49%)
-------------------
Total profit:  1.36 L
Total loss:  -35.33 L
-------------------
Total Booked + Current PnL: 10.98 L (7.87%)
Total Booked PnL: 44.95 L (32.22%)
Curr Year Booked PnL: 2.08 L (1.39%)
Prev Year Booked PnL: 42.87 L (30.73%)
===================
Est FTT:  2.55 C
Est FTT PnL: 1.06 C (71.2%)
===================
Deployed:  1.40 C
Current:  1.49 C
CAGR/XIRR %: 3.33%

In [9]:
# top 5 near their targets
cols = ['Symbol', 'Today P/L%', 'Current P/L%', 'FTT%', 'OTT%', 'FTT Amt', 'Current P/L', 'Current', 'FTT', 'Dev%_PE', 'RSI_14','Conviction', 'Spread%',  'CumlRnk', 'RRR Ind', 'CurrAlloc%', 'Gained%', 'Criteria', 'Strategy', 'Category']
df_tmp = df_portfolio_features[~df_portfolio_features['Symbol'].isin(['ENRIN','BLUSPRING','DIGITIDE'])]
df_tmp = df_tmp.sort_values(by = 'FTT Amt', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
55,MASFIN,-0.56,5.63,15.08,21.57,15608.0,5520.0,103500.0,397.04,-8.76,70.0,H-SC,2.50,167.0,0.35,0.69,33.75,XR,ATH,FINANCE
53,M&M,2.90,3.72,18.96,23.38,27272.0,5161.0,143842.0,3802.40,-12.00,53.0,X-LC,8.20,25.0,0.19,0.96,9.05,X40N,ATH,AUTO
51,KOTAKBANK,0.12,-0.57,21.81,21.11,30027.0,-796.0,137677.0,453.24,-14.61,45.0,X-LC,7.91,12.0,-0.03,0.92,5.29,X40,ATH,BANKS
59,PIDILITIND,-0.37,-3.65,22.85,18.37,31067.0,-5150.0,135960.0,1670.26,-32.57,46.0,X-LC,6.34,5.0,-0.17,0.91,6.75,X40,ATH,CHEMICALS
83,TTKPRESTIG,-0.69,-30.76,44.56,0.09,31093.0,-31000.0,69777.0,770.00,62.01,62.0,M-SC,17.19,250.0,-1.00,0.47,24.25,OX40N,NTT,DURABLES

In [10]:
# top 5 today
df_tmp = df_portfolio_features.sort_values(by = 'Today P/L%', ascending=False)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
80,TITAGARH,9.51,-20.67,83.72,45.74,160837.0,-50064.0,192113.0,1548.00,5.62,73.0,H-SC,14.50,175.0,-0.31,1.29,46.58,XY24,NTT,ENGINEERING
15,CAMS,8.69,4.08,19.59,24.48,51352.0,10280.0,262136.0,950.00,-0.16,70.0,X-SC,6.36,89.0,0.20,1.76,27.62,X40N,NTT,MISC
60,QUESS,6.71,-7.37,87.74,73.90,86791.0,-7875.0,98918.0,424.00,-50.41,74.0,X-SC,14.50,80.0,-0.09,0.66,33.07,XY24,NTT,MISC
86,VALIANTORG,3.55,-42.74,204.12,74.15,191234.0,-69918.0,93687.0,838.00,-268.43,57.0,H-SC,16.63,145.0,-0.37,0.63,39.42,XR,NTT,CHEMICALS
25,FINCABLES,3.32,32.99,56.34,107.91,110624.0,48706.0,196350.0,1641.55,19.74,76.0,M-SC,13.05,220.0,0.44,1.32,47.72,OX40N,ATH,CABLES

In [11]:
# bottom 5 today
df_tmp = df_portfolio_features.sort_values(by = 'Today P/L%', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
88,VOLTAS,-4.25,8.93,33.30,45.20,69550.0,17118.0,208860.0,1856.00,24.66,47.0,X-MC,1.94,79.0,0.25,1.40,14.48,XY25,NTT,AC
76,SYMPHONY,-2.89,-38.71,63.10,-0.03,66191.0,-66243.0,104898.0,1306.00,-50.83,50.0,M-SC,11.82,205.0,-1.00,0.70,16.34,OX40N,NTT,DURABLES
3,ALKYLAMINE,-2.61,-34.47,195.47,93.63,129331.0,-34799.0,66164.0,4546.37,-29.89,59.0,H-SC,18.98,142.0,-0.27,0.44,24.94,SR,ATH,CHEMICALS
5,ATULAUTO,-2.40,-16.40,74.13,45.57,122165.0,-32334.0,164798.0,844.00,3570.27,58.0,M-SC,3.13,248.0,-0.26,1.10,26.82,XY24,NTT,AUTO
89,WHIRLPOOL,-2.04,-21.89,132.92,81.92,119180.0,-25135.0,89663.0,2270.00,-54.27,65.0,M-SC,18.28,210.0,-0.21,0.60,25.95,XR,NTT,DURABLES

In [12]:
# top 5 to exit based on CumlRnk
df_tmp = df_portfolio_features[~df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])]
df_tmp = df_tmp[(df_tmp['Current P/L%'] > -1) & (df_tmp['Current P/L%'] < 1)].sort_values(by = 'CumlRnk', ascending=False)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
73,SONACOMS,0.52,0.07,39.00,39.09,39479.0,70.0,101229.0,804.02,-20.74,55.0,M-MC,18.53,193.0,0.00,0.68,43.20,AR,ATH,AUTO
9,BANDHANBNK,-0.17,-0.71,93.79,92.42,259413.0,-1970.0,276589.0,400.00,137.07,76.0,H-SC,10.65,174.0,-0.01,1.85,52.37,XY24,NTT,BANKS
74,STARHEALTH,-0.38,0.23,46.93,47.26,132232.0,642.0,281765.0,761.00,58.09,64.0,H-SC,7.34,173.0,0.00,1.89,45.92,XY24,NTT,INSURANCE

In [13]:
# OX40N stocks to exit
df_tmp = df_portfolio_features[(df_portfolio_features['Symbol'].isin(list_ox40n))].sort_values(by = 'Current P/L%', ascending=False)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
25,FINCABLES,3.32,32.99,56.34,107.91,110624.0,48706.0,196350.0,1641.55,19.74,76.0,M-SC,13.05,220.0,0.44,1.32,47.72,OX40N,ATH,CABLES
72,SIS,-0.12,-8.13,32.00,21.26,32640.0,-9032.0,102000.0,528.00,2427.46,80.0,H-SC,7.54,168.0,-0.28,0.68,51.66,OX40N,NTT,MISC
16,CERA,1.46,-29.68,76.18,23.89,94230.0,-52209.0,123694.0,9475.00,-32.22,61.0,H-SC,11.94,153.0,-0.55,0.83,18.87,OX40N,NTT,CERAMICS
83,TTKPRESTIG,-0.69,-30.76,44.56,0.09,31093.0,-31000.0,69777.0,770.00,62.01,62.0,M-SC,17.19,250.0,-1.00,0.47,24.25,OX40N,NTT,DURABLES
50,KANSAINER,-1.74,-35.50,75.93,13.47,132068.0,-95733.0,173934.0,340.00,-44.56,49.0,H-SC,16.25,162.0,-0.72,1.17,21.49,XY24,NTT,PAINTS

In [14]:
# top 5 to book for rotation
df_tmp = df_portfolio_features[(df_portfolio_features['Current P/L%'] > 20) ].sort_values(by = 'CumlRnk', ascending=False)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
25,FINCABLES,3.32,32.99,56.34,107.91,110624.0,48706.0,196350.0,1641.55,19.74,76.0,M-SC,13.05,220.0,0.44,1.32,47.72,OX40N,ATH,CABLES

In [15]:
# top 5 to monitor for exit
df_tmp = df_portfolio_features[~df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])]
df_tmp = df_tmp[(df_tmp['Current P/L%'] > 0) ].sort_values(by = 'Dev%_PE', ascending=False)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
74,STARHEALTH,-0.38,0.23,46.93,47.26,132232.0,642.0,281765.0,761.00,58.09,64.0,H-SC,7.34,173.0,0.00,1.89,45.92,XY24,NTT,INSURANCE
25,FINCABLES,3.32,32.99,56.34,107.91,110624.0,48706.0,196350.0,1641.55,19.74,76.0,M-SC,13.05,220.0,0.44,1.32,47.72,OX40N,ATH,CABLES
68,SATIN,-1.36,3.06,47.33,51.83,134765.0,8451.0,284735.0,274.00,-8.02,69.0,H-SC,11.84,159.0,0.06,1.91,38.71,XY24,NTT,FINANCE
55,MASFIN,-0.56,5.63,15.08,21.57,15608.0,5520.0,103500.0,397.04,-8.76,70.0,H-SC,2.50,167.0,0.35,0.69,33.75,XR,ATH,FINANCE
73,SONACOMS,0.52,0.07,39.00,39.09,39479.0,70.0,101229.0,804.02,-20.74,55.0,M-MC,18.53,193.0,0.00,0.68,43.20,AR,ATH,AUTO

In [16]:
# top 5 to book for rotation from weak conviction
df_tmp = df_portfolio_features[~df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])]
df_tmp = df_tmp[~df_tmp['Criteria'].isin(['XY25','XY24','X40', 'X40N'])].sort_values(by = 'RRR Ind', ascending=False)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
25,FINCABLES,3.32,32.99,56.34,107.91,110624.0,48706.0,196350.0,1641.55,19.74,76.0,M-SC,13.05,220.0,0.44,1.32,47.72,OX40N,ATH,CABLES
55,MASFIN,-0.56,5.63,15.08,21.57,15608.0,5520.0,103500.0,397.04,-8.76,70.0,H-SC,2.50,167.0,0.35,0.69,33.75,XR,ATH,FINANCE
73,SONACOMS,0.52,0.07,39.00,39.09,39479.0,70.0,101229.0,804.02,-20.74,55.0,M-MC,18.53,193.0,0.00,0.68,43.20,AR,ATH,AUTO
42,INDIAMART,-2.00,-11.79,134.36,106.72,146174.0,-14543.0,108793.0,4810.62,-60.16,40.0,H-SC,9.32,140.0,-0.10,0.73,4.52,AR,ATH,MISC
91,ZYDUSLIFE,0.85,-4.04,41.34,35.63,83139.0,-8464.0,201110.0,1286.17,-16.67,49.0,H-MC,3.85,120.0,-0.10,1.35,5.74,AR,ATH,PHARMA

In [17]:
# top 5 to accumulate based on lowest RSI_14
df_tmp = df_portfolio_features[df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])].sort_values(by = 'RSI_14', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
33,HCLTECH,0.01,-22.09,55.95,21.51,105462.0,-53430.0,188494.0,1872.35,-18.11,30.0,X-LC,10.19,8.0,-0.51,1.26,0.38,X40,ATH,IT
45,INFY,0.49,-20.07,67.96,34.24,169956.0,-62805.0,250083.0,1972.00,-37.23,36.0,X-LC,14.45,3.0,-0.37,1.68,1.91,X40,NTT,IT
1,ABBOTINDIA,-0.26,-14.96,38.84,18.07,59076.0,-26755.0,152100.0,35195.00,-27.72,41.0,X-MC,12.02,58.0,-0.45,1.02,0.68,X40,ATH,PHARMA
79,TCS,-0.42,-28.93,78.09,26.57,257116.0,-134017.0,329256.0,4311.58,-39.69,41.0,X-LC,13.90,2.0,-0.52,2.21,2.76,X40,ATH,IT
34,HDFCBANK,-0.78,-7.49,38.76,28.37,84224.0,-17588.0,217297.0,1073.00,-21.52,42.0,X-LC,15.49,26.0,-0.21,1.46,5.71,X40,BTT,BANKS

In [18]:
# top 5 to accumulate based on Spread and CumlRnk
df_tmp = df_portfolio_features[df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])]
df_tmp = df_tmp[(df_tmp['CumlRnk'] < 100)].sort_values(by = 'Spread%', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
88,VOLTAS,-4.25,8.93,33.30,45.20,69550.0,17118.0,208860.0,1856.00,24.66,47.0,X-MC,1.94,79.0,0.25,1.40,14.48,XY25,NTT,AC
84,UNITDSPR,-0.70,-3.58,25.26,20.77,57024.0,-8394.0,225750.0,1644.00,-14.48,48.0,X-MC,3.07,64.0,-0.15,1.51,7.69,X40N,NTT,BREWERIES
65,RELIANCE,-0.19,-6.26,33.67,25.30,63427.0,-12584.0,188379.0,1952.00,-8.88,66.0,X-LC,4.41,21.0,-0.20,1.26,11.93,XY25,BTT,REFINERIES
81,TMPV,-0.71,-22.47,76.16,36.58,210115.0,-79955.0,275886.0,600.00,-83.62,48.0,X-LC,4.78,4.0,-0.38,1.85,14.99,XY24,NTT,AUTO
19,COLPAL,-0.11,-17.59,71.70,41.51,155625.0,-46315.0,217050.0,3726.84,-0.25,64.0,X-MC,5.21,62.0,-0.30,1.45,21.35,XY25,ATH,FMCG

In [19]:
# top 5 to accumulate based on lowest Gained%
df_tmp = df_portfolio_features[df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])].sort_values(by = 'Gained%', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
33,HCLTECH,0.01,-22.09,55.95,21.51,105462.0,-53430.0,188494.0,1872.35,-18.11,30.0,X-LC,10.19,8.0,-0.51,1.26,0.38,X40,ATH,IT
1,ABBOTINDIA,-0.26,-14.96,38.84,18.07,59076.0,-26755.0,152100.0,35195.00,-27.72,41.0,X-MC,12.02,58.0,-0.45,1.02,0.68,X40,ATH,PHARMA
45,INFY,0.49,-20.07,67.96,34.24,169956.0,-62805.0,250083.0,1972.00,-37.23,36.0,X-LC,14.45,3.0,-0.37,1.68,1.91,X40,NTT,IT
79,TCS,-0.42,-28.93,78.09,26.57,257116.0,-134017.0,329256.0,4311.58,-39.69,41.0,X-LC,13.90,2.0,-0.52,2.21,2.76,X40,ATH,IT
35,HDFCLIFE,0.82,-2.99,37.28,33.18,54176.0,-4478.0,145322.0,814.30,-24.30,43.0,X-LC,17.00,31.0,-0.08,0.97,4.78,X40,ATH,INSURANCE

In [20]:
# top 5 to accumulate based on lowest CurrAlloc%
df_tmp = df_portfolio_features[df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])].sort_values(by = 'CurrAlloc%', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
64,RELAXO,-0.51,-61.21,292.65,52.31,164780.0,-88854.0,56306.0,1176.00,-58.67,50.0,X-SC,25.54,92.0,-0.54,0.38,25.89,X40N,NTT,FOOTWEAR
10,BATAINDIA,-0.53,-53.72,192.13,35.20,114417.0,-69118.0,59552.0,2096.00,-21.88,47.0,X-SC,26.13,91.0,-0.60,0.40,18.11,X40,NTT,FOOTWEAR
60,QUESS,6.71,-7.37,87.74,73.90,86791.0,-7875.0,98918.0,424.00,-50.41,74.0,X-SC,14.50,80.0,-0.09,0.66,33.07,XY24,NTT,MISC
59,PIDILITIND,-0.37,-3.65,22.85,18.37,31067.0,-5150.0,135960.0,1670.26,-32.57,46.0,X-LC,6.34,5.0,-0.17,0.91,6.75,X40,ATH,CHEMICALS
51,KOTAKBANK,0.12,-0.57,21.81,21.11,30027.0,-796.0,137677.0,453.24,-14.61,45.0,X-LC,7.91,12.0,-0.03,0.92,5.29,X40,ATH,BANKS

In [21]:
# top 5 to accumulate based on CumlRnk
df_tmp = df_portfolio_features.sort_values(by = 'CumlRnk', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
47,ITC,0.39,-17.74,44.73,19.06,125164.0,-60345.0,279821.0,452.00,-54.71,57.0,X-LC,15.88,1.0,-0.48,1.88,8.55,X40,NTT,FMCG
79,TCS,-0.42,-28.93,78.09,26.57,257116.0,-134017.0,329256.0,4311.58,-39.69,41.0,X-LC,13.90,2.0,-0.52,2.21,2.76,X40,ATH,IT
45,INFY,0.49,-20.07,67.96,34.24,169956.0,-62805.0,250083.0,1972.00,-37.23,36.0,X-LC,14.45,3.0,-0.37,1.68,1.91,X40,NTT,IT
81,TMPV,-0.71,-22.47,76.16,36.58,210115.0,-79955.0,275886.0,600.00,-83.62,48.0,X-LC,4.78,4.0,-0.38,1.85,14.99,XY24,NTT,AUTO
59,PIDILITIND,-0.37,-3.65,22.85,18.37,31067.0,-5150.0,135960.0,1670.26,-32.57,46.0,X-LC,6.34,5.0,-0.17,0.91,6.75,X40,ATH,CHEMICALS

In [22]:
# top 5 for average up
df_tmp = df_portfolio_features[(df_portfolio_features['Dev%_200'] > 5)].sort_values(by = 'CurrAlloc%', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
44,INDUSINDBK,-0.04,-32.56,97.04,32.89,50529.0,-25136.0,52070.0,1800.00,-345.10,62.0,L-MC,3.65,258.0,-0.50,0.35,28.17,XR,NTT,BANKS
72,SIS,-0.12,-8.13,32.00,21.26,32640.0,-9032.0,102000.0,528.00,2427.46,80.0,H-SC,7.54,168.0,-0.28,0.68,51.66,OX40N,NTT,MISC
73,SONACOMS,0.52,0.07,39.00,39.09,39479.0,70.0,101229.0,804.02,-20.74,55.0,M-MC,18.53,193.0,0.00,0.68,43.20,AR,ATH,AUTO
55,MASFIN,-0.56,5.63,15.08,21.57,15608.0,5520.0,103500.0,397.04,-8.76,70.0,H-SC,2.50,167.0,0.35,0.69,33.75,XR,ATH,FINANCE
75,SURYODAY,1.39,-9.96,36.65,23.03,59091.0,-17840.0,161231.0,216.00,75.44,73.0,H-SC,7.77,166.0,-0.30,1.08,37.50,XR,NTT,BANKS

In [23]:
# top 5 RSP
df_tmp = df_portfolio_features.sort_values(by = 'RSP', ascending=False)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
72,SIS,-0.12,-8.13,32.00,21.26,32640.0,-9032.0,102000.0,528.00,2427.46,80.0,H-SC,7.54,168.0,-0.28,0.68,51.66,OX40N,NTT,MISC
9,BANDHANBNK,-0.17,-0.71,93.79,92.42,259413.0,-1970.0,276589.0,400.00,137.07,76.0,H-SC,10.65,174.0,-0.01,1.85,52.37,XY24,NTT,BANKS
80,TITAGARH,9.51,-20.67,83.72,45.74,160837.0,-50064.0,192113.0,1548.00,5.62,73.0,H-SC,14.50,175.0,-0.31,1.29,46.58,XY24,NTT,ENGINEERING
61,RAJESHEXPO,-0.48,-76.97,334.56,0.07,105681.0,-105589.0,31588.0,518.00,1057.83,51.0,L-SC,29.85,268.0,-1.00,0.21,48.30,OX40N,NTT,JEWELLERY
25,FINCABLES,3.32,32.99,56.34,107.91,110624.0,48706.0,196350.0,1641.55,19.74,76.0,M-SC,13.05,220.0,0.44,1.32,47.72,OX40N,ATH,CABLES

In [24]:
# Top N allocation
df_tmp = df_portfolio_features.sort_values(by = 'CurrAlloc%', ascending=False)
top_n_values = [10, 25, 50]

sum_df = pd.DataFrame({
    'Top_N': top_n_values,
    'Sum_Alloc%': [df_tmp['CurrAlloc%'].head(n).sum() for n in top_n_values]
})

sum_df

   Top_N  Sum_Alloc%
0     10       19.05
1     25       42.57
2     50       72.73

In [25]:
# market-cap-wise allocation
df_tmp = df_portfolio_features[cols]
df_tmp.groupby(df_tmp['Conviction'].str[-2:])['CurrAlloc%'].sum().sort_values(ascending=False)

Conviction
SC    42.55
LC    31.64
MC    25.84
Name: CurrAlloc%, dtype: float64

In [26]:
# criteria-wise allocation
df_portfolio_features.groupby('Criteria')['CurrAlloc%'].sum().sort_values(ascending=False)

Criteria
XY24     27.15
X40      25.46
X40N     16.91
XR        9.09
XY25      6.97
OX40N     6.93
AR        6.70
SR        0.82
Name: CurrAlloc%, dtype: float64

In [27]:
# conviction-wise allocation
df_portfolio_features.groupby('Conviction')['CurrAlloc%'].sum().sort_values(ascending=False)

Conviction
X-LC    29.42
H-SC    22.14
X-MC    20.90
M-SC    10.05
X-SC     9.82
H-MC     2.60
M-MC     1.99
H-LC     1.29
M-LC     0.93
L-SC     0.54
L-MC     0.35
Name: CurrAlloc%, dtype: float64

In [28]:
# sector-wise stats
df_tmp = df_portfolio_features.groupby('Category')[['CurrAlloc%', 'Current', 'Current P/L', 'FTT Amt']].sum().sort_values(by=['Current', 'Current P/L'], ascending=False)
df_tmp['Current P/L%'] = round(df_tmp['Current P/L'] * 100 / df_tmp['Current'], 2)
df_tmp['FTT%'] = round(df_tmp['FTT Amt'] * 100 / df_tmp['Current'], 2)
cols = ['CurrAlloc%', 'Current P/L%', 'FTT%']
df_tmp[cols].sort_values(by=['CurrAlloc%'], ascending=False)

               CurrAlloc%  Current P/L%    FTT%
Category
FMCG                15.67        -13.19   53.12
FINANCE             10.78        -14.70   64.59
IT                  10.57        -43.01  115.01
MISC                 7.05        -27.63   83.07
AUTO                 6.58        -11.41   53.18
BANKS                5.66         -7.50   57.20
INSURANCE            5.29         -4.77   40.43
PAINTS               5.04        -31.32   54.13
PHARMA               4.75         -4.69   38.34
ELECTRICAL           4.07        -16.53   58.01
CHEMICALS            1.98        -37.14  118.87
HEALTHCARE           1.93        -23.66   55.93
AC                   1.93        -10.81   40.86
DURABLES             1.77        -46.30   81.89
APPARELS             1.76         -2.34   37.24
TRAVEL               1.76        -71.13  156.81
FOOTWEAR             1.72        -72.69  141.93
BREWERIES            1.51         -3.72   25.26
REALTY               1.38         -7.64   25.32
CABLES               1.32         24.81   56.34
CERAMICS             1.30        -58.43  106.56
ENGINEERING          1.29        -26.06   83.72
REFINERIES           1.26         -6.68   33.67
CEMENT               1.12        -60.86  181.21
JEWELLERY            1.04       -105.01  176.25
ENTERTAINMENT        0.74        -77.14  182.78
TEXTILES             0.43        -43.43   84.33
HOTELS               0.33       -130.84  212.26

In [29]:
# money to be made criteria-wise
df_portfolio_features.groupby('Criteria')['FTT Amt'].agg(['sum', 'count']).sort_values(by='sum', ascending=False)

                sum  count
Criteria
XY24      3548595.0     21
X40       1905456.0     19
XR        1324781.0     13
X40N      1203397.0     13
AR        1186455.0      9
OX40N      758810.0     10
XY25       398867.0      5
SR         297020.0      2

In [30]:
# money to be made conviction-wise
df_portfolio_features.groupby('Conviction')['FTT Amt'].agg(['sum', 'count']).sort_values(by='sum', ascending=False)

                  sum  count
Conviction
H-SC        3485345.0     24
X-LC        1908502.0     21
X-MC        1615553.0     15
M-SC        1419713.0     14
X-SC        1338781.0      9
H-MC         310959.0      2
L-SC         210092.0      2
M-LC         153128.0      1
M-MC          89304.0      2
L-MC          50529.0      1
H-LC          41475.0      1

In [31]:
# money to be made criteria and conviction-wise
df_portfolio_features.groupby(['Conviction', 'Criteria'])['FTT Amt'].agg(['sum', 'count']).sort_values(by='sum', ascending=False)

                           sum  count
Conviction Criteria
H-SC       XY24      1111692.0      6
X-LC       X40       1030684.0     10
H-SC       AR         946443.0      5
M-SC       XY24       846696.0      6
H-SC       XR         800739.0      7
X-SC       XY24       779537.0      4
X-MC       X40        669626.0      7
           X40N       485847.0      4
X-LC       X40N       363452.0      6
X-SC       X40N       354098.0      3
X-LC       XY24       347945.0      2
H-SC       OX40N      329451.0      4
M-SC       OX40N      323678.0      5
H-SC       SR         297020.0      2
X-MC       XY24       234905.0      2
H-MC       XY24       227820.0      1
X-MC       XY25       225175.0      2
X-SC       X40        205146.0      2
M-SC       XR         173420.0      2
M-LC       XR         153128.0      1
X-LC       XY25       123867.0      2
L-SC       OX40N      105681.0      1
           XR         104411.0      1
H-MC       AR          83139.0      1
M-SC       AR          75919.0      1
L-MC       XR          50529.0      1
M-MC       XY25        49825.0      1
X-LC       XR          42554.0      1
H-LC       AR          41475.0      1
M-MC       AR          39479.0      1

In [32]:
# notebook execution time

end_time = time.time()
execution_time = round(end_time - start_time, 0)
print(f"Notebook execution time: {execution_time} seconds")

Notebook execution time: 37.0 seconds