<a href="https://colab.research.google.com/github/ankit-rathi/Quantvesting_v2/blob/main/myStocks_Portfolio_Analysis.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
'''
!pip install pandas==2.2.2 -qq
!pip install pyxirr -qq
!pip install ta -qq
!pip install yfinance==0.2.59 -qq
'''

'\n!pip install pandas==2.2.2 -qq\n!pip install pyxirr -qq\n!pip install ta -qq\n!pip install yfinance==0.2.59 -qq\n'

In [2]:
# import libraries

import numpy as np
import pandas as pd
import datetime
import warnings
warnings.filterwarnings('ignore')
import yfinance as yfin
import ta
import matplotlib.pyplot as plt
import requests

In [3]:
# notebook start time
import time
import datetime
import pytz

start_time = time.time()

# function to print date timestamp
def print_date_time():
  tz_NY = pytz.timezone('Asia/Kolkata')
  datetime_NY = datetime.datetime.now(tz_NY)
  print("Run date time (IST):", datetime_NY.strftime("%Y-%m-%d %H:%M:%S"))

In [4]:
# function to get booked and reserved amount
def get_amt():
  # fetch the JSON data from the URL
  url = "https://raw.githubusercontent.com/ankit-rathi/Tradevesting_v1/main/data/myPortfolioAmts.json"
  response = requests.get(url)
  pf_amts = response.json()  # parse the JSON data

  # extract values from the JSON
  py_booked_amt_dm = pf_amts["py_booked_amt_dm"]
  py_booked_amt_sv = pf_amts["py_booked_amt_sv"]
  cy_booked_amt_dm = pf_amts["cy_booked_amt_dm"]
  cy_booked_amt_sv = pf_amts["cy_booked_amt_sv"]
  reserve_amt_dm = pf_amts["reserve_amt_dm"]
  reserve_amt_sv = pf_amts["reserve_amt_sv"]

  # perform calculations
  py_booked_amt = py_booked_amt_dm + py_booked_amt_sv
  cy_booked_amt = cy_booked_amt_dm + cy_booked_amt_sv
  reserve_amt = reserve_amt_dm + reserve_amt_sv
  total_booked_amt = py_booked_amt + cy_booked_amt

  return total_booked_amt, reserve_amt, cy_booked_amt, py_booked_amt

gen_output = 0

In [5]:
# function to format the amount
def format_amt(number):
    abs_number = abs(number)

    if abs_number >= 1_00_00_000:  # Crores
        formatted_amt = f"{number / 1_00_00_000:.2f} C"
    elif abs_number >= 1_00_000:  # Lakhs
        formatted_amt = f"{number / 1_00_000:.2f} L"
    elif abs_number >= 1_000:  # Thousands
        formatted_amt = f"{number / 1_000:.2f} K"
    else:
        formatted_amt = f"{number:.2f}"

    return formatted_amt

# function to set start and end date
def get_start_end_date():
  start_date = (datetime.date.today() + datetime.timedelta(days=-365)).strftime('%Y-%m-%d')
  end_date = (datetime.date.today() + datetime.timedelta(days=1)).strftime('%Y-%m-%d')
  return start_date, end_date

# function to fetch my portfolio csv
def get_mypfs_df():
  mypfs_df = pd.read_csv('https://raw.githubusercontent.com/ankit-rathi/Tradevesting_v1/main/data/myPortfolioStocks.csv')
  return mypfs_df

# function to fetch my prospects csv
def get_mypps_df():
  mypps_df = pd.read_csv('https://raw.githubusercontent.com/ankit-rathi/Tradevesting_v1/main/data/myProspectsScrips.csv')
  return mypps_df

# function to fetch screener data
def get_myscreen_df():
  myscreen_df = pd.read_csv('https://raw.githubusercontent.com/ankit-rathi/Tradevesting_v1/main/data/myScreenerDB.csv')
  return myscreen_df

# function to fetch momentum data
def get_myinvmt_df():
  myinvmt_df = pd.read_csv('https://raw.githubusercontent.com/ankit-rathi/Tradevesting_v1/main/data/myInvestments.csv')
  return myinvmt_df

# function to get the stock ids
def get_stock_ids(df_pf):
  stock_n100 = df_pf['Symbol'].unique()

  exclude = ['CADILAHC','MMTC', 'MASFIN']

  stock_ids = df_pf[~df_pf['Symbol'].isin(exclude) ]['Symbol'].unique()

  #mypf = mypf[mypf.Forecast.notnull()]
  #stock_ids = mypf['Symbol'].unique()

  #stock_ids.sort()
  return stock_ids

# get features from screener data
def get_screener_features():
  myscreen_df = get_myscreen_df()
  cols = ['Symbol', 'EPS', 'MedPE', 'ROCE%', 'ROE%', 'CapType']
  return myscreen_df[cols]

# get relative strength
def get_relative_strength(stock_list):

    # Dictionary to store stock tickers and their corresponding percentage price change
    stock_changes = {}

    # Loop through each stock and fetch its price data
    for stock in stock_list:
        try:
            # Download the stock data for the given date range
            stock_data = yfin.Ticker(stock + '.NS').history(period='1mo', interval='1d')[map(str.title, ['open', 'close', 'low', 'high', 'volume'])]

            # Calculate the percentage change for the stock
            if len(stock_data) > 0:
                start_price = stock_data['Close'].iloc[0]
                end_price = stock_data['Close'].iloc[-1]
                percent_change = round(((end_price - start_price) / start_price) * 100, 2)
                stock_changes[stock] = percent_change
            else:
                stock_changes[stock] = np.nan  # If no data is available, set to NaN

        except Exception as e:
            print(f"Error fetching data for {stock}: {e}")
            stock_changes[stock] = np.nan

    # Create a DataFrame with stock tickers and their percentage changes
    df = pd.DataFrame(list(stock_changes.items()), columns=['Symbol', 'Percent_Change'])

    # Drop any stocks with missing data (NaN values)
    df = df.dropna()

    # Calculate the percentile rank based on percentage change
    df['RSP'] = round(df['Percent_Change'].rank(pct=True) * 100, 2)
    cols = ['Symbol', 'RSP']
    df = df[cols]
    # Sort by percentile rank (optional)
    df = df.sort_values(by='RSP', ascending=False).reset_index(drop=True)

    return df

In [6]:
# function to get stock technicals
def stock_prec_dev(stock_symbol):
    #stock_symbol = 'ULTRACEMCO.NS'
    short_window = 20
    mid_window = 50
    long_window = 200
    moving_avg = 'SMA'

    start = datetime.datetime(*map(int, start_date.split('-')))
    end = datetime.datetime(*map(int, end_date.split('-')))

    stock_df = yfin.Ticker(stock_symbol + '.NS').history(period='max', interval='1d')[map(str.title, ['open', 'close', 'low', 'high', 'volume'])]

    stock_df['Max'] = round(max(stock_df['Close']),2)
    stock_df = stock_df[(stock_df.index <= end_date) & (stock_df.index >= start_date)]
    stock_df['200_SMA'] = round(stock_df['Close'].rolling(window = 200, min_periods = 1).mean(),0)
    stock_df['Dev%_200'] = round((stock_df['Close'] - stock_df['200_SMA'])*100/stock_df['200_SMA'],2)
    stock_df.dropna(axis = 0, inplace = True) # remove any null rows

    stock_df['20_SMA'] = stock_df['Close'].rolling(window=20).mean()
    stock_df['50_SMA'] = stock_df['Close'].rolling(window=50).mean()
    stock_df['Symbol'] = stock_symbol

    stock_df['Close'] = round(stock_df['Close'],2)
    stock_df['Min'] = round(min(stock_df['Close']),2)
    stock_df['RSI_14'] = ta.momentum.RSIIndicator(close=stock_df['Close'], window=14).rsi()
    stock_df['RSI_14'] = round(stock_df['RSI_14'],0)
    stock_df['Prev_Close'] = stock_df['Close'].shift(1)
    stock_df.drop(['Open', 'Low', 'High', 'Volume'], axis=1, inplace=True)
    stock_df = stock_df.tail(1)

    max_SMA = max(stock_df['20_SMA'].item(), stock_df['50_SMA'].item(), stock_df['200_SMA'].item())
    min_SMA = min(stock_df['20_SMA'].item(), stock_df['50_SMA'].item(), stock_df['200_SMA'].item())
    ABS_Spread = max_SMA - min_SMA
    stock_df['Spread%'] = round((ABS_Spread / stock_df['200_SMA'].item()) * 100,2)

    return stock_df

# function to compute stock attributes
def get_common_features(stock_ids, df_mypf):

  df_prec_dev = pd.DataFrame()
  df_tmp = get_screener_features()
  df_rs = get_relative_strength(stock_ids)

  for stock_id in stock_ids:
      tmp = stock_prec_dev(stock_id)
      tmp = tmp.reset_index()
      df_prec_dev = pd.concat([df_prec_dev, tmp], ignore_index = True)
  df_prec_dev = pd.merge(df_prec_dev, df_mypf, on= 'Symbol')
  df_prec_dev = pd.merge(df_prec_dev, df_tmp, on= 'Symbol', how='left')
  df_prec_dev = pd.merge(df_prec_dev, df_rs, on= 'Symbol', how='left')
  #print(df_prec_dev.columns)
  df_prec_dev['Curr_PE'] = round(df_prec_dev['Close']/df_prec_dev['EPS'],1)
  df_prec_dev['Dev%_PE'] = round((df_prec_dev['Curr_PE'] - df_prec_dev['MedPE'])*100/df_prec_dev['MedPE'],2)
  df_prec_dev['Conviction'] = df_prec_dev['Conviction'] + '-' + df_prec_dev['CapType']
  return df_prec_dev

# function to arrange stock features
def arrange_features(df_stocks, common_cols, diff_cols):
  df_stocks_common = df_stocks[common_cols].drop_duplicates()
  df_stocks_diff = df_stocks[diff_cols]
  df_stocks_diff['Investment'] = df_stocks_diff['AvgCost'] * df_stocks_diff['Shares']
  df_stocks_diff = df_stocks_diff.groupby(['Symbol'])[['Shares', 'Investment']].aggregate(['sum']).reset_index()
  df_stocks_diff.columns = ['Symbol', 'Shares', 'Investment']
  df_stocks_diff['AvgCost'] = round(df_stocks_diff['Investment']/df_stocks_diff['Shares'],2)
  df_stocks = pd.merge(df_stocks_diff, df_stocks_common, on='Symbol')
  return df_stocks

# plot fact distribution across dimension
def plot_pie_chart(df, dimension, fact):
  # grouping the data by category and calculating the sum of fact for each type
  grouped_data = df.groupby(dimension)[fact].sum()

  # sorting the grouped data in descending order
  grouped_data = grouped_data.sort_values(ascending=False)

  # creating a pie chart
  grouped_data.plot.pie(autopct='%1.1f%%', startangle=90, figsize=(6, 6))

  # adding a title and displaying the plot
  plt.title(f'{dimension} {fact} Distribution')
  plt.ylabel('')  # To hide the y-label
  plt.show()

In [7]:
# function to get portfolio features

def get_portfolio_features(df_common_features):

  print_date_time()
  print('-------------------')

  #df_common_features["Target"] = df_common_features["Target"].fillna(df_common_features["Max"])
  df_common_features['NTT'] = np.where(df_common_features['Strategy']== 'NTT', df_common_features["Target"], df_common_features['Max'])
  df_common_features['LTT'] = np.where(df_common_features['Strategy']== 'BTT', df_common_features["Target"], df_common_features['Max'])
  df_common_features['BOL'] = df_common_features['Min']

  tmp_df = df_common_features[df_common_features['Symbol'].isin(mypf_df[mypf_df['InPortfolio'] != 'NA'].Symbol.values)]
  print('qualified stocks: '+str(len(tmp_df['Symbol'].unique())))
  tmp_df1 = tmp_df[tmp_df['LatestQtr'] == 1]
  print('with latest results: '+str(len(tmp_df1['Symbol'].unique())))
  tmp_df1 = tmp_df1[tmp_df1['StarStock'] == 1]
  print('still star stocks: '+str(len(tmp_df1['Symbol'].unique())))
  tmp_df['Investment'] = tmp_df['AvgCost'] * tmp_df['Shares']
  tmp_df['Current'] = round(tmp_df['Close'] * tmp_df['Shares'],0)
  tmp_df['Previous'] = tmp_df['Prev_Close'] * tmp_df['Shares']
  tmp_df['EstimatedST'] = tmp_df['NTT'] * tmp_df['Shares']
  tmp_df['EstimatedLT'] = tmp_df['LTT'] * tmp_df['Shares']
  tmp_df['Current P/L'] = round((tmp_df['Current'] - tmp_df['Investment']),0)
  tmp_df['Today P/L%'] = round((tmp_df['Current'] - tmp_df['Previous'])*100/tmp_df['Previous'],2)
  tmp_df['Current P/L%'] = round((tmp_df['Current'] - tmp_df['Investment'])*100/tmp_df['Investment'],2)
  tmp_df['EstimatedST P/L%'] = round((tmp_df['EstimatedST'] - tmp_df['Investment'])*100/tmp_df['Investment'],2)
  tmp_df['EstimatedLT P/L%'] = round((tmp_df['EstimatedLT'] - tmp_df['Investment'])*100/tmp_df['Investment'],2)
  tmp_df['NTT%'] = round((tmp_df['NTT'] - tmp_df['Close'])*100/tmp_df['Close'],2)
  tmp_df['LTT%'] = round((tmp_df['LTT'] - tmp_df['Close'])*100/tmp_df['Close'],2)
  tmp_df['Gained%'] = round((tmp_df['Close'] - tmp_df['BOL'])*100/tmp_df['BOL'],2)
  investment = round(sum(tmp_df['AvgCost']*tmp_df['Shares']),0)
  current = round(sum(tmp_df['Close']*tmp_df['Shares']),0)
  tmp_df['InitAlloc%'] = round(tmp_df['Investment']*100/investment,2)
  tmp_df['CurrAlloc%'] = round(tmp_df['Current']*100/current,2)
  tmp_df['FTT'] = tmp_df['LTT']
  tmp_df.loc[tmp_df['Strategy'] == 'NTT', 'FTT'] = tmp_df['NTT']
  tmp_df['FTT%'] = tmp_df['LTT%']
  tmp_df.loc[tmp_df['Strategy'] == 'NTT', 'FTT%'] = tmp_df['NTT%']
  tmp_df['FTT Amt'] = round(tmp_df['FTT%'] * tmp_df['Current']/100,0)
  tmp_df['OTT%'] = round((tmp_df['FTT'] - tmp_df['AvgCost'])*100/tmp_df['AvgCost'],2)
  tmp_df['RRR Ind'] = round(tmp_df['Current P/L']/tmp_df['FTT Amt'],2)
  tmp_df['Risk Ind'] = round(tmp_df['Current P/L%']*tmp_df['CurrAlloc%'],0)

  return tmp_df

# function to print portfolio features
def print_portfolio_stats(df_portfolio_features, myinvmt_df):
  from pyxirr import xirr

  total_booked_amt, reserve_amt, cy_booked_amt, py_booked_amt = get_amt()

  dates = myinvmt_df['Date'].values
  dates = np.append(dates, datetime.date.today().strftime('%d-%b-%y'))
  investment = myinvmt_df['Investment'].values
  dates= pd.to_datetime(dates)

  current = round(sum(df_portfolio_features['Close']*df_portfolio_features['Shares']),0) + reserve_amt
  investment_xirr = np.append(investment, current)
  cagr = round(xirr(pd.DataFrame({"dates": dates, "amounts": investment_xirr}))*100,2)

  investment = -sum(investment)
  invested = round(sum(df_portfolio_features['AvgCost']*df_portfolio_features['Shares']),0) + reserve_amt
  previous = round(sum(df_portfolio_features['Prev_Close']*df_portfolio_features['Shares']),0) + reserve_amt
  cy_invested = investment + py_booked_amt

  today_pnl_amount = current-previous
  today_pnl_percentage = round((current-previous)*100/previous,2)

  curr_pnl_amount = current-invested
  curr_pnl_percentage = round((curr_pnl_amount)*100/(cy_invested),2)

  cy_pnl_amount = cy_booked_amt + curr_pnl_amount
  cy_pnl_percentage = round((cy_pnl_amount)*100/cy_invested,2)

  overall_pnl_amount = total_booked_amt + curr_pnl_amount
  overall_pnl_percentage = round((overall_pnl_amount)*100/investment,2)

  estimate_st = round(sum(df_portfolio_features['FTT']*df_portfolio_features['Shares']),0)  + reserve_amt
  est_st_pnl_amount = estimate_st-current
  est_st_pnl_percentage = round((est_st_pnl_amount)*100/current,2)

  estimate_lt = round(sum(df_portfolio_features['LTT']*df_portfolio_features['Shares']),0)  + reserve_amt
  est_lt_pnl_amount = estimate_lt-current
  est_lt_pnl_percentage = round((est_lt_pnl_amount)*100/current,2)

  total_profit = round(sum(df_portfolio_features[df_portfolio_features['Current P/L%'] > 0]['Current']) - sum(df_portfolio_features[df_portfolio_features['Current P/L%'] > 0]['Investment']),0)
  total_loss = round(sum(df_portfolio_features[df_portfolio_features['Current P/L%'] < 0]['Current']) - sum(df_portfolio_features[df_portfolio_features['Current P/L%'] < 0]['Investment']),0)

  cy_booked_percentage = round((cy_booked_amt)*100/current,2)
  py_booked_percentage = round((py_booked_amt)*100/investment,2)
  total_booked_percentage = round((total_booked_amt)*100/investment,2)

  print('-------------------')
  print('Initial Investment: ', format_amt(investment))
  print('CY Investment: ', format_amt(cy_invested))
  print('Reserve: ', format_amt(reserve_amt))
  print('Current: ',  format_amt(current))
  print('-------------------')
  print('Today PnL: '+ '{} ({}%)'.format(format_amt(today_pnl_amount), today_pnl_percentage))
  print('Current PnL: '+ '{} ({}%)'.format(format_amt(curr_pnl_amount), curr_pnl_percentage))
  print('CY Booked + Current PnL: '+ '{} ({}%)'.format(format_amt(cy_pnl_amount), cy_pnl_percentage))
  print('-------------------')
  print('Total profit: ', format_amt(total_profit))
  print('Total loss: ', format_amt(total_loss))
  print('-------------------')
  print('Total Booked + Current PnL: '+ '{} ({}%)'.format(format_amt(overall_pnl_amount), overall_pnl_percentage))
  print('Total Booked PnL: '+ '{} ({}%)'.format(format_amt(total_booked_amt), total_booked_percentage))
  print('Curr Year Booked PnL: '+ '{} ({}%)'.format(format_amt(cy_booked_amt), cy_booked_percentage))
  print('Prev Year Booked PnL: '+ '{} ({}%)'.format(format_amt(py_booked_amt), py_booked_percentage))
  print('===================')
  print('Est FTT: ',  format_amt(estimate_st))
  print('Est FTT PnL: '+ '{} ({}%)'.format(format_amt(est_st_pnl_amount), est_st_pnl_percentage))

  print('===================')
  print('Deployed: ', format_amt(investment))

  print('Current: ', format_amt(current))

  print('CAGR/XIRR %: '+'{}%'.format(cagr))

In [8]:
# get start and end date
start_date, end_date = get_start_end_date()

# get portfolio and prospects data
mypfs_df = get_mypfs_df()
mypps_df = get_mypps_df()
myinvmt_df = get_myinvmt_df()

# merge above datasets
mypf_df = pd.merge(mypfs_df, mypps_df, on="Symbol")

# seggregate dm and sv portfolio
dm_pf = mypf_df[mypf_df['InPortfolio'] == 'DM']
sv_pf = mypf_df[mypf_df['InPortfolio'] == 'SV']

# build portfolio stock dataframe
dm_stocks = get_stock_ids(dm_pf)
sv_stocks = get_stock_ids(sv_pf)
df_stocks = pd.concat([dm_pf,sv_pf], ignore_index = True)

# arrange common and diff stock features
common_cols = ['Symbol', 'Target', 'Criteria', 'Strategy', 'CumlRnk', 'LatestQtr', 'StarStock', 'Conviction', 'Category', 'InFolio', 'XIRR', 'MBQ']
diff_cols = ['Symbol', 'AvgCost', 'Shares']
df_stocks = arrange_features(df_stocks, common_cols, diff_cols)

# get common features
stock_ids = df_stocks['Symbol'].values
df_common_features = get_common_features(stock_ids, df_stocks)

df_common_features.reset_index(drop=True, inplace=True)
df_common_features.drop(['Date'], axis=1, inplace=True)
# get and print portfolio features
df_portfolio_features = get_portfolio_features(df_common_features)

print_portfolio_stats(df_portfolio_features, myinvmt_df)

df = df_portfolio_features
#plot_pie_chart(df, 'CapType', 'Current')
list_ox40n = list(df[df['MBQ'].str.contains('OX40N', na=False)]['Symbol'].values)

Run date time (IST): 2026-05-14 16:34:00
-------------------
qualified stocks: 92
with latest results: 31
still star stocks: 20

-------------------
Initial Investment:  1.40 C
CY Investment:  1.82 C
Reserve:  1.49 K
Current:  1.48 C
-------------------
Today PnL: 96.72 K (0.66%)
Current PnL: -34.98 L (-19.18%)
CY Booked + Current PnL: -32.90 L (-18.04%)
-------------------
Total profit:  2.06 L
Total loss:  -37.04 L
-------------------
Total Booked + Current PnL: 9.97 L (7.14%)
Total Booked PnL: 44.95 L (32.22%)
Curr Year Booked PnL: 2.08 L (1.4%)
Prev Year Booked PnL: 42.87 L (30.73%)
===================
Est FTT:  2.55 C
Est FTT PnL: 1.07 C (72.37%)
===================
Deployed:  1.40 C
Current:  1.48 C
CAGR/XIRR %: 2.95%

In [9]:
# top 5 near their targets
cols = ['Symbol', 'Today P/L%', 'Current P/L%', 'FTT%', 'OTT%', 'FTT Amt', 'Current P/L', 'Current', 'FTT', 'Dev%_PE', 'RSI_14','Conviction', 'Spread%',  'CumlRnk', 'RRR Ind', 'CurrAlloc%', 'Gained%', 'Criteria', 'Strategy', 'Category']
df_tmp = df_portfolio_features[~df_portfolio_features['Symbol'].isin(['ENRIN','BLUSPRING','DIGITIDE'])]
df_tmp = df_tmp.sort_values(by = 'FTT Amt', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
59,PIDILITIND,2.64,5.15,12.57,18.37,18651.0,7270.0,148380.0,1670.26,-26.30,65.0,X-LC,5.57,5.0,0.39,1.00,16.50,X40,ATH,CHEMICALS
55,MASFIN,-0.02,-0.47,22.15,21.57,21600.0,-465.0,97515.0,397.04,-14.18,48.0,H-SC,5.69,167.0,-0.02,0.66,21.04,XR,ATH,FINANCE
51,KOTAKBANK,1.47,2.39,18.28,21.11,25918.0,3312.0,141784.0,453.24,-12.01,55.0,X-LC,7.26,12.0,0.13,0.96,8.43,X40,ATH,BANKS
17,CIPLA,8.22,16.32,15.79,34.69,28130.0,24990.0,178151.0,1663.60,-10.08,71.0,X-LC,11.01,18.0,0.89,1.20,20.49,X40N,ATH,PHARMA
53,M&M,2.00,2.99,19.80,23.38,28280.0,4145.0,142826.0,3802.40,-12.70,49.0,X-LC,8.22,25.0,0.15,0.96,8.28,X40N,ATH,AUTO

In [10]:
# top 5 today
df_tmp = df_portfolio_features.sort_values(by = 'Today P/L%', ascending=False)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
17,CIPLA,8.22,16.32,15.79,34.69,28130.0,24990.0,178151.0,1663.60,-10.08,71.0,X-LC,11.01,18.0,0.89,1.20,20.49,X40N,ATH,PHARMA
3,ALKYLAMINE,6.92,-25.47,159.79,93.63,120242.0,-25713.0,75250.0,4546.37,-20.23,65.0,H-SC,16.51,142.0,-0.21,0.51,42.09,SR,ATH,CHEMICALS
91,ZYDUSLIFE,5.58,4.58,29.69,35.63,65070.0,9592.0,219166.0,1286.17,-9.01,67.0,H-MC,3.24,120.0,0.15,1.48,15.23,AR,ATH,PHARMA
11,BERGEPAINT,5.16,-1.61,27.36,25.32,69386.0,-4147.0,253602.0,680.00,-6.90,71.0,X-MC,11.80,68.0,-0.06,1.71,31.99,XY24,NTT,PAINTS
24,EASEMYTRIP,4.82,-54.36,219.23,45.70,176916.0,-96116.0,80699.0,26.40,-16.12,61.0,M-SC,6.93,204.0,-0.54,0.54,41.37,XY24,NTT,TRAVEL

In [11]:
# bottom 5 today
df_tmp = df_portfolio_features.sort_values(by = 'Today P/L%', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
67,ROUTE,-2.56,-61.57,337.53,68.16,172616.0,-81925.0,51141.0,2215.45,-68.92,46.0,H-SC,25.94,141.0,-0.47,0.35,21.84,SR,ATH,IT
45,INFY,-2.50,-25.46,80.09,34.24,186798.0,-79653.0,233235.0,1972.00,-41.22,27.0,X-LC,17.58,3.0,-0.43,1.57,0.00,X40,NTT,IT
13,BSOFT,-2.45,-43.63,167.51,50.79,132802.0,-61373.0,79280.0,831.70,-27.72,24.0,H-SC,5.32,172.0,-0.46,0.54,0.00,XR,ATH,IT
83,TTKPRESTIG,-2.44,-32.65,48.61,0.09,32995.0,-32899.0,67878.0,770.00,57.52,53.0,M-SC,17.12,250.0,-1.00,0.46,20.87,OX40N,NTT,DURABLES
61,RAJESHEXPO,-2.31,-78.92,374.75,0.07,108355.0,-108263.0,28914.0,518.00,959.34,40.0,L-SC,32.09,268.0,-1.00,0.20,35.74,OX40N,NTT,JEWELLERY

In [12]:
# top 5 to exit based on CumlRnk
df_tmp = df_portfolio_features[~df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])]
df_tmp = df_tmp[(df_tmp['Current P/L%'] > -1) & (df_tmp['Current P/L%'] < 1)].sort_values(by = 'CumlRnk', ascending=False)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
55,MASFIN,-0.02,-0.47,22.15,21.57,21600.0,-465.0,97515.0,397.04,-14.18,48.0,H-SC,5.69,167.0,-0.02,0.66,21.04,XR,ATH,FINANCE

In [13]:
# OX40N stocks to exit
df_tmp = df_portfolio_features[(df_portfolio_features['Symbol'].isin(list_ox40n))].sort_values(by = 'Current P/L%', ascending=False)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
25,FINCABLES,-0.31,36.07,52.80,107.91,106072.0,53250.0,200894.0,1641.55,22.27,64.0,M-SC,23.23,220.0,0.50,1.36,51.14,OX40N,ATH,CABLES
72,SIS,3.08,-11.48,36.98,21.26,36348.0,-12742.0,98290.0,528.00,2335.75,65.0,H-SC,13.02,168.0,-0.35,0.66,46.14,OX40N,NTT,MISC
16,CERA,-2.06,-25.61,66.53,23.89,87060.0,-45045.0,130858.0,9475.00,-28.16,60.0,H-SC,9.47,153.0,-0.52,0.88,25.75,OX40N,NTT,CERAMICS
50,KANSAINER,1.47,-25.92,53.17,13.47,106219.0,-69894.0,199773.0,340.00,-36.25,68.0,H-SC,14.94,162.0,-0.66,1.35,39.54,XY24,NTT,PAINTS
43,INDIGOPNTS,-0.80,-30.56,44.03,0.02,53374.0,-53337.0,121222.0,1408.00,84.71,68.0,M-SC,20.48,222.0,-1.00,0.82,37.54,OX40N,NTT,PAINTS

In [14]:
# top 5 to book for rotation
df_tmp = df_portfolio_features[(df_portfolio_features['Current P/L%'] > 20) ].sort_values(by = 'CumlRnk', ascending=False)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
25,FINCABLES,-0.31,36.07,52.80,107.91,106072.0,53250.0,200894.0,1641.55,22.27,64.0,M-SC,23.23,220.0,0.5,1.36,51.14,OX40N,ATH,CABLES
68,SATIN,-0.29,24.57,21.89,51.83,75339.0,67885.0,344169.0,274.00,11.70,84.0,H-SC,24.28,159.0,0.9,2.32,67.66,XY24,NTT,FINANCE

In [15]:
# top 5 to monitor for exit
df_tmp = df_portfolio_features[~df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])]
df_tmp = df_tmp[(df_tmp['Current P/L%'] > 0) ].sort_values(by = 'Dev%_PE', ascending=False)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
25,FINCABLES,-0.31,36.07,52.80,107.91,106072.0,53250.0,200894.0,1641.55,22.27,64.0,M-SC,23.23,220.0,0.50,1.36,51.14,OX40N,ATH,CABLES
68,SATIN,-0.29,24.57,21.89,51.83,75339.0,67885.0,344169.0,274.00,11.70,84.0,H-SC,24.28,159.0,0.90,2.32,67.66,XY24,NTT,FINANCE
91,ZYDUSLIFE,5.58,4.58,29.69,35.63,65070.0,9592.0,219166.0,1286.17,-9.01,67.0,H-MC,3.24,120.0,0.15,1.48,15.23,AR,ATH,PHARMA
73,SONACOMS,-0.64,1.64,36.84,39.09,37879.0,1662.0,102821.0,804.02,-19.52,56.0,M-MC,19.96,193.0,0.04,0.69,45.45,AR,ATH,AUTO

In [16]:
# top 5 to book for rotation from weak conviction
df_tmp = df_portfolio_features[~df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])]
df_tmp = df_tmp[~df_tmp['Criteria'].isin(['XY25','XY24','X40', 'X40N'])].sort_values(by = 'RRR Ind', ascending=False)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
25,FINCABLES,-0.31,36.07,52.80,107.91,106072.0,53250.0,200894.0,1641.55,22.27,64.0,M-SC,23.23,220.0,0.50,1.36,51.14,OX40N,ATH,CABLES
91,ZYDUSLIFE,5.58,4.58,29.69,35.63,65070.0,9592.0,219166.0,1286.17,-9.01,67.0,H-MC,3.24,120.0,0.15,1.48,15.23,AR,ATH,PHARMA
73,SONACOMS,-0.64,1.64,36.84,39.09,37879.0,1662.0,102821.0,804.02,-19.52,56.0,M-MC,19.96,193.0,0.04,0.69,45.45,AR,ATH,AUTO
55,MASFIN,-0.02,-0.47,22.15,21.57,21600.0,-465.0,97515.0,397.04,-14.18,48.0,H-SC,5.69,167.0,-0.02,0.66,21.04,XR,ATH,FINANCE
75,SURYODAY,-1.00,-2.03,25.58,23.03,44878.0,-3631.0,175440.0,216.00,90.79,70.0,H-SC,14.52,166.0,-0.08,1.18,47.72,XR,NTT,BANKS

In [17]:
# top 5 to accumulate based on lowest RSI_14
df_tmp = df_portfolio_features[df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])].sort_values(by = 'RSI_14', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
33,HCLTECH,-1.68,-27.06,66.58,21.51,117492.0,-65456.0,176468.0,1872.35,-23.49,24.0,X-LC,15.63,8.0,-0.56,1.19,0.00,X40,ATH,IT
45,INFY,-2.50,-25.46,80.09,34.24,186798.0,-79653.0,233235.0,1972.00,-41.22,27.0,X-LC,17.58,3.0,-0.43,1.57,0.00,X40,NTT,IT
79,TCS,-1.18,-34.07,91.97,26.57,280928.0,-157817.0,305456.0,4311.58,-44.28,27.0,X-LC,15.35,2.0,-0.56,2.06,0.00,X40,ATH,IT
58,PGHH,-0.22,-27.80,82.84,32.01,127706.0,-59360.0,154160.0,17616.87,-51.15,35.0,X-MC,16.71,57.0,-0.46,1.04,5.44,X40,ATH,FMCG
88,VOLTAS,2.75,1.19,43.49,45.20,84381.0,2283.0,194025.0,1856.00,15.85,39.0,X-MC,1.52,79.0,0.03,1.31,6.01,XY25,NTT,AC

In [18]:
# top 5 to accumulate based on Spread and CumlRnk
df_tmp = df_portfolio_features[df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])]
df_tmp = df_tmp[(df_tmp['CumlRnk'] < 100)].sort_values(by = 'Spread%', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
88,VOLTAS,2.75,1.19,43.49,45.20,84381.0,2283.0,194025.0,1856.00,15.85,39.0,X-MC,1.52,79.0,0.03,1.31,6.01,XY25,NTT,AC
84,UNITDSPR,1.28,-6.52,29.19,20.77,63888.0,-15274.0,218870.0,1644.00,-17.10,43.0,X-MC,2.92,64.0,-0.24,1.48,4.41,X40N,NTT,BREWERIES
65,RELIANCE,0.22,-12.58,43.34,25.30,76136.0,-25291.0,175672.0,1952.00,-15.03,43.0,X-LC,3.58,21.0,-0.33,1.19,4.38,XY25,BTT,REFINERIES
39,ICICIGI,2.48,-2.06,21.85,19.34,42822.0,-4126.0,195983.0,2252.93,-17.63,58.0,X-MC,4.62,66.0,-0.10,1.32,9.46,X40,ATH,INSURANCE
19,COLPAL,0.57,-18.49,73.62,41.51,158033.0,-48705.0,214660.0,3726.84,-1.37,57.0,X-MC,5.35,62.0,-0.31,1.45,20.01,XY25,ATH,FMCG

In [19]:
# top 5 to accumulate based on lowest Gained%
df_tmp = df_portfolio_features[df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])].sort_values(by = 'Gained%', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
45,INFY,-2.50,-25.46,80.09,34.24,186798.0,-79653.0,233235.0,1972.00,-41.22,27.0,X-LC,17.58,3.0,-0.43,1.57,0.00,X40,NTT,IT
33,HCLTECH,-1.68,-27.06,66.58,21.51,117492.0,-65456.0,176468.0,1872.35,-23.49,24.0,X-LC,15.63,8.0,-0.56,1.19,0.00,X40,ATH,IT
79,TCS,-1.18,-34.07,91.97,26.57,280928.0,-157817.0,305456.0,4311.58,-44.28,27.0,X-LC,15.35,2.0,-0.56,2.06,0.00,X40,ATH,IT
32,HAVELLS,0.97,-22.48,70.37,32.08,178928.0,-73723.0,254268.0,2062.85,-27.08,41.0,X-MC,10.99,63.0,-0.41,1.72,2.56,X40,ATH,ELECTRICAL
65,RELIANCE,0.22,-12.58,43.34,25.30,76136.0,-25291.0,175672.0,1952.00,-15.03,43.0,X-LC,3.58,21.0,-0.33,1.19,4.38,XY25,BTT,REFINERIES

In [20]:
# top 5 to accumulate based on lowest CurrAlloc%
df_tmp = df_portfolio_features[df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])].sort_values(by = 'CurrAlloc%', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
64,RELAXO,1.52,-62.31,304.12,52.31,166378.0,-90452.0,54708.0,1176.00,-59.83,44.0,X-SC,24.87,92.0,-0.54,0.37,22.32,X40N,NTT,FOOTWEAR
10,BATAINDIA,0.61,-54.49,197.07,35.20,115406.0,-70109.0,58561.0,2096.00,-23.18,43.0,X-SC,26.17,91.0,-0.61,0.40,16.14,X40,NTT,FOOTWEAR
60,QUESS,-0.38,-15.05,104.71,73.90,94992.0,-16074.0,90719.0,424.00,-54.27,55.0,X-SC,12.62,80.0,-0.17,0.61,23.67,XY24,NTT,MISC
28,GODREJCP,0.27,-7.53,42.17,31.47,57954.0,-11185.0,137429.0,1469.04,-2.65,43.0,X-LC,7.41,32.0,-0.19,0.93,5.45,X40N,ATH,FMCG
51,KOTAKBANK,1.47,2.39,18.28,21.11,25918.0,3312.0,141784.0,453.24,-12.01,55.0,X-LC,7.26,12.0,0.13,0.96,8.43,X40,ATH,BANKS

In [21]:
# top 5 to accumulate based on CumlRnk
df_tmp = df_portfolio_features.sort_values(by = 'CumlRnk', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
47,ITC,0.90,-19.08,47.14,19.06,129753.0,-64915.0,275251.0,452.00,-55.52,51.0,X-LC,15.49,1.0,-0.50,1.86,6.78,X40,NTT,FMCG
79,TCS,-1.18,-34.07,91.97,26.57,280928.0,-157817.0,305456.0,4311.58,-44.28,27.0,X-LC,15.35,2.0,-0.56,2.06,0.00,X40,ATH,IT
45,INFY,-2.50,-25.46,80.09,34.24,186798.0,-79653.0,233235.0,1972.00,-41.22,27.0,X-LC,17.58,3.0,-0.43,1.57,0.00,X40,NTT,IT
81,TMPV,0.56,-22.89,77.12,36.58,211608.0,-81453.0,274388.0,600.00,-83.62,46.0,X-LC,5.79,4.0,-0.38,1.85,14.37,XY24,NTT,AUTO
59,PIDILITIND,2.64,5.15,12.57,18.37,18651.0,7270.0,148380.0,1670.26,-26.30,65.0,X-LC,5.57,5.0,0.39,1.00,16.50,X40,ATH,CHEMICALS

In [22]:
# top 5 for average up
df_tmp = df_portfolio_features[(df_portfolio_features['Dev%_200'] > 5)].sort_values(by = 'CurrAlloc%', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
44,INDUSINDBK,1.72,-32.97,98.26,32.89,50850.0,-25456.0,51750.0,1800.00,-343.70,55.0,L-MC,7.40,258.0,-0.50,0.35,27.38,XR,NTT,BANKS
72,SIS,3.08,-11.48,36.98,21.26,36348.0,-12742.0,98290.0,528.00,2335.75,65.0,H-SC,13.02,168.0,-0.35,0.66,46.14,OX40N,NTT,MISC
73,SONACOMS,-0.64,1.64,36.84,39.09,37879.0,1662.0,102821.0,804.02,-19.52,56.0,M-MC,19.96,193.0,0.04,0.69,45.45,AR,ATH,AUTO
5,ATULAUTO,-0.39,-15.63,72.53,45.57,120638.0,-30804.0,166328.0,844.00,3602.70,56.0,M-SC,7.25,248.0,-0.26,1.12,28.00,XY24,NTT,AUTO
75,SURYODAY,-1.00,-2.03,25.58,23.03,44878.0,-3631.0,175440.0,216.00,90.79,70.0,H-SC,14.52,166.0,-0.08,1.18,47.72,XR,NTT,BANKS

In [23]:
# top 5 RSP
df_tmp = df_portfolio_features.sort_values(by = 'RSP', ascending=False)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
68,SATIN,-0.29,24.57,21.89,51.83,75339.0,67885.0,344169.0,274.00,11.70,84.0,H-SC,24.28,159.0,0.90,2.32,67.66,XY24,NTT,FINANCE
3,ALKYLAMINE,6.92,-25.47,159.79,93.63,120242.0,-25713.0,75250.0,4546.37,-20.23,65.0,H-SC,16.51,142.0,-0.21,0.51,42.09,SR,ATH,CHEMICALS
75,SURYODAY,-1.00,-2.03,25.58,23.03,44878.0,-3631.0,175440.0,216.00,90.79,70.0,H-SC,14.52,166.0,-0.08,1.18,47.72,XR,NTT,BANKS
25,FINCABLES,-0.31,36.07,52.80,107.91,106072.0,53250.0,200894.0,1641.55,22.27,64.0,M-SC,23.23,220.0,0.50,1.36,51.14,OX40N,ATH,CABLES
72,SIS,3.08,-11.48,36.98,21.26,36348.0,-12742.0,98290.0,528.00,2335.75,65.0,H-SC,13.02,168.0,-0.35,0.66,46.14,OX40N,NTT,MISC

In [24]:
# Top N allocation
df_tmp = df_portfolio_features.sort_values(by = 'CurrAlloc%', ascending=False)
top_n_values = [10, 25, 50]

sum_df = pd.DataFrame({
    'Top_N': top_n_values,
    'Sum_Alloc%': [df_tmp['CurrAlloc%'].head(n).sum() for n in top_n_values]
})

sum_df

   Top_N  Sum_Alloc%
0     10       19.25
1     25       42.70
2     50       73.04

In [25]:
# market-cap-wise allocation
df_tmp = df_portfolio_features[cols]
df_tmp.groupby(df_tmp['Conviction'].str[-2:])['CurrAlloc%'].sum().sort_values(ascending=False)

Conviction
SC    42.63
LC    31.38
MC    26.03
Name: CurrAlloc%, dtype: float64

In [26]:
# criteria-wise allocation
df_portfolio_features.groupby('Criteria')['CurrAlloc%'].sum().sort_values(ascending=False)

Criteria
XY24     27.55
X40      25.49
X40N     16.79
XR        8.92
OX40N     6.97
XY25      6.76
AR        6.70
SR        0.86
Name: CurrAlloc%, dtype: float64

In [27]:
# conviction-wise allocation
df_portfolio_features.groupby('Conviction')['CurrAlloc%'].sum().sort_values(ascending=False)

Conviction
X-LC    29.25
H-SC    22.35
X-MC    21.03
M-SC    10.05
X-SC     9.71
H-MC     2.67
M-MC     1.98
H-LC     1.25
M-LC     0.88
L-SC     0.52
L-MC     0.35
Name: CurrAlloc%, dtype: float64

In [28]:
# sector-wise stats
df_tmp = df_portfolio_features.groupby('Category')[['CurrAlloc%', 'Current', 'Current P/L', 'FTT Amt']].sum().sort_values(by=['Current', 'Current P/L'], ascending=False)
df_tmp['Current P/L%'] = round(df_tmp['Current P/L'] * 100 / df_tmp['Current'], 2)
df_tmp['FTT%'] = round(df_tmp['FTT Amt'] * 100 / df_tmp['Current'], 2)
cols = ['CurrAlloc%', 'Current P/L%', 'FTT%']
df_tmp[cols].sort_values(by=['CurrAlloc%'], ascending=False)

               CurrAlloc%  Current P/L%    FTT%
Category
FMCG                15.51        -15.22   55.83
FINANCE             10.87        -14.50   64.30
IT                   9.98        -52.43  129.18
MISC                 6.93        -30.61   87.35
AUTO                 6.61        -11.57   53.40
BANKS                5.75         -6.60   55.89
PAINTS               5.69        -17.02   37.34
INSURANCE            5.38         -3.70   39.00
PHARMA               5.09          1.97   29.54
ELECTRICAL           3.94        -21.35   64.54
CHEMICALS            2.16        -26.70  102.21
HEALTHCARE           1.99        -21.78   53.55
AC                   1.84        -17.27   49.07
TRAVEL               1.73        -74.49  161.86
APPARELS             1.71         -6.13   42.34
FOOTWEAR             1.69        -76.78  147.66
DURABLES             1.67        -56.43   94.49
BREWERIES            1.48         -6.98   29.19
REALTY               1.36         -9.79   27.83
CABLES               1.36         26.51   52.80
CERAMICS             1.34        -54.37  101.26
ENGINEERING          1.19        -37.61  100.54
REFINERIES           1.19        -14.40   43.34
CEMENT               1.12        -62.12  183.41
JEWELLERY            1.02       -113.52  187.70
ENTERTAINMENT        0.70        -85.71  196.47
TEXTILES             0.42        -48.51   90.85
HOTELS               0.32       -139.82  224.41

In [29]:
# money to be made criteria-wise
df_portfolio_features.groupby('Criteria')['FTT Amt'].agg(['sum', 'count']).sort_values(by='sum', ascending=False)

                sum  count
Criteria
XY24      3514969.0     21
X40       1925667.0     19
XR        1360829.0     13
X40N      1236863.0     13
AR        1192600.0      9
OX40N      760427.0     10
XY25       439610.0      5
SR         292858.0      2

In [30]:
# money to be made conviction-wise
df_portfolio_features.groupby('Conviction')['FTT Amt'].agg(['sum', 'count']).sort_values(by='sum', ascending=False)

                  sum  count
Conviction
H-SC        3477857.0     24
X-LC        1963990.0     21
X-MC        1616614.0     15
M-SC        1429275.0     14
X-SC        1366001.0      9
H-MC         303096.0      2
L-SC         214606.0      2
M-LC         161034.0      1
M-MC          91613.0      2
L-MC          50850.0      1
H-LC          48887.0      1

In [31]:
# money to be made criteria and conviction-wise
df_portfolio_features.groupby(['Conviction', 'Criteria'])['FTT Amt'].agg(['sum', 'count']).sort_values(by='sum', ascending=False)

                           sum  count
Conviction Criteria
H-SC       XY24      1073144.0      6
X-LC       X40       1049321.0     10
H-SC       AR         962267.0      5
M-SC       XY24       851984.0      6
H-SC       XR         809322.0      7
X-SC       XY24       788414.0      4
X-MC       X40        667492.0      7
           X40N       506250.0      4
X-SC       X40N       368733.0      3
X-LC       XY24       362943.0      2
           X40N       361880.0      6
H-SC       OX40N      340266.0      4
M-SC       OX40N      311806.0      5
H-SC       SR         292858.0      2
X-MC       XY25       242414.0      2
H-MC       XY24       238026.0      1
X-SC       X40        208854.0      2
X-MC       XY24       200458.0      2
M-SC       XR         186988.0      2
M-LC       XR         161034.0      1
X-LC       XY25       143462.0      2
L-SC       OX40N      108355.0      1
           XR         106251.0      1
M-SC       AR          78497.0      1
H-MC       AR          65070.0      1
M-MC       XY25        53734.0      1
L-MC       XR          50850.0      1
H-LC       AR          48887.0      1
X-LC       XR          46384.0      1
M-MC       AR          37879.0      1

In [32]:
# notebook execution time

end_time = time.time()
execution_time = round(end_time - start_time, 0)
print(f"Notebook execution time: {execution_time} seconds")

Notebook execution time: 29.0 seconds