<a href="https://colab.research.google.com/github/ankit-rathi/Quantvesting_v2/blob/main/myStocks_Portfolio_Analysis.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
'''
!pip install pandas==2.2.2 -qq
!pip install pyxirr -qq
!pip install ta -qq
!pip install yfinance==0.2.59 -qq
'''

'\n!pip install pandas==2.2.2 -qq\n!pip install pyxirr -qq\n!pip install ta -qq\n!pip install yfinance==0.2.59 -qq\n'

In [2]:
# import libraries

import numpy as np
import pandas as pd
import datetime
import warnings
warnings.filterwarnings('ignore')
import yfinance as yfin
import ta
import matplotlib.pyplot as plt
import requests

In [3]:
# notebook start time
import time
import datetime
import pytz

start_time = time.time()

# function to print date timestamp
def print_date_time():
  tz_NY = pytz.timezone('Asia/Kolkata')
  datetime_NY = datetime.datetime.now(tz_NY)
  print("Run date time (IST):", datetime_NY.strftime("%Y-%m-%d %H:%M:%S"))

In [4]:
# function to get booked and reserved amount
def get_amt():
  # fetch the JSON data from the URL
  url = "https://raw.githubusercontent.com/ankit-rathi/Tradevesting_v1/main/data/myPortfolioAmts.json"
  response = requests.get(url)
  pf_amts = response.json()  # parse the JSON data

  # extract values from the JSON
  py_booked_amt_dm = pf_amts["py_booked_amt_dm"]
  py_booked_amt_sv = pf_amts["py_booked_amt_sv"]
  cy_booked_amt_dm = pf_amts["cy_booked_amt_dm"]
  cy_booked_amt_sv = pf_amts["cy_booked_amt_sv"]
  reserve_amt_dm = pf_amts["reserve_amt_dm"]
  reserve_amt_sv = pf_amts["reserve_amt_sv"]

  # perform calculations
  py_booked_amt = py_booked_amt_dm + py_booked_amt_sv
  cy_booked_amt = cy_booked_amt_dm + cy_booked_amt_sv
  reserve_amt = reserve_amt_dm + reserve_amt_sv
  total_booked_amt = py_booked_amt + cy_booked_amt

  return total_booked_amt, reserve_amt, cy_booked_amt, py_booked_amt

gen_output = 0

In [5]:
# function to format the amount
def format_amt(number):
    abs_number = abs(number)

    if abs_number >= 1_00_00_000:  # Crores
        formatted_amt = f"{number / 1_00_00_000:.2f} C"
    elif abs_number >= 1_00_000:  # Lakhs
        formatted_amt = f"{number / 1_00_000:.2f} L"
    elif abs_number >= 1_000:  # Thousands
        formatted_amt = f"{number / 1_000:.2f} K"
    else:
        formatted_amt = f"{number:.2f}"

    return formatted_amt

# function to set start and end date
def get_start_end_date():
  start_date = (datetime.date.today() + datetime.timedelta(days=-365)).strftime('%Y-%m-%d')
  end_date = (datetime.date.today() + datetime.timedelta(days=1)).strftime('%Y-%m-%d')
  return start_date, end_date

# function to fetch my portfolio csv
def get_mypfs_df():
  mypfs_df = pd.read_csv('https://raw.githubusercontent.com/ankit-rathi/Tradevesting_v1/main/data/myPortfolioStocks.csv')
  return mypfs_df

# function to fetch my prospects csv
def get_mypps_df():
  mypps_df = pd.read_csv('https://raw.githubusercontent.com/ankit-rathi/Tradevesting_v1/main/data/myProspectsScrips.csv')
  return mypps_df

# function to fetch screener data
def get_myscreen_df():
  myscreen_df = pd.read_csv('https://raw.githubusercontent.com/ankit-rathi/Tradevesting_v1/main/data/myScreenerDB.csv')
  return myscreen_df

# function to fetch momentum data
def get_myinvmt_df():
  myinvmt_df = pd.read_csv('https://raw.githubusercontent.com/ankit-rathi/Tradevesting_v1/main/data/myInvestments.csv')
  return myinvmt_df

# function to get the stock ids
def get_stock_ids(df_pf):
  stock_n100 = df_pf['Symbol'].unique()

  exclude = ['CADILAHC','MMTC', 'MASFIN']

  stock_ids = df_pf[~df_pf['Symbol'].isin(exclude) ]['Symbol'].unique()

  #mypf = mypf[mypf.Forecast.notnull()]
  #stock_ids = mypf['Symbol'].unique()

  #stock_ids.sort()
  return stock_ids

# get features from screener data
def get_screener_features():
  myscreen_df = get_myscreen_df()
  cols = ['Symbol', 'EPS', 'MedPE', 'ROCE%', 'ROE%', 'CapType']
  return myscreen_df[cols]

# get relative strength
def get_relative_strength(stock_list):

    # Dictionary to store stock tickers and their corresponding percentage price change
    stock_changes = {}

    # Loop through each stock and fetch its price data
    for stock in stock_list:
        try:
            # Download the stock data for the given date range
            stock_data = yfin.Ticker(stock + '.NS').history(period='1mo', interval='1d')[map(str.title, ['open', 'close', 'low', 'high', 'volume'])]

            # Calculate the percentage change for the stock
            if len(stock_data) > 0:
                start_price = stock_data['Close'].iloc[0]
                end_price = stock_data['Close'].iloc[-1]
                percent_change = round(((end_price - start_price) / start_price) * 100, 2)
                stock_changes[stock] = percent_change
            else:
                stock_changes[stock] = np.nan  # If no data is available, set to NaN

        except Exception as e:
            print(f"Error fetching data for {stock}: {e}")
            stock_changes[stock] = np.nan

    # Create a DataFrame with stock tickers and their percentage changes
    df = pd.DataFrame(list(stock_changes.items()), columns=['Symbol', 'Percent_Change'])

    # Drop any stocks with missing data (NaN values)
    df = df.dropna()

    # Calculate the percentile rank based on percentage change
    df['RSP'] = round(df['Percent_Change'].rank(pct=True) * 100, 2)
    cols = ['Symbol', 'RSP']
    df = df[cols]
    # Sort by percentile rank (optional)
    df = df.sort_values(by='RSP', ascending=False).reset_index(drop=True)

    return df

In [6]:
# function to get stock technicals
def stock_prec_dev(stock_symbol):
    #stock_symbol = 'ULTRACEMCO.NS'
    short_window = 20
    mid_window = 50
    long_window = 200
    moving_avg = 'SMA'

    start = datetime.datetime(*map(int, start_date.split('-')))
    end = datetime.datetime(*map(int, end_date.split('-')))

    stock_df = yfin.Ticker(stock_symbol + '.NS').history(period='max', interval='1d')[map(str.title, ['open', 'close', 'low', 'high', 'volume'])]

    stock_df['Max'] = round(max(stock_df['Close']),2)
    stock_df = stock_df[(stock_df.index <= end_date) & (stock_df.index >= start_date)]
    stock_df['200_SMA'] = round(stock_df['Close'].rolling(window = 200, min_periods = 1).mean(),0)
    stock_df['Dev%_200'] = round((stock_df['Close'] - stock_df['200_SMA'])*100/stock_df['200_SMA'],2)
    stock_df.dropna(axis = 0, inplace = True) # remove any null rows

    stock_df['20_SMA'] = stock_df['Close'].rolling(window=20).mean()
    stock_df['50_SMA'] = stock_df['Close'].rolling(window=50).mean()
    stock_df['Symbol'] = stock_symbol

    stock_df['Close'] = round(stock_df['Close'],2)
    stock_df['Min'] = round(min(stock_df['Close']),2)
    stock_df['RSI_14'] = ta.momentum.RSIIndicator(close=stock_df['Close'], window=14).rsi()
    stock_df['RSI_14'] = round(stock_df['RSI_14'],0)
    stock_df['Prev_Close'] = stock_df['Close'].shift(1)
    stock_df.drop(['Open', 'Low', 'High', 'Volume'], axis=1, inplace=True)
    stock_df = stock_df.tail(1)

    max_SMA = max(stock_df['20_SMA'].item(), stock_df['50_SMA'].item(), stock_df['200_SMA'].item())
    min_SMA = min(stock_df['20_SMA'].item(), stock_df['50_SMA'].item(), stock_df['200_SMA'].item())
    ABS_Spread = max_SMA - min_SMA
    stock_df['Spread%'] = round((ABS_Spread / stock_df['200_SMA'].item()) * 100,2)

    return stock_df

# function to compute stock attributes
def get_common_features(stock_ids, df_mypf):

  df_prec_dev = pd.DataFrame()
  df_tmp = get_screener_features()
  df_rs = get_relative_strength(stock_ids)

  for stock_id in stock_ids:
      tmp = stock_prec_dev(stock_id)
      tmp = tmp.reset_index()
      df_prec_dev = pd.concat([df_prec_dev, tmp], ignore_index = True)
  df_prec_dev = pd.merge(df_prec_dev, df_mypf, on= 'Symbol')
  df_prec_dev = pd.merge(df_prec_dev, df_tmp, on= 'Symbol', how='left')
  df_prec_dev = pd.merge(df_prec_dev, df_rs, on= 'Symbol', how='left')
  #print(df_prec_dev.columns)
  df_prec_dev['Curr_PE'] = round(df_prec_dev['Close']/df_prec_dev['EPS'],1)
  df_prec_dev['Dev%_PE'] = round((df_prec_dev['Curr_PE'] - df_prec_dev['MedPE'])*100/df_prec_dev['MedPE'],2)
  df_prec_dev['Conviction'] = df_prec_dev['Conviction'] + '-' + df_prec_dev['CapType']
  return df_prec_dev

# function to arrange stock features
def arrange_features(df_stocks, common_cols, diff_cols):
  df_stocks_common = df_stocks[common_cols].drop_duplicates()
  df_stocks_diff = df_stocks[diff_cols]
  df_stocks_diff['Investment'] = df_stocks_diff['AvgCost'] * df_stocks_diff['Shares']
  df_stocks_diff = df_stocks_diff.groupby(['Symbol'])[['Shares', 'Investment']].aggregate(['sum']).reset_index()
  df_stocks_diff.columns = ['Symbol', 'Shares', 'Investment']
  df_stocks_diff['AvgCost'] = round(df_stocks_diff['Investment']/df_stocks_diff['Shares'],2)
  df_stocks = pd.merge(df_stocks_diff, df_stocks_common, on='Symbol')
  return df_stocks

# plot fact distribution across dimension
def plot_pie_chart(df, dimension, fact):
  # grouping the data by category and calculating the sum of fact for each type
  grouped_data = df.groupby(dimension)[fact].sum()

  # sorting the grouped data in descending order
  grouped_data = grouped_data.sort_values(ascending=False)

  # creating a pie chart
  grouped_data.plot.pie(autopct='%1.1f%%', startangle=90, figsize=(6, 6))

  # adding a title and displaying the plot
  plt.title(f'{dimension} {fact} Distribution')
  plt.ylabel('')  # To hide the y-label
  plt.show()

In [7]:
# function to get portfolio features

def get_portfolio_features(df_common_features):

  print_date_time()
  print('-------------------')

  #df_common_features["Target"] = df_common_features["Target"].fillna(df_common_features["Max"])
  df_common_features['NTT'] = np.where(df_common_features['Strategy']== 'NTT', df_common_features["Target"], df_common_features['Max'])
  df_common_features['LTT'] = np.where(df_common_features['Strategy']== 'BTT', df_common_features["Target"], df_common_features['Max'])
  df_common_features['BOL'] = df_common_features['Min']

  tmp_df = df_common_features[df_common_features['Symbol'].isin(mypf_df[mypf_df['InPortfolio'] != 'NA'].Symbol.values)]
  print('qualified stocks: '+str(len(tmp_df['Symbol'].unique())))
  tmp_df1 = tmp_df[tmp_df['LatestQtr'] == 1]
  print('with latest results: '+str(len(tmp_df1['Symbol'].unique())))
  tmp_df1 = tmp_df1[tmp_df1['StarStock'] == 1]
  print('still star stocks: '+str(len(tmp_df1['Symbol'].unique())))
  tmp_df['Investment'] = tmp_df['AvgCost'] * tmp_df['Shares']
  tmp_df['Current'] = round(tmp_df['Close'] * tmp_df['Shares'],0)
  tmp_df['Previous'] = tmp_df['Prev_Close'] * tmp_df['Shares']
  tmp_df['EstimatedST'] = tmp_df['NTT'] * tmp_df['Shares']
  tmp_df['EstimatedLT'] = tmp_df['LTT'] * tmp_df['Shares']
  tmp_df['Current P/L'] = round((tmp_df['Current'] - tmp_df['Investment']),0)
  tmp_df['Today P/L%'] = round((tmp_df['Current'] - tmp_df['Previous'])*100/tmp_df['Previous'],2)
  tmp_df['Current P/L%'] = round((tmp_df['Current'] - tmp_df['Investment'])*100/tmp_df['Investment'],2)
  tmp_df['EstimatedST P/L%'] = round((tmp_df['EstimatedST'] - tmp_df['Investment'])*100/tmp_df['Investment'],2)
  tmp_df['EstimatedLT P/L%'] = round((tmp_df['EstimatedLT'] - tmp_df['Investment'])*100/tmp_df['Investment'],2)
  tmp_df['NTT%'] = round((tmp_df['NTT'] - tmp_df['Close'])*100/tmp_df['Close'],2)
  tmp_df['LTT%'] = round((tmp_df['LTT'] - tmp_df['Close'])*100/tmp_df['Close'],2)
  tmp_df['Gained%'] = round((tmp_df['Close'] - tmp_df['BOL'])*100/tmp_df['BOL'],2)
  investment = round(sum(tmp_df['AvgCost']*tmp_df['Shares']),0)
  current = round(sum(tmp_df['Close']*tmp_df['Shares']),0)
  tmp_df['InitAlloc%'] = round(tmp_df['Investment']*100/investment,2)
  tmp_df['CurrAlloc%'] = round(tmp_df['Current']*100/current,2)
  tmp_df['FTT'] = tmp_df['LTT']
  tmp_df.loc[tmp_df['Strategy'] == 'NTT', 'FTT'] = tmp_df['NTT']
  tmp_df['FTT%'] = tmp_df['LTT%']
  tmp_df.loc[tmp_df['Strategy'] == 'NTT', 'FTT%'] = tmp_df['NTT%']
  tmp_df['FTT Amt'] = round(tmp_df['FTT%'] * tmp_df['Current']/100,0)
  tmp_df['OTT%'] = round((tmp_df['FTT'] - tmp_df['AvgCost'])*100/tmp_df['AvgCost'],2)
  tmp_df['RRR Ind'] = round(tmp_df['Current P/L']/tmp_df['FTT Amt'],2)
  tmp_df['Risk Ind'] = round(tmp_df['Current P/L%']*tmp_df['CurrAlloc%'],0)

  return tmp_df

# function to print portfolio features
def print_portfolio_stats(df_portfolio_features, myinvmt_df):
  from pyxirr import xirr

  total_booked_amt, reserve_amt, cy_booked_amt, py_booked_amt = get_amt()

  dates = myinvmt_df['Date'].values
  dates = np.append(dates, datetime.date.today().strftime('%d-%b-%y'))
  investment = myinvmt_df['Investment'].values
  dates= pd.to_datetime(dates)

  current = round(sum(df_portfolio_features['Close']*df_portfolio_features['Shares']),0) + reserve_amt
  investment_xirr = np.append(investment, current)
  cagr = round(xirr(pd.DataFrame({"dates": dates, "amounts": investment_xirr}))*100,2)

  investment = -sum(investment)
  invested = round(sum(df_portfolio_features['AvgCost']*df_portfolio_features['Shares']),0) + reserve_amt
  previous = round(sum(df_portfolio_features['Prev_Close']*df_portfolio_features['Shares']),0) + reserve_amt
  cy_invested = investment + py_booked_amt

  today_pnl_amount = current-previous
  today_pnl_percentage = round((current-previous)*100/previous,2)

  curr_pnl_amount = current-invested
  curr_pnl_percentage = round((curr_pnl_amount)*100/(cy_invested),2)

  cy_pnl_amount = cy_booked_amt + curr_pnl_amount
  cy_pnl_percentage = round((cy_pnl_amount)*100/cy_invested,2)

  overall_pnl_amount = total_booked_amt + curr_pnl_amount
  overall_pnl_percentage = round((overall_pnl_amount)*100/investment,2)

  estimate_st = round(sum(df_portfolio_features['FTT']*df_portfolio_features['Shares']),0)  + reserve_amt
  est_st_pnl_amount = estimate_st-current
  est_st_pnl_percentage = round((est_st_pnl_amount)*100/current,2)

  estimate_lt = round(sum(df_portfolio_features['LTT']*df_portfolio_features['Shares']),0)  + reserve_amt
  est_lt_pnl_amount = estimate_lt-current
  est_lt_pnl_percentage = round((est_lt_pnl_amount)*100/current,2)

  total_profit = round(sum(df_portfolio_features[df_portfolio_features['Current P/L%'] > 0]['Current']) - sum(df_portfolio_features[df_portfolio_features['Current P/L%'] > 0]['Investment']),0)
  total_loss = round(sum(df_portfolio_features[df_portfolio_features['Current P/L%'] < 0]['Current']) - sum(df_portfolio_features[df_portfolio_features['Current P/L%'] < 0]['Investment']),0)

  cy_booked_percentage = round((cy_booked_amt)*100/current,2)
  py_booked_percentage = round((py_booked_amt)*100/investment,2)
  total_booked_percentage = round((total_booked_amt)*100/investment,2)

  print('-------------------')
  print('Initial Investment: ', format_amt(investment))
  print('CY Investment: ', format_amt(cy_invested))
  print('Reserve: ', format_amt(reserve_amt))
  print('Current: ',  format_amt(current))
  print('-------------------')
  print('Today PnL: '+ '{} ({}%)'.format(format_amt(today_pnl_amount), today_pnl_percentage))
  print('Current PnL: '+ '{} ({}%)'.format(format_amt(curr_pnl_amount), curr_pnl_percentage))
  print('CY Booked + Current PnL: '+ '{} ({}%)'.format(format_amt(cy_pnl_amount), cy_pnl_percentage))
  print('-------------------')
  print('Total profit: ', format_amt(total_profit))
  print('Total loss: ', format_amt(total_loss))
  print('-------------------')
  print('Total Booked + Current PnL: '+ '{} ({}%)'.format(format_amt(overall_pnl_amount), overall_pnl_percentage))
  print('Total Booked PnL: '+ '{} ({}%)'.format(format_amt(total_booked_amt), total_booked_percentage))
  print('Curr Year Booked PnL: '+ '{} ({}%)'.format(format_amt(cy_booked_amt), cy_booked_percentage))
  print('Prev Year Booked PnL: '+ '{} ({}%)'.format(format_amt(py_booked_amt), py_booked_percentage))
  print('===================')
  print('Est FTT: ',  format_amt(estimate_st))
  print('Est FTT PnL: '+ '{} ({}%)'.format(format_amt(est_st_pnl_amount), est_st_pnl_percentage))

  print('===================')
  print('Deployed: ', format_amt(investment))

  print('Current: ', format_amt(current))

  print('CAGR/XIRR %: '+'{}%'.format(cagr))

In [8]:
# get start and end date
start_date, end_date = get_start_end_date()

# get portfolio and prospects data
mypfs_df = get_mypfs_df()
mypps_df = get_mypps_df()
myinvmt_df = get_myinvmt_df()

# merge above datasets
mypf_df = pd.merge(mypfs_df, mypps_df, on="Symbol")

# seggregate dm and sv portfolio
dm_pf = mypf_df[mypf_df['InPortfolio'] == 'DM']
sv_pf = mypf_df[mypf_df['InPortfolio'] == 'SV']

# build portfolio stock dataframe
dm_stocks = get_stock_ids(dm_pf)
sv_stocks = get_stock_ids(sv_pf)
df_stocks = pd.concat([dm_pf,sv_pf], ignore_index = True)

# arrange common and diff stock features
common_cols = ['Symbol', 'Target', 'Criteria', 'Strategy', 'CumlRnk', 'LatestQtr', 'StarStock', 'Conviction', 'Category', 'InFolio', 'XIRR', 'MBQ']
diff_cols = ['Symbol', 'AvgCost', 'Shares']
df_stocks = arrange_features(df_stocks, common_cols, diff_cols)

# get common features
stock_ids = df_stocks['Symbol'].values
df_common_features = get_common_features(stock_ids, df_stocks)

df_common_features.reset_index(drop=True, inplace=True)
df_common_features.drop(['Date'], axis=1, inplace=True)
# get and print portfolio features
df_portfolio_features = get_portfolio_features(df_common_features)

print_portfolio_stats(df_portfolio_features, myinvmt_df)

df = df_portfolio_features
#plot_pie_chart(df, 'CapType', 'Current')
list_ox40n = list(df[df['MBQ'].str.contains('OX40N', na=False)]['Symbol'].values)

Run date time (IST): 2026-08-11 14:46:32
-------------------
qualified stocks: 88
with latest results: 30
still star stocks: 19
-------------------
Initial Investment:  1.46 C
CY Investment:  1.89 C
Reserve:  2.24 L
Current:  1.61 C
-------------------
Today PnL: -15.87 K (-0.1%)
Current PnL: -30.82 L (-16.31%)
CY Booked + Current PnL: -26.60 L (-14.08%)
-------------------
Total profit:  4.17 L
Total loss:  -34.99 L
-------------------
Total Booked + Current PnL: 16.27 L (11.14%)
Total Booked PnL: 47.09 L (32.24%)
Curr Year Booked PnL: 4.22 L (2.62%)
Prev Year Booked PnL: 42.87 L (29.35%)
===================
Est FTT:  2.67 C
Est FTT PnL: 1.05 C (65.36%)
===================
Deployed:  1.46 C
Current:  1.61 C
CAGR/XIRR %: 4.55%

In [9]:
# top 5 near their targets
cols = ['Symbol', 'Today P/L%', 'Current P/L%', 'FTT%', 'OTT%', 'FTT Amt', 'Current P/L', 'Current', 'FTT', 'Dev%_PE', 'RSI_14','Conviction', 'Spread%',  'CumlRnk', 'RRR Ind', 'CurrAlloc%', 'Gained%', 'Criteria', 'Strategy', 'Category']
df_tmp = df_portfolio_features[~df_portfolio_features['Symbol'].isin(['ENRIN','BLUSPRING','DIGITIDE'])]
df_tmp = df_tmp.sort_values(by = 'FTT Amt', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
55,MEDANTA,-3.52,21.83,4.34,27.12,9333.0,38537.0,215054.0,1486.00,18.10,58.0,X-SC,15.97,87.0,4.13,1.35,48.18,XY24,NTT,HEALTHCARE
80,UNITDSPR,0.62,12.50,7.35,20.77,19361.0,29274.0,263418.0,1644.00,-0.15,72.0,X-MC,8.06,64.0,1.51,1.66,26.62,X40N,NTT,BREWERIES
87,ZYDUSLIFE,7.01,26.27,7.32,35.51,19371.0,55051.0,264625.0,1285.01,9.91,70.0,H-MC,15.78,120.0,2.84,1.66,39.26,AR,ATH,PHARMA
52,M&M,-1.36,9.54,8.47,18.82,22331.0,22963.0,263644.0,3762.88,-4.70,65.0,X-LC,5.04,25.0,1.03,1.66,19.59,X40N,ATH,AUTO
69,SIS,2.26,0.36,20.82,21.26,23201.0,403.0,111435.0,528.00,2661.14,56.0,H-SC,22.59,168.0,0.02,0.70,65.69,OX40N,NTT,MISC

In [10]:
# top 5 today
df_tmp = df_portfolio_features.sort_values(by = 'Today P/L%', ascending=False)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
25,FINCABLES,13.24,51.75,37.01,107.91,82919.0,76401.0,224045.0,1641.55,36.48,72.0,M-SC,17.48,220.0,0.92,1.41,68.56,OX40N,ATH,CABLES
87,ZYDUSLIFE,7.01,26.27,7.32,35.51,19371.0,55051.0,264625.0,1285.01,9.91,70.0,H-MC,15.78,120.0,2.84,1.66,39.26,AR,ATH,PHARMA
82,VALIANTORG,3.58,-35.91,171.73,74.15,180069.0,-58749.0,104856.0,838.00,-288.40,69.0,H-SC,4.07,145.0,-0.33,0.66,56.04,XR,NTT,CHEMICALS
68,SIEMENS,2.53,7.83,15.83,24.90,31767.0,14580.0,200675.0,4648.66,68.58,71.0,H-LC,11.55,51.0,0.46,1.26,41.59,AR,ATH,ELECTRICAL
69,SIS,2.26,0.36,20.82,21.26,23201.0,403.0,111435.0,528.00,2661.14,56.0,H-SC,22.59,168.0,0.02,0.70,65.69,OX40N,NTT,MISC

In [11]:
# bottom 5 today
df_tmp = df_portfolio_features.sort_values(by = 'Today P/L%', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
55,MEDANTA,-3.52,21.83,4.34,27.12,9333.0,38537.0,215054.0,1486.0,18.10,58.0,X-SC,15.97,87.0,4.13,1.35,48.18,XY24,NTT,HEALTHCARE
29,GREENPANEL,-3.42,-51.07,192.55,43.14,172481.0,-93501.0,89577.0,537.0,100.90,38.0,M-SC,10.34,225.0,-0.54,0.56,7.88,XY24,NTT,MISC
5,ATULAUTO,-2.66,-14.52,70.30,45.57,118458.0,-28628.0,168504.0,844.0,3651.35,46.0,M-SC,9.78,248.0,-0.24,1.06,29.67,XY24,NTT,AUTO
18,COFFEEDAY,-2.32,-48.68,163.59,35.27,95327.0,-55277.0,58272.0,80.0,-59.76,41.0,L-SC,4.54,266.0,-0.58,0.37,43.70,XR,NTT,HOTELS
79,TTKPRESTIG,-2.15,-22.97,29.94,0.09,23243.0,-23146.0,77631.0,770.0,80.15,39.0,M-SC,12.79,250.0,-1.00,0.49,39.72,OX40N,NTT,DURABLES

In [12]:
# top 5 to exit based on CumlRnk
df_tmp = df_portfolio_features[~df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])]
df_tmp = df_tmp[(df_tmp['Current P/L%'] > -1) & (df_tmp['Current P/L%'] < 1)].sort_values(by = 'CumlRnk', ascending=False)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
69,SIS,2.26,0.36,20.82,21.26,23201.0,403.0,111435.0,528.0,2661.14,56.0,H-SC,22.59,168.0,0.02,0.7,65.69,OX40N,NTT,MISC

In [13]:
# OX40N stocks to exit
df_tmp = df_portfolio_features[(df_portfolio_features['Symbol'].isin(list_ox40n))].sort_values(by = 'Current P/L%', ascending=False)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
25,FINCABLES,13.24,51.75,37.01,107.91,82919.0,76401.0,224045.0,1641.55,36.48,72.0,M-SC,17.48,220.0,0.92,1.41,68.56,OX40N,ATH,CABLES
69,SIS,2.26,0.36,20.82,21.26,23201.0,403.0,111435.0,528.00,2661.14,56.0,H-SC,22.59,168.0,0.02,0.70,65.69,OX40N,NTT,MISC
43,INDIGOPNTS,-1.18,-19.89,24.86,0.02,34763.0,-34724.0,139835.0,1408.00,113.17,63.0,M-SC,5.44,222.0,-1.00,0.88,58.65,OX40N,NTT,PAINTS
16,CERA,-0.50,-21.50,57.82,23.89,79838.0,-37823.0,138080.0,9475.00,-24.34,42.0,H-SC,12.57,153.0,-0.47,0.87,34.23,OX40N,NTT,CERAMICS
79,TTKPRESTIG,-2.15,-22.97,29.94,0.09,23243.0,-23146.0,77631.0,770.00,80.15,39.0,M-SC,12.79,250.0,-1.00,0.49,39.72,OX40N,NTT,DURABLES

In [14]:
# top 5 to book for rotation
df_tmp = df_portfolio_features[(df_portfolio_features['Current P/L%'] > 20) ].sort_values(by = 'CumlRnk', ascending=False)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
25,FINCABLES,13.24,51.75,37.01,107.91,82919.0,76401.0,224045.0,1641.55,36.48,72.0,M-SC,17.48,220.0,0.92,1.41,68.56,OX40N,ATH,CABLES
87,ZYDUSLIFE,7.01,26.27,7.32,35.51,19371.0,55051.0,264625.0,1285.01,9.91,70.0,H-MC,15.78,120.0,2.84,1.66,39.26,AR,ATH,PHARMA
55,MEDANTA,-3.52,21.83,4.34,27.12,9333.0,38537.0,215054.0,1486.00,18.10,58.0,X-SC,15.97,87.0,4.13,1.35,48.18,XY24,NTT,HEALTHCARE
58,QUESS,0.12,32.95,30.80,73.90,43729.0,35185.0,141978.0,424.00,-28.37,65.0,X-SC,40.30,80.0,0.80,0.89,95.41,XY24,NTT,MISC

In [15]:
# top 5 to monitor for exit
df_tmp = df_portfolio_features[~df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])]
df_tmp = df_tmp[(df_tmp['Current P/L%'] > 0) ].sort_values(by = 'Dev%_PE', ascending=False)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
69,SIS,2.26,0.36,20.82,21.26,23201.0,403.0,111435.0,528.00,2661.14,56.0,H-SC,22.59,168.0,0.02,0.70,65.69,OX40N,NTT,MISC
70,STARHEALTH,1.74,13.19,30.10,47.26,95782.0,37090.0,318213.0,761.00,78.72,51.0,H-SC,17.00,173.0,0.39,2.00,37.59,XY24,NTT,INSURANCE
25,FINCABLES,13.24,51.75,37.01,107.91,82919.0,76401.0,224045.0,1641.55,36.48,72.0,M-SC,17.48,220.0,0.92,1.41,68.56,OX40N,ATH,CABLES
87,ZYDUSLIFE,7.01,26.27,7.32,35.51,19371.0,55051.0,264625.0,1285.01,9.91,70.0,H-MC,15.78,120.0,2.84,1.66,39.26,AR,ATH,PHARMA

In [16]:
# top 5 to book for rotation from weak conviction
df_tmp = df_portfolio_features[~df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])]
df_tmp = df_tmp[~df_tmp['Criteria'].isin(['XY25','XY24','X40', 'X40N'])].sort_values(by = 'RRR Ind', ascending=False)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
87,ZYDUSLIFE,7.01,26.27,7.32,35.51,19371.0,55051.0,264625.0,1285.01,9.91,70.0,H-MC,15.78,120.0,2.84,1.66,39.26,AR,ATH,PHARMA
25,FINCABLES,13.24,51.75,37.01,107.91,82919.0,76401.0,224045.0,1641.55,36.48,72.0,M-SC,17.48,220.0,0.92,1.41,68.56,OX40N,ATH,CABLES
69,SIS,2.26,0.36,20.82,21.26,23201.0,403.0,111435.0,528.00,2661.14,56.0,H-SC,22.59,168.0,0.02,0.70,65.69,OX40N,NTT,MISC
3,ALKYLAMINE,1.77,-16.94,131.80,92.54,110531.0,-17100.0,83863.0,4520.85,-11.07,62.0,H-SC,13.71,142.0,-0.15,0.53,59.25,SR,ATH,CHEMICALS
42,INDIAMART,-0.03,-23.42,162.36,100.92,153351.0,-28885.0,94451.0,4675.60,-65.43,41.0,H-SC,12.48,140.0,-0.19,0.59,2.24,AR,ATH,MISC

In [17]:
# top 5 to accumulate based on lowest RSI_14
df_tmp = df_portfolio_features[df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])].sort_values(by = 'RSI_14', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
34,HDFCBANK,-0.29,-10.98,47.21,31.05,123193.0,-32174.0,260946.0,1073.00,-25.96,34.0,X-LC,11.35,26.0,-0.26,1.64,1.29,X40,BTT,BANKS
57,PGHH,-0.10,-36.50,107.91,32.01,146300.0,-77944.0,135576.0,17616.87,-57.06,35.0,X-MC,19.23,57.0,-0.53,0.85,0.00,X40,ATH,FMCG
56,PAGEIND,-0.61,0.22,33.29,33.59,89542.0,596.0,268975.0,51217.29,-28.15,38.0,X-MC,8.80,55.0,0.01,1.69,27.74,X40,ATH,APPARELS
35,HDFCLIFE,-0.66,-8.00,51.26,39.15,118243.0,-20063.0,230674.0,811.41,-31.47,38.0,X-LC,16.11,31.0,-0.17,1.45,0.09,X40,ATH,INSURANCE
83,VBL,-1.57,-11.14,52.66,35.66,164641.0,-39194.0,312650.0,669.42,-21.86,38.0,X-LC,7.57,13.0,-0.24,1.97,15.11,X40N,ATH,FMCG

In [18]:
# top 5 to accumulate based on Spread and CumlRnk
df_tmp = df_portfolio_features[df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])]
df_tmp = df_tmp[(df_tmp['CumlRnk'] < 100)].sort_values(by = 'Spread%', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
19,COLPAL,-0.82,-23.95,83.90,39.86,168043.0,-63075.0,200290.0,3683.41,-7.87,42.0,X-MC,1.57,62.0,-0.38,1.26,13.30,XY25,ATH,FMCG
11,BERGEPAINT,-1.14,-1.24,26.89,25.32,68449.0,-3197.0,254552.0,680.00,-6.58,60.0,X-MC,2.25,68.0,-0.05,1.60,33.48,XY24,NTT,PAINTS
8,BAJAJHLDNG,0.40,3.47,23.94,28.24,63415.0,8886.0,264891.0,14274.15,-4.76,66.0,X-LC,2.82,28.0,0.14,1.67,33.32,X40,ATH,FINANCE
23,DMART,-0.12,-1.30,33.15,31.42,102015.0,-4051.0,307739.0,5391.45,-17.91,53.0,X-LC,3.06,14.0,-0.04,1.93,11.05,X40N,ATH,FMCG
26,GILLETTE,-0.48,-10.02,44.17,29.72,100906.0,-25446.0,228450.0,10978.86,-30.84,42.0,X-SC,3.31,83.0,-0.25,1.44,4.98,X40,ATH,FMCG

In [19]:
# top 5 to accumulate based on lowest Gained%
df_tmp = df_portfolio_features[df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])].sort_values(by = 'Gained%', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
57,PGHH,-0.10,-36.50,107.91,32.01,146300.0,-77944.0,135576.0,17616.87,-57.06,35.0,X-MC,19.23,57.0,-0.53,0.85,0.00,X40,ATH,FMCG
35,HDFCLIFE,-0.66,-8.00,51.26,39.15,118243.0,-20063.0,230674.0,811.41,-31.47,38.0,X-LC,16.11,31.0,-0.17,1.45,0.09,X40,ATH,INSURANCE
47,ITC,-1.29,-23.03,62.01,24.70,189617.0,-91494.0,305784.0,452.00,-59.56,40.0,X-LC,10.92,1.0,-0.48,1.92,1.25,X40,NTT,FMCG
34,HDFCBANK,-0.29,-10.98,47.21,31.05,123193.0,-32174.0,260946.0,1073.00,-25.96,34.0,X-LC,11.35,26.0,-0.26,1.64,1.29,X40,BTT,BANKS
20,DABUR,-0.59,-19.50,78.51,43.70,156784.0,-48369.0,199699.0,735.00,-26.86,40.0,X-MC,9.25,70.0,-0.31,1.26,1.62,XY24,BTT,FMCG

In [20]:
# top 5 to accumulate based on lowest CurrAlloc%
df_tmp = df_portfolio_features[df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])].sort_values(by = 'CurrAlloc%', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
10,BATAINDIA,-1.94,-54.91,199.86,35.20,115953.0,-70653.0,58017.0,2096.00,-23.90,51.0,X-SC,13.64,91.0,-0.61,0.36,16.56,X40,NTT,FOOTWEAR
62,RELAXO,-0.47,-45.29,178.38,52.31,141671.0,-65739.0,79421.0,1176.00,-41.73,59.0,X-SC,12.09,92.0,-0.46,0.50,77.57,X40N,NTT,FOOTWEAR
57,PGHH,-0.10,-36.50,107.91,32.01,146300.0,-77944.0,135576.0,17616.87,-57.06,35.0,X-MC,19.23,57.0,-0.53,0.85,0.00,X40,ATH,FMCG
58,QUESS,0.12,32.95,30.80,73.90,43729.0,35185.0,141978.0,424.00,-28.37,65.0,X-SC,40.30,80.0,0.80,0.89,95.41,XY24,NTT,MISC
2,ACC,-1.10,-39.91,190.93,74.81,307611.0,-107016.0,161112.0,3906.00,-57.46,45.0,X-SC,12.10,85.0,-0.35,1.01,7.63,XY24,BTT,CEMENT

In [21]:
# top 5 to accumulate based on CumlRnk
df_tmp = df_portfolio_features.sort_values(by = 'CumlRnk', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
47,ITC,-1.29,-23.03,62.01,24.70,189617.0,-91494.0,305784.0,452.00,-59.56,40.0,X-LC,10.92,1.0,-0.48,1.92,1.25,X40,NTT,FMCG
75,TCS,0.52,-28.42,73.52,24.20,243789.0,-131678.0,331595.0,4230.71,-39.36,61.0,X-LC,15.43,2.0,-0.54,2.08,23.65,X40,ATH,IT
45,INFY,0.36,-15.49,66.11,40.38,210342.0,-58300.0,318170.0,1972.00,-36.50,64.0,X-LC,16.25,3.0,-0.28,2.00,20.49,X40,NTT,IT
77,TMPV,0.04,-17.38,72.79,42.75,250236.0,-72329.0,343778.0,600.00,-83.62,55.0,X-LC,5.12,4.0,-0.29,2.16,18.21,XY24,NTT,AUTO
33,HCLTECH,0.41,-8.85,36.00,23.97,101556.0,-27386.0,282100.0,1853.42,-6.95,70.0,X-LC,13.07,8.0,-0.27,1.77,33.12,X40,ATH,IT

In [22]:
# top 5 for average up
df_tmp = df_portfolio_features[(df_portfolio_features['Dev%_200'] > 5)].sort_values(by = 'CurrAlloc%', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
44,INDUSINDBK,-1.98,-25.66,78.75,32.89,45202.0,-19808.0,57399.0,1800.00,-370.31,51.0,L-MC,13.88,258.0,-0.44,0.36,41.51,XR,NTT,BANKS
62,RELAXO,-0.47,-45.29,178.38,52.31,141671.0,-65739.0,79421.0,1176.00,-41.73,59.0,X-SC,12.09,92.0,-0.46,0.50,77.57,X40N,NTT,FOOTWEAR
3,ALKYLAMINE,1.77,-16.94,131.80,92.54,110531.0,-17100.0,83863.0,4520.85,-11.07,62.0,H-SC,13.71,142.0,-0.15,0.53,59.25,SR,ATH,CHEMICALS
12,BOSCH-HCIL,-0.47,-25.46,34.15,-0.01,32532.0,-32543.0,95262.0,2282.00,19400.00,84.0,M-SC,3.11,231.0,-1.00,0.60,62.15,OX40N,BTT,AC
82,VALIANTORG,3.58,-35.91,171.73,74.15,180069.0,-58749.0,104856.0,838.00,-288.40,69.0,H-SC,4.07,145.0,-0.33,0.66,56.04,XR,NTT,CHEMICALS

In [23]:
# top 5 RSP
df_tmp = df_portfolio_features.sort_values(by = 'RSP', ascending=False)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
12,BOSCH-HCIL,-0.47,-25.46,34.15,-0.01,32532.0,-32543.0,95262.0,2282.00,19400.00,84.0,M-SC,3.11,231.0,-1.00,0.60,62.15,OX40N,BTT,AC
68,SIEMENS,2.53,7.83,15.83,24.90,31767.0,14580.0,200675.0,4648.66,68.58,71.0,H-LC,11.55,51.0,0.46,1.26,41.59,AR,ATH,ELECTRICAL
33,HCLTECH,0.41,-8.85,36.00,23.97,101556.0,-27386.0,282100.0,1853.42,-6.95,70.0,X-LC,13.07,8.0,-0.27,1.77,33.12,X40,ATH,IT
25,FINCABLES,13.24,51.75,37.01,107.91,82919.0,76401.0,224045.0,1641.55,36.48,72.0,M-SC,17.48,220.0,0.92,1.41,68.56,OX40N,ATH,CABLES
82,VALIANTORG,3.58,-35.91,171.73,74.15,180069.0,-58749.0,104856.0,838.00,-288.40,69.0,H-SC,4.07,145.0,-0.33,0.66,56.04,XR,NTT,CHEMICALS

In [24]:
# Top N allocation
df_tmp = df_portfolio_features.sort_values(by = 'CurrAlloc%', ascending=False)
top_n_values = [10, 25, 50]

sum_df = pd.DataFrame({
    'Top_N': top_n_values,
    'Sum_Alloc%': [df_tmp['CurrAlloc%'].head(n).sum() for n in top_n_values]
})

sum_df

   Top_N  Sum_Alloc%
0     10       19.73
1     25       44.80
2     50       76.86

In [25]:
# market-cap-wise allocation
df_tmp = df_portfolio_features[cols]
df_tmp.groupby(df_tmp['Conviction'].str[-2:])['CurrAlloc%'].sum().sort_values(ascending=False)

Conviction
SC    39.34
LC    37.72
MC    22.93
Name: CurrAlloc%, dtype: float64

In [26]:
# criteria-wise allocation
df_portfolio_features.groupby('Criteria')['CurrAlloc%'].sum().sort_values(ascending=False)

Criteria
X40      26.33
XY24     24.83
X40N     18.48
XR        9.09
XY25      7.16
OX40N     7.07
AR        6.16
SR        0.87
Name: CurrAlloc%, dtype: float64

In [27]:
# conviction-wise allocation
df_portfolio_features.groupby('Conviction')['CurrAlloc%'].sum().sort_values(ascending=False)

Conviction
X-LC    35.66
H-SC    19.33
X-MC    18.67
X-SC     9.86
M-SC     9.64
H-MC     2.72
H-LC     1.26
M-MC     1.18
M-LC     0.80
L-SC     0.51
L-MC     0.36
Name: CurrAlloc%, dtype: float64

In [28]:
# sector-wise stats
df_tmp = df_portfolio_features.groupby('Category')[['CurrAlloc%', 'Current', 'Current P/L', 'FTT Amt']].sum().sort_values(by=['Current', 'Current P/L'], ascending=False)
df_tmp['Current P/L%'] = round(df_tmp['Current P/L'] * 100 / df_tmp['Current'], 2)
df_tmp['FTT%'] = round(df_tmp['FTT Amt'] * 100 / df_tmp['Current'], 2)
cols = ['CurrAlloc%', 'Current P/L%', 'FTT%']
df_tmp[cols].sort_values(by=['CurrAlloc%'], ascending=False)

               CurrAlloc%  Current P/L%    FTT%
Category
FMCG                15.40        -21.78   65.65
IT                  11.23        -33.39   99.59
FINANCE              9.25        -16.28   65.15
AUTO                 8.27         -2.89   39.73
MISC                 6.87        -22.42   74.94
BANKS                6.07        -10.61   58.31
PHARMA               5.71          8.85   17.00
INSURANCE            5.57         -4.84   41.91
PAINTS               5.43        -14.01   33.46
ELECTRICAL           4.13         -7.47   45.11
HEALTHCARE           2.05         -9.46   38.03
AC                   1.80        -11.38   41.58
REFINERIES           1.70        -10.37   47.44
APPARELS             1.69          0.22   33.29
BREWERIES            1.66         11.11    7.35
FOOTWEAR             1.64        -68.70  136.35
DURABLES             1.48        -64.75  104.83
TRAVEL               1.46        -92.39  188.73
CABLES               1.41         34.10   37.01
CERAMICS             1.34        -44.14   87.93
ENGINEERING          1.21        -26.00   83.63
CHEMICALS            1.19        -40.19  153.99
CEMENT               1.01        -66.42  190.93
JEWELLERY            0.98       -105.10  176.36
ENTERTAINMENT        0.68        -79.25  186.15
TEXTILES             0.39        -50.30   93.16
HOTELS               0.37        -94.86  163.59

In [29]:
# money to be made criteria-wise
df_portfolio_features.groupby('Criteria')['FTT Amt'].agg(['sum', 'count']).sort_values(by='sum', ascending=False)

                sum  count
Criteria
XY24      3451252.0     20
X40       2034340.0     18
XR        1353338.0     13
X40N      1144420.0     12
AR        1050298.0      8
OX40N      669416.0     10
XY25       559375.0      5
SR         279278.0      2

In [30]:
# money to be made conviction-wise
df_portfolio_features.groupby('Conviction')['FTT Amt'].agg(['sum', 'count']).sort_values(by='sum', ascending=False)

                  sum  count
Conviction
H-SC        3279290.0     23
X-LC        2387138.0     20
X-MC        1484254.0     14
M-SC        1384530.0     14
X-SC        1233378.0      9
H-MC         264579.0      2
L-SC         210603.0      2
M-LC         164108.0      1
M-MC          56868.0      1
L-MC          45202.0      1
H-LC          31767.0      1

In [31]:
# money to be made criteria and conviction-wise
df_portfolio_features.groupby(['Conviction', 'Criteria'])['FTT Amt'].agg(['sum', 'count']).sort_values(by='sum', ascending=False)

                           sum  count
Conviction Criteria
X-LC       X40       1160092.0      9
H-SC       XY24       984322.0      5
           AR         922378.0      5
M-SC       XY24       854284.0      6
H-SC       XR         799861.0      7
X-SC       XY24       718772.0      4
X-MC       X40        657389.0      7
X-LC       X40N       499852.0      6
           XY24       423433.0      2
X-MC       X40N       346821.0      3
X-SC       X40N       297747.0      3
H-SC       OX40N      293451.0      4
           SR         279278.0      2
M-SC       OX40N      260689.0      5
X-MC       XY25       254811.0      2
X-LC       XY25       247696.0      2
H-MC       XY24       245208.0      1
X-MC       XY24       225233.0      2
X-SC       X40        216859.0      2
M-SC       XR         192775.0      2
M-LC       XR         164108.0      1
L-SC       OX40N      115276.0      1
           XR          95327.0      1
M-SC       AR          76782.0      1
M-MC       XY25        56868.0      1
X-LC       XR          56065.0      1
L-MC       XR          45202.0      1
H-LC       AR          31767.0      1
H-MC       AR          19371.0      1

In [32]:
# notebook execution time

end_time = time.time()
execution_time = round(end_time - start_time, 0)
print(f"Notebook execution time: {execution_time} seconds")

Notebook execution time: 30.0 seconds