<a href="https://colab.research.google.com/github/ankit-rathi/Quantvesting_v2/blob/main/myStocks_Portfolio_Analysis.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
'''
!pip install pandas==2.2.2 -qq
!pip install pyxirr -qq
!pip install ta -qq
!pip install yfinance==0.2.59 -qq
'''

'\n!pip install pandas==2.2.2 -qq\n!pip install pyxirr -qq\n!pip install ta -qq\n!pip install yfinance==0.2.59 -qq\n'

In [2]:
# import libraries

import numpy as np
import pandas as pd
import datetime
import warnings
warnings.filterwarnings('ignore')
import yfinance as yfin
import ta
import matplotlib.pyplot as plt
import requests

In [3]:
# notebook start time
import time
import datetime
import pytz

start_time = time.time()

# function to print date timestamp
def print_date_time():
  tz_NY = pytz.timezone('Asia/Kolkata')
  datetime_NY = datetime.datetime.now(tz_NY)
  print("Run date time (IST):", datetime_NY.strftime("%Y-%m-%d %H:%M:%S"))

In [4]:
# function to get booked and reserved amount
def get_amt():
  # fetch the JSON data from the URL
  url = "https://raw.githubusercontent.com/ankit-rathi/Tradevesting_v1/main/data/myPortfolioAmts.json"
  response = requests.get(url)
  pf_amts = response.json()  # parse the JSON data

  # extract values from the JSON
  py_booked_amt_dm = pf_amts["py_booked_amt_dm"]
  py_booked_amt_sv = pf_amts["py_booked_amt_sv"]
  cy_booked_amt_dm = pf_amts["cy_booked_amt_dm"]
  cy_booked_amt_sv = pf_amts["cy_booked_amt_sv"]
  reserve_amt_dm = pf_amts["reserve_amt_dm"]
  reserve_amt_sv = pf_amts["reserve_amt_sv"]

  # perform calculations
  py_booked_amt = py_booked_amt_dm + py_booked_amt_sv
  cy_booked_amt = cy_booked_amt_dm + cy_booked_amt_sv
  reserve_amt = reserve_amt_dm + reserve_amt_sv
  total_booked_amt = py_booked_amt + cy_booked_amt

  return total_booked_amt, reserve_amt, cy_booked_amt, py_booked_amt

gen_output = 0

In [5]:
# function to format the amount
def format_amt(number):
    abs_number = abs(number)

    if abs_number >= 1_00_00_000:  # Crores
        formatted_amt = f"{number / 1_00_00_000:.2f} C"
    elif abs_number >= 1_00_000:  # Lakhs
        formatted_amt = f"{number / 1_00_000:.2f} L"
    elif abs_number >= 1_000:  # Thousands
        formatted_amt = f"{number / 1_000:.2f} K"
    else:
        formatted_amt = f"{number:.2f}"

    return formatted_amt

# function to set start and end date
def get_start_end_date():
  start_date = (datetime.date.today() + datetime.timedelta(days=-365)).strftime('%Y-%m-%d')
  end_date = (datetime.date.today() + datetime.timedelta(days=1)).strftime('%Y-%m-%d')
  return start_date, end_date

# function to fetch my portfolio csv
def get_mypfs_df():
  mypfs_df = pd.read_csv('https://raw.githubusercontent.com/ankit-rathi/Tradevesting_v1/main/data/myPortfolioStocks.csv')
  return mypfs_df

# function to fetch my prospects csv
def get_mypps_df():
  mypps_df = pd.read_csv('https://raw.githubusercontent.com/ankit-rathi/Tradevesting_v1/main/data/myProspectsScrips.csv')
  return mypps_df

# function to fetch screener data
def get_myscreen_df():
  myscreen_df = pd.read_csv('https://raw.githubusercontent.com/ankit-rathi/Tradevesting_v1/main/data/myScreenerDB.csv')
  return myscreen_df

# function to fetch momentum data
def get_myinvmt_df():
  myinvmt_df = pd.read_csv('https://raw.githubusercontent.com/ankit-rathi/Tradevesting_v1/main/data/myInvestments.csv')
  return myinvmt_df

# function to get the stock ids
def get_stock_ids(df_pf):
  stock_n100 = df_pf['Symbol'].unique()

  exclude = ['CADILAHC','MMTC', 'MASFIN']

  stock_ids = df_pf[~df_pf['Symbol'].isin(exclude) ]['Symbol'].unique()

  #mypf = mypf[mypf.Forecast.notnull()]
  #stock_ids = mypf['Symbol'].unique()

  #stock_ids.sort()
  return stock_ids

# get features from screener data
def get_screener_features():
  myscreen_df = get_myscreen_df()
  cols = ['Symbol', 'EPS', 'MedPE', 'ROCE%', 'ROE%', 'CapType']
  return myscreen_df[cols]

# get relative strength
def get_relative_strength(stock_list):

    # Dictionary to store stock tickers and their corresponding percentage price change
    stock_changes = {}

    # Loop through each stock and fetch its price data
    for stock in stock_list:
        try:
            # Download the stock data for the given date range
            stock_data = yfin.Ticker(stock + '.NS').history(period='1mo', interval='1d')[map(str.title, ['open', 'close', 'low', 'high', 'volume'])]

            # Calculate the percentage change for the stock
            if len(stock_data) > 0:
                start_price = stock_data['Close'].iloc[0]
                end_price = stock_data['Close'].iloc[-1]
                percent_change = round(((end_price - start_price) / start_price) * 100, 2)
                stock_changes[stock] = percent_change
            else:
                stock_changes[stock] = np.nan  # If no data is available, set to NaN

        except Exception as e:
            print(f"Error fetching data for {stock}: {e}")
            stock_changes[stock] = np.nan

    # Create a DataFrame with stock tickers and their percentage changes
    df = pd.DataFrame(list(stock_changes.items()), columns=['Symbol', 'Percent_Change'])

    # Drop any stocks with missing data (NaN values)
    df = df.dropna()

    # Calculate the percentile rank based on percentage change
    df['RSP'] = round(df['Percent_Change'].rank(pct=True) * 100, 2)
    cols = ['Symbol', 'RSP']
    df = df[cols]
    # Sort by percentile rank (optional)
    df = df.sort_values(by='RSP', ascending=False).reset_index(drop=True)

    return df

In [6]:
# function to get stock technicals
def stock_prec_dev(stock_symbol):
    #stock_symbol = 'ULTRACEMCO.NS'
    short_window = 20
    mid_window = 50
    long_window = 200
    moving_avg = 'SMA'

    start = datetime.datetime(*map(int, start_date.split('-')))
    end = datetime.datetime(*map(int, end_date.split('-')))

    stock_df = yfin.Ticker(stock_symbol + '.NS').history(period='max', interval='1d')[map(str.title, ['open', 'close', 'low', 'high', 'volume'])]

    stock_df['Max'] = round(max(stock_df['Close']),2)
    stock_df = stock_df[(stock_df.index <= end_date) & (stock_df.index >= start_date)]
    stock_df['200_SMA'] = round(stock_df['Close'].rolling(window = 200, min_periods = 1).mean(),0)
    stock_df['Dev%_200'] = round((stock_df['Close'] - stock_df['200_SMA'])*100/stock_df['200_SMA'],2)
    stock_df.dropna(axis = 0, inplace = True) # remove any null rows

    stock_df['20_SMA'] = stock_df['Close'].rolling(window=20).mean()
    stock_df['50_SMA'] = stock_df['Close'].rolling(window=50).mean()
    stock_df['Symbol'] = stock_symbol

    stock_df['Close'] = round(stock_df['Close'],2)
    stock_df['Min'] = round(min(stock_df['Close']),2)
    stock_df['RSI_14'] = ta.momentum.RSIIndicator(close=stock_df['Close'], window=14).rsi()
    stock_df['RSI_14'] = round(stock_df['RSI_14'],0)
    stock_df['Prev_Close'] = stock_df['Close'].shift(1)
    stock_df.drop(['Open', 'Low', 'High', 'Volume'], axis=1, inplace=True)
    stock_df = stock_df.tail(1)

    max_SMA = max(stock_df['20_SMA'].item(), stock_df['50_SMA'].item(), stock_df['200_SMA'].item())
    min_SMA = min(stock_df['20_SMA'].item(), stock_df['50_SMA'].item(), stock_df['200_SMA'].item())
    ABS_Spread = max_SMA - min_SMA
    stock_df['Spread%'] = round((ABS_Spread / stock_df['200_SMA'].item()) * 100,2)

    return stock_df

# function to compute stock attributes
def get_common_features(stock_ids, df_mypf):

  df_prec_dev = pd.DataFrame()
  df_tmp = get_screener_features()
  df_rs = get_relative_strength(stock_ids)

  for stock_id in stock_ids:
      tmp = stock_prec_dev(stock_id)
      tmp = tmp.reset_index()
      df_prec_dev = pd.concat([df_prec_dev, tmp], ignore_index = True)
  df_prec_dev = pd.merge(df_prec_dev, df_mypf, on= 'Symbol')
  df_prec_dev = pd.merge(df_prec_dev, df_tmp, on= 'Symbol', how='left')
  df_prec_dev = pd.merge(df_prec_dev, df_rs, on= 'Symbol', how='left')
  #print(df_prec_dev.columns)
  df_prec_dev['Curr_PE'] = round(df_prec_dev['Close']/df_prec_dev['EPS'],1)
  df_prec_dev['Dev%_PE'] = round((df_prec_dev['Curr_PE'] - df_prec_dev['MedPE'])*100/df_prec_dev['MedPE'],2)
  df_prec_dev['Conviction'] = df_prec_dev['Conviction'] + '-' + df_prec_dev['CapType']
  return df_prec_dev

# function to arrange stock features
def arrange_features(df_stocks, common_cols, diff_cols):
  df_stocks_common = df_stocks[common_cols].drop_duplicates()
  df_stocks_diff = df_stocks[diff_cols]
  df_stocks_diff['Investment'] = df_stocks_diff['AvgCost'] * df_stocks_diff['Shares']
  df_stocks_diff = df_stocks_diff.groupby(['Symbol'])[['Shares', 'Investment']].aggregate(['sum']).reset_index()
  df_stocks_diff.columns = ['Symbol', 'Shares', 'Investment']
  df_stocks_diff['AvgCost'] = round(df_stocks_diff['Investment']/df_stocks_diff['Shares'],2)
  df_stocks = pd.merge(df_stocks_diff, df_stocks_common, on='Symbol')
  return df_stocks

# plot fact distribution across dimension
def plot_pie_chart(df, dimension, fact):
  # grouping the data by category and calculating the sum of fact for each type
  grouped_data = df.groupby(dimension)[fact].sum()

  # sorting the grouped data in descending order
  grouped_data = grouped_data.sort_values(ascending=False)

  # creating a pie chart
  grouped_data.plot.pie(autopct='%1.1f%%', startangle=90, figsize=(6, 6))

  # adding a title and displaying the plot
  plt.title(f'{dimension} {fact} Distribution')
  plt.ylabel('')  # To hide the y-label
  plt.show()

In [7]:
# function to get portfolio features

def get_portfolio_features(df_common_features):

  print_date_time()
  print('-------------------')

  #df_common_features["Target"] = df_common_features["Target"].fillna(df_common_features["Max"])
  df_common_features['NTT'] = np.where(df_common_features['Strategy']== 'NTT', df_common_features["Target"], df_common_features['Max'])
  df_common_features['LTT'] = np.where(df_common_features['Strategy']== 'BTT', df_common_features["Target"], df_common_features['Max'])
  df_common_features['BOL'] = df_common_features['Min']

  tmp_df = df_common_features[df_common_features['Symbol'].isin(mypf_df[mypf_df['InPortfolio'] != 'NA'].Symbol.values)]
  print('qualified stocks: '+str(len(tmp_df['Symbol'].unique())))
  tmp_df1 = tmp_df[tmp_df['LatestQtr'] == 1]
  print('with latest results: '+str(len(tmp_df1['Symbol'].unique())))
  tmp_df1 = tmp_df1[tmp_df1['StarStock'] == 1]
  print('still star stocks: '+str(len(tmp_df1['Symbol'].unique())))
  tmp_df['Investment'] = tmp_df['AvgCost'] * tmp_df['Shares']
  tmp_df['Current'] = round(tmp_df['Close'] * tmp_df['Shares'],0)
  tmp_df['Previous'] = tmp_df['Prev_Close'] * tmp_df['Shares']
  tmp_df['EstimatedST'] = tmp_df['NTT'] * tmp_df['Shares']
  tmp_df['EstimatedLT'] = tmp_df['LTT'] * tmp_df['Shares']
  tmp_df['Current P/L'] = round((tmp_df['Current'] - tmp_df['Investment']),0)
  tmp_df['Today P/L%'] = round((tmp_df['Current'] - tmp_df['Previous'])*100/tmp_df['Previous'],2)
  tmp_df['Current P/L%'] = round((tmp_df['Current'] - tmp_df['Investment'])*100/tmp_df['Investment'],2)
  tmp_df['EstimatedST P/L%'] = round((tmp_df['EstimatedST'] - tmp_df['Investment'])*100/tmp_df['Investment'],2)
  tmp_df['EstimatedLT P/L%'] = round((tmp_df['EstimatedLT'] - tmp_df['Investment'])*100/tmp_df['Investment'],2)
  tmp_df['NTT%'] = round((tmp_df['NTT'] - tmp_df['Close'])*100/tmp_df['Close'],2)
  tmp_df['LTT%'] = round((tmp_df['LTT'] - tmp_df['Close'])*100/tmp_df['Close'],2)
  tmp_df['Gained%'] = round((tmp_df['Close'] - tmp_df['BOL'])*100/tmp_df['BOL'],2)
  investment = round(sum(tmp_df['AvgCost']*tmp_df['Shares']),0)
  current = round(sum(tmp_df['Close']*tmp_df['Shares']),0)
  tmp_df['InitAlloc%'] = round(tmp_df['Investment']*100/investment,2)
  tmp_df['CurrAlloc%'] = round(tmp_df['Current']*100/current,2)
  tmp_df['FTT'] = tmp_df['LTT']
  tmp_df.loc[tmp_df['Strategy'] == 'NTT', 'FTT'] = tmp_df['NTT']
  tmp_df['FTT%'] = tmp_df['LTT%']
  tmp_df.loc[tmp_df['Strategy'] == 'NTT', 'FTT%'] = tmp_df['NTT%']
  tmp_df['FTT Amt'] = round(tmp_df['FTT%'] * tmp_df['Current']/100,0)
  tmp_df['OTT%'] = round((tmp_df['FTT'] - tmp_df['AvgCost'])*100/tmp_df['AvgCost'],2)
  tmp_df['RRR Ind'] = round(tmp_df['Current P/L']/tmp_df['FTT Amt'],2)
  tmp_df['Risk Ind'] = round(tmp_df['Current P/L%']*tmp_df['CurrAlloc%'],0)

  return tmp_df

# function to print portfolio features
def print_portfolio_stats(df_portfolio_features, myinvmt_df):
  from pyxirr import xirr

  total_booked_amt, reserve_amt, cy_booked_amt, py_booked_amt = get_amt()

  dates = myinvmt_df['Date'].values
  dates = np.append(dates, datetime.date.today().strftime('%d-%b-%y'))
  investment = myinvmt_df['Investment'].values
  dates= pd.to_datetime(dates)

  current = round(sum(df_portfolio_features['Close']*df_portfolio_features['Shares']),0) + reserve_amt
  investment_xirr = np.append(investment, current)
  cagr = round(xirr(pd.DataFrame({"dates": dates, "amounts": investment_xirr}))*100,2)

  investment = -sum(investment)
  invested = round(sum(df_portfolio_features['AvgCost']*df_portfolio_features['Shares']),0) + reserve_amt
  previous = round(sum(df_portfolio_features['Prev_Close']*df_portfolio_features['Shares']),0) + reserve_amt
  cy_invested = investment + py_booked_amt

  today_pnl_amount = current-previous
  today_pnl_percentage = round((current-previous)*100/previous,2)

  curr_pnl_amount = current-invested
  curr_pnl_percentage = round((curr_pnl_amount)*100/(cy_invested),2)

  cy_pnl_amount = cy_booked_amt + curr_pnl_amount
  cy_pnl_percentage = round((cy_pnl_amount)*100/cy_invested,2)

  overall_pnl_amount = total_booked_amt + curr_pnl_amount
  overall_pnl_percentage = round((overall_pnl_amount)*100/investment,2)

  estimate_st = round(sum(df_portfolio_features['FTT']*df_portfolio_features['Shares']),0)  + reserve_amt
  est_st_pnl_amount = estimate_st-current
  est_st_pnl_percentage = round((est_st_pnl_amount)*100/current,2)

  estimate_lt = round(sum(df_portfolio_features['LTT']*df_portfolio_features['Shares']),0)  + reserve_amt
  est_lt_pnl_amount = estimate_lt-current
  est_lt_pnl_percentage = round((est_lt_pnl_amount)*100/current,2)

  total_profit = round(sum(df_portfolio_features[df_portfolio_features['Current P/L%'] > 0]['Current']) - sum(df_portfolio_features[df_portfolio_features['Current P/L%'] > 0]['Investment']),0)
  total_loss = round(sum(df_portfolio_features[df_portfolio_features['Current P/L%'] < 0]['Current']) - sum(df_portfolio_features[df_portfolio_features['Current P/L%'] < 0]['Investment']),0)

  cy_booked_percentage = round((cy_booked_amt)*100/current,2)
  py_booked_percentage = round((py_booked_amt)*100/investment,2)
  total_booked_percentage = round((total_booked_amt)*100/investment,2)

  print('-------------------')
  print('Initial Investment: ', format_amt(investment))
  print('CY Investment: ', format_amt(cy_invested))
  print('Reserve: ', format_amt(reserve_amt))
  print('Current: ',  format_amt(current))
  print('-------------------')
  print('Today PnL: '+ '{} ({}%)'.format(format_amt(today_pnl_amount), today_pnl_percentage))
  print('Current PnL: '+ '{} ({}%)'.format(format_amt(curr_pnl_amount), curr_pnl_percentage))
  print('CY Booked + Current PnL: '+ '{} ({}%)'.format(format_amt(cy_pnl_amount), cy_pnl_percentage))
  print('-------------------')
  print('Total profit: ', format_amt(total_profit))
  print('Total loss: ', format_amt(total_loss))
  print('-------------------')
  print('Total Booked + Current PnL: '+ '{} ({}%)'.format(format_amt(overall_pnl_amount), overall_pnl_percentage))
  print('Total Booked PnL: '+ '{} ({}%)'.format(format_amt(total_booked_amt), total_booked_percentage))
  print('Curr Year Booked PnL: '+ '{} ({}%)'.format(format_amt(cy_booked_amt), cy_booked_percentage))
  print('Prev Year Booked PnL: '+ '{} ({}%)'.format(format_amt(py_booked_amt), py_booked_percentage))
  print('===================')
  print('Est FTT: ',  format_amt(estimate_st))
  print('Est FTT PnL: '+ '{} ({}%)'.format(format_amt(est_st_pnl_amount), est_st_pnl_percentage))

  print('===================')
  print('Deployed: ', format_amt(investment))

  print('Current: ', format_amt(current))

  print('CAGR/XIRR %: '+'{}%'.format(cagr))

In [8]:
# get start and end date
start_date, end_date = get_start_end_date()

# get portfolio and prospects data
mypfs_df = get_mypfs_df()
mypps_df = get_mypps_df()
myinvmt_df = get_myinvmt_df()

# merge above datasets
mypf_df = pd.merge(mypfs_df, mypps_df, on="Symbol")

# seggregate dm and sv portfolio
dm_pf = mypf_df[mypf_df['InPortfolio'] == 'DM']
sv_pf = mypf_df[mypf_df['InPortfolio'] == 'SV']

# build portfolio stock dataframe
dm_stocks = get_stock_ids(dm_pf)
sv_stocks = get_stock_ids(sv_pf)
df_stocks = pd.concat([dm_pf,sv_pf], ignore_index = True)

# arrange common and diff stock features
common_cols = ['Symbol', 'Target', 'Criteria', 'Strategy', 'CumlRnk', 'LatestQtr', 'StarStock', 'Conviction', 'Category', 'InFolio', 'XIRR', 'MBQ']
diff_cols = ['Symbol', 'AvgCost', 'Shares']
df_stocks = arrange_features(df_stocks, common_cols, diff_cols)

# get common features
stock_ids = df_stocks['Symbol'].values
df_common_features = get_common_features(stock_ids, df_stocks)

df_common_features.reset_index(drop=True, inplace=True)
df_common_features.drop(['Date'], axis=1, inplace=True)
# get and print portfolio features
df_portfolio_features = get_portfolio_features(df_common_features)

print_portfolio_stats(df_portfolio_features, myinvmt_df)

df = df_portfolio_features
#plot_pie_chart(df, 'CapType', 'Current')
list_ox40n = list(df[df['MBQ'].str.contains('OX40N', na=False)]['Symbol'].values)

Run date time (IST): 2026-03-04 14:55:01
-------------------
qualified stocks: 86
with latest results: 26
still star stocks: 15
-------------------
Initial Investment:  1.33 C
CY Investment:  1.60 C
Reserve:  2.44 L
Current:  1.35 C
-------------------
Today PnL: -2.05 L (-1.49%)
Current PnL: -39.62 L (-24.77%)
CY Booked + Current PnL: -23.94 L (-14.97%)
-------------------
Total profit:  86.41 K
Total loss:  -40.49 L
-------------------
Total Booked + Current PnL: 3.04 L (2.28%)
Total Booked PnL: 42.66 L (32.07%)
Curr Year Booked PnL: 15.68 L (11.63%)
Prev Year Booked PnL: 26.98 L (20.29%)
===================
Est FTT:  2.41 C
Est FTT PnL: 1.06 C (78.8%)
===================
Deployed:  1.33 C
Current:  1.35 C
CAGR/XIRR %: 0.68%

In [9]:
# top 5 near their targets
cols = ['Symbol', 'Today P/L%', 'Current P/L%', 'FTT%', 'OTT%', 'FTT Amt', 'Current P/L', 'Current', 'FTT', 'Dev%_PE', 'RSI_14','Conviction', 'Spread%',  'CumlRnk', 'RRR Ind', 'CurrAlloc%', 'Gained%', 'Criteria', 'Strategy', 'Category']
df_tmp = df_portfolio_features[~df_portfolio_features['Symbol'].isin(['ENRIN','BLUSPRING','DIGITIDE'])]
df_tmp = df_tmp.sort_values(by = 'FTT Amt', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
19,COALINDIA,2.44,7.38,9.59,17.67,15494.0,11100.0,161560.0,478.51,29.12,59.0,L-LC,11.03,185.0,0.72,1.22,28.45,XY25,ATH,MINING
50,MASFIN,-2.92,-6.26,29.69,21.57,27269.0,-6135.0,91845.0,397.04,-19.15,37.0,H-SC,6.51,167.0,-0.22,0.69,33.01,XR,ATH,FINANCE
77,TTKPRESTIG,-1.57,-35.88,56.09,0.09,36246.0,-36155.0,64622.0,770.00,50.05,23.0,M-SC,12.45,250.0,-1.00,0.49,0.00,OX40N,NTT,DURABLES
51,MEDANTA,-1.52,-7.08,33.54,24.08,39563.0,-8993.0,117957.0,1486.00,-7.74,44.0,X-SC,8.02,87.0,-0.23,0.89,8.04,XY24,NTT,HEALTHCARE
37,ICICIGI,-2.15,-1.75,21.47,19.34,42210.0,-3511.0,196598.0,2252.93,-17.38,41.0,X-MC,1.30,66.0,-0.08,1.49,13.90,X40,ATH,INSURANCE

In [10]:
# top 5 today
df_tmp = df_portfolio_features.sort_values(by = 'Today P/L%', ascending=False)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
69,SURYODAY,3.92,-25.93,66.10,23.03,87676.0,-46430.0,132641.0,216.00,44.74,51.0,H-SC,6.69,166.0,-0.53,1.00,31.61,XR,NTT,BANKS
2,ABBOTINDIA,3.43,-6.99,26.94,18.07,44815.0,-12505.0,166350.0,35195.00,-20.76,62.0,X-MC,11.32,58.0,-0.28,1.26,5.46,X40,ATH,PHARMA
19,COALINDIA,2.44,7.38,9.59,17.67,15494.0,11100.0,161560.0,478.51,29.12,59.0,L-LC,11.03,185.0,0.72,1.22,28.45,XY25,ATH,MINING
43,INFY,1.93,-10.56,50.10,34.24,140199.0,-33049.0,279839.0,1972.00,-29.61,30.0,X-LC,10.08,3.0,-0.24,2.11,3.00,X40,NTT,IT
18,CERA,0.38,-37.20,97.27,23.89,107453.0,-65434.0,110469.0,9475.00,-39.38,33.0,H-SC,14.89,153.0,-0.61,0.83,0.38,OX40N,NTT,CERAMICS

In [11]:
# bottom 5 today
df_tmp = df_portfolio_features.sort_values(by = 'Today P/L%', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
75,TMPV,-5.02,-21.78,70.45,33.33,179540.0,-70952.0,254848.0,600.00,-83.62,37.0,X-LC,3.58,4.0,-0.40,1.93,4.19,XY24,NTT,AUTO
55,RAJESHEXPO,-4.99,-74.56,293.32,0.07,102369.0,-102277.0,34900.0,518.00,1179.04,24.0,L-SC,11.11,268.0,-1.00,0.26,0.00,OX40N,NTT,JEWELLERY
27,FINCABLES,-4.89,14.01,82.36,107.91,138635.0,20684.0,168328.0,1641.55,2.49,65.0,M-SC,6.40,220.0,0.15,1.27,26.64,OX40N,ATH,CABLES
65,SIEMENS,-4.82,-14.54,46.87,25.51,74540.0,-27060.0,159035.0,4671.50,33.57,49.0,H-LC,3.71,51.0,-0.36,1.20,17.12,AR,ATH,ELECTRICAL
12,BATAINDIA,-4.42,-52.56,184.98,35.20,112923.0,-67624.0,61046.0,2096.00,-20.00,19.0,X-SC,23.01,91.0,-0.60,0.46,0.00,X40,NTT,FOOTWEAR

In [12]:
# top 5 to exit based on CumlRnk
df_tmp = df_portfolio_features[~df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])]
df_tmp = df_tmp[(df_tmp['Current P/L%'] > -1) & (df_tmp['Current P/L%'] < 1)].sort_values(by = 'CumlRnk', ascending=False)
df_tmp[cols].head()

Empty DataFrame
Columns: [Symbol, Today P/L%, Current P/L%, FTT%, OTT%, FTT Amt, Current P/L, Current, FTT, Dev%_PE, RSI_14, Conviction, Spread%, CumlRnk, RRR Ind, CurrAlloc%, Gained%, Criteria, Strategy, Category]
Index: []

In [13]:
# OX40N stocks to exit
df_tmp = df_portfolio_features[(df_portfolio_features['Symbol'].isin(list_ox40n))].sort_values(by = 'Current P/L%', ascending=False)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
27,FINCABLES,-4.89,14.01,82.36,107.91,138635.0,20684.0,168328.0,1641.55,2.49,65.0,M-SC,6.40,220.0,0.15,1.27,26.64,OX40N,ATH,CABLES
66,SIS,-2.44,-31.72,77.60,21.26,58830.0,-35220.0,75812.0,528.00,1778.76,36.0,H-SC,6.48,168.0,-0.60,0.57,4.51,OX40N,NTT,MISC
48,KANSAINER,0.31,-34.28,72.67,13.47,128785.0,-92448.0,177219.0,340.00,-43.52,33.0,H-SC,14.08,162.0,-0.72,1.34,0.31,XY24,NTT,PAINTS
41,INDIGOPNTS,-0.14,-34.86,53.55,0.02,60887.0,-60857.0,113702.0,1408.00,73.55,23.0,M-SC,13.13,222.0,-1.00,0.86,0.00,OX40N,NTT,PAINTS
77,TTKPRESTIG,-1.57,-35.88,56.09,0.09,36246.0,-36155.0,64622.0,770.00,50.05,23.0,M-SC,12.45,250.0,-1.00,0.49,0.00,OX40N,NTT,DURABLES

In [14]:
# top 5 to book for rotation
df_tmp = df_portfolio_features[(df_portfolio_features['Current P/L%'] > 20) ].sort_values(by = 'CumlRnk', ascending=False)
df_tmp[cols].head()

Empty DataFrame
Columns: [Symbol, Today P/L%, Current P/L%, FTT%, OTT%, FTT Amt, Current P/L, Current, FTT, Dev%_PE, RSI_14, Conviction, Spread%, CumlRnk, RRR Ind, CurrAlloc%, Gained%, Criteria, Strategy, Category]
Index: []

In [15]:
# top 5 to monitor for exit
df_tmp = df_portfolio_features[~df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])]
df_tmp = df_tmp[(df_tmp['Current P/L%'] > 0) ].sort_values(by = 'Dev%_PE', ascending=False)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
19,COALINDIA,2.44,7.38,9.59,17.67,15494.0,11100.0,161560.0,478.51,29.12,59.0,L-LC,11.03,185.0,0.72,1.22,28.45,XY25,ATH,MINING
27,FINCABLES,-4.89,14.01,82.36,107.91,138635.0,20684.0,168328.0,1641.55,2.49,65.0,M-SC,6.40,220.0,0.15,1.27,26.64,OX40N,ATH,CABLES
1,ABB,-1.51,8.11,34.65,45.57,98004.0,21221.0,282840.0,7934.00,-30.51,56.0,H-MC,8.90,125.0,0.22,2.14,25.60,AR,NTT,ELECTRICAL

In [16]:
# top 5 to book for rotation from weak conviction
df_tmp = df_portfolio_features[~df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])]
df_tmp = df_tmp[~df_tmp['Criteria'].isin(['XY25','XY24','X40', 'X40N'])].sort_values(by = 'RRR Ind', ascending=False)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
1,ABB,-1.51,8.11,34.65,45.57,98004.0,21221.0,282840.0,7934.00,-30.51,56.0,H-MC,8.90,125.0,0.22,2.14,25.60,AR,NTT,ELECTRICAL
27,FINCABLES,-4.89,14.01,82.36,107.91,138635.0,20684.0,168328.0,1641.55,2.49,65.0,M-SC,6.40,220.0,0.15,1.27,26.64,OX40N,ATH,CABLES
40,INDIAMART,-1.65,-10.66,131.39,106.72,144775.0,-13149.0,110187.0,4810.62,-59.77,33.0,H-SC,8.27,140.0,-0.09,0.83,10.22,AR,ATH,MISC
85,ZYDUSLIFE,-0.87,-5.20,43.07,35.63,85571.0,-10895.0,198679.0,1286.17,-17.57,47.0,H-MC,4.95,120.0,-0.13,1.50,10.61,AR,ATH,PHARMA
84,WIPRO,-1.46,-19.74,114.64,72.27,155908.0,-33450.0,135998.0,420.00,-27.37,20.0,M-LC,11.40,98.0,-0.21,1.03,0.00,XR,NTT,IT

In [17]:
# top 5 to accumulate based on lowest RSI_14
df_tmp = df_portfolio_features[df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])].sort_values(by = 'RSI_14', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
8,AWL,-0.19,-41.68,169.53,57.19,322441.0,-135930.0,190197.0,485.00,-66.62,13.0,X-SC,19.85,81.0,-0.42,1.44,0.00,XY24,NTT,FMCG
12,BATAINDIA,-4.42,-52.56,184.98,35.20,112923.0,-67624.0,61046.0,2096.00,-20.00,19.0,X-SC,23.01,91.0,-0.60,0.46,0.00,X40,NTT,FOOTWEAR
3,ACC,-1.30,-35.57,154.79,64.15,237293.0,-84651.0,153300.0,3906.00,-51.19,24.0,X-SC,9.91,85.0,-0.36,1.16,0.00,XY24,BTT,CEMENT
9,BAJAJHFL,-1.01,-27.69,115.00,55.47,202321.0,-67355.0,175931.0,181.50,-38.00,24.0,X-MC,17.72,60.0,-0.33,1.33,0.00,X40N,ATH,FINANCE
53,PGHH,0.05,-15.88,56.93,32.01,102255.0,-33904.0,179616.0,17616.87,-43.10,24.0,X-MC,9.78,57.0,-0.33,1.36,0.05,X40,ATH,FMCG

In [18]:
# top 5 to accumulate based on Spread and CumlRnk
df_tmp = df_portfolio_features[df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])]
df_tmp = df_tmp[(df_tmp['CumlRnk'] < 100)].sort_values(by = 'Spread%', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
37,ICICIGI,-2.15,-1.75,21.47,19.34,42210.0,-3511.0,196598.0,2252.93,-17.38,41.0,X-MC,1.30,66.0,-0.08,1.49,13.90,X40,ATH,INSURANCE
78,UNITDSPR,-3.18,-2.81,24.25,20.77,55186.0,-6571.0,227573.0,1644.00,-13.87,36.0,X-MC,1.36,64.0,-0.12,1.72,4.10,X40N,NTT,BREWERIES
22,DABUR,-3.17,-3.91,49.54,43.70,118092.0,-9690.0,238378.0,735.00,-12.82,37.0,X-MC,1.47,70.0,-0.08,1.80,10.56,XY24,BTT,FMCG
59,RELIANCE,-0.66,-13.41,44.70,25.30,77787.0,-26942.0,174021.0,1952.00,-15.80,32.0,X-LC,2.17,21.0,-0.35,1.31,16.57,XY25,BTT,REFINERIES
35,HINDUNILVR,-1.53,-11.10,27.87,13.67,63689.0,-28543.0,228520.0,2922.00,-34.02,40.0,X-LC,2.50,9.0,-0.45,1.73,7.88,XY25,NTT,FMCG

In [19]:
# top 5 to accumulate based on lowest Gained%
df_tmp = df_portfolio_features[df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])].sort_values(by = 'Gained%', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
3,ACC,-1.30,-35.57,154.79,64.15,237293.0,-84651.0,153300.0,3906.0,-51.19,24.0,X-SC,9.91,85.0,-0.36,1.16,0.0,XY24,BTT,CEMENT
12,BATAINDIA,-4.42,-52.56,184.98,35.20,112923.0,-67624.0,61046.0,2096.0,-20.00,19.0,X-SC,23.01,91.0,-0.60,0.46,0.0,X40,NTT,FOOTWEAR
9,BAJAJHFL,-1.01,-27.69,115.00,55.47,202321.0,-67355.0,175931.0,181.5,-38.00,24.0,X-MC,17.72,60.0,-0.33,1.33,0.0,X40N,ATH,FINANCE
8,AWL,-0.19,-41.68,169.53,57.19,322441.0,-135930.0,190197.0,485.0,-66.62,13.0,X-SC,19.85,81.0,-0.42,1.44,0.0,XY24,NTT,FMCG
13,BERGEPAINT,-1.98,-21.87,55.06,21.14,97794.0,-49726.0,177613.0,680.0,-23.60,26.0,X-MC,14.35,68.0,-0.51,1.34,0.0,XY24,NTT,PAINTS

In [20]:
# top 5 to accumulate based on lowest CurrAlloc%
df_tmp = df_portfolio_features[df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])].sort_values(by = 'CurrAlloc%', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
54,QUESS,-1.46,-36.32,124.33,42.84,51464.0,-23613.0,41393.0,424.00,-58.13,33.0,X-SC,16.96,80.0,-0.46,0.31,0.00,XY24,NTT,MISC
12,BATAINDIA,-4.42,-52.56,184.98,35.20,112923.0,-67624.0,61046.0,2096.00,-20.00,19.0,X-SC,23.01,91.0,-0.60,0.46,0.00,X40,NTT,FOOTWEAR
58,RELAXO,-0.97,-57.67,259.80,52.31,159642.0,-83712.0,61448.0,1176.00,-54.89,26.0,X-SC,15.87,92.0,-0.52,0.46,0.00,X40N,NTT,FOOTWEAR
51,MEDANTA,-1.52,-7.08,33.54,24.08,39563.0,-8993.0,117957.0,1486.00,-7.74,44.0,X-SC,8.02,87.0,-0.23,0.89,8.04,XY24,NTT,HEALTHCARE
36,HONAUT,-0.71,-26.06,93.85,43.32,113014.0,-42452.0,120420.0,58357.33,-35.08,32.0,X-SC,12.54,90.0,-0.38,0.91,0.00,X40N,ATH,ELECTRICAL

In [21]:
# top 5 to accumulate based on CumlRnk
df_tmp = df_portfolio_features.sort_values(by = 'CumlRnk', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
45,ITC,-0.48,-17.45,44.22,19.06,124172.0,-59360.0,280806.0,452.00,-54.71,39.0,X-LC,16.87,1.0,-0.48,2.12,1.67,X40,NTT,FMCG
73,TCS,-0.70,-25.62,66.14,23.58,212833.0,-110837.0,321792.0,4311.59,-35.43,28.0,X-LC,10.80,2.0,-0.52,2.43,0.83,X40,ATH,IT
43,INFY,1.93,-10.56,50.10,34.24,140199.0,-33049.0,279839.0,1972.00,-29.61,30.0,X-LC,10.08,3.0,-0.24,2.11,3.00,X40,NTT,IT
75,TMPV,-5.02,-21.78,70.45,33.33,179540.0,-70952.0,254848.0,600.00,-83.62,37.0,X-LC,3.58,4.0,-0.40,1.93,4.19,XY24,NTT,AUTO
34,HCLTECH,-0.02,-11.05,39.21,23.83,84380.0,-26724.0,215200.0,1908.19,-6.53,28.0,X-LC,7.41,8.0,-0.32,1.63,3.25,X40,ATH,IT

In [22]:
# top 5 for average up
df_tmp = df_portfolio_features[(df_portfolio_features['Dev%_200'] > 5)].sort_values(by = 'CurrAlloc%', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
42,INDUSINDBK,-1.43,-31.41,93.76,32.89,49649.0,-24254.0,52953.0,1800.00,-349.30,51.0,L-MC,12.19,258.0,-0.49,0.40,45.83,XR,NTT,BANKS
67,SONACOMS,-2.94,-13.15,60.15,39.09,52847.0,-13300.0,87859.0,804.02,-31.14,43.0,M-MC,10.95,193.0,-0.25,0.66,24.29,AR,ATH,AUTO
19,COALINDIA,2.44,7.38,9.59,17.67,15494.0,11100.0,161560.0,478.51,29.12,59.0,L-LC,11.03,185.0,0.72,1.22,28.45,XY25,ATH,MINING
27,FINCABLES,-4.89,14.01,82.36,107.91,138635.0,20684.0,168328.0,1641.55,2.49,65.0,M-SC,6.40,220.0,0.15,1.27,26.64,OX40N,ATH,CABLES
82,VOLTAS,-3.46,13.22,28.24,45.20,61308.0,25353.0,217095.0,1856.00,29.67,45.0,X-MC,9.85,79.0,0.41,1.64,20.92,XY25,NTT,AC

In [23]:
# top 5 RSP
df_tmp = df_portfolio_features.sort_values(by = 'RSP', ascending=False)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
27,FINCABLES,-4.89,14.01,82.36,107.91,138635.0,20684.0,168328.0,1641.55,2.49,65.0,M-SC,6.40,220.0,0.15,1.27,26.64,OX40N,ATH,CABLES
26,EASEMYTRIP,-2.75,-57.12,239.77,45.70,181794.0,-100995.0,75820.0,26.40,-21.23,48.0,M-SC,18.05,204.0,-0.56,0.57,24.92,XY24,NTT,TRAVEL
83,WHIRLPOOL,-1.40,-27.75,151.79,81.92,125899.0,-31855.0,82943.0,2270.00,-57.64,53.0,M-SC,25.85,210.0,-0.25,0.63,16.51,XR,NTT,DURABLES
11,BANDHANBNK,0.33,-14.25,124.40,92.42,297136.0,-39704.0,238855.0,400.00,104.74,64.0,H-SC,8.96,174.0,-0.13,1.80,31.58,XY24,NTT,BANKS
7,ATULAUTO,-4.13,-21.04,84.36,45.57,131308.0,-41480.0,155652.0,844.00,3364.86,46.0,M-SC,7.22,248.0,-0.32,1.18,17.79,XY24,NTT,AUTO

In [24]:
# Top N allocation
df_tmp = df_portfolio_features.sort_values(by = 'CurrAlloc%', ascending=False)
top_n_values = [10, 25, 50]

sum_df = pd.DataFrame({
    'Top_N': top_n_values,
    'Sum_Alloc%': [df_tmp['CurrAlloc%'].head(n).sum() for n in top_n_values]
})

sum_df

   Top_N  Sum_Alloc%
0     10       20.72
1     25       45.56
2     50       77.58

In [25]:
# market-cap-wise allocation
df_tmp = df_portfolio_features[cols]
df_tmp.groupby(df_tmp['Conviction'].str[-2:])['CurrAlloc%'].sum().sort_values(ascending=False)

Conviction
SC    44.80
MC    30.24
LC    24.96
Name: CurrAlloc%, dtype: float64

In [26]:
# criteria-wise allocation
df_portfolio_features.groupby('Criteria')['CurrAlloc%'].sum().sort_values(ascending=False)

Criteria
XY24     26.75
X40      24.13
X40N     14.53
AR        9.13
XY25      8.92
XR        8.52
OX40N     7.20
SR        0.82
Name: CurrAlloc%, dtype: float64

In [27]:
# conviction-wise allocation
df_portfolio_features.groupby('Conviction')['CurrAlloc%'].sum().sort_values(ascending=False)

Conviction
X-MC    22.81
H-SC    22.29
X-LC    21.51
X-SC    11.12
M-SC    10.72
H-MC     5.01
M-MC     2.02
L-LC     1.22
H-LC     1.20
M-LC     1.03
L-SC     0.67
L-MC     0.40
Name: CurrAlloc%, dtype: float64

In [28]:
# sector-wise stats
df_tmp = df_portfolio_features.groupby('Category')[['CurrAlloc%', 'Current', 'Current P/L', 'FTT Amt']].sum().sort_values(by=['Current', 'Current P/L'], ascending=False)
df_tmp['Current P/L%'] = round(df_tmp['Current P/L'] * 100 / df_tmp['Current'], 2)
df_tmp['FTT%'] = round(df_tmp['FTT Amt'] * 100 / df_tmp['Current'], 2)
cols = ['CurrAlloc%', 'Current P/L%', 'FTT%']
df_tmp[cols].sort_values(by=['CurrAlloc%'], ascending=False)

               CurrAlloc%  Current P/L%    FTT%
Category
FMCG                15.71        -18.75   58.91
FINANCE             12.80        -23.11   71.56
IT                  11.60        -42.85  114.44
MISC                 6.75        -45.27  104.69
ELECTRICAL           6.35        -11.72   52.49
PAINTS               5.06        -37.87   58.36
INSURANCE            4.94         -3.82   39.35
PHARMA               4.27         -4.15   36.93
AUTO                 3.77        -25.23   72.98
BANKS                3.20        -26.01  102.36
AC                   2.21         -9.39   39.05
FOOTWEAR             1.98        -68.05  135.43
TRAVEL               1.94        -74.20  161.43
DURABLES             1.88        -55.41   93.22
BREWERIES            1.72         -2.89   24.25
HEALTHCARE           1.66        -40.05   74.61
APPARELS             1.41        -26.92   65.17
CERAMICS             1.41        -64.51  114.48
REALTY               1.41        -19.02   38.57
REFINERIES           1.31        -15.48   44.70
CABLES               1.27         12.29   82.36
MINING               1.22          6.87    9.59
JEWELLERY            1.19       -103.26  173.88
CEMENT               1.16        -55.22  154.79
ENGINEERING          1.11        -64.65  139.96
CHEMICALS            1.03        -93.47  251.30
ENTERTAINMENT        0.79        -85.01  195.35
TEXTILES             0.44        -57.13  101.94
HOTELS               0.41       -107.07  180.11

In [29]:
# money to be made criteria-wise
df_portfolio_features.groupby('Criteria')['FTT Amt'].agg(['sum', 'count']).sort_values(by='sum', ascending=False)

                sum  count
Criteria
XY24      3585749.0     21
X40       1528605.0     15
AR        1364185.0     10
XR        1362125.0     12
X40N      1198863.0     10
OX40N      837813.0     10
XY25       435952.0      6
SR         310412.0      2

In [30]:
# money to be made conviction-wise
df_portfolio_features.groupby('Conviction')['FTT Amt'].agg(['sum', 'count']).sort_values(by='sum', ascending=False)

                  sum  count
Conviction
H-SC        3840457.0     24
M-SC        1498772.0     14
X-MC        1496869.0     15
X-LC        1426238.0     12
X-SC        1330622.0     10
H-MC         416312.0      3
L-SC         201132.0      2
M-LC         155908.0      1
M-MC         117711.0      2
H-LC          74540.0      1
L-MC          49649.0      1
L-LC          15494.0      1

In [31]:
# money to be made criteria and conviction-wise
df_portfolio_features.groupby(['Conviction', 'Criteria'])['FTT Amt'].agg(['sum', 'count']).sort_values(by='sum', ascending=False)

                           sum  count
Conviction Criteria
H-SC       XY24      1304401.0      6
           AR         976505.0      5
M-SC       XY24       877944.0      6
H-SC       XR         872055.0      7
X-LC       X40        729384.0      6
X-SC       XY24       650761.0      4
X-MC       X40        596922.0      7
X-SC       X40N       477562.0      4
X-MC       X40N       469943.0      4
H-SC       OX40N      377084.0      4
M-SC       OX40N      358360.0      5
H-SC       SR         310412.0      2
X-LC       XY24       304020.0      2
           X40N       251358.0      2
H-MC       XY24       232737.0      1
X-MC       XY24       215886.0      2
           XY25       214118.0      2
X-SC       X40        202299.0      2
M-SC       XR         185750.0      2
H-MC       AR         183575.0      2
M-LC       XR         155908.0      1
X-LC       XY25       141476.0      2
L-SC       OX40N      102369.0      1
           XR          98763.0      1
M-SC       AR          76718.0      1
H-LC       AR          74540.0      1
M-MC       XY25        64864.0      1
           AR          52847.0      1
L-MC       XR          49649.0      1
L-LC       XY25        15494.0      1

In [32]:
# notebook execution time

end_time = time.time()
execution_time = round(end_time - start_time, 0)
print(f"Notebook execution time: {execution_time} seconds")

Notebook execution time: 24.0 seconds