<a href="https://colab.research.google.com/github/ankit-rathi/Quantvesting_v2/blob/main/myStocks_Portfolio_Analysis.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
'''
!pip install pandas==2.2.2 -qq
!pip install pyxirr -qq
!pip install ta -qq
!pip install yfinance==0.2.59 -qq
'''

'\n!pip install pandas==2.2.2 -qq\n!pip install pyxirr -qq\n!pip install ta -qq\n!pip install yfinance==0.2.59 -qq\n'

In [2]:
# import libraries

import numpy as np
import pandas as pd
import datetime
import warnings
warnings.filterwarnings('ignore')
import yfinance as yfin
import ta
import matplotlib.pyplot as plt
import requests

In [3]:
# notebook start time
import time
import datetime
import pytz

start_time = time.time()

# function to print date timestamp
def print_date_time():
  tz_NY = pytz.timezone('Asia/Kolkata')
  datetime_NY = datetime.datetime.now(tz_NY)
  print("Run date time (IST):", datetime_NY.strftime("%Y-%m-%d %H:%M:%S"))

In [4]:
# function to get booked and reserved amount
def get_amt():
  # fetch the JSON data from the URL
  url = "https://raw.githubusercontent.com/ankit-rathi/Tradevesting_v1/main/data/myPortfolioAmts.json"
  response = requests.get(url)
  pf_amts = response.json()  # parse the JSON data

  # extract values from the JSON
  py_booked_amt_dm = pf_amts["py_booked_amt_dm"]
  py_booked_amt_sv = pf_amts["py_booked_amt_sv"]
  cy_booked_amt_dm = pf_amts["cy_booked_amt_dm"]
  cy_booked_amt_sv = pf_amts["cy_booked_amt_sv"]
  reserve_amt_dm = pf_amts["reserve_amt_dm"]
  reserve_amt_sv = pf_amts["reserve_amt_sv"]

  # perform calculations
  py_booked_amt = py_booked_amt_dm + py_booked_amt_sv
  cy_booked_amt = cy_booked_amt_dm + cy_booked_amt_sv
  reserve_amt = reserve_amt_dm + reserve_amt_sv
  total_booked_amt = py_booked_amt + cy_booked_amt

  return total_booked_amt, reserve_amt, cy_booked_amt, py_booked_amt

gen_output = 0

In [5]:
# function to format the amount
def format_amt(number):
    abs_number = abs(number)

    if abs_number >= 1_00_00_000:  # Crores
        formatted_amt = f"{number / 1_00_00_000:.2f} C"
    elif abs_number >= 1_00_000:  # Lakhs
        formatted_amt = f"{number / 1_00_000:.2f} L"
    elif abs_number >= 1_000:  # Thousands
        formatted_amt = f"{number / 1_000:.2f} K"
    else:
        formatted_amt = f"{number:.2f}"

    return formatted_amt

# function to set start and end date
def get_start_end_date():
  start_date = (datetime.date.today() + datetime.timedelta(days=-365)).strftime('%Y-%m-%d')
  end_date = (datetime.date.today() + datetime.timedelta(days=1)).strftime('%Y-%m-%d')
  return start_date, end_date

# function to fetch my portfolio csv
def get_mypfs_df():
  mypfs_df = pd.read_csv('https://raw.githubusercontent.com/ankit-rathi/Tradevesting_v1/main/data/myPortfolioStocks.csv')
  return mypfs_df

# function to fetch my prospects csv
def get_mypps_df():
  mypps_df = pd.read_csv('https://raw.githubusercontent.com/ankit-rathi/Tradevesting_v1/main/data/myProspectsScrips.csv')
  return mypps_df

# function to fetch screener data
def get_myscreen_df():
  myscreen_df = pd.read_csv('https://raw.githubusercontent.com/ankit-rathi/Tradevesting_v1/main/data/myScreenerDB.csv')
  return myscreen_df

# function to fetch momentum data
def get_myinvmt_df():
  myinvmt_df = pd.read_csv('https://raw.githubusercontent.com/ankit-rathi/Tradevesting_v1/main/data/myInvestments.csv')
  return myinvmt_df

# function to get the stock ids
def get_stock_ids(df_pf):
  stock_n100 = df_pf['Symbol'].unique()

  exclude = ['CADILAHC','MMTC', 'MASFIN']

  stock_ids = df_pf[~df_pf['Symbol'].isin(exclude) ]['Symbol'].unique()

  #mypf = mypf[mypf.Forecast.notnull()]
  #stock_ids = mypf['Symbol'].unique()

  #stock_ids.sort()
  return stock_ids

# get features from screener data
def get_screener_features():
  myscreen_df = get_myscreen_df()
  cols = ['Symbol', 'EPS', 'MedPE', 'ROCE%', 'ROE%', 'CapType']
  return myscreen_df[cols]

# get relative strength
def get_relative_strength(stock_list):

    # Dictionary to store stock tickers and their corresponding percentage price change
    stock_changes = {}

    # Loop through each stock and fetch its price data
    for stock in stock_list:
        try:
            # Download the stock data for the given date range
            stock_data = yfin.Ticker(stock + '.NS').history(period='1mo', interval='1d')[map(str.title, ['open', 'close', 'low', 'high', 'volume'])]

            # Calculate the percentage change for the stock
            if len(stock_data) > 0:
                start_price = stock_data['Close'].iloc[0]
                end_price = stock_data['Close'].iloc[-1]
                percent_change = round(((end_price - start_price) / start_price) * 100, 2)
                stock_changes[stock] = percent_change
            else:
                stock_changes[stock] = np.nan  # If no data is available, set to NaN

        except Exception as e:
            print(f"Error fetching data for {stock}: {e}")
            stock_changes[stock] = np.nan

    # Create a DataFrame with stock tickers and their percentage changes
    df = pd.DataFrame(list(stock_changes.items()), columns=['Symbol', 'Percent_Change'])

    # Drop any stocks with missing data (NaN values)
    df = df.dropna()

    # Calculate the percentile rank based on percentage change
    df['RSP'] = round(df['Percent_Change'].rank(pct=True) * 100, 2)
    cols = ['Symbol', 'RSP']
    df = df[cols]
    # Sort by percentile rank (optional)
    df = df.sort_values(by='RSP', ascending=False).reset_index(drop=True)

    return df

In [6]:
# function to get stock technicals
def stock_prec_dev(stock_symbol):
    #stock_symbol = 'ULTRACEMCO.NS'
    short_window = 20
    mid_window = 50
    long_window = 200
    moving_avg = 'SMA'

    start = datetime.datetime(*map(int, start_date.split('-')))
    end = datetime.datetime(*map(int, end_date.split('-')))

    stock_df = yfin.Ticker(stock_symbol + '.NS').history(period='max', interval='1d')[map(str.title, ['open', 'close', 'low', 'high', 'volume'])]

    stock_df['Max'] = round(max(stock_df['Close']),2)
    stock_df = stock_df[(stock_df.index <= end_date) & (stock_df.index >= start_date)]
    stock_df['200_SMA'] = round(stock_df['Close'].rolling(window = 200, min_periods = 1).mean(),0)
    stock_df['Dev%_200'] = round((stock_df['Close'] - stock_df['200_SMA'])*100/stock_df['200_SMA'],2)
    stock_df.dropna(axis = 0, inplace = True) # remove any null rows

    stock_df['20_SMA'] = stock_df['Close'].rolling(window=20).mean()
    stock_df['50_SMA'] = stock_df['Close'].rolling(window=50).mean()
    stock_df['Symbol'] = stock_symbol

    stock_df['Close'] = round(stock_df['Close'],2)
    stock_df['Min'] = round(min(stock_df['Close']),2)
    stock_df['RSI_14'] = ta.momentum.RSIIndicator(close=stock_df['Close'], window=14).rsi()
    stock_df['RSI_14'] = round(stock_df['RSI_14'],0)
    stock_df['Prev_Close'] = stock_df['Close'].shift(1)
    stock_df.drop(['Open', 'Low', 'High', 'Volume'], axis=1, inplace=True)
    stock_df = stock_df.tail(1)

    max_SMA = max(stock_df['20_SMA'].item(), stock_df['50_SMA'].item(), stock_df['200_SMA'].item())
    min_SMA = min(stock_df['20_SMA'].item(), stock_df['50_SMA'].item(), stock_df['200_SMA'].item())
    ABS_Spread = max_SMA - min_SMA
    stock_df['Spread%'] = round((ABS_Spread / stock_df['200_SMA'].item()) * 100,2)

    return stock_df

# function to compute stock attributes
def get_common_features(stock_ids, df_mypf):

  df_prec_dev = pd.DataFrame()
  df_tmp = get_screener_features()
  df_rs = get_relative_strength(stock_ids)

  for stock_id in stock_ids:
      tmp = stock_prec_dev(stock_id)
      tmp = tmp.reset_index()
      df_prec_dev = pd.concat([df_prec_dev, tmp], ignore_index = True)
  df_prec_dev = pd.merge(df_prec_dev, df_mypf, on= 'Symbol')
  df_prec_dev = pd.merge(df_prec_dev, df_tmp, on= 'Symbol', how='left')
  df_prec_dev = pd.merge(df_prec_dev, df_rs, on= 'Symbol', how='left')
  #print(df_prec_dev.columns)
  df_prec_dev['Curr_PE'] = round(df_prec_dev['Close']/df_prec_dev['EPS'],1)
  df_prec_dev['Dev%_PE'] = round((df_prec_dev['Curr_PE'] - df_prec_dev['MedPE'])*100/df_prec_dev['MedPE'],2)
  df_prec_dev['Conviction'] = df_prec_dev['Conviction'] + '-' + df_prec_dev['CapType']
  return df_prec_dev

# function to arrange stock features
def arrange_features(df_stocks, common_cols, diff_cols):
  df_stocks_common = df_stocks[common_cols].drop_duplicates()
  df_stocks_diff = df_stocks[diff_cols]
  df_stocks_diff['Investment'] = df_stocks_diff['AvgCost'] * df_stocks_diff['Shares']
  df_stocks_diff = df_stocks_diff.groupby(['Symbol'])[['Shares', 'Investment']].aggregate(['sum']).reset_index()
  df_stocks_diff.columns = ['Symbol', 'Shares', 'Investment']
  df_stocks_diff['AvgCost'] = round(df_stocks_diff['Investment']/df_stocks_diff['Shares'],2)
  df_stocks = pd.merge(df_stocks_diff, df_stocks_common, on='Symbol')
  return df_stocks

# plot fact distribution across dimension
def plot_pie_chart(df, dimension, fact):
  # grouping the data by category and calculating the sum of fact for each type
  grouped_data = df.groupby(dimension)[fact].sum()

  # sorting the grouped data in descending order
  grouped_data = grouped_data.sort_values(ascending=False)

  # creating a pie chart
  grouped_data.plot.pie(autopct='%1.1f%%', startangle=90, figsize=(6, 6))

  # adding a title and displaying the plot
  plt.title(f'{dimension} {fact} Distribution')
  plt.ylabel('')  # To hide the y-label
  plt.show()

In [7]:
# function to get portfolio features

def get_portfolio_features(df_common_features):

  print_date_time()
  print('-------------------')

  #df_common_features["Target"] = df_common_features["Target"].fillna(df_common_features["Max"])
  df_common_features['NTT'] = np.where(df_common_features['Strategy']== 'NTT', df_common_features["Target"], df_common_features['Max'])
  df_common_features['LTT'] = np.where(df_common_features['Strategy']== 'BTT', df_common_features["Target"], df_common_features['Max'])
  df_common_features['BOL'] = df_common_features['Min']

  tmp_df = df_common_features[df_common_features['Symbol'].isin(mypf_df[mypf_df['InPortfolio'] != 'NA'].Symbol.values)]
  print('qualified stocks: '+str(len(tmp_df['Symbol'].unique())))
  tmp_df1 = tmp_df[tmp_df['LatestQtr'] == 1]
  print('with latest results: '+str(len(tmp_df1['Symbol'].unique())))
  tmp_df1 = tmp_df1[tmp_df1['StarStock'] == 1]
  print('still star stocks: '+str(len(tmp_df1['Symbol'].unique())))
  tmp_df['Investment'] = tmp_df['AvgCost'] * tmp_df['Shares']
  tmp_df['Current'] = round(tmp_df['Close'] * tmp_df['Shares'],0)
  tmp_df['Previous'] = tmp_df['Prev_Close'] * tmp_df['Shares']
  tmp_df['EstimatedST'] = tmp_df['NTT'] * tmp_df['Shares']
  tmp_df['EstimatedLT'] = tmp_df['LTT'] * tmp_df['Shares']
  tmp_df['Current P/L'] = round((tmp_df['Current'] - tmp_df['Investment']),0)
  tmp_df['Today P/L%'] = round((tmp_df['Current'] - tmp_df['Previous'])*100/tmp_df['Previous'],2)
  tmp_df['Current P/L%'] = round((tmp_df['Current'] - tmp_df['Investment'])*100/tmp_df['Investment'],2)
  tmp_df['EstimatedST P/L%'] = round((tmp_df['EstimatedST'] - tmp_df['Investment'])*100/tmp_df['Investment'],2)
  tmp_df['EstimatedLT P/L%'] = round((tmp_df['EstimatedLT'] - tmp_df['Investment'])*100/tmp_df['Investment'],2)
  tmp_df['NTT%'] = round((tmp_df['NTT'] - tmp_df['Close'])*100/tmp_df['Close'],2)
  tmp_df['LTT%'] = round((tmp_df['LTT'] - tmp_df['Close'])*100/tmp_df['Close'],2)
  tmp_df['Gained%'] = round((tmp_df['Close'] - tmp_df['BOL'])*100/tmp_df['BOL'],2)
  investment = round(sum(tmp_df['AvgCost']*tmp_df['Shares']),0)
  current = round(sum(tmp_df['Close']*tmp_df['Shares']),0)
  tmp_df['InitAlloc%'] = round(tmp_df['Investment']*100/investment,2)
  tmp_df['CurrAlloc%'] = round(tmp_df['Current']*100/current,2)
  tmp_df['FTT'] = tmp_df['LTT']
  tmp_df.loc[tmp_df['Strategy'] == 'NTT', 'FTT'] = tmp_df['NTT']
  tmp_df['FTT%'] = tmp_df['LTT%']
  tmp_df.loc[tmp_df['Strategy'] == 'NTT', 'FTT%'] = tmp_df['NTT%']
  tmp_df['FTT Amt'] = round(tmp_df['FTT%'] * tmp_df['Current']/100,0)
  tmp_df['OTT%'] = round((tmp_df['FTT'] - tmp_df['AvgCost'])*100/tmp_df['AvgCost'],2)
  tmp_df['RRR Ind'] = round(tmp_df['Current P/L']/tmp_df['FTT Amt'],2)
  tmp_df['Risk Ind'] = round(tmp_df['Current P/L%']*tmp_df['CurrAlloc%'],0)

  return tmp_df

# function to print portfolio features
def print_portfolio_stats(df_portfolio_features, myinvmt_df):
  from pyxirr import xirr

  total_booked_amt, reserve_amt, cy_booked_amt, py_booked_amt = get_amt()

  dates = myinvmt_df['Date'].values
  dates = np.append(dates, datetime.date.today().strftime('%d-%b-%y'))
  investment = myinvmt_df['Investment'].values
  dates= pd.to_datetime(dates)

  current = round(sum(df_portfolio_features['Close']*df_portfolio_features['Shares']),0) + reserve_amt
  investment_xirr = np.append(investment, current)
  cagr = round(xirr(pd.DataFrame({"dates": dates, "amounts": investment_xirr}))*100,2)

  investment = -sum(investment)
  invested = round(sum(df_portfolio_features['AvgCost']*df_portfolio_features['Shares']),0) + reserve_amt
  previous = round(sum(df_portfolio_features['Prev_Close']*df_portfolio_features['Shares']),0) + reserve_amt
  cy_invested = investment + py_booked_amt

  today_pnl_amount = current-previous
  today_pnl_percentage = round((current-previous)*100/previous,2)

  curr_pnl_amount = current-invested
  curr_pnl_percentage = round((curr_pnl_amount)*100/(cy_invested),2)

  cy_pnl_amount = cy_booked_amt + curr_pnl_amount
  cy_pnl_percentage = round((cy_pnl_amount)*100/cy_invested,2)

  overall_pnl_amount = total_booked_amt + curr_pnl_amount
  overall_pnl_percentage = round((overall_pnl_amount)*100/investment,2)

  estimate_st = round(sum(df_portfolio_features['FTT']*df_portfolio_features['Shares']),0)  + reserve_amt
  est_st_pnl_amount = estimate_st-current
  est_st_pnl_percentage = round((est_st_pnl_amount)*100/current,2)

  estimate_lt = round(sum(df_portfolio_features['LTT']*df_portfolio_features['Shares']),0)  + reserve_amt
  est_lt_pnl_amount = estimate_lt-current
  est_lt_pnl_percentage = round((est_lt_pnl_amount)*100/current,2)

  total_profit = round(sum(df_portfolio_features[df_portfolio_features['Current P/L%'] > 0]['Current']) - sum(df_portfolio_features[df_portfolio_features['Current P/L%'] > 0]['Investment']),0)
  total_loss = round(sum(df_portfolio_features[df_portfolio_features['Current P/L%'] < 0]['Current']) - sum(df_portfolio_features[df_portfolio_features['Current P/L%'] < 0]['Investment']),0)

  cy_booked_percentage = round((cy_booked_amt)*100/current,2)
  py_booked_percentage = round((py_booked_amt)*100/investment,2)
  total_booked_percentage = round((total_booked_amt)*100/investment,2)

  print('-------------------')
  print('Initial Investment: ', format_amt(investment))
  print('CY Investment: ', format_amt(cy_invested))
  print('Reserve: ', format_amt(reserve_amt))
  print('Current: ',  format_amt(current))
  print('-------------------')
  print('Today PnL: '+ '{} ({}%)'.format(format_amt(today_pnl_amount), today_pnl_percentage))
  print('Current PnL: '+ '{} ({}%)'.format(format_amt(curr_pnl_amount), curr_pnl_percentage))
  print('CY Booked + Current PnL: '+ '{} ({}%)'.format(format_amt(cy_pnl_amount), cy_pnl_percentage))
  print('-------------------')
  print('Total profit: ', format_amt(total_profit))
  print('Total loss: ', format_amt(total_loss))
  print('-------------------')
  print('Total Booked + Current PnL: '+ '{} ({}%)'.format(format_amt(overall_pnl_amount), overall_pnl_percentage))
  print('Total Booked PnL: '+ '{} ({}%)'.format(format_amt(total_booked_amt), total_booked_percentage))
  print('Curr Year Booked PnL: '+ '{} ({}%)'.format(format_amt(cy_booked_amt), cy_booked_percentage))
  print('Prev Year Booked PnL: '+ '{} ({}%)'.format(format_amt(py_booked_amt), py_booked_percentage))
  print('===================')
  print('Est FTT: ',  format_amt(estimate_st))
  print('Est FTT PnL: '+ '{} ({}%)'.format(format_amt(est_st_pnl_amount), est_st_pnl_percentage))

  print('===================')
  print('Deployed: ', format_amt(investment))

  print('Current: ', format_amt(current))

  print('CAGR/XIRR %: '+'{}%'.format(cagr))

In [8]:
# get start and end date
start_date, end_date = get_start_end_date()

# get portfolio and prospects data
mypfs_df = get_mypfs_df()
mypps_df = get_mypps_df()
myinvmt_df = get_myinvmt_df()

# merge above datasets
mypf_df = pd.merge(mypfs_df, mypps_df, on="Symbol")

# seggregate dm and sv portfolio
dm_pf = mypf_df[mypf_df['InPortfolio'] == 'DM']
sv_pf = mypf_df[mypf_df['InPortfolio'] == 'SV']

# build portfolio stock dataframe
dm_stocks = get_stock_ids(dm_pf)
sv_stocks = get_stock_ids(sv_pf)
df_stocks = pd.concat([dm_pf,sv_pf], ignore_index = True)

# arrange common and diff stock features
common_cols = ['Symbol', 'Target', 'Criteria', 'Strategy', 'CumlRnk', 'LatestQtr', 'StarStock', 'Conviction', 'Category', 'InFolio', 'XIRR', 'MBQ']
diff_cols = ['Symbol', 'AvgCost', 'Shares']
df_stocks = arrange_features(df_stocks, common_cols, diff_cols)

# get common features
stock_ids = df_stocks['Symbol'].values
df_common_features = get_common_features(stock_ids, df_stocks)

df_common_features.reset_index(drop=True, inplace=True)
df_common_features.drop(['Date'], axis=1, inplace=True)
# get and print portfolio features
df_portfolio_features = get_portfolio_features(df_common_features)

print_portfolio_stats(df_portfolio_features, myinvmt_df)

df = df_portfolio_features
#plot_pie_chart(df, 'CapType', 'Current')
list_ox40n = list(df[df['MBQ'].str.contains('OX40N', na=False)]['Symbol'].values)

Run date time (IST): 2026-04-24 12:34:23
-------------------
qualified stocks: 92
with latest results: 31
still star stocks: 20
-------------------
Initial Investment:  1.40 C
CY Investment:  1.82 C
Reserve:  1.49 K
Current:  1.47 C
-------------------
Today PnL: -2.13 L (-1.43%)
Current PnL: -36.58 L (-20.06%)
CY Booked + Current PnL: -34.50 L (-18.92%)
-------------------
Total profit:  89.46 K
Total loss:  -37.47 L
-------------------
Total Booked + Current PnL: 8.37 L (6.0%)
Total Booked PnL: 44.95 L (32.22%)
Curr Year Booked PnL: 2.08 L (1.42%)
Prev Year Booked PnL: 42.87 L (30.73%)
===================
Est FTT:  2.56 C
Est FTT PnL: 1.09 C (74.29%)
===================
Deployed:  1.40 C
Current:  1.47 C
CAGR/XIRR %: 2.49%

In [9]:
# top 5 near their targets
cols = ['Symbol', 'Today P/L%', 'Current P/L%', 'FTT%', 'OTT%', 'FTT Amt', 'Current P/L', 'Current', 'FTT', 'Dev%_PE', 'RSI_14','Conviction', 'Spread%',  'CumlRnk', 'RRR Ind', 'CurrAlloc%', 'Gained%', 'Criteria', 'Strategy', 'Category']
df_tmp = df_portfolio_features[~df_portfolio_features['Symbol'].isin(['ENRIN','BLUSPRING','DIGITIDE'])]
df_tmp = df_tmp.sort_values(by = 'FTT Amt', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
55,MASFIN,-0.83,-2.89,25.19,21.57,23967.0,-2835.0,95145.0,397.04,-16.44,55.0,H-SC,2.23,167.0,-0.12,0.65,22.95,XR,ATH,FINANCE
59,PIDILITIND,-0.83,-1.47,20.13,18.37,27989.0,-2070.0,139040.0,1670.26,-31.00,54.0,X-LC,8.34,5.0,-0.07,0.95,9.17,X40,ATH,CHEMICALS
51,KOTAKBANK,0.16,-0.87,22.17,21.11,30433.0,-1202.0,137270.0,453.24,-15.04,45.0,X-LC,9.75,12.0,-0.04,0.94,4.98,X40,ATH,BANKS
83,TTKPRESTIG,-0.01,-32.41,48.08,0.09,32752.0,-32657.0,68120.0,770.00,58.16,62.0,M-SC,21.53,250.0,-1.00,0.46,21.30,OX40N,NTT,DURABLES
53,M&M,0.22,-0.89,24.49,23.38,33662.0,-1229.0,137452.0,3802.40,-15.83,43.0,X-LC,9.10,25.0,-0.04,0.94,7.50,X40N,ATH,AUTO

In [10]:
# top 5 today
df_tmp = df_portfolio_features.sort_values(by = 'Today P/L%', ascending=False)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
5,ATULAUTO,4.91,-14.32,69.89,45.57,118053.0,-28220.0,168912.0,844.0,3662.16,66.0,M-SC,3.67,248.0,-0.24,1.15,29.98,XY24,NTT,AUTO
72,SIS,1.91,-22.86,57.19,21.26,48986.0,-25378.0,85654.0,528.0,2022.28,70.0,H-SC,8.33,168.0,-0.52,0.58,27.36,OX40N,NTT,MISC
49,JSWINFRA,1.83,-4.90,22.43,16.43,47307.0,-10865.0,210909.0,342.0,-18.52,62.0,X-MC,9.28,61.0,-0.23,1.44,19.22,X40N,NTT,REALTY
29,GREENPANEL,1.81,-43.48,153.27,43.14,158590.0,-79607.0,103471.0,537.0,131.91,58.0,M-SC,21.20,225.0,-0.50,0.71,24.29,XY24,NTT,MISC
89,WHIRLPOOL,1.25,-23.14,136.70,81.92,120608.0,-26570.0,88228.0,2270.0,-55.05,70.0,M-SC,21.79,210.0,-0.22,0.60,23.93,XR,NTT,DURABLES

In [11]:
# bottom 5 today
df_tmp = df_portfolio_features.sort_values(by = 'Today P/L%', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
45,INFY,-5.73,-20.39,68.62,34.24,170935.0,-63784.0,249104.0,1972.00,-37.23,29.0,X-LC,12.68,3.0,-0.37,1.70,0.00,X40,NTT,IT
13,BSOFT,-4.35,-33.24,125.85,50.79,118178.0,-46749.0,93904.0,831.70,-14.19,47.0,H-SC,5.80,172.0,-0.40,0.64,10.74,XR,ATH,IT
79,TCS,-4.32,-29.17,78.69,26.57,258224.0,-135119.0,328154.0,4311.59,-40.02,39.0,X-LC,15.16,2.0,-0.52,2.24,2.42,X40,ATH,IT
69,SFL,-4.20,-47.80,142.60,26.63,195175.0,-125349.0,136869.0,1287.00,3.64,50.0,M-SC,15.51,242.0,-0.64,0.93,14.07,XY24,NTT,MISC
28,GODREJCP,-4.08,-1.89,34.67,32.12,50552.0,-2806.0,145808.0,1476.34,3.22,52.0,X-LC,8.99,32.0,-0.06,0.99,11.32,X40N,ATH,FMCG

In [12]:
# top 5 to exit based on CumlRnk
df_tmp = df_portfolio_features[~df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])]
df_tmp = df_tmp[(df_tmp['Current P/L%'] > -1) & (df_tmp['Current P/L%'] < 1)].sort_values(by = 'CumlRnk', ascending=False)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
63,RECLTD,-1.34,0.54,20.09,20.74,41038.0,1100.0,204270.0,446.0,11.33,61.0,M-MC,3.72,191.0,0.03,1.39,21.73,XY25,NTT,FINANCE
74,STARHEALTH,-0.56,-0.63,48.20,47.26,134644.0,-1779.0,279344.0,761.0,56.93,71.0,H-SC,4.14,173.0,-0.01,1.91,44.67,XY24,NTT,INSURANCE

In [13]:
# OX40N stocks to exit
df_tmp = df_portfolio_features[(df_portfolio_features['Symbol'].isin(list_ox40n))].sort_values(by = 'Current P/L%', ascending=False)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
25,FINCABLES,-0.45,22.10,70.29,107.91,126710.0,32624.0,180268.0,1641.55,9.59,67.0,M-SC,5.71,220.0,0.26,1.23,35.62,OX40N,ATH,CABLES
72,SIS,1.91,-22.86,57.19,21.26,48986.0,-25378.0,85654.0,528.00,2022.28,70.0,H-SC,8.33,168.0,-0.52,0.58,27.36,OX40N,NTT,MISC
16,CERA,-2.44,-30.22,77.55,23.89,95186.0,-53161.0,122742.0,9475.00,-32.70,62.0,H-SC,12.80,153.0,-0.56,0.84,17.95,OX40N,NTT,CERAMICS
83,TTKPRESTIG,-0.01,-32.41,48.08,0.09,32752.0,-32657.0,68120.0,770.00,58.16,62.0,M-SC,21.53,250.0,-1.00,0.46,21.30,OX40N,NTT,DURABLES
50,KANSAINER,-2.36,-34.59,73.47,13.47,129601.0,-93267.0,176400.0,340.00,-43.73,54.0,H-SC,17.77,162.0,-0.72,1.20,23.22,XY24,NTT,PAINTS

In [14]:
# top 5 to book for rotation
df_tmp = df_portfolio_features[(df_portfolio_features['Current P/L%'] > 20) ].sort_values(by = 'CumlRnk', ascending=False)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
25,FINCABLES,-0.45,22.1,70.29,107.91,126710.0,32624.0,180268.0,1641.55,9.59,67.0,M-SC,5.71,220.0,0.26,1.23,35.62,OX40N,ATH,CABLES

In [15]:
# top 5 to monitor for exit
df_tmp = df_portfolio_features[~df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])]
df_tmp = df_tmp[(df_tmp['Current P/L%'] > 0) ].sort_values(by = 'Dev%_PE', ascending=False)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
63,RECLTD,-1.34,0.54,20.09,20.74,41038.0,1100.0,204270.0,446.00,11.33,61.0,M-MC,3.72,191.0,0.03,1.39,21.73,XY25,NTT,FINANCE
25,FINCABLES,-0.45,22.10,70.29,107.91,126710.0,32624.0,180268.0,1641.55,9.59,67.0,M-SC,5.71,220.0,0.26,1.23,35.62,OX40N,ATH,CABLES

In [16]:
# top 5 to book for rotation from weak conviction
df_tmp = df_portfolio_features[~df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])]
df_tmp = df_tmp[~df_tmp['Criteria'].isin(['XY25','XY24','X40', 'X40N'])].sort_values(by = 'RRR Ind', ascending=False)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
25,FINCABLES,-0.45,22.10,70.29,107.91,126710.0,32624.0,180268.0,1641.55,9.59,67.0,M-SC,5.71,220.0,0.26,1.23,35.62,OX40N,ATH,CABLES
91,ZYDUSLIFE,-1.75,-1.95,38.33,35.63,78763.0,-4088.0,205486.0,1286.17,-14.86,56.0,H-MC,4.09,120.0,-0.05,1.40,9.40,AR,ATH,PHARMA
73,SONACOMS,-2.08,-2.67,42.91,39.09,42247.0,-2704.0,98455.0,804.02,-22.90,56.0,M-MC,12.70,193.0,-0.06,0.67,39.28,AR,ATH,AUTO
42,INDIAMART,-2.39,-9.43,128.24,106.72,143254.0,-11628.0,111708.0,4810.62,-59.18,49.0,H-SC,10.75,140.0,-0.08,0.76,7.32,AR,ATH,MISC
55,MASFIN,-0.83,-2.89,25.19,21.57,23967.0,-2835.0,95145.0,397.04,-16.44,55.0,H-SC,2.23,167.0,-0.12,0.65,22.95,XR,ATH,FINANCE

In [17]:
# top 5 to accumulate based on lowest RSI_14
df_tmp = df_portfolio_features[df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])].sort_values(by = 'RSI_14', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
33,HCLTECH,-3.60,-21.57,54.93,21.51,104221.0,-52190.0,189734.0,1872.35,-17.70,28.0,X-LC,7.65,8.0,-0.50,1.29,0.00,X40,ATH,IT
45,INFY,-5.73,-20.39,68.62,34.24,170935.0,-63784.0,249104.0,1972.00,-37.23,29.0,X-LC,12.68,3.0,-0.37,1.70,0.00,X40,NTT,IT
40,ICICIPRULI,-2.71,-13.82,51.69,30.73,87760.0,-27224.0,169781.0,790.00,-36.96,34.0,X-MC,13.07,78.0,-0.31,1.16,3.46,X40,ATH,INSURANCE
79,TCS,-4.32,-29.17,78.69,26.57,258224.0,-135119.0,328154.0,4311.59,-40.02,39.0,X-LC,15.16,2.0,-0.52,2.24,2.42,X40,ATH,IT
35,HDFCLIFE,-0.94,-3.01,37.31,33.18,54210.0,-4503.0,145297.0,814.30,-24.30,40.0,X-LC,17.77,31.0,-0.08,0.99,4.76,X40,ATH,INSURANCE

In [18]:
# top 5 to accumulate based on Spread and CumlRnk
df_tmp = df_portfolio_features[df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])]
df_tmp = df_tmp[(df_tmp['CumlRnk'] < 100)].sort_values(by = 'Spread%', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
84,UNITDSPR,0.33,1.87,18.55,20.77,44247.0,4386.0,238530.0,1644.00,-9.71,63.0,X-MC,5.03,64.0,0.10,1.63,13.78,X40N,NTT,BREWERIES
88,VOLTAS,-0.12,12.95,28.55,45.20,61831.0,24828.0,216570.0,1856.00,29.27,58.0,X-MC,5.42,79.0,0.40,1.48,20.63,XY25,NTT,AC
71,SIEMENS,-1.89,1.86,23.22,25.51,44017.0,3470.0,189565.0,4671.50,59.20,70.0,H-LC,5.95,51.0,0.08,1.29,33.80,AR,ATH,ELECTRICAL
65,RELIANCE,-0.99,-14.62,46.76,25.30,80232.0,-29380.0,171583.0,1952.00,-16.96,43.0,X-LC,6.08,21.0,-0.37,1.17,2.69,XY25,BTT,REFINERIES
39,ICICIGI,-1.89,-5.94,26.88,19.34,50595.0,-11885.0,188224.0,2252.93,-20.81,44.0,X-MC,6.61,66.0,-0.23,1.28,5.13,X40,ATH,INSURANCE

In [19]:
# top 5 to accumulate based on lowest Gained%
df_tmp = df_portfolio_features[df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])].sort_values(by = 'Gained%', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
45,INFY,-5.73,-20.39,68.62,34.24,170935.0,-63784.0,249104.0,1972.00,-37.23,29.0,X-LC,12.68,3.0,-0.37,1.70,0.00,X40,NTT,IT
33,HCLTECH,-3.60,-21.57,54.93,21.51,104221.0,-52190.0,189734.0,1872.35,-17.70,28.0,X-LC,7.65,8.0,-0.50,1.29,0.00,X40,ATH,IT
1,ABBOTINDIA,0.12,-14.66,38.35,18.07,58537.0,-26215.0,152640.0,35195.00,-27.31,40.0,X-MC,11.81,58.0,-0.45,1.04,0.22,X40,ATH,PHARMA
79,TCS,-4.32,-29.17,78.69,26.57,258224.0,-135119.0,328154.0,4311.59,-40.02,39.0,X-LC,15.16,2.0,-0.52,2.24,2.42,X40,ATH,IT
65,RELIANCE,-0.99,-14.62,46.76,25.30,80232.0,-29380.0,171583.0,1952.00,-16.96,43.0,X-LC,6.08,21.0,-0.37,1.17,2.69,XY25,BTT,REFINERIES

In [20]:
# top 5 to accumulate based on lowest CurrAlloc%
df_tmp = df_portfolio_features[df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])].sort_values(by = 'CurrAlloc%', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
64,RELAXO,-2.68,-60.98,290.35,52.31,164451.0,-88521.0,56639.0,1176.00,-58.47,52.0,X-SC,29.86,92.0,-0.54,0.39,26.64,X40N,NTT,FOOTWEAR
10,BATAINDIA,-2.34,-52.43,184.24,35.20,112762.0,-67466.0,61204.0,2096.00,-19.71,53.0,X-SC,29.41,91.0,-0.60,0.42,21.38,X40,NTT,FOOTWEAR
60,QUESS,-1.91,-22.48,124.33,73.90,102928.0,-24007.0,82786.0,424.00,-58.13,50.0,X-SC,17.46,80.0,-0.23,0.56,11.37,XY24,NTT,MISC
53,M&M,0.22,-0.89,24.49,23.38,33662.0,-1229.0,137452.0,3802.40,-15.83,43.0,X-LC,9.10,25.0,-0.04,0.94,7.50,X40N,ATH,AUTO
51,KOTAKBANK,0.16,-0.87,22.17,21.11,30433.0,-1202.0,137270.0,453.24,-15.04,45.0,X-LC,9.75,12.0,-0.04,0.94,4.98,X40,ATH,BANKS

In [21]:
# top 5 to accumulate based on CumlRnk
df_tmp = df_portfolio_features.sort_values(by = 'CumlRnk', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
47,ITC,-0.56,-20.03,48.88,19.06,132966.0,-68140.0,272026.0,452.00,-55.92,50.0,X-LC,18.30,1.0,-0.51,1.86,5.53,X40,NTT,FMCG
79,TCS,-4.32,-29.17,78.69,26.57,258224.0,-135119.0,328154.0,4311.59,-40.02,39.0,X-LC,15.16,2.0,-0.52,2.24,2.42,X40,ATH,IT
45,INFY,-5.73,-20.39,68.62,34.24,170935.0,-63784.0,249104.0,1972.00,-37.23,29.0,X-LC,12.68,3.0,-0.37,1.70,0.00,X40,NTT,IT
81,TMPV,-0.84,-20.56,71.92,36.58,203311.0,-73151.0,282690.0,600.00,-83.62,55.0,X-LC,7.82,4.0,-0.36,1.93,17.83,XY24,NTT,AUTO
59,PIDILITIND,-0.83,-1.47,20.13,18.37,27989.0,-2070.0,139040.0,1670.26,-31.00,54.0,X-LC,8.34,5.0,-0.07,0.95,9.17,X40,ATH,CHEMICALS

In [22]:
# top 5 for average up
df_tmp = df_portfolio_features[(df_portfolio_features['Dev%_200'] > 5)].sort_values(by = 'CurrAlloc%', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
73,SONACOMS,-2.08,-2.67,42.91,39.09,42247.0,-2704.0,98455.0,804.02,-22.90,56.0,M-MC,12.70,193.0,-0.06,0.67,39.28,AR,ATH,AUTO
75,SURYODAY,-0.52,-17.52,49.17,23.03,72622.0,-31375.0,147696.0,216.00,60.09,61.0,H-SC,3.52,166.0,-0.43,1.01,25.96,XR,NTT,BANKS
5,ATULAUTO,4.91,-14.32,69.89,45.57,118053.0,-28220.0,168912.0,844.00,3662.16,66.0,M-SC,3.67,248.0,-0.24,1.15,29.98,XY24,NTT,AUTO
25,FINCABLES,-0.45,22.10,70.29,107.91,126710.0,32624.0,180268.0,1641.55,9.59,67.0,M-SC,5.71,220.0,0.26,1.23,35.62,OX40N,ATH,CABLES
71,SIEMENS,-1.89,1.86,23.22,25.51,44017.0,3470.0,189565.0,4671.50,59.20,70.0,H-LC,5.95,51.0,0.08,1.29,33.80,AR,ATH,ELECTRICAL

In [23]:
# top 5 RSP
df_tmp = df_portfolio_features.sort_values(by = 'RSP', ascending=False)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
61,RAJESHEXPO,-3.26,-75.95,316.06,0.07,104275.0,-104185.0,32992.0,518.0,1109.60,58.0,L-SC,38.09,268.0,-1.00,0.23,54.89,OX40N,NTT,JEWELLERY
62,RAJOOENG,-1.82,-30.99,102.29,39.61,72360.0,-31760.0,70740.0,143.1,-53.34,66.0,H-SC,25.25,136.0,-0.44,0.48,51.54,AR,ATH,MISC
71,SIEMENS,-1.89,1.86,23.22,25.51,44017.0,3470.0,189565.0,4671.5,59.20,70.0,H-LC,5.95,51.0,0.08,1.29,33.80,AR,ATH,ELECTRICAL
87,VBL,-0.24,-2.41,38.85,35.50,119743.0,-7624.0,308218.0,670.8,-13.85,67.0,X-LC,7.00,13.0,-0.06,2.10,26.56,X40N,ATH,FMCG
50,KANSAINER,-2.36,-34.59,73.47,13.47,129601.0,-93267.0,176400.0,340.0,-43.73,54.0,H-SC,17.77,162.0,-0.72,1.20,23.22,XY24,NTT,PAINTS

In [24]:
# Top N allocation
df_tmp = df_portfolio_features.sort_values(by = 'CurrAlloc%', ascending=False)
top_n_values = [10, 25, 50]

sum_df = pd.DataFrame({
    'Top_N': top_n_values,
    'Sum_Alloc%': [df_tmp['CurrAlloc%'].head(n).sum() for n in top_n_values]
})

sum_df

   Top_N  Sum_Alloc%
0     10       18.92
1     25       42.72
2     50       72.79

In [25]:
# market-cap-wise allocation
df_tmp = df_portfolio_features[cols]
df_tmp.groupby(df_tmp['Conviction'].str[-2:])['CurrAlloc%'].sum().sort_values(ascending=False)

Conviction
SC    41.71
LC    31.90
MC    26.40
Name: CurrAlloc%, dtype: float64

In [26]:
# criteria-wise allocation
df_portfolio_features.groupby('Criteria')['CurrAlloc%'].sum().sort_values(ascending=False)

Criteria
XY24     26.52
X40      26.01
X40N     17.08
XR        8.95
XY25      7.09
OX40N     6.81
AR        6.78
SR        0.77
Name: CurrAlloc%, dtype: float64

In [27]:
# conviction-wise allocation
df_portfolio_features.groupby('Conviction')['CurrAlloc%'].sum().sort_values(ascending=False)

Conviction
X-LC    29.67
X-MC    21.41
H-SC    21.41
M-SC     9.98
X-SC     9.75
H-MC     2.60
M-MC     2.06
H-LC     1.29
M-LC     0.94
L-SC     0.57
L-MC     0.33
Name: CurrAlloc%, dtype: float64

In [28]:
# sector-wise stats
df_tmp = df_portfolio_features.groupby('Category')[['CurrAlloc%', 'Current', 'Current P/L', 'FTT Amt']].sum().sort_values(by=['Current', 'Current P/L'], ascending=False)
df_tmp['Current P/L%'] = round(df_tmp['Current P/L'] * 100 / df_tmp['Current'], 2)
df_tmp['FTT%'] = round(df_tmp['FTT Amt'] * 100 / df_tmp['Current'], 2)
cols = ['CurrAlloc%', 'Current P/L%', 'FTT%']
df_tmp[cols].sort_values(by=['CurrAlloc%'], ascending=False)

               CurrAlloc%  Current P/L%    FTT%
Category
FMCG                15.73        -14.83   55.36
FINANCE             10.80        -16.54   67.23
IT                  10.51        -46.08  120.06
MISC                 6.89        -32.49   90.05
AUTO                 6.67        -12.06   54.07
BANKS                5.35        -16.05   69.72
INSURANCE            5.34         -5.80   41.81
PAINTS               5.15        -30.54   53.20
PHARMA               4.88         -3.59   36.89
ELECTRICAL           4.16        -15.92   57.18
AC                   2.01         -8.79   38.28
CHEMICALS            1.97        -40.41  124.09
HEALTHCARE           1.86        -30.86   65.02
APPARELS             1.80         -1.89   36.64
DURABLES             1.78        -47.94   83.93
FOOTWEAR             1.76        -71.50  140.27
TRAVEL               1.71        -78.28  167.54
BREWERIES            1.63          1.84   18.55
REALTY               1.44         -5.15   22.43
CERAMICS             1.31        -59.96  108.56
CABLES               1.23         18.10   70.29
REFINERIES           1.17        -17.12   46.76
CEMENT               1.15        -59.51  178.84
ENGINEERING          1.13        -45.80  112.49
JEWELLERY            1.06       -106.78  178.62
ENTERTAINMENT        0.75        -74.84  179.12
TEXTILES             0.43        -46.76   88.61
HOTELS               0.34       -125.38  204.88

In [29]:
# money to be made criteria-wise
df_portfolio_features.groupby('Criteria')['FTT Amt'].agg(['sum', 'count']).sort_values(by='sum', ascending=False)

                sum  count
Criteria
XY24      3708785.0     21
X40       1891794.0     19
XR        1367979.0     13
X40N      1224006.0     13
AR        1195229.0      9
OX40N      795770.0     10
XY25       402122.0      5
SR         305573.0      2

In [30]:
# money to be made conviction-wise
df_portfolio_features.groupby('Conviction')['FTT Amt'].agg(['sum', 'count']).sort_values(by='sum', ascending=False)

                  sum  count
Conviction
H-SC        3653186.0     24
X-LC        1953015.0     21
X-MC        1595948.0     15
M-SC        1454231.0     14
X-SC        1376261.0      9
H-MC         316099.0      2
L-SC         207496.0      2
M-LC         153390.0      1
M-MC          83285.0      2
L-MC          54330.0      1
H-LC          44017.0      1

In [31]:
# money to be made criteria and conviction-wise
df_portfolio_features.groupby(['Conviction', 'Criteria'])['FTT Amt'].agg(['sum', 'count']).sort_values(by='sum', ascending=False)

                           sum  count
Conviction Criteria
H-SC       XY24      1212211.0      6
X-LC       X40       1030308.0     10
H-SC       AR         954152.0      5
M-SC       XY24       857899.0      6
H-SC       XR         833727.0      7
X-SC       XY24       816762.0      4
X-MC       X40        662362.0      7
           X40N       471675.0      4
X-LC       X40N       391956.0      6
X-SC       X40N       360375.0      3
H-SC       OX40N      347523.0      4
M-SC       OX40N      343972.0      5
X-LC       XY24       342270.0      2
H-SC       SR         305573.0      2
X-MC       XY24       242307.0      2
H-MC       XY24       237336.0      1
X-MC       XY25       219604.0      2
X-SC       X40        199124.0      2
M-SC       XR         176310.0      2
M-LC       XR         153390.0      1
X-LC       XY25       141480.0      2
L-SC       OX40N      104275.0      1
           XR         103221.0      1
H-MC       AR          78763.0      1
M-SC       AR          76050.0      1
L-MC       XR          54330.0      1
X-LC       XR          47001.0      1
H-LC       AR          44017.0      1
M-MC       AR          42247.0      1
           XY25        41038.0      1

In [32]:
# notebook execution time

end_time = time.time()
execution_time = round(end_time - start_time, 0)
print(f"Notebook execution time: {execution_time} seconds")

Notebook execution time: 25.0 seconds