<a href="https://colab.research.google.com/github/ankit-rathi/Quantvesting_v2/blob/main/myStocks_Portfolio_Analysis.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
'''
!pip install pandas==2.2.2 -qq
!pip install pyxirr -qq
!pip install ta -qq
!pip install yfinance==0.2.59 -qq
'''

'\n!pip install pandas==2.2.2 -qq\n!pip install pyxirr -qq\n!pip install ta -qq\n!pip install yfinance==0.2.59 -qq\n'

In [2]:
# import libraries

import numpy as np
import pandas as pd
import datetime
import warnings
warnings.filterwarnings('ignore')
import yfinance as yfin
import ta
import matplotlib.pyplot as plt
import requests

In [3]:
# notebook start time
import time
import datetime
import pytz

start_time = time.time()

# function to print date timestamp
def print_date_time():
  tz_NY = pytz.timezone('Asia/Kolkata')
  datetime_NY = datetime.datetime.now(tz_NY)
  print("Run date time (IST):", datetime_NY.strftime("%Y-%m-%d %H:%M:%S"))

In [4]:
# function to get booked and reserved amount
def get_amt():
  # fetch the JSON data from the URL
  url = "https://raw.githubusercontent.com/ankit-rathi/Tradevesting_v1/main/data/myPortfolioAmts.json"
  response = requests.get(url)
  pf_amts = response.json()  # parse the JSON data

  # extract values from the JSON
  py_booked_amt_dm = pf_amts["py_booked_amt_dm"]
  py_booked_amt_sv = pf_amts["py_booked_amt_sv"]
  cy_booked_amt_dm = pf_amts["cy_booked_amt_dm"]
  cy_booked_amt_sv = pf_amts["cy_booked_amt_sv"]
  reserve_amt_dm = pf_amts["reserve_amt_dm"]
  reserve_amt_sv = pf_amts["reserve_amt_sv"]

  # perform calculations
  py_booked_amt = py_booked_amt_dm + py_booked_amt_sv
  cy_booked_amt = cy_booked_amt_dm + cy_booked_amt_sv
  reserve_amt = reserve_amt_dm + reserve_amt_sv
  total_booked_amt = py_booked_amt + cy_booked_amt

  return total_booked_amt, reserve_amt, cy_booked_amt, py_booked_amt

gen_output = 0

In [5]:
# function to format the amount
def format_amt(number):
    abs_number = abs(number)

    if abs_number >= 1_00_00_000:  # Crores
        formatted_amt = f"{number / 1_00_00_000:.2f} C"
    elif abs_number >= 1_00_000:  # Lakhs
        formatted_amt = f"{number / 1_00_000:.2f} L"
    elif abs_number >= 1_000:  # Thousands
        formatted_amt = f"{number / 1_000:.2f} K"
    else:
        formatted_amt = f"{number:.2f}"

    return formatted_amt

# function to set start and end date
def get_start_end_date():
  start_date = (datetime.date.today() + datetime.timedelta(days=-365)).strftime('%Y-%m-%d')
  end_date = (datetime.date.today() + datetime.timedelta(days=1)).strftime('%Y-%m-%d')
  return start_date, end_date

# function to fetch my portfolio csv
def get_mypfs_df():
  mypfs_df = pd.read_csv('https://raw.githubusercontent.com/ankit-rathi/Tradevesting_v1/main/data/myPortfolioStocks.csv')
  return mypfs_df

# function to fetch my prospects csv
def get_mypps_df():
  mypps_df = pd.read_csv('https://raw.githubusercontent.com/ankit-rathi/Tradevesting_v1/main/data/myProspectsScrips.csv')
  return mypps_df

# function to fetch screener data
def get_myscreen_df():
  myscreen_df = pd.read_csv('https://raw.githubusercontent.com/ankit-rathi/Tradevesting_v1/main/data/myScreenerDB.csv')
  return myscreen_df

# function to fetch momentum data
def get_myinvmt_df():
  myinvmt_df = pd.read_csv('https://raw.githubusercontent.com/ankit-rathi/Tradevesting_v1/main/data/myInvestments.csv')
  return myinvmt_df

# function to get the stock ids
def get_stock_ids(df_pf):
  stock_n100 = df_pf['Symbol'].unique()

  exclude = ['CADILAHC','MMTC', 'MASFIN']

  stock_ids = df_pf[~df_pf['Symbol'].isin(exclude) ]['Symbol'].unique()

  #mypf = mypf[mypf.Forecast.notnull()]
  #stock_ids = mypf['Symbol'].unique()

  #stock_ids.sort()
  return stock_ids

# get features from screener data
def get_screener_features():
  myscreen_df = get_myscreen_df()
  cols = ['Symbol', 'EPS', 'MedPE', 'ROCE%', 'ROE%', 'CapType']
  return myscreen_df[cols]

# get relative strength
def get_relative_strength(stock_list):

    # Dictionary to store stock tickers and their corresponding percentage price change
    stock_changes = {}

    # Loop through each stock and fetch its price data
    for stock in stock_list:
        try:
            # Download the stock data for the given date range
            stock_data = yfin.Ticker(stock + '.NS').history(period='1mo', interval='1d')[map(str.title, ['open', 'close', 'low', 'high', 'volume'])]

            # Calculate the percentage change for the stock
            if len(stock_data) > 0:
                start_price = stock_data['Close'].iloc[0]
                end_price = stock_data['Close'].iloc[-1]
                percent_change = round(((end_price - start_price) / start_price) * 100, 2)
                stock_changes[stock] = percent_change
            else:
                stock_changes[stock] = np.nan  # If no data is available, set to NaN

        except Exception as e:
            print(f"Error fetching data for {stock}: {e}")
            stock_changes[stock] = np.nan

    # Create a DataFrame with stock tickers and their percentage changes
    df = pd.DataFrame(list(stock_changes.items()), columns=['Symbol', 'Percent_Change'])

    # Drop any stocks with missing data (NaN values)
    df = df.dropna()

    # Calculate the percentile rank based on percentage change
    df['RSP'] = round(df['Percent_Change'].rank(pct=True) * 100, 2)
    cols = ['Symbol', 'RSP']
    df = df[cols]
    # Sort by percentile rank (optional)
    df = df.sort_values(by='RSP', ascending=False).reset_index(drop=True)

    return df

In [6]:
# function to get stock technicals
def stock_prec_dev(stock_symbol):
    #stock_symbol = 'ULTRACEMCO.NS'
    short_window = 20
    mid_window = 50
    long_window = 200
    moving_avg = 'SMA'

    start = datetime.datetime(*map(int, start_date.split('-')))
    end = datetime.datetime(*map(int, end_date.split('-')))

    stock_df = yfin.Ticker(stock_symbol + '.NS').history(period='max', interval='1d')[map(str.title, ['open', 'close', 'low', 'high', 'volume'])]

    stock_df['Max'] = round(max(stock_df['Close']),2)
    stock_df = stock_df[(stock_df.index <= end_date) & (stock_df.index >= start_date)]
    stock_df['200_SMA'] = round(stock_df['Close'].rolling(window = 200, min_periods = 1).mean(),0)
    stock_df['Dev%_200'] = round((stock_df['Close'] - stock_df['200_SMA'])*100/stock_df['200_SMA'],2)
    stock_df.dropna(axis = 0, inplace = True) # remove any null rows

    stock_df['20_SMA'] = stock_df['Close'].rolling(window=20).mean()
    stock_df['50_SMA'] = stock_df['Close'].rolling(window=50).mean()
    stock_df['Symbol'] = stock_symbol

    stock_df['Close'] = round(stock_df['Close'],2)
    stock_df['Min'] = round(min(stock_df['Close']),2)
    stock_df['RSI_14'] = ta.momentum.RSIIndicator(close=stock_df['Close'], window=14).rsi()
    stock_df['RSI_14'] = round(stock_df['RSI_14'],0)
    stock_df['Prev_Close'] = stock_df['Close'].shift(1)
    stock_df.drop(['Open', 'Low', 'High', 'Volume'], axis=1, inplace=True)
    stock_df = stock_df.tail(1)

    max_SMA = max(stock_df['20_SMA'].item(), stock_df['50_SMA'].item(), stock_df['200_SMA'].item())
    min_SMA = min(stock_df['20_SMA'].item(), stock_df['50_SMA'].item(), stock_df['200_SMA'].item())
    ABS_Spread = max_SMA - min_SMA
    stock_df['Spread%'] = round((ABS_Spread / stock_df['200_SMA'].item()) * 100,2)

    return stock_df

# function to compute stock attributes
def get_common_features(stock_ids, df_mypf):

  df_prec_dev = pd.DataFrame()
  df_tmp = get_screener_features()
  df_rs = get_relative_strength(stock_ids)

  for stock_id in stock_ids:
      tmp = stock_prec_dev(stock_id)
      tmp = tmp.reset_index()
      df_prec_dev = pd.concat([df_prec_dev, tmp], ignore_index = True)
  df_prec_dev = pd.merge(df_prec_dev, df_mypf, on= 'Symbol')
  df_prec_dev = pd.merge(df_prec_dev, df_tmp, on= 'Symbol', how='left')
  df_prec_dev = pd.merge(df_prec_dev, df_rs, on= 'Symbol', how='left')
  #print(df_prec_dev.columns)
  df_prec_dev['Curr_PE'] = round(df_prec_dev['Close']/df_prec_dev['EPS'],1)
  df_prec_dev['Dev%_PE'] = round((df_prec_dev['Curr_PE'] - df_prec_dev['MedPE'])*100/df_prec_dev['MedPE'],2)
  df_prec_dev['Conviction'] = df_prec_dev['Conviction'] + '-' + df_prec_dev['CapType']
  return df_prec_dev

# function to arrange stock features
def arrange_features(df_stocks, common_cols, diff_cols):
  df_stocks_common = df_stocks[common_cols].drop_duplicates()
  df_stocks_diff = df_stocks[diff_cols]
  df_stocks_diff['Investment'] = df_stocks_diff['AvgCost'] * df_stocks_diff['Shares']
  df_stocks_diff = df_stocks_diff.groupby(['Symbol'])[['Shares', 'Investment']].aggregate(['sum']).reset_index()
  df_stocks_diff.columns = ['Symbol', 'Shares', 'Investment']
  df_stocks_diff['AvgCost'] = round(df_stocks_diff['Investment']/df_stocks_diff['Shares'],2)
  df_stocks = pd.merge(df_stocks_diff, df_stocks_common, on='Symbol')
  return df_stocks

# plot fact distribution across dimension
def plot_pie_chart(df, dimension, fact):
  # grouping the data by category and calculating the sum of fact for each type
  grouped_data = df.groupby(dimension)[fact].sum()

  # sorting the grouped data in descending order
  grouped_data = grouped_data.sort_values(ascending=False)

  # creating a pie chart
  grouped_data.plot.pie(autopct='%1.1f%%', startangle=90, figsize=(6, 6))

  # adding a title and displaying the plot
  plt.title(f'{dimension} {fact} Distribution')
  plt.ylabel('')  # To hide the y-label
  plt.show()

In [7]:
# function to get portfolio features

def get_portfolio_features(df_common_features):

  print_date_time()
  print('-------------------')

  #df_common_features["Target"] = df_common_features["Target"].fillna(df_common_features["Max"])
  df_common_features['NTT'] = np.where(df_common_features['Strategy']== 'NTT', df_common_features["Target"], df_common_features['Max'])
  df_common_features['LTT'] = np.where(df_common_features['Strategy']== 'BTT', df_common_features["Target"], df_common_features['Max'])
  df_common_features['BOL'] = df_common_features['Min']

  tmp_df = df_common_features[df_common_features['Symbol'].isin(mypf_df[mypf_df['InPortfolio'] != 'NA'].Symbol.values)]
  print('qualified stocks: '+str(len(tmp_df['Symbol'].unique())))
  tmp_df1 = tmp_df[tmp_df['LatestQtr'] == 1]
  print('with latest results: '+str(len(tmp_df1['Symbol'].unique())))
  tmp_df1 = tmp_df1[tmp_df1['StarStock'] == 1]
  print('still star stocks: '+str(len(tmp_df1['Symbol'].unique())))
  tmp_df['Investment'] = tmp_df['AvgCost'] * tmp_df['Shares']
  tmp_df['Current'] = round(tmp_df['Close'] * tmp_df['Shares'],0)
  tmp_df['Previous'] = tmp_df['Prev_Close'] * tmp_df['Shares']
  tmp_df['EstimatedST'] = tmp_df['NTT'] * tmp_df['Shares']
  tmp_df['EstimatedLT'] = tmp_df['LTT'] * tmp_df['Shares']
  tmp_df['Current P/L'] = round((tmp_df['Current'] - tmp_df['Investment']),0)
  tmp_df['Today P/L%'] = round((tmp_df['Current'] - tmp_df['Previous'])*100/tmp_df['Previous'],2)
  tmp_df['Current P/L%'] = round((tmp_df['Current'] - tmp_df['Investment'])*100/tmp_df['Investment'],2)
  tmp_df['EstimatedST P/L%'] = round((tmp_df['EstimatedST'] - tmp_df['Investment'])*100/tmp_df['Investment'],2)
  tmp_df['EstimatedLT P/L%'] = round((tmp_df['EstimatedLT'] - tmp_df['Investment'])*100/tmp_df['Investment'],2)
  tmp_df['NTT%'] = round((tmp_df['NTT'] - tmp_df['Close'])*100/tmp_df['Close'],2)
  tmp_df['LTT%'] = round((tmp_df['LTT'] - tmp_df['Close'])*100/tmp_df['Close'],2)
  tmp_df['Gained%'] = round((tmp_df['Close'] - tmp_df['BOL'])*100/tmp_df['BOL'],2)
  investment = round(sum(tmp_df['AvgCost']*tmp_df['Shares']),0)
  current = round(sum(tmp_df['Close']*tmp_df['Shares']),0)
  tmp_df['InitAlloc%'] = round(tmp_df['Investment']*100/investment,2)
  tmp_df['CurrAlloc%'] = round(tmp_df['Current']*100/current,2)
  tmp_df['FTT'] = tmp_df['LTT']
  tmp_df.loc[tmp_df['Strategy'] == 'NTT', 'FTT'] = tmp_df['NTT']
  tmp_df['FTT%'] = tmp_df['LTT%']
  tmp_df.loc[tmp_df['Strategy'] == 'NTT', 'FTT%'] = tmp_df['NTT%']
  tmp_df['FTT Amt'] = round(tmp_df['FTT%'] * tmp_df['Current']/100,0)
  tmp_df['OTT%'] = round((tmp_df['FTT'] - tmp_df['AvgCost'])*100/tmp_df['AvgCost'],2)
  tmp_df['RRR Ind'] = round(tmp_df['Current P/L']/tmp_df['FTT Amt'],2)
  tmp_df['Risk Ind'] = round(tmp_df['Current P/L%']*tmp_df['CurrAlloc%'],0)

  return tmp_df

# function to print portfolio features
def print_portfolio_stats(df_portfolio_features, myinvmt_df):
  from pyxirr import xirr

  total_booked_amt, reserve_amt, cy_booked_amt, py_booked_amt = get_amt()

  dates = myinvmt_df['Date'].values
  dates = np.append(dates, datetime.date.today().strftime('%d-%b-%y'))
  investment = myinvmt_df['Investment'].values
  dates= pd.to_datetime(dates)

  current = round(sum(df_portfolio_features['Close']*df_portfolio_features['Shares']),0) + reserve_amt
  investment_xirr = np.append(investment, current)
  cagr = round(xirr(pd.DataFrame({"dates": dates, "amounts": investment_xirr}))*100,2)

  investment = -sum(investment)
  invested = round(sum(df_portfolio_features['AvgCost']*df_portfolio_features['Shares']),0) + reserve_amt
  previous = round(sum(df_portfolio_features['Prev_Close']*df_portfolio_features['Shares']),0) + reserve_amt
  cy_invested = investment + py_booked_amt

  today_pnl_amount = current-previous
  today_pnl_percentage = round((current-previous)*100/previous,2)

  curr_pnl_amount = current-invested
  curr_pnl_percentage = round((curr_pnl_amount)*100/(cy_invested),2)

  cy_pnl_amount = cy_booked_amt + curr_pnl_amount
  cy_pnl_percentage = round((cy_pnl_amount)*100/cy_invested,2)

  overall_pnl_amount = total_booked_amt + curr_pnl_amount
  overall_pnl_percentage = round((overall_pnl_amount)*100/investment,2)

  estimate_st = round(sum(df_portfolio_features['FTT']*df_portfolio_features['Shares']),0)  + reserve_amt
  est_st_pnl_amount = estimate_st-current
  est_st_pnl_percentage = round((est_st_pnl_amount)*100/current,2)

  estimate_lt = round(sum(df_portfolio_features['LTT']*df_portfolio_features['Shares']),0)  + reserve_amt
  est_lt_pnl_amount = estimate_lt-current
  est_lt_pnl_percentage = round((est_lt_pnl_amount)*100/current,2)

  total_profit = round(sum(df_portfolio_features[df_portfolio_features['Current P/L%'] > 0]['Current']) - sum(df_portfolio_features[df_portfolio_features['Current P/L%'] > 0]['Investment']),0)
  total_loss = round(sum(df_portfolio_features[df_portfolio_features['Current P/L%'] < 0]['Current']) - sum(df_portfolio_features[df_portfolio_features['Current P/L%'] < 0]['Investment']),0)

  cy_booked_percentage = round((cy_booked_amt)*100/current,2)
  py_booked_percentage = round((py_booked_amt)*100/investment,2)
  total_booked_percentage = round((total_booked_amt)*100/investment,2)

  print('-------------------')
  print('Initial Investment: ', format_amt(investment))
  print('CY Investment: ', format_amt(cy_invested))
  print('Reserve: ', format_amt(reserve_amt))
  print('Current: ',  format_amt(current))
  print('-------------------')
  print('Today PnL: '+ '{} ({}%)'.format(format_amt(today_pnl_amount), today_pnl_percentage))
  print('Current PnL: '+ '{} ({}%)'.format(format_amt(curr_pnl_amount), curr_pnl_percentage))
  print('CY Booked + Current PnL: '+ '{} ({}%)'.format(format_amt(cy_pnl_amount), cy_pnl_percentage))
  print('-------------------')
  print('Total profit: ', format_amt(total_profit))
  print('Total loss: ', format_amt(total_loss))
  print('-------------------')
  print('Total Booked + Current PnL: '+ '{} ({}%)'.format(format_amt(overall_pnl_amount), overall_pnl_percentage))
  print('Total Booked PnL: '+ '{} ({}%)'.format(format_amt(total_booked_amt), total_booked_percentage))
  print('Curr Year Booked PnL: '+ '{} ({}%)'.format(format_amt(cy_booked_amt), cy_booked_percentage))
  print('Prev Year Booked PnL: '+ '{} ({}%)'.format(format_amt(py_booked_amt), py_booked_percentage))
  print('===================')
  print('Est FTT: ',  format_amt(estimate_st))
  print('Est FTT PnL: '+ '{} ({}%)'.format(format_amt(est_st_pnl_amount), est_st_pnl_percentage))

  print('===================')
  print('Deployed: ', format_amt(investment))

  print('Current: ', format_amt(current))

  print('CAGR/XIRR %: '+'{}%'.format(cagr))

In [8]:
# get start and end date
start_date, end_date = get_start_end_date()

# get portfolio and prospects data
mypfs_df = get_mypfs_df()
mypps_df = get_mypps_df()
myinvmt_df = get_myinvmt_df()

# merge above datasets
mypf_df = pd.merge(mypfs_df, mypps_df, on="Symbol")

# seggregate dm and sv portfolio
dm_pf = mypf_df[mypf_df['InPortfolio'] == 'DM']
sv_pf = mypf_df[mypf_df['InPortfolio'] == 'SV']

# build portfolio stock dataframe
dm_stocks = get_stock_ids(dm_pf)
sv_stocks = get_stock_ids(sv_pf)
df_stocks = pd.concat([dm_pf,sv_pf], ignore_index = True)

# arrange common and diff stock features
common_cols = ['Symbol', 'Target', 'Criteria', 'Strategy', 'CumlRnk', 'LatestQtr', 'StarStock', 'Conviction', 'Category', 'InFolio', 'XIRR', 'MBQ']
diff_cols = ['Symbol', 'AvgCost', 'Shares']
df_stocks = arrange_features(df_stocks, common_cols, diff_cols)

# get common features
stock_ids = df_stocks['Symbol'].values
df_common_features = get_common_features(stock_ids, df_stocks)

df_common_features.reset_index(drop=True, inplace=True)
df_common_features.drop(['Date'], axis=1, inplace=True)
# get and print portfolio features
df_portfolio_features = get_portfolio_features(df_common_features)

print_portfolio_stats(df_portfolio_features, myinvmt_df)

df = df_portfolio_features
#plot_pie_chart(df, 'CapType', 'Current')
list_ox40n = list(df[df['MBQ'].str.contains('OX40N', na=False)]['Symbol'].values)

Run date time (IST): 2026-05-25 11:57:18
-------------------
qualified stocks: 92
with latest results: 31
still star stocks: 20
-------------------
Initial Investment:  1.40 C
CY Investment:  1.82 C
Reserve:  1.49 K
Current:  1.50 C
-------------------
Today PnL: 1.51 L (1.01%)
Current PnL: -32.91 L (-18.05%)
CY Booked + Current PnL: -30.83 L (-16.91%)
-------------------
Total profit:  2.41 L
Total loss:  -35.32 L
-------------------
Total Booked + Current PnL: 12.04 L (8.63%)
Total Booked PnL: 44.95 L (32.22%)
Curr Year Booked PnL: 2.08 L (1.38%)
Prev Year Booked PnL: 42.87 L (30.73%)
===================
Est FTT:  2.55 C
Est FTT PnL: 1.05 C (69.92%)
===================
Deployed:  1.40 C
Current:  1.50 C
CAGR/XIRR %: 3.59%

In [9]:
# top 5 near their targets
cols = ['Symbol', 'Today P/L%', 'Current P/L%', 'FTT%', 'OTT%', 'FTT Amt', 'Current P/L', 'Current', 'FTT', 'Dev%_PE', 'RSI_14','Conviction', 'Spread%',  'CumlRnk', 'RRR Ind', 'CurrAlloc%', 'Gained%', 'Criteria', 'Strategy', 'Category']
df_tmp = df_portfolio_features[~df_portfolio_features['Symbol'].isin(['ENRIN','BLUSPRING','DIGITIDE'])]
df_tmp = df_tmp.sort_values(by = 'FTT Amt', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
59,PIDILITIND,0.51,5.30,12.41,18.37,18440.0,7480.0,148590.0,1670.26,-26.19,63.0,X-LC,5.40,5.0,0.41,0.99,16.67,X40,ATH,CHEMICALS
51,KOTAKBANK,2.67,5.38,14.92,21.11,21772.0,7456.0,145928.0,453.24,-9.41,61.0,X-LC,7.82,12.0,0.34,0.97,11.60,X40,ATH,BANKS
55,MASFIN,-0.26,-6.00,29.33,21.57,27013.0,-5880.0,92100.0,397.04,-19.15,37.0,H-SC,4.77,167.0,-0.22,0.61,9.78,XR,ATH,FINANCE
53,M&M,2.19,2.17,20.76,23.38,29415.0,3011.0,141692.0,3802.40,-13.39,50.0,X-LC,8.93,25.0,0.10,0.94,7.42,X40N,ATH,AUTO
17,CIPLA,0.46,13.80,18.36,34.69,32000.0,21133.0,174294.0,1663.60,-11.85,63.0,X-LC,9.92,18.0,0.66,1.16,17.88,X40N,ATH,PHARMA

In [10]:
# top 5 today
df_tmp = df_portfolio_features.sort_values(by = 'Today P/L%', ascending=False)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
80,TITAGARH,8.28,-22.80,88.78,45.74,165983.0,-55217.0,186960.0,1548.00,2.93,63.0,H-SC,10.65,175.0,-0.33,1.24,42.65,XY24,NTT,ENGINEERING
25,FINCABLES,5.97,38.40,50.22,107.91,102622.0,56700.0,204344.0,1641.55,24.30,62.0,M-SC,25.93,220.0,0.55,1.36,53.74,OX40N,ATH,CABLES
61,RAJESHEXPO,4.24,-78.36,362.50,0.07,107590.0,-107497.0,29680.0,518.00,988.38,47.0,L-SC,32.32,268.0,-1.00,0.20,39.34,OX40N,NTT,JEWELLERY
68,SATIN,3.82,20.86,25.62,51.83,85552.0,57642.0,333926.0,274.00,7.75,66.0,H-SC,32.76,159.0,0.67,2.22,62.67,XY24,NTT,FINANCE
62,RAJOOENG,3.27,-44.57,151.85,39.61,86281.0,-45680.0,56820.0,143.10,-62.56,46.0,H-SC,21.93,136.0,-0.53,0.38,21.72,AR,ATH,MISC

In [11]:
# bottom 5 today
df_tmp = df_portfolio_features.sort_values(by = 'Today P/L%', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
43,INDIGOPNTS,-3.03,-30.88,44.71,0.02,53944.0,-53907.0,120652.0,1408.00,84.15,60.0,M-SC,18.73,222.0,-1.00,0.80,36.89,OX40N,NTT,PAINTS
37,HONAUT,-2.61,-10.60,69.25,51.31,119387.0,-20438.0,172400.0,58357.33,-25.72,67.0,X-SC,11.06,90.0,-0.17,1.15,30.98,X40N,ATH,ELECTRICAL
83,TTKPRESTIG,-2.49,-31.69,46.53,0.09,32031.0,-31937.0,68840.0,770.00,59.87,53.0,M-SC,15.50,250.0,-1.00,0.46,22.58,OX40N,NTT,DURABLES
19,COLPAL,-2.29,-19.98,76.85,41.51,161954.0,-52625.0,210740.0,3726.84,-3.16,47.0,X-MC,5.54,62.0,-0.32,1.40,17.82,XY25,ATH,FMCG
87,VBL,-1.03,7.85,25.52,35.37,86928.0,24786.0,340628.0,670.16,-4.72,68.0,X-LC,10.73,13.0,0.29,2.27,40.00,X40N,ATH,FMCG

In [12]:
# top 5 to exit based on CumlRnk
df_tmp = df_portfolio_features[~df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])]
df_tmp = df_tmp[(df_tmp['Current P/L%'] > -1) & (df_tmp['Current P/L%'] < 1)].sort_values(by = 'CumlRnk', ascending=False)
df_tmp[cols].head()

Empty DataFrame
Columns: [Symbol, Today P/L%, Current P/L%, FTT%, OTT%, FTT Amt, Current P/L, Current, FTT, Dev%_PE, RSI_14, Conviction, Spread%, CumlRnk, RRR Ind, CurrAlloc%, Gained%, Criteria, Strategy, Category]
Index: []

In [13]:
# OX40N stocks to exit
df_tmp = df_portfolio_features[(df_portfolio_features['Symbol'].isin(list_ox40n))].sort_values(by = 'Current P/L%', ascending=False)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
25,FINCABLES,5.97,38.40,50.22,107.91,102622.0,56700.0,204344.0,1641.55,24.30,62.0,M-SC,25.93,220.0,0.55,1.36,53.74,OX40N,ATH,CABLES
72,SIS,-0.62,-10.41,35.35,21.26,35165.0,-11556.0,99476.0,528.00,2364.77,61.0,H-SC,15.70,168.0,-0.33,0.66,47.91,OX40N,NTT,MISC
16,CERA,1.07,-24.57,64.24,23.89,85238.0,-43216.0,132687.0,9475.00,-27.21,59.0,H-SC,7.06,153.0,-0.51,0.88,27.51,OX40N,NTT,CERAMICS
50,KANSAINER,0.69,-26.76,54.93,13.47,108489.0,-72162.0,197505.0,340.00,-37.08,63.0,H-SC,13.12,162.0,-0.67,1.31,37.96,XY24,NTT,PAINTS
43,INDIGOPNTS,-3.03,-30.88,44.71,0.02,53944.0,-53907.0,120652.0,1408.00,84.15,60.0,M-SC,18.73,222.0,-1.00,0.80,36.89,OX40N,NTT,PAINTS

In [14]:
# top 5 to book for rotation
df_tmp = df_portfolio_features[(df_portfolio_features['Current P/L%'] > 20) ].sort_values(by = 'CumlRnk', ascending=False)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
25,FINCABLES,5.97,38.40,50.22,107.91,102622.0,56700.0,204344.0,1641.55,24.30,62.0,M-SC,25.93,220.0,0.55,1.36,53.74,OX40N,ATH,CABLES
68,SATIN,3.82,20.86,25.62,51.83,85552.0,57642.0,333926.0,274.00,7.75,66.0,H-SC,32.76,159.0,0.67,2.22,62.67,XY24,NTT,FINANCE

In [15]:
# top 5 to monitor for exit
df_tmp = df_portfolio_features[~df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])]
df_tmp = df_tmp[(df_tmp['Current P/L%'] > 0) ].sort_values(by = 'Dev%_PE', ascending=False)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
74,STARHEALTH,0.20,1.38,45.26,47.26,128992.0,3879.0,285002.0,761.00,59.94,61.0,H-SC,10.11,173.0,0.03,1.90,25.13,XY24,NTT,INSURANCE
25,FINCABLES,5.97,38.40,50.22,107.91,102622.0,56700.0,204344.0,1641.55,24.30,62.0,M-SC,25.93,220.0,0.55,1.36,53.74,OX40N,ATH,CABLES
68,SATIN,3.82,20.86,25.62,51.83,85552.0,57642.0,333926.0,274.00,7.75,66.0,H-SC,32.76,159.0,0.67,2.22,62.67,XY24,NTT,FINANCE
91,ZYDUSLIFE,2.14,11.90,21.21,35.63,49740.0,24940.0,234514.0,1286.17,-2.70,73.0,H-MC,3.72,120.0,0.50,1.56,23.30,AR,ATH,PHARMA
73,SONACOMS,0.40,3.13,34.87,39.09,36378.0,3167.0,104326.0,804.02,-18.31,58.0,M-MC,19.14,193.0,0.09,0.69,47.58,AR,ATH,AUTO

In [16]:
# top 5 to book for rotation from weak conviction
df_tmp = df_portfolio_features[~df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])]
df_tmp = df_tmp[~df_tmp['Criteria'].isin(['XY25','XY24','X40', 'X40N'])].sort_values(by = 'RRR Ind', ascending=False)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
25,FINCABLES,5.97,38.40,50.22,107.91,102622.0,56700.0,204344.0,1641.55,24.30,62.0,M-SC,25.93,220.0,0.55,1.36,53.74,OX40N,ATH,CABLES
91,ZYDUSLIFE,2.14,11.90,21.21,35.63,49740.0,24940.0,234514.0,1286.17,-2.70,73.0,H-MC,3.72,120.0,0.50,1.56,23.30,AR,ATH,PHARMA
73,SONACOMS,0.40,3.13,34.87,39.09,36378.0,3167.0,104326.0,804.02,-18.31,58.0,M-MC,19.14,193.0,0.09,0.69,47.58,AR,ATH,AUTO
42,INDIAMART,0.26,-12.54,136.36,106.72,147093.0,-15465.0,107871.0,4810.62,-60.55,48.0,H-SC,10.45,140.0,-0.11,0.72,4.43,AR,ATH,MISC
90,WIPRO,2.80,-14.36,101.16,72.27,146792.0,-24339.0,145109.0,420.00,-22.68,66.0,M-LC,13.44,98.0,-0.17,0.97,11.33,XR,NTT,IT

In [17]:
# top 5 to accumulate based on lowest RSI_14
df_tmp = df_portfolio_features[df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])].sort_values(by = 'RSI_14', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
23,DMART,-0.23,-1.26,31.26,29.60,77040.0,-3150.0,246450.0,5391.45,-16.75,33.0,X-LC,4.78,14.0,-0.04,1.64,12.65,X40N,ATH,FMCG
27,GLAXO,0.66,-6.78,49.26,39.15,91513.0,-13508.0,185776.0,3466.20,-28.86,40.0,X-MC,6.40,56.0,-0.15,1.24,2.77,X40,ATH,PHARMA
33,HCLTECH,0.75,-23.90,59.66,21.51,109842.0,-57810.0,184114.0,1872.35,-20.18,40.0,X-LC,18.66,8.0,-0.53,1.23,4.33,X40,ATH,IT
7,BAJAJHFL,0.06,-25.75,118.36,62.13,239951.0,-70316.0,202730.0,181.50,-38.88,41.0,X-MC,13.85,60.0,-0.29,1.35,13.72,X40N,ATH,FINANCE
58,PGHH,0.98,-27.47,82.01,32.01,127004.0,-58656.0,154864.0,17616.87,-50.89,41.0,X-MC,17.65,57.0,-0.46,1.03,5.92,X40,ATH,FMCG

In [18]:
# top 5 to accumulate based on Spread and CumlRnk
df_tmp = df_portfolio_features[df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])]
df_tmp = df_tmp[(df_tmp['CumlRnk'] < 100)].sort_values(by = 'Spread%', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
88,VOLTAS,1.66,0.85,43.97,45.20,85029.0,1638.0,193380.0,1856.00,15.45,44.0,X-MC,3.37,79.0,0.02,1.29,5.65,XY25,NTT,AC
84,UNITDSPR,0.57,-5.28,27.50,20.77,60989.0,-12367.0,221777.0,1644.00,-16.02,48.0,X-MC,3.52,64.0,-0.20,1.48,5.79,X40N,NTT,BREWERIES
65,RELIANCE,0.41,-12.70,43.53,25.30,76369.0,-25523.0,175440.0,1952.00,-15.03,47.0,X-LC,3.87,21.0,-0.33,1.17,4.25,XY25,BTT,REFINERIES
23,DMART,-0.23,-1.26,31.26,29.60,77040.0,-3150.0,246450.0,5391.45,-16.75,33.0,X-LC,4.78,14.0,-0.04,1.64,12.65,X40N,ATH,FMCG
39,ICICIGI,1.29,-2.02,21.80,19.34,42743.0,-4041.0,196068.0,2252.93,-17.63,57.0,X-MC,4.95,66.0,-0.09,1.30,9.51,X40,ATH,INSURANCE

In [19]:
# top 5 to accumulate based on lowest Gained%
df_tmp = df_portfolio_features[df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])].sort_values(by = 'Gained%', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
27,GLAXO,0.66,-6.78,49.26,39.15,91513.0,-13508.0,185776.0,3466.20,-28.86,40.0,X-MC,6.40,56.0,-0.15,1.24,2.77,X40,ATH,PHARMA
32,HAVELLS,0.67,-22.59,69.78,31.42,177164.0,-74101.0,253890.0,2052.62,-27.23,44.0,X-MC,12.45,63.0,-0.42,1.69,2.92,X40,ATH,ELECTRICAL
28,GODREJCP,-1.02,-8.99,44.45,31.47,60124.0,-13353.0,135261.0,1469.04,-4.32,42.0,X-LC,8.60,32.0,-0.22,0.90,3.78,X40N,ATH,FMCG
79,TCS,0.98,-32.23,84.26,24.88,264562.0,-149290.0,313983.0,4253.91,-42.64,43.0,X-LC,17.22,2.0,-0.56,2.09,4.19,X40,ATH,IT
40,ICICIPRULI,0.89,-13.17,50.56,30.73,86484.0,-25953.0,171052.0,790.00,-36.50,45.0,X-MC,11.95,78.0,-0.30,1.14,4.23,X40,ATH,INSURANCE

In [20]:
# top 5 to accumulate based on lowest CurrAlloc%
df_tmp = df_portfolio_features[df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])].sort_values(by = 'CurrAlloc%', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
10,BATAINDIA,1.18,-55.08,201.02,35.20,116175.0,-70877.0,57793.0,2096.00,-24.19,45.0,X-SC,25.66,91.0,-0.61,0.38,14.62,X40,NTT,FOOTWEAR
64,RELAXO,1.89,-61.15,292.07,52.31,164701.0,-88769.0,56391.0,1176.00,-58.67,53.0,X-SC,24.90,92.0,-0.54,0.38,26.08,X40N,NTT,FOOTWEAR
60,QUESS,0.84,-16.15,107.40,73.90,96171.0,-17248.0,89545.0,424.00,-54.82,52.0,X-SC,10.43,80.0,-0.18,0.60,22.07,XY24,NTT,MISC
28,GODREJCP,-1.02,-8.99,44.45,31.47,60124.0,-13353.0,135261.0,1469.04,-4.32,42.0,X-LC,8.60,32.0,-0.22,0.90,3.78,X40N,ATH,FMCG
53,M&M,2.19,2.17,20.76,23.38,29415.0,3011.0,141692.0,3802.40,-13.39,50.0,X-LC,8.93,25.0,0.10,0.94,7.42,X40N,ATH,AUTO

In [21]:
# top 5 to accumulate based on CumlRnk
df_tmp = df_portfolio_features.sort_values(by = 'CumlRnk', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
47,ITC,0.55,-20.10,49.00,19.06,133183.0,-68364.0,271802.0,452.00,-56.33,45.0,X-LC,14.92,1.0,-0.51,1.81,5.44,X40,NTT,FMCG
79,TCS,0.98,-32.23,84.26,24.88,264562.0,-149290.0,313983.0,4253.91,-42.64,43.0,X-LC,17.22,2.0,-0.56,2.09,4.19,X40,ATH,IT
45,INFY,0.21,-19.88,67.54,34.24,169323.0,-62187.0,250701.0,1972.00,-36.87,47.0,X-LC,19.01,3.0,-0.37,1.67,7.49,X40,NTT,IT
81,TMPV,2.11,-15.55,61.73,36.58,185505.0,-55331.0,300510.0,600.00,-82.53,64.0,X-LC,5.82,4.0,-0.30,2.00,25.25,XY24,NTT,AUTO
59,PIDILITIND,0.51,5.30,12.41,18.37,18440.0,7480.0,148590.0,1670.26,-26.19,63.0,X-LC,5.40,5.0,0.41,0.99,16.67,X40,ATH,CHEMICALS

In [22]:
# top 5 for average up
df_tmp = df_portfolio_features[(df_portfolio_features['Dev%_200'] > 5)].sort_values(by = 'CurrAlloc%', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
44,INDUSINDBK,1.90,-31.53,94.08,32.89,49735.0,-24342.0,52865.0,1800.00,-348.60,60.0,L-MC,8.61,258.0,-0.49,0.35,30.12,XR,NTT,BANKS
72,SIS,-0.62,-10.41,35.35,21.26,35165.0,-11556.0,99476.0,528.00,2364.77,61.0,H-SC,15.70,168.0,-0.33,0.66,47.91,OX40N,NTT,MISC
73,SONACOMS,0.40,3.13,34.87,39.09,36378.0,3167.0,104326.0,804.02,-18.31,58.0,M-MC,19.14,193.0,0.09,0.69,47.58,AR,ATH,AUTO
69,SFL,0.40,-36.93,100.76,26.63,166648.0,-96827.0,165391.0,1287.00,25.24,70.0,M-SC,11.22,242.0,-0.58,1.10,37.85,XY24,NTT,MISC
5,ATULAUTO,1.27,-15.28,71.82,45.57,119945.0,-30124.0,167008.0,844.00,3618.92,53.0,M-SC,7.47,248.0,-0.25,1.11,28.52,XY24,NTT,AUTO

In [23]:
# top 5 RSP
df_tmp = df_portfolio_features.sort_values(by = 'RSP', ascending=False)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
68,SATIN,3.82,20.86,25.62,51.83,85552.0,57642.0,333926.0,274.00,7.75,66.0,H-SC,32.76,159.0,0.67,2.22,62.67,XY24,NTT,FINANCE
69,SFL,0.40,-36.93,100.76,26.63,166648.0,-96827.0,165391.0,1287.00,25.24,70.0,M-SC,11.22,242.0,-0.58,1.10,37.85,XY24,NTT,MISC
3,ALKYLAMINE,2.64,-24.82,157.54,93.63,119585.0,-25055.0,75908.0,4546.37,-19.40,63.0,H-SC,12.78,142.0,-0.21,0.51,43.33,SR,ATH,CHEMICALS
72,SIS,-0.62,-10.41,35.35,21.26,35165.0,-11556.0,99476.0,528.00,2364.77,61.0,H-SC,15.70,168.0,-0.33,0.66,47.91,OX40N,NTT,MISC
91,ZYDUSLIFE,2.14,11.90,21.21,35.63,49740.0,24940.0,234514.0,1286.17,-2.70,73.0,H-MC,3.72,120.0,0.50,1.56,23.30,AR,ATH,PHARMA

In [24]:
# Top N allocation
df_tmp = df_portfolio_features.sort_values(by = 'CurrAlloc%', ascending=False)
top_n_values = [10, 25, 50]

sum_df = pd.DataFrame({
    'Top_N': top_n_values,
    'Sum_Alloc%': [df_tmp['CurrAlloc%'].head(n).sum() for n in top_n_values]
})

sum_df

   Top_N  Sum_Alloc%
0     10       19.40
1     25       42.68
2     50       72.93

In [25]:
# market-cap-wise allocation
df_tmp = df_portfolio_features[cols]
df_tmp.groupby(df_tmp['Conviction'].str[-2:])['CurrAlloc%'].sum().sort_values(ascending=False)

Conviction
SC    42.55
LC    31.63
MC    25.83
Name: CurrAlloc%, dtype: float64

In [26]:
# criteria-wise allocation
df_portfolio_features.groupby('Criteria')['CurrAlloc%'].sum().sort_values(ascending=False)

Criteria
XY24     27.46
X40      25.53
X40N     16.89
XR        8.89
OX40N     6.94
AR        6.84
XY25      6.60
SR        0.86
Name: CurrAlloc%, dtype: float64

In [27]:
# conviction-wise allocation
df_portfolio_features.groupby('Conviction')['CurrAlloc%'].sum().sort_values(ascending=False)

Conviction
X-LC    29.39
H-SC    22.26
X-MC    20.80
M-SC    10.05
X-SC     9.72
H-MC     2.73
M-MC     1.95
H-LC     1.27
M-LC     0.97
L-SC     0.52
L-MC     0.35
Name: CurrAlloc%, dtype: float64

In [28]:
# sector-wise stats
df_tmp = df_portfolio_features.groupby('Category')[['CurrAlloc%', 'Current', 'Current P/L', 'FTT Amt']].sum().sort_values(by=['Current', 'Current P/L'], ascending=False)
df_tmp['Current P/L%'] = round(df_tmp['Current P/L'] * 100 / df_tmp['Current'], 2)
df_tmp['FTT%'] = round(df_tmp['FTT Amt'] * 100 / df_tmp['Current'], 2)
cols = ['CurrAlloc%', 'Current P/L%', 'FTT%']
df_tmp[cols].sort_values(by=['CurrAlloc%'], ascending=False)

               CurrAlloc%  Current P/L%    FTT%
Category
FMCG                15.13        -16.42   57.45
FINANCE             10.73        -14.31   64.02
IT                  10.38        -44.55  116.82
MISC                 6.97        -28.23   83.94
AUTO                 6.72         -8.22   48.80
BANKS                5.66         -6.89   56.31
PAINTS               5.53        -18.44   39.01
INSURANCE            5.35         -2.99   38.04
PHARMA               5.06          2.52   28.81
ELECTRICAL           4.11        -14.57   55.01
CHEMICALS            2.15        -26.02  101.11
HEALTHCARE           2.05        -15.96   46.22
APPARELS             1.83          2.55   30.69
AC                   1.80        -18.22   50.28
TRAVEL               1.69        -76.21  164.44
FOOTWEAR             1.66        -77.41  148.55
DURABLES             1.61        -59.27   98.01
BREWERIES            1.48         -5.58   27.50
REALTY               1.40         -5.64   23.00
CABLES               1.36         27.75   50.22
CERAMICS             1.34        -52.53   98.86
ENGINEERING          1.24        -29.53   88.78
REFINERIES           1.17        -14.55   43.53
CEMENT               1.10        -62.37  183.85
JEWELLERY            1.05       -102.37  172.68
ENTERTAINMENT        0.71        -81.67  190.02
TEXTILES             0.41        -50.85   93.86
HOTELS               0.32       -137.13  220.77

In [29]:
# money to be made criteria-wise
df_portfolio_features.groupby('Criteria')['FTT Amt'].agg(['sum', 'count']).sort_values(by='sum', ascending=False)

                sum  count
Criteria
XY24      3472337.0     21
X40       1856334.0     19
XR        1344885.0     13
X40N      1187999.0     13
AR        1157096.0      9
OX40N      747596.0     10
XY25       449649.0      5
SR         290685.0      2

In [30]:
# money to be made conviction-wise
df_portfolio_features.groupby('Conviction')['FTT Amt'].agg(['sum', 'count']).sort_values(by='sum', ascending=False)

                  sum  count
Conviction
H-SC        3441738.0     24
X-LC        1874585.0     21
X-MC        1606763.0     15
M-SC        1405735.0     14
X-SC        1344597.0      9
H-MC         288217.0      2
L-SC         213306.0      2
M-LC         146792.0      1
M-MC          92257.0      2
L-MC          49735.0      1
H-LC          42856.0      1

In [31]:
# money to be made criteria and conviction-wise
df_portfolio_features.groupby(['Conviction', 'Criteria'])['FTT Amt'].agg(['sum', 'count']).sort_values(by='sum', ascending=False)

                           sum  count
Conviction Criteria
H-SC       XY24      1064857.0      6
X-LC       X40        990686.0     10
H-SC       AR         952060.0      5
M-SC       XY24       826836.0      6
H-SC       XR         809507.0      7
X-SC       XY24       793078.0      4
X-MC       X40        655147.0      7
           X40N       484696.0      4
X-LC       X40N       362285.0      6
X-SC       X40N       341018.0      3
X-LC       XY24       329152.0      2
H-SC       OX40N      324629.0      4
M-SC       OX40N      315377.0      5
H-SC       SR         290685.0      2
X-MC       XY25       246983.0      2
H-MC       XY24       238477.0      1
X-MC       XY24       219937.0      2
X-SC       X40        210501.0      2
M-SC       XR         187460.0      2
M-LC       XR         146792.0      1
X-LC       XY25       146787.0      2
L-SC       OX40N      107590.0      1
           XR         105716.0      1
M-SC       AR          76062.0      1
M-MC       XY25        55879.0      1
H-MC       AR          49740.0      1
L-MC       XR          49735.0      1
X-LC       XR          45675.0      1
H-LC       AR          42856.0      1
M-MC       AR          36378.0      1

In [32]:
# notebook execution time

end_time = time.time()
execution_time = round(end_time - start_time, 0)
print(f"Notebook execution time: {execution_time} seconds")

Notebook execution time: 24.0 seconds