<a href="https://colab.research.google.com/github/ankit-rathi/Quantvesting_v2/blob/main/myStocks_Portfolio_Analysis.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
'''
!pip install pandas==2.2.2 -qq
!pip install pyxirr -qq
!pip install ta -qq
!pip install yfinance==0.2.59 -qq
'''

'\n!pip install pandas==2.2.2 -qq\n!pip install pyxirr -qq\n!pip install ta -qq\n!pip install yfinance==0.2.59 -qq\n'

In [2]:
# import libraries

import numpy as np
import pandas as pd
import datetime
import warnings
warnings.filterwarnings('ignore')
import yfinance as yfin
import ta
import matplotlib.pyplot as plt
import requests

In [3]:
# notebook start time
import time
import datetime
import pytz

start_time = time.time()

# function to print date timestamp
def print_date_time():
  tz_NY = pytz.timezone('Asia/Kolkata')
  datetime_NY = datetime.datetime.now(tz_NY)
  print("Run date time (IST):", datetime_NY.strftime("%Y-%m-%d %H:%M:%S"))

In [4]:
# function to get booked and reserved amount
def get_amt():
  # fetch the JSON data from the URL
  url = "https://raw.githubusercontent.com/ankit-rathi/Tradevesting_v1/main/data/myPortfolioAmts.json"
  response = requests.get(url)
  pf_amts = response.json()  # parse the JSON data

  # extract values from the JSON
  py_booked_amt_dm = pf_amts["py_booked_amt_dm"]
  py_booked_amt_sv = pf_amts["py_booked_amt_sv"]
  cy_booked_amt_dm = pf_amts["cy_booked_amt_dm"]
  cy_booked_amt_sv = pf_amts["cy_booked_amt_sv"]
  reserve_amt_dm = pf_amts["reserve_amt_dm"]
  reserve_amt_sv = pf_amts["reserve_amt_sv"]

  # perform calculations
  py_booked_amt = py_booked_amt_dm + py_booked_amt_sv
  cy_booked_amt = cy_booked_amt_dm + cy_booked_amt_sv
  reserve_amt = reserve_amt_dm + reserve_amt_sv
  total_booked_amt = py_booked_amt + cy_booked_amt

  return total_booked_amt, reserve_amt, cy_booked_amt, py_booked_amt

gen_output = 0

In [5]:
# function to format the amount
def format_amt(number):
    abs_number = abs(number)

    if abs_number >= 1_00_00_000:  # Crores
        formatted_amt = f"{number / 1_00_00_000:.2f} C"
    elif abs_number >= 1_00_000:  # Lakhs
        formatted_amt = f"{number / 1_00_000:.2f} L"
    elif abs_number >= 1_000:  # Thousands
        formatted_amt = f"{number / 1_000:.2f} K"
    else:
        formatted_amt = f"{number:.2f}"

    return formatted_amt

# function to set start and end date
def get_start_end_date():
  start_date = (datetime.date.today() + datetime.timedelta(days=-365)).strftime('%Y-%m-%d')
  end_date = (datetime.date.today() + datetime.timedelta(days=1)).strftime('%Y-%m-%d')
  return start_date, end_date

# function to fetch my portfolio csv
def get_mypfs_df():
  mypfs_df = pd.read_csv('https://raw.githubusercontent.com/ankit-rathi/Tradevesting_v1/main/data/myPortfolioStocks.csv')
  return mypfs_df

# function to fetch my prospects csv
def get_mypps_df():
  mypps_df = pd.read_csv('https://raw.githubusercontent.com/ankit-rathi/Tradevesting_v1/main/data/myProspectsScrips.csv')
  return mypps_df

# function to fetch screener data
def get_myscreen_df():
  myscreen_df = pd.read_csv('https://raw.githubusercontent.com/ankit-rathi/Tradevesting_v1/main/data/myScreenerDB.csv')
  return myscreen_df

# function to fetch momentum data
def get_myinvmt_df():
  myinvmt_df = pd.read_csv('https://raw.githubusercontent.com/ankit-rathi/Tradevesting_v1/main/data/myInvestments.csv')
  return myinvmt_df

# function to get the stock ids
def get_stock_ids(df_pf):
  stock_n100 = df_pf['Symbol'].unique()

  exclude = ['CADILAHC','MMTC', 'MASFIN']

  stock_ids = df_pf[~df_pf['Symbol'].isin(exclude) ]['Symbol'].unique()

  #mypf = mypf[mypf.Forecast.notnull()]
  #stock_ids = mypf['Symbol'].unique()

  #stock_ids.sort()
  return stock_ids

# get features from screener data
def get_screener_features():
  myscreen_df = get_myscreen_df()
  cols = ['Symbol', 'EPS', 'MedPE', 'ROCE%', 'ROE%', 'CapType']
  return myscreen_df[cols]

# get relative strength
def get_relative_strength(stock_list):

    # Dictionary to store stock tickers and their corresponding percentage price change
    stock_changes = {}

    # Loop through each stock and fetch its price data
    for stock in stock_list:
        try:
            # Download the stock data for the given date range
            stock_data = yfin.Ticker(stock + '.NS').history(period='1mo', interval='1d')[map(str.title, ['open', 'close', 'low', 'high', 'volume'])]

            # Calculate the percentage change for the stock
            if len(stock_data) > 0:
                start_price = stock_data['Close'].iloc[0]
                end_price = stock_data['Close'].iloc[-1]
                percent_change = round(((end_price - start_price) / start_price) * 100, 2)
                stock_changes[stock] = percent_change
            else:
                stock_changes[stock] = np.nan  # If no data is available, set to NaN

        except Exception as e:
            print(f"Error fetching data for {stock}: {e}")
            stock_changes[stock] = np.nan

    # Create a DataFrame with stock tickers and their percentage changes
    df = pd.DataFrame(list(stock_changes.items()), columns=['Symbol', 'Percent_Change'])

    # Drop any stocks with missing data (NaN values)
    df = df.dropna()

    # Calculate the percentile rank based on percentage change
    df['RSP'] = round(df['Percent_Change'].rank(pct=True) * 100, 2)
    cols = ['Symbol', 'RSP']
    df = df[cols]
    # Sort by percentile rank (optional)
    df = df.sort_values(by='RSP', ascending=False).reset_index(drop=True)

    return df

In [6]:
# function to get stock technicals
def stock_prec_dev(stock_symbol):
    #stock_symbol = 'ULTRACEMCO.NS'
    short_window = 20
    mid_window = 50
    long_window = 200
    moving_avg = 'SMA'

    start = datetime.datetime(*map(int, start_date.split('-')))
    end = datetime.datetime(*map(int, end_date.split('-')))

    stock_df = yfin.Ticker(stock_symbol + '.NS').history(period='max', interval='1d')[map(str.title, ['open', 'close', 'low', 'high', 'volume'])]

    stock_df['Max'] = round(max(stock_df['Close']),2)
    stock_df = stock_df[(stock_df.index <= end_date) & (stock_df.index >= start_date)]
    stock_df['200_SMA'] = round(stock_df['Close'].rolling(window = 200, min_periods = 1).mean(),0)
    stock_df['Dev%_200'] = round((stock_df['Close'] - stock_df['200_SMA'])*100/stock_df['200_SMA'],2)
    stock_df.dropna(axis = 0, inplace = True) # remove any null rows

    stock_df['20_SMA'] = stock_df['Close'].rolling(window=20).mean()
    stock_df['50_SMA'] = stock_df['Close'].rolling(window=50).mean()
    stock_df['Symbol'] = stock_symbol

    stock_df['Close'] = round(stock_df['Close'],2)
    stock_df['Min'] = round(min(stock_df['Close']),2)
    stock_df['RSI_14'] = ta.momentum.RSIIndicator(close=stock_df['Close'], window=14).rsi()
    stock_df['RSI_14'] = round(stock_df['RSI_14'],0)
    stock_df['Prev_Close'] = stock_df['Close'].shift(1)
    stock_df.drop(['Open', 'Low', 'High', 'Volume'], axis=1, inplace=True)
    stock_df = stock_df.tail(1)

    max_SMA = max(stock_df['20_SMA'].item(), stock_df['50_SMA'].item(), stock_df['200_SMA'].item())
    min_SMA = min(stock_df['20_SMA'].item(), stock_df['50_SMA'].item(), stock_df['200_SMA'].item())
    ABS_Spread = max_SMA - min_SMA
    stock_df['Spread%'] = round((ABS_Spread / stock_df['200_SMA'].item()) * 100,2)

    return stock_df

# function to compute stock attributes
def get_common_features(stock_ids, df_mypf):

  df_prec_dev = pd.DataFrame()
  df_tmp = get_screener_features()
  df_rs = get_relative_strength(stock_ids)

  for stock_id in stock_ids:
      tmp = stock_prec_dev(stock_id)
      tmp = tmp.reset_index()
      df_prec_dev = pd.concat([df_prec_dev, tmp], ignore_index = True)
  df_prec_dev = pd.merge(df_prec_dev, df_mypf, on= 'Symbol')
  df_prec_dev = pd.merge(df_prec_dev, df_tmp, on= 'Symbol', how='left')
  df_prec_dev = pd.merge(df_prec_dev, df_rs, on= 'Symbol', how='left')
  #print(df_prec_dev.columns)
  df_prec_dev['Curr_PE'] = round(df_prec_dev['Close']/df_prec_dev['EPS'],1)
  df_prec_dev['Dev%_PE'] = round((df_prec_dev['Curr_PE'] - df_prec_dev['MedPE'])*100/df_prec_dev['MedPE'],2)
  df_prec_dev['Conviction'] = df_prec_dev['Conviction'] + '-' + df_prec_dev['CapType']
  return df_prec_dev

# function to arrange stock features
def arrange_features(df_stocks, common_cols, diff_cols):
  df_stocks_common = df_stocks[common_cols].drop_duplicates()
  df_stocks_diff = df_stocks[diff_cols]
  df_stocks_diff['Investment'] = df_stocks_diff['AvgCost'] * df_stocks_diff['Shares']
  df_stocks_diff = df_stocks_diff.groupby(['Symbol'])[['Shares', 'Investment']].aggregate(['sum']).reset_index()
  df_stocks_diff.columns = ['Symbol', 'Shares', 'Investment']
  df_stocks_diff['AvgCost'] = round(df_stocks_diff['Investment']/df_stocks_diff['Shares'],2)
  df_stocks = pd.merge(df_stocks_diff, df_stocks_common, on='Symbol')
  return df_stocks

# plot fact distribution across dimension
def plot_pie_chart(df, dimension, fact):
  # grouping the data by category and calculating the sum of fact for each type
  grouped_data = df.groupby(dimension)[fact].sum()

  # sorting the grouped data in descending order
  grouped_data = grouped_data.sort_values(ascending=False)

  # creating a pie chart
  grouped_data.plot.pie(autopct='%1.1f%%', startangle=90, figsize=(6, 6))

  # adding a title and displaying the plot
  plt.title(f'{dimension} {fact} Distribution')
  plt.ylabel('')  # To hide the y-label
  plt.show()

In [7]:
# function to get portfolio features

def get_portfolio_features(df_common_features):

  print_date_time()
  print('-------------------')

  #df_common_features["Target"] = df_common_features["Target"].fillna(df_common_features["Max"])
  df_common_features['NTT'] = np.where(df_common_features['Strategy']== 'NTT', df_common_features["Target"], df_common_features['Max'])
  df_common_features['LTT'] = np.where(df_common_features['Strategy']== 'BTT', df_common_features["Target"], df_common_features['Max'])
  df_common_features['BOL'] = df_common_features['Min']

  tmp_df = df_common_features[df_common_features['Symbol'].isin(mypf_df[mypf_df['InPortfolio'] != 'NA'].Symbol.values)]
  print('qualified stocks: '+str(len(tmp_df['Symbol'].unique())))
  tmp_df1 = tmp_df[tmp_df['LatestQtr'] == 1]
  print('with latest results: '+str(len(tmp_df1['Symbol'].unique())))
  tmp_df1 = tmp_df1[tmp_df1['StarStock'] == 1]
  print('still star stocks: '+str(len(tmp_df1['Symbol'].unique())))
  tmp_df['Investment'] = tmp_df['AvgCost'] * tmp_df['Shares']
  tmp_df['Current'] = round(tmp_df['Close'] * tmp_df['Shares'],0)
  tmp_df['Previous'] = tmp_df['Prev_Close'] * tmp_df['Shares']
  tmp_df['EstimatedST'] = tmp_df['NTT'] * tmp_df['Shares']
  tmp_df['EstimatedLT'] = tmp_df['LTT'] * tmp_df['Shares']
  tmp_df['Current P/L'] = round((tmp_df['Current'] - tmp_df['Investment']),0)
  tmp_df['Today P/L%'] = round((tmp_df['Current'] - tmp_df['Previous'])*100/tmp_df['Previous'],2)
  tmp_df['Current P/L%'] = round((tmp_df['Current'] - tmp_df['Investment'])*100/tmp_df['Investment'],2)
  tmp_df['EstimatedST P/L%'] = round((tmp_df['EstimatedST'] - tmp_df['Investment'])*100/tmp_df['Investment'],2)
  tmp_df['EstimatedLT P/L%'] = round((tmp_df['EstimatedLT'] - tmp_df['Investment'])*100/tmp_df['Investment'],2)
  tmp_df['NTT%'] = round((tmp_df['NTT'] - tmp_df['Close'])*100/tmp_df['Close'],2)
  tmp_df['LTT%'] = round((tmp_df['LTT'] - tmp_df['Close'])*100/tmp_df['Close'],2)
  tmp_df['Gained%'] = round((tmp_df['Close'] - tmp_df['BOL'])*100/tmp_df['BOL'],2)
  investment = round(sum(tmp_df['AvgCost']*tmp_df['Shares']),0)
  current = round(sum(tmp_df['Close']*tmp_df['Shares']),0)
  tmp_df['InitAlloc%'] = round(tmp_df['Investment']*100/investment,2)
  tmp_df['CurrAlloc%'] = round(tmp_df['Current']*100/current,2)
  tmp_df['FTT'] = tmp_df['LTT']
  tmp_df.loc[tmp_df['Strategy'] == 'NTT', 'FTT'] = tmp_df['NTT']
  tmp_df['FTT%'] = tmp_df['LTT%']
  tmp_df.loc[tmp_df['Strategy'] == 'NTT', 'FTT%'] = tmp_df['NTT%']
  tmp_df['FTT Amt'] = round(tmp_df['FTT%'] * tmp_df['Current']/100,0)
  tmp_df['OTT%'] = round((tmp_df['FTT'] - tmp_df['AvgCost'])*100/tmp_df['AvgCost'],2)
  tmp_df['RRR Ind'] = round(tmp_df['Current P/L']/tmp_df['FTT Amt'],2)
  tmp_df['Risk Ind'] = round(tmp_df['Current P/L%']*tmp_df['CurrAlloc%'],0)

  return tmp_df

# function to print portfolio features
def print_portfolio_stats(df_portfolio_features, myinvmt_df):
  from pyxirr import xirr

  total_booked_amt, reserve_amt, cy_booked_amt, py_booked_amt = get_amt()

  dates = myinvmt_df['Date'].values
  dates = np.append(dates, datetime.date.today().strftime('%d-%b-%y'))
  investment = myinvmt_df['Investment'].values
  dates= pd.to_datetime(dates)

  current = round(sum(df_portfolio_features['Close']*df_portfolio_features['Shares']),0) + reserve_amt
  investment_xirr = np.append(investment, current)
  cagr = round(xirr(pd.DataFrame({"dates": dates, "amounts": investment_xirr}))*100,2)

  investment = -sum(investment)
  invested = round(sum(df_portfolio_features['AvgCost']*df_portfolio_features['Shares']),0) + reserve_amt
  previous = round(sum(df_portfolio_features['Prev_Close']*df_portfolio_features['Shares']),0) + reserve_amt
  cy_invested = investment + py_booked_amt

  today_pnl_amount = current-previous
  today_pnl_percentage = round((current-previous)*100/previous,2)

  curr_pnl_amount = current-invested
  curr_pnl_percentage = round((curr_pnl_amount)*100/(cy_invested),2)

  cy_pnl_amount = cy_booked_amt + curr_pnl_amount
  cy_pnl_percentage = round((cy_pnl_amount)*100/cy_invested,2)

  overall_pnl_amount = total_booked_amt + curr_pnl_amount
  overall_pnl_percentage = round((overall_pnl_amount)*100/investment,2)

  estimate_st = round(sum(df_portfolio_features['FTT']*df_portfolio_features['Shares']),0)  + reserve_amt
  est_st_pnl_amount = estimate_st-current
  est_st_pnl_percentage = round((est_st_pnl_amount)*100/current,2)

  estimate_lt = round(sum(df_portfolio_features['LTT']*df_portfolio_features['Shares']),0)  + reserve_amt
  est_lt_pnl_amount = estimate_lt-current
  est_lt_pnl_percentage = round((est_lt_pnl_amount)*100/current,2)

  total_profit = round(sum(df_portfolio_features[df_portfolio_features['Current P/L%'] > 0]['Current']) - sum(df_portfolio_features[df_portfolio_features['Current P/L%'] > 0]['Investment']),0)
  total_loss = round(sum(df_portfolio_features[df_portfolio_features['Current P/L%'] < 0]['Current']) - sum(df_portfolio_features[df_portfolio_features['Current P/L%'] < 0]['Investment']),0)

  cy_booked_percentage = round((cy_booked_amt)*100/current,2)
  py_booked_percentage = round((py_booked_amt)*100/investment,2)
  total_booked_percentage = round((total_booked_amt)*100/investment,2)

  print('-------------------')
  print('Initial Investment: ', format_amt(investment))
  print('CY Investment: ', format_amt(cy_invested))
  print('Reserve: ', format_amt(reserve_amt))
  print('Current: ',  format_amt(current))
  print('-------------------')
  print('Today PnL: '+ '{} ({}%)'.format(format_amt(today_pnl_amount), today_pnl_percentage))
  print('Current PnL: '+ '{} ({}%)'.format(format_amt(curr_pnl_amount), curr_pnl_percentage))
  print('CY Booked + Current PnL: '+ '{} ({}%)'.format(format_amt(cy_pnl_amount), cy_pnl_percentage))
  print('-------------------')
  print('Total profit: ', format_amt(total_profit))
  print('Total loss: ', format_amt(total_loss))
  print('-------------------')
  print('Total Booked + Current PnL: '+ '{} ({}%)'.format(format_amt(overall_pnl_amount), overall_pnl_percentage))
  print('Total Booked PnL: '+ '{} ({}%)'.format(format_amt(total_booked_amt), total_booked_percentage))
  print('Curr Year Booked PnL: '+ '{} ({}%)'.format(format_amt(cy_booked_amt), cy_booked_percentage))
  print('Prev Year Booked PnL: '+ '{} ({}%)'.format(format_amt(py_booked_amt), py_booked_percentage))
  print('===================')
  print('Est FTT: ',  format_amt(estimate_st))
  print('Est FTT PnL: '+ '{} ({}%)'.format(format_amt(est_st_pnl_amount), est_st_pnl_percentage))

  print('===================')
  print('Deployed: ', format_amt(investment))

  print('Current: ', format_amt(current))

  print('CAGR/XIRR %: '+'{}%'.format(cagr))

In [8]:
# get start and end date
start_date, end_date = get_start_end_date()

# get portfolio and prospects data
mypfs_df = get_mypfs_df()
mypps_df = get_mypps_df()
myinvmt_df = get_myinvmt_df()

# merge above datasets
mypf_df = pd.merge(mypfs_df, mypps_df, on="Symbol")

# seggregate dm and sv portfolio
dm_pf = mypf_df[mypf_df['InPortfolio'] == 'DM']
sv_pf = mypf_df[mypf_df['InPortfolio'] == 'SV']

# build portfolio stock dataframe
dm_stocks = get_stock_ids(dm_pf)
sv_stocks = get_stock_ids(sv_pf)
df_stocks = pd.concat([dm_pf,sv_pf], ignore_index = True)

# arrange common and diff stock features
common_cols = ['Symbol', 'Target', 'Criteria', 'Strategy', 'CumlRnk', 'LatestQtr', 'StarStock', 'Conviction', 'Category', 'InFolio', 'XIRR', 'MBQ']
diff_cols = ['Symbol', 'AvgCost', 'Shares']
df_stocks = arrange_features(df_stocks, common_cols, diff_cols)

# get common features
stock_ids = df_stocks['Symbol'].values
df_common_features = get_common_features(stock_ids, df_stocks)

df_common_features.reset_index(drop=True, inplace=True)
df_common_features.drop(['Date'], axis=1, inplace=True)
# get and print portfolio features
df_portfolio_features = get_portfolio_features(df_common_features)

print_portfolio_stats(df_portfolio_features, myinvmt_df)

df = df_portfolio_features
#plot_pie_chart(df, 'CapType', 'Current')
list_ox40n = list(df[df['MBQ'].str.contains('OX40N', na=False)]['Symbol'].values)

Run date time (IST): 2026-07-27 15:18:51
-------------------
qualified stocks: 92
with latest results: 31
still star stocks: 20
-------------------
Initial Investment:  1.40 C
CY Investment:  1.82 C
Reserve:  1.49 K
Current:  1.52 C
-------------------
Today PnL: 1.29 L (0.86%)
Current PnL: -30.78 L (-16.88%)
CY Booked + Current PnL: -28.70 L (-15.73%)
-------------------
Total profit:  4.69 L
Total loss:  -35.47 L
-------------------
Total Booked + Current PnL: 14.17 L (10.16%)
Total Booked PnL: 44.95 L (32.22%)
Curr Year Booked PnL: 2.08 L (1.36%)
Prev Year Booked PnL: 42.87 L (30.73%)
===================
Est FTT:  2.55 C
Est FTT PnL: 1.02 C (67.2%)
===================
Deployed:  1.40 C
Current:  1.52 C
CAGR/XIRR %: 3.95%

In [9]:
# top 5 near their targets
cols = ['Symbol', 'Today P/L%', 'Current P/L%', 'FTT%', 'OTT%', 'FTT Amt', 'Current P/L', 'Current', 'FTT', 'Dev%_PE', 'RSI_14','Conviction', 'Spread%',  'CumlRnk', 'RRR Ind', 'CurrAlloc%', 'Gained%', 'Criteria', 'Strategy', 'Category']
df_tmp = df_portfolio_features[~df_portfolio_features['Symbol'].isin(['ENRIN','BLUSPRING','DIGITIDE'])]
df_tmp = df_tmp.sort_values(by = 'FTT Amt', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
59,PIDILITIND,2.74,14.37,2.75,17.52,4438.0,20280.0,161390.0,1658.32,-19.93,62.0,X-LC,8.05,5.0,4.57,1.06,27.63,X40,ATH,CHEMICALS
56,MEDANTA,2.77,20.53,5.46,27.12,11617.0,36242.0,212759.0,1486.00,16.84,71.0,X-SC,12.15,87.0,3.12,1.40,46.60,XY24,NTT,HEALTHCARE
73,SONACOMS,0.53,24.86,11.08,38.69,13995.0,25147.0,126306.0,801.69,-1.03,75.0,M-MC,26.67,193.0,1.80,0.83,79.20,AR,ATH,AUTO
83,TTKPRESTIG,1.79,-14.88,17.58,0.09,15081.0,-14992.0,85785.0,770.00,99.15,61.0,M-SC,11.79,250.0,-0.99,0.56,52.75,OX40N,NTT,DURABLES
49,JSWINFRA,-0.36,9.47,6.36,16.43,15440.0,20996.0,242770.0,342.00,-6.17,48.0,X-MC,18.81,61.0,1.36,1.59,37.64,X40N,NTT,REALTY

In [10]:
# top 5 today
df_tmp = df_portfolio_features.sort_values(by = 'Today P/L%', ascending=False)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
50,KANSAINER,5.18,-32.18,67.32,13.47,123115.0,-86787.0,182880.0,340.00,-41.65,50.0,H-SC,5.07,162.0,-0.70,1.20,29.26,XY24,NTT,PAINTS
85,VAIBHAVGBL,4.99,-18.38,96.96,60.77,144654.0,-33586.0,149189.0,521.00,71.90,64.0,H-SC,8.80,160.0,-0.23,0.98,51.79,XR,NTT,JEWELLERY
13,BSOFT,3.91,-46.80,179.30,48.59,134170.0,-65823.0,74830.0,819.60,-31.58,51.0,H-SC,22.04,172.0,-0.49,0.49,9.40,XR,ATH,IT
30,HAPPSTMNDS,3.91,-51.67,278.85,83.08,172709.0,-66229.0,61936.0,1466.54,-42.53,61.0,H-SC,12.40,152.0,-0.38,0.41,16.01,AR,ATH,IT
45,INFY,3.75,-26.49,82.61,34.24,190019.0,-82869.0,230019.0,1972.00,-42.31,51.0,X-LC,20.33,3.0,-0.44,1.51,9.60,X40,NTT,IT

In [11]:
# bottom 5 today
df_tmp = df_portfolio_features.sort_values(by = 'Today P/L%', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
75,SURYODAY,-5.01,4.48,17.76,23.03,33229.0,8028.0,187099.0,216.00,103.95,52.0,H-SC,24.33,166.0,0.24,1.23,58.81,XR,NTT,BANKS
67,ROUTE,-4.87,-58.95,309.62,68.16,169133.0,-78440.0,54626.0,2215.45,-66.75,46.0,H-SC,8.19,141.0,-0.46,0.36,30.14,SR,ATH,IT
77,TANLA,-2.54,-33.94,228.88,117.25,409368.0,-91904.0,178857.0,1922.32,-33.47,58.0,H-SC,7.03,147.0,-0.22,1.17,56.59,AR,ATH,IT
68,SATIN,-2.48,45.30,4.50,51.83,18065.0,125160.0,401444.0,274.00,30.09,57.0,H-SC,45.72,159.0,6.93,2.63,95.56,XY24,NTT,FINANCE
29,GREENPANEL,-1.41,-48.96,180.42,43.14,168606.0,-89626.0,93452.0,537.00,109.30,46.0,M-SC,13.27,225.0,-0.53,0.61,12.26,XY24,NTT,MISC

In [12]:
# top 5 to exit based on CumlRnk
df_tmp = df_portfolio_features[~df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])]
df_tmp = df_tmp[(df_tmp['Current P/L%'] > -1) & (df_tmp['Current P/L%'] < 1)].sort_values(by = 'CumlRnk', ascending=False)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
63,RECLTD,1.96,-0.19,20.97,20.74,42524.0,-385.0,202785.0,446.0,9.37,62.0,M-MC,2.24,191.0,-0.01,1.33,20.85,XY25,NTT,FINANCE
72,SIS,-0.53,-0.04,21.31,21.26,23652.0,-43.0,110989.0,528.0,2650.26,55.0,H-SC,24.30,168.0,-0.00,0.73,65.02,OX40N,NTT,MISC

In [13]:
# OX40N stocks to exit
df_tmp = df_portfolio_features[(df_portfolio_features['Symbol'].isin(list_ox40n))].sort_values(by = 'Current P/L%', ascending=False)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
25,FINCABLES,-0.03,26.48,64.39,107.91,120241.0,39094.0,186738.0,1641.55,13.65,40.0,M-SC,20.34,220.0,0.33,1.23,40.49,OX40N,ATH,CABLES
72,SIS,-0.53,-0.04,21.31,21.26,23652.0,-43.0,110989.0,528.00,2650.26,55.0,H-SC,24.30,168.0,-0.00,0.73,65.02,OX40N,NTT,MISC
83,TTKPRESTIG,1.79,-14.88,17.58,0.09,15081.0,-14992.0,85785.0,770.00,99.15,61.0,M-SC,11.79,250.0,-0.99,0.56,52.75,OX40N,NTT,DURABLES
16,CERA,3.07,-18.91,52.77,23.89,75274.0,-33257.0,142646.0,9475.00,-21.72,53.0,H-SC,14.29,153.0,-0.44,0.94,38.66,OX40N,NTT,CERAMICS
43,INDIGOPNTS,2.21,-23.84,31.33,0.02,41650.0,-41619.0,132940.0,1408.00,102.57,57.0,M-SC,3.90,222.0,-1.00,0.87,50.83,OX40N,NTT,PAINTS

In [14]:
# top 5 to book for rotation
df_tmp = df_portfolio_features[(df_portfolio_features['Current P/L%'] > 20) ].sort_values(by = 'CumlRnk', ascending=False)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
25,FINCABLES,-0.03,26.48,64.39,107.91,120241.0,39094.0,186738.0,1641.55,13.65,40.0,M-SC,20.34,220.0,0.33,1.23,40.49,OX40N,ATH,CABLES
73,SONACOMS,0.53,24.86,11.08,38.69,13995.0,25147.0,126306.0,801.69,-1.03,75.0,M-MC,26.67,193.0,1.80,0.83,79.20,AR,ATH,AUTO
68,SATIN,-2.48,45.30,4.50,51.83,18065.0,125160.0,401444.0,274.00,30.09,57.0,H-SC,45.72,159.0,6.93,2.63,95.56,XY24,NTT,FINANCE
56,MEDANTA,2.77,20.53,5.46,27.12,11617.0,36242.0,212759.0,1486.00,16.84,71.0,X-SC,12.15,87.0,3.12,1.40,46.60,XY24,NTT,HEALTHCARE
60,QUESS,0.02,21.18,43.51,73.90,56305.0,22614.0,129407.0,424.00,-34.99,65.0,X-SC,35.54,80.0,0.40,0.85,76.41,XY24,NTT,MISC

In [15]:
# top 5 to monitor for exit
df_tmp = df_portfolio_features[~df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])]
df_tmp = df_tmp[(df_tmp['Current P/L%'] > 0) ].sort_values(by = 'Dev%_PE', ascending=False)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
75,SURYODAY,-5.01,4.48,17.76,23.03,33229.0,8028.0,187099.0,216.00,103.95,52.0,H-SC,24.33,166.0,0.24,1.23,58.81,XR,NTT,BANKS
74,STARHEALTH,1.93,14.56,28.55,47.26,91945.0,40925.0,322048.0,761.00,80.81,58.0,H-SC,18.79,173.0,0.45,2.11,39.75,XY24,NTT,INSURANCE
68,SATIN,-2.48,45.30,4.50,51.83,18065.0,125160.0,401444.0,274.00,30.09,57.0,H-SC,45.72,159.0,6.93,2.63,95.56,XY24,NTT,FINANCE
25,FINCABLES,-0.03,26.48,64.39,107.91,120241.0,39094.0,186738.0,1641.55,13.65,40.0,M-SC,20.34,220.0,0.33,1.23,40.49,OX40N,ATH,CABLES
91,ZYDUSLIFE,0.01,16.93,15.89,35.51,38938.0,35471.0,245045.0,1285.01,1.80,46.0,H-MC,17.11,120.0,0.91,1.61,28.96,AR,ATH,PHARMA

In [16]:
# top 5 to book for rotation from weak conviction
df_tmp = df_portfolio_features[~df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])]
df_tmp = df_tmp[~df_tmp['Criteria'].isin(['XY25','XY24','X40', 'X40N'])].sort_values(by = 'RRR Ind', ascending=False)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
73,SONACOMS,0.53,24.86,11.08,38.69,13995.0,25147.0,126306.0,801.69,-1.03,75.0,M-MC,26.67,193.0,1.80,0.83,79.20,AR,ATH,AUTO
91,ZYDUSLIFE,0.01,16.93,15.89,35.51,38938.0,35471.0,245045.0,1285.01,1.80,46.0,H-MC,17.11,120.0,0.91,1.61,28.96,AR,ATH,PHARMA
25,FINCABLES,-0.03,26.48,64.39,107.91,120241.0,39094.0,186738.0,1641.55,13.65,40.0,M-SC,20.34,220.0,0.33,1.23,40.49,OX40N,ATH,CABLES
75,SURYODAY,-5.01,4.48,17.76,23.03,33229.0,8028.0,187099.0,216.00,103.95,52.0,H-SC,24.33,166.0,0.24,1.23,58.81,XR,NTT,BANKS
72,SIS,-0.53,-0.04,21.31,21.26,23652.0,-43.0,110989.0,528.00,2650.26,55.0,H-SC,24.30,168.0,-0.00,0.73,65.02,OX40N,NTT,MISC

In [17]:
# top 5 to accumulate based on lowest RSI_14
df_tmp = df_portfolio_features[df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])].sort_values(by = 'RSI_14', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
34,HDFCBANK,-0.48,-11.56,45.15,28.37,93790.0,-27156.0,207729.0,1073.00,-24.98,33.0,X-LC,10.54,26.0,-0.29,1.36,2.72,X40,BTT,BANKS
87,VBL,1.68,-6.09,44.15,35.37,130952.0,-19236.0,296606.0,670.16,-17.05,38.0,X-LC,6.80,13.0,-0.15,1.95,21.91,X40N,ATH,FMCG
81,TMPV,1.22,-25.39,83.07,36.58,220533.0,-90363.0,265478.0,600.00,-84.72,38.0,X-LC,7.29,4.0,-0.41,1.74,11.57,XY24,NTT,AUTO
35,HDFCLIFE,-0.41,-9.60,46.80,32.71,63378.0,-14376.0,135424.0,811.41,-29.45,41.0,X-LC,15.82,31.0,-0.23,0.89,1.74,X40,ATH,INSURANCE
65,RELIANCE,0.12,-17.87,52.56,25.30,86753.0,-35907.0,165056.0,1952.00,-20.03,43.0,X-LC,7.69,21.0,-0.41,1.08,1.64,XY25,BTT,REFINERIES

In [18]:
# top 5 to accumulate based on Spread and CumlRnk
df_tmp = df_portfolio_features[df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])]
df_tmp = df_tmp[(df_tmp['CumlRnk'] < 100)].sort_values(by = 'Spread%', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
11,BERGEPAINT,1.19,-7.14,34.95,25.32,83654.0,-18397.0,239352.0,680.00,-12.26,50.0,X-MC,1.54,68.0,-0.22,1.57,24.57,XY24,NTT,PAINTS
19,COLPAL,2.37,-18.91,72.48,39.86,154788.0,-49805.0,213560.0,3683.41,-1.82,62.0,X-MC,1.64,62.0,-0.32,1.40,20.80,XY25,ATH,FMCG
23,DMART,0.01,-3.39,34.15,29.60,82351.0,-8454.0,241146.0,5391.45,-18.53,44.0,X-LC,1.77,14.0,-0.10,1.58,10.22,X40N,ATH,FMCG
1,ABBOTINDIA,-0.70,-6.71,23.66,15.37,39479.0,-11995.0,166860.0,34390.26,-20.56,67.0,X-MC,2.44,58.0,-0.30,1.09,13.03,X40,ATH,PHARMA
17,CIPLA,-0.08,14.11,16.94,33.43,29605.0,21605.0,174766.0,1648.14,-11.85,46.0,X-LC,2.81,18.0,0.73,1.15,19.31,X40N,ATH,PHARMA

In [19]:
# top 5 to accumulate based on lowest Gained%
df_tmp = df_portfolio_features[df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])].sort_values(by = 'Gained%', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
65,RELIANCE,0.12,-17.87,52.56,25.30,86753.0,-35907.0,165056.0,1952.00,-20.03,43.0,X-LC,7.69,21.0,-0.41,1.08,1.64,XY25,BTT,REFINERIES
35,HDFCLIFE,-0.41,-9.60,46.80,32.71,63378.0,-14376.0,135424.0,811.41,-29.45,41.0,X-LC,15.82,31.0,-0.23,0.89,1.74,X40,ATH,INSURANCE
34,HDFCBANK,-0.48,-11.56,45.15,28.37,93790.0,-27156.0,207729.0,1073.00,-24.98,33.0,X-LC,10.54,26.0,-0.29,1.36,2.72,X40,BTT,BANKS
58,PGHH,0.25,-32.59,95.82,32.01,137927.0,-69576.0,143944.0,17616.87,-54.37,51.0,X-MC,19.52,57.0,-0.50,0.94,3.16,X40,ATH,FMCG
47,ITC,0.88,-24.68,58.07,19.06,148782.0,-83955.0,256211.0,452.00,-58.75,54.0,X-LC,12.57,1.0,-0.56,1.68,3.77,X40,NTT,FMCG

In [20]:
# top 5 to accumulate based on lowest CurrAlloc%
df_tmp = df_portfolio_features[df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])].sort_values(by = 'CurrAlloc%', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
10,BATAINDIA,1.39,-54.87,199.62,35.20,115905.0,-70607.0,58063.0,2096.00,-23.90,53.0,X-SC,17.22,91.0,-0.61,0.38,15.15,X40,NTT,FOOTWEAR
64,RELAXO,-0.56,-48.10,193.49,52.31,145760.0,-69828.0,75332.0,1176.00,-44.73,54.0,X-SC,9.94,92.0,-0.48,0.49,68.43,X40N,NTT,FOOTWEAR
60,QUESS,0.02,21.18,43.51,73.90,56305.0,22614.0,129407.0,424.00,-34.99,65.0,X-SC,35.54,80.0,0.40,0.85,76.41,XY24,NTT,MISC
35,HDFCLIFE,-0.41,-9.60,46.80,32.71,63378.0,-14376.0,135424.0,811.41,-29.45,41.0,X-LC,15.82,31.0,-0.23,0.89,1.74,X40,ATH,INSURANCE
51,KOTAKBANK,-0.08,2.73,17.69,20.90,25163.0,3774.0,142246.0,452.46,-12.01,49.0,X-LC,4.97,12.0,0.15,0.93,8.97,X40,ATH,BANKS

In [21]:
# top 5 to accumulate based on CumlRnk
df_tmp = df_portfolio_features.sort_values(by = 'CumlRnk', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
47,ITC,0.88,-24.68,58.07,19.06,148782.0,-83955.0,256211.0,452.00,-58.75,54.0,X-LC,12.57,1.0,-0.56,1.68,3.77,X40,NTT,FMCG
79,TCS,1.82,-32.62,84.31,24.20,263194.0,-151099.0,312174.0,4230.71,-42.97,64.0,X-LC,18.54,2.0,-0.57,2.05,16.41,X40,ATH,IT
45,INFY,3.75,-26.49,82.61,34.24,190019.0,-82869.0,230019.0,1972.00,-42.31,51.0,X-LC,20.33,3.0,-0.44,1.51,9.60,X40,NTT,IT
81,TMPV,1.22,-25.39,83.07,36.58,220533.0,-90363.0,265478.0,600.00,-84.72,38.0,X-LC,7.29,4.0,-0.41,1.74,11.57,XY24,NTT,AUTO
59,PIDILITIND,2.74,14.37,2.75,17.52,4438.0,20280.0,161390.0,1658.32,-19.93,62.0,X-LC,8.05,5.0,4.57,1.06,27.63,X40,ATH,CHEMICALS

In [22]:
# top 5 for average up
df_tmp = df_portfolio_features[(df_portfolio_features['Dev%_200'] > 5)].sort_values(by = 'CurrAlloc%', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
44,INDUSINDBK,1.00,-25.73,78.93,32.89,45260.0,-19864.0,57342.0,1800.00,-369.61,54.0,L-MC,13.80,258.0,-0.44,0.38,41.37,XR,NTT,BANKS
64,RELAXO,-0.56,-48.10,193.49,52.31,145760.0,-69828.0,75332.0,1176.00,-44.73,54.0,X-SC,9.94,92.0,-0.48,0.49,68.43,X40N,NTT,FOOTWEAR
3,ALKYLAMINE,1.57,-22.59,148.73,92.54,116243.0,-22806.0,78157.0,4520.85,-17.07,50.0,H-SC,12.51,142.0,-0.20,0.51,48.41,SR,ATH,CHEMICALS
83,TTKPRESTIG,1.79,-14.88,17.58,0.09,15081.0,-14992.0,85785.0,770.00,99.15,61.0,M-SC,11.79,250.0,-0.99,0.56,52.75,OX40N,NTT,DURABLES
72,SIS,-0.53,-0.04,21.31,21.26,23652.0,-43.0,110989.0,528.00,2650.26,55.0,H-SC,24.30,168.0,-0.00,0.73,65.02,OX40N,NTT,MISC

In [23]:
# top 5 RSP
df_tmp = df_portfolio_features.sort_values(by = 'RSP', ascending=False)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
60,QUESS,0.02,21.18,43.51,73.90,56305.0,22614.0,129407.0,424.00,-34.99,65.0,X-SC,35.54,80.0,0.40,0.85,76.41,XY24,NTT,MISC
33,HCLTECH,2.01,-15.86,42.96,20.28,87445.0,-38374.0,203550.0,1853.42,-11.50,71.0,X-LC,16.35,8.0,-0.44,1.34,26.64,X40,ATH,IT
22,DIXON,-0.25,0.62,37.08,37.92,97301.0,1611.0,262409.0,18931.72,-57.19,60.0,X-MC,8.46,54.0,0.02,1.72,42.78,X40N,ATH,IT
73,SONACOMS,0.53,24.86,11.08,38.69,13995.0,25147.0,126306.0,801.69,-1.03,75.0,M-MC,26.67,193.0,1.80,0.83,79.20,AR,ATH,AUTO
30,HAPPSTMNDS,3.91,-51.67,278.85,83.08,172709.0,-66229.0,61936.0,1466.54,-42.53,61.0,H-SC,12.40,152.0,-0.38,0.41,16.01,AR,ATH,IT

In [24]:
# Top N allocation
df_tmp = df_portfolio_features.sort_values(by = 'CurrAlloc%', ascending=False)
top_n_values = [10, 25, 50]

sum_df = pd.DataFrame({
    'Top_N': top_n_values,
    'Sum_Alloc%': [df_tmp['CurrAlloc%'].head(n).sum() for n in top_n_values]
})

sum_df

   Top_N  Sum_Alloc%
0     10       19.24
1     25       42.37
2     50       72.70

In [25]:
# market-cap-wise allocation
df_tmp = df_portfolio_features[cols]
df_tmp.groupby(df_tmp['Conviction'].str[-2:])['CurrAlloc%'].sum().sort_values(ascending=False)

Conviction
SC    43.35
LC    30.29
MC    26.35
Name: CurrAlloc%, dtype: float64

In [26]:
# criteria-wise allocation
df_portfolio_features.groupby('Criteria')['CurrAlloc%'].sum().sort_values(ascending=False)

Criteria
XY24     27.33
X40      24.93
X40N     17.42
XR        8.92
OX40N     7.00
AR        6.98
XY25      6.54
SR        0.87
Name: CurrAlloc%, dtype: float64

In [27]:
# conviction-wise allocation
df_portfolio_features.groupby('Conviction')['CurrAlloc%'].sum().sort_values(ascending=False)

Conviction
X-LC    28.26
H-SC    22.73
X-MC    21.14
X-SC    10.19
M-SC     9.90
H-MC     2.67
M-MC     2.16
H-LC     1.22
M-LC     0.81
L-SC     0.53
L-MC     0.38
Name: CurrAlloc%, dtype: float64

In [28]:
# sector-wise stats
df_tmp = df_portfolio_features.groupby('Category')[['CurrAlloc%', 'Current', 'Current P/L', 'FTT Amt']].sum().sort_values(by=['Current', 'Current P/L'], ascending=False)
df_tmp['Current P/L%'] = round(df_tmp['Current P/L'] * 100 / df_tmp['Current'], 2)
df_tmp['FTT%'] = round(df_tmp['FTT Amt'] * 100 / df_tmp['Current'], 2)
cols = ['CurrAlloc%', 'Current P/L%', 'FTT%']
df_tmp[cols].sort_values(by=['CurrAlloc%'], ascending=False)

               CurrAlloc%  Current P/L%    FTT%
Category
FMCG                14.35        -21.01   63.46
FINANCE             11.30         -7.16   53.59
IT                  10.30        -43.49  114.50
MISC                 7.29        -20.72   72.52
AUTO                 6.67         -7.81   48.02
PAINTS               5.45        -18.48   38.69
BANKS                5.39        -10.57   61.66
INSURANCE            5.26         -3.25   38.08
PHARMA               5.19          6.30   22.06
ELECTRICAL           4.15        -11.66   50.94
CHEMICALS            2.15        -23.51   96.42
HEALTHCARE           2.14         -9.67   38.29
APPARELS             1.83          3.80   28.51
AC                   1.79        -17.30   49.10
FOOTWEAR             1.69        -71.16  139.79
BREWERIES            1.67          8.18   10.89
DURABLES             1.62        -56.02   93.98
REALTY               1.59          8.65    6.36
TRAVEL               1.50        -96.33  194.64
CERAMICS             1.42        -42.35   85.59
CABLES               1.23         20.94   64.39
ENGINEERING          1.22        -30.25   89.82
JEWELLERY            1.13        -85.31  149.70
REFINERIES           1.08        -21.75   52.56
CEMENT               1.07        -64.85  188.18
ENTERTAINMENT        0.72        -77.11  182.74
TEXTILES             0.41        -48.81   91.24
HOTELS               0.38        -94.03  162.47

In [29]:
# money to be made criteria-wise
df_portfolio_features.groupby('Criteria')['FTT Amt'].agg(['sum', 'count']).sort_values(by='sum', ascending=False)

                sum  count
Criteria
XY24      3433905.0     21
X40       1860979.0     19
XR        1319850.0     13
AR        1111484.0      9
X40N      1064889.0     13
OX40N      724498.0     10
XY25       439702.0      5
SR         285376.0      2

In [30]:
# money to be made conviction-wise
df_portfolio_features.groupby('Conviction')['FTT Amt'].agg(['sum', 'count']).sort_values(by='sum', ascending=False)

                  sum  count
Conviction
H-SC        3310337.0     24
X-LC        1965909.0     21
X-MC        1488281.0     15
M-SC        1408811.0     14
X-SC        1249411.0      9
H-MC         291739.0      2
L-SC         208886.0      2
M-LC         167788.0      1
M-MC          56519.0      2
H-LC          47742.0      1
L-MC          45260.0      1

In [31]:
# money to be made criteria and conviction-wise
df_portfolio_features.groupby(['Conviction', 'Criteria'])['FTT Amt'].agg(['sum', 'count']).sort_values(by='sum', ascending=False)

                           sum  count
Conviction Criteria
H-SC       XY24      1011254.0      6
X-LC       X40       1008780.0     10
H-SC       AR         934666.0      5
M-SC       XY24       828220.0      6
H-SC       XR         780533.0      7
X-SC       XY24       738778.0      4
X-MC       X40        644924.0      7
X-LC       X40N       386766.0      6
X-MC       X40N       374765.0      4
X-LC       XY24       369749.0      2
M-SC       OX40N      312185.0      5
X-SC       X40N       303358.0      3
H-SC       OX40N      298508.0      4
           SR         285376.0      2
H-MC       XY24       252801.0      1
X-MC       XY25       235489.0      2
           XY24       233103.0      2
X-SC       X40        207275.0      2
M-SC       XR         192263.0      2
M-LC       XR         167788.0      1
X-LC       XY25       161689.0      2
L-SC       OX40N      113805.0      1
           XR          95081.0      1
M-SC       AR          76143.0      1
H-LC       AR          47742.0      1
L-MC       XR          45260.0      1
M-MC       XY25        42524.0      1
H-MC       AR          38938.0      1
X-LC       XR          38925.0      1
M-MC       AR          13995.0      1

In [32]:
# notebook execution time

end_time = time.time()
execution_time = round(end_time - start_time, 0)
print(f"Notebook execution time: {execution_time} seconds")

Notebook execution time: 30.0 seconds