<a href="https://colab.research.google.com/github/ankit-rathi/Quantvesting_v2/blob/main/myStocks_Portfolio_Analysis.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
'''
!pip install pandas==2.2.2 -qq
!pip install pyxirr -qq
!pip install ta -qq
!pip install yfinance==0.2.59 -qq
'''

'\n!pip install pandas==2.2.2 -qq\n!pip install pyxirr -qq\n!pip install ta -qq\n!pip install yfinance==0.2.59 -qq\n'

In [2]:
# import libraries

import numpy as np
import pandas as pd
import datetime
import warnings
warnings.filterwarnings('ignore')
import yfinance as yfin
import ta
import matplotlib.pyplot as plt
import requests

In [3]:
# notebook start time
import time
import datetime
import pytz

start_time = time.time()

# function to print date timestamp
def print_date_time():
  tz_NY = pytz.timezone('Asia/Kolkata')
  datetime_NY = datetime.datetime.now(tz_NY)
  print("Run date time (IST):", datetime_NY.strftime("%Y-%m-%d %H:%M:%S"))

In [4]:
# function to get booked and reserved amount
def get_amt():
  # fetch the JSON data from the URL
  url = "https://raw.githubusercontent.com/ankit-rathi/Tradevesting_v1/main/data/myPortfolioAmts.json"
  response = requests.get(url)
  pf_amts = response.json()  # parse the JSON data

  # extract values from the JSON
  py_booked_amt_dm = pf_amts["py_booked_amt_dm"]
  py_booked_amt_sv = pf_amts["py_booked_amt_sv"]
  cy_booked_amt_dm = pf_amts["cy_booked_amt_dm"]
  cy_booked_amt_sv = pf_amts["cy_booked_amt_sv"]
  reserve_amt_dm = pf_amts["reserve_amt_dm"]
  reserve_amt_sv = pf_amts["reserve_amt_sv"]

  # perform calculations
  py_booked_amt = py_booked_amt_dm + py_booked_amt_sv
  cy_booked_amt = cy_booked_amt_dm + cy_booked_amt_sv
  reserve_amt = reserve_amt_dm + reserve_amt_sv
  total_booked_amt = py_booked_amt + cy_booked_amt

  return total_booked_amt, reserve_amt, cy_booked_amt, py_booked_amt

gen_output = 0

In [5]:
# function to format the amount
def format_amt(number):
    abs_number = abs(number)

    if abs_number >= 1_00_00_000:  # Crores
        formatted_amt = f"{number / 1_00_00_000:.2f} C"
    elif abs_number >= 1_00_000:  # Lakhs
        formatted_amt = f"{number / 1_00_000:.2f} L"
    elif abs_number >= 1_000:  # Thousands
        formatted_amt = f"{number / 1_000:.2f} K"
    else:
        formatted_amt = f"{number:.2f}"

    return formatted_amt

# function to set start and end date
def get_start_end_date():
  start_date = (datetime.date.today() + datetime.timedelta(days=-365)).strftime('%Y-%m-%d')
  end_date = (datetime.date.today() + datetime.timedelta(days=1)).strftime('%Y-%m-%d')
  return start_date, end_date

# function to fetch my portfolio csv
def get_mypfs_df():
  mypfs_df = pd.read_csv('https://raw.githubusercontent.com/ankit-rathi/Tradevesting_v1/main/data/myPortfolioStocks.csv')
  return mypfs_df

# function to fetch my prospects csv
def get_mypps_df():
  mypps_df = pd.read_csv('https://raw.githubusercontent.com/ankit-rathi/Tradevesting_v1/main/data/myProspectsScrips.csv')
  return mypps_df

# function to fetch screener data
def get_myscreen_df():
  myscreen_df = pd.read_csv('https://raw.githubusercontent.com/ankit-rathi/Tradevesting_v1/main/data/myScreenerDB.csv')
  return myscreen_df

# function to fetch momentum data
def get_myinvmt_df():
  myinvmt_df = pd.read_csv('https://raw.githubusercontent.com/ankit-rathi/Tradevesting_v1/main/data/myInvestments.csv')
  return myinvmt_df

# function to get the stock ids
def get_stock_ids(df_pf):
  stock_n100 = df_pf['Symbol'].unique()

  exclude = ['CADILAHC','MMTC', 'MASFIN']

  stock_ids = df_pf[~df_pf['Symbol'].isin(exclude) ]['Symbol'].unique()

  #mypf = mypf[mypf.Forecast.notnull()]
  #stock_ids = mypf['Symbol'].unique()

  #stock_ids.sort()
  return stock_ids

# get features from screener data
def get_screener_features():
  myscreen_df = get_myscreen_df()
  cols = ['Symbol', 'EPS', 'MedPE', 'ROCE%', 'ROE%', 'CapType']
  return myscreen_df[cols]

# get relative strength
def get_relative_strength(stock_list):

    # Dictionary to store stock tickers and their corresponding percentage price change
    stock_changes = {}

    # Loop through each stock and fetch its price data
    for stock in stock_list:
        try:
            # Download the stock data for the given date range
            stock_data = yfin.Ticker(stock + '.NS').history(period='1mo', interval='1d')[map(str.title, ['open', 'close', 'low', 'high', 'volume'])]

            # Calculate the percentage change for the stock
            if len(stock_data) > 0:
                start_price = stock_data['Close'].iloc[0]
                end_price = stock_data['Close'].iloc[-1]
                percent_change = round(((end_price - start_price) / start_price) * 100, 2)
                stock_changes[stock] = percent_change
            else:
                stock_changes[stock] = np.nan  # If no data is available, set to NaN

        except Exception as e:
            print(f"Error fetching data for {stock}: {e}")
            stock_changes[stock] = np.nan

    # Create a DataFrame with stock tickers and their percentage changes
    df = pd.DataFrame(list(stock_changes.items()), columns=['Symbol', 'Percent_Change'])

    # Drop any stocks with missing data (NaN values)
    df = df.dropna()

    # Calculate the percentile rank based on percentage change
    df['RSP'] = round(df['Percent_Change'].rank(pct=True) * 100, 2)
    cols = ['Symbol', 'RSP']
    df = df[cols]
    # Sort by percentile rank (optional)
    df = df.sort_values(by='RSP', ascending=False).reset_index(drop=True)

    return df

In [6]:
# function to get stock technicals
def stock_prec_dev(stock_symbol):
    #stock_symbol = 'ULTRACEMCO.NS'
    short_window = 20
    mid_window = 50
    long_window = 200
    moving_avg = 'SMA'

    start = datetime.datetime(*map(int, start_date.split('-')))
    end = datetime.datetime(*map(int, end_date.split('-')))

    stock_df = yfin.Ticker(stock_symbol + '.NS').history(period='max', interval='1d')[map(str.title, ['open', 'close', 'low', 'high', 'volume'])]

    stock_df['Max'] = round(max(stock_df['Close']),2)
    stock_df = stock_df[(stock_df.index <= end_date) & (stock_df.index >= start_date)]
    stock_df['200_SMA'] = round(stock_df['Close'].rolling(window = 200, min_periods = 1).mean(),0)
    stock_df['Dev%_200'] = round((stock_df['Close'] - stock_df['200_SMA'])*100/stock_df['200_SMA'],2)
    stock_df.dropna(axis = 0, inplace = True) # remove any null rows

    stock_df['20_SMA'] = stock_df['Close'].rolling(window=20).mean()
    stock_df['50_SMA'] = stock_df['Close'].rolling(window=50).mean()
    stock_df['Symbol'] = stock_symbol

    stock_df['Close'] = round(stock_df['Close'],2)
    stock_df['Min'] = round(min(stock_df['Close']),2)
    stock_df['RSI_14'] = ta.momentum.RSIIndicator(close=stock_df['Close'], window=14).rsi()
    stock_df['RSI_14'] = round(stock_df['RSI_14'],0)
    stock_df['Prev_Close'] = stock_df['Close'].shift(1)
    stock_df.drop(['Open', 'Low', 'High', 'Volume'], axis=1, inplace=True)
    stock_df = stock_df.tail(1)

    max_SMA = max(stock_df['20_SMA'].item(), stock_df['50_SMA'].item(), stock_df['200_SMA'].item())
    min_SMA = min(stock_df['20_SMA'].item(), stock_df['50_SMA'].item(), stock_df['200_SMA'].item())
    ABS_Spread = max_SMA - min_SMA
    stock_df['Spread%'] = round((ABS_Spread / stock_df['200_SMA'].item()) * 100,2)

    return stock_df

# function to compute stock attributes
def get_common_features(stock_ids, df_mypf):

  df_prec_dev = pd.DataFrame()
  df_tmp = get_screener_features()
  df_rs = get_relative_strength(stock_ids)

  for stock_id in stock_ids:
      tmp = stock_prec_dev(stock_id)
      tmp = tmp.reset_index()
      df_prec_dev = pd.concat([df_prec_dev, tmp], ignore_index = True)
  df_prec_dev = pd.merge(df_prec_dev, df_mypf, on= 'Symbol')
  df_prec_dev = pd.merge(df_prec_dev, df_tmp, on= 'Symbol', how='left')
  df_prec_dev = pd.merge(df_prec_dev, df_rs, on= 'Symbol', how='left')
  #print(df_prec_dev.columns)
  df_prec_dev['Curr_PE'] = round(df_prec_dev['Close']/df_prec_dev['EPS'],1)
  df_prec_dev['Dev%_PE'] = round((df_prec_dev['Curr_PE'] - df_prec_dev['MedPE'])*100/df_prec_dev['MedPE'],2)
  df_prec_dev['Conviction'] = df_prec_dev['Conviction'] + '-' + df_prec_dev['CapType']
  return df_prec_dev

# function to arrange stock features
def arrange_features(df_stocks, common_cols, diff_cols):
  df_stocks_common = df_stocks[common_cols].drop_duplicates()
  df_stocks_diff = df_stocks[diff_cols]
  df_stocks_diff['Investment'] = df_stocks_diff['AvgCost'] * df_stocks_diff['Shares']
  df_stocks_diff = df_stocks_diff.groupby(['Symbol'])[['Shares', 'Investment']].aggregate(['sum']).reset_index()
  df_stocks_diff.columns = ['Symbol', 'Shares', 'Investment']
  df_stocks_diff['AvgCost'] = round(df_stocks_diff['Investment']/df_stocks_diff['Shares'],2)
  df_stocks = pd.merge(df_stocks_diff, df_stocks_common, on='Symbol')
  return df_stocks

# plot fact distribution across dimension
def plot_pie_chart(df, dimension, fact):
  # grouping the data by category and calculating the sum of fact for each type
  grouped_data = df.groupby(dimension)[fact].sum()

  # sorting the grouped data in descending order
  grouped_data = grouped_data.sort_values(ascending=False)

  # creating a pie chart
  grouped_data.plot.pie(autopct='%1.1f%%', startangle=90, figsize=(6, 6))

  # adding a title and displaying the plot
  plt.title(f'{dimension} {fact} Distribution')
  plt.ylabel('')  # To hide the y-label
  plt.show()

In [7]:
# function to get portfolio features

def get_portfolio_features(df_common_features):

  print_date_time()
  print('-------------------')

  #df_common_features["Target"] = df_common_features["Target"].fillna(df_common_features["Max"])
  df_common_features['NTT'] = np.where(df_common_features['Strategy']== 'NTT', df_common_features["Target"], df_common_features['Max'])
  df_common_features['LTT'] = np.where(df_common_features['Strategy']== 'BTT', df_common_features["Target"], df_common_features['Max'])
  df_common_features['BOL'] = df_common_features['Min']

  tmp_df = df_common_features[df_common_features['Symbol'].isin(mypf_df[mypf_df['InPortfolio'] != 'NA'].Symbol.values)]
  print('qualified stocks: '+str(len(tmp_df['Symbol'].unique())))
  tmp_df1 = tmp_df[tmp_df['LatestQtr'] == 1]
  print('with latest results: '+str(len(tmp_df1['Symbol'].unique())))
  tmp_df1 = tmp_df1[tmp_df1['StarStock'] == 1]
  print('still star stocks: '+str(len(tmp_df1['Symbol'].unique())))
  tmp_df['Investment'] = tmp_df['AvgCost'] * tmp_df['Shares']
  tmp_df['Current'] = round(tmp_df['Close'] * tmp_df['Shares'],0)
  tmp_df['Previous'] = tmp_df['Prev_Close'] * tmp_df['Shares']
  tmp_df['EstimatedST'] = tmp_df['NTT'] * tmp_df['Shares']
  tmp_df['EstimatedLT'] = tmp_df['LTT'] * tmp_df['Shares']
  tmp_df['Current P/L'] = round((tmp_df['Current'] - tmp_df['Investment']),0)
  tmp_df['Today P/L%'] = round((tmp_df['Current'] - tmp_df['Previous'])*100/tmp_df['Previous'],2)
  tmp_df['Current P/L%'] = round((tmp_df['Current'] - tmp_df['Investment'])*100/tmp_df['Investment'],2)
  tmp_df['EstimatedST P/L%'] = round((tmp_df['EstimatedST'] - tmp_df['Investment'])*100/tmp_df['Investment'],2)
  tmp_df['EstimatedLT P/L%'] = round((tmp_df['EstimatedLT'] - tmp_df['Investment'])*100/tmp_df['Investment'],2)
  tmp_df['NTT%'] = round((tmp_df['NTT'] - tmp_df['Close'])*100/tmp_df['Close'],2)
  tmp_df['LTT%'] = round((tmp_df['LTT'] - tmp_df['Close'])*100/tmp_df['Close'],2)
  tmp_df['Gained%'] = round((tmp_df['Close'] - tmp_df['BOL'])*100/tmp_df['BOL'],2)
  investment = round(sum(tmp_df['AvgCost']*tmp_df['Shares']),0)
  current = round(sum(tmp_df['Close']*tmp_df['Shares']),0)
  tmp_df['InitAlloc%'] = round(tmp_df['Investment']*100/investment,2)
  tmp_df['CurrAlloc%'] = round(tmp_df['Current']*100/current,2)
  tmp_df['FTT'] = tmp_df['LTT']
  tmp_df.loc[tmp_df['Strategy'] == 'NTT', 'FTT'] = tmp_df['NTT']
  tmp_df['FTT%'] = tmp_df['LTT%']
  tmp_df.loc[tmp_df['Strategy'] == 'NTT', 'FTT%'] = tmp_df['NTT%']
  tmp_df['FTT Amt'] = round(tmp_df['FTT%'] * tmp_df['Current']/100,0)
  tmp_df['OTT%'] = round((tmp_df['FTT'] - tmp_df['AvgCost'])*100/tmp_df['AvgCost'],2)
  tmp_df['RRR Ind'] = round(tmp_df['Current P/L']/tmp_df['FTT Amt'],2)
  tmp_df['Risk Ind'] = round(tmp_df['Current P/L%']*tmp_df['CurrAlloc%'],0)

  return tmp_df

# function to print portfolio features
def print_portfolio_stats(df_portfolio_features, myinvmt_df):
  from pyxirr import xirr

  total_booked_amt, reserve_amt, cy_booked_amt, py_booked_amt = get_amt()

  dates = myinvmt_df['Date'].values
  dates = np.append(dates, datetime.date.today().strftime('%d-%b-%y'))
  investment = myinvmt_df['Investment'].values
  dates= pd.to_datetime(dates)

  current = round(sum(df_portfolio_features['Close']*df_portfolio_features['Shares']),0) + reserve_amt
  investment_xirr = np.append(investment, current)
  cagr = round(xirr(pd.DataFrame({"dates": dates, "amounts": investment_xirr}))*100,2)

  investment = -sum(investment)
  invested = round(sum(df_portfolio_features['AvgCost']*df_portfolio_features['Shares']),0) + reserve_amt
  previous = round(sum(df_portfolio_features['Prev_Close']*df_portfolio_features['Shares']),0) + reserve_amt
  cy_invested = investment + py_booked_amt

  today_pnl_amount = current-previous
  today_pnl_percentage = round((current-previous)*100/previous,2)

  curr_pnl_amount = current-invested
  curr_pnl_percentage = round((curr_pnl_amount)*100/(cy_invested),2)

  cy_pnl_amount = cy_booked_amt + curr_pnl_amount
  cy_pnl_percentage = round((cy_pnl_amount)*100/cy_invested,2)

  overall_pnl_amount = total_booked_amt + curr_pnl_amount
  overall_pnl_percentage = round((overall_pnl_amount)*100/investment,2)

  estimate_st = round(sum(df_portfolio_features['FTT']*df_portfolio_features['Shares']),0)  + reserve_amt
  est_st_pnl_amount = estimate_st-current
  est_st_pnl_percentage = round((est_st_pnl_amount)*100/current,2)

  estimate_lt = round(sum(df_portfolio_features['LTT']*df_portfolio_features['Shares']),0)  + reserve_amt
  est_lt_pnl_amount = estimate_lt-current
  est_lt_pnl_percentage = round((est_lt_pnl_amount)*100/current,2)

  total_profit = round(sum(df_portfolio_features[df_portfolio_features['Current P/L%'] > 0]['Current']) - sum(df_portfolio_features[df_portfolio_features['Current P/L%'] > 0]['Investment']),0)
  total_loss = round(sum(df_portfolio_features[df_portfolio_features['Current P/L%'] < 0]['Current']) - sum(df_portfolio_features[df_portfolio_features['Current P/L%'] < 0]['Investment']),0)

  cy_booked_percentage = round((cy_booked_amt)*100/current,2)
  py_booked_percentage = round((py_booked_amt)*100/investment,2)
  total_booked_percentage = round((total_booked_amt)*100/investment,2)

  print('-------------------')
  print('Initial Investment: ', format_amt(investment))
  print('CY Investment: ', format_amt(cy_invested))
  print('Reserve: ', format_amt(reserve_amt))
  print('Current: ',  format_amt(current))
  print('-------------------')
  print('Today PnL: '+ '{} ({}%)'.format(format_amt(today_pnl_amount), today_pnl_percentage))
  print('Current PnL: '+ '{} ({}%)'.format(format_amt(curr_pnl_amount), curr_pnl_percentage))
  print('CY Booked + Current PnL: '+ '{} ({}%)'.format(format_amt(cy_pnl_amount), cy_pnl_percentage))
  print('-------------------')
  print('Total profit: ', format_amt(total_profit))
  print('Total loss: ', format_amt(total_loss))
  print('-------------------')
  print('Total Booked + Current PnL: '+ '{} ({}%)'.format(format_amt(overall_pnl_amount), overall_pnl_percentage))
  print('Total Booked PnL: '+ '{} ({}%)'.format(format_amt(total_booked_amt), total_booked_percentage))
  print('Curr Year Booked PnL: '+ '{} ({}%)'.format(format_amt(cy_booked_amt), cy_booked_percentage))
  print('Prev Year Booked PnL: '+ '{} ({}%)'.format(format_amt(py_booked_amt), py_booked_percentage))
  print('===================')
  print('Est FTT: ',  format_amt(estimate_st))
  print('Est FTT PnL: '+ '{} ({}%)'.format(format_amt(est_st_pnl_amount), est_st_pnl_percentage))

  print('===================')
  print('Deployed: ', format_amt(investment))

  print('Current: ', format_amt(current))

  print('CAGR/XIRR %: '+'{}%'.format(cagr))

In [8]:
# get start and end date
start_date, end_date = get_start_end_date()

# get portfolio and prospects data
mypfs_df = get_mypfs_df()
mypps_df = get_mypps_df()
myinvmt_df = get_myinvmt_df()

# merge above datasets
mypf_df = pd.merge(mypfs_df, mypps_df, on="Symbol")

# seggregate dm and sv portfolio
dm_pf = mypf_df[mypf_df['InPortfolio'] == 'DM']
sv_pf = mypf_df[mypf_df['InPortfolio'] == 'SV']

# build portfolio stock dataframe
dm_stocks = get_stock_ids(dm_pf)
sv_stocks = get_stock_ids(sv_pf)
df_stocks = pd.concat([dm_pf,sv_pf], ignore_index = True)

# arrange common and diff stock features
common_cols = ['Symbol', 'Target', 'Criteria', 'Strategy', 'CumlRnk', 'LatestQtr', 'StarStock', 'Conviction', 'Category', 'InFolio', 'XIRR', 'MBQ']
diff_cols = ['Symbol', 'AvgCost', 'Shares']
df_stocks = arrange_features(df_stocks, common_cols, diff_cols)

# get common features
stock_ids = df_stocks['Symbol'].values
df_common_features = get_common_features(stock_ids, df_stocks)

df_common_features.reset_index(drop=True, inplace=True)
df_common_features.drop(['Date'], axis=1, inplace=True)
# get and print portfolio features
df_portfolio_features = get_portfolio_features(df_common_features)

print_portfolio_stats(df_portfolio_features, myinvmt_df)

df = df_portfolio_features
#plot_pie_chart(df, 'CapType', 'Current')
list_ox40n = list(df[df['MBQ'].str.contains('OX40N', na=False)]['Symbol'].values)

Run date time (IST): 2026-04-21 14:25:38
-------------------
qualified stocks: 85
with latest results: 25
still star stocks: 15

-------------------
Initial Investment:  1.36 C
CY Investment:  1.78 C
Reserve:  1.61 K
Current:  1.41 C
-------------------
Today PnL: 1.19 L (0.85%)
Current PnL: -33.11 L (-18.56%)
CY Booked + Current PnL: -32.15 L (-18.03%)
-------------------
Total profit:  1.78 L
Total loss:  -34.89 L
-------------------
Total Booked + Current PnL: 10.72 L (7.91%)
Total Booked PnL: 43.83 L (32.35%)
Curr Year Booked PnL: 96.00 K (0.68%)
Prev Year Booked PnL: 42.87 L (31.64%)
===================
Est FTT:  2.44 C
Est FTT PnL: 1.03 C (73.16%)
===================
Deployed:  1.36 C
Current:  1.41 C
CAGR/XIRR %: 1.89%

In [9]:
# top 5 near their targets
cols = ['Symbol', 'Today P/L%', 'Current P/L%', 'FTT%', 'OTT%', 'FTT Amt', 'Current P/L', 'Current', 'FTT', 'Dev%_PE', 'RSI_14','Conviction', 'Spread%',  'CumlRnk', 'RRR Ind', 'CurrAlloc%', 'Gained%', 'Criteria', 'Strategy', 'Category']
df_tmp = df_portfolio_features[~df_portfolio_features['Symbol'].isin(['ENRIN','BLUSPRING','DIGITIDE'])]
df_tmp = df_tmp.sort_values(by = 'FTT Amt', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
49,MASFIN,1.10,-2.53,24.72,21.57,23609.0,-2475.0,95505.0,397.04,-15.99,58.0,H-SC,3.28,167.0,-0.10,0.68,23.42,XR,ATH,FINANCE
1,ABB,1.52,33.33,9.18,45.57,32021.0,87197.0,348816.0,7934.00,-14.32,77.0,H-MC,18.42,125.0,2.72,2.47,54.90,AR,NTT,ELECTRICAL
56,RECLTD,0.17,3.78,16.34,20.74,34452.0,7672.0,210842.0,446.00,15.23,71.0,M-MC,4.83,191.0,0.22,1.50,25.65,XY25,NTT,FINANCE
76,TTKPRESTIG,1.26,-34.89,53.74,0.09,35259.0,-35166.0,65611.0,770.00,52.19,56.0,M-SC,22.93,250.0,-1.00,0.47,16.83,OX40N,NTT,DURABLES
66,SONACOMS,1.22,0.96,37.77,39.09,38575.0,971.0,102130.0,804.02,-20.06,65.0,M-MC,10.50,193.0,0.03,0.72,44.48,AR,ATH,AUTO

In [10]:
# top 5 today
df_tmp = df_portfolio_features.sort_values(by = 'Today P/L%', ascending=False)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
40,INDIGOPNTS,4.32,-38.06,61.47,0.02,66466.0,-66431.0,108128.0,1408.00,64.62,61.0,M-SC,27.58,222.0,-1.00,0.77,22.68,OX40N,NTT,PAINTS
77,UNITDSPR,4.32,0.21,20.51,20.77,48125.0,498.0,234642.0,1644.00,-11.09,61.0,X-MC,6.13,64.0,0.01,1.66,11.93,X40N,NTT,BREWERIES
65,SIS,4.09,-21.98,55.43,21.26,48016.0,-24408.0,86624.0,528.00,2046.63,76.0,H-SC,10.09,168.0,-0.51,0.61,28.80,OX40N,NTT,MISC
4,ALKYLAMINE,3.95,-37.68,210.71,93.63,132575.0,-38045.0,62918.0,4546.37,-33.22,59.0,H-SC,23.87,142.0,-0.29,0.45,18.80,SR,ATH,CHEMICALS
59,REPCOHOME,3.74,-9.67,110.15,89.82,285055.0,-27717.0,258788.0,880.00,-54.55,68.0,H-SC,4.57,161.0,-0.10,1.84,24.41,XY24,NTT,FINANCE

In [11]:
# bottom 5 today
df_tmp = df_portfolio_features.sort_values(by = 'Today P/L%', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
54,RAJESHEXPO,-4.56,-77.40,342.74,0.07,106267.0,-106172.0,31005.0,518.00,1036.36,53.0,L-SC,41.17,268.0,-1.00,0.22,45.56,OX40N,NTT,JEWELLERY
19,COLPAL,-1.58,-20.44,77.87,41.51,163161.0,-53835.0,209530.0,3726.84,-3.83,62.0,X-MC,11.88,62.0,-0.33,1.49,17.14,XY25,ATH,FMCG
37,ICICIPRULI,-1.52,-9.09,43.79,30.73,78430.0,-17901.0,179104.0,790.00,-33.52,45.0,X-MC,12.95,78.0,-0.23,1.27,9.14,X40,ATH,INSURANCE
36,ICICIGI,-1.16,-1.75,21.46,19.34,42192.0,-3500.0,196609.0,2252.93,-17.38,57.0,X-MC,7.09,66.0,-0.08,1.39,9.81,X40,ATH,INSURANCE
45,JIOFIN,-1.00,-22.09,64.84,28.43,150709.0,-65895.0,232432.0,387.00,-23.29,46.0,X-LC,18.73,34.0,-0.44,1.65,4.77,XY24,BTT,FINANCE

In [12]:
# top 5 to exit based on CumlRnk
df_tmp = df_portfolio_features[~df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])]
df_tmp = df_tmp[(df_tmp['Current P/L%'] > -1) & (df_tmp['Current P/L%'] < 1)].sort_values(by = 'CumlRnk', ascending=False)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
66,SONACOMS,1.22,0.96,37.77,39.09,38575.0,971.0,102130.0,804.02,-20.06,65.0,M-MC,10.50,193.0,0.03,0.72,44.48,AR,ATH,AUTO
67,STARHEALTH,1.89,-0.15,47.48,47.26,133278.0,-419.0,280704.0,761.00,57.63,76.0,H-SC,2.55,173.0,-0.00,1.99,45.37,XY24,NTT,INSURANCE

In [13]:
# OX40N stocks to exit
df_tmp = df_portfolio_features[(df_portfolio_features['Symbol'].isin(list_ox40n))].sort_values(by = 'Current P/L%', ascending=False)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
25,FINCABLES,0.63,20.64,72.34,107.91,128851.0,30474.0,178118.0,1641.55,8.57,68.0,M-SC,3.44,220.0,0.24,1.26,34.00,OX40N,ATH,CABLES
65,SIS,4.09,-21.98,55.43,21.26,48016.0,-24408.0,86624.0,528.00,2046.63,76.0,H-SC,10.09,168.0,-0.51,0.61,28.80,OX40N,NTT,MISC
17,CERA,0.16,-30.51,78.28,23.89,95688.0,-53665.0,122238.0,9475.00,-32.94,67.0,H-SC,13.51,153.0,-0.56,0.87,17.47,OX40N,NTT,CERAMICS
47,KANSAINER,1.48,-30.88,64.17,13.47,119606.0,-83277.0,186390.0,340.00,-40.61,67.0,H-SC,20.09,162.0,-0.70,1.32,30.19,XY24,NTT,PAINTS
71,TATAELXSI,2.78,-33.10,97.35,32.03,85861.0,-43637.0,88198.0,9161.00,-16.33,60.0,H-SC,18.30,158.0,-0.51,0.63,16.73,OX40N,NTT,IT

In [14]:
# top 5 to book for rotation
df_tmp = df_portfolio_features[(df_portfolio_features['Current P/L%'] > 20) ].sort_values(by = 'CumlRnk', ascending=False)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
25,FINCABLES,0.63,20.64,72.34,107.91,128851.0,30474.0,178118.0,1641.55,8.57,68.0,M-SC,3.44,220.0,0.24,1.26,34.0,OX40N,ATH,CABLES
1,ABB,1.52,33.33,9.18,45.57,32021.0,87197.0,348816.0,7934.00,-14.32,77.0,H-MC,18.42,125.0,2.72,2.47,54.9,AR,NTT,ELECTRICAL

In [15]:
# top 5 to monitor for exit
df_tmp = df_portfolio_features[~df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])]
df_tmp = df_tmp[(df_tmp['Current P/L%'] > 0) ].sort_values(by = 'Dev%_PE', ascending=False)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
56,RECLTD,0.17,3.78,16.34,20.74,34452.0,7672.0,210842.0,446.00,15.23,71.0,M-MC,4.83,191.0,0.22,1.50,25.65,XY25,NTT,FINANCE
25,FINCABLES,0.63,20.64,72.34,107.91,128851.0,30474.0,178118.0,1641.55,8.57,68.0,M-SC,3.44,220.0,0.24,1.26,34.00,OX40N,ATH,CABLES
1,ABB,1.52,33.33,9.18,45.57,32021.0,87197.0,348816.0,7934.00,-14.32,77.0,H-MC,18.42,125.0,2.72,2.47,54.90,AR,NTT,ELECTRICAL
66,SONACOMS,1.22,0.96,37.77,39.09,38575.0,971.0,102130.0,804.02,-20.06,65.0,M-MC,10.50,193.0,0.03,0.72,44.48,AR,ATH,AUTO

In [16]:
# top 5 to book for rotation from weak conviction
df_tmp = df_portfolio_features[~df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])]
df_tmp = df_tmp[~df_tmp['Criteria'].isin(['XY25','XY24','X40', 'X40N'])].sort_values(by = 'RRR Ind', ascending=False)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
1,ABB,1.52,33.33,9.18,45.57,32021.0,87197.0,348816.0,7934.00,-14.32,77.0,H-MC,18.42,125.0,2.72,2.47,54.90,AR,NTT,ELECTRICAL
25,FINCABLES,0.63,20.64,72.34,107.91,128851.0,30474.0,178118.0,1641.55,8.57,68.0,M-SC,3.44,220.0,0.24,1.26,34.00,OX40N,ATH,CABLES
66,SONACOMS,1.22,0.96,37.77,39.09,38575.0,971.0,102130.0,804.02,-20.06,65.0,M-MC,10.50,193.0,0.03,0.72,44.48,AR,ATH,AUTO
84,ZYDUSLIFE,-0.68,-1.91,38.28,35.63,78690.0,-4011.0,205563.0,1286.17,-14.41,58.0,H-MC,4.92,120.0,-0.05,1.46,11.29,AR,ATH,PHARMA
39,INDIAMART,-0.66,-6.74,121.67,106.72,139946.0,-8315.0,115021.0,4810.62,-58.01,61.0,H-SC,11.95,140.0,-0.06,0.82,10.50,AR,ATH,MISC

In [17]:
# top 5 to accumulate based on lowest RSI_14
df_tmp = df_portfolio_features[df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])].sort_values(by = 'RSI_14', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
2,ABBOTINDIA,-0.51,-14.72,38.45,18.07,58644.0,-26335.0,152520.0,35195.0,-27.52,39.0,X-MC,11.81,58.0,-0.45,1.08,0.00,X40,ATH,PHARMA
37,ICICIPRULI,-1.52,-9.09,43.79,30.73,78430.0,-17901.0,179104.0,790.0,-33.52,45.0,X-MC,12.95,78.0,-0.23,1.27,9.14,X40,ATH,INSURANCE
45,JIOFIN,-1.00,-22.09,64.84,28.43,150709.0,-65895.0,232432.0,387.0,-23.29,46.0,X-LC,18.73,34.0,-0.44,1.65,4.77,XY24,BTT,FINANCE
58,RELIANCE,-0.62,-13.03,44.07,25.30,77026.0,-26181.0,174782.0,1952.0,-15.42,48.0,X-LC,5.61,21.0,-0.34,1.24,5.35,XY25,BTT,REFINERIES
42,INFY,-0.13,-10.76,50.43,34.24,140812.0,-33666.0,279222.0,1972.0,-29.61,50.0,X-LC,12.80,3.0,-0.24,1.98,7.38,X40,NTT,IT

In [18]:
# top 5 to accumulate based on Spread and CumlRnk
df_tmp = df_portfolio_features[df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])]
df_tmp = df_tmp[(df_tmp['CumlRnk'] < 100)].sort_values(by = 'Spread%', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
64,SIEMENS,0.51,0.16,25.31,25.51,47178.0,305.0,186400.0,4671.50,56.49,73.0,H-LC,2.62,51.0,0.01,1.32,31.87,AR,ATH,ELECTRICAL
23,DMART,-0.91,9.70,18.14,29.60,49669.0,24210.0,273810.0,5391.45,-7.47,67.0,X-LC,5.14,14.0,0.49,1.94,25.15,X40N,ATH,FMCG
58,RELIANCE,-0.62,-13.03,44.07,25.30,77026.0,-26181.0,174782.0,1952.00,-15.42,48.0,X-LC,5.61,21.0,-0.34,1.24,5.35,XY25,BTT,REFINERIES
77,UNITDSPR,4.32,0.21,20.51,20.77,48125.0,498.0,234642.0,1644.00,-11.09,61.0,X-MC,6.13,64.0,0.01,1.66,11.93,X40N,NTT,BREWERIES
81,VOLTAS,1.06,13.69,27.71,45.20,60406.0,26253.0,217995.0,1856.00,30.22,61.0,X-MC,6.92,79.0,0.43,1.55,21.42,XY25,NTT,AC

In [19]:
# top 5 to accumulate based on lowest Gained%
df_tmp = df_portfolio_features[df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])].sort_values(by = 'Gained%', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
2,ABBOTINDIA,-0.51,-14.72,38.45,18.07,58644.0,-26335.0,152520.0,35195.0,-27.52,39.0,X-MC,11.81,58.0,-0.45,1.08,0.00,X40,ATH,PHARMA
45,JIOFIN,-1.00,-22.09,64.84,28.43,150709.0,-65895.0,232432.0,387.0,-23.29,46.0,X-LC,18.73,34.0,-0.44,1.65,4.77,XY24,BTT,FINANCE
58,RELIANCE,-0.62,-13.03,44.07,25.30,77026.0,-26181.0,174782.0,1952.0,-15.42,48.0,X-LC,5.61,21.0,-0.34,1.24,5.35,XY25,BTT,REFINERIES
44,ITC,1.15,-18.74,46.52,19.06,128589.0,-63750.0,276416.0,452.0,-55.52,56.0,X-LC,19.11,1.0,-0.50,1.96,7.23,X40,NTT,FMCG
42,INFY,-0.13,-10.76,50.43,34.24,140812.0,-33666.0,279222.0,1972.0,-29.61,50.0,X-LC,12.80,3.0,-0.24,1.98,7.38,X40,NTT,IT

In [20]:
# top 5 to accumulate based on lowest CurrAlloc%
df_tmp = df_portfolio_features[df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])].sort_values(by = 'CurrAlloc%', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
57,RELAXO,0.53,-60.25,283.12,52.31,163380.0,-87453.0,57707.0,1176.0,-57.70,57.0,X-SC,31.68,92.0,-0.54,0.41,29.02,X40N,NTT,FOOTWEAR
11,BATAINDIA,0.67,-50.79,174.76,35.20,110653.0,-65353.0,63317.0,2096.0,-16.97,63.0,X-SC,31.55,91.0,-0.59,0.45,25.57,X40,NTT,FOOTWEAR
53,QUESS,1.82,-19.29,115.45,73.90,99516.0,-20595.0,86198.0,424.0,-56.47,59.0,X-SC,19.33,80.0,-0.21,0.61,15.96,XY24,NTT,MISC
2,ABBOTINDIA,-0.51,-14.72,38.45,18.07,58644.0,-26335.0,152520.0,35195.0,-27.52,39.0,X-MC,11.81,58.0,-0.45,1.08,0.00,X40,ATH,PHARMA
50,MEDANTA,0.65,-7.07,36.78,27.12,60336.0,-12471.0,164046.0,1486.0,-9.96,57.0,X-SC,15.58,87.0,-0.21,1.16,13.04,XY24,NTT,HEALTHCARE

In [21]:
# top 5 to accumulate based on CumlRnk
df_tmp = df_portfolio_features.sort_values(by = 'CumlRnk', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
44,ITC,1.15,-18.74,46.52,19.06,128589.0,-63750.0,276416.0,452.00,-55.52,56.0,X-LC,19.11,1.0,-0.50,1.96,7.23,X40,NTT,FMCG
72,TCS,0.93,-23.56,65.59,26.57,232256.0,-109170.0,354103.0,4311.59,-35.43,58.0,X-LC,16.13,2.0,-0.47,2.51,10.51,X40,ATH,IT
42,INFY,-0.13,-10.76,50.43,34.24,140812.0,-33666.0,279222.0,1972.00,-29.61,50.0,X-LC,12.80,3.0,-0.24,1.98,7.38,X40,NTT,IT
74,TMPV,0.27,-18.82,68.23,36.58,197107.0,-66955.0,288886.0,600.00,-83.62,61.0,X-LC,9.66,4.0,-0.34,2.05,20.41,XY24,NTT,AUTO
32,HCLTECH,1.19,-6.21,32.03,23.83,72680.0,-15012.0,226912.0,1908.19,-1.57,56.0,X-LC,7.29,8.0,-0.21,1.61,10.18,X40,ATH,IT

In [22]:
# top 5 for average up
df_tmp = df_portfolio_features[(df_portfolio_features['Dev%_200'] > 5)].sort_values(by = 'CurrAlloc%', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
66,SONACOMS,1.22,0.96,37.77,39.09,38575.0,971.0,102130.0,804.02,-20.06,65.0,M-MC,10.50,193.0,0.03,0.72,44.48,AR,ATH,AUTO
68,SURYODAY,1.32,-16.79,47.85,23.03,71302.0,-30059.0,149012.0,216.00,62.28,65.0,H-SC,3.67,166.0,-0.42,1.06,27.08,XR,NTT,BANKS
25,FINCABLES,0.63,20.64,72.34,107.91,128851.0,30474.0,178118.0,1641.55,8.57,68.0,M-SC,3.44,220.0,0.24,1.26,34.00,OX40N,ATH,CABLES
64,SIEMENS,0.51,0.16,25.31,25.51,47178.0,305.0,186400.0,4671.50,56.49,73.0,H-LC,2.62,51.0,0.01,1.32,31.87,AR,ATH,ELECTRICAL
56,RECLTD,0.17,3.78,16.34,20.74,34452.0,7672.0,210842.0,446.00,15.23,71.0,M-MC,4.83,191.0,0.22,1.50,25.65,XY25,NTT,FINANCE

In [23]:
# top 5 RSP
df_tmp = df_portfolio_features.sort_values(by = 'RSP', ascending=False)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
54,RAJESHEXPO,-4.56,-77.40,342.74,0.07,106267.0,-106172.0,31005.0,518.0,1036.36,53.0,L-SC,41.17,268.0,-1.00,0.22,45.56,OX40N,NTT,JEWELLERY
47,KANSAINER,1.48,-30.88,64.17,13.47,119606.0,-83277.0,186390.0,340.0,-40.61,67.0,H-SC,20.09,162.0,-0.70,1.32,30.19,XY24,NTT,PAINTS
55,RAJOOENG,0.64,-35.80,117.48,39.61,77302.0,-36700.0,65800.0,143.1,-56.61,61.0,H-SC,29.05,136.0,-0.47,0.47,40.96,AR,ATH,MISC
65,SIS,4.09,-21.98,55.43,21.26,48016.0,-24408.0,86624.0,528.0,2046.63,76.0,H-SC,10.09,168.0,-0.51,0.61,28.80,OX40N,NTT,MISC
80,VBL,3.26,-2.69,39.24,35.50,120606.0,-8486.0,307356.0,670.8,-14.17,70.0,X-LC,9.80,13.0,-0.07,2.18,26.21,X40N,ATH,FMCG

In [24]:
# Top N allocation
df_tmp = df_portfolio_features.sort_values(by = 'CurrAlloc%', ascending=False)
top_n_values = [10, 25, 50]

sum_df = pd.DataFrame({
    'Top_N': top_n_values,
    'Sum_Alloc%': [df_tmp['CurrAlloc%'].head(n).sum() for n in top_n_values]
})

sum_df

   Top_N  Sum_Alloc%
0     10       20.94
1     25       46.17
2     50       78.37

In [25]:
# market-cap-wise allocation
df_tmp = df_portfolio_features[cols]
df_tmp.groupby(df_tmp['Conviction'].str[-2:])['CurrAlloc%'].sum().sort_values(ascending=False)

Conviction
SC    43.82
MC    30.40
LC    25.78
Name: CurrAlloc%, dtype: float64

In [26]:
# criteria-wise allocation
df_portfolio_features.groupby('Criteria')['CurrAlloc%'].sum().sort_values(ascending=False)

Criteria
XY24     27.90
X40      25.05
X40N     13.69
AR        9.60
XR        8.47
XY25      7.40
OX40N     7.07
SR        0.82
Name: CurrAlloc%, dtype: float64

In [27]:
# conviction-wise allocation
df_portfolio_features.groupby('Conviction')['CurrAlloc%'].sum().sort_values(ascending=False)

Conviction
X-LC    23.45
H-SC    22.76
X-MC    22.60
M-SC    10.38
X-SC    10.09
H-MC     5.23
M-MC     2.22
H-LC     1.32
M-LC     1.01
L-SC     0.59
L-MC     0.35
Name: CurrAlloc%, dtype: float64

In [28]:
# sector-wise stats
df_tmp = df_portfolio_features.groupby('Category')[['CurrAlloc%', 'Current', 'Current P/L', 'FTT Amt']].sum().sort_values(by=['Current', 'Current P/L'], ascending=False)
df_tmp['Current P/L%'] = round(df_tmp['Current P/L'] * 100 / df_tmp['Current'], 2)
df_tmp['FTT%'] = round(df_tmp['FTT Amt'] * 100 / df_tmp['Current'], 2)
cols = ['CurrAlloc%', 'Current P/L%', 'FTT%']
df_tmp[cols].sort_values(by=['CurrAlloc%'], ascending=False)

               CurrAlloc%  Current P/L%    FTT%
Category
FMCG                15.23        -16.34   57.62
IT                  11.84        -35.01  103.71
FINANCE             11.33        -15.50   65.73
MISC                 7.21        -31.86   89.14
ELECTRICAL           6.92          0.78   37.21
PAINTS               5.55        -26.09   47.99
BANKS                4.71        -16.19   75.17
INSURANCE            4.65         -3.32   38.68
PHARMA               3.92         -6.38   39.86
AUTO                 3.91        -18.69   65.78
AC                   2.09         -8.73   38.21
HEALTHCARE           1.94        -30.32   64.33
APPARELS             1.89         -0.78   35.15
FOOTWEAR             1.87        -67.27  134.34
TRAVEL               1.84        -72.80  159.32
DURABLES             1.82        -51.05   87.79
BREWERIES            1.66          0.21   20.51
REALTY               1.49         -5.83   23.22
CERAMICS             1.38        -58.28  106.36
CABLES               1.26         17.11   72.34
REFINERIES           1.24        -14.98   44.07
CEMENT               1.22        -55.37  171.61
ENGINEERING          1.19        -43.98  109.83
JEWELLERY            1.11       -104.91  176.11
CHEMICALS            1.10        -71.65  211.69
ENTERTAINMENT        0.80        -71.10  173.15
TEXTILES             0.46        -43.21   84.05
HOTELS               0.37       -117.11  193.69

In [29]:
# money to be made criteria-wise
df_portfolio_features.groupby('Criteria')['FTT Amt'].agg(['sum', 'count']).sort_values(by='sum', ascending=False)

                sum  count
Criteria
XY24      3662798.0     21
X40       1641667.0     16
XR        1299624.0     12
AR        1218531.0     10
X40N       990386.0      9
OX40N      795727.0     10
XY25       399304.0      5
SR         304779.0      2

In [30]:
# money to be made conviction-wise
df_portfolio_features.groupby('Conviction')['FTT Amt'].agg(['sum', 'count']).sort_values(by='sum', ascending=False)

                  sum  count
Conviction
H-SC        3588619.0     24
X-MC        1546939.0     15
X-LC        1470351.0     13
M-SC        1454896.0     14
X-SC        1380156.0      9
H-MC         341062.0      3
L-SC         207569.0      2
M-LC         149428.0      1
M-MC          73027.0      2
L-MC          53591.0      1
H-LC          47178.0      1

In [31]:
# money to be made criteria and conviction-wise
df_portfolio_features.groupby(['Conviction', 'Criteria'])['FTT Amt'].agg(['sum', 'count']).sort_values(by='sum', ascending=False)

                           sum  count
Conviction Criteria
H-SC       XY24      1176841.0      6
           AR         948370.0      5
M-SC       XY24       855065.0      6
X-SC       XY24       820395.0      4
H-SC       XR         816959.0      7
X-LC       X40        810975.0      7
X-MC       X40        629413.0      7
           X40N       461629.0      4
X-SC       X40N       358482.0      3
X-LC       XY24       347816.0      2
M-SC       OX40N      347790.0      5
H-SC       OX40N      341670.0      4
           SR         304779.0      2
X-MC       XY24       232330.0      2
H-MC       XY24       230351.0      1
X-MC       XY25       223567.0      2
X-SC       X40        201279.0      2
M-SC       XR         178344.0      2
X-LC       X40N       170275.0      2
M-LC       XR         149428.0      1
X-LC       XY25       141285.0      2
H-MC       AR         110711.0      2
L-SC       OX40N      106267.0      1
           XR         101302.0      1
M-SC       AR          73697.0      1
L-MC       XR          53591.0      1
H-LC       AR          47178.0      1
M-MC       AR          38575.0      1
           XY25        34452.0      1

In [32]:
# notebook execution time

end_time = time.time()
execution_time = round(end_time - start_time, 0)
print(f"Notebook execution time: {execution_time} seconds")

Notebook execution time: 35.0 seconds