<a href="https://colab.research.google.com/github/ankit-rathi/Quantvesting_v2/blob/main/myStocks_Portfolio_Analysis.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
'''
!pip install pandas==2.2.2 -qq
!pip install pyxirr -qq
!pip install ta -qq
!pip install yfinance==0.2.59 -qq
'''

'\n!pip install pandas==2.2.2 -qq\n!pip install pyxirr -qq\n!pip install ta -qq\n!pip install yfinance==0.2.59 -qq\n'

In [2]:
# import libraries

import numpy as np
import pandas as pd
import datetime
import warnings
warnings.filterwarnings('ignore')
import yfinance as yfin
import ta
import matplotlib.pyplot as plt
import requests

In [3]:
# notebook start time
import time
import datetime
import pytz

start_time = time.time()

# function to print date timestamp
def print_date_time():
  tz_NY = pytz.timezone('Asia/Kolkata')
  datetime_NY = datetime.datetime.now(tz_NY)
  print("Run date time (IST):", datetime_NY.strftime("%Y-%m-%d %H:%M:%S"))

In [4]:
# function to get booked and reserved amount
def get_amt():
  # fetch the JSON data from the URL
  url = "https://raw.githubusercontent.com/ankit-rathi/Tradevesting_v1/main/data/myPortfolioAmts.json"
  response = requests.get(url)
  pf_amts = response.json()  # parse the JSON data

  # extract values from the JSON
  py_booked_amt_dm = pf_amts["py_booked_amt_dm"]
  py_booked_amt_sv = pf_amts["py_booked_amt_sv"]
  cy_booked_amt_dm = pf_amts["cy_booked_amt_dm"]
  cy_booked_amt_sv = pf_amts["cy_booked_amt_sv"]
  reserve_amt_dm = pf_amts["reserve_amt_dm"]
  reserve_amt_sv = pf_amts["reserve_amt_sv"]

  # perform calculations
  py_booked_amt = py_booked_amt_dm + py_booked_amt_sv
  cy_booked_amt = cy_booked_amt_dm + cy_booked_amt_sv
  reserve_amt = reserve_amt_dm + reserve_amt_sv
  total_booked_amt = py_booked_amt + cy_booked_amt

  return total_booked_amt, reserve_amt, cy_booked_amt, py_booked_amt

gen_output = 0

In [5]:
# function to format the amount
def format_amt(number):
    abs_number = abs(number)

    if abs_number >= 1_00_00_000:  # Crores
        formatted_amt = f"{number / 1_00_00_000:.2f} C"
    elif abs_number >= 1_00_000:  # Lakhs
        formatted_amt = f"{number / 1_00_000:.2f} L"
    elif abs_number >= 1_000:  # Thousands
        formatted_amt = f"{number / 1_000:.2f} K"
    else:
        formatted_amt = f"{number:.2f}"

    return formatted_amt

# function to set start and end date
def get_start_end_date():
  start_date = (datetime.date.today() + datetime.timedelta(days=-365)).strftime('%Y-%m-%d')
  end_date = (datetime.date.today() + datetime.timedelta(days=1)).strftime('%Y-%m-%d')
  return start_date, end_date

# function to fetch my portfolio csv
def get_mypfs_df():
  mypfs_df = pd.read_csv('https://raw.githubusercontent.com/ankit-rathi/Tradevesting_v1/main/data/myPortfolioStocks.csv')
  return mypfs_df

# function to fetch my prospects csv
def get_mypps_df():
  mypps_df = pd.read_csv('https://raw.githubusercontent.com/ankit-rathi/Tradevesting_v1/main/data/myProspectsScrips.csv')
  return mypps_df

# function to fetch screener data
def get_myscreen_df():
  myscreen_df = pd.read_csv('https://raw.githubusercontent.com/ankit-rathi/Tradevesting_v1/main/data/myScreenerDB.csv')
  return myscreen_df

# function to fetch momentum data
def get_myinvmt_df():
  myinvmt_df = pd.read_csv('https://raw.githubusercontent.com/ankit-rathi/Tradevesting_v1/main/data/myInvestments.csv')
  return myinvmt_df

# function to get the stock ids
def get_stock_ids(df_pf):
  stock_n100 = df_pf['Symbol'].unique()

  exclude = ['CADILAHC','MMTC', 'MASFIN']

  stock_ids = df_pf[~df_pf['Symbol'].isin(exclude) ]['Symbol'].unique()

  #mypf = mypf[mypf.Forecast.notnull()]
  #stock_ids = mypf['Symbol'].unique()

  #stock_ids.sort()
  return stock_ids

# get features from screener data
def get_screener_features():
  myscreen_df = get_myscreen_df()
  cols = ['Symbol', 'EPS', 'MedPE', 'ROCE%', 'ROE%', 'CapType']
  return myscreen_df[cols]

# get relative strength
def get_relative_strength(stock_list):

    # Dictionary to store stock tickers and their corresponding percentage price change
    stock_changes = {}

    # Loop through each stock and fetch its price data
    for stock in stock_list:
        try:
            # Download the stock data for the given date range
            stock_data = yfin.Ticker(stock + '.NS').history(period='1mo', interval='1d')[map(str.title, ['open', 'close', 'low', 'high', 'volume'])]

            # Calculate the percentage change for the stock
            if len(stock_data) > 0:
                start_price = stock_data['Close'].iloc[0]
                end_price = stock_data['Close'].iloc[-1]
                percent_change = round(((end_price - start_price) / start_price) * 100, 2)
                stock_changes[stock] = percent_change
            else:
                stock_changes[stock] = np.nan  # If no data is available, set to NaN

        except Exception as e:
            print(f"Error fetching data for {stock}: {e}")
            stock_changes[stock] = np.nan

    # Create a DataFrame with stock tickers and their percentage changes
    df = pd.DataFrame(list(stock_changes.items()), columns=['Symbol', 'Percent_Change'])

    # Drop any stocks with missing data (NaN values)
    df = df.dropna()

    # Calculate the percentile rank based on percentage change
    df['RSP'] = round(df['Percent_Change'].rank(pct=True) * 100, 2)
    cols = ['Symbol', 'RSP']
    df = df[cols]
    # Sort by percentile rank (optional)
    df = df.sort_values(by='RSP', ascending=False).reset_index(drop=True)

    return df

In [6]:
# function to get stock technicals
def stock_prec_dev(stock_symbol):
    #stock_symbol = 'ULTRACEMCO.NS'
    short_window = 20
    mid_window = 50
    long_window = 200
    moving_avg = 'SMA'

    start = datetime.datetime(*map(int, start_date.split('-')))
    end = datetime.datetime(*map(int, end_date.split('-')))

    stock_df = yfin.Ticker(stock_symbol + '.NS').history(period='max', interval='1d')[map(str.title, ['open', 'close', 'low', 'high', 'volume'])]

    stock_df['Max'] = round(max(stock_df['Close']),2)
    stock_df = stock_df[(stock_df.index <= end_date) & (stock_df.index >= start_date)]
    stock_df['200_SMA'] = round(stock_df['Close'].rolling(window = 200, min_periods = 1).mean(),0)
    stock_df['Dev%_200'] = round((stock_df['Close'] - stock_df['200_SMA'])*100/stock_df['200_SMA'],2)
    stock_df.dropna(axis = 0, inplace = True) # remove any null rows

    stock_df['20_SMA'] = stock_df['Close'].rolling(window=20).mean()
    stock_df['50_SMA'] = stock_df['Close'].rolling(window=50).mean()
    stock_df['Symbol'] = stock_symbol

    stock_df['Close'] = round(stock_df['Close'],2)
    stock_df['Min'] = round(min(stock_df['Close']),2)
    stock_df['RSI_14'] = ta.momentum.RSIIndicator(close=stock_df['Close'], window=14).rsi()
    stock_df['RSI_14'] = round(stock_df['RSI_14'],0)
    stock_df['Prev_Close'] = stock_df['Close'].shift(1)
    stock_df.drop(['Open', 'Low', 'High', 'Volume'], axis=1, inplace=True)
    stock_df = stock_df.tail(1)

    max_SMA = max(stock_df['20_SMA'].item(), stock_df['50_SMA'].item(), stock_df['200_SMA'].item())
    min_SMA = min(stock_df['20_SMA'].item(), stock_df['50_SMA'].item(), stock_df['200_SMA'].item())
    ABS_Spread = max_SMA - min_SMA
    stock_df['Spread%'] = round((ABS_Spread / stock_df['200_SMA'].item()) * 100,2)

    return stock_df

# function to compute stock attributes
def get_common_features(stock_ids, df_mypf):

  df_prec_dev = pd.DataFrame()
  df_tmp = get_screener_features()
  df_rs = get_relative_strength(stock_ids)

  for stock_id in stock_ids:
      tmp = stock_prec_dev(stock_id)
      tmp = tmp.reset_index()
      df_prec_dev = pd.concat([df_prec_dev, tmp], ignore_index = True)
  df_prec_dev = pd.merge(df_prec_dev, df_mypf, on= 'Symbol')
  df_prec_dev = pd.merge(df_prec_dev, df_tmp, on= 'Symbol', how='left')
  df_prec_dev = pd.merge(df_prec_dev, df_rs, on= 'Symbol', how='left')
  #print(df_prec_dev.columns)
  df_prec_dev['Curr_PE'] = round(df_prec_dev['Close']/df_prec_dev['EPS'],1)
  df_prec_dev['Dev%_PE'] = round((df_prec_dev['Curr_PE'] - df_prec_dev['MedPE'])*100/df_prec_dev['MedPE'],2)
  df_prec_dev['Conviction'] = df_prec_dev['Conviction'] + '-' + df_prec_dev['CapType']
  return df_prec_dev

# function to arrange stock features
def arrange_features(df_stocks, common_cols, diff_cols):
  df_stocks_common = df_stocks[common_cols].drop_duplicates()
  df_stocks_diff = df_stocks[diff_cols]
  df_stocks_diff['Investment'] = df_stocks_diff['AvgCost'] * df_stocks_diff['Shares']
  df_stocks_diff = df_stocks_diff.groupby(['Symbol'])[['Shares', 'Investment']].aggregate(['sum']).reset_index()
  df_stocks_diff.columns = ['Symbol', 'Shares', 'Investment']
  df_stocks_diff['AvgCost'] = round(df_stocks_diff['Investment']/df_stocks_diff['Shares'],2)
  df_stocks = pd.merge(df_stocks_diff, df_stocks_common, on='Symbol')
  return df_stocks

# plot fact distribution across dimension
def plot_pie_chart(df, dimension, fact):
  # grouping the data by category and calculating the sum of fact for each type
  grouped_data = df.groupby(dimension)[fact].sum()

  # sorting the grouped data in descending order
  grouped_data = grouped_data.sort_values(ascending=False)

  # creating a pie chart
  grouped_data.plot.pie(autopct='%1.1f%%', startangle=90, figsize=(6, 6))

  # adding a title and displaying the plot
  plt.title(f'{dimension} {fact} Distribution')
  plt.ylabel('')  # To hide the y-label
  plt.show()

In [7]:
# function to get portfolio features

def get_portfolio_features(df_common_features):

  print_date_time()
  print('-------------------')

  #df_common_features["Target"] = df_common_features["Target"].fillna(df_common_features["Max"])
  df_common_features['NTT'] = np.where(df_common_features['Strategy']== 'NTT', df_common_features["Target"], df_common_features['Max'])
  df_common_features['LTT'] = np.where(df_common_features['Strategy']== 'BTT', df_common_features["Target"], df_common_features['Max'])
  df_common_features['BOL'] = df_common_features['Min']

  tmp_df = df_common_features[df_common_features['Symbol'].isin(mypf_df[mypf_df['InPortfolio'] != 'NA'].Symbol.values)]
  print('qualified stocks: '+str(len(tmp_df['Symbol'].unique())))
  tmp_df1 = tmp_df[tmp_df['LatestQtr'] == 1]
  print('with latest results: '+str(len(tmp_df1['Symbol'].unique())))
  tmp_df1 = tmp_df1[tmp_df1['StarStock'] == 1]
  print('still star stocks: '+str(len(tmp_df1['Symbol'].unique())))
  tmp_df['Investment'] = tmp_df['AvgCost'] * tmp_df['Shares']
  tmp_df['Current'] = round(tmp_df['Close'] * tmp_df['Shares'],0)
  tmp_df['Previous'] = tmp_df['Prev_Close'] * tmp_df['Shares']
  tmp_df['EstimatedST'] = tmp_df['NTT'] * tmp_df['Shares']
  tmp_df['EstimatedLT'] = tmp_df['LTT'] * tmp_df['Shares']
  tmp_df['Current P/L'] = round((tmp_df['Current'] - tmp_df['Investment']),0)
  tmp_df['Today P/L%'] = round((tmp_df['Current'] - tmp_df['Previous'])*100/tmp_df['Previous'],2)
  tmp_df['Current P/L%'] = round((tmp_df['Current'] - tmp_df['Investment'])*100/tmp_df['Investment'],2)
  tmp_df['EstimatedST P/L%'] = round((tmp_df['EstimatedST'] - tmp_df['Investment'])*100/tmp_df['Investment'],2)
  tmp_df['EstimatedLT P/L%'] = round((tmp_df['EstimatedLT'] - tmp_df['Investment'])*100/tmp_df['Investment'],2)
  tmp_df['NTT%'] = round((tmp_df['NTT'] - tmp_df['Close'])*100/tmp_df['Close'],2)
  tmp_df['LTT%'] = round((tmp_df['LTT'] - tmp_df['Close'])*100/tmp_df['Close'],2)
  tmp_df['Gained%'] = round((tmp_df['Close'] - tmp_df['BOL'])*100/tmp_df['BOL'],2)
  investment = round(sum(tmp_df['AvgCost']*tmp_df['Shares']),0)
  current = round(sum(tmp_df['Close']*tmp_df['Shares']),0)
  tmp_df['InitAlloc%'] = round(tmp_df['Investment']*100/investment,2)
  tmp_df['CurrAlloc%'] = round(tmp_df['Current']*100/current,2)
  tmp_df['FTT'] = tmp_df['LTT']
  tmp_df.loc[tmp_df['Strategy'] == 'NTT', 'FTT'] = tmp_df['NTT']
  tmp_df['FTT%'] = tmp_df['LTT%']
  tmp_df.loc[tmp_df['Strategy'] == 'NTT', 'FTT%'] = tmp_df['NTT%']
  tmp_df['FTT Amt'] = round(tmp_df['FTT%'] * tmp_df['Current']/100,0)
  tmp_df['OTT%'] = round((tmp_df['FTT'] - tmp_df['AvgCost'])*100/tmp_df['AvgCost'],2)
  tmp_df['RRR Ind'] = round(tmp_df['Current P/L']/tmp_df['FTT Amt'],2)
  tmp_df['Risk Ind'] = round(tmp_df['Current P/L%']*tmp_df['CurrAlloc%'],0)

  return tmp_df

# function to print portfolio features
def print_portfolio_stats(df_portfolio_features, myinvmt_df):
  from pyxirr import xirr

  total_booked_amt, reserve_amt, cy_booked_amt, py_booked_amt = get_amt()

  dates = myinvmt_df['Date'].values
  dates = np.append(dates, datetime.date.today().strftime('%d-%b-%y'))
  investment = myinvmt_df['Investment'].values
  dates= pd.to_datetime(dates)

  current = round(sum(df_portfolio_features['Close']*df_portfolio_features['Shares']),0) + reserve_amt
  investment_xirr = np.append(investment, current)
  cagr = round(xirr(pd.DataFrame({"dates": dates, "amounts": investment_xirr}))*100,2)

  investment = -sum(investment)
  invested = round(sum(df_portfolio_features['AvgCost']*df_portfolio_features['Shares']),0) + reserve_amt
  previous = round(sum(df_portfolio_features['Prev_Close']*df_portfolio_features['Shares']),0) + reserve_amt
  cy_invested = investment + py_booked_amt

  today_pnl_amount = current-previous
  today_pnl_percentage = round((current-previous)*100/previous,2)

  curr_pnl_amount = current-invested
  curr_pnl_percentage = round((curr_pnl_amount)*100/(cy_invested),2)

  cy_pnl_amount = cy_booked_amt + curr_pnl_amount
  cy_pnl_percentage = round((cy_pnl_amount)*100/cy_invested,2)

  overall_pnl_amount = total_booked_amt + curr_pnl_amount
  overall_pnl_percentage = round((overall_pnl_amount)*100/investment,2)

  estimate_st = round(sum(df_portfolio_features['FTT']*df_portfolio_features['Shares']),0)  + reserve_amt
  est_st_pnl_amount = estimate_st-current
  est_st_pnl_percentage = round((est_st_pnl_amount)*100/current,2)

  estimate_lt = round(sum(df_portfolio_features['LTT']*df_portfolio_features['Shares']),0)  + reserve_amt
  est_lt_pnl_amount = estimate_lt-current
  est_lt_pnl_percentage = round((est_lt_pnl_amount)*100/current,2)

  total_profit = round(sum(df_portfolio_features[df_portfolio_features['Current P/L%'] > 0]['Current']) - sum(df_portfolio_features[df_portfolio_features['Current P/L%'] > 0]['Investment']),0)
  total_loss = round(sum(df_portfolio_features[df_portfolio_features['Current P/L%'] < 0]['Current']) - sum(df_portfolio_features[df_portfolio_features['Current P/L%'] < 0]['Investment']),0)

  cy_booked_percentage = round((cy_booked_amt)*100/current,2)
  py_booked_percentage = round((py_booked_amt)*100/investment,2)
  total_booked_percentage = round((total_booked_amt)*100/investment,2)

  print('-------------------')
  print('Initial Investment: ', format_amt(investment))
  print('CY Investment: ', format_amt(cy_invested))
  print('Reserve: ', format_amt(reserve_amt))
  print('Current: ',  format_amt(current))
  print('-------------------')
  print('Today PnL: '+ '{} ({}%)'.format(format_amt(today_pnl_amount), today_pnl_percentage))
  print('Current PnL: '+ '{} ({}%)'.format(format_amt(curr_pnl_amount), curr_pnl_percentage))
  print('CY Booked + Current PnL: '+ '{} ({}%)'.format(format_amt(cy_pnl_amount), cy_pnl_percentage))
  print('-------------------')
  print('Total profit: ', format_amt(total_profit))
  print('Total loss: ', format_amt(total_loss))
  print('-------------------')
  print('Total Booked + Current PnL: '+ '{} ({}%)'.format(format_amt(overall_pnl_amount), overall_pnl_percentage))
  print('Total Booked PnL: '+ '{} ({}%)'.format(format_amt(total_booked_amt), total_booked_percentage))
  print('Curr Year Booked PnL: '+ '{} ({}%)'.format(format_amt(cy_booked_amt), cy_booked_percentage))
  print('Prev Year Booked PnL: '+ '{} ({}%)'.format(format_amt(py_booked_amt), py_booked_percentage))
  print('===================')
  print('Est FTT: ',  format_amt(estimate_st))
  print('Est FTT PnL: '+ '{} ({}%)'.format(format_amt(est_st_pnl_amount), est_st_pnl_percentage))

  print('===================')
  print('Deployed: ', format_amt(investment))

  print('Current: ', format_amt(current))

  print('CAGR/XIRR %: '+'{}%'.format(cagr))

In [8]:
# get start and end date
start_date, end_date = get_start_end_date()

# get portfolio and prospects data
mypfs_df = get_mypfs_df()
mypps_df = get_mypps_df()
myinvmt_df = get_myinvmt_df()

# merge above datasets
mypf_df = pd.merge(mypfs_df, mypps_df, on="Symbol")

# seggregate dm and sv portfolio
dm_pf = mypf_df[mypf_df['InPortfolio'] == 'DM']
sv_pf = mypf_df[mypf_df['InPortfolio'] == 'SV']

# build portfolio stock dataframe
dm_stocks = get_stock_ids(dm_pf)
sv_stocks = get_stock_ids(sv_pf)
df_stocks = pd.concat([dm_pf,sv_pf], ignore_index = True)

# arrange common and diff stock features
common_cols = ['Symbol', 'Target', 'Criteria', 'Strategy', 'CumlRnk', 'LatestQtr', 'StarStock', 'Conviction', 'Category', 'InFolio', 'XIRR', 'MBQ']
diff_cols = ['Symbol', 'AvgCost', 'Shares']
df_stocks = arrange_features(df_stocks, common_cols, diff_cols)

# get common features
stock_ids = df_stocks['Symbol'].values
df_common_features = get_common_features(stock_ids, df_stocks)

df_common_features.reset_index(drop=True, inplace=True)
df_common_features.drop(['Date'], axis=1, inplace=True)
# get and print portfolio features
df_portfolio_features = get_portfolio_features(df_common_features)

print_portfolio_stats(df_portfolio_features, myinvmt_df)

df = df_portfolio_features
#plot_pie_chart(df, 'CapType', 'Current')
list_ox40n = list(df[df['MBQ'].str.contains('OX40N', na=False)]['Symbol'].values)

Run date time (IST): 2026-08-03 17:51:18
-------------------
qualified stocks: 90
with latest results: 31
still star stocks: 20
-------------------
Initial Investment:  1.40 C
CY Investment:  1.82 C
Reserve:  6.53 L
Current:  1.56 C
-------------------
Today PnL: 2.08 L (1.35%)
Current PnL: -28.80 L (-15.79%)
CY Booked + Current PnL: -25.16 L (-13.8%)
-------------------
Total profit:  4.46 L
Total loss:  -33.27 L
-------------------
Total Booked + Current PnL: 17.71 L (12.69%)
Total Booked PnL: 46.51 L (33.34%)
Curr Year Booked PnL: 3.64 L (2.33%)
Prev Year Booked PnL: 42.87 L (30.73%)
===================
Est FTT:  2.55 C
Est FTT PnL: 98.60 L (63.25%)
===================
Deployed:  1.40 C
Current:  1.56 C
CAGR/XIRR %: 4.94%

In [9]:
# top 5 near their targets
cols = ['Symbol', 'Today P/L%', 'Current P/L%', 'FTT%', 'OTT%', 'FTT Amt', 'Current P/L', 'Current', 'FTT', 'Dev%_PE', 'RSI_14','Conviction', 'Spread%',  'CumlRnk', 'RRR Ind', 'CurrAlloc%', 'Gained%', 'Criteria', 'Strategy', 'Category']
df_tmp = df_portfolio_features[~df_portfolio_features['Symbol'].isin(['ENRIN','BLUSPRING','DIGITIDE'])]
df_tmp = df_tmp.sort_values(by = 'FTT Amt', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
58,PIDILITIND,1.93,16.40,0.96,17.52,1577.0,23140.0,164250.0,1658.32,-18.47,64.0,X-LC,8.49,5.0,14.67,1.10,29.89,X40,ATH,CHEMICALS
71,SONACOMS,2.03,35.80,2.13,38.69,2926.0,36216.0,137375.0,801.69,7.62,83.0,M-MC,29.59,193.0,12.38,0.92,94.90,AR,ATH,AUTO
55,MEDANTA,2.80,23.60,2.84,27.12,6196.0,41663.0,218180.0,1486.00,19.85,70.0,X-SC,13.67,87.0,6.72,1.46,50.34,XY24,NTT,HEALTHCARE
52,M&M,0.89,11.25,9.75,22.10,15043.0,15606.0,154287.0,3762.88,-5.74,68.0,X-LC,6.69,25.0,1.04,1.03,18.20,X40N,ATH,AUTO
81,TTKPRESTIG,0.42,-16.25,19.51,0.09,16467.0,-16374.0,84403.0,770.00,95.94,54.0,M-SC,13.34,250.0,-0.99,0.57,51.91,OX40N,NTT,DURABLES

In [10]:
# top 5 today
df_tmp = df_portfolio_features.sort_values(by = 'Today P/L%', ascending=False)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
5,ATULAUTO,9.29,-2.84,49.82,45.57,95425.0,-5593.0,191539.0,844.0,4164.86,77.0,M-SC,6.06,248.0,-0.06,1.28,47.40,XY24,NTT,AUTO
13,BSOFT,6.32,-41.71,154.93,48.59,127015.0,-58671.0,81982.0,819.6,-25.40,64.0,H-SC,19.69,172.0,-0.46,0.55,19.86,XR,ATH,IT
84,VALIANTORG,4.99,-41.81,199.29,74.15,189724.0,-68405.0,95200.0,838.0,-271.55,58.0,H-SC,4.03,145.0,-0.36,0.64,41.67,XR,NTT,CHEMICALS
18,COFFEEDAY,4.98,-45.84,149.77,35.27,92106.0,-52051.0,61498.0,80.0,-57.75,54.0,L-SC,5.19,266.0,-0.57,0.41,51.66,XR,NTT,HOTELS
46,IRCTC,4.84,-38.12,147.13,52.93,246297.0,-103107.0,167401.0,1269.0,-54.27,58.0,H-MC,15.38,119.0,-0.42,1.12,5.67,XY24,BTT,TRAVEL

In [11]:
# bottom 5 today
df_tmp = df_portfolio_features.sort_values(by = 'Today P/L%', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
41,IEX,-3.21,-13.13,71.09,48.63,123480.0,-26258.0,173696.0,219.00,-42.17,54.0,H-SC,3.18,137.0,-0.21,1.16,13.31,XR,NTT,MISC
43,INDIGOPNTS,-2.19,-22.75,29.48,0.02,39750.0,-39721.0,134838.0,1408.00,105.36,56.0,M-SC,4.19,222.0,-1.00,0.90,52.98,OX40N,NTT,PAINTS
72,STARHEALTH,-1.40,14.67,28.42,47.26,91619.0,41251.0,322374.0,761.00,81.04,54.0,H-SC,18.69,173.0,0.45,2.16,39.39,XY24,NTT,INSURANCE
62,RECLTD,-1.30,-0.35,21.16,20.74,42839.0,-715.0,202455.0,446.00,9.37,61.0,M-MC,2.42,191.0,-0.02,1.36,22.03,XY25,NTT,FINANCE
22,DIXON,-1.12,1.21,36.28,37.92,95760.0,3150.0,263948.0,18931.72,-56.95,57.0,X-MC,12.53,54.0,0.03,1.77,43.62,X40N,ATH,IT

In [12]:
# top 5 to exit based on CumlRnk
df_tmp = df_portfolio_features[~df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])]
df_tmp = df_tmp[(df_tmp['Current P/L%'] > -1) & (df_tmp['Current P/L%'] < 1)].sort_values(by = 'CumlRnk', ascending=False)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
62,RECLTD,-1.3,-0.35,21.16,20.74,42839.0,-715.0,202455.0,446.0,9.37,61.0,M-MC,2.42,191.0,-0.02,1.36,22.03,XY25,NTT,FINANCE

In [13]:
# OX40N stocks to exit
df_tmp = df_portfolio_features[(df_portfolio_features['Symbol'].isin(list_ox40n))].sort_values(by = 'Current P/L%', ascending=False)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
25,FINCABLES,1.06,26.41,64.48,107.91,120342.0,38991.0,186635.0,1641.55,13.65,44.0,M-SC,18.94,220.0,0.32,1.25,40.41,OX40N,ATH,CABLES
70,SIS,0.64,-2.37,24.21,21.26,26244.0,-2632.0,108400.0,528.00,2586.01,45.0,H-SC,23.53,168.0,-0.10,0.73,61.18,OX40N,NTT,MISC
81,TTKPRESTIG,0.42,-16.25,19.51,0.09,16467.0,-16374.0,84403.0,770.00,95.94,54.0,M-SC,13.34,250.0,-0.99,0.57,51.91,OX40N,NTT,DURABLES
16,CERA,2.52,-17.88,50.86,23.89,73468.0,-31451.0,144452.0,9475.00,-20.76,56.0,H-SC,13.18,153.0,-0.43,0.97,40.42,OX40N,NTT,CERAMICS
67,SFL,0.89,-22.20,62.76,26.63,128039.0,-58204.0,204014.0,1287.00,54.60,63.0,M-SC,25.52,242.0,-0.45,1.37,70.27,XY24,NTT,MISC

In [14]:
# top 5 to book for rotation
df_tmp = df_portfolio_features[(df_portfolio_features['Current P/L%'] > 20) ].sort_values(by = 'CumlRnk', ascending=False)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
25,FINCABLES,1.06,26.41,64.48,107.91,120342.0,38991.0,186635.0,1641.55,13.65,44.0,M-SC,18.94,220.0,0.32,1.25,40.41,OX40N,ATH,CABLES
71,SONACOMS,2.03,35.80,2.13,38.69,2926.0,36216.0,137375.0,801.69,7.62,83.0,M-MC,29.59,193.0,12.38,0.92,94.90,AR,ATH,AUTO
55,MEDANTA,2.80,23.60,2.84,27.12,6196.0,41663.0,218180.0,1486.00,19.85,70.0,X-SC,13.67,87.0,6.72,1.46,50.34,XY24,NTT,HEALTHCARE
59,QUESS,3.76,41.52,22.88,73.90,34579.0,44339.0,151132.0,424.00,-23.97,84.0,X-SC,38.02,80.0,1.28,1.01,106.02,XY24,NTT,MISC

In [15]:
# top 5 to monitor for exit
df_tmp = df_portfolio_features[~df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])]
df_tmp = df_tmp[(df_tmp['Current P/L%'] > 0) ].sort_values(by = 'Dev%_PE', ascending=False)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
72,STARHEALTH,-1.40,14.67,28.42,47.26,91619.0,41251.0,322374.0,761.00,81.04,54.0,H-SC,18.69,173.0,0.45,2.16,39.39,XY24,NTT,INSURANCE
25,FINCABLES,1.06,26.41,64.48,107.91,120342.0,38991.0,186635.0,1641.55,13.65,44.0,M-SC,18.94,220.0,0.32,1.25,40.41,OX40N,ATH,CABLES
71,SONACOMS,2.03,35.80,2.13,38.69,2926.0,36216.0,137375.0,801.69,7.62,83.0,M-MC,29.59,193.0,12.38,0.92,94.90,AR,ATH,AUTO
89,ZYDUSLIFE,-0.51,18.21,14.63,35.51,36245.0,38167.0,247741.0,1285.01,2.70,51.0,H-MC,16.64,120.0,1.05,1.66,30.37,AR,ATH,PHARMA

In [16]:
# top 5 to book for rotation from weak conviction
df_tmp = df_portfolio_features[~df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])]
df_tmp = df_tmp[~df_tmp['Criteria'].isin(['XY25','XY24','X40', 'X40N'])].sort_values(by = 'RRR Ind', ascending=False)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
71,SONACOMS,2.03,35.80,2.13,38.69,2926.0,36216.0,137375.0,801.69,7.62,83.0,M-MC,29.59,193.0,12.38,0.92,94.90,AR,ATH,AUTO
89,ZYDUSLIFE,-0.51,18.21,14.63,35.51,36245.0,38167.0,247741.0,1285.01,2.70,51.0,H-MC,16.64,120.0,1.05,1.66,30.37,AR,ATH,PHARMA
25,FINCABLES,1.06,26.41,64.48,107.91,120342.0,38991.0,186635.0,1641.55,13.65,44.0,M-SC,18.94,220.0,0.32,1.25,40.41,OX40N,ATH,CABLES
70,SIS,0.64,-2.37,24.21,21.26,26244.0,-2632.0,108400.0,528.00,2586.01,45.0,H-SC,23.53,168.0,-0.10,0.73,61.18,OX40N,NTT,MISC
54,MASFIN,-0.67,-2.74,24.99,21.57,23814.0,-2685.0,95295.0,397.04,-15.99,50.0,H-SC,1.69,167.0,-0.11,0.64,13.59,XR,ATH,FINANCE

In [17]:
# top 5 to accumulate based on lowest RSI_14
df_tmp = df_portfolio_features[df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])].sort_values(by = 'RSI_14', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
85,VBL,0.61,-10.11,50.43,35.22,143176.0,-31932.0,283910.0,669.42,-20.58,37.0,X-LC,7.66,13.0,-0.22,1.90,16.82,X40N,ATH,FMCG
57,PGHH,0.64,-35.19,103.69,32.01,143490.0,-75136.0,138384.0,17616.87,-56.12,40.0,X-MC,19.22,57.0,-0.52,0.93,2.03,X40,ATH,FMCG
34,HDFCBANK,0.65,-9.92,42.50,28.37,89927.0,-23292.0,211593.0,1073.00,-23.49,42.0,X-LC,10.10,26.0,-0.26,1.42,4.63,X40,BTT,BANKS
35,HDFCLIFE,0.84,-9.54,46.70,32.71,63283.0,-14290.0,135510.0,811.41,-29.34,44.0,X-LC,15.84,31.0,-0.23,0.91,1.80,X40,ATH,INSURANCE
26,GILLETTE,1.25,-8.79,42.23,29.72,97792.0,-22326.0,231570.0,10978.86,-29.98,47.0,X-SC,3.34,83.0,-0.23,1.55,6.42,X40,ATH,FMCG

In [18]:
# top 5 to accumulate based on Spread and CumlRnk
df_tmp = df_portfolio_features[df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])]
df_tmp = df_tmp[(df_tmp['CumlRnk'] < 100)].sort_values(by = 'Spread%', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
19,COLPAL,0.04,-21.14,77.34,39.86,160635.0,-55665.0,207700.0,3683.41,-4.51,51.0,X-MC,1.66,62.0,-0.35,1.39,17.49,XY25,ATH,FMCG
11,BERGEPAINT,1.17,-2.96,29.14,25.32,72882.0,-7638.0,250111.0,680.00,-8.32,61.0,X-MC,1.84,68.0,-0.10,1.67,30.17,XY24,NTT,PAINTS
8,BAJAJHLDNG,2.26,3.71,23.06,27.63,45470.0,7058.0,197183.0,14274.15,-4.11,74.0,X-LC,2.03,28.0,0.16,1.32,34.27,X40,ATH,FINANCE
23,DMART,2.40,-3.49,34.28,29.60,82581.0,-8700.0,240900.0,5391.45,-18.62,50.0,X-LC,2.96,14.0,-0.11,1.61,10.11,X40N,ATH,FMCG
17,CIPLA,0.08,19.37,11.78,33.43,21537.0,29665.0,182826.0,1648.14,-7.62,62.0,X-LC,3.05,18.0,1.38,1.22,24.81,X40N,ATH,PHARMA

In [19]:
# top 5 to accumulate based on lowest Gained%
df_tmp = df_portfolio_features[df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])].sort_values(by = 'Gained%', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
35,HDFCLIFE,0.84,-9.54,46.70,32.71,63283.0,-14290.0,135510.0,811.41,-29.34,44.0,X-LC,15.84,31.0,-0.23,0.91,1.80,X40,ATH,INSURANCE
57,PGHH,0.64,-35.19,103.69,32.01,143490.0,-75136.0,138384.0,17616.87,-56.12,40.0,X-MC,19.22,57.0,-0.52,0.93,2.03,X40,ATH,FMCG
47,ITC,2.14,-24.40,57.49,19.06,147837.0,-83014.0,257152.0,452.00,-58.35,55.0,X-LC,12.36,1.0,-0.56,1.72,4.16,X40,NTT,FMCG
34,HDFCBANK,0.65,-9.92,42.50,28.37,89927.0,-23292.0,211593.0,1073.00,-23.49,42.0,X-LC,10.10,26.0,-0.26,1.42,4.63,X40,BTT,BANKS
64,RELIANCE,0.86,-15.33,47.99,25.30,81655.0,-30812.0,170151.0,1952.00,-17.34,57.0,X-LC,7.80,21.0,-0.38,1.14,4.78,XY25,BTT,REFINERIES

In [20]:
# top 5 to accumulate based on lowest CurrAlloc%
df_tmp = df_portfolio_features[df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])].sort_values(by = 'CurrAlloc%', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
10,BATAINDIA,1.94,-54.22,195.36,35.20,115069.0,-69769.0,58901.0,2096.00,-22.74,60.0,X-SC,15.68,91.0,-0.61,0.39,18.34,X40,NTT,FOOTWEAR
63,RELAXO,1.18,-47.07,187.74,52.31,144252.0,-68324.0,76836.0,1176.00,-43.66,55.0,X-SC,9.93,92.0,-0.47,0.51,71.79,X40N,NTT,FOOTWEAR
35,HDFCLIFE,0.84,-9.54,46.70,32.71,63283.0,-14290.0,135510.0,811.41,-29.34,44.0,X-LC,15.84,31.0,-0.23,0.91,1.80,X40,ATH,INSURANCE
57,PGHH,0.64,-35.19,103.69,32.01,143490.0,-75136.0,138384.0,17616.87,-56.12,40.0,X-MC,19.22,57.0,-0.52,0.93,2.03,X40,ATH,FMCG
28,GODREJCP,1.45,-2.82,35.28,31.47,50953.0,-4189.0,144425.0,1469.04,2.21,59.0,X-LC,5.45,32.0,-0.08,0.97,10.81,X40N,ATH,FMCG

In [21]:
# top 5 to accumulate based on CumlRnk
df_tmp = df_portfolio_features.sort_values(by = 'CumlRnk', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
47,ITC,2.14,-24.40,57.49,19.06,147837.0,-83014.0,257152.0,452.00,-58.35,55.0,X-LC,12.36,1.0,-0.56,1.72,4.16,X40,NTT,FMCG
77,TCS,4.57,-27.38,71.03,24.20,238961.0,-126850.0,336423.0,4230.71,-38.38,69.0,X-LC,16.48,2.0,-0.53,2.25,25.45,X40,ATH,IT
45,INFY,4.42,-19.67,67.12,34.24,168699.0,-61548.0,251340.0,1972.00,-36.87,65.0,X-LC,17.61,3.0,-0.36,1.68,19.76,X40,NTT,IT
79,TMPV,2.81,-20.49,71.77,36.58,203061.0,-72908.0,282933.0,600.00,-83.62,58.0,X-LC,6.41,4.0,-0.36,1.89,18.91,XY24,NTT,AUTO
58,PIDILITIND,1.93,16.40,0.96,17.52,1577.0,23140.0,164250.0,1658.32,-18.47,64.0,X-LC,8.49,5.0,14.67,1.10,29.89,X40,ATH,CHEMICALS

In [22]:
# top 5 for average up
df_tmp = df_portfolio_features[(df_portfolio_features['Dev%_200'] > 5)].sort_values(by = 'CurrAlloc%', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
44,INDUSINDBK,1.62,-24.04,74.94,32.89,43950.0,-18560.0,58647.0,1800.00,-375.91,59.0,L-MC,14.52,258.0,-0.42,0.39,44.59,XR,NTT,BANKS
63,RELAXO,1.18,-47.07,187.74,52.31,144252.0,-68324.0,76836.0,1176.00,-43.66,55.0,X-SC,9.93,92.0,-0.47,0.51,71.79,X40N,NTT,FOOTWEAR
3,ALKYLAMINE,2.17,-22.30,147.80,92.54,115948.0,-22514.0,78449.0,4520.85,-16.74,51.0,H-SC,12.88,142.0,-0.19,0.53,48.97,SR,ATH,CHEMICALS
81,TTKPRESTIG,0.42,-16.25,19.51,0.09,16467.0,-16374.0,84403.0,770.00,95.94,54.0,M-SC,13.34,250.0,-0.99,0.57,51.91,OX40N,NTT,DURABLES
70,SIS,0.64,-2.37,24.21,21.26,26244.0,-2632.0,108400.0,528.00,2586.01,45.0,H-SC,23.53,168.0,-0.10,0.73,61.18,OX40N,NTT,MISC

In [23]:
# top 5 RSP
df_tmp = df_portfolio_features.sort_values(by = 'RSP', ascending=False)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
33,HCLTECH,2.23,-10.64,34.60,20.28,74801.0,-25735.0,216189.0,1853.42,-6.12,78.0,X-LC,14.84,8.0,-0.34,1.45,34.51,X40,ATH,IT
71,SONACOMS,2.03,35.80,2.13,38.69,2926.0,36216.0,137375.0,801.69,7.62,83.0,M-MC,29.59,193.0,12.38,0.92,94.90,AR,ATH,AUTO
77,TCS,4.57,-27.38,71.03,24.20,238961.0,-126850.0,336423.0,4230.71,-38.38,69.0,X-LC,16.48,2.0,-0.53,2.25,25.45,X40,ATH,IT
59,QUESS,3.76,41.52,22.88,73.90,34579.0,44339.0,151132.0,424.00,-23.97,84.0,X-SC,38.02,80.0,1.28,1.01,106.02,XY24,NTT,MISC
13,BSOFT,6.32,-41.71,154.93,48.59,127015.0,-58671.0,81982.0,819.60,-25.40,64.0,H-SC,19.69,172.0,-0.46,0.55,19.86,XR,ATH,IT

In [24]:
# Top N allocation
df_tmp = df_portfolio_features.sort_values(by = 'CurrAlloc%', ascending=False)
top_n_values = [10, 25, 50]

sum_df = pd.DataFrame({
    'Top_N': top_n_values,
    'Sum_Alloc%': [df_tmp['CurrAlloc%'].head(n).sum() for n in top_n_values]
})

sum_df

   Top_N  Sum_Alloc%
0     10       19.09
1     25       42.63
2     50       73.77

In [25]:
# market-cap-wise allocation
df_tmp = df_portfolio_features[cols]
df_tmp.groupby(df_tmp['Conviction'].str[-2:])['CurrAlloc%'].sum().sort_values(ascending=False)

Conviction
SC    42.20
LC    32.12
MC    25.67
Name: CurrAlloc%, dtype: float64

In [26]:
# criteria-wise allocation
df_portfolio_features.groupby('Criteria')['CurrAlloc%'].sum().sort_values(ascending=False)

Criteria
X40      26.19
XY24     26.14
X40N     16.44
XR        9.19
AR        7.34
OX40N     7.15
XY25      6.65
SR        0.89
Name: CurrAlloc%, dtype: float64

In [27]:
# conviction-wise allocation
df_portfolio_features.groupby('Conviction')['CurrAlloc%'].sum().sort_values(ascending=False)

Conviction
X-LC    29.93
H-SC    20.61
X-MC    20.22
X-SC    10.64
M-SC    10.39
H-MC     2.78
M-MC     2.28
H-LC     1.31
M-LC     0.88
L-SC     0.56
L-MC     0.39
Name: CurrAlloc%, dtype: float64

In [28]:
# sector-wise stats
df_tmp = df_portfolio_features.groupby('Category')[['CurrAlloc%', 'Current', 'Current P/L', 'FTT Amt']].sum().sort_values(by=['Current', 'Current P/L'], ascending=False)
df_tmp['Current P/L%'] = round(df_tmp['Current P/L'] * 100 / df_tmp['Current'], 2)
df_tmp['FTT%'] = round(df_tmp['FTT Amt'] * 100 / df_tmp['Current'], 2)
cols = ['CurrAlloc%', 'Current P/L%', 'FTT%']
df_tmp[cols].sort_values(by=['CurrAlloc%'], ascending=False)

               CurrAlloc%  Current P/L%    FTT%
Category
FMCG                14.44        -22.64   65.64
IT                  11.09        -36.03  103.25
FINANCE              9.06        -15.90   64.38
MISC                 7.65        -17.40   67.77
AUTO                 7.37          0.72   36.31
PAINTS               5.72        -15.21   34.86
BANKS                5.47        -11.16   62.53
PHARMA               5.43          8.64   19.01
INSURANCE            5.40         -2.77   37.43
ELECTRICAL           4.41         -7.48   45.12
CHEMICALS            2.27        -20.06   90.93
HEALTHCARE           2.22         -7.82   35.95
APPARELS             1.88          4.63   27.41
AC                   1.85        -15.54   46.87
BREWERIES            1.76         11.03    7.45
FOOTWEAR             1.75        -68.08  135.47
DURABLES             1.68        -54.88   92.56
TRAVEL               1.55        -92.97  189.60
CERAMICS             1.46        -40.66   83.39
ENGINEERING          1.31        -23.65   80.20
CABLES               1.25         20.89   64.48
JEWELLERY            1.15        -85.67  150.18
REFINERIES           1.14        -18.11   47.99
CEMENT               1.12        -59.83  179.40
ENTERTAINMENT        0.74        -74.59  178.71
TEXTILES             0.41        -49.76   92.46
HOTELS               0.41        -84.64  149.77

In [29]:
# money to be made criteria-wise
df_portfolio_features.groupby('Criteria')['FTT Amt'].agg(['sum', 'count']).sort_values(by='sum', ascending=False)

                sum  count
Criteria
XY24      3270301.0     20
X40       1751974.0     19
XR        1304774.0     13
AR        1077431.0      9
X40N      1003733.0     12
OX40N      724978.0     10
XY25       443216.0      5
SR         283843.0      2

In [30]:
# money to be made conviction-wise
df_portfolio_features.groupby('Conviction')['FTT Amt'].agg(['sum', 'count']).sort_values(by='sum', ascending=False)

                  sum  count
Conviction
H-SC        3274059.0     23
X-LC        1797293.0     21
X-MC        1434320.0     14
M-SC        1366166.0     14
X-SC        1211033.0      9
H-MC         282542.0      2
L-SC         206904.0      2
M-LC         160778.0      1
M-MC          45765.0      2
L-MC          43950.0      1
H-LC          37440.0      1

In [31]:
# money to be made criteria and conviction-wise
df_portfolio_features.groupby(['Conviction', 'Criteria'])['FTT Amt'].agg(['sum', 'count']).sort_values(by='sum', ascending=False)

                          sum  count
Conviction Criteria
H-SC       XY24      979578.0      5
           AR        925173.0      5
X-LC       X40       914181.0     10
M-SC       XY24      792418.0      6
H-SC       XR        783435.0      7
X-SC       XY24      703331.0      4
X-MC       X40       624932.0      7
X-LC       X40N      362678.0      6
X-MC       X40N      346214.0      3
X-LC       XY24      325825.0      2
M-SC       OX40N     308150.0      5
H-SC       OX40N     302030.0      4
X-SC       X40N      294841.0      3
H-SC       SR        283843.0      2
H-MC       XY24      246297.0      1
X-MC       XY25      240322.0      2
           XY24      222852.0      2
X-SC       X40       212861.0      2
M-SC       XR        189951.0      2
M-LC       XR        160778.0      1
X-LC       XY25      160055.0      2
L-SC       OX40N     114798.0      1
           XR         92106.0      1
M-SC       AR         75647.0      1
L-MC       XR         43950.0      1
M-MC       XY25       42839.0      1
H-LC       AR         37440.0      1
H-MC       AR         36245.0      1
X-LC       XR         34554.0      1
M-MC       AR          2926.0      1

In [32]:
# notebook execution time

end_time = time.time()
execution_time = round(end_time - start_time, 0)
print(f"Notebook execution time: {execution_time} seconds")

Notebook execution time: 27.0 seconds