<a href="https://colab.research.google.com/github/ankit-rathi/Quantvesting_v2/blob/main/myStocks_Portfolio_Analysis.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
'''
!pip install pandas==2.2.2 -qq
!pip install pyxirr -qq
!pip install ta -qq
!pip install yfinance==0.2.59 -qq
'''

'\n!pip install pandas==2.2.2 -qq\n!pip install pyxirr -qq\n!pip install ta -qq\n!pip install yfinance==0.2.59 -qq\n'

In [2]:
# import libraries

import numpy as np
import pandas as pd
import datetime
import warnings
warnings.filterwarnings('ignore')
import yfinance as yfin
import ta
import matplotlib.pyplot as plt
import requests

In [3]:
# notebook start time
import time
import datetime
import pytz

start_time = time.time()

# function to print date timestamp
def print_date_time():
  tz_NY = pytz.timezone('Asia/Kolkata')
  datetime_NY = datetime.datetime.now(tz_NY)
  print("Run date time (IST):", datetime_NY.strftime("%Y-%m-%d %H:%M:%S"))

In [4]:
# function to get booked and reserved amount
def get_amt():
  # fetch the JSON data from the URL
  url = "https://raw.githubusercontent.com/ankit-rathi/Tradevesting_v1/main/data/myPortfolioAmts.json"
  response = requests.get(url)
  pf_amts = response.json()  # parse the JSON data

  # extract values from the JSON
  py_booked_amt_dm = pf_amts["py_booked_amt_dm"]
  py_booked_amt_sv = pf_amts["py_booked_amt_sv"]
  cy_booked_amt_dm = pf_amts["cy_booked_amt_dm"]
  cy_booked_amt_sv = pf_amts["cy_booked_amt_sv"]
  reserve_amt_dm = pf_amts["reserve_amt_dm"]
  reserve_amt_sv = pf_amts["reserve_amt_sv"]

  # perform calculations
  py_booked_amt = py_booked_amt_dm + py_booked_amt_sv
  cy_booked_amt = cy_booked_amt_dm + cy_booked_amt_sv
  reserve_amt = reserve_amt_dm + reserve_amt_sv
  total_booked_amt = py_booked_amt + cy_booked_amt

  return total_booked_amt, reserve_amt, cy_booked_amt, py_booked_amt

gen_output = 0

In [5]:
# function to format the amount
def format_amt(number):
    abs_number = abs(number)

    if abs_number >= 1_00_00_000:  # Crores
        formatted_amt = f"{number / 1_00_00_000:.2f} C"
    elif abs_number >= 1_00_000:  # Lakhs
        formatted_amt = f"{number / 1_00_000:.2f} L"
    elif abs_number >= 1_000:  # Thousands
        formatted_amt = f"{number / 1_000:.2f} K"
    else:
        formatted_amt = f"{number:.2f}"

    return formatted_amt

# function to set start and end date
def get_start_end_date():
  start_date = (datetime.date.today() + datetime.timedelta(days=-365)).strftime('%Y-%m-%d')
  end_date = (datetime.date.today() + datetime.timedelta(days=1)).strftime('%Y-%m-%d')
  return start_date, end_date

# function to fetch my portfolio csv
def get_mypfs_df():
  mypfs_df = pd.read_csv('https://raw.githubusercontent.com/ankit-rathi/Tradevesting_v1/main/data/myPortfolioStocks.csv')
  return mypfs_df

# function to fetch my prospects csv
def get_mypps_df():
  mypps_df = pd.read_csv('https://raw.githubusercontent.com/ankit-rathi/Tradevesting_v1/main/data/myProspectsScrips.csv')
  return mypps_df

# function to fetch screener data
def get_myscreen_df():
  myscreen_df = pd.read_csv('https://raw.githubusercontent.com/ankit-rathi/Tradevesting_v1/main/data/myScreenerDB.csv')
  return myscreen_df

# function to fetch momentum data
def get_myinvmt_df():
  myinvmt_df = pd.read_csv('https://raw.githubusercontent.com/ankit-rathi/Tradevesting_v1/main/data/myInvestments.csv')
  return myinvmt_df

# function to get the stock ids
def get_stock_ids(df_pf):
  stock_n100 = df_pf['Symbol'].unique()

  exclude = ['CADILAHC','MMTC', 'MASFIN']

  stock_ids = df_pf[~df_pf['Symbol'].isin(exclude) ]['Symbol'].unique()

  #mypf = mypf[mypf.Forecast.notnull()]
  #stock_ids = mypf['Symbol'].unique()

  #stock_ids.sort()
  return stock_ids

# get features from screener data
def get_screener_features():
  myscreen_df = get_myscreen_df()
  cols = ['Symbol', 'EPS', 'MedPE', 'ROCE%', 'ROE%', 'CapType']
  return myscreen_df[cols]

# get relative strength
def get_relative_strength(stock_list):

    # Dictionary to store stock tickers and their corresponding percentage price change
    stock_changes = {}

    # Loop through each stock and fetch its price data
    for stock in stock_list:
        try:
            # Download the stock data for the given date range
            stock_data = yfin.Ticker(stock + '.NS').history(period='1mo', interval='1d')[map(str.title, ['open', 'close', 'low', 'high', 'volume'])]

            # Calculate the percentage change for the stock
            if len(stock_data) > 0:
                start_price = stock_data['Close'].iloc[0]
                end_price = stock_data['Close'].iloc[-1]
                percent_change = round(((end_price - start_price) / start_price) * 100, 2)
                stock_changes[stock] = percent_change
            else:
                stock_changes[stock] = np.nan  # If no data is available, set to NaN

        except Exception as e:
            print(f"Error fetching data for {stock}: {e}")
            stock_changes[stock] = np.nan

    # Create a DataFrame with stock tickers and their percentage changes
    df = pd.DataFrame(list(stock_changes.items()), columns=['Symbol', 'Percent_Change'])

    # Drop any stocks with missing data (NaN values)
    df = df.dropna()

    # Calculate the percentile rank based on percentage change
    df['RSP'] = round(df['Percent_Change'].rank(pct=True) * 100, 2)
    cols = ['Symbol', 'RSP']
    df = df[cols]
    # Sort by percentile rank (optional)
    df = df.sort_values(by='RSP', ascending=False).reset_index(drop=True)

    return df

In [6]:
# function to get stock technicals
def stock_prec_dev(stock_symbol):
    #stock_symbol = 'ULTRACEMCO.NS'
    short_window = 20
    mid_window = 50
    long_window = 200
    moving_avg = 'SMA'

    start = datetime.datetime(*map(int, start_date.split('-')))
    end = datetime.datetime(*map(int, end_date.split('-')))

    stock_df = yfin.Ticker(stock_symbol + '.NS').history(period='max', interval='1d')[map(str.title, ['open', 'close', 'low', 'high', 'volume'])]

    stock_df['Max'] = round(max(stock_df['Close']),2)
    stock_df = stock_df[(stock_df.index <= end_date) & (stock_df.index >= start_date)]
    stock_df['200_SMA'] = round(stock_df['Close'].rolling(window = 200, min_periods = 1).mean(),0)
    stock_df['Dev%_200'] = round((stock_df['Close'] - stock_df['200_SMA'])*100/stock_df['200_SMA'],2)
    stock_df.dropna(axis = 0, inplace = True) # remove any null rows

    stock_df['20_SMA'] = stock_df['Close'].rolling(window=20).mean()
    stock_df['50_SMA'] = stock_df['Close'].rolling(window=50).mean()
    stock_df['Symbol'] = stock_symbol

    stock_df['Close'] = round(stock_df['Close'],2)
    stock_df['Min'] = round(min(stock_df['Close']),2)
    stock_df['RSI_14'] = ta.momentum.RSIIndicator(close=stock_df['Close'], window=14).rsi()
    stock_df['RSI_14'] = round(stock_df['RSI_14'],0)
    stock_df['Prev_Close'] = stock_df['Close'].shift(1)
    stock_df.drop(['Open', 'Low', 'High', 'Volume'], axis=1, inplace=True)
    stock_df = stock_df.tail(1)

    max_SMA = max(stock_df['20_SMA'].item(), stock_df['50_SMA'].item(), stock_df['200_SMA'].item())
    min_SMA = min(stock_df['20_SMA'].item(), stock_df['50_SMA'].item(), stock_df['200_SMA'].item())
    ABS_Spread = max_SMA - min_SMA
    stock_df['Spread%'] = round((ABS_Spread / stock_df['200_SMA'].item()) * 100,2)

    return stock_df

# function to compute stock attributes
def get_common_features(stock_ids, df_mypf):

  df_prec_dev = pd.DataFrame()
  df_tmp = get_screener_features()
  df_rs = get_relative_strength(stock_ids)

  for stock_id in stock_ids:
      tmp = stock_prec_dev(stock_id)
      tmp = tmp.reset_index()
      df_prec_dev = pd.concat([df_prec_dev, tmp], ignore_index = True)
  df_prec_dev = pd.merge(df_prec_dev, df_mypf, on= 'Symbol')
  df_prec_dev = pd.merge(df_prec_dev, df_tmp, on= 'Symbol', how='left')
  df_prec_dev = pd.merge(df_prec_dev, df_rs, on= 'Symbol', how='left')
  #print(df_prec_dev.columns)
  df_prec_dev['Curr_PE'] = round(df_prec_dev['Close']/df_prec_dev['EPS'],1)
  df_prec_dev['Dev%_PE'] = round((df_prec_dev['Curr_PE'] - df_prec_dev['MedPE'])*100/df_prec_dev['MedPE'],2)
  df_prec_dev['Conviction'] = df_prec_dev['Conviction'] + '-' + df_prec_dev['CapType']
  return df_prec_dev

# function to arrange stock features
def arrange_features(df_stocks, common_cols, diff_cols):
  df_stocks_common = df_stocks[common_cols].drop_duplicates()
  df_stocks_diff = df_stocks[diff_cols]
  df_stocks_diff['Investment'] = df_stocks_diff['AvgCost'] * df_stocks_diff['Shares']
  df_stocks_diff = df_stocks_diff.groupby(['Symbol'])[['Shares', 'Investment']].aggregate(['sum']).reset_index()
  df_stocks_diff.columns = ['Symbol', 'Shares', 'Investment']
  df_stocks_diff['AvgCost'] = round(df_stocks_diff['Investment']/df_stocks_diff['Shares'],2)
  df_stocks = pd.merge(df_stocks_diff, df_stocks_common, on='Symbol')
  return df_stocks

# plot fact distribution across dimension
def plot_pie_chart(df, dimension, fact):
  # grouping the data by category and calculating the sum of fact for each type
  grouped_data = df.groupby(dimension)[fact].sum()

  # sorting the grouped data in descending order
  grouped_data = grouped_data.sort_values(ascending=False)

  # creating a pie chart
  grouped_data.plot.pie(autopct='%1.1f%%', startangle=90, figsize=(6, 6))

  # adding a title and displaying the plot
  plt.title(f'{dimension} {fact} Distribution')
  plt.ylabel('')  # To hide the y-label
  plt.show()

In [7]:
# function to get portfolio features

def get_portfolio_features(df_common_features):

  print_date_time()
  print('-------------------')

  #df_common_features["Target"] = df_common_features["Target"].fillna(df_common_features["Max"])
  df_common_features['NTT'] = np.where(df_common_features['Strategy']== 'NTT', df_common_features["Target"], df_common_features['Max'])
  df_common_features['LTT'] = np.where(df_common_features['Strategy']== 'BTT', df_common_features["Target"], df_common_features['Max'])
  df_common_features['BOL'] = df_common_features['Min']

  tmp_df = df_common_features[df_common_features['Symbol'].isin(mypf_df[mypf_df['InPortfolio'] != 'NA'].Symbol.values)]
  print('qualified stocks: '+str(len(tmp_df['Symbol'].unique())))
  tmp_df1 = tmp_df[tmp_df['LatestQtr'] == 1]
  print('with latest results: '+str(len(tmp_df1['Symbol'].unique())))
  tmp_df1 = tmp_df1[tmp_df1['StarStock'] == 1]
  print('still star stocks: '+str(len(tmp_df1['Symbol'].unique())))
  tmp_df['Investment'] = tmp_df['AvgCost'] * tmp_df['Shares']
  tmp_df['Current'] = round(tmp_df['Close'] * tmp_df['Shares'],0)
  tmp_df['Previous'] = tmp_df['Prev_Close'] * tmp_df['Shares']
  tmp_df['EstimatedST'] = tmp_df['NTT'] * tmp_df['Shares']
  tmp_df['EstimatedLT'] = tmp_df['LTT'] * tmp_df['Shares']
  tmp_df['Current P/L'] = round((tmp_df['Current'] - tmp_df['Investment']),0)
  tmp_df['Today P/L%'] = round((tmp_df['Current'] - tmp_df['Previous'])*100/tmp_df['Previous'],2)
  tmp_df['Current P/L%'] = round((tmp_df['Current'] - tmp_df['Investment'])*100/tmp_df['Investment'],2)
  tmp_df['EstimatedST P/L%'] = round((tmp_df['EstimatedST'] - tmp_df['Investment'])*100/tmp_df['Investment'],2)
  tmp_df['EstimatedLT P/L%'] = round((tmp_df['EstimatedLT'] - tmp_df['Investment'])*100/tmp_df['Investment'],2)
  tmp_df['NTT%'] = round((tmp_df['NTT'] - tmp_df['Close'])*100/tmp_df['Close'],2)
  tmp_df['LTT%'] = round((tmp_df['LTT'] - tmp_df['Close'])*100/tmp_df['Close'],2)
  tmp_df['Gained%'] = round((tmp_df['Close'] - tmp_df['BOL'])*100/tmp_df['BOL'],2)
  investment = round(sum(tmp_df['AvgCost']*tmp_df['Shares']),0)
  current = round(sum(tmp_df['Close']*tmp_df['Shares']),0)
  tmp_df['InitAlloc%'] = round(tmp_df['Investment']*100/investment,2)
  tmp_df['CurrAlloc%'] = round(tmp_df['Current']*100/current,2)
  tmp_df['FTT'] = tmp_df['LTT']
  tmp_df.loc[tmp_df['Strategy'] == 'NTT', 'FTT'] = tmp_df['NTT']
  tmp_df['FTT%'] = tmp_df['LTT%']
  tmp_df.loc[tmp_df['Strategy'] == 'NTT', 'FTT%'] = tmp_df['NTT%']
  tmp_df['FTT Amt'] = round(tmp_df['FTT%'] * tmp_df['Current']/100,0)
  tmp_df['OTT%'] = round((tmp_df['FTT'] - tmp_df['AvgCost'])*100/tmp_df['AvgCost'],2)
  tmp_df['RRR Ind'] = round(tmp_df['Current P/L']/tmp_df['FTT Amt'],2)
  tmp_df['Risk Ind'] = round(tmp_df['Current P/L%']*tmp_df['CurrAlloc%'],0)

  return tmp_df

# function to print portfolio features
def print_portfolio_stats(df_portfolio_features, myinvmt_df):
  from pyxirr import xirr

  total_booked_amt, reserve_amt, cy_booked_amt, py_booked_amt = get_amt()

  dates = myinvmt_df['Date'].values
  dates = np.append(dates, datetime.date.today().strftime('%d-%b-%y'))
  investment = myinvmt_df['Investment'].values
  dates= pd.to_datetime(dates)

  current = round(sum(df_portfolio_features['Close']*df_portfolio_features['Shares']),0) + reserve_amt
  investment_xirr = np.append(investment, current)
  cagr = round(xirr(pd.DataFrame({"dates": dates, "amounts": investment_xirr}))*100,2)

  investment = -sum(investment)
  invested = round(sum(df_portfolio_features['AvgCost']*df_portfolio_features['Shares']),0) + reserve_amt
  previous = round(sum(df_portfolio_features['Prev_Close']*df_portfolio_features['Shares']),0) + reserve_amt
  cy_invested = investment + py_booked_amt

  today_pnl_amount = current-previous
  today_pnl_percentage = round((current-previous)*100/previous,2)

  curr_pnl_amount = current-invested
  curr_pnl_percentage = round((curr_pnl_amount)*100/(cy_invested),2)

  cy_pnl_amount = cy_booked_amt + curr_pnl_amount
  cy_pnl_percentage = round((cy_pnl_amount)*100/cy_invested,2)

  overall_pnl_amount = total_booked_amt + curr_pnl_amount
  overall_pnl_percentage = round((overall_pnl_amount)*100/investment,2)

  estimate_st = round(sum(df_portfolio_features['FTT']*df_portfolio_features['Shares']),0)  + reserve_amt
  est_st_pnl_amount = estimate_st-current
  est_st_pnl_percentage = round((est_st_pnl_amount)*100/current,2)

  estimate_lt = round(sum(df_portfolio_features['LTT']*df_portfolio_features['Shares']),0)  + reserve_amt
  est_lt_pnl_amount = estimate_lt-current
  est_lt_pnl_percentage = round((est_lt_pnl_amount)*100/current,2)

  total_profit = round(sum(df_portfolio_features[df_portfolio_features['Current P/L%'] > 0]['Current']) - sum(df_portfolio_features[df_portfolio_features['Current P/L%'] > 0]['Investment']),0)
  total_loss = round(sum(df_portfolio_features[df_portfolio_features['Current P/L%'] < 0]['Current']) - sum(df_portfolio_features[df_portfolio_features['Current P/L%'] < 0]['Investment']),0)

  cy_booked_percentage = round((cy_booked_amt)*100/current,2)
  py_booked_percentage = round((py_booked_amt)*100/investment,2)
  total_booked_percentage = round((total_booked_amt)*100/investment,2)

  print('-------------------')
  print('Initial Investment: ', format_amt(investment))
  print('CY Investment: ', format_amt(cy_invested))
  print('Reserve: ', format_amt(reserve_amt))
  print('Current: ',  format_amt(current))
  print('-------------------')
  print('Today PnL: '+ '{} ({}%)'.format(format_amt(today_pnl_amount), today_pnl_percentage))
  print('Current PnL: '+ '{} ({}%)'.format(format_amt(curr_pnl_amount), curr_pnl_percentage))
  print('CY Booked + Current PnL: '+ '{} ({}%)'.format(format_amt(cy_pnl_amount), cy_pnl_percentage))
  print('-------------------')
  print('Total profit: ', format_amt(total_profit))
  print('Total loss: ', format_amt(total_loss))
  print('-------------------')
  print('Total Booked + Current PnL: '+ '{} ({}%)'.format(format_amt(overall_pnl_amount), overall_pnl_percentage))
  print('Total Booked PnL: '+ '{} ({}%)'.format(format_amt(total_booked_amt), total_booked_percentage))
  print('Curr Year Booked PnL: '+ '{} ({}%)'.format(format_amt(cy_booked_amt), cy_booked_percentage))
  print('Prev Year Booked PnL: '+ '{} ({}%)'.format(format_amt(py_booked_amt), py_booked_percentage))
  print('===================')
  print('Est FTT: ',  format_amt(estimate_st))
  print('Est FTT PnL: '+ '{} ({}%)'.format(format_amt(est_st_pnl_amount), est_st_pnl_percentage))

  print('===================')
  print('Deployed: ', format_amt(investment))

  print('Current: ', format_amt(current))

  print('CAGR/XIRR %: '+'{}%'.format(cagr))

In [8]:
# get start and end date
start_date, end_date = get_start_end_date()

# get portfolio and prospects data
mypfs_df = get_mypfs_df()
mypps_df = get_mypps_df()
myinvmt_df = get_myinvmt_df()

# merge above datasets
mypf_df = pd.merge(mypfs_df, mypps_df, on="Symbol")

# seggregate dm and sv portfolio
dm_pf = mypf_df[mypf_df['InPortfolio'] == 'DM']
sv_pf = mypf_df[mypf_df['InPortfolio'] == 'SV']

# build portfolio stock dataframe
dm_stocks = get_stock_ids(dm_pf)
sv_stocks = get_stock_ids(sv_pf)
df_stocks = pd.concat([dm_pf,sv_pf], ignore_index = True)

# arrange common and diff stock features
common_cols = ['Symbol', 'Target', 'Criteria', 'Strategy', 'CumlRnk', 'LatestQtr', 'StarStock', 'Conviction', 'Category', 'InFolio', 'XIRR', 'MBQ']
diff_cols = ['Symbol', 'AvgCost', 'Shares']
df_stocks = arrange_features(df_stocks, common_cols, diff_cols)

# get common features
stock_ids = df_stocks['Symbol'].values
df_common_features = get_common_features(stock_ids, df_stocks)

df_common_features.reset_index(drop=True, inplace=True)
df_common_features.drop(['Date'], axis=1, inplace=True)
# get and print portfolio features
df_portfolio_features = get_portfolio_features(df_common_features)

print_portfolio_stats(df_portfolio_features, myinvmt_df)

df = df_portfolio_features
#plot_pie_chart(df, 'CapType', 'Current')
list_ox40n = list(df[df['MBQ'].str.contains('OX40N', na=False)]['Symbol'].values)

Run date time (IST): 2026-05-19 15:38:34
-------------------
qualified stocks: 92
with latest results: 31
still star stocks: 20

-------------------
Initial Investment:  1.40 C
CY Investment:  1.82 C
Reserve:  1.49 K
Current:  1.48 C
-------------------
Today PnL: 1.17 L (0.8%)
Current PnL: -35.03 L (-19.21%)
CY Booked + Current PnL: -32.95 L (-18.07%)
-------------------
Total profit:  1.99 L
Total loss:  -37.02 L
-------------------
Total Booked + Current PnL: 9.92 L (7.11%)
Total Booked PnL: 44.95 L (32.22%)
Curr Year Booked PnL: 2.08 L (1.4%)
Prev Year Booked PnL: 42.87 L (30.73%)
===================
Est FTT:  2.55 C
Est FTT PnL: 1.07 C (72.42%)
===================
Deployed:  1.40 C
Current:  1.48 C
CAGR/XIRR %: 2.92%

In [9]:
# top 5 near their targets
cols = ['Symbol', 'Today P/L%', 'Current P/L%', 'FTT%', 'OTT%', 'FTT Amt', 'Current P/L', 'Current', 'FTT', 'Dev%_PE', 'RSI_14','Conviction', 'Spread%',  'CumlRnk', 'RRR Ind', 'CurrAlloc%', 'Gained%', 'Criteria', 'Strategy', 'Category']
df_tmp = df_portfolio_features[~df_portfolio_features['Symbol'].isin(['ENRIN','BLUSPRING','DIGITIDE'])]
df_tmp = df_tmp.sort_values(by = 'FTT Amt', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
59,PIDILITIND,0.39,3.17,14.73,18.37,21444.0,4470.0,145580.0,1670.26,-27.76,58.0,X-LC,5.61,5.0,0.21,0.98,14.31,X40,ATH,CHEMICALS
55,MASFIN,-0.18,-4.29,27.01,21.57,25330.0,-4200.0,93780.0,397.04,-17.34,40.0,H-SC,5.64,167.0,-0.17,0.63,15.79,XR,ATH,FINANCE
51,KOTAKBANK,-2.51,2.06,18.66,21.11,26371.0,2850.0,141322.0,453.24,-12.44,52.0,X-LC,7.61,12.0,0.11,0.95,8.08,X40,ATH,BANKS
17,CIPLA,-1.15,14.14,18.00,34.69,31467.0,21654.0,174815.0,1663.60,-11.85,65.0,X-LC,10.59,18.0,0.69,1.18,18.23,X40N,ATH,PHARMA
72,SIS,2.45,-7.16,30.61,21.26,31554.0,-7948.0,103084.0,528.00,2454.40,70.0,H-SC,14.67,168.0,-0.25,0.70,53.27,OX40N,NTT,MISC

In [10]:
# top 5 today
df_tmp = df_portfolio_features.sort_values(by = 'Today P/L%', ascending=False)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
85,VAIBHAVGBL,6.31,-30.94,132.81,60.77,167630.0,-56557.0,126218.0,521.00,45.45,54.0,H-SC,6.48,160.0,-0.34,0.85,27.62,XR,NTT,JEWELLERY
77,TANLA,5.75,-40.87,267.38,117.25,428113.0,-110647.0,160114.0,1922.32,-40.45,54.0,H-SC,14.31,147.0,-0.26,1.08,40.18,AR,ATH,IT
45,INFY,4.76,-18.52,64.76,34.24,165099.0,-57948.0,254940.0,1972.00,-35.78,51.0,X-LC,18.98,3.0,-0.35,1.72,9.31,X40,NTT,IT
21,DEN,4.72,-49.16,179.43,42.07,77054.0,-41520.0,42944.0,75.00,52.85,48.0,M-SC,13.15,235.0,-0.54,0.29,16.80,AR,NTT,ENTERTAINMENT
88,VOLTAS,3.98,1.90,42.48,45.20,83002.0,3648.0,195390.0,1856.00,16.67,44.0,X-MC,1.20,79.0,0.04,1.32,6.75,XY25,NTT,AC

In [11]:
# bottom 5 today
df_tmp = df_portfolio_features.sort_values(by = 'Today P/L%', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
29,GREENPANEL,-3.79,-51.24,193.59,43.14,172798.0,-93818.0,89260.0,537.00,99.61,28.0,M-SC,16.56,225.0,-0.54,0.60,7.22,XY24,NTT,MISC
11,BERGEPAINT,-3.22,-6.44,33.94,25.32,81849.0,-16591.0,241158.0,680.00,-11.47,59.0,X-MC,10.75,68.0,-0.20,1.63,25.51,XY24,NTT,PAINTS
24,EASEMYTRIP,-3.16,-56.02,231.24,45.70,179838.0,-99044.0,77771.0,26.40,-19.28,53.0,M-SC,6.99,204.0,-0.55,0.53,36.24,XY24,NTT,TRAVEL
51,KOTAKBANK,-2.51,2.06,18.66,21.11,26371.0,2850.0,141322.0,453.24,-12.44,52.0,X-LC,7.61,12.0,0.11,0.95,8.08,X40,ATH,BANKS
69,SFL,-1.96,-42.29,119.42,26.63,180718.0,-110888.0,151330.0,1287.00,14.70,60.0,M-SC,12.62,242.0,-0.61,1.02,26.13,XY24,NTT,MISC

In [12]:
# top 5 to exit based on CumlRnk
df_tmp = df_portfolio_features[~df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])]
df_tmp = df_tmp[(df_tmp['Current P/L%'] > -1) & (df_tmp['Current P/L%'] < 1)].sort_values(by = 'CumlRnk', ascending=False)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
73,SONACOMS,2.15,0.29,38.68,39.09,39243.0,297.0,101456.0,804.02,-20.47,53.0,M-MC,19.15,193.0,0.01,0.68,43.52,AR,ATH,AUTO
74,STARHEALTH,3.50,0.06,47.17,47.26,132690.0,179.0,281302.0,761.00,57.86,59.0,H-SC,10.16,173.0,0.00,1.90,23.50,XY24,NTT,INSURANCE

In [13]:
# OX40N stocks to exit
df_tmp = df_portfolio_features[(df_portfolio_features['Symbol'].isin(list_ox40n))].sort_values(by = 'Current P/L%', ascending=False)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
25,FINCABLES,3.26,33.78,55.41,107.91,109445.0,49875.0,197519.0,1641.55,20.24,59.0,M-SC,24.67,220.0,0.46,1.33,48.60,OX40N,ATH,CABLES
72,SIS,2.45,-7.16,30.61,21.26,31554.0,-7948.0,103084.0,528.00,2454.40,70.0,H-SC,14.67,168.0,-0.25,0.70,53.27,OX40N,NTT,MISC
16,CERA,3.87,-24.51,64.11,23.89,85132.0,-43113.0,132790.0,9475.00,-27.21,61.0,H-SC,8.30,153.0,-0.51,0.90,27.61,OX40N,NTT,CERAMICS
50,KANSAINER,-1.02,-28.07,57.77,13.47,112050.0,-75708.0,193959.0,340.00,-38.12,60.0,H-SC,14.45,162.0,-0.68,1.31,35.48,XY24,NTT,PAINTS
83,TTKPRESTIG,1.38,-32.09,47.40,0.09,32438.0,-32343.0,68434.0,770.00,58.80,54.0,M-SC,16.67,250.0,-1.00,0.46,21.86,OX40N,NTT,DURABLES

In [14]:
# top 5 to book for rotation
df_tmp = df_portfolio_features[(df_portfolio_features['Current P/L%'] > 20) ].sort_values(by = 'CumlRnk', ascending=False)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
25,FINCABLES,3.26,33.78,55.41,107.91,109445.0,49875.0,197519.0,1641.55,20.24,59.0,M-SC,24.67,220.0,0.46,1.33,48.6,OX40N,ATH,CABLES
68,SATIN,1.34,23.19,23.25,51.83,79133.0,64073.0,340357.0,274.00,10.38,77.0,H-SC,28.31,159.0,0.81,2.30,65.8,XY24,NTT,FINANCE

In [15]:
# top 5 to monitor for exit
df_tmp = df_portfolio_features[~df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])]
df_tmp = df_tmp[(df_tmp['Current P/L%'] > 0) ].sort_values(by = 'Dev%_PE', ascending=False)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
74,STARHEALTH,3.50,0.06,47.17,47.26,132690.0,179.0,281302.0,761.00,57.86,59.0,H-SC,10.16,173.0,0.00,1.90,23.50,XY24,NTT,INSURANCE
25,FINCABLES,3.26,33.78,55.41,107.91,109445.0,49875.0,197519.0,1641.55,20.24,59.0,M-SC,24.67,220.0,0.46,1.33,48.60,OX40N,ATH,CABLES
68,SATIN,1.34,23.19,23.25,51.83,79133.0,64073.0,340357.0,274.00,10.38,77.0,H-SC,28.31,159.0,0.81,2.30,65.80,XY24,NTT,FINANCE
91,ZYDUSLIFE,2.81,7.44,26.23,35.63,59064.0,15603.0,225177.0,1286.17,-6.31,68.0,H-MC,2.71,120.0,0.26,1.52,18.39,AR,ATH,PHARMA
73,SONACOMS,2.15,0.29,38.68,39.09,39243.0,297.0,101456.0,804.02,-20.47,53.0,M-MC,19.15,193.0,0.01,0.68,43.52,AR,ATH,AUTO

In [16]:
# top 5 to book for rotation from weak conviction
df_tmp = df_portfolio_features[~df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])]
df_tmp = df_tmp[~df_tmp['Criteria'].isin(['XY25','XY24','X40', 'X40N'])].sort_values(by = 'RRR Ind', ascending=False)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
25,FINCABLES,3.26,33.78,55.41,107.91,109445.0,49875.0,197519.0,1641.55,20.24,59.0,M-SC,24.67,220.0,0.46,1.33,48.60,OX40N,ATH,CABLES
91,ZYDUSLIFE,2.81,7.44,26.23,35.63,59064.0,15603.0,225177.0,1286.17,-6.31,68.0,H-MC,2.71,120.0,0.26,1.52,18.39,AR,ATH,PHARMA
73,SONACOMS,2.15,0.29,38.68,39.09,39243.0,297.0,101456.0,804.02,-20.47,53.0,M-MC,19.15,193.0,0.01,0.68,43.52,AR,ATH,AUTO
42,INDIAMART,1.72,-14.80,142.64,106.72,149883.0,-18258.0,105078.0,4810.62,-61.52,37.0,H-SC,9.87,140.0,-0.12,0.71,1.72,AR,ATH,MISC
55,MASFIN,-0.18,-4.29,27.01,21.57,25330.0,-4200.0,93780.0,397.04,-17.34,40.0,H-SC,5.64,167.0,-0.17,0.63,15.79,XR,ATH,FINANCE

In [17]:
# top 5 to accumulate based on lowest RSI_14
df_tmp = df_portfolio_features[df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])].sort_values(by = 'RSI_14', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
65,RELIANCE,-0.99,-15.09,47.58,25.30,81185.0,-30335.0,170628.0,1952.00,-17.34,36.0,X-LC,3.59,21.0,-0.37,1.15,1.39,XY25,BTT,REFINERIES
26,GILLETTE,-0.90,-9.46,43.28,29.72,99490.0,-24021.0,229875.0,10978.86,-30.50,38.0,X-SC,8.80,83.0,-0.24,1.55,5.64,X40,ATH,FMCG
58,PGHH,0.38,-27.27,81.50,32.01,126566.0,-58224.0,155296.0,17616.87,-50.75,39.0,X-MC,16.96,57.0,-0.46,1.05,6.22,X40,ATH,FMCG
10,BATAINDIA,1.68,-55.44,203.44,35.20,116636.0,-71338.0,57332.0,2096.00,-24.77,40.0,X-SC,26.10,91.0,-0.61,0.39,13.70,X40,NTT,FOOTWEAR
38,HYUNDAI,-0.09,-5.35,57.80,49.35,84379.0,-8256.0,145985.0,2809.30,-23.56,40.0,X-LC,17.62,29.0,-0.10,0.99,5.26,X40N,ATH,AUTO

In [18]:
# top 5 to accumulate based on Spread and CumlRnk
df_tmp = df_portfolio_features[df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])]
df_tmp = df_tmp[(df_tmp['CumlRnk'] < 100)].sort_values(by = 'Spread%', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
88,VOLTAS,3.98,1.90,42.48,45.20,83002.0,3648.0,195390.0,1856.00,16.67,44.0,X-MC,1.20,79.0,0.04,1.32,6.75,XY25,NTT,AC
84,UNITDSPR,-0.82,-4.14,25.99,20.77,58333.0,-9701.0,224443.0,1644.00,-14.95,50.0,X-MC,3.20,64.0,-0.17,1.52,7.06,X40N,NTT,BREWERIES
65,RELIANCE,-0.99,-15.09,47.58,25.30,81185.0,-30335.0,170628.0,1952.00,-17.34,36.0,X-LC,3.59,21.0,-0.37,1.15,1.39,XY25,BTT,REFINERIES
39,ICICIGI,0.54,-3.44,23.60,19.34,45599.0,-6892.0,193217.0,2252.93,-18.85,53.0,X-MC,4.89,66.0,-0.15,1.30,7.92,X40,ATH,INSURANCE
19,COLPAL,1.72,-16.91,70.31,41.51,153859.0,-44535.0,218830.0,3726.84,0.65,61.0,X-MC,5.45,62.0,-0.29,1.48,22.34,XY25,ATH,FMCG

In [19]:
# top 5 to accumulate based on lowest Gained%
df_tmp = df_portfolio_features[df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])].sort_values(by = 'Gained%', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
65,RELIANCE,-0.99,-15.09,47.58,25.30,81185.0,-30335.0,170628.0,1952.00,-17.34,36.0,X-LC,3.59,21.0,-0.37,1.15,1.39,XY25,BTT,REFINERIES
32,HAVELLS,1.04,-22.71,70.88,32.08,179689.0,-74479.0,253512.0,2062.85,-27.23,42.0,X-MC,11.83,63.0,-0.41,1.71,2.25,X40,ATH,ELECTRICAL
79,TCS,1.92,-31.68,85.28,26.57,269899.0,-146787.0,316486.0,4311.59,-42.31,40.0,X-LC,16.55,2.0,-0.54,2.14,3.61,X40,ATH,IT
40,ICICIPRULI,1.31,-13.60,51.30,30.73,87323.0,-26784.0,170221.0,790.00,-36.85,41.0,X-MC,11.87,78.0,-0.31,1.15,3.72,X40,ATH,INSURANCE
48,JIOFIN,0.28,-22.59,65.90,28.43,152194.0,-67380.0,230947.0,387.00,-23.79,42.0,X-LC,15.62,34.0,-0.44,1.56,4.10,XY24,BTT,FINANCE

In [20]:
# top 5 to accumulate based on lowest CurrAlloc%
df_tmp = df_portfolio_features[df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])].sort_values(by = 'CurrAlloc%', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
64,RELAXO,1.20,-62.34,304.47,52.31,166426.0,-90499.0,54661.0,1176.00,-59.93,45.0,X-SC,25.14,92.0,-0.54,0.37,22.22,X40N,NTT,FOOTWEAR
10,BATAINDIA,1.68,-55.44,203.44,35.20,116636.0,-71338.0,57332.0,2096.00,-24.77,40.0,X-SC,26.10,91.0,-0.61,0.39,13.70,X40,NTT,FOOTWEAR
60,QUESS,2.84,-15.73,106.37,73.90,95723.0,-16802.0,89991.0,424.00,-54.82,53.0,X-SC,11.44,80.0,-0.18,0.61,22.68,XY24,NTT,MISC
28,GODREJCP,0.75,-8.54,43.74,31.47,59454.0,-12688.0,135926.0,1469.04,-3.82,42.0,X-LC,7.93,32.0,-0.21,0.92,4.29,X40N,ATH,FMCG
53,M&M,0.28,0.34,22.96,23.38,31950.0,473.0,139154.0,3802.40,-14.78,45.0,X-LC,8.57,25.0,0.01,0.94,5.50,X40N,ATH,AUTO

In [21]:
# top 5 to accumulate based on CumlRnk
df_tmp = df_portfolio_features.sort_values(by = 'CumlRnk', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
47,ITC,0.05,-18.27,45.67,19.06,126976.0,-62137.0,278029.0,452.00,-55.12,55.0,X-LC,15.31,1.0,-0.49,1.88,7.86,X40,NTT,FMCG
79,TCS,1.92,-31.68,85.28,26.57,269899.0,-146787.0,316486.0,4311.59,-42.31,40.0,X-LC,16.55,2.0,-0.54,2.14,3.61,X40,ATH,IT
45,INFY,4.76,-18.52,64.76,34.24,165099.0,-57948.0,254940.0,1972.00,-35.78,51.0,X-LC,18.98,3.0,-0.35,1.72,9.31,X40,NTT,IT
81,TMPV,2.28,-17.78,66.11,36.58,193419.0,-63269.0,292572.0,600.00,-82.53,59.0,X-LC,6.20,4.0,-0.33,1.98,21.94,XY24,NTT,AUTO
59,PIDILITIND,0.39,3.17,14.73,18.37,21444.0,4470.0,145580.0,1670.26,-27.76,58.0,X-LC,5.61,5.0,0.21,0.98,14.31,X40,ATH,CHEMICALS

In [22]:
# top 5 for average up
df_tmp = df_portfolio_features[(df_portfolio_features['Dev%_200'] > 5)].sort_values(by = 'CurrAlloc%', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
44,INDUSINDBK,0.35,-33.91,101.06,32.89,51570.0,-26178.0,51029.0,1800.00,-340.20,51.0,L-MC,7.94,258.0,-0.51,0.34,25.61,XR,NTT,BANKS
73,SONACOMS,2.15,0.29,38.68,39.09,39243.0,297.0,101456.0,804.02,-20.47,53.0,M-MC,19.15,193.0,0.01,0.68,43.52,AR,ATH,AUTO
72,SIS,2.45,-7.16,30.61,21.26,31554.0,-7948.0,103084.0,528.00,2454.40,70.0,H-SC,14.67,168.0,-0.25,0.70,53.27,OX40N,NTT,MISC
75,SURYODAY,-0.02,-7.41,32.88,23.03,54515.0,-13270.0,165801.0,216.00,79.82,57.0,H-SC,16.73,166.0,-0.24,1.12,39.60,XR,NTT,BANKS
5,ATULAUTO,-1.91,-14.29,69.84,45.57,118004.0,-28169.0,168963.0,844.00,3662.16,56.0,M-SC,8.18,248.0,-0.24,1.14,30.02,XY24,NTT,AUTO

In [23]:
# top 5 RSP
df_tmp = df_portfolio_features.sort_values(by = 'RSP', ascending=False)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
68,SATIN,1.34,23.19,23.25,51.83,79133.0,64073.0,340357.0,274.00,10.38,77.0,H-SC,28.31,159.0,0.81,2.30,65.80,XY24,NTT,FINANCE
3,ALKYLAMINE,3.23,-24.77,157.40,93.63,119547.0,-25012.0,75951.0,4546.37,-19.40,65.0,H-SC,15.14,142.0,-0.21,0.51,43.42,SR,ATH,CHEMICALS
72,SIS,2.45,-7.16,30.61,21.26,31554.0,-7948.0,103084.0,528.00,2454.40,70.0,H-SC,14.67,168.0,-0.25,0.70,53.27,OX40N,NTT,MISC
56,MEDANTA,0.10,6.11,19.80,27.12,37085.0,10783.0,187300.0,1486.00,2.89,67.0,X-SC,9.46,87.0,0.29,1.26,29.06,XY24,NTT,HEALTHCARE
17,CIPLA,-1.15,14.14,18.00,34.69,31467.0,21654.0,174815.0,1663.60,-11.85,65.0,X-LC,10.59,18.0,0.69,1.18,18.23,X40N,ATH,PHARMA

In [24]:
# Top N allocation
df_tmp = df_portfolio_features.sort_values(by = 'CurrAlloc%', ascending=False)
top_n_values = [10, 25, 50]

sum_df = pd.DataFrame({
    'Top_N': top_n_values,
    'Sum_Alloc%': [df_tmp['CurrAlloc%'].head(n).sum() for n in top_n_values]
})

sum_df

   Top_N  Sum_Alloc%
0     10       19.51
1     25       43.10
2     50       73.10

In [25]:
# market-cap-wise allocation
df_tmp = df_portfolio_features[cols]
df_tmp.groupby(df_tmp['Conviction'].str[-2:])['CurrAlloc%'].sum().sort_values(ascending=False)

Conviction
SC    42.42
LC    31.60
MC    26.00
Name: CurrAlloc%, dtype: float64

In [26]:
# criteria-wise allocation
df_portfolio_features.groupby('Criteria')['CurrAlloc%'].sum().sort_values(ascending=False)

Criteria
XY24     27.44
X40      25.75
X40N     16.74
XR        8.87
OX40N     6.96
AR        6.70
XY25      6.70
SR        0.86
Name: CurrAlloc%, dtype: float64

In [27]:
# conviction-wise allocation
df_portfolio_features.groupby('Conviction')['CurrAlloc%'].sum().sort_values(ascending=False)

Conviction
X-LC    29.48
H-SC    22.32
X-MC    21.05
M-SC     9.93
X-SC     9.67
H-MC     2.69
M-MC     1.92
H-LC     1.20
M-LC     0.92
L-SC     0.50
L-MC     0.34
Name: CurrAlloc%, dtype: float64

In [28]:
# sector-wise stats
df_tmp = df_portfolio_features.groupby('Category')[['CurrAlloc%', 'Current', 'Current P/L', 'FTT Amt']].sum().sort_values(by=['Current', 'Current P/L'], ascending=False)
df_tmp['Current P/L%'] = round(df_tmp['Current P/L'] * 100 / df_tmp['Current'], 2)
df_tmp['FTT%'] = round(df_tmp['FTT Amt'] * 100 / df_tmp['Current'], 2)
cols = ['CurrAlloc%', 'Current P/L%', 'FTT%']
df_tmp[cols].sort_values(by=['CurrAlloc%'], ascending=False)

               CurrAlloc%  Current P/L%    FTT%
Category
FMCG                15.48        -15.49   56.19
FINANCE             10.82        -14.98   64.99
IT                  10.36        -46.88  120.83
MISC                 6.90        -31.34   88.39
AUTO                 6.69        -10.52   51.96
BANKS                5.59         -9.60   60.28
PAINTS               5.53        -20.33   41.23
INSURANCE            5.36         -4.25   39.73
PHARMA               5.12          2.25   29.17
ELECTRICAL           3.89        -22.64   66.29
CHEMICALS            2.18        -25.18   99.78
HEALTHCARE           2.03        -18.62   49.58
AC                   1.84        -17.62   49.51
APPARELS             1.83          0.93   32.86
TRAVEL               1.70        -78.58  168.00
FOOTWEAR             1.65        -80.77  153.25
DURABLES             1.63        -59.75   98.62
BREWERIES            1.52         -4.32   25.99
REALTY               1.36        -10.37   28.50
CERAMICS             1.36        -53.27   99.83
CABLES               1.33         25.25   55.41
REFINERIES           1.15        -17.78   47.58
ENGINEERING          1.14        -43.62  109.30
CEMENT               1.10        -64.38  187.35
JEWELLERY            1.04       -106.50  178.24
ENTERTAINMENT        0.70        -85.60  196.30
TEXTILES             0.41        -52.82   96.40
HOTELS               0.31       -144.38  230.58

In [29]:
# money to be made criteria-wise
df_portfolio_features.groupby('Criteria')['FTT Amt'].agg(['sum', 'count']).sort_values(by='sum', ascending=False)

                sum  count
Criteria
XY24      3532987.0     21
X40       1888681.0     19
XR        1365796.0     13
X40N      1248309.0     13
AR        1191877.0      9
OX40N      761293.0     10
XY25       448410.0      5
SR         290817.0      2

In [30]:
# money to be made conviction-wise
df_portfolio_features.groupby('Conviction')['FTT Amt'].agg(['sum', 'count']).sort_values(by='sum', ascending=False)

                  sum  count
Conviction
H-SC        3480404.0     24
X-LC        1932928.0     21
X-MC        1617754.0     15
M-SC        1446074.0     14
X-SC        1370729.0      9
H-MC         300036.0      2
L-SC         215681.0      2
M-LC         156261.0      1
M-MC         100700.0      2
H-LC          56033.0      1
L-MC          51570.0      1

In [31]:
# money to be made criteria and conviction-wise
df_portfolio_features.groupby(['Conviction', 'Criteria'])['FTT Amt'].agg(['sum', 'count']).sort_values(by='sum', ascending=False)

                           sum  count
Conviction Criteria
H-SC       XY24      1087176.0      6
X-LC       X40       1013814.0     10
H-SC       AR         960483.0      5
M-SC       XY24       855071.0      6
H-SC       XR         814277.0      7
X-SC       XY24       785446.0      4
X-MC       X40        658741.0      7
           X40N       503443.0      4
X-LC       X40N       375709.0      6
X-SC       X40N       369157.0      3
X-LC       XY24       345613.0      2
H-SC       OX40N      327651.0      4
M-SC       OX40N      325098.0      5
H-SC       SR         290817.0      2
H-MC       XY24       240972.0      1
X-MC       XY25       236861.0      2
           XY24       218709.0      2
X-SC       X40        216126.0      2
M-SC       XR         188851.0      2
M-LC       XR         156261.0      1
X-LC       XY25       150092.0      2
L-SC       OX40N      108544.0      1
           XR         107137.0      1
M-SC       AR          77054.0      1
M-MC       XY25        61457.0      1
H-MC       AR          59064.0      1
H-LC       AR          56033.0      1
L-MC       XR          51570.0      1
X-LC       XR          47700.0      1
M-MC       AR          39243.0      1

In [32]:
# notebook execution time

end_time = time.time()
execution_time = round(end_time - start_time, 0)
print(f"Notebook execution time: {execution_time} seconds")

Notebook execution time: 57.0 seconds