<a href="https://colab.research.google.com/github/ankit-rathi/Quantvesting_v2/blob/main/myStocks_Portfolio_Analysis.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
'''
!pip install pandas==2.2.2 -qq
!pip install pyxirr -qq
!pip install ta -qq
!pip install yfinance==0.2.59 -qq
'''

'\n!pip install pandas==2.2.2 -qq\n!pip install pyxirr -qq\n!pip install ta -qq\n!pip install yfinance==0.2.59 -qq\n'

In [2]:
# import libraries

import numpy as np
import pandas as pd
import datetime
import warnings
warnings.filterwarnings('ignore')
import yfinance as yfin
import ta
import matplotlib.pyplot as plt
import requests

In [3]:
# notebook start time
import time
import datetime
import pytz

start_time = time.time()

# function to print date timestamp
def print_date_time():
  tz_NY = pytz.timezone('Asia/Kolkata')
  datetime_NY = datetime.datetime.now(tz_NY)
  print("Run date time (IST):", datetime_NY.strftime("%Y-%m-%d %H:%M:%S"))

In [4]:
# function to get booked and reserved amount
def get_amt():
  # fetch the JSON data from the URL
  url = "https://raw.githubusercontent.com/ankit-rathi/Tradevesting_v1/main/data/myPortfolioAmts.json"
  response = requests.get(url)
  pf_amts = response.json()  # parse the JSON data

  # extract values from the JSON
  py_booked_amt_dm = pf_amts["py_booked_amt_dm"]
  py_booked_amt_sv = pf_amts["py_booked_amt_sv"]
  cy_booked_amt_dm = pf_amts["cy_booked_amt_dm"]
  cy_booked_amt_sv = pf_amts["cy_booked_amt_sv"]
  reserve_amt_dm = pf_amts["reserve_amt_dm"]
  reserve_amt_sv = pf_amts["reserve_amt_sv"]

  # perform calculations
  py_booked_amt = py_booked_amt_dm + py_booked_amt_sv
  cy_booked_amt = cy_booked_amt_dm + cy_booked_amt_sv
  reserve_amt = reserve_amt_dm + reserve_amt_sv
  total_booked_amt = py_booked_amt + cy_booked_amt

  return total_booked_amt, reserve_amt, cy_booked_amt, py_booked_amt

gen_output = 0

In [5]:
# function to format the amount
def format_amt(number):
    abs_number = abs(number)

    if abs_number >= 1_00_00_000:  # Crores
        formatted_amt = f"{number / 1_00_00_000:.2f} C"
    elif abs_number >= 1_00_000:  # Lakhs
        formatted_amt = f"{number / 1_00_000:.2f} L"
    elif abs_number >= 1_000:  # Thousands
        formatted_amt = f"{number / 1_000:.2f} K"
    else:
        formatted_amt = f"{number:.2f}"

    return formatted_amt

# function to set start and end date
def get_start_end_date():
  start_date = (datetime.date.today() + datetime.timedelta(days=-365)).strftime('%Y-%m-%d')
  end_date = (datetime.date.today() + datetime.timedelta(days=1)).strftime('%Y-%m-%d')
  return start_date, end_date

# function to fetch my portfolio csv
def get_mypfs_df():
  mypfs_df = pd.read_csv('https://raw.githubusercontent.com/ankit-rathi/Tradevesting_v1/main/data/myPortfolioStocks.csv')
  return mypfs_df

# function to fetch my prospects csv
def get_mypps_df():
  mypps_df = pd.read_csv('https://raw.githubusercontent.com/ankit-rathi/Tradevesting_v1/main/data/myProspectsScrips.csv')
  return mypps_df

# function to fetch screener data
def get_myscreen_df():
  myscreen_df = pd.read_csv('https://raw.githubusercontent.com/ankit-rathi/Tradevesting_v1/main/data/myScreenerDB.csv')
  return myscreen_df

# function to fetch momentum data
def get_myinvmt_df():
  myinvmt_df = pd.read_csv('https://raw.githubusercontent.com/ankit-rathi/Tradevesting_v1/main/data/myInvestments.csv')
  return myinvmt_df

# function to get the stock ids
def get_stock_ids(df_pf):
  stock_n100 = df_pf['Symbol'].unique()

  exclude = ['CADILAHC','MMTC', 'MASFIN']

  stock_ids = df_pf[~df_pf['Symbol'].isin(exclude) ]['Symbol'].unique()

  #mypf = mypf[mypf.Forecast.notnull()]
  #stock_ids = mypf['Symbol'].unique()

  #stock_ids.sort()
  return stock_ids

# get features from screener data
def get_screener_features():
  myscreen_df = get_myscreen_df()
  cols = ['Symbol', 'EPS', 'MedPE', 'ROCE%', 'ROE%', 'CapType']
  return myscreen_df[cols]

# get relative strength
def get_relative_strength(stock_list):

    # Dictionary to store stock tickers and their corresponding percentage price change
    stock_changes = {}

    # Loop through each stock and fetch its price data
    for stock in stock_list:
        try:
            # Download the stock data for the given date range
            stock_data = yfin.Ticker(stock + '.NS').history(period='1mo', interval='1d')[map(str.title, ['open', 'close', 'low', 'high', 'volume'])]

            # Calculate the percentage change for the stock
            if len(stock_data) > 0:
                start_price = stock_data['Close'].iloc[0]
                end_price = stock_data['Close'].iloc[-1]
                percent_change = round(((end_price - start_price) / start_price) * 100, 2)
                stock_changes[stock] = percent_change
            else:
                stock_changes[stock] = np.nan  # If no data is available, set to NaN

        except Exception as e:
            print(f"Error fetching data for {stock}: {e}")
            stock_changes[stock] = np.nan

    # Create a DataFrame with stock tickers and their percentage changes
    df = pd.DataFrame(list(stock_changes.items()), columns=['Symbol', 'Percent_Change'])

    # Drop any stocks with missing data (NaN values)
    df = df.dropna()

    # Calculate the percentile rank based on percentage change
    df['RSP'] = round(df['Percent_Change'].rank(pct=True) * 100, 2)
    cols = ['Symbol', 'RSP']
    df = df[cols]
    # Sort by percentile rank (optional)
    df = df.sort_values(by='RSP', ascending=False).reset_index(drop=True)

    return df

In [6]:
# function to get stock technicals
def stock_prec_dev(stock_symbol):
    #stock_symbol = 'ULTRACEMCO.NS'
    short_window = 20
    mid_window = 50
    long_window = 200
    moving_avg = 'SMA'

    start = datetime.datetime(*map(int, start_date.split('-')))
    end = datetime.datetime(*map(int, end_date.split('-')))

    stock_df = yfin.Ticker(stock_symbol + '.NS').history(period='max', interval='1d')[map(str.title, ['open', 'close', 'low', 'high', 'volume'])]

    stock_df['Max'] = round(max(stock_df['Close']),2)
    stock_df = stock_df[(stock_df.index <= end_date) & (stock_df.index >= start_date)]
    stock_df['200_SMA'] = round(stock_df['Close'].rolling(window = 200, min_periods = 1).mean(),0)
    stock_df['Dev%_200'] = round((stock_df['Close'] - stock_df['200_SMA'])*100/stock_df['200_SMA'],2)
    stock_df.dropna(axis = 0, inplace = True) # remove any null rows

    stock_df['20_SMA'] = stock_df['Close'].rolling(window=20).mean()
    stock_df['50_SMA'] = stock_df['Close'].rolling(window=50).mean()
    stock_df['Symbol'] = stock_symbol

    stock_df['Close'] = round(stock_df['Close'],2)
    stock_df['Min'] = round(min(stock_df['Close']),2)
    stock_df['RSI_14'] = ta.momentum.RSIIndicator(close=stock_df['Close'], window=14).rsi()
    stock_df['RSI_14'] = round(stock_df['RSI_14'],0)
    stock_df['Prev_Close'] = stock_df['Close'].shift(1)
    stock_df.drop(['Open', 'Low', 'High', 'Volume'], axis=1, inplace=True)
    stock_df = stock_df.tail(1)

    max_SMA = max(stock_df['20_SMA'].item(), stock_df['50_SMA'].item(), stock_df['200_SMA'].item())
    min_SMA = min(stock_df['20_SMA'].item(), stock_df['50_SMA'].item(), stock_df['200_SMA'].item())
    ABS_Spread = max_SMA - min_SMA
    stock_df['Spread%'] = round((ABS_Spread / stock_df['200_SMA'].item()) * 100,2)

    return stock_df

# function to compute stock attributes
def get_common_features(stock_ids, df_mypf):

  df_prec_dev = pd.DataFrame()
  df_tmp = get_screener_features()
  df_rs = get_relative_strength(stock_ids)

  for stock_id in stock_ids:
      tmp = stock_prec_dev(stock_id)
      tmp = tmp.reset_index()
      df_prec_dev = pd.concat([df_prec_dev, tmp], ignore_index = True)
  df_prec_dev = pd.merge(df_prec_dev, df_mypf, on= 'Symbol')
  df_prec_dev = pd.merge(df_prec_dev, df_tmp, on= 'Symbol', how='left')
  df_prec_dev = pd.merge(df_prec_dev, df_rs, on= 'Symbol', how='left')
  #print(df_prec_dev.columns)
  df_prec_dev['Curr_PE'] = round(df_prec_dev['Close']/df_prec_dev['EPS'],1)
  df_prec_dev['Dev%_PE'] = round((df_prec_dev['Curr_PE'] - df_prec_dev['MedPE'])*100/df_prec_dev['MedPE'],2)
  df_prec_dev['Conviction'] = df_prec_dev['Conviction'] + '-' + df_prec_dev['CapType']
  return df_prec_dev

# function to arrange stock features
def arrange_features(df_stocks, common_cols, diff_cols):
  df_stocks_common = df_stocks[common_cols].drop_duplicates()
  df_stocks_diff = df_stocks[diff_cols]
  df_stocks_diff['Investment'] = df_stocks_diff['AvgCost'] * df_stocks_diff['Shares']
  df_stocks_diff = df_stocks_diff.groupby(['Symbol'])[['Shares', 'Investment']].aggregate(['sum']).reset_index()
  df_stocks_diff.columns = ['Symbol', 'Shares', 'Investment']
  df_stocks_diff['AvgCost'] = round(df_stocks_diff['Investment']/df_stocks_diff['Shares'],2)
  df_stocks = pd.merge(df_stocks_diff, df_stocks_common, on='Symbol')
  return df_stocks

# plot fact distribution across dimension
def plot_pie_chart(df, dimension, fact):
  # grouping the data by category and calculating the sum of fact for each type
  grouped_data = df.groupby(dimension)[fact].sum()

  # sorting the grouped data in descending order
  grouped_data = grouped_data.sort_values(ascending=False)

  # creating a pie chart
  grouped_data.plot.pie(autopct='%1.1f%%', startangle=90, figsize=(6, 6))

  # adding a title and displaying the plot
  plt.title(f'{dimension} {fact} Distribution')
  plt.ylabel('')  # To hide the y-label
  plt.show()

In [7]:
# function to get portfolio features

def get_portfolio_features(df_common_features):

  print_date_time()
  print('-------------------')

  #df_common_features["Target"] = df_common_features["Target"].fillna(df_common_features["Max"])
  df_common_features['NTT'] = np.where(df_common_features['Strategy']== 'NTT', df_common_features["Target"], df_common_features['Max'])
  df_common_features['LTT'] = np.where(df_common_features['Strategy']== 'BTT', df_common_features["Target"], df_common_features['Max'])
  df_common_features['BOL'] = df_common_features['Min']

  tmp_df = df_common_features[df_common_features['Symbol'].isin(mypf_df[mypf_df['InPortfolio'] != 'NA'].Symbol.values)]
  print('qualified stocks: '+str(len(tmp_df['Symbol'].unique())))
  tmp_df1 = tmp_df[tmp_df['LatestQtr'] == 1]
  print('with latest results: '+str(len(tmp_df1['Symbol'].unique())))
  tmp_df1 = tmp_df1[tmp_df1['StarStock'] == 1]
  print('still star stocks: '+str(len(tmp_df1['Symbol'].unique())))
  tmp_df['Investment'] = tmp_df['AvgCost'] * tmp_df['Shares']
  tmp_df['Current'] = round(tmp_df['Close'] * tmp_df['Shares'],0)
  tmp_df['Previous'] = tmp_df['Prev_Close'] * tmp_df['Shares']
  tmp_df['EstimatedST'] = tmp_df['NTT'] * tmp_df['Shares']
  tmp_df['EstimatedLT'] = tmp_df['LTT'] * tmp_df['Shares']
  tmp_df['Current P/L'] = round((tmp_df['Current'] - tmp_df['Investment']),0)
  tmp_df['Today P/L%'] = round((tmp_df['Current'] - tmp_df['Previous'])*100/tmp_df['Previous'],2)
  tmp_df['Current P/L%'] = round((tmp_df['Current'] - tmp_df['Investment'])*100/tmp_df['Investment'],2)
  tmp_df['EstimatedST P/L%'] = round((tmp_df['EstimatedST'] - tmp_df['Investment'])*100/tmp_df['Investment'],2)
  tmp_df['EstimatedLT P/L%'] = round((tmp_df['EstimatedLT'] - tmp_df['Investment'])*100/tmp_df['Investment'],2)
  tmp_df['NTT%'] = round((tmp_df['NTT'] - tmp_df['Close'])*100/tmp_df['Close'],2)
  tmp_df['LTT%'] = round((tmp_df['LTT'] - tmp_df['Close'])*100/tmp_df['Close'],2)
  tmp_df['Gained%'] = round((tmp_df['Close'] - tmp_df['BOL'])*100/tmp_df['BOL'],2)
  investment = round(sum(tmp_df['AvgCost']*tmp_df['Shares']),0)
  current = round(sum(tmp_df['Close']*tmp_df['Shares']),0)
  tmp_df['InitAlloc%'] = round(tmp_df['Investment']*100/investment,2)
  tmp_df['CurrAlloc%'] = round(tmp_df['Current']*100/current,2)
  tmp_df['FTT'] = tmp_df['LTT']
  tmp_df.loc[tmp_df['Strategy'] == 'NTT', 'FTT'] = tmp_df['NTT']
  tmp_df['FTT%'] = tmp_df['LTT%']
  tmp_df.loc[tmp_df['Strategy'] == 'NTT', 'FTT%'] = tmp_df['NTT%']
  tmp_df['FTT Amt'] = round(tmp_df['FTT%'] * tmp_df['Current']/100,0)
  tmp_df['OTT%'] = round((tmp_df['FTT'] - tmp_df['AvgCost'])*100/tmp_df['AvgCost'],2)
  tmp_df['RRR Ind'] = round(tmp_df['Current P/L']/tmp_df['FTT Amt'],2)
  tmp_df['Risk Ind'] = round(tmp_df['Current P/L%']*tmp_df['CurrAlloc%'],0)

  return tmp_df

# function to print portfolio features
def print_portfolio_stats(df_portfolio_features, myinvmt_df):
  from pyxirr import xirr

  total_booked_amt, reserve_amt, cy_booked_amt, py_booked_amt = get_amt()

  dates = myinvmt_df['Date'].values
  dates = np.append(dates, datetime.date.today().strftime('%d-%b-%y'))
  investment = myinvmt_df['Investment'].values
  dates= pd.to_datetime(dates)

  current = round(sum(df_portfolio_features['Close']*df_portfolio_features['Shares']),0) + reserve_amt
  investment_xirr = np.append(investment, current)
  cagr = round(xirr(pd.DataFrame({"dates": dates, "amounts": investment_xirr}))*100,2)

  investment = -sum(investment)
  invested = round(sum(df_portfolio_features['AvgCost']*df_portfolio_features['Shares']),0) + reserve_amt
  previous = round(sum(df_portfolio_features['Prev_Close']*df_portfolio_features['Shares']),0) + reserve_amt
  cy_invested = investment + py_booked_amt

  today_pnl_amount = current-previous
  today_pnl_percentage = round((current-previous)*100/previous,2)

  curr_pnl_amount = current-invested
  curr_pnl_percentage = round((curr_pnl_amount)*100/(cy_invested),2)

  cy_pnl_amount = cy_booked_amt + curr_pnl_amount
  cy_pnl_percentage = round((cy_pnl_amount)*100/cy_invested,2)

  overall_pnl_amount = total_booked_amt + curr_pnl_amount
  overall_pnl_percentage = round((overall_pnl_amount)*100/investment,2)

  estimate_st = round(sum(df_portfolio_features['FTT']*df_portfolio_features['Shares']),0)  + reserve_amt
  est_st_pnl_amount = estimate_st-current
  est_st_pnl_percentage = round((est_st_pnl_amount)*100/current,2)

  estimate_lt = round(sum(df_portfolio_features['LTT']*df_portfolio_features['Shares']),0)  + reserve_amt
  est_lt_pnl_amount = estimate_lt-current
  est_lt_pnl_percentage = round((est_lt_pnl_amount)*100/current,2)

  total_profit = round(sum(df_portfolio_features[df_portfolio_features['Current P/L%'] > 0]['Current']) - sum(df_portfolio_features[df_portfolio_features['Current P/L%'] > 0]['Investment']),0)
  total_loss = round(sum(df_portfolio_features[df_portfolio_features['Current P/L%'] < 0]['Current']) - sum(df_portfolio_features[df_portfolio_features['Current P/L%'] < 0]['Investment']),0)

  cy_booked_percentage = round((cy_booked_amt)*100/current,2)
  py_booked_percentage = round((py_booked_amt)*100/investment,2)
  total_booked_percentage = round((total_booked_amt)*100/investment,2)

  print('-------------------')
  print('Initial Investment: ', format_amt(investment))
  print('CY Investment: ', format_amt(cy_invested))
  print('Reserve: ', format_amt(reserve_amt))
  print('Current: ',  format_amt(current))
  print('-------------------')
  print('Today PnL: '+ '{} ({}%)'.format(format_amt(today_pnl_amount), today_pnl_percentage))
  print('Current PnL: '+ '{} ({}%)'.format(format_amt(curr_pnl_amount), curr_pnl_percentage))
  print('CY Booked + Current PnL: '+ '{} ({}%)'.format(format_amt(cy_pnl_amount), cy_pnl_percentage))
  print('-------------------')
  print('Total profit: ', format_amt(total_profit))
  print('Total loss: ', format_amt(total_loss))
  print('-------------------')
  print('Total Booked + Current PnL: '+ '{} ({}%)'.format(format_amt(overall_pnl_amount), overall_pnl_percentage))
  print('Total Booked PnL: '+ '{} ({}%)'.format(format_amt(total_booked_amt), total_booked_percentage))
  print('Curr Year Booked PnL: '+ '{} ({}%)'.format(format_amt(cy_booked_amt), cy_booked_percentage))
  print('Prev Year Booked PnL: '+ '{} ({}%)'.format(format_amt(py_booked_amt), py_booked_percentage))
  print('===================')
  print('Est FTT: ',  format_amt(estimate_st))
  print('Est FTT PnL: '+ '{} ({}%)'.format(format_amt(est_st_pnl_amount), est_st_pnl_percentage))

  print('===================')
  print('Deployed: ', format_amt(investment))

  print('Current: ', format_amt(current))

  print('CAGR/XIRR %: '+'{}%'.format(cagr))

In [8]:
# get start and end date
start_date, end_date = get_start_end_date()

# get portfolio and prospects data
mypfs_df = get_mypfs_df()
mypps_df = get_mypps_df()
myinvmt_df = get_myinvmt_df()

# merge above datasets
mypf_df = pd.merge(mypfs_df, mypps_df, on="Symbol")

# seggregate dm and sv portfolio
dm_pf = mypf_df[mypf_df['InPortfolio'] == 'DM']
sv_pf = mypf_df[mypf_df['InPortfolio'] == 'SV']

# build portfolio stock dataframe
dm_stocks = get_stock_ids(dm_pf)
sv_stocks = get_stock_ids(sv_pf)
df_stocks = pd.concat([dm_pf,sv_pf], ignore_index = True)

# arrange common and diff stock features
common_cols = ['Symbol', 'Target', 'Criteria', 'Strategy', 'CumlRnk', 'LatestQtr', 'StarStock', 'Conviction', 'Category', 'InFolio', 'XIRR', 'MBQ']
diff_cols = ['Symbol', 'AvgCost', 'Shares']
df_stocks = arrange_features(df_stocks, common_cols, diff_cols)

# get common features
stock_ids = df_stocks['Symbol'].values
df_common_features = get_common_features(stock_ids, df_stocks)

df_common_features.reset_index(drop=True, inplace=True)
df_common_features.drop(['Date'], axis=1, inplace=True)
# get and print portfolio features
df_portfolio_features = get_portfolio_features(df_common_features)

print_portfolio_stats(df_portfolio_features, myinvmt_df)

df = df_portfolio_features
#plot_pie_chart(df, 'CapType', 'Current')
list_ox40n = list(df[df['MBQ'].str.contains('OX40N', na=False)]['Symbol'].values)

Failed to get ticker '5PAISA.NS' reason: Failed to perform, curl: (60) SSL: no alternative certificate subject name matches target hostname 'fc.yahoo.com'. See https://curl.se/libcurl/c/libcurl-errors.html first for more details.

Failed to get ticker 'ABBOTINDIA.NS' reason: Failed to perform, curl: (60) SSL: no alternative certificate subject name matches target hostname 'fc.yahoo.com'. See https://curl.se/libcurl/c/libcurl-errors.html first for more details.

Failed to get ticker 'ACC.NS' reason: Failed to perform, curl: (60) SSL: no alternative certificate subject name matches target hostname 'fc.yahoo.com'. See https://curl.se/libcurl/c/libcurl-errors.html first for more details.

$ACC.NS: possibly delisted; no price data found  (period=1mo)

Failed to get ticker 'ALKYLAMINE.NS' reason: Failed to perform, curl: (60) SSL: no alternative certificate subject name matches target hostname 'fc.yahoo.com'. See https://curl.se/libcurl/c/libcurl-errors.html first for more details.

$ALKYLAMINE.NS: possibly delisted; no price data found  (period=1mo)

Error fetching data for 5PAISA: Failed to perform, curl: (60) SSL: no alternative certificate subject name matches target hostname 'fc.yahoo.com'. See https://curl.se/libcurl/c/libcurl-errors.html first for more details.
Error fetching data for ABBOTINDIA: Failed to perform, curl: (60) SSL: no alternative certificate subject name matches target hostname 'fc.yahoo.com'. See https://curl.se/libcurl/c/libcurl-errors.html first for more details.

Run date time (IST): 2026-07-08 13:24:20
-------------------
qualified stocks: 92
with latest results: 31
still star stocks: 20

-------------------
Initial Investment:  1.40 C
CY Investment:  1.82 C
Reserve:  1.49 K
Current:  1.53 C
-------------------
Today PnL: -1.06 L (-0.69%)
Current PnL: -30.50 L (-16.72%)
CY Booked + Current PnL: -28.42 L (-15.58%)
-------------------
Total profit:  4.54 L
Total loss:  -35.04 L
-------------------
Total Booked + Current PnL: 14.45 L (10.36%)
Total Booked PnL: 44.95 L (32.22%)
Curr Year Booked PnL: 2.08 L (1.36%)
Prev Year Booked PnL: 42.87 L (30.73%)
===================
Est FTT:  2.55 C
Est FTT PnL: 1.02 C (67.01%)
===================
Deployed:  1.40 C
Current:  1.53 C
CAGR/XIRR %: 4.13%

In [9]:
# top 5 near their targets
cols = ['Symbol', 'Today P/L%', 'Current P/L%', 'FTT%', 'OTT%', 'FTT Amt', 'Current P/L', 'Current', 'FTT', 'Dev%_PE', 'RSI_14','Conviction', 'Spread%',  'CumlRnk', 'RRR Ind', 'CurrAlloc%', 'Gained%', 'Criteria', 'Strategy', 'Category']
df_tmp = df_portfolio_features[~df_portfolio_features['Symbol'].isin(['ENRIN','BLUSPRING','DIGITIDE'])]
df_tmp = df_tmp.sort_values(by = 'FTT Amt', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
59,PIDILITIND,-1.18,13.24,4.53,18.37,7238.0,18680.0,159790.0,1670.26,-20.71,63.0,X-LC,7.75,5.0,2.58,1.05,25.46,X40,ATH,CHEMICALS
49,JSWINFRA,-1.28,8.89,6.93,16.43,16735.0,19713.0,241487.0,342.00,-6.62,59.0,X-MC,11.73,61.0,1.18,1.58,36.92,X40N,NTT,REALTY
83,TTKPRESTIG,0.41,-18.23,22.41,0.09,18467.0,-18371.0,82406.0,770.00,91.25,70.0,M-SC,5.28,250.0,-0.99,0.54,46.73,OX40N,NTT,DURABLES
68,SATIN,-1.06,44.35,5.18,51.83,20659.0,122542.0,398826.0,274.00,28.78,67.0,H-SC,41.50,159.0,5.93,2.61,94.29,XY24,NTT,FINANCE
73,SONACOMS,1.81,17.57,17.96,38.69,21360.0,17771.0,118930.0,801.69,-6.83,80.0,M-MC,19.59,193.0,0.83,0.78,68.73,AR,ATH,AUTO

In [10]:
# top 5 today
df_tmp = df_portfolio_features.sort_values(by = 'Today P/L%', ascending=False)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
3,ALKYLAMINE,7.48,-17.80,134.24,92.54,111406.0,-17973.0,82990.0,4520.85,-11.91,64.0,H-SC,9.46,142.0,-0.16,0.54,57.59,SR,ATH,CHEMICALS
85,VAIBHAVGBL,6.62,-22.86,108.40,60.77,152844.0,-41775.0,141000.0,521.00,62.53,65.0,H-SC,3.65,160.0,-0.27,0.92,43.46,XR,NTT,JEWELLERY
29,GREENPANEL,3.51,-47.93,174.89,43.14,166724.0,-87747.0,95331.0,537.00,113.82,53.0,M-SC,16.38,225.0,-0.53,0.62,14.51,XY24,NTT,MISC
60,QUESS,3.36,24.44,39.75,73.90,52823.0,26096.0,132889.0,424.00,-33.33,88.0,X-SC,22.13,80.0,0.49,0.87,81.16,XY24,NTT,MISC
69,SFL,2.93,-23.83,66.25,26.63,132322.0,-62487.0,199731.0,1287.00,51.32,71.0,M-SC,20.47,242.0,-0.47,1.31,66.47,XY24,NTT,MISC

In [11]:
# bottom 5 today
df_tmp = df_portfolio_features.sort_values(by = 'Today P/L%', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
41,IEX,-3.38,-19.70,85.09,48.63,136621.0,-39394.0,160560.0,219.0,-46.67,33.0,H-SC,4.41,137.0,-0.29,1.05,4.75,XR,NTT,MISC
5,ATULAUTO,-3.33,-16.09,73.48,45.57,121543.0,-31722.0,165410.0,844.0,3581.08,55.0,M-SC,3.71,248.0,-0.26,1.08,27.29,XY24,NTT,AUTO
80,TITAGARH,-3.16,-20.84,84.10,45.74,161231.0,-50463.0,191714.0,1548.0,5.39,43.0,H-SC,9.76,175.0,-0.31,1.26,46.27,XY24,NTT,ENGINEERING
11,BERGEPAINT,-2.94,-6.66,34.25,25.32,82401.0,-17161.0,240588.0,680.0,-11.78,45.0,X-MC,3.56,68.0,-0.21,1.58,25.22,XY24,NTT,PAINTS
48,JIOFIN,-2.87,-21.65,63.92,28.43,149400.0,-64598.0,233729.0,387.0,-22.88,45.0,X-LC,11.09,34.0,-0.43,1.53,5.35,XY24,BTT,FINANCE

In [12]:
# top 5 to exit based on CumlRnk
df_tmp = df_portfolio_features[~df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])]
df_tmp = df_tmp[(df_tmp['Current P/L%'] > -1) & (df_tmp['Current P/L%'] < 1)].sort_values(by = 'CumlRnk', ascending=False)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
72,SIS,2.49,0.29,20.91,21.26,23285.0,326.0,111358.0,528.0,2659.59,60.0,H-SC,25.08,168.0,0.01,0.73,65.57,OX40N,NTT,MISC

In [13]:
# OX40N stocks to exit
df_tmp = df_portfolio_features[(df_portfolio_features['Symbol'].isin(list_ox40n))].sort_values(by = 'Current P/L%', ascending=False)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
25,FINCABLES,-2.39,34.38,54.72,107.91,108568.0,50763.0,198407.0,1641.55,20.75,44.0,M-SC,26.85,220.0,0.47,1.30,49.27,OX40N,ATH,CABLES
72,SIS,2.49,0.29,20.91,21.26,23285.0,326.0,111358.0,528.00,2659.59,60.0,H-SC,25.08,168.0,0.01,0.73,65.57,OX40N,NTT,MISC
16,CERA,-1.89,-16.67,48.67,23.89,71340.0,-29324.0,146579.0,9475.00,-19.57,61.0,H-SC,14.80,153.0,-0.41,0.96,42.49,OX40N,NTT,CERAMICS
83,TTKPRESTIG,0.41,-18.23,22.41,0.09,18467.0,-18371.0,82406.0,770.00,91.25,70.0,M-SC,5.28,250.0,-0.99,0.54,46.73,OX40N,NTT,DURABLES
43,INDIGOPNTS,-0.50,-23.75,31.17,0.02,41488.0,-41457.0,133102.0,1408.00,103.12,66.0,M-SC,4.47,222.0,-1.00,0.87,51.01,OX40N,NTT,PAINTS

In [14]:
# top 5 to book for rotation
df_tmp = df_portfolio_features[(df_portfolio_features['Current P/L%'] > 20) ].sort_values(by = 'CumlRnk', ascending=False)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
25,FINCABLES,-2.39,34.38,54.72,107.91,108568.0,50763.0,198407.0,1641.55,20.75,44.0,M-SC,26.85,220.0,0.47,1.30,49.27,OX40N,ATH,CABLES
68,SATIN,-1.06,44.35,5.18,51.83,20659.0,122542.0,398826.0,274.00,28.78,67.0,H-SC,41.50,159.0,5.93,2.61,94.29,XY24,NTT,FINANCE
91,ZYDUSLIFE,1.18,23.02,10.25,35.63,26426.0,48245.0,257819.0,1286.17,7.21,72.0,H-MC,15.17,120.0,1.83,1.69,35.56,AR,ATH,PHARMA
60,QUESS,3.36,24.44,39.75,73.90,52823.0,26096.0,132889.0,424.00,-33.33,88.0,X-SC,22.13,80.0,0.49,0.87,81.16,XY24,NTT,MISC

In [15]:
# top 5 to monitor for exit
df_tmp = df_portfolio_features[~df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])]
df_tmp = df_tmp[(df_tmp['Current P/L%'] > 0) ].sort_values(by = 'Dev%_PE', ascending=False)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
72,SIS,2.49,0.29,20.91,21.26,23285.0,326.0,111358.0,528.00,2659.59,60.0,H-SC,25.08,168.0,0.01,0.73,65.57,OX40N,NTT,MISC
75,SURYODAY,-1.14,2.28,20.29,23.03,37163.0,4090.0,183161.0,216.00,99.56,61.0,H-SC,20.28,166.0,0.11,1.20,54.22,XR,NTT,BANKS
74,STARHEALTH,1.94,14.68,28.41,47.26,91594.0,41279.0,322402.0,761.00,81.04,71.0,H-SC,15.93,173.0,0.45,2.11,40.37,XY24,NTT,INSURANCE
68,SATIN,-1.06,44.35,5.18,51.83,20659.0,122542.0,398826.0,274.00,28.78,67.0,H-SC,41.50,159.0,5.93,2.61,94.29,XY24,NTT,FINANCE
25,FINCABLES,-2.39,34.38,54.72,107.91,108568.0,50763.0,198407.0,1641.55,20.75,44.0,M-SC,26.85,220.0,0.47,1.30,49.27,OX40N,ATH,CABLES

In [16]:
# top 5 to book for rotation from weak conviction
df_tmp = df_portfolio_features[~df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])]
df_tmp = df_tmp[~df_tmp['Criteria'].isin(['XY25','XY24','X40', 'X40N'])].sort_values(by = 'RRR Ind', ascending=False)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
91,ZYDUSLIFE,1.18,23.02,10.25,35.63,26426.0,48245.0,257819.0,1286.17,7.21,72.0,H-MC,15.17,120.0,1.83,1.69,35.56,AR,ATH,PHARMA
73,SONACOMS,1.81,17.57,17.96,38.69,21360.0,17771.0,118930.0,801.69,-6.83,80.0,M-MC,19.59,193.0,0.83,0.78,68.73,AR,ATH,AUTO
25,FINCABLES,-2.39,34.38,54.72,107.91,108568.0,50763.0,198407.0,1641.55,20.75,44.0,M-SC,26.85,220.0,0.47,1.30,49.27,OX40N,ATH,CABLES
75,SURYODAY,-1.14,2.28,20.29,23.03,37163.0,4090.0,183161.0,216.00,99.56,61.0,H-SC,20.28,166.0,0.11,1.20,54.22,XR,NTT,BANKS
72,SIS,2.49,0.29,20.91,21.26,23285.0,326.0,111358.0,528.00,2659.59,60.0,H-SC,25.08,168.0,0.01,0.73,65.57,OX40N,NTT,MISC

In [17]:
# top 5 to accumulate based on lowest RSI_14
df_tmp = df_portfolio_features[df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])].sort_values(by = 'RSI_14', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
87,VBL,-1.02,-3.18,39.82,35.37,121767.0,-10049.0,305793.0,670.16,-14.49,32.0,X-LC,9.21,13.0,-0.08,2.00,25.68,X40N,ATH,FMCG
51,KOTAKBANK,-1.66,0.29,20.75,21.11,28818.0,408.0,138880.0,453.24,-14.17,36.0,X-LC,4.30,12.0,0.01,0.91,6.21,X40,ATH,BANKS
81,TMPV,-0.98,-22.84,77.02,36.58,211458.0,-81291.0,274550.0,600.00,-83.62,36.0,X-LC,7.28,4.0,-0.38,1.80,15.38,XY24,NTT,AUTO
23,DMART,-0.86,-2.99,33.59,29.60,81338.0,-7452.0,242148.0,5391.45,-18.18,39.0,X-LC,3.27,14.0,-0.09,1.59,10.68,X40N,ATH,FMCG
71,SIEMENS,-2.16,-6.11,33.69,25.51,58863.0,-11375.0,174720.0,4671.50,46.70,40.0,H-LC,11.06,51.0,-0.19,1.14,22.67,AR,ATH,ELECTRICAL

In [18]:
# top 5 to accumulate based on Spread and CumlRnk
df_tmp = df_portfolio_features[df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])]
df_tmp = df_tmp[(df_tmp['CumlRnk'] < 100)].sort_values(by = 'Spread%', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
17,CIPLA,-1.42,17.51,13.56,33.43,24404.0,26813.0,179974.0,1648.14,-9.03,62.0,X-LC,2.24,18.0,1.10,1.18,22.86,X40N,ATH,PHARMA
19,COLPAL,-1.33,-22.09,79.51,39.86,163147.0,-58175.0,205190.0,3683.41,-5.63,53.0,X-MC,3.01,62.0,-0.36,1.34,16.07,XY25,ATH,FMCG
84,UNITDSPR,-0.83,4.05,16.06,20.77,39128.0,9494.0,243638.0,1644.00,-7.70,68.0,X-MC,3.06,64.0,0.24,1.60,17.12,X40N,NTT,BREWERIES
23,DMART,-0.86,-2.99,33.59,29.60,81338.0,-7452.0,242148.0,5391.45,-18.18,39.0,X-LC,3.27,14.0,-0.09,1.59,10.68,X40N,ATH,FMCG
11,BERGEPAINT,-2.94,-6.66,34.25,25.32,82401.0,-17161.0,240588.0,680.00,-11.78,45.0,X-MC,3.56,68.0,-0.21,1.58,25.22,XY24,NTT,PAINTS

In [19]:
# top 5 to accumulate based on lowest Gained%
df_tmp = df_portfolio_features[df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])].sort_values(by = 'Gained%', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
58,PGHH,-0.70,-33.32,97.96,32.01,139479.0,-71136.0,142384.0,17616.87,-54.91,41.0,X-MC,20.92,57.0,-0.51,0.93,0.98,X40,ATH,FMCG
65,RELIANCE,-1.30,-17.10,51.15,25.30,85211.0,-34372.0,166591.0,1952.00,-19.26,43.0,X-LC,7.30,21.0,-0.40,1.09,2.59,XY25,BTT,REFINERIES
47,ITC,-1.40,-25.01,58.76,19.06,149891.0,-85075.0,255091.0,452.00,-58.75,41.0,X-LC,12.65,1.0,-0.57,1.67,2.78,X40,NTT,FMCG
35,HDFCLIFE,-1.13,-7.43,43.36,32.71,60127.0,-11130.0,138670.0,811.41,-27.77,41.0,X-LC,15.42,31.0,-0.19,0.91,4.18,X40,ATH,INSURANCE
88,VOLTAS,-0.71,-0.23,45.52,45.20,87084.0,-432.0,191310.0,1856.00,14.23,43.0,X-MC,4.97,79.0,-0.00,1.25,4.85,XY25,NTT,AC

In [20]:
# top 5 to accumulate based on lowest CurrAlloc%
df_tmp = df_portfolio_features[df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])].sort_values(by = 'CurrAlloc%', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
10,BATAINDIA,-0.17,-55.63,204.70,35.20,116876.0,-71574.0,57096.0,2096.00,-25.20,47.0,X-SC,19.74,91.0,-0.61,0.37,13.23,X40,NTT,FOOTWEAR
64,RELAXO,1.61,-48.36,194.92,52.31,146122.0,-70195.0,74965.0,1176.00,-45.02,63.0,X-SC,11.62,92.0,-0.48,0.49,67.61,X40N,NTT,FOOTWEAR
60,QUESS,3.36,24.44,39.75,73.90,52823.0,26096.0,132889.0,424.00,-33.33,88.0,X-SC,22.13,80.0,0.49,0.87,81.16,XY24,NTT,MISC
35,HDFCLIFE,-1.13,-7.43,43.36,32.71,60127.0,-11130.0,138670.0,811.41,-27.77,41.0,X-LC,15.42,31.0,-0.19,0.91,4.18,X40,ATH,INSURANCE
51,KOTAKBANK,-1.66,0.29,20.75,21.11,28818.0,408.0,138880.0,453.24,-14.17,36.0,X-LC,4.30,12.0,0.01,0.91,6.21,X40,ATH,BANKS

In [21]:
# top 5 to accumulate based on CumlRnk
df_tmp = df_portfolio_features.sort_values(by = 'CumlRnk', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
47,ITC,-1.40,-25.01,58.76,19.06,149891.0,-85075.0,255091.0,452.00,-58.75,41.0,X-LC,12.65,1.0,-0.57,1.67,2.78,X40,NTT,FMCG
79,TCS,-0.75,-38.93,104.48,24.88,295609.0,-180339.0,282934.0,4253.91,-48.21,44.0,X-LC,21.61,2.0,-0.61,1.85,4.93,X40,ATH,IT
45,INFY,0.27,-26.84,83.49,34.24,191118.0,-83977.0,228911.0,1972.00,-42.31,49.0,X-LC,21.05,3.0,-0.44,1.50,9.07,X40,NTT,IT
81,TMPV,-0.98,-22.84,77.02,36.58,211458.0,-81291.0,274550.0,600.00,-83.62,36.0,X-LC,7.28,4.0,-0.38,1.80,15.38,XY24,NTT,AUTO
59,PIDILITIND,-1.18,13.24,4.53,18.37,7238.0,18680.0,159790.0,1670.26,-20.71,63.0,X-LC,7.75,5.0,2.58,1.05,25.46,X40,ATH,CHEMICALS

In [22]:
# top 5 for average up
df_tmp = df_portfolio_features[(df_portfolio_features['Dev%_200'] > 5)].sort_values(by = 'CurrAlloc%', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
44,INDUSINDBK,0.60,-24.08,75.03,32.89,43982.0,-18588.0,58619.0,1800.00,-375.91,74.0,L-MC,8.94,258.0,-0.42,0.38,44.52,XR,NTT,BANKS
64,RELAXO,1.61,-48.36,194.92,52.31,146122.0,-70195.0,74965.0,1176.00,-45.02,63.0,X-SC,11.62,92.0,-0.48,0.49,67.61,X40N,NTT,FOOTWEAR
3,ALKYLAMINE,7.48,-17.80,134.24,92.54,111406.0,-17973.0,82990.0,4520.85,-11.91,64.0,H-SC,9.46,142.0,-0.16,0.54,57.59,SR,ATH,CHEMICALS
83,TTKPRESTIG,0.41,-18.23,22.41,0.09,18467.0,-18371.0,82406.0,770.00,91.25,70.0,M-SC,5.28,250.0,-0.99,0.54,46.73,OX40N,NTT,DURABLES
72,SIS,2.49,0.29,20.91,21.26,23285.0,326.0,111358.0,528.00,2659.59,60.0,H-SC,25.08,168.0,0.01,0.73,65.57,OX40N,NTT,MISC

In [23]:
# top 5 RSP
df_tmp = df_portfolio_features.sort_values(by = 'RSP', ascending=False)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
60,QUESS,3.36,24.44,39.75,73.90,52823.0,26096.0,132889.0,424.0,-33.33,88.0,X-SC,22.13,80.0,0.49,0.87,81.16,XY24,NTT,MISC
64,RELAXO,1.61,-48.36,194.92,52.31,146122.0,-70195.0,74965.0,1176.0,-45.02,63.0,X-SC,11.62,92.0,-0.48,0.49,67.61,X40N,NTT,FOOTWEAR
83,TTKPRESTIG,0.41,-18.23,22.41,0.09,18467.0,-18371.0,82406.0,770.0,91.25,70.0,M-SC,5.28,250.0,-0.99,0.54,46.73,OX40N,NTT,DURABLES
49,JSWINFRA,-1.28,8.89,6.93,16.43,16735.0,19713.0,241487.0,342.0,-6.62,59.0,X-MC,11.73,61.0,1.18,1.58,36.92,X40N,NTT,REALTY
16,CERA,-1.89,-16.67,48.67,23.89,71340.0,-29324.0,146579.0,9475.0,-19.57,61.0,H-SC,14.80,153.0,-0.41,0.96,42.49,OX40N,NTT,CERAMICS

In [24]:
# Top N allocation
df_tmp = df_portfolio_features.sort_values(by = 'CurrAlloc%', ascending=False)
top_n_values = [10, 25, 50]

sum_df = pd.DataFrame({
    'Top_N': top_n_values,
    'Sum_Alloc%': [df_tmp['CurrAlloc%'].head(n).sum() for n in top_n_values]
})

sum_df

   Top_N  Sum_Alloc%
0     10       19.25
1     25       42.68
2     50       72.60

In [25]:
# market-cap-wise allocation
df_tmp = df_portfolio_features[cols]
df_tmp.groupby(df_tmp['Conviction'].str[-2:])['CurrAlloc%'].sum().sort_values(ascending=False)

Conviction
SC    43.68
LC    30.11
MC    26.20
Name: CurrAlloc%, dtype: float64

In [26]:
# criteria-wise allocation
df_portfolio_features.groupby('Criteria')['CurrAlloc%'].sum().sort_values(ascending=False)

Criteria
XY24     27.89
X40      24.67
X40N     17.35
XR        8.82
OX40N     7.13
AR        6.83
XY25      6.39
SR        0.91
Name: CurrAlloc%, dtype: float64

In [27]:
# conviction-wise allocation
df_portfolio_features.groupby('Conviction')['CurrAlloc%'].sum().sort_values(ascending=False)

Conviction
X-LC    28.17
H-SC    22.99
X-MC    20.99
M-SC    10.09
X-SC    10.04
H-MC     2.76
M-MC     2.07
H-LC     1.14
M-LC     0.80
L-SC     0.56
L-MC     0.38
Name: CurrAlloc%, dtype: float64

In [28]:
# sector-wise stats
df_tmp = df_portfolio_features.groupby('Category')[['CurrAlloc%', 'Current', 'Current P/L', 'FTT Amt']].sum().sort_values(by=['Current', 'Current P/L'], ascending=False)
df_tmp['Current P/L%'] = round(df_tmp['Current P/L'] * 100 / df_tmp['Current'], 2)
df_tmp['FTT%'] = round(df_tmp['FTT Amt'] * 100 / df_tmp['Current'], 2)
cols = ['CurrAlloc%', 'Current P/L%', 'FTT%']
df_tmp[cols].sort_values(by=['CurrAlloc%'], ascending=False)

               CurrAlloc%  Current P/L%    FTT%
Category
FMCG                14.33        -20.96   63.40
FINANCE             11.36         -6.31   52.37
IT                   9.73        -51.61  127.41
MISC                 7.25        -21.08   73.03
AUTO                 6.68         -7.48   47.56
BANKS                5.80         -2.53   49.94
PAINTS               5.48        -17.84   37.95
INSURANCE            5.33         -1.77   36.10
PHARMA               5.19          6.42   22.54
ELECTRICAL           4.08        -13.50   53.55
CHEMICALS            2.21        -20.03   91.24
HEALTHCARE           2.08        -12.56   41.94
APPARELS             1.92          8.43   22.32
AC                   1.74        -19.85   52.34
FOOTWEAR             1.71        -68.35  135.85
DURABLES             1.62        -56.64   94.75
BREWERIES            1.60          3.90   16.06
REALTY               1.58          8.16    6.93
TRAVEL               1.52        -93.47  190.35
CERAMICS             1.42        -41.58   84.59
CABLES               1.30         25.59   54.72
ENGINEERING          1.26        -26.32   84.10
REFINERIES           1.09        -20.63   51.15
JEWELLERY            1.08        -92.54  159.44
CEMENT               1.08        -63.09  185.11
ENTERTAINMENT        0.73        -72.74  175.77
TEXTILES             0.42        -44.93   86.26
HOTELS               0.40        -85.39  150.78

In [29]:
# money to be made criteria-wise
df_portfolio_features.groupby('Criteria')['FTT Amt'].agg(['sum', 'count']).sort_values(by='sum', ascending=False)

                sum  count
Criteria
XY24      3340256.0     21
X40       1910162.0     19
XR        1333909.0     13
AR        1132536.0      9
X40N      1072874.0     13
OX40N      702153.0     10
XY25       460260.0      5
SR         279364.0      2

In [30]:
# money to be made conviction-wise
df_portfolio_features.groupby('Conviction')['FTT Amt'].agg(['sum', 'count']).sort_values(by='sum', ascending=False)

                  sum  count
Conviction
H-SC        3265610.0     24
X-LC        1980095.0     21
X-MC        1513148.0     15
M-SC        1375938.0     14
X-SC        1271779.0      9
H-MC         277026.0      2
L-SC         204446.0      2
M-LC         170349.0      1
M-MC          70278.0      2
H-LC          58863.0      1
L-MC          43982.0      1

In [31]:
# money to be made criteria and conviction-wise
df_portfolio_features.groupby(['Conviction', 'Criteria'])['FTT Amt'].agg(['sum', 'count']).sort_values(by='sum', ascending=False)

                           sum  count
Conviction Criteria
X-LC       X40       1050722.0     10
H-SC       AR         951840.0      5
           XY24       941509.0      6
M-SC       XY24       810542.0      6
H-SC       XR         803045.0      7
X-SC       XY24       754034.0      4
X-MC       X40        647954.0      7
           X40N       392250.0      4
X-LC       X40N       374365.0      6
           XY24       360858.0      2
X-SC       X40N       306259.0      3
M-SC       OX40N      300205.0      5
H-SC       OX40N      289852.0      4
           SR         279364.0      2
H-MC       XY24       250600.0      1
X-MC       XY25       250231.0      2
           XY24       222713.0      2
X-SC       X40        211486.0      2
M-SC       XR         191144.0      2
M-LC       XR         170349.0      1
X-LC       XY25       161111.0      2
L-SC       OX40N      112096.0      1
           XR          92350.0      1
M-SC       AR          74047.0      1
H-LC       AR          58863.0      1
M-MC       XY25        48918.0      1
L-MC       XR          43982.0      1
X-LC       XR          33039.0      1
H-MC       AR          26426.0      1
M-MC       AR          21360.0      1

In [32]:
# notebook execution time

end_time = time.time()
execution_time = round(end_time - start_time, 0)
print(f"Notebook execution time: {execution_time} seconds")

Notebook execution time: 32.0 seconds