<a href="https://colab.research.google.com/github/ankit-rathi/Quantvesting_v2/blob/main/myStocks_Portfolio_Analysis.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
'''
!pip install pandas==2.2.2 -qq
!pip install pyxirr -qq
!pip install ta -qq
!pip install yfinance==0.2.59 -qq
'''

'\n!pip install pandas==2.2.2 -qq\n!pip install pyxirr -qq\n!pip install ta -qq\n!pip install yfinance==0.2.59 -qq\n'

In [2]:
# import libraries

import numpy as np
import pandas as pd
import datetime
import warnings
warnings.filterwarnings('ignore')
import yfinance as yfin
import ta
import matplotlib.pyplot as plt
import requests

In [3]:
# notebook start time
import time
import datetime
import pytz

start_time = time.time()

# function to print date timestamp
def print_date_time():
  tz_NY = pytz.timezone('Asia/Kolkata')
  datetime_NY = datetime.datetime.now(tz_NY)
  print("Run date time (IST):", datetime_NY.strftime("%Y-%m-%d %H:%M:%S"))

In [4]:
# function to get booked and reserved amount
def get_amt():
  # fetch the JSON data from the URL
  url = "https://raw.githubusercontent.com/ankit-rathi/Tradevesting_v1/main/data/myPortfolioAmts.json"
  response = requests.get(url)
  pf_amts = response.json()  # parse the JSON data

  # extract values from the JSON
  py_booked_amt_dm = pf_amts["py_booked_amt_dm"]
  py_booked_amt_sv = pf_amts["py_booked_amt_sv"]
  cy_booked_amt_dm = pf_amts["cy_booked_amt_dm"]
  cy_booked_amt_sv = pf_amts["cy_booked_amt_sv"]
  reserve_amt_dm = pf_amts["reserve_amt_dm"]
  reserve_amt_sv = pf_amts["reserve_amt_sv"]

  # perform calculations
  py_booked_amt = py_booked_amt_dm + py_booked_amt_sv
  cy_booked_amt = cy_booked_amt_dm + cy_booked_amt_sv
  reserve_amt = reserve_amt_dm + reserve_amt_sv
  total_booked_amt = py_booked_amt + cy_booked_amt

  return total_booked_amt, reserve_amt, cy_booked_amt, py_booked_amt

gen_output = 0

In [5]:
# function to format the amount
def format_amt(number):
    abs_number = abs(number)

    if abs_number >= 1_00_00_000:  # Crores
        formatted_amt = f"{number / 1_00_00_000:.2f} C"
    elif abs_number >= 1_00_000:  # Lakhs
        formatted_amt = f"{number / 1_00_000:.2f} L"
    elif abs_number >= 1_000:  # Thousands
        formatted_amt = f"{number / 1_000:.2f} K"
    else:
        formatted_amt = f"{number:.2f}"

    return formatted_amt

# function to set start and end date
def get_start_end_date():
  start_date = (datetime.date.today() + datetime.timedelta(days=-365)).strftime('%Y-%m-%d')
  end_date = (datetime.date.today() + datetime.timedelta(days=1)).strftime('%Y-%m-%d')
  return start_date, end_date

# function to fetch my portfolio csv
def get_mypfs_df():
  mypfs_df = pd.read_csv('https://raw.githubusercontent.com/ankit-rathi/Tradevesting_v1/main/data/myPortfolioStocks.csv')
  return mypfs_df

# function to fetch my prospects csv
def get_mypps_df():
  mypps_df = pd.read_csv('https://raw.githubusercontent.com/ankit-rathi/Tradevesting_v1/main/data/myProspectsScrips.csv')
  return mypps_df

# function to fetch screener data
def get_myscreen_df():
  myscreen_df = pd.read_csv('https://raw.githubusercontent.com/ankit-rathi/Tradevesting_v1/main/data/myScreenerDB.csv')
  return myscreen_df

# function to fetch momentum data
def get_myinvmt_df():
  myinvmt_df = pd.read_csv('https://raw.githubusercontent.com/ankit-rathi/Tradevesting_v1/main/data/myInvestments.csv')
  return myinvmt_df

# function to get the stock ids
def get_stock_ids(df_pf):
  stock_n100 = df_pf['Symbol'].unique()

  exclude = ['CADILAHC','MMTC', 'MASFIN']

  stock_ids = df_pf[~df_pf['Symbol'].isin(exclude) ]['Symbol'].unique()

  #mypf = mypf[mypf.Forecast.notnull()]
  #stock_ids = mypf['Symbol'].unique()

  #stock_ids.sort()
  return stock_ids

# get features from screener data
def get_screener_features():
  myscreen_df = get_myscreen_df()
  cols = ['Symbol', 'EPS', 'MedPE', 'ROCE%', 'ROE%', 'CapType']
  return myscreen_df[cols]

# get relative strength
def get_relative_strength(stock_list):

    # Dictionary to store stock tickers and their corresponding percentage price change
    stock_changes = {}

    # Loop through each stock and fetch its price data
    for stock in stock_list:
        try:
            # Download the stock data for the given date range
            stock_data = yfin.Ticker(stock + '.NS').history(period='1mo', interval='1d')[map(str.title, ['open', 'close', 'low', 'high', 'volume'])]

            # Calculate the percentage change for the stock
            if len(stock_data) > 0:
                start_price = stock_data['Close'].iloc[0]
                end_price = stock_data['Close'].iloc[-1]
                percent_change = round(((end_price - start_price) / start_price) * 100, 2)
                stock_changes[stock] = percent_change
            else:
                stock_changes[stock] = np.nan  # If no data is available, set to NaN

        except Exception as e:
            print(f"Error fetching data for {stock}: {e}")
            stock_changes[stock] = np.nan

    # Create a DataFrame with stock tickers and their percentage changes
    df = pd.DataFrame(list(stock_changes.items()), columns=['Symbol', 'Percent_Change'])

    # Drop any stocks with missing data (NaN values)
    df = df.dropna()

    # Calculate the percentile rank based on percentage change
    df['RSP'] = round(df['Percent_Change'].rank(pct=True) * 100, 2)
    cols = ['Symbol', 'RSP']
    df = df[cols]
    # Sort by percentile rank (optional)
    df = df.sort_values(by='RSP', ascending=False).reset_index(drop=True)

    return df

In [6]:
# function to get stock technicals
def stock_prec_dev(stock_symbol):
    #stock_symbol = 'ULTRACEMCO.NS'
    short_window = 20
    mid_window = 50
    long_window = 200
    moving_avg = 'SMA'

    start = datetime.datetime(*map(int, start_date.split('-')))
    end = datetime.datetime(*map(int, end_date.split('-')))

    stock_df = yfin.Ticker(stock_symbol + '.NS').history(period='max', interval='1d')[map(str.title, ['open', 'close', 'low', 'high', 'volume'])]

    stock_df['Max'] = round(max(stock_df['Close']),2)
    stock_df = stock_df[(stock_df.index <= end_date) & (stock_df.index >= start_date)]
    stock_df['200_SMA'] = round(stock_df['Close'].rolling(window = 200, min_periods = 1).mean(),0)
    stock_df['Dev%_200'] = round((stock_df['Close'] - stock_df['200_SMA'])*100/stock_df['200_SMA'],2)
    stock_df.dropna(axis = 0, inplace = True) # remove any null rows

    stock_df['20_SMA'] = stock_df['Close'].rolling(window=20).mean()
    stock_df['50_SMA'] = stock_df['Close'].rolling(window=50).mean()
    stock_df['Symbol'] = stock_symbol

    stock_df['Close'] = round(stock_df['Close'],2)
    stock_df['Min'] = round(min(stock_df['Close']),2)
    stock_df['RSI_14'] = ta.momentum.RSIIndicator(close=stock_df['Close'], window=14).rsi()
    stock_df['RSI_14'] = round(stock_df['RSI_14'],0)
    stock_df['Prev_Close'] = stock_df['Close'].shift(1)
    stock_df.drop(['Open', 'Low', 'High', 'Volume'], axis=1, inplace=True)
    stock_df = stock_df.tail(1)

    max_SMA = max(stock_df['20_SMA'].item(), stock_df['50_SMA'].item(), stock_df['200_SMA'].item())
    min_SMA = min(stock_df['20_SMA'].item(), stock_df['50_SMA'].item(), stock_df['200_SMA'].item())
    ABS_Spread = max_SMA - min_SMA
    stock_df['Spread%'] = round((ABS_Spread / stock_df['200_SMA'].item()) * 100,2)

    return stock_df

# function to compute stock attributes
def get_common_features(stock_ids, df_mypf):

  df_prec_dev = pd.DataFrame()
  df_tmp = get_screener_features()
  df_rs = get_relative_strength(stock_ids)

  for stock_id in stock_ids:
      tmp = stock_prec_dev(stock_id)
      tmp = tmp.reset_index()
      df_prec_dev = pd.concat([df_prec_dev, tmp], ignore_index = True)
  df_prec_dev = pd.merge(df_prec_dev, df_mypf, on= 'Symbol')
  df_prec_dev = pd.merge(df_prec_dev, df_tmp, on= 'Symbol', how='left')
  df_prec_dev = pd.merge(df_prec_dev, df_rs, on= 'Symbol', how='left')
  #print(df_prec_dev.columns)
  df_prec_dev['Curr_PE'] = round(df_prec_dev['Close']/df_prec_dev['EPS'],1)
  df_prec_dev['Dev%_PE'] = round((df_prec_dev['Curr_PE'] - df_prec_dev['MedPE'])*100/df_prec_dev['MedPE'],2)
  df_prec_dev['Conviction'] = df_prec_dev['Conviction'] + '-' + df_prec_dev['CapType']
  return df_prec_dev

# function to arrange stock features
def arrange_features(df_stocks, common_cols, diff_cols):
  df_stocks_common = df_stocks[common_cols].drop_duplicates()
  df_stocks_diff = df_stocks[diff_cols]
  df_stocks_diff['Investment'] = df_stocks_diff['AvgCost'] * df_stocks_diff['Shares']
  df_stocks_diff = df_stocks_diff.groupby(['Symbol'])[['Shares', 'Investment']].aggregate(['sum']).reset_index()
  df_stocks_diff.columns = ['Symbol', 'Shares', 'Investment']
  df_stocks_diff['AvgCost'] = round(df_stocks_diff['Investment']/df_stocks_diff['Shares'],2)
  df_stocks = pd.merge(df_stocks_diff, df_stocks_common, on='Symbol')
  return df_stocks

# plot fact distribution across dimension
def plot_pie_chart(df, dimension, fact):
  # grouping the data by category and calculating the sum of fact for each type
  grouped_data = df.groupby(dimension)[fact].sum()

  # sorting the grouped data in descending order
  grouped_data = grouped_data.sort_values(ascending=False)

  # creating a pie chart
  grouped_data.plot.pie(autopct='%1.1f%%', startangle=90, figsize=(6, 6))

  # adding a title and displaying the plot
  plt.title(f'{dimension} {fact} Distribution')
  plt.ylabel('')  # To hide the y-label
  plt.show()

In [7]:
# function to get portfolio features

def get_portfolio_features(df_common_features):

  print_date_time()
  print('-------------------')

  #df_common_features["Target"] = df_common_features["Target"].fillna(df_common_features["Max"])
  df_common_features['NTT'] = np.where(df_common_features['Strategy']== 'NTT', df_common_features["Target"], df_common_features['Max'])
  df_common_features['LTT'] = np.where(df_common_features['Strategy']== 'BTT', df_common_features["Target"], df_common_features['Max'])
  df_common_features['BOL'] = df_common_features['Min']

  tmp_df = df_common_features[df_common_features['Symbol'].isin(mypf_df[mypf_df['InPortfolio'] != 'NA'].Symbol.values)]
  print('qualified stocks: '+str(len(tmp_df['Symbol'].unique())))
  tmp_df1 = tmp_df[tmp_df['LatestQtr'] == 1]
  print('with latest results: '+str(len(tmp_df1['Symbol'].unique())))
  tmp_df1 = tmp_df1[tmp_df1['StarStock'] == 1]
  print('still star stocks: '+str(len(tmp_df1['Symbol'].unique())))
  tmp_df['Investment'] = tmp_df['AvgCost'] * tmp_df['Shares']
  tmp_df['Current'] = round(tmp_df['Close'] * tmp_df['Shares'],0)
  tmp_df['Previous'] = tmp_df['Prev_Close'] * tmp_df['Shares']
  tmp_df['EstimatedST'] = tmp_df['NTT'] * tmp_df['Shares']
  tmp_df['EstimatedLT'] = tmp_df['LTT'] * tmp_df['Shares']
  tmp_df['Current P/L'] = round((tmp_df['Current'] - tmp_df['Investment']),0)
  tmp_df['Today P/L%'] = round((tmp_df['Current'] - tmp_df['Previous'])*100/tmp_df['Previous'],2)
  tmp_df['Current P/L%'] = round((tmp_df['Current'] - tmp_df['Investment'])*100/tmp_df['Investment'],2)
  tmp_df['EstimatedST P/L%'] = round((tmp_df['EstimatedST'] - tmp_df['Investment'])*100/tmp_df['Investment'],2)
  tmp_df['EstimatedLT P/L%'] = round((tmp_df['EstimatedLT'] - tmp_df['Investment'])*100/tmp_df['Investment'],2)
  tmp_df['NTT%'] = round((tmp_df['NTT'] - tmp_df['Close'])*100/tmp_df['Close'],2)
  tmp_df['LTT%'] = round((tmp_df['LTT'] - tmp_df['Close'])*100/tmp_df['Close'],2)
  tmp_df['Gained%'] = round((tmp_df['Close'] - tmp_df['BOL'])*100/tmp_df['BOL'],2)
  investment = round(sum(tmp_df['AvgCost']*tmp_df['Shares']),0)
  current = round(sum(tmp_df['Close']*tmp_df['Shares']),0)
  tmp_df['InitAlloc%'] = round(tmp_df['Investment']*100/investment,2)
  tmp_df['CurrAlloc%'] = round(tmp_df['Current']*100/current,2)
  tmp_df['FTT'] = tmp_df['LTT']
  tmp_df.loc[tmp_df['Strategy'] == 'NTT', 'FTT'] = tmp_df['NTT']
  tmp_df['FTT%'] = tmp_df['LTT%']
  tmp_df.loc[tmp_df['Strategy'] == 'NTT', 'FTT%'] = tmp_df['NTT%']
  tmp_df['FTT Amt'] = round(tmp_df['FTT%'] * tmp_df['Current']/100,0)
  tmp_df['OTT%'] = round((tmp_df['FTT'] - tmp_df['AvgCost'])*100/tmp_df['AvgCost'],2)
  tmp_df['RRR Ind'] = round(tmp_df['Current P/L']/tmp_df['FTT Amt'],2)
  tmp_df['Risk Ind'] = round(tmp_df['Current P/L%']*tmp_df['CurrAlloc%'],0)

  return tmp_df

# function to print portfolio features
def print_portfolio_stats(df_portfolio_features, myinvmt_df):
  from pyxirr import xirr

  total_booked_amt, reserve_amt, cy_booked_amt, py_booked_amt = get_amt()

  dates = myinvmt_df['Date'].values
  dates = np.append(dates, datetime.date.today().strftime('%d-%b-%y'))
  investment = myinvmt_df['Investment'].values
  dates= pd.to_datetime(dates)

  current = round(sum(df_portfolio_features['Close']*df_portfolio_features['Shares']),0) + reserve_amt
  investment_xirr = np.append(investment, current)
  cagr = round(xirr(pd.DataFrame({"dates": dates, "amounts": investment_xirr}))*100,2)

  investment = -sum(investment)
  invested = round(sum(df_portfolio_features['AvgCost']*df_portfolio_features['Shares']),0) + reserve_amt
  previous = round(sum(df_portfolio_features['Prev_Close']*df_portfolio_features['Shares']),0) + reserve_amt
  cy_invested = investment + py_booked_amt

  today_pnl_amount = current-previous
  today_pnl_percentage = round((current-previous)*100/previous,2)

  curr_pnl_amount = current-invested
  curr_pnl_percentage = round((curr_pnl_amount)*100/(cy_invested),2)

  cy_pnl_amount = cy_booked_amt + curr_pnl_amount
  cy_pnl_percentage = round((cy_pnl_amount)*100/cy_invested,2)

  overall_pnl_amount = total_booked_amt + curr_pnl_amount
  overall_pnl_percentage = round((overall_pnl_amount)*100/investment,2)

  estimate_st = round(sum(df_portfolio_features['FTT']*df_portfolio_features['Shares']),0)  + reserve_amt
  est_st_pnl_amount = estimate_st-current
  est_st_pnl_percentage = round((est_st_pnl_amount)*100/current,2)

  estimate_lt = round(sum(df_portfolio_features['LTT']*df_portfolio_features['Shares']),0)  + reserve_amt
  est_lt_pnl_amount = estimate_lt-current
  est_lt_pnl_percentage = round((est_lt_pnl_amount)*100/current,2)

  total_profit = round(sum(df_portfolio_features[df_portfolio_features['Current P/L%'] > 0]['Current']) - sum(df_portfolio_features[df_portfolio_features['Current P/L%'] > 0]['Investment']),0)
  total_loss = round(sum(df_portfolio_features[df_portfolio_features['Current P/L%'] < 0]['Current']) - sum(df_portfolio_features[df_portfolio_features['Current P/L%'] < 0]['Investment']),0)

  cy_booked_percentage = round((cy_booked_amt)*100/current,2)
  py_booked_percentage = round((py_booked_amt)*100/investment,2)
  total_booked_percentage = round((total_booked_amt)*100/investment,2)

  print('-------------------')
  print('Initial Investment: ', format_amt(investment))
  print('CY Investment: ', format_amt(cy_invested))
  print('Reserve: ', format_amt(reserve_amt))
  print('Current: ',  format_amt(current))
  print('-------------------')
  print('Today PnL: '+ '{} ({}%)'.format(format_amt(today_pnl_amount), today_pnl_percentage))
  print('Current PnL: '+ '{} ({}%)'.format(format_amt(curr_pnl_amount), curr_pnl_percentage))
  print('CY Booked + Current PnL: '+ '{} ({}%)'.format(format_amt(cy_pnl_amount), cy_pnl_percentage))
  print('-------------------')
  print('Total profit: ', format_amt(total_profit))
  print('Total loss: ', format_amt(total_loss))
  print('-------------------')
  print('Total Booked + Current PnL: '+ '{} ({}%)'.format(format_amt(overall_pnl_amount), overall_pnl_percentage))
  print('Total Booked PnL: '+ '{} ({}%)'.format(format_amt(total_booked_amt), total_booked_percentage))
  print('Curr Year Booked PnL: '+ '{} ({}%)'.format(format_amt(cy_booked_amt), cy_booked_percentage))
  print('Prev Year Booked PnL: '+ '{} ({}%)'.format(format_amt(py_booked_amt), py_booked_percentage))
  print('===================')
  print('Est FTT: ',  format_amt(estimate_st))
  print('Est FTT PnL: '+ '{} ({}%)'.format(format_amt(est_st_pnl_amount), est_st_pnl_percentage))

  print('===================')
  print('Deployed: ', format_amt(investment))

  print('Current: ', format_amt(current))

  print('CAGR/XIRR %: '+'{}%'.format(cagr))

In [8]:
# get start and end date
start_date, end_date = get_start_end_date()

# get portfolio and prospects data
mypfs_df = get_mypfs_df()
mypps_df = get_mypps_df()
myinvmt_df = get_myinvmt_df()

# merge above datasets
mypf_df = pd.merge(mypfs_df, mypps_df, on="Symbol")

# seggregate dm and sv portfolio
dm_pf = mypf_df[mypf_df['InPortfolio'] == 'DM']
sv_pf = mypf_df[mypf_df['InPortfolio'] == 'SV']

# build portfolio stock dataframe
dm_stocks = get_stock_ids(dm_pf)
sv_stocks = get_stock_ids(sv_pf)
df_stocks = pd.concat([dm_pf,sv_pf], ignore_index = True)

# arrange common and diff stock features
common_cols = ['Symbol', 'Target', 'Criteria', 'Strategy', 'CumlRnk', 'LatestQtr', 'StarStock', 'Conviction', 'Category', 'InFolio', 'XIRR', 'MBQ']
diff_cols = ['Symbol', 'AvgCost', 'Shares']
df_stocks = arrange_features(df_stocks, common_cols, diff_cols)

# get common features
stock_ids = df_stocks['Symbol'].values
df_common_features = get_common_features(stock_ids, df_stocks)

df_common_features.reset_index(drop=True, inplace=True)
df_common_features.drop(['Date'], axis=1, inplace=True)
# get and print portfolio features
df_portfolio_features = get_portfolio_features(df_common_features)

print_portfolio_stats(df_portfolio_features, myinvmt_df)

df = df_portfolio_features
#plot_pie_chart(df, 'CapType', 'Current')
list_ox40n = list(df[df['MBQ'].str.contains('OX40N', na=False)]['Symbol'].values)

Run date time (IST): 2026-04-10 10:17:59
-------------------
qualified stocks: 86
with latest results: 26
still star stocks: 16
-------------------
Initial Investment:  1.36 C
CY Investment:  1.62 C
Reserve:  1.61 K
Current:  1.38 C
-------------------
Today PnL: 1.49 L (1.09%)
Current PnL: -39.25 L (-24.15%)
CY Booked + Current PnL: -23.36 L (-14.37%)
-------------------
Total profit:  1.37 L
Total loss:  -40.61 L
-------------------
Total Booked + Current PnL: 3.62 L (2.67%)
Total Booked PnL: 42.87 L (31.64%)
Curr Year Booked PnL: 15.89 L (11.52%)
Prev Year Booked PnL: 26.98 L (19.91%)
===================
Est FTT:  2.48 C
Est FTT PnL: 1.10 C (79.78%)
===================
Deployed:  1.36 C
Current:  1.38 C
CAGR/XIRR %: 0.84%

In [9]:
# top 5 near their targets
cols = ['Symbol', 'Today P/L%', 'Current P/L%', 'FTT%', 'OTT%', 'FTT Amt', 'Current P/L', 'Current', 'FTT', 'Dev%_PE', 'RSI_14','Conviction', 'Spread%',  'CumlRnk', 'RRR Ind', 'CurrAlloc%', 'Gained%', 'Criteria', 'Strategy', 'Category']
df_tmp = df_portfolio_features[~df_portfolio_features['Symbol'].isin(['ENRIN','BLUSPRING','DIGITIDE'])]
df_tmp = df_tmp.sort_values(by = 'FTT Amt', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
5,ANGELONE,1.14,16.81,6.31,24.18,22481.0,51275.0,356275.0,303.00,-82.85,73.0,X-SC,5.09,97.0,2.28,2.58,36.30,X40N,NTT,FINANCE
50,MASFIN,-0.39,-5.40,28.51,21.57,26424.0,-5295.0,92685.0,397.04,-18.25,53.0,H-SC,4.79,167.0,-0.20,0.67,19.77,XR,ATH,FINANCE
77,TTKPRESTIG,2.17,-37.47,60.08,0.09,37857.0,-37766.0,63011.0,770.00,46.21,49.0,M-SC,21.76,250.0,-1.00,0.46,12.20,OX40N,NTT,DURABLES
67,SONACOMS,3.04,-6.76,49.18,39.09,46385.0,-6843.0,94316.0,804.02,-26.14,60.0,M-MC,8.05,193.0,-0.15,0.68,33.42,AR,ATH,AUTO
37,ICICIGI,1.24,-5.15,25.82,19.34,49007.0,-10305.0,189804.0,2252.93,-20.32,50.0,X-MC,7.44,66.0,-0.21,1.38,6.01,X40,ATH,INSURANCE

In [10]:
# top 5 today
df_tmp = df_portfolio_features.sort_values(by = 'Today P/L%', ascending=False)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
22,DEN,6.85,-44.78,157.29,42.07,73360.0,-37824.0,46640.0,75.00,65.80,66.0,M-SC,21.58,235.0,-0.52,0.34,26.85,AR,NTT,ENTERTAINMENT
31,HATHWAY,5.05,-37.97,179.36,73.29,120960.0,-41280.0,67440.0,31.40,682.61,65.0,H-SC,23.78,171.0,-0.34,0.49,26.72,XR,NTT,ENTERTAINMENT
55,RAJESHEXPO,4.99,-78.80,371.94,0.07,108182.0,-108091.0,29086.0,518.00,965.66,51.0,L-SC,44.12,268.0,-1.00,0.21,36.55,OX40N,NTT,JEWELLERY
6,ASIANPAINT,4.38,-14.75,46.07,24.52,111318.0,-41811.0,241628.0,3460.25,-14.00,59.0,X-LC,11.70,30.0,-0.38,1.75,11.67,X40,ATH,PAINTS
41,INDIGOPNTS,4.27,-41.51,71.00,0.02,72492.0,-72457.0,102102.0,1408.00,55.69,52.0,M-SC,29.63,222.0,-1.00,0.74,15.84,OX40N,NTT,PAINTS

In [11]:
# bottom 5 today
df_tmp = df_portfolio_features.sort_values(by = 'Today P/L%', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
43,INFY,-3.18,-12.23,52.95,34.24,145412.0,-38267.0,274621.0,1972.00,-31.06,46.0,X-LC,14.29,3.0,-0.26,1.99,5.61,X40,NTT,IT
73,TCS,-2.93,-26.22,71.56,26.57,244589.0,-121478.0,341795.0,4311.59,-37.40,49.0,X-LC,18.15,2.0,-0.50,2.48,6.67,X40,ATH,IT
33,HCLTECH,-2.09,-6.92,33.04,23.83,74401.0,-16739.0,225185.0,1908.19,-2.40,56.0,X-LC,9.77,8.0,-0.22,1.63,9.34,X40,ATH,IT
72,TATAELXSI,-1.29,-36.66,108.45,32.03,90557.0,-48334.0,83501.0,9161.00,-20.70,51.0,H-SC,20.88,158.0,-0.53,0.61,10.52,OX40N,NTT,IT
24,DMART,-0.50,5.61,22.71,29.60,59866.0,14010.0,263610.0,5391.45,-10.95,66.0,X-LC,4.70,14.0,0.23,1.91,20.49,X40N,ATH,FMCG

In [12]:
# top 5 to exit based on CumlRnk
df_tmp = df_portfolio_features[~df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])]
df_tmp = df_tmp[(df_tmp['Current P/L%'] > -1) & (df_tmp['Current P/L%'] < 1)].sort_values(by = 'CumlRnk', ascending=False)
df_tmp[cols].head()

Empty DataFrame
Columns: [Symbol, Today P/L%, Current P/L%, FTT%, OTT%, FTT Amt, Current P/L, Current, FTT, Dev%_PE, RSI_14, Conviction, Spread%, CumlRnk, RRR Ind, CurrAlloc%, Gained%, Criteria, Strategy, Category]
Index: []

In [13]:
# OX40N stocks to exit
df_tmp = df_portfolio_features[(df_portfolio_features['Symbol'].isin(list_ox40n))].sort_values(by = 'Current P/L%', ascending=False)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
26,FINCABLES,1.11,8.02,92.48,107.91,147490.0,11839.0,159483.0,1641.55,-2.59,53.0,M-SC,1.73,220.0,0.08,1.16,19.98,OX40N,ATH,CABLES
66,SIS,-0.02,-30.80,75.24,21.26,57808.0,-34200.0,76832.0,528.00,1803.63,58.0,H-SC,14.34,168.0,-0.59,0.56,14.24,OX40N,NTT,MISC
18,CERA,2.79,-32.35,83.13,23.89,98926.0,-56901.0,119002.0,9475.00,-34.84,64.0,H-SC,17.36,153.0,-0.58,0.86,14.36,OX40N,NTT,CERAMICS
72,TATAELXSI,-1.29,-36.66,108.45,32.03,90557.0,-48334.0,83501.0,9161.00,-20.70,51.0,H-SC,20.88,158.0,-0.53,0.61,10.52,OX40N,NTT,IT
48,KANSAINER,2.32,-36.72,79.32,13.47,135352.0,-99027.0,170640.0,340.00,-45.60,56.0,H-SC,23.35,162.0,-0.73,1.24,19.19,XY24,NTT,PAINTS

In [14]:
# top 5 to book for rotation
df_tmp = df_portfolio_features[(df_portfolio_features['Current P/L%'] > 20) ].sort_values(by = 'CumlRnk', ascending=False)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
1,ABB,0.56,22.03,19.29,45.57,61583.0,57629.0,319248.0,7934.0,-21.58,67.0,H-MC,15.17,125.0,0.94,2.32,41.77,AR,NTT,ELECTRICAL

In [15]:
# top 5 to monitor for exit
df_tmp = df_portfolio_features[~df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])]
df_tmp = df_tmp[(df_tmp['Current P/L%'] > 0) ].sort_values(by = 'Dev%_PE', ascending=False)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
26,FINCABLES,1.11,8.02,92.48,107.91,147490.0,11839.0,159483.0,1641.55,-2.59,53.0,M-SC,1.73,220.0,0.08,1.16,19.98,OX40N,ATH,CABLES
1,ABB,0.56,22.03,19.29,45.57,61583.0,57629.0,319248.0,7934.00,-21.58,67.0,H-MC,15.17,125.0,0.94,2.32,41.77,AR,NTT,ELECTRICAL

In [16]:
# top 5 to book for rotation from weak conviction
df_tmp = df_portfolio_features[~df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])]
df_tmp = df_tmp[~df_tmp['Criteria'].isin(['XY25','XY24','X40', 'X40N'])].sort_values(by = 'RRR Ind', ascending=False)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
1,ABB,0.56,22.03,19.29,45.57,61583.0,57629.0,319248.0,7934.00,-21.58,67.0,H-MC,15.17,125.0,0.94,2.32,41.77,AR,NTT,ELECTRICAL
26,FINCABLES,1.11,8.02,92.48,107.91,147490.0,11839.0,159483.0,1641.55,-2.59,53.0,M-SC,1.73,220.0,0.08,1.16,19.98,OX40N,ATH,CABLES
40,INDIAMART,-0.01,-9.76,129.08,106.72,143666.0,-12036.0,111300.0,4810.62,-59.38,53.0,H-SC,13.04,140.0,-0.08,0.81,6.93,AR,ATH,MISC
85,ZYDUSLIFE,0.88,-4.02,41.31,35.63,83097.0,-8420.0,201154.0,1286.17,-16.67,56.0,H-MC,6.04,120.0,-0.10,1.46,11.98,AR,ATH,PHARMA
67,SONACOMS,3.04,-6.76,49.18,39.09,46385.0,-6843.0,94316.0,804.02,-26.14,60.0,M-MC,8.05,193.0,-0.15,0.68,33.42,AR,ATH,AUTO

In [17]:
# top 5 to accumulate based on lowest RSI_14
df_tmp = df_portfolio_features[df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])].sort_values(by = 'RSI_14', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
53,PGHH,0.26,-27.32,81.64,32.01,126692.0,-58336.0,155184.0,17616.87,-50.89,38.0,X-MC,20.92,57.0,-0.46,1.13,6.14,X40,ATH,FMCG
21,DABUR,0.59,-15.55,70.16,43.70,146982.0,-38572.0,209496.0,735.00,-23.35,42.0,X-MC,13.60,70.0,-0.26,1.52,5.24,XY24,BTT,FMCG
78,UNITDSPR,0.05,-8.15,31.49,20.77,67720.0,-19092.0,215052.0,1644.00,-18.49,42.0,X-MC,5.42,64.0,-0.28,1.56,2.58,X40N,NTT,BREWERIES
38,ICICIPRULI,0.77,-9.63,44.66,30.73,79508.0,-18976.0,178029.0,790.00,-33.87,43.0,X-MC,11.59,78.0,-0.24,1.29,8.48,X40,ATH,INSURANCE
82,VOLTAS,0.59,1.03,43.71,45.20,84677.0,1983.0,193725.0,1856.00,15.72,43.0,X-MC,6.08,79.0,0.02,1.41,7.90,XY25,NTT,AC

In [18]:
# top 5 to accumulate based on Spread and CumlRnk
df_tmp = df_portfolio_features[df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])]
df_tmp = df_tmp[(df_tmp['CumlRnk'] < 100)].sort_values(by = 'Spread%', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
65,SIEMENS,1.64,-12.00,42.63,25.51,69811.0,-22335.0,163760.0,4671.50,37.53,58.0,H-LC,1.37,51.0,-0.32,1.19,20.07,AR,ATH,ELECTRICAL
24,DMART,-0.50,5.61,22.71,29.60,59866.0,14010.0,263610.0,5391.45,-10.95,66.0,X-LC,4.70,14.0,0.23,1.91,20.49,X40N,ATH,FMCG
59,RELIANCE,1.34,-13.48,44.83,25.30,77944.0,-27097.0,173866.0,1952.00,-15.80,45.0,X-LC,4.91,21.0,-0.35,1.26,11.01,XY25,BTT,REFINERIES
5,ANGELONE,1.14,16.81,6.31,24.18,22481.0,51275.0,356275.0,303.00,-82.85,73.0,X-SC,5.09,97.0,2.28,2.58,36.30,X40N,NTT,FINANCE
78,UNITDSPR,0.05,-8.15,31.49,20.77,67720.0,-19092.0,215052.0,1644.00,-18.49,42.0,X-MC,5.42,64.0,-0.28,1.56,2.58,X40N,NTT,BREWERIES

In [19]:
# top 5 to accumulate based on lowest Gained%
df_tmp = df_portfolio_features[df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])].sort_values(by = 'Gained%', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
2,ABBOTINDIA,0.23,-13.32,36.20,18.07,56124.0,-23815.0,155040.0,35195.0,-26.29,44.0,X-MC,11.34,58.0,-0.42,1.12,1.39,X40,ATH,PHARMA
78,UNITDSPR,0.05,-8.15,31.49,20.77,67720.0,-19092.0,215052.0,1644.0,-18.49,42.0,X-MC,5.42,64.0,-0.28,1.56,2.58,X40N,NTT,BREWERIES
8,AWL,1.86,-37.88,168.85,67.02,373751.0,-134958.0,221351.0,485.0,-66.49,47.0,X-SC,25.32,81.0,-0.36,1.61,4.70,XY24,NTT,FMCG
21,DABUR,0.59,-15.55,70.16,43.70,146982.0,-38572.0,209496.0,735.0,-23.35,42.0,X-MC,13.60,70.0,-0.26,1.52,5.24,XY24,BTT,FMCG
35,HINDUNILVR,1.50,-15.77,34.95,13.67,75677.0,-40533.0,216530.0,2922.0,-37.41,51.0,X-LC,11.85,9.0,-0.54,1.57,5.51,XY25,NTT,FMCG

In [20]:
# top 5 to accumulate based on lowest CurrAlloc%
df_tmp = df_portfolio_features[df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])].sort_values(by = 'CurrAlloc%', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
58,RELAXO,4.00,-62.13,302.19,52.31,166117.0,-90189.0,54971.0,1176.00,-59.64,51.0,X-SC,33.08,92.0,-0.54,0.40,22.91,X40N,NTT,FOOTWEAR
12,BATAINDIA,1.50,-54.09,194.49,35.20,114895.0,-69595.0,59075.0,2096.00,-22.60,53.0,X-SC,34.14,91.0,-0.61,0.43,17.16,X40,NTT,FOOTWEAR
54,QUESS,2.59,-20.53,118.83,73.90,100847.0,-21926.0,84867.0,424.00,-57.02,59.0,X-SC,21.91,80.0,-0.22,0.62,14.16,XY24,NTT,MISC
36,HONAUT,1.17,-27.18,107.79,51.31,151364.0,-52413.0,140425.0,58357.33,-39.39,45.0,X-SC,19.19,90.0,-0.35,1.02,6.69,X40N,ATH,ELECTRICAL
2,ABBOTINDIA,0.23,-13.32,36.20,18.07,56124.0,-23815.0,155040.0,35195.00,-26.29,44.0,X-MC,11.34,58.0,-0.42,1.12,1.39,X40,ATH,PHARMA

In [21]:
# top 5 to accumulate based on CumlRnk
df_tmp = df_portfolio_features.sort_values(by = 'CumlRnk', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
45,ITC,0.28,-19.97,48.76,19.06,132749.0,-67916.0,272250.0,452.00,-55.92,51.0,X-LC,19.67,1.0,-0.51,1.97,5.61,X40,NTT,FMCG
73,TCS,-2.93,-26.22,71.56,26.57,244589.0,-121478.0,341795.0,4311.59,-37.40,49.0,X-LC,18.15,2.0,-0.50,2.48,6.67,X40,ATH,IT
43,INFY,-3.18,-12.23,52.95,34.24,145412.0,-38267.0,274621.0,1972.00,-31.06,46.0,X-LC,14.29,3.0,-0.26,1.99,5.61,X40,NTT,IT
75,TMPV,1.17,-23.25,77.96,36.58,212903.0,-82749.0,273092.0,600.00,-83.62,55.0,X-LC,12.51,4.0,-0.39,1.98,13.83,XY24,NTT,AUTO
33,HCLTECH,-2.09,-6.92,33.04,23.83,74401.0,-16739.0,225185.0,1908.19,-2.40,56.0,X-LC,9.77,8.0,-0.22,1.63,9.34,X40,ATH,IT

In [22]:
# top 5 for average up
df_tmp = df_portfolio_features[(df_portfolio_features['Dev%_200'] > 5)].sort_values(by = 'CurrAlloc%', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
67,SONACOMS,3.04,-6.76,49.18,39.09,46385.0,-6843.0,94316.0,804.02,-26.14,60.0,M-MC,8.05,193.0,-0.15,0.68,33.42,AR,ATH,AUTO
62,SATIN,2.74,-11.10,70.79,51.83,173873.0,-30666.0,245618.0,274.00,-19.84,66.0,H-SC,3.06,159.0,-0.18,1.78,19.65,XY24,NTT,FINANCE
24,DMART,-0.50,5.61,22.71,29.60,59866.0,14010.0,263610.0,5391.45,-10.95,66.0,X-LC,4.70,14.0,0.23,1.91,20.49,X40N,ATH,FMCG
1,ABB,0.56,22.03,19.29,45.57,61583.0,57629.0,319248.0,7934.00,-21.58,67.0,H-MC,15.17,125.0,0.94,2.32,41.77,AR,NTT,ELECTRICAL
5,ANGELONE,1.14,16.81,6.31,24.18,22481.0,51275.0,356275.0,303.00,-82.85,73.0,X-SC,5.09,97.0,2.28,2.58,36.30,X40N,NTT,FINANCE

In [23]:
# top 5 RSP
df_tmp = df_portfolio_features.sort_values(by = 'RSP', ascending=False)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
5,ANGELONE,1.14,16.81,6.31,24.18,22481.0,51275.0,356275.0,303.00,-82.85,73.0,X-SC,5.09,97.0,2.28,2.58,36.30,X40N,NTT,FINANCE
80,VALIANTORG,-0.50,-44.58,214.22,74.15,194244.0,-72930.0,90675.0,838.00,-262.82,61.0,H-SC,22.78,145.0,-0.38,0.66,34.94,XR,NTT,CHEMICALS
52,PAGEIND,-0.14,-6.36,43.23,34.11,108637.0,-17079.0,251300.0,51418.64,-32.80,70.0,X-MC,17.24,55.0,-0.16,1.82,18.87,X40,ATH,APPARELS
18,CERA,2.79,-32.35,83.13,23.89,98926.0,-56901.0,119002.0,9475.00,-34.84,64.0,H-SC,17.36,153.0,-0.58,0.86,14.36,OX40N,NTT,CERAMICS
31,HATHWAY,5.05,-37.97,179.36,73.29,120960.0,-41280.0,67440.0,31.40,682.61,65.0,H-SC,23.78,171.0,-0.34,0.49,26.72,XR,NTT,ENTERTAINMENT

In [24]:
# Top N allocation
df_tmp = df_portfolio_features.sort_values(by = 'CurrAlloc%', ascending=False)
top_n_values = [10, 25, 50]

sum_df = pd.DataFrame({
    'Top_N': top_n_values,
    'Sum_Alloc%': [df_tmp['CurrAlloc%'].head(n).sum() for n in top_n_values]
})

sum_df

   Top_N  Sum_Alloc%
0     10       21.01
1     25       45.92
2     50       77.72

In [25]:
# market-cap-wise allocation
df_tmp = df_portfolio_features[cols]
df_tmp.groupby(df_tmp['Conviction'].str[-2:])['CurrAlloc%'].sum().sort_values(ascending=False)

Conviction
SC    45.24
MC    29.39
LC    25.38
Name: CurrAlloc%, dtype: float64

In [26]:
# criteria-wise allocation
df_portfolio_features.groupby('Criteria')['CurrAlloc%'].sum().sort_values(ascending=False)

Criteria
XY24     27.22
X40      24.88
X40N     15.59
AR        9.27
XR        8.43
XY25      7.02
OX40N     6.80
SR        0.80
Name: CurrAlloc%, dtype: float64

In [27]:
# conviction-wise allocation
df_portfolio_features.groupby('Conviction')['CurrAlloc%'].sum().sort_values(ascending=False)

Conviction
X-LC    23.16
H-SC    22.12
X-MC    21.92
X-SC    12.44
M-SC    10.10
H-MC     5.06
M-MC     2.07
H-LC     1.19
M-LC     1.03
L-SC     0.58
L-MC     0.34
Name: CurrAlloc%, dtype: float64

In [28]:
# sector-wise stats
df_tmp = df_portfolio_features.groupby('Category')[['CurrAlloc%', 'Current', 'Current P/L', 'FTT Amt']].sum().sort_values(by=['Current', 'Current P/L'], ascending=False)
df_tmp['Current P/L%'] = round(df_tmp['Current P/L'] * 100 / df_tmp['Current'], 2)
df_tmp['FTT%'] = round(df_tmp['FTT Amt'] * 100 / df_tmp['Current'], 2)
cols = ['CurrAlloc%', 'Current P/L%', 'FTT%']
df_tmp[cols].sort_values(by=['CurrAlloc%'], ascending=False)

               CurrAlloc%  Current P/L%    FTT%
Category
FMCG                14.77        -22.69   66.23
FINANCE             13.55        -14.97   61.82
IT                  11.79        -38.69  109.27
MISC                 7.13        -36.62   95.96
ELECTRICAL           6.46         -8.91   50.61
PAINTS               5.28        -35.22   58.70
BANKS                4.64        -20.09   81.04
INSURANCE            4.53         -8.60   45.77
PHARMA               3.97         -7.19   40.93
AUTO                 3.74        -26.62   76.86
AC                   1.97        -18.18   50.23
HEALTHCARE           1.94        -33.69   68.58
TRAVEL               1.85        -75.38  163.19
APPARELS             1.82         -6.80   43.23
FOOTWEAR             1.82        -76.23  146.90
DURABLES             1.74        -61.63  100.96
BREWERIES            1.56         -8.88   31.49
REALTY               1.42        -13.28   31.89
CERAMICS             1.36        -63.39  113.03
REFINERIES           1.26        -15.58   44.83
CEMENT               1.23        -58.63  177.30
ENGINEERING          1.18        -48.47  116.38
CABLES               1.16          7.42   92.48
CHEMICALS            1.10        -75.08  217.91
JEWELLERY            1.09       -113.11  187.14
ENTERTAINMENT        0.83        -69.34  170.34
TEXTILES             0.45        -47.11   89.05
HOTELS               0.37       -124.70  203.95

In [29]:
# money to be made criteria-wise
df_portfolio_features.groupby('Criteria')['FTT Amt'].agg(['sum', 'count']).sort_values(by='sum', ascending=False)

                sum  count
Criteria
XY24      3842849.0     21
X40       1742665.0     16
XR        1330322.0     12
AR        1294272.0     10
X40N      1151260.0     10
OX40N      856087.0     10
XY25       473326.0      5
SR         309231.0      2

In [30]:
# money to be made conviction-wise
df_portfolio_features.groupby('Conviction')['FTT Amt'].agg(['sum', 'count']).sort_values(by='sum', ascending=False)

                  sum  count
Conviction
H-SC        3743418.0     24
X-MC        1711138.0     15
X-LC        1580474.0     13
M-SC        1525003.0     14
X-SC        1470328.0     10
H-MC         381761.0      3
L-SC         211246.0      2
M-LC         150584.0      1
M-MC         100702.0      2
H-LC          69811.0      1
L-MC          55547.0      1

In [31]:
# money to be made criteria and conviction-wise
df_portfolio_features.groupby(['Conviction', 'Criteria'])['FTT Amt'].agg(['sum', 'count']).sort_values(by='sum', ascending=False)

                           sum  count
Conviction Criteria
H-SC       XY24      1273615.0      6
           AR         960036.0      5
M-SC       XY24       883147.0      6
X-LC       X40        857412.0      7
X-SC       XY24       837826.0      4
H-SC       XR         833214.0      7
X-MC       X40        672482.0      7
           X40N       517644.0      4
X-SC       X40N       419731.0      4
M-SC       OX40N      380583.0      5
H-SC       OX40N      367322.0      4
X-LC       XY24       355556.0      2
H-SC       SR         309231.0      2
X-MC       XY25       265388.0      2
           XY24       255624.0      2
H-MC       XY24       237081.0      1
X-LC       X40N       213885.0      2
X-SC       X40        212771.0      2
M-SC       XR         187913.0      2
X-LC       XY25       153621.0      2
M-LC       XR         150584.0      1
H-MC       AR         144680.0      2
L-SC       OX40N      108182.0      1
           XR         103064.0      1
M-SC       AR          73360.0      1
H-LC       AR          69811.0      1
L-MC       XR          55547.0      1
M-MC       XY25        54317.0      1
           AR          46385.0      1

In [32]:
# notebook execution time

end_time = time.time()
execution_time = round(end_time - start_time, 0)
print(f"Notebook execution time: {execution_time} seconds")

Notebook execution time: 49.0 seconds