<a href="https://colab.research.google.com/github/ankit-rathi/Quantvesting_v2/blob/main/myStocks_Portfolio_Analysis.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
'''
!pip install pandas==2.2.2 -qq
!pip install pyxirr -qq
!pip install ta -qq
!pip install yfinance==0.2.59 -qq
'''

'\n!pip install pandas==2.2.2 -qq\n!pip install pyxirr -qq\n!pip install ta -qq\n!pip install yfinance==0.2.59 -qq\n'

In [2]:
# import libraries

import numpy as np
import pandas as pd
import datetime
import warnings
warnings.filterwarnings('ignore')
import yfinance as yfin
import ta
import matplotlib.pyplot as plt
import requests

In [3]:
# notebook start time
import time
import datetime
import pytz

start_time = time.time()

# function to print date timestamp
def print_date_time():
  tz_NY = pytz.timezone('Asia/Kolkata')
  datetime_NY = datetime.datetime.now(tz_NY)
  print("Run date time (IST):", datetime_NY.strftime("%Y-%m-%d %H:%M:%S"))

In [4]:
# function to get booked and reserved amount
def get_amt():
  # fetch the JSON data from the URL
  url = "https://raw.githubusercontent.com/ankit-rathi/Tradevesting_v1/main/data/myPortfolioAmts.json"
  response = requests.get(url)
  pf_amts = response.json()  # parse the JSON data

  # extract values from the JSON
  py_booked_amt_dm = pf_amts["py_booked_amt_dm"]
  py_booked_amt_sv = pf_amts["py_booked_amt_sv"]
  cy_booked_amt_dm = pf_amts["cy_booked_amt_dm"]
  cy_booked_amt_sv = pf_amts["cy_booked_amt_sv"]
  reserve_amt_dm = pf_amts["reserve_amt_dm"]
  reserve_amt_sv = pf_amts["reserve_amt_sv"]

  # perform calculations
  py_booked_amt = py_booked_amt_dm + py_booked_amt_sv
  cy_booked_amt = cy_booked_amt_dm + cy_booked_amt_sv
  reserve_amt = reserve_amt_dm + reserve_amt_sv
  total_booked_amt = py_booked_amt + cy_booked_amt

  return total_booked_amt, reserve_amt, cy_booked_amt, py_booked_amt

gen_output = 0

In [5]:
# function to format the amount
def format_amt(number):
    abs_number = abs(number)

    if abs_number >= 1_00_00_000:  # Crores
        formatted_amt = f"{number / 1_00_00_000:.2f} C"
    elif abs_number >= 1_00_000:  # Lakhs
        formatted_amt = f"{number / 1_00_000:.2f} L"
    elif abs_number >= 1_000:  # Thousands
        formatted_amt = f"{number / 1_000:.2f} K"
    else:
        formatted_amt = f"{number:.2f}"

    return formatted_amt

# function to set start and end date
def get_start_end_date():
  start_date = (datetime.date.today() + datetime.timedelta(days=-365)).strftime('%Y-%m-%d')
  end_date = (datetime.date.today() + datetime.timedelta(days=1)).strftime('%Y-%m-%d')
  return start_date, end_date

# function to fetch my portfolio csv
def get_mypfs_df():
  mypfs_df = pd.read_csv('https://raw.githubusercontent.com/ankit-rathi/Tradevesting_v1/main/data/myPortfolioStocks.csv')
  return mypfs_df

# function to fetch my prospects csv
def get_mypps_df():
  mypps_df = pd.read_csv('https://raw.githubusercontent.com/ankit-rathi/Tradevesting_v1/main/data/myProspectsScrips.csv')
  return mypps_df

# function to fetch screener data
def get_myscreen_df():
  myscreen_df = pd.read_csv('https://raw.githubusercontent.com/ankit-rathi/Tradevesting_v1/main/data/myScreenerDB.csv')
  return myscreen_df

# function to fetch momentum data
def get_myinvmt_df():
  myinvmt_df = pd.read_csv('https://raw.githubusercontent.com/ankit-rathi/Tradevesting_v1/main/data/myInvestments.csv')
  return myinvmt_df

# function to get the stock ids
def get_stock_ids(df_pf):
  stock_n100 = df_pf['Symbol'].unique()

  exclude = ['CADILAHC','MMTC', 'MASFIN']

  stock_ids = df_pf[~df_pf['Symbol'].isin(exclude) ]['Symbol'].unique()

  #mypf = mypf[mypf.Forecast.notnull()]
  #stock_ids = mypf['Symbol'].unique()

  #stock_ids.sort()
  return stock_ids

# get features from screener data
def get_screener_features():
  myscreen_df = get_myscreen_df()
  cols = ['Symbol', 'EPS', 'MedPE', 'ROCE%', 'ROE%', 'CapType']
  return myscreen_df[cols]

# get relative strength
def get_relative_strength(stock_list):

    # Dictionary to store stock tickers and their corresponding percentage price change
    stock_changes = {}

    # Loop through each stock and fetch its price data
    for stock in stock_list:
        try:
            # Download the stock data for the given date range
            stock_data = yfin.Ticker(stock + '.NS').history(period='1mo', interval='1d')[map(str.title, ['open', 'close', 'low', 'high', 'volume'])]

            # Calculate the percentage change for the stock
            if len(stock_data) > 0:
                start_price = stock_data['Close'].iloc[0]
                end_price = stock_data['Close'].iloc[-1]
                percent_change = round(((end_price - start_price) / start_price) * 100, 2)
                stock_changes[stock] = percent_change
            else:
                stock_changes[stock] = np.nan  # If no data is available, set to NaN

        except Exception as e:
            print(f"Error fetching data for {stock}: {e}")
            stock_changes[stock] = np.nan

    # Create a DataFrame with stock tickers and their percentage changes
    df = pd.DataFrame(list(stock_changes.items()), columns=['Symbol', 'Percent_Change'])

    # Drop any stocks with missing data (NaN values)
    df = df.dropna()

    # Calculate the percentile rank based on percentage change
    df['RSP'] = round(df['Percent_Change'].rank(pct=True) * 100, 2)
    cols = ['Symbol', 'RSP']
    df = df[cols]
    # Sort by percentile rank (optional)
    df = df.sort_values(by='RSP', ascending=False).reset_index(drop=True)

    return df

In [6]:
# function to get stock technicals
def stock_prec_dev(stock_symbol):
    #stock_symbol = 'ULTRACEMCO.NS'
    short_window = 20
    mid_window = 50
    long_window = 200
    moving_avg = 'SMA'

    start = datetime.datetime(*map(int, start_date.split('-')))
    end = datetime.datetime(*map(int, end_date.split('-')))

    stock_df = yfin.Ticker(stock_symbol + '.NS').history(period='max', interval='1d')[map(str.title, ['open', 'close', 'low', 'high', 'volume'])]

    stock_df['Max'] = round(max(stock_df['Close']),2)
    stock_df = stock_df[(stock_df.index <= end_date) & (stock_df.index >= start_date)]
    stock_df['200_SMA'] = round(stock_df['Close'].rolling(window = 200, min_periods = 1).mean(),0)
    stock_df['Dev%_200'] = round((stock_df['Close'] - stock_df['200_SMA'])*100/stock_df['200_SMA'],2)
    stock_df.dropna(axis = 0, inplace = True) # remove any null rows

    stock_df['20_SMA'] = stock_df['Close'].rolling(window=20).mean()
    stock_df['50_SMA'] = stock_df['Close'].rolling(window=50).mean()
    stock_df['Symbol'] = stock_symbol

    stock_df['Close'] = round(stock_df['Close'],2)
    stock_df['Min'] = round(min(stock_df['Close']),2)
    stock_df['RSI_14'] = ta.momentum.RSIIndicator(close=stock_df['Close'], window=14).rsi()
    stock_df['RSI_14'] = round(stock_df['RSI_14'],0)
    stock_df['Prev_Close'] = stock_df['Close'].shift(1)
    stock_df.drop(['Open', 'Low', 'High', 'Volume'], axis=1, inplace=True)
    stock_df = stock_df.tail(1)

    max_SMA = max(stock_df['20_SMA'].item(), stock_df['50_SMA'].item(), stock_df['200_SMA'].item())
    min_SMA = min(stock_df['20_SMA'].item(), stock_df['50_SMA'].item(), stock_df['200_SMA'].item())
    ABS_Spread = max_SMA - min_SMA
    stock_df['Spread%'] = round((ABS_Spread / stock_df['200_SMA'].item()) * 100,2)

    return stock_df

# function to compute stock attributes
def get_common_features(stock_ids, df_mypf):

  df_prec_dev = pd.DataFrame()
  df_tmp = get_screener_features()
  df_rs = get_relative_strength(stock_ids)

  for stock_id in stock_ids:
      tmp = stock_prec_dev(stock_id)
      tmp = tmp.reset_index()
      df_prec_dev = pd.concat([df_prec_dev, tmp], ignore_index = True)
  df_prec_dev = pd.merge(df_prec_dev, df_mypf, on= 'Symbol')
  df_prec_dev = pd.merge(df_prec_dev, df_tmp, on= 'Symbol', how='left')
  df_prec_dev = pd.merge(df_prec_dev, df_rs, on= 'Symbol', how='left')
  #print(df_prec_dev.columns)
  df_prec_dev['Curr_PE'] = round(df_prec_dev['Close']/df_prec_dev['EPS'],1)
  df_prec_dev['Dev%_PE'] = round((df_prec_dev['Curr_PE'] - df_prec_dev['MedPE'])*100/df_prec_dev['MedPE'],2)
  df_prec_dev['Conviction'] = df_prec_dev['Conviction'] + '-' + df_prec_dev['CapType']
  return df_prec_dev

# function to arrange stock features
def arrange_features(df_stocks, common_cols, diff_cols):
  df_stocks_common = df_stocks[common_cols].drop_duplicates()
  df_stocks_diff = df_stocks[diff_cols]
  df_stocks_diff['Investment'] = df_stocks_diff['AvgCost'] * df_stocks_diff['Shares']
  df_stocks_diff = df_stocks_diff.groupby(['Symbol'])[['Shares', 'Investment']].aggregate(['sum']).reset_index()
  df_stocks_diff.columns = ['Symbol', 'Shares', 'Investment']
  df_stocks_diff['AvgCost'] = round(df_stocks_diff['Investment']/df_stocks_diff['Shares'],2)
  df_stocks = pd.merge(df_stocks_diff, df_stocks_common, on='Symbol')
  return df_stocks

# plot fact distribution across dimension
def plot_pie_chart(df, dimension, fact):
  # grouping the data by category and calculating the sum of fact for each type
  grouped_data = df.groupby(dimension)[fact].sum()

  # sorting the grouped data in descending order
  grouped_data = grouped_data.sort_values(ascending=False)

  # creating a pie chart
  grouped_data.plot.pie(autopct='%1.1f%%', startangle=90, figsize=(6, 6))

  # adding a title and displaying the plot
  plt.title(f'{dimension} {fact} Distribution')
  plt.ylabel('')  # To hide the y-label
  plt.show()

In [7]:
# function to get portfolio features

def get_portfolio_features(df_common_features):

  print_date_time()
  print('-------------------')

  #df_common_features["Target"] = df_common_features["Target"].fillna(df_common_features["Max"])
  df_common_features['NTT'] = np.where(df_common_features['Strategy']== 'NTT', df_common_features["Target"], df_common_features['Max'])
  df_common_features['LTT'] = np.where(df_common_features['Strategy']== 'BTT', df_common_features["Target"], df_common_features['Max'])
  df_common_features['BOL'] = df_common_features['Min']

  tmp_df = df_common_features[df_common_features['Symbol'].isin(mypf_df[mypf_df['InPortfolio'] != 'NA'].Symbol.values)]
  print('qualified stocks: '+str(len(tmp_df['Symbol'].unique())))
  tmp_df1 = tmp_df[tmp_df['LatestQtr'] == 1]
  print('with latest results: '+str(len(tmp_df1['Symbol'].unique())))
  tmp_df1 = tmp_df1[tmp_df1['StarStock'] == 1]
  print('still star stocks: '+str(len(tmp_df1['Symbol'].unique())))
  tmp_df['Investment'] = tmp_df['AvgCost'] * tmp_df['Shares']
  tmp_df['Current'] = round(tmp_df['Close'] * tmp_df['Shares'],0)
  tmp_df['Previous'] = tmp_df['Prev_Close'] * tmp_df['Shares']
  tmp_df['EstimatedST'] = tmp_df['NTT'] * tmp_df['Shares']
  tmp_df['EstimatedLT'] = tmp_df['LTT'] * tmp_df['Shares']
  tmp_df['Current P/L'] = round((tmp_df['Current'] - tmp_df['Investment']),0)
  tmp_df['Today P/L%'] = round((tmp_df['Current'] - tmp_df['Previous'])*100/tmp_df['Previous'],2)
  tmp_df['Current P/L%'] = round((tmp_df['Current'] - tmp_df['Investment'])*100/tmp_df['Investment'],2)
  tmp_df['EstimatedST P/L%'] = round((tmp_df['EstimatedST'] - tmp_df['Investment'])*100/tmp_df['Investment'],2)
  tmp_df['EstimatedLT P/L%'] = round((tmp_df['EstimatedLT'] - tmp_df['Investment'])*100/tmp_df['Investment'],2)
  tmp_df['NTT%'] = round((tmp_df['NTT'] - tmp_df['Close'])*100/tmp_df['Close'],2)
  tmp_df['LTT%'] = round((tmp_df['LTT'] - tmp_df['Close'])*100/tmp_df['Close'],2)
  tmp_df['Gained%'] = round((tmp_df['Close'] - tmp_df['BOL'])*100/tmp_df['BOL'],2)
  investment = round(sum(tmp_df['AvgCost']*tmp_df['Shares']),0)
  current = round(sum(tmp_df['Close']*tmp_df['Shares']),0)
  tmp_df['InitAlloc%'] = round(tmp_df['Investment']*100/investment,2)
  tmp_df['CurrAlloc%'] = round(tmp_df['Current']*100/current,2)
  tmp_df['FTT'] = tmp_df['LTT']
  tmp_df.loc[tmp_df['Strategy'] == 'NTT', 'FTT'] = tmp_df['NTT']
  tmp_df['FTT%'] = tmp_df['LTT%']
  tmp_df.loc[tmp_df['Strategy'] == 'NTT', 'FTT%'] = tmp_df['NTT%']
  tmp_df['FTT Amt'] = round(tmp_df['FTT%'] * tmp_df['Current']/100,0)
  tmp_df['OTT%'] = round((tmp_df['FTT'] - tmp_df['AvgCost'])*100/tmp_df['AvgCost'],2)
  tmp_df['RRR Ind'] = round(tmp_df['Current P/L']/tmp_df['FTT Amt'],2)
  tmp_df['Risk Ind'] = round(tmp_df['Current P/L%']*tmp_df['CurrAlloc%'],0)

  return tmp_df

# function to print portfolio features
def print_portfolio_stats(df_portfolio_features, myinvmt_df):
  from pyxirr import xirr

  total_booked_amt, reserve_amt, cy_booked_amt, py_booked_amt = get_amt()

  dates = myinvmt_df['Date'].values
  dates = np.append(dates, datetime.date.today().strftime('%d-%b-%y'))
  investment = myinvmt_df['Investment'].values
  dates= pd.to_datetime(dates)

  current = round(sum(df_portfolio_features['Close']*df_portfolio_features['Shares']),0) + reserve_amt
  investment_xirr = np.append(investment, current)
  cagr = round(xirr(pd.DataFrame({"dates": dates, "amounts": investment_xirr}))*100,2)

  investment = -sum(investment)
  invested = round(sum(df_portfolio_features['AvgCost']*df_portfolio_features['Shares']),0) + reserve_amt
  previous = round(sum(df_portfolio_features['Prev_Close']*df_portfolio_features['Shares']),0) + reserve_amt
  cy_invested = investment + py_booked_amt

  today_pnl_amount = current-previous
  today_pnl_percentage = round((current-previous)*100/previous,2)

  curr_pnl_amount = current-invested
  curr_pnl_percentage = round((curr_pnl_amount)*100/(cy_invested),2)

  cy_pnl_amount = cy_booked_amt + curr_pnl_amount
  cy_pnl_percentage = round((cy_pnl_amount)*100/cy_invested,2)

  overall_pnl_amount = total_booked_amt + curr_pnl_amount
  overall_pnl_percentage = round((overall_pnl_amount)*100/investment,2)

  estimate_st = round(sum(df_portfolio_features['FTT']*df_portfolio_features['Shares']),0)  + reserve_amt
  est_st_pnl_amount = estimate_st-current
  est_st_pnl_percentage = round((est_st_pnl_amount)*100/current,2)

  estimate_lt = round(sum(df_portfolio_features['LTT']*df_portfolio_features['Shares']),0)  + reserve_amt
  est_lt_pnl_amount = estimate_lt-current
  est_lt_pnl_percentage = round((est_lt_pnl_amount)*100/current,2)

  total_profit = round(sum(df_portfolio_features[df_portfolio_features['Current P/L%'] > 0]['Current']) - sum(df_portfolio_features[df_portfolio_features['Current P/L%'] > 0]['Investment']),0)
  total_loss = round(sum(df_portfolio_features[df_portfolio_features['Current P/L%'] < 0]['Current']) - sum(df_portfolio_features[df_portfolio_features['Current P/L%'] < 0]['Investment']),0)

  cy_booked_percentage = round((cy_booked_amt)*100/current,2)
  py_booked_percentage = round((py_booked_amt)*100/investment,2)
  total_booked_percentage = round((total_booked_amt)*100/investment,2)

  print('-------------------')
  print('Initial Investment: ', format_amt(investment))
  print('CY Investment: ', format_amt(cy_invested))
  print('Reserve: ', format_amt(reserve_amt))
  print('Current: ',  format_amt(current))
  print('-------------------')
  print('Today PnL: '+ '{} ({}%)'.format(format_amt(today_pnl_amount), today_pnl_percentage))
  print('Current PnL: '+ '{} ({}%)'.format(format_amt(curr_pnl_amount), curr_pnl_percentage))
  print('CY Booked + Current PnL: '+ '{} ({}%)'.format(format_amt(cy_pnl_amount), cy_pnl_percentage))
  print('-------------------')
  print('Total profit: ', format_amt(total_profit))
  print('Total loss: ', format_amt(total_loss))
  print('-------------------')
  print('Total Booked + Current PnL: '+ '{} ({}%)'.format(format_amt(overall_pnl_amount), overall_pnl_percentage))
  print('Total Booked PnL: '+ '{} ({}%)'.format(format_amt(total_booked_amt), total_booked_percentage))
  print('Curr Year Booked PnL: '+ '{} ({}%)'.format(format_amt(cy_booked_amt), cy_booked_percentage))
  print('Prev Year Booked PnL: '+ '{} ({}%)'.format(format_amt(py_booked_amt), py_booked_percentage))
  print('===================')
  print('Est FTT: ',  format_amt(estimate_st))
  print('Est FTT PnL: '+ '{} ({}%)'.format(format_amt(est_st_pnl_amount), est_st_pnl_percentage))

  print('===================')
  print('Deployed: ', format_amt(investment))

  print('Current: ', format_amt(current))

  print('CAGR/XIRR %: '+'{}%'.format(cagr))

In [8]:
# get start and end date
start_date, end_date = get_start_end_date()

# get portfolio and prospects data
mypfs_df = get_mypfs_df()
mypps_df = get_mypps_df()
myinvmt_df = get_myinvmt_df()

# merge above datasets
mypf_df = pd.merge(mypfs_df, mypps_df, on="Symbol")

# seggregate dm and sv portfolio
dm_pf = mypf_df[mypf_df['InPortfolio'] == 'DM']
sv_pf = mypf_df[mypf_df['InPortfolio'] == 'SV']

# build portfolio stock dataframe
dm_stocks = get_stock_ids(dm_pf)
sv_stocks = get_stock_ids(sv_pf)
df_stocks = pd.concat([dm_pf,sv_pf], ignore_index = True)

# arrange common and diff stock features
common_cols = ['Symbol', 'Target', 'Criteria', 'Strategy', 'CumlRnk', 'LatestQtr', 'StarStock', 'Conviction', 'Category', 'InFolio', 'XIRR', 'MBQ']
diff_cols = ['Symbol', 'AvgCost', 'Shares']
df_stocks = arrange_features(df_stocks, common_cols, diff_cols)

# get common features
stock_ids = df_stocks['Symbol'].values
df_common_features = get_common_features(stock_ids, df_stocks)

df_common_features.reset_index(drop=True, inplace=True)
df_common_features.drop(['Date'], axis=1, inplace=True)
# get and print portfolio features
df_portfolio_features = get_portfolio_features(df_common_features)

print_portfolio_stats(df_portfolio_features, myinvmt_df)

df = df_portfolio_features
#plot_pie_chart(df, 'CapType', 'Current')
list_ox40n = list(df[df['MBQ'].str.contains('OX40N', na=False)]['Symbol'].values)

Run date time (IST): 2026-04-16 10:21:39
-------------------
qualified stocks: 86
with latest results: 26
still star stocks: 16
-------------------
Initial Investment:  1.36 C
CY Investment:  1.62 C
Reserve:  1.61 K
Current:  1.42 C
-------------------
Today PnL: 52.60 K (0.37%)
Current PnL: -35.48 L (-21.84%)
CY Booked + Current PnL: -19.59 L (-12.06%)
-------------------
Total profit:  1.86 L
Total loss:  -37.35 L
-------------------
Total Booked + Current PnL: 7.39 L (5.45%)
Total Booked PnL: 42.87 L (31.64%)
Curr Year Booked PnL: 15.89 L (11.22%)
Prev Year Booked PnL: 26.98 L (19.91%)
===================
Est FTT:  2.48 C
Est FTT PnL: 1.06 C (75.01%)
===================
Deployed:  1.36 C
Current:  1.42 C
CAGR/XIRR %: 2.14%

In [9]:
# top 5 near their targets
cols = ['Symbol', 'Today P/L%', 'Current P/L%', 'FTT%', 'OTT%', 'FTT Amt', 'Current P/L', 'Current', 'FTT', 'Dev%_PE', 'RSI_14','Conviction', 'Spread%',  'CumlRnk', 'RRR Ind', 'CurrAlloc%', 'Gained%', 'Criteria', 'Strategy', 'Category']
df_tmp = df_portfolio_features[~df_portfolio_features['Symbol'].isin(['ENRIN','BLUSPRING','DIGITIDE'])]
df_tmp = df_tmp.sort_values(by = 'FTT Amt', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
5,ANGELONE,-1.36,20.37,3.17,24.18,11638.0,62125.0,367125.0,303.00,-82.34,73.0,X-SC,1.18,97.0,5.34,2.59,40.45,X40N,NTT,FINANCE
50,MASFIN,1.35,-2.65,24.87,21.57,23722.0,-2595.0,95385.0,397.04,-15.99,58.0,H-SC,4.24,167.0,-0.11,0.67,23.26,XR,ATH,FINANCE
77,TTKPRESTIG,0.59,-37.14,59.22,0.09,37517.0,-37425.0,63352.0,770.00,47.07,51.0,M-SC,23.34,250.0,-1.00,0.45,12.81,OX40N,NTT,DURABLES
67,SONACOMS,-0.51,0.80,37.98,39.09,38729.0,814.0,101973.0,804.02,-20.06,68.0,M-MC,9.00,193.0,0.02,0.72,44.25,AR,ATH,AUTO
37,ICICIGI,1.21,-0.39,19.81,19.34,39486.0,-787.0,199322.0,2252.93,-16.16,63.0,X-MC,7.48,66.0,-0.02,1.41,11.33,X40,ATH,INSURANCE

In [10]:
# top 5 today
df_tmp = df_portfolio_features.sort_values(by = 'Today P/L%', ascending=False)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
55,RAJESHEXPO,5.00,-75.46,307.71,0.07,103600.0,-103509.0,33668.0,518.00,1133.59,64.0,L-SC,43.08,268.0,-1.00,0.24,58.06,OX40N,NTT,JEWELLERY
60,REPCOHOME,4.72,-12.75,117.55,89.82,293853.0,-36524.0,249981.0,880.00,-56.04,63.0,H-SC,6.45,161.0,-0.12,1.77,20.17,XY24,NTT,FINANCE
15,BSOFT,3.36,-28.80,111.76,50.79,111929.0,-40502.0,100151.0,831.70,-8.77,60.0,H-SC,8.16,172.0,-0.36,0.71,18.10,XR,ATH,IT
26,FINCABLES,3.17,15.47,80.06,107.91,136485.0,22835.0,170479.0,1641.55,4.01,63.0,M-SC,1.85,220.0,0.17,1.20,28.26,OX40N,ATH,CABLES
29,GREENPANEL,2.87,-42.09,147.19,43.14,156041.0,-77065.0,106013.0,537.00,137.73,66.0,M-SC,24.03,225.0,-0.49,0.75,27.35,XY24,NTT,MISC

In [11]:
# bottom 5 today
df_tmp = df_portfolio_features.sort_values(by = 'Today P/L%', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
14,BOSCH-HCIL,-1.77,-41.50,70.91,-0.01,53020.0,-53034.0,74771.0,2282.0,15204.35,57.0,M-SC,8.98,231.0,-1.00,0.53,27.27,OX40N,BTT,AC
5,ANGELONE,-1.36,20.37,3.17,24.18,11638.0,62125.0,367125.0,303.0,-82.34,73.0,X-SC,1.18,97.0,5.34,2.59,40.45,X40N,NTT,FINANCE
31,HATHWAY,-1.13,-36.98,174.96,73.29,119883.0,-40200.0,68520.0,31.4,697.10,65.0,H-SC,22.09,171.0,-0.34,0.48,28.75,XR,NTT,ENTERTAINMENT
74,TITAGARH,-1.10,-33.19,118.14,45.74,191151.0,-80377.0,161800.0,1548.0,-10.94,58.0,H-SC,21.17,175.0,-0.42,1.14,23.45,XY24,NTT,ENGINEERING
7,ATULAUTO,-1.00,-19.43,80.67,45.57,128129.0,-38301.0,158831.0,844.0,3435.14,59.0,M-SC,7.52,248.0,-0.30,1.12,22.23,XY24,NTT,AUTO

In [12]:
# top 5 to exit based on CumlRnk
df_tmp = df_portfolio_features[~df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])]
df_tmp = df_tmp[(df_tmp['Current P/L%'] > -1) & (df_tmp['Current P/L%'] < 1)].sort_values(by = 'CumlRnk', ascending=False)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
67,SONACOMS,-0.51,0.80,37.98,39.09,38729.0,814.0,101973.0,804.02,-20.06,68.0,M-MC,9.00,193.0,0.02,0.72,44.25,AR,ATH,AUTO
85,ZYDUSLIFE,0.44,-0.86,36.80,35.63,76460.0,-1801.0,207773.0,1286.17,-13.51,63.0,H-MC,5.73,120.0,-0.02,1.47,15.67,AR,ATH,PHARMA

In [13]:
# OX40N stocks to exit
df_tmp = df_portfolio_features[(df_portfolio_features['Symbol'].isin(list_ox40n))].sort_values(by = 'Current P/L%', ascending=False)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
26,FINCABLES,3.17,15.47,80.06,107.91,136485.0,22835.0,170479.0,1641.55,4.01,63.0,M-SC,1.85,220.0,0.17,1.20,28.26,OX40N,ATH,CABLES
66,SIS,2.86,-24.81,61.27,21.26,51152.0,-27545.0,83487.0,528.00,1968.91,71.0,H-SC,12.67,168.0,-0.54,0.59,24.13,OX40N,NTT,MISC
18,CERA,-0.39,-30.99,79.52,23.89,96534.0,-54507.0,121396.0,9475.00,-33.41,67.0,H-SC,15.36,153.0,-0.56,0.86,16.66,OX40N,NTT,CERAMICS
48,KANSAINER,0.29,-34.30,72.70,13.47,128812.0,-92484.0,177183.0,340.00,-43.52,61.0,H-SC,22.43,162.0,-0.72,1.25,23.76,XY24,NTT,PAINTS
72,TATAELXSI,-0.24,-34.72,102.24,32.03,87992.0,-45771.0,86064.0,9161.00,-18.35,57.0,H-SC,19.91,158.0,-0.52,0.61,13.91,OX40N,NTT,IT

In [14]:
# top 5 to book for rotation
df_tmp = df_portfolio_features[(df_portfolio_features['Current P/L%'] > 20) ].sort_values(by = 'CumlRnk', ascending=False)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
1,ABB,-0.65,25.28,16.20,45.57,53095.0,66125.0,327744.0,7934.0,-19.52,68.0,H-MC,16.37,125.0,1.25,2.31,45.54,AR,NTT,ELECTRICAL
5,ANGELONE,-1.36,20.37,3.17,24.18,11638.0,62125.0,367125.0,303.0,-82.34,73.0,X-SC,1.18,97.0,5.34,2.59,40.45,X40N,NTT,FINANCE

In [15]:
# top 5 to monitor for exit
df_tmp = df_portfolio_features[~df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])]
df_tmp = df_tmp[(df_tmp['Current P/L%'] > 0) ].sort_values(by = 'Dev%_PE', ascending=False)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
26,FINCABLES,3.17,15.47,80.06,107.91,136485.0,22835.0,170479.0,1641.55,4.01,63.0,M-SC,1.85,220.0,0.17,1.20,28.26,OX40N,ATH,CABLES
1,ABB,-0.65,25.28,16.20,45.57,53095.0,66125.0,327744.0,7934.00,-19.52,68.0,H-MC,16.37,125.0,1.25,2.31,45.54,AR,NTT,ELECTRICAL
67,SONACOMS,-0.51,0.80,37.98,39.09,38729.0,814.0,101973.0,804.02,-20.06,68.0,M-MC,9.00,193.0,0.02,0.72,44.25,AR,ATH,AUTO

In [16]:
# top 5 to book for rotation from weak conviction
df_tmp = df_portfolio_features[~df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])]
df_tmp = df_tmp[~df_tmp['Criteria'].isin(['XY25','XY24','X40', 'X40N'])].sort_values(by = 'RRR Ind', ascending=False)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
1,ABB,-0.65,25.28,16.20,45.57,53095.0,66125.0,327744.0,7934.00,-19.52,68.0,H-MC,16.37,125.0,1.25,2.31,45.54,AR,NTT,ELECTRICAL
26,FINCABLES,3.17,15.47,80.06,107.91,136485.0,22835.0,170479.0,1641.55,4.01,63.0,M-SC,1.85,220.0,0.17,1.20,28.26,OX40N,ATH,CABLES
67,SONACOMS,-0.51,0.80,37.98,39.09,38729.0,814.0,101973.0,804.02,-20.06,68.0,M-MC,9.00,193.0,0.02,0.72,44.25,AR,ATH,AUTO
85,ZYDUSLIFE,0.44,-0.86,36.80,35.63,76460.0,-1801.0,207773.0,1286.17,-13.51,63.0,H-MC,5.73,120.0,-0.02,1.47,15.67,AR,ATH,PHARMA
40,INDIAMART,1.05,-7.94,124.55,106.72,141417.0,-9794.0,113542.0,4810.62,-58.40,58.0,H-SC,12.74,140.0,-0.07,0.80,9.08,AR,ATH,MISC

In [17]:
# top 5 to accumulate based on lowest RSI_14
df_tmp = df_portfolio_features[df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])].sort_values(by = 'RSI_14', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
53,PGHH,-0.60,-26.26,79.02,32.01,124415.0,-56072.0,157448.0,17616.87,-50.08,43.0,X-MC,21.64,57.0,-0.45,1.11,7.69,X40,ATH,FMCG
78,UNITDSPR,-0.30,-8.27,31.66,20.77,67998.0,-19368.0,214776.0,1644.00,-18.64,43.0,X-MC,6.42,64.0,-0.28,1.52,2.45,X40N,NTT,BREWERIES
59,RELIANCE,-0.64,-14.27,46.16,25.30,79524.0,-28683.0,172280.0,1952.00,-16.57,44.0,X-LC,5.36,21.0,-0.36,1.22,8.19,XY25,BTT,REFINERIES
21,DABUR,-0.03,-15.32,69.71,43.70,146429.0,-38014.0,210054.0,735.00,-23.16,45.0,X-MC,14.50,70.0,-0.26,1.48,5.52,XY24,BTT,FMCG
2,ABBOTINDIA,0.02,-12.85,35.47,18.07,55291.0,-22975.0,155880.0,35195.00,-25.88,46.0,X-MC,11.65,58.0,-0.42,1.10,1.94,X40,ATH,PHARMA

In [18]:
# top 5 to accumulate based on Spread and CumlRnk
df_tmp = df_portfolio_features[df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])]
df_tmp = df_tmp[(df_tmp['CumlRnk'] < 100)].sort_values(by = 'Spread%', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
5,ANGELONE,-1.36,20.37,3.17,24.18,11638.0,62125.0,367125.0,303.00,-82.34,73.0,X-SC,1.18,97.0,5.34,2.59,40.45,X40N,NTT,FINANCE
65,SIEMENS,-0.66,-4.55,31.50,25.51,55952.0,-8470.0,177625.0,4671.50,49.20,67.0,H-LC,1.51,51.0,-0.15,1.25,26.42,AR,ATH,ELECTRICAL
24,DMART,-0.52,6.97,21.16,29.60,56497.0,17400.0,267000.0,5391.45,-9.79,67.0,X-LC,3.65,14.0,0.31,1.89,22.04,X40N,ATH,FMCG
59,RELIANCE,-0.64,-14.27,46.16,25.30,79524.0,-28683.0,172280.0,1952.00,-16.57,44.0,X-LC,5.36,21.0,-0.36,1.22,8.19,XY25,BTT,REFINERIES
78,UNITDSPR,-0.30,-8.27,31.66,20.77,67998.0,-19368.0,214776.0,1644.00,-18.64,43.0,X-MC,6.42,64.0,-0.28,1.52,2.45,X40N,NTT,BREWERIES

In [19]:
# top 5 to accumulate based on lowest Gained%
df_tmp = df_portfolio_features[df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])].sort_values(by = 'Gained%', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
2,ABBOTINDIA,0.02,-12.85,35.47,18.07,55291.0,-22975.0,155880.0,35195.0,-25.88,46.0,X-MC,11.65,58.0,-0.42,1.10,1.94,X40,ATH,PHARMA
78,UNITDSPR,-0.30,-8.27,31.66,20.77,67998.0,-19368.0,214776.0,1644.0,-18.64,43.0,X-MC,6.42,64.0,-0.28,1.52,2.45,X40N,NTT,BREWERIES
35,HINDUNILVR,-0.47,-16.46,36.07,13.67,77457.0,-42323.0,214740.0,2922.0,-37.95,49.0,X-LC,11.89,9.0,-0.55,1.52,4.64,XY25,NTT,FMCG
45,ITC,0.13,-20.33,49.45,19.06,134007.0,-69171.0,270995.0,452.0,-56.33,50.0,X-LC,19.38,1.0,-0.52,1.91,5.13,X40,NTT,FMCG
21,DABUR,-0.03,-15.32,69.71,43.70,146429.0,-38014.0,210054.0,735.0,-23.16,45.0,X-MC,14.50,70.0,-0.26,1.48,5.52,XY24,BTT,FMCG

In [20]:
# top 5 to accumulate based on lowest CurrAlloc%
df_tmp = df_portfolio_features[df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])].sort_values(by = 'CurrAlloc%', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
58,RELAXO,-0.89,-60.84,288.95,52.31,164245.0,-88318.0,56842.0,1176.00,-58.28,55.0,X-SC,32.94,92.0,-0.54,0.40,27.09,X40N,NTT,FOOTWEAR
12,BATAINDIA,0.26,-52.11,182.33,35.20,112350.0,-67051.0,61619.0,2096.00,-19.28,59.0,X-SC,33.31,91.0,-0.60,0.44,22.21,X40,NTT,FOOTWEAR
54,QUESS,0.45,-19.59,116.26,73.90,99837.0,-20919.0,85874.0,424.00,-57.02,60.0,X-SC,20.87,80.0,-0.21,0.61,15.52,XY24,NTT,MISC
2,ABBOTINDIA,0.02,-12.85,35.47,18.07,55291.0,-22975.0,155880.0,35195.00,-25.88,46.0,X-MC,11.65,58.0,-0.42,1.10,1.94,X40,ATH,PHARMA
36,HONAUT,2.49,-18.95,86.68,51.31,135481.0,-36538.0,156300.0,58357.33,-32.62,65.0,X-SC,18.90,90.0,-0.27,1.10,18.75,X40N,ATH,ELECTRICAL

In [21]:
# top 5 to accumulate based on CumlRnk
df_tmp = df_portfolio_features.sort_values(by = 'CumlRnk', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
45,ITC,0.13,-20.33,49.45,19.06,134007.0,-69171.0,270995.0,452.00,-56.33,50.0,X-LC,19.38,1.0,-0.52,1.91,5.13,X40,NTT,FMCG
73,TCS,0.97,-24.27,67.14,26.57,235553.0,-112434.0,350839.0,4311.59,-35.76,56.0,X-LC,17.31,2.0,-0.48,2.48,9.49,X40,ATH,IT
43,INFY,1.46,-9.84,48.90,34.24,137945.0,-30791.0,282097.0,1972.00,-28.88,53.0,X-LC,13.66,3.0,-0.22,1.99,8.49,X40,NTT,IT
75,TMPV,-0.60,-19.02,68.66,36.58,197849.0,-67683.0,288158.0,600.00,-83.62,62.0,X-LC,11.25,4.0,-0.34,2.03,20.10,XY24,NTT,AUTO
33,HCLTECH,-0.72,-6.49,32.43,23.83,73363.0,-15703.0,226221.0,1908.19,-1.57,56.0,X-LC,8.59,8.0,-0.21,1.60,9.84,X40,ATH,IT

In [22]:
# top 5 for average up
df_tmp = df_portfolio_features[(df_portfolio_features['Dev%_200'] > 5)].sort_values(by = 'CurrAlloc%', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
67,SONACOMS,-0.51,0.80,37.98,39.09,38729.0,814.0,101973.0,804.02,-20.06,68.0,M-MC,9.00,193.0,0.02,0.72,44.25,AR,ATH,AUTO
26,FINCABLES,3.17,15.47,80.06,107.91,136485.0,22835.0,170479.0,1641.55,4.01,63.0,M-SC,1.85,220.0,0.17,1.20,28.26,OX40N,ATH,CABLES
65,SIEMENS,-0.66,-4.55,31.50,25.51,55952.0,-8470.0,177625.0,4671.50,49.20,67.0,H-LC,1.51,51.0,-0.15,1.25,26.42,AR,ATH,ELECTRICAL
11,BANDHANBNK,0.45,-16.03,129.16,92.42,302101.0,-44662.0,233897.0,400.00,100.43,60.0,H-SC,4.98,174.0,-0.15,1.65,28.85,XY24,NTT,BANKS
62,SATIN,0.54,-10.72,70.07,51.83,172834.0,-29625.0,246659.0,274.00,-19.84,66.0,H-SC,1.90,159.0,-0.17,1.74,20.16,XY24,NTT,FINANCE

In [23]:
# top 5 RSP
df_tmp = df_portfolio_features.sort_values(by = 'RSP', ascending=False)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
5,ANGELONE,-1.36,20.37,3.17,24.18,11638.0,62125.0,367125.0,303.00,-82.34,73.0,X-SC,1.18,97.0,5.34,2.59,40.45,X40N,NTT,FINANCE
80,VALIANTORG,1.64,-43.68,209.23,74.15,192785.0,-71465.0,92140.0,838.00,-265.94,62.0,H-SC,20.00,145.0,-0.37,0.65,37.12,XR,NTT,CHEMICALS
52,PAGEIND,0.34,-4.39,40.28,34.11,103352.0,-11794.0,256585.0,51418.64,-31.42,73.0,X-MC,15.74,55.0,-0.11,1.81,21.37,X40,ATH,APPARELS
55,RAJESHEXPO,5.00,-75.46,307.71,0.07,103600.0,-103509.0,33668.0,518.00,1133.59,64.0,L-SC,43.08,268.0,-1.00,0.24,58.06,OX40N,NTT,JEWELLERY
67,SONACOMS,-0.51,0.80,37.98,39.09,38729.0,814.0,101973.0,804.02,-20.06,68.0,M-MC,9.00,193.0,0.02,0.72,44.25,AR,ATH,AUTO

In [24]:
# Top N allocation
df_tmp = df_portfolio_features.sort_values(by = 'CurrAlloc%', ascending=False)
top_n_values = [10, 25, 50]

sum_df = pd.DataFrame({
    'Top_N': top_n_values,
    'Sum_Alloc%': [df_tmp['CurrAlloc%'].head(n).sum() for n in top_n_values]
})

sum_df

   Top_N  Sum_Alloc%
0     10       21.00
1     25       45.74
2     50       77.61

In [25]:
# market-cap-wise allocation
df_tmp = df_portfolio_features[cols]
df_tmp.groupby(df_tmp['Conviction'].str[-2:])['CurrAlloc%'].sum().sort_values(ascending=False)

Conviction
SC    45.38
MC    29.41
LC    25.22
Name: CurrAlloc%, dtype: float64

In [26]:
# criteria-wise allocation
df_portfolio_features.groupby('Criteria')['CurrAlloc%'].sum().sort_values(ascending=False)

Criteria
XY24     27.24
X40      24.66
X40N     15.71
AR        9.32
XR        8.43
XY25      6.98
OX40N     6.88
SR        0.79
Name: CurrAlloc%, dtype: float64

In [27]:
# conviction-wise allocation
df_portfolio_features.groupby('Conviction')['CurrAlloc%'].sum().sort_values(ascending=False)

Conviction
X-LC    22.94
H-SC    22.12
X-MC    21.91
X-SC    12.46
M-SC    10.18
H-MC     5.05
M-MC     2.11
H-LC     1.25
M-LC     1.03
L-SC     0.62
L-MC     0.34
Name: CurrAlloc%, dtype: float64

In [28]:
# sector-wise stats
df_tmp = df_portfolio_features.groupby('Category')[['CurrAlloc%', 'Current', 'Current P/L', 'FTT Amt']].sum().sort_values(by=['Current', 'Current P/L'], ascending=False)
df_tmp['Current P/L%'] = round(df_tmp['Current P/L'] * 100 / df_tmp['Current'], 2)
df_tmp['FTT%'] = round(df_tmp['FTT Amt'] * 100 / df_tmp['Current'], 2)
cols = ['CurrAlloc%', 'Current P/L%', 'FTT%']
df_tmp[cols].sort_values(by=['CurrAlloc%'], ascending=False)

               CurrAlloc%  Current P/L%    FTT%
Category
FMCG                14.56        -21.16   64.15
FINANCE             13.54        -12.06   57.73
IT                  11.74        -35.52  104.49
MISC                 7.18        -31.91   89.22
ELECTRICAL           6.56         -4.01   43.84
PAINTS               5.31        -31.04   53.79
BANKS                4.62        -17.61   77.31
INSURANCE            4.59         -4.35   40.06
PHARMA               3.93         -5.61   38.86
AUTO                 3.87        -19.16   66.44
AC                   2.00        -12.73   43.29
HEALTHCARE           1.93        -31.11   65.33
FOOTWEAR             1.84        -69.76  137.83
TRAVEL               1.82        -73.20  159.92
APPARELS             1.81         -4.60   40.28
DURABLES             1.75        -56.38   94.42
BREWERIES            1.52         -9.02   31.66
REALTY               1.46         -7.60   25.27
CERAMICS             1.36        -59.63  108.13
REFINERIES           1.22        -16.65   46.16
CEMENT               1.22        -55.75  172.27
CABLES               1.20         13.39   80.06
ENGINEERING          1.14        -49.68  118.14
JEWELLERY            1.12       -101.93  172.08
CHEMICALS            1.08        -73.66  215.35
ENTERTAINMENT        0.81        -68.64  169.23
TEXTILES             0.45        -44.66   85.90
HOTELS               0.38       -111.82  186.53

In [29]:
# money to be made criteria-wise
df_portfolio_features.groupby('Criteria')['FTT Amt'].agg(['sum', 'count']).sort_values(by='sum', ascending=False)

                sum  count
Criteria
XY24      3738857.0     21
X40       1681622.0     16
XR        1296883.0     12
AR        1250900.0     10
X40N      1075410.0     10
OX40N      820069.0     10
XY25       452099.0      5
SR         307997.0      2

In [30]:
# money to be made conviction-wise
df_portfolio_features.groupby('Conviction')['FTT Amt'].agg(['sum', 'count']).sort_values(by='sum', ascending=False)

                  sum  count
Conviction
H-SC        3659583.0     24
X-MC        1630065.0     15
X-LC        1527691.0     13
M-SC        1477794.0     14
X-SC        1418799.0     10
H-MC         363128.0      3
L-SC         203591.0      2
M-LC         146605.0      1
M-MC          86459.0      2
H-LC          55952.0      1
L-MC          54170.0      1

In [31]:
# money to be made criteria and conviction-wise
df_portfolio_features.groupby(['Conviction', 'Criteria'])['FTT Amt'].agg(['sum', 'count']).sort_values(by='sum', ascending=False)

                           sum  count
Conviction Criteria
H-SC       XY24      1236009.0      6
           AR         952695.0      5
M-SC       XY24       854121.0      6
X-LC       X40        831979.0      7
X-SC       XY24       829520.0      4
H-SC       XR         810148.0      7
X-MC       X40        644388.0      7
           X40N       493322.0      4
X-SC       X40N       384024.0      4
M-SC       OX40N      363735.0      5
H-SC       OX40N      352734.0      4
X-LC       XY24       340667.0      2
H-SC       SR         307997.0      2
X-MC       XY25       247388.0      2
           XY24       244967.0      2
H-MC       XY24       233573.0      1
X-SC       X40        205255.0      2
X-LC       X40N       198064.0      2
M-SC       XR         185969.0      2
X-LC       XY25       156981.0      2
M-LC       XR         146605.0      1
H-MC       AR         129555.0      2
L-SC       OX40N      103600.0      1
           XR          99991.0      1
M-SC       AR          73969.0      1
H-LC       AR          55952.0      1
L-MC       XR          54170.0      1
M-MC       XY25        47730.0      1
           AR          38729.0      1

In [32]:
# notebook execution time

end_time = time.time()
execution_time = round(end_time - start_time, 0)
print(f"Notebook execution time: {execution_time} seconds")

Notebook execution time: 26.0 seconds