<a href="https://colab.research.google.com/github/ankit-rathi/Quantvesting_v2/blob/main/myStocks_Portfolio_Analysis.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
'''
!pip install pandas==2.2.2 -qq
!pip install pyxirr -qq
!pip install ta -qq
!pip install yfinance==0.2.59 -qq
'''

'\n!pip install pandas==2.2.2 -qq\n!pip install pyxirr -qq\n!pip install ta -qq\n!pip install yfinance==0.2.59 -qq\n'

In [2]:
# import libraries

import numpy as np
import pandas as pd
import datetime
import warnings
warnings.filterwarnings('ignore')
import yfinance as yfin
import ta
import matplotlib.pyplot as plt
import requests

In [3]:
# notebook start time
import time
import datetime
import pytz

start_time = time.time()

# function to print date timestamp
def print_date_time():
  tz_NY = pytz.timezone('Asia/Kolkata')
  datetime_NY = datetime.datetime.now(tz_NY)
  print("Run date time (IST):", datetime_NY.strftime("%Y-%m-%d %H:%M:%S"))

In [4]:
# function to get booked and reserved amount
def get_amt():
  # fetch the JSON data from the URL
  url = "https://raw.githubusercontent.com/ankit-rathi/Tradevesting_v1/main/data/myPortfolioAmts.json"
  response = requests.get(url)
  pf_amts = response.json()  # parse the JSON data

  # extract values from the JSON
  py_booked_amt_dm = pf_amts["py_booked_amt_dm"]
  py_booked_amt_sv = pf_amts["py_booked_amt_sv"]
  cy_booked_amt_dm = pf_amts["cy_booked_amt_dm"]
  cy_booked_amt_sv = pf_amts["cy_booked_amt_sv"]
  reserve_amt_dm = pf_amts["reserve_amt_dm"]
  reserve_amt_sv = pf_amts["reserve_amt_sv"]

  # perform calculations
  py_booked_amt = py_booked_amt_dm + py_booked_amt_sv
  cy_booked_amt = cy_booked_amt_dm + cy_booked_amt_sv
  reserve_amt = reserve_amt_dm + reserve_amt_sv
  total_booked_amt = py_booked_amt + cy_booked_amt

  return total_booked_amt, reserve_amt, cy_booked_amt, py_booked_amt

gen_output = 0

In [5]:
# function to format the amount
def format_amt(number):
    abs_number = abs(number)

    if abs_number >= 1_00_00_000:  # Crores
        formatted_amt = f"{number / 1_00_00_000:.2f} C"
    elif abs_number >= 1_00_000:  # Lakhs
        formatted_amt = f"{number / 1_00_000:.2f} L"
    elif abs_number >= 1_000:  # Thousands
        formatted_amt = f"{number / 1_000:.2f} K"
    else:
        formatted_amt = f"{number:.2f}"

    return formatted_amt

# function to set start and end date
def get_start_end_date():
  start_date = (datetime.date.today() + datetime.timedelta(days=-365)).strftime('%Y-%m-%d')
  end_date = (datetime.date.today() + datetime.timedelta(days=1)).strftime('%Y-%m-%d')
  return start_date, end_date

# function to fetch my portfolio csv
def get_mypfs_df():
  mypfs_df = pd.read_csv('https://raw.githubusercontent.com/ankit-rathi/Tradevesting_v1/main/data/myPortfolioStocks.csv')
  return mypfs_df

# function to fetch my prospects csv
def get_mypps_df():
  mypps_df = pd.read_csv('https://raw.githubusercontent.com/ankit-rathi/Tradevesting_v1/main/data/myProspectsScrips.csv')
  return mypps_df

# function to fetch screener data
def get_myscreen_df():
  myscreen_df = pd.read_csv('https://raw.githubusercontent.com/ankit-rathi/Tradevesting_v1/main/data/myScreenerDB.csv')
  return myscreen_df

# function to fetch momentum data
def get_myinvmt_df():
  myinvmt_df = pd.read_csv('https://raw.githubusercontent.com/ankit-rathi/Tradevesting_v1/main/data/myInvestments.csv')
  return myinvmt_df

# function to get the stock ids
def get_stock_ids(df_pf):
  stock_n100 = df_pf['Symbol'].unique()

  exclude = ['CADILAHC','MMTC', 'MASFIN']

  stock_ids = df_pf[~df_pf['Symbol'].isin(exclude) ]['Symbol'].unique()

  #mypf = mypf[mypf.Forecast.notnull()]
  #stock_ids = mypf['Symbol'].unique()

  #stock_ids.sort()
  return stock_ids

# get features from screener data
def get_screener_features():
  myscreen_df = get_myscreen_df()
  cols = ['Symbol', 'EPS', 'MedPE', 'ROCE%', 'ROE%', 'CapType']
  return myscreen_df[cols]

# get relative strength
def get_relative_strength(stock_list):

    # Dictionary to store stock tickers and their corresponding percentage price change
    stock_changes = {}

    # Loop through each stock and fetch its price data
    for stock in stock_list:
        try:
            # Download the stock data for the given date range
            stock_data = yfin.Ticker(stock + '.NS').history(period='1mo', interval='1d')[map(str.title, ['open', 'close', 'low', 'high', 'volume'])]

            # Calculate the percentage change for the stock
            if len(stock_data) > 0:
                start_price = stock_data['Close'].iloc[0]
                end_price = stock_data['Close'].iloc[-1]
                percent_change = round(((end_price - start_price) / start_price) * 100, 2)
                stock_changes[stock] = percent_change
            else:
                stock_changes[stock] = np.nan  # If no data is available, set to NaN

        except Exception as e:
            print(f"Error fetching data for {stock}: {e}")
            stock_changes[stock] = np.nan

    # Create a DataFrame with stock tickers and their percentage changes
    df = pd.DataFrame(list(stock_changes.items()), columns=['Symbol', 'Percent_Change'])

    # Drop any stocks with missing data (NaN values)
    df = df.dropna()

    # Calculate the percentile rank based on percentage change
    df['RSP'] = round(df['Percent_Change'].rank(pct=True) * 100, 2)
    cols = ['Symbol', 'RSP']
    df = df[cols]
    # Sort by percentile rank (optional)
    df = df.sort_values(by='RSP', ascending=False).reset_index(drop=True)

    return df

In [6]:
# function to get stock technicals
def stock_prec_dev(stock_symbol):
    #stock_symbol = 'ULTRACEMCO.NS'
    short_window = 20
    mid_window = 50
    long_window = 200
    moving_avg = 'SMA'

    start = datetime.datetime(*map(int, start_date.split('-')))
    end = datetime.datetime(*map(int, end_date.split('-')))

    stock_df = yfin.Ticker(stock_symbol + '.NS').history(period='max', interval='1d')[map(str.title, ['open', 'close', 'low', 'high', 'volume'])]

    stock_df['Max'] = round(max(stock_df['Close']),2)
    stock_df = stock_df[(stock_df.index <= end_date) & (stock_df.index >= start_date)]
    stock_df['200_SMA'] = round(stock_df['Close'].rolling(window = 200, min_periods = 1).mean(),0)
    stock_df['Dev%_200'] = round((stock_df['Close'] - stock_df['200_SMA'])*100/stock_df['200_SMA'],2)
    stock_df.dropna(axis = 0, inplace = True) # remove any null rows

    stock_df['20_SMA'] = stock_df['Close'].rolling(window=20).mean()
    stock_df['50_SMA'] = stock_df['Close'].rolling(window=50).mean()
    stock_df['Symbol'] = stock_symbol

    stock_df['Close'] = round(stock_df['Close'],2)
    stock_df['Min'] = round(min(stock_df['Close']),2)
    stock_df['RSI_14'] = ta.momentum.RSIIndicator(close=stock_df['Close'], window=14).rsi()
    stock_df['RSI_14'] = round(stock_df['RSI_14'],0)
    stock_df['Prev_Close'] = stock_df['Close'].shift(1)
    stock_df.drop(['Open', 'Low', 'High', 'Volume'], axis=1, inplace=True)
    stock_df = stock_df.tail(1)

    max_SMA = max(stock_df['20_SMA'].item(), stock_df['50_SMA'].item(), stock_df['200_SMA'].item())
    min_SMA = min(stock_df['20_SMA'].item(), stock_df['50_SMA'].item(), stock_df['200_SMA'].item())
    ABS_Spread = max_SMA - min_SMA
    stock_df['Spread%'] = round((ABS_Spread / stock_df['200_SMA'].item()) * 100,2)

    return stock_df

# function to compute stock attributes
def get_common_features(stock_ids, df_mypf):

  df_prec_dev = pd.DataFrame()
  df_tmp = get_screener_features()
  df_rs = get_relative_strength(stock_ids)

  for stock_id in stock_ids:
      tmp = stock_prec_dev(stock_id)
      tmp = tmp.reset_index()
      df_prec_dev = pd.concat([df_prec_dev, tmp], ignore_index = True)
  df_prec_dev = pd.merge(df_prec_dev, df_mypf, on= 'Symbol')
  df_prec_dev = pd.merge(df_prec_dev, df_tmp, on= 'Symbol', how='left')
  df_prec_dev = pd.merge(df_prec_dev, df_rs, on= 'Symbol', how='left')
  #print(df_prec_dev.columns)
  df_prec_dev['Curr_PE'] = round(df_prec_dev['Close']/df_prec_dev['EPS'],1)
  df_prec_dev['Dev%_PE'] = round((df_prec_dev['Curr_PE'] - df_prec_dev['MedPE'])*100/df_prec_dev['MedPE'],2)
  df_prec_dev['Conviction'] = df_prec_dev['Conviction'] + '-' + df_prec_dev['CapType']
  return df_prec_dev

# function to arrange stock features
def arrange_features(df_stocks, common_cols, diff_cols):
  df_stocks_common = df_stocks[common_cols].drop_duplicates()
  df_stocks_diff = df_stocks[diff_cols]
  df_stocks_diff['Investment'] = df_stocks_diff['AvgCost'] * df_stocks_diff['Shares']
  df_stocks_diff = df_stocks_diff.groupby(['Symbol'])[['Shares', 'Investment']].aggregate(['sum']).reset_index()
  df_stocks_diff.columns = ['Symbol', 'Shares', 'Investment']
  df_stocks_diff['AvgCost'] = round(df_stocks_diff['Investment']/df_stocks_diff['Shares'],2)
  df_stocks = pd.merge(df_stocks_diff, df_stocks_common, on='Symbol')
  return df_stocks

# plot fact distribution across dimension
def plot_pie_chart(df, dimension, fact):
  # grouping the data by category and calculating the sum of fact for each type
  grouped_data = df.groupby(dimension)[fact].sum()

  # sorting the grouped data in descending order
  grouped_data = grouped_data.sort_values(ascending=False)

  # creating a pie chart
  grouped_data.plot.pie(autopct='%1.1f%%', startangle=90, figsize=(6, 6))

  # adding a title and displaying the plot
  plt.title(f'{dimension} {fact} Distribution')
  plt.ylabel('')  # To hide the y-label
  plt.show()

In [7]:
# function to get portfolio features

def get_portfolio_features(df_common_features):

  print_date_time()
  print('-------------------')

  #df_common_features["Target"] = df_common_features["Target"].fillna(df_common_features["Max"])
  df_common_features['NTT'] = np.where(df_common_features['Strategy']== 'NTT', df_common_features["Target"], df_common_features['Max'])
  df_common_features['LTT'] = np.where(df_common_features['Strategy']== 'BTT', df_common_features["Target"], df_common_features['Max'])
  df_common_features['BOL'] = df_common_features['Min']

  tmp_df = df_common_features[df_common_features['Symbol'].isin(mypf_df[mypf_df['InPortfolio'] != 'NA'].Symbol.values)]
  print('qualified stocks: '+str(len(tmp_df['Symbol'].unique())))
  tmp_df1 = tmp_df[tmp_df['LatestQtr'] == 1]
  print('with latest results: '+str(len(tmp_df1['Symbol'].unique())))
  tmp_df1 = tmp_df1[tmp_df1['StarStock'] == 1]
  print('still star stocks: '+str(len(tmp_df1['Symbol'].unique())))
  tmp_df['Investment'] = tmp_df['AvgCost'] * tmp_df['Shares']
  tmp_df['Current'] = round(tmp_df['Close'] * tmp_df['Shares'],0)
  tmp_df['Previous'] = tmp_df['Prev_Close'] * tmp_df['Shares']
  tmp_df['EstimatedST'] = tmp_df['NTT'] * tmp_df['Shares']
  tmp_df['EstimatedLT'] = tmp_df['LTT'] * tmp_df['Shares']
  tmp_df['Current P/L'] = round((tmp_df['Current'] - tmp_df['Investment']),0)
  tmp_df['Today P/L%'] = round((tmp_df['Current'] - tmp_df['Previous'])*100/tmp_df['Previous'],2)
  tmp_df['Current P/L%'] = round((tmp_df['Current'] - tmp_df['Investment'])*100/tmp_df['Investment'],2)
  tmp_df['EstimatedST P/L%'] = round((tmp_df['EstimatedST'] - tmp_df['Investment'])*100/tmp_df['Investment'],2)
  tmp_df['EstimatedLT P/L%'] = round((tmp_df['EstimatedLT'] - tmp_df['Investment'])*100/tmp_df['Investment'],2)
  tmp_df['NTT%'] = round((tmp_df['NTT'] - tmp_df['Close'])*100/tmp_df['Close'],2)
  tmp_df['LTT%'] = round((tmp_df['LTT'] - tmp_df['Close'])*100/tmp_df['Close'],2)
  tmp_df['Gained%'] = round((tmp_df['Close'] - tmp_df['BOL'])*100/tmp_df['BOL'],2)
  investment = round(sum(tmp_df['AvgCost']*tmp_df['Shares']),0)
  current = round(sum(tmp_df['Close']*tmp_df['Shares']),0)
  tmp_df['InitAlloc%'] = round(tmp_df['Investment']*100/investment,2)
  tmp_df['CurrAlloc%'] = round(tmp_df['Current']*100/current,2)
  tmp_df['FTT'] = tmp_df['LTT']
  tmp_df.loc[tmp_df['Strategy'] == 'NTT', 'FTT'] = tmp_df['NTT']
  tmp_df['FTT%'] = tmp_df['LTT%']
  tmp_df.loc[tmp_df['Strategy'] == 'NTT', 'FTT%'] = tmp_df['NTT%']
  tmp_df['FTT Amt'] = round(tmp_df['FTT%'] * tmp_df['Current']/100,0)
  tmp_df['OTT%'] = round((tmp_df['FTT'] - tmp_df['AvgCost'])*100/tmp_df['AvgCost'],2)
  tmp_df['RRR Ind'] = round(tmp_df['Current P/L']/tmp_df['FTT Amt'],2)
  tmp_df['Risk Ind'] = round(tmp_df['Current P/L%']*tmp_df['CurrAlloc%'],0)

  return tmp_df

# function to print portfolio features
def print_portfolio_stats(df_portfolio_features, myinvmt_df):
  from pyxirr import xirr

  total_booked_amt, reserve_amt, cy_booked_amt, py_booked_amt = get_amt()

  dates = myinvmt_df['Date'].values
  dates = np.append(dates, datetime.date.today().strftime('%d-%b-%y'))
  investment = myinvmt_df['Investment'].values
  dates= pd.to_datetime(dates)

  current = round(sum(df_portfolio_features['Close']*df_portfolio_features['Shares']),0) + reserve_amt
  investment_xirr = np.append(investment, current)
  cagr = round(xirr(pd.DataFrame({"dates": dates, "amounts": investment_xirr}))*100,2)

  investment = -sum(investment)
  invested = round(sum(df_portfolio_features['AvgCost']*df_portfolio_features['Shares']),0) + reserve_amt
  previous = round(sum(df_portfolio_features['Prev_Close']*df_portfolio_features['Shares']),0) + reserve_amt
  cy_invested = investment + py_booked_amt

  today_pnl_amount = current-previous
  today_pnl_percentage = round((current-previous)*100/previous,2)

  curr_pnl_amount = current-invested
  curr_pnl_percentage = round((curr_pnl_amount)*100/(cy_invested),2)

  cy_pnl_amount = cy_booked_amt + curr_pnl_amount
  cy_pnl_percentage = round((cy_pnl_amount)*100/cy_invested,2)

  overall_pnl_amount = total_booked_amt + curr_pnl_amount
  overall_pnl_percentage = round((overall_pnl_amount)*100/investment,2)

  estimate_st = round(sum(df_portfolio_features['FTT']*df_portfolio_features['Shares']),0)  + reserve_amt
  est_st_pnl_amount = estimate_st-current
  est_st_pnl_percentage = round((est_st_pnl_amount)*100/current,2)

  estimate_lt = round(sum(df_portfolio_features['LTT']*df_portfolio_features['Shares']),0)  + reserve_amt
  est_lt_pnl_amount = estimate_lt-current
  est_lt_pnl_percentage = round((est_lt_pnl_amount)*100/current,2)

  total_profit = round(sum(df_portfolio_features[df_portfolio_features['Current P/L%'] > 0]['Current']) - sum(df_portfolio_features[df_portfolio_features['Current P/L%'] > 0]['Investment']),0)
  total_loss = round(sum(df_portfolio_features[df_portfolio_features['Current P/L%'] < 0]['Current']) - sum(df_portfolio_features[df_portfolio_features['Current P/L%'] < 0]['Investment']),0)

  cy_booked_percentage = round((cy_booked_amt)*100/current,2)
  py_booked_percentage = round((py_booked_amt)*100/investment,2)
  total_booked_percentage = round((total_booked_amt)*100/investment,2)

  print('-------------------')
  print('Initial Investment: ', format_amt(investment))
  print('CY Investment: ', format_amt(cy_invested))
  print('Reserve: ', format_amt(reserve_amt))
  print('Current: ',  format_amt(current))
  print('-------------------')
  print('Today PnL: '+ '{} ({}%)'.format(format_amt(today_pnl_amount), today_pnl_percentage))
  print('Current PnL: '+ '{} ({}%)'.format(format_amt(curr_pnl_amount), curr_pnl_percentage))
  print('CY Booked + Current PnL: '+ '{} ({}%)'.format(format_amt(cy_pnl_amount), cy_pnl_percentage))
  print('-------------------')
  print('Total profit: ', format_amt(total_profit))
  print('Total loss: ', format_amt(total_loss))
  print('-------------------')
  print('Total Booked + Current PnL: '+ '{} ({}%)'.format(format_amt(overall_pnl_amount), overall_pnl_percentage))
  print('Total Booked PnL: '+ '{} ({}%)'.format(format_amt(total_booked_amt), total_booked_percentage))
  print('Curr Year Booked PnL: '+ '{} ({}%)'.format(format_amt(cy_booked_amt), cy_booked_percentage))
  print('Prev Year Booked PnL: '+ '{} ({}%)'.format(format_amt(py_booked_amt), py_booked_percentage))
  print('===================')
  print('Est FTT: ',  format_amt(estimate_st))
  print('Est FTT PnL: '+ '{} ({}%)'.format(format_amt(est_st_pnl_amount), est_st_pnl_percentage))

  print('===================')
  print('Deployed: ', format_amt(investment))

  print('Current: ', format_amt(current))

  print('CAGR/XIRR %: '+'{}%'.format(cagr))

In [8]:
# get start and end date
start_date, end_date = get_start_end_date()

# get portfolio and prospects data
mypfs_df = get_mypfs_df()
mypps_df = get_mypps_df()
myinvmt_df = get_myinvmt_df()

# merge above datasets
mypf_df = pd.merge(mypfs_df, mypps_df, on="Symbol")

# seggregate dm and sv portfolio
dm_pf = mypf_df[mypf_df['InPortfolio'] == 'DM']
sv_pf = mypf_df[mypf_df['InPortfolio'] == 'SV']

# build portfolio stock dataframe
dm_stocks = get_stock_ids(dm_pf)
sv_stocks = get_stock_ids(sv_pf)
df_stocks = pd.concat([dm_pf,sv_pf], ignore_index = True)

# arrange common and diff stock features
common_cols = ['Symbol', 'Target', 'Criteria', 'Strategy', 'CumlRnk', 'LatestQtr', 'StarStock', 'Conviction', 'Category', 'InFolio', 'XIRR', 'MBQ']
diff_cols = ['Symbol', 'AvgCost', 'Shares']
df_stocks = arrange_features(df_stocks, common_cols, diff_cols)

# get common features
stock_ids = df_stocks['Symbol'].values
df_common_features = get_common_features(stock_ids, df_stocks)

df_common_features.reset_index(drop=True, inplace=True)
df_common_features.drop(['Date'], axis=1, inplace=True)
# get and print portfolio features
df_portfolio_features = get_portfolio_features(df_common_features)

print_portfolio_stats(df_portfolio_features, myinvmt_df)

df = df_portfolio_features
#plot_pie_chart(df, 'CapType', 'Current')
list_ox40n = list(df[df['MBQ'].str.contains('OX40N', na=False)]['Symbol'].values)

Run date time (IST): 2026-04-21 10:18:46
-------------------
qualified stocks: 85
with latest results: 25
still star stocks: 15

-------------------
Initial Investment:  1.36 C
CY Investment:  1.78 C
Reserve:  1.61 K
Current:  1.41 C
-------------------
Today PnL: 1.34 L (0.96%)
Current PnL: -32.96 L (-18.48%)
CY Booked + Current PnL: -32.00 L (-17.94%)
-------------------
Total profit:  1.84 L
Total loss:  -34.80 L
-------------------
Total Booked + Current PnL: 10.87 L (8.02%)
Total Booked PnL: 43.83 L (32.35%)
Curr Year Booked PnL: 96.00 K (0.68%)
Prev Year Booked PnL: 42.87 L (31.64%)
===================
Est FTT:  2.44 C
Est FTT PnL: 1.03 C (72.98%)
===================
Deployed:  1.36 C
Current:  1.41 C
CAGR/XIRR %: 1.94%

In [9]:
# top 5 near their targets
cols = ['Symbol', 'Today P/L%', 'Current P/L%', 'FTT%', 'OTT%', 'FTT Amt', 'Current P/L', 'Current', 'FTT', 'Dev%_PE', 'RSI_14','Conviction', 'Spread%',  'CumlRnk', 'RRR Ind', 'CurrAlloc%', 'Gained%', 'Criteria', 'Strategy', 'Category']
df_tmp = df_portfolio_features[~df_portfolio_features['Symbol'].isin(['ENRIN','BLUSPRING','DIGITIDE'])]
df_tmp = df_tmp.sort_values(by = 'FTT Amt', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
49,MASFIN,0.83,-2.79,25.05,21.57,23860.0,-2730.0,95250.0,397.04,-15.99,57.0,H-SC,3.29,167.0,-0.11,0.68,23.09,XR,ATH,FINANCE
1,ABB,1.54,33.35,9.16,45.57,31956.0,87245.0,348864.0,7934.00,-14.32,77.0,H-MC,18.42,125.0,2.73,2.47,54.92,AR,NTT,ELECTRICAL
76,TTKPRESTIG,1.32,-34.86,53.65,0.09,35222.0,-35126.0,65651.0,770.00,52.40,56.0,M-SC,22.93,250.0,-1.00,0.47,16.90,OX40N,NTT,DURABLES
56,RECLTD,-0.31,3.28,16.91,20.74,35481.0,6655.0,209825.0,446.00,13.28,70.0,M-MC,4.85,191.0,0.19,1.49,25.04,XY25,NTT,FINANCE
66,SONACOMS,0.66,0.40,38.54,39.09,39142.0,402.0,101561.0,804.02,-20.47,64.0,M-MC,10.46,193.0,0.01,0.72,43.67,AR,ATH,AUTO

In [10]:
# top 5 today
df_tmp = df_portfolio_features.sort_values(by = 'Today P/L%', ascending=False)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
80,VBL,3.91,-2.07,38.37,35.50,118679.0,-6540.0,309302.0,670.8,-13.53,71.0,X-LC,9.77,13.0,-0.06,2.19,27.00,X40N,ATH,FMCG
14,BSOFT,3.42,-28.45,110.74,50.79,111444.0,-40017.0,100636.0,831.7,-8.39,60.0,H-SC,6.82,172.0,-0.36,0.71,18.67,XR,ATH,IT
59,REPCOHOME,3.06,-10.27,111.54,89.82,286756.0,-29417.0,257088.0,880.0,-55.29,67.0,H-SC,4.60,161.0,-0.10,1.82,23.59,XY24,NTT,FINANCE
40,INDIGOPNTS,2.88,-38.91,63.73,0.02,67958.0,-67925.0,106634.0,1408.0,62.39,59.0,M-SC,27.64,222.0,-1.00,0.76,20.98,OX40N,NTT,PAINTS
78,VAIBHAVGBL,2.70,-30.31,130.67,60.77,166454.0,-55390.0,127385.0,521.0,47.11,60.0,H-SC,10.78,160.0,-0.33,0.90,28.80,XR,NTT,JEWELLERY

In [11]:
# bottom 5 today
df_tmp = df_portfolio_features.sort_values(by = 'Today P/L%', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
54,RAJESHEXPO,-4.06,-77.28,340.40,0.07,106099.0,-106008.0,31169.0,518.00,1042.68,54.0,L-SC,41.15,268.0,-1.00,0.22,46.33,OX40N,NTT,JEWELLERY
37,ICICIPRULI,-2.87,-10.33,45.78,30.73,80874.0,-20346.0,176659.0,790.00,-34.44,42.0,X-MC,13.01,78.0,-0.25,1.25,7.65,X40,ATH,INSURANCE
36,ICICIGI,-1.06,-1.65,21.35,19.34,42017.0,-3309.0,196800.0,2252.93,-17.38,57.0,X-MC,7.09,66.0,-0.08,1.39,9.92,X40,ATH,INSURANCE
84,ZYDUSLIFE,-0.61,-1.85,38.19,35.63,78555.0,-3878.0,205696.0,1286.17,-14.41,59.0,H-MC,4.92,120.0,-0.05,1.46,11.36,AR,ATH,PHARMA
45,JIOFIN,-0.60,-21.78,64.18,28.43,149772.0,-64964.0,233363.0,387.00,-22.96,46.0,X-LC,18.71,34.0,-0.43,1.65,5.19,XY24,BTT,FINANCE

In [12]:
# top 5 to exit based on CumlRnk
df_tmp = df_portfolio_features[~df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])]
df_tmp = df_tmp[(df_tmp['Current P/L%'] > -1) & (df_tmp['Current P/L%'] < 1)].sort_values(by = 'CumlRnk', ascending=False)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
66,SONACOMS,0.66,0.4,38.54,39.09,39142.0,402.0,101561.0,804.02,-20.47,64.0,M-MC,10.46,193.0,0.01,0.72,43.67,AR,ATH,AUTO

In [13]:
# OX40N stocks to exit
df_tmp = df_portfolio_features[(df_portfolio_features['Symbol'].isin(list_ox40n))].sort_values(by = 'Current P/L%', ascending=False)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
25,FINCABLES,2.43,22.80,69.31,107.91,125663.0,33662.0,181306.0,1641.55,10.60,70.0,M-SC,3.55,220.0,0.27,1.29,36.40,OX40N,ATH,CABLES
65,SIS,1.95,-23.59,58.70,21.26,49800.0,-26194.0,84838.0,528.00,2002.07,74.0,H-SC,10.20,168.0,-0.53,0.60,26.14,OX40N,NTT,MISC
17,CERA,0.98,-29.94,76.82,23.89,94678.0,-52657.0,123246.0,9475.00,-32.46,68.0,H-SC,13.47,153.0,-0.56,0.87,18.44,OX40N,NTT,CERAMICS
47,KANSAINER,1.05,-31.18,64.88,13.47,120410.0,-84078.0,185589.0,340.00,-40.82,67.0,H-SC,20.11,162.0,-0.70,1.32,29.63,XY24,NTT,PAINTS
71,TATAELXSI,1.28,-34.08,100.28,32.03,87153.0,-44925.0,86910.0,9161.00,-17.51,58.0,H-SC,18.37,158.0,-0.52,0.62,15.03,OX40N,NTT,IT

In [14]:
# top 5 to book for rotation
df_tmp = df_portfolio_features[(df_portfolio_features['Current P/L%'] > 20) ].sort_values(by = 'CumlRnk', ascending=False)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
25,FINCABLES,2.43,22.80,69.31,107.91,125663.0,33662.0,181306.0,1641.55,10.60,70.0,M-SC,3.55,220.0,0.27,1.29,36.40,OX40N,ATH,CABLES
1,ABB,1.54,33.35,9.16,45.57,31956.0,87245.0,348864.0,7934.00,-14.32,77.0,H-MC,18.42,125.0,2.73,2.47,54.92,AR,NTT,ELECTRICAL

In [15]:
# top 5 to monitor for exit
df_tmp = df_portfolio_features[~df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])]
df_tmp = df_tmp[(df_tmp['Current P/L%'] > 0) ].sort_values(by = 'Dev%_PE', ascending=False)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
56,RECLTD,-0.31,3.28,16.91,20.74,35481.0,6655.0,209825.0,446.00,13.28,70.0,M-MC,4.85,191.0,0.19,1.49,25.04,XY25,NTT,FINANCE
25,FINCABLES,2.43,22.80,69.31,107.91,125663.0,33662.0,181306.0,1641.55,10.60,70.0,M-SC,3.55,220.0,0.27,1.29,36.40,OX40N,ATH,CABLES
1,ABB,1.54,33.35,9.16,45.57,31956.0,87245.0,348864.0,7934.00,-14.32,77.0,H-MC,18.42,125.0,2.73,2.47,54.92,AR,NTT,ELECTRICAL
66,SONACOMS,0.66,0.40,38.54,39.09,39142.0,402.0,101561.0,804.02,-20.47,64.0,M-MC,10.46,193.0,0.01,0.72,43.67,AR,ATH,AUTO

In [16]:
# top 5 to book for rotation from weak conviction
df_tmp = df_portfolio_features[~df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])]
df_tmp = df_tmp[~df_tmp['Criteria'].isin(['XY25','XY24','X40', 'X40N'])].sort_values(by = 'RRR Ind', ascending=False)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
1,ABB,1.54,33.35,9.16,45.57,31956.0,87245.0,348864.0,7934.00,-14.32,77.0,H-MC,18.42,125.0,2.73,2.47,54.92,AR,NTT,ELECTRICAL
25,FINCABLES,2.43,22.80,69.31,107.91,125663.0,33662.0,181306.0,1641.55,10.60,70.0,M-SC,3.55,220.0,0.27,1.29,36.40,OX40N,ATH,CABLES
66,SONACOMS,0.66,0.40,38.54,39.09,39142.0,402.0,101561.0,804.02,-20.47,64.0,M-MC,10.46,193.0,0.01,0.72,43.67,AR,ATH,AUTO
84,ZYDUSLIFE,-0.61,-1.85,38.19,35.63,78555.0,-3878.0,205696.0,1286.17,-14.41,59.0,H-MC,4.92,120.0,-0.05,1.46,11.36,AR,ATH,PHARMA
39,INDIAMART,0.39,-5.75,119.34,106.72,138721.0,-7096.0,116240.0,4810.62,-57.42,64.0,H-SC,11.90,140.0,-0.05,0.82,11.68,AR,ATH,MISC

In [17]:
# top 5 to accumulate based on lowest RSI_14
df_tmp = df_portfolio_features[df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])].sort_values(by = 'RSI_14', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
2,ABBOTINDIA,-0.12,-14.39,37.91,18.07,58048.0,-25735.0,153120.0,35195.0,-27.11,40.0,X-MC,11.80,58.0,-0.44,1.09,0.14,X40,ATH,PHARMA
37,ICICIPRULI,-2.87,-10.33,45.78,30.73,80874.0,-20346.0,176659.0,790.0,-34.44,42.0,X-MC,13.01,78.0,-0.25,1.25,7.65,X40,ATH,INSURANCE
45,JIOFIN,-0.60,-21.78,64.18,28.43,149772.0,-64964.0,233363.0,387.0,-22.96,46.0,X-LC,18.71,34.0,-0.43,1.65,5.19,XY24,BTT,FINANCE
58,RELIANCE,0.00,-12.49,43.18,25.30,75939.0,-25097.0,175866.0,1952.0,-14.65,49.0,X-LC,5.58,21.0,-0.33,1.25,6.01,XY25,BTT,REFINERIES
33,HDFCBANK,0.91,-3.97,33.67,28.37,75946.0,-9326.0,225559.0,1073.0,-18.56,49.0,X-LC,17.55,26.0,-0.12,1.60,9.73,X40,BTT,BANKS

In [18]:
# top 5 to accumulate based on Spread and CumlRnk
df_tmp = df_portfolio_features[df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])]
df_tmp = df_tmp[(df_tmp['CumlRnk'] < 100)].sort_values(by = 'Spread%', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
64,SIEMENS,1.19,0.84,24.47,25.51,45920.0,1565.0,187660.0,4671.50,57.53,73.0,H-LC,2.66,51.0,0.03,1.33,32.76,AR,ATH,ELECTRICAL
23,DMART,-0.02,10.68,17.10,29.60,47239.0,26652.0,276252.0,5391.45,-6.67,70.0,X-LC,5.17,14.0,0.56,1.96,26.27,X40N,ATH,FMCG
58,RELIANCE,0.00,-12.49,43.18,25.30,75939.0,-25097.0,175866.0,1952.00,-14.65,49.0,X-LC,5.58,21.0,-0.33,1.25,6.01,XY25,BTT,REFINERIES
77,UNITDSPR,1.69,-2.31,23.63,20.77,54048.0,-5418.0,228726.0,1644.00,-13.41,57.0,X-MC,6.26,64.0,-0.10,1.62,9.11,X40N,NTT,BREWERIES
81,VOLTAS,1.70,14.40,26.91,45.20,59030.0,27618.0,219360.0,1856.00,31.03,62.0,X-MC,6.90,79.0,0.47,1.55,22.18,XY25,NTT,AC

In [19]:
# top 5 to accumulate based on lowest Gained%
df_tmp = df_portfolio_features[df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])].sort_values(by = 'Gained%', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
2,ABBOTINDIA,-0.12,-14.39,37.91,18.07,58048.0,-25735.0,153120.0,35195.0,-27.11,40.0,X-MC,11.80,58.0,-0.44,1.09,0.14,X40,ATH,PHARMA
45,JIOFIN,-0.60,-21.78,64.18,28.43,149772.0,-64964.0,233363.0,387.0,-22.96,46.0,X-LC,18.71,34.0,-0.43,1.65,5.19,XY24,BTT,FINANCE
58,RELIANCE,0.00,-12.49,43.18,25.30,75939.0,-25097.0,175866.0,1952.0,-14.65,49.0,X-LC,5.58,21.0,-0.33,1.25,6.01,XY25,BTT,REFINERIES
44,ITC,0.15,-19.54,47.98,19.06,131313.0,-66483.0,273683.0,452.0,-55.92,53.0,X-LC,19.15,1.0,-0.51,1.94,6.17,X40,NTT,FMCG
42,INFY,0.06,-10.59,50.14,34.24,140269.0,-33134.0,279754.0,1972.0,-29.61,51.0,X-LC,12.79,3.0,-0.24,1.98,7.59,X40,NTT,IT

In [20]:
# top 5 to accumulate based on lowest CurrAlloc%
df_tmp = df_portfolio_features[df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])].sort_values(by = 'CurrAlloc%', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
57,RELAXO,1.60,-59.82,279.10,52.31,162768.0,-86841.0,58319.0,1176.00,-57.22,58.0,X-SC,31.64,92.0,-0.53,0.41,30.40,X40N,NTT,FOOTWEAR
11,BATAINDIA,1.68,-50.30,172.03,35.20,110017.0,-64718.0,63952.0,2096.00,-16.10,65.0,X-SC,31.51,91.0,-0.59,0.45,26.83,X40,NTT,FOOTWEAR
53,QUESS,2.14,-19.03,114.78,73.90,99246.0,-20327.0,86466.0,424.00,-56.47,60.0,X-SC,19.32,80.0,-0.20,0.61,16.32,XY24,NTT,MISC
2,ABBOTINDIA,-0.12,-14.39,37.91,18.07,58048.0,-25735.0,153120.0,35195.00,-27.11,40.0,X-MC,11.80,58.0,-0.44,1.09,0.14,X40,ATH,PHARMA
52,PGHH,2.03,-24.06,73.83,32.01,119717.0,-51368.0,162152.0,17616.87,-48.60,52.0,X-MC,21.37,57.0,-0.43,1.15,10.91,X40,ATH,FMCG

In [21]:
# top 5 to accumulate based on CumlRnk
df_tmp = df_portfolio_features.sort_values(by = 'CumlRnk', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
44,ITC,0.15,-19.54,47.98,19.06,131313.0,-66483.0,273683.0,452.00,-55.92,53.0,X-LC,19.15,1.0,-0.51,1.94,6.17,X40,NTT,FMCG
72,TCS,0.31,-24.04,66.63,26.57,234471.0,-111373.0,351900.0,4311.59,-35.76,56.0,X-LC,16.15,2.0,-0.47,2.49,9.83,X40,ATH,IT
42,INFY,0.06,-10.59,50.14,34.24,140269.0,-33134.0,279754.0,1972.00,-29.61,51.0,X-LC,12.79,3.0,-0.24,1.98,7.59,X40,NTT,IT
74,TMPV,0.72,-18.45,67.48,36.58,195815.0,-65659.0,290182.0,600.00,-82.53,62.0,X-LC,9.64,4.0,-0.34,2.06,20.95,XY24,NTT,AUTO
32,HCLTECH,0.52,-6.83,32.91,23.83,74181.0,-16519.0,225405.0,1908.19,-1.99,54.0,X-LC,7.33,8.0,-0.22,1.60,9.45,X40,ATH,IT

In [22]:
# top 5 for average up
df_tmp = df_portfolio_features[(df_portfolio_features['Dev%_200'] > 5)].sort_values(by = 'CurrAlloc%', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
66,SONACOMS,0.66,0.40,38.54,39.09,39142.0,402.0,101561.0,804.02,-20.47,64.0,M-MC,10.46,193.0,0.01,0.72,43.67,AR,ATH,AUTO
68,SURYODAY,-0.44,-18.23,50.47,23.03,73899.0,-32650.0,146421.0,216.00,60.09,63.0,H-SC,3.70,166.0,-0.44,1.04,24.87,XR,NTT,BANKS
25,FINCABLES,2.43,22.80,69.31,107.91,125663.0,33662.0,181306.0,1641.55,10.60,70.0,M-SC,3.55,220.0,0.27,1.29,36.40,OX40N,ATH,CABLES
64,SIEMENS,1.19,0.84,24.47,25.51,45920.0,1565.0,187660.0,4671.50,57.53,73.0,H-LC,2.66,51.0,0.03,1.33,32.76,AR,ATH,ELECTRICAL
56,RECLTD,-0.31,3.28,16.91,20.74,35481.0,6655.0,209825.0,446.00,13.28,70.0,M-MC,4.85,191.0,0.19,1.49,25.04,XY25,NTT,FINANCE

In [23]:
# top 5 RSP
df_tmp = df_portfolio_features.sort_values(by = 'RSP', ascending=False)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
54,RAJESHEXPO,-4.06,-77.28,340.40,0.07,106099.0,-106008.0,31169.0,518.0,1042.68,54.0,L-SC,41.15,268.0,-1.00,0.22,46.33,OX40N,NTT,JEWELLERY
55,RAJOOENG,2.32,-34.73,113.90,39.61,76199.0,-35600.0,66900.0,143.1,-55.84,63.0,H-SC,28.98,136.0,-0.47,0.47,43.32,AR,ATH,MISC
47,KANSAINER,1.05,-31.18,64.88,13.47,120410.0,-84078.0,185589.0,340.0,-40.82,67.0,H-SC,20.11,162.0,-0.70,1.32,29.63,XY24,NTT,PAINTS
80,VBL,3.91,-2.07,38.37,35.50,118679.0,-6540.0,309302.0,670.8,-13.53,71.0,X-LC,9.77,13.0,-0.06,2.19,27.00,X40N,ATH,FMCG
65,SIS,1.95,-23.59,58.70,21.26,49800.0,-26194.0,84838.0,528.0,2002.07,74.0,H-SC,10.20,168.0,-0.53,0.60,26.14,OX40N,NTT,MISC

In [24]:
# Top N allocation
df_tmp = df_portfolio_features.sort_values(by = 'CurrAlloc%', ascending=False)
top_n_values = [10, 25, 50]

sum_df = pd.DataFrame({
    'Top_N': top_n_values,
    'Sum_Alloc%': [df_tmp['CurrAlloc%'].head(n).sum() for n in top_n_values]
})

sum_df

   Top_N  Sum_Alloc%
0     10       20.95
1     25       46.07
2     50       78.33

In [25]:
# market-cap-wise allocation
df_tmp = df_portfolio_features[cols]
df_tmp.groupby(df_tmp['Conviction'].str[-2:])['CurrAlloc%'].sum().sort_values(ascending=False)

Conviction
SC    43.82
MC    30.42
LC    25.76
Name: CurrAlloc%, dtype: float64

In [26]:
# criteria-wise allocation
df_portfolio_features.groupby('Criteria')['CurrAlloc%'].sum().sort_values(ascending=False)

Criteria
XY24     27.92
X40      25.01
X40N     13.70
AR        9.61
XR        8.47
XY25      7.41
OX40N     7.08
SR        0.80
Name: CurrAlloc%, dtype: float64

In [27]:
# conviction-wise allocation
df_portfolio_features.groupby('Conviction')['CurrAlloc%'].sum().sort_values(ascending=False)

Conviction
X-LC    23.43
H-SC    22.65
X-MC    22.62
M-SC    10.46
X-SC    10.11
H-MC     5.24
M-MC     2.21
H-LC     1.33
M-LC     1.00
L-SC     0.60
L-MC     0.35
Name: CurrAlloc%, dtype: float64

In [28]:
# sector-wise stats
df_tmp = df_portfolio_features.groupby('Category')[['CurrAlloc%', 'Current', 'Current P/L', 'FTT Amt']].sum().sort_values(by=['Current', 'Current P/L'], ascending=False)
df_tmp['Current P/L%'] = round(df_tmp['Current P/L'] * 100 / df_tmp['Current'], 2)
df_tmp['FTT%'] = round(df_tmp['FTT Amt'] * 100 / df_tmp['Current'], 2)
cols = ['CurrAlloc%', 'Current P/L%', 'FTT%']
df_tmp[cols].sort_values(by=['CurrAlloc%'], ascending=False)

               CurrAlloc%  Current P/L%    FTT%
Category
FMCG                15.24        -16.20   57.43
IT                  11.79        -35.27  104.11
FINANCE             11.26        -16.05   66.52
MISC                 7.25        -30.84   87.68
ELECTRICAL           6.94          1.13   36.73
PAINTS               5.56        -25.76   47.60
BANKS                4.66        -17.14   76.60
INSURANCE            4.61         -4.13   39.76
PHARMA               3.94         -6.00   39.36
AUTO                 3.91        -18.81   65.95
AC                   2.09         -7.99   37.27
HEALTHCARE           1.95        -30.17   64.14
APPARELS             1.90         -0.10   34.25
FOOTWEAR             1.89        -65.35  131.65
TRAVEL               1.85        -71.20  156.93
DURABLES             1.83        -50.01   86.50
BREWERIES            1.62         -2.37   23.63
REALTY               1.50         -4.81   22.03
CERAMICS             1.38        -57.07  104.79
CABLES               1.29         18.57   69.31
REFINERIES           1.25        -14.27   43.18
CEMENT               1.23        -54.97  170.91
ENGINEERING          1.20        -43.63  109.32
JEWELLERY            1.12       -101.79  171.90
CHEMICALS            1.10        -71.10  210.69
ENTERTAINMENT        0.80        -70.97  172.93
TEXTILES             0.46        -42.39   83.00
HOTELS               0.38       -112.35  187.25

In [29]:
# money to be made criteria-wise
df_portfolio_features.groupby('Criteria')['FTT Amt'].agg(['sum', 'count']).sort_values(by='sum', ascending=False)

                sum  count
Criteria
XY24      3658716.0     21
X40       1644374.0     16
XR        1296143.0     12
AR        1214697.0     10
X40N       987565.0      9
OX40N      795162.0     10
XY25       395451.0      5
SR         305862.0      2

In [30]:
# money to be made conviction-wise
df_portfolio_features.groupby('Conviction')['FTT Amt'].agg(['sum', 'count']).sort_values(by='sum', ascending=False)

                  sum  count
Conviction
H-SC        3596332.0     24
X-MC        1540941.0     15
X-LC        1469509.0     13
M-SC        1444534.0     14
X-SC        1376999.0      9
H-MC         339128.0      3
L-SC         206225.0      2
M-LC         150226.0      1
M-MC          74623.0      2
L-MC          53533.0      1
H-LC          45920.0      1

In [31]:
# money to be made criteria and conviction-wise
df_portfolio_features.groupby(['Conviction', 'Criteria'])['FTT Amt'].agg(['sum', 'count']).sort_values(by='sum', ascending=False)

                           sum  count
Conviction Criteria
H-SC       XY24      1185339.0      6
           AR         945459.0      5
M-SC       XY24       849220.0      6
X-SC       XY24       819541.0      4
X-LC       X40        816374.0      7
H-SC       XR         814925.0      7
X-MC       X40        626752.0      7
           X40N       465437.0      4
X-SC       X40N       356210.0      3
X-LC       XY24       345587.0      2
H-SC       OX40N      344747.0      4
M-SC       OX40N      344316.0      5
H-SC       SR         305862.0      2
X-MC       XY24       230412.0      2
H-MC       XY24       228617.0      1
X-MC       XY25       218340.0      2
X-SC       X40        201248.0      2
M-SC       XR         177333.0      2
X-LC       X40N       165918.0      2
M-LC       XR         150226.0      1
X-LC       XY25       141630.0      2
H-MC       AR         110511.0      2
L-SC       OX40N      106099.0      1
           XR         100126.0      1
M-SC       AR          73665.0      1
L-MC       XR          53533.0      1
H-LC       AR          45920.0      1
M-MC       AR          39142.0      1
           XY25        35481.0      1

In [32]:
# notebook execution time

end_time = time.time()
execution_time = round(end_time - start_time, 0)
print(f"Notebook execution time: {execution_time} seconds")

Notebook execution time: 37.0 seconds