<a href="https://colab.research.google.com/github/ankit-rathi/Quantvesting_v2/blob/main/myStocks_Portfolio_Analysis.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
'''
!pip install pandas==2.2.2 -qq
!pip install pyxirr -qq
!pip install ta -qq
!pip install yfinance==0.2.59 -qq
'''

'\n!pip install pandas==2.2.2 -qq\n!pip install pyxirr -qq\n!pip install ta -qq\n!pip install yfinance==0.2.59 -qq\n'

In [2]:
# import libraries

import numpy as np
import pandas as pd
import datetime
import warnings
warnings.filterwarnings('ignore')
import yfinance as yfin
import ta
import matplotlib.pyplot as plt
import requests

In [3]:
# notebook start time
import time
import datetime
import pytz

start_time = time.time()

# function to print date timestamp
def print_date_time():
  tz_NY = pytz.timezone('Asia/Kolkata')
  datetime_NY = datetime.datetime.now(tz_NY)
  print("Run date time (IST):", datetime_NY.strftime("%Y-%m-%d %H:%M:%S"))

In [4]:
# function to get booked and reserved amount
def get_amt():
  # fetch the JSON data from the URL
  url = "https://raw.githubusercontent.com/ankit-rathi/Tradevesting_v1/main/data/myPortfolioAmts.json"
  response = requests.get(url)
  pf_amts = response.json()  # parse the JSON data

  # extract values from the JSON
  py_booked_amt_dm = pf_amts["py_booked_amt_dm"]
  py_booked_amt_sv = pf_amts["py_booked_amt_sv"]
  cy_booked_amt_dm = pf_amts["cy_booked_amt_dm"]
  cy_booked_amt_sv = pf_amts["cy_booked_amt_sv"]
  reserve_amt_dm = pf_amts["reserve_amt_dm"]
  reserve_amt_sv = pf_amts["reserve_amt_sv"]

  # perform calculations
  py_booked_amt = py_booked_amt_dm + py_booked_amt_sv
  cy_booked_amt = cy_booked_amt_dm + cy_booked_amt_sv
  reserve_amt = reserve_amt_dm + reserve_amt_sv
  total_booked_amt = py_booked_amt + cy_booked_amt

  return total_booked_amt, reserve_amt, cy_booked_amt, py_booked_amt

gen_output = 0

In [5]:
# function to format the amount
def format_amt(number):
    abs_number = abs(number)

    if abs_number >= 1_00_00_000:  # Crores
        formatted_amt = f"{number / 1_00_00_000:.2f} C"
    elif abs_number >= 1_00_000:  # Lakhs
        formatted_amt = f"{number / 1_00_000:.2f} L"
    elif abs_number >= 1_000:  # Thousands
        formatted_amt = f"{number / 1_000:.2f} K"
    else:
        formatted_amt = f"{number:.2f}"

    return formatted_amt

# function to set start and end date
def get_start_end_date():
  start_date = (datetime.date.today() + datetime.timedelta(days=-365)).strftime('%Y-%m-%d')
  end_date = (datetime.date.today() + datetime.timedelta(days=1)).strftime('%Y-%m-%d')
  return start_date, end_date

# function to fetch my portfolio csv
def get_mypfs_df():
  mypfs_df = pd.read_csv('https://raw.githubusercontent.com/ankit-rathi/Tradevesting_v1/main/data/myPortfolioStocks.csv')
  return mypfs_df

# function to fetch my prospects csv
def get_mypps_df():
  mypps_df = pd.read_csv('https://raw.githubusercontent.com/ankit-rathi/Tradevesting_v1/main/data/myProspectsScrips.csv')
  return mypps_df

# function to fetch screener data
def get_myscreen_df():
  myscreen_df = pd.read_csv('https://raw.githubusercontent.com/ankit-rathi/Tradevesting_v1/main/data/myScreenerDB.csv')
  return myscreen_df

# function to fetch momentum data
def get_myinvmt_df():
  myinvmt_df = pd.read_csv('https://raw.githubusercontent.com/ankit-rathi/Tradevesting_v1/main/data/myInvestments.csv')
  return myinvmt_df

# function to get the stock ids
def get_stock_ids(df_pf):
  stock_n100 = df_pf['Symbol'].unique()

  exclude = ['CADILAHC','MMTC', 'MASFIN']

  stock_ids = df_pf[~df_pf['Symbol'].isin(exclude) ]['Symbol'].unique()

  #mypf = mypf[mypf.Forecast.notnull()]
  #stock_ids = mypf['Symbol'].unique()

  #stock_ids.sort()
  return stock_ids

# get features from screener data
def get_screener_features():
  myscreen_df = get_myscreen_df()
  cols = ['Symbol', 'EPS', 'MedPE', 'ROCE%', 'ROE%', 'CapType']
  return myscreen_df[cols]

# get relative strength
def get_relative_strength(stock_list):

    # Dictionary to store stock tickers and their corresponding percentage price change
    stock_changes = {}

    # Loop through each stock and fetch its price data
    for stock in stock_list:
        try:
            # Download the stock data for the given date range
            stock_data = yfin.Ticker(stock + '.NS').history(period='1mo', interval='1d')[map(str.title, ['open', 'close', 'low', 'high', 'volume'])]

            # Calculate the percentage change for the stock
            if len(stock_data) > 0:
                start_price = stock_data['Close'].iloc[0]
                end_price = stock_data['Close'].iloc[-1]
                percent_change = round(((end_price - start_price) / start_price) * 100, 2)
                stock_changes[stock] = percent_change
            else:
                stock_changes[stock] = np.nan  # If no data is available, set to NaN

        except Exception as e:
            print(f"Error fetching data for {stock}: {e}")
            stock_changes[stock] = np.nan

    # Create a DataFrame with stock tickers and their percentage changes
    df = pd.DataFrame(list(stock_changes.items()), columns=['Symbol', 'Percent_Change'])

    # Drop any stocks with missing data (NaN values)
    df = df.dropna()

    # Calculate the percentile rank based on percentage change
    df['RSP'] = round(df['Percent_Change'].rank(pct=True) * 100, 2)
    cols = ['Symbol', 'RSP']
    df = df[cols]
    # Sort by percentile rank (optional)
    df = df.sort_values(by='RSP', ascending=False).reset_index(drop=True)

    return df

In [6]:
# function to get stock technicals
def stock_prec_dev(stock_symbol):
    #stock_symbol = 'ULTRACEMCO.NS'
    short_window = 20
    mid_window = 50
    long_window = 200
    moving_avg = 'SMA'

    start = datetime.datetime(*map(int, start_date.split('-')))
    end = datetime.datetime(*map(int, end_date.split('-')))

    stock_df = yfin.Ticker(stock_symbol + '.NS').history(period='max', interval='1d')[map(str.title, ['open', 'close', 'low', 'high', 'volume'])]

    stock_df['Max'] = round(max(stock_df['Close']),2)
    stock_df = stock_df[(stock_df.index <= end_date) & (stock_df.index >= start_date)]
    stock_df['200_SMA'] = round(stock_df['Close'].rolling(window = 200, min_periods = 1).mean(),0)
    stock_df['Dev%_200'] = round((stock_df['Close'] - stock_df['200_SMA'])*100/stock_df['200_SMA'],2)
    stock_df.dropna(axis = 0, inplace = True) # remove any null rows

    stock_df['20_SMA'] = stock_df['Close'].rolling(window=20).mean()
    stock_df['50_SMA'] = stock_df['Close'].rolling(window=50).mean()
    stock_df['Symbol'] = stock_symbol

    stock_df['Close'] = round(stock_df['Close'],2)
    stock_df['Min'] = round(min(stock_df['Close']),2)
    stock_df['RSI_14'] = ta.momentum.RSIIndicator(close=stock_df['Close'], window=14).rsi()
    stock_df['RSI_14'] = round(stock_df['RSI_14'],0)
    stock_df['Prev_Close'] = stock_df['Close'].shift(1)
    stock_df.drop(['Open', 'Low', 'High', 'Volume'], axis=1, inplace=True)
    stock_df = stock_df.tail(1)

    max_SMA = max(stock_df['20_SMA'].item(), stock_df['50_SMA'].item(), stock_df['200_SMA'].item())
    min_SMA = min(stock_df['20_SMA'].item(), stock_df['50_SMA'].item(), stock_df['200_SMA'].item())
    ABS_Spread = max_SMA - min_SMA
    stock_df['Spread%'] = round((ABS_Spread / stock_df['200_SMA'].item()) * 100,2)

    return stock_df

# function to compute stock attributes
def get_common_features(stock_ids, df_mypf):

  df_prec_dev = pd.DataFrame()
  df_tmp = get_screener_features()
  df_rs = get_relative_strength(stock_ids)

  for stock_id in stock_ids:
      tmp = stock_prec_dev(stock_id)
      tmp = tmp.reset_index()
      df_prec_dev = pd.concat([df_prec_dev, tmp], ignore_index = True)
  df_prec_dev = pd.merge(df_prec_dev, df_mypf, on= 'Symbol')
  df_prec_dev = pd.merge(df_prec_dev, df_tmp, on= 'Symbol', how='left')
  df_prec_dev = pd.merge(df_prec_dev, df_rs, on= 'Symbol', how='left')
  #print(df_prec_dev.columns)
  df_prec_dev['Curr_PE'] = round(df_prec_dev['Close']/df_prec_dev['EPS'],1)
  df_prec_dev['Dev%_PE'] = round((df_prec_dev['Curr_PE'] - df_prec_dev['MedPE'])*100/df_prec_dev['MedPE'],2)
  df_prec_dev['Conviction'] = df_prec_dev['Conviction'] + '-' + df_prec_dev['CapType']
  return df_prec_dev

# function to arrange stock features
def arrange_features(df_stocks, common_cols, diff_cols):
  df_stocks_common = df_stocks[common_cols].drop_duplicates()
  df_stocks_diff = df_stocks[diff_cols]
  df_stocks_diff['Investment'] = df_stocks_diff['AvgCost'] * df_stocks_diff['Shares']
  df_stocks_diff = df_stocks_diff.groupby(['Symbol'])[['Shares', 'Investment']].aggregate(['sum']).reset_index()
  df_stocks_diff.columns = ['Symbol', 'Shares', 'Investment']
  df_stocks_diff['AvgCost'] = round(df_stocks_diff['Investment']/df_stocks_diff['Shares'],2)
  df_stocks = pd.merge(df_stocks_diff, df_stocks_common, on='Symbol')
  return df_stocks

# plot fact distribution across dimension
def plot_pie_chart(df, dimension, fact):
  # grouping the data by category and calculating the sum of fact for each type
  grouped_data = df.groupby(dimension)[fact].sum()

  # sorting the grouped data in descending order
  grouped_data = grouped_data.sort_values(ascending=False)

  # creating a pie chart
  grouped_data.plot.pie(autopct='%1.1f%%', startangle=90, figsize=(6, 6))

  # adding a title and displaying the plot
  plt.title(f'{dimension} {fact} Distribution')
  plt.ylabel('')  # To hide the y-label
  plt.show()

In [7]:
# function to get portfolio features

def get_portfolio_features(df_common_features):

  print_date_time()
  print('-------------------')

  #df_common_features["Target"] = df_common_features["Target"].fillna(df_common_features["Max"])
  df_common_features['NTT'] = np.where(df_common_features['Strategy']== 'NTT', df_common_features["Target"], df_common_features['Max'])
  df_common_features['LTT'] = np.where(df_common_features['Strategy']== 'BTT', df_common_features["Target"], df_common_features['Max'])
  df_common_features['BOL'] = df_common_features['Min']

  tmp_df = df_common_features[df_common_features['Symbol'].isin(mypf_df[mypf_df['InPortfolio'] != 'NA'].Symbol.values)]
  print('qualified stocks: '+str(len(tmp_df['Symbol'].unique())))
  tmp_df1 = tmp_df[tmp_df['LatestQtr'] == 1]
  print('with latest results: '+str(len(tmp_df1['Symbol'].unique())))
  tmp_df1 = tmp_df1[tmp_df1['StarStock'] == 1]
  print('still star stocks: '+str(len(tmp_df1['Symbol'].unique())))
  tmp_df['Investment'] = tmp_df['AvgCost'] * tmp_df['Shares']
  tmp_df['Current'] = round(tmp_df['Close'] * tmp_df['Shares'],0)
  tmp_df['Previous'] = tmp_df['Prev_Close'] * tmp_df['Shares']
  tmp_df['EstimatedST'] = tmp_df['NTT'] * tmp_df['Shares']
  tmp_df['EstimatedLT'] = tmp_df['LTT'] * tmp_df['Shares']
  tmp_df['Current P/L'] = round((tmp_df['Current'] - tmp_df['Investment']),0)
  tmp_df['Today P/L%'] = round((tmp_df['Current'] - tmp_df['Previous'])*100/tmp_df['Previous'],2)
  tmp_df['Current P/L%'] = round((tmp_df['Current'] - tmp_df['Investment'])*100/tmp_df['Investment'],2)
  tmp_df['EstimatedST P/L%'] = round((tmp_df['EstimatedST'] - tmp_df['Investment'])*100/tmp_df['Investment'],2)
  tmp_df['EstimatedLT P/L%'] = round((tmp_df['EstimatedLT'] - tmp_df['Investment'])*100/tmp_df['Investment'],2)
  tmp_df['NTT%'] = round((tmp_df['NTT'] - tmp_df['Close'])*100/tmp_df['Close'],2)
  tmp_df['LTT%'] = round((tmp_df['LTT'] - tmp_df['Close'])*100/tmp_df['Close'],2)
  tmp_df['Gained%'] = round((tmp_df['Close'] - tmp_df['BOL'])*100/tmp_df['BOL'],2)
  investment = round(sum(tmp_df['AvgCost']*tmp_df['Shares']),0)
  current = round(sum(tmp_df['Close']*tmp_df['Shares']),0)
  tmp_df['InitAlloc%'] = round(tmp_df['Investment']*100/investment,2)
  tmp_df['CurrAlloc%'] = round(tmp_df['Current']*100/current,2)
  tmp_df['FTT'] = tmp_df['LTT']
  tmp_df.loc[tmp_df['Strategy'] == 'NTT', 'FTT'] = tmp_df['NTT']
  tmp_df['FTT%'] = tmp_df['LTT%']
  tmp_df.loc[tmp_df['Strategy'] == 'NTT', 'FTT%'] = tmp_df['NTT%']
  tmp_df['FTT Amt'] = round(tmp_df['FTT%'] * tmp_df['Current']/100,0)
  tmp_df['OTT%'] = round((tmp_df['FTT'] - tmp_df['AvgCost'])*100/tmp_df['AvgCost'],2)
  tmp_df['RRR Ind'] = round(tmp_df['Current P/L']/tmp_df['FTT Amt'],2)
  tmp_df['Risk Ind'] = round(tmp_df['Current P/L%']*tmp_df['CurrAlloc%'],0)

  return tmp_df

# function to print portfolio features
def print_portfolio_stats(df_portfolio_features, myinvmt_df):
  from pyxirr import xirr

  total_booked_amt, reserve_amt, cy_booked_amt, py_booked_amt = get_amt()

  dates = myinvmt_df['Date'].values
  dates = np.append(dates, datetime.date.today().strftime('%d-%b-%y'))
  investment = myinvmt_df['Investment'].values
  dates= pd.to_datetime(dates)

  current = round(sum(df_portfolio_features['Close']*df_portfolio_features['Shares']),0) + reserve_amt
  investment_xirr = np.append(investment, current)
  cagr = round(xirr(pd.DataFrame({"dates": dates, "amounts": investment_xirr}))*100,2)

  investment = -sum(investment)
  invested = round(sum(df_portfolio_features['AvgCost']*df_portfolio_features['Shares']),0) + reserve_amt
  previous = round(sum(df_portfolio_features['Prev_Close']*df_portfolio_features['Shares']),0) + reserve_amt
  cy_invested = investment + py_booked_amt

  today_pnl_amount = current-previous
  today_pnl_percentage = round((current-previous)*100/previous,2)

  curr_pnl_amount = current-invested
  curr_pnl_percentage = round((curr_pnl_amount)*100/(cy_invested),2)

  cy_pnl_amount = cy_booked_amt + curr_pnl_amount
  cy_pnl_percentage = round((cy_pnl_amount)*100/cy_invested,2)

  overall_pnl_amount = total_booked_amt + curr_pnl_amount
  overall_pnl_percentage = round((overall_pnl_amount)*100/investment,2)

  estimate_st = round(sum(df_portfolio_features['FTT']*df_portfolio_features['Shares']),0)  + reserve_amt
  est_st_pnl_amount = estimate_st-current
  est_st_pnl_percentage = round((est_st_pnl_amount)*100/current,2)

  estimate_lt = round(sum(df_portfolio_features['LTT']*df_portfolio_features['Shares']),0)  + reserve_amt
  est_lt_pnl_amount = estimate_lt-current
  est_lt_pnl_percentage = round((est_lt_pnl_amount)*100/current,2)

  total_profit = round(sum(df_portfolio_features[df_portfolio_features['Current P/L%'] > 0]['Current']) - sum(df_portfolio_features[df_portfolio_features['Current P/L%'] > 0]['Investment']),0)
  total_loss = round(sum(df_portfolio_features[df_portfolio_features['Current P/L%'] < 0]['Current']) - sum(df_portfolio_features[df_portfolio_features['Current P/L%'] < 0]['Investment']),0)

  cy_booked_percentage = round((cy_booked_amt)*100/current,2)
  py_booked_percentage = round((py_booked_amt)*100/investment,2)
  total_booked_percentage = round((total_booked_amt)*100/investment,2)

  print('-------------------')
  print('Initial Investment: ', format_amt(investment))
  print('CY Investment: ', format_amt(cy_invested))
  print('Reserve: ', format_amt(reserve_amt))
  print('Current: ',  format_amt(current))
  print('-------------------')
  print('Today PnL: '+ '{} ({}%)'.format(format_amt(today_pnl_amount), today_pnl_percentage))
  print('Current PnL: '+ '{} ({}%)'.format(format_amt(curr_pnl_amount), curr_pnl_percentage))
  print('CY Booked + Current PnL: '+ '{} ({}%)'.format(format_amt(cy_pnl_amount), cy_pnl_percentage))
  print('-------------------')
  print('Total profit: ', format_amt(total_profit))
  print('Total loss: ', format_amt(total_loss))
  print('-------------------')
  print('Total Booked + Current PnL: '+ '{} ({}%)'.format(format_amt(overall_pnl_amount), overall_pnl_percentage))
  print('Total Booked PnL: '+ '{} ({}%)'.format(format_amt(total_booked_amt), total_booked_percentage))
  print('Curr Year Booked PnL: '+ '{} ({}%)'.format(format_amt(cy_booked_amt), cy_booked_percentage))
  print('Prev Year Booked PnL: '+ '{} ({}%)'.format(format_amt(py_booked_amt), py_booked_percentage))
  print('===================')
  print('Est FTT: ',  format_amt(estimate_st))
  print('Est FTT PnL: '+ '{} ({}%)'.format(format_amt(est_st_pnl_amount), est_st_pnl_percentage))

  print('===================')
  print('Deployed: ', format_amt(investment))

  print('Current: ', format_amt(current))

  print('CAGR/XIRR %: '+'{}%'.format(cagr))

In [8]:
# get start and end date
start_date, end_date = get_start_end_date()

# get portfolio and prospects data
mypfs_df = get_mypfs_df()
mypps_df = get_mypps_df()
myinvmt_df = get_myinvmt_df()

# merge above datasets
mypf_df = pd.merge(mypfs_df, mypps_df, on="Symbol")

# seggregate dm and sv portfolio
dm_pf = mypf_df[mypf_df['InPortfolio'] == 'DM']
sv_pf = mypf_df[mypf_df['InPortfolio'] == 'SV']

# build portfolio stock dataframe
dm_stocks = get_stock_ids(dm_pf)
sv_stocks = get_stock_ids(sv_pf)
df_stocks = pd.concat([dm_pf,sv_pf], ignore_index = True)

# arrange common and diff stock features
common_cols = ['Symbol', 'Target', 'Criteria', 'Strategy', 'CumlRnk', 'LatestQtr', 'StarStock', 'Conviction', 'Category', 'InFolio', 'XIRR', 'MBQ']
diff_cols = ['Symbol', 'AvgCost', 'Shares']
df_stocks = arrange_features(df_stocks, common_cols, diff_cols)

# get common features
stock_ids = df_stocks['Symbol'].values
df_common_features = get_common_features(stock_ids, df_stocks)

df_common_features.reset_index(drop=True, inplace=True)
df_common_features.drop(['Date'], axis=1, inplace=True)
# get and print portfolio features
df_portfolio_features = get_portfolio_features(df_common_features)

print_portfolio_stats(df_portfolio_features, myinvmt_df)

df = df_portfolio_features
#plot_pie_chart(df, 'CapType', 'Current')
list_ox40n = list(df[df['MBQ'].str.contains('OX40N', na=False)]['Symbol'].values)

Run date time (IST): 2026-04-17 13:57:56
-------------------
qualified stocks: 86
with latest results: 26
still star stocks: 16

-------------------
Initial Investment:  1.36 C
CY Investment:  1.62 C
Reserve:  1.61 K
Current:  1.44 C
-------------------
Today PnL: 2.21 L (1.55%)
Current PnL: -32.76 L (-20.16%)
CY Booked + Current PnL: -16.87 L (-10.38%)
-------------------
Total profit:  2.59 L
Total loss:  -35.35 L
-------------------
Total Booked + Current PnL: 10.11 L (7.46%)
Total Booked PnL: 42.87 L (31.64%)
Curr Year Booked PnL: 15.89 L (11.01%)
Prev Year Booked PnL: 26.98 L (19.91%)
===================
Est FTT:  2.48 C
Est FTT PnL: 1.04 C (71.7%)
===================
Deployed:  1.36 C
Current:  1.44 C
CAGR/XIRR %: 3.06%

In [9]:
# top 5 near their targets
cols = ['Symbol', 'Today P/L%', 'Current P/L%', 'FTT%', 'OTT%', 'FTT Amt', 'Current P/L', 'Current', 'FTT', 'Dev%_PE', 'RSI_14','Conviction', 'Spread%',  'CumlRnk', 'RRR Ind', 'CurrAlloc%', 'Gained%', 'Criteria', 'Strategy', 'Category']
df_tmp = df_portfolio_features[~df_portfolio_features['Symbol'].isin(['ENRIN','BLUSPRING','DIGITIDE'])]
df_tmp = df_tmp.sort_values(by = 'FTT Amt', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
5,ANGELONE,10.11,32.05,-5.96,24.18,-24004.0,97750.0,402750.0,303.00,-80.83,79.0,X-SC,2.19,97.0,-4.07,2.79,54.08,X40N,NTT,FINANCE
50,MASFIN,-0.58,-3.29,25.71,21.57,24362.0,-3225.0,94755.0,397.04,-16.44,56.0,H-SC,3.85,167.0,-0.13,0.66,22.45,XR,ATH,FINANCE
77,TTKPRESTIG,3.01,-35.46,55.09,0.09,35832.0,-35735.0,65042.0,770.00,50.91,55.0,M-SC,23.32,250.0,-1.00,0.45,15.82,OX40N,NTT,DURABLES
67,SONACOMS,1.77,2.27,36.01,39.09,37253.0,2292.0,103451.0,804.02,-18.98,69.0,M-MC,9.17,193.0,0.06,0.72,46.35,AR,ATH,AUTO
57,RECLTD,3.10,1.65,18.77,20.74,38765.0,3355.0,206525.0,446.00,11.33,68.0,M-MC,6.01,191.0,0.09,1.43,23.07,XY25,NTT,FINANCE

In [10]:
# top 5 today
df_tmp = df_portfolio_features.sort_values(by = 'Today P/L%', ascending=False)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
5,ANGELONE,10.11,32.05,-5.96,24.18,-24004.0,97750.0,402750.0,303.00,-80.83,79.0,X-SC,2.19,97.0,-4.07,2.79,54.08,X40N,NTT,FINANCE
62,SATIN,10.10,-1.36,53.93,51.83,146969.0,-3766.0,272518.0,274.00,-11.96,78.0,H-SC,1.58,159.0,-0.03,1.89,32.76,XY24,NTT,FINANCE
20,COLPAL,5.59,-20.72,78.49,41.51,163887.0,-54565.0,208800.0,3726.84,-4.06,63.0,X-MC,12.84,62.0,-0.33,1.45,16.73,XY25,ATH,FMCG
83,WHIRLPOOL,5.49,-28.25,153.56,81.92,126477.0,-32435.0,82363.0,2270.00,-58.03,61.0,M-SC,25.23,210.0,-0.26,0.57,15.70,XR,NTT,DURABLES
35,HINDUNILVR,4.60,-12.96,30.59,13.67,68445.0,-33313.0,223750.0,2922.00,-35.45,60.0,X-LC,11.74,9.0,-0.49,1.55,9.03,XY25,NTT,FMCG

In [11]:
# bottom 5 today
df_tmp = df_portfolio_features.sort_values(by = 'Today P/L%', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
84,WIPRO,-2.93,-16.29,105.79,72.27,150056.0,-27605.0,141843.0,420.0,-24.55,53.0,M-LC,16.26,98.0,-0.18,0.98,8.82,XR,NTT,IT
29,GREENPANEL,-1.98,-42.69,149.77,43.14,157139.0,-78158.0,104920.0,537.0,135.14,63.0,M-SC,23.55,225.0,-0.50,0.73,26.03,XY24,NTT,MISC
80,VALIANTORG,-1.96,-41.39,197.15,74.15,189033.0,-67722.0,95883.0,838.0,-272.18,64.0,H-SC,19.36,145.0,-0.36,0.66,42.69,XR,NTT,CHEMICALS
55,RAJESHEXPO,-1.77,-75.89,315.06,0.07,104197.0,-104105.0,33072.0,518.0,1112.12,61.0,L-SC,42.51,268.0,-1.00,0.23,55.26,OX40N,NTT,JEWELLERY
69,SURYODAY,-1.20,-19.05,51.99,23.03,75361.0,-34119.0,144952.0,216.0,57.89,61.0,H-SC,4.00,166.0,-0.45,1.00,23.62,XR,NTT,BANKS

In [12]:
# top 5 to exit based on CumlRnk
df_tmp = df_portfolio_features[~df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])]
df_tmp = df_tmp[(df_tmp['Current P/L%'] > -1) & (df_tmp['Current P/L%'] < 1)].sort_values(by = 'CumlRnk', ascending=False)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
85,ZYDUSLIFE,0.64,-0.33,36.08,35.63,75363.0,-696.0,208878.0,1286.17,-13.06,65.0,H-MC,5.42,120.0,-0.01,1.45,14.96,AR,ATH,PHARMA

In [13]:
# OX40N stocks to exit
df_tmp = df_portfolio_features[(df_portfolio_features['Symbol'].isin(list_ox40n))].sort_values(by = 'Current P/L%', ascending=False)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
26,FINCABLES,3.40,19.64,73.78,107.91,130325.0,28996.0,176640.0,1641.55,7.56,67.0,M-SC,2.47,220.0,0.22,1.22,32.89,OX40N,ATH,CABLES
66,SIS,0.94,-25.91,63.67,21.26,52377.0,-28769.0,82263.0,528.00,1938.34,69.0,H-SC,12.11,168.0,-0.55,0.57,22.31,OX40N,NTT,MISC
18,CERA,0.87,-30.48,78.21,23.89,95642.0,-53614.0,122289.0,9475.00,-32.94,68.0,H-SC,14.62,153.0,-0.56,0.85,17.52,OX40N,NTT,CERAMICS
48,KANSAINER,1.44,-32.24,67.45,13.47,123255.0,-86931.0,182736.0,340.00,-41.86,65.0,H-SC,21.80,162.0,-0.71,1.27,27.64,XY24,NTT,PAINTS
72,TATAELXSI,0.01,-33.79,99.41,32.03,86771.0,-44549.0,87286.0,9161.00,-17.17,60.0,H-SC,19.36,158.0,-0.51,0.60,15.53,OX40N,NTT,IT

In [14]:
# top 5 to book for rotation
df_tmp = df_portfolio_features[(df_portfolio_features['Current P/L%'] > 20) ].sort_values(by = 'CumlRnk', ascending=False)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
1,ABB,2.54,29.50,12.40,45.57,42012.0,77189.0,338808.0,7934.0,-16.77,74.0,H-MC,17.06,125.0,1.84,2.35,50.45,AR,NTT,ELECTRICAL
5,ANGELONE,10.11,32.05,-5.96,24.18,-24004.0,97750.0,402750.0,303.0,-80.83,79.0,X-SC,2.19,97.0,-4.07,2.79,54.08,X40N,NTT,FINANCE

In [15]:
# top 5 to monitor for exit
df_tmp = df_portfolio_features[~df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])]
df_tmp = df_tmp[(df_tmp['Current P/L%'] > 0) ].sort_values(by = 'Dev%_PE', ascending=False)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
57,RECLTD,3.10,1.65,18.77,20.74,38765.0,3355.0,206525.0,446.00,11.33,68.0,M-MC,6.01,191.0,0.09,1.43,23.07,XY25,NTT,FINANCE
26,FINCABLES,3.40,19.64,73.78,107.91,130325.0,28996.0,176640.0,1641.55,7.56,67.0,M-SC,2.47,220.0,0.22,1.22,32.89,OX40N,ATH,CABLES
1,ABB,2.54,29.50,12.40,45.57,42012.0,77189.0,338808.0,7934.00,-16.77,74.0,H-MC,17.06,125.0,1.84,2.35,50.45,AR,NTT,ELECTRICAL
67,SONACOMS,1.77,2.27,36.01,39.09,37253.0,2292.0,103451.0,804.02,-18.98,69.0,M-MC,9.17,193.0,0.06,0.72,46.35,AR,ATH,AUTO

In [16]:
# top 5 to book for rotation from weak conviction
df_tmp = df_portfolio_features[~df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])]
df_tmp = df_tmp[~df_tmp['Criteria'].isin(['XY25','XY24','X40', 'X40N'])].sort_values(by = 'RRR Ind', ascending=False)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
1,ABB,2.54,29.50,12.40,45.57,42012.0,77189.0,338808.0,7934.00,-16.77,74.0,H-MC,17.06,125.0,1.84,2.35,50.45,AR,NTT,ELECTRICAL
26,FINCABLES,3.40,19.64,73.78,107.91,130325.0,28996.0,176640.0,1641.55,7.56,67.0,M-SC,2.47,220.0,0.22,1.22,32.89,OX40N,ATH,CABLES
67,SONACOMS,1.77,2.27,36.01,39.09,37253.0,2292.0,103451.0,804.02,-18.98,69.0,M-MC,9.17,193.0,0.06,0.72,46.35,AR,ATH,AUTO
85,ZYDUSLIFE,0.64,-0.33,36.08,35.63,75363.0,-696.0,208878.0,1286.17,-13.06,65.0,H-MC,5.42,120.0,-0.01,1.45,14.96,AR,ATH,PHARMA
40,INDIAMART,0.53,-6.88,121.98,106.72,140101.0,-8480.0,114856.0,4810.62,-58.01,61.0,H-SC,12.51,140.0,-0.06,0.80,10.35,AR,ATH,MISC

In [17]:
# top 5 to accumulate based on lowest RSI_14
df_tmp = df_portfolio_features[df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])].sort_values(by = 'RSI_14', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
2,ABBOTINDIA,-1.06,-14.17,37.56,18.07,57658.0,-25345.0,153510.0,35195.00,-26.90,41.0,X-MC,11.77,58.0,-0.44,1.06,0.39,X40,ATH,PHARMA
34,HDFCBANK,0.57,-4.29,34.12,28.37,76702.0,-10085.0,224800.0,1073.00,-18.56,48.0,X-LC,17.25,26.0,-0.13,1.56,9.36,X40,BTT,BANKS
53,PGHH,1.31,-25.12,76.30,32.01,121988.0,-53640.0,159880.0,17616.87,-49.41,48.0,X-MC,21.59,57.0,-0.44,1.11,9.35,X40,ATH,FMCG
38,ICICIPRULI,0.34,-7.36,41.11,30.73,75030.0,-14494.0,182511.0,790.00,-32.26,49.0,X-MC,12.52,78.0,-0.19,1.26,11.21,X40,ATH,INSURANCE
59,RELIANCE,1.43,-12.54,43.27,25.30,76052.0,-25201.0,175762.0,1952.00,-14.65,49.0,X-LC,5.44,21.0,-0.33,1.22,7.33,XY25,BTT,REFINERIES

In [18]:
# top 5 to accumulate based on Spread and CumlRnk
df_tmp = df_portfolio_features[df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])]
df_tmp = df_tmp[(df_tmp['CumlRnk'] < 100)].sort_values(by = 'Spread%', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
65,SIEMENS,4.03,-0.39,26.00,25.51,48196.0,-725.0,185370.0,4671.50,55.66,72.0,H-LC,1.81,51.0,-0.02,1.28,31.94,AR,ATH,ELECTRICAL
5,ANGELONE,10.11,32.05,-5.96,24.18,-24004.0,97750.0,402750.0,303.00,-80.83,79.0,X-SC,2.19,97.0,-4.07,2.79,54.08,X40N,NTT,FINANCE
24,DMART,4.47,11.21,16.54,29.60,45911.0,27978.0,277578.0,5391.45,-6.22,72.0,X-LC,4.11,14.0,0.61,1.92,26.88,X40N,ATH,FMCG
59,RELIANCE,1.43,-12.54,43.27,25.30,76052.0,-25201.0,175762.0,1952.00,-14.65,49.0,X-LC,5.44,21.0,-0.33,1.22,7.33,XY25,BTT,REFINERIES
78,UNITDSPR,3.69,-4.44,26.38,20.77,59022.0,-10406.0,223738.0,1644.00,-15.25,52.0,X-MC,6.39,64.0,-0.18,1.55,6.73,X40N,NTT,BREWERIES

In [19]:
# top 5 to accumulate based on lowest Gained%
df_tmp = df_portfolio_features[df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])].sort_values(by = 'Gained%', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
2,ABBOTINDIA,-1.06,-14.17,37.56,18.07,57658.0,-25345.0,153510.0,35195.0,-26.90,41.0,X-MC,11.77,58.0,-0.44,1.06,0.39,X40,ATH,PHARMA
45,ITC,1.02,-19.27,47.47,19.06,130364.0,-65542.0,274624.0,452.0,-55.52,54.0,X-LC,19.39,1.0,-0.50,1.90,6.53,X40,NTT,FMCG
78,UNITDSPR,3.69,-4.44,26.38,20.77,59022.0,-10406.0,223738.0,1644.0,-15.25,52.0,X-MC,6.39,64.0,-0.18,1.55,6.73,X40N,NTT,BREWERIES
59,RELIANCE,1.43,-12.54,43.27,25.30,76052.0,-25201.0,175762.0,1952.0,-14.65,49.0,X-LC,5.44,21.0,-0.33,1.22,7.33,XY25,BTT,REFINERIES
43,INFY,-0.58,-10.72,50.36,34.24,140681.0,-33538.0,279350.0,1972.0,-29.61,50.0,X-LC,13.41,3.0,-0.24,1.94,7.43,X40,NTT,IT

In [20]:
# top 5 to accumulate based on lowest CurrAlloc%
df_tmp = df_portfolio_features[df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])].sort_values(by = 'CurrAlloc%', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
58,RELAXO,1.65,-59.92,279.97,52.31,162903.0,-86974.0,58186.0,1176.00,-57.31,58.0,X-SC,32.47,92.0,-0.53,0.40,30.10,X40N,NTT,FOOTWEAR
12,BATAINDIA,1.59,-51.08,176.35,35.20,111014.0,-65719.0,62951.0,2096.00,-17.40,62.0,X-SC,32.69,91.0,-0.59,0.44,24.85,X40,NTT,FOOTWEAR
54,QUESS,0.69,-19.00,114.68,73.90,99204.0,-20288.0,86505.0,424.00,-56.47,62.0,X-SC,20.38,80.0,-0.20,0.60,16.37,XY24,NTT,MISC
2,ABBOTINDIA,-1.06,-14.17,37.56,18.07,57658.0,-25345.0,153510.0,35195.00,-26.90,41.0,X-MC,11.77,58.0,-0.44,1.06,0.39,X40,ATH,PHARMA
53,PGHH,1.31,-25.12,76.30,32.01,121988.0,-53640.0,159880.0,17616.87,-49.41,48.0,X-MC,21.59,57.0,-0.44,1.11,9.35,X40,ATH,FMCG

In [21]:
# top 5 to accumulate based on CumlRnk
df_tmp = df_portfolio_features.sort_values(by = 'CumlRnk', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
45,ITC,1.02,-19.27,47.47,19.06,130364.0,-65542.0,274624.0,452.00,-55.52,54.0,X-LC,19.39,1.0,-0.50,1.90,6.53,X40,NTT,FMCG
73,TCS,0.16,-24.23,67.06,26.57,235382.0,-112271.0,351002.0,4311.58,-35.76,56.0,X-LC,16.95,2.0,-0.48,2.43,9.55,X40,ATH,IT
43,INFY,-0.58,-10.72,50.36,34.24,140681.0,-33538.0,279350.0,1972.00,-29.61,50.0,X-LC,13.41,3.0,-0.24,1.94,7.43,X40,NTT,IT
75,TMPV,0.87,-18.19,66.94,36.58,194872.0,-64727.0,291114.0,600.00,-82.53,64.0,X-LC,10.62,4.0,-0.33,2.02,21.34,XY24,NTT,AUTO
33,HCLTECH,-1.12,-6.94,33.07,23.83,74453.0,-16786.0,225138.0,1908.19,-2.40,54.0,X-LC,8.15,8.0,-0.23,1.56,9.32,X40,ATH,IT

In [22]:
# top 5 for average up
df_tmp = df_portfolio_features[(df_portfolio_features['Dev%_200'] > 5)].sort_values(by = 'CurrAlloc%', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
67,SONACOMS,1.77,2.27,36.01,39.09,37253.0,2292.0,103451.0,804.02,-18.98,69.0,M-MC,9.17,193.0,0.06,0.72,46.35,AR,ATH,AUTO
69,SURYODAY,-1.20,-19.05,51.99,23.03,75361.0,-34119.0,144952.0,216.00,57.89,61.0,H-SC,4.00,166.0,-0.45,1.00,23.62,XR,NTT,BANKS
26,FINCABLES,3.40,19.64,73.78,107.91,130325.0,28996.0,176640.0,1641.55,7.56,67.0,M-SC,2.47,220.0,0.22,1.22,32.89,OX40N,ATH,CABLES
65,SIEMENS,4.03,-0.39,26.00,25.51,48196.0,-725.0,185370.0,4671.50,55.66,72.0,H-LC,1.81,51.0,-0.02,1.28,31.94,AR,ATH,ELECTRICAL
57,RECLTD,3.10,1.65,18.77,20.74,38765.0,3355.0,206525.0,446.00,11.33,68.0,M-MC,6.01,191.0,0.09,1.43,23.07,XY25,NTT,FINANCE

In [23]:
# top 5 RSP
df_tmp = df_portfolio_features.sort_values(by = 'RSP', ascending=False)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
5,ANGELONE,10.11,32.05,-5.96,24.18,-24004.0,97750.0,402750.0,303.00,-80.83,79.0,X-SC,2.19,97.0,-4.07,2.79,54.08,X40N,NTT,FINANCE
80,VALIANTORG,-1.96,-41.39,197.15,74.15,189033.0,-67722.0,95883.0,838.00,-272.18,64.0,H-SC,19.36,145.0,-0.36,0.66,42.69,XR,NTT,CHEMICALS
52,PAGEIND,2.89,-0.76,35.13,34.11,93569.0,-2029.0,266350.0,51418.65,-28.78,78.0,X-MC,15.38,55.0,-0.02,1.85,25.99,X40,ATH,APPARELS
62,SATIN,10.10,-1.36,53.93,51.83,146969.0,-3766.0,272518.0,274.00,-11.96,78.0,H-SC,1.58,159.0,-0.03,1.89,32.76,XY24,NTT,FINANCE
24,DMART,4.47,11.21,16.54,29.60,45911.0,27978.0,277578.0,5391.45,-6.22,72.0,X-LC,4.11,14.0,0.61,1.92,26.88,X40N,ATH,FMCG

In [24]:
# Top N allocation
df_tmp = df_portfolio_features.sort_values(by = 'CurrAlloc%', ascending=False)
top_n_values = [10, 25, 50]

sum_df = pd.DataFrame({
    'Top_N': top_n_values,
    'Sum_Alloc%': [df_tmp['CurrAlloc%'].head(n).sum() for n in top_n_values]
})

sum_df

   Top_N  Sum_Alloc%
0     10       21.22
1     25       45.93
2     50       77.86

In [25]:
# market-cap-wise allocation
df_tmp = df_portfolio_features[cols]
df_tmp.groupby(df_tmp['Conviction'].str[-2:])['CurrAlloc%'].sum().sort_values(ascending=False)

Conviction
SC    45.48
MC    29.47
LC    25.07
Name: CurrAlloc%, dtype: float64

In [26]:
# criteria-wise allocation
df_portfolio_features.groupby('Criteria')['CurrAlloc%'].sum().sort_values(ascending=False)

Criteria
XY24     27.12
X40      24.38
X40N     16.06
AR        9.34
XR        8.35
XY25      7.13
OX40N     6.85
SR        0.79
Name: CurrAlloc%, dtype: float64

In [27]:
# conviction-wise allocation
df_portfolio_features.groupby('Conviction')['CurrAlloc%'].sum().sort_values(ascending=False)

Conviction
X-LC    22.81
H-SC    22.12
X-MC    21.90
X-SC    12.64
M-SC    10.12
H-MC     5.08
M-MC     2.15
H-LC     1.28
M-LC     0.98
L-SC     0.60
L-MC     0.34
Name: CurrAlloc%, dtype: float64

In [28]:
# sector-wise stats
df_tmp = df_portfolio_features.groupby('Category')[['CurrAlloc%', 'Current', 'Current P/L', 'FTT Amt']].sum().sort_values(by=['Current', 'Current P/L'], ascending=False)
df_tmp['Current P/L%'] = round(df_tmp['Current P/L'] * 100 / df_tmp['Current'], 2)
df_tmp['FTT%'] = round(df_tmp['FTT Amt'] * 100 / df_tmp['Current'], 2)
cols = ['CurrAlloc%', 'Current P/L%', 'FTT%']
df_tmp[cols].sort_values(by=['CurrAlloc%'], ascending=False)

               CurrAlloc%  Current P/L%    FTT%
Category
FMCG                14.74        -17.54   59.24
FINANCE             13.82         -7.75   51.66
IT                  11.52        -35.45  104.38
MISC                 7.16        -29.89   86.31
ELECTRICAL           6.66         -0.76   39.34
PAINTS               5.29        -29.08   51.49
INSURANCE            4.52         -3.95   39.52
BANKS                4.51        -18.17   78.15
PHARMA               3.87         -5.10   38.19
AUTO                 3.84        -18.14   65.01
AC                   2.01        -10.35   40.27
HEALTHCARE           1.90        -30.08   64.03
APPARELS             1.85         -0.76   35.13
TRAVEL               1.82        -70.33  155.61
FOOTWEAR             1.82        -68.40  135.92
DURABLES             1.76        -52.05   89.04
BREWERIES            1.55         -4.65   26.38
REALTY               1.43         -7.48   25.14
CERAMICS             1.34        -58.72  106.95
CABLES               1.22         16.42   73.78
REFINERIES           1.22        -14.34   43.27
CEMENT               1.19        -55.71  172.20
ENGINEERING          1.17        -43.12  108.58
JEWELLERY            1.10       -101.09  170.95
CHEMICALS            1.09        -67.48  204.12
ENTERTAINMENT        0.80        -65.77  164.63
TEXTILES             0.45        -43.21   84.05
HOTELS               0.37       -112.73  187.77

In [29]:
# money to be made criteria-wise
df_portfolio_features.groupby('Criteria')['FTT Amt'].agg(['sum', 'count']).sort_values(by='sum', ascending=False)

                sum  count
Criteria
XY24      3683582.0     21
X40       1657283.0     16
XR        1285075.0     12
AR        1222867.0     10
X40N       981487.0     10
OX40N      802890.0     10
XY25       412018.0      5
SR         305551.0      2

In [30]:
# money to be made conviction-wise
df_portfolio_features.groupby('Conviction')['FTT Amt'].agg(['sum', 'count']).sort_values(by='sum', ascending=False)

                  sum  count
Conviction
H-SC        3598018.0     24
X-MC        1573652.0     15
X-LC        1485092.0     13
M-SC        1456620.0     14
X-SC        1358145.0     10
H-MC         346594.0      3
L-SC         204421.0      2
M-LC         150056.0      1
M-MC          76018.0      2
L-MC          53941.0      1
H-LC          48196.0      1

In [31]:
# money to be made criteria and conviction-wise
df_portfolio_features.groupby(['Conviction', 'Criteria'])['FTT Amt'].agg(['sum', 'count']).sort_values(by='sum', ascending=False)

                           sum  count
Conviction Criteria
H-SC       XY24      1198012.0      6
           AR         946924.0      5
M-SC       XY24       851485.0      6
X-LC       X40        827968.0      7
X-SC       XY24       824356.0      4
H-SC       XR         800234.0      7
X-MC       X40        627955.0      7
           X40N       474859.0      4
M-SC       OX40N      351396.0      5
H-SC       OX40N      347297.0      4
X-LC       XY24       338428.0      2
X-SC       X40N       332429.0      4
H-SC       SR         305551.0      2
X-MC       XY24       242082.0      2
H-MC       XY24       229219.0      1
X-MC       XY25       228756.0      2
X-SC       X40        201360.0      2
M-SC       XR         180620.0      2
X-LC       X40N       174199.0      2
M-LC       XR         150056.0      1
X-LC       XY25       144497.0      2
H-MC       AR         117375.0      2
L-SC       OX40N      104197.0      1
           XR         100224.0      1
M-SC       AR          73119.0      1
L-MC       XR          53941.0      1
H-LC       AR          48196.0      1
M-MC       XY25        38765.0      1
           AR          37253.0      1

In [32]:
# notebook execution time

end_time = time.time()
execution_time = round(end_time - start_time, 0)
print(f"Notebook execution time: {execution_time} seconds")

Notebook execution time: 34.0 seconds